/mnt/V8SourceCode/src/flags/flag-definitions.h File Reference
Macros
#define DEFINE_IMPLICATION(whenflag, thenflag) DEFINE_VALUE_IMPLICATION(whenflag, thenflag, true)
#define DEFINE_WEAK_IMPLICATION(whenflag, thenflag) DEFINE_WEAK_VALUE_IMPLICATION(whenflag, thenflag, true)
#define DEFINE_WEAK_NEG_IMPLICATION(whenflag, thenflag) DEFINE_WEAK_VALUE_IMPLICATION(whenflag, thenflag, false)
#define DEFINE_NEG_IMPLICATION(whenflag, thenflag) DEFINE_VALUE_IMPLICATION(whenflag, thenflag, false)
#define DEFINE_NEG_NEG_IMPLICATION(whenflag, thenflag) DEFINE_NEG_VALUE_IMPLICATION(whenflag, thenflag, false)
#define FLAG_FULL(ftype, ctype, nam, def, cmt)
#define FLAG_READONLY(ftype, ctype, nam, def, cmt)
#define FLAG_ALIAS(ftype, ctype, alias, nam)
#define DEFINE_VALUE_IMPLICATION(whenflag, thenflag, value)
#define DEFINE_WEAK_VALUE_IMPLICATION(whenflag, thenflag, value)
#define DEFINE_GENERIC_IMPLICATION(whenflag, statement)
#define DEFINE_NEG_VALUE_IMPLICATION(whenflag, thenflag, value)
#define DEFINE_NEG_VALUE_VALUE_IMPLICATION(whenflag, whenvalue, thenflag, thenvalue)
#define DEFINE_MIN_VALUE_IMPLICATION(flag, min_value)
#define DEFINE_DISABLE_FLAG_IMPLICATION(whenflag, thenflag)
#define DEFINE_REQUIREMENT(statement)
#define ENABLE_SPARKPLUG_BY_DEFAULT false
#define ARM_ARCH_DEFAULT `armv8`
#define ENABLE_LOG_COLOUR true
#define DEFINE_BOOL(nam, def, cmt) FLAG(BOOL, bool, nam, def, cmt)
#define DEFINE_BOOL_READONLY(nam, def, cmt) FLAG_READONLY(BOOL, bool, nam, def, cmt)
#define DEFINE_MAYBE_BOOL(nam, cmt) FLAG(MAYBE_BOOL, std::optional<bool>, nam, std::nullopt, cmt)
#define DEFINE_INT(nam, def, cmt) FLAG(INT, int, nam, def, cmt)
#define DEFINE_UINT(nam, def, cmt) FLAG(UINT, unsigned int, nam, def, cmt)
#define DEFINE_UINT_READONLY(nam, def, cmt) FLAG_READONLY(UINT, unsigned int, nam, def, cmt)
#define DEFINE_UINT64(nam, def, cmt) FLAG(UINT64, uint64_t, nam, def, cmt)
#define DEFINE_FLOAT(nam, def, cmt) FLAG(FLOAT, double, nam, def, cmt)
#define DEFINE_SIZE_T(nam, def, cmt) FLAG(SIZE_T, size_t, nam, def, cmt)
#define DEFINE_STRING(nam, def, cmt) FLAG(STRING, const char*, nam, def, cmt)
#define DEFINE_ALIAS_BOOL(alias, nam) FLAG_ALIAS(BOOL, bool, alias, nam)
#define DEFINE_ALIAS_INT(alias, nam) FLAG_ALIAS(INT, int, alias, nam)
#define DEFINE_ALIAS_FLOAT(alias, nam) FLAG_ALIAS(FLOAT, double, alias, nam)
#define DEFINE_ALIAS_SIZE_T(alias, nam) FLAG_ALIAS(SIZE_T, size_t, alias, nam)
#define DEFINE_ALIAS_STRING(alias, nam) FLAG_ALIAS(STRING, const char*, alias, nam)
#define DEFINE_DEBUG_BOOL DEFINE_BOOL_READONLY
#define FLAG FLAG_FULL
#define DEFINE_EXPERIMENTAL_FEATURE(nam, cmt)
#define HARMONY_INPROGRESS_BASE(V)
#define JAVASCRIPT_INPROGRESS_FEATURES_BASE(V)
#define HARMONY_INPROGRESS(V) HARMONY_INPROGRESS_BASE(V)
#define JAVASCRIPT_INPROGRESS_FEATURES(V) JAVASCRIPT_INPROGRESS_FEATURES_BASE(V)
#define HARMONY_STAGED_BASE(V)
#define JAVASCRIPT_STAGED_FEATURES_BASE(V) V(js_base_64, `Uint8Array to/from base64 and hex`)
#define HARMONY_STAGED(V) HARMONY_STAGED_BASE(V)
#define JAVASCRIPT_STAGED_FEATURES(V) JAVASCRIPT_STAGED_FEATURES_BASE(V)
#define HARMONY_SHIPPING_BASE(V) V(harmony_import_attributes, `harmony import attributes`)
#define JAVASCRIPT_SHIPPING_FEATURES_BASE(V)
#define HARMONY_SHIPPING(V) HARMONY_SHIPPING_BASE(V)
#define JAVASCRIPT_SHIPPING_FEATURES(V) JAVASCRIPT_SHIPPING_FEATURES_BASE(V)
#define FLAG_INPROGRESS_FEATURES(id, description)
#define FLAG_STAGED_FEATURES(id, description)
#define FLAG_SHIPPING_FEATURES(id, description)
#define V8_ENABLE_DOUBLE_CONST_STORE_CHECK_BOOL false
#define V8_LAZY_SOURCE_POSITIONS_BOOL false
#define V8_LITE_MODE_BOOL false
#define V8_ALLOCATION_FOLDING_BOOL false
#define V8_DISABLE_WRITE_BARRIERS_BOOL false
#define V8_ENABLE_UNCONDITIONAL_WRITE_BARRIERS_BOOL false
#define V8_SINGLE_GENERATION_BOOL false
#define V8_ENABLE_DIRECT_HANDLE_BOOL false
#define V8_ENABLE_LOCAL_OFF_STACK_CHECK_BOOL false
#define FUTURE_BOOL false
#define V8_JITLESS_BOOL false
#define V8_ALLOCATION_SITE_TRACKING_BOOL false
#define FLAG FLAG_READONLY
#define FLAG FLAG_FULL
#define V8_ENABLE_TURBOFAN_BOOL false
#define DEFINE_SLOW_TRACING_BOOL DEFINE_BOOL_READONLY
#define DEFAULT_MAX_POLYMORPHIC_MAP_COUNT 4
#define V8_SHORT_BUILTIN_CALLS_BOOL false
#define REGEXP_PEEPHOLE_OPTIMIZATION_BOOL true
#define V8_CET_SHADOW_STACK_BOOL false
#define V8_ENABLE_BLACK_ALLOCATED_PAGES_BOOL false
#define V8_ENABLE_STICKY_MARK_BITS_BOOL false
#define V8_MINOR_MS_CONCURRENT_MARKING_MIN_CAPACITY_DEFAULT 8
#define FLAG FLAG_READONLY
#define FLAG FLAG_READONLY
#define FLAG FLAG_FULL
#define DEFAULT_PROF_SAMPLING_INTERVAL 1000
#define DEFINE_PERF_PROF_BOOL(nam, cmt) DEFINE_BOOL_READONLY(nam, false, cmt)
#define DEFINE_PERF_PROF_IMPLICATION(...)
#define DEFAULT_PERF_BASIC_PROF_PATH `/tmp`
#define DEFAULT_PERF_PROF_PATH `.`
#define FLAG FLAG_READONLY
#define FLAG FLAG_FULL
#define FLAG FLAG_READONLY
#define LOG_FLAGS(V)
#define SET_IMPLICATIONS(V)
Typedefs
using tier = =any, 0==ignition/interpreter, 1==sparkplug/baseline, ` `2==maglev, 3==turbofan`) DEFINE_MAYBE_BOOL(efficiency_mode, `Forces efficiency mode on or off, disregarding any dynamic ` `signals. Efficiency mode is optimized for situations with ` `no latency requirements and uses fewer threads.`) DEFINE_MAYBE_BOOL(battery_saver_mode, `Forces battery saver mode on or off, disregarding any dynamic signals. ` `Battery saver tries to conserve overall cpu cycles spent.`) DEFINE_MAYBE_BOOL(memory_saver_mode, `Forces memory saver mode on or off, disregarding any dynamic signals. ` `Memory saver tries to keep memory footprint low at the expense of extra ` `cpu cycles.`) DEFINE_BOOL(efficiency_mode_for_tiering_heuristics, true, `Use efficiency mode in tiering heuristics.`) DEFINE_BOOL(efficiency_mode_disable_turbofan, false, `Defer tier-up to turbofan while in efficiency mode.`) DEFINE_INT(efficiency_mode_delay_turbofan, 15000, `Delay tier-up to turbofan to a certain invocation count while in ` `efficiency mode.`) DEFINE_STRING(wasm_trace_native, nullptr, `Select which native code sequence to use for wasm trace instruction:` `default or cpuid`) #define V8_JITLESS_BOOL DEFINE_BOOL(jitless, V8_LITE_MODE_BOOL, `Disable runtime allocation of executable memory.`) DEFINE_BOOL(disable_optimizing_compilers, false, `Disable all optimizing compilers while leaving baseline compilers enabled`) DEFINE_BOOL(memory_protection_keys, true, `protect code memory with PKU if available`) DEFINE_BOOL(force_memory_protection_keys, false, `fail if memory protection key support is not available`) DEFINE_BOOL(assert_types, false, `generate runtime type assertions to test the typer`) DEFINE_EXPERIMENTAL_FEATURE(turboshaft_assert_types, `generate runtime type assertions to test the turboshaft type system`) DEFINE_BOOL(verify_simplified_lowering, false, `verify graph generated by simplified lowering`) #define V8_ALLOCATION_SITE_TRACKING_BOOL DEFINE_BOOL_READONLY(allocation_site_tracking, V8_ALLOCATION_SITE_TRACKING_BOOL, `Enable allocation site tracking`) DEFINE_NEG_NEG_IMPLICATION(allocation_site_tracking, allocation_site_pretenuring) DEFINE_BOOL(allocation_site_pretenuring, true, `pretenure with allocation sites`) DEFINE_INT(page_promotion_threshold, 70, `min percentage of live bytes on a page to enable fast evacuation ` `in full GCs`) DEFINE_INT(minor_ms_page_promotion_threshold, 50, `min percentage of live bytes on a page to enable fast evacuation ` `in MinorMS`) DEFINE_INT(minor_ms_page_promotion_max_lab_threshold, 30, `max percentage of labs out of a page to still be considered for ` `page promotion`) DEFINE_UINT(minor_ms_max_page_age, 4, `max age for a page after which it is force promoted to old space`) DEFINE_BOOL(trace_pretenuring, false, `trace pretenuring decisions of HAllocate instructions`) DEFINE_BOOL(trace_pretenuring_statistics, false, `trace allocation site pretenuring statistics`) DEFINE_BOOL(trace_block_coverage, false, `trace collected block coverage information`) DEFINE_BOOL(trace_protector_invalidation, false, `trace protector cell invalidations`) DEFINE_BOOL(decommit_pooled_pages, true, `decommit, rather than discard pooled pages`) DEFINE_BOOL(zero_unused_memory, true, `Zero unused memory(except for memory which was discarded) on memory ` `reducing GCs.`) DEFINE_BOOL_READONLY(minor_ms_shortcut_strings, false, `short cut strings during marking`) DEFINE_EXPERIMENTAL_FEATURE(feedback_normalization, `feed back normalization to constructors`) DEFINE_BOOL_READONLY(internalize_on_the_fly, true, `internalize string keys for generic keyed ICs on the fly`) DEFINE_INT(invocation_count_for_feedback_allocation, 8, `invocation count required for allocating feedback vectors`) DEFINE_INT(invocation_count_for_maglev, 400, `invocation count required for optimizing with Maglev`) DEFINE_INT(invocation_count_for_maglev_osr, 100, `invocation count required for maglev OSR`) DEFINE_BOOL(osr_from_maglev, false, `whether we try to OSR to Turbofan from OSR 'd Maglev`) DEFINE_FLOAT(osr_from_maglev_interrupt_scale_factor, 0.8, `Scale interrupt budget reduction for OSR from Maglev vs. OSR to Maglev`) DEFINE_BOOL(always_osr_from_maglev, false, `whether we try to OSR to Turbofan from any Maglev`) DEFINE_INT(invocation_count_for_turbofan, 3000, `invocation count required for optimizing with TurboFan`) DEFINE_INT(osr_to_tierup, 1, `number to decrease the invocation budget by when we follow OSR`) DEFINE_INT(minimum_invocations_after_ic_update, 500, `How long to minimally wait after IC update before tier up`) DEFINE_INT(minimum_invocations_before_optimization, 2, `Minimum number of invocations we need before non-OSR optimization`) DEFINE_BOOL(jit_fuzzing, false, `Set JIT tiering thresholds suitable for JIT fuzzing`) DEFINE_BOOL(use_std_math_pow, true, `use std::pow instead of our custom implementation`) DEFINE_BOOL(ignition_elide_noneffectful_bytecodes, true, `elide bytecodes which won 't have any external effect`) DEFINE_BOOL(ignition_filter_expression_positions, true, `filter expression positions before the bytecode pipeline`) DEFINE_BOOL(ignition_share_named_property_feedback, true, `share feedback slots when loading the same named property from ` `the same object`) DEFINE_BOOL(ignition_elide_redundant_tdz_checks, true, `elide TDZ checks dominated by other TDZ checks`) DEFINE_BOOL(print_bytecode, false, `print bytecode generated by ignition interpreter`) DEFINE_BOOL(enable_lazy_source_positions, V8_LAZY_SOURCE_POSITIONS_BOOL, `skip generating source positions during initial compile but ` `regenerate when actually required`) DEFINE_BOOL(stress_lazy_source_positions, false, `collect lazy source positions immediately after lazy compile`) DEFINE_STRING(print_bytecode_filter, ` *`, `filter for selecting which functions to print bytecode`) DEFINE_BOOL(trace_ignition_codegen, false, `trace the codegen of ignition interpreter bytecode handlers`) DEFINE_STRING(trace_ignition_dispatches_output_file, nullptr, `write the bytecode handler dispatch table to the specified file(d8 only) ` `(requires building with v8_enable_ignition_dispatch_counting)`) DEFINE_BOOL(trace_track_allocation_sites, false, `trace the tracking of allocation sites`) #define FLAG DEFINE_BOOL(sparkplug, ENABLE_SPARKPLUG_BY_DEFAULT, `enable Sparkplug baseline compiler`) DEFINE_BOOL_READONLY(concurrent_sparkplug, false, `compile Sparkplug code in a background thread`) DEFINE_BOOL(sparkplug_needs_short_builtins, false, `only enable Sparkplug baseline compiler when ` `--short-builtin-calls are also enabled`) DEFINE_INT(baseline_batch_compilation_threshold, 4 * KB, `the estimated instruction size of a batch to trigger compilation`) DEFINE_BOOL(trace_baseline_batch_compilation, false, `trace baseline batch compilation`) #define FLAG DEFINE_BOOL_READONLY(always_use_string_forwarding_table, false, `use string forwarding table instead of thin strings for ` `all strings(experimental)`) DEFINE_BOOL(transition_strings_during_gc_with_stack, false, `Transition strings during a full GC with stack`) DEFINE_SIZE_T(initial_shared_heap_size, 0, `initial size of the shared heap(in Mbytes)
Functions
DEFINE_BOOL (experimental, false, `Indicates that V8 is running with experimental features enabled. ` `This flag is typically not set explicitly but instead enabled as ` `an implication of other flags which enable experimental features.`) DEFINE_BOOL(abort_on_contradictory_flags
Disallow flags or implications overriding each other DEFINE_BOOL (exit_on_contradictory_flags, false, `Exit with return code 0 on contradictory flags.`) DEFINE_WEAK_IMPLICATION(exit_on_contradictory_flags
Disallow flags or implications overriding each other abort_on_contradictory_flags DEFINE_BOOL (allow_overwriting_for_next_flag, false, `temporary disable flag contradiction to allow overwriting just ` `the next flag`) DEFINE_BOOL(builtin_subclassing
Disallow flags or implications overriding each other abort_on_contradictory_flags subclassing support in built in methods DEFINE_BOOL (enable_sharedarraybuffer_per_context, false, `enable the SharedArrayBuffer constructor per context`) DEFINE_BOOL(stress_snapshot
DEFINE_BOOL (lite_mode, V8_LITE_MODE_BOOL, `enables trade-off of performance for memory savings`) DEFINE_BOOL_READONLY(enable_allocation_folding
DEFINE_BOOL_READONLY (disable_write_barriers, V8_DISABLE_WRITE_BARRIERS_BOOL, `disable write barriers when GC is non-incremental ` `and heap contains single generation.`) DEFINE_BOOL_READONLY(enable_unconditional_write_barriers
DEFINE_BOOL_READONLY (single_generation, V8_SINGLE_GENERATION_BOOL, `allocate all objects from young generation to old generation`) DEFINE_EXPERIMENTAL_FEATURE(conservative_stack_scanning
use conservative stack scanning DEFINE_IMPLICATION (conservative_stack_scanning, scavenger_conservative_object_pinning) DEFINE_BOOL_READONLY(direct_handle
use conservative stack scanning use direct handles with conservative stack scanning DEFINE_BOOL (scavenger_conservative_object_pinning, false, `Objects reachable from the native stack during ` `scavenge will be pinned and ` `won't move.`) DEFINE_BOOL(stress_scavenger_conservative_object_pinning
use conservative stack scanning use direct handles with conservative stack scanning Treat some precise references as conservative references to stress test object pinning in Scavenger DEFINE_IMPLICATION (stress_scavenger_conservative_object_pinning, scavenger_conservative_object_pinning) DEFINE_NEG_IMPLICATION(stress_scavenger_conservative_object_pinning
use conservative stack scanning use direct handles with conservative stack scanning Treat some precise references as conservative references to stress test object pinning in Scavenger minor_gc_task DEFINE_VALUE_IMPLICATION (stress_scavenger_conservative_object_pinning, max_semi_space_size, size_t{1}) DEFINE_BOOL(stress_scavenger_conservative_object_pinning_random
use conservative stack scanning use direct handles with conservative stack scanning Treat some precise references as conservative references to stress test object pinning in Scavenger minor_gc_task Enables random stressing of object pinning in such that each GC would randomly pick a subset of the precise references to treat conservatively DEFINE_IMPLICATION (stress_scavenger_conservative_object_pinning_random, stress_scavenger_conservative_object_pinning) DEFINE_BOOL(scavenger_precise_object_pinning
use conservative stack scanning use direct handles with conservative stack scanning Treat some precise references as conservative references to stress test object pinning in Scavenger minor_gc_task Enables random stressing of object pinning in such that each GC would randomly pick a subset of the precise references to treat conservatively Objects reachable from handles during scavenge will be pinned and won t move DEFINE_BOOL (precise_object_pinning, false, `Objects reachable from handles during GC will be pinned and won't move.`) DEFINE_BOOL(scavenger_promote_quarantined_pages
DEFINE_BOOL_READONLY (local_off_stack_check, V8_ENABLE_LOCAL_OFF_STACK_CHECK_BOOL, `check for off-stack allocation of v8::Local`) DEFINE_BOOL(experimental_fuzzing
DEFINE_BOOL (future, FUTURE_BOOL, `Implies all staged features that we want to ship in the ` `not-too-far future`) DEFINE_BOOL(force_emit_interrupt_budget_checks
force emit tier up logic from all non turbofan even if it is the top enabled tier DEFINE_BOOL_READONLY (maglev_future, false, `enable maglev features that we want to ship in the not-too-far future`) DEFINE_BOOL_READONLY(optimize_on_next_call_optimizes_to_maglev
force emit tier up logic from all non turbofan even if it is the top enabled tier make OptimizeFunctionOnNextCall optimize to maglev instead of turbofan DEFINE_BOOL (maglev_inlining, true, `enable inlining in the maglev optimizing compiler`) DEFINE_BOOL(maglev_loop_peeling
force emit tier up logic from all non turbofan even if it is the top enabled tier make OptimizeFunctionOnNextCall optimize to maglev instead of turbofan enable loop peeling in the maglev optimizing compiler DEFINE_BOOL (maglev_optimistic_peeled_loops, true, `enable aggressive optimizations for loops (loop SPeeling) in the ` `maglev optimizing compiler`) DEFINE_INT(maglev_loop_peeling_max_size
force emit tier up logic from all non turbofan even if it is the top enabled tier make OptimizeFunctionOnNextCall optimize to maglev instead of turbofan enable loop peeling in the maglev optimizing compiler max loop size for loop peeling in the maglev optimizing compiler DEFINE_INT (maglev_loop_peeling_max_size_cumulative, 900, `max cumulative size for loop peeling in the maglev optimizing compiler`) DEFINE_BOOL(maglev_deopt_data_on_background
force emit tier up logic from all non turbofan even if it is the top enabled tier make OptimizeFunctionOnNextCall optimize to maglev instead of turbofan enable loop peeling in the maglev optimizing compiler max loop size for loop peeling in the maglev optimizing compiler Generate deopt data on background thread DEFINE_BOOL (maglev_build_code_on_background, true, `Generate code on background thread`) DEFINE_WEAK_IMPLICATION(maglev_build_code_on_background
force emit tier up logic from all non turbofan even if it is the top enabled tier make OptimizeFunctionOnNextCall optimize to maglev instead of turbofan enable loop peeling in the maglev optimizing compiler max loop size for loop peeling in the maglev optimizing compiler Generate deopt data on background thread maglev_deopt_data_on_background DEFINE_BOOL (maglev_destroy_on_background, true, `Destroy compilation jobs on background thread`) DEFINE_BOOL(maglev_inline_api_calls
force emit tier up logic from all non turbofan even if it is the top enabled tier make OptimizeFunctionOnNextCall optimize to maglev instead of turbofan enable loop peeling in the maglev optimizing compiler max loop size for loop peeling in the maglev optimizing compiler Generate deopt data on background thread maglev_deopt_data_on_background Inline CallApiCallback builtin into generated code DEFINE_BOOL (maglev_cons_string_elision, true, `Native support for cons strings and their elision in maglev.`) DEFINE_BOOL(maglev_pretenure_store_values
force emit tier up logic from all non turbofan even if it is the top enabled tier make OptimizeFunctionOnNextCall optimize to maglev instead of turbofan enable loop peeling in the maglev optimizing compiler max loop size for loop peeling in the maglev optimizing compiler Generate deopt data on background thread maglev_deopt_data_on_background Inline CallApiCallback builtin into generated code Recursively pretenure values which are stored into pretenured allocation sites DEFINE_UINT (concurrent_maglev_max_threads, 2, `max number of threads that concurrent Maglev can use (0 for unbounded)`) DEFINE_BOOL(concurrent_maglev_high_priority_threads
force emit tier up logic from all non turbofan even if it is the top enabled tier make OptimizeFunctionOnNextCall optimize to maglev instead of turbofan enable loop peeling in the maglev optimizing compiler max loop size for loop peeling in the maglev optimizing compiler Generate deopt data on background thread maglev_deopt_data_on_background Inline CallApiCallback builtin into generated code Recursively pretenure values which are stored into pretenured allocation sites use high priority compiler threads for concurrent Maglev DEFINE_INT (max_maglev_inline_depth, 1, `max depth of functions that Maglev will inline excl. small functions`) DEFINE_INT(max_maglev_hard_inline_depth
force emit tier up logic from all non turbofan even if it is the top enabled tier make OptimizeFunctionOnNextCall optimize to maglev instead of turbofan enable loop peeling in the maglev optimizing compiler max loop size for loop peeling in the maglev optimizing compiler Generate deopt data on background thread maglev_deopt_data_on_background Inline CallApiCallback builtin into generated code Recursively pretenure values which are stored into pretenured allocation sites use high priority compiler threads for concurrent Maglev max depth of functions that Maglev will incl small functions DEFINE_INT (max_maglev_inlined_bytecode_size, 460, `maximum size of bytecode for a single inlining`) DEFINE_INT(max_maglev_inlined_bytecode_size_cumulative
force emit tier up logic from all non turbofan even if it is the top enabled tier make OptimizeFunctionOnNextCall optimize to maglev instead of turbofan enable loop peeling in the maglev optimizing compiler max loop size for loop peeling in the maglev optimizing compiler Generate deopt data on background thread maglev_deopt_data_on_background Inline CallApiCallback builtin into generated code Recursively pretenure values which are stored into pretenured allocation sites use high priority compiler threads for concurrent Maglev max depth of functions that Maglev will incl small functions maximum cumulative size of bytecode considered for inlining excl small functions DEFINE_INT (max_maglev_inlined_bytecode_size_small, 27, `maximum size of bytecode considered for small function inlining`) DEFINE_FLOAT(min_maglev_inlining_frequency
force emit tier up logic from all non turbofan even if it is the top enabled tier make OptimizeFunctionOnNextCall optimize to maglev instead of turbofan enable loop peeling in the maglev optimizing compiler max loop size for loop peeling in the maglev optimizing compiler Generate deopt data on background thread maglev_deopt_data_on_background Inline CallApiCallback builtin into generated code Recursively pretenure values which are stored into pretenured allocation sites use high priority compiler threads for concurrent Maglev max depth of functions that Maglev will incl small functions maximum cumulative size of bytecode considered for inlining excl small functions minimum frequency for inlining DEFINE_WEAK_VALUE_IMPLICATION (turbofan, max_maglev_inlined_bytecode_size_cumulative, 920) DEFINE_BOOL(maglev_reuse_stack_slots
force emit tier up logic from all non turbofan even if it is the top enabled tier make OptimizeFunctionOnNextCall optimize to maglev instead of turbofan enable loop peeling in the maglev optimizing compiler max loop size for loop peeling in the maglev optimizing compiler Generate deopt data on background thread maglev_deopt_data_on_background Inline CallApiCallback builtin into generated code Recursively pretenure values which are stored into pretenured allocation sites use high priority compiler threads for concurrent Maglev max depth of functions that Maglev will incl small functions maximum cumulative size of bytecode considered for inlining excl small functions minimum frequency for inlining reuse stack slots in the maglev optimizing compiler DEFINE_BOOL (maglev_untagged_phis, true, `enable phi untagging in the maglev optimizing compiler`) DEFINE_BOOL(maglev_hoist_osr_value_phi_untagging
force emit tier up logic from all non turbofan even if it is the top enabled tier make OptimizeFunctionOnNextCall optimize to maglev instead of turbofan enable loop peeling in the maglev optimizing compiler max loop size for loop peeling in the maglev optimizing compiler Generate deopt data on background thread maglev_deopt_data_on_background Inline CallApiCallback builtin into generated code Recursively pretenure values which are stored into pretenured allocation sites use high priority compiler threads for concurrent Maglev max depth of functions that Maglev will incl small functions maximum cumulative size of bytecode considered for inlining excl small functions minimum frequency for inlining reuse stack slots in the maglev optimizing compiler enable phi untagging to hoist untagging of osr values DEFINE_EXPERIMENTAL_FEATURE (maglev_speculative_hoist_phi_untagging, `enable phi untagging to hoist untagging of loop phi inputs (could ` `still cause deopt loops)`) DEFINE_EXPERIMENTAL_FEATURE(maglev_non_eager_inlining
force emit tier up logic from all non turbofan even if it is the top enabled tier make OptimizeFunctionOnNextCall optimize to maglev instead of turbofan enable loop peeling in the maglev optimizing compiler max loop size for loop peeling in the maglev optimizing compiler Generate deopt data on background thread maglev_deopt_data_on_background Inline CallApiCallback builtin into generated code Recursively pretenure values which are stored into pretenured allocation sites use high priority compiler threads for concurrent Maglev max depth of functions that Maglev will incl small functions maximum cumulative size of bytecode considered for inlining excl small functions minimum frequency for inlining reuse stack slots in the maglev optimizing compiler enable phi untagging to hoist untagging of osr values enable Maglev non eager inlining DEFINE_EXPERIMENTAL_FEATURE (turbolev_non_eager_inlining, `enable Turbolev non-eager inlining`) DEFINE_BOOL(maglev_inlining_following_eager_order
other heap size flags (e.g. initial_heap_size) take precedence`) DEFINE_SIZE_T(max_shared_heap_size
other heap size max size of the shared heap (in Mbytes)
other heap size generate builtins concurrently on separate threads in mksnapshot DEFINE_BOOL (concurrent_recompilation, true, `optimizing hot functions asynchronously on a separate thread`) DEFINE_BOOL(trace_concurrent_recompilation
other heap size generate builtins concurrently on separate threads in mksnapshot track concurrent recompilation DEFINE_INT (concurrent_recompilation_queue_length, 8, `the length of the concurrent compilation queue`) DEFINE_INT(concurrent_recompilation_delay
other heap size generate builtins concurrently on separate threads in mksnapshot track concurrent recompilation artificial compilation delay in ms DEFINE_BOOL (concurrent_recompilation_front_running, true, `move compile jobs to the front if recompilation is requested ` `multiple times`) DEFINE_UINT(concurrent_turbofan_max_threads
other heap size generate builtins concurrently on separate threads in mksnapshot track concurrent recompilation artificial compilation delay in ms max number of threads that concurrent Turbofan can use (0 for unbounded)`) DEFINE_BOOL(stress_concurrent_inlining
other heap size generate builtins concurrently on separate threads in mksnapshot track concurrent recompilation artificial compilation delay in ms max number of threads that concurrent Turbofan can create additional concurrent optimization jobs but throw away result DEFINE_WEAK_VALUE_IMPLICATION (stress_concurrent_inlining, invocation_count_for_turbofan, 150) DEFINE_BOOL(maglev_overwrite_budget
other heap size generate builtins concurrently on separate threads in mksnapshot track concurrent recompilation artificial compilation delay in ms max number of threads that concurrent Turbofan can create additional concurrent optimization jobs but throw away result whether maglev resets the interrupt budget DEFINE_WEAK_VALUE_IMPLICATION (maglev_overwrite_budget, invocation_count_for_turbofan, 12000) DEFINE_BOOL(maglev_overwrite_osr_budget
other heap size generate builtins concurrently on separate threads in mksnapshot track concurrent recompilation artificial compilation delay in ms max number of threads that concurrent Turbofan can create additional concurrent optimization jobs but throw away result whether maglev resets the interrupt budget whether maglev resets the OSR interrupt budget DEFINE_WEAK_VALUE_IMPLICATION (maglev_overwrite_osr_budget, invocation_count_for_osr, 800) DEFINE_BOOL(stress_concurrent_inlining_attach_code
other heap size generate builtins concurrently on separate threads in mksnapshot track concurrent recompilation artificial compilation delay in ms max number of threads that concurrent Turbofan can create additional concurrent optimization jobs but throw away result whether maglev resets the interrupt budget whether maglev resets the OSR interrupt budget create additional concurrent optimization jobs DEFINE_IMPLICATION (stress_concurrent_inlining_attach_code, stress_concurrent_inlining) DEFINE_INT(max_serializer_nesting
other heap size generate builtins concurrently on separate threads in mksnapshot track concurrent recompilation artificial compilation delay in ms max number of threads that concurrent Turbofan can create additional concurrent optimization jobs but throw away result whether maglev resets the interrupt budget whether maglev resets the OSR interrupt budget create additional concurrent optimization jobs maximum levels for nesting child serializers DEFINE_BOOL (trace_heap_broker_verbose, false, `trace the heap broker verbosely (all reports)`) DEFINE_BOOL(trace_heap_broker
other heap size generate builtins concurrently on separate threads in mksnapshot track concurrent recompilation artificial compilation delay in ms max number of threads that concurrent Turbofan can create additional concurrent optimization jobs but throw away result whether maglev resets the interrupt budget whether maglev resets the OSR interrupt budget create additional concurrent optimization jobs maximum levels for nesting child serializers trace the heap broker (reports on missing data only)`) DEFINE_INT(deopt_every_n_times
DEFINE_BOOL (stress_turbo_late_spilling, false, `optimize placement of all spill instructions, not just loop-top phis`) DEFINE_BOOL(turbo_wasm_address_reassociation
refactor address components for immediate indexing DEFINE_BOOL (concurrent_turbo_tracing, false, `allow concurrent compilation to happen in combination with ` `trace-turbo* flags`) DEFINE_BOOL(optimize_maglev_optimizes_to_turbofan
refactor address components for immediate indexing make OptimizeMaglevOnNextCall optimize to turbofan instead of maglev DEFINE_STRING (trace_turbo_path, nullptr, `directory to dump generated TurboFan IR to`) DEFINE_STRING(trace_turbo_filter
refactor address components for immediate indexing make OptimizeMaglevOnNextCall optimize to turbofan instead of maglev filter for tracing turbofan compilation DEFINE_STRING (trace_turbo_file_prefix, `turbo`, `trace turbo graph to a file with given prefix`) DEFINE_STRING(trace_turbo_cfg_file
refactor address components for immediate indexing make OptimizeMaglevOnNextCall optimize to turbofan instead of maglev filter for tracing turbofan compilation trace turbo cfg graph (for C1 visualizer) to a given file name`) DEFINE_SLOW_TRACING_BOOL(trace_turbo_trimming
refactor address components for immediate indexing make OptimizeMaglevOnNextCall optimize to turbofan instead of maglev filter for tracing turbofan compilation trace turbo cfg trace TurboFan s graph trimmer DEFINE_SLOW_TRACING_BOOL (trace_turbo_jt, false, `trace TurboFan's jump threading`) DEFINE_SLOW_TRACING_BOOL(trace_turbo_ceq
refactor address components for immediate indexing make OptimizeMaglevOnNextCall optimize to turbofan instead of maglev filter for tracing turbofan compilation trace turbo cfg trace TurboFan s graph trimmer trace TurboFan s control equivalence DEFINE_SLOW_TRACING_BOOL (trace_turbo_loop, false, `trace TurboFan's loop optimizations`) DEFINE_SLOW_TRACING_BOOL(trace_turbo_alloc
refactor address components for immediate indexing make OptimizeMaglevOnNextCall optimize to turbofan instead of maglev filter for tracing turbofan compilation trace turbo cfg trace TurboFan s graph trimmer trace TurboFan s control equivalence trace TurboFan s register allocator DEFINE_SLOW_TRACING_BOOL (trace_representation, false, `trace representation types`) DEFINE_BOOL(trace_turbo_stack_accesses
refactor address components for immediate indexing make OptimizeMaglevOnNextCall optimize to turbofan instead of maglev filter for tracing turbofan compilation trace turbo cfg trace TurboFan s graph trimmer trace TurboFan s control equivalence trace TurboFan s register allocator trace stack load store counters for optimized code in run time (x64 only)`) DEFINE_BOOL(fuzzing_and_concurrent_recompilation
refactor address components for immediate indexing make OptimizeMaglevOnNextCall optimize to turbofan instead of maglev filter for tracing turbofan compilation trace turbo cfg trace TurboFan s graph trimmer trace TurboFan s control equivalence trace TurboFan s register allocator trace stack load store counters for optimized code in run fuzzing &&concurrent_recompilation DEFINE_NEG_NEG_IMPLICATION (concurrent_recompilation, fuzzing_and_concurrent_recompilation) DEFINE_DISABLE_FLAG_IMPLICATION(fuzzing_and_concurrent_recompilation
refactor address components for immediate indexing make OptimizeMaglevOnNextCall optimize to turbofan instead of maglev filter for tracing turbofan compilation trace turbo cfg trace TurboFan s graph trimmer trace TurboFan s control equivalence trace TurboFan s register allocator trace stack load store counters for optimized code in run fuzzing &&concurrent_recompilation trace_turbo DEFINE_DISABLE_FLAG_IMPLICATION (fuzzing_and_concurrent_recompilation, trace_turbo_graph) DEFINE_DISABLE_FLAG_IMPLICATION(fuzzing_and_concurrent_recompilation
refactor address components for immediate indexing make OptimizeMaglevOnNextCall optimize to turbofan instead of maglev filter for tracing turbofan compilation trace turbo cfg trace TurboFan s graph trimmer trace TurboFan s control equivalence trace TurboFan s register allocator trace stack load store counters for optimized code in run fuzzing &&concurrent_recompilation trace_turbo trace_turbo_scheduled DEFINE_DISABLE_FLAG_IMPLICATION (fuzzing_and_concurrent_recompilation, trace_turbo_reduction) DEFINE_DISABLE_FLAG_IMPLICATION(fuzzing_and_concurrent_recompilation
refactor address components for immediate indexing make OptimizeMaglevOnNextCall optimize to turbofan instead of maglev filter for tracing turbofan compilation trace turbo cfg trace TurboFan s graph trimmer trace TurboFan s control equivalence trace TurboFan s register allocator trace stack load store counters for optimized code in run fuzzing &&concurrent_recompilation trace_turbo trace_turbo_scheduled trace_turbo_stack_accesses DEFINE_STRING (turbo_verify_machine_graph, nullptr, `verify TurboFan machine graph before instruction selection`) DEFINE_BOOL_READONLY(verify_csa
refactor address components for immediate indexing make OptimizeMaglevOnNextCall optimize to turbofan instead of maglev filter for tracing turbofan compilation trace turbo cfg trace TurboFan s graph trimmer trace TurboFan s control equivalence trace TurboFan s register allocator trace stack load store counters for optimized code in run fuzzing &&concurrent_recompilation trace_turbo trace_turbo_scheduled trace_turbo_stack_accesses verify TurboFan machine graph of code stubs DEFINE_STRING (csa_trap_on_node, nullptr, `trigger break point when a node with given id is created in ` `given stub. The format is: StubName,NodeId`) DEFINE_STRING(builtins_effects_src
refactor address components for immediate indexing make OptimizeMaglevOnNextCall optimize to turbofan instead of maglev filter for tracing turbofan compilation trace turbo cfg trace TurboFan s graph trimmer trace TurboFan s control equivalence trace TurboFan s register allocator trace stack load store counters for optimized code in run fuzzing &&concurrent_recompilation trace_turbo trace_turbo_scheduled trace_turbo_stack_accesses verify TurboFan machine graph of code stubs path where to generate builtins effects h (used for mksnapshot only)`) DEFINE_BOOL_READONLY(fixed_array_bounds_checks
refactor address components for immediate indexing make OptimizeMaglevOnNextCall optimize to turbofan instead of maglev filter for tracing turbofan compilation trace turbo cfg trace TurboFan s graph trimmer trace TurboFan s control equivalence trace TurboFan s register allocator trace stack load store counters for optimized code in run fuzzing &&concurrent_recompilation trace_turbo trace_turbo_scheduled trace_turbo_stack_accesses verify TurboFan machine graph of code stubs path where to generate builtins effects enable FixedArray bounds checks DEFINE_BOOL (turbo_stats_nvp, false, `print TurboFan statistics in machine-readable format`) DEFINE_BOOL(turbo_stats_wasm
refactor address components for immediate indexing make OptimizeMaglevOnNextCall optimize to turbofan instead of maglev filter for tracing turbofan compilation trace turbo cfg trace TurboFan s graph trimmer trace TurboFan s control equivalence trace TurboFan s register allocator trace stack load store counters for optimized code in run fuzzing &&concurrent_recompilation trace_turbo trace_turbo_scheduled trace_turbo_stack_accesses verify TurboFan machine graph of code stubs path where to generate builtins effects enable FixedArray bounds checks print TurboFan statistics of wasm compilations DEFINE_INT (max_inlined_bytecode_size, 460, `maximum size of bytecode for a single inlining`) DEFINE_INT(max_inlined_bytecode_size_cumulative
refactor address components for immediate indexing make OptimizeMaglevOnNextCall optimize to turbofan instead of maglev filter for tracing turbofan compilation trace turbo cfg trace TurboFan s graph trimmer trace TurboFan s control equivalence trace TurboFan s register allocator trace stack load store counters for optimized code in run fuzzing &&concurrent_recompilation trace_turbo trace_turbo_scheduled trace_turbo_stack_accesses verify TurboFan machine graph of code stubs path where to generate builtins effects enable FixedArray bounds checks print TurboFan statistics of wasm compilations maximum cumulative size of bytecode considered for inlining DEFINE_INT (max_inlined_bytecode_size_absolute, 4600, `maximum absolute size of bytecode considered for inlining`) DEFINE_INT(max_inlined_bytecode_size_small_total
refactor address components for immediate indexing make OptimizeMaglevOnNextCall optimize to turbofan instead of maglev filter for tracing turbofan compilation trace turbo cfg trace TurboFan s graph trimmer trace TurboFan s control equivalence trace TurboFan s register allocator trace stack load store counters for optimized code in run fuzzing &&concurrent_recompilation trace_turbo trace_turbo_scheduled trace_turbo_stack_accesses verify TurboFan machine graph of code stubs path where to generate builtins effects enable FixedArray bounds checks print TurboFan statistics of wasm compilations maximum cumulative size of bytecode considered for inlining maximum size of small functions bytecode that can be inlining DEFINE_FLOAT (reserve_inline_budget_scale_factor, 1.2, `scale factor of bytecode size used to calculate the inlining budget`) DEFINE_INT(max_inlined_bytecode_size_small
refactor address components for immediate indexing make OptimizeMaglevOnNextCall optimize to turbofan instead of maglev filter for tracing turbofan compilation trace turbo cfg trace TurboFan s graph trimmer trace TurboFan s control equivalence trace TurboFan s register allocator trace stack load store counters for optimized code in run fuzzing &&concurrent_recompilation trace_turbo trace_turbo_scheduled trace_turbo_stack_accesses verify TurboFan machine graph of code stubs path where to generate builtins effects enable FixedArray bounds checks print TurboFan statistics of wasm compilations maximum cumulative size of bytecode considered for inlining maximum size of small functions bytecode that can be inlining maximum size of bytecode considered for small function inlining DEFINE_INT (max_inlined_bytecode_size_small_with_heapnum_in_out, 75, `maximum size of bytecode considered for small function inlining, ` `when the function call has a HeapNumber as input or output`) DEFINE_INT(max_optimized_bytecode_size
too high values may cause the compiler to hit (release) assertions`) DEFINE_BOOL(stress_inline
too high values may cause the compiler to set high thresholds for inlining to as much as possible DEFINE_VALUE_IMPLICATION (stress_inline, max_inlined_bytecode_size_cumulative, 999999) DEFINE_VALUE_IMPLICATION(stress_inline
too high values may cause the compiler to set high thresholds for inlining to as much as possible DEFINE_BOOL (turbo_inline_array_builtins, true, `inline array builtins in TurboFan code`) DEFINE_BOOL(maglev_escape_analysis
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape DEFINE_EXPERIMENTAL_FEATURE (maglev_object_tracking, `track object changes to avoid escaping them`) DEFINE_BOOL(trace_maglev_object_tracking
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects DEFINE_WEAK_IMPLICATION (trace_maglev_graph_building, trace_maglev_object_tracking) DEFINE_BOOL_READONLY(turbo_string_builder
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder DEFINE_BOOL (log_or_trace_osr, false, `internal helper flag, please use --trace-osr instead.`) DEFINE_BOOL(analyze_environment_liveness
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values DEFINE_BOOL (trace_environment_liveness, false, `trace liveness of local variable slots`) DEFINE_BOOL(trace_turbo_load_elimination
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination DEFINE_BOOL (turbo_profiling_verbose, false, `enable basic block profiling in TurboFan, and include each ` `function's schedule and disassembly in the output`) DEFINE_STRING(turbo_profiling_output
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this file (requires that V8 was built with v8_enable_builtins_profiling=true)`) DEFINE_BOOL(reorder_builtins
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot DEFINE_BOOL (abort_on_bad_builtin_profile_data, false, `flag for mksnapshot, abort if builtins profile can't be applied`) DEFINE_BOOL(warn_about_builtin_profile_data
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data DEFINE_STRING (dump_builtins_hashes_to_file, nullptr, `flag for mksnapshot, dump CSA builtins graph hashes to this file`) DEFINE_BOOL(turbo_verify_allocation
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan DEFINE_BOOL (turbo_instruction_scheduling, false, `enable instruction scheduling in TurboFan`) DEFINE_BOOL(turbo_stress_instruction_scheduling
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking DEFINE_IMPLICATION (turbo_stress_instruction_scheduling, turbo_instruction_scheduling) DEFINE_BOOL(turbo_store_elimination
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan DEFINE_BOOL_READONLY (turbo_typer_hardening, true, `extra bounds checks to protect against some known typer ` `mismatch exploit techniques (best effort)`) DEFINE_BOOL_READONLY(turbo_rewrite_far_jumps
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near jumps (ia32, x64)`) DEFINE_BOOL(stress_gc_during_compilation
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode DEFINE_BOOL_READONLY (turbo_compress_frame_translations, false, `compress deoptimization frame translations (experimental)`) DEFINE_BOOL(turbo_inline_js_wasm_calls
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm calls (specifically:inline JS-to-Wasm wrappers and then ` `the body of the Wasm function, if applicable)`) DEFINE_BOOL(turbo_optimize_inlined_js_wasm_wrappers
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional optimizations (especially load-elimination) on ` `inlined JS-to-Wasm wrappers`) DEFINE_NEG_NEG_IMPLICATION(turbo_inline_js_wasm_calls
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers DEFINE_BOOL (turbo_optimize_math_minmax, true, `optimize call math.min/max with double array`) DEFINE_BOOL(turboshaft_enable_debug_features
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations DEFINE_BOOL (turboshaft_wasm_load_elimination, true, `enable Turboshaft's WasmLoadElimination`) DEFINE_EXPERIMENTAL_FEATURE(turboshaft_wasm_in_js_inlining
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via Turboshaft (instead of via ` `TurboFan). Only the Wasm code is inlined in Turboshaft
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls DEFINE_BOOL (turboshaft_load_elimination, true, `enable Turboshaft's low-level load elimination for JS`) DEFINE_BOOL(turboshaft_loop_unrolling
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling DEFINE_BOOL (turboshaft_string_concat_escape_analysis, true, `enable Turboshaft's escape analysis for string concatenation`) DEFINE_EXPERIMENTAL_FEATURE(turboshaft_typed_optimizations
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information DEFINE_BOOL (turbolev, false, `use Turbolev (Maglev + Turboshaft combined) as the 4th tier ` `compiler instead of Turbofan`) DEFINE_EXPERIMENTAL_FEATURE(turbolev_future
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future DEFINE_BOOL (typed_array_length_loading, true, `Enable specializing loading the TypedArray length in Maglev / Turbofan`) DEFINE_BOOL_READONLY(turboshaft_trace_reduction
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps DEFINE_BOOL_READONLY (turboshaft_trace_emitted, false, `trace emitted Turboshaft instructions`) DEFINE_BOOL_READONLY(turboshaft_trace_intermediate_reductions
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps DEFINE_BOOL_READONLY (turboshaft_trace_load_elimination, false, `trace Turboshaft's late load elimination`) DEFINE_BOOL_READONLY(turboshaft_trace_if_else_to_switch
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer DEFINE_BOOL (profile_guided_optimization_for_empty_feedback_vector, true, `profile guided optimization for empty feedback vector`) DEFINE_INT(invocation_count_for_early_optimization
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization DEFINE_INT (invocation_count_for_maglev_with_delay, 600, `invocation count for maglev for functions which according to ` `profile_guided_optimization are likely to deoptimize before ` `reaching this invocation count`) DEFINE_BOOL(optimize_for_size
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed DEFINE_BOOL (reopt_after_lazy_deopts, true, `Immediately re-optimize code after some lazy deopts`) DEFINE_INT(stress_sampling_allocation_profiler
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval DEFINE_BOOL (lazy_new_space_shrinking, false, `Enables the lazy new space shrinking strategy`) DEFINE_SIZE_T(min_semi_space_size
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi space (in MBytes)
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces DEFINE_SIZE_T (max_semi_space_size, 0, `max size of a semi-space (in MBytes), the new space consists of ` `two semi-spaces`) DEFINE_SIZE_T(max_heap_size
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space size (in Mbytes)`) DEFINE_INT(random_gc_interval
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after random (0, X) V8 allocations. It override s ` `gc_interval.`) DEFINE_INT(cppgc_random_gc_interval
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections DEFINE_BOOL (trace_gc, false, `print one trace line following each garbage collection`) DEFINE_BOOL(trace_gc_nvp
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed DEFINE_BOOL (incremental_marking_start_user_visible, true, `Starts incremental marking with kUserVisible priority.`) DEFINE_INT(incremental_marking_soft_trigger
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects DEFINE_UINT (minor_gc_task_trigger, 80, `minor GC task trigger in percent of the current heap limit`) DEFINE_BOOL(minor_gc_task_with_lower_priority
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority DEFINE_EXPERIMENTAL_FEATURE (cppgc_young_generation, `run young generation garbage collections in Oilpan`) DEFINE_INT(concurrent_marking_max_worker_num
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads DEFINE_BOOL (concurrent_array_buffer_sweeping, true, `concurrently sweep array buffers`) DEFINE_BOOL(stress_concurrent_allocation
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory DEFINE_INT (ephemeron_fixpoint_iterations, 10, `number of fixpoint iterations it takes to switch to linear ` `ephemeron algorithm`) DEFINE_NEG_NEG_IMPLICATION(concurrent_sweeping
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping DEFINE_BOOL (parallel_pointer_update, true, `use parallel pointer update during compaction`) DEFINE_BOOL(parallel_weak_ref_clearing
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause DEFINE_BOOL (detect_ineffective_gcs_near_heap_limit, true, `trigger out-of-memory failure to avoid GC storm near heap limit`) DEFINE_BOOL(trace_incremental_marking
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking DEFINE_BOOL (track_gc_object_stats, false, `track object counts and memory usage`) DEFINE_BOOL(trace_gc_object_stats
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage DEFINE_GENERIC_IMPLICATION (trace_zone_stats, TracingFlags::zone_stats.store(v8::tracing::TracingCategoryObserver::ENABLED_BY_NATIVE)) DEFINE_SIZE_T(zone_stats_tolerance
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount DEFINE_GENERIC_IMPLICATION (trace_zone_type_stats, TracingFlags::zone_stats.store(v8::tracing::TracingCategoryObserver::ENABLED_BY_NATIVE)) DEFINE_GENERIC_IMPLICATION(track_gc_object_stats
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats store (v8::tracing::TracingCategoryObserver::ENABLED_BY_NATIVE)) DEFINE_GENERIC_IMPLICATION(trace_gc_object_stats
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected DEFINE_BOOL (trace_detached_contexts, false, `trace native contexts that are expected to be garbage collected`) DEFINE_BOOL_READONLY(verify_heap
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC DEFINE_BOOL (memory_reducer_respects_frozen_state, false, `don't schedule another GC when we are frozen`) DEFINE_BOOL(memory_reducer_favors_memory
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag DEFINE_BOOL (memory_reducer_for_small_heaps, true, `use memory reducer for small heaps`) DEFINE_INT(memory_reducer_gc_count
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled DEFINE_BOOL (external_memory_accounted_in_global_limit, false, `External memory limits are computed as part of global limits in v8 Heap.`) DEFINE_BOOL(gc_speed_uses_counters
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters DEFINE_INT (heap_growing_percent, 0, `specifies heap growing factor as (1 + heap_growing_percent/100)`) DEFINE_BOOL(compact
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics DEFINE_BOOL (compact_code_space, true, `Perform code space compaction on full collections.`) DEFINE_BOOL(compact_on_every_full_gc
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC DEFINE_BOOL (compact_with_stack, true, `Perform compaction when finalizing a full GC with stack`) DEFINE_BOOL(compact_code_space_with_stack
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack DEFINE_BOOL (shortcut_strings_with_stack, true, `Shortcut Strings during GC with stack`) DEFINE_BOOL(stress_compaction
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects DEFINE_BOOL (stress_compaction_random, false, `Stress GC compaction by selecting random percent of pages as ` `evacuation candidates. Overrides stress_compaction.`) DEFINE_BOOL(flush_baseline_code
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently DEFINE_BOOL (flush_bytecode, true, `flush of bytecode when it has not been executed recently`) DEFINE_BOOL(flush_code_based_on_time
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age DEFINE_BOOL (flush_code_based_on_tab_visibility, false, `Flush code when tab goes into the background.`) DEFINE_BOOL(use_marking_progress_bar
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active DEFINE_BOOL (stress_per_context_marking_worklist, false, `Use per-context worklist for marking`) DEFINE_BOOL(stress_incremental_marking
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often DEFINE_SIZE_T (max_large_page_pool_size, 32, `Maximum size of pooled large pages in MB.`) DEFINE_INT(large_page_pool_timeout
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds DEFINE_BOOL (managed_zone_memory, false, `Manage zone memory in V8 instead of using malloc().`) DEFINE_BOOL(fuzzer_gc_analysis
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge DEFINE_INT (stress_marking, 0, `force marking at random points between 0 and X (inclusive) percent ` `of the regular marking start limit`) DEFINE_INT(stress_scavenge
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and X (inclusive) ` `percent of the new space capacity`) DEFINE_BOOL(reclaim_unmodified_wrappers
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and reclaim otherwise unreachable unmodified wrapper objects when possible DEFINE_BOOL (parallel_reclaim_unmodified_wrappers, true, `reclaim wrapper objects in parallel`) DEFINE_BOOL(discard_memory_pool_before_memory_pressure_gcs
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and reclaim otherwise unreachable unmodified wrapper objects when possible discard the memory pool before invoking the GC on memory pressure or last resort GCs DEFINE_BOOL (gc_experiment_less_compaction, false, `less compaction in non-memory reducing mode`) DEFINE_INT(gc_memory_reducer_start_delay_ms
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and reclaim otherwise unreachable unmodified wrapper objects when possible discard the memory pool before invoking the GC on memory pressure or last resort GCs Delay before memory reducer start DEFINE_BOOL (concurrent_marking_high_priority_threads, false, `use high priority threads for concurrent Marking`) DEFINE_BOOL(randomize_all_allocations
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and reclaim otherwise unreachable unmodified wrapper objects when possible discard the memory pool before invoking the GC on memory pressure or last resort GCs Delay before memory reducer start virtual randomize memory reservations by ignoring any hints passed when allocating pages DEFINE_BOOL (manual_evacuation_candidates_selection, false, `Test mode only flag. It allows an unit test to select evacuation ` `candidates pages (requires --stress_compaction).`) DEFINE_BOOL(cppheap_incremental_marking
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and reclaim otherwise unreachable unmodified wrapper objects when possible discard the memory pool before invoking the GC on memory pressure or last resort GCs Delay before memory reducer start virtual randomize memory reservations by ignoring any hints passed when allocating pages use incremental marking for CppHeap DEFINE_BOOL (cppheap_concurrent_marking, false, `use concurrent marking for CppHeap`) DEFINE_NEG_NEG_IMPLICATION(cppheap_incremental_marking
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and reclaim otherwise unreachable unmodified wrapper objects when possible discard the memory pool before invoking the GC on memory pressure or last resort GCs Delay before memory reducer start virtual randomize memory reservations by ignoring any hints passed when allocating pages use incremental marking for CppHeap cppheap_concurrent_marking DEFINE_BOOL (memory_balancer, false, `use membalancer, ` `a new heap limit balancing algorithm`) DEFINE_FLOAT(memory_balancer_c_value
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and reclaim otherwise unreachable unmodified wrapper objects when possible discard the memory pool before invoking the GC on memory pressure or last resort GCs Delay before memory reducer start virtual randomize memory reservations by ignoring any hints passed when allocating pages use incremental marking for CppHeap cppheap_concurrent_marking c value for membalancer A special constant to balance between memory and space tradeoff The smaller the more memory it uses DEFINE_BOOL (late_heap_limit_check, false, `skips heap limit check for early GCs on allocation failure.`) DEFINE_BOOL(enable_sse4_1
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and reclaim otherwise unreachable unmodified wrapper objects when possible discard the memory pool before invoking the GC on memory pressure or last resort GCs Delay before memory reducer start virtual randomize memory reservations by ignoring any hints passed when allocating pages use incremental marking for CppHeap cppheap_concurrent_marking c value for membalancer A special constant to balance between memory and space tradeoff The smaller the more memory it uses enable use of SSE4 instructions if available DEFINE_BOOL (enable_sse4_2, true, `enable use of SSE4.2 instructions if available`) DEFINE_BOOL(enable_sahf
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and reclaim otherwise unreachable unmodified wrapper objects when possible discard the memory pool before invoking the GC on memory pressure or last resort GCs Delay before memory reducer start virtual randomize memory reservations by ignoring any hints passed when allocating pages use incremental marking for CppHeap cppheap_concurrent_marking c value for membalancer A special constant to balance between memory and space tradeoff The smaller the more memory it uses enable use of SSE4 instructions if available enable use of SAHF instruction if available (X64 only)`) DEFINE_BOOL(enable_avx_vnni
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and reclaim otherwise unreachable unmodified wrapper objects when possible discard the memory pool before invoking the GC on memory pressure or last resort GCs Delay before memory reducer start virtual randomize memory reservations by ignoring any hints passed when allocating pages use incremental marking for CppHeap cppheap_concurrent_marking c value for membalancer A special constant to balance between memory and space tradeoff The smaller the more memory it uses enable use of SSE4 instructions if available enable use of SAHF instruction if enable use of AVX VNNI instructions if available DEFINE_BOOL (enable_avx_vnni_int8, true, `enable use of AVX-VNNI-INT8 instructions if available`) DEFINE_BOOL(enable_popcnt
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and reclaim otherwise unreachable unmodified wrapper objects when possible discard the memory pool before invoking the GC on memory pressure or last resort GCs Delay before memory reducer start virtual randomize memory reservations by ignoring any hints passed when allocating pages use incremental marking for CppHeap cppheap_concurrent_marking c value for membalancer A special constant to balance between memory and space tradeoff The smaller the more memory it uses enable use of SSE4 instructions if available enable use of SAHF instruction if enable use of AVX VNNI instructions if available enable use of POPCNT instruction if available DEFINE_STRING (arm_arch, ARM_ARCH_DEFAULT, `generate instructions for the selected ARM architecture if ` `available: armv6, armv7, armv7+sudiv or armv8`) DEFINE_BOOL(force_long_branches
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and reclaim otherwise unreachable unmodified wrapper objects when possible discard the memory pool before invoking the GC on memory pressure or last resort GCs Delay before memory reducer start virtual randomize memory reservations by ignoring any hints passed when allocating pages use incremental marking for CppHeap cppheap_concurrent_marking c value for membalancer A special constant to balance between memory and space tradeoff The smaller the more memory it uses enable use of SSE4 instructions if available enable use of SAHF instruction if enable use of AVX VNNI instructions if available enable use of POPCNT instruction if available force all emitted branches to be in long mode (MIPS/PPC only)`) DEFINE_BOOL(partial_constant_pool
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and reclaim otherwise unreachable unmodified wrapper objects when possible discard the memory pool before invoking the GC on memory pressure or last resort GCs Delay before memory reducer start virtual randomize memory reservations by ignoring any hints passed when allocating pages use incremental marking for CppHeap cppheap_concurrent_marking c value for membalancer A special constant to balance between memory and space tradeoff The smaller the more memory it uses enable use of SSE4 instructions if available enable use of SAHF instruction if enable use of AVX VNNI instructions if available enable use of POPCNT instruction if available force all emitted branches to be in long enable use of partial constant pools (x64 only)`) DEFINE_STRING(sim_arm64_optional_features
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and reclaim otherwise unreachable unmodified wrapper objects when possible discard the memory pool before invoking the GC on memory pressure or last resort GCs Delay before memory reducer start virtual randomize memory reservations by ignoring any hints passed when allocating pages use incremental marking for CppHeap cppheap_concurrent_marking c value for membalancer A special constant to balance between memory and space tradeoff The smaller the more memory it uses enable use of SSE4 instructions if available enable use of SAHF instruction if enable use of AVX VNNI instructions if available enable use of POPCNT instruction if available force all emitted branches to be in long enable use of partial constant enable optional features on the simulator for enable mitigation for Intel JCC erratum on affected CPUs DEFINE_BOOL (enable_source_at_csa_bind, false, `Include source information in the binary at CSA bind locations.`) DEFINE_BOOL(enable_regexp_unaligned_accesses
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and reclaim otherwise unreachable unmodified wrapper objects when possible discard the memory pool before invoking the GC on memory pressure or last resort GCs Delay before memory reducer start virtual randomize memory reservations by ignoring any hints passed when allocating pages use incremental marking for CppHeap cppheap_concurrent_marking c value for membalancer A special constant to balance between memory and space tradeoff The smaller the more memory it uses enable use of SSE4 instructions if available enable use of SAHF instruction if enable use of AVX VNNI instructions if available enable use of POPCNT instruction if available force all emitted branches to be in long enable use of partial constant enable optional features on the simulator for enable mitigation for Intel JCC erratum on affected CPUs enable unaligned accesses for the regexp engine DEFINE_BOOL (stress_background_compile, false, `stress test parsing on background`) DEFINE_BOOL(concurrent_cache_deserialization
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and reclaim otherwise unreachable unmodified wrapper objects when possible discard the memory pool before invoking the GC on memory pressure or last resort GCs Delay before memory reducer start virtual randomize memory reservations by ignoring any hints passed when allocating pages use incremental marking for CppHeap cppheap_concurrent_marking c value for membalancer A special constant to balance between memory and space tradeoff The smaller the more memory it uses enable use of SSE4 instructions if available enable use of SAHF instruction if enable use of AVX VNNI instructions if available enable use of POPCNT instruction if available force all emitted branches to be in long enable use of partial constant enable optional features on the simulator for enable mitigation for Intel JCC erratum on affected CPUs enable unaligned accesses for the regexp engine enable deserializing code caches on background DEFINE_BOOL (merge_background_deserialized_script_with_compilation_cache, true, `After deserializing code cache data on a background thread, merge it into ` `an existing Script if one is found in the Isolate compilation cache`) DEFINE_BOOL(experimental_embedder_instance_types
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and reclaim otherwise unreachable unmodified wrapper objects when possible discard the memory pool before invoking the GC on memory pressure or last resort GCs Delay before memory reducer start virtual randomize memory reservations by ignoring any hints passed when allocating pages use incremental marking for CppHeap cppheap_concurrent_marking c value for membalancer A special constant to balance between memory and space tradeoff The smaller the more memory it uses enable use of SSE4 instructions if available enable use of SAHF instruction if enable use of AVX VNNI instructions if available enable use of POPCNT instruction if available force all emitted branches to be in long enable use of partial constant enable optional features on the simulator for enable mitigation for Intel JCC erratum on affected CPUs enable unaligned accesses for the regexp engine enable deserializing code caches on background enable type checks based on instance types provided by the embedder DEFINE_STRING (expose_gc_as, nullptr, `expose gc extension under the specified name`) DEFINE_BOOL(expose_externalize_string
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and reclaim otherwise unreachable unmodified wrapper objects when possible discard the memory pool before invoking the GC on memory pressure or last resort GCs Delay before memory reducer start virtual randomize memory reservations by ignoring any hints passed when allocating pages use incremental marking for CppHeap cppheap_concurrent_marking c value for membalancer A special constant to balance between memory and space tradeoff The smaller the more memory it uses enable use of SSE4 instructions if available enable use of SAHF instruction if enable use of AVX VNNI instructions if available enable use of POPCNT instruction if available force all emitted branches to be in long enable use of partial constant enable optional features on the simulator for enable mitigation for Intel JCC erratum on affected CPUs enable unaligned accesses for the regexp engine enable deserializing code caches on background enable type checks based on instance types provided by the embedder expose externalize string extension DEFINE_BOOL (expose_ignition_statistics, false, `expose ignition-statistics extension (requires building with ` `v8_enable_ignition_dispatch_counting)`) DEFINE_BOOL(builtins_in_stack_traces
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and reclaim otherwise unreachable unmodified wrapper objects when possible discard the memory pool before invoking the GC on memory pressure or last resort GCs Delay before memory reducer start virtual randomize memory reservations by ignoring any hints passed when allocating pages use incremental marking for CppHeap cppheap_concurrent_marking c value for membalancer A special constant to balance between memory and space tradeoff The smaller the more memory it uses enable use of SSE4 instructions if available enable use of SAHF instruction if enable use of AVX VNNI instructions if available enable use of POPCNT instruction if available force all emitted branches to be in long enable use of partial constant enable optional features on the simulator for enable mitigation for Intel JCC erratum on affected CPUs enable unaligned accesses for the regexp engine enable deserializing code caches on background enable type checks based on instance types provided by the embedder expose externalize string extension show built in functions in stack traces DEFINE_BOOL (experimental_stack_trace_frames, false, `enable experimental frames (API/Builtins) and stack trace layout`) DEFINE_BOOL(disallow_code_generation_from_strings
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and reclaim otherwise unreachable unmodified wrapper objects when possible discard the memory pool before invoking the GC on memory pressure or last resort GCs Delay before memory reducer start virtual randomize memory reservations by ignoring any hints passed when allocating pages use incremental marking for CppHeap cppheap_concurrent_marking c value for membalancer A special constant to balance between memory and space tradeoff The smaller the more memory it uses enable use of SSE4 instructions if available enable use of SAHF instruction if enable use of AVX VNNI instructions if available enable use of POPCNT instruction if available force all emitted branches to be in long enable use of partial constant enable optional features on the simulator for enable mitigation for Intel JCC erratum on affected CPUs enable unaligned accesses for the regexp engine enable deserializing code caches on background enable type checks based on instance types provided by the embedder expose externalize string extension show built in functions in stack traces disallow eval and friends DEFINE_STRING (expose_cputracemark_as, nullptr, `expose cputracemark extension under the specified name`) DEFINE_BOOL(experimental_report_exceptions_from_callbacks
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and reclaim otherwise unreachable unmodified wrapper objects when possible discard the memory pool before invoking the GC on memory pressure or last resort GCs Delay before memory reducer start virtual randomize memory reservations by ignoring any hints passed when allocating pages use incremental marking for CppHeap cppheap_concurrent_marking c value for membalancer A special constant to balance between memory and space tradeoff The smaller the more memory it uses enable use of SSE4 instructions if available enable use of SAHF instruction if enable use of AVX VNNI instructions if available enable use of POPCNT instruction if available force all emitted branches to be in long enable use of partial constant enable optional features on the simulator for enable mitigation for Intel JCC erratum on affected CPUs enable unaligned accesses for the regexp engine enable deserializing code caches on background enable type checks based on instance types provided by the embedder expose externalize string extension show built in functions in stack traces disallow eval and friends Notify Api callback about exceptions thrown in Api callbacks DEFINE_BOOL (allow_unsafe_function_constructor, false, `allow invoking the function constructor without security checks`) DEFINE_BOOL(test_small_max_function_context_stub_size
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and reclaim otherwise unreachable unmodified wrapper objects when possible discard the memory pool before invoking the GC on memory pressure or last resort GCs Delay before memory reducer start virtual randomize memory reservations by ignoring any hints passed when allocating pages use incremental marking for CppHeap cppheap_concurrent_marking c value for membalancer A special constant to balance between memory and space tradeoff The smaller the more memory it uses enable use of SSE4 instructions if available enable use of SAHF instruction if enable use of AVX VNNI instructions if available enable use of POPCNT instruction if available force all emitted branches to be in long enable use of partial constant enable optional features on the simulator for enable mitigation for Intel JCC erratum on affected CPUs enable unaligned accesses for the regexp engine enable deserializing code caches on background enable type checks based on instance types provided by the embedder expose externalize string extension show built in functions in stack traces disallow eval and friends Notify Api callback about exceptions thrown in Api callbacks enable testing the function context size overflow path by making the maximum size smaller DEFINE_INT (switch_table_spread_threshold, 3, `allow the jump table used for switch statements to span a range ` `of integers roughly equal to this number times the number of ` `clauses in the switch`) DEFINE_INT(switch_table_min_cases
Variables
false
Disallow flags or implications overriding each other abort_on_contradictory_flags true
V8_ALLOCATION_FOLDING_BOOL
V8_ENABLE_UNCONDITIONAL_WRITE_BARRIERS_BOOL
use conservative stack scanning V8_ENABLE_DIRECT_HANDLE_BOOL
use conservative stack scanning use direct handles with conservative stack scanning Treat some precise references as conservative references to stress test object pinning in Scavenger minor_gc_task Enables random stressing of object pinning in Scavenger
force emit tier up logic from all non turbofan code
refactor address components for immediate indexing make OptimizeMaglevOnNextCall optimize to turbofan instead of maglev filter for tracing turbofan compilation nullptr
refactor address components for immediate indexing make OptimizeMaglevOnNextCall optimize to turbofan instead of maglev filter for tracing turbofan compilation trace turbo cfg trace TurboFan s graph trimmer trace TurboFan s control equivalence trace TurboFan s register allocator trace stack load store counters for optimized code in run fuzzing &&concurrent_recompilation trace_turbo trace_turbo_scheduled trace_turbo_stack_accesses verify TurboFan machine graph of code stubs path where to generate builtins effects enable FixedArray bounds checks print TurboFan statistics of wasm compilations maximum cumulative size of bytecode considered for inlining maximum size of small functions bytecode that can be inlining maximum size of bytecode considered for small function inlining * KB
refactor address components for immediate indexing make OptimizeMaglevOnNextCall optimize to turbofan instead of maglev filter for tracing turbofan compilation trace turbo cfg trace TurboFan s graph trimmer trace TurboFan s control equivalence trace TurboFan s register allocator trace stack load store counters for optimized code in run fuzzing &&concurrent_recompilation trace_turbo trace_turbo_scheduled trace_turbo_stack_accesses verify TurboFan machine graph of code stubs path where to generate builtins effects enable FixedArray bounds checks print TurboFan statistics of wasm compilations maximum cumulative size of bytecode considered for inlining maximum size of small functions bytecode that can be inlining maximum size of bytecode considered for small function inlining maximum bytecode size to be considered for turbofan optimization
too high values may cause the compiler to set high thresholds for inlining to as much as possible max_inlined_bytecode_size_absolute
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for mksnapshot
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data DEBUG_BOOL
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to https
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s DebugPrint
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at all
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in name
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation speed
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available space
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent marking
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage * MB
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz testing
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and reclaim otherwise unreachable unmodified wrapper objects when possible discard the memory pool before invoking the GC on memory pressure or last resort GCs Delay before memory reducer start virtual randomize memory reservations by ignoring any hints passed when allocating pages use incremental marking for CppHeap cppheap_concurrent_marking c value for membalancer A special constant to balance between memory and space tradeoff The smaller the more memory it uses enable use of SSE4 instructions if available enable use of SAHF instruction if enable use of AVX VNNI instructions if available enable use of POPCNT instruction if available force all emitted branches to be in long enable use of partial constant none
Macro Definition Documentation
ARM_ARCH_DEFAULT
#define ARM_ARCH_DEFAULT `armv8`
Definition at line 172 of file flag-definitions.h.
DEFAULT_MAX_POLYMORPHIC_MAP_COUNT
#define DEFAULT_MAX_POLYMORPHIC_MAP_COUNT 4
DEFAULT_PERF_BASIC_PROF_PATH
#define DEFAULT_PERF_BASIC_PROF_PATH `/tmp`
DEFAULT_PERF_PROF_PATH
#define DEFAULT_PERF_PROF_PATH `.`
DEFAULT_PROF_SAMPLING_INTERVAL
#define DEFAULT_PROF_SAMPLING_INTERVAL 1000
DEFINE_ALIAS_BOOL
#define DEFINE_ALIAS_BOOL(alias, nam) FLAG_ALIAS(BOOL, bool, alias, nam)
Definition at line 202 of file flag-definitions.h.
DEFINE_ALIAS_FLOAT
#define DEFINE_ALIAS_FLOAT(alias, nam) FLAG_ALIAS(FLOAT, double, alias, nam)
Definition at line 204 of file flag-definitions.h.
DEFINE_ALIAS_INT
#define DEFINE_ALIAS_INT(alias, nam) FLAG_ALIAS(INT, int, alias, nam)
Definition at line 203 of file flag-definitions.h.
DEFINE_ALIAS_SIZE_T
#define DEFINE_ALIAS_SIZE_T(alias, nam) FLAG_ALIAS(SIZE_T, size_t, alias, nam)
Definition at line 205 of file flag-definitions.h.
DEFINE_ALIAS_STRING
#define DEFINE_ALIAS_STRING(alias, nam) FLAG_ALIAS(STRING, const char*, alias, nam)
Definition at line 206 of file flag-definitions.h.
DEFINE_BOOL
#define DEFINE_BOOL(nam, def, cmt) FLAG(BOOL, bool, nam, def, cmt)
Definition at line 189 of file flag-definitions.h.
DEFINE_BOOL_READONLY
#define DEFINE_BOOL_READONLY(nam, def, cmt) FLAG_READONLY(BOOL, bool, nam, def, cmt)
Definition at line 190 of file flag-definitions.h.
DEFINE_DEBUG_BOOL
#define DEFINE_DEBUG_BOOL DEFINE_BOOL_READONLY
Definition at line 212 of file flag-definitions.h.
DEFINE_DISABLE_FLAG_IMPLICATION
#define DEFINE_DISABLE_FLAG_IMPLICATION(whenflag, thenflag)
Definition at line 146 of file flag-definitions.h.
DEFINE_EXPERIMENTAL_FEATURE
#define DEFINE_EXPERIMENTAL_FEATURE(nam, cmt)
Value:
  FLAG(BOOL, bool, nam, false, cmt " (experimental)") \
  DEFINE_IMPLICATION(nam, experimental)
DEFINE_FLOAT
#define DEFINE_FLOAT(nam, def, cmt) FLAG(FLOAT, double, nam, def, cmt)
Definition at line 199 of file flag-definitions.h.
DEFINE_GENERIC_IMPLICATION
#define DEFINE_GENERIC_IMPLICATION(whenflag, statement)
Definition at line 130 of file flag-definitions.h.
DEFINE_IMPLICATION
#define DEFINE_IMPLICATION(whenflag, thenflag) DEFINE_VALUE_IMPLICATION(whenflag, thenflag, true)
Definition at line 15 of file flag-definitions.h.
DEFINE_INT
#define DEFINE_INT(nam, def, cmt) FLAG(INT, int, nam, def, cmt)
Definition at line 194 of file flag-definitions.h.
DEFINE_MAYBE_BOOL
#define DEFINE_MAYBE_BOOL(nam, cmt) FLAG(MAYBE_BOOL, std::optional<bool>, nam, std::nullopt, cmt)
Definition at line 192 of file flag-definitions.h.
DEFINE_MIN_VALUE_IMPLICATION
#define DEFINE_MIN_VALUE_IMPLICATION(flag, min_value)
Definition at line 142 of file flag-definitions.h.
DEFINE_NEG_IMPLICATION
#define DEFINE_NEG_IMPLICATION(whenflag, thenflag) DEFINE_VALUE_IMPLICATION(whenflag, thenflag, false)
Definition at line 26 of file flag-definitions.h.
DEFINE_NEG_NEG_IMPLICATION
#define DEFINE_NEG_NEG_IMPLICATION(whenflag, thenflag) DEFINE_NEG_VALUE_IMPLICATION(whenflag, thenflag, false)
Definition at line 29 of file flag-definitions.h.
DEFINE_NEG_VALUE_IMPLICATION
#define DEFINE_NEG_VALUE_IMPLICATION(whenflag, thenflag, value)
Definition at line 134 of file flag-definitions.h.
DEFINE_NEG_VALUE_VALUE_IMPLICATION
#define DEFINE_NEG_VALUE_VALUE_IMPLICATION(whenflag, whenvalue, thenflag, thenvalue)
Definition at line 137 of file flag-definitions.h.
DEFINE_PERF_PROF_BOOL
#define DEFINE_PERF_PROF_BOOL(nam, cmt) DEFINE_BOOL_READONLY(nam, false, cmt)
DEFINE_PERF_PROF_IMPLICATION
#define DEFINE_PERF_PROF_IMPLICATION(...)
DEFINE_REQUIREMENT
#define DEFINE_REQUIREMENT(statement)
Definition at line 150 of file flag-definitions.h.
DEFINE_SIZE_T
#define DEFINE_SIZE_T(nam, def, cmt) FLAG(SIZE_T, size_t, nam, def, cmt)
Definition at line 200 of file flag-definitions.h.
DEFINE_SLOW_TRACING_BOOL
#define DEFINE_SLOW_TRACING_BOOL DEFINE_BOOL_READONLY
DEFINE_STRING
#define DEFINE_STRING(nam, def, cmt) FLAG(STRING, const char*, nam, def, cmt)
Definition at line 201 of file flag-definitions.h.
DEFINE_UINT
#define DEFINE_UINT(nam, def, cmt) FLAG(UINT, unsigned int, nam, def, cmt)
Definition at line 195 of file flag-definitions.h.
DEFINE_UINT64
#define DEFINE_UINT64(nam, def, cmt) FLAG(UINT64, uint64_t, nam, def, cmt)
Definition at line 198 of file flag-definitions.h.
DEFINE_UINT_READONLY
#define DEFINE_UINT_READONLY(nam, def, cmt) FLAG_READONLY(UINT, unsigned int, nam, def, cmt)
Definition at line 196 of file flag-definitions.h.
DEFINE_VALUE_IMPLICATION
#define DEFINE_VALUE_IMPLICATION(whenflag, thenflag, value)
Definition at line 122 of file flag-definitions.h.
DEFINE_WEAK_IMPLICATION
#define DEFINE_WEAK_IMPLICATION(whenflag, thenflag) DEFINE_WEAK_VALUE_IMPLICATION(whenflag, thenflag, true)
Definition at line 20 of file flag-definitions.h.
DEFINE_WEAK_NEG_IMPLICATION
#define DEFINE_WEAK_NEG_IMPLICATION(whenflag, thenflag) DEFINE_WEAK_VALUE_IMPLICATION(whenflag, thenflag, false)
Definition at line 23 of file flag-definitions.h.
DEFINE_WEAK_VALUE_IMPLICATION
#define DEFINE_WEAK_VALUE_IMPLICATION(whenflag, thenflag, value)
Definition at line 126 of file flag-definitions.h.
ENABLE_LOG_COLOUR
#define ENABLE_LOG_COLOUR true
Definition at line 186 of file flag-definitions.h.
ENABLE_SPARKPLUG_BY_DEFAULT
#define ENABLE_SPARKPLUG_BY_DEFAULT false
Definition at line 160 of file flag-definitions.h.
FLAG [1/9]
#define FLAG FLAG_FULL
Definition at line 218 of file flag-definitions.h.
FLAG [2/9]
#define FLAG FLAG_READONLY
Definition at line 218 of file flag-definitions.h.
FLAG [3/9]
#define FLAG FLAG_FULL
Definition at line 218 of file flag-definitions.h.
FLAG [4/9]
#define FLAG FLAG_READONLY
Definition at line 218 of file flag-definitions.h.
FLAG [5/9]
#define FLAG FLAG_READONLY
Definition at line 218 of file flag-definitions.h.
FLAG [6/9]
#define FLAG FLAG_FULL
Definition at line 218 of file flag-definitions.h.
FLAG [7/9]
#define FLAG FLAG_READONLY
Definition at line 218 of file flag-definitions.h.
FLAG [8/9]
#define FLAG FLAG_FULL
Definition at line 218 of file flag-definitions.h.
FLAG [9/9]
#define FLAG FLAG_READONLY
Definition at line 218 of file flag-definitions.h.
FLAG_ALIAS
#define FLAG_ALIAS(ftype, ctype, alias, nam)
Definition at line 118 of file flag-definitions.h.
FLAG_FULL
#define FLAG_FULL(ftype, ctype, nam, def, cmt)
Definition at line 110 of file flag-definitions.h.
FLAG_INPROGRESS_FEATURES
#define FLAG_INPROGRESS_FEATURES(id, description)
Value:
  DEFINE_BOOL(id, false, \
              "enable " #description " (in progress / experimental)") \
  DEFINE_IMPLICATION(id, experimental)
FLAG_READONLY
#define FLAG_READONLY(ftype, ctype, nam, def, cmt)
Definition at line 114 of file flag-definitions.h.
FLAG_SHIPPING_FEATURES
#define FLAG_SHIPPING_FEATURES(id, description)
Value:
  DEFINE_BOOL(id, true, "enable " #description) \
  DEFINE_NEG_NEG_IMPLICATION(harmony_shipping, id) \
  DEFINE_NEG_NEG_IMPLICATION(js_shipping, id)
FLAG_STAGED_FEATURES
#define FLAG_STAGED_FEATURES(id, description)
Value:
  DEFINE_BOOL(id, false, "enable " #description) \
  DEFINE_IMPLICATION(harmony, id) \
  DEFINE_IMPLICATION(js_staging, id)
FUTURE_BOOL
#define FUTURE_BOOL false
Definition at line 539 of file flag-definitions.h.
HARMONY_INPROGRESS
#define HARMONY_INPROGRESS(V) HARMONY_INPROGRESS_BASE(V)
HARMONY_INPROGRESS_BASE
#define HARMONY_INPROGRESS_BASE(V)
Value:
  V(harmony_temporal, "Temporal") \
  V(harmony_shadow_realm, "harmony ShadowRealm") \
  V(harmony_struct, "harmony structs, shared structs, and shared arrays")
HARMONY_SHIPPING
#define HARMONY_SHIPPING(V) HARMONY_SHIPPING_BASE(V)
HARMONY_SHIPPING_BASE
#define HARMONY_SHIPPING_BASE(V) V(harmony_import_attributes, `harmony import attributes`)
HARMONY_STAGED
#define HARMONY_STAGED(V) HARMONY_STAGED_BASE(V)
HARMONY_STAGED_BASE
#define HARMONY_STAGED_BASE(V)
JAVASCRIPT_INPROGRESS_FEATURES
#define JAVASCRIPT_INPROGRESS_FEATURES(V) JAVASCRIPT_INPROGRESS_FEATURES_BASE(V)
JAVASCRIPT_INPROGRESS_FEATURES_BASE
#define JAVASCRIPT_INPROGRESS_FEATURES_BASE(V)
Value:
  V(js_decorators, "decorators") \
  V(js_source_phase_imports, "source phase imports")
JAVASCRIPT_SHIPPING_FEATURES
#define JAVASCRIPT_SHIPPING_FEATURES(V) JAVASCRIPT_SHIPPING_FEATURES_BASE(V)
JAVASCRIPT_SHIPPING_FEATURES_BASE
#define JAVASCRIPT_SHIPPING_FEATURES_BASE(V)
Value:
  V(js_regexp_duplicate_named_groups, "RegExp duplicate named groups") \
  V(js_regexp_modifiers, "RegExp modifiers") \
  V(js_promise_try, "Promise.try") \
  V(js_atomics_pause, "Atomics.pause") \
  V(js_error_iserror, "Error.isError") \
  V(js_regexp_escape, "RegExp.escape") \
  V(js_explicit_resource_management, "explicit resource management") \
  V(js_float16array, \
    "Float16Array, Math.f16round, DataView.getFloat16, DataView.setFloat16")
JAVASCRIPT_STAGED_FEATURES
#define JAVASCRIPT_STAGED_FEATURES(V) JAVASCRIPT_STAGED_FEATURES_BASE(V)
JAVASCRIPT_STAGED_FEATURES_BASE
#define JAVASCRIPT_STAGED_FEATURES_BASE(V) V(js_base_64, `Uint8Array to/from base64 and hex`)
LOG_FLAGS
#define LOG_FLAGS(V)
Value:
  V(log_code) \
  V(log_code_disassemble) \
  V(log_deopt) \
  V(log_feedback_vector) \
  V(log_function_events) \
  V(log_ic) \
  V(log_maps) \
  V(log_source_code) \
  V(log_source_position) \
  V(log_timer_events) \
  V(prof) \
  V(prof_cpp)
REGEXP_PEEPHOLE_OPTIMIZATION_BOOL
#define REGEXP_PEEPHOLE_OPTIMIZATION_BOOL true
SET_IMPLICATIONS
#define SET_IMPLICATIONS(V)
Value:
  DEFINE_IMPLICATION(log_all, V) \
  DEFINE_IMPLICATION(V, log)
V8_ALLOCATION_FOLDING_BOOL
#define V8_ALLOCATION_FOLDING_BOOL false
V8_ALLOCATION_SITE_TRACKING_BOOL
#define V8_ALLOCATION_SITE_TRACKING_BOOL false
V8_CET_SHADOW_STACK_BOOL
#define V8_CET_SHADOW_STACK_BOOL false
V8_DISABLE_WRITE_BARRIERS_BOOL
#define V8_DISABLE_WRITE_BARRIERS_BOOL false
Definition at line 430 of file flag-definitions.h.
V8_ENABLE_BLACK_ALLOCATED_PAGES_BOOL
#define V8_ENABLE_BLACK_ALLOCATED_PAGES_BOOL false
V8_ENABLE_DIRECT_HANDLE_BOOL
#define V8_ENABLE_DIRECT_HANDLE_BOOL false
V8_ENABLE_DOUBLE_CONST_STORE_CHECK_BOOL
#define V8_ENABLE_DOUBLE_CONST_STORE_CHECK_BOOL false
V8_ENABLE_LOCAL_OFF_STACK_CHECK_BOOL
#define V8_ENABLE_LOCAL_OFF_STACK_CHECK_BOOL false
Definition at line 522 of file flag-definitions.h.
V8_ENABLE_STICKY_MARK_BITS_BOOL
#define V8_ENABLE_STICKY_MARK_BITS_BOOL false
V8_ENABLE_TURBOFAN_BOOL
#define V8_ENABLE_TURBOFAN_BOOL false
Definition at line 1246 of file flag-definitions.h.
V8_ENABLE_UNCONDITIONAL_WRITE_BARRIERS_BOOL
#define V8_ENABLE_UNCONDITIONAL_WRITE_BARRIERS_BOOL false
V8_JITLESS_BOOL
#define V8_JITLESS_BOOL false
V8_LAZY_SOURCE_POSITIONS_BOOL
#define V8_LAZY_SOURCE_POSITIONS_BOOL false
V8_LITE_MODE_BOOL
#define V8_LITE_MODE_BOOL false
Definition at line 407 of file flag-definitions.h.
V8_MINOR_MS_CONCURRENT_MARKING_MIN_CAPACITY_DEFAULT
#define V8_MINOR_MS_CONCURRENT_MARKING_MIN_CAPACITY_DEFAULT 8
V8_SHORT_BUILTIN_CALLS_BOOL
#define V8_SHORT_BUILTIN_CALLS_BOOL false
V8_SINGLE_GENERATION_BOOL
#define V8_SINGLE_GENERATION_BOOL false
Definition at line 456 of file flag-definitions.h.
Typedef Documentation
tier
using tier = = any, 0 == ignition/interpreter, 1 == sparkplug/baseline, ` `2 == maglev, 3 == turbofan`) DEFINE_MAYBE_BOOL(efficiency_mode, `Forces efficiency mode on or off, disregarding any dynamic ` `signals. Efficiency mode is optimized for situations with ` `no latency requirements and uses fewer threads.`) DEFINE_MAYBE_BOOL(battery_saver_mode, `Forces battery saver mode on or off, disregarding any dynamic signals. ` `Battery saver tries to conserve overall cpu cycles spent.`) DEFINE_MAYBE_BOOL(memory_saver_mode, `Forces memory saver mode on or off, disregarding any dynamic signals. ` `Memory saver tries to keep memory footprint low at the expense of extra ` `cpu cycles.`) DEFINE_BOOL(efficiency_mode_for_tiering_heuristics, true, `Use efficiency mode in tiering heuristics.`) DEFINE_BOOL(efficiency_mode_disable_turbofan, false, `Defer tier-up to turbofan while in efficiency mode.`) DEFINE_INT(efficiency_mode_delay_turbofan, 15000, `Delay tier-up to turbofan to a certain invocation count while in ` `efficiency mode.`) DEFINE_STRING(wasm_trace_native, nullptr, `Select which native code sequence to use for wasm trace instruction: ` `default or cpuid`) #define V8_JITLESS_BOOL DEFINE_BOOL(jitless, V8_LITE_MODE_BOOL, `Disable runtime allocation of executable memory.`) DEFINE_BOOL(disable_optimizing_compilers, false, `Disable all optimizing compilers while leaving baseline compilers enabled`) DEFINE_BOOL(memory_protection_keys, true, `protect code memory with PKU if available`) DEFINE_BOOL(force_memory_protection_keys, false, `fail if memory protection key support is not available`) DEFINE_BOOL(assert_types, false, `generate runtime type assertions to test the typer`) DEFINE_EXPERIMENTAL_FEATURE(turboshaft_assert_types, `generate runtime type assertions to test the turboshaft type system`) DEFINE_BOOL(verify_simplified_lowering, false, `verify graph generated by simplified lowering`) #define V8_ALLOCATION_SITE_TRACKING_BOOL DEFINE_BOOL_READONLY(allocation_site_tracking, V8_ALLOCATION_SITE_TRACKING_BOOL, `Enable allocation site tracking`) DEFINE_NEG_NEG_IMPLICATION(allocation_site_tracking, allocation_site_pretenuring) DEFINE_BOOL(allocation_site_pretenuring, true, `pretenure with allocation sites`) DEFINE_INT(page_promotion_threshold, 70, `min percentage of live bytes on a page to enable fast evacuation ` `in full GCs`) DEFINE_INT(minor_ms_page_promotion_threshold, 50, `min percentage of live bytes on a page to enable fast evacuation ` `in MinorMS`) DEFINE_INT(minor_ms_page_promotion_max_lab_threshold, 30, `max percentage of labs out of a page to still be considered for ` `page promotion`) DEFINE_UINT(minor_ms_max_page_age, 4, `max age for a page after which it is force promoted to old space`) DEFINE_BOOL(trace_pretenuring, false, `trace pretenuring decisions of HAllocate instructions`) DEFINE_BOOL(trace_pretenuring_statistics, false, `trace allocation site pretenuring statistics`) DEFINE_BOOL(trace_block_coverage, false, `trace collected block coverage information`) DEFINE_BOOL(trace_protector_invalidation, false, `trace protector cell invalidations`) DEFINE_BOOL(decommit_pooled_pages, true, `decommit, rather than discard pooled pages`) DEFINE_BOOL(zero_unused_memory, true, `Zero unused memory (except for memory which was discarded) on memory ` `reducing GCs.`) DEFINE_BOOL_READONLY(minor_ms_shortcut_strings, false, `short cut strings during marking`) DEFINE_EXPERIMENTAL_FEATURE(feedback_normalization, `feed back normalization to constructors`) DEFINE_BOOL_READONLY(internalize_on_the_fly, true, `internalize string keys for generic keyed ICs on the fly`) DEFINE_INT(invocation_count_for_feedback_allocation, 8, `invocation count required for allocating feedback vectors`) DEFINE_INT(invocation_count_for_maglev, 400, `invocation count required for optimizing with Maglev`) DEFINE_INT(invocation_count_for_maglev_osr, 100, `invocation count required for maglev OSR`) DEFINE_BOOL(osr_from_maglev, false, `whether we try to OSR to Turbofan from OSR'd Maglev`) DEFINE_FLOAT(osr_from_maglev_interrupt_scale_factor, 0.8, `Scale interrupt budget reduction for OSR from Maglev vs. OSR to Maglev`) DEFINE_BOOL(always_osr_from_maglev, false, `whether we try to OSR to Turbofan from any Maglev`) DEFINE_INT(invocation_count_for_turbofan, 3000, `invocation count required for optimizing with TurboFan`) DEFINE_INT(osr_to_tierup, 1, `number to decrease the invocation budget by when we follow OSR`) DEFINE_INT(minimum_invocations_after_ic_update, 500, `How long to minimally wait after IC update before tier up`) DEFINE_INT(minimum_invocations_before_optimization, 2, `Minimum number of invocations we need before non-OSR optimization`) DEFINE_BOOL(jit_fuzzing, false, `Set JIT tiering thresholds suitable for JIT fuzzing`) DEFINE_BOOL(use_std_math_pow, true, `use std::pow instead of our custom implementation`) DEFINE_BOOL(ignition_elide_noneffectful_bytecodes, true, `elide bytecodes which won't have any external effect`) DEFINE_BOOL(ignition_filter_expression_positions, true, `filter expression positions before the bytecode pipeline`) DEFINE_BOOL(ignition_share_named_property_feedback, true, `share feedback slots when loading the same named property from ` `the same object`) DEFINE_BOOL(ignition_elide_redundant_tdz_checks, true, `elide TDZ checks dominated by other TDZ checks`) DEFINE_BOOL(print_bytecode, false, `print bytecode generated by ignition interpreter`) DEFINE_BOOL(enable_lazy_source_positions, V8_LAZY_SOURCE_POSITIONS_BOOL, `skip generating source positions during initial compile but ` `regenerate when actually required`) DEFINE_BOOL(stress_lazy_source_positions, false, `collect lazy source positions immediately after lazy compile`) DEFINE_STRING(print_bytecode_filter, `*`, `filter for selecting which functions to print bytecode`) DEFINE_BOOL(trace_ignition_codegen, false, `trace the codegen of ignition interpreter bytecode handlers`) DEFINE_STRING(trace_ignition_dispatches_output_file, nullptr, `write the bytecode handler dispatch table to the specified file (d8 only) ` `(requires building with v8_enable_ignition_dispatch_counting)`) DEFINE_BOOL(trace_track_allocation_sites, false, `trace the tracking of allocation sites`) #define FLAG DEFINE_BOOL(sparkplug, ENABLE_SPARKPLUG_BY_DEFAULT, `enable Sparkplug baseline compiler`) DEFINE_BOOL_READONLY(concurrent_sparkplug, false, `compile Sparkplug code in a background thread`) DEFINE_BOOL(sparkplug_needs_short_builtins, false, `only enable Sparkplug baseline compiler when ` `--short-builtin-calls are also enabled`) DEFINE_INT(baseline_batch_compilation_threshold, 4 * KB, `the estimated instruction size of a batch to trigger compilation`) DEFINE_BOOL(trace_baseline_batch_compilation, false, `trace baseline batch compilation`) #define FLAG DEFINE_BOOL_READONLY(always_use_string_forwarding_table, false, `use string forwarding table instead of thin strings for ` `all strings (experimental)`) DEFINE_BOOL(transition_strings_during_gc_with_stack, false, `Transition strings during a full GC with stack`) DEFINE_SIZE_T(initial_shared_heap_size, 0, `initial size of the shared heap (in Mbytes)
Definition at line 792 of file flag-definitions.h.
Function Documentation
available()
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and reclaim otherwise unreachable unmodified wrapper objects when possible discard the memory pool before invoking the GC on memory pressure or last resort GCs Delay before memory reducer start virtual randomize memory reservations by ignoring any hints passed when allocating pages use incremental marking for CppHeap cppheap_concurrent_marking c value for membalancer A special constant to balance between memory and space tradeoff The smaller the more memory it uses enable use of SSE4 instructions if available enable use of SAHF instruction if available (X64 only)
Referenced by v8::internal::UseScratchRegisterScope::Acquire(), v8::internal::wasm::liftoff::CacheStatePreservingTempRegisters::Acquire(), v8::internal::UseScratchRegisterScope::AcquireNextAvailable(), v8::internal::UseScratchRegisterScope::AcquireVfp(), v8::internal::interpreter::ConstantArrayBuilder::ConstantArraySlice::Allocate(), v8::internal::interpreter::ConstantArrayBuilder::AllocateIndexArray(), v8::internal::UseScratchRegisterScope::CanAcquire(), v8::internal::UseScratchRegisterScope::CanAcquireVfp(), v8::internal::interpreter::ConstantArrayBuilder::CreateReservedEntry(), v8::internal::UseScratchRegisterScope::Exclude(), v8::internal::wasm::LiftoffRegList::GetAdjacentFpRegsSet(), v8::internal::UseScratchRegisterScope::Include(), v8::internal::WeakCollectionsBuiltinsAssembler::InsufficientCapacityToAdd(), v8::internal::interpreter::ConstantArrayBuilder::ConstantArraySlice::Reserve(), v8::internal::AssemblerBase::set_constant_pool_available(), v8::internal::UseScratchRegisterScope::SetAvailable(), v8::internal::UseScratchRegisterScope::SetAvailableDoubleRegList(), v8::internal::UseScratchRegisterScope::SetAvailableVfp(), and v8::internal::UseScratchRegisterScope::~UseScratchRegisterScope().
broker()
other heap size generate builtins concurrently on separate threads in mksnapshot track concurrent recompilation artificial compilation delay in ms max number of threads that concurrent Turbofan can create additional concurrent optimization jobs but throw away result whether maglev resets the interrupt budget whether maglev resets the OSR interrupt budget create additional concurrent optimization jobs maximum levels for nesting child serializers trace the heap broker (reports on missing data only)
Referenced by v8::internal::compiler::anonymous_namespace{access-info.cc}::AccessorAccessInfoHelper(), v8::internal::compiler::MapRef::AsElementsKind(), v8::internal::compiler::turboshaft::Pipeline::AssembleCode(), v8::internal::compiler::AllocationSiteRef::boilerplate(), v8::internal::compiler::JSBoundFunctionRef::bound_arguments(), v8::internal::compiler::JSBoundFunctionRef::bound_target_function(), v8::internal::compiler::JSBoundFunctionRef::bound_this(), v8::internal::compiler::JSTypedArrayRef::buffer(), v8::internal::maglev::MaglevGraphBuilder::BuildAndAllocateJSArrayIterator(), v8::internal::maglev::MaglevGraphBuilder::BuildAndAllocateKeyValueArray(), v8::internal::maglev::MaglevGraphBuilder::BuildCallWithFeedback(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckInternalizedStringValueOrByReference(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckValueByReference(), v8::internal::maglev::MaglevGraphBuilder::BuildConstruct(), v8::internal::maglev::MaglevGraphBuilder::BuildElementsArray(), v8::internal::compiler::BuildGraphFromBytecode(), v8::internal::maglev::MaglevGraphBuilder::BuildInlinedAllocationForDoubleFixedArray(), v8::internal::maglev::MaglevGraphBuilder::BuildInlinedAllocationForHeapNumber(), v8::internal::maglev::MaglevGraphBuilder::BuildInlinedArgumentsElements(), v8::internal::maglev::MaglevGraphBuilder::BuildInlinedUnmappedArgumentsElements(), v8::internal::maglev::MaglevInliner::BuildInlineFunction(), v8::internal::compiler::BytecodeGraphBuilder::BuildLdaLookupContextSlot(), v8::internal::compiler::BytecodeGraphBuilder::BuildLdaLookupGlobalSlot(), v8::internal::compiler::BytecodeGraphBuilder::BuildLdaLookupSlot(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadGlobal(), v8::internal::compiler::BytecodeGraphBuilder::BuildLoadGlobal(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadStringLength(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadTypedArrayLength(), v8::internal::compiler::BytecodeGraphBuilder::BuildNamedStore(), v8::internal::maglev::MaglevGraphBuilder::BuildToNumberOrToNumeric(), v8::internal::maglev::MaglevGraphBuilder::BuildVirtualArgumentsObject(), v8::internal::compiler::FunctionTemplateInfoRef::c_functions(), v8::internal::compiler::FunctionTemplateInfoRef::c_signatures(), v8::internal::compiler::PropertyCellData::Cache(), v8::internal::compiler::JSFunctionData::Cache(), v8::internal::compiler::PropertyCellRef::Cache(), v8::internal::compiler::PropertyCellRef::CacheAsProtector(), v8::internal::compiler::FunctionTemplateInfoRef::callback(), v8::internal::compiler::FunctionTemplateInfoRef::callback_data(), v8::internal::compiler::NodeProperties::CanBeNullOrUndefined(), v8::internal::compiler::NodeProperties::CanBePrimitive(), v8::internal::compiler::anonymous_namespace{js-inlining-heuristic.cc}::CanConsiderForInlining(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::CanInlineArrayIteratingBuiltin(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::CanInlineArrayIteratingBuiltin(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::CanInlineArrayResizingBuiltin(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::CanInlineArrayResizingBuiltin(), v8::internal::maglev::MaglevGraphBuilder::CanInlineCall(), v8::internal::compiler::BytecodeGraphBuilder::CheckContextExtensions(), v8::internal::maglev::KnownNodeAspects::CheckType(), v8::internal::maglev::KnownNodeAspects::CheckTypes(), cppgc::EphemeronPair< K, V >::ClearValueIfKeyIsDead(), v8::internal::compiler::JSFunctionRef::code(), v8::internal::compiler::CompilationDependencies::CompilationDependencies(), v8::internal::compiler::BytecodeGraphBuilder::ComputeCallFeedbackRelation(), v8::internal::compiler::BytecodeGraphBuilder::ComputeCallFrequency(), v8::internal::compiler::JSGraph::Constant(), v8::internal::compiler::JSGraph::ConstantMaybeHole(), v8::internal::compiler::JSGraph::ConstantNoHole(), v8::internal::maglev::MaglevGraphBuilder::CreateDoubleFixedArray(), v8::internal::maglev::MaglevGraphBuilder::CreateHeapNumber(), v8::internal::maglev::MaglevGraphBuilder::CreateJSConstructor(), v8::internal::maglev::MaglevGraphBuilder::CreateRegExpLiteralObject(), v8::internal::compiler::RegExpBoilerplateDescriptionRef::data(), v8::internal::compiler::PropertyAccessInfo::DataField(), v8::internal::compiler::JSNativeContextSpecialization::dependencies(), v8::internal::compiler::CompilationDependencies::DependOnContextCell(), v8::internal::compiler::JSObjectRef::elements(), v8::internal::compiler::JSTypedArrayRef::elements_kind(), v8::internal::maglev::KnownNodeAspects::EnsureType(), v8::internal::maglev::MaglevCompilationUnit::feedback(), v8::internal::compiler::JSFunctionRef::feedback_vector(), v8::internal::compiler::FeedbackCellRef::feedback_vector(), v8::internal::maglev::MaglevGraphBuilder::FeedbackNexusForOperand(), v8::internal::maglev::MaglevGraphBuilder::FeedbackNexusForSlot(), v8::internal::compiler::MapRef::FindFieldOwner(), v8::internal::compiler::MapRef::FindRootMap(), v8::internal::compiler::Type::For(), v8::internal::compiler::InstructionSelector::ForTurboshaft(), v8::internal::compiler::SharedFunctionInfoRef::function_template_info(), v8::internal::compiler::ContextRef::get(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::GetArrayConstructorInitialMap(), v8::internal::compiler::MapRef::GetBackPointer(), v8::internal::compiler::JSArrayRef::GetBoilerplateLength(), v8::internal::compiler::SharedFunctionInfoRef::GetBytecodeArray(), v8::internal::compiler::SourceTextModuleRef::GetCell(), v8::internal::compiler::StringRef::GetChar(), v8::internal::compiler::StringRef::GetCharAsStringOrUndefined(), v8::internal::compiler::FeedbackVectorRef::GetClosureFeedbackCell(), v8::internal::maglev::Graph::GetConstant(), v8::internal::compiler::GlobalAccessFeedback::GetConstantHint(), v8::internal::compiler::MapRef::GetConstructor(), v8::internal::compiler::NativeContextRef::GetConstructorFunction(), v8::internal::maglev::MaglevGraphBuilder::GetConvertReceiver(), v8::internal::compiler::fast_api_call::GetFastApiCallTarget(), v8::internal::compiler::JSCreateClosureNode::GetFeedbackCellRefChecked(), v8::internal::compiler::StringRef::GetFirstChar(), v8::internal::compiler::BytecodeGraphBuilder::GetForInMode(), v8::internal::compiler::NativeContextRef::GetFunctionMapFromIndex(), v8::internal::compiler::JSProxyRef::GetHandler(), v8::internal::compiler::HeapObjectRef::GetHeapObjectType(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ConstantInDictionaryPrototypeChainDependency::GetHolderIfValid(), v8::internal::compiler::NativeContextRef::GetInitialJSArrayMap(), v8::internal::compiler::SharedFunctionInfoRef::GetInlineability(), v8::internal::compiler::NodeProperties::GetJSCreateMap(), v8::internal::compiler::GetModuleContext(), v8::internal::compiler::JSObjectRef::GetObjectCreateMap(), v8::internal::compiler::anonymous_namespace{js-create-lowering.cc}::GetObjectCreateMap(), v8::internal::maglev::KnownNodeAspects::GetOrCreateInfoFor(), v8::internal::compiler::JSObjectRef::GetOwnConstantElement(), v8::internal::compiler::JSObjectRef::GetOwnConstantElementFromHeap(), v8::internal::compiler::JSArrayRef::GetOwnCowElement(), v8::internal::compiler::JSObjectRef::GetOwnDictionaryProperty(), v8::internal::compiler::anonymous_namespace{heap-refs.cc}::GetOwnDictionaryPropertyFromHeap(), v8::internal::compiler::JSObjectRef::GetOwnFastConstantDataProperty(), v8::internal::compiler::anonymous_namespace{heap-refs.cc}::GetOwnFastConstantDataPropertyFromHeap(), v8::internal::compiler::JSObjectRef::GetOwnFastConstantDoubleProperty(), v8::internal::compiler::JSGlobalObjectRef::GetPropertyCell(), v8::internal::compiler::MapRef::GetPropertyDetails(), v8::internal::compiler::DescriptorArrayRef::GetPropertyKey(), v8::internal::compiler::MapRef::GetPropertyKey(), v8::internal::maglev::MaglevGraphBuilder::GetRefOperand(), v8::internal::compiler::anonymous_namespace{js-context-specialization.cc}::GetSpecializationContext(), v8::internal::maglev::MaglevGraphBuilder::SaveCallSpeculationScope::GetSpeculationMode(), v8::internal::compiler::BytecodeGraphBuilder::GetSpeculationMode(), v8::internal::compiler::anonymous_namespace{typed-optimization.cc}::GetStableMapFromObjectType(), v8::internal::maglev::ValueNode::GetStaticType(), v8::internal::compiler::DescriptorArrayRef::GetStrongValue(), v8::internal::compiler::MapRef::GetStrongValue(), v8::internal::compiler::JSProxyRef::GetTarget(), v8::internal::maglev::KnownNodeAspects::GetType(), v8::internal::compiler::anonymous_namespace{js-native-context-specialization.cc}::GetTypedArrayConstant(), v8::internal::compiler::NativeContextRef::GlobalIsDetached(), v8::internal::compiler::SharedFunctionInfoRef::HasBreakInfo(), v8::internal::maglev::KnownNodeAspects::HasDisjointType(), v8::internal::maglev::MaglevGraphBuilder::HasValidInitialMap(), v8::internal::maglev::KnownNodeAspects::HaveDisjointTypes(), v8::internal::compiler::HeapObjectData::HeapObjectData(), v8::internal::compiler::if(), v8::internal::compiler::SourceTextModuleRef::import_meta(), v8::internal::maglev::MaglevGraphBuilder::InferHasInPrototypeChain(), v8::internal::compiler::NodeProperties::InferMapsUnsafe(), v8::internal::compiler::turboshaft::PipelineData::InitializeBrokerAndDependencies(), v8::internal::compiler::JSFunctionRef::InitialMapInstanceSizeWithMinSlack(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::InitialMapDependency::Install(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PrototypePropertyDependency::Install(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::StableMapDependency::Install(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ConstantInDictionaryPrototypeChainDependency::Install(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::TransitionDependency::Install(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PretenureModeDependency::Install(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldRepresentationDependency::Install(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldTypeDependency::Install(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldConstnessDependency::Install(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::GlobalPropertyDependency::Install(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ContextCellDependency::Install(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::EmptyContextExtensionDependency::Install(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ProtectorDependency::Install(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ElementsKindDependency::Install(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::InitialMapInstanceSizePredictionDependency::Install(), v8::internal::compiler::MapRef::instance_descriptors(), v8::internal::compiler::anonymous_namespace{heap-refs.cc}::InstanceSizeWithMinSlack(), v8::internal::compiler::JSTypedArrayRef::is_off_heap_non_rab_gsab(), v8::internal::compiler::FunctionTemplateInfoRef::is_signature_undefined(), v8::internal::compiler::MapRef::IsBooleanMap(), v8::internal::compiler::JSFunctionData::IsConsistentWithHeapState(), v8::internal::compiler::JSFunctionRef::IsConsistentWithHeapState(), v8::internal::compiler::MapRef::IsFixedCowArrayMap(), v8::internal::compiler::SharedFunctionInfoRef::IsInlineable(), v8::internal::maglev::IsInstanceOfLeafNodeType(), v8::internal::maglev::IsInstanceOfNodeType(), v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::IsLiteralString(), v8::internal::compiler::MapRef::IsNullMap(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::IsSloppyMappedArgumentsObject(), v8::internal::compiler::anonymous_namespace{js-native-context-specialization.cc}::IsStringConstant(), v8::internal::compiler::anonymous_namespace{js-native-context-specialization.cc}::IsStringWithNonAccessibleContent(), v8::internal::compiler::JSPrimitiveWrapperRef::IsStringWrapper(), v8::internal::compiler::MapRef::IsUndefinedMap(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ConstantInDictionaryPrototypeChainDependency::IsValid(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDictionaryPropertyDependency::IsValid(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ConsistentJSFunctionViewDependency::IsValid(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldRepresentationDependency::IsValid(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldTypeDependency::IsValid(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldConstnessDependency::IsValid(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::GlobalPropertyDependency::IsValid(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantElementDependency::IsValid(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::InitialMapInstanceSizePredictionDependency::IsValid(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::IteratingArrayBuiltinHelper::IteratingArrayBuiltinHelper(), v8::internal::compiler::JSFunctionData::JSFunctionData(), v8::internal::compiler::JSTypedArrayRef::length(), v8::internal::compiler::JSArrayRef::length_unsafe(), v8::internal::compiler::FunctionTemplateInfoRef::LookupHolderOfExpectedType(), v8::internal::compiler::BitsetType::Lub(), v8::internal::compiler::MakeRef(), v8::internal::compiler::MakeRefAssumeMemoryFence(), v8::internal::compiler::HeapObjectRef::map_direct_read(), v8::internal::compiler::MapData::MapData(), v8::internal::compiler::anonymous_namespace{js-create-lowering.cc}::MapForCollectionIterationKind(), v8::internal::maglev::KnownNodeAspects::MayBeNullOrUndefined(), v8::internal::compiler::JSNativeContextSpecialization::native_context(), v8::internal::compiler::JSFunctionRef::native_context(), v8::internal::compiler::AllocationSiteRef::nested_site(), v8::internal::compiler::ObjectData::ObjectData(), v8::internal::compiler::StringRef::ObjectIfContentAccessible(), v8::internal::compiler::MapRef::oddball_type(), v8::internal::compiler::OperationTyper::OperationTyper(), v8::internal::compiler::ScopeInfoRef::OuterScopeInfo(), v8::internal::compiler::turboshaft::Pipeline::PrepareForInstructionSelection(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PrototypePropertyDependency::PrepareInstall(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::InitialMapInstanceSizePredictionDependency::PrepareInstall(), v8::internal::compiler::ContextRef::previous(), v8::internal::maglev::MaglevGraphBuilder::Print(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), cppgc::internal::MarkerBase::ProcessWeakness(), v8::internal::compiler::MapRef::prototype(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PrototypePropertyDependency::PrototypePropertyDependency(), v8::internal::compiler::MapRef::PrototypesElementsDoNotHaveAccessorsOrThrow(), v8::internal::compiler::anonymous_namespace{js-native-context-specialization.cc}::PushRegularApiCallInputs(), v8::internal::compiler::JSObjectRef::raw_properties_or_hash(), v8::internal::compiler::JSObjectRef::RawInobjectPropertyAt(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForGlobalAccess(), v8::internal::compiler::anonymous_namespace{heap-refs.cc}::RecordConsistentJSFunctionViewDependencyIfNeeded(), v8::internal::maglev::MaglevGraphBuilder::ReduceCallWithArrayLikeForArgumentsObject(), v8::internal::compiler::HeapObjectMatcherImpl< kHeapConstantOpcode >::Ref(), v8::internal::compiler::ElementAccessFeedback::Refine(), v8::internal::compiler::RepresentationSelector::RepresentationSelector(), v8::internal::compiler::GraphBuilderPhase::Run(), v8::internal::compiler::ContextRef::scope_info(), v8::internal::compiler::SharedFunctionInfoRef::scope_info(), v8::internal::maglev::NodeInfo::SetPossibleMaps(), v8::internal::compiler::FeedbackCellRef::shared_function_info(), v8::internal::compiler::FeedbackVectorRef::shared_function_info(), v8::internal::compiler::JSBinopReduction::ShouldCreateConsString(), v8::internal::maglev::MaglevGraphBuilder::ShouldEagerInlineCall(), v8::internal::compiler::anonymous_namespace{js-generic-lowering.cc}::ShouldUseMegamorphicAccessBuiltin(), v8::internal::compiler::RegExpBoilerplateDescriptionRef::source(), v8::internal::compiler::BytecodeArrayRef::SourcePositionTable(), v8::internal::maglev::StaticTypeForConstant(), v8::internal::maglev::StaticTypeForMap(), v8::internal::maglev::ValueNode::StaticTypeIs(), v8::internal::compiler::MapRef::supports_fast_array_iteration(), v8::internal::compiler::MapRef::supports_fast_array_resize(), v8::internal::compiler::anonymous_namespace{heap-refs.cc}::SupportsFastArrayIteration(), v8::internal::compiler::anonymous_namespace{heap-refs.cc}::SupportsFastArrayResize(), v8::internal::compiler::ContextCellRef::tagged_value(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::TargetIsClassConstructor(), v8::internal::maglev::MaglevAssembler::ToBoolean(), v8::internal::compiler::StringRef::ToInt(), v8::internal::compiler::StringRef::ToNumber(), v8::internal::compiler::TraceInvalidCompilationDependency(), v8::internal::compiler::turboshaft::Pipeline::TraceSequence(), v8::internal::compiler::turboshaft::anonymous_namespace{instruction-selection-phase.cc}::TraceSequence(), v8::internal::maglev::MaglevGraphBuilder::TryBuildAndAllocateJSGeneratorObject(), v8::internal::maglev::MaglevGraphBuilder::TryBuildCallKnownApiFunction(), v8::internal::maglev::MaglevGraphBuilder::TryBuildCallKnownJSFunction(), v8::internal::maglev::MaglevGraphBuilder::TryBuildElementAccess(), v8::internal::maglev::MaglevGraphBuilder::TryBuildElementAccessOnTypedArray(), v8::internal::maglev::MaglevGraphBuilder::TryBuildElementStoreOnJSArrayOrJSObject(), v8::internal::maglev::MaglevGraphBuilder::TryBuildFastCreateObjectOrArrayLiteral(), v8::internal::maglev::MaglevGraphBuilder::TryBuildFastInstanceOf(), v8::internal::maglev::MaglevGraphBuilder::TryBuildFastInstanceOfWithFeedback(), v8::internal::maglev::MaglevGraphBuilder::TryBuildFastOrdinaryHasInstance(), v8::internal::maglev::MaglevGraphBuilder::TryBuildFindNonDefaultConstructorOrConstruct(), v8::internal::maglev::MaglevGraphBuilder::TryBuildInlineCall(), v8::internal::maglev::MaglevGraphBuilder::TryBuildLoadDataView(), v8::internal::maglev::MaglevGraphBuilder::TryBuildLoadNamedProperty(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPolymorphicPropertyAccess(), v8::internal::maglev::MaglevGraphBuilder::TryBuildStoreDataView(), v8::internal::compiler::FixedArrayRef::TryGet(), v8::internal::compiler::HeapObjectData::TryGetBooleanValue(), v8::internal::compiler::HeapObjectData::TryGetBooleanValueImpl(), v8::internal::compiler::turboshaft::TryGetBuiltinId(), v8::internal::maglev::ValueNode::TryGetConstant(), v8::internal::compiler::anonymous_namespace{constant-folding-reducer.cc}::TryGetConstant(), v8::internal::maglev::MaglevGraphBuilder::TryGetNonEscapingArgumentsObject(), v8::internal::compiler::BytecodeGraphBuilder::TryGetScopeInfo(), v8::internal::maglev::MaglevGraphBuilder::TryInferApiHolderValue(), v8::internal::maglev::MaglevGraphBuilder::TryReadBoilerplateForFastLiteral(), v8::internal::maglev::MaglevGraphBuilder::TryReduceArrayIteratingBuiltin(), v8::internal::maglev::MaglevGraphBuilder::TryReduceCallForApiFunction(), v8::internal::maglev::MaglevGraphBuilder::TryReduceCallForConstant(), v8::internal::maglev::MaglevGraphBuilder::TryReduceCallForNewClosure(), v8::internal::maglev::MaglevGraphBuilder::TryReduceConstantStringAt(), v8::internal::maglev::MaglevGraphBuilder::TryReduceConstruct(), v8::internal::maglev::MaglevGraphBuilder::TryReduceConstructArrayConstructor(), v8::internal::maglev::MaglevGraphBuilder::TryReduceConstructGeneric(), v8::internal::maglev::MaglevGraphBuilder::TryReduceDatePrototypeGetField(), v8::internal::maglev::MaglevGraphBuilder::TryReduceFunctionPrototypeApplyCallWithReceiver(), v8::internal::maglev::MaglevGraphBuilder::TryReduceGetIterator(), v8::internal::maglev::MaglevGraphBuilder::TryReduceGetProto(), v8::internal::compiler::UnparkedScopeIfNeeded::UnparkedScopeIfNeeded(), v8::internal::maglev::KnownNodeAspects::UpdateMayHaveAliasingContexts(), v8::internal::compiler::V(), and v8::internal::compiler::FeedbackCellRef::value().
calls()
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm calls (specifically:inline JS-to-Wasm wrappers and then ` `the body of the Wasm function, if applicable) [inline]
Referenced by v8::internal::compiler::JSInliningHeuristic::CreateOrReuseDispatch(), v8::internal::compiler::JSInliningHeuristic::InlineCandidate(), and v8::internal::compiler::JSInliningHeuristic::TryReuseDispatch().
DEFINE_BOOL() [1/68]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot DEFINE_BOOL (abort_on_bad_builtin_profile_data , false , `flag for mksnapshot, abort if builtins profile can 't be applied`)
DEFINE_BOOL() [2/68]
Disallow flags or implications overriding each other abort_on_contradictory_flags DEFINE_BOOL (allow_overwriting_for_next_flag , false , `temporary disable flag contradiction to allow overwriting just ` `the next flag`)
DEFINE_BOOL() [3/68]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and reclaim otherwise unreachable unmodified wrapper objects when possible discard the memory pool before invoking the GC on memory pressure or last resort GCs Delay before memory reducer start virtual randomize memory reservations by ignoring any hints passed when allocating pages use incremental marking for CppHeap cppheap_concurrent_marking c value for membalancer A special constant to balance between memory and space tradeoff The smaller the more memory it uses enable use of SSE4 instructions if available enable use of SAHF instruction if enable use of AVX VNNI instructions if available enable use of POPCNT instruction if available force all emitted branches to be in long enable use of partial constant enable optional features on the simulator for enable mitigation for Intel JCC erratum on affected CPUs enable unaligned accesses for the regexp engine enable deserializing code caches on background enable type checks based on instance types provided by the embedder expose externalize string extension show built in functions in stack traces disallow eval and friends Notify Api callback about exceptions thrown in Api callbacks DEFINE_BOOL (allow_unsafe_function_constructor , false , `allow invoking the function constructor without security checks`)
DEFINE_BOOL() [4/68]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics DEFINE_BOOL (compact_code_space , true , `Perform code space compaction on full collections.`)
DEFINE_BOOL() [5/68]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC DEFINE_BOOL (compact_with_stack , true , `Perform compaction when finalizing a full GC with stack`)
DEFINE_BOOL() [6/68]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads DEFINE_BOOL (concurrent_array_buffer_sweeping , true , `concurrently sweep array buffers`)
DEFINE_BOOL() [7/68]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and reclaim otherwise unreachable unmodified wrapper objects when possible discard the memory pool before invoking the GC on memory pressure or last resort GCs Delay before memory reducer start DEFINE_BOOL (concurrent_marking_high_priority_threads , false , `use high priority threads for concurrent Marking`)
DEFINE_BOOL() [8/68]
other heap size generate builtins concurrently on separate threads in mksnapshot DEFINE_BOOL (concurrent_recompilation , true , `optimizing hot functions asynchronously on a separate thread`)
DEFINE_BOOL() [9/68]
other heap size generate builtins concurrently on separate threads in mksnapshot track concurrent recompilation artificial compilation delay in ms DEFINE_BOOL (concurrent_recompilation_front_running , true , `move compile jobs to the front if recompilation is requested ` `multiple times`)
DEFINE_BOOL() [10/68]
refactor address components for immediate indexing DEFINE_BOOL (concurrent_turbo_tracing , false , `allow concurrent compilation to happen in combination with ` `trace-turbo* flags`)
DEFINE_BOOL() [11/68]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and reclaim otherwise unreachable unmodified wrapper objects when possible discard the memory pool before invoking the GC on memory pressure or last resort GCs Delay before memory reducer start virtual randomize memory reservations by ignoring any hints passed when allocating pages use incremental marking for CppHeap DEFINE_BOOL (cppheap_concurrent_marking , false , `use concurrent marking for CppHeap`)
DEFINE_BOOL() [12/68]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause DEFINE_BOOL (detect_ineffective_gcs_near_heap_limit , true , `trigger out-of-memory failure to avoid GC storm near heap limit`)
DEFINE_BOOL() [13/68]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and reclaim otherwise unreachable unmodified wrapper objects when possible discard the memory pool before invoking the GC on memory pressure or last resort GCs Delay before memory reducer start virtual randomize memory reservations by ignoring any hints passed when allocating pages use incremental marking for CppHeap cppheap_concurrent_marking c value for membalancer A special constant to balance between memory and space tradeoff The smaller the more memory it uses enable use of SSE4 instructions if available enable use of SAHF instruction if enable use of AVX VNNI instructions if available DEFINE_BOOL (enable_avx_vnni_int8 , true , `enable use of AVX-VNNI-INT8 instructions if available`)
DEFINE_BOOL() [14/68]
Disallow flags or implications overriding each other abort_on_contradictory_flags subclassing support in built in methods DEFINE_BOOL (enable_sharedarraybuffer_per_context , false , `enable the SharedArrayBuffer constructor per context`)
DEFINE_BOOL() [15/68]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and reclaim otherwise unreachable unmodified wrapper objects when possible discard the memory pool before invoking the GC on memory pressure or last resort GCs Delay before memory reducer start virtual randomize memory reservations by ignoring any hints passed when allocating pages use incremental marking for CppHeap cppheap_concurrent_marking c value for membalancer A special constant to balance between memory and space tradeoff The smaller the more memory it uses enable use of SSE4 instructions if available enable use of SAHF instruction if enable use of AVX VNNI instructions if available enable use of POPCNT instruction if available force all emitted branches to be in long enable use of partial constant enable optional features on the simulator for enable mitigation for Intel JCC erratum on affected CPUs DEFINE_BOOL (enable_source_at_csa_bind , false , `Include source information in the binary at CSA bind locations.`)
DEFINE_BOOL() [16/68]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and reclaim otherwise unreachable unmodified wrapper objects when possible discard the memory pool before invoking the GC on memory pressure or last resort GCs Delay before memory reducer start virtual randomize memory reservations by ignoring any hints passed when allocating pages use incremental marking for CppHeap cppheap_concurrent_marking c value for membalancer A special constant to balance between memory and space tradeoff The smaller the more memory it uses enable use of SSE4 instructions if available DEFINE_BOOL (enable_sse4_2 , true , `enable use of SSE4.2 instructions if available`)
DEFINE_BOOL() [17/68]
Disallow flags or implications overriding each other DEFINE_BOOL (exit_on_contradictory_flags , false , `Exit with return code 0 on contradictory flags.`)
DEFINE_BOOL() [18/68]
DEFINE_BOOL (experimental , false , `Indicates that V8 is running with experimental features enabled. ` `This flag is typically not set explicitly but instead enabled as ` `an implication of other flags which enable experimental features.`)
DEFINE_BOOL() [19/68]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and reclaim otherwise unreachable unmodified wrapper objects when possible discard the memory pool before invoking the GC on memory pressure or last resort GCs Delay before memory reducer start virtual randomize memory reservations by ignoring any hints passed when allocating pages use incremental marking for CppHeap cppheap_concurrent_marking c value for membalancer A special constant to balance between memory and space tradeoff The smaller the more memory it uses enable use of SSE4 instructions if available enable use of SAHF instruction if enable use of AVX VNNI instructions if available enable use of POPCNT instruction if available force all emitted branches to be in long enable use of partial constant enable optional features on the simulator for enable mitigation for Intel JCC erratum on affected CPUs enable unaligned accesses for the regexp engine enable deserializing code caches on background enable type checks based on instance types provided by the embedder expose externalize string extension show built in functions in stack traces DEFINE_BOOL (experimental_stack_trace_frames , false , `enable experimental frames (API/Builtins) and stack trace layout`)
DEFINE_BOOL() [20/68]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and reclaim otherwise unreachable unmodified wrapper objects when possible discard the memory pool before invoking the GC on memory pressure or last resort GCs Delay before memory reducer start virtual randomize memory reservations by ignoring any hints passed when allocating pages use incremental marking for CppHeap cppheap_concurrent_marking c value for membalancer A special constant to balance between memory and space tradeoff The smaller the more memory it uses enable use of SSE4 instructions if available enable use of SAHF instruction if enable use of AVX VNNI instructions if available enable use of POPCNT instruction if available force all emitted branches to be in long enable use of partial constant enable optional features on the simulator for enable mitigation for Intel JCC erratum on affected CPUs enable unaligned accesses for the regexp engine enable deserializing code caches on background enable type checks based on instance types provided by the embedder expose externalize string extension DEFINE_BOOL (expose_ignition_statistics , false , `expose ignition-statistics extension (requires building with ` `v8_enable_ignition_dispatch_counting)`)
DEFINE_BOOL() [21/68]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled DEFINE_BOOL (external_memory_accounted_in_global_limit , false , `External memory limits are computed as part of global limits in v8 Heap.`)
DEFINE_BOOL() [22/68]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently DEFINE_BOOL (flush_bytecode , true , `flush of bytecode when it has not been executed recently`)
DEFINE_BOOL() [23/68]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age DEFINE_BOOL (flush_code_based_on_tab_visibility , false , `Flush code when tab goes into the background.`)
DEFINE_BOOL() [24/68]
DEFINE_BOOL (future , FUTURE_BOOL , `Implies all staged features that we want to ship in the ` `not-too-far future`)
DEFINE_BOOL() [25/68]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and reclaim otherwise unreachable unmodified wrapper objects when possible discard the memory pool before invoking the GC on memory pressure or last resort GCs DEFINE_BOOL (gc_experiment_less_compaction , false , `less compaction in non-memory reducing mode`)
DEFINE_BOOL() [26/68]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed DEFINE_BOOL (incremental_marking_start_user_visible , true , `Starts incremental marking with kUserVisible priority.`)
DEFINE_BOOL() [27/68]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and reclaim otherwise unreachable unmodified wrapper objects when possible discard the memory pool before invoking the GC on memory pressure or last resort GCs Delay before memory reducer start virtual randomize memory reservations by ignoring any hints passed when allocating pages use incremental marking for CppHeap cppheap_concurrent_marking c value for membalancer A special constant to balance between memory and space tradeoff The smaller the more memory it uses DEFINE_BOOL (late_heap_limit_check , false , `skips heap limit check for early GCs on allocation failure.`)
DEFINE_BOOL() [28/68]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval DEFINE_BOOL (lazy_new_space_shrinking , false , `Enables the lazy new space shrinking strategy`)
DEFINE_BOOL() [29/68]
DEFINE_BOOL (lite_mode , V8_LITE_MODE_BOOL , `enables trade-off of performance for memory savings`)
DEFINE_BOOL() [30/68]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder DEFINE_BOOL (log_or_trace_osr , false , `internal helper flag, please use --trace-osr instead.`)
DEFINE_BOOL() [31/68]
force emit tier up logic from all non turbofan even if it is the top enabled tier make OptimizeFunctionOnNextCall optimize to maglev instead of turbofan enable loop peeling in the maglev optimizing compiler max loop size for loop peeling in the maglev optimizing compiler Generate deopt data on background thread DEFINE_BOOL (maglev_build_code_on_background , true , `Generate code on background thread`)
DEFINE_BOOL() [32/68]
force emit tier up logic from all non turbofan even if it is the top enabled tier make OptimizeFunctionOnNextCall optimize to maglev instead of turbofan enable loop peeling in the maglev optimizing compiler max loop size for loop peeling in the maglev optimizing compiler Generate deopt data on background thread maglev_deopt_data_on_background Inline CallApiCallback builtin into generated code DEFINE_BOOL (maglev_cons_string_elision , true , `Native support for cons strings and their elision in maglev.`)
DEFINE_BOOL() [33/68]
force emit tier up logic from all non turbofan even if it is the top enabled tier make OptimizeFunctionOnNextCall optimize to maglev instead of turbofan enable loop peeling in the maglev optimizing compiler max loop size for loop peeling in the maglev optimizing compiler Generate deopt data on background thread maglev_deopt_data_on_background DEFINE_BOOL (maglev_destroy_on_background , true , `Destroy compilation jobs on background thread`)
DEFINE_BOOL() [34/68]
force emit tier up logic from all non turbofan even if it is the top enabled tier make OptimizeFunctionOnNextCall optimize to maglev instead of turbofan DEFINE_BOOL (maglev_inlining , true , `enable inlining in the maglev optimizing compiler`)
DEFINE_BOOL() [35/68]
force emit tier up logic from all non turbofan even if it is the top enabled tier make OptimizeFunctionOnNextCall optimize to maglev instead of turbofan enable loop peeling in the maglev optimizing compiler DEFINE_BOOL (maglev_optimistic_peeled_loops , true , `enable aggressive optimizations for loops (loop SPeeling) in the ` `maglev optimizing compiler`)
DEFINE_BOOL() [36/68]
force emit tier up logic from all non turbofan even if it is the top enabled tier make OptimizeFunctionOnNextCall optimize to maglev instead of turbofan enable loop peeling in the maglev optimizing compiler max loop size for loop peeling in the maglev optimizing compiler Generate deopt data on background thread maglev_deopt_data_on_background Inline CallApiCallback builtin into generated code Recursively pretenure values which are stored into pretenured allocation sites use high priority compiler threads for concurrent Maglev max depth of functions that Maglev will incl small functions maximum cumulative size of bytecode considered for inlining excl small functions minimum frequency for inlining reuse stack slots in the maglev optimizing compiler DEFINE_BOOL (maglev_untagged_phis , true , `enable phi untagging in the maglev optimizing compiler`)
DEFINE_BOOL() [37/68]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds DEFINE_BOOL (managed_zone_memory , false , `Manage zone memory in V8 instead of using malloc().`)
DEFINE_BOOL() [38/68]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and reclaim otherwise unreachable unmodified wrapper objects when possible discard the memory pool before invoking the GC on memory pressure or last resort GCs Delay before memory reducer start virtual randomize memory reservations by ignoring any hints passed when allocating pages DEFINE_BOOL (manual_evacuation_candidates_selection , false , `Test mode only flag. It allows an unit test to select evacuation ` `candidates pages (requires --stress_compaction).`) [virtual]
DEFINE_BOOL() [39/68]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and reclaim otherwise unreachable unmodified wrapper objects when possible discard the memory pool before invoking the GC on memory pressure or last resort GCs Delay before memory reducer start virtual randomize memory reservations by ignoring any hints passed when allocating pages use incremental marking for CppHeap cppheap_concurrent_marking DEFINE_BOOL (memory_balancer , false , `use membalancer, ` `a new heap limit balancing algorithm`)
DEFINE_BOOL() [40/68]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag DEFINE_BOOL (memory_reducer_for_small_heaps , true , `use memory reducer for small heaps`)
DEFINE_BOOL() [41/68]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC DEFINE_BOOL (memory_reducer_respects_frozen_state , false , `don't schedule another GC when we are frozen`)
DEFINE_BOOL() [42/68]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and reclaim otherwise unreachable unmodified wrapper objects when possible discard the memory pool before invoking the GC on memory pressure or last resort GCs Delay before memory reducer start virtual randomize memory reservations by ignoring any hints passed when allocating pages use incremental marking for CppHeap cppheap_concurrent_marking c value for membalancer A special constant to balance between memory and space tradeoff The smaller the more memory it uses enable use of SSE4 instructions if available enable use of SAHF instruction if enable use of AVX VNNI instructions if available enable use of POPCNT instruction if available force all emitted branches to be in long enable use of partial constant enable optional features on the simulator for enable mitigation for Intel JCC erratum on affected CPUs enable unaligned accesses for the regexp engine enable deserializing code caches on background DEFINE_BOOL (merge_background_deserialized_script_with_compilation_cache , true , `After deserializing code cache data on a background thread, merge it into ` `an existing Script if one is found in the Isolate compilation cache`)
DEFINE_BOOL() [43/68]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping DEFINE_BOOL (parallel_pointer_update , true , `use parallel pointer update during compaction`)
DEFINE_BOOL() [44/68]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and reclaim otherwise unreachable unmodified wrapper objects when possible DEFINE_BOOL (parallel_reclaim_unmodified_wrappers , true , `reclaim wrapper objects in parallel`)
DEFINE_BOOL() [45/68]
use conservative stack scanning use direct handles with conservative stack scanning Treat some precise references as conservative references to stress test object pinning in Scavenger minor_gc_task Enables random stressing of object pinning in such that each GC would randomly pick a subset of the precise references to treat conservatively Objects reachable from handles during scavenge will be pinned and won t move DEFINE_BOOL (precise_object_pinning , false , `Objects reachable from handles during GC will be pinned and won't move.`)
DEFINE_BOOL() [46/68]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer DEFINE_BOOL (profile_guided_optimization_for_empty_feedback_vector , true , `profile guided optimization for empty feedback vector`)
DEFINE_BOOL() [47/68]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed DEFINE_BOOL (reopt_after_lazy_deopts , true , `Immediately re-optimize code after some lazy deopts`)
DEFINE_BOOL() [48/68]
use conservative stack scanning use direct handles with conservative stack scanning DEFINE_BOOL (scavenger_conservative_object_pinning , false , `Objects reachable from the native stack during ` `scavenge will be pinned and ` `won't move.`)
DEFINE_BOOL() [49/68]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack DEFINE_BOOL (shortcut_strings_with_stack , true , `Shortcut Strings during GC with stack`)
DEFINE_BOOL() [50/68]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and reclaim otherwise unreachable unmodified wrapper objects when possible discard the memory pool before invoking the GC on memory pressure or last resort GCs Delay before memory reducer start virtual randomize memory reservations by ignoring any hints passed when allocating pages use incremental marking for CppHeap cppheap_concurrent_marking c value for membalancer A special constant to balance between memory and space tradeoff The smaller the more memory it uses enable use of SSE4 instructions if available enable use of SAHF instruction if enable use of AVX VNNI instructions if available enable use of POPCNT instruction if available force all emitted branches to be in long enable use of partial constant enable optional features on the simulator for enable mitigation for Intel JCC erratum on affected CPUs enable unaligned accesses for the regexp engine DEFINE_BOOL (stress_background_compile , false , `stress test parsing on background`)
DEFINE_BOOL() [51/68]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects DEFINE_BOOL (stress_compaction_random , false , `Stress GC compaction by selecting random percent of pages as ` `evacuation candidates. Overrides stress_compaction.`)
DEFINE_BOOL() [52/68]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active DEFINE_BOOL (stress_per_context_marking_worklist , false , `Use per-context worklist for marking`)
DEFINE_BOOL() [53/68]
DEFINE_BOOL (stress_turbo_late_spilling , false , `optimize placement of all spill instructions, not just loop-top phis`)
DEFINE_BOOL() [54/68]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected DEFINE_BOOL (trace_detached_contexts , false , `trace native contexts that are expected to be garbage collected`)
DEFINE_BOOL() [55/68]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values DEFINE_BOOL (trace_environment_liveness , false , `trace liveness of local variable slots`)
DEFINE_BOOL() [56/68]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections DEFINE_BOOL (trace_gc , false , `print one trace line following each garbage collection`)
DEFINE_BOOL() [57/68]
other heap size generate builtins concurrently on separate threads in mksnapshot track concurrent recompilation artificial compilation delay in ms max number of threads that concurrent Turbofan can create additional concurrent optimization jobs but throw away result whether maglev resets the interrupt budget whether maglev resets the OSR interrupt budget create additional concurrent optimization jobs maximum levels for nesting child serializers DEFINE_BOOL (trace_heap_broker_verbose , false , `trace the heap broker verbosely (all reports)`)
DEFINE_BOOL() [58/68]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking DEFINE_BOOL (track_gc_object_stats , false , `track object counts and memory usage`)
DEFINE_BOOL() [59/68]
too high values may cause the compiler to set high thresholds for inlining to as much as possible DEFINE_BOOL (turbo_inline_array_builtins , true , `inline array builtins in TurboFan code`)
DEFINE_BOOL() [60/68]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan DEFINE_BOOL (turbo_instruction_scheduling , false , `enable instruction scheduling in TurboFan`)
DEFINE_BOOL() [61/68]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers DEFINE_BOOL (turbo_optimize_math_minmax , true , `optimize call math.min/max with double array`)
DEFINE_BOOL() [62/68]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination DEFINE_BOOL (turbo_profiling_verbose , false , `enable basic block profiling in TurboFan, and include each ` `function 's schedule and disassembly in the output`)
DEFINE_BOOL() [63/68]
refactor address components for immediate indexing make OptimizeMaglevOnNextCall optimize to turbofan instead of maglev filter for tracing turbofan compilation trace turbo cfg trace TurboFan s graph trimmer trace TurboFan s control equivalence trace TurboFan s register allocator trace stack load store counters for optimized code in run fuzzing&& concurrent_recompilation trace_turbo trace_turbo_scheduled trace_turbo_stack_accesses verify TurboFan machine graph of code stubs path where to generate builtins effects enable FixedArray bounds checks DEFINE_BOOL (turbo_stats_nvp , false , `print TurboFan statistics in machine-readable format`)
DEFINE_BOOL() [64/68]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information DEFINE_BOOL (turbolev , false , `use Turbolev (Maglev + Turboshaft combined) as the 4th tier ` `compiler instead of Turbofan`)
DEFINE_BOOL() [65/68]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls DEFINE_BOOL (turboshaft_load_elimination , true , `enable Turboshaft's low-level load elimination for JS`)
DEFINE_BOOL() [66/68]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling DEFINE_BOOL (turboshaft_string_concat_escape_analysis , true , `enable Turboshaft's escape analysis for string concatenation`)
DEFINE_BOOL() [67/68]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations DEFINE_BOOL (turboshaft_wasm_load_elimination , true , `enable Turboshaft's WasmLoadElimination`)
DEFINE_BOOL() [68/68]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future DEFINE_BOOL (typed_array_length_loading , true , `Enable specializing loading the TypedArray length in Maglev / Turbofan`)
DEFINE_BOOL_READONLY() [1/8]
DEFINE_BOOL_READONLY (disable_write_barriers , V8_DISABLE_WRITE_BARRIERS_BOOL , `disable write barriers when GC is non-incremental ` `and heap contains single generation.`)
DEFINE_BOOL_READONLY() [2/8]
DEFINE_BOOL_READONLY (local_off_stack_check , V8_ENABLE_LOCAL_OFF_STACK_CHECK_BOOL , `check for off-stack allocation of v8::Local`)
DEFINE_BOOL_READONLY() [3/8]
force emit tier up logic from all non turbofan even if it is the top enabled tier DEFINE_BOOL_READONLY (maglev_future , false , `enable maglev features that we want to ship in the not-too-far future`)
DEFINE_BOOL_READONLY() [4/8]
DEFINE_BOOL_READONLY (single_generation , V8_SINGLE_GENERATION_BOOL , `allocate all objects from young generation to old generation`)
DEFINE_BOOL_READONLY() [5/8]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode DEFINE_BOOL_READONLY (turbo_compress_frame_translations , false , `compress deoptimization frame translations (experimental)`)
DEFINE_BOOL_READONLY() [6/8]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan DEFINE_BOOL_READONLY (turbo_typer_hardening , true , `extra bounds checks to protect against some known typer ` `mismatch exploit techniques (best effort)`)
DEFINE_BOOL_READONLY() [7/8]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps DEFINE_BOOL_READONLY (turboshaft_trace_emitted , false , `trace emitted Turboshaft instructions`)
DEFINE_BOOL_READONLY() [8/8]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps DEFINE_BOOL_READONLY (turboshaft_trace_load_elimination , false , `trace Turboshaft's late load elimination`)
DEFINE_DISABLE_FLAG_IMPLICATION() [1/2]
refactor address components for immediate indexing make OptimizeMaglevOnNextCall optimize to turbofan instead of maglev filter for tracing turbofan compilation trace turbo cfg trace TurboFan s graph trimmer trace TurboFan s control equivalence trace TurboFan s register allocator trace stack load store counters for optimized code in run fuzzing&& concurrent_recompilation trace_turbo DEFINE_DISABLE_FLAG_IMPLICATION (fuzzing_and_concurrent_recompilation , trace_turbo_graph)
DEFINE_DISABLE_FLAG_IMPLICATION() [2/2]
refactor address components for immediate indexing make OptimizeMaglevOnNextCall optimize to turbofan instead of maglev filter for tracing turbofan compilation trace turbo cfg trace TurboFan s graph trimmer trace TurboFan s control equivalence trace TurboFan s register allocator trace stack load store counters for optimized code in run fuzzing&& concurrent_recompilation trace_turbo trace_turbo_scheduled DEFINE_DISABLE_FLAG_IMPLICATION (fuzzing_and_concurrent_recompilation , trace_turbo_reduction)
DEFINE_EXPERIMENTAL_FEATURE() [1/4]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority DEFINE_EXPERIMENTAL_FEATURE (cppgc_young_generation , `run young generation garbage collections in Oilpan`)
DEFINE_EXPERIMENTAL_FEATURE() [2/4]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape DEFINE_EXPERIMENTAL_FEATURE (maglev_object_tracking , `track object changes to avoid escaping them`)
DEFINE_EXPERIMENTAL_FEATURE() [3/4]
force emit tier up logic from all non turbofan even if it is the top enabled tier make OptimizeFunctionOnNextCall optimize to maglev instead of turbofan enable loop peeling in the maglev optimizing compiler max loop size for loop peeling in the maglev optimizing compiler Generate deopt data on background thread maglev_deopt_data_on_background Inline CallApiCallback builtin into generated code Recursively pretenure values which are stored into pretenured allocation sites use high priority compiler threads for concurrent Maglev max depth of functions that Maglev will incl small functions maximum cumulative size of bytecode considered for inlining excl small functions minimum frequency for inlining reuse stack slots in the maglev optimizing compiler enable phi untagging to hoist untagging of osr values DEFINE_EXPERIMENTAL_FEATURE (maglev_speculative_hoist_phi_untagging , `enable phi untagging to hoist untagging of loop phi inputs (could ` `still cause deopt loops)`)
DEFINE_EXPERIMENTAL_FEATURE() [4/4]
force emit tier up logic from all non turbofan even if it is the top enabled tier make OptimizeFunctionOnNextCall optimize to maglev instead of turbofan enable loop peeling in the maglev optimizing compiler max loop size for loop peeling in the maglev optimizing compiler Generate deopt data on background thread maglev_deopt_data_on_background Inline CallApiCallback builtin into generated code Recursively pretenure values which are stored into pretenured allocation sites use high priority compiler threads for concurrent Maglev max depth of functions that Maglev will incl small functions maximum cumulative size of bytecode considered for inlining excl small functions minimum frequency for inlining reuse stack slots in the maglev optimizing compiler enable phi untagging to hoist untagging of osr values enable Maglev non eager inlining DEFINE_EXPERIMENTAL_FEATURE (turbolev_non_eager_inlining , `enable Turbolev non-eager inlining`)
DEFINE_FLOAT()
refactor address components for immediate indexing make OptimizeMaglevOnNextCall optimize to turbofan instead of maglev filter for tracing turbofan compilation trace turbo cfg trace TurboFan s graph trimmer trace TurboFan s control equivalence trace TurboFan s register allocator trace stack load store counters for optimized code in run fuzzing&& concurrent_recompilation trace_turbo trace_turbo_scheduled trace_turbo_stack_accesses verify TurboFan machine graph of code stubs path where to generate builtins effects enable FixedArray bounds checks print TurboFan statistics of wasm compilations maximum cumulative size of bytecode considered for inlining maximum size of small functions bytecode that can be inlining DEFINE_FLOAT (reserve_inline_budget_scale_factor , 1. 2, `scale factor of bytecode size used to calculate the inlining budget`)
DEFINE_GENERIC_IMPLICATION() [1/2]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage DEFINE_GENERIC_IMPLICATION (trace_zone_stats , TracingFlags::zone_stats. store v8::tracing::TracingCategoryObserver::ENABLED_BY_NATIVE)
DEFINE_GENERIC_IMPLICATION() [2/2]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount DEFINE_GENERIC_IMPLICATION (trace_zone_type_stats , TracingFlags::zone_stats. store v8::tracing::TracingCategoryObserver::ENABLED_BY_NATIVE)
DEFINE_IMPLICATION() [1/5]
use conservative stack scanning DEFINE_IMPLICATION (conservative_stack_scanning , scavenger_conservative_object_pinning)
DEFINE_IMPLICATION() [2/5]
other heap size generate builtins concurrently on separate threads in mksnapshot track concurrent recompilation artificial compilation delay in ms max number of threads that concurrent Turbofan can create additional concurrent optimization jobs but throw away result whether maglev resets the interrupt budget whether maglev resets the OSR interrupt budget create additional concurrent optimization jobs DEFINE_IMPLICATION (stress_concurrent_inlining_attach_code , stress_concurrent_inlining)
DEFINE_IMPLICATION() [3/5]
use conservative stack scanning use direct handles with conservative stack scanning Treat some precise references as conservative references to stress test object pinning in Scavenger DEFINE_IMPLICATION (stress_scavenger_conservative_object_pinning , scavenger_conservative_object_pinning)
DEFINE_IMPLICATION() [4/5]
use conservative stack scanning use direct handles with conservative stack scanning Treat some precise references as conservative references to stress test object pinning in Scavenger minor_gc_task Enables random stressing of object pinning in such that each GC would randomly pick a subset of the precise references to treat conservatively DEFINE_IMPLICATION (stress_scavenger_conservative_object_pinning_random , stress_scavenger_conservative_object_pinning)
DEFINE_IMPLICATION() [5/5]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking DEFINE_IMPLICATION (turbo_stress_instruction_scheduling , turbo_instruction_scheduling)
DEFINE_INT() [1/13]
other heap size generate builtins concurrently on separate threads in mksnapshot track concurrent recompilation DEFINE_INT (concurrent_recompilation_queue_length , 8 , `the length of the concurrent compilation queue`)
DEFINE_INT() [2/13]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory DEFINE_INT (ephemeron_fixpoint_iterations , 10 , `number of fixpoint iterations it takes to switch to linear ` `ephemeron algorithm`)
DEFINE_INT() [3/13]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters DEFINE_INT (heap_growing_percent , 0 , `specifies heap growing factor as (1 + heap_growing_percent/100)`)
DEFINE_INT() [4/13]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization DEFINE_INT (invocation_count_for_maglev_with_delay , 600 , `invocation count for maglev for functions which according to ` `profile_guided_optimization are likely to deoptimize before ` `reaching this invocation count`)
DEFINE_INT() [5/13]
force emit tier up logic from all non turbofan even if it is the top enabled tier make OptimizeFunctionOnNextCall optimize to maglev instead of turbofan enable loop peeling in the maglev optimizing compiler max loop size for loop peeling in the maglev optimizing compiler DEFINE_INT (maglev_loop_peeling_max_size_cumulative , 900 , `max cumulative size for loop peeling in the maglev optimizing compiler`)
DEFINE_INT() [6/13]
refactor address components for immediate indexing make OptimizeMaglevOnNextCall optimize to turbofan instead of maglev filter for tracing turbofan compilation trace turbo cfg trace TurboFan s graph trimmer trace TurboFan s control equivalence trace TurboFan s register allocator trace stack load store counters for optimized code in run fuzzing&& concurrent_recompilation trace_turbo trace_turbo_scheduled trace_turbo_stack_accesses verify TurboFan machine graph of code stubs path where to generate builtins effects enable FixedArray bounds checks print TurboFan statistics of wasm compilations DEFINE_INT (max_inlined_bytecode_size , 460 , `maximum size of bytecode for a single inlining`)
DEFINE_INT() [7/13]
refactor address components for immediate indexing make OptimizeMaglevOnNextCall optimize to turbofan instead of maglev filter for tracing turbofan compilation trace turbo cfg trace TurboFan s graph trimmer trace TurboFan s control equivalence trace TurboFan s register allocator trace stack load store counters for optimized code in run fuzzing&& concurrent_recompilation trace_turbo trace_turbo_scheduled trace_turbo_stack_accesses verify TurboFan machine graph of code stubs path where to generate builtins effects enable FixedArray bounds checks print TurboFan statistics of wasm compilations maximum cumulative size of bytecode considered for inlining DEFINE_INT (max_inlined_bytecode_size_absolute , 4600 , `maximum absolute size of bytecode considered for inlining`)
DEFINE_INT() [8/13]
refactor address components for immediate indexing make OptimizeMaglevOnNextCall optimize to turbofan instead of maglev filter for tracing turbofan compilation trace turbo cfg trace TurboFan s graph trimmer trace TurboFan s control equivalence trace TurboFan s register allocator trace stack load store counters for optimized code in run fuzzing&& concurrent_recompilation trace_turbo trace_turbo_scheduled trace_turbo_stack_accesses verify TurboFan machine graph of code stubs path where to generate builtins effects enable FixedArray bounds checks print TurboFan statistics of wasm compilations maximum cumulative size of bytecode considered for inlining maximum size of small functions bytecode that can be inlining maximum size of bytecode considered for small function inlining DEFINE_INT (max_inlined_bytecode_size_small_with_heapnum_in_out , 75 , `maximum size of bytecode considered for small function inlining, ` `when the function call has a HeapNumber as input or output`)
DEFINE_INT() [9/13]
force emit tier up logic from all non turbofan even if it is the top enabled tier make OptimizeFunctionOnNextCall optimize to maglev instead of turbofan enable loop peeling in the maglev optimizing compiler max loop size for loop peeling in the maglev optimizing compiler Generate deopt data on background thread maglev_deopt_data_on_background Inline CallApiCallback builtin into generated code Recursively pretenure values which are stored into pretenured allocation sites use high priority compiler threads for concurrent Maglev DEFINE_INT (max_maglev_inline_depth , 1 , `max depth of functions that Maglev will inline excl. small functions`)
DEFINE_INT() [10/13]
force emit tier up logic from all non turbofan even if it is the top enabled tier make OptimizeFunctionOnNextCall optimize to maglev instead of turbofan enable loop peeling in the maglev optimizing compiler max loop size for loop peeling in the maglev optimizing compiler Generate deopt data on background thread maglev_deopt_data_on_background Inline CallApiCallback builtin into generated code Recursively pretenure values which are stored into pretenured allocation sites use high priority compiler threads for concurrent Maglev max depth of functions that Maglev will incl small functions DEFINE_INT (max_maglev_inlined_bytecode_size , 460 , `maximum size of bytecode for a single inlining`) [inline]
DEFINE_INT() [11/13]
force emit tier up logic from all non turbofan even if it is the top enabled tier make OptimizeFunctionOnNextCall optimize to maglev instead of turbofan enable loop peeling in the maglev optimizing compiler max loop size for loop peeling in the maglev optimizing compiler Generate deopt data on background thread maglev_deopt_data_on_background Inline CallApiCallback builtin into generated code Recursively pretenure values which are stored into pretenured allocation sites use high priority compiler threads for concurrent Maglev max depth of functions that Maglev will incl small functions maximum cumulative size of bytecode considered for inlining excl small functions DEFINE_INT (max_maglev_inlined_bytecode_size_small , 27 , `maximum size of bytecode considered for small function inlining`)
DEFINE_INT() [12/13]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge DEFINE_INT (stress_marking , 0 , `force marking at random points between 0 and X (inclusive) percent ` `of the regular marking start limit`)
DEFINE_INT() [13/13]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and reclaim otherwise unreachable unmodified wrapper objects when possible discard the memory pool before invoking the GC on memory pressure or last resort GCs Delay before memory reducer start virtual randomize memory reservations by ignoring any hints passed when allocating pages use incremental marking for CppHeap cppheap_concurrent_marking c value for membalancer A special constant to balance between memory and space tradeoff The smaller the more memory it uses enable use of SSE4 instructions if available enable use of SAHF instruction if enable use of AVX VNNI instructions if available enable use of POPCNT instruction if available force all emitted branches to be in long enable use of partial constant enable optional features on the simulator for enable mitigation for Intel JCC erratum on affected CPUs enable unaligned accesses for the regexp engine enable deserializing code caches on background enable type checks based on instance types provided by the embedder expose externalize string extension show built in functions in stack traces disallow eval and friends Notify Api callback about exceptions thrown in Api callbacks enable testing the function context size overflow path by making the maximum size smaller DEFINE_INT (switch_table_spread_threshold , 3 , `allow the jump table used for switch statements to span a range ` `of integers roughly equal to this number times the number of ` `clauses in the switch`)
DEFINE_NEG_NEG_IMPLICATION()
refactor address components for immediate indexing make OptimizeMaglevOnNextCall optimize to turbofan instead of maglev filter for tracing turbofan compilation trace turbo cfg trace TurboFan s graph trimmer trace TurboFan s control equivalence trace TurboFan s register allocator trace stack load store counters for optimized code in run fuzzing&& concurrent_recompilation DEFINE_NEG_NEG_IMPLICATION (concurrent_recompilation , fuzzing_and_concurrent_recompilation)
DEFINE_SIZE_T() [1/2]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often DEFINE_SIZE_T (max_large_page_pool_size , 32 , `Maximum size of pooled large pages in MB.`)
DEFINE_SIZE_T() [2/2]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces DEFINE_SIZE_T (max_semi_space_size , 0 , `max size of a semi-space in MBytes, the new space consists of ` `two semi-spaces`)
DEFINE_SLOW_TRACING_BOOL() [1/3]
refactor address components for immediate indexing make OptimizeMaglevOnNextCall optimize to turbofan instead of maglev filter for tracing turbofan compilation trace turbo cfg trace TurboFan s graph trimmer trace TurboFan s control equivalence trace TurboFan s register allocator DEFINE_SLOW_TRACING_BOOL (trace_representation , false , `trace representation types`)
DEFINE_SLOW_TRACING_BOOL() [2/3]
refactor address components for immediate indexing make OptimizeMaglevOnNextCall optimize to turbofan instead of maglev filter for tracing turbofan compilation trace turbo cfg trace TurboFan s graph trimmer DEFINE_SLOW_TRACING_BOOL (trace_turbo_jt , false , `trace TurboFan's jump threading`)
DEFINE_SLOW_TRACING_BOOL() [3/3]
refactor address components for immediate indexing make OptimizeMaglevOnNextCall optimize to turbofan instead of maglev filter for tracing turbofan compilation trace turbo cfg trace TurboFan s graph trimmer trace TurboFan s control equivalence DEFINE_SLOW_TRACING_BOOL (trace_turbo_loop , false , `trace TurboFan's loop optimizations`)
DEFINE_STRING() [1/8]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and reclaim otherwise unreachable unmodified wrapper objects when possible discard the memory pool before invoking the GC on memory pressure or last resort GCs Delay before memory reducer start virtual randomize memory reservations by ignoring any hints passed when allocating pages use incremental marking for CppHeap cppheap_concurrent_marking c value for membalancer A special constant to balance between memory and space tradeoff The smaller the more memory it uses enable use of SSE4 instructions if available enable use of SAHF instruction if enable use of AVX VNNI instructions if available enable use of POPCNT instruction if available DEFINE_STRING (arm_arch , ARM_ARCH_DEFAULT , `generate instructions for the selected ARM architecture if ` `available: armv6, armv7 , armv7+sudiv or armv8`)
DEFINE_STRING() [2/8]
refactor address components for immediate indexing make OptimizeMaglevOnNextCall optimize to turbofan instead of maglev filter for tracing turbofan compilation trace turbo cfg trace TurboFan s graph trimmer trace TurboFan s control equivalence trace TurboFan s register allocator trace stack load store counters for optimized code in run fuzzing&& concurrent_recompilation trace_turbo trace_turbo_scheduled trace_turbo_stack_accesses verify TurboFan machine graph of code stubs DEFINE_STRING (csa_trap_on_node , nullptr , `trigger break point when a node with given id is created in ` `given stub. The format is: StubName, NodeId`)
DEFINE_STRING() [3/8]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data DEFINE_STRING (dump_builtins_hashes_to_file , nullptr , `flag for mksnapshot, dump CSA builtins graph hashes to this file`)
DEFINE_STRING() [4/8]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and reclaim otherwise unreachable unmodified wrapper objects when possible discard the memory pool before invoking the GC on memory pressure or last resort GCs Delay before memory reducer start virtual randomize memory reservations by ignoring any hints passed when allocating pages use incremental marking for CppHeap cppheap_concurrent_marking c value for membalancer A special constant to balance between memory and space tradeoff The smaller the more memory it uses enable use of SSE4 instructions if available enable use of SAHF instruction if enable use of AVX VNNI instructions if available enable use of POPCNT instruction if available force all emitted branches to be in long enable use of partial constant enable optional features on the simulator for enable mitigation for Intel JCC erratum on affected CPUs enable unaligned accesses for the regexp engine enable deserializing code caches on background enable type checks based on instance types provided by the embedder expose externalize string extension show built in functions in stack traces disallow eval and friends DEFINE_STRING (expose_cputracemark_as , nullptr , `expose cputracemark extension under the specified name`)
DEFINE_STRING() [5/8]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and reclaim otherwise unreachable unmodified wrapper objects when possible discard the memory pool before invoking the GC on memory pressure or last resort GCs Delay before memory reducer start virtual randomize memory reservations by ignoring any hints passed when allocating pages use incremental marking for CppHeap cppheap_concurrent_marking c value for membalancer A special constant to balance between memory and space tradeoff The smaller the more memory it uses enable use of SSE4 instructions if available enable use of SAHF instruction if enable use of AVX VNNI instructions if available enable use of POPCNT instruction if available force all emitted branches to be in long enable use of partial constant enable optional features on the simulator for enable mitigation for Intel JCC erratum on affected CPUs enable unaligned accesses for the regexp engine enable deserializing code caches on background enable type checks based on instance types provided by the embedder DEFINE_STRING (expose_gc_as , nullptr , `expose gc extension under the specified name`)
DEFINE_STRING() [6/8]
refactor address components for immediate indexing make OptimizeMaglevOnNextCall optimize to turbofan instead of maglev filter for tracing turbofan compilation DEFINE_STRING (trace_turbo_file_prefix , `turbo` , `trace turbo graph to a file with given prefix`)
DEFINE_STRING() [7/8]
refactor address components for immediate indexing make OptimizeMaglevOnNextCall optimize to turbofan instead of maglev DEFINE_STRING (trace_turbo_path , nullptr , `directory to dump generated TurboFan IR to`)
DEFINE_STRING() [8/8]
refactor address components for immediate indexing make OptimizeMaglevOnNextCall optimize to turbofan instead of maglev filter for tracing turbofan compilation trace turbo cfg trace TurboFan s graph trimmer trace TurboFan s control equivalence trace TurboFan s register allocator trace stack load store counters for optimized code in run fuzzing&& concurrent_recompilation trace_turbo trace_turbo_scheduled trace_turbo_stack_accesses DEFINE_STRING (turbo_verify_machine_graph , nullptr , `verify TurboFan machine graph before instruction selection`)
DEFINE_UINT() [1/2]
force emit tier up logic from all non turbofan even if it is the top enabled tier make OptimizeFunctionOnNextCall optimize to maglev instead of turbofan enable loop peeling in the maglev optimizing compiler max loop size for loop peeling in the maglev optimizing compiler Generate deopt data on background thread maglev_deopt_data_on_background Inline CallApiCallback builtin into generated code Recursively pretenure values which are stored into pretenured allocation sites DEFINE_UINT (concurrent_maglev_max_threads , 2 , `max number of threads that concurrent Maglev can use (0 for unbounded)`)
DEFINE_UINT() [2/2]
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects DEFINE_UINT (minor_gc_task_trigger , 80 , `minor GC task trigger in percent of the current heap limit`)
DEFINE_VALUE_IMPLICATION() [1/2]
too high values may cause the compiler to set high thresholds for inlining to as much as possible DEFINE_VALUE_IMPLICATION (stress_inline , max_inlined_bytecode_size_cumulative , 999999) [inline]
DEFINE_VALUE_IMPLICATION() [2/2]
use conservative stack scanning use direct handles with conservative stack scanning Treat some precise references as conservative references to stress test object pinning in Scavenger minor_gc_task DEFINE_VALUE_IMPLICATION (stress_scavenger_conservative_object_pinning , max_semi_space_size , size_t{1})
DEFINE_WEAK_IMPLICATION()
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects DEFINE_WEAK_IMPLICATION (trace_maglev_graph_building , trace_maglev_object_tracking) [virtual]
DEFINE_WEAK_VALUE_IMPLICATION() [1/4]
other heap size generate builtins concurrently on separate threads in mksnapshot track concurrent recompilation artificial compilation delay in ms max number of threads that concurrent Turbofan can create additional concurrent optimization jobs but throw away result whether maglev resets the interrupt budget DEFINE_WEAK_VALUE_IMPLICATION (maglev_overwrite_budget , invocation_count_for_turbofan , 12000)
DEFINE_WEAK_VALUE_IMPLICATION() [2/4]
other heap size generate builtins concurrently on separate threads in mksnapshot track concurrent recompilation artificial compilation delay in ms max number of threads that concurrent Turbofan can create additional concurrent optimization jobs but throw away result whether maglev resets the interrupt budget whether maglev resets the OSR interrupt budget DEFINE_WEAK_VALUE_IMPLICATION (maglev_overwrite_osr_budget , invocation_count_for_osr , 800)
DEFINE_WEAK_VALUE_IMPLICATION() [3/4]
other heap size generate builtins concurrently on separate threads in mksnapshot track concurrent recompilation artificial compilation delay in ms max number of threads that concurrent Turbofan can create additional concurrent optimization jobs but throw away result DEFINE_WEAK_VALUE_IMPLICATION (stress_concurrent_inlining , invocation_count_for_turbofan , 150)
DEFINE_WEAK_VALUE_IMPLICATION() [4/4]
force emit tier up logic from all non turbofan even if it is the top enabled tier make OptimizeFunctionOnNextCall optimize to maglev instead of turbofan enable loop peeling in the maglev optimizing compiler max loop size for loop peeling in the maglev optimizing compiler Generate deopt data on background thread maglev_deopt_data_on_background Inline CallApiCallback builtin into generated code Recursively pretenure values which are stored into pretenured allocation sites use high priority compiler threads for concurrent Maglev max depth of functions that Maglev will incl small functions maximum cumulative size of bytecode considered for inlining excl small functions minimum frequency for inlining DEFINE_WEAK_VALUE_IMPLICATION (turbofan , max_maglev_inlined_bytecode_size_cumulative , 920)
file()
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this file (requires that V8 was built with v8_enable_builtins_profiling = true)
Referenced by v8::internal::torque::SourceFileMap::AbsolutePath(), v8::internal::compiler::CommonOperatorBuilder::Assert(), v8::internal::compiler::JSGraphAssembler::Assert(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::AssertImpl(), v8::internal::torque::ImplementationVisitor::BeginGeneratedFiles(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Check(), v8::base::OS::MemoryMappedFile::create(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Dcheck(), v8::base::anonymous_namespace{logging.cc}::DefaultDcheckHandler(), v8::internal::Deoptimizer::DoComputeBuiltinContinuation(), v8::internal::Deoptimizer::DoComputeConstructCreateStubFrame(), v8::internal::Deoptimizer::DoComputeConstructInvokeStubFrame(), v8::internal::Deoptimizer::DoComputeUnoptimizedFrame(), v8::internal::wasm::DumpModule(), v8::internal::wasm::DumpProfileToFile(), v8::internal::torque::CCGenerator::EmitSourcePosition(), v8::internal::torque::CSAGenerator::EmitSourcePosition(), v8::internal::torque::ImplementationVisitor::EndGeneratedFiles(), v8::internal::anonymous_namespace{profile-data-reader.cc}::EnsureInitProfileData(), v8::Shell::FetchModuleSource(), v8::internal::torque::SourceFileMap::FileRelativeToV8RootExists(), v8::base::OS::FOpen(), v8::internal::torque::ImplementationVisitor::GenerateCall(), v8::internal::torque::GlobalContext::GeneratedPerFile(), v8::internal::torque::ImplementationVisitor::GenerateExportedMacrosAssembler(), v8::internal::torque::ImplementationVisitor::GenerateImplementation(), anonymous_namespace{mksnapshot.cc}::GetExtraCode(), v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::DiagnosticCollector::GetOrCreateNotificationForSource(), v8::internal::BuiltinsSorter::InitializeCallGraph(), v8::internal::wasm::LoadProfileFromFile(), v8::internal::Deoptimizer::MaterializeHeapObjects(), v8::base::OS::MemoryMappedFile::open(), v8::internal::torque::SourceFileMap::PathFromV8Root(), v8::internal::torque::SourceFileMap::PathFromV8RootWithoutExtension(), v8::internal::JSObject::PrintElementsTransition(), v8::internal::JavaScriptFrame::PrintFunctionAndOffset(), v8::internal::anonymous_namespace{map-updater.cc}::PrintGeneralization(), v8::internal::JSObject::PrintInstanceMigration(), v8::internal::String::PrintOn(), v8::internal::anonymous_namespace{map-updater.cc}::PrintReconfiguration(), v8::internal::JavaScriptFrame::PrintTop(), v8::internal::Deoptimizer::ProcessDeoptReason(), v8::Shell::ReadChars(), v8::internal::anonymous_namespace{utils.cc}::ReadCharsFromFile(), v8::internal::ReadFile(), v8::Shell::ReadFile(), v8::Shell::ReadFileData(), v8::internal::compiler::CodeAssemblerState::SetInitialDebugInformation(), v8::internal::compiler::CodeAssembler::SetSourcePosition(), v8::internal::Deoptimizer::TraceDeoptBegin(), v8::internal::Deoptimizer::TraceDeoptEnd(), V8_Dcheck(), V8_Fatal(), v8::internal::torque::ImplementationVisitor::Visit(), v8::internal::BuiltinsEffectsAnalyzer::Write(), v8::internal::StaticRootsTableGen::write(), v8::WriteAndFlush(), v8::Shell::WriteChars(), v8::internal::torque::ImplementationVisitor::WriteFile(), v8::Shell::WriteFile(), v8::Shell::WriteLcovData(), v8::anonymous_namespace{d8-console.cc}::WriteToFile(), and v8::WriteToFile().
flags()
other heap size flags (e.g. initial_heap_size)
Referenced by v8::base::OS::Allocate(), v8::base::anonymous_namespace{platform-posix.cc}::Allocate(), v8::base::anonymous_namespace{platform-win32.cc}::AllocateInternal(), v8::CallGCCallbackWithoutData(), v8::anonymous_namespace{api.cc}::CreateIndexedInterceptorInfo(), v8::anonymous_namespace{api.cc}::CreateInterceptorInfo(), v8::anonymous_namespace{api.cc}::CreateNamedInterceptorInfo(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForRegExp(), v8_inspector::anonymous_namespace{v8-deep-serializer.cc}::DescriptionForRegExpFlags(), v8::Shell::ExecuteString(), v8::internal::JSRegExp::flags(), v8::base::anonymous_namespace{platform-posix.cc}::GetFlagsForMemoryPermission(), v8::internal::CodeStubAssembler::GetInterestingProperty(), v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >::Initialize(), v8::internal::CodeStubAssembler::InitializePropertyDescriptorObject(), v8::base::anonymous_namespace{platform-darwin.cc}::mach_vm_map_wrapper(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeStructDeclaration(), v8::CTypeInfoBuilder< T, Flags >::MergeFlags(), v8::RegExp::New(), v8::RegExp::NewWithBacktrackLimit(), v8::anonymous_namespace{api.cc}::ObjectTemplateSetNamedPropertyHandler(), v8::base::OS::MemoryMappedFile::open(), v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator&(), v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator&=(), v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator^(), v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator^=(), v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator|(), v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::operator|=(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::ParseBrOnCast(), v8::base::RegionAllocator::Print(), v8::base::RegionAllocator::Region::Print(), v8::base::anonymous_namespace{platform-cygwin.cc}::RandomizedVirtualAlloc(), v8::base::OS::RemapPages(), v8_inspector::V8HeapProfilerAgentImpl::restore(), v8_inspector::anonymous_namespace{v8-deep-serializer.cc}::SerializeRegexp(), v8_inspector::V8HeapProfilerAgentImpl::startSampling(), v8::HeapProfiler::StartSamplingHeapProfiler(), v8::base::PreciseSleepTimer::TryInit(), v8::String::Utf8Value::Utf8Value(), v8_inspector::V8Regex::V8Regex(), v8::base::anonymous_namespace{platform-win32.cc}::VirtualAllocWithHint(), v8::base::anonymous_namespace{platform-win32.cc}::VirtualAllocWrapper(), v8::WriteHelperV2(), v8::String::WriteOneByteV2(), v8::internal::String::WriteUtf8(), v8::String::WriteUtf8V2(), and v8::String::WriteV2().
graph()
refactor address components for immediate indexing make OptimizeMaglevOnNextCall optimize to turbofan instead of maglev filter for tracing turbofan compilation trace turbo cfg graph (for C1 visualizer)
Referenced by v8::internal::compiler::BytecodeGraphBuilder::AddBytecodePositionDecorator(), v8::internal::compiler::turboshaft::UseMap::AddUse(), v8::internal::compiler::AllNodes::AllNodes(), v8::internal::compiler::turboshaft::AllocateOpStorage(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Analyze(), v8::internal::compiler::turboshaft::GeneratorAnalyzer::Analyze(), v8::internal::compiler::turboshaft::AnalyzeCall(), v8::internal::compiler::turboshaft::AnalyzerIterator::AnalyzerIterator(), v8::internal::compiler::turboshaft::AsJSON(), v8::internal::compiler::CodeAssembler::BreakOnNode(), v8::internal::maglev::MaglevGraphBuilder::BuildCallSelf(), v8::internal::maglev::MaglevGraphBuilder::BuildCallWithFeedback(), v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::BuildCWasmEntry(), v8::internal::HeapProfiler::BuildEmbedderGraph(), v8::internal::compiler::fast_api_call::BuildFastApiCall(), v8::internal::maglev::MaglevGraphBuilder::BuildInlineFunction(), v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::BuildJSFastApiCallWrapper(), v8::internal::compiler::LoopFinder::BuildLoopTree(), v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::BuildReceiverNode(), v8::internal::wasm::BuildTSGraph(), v8::internal::wasm::BuildWasmWrapper(), v8::internal::compiler::InstructionSelector::CanCoverProtectedLoad(), v8::internal::compiler::InstructionSelector::CanDoBranchIfOverflowFusion(), v8::internal::maglev::MaglevGraphBuilder::CanInlineCall(), v8::internal::maglev::MaglevGraphBuilder::ClobberAccumulator(), v8::internal::compiler::CloneFrameState(), v8::internal::maglev::MaglevCompiler::Compile(), v8::internal::compiler::CompileCWasmEntry(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::ComputeDeferred(), v8::internal::compiler::anonymous_namespace{pipeline.cc}::ComputeInitialGraphHash(), v8::internal::compiler::Scheduler::ComputeSchedule(), v8::internal::compiler::turboshaft::IfElseCascadeToSwitchReducer< Next >::ContainsOnlyPureOps(), v8::internal::compiler::NodeCopier::CopyNodes(), v8::internal::compiler::anonymous_namespace{frame-states.cc}::CreateBuiltinContinuationFrameStateCommon(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::CreateConstructInvokeStubFrameState(), v8::internal::compiler::CreateGenericLazyDeoptContinuationFrameState(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::CreateStringCreateLazyDeoptContinuationFrameState(), v8::internal::compiler::turboshaft::anonymous_namespace{decompression-optimization.cc}::DecompressionAnalyzer::DecompressionAnalyzer(), v8::internal::compiler::turboshaft::detail::BitfieldCheck::Detect(), v8::internal::compiler::LoopPeeler::EliminateLoopExits(), v8::internal::compiler::turboshaft::Block::EndsWithBranchingOp(), v8::internal::compiler::JSGraphAssembler::EnterMachineGraph(), v8::internal::maglev::AnyUseMarkingProcessor::EscapeAllocation(), v8::internal::compiler::JSGraphAssembler::ExitMachineGraph(), v8::internal::maglev::MaglevGraphBuilder::ExtendOrReallocateCurrentAllocationBlock(), v8::internal::compiler::EscapeAnalysisReducer::Finalize(), v8::internal::compiler::turboshaft::GeneratorAnalyzer::FindLoopHeaderBypasses(), v8::internal::compiler::InstructionSelector::FindProjection(), v8::internal::maglev::MaglevGraphBuilder::FinishBlock(), v8::internal::compiler::turboshaft::Block::FirstOperation(), v8::internal::compiler::InstructionSelector::ForTurboshaft(), v8::internal::compiler::Pipeline::GenerateCodeForTesting(), v8::internal::compiler::turboshaft::Get(), v8::internal::compiler::turboshaft::get_zone(), v8::internal::maglev::MaglevGraphBuilder::GetFeedbackCell(), v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::GetFrameStateDescriptorInternal(), v8::internal::compiler::turboshaft::GrowingOpIndexSidetable< T >::GrowingOpIndexSidetable(), v8::internal::compiler::turboshaft::Block::HasBackedge(), v8::internal::compiler::anonymous_namespace{pipeline.cc}::HashGraphForPGO(), v8::internal::compiler::turboshaft::Block::HasPhis(), v8::internal::compiler::turboshaft::PipelineData::InitializeInstructionComponent(), v8::internal::compiler::anonymous_namespace{add-type-assertions-reducer.cc}::AddTypeAssertionsImpl::InsertAssertion(), v8::internal::compiler::RepresentationChanger::InsertChangeFloat16RawBitsToFloat64Fallback(), v8::internal::compiler::InstructionBlockFor(), v8::internal::compiler::InstructionSequence::InstructionBlocksFor(), v8::internal::compiler::BasicBlockInstrumentor::Instrument(), v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::is_exclusive_user_of(), v8::internal::compiler::IsBuiltinCall(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::IsEscaping(), v8::internal::compiler::turboshaft::IsInt32TruncatedLoadPattern(), v8::internal::compiler::turboshaft::IsUnlikelySuccessor(), v8::internal::NativeObjectsExplorer::IterateAndExtractReferences(), v8::internal::compiler::turboshaft::Block::LastOperation(), v8::internal::compiler::turboshaft::LoadStrideEqualTo(), v8::internal::compiler::InstructionSelector::LoadView::LoadView(), v8::internal::compiler::JSGraphAssembler::MachineSelect(), v8::internal::compiler::BytecodeGraphBuilder::MakeNode(), v8::internal::compiler::AllNodes::Mark(), v8::internal::compiler::turboshaft::anonymous_namespace{decompression-optimization.cc}::DecompressionAnalyzer::MarkAddressingBase(), v8::internal::compiler::JSGraphAssembler::MayThrow(), v8::internal::compiler::BytecodeGraphBuilder::MergeControl(), v8::internal::compiler::AdvancedReducer::MergeControlToEnd(), v8::internal::compiler::NodeProperties::MergeControlToEnd(), v8::internal::compiler::turboshaft::anonymous_namespace{decompression-optimization.cc}::DecompressionAnalyzer::NeedsDecompression(), v8::internal::compiler::turboshaft::FixedArityOperationT< InputCount, Derived >::New(), v8::internal::compiler::turboshaft::LoadOp::New(), v8::internal::compiler::turboshaft::StoreOp::New(), v8::internal::compiler::turboshaft::AtomicRMWOp::New(), v8::internal::compiler::turboshaft::TailCallOp::New(), v8::internal::compiler::turboshaft::OperationT< Derived >::New(), v8::internal::compiler::turboshaft::CallOp::New(), v8::internal::compiler::turboshaft::JSStackCheckOp::New(), v8::internal::compiler::turboshaft::FastApiCallOp::New(), v8::internal::compiler::turboshaft::CompareMapsOp::New(), v8::internal::compiler::turboshaft::CheckMapsOp::New(), v8::internal::compiler::turboshaft::ReturnOp::New(), v8::internal::compiler::turboshaft::AtomicWord32PairOp::New(), v8::internal::compiler::BytecodeGraphBuilder::NewEffectPhi(), v8::internal::maglev::MergePointInterpreterFrameState::NewForLoop(), v8::internal::compiler::BytecodeGraphBuilder::NewPhi(), v8::internal::compiler::turboshaft::operator<<(), v8::internal::maglev::MaglevGraphBuilder::OsrAnalyzePrequel(), v8::internal::maglev::MaglevAssembler::OSRPrologue(), v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::ParseRefCast(), v8::internal::compiler::RawMachineAssembler::Phi(), v8::internal::maglev::NodeMultiProcessor< Processor, Processors... >::PostProcessGraph(), v8::internal::maglev::AnyUseMarkingProcessor::PostProcessGraph(), v8::internal::maglev::MaxCallDepthProcessor::PostProcessGraph(), v8::internal::compiler::turboshaft::Pipeline::PrepareForInstructionSelection(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::PreProcessGraph(), v8::internal::maglev::NodeMultiProcessor< Processor, Processors... >::PreProcessGraph(), v8::internal::maglev::MaglevGraphVerifier::PreProcessGraph(), v8::internal::maglev::MaglevPhiRepresentationSelector::PreProcessGraph(), v8::internal::maglev::DeadNodeSweepingProcessor::PreProcessGraph(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::PreProcessGraph(), v8::internal::maglev::MaglevGraphBuilder::Print(), v8::internal::compiler::turboshaft::PackNode::Print(), v8::internal::compiler::turboshaft::Tracing::PrintPerBlockData(), v8::internal::compiler::turboshaft::Tracing::PrintPerOperationData(), v8::internal::compiler::turboshaft::PrintTurboshaftCustomDataPerBlock(), v8::internal::compiler::turboshaft::PrintTurboshaftCustomDataPerOperation(), v8::internal::compiler::turboshaft::PrintTurboshaftGraph(), v8::internal::compiler::turboshaft::PrintTurboshaftGraphForTurbolizer(), v8::internal::compiler::turboshaft::anonymous_namespace{decompression-optimization.cc}::DecompressionAnalyzer::ProcessBlock(), v8::internal::maglev::GraphProcessor< NodeProcessor, visit_identity_nodes >::ProcessGraph(), v8::internal::compiler::turboshaft::anonymous_namespace{decompression-optimization.cc}::DecompressionAnalyzer::ProcessOperation(), v8::internal::maglev::MaglevAssembler::Prologue(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::PromiseConstructorFrameState(), v8::internal::compiler::turboshaft::PropagateDeferred(), v8::internal::compiler::BytecodeGraphBuilder::RemoveBytecodePositionDecorator(), v8::internal::compiler::NodeProperties::RemoveControlFromEnd(), v8::internal::compiler::turboshaft::anonymous_namespace{decompression-optimization.cc}::DecompressionAnalyzer::Run(), v8::internal::compiler::turboshaft::SpecialRPOSchedulingPhase::Run(), v8::internal::compiler::turboshaft::InstructionSelectionPhase::Run(), v8::internal::compiler::turboshaft::ProfileApplicationPhase::Run(), v8::internal::compiler::MachineGraphVerifier::Run(), v8::internal::compiler::Verifier::Run(), v8::internal::compiler::PrintGraphPhase::Run(), v8::internal::CppGraphBuilder::Run(), v8::internal::compiler::turboshaft::RunDecompressionOptimization(), v8::internal::maglev::AnyUseMarkingProcessor::RunEscapeAnalysis(), v8::internal::compiler::Scheduler::Scheduler(), v8::internal::maglev::MergePointInterpreterFrameState::set_is_resumable_loop(), v8::internal::compiler::turboshaft::Simd128UseMap::Simd128UseMap(), v8::internal::compiler::GraphAssembler::start(), v8::internal::compiler::BasicBlockCallGraphProfiler::StoreCallGraph(), v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::StoreLoadInfo(), v8::internal::compiler::InstructionSelector::StoreView::StoreView(), v8::internal::compiler::turboshaft::SuccessorBlocks(), v8::internal::maglev::MaglevGraphBuilder::TryBuildInlineCall(), v8::internal::compiler::turboshaft::TryGetBuiltin(), v8::internal::compiler::UnrollLoop(), v8::internal::compiler::turboshaft::UnwrapAllocate(), v8::internal::compiler::turboshaft::UseMap::UseMap(), v8::internal::compiler::turboshaft::ComparisonOp::Validate(), v8::internal::compiler::turboshaft::ChangeOrDeoptOp::Validate(), v8::internal::compiler::turboshaft::FrameStateOp::Validate(), v8::internal::compiler::turboshaft::DeoptimizeOp::Validate(), v8::internal::compiler::turboshaft::DeoptimizeIfOp::Validate(), v8::internal::compiler::turboshaft::CallOp::Validate(), v8::internal::compiler::turboshaft::CheckExceptionOp::Validate(), v8::internal::compiler::turboshaft::DidntThrowOp::Validate(), v8::internal::compiler::turboshaft::ProjectionOp::Validate(), v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOrDeoptOp::Validate(), v8::internal::compiler::turboshaft::ConvertJSPrimitiveToUntaggedOrDeoptOp::Validate(), v8::internal::compiler::turboshaft::TruncateJSPrimitiveToUntaggedOrDeoptOp::Validate(), v8::internal::compiler::turboshaft::BigIntBinopOp::Validate(), v8::internal::compiler::turboshaft::CheckMapsOp::Validate(), v8::internal::compiler::turboshaft::CheckedClosureOp::Validate(), v8::internal::compiler::turboshaft::CheckEqualsInternalizedStringOp::Validate(), v8::internal::compiler::turboshaft::MaybeGrowFastElementsOp::Validate(), v8::internal::compiler::turboshaft::ValueNeedsWriteBarrier(), v8::internal::compiler::turboshaft::WasmRevecVerifier::Verify(), v8::internal::maglev::AnyUseMarkingProcessor::VerifyEscapeAnalysis(), v8::internal::compiler::EscapeAnalysisReducer::VerifyReplacement(), v8::internal::compiler::StateValuesCache::zone(), v8::internal::compiler::MachineGraph::zone(), v8::internal::compiler::RawMachineAssembler::zone(), and v8::internal::compiler::Typer::zone().
h()
refactor address components for immediate indexing make OptimizeMaglevOnNextCall optimize to turbofan instead of maglev filter for tracing turbofan compilation trace turbo cfg trace TurboFan s graph trimmer trace TurboFan s control equivalence trace TurboFan s register allocator trace stack load store counters for optimized code in run fuzzing&& concurrent_recompilation trace_turbo trace_turbo_scheduled trace_turbo_stack_accesses verify TurboFan machine graph of code stubs path where to generate builtins effects h (used for mksnapshot only)
Referenced by v8::internal::BUILTIN(), v8::internal::JSTemporalDuration::Constructor(), v8::internal::compiler::InstructionSelector::Emit(), v8::internal::maglev::MaglevGraphBuilder::fast_hash_combine(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::InitialMapDependency::Hash(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PrototypePropertyDependency::Hash(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::StableMapDependency::Hash(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ConstantInDictionaryPrototypeChainDependency::Hash(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDataPropertyDependency::Hash(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDoublePropertyDependency::Hash(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDictionaryPropertyDependency::Hash(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ConsistentJSFunctionViewDependency::Hash(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::TransitionDependency::Hash(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PretenureModeDependency::Hash(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldRepresentationDependency::Hash(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldTypeDependency::Hash(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldConstnessDependency::Hash(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::GlobalPropertyDependency::Hash(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ContextCellDependency::Hash(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::EmptyContextExtensionDependency::Hash(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ProtectorDependency::Hash(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ElementsKindDependency::Hash(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantElementDependency::Hash(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::NoSlackTrackingChangeDependency::Hash(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::InitialMapInstanceSizePredictionDependency::Hash(), v8::internal::compiler::NodeProperties::HashCode(), v8::internal::Assembler::ImmNEONHLM(), v8::internal::compiler::anonymous_namespace{turbofan-graph-visualizer.cc}::JsonPrintInlinedFunctionInfo(), v8::internal::MakeTime(), v8::base::RandomNumberGenerator::MurmurHash3(), v8::internal::compiler::anonymous_namespace{pipeline.cc}::PrintInlinedFunctionInfo(), v8::internal::compiler::JSCallReducer::ReduceArrayEvery(), v8::internal::compiler::JSCallReducer::ReduceArrayFilter(), v8::internal::compiler::JSCallReducer::ReduceArrayFind(), v8::internal::compiler::JSCallReducer::ReduceArrayFindIndex(), v8::internal::compiler::JSCallReducer::ReduceArrayForEach(), v8::internal::compiler::JSCallReducer::ReduceArrayIncludes(), v8::internal::compiler::JSCallReducer::ReduceArrayIndexOf(), v8::internal::compiler::JSCallReducer::ReduceArrayMap(), v8::internal::compiler::JSCallReducer::ReduceArrayReduce(), v8::internal::compiler::JSCallReducer::ReduceArrayReduceRight(), v8::internal::compiler::JSCallReducer::ReduceArraySome(), v8::base::internal::requires(), v8::internal::CrossHeapRememberedSet::Reset(), v8::internal::SwissNameDictionary::SetCtrl(), v8::base::ieee754::sinh(), v8::internal::anonymous_namespace{runtime-classes.cc}::ToHandle(), and v8::anonymous_namespace{api.cc}::ToHandle().
heap()
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the heap (in Mbytes)
Referenced by v8::internal::CppGraphBuilderImpl::AddEdge(), v8::internal::Deserializer< IsolateT >::Allocate(), v8::internal::compiler::AllocationBuilder::Allocate(), v8::internal::SemiSpaceNewSpace::Allocate(), v8::internal::PagedSpaceForNewSpace::AllocatePage(), v8::internal::LocalFactory::AllocateRaw(), v8::internal::FactoryBase< Impl >::AllocateRawArray(), v8::internal::LocalHeap::AsHeap(), v8::internal::CollectionsBuiltinsAssembler::BranchIfMapIteratorProtectorValid(), v8::internal::CollectionsBuiltinsAssembler::BranchIfSetIteratorProtectorValid(), v8::internal::StringBuiltinsAssembler::BranchIfStringPrimitiveWithNoCustomIteration(), v8::internal::Heap::CanShortcutStringsDuringGC(), v8::internal::CommonFrameWithJSLinkage::ComputeParametersCount(), v8::internal::Factory::CopyJSObjectWithAllocationSite(), v8::internal::anonymous_namespace{cpp-heap.cc}::UnifiedHeapConcurrentMarker::CreateConcurrentMarkingVisitor(), v8::internal::StrongRootAllocatorBase::deallocate_impl(), v8::internal::OffThreadObjectDeserializer::Deserialize(), v8::internal::StartupDeserializer::DeserializeIntoIsolate(), v8::Shell::DoHostImportModuleDynamically(), v8::internal::SemiSpaceNewSpace::ExternalBackingStoreBytes(), v8::internal::PagedSpaceForNewSpace::ExternalBackingStoreBytes(), v8::internal::OldSpace::ExternalBackingStoreBytes(), v8::internal::anonymous_namespace{cpp-heap.cc}::FatalOutOfMemoryHandlerImpl(), v8::internal::Isolate::FatalProcessOutOfHeapMemory(), v8::internal::compiler::JSHeapBroker::feedback_nexus_config(), v8::internal::SemiSpaceNewSpace::FillCurrentPageForTesting(), v8::internal::Scavenger::Finalize(), v8::internal::PagedSpaceForNewSpace::FinishShrinking(), v8::internal::StartupDeserializer::FlushICache(), v8::debug::ForceGarbageCollection(), v8::internal::WriteBarrier::ForRange(), v8::internal::SemiSpaceNewSpace::Free(), v8::internal::PagedSpaceBase::FreeInternal(), v8::internal::Isolate::Freeze(), cppgc::internal::Heap::From(), v8::internal::CppHeap::From(), v8::internal::Isolate::FromHeap(), v8::internal::LocalIsolate::FromHeap(), v8::internal::Heap::FromWritableHeapObject(), v8::internal::SemiSpaceNewSpace::GarbageCollectionEpilogue(), v8::internal::HeapLayoutTracer::GCEpiloguePrintHeapLayout(), v8::internal::HeapLayoutTracer::GCProloguePrintHeapLayout(), v8::internal::GetHeapFromWritableObject(), v8::Isolate::GetHeapProfiler(), cppgc::internal::HeapObjectHeader::GetName(), v8::internal::MaterializedObjectStore::GetStackEntries(), v8::internal::PagedSpaceForNewSpace::Grow(), v8::internal::SemiSpaceNewSpace::Grow(), v8::Isolate::HandleExternalMemoryInterrupt(), v8::internal::GlobalHandles::InvokeFirstPassWeakCallbacks(), v8::internal::anonymous_namespace{gc-extension.cc}::InvokeGC(), v8::internal::GlobalHandles::InvokeSecondPassPhantomCallbacks(), v8::internal::LocalIsolate::is_main_thread(), v8::internal::LocalHeap::is_main_thread_for(), v8::internal::StackFrame::IteratePc(), v8::internal::StackFrame::LookupCode(), v8::internal::StackFrame::LookupCodeAndOffset(), v8::internal::SemiSpaceNewSpace::MakeAllPagesInFromSpaceIterable(), v8::internal::PagedSpaceForNewSpace::MakeIterable(), v8::internal::SemiSpaceNewSpace::MakeUnusedPagesInToSpaceIterable(), cppgc::internal::MarkingStateBase::MarkNoPush(), v8::internal::YoungGenerationRememberedSetsMarkingWorklist::MarkingItem::MarkTypedPointers(), v8::internal::PagedSpaceBase::MergeCompactionSpace(), v8::internal::Factory::NewAllocationSite(), v8::internal::Factory::NewStackTraceInfo(), v8::internal::SamplingHeapProfiler::OnWeakCallback(), v8::internal::anonymous_namespace{traced-handles.cc}::ClearWeaknessProcessor::ProcessBlock(), v8::internal::PagedSpaceBase::RefillFreeList(), v8::internal::CompactionSpace::RefillFreeList(), v8::internal::MarkCompactCollector::ReleasePage(), v8::internal::PagedSpaceBase::RemovePage(), v8::internal::PagedSpaceBase::RemovePageFromSpaceImpl(), v8::Isolate::RequestGarbageCollectionForTesting(), v8::internal::GlobalHandles::ResetWeakNodeIfDead(), v8::internal::anonymous_namespace{bigint.cc}::RightTrimString(), v8::InspectorClient::runMessageLoopOnPause(), v8::internal::RUNTIME_FUNCTION(), v8::internal::Serializer::ObjectSerializer::SerializeContent(), v8::internal::ContextSerializer::SerializeObjectWithEmbedderFields(), v8::internal::AllocationSite::set_memento_found_count(), v8::internal::IsolateGroup::set_shared_read_only_heap(), v8::internal::JSArray::SetLengthWouldNormalize(), v8::internal::PagedSpaceForNewSpace::StartShrinking(), v8::internal::OptimizedJSFrame::Summarize(), v8::internal::MarkCompactCollector::SweepLargeSpace(), v8::internal::PagedSpaceBase::TearDown(), v8::internal::PagedSpaceBase::TryExpand(), cppgc::internal::HeapRegistry::TryFromManagedPointer(), and v8::internal::JSObject::UpdateAllocationSite().
hit()
too high values may cause the compiler to hit (release)
jumps()
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near jumps (ia32 , x64)
mode()
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and reclaim otherwise unreachable unmodified wrapper objects when possible discard the memory pool before invoking the GC on memory pressure or last resort GCs Delay before memory reducer start virtual randomize memory reservations by ignoring any hints passed when allocating pages use incremental marking for CppHeap cppheap_concurrent_marking c value for membalancer A special constant to balance between memory and space tradeoff The smaller the more memory it uses enable use of SSE4 instructions if available enable use of SAHF instruction if enable use of AVX VNNI instructions if available enable use of POPCNT instruction if available force all emitted branches to be in long mode (MIPS/PPC only)
Referenced by v8_inspector::anonymous_namespace{value-mirror.cc}::abbreviateString(), v8::internal::interpreter::BytecodeGenerator::AccumulatorPreservingScope::AccumulatorPreservingScope(), v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::AddArguments(), v8::internal::wasm::NativeModule::AddCodeForTesting(), v8::internal::wasm::NativeModule::AddCodeWithCodeSpace(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::AddDisplacementToAddressingMode(), v8::internal::interpreter::BytecodeGenerator::AddDisposableValue(), v8::internal::ProfileTree::AddPathFromEnd(), v8::internal::HeapObject::AllocateAndInstallJSDispatchHandle(), v8::internal::CodeStubAssembler::AllocateCellWithValue(), v8::internal::HeapAllocator::AllocateRawWith(), v8::internal::LocalHeap::AllocateRawWith(), v8::internal::DeclarationScope::AllocateScopeInfos(), v8::internal::ArrayConstructInitializeElements(), v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::compiler::CodeGenerator::AssembleInstruction(), v8::internal::compiler::anonymous_namespace{code-generator-s390.cc}::AssembleOp(), v8::base::BignumDtoa(), v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::InterpreterBinaryOpAssembler::BinaryOpSmiWithFeedback(), v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::InterpreterBinaryOpAssembler::BinaryOpWithFeedback_WithoutDispatch(), v8::internal::compiler::BytecodeGraphBuilder::Environment::BindAccumulator(), v8::internal::compiler::BytecodeGraphBuilder::Environment::BindRegister(), v8::internal::compiler::BytecodeGraphBuilder::Environment::BindRegistersToProjections(), v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::InterpreterBitwiseBinaryOpAssembler::BitwiseBinaryOpWithFeedback(), v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::InterpreterBitwiseBinaryOpAssembler::BitwiseBinaryOpWithSmi(), v8::internal::CodeStubAssembler::BranchIfSameValue(), v8::internal::interpreter::BreakableControlFlowBuilder::BreakIfTrue(), v8::internal::CallOrConstructBuiltinsAssembler::BuildConstruct(), v8::internal::compiler::BytecodeGraphBuilder::BuildDelete(), v8::internal::compiler::JSNativeContextSpecialization::BuildElementAccess(), v8::internal::JsonParser< Char >::BuildJsonArray(), v8::internal::JsonParser< Char >::BuildJsonObject(), v8::internal::Factory::JSFunctionBuilder::BuildRaw(), v8::internal::interpreter::BytecodeGenerator::BuildTest(), v8::internal::maglev::MaglevGraphBuilder::BuildToNumberOrToNumeric(), v8::internal::maglev::MaglevGraphBuilder::BuildToString(), v8::internal::interpreter::BytecodeGenerator::BuildVariableAssignment(), v8::internal::BUILTIN(), v8::internal::anonymous_namespace{deoptimizer.cc}::BuiltinContinuationModeIsJavaScript(), v8::internal::anonymous_namespace{frames.cc}::BuiltinContinuationModeIsWithCatch(), v8::internal::anonymous_namespace{deoptimizer.cc}::BuiltinContinuationModeToFrameType(), v8::internal::Builtins::Call(), v8::internal::CodeFactory::Call(), v8::internal::CodeStubAssembler::Call(), v8::internal::CodeFactory::Call_WithFeedback(), v8::internal::compiler::anonymous_namespace{raw-machine-assembler.cc}::CallCFunctionImpl(), v8::internal::compiler::CodeAssembler::CallCFunctionWithCallerSavedRegisters(), v8::internal::compiler::RawMachineAssembler::CallCFunctionWithCallerSavedRegisters(), v8::internal::Builtins::CallFunction(), v8::internal::CodeFactory::CallFunction(), v8::internal::CodeStubAssembler::CallFunction(), v8::internal::CallOrConstructBuiltinsAssembler::CallFunctionTemplate(), v8::internal::CodeStubAssembler::CallGetterIfAccessor(), v8::internal::MacroAssembler::CallRecordWriteStub(), v8::internal::MacroAssembler::CallRecordWriteStubSaveRegisters(), v8::internal::NexusConfig::can_write(), v8::internal::compiler::Arm64OperandGenerator::CanBeImmediate(), v8::internal::compiler::PPCOperandGenerator::CanBeImmediate(), v8::internal::compiler::Loong64OperandGenerator::CanBeImmediate(), v8::internal::compiler::Mips64OperandGenerator::CanBeImmediate(), v8::internal::compiler::RiscvOperandGenerator::CanBeImmediate(), v8::internal::compiler::S390OperandGenerator::CanBeImmediate(), v8::internal::maglev::MaglevGraphBuilder::CanTrackObjectChanges(), v8::internal::Isolate::CaptureAndSetErrorStack(), v8::internal::anonymous_namespace{isolate.cc}::CaptureSimpleStackTrace(), v8::internal::ErrorUtils::CaptureStackTrace(), v8::Exception::CaptureStackTrace(), v8::internal::compiler::SimplifiedOperatorBuilder::ChangeFloat64OrUndefinedToTagged(), v8::internal::compiler::SimplifiedOperatorBuilder::ChangeFloat64ToTagged(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedFloat64ToAdditiveSafeInteger(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedFloat64ToInt32(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedFloat64ToInt64(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedInt32Mul(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedTaggedToAdditiveSafeInteger(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedTaggedToFloat64(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedTaggedToInt32(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedTaggedToInt64(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedTruncateTaggedToWord32(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckFloat64Hole(), v8::internal::MarkingBitmap::Clear(), v8::internal::Code::ClearEmbeddedObjectsAndJSDispatchHandles(), v8::internal::MutablePageMetadata::ClearLiveness(), v8::internal::MarkingBitmap::ClearRange(), v8::internal::anonymous_namespace{debug-coverage.cc}::CollectBlockCoverage(), v8::internal::anonymous_namespace{debug-coverage.cc}::CollectBlockCoverageInternal(), v8::internal::anonymous_namespace{keys.cc}::CollectOwnPropertyNamesInternal(), v8::internal::WriteBarrier::CombinedWriteBarrierInternal(), v8::internal::anonymous_namespace{keys.cc}::CommonCopyEnumKeysTo(), v8::internal::Factory::CompactWeakArrayList(), v8::internal::TaggedArrayBase< Derived, ShapeT, Super >::compare_and_swap(), v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::InterpreterCompareOpAssembler::CompareOpWithFeedback(), v8::internal::MacroAssembler::CompareRootAndBranch(), v8::internal::RegExpImpl::Compile(), v8::internal::anonymous_namespace{compiler.cc}::CompileMaglev(), v8::internal::Compiler::CompileOptimized(), v8::internal::Compiler::CompileOptimizedOSR(), v8::internal::anonymous_namespace{runtime-compiler.cc}::CompileOptimizedOSR(), v8::internal::anonymous_namespace{compiler.cc}::CompileTurbofan(), v8::internal::compiler::LoadElimination::ComputeLoopState(), v8::internal::Heap::ComputeNewAllocationLimits(), v8::internal::ElementsAccessor::Concat(), v8::internal::ErrorUtils::Construct(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ConvertJSPrimitiveToObject(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::ConvertJSPrimitiveToObject(), v8::internal::compiler::SimplifiedOperatorBuilder::ConvertReceiver(), v8::internal::baseline::anonymous_namespace{baseline-compiler.cc}::ConvertReceiverModeToBuiltin(), v8::internal::baseline::anonymous_namespace{baseline-compiler.cc}::ConvertReceiverModeToCompactBuiltin(), v8::internal::wasm::NativeModuleDeserializer::CopyAndRelocate(), v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::CopyArguments(), v8::internal::Factory::CopyArrayAndGrow(), v8::internal::Factory::CopyArrayWithMap(), v8::internal::FixedArray::CopyElements(), v8::internal::ScopeInfo::CopyElements(), v8::internal::WeakArrayList::CopyElements(), v8::internal::TaggedArrayBase< Derived, ShapeT, Super >::CopyElements(), v8::internal::PropertyArray::CopyElements(), v8::internal::anonymous_namespace{keys.cc}::CopyEnumKeysTo(), v8::internal::Factory::CopyFixedArrayUpTo(), v8::internal::Map::CopyInitialMapNormalized(), v8::internal::Map::CopyNormalized(), v8::internal::anonymous_namespace{heap.cc}::CopyOrMoveRangeImpl(), v8::internal::Heap::CopyRange(), v8::internal::CodeStubAssembler::CopyRange(), v8::internal::NumberDictionary::CopyValuesTo(), v8::internal::Factory::CopyWeakArrayListAndGrow(), v8::internal::ScopeInfo::Create(), v8::internal::JSDataObjectBuilder::CreateAndInitialiseObject(), v8::internal::ArrayBuiltinsAssembler::CreateArrayDispatchNoArgument(), v8::internal::ArrayBuiltinsAssembler::CreateArrayDispatchSingleArgument(), v8::internal::Heap::CreateDefaultMeasureMemoryDelegate(), v8::internal::compiler::CreateJavaScriptBuiltinContinuationFrameState(), v8::internal::Parser::CreatePrivateNameVariable(), v8::internal::compiler::CreateStubBuiltinContinuationFrameState(), v8::internal::PrimitiveArrayBase< ByteArray, ByteArrayShape >::DataSize(), v8::internal::CodeStubAssembler::DCheckReceiver(), v8::internal::ParameterDeclarationParsingScope< Types >::Declare(), v8::internal::Parser::Declare(), v8::internal::Scope::Declare(), v8::internal::VariableMap::Declare(), v8::internal::PreParser::DeclareAndBindVariable(), v8::internal::Parser::DeclareAndBindVariable(), v8::internal::Parser::DeclareBoundVariable(), v8::internal::anonymous_namespace{runtime-scopes.cc}::DeclareEvalHelper(), v8::internal::Parser::DeclareFunction(), v8::internal::PreParser::DeclareFunction(), v8::internal::Scope::DeclareLocal(), v8::internal::DeclarationScope::DeclareParameter(), v8::internal::ClassScope::DeclarePrivateName(), v8::internal::PreParser::DeclarePrivateVariableName(), v8::internal::ScopeIterator::DeclaresLocals(), v8::internal::Parser::DeclareUnboundVariable(), v8::internal::Parser::DeclareVariable(), v8::internal::PreParser::DeclareVariable(), v8::internal::Scope::DeclareVariable(), v8::internal::Scope::DeclareVariableName(), v8::internal::PreParser::DeclareVariableName(), v8::MeasureMemoryDelegate::Default(), v8::internal::MemoryMeasurement::DefaultDelegate(), v8::internal::LookupIterator::Delete(), v8::internal::compiler::anonymous_namespace{frame-states.cc}::DeoptimizerParameterCountFor(), v8::internal::Parser::DeserializeScopeChain(), v8::internal::Deoptimizer::DoComputeBuiltinContinuation(), v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction(), v8::internal::Parser::DoParseProgram(), v8::base::DoubleToAscii(), v8::internal::FactoryBase< Impl >::DoubleToString(), v8::internal::DoWait(), cppgc::internal::DynamicallyTraceMarkedObject(), v8::internal::StoreHandler::ElementsTransitionAndStoreBuiltin(), v8::internal::wasm::LiftoffAssembler::emit_smi_check(), v8::internal::interpreter::BreakableControlFlowBuilder::EmitJumpIfFalse(), v8::internal::interpreter::BreakableControlFlowBuilder::EmitJumpIfTrue(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::EmitLea(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::EmitLea(), v8::internal::compiler::MemoryLowering::EnsureAllocateOperator(), v8::internal::JSObject::EnsureCanContainElements(), v8::internal::ArrayList::EnsureSpace(), v8::internal::Heap::EnsureSweepingCompleted(), v8::internal::HandlerTable::EntrySizeFromMode(), v8::internal::Map::EquivalentToForNormalization(), v8::internal::Evacuator::EvacuationModeName(), v8_inspector::V8RuntimeAgentImpl::evaluate(), v8::debug::EvaluateGlobal(), v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::fallthrough(), v8::internal::anonymous_namespace{js-objects.cc}::FastAssign(), v8::base::FastDtoa(), v8::internal::JSObject::FastPropertyAtPut(), v8::internal::PretenuringHandler::FindAllocationMemento(), v8::internal::compiler::FlagsContinuation::FlagsContinuation(), v8::internal::Trace::Flush(), v8::base::Fopen(), v8::base::OS::FOpen(), v8::debug::anonymous_namespace{debug-interface.cc}::ForEachContextLocal(), v8::internal::WriteBarrier::ForEphemeronHashTable(), v8::internal::WriteBarrier::ForExternalPointer(), v8::internal::WriteBarrier::ForIndirectPointer(), v8::internal::compiler::JSOperatorBuilder::ForInNext(), v8::internal::compiler::JSOperatorBuilder::ForInPrepare(), v8::internal::WriteBarrier::ForJSDispatchHandle(), v8::internal::compiler::AccessBuilder::ForJSForInCacheArrayElement(), v8::internal::WriteBarrier::ForProtectedPointer(), v8::internal::WriteBarrier::ForRange(), v8::internal::WriteBarrier::ForRelocInfo(), v8::internal::WriteBarrier::ForValue(), v8::internal::FreeList::Free(), v8::internal::FreeListManyCached::Free(), v8::internal::FreeListCategory::Free(), v8::internal::MemoryAllocator::Free(), v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::FromBool(), v8::internal::TaggedMember< v8::internal::Map >::full_to_tagged(), v8::internal::Builtins::Generate_Call(), v8::internal::Builtins::Generate_CallApiCallbackImpl(), v8::internal::Builtins::Generate_CallFunction(), v8::internal::Builtins::Generate_CallOrConstructForwardVarargs(), v8::internal::Builtins::Generate_InterpreterPushArgsThenCallImpl(), v8::internal::Builtins::Generate_InterpreterPushArgsThenConstructImpl(), v8::internal::ArrayBuiltinsAssembler::GenerateArrayNoArgumentConstructor(), v8::internal::ArrayBuiltinsAssembler::GenerateArraySingleArgumentConstructor(), v8::internal::ArrayBuiltinsAssembler::GenerateConstructor(), v8::internal::ArrayBuiltinsAssembler::GenerateDispatchToArrayStub(), v8::internal::compiler::IA32OperandGenerator::GenerateMemoryOperandInputs(), v8::internal::compiler::X64OperandGenerator::GenerateMemoryOperandInputs(), v8::internal::compiler::S390OperandGenerator::GenerateMemoryOperandInputs(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::GenerateRightOperands(), v8::internal::NormalizedMapCache::Get(), v8::internal::AllocationSite::GetAllocationType(), v8::internal::GetAttributesForMode(), v8::internal::anonymous_namespace{ic.cc}::GetCloneModeForMap(), v8::internal::compiler::X64OperandGenerator::GetEffectiveAddressMemoryOperand(), v8::internal::compiler::IA32OperandGenerator::GetEffectiveIndexOperand(), v8::internal::compiler::X64OperandGenerator::GetEffectiveIndexOperand(), v8::internal::FeedbackNexus::GetFeedbackPair(), v8::internal::FeedbackNexus::GetKeyedAccessLoadMode(), v8::internal::FeedbackNexus::GetKeyedAccessStoreMode(), v8::internal::anonymous_namespace{ic.cc}::GetModifier(), v8::internal::wasm::GetOperatorModeString(), v8::internal::anonymous_namespace{compiler.cc}::GetOrCompileOptimized(), v8::internal::anonymous_namespace{keys.cc}::GetOwnEnumPropertyDictionaryKeys(), v8::debug::GetPrivateMembers(), v8::Object::GetPropertyNames(), v8::internal::JSFunction::GetRequestedOptimizationIfAny(), v8::internal::GetShouldThrow(), v8::debug::Script::GetSourceOffset(), v8::internal::maglev::ValueNode::GetStaticType(), v8::internal::anonymous_namespace{runtime-classes.cc}::GetSuperHolder(), v8::internal::DebugEvaluate::Global(), v8::internal::AccessorAssembler::HandleLoadICHandlerCase(), v8::internal::AccessorAssembler::HandleStoreICHandlerCase(), v8::internal::AccessorAssembler::HandleStoreICProtoHandler(), v8::internal::compiler::hash_value(), v8::internal::hash_value(), v8::internal::CodeStubAssembler::HasProperty(), v8::internal::torque::Signature::HasSameTypesAs(), v8::internal::VariableProxy::hole_check_mode(), v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER(), v8::internal::Immediate::Immediate(), v8::internal::ImmutableLexicalVariableModeToString(), v8::internal::HeapObject::InitExternalPointerField(), v8::internal::V8::Initialize(), v8::internal::maglev::CallKnownApiFunction::inline_builtin(), v8::internal::JSObject::InObjectPropertyAtPut(), v8::internal::Builtins::InterpreterPushArgsThenCall(), v8::internal::Builtins::InterpreterPushArgsThenConstruct(), v8::internal::ExternalReference::invoke_function_callback(), v8::internal::anonymous_namespace{api.cc}::InvokeFunctionCallback(), v8::internal::CallOrConstructBuiltinsAssembler::IsAccessCheckRequired(), v8::internal::compiler::IsAnyStore(), v8::internal::IsBaselineCodeFlushingEnabled(), v8::internal::anonymous_namespace{debug-coverage.cc}::IsBinaryMode(), v8::internal::anonymous_namespace{debug-coverage.cc}::IsBlockMode(), v8::internal::RelocInfo::IsBuiltinEntryMode(), v8::internal::IsByteCodeFlushingEnabled(), v8::internal::RelocInfo::IsCodeTarget(), v8::internal::RelocInfo::IsCodeTargetMode(), v8::internal::RelocInfo::IsCompressedEmbeddedObject(), v8::internal::IsConcurrent(), v8::internal::RelocInfo::IsConstPool(), v8::internal::TaggedArrayBase< ArrayList, ArrayListShape >::IsCowArray(), v8::internal::IsDeclaredVariableMode(), v8::internal::compiler::IsDefiningStore(), v8::internal::RelocInfo::IsDeoptId(), v8::internal::RelocInfo::IsDeoptNodeId(), v8::internal::RelocInfo::IsDeoptPosition(), v8::internal::RelocInfo::IsDeoptReason(), v8::internal::IsDynamicVariableMode(), v8::internal::RelocInfo::IsEmbeddedObjectMode(), v8::internal::RelocInfo::IsExternalReference(), v8::internal::IsFlushingDisabled(), v8::internal::IsForceFlushingEnabled(), v8::internal::RelocInfo::IsFullEmbeddedObject(), v8::internal::RelocInfo::IsGCRelocMode(), v8::internal::IsImmutableLexicalOrPrivateVariableMode(), v8::internal::IsImmutableLexicalVariableMode(), v8::internal::maglev::IsInitializingOrTransitioning(), v8::internal::RelocInfo::IsInternalReference(), v8::internal::RelocInfo::IsInternalReferenceEncoded(), v8::internal::RelocInfo::IsJSDispatchHandle(), v8::internal::IsLexicalVariableMode(), v8::internal::RelocInfo::IsNearBuiltinEntry(), v8::internal::RelocInfo::IsNoInfo(), v8::internal::RelocInfo::IsOffHeapTarget(), v8::internal::RelocInfo::IsOnlyForSerializer(), v8::internal::IsPrivateAccessorVariableMode(), v8::internal::IsPrivateMethodOrAccessorVariableMode(), v8::internal::IsPrivateMethodVariableMode(), v8::internal::RelocInfo::IsRealRelocMode(), v8::internal::RelocInfo::IsRelativeCodeTarget(), v8::internal::IsSerializableVariableMode(), v8::internal::RelocInfo::IsShareableRelocMode(), v8::internal::IsSynchronous(), v8::internal::RelocInfo::IsVeneerPool(), v8::internal::RelocInfo::IsWasmCall(), v8::internal::RelocInfo::IsWasmCanonicalSigId(), v8::internal::RelocInfo::IsWasmCodePointerTableEntry(), v8::internal::RelocInfo::IsWasmStubCall(), heap::base::BasicSlotSet< SlotGranularity >::Iterate(), v8::internal::SlotSet::Iterate(), v8::internal::TypedSlotSet::Iterate(), v8::internal::RememberedSet< type >::Iterate(), v8::internal::RememberedSetOperations::Iterate(), v8::internal::BodyDescriptorBase::IterateCodePointer(), v8::internal::BodyDescriptorBase::IterateTrustedPointer(), v8::internal::anonymous_namespace{builtins-riscv.cc}::JSToWasmWrapperHelper(), v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::jump_target(), v8::internal::interpreter::BytecodeArrayBuilder::JumpIfFalse(), v8::internal::interpreter::BytecodeArrayBuilder::JumpIfTrue(), v8::internal::interpreter::SwitchBuilder::JumpToCaseIfTrue(), v8::internal::LanguageMode2String(), v8::internal::MacroAssembler::li(), v8::internal::MacroAssembler::li_optimized(), cppgc::internal::ObjectStartBitmap::load(), cppgc::internal::HeapObjectHeader::LoadEncoded(), v8::internal::anonymous_namespace{runtime-scopes.cc}::LoadLookupSlot(), v8::internal::interpreter::BytecodeArrayBuilder::LogicalNot(), v8::internal::Context::Lookup(), v8::internal::Scope::Lookup(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::LowerGlobalSetOrGet(), v8::internal::ErrorUtils::MakeGenericError(), v8::internal::compiler::JSGraphAssembler::MaybeGrowFastElements(), v8::internal::compiler::SimplifiedOperatorBuilder::MaybeGrowFastElements(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::MaybeGrowFastElements(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::MaybeGrowFastElements(), v8::internal::parsing::anonymous_namespace{parsing.cc}::MaybeReportStatistics(), v8::internal::compiler::PPCOperandConverter::MemoryOperand(), v8::internal::compiler::S390OperandConverter::MemoryOperand(), v8::internal::compiler::IA32OperandConverter::MemoryOperand(), v8::internal::compiler::X64OperandConverter::MemoryOperand(), v8::internal::RelocInfo::ModeMask(), v8::internal::ScopeInfo::ModuleIndex(), v8::internal::ScopeInfo::ModuleVariable(), v8::internal::FixedDoubleArray::MoveElements(), v8::internal::TaggedArrayBase< ArrayList, ArrayListShape >::MoveElements(), v8::internal::TaggedArrayBase< Derived, ShapeT, Super >::MoveElements(), v8::internal::Heap::MoveRange(), v8::internal::Scope::MustAllocateInContext(), v8::internal::CodeStubAssembler::NameDictionaryLookup(), v8::internal::NameDictionaryLookupForwardedString(), v8::internal::NameDictionaryLookupForwardedStringWithHandle(), v8::internal::CodeStubAssembler::NameDictionaryLookupWithForwardIndex(), v8::internal::FactoryBase< Impl >::NewConsString(), v8::internal::Factory::NewJSArray(), v8::internal::Factory::NewJSArrayStorage(), v8::internal::Factory::NewPropertyCell(), v8::internal::anonymous_namespace{execution.cc}::NewScriptContext(), v8::internal::compiler::IA32OperandConverter::NextMemoryOperand(), v8::internal::FeedbackNexus::NextSpeculationMode(), v8::internal::Scope::NonLocal(), v8::internal::CodeStubAssembler::NonNumberToNumberOrNumeric(), v8::internal::Map::Normalize(), v8::internal::JSObject::NormalizeProperties(), v8::internal::compiler::SimplifiedOperatorBuilder::NumberSilenceNaN(), v8::internal::FactoryBase< Impl >::NumberToString(), cppgc::internal::BasePage::ObjectHeaderFromInnerAddress(), cppgc::internal::ObjectHeaderFromInnerAddressImpl(), v8::base::OS::MemoryMappedFile::open(), v8::internal::compiler::operator<<(), v8::internal::interpreter::operator<<(), v8::internal::operator<<(), v8::internal::compiler::turboshaft::operator<<(), v8::internal::OptionalTimedHistogramScope::OptionalTimedHistogramScope(), v8::internal::compiler::turboshaft::WordBinopDeoptOnOverflowOp::options(), v8::internal::compiler::turboshaft::ConvertJSPrimitiveToObjectOp::options(), v8::internal::compiler::turboshaft::SameValueOp::options(), v8::internal::compiler::turboshaft::MaybeGrowFastElementsOp::options(), v8::internal::maglev::BuiltinStringPrototypeCharCodeOrCodePointAt::options(), v8::internal::parsing::ParseAny(), v8::internal::Parser::ParseClassForMemberInitialization(), v8::internal::parsing::ParseFunction(), v8::internal::Parser::ParseFunction(), v8::internal::ParserBase< Impl >::ParseHoistableDeclaration(), v8::internal::parsing::ParseProgram(), v8::internal::Parser::ParsingModeScope::ParsingModeScope(), v8::Shell::PerformanceMeasureMemory(), v8::internal::anonymous_namespace{compiler.cc}::PrepareJobWithHandleScope(), v8::internal::StackFrame::Print(), v8::internal::JavaScriptFrame::Print(), v8::internal::BuiltinExitFrame::Print(), v8::internal::ApiCallbackExitFrame::Print(), v8::internal::ApiAccessorExitFrame::Print(), v8::internal::PropertyDetails::PrintAsFastTo(), v8::internal::DescriptorArray::PrintDescriptorDetails(), v8::internal::PrintFrames(), v8::internal::anonymous_namespace{frames.cc}::PrintIndex(), v8::internal::Isolate::PrintStack(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::MarkCompactCollector::ProcessMarkingWorklist(), v8::internal::ParserBase< Impl >::RaiseLanguageMode(), v8::internal::JSObject::RawFastInobjectPropertyAtPut(), v8::internal::EvacuateVisitorBase::RawMigrateObject(), v8::internal::Deserializer< LocalIsolate >::ReadAllocateJSDispatchEntry(), v8::internal::compiler::BytecodeGraphBuilder::Environment::RecordAfterState(), v8::internal::TurbofanCompilationJob::RecordCompilationStats(), v8::internal::GCTracer::RecordGCPhasesHistograms(), v8::internal::RedirectActiveFunctions::RedirectActiveFunctions(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSGetIterator(), v8::internal::RELEASE_ACQUIRE_ACCESSORS(), v8::internal::TaggedMember< T, CompressionScheme >::Release_Store(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::RelocatableConstant(), v8::internal::InstructionStream::RelocateFromDesc(), v8::internal::InstructionStream::RelocateFromDescWriteBarriers(), v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::RemoveElement(), v8::internal::RememberedSet< type >::RemoveRange(), heap::base::BasicSlotSet< SlotGranularity >::RemoveRange(), v8::internal::RememberedSetOperations::RemoveRange(), v8::internal::JSFunction::RequestOptimization(), v8::internal::FixedArray::Resize(), v8::internal::Heap::ResizeNewSpace(), v8_inspector::V8DebuggerAgentImpl::restartFrame(), v8::internal::RUNTIME_FUNCTION(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::SameValue(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::SameValue(), v8::internal::maglev::MaglevGraphBuilder::SaveCallSpeculationScope::SaveCallSpeculationScope(), v8::internal::compiler::IA32OperandConverter::ScaleFor(), v8::internal::compiler::X64OperandConverter::ScaleFor(), v8::internal::ScopeIterator::ScopeObject(), v8::internal::compiler::SelectLoadOpcode(), v8::debug::Coverage::SelectMode(), v8::internal::Coverage::SelectMode(), v8::internal::TaggedMember< T, CompressionScheme >::SeqCst_CompareAndSwap(), v8::internal::TaggedMember< T, CompressionScheme >::SeqCst_Store(), v8::internal::TaggedMember< T, CompressionScheme >::SeqCst_Swap(), v8::internal::FeedbackVector::Set(), v8::internal::Assembler::VectorUnit::set(), v8::internal::TaggedArrayBase< Derived, ShapeT, Super >::set(), v8::internal::WeakArrayList::Set(), v8::internal::PropertyArray::set(), v8::internal::NativeContext::set(), v8::internal::Context::set(), v8::internal::ScopeInfo::set(), v8::internal::ThinString::set_actual(), v8::internal::AllocationMemento::set_allocation_site(), v8::internal::SloppyArgumentsElements::set_arguments(), v8::internal::AllocationSite::set_boilerplate(), v8::internal::Code::set_bytecode_or_interpreter_data(), v8::internal::PreparseData::set_child(), v8::internal::CallSiteInfo::set_code_object(), v8::internal::SloppyArgumentsElements::set_context(), v8::internal::DataHandler::set_data1(), v8::internal::DataHandler::set_data2(), v8::internal::DataHandler::set_data3(), v8::internal::AllocationSite::set_dependent_code(), v8::internal::ContextCell::set_dependent_code(), v8::internal::Symbol::set_description(), v8::internal::JSObject::set_elements(), v8::internal::Context::set_extension(), v8::internal::ConsString::set_first(), v8::internal::AccessorPair::set_getter(), v8::internal::RegExpMacroAssembler::set_global_mode(), v8::internal::SharedFunctionInfo::set_interpreter_data(), v8::internal::RegExpMatchInfo::set_last_input(), v8::internal::RegExpMatchInfo::set_last_subject(), v8::internal::Assignment::set_lookup_hoisting_mode(), v8::internal::HeapObject::set_map(), v8::internal::HeapObjectLayout::set_map_after_allocation(), v8::internal::HeapObject::set_map_after_allocation(), v8::internal::ScriptContextTable::set_names_to_context_index(), v8::internal::AllocationSite::set_nested_site(), v8::internal::SlicedString::set_parent(), v8::internal::Context::set_previous(), v8::internal::SharedFunctionInfo::set_raw_scope_info(), v8::internal::ConsString::set_second(), v8::internal::AccessorPair::set_setter(), v8::internal::ContextCell::set_tagged_value(), v8::internal::Oddball::set_to_number(), v8::internal::Oddball::set_to_string(), v8::internal::Oddball::set_type_of(), v8::internal::SharedFunctionInfo::set_uncompiled_data(), v8::internal::SharedFunctionInfo::set_uncompiled_data_with_preparse_data(), v8::internal::DataHandler::set_validity_cell(), v8::internal::Tuple2::set_value1(), v8::internal::Tuple2::set_value2(), v8::internal::AllocationSiteWithWeakNext::set_weak_next(), v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::SetAccumulatorInBranch(), v8::internal::Map::SetBackPointer(), v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::SetBranchSpecializationMode(), v8::internal::Map::SetConstructor(), v8::internal::CompilationCacheTable::SetEvalJSFunctionsValueAt(), v8::internal::FeedbackNexus::SetFeedback(), v8::internal::anonymous_namespace{elements.cc}::FastSmiOrObjectElementsAccessor< Subclass, KindTraits >::SetImpl(), v8::internal::Code::SetInstructionStreamAndInstructionStart(), v8::internal::Parser::SetLanguageMode(), v8::internal::PreParser::SetLanguageMode(), v8::internal::maglev::HoleyFloat64ToTagged::SetMode(), v8::internal::RelocIteratorBase< RelocInfoT >::SetMode(), v8::internal::ScopeIterator::SetModuleVariableValue(), v8::internal::Context::SetNoCell(), v8::internal::JSReceiver::SetOrCopyDataProperties(), v8::internal::CompilationCacheTable::SetPrimaryValueAt(), v8::internal::MarkingBitmap::SetRange(), v8::internal::MacroAssemblerBase::SetSandboxingModeForCurrentBuiltin(), v8::internal::SharedFunctionInfo::SetScopeInfo(), v8::internal::FeedbackNexus::SetSpeculationMode(), v8::internal::WasmArray::SetTaggedElement(), v8::internal::WasmStruct::SetTaggedFieldValue(), v8::platform::tracing::TraceConfig::SetTraceRecordMode(), v8::ValueSerializer::SetTreatArrayBufferViewsAsHostObjects(), v8::internal::ValueSerializer::SetTreatArrayBufferViewsAsHostObjects(), v8::internal::SharedFunctionInfo::SetUntrustedData(), v8::internal::SwissNameDictionary::ShallowCopy(), v8::internal::compiler::ShouldAlignForJCCErratum(), v8::internal::compiler::ShouldClearOutputRegisterBeforeInstruction(), cppgc::internal::PlatformAwareObjectStartBitmap::ShouldForceNonAtomic(), v8::internal::compiler::anonymous_namespace{js-generic-lowering.cc}::ShouldUseMegamorphicAccessBuiltin(), v8::internal::FactoryBase< Impl >::SmiToString(), v8::internal::anonymous_namespace{compiler.cc}::SpawnDuplicateConcurrentJobForStressTesting(), v8::internal::StackTraceFailureMessage::StackTraceFailureMessage(), v8::CpuProfiler::Start(), v8::internal::MarkCompactCollector::StartCompaction(), v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::StartFallthroughBlock(), v8_inspector::V8ProfilerAgentImpl::startPreciseCoverage(), v8::CpuProfiler::StartProfiling(), cppgc::internal::ObjectStartBitmap::store(), v8::internal::CodeStubAssembler::StoreCellValue(), cppgc::internal::HeapObjectHeader::StoreEncoded(), v8::internal::StoreHandler::StoreFastElementBuiltin(), v8::internal::anonymous_namespace{runtime-scopes.cc}::StoreLookupSlot(), v8::internal::wasm::Handlers< Compressed >::StoreRefIntoMemory(), v8::internal::StoreHandler::StoreSloppyArgumentsBuiltin(), v8::internal::CodeStubAssembler::StoreValueByKeyIndex(), v8::internal::maglev::MaglevAssembler::StringCharCodeOrCodePointAt(), v8::internal::StringToIndex(), v8::internal::anonymous_namespace{factory-base.cc}::StringViewToString(), v8::internal::anonymous_namespace{builtins-riscv.cc}::SwitchBackAndReturnPromise(), v8::internal::FeedbackVector::SynchronizedSet(), v8::internal::PagedSpaceBase::TearDown(), v8::internal::anonymous_namespace{js-function.cc}::TieringStateFor(), v8::internal::interpreter::BytecodeArrayBuilder::ToBoolean(), v8::internal::compiler::OperandGenerator::ToConstant(), v8::internal::ToDateString(), v8::internal::ArrayList::ToFixedArray(), v8::internal::CodeStubAssembler::ToNumberOrNumeric(), v8::internal::interpreter::InterpreterAssembler::ToNumberOrNumeric(), v8::internal::ToString(), v8::internal::IC::TraceIC(), v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceOptimizeOSRAvailable(), v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceOptimizeOSRStarted(), v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceOptimizeOSRUnavailable(), v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TracePrepareJob(), v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceStartMaglevCompile(), v8::internal::Deoptimizer::TrampolineForBuiltinContinuation(), v8::internal::LookupIterator::TransitionToAccessorPair(), v8::internal::Map::TransitionToAccessorProperty(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::TryEmitLoadForLoadWord64AndShiftRight(), v8::internal::CodeStubAssembler::TryGetOwnProperty(), v8::internal::compiler::TryMatchInt32OpWithOverflow(), v8::internal::compiler::TryMatchInt64OpWithOverflow(), v8::internal::maglev::MaglevGraphBuilder::TryReduceCallForApiFunction(), v8::internal::wasm::TurboshaftGraphBuildingInterface::TurboshaftGraphBuildingInterface(), v8::internal::JSFunction::UpdateCode(), v8::internal::JSFunction::UpdateCodeImpl(), v8::internal::JSFunction::UpdateCodeKeepTieringRequests(), v8::internal::CodeStubAssembler::UpdateFeedback(), v8::internal::JSFunction::UpdateOptimizedCode(), v8::internal::compiler::Arm64OperandGenerator::UseOperand(), v8::internal::compiler::PPCOperandGenerator::UseOperand(), v8::internal::compiler::S390OperandGenerator::UseOperand(), v8::internal::wasm::WasmCode::Validate(), v8::internal::ArrowHeadParsingScope< Types >::ValidateAndCreateScope(), v8::internal::RelocInfo::Visit(), v8::internal::compiler::InstructionSelector::VisitCall(), v8::internal::interpreter::BytecodeGenerator::VisitForNullishTest(), v8::internal::ObjectVisitorForwarder::VisitIndirectPointer(), v8::internal::compiler::VisitLoadCommon(), v8::internal::ScopeIterator::VisitLocals(), v8::internal::ScopeIterator::VisitLocalScope(), v8::internal::ForEachStatement::VisitModeString(), v8::internal::compiler::RepresentationSelector::VisitNode(), v8::internal::ExternalStringTableCleanerVisitor< mode >::VisitRootPointers(), v8::internal::Deserializer< LocalIsolate >::VisitRootPointers(), v8::internal::ScopeIterator::VisitScope(), v8::internal::compiler::VisitStoreCommon(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitWord32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitWord32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitWord64Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitWord64Compare(), v8::internal::Assembler::vroundpd(), v8::internal::Assembler::vroundps(), v8::internal::Assembler::vroundsd(), v8::internal::Assembler::vroundss(), v8::internal::FutexEmulation::Wait(), v8::internal::FutexEmulation::WaitJs32(), v8::internal::FutexEmulation::WaitJs64(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::WordBinopDeoptOnOverflow(), v8::internal::SlotAccessorForRootSlots::Write(), v8::internal::SlotAccessorForHeapObject::Write(), v8::internal::TaggedMember< T, CompressionScheme >::WriteBarrier(), v8::internal::wasm::NativeModuleSerializer::WriteCode(), v8::internal::SlotAccessorForHeapObject::WriteIndirectPointerTo(), and v8::internal::GCTracer::YoungGenerationSpeedInBytesPerMillisecond().
optimizations()
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional optimizations (especially load- elimination)
pools()
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and reclaim otherwise unreachable unmodified wrapper objects when possible discard the memory pool before invoking the GC on memory pressure or last resort GCs Delay before memory reducer start virtual randomize memory reservations by ignoring any hints passed when allocating pages use incremental marking for CppHeap cppheap_concurrent_marking c value for membalancer A special constant to balance between memory and space tradeoff The smaller the more memory it uses enable use of SSE4 instructions if available enable use of SAHF instruction if enable use of AVX VNNI instructions if available enable use of POPCNT instruction if available force all emitted branches to be in long enable use of partial constant pools (x64 only)
random()
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after random (0 , X) [override]
Referenced by v8::base::RegionAllocator::AllocateRegion(), and v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GenerateRef().
size()
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space size (in Mbytes)
Referenced by v8::internal::compiler::anonymous_namespace{code-assembler.cc}::NodeArray< kMaxSize >::Add(), cppgc::internal::NormalPageMemoryPool::Add(), v8::internal::maglev::Graph::add_inlined_bytecode_size(), v8::internal::maglev::Graph::add_peeled_bytecode_size(), v8::internal::HeapEntry::add_self_size(), v8::internal::AllocationTraceNode::AddAllocation(), v8::internal::wasm::WasmModuleBuilder::AddDataSegment(), v8::internal::HeapSnapshot::AddEntry(), v8::internal::V8HeapExplorer::AddEntry(), cppgc::internal::anonymous_namespace{sweeper.cc}::InlinedFinalizationBuilder< FreeHandler >::AddFinalizer(), cppgc::internal::anonymous_namespace{sweeper.cc}::DeferredFinalizationBuilder< FreeHandler >::AddFinalizer(), cppgc::internal::anonymous_namespace{sweeper.cc}::InlinedFinalizationBuilder< FreeHandler >::AddFreeListEntry(), cppgc::internal::anonymous_namespace{sweeper.cc}::DeferredFinalizationBuilder< FreeHandler >::AddFreeListEntry(), v8::internal::EmbedderGraphImpl::AddNativeSize(), v8::internal::CppGraphBuilderImpl::AddNode(), v8::internal::wasm::WasmModuleBuilder::AddPassiveDataSegment(), v8::internal::compiler::turboshaft::Block::AddPredecessor(), v8::internal::AddressToTraceMap::AddRange(), v8::internal::wasm::TypeCanonicalizer::AddRecursiveGroup(), v8::internal::wasm::WasmModuleBuilder::AddRecursiveTypeGroup(), v8::base::AddressRegionOf(), cppgc::internal::FreeList::AddReturningUnusedBounds(), cppgc::internal::anonymous_namespace{object-allocator.cc}::AddToFreeList(), v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::AddToFreeListFreeSpaceHandler(), v8::base::AlignedAlloc(), v8::internal::AlignedAllocWithRetry(), v8::internal::BuiltinsReducer< Next >::AlignTagged(), v8::base::all_equal(), cppgc::MakeGarbageCollectedTraitBase< T >::Allocate(), v8::internal::Deserializer< IsolateT >::Allocate(), v8::internal::compiler::JSGraphAssembler::Allocate(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Allocate(), cppgc::internal::MakeGarbageCollectedTraitInternal::Allocate(), v8::internal::Heap::Allocate(), v8::internal::compiler::WasmGraphAssembler::Allocate(), v8::internal::compiler::AllocationBuilder::Allocate(), v8::internal::RegExpResultVector::Allocate(), heap::base::BasicSlotSet< SlotGranularity >::Allocate(), v8::internal::wasm::DisjointAllocationPool::Allocate(), v8::internal::Zone::Allocate(), v8::platform::DefaultThreadIsolatedAllocator::Allocate(), v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::Allocate(), v8::base::Allocate(), v8::base::OS::Allocate(), v8::base::anonymous_namespace{platform-posix.cc}::Allocate(), v8::internal::maglev::NodeBase::Allocate(), v8::internal::compiler::AllocationBuilder::AllocateArray(), v8::internal::CodeStubAssembler::AllocateByteArray(), v8::internal::compiler::AllocationBuilder::AllocateContext(), v8::internal::wasm::StackMemory::allocated_size(), v8::internal::SerializedData::AllocateData(), cppgc::internal::HeapObjectHeader::AllocatedSize(), v8::internal::EmbedderGraphEntriesAllocator::AllocateEntry(), v8::internal::wasm::WasmCodeAllocator::AllocateForCode(), v8::internal::wasm::WasmCodeAllocator::AllocateForCodeInRegion(), v8::internal::wasm::WasmCodeAllocator::AllocateForWrapper(), v8::base::EmulatedVirtualAddressSubspace::AllocateGuardRegion(), v8::base::LsanVirtualAddressSpace::AllocateGuardRegion(), v8::base::VirtualAddressSpace::AllocateGuardRegion(), v8::base::VirtualAddressSubspace::AllocateGuardRegion(), v8::internal::wasm::DisjointAllocationPool::AllocateInRegion(), v8::base::anonymous_namespace{platform-win32.cc}::AllocateInternal(), v8::internal::CodeStubAssembler::AllocateJSArray(), v8::internal::interpreter::BytecodeArrayBuilder::AllocateJumpTable(), v8::internal::CodeStubAssembler::AllocateNonEmptyByteArray(), cppgc::internal::ObjectAllocator::AllocateObject(), cppgc::internal::ObjectAllocator::AllocateObjectOnSpace(), v8::internal::MemoryAllocator::AllocatePage(), v8::base::VirtualAddressSpace::AllocatePages(), v8::base::EmulatedVirtualAddressSubspace::AllocatePages(), v8::base::VirtualAddressSubspace::AllocatePages(), v8::internal::AllocatePages(), v8::base::LsanPageAllocator::AllocatePages(), v8::base::PageAllocator::AllocatePages(), v8::base::VirtualAddressSpacePageAllocator::AllocatePages(), v8::internal::FactoryBase< Impl >::AllocateRaw(), v8::internal::Factory::AllocateRaw(), v8::internal::LocalFactory::AllocateRaw(), v8::internal::FactoryBase< Impl >::AllocateRawArray(), v8::internal::CodeStubAssembler::AllocateRawBigInt(), v8::internal::FactoryBase< Impl >::AllocateRawOneByteInternalizedString(), v8::internal::Heap::AllocateRawOrFail(), v8::internal::FactoryBase< Impl >::AllocateRawTwoByteInternalizedString(), v8::internal::HeapAllocator::AllocateRawWith(), v8::internal::FactoryBase< Impl >::AllocateRawWithImmortalMap(), v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(), v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(), v8::internal::MemoryAllocator::AllocateReadOnlyPage(), v8::internal::compiler::LinearScanAllocator::AllocateRegisters(), v8::base::OS::AllocateShared(), v8::base::EmulatedVirtualAddressSubspace::AllocateSharedPages(), v8::base::VirtualAddressSpace::AllocateSharedPages(), v8::base::VirtualAddressSubspace::AllocateSharedPages(), v8::base::PageAllocator::AllocateSharedPages(), v8::base::LsanPageAllocator::AllocateSharedPages(), v8::internal::compiler::AllocationBuilder::AllocateSloppyArgumentElements(), v8::internal::Factory::AllocateSmallOrderedHashTable(), v8::internal::wasm::LiftoffAssembler::AllocateStackSlot(), v8::base::VirtualAddressSpace::AllocateSubspace(), v8::base::VirtualAddressSubspace::AllocateSubspace(), v8::internal::EvacuateNewSpaceVisitor::AllocateTargetObject(), v8::internal::maglev::MaglevAssembler::AllocateTwoByteString(), v8::internal::CodeStubAssembler::AllocateUninitializedJSArrayWithElements(), v8::internal::MemoryAllocator::AllocateUninitializedPageFromPool(), v8::internal::AllocationTracker::AllocationEvent(), v8::internal::Heap::AllocationTrackerForDebugging::AllocationEvent(), v8::internal::Debug::TemporaryObjectsTracker::AllocationEvent(), v8::internal::HeapProfiler::AllocationEvent(), v8::internal::AllocAtLeastWithRetry(), v8::internal::AllocWithRetry(), v8::base::SysInfo::AmountOfPhysicalMemory(), v8::internal::anonymous_namespace{log.cc}::AppendCodeCreateHeader(), v8::internal::compiler::turboshaft::FastApiCallOp::arguments(), v8::internal::Zone::AsanNew(), v8::internal::wasm::WasmOpcodes::AsmjsSignature(), v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::compiler::CodeGenerator::AssembleCode(), v8::internal::AtomicIsLockFree(), v8::internal::MemoryAllocator::Available(), v8::internal::interpreter::ConstantArrayBuilder::ConstantArraySlice::available(), v8::internal::wasm::ModuleWireBytes::BoundsCheck(), v8::internal::wasm::WasmInterpreterRuntime::BoundsCheckMemRange(), cppgc::internal::anonymous_namespace{free-list.cc}::BucketIndexForSize(), heap::base::BasicSlotSet< SlotGranularity >::BucketsForSize(), v8::internal::maglev::MaglevGraphBuilder::Build(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCallAndReturn(), v8::internal::compiler::turboshaft::Opmask::MaskBuilder< Op, Fields >::BuildFieldMask(), v8::internal::compiler::LiveRangeBuilder::BuildLiveRanges(), v8::internal::ExternalizeStringExtension::BuildSource(), v8::internal::CpuTraceMarkExtension::BuildSource(), v8::internal::GCExtension::BuildSource(), v8::internal::VTuneDomainSupportExtension::BuildSource(), v8::internal::FuzzilliExtension::BuildSource(), v8::internal::BUILTIN(), v8::internal::wasm::ModuleDecoderImpl::CalculateGlobalOffsets(), v8::internal::maglev::MaglevGraphBuilder::CalculatePredecessorCounts(), v8::internal::compiler::GraphAssembler::Call(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin_GrowFastDoubleElements(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin_GrowFastSmiOrObjectElements(), v8::base::Calloc(), v8::internal::compiler::AllocationBuilder::CanAllocateArray(), v8::internal::compiler::AllocationBuilder::CanAllocateSloppyArgumentElements(), v8::internal::compiler::InstructionSelector::CanDoBranchIfOverflowFusion(), v8::internal::Heap::CanExpandOldGeneration(), v8::internal::wasm::TypeCanonicalizer::CanonicalGroup::CanonicalGroup(), wasm::anonymous_namespace{c-api.cc}::SignatureHelper::Canonicalize(), v8::internal::Heap::CanPromoteYoungAndExpandOldGeneration(), v8::internal::compiler::Verifier::Visitor::Check(), v8::internal::wasm::Decoder::checkAvailable(), v8::internal::anonymous_namespace{code-memory-access.cc}::CheckForRegionOverlap(), cppgc::internal::CheckMemoryIsZapped(), cppgc::internal::CheckMemoryIsZero(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::CheckStaticallyOutOfBounds(), v8::internal::torque::Item::Children(), v8::internal::MacroAssembler::Claim(), v8::internal::compiler::OperandAssigner::CommitAssignment(), v8::internal::SemiSpaceNewSpace::CommittedPhysicalMemory(), v8::internal::ReadOnlySpace::CommittedPhysicalMemory(), cppgc::internal::anonymous_namespace{compactor.cc}::CompactPage(), v8::internal::anonymous_namespace{heap.cc}::CompareWords(), v8::internal::anonymous_namespace{string.cc}::ComputeExternalStringMap(), v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::ComputePredecessors(), v8::internal::torque::TypeVisitor::ComputeType(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ComputeTypeForPhi(), v8::internal::MinorGCHeapGrowing::ConfigureLimit(), cppgc::internal::HeapGrowing::HeapGrowingImpl::ConfigureLimit(), v8::internal::compiler::LiveRangeConnector::ConnectRanges(), v8::internal::Code::constant_pool_size(), v8::internal::wasm::Decoder::consume_bytes(), v8::base::EmulatedVirtualAddressSubspace::Contains(), v8::base::RegionAllocator::contains(), v8::internal::ThreadIsolation::JitPageReference::Contains(), v8::internal::Factory::CopyBytecodeArray(), v8::internal::Serializer::CopyCode(), v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::CopyElements(), v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::CopyToReadOnlyHeap(), v8::internal::DescriptorArray::CopyUpToAddAttributes(), v8::internal::Serializer::CountAllocation(), v8::base::OS::MemoryMappedFile::create(), v8::internal::Register::Create(), v8::internal::VRegister::Create(), v8::internal::CPURegister::Create(), v8::base::OS::CreateAddressSpaceReservation(), v8::base::anonymous_namespace{platform-fuchsia.cc}::CreateAddressSpaceReservationInternal(), v8::internal::CodeStubAssembler::CreateAllocationSiteInFeedbackVector(), v8::base::anonymous_namespace{platform-fuchsia.cc}::CreateAndMapVmo(), v8::internal::compiler::JSCallReducerAssembler::CreateArrayNoThrow(), cppgc::internal::FreeList::Entry::CreateAt(), cppgc::internal::Filler::CreateAt(), v8::internal::torque::DeclarationVisitor::CreateBuiltin(), v8::internal::Factory::CreateCanonicalEmptySwissNameDictionary(), v8::internal::Heap::CreateEarlyReadOnlyMapsAndObjects(), v8::Shell::CreateEvaluationContext(), v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::CreateFillerFreeSpaceHandler(), v8::internal::Heap::CreateFillerObjectAt(), v8::internal::anonymous_namespace{heap.cc}::CreateFillerObjectAtImpl(), v8::internal::Heap::CreateFillerObjectAtRaw(), v8::internal::trap_handler::CreateHandlerData(), v8::internal::Genesis::CreateInitialMapForArraySubclass(), v8::internal::compiler::turboshaft::CreateOperation(), v8::base::OS::CreateSharedMemoryHandleForTesting(), v8::internal::wasm::LiftoffAssembler::DeallocateStackSlot(), v8::internal::PlatformEmbeddedFileWriterGeneric::DeclareFunctionBegin(), v8::internal::wasm::DecodeAsmJsOffsets(), v8::internal::wasm::ModuleDecoderImpl::DecodeCodeSection(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeNumericOpcode(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeStringNewWtf8(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeStringRefOpcode(), v8::base::EmulatedVirtualAddressSubspace::DecommitPages(), v8::base::LsanVirtualAddressSpace::DecommitPages(), v8::base::VirtualAddressSpace::DecommitPages(), v8::base::VirtualAddressSubspace::DecommitPages(), v8::base::OS::DecommitPages(), v8::base::PageAllocator::DecommitPages(), v8::base::LsanPageAllocator::DecommitPages(), v8::base::VirtualAddressSpacePageAllocator::DecommitPages(), v8::ExternalMemoryAccounter::Decrease(), v8::internal::DEF_GETTER(), v8::internal::Zone::Delete(), v8::internal::Deoptimizer::Deoptimizer(), v8::internal::DeoptTranslationIterator::DeoptTranslationIterator(), v8::internal::OffThreadObjectDeserializer::Deserialize(), v8::internal::ContextDeserializer::DeserializeApiWrapperFields(), v8::internal::ContextDeserializer::DeserializeEmbedderFields(), v8::base::EmulatedVirtualAddressSubspace::DiscardSystemPages(), v8::base::LsanVirtualAddressSpace::DiscardSystemPages(), v8::base::VirtualAddressSpace::DiscardSystemPages(), v8::base::VirtualAddressSubspace::DiscardSystemPages(), v8::base::OS::DiscardSystemPages(), v8::base::PageAllocator::DiscardSystemPages(), v8::base::LsanPageAllocator::DiscardSystemPages(), v8::base::VirtualAddressSpacePageAllocator::DiscardSystemPages(), v8::base::anonymous_namespace{platform-fuchsia.cc}::DiscardSystemPagesInternal(), v8::internal::wasm::TurboshaftGraphBuildingInterface::DoReturn(), v8::internal::MacroAssembler::Drop(), v8::internal::compiler::turboshaft::TupleType::element(), v8::internal::compiler::turboshaft::TupleType::elements(), v8::internal::Assembler::emit_add(), v8::internal::Assembler::emit_aligned_cmp(), v8::internal::Assembler::emit_aligned_test(), v8::internal::Assembler::emit_and(), v8::internal::Assembler::emit_cmp(), v8::internal::Assembler::emit_or(), v8::internal::Assembler::emit_rex(), v8::internal::Assembler::emit_sbb(), v8::internal::Assembler::emit_sub(), v8::internal::Assembler::emit_test(), v8::internal::Assembler::emit_xor(), v8::internal::Assembler::EmitData(), v8::MemorySpan< T >::empty(), v8::internal::MarkingProgressTracker::Enable(), v8::internal::ETWJITInterface::IsolateLoadScriptData::EnableLogWithFilterDataOnAllIsolates(), unibrow::Utf8::Encode(), v8::internal::compiler::turboshaft::Opmask::MaskBuilder< Op, Fields >::EncodeFieldValue(), cppgc::internal::HeapObjectHeader::EncodeSize(), v8::internal::ZoneCompactSet< T >::end(), v8::internal::compiler::turboshaft::Block::EndsWithBranchingOp(), v8::base::Bignum::EnsureCapacity(), v8::internal::EmbedderDataArray::EnsureCapacity(), v8::internal::OutBuffer< Char >::EnsureCapacity(), v8::internal::FastJsonStringifier< Char >::EnsureCapacity(), v8::internal::RegExpStack::EnsureCapacity(), v8::internal::compiler::BytecodeGraphBuilder::EnsureInputBufferSize(), v8::internal::MicrotaskQueueBuiltinsAssembler::EnterContext(), v8::internal::compiler::ParallelMove::Equals(), v8::base::erase_at(), v8::internal::Scavenger::EvacuateObject(), v8::internal::EvacuateVisitorBase::ExecuteMigrationObservers(), v8::internal::Zone::Expand(), wasm::ExportsImpl(), v8::internal::ExternalAssemblerBuffer(), v8::internal::MacroAssembler::ExtractBits(), v8::internal::compiler::ExtractBitsLatency(), v8::internal::ConstructorBuiltinsAssembler::FastNewFunctionContext(), v8::internal::HeapSnapshot::FillChildren(), v8::internal::wasm::LiftoffAssembler::FillStackSlotsWithZero(), v8::internal::compiler::BytecodeGraphBuilder::Environment::FillWithOsrValues(), cppgc::internal::HeapObjectHeader::Finalize(), cppgc::internal::anonymous_namespace{sweeper.cc}::SweepFinalizer::FinalizePage(), v8::internal::ObjectEntriesValuesBuiltinsAssembler::FinalizeValuesOrEntriesJSArray(), cppgc::internal::anonymous_namespace{sweeper.cc}::SweepFinalizer::FinalizeWithDeadlineAndSize(), v8::internal::compiler::turboshaft::MemoryContentTable::Find(), v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::Find(), v8::internal::ConservativeStackVisitorBase< ConcreteVisitor >::FindBasePtr(), v8::base::anonymous_namespace{platform-linux.cc}::FindEnclosingMapping(), v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::FindImpl(), v8::internal::HeapObjectsMap::FindOrAddEntry(), v8::internal::compiler::InstructionSelector::FindProjection(), v8::internal::maglev::MaglevGraphBuilder::FinishInlinedBlockForCaller(), v8::internal::OffHeapHashTableBase< Derived >::FirstProbe(), v8::internal::anonymous_namespace{runtime-test.cc}::FixedArrayLenFromSize(), v8::internal::FlattenRegionsToParts(), v8::internal::CpuFeatures::FlushICache(), v8::internal::FlushInstructionCache(), v8::internal::maglev::MaglevGraphBuilder::FlushNodesToBlock(), v8::internal::FoldedMutableHeapNumberAllocation::FoldedMutableHeapNumberAllocation(), v8::internal::WritableFreeSpace::ForNonExecutableMemory(), v8::base::OS::Free(), v8::internal::Sweeper::FreeAndProcessFreedMemory(), v8::internal::NewLargeObjectSpace::FreeDeadObjects(), v8::base::EmulatedVirtualAddressSubspace::FreeGuardRegion(), v8::base::LsanVirtualAddressSpace::FreeGuardRegion(), v8::base::VirtualAddressSpace::FreeGuardRegion(), v8::base::VirtualAddressSubspace::FreeGuardRegion(), cppgc::internal::PageBackend::FreeLargePageMemory(), v8::internal::MemoryAllocator::FreeMemoryRegion(), v8::base::EmulatedVirtualAddressSubspace::FreePages(), v8::base::VirtualAddressSpace::FreePages(), v8::base::VirtualAddressSubspace::FreePages(), v8::internal::FreePages(), v8::base::PageAllocator::FreePages(), v8::base::LsanPageAllocator::FreePages(), v8::base::VirtualAddressSpacePageAllocator::FreePages(), v8::internal::WritableJitPage::FreeRange(), v8::base::OS::FreeShared(), v8::base::EmulatedVirtualAddressSubspace::FreeSharedPages(), v8::base::VirtualAddressSpace::FreeSharedPages(), v8::base::VirtualAddressSubspace::FreeSharedPages(), v8::internal::torque::ImplementationVisitor::GenerateBuiltinDefinitionsAndInterfaceDescriptors(), v8::internal::torque::ImplementationVisitor::GenerateCall(), v8::internal::torque::ImplementationVisitor::GenerateFunction(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GenerateI32(), v8::internal::Genesis::Genesis(), v8::internal::SnapshotByteSource::GetBlob(), v8::internal::wasm::GetCustomSections(), v8::internal::TypedArrayBuiltinsAssembler::GetDefaultConstructor(), anonymous_namespace{mksnapshot.cc}::GetExtraCode(), v8::internal::Assembler::getfield(), cppgc::internal::ObjectAllocator::GetInitialSpaceIndexForSize(), v8::internal::IndexGenerator::GetNext(), v8::internal::EhFrameIterator::GetNextSLeb128(), v8::internal::EhFrameIterator::GetNextULeb128(), v8::internal::compiler::turboshaft::MaybeRedundantStoresTable::GetObservability(), v8::internal::wasm::gdb_server::Packet::GetPacketData(), v8::Deserializer::GetSharedArrayBufferFromId(), v8::internal::TypedArrayBuiltinsAssembler::GetTypedArrayElementsInfo(), v8::internal::TypedArrayBuiltinsAssembler::GetTypedArrayElementSize(), v8::internal::GetUncompressedSize(), v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmData(), v8::internal::wasm::gdb_server::GdbServer::GetWasmData(), v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmGlobal(), v8::internal::wasm::gdb_server::GdbServer::GetWasmGlobal(), v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmLocal(), v8::internal::wasm::gdb_server::GdbServer::GetWasmLocal(), v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmMemory(), v8::internal::wasm::gdb_server::GdbServer::GetWasmMemory(), v8::internal::wasm::gdb_server::GdbServer::GetWasmModuleBytes(), v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmModuleBytes(), v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmStackValue(), v8::internal::wasm::gdb_server::GdbServer::GetWasmStackValue(), v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmValue(), v8::internal::interpreter::BytecodeArrayRandomIterator::GoToEnd(), v8::internal::anonymous_namespace{assembler.cc}::DefaultAssemblerBuffer::Grow(), v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::HasValueWithIncorrectMutability(), v8::internal::ETWJITInterface::Header(), cppgc::internal::HeapObjectHeader::HeapObjectHeader(), v8::internal::ObjectStats::HistogramIndexFromSize(), v8::internal::Assembler::ImmLSPair(), v8::ExternalMemoryAccounter::Increase(), v8::internal::AllocationStats::IncreaseAllocatedBytes(), v8::internal::compiler::InstructionSequence::IncreaseRpoForTesting(), v8::internal::NativeContextStats::IncrementSize(), v8::internal::IndexGenerator::IndexGenerator(), v8::internal::compiler::LoadElimination::IndexRange::IndexRange(), v8::internal::V8::Initialize(), v8::internal::RegExpResultVectorScope::Initialize(), v8::internal::wasm::WellKnownImportsList::Initialize(), v8::internal::JSObject::InitializeBody(), v8::internal::BuiltinsSorter::InitializeCallGraph(), v8::internal::wasm::WasmCodeAllocator::InitializeCodeRange(), v8::internal::InitializeICU(), v8::internal::compiler::EscapeAnalysisTracker::Scope::InitVirtualObject(), v8::internal::compiler::turboshaft::FastApiCallOp::inputs_rep(), v8::internal::compiler::turboshaft::MemoryContentTable::Insert(), v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::Insert(), v8::internal::MacroAssembler::InsertBits(), v8::internal::compiler::turboshaft::MemoryContentTable::InsertImmutable(), v8::internal::AsmJs::InstantiateAsmWasm(), v8::internal::Instruction::InstructionBits(), cppgc::internal::MakeGarbageCollectedTraitInternal::AllocationDispatcher< GCInfoType, CustomSpace, alignment >::Invoke(), cppgc::internal::MakeGarbageCollectedTraitInternal::AllocationDispatcher< GCInfoType, void, api_constants::kDefaultAlignment >::Invoke(), cppgc::internal::MakeGarbageCollectedTraitInternal::AllocationDispatcher< GCInfoType, void, alignment >::Invoke(), cppgc::internal::MakeGarbageCollectedTraitInternal::AllocationDispatcher< GCInfoType, CustomSpace, api_constants::kDefaultAlignment >::Invoke(), v8::internal::compiler::turboshaft::detail::is_unique_and_sorted(), v8::internal::torque::Item::IsComplete(), v8::internal::IsIdentityMapping(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::IsIntegerSet(), v8::internal::compiler::Arm64OperandGenerator::IsLoadStoreImmediate(), v8::internal::CPURegister::IsNone(), v8::internal::Heap::IsOldGenerationExpansionAllowed(), v8::internal::CodeStubAssembler::IsRegularHeapObjectSize(), v8::internal::compiler::anonymous_namespace{js-inlining-heuristic.cc}::IsSmall(), v8::internal::compiler::anonymous_namespace{js-inlining-heuristic.cc}::IsSmallWithHeapNumberParam(), v8::base::EmulatedVirtualAddressSubspace::IsUsableSizeForUnmappedRegion(), v8::internal::CPURegister::IsValid(), v8::internal::anonymous_namespace{asm-js.cc}::IsValidAsmjsMemorySize(), v8::internal::CPURegister::IsValidRegister(), v8::internal::CPURegister::IsValidVRegister(), v8::internal::torque::Item::Item(), v8::internal::Scavenger::IterateAndScavengePromotedObject(), v8::internal::HandleScopeImplementer::IterateThis(), v8::internal::wasm::WasmBytecode::JSToWasmWrapperPackedArraySize(), v8::internal::wasm::InstanceBuilder::LoadDataSegments(), v8::internal::wasm::LiftoffAssembler::LoadFromInstance(), v8::internal::wasm::LoadProfileFromFile(), v8::internal::maglev::MaglevAssembler::LoadSignedField(), v8::internal::Assembler::LoadStoreScaledImmOffset(), v8::internal::maglev::MaglevAssembler::LoadUnsignedField(), v8::internal::anonymous_namespace{object-stats.cc}::Log2ForSize(), v8::internal::LowLevelLogger::LogWriteBytes(), v8::internal::ThreadIsolation::JitPageReference::LookupAllocation(), v8::internal::ThreadIsolation::LookupJitAllocation(), v8::internal::ThreadIsolation::LookupJitPage(), v8::internal::ThreadIsolation::LookupJitPageLocked(), unibrow::LookupMapping(), unibrow::LookupPredicate(), v8::internal::ThreadIsolation::LookupWritableJitPage(), v8::base::anonymous_namespace{platform-darwin.cc}::mach_vm_map_wrapper(), v8::Shell::Main(), v8::internal::ThreadIsolation::MakeExecutable(), v8::internal::String::MakeExternal(), v8::internal::String::MakeExternalDuringGC(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::MostlySmallValueKindSig::MakeKinds(), v8::base::Malloc(), v8::internal::compiler::turboshaft::MaybeRedundantStoresTable::map_to_key(), v8::internal::WasmMemoryMapDescriptor::MapDescriptor(), v8::internal::CollectionsBuiltinsAssembler::MapIteratorToList(), v8::base::anonymous_namespace{platform-fuchsia.cc}::MapVmo(), v8::internal::interpreter::BytecodeJumpTable::mark_bound(), v8::internal::compiler::turboshaft::MaybeRedundantStoresTable::MarkStoreAsUnobservable(), v8::internal::compiler::turboshaft::LoopLabel< Ts >::MaterializeLoopPhisImpl(), v8::internal::compiler::turboshaft::LabelBase< loop, Ts >::MaterializePhisImpl(), v8::internal::interpreter::BytecodeArrayWriter::MaybeElideLastBytecode(), v8::internal::MaybeObjectSize::MaybeObjectSize(), v8::internal::wasm::NativeModuleSerializer::Measure(), v8::internal::MemCopy(), v8::internal::MemMove(), v8::internal::wasm::memory_copy_wrapper(), v8::internal::wasm::memory_fill_wrapper(), v8::internal::wasm::memory_init_wrapper(), v8::internal::wasm::WasmInterpreterRuntime::MemoryCopy(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::MemoryCopy(), v8::internal::wasm::TurboshaftGraphBuildingInterface::MemoryCopy(), v8::internal::wasm::WasmInterpreterRuntime::MemoryFill(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::MemoryFill(), v8::internal::wasm::TurboshaftGraphBuildingInterface::MemoryFill(), v8::internal::wasm::WasmInterpreterRuntime::MemoryInit(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::MemoryInit(), v8::internal::wasm::TurboshaftGraphBuildingInterface::MemoryInit(), cppgc::internal::MemoryRegion::MemoryRegion(), v8::internal::compiler::JSGraphAssembler::CatchScope::MergeExceptionalPaths(), v8::internal::maglev::StraightForwardRegisterAllocator::MergeRegisterValues(), v8::internal::EvacuateVisitorBase::MigrateObject(), v8::internal::Scavenger::MigrateObject(), v8::internal::maglev::Graph::min_maglev_stackslots_for_unoptimized_frame_size(), v8::internal::compiler::PersistentMap< Key, Value, Hasher >::Modify(), v8::internal::ProfilingMigrationObserver::Move(), v8::internal::Debug::TemporaryObjectsTracker::MoveEvent(), v8::internal::Heap::AllocationTrackerForDebugging::MoveEvent(), v8::internal::AddressToTraceMap::MoveObject(), v8::internal::Instruction::NEONLSIndex(), v8::internal::NeonSizeToDataType(), v8::internal::Factory::New(), v8::internal::WasmExceptionPackage::New(), v8::internal::SourceTextModuleInfo::New(), v8::internal::compiler::Instruction::New(), v8::internal::compiler::Node::OutOfLineInputs::New(), v8::internal::NewArray(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::NewArray(), v8::internal::FactoryBase< Impl >::NewArrayList(), v8::internal::NewAssemblerBuffer(), v8::internal::Factory::NewAtomRegExpData(), v8::internal::Parser::NewClassPropertyList(), v8::internal::Parser::NewClassStaticElementList(), v8::internal::FactoryBase< Impl >::NewCode(), v8::internal::Factory::NewContextInternal(), v8::internal::FactoryBase< Impl >::NewCoverageInfo(), v8::internal::FactoryBase< Impl >::NewDescriptorArray(), v8::internal::Factory::NewDictionaryTemplateInfo(), v8::internal::Factory::NewEmbedderDataArray(), v8::internal::V8FileLogger::NewEvent(), v8::internal::Factory::NewExperimentalRegExpData(), v8::internal::FactoryBase< Impl >::NewFeedbackMetadata(), v8::internal::Factory::NewFeedbackVector(), v8::internal::Factory::NewFillerObject(), v8::internal::Factory::NewFunctionTemplateInfo(), v8::internal::compiler::Node::NewImpl(), v8::internal::Factory::NewIrRegExpData(), v8::internal::Factory::NewObjectTemplateInfo(), v8::internal::FactoryBase< Impl >::NewPreparseData(), v8::internal::FactoryBase< Impl >::NewRawStringWithMap(), v8::internal::FactoryBase< Impl >::NewScopeInfo(), v8::internal::Factory::NewStringFromUtf8(), v8::internal::FactoryBase< Impl >::NewStruct(), v8::internal::FactoryBase< Impl >::NewStructInternal(), v8::internal::FactoryBase< Impl >::NewSwissNameDictionaryWithCapacity(), v8::internal::Factory::NewUninitializedJSGlobalProxy(), v8::internal::compiler::EscapeAnalysisTracker::NewVirtualObject(), v8::internal::HashTableBase::NextProbe(), v8::internal::OffHeapHashTableBase< Derived >::NextProbe(), v8::internal::torque::Item::NextSymbol(), v8::anonymous_namespace{d8.cc}::NormalizePath(), cppgc::internal::StatsCollector::NotifyAllocatedMemory(), cppgc::internal::PreFinalizerHandler::NotifyAllocationInPrefinalizer(), v8::internal::StickySpace::NotifyBlackAreaCreated(), v8::internal::StickySpace::NotifyBlackAreaDestroyed(), cppgc::internal::StatsCollector::NotifyFreedMemory(), v8::internal::HeapProfilerNativeMoveListener::ObjectMoveEvent(), v8::internal::HeapProfiler::ObjectMoveEvent(), v8::WasmStreaming::WasmStreamingImpl::OnBytesReceived(), v8::internal::SamplingEventsProcessor::operator new(), v8::internal::Malloced::operator new(), v8::internal::SharedStructTypeRegistry::Data::operator new(), v8::internal::StringTable::Data::operator new(), v8::internal::FrameDescription::operator new(), v8::internal::HandleScope::operator new(), cppgc::internal::NormalPage::IteratorImpl< T >::operator++(), v8::internal::wasm::WasmInitExpr::operator==(), v8::internal::compiler::RawMachineAssembler::OptimizeControlFlow(), v8::internal::compiler::RawMachineAssembler::OptimizedAllocate(), v8::internal::compiler::CodeAssembler::OptimizedAllocate(), v8::internal::compiler::turboshaft::StackSlotOp::options(), cppgc::internal::ObjectAllocator::OutOfLineAllocate(), cppgc::internal::ObjectAllocator::OutOfLineAllocateGCSafePoint(), cppgc::internal::ObjectAllocator::OutOfLineAllocateImpl(), v8::internal::anonymous_namespace{code-stub-assembler.cc}::MetaTableAccessor::OverallOffset(), v8::base::OwnedCopyOf(), v8::internal::EmbeddedData::PadAndAlignCode(), v8::internal::EmbeddedData::PadAndAlignData(), v8::internal::EmbeddedData::PaddedInstructionSizeOf(), v8::internal::ReadOnlyHeapImageDeserializer::PageAt(), v8::internal::Sweeper::LocalSweeper::ParallelIteratePromotedPage(), v8::internal::compiler::turboshaft::GenericReducerBase< Next >::Phi(), v8::internal::MacroAssembler::Pop(), v8::internal::compiler::ReferenceMapPopulator::PopulateReferenceMaps(), v8::internal::wasm::LocalDeclEncoder::Prepend(), v8::internal::maglev::DeadNodeSweepingProcessor::Process(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::turboshaft::MemoryAnalyzer::ProcessAllocation(), v8::internal::compiler::turboshaft::RedundantStoreAnalysis::ProcessBlock(), v8::internal::wasm::gdb_server::Target::ProcessQueryPacket(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessStructGet(), v8::internal::MacroAssembler::Push(), v8::internal::MacroAssembler::PushArray(), v8::base::anonymous_namespace{platform-cygwin.cc}::RandomizedVirtualAlloc(), v8::base::EmulatedVirtualAddressSubspace::RandomPageAddress(), v8::base::VirtualAddressSubspace::RandomPageAddress(), v8::internal::compiler::RegisterAllocationData::RangesDefinedInDeferredStayInDeferred(), v8::internal::EvacuateVisitorBase::RawMigrateObject(), v8::internal::Sweeper::RawSweep(), v8::internal::wasm::AsyncStreamingDecoder::DecodeVarInt32::ReadBytes(), v8::Shell::ReadChars(), v8::internal::anonymous_namespace{utils.cc}::ReadCharsFromFile(), v8::Shell::ReadFile(), v8::Shell::ReadLines(), v8::internal::ValueDeserializer::ReadRawBytes(), v8::internal::ValueDeserializer::ReadRawTwoBytes(), v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::Reader::ReadVector(), v8::base::Realloc(), v8::ValueSerializer::Delegate::ReallocateBufferMemory(), v8::Serializer::ReallocateBufferMemory(), v8::base::VirtualAddressSpace::RecommitPages(), v8::base::EmulatedVirtualAddressSubspace::RecommitPages(), v8::base::LsanVirtualAddressSpace::RecommitPages(), v8::base::VirtualAddressSubspace::RecommitPages(), v8::base::OS::RecommitPages(), v8::base::PageAllocator::RecommitPages(), v8::base::LsanPageAllocator::RecommitPages(), v8::base::VirtualAddressSpacePageAllocator::RecommitPages(), v8::internal::SharedHeapSerializer::ReconstructSharedHeapObjectCacheForTesting(), v8::internal::CodeStatistics::RecordCodeAndMetadataStatistics(), v8::internal::Assembler::RecordConstPool(), v8::internal::ObjectStatsCollectorImpl::RecordExternalResourceStats(), v8::internal::MemoryAllocator::RecordMemoryChunkDestroyed(), v8::internal::ObjectStats::RecordObjectStats(), v8::internal::ObjectStatsCollectorImpl::RecordObjectStats(), v8::internal::wasm::LiftoffAssembler::RecordOolSpillSpaceSize(), v8::internal::anonymous_namespace{heap-snapshot-generator.cc}::ExternalStringRecorder::RecordSharedMemoryUsage(), v8::internal::ObjectStatsCollectorImpl::RecordVirtualObjectStats(), v8::internal::ObjectStats::RecordVirtualObjectStats(), v8::internal::compiler::MemoryLowering::ReduceAllocateRaw(), v8::internal::OutBuffer< Char >::ReduceCurrentCapacity(), v8::internal::compiler::FastApiCallReducerAssembler::ReduceFastApiCall(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateObject(), v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::ReduceNode(), v8::internal::RegExpResultVectorScope::RegExpResultVectorScope(), v8::internal::ThreadIsolation::JitPageReference::RegisterAllocation(), v8::internal::trap_handler::RegisterHandlerData(), v8::internal::ThreadIsolation::RegisterInstructionStreamAllocation(), v8::internal::ThreadIsolation::RegisterJitAllocation(), v8::internal::ThreadIsolation::RegisterJitAllocationForTesting(), v8::internal::ThreadIsolation::RegisterJitAllocations(), v8::internal::ThreadIsolation::RegisterJitPage(), v8::internal::wasm::WasmCode::RegisterTrapHandlerData(), v8::internal::trap_handler::RegisterV8Sandbox(), v8::base::OS::Release(), v8::internal::ReleasePages(), v8::base::PageAllocator::ReleasePages(), v8::base::LsanPageAllocator::ReleasePages(), v8::base::VirtualAddressSpacePageAllocator::ReleasePages(), cppgc::internal::NormalPageMemoryPool::ReleasePooledPages(), cppgc::internal::anonymous_namespace{compactor.cc}::MovableReferences::Relocate(), cppgc::internal::anonymous_namespace{compactor.cc}::MovableReferences::RelocateInteriorReferences(), cppgc::internal::anonymous_namespace{compactor.cc}::CompactionState::RelocateObject(), v8::base::OS::RemapPages(), v8::base::PageAllocator::RemapShared(), v8::base::OS::RemapShared(), cppgc::internal::PageMemoryRegionTree::Remove(), v8::internal::anonymous_namespace{heap.cc}::ReportDuplicates(), v8::internal::baseline::BytecodeOffsetTableBuilder::Reserve(), v8_inspector::DisassemblyChunk::Reserve(), v8::internal::wasm::TypeCanonicalizer::CanonicalTypeVector::reserve(), v8::internal::compiler::StateValueList::ReserveSize(), v8::internal::SnapshotData::Resize(), v8::internal::compiler::CommonOperatorBuilder::ResizeMergeOrPhi(), v8::internal::compiler::LiveRangeConnector::ResolveControlFlow(), v8::internal::compiler::ConstraintBuilder::ResolvePhis(), v8_inspector::V8RuntimeAgentImpl::restore(), v8::internal::maglev::MaglevAssembler::ReverseByteOrder(), v8::internal::ZoneChunkList< T >::Rewind(), v8::internal::MicrotaskQueueBuiltinsAssembler::RewindEnteredContext(), v8::internal::torque::RunEarleyAlgorithm(), v8::internal::RUNTIME_FUNCTION(), v8::internal::wasm::Handlers< Compressed >::s2s_ArrayCopy(), v8::internal::wasm::Handlers< Compressed >::s2s_ArrayFill(), v8::internal::wasm::Handlers< Compressed >::s2s_ArrayInitSegment(), v8::internal::wasm::Handlers< Compressed >::s2s_Memory64Copy(), v8::internal::wasm::Handlers< Compressed >::s2s_Memory64Fill(), v8::internal::wasm::Handlers< Compressed >::s2s_Memory64Init(), v8::internal::wasm::Handlers< Compressed >::s2s_MemoryCopy(), v8::internal::wasm::Handlers< Compressed >::s2s_MemoryFill(), v8::internal::wasm::Handlers< Compressed >::s2s_MemoryInit(), v8::internal::wasm::Handlers< Compressed >::s2s_RefArrayFill(), v8::internal::wasm::Handlers< Compressed >::s2s_Table64CopyImpl(), v8::internal::wasm::Handlers< Compressed >::s2s_Table64Init(), v8::internal::wasm::Handlers< Compressed >::s2s_Table64Size(), v8::internal::wasm::Handlers< Compressed >::s2s_TableCopy(), v8::internal::wasm::Handlers< Compressed >::s2s_TableInit(), v8::internal::wasm::Handlers< Compressed >::s2s_TableSize(), v8::internal::SamplingHeapProfiler::SampleObject(), v8::internal::SamplingHeapProfiler::ScaleSample(), v8_inspector::anonymous_namespace{search-util.cc}::scriptRegexpMatchesByLines(), v8::base::PageAllocator::SealPages(), v8::internal::FreeListCategory::SearchForNodeInList(), v8::internal::ZoneChunkList< T >::SeekIndex(), v8::internal::compiler::InstructionSelector::SelectInstructions(), v8::internal::SourceTextModuleDescriptor::AstModuleRequest::Serialize(), v8::internal::Serializer::ObjectSerializer::SerializeContent(), v8::internal::SerializedCodeData::SerializedCodeData(), v8::internal::Serializer::ObjectSerializer::SerializeObject(), v8::internal::Serializer::ObjectSerializer::SerializePrologue(), cppgc::internal::NormalPageSpace::LinearAllocationBuffer::Set(), v8::internal::Factory::CodeBuilder::set_inlined_bytecode_size(), v8::internal::OptimizedCompilationInfo::set_inlined_bytecode_size(), v8::internal::maglev::Graph::set_max_deopted_stack_size(), v8::internal::maglev::AllocationBlock::set_size(), v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::set_total_fields_size(), cppgc::internal::HeapObjectHeader::SetAllocatedSize(), v8::base::OS::SetDataReadOnly(), v8::internal::ETWJITInterface::SetFieldDescriptors(), v8_inspector::V8RuntimeAgentImpl::setMaxCallStackSizeToCapture(), v8_inspector::V8Debugger::setMaxCallStackSizeToCapture(), cppgc::internal::SetMemoryInaccessible(), v8::internal::ETWJITInterface::SetMetaDescriptors(), v8::internal::CollectionsBuiltinsAssembler::SetOrSetIteratorToList(), v8::base::VirtualAddressSpace::SetPagePermissions(), v8::base::EmulatedVirtualAddressSubspace::SetPagePermissions(), v8::base::LsanVirtualAddressSpace::SetPagePermissions(), v8::base::VirtualAddressSubspace::SetPagePermissions(), v8::internal::SetPermissions(), v8::base::OS::SetPermissions(), v8::base::PageAllocator::SetPermissions(), v8::base::LsanPageAllocator::SetPermissions(), v8::base::VirtualAddressSpacePageAllocator::SetPermissions(), v8::base::anonymous_namespace{platform-fuchsia.cc}::SetPermissionsInternal(), v8::internal::JSObject::SetPrototype(), v8::internal::wasm::TurboshaftGraphBuildingInterface::should_inline(), v8::internal::LargeObjectSpace::ShrinkPageToObjectSize(), v8::internal::wasm::WasmOpcodes::Signature(), v8::internal::SimpleStringBuilder::SimpleStringBuilder(), cppgc::internal::FreeList::Size(), v8::internal::wasm::LocalDeclEncoder::Size(), v8::internal::anonymous_namespace{elements-kind.cc}::size_to_shift(), v8::internal::anonymous_namespace{heap-snapshot-generator.cc}::SizeForSnapshot(), v8::internal::Code::SizeIncludingMetadata(), v8::internal::torque::SizeOf(), v8::internal::wasm::LEBHelper::sizeof_i32v(), v8::internal::wasm::LEBHelper::sizeof_i64v(), v8::internal::wasm::LEBHelper::sizeof_u32v(), v8::internal::wasm::LEBHelper::sizeof_u64v(), v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::Writer::Skip(), v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::Reader::Skip(), v8::internal::SnapshotData::SnapshotData(), v8::internal::compiler::SourceIdAssigner::SourceIdAssigner(), v8::internal::compiler::RegisterAllocator::SplitAndSpillRangesDefinedByMemoryOperand(), v8::internal::ZoneChunkList< T >::SplitAt(), v8::internal::torque::Item::SplitByChildren(), v8::internal::ThreadIsolation::SplitJitPage(), v8::internal::ThreadIsolation::SplitJitPageLocked(), v8::internal::JsonStringifier::StackPush(), v8::internal::compiler::RawMachineAssembler::StackSlot(), v8::internal::compiler::GraphAssembler::StackSlot(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StackSlot(), v8::internal::compiler::MachineOperatorBuilder::StackSlot(), v8::internal::compiler::CodeAssembler::StackSlotPtr(), v8::internal::compiler::turboshaft::FrameStateOp::state_values_count(), v8::internal::compiler::ZoneStats::StatsScope::StatsScope(), v8::internal::SamplingHeapProfiler::Observer::Step(), v8::internal::maglev::MaglevAssembler::StoreField(), v8::internal::wasm::gdb_server::StoreValue(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StringNewWtf16(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StringNewWtf8(), v8::internal::Sweeper::SweepEmptyNewSpacePage(), cppgc::internal::Sweeper::SweepForAllocationIfRunning(), cppgc::internal::Sweeper::SweeperImpl::SweepForAllocationIfRunning(), cppgc::internal::Sweeper::SweeperImpl::SweepForLargeAllocation(), cppgc::internal::Sweeper::SweeperImpl::SweepForNormalAllocation(), cppgc::internal::anonymous_namespace{sweeper.cc}::SweepNormalPage(), cppgc::internal::anonymous_namespace{sweeper.cc}::MutatorThreadSweeper::SweepWithDeadlineAndSize(), v8::internal::wasm::WasmInterpreterRuntime::TableCopy(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::TableCopy(), v8::internal::wasm::WasmInterpreterRuntime::TableInit(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::TableInit(), v8::internal::wasm::TurboshaftGraphBuildingInterface::TableInit(), cppgc::internal::NormalPageMemoryPool::Take(), v8::internal::TF_BUILTIN(), v8::internal::MinorMarkSweepCollector::TraceFragmentation(), v8::internal::compiler::DeadCodeElimination::TrimMergeOrPhi(), v8::internal::wasm::WasmCodeManager::TryAllocate(), v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteralElements(), cppgc::internal::anonymous_namespace{object-allocator.cc}::TryAllocateLargeObject(), cppgc::internal::anonymous_namespace{object-allocator.cc}::TryAllocateLargeObjectImpl(), cppgc::internal::PageBackend::TryAllocateLargePageMemory(), v8::internal::MemoryAllocator::TryAllocateUninitializedLargePageFromPool(), v8::internal::compiler::ArrayBufferViewAccessBuilder::TryComputeStaticElementSize(), cppgc::internal::LargePage::TryCreate(), cppgc::internal::NormalPage::TryCreate(), v8::internal::EvacuateVisitorBase::TryEvacuateObject(), v8::internal::ThreadIsolation::TryLookupJitPage(), v8::internal::ThreadIsolation::TryLookupJitPageLocked(), v8::internal::Factory::TryNewFixedArray(), v8::internal::TryNumberToSize(), v8::internal::maglev::MaglevGraphBuilder::TryReadBoilerplateForFastLiteral(), cppgc::internal::ObjectAllocator::TryRefillLinearAllocationBuffer(), cppgc::internal::ObjectAllocator::TryRefillLinearAllocationBufferFromFreeList(), v8::internal::compiler::LinearScanAllocator::TryReuseSpillForPhi(), v8::internal::WasmMemoryMapDescriptor::UnmapDescriptor(), v8::base::EmulatedVirtualAddressSubspace::unmapped_size(), v8::base::anonymous_namespace{platform-fuchsia.cc}::UnmapVmo(), v8::internal::ThreadIsolation::JitPageReference::UnregisterAllocationsExcept(), v8::internal::ThreadIsolation::UnregisterJitAllocationForTesting(), v8::internal::ThreadIsolation::UnregisterJitPage(), v8::internal::MemoryAllocator::UnregisterMemoryChunk(), v8::internal::ThreadIsolation::JitPageReference::UnregisterRange(), v8::internal::MemoryAllocator::UnregisterSharedMemoryChunk(), v8::internal::trap_handler::UnregisterV8Sandbox(), v8::internal::ThreadIsolation::UnregisterWasmAllocation(), v8::internal::compiler::unrolling_count_heuristic(), v8::Shell::update_script_size(), v8::internal::wasm::NativeModule::UpdateCodeSize(), v8::internal::HeapObjectsMap::UpdateObjectSize(), v8::internal::HeapProfiler::UpdateObjectSizeEvent(), v8::internal::compiler::InstructionSelector::UpdateRenamesInPhi(), v8::internal::compiler::turboshaft::UseMap::uses(), v8::internal::wasm::AsmJsParser::ValidateHeapAccess(), v8::internal::wasm::value_kind_size(), v8::ValueDeserializer::ValueDeserializer(), v8::internal::ObjectCacheIndexMap::Values(), v8::base::VectorOf(), v8::internal::compiler::RegisterAllocatorVerifier::VerifyAssignment(), v8::internal::maglev::FixedInputNodeTMixin< InputCount, Base, Derived >::VerifyInputs(), v8::base::VirtualAddressSubspace::VirtualAddressSubspace(), v8::base::anonymous_namespace{platform-win32.cc}::VirtualAllocWithHint(), v8::base::anonymous_namespace{platform-win32.cc}::VirtualAllocWrapper(), v8::internal::EvacuateNewSpaceVisitor::Visit(), v8::internal::EvacuateNewToOldSpacePageVisitor::Visit(), v8::internal::EvacuateOldSpaceVisitor::Visit(), v8::internal::EvacuateRecordOnlyVisitor::Visit(), v8::internal::ScavengeVisitor::VisitCppHeapExternalObject(), v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitDescriptorArray(), v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitDescriptorArrayStrongly(), v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitFixedArrayWithProgressTracker(), v8::internal::ScavengeVisitor::VisitJSApiObject(), v8::internal::ScavengeVisitor::VisitJSArrayBuffer(), v8::internal::HeapVisitor< ConcreteVisitor >::VisitJSObjectSubclass(), v8::internal::LiveObjectVisitor::VisitMarkedObjects(), v8::internal::LiveObjectVisitor::VisitMarkedObjectsNoFail(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitOpNoMappingUpdate(), v8::internal::ConcurrentHeapVisitor< ConcreteVisitor >::VisitStringLocked(), wasm_instance_new(), wasm_val_vec_new(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::WasmAllocateStruct(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyExceptionImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryMapDescriptorImpl(), v8::internal::compiler::Word32AtomicCompareExchangeLatency(), v8::internal::compiler::Word32AtomicExchangeLatency(), v8::internal::StaticRootsTableGen::write(), v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc}::HeapSnapshotOutputStream::WriteAsciiChunk(), v8::internal::FileOutputStream::WriteAsciiChunk(), v8::internal::StringOutputStream::WriteAsciiChunk(), v8::internal::EmbeddedFileWriter::WriteBinaryContentsAsInlineAssembly(), v8::internal::EmbeddedFileWriter::WriteBuiltin(), v8::internal::WriteBytes(), v8::internal::EhFrameWriter::WriteBytes(), v8::internal::WriteChars(), v8::internal::anonymous_namespace{utils.cc}::WriteCharsToFile(), v8::internal::wasm::NativeModuleSerializer::WriteCode(), v8::internal::Assembler::WriteCodeComments(), v8::internal::EmbeddedFileWriter::WriteExternalFilenames(), v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc}::HeapStatsStream::WriteHeapStatsChunk(), v8::internal::ThreadIsolation::WriteProtectMemory(), v8::internal::wasm::WasmModuleBuilder::WriteTo(), v8::internal::heap::ZapBlock(), v8::internal::anonymous_namespace{sweeper.cc}::ZapDeadObjectsOnPage(), cppgc::internal::ZapMemory(), v8::internal::Sweeper::ZeroOrDiscardUnusedMemory(), and v8::internal::ReadOnlyArtifacts::~ReadOnlyArtifacts().
space()
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi space (in MBytes)
store()
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats store (v8::tracing::TracingCategoryObserver::ENABLED_BY_NATIVE)
Referenced by v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::wasm::LiftoffAssembler::AtomicCompareExchange(), v8::internal::wasm::liftoff::AtomicOp32(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::AtomicStoreParametersOf(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::AtomicStoreParametersOf(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::AtomicStoreParametersOf(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::AtomicStoreParametersOf(), wasm::anonymous_namespace{c-api.cc}::CreateFrameFromInternal(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeStoreMem(), v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::DeleteCommon(), v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::DirectCollectElementIndicesImpl(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::EmitStoreFieldStatement(), v8::internal::anonymous_namespace{elements.cc}::FastSloppyArgumentsElementsAccessor::GetArguments(), v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::GetCapacityImpl(), v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::GetEntryForIndexImpl(), v8::internal::JSObject::GetFastElementsUsage(), wasm::anonymous_namespace{c-api.cc}::GetInstance(), v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::GetRaw(), v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::HasEntryImpl(), v8::internal::HoleyElementsUsage(), v8::internal::compiler::turboshaft::MemoryContentTable::Insert(), v8::internal::compiler::BasicBlockInstrumentor::Instrument(), v8::internal::compiler::turboshaft::MemoryContentTable::Invalidate(), v8::internal::compiler::InstructionSelector::IsSourcePositionUsed(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::LoadStoreView::LoadStoreView(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::LoadStoreView::LoadStoreView(), wasm::anonymous_namespace{c-api.cc}::make_func(), v8::internal::compiler::turboshaft::LateEscapeAnalysisAnalyzer::MarkToRemove(), v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::NormalizeImpl(), wasm::anonymous_namespace{c-api.cc}::PopArgs(), v8::internal::compiler::turboshaft::JSONTurboshaftGraphWriter::PrintEdges(), v8::internal::compiler::turboshaft::MemoryAnalyzer::Process(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessAtomicRMW(), v8::internal::compiler::turboshaft::RedundantStoreAnalysis::ProcessBlock(), v8::internal::compiler::turboshaft::anonymous_namespace{decompression-optimization.cc}::DecompressionAnalyzer::ProcessOperation(), v8::internal::compiler::turboshaft::MemoryAnalyzer::ProcessStore(), v8::internal::compiler::turboshaft::PretenuringPropagationAnalyzer::ProcessStore(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessStore(), v8::internal::NodeBase< Child >::Publish(), v8::internal::TracedNode::Publish(), v8::internal::GrowableFixedArray::Push(), wasm::anonymous_namespace{c-api.cc}::PushArgs(), v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::Reconfigure(), v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::ReconfigureImpl(), v8::internal::anonymous_namespace{elements.cc}::SlowSloppyArgumentsElementsAccessor::ReconfigureImpl(), v8::internal::anonymous_namespace{elements.cc}::FastSloppyArgumentsElementsAccessor::ReconfigureImpl(), v8::internal::anonymous_namespace{elements.cc}::StringWrapperElementsAccessor< Subclass, BackingStoreAccessor, KindTraits >::ReconfigureImpl(), v8::internal::compiler::TFGraph::RecordSimdStore(), v8::internal::compiler::JSContextSpecialization::ReduceJSStoreContext(), v8::internal::compiler::WasmGCLowering::ReduceWasmArraySet(), v8::internal::compiler::WasmGCLowering::ReduceWasmStructSet(), v8::internal::RELEASE_ACQUIRE_ACCESSORS(), v8::internal::TracedNode::set_raw_object(), v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::SetImpl(), v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::SetImpl(), cppgc::internal::CrossThreadPersistentBase::SetNodeSafe(), cppgc::internal::MemberBase< StorageType >::SetRawStorageAtomic(), v8::internal::SetSlotThreadSafe(), v8::TracedReferenceBase::SetSlotThreadSafe(), v8::internal::compiler::turboshaft::MemoryAnalyzer::SkipWriteBarrier(), v8::internal::compiler::turboshaft::StoreStoreEliminationReducer< Next >::Store(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Store(), v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::Store(), v8::internal::maglev::MaglevGraphBuilder::StoreAndCacheContextSlot(), cppgc::internal::RawPointer::StoreAtomic(), v8::internal::AccessorAssembler::StoreGlobalIC_PropertyCellCase(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::TryMatchBaseWithScaledIndexAndDisplacement(), v8::internal::compiler::TryMatchBaseWithScaledIndexAndDisplacement64(), v8::internal::maglev::MaglevGraphBuilder::TrySpecializeStoreContextSlot(), wasm::anonymous_namespace{c-api.cc}::V8RefValueToWasm(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitAtomicStore(), v8::internal::compiler::VisitGeneralStore(), v8::internal::compiler::InstructionSelector::VisitNode(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitStoreCommon(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitStoreCommon(), v8::internal::compiler::VisitStoreCommon(), wasm_foreign_new(), wasm_func_new(), wasm_func_new_with_env(), wasm_global_new(), wasm_instance_new(), wasm_memory_new(), wasm_module_deserialize(), wasm_module_new(), wasm_module_obtain(), wasm_module_validate(), wasm_table_new(), wasm_trap_new(), and v8::internal::WritableJitAllocation::WriteValue().
time()
refactor address components for immediate indexing make OptimizeMaglevOnNextCall optimize to turbofan instead of maglev filter for tracing turbofan compilation trace turbo cfg trace TurboFan s graph trimmer trace TurboFan s control equivalence trace TurboFan s register allocator trace stack load store counters for optimized code in run time (x64 only)
Referenced by v8::base::WindowsTimezoneCache::DaylightSavingsOffset(), v8::base::PosixTimezoneCache::DaylightSavingsOffset(), cppgc::internal::StatsCollector::InternalScope< trace_category, scope_category >::IncreaseScopeTime(), v8::base::LocalTimeOffset(), v8::base::AIXTimezoneCache::LocalTimeOffset(), v8::base::PosixDefaultTimezoneCache::LocalTimeOffset(), v8::base::ZOSTimezoneCache::LocalTimeOffset(), v8::base::CygwinTimezoneCache::LocalTimezone(), v8::base::SolarisTimezoneCache::LocalTimezone(), v8::base::WindowsTimezoneCache::LocalTimezone(), v8::base::ZOSTimezoneCache::LocalTimezone(), v8::base::PosixDefaultTimezoneCache::LocalTimezone(), v8::Date::New(), v8::base::operator+(), v8::base::operator<<(), v8::Date::Parse(), cppgc::internal::StatsCollector::RecordHistogramSample(), and v8::base::ConditionVariable::WaitFor().
Turboshaft()
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via Turboshaft (instead of via ` ` TurboFan) [inline]
use()
other heap size generate builtins concurrently on separate threads in mksnapshot track concurrent recompilation artificial compilation delay in ms max number of threads that concurrent Turbofan can use (0 for unbounded)
Referenced by v8::internal::compiler::turboshaft::UseMap::AddUse(), v8::internal::maglev::ValueNode::advance_next_use(), v8::internal::compiler::turboshaft::LateEscapeAnalysisAnalyzer::AllocationIsEscaping(), v8::internal::compiler::Node::AppendInput(), v8::internal::compiler::Node::AppendUse(), v8::internal::compiler::BranchMatcher::BranchMatcher(), v8::internal::compiler::Node::BranchUseCount(), v8::internal::compiler::InstructionSelector::CanDoBranchIfOverflowFusion(), v8::internal::compiler::Verifier::Visitor::Check(), v8::internal::compiler::Verifier::Visitor::CheckOutput(), v8::internal::compiler::Verifier::Visitor::CheckSwitch(), v8::internal::wasm::LiftoffAssembler::ClearRegister(), v8::internal::compiler::NodeProperties::CollectControlProjections(), v8::internal::compiler::NodeProperties::CollectValueProjections(), v8::internal::compiler::LinearScheduler::ComputeControlLevel(), v8::internal::compiler::RepresentationSelector::ConvertInput(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::DecideVectorize(), v8::internal::compiler::ControlEquivalence::DFSPush(), v8::internal::compiler::Edge::Edge(), v8::internal::compiler::anonymous_namespace{memory-optimizer.cc}::EffectPhiForPhi(), v8::internal::compiler::EscapeAnalysisReducer::Finalize(), v8::internal::compiler::NodeProperties::FindProjection(), v8::internal::compiler::InstructionSelector::FindProjection(), v8::internal::compiler::EscapeAnalysisTracker::Scope::FrameStateMightLazyDeopt(), v8::internal::compiler::Scheduler::FuseFloatingControl(), v8::internal::compiler::ScheduleLateNodeVisitor::GetBlockForUse(), v8::internal::compiler::LinearScheduler::GetEarlySchedulePosition(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::GetExtractOpIfNeeded(), v8::internal::compiler::RepresentationSelector::GetOutputInfoForPhi(), v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::HasConcatOrPhiUse(), v8::internal::compiler::LoopFinder::HasMarkedExits(), v8::internal::compiler::InstructionSelector::InitializeCallBuffer(), v8::internal::compiler::JSInliner::InlineCall(), v8::internal::compiler::LoopFinderImpl::IsBackedge(), v8::internal::compiler::InstructionSelector::IsOnlyUserOfNodeInSameBlock(), v8::internal::compiler::AllNodes::Mark(), v8::internal::maglev::LiveRangeAndNextUseProcessor::MarkInputUses(), v8::internal::maglev::LiveRangeAndNextUseProcessor::MarkJumpInputUses(), v8::internal::compiler::turboshaft::LateEscapeAnalysisAnalyzer::MarkToRemove(), v8::internal::compiler::Node::NewImpl(), v8::internal::compiler::LiveRange::NextUsePosition(), v8::internal::interpreter::operator<<(), v8::internal::compiler::Node::OwnedBy(), v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::OwnedByAddressingOperand(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::OwnedByWord32Op(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::OwnsInput(), v8::internal::maglev::StraightForwardRegisterAllocator::PickRegisterToFree(), v8::internal::compiler::RepresentationSelector::ProcessInput(), v8::internal::compiler::LoopFinderImpl::PropagateForward(), v8::internal::compiler::turboshaft::LateEscapeAnalysisAnalyzer::RecordAllocateUse(), v8::internal::compiler::SimplifyTFLoops::Reduce(), v8::internal::compiler::WasmEscapeAnalysis::ReduceAllocateRaw(), v8::internal::compiler::BranchElimination::ReduceBranch(), v8::internal::compiler::CommonOperatorReducer::ReduceBranch(), v8::internal::compiler::LoadElimination::ReduceEffectPhi(), v8::internal::compiler::EffectGraphReducer::ReduceFrom(), v8::internal::compiler::DeadCodeElimination::ReduceLoopOrMerge(), v8::internal::compiler::CommonOperatorReducer::ReduceMerge(), v8::internal::compiler::LateEscapeAnalysis::RemoveAllocation(), v8::internal::compiler::DeadCodeElimination::RemoveLoopExit(), v8::internal::compiler::Node::RemoveUse(), v8::internal::compiler::Node::ReplaceInput(), v8::internal::compiler::Node::ReplaceUses(), v8::internal::compiler::LoopVariableOptimizer::Run(), v8::internal::compiler::ControlEquivalence::RunUndirectedDFS(), v8::internal::compiler::RepresentationSelector::RunVerifyPhase(), v8::internal::compiler::LoopFinderImpl::SetLoopMarkForLoopHeader(), v8::internal::compiler::MachineOperatorReducer::SwapBranches(), v8::internal::interpreter::BytecodeHandlerReducer< Next >::TrackRegisterUse(), v8::internal::compiler::LoopVariableOptimizer::TryGetInductionVariable(), v8::internal::compiler::InstructionSelector::TryPrepareScheduleFirstProjection(), v8::internal::compiler::RepresentationChanger::TypeError(), v8::internal::compiler::UnrollLoop(), v8::internal::compiler::Scheduler::UpdatePlacement(), v8::internal::compiler::Revectorizer::UpdateSources(), v8::internal::compiler::Node::UseCount(), v8::internal::compiler::ScheduleEarlyNodeVisitor::VisitNode(), v8::internal::compiler::StringBuilderOptimizer::VisitNode(), and v8::internal::compiler::RepresentationSelector::VisitNode().
X()
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and X (inclusive) [new]
Referenced by v8::bigint::Add(), v8::bigint::AddAndReturnCarry(), v8::bigint::AddAndReturnOverflow(), v8::bigint::AddOne(), v8::bigint::AddSigned(), v8::bigint::AsIntN(), v8::bigint::AsIntNResultLength(), v8::bigint::AsUintN_Neg(), v8::bigint::AsUintN_Pos(), v8::bigint::AsUintN_Pos_ResultLength(), v8::bigint::BitLength(), v8::bigint::BitwiseAnd_NegNeg(), v8::bigint::BitwiseAnd_PosNeg(), v8::bigint::BitwiseAnd_PosPos(), v8::bigint::BitwiseOr_NegNeg(), v8::bigint::BitwiseOr_PosNeg(), v8::bigint::BitwiseOr_PosPos(), v8::bigint::BitwiseXor_NegNeg(), v8::bigint::BitwiseXor_PosNeg(), v8::bigint::BitwiseXor_PosPos(), v8::bigint::anonymous_namespace{div-helpers.cc}::Copy(), v8::bigint::anonymous_namespace{div-barrett.cc}::DcheckIntegerPartRange(), v8::bigint::anonymous_namespace{mul-toom.cc}::DivideByThree(), v8::bigint::anonymous_namespace{mul-toom.cc}::DivideByTwo(), v8::bigint::InplaceAdd(), v8::bigint::InplaceSub(), v8::bigint::IsBitNormalized(), v8::bigint::IsDigitNormalized(), v8::bigint::ProcessorImpl::KaratsubaChunk(), v8::bigint::ProcessorImpl::KaratsubaMain(), v8::bigint::ProcessorImpl::KaratsubaStart(), v8::bigint::anonymous_namespace{mul-karatsuba.cc}::KaratsubaSubtractionHelper(), v8::bigint::LeftShift(), v8::bigint::ProcessorImpl::Multiply(), v8::bigint::Processor::Multiply(), v8::bigint::anonymous_namespace{mul-fft.cc}::MultiplyFFT_Inner(), v8::bigint::ProcessorImpl::MultiplyKaratsuba(), v8::bigint::MultiplyResultLength(), v8::bigint::ProcessorImpl::MultiplySchoolbook(), v8::bigint::ProcessorImpl::MultiplySingle(), v8::bigint::RightShift(), v8::bigint::RightShift_ResultLength(), v8::bigint::anonymous_namespace{div-burnikel.cc}::SetOnes(), v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::Start(), v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::Start_Default(), v8::bigint::SubAndReturnBorrow(), v8::bigint::Subtract(), v8::bigint::SubtractAndReturnBorrow(), v8::bigint::SubtractOne(), v8::bigint::SubtractSigned(), v8::bigint::anonymous_namespace{mul-toom.cc}::TimesTwo(), v8::bigint::ProcessorImpl::ToString(), v8::bigint::Processor::ToString(), v8::bigint::ProcessorImpl::ToStringImpl(), v8::bigint::ToStringResultLength(), v8::bigint::anonymous_namespace{bitwise.cc}::TruncateAndSubFromPowerOfTwo(), and v8::bigint::anonymous_namespace{bitwise.cc}::TruncateToNBits().
Variable Documentation
all
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at all [inline]
Definition at line 1570 of file flag-definitions.h.
Referenced by v8::internal::compiler::Verifier::Visitor::Check(), v8::internal::compiler::Verifier::Visitor::CheckSwitch(), v8::internal::wasm::ModuleDecoderImpl::FinalizeRecgroup(), v8::internal::compiler::BytecodeGraphBuilder::GetCallArgumentsFromRegisters(), v8::internal::compiler::BytecodeGraphBuilder::GetConstructArgumentsFromRegister(), v8::internal::compiler::JSNativeContextSpecialization::InferHasInPrototypeChain(), v8::internal::maglev::MaglevGraphBuilder::InferHasInPrototypeChain(), v8::internal::WasmCapiFunction::MatchesSignature(), v8::internal::compiler::turboshaft::operator<<(), v8::internal::compiler::JSONGraphWriter::Print(), v8::internal::compiler::BytecodeGraphBuilder::ProcessCallRuntimeArguments(), v8::internal::compiler::Verifier::Run(), and v8::internal::compiler::EscapeAnalysisReducer::VerifyReplacement().
code
force emit tier up logic from all non turbofan code
Definition at line 546 of file flag-definitions.h.
Referenced by v8::internal::JSFunction::abstract_code(), v8::internal::UseScratchRegisterScope::AcquireSameSizeAs(), v8::internal::UseScratchRegisterScope::AcquireV(), v8::internal::compiler::SpillPlacer::Add(), v8::internal::SetupIsolateDelegate::AddBuiltin(), v8::internal::wasm::FeedbackMaker::AddCallIndirectCandidate(), v8::internal::wasm::NativeModule::AddCodeForTesting(), v8::internal::wasm::NativeModule::AddCodeWithCodeSpace(), v8::internal::wasm::NativeModule::AddCompiledCode(), v8::internal::compiler::turboshaft::CompareSequence::AddConditionalCompare(), v8::internal::anonymous_namespace{intl-objects.cc}::anonymous_namespace{intl-objects.cc}::ResourceAvailableCurrencies::AddIfAvailable(), v8::internal::wasm::WasmEngine::AddPotentiallyDeadCode(), v8::internal::wasm::WasmCodeRefScope::AddRef(), v8::internal::wasm::WasmCodeRefScope::AddRefIfNotDying(), v8::internal::wasm::ValidateFunctionsStreamingJobData::AddUnit(), v8::internal::anonymous_namespace{memory-measurement.cc}::MemoryMeasurementResultBuilder::AddWasm(), v8::internal::wasm::WasmImportWrapperCache::ModificationScope::AddWrapper(), v8::internal::HeapObject::AllocateAndInstallJSDispatchHandle(), v8::internal::CodeStubAssembler::AllocateRootFunctionWithContext(), v8::internal::anonymous_namespace{isolate.cc}::CallSiteBuilder::AppendAsyncFrame(), v8::internal::anonymous_namespace{log.cc}::AppendCodeCreateHeader(), v8::internal::anonymous_namespace{isolate.cc}::CallSiteBuilder::AppendFrame(), v8::internal::anonymous_namespace{isolate.cc}::CallSiteBuilder::AppendPromiseCombinatorFrame(), v8::internal::compiler::JumpThreading::ApplyForwarding(), v8::internal::maglev::MaglevCodeGenerator::Assemble(), v8::internal::RegExpCompiler::Assemble(), v8::internal::compiler::AssembleConditionalCompareChain(), v8::internal::AssertCodeIsBaseline(), v8::internal::ProfilerListener::AttachDeoptInlinedFrames(), v8::internal::Assembler::break_(), v8::internal::MacroAssembler::Brk(), v8::internal::Factory::JSFunctionBuilder::Build(), v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuildAdaptor(), v8::internal::Factory::CodeBuilder::BuildInternal(), v8::internal::compiler::BuildParameterLocations(), v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuildPlaceholder(), v8::internal::Factory::JSFunctionBuilder::BuildRaw(), v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuildWithMacroAssembler(), v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuildWithTurboshaftAssemblerCS(), v8::internal::compiler::turboshaft::BuildWithTurboshaftAssemblerImpl(), v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuildWithTurboshaftAssemblerJS(), v8::internal::BUILTIN(), v8::internal::MacroAssembler::CallBuiltin(), v8::internal::MacroAssembler::CallJSFunction(), v8::internal::wasm::CallThroughDispatchTable(), v8::internal::JSFunction::CanDiscardCompiled(), v8::internal::compiler::CheckNoDeprecatedMaps(), v8::internal::JSFunction::ChecksTieringState(), v8::internal::wasm::DebugInfoImpl::ClearStepping(), v8::internal::anonymous_namespace{code-reference.cc}::CodeOps::code_comments(), v8::internal::anonymous_namespace{code-reference.cc}::CodeOps::code_comments_size(), v8::internal::compiler::MoveOptimizer::code_zone(), v8::internal::Logger::CodeCreateEvent(), v8::internal::ExternalLogEventListener::CodeCreateEvent(), v8::internal::V8FileLogger::CodeCreateEvent(), v8::internal::CodeEventLogger::CodeCreateEvent(), v8::internal::ProfilerListener::CodeCreateEvent(), v8::internal::PerfettoLogger::CodeCreateEvent(), v8::internal::Logger::CodeDeoptEvent(), v8::internal::V8FileLogger::CodeDeoptEvent(), v8::internal::ProfilerListener::CodeDeoptEvent(), v8::internal::Logger::CodeDependencyChangeEvent(), v8::internal::V8FileLogger::CodeDependencyChangeEvent(), v8::internal::Logger::CodeDisableOptEvent(), v8::internal::ProfilerListener::CodeDisableOptEvent(), v8::internal::wasm::WasmInterpreter::CodeMap::CodeMap(), v8::internal::JitLogger::CodeMoveEvent(), v8::internal::PerfettoLogger::CodeMoveEvent(), v8::internal::JavaScriptFrame::CollectFunctionAndOffsetForICStats(), v8::internal::maglev::MaglevCodeGenerator::CollectRetainedMaps(), v8::internal::OptimizedCompilationJob::CollectRetainedMaps(), v8::internal::CPURegList::Combine(), v8::internal::compiler::CompilationDependencies::Commit(), v8::internal::compiler::turboshaft::Pipeline::CommitDependencies(), v8::internal::Compiler::Compile(), v8::internal::RegExpImpl::Compile(), v8::internal::wasm::CompileLazy(), v8::internal::LazyBuiltinsAssembler::CompileLazy(), v8::internal::Compiler::CompileOptimized(), v8_inspector::V8InspectorImpl::compileScript(), v8::internal::Compiler::CompileSharedWithBaseline(), v8::internal::anonymous_namespace{frames.cc}::ComputeBuiltinFrameType(), v8::internal::compiler::JumpThreading::ComputeForwarding(), v8::internal::Deoptimizer::ComputeIncomingArgumentSize(), v8::internal::anonymous_namespace{log.cc}::ComputeMarker(), v8::internal::CallSiteInfo::ComputeSourcePosition(), v8::internal::anonymous_namespace{code-reference.cc}::CodeOps::constant_pool(), v8::internal::wasm::WasmInterpreterRuntime::ContinueExecution(), v8::internal::BasicBlockProfilerData::CopyToJSHeap(), v8::internal::Isolate::CreateAndSetEmbeddedBlob(), v8::internal::compiler::JSOperatorBuilder::CreateClosure(), v8::internal::compiler::JSCallReducer::CreateClosureFromBuiltinSharedFunctionInfo(), v8::internal::compiler::PromiseBuiltinReducerAssembler::CreateClosureFromBuiltinSharedFunctionInfo(), v8::internal::Heap::CreateEarlyReadOnlyMapsAndObjects(), v8::internal::wasm::NativeModule::CreateEmptyJumpTableInRegionLocked(), v8::internal::anonymous_namespace{code-serializer.cc}::CreateInterpreterDataForDeserializedCode(), v8::internal::OffHeapInstructionStream::CreateOffHeapOffHeapInstructionStream(), v8::internal::anonymous_namespace{bootstrapper.cc}::CreateSharedFunctionInfoForBuiltin(), v8::internal::Isolate::CurrentEmbeddedBlobIsBinaryEmbedded(), v8::internal::MacroAssembler::Debug(), v8::internal::wasm::LiftoffAssembler::CacheState::dec_used(), v8::internal::compiler::OperandAssigner::DecideSpillingMode(), v8::internal::wasm::WasmBytecodeGenerator::DecodeAtomicOp(), v8::internal::wasm::WasmBytecodeGenerator::DecodeGCOp(), v8::internal::wasm::WasmBytecodeGenerator::DecodeNumericOp(), v8::internal::wasm::WasmBytecodeGenerator::DecodeSimdOp(), v8::internal::wasm::WasmCode::DecrementRefCount(), v8::internal::anonymous_namespace{runtime-compiler.cc}::DeoptAllOsrLoopsContainingDeoptExit(), v8::internal::Deoptimizer::DeoptimizeAll(), v8::internal::Deoptimizer::DeoptimizeAllOptimizedCodeWithFunction(), v8::internal::anonymous_namespace{deoptimizer.cc}::DeoptimizedMaglevvedCodeEarly(), v8::internal::Deoptimizer::DeoptimizeFunction(), v8::internal::Deoptimizer::DeoptimizeMarkedCode(), v8::internal::Deoptimizer::Deoptimizer(), v8::internal::Assembler::deserialization_set_special_target_at(), v8::internal::ContextDeserializer::DeserializeApiWrapperFields(), v8::internal::Deserializer< IsolateT >::DeserializeDeferredObjects(), v8::internal::ContextDeserializer::DeserializeEmbedderFields(), v8::internal::wasm::DisassembleFunction(), v8::internal::Deoptimizer::DoComputeBuiltinContinuation(), v8::internal::compiler::SimplifiedLowering::DoJSToNumberOrNumericTruncatesToFloat64(), v8::internal::compiler::SimplifiedLowering::DoJSToNumberOrNumericTruncatesToWord32(), v8::internal::Assembler::emit(), v8::internal::Assembler::emit_modrm(), v8::internal::wasm::WasmFunctionBuilder::EmitCode(), v8::internal::wasm::anonymous_namespace{wasm-module-builder.cc}::EmitSection(), v8::internal::anonymous_namespace{embedded-data.cc}::EnsureRelocatable(), v8::internal::wasm::NativeModule::EstimateCurrentMemoryConsumption(), v8::internal::wasm::DebugInfoImpl::EstimateCurrentMemoryConsumption(), v8::internal::ETWJITInterface::EventHandler(), v8::internal::FeedbackVector::EvictOptimizedCodeMarkedForDeoptimization(), v8::internal::NativeRegExpMacroAssembler::Execute(), v8::internal::wasm::WasmCompilationUnit::ExecuteCompilation(), v8::internal::wasm::WasmInterpreterRuntime::ExecuteFunction(), v8::internal::wasm::WasmInterpreterRuntime::ExecuteImportedFunction(), v8::internal::V8HeapExplorer::ExtractCodeReferences(), v8::internal::V8HeapExplorer::ExtractFeedbackVectorReferences(), v8::internal::V8HeapExplorer::ExtractInstructionStreamReferences(), v8::internal::V8HeapExplorer::ExtractSharedFunctionInfoReferences(), v8::internal::V8FileLogger::FeedbackVectorEvent(), v8::internal::wasm::JSToWasmWrapperCompilationUnit::Finalize(), v8::internal::compiler::CodeGenerator::FinalizeCode(), v8::internal::compiler::turboshaft::Pipeline::FinalizeCode(), v8::internal::anonymous_namespace{embedded-data.cc}::FinalizeEmbeddedCodeTargets(), v8::internal::compiler::CodeAssemblerCompilationJob::FinalizeJobImpl(), v8::internal::compiler::PipelineCompilationJob::FinalizeJobImpl(), v8::internal::Compiler::FinalizeMaglevCompilationJob(), v8::internal::MaglevSafepointTable::FindEntry(), v8::internal::SafepointTable::FindEntry(), v8::internal::MaglevFrame::FindReturnPCForTrampoline(), v8::internal::TurbofanJSFrame::FindReturnPCForTrampoline(), v8::internal::compiler::SpillPlacer::FirstBackwardPass(), v8::internal::SourcePosition::FirstInfo(), v8::internal::compiler::SpillPlacer::ForwardPass(), v8::internal::wasm::DebugInfoImpl::FrameInspectionScope::FrameInspectionScope(), v8::internal::wasm::WasmCodeAllocator::FreeCode(), v8::internal::wasm::NativeModule::FreeCode(), v8::internal::wasm::WasmEngine::FreeNativeModule(), v8::internal::OffHeapInstructionStream::FreeOffHeapOffHeapInstructionStream(), v8::internal::wasm::LiftoffRegister::from_code(), v8::internal::wasm::LiftoffRegister::from_external_code(), v8::internal::wasm::LiftoffRegister::from_liftoff_code(), v8::internal::GeneratedCode< Return, Args >::FromCode(), v8::internal::DebugEvaluate::FunctionGetSideEffectState(), v8::internal::Heap::GcSafeTryFindCodeForInnerPointer(), v8::internal::maglev::MaglevCodeGenerator::Generate(), v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_ContinueToBuiltinHelper(), v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_DeoptimizationEntry(), v8::internal::maglev::MaglevCompiler::GenerateCode(), v8::internal::compiler::Pipeline::GenerateCodeForTesting(), v8::internal::wasm::GenerateLiftoffDebugSideTable(), v8::internal::LazyBuiltinsAssembler::GenerateTailCallToJSCode(), v8::internal::LazyBuiltinsAssembler::GenerateTailCallToJSFunction(), v8::internal::LazyBuiltinsAssembler::GenerateTailCallToReturnedCode(), v8::internal::compiler::Pipeline::GenerateTurboshaftCodeForTesting(), v8::internal::anonymous_namespace{compiler.cc}::OptimizedCodeCache::Get(), v8::internal::JavaScriptFrame::GetActiveCodeAndOffset(), v8::internal::JSFunction::GetActiveTier(), v8::internal::JSFunction::GetAttachedCodeKinds(), v8::internal::JSFunction::GetAvailableCodeKinds(), v8::internal::BreakIterator::GetBreakLocation(), v8::internal::BaselineFrame::GetBytecodeOffset(), v8::internal::MaglevFrame::GetBytecodeOffsetForOSR(), v8::internal::RegExpMacroAssemblerRISCV::GetCode(), v8::internal::SharedFunctionInfo::GetCode(), v8::internal::wasm::WasmInterpreter::CodeMap::GetCode(), v8::internal::wasm::NativeModule::GetCode(), v8::internal::maglev::MaglevGraphBuilder::GetConstantSingleCharacterStringFromCode(), v8::internal::StatisticsExtension::GetCounters(), v8::internal::wasm::DebugInfoImpl::GetDebugSideTable(), v8::internal::wasm::DebugInfo::GetDebugSideTableIfExists(), v8::internal::wasm::DebugInfoImpl::GetDebugSideTableIfExists(), v8::internal::anonymous_namespace{deoptimizer.cc}::GetDeoptCallPCFromReturnPC(), v8::internal::OptimizedJSFrame::GetDeoptimizationData(), v8::internal::Deoptimizer::GetDeoptInfo(), v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >::GetDoubleRegisterParameter(), v8::internal::wasm::WasmInterpreter::CodeMap::GetFunctionBytecode(), v8::internal::wasm::NativeModule::GetFunctionIndexFromJumpTableSlot(), v8::internal::OptimizedJSFrame::GetFunctions(), v8::internal::compiler::CodeRef::GetInlinedBytecodeSize(), v8::internal::compiler::anonymous_namespace{register-allocator.cc}::GetInstructionBlock(), v8::internal::FeedbackNexus::GetKeyedAccessStoreMode(), v8::internal::compiler::anonymous_namespace{register-allocator.cc}::GetLastInstruction(), v8::internal::wasm::GetNearestWasmFunction(), v8::internal::FeedbackVector::GetOptimizedOsrCode(), v8::internal::BaselineFrame::GetPCForBytecodeOffset(), v8::internal::WasmScript::GetPossibleBreakpoints(), v8::internal::GetRegisterThatIsNotOneOf(), v8::internal::SourceTextModule::GetSharedFunctionInfo(), v8::internal::SourceTextModule::GetStalledTopLevelAwaitMessages(), v8::internal::anonymous_namespace{frames.cc}::GetStateForFastCCallCallerFP(), v8::internal::wasm::DebugInfoImpl::GetValue(), v8::internal::wasm::GetWasmFunctionOffset(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerCase(), v8::internal::AccessorAssembler::HandleProtoHandler(), v8::internal::Isolate::HashIsolateForEmbeddedBlob(), v8::internal::MacroAssembler::Hint(), v8::internal::MacroAssembler::Hlt(), v8::internal::Isolate::IncreaseTotalRegexpCodeGenerated(), v8::internal::interpreter::Interpreter::Initialize(), v8::internal::Isolate::InitializeBuiltinJSDispatchTable(), v8::internal::Isolate::InitializeDefaultEmbeddedBlob(), v8::internal::SourcePosition::InliningStack(), v8::internal::anonymous_namespace{compiler.cc}::OptimizedCodeCache::Insert(), v8::internal::DependentCode::InsertWeakCode(), v8::internal::baseline::BaselineCompilerTask::Install(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PendingDependencies::InstallAll(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PendingDependencies::InstallAllPredictable(), v8::internal::DependentCode::InstallDependency(), v8::internal::Compiler::InstallInterpreterTrampolineCopy(), v8::internal::anonymous_namespace{code-reference.cc}::CodeOps::instruction_end(), v8::internal::anonymous_namespace{code-reference.cc}::CodeOps::instruction_size(), v8::internal::anonymous_namespace{code-reference.cc}::CodeOps::instruction_start(), v8::internal::JSFunction::instruction_start(), v8::internal::anonymous_namespace{uri.cc}::IntoOneAndTwoByte(), v8::internal::anonymous_namespace{uri.cc}::IntoTwoByte(), v8::internal::anonymous_namespace{execution.cc}::Invoke(), v8::internal::JSFunction::is_compiled(), v8::internal::wasm::DebugInfoImpl::IsAtReturn(), v8::internal::IsBaselineCompiledScope::IsBaselineCompiledScope(), v8::internal::compiler::IsBuiltinCall(), v8::internal::IsCompiledScope::IsCompiledScope(), unibrow::Utf16::IsLeadSurrogate(), v8::internal::CodeStubAssembler::IsMarkedForDeoptimization(), unibrow::Utf16::IsTrailSurrogate(), v8::internal::MarkingVisitorBase< ReferenceSummarizerMarkingVisitor >::IsTrivialWeakReferenceValue(), v8::internal::WasmExportedFunction::IsWasmExportedFunction(), v8::internal::TypedFrame::Iterate(), v8::internal::MaglevFrame::Iterate(), v8::internal::InternalFrame::Iterate(), v8::internal::CommonFrame::IterateTurbofanJSOptimizedFrame(), v8::internal::anonymous_namespace{code-reference.cc}::CodeOps::jump_table_info(), v8::internal::anonymous_namespace{code-reference.cc}::CodeOps::jump_table_info_size(), v8::internal::MacroAssembler::JumpIfCodeIsMarkedForDeoptimization(), v8::internal::MacroAssembler::JumpJSFunction(), v8::internal::CodeStubAssembler::LoadCodeInstructionStart(), v8::internal::CodeStubAssembler::LoadSharedFunctionInfoBytecodeArray(), v8::internal::ProfilerCodeObserver::LogBuiltins(), v8::internal::wasm::WasmEngine::LogCode(), v8::internal::V8FileLogger::LogCodeDisassemble(), v8::internal::V8FileLogger::LogExistingFunction(), v8::internal::ExistingCodeLogger::LogExistingFunction(), v8::internal::wasm::WasmEngine::LogOutstandingCodesForIsolate(), v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::LogPromotedCodePointerTableEntry(), v8::internal::LowLevelLogger::LogRecordedBuffer(), v8::internal::JitLogger::LogRecordedBuffer(), v8::internal::CodeAddressMap::LogRecordedBuffer(), v8::internal::V8FileLogger::LogSourceCodeInformation(), v8::internal::wasm::NativeModule::LogWasmCodes(), v8::internal::wasm::WasmEngine::LogWrapperCode(), v8::internal::wasm::WasmCodeManager::LookupCodeAndSafepoint(), v8::internal::StubFrame::LookupExceptionHandlerInTable(), v8::internal::OptimizedJSFrame::LookupExceptionHandlerInTable(), v8::internal::FactoryBase< Impl >::LookupSingleCharacterStringFromCode(), v8::internal::MaglevSafepointTable::MaglevSafepointTable(), v8::internal::wasm::JSPrototypesSetup::MakeConstructor(), v8::internal::DependentCode::MarkCodeForDeoptimization(), v8::internal::MarkCompactCollector::MarkDependentCodeForDeoptimization(), v8::internal::wasm::NativeModuleSerializer::Measure(), v8::internal::wasm::NativeModuleSerializer::MeasureCode(), v8::internal::JSFunction::NeedsResetDueToFlushedBaselineCode(), v8::internal::JSFunction::NeedsResetDueToFlushedBytecode(), v8::internal::FactoryBase< Impl >::NewCode(), v8::internal::Factory::NewCodeObjectForEmbeddedBuiltin(), v8::internal::FactoryBase< Factory >::NewCodeWrapper(), v8::internal::FactoryBase< Factory >::NewFixedArray(), v8::internal::Factory::NewInterpreterData(), v8::internal::anonymous_namespace{deoptimizer.cc}::DeoptimizableCodeIterator::Next(), v8::internal::JSSegmentIterator::Next(), v8::internal::wasm::LinkageAllocator::NextFpReg(), v8::internal::anonymous_namespace{js-display-names.cc}::LanguageNames::of(), v8::internal::anonymous_namespace{js-display-names.cc}::RegionNames::of(), v8::internal::anonymous_namespace{js-display-names.cc}::ScriptNames::of(), v8::internal::anonymous_namespace{js-display-names.cc}::KeyValueDisplayNames::of(), v8::internal::anonymous_namespace{js-display-names.cc}::CurrencyNames::of(), v8::internal::anonymous_namespace{js-display-names.cc}::CalendarNames::of(), v8::internal::anonymous_namespace{js-display-names.cc}::DateTimeFieldNames::of(), v8::internal::JSDisplayNames::Of(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::OnFinishedUnits(), v8_inspector::V8Debugger::CachedStackFrameKey::Hash::operator()(), v8::internal::compiler::operator<<(), v8::internal::FeedbackVector::optimized_code(), v8::internal::anonymous_namespace{runtime-test.cc}::OptimizeFunctionOnNextCall(), v8::internal::LiveEdit::PatchScript(), v8::internal::wasm::Handlers< Compressed >::pop(), v8::internal::wasm::LiftoffAssembler::PopRegisters(), v8::internal::compiler::ReferenceMapPopulator::PopulateReferenceMaps(), v8::internal::CommonFrame::position(), v8::internal::UnoptimizedJSFrame::position(), v8::internal::Compiler::PostInstantiation(), v8::internal::Deserializer< IsolateT >::PostProcessNewObject(), v8::internal::wasm::WasmEngine::PotentiallyFinishCurrentGC(), v8::internal::anonymous_namespace{isolate.cc}::PredictException(), v8::internal::anonymous_namespace{isolate.cc}::PredictExceptionCatchAtFrame(), v8::internal::EmbeddedFileWriter::PrepareBuiltinSourcePositionMap(), v8::internal::wasm::DebugInfoImpl::PrepareStep(), v8::internal::Debug::PrepareStepOnThrow(), v8::internal::wasm::DebugInfoImpl::PrepareStepOutTo(), v8::internal::wasm::WasmInterpreterRuntime::PrepareTailCall(), v8::internal::wasm::WasmInterpreter::CodeMap::Preprocess(), v8::internal::SourcePosition::Print(), v8::internal::compiler::JSInliningHeuristic::PrintCandidates(), v8::internal::compiler::PrintCode(), v8::internal::JavaScriptFrame::PrintFunctionAndOffset(), v8::internal::wasm::ModuleDisassembler::PrintModule(), v8::internal::JavaScriptFrame::PrintTop(), v8::internal::compiler::PrintTopLevelLiveRanges(), v8::internal::V8FileLogger::ProcessDeoptEvent(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::PublishCode(), v8::internal::wasm::NativeModule::PublishCode(), v8::internal::wasm::NativeModule::PublishCodeLocked(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::PublishCompilationResults(), v8::internal::wasm::Handlers< Compressed >::push(), v8::internal::wasm::LiftoffAssembler::PushRegisters(), v8::internal::compiler::anonymous_namespace{js-native-context-specialization.cc}::PushRegularApiCallInputs(), v8::internal::wasm::WasmExportWrapperCache::Put(), v8::internal::wasm::Handlers< Compressed >::r2r_LoadMemF(), v8::internal::wasm::Handlers< Compressed >::r2r_LoadMemI(), v8::internal::wasm::Handlers< Compressed >::r2r_SelectF(), v8::internal::wasm::Handlers< Compressed >::r2r_SelectI(), v8::internal::wasm::Handlers< Compressed >::r2s_BranchIf(), v8::internal::wasm::Handlers< Compressed >::r2s_BranchIfWithParams(), v8::internal::wasm::Handlers< Compressed >::r2s_BrTable(), v8::internal::wasm::Handlers< Compressed >::r2s_CopyFp0ToSlot32(), v8::internal::wasm::Handlers< Compressed >::r2s_CopyFp0ToSlot64(), v8::internal::wasm::Handlers< Compressed >::r2s_CopyR0ToSlot32(), v8::internal::wasm::Handlers< Compressed >::r2s_CopyR0ToSlot64(), v8::internal::wasm::Handlers< Compressed >::r2s_GlobalSetF(), v8::internal::wasm::Handlers< Compressed >::r2s_GlobalSetI(), v8::internal::wasm::Handlers< Compressed >::r2s_I32ConvertI64(), v8::internal::wasm::Handlers< Compressed >::r2s_If(), v8::internal::wasm::Handlers< Compressed >::r2s_LoadMem(), v8::internal::wasm::Handlers< Compressed >::r2s_LoadStoreMem(), v8::internal::wasm::Handlers< Compressed >::r2s_PreserveCopyFp0ToSlot32(), v8::internal::wasm::Handlers< Compressed >::r2s_PreserveCopyFp0ToSlot64(), v8::internal::wasm::Handlers< Compressed >::r2s_PreserveCopyR0ToSlot32(), v8::internal::wasm::Handlers< Compressed >::r2s_PreserveCopyR0ToSlot64(), v8::internal::wasm::Handlers< Compressed >::r2s_RefSelect(), v8::internal::wasm::Handlers< Compressed >::r2s_Select(), v8::internal::wasm::Handlers< Compressed >::r2s_StoreMemF(), v8::internal::wasm::Handlers< Compressed >::r2s_StoreMemI(), v8::internal::wasm::Handlers< Compressed >::Read(), v8::internal::wasm::value_type_reader::read_heap_type(), v8::internal::wasm::value_type_reader::read_value_type(), v8::internal::Deserializer< IsolateT >::ReadAllocateJSDispatchEntry(), v8::internal::wasm::ReadFnId(), v8::internal::wasm::Handlers< Compressed >::ReadGlobalIndex(), v8::internal::wasm::Handlers< Compressed >::ReadMemoryAddress(), v8::internal::FeedbackVector::RecomputeOptimizedOsrCodeFlags(), v8::internal::TurbofanCompilationJob::RecordFunctionCompilation(), v8::internal::ObjectStatsCollectorImpl::RecordVirtualCodeDetails(), v8::internal::wasm::anonymous_namespace{wasm-interpreter-runtime.cc}::RedirectCodeToUnwindHandler(), v8::internal::compiler::JSInliningHeuristic::Reduce(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateClosure(), v8::internal::wasm::Handlers< Compressed >::RefCast(), v8::internal::wasm::Handlers< Compressed >::RefTest(), v8::internal::Logger::RegExpCodeCreateEvent(), v8::internal::V8FileLogger::RegExpCodeCreateEvent(), v8::internal::CodeEventLogger::RegExpCodeCreateEvent(), v8::internal::ExternalLogEventListener::RegExpCodeCreateEvent(), v8::internal::ProfilerListener::RegExpCodeCreateEvent(), v8::internal::PerfettoLogger::RegExpCodeCreateEvent(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal(), v8::internal::OptimizedCompilationJob::RegisterWeakObjectsInOptimizedCode(), v8::internal::wasm::NativeModule::ReinstallDebugCode(), v8::internal::anonymous_namespace{code-reference.cc}::CodeOps::relocation_end(), v8::internal::anonymous_namespace{code-reference.cc}::CodeOps::relocation_size(), v8::internal::anonymous_namespace{code-reference.cc}::CodeOps::relocation_start(), v8::internal::CPURegList::Remove(), v8::internal::wasm::NativeModule::RemoveCompiledCode(), v8::internal::wasm::DebugInfoImpl::RemoveDebugSideTables(), v8::internal::wasm::DebugInfo::RemoveDebugSideTables(), v8::internal::wasm::WasmEngine::RemoveIsolate(), v8::internal::SetupIsolateDelegate::ReplacePlaceholders(), v8::internal::wasm::WasmEngine::ReportLiveCodeForGC(), v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::ReportLiveCodeFromFrameForGC(), v8::internal::wasm::WasmInterpreterRuntime::RethrowException(), v8::internal::Assembler::rie_d_format(), v8::internal::Assembler::rie_e_format(), v8::internal::Assembler::rie_f_format(), v8::internal::Assembler::ris_format(), v8::internal::Assembler::rrf_format(), v8::internal::Assembler::rrs_format(), v8::internal::Assembler::rs_format(), v8::internal::Assembler::rsi_format(), v8::internal::Assembler::rsl_format(), v8::internal::Assembler::rsy_format(), v8::internal::RUNTIME_FUNCTION(), v8::internal::Assembler::rxe_format(), v8::internal::wasm::Handlers< Compressed >::s2r_GlobalGetF(), v8::internal::wasm::Handlers< Compressed >::s2r_GlobalGetI(), v8::internal::wasm::Handlers< Compressed >::s2r_I32ConvertI64(), v8::internal::wasm::Handlers< Compressed >::s2r_LoadMemF(), v8::internal::wasm::Handlers< Compressed >::s2r_LoadMemI(), v8::internal::wasm::Handlers< Compressed >::s2r_SelectF(), v8::internal::wasm::Handlers< Compressed >::s2r_SelectI(), v8::internal::wasm::Handlers< Compressed >::s2s_AnyConvertExtern(), v8::internal::wasm::Handlers< Compressed >::s2s_ArrayCopy(), v8::internal::wasm::Handlers< Compressed >::s2s_ArrayFill(), v8::internal::wasm::Handlers< Compressed >::s2s_ArrayGet(), v8::internal::wasm::Handlers< Compressed >::s2s_ArrayInitSegment(), v8::internal::wasm::Handlers< Compressed >::s2s_ArrayLen(), v8::internal::wasm::Handlers< Compressed >::s2s_ArrayNew(), v8::internal::wasm::Handlers< Compressed >::s2s_ArrayNewDefault(), v8::internal::wasm::Handlers< Compressed >::s2s_ArrayNewFixed(), v8::internal::wasm::Handlers< Compressed >::s2s_ArrayNewSegment(), v8::internal::wasm::Handlers< Compressed >::s2s_ArraySet(), v8::internal::wasm::Handlers< Compressed >::s2s_AssertNotNullTypecheck(), v8::internal::wasm::Handlers< Compressed >::s2s_AssertNullTypecheck(), v8::internal::wasm::Handlers< Compressed >::s2s_AtomicNotify(), v8::internal::wasm::Handlers< Compressed >::s2s_Branch(), v8::internal::wasm::Handlers< Compressed >::s2s_BranchIf(), v8::internal::wasm::Handlers< Compressed >::s2s_BranchIfWithParams(), v8::internal::wasm::Handlers< Compressed >::s2s_BranchOnCast(), v8::internal::wasm::Handlers< Compressed >::s2s_BranchOnCastFail(), v8::internal::wasm::Handlers< Compressed >::s2s_BranchOnNonNull(), v8::internal::wasm::Handlers< Compressed >::s2s_BranchOnNonNullWithParams(), v8::internal::wasm::Handlers< Compressed >::s2s_BranchOnNull(), v8::internal::wasm::Handlers< Compressed >::s2s_BranchOnNullWithParams(), v8::internal::wasm::Handlers< Compressed >::s2s_BrTable(), v8::internal::wasm::Handlers< Compressed >::s2s_CallFunction(), v8::internal::wasm::Handlers< Compressed >::s2s_CallImportedFunction(), v8::internal::wasm::Handlers< Compressed >::s2s_CallIndirect(), v8::internal::wasm::Handlers< Compressed >::s2s_CallIndirect64(), v8::internal::wasm::Handlers< Compressed >::s2s_CallRef(), v8::internal::wasm::Handlers< Compressed >::s2s_Catch(), v8::internal::wasm::Handlers< Compressed >::s2s_CopySlot128(), v8::internal::wasm::Handlers< Compressed >::s2s_CopySlot32(), v8::internal::wasm::Handlers< Compressed >::s2s_CopySlot32x2(), v8::internal::wasm::Handlers< Compressed >::s2s_CopySlot64(), v8::internal::wasm::Handlers< Compressed >::s2s_CopySlot64x2(), v8::internal::wasm::Handlers< Compressed >::s2s_CopySlot_ll(), v8::internal::wasm::Handlers< Compressed >::s2s_CopySlot_lq(), v8::internal::wasm::Handlers< Compressed >::s2s_CopySlot_ql(), v8::internal::wasm::Handlers< Compressed >::s2s_CopySlot_qq(), v8::internal::wasm::Handlers< Compressed >::s2s_CopySlotMulti(), v8::internal::wasm::Handlers< Compressed >::s2s_CopySlotRef(), v8::internal::wasm::Handlers< Compressed >::s2s_DataDrop(), v8::internal::wasm::Handlers< Compressed >::s2s_DoSimdExtAddPairwise(), v8::internal::wasm::Handlers< Compressed >::s2s_DoSimdExtMul(), v8::internal::wasm::Handlers< Compressed >::s2s_DoSimdLoadExtend(), v8::internal::wasm::Handlers< Compressed >::s2s_DoSimdLoadLane(), v8::internal::wasm::Handlers< Compressed >::s2s_DoSimdLoadSplat(), v8::internal::wasm::Handlers< Compressed >::s2s_DoSimdLoadZeroExtend(), v8::internal::wasm::Handlers< Compressed >::s2s_DoSimdStoreLane(), v8::internal::wasm::Handlers< Compressed >::s2s_Drop(), v8::internal::wasm::Handlers< Compressed >::s2s_ElemDrop(), v8::internal::wasm::Handlers< Compressed >::s2s_Else(), v8::internal::wasm::Handlers< Compressed >::s2s_ExternConvertAny(), v8::internal::wasm::Handlers< Compressed >::s2s_GlobalGet(), v8::internal::wasm::Handlers< Compressed >::s2s_GlobalSet(), v8::internal::wasm::Handlers< Compressed >::s2s_I31GetS(), v8::internal::wasm::Handlers< Compressed >::s2s_I31GetU(), v8::internal::wasm::Handlers< Compressed >::s2s_I32AtomicWait(), v8::internal::wasm::Handlers< Compressed >::s2s_I32ConvertI64(), v8::internal::wasm::Handlers< Compressed >::s2s_I64AtomicWait(), v8::internal::wasm::Handlers< Compressed >::s2s_If(), v8::internal::wasm::Handlers< Compressed >::s2s_LoadMem(), v8::internal::wasm::Handlers< Compressed >::s2s_LoadMem_LocalSet(), v8::internal::wasm::Handlers< Compressed >::s2s_LoadStoreMem(), v8::internal::wasm::Handlers< Compressed >::s2s_Memory64Copy(), v8::internal::wasm::Handlers< Compressed >::s2s_Memory64Fill(), v8::internal::wasm::Handlers< Compressed >::s2s_Memory64Grow(), v8::internal::wasm::Handlers< Compressed >::s2s_Memory64Init(), v8::internal::wasm::Handlers< Compressed >::s2s_Memory64Size(), v8::internal::wasm::Handlers< Compressed >::s2s_MemoryCopy(), v8::internal::wasm::Handlers< Compressed >::s2s_MemoryFill(), v8::internal::wasm::Handlers< Compressed >::s2s_MemoryGrow(), v8::internal::wasm::Handlers< Compressed >::s2s_MemoryInit(), v8::internal::wasm::Handlers< Compressed >::s2s_MemorySize(), v8::internal::wasm::Handlers< Compressed >::s2s_OnLoopBegin(), v8::internal::wasm::Handlers< Compressed >::s2s_OnLoopBeginNoRefSlots(), v8::internal::wasm::Handlers< Compressed >::s2s_PreserveCopySlot128(), v8::internal::wasm::Handlers< Compressed >::s2s_PreserveCopySlot32(), v8::internal::wasm::Handlers< Compressed >::s2s_PreserveCopySlot64(), v8::internal::wasm::Handlers< Compressed >::s2s_RefArrayFill(), v8::internal::wasm::Handlers< Compressed >::s2s_RefArrayGet(), v8::internal::wasm::Handlers< Compressed >::s2s_RefArrayNew(), v8::internal::wasm::Handlers< Compressed >::s2s_RefArraySet(), v8::internal::wasm::Handlers< Compressed >::s2s_RefAsNonNull(), v8::internal::wasm::Handlers< Compressed >::s2s_RefDrop(), v8::internal::wasm::Handlers< Compressed >::s2s_RefEq(), v8::internal::wasm::Handlers< Compressed >::s2s_RefFunc(), v8::internal::wasm::Handlers< Compressed >::s2s_RefGlobalGet(), v8::internal::wasm::Handlers< Compressed >::s2s_RefGlobalSet(), v8::internal::wasm::Handlers< Compressed >::s2s_RefI31(), v8::internal::wasm::Handlers< Compressed >::s2s_RefIsNonNull(), v8::internal::wasm::Handlers< Compressed >::s2s_RefIsNull(), v8::internal::wasm::Handlers< Compressed >::s2s_RefNull(), v8::internal::wasm::Handlers< Compressed >::s2s_RefSelect(), v8::internal::wasm::Handlers< Compressed >::s2s_RefStructGet(), v8::internal::wasm::Handlers< Compressed >::s2s_RefStructSet(), v8::internal::wasm::Handlers< Compressed >::s2s_RefTestFails(), v8::internal::wasm::Handlers< Compressed >::s2s_RefTestSucceeds(), v8::internal::wasm::Handlers< Compressed >::s2s_Rethrow(), v8::internal::wasm::Handlers< Compressed >::s2s_Return(), v8::internal::wasm::Handlers< Compressed >::s2s_ReturnCall(), v8::internal::wasm::Handlers< Compressed >::s2s_ReturnCallImportedFunction(), v8::internal::wasm::Handlers< Compressed >::s2s_ReturnCallIndirect(), v8::internal::wasm::Handlers< Compressed >::s2s_ReturnCallIndirect64(), v8::internal::wasm::Handlers< Compressed >::s2s_ReturnCallRef(), v8::internal::wasm::Handlers< Compressed >::s2s_Select(), v8::internal::wasm::Handlers< Compressed >::s2s_SimdI16x8DotI8x16I7x16S(), v8::internal::wasm::Handlers< Compressed >::s2s_SimdI32x4DotI16x8S(), v8::internal::wasm::Handlers< Compressed >::s2s_SimdI32x4DotI8x16I7x16AddS(), v8::internal::wasm::Handlers< Compressed >::s2s_SimdI8x16Shuffle(), v8::internal::wasm::Handlers< Compressed >::s2s_SimdI8x16Swizzle(), v8::internal::wasm::Handlers< Compressed >::s2s_SimdS128StoreMemI(), v8::internal::wasm::Handlers< Compressed >::s2s_SimdV128AnyTrue(), v8::internal::wasm::Handlers< Compressed >::s2s_StoreMem(), v8::internal::wasm::Handlers< Compressed >::s2s_StructGet(), v8::internal::wasm::Handlers< Compressed >::s2s_StructNew(), v8::internal::wasm::Handlers< Compressed >::s2s_StructNewDefault(), v8::internal::wasm::Handlers< Compressed >::s2s_StructSet(), v8::internal::wasm::Handlers< Compressed >::s2s_Table64CopyImpl(), v8::internal::wasm::Handlers< Compressed >::s2s_Table64Fill(), v8::internal::wasm::Handlers< Compressed >::s2s_Table64Get(), v8::internal::wasm::Handlers< Compressed >::s2s_Table64Grow(), v8::internal::wasm::Handlers< Compressed >::s2s_Table64Init(), v8::internal::wasm::Handlers< Compressed >::s2s_Table64Set(), v8::internal::wasm::Handlers< Compressed >::s2s_Table64Size(), v8::internal::wasm::Handlers< Compressed >::s2s_TableCopy(), v8::internal::wasm::Handlers< Compressed >::s2s_TableFill(), v8::internal::wasm::Handlers< Compressed >::s2s_TableGet(), v8::internal::wasm::Handlers< Compressed >::s2s_TableGrow(), v8::internal::wasm::Handlers< Compressed >::s2s_TableInit(), v8::internal::wasm::Handlers< Compressed >::s2s_TableSet(), v8::internal::wasm::Handlers< Compressed >::s2s_TableSize(), v8::internal::wasm::Handlers< Compressed >::s2s_Throw(), v8::internal::wasm::HandlersBase::s2s_Unreachable(), v8::internal::Assembler::s_format(), v8::internal::compiler::ReferenceMapPopulator::SafePointsAreInOrder(), v8::internal::SafepointTable::SafepointTable(), v8::internal::compiler::SpillPlacer::SecondBackwardPass(), v8::internal::wasm::SectionName(), v8::internal::Serializer::SerializeObject(), v8::internal::StubCache::Set(), v8::internal::maglev::MaglevCompilationInfo::set_code(), v8::internal::compiler::turboshaft::PipelineData::set_code(), v8::internal::CallSiteInfo::set_code_object(), v8::internal::EhFrameWriter::SetBaseAddressRegister(), v8::internal::EhFrameWriter::SetBaseAddressRegisterAndOffset(), v8::internal::Isolate::SetEmbeddedBlob(), v8::internal::Code::SetInstructionStreamAndInstructionStart(), v8::internal::FeedbackVector::SetOptimizedCode(), v8::internal::FeedbackVector::SetOptimizedOsrCode(), v8::internal::anonymous_namespace{isolate.cc}::SetStickyEmbeddedBlob(), v8::internal::wasm::WasmInterpreterRuntime::SetTrap(), v8::internal::SetupIsolateDelegate::SetupBuiltinsInternal(), v8::internal::MarkingVisitorBase< ConcreteVisitor >::ShouldFlushBaselineCode(), v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::ShouldRemoveCode(), v8::internal::Assembler::si_format(), v8::internal::Assembler::sil_format(), v8::internal::ReadOnlyRoots::single_character_string(), v8::internal::Assembler::siy_format(), v8::internal::wasm::NativeModule::SnapshotCodeTable(), v8::internal::Assembler::ss_a_format(), v8::internal::Assembler::stop(), v8::internal::compiler::anonymous_namespace{basic-block-instrumentor.cc}::StoreBuiltinCallForNode(), v8::internal::KeyedStoreIC::StoreElementHandler(), v8::internal::StoreHandler::StoreElementTransition(), v8::internal::AccessorAssembler::StoreInArrayLiteralIC(), v8::internal::CodeStubAssembler::StringFromSingleCharCode(), v8::internal::compiler::JSGraphAssembler::StringFromSingleCharCode(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::StringFromSingleCharCode(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::StringFromSingleCodePoint(), v8::internal::CodeStubAssembler::StringFromSingleOneByteCharCode(), v8::internal::anonymous_namespace{js-display-names.cc}::StringToUDateTimePatternField(), v8::internal::wasm::NativeModule::SumLiftoffCodeSizeForTesting(), v8::internal::CommonFrameWithJSLinkage::Summarize(), v8::internal::BuiltinExitFrame::Summarize(), v8::internal::ApiCallbackExitFrame::Summarize(), v8::internal::StubFrame::Summarize(), v8::internal::OptimizedJSFrame::Summarize(), v8::internal::V8HeapExplorer::TagBuiltinCodeObject(), v8::internal::ArrayBuiltinsAssembler::TailCallArrayConstructorStub(), v8::internal::MacroAssembler::TailCallBuiltin(), v8::internal::compiler::CodeAssembler::TailCallJSCode(), v8::internal::compiler::OperandGenerator::TempRegister(), v8::internal::TF_BUILTIN(), v8::internal::wasm::WasmInterpreterRuntime::ThrowException(), v8::internal::wasm::ThrowLazyCompilationError(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::TierUpAllFunctions(), v8::internal::IC::TraceIC(), v8::internal::Deoptimizer::TraceMarkForDeoptimization(), v8::internal::WeakCodeRegistry::Track(), v8::internal::wasm::NativeModule::TransferNewOwnedCodeLocked(), v8::internal::TranslatedState::TranslatedState(), v8::internal::anonymous_namespace{liveedit.cc}::TranslateSourcePositionTable(), v8::internal::wasm::HandlersBase::Trap(), v8::internal::wasm::WasmEngine::TriggerGC(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::TryEmitLoadForLoadWord64AndShiftRight(), v8::internal::compiler::turboshaft::TryGetBuiltinId(), v8::internal::compiler::OneOrTwoByteAnalysis::TryGetRange(), v8::internal::CommonFrameWithJSLinkage::unchecked_code(), v8::internal::Isolate::UnwindAndFindHandler(), v8::internal::JSFunction::UpdateCode(), v8::internal::UpdateTypedSlotHelper::UpdateCodeEntry(), v8::internal::JSFunction::UpdateCodeKeepTieringRequests(), v8::internal::JSFunction::UpdateOptimizedCode(), v8::internal::anonymous_namespace{mark-compact.cc}::UpdateStrongCodeSlot(), v8::internal::wasm::WasmCode::Validate(), v8::internal::wasm::anonymous_namespace{module-decoder.cc}::ValidateFunctionsTask::ValidateFunction(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ValidateSingleFunction(), v8::internal::compiler::turboshaft::Pipeline::VerifyGeneratedCodeIsIdempotent(), v8::internal::compiler::VisitAtomicBinaryOperation(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicBinop(), v8::internal::compiler::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitAtomicBinOp(), v8::internal::compiler::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitAtomicCompareExchange(), v8::internal::compiler::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitAtomicStore(), v8::internal::IndexedReferencesExtractor::VisitEmbeddedPointer(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitFloatBinop(), v8::internal::compiler::VisitGeneralStore(), v8::internal::RecordMigratedSlotVisitor::VisitInstructionStreamPointer(), v8::internal::Serializer::ObjectSerializer::VisitJSDispatchTableEntry(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitPairAtomicBinOp(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitPairAtomicBinOp(), v8::internal::compiler::VisitPairAtomicBinop(), v8::internal::RootMarkingVisitor::VisitRunningCode(), v8::internal::RootsReferencesExtractor::VisitRunningCode(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitStoreCommon(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitStoreCommon(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitStoreCommon(), v8::internal::compiler::VisitStoreCommon(), v8::internal::anonymous_namespace{debug.cc}::DiscardBaselineCodeVisitor::VisitThread(), v8::internal::anonymous_namespace{deoptimizer.cc}::ActivationsFinder::VisitThread(), v8::internal::compiler::InstructionSelector::VisitWord32AtomicBinaryOperation(), v8::internal::wasm::WasmInterpreterRuntime::WasmStackCheck(), v8::internal::anonymous_namespace{builtins-riscv.cc}::RegisterAllocator::WithAllocatableGeneralRegisters(), v8::internal::wasm::NativeModuleSerializer::Write(), v8::internal::wasm::NativeModuleSerializer::WriteCode(), v8::internal::anonymous_namespace{perfetto-logger.cc}::WriteJsCode(), and v8::internal::wasm::WasmEngine::~WasmEngine().
DEBUG_BOOL
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data DEBUG_BOOL
Definition at line 1478 of file flag-definitions.h.
Referenced by v8::internal::compiler::anonymous_namespace{access-info.cc}::AccessorAccessInfoHelper(), v8::internal::TaggedArrayBase< Derived, ShapeT, Super >::Allocate(), v8::internal::PrimitiveArrayBase< Derived, ShapeT, Super >::Allocate(), v8::internal::torque::BuildFlags::BuildFlags(), v8::internal::ComputeFlagListHash(), v8::internal::anonymous_namespace{runtime-literals.cc}::CreateArrayLiteral(), v8::internal::JSSynchronizationPrimitive::DestructivelyGetWaiterQueueHead(), v8::internal::SharedFunctionInfo::DisableOptimization(), v8::internal::DoubleToStringView(), v8::internal::LazyCompileDispatcher::FinishNow(), v8::internal::PropertyCallbackArguments::GetBooleanReturnValue(), v8::internal::Isolate::GetIncumbentContextSlow(), v8::internal::Isolate::Init(), v8::internal::anonymous_namespace{api.cc}::InvokeFunctionCallback(), v8::internal::wasm::StackMemory::JSStackLimitMarginKB(), v8::internal::CommonFrameWithJSLinkage::LookupExceptionHandlerInTable(), v8::internal::NeedsBoundsCheck(), v8::internal::EmbeddedData::NewFromIsolate(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationChecker::PrintDebugHelp(), v8::internal::PropertyCallbackArguments::PropertyCallbackArguments(), v8::internal::Sweeper::RawSweep(), v8::internal::MicrotaskQueueBuiltinsAssembler::RewindEnteredContext(), v8::internal::compiler::turboshaft::CodeEliminationAndSimplificationPhase::Run(), v8::internal::compiler::turboshaft::WasmDeadCodeEliminationPhase::Run(), v8::internal::compiler::turboshaft::WasmInJSInliningPhase::Run(), v8::internal::JSSynchronizationPrimitive::SetWaiterQueueHead(), and v8::internal::anonymous_namespace{frames.cc}::VisitSpillSlot().
DebugPrint
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s DebugPrint
Definition at line 1558 of file flag-definitions.h.
Referenced by v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DebugPrint().
false
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and reclaim otherwise unreachable unmodified wrapper objects when possible discard the memory pool before invoking the GC on memory pressure or last resort GCs Delay before memory reducer start virtual randomize memory reservations by ignoring any hints passed when allocating pages use incremental marking for CppHeap cppheap_concurrent_marking c value for membalancer A special constant to balance between memory and space tradeoff The smaller the more memory it uses enable use of SSE4 instructions if available enable use of SAHF instruction if enable use of AVX VNNI instructions if available enable use of POPCNT instruction if available force all emitted branches to be in long enable use of partial constant enable optional features on the simulator for enable mitigation for Intel JCC erratum on affected CPUs enable unaligned accesses for the regexp engine enable deserializing code caches on background enable type checks based on instance types provided by the embedder expose externalize string extension show built in functions in stack traces disallow eval and friends Notify Api callback about exceptions thrown in Api callbacks false
Definition at line 238 of file flag-definitions.h.
Referenced by v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildWasmToJSWrapper(), v8::internal::ChoiceNode::Emit(), v8::internal::IsInString(), and v8::internal::V8HeapExplorer::IterateAndExtractReferences().
https
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to https
Definition at line 1511 of file flag-definitions.h.
KB
refactor address components for immediate indexing make OptimizeMaglevOnNextCall optimize to turbofan instead of maglev filter for tracing turbofan compilation trace turbo cfg trace TurboFan s graph trimmer trace TurboFan s control equivalence trace TurboFan s register allocator trace stack load store counters for optimized code in run fuzzing&& concurrent_recompilation trace_turbo trace_turbo_scheduled trace_turbo_stack_accesses verify TurboFan machine graph of code stubs path where to generate builtins effects enable FixedArray bounds checks print TurboFan statistics of wasm compilations maximum cumulative size of bytecode considered for inlining maximum size of small functions bytecode that can be inlining maximum size of bytecode considered for small function inlining * KB
Definition at line 1400 of file flag-definitions.h.
Referenced by v8::base::OS::GetPeakMemoryUsageKb(), and v8::internal::RUNTIME_FUNCTION().
marking
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress marking
Definition at line 2248 of file flag-definitions.h.
Referenced by v8::internal::GCTracer::StartCycle().
max_inlined_bytecode_size_absolute
too high values may cause the compiler to set high thresholds for inlining to as much as possible max_inlined_bytecode_size_absolute
Definition at line 1410 of file flag-definitions.h.
MB
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage * MB
Definition at line 2282 of file flag-definitions.h.
Referenced by v8::anonymous_namespace{d8.cc}::MockArrayBufferAllocator::Adjust(), v8::internal::FuzzilliExtension::Fuzzilli(), v8::internal::PageEvacuationJob::GetMaxConcurrency(), v8::anonymous_namespace{d8.cc}::GetThreadOptions(), main(), and v8::Shell::SetOptions().
mksnapshot
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for mksnapshot
Definition at line 1473 of file flag-definitions.h.
name
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in name
Definition at line 2171 of file flag-definitions.h.
Referenced by v8_inspector::V8Console::CommandLineAPIScope::accessorGetterCallback(), v8_inspector::V8Console::CommandLineAPIScope::accessorSetterCallback(), v8_inspector::V8RuntimeAgentImpl::addBinding(), v8::anonymous_namespace{api.cc}::AddPropertiesAndElementsToObject(), v8_inspector::V8InspectorSessionImpl::agentState(), v8::tracing::TracedValue::BeginArray(), v8::tracing::TracedValue::BeginDictionary(), v8::Counter::Bind(), v8_inspector::V8RuntimeAgentImpl::bindingCallback(), v8_inspector::V8RuntimeAgentImpl::bindingCalled(), v8_inspector::anonymous_namespace{value-mirror.cc}::ObjectMirror::buildObjectPreviewInternal(), v8_inspector::anonymous_namespace{value-mirror.cc}::PrimitiveValueMirror::buildPropertyPreview(), v8_inspector::anonymous_namespace{value-mirror.cc}::NumberMirror::buildPropertyPreview(), v8_inspector::anonymous_namespace{value-mirror.cc}::FunctionMirror::buildPropertyPreview(), v8_inspector::anonymous_namespace{value-mirror.cc}::ObjectMirror::buildPropertyPreview(), v8_inspector::anonymous_namespace{value-mirror.cc}::BigIntMirror::buildPropertyPreview(), v8_inspector::anonymous_namespace{value-mirror.cc}::SymbolMirror::buildPropertyPreview(), v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::buildScopes(), v8::internal::CodeStubAssembler::CheckForAssociatedProtector(), v8::internal::torque::AggregateType::CheckForDuplicateFields(), v8_inspector::V8Console::CommandLineAPIScope::CommandLineAPIScope(), v8::HeapProfiler::CopyNameForHeapSnapshot(), v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::coverageToProtocol(), v8::base::OS::MemoryMappedFile::create(), v8_inspector::anonymous_namespace{v8-console.cc}::createBoundFunctionProperty(), v8::Shell::CreateEvaluationContext(), v8::Shell::CreateHistogram(), v8_inspector::anonymous_namespace{value-mirror.cc}::createNativeGetter(), v8_inspector::anonymous_namespace{value-mirror.cc}::createNativeSetter(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForError(), v8_inspector::anonymous_namespace{value-mirror.cc}::doesAttributeHaveObservableSideEffectOnGet(), v8::Shell::ExecuteString(), wasm::ExportsImpl(), v8_inspector::anonymous_namespace{search-util.cc}::findMagicComment(), v8::Symbol::For(), v8::Symbol::ForApi(), v8::Private::ForApi(), v8::debug::anonymous_namespace{debug-interface.cc}::ForEachContextLocal(), v8::debug::GetBuiltin(), v8::internal::torque::UnionType::GetConstexprGeneratedTypeName(), v8::Object::GetConstructorName(), v8::Shell::GetCounter(), v8::internal::JSReceiver::GetDataProperty(), v8::Function::GetDebugName(), v8_inspector::anonymous_namespace{value-mirror.cc}::getErrorProperty(), v8::StackFrame::GetFunctionName(), v8::CpuProfileNode::GetFunctionName(), v8::internal::torque::UnionType::GetGeneratedTNodeTypeNameImpl(), v8::internal::CodeStubAssembler::GetInterestingProperty(), v8_inspector::ValueMirror::getInternalProperties(), v8::internal::CodeStubAssembler::GetMethod(), v8::Function::GetName(), v8::HeapGraphNode::GetName(), v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc}::GlobalObjectNameResolver::GetName(), cppgc::internal::NameTraitBase::GetNameFromTypeSignature(), wasm::anonymous_namespace{c-api.cc}::GetNameFromWireBytes(), v8::internal::JSReceiver::GetOwnPropertyAttributes(), v8::debug::GetPrivateMembers(), v8_inspector::ValueMirror::getPrivateProperties(), v8_inspector::ValueMirror::getProperties(), v8::internal::JSReceiver::GetProperty(), v8::internal::JSReceiver::GetPropertyAttributes(), v8::UnboundScript::GetScriptName(), v8::StackFrame::GetScriptName(), v8_inspector::V8DebuggerScript::GetScriptName(), v8::internal::anonymous_namespace{wasm-js.cc}::GetterName(), v8::anonymous_namespace{d8.cc}::GetThreadOptions(), v8::internal::torque::AbstractType::GetTypeCheckers(), v8::Object::Has(), v8::internal::torque::AggregateType::HasField(), v8::internal::JSReceiver::HasProperty(), v8::internal::CodeStubAssembler::HasProperty(), cppgc::internal::anonymous_namespace{heap-statistics-collector.cc}::InitializeSpace(), v8::internal::anonymous_namespace{wasm-js.cc}::InstallFunc(), v8::internal::anonymous_namespace{wasm-js.cc}::InstallGetter(), v8::internal::anonymous_namespace{wasm-js.cc}::InstallGetterSetter(), v8::internal::WasmJs::InstallModule(), v8_inspector::isCommandLineAPIGetter(), v8::internal::CodeStubAssembler::IsInterestingProperty(), v8::internal::TimerEventScope< TimerEvent >::LogTimerEvent(), v8::Shell::LookupCounter(), v8::internal::torque::BitFieldStructType::LookupField(), v8::internal::torque::AggregateType::LookupField(), v8::internal::torque::AggregateType::LookupFieldInternal(), v8::anonymous_namespace{api.cc}::MakeAccessorInfo(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeBasicTypeExpression(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeBitFieldDeclaration(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeBitFieldStructDeclaration(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeClassField(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeEnumDeclaration(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeEnumEntry(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeExternalBuiltin(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeExternalRuntime(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeGenericParameter(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeIdentifier(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeIdentifierExpression(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeLabelAndTypes(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeNameAndExpression(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeNameAndType(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeNamespaceDeclaration(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeSpecializationDeclaration(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeStructDeclaration(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeStructField(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeTypeswitchCase(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeTypeswitchStatement(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeVarDeclarationStatement(), v8::Shell::MapCounters(), anonymous_namespace{mksnapshot.cc}::MaybeSetCounterFunction(), v8_inspector::V8Console::monitorFunctionCallback(), v8_inspector::anonymous_namespace{value-mirror.cc}::nativeGetterCallback(), v8_inspector::anonymous_namespace{value-mirror.cc}::nativeSetterCallback(), v8::Symbol::New(), v8::Private::New(), v8::ObjectSetAccessor(), v8_inspector::objectToProtocolValue(), v8::base::OS::MemoryMappedFile::open(), v8::Shell::PerformanceMark(), v8::Shell::PerformanceMeasure(), v8_inspector::V8Debugger::privateMethods(), v8::Shell::ReadChars(), v8::Shell::ReadCharsFromTcpPort(), v8::Shell::ReadFile(), v8::Shell::ReadFileData(), v8::Shell::ReadLines(), v8::internal::Deserializer< IsolateT >::ReadRepeatedRoot(), v8::internal::Deserializer< IsolateT >::ReadRootArray(), v8::internal::Deserializer< IsolateT >::ReadRootArrayConstants(), v8::base::RelativePath(), v8_inspector::V8RuntimeAgentImpl::removeBinding(), cppgc::internal::MarkingVerifierBase::ReportHeapObjectHeader(), v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::resourceNameToUrl(), v8::Shell::RunShell(), v8::Template::Set(), v8::Object::SetAccessorProperty(), v8::Template::SetAccessorProperty(), v8::tracing::TracedValue::SetBoolean(), v8::FunctionTemplate::SetClassName(), v8::tracing::TracedValue::SetDouble(), v8::tracing::TracedValue::SetInteger(), v8::FunctionTemplate::SetInterfaceName(), v8::Template::SetIntrinsicDataProperty(), v8::Object::SetLazyDataProperty(), v8::Template::SetLazyDataProperty(), v8::Function::SetName(), v8::Object::SetNativeDataProperty(), v8::Template::SetNativeDataProperty(), v8::Template::SetPrivate(), v8::tracing::TracedValue::SetString(), v8::internal::anonymous_namespace{wasm-js.cc}::SetterName(), v8::base::SetThreadName(), v8::tracing::TracedValue::SetUnsignedInteger(), v8::internal::anonymous_namespace{wasm-js.cc}::SetupConstructor(), v8::tracing::TracedValue::SetValue(), v8::TryCatch::StackTrace(), v8::Shell::Stringify(), v8::anonymous_namespace{api.cc}::TemplateSetAccessor(), v8_inspector::InjectedScript::ProtocolPromiseHandler::thenCallback(), v8::internal::torque::BitFieldStructType::ToExplicitString(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::ToString(), wasm_exporttype_new(), wasm_importtype_new(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyModuleCustomSectionsImpl(), v8_inspector::InjectedScript::wrapTable(), v8::Shell::WriteChars(), v8::Shell::WriteLcovData(), v8::anonymous_namespace{d8.cc}::WriteLcovDataForNamedRange(), v8::tracing::TracedValue::WriteName(), and v8_inspector::V8Console::CommandLineAPIScope::~CommandLineAPIScope().
none
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and reclaim otherwise unreachable unmodified wrapper objects when possible discard the memory pool before invoking the GC on memory pressure or last resort GCs Delay before memory reducer start virtual randomize memory reservations by ignoring any hints passed when allocating pages use incremental marking for CppHeap cppheap_concurrent_marking c value for membalancer A special constant to balance between memory and space tradeoff The smaller the more memory it uses enable use of SSE4 instructions if available enable use of SAHF instruction if enable use of AVX VNNI instructions if available enable use of POPCNT instruction if available force all emitted branches to be in long enable use of partial constant none
Definition at line 2526 of file flag-definitions.h.
Referenced by v8::internal::compiler::JSNativeContextSpecialization::InferHasInPrototypeChain(), v8::internal::maglev::MaglevGraphBuilder::InferHasInPrototypeChain(), v8::internal::anonymous_namespace{js-number-format.cc}::IsWellFormedUnitIdentifier(), and v8::internal::JSNumberFormat::New().
nullptr
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination nullptr
Definition at line 1280 of file flag-definitions.h.
Referenced by v8_inspector::V8RuntimeAgentImpl::addBindings(), v8::internal::compiler::LinearScanAllocator::AllocateRegisters(), v8::internal::ClassScope::brand(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::BuildSimpleOperator(), v8::internal::compiler::SpecialRPONumberer::ComputeAndInsertSpecialRPO(), v8::internal::ScopeInfo::Create(), v8_inspector::V8Debugger::currentAsyncParent(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeSimdOpcode(), v8::internal::wasm::TurboshaftGraphBuildingInterface::DoReturn(), v8::base::RegionAllocator::FreeListFindRegion(), v8::internal::compiler::TopLevelLiveRange::GetChildCovers(), v8::internal::wasm::DebugInfoImpl::GetDebugSideTableIfExists(), v8_inspector::InspectedContext::getInjectedScript(), v8::internal::AllocationProfile::GetRootNode(), v8::internal::TickSample::GetStackSample(), v8::internal::WasmTableObject::JSToWasmElement(), v8::internal::compiler::LiveRange::NextRegisterPosition(), v8::internal::compiler::LiveRange::NextUsePositionRegisterIsBeneficial(), v8::internal::compiler::LiveRange::NextUsePositionSpillDetrimental(), v8_inspector::V8InspectorImpl::sessionById(), v8::internal::wasm::TurboshaftGraphBuildingInterface::SetupControlFlowEdge(), v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::SolveInstanceTypeConstraints(), cppgc::subtle::TaggedUncompressedMember< Pointee, Tag1, Tag2 >::TryGetAs(), v8::internal::ProfileDataFromFile::TryRead(), and v8::internal::wasm::WasmModuleBuilder::WriteTo().
optimization
refactor address components for immediate indexing make OptimizeMaglevOnNextCall optimize to turbofan instead of maglev filter for tracing turbofan compilation trace turbo cfg trace TurboFan s graph trimmer trace TurboFan s control equivalence trace TurboFan s register allocator trace stack load store counters for optimized code in run fuzzing&& concurrent_recompilation trace_turbo trace_turbo_scheduled trace_turbo_stack_accesses verify TurboFan machine graph of code stubs path where to generate builtins effects enable FixedArray bounds checks print TurboFan statistics of wasm compilations maximum cumulative size of bytecode considered for inlining maximum size of small functions bytecode that can be inlining maximum size of bytecode considered for small function inlining maximum bytecode size to be considered for turbofan optimization
Definition at line 1402 of file flag-definitions.h.
Referenced by v8::internal::compiler::anonymous_namespace{access-info.cc}::AccessorAccessInfoHelper().
Scavenger
use conservative stack scanning use direct handles with conservative stack scanning Treat some precise references as conservative references to stress test object pinning in Scavenger minor_gc_task Enables random stressing of object pinning in Scavenger
Definition at line 500 of file flag-definitions.h.
Referenced by v8::internal::GCTracer::RecordGCPhasesInfo::RecordGCPhasesInfo().
space
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available space
Definition at line 2215 of file flag-definitions.h.
Referenced by v8::internal::anonymous_namespace{marking-barrier.cc}::ActivateSpace(), v8::internal::Sweeper::AddPage(), v8::internal::Sweeper::AddPageImpl(), cppgc::internal::anonymous_namespace{object-allocator.cc}::AddToFreeList(), v8::internal::MemoryChunkLayout::AllocatableMemoryInMemoryChunk(), v8::internal::EvacuationAllocator::Allocate(), v8::internal::MemoryAllocator::AllocateAlignedMemory(), v8::internal::HeapObject::AllocateAndInstallJSDispatchHandle(), v8::internal::ExternalEntityTable< Entry, size >::AllocateEntry(), v8::internal::ExternalEntityTable< Entry, size >::AllocateEntryBelow(), v8::internal::MemoryAllocator::AllocateLargePage(), cppgc::internal::ObjectAllocator::AllocateObjectOnSpace(), v8::internal::MemoryAllocator::AllocatePage(), v8::internal::MemoryAllocator::AllocateReadOnlyPage(), v8::internal::MemoryAllocator::AllocateUninitializedChunk(), v8::internal::MemoryAllocator::AllocateUninitializedChunkAt(), v8::internal::MemoryAllocator::AllocateUninitializedPageFromPool(), v8::internal::CodeEventLogger::NameBuffer::AppendHex(), v8::internal::CodeEventLogger::NameBuffer::AppendInt(), v8::internal::ExternalEntityTable< Entry, size >::AttachSpaceToReadOnlySegments(), v8::internal::CodeStatistics::CollectCodeStatistics(), v8::internal::MarkCompactCollector::CollectEvacuationCandidates(), v8::internal::anonymous_namespace{mark-compact.cc}::CollectRememberedSetUpdatingItems(), cppgc::internal::Compactor::Compactor(), cppgc::internal::anonymous_namespace{compactor.cc}::CompactSpace(), cppgc::internal::Compactor::CompactSpacesIfEnabled(), v8::internal::MemoryAllocator::ComputeChunkSize(), v8::internal::PagedSpaceBase::ConcurrentAllocationMutex::ConcurrentAllocationMutex(), v8::internal::Serializer::CountAllocation(), v8::internal::CountTotalHolesSize(), v8::internal::anonymous_namespace{marking-barrier.cc}::DeactivateSpace(), v8::internal::Deserializer< IsolateT >::DeserializeDeferredObjects(), v8::internal::ExternalEntityTable< Entry, size >::DetachSpaceFromReadOnlySegments(), v8::internal::Sweeper::EnsurePageIsSwept(), v8::internal::MarkCompactCollector::Evacuate(), v8::internal::ExternalEntityTable< Entry, size >::Extend(), v8::internal::anonymous_namespace{runtime-test.cc}::FillUpOneNewSpacePage(), v8::internal::Sweeper::FinishMajorJobs(), v8::internal::MarkCompactCollector::FlushBytecodeFromSFI(), v8::internal::Sweeper::FreeAndProcessFreedMemory(), v8::internal::EvacuationAllocator::FreeLast(), cppgc::internal::NormalPageSpace::From(), cppgc::internal::LargePageSpace::From(), v8::internal::SemiSpaceNewSpace::From(), v8::internal::PagedNewSpace::From(), v8::internal::StickySpace::From(), v8::internal::ExternalEntityTable< Entry, size >::GenericSweep(), v8::internal::CompactionSpaceCollection::Get(), v8::internal::Sweeper::GetAllSweptPagesSafe(), v8::Isolate::GetHeapSpaceStatistics(), v8::internal::Sweeper::GetSweepingPageSafe(), v8::internal::Sweeper::GetSweepSpaceIndex(), v8::internal::Sweeper::GetSweptPageSafe(), v8::internal::Sweeper::GetTracingScope(), v8::internal::SpaceIterator::HasNext(), v8::internal::MemoryChunkIterator::HasNext(), v8::internal::ExternalEntityTable< Entry, size >::InitializeSpace(), v8::internal::InitSelfIndirectPointerField(), v8::internal::IsAnyCodeSpace(), v8::internal::IsAnyNewSpace(), v8::internal::IsAnySharedSpace(), v8::internal::IsAnyTrustedSpace(), v8::internal::anonymous_namespace{main-allocator.cc}::IsPagedNewSpaceAtFullCapacity(), v8::internal::anonymous_namespace{memory-allocator.cc}::IsPagePoolSupportedForLargeSpace(), v8::internal::Sweeper::IsSweepingDoneForSpace(), v8::internal::Sweeper::IsValidSweepingSpace(), v8::internal::ExternalEntityTable< Entry, size >::IterateEntriesIn(), v8::internal::LargeObjectSpaceObjectIterator::LargeObjectSpaceObjectIterator(), v8::internal::MarkingVisitorBase< ReferenceSummarizerMarkingVisitor >::MakeOlder(), v8::internal::WriteBarrier::MarkingSlow(), v8::internal::WriteBarrier::MarkingSlowFromCppHeapWrappable(), v8::internal::FullMarkingVisitorBase< ConcreteVisitor >::MarkPointerTableEntry(), v8::internal::MutablePageMetadata::MutablePageMetadata(), v8::internal::PagedSpaceIterator::Next(), v8::internal::SpaceIterator::Next(), v8::internal::MemoryChunkLayout::ObjectStartOffsetInMemoryChunk(), v8::internal::MemoryChunk::OldGenerationPageFlags(), v8::internal::IncrementalMarking::OldGenerationSizeOfObjects(), v8::internal::operator<<(), cppgc::internal::ObjectAllocator::OutOfLineAllocate(), cppgc::internal::ObjectAllocator::OutOfLineAllocateGCSafePoint(), cppgc::internal::ObjectAllocator::OutOfLineAllocateImpl(), v8::internal::Serializer::OutputStatistics(), v8::internal::MemoryAllocator::page_allocator(), v8::internal::PagedSpaceBase::PagedSpaceBase(), v8::internal::Deserializer< IsolateT >::PostProcessNewObject(), v8::internal::Sweeper::PrepareToBeIteratedPromotedPage(), v8::internal::Sweeper::PrepareToBeSweptPage(), v8::internal::Sweeper::RawSweep(), v8::internal::Deserializer< IsolateT >::ReadAllocateJSDispatchEntry(), v8::internal::Deserializer< IsolateT >::ReadMetaMap(), v8::internal::Deserializer< IsolateT >::ReadNewMetaMap(), v8::internal::Deserializer< IsolateT >::ReadNewObject(), v8::internal::Deserializer< IsolateT >::ReadObject(), v8::internal::Assembler::RecordDeoptReason(), v8::internal::MarkCompactCollector::ReleaseEvacuationCandidates(), v8::internal::MarkCompactCollector::ReleasePage(), cppgc::internal::anonymous_namespace{object-allocator.cc}::ReplaceLinearAllocationBuffer(), v8::internal::anonymous_namespace{cpp-heap.cc}::ReportCustomSpaceStatistics(), cppgc::internal::MarkingVerifierBase::ReportDifferences(), v8::internal::HeapObject::RequiredAlignment(), v8::internal::MarkCompactCollector::ResetAndRelinkBlackAllocatedPage(), cppgc::internal::ObjectAllocator::ResetLinearAllocationBuffers(), v8::internal::MemoryAllocator::ResizeLargePage(), v8::internal::RUNTIME_FUNCTION(), v8::internal::Serializer::ObjectSerializer::SerializeExternalStringAsSequentialString(), v8::internal::Serializer::ObjectSerializer::SerializeObject(), v8::internal::Serializer::ObjectSerializer::SerializePrologue(), v8::internal::Serializer::Serializer(), v8::internal::MemoryChunkMetadata::set_owner(), v8::internal::anonymous_namespace{marking-barrier.cc}::SetGenerationPageFlags(), v8::internal::MemoryChunk::SetOldGenerationPageFlags(), v8::internal::anonymous_namespace{mark-compact.cc}::ShouldPostponeFreeingEmptyPages(), v8::internal::Sweeper::ShouldRefillFreelistForSpace(), v8::internal::anonymous_namespace{mark-compact.cc}::ShrinkPagesToObjectSizes(), v8::internal::anonymous_namespace{deserializer.cc}::SnapshotSpaceName(), cppgc::internal::RawHeap::Space(), v8::internal::anonymous_namespace{deserializer.cc}::SpaceToAllocation(), v8::internal::Sweeper::StartMajorSweeping(), v8::internal::MarkCompactCollector::StartSweepSpace(), cppgc::internal::Sweeper::SweepForAllocationIfRunning(), cppgc::internal::Sweeper::SweeperImpl::SweepForAllocationIfRunning(), cppgc::internal::Sweeper::SweeperImpl::SweepForLargeAllocation(), cppgc::internal::Sweeper::SweeperImpl::SweepForNormalAllocation(), v8::internal::Heap::sweeping_in_progress_for_space(), v8::internal::Sweeper::sweeping_in_progress_for_space(), v8::internal::MarkCompactCollector::SweepLargeSpace(), v8::internal::ExternalEntityTable< Entry, size >::TearDownSpace(), v8::internal::ToString(), v8::internal::anonymous_namespace{serializer.cc}::ToString(), v8::internal::Serializer::TotalAllocationSize(), v8::internal::TraceFragmentation(), cppgc::internal::HeapVisitor< Derived >::Traverse(), v8::internal::ExternalEntityTable< Entry, size >::TryAllocateEntry(), v8::internal::ExternalEntityTable< Entry, size >::TryAllocateEntryFromFreelist(), cppgc::internal::anonymous_namespace{object-allocator.cc}::TryAllocateLargeObject(), cppgc::internal::anonymous_namespace{object-allocator.cc}::TryAllocateLargeObjectImpl(), v8::internal::MemoryAllocator::TryAllocateUninitializedLargePageFromPool(), cppgc::internal::ObjectAllocator::TryExpandAndRefillLinearAllocationBuffer(), v8::internal::ExternalEntityTable< Entry, size >::TryExtend(), cppgc::internal::ObjectAllocator::TryRefillLinearAllocationBuffer(), cppgc::internal::ObjectAllocator::TryRefillLinearAllocationBufferFromFreeList(), v8::internal::Sweeper::TryRemoveSweepingPageSafe(), v8::internal::HeapAllocator::TryResizeLargeObject(), cppgc::internal::anonymous_namespace{compactor.cc}::UpdateHeapResidency(), v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitCppHeapPointer(), v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitJSDispatchTableEntry(), cppgc::internal::anonymous_namespace{sweeper.cc}::PrepareForSweepVisitor::VisitLargePageSpace(), cppgc::internal::HeapVisitor< Derived >::VisitLargePageSpaceImpl(), cppgc::internal::HeapStatisticsCollector::VisitNormalPageSpace(), cppgc::internal::anonymous_namespace{sweeper.cc}::PrepareForSweepVisitor::VisitNormalPageSpace(), cppgc::internal::HeapVisitor< Derived >::VisitNormalPageSpaceImpl(), and v8::internal::PagedNewSpaceAllocatorPolicy::WaitForSweepingForAllocation().
speed
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for<n> old space garbage collections print one detailed trace line in allocation speed
Definition at line 2208 of file flag-definitions.h.
testing
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and reclaim otherwise unreachable unmodified wrapper objects when possible discard the memory pool before invoking the GC on memory pressure or last resort GCs Delay before memory reducer start virtual randomize memory reservations by ignoring any hints passed when allocating pages use incremental marking for CppHeap cppheap_concurrent_marking c value for membalancer A special constant to balance between memory and space tradeoff The smaller the more memory it uses enable use of SSE4 instructions if available enable use of SAHF instruction if enable use of AVX VNNI instructions if available enable use of POPCNT instruction if available force all emitted branches to be in long enable use of partial constant enable optional features on the simulator for testing
Definition at line 2399 of file flag-definitions.h.
true
too high values may cause the compiler to set high thresholds for inlining to as much as possible avoid inlined allocation of objects that cannot escape trace load stores from virtual maglev objects use TurboFan fast string builder analyze liveness of environment slots and zap dead values trace TurboFan load elimination emit data about basic block usage in builtins to this enable builtin reordering when run mksnapshot flag for emit warnings when applying builtin profile data verify register allocation in TurboFan randomly schedule instructions to stress dependency tracking enable store store elimination in TurboFan rewrite far to near simulate GC compiler thread race related to allow float parameters to be passed in simulator mode JS Wasm Run additional turbo_optimize_inlined_js_wasm_wrappers enables Turboshaft s StaticAssert and CheckTurboshaftTypeOf operations Wasm code into JS functions via the JS to Wasm wrappers are still inlined in TurboFan For controlling whether to at see turbo inline js wasm calls enable Turboshaft s loop unrolling enable an additional Turboshaft phase that performs optimizations based on type information enable Turbolev features that we want to ship in the not too far future trace individual Turboshaft reduction steps trace intermediate Turboshaft reduction steps trace Turboshaft s if else to switch reducer invocation count threshold for early optimization Enables optimizations which favor memory size over execution speed Enables sampling allocation profiler with X as a sample interval min size of a semi the new space consists of two semi spaces max size of the preconfigured old space Collect garbage after Collect garbage after keeps maps alive for< n > old space garbage collections print one detailed trace line in allocation gc speed threshold for starting incremental marking via a task in percent of available threshold for starting incremental marking immediately in percent of available Use a single schedule for determining a marking schedule between JS and C objects schedules the minor GC task with kUserVisible priority max worker number of concurrent for NumberOfWorkerThreads start background threads that allocate memory concurrent_array_buffer_sweeping use parallel threads to clear weak refs in the atomic pause trace progress of the incremental marking trace object counts and memory usage report a tick only when allocated zone memory changes by this amount TracingFlags::gc_stats TracingFlags::gc_stats track native contexts that are expected to be garbage collected verify heap pointers before and after GC memory reducer runs GC with ReduceMemoryFootprint flag Maximum number of memory reducer GCs scheduled Old gen GC speed is computed directly from gc tracer counters Perform compaction on full GCs based on V8 s default heuristics Perform compaction on every full GC Perform code space compaction when finalizing a full GC with stack Stress GC compaction to flush out bugs with moving objects flush of baseline code when it has not been executed recently Use time base code flushing instead of age Use a progress bar to scan large objects in increments when incremental marking is active force incremental marking for small heaps and run it more often Release pooled large pages after X seconds prints number of allocations and enables analysis mode for gc fuzz e g stress stress scavenge force scavenge at random points between and reclaim otherwise unreachable unmodified wrapper objects when possible discard the memory pool before invoking the GC on memory pressure or last resort GCs Delay before memory reducer start virtual randomize memory reservations by ignoring any hints passed when allocating pages use incremental marking for CppHeap cppheap_concurrent_marking c value for membalancer A special constant to balance between memory and space tradeoff The smaller the more memory it uses enable use of SSE4 instructions if available enable use of SAHF instruction if enable use of AVX VNNI instructions if available enable use of POPCNT instruction if available force all emitted branches to be in long enable use of partial constant enable optional features on the simulator for enable mitigation for Intel JCC erratum on affected CPUs enable unaligned accesses for the regexp engine enable deserializing code caches on background enable type checks based on instance types provided by the embedder expose externalize string extension show built in functions in stack traces disallow eval and friends true
Definition at line 367 of file flag-definitions.h.
V8_ALLOCATION_FOLDING_BOOL
V8_ALLOCATION_FOLDING_BOOL
Definition at line 423 of file flag-definitions.h.
V8_ENABLE_DIRECT_HANDLE_BOOL
use conservative stack scanning V8_ENABLE_DIRECT_HANDLE_BOOL
Definition at line 479 of file flag-definitions.h.
V8_ENABLE_UNCONDITIONAL_WRITE_BARRIERS_BOOL
V8_ENABLE_UNCONDITIONAL_WRITE_BARRIERS_BOOL
Definition at line 450 of file flag-definitions.h.