/mnt/V8SourceCode/src/snapshot/mksnapshot.cc File Reference
#include <errno.h>
#include <signal.h>
#include <stdio.h>
#include <iomanip>
#include `include/libplatform/libplatform.h`
#include `include/v8-initialization.h`
#include `src/base/logging.h`
#include `src/base/platform/elapsed-timer.h`
#include `src/base/platform/platform.h`
#include `src/base/platform/wrappers.h`
#include `src/base/vector.h`
#include `src/builtins/builtins-effects-analyzer.h`
#include `src/codegen/cpu-features.h`
#include `src/common/globals.h`
#include `src/flags/flags.h`
#include `src/snapshot/embedded/embedded-file-writer.h`
#include `src/snapshot/snapshot.h`
#include `src/snapshot/static-roots-gen.h`
Classes
class anonymous_namespace{mksnapshot.cc}::SnapshotFileWriter
Namespaces
 anonymous_namespace{mksnapshot.cc}
Typedefs
using anonymous_namespace{mksnapshot.cc}::CounterMap = std::map< std::string, int >
Functions
std::unique_ptr< char[]> anonymous_namespace{mksnapshot.cc}::GetExtraCode (char *filename, const char *description)
v8::StartupData anonymous_namespace{mksnapshot.cc}::CreateSnapshotDataBlob (v8::SnapshotCreator &snapshot_creator, const char *embedded_source)
v8::StartupData anonymous_namespace{mksnapshot.cc}::WarmUpSnapshotDataBlob (v8::StartupData cold_snapshot_blob, const char *warmup_source)
void anonymous_namespace{mksnapshot.cc}::WriteEmbeddedFile (i::EmbeddedFileWriter *writer)
void anonymous_namespace{mksnapshot.cc}::MaybeSetCounterFunction (v8::Isolate *isolate)
int main (int argc, char **argv)
Variables
CounterMap * anonymous_namespace{mksnapshot.cc}::counter_map_ = nullptr
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 225 of file mksnapshot.cc.
                                {
  v8::base::EnsureConsoleOutput();
  // Make mksnapshot runs predictable to create reproducible snapshots.
  i::v8_flags.predictable = true;
  // Disable ICs globally in mksnapshot to avoid problems with Code handlers.
  // See https://crbug.com/345280736.
  // TODO(jgruber): Re-enable once a better fix is available.
  i::v8_flags.use_ic = false;
  // Print the usage if an error occurs when parsing the command line
  // flags or if the help flag is set.
  using HelpOptions = i::FlagList::HelpOptions;
  std::string usage = "Usage: " + std::string(argv[0]) +
                      " [--startup-src=file]" + " [--startup-blob=file]" +
                      " [--embedded-src=file]" + " [--embedded-variant=label]" +
                      " [--static-roots-src=file]" + " [--target-arch=arch]" +
                      " [--target-os=os] [extras]\n\n";
  int result = i::FlagList::SetFlagsFromCommandLine(
      &argc, argv, true, HelpOptions(HelpOptions::kExit, usage.c_str()));
  if (result > 0 || (argc > 3)) {
    i::PrintF(stdout, "%s", usage.c_str());
    return result;
  }
  i::CpuFeatures::Probe(true);
  v8::V8::InitializeICUDefaultLocation(argv[0]);
  std::unique_ptr<v8::Platform> platform = v8::platform::NewDefaultPlatform();
  v8::V8::InitializePlatform(platform.get());
  v8::V8::Initialize();
  {
    SnapshotFileWriter snapshot_writer;
    snapshot_writer.SetSnapshotFile(i::v8_flags.startup_src);
    snapshot_writer.SetStartupBlobFile(i::v8_flags.startup_blob);
    i::EmbeddedFileWriter embedded_writer;
    embedded_writer.SetEmbeddedFile(i::v8_flags.embedded_src);
    embedded_writer.SetEmbeddedVariant(i::v8_flags.embedded_variant);
    embedded_writer.SetTargetArch(i::v8_flags.target_arch);
    embedded_writer.SetTargetOs(i::v8_flags.target_os);
    std::unique_ptr<char[]> embed_script =
        GetExtraCode(argc >= 2 ? argv[1] : nullptr, "embedding");
    std::unique_ptr<char[]> warmup_script =
        GetExtraCode(argc >= 3 ? argv[2] : nullptr, "warm up");
    v8::StartupData blob;
    {
      v8::Isolate* isolate = v8::Isolate::Allocate();
      MaybeSetCounterFunction(isolate);
      // The isolate contains data from builtin compilation that needs
      // to be written out if builtins are embedded.
      i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(isolate);
      i_isolate->RegisterEmbeddedFileWriter(&embedded_writer);
      std::unique_ptr<v8::ArrayBuffer::Allocator> array_buffer_allocator(
          v8::ArrayBuffer::Allocator::NewDefaultAllocator());
      v8::Isolate::CreateParams create_params;
      create_params.array_buffer_allocator = array_buffer_allocator.get();
      // Set code range such that relative jumps for builtins to
      // builtin calls in the snapshot are possible.
      size_t code_range_size_mb =
          i::kMaximalCodeRangeSize == 0
              ? i::kMaxPCRelativeCodeRangeInMB
              : std::min(i::kMaximalCodeRangeSize / i::MB,
                         i::kMaxPCRelativeCodeRangeInMB);
      create_params.constraints.set_code_range_size_in_bytes(
          code_range_size_mb * i::MB);
      {
        v8::SnapshotCreator creator(isolate, create_params);
        blob = CreateSnapshotDataBlob(creator, embed_script.get());
        WriteEmbeddedFile(&embedded_writer);
#if V8_STATIC_ROOTS_GENERATION_BOOL
        if (i::v8_flags.static_roots_src) {
          i::StaticRootsTableGen::write(i_isolate,
                                        i::v8_flags.static_roots_src);
        }
#endif
        if (i::v8_flags.builtins_effects_src) {
          DCHECK_NOT_NULL(i_isolate->builtins_effects_analyzer());
          i_isolate->builtins_effects_analyzer()->Write(
              i::v8_flags.builtins_effects_src);
        }
        if (i_isolate->builtins_effects_analyzer() != nullptr) {
          i_isolate->builtins_effects_analyzer()->TearDown(i_isolate);
        }
      }
      isolate->Dispose();
    }
    if (warmup_script) {
      v8::StartupData cold = blob;
      blob = WarmUpSnapshotDataBlob(cold, warmup_script.get());
      delete[] cold.data;
    }
    delete counter_map_;
    CHECK(blob.data);
    snapshot_writer.WriteSnapshot(blob);
    delete[] blob.data;
  }
  v8::V8::Dispose();
  v8::V8::DisposePlatform();
  return 0;
}
References v8::Isolate::Allocate(), v8::Isolate::CreateParams::array_buffer_allocator, v8::internal::Isolate::builtins_effects_analyzer(), CHECK, v8::Isolate::CreateParams::constraints, anonymous_namespace{mksnapshot.cc}::counter_map_, anonymous_namespace{mksnapshot.cc}::CreateSnapshotDataBlob(), v8::StartupData::data, DCHECK_NOT_NULL, v8::V8::Dispose(), v8::Isolate::Dispose(), v8::V8::DisposePlatform(), v8::base::EnsureConsoleOutput(), anonymous_namespace{mksnapshot.cc}::GetExtraCode(), v8::V8::Initialize(), v8::V8::InitializeICUDefaultLocation(), v8::V8::InitializePlatform(), v8::internal::kMaximalCodeRangeSize, v8::internal::kMaxPCRelativeCodeRangeInMB, anonymous_namespace{mksnapshot.cc}::MaybeSetCounterFunction(), MB, v8::ArrayBuffer::Allocator::NewDefaultAllocator(), v8::platform::NewDefaultPlatform(), v8::internal::PrintF(), v8::internal::CpuFeatures::Probe(), v8::internal::Isolate::RegisterEmbeddedFileWriter(), v8::base::internal::result, v8::ResourceConstraints::set_code_range_size_in_bytes(), v8::internal::EmbeddedFileWriter::SetEmbeddedFile(), v8::internal::EmbeddedFileWriter::SetEmbeddedVariant(), v8::internal::FlagList::SetFlagsFromCommandLine(), v8::internal::EmbeddedFileWriter::SetTargetArch(), v8::internal::EmbeddedFileWriter::SetTargetOs(), v8::internal::string, v8::internal::BuiltinsEffectsAnalyzer::TearDown(), v8::internal::v8_flags, anonymous_namespace{mksnapshot.cc}::WarmUpSnapshotDataBlob(), v8::internal::BuiltinsEffectsAnalyzer::Write(), v8::internal::StaticRootsTableGen::write(), and anonymous_namespace{mksnapshot.cc}::WriteEmbeddedFile().