v8::internal::compiler::anonymous_namespace{js-typed-lowering.cc} Namespace Reference
Functions
void ReduceBuiltin (JSGraph *jsgraph, Node *node, Builtin builtin, int arity, CallDescriptor::Flags flags)
Function Documentation
ReduceBuiltin()
void v8::internal::compiler::anonymous_namespace{js-typed-lowering.cc}::ReduceBuiltin (JSGraph * jsgraph, Node * node, Builtin builtin, int arity, CallDescriptor::Flags flags)
Definition at line 1831 of file js-typed-lowering.cc.
                                              {
  // Patch {node} to a direct CEntry call.
  // ----------- A r g u m e n t s -----------
  // -- 0: CEntry
  // --- Stack args ---
  // -- 1: new_target
  // -- 2: target
  // -- 3: argc, including the receiver and implicit args (Smi)
  // -- 4: padding
  // -- 5: receiver
  // -- [6, 6 + n[: the n actual arguments passed to the builtin
  // --- Register args ---
  // -- 6 + n: the C entry point
  // -- 6 + n + 1: argc (Int32)
  // -----------------------------------
  // These SBXCHECKs are a defense-in-depth measure to ensure that we always
  // generate valid calls here (with matching signatures).
  SBXCHECK(Builtins::IsCpp(builtin));
  SBXCHECK_GE(arity + kJSArgcReceiverSlots,
              Builtins::GetFormalParameterCount(builtin));
  // The logic contained here is mirrored in Builtins::Generate_Adaptor.
  // Keep these in sync.
  Node* target = node->InputAt(JSCallOrConstructNode::TargetIndex());
  // Unify representations between construct and call nodes. For construct
  // nodes, the receiver is undefined. For call nodes, the new_target is
  // undefined.
  Node* new_target;
  Zone* zone = jsgraph->zone();
  if (node->opcode() == IrOpcode::kJSConstruct) {
    static_assert(JSCallNode::ReceiverIndex() ==
                  JSConstructNode::NewTargetIndex());
    new_target = JSConstructNode{node}.new_target();
    node->ReplaceInput(JSConstructNode::NewTargetIndex(),
                       jsgraph->UndefinedConstant());
    node->RemoveInput(JSConstructNode{node}.FeedbackVectorIndex());
  } else {
    new_target = jsgraph->UndefinedConstant();
    node->RemoveInput(JSCallNode{node}.FeedbackVectorIndex());
  }
  // CPP builtins are implemented in C++, and we can inline it.
  // CPP builtins create a builtin exit frame.
  const bool has_builtin_exit_frame = true;
  Node* stub =
      jsgraph->CEntryStubConstant(1, ArgvMode::kStack, has_builtin_exit_frame);
  node->ReplaceInput(0, stub);
  const int argc = arity + BuiltinArguments::kNumExtraArgsWithReceiver;
  Node* argc_node = jsgraph->ConstantNoHole(argc);
  static const int kStub = 1;
  static_assert(BuiltinArguments::kNewTargetIndex == 0);
  static_assert(BuiltinArguments::kTargetIndex == 1);
  static_assert(BuiltinArguments::kArgcIndex == 2);
  static_assert(BuiltinArguments::kPaddingIndex == 3);
  node->InsertInput(zone, 1, new_target);
  node->InsertInput(zone, 2, target);
  node->InsertInput(zone, 3, argc_node);
  node->InsertInput(zone, 4, jsgraph->PaddingConstant());
  int cursor = arity + kStub + BuiltinArguments::kNumExtraArgsWithReceiver;
  Address entry = Builtins::CppEntryOf(builtin);
  ExternalReference entry_ref = ExternalReference::Create(entry);
  Node* entry_node = jsgraph->ExternalConstant(entry_ref);
  node->InsertInput(zone, cursor++, entry_node);
  node->InsertInput(zone, cursor++, argc_node);
  static const int kReturnCount = 1;
  const char* debug_name = Builtins::name(builtin);
  Operator::Properties properties = node->op()->properties();
  auto call_descriptor = Linkage::GetCEntryStubCallDescriptor(
      zone, kReturnCount, argc, debug_name, properties, flags,
      StackArgumentOrder::kJS);
  NodeProperties::ChangeOp(node, jsgraph->common()->Call(call_descriptor));
}
References v8::internal::compiler::CommonOperatorBuilder::Call(), v8::internal::compiler::JSGraph::CEntryStubConstant(), v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::MachineGraph::common(), v8::internal::compiler::JSGraph::ConstantNoHole(), v8::internal::Builtins::CppEntryOf(), v8::internal::ExternalReference::Create(), v8::internal::compiler::MachineGraph::ExternalConstant(), v8::internal::flags, v8::internal::compiler::Linkage::GetCEntryStubCallDescriptor(), v8::internal::Builtins::GetFormalParameterCount(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::InsertInput(), v8::internal::Builtins::IsCpp(), v8::internal::BuiltinArguments::kArgcIndex, v8::internal::kJS, v8::internal::kJSArgcReceiverSlots, v8::internal::BuiltinArguments::kNewTargetIndex, v8::internal::BuiltinArguments::kNumExtraArgsWithReceiver, v8::internal::BuiltinArguments::kPaddingIndex, v8::internal::kStack, v8::internal::BuiltinArguments::kTargetIndex, v8::internal::Builtins::name(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::JSGraph::PaddingConstant(), v8::internal::compiler::Operator::properties(), v8::internal::compiler::Node::RemoveInput(), v8::internal::compiler::Node::ReplaceInput(), SBXCHECK, SBXCHECK_GE, and v8::internal::compiler::MachineGraph::zone().
Referenced by v8::internal::compiler::JSTypedLowering::ReduceJSCall().