v8_inspector::anonymous_namespace{v8-inspector-session-impl.cc} Namespace Reference
Functions
bool IsCBORMessage (StringView msg)
Status ConvertToCBOR (StringView state, std::vector< uint8_t > *cbor)
std::unique_ptr< protocol::DictionaryValue > ParseState (StringView state)
Function Documentation
ConvertToCBOR()
Status v8_inspector::anonymous_namespace{v8-inspector-session-impl.cc}::ConvertToCBOR (StringView state, std::vector< uint8_t > * cbor)
Definition at line 46 of file v8-inspector-session-impl.cc.
                                                                 {
  return state.is8Bit()
             ? ConvertJSONToCBOR(
                   span<uint8_t>(state.characters8(), state.length()), cbor)
             : ConvertJSONToCBOR(
                   span<uint16_t>(state.characters16(), state.length()), cbor);
}
References v8_inspector::StringView::characters16(), v8_inspector::StringView::characters8(), v8_inspector::StringView::is8Bit(), and v8_inspector::StringView::length().
Referenced by v8_inspector::V8InspectorSessionImpl::breakProgram(), v8_inspector::V8InspectorSessionImpl::dispatchProtocolMessage(), ParseState(), and v8_inspector::V8InspectorSessionImpl::schedulePauseOnNextStatement().
IsCBORMessage()
bool v8_inspector::anonymous_namespace{v8-inspector-session-impl.cc}::IsCBORMessage (StringView msg)
Definition at line 39 of file v8-inspector-session-impl.cc.
                                   {
  if (!msg.is8Bit() || msg.length() < 3) return false;
  const uint8_t* bytes = msg.characters8();
  return bytes[0] == 0xd8 &&
         (bytes[1] == 0x5a || (bytes[1] == 0x18 && bytes[2] == 0x5a));
}
References v8_inspector::StringView::characters8(), v8_inspector::StringView::is8Bit(), and v8_inspector::StringView::length().
Referenced by v8_inspector::V8InspectorSessionImpl::dispatchProtocolMessage(), and ParseState().
ParseState()
std::unique_ptr<protocol::DictionaryValue> v8_inspector::anonymous_namespace{v8-inspector-session-impl.cc}::ParseState (StringView state)
Definition at line 54 of file v8-inspector-session-impl.cc.
                                                                    {
  std::vector<uint8_t> converted;
  span<uint8_t> cbor;
  if (IsCBORMessage(state))
    cbor = span<uint8_t>(state.characters8(), state.length());
  else if (ConvertToCBOR(state, &converted).ok())
    cbor = SpanFrom(converted);
  if (!cbor.empty()) {
    std::unique_ptr<protocol::Value> value =
        protocol::Value::parseBinary(cbor.data(), cbor.size());
    std::unique_ptr<protocol::DictionaryValue> dictionaryValue =
        protocol::DictionaryValue::cast(std::move(value));
    if (dictionaryValue) return dictionaryValue;
  }
  return protocol::DictionaryValue::create();
}
References v8_inspector::StringView::characters8(), ConvertToCBOR(), IsCBORMessage(), v8_inspector::StringView::length(), and v8::internal::value.