v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc} Namespace Reference
Enumerations
enum class CondensedIndices : int { ENTRY
 }
Functions
bool EquivalentIndices (ModuleTypeIndex index1, ModuleTypeIndex index2, const WasmModule *module)
bool ValidStructSubtypeDefinition (ModuleTypeIndex subtype_index, ModuleTypeIndex supertype_index, const WasmModule *module)
bool ValidArraySubtypeDefinition (ModuleTypeIndex subtype_index, ModuleTypeIndex supertype_index, const WasmModule *module)
bool ValidFunctionSubtypeDefinition (ModuleTypeIndex subtype_index, ModuleTypeIndex supertype_index, const WasmModule *module)
bool ValidContinuationSubtypeDefinition (ModuleTypeIndex subtype_index, ModuleTypeIndex supertype_index, const WasmModule *module)
StandardType UpcastToStandardType (ValueTypeBase type)
constexpr GenericKind ToGenericKind (StandardType type)
constexpr int NotInSubtypeRelation (StandardType type)
constexpr uint8_t ComputeCondensedIndex (StandardType type)
constexpr StandardType ComputeStandardType (uint8_t condensed_index)
constexpr uint8_t CondensedIndex (StandardType type)
constexpr StandardType CondensedToStandard (uint8_t condensed)
constexpr bool ComputeIsSubtype (size_t sub, size_t super)
constexpr bool SubtypeLookup (StandardType sub, StandardType super)
constexpr StandardType ComputeCommonAncestor (size_t t1, size_t t2)
constexpr StandardType CommonAncestorLookup (StandardType t1, StandardType t2)
HeapType NullSentinelImpl (HeapType type)
bool IsNullSentinel (ValueTypeBase type)
bool IsGenericSubtypeOfIndexedTypes (ValueTypeBase type)
std::optional< bool > IsSubtypeOf_CommonImpl (ValueTypeBase subtype, ValueTypeBase supertype)
HeapType CommonAncestor (HeapType type1, HeapType type2, const WasmModule *module)
HeapType CommonAncestorWithAbstract (HeapType heap1, HeapType heap2)
Exactness UnionExactness (ValueType type1, ValueType type2, const WasmModule *module)
Variables
static constexpr uint32_t kNumStandardTypes
static constexpr std::array< GenericKind, kNumStandardTypes > kValueTypeLookupMap
static constexpr uint32_t kNumNonTrivial
static constexpr uint8_t kNotRelatedSentinel = 0xFF
static constexpr std::array< uint8_t, kNumStandardTypes > kCondensedIndexLookupMap
static constexpr std::array< uint8_t, kNumNonTrivial > kCondensedToStandardMap
static constexpr std::array< std::array< bool, kNumNonTrivial >, kNumNonTrivial > kSubtypeLookupMap2
static constexpr std::array< std::array< StandardType, kNumNonTrivial >, kNumNonTrivial > kCommonAncestorLookupMap
Enumeration Type Documentation
CondensedIndices
enum v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::CondensedIndices : int [strong]
Enumerator
ENTRY
Definition at line 196 of file wasm-subtyping.cc.
                            : int {
// "kFooAdjustNext" is a dummy entry to control whether the next "kBar" will
// get its own unique value: when NotInSubtypeRelation(kFoo), then we'll end
// up with kFoo = N, kFooAdJustNext = N-1, kBar = N, and we'll never use
// kFoo later, so have effectively skipped it from the condensed space.
#define ENTRY(name, ...) \
  k##name, \
      k##name##AdjustNext = \
          k##name - NotInSubtypeRelation(StandardType::k##name),
  FOREACH_GENERIC_TYPE(ENTRY)
#undef ENTRY
};
Function Documentation
CommonAncestor()
HeapType v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::CommonAncestor (HeapType type1, HeapType type2, const WasmModule * module)
Definition at line 512 of file wasm-subtyping.cc.
                                                  {
  DCHECK(type1.has_index() && type2.has_index());
  bool both_shared = type1.is_shared();
  if (both_shared != type2.is_shared()) return HeapType{kWasmTop};
  ModuleTypeIndex type_index1 = type1.ref_index();
  ModuleTypeIndex type_index2 = type2.ref_index();
  {
    int depth1 = GetSubtypingDepth(module, type_index1);
    int depth2 = GetSubtypingDepth(module, type_index2);
    while (depth1 > depth2) {
      type_index1 = module->supertype(type_index1);
      depth1--;
    }
    while (depth2 > depth1) {
      type_index2 = module->supertype(type_index2);
      depth2--;
    }
  }
  DCHECK_NE(type_index1, kNoSuperType);
  DCHECK_NE(type_index2, kNoSuperType);
  while (type_index1 != kNoSuperType &&
         !EquivalentIndices(type_index1, type_index2, module)) {
    type_index1 = module->supertype(type_index1);
    type_index2 = module->supertype(type_index2);
  }
  DCHECK_EQ(type_index1 == kNoSuperType, type_index2 == kNoSuperType);
  RefTypeKind kind1 = type1.ref_type_kind();
  if (type_index1 != kNoSuperType) {
    DCHECK_EQ(kind1, type2.ref_type_kind());
    return HeapType::Index(type_index1, both_shared, kind1);
  }
  // No indexed type was found as common ancestor, so we can treat both types
  // as generic.
  StandardType generic_ancestor = CommonAncestorLookup(
      UpcastToStandardType(type1), UpcastToStandardType(type2));
  return HeapType::Generic(ToGenericKind(generic_ancestor), both_shared);
}
References CommonAncestorLookup(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NE, EquivalentIndices(), v8::internal::wasm::HeapType::Generic(), v8::internal::wasm::GetSubtypingDepth(), v8::internal::wasm::ValueTypeBase::has_index(), v8::internal::wasm::HeapType::Index(), v8::internal::wasm::ValueTypeBase::is_shared(), v8::internal::wasm::kNoSuperType, v8::internal::wasm::kWasmTop, v8::internal::wasm::HeapType::ref_index(), v8::internal::wasm::ValueTypeBase::ref_type_kind(), v8::internal::wasm::WasmModule::supertype(), ToGenericKind(), and UpcastToStandardType().
Referenced by v8::internal::wasm::Union().
CommonAncestorLookup()
constexpr StandardType v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::CommonAncestorLookup (StandardType t1, StandardType t2) [constexpr]
Definition at line 321 of file wasm-subtyping.cc.
                                                                              {
  if (t1 == StandardType::kBottom) return t2;
  if (t2 == StandardType::kBottom) return t1;
  if (t1 == StandardType::kTop) return t1;
  if (t2 == StandardType::kTop) return t2;
  uint8_t t1_condensed = CondensedIndex(t1);
  if (t1_condensed == kNotRelatedSentinel) {
    return t2 == t1 ? t1 : StandardType::kTop;
  }
  uint8_t t2_condensed = CondensedIndex(t2);
  if (t2_condensed == kNotRelatedSentinel) return StandardType::kTop;
  return kCommonAncestorLookupMap[t1_condensed][t2_condensed];
}
References CondensedIndex(), kCommonAncestorLookupMap, and kNotRelatedSentinel.
Referenced by CommonAncestor(), and CommonAncestorWithAbstract().
CommonAncestorWithAbstract()
HeapType v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::CommonAncestorWithAbstract (HeapType heap1, HeapType heap2)
Definition at line 554 of file wasm-subtyping.cc.
                                                                    {
  DCHECK(heap1.is_abstract_ref());
  bool is_shared = heap1.is_shared();
  if (is_shared != heap2.is_shared()) return HeapType{kWasmTop};
  // If {heap2} is an indexed type, then {heap1} could be a subtype of it if
  // it is a none-type. In that case, {heap2} is the common ancestor.
  std::optional<bool> is_sub = IsSubtypeOf_CommonImpl(heap1, heap2);
  DCHECK(is_sub.has_value()); // Guaranteed by {heap1.is_abstract_ref()}.
  if (is_sub.value()) return heap2;
  // Otherwise, we can treat {heap2} like its generic supertype (e.g. any
  // indexed struct is "rounded up" to structref).
  StandardType generic_ancestor = CommonAncestorLookup(
      UpcastToStandardType(heap1), UpcastToStandardType(heap2));
  return HeapType::Generic(ToGenericKind(generic_ancestor), is_shared);
}
References CommonAncestorLookup(), v8::internal::DCHECK(), v8::internal::wasm::HeapType::Generic(), v8::internal::wasm::ValueTypeBase::is_abstract_ref(), v8::internal::is_shared, v8::internal::wasm::ValueTypeBase::is_shared(), IsSubtypeOf_CommonImpl(), v8::internal::wasm::kWasmTop, ToGenericKind(), and UpcastToStandardType().
Referenced by v8::internal::wasm::Union().
ComputeCommonAncestor()
constexpr StandardType v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::ComputeCommonAncestor (size_t t1, size_t t2) [constexpr]
Definition at line 298 of file wasm-subtyping.cc.
                                                                   {
  if (kSubtypeLookupMap2[t1][t2]) return CondensedToStandard(t2);
  if (kSubtypeLookupMap2[t2][t1]) return CondensedToStandard(t1);
#define CASE(a, b) \
  if (t1 == static_cast<size_t>(CondensedIndices::k##a)) { \
    return ComputeCommonAncestor(static_cast<size_t>(CondensedIndices::k##b), \
                                 t2); \
  }
  FOREACH_SUBTYPING(CASE)
#undef CASE
  return StandardType::kTop;
}
References CASE, CondensedToStandard(), FOREACH_SUBTYPING, and kSubtypeLookupMap2.
ComputeCondensedIndex()
constexpr uint8_t v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::ComputeCondensedIndex (StandardType type) [constexpr]
Definition at line 211 of file wasm-subtyping.cc.
                                                           {
  switch (type) {
#define BAILOUT(name, ...) case StandardType::k##name:
    FOREACH_NUMERIC_VALUE_TYPE(BAILOUT)
    return kNotRelatedSentinel;
#undef BAILOUT
#define CASE(name, ...) \
  case StandardType::k##name: \
    if (NotInSubtypeRelation(type)) return kNotRelatedSentinel; \
    return static_cast<uint8_t>(CondensedIndices::k##name);
    FOREACH_GENERIC_TYPE(CASE)
#undef CASE
  }
}
References BAILOUT, CASE, FOREACH_GENERIC_TYPE, FOREACH_NUMERIC_VALUE_TYPE, kNotRelatedSentinel, and v8::internal::tracing::type.
ComputeIsSubtype()
constexpr bool v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::ComputeIsSubtype (size_t sub, size_t super) [constexpr]
Definition at line 254 of file wasm-subtyping.cc.
                                                          {
  if (sub == super) return true;
#define CASE(a, b) \
  { \
    size_t raw_a = static_cast<size_t>(CondensedIndices::k##a); \
    size_t raw_b = static_cast<size_t>(CondensedIndices::k##b); \
    if (sub == raw_a) { \
      if (super == raw_b) return true; \
      if (ComputeIsSubtype(raw_b, super)) return true; \
    } \
  }
  FOREACH_SUBTYPING(CASE)
#undef CASE
  return false;
}
References CASE, and FOREACH_SUBTYPING.
ComputeStandardType()
constexpr StandardType v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::ComputeStandardType (uint8_t condensed_index) [constexpr]
Definition at line 225 of file wasm-subtyping.cc.
                                                                    {
#define CASE(name, ...) \
  if (ComputeCondensedIndex(StandardType::k##name) == condensed_index) \
    return StandardType::k##name;
  FOREACH_GENERIC_TYPE(CASE)
#undef CASE
  UNREACHABLE();
}
References CASE, FOREACH_GENERIC_TYPE, and v8::internal::UNREACHABLE().
CondensedIndex()
constexpr uint8_t v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::CondensedIndex (StandardType type) [constexpr]
Definition at line 243 of file wasm-subtyping.cc.
                                                    {
  return kCondensedIndexLookupMap[static_cast<size_t>(type)];
}
References kCondensedIndexLookupMap, and v8::internal::tracing::type.
Referenced by CommonAncestorLookup(), and SubtypeLookup().
CondensedToStandard()
constexpr StandardType v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::CondensedToStandard (uint8_t condensed) [constexpr]
Definition at line 246 of file wasm-subtyping.cc.
                                                              {
  return static_cast<StandardType>(kCondensedToStandardMap[condensed]);
}
References kCondensedToStandardMap.
Referenced by ComputeCommonAncestor().
EquivalentIndices()
bool v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::EquivalentIndices (ModuleTypeIndex index1, ModuleTypeIndex index2, const WasmModule * module) [inline]
Definition at line 14 of file wasm-subtyping.cc.
                                                           {
  if (index1 == index2) return true;
  return module->canonical_type_id(index1) == module->canonical_type_id(index2);
}
References v8::internal::wasm::WasmModule::canonical_type_id().
Referenced by CommonAncestor(), v8::internal::wasm::EquivalentTypes(), and UnionExactness().
IsGenericSubtypeOfIndexedTypes()
bool v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::IsGenericSubtypeOfIndexedTypes (ValueTypeBase type)
Definition at line 364 of file wasm-subtyping.cc.
                                                        {
  DCHECK(type.is_generic());
  GenericKind kind = type.generic_kind();
  return IsNullKind(kind) || kind == GenericKind::kBottom;
}
References v8::internal::DCHECK(), v8::internal::wasm::IsNullKind(), and v8::internal::tracing::type.
Referenced by IsSubtypeOf_CommonImpl().
IsNullSentinel()
bool v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::IsNullSentinel (ValueTypeBase type)
Definition at line 358 of file wasm-subtyping.cc.
                                        {
  DCHECK(!type.is_numeric());
  if (!type.is_abstract_ref()) return false;
  return IsNullKind(type.generic_kind());
}
References v8::internal::DCHECK(), v8::internal::wasm::IsNullKind(), and v8::internal::tracing::type.
Referenced by v8::internal::wasm::Intersection(), and UnionExactness().
IsSubtypeOf_CommonImpl()
std::optional<bool> v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::IsSubtypeOf_CommonImpl (ValueTypeBase subtype, ValueTypeBase supertype)
Definition at line 398 of file wasm-subtyping.cc.
                                                                    {
  DCHECK(!subtype.is_numeric() && !supertype.is_numeric());
  if (subtype.is_shared() != supertype.is_shared()) return false;
  if (subtype.is_bottom()) return true;
  if (supertype.has_index()) {
    if (subtype.has_index()) {
      // Only exact types can possibly be subtypes of other exact types.
      if (supertype.is_exact() && !subtype.is_exact()) return false;
      // If both types are indexed, the specialized implementations need to
      // take care of it.
      return {};
    }
    // Subtype is generic. It can only be a subtype if it is a none-type.
    if (!IsGenericSubtypeOfIndexedTypes(subtype)) return false;
  }
  return SubtypeLookup(UpcastToStandardType(subtype),
                       UpcastToStandardType(supertype));
}
References v8::internal::DCHECK(), v8::internal::wasm::ValueTypeBase::has_index(), v8::internal::wasm::ValueTypeBase::is_bottom(), v8::internal::wasm::ValueTypeBase::is_exact(), v8::internal::wasm::ValueTypeBase::is_numeric(), v8::internal::wasm::ValueTypeBase::is_shared(), IsGenericSubtypeOfIndexedTypes(), SubtypeLookup(), and UpcastToStandardType().
Referenced by CommonAncestorWithAbstract(), and v8::internal::wasm::IsSubtypeOfImpl().
NotInSubtypeRelation()
constexpr int v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::NotInSubtypeRelation (StandardType type) [constexpr]
Definition at line 182 of file wasm-subtyping.cc.
                                                      {
#define CASE(sub, super) \
  if (type == StandardType::k##sub || type == StandardType::k##super) return 0;
  FOREACH_SUBTYPING(CASE)
#undef CASE
  return 1;
}
References CASE, and FOREACH_SUBTYPING.
NullSentinelImpl()
HeapType v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::NullSentinelImpl (HeapType type)
Definition at line 338 of file wasm-subtyping.cc.
                                         {
  StandardType standard = UpcastToStandardType(type);
  constexpr StandardType candidates[] = {
#define NULLTYPE(name, ...) StandardType::k##name,
      FOREACH_NONE_TYPE(NULLTYPE)
#undef NULLTYPE
  };
  for (StandardType candidate : candidates) {
    if (SubtypeLookup(candidate, standard)) {
      return HeapType::Generic(ToGenericKind(candidate), type.is_shared());
    }
  }
  if (type.is_string_view()) {
    // TODO(12868): This special case reflects unresolved discussion. If string
    // views aren't nullable, they shouldn't really show up here at all.
    return HeapType::Generic(GenericKind::kNone, type.is_shared());
  }
  UNREACHABLE();
}
References FOREACH_NONE_TYPE, v8::internal::wasm::HeapType::Generic(), NULLTYPE, SubtypeLookup(), ToGenericKind(), v8::internal::tracing::type, v8::internal::UNREACHABLE(), and UpcastToStandardType().
Referenced by v8::internal::wasm::IsSameTypeHierarchy(), and v8::internal::wasm::ToNullSentinel().
SubtypeLookup()
constexpr bool v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::SubtypeLookup (StandardType sub, StandardType super) [constexpr]
Definition at line 279 of file wasm-subtyping.cc.
                                                                   {
  // Note: this implementation strikes a compromise between time and space.
  // We could put everything into the lookup map, but that would significantly
  // increase its size (at the time of this writing: by about 4x), with
  // mostly-sparse additional entries.
  if (sub == StandardType::kBottom) return true;
  if (super == StandardType::kTop) return true;
  uint8_t sub_condensed = CondensedIndex(sub);
  if (sub_condensed == kNotRelatedSentinel) return sub == super;
  uint8_t super_condensed = CondensedIndex(super);
  if (super_condensed == kNotRelatedSentinel) return false;
  return kSubtypeLookupMap2[sub_condensed][super_condensed];
}
References CondensedIndex(), kNotRelatedSentinel, and kSubtypeLookupMap2.
Referenced by IsSubtypeOf_CommonImpl(), and NullSentinelImpl().
ToGenericKind()
constexpr GenericKind v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::ToGenericKind (StandardType type) [constexpr]
Definition at line 173 of file wasm-subtyping.cc.
                                                       {
  DCHECK_LT(static_cast<int>(type), static_cast<int>(StandardType::kI32));
  return kValueTypeLookupMap[static_cast<size_t>(type)];
}
References DCHECK_LT, kValueTypeLookupMap, and v8::internal::tracing::type.
Referenced by CommonAncestor(), CommonAncestorWithAbstract(), and NullSentinelImpl().
UnionExactness()
Exactness v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::UnionExactness (ValueType type1, ValueType type2, const WasmModule * module)
Definition at line 572 of file wasm-subtyping.cc.
                                                   {
  // The union of two types could be exact in these cases:
  // - if both types are exact and the same type index
  // - if one type is an exact indexed type, and the other is the matching
  // none-type.
  if (type1.is_exact()) {
    if (type2.is_exact()) {
      bool same =
          EquivalentIndices(type1.ref_index(), type2.ref_index(), module);
      return same ? Exactness::kExact : Exactness::kAnySubtype;
    }
    // Possibly compatible, actual subtyping check will follow.
    if (IsNullSentinel(type2)) return Exactness::kExact;
  } else if (type2.is_exact()) {
    if (IsNullSentinel(type1)) return Exactness::kExact;
  }
  return Exactness::kAnySubtype;
}
References EquivalentIndices(), v8::internal::wasm::ValueTypeBase::is_exact(), IsNullSentinel(), v8::internal::wasm::kAnySubtype, v8::internal::wasm::kExact, and v8::internal::wasm::ValueType::ref_index().
Referenced by v8::internal::wasm::Union().
UpcastToStandardType()
StandardType v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::UpcastToStandardType (ValueTypeBase type)
Definition at line 121 of file wasm-subtyping.cc.
                                                      {
  if (!type.has_index()) return type.standard_type();
  switch (type.ref_type_kind()) {
    case RefTypeKind::kStruct:
      return StandardType::kStruct;
    case RefTypeKind::kArray:
      return StandardType::kArray;
    case RefTypeKind::kFunction:
      return StandardType::kFunc;
    case RefTypeKind::kCont:
      return StandardType::kCont;
    case RefTypeKind::kOther:
      UNREACHABLE();
  }
}
References v8::internal::wasm::kArray, v8::internal::wasm::kCont, v8::internal::wasm::kFunction, v8::internal::wasm::kOther, v8::internal::torque::ls::kStruct, v8::internal::wasm::kStruct, v8::internal::tracing::type, and v8::internal::UNREACHABLE().
Referenced by CommonAncestor(), CommonAncestorWithAbstract(), IsSubtypeOf_CommonImpl(), and NullSentinelImpl().
ValidArraySubtypeDefinition()
bool v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::ValidArraySubtypeDefinition (ModuleTypeIndex subtype_index, ModuleTypeIndex supertype_index, const WasmModule * module)
Definition at line 63 of file wasm-subtyping.cc.
                                                           {
  const ArrayType* sub_array = module->type(subtype_index).array_type;
  const ArrayType* super_array = module->type(supertype_index).array_type;
  bool sub_mut = sub_array->mutability();
  bool super_mut = super_array->mutability();
  return (sub_mut && super_mut &&
          EquivalentTypes(sub_array->element_type(),
                          super_array->element_type(), module)) ||
         (!sub_mut && !super_mut &&
          IsSubtypeOf(sub_array->element_type(), super_array->element_type(),
                      module));
}
References v8::internal::wasm::TypeDefinition::array_type, v8::internal::wasm::ArrayType::element_type(), v8::internal::wasm::EquivalentTypes(), v8::internal::wasm::IsSubtypeOf(), v8::internal::wasm::ArrayTypeBase::mutability(), and v8::internal::wasm::WasmModule::type().
Referenced by v8::internal::wasm::ValidSubtypeDefinition().
ValidContinuationSubtypeDefinition()
bool v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::ValidContinuationSubtypeDefinition (ModuleTypeIndex subtype_index, ModuleTypeIndex supertype_index, const WasmModule * module)
Definition at line 108 of file wasm-subtyping.cc.
                                                                  {
  const ContType* sub_cont = module->type(subtype_index).cont_type;
  const ContType* super_cont = module->type(supertype_index).cont_type;
  return IsHeapSubtypeOf(module->heap_type(sub_cont->contfun_typeindex()),
                         module->heap_type(super_cont->contfun_typeindex()),
                         module);
}
References v8::internal::wasm::TypeDefinition::cont_type, v8::internal::wasm::ContType::contfun_typeindex(), v8::internal::wasm::WasmModule::heap_type(), v8::internal::wasm::IsHeapSubtypeOf(), and v8::internal::wasm::WasmModule::type().
Referenced by v8::internal::wasm::ValidSubtypeDefinition().
ValidFunctionSubtypeDefinition()
bool v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::ValidFunctionSubtypeDefinition (ModuleTypeIndex subtype_index, ModuleTypeIndex supertype_index, const WasmModule * module)
Definition at line 79 of file wasm-subtyping.cc.
                                                              {
  const FunctionSig* sub_func = module->type(subtype_index).function_sig;
  const FunctionSig* super_func = module->type(supertype_index).function_sig;
  if (sub_func->parameter_count() != super_func->parameter_count() ||
      sub_func->return_count() != super_func->return_count()) {
    return false;
  }
  for (uint32_t i = 0; i < sub_func->parameter_count(); i++) {
    // Contravariance for params.
    if (!IsSubtypeOf(super_func->parameters()[i], sub_func->parameters()[i],
                     module)) {
      return false;
    }
  }
  for (uint32_t i = 0; i < sub_func->return_count(); i++) {
    // Covariance for returns.
    if (!IsSubtypeOf(sub_func->returns()[i], super_func->returns()[i],
                     module)) {
      return false;
    }
  }
  return true;
}
References v8::internal::wasm::TypeDefinition::function_sig, v8::internal::wasm::IsSubtypeOf(), v8::internal::Signature< T >::parameter_count(), v8::internal::Signature< T >::parameters(), v8::internal::Signature< T >::return_count(), v8::internal::Signature< T >::returns(), and v8::internal::wasm::WasmModule::type().
Referenced by v8::internal::wasm::ValidSubtypeDefinition().
ValidStructSubtypeDefinition()
bool v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::ValidStructSubtypeDefinition (ModuleTypeIndex subtype_index, ModuleTypeIndex supertype_index, const WasmModule * module)
Definition at line 20 of file wasm-subtyping.cc.
                                                            {
  const TypeDefinition& sub_def = module->type(subtype_index);
  const TypeDefinition& super_def = module->type(supertype_index);
  const StructType* sub_struct = sub_def.struct_type;
  const StructType* super_struct = super_def.struct_type;
  if (sub_struct->field_count() < super_struct->field_count()) {
    return false;
  }
  for (uint32_t i = 0; i < super_struct->field_count(); i++) {
    bool sub_mut = sub_struct->mutability(i);
    bool super_mut = super_struct->mutability(i);
    if (sub_mut != super_mut ||
        (sub_mut && !EquivalentTypes(sub_struct->field(i),
                                     super_struct->field(i), module)) ||
        (!sub_mut &&
         !IsSubtypeOf(sub_struct->field(i), super_struct->field(i), module))) {
      return false;
    }
  }
  if (sub_def.descriptor.valid()) {
    // If a type has a descriptor, its supertype must either have no descriptor,
    // or the supertype's descriptor must be a supertype of the subtype's
    // descriptor.
    if (super_def.descriptor.valid() &&
        !IsHeapSubtypeOf(module->heap_type(sub_def.descriptor),
                         module->heap_type(super_def.descriptor), module)) {
      return false;
    }
  } else {
    // If a type has no descriptor, its supertype must not have one either.
    if (super_def.descriptor.valid()) return false;
  }
  // A type and its supertype must either both be descriptors, or both not.
  if (sub_def.describes.valid() != super_def.describes.valid()) {
    return false;
  }
  return true;
}
References v8::internal::wasm::TypeDefinition::describes, v8::internal::wasm::TypeDefinition::descriptor, v8::internal::wasm::EquivalentTypes(), v8::internal::wasm::StructType::field(), v8::internal::wasm::StructTypeBase::field_count(), v8::internal::wasm::WasmModule::heap_type(), v8::internal::wasm::IsHeapSubtypeOf(), v8::internal::wasm::IsSubtypeOf(), v8::internal::wasm::StructTypeBase::mutability(), v8::internal::wasm::TypeDefinition::struct_type, v8::internal::wasm::WasmModule::type(), and v8::internal::wasm::TypeIndex::valid().
Referenced by v8::internal::wasm::ValidSubtypeDefinition().
Variable Documentation
kCommonAncestorLookupMap
constexpr std::array<std::array<StandardType, kNumNonTrivial>, kNumNonTrivial> v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::kCommonAncestorLookupMap [static], [constexpr]
Initial value:
= base::make_array<kNumNonTrivial>([](size_t sub) {
      return base::make_array<kNumNonTrivial>(
          [sub](size_t super) { return ComputeCommonAncestor(sub, super); });
    })
Definition at line 315 of file wasm-subtyping.cc.
Referenced by CommonAncestorLookup().
kCondensedIndexLookupMap
constexpr std::array<uint8_t, kNumStandardTypes> v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::kCondensedIndexLookupMap [static], [constexpr]
Initial value:
=
        base::make_array<kNumStandardTypes>([](size_t i) {
          return ComputeCondensedIndex(static_cast<StandardType>(i));
        })
Definition at line 235 of file wasm-subtyping.cc.
Referenced by CondensedIndex().
kCondensedToStandardMap
constexpr std::array<uint8_t, kNumNonTrivial> v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::kCondensedToStandardMap [static], [constexpr]
Initial value:
=
    base::make_array<kNumNonTrivial>(
        [](size_t i) { return static_cast<uint8_t>(ComputeStandardType(i)); })
Definition at line 239 of file wasm-subtyping.cc.
Referenced by CondensedToStandard().
kNotRelatedSentinel
constexpr uint8_t v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::kNotRelatedSentinel = 0xFF [static], [constexpr]
Definition at line 208 of file wasm-subtyping.cc.
Referenced by CommonAncestorLookup(), ComputeCondensedIndex(), and SubtypeLookup().
kNumNonTrivial
constexpr uint32_t v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::kNumNonTrivial [static], [constexpr]
Initial value:
=
#define CASE(name, ...)
        0
Definition at line 189 of file wasm-subtyping.cc.
kNumStandardTypes
constexpr uint32_t v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::kNumStandardTypes [static], [constexpr]
Initial value:
=
    value_type_impl::kNumberOfStandardTypes
Definition at line 159 of file wasm-subtyping.cc.
kSubtypeLookupMap2
constexpr std::array<std::array<bool, kNumNonTrivial>, kNumNonTrivial> v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::kSubtypeLookupMap2 [static], [constexpr]
Initial value:
= base::make_array<kNumNonTrivial>([](size_t sub) {
      return base::make_array<kNumNonTrivial>(
          [sub](size_t super) { return ComputeIsSubtype(sub, super); });
    })
Definition at line 273 of file wasm-subtyping.cc.
Referenced by ComputeCommonAncestor(), and SubtypeLookup().
kValueTypeLookupMap
constexpr std::array<GenericKind, kNumStandardTypes> v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::kValueTypeLookupMap [static], [constexpr]
Initial value:
= base::make_array<kNumStandardTypes>([](size_t i) {
#define ENTRY(name, ...)
      
      return GenericKind::kVoid;
    })
Definition at line 163 of file wasm-subtyping.cc.
Referenced by ToGenericKind().