v8::internal::anonymous_namespace{builtins-regexp.cc} Namespace Reference
Functions
constexpr uint8_t GetAsciiEscape (char c)
template<typename CharT >
MaybeDirectHandle< String > RegExpEscapeImpl (Isolate *isolate, base::OwnedVector< CharT > source)
Variables
constexpr uint8_t kNoEscape = 0
constexpr uint8_t kEscapeToHex = std::numeric_limits<uint8_t>::max()
constexpr const uint8_t kAsciiEscapes [128]
Function Documentation
GetAsciiEscape()
constexpr uint8_t v8::internal::anonymous_namespace{builtins-regexp.cc}::GetAsciiEscape (char c) [constexpr]
Definition at line 148 of file builtins-regexp.cc.
                                         {
  switch (c) {
    // SyntaxCharacter :: one of
    // ^ $ \ . * + ? () [ ] { } |
    //
    // SyntaxCharacter and U+002F (SOLIDUS) are escaped as-is.
    case '^':
    case '$':
    case '\\':
    case '.':
    case '*':
    case '+':
    case '?':
    case '(':
    case ')':
    case '[':
    case ']':
    case '{':
    case '}':
    case '|':
    case '/':
      return c;
    // ControlEscape :: one of
    // f n r t v
    case '\f':
      return 'f';
    case '\n':
      return 'n';
    case '\r':
      return 'r';
    case '\t':
      return 't';
    case '\v':
      return 'v';
    // One of ",-=<>#&!%:;@~'`", the code unit 0x0022 (QUOTATION MARK), and
    // ASCII whitespace are escaped to hex.
    case ',':
    case '-':
    case '=':
    case '<':
    case '>':
    case '#':
    case '&':
    case '!':
    case '%':
    case ':':
    case ';':
    case '@':
    case '~':
    case '\'':
    case '`':
    case '"':
    case ' ':
      return kEscapeToHex;
    default:
      return kNoEscape;
  }
}
References kEscapeToHex, and kNoEscape.
RegExpEscapeImpl()
template<typename CharT >
MaybeDirectHandle<String> v8::internal::anonymous_namespace{builtins-regexp.cc}::RegExpEscapeImpl (Isolate * isolate, base::OwnedVector< CharT > source)
Definition at line 217 of file builtins-regexp.cc.
                                                                          {
  char double_to_radix_chars[kDoubleToRadixMaxChars];
  base::Vector<char> double_to_radix_buffer =
      base::ArrayVector(double_to_radix_chars);
  // 2. Let escaped be the empty String.
  IncrementalStringBuilder escaped_builder(isolate);
  if constexpr (sizeof(CharT) == 2) {
    escaped_builder.ChangeEncoding();
  }
  // 3. Let cpList be StringToCodePoints(S).
  // 4. For each code point c of cpList, do
  // (Done below.)
  size_t start;
  std::remove_const_t<CharT> first_c = source[0];
  if (IsAlphaNumeric(first_c)) {
    // a. If escaped is the empty String and c is matched by either
    // DecimalDigit or AsciiLetter, then
    // i. NOTE: Escaping a leading digit ensures that output corresponds
    // with pattern text which may be used after a \0 character escape or
    // a DecimalEscape such as \1 and still match S rather than be
    // interpreted as an extension of the preceding escape sequence.
    // Escaping a leading ASCII letter does the same for the context after
    // \c.
    // ii. Let numericValue be the numeric value of c.
    // iii. Let hex be Number::toString(𝔽(numericValue), 16).
    // iv. Assert: The length of hex is 2.
    // v. Set escaped to the string-concatenation of the code unit 0x005C
    // (REVERSE SOLIDUS), "x", and hex.
    start = 1;
    escaped_builder.AppendCStringLiteral("\\x");
    std::string_view hex =
        DoubleToRadixStringView(first_c, 16, double_to_radix_buffer);
    escaped_builder.AppendString(hex);
  } else {
    start = 0;
  }
  // EncodeForRegExpEscape
  //
  // 1. If c is matched by SyntaxCharacter or c is U+002F (SOLIDUS), then a.
  // Return the string-concatenation of 0x005C (REVERSE SOLIDUS) and
  // UTF16EncodeCodePoint(c).
  // 2. Else if c is the code point listed in some cell of the “Code Point”
  // column of Table 63, then a. Return the string-concatenation of 0x005C
  // (REVERSE SOLIDUS) and the string in the “ControlEscape” column of the
  // row whose “Code Point” column contains c.
  // 3. Let otherPunctuators be the string-concatenation of ",-=<>#&!%:;@~'`"
  // and the code unit 0x0022 (QUOTATION MARK).
  // 4. Let toEscape be StringToCodePoints(otherPunctuators).
  // 5. If toEscape contains c, c is matched by either WhiteSpace or
  // LineTerminator, or c has the same numeric value as a leading surrogate
  // or trailing surrogate, then a. Let cNum be the numeric value of c. b. If
  // cNum ≤ 0xFF, then i. Let hex be Number::toString(𝔽(cNum), 16). ii.
  // Return the string-concatenation of the code unit 0x005C (REVERSE
  // SOLIDUS), "x", and StringPad(hex, 2, "0", start). c. Let escaped be the
  // empty String. d. Let codeUnits be UTF16EncodeCodePoint(c). e. For each
  // code unit cu of codeUnits, do i. Set escaped to the string-concatenation
  // of escaped and UnicodeEscape(cu). f. Return escaped.
  // 6. Return UTF16EncodeCodePoint(c).
  //
  // Steps 1-2 above are done by table lookup in kAsciiEscapes. For step 3,
  // matching otherPuncatuators, quotation mark, and ASCII whitespace is done by
  // table lookup in kAsciiEscapes. Non-ASCII whitespace and line terminators in
  // step 5 are matched manually below.
  for (size_t i = start; i < source.size(); i++) {
    CharT cu = source[i];
    base::uc32 cp = cu;
    uint8_t cmd = kNoEscape;
    if (IsAscii(cu)) {
      cmd = kAsciiEscapes[cu];
    } else {
      if constexpr (sizeof(CharT) == 2) {
        if (unibrow::Utf16::IsLeadSurrogate(cu)) {
          if (i + 1 < source.size() &&
              unibrow::Utf16::IsTrailSurrogate(source[i + 1])) {
            // Surrogate pair. Combine them.
            cp = unibrow::Utf16::CombineSurrogatePair(cu, source[i + 1]);
            i++;
          } else {
            // Lone lead surrogate.
            cmd = kEscapeToHex;
          }
        } else if (unibrow::Utf16::IsTrailSurrogate(cu)) {
          // Lone trailing surrogate.
          cmd = kEscapeToHex;
        }
      }
      // ASCII whitespace and line terminators are hardcoded in the
      // kAsciiEscapes table.
      if (IsWhiteSpaceOrLineTerminator(cp)) {
        cmd = kEscapeToHex;
      }
    }
    if (cmd == kNoEscape) {
      // Code point does not need to be escaped.
      if (cp == cu) {
        escaped_builder.Append<CharT, CharT>(cp);
      } else {
        DCHECK_LT(i, source.size());
        DCHECK(unibrow::Utf16::IsSurrogatePair(cu, source[i]));
        DCHECK_EQ(cp, unibrow::Utf16::CombineSurrogatePair(cu, source[i]));
        escaped_builder.Append<CharT, CharT>(cu);
        escaped_builder.Append<CharT, CharT>(source[i]);
      }
    } else if (cmd == kEscapeToHex) {
      // An escape to hex. Output \x or \u depending on how many code units.
      escaped_builder.AppendCStringLiteral(cp <= 0xFF ? "\\x" : "\\u");
      std::string_view hex =
          DoubleToRadixStringView(cp, 16, double_to_radix_buffer);
      escaped_builder.AppendString(hex);
    } else {
      // A manual, non-hex escape. See table in kAsciiEscapes.
      escaped_builder.AppendCharacter('\\');
      escaped_builder.AppendCharacter(cmd);
    }
  }
  return escaped_builder.Finish();
}
References v8::internal::IncrementalStringBuilder::Append(), v8::internal::IncrementalStringBuilder::AppendCharacter(), v8::internal::IncrementalStringBuilder::AppendCStringLiteral(), v8::internal::IncrementalStringBuilder::AppendString(), v8::base::ArrayVector(), v8::internal::IncrementalStringBuilder::ChangeEncoding(), unibrow::Utf16::CombineSurrogatePair(), v8::internal::cp, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LT, v8::internal::DoubleToRadixStringView(), v8::internal::IncrementalStringBuilder::Finish(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::IsAlphaNumeric(), v8::internal::IsAscii(), unibrow::Utf16::IsLeadSurrogate(), unibrow::Utf16::IsSurrogatePair(), unibrow::Utf16::IsTrailSurrogate(), v8::internal::IsWhiteSpaceOrLineTerminator(), kAsciiEscapes, v8::internal::kDoubleToRadixMaxChars, kEscapeToHex, kNoEscape, and v8::base::OwnedVector< T >::size().
Referenced by v8::internal::BUILTIN().
Variable Documentation
kAsciiEscapes
constexpr const uint8_t v8::internal::anonymous_namespace{builtins-regexp.cc}::kAsciiEscapes[128] [constexpr]
Initial value:
{
#define GET_ASCII_ESCAPE(c)
}
Definition at line 210 of file builtins-regexp.cc.
Referenced by RegExpEscapeImpl().
kEscapeToHex
constexpr uint8_t v8::internal::anonymous_namespace{builtins-regexp.cc}::kEscapeToHex = std::numeric_limits<uint8_t>::max() [constexpr]
Definition at line 147 of file builtins-regexp.cc.
Referenced by GetAsciiEscape(), and RegExpEscapeImpl().
kNoEscape
constexpr uint8_t v8::internal::anonymous_namespace{builtins-regexp.cc}::kNoEscape = 0 [constexpr]
Definition at line 146 of file builtins-regexp.cc.
Referenced by GetAsciiEscape(), and RegExpEscapeImpl().