v8::internal::compiler::anonymous_namespace{turbofan-graph-visualizer.cc} Namespace Reference
Functions
void JsonPrintInlinedFunctionInfo (std::ostream &os, int source_id, int inlining_id, const OptimizedCompilationInfo::InlinedFunctionHolder &h)
void PrintIndent (std::ostream &os, int indent)
void PrintScheduledNode (std::ostream &os, int indent, Node *n)
void PrintScheduledGraph (std::ostream &os, const Schedule *schedule)
Function Documentation
JsonPrintInlinedFunctionInfo()
void v8::internal::compiler::anonymous_namespace{turbofan-graph-visualizer.cc}::JsonPrintInlinedFunctionInfo (std::ostream & os, int source_id, int inlining_id, const OptimizedCompilationInfo::InlinedFunctionHolder & h)
Definition at line 165 of file turbofan-graph-visualizer.cc.
                                                            {
  os << "\"" << inlining_id << "\" : ";
  os << "{ \"inliningId\" : " << inlining_id;
  os << ", \"sourceId\" : " << source_id;
  const SourcePosition position = h.position.position;
  if (position.IsKnown()) {
    os << ", \"inliningPosition\" : " << AsJSON(position);
  }
  os << "}";
}
References v8::internal::compiler::AsJSON(), h(), and v8::internal::SourcePosition::IsKnown().
Referenced by v8::internal::compiler::JsonPrintAllSourceWithPositions().
PrintIndent()
void v8::internal::compiler::anonymous_namespace{turbofan-graph-visualizer.cc}::PrintIndent (std::ostream & os, int indent)
Definition at line 977 of file turbofan-graph-visualizer.cc.
                                             {
  os << " ";
  for (int i = 0; i < indent; i++) {
    os << ". ";
  }
}
Referenced by PrintScheduledGraph(), and PrintScheduledNode().
PrintScheduledGraph()
void v8::internal::compiler::anonymous_namespace{turbofan-graph-visualizer.cc}::PrintScheduledGraph (std::ostream & os, const Schedule * schedule)
Definition at line 1000 of file turbofan-graph-visualizer.cc.
                                                                   {
  const BasicBlockVector* rpo = schedule->rpo_order();
  for (size_t i = 0; i < rpo->size(); i++) {
    BasicBlock* current = (*rpo)[i];
    int indent = current->loop_depth();
    os << " + Block B" << current->rpo_number() << " (pred:";
    for (BasicBlock* predecessor : current->predecessors()) {
      os << " B" << predecessor->rpo_number();
    }
    if (current->IsLoopHeader()) {
      os << ", loop until B" << current->loop_end()->rpo_number();
    } else if (current->loop_header()) {
      os << ", in loop B" << current->loop_header()->rpo_number();
    }
    os << ")" << std::endl;
    for (BasicBlock::const_iterator it = current->begin(); it != current->end();
         ++it) {
      Node* node = *it;
      PrintScheduledNode(os, indent, node);
      os << std::endl;
    }
    if (current->SuccessorCount() > 0) {
      if (current->control_input() != nullptr) {
        PrintScheduledNode(os, indent, current->control_input());
      } else {
        PrintIndent(os, indent);
        os << "Goto";
      }
      os << " ->";
      bool isFirst = true;
      for (BasicBlock* successor : current->successors()) {
        if (isFirst) {
          isFirst = false;
        } else {
          os << ",";
        }
        os << " B" << successor->rpo_number();
      }
      os << std::endl;
    } else {
      DCHECK_NULL(current->control_input());
    }
  }
}
References v8::internal::compiler::BasicBlock::begin(), v8::internal::compiler::BasicBlock::control_input(), DCHECK_NULL, v8::internal::compiler::BasicBlock::end(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::BasicBlock::IsLoopHeader(), v8::internal::compiler::BasicBlock::loop_depth(), v8::internal::compiler::BasicBlock::loop_end(), v8::internal::compiler::BasicBlock::loop_header(), v8::internal::compiler::BasicBlock::predecessors(), PrintIndent(), PrintScheduledNode(), v8::internal::compiler::BasicBlock::rpo_number(), v8::internal::compiler::Schedule::rpo_order(), v8::internal::ZoneVector< T >::size(), v8::internal::compiler::BasicBlock::SuccessorCount(), and v8::internal::compiler::BasicBlock::successors().
Referenced by v8::internal::compiler::operator<<().
PrintScheduledNode()
void v8::internal::compiler::anonymous_namespace{turbofan-graph-visualizer.cc}::PrintScheduledNode (std::ostream & os, int indent, Node * n)
Definition at line 984 of file turbofan-graph-visualizer.cc.
                                                             {
  PrintIndent(os, indent);
  os << "#" << n->id() << ":" << *n->op() << "(";
  // Print the inputs.
  int j = 0;
  for (Node* const i : n->inputs()) {
    if (j++ > 0) os << ", ";
    os << "#" << SafeId(i) << ":" << SafeMnemonic(i);
  }
  os << ")";
  // Print the node type, if any.
  if (NodeProperties::IsTyped(n)) {
    os << " [Type: " << NodeProperties::GetType(n) << "]";
  }
}
References v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::Node::id(), v8::internal::compiler::Node::inputs(), v8::internal::compiler::NodeProperties::IsTyped(), v8::internal::compiler::Node::op(), PrintIndent(), v8::internal::compiler::SafeId(), and v8::internal::compiler::SafeMnemonic().
Referenced by PrintScheduledGraph().