v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc} Namespace Reference
Functions
void VisitWordCompare (InstructionSelector *selector, OpIndex node, FlagsContinuation *cont)
void VisitAtomicLoad (InstructionSelector *selector, OpIndex node, ArchOpcode opcode, AtomicWidth width)
void VisitAtomicStore (InstructionSelector *selector, OpIndex node, ArchOpcode opcode, AtomicWidth width)
void VisitAtomicBinop (InstructionSelector *selector, OpIndex node, ArchOpcode opcode)
void VisitWord32PairShift (InstructionSelector *selector, InstructionCode opcode, OpIndex node)
Function Documentation
VisitAtomicBinop()
void v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitAtomicBinop (InstructionSelector * selector, OpIndex node, ArchOpcode opcode)
Definition at line 799 of file instruction-selector-riscv32.cc.
                                         {
  RiscvOperandGenerator g(selector);
  using OpIndex = OpIndex;
  const AtomicRMWOp& atomic_op = selector->Cast<AtomicRMWOp>(node);
  OpIndex base = atomic_op.base();
  OpIndex index = atomic_op.index();
  OpIndex value = atomic_op.value();
  AddressingMode addressing_mode = kMode_MRI;
  InstructionOperand inputs[3];
  size_t input_count = 0;
  inputs[input_count++] = g.UseUniqueRegister(base);
  inputs[input_count++] = g.UseUniqueRegister(index);
  inputs[input_count++] = g.UseUniqueRegister(value);
  InstructionOperand outputs[1];
  outputs[0] = g.UseUniqueRegister(node);
  InstructionOperand temps[4];
  temps[0] = g.TempRegister();
  temps[1] = g.TempRegister();
  temps[2] = g.TempRegister();
  temps[3] = g.TempRegister();
  InstructionCode code = opcode | AddressingModeField::encode(addressing_mode);
  selector->Emit(code, 1, outputs, input_count, inputs, 4, temps);
}
References v8::internal::compiler::turboshaft::AtomicRMWOp::base(), v8::internal::compiler::turboshaft::OperationMatcher::Cast(), code, v8::internal::compiler::InstructionSelector::Emit(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::turboshaft::AtomicRMWOp::index(), v8::internal::index, v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::turboshaft::OpIndex, v8::internal::compiler::OperandGenerator::TempRegister(), v8::internal::compiler::OperandGenerator::UseUniqueRegister(), v8::internal::compiler::turboshaft::AtomicRMWOp::value(), and v8::internal::value.
VisitAtomicLoad()
void v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitAtomicLoad (InstructionSelector * selector, OpIndex node, ArchOpcode opcode, AtomicWidth width)
Definition at line 750 of file instruction-selector-riscv32.cc.
                                                           {
  using OpIndex = OpIndex;
  RiscvOperandGenerator g(selector);
  auto load = selector->load_view(node);
  OpIndex base = load.base();
  OpIndex index = load.index();
  if (g.CanBeImmediate(index, opcode)) {
    selector->Emit(opcode | AddressingModeField::encode(kMode_MRI) |
                       AtomicWidthField::encode(width),
                   g.DefineAsRegister(node), g.UseRegister(base),
                   g.UseImmediate(index));
  } else {
    InstructionOperand addr_reg = g.TempRegister();
    selector->Emit(kRiscvAdd32 | AddressingModeField::encode(kMode_None),
                   addr_reg, g.UseRegister(index), g.UseRegister(base));
    // Emit desired load opcode, using temp addr_reg.
    selector->Emit(opcode | AddressingModeField::encode(kMode_MRI) |
                       AtomicWidthField::encode(width),
                   g.DefineAsRegister(node), addr_reg, g.TempImmediate(0));
  }
}
References v8::internal::compiler::RiscvOperandGenerator::CanBeImmediate(), v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::InstructionSelector::Emit(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::index, v8::internal::compiler::InstructionSelector::load_view(), v8::internal::compiler::turboshaft::OpIndex, v8::internal::compiler::OperandGenerator::TempImmediate(), v8::internal::compiler::OperandGenerator::TempRegister(), v8::internal::compiler::OperandGenerator::UseImmediate(), and v8::internal::compiler::OperandGenerator::UseRegister().
VisitAtomicStore()
void v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitAtomicStore (InstructionSelector * selector, OpIndex node, ArchOpcode opcode, AtomicWidth width)
Definition at line 773 of file instruction-selector-riscv32.cc.
                                                            {
  RiscvOperandGenerator g(selector);
  using OpIndex = OpIndex;
  auto store = selector->store_view(node);
  OpIndex base = store.base();
  OpIndex index = store.index().value();
  OpIndex value = store.value();
  if (g.CanBeImmediate(index, opcode)) {
    selector->Emit(opcode | AddressingModeField::encode(kMode_MRI) |
                       AtomicWidthField::encode(width),
                   g.NoOutput(), g.UseRegisterOrImmediateZero(value),
                   g.UseRegister(base), g.UseImmediate(index));
  } else {
    InstructionOperand addr_reg = g.TempRegister();
    selector->Emit(kRiscvAdd32 | AddressingModeField::encode(kMode_None),
                   addr_reg, g.UseRegister(index), g.UseRegister(base));
    // Emit desired store opcode, using temp addr_reg.
    selector->Emit(opcode | AddressingModeField::encode(kMode_MRI) |
                       AtomicWidthField::encode(width),
                   g.NoOutput(), g.UseRegisterOrImmediateZero(value), addr_reg,
                   g.TempImmediate(0));
  }
}
References v8::internal::compiler::RiscvOperandGenerator::CanBeImmediate(), v8::internal::compiler::InstructionSelector::Emit(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::index, v8::internal::compiler::OperandGenerator::NoOutput(), v8::internal::compiler::turboshaft::OpIndex, store(), v8::internal::compiler::InstructionSelector::store_view(), v8::internal::compiler::OperandGenerator::TempImmediate(), v8::internal::compiler::OperandGenerator::TempRegister(), v8::internal::compiler::OperandGenerator::UseImmediate(), v8::internal::compiler::OperandGenerator::UseRegister(), v8::internal::compiler::RiscvOperandGenerator::UseRegisterOrImmediateZero(), and v8::internal::value.
VisitWord32PairShift()
void v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitWord32PairShift (InstructionSelector * selector, InstructionCode opcode, OpIndex node)
Definition at line 1297 of file instruction-selector-riscv32.cc.
                                        {
  RiscvOperandGenerator g(selector);
  const Word32PairBinopOp& pair_binop = selector->Cast<Word32PairBinopOp>(node);
  // We use g.UseUniqueRegister here to guarantee that there is
  // no register aliasing of input registers with output registers.
  InstructionOperand shift_operand;
  OpIndex shift_by = pair_binop.right_low();
  int64_t unused;
  if (selector->MatchSignedIntegralConstant(shift_by, &unused)) {
    shift_operand = g.UseImmediate(shift_by);
  } else {
    shift_operand = g.UseUniqueRegister(shift_by);
  }
  InstructionOperand inputs[] = {g.UseUniqueRegister(pair_binop.left_low()),
                                 g.UseUniqueRegister(pair_binop.left_high()),
                                 shift_operand};
  OptionalOpIndex projection1 = selector->FindProjection(node, 1);
  InstructionOperand outputs[2];
  InstructionOperand temps[1];
  int32_t output_count = 0;
  int32_t temp_count = 0;
  outputs[output_count++] = g.DefineAsRegister(node);
  if (projection1.valid()) {
    outputs[output_count++] = g.DefineAsRegister(projection1.value());
  } else {
    temps[temp_count++] = g.TempRegister();
  }
  selector->Emit(opcode, output_count, outputs, 3, inputs, temp_count, temps);
}
References v8::internal::compiler::turboshaft::OperationMatcher::Cast(), v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::InstructionSelector::Emit(), v8::internal::compiler::InstructionSelector::FindProjection(), v8::internal::compiler::turboshaft::Word32PairBinopOp::left_high(), v8::internal::compiler::turboshaft::Word32PairBinopOp::left_low(), v8::internal::compiler::turboshaft::OperationMatcher::MatchSignedIntegralConstant(), v8::internal::compiler::turboshaft::Word32PairBinopOp::right_low(), v8::internal::compiler::OperandGenerator::TempRegister(), v8::internal::compiler::OperandGenerator::UseImmediate(), v8::internal::compiler::OperandGenerator::UseUniqueRegister(), v8::internal::compiler::turboshaft::OptionalOpIndex::valid(), and v8::internal::compiler::turboshaft::OptionalOpIndex::value().
VisitWordCompare()
void v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitWordCompare (InstructionSelector * selector, OpIndex node, FlagsContinuation * cont)
Definition at line 745 of file instruction-selector-riscv32.cc.
                                               {
  VisitWordCompare(selector, node, kRiscvCmp, cont, false);
}
References v8::internal::compiler::VisitWordCompare().