v8::anonymous_namespace{d8.cc} Namespace Reference
Classes
class ArrayBufferAllocatorBase
class ShellArrayBufferAllocator
class MockArrayBufferAllocator
class MockArrayBufferAllocatiorWithLimit
class ModuleEmbedderData
class D8WasmAsyncResolvePromiseTask
Enumerations
enum { kModuleEmbedderDataIndex
, kInspectorClientIndex
 }
enum ModuleResolutionDataIndex : uint32_t { kResolver = 0
, kNamespaceOrSource = 1
 }
Functions
template<int N>
void ThrowError (Isolate *isolate, const char(&message)[N])
void ThrowError (Isolate *isolate, Local< String > message)
void ThrowException (Isolate *isolate, Local< Value > exception)
static MaybeLocal< Value > TryGetValue (v8::Isolate *isolate, Local< Context > context, Local< v8::Object > object, const char *property)
static Local< Value > GetValue (v8::Isolate *isolate, Local< Context > context, Local< v8::Object > object, const char *property)
std::shared_ptr< Worker > GetWorkerFromInternalField (Isolate *isolate, Local< Object > object)
base::Thread::Options GetThreadOptions (const char *name)
template<class T >
MaybeLocal< T > CompileStreamed (Local< Context > context, ScriptCompiler::StreamedSource *v8_source, Local< String > full_source_string, const ScriptOrigin &origin)
template<> MaybeLocal< Script > CompileStreamed (Local< Context > context, ScriptCompiler::StreamedSource *v8_source, Local< String > full_source_string, const ScriptOrigin &origin)
template<class T >
MaybeLocal< T > Compile (Local< Context > context, ScriptCompiler::Source *source, ScriptCompiler::CompileOptions options)
template<> MaybeLocal< Script > Compile (Local< Context > context, ScriptCompiler::Source *source, ScriptCompiler::CompileOptions options)
std::string ToSTLString (Isolate *isolate, Local< String > v8_str)
std::shared_ptr< ModuleEmbedderData > InitializeModuleEmbedderData (Local< Context > context)
std::shared_ptr< ModuleEmbedderData > GetModuleDataFromContext (Local< Context > context)
ScriptOrigin CreateScriptOrigin (Isolate *isolate, Local< String > resource_name, v8::ScriptType type)
bool IsValidHostDefinedOptions (Local< Context > context, Local< Data > options, Local< Value > resource_name)
void D8WasmAsyncResolvePromiseCallback (v8::Isolate *isolate, v8::Local< v8::Context > context, v8::Local< v8::Promise::Resolver > resolver, v8::Local< v8::Value > result, WasmAsyncSuccess success)
bool IsAbsolutePath (const std::string &path)
std::string GetWorkingDirectory ()
std::string DirName (const std::string &path)
std::string NormalizePath (const std::string &path, const std::string &dir_name)
std::string NormalizeModuleSpecifier (const std::string &specifier, const std::string &dir_name)
MaybeLocal< Module > ResolveModuleCallback (Local< Context > context, Local< String > specifier, Local< FixedArray > import_attributes, Local< Module > referrer)
MaybeLocal< Object > ResolveModuleSourceCallback (Local< Context > context, Local< String > specifier, Local< FixedArray > import_attributes, Local< Module > referrer)
void RejectPromiseIfExecutionIsNotTerminating (Isolate *isolate, Local< Context > realm, Local< Promise::Resolver > resolver, const TryCatch &try_catch)
Maybe< bool > ChainDynamicImportPromise (Isolate *isolate, Local< Context > realm, v8::Local< v8::Promise::Resolver > resolver, Local< Promise > result_promise, Local< Value > namespace_or_source)
bool SkipTerminationForFuzzing ()
int LineFromOffset (Local< debug::Script > script, int offset)
void WriteLcovDataForRange (std::vector< uint32_t > *lines, int start_line, int end_line, uint32_t count)
void WriteLcovDataForNamedRange (std::ostream &sink, std::vector< uint32_t > *lines, const std::string &name, int start_line, int end_line, uint32_t count)
bool FlagMatches (const char *flag, char **arg, bool keep_flag=false)
template<size_t N>
bool FlagWithArgMatches (const char(&flag)[N], char **flag_value, int argc, char *argv[], int *i)
bool ProcessMessages (Isolate *isolate, const std::function< platform::MessageLoopBehavior()> &behavior)
void d8_install_sigterm_handler ()
Variables
thread_local Worker * current_worker_ = nullptr
bool fuzzilli_reprl = false
v8::Platform * g_default_platform
std::unique_ptr< v8::Platform > g_platform
const int kHostDefinedOptionsLength = 2
const uint32_t kHostDefinedOptionsMagicConstant = 0xF1F2F3F0
const char kDataURLPrefix [] = `data:text/javascript,`
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
kModuleEmbedderDataIndex
kInspectorClientIndex
Definition at line 833 of file d8.cc.
{ kModuleEmbedderDataIndex, kInspectorClientIndex };
ModuleResolutionDataIndex
enum v8::anonymous_namespace{d8.cc}::ModuleResolutionDataIndex : uint32_t
Enumerator
kResolver
kNamespaceOrSource
Definition at line 1477 of file d8.cc.
                               : uint32_t {
  kResolver = 0,
  kNamespaceOrSource = 1,
};
Function Documentation
ChainDynamicImportPromise()
Maybe<bool> v8::anonymous_namespace{d8.cc}::ChainDynamicImportPromise (Isolate * isolate, Local< Context > realm, v8::Local< v8::Promise::Resolver > resolver, Local< Promise > result_promise, Local< Value > namespace_or_source)
Definition at line 1612 of file d8.cc.
                                                                        {
  Local<Array> module_resolution_data = v8::Array::New(isolate);
  if (module_resolution_data->SetPrototypeV2(realm, v8::Null(isolate))
          .IsNothing()) {
    return Nothing<bool>();
  }
  if (module_resolution_data
          ->Set(realm, ModuleResolutionDataIndex::kResolver, resolver)
          .IsNothing()) {
    return Nothing<bool>();
  }
  if (module_resolution_data
          ->Set(realm, ModuleResolutionDataIndex::kNamespaceOrSource,
                namespace_or_source)
          .IsNothing()) {
    return Nothing<bool>();
  }
  Local<Function> callback_success;
  if (!Function::New(realm, Shell::ModuleResolutionSuccessCallback,
                     module_resolution_data)
           .ToLocal(&callback_success)) {
    return Nothing<bool>();
  }
  Local<Function> callback_failure;
  if (!Function::New(realm, Shell::ModuleResolutionFailureCallback,
                     module_resolution_data)
           .ToLocal(&callback_failure)) {
    return Nothing<bool>();
  }
  if (result_promise->Then(realm, callback_success, callback_failure)
          .IsEmpty()) {
    return Nothing<bool>();
  }
  return Just(true);
}
References v8::Just(), kNamespaceOrSource, kResolver, v8::Shell::ModuleResolutionFailureCallback(), v8::Shell::ModuleResolutionSuccessCallback(), v8::Array::New(), v8::Function::New(), and v8::Null().
Referenced by v8::Shell::DoHostImportModuleDynamically().
Compile() [1/2]
template<class T >
MaybeLocal<T> v8::anonymous_namespace{d8.cc}::Compile (Local< Context > context, ScriptCompiler::Source * source, ScriptCompiler::CompileOptions options)
Definition at line 669 of file d8.cc.
                                                            {}
Referenced by v8::internal::ExperimentalRegExpCompiler::Compile(), and v8::internal::RegExpImpl::CompileIrregexp().
Compile() [2/2]
template<>
MaybeLocal< Module > v8::anonymous_namespace{d8.cc}::Compile (Local< Context > context, ScriptCompiler::Source * source, ScriptCompiler::CompileOptions options)
Definition at line 672 of file d8.cc.
                                                                 {
  return ScriptCompiler::Compile(context, source, options);
}
References v8::ScriptCompiler::Compile().
CompileStreamed() [1/2]
template<class T >
MaybeLocal<T> v8::anonymous_namespace{d8.cc}::CompileStreamed (Local< Context > context, ScriptCompiler::StreamedSource * v8_source, Local< String > full_source_string, const ScriptOrigin & origin)
Definition at line 645 of file d8.cc.
                                                          {}
CompileStreamed() [2/2]
template<>
MaybeLocal< Module > v8::anonymous_namespace{d8.cc}::CompileStreamed (Local< Context > context, ScriptCompiler::StreamedSource * v8_source, Local< String > full_source_string, const ScriptOrigin & origin)
Definition at line 651 of file d8.cc.
                                                               {
  return ScriptCompiler::Compile(context, v8_source, full_source_string,
                                 origin);
}
References v8::ScriptCompiler::Compile().
CreateScriptOrigin()
ScriptOrigin v8::anonymous_namespace{d8.cc}::CreateScriptOrigin (Isolate * isolate, Local< String > resource_name, v8::ScriptType type)
Definition at line 859 of file d8.cc.
                                                   {
  Local<PrimitiveArray> options =
      PrimitiveArray::New(isolate, kHostDefinedOptionsLength);
  options->Set(isolate, 0,
               v8::Uint32::New(isolate, kHostDefinedOptionsMagicConstant));
  options->Set(isolate, 1, resource_name);
  return ScriptOrigin(resource_name, 0, 0, false, -1, Local<Value>(), false,
                      false, type == v8::ScriptType::kModule, options);
}
References kHostDefinedOptionsLength, kHostDefinedOptionsMagicConstant, v8::kModule, v8::PrimitiveArray::New(), v8::Integer::New(), and v8::internal::tracing::type.
Referenced by v8::Shell::ExecuteString(), v8::Shell::FetchModuleTree(), and v8::Shell::RealmEval().
d8_install_sigterm_handler()
void v8::anonymous_namespace{d8.cc}::d8_install_sigterm_handler ()
Definition at line 6656 of file d8.cc.
                                  {
#ifdef V8_OS_POSIX
  CHECK(!i::v8_flags.fuzzing);
  struct sigaction sa;
  sa.sa_sigaction = d8_sigterm_handler;
  sigemptyset(&sa.sa_mask);
  sa.sa_flags = 0;
  if (sigaction(SIGTERM, &sa, NULL) == -1) {
    FATAL("Could not install SIGTERM handler");
  }
#endif // V8_OS_POSIX
}
References CHECK, FATAL, and v8::internal::v8_flags.
Referenced by v8::Shell::Main().
D8WasmAsyncResolvePromiseCallback()
void v8::anonymous_namespace{d8.cc}::D8WasmAsyncResolvePromiseCallback (v8::Isolate * isolate, v8::Local< v8::Context > context, v8::Local< v8::Promise::Resolver > resolver, v8::Local< v8::Value > result, WasmAsyncSuccess success)
Definition at line 921 of file d8.cc.
                              {
  // We have to resolve the promise in a separate task which is not a cancelable
  // task, to avoid a deadlock when {quit()} is called in the then-handler of
  // the result promise.
  g_platform->GetForegroundTaskRunner(isolate)->PostTask(
      std::make_unique<D8WasmAsyncResolvePromiseTask>(
          isolate, context, resolver, result, success));
}
References g_platform, and v8::base::internal::result.
Referenced by v8::Shell::Initialize().
DirName()
std::string v8::anonymous_namespace{d8.cc}::DirName (const std::string & path)
Definition at line 1089 of file d8.cc.
                                         {
  if (path.starts_with(kDataURLPrefix)) return GetWorkingDirectory();
  DCHECK(IsAbsolutePath(path));
  size_t last_slash = path.find_last_of('/');
  DCHECK(last_slash != std::string::npos);
  return path.substr(0, last_slash);
}
References DCHECK, GetWorkingDirectory(), IsAbsolutePath(), and kDataURLPrefix.
Referenced by v8::Shell::DoHostImportModuleDynamically(), v8::Shell::FetchModuleTree(), ResolveModuleCallback(), and ResolveModuleSourceCallback().
FlagMatches()
bool v8::anonymous_namespace{d8.cc}::FlagMatches (const char * flag, char ** arg, bool keep_flag = false)
Definition at line 5795 of file d8.cc.
                                                                       {
  if (strcmp(*arg, flag) == 0) {
    if (!keep_flag) {
      *arg = nullptr;
    }
    return true;
  }
  return false;
}
Referenced by v8::Shell::SetOptions().
FlagWithArgMatches()
template<size_t N>
bool v8::anonymous_namespace{d8.cc}::FlagWithArgMatches (const char(&) flag[N], char ** flag_value, int argc, char * argv[], int * i)
Definition at line 5806 of file d8.cc.
                                              {
  char* current_arg = argv[*i];
  // Compare the flag up to the last character of the flag name (not including
  // the null terminator).
  if (strncmp(current_arg, flag, N - 1) == 0) {
    // Match against --flag=value
    if (current_arg[N - 1] == '=') {
      *flag_value = argv[*i] + N;
      argv[*i] = nullptr;
      return true;
    }
    // Match against --flag value
    if (current_arg[N - 1] == '\0') {
      CHECK_LT(*i, argc - 1);
      argv[*i] = nullptr;
      (*i)++;
      *flag_value = argv[*i];
      argv[*i] = nullptr;
      return true;
    }
  }
  flag_value = nullptr;
  return false;
}
References CHECK_LT, v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::N.
Referenced by v8::Shell::SetOptions().
GetModuleDataFromContext()
std::shared_ptr<ModuleEmbedderData> v8::anonymous_namespace{d8.cc}::GetModuleDataFromContext (Local< Context > context)
Definition at line 849 of file d8.cc.
                            {
  v8::Local<v8::Value> module_data =
      context->GetEmbedderData(kModuleEmbedderDataIndex);
  i::DirectHandle<i::Managed<ModuleEmbedderData>> module_data_managed =
      i::Cast<i::Managed<ModuleEmbedderData>>(
          Utils::OpenDirectHandle<Value, i::Object>(module_data));
  return module_data_managed->get();
}
References v8::Context::GetEmbedderData(), and kModuleEmbedderDataIndex.
Referenced by v8::Shell::DoHostImportModuleDynamically(), v8::Shell::ExecuteModule(), v8::Shell::ExecuteString(), v8::Shell::FetchModuleSource(), v8::Shell::FetchModuleTree(), v8::Shell::HostCreateShadowRealmContext(), v8::Shell::HostInitializeImportMetaObject(), v8::Shell::JSONModuleEvaluationSteps(), ResolveModuleCallback(), and ResolveModuleSourceCallback().
GetThreadOptions()
base::Thread::Options v8::anonymous_namespace{d8.cc}::GetThreadOptions (const char * name)
Definition at line 439 of file d8.cc.
                                                     {
  // On some systems (OSX 10.6) the stack size default is 0.5Mb or less
  // which is not enough to parse the big literal expressions used in tests.
  // The stack size should be at least StackGuard::kLimitSize + some
  // OS-specific padding for thread startup code. 2Mbytes seems to be enough.
  return base::Thread::Options(name, 2 * i::MB);
}
References MB, and name.
GetValue()
static Local<Value> v8::anonymous_namespace{d8.cc}::GetValue (v8::Isolate * isolate, Local< Context > context, Local< v8::Object > object, const char * property) [static]
Definition at line 417 of file d8.cc.
                                                                           {
  return TryGetValue(isolate, context, object, property).ToLocalChecked();
}
References v8::MaybeLocal< T >::ToLocalChecked(), and TryGetValue().
Referenced by v8::tracing::anonymous_namespace{d8.cc}::TraceConfigParser::FillTraceConfig(), and v8::tracing::anonymous_namespace{d8.cc}::TraceConfigParser::UpdateIncludedCategoriesList().
GetWorkerFromInternalField()
std::shared_ptr<Worker> v8::anonymous_namespace{d8.cc}::GetWorkerFromInternalField (Isolate * isolate, Local< Object > object)
Definition at line 422 of file d8.cc.
                                                                         {
  if (object->InternalFieldCount() != 1) {
    ThrowError(isolate, "this is not a Worker");
    return nullptr;
  }
  i::DirectHandle<i::Object> handle =
      Utils::OpenDirectHandle(*object->GetInternalField(0));
  if (IsSmi(*handle)) {
    ThrowError(isolate, "Worker is defunct because main thread is terminating");
    return nullptr;
  }
  auto managed = i::Cast<i::Managed<Worker>>(handle);
  return managed->get();
}
References v8::Object::GetInternalField(), v8::internal::handle(), v8::Object::InternalFieldCount(), v8::internal::IsSmi(), v8::Utils::OpenDirectHandle(), and ThrowError().
Referenced by v8::Shell::WorkerGetMessage(), v8::Shell::WorkerOnMessageGetter(), v8::Shell::WorkerOnMessageSetter(), v8::Shell::WorkerPostMessage(), v8::Shell::WorkerTerminate(), and v8::Shell::WorkerTerminateAndWait().
GetWorkingDirectory()
std::string v8::anonymous_namespace{d8.cc}::GetWorkingDirectory ()
Definition at line 1073 of file d8.cc.
                                {
#if defined(V8_OS_WIN)
  char system_buffer[MAX_PATH];
  // Unicode paths are unsupported, which is fine as long as
  // the test directory doesn't include any such paths.
  DWORD len = GetCurrentDirectoryA(MAX_PATH, system_buffer);
  CHECK_GT(len, 0);
  return system_buffer;
#else
  char curdir[PATH_MAX];
  CHECK_NOT_NULL(getcwd(curdir, PATH_MAX));
  return curdir;
#endif
}
References CHECK_GT, and CHECK_NOT_NULL.
Referenced by DirName(), v8::Shell::DoHostImportModuleDynamically(), v8::Shell::ExecuteModule(), v8::Shell::LoadJSON(), and v8::Shell::WriteLcovData().
InitializeModuleEmbedderData()
std::shared_ptr<ModuleEmbedderData> v8::anonymous_namespace{d8.cc}::InitializeModuleEmbedderData (Local< Context > context)
Definition at line 835 of file d8.cc.
                            {
  i::Isolate* i_isolate = i::Isolate::Current();
  const size_t kModuleEmbedderDataEstimate = 4 * 1024; // module map.
  i::DirectHandle<i::Managed<ModuleEmbedderData>> module_data_managed =
      i::Managed<ModuleEmbedderData>::From(
          i_isolate, kModuleEmbedderDataEstimate,
          std::make_shared<ModuleEmbedderData>(
              reinterpret_cast<v8::Isolate*>(i_isolate)));
  v8::Local<v8::Value> module_data = Utils::ToLocal(module_data_managed);
  context->SetEmbedderData(kModuleEmbedderDataIndex, module_data);
  return module_data_managed->get();
}
References v8::internal::Isolate::Current(), v8::internal::Managed< CppType >::From(), kModuleEmbedderDataIndex, and v8::Context::SetEmbedderData().
Referenced by v8::Shell::CreateEvaluationContext(), v8::Shell::CreateRealm(), and v8::Shell::HostCreateShadowRealmContext().
IsAbsolutePath()
bool v8::anonymous_namespace{d8.cc}::IsAbsolutePath (const std::string & path)
Definition at line 1063 of file d8.cc.
                                           {
#if defined(V8_OS_WIN)
  // This is an incorrect approximation, but should
  // work for all our test-running cases.
  return path.find(":/") == 1 || path.find(":\\") == 1;
#else
  return path[0] == '/';
#endif
}
Referenced by DirName(), v8::Shell::FetchModuleSource(), v8::Shell::FetchModuleTree(), and NormalizePath().
IsValidHostDefinedOptions()
bool v8::anonymous_namespace{d8.cc}::IsValidHostDefinedOptions (Local< Context > context, Local< Data > options, Local< Value > resource_name)
Definition at line 870 of file d8.cc.
                                                           {
  if (!options->IsFixedArray()) return false;
  Local<FixedArray> array = options.As<FixedArray>();
  if (array->Length() != kHostDefinedOptionsLength) return false;
  uint32_t magic = 0;
  if (!array->Get(context, 0).As<Value>()->Uint32Value(context).To(&magic)) {
    return false;
  }
  if (magic != kHostDefinedOptionsMagicConstant) return false;
  return array->Get(context, 1).As<String>()->StrictEquals(resource_name);
}
References v8::Local< T >::As(), kHostDefinedOptionsLength, and kHostDefinedOptionsMagicConstant.
Referenced by v8::Shell::HostImportModuleWithPhaseDynamically().
LineFromOffset()
int v8::anonymous_namespace{d8.cc}::LineFromOffset (Local< debug::Script > script, int offset)
Definition at line 4424 of file d8.cc.
                                                          {
  debug::Location location = script->GetSourceLocation(offset);
  return location.GetLineNumber();
}
References v8::debug::Location::GetLineNumber(), and v8::internal::script.
Referenced by v8::Shell::WriteLcovData().
NormalizeModuleSpecifier()
std::string v8::anonymous_namespace{d8.cc}::NormalizeModuleSpecifier (const std::string & specifier, const std::string & dir_name)
Definition at line 1157 of file d8.cc.
                                                                {
  if (specifier.starts_with(kDataURLPrefix) ||
      specifier.starts_with("http://") || specifier.starts_with("https://"))
    return specifier;
  return NormalizePath(specifier, dir_name);
}
References kDataURLPrefix, and NormalizePath().
Referenced by v8::Shell::DoHostImportModuleDynamically(), v8::Shell::ExecuteModule(), v8::Shell::FetchModuleTree(), ResolveModuleCallback(), and ResolveModuleSourceCallback().
NormalizePath()
std::string v8::anonymous_namespace{d8.cc}::NormalizePath (const std::string & path, const std::string & dir_name)
Definition at line 1100 of file d8.cc.
                                                     {
  DCHECK(!path.starts_with(kDataURLPrefix));
  std::string absolute_path;
  if (IsAbsolutePath(path)) {
    absolute_path = path;
  } else {
    absolute_path = dir_name + '/' + path;
  }
  std::replace(absolute_path.begin(), absolute_path.end(), '\\', '/');
  std::vector<std::string> segments;
  std::istringstream segment_stream(absolute_path);
  std::string segment;
  while (std::getline(segment_stream, segment, '/')) {
    if (segment == "..") {
#if defined(V8_OS_WIN)
      if (segments.size() > 1) segments.pop_back();
#else
      if (!segments.empty()) segments.pop_back();
#endif
    } else if (segment != "" && segment != ".") {
      segments.push_back(segment);
    }
  }
  // Join path segments.
  std::ostringstream os;
#if defined(V8_OS_WIN)
  // The drive letter should be present in an absolute path.
  DCHECK(!segments.empty());
  DCHECK_EQ(2UL, segments[0].size());
  DCHECK_EQ(':', segments[0][1]);
  os << segments[0] << "/";
  if (segments.size() > 2) {
    std::copy(segments.begin() + 1, segments.end() - 1,
              std::ostream_iterator<std::string>(os, "/"));
    os << *segments.rbegin();
  } else if (segments.size() == 2) {
    os << segments[1];
  }
#else
  os << "/";
  if (segments.size() > 1) {
    std::copy(segments.begin(), segments.end() - 1,
              std::ostream_iterator<std::string>(os, "/"));
    os << *segments.rbegin();
  } else if (segments.size() == 1) {
    os << segments[0];
  }
#endif
  return os.str();
}
References DCHECK, DCHECK_EQ, IsAbsolutePath(), kDataURLPrefix, size(), and v8::internal::string.
Referenced by v8::Shell::DoHostImportModuleDynamically(), v8::Shell::LoadJSON(), NormalizeModuleSpecifier(), and v8::Shell::WriteLcovData().
ProcessMessages()
bool v8::anonymous_namespace{d8.cc}::ProcessMessages (Isolate * isolate, const std::function< platform::MessageLoopBehavior()> & behavior)
Definition at line 6233 of file d8.cc.
                                                                {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(isolate);
  i::SaveAndSwitchContext saved_context(i_isolate, i::Context());
  SealHandleScope shs(isolate);
  if (isolate->IsExecutionTerminating()) return true;
  TryCatch try_catch(isolate);
  try_catch.SetVerbose(true);
  while (true) {
    bool ran_a_task;
    ran_a_task =
        v8::platform::PumpMessageLoop(g_default_platform, isolate, behavior());
    if (isolate->IsExecutionTerminating()) return true;
    if (try_catch.HasCaught()) return false;
    if (ran_a_task) MicrotasksScope::PerformCheckpoint(isolate);
    if (isolate->IsExecutionTerminating()) return true;
    // In predictable mode we push all background tasks into the foreground
    // task queue of the {kProcessGlobalPredictablePlatformWorkerTaskQueue}
    // isolate. We execute all background tasks after running one foreground
    // task.
    if (i::v8_flags.verify_predictable) {
      TryCatch inner_try_catch(isolate);
      inner_try_catch.SetVerbose(true);
      while (v8::platform::PumpMessageLoop(
          g_default_platform, kProcessGlobalPredictablePlatformWorkerTaskQueue,
          platform::MessageLoopBehavior::kDoNotWait)) {
        ran_a_task = true;
        if (inner_try_catch.HasCaught()) return false;
        if (isolate->IsExecutionTerminating()) return true;
      }
    }
    if (!ran_a_task) break;
  }
  if (g_default_platform->IdleTasksEnabled(isolate)) {
    v8::platform::RunIdleTasks(g_default_platform, isolate,
                               50.0 / base::Time::kMillisecondsPerSecond);
    if (try_catch.HasCaught()) return false;
    if (isolate->IsExecutionTerminating()) return true;
  }
  return true;
}
References g_default_platform, v8::TryCatch::HasCaught(), v8::Platform::IdleTasksEnabled(), v8::Isolate::IsExecutionTerminating(), v8::platform::kDoNotWait, v8::base::TimeConstants::kMillisecondsPerSecond, v8::kProcessGlobalPredictablePlatformWorkerTaskQueue, v8::MicrotasksScope::PerformCheckpoint(), v8::platform::PumpMessageLoop(), v8::platform::RunIdleTasks(), v8::TryCatch::SetVerbose(), and v8::internal::v8_flags.
RejectPromiseIfExecutionIsNotTerminating()
void v8::anonymous_namespace{d8.cc}::RejectPromiseIfExecutionIsNotTerminating (Isolate * isolate, Local< Context > realm, Local< Promise::Resolver > resolver, const TryCatch & try_catch)
Definition at line 1600 of file d8.cc.
                                                                         {
  CHECK(try_catch.HasCaught());
  if (isolate->IsExecutionTerminating()) {
    Shell::ReportException(isolate, try_catch);
  } else {
    resolver->Reject(realm, try_catch.Exception()).ToChecked();
  }
}
References CHECK, v8::TryCatch::Exception(), v8::TryCatch::HasCaught(), v8::Isolate::IsExecutionTerminating(), and v8::Shell::ReportException().
Referenced by v8::Shell::DoHostImportModuleDynamically().
ResolveModuleCallback()
MaybeLocal<Module> v8::anonymous_namespace{d8.cc}::ResolveModuleCallback (Local< Context > context, Local< String > specifier, Local< FixedArray > import_attributes, Local< Module > referrer)
Definition at line 1179 of file d8.cc.
                                                                 {
  Isolate* isolate = Isolate::GetCurrent();
  std::shared_ptr<ModuleEmbedderData> module_data =
      GetModuleDataFromContext(context);
  std::string referrer_specifier = module_data->GetModuleSpecifier(referrer);
  std::string stl_specifier = ToSTLString(isolate, specifier);
  std::string absolute_path =
      NormalizeModuleSpecifier(stl_specifier, DirName(referrer_specifier));
  ModuleType module_type =
      ModuleEmbedderData::ModuleTypeFromImportSpecifierAndAttributes(
          context, stl_specifier, import_attributes, true);
  return module_data->GetModule(std::make_pair(absolute_path, module_type));
}
References DirName(), v8::Isolate::GetCurrent(), GetModuleDataFromContext(), NormalizeModuleSpecifier(), v8::internal::string, and ToSTLString().
Referenced by v8::Shell::DoHostImportModuleDynamically(), and v8::Shell::ExecuteModule().
ResolveModuleSourceCallback()
MaybeLocal<Object> v8::anonymous_namespace{d8.cc}::ResolveModuleSourceCallback (Local< Context > context, Local< String > specifier, Local< FixedArray > import_attributes, Local< Module > referrer)
Definition at line 1197 of file d8.cc.
                                                                 {
  Isolate* isolate = Isolate::GetCurrent();
  std::shared_ptr<ModuleEmbedderData> module_data =
      GetModuleDataFromContext(context);
  std::string referrer_specifier = module_data->GetModuleSpecifier(referrer);
  std::string stl_specifier = ToSTLString(isolate, specifier);
  std::string absolute_path =
      NormalizeModuleSpecifier(stl_specifier, DirName(referrer_specifier));
  ModuleType module_type =
      ModuleEmbedderData::ModuleTypeFromImportSpecifierAndAttributes(
          context, stl_specifier, import_attributes, true);
  return module_data->GetModuleSource(
      std::make_pair(absolute_path, module_type));
}
References DirName(), v8::Isolate::GetCurrent(), GetModuleDataFromContext(), NormalizeModuleSpecifier(), v8::internal::string, and ToSTLString().
Referenced by v8::Shell::DoHostImportModuleDynamically(), and v8::Shell::ExecuteModule().
SkipTerminationForFuzzing()
bool v8::anonymous_namespace{d8.cc}::SkipTerminationForFuzzing ()
Definition at line 3667 of file d8.cc.
                                 {
  // Triggering termination from JS can cause some non-determinism thus we
  // skip it for correctness fuzzing.
  if (i::v8_flags.correctness_fuzzer_suppressions) return true;
  // Termination also currently breaks Fuzzilli's REPRL mechanism as the
  // scheduled termination will prevent the next testcase sent by Fuzzilli from
  // being processed. This will in turn desynchronize the communication
  // between d8 and Fuzzilli, leading to a crash.
  if (fuzzilli_reprl) return true;
  return false;
}
References fuzzilli_reprl, and v8::internal::v8_flags.
Referenced by v8::Shell::ScheduleTermination(), and v8::Shell::TerminateNow().
ThrowError() [1/2]
template<int N>
void v8::anonymous_namespace{d8.cc}::ThrowError (Isolate * isolate, const char(&) message[N])
Definition at line 393 of file d8.cc.
                                                            {
  if (isolate->IsExecutionTerminating()) return;
  isolate->ThrowError(message);
}
References v8::Isolate::IsExecutionTerminating(), and v8::Isolate::ThrowError().
Referenced by v8::Isolate::ThrowError().
ThrowError() [2/2]
void v8::anonymous_namespace{d8.cc}::ThrowError (Isolate * isolate, Local< String > message)
Definition at line 398 of file d8.cc.
                                                         {
  if (isolate->IsExecutionTerminating()) return;
  isolate->ThrowError(message);
}
References v8::Isolate::IsExecutionTerminating(), and v8::Isolate::ThrowError().
Referenced by v8::Shell::DoHostImportModuleDynamically(), v8::Shell::ExecuteFile(), v8::Shell::FetchModuleSource(), v8::Shell::FetchModuleTree(), v8::Shell::FunctionAndArgumentsToString(), GetWorkerFromInternalField(), v8::Shell::LogGetAndStop(), v8::Shell::PerformanceMark(), v8::Shell::PerformanceMeasure(), v8::Worker::PostMessageOut(), v8::Shell::ProfilerSetOnProfileEndListener(), v8::Shell::ReadBuffer(), v8::Shell::ReadFile(), v8::Shell::ReadFileData(), v8::Shell::RealmDetachGlobal(), v8::Shell::RealmDispose(), v8::Shell::RealmEval(), v8::PerIsolateData::RealmIndexOrThrow(), v8::Shell::RealmNavigate(), v8::Shell::RealmOwner(), v8::Shell::SerializerDeserialize(), v8::Shell::SetFlushDenormals(), v8::Shell::SetPromiseHooks(), v8::Shell::TestVerifySourcePositions(), v8::Shell::WorkerNew(), v8::Shell::WorkerOnMessageSetter(), v8::Shell::WorkerPostMessage(), and v8::Shell::WriteFile().
ThrowException()
void v8::anonymous_namespace{d8.cc}::ThrowException (Isolate * isolate, Local< Value > exception)
Definition at line 403 of file d8.cc.
                                                              {
  if (isolate->IsExecutionTerminating()) return;
  isolate->ThrowException(exception);
}
References v8::Isolate::IsExecutionTerminating(), and v8::Isolate::ThrowException().
Referenced by v8::Shell::FetchModuleSource().
ToSTLString()
std::string v8::anonymous_namespace{d8.cc}::ToSTLString (Isolate * isolate, Local< String > v8_str)
Definition at line 724 of file d8.cc.
                                                              {
  String::Utf8Value utf8(isolate, v8_str);
  // Should not be able to fail since the input is a String.
  CHECK(*utf8);
  return *utf8;
}
References CHECK, and v8::anonymous_namespace{wasm-js.cc}::v8_str().
Referenced by v8::Shell::DoHostImportModuleDynamically(), v8::Shell::ExecuteString(), v8::Shell::FetchModuleTree(), v8::anonymous_namespace{d8.cc}::ModuleEmbedderData::ModuleTypeFromImportSpecifierAndAttributes(), ResolveModuleCallback(), ResolveModuleSourceCallback(), and v8::Shell::WriteLcovData().
TryGetValue()
static MaybeLocal<Value> v8::anonymous_namespace{d8.cc}::TryGetValue (v8::Isolate * isolate, Local< Context > context, Local< v8::Object > object, const char * property) [static]
Definition at line 408 of file d8.cc.
                                                           {
  MaybeLocal<String> v8_str = String::NewFromUtf8(isolate, property);
  if (v8_str.IsEmpty()) return {};
  return object->Get(context, v8_str.ToLocalChecked());
}
References v8::String::NewFromUtf8(), and v8::anonymous_namespace{wasm-js.cc}::v8_str().
Referenced by GetValue(), v8::Shell::PerformanceMeasureMemory(), v8::Shell::ReadCodeTypeAndArguments(), and v8::Shell::WorkerNew().
WriteLcovDataForNamedRange()
void v8::anonymous_namespace{d8.cc}::WriteLcovDataForNamedRange (std::ostream & sink, std::vector< uint32_t > * lines, const std::string & name, int start_line, int end_line, uint32_t count)
Definition at line 4441 of file d8.cc.
                                                              {
  WriteLcovDataForRange(lines, start_line, end_line, count);
  sink << "FN:" << start_line + 1 << "," << name << std::endl;
  sink << "FNDA:" << count << "," << name << std::endl;
}
References name, and WriteLcovDataForRange().
Referenced by v8::Shell::WriteLcovData().
WriteLcovDataForRange()
void v8::anonymous_namespace{d8.cc}::WriteLcovDataForRange (std::vector< uint32_t > * lines, int start_line, int end_line, uint32_t count)
Definition at line 4429 of file d8.cc.
                                                         {
  // Ensure space in the array.
  lines->resize(std::max(static_cast<size_t>(end_line + 1), lines->size()), 0);
  // Boundary lines could be shared between two functions with different
  // invocation counts. Take the maximum.
  (*lines)[start_line] = std::max((*lines)[start_line], count);
  (*lines)[end_line] = std::max((*lines)[end_line], count);
  // Invocation counts for non-boundary lines are overwritten.
  for (int k = start_line + 1; k < end_line; k++) (*lines)[k] = count;
}
Referenced by v8::Shell::WriteLcovData(), and WriteLcovDataForNamedRange().
Variable Documentation
current_worker_
thread_local Worker* v8::anonymous_namespace{d8.cc}::current_worker_ = nullptr
Definition at line 136 of file d8.cc.
Referenced by v8::Worker::GetCurrentWorker(), and v8::Worker::SetCurrentWorker().
fuzzilli_reprl
bool v8::anonymous_namespace{d8.cc}::fuzzilli_reprl = false
Definition at line 141 of file d8.cc.
Referenced by v8::SourceGroup::Execute(), v8::Shell::Main(), v8::Shell::RunMainIsolate(), and SkipTerminationForFuzzing().
g_default_platform
v8::Platform* v8::anonymous_namespace{d8.cc}::g_default_platform
Definition at line 389 of file d8.cc.
Referenced by v8::Worker::ExecuteInThread(), v8::Shell::Main(), v8::Shell::OnExit(), v8::Worker::ProcessMessages(), and ProcessMessages().
g_platform
std::unique_ptr<v8::Platform> v8::anonymous_namespace{d8.cc}::g_platform
Definition at line 390 of file d8.cc.
Referenced by D8WasmAsyncResolvePromiseCallback(), v8::Worker::ExecuteInThread(), v8::Shell::GetTimestamp(), v8::Shell::Main(), v8::Worker::PostMessageOut(), v8::CheckMessageFromWorkerTask::Run(), and v8::Shell::SetTimeout().
kDataURLPrefix
const char v8::anonymous_namespace{d8.cc}::kDataURLPrefix[] = `data:text/javascript,`
Definition at line 722 of file d8.cc.
Referenced by DirName(), v8::Shell::FetchModuleTree(), NormalizeModuleSpecifier(), and NormalizePath().
kHostDefinedOptionsLength
const int v8::anonymous_namespace{d8.cc}::kHostDefinedOptionsLength = 2
Definition at line 719 of file d8.cc.
Referenced by CreateScriptOrigin(), and IsValidHostDefinedOptions().
kHostDefinedOptionsMagicConstant
const uint32_t v8::anonymous_namespace{d8.cc}::kHostDefinedOptionsMagicConstant = 0xF1F2F3F0
Definition at line 720 of file d8.cc.
Referenced by CreateScriptOrigin(), and IsValidHostDefinedOptions().