v8::internal::compiler::anonymous_namespace{js-operator.cc} Namespace Reference
Functions
constexpr Operator::Properties BinopProperties (Operator::Opcode opcode)
template<class T >
Address AddressOrNull (OptionalRef< T > ref)
Function Documentation
AddressOrNull()
template<class T >
Address v8::internal::compiler::anonymous_namespace{js-operator.cc}::AddressOrNull (OptionalRef< T > ref)
Definition at line 37 of file js-operator.cc.
                                          {
  if (!ref.has_value()) return kNullAddress;
  return ref->object().address();
}
References v8::internal::compiler::OptionalRef< TRef >::has_value(), and v8::internal::kNullAddress.
BinopProperties()
constexpr Operator::Properties v8::internal::compiler::anonymous_namespace{js-operator.cc}::BinopProperties (Operator::Opcode opcode) [constexpr]
Definition at line 30 of file js-operator.cc.
                                                                    {
  DCHECK(JSOperator::IsBinaryWithFeedback(opcode));
  return opcode == IrOpcode::kJSStrictEqual ? Operator::kPure
                                            : Operator::kNoProperties;
}
References v8::internal::DCHECK(), v8::internal::compiler::JSOperator::IsBinaryWithFeedback(), v8::internal::compiler::Operator::kNoProperties, and v8::internal::compiler::Operator::kPure.