v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc} Namespace Reference
Classes
class CoverageFileWriter
class NativeModuleWireBytesStorage
Functions
bool ProtectedInstructionDataCompare (const ProtectedInstructionData &left, const ProtectedInstructionData &right)
base::SmallVector< base::AddressRegion, 1 > SplitRangeByReservationsIfNeeded (base::AddressRegion range, const std::vector< VirtualMemory > &owned_code_space)
int NumWasmFunctionsInFarJumpTable (uint32_t num_declared_functions)
size_t OverheadPerCodeSpace (uint32_t num_declared_functions)
size_t ReservationSizeForWasmCode (size_t needed_size, int num_declared_functions, size_t total_reserved_so_far)
size_t ReservationSizeForWrappers (size_t needed_size, size_t total_reserved_so_far)
ThreadIsolation::JitAllocationType ToAllocationType (v8::internal::wasm::NativeModule::JumpTableType type)
bool ShouldRemoveCode (WasmCode *code, NativeModule::RemoveFilter filter)
Variables
constexpr bool kNeedsToSplitRangeByReservations = false
constexpr base::AddressRegion kUnrestrictedRegion
constexpr size_t kTurbofanFunctionOverhead = 44
constexpr size_t kTurbofanCodeSizeMultiplier = 4
constexpr size_t kLiftoffFunctionOverhead = 96
constexpr size_t kLiftoffCodeSizeMultiplier = 5
thread_local WasmCodeRefScope * current_code_refs_scope = nullptr
Function Documentation
NumWasmFunctionsInFarJumpTable()
int v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::NumWasmFunctionsInFarJumpTable (uint32_t num_declared_functions)
Definition at line 697 of file wasm-code-manager.cc.
                                                                    {
  return NativeModule::kNeedsFarJumpsBetweenCodeSpaces
             ? static_cast<int>(num_declared_functions)
             : 0;
}
References v8::internal::wasm::NativeModule::kNeedsFarJumpsBetweenCodeSpaces.
Referenced by v8::internal::wasm::NativeModule::AddCodeSpaceLocked(), v8::internal::wasm::WasmCodeManager::EstimateNativeModuleMetaDataSize(), and OverheadPerCodeSpace().
OverheadPerCodeSpace()
size_t v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::OverheadPerCodeSpace (uint32_t num_declared_functions)
Definition at line 705 of file wasm-code-manager.cc.
                                                             {
  // Overhead for the jump table.
  size_t overhead = RoundUp<kCodeAlignment>(
      JumpTableAssembler::SizeForNumberOfSlots(num_declared_functions));
#if defined(V8_OS_WIN64)
  // On Win64, we need to reserve some pages at the beginning of an executable
  // space. See {AddCodeSpace}.
  overhead += Heap::GetCodeRangeReservedAreaSize();
#endif // V8_OS_WIN64
  // Overhead for the far jump table.
  if constexpr (NativeModule::kNeedsFarJumpsBetweenCodeSpaces) {
    overhead +=
        RoundUp<kCodeAlignment>(JumpTableAssembler::SizeForNumberOfFarJumpSlots(
            BuiltinLookup::BuiltinCount(),
            NumWasmFunctionsInFarJumpTable(num_declared_functions)));
  }
  return overhead;
}
References v8::internal::wasm::BuiltinLookup::BuiltinCount(), v8::internal::Heap::GetCodeRangeReservedAreaSize(), v8::internal::wasm::NativeModule::kNeedsFarJumpsBetweenCodeSpaces, NumWasmFunctionsInFarJumpTable(), v8::internal::wasm::JumpTableAssembler::SizeForNumberOfFarJumpSlots(), and v8::internal::wasm::JumpTableAssembler::SizeForNumberOfSlots().
Referenced by v8::internal::wasm::NativeModule::AddCodeSpaceLocked(), and ReservationSizeForWasmCode().
ProtectedInstructionDataCompare()
bool v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::ProtectedInstructionDataCompare (const ProtectedInstructionData & left, const ProtectedInstructionData & right)
Definition at line 330 of file wasm-code-manager.cc.
                                                                            {
  return left.instr_offset < right.instr_offset;
}
References v8::internal::trap_handler::ProtectedInstructionData::instr_offset.
Referenced by v8::internal::wasm::WasmCode::IsProtectedInstruction().
ReservationSizeForWasmCode()
size_t v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::ReservationSizeForWasmCode (size_t needed_size, int num_declared_functions, size_t total_reserved_so_far)
Definition at line 730 of file wasm-code-manager.cc.
                                                                {
  DCHECK_EQ(needed_size == 0, num_declared_functions == 0);
  if (needed_size == 0) return 0;
  size_t overhead = OverheadPerCodeSpace(num_declared_functions);
  // Reserve the maximum of
  // a) needed size + overhead (this is the minimum needed)
  // b) 2 * overhead (to not waste too much space by overhead)
  // c) 1/4 of current total reservation size (to grow exponentially)
  // For the minimum size we only take the overhead into account and not the
  // code space estimate, for two reasons:
  // - The code space estimate is only an estimate; we might actually need less
  // space later.
  // - When called at module construction time we pass the estimate for all
  // code in the module; this can still be split up into multiple spaces
  // later.
  size_t minimum_size = 2 * overhead;
  size_t suggested_size = std::max(
      std::max(RoundUp<kCodeAlignment>(needed_size) + overhead, minimum_size),
      total_reserved_so_far / 4);
  const size_t max_code_space_size =
      size_t{v8_flags.wasm_max_code_space_size_mb} * MB;
  if (V8_UNLIKELY(minimum_size > max_code_space_size)) {
    auto oom_detail = base::FormattedString{}
                      << "required reservation minimum (" << minimum_size
                      << ") is bigger than supported maximum ("
                      << max_code_space_size << ")";
    V8::FatalProcessOutOfMemory(nullptr,
                                "Exceeding maximum wasm code space size",
                                oom_detail.PrintToArray().data());
    UNREACHABLE();
  }
  // Limit by the maximum code space size.
  return std::min(max_code_space_size, suggested_size);
}
References DCHECK_EQ, v8::internal::V8::FatalProcessOutOfMemory(), v8::internal::MB, OverheadPerCodeSpace(), v8::internal::UNREACHABLE(), v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by v8::internal::wasm::WasmCodeAllocator::AllocateForCodeInRegion(), and v8::internal::wasm::WasmCodeManager::NewNativeModule().
ReservationSizeForWrappers()
size_t v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::ReservationSizeForWrappers (size_t needed_size, size_t total_reserved_so_far)
Definition at line 772 of file wasm-code-manager.cc.
                                                                {
  needed_size = RoundUp<kCodeAlignment>(needed_size);
  // Reserve the maximum of
  // a) needed size
  // c) 1/4 of current total reservation size (to grow exponentially)
  size_t suggested_size = std::max(needed_size, total_reserved_so_far / 4);
  const size_t max_code_space_size =
      size_t{v8_flags.wasm_max_code_space_size_mb} * MB;
  if (V8_UNLIKELY(needed_size > max_code_space_size)) {
    auto oom_detail = base::FormattedString{}
                      << "required reservation minimum (" << needed_size
                      << ") is bigger than supported maximum ("
                      << max_code_space_size << ")";
    V8::FatalProcessOutOfMemory(nullptr,
                                "Exceeding maximum wasm code space size",
                                oom_detail.PrintToArray().data());
    UNREACHABLE();
  }
  // Limit by the maximum code space size.
  return std::min(max_code_space_size, suggested_size);
}
References v8::internal::V8::FatalProcessOutOfMemory(), v8::internal::MB, v8::internal::UNREACHABLE(), v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by v8::internal::wasm::WasmCodeAllocator::AllocateForCodeInRegion().
ShouldRemoveCode()
bool v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::ShouldRemoveCode (WasmCode * code, NativeModule::RemoveFilter filter)
Definition at line 2757 of file wasm-code-manager.cc.
                                                                       {
  if (filter == NativeModule::RemoveFilter::kRemoveDebugCode &&
      !code->for_debugging()) {
    return false;
  }
  if (filter == NativeModule::RemoveFilter::kRemoveNonDebugCode &&
      code->for_debugging()) {
    return false;
  }
  if (filter == NativeModule::RemoveFilter::kRemoveLiftoffCode &&
      !code->is_liftoff()) {
    return false;
  }
  if (filter == NativeModule::RemoveFilter::kRemoveTurbofanCode &&
      !code->is_turbofan()) {
    return false;
  }
  return true;
}
References code, v8::internal::wasm::NativeModule::kRemoveDebugCode, v8::internal::wasm::NativeModule::kRemoveLiftoffCode, v8::internal::wasm::NativeModule::kRemoveNonDebugCode, and v8::internal::wasm::NativeModule::kRemoveTurbofanCode.
Referenced by v8::internal::wasm::NativeModule::RemoveCompiledCode().
SplitRangeByReservationsIfNeeded()
base::SmallVector<base::AddressRegion, 1> v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::SplitRangeByReservationsIfNeeded (base::AddressRegion range, const std::vector< VirtualMemory > & owned_code_space)
Definition at line 669 of file wasm-code-manager.cc.
                                                      {
  if (!kNeedsToSplitRangeByReservations) return {range};
  base::SmallVector<base::AddressRegion, 1> split_ranges;
  size_t missing_begin = range.begin();
  size_t missing_end = range.end();
  for (auto& vmem : base::Reversed(owned_code_space)) {
    Address overlap_begin = std::max(missing_begin, vmem.address());
    Address overlap_end = std::min(missing_end, vmem.end());
    if (overlap_begin >= overlap_end) continue;
    split_ranges.emplace_back(overlap_begin, overlap_end - overlap_begin);
    // Opportunistically reduce the missing range. This might terminate the loop
    // early.
    if (missing_begin == overlap_begin) missing_begin = overlap_end;
    if (missing_end == overlap_end) missing_end = overlap_begin;
    if (missing_begin >= missing_end) break;
  }
#ifdef ENABLE_SLOW_DCHECKS
  // The returned vector should cover the full range.
  size_t total_split_size = 0;
  for (auto split : split_ranges) total_split_size += split.size();
  DCHECK_EQ(range.size(), total_split_size);
#endif
  return split_ranges;
}
References v8::base::AddressRegion::begin(), DCHECK_EQ, v8::base::SmallVector< T, kSize, Allocator >::emplace_back(), v8::base::AddressRegion::end(), kNeedsToSplitRangeByReservations, v8::base::Reversed(), v8::base::AddressRegion::size(), and v8::internal::libvtune::split().
Referenced by v8::internal::wasm::WasmCodeAllocator::AllocateForCodeInRegion(), and v8::internal::wasm::WasmCodeAllocator::FreeCode().
ToAllocationType()
ThreadIsolation::JitAllocationType v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::ToAllocationType (v8::internal::wasm::NativeModule::JumpTableType type)
Definition at line 1726 of file wasm-code-manager.cc.
                                                  {
  switch (type) {
    case NativeModule::JumpTableType::kJumpTable:
      return ThreadIsolation::JitAllocationType::kWasmJumpTable;
    case NativeModule::JumpTableType::kFarJumpTable:
      return ThreadIsolation::JitAllocationType::kWasmFarJumpTable;
    case NativeModule::JumpTableType::kLazyCompileTable:
      return ThreadIsolation::JitAllocationType::kWasmLazyCompileTable;
  }
}
References v8::internal::wasm::NativeModule::kFarJumpTable, v8::internal::wasm::NativeModule::kJumpTable, v8::internal::wasm::NativeModule::kLazyCompileTable, v8::internal::ThreadIsolation::kWasmFarJumpTable, v8::internal::ThreadIsolation::kWasmJumpTable, v8::internal::ThreadIsolation::kWasmLazyCompileTable, and v8::internal::tracing::type.
Referenced by v8::internal::wasm::NativeModule::CreateEmptyJumpTableInRegionLocked().
Variable Documentation
current_code_refs_scope
thread_local WasmCodeRefScope* v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::current_code_refs_scope = nullptr
Definition at line 3030 of file wasm-code-manager.cc.
Referenced by v8::internal::wasm::WasmCodeRefScope::AddRef(), v8::internal::wasm::WasmCodeRefScope::AddRefIfNotDying(), v8::internal::wasm::WasmCodeRefScope::WasmCodeRefScope(), and v8::internal::wasm::WasmCodeRefScope::~WasmCodeRefScope().
kLiftoffCodeSizeMultiplier
constexpr size_t v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::kLiftoffCodeSizeMultiplier = 5 [constexpr]
Definition at line 2375 of file wasm-code-manager.cc.
Referenced by v8::internal::wasm::WasmCodeManager::EstimateLiftoffCodeSize(), and v8::internal::wasm::WasmCodeManager::EstimateNativeModuleCodeSize().
kLiftoffFunctionOverhead
constexpr size_t v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::kLiftoffFunctionOverhead = 96 [constexpr]
Definition at line 2374 of file wasm-code-manager.cc.
Referenced by v8::internal::wasm::WasmCodeManager::EstimateLiftoffCodeSize(), and v8::internal::wasm::WasmCodeManager::EstimateNativeModuleCodeSize().
kNeedsToSplitRangeByReservations
constexpr bool v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::kNeedsToSplitRangeByReservations = false [constexpr]
Definition at line 666 of file wasm-code-manager.cc.
Referenced by SplitRangeByReservationsIfNeeded().
kTurbofanCodeSizeMultiplier
constexpr size_t v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::kTurbofanCodeSizeMultiplier = 4 [constexpr]
Definition at line 2373 of file wasm-code-manager.cc.
Referenced by v8::internal::wasm::WasmCodeManager::EstimateNativeModuleCodeSize().
kTurbofanFunctionOverhead
constexpr size_t v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::kTurbofanFunctionOverhead = 44 [constexpr]
Definition at line 2372 of file wasm-code-manager.cc.
Referenced by v8::internal::wasm::WasmCodeManager::EstimateNativeModuleCodeSize().
kUnrestrictedRegion
constexpr base::AddressRegion v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::kUnrestrictedRegion [constexpr]
Initial value:
{
    kNullAddress, std::numeric_limits<size_t>::max()}
Definition at line 799 of file wasm-code-manager.cc.
Referenced by v8::internal::wasm::WasmCodeAllocator::AllocateForCode(), v8::internal::wasm::WasmCodeAllocator::AllocateForCodeInRegion(), v8::internal::wasm::WasmCodeAllocator::AllocateForWrapper(), and v8::internal::wasm::NativeModule::CreateEmptyJumpTableLocked().