v8::internal::torque::anonymous_namespace{torque-parser.cc}::anonymous_namespace{torque-parser.cc} Namespace Reference
Functions
bool HasAnnotation (ParseResultIterator *child_results, const char *annotation, const char *declaration)
bool HasExportAnnotation (ParseResultIterator *child_results, const char *declaration)
Function Documentation
HasAnnotation()
bool v8::internal::torque::anonymous_namespace{torque-parser.cc}::anonymous_namespace{torque-parser.cc}::HasAnnotation (ParseResultIterator * child_results, const char * annotation, const char * declaration)
Definition at line 652 of file torque-parser.cc.
                                            {
  auto annotations = child_results->NextAs<std::vector<Annotation>>();
  if (!annotations.empty()) {
    if (annotations.size() > 1 || annotations[0].name->value != annotation) {
      Error(declaration, " declarations only support a single ", annotation,
            " annotation");
    }
    return true;
  }
  return false;
}
References v8::internal::torque::Error(), and v8::internal::torque::ParseResultIterator::NextAs().
Referenced by HasExportAnnotation(), and v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeAbstractTypeDeclaration().
HasExportAnnotation()
bool v8::internal::torque::anonymous_namespace{torque-parser.cc}::anonymous_namespace{torque-parser.cc}::HasExportAnnotation (ParseResultIterator * child_results, const char * declaration)
Definition at line 665 of file torque-parser.cc.
                                                  {
  return HasAnnotation(child_results, ANNOTATION_EXPORT, declaration);
}
References v8::internal::torque::ANNOTATION_EXPORT, and HasAnnotation().
Referenced by v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeStructDeclaration().