v8::internal::anonymous_namespace{runtime-test.cc} Namespace Reference
Functions
V8_WARN_UNUSED_RESULT Tagged< Object > CrashUnlessFuzzing (Isolate *isolate)
V8_WARN_UNUSED_RESULT bool CrashUnlessFuzzingReturnFalse (Isolate *isolate)
V8_WARN_UNUSED_RESULT bool CheckMarkedForManualOptimization (Isolate *isolate, Tagged< JSFunction > function)
V8_WARN_UNUSED_RESULT Tagged< Object > ReturnFuzzSafe (Tagged< Object > value, Isolate *isolate)
bool IsAsmWasmFunction (Isolate *isolate, Tagged< JSFunction > function)
bool CanOptimizeFunction (CodeKind target_kind, DirectHandle< JSFunction > function, Isolate *isolate, IsCompiledScope *is_compiled_scope)
Tagged< Object > OptimizeFunctionOnNextCall (RuntimeArguments &args, Isolate *isolate, CodeKind target_kind)
bool EnsureCompiledAndFeedbackVector (Isolate *isolate, DirectHandle< JSFunction > function, IsCompiledScope *is_compiled_scope)
void FinalizeOptimization (Isolate *isolate)
BytecodeOffset OffsetOfNextJumpLoop (Isolate *isolate, Handle< BytecodeArray > bytecode_array, int current_offset)
void call_as_function (const v8::FunctionCallbackInfo< v8::Value > &info)
int FixedArrayLenFromSize (int size)
void FillUpOneNewSpacePage (Isolate *isolate, Heap *heap, SemiSpaceNewSpace *space)
int StackSize (Isolate *isolate)
void PrintIndentation (int stack_size)
v8::ModifyCodeGenerationFromStringsResult DisallowCodegenFromStringsCallback (v8::Local< v8::Context > context, v8::Local< v8::Value > source, bool is_code_kind)
Function Documentation
call_as_function()
void v8::internal::anonymous_namespace{runtime-test.cc}::call_as_function (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 1090 of file runtime-test.cc.
                                                                   {
  DCHECK(ValidateCallbackInfo(info));
  v8::Isolate* isolate = info.GetIsolate();
  auto context = isolate->GetCurrentContext();
  auto global = context->Global();
  auto target_function_name = info.Data().As<v8::String>();
  v8::Local<v8::Function> target;
  {
    Local<Value> result;
    if (!global->Get(context, target_function_name).ToLocal(&result)) {
      return;
    }
    if (!result->IsFunction()) {
      isolate->ThrowError("Target function is not callable");
      return;
    }
    target = result.As<Function>();
  }
  int argc = info.Length();
  v8::LocalVector<v8::Value> args(isolate, argc);
  for (int i = 0; i < argc; i++) {
    args[i] = info[i];
  }
  Local<Value> result;
  if (!target->Call(context, info.This(), argc, args.data()).ToLocal(&result)) {
    return;
  }
  info.GetReturnValue().Set(result);
}
References v8::base::args, v8::FunctionCallbackInfo< T >::Data(), v8::internal::DCHECK(), v8::Isolate::GetCurrentContext(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::FunctionCallbackInfo< T >::Length(), v8::base::internal::result, v8::FunctionCallbackInfo< T >::This(), v8::Isolate::ThrowError(), and v8::internal::ValidateCallbackInfo().
Referenced by v8::internal::RUNTIME_FUNCTION().
CanOptimizeFunction()
bool v8::internal::anonymous_namespace{runtime-test.cc}::CanOptimizeFunction (CodeKind target_kind, DirectHandle< JSFunction > function, Isolate * isolate, IsCompiledScope * is_compiled_scope)
Definition at line 307 of file runtime-test.cc.
                                                             {
  // The following conditions were lifted (in part) from the DCHECK inside
  // JSFunction::MarkForOptimization().
  // If function isn't compiled, compile it now.
  if (!is_compiled_scope->is_compiled() &&
      !Compiler::Compile(isolate, function, Compiler::CLEAR_EXCEPTION,
                         is_compiled_scope)) {
    return CrashUnlessFuzzingReturnFalse(isolate);
  }
  if (target_kind == CodeKind::TURBOFAN_JS && !v8_flags.turbofan) return false;
  if (target_kind == CodeKind::MAGLEV && !maglev::IsMaglevEnabled()) {
    return false;
  }
  if (function->shared()->optimization_disabled(target_kind)) {
    return false;
  }
  if (IsAsmWasmFunction(isolate, *function)) {
    return CrashUnlessFuzzingReturnFalse(isolate);
  }
  if (v8_flags.testing_d8_test_runner) {
    if (!CheckMarkedForManualOptimization(isolate, *function)) {
      return CrashUnlessFuzzingReturnFalse(isolate);
    }
  }
  if (function->is_compiled(isolate) &&
      !function->HasAvailableCodeKind(isolate,
                                      CodeKind::INTERPRETED_FUNCTION)) {
    return CrashUnlessFuzzingReturnFalse(isolate);
  }
  if (function->HasAvailableCodeKind(isolate, target_kind) ||
      function->HasAvailableHigherTierCodeThan(isolate, target_kind)) {
    DCHECK(function->HasAttachedOptimizedCode(isolate) ||
           function->ChecksTieringState(isolate));
    return false;
  }
  return true;
}
References CheckMarkedForManualOptimization(), v8::internal::Compiler::CLEAR_EXCEPTION, v8::internal::Compiler::Compile(), CrashUnlessFuzzingReturnFalse(), v8::internal::DCHECK(), v8::internal::IsCompiledScope::is_compiled(), IsAsmWasmFunction(), v8::internal::maglev::IsMaglevEnabled(), and v8::internal::v8_flags.
Referenced by OptimizeFunctionOnNextCall().
CheckMarkedForManualOptimization()
V8_WARN_UNUSED_RESULT bool v8::internal::anonymous_namespace{runtime-test.cc}::CheckMarkedForManualOptimization (Isolate * isolate, Tagged< JSFunction > function)
Definition at line 73 of file runtime-test.cc.
                                                   {
  if (!ManualOptimizationTable::IsMarkedForManualOptimization(isolate,
                                                              function)) {
    PrintF("Error: Function ");
    ShortPrint(function);
    PrintF(
        " should be prepared for optimization with "
        "%%PrepareFunctionForOptimization before "
        "%%OptimizeFunctionOnNextCall / %%OptimizeMaglevOnNextCall / "
        "%%OptimizeOsr ");
    return false;
  }
  return true;
}
References v8::internal::ManualOptimizationTable::IsMarkedForManualOptimization(), v8::internal::PrintF(), and v8::internal::ShortPrint().
Referenced by CanOptimizeFunction(), and v8::internal::RUNTIME_FUNCTION().
CrashUnlessFuzzing()
V8_WARN_UNUSED_RESULT Tagged<Object> v8::internal::anonymous_namespace{runtime-test.cc}::CrashUnlessFuzzing (Isolate * isolate)
Definition at line 63 of file runtime-test.cc.
                                                                          {
  CHECK(v8_flags.fuzzing);
  return ReadOnlyRoots(isolate).undefined_value();
}
References CHECK, and v8::internal::v8_flags.
Referenced by OptimizeFunctionOnNextCall(), and v8::internal::RUNTIME_FUNCTION().
CrashUnlessFuzzingReturnFalse()
V8_WARN_UNUSED_RESULT bool v8::internal::anonymous_namespace{runtime-test.cc}::CrashUnlessFuzzingReturnFalse (Isolate * isolate)
Definition at line 68 of file runtime-test.cc.
                                                                           {
  CHECK(v8_flags.fuzzing);
  return false;
}
References CHECK, and v8::internal::v8_flags.
Referenced by CanOptimizeFunction().
DisallowCodegenFromStringsCallback()
v8::ModifyCodeGenerationFromStringsResult v8::internal::anonymous_namespace{runtime-test.cc}::DisallowCodegenFromStringsCallback (v8::Local< v8::Context > context, v8::Local< v8::Value > source, bool is_code_kind)
Definition at line 1712 of file runtime-test.cc.
                       {
  return {false, {}};
}
Referenced by v8::internal::RUNTIME_FUNCTION().
EnsureCompiledAndFeedbackVector()
bool v8::internal::anonymous_namespace{runtime-test.cc}::EnsureCompiledAndFeedbackVector (Isolate * isolate, DirectHandle< JSFunction > function, IsCompiledScope * is_compiled_scope)
Definition at line 404 of file runtime-test.cc.
                                                                         {
  *is_compiled_scope = function->shared()->is_compiled_scope(isolate);
  // If function isn't compiled, compile it now.
  if (!is_compiled_scope->is_compiled()) {
    // Check function allows lazy compilation.
    DCHECK(function->shared()->allows_lazy_compilation());
    if (!Compiler::Compile(isolate, function, Compiler::CLEAR_EXCEPTION,
                           is_compiled_scope)) {
      return false;
    }
  }
  // Ensure function has a feedback vector to hold type feedback for
  // optimization.
  if (!function->shared()->HasFeedbackMetadata()) {
    return false;
  }
  JSFunction::EnsureFeedbackVector(isolate, function, is_compiled_scope);
  return true;
}
References v8::internal::Compiler::CLEAR_EXCEPTION, v8::internal::Compiler::Compile(), v8::internal::DCHECK(), v8::internal::JSFunction::EnsureFeedbackVector(), and v8::internal::IsCompiledScope::is_compiled().
Referenced by v8::internal::RUNTIME_FUNCTION().
FillUpOneNewSpacePage()
void v8::internal::anonymous_namespace{runtime-test.cc}::FillUpOneNewSpacePage (Isolate * isolate, Heap * heap, SemiSpaceNewSpace * space)
Definition at line 1204 of file runtime-test.cc.
                                                     {
  DCHECK(!v8_flags.single_generation);
  heap->FreeMainThreadLinearAllocationAreas();
  PauseAllocationObserversScope pause_observers(heap);
  while (space->GetSpaceRemainingOnCurrentPageForTesting() > 0) {
    int space_remaining = space->GetSpaceRemainingOnCurrentPageForTesting();
    int length = FixedArrayLenFromSize(space_remaining);
    if (length > 0) {
      DirectHandle<FixedArray> padding =
          isolate->factory()->NewFixedArray(length, AllocationType::kYoung);
      DCHECK(heap->new_space()->Contains(*padding));
      space_remaining -= padding->Size();
    } else {
      // Not enough room to create another fixed array. Create a filler instead.
      space->FillCurrentPageForTesting();
    }
    heap->FreeMainThreadLinearAllocationAreas();
  }
}
References v8::internal::DCHECK(), v8::internal::Isolate::factory(), FixedArrayLenFromSize(), v8::internal::kYoung, v8::internal::length, v8::internal::FactoryBase< Impl >::NewFixedArray(), space, and v8::internal::v8_flags.
Referenced by v8::internal::RUNTIME_FUNCTION().
FinalizeOptimization()
void v8::internal::anonymous_namespace{runtime-test.cc}::FinalizeOptimization (Isolate * isolate)
Definition at line 640 of file runtime-test.cc.
                                            {
  DCHECK(isolate->concurrent_recompilation_enabled());
  isolate->optimizing_compile_dispatcher()->WaitUntilCompilationJobsDone();
  isolate->optimizing_compile_dispatcher()->InstallOptimizedFunctions();
  isolate->optimizing_compile_dispatcher()->set_finalize(true);
#if V8_ENABLE_MAGLEV
  if (isolate->maglev_concurrent_dispatcher()->is_enabled()) {
    isolate->maglev_concurrent_dispatcher()->AwaitCompileJobs();
    isolate->maglev_concurrent_dispatcher()->FinalizeFinishedJobs();
  }
#endif // V8_ENABLE_MAGLEV
}
References v8::internal::Isolate::concurrent_recompilation_enabled(), v8::internal::DCHECK(), v8::internal::OptimizingCompileDispatcher::InstallOptimizedFunctions(), v8::internal::Isolate::optimizing_compile_dispatcher(), v8::internal::OptimizingCompileDispatcher::set_finalize(), and v8::internal::OptimizingCompileDispatcher::WaitUntilCompilationJobsDone().
Referenced by v8::internal::RUNTIME_FUNCTION().
FixedArrayLenFromSize()
int v8::internal::anonymous_namespace{runtime-test.cc}::FixedArrayLenFromSize (int size)
Definition at line 1199 of file runtime-test.cc.
                                    {
  return std::min({(size - OFFSET_OF_DATA_START(FixedArray)) / kTaggedSize,
                   FixedArray::kMaxRegularLength});
}
References v8::internal::FixedArray::kMaxRegularLength, v8::internal::kTaggedSize, OFFSET_OF_DATA_START, and size().
Referenced by FillUpOneNewSpacePage().
IsAsmWasmFunction()
bool v8::internal::anonymous_namespace{runtime-test.cc}::IsAsmWasmFunction (Isolate * isolate, Tagged< JSFunction > function)
Definition at line 113 of file runtime-test.cc.
                                                                      {
  DisallowGarbageCollection no_gc;
#if V8_ENABLE_WEBASSEMBLY
  // For simplicity we include invalid asm.js functions whose code hasn't yet
  // been updated to CompileLazy but is still the InstantiateAsmJs builtin.
  return function->shared()->HasAsmWasmData() ||
         function->code(isolate)->builtin_id() == Builtin::kInstantiateAsmJs;
#else
  return false;
#endif // V8_ENABLE_WEBASSEMBLY
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by CanOptimizeFunction(), and v8::internal::RUNTIME_FUNCTION().
OffsetOfNextJumpLoop()
BytecodeOffset v8::internal::anonymous_namespace{runtime-test.cc}::OffsetOfNextJumpLoop (Isolate * isolate, Handle< BytecodeArray > bytecode_array, int current_offset)
Definition at line 654 of file runtime-test.cc.
                                                        {
  interpreter::BytecodeArrayIterator it(bytecode_array, current_offset);
  // First, look for a loop that contains the current bytecode offset.
  for (; !it.done(); it.Advance()) {
    if (it.current_bytecode() != interpreter::Bytecode::kJumpLoop) {
      continue;
    }
    if (!base::IsInRange(current_offset, it.GetJumpTargetOffset(),
                         it.current_offset())) {
      continue;
    }
    return BytecodeOffset(it.current_offset());
  }
  // Fall back to any loop after the current offset.
  it.SetOffset(current_offset);
  for (; !it.done(); it.Advance()) {
    if (it.current_bytecode() == interpreter::Bytecode::kJumpLoop) {
      return BytecodeOffset(it.current_offset());
    }
  }
  return BytecodeOffset::None();
}
References v8::internal::interpreter::BytecodeArrayIterator::Advance(), v8::internal::interpreter::BytecodeArrayIterator::current_bytecode(), v8::internal::interpreter::BytecodeArrayIterator::current_offset(), v8::internal::interpreter::BytecodeArrayIterator::done(), v8::internal::interpreter::BytecodeArrayIterator::GetJumpTargetOffset(), v8::internal::BytecodeOffset::None(), and v8::internal::interpreter::BytecodeArrayIterator::SetOffset().
Referenced by v8::internal::RUNTIME_FUNCTION().
OptimizeFunctionOnNextCall()
Tagged<Object> v8::internal::anonymous_namespace{runtime-test.cc}::OptimizeFunctionOnNextCall (RuntimeArguments & args, Isolate * isolate, CodeKind target_kind)
Definition at line 355 of file runtime-test.cc.
                                                                {
  if (args.length() != 1 && args.length() != 2) {
    return CrashUnlessFuzzing(isolate);
  }
  DirectHandle<Object> function_object = args.at(0);
  if (!IsJSFunction(*function_object)) return CrashUnlessFuzzing(isolate);
  DirectHandle<JSFunction> function = Cast<JSFunction>(function_object);
  IsCompiledScope is_compiled_scope(
      function->shared()->is_compiled_scope(isolate));
  if (!CanOptimizeFunction(target_kind, function, isolate,
                           &is_compiled_scope)) {
    return ReadOnlyRoots(isolate).undefined_value();
  }
  ConcurrencyMode concurrency_mode = ConcurrencyMode::kSynchronous;
  if (args.length() == 2) {
    DirectHandle<Object> type = args.at(1);
    if (!IsString(*type)) return CrashUnlessFuzzing(isolate);
    if (Cast<String>(type)->IsOneByteEqualTo(
            base::StaticCharVector("concurrent")) &&
        isolate->concurrent_recompilation_enabled()) {
      concurrency_mode = ConcurrencyMode::kConcurrent;
    }
  }
  // This function may not have been lazily compiled yet, even though its shared
  // function has.
  if (!function->is_compiled(isolate)) {
    DCHECK(function->shared()->HasBytecodeArray());
    Tagged<Code> code = *BUILTIN_CODE(isolate, InterpreterEntryTrampoline);
    if (function->shared()->HasBaselineCode()) {
      code = function->shared()->baseline_code(kAcquireLoad);
    }
    function->UpdateCode(isolate, code);
  }
  TraceManualRecompile(*function, target_kind, concurrency_mode);
  JSFunction::EnsureFeedbackVector(isolate, function, &is_compiled_scope);
  if (function->GetActiveTier(isolate) != target_kind) {
    function->RequestOptimization(isolate, target_kind, concurrency_mode);
  }
  return ReadOnlyRoots(isolate).undefined_value();
}
References v8::base::args, BUILTIN_CODE, CanOptimizeFunction(), code, v8::internal::Isolate::concurrent_recompilation_enabled(), CrashUnlessFuzzing(), v8::internal::DCHECK(), v8::internal::JSFunction::EnsureFeedbackVector(), v8::kAcquireLoad, v8::internal::kConcurrent, v8::internal::kSynchronous, v8::base::StaticCharVector(), v8::internal::TraceManualRecompile(), and v8::internal::tracing::type.
Referenced by v8::internal::RUNTIME_FUNCTION().
PrintIndentation()
void v8::internal::anonymous_namespace{runtime-test.cc}::PrintIndentation (int stack_size)
Definition at line 1597 of file runtime-test.cc.
                                      {
  const int max_display = 80;
  if (stack_size <= max_display) {
    PrintF("%4d:%*s", stack_size, stack_size, "");
  } else {
    PrintF("%4d:%*s", stack_size, max_display, "...");
  }
}
References v8::internal::PrintF().
Referenced by v8::internal::RUNTIME_FUNCTION().
ReturnFuzzSafe()
V8_WARN_UNUSED_RESULT Tagged<Object> v8::internal::anonymous_namespace{runtime-test.cc}::ReturnFuzzSafe (Tagged< Object > value, Isolate * isolate)
Definition at line 91 of file runtime-test.cc.
                                                                      {
  return v8_flags.correctness_fuzzer_suppressions
             ? ReadOnlyRoots(isolate).undefined_value()
             : value;
}
References v8::internal::v8_flags, and v8::internal::value.
Referenced by v8::internal::RUNTIME_FUNCTION().
StackSize()
int v8::internal::anonymous_namespace{runtime-test.cc}::StackSize (Isolate * isolate)
Definition at line 1591 of file runtime-test.cc.
                                {
  int n = 0;
  for (JavaScriptStackFrameIterator it(isolate); !it.done(); it.Advance()) n++;
  return n;
}
References v8::internal::JavaScriptStackFrameIterator::done().
Referenced by v8::internal::RUNTIME_FUNCTION().