v8::internal::interpreter::anonymous_namespace{bytecode-decoder.cc} Namespace Reference
Functions
const char * NameForRuntimeId (Runtime::FunctionId idx)
const char * NameForNativeContextIndex (uint32_t idx)
Function Documentation
NameForNativeContextIndex()
const char* v8::internal::interpreter::anonymous_namespace{bytecode-decoder.cc}::NameForNativeContextIndex (uint32_t idx)
Definition at line 80 of file bytecode-decoder.cc.
                                                    {
  switch (idx) {
#define CASE(index_name, type, name) \
  case Context::index_name: \
    return #name;
    NATIVE_CONTEXT_FIELDS(CASE)
#undef CASE
    default:
      UNREACHABLE();
  }
}
References CASE, NATIVE_CONTEXT_FIELDS, and v8::internal::UNREACHABLE().
Referenced by v8::internal::interpreter::BytecodeDecoder::Decode().
NameForRuntimeId()
const char* v8::internal::interpreter::anonymous_namespace{bytecode-decoder.cc}::NameForRuntimeId (Runtime::FunctionId idx)
Definition at line 76 of file bytecode-decoder.cc.
                                                    {
  return Runtime::FunctionForId(idx)->name;
}
References v8::internal::Runtime::FunctionForId(), and v8::internal::Runtime::Function::name.
Referenced by v8::internal::interpreter::BytecodeDecoder::Decode().