v8::internal::wasm::anonymous_namespace{wasm-debug.cc} Namespace Reference
Typedefs
using ImportExportKey = std::pair< ImportExportKindCode, uint32_t >
Enumerations
enum ReturnLocation { kAfterBreakpoint
, kAfterWasmCall
 }
Functions
Address FindNewPC (WasmFrame *frame, WasmCode *wasm_code, int byte_offset, ReturnLocation return_location)
Typedef Documentation
ImportExportKey
using v8::internal::wasm::anonymous_namespace{wasm-debug.cc}::ImportExportKey = typedef std::pair<ImportExportKindCode, uint32_t>
Definition at line 39 of file wasm-debug.cc.
Enumeration Type Documentation
ReturnLocation
enum v8::internal::wasm::anonymous_namespace{wasm-debug.cc}::ReturnLocation
Enumerator
kAfterBreakpoint
kAfterWasmCall
Definition at line 41 of file wasm-debug.cc.
{ kAfterBreakpoint, kAfterWasmCall };
Function Documentation
FindNewPC()
Address v8::internal::wasm::anonymous_namespace{wasm-debug.cc}::FindNewPC (WasmFrame * frame, WasmCode * wasm_code, int byte_offset, ReturnLocation return_location)
Definition at line 43 of file wasm-debug.cc.
                                                  {
  base::Vector<const uint8_t> new_pos_table = wasm_code->source_positions();
  DCHECK_LE(0, byte_offset);
  // Find the size of the call instruction by computing the distance from the
  // source position entry to the return address.
  WasmCode* old_code = frame->wasm_code();
  int pc_offset = static_cast<int>(frame->pc() - old_code->instruction_start());
  base::Vector<const uint8_t> old_pos_table = old_code->source_positions();
  SourcePositionTableIterator old_it(old_pos_table);
  int call_offset = -1;
  while (!old_it.done() && old_it.code_offset() < pc_offset) {
    call_offset = old_it.code_offset();
    old_it.Advance();
  }
  DCHECK_LE(0, call_offset);
  int call_instruction_size = pc_offset - call_offset;
  // If {return_location == kAfterBreakpoint} we search for the first code
  // offset which is marked as instruction (i.e. not the breakpoint).
  // If {return_location == kAfterWasmCall} we return the last code offset
  // associated with the byte offset.
  SourcePositionTableIterator it(new_pos_table);
  while (!it.done() && it.source_position().ScriptOffset() != byte_offset) {
    it.Advance();
  }
  if (return_location == kAfterBreakpoint) {
    while (!it.is_statement()) it.Advance();
    DCHECK_EQ(byte_offset, it.source_position().ScriptOffset());
    return wasm_code->instruction_start() + it.code_offset() +
           call_instruction_size;
  }
  DCHECK_EQ(kAfterWasmCall, return_location);
  int code_offset;
  do {
    code_offset = it.code_offset();
    it.Advance();
  } while (!it.done() && it.source_position().ScriptOffset() == byte_offset);
  return wasm_code->instruction_start() + code_offset + call_instruction_size;
}
References v8::internal::SourcePositionTableIterator::Advance(), v8::internal::SourcePositionTableIterator::code_offset(), DCHECK_EQ, DCHECK_LE, v8::internal::SourcePositionTableIterator::done(), v8::internal::wasm::WasmCode::instruction_start(), v8::internal::SourcePositionTableIterator::is_statement(), kAfterBreakpoint, kAfterWasmCall, v8::internal::SourcePosition::ScriptOffset(), v8::internal::SourcePositionTableIterator::source_position(), and v8::internal::wasm::WasmCode::source_positions().
Referenced by v8::internal::wasm::DebugInfoImpl::UpdateReturnAddress().