v8::internal::maglev::anonymous_namespace{maglev-ir-arm.cc} Namespace Reference
Enumerations
enum class ReduceInterruptBudgetType { kLoop
, kReturn
 }
Functions
void Uint32Mod (MaglevAssembler *masm, Register out, Register left, Register right)
void HandleInterruptsAndTiering (MaglevAssembler *masm, ZoneLabelRef done, Node *node, ReduceInterruptBudgetType type, Register scratch0)
void GenerateReduceInterruptBudget (MaglevAssembler *masm, Node *node, Register feedback_cell, ReduceInterruptBudgetType type, int amount)
Enumeration Type Documentation
ReduceInterruptBudgetType
enum v8::internal::maglev::anonymous_namespace{maglev-ir-arm.cc}::ReduceInterruptBudgetType [strong]
Enumerator
kLoop
kReturn
Definition at line 809 of file maglev-ir-arm.cc.
{
Function Documentation
GenerateReduceInterruptBudget()
void v8::internal::maglev::anonymous_namespace{maglev-ir-arm.cc}::GenerateReduceInterruptBudget (MaglevAssembler * masm, Node * node, Register feedback_cell, ReduceInterruptBudgetType type, int amount)
Definition at line 863 of file maglev-ir-arm.cc.
                                                                               {
  MaglevAssembler::TemporaryRegisterScope temps(masm);
  Register budget = temps.Acquire();
  __ ldr(budget,
         FieldMemOperand(feedback_cell, FeedbackCell::kInterruptBudgetOffset));
  __ sub(budget, budget, Operand(amount), SetCC);
  __ str(budget,
         FieldMemOperand(feedback_cell, FeedbackCell::kInterruptBudgetOffset));
  ZoneLabelRef done(masm);
  __ JumpToDeferredIf(lt, HandleInterruptsAndTiering, done, node, type, budget);
HandleInterruptsAndTiering()
void v8::internal::maglev::anonymous_namespace{maglev-ir-arm.cc}::HandleInterruptsAndTiering (MaglevAssembler * masm, ZoneLabelRef done, Node * node, ReduceInterruptBudgetType type, Register scratch0)
Definition at line 811 of file maglev-ir-arm.cc.
                                     { kLoop, kReturn };
void HandleInterruptsAndTiering(MaglevAssembler* masm, ZoneLabelRef done,
                                Node* node, ReduceInterruptBudgetType type,
                                Register scratch0) {
  // For loops, first check for interrupts. Don't do this for returns, as we
  // can't lazy deopt to the end of a return.
  if (type == ReduceInterruptBudgetType::kLoop) {
    Label next;
    // Here, we only care about interrupts since we've already guarded against
    // real stack overflows on function entry.
    {
      Register stack_limit = scratch0;
      __ LoadStackLimit(stack_limit, StackLimitKind::kInterruptStackLimit);
      __ cmp(sp, stack_limit);
      __ b(hi, &next);
    }
    // An interrupt has been requested and we must call into runtime to handle
    // it; since we already pay the call cost, combine with the TieringManager
    // call.
    {
      SaveRegisterStateForCall save_register_state(masm,
                                                   node->register_snapshot());
      Register function = scratch0;
      __ ldr(function, MemOperand(fp, StandardFrameConstants::kFunctionOffset));
      __ Push(function);
      // Move into kContextRegister after the load into scratch0, just in case
      // scratch0 happens to be kContextRegister.
      __ Move(kContextRegister, masm->native_context().object());
      __ CallRuntime(Runtime::kBytecodeBudgetInterruptWithStackCheck_Maglev, 1);
      save_register_state.DefineSafepointWithLazyDeopt(node->lazy_deopt_info());
    }
    __ b(*done); // All done, continue.
    __ bind(&next);
  }
  // No pending interrupts. Call into the TieringManager if needed.
  {
    SaveRegisterStateForCall save_register_state(masm,
                                                 node->register_snapshot());
    Register function = scratch0;
    __ ldr(function, MemOperand(fp, StandardFrameConstants::kFunctionOffset));
    __ Push(function);
    // Move into kContextRegister after the load into scratch0, just in case
    // scratch0 happens to be kContextRegister.
    __ Move(kContextRegister, masm->native_context().object());
    // Note: must not cause a lazy deopt!
    __ CallRuntime(Runtime::kBytecodeBudgetInterrupt_Maglev, 1);
    save_register_state.DefineSafepoint();
  }
Uint32Mod()
void v8::internal::maglev::anonymous_namespace{maglev-ir-arm.cc}::Uint32Mod (MaglevAssembler * masm, Register out, Register left, Register right)
Definition at line 366 of file maglev-ir-arm.cc.
                               {
  MaglevAssembler::TemporaryRegisterScope temps(masm);
  Register res = temps.AcquireScratch();
  if (CpuFeatures::IsSupported(SUDIV)) {
    CpuFeatureScope scope(masm, SUDIV);
    __ udiv(res, left, right);
  } else {
    UseScratchRegisterScope temps(masm);
    LowDwVfpRegister double_right = temps.AcquireLowD();
    SwVfpRegister tmp = double_right.low();
    DwVfpRegister double_left = temps.AcquireD();
    DwVfpRegister double_res = double_left;
    __ vmov(tmp, left);
    __ vcvt_f64_s32(double_left, tmp);
    __ vmov(tmp, right);
    __ vcvt_f64_s32(double_right, tmp);
    __ vdiv(double_res, double_left, double_right);
    __ vcvt_s32_f64(tmp, double_res);
    __ vmov(res, tmp);
  }
  if (CpuFeatures::IsSupported(ARMv7)) {
    __ mls(out, res, right, left);
  } else {
    __ mul(res, res, right);
    __ sub(out, left, res);
  }
}
References __, v8::internal::UseScratchRegisterScope::AcquireD(), v8::internal::UseScratchRegisterScope::AcquireLowD(), v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), v8::internal::CpuFeatures::IsSupported(), and v8::internal::LowDwVfpRegister::low().
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::BinOpImpl(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::BuildUint32Mod(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::Typer::Visitor::TypeNode(), v8::internal::compiler::RawMachineAssembler::Uint32Mod(), v8::internal::compiler::SimplifiedLoweringVerifier::VisitNode(), and v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::WordBinopDeoptOnOverflow().