v8::internal::maglev::anonymous_namespace{maglev-compilation-info.cc} Namespace Reference
Classes
class MaglevCompilationHandleScope
Functions
static bool SpecializeToFunctionContext (Isolate *isolate, BytecodeOffset osr_offset, DirectHandle< JSFunction > function, std::optional< bool > specialize_to_function_context_override)
template<typename T >
IndirectHandle< T > CanonicalHandle (CanonicalHandlesMap *canonical_handles, Tagged< T > object, Isolate *isolate)
Variables
constexpr char kMaglevZoneName [] = `maglev-compilation-job-zone`
Function Documentation
CanonicalHandle()
template<typename T >
IndirectHandle<T> v8::internal::maglev::anonymous_namespace{maglev-compilation-info.cc}::CanonicalHandle (CanonicalHandlesMap * canonical_handles, Tagged< T > object, Isolate * isolate)
Definition at line 140 of file maglev-compilation-info.cc.
                                                                      {
  DCHECK_NOT_NULL(canonical_handles);
  DCHECK(PersistentHandlesScope::IsActive(isolate));
  auto find_result = canonical_handles->FindOrInsert(object);
  if (!find_result.already_exists) {
    *find_result.entry = IndirectHandle<T>(object, isolate).location();
  }
  return IndirectHandle<T>(*find_result.entry);
}
References v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::IdentityMap< V, AllocationPolicy >::FindOrInsert(), v8::internal::PersistentHandlesScope::IsActive(), and v8::internal::HandleBase::location().
Referenced by v8::internal::compiler::TFPipelineData::ChooseSpecializationContext(), and v8::internal::maglev::MaglevCompilationInfo::ReopenAndCanonicalizeHandlesInNewScope().
SpecializeToFunctionContext()
static bool v8::internal::maglev::anonymous_namespace{maglev-compilation-info.cc}::SpecializeToFunctionContext (Isolate * isolate, BytecodeOffset osr_offset, DirectHandle< JSFunction > function, std::optional< bool > specialize_to_function_context_override) [static]
Definition at line 49 of file maglev-compilation-info.cc.
                                                               {
  if (osr_offset != BytecodeOffset::None()) return false;
  if (!v8_flags.maglev_function_context_specialization) return false;
  if (specialize_to_function_context_override.has_value()) {
    return specialize_to_function_context_override.value();
  }
  if (function->shared()->function_context_independent_compiled()) {
    return false;
  }
  return function->raw_feedback_cell()->map() ==
         ReadOnlyRoots(isolate).one_closure_cell_map();
}
References v8::internal::BytecodeOffset::None(), and v8::internal::v8_flags.
Variable Documentation
kMaglevZoneName
constexpr char v8::internal::maglev::anonymous_namespace{maglev-compilation-info.cc}::kMaglevZoneName[] = `maglev-compilation-job-zone` [constexpr]
Definition at line 30 of file maglev-compilation-info.cc.