v8::anonymous_namespace{d8-posix.cc} Namespace Reference
Functions
v8::Local< v8::String > v8_strerror (v8::Isolate *isolate, int err)
Function Documentation
v8_strerror()
v8::Local<v8::String> v8::anonymous_namespace{d8-posix.cc}::v8_strerror (v8::Isolate * isolate, int err)
Definition at line 242 of file d8-posix.cc.
                                                           {
  return v8::String::NewFromUtf8(isolate, strerror(err)).ToLocalChecked();
}
References v8::String::NewFromUtf8().
Referenced by v8::Shell::ChangeDirectory(), v8::CheckItsADirectory(), v8::ChildLaunchedOK(), v8::GetStdout(), and v8::mkdirp().