v8::internal::maglev::anonymous_namespace{maglev-assembler-x64.cc} Namespace Reference
Functions
void LoadNewAllocationTop (MaglevAssembler *masm, Register new_top, Register object, int size_in_bytes)
void LoadNewAllocationTop (MaglevAssembler *masm, Register new_top, Register object, Register size_in_bytes)
template<typename T >
void AllocateRaw (MaglevAssembler *masm, Isolate *isolate, RegisterSnapshot register_snapshot, Register object, T size_in_bytes, AllocationType alloc_type, AllocationAlignment alignment)
Function Documentation
AllocateRaw()
template<typename T >
void v8::internal::maglev::anonymous_namespace{maglev-assembler-x64.cc}::AllocateRaw (MaglevAssembler * masm, Isolate * isolate, RegisterSnapshot register_snapshot, Register object, T size_in_bytes, AllocationType alloc_type, AllocationAlignment alignment)
Definition at line 38 of file maglev-assembler-x64.cc.
                                                {
  // TODO(victorgomes): Call the runtime for large object allocation.
  // TODO(victorgomes): Support double alignment.
  DCHECK_EQ(alignment, kTaggedAligned);
  if (v8_flags.single_generation) {
    alloc_type = AllocationType::kOld;
  }
  ExternalReference top = SpaceAllocationTopAddress(isolate, alloc_type);
  ExternalReference limit = SpaceAllocationLimitAddress(isolate, alloc_type);
  ZoneLabelRef done(masm);
  Register new_top = kScratchRegister;
  // Check if there is enough space.
  __ Move(object, __ ExternalReferenceAsOperand(top));
  LoadNewAllocationTop(masm, new_top, object, size_in_bytes);
  __ cmpq(new_top, __ ExternalReferenceAsOperand(limit));
  // Otherwise call runtime.
  __ JumpToDeferredIf(kUnsignedGreaterThanEqual, AllocateSlow<T>,
                      register_snapshot, object, AllocateBuiltin(alloc_type),
                      size_in_bytes, done);
  // Store new top and tag object.
  __ movq(__ ExternalReferenceAsOperand(top), new_top);
  __ addq(object, Immediate(kHeapObjectTag));
  __ bind(*done);
}
References __, v8::internal::maglev::AllocateBuiltin(), DCHECK_EQ, v8::internal::kHeapObjectTag, v8::internal::kOld, v8::internal::kScratchRegister, v8::internal::kTaggedAligned, v8::internal::kUnsignedGreaterThanEqual, LoadNewAllocationTop(), v8::internal::maglev::SpaceAllocationLimitAddress(), v8::internal::maglev::SpaceAllocationTopAddress(), and v8::internal::v8_flags.
LoadNewAllocationTop() [1/2]
void v8::internal::maglev::anonymous_namespace{maglev-assembler-x64.cc}::LoadNewAllocationTop (MaglevAssembler * masm, Register new_top, Register object, int size_in_bytes)
Definition at line 26 of file maglev-assembler-x64.cc.
                                                              {
  __ leaq(new_top, Operand(object, size_in_bytes));
}
References __.
LoadNewAllocationTop() [2/2]
void v8::internal::maglev::anonymous_namespace{maglev-assembler-x64.cc}::LoadNewAllocationTop (MaglevAssembler * masm, Register new_top, Register object, Register size_in_bytes)
Definition at line 31 of file maglev-assembler-x64.cc.
                                                                   {
  __ Move(new_top, object);
  __ addq(new_top, size_in_bytes);
}
References __.
Referenced by AllocateRaw().