v8::internal::anonymous_namespace{string-forwarding-table.cc} Namespace Reference
Functions
bool UpdateForwardedSlot (Tagged< HeapObject > object, OffHeapObjectSlot slot)
bool UpdateForwardedSlot (Tagged< Object > object, OffHeapObjectSlot slot)
Function Documentation
UpdateForwardedSlot() [1/2]
bool v8::internal::anonymous_namespace{string-forwarding-table.cc}::UpdateForwardedSlot (Tagged< HeapObject > object, OffHeapObjectSlot slot)
Definition at line 74 of file string-forwarding-table.cc.
                                                                            {
  MapWord map_word = object->map_word(kRelaxedLoad);
  if (map_word.IsForwardingAddress()) {
    Tagged<HeapObject> forwarded_object = map_word.ToForwardingAddress(object);
    slot.Release_Store(forwarded_object);
    return true;
  }
  return false;
}
References v8::internal::MapWord::IsForwardingAddress(), v8::kRelaxedLoad, v8::internal::FullObjectSlot::Release_Store(), and v8::internal::MapWord::ToForwardingAddress().
UpdateForwardedSlot() [2/2]
bool v8::internal::anonymous_namespace{string-forwarding-table.cc}::UpdateForwardedSlot (Tagged< Object > object, OffHeapObjectSlot slot)
Definition at line 84 of file string-forwarding-table.cc.
                                                                        {
  if (!IsHeapObject(object)) return false;
  return UpdateForwardedSlot(Cast<HeapObject>(object), slot);
}
References v8::internal::IsHeapObject().
Referenced by v8::internal::StringForwardingTable::Block::UpdateAfterFullEvacuation(), and v8::internal::StringForwardingTable::Block::UpdateAfterYoungEvacuation().