v8::internal::trap_handler Namespace Reference
Namespaces
 anonymous_namespace{handler-outside.cc}
Classes
struct CodeProtectionInfo
class MetadataLock
struct CodeProtectionInfoListEntry
struct SandboxRecord
class SandboxRecordsLock
struct ProtectedInstructionData
Functions
void HandleSignal (int signum, siginfo_t *info, void *context)
bool TryHandleSignal (int signum, siginfo_t *info, void *context)
LONG WINAPI HandleWasmTrap (EXCEPTION_POINTERS *exception)
TH_DISABLE_ASAN bool TryHandleWasmTrap (EXCEPTION_POINTERS *exception)
constexpr size_t HandlerDataSize (size_t num_protected_instructions)
CodeProtectionInfo * CreateHandlerData (uintptr_t base, size_t size, size_t num_protected_instructions, const ProtectedInstructionData *protected_instructions)
int RegisterHandlerData (uintptr_t base, size_t size, size_t num_protected_instructions, const ProtectedInstructionData *protected_instructions)
Adds the handler data to the place where the trap handler will find it.
void ReleaseHandlerData (int index)
Removes the data from the master list and frees any memory, if necessary.
bool RegisterV8Sandbox (uintptr_t base, size_t size)
Registers the base and size of the V8 sandbox region into list of sandboxes records.
void UnregisterV8Sandbox (uintptr_t base, size_t size)
Unregisters the base and size of the V8 sandbox region decribed by base and size.
int * GetThreadInWasmThreadLocalAddress ()
size_t GetRecoveredTrapCount ()
bool RegisterDefaultTrapHandler ()
void RemoveTrapHandler ()
bool EnableTrapHandler (bool use_v8_handler)
void SetLandingPad (uintptr_t landing_pad)
bool IsFaultAddressCovered (uintptr_t fault_addr)
bool IsAccessedMemoryCovered (uintptr_t accessed_addr)
bool IsTrapHandlerEnabled ()
TH_DISABLE_ASAN bool IsThreadInWasm ()
void SetThreadInWasm ()
void ClearThreadInWasm ()
void AssertThreadNotInWasm ()
Variables
constexpr size_t kInitialCodeObjectSize = 1024
constexpr size_t kCodeObjectGrowthFactor = 2
bool g_is_trap_handler_enabled {false}
std::atomic< bool > g_can_enable_trap_handler {true}
thread_local int g_thread_in_wasm_code
size_t gNumCodeObjects = 0
CodeProtectionInfoListEntry * gCodeObjects = nullptr
SandboxRecord * gSandboxRecordsHead = nullptr
std::atomic_size_t gRecoveredTrapCount = {0}
std::atomic< uintptr_t > gLandingPad = {0}
const int kInvalidIndex = -1
Function Documentation
AssertThreadNotInWasm()
void v8::internal::trap_handler::AssertThreadNotInWasm () [inline]
Definition at line 220 of file trap-handler.h.
                                    {
  TH_DCHECK(!g_is_trap_handler_enabled || !g_thread_in_wasm_code);
}
References g_is_trap_handler_enabled, g_thread_in_wasm_code, and TH_DCHECK.
Referenced by v8::internal::HeapAllocator::AllocateRaw(), v8::internal::Isolate::Throw(), and v8::internal::anonymous_namespace{runtime-wasm.cc}::ClearThreadInWasmScope::~ClearThreadInWasmScope().
ClearThreadInWasm()
void v8::internal::trap_handler::ClearThreadInWasm () [inline]
Definition at line 199 of file trap-handler.h.
                                {
  if (IsTrapHandlerEnabled()) {
    TH_DCHECK(IsThreadInWasm());
    g_thread_in_wasm_code = false;
  }
}
References g_thread_in_wasm_code, IsThreadInWasm(), IsTrapHandlerEnabled(), and TH_DCHECK.
Referenced by v8::internal::wasm::WasmInterpreterRuntime::CallWasmToJSBuiltin(), v8::internal::anonymous_namespace{runtime-wasm.cc}::ClearThreadInWasmScope::ClearThreadInWasmScope(), v8::internal::wasm::ClearThreadInWasmScope::ClearThreadInWasmScope(), v8::internal::Deoptimizer::DoComputeOutputFrames(), v8::internal::wasm::WasmInterpreterRuntime::JSToWasmObject(), v8::internal::RUNTIME_FUNCTION(), and v8::internal::Isolate::UnwindAndFindHandler().
CreateHandlerData()
CodeProtectionInfo* v8::internal::trap_handler::CreateHandlerData (uintptr_t base, size_t size, size_t num_protected_instructions, const ProtectedInstructionData * protected_instructions)
Definition at line 109 of file handler-outside.cc.
                                                            {
  const size_t alloc_size = HandlerDataSize(num_protected_instructions);
  CodeProtectionInfo* data =
      reinterpret_cast<CodeProtectionInfo*>(malloc(alloc_size));
  if (data == nullptr) {
    return nullptr;
  }
  data->base = base;
  data->size = size;
  data->num_protected_instructions = num_protected_instructions;
  if (num_protected_instructions > 0) {
    memcpy(data->instructions, protected_instructions,
           num_protected_instructions * sizeof(ProtectedInstructionData));
  }
  return data;
}
References v8::internal::trap_handler::CodeProtectionInfo::base, HandlerDataSize(), v8::internal::trap_handler::CodeProtectionInfo::instructions, v8::internal::trap_handler::CodeProtectionInfo::num_protected_instructions, size(), and v8::internal::trap_handler::CodeProtectionInfo::size.
Referenced by RegisterHandlerData().
EnableTrapHandler()
TH_EXPORT_PRIVATE bool v8::internal::trap_handler::EnableTrapHandler (bool use_v8_handler)
Definition at line 299 of file handler-outside.cc.
                                            {
  // We should only enable the trap handler once, and before any call to
  // {IsTrapHandlerEnabled}. Enabling the trap handler late can lead to problems
  // because code or objects might have been generated under the assumption that
  // trap handlers are disabled.
  bool can_enable =
      g_can_enable_trap_handler.exchange(false, std::memory_order_relaxed);
  // EnableTrapHandler called twice, or after IsTrapHandlerEnabled.
  TH_CHECK(can_enable);
  if (!V8_TRAP_HANDLER_SUPPORTED) {
    return false;
  }
  if (use_v8_handler) {
    g_is_trap_handler_enabled = RegisterDefaultTrapHandler();
    return g_is_trap_handler_enabled;
  }
  g_is_trap_handler_enabled = true;
  return true;
}
References g_can_enable_trap_handler, g_is_trap_handler_enabled, RegisterDefaultTrapHandler(), TH_CHECK, and V8_TRAP_HANDLER_SUPPORTED.
Referenced by v8::V8::EnableWebAssemblyTrapHandler().
GetRecoveredTrapCount()
TH_EXPORT_PRIVATE size_t v8::internal::trap_handler::GetRecoveredTrapCount ()
Definition at line 283 of file handler-outside.cc.
                               {
  return gRecoveredTrapCount.load(std::memory_order_relaxed);
}
References gRecoveredTrapCount.
Referenced by v8::internal::RUNTIME_FUNCTION().
GetThreadInWasmThreadLocalAddress()
V8_NOINLINE TH_EXPORT_PRIVATE int * v8::internal::trap_handler::GetThreadInWasmThreadLocalAddress ()
Definition at line 281 of file handler-outside.cc.
{ return &g_thread_in_wasm_code; }
References g_thread_in_wasm_code.
Referenced by v8::internal::ThreadLocalTop::Initialize().
HandlerDataSize()
constexpr size_t v8::internal::trap_handler::HandlerDataSize (size_t num_protected_instructions) [constexpr]
Definition at line 49 of file handler-outside.cc.
                                                                    {
  return offsetof(CodeProtectionInfo, instructions) +
         num_protected_instructions * sizeof(ProtectedInstructionData);
}
Referenced by CreateHandlerData().
HandleSignal()
void v8::internal::trap_handler::HandleSignal (int signum, siginfo_t * info, void * context)
HandleWasmTrap()
LONG WINAPI v8::internal::trap_handler::HandleWasmTrap (EXCEPTION_POINTERS * exception)
IsAccessedMemoryCovered()
bool v8::internal::trap_handler::IsAccessedMemoryCovered (uintptr_t accessed_addr)
IsFaultAddressCovered()
bool v8::internal::trap_handler::IsFaultAddressCovered (uintptr_t fault_addr)
IsThreadInWasm()
TH_DISABLE_ASAN bool v8::internal::trap_handler::IsThreadInWasm () [inline]
Definition at line 190 of file trap-handler.h.
{ return g_thread_in_wasm_code; }
References g_thread_in_wasm_code.
Referenced by v8::internal::wasm::WasmInterpreterRuntime::CallWasmToJSBuiltin(), ClearThreadInWasm(), v8::internal::wasm::ClearThreadInWasmScope::ClearThreadInWasmScope(), v8::internal::wasm::WasmInterpreterRuntime::ExecuteCallRef(), v8::internal::wasm::WasmInterpreterRuntime::ExecuteFunction(), v8::internal::wasm::WasmInterpreterRuntime::ExecuteImportedFunction(), v8::internal::wasm::WasmInterpreterRuntime::ExecuteIndirectCall(), v8::internal::wasm::WasmInterpreterRuntime::JSToWasmObject(), v8::internal::wasm::WasmInterpreterThread::Run(), v8::internal::wasm::InterpreterHandle::RunExecutionLoop(), v8::internal::RUNTIME_FUNCTION(), SetThreadInWasm(), v8::internal::wasm::WasmInterpreterRuntime::ThrowException(), v8::internal::Isolate::UnwindAndFindHandler(), and v8::internal::wasm::ClearThreadInWasmScope::~ClearThreadInWasmScope().
IsTrapHandlerEnabled()
bool v8::internal::trap_handler::IsTrapHandlerEnabled () [inline]
Definition at line 162 of file trap-handler.h.
                                   {
  TH_DCHECK(!g_is_trap_handler_enabled || V8_TRAP_HANDLER_SUPPORTED);
  // Disallow enabling the trap handler after retrieving the current value.
  // Re-enabling them late can produce issues because code or objects might have
  // been generated under the assumption that trap handlers are disabled.
  // Note: We test before setting to avoid contention by an unconditional write.
  if (g_can_enable_trap_handler.load(std::memory_order_relaxed)) {
    g_can_enable_trap_handler.store(false, std::memory_order_relaxed);
  }
  return g_is_trap_handler_enabled;
}
References g_can_enable_trap_handler, g_is_trap_handler_enabled, TH_DCHECK, and V8_TRAP_HANDLER_SUPPORTED.
Referenced by v8::internal::compiler::WasmGraphBuilder::BuildModifyThreadInWasmFlag(), v8::internal::wasm::WasmGraphBuilderBase::BuildModifyThreadInWasmFlag(), ClearThreadInWasm(), v8::internal::wasm::ClearThreadInWasmScope::ClearThreadInWasmScope(), v8::internal::wasm::TurboshaftGraphBuildingInterface::GetRttFromDescriptor(), v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::ModifyThreadInWasmFlagScope::ModifyThreadInWasmFlagScope(), v8::internal::wasm::WasmWrapperTSGraphBuilder::ModifyThreadInWasmFlagScope::ModifyThreadInWasmFlagScope(), v8::internal::RUNTIME_FUNCTION(), SetThreadInWasm(), v8::internal::wasm::UpdateComputedInformation(), v8::internal::compiler::WasmGraphBuilder::WasmGraphBuilder(), v8::internal::wasm::ClearThreadInWasmScope::~ClearThreadInWasmScope(), v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::ModifyThreadInWasmFlagScope::~ModifyThreadInWasmFlagScope(), and v8::internal::wasm::WasmWrapperTSGraphBuilder::ModifyThreadInWasmFlagScope::~ModifyThreadInWasmFlagScope().
RegisterDefaultTrapHandler()
bool v8::internal::trap_handler::RegisterDefaultTrapHandler ()
Definition at line 291 of file handler-outside.cc.
{ return false; }
Referenced by EnableTrapHandler().
RegisterHandlerData()
int TH_EXPORT_PRIVATE v8::internal::trap_handler::RegisterHandlerData (uintptr_t base, size_t size, size_t num_protected_instructions, const ProtectedInstructionData * protected_instructions)
Adds the handler data to the place where the trap handler will find it.
This returns a number that can be used to identify the handler data to ReleaseHandlerData, or -1 on failure.
Definition at line 132 of file handler-outside.cc.
                                                            {
  CodeProtectionInfo* data = CreateHandlerData(
      base, size, num_protected_instructions, protected_instructions);
  if (data == nullptr) {
    abort();
  }
  MetadataLock lock;
  if (kEnableSlowChecks) {
    VerifyCodeRangeIsDisjoint(data);
  }
  size_t i = gNextCodeObject;
  // Explicitly convert std::numeric_limits<int>::max() to unsigned to avoid
  // compiler warnings about signed/unsigned comparisons. We aren't worried
  // about sign extension because we know std::numeric_limits<int>::max() is
  // positive.
  const size_t int_max = std::numeric_limits<int>::max();
  // We didn't find an opening in the available space, so grow.
  if (i == gNumCodeObjects) {
    size_t new_size = gNumCodeObjects > 0
                          ? gNumCodeObjects * kCodeObjectGrowthFactor
                          : kInitialCodeObjectSize;
    // Because we must return an int, there is no point in allocating space for
    // more objects than can fit in an int.
    if (new_size > int_max) {
      new_size = int_max;
    }
    if (new_size == gNumCodeObjects) {
      free(data);
      return kInvalidIndex;
    }
    // Now that we know our new size is valid, we can go ahead and realloc the
    // array.
    gCodeObjects = static_cast<CodeProtectionInfoListEntry*>(
        realloc(gCodeObjects, sizeof(*gCodeObjects) * new_size));
    if (gCodeObjects == nullptr) {
      abort();
    }
    memset(gCodeObjects + gNumCodeObjects, 0,
           sizeof(*gCodeObjects) * (new_size - gNumCodeObjects));
    for (size_t j = gNumCodeObjects; j < new_size; ++j) {
      gCodeObjects[j].next_free = j + 1;
    }
    gNumCodeObjects = new_size;
  }
  TH_DCHECK(gCodeObjects[i].code_info == nullptr);
  // Find out where the next entry should go.
  gNextCodeObject = gCodeObjects[i].next_free;
  if (i <= int_max) {
    gCodeObjects[i].code_info = data;
    if (kEnableSlowChecks) {
      ValidateCodeObjects();
    }
    return static_cast<int>(i);
  } else {
    free(data);
    return kInvalidIndex;
  }
}
References v8::internal::trap_handler::CodeProtectionInfoListEntry::code_info, CreateHandlerData(), gCodeObjects, anonymous_namespace{handler-outside.cc}::gNextCodeObject, gNumCodeObjects, v8::internal::anonymous_namespace{json-stringifier.cc}::i, kCodeObjectGrowthFactor, anonymous_namespace{handler-outside.cc}::kEnableSlowChecks, kInitialCodeObjectSize, kInvalidIndex, v8::internal::trap_handler::CodeProtectionInfoListEntry::next_free, size(), TH_DCHECK, v8::internal::trap_handler::anonymous_namespace{handler-outside.cc}::ValidateCodeObjects(), and v8::internal::trap_handler::anonymous_namespace{handler-outside.cc}::VerifyCodeRangeIsDisjoint().
Referenced by v8::internal::wasm::WasmCode::RegisterTrapHandlerData().
RegisterV8Sandbox()
bool TH_EXPORT_PRIVATE v8::internal::trap_handler::RegisterV8Sandbox (uintptr_t base, size_t size)
Registers the base and size of the V8 sandbox region into list of sandboxes records.
If successful, these will be used by the trap handler: only faulting accesses to memory inside the V8 sandboxes should be handled by the trap handler since all Wasm memory objects are located inside the sandboxes.
Definition at line 235 of file handler-outside.cc.
                                                    {
  SandboxRecordsLock lock;
#ifdef DEBUG
  for (SandboxRecord* current = gSandboxRecordsHead; current != nullptr;
       current = current->next) {
    TH_DCHECK(current->base != base);
  }
#endif
  SandboxRecord* new_record =
      reinterpret_cast<SandboxRecord*>(malloc(sizeof(SandboxRecord)));
  if (new_record == nullptr) {
    return false;
  }
  new_record->base = base;
  new_record->size = size;
  new_record->next = gSandboxRecordsHead;
  gSandboxRecordsHead = new_record;
  return true;
}
References v8::internal::trap_handler::SandboxRecord::base, gSandboxRecordsHead, v8::internal::trap_handler::SandboxRecord::next, size(), v8::internal::trap_handler::SandboxRecord::size, and TH_DCHECK.
ReleaseHandlerData()
void TH_EXPORT_PRIVATE v8::internal::trap_handler::ReleaseHandlerData (int index)
Removes the data from the master list and frees any memory, if necessary.
TODO(mtrofin): We can switch to using size_t for index and not need kInvalidIndex.
Definition at line 208 of file handler-outside.cc.
                                   {
  if (index == kInvalidIndex) {
    return;
  }
  TH_DCHECK(index >= 0);
  // Remove the data from the global list if it's there.
  CodeProtectionInfo* data = nullptr;
  {
    MetadataLock lock;
    data = gCodeObjects[index].code_info;
    gCodeObjects[index].code_info = nullptr;
    gCodeObjects[index].next_free = gNextCodeObject;
    gNextCodeObject = index;
    if (kEnableSlowChecks) {
      ValidateCodeObjects();
    }
  }
  // TODO(eholk): on debug builds, ensure there are no more copies in
  // the list.
  TH_DCHECK(data); // make sure we're releasing legitimate handler data.
  free(data);
}
References v8::internal::trap_handler::CodeProtectionInfoListEntry::code_info, gCodeObjects, anonymous_namespace{handler-outside.cc}::gNextCodeObject, v8::internal::index, anonymous_namespace{handler-outside.cc}::kEnableSlowChecks, kInvalidIndex, v8::internal::trap_handler::CodeProtectionInfoListEntry::next_free, TH_DCHECK, and v8::internal::trap_handler::anonymous_namespace{handler-outside.cc}::ValidateCodeObjects().
Referenced by v8::internal::wasm::WasmCode::~WasmCode().
RemoveTrapHandler()
TH_EXPORT_PRIVATE void v8::internal::trap_handler::RemoveTrapHandler ()
Definition at line 293 of file handler-outside.cc.
{}
SetLandingPad()
TH_EXPORT_PRIVATE void v8::internal::trap_handler::SetLandingPad (uintptr_t landing_pad)
Definition at line 319 of file handler-outside.cc.
{ gLandingPad.store(landing_pad); }
References gLandingPad.
Referenced by v8::internal::Isolate::Isolate(), and v8::internal::wasm::WasmInterpreter::WasmInterpreter().
SetThreadInWasm()
void v8::internal::trap_handler::SetThreadInWasm () [inline]
Definition at line 192 of file trap-handler.h.
                              {
  if (IsTrapHandlerEnabled()) {
    TH_DCHECK(!IsThreadInWasm());
    g_thread_in_wasm_code = true;
  }
}
References g_thread_in_wasm_code, IsThreadInWasm(), IsTrapHandlerEnabled(), and TH_DCHECK.
Referenced by v8::internal::wasm::WasmInterpreterRuntime::CallWasmToJSBuiltin(), v8::internal::Deoptimizer::DoComputeOutputFrames(), v8::internal::wasm::WasmInterpreterThread::Run(), v8::internal::wasm::InterpreterHandle::RunExecutionLoop(), v8::internal::anonymous_namespace{runtime-wasm.cc}::ClearThreadInWasmScope::~ClearThreadInWasmScope(), and v8::internal::wasm::ClearThreadInWasmScope::~ClearThreadInWasmScope().
TryHandleSignal()
bool v8::internal::trap_handler::TryHandleSignal (int signum, siginfo_t * info, void * context)
TryHandleWasmTrap()
TH_DISABLE_ASAN bool v8::internal::trap_handler::TryHandleWasmTrap (EXCEPTION_POINTERS * exception)
UnregisterV8Sandbox()
void TH_EXPORT_PRIVATE v8::internal::trap_handler::UnregisterV8Sandbox (uintptr_t base, size_t size)
Unregisters the base and size of the V8 sandbox region decribed by base and size.
Definition at line 258 of file handler-outside.cc.
                                                      {
  SandboxRecordsLock lock;
  SandboxRecord* current = gSandboxRecordsHead;
  SandboxRecord* previous = nullptr;
  while (current != nullptr) {
    if (current->base == base) {
      break;
    }
    previous = current;
    current = current->next;
  }
  TH_CHECK(current != nullptr);
  TH_CHECK(current->size == size);
  if (previous) {
    previous->next = current->next;
  } else {
    gSandboxRecordsHead = current->next;
  }
  free(current);
}
References v8::internal::trap_handler::SandboxRecord::base, gSandboxRecordsHead, v8::internal::trap_handler::SandboxRecord::next, size(), v8::internal::trap_handler::SandboxRecord::size, and TH_CHECK.
Variable Documentation
g_can_enable_trap_handler
TH_EXPORT_PRIVATE std::atomic< bool > v8::internal::trap_handler::g_can_enable_trap_handler {true}
Definition at line 297 of file handler-outside.cc.
Referenced by EnableTrapHandler(), and IsTrapHandlerEnabled().
g_is_trap_handler_enabled
TH_EXPORT_PRIVATE bool v8::internal::trap_handler::g_is_trap_handler_enabled {false}
Definition at line 296 of file handler-outside.cc.
Referenced by AssertThreadNotInWasm(), EnableTrapHandler(), and IsTrapHandlerEnabled().
g_thread_in_wasm_code
thread_local int v8::internal::trap_handler::g_thread_in_wasm_code
Definition at line 30 of file handler-shared.cc.
Referenced by AssertThreadNotInWasm(), ClearThreadInWasm(), GetThreadInWasmThreadLocalAddress(), IsThreadInWasm(), v8::internal::trap_handler::MetadataLock::MetadataLock(), SetThreadInWasm(), and v8::internal::trap_handler::MetadataLock::~MetadataLock().
gCodeObjects
CodeProtectionInfoListEntry * v8::internal::trap_handler::gCodeObjects = nullptr
Definition at line 37 of file handler-shared.cc.
Referenced by RegisterHandlerData(), ReleaseHandlerData(), v8::internal::trap_handler::anonymous_namespace{handler-outside.cc}::ValidateCodeObjects(), and v8::internal::trap_handler::anonymous_namespace{handler-outside.cc}::VerifyCodeRangeIsDisjoint().
gLandingPad
std::atomic< uintptr_t > v8::internal::trap_handler::gLandingPad = {0}
Definition at line 40 of file handler-shared.cc.
Referenced by SetLandingPad().
gNumCodeObjects
size_t v8::internal::trap_handler::gNumCodeObjects = 0
Definition at line 36 of file handler-shared.cc.
Referenced by RegisterHandlerData(), v8::internal::trap_handler::anonymous_namespace{handler-outside.cc}::ValidateCodeObjects(), and v8::internal::trap_handler::anonymous_namespace{handler-outside.cc}::VerifyCodeRangeIsDisjoint().
gRecoveredTrapCount
std::atomic_size_t v8::internal::trap_handler::gRecoveredTrapCount = {0}
Definition at line 39 of file handler-shared.cc.
Referenced by GetRecoveredTrapCount().
gSandboxRecordsHead
SandboxRecord * v8::internal::trap_handler::gSandboxRecordsHead = nullptr
Definition at line 38 of file handler-shared.cc.
Referenced by RegisterV8Sandbox(), and UnregisterV8Sandbox().
kCodeObjectGrowthFactor
constexpr size_t v8::internal::trap_handler::kCodeObjectGrowthFactor = 2 [constexpr]
Definition at line 47 of file handler-outside.cc.
Referenced by RegisterHandlerData().
kInitialCodeObjectSize
constexpr size_t v8::internal::trap_handler::kInitialCodeObjectSize = 1024 [constexpr]
Definition at line 46 of file handler-outside.cc.
Referenced by RegisterHandlerData().
kInvalidIndex
const int v8::internal::trap_handler::kInvalidIndex = -1
Definition at line 115 of file trap-handler.h.
Referenced by v8::internal::BUILTIN(), v8::internal::EternalHandles::Create(), v8::internal::interpreter::Register::is_valid(), v8::internal::LookupIterator::IsElement(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::PatchNamedBackReferences(), RegisterHandlerData(), ReleaseHandlerData(), and v8::internal::MessageFormatter::TryFormat().