v8::internal::wasm::anonymous_namespace{wasm-external-refs.cc} Namespace Reference
Classes
class ThreadNotInWasmScope
Functions
uint8_t * EffectiveAddress (Tagged< WasmTrustedInstanceData > trusted_data, uint32_t mem_index, uintptr_t index)
template<typename V >
V ReadAndIncrementOffset (Address data, size_t *offset)
void * ArrayElementAddress (Address array, uint32_t index, int element_size_bytes)
void * ArrayElementAddress (Tagged< WasmArray > array, uint32_t index, int element_size_bytes)
Variables
constexpr int32_t kSuccess = 1
constexpr int32_t kOutOfBounds = 0
Function Documentation
ArrayElementAddress() [1/2]
void* v8::internal::wasm::anonymous_namespace{wasm-external-refs.cc}::ArrayElementAddress (Address array, uint32_t index, int element_size_bytes) [inline]
Definition at line 814 of file wasm-external-refs.cc.
                                                         {
  return reinterpret_cast<void*>(array + WasmArray::kHeaderSize -
                                 kHeapObjectTag + index * element_size_bytes);
}
References v8::internal::index, and v8::internal::kHeapObjectTag.
ArrayElementAddress() [2/2]
void* v8::internal::wasm::anonymous_namespace{wasm-external-refs.cc}::ArrayElementAddress (Tagged< WasmArray > array, uint32_t index, int element_size_bytes) [inline]
Definition at line 819 of file wasm-external-refs.cc.
                                                         {
  return ArrayElementAddress(array.ptr(), index, element_size_bytes);
}
References v8::internal::index, and v8::internal::TaggedImpl< kRefType, StorageType >::ptr().
Referenced by v8::internal::wasm::array_copy_wrapper(), and v8::internal::wasm::array_fill_wrapper().
EffectiveAddress()
uint8_t* v8::internal::wasm::anonymous_namespace{wasm-external-refs.cc}::EffectiveAddress (Tagged< WasmTrustedInstanceData > trusted_data, uint32_t mem_index, uintptr_t index) [inline]
Definition at line 741 of file wasm-external-refs.cc.
                                                                      {
  return trusted_data->memory_base(mem_index) + index;
}
References v8::internal::index.
Referenced by v8::internal::wasm::memory_copy_wrapper(), v8::internal::wasm::memory_fill_wrapper(), and v8::internal::wasm::memory_init_wrapper().
ReadAndIncrementOffset()
template<typename V >
V v8::internal::wasm::anonymous_namespace{wasm-external-refs.cc}::ReadAndIncrementOffset (Address data, size_t * offset)
Definition at line 747 of file wasm-external-refs.cc.
                                                       {
  V result = ReadUnalignedValue<V>(data + *offset);
  *offset += sizeof(V);
  return result;
}
References v8::base::internal::result.
Variable Documentation
kOutOfBounds
constexpr int32_t v8::internal::wasm::anonymous_namespace{wasm-external-refs.cc}::kOutOfBounds = 0 [constexpr]
Definition at line 754 of file wasm-external-refs.cc.
Referenced by v8::internal::wasm::memory_copy_wrapper(), v8::internal::wasm::memory_fill_wrapper(), v8::internal::wasm::memory_init_wrapper(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::maglev::MaglevGraphBuilder::TryBuildElementLoadOnJSArrayOrJSObject(), v8::internal::maglev::MaglevGraphBuilder::TryBuildElementStoreOnJSArrayOrJSObject(), and v8::internal::maglev::MaglevGraphBuilder::TryReduceConstantStringAt().
kSuccess
constexpr int32_t v8::internal::wasm::anonymous_namespace{wasm-external-refs.cc}::kSuccess = 1 [constexpr]
Definition at line 753 of file wasm-external-refs.cc.