v8::internal::compiler::anonymous_namespace{js-inlining-heuristic.cc} Namespace Reference
Classes
struct NodeAndIndex
Functions
bool IsSmall (int const size)
bool IsSmallWithHeapNumberParam (int const size)
bool HasHeapNumberInputOrOutput (Node *node)
bool CanConsiderForInlining (JSHeapBroker *broker, FeedbackCellRef feedback_cell)
bool CanConsiderForInlining (JSHeapBroker *broker, JSFunctionRef function)
bool CollectStateValuesOwnedUses (Node *node, Node *state_values, NodeAndIndex *uses_buffer, size_t *use_count, size_t max_uses)
bool CollectFrameStateUniqueUses (Node *node, FrameState frame_state, NodeAndIndex *uses_buffer, size_t *use_count, size_t max_uses)
Function Documentation
CanConsiderForInlining() [1/2]
bool v8::internal::compiler::anonymous_namespace{js-inlining-heuristic.cc}::CanConsiderForInlining (JSHeapBroker * broker, FeedbackCellRef feedback_cell)
Definition at line 74 of file js-inlining-heuristic.cc.
                                                           {
  OptionalFeedbackVectorRef feedback_vector =
      feedback_cell.feedback_vector(broker);
  if (!feedback_vector.has_value()) {
    TRACE("Cannot consider " << feedback_cell
                             << " for inlining (no feedback vector)");
    return false;
  }
  SharedFunctionInfoRef shared = feedback_vector->shared_function_info(broker);
  if (!shared.HasBytecodeArray()) {
    TRACE("Cannot consider " << shared << " for inlining (no bytecode)");
    return false;
  }
  // Ensure we have a persistent handle to the bytecode in order to avoid
  // flushing it during the remaining compilation.
  shared.GetBytecodeArray(broker);
  // Read feedback vector again in case it got flushed before we were able to
  // prevent flushing above.
  OptionalFeedbackVectorRef feedback_vector_again =
      feedback_cell.feedback_vector(broker);
  if (!feedback_vector_again.has_value()) {
    TRACE("Cannot consider " << shared << " for inlining (no feedback vector)");
    return false;
  }
  if (!feedback_vector_again->equals(*feedback_vector)) {
    // The new feedback vector likely contains lots of uninitialized slots, so
    // it doesn't make much sense to inline this function now.
    TRACE("Not considering " << shared
                             << " for inlining (feedback vector changed)");
    return false;
  }
  SharedFunctionInfo::Inlineability inlineability =
      shared.GetInlineability(CodeKind::TURBOFAN_JS, broker);
  if (inlineability != SharedFunctionInfo::kIsInlineable) {
    TRACE("Cannot consider "
          << shared << " for inlining (reason: " << inlineability << ")");
    return false;
  }
  TRACE("Considering " << shared << " for inlining with " << *feedback_vector);
  return true;
}
References broker(), v8::internal::compiler::FeedbackCellRef::feedback_vector(), v8::internal::compiler::SharedFunctionInfoRef::GetBytecodeArray(), v8::internal::compiler::SharedFunctionInfoRef::GetInlineability(), v8::internal::SharedFunctionInfo::kIsInlineable, and v8::internal::TRACE().
CanConsiderForInlining() [2/2]
bool v8::internal::compiler::anonymous_namespace{js-inlining-heuristic.cc}::CanConsiderForInlining (JSHeapBroker * broker, JSFunctionRef function)
Definition at line 121 of file js-inlining-heuristic.cc.
                                                                          {
  FeedbackCellRef feedback_cell = function.raw_feedback_cell(broker);
  bool const result = CanConsiderForInlining(broker, feedback_cell);
  if (result) {
    CHECK(function.shared(broker).equals(
        feedback_cell.shared_function_info(broker).value()));
  }
  return result;
}
References broker(), CHECK, v8::base::internal::result, and v8::internal::compiler::FeedbackCellRef::shared_function_info().
Referenced by v8::internal::compiler::JSInliningHeuristic::CollectFunctions().
CollectFrameStateUniqueUses()
bool v8::internal::compiler::anonymous_namespace{js-inlining-heuristic.cc}::CollectFrameStateUniqueUses (Node * node, FrameState frame_state, NodeAndIndex * uses_buffer, size_t * use_count, size_t max_uses)
Definition at line 437 of file js-inlining-heuristic.cc.
                                                  {
  // Only accumulate states that are not shared with other users.
  if (frame_state->UseCount() > 1) return true;
  if (frame_state.stack() == node) {
    if (*use_count >= max_uses) return false;
    uses_buffer[*use_count] = {frame_state, FrameState::kFrameStateStackInput};
    (*use_count)++;
  }
  if (!CollectStateValuesOwnedUses(node, frame_state.locals(), uses_buffer,
                                   use_count, max_uses)) {
    return false;
  }
  return true;
}
References CollectStateValuesOwnedUses(), v8::internal::compiler::FrameState::kFrameStateStackInput, v8::internal::compiler::FrameState::locals(), and v8::internal::compiler::FrameState::stack().
Referenced by v8::internal::compiler::JSInliningHeuristic::TryReuseDispatch().
CollectStateValuesOwnedUses()
bool v8::internal::compiler::anonymous_namespace{js-inlining-heuristic.cc}::CollectStateValuesOwnedUses (Node * node, Node * state_values, NodeAndIndex * uses_buffer, size_t * use_count, size_t max_uses)
Definition at line 385 of file js-inlining-heuristic.cc.
                                                  {
  // Only accumulate states that are not shared with other users.
  if (state_values->UseCount() > 1) return true;
  for (int i = 0; i < state_values->InputCount(); i++) {
    Node* input = state_values->InputAt(i);
    if (input->opcode() == IrOpcode::kStateValues) {
      if (!CollectStateValuesOwnedUses(node, input, uses_buffer, use_count,
                                       max_uses)) {
        return false;
      }
    } else if (input == node) {
      if (*use_count >= max_uses) return false;
      uses_buffer[*use_count] = {state_values, i};
      (*use_count)++;
    }
  }
  return true;
}
References v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::InputCount(), v8::internal::compiler::Node::opcode(), and v8::internal::compiler::Node::UseCount().
Referenced by CollectFrameStateUniqueUses().
HasHeapNumberInputOrOutput()
bool v8::internal::compiler::anonymous_namespace{js-inlining-heuristic.cc}::HasHeapNumberInputOrOutput (Node * node)
Definition at line 33 of file js-inlining-heuristic.cc.
                                            {
  int input_count = node->InputCount();
  for (int j = 2; j < input_count; ++j) {
    Node* input = node->InputAt(j);
    if (input->opcode() == IrOpcode::kNumberConstant) {
      double value = OpParameter<double>(input->op());
      if (!IsSmiDouble(value)) {
        return true;
      }
    } else if (input->opcode() == IrOpcode::kChangeFloat64HoleToTagged) {
      return true;
    }
  }
  for (Edge const edge : node->use_edges()) {
    if (!NodeProperties::IsValueEdge(edge)) continue;
    switch (edge.from()->opcode()) {
      case IrOpcode::kSpeculativeNumberAdd:
      case IrOpcode::kSpeculativeNumberSubtract:
      case IrOpcode::kSpeculativeNumberMultiply:
      case IrOpcode::kSpeculativeNumberPow:
      case IrOpcode::kSpeculativeNumberDivide:
      case IrOpcode::kSpeculativeNumberModulus:
      case IrOpcode::kSpeculativeNumberBitwiseAnd:
      case IrOpcode::kSpeculativeNumberBitwiseOr:
      case IrOpcode::kSpeculativeNumberBitwiseXor:
      case IrOpcode::kSpeculativeNumberShiftLeft:
      case IrOpcode::kSpeculativeNumberShiftRight:
      case IrOpcode::kSpeculativeNumberShiftRightLogical:
      case IrOpcode::kSpeculativeAdditiveSafeIntegerAdd:
      case IrOpcode::kSpeculativeAdditiveSafeIntegerSubtract:
        return true;
      default:
        break;
    }
  }
  return false;
}
References v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::InputCount(), v8::internal::IsSmiDouble(), v8::internal::compiler::NodeProperties::IsValueEdge(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::Node::use_edges(), and v8::internal::value.
Referenced by v8::internal::compiler::JSInliningHeuristic::CollectFunctions(), and v8::internal::compiler::JSInliningHeuristic::Finalize().
IsSmall()
bool v8::internal::compiler::anonymous_namespace{js-inlining-heuristic.cc}::IsSmall (int const size)
Definition at line 25 of file js-inlining-heuristic.cc.
                             {
  return size <= v8_flags.max_inlined_bytecode_size_small;
}
References size(), and v8::internal::v8_flags.
Referenced by v8::internal::compiler::JSInliningHeuristic::Reduce().
IsSmallWithHeapNumberParam()
bool v8::internal::compiler::anonymous_namespace{js-inlining-heuristic.cc}::IsSmallWithHeapNumberParam (int const size)
Definition at line 29 of file js-inlining-heuristic.cc.
                                                {
  return size <= v8_flags.max_inlined_bytecode_size_small_with_heapnum_in_out;
}
References size(), and v8::internal::v8_flags.
Referenced by v8::internal::compiler::JSInliningHeuristic::Finalize(), and v8::internal::compiler::JSInliningHeuristic::Reduce().