v8::internal::torque::anonymous_namespace{declarations.cc} Namespace Reference
Functions
template<class T >
std::vector< T > EnsureNonempty (std::vector< T > list, const std::string &name, const char *kind)
template<class T , class Name >
T EnsureUnique (const std::vector< T > &list, const Name &name, const char *kind)
template<class T >
void CheckAlreadyDeclared (const std::string &name, const char *new_type)
Function Documentation
CheckAlreadyDeclared()
template<class T >
void v8::internal::torque::anonymous_namespace{declarations.cc}::CheckAlreadyDeclared (const std::string & name, const char * new_type)
Definition at line 38 of file declarations.cc.
                                                                       {
  std::vector<T*> declarations =
      FilterDeclarables<T>(Declarations::TryLookupShallow(QualifiedName(name)));
  if (!declarations.empty()) {
    Scope* scope = CurrentScope::Get();
    ReportError("cannot redeclare ", name, " (type ", *new_type, scope, ")");
  }
}
References v8::internal::compiler::turboshaft::Get(), v8::internal::name, v8::internal::torque::ReportError(), and v8::internal::torque::Declarations::TryLookupShallow().
EnsureNonempty()
template<class T >
std::vector<T> v8::internal::torque::anonymous_namespace{declarations.cc}::EnsureNonempty (std::vector< T > list, const std::string & name, const char * kind)
Definition at line 18 of file declarations.cc.
                                                {
  if (list.empty()) {
    ReportError("there is no ", kind, " named ", name);
  }
  return std::move(list);
}
References v8::internal::name, and v8::internal::torque::ReportError().
Referenced by v8::internal::torque::Declarations::LookupGeneric().
EnsureUnique()
template<class T , class Name >
T v8::internal::torque::anonymous_namespace{declarations.cc}::EnsureUnique (const std::vector< T > & list, const Name & name, const char * kind)
Definition at line 27 of file declarations.cc.
                                                                             {
  if (list.empty()) {
    ReportError("there is no ", kind, " named ", name);
  }
  if (list.size() >= 2) {
    ReportError("ambiguous reference to ", kind, " ", name);
  }
  return list.front();
}
References v8::internal::name, and v8::internal::torque::ReportError().
Referenced by v8::internal::torque::Declarations::LookupGlobalType(), v8::internal::torque::Declarations::LookupGlobalUniqueGenericType(), v8::internal::torque::Declarations::LookupTypeAlias(), v8::internal::torque::Declarations::LookupUniqueGeneric(), v8::internal::torque::Declarations::LookupUniqueGenericType(), v8::internal::torque::Declarations::LookupValue(), v8::internal::torque::Declarations::TryLookupBuiltin(), v8::internal::torque::Declarations::TryLookupGenericType(), and v8::internal::torque::Declarations::TryLookupType().