v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc} Namespace Reference
Typedefs
using BlockReverseIterator = std::vector< BasicBlock >::reverse_iterator
Functions
bool IsTargetOfNodeFallthrough (ControlNode *node, BasicBlock *target)
ControlNode * NearestPostDominatingHole (ControlNode *node)
ControlNode * HighestPostDominatingHole (ControlNode *first, ControlNode *second)
template<size_t kSize>
ControlNode * HighestPostDominatingHole (base::SmallVector< ControlNode *, kSize > &holes)
bool IsLiveAtTarget (ValueNode *node, ControlNode *source, BasicBlock *target)
bool IsDeadNodeToSkip (Node *node)
bool SameAsInput (ValueNode *node, Input &input)
compiler::InstructionOperand InputHint (NodeBase *node, Input &input)
template<typename RegisterT >
static RegisterT GetRegisterHint (const compiler::InstructionOperand &hint)
template<typename RegisterT >
compiler::AllocatedOperand OperandForNodeRegister (ValueNode *node, RegisterT reg)
template<typename RegisterT >
RegListBase< RegisterT > GetReservedRegisters (NodeBase *node_base)
Variables
constexpr RegisterStateFlags initialized_node {true, false}
constexpr RegisterStateFlags initialized_merge {true, true}
Typedef Documentation
BlockReverseIterator
using v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::BlockReverseIterator = typedef std::vector<BasicBlock>::reverse_iterator
Definition at line 54 of file maglev-regalloc.cc.
Function Documentation
GetRegisterHint()
template<typename RegisterT >
static RegisterT v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::GetRegisterHint (const compiler::InstructionOperand & hint) [static]
Definition at line 1776 of file maglev-regalloc.cc.
                                                                         {
  if (hint.IsInvalid()) return RegisterT::no_reg();
  DCHECK(hint.IsUnallocated());
  return RegisterT::from_code(
      compiler::UnallocatedOperand::cast(hint).fixed_register_index());
}
References DCHECK, and v8::internal::no_reg.
GetReservedRegisters()
template<typename RegisterT >
RegListBase<RegisterT> v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::GetReservedRegisters (NodeBase * node_base)
Definition at line 1982 of file maglev-regalloc.cc.
                                                                 {
  if (!node_base->Is<ValueNode>()) return RegListBase<RegisterT>();
  ValueNode* node = node_base->Cast<ValueNode>();
  compiler::UnallocatedOperand operand =
      compiler::UnallocatedOperand::cast(node->result().operand());
  RegListBase<RegisterT> reserved = {node->GetRegisterHint<RegisterT>()};
  if (operand.basic_policy() == compiler::UnallocatedOperand::FIXED_SLOT) {
    DCHECK(node->Is<InitialValue>());
    return reserved;
  }
  if constexpr (std::is_same_v<RegisterT, Register>) {
    if (operand.extended_policy() ==
        compiler::UnallocatedOperand::FIXED_REGISTER) {
      reserved.set(Register::from_code(operand.fixed_register_index()));
    }
  } else {
    static_assert(std::is_same_v<RegisterT, DoubleRegister>);
    if (operand.extended_policy() ==
        compiler::UnallocatedOperand::FIXED_FP_REGISTER) {
      reserved.set(DoubleRegister::from_code(operand.fixed_register_index()));
    }
  }
  return reserved;
}
References v8::internal::maglev::NodeBase::Cast(), DCHECK, v8::internal::maglev::ValueNode::GetRegisterHint(), v8::internal::maglev::NodeBase::Is(), v8::internal::maglev::ValueLocation::operand(), v8::internal::maglev::ValueNode::result(), and v8::internal::RegListBase< RegisterT >::set().
HighestPostDominatingHole() [1/2]
template<size_t kSize>
ControlNode* v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::HighestPostDominatingHole (base::SmallVector< ControlNode *, kSize > & holes)
Definition at line 129 of file maglev-regalloc.cc.
                                                 {
  // Sort them from highest to shortest.
  std::sort(holes.begin(), holes.end(),
            [](ControlNode* first, ControlNode* second) {
              return first->id() > second->id();
            });
  DCHECK_GT(holes.size(), 1);
  // Find the highest post dominating hole.
  ControlNode* post_dominating_hole = holes.back();
  holes.pop_back();
  while (holes.size() > 0) {
    ControlNode* next_hole = holes.back();
    holes.pop_back();
    post_dominating_hole =
        HighestPostDominatingHole(post_dominating_hole, next_hole);
  }
  return post_dominating_hole;
}
References v8::base::SmallVector< T, kSize, Allocator >::back(), v8::base::SmallVector< T, kSize, Allocator >::begin(), DCHECK_GT, v8::base::SmallVector< T, kSize, Allocator >::end(), v8::base::SmallVector< T, kSize, Allocator >::pop_back(), v8::base::SmallVector< T, kSize, Allocator >::size(), and v8::base::sort().
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::ComputePostDominatingHoles().
HighestPostDominatingHole() [2/2]
ControlNode* v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::HighestPostDominatingHole (ControlNode * first, ControlNode * second)
Definition at line 98 of file maglev-regalloc.cc.
                                                            {
  // Either find the merge-point of both branches, or the highest reachable
  // control-node of the longest branch after the last node of the shortest
  // branch.
  // As long as there's no merge-point.
  while (first != second) {
    // Walk the highest branch to find where it goes.
    if (first->id() > second->id()) std::swap(first, second);
    // If the first branch terminates or jumps back, we've found highest
    // reachable control-node of the longest branch (the second control
    // node).
    if (first->Is<TerminalControlNode>() || first->Is<JumpLoop>()) {
      return second;
    }
    // Continue one step along the highest branch. This may cross over the
    // lowest branch in case it returns or loops. If labelled blocks are
    // involved such swapping of which branch is the highest branch can
    // occur multiple times until a return/jumploop/merge is discovered.
    first = first->next_post_dominating_hole();
  }
  // Once the branches merged, we've found the gap-chain that's relevant
  // for the control node.
  return first;
}
References v8::internal::maglev::NodeBase::id(), v8::internal::maglev::NodeBase::Is(), and v8::internal::maglev::ControlNode::next_post_dominating_hole().
InputHint()
compiler::InstructionOperand v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::InputHint (NodeBase * node, Input & input)
Definition at line 1341 of file maglev-regalloc.cc.
                                                                   {
  ValueNode* value_node = node->TryCast<ValueNode>();
  if (!value_node) return input.node()->hint();
  DCHECK(value_node->result().operand().IsUnallocated());
  if (SameAsInput(value_node, input)) {
    return value_node->hint();
  } else {
    return input.node()->hint();
  }
}
References v8::internal::DCHECK(), v8::internal::maglev::ValueNode::hint(), v8::internal::maglev::Input::node(), v8::internal::maglev::ValueLocation::operand(), v8::internal::maglev::ValueNode::result(), SameAsInput(), and v8::internal::maglev::NodeBase::TryCast().
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AssignArbitraryRegisterInput().
IsDeadNodeToSkip()
bool v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::IsDeadNodeToSkip (Node * node)
Definition at line 170 of file maglev-regalloc.cc.
                                  {
  if (!node->Is<ValueNode>()) return false;
  ValueNode* value = node->Cast<ValueNode>();
  return value->has_no_more_uses() &&
         !value->properties().is_required_when_unused();
}
References v8::internal::maglev::NodeBase::Cast(), v8::internal::maglev::NodeBase::Is(), and v8::internal::value.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisters().
IsLiveAtTarget()
bool v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::IsLiveAtTarget (ValueNode * node, ControlNode * source, BasicBlock * target)
Definition at line 149 of file maglev-regalloc.cc.
                                                                              {
  DCHECK_NOT_NULL(node);
  DCHECK(!node->has_no_more_uses());
  // If we're looping, a value can only be live if it was live before the loop.
  if (target->control_node()->id() <= source->id()) {
    // Gap moves may already be inserted in the target, so skip over those.
    return node->id() < target->FirstNonGapMoveId();
  }
  // Drop all values on resumable loop headers.
  if (target->is_loop() && target->state()->is_resumable_loop()) return false;
  // TODO(verwaest): This should be true but isn't because we don't yet
  // eliminate dead code.
  // DCHECK_GT(node->next_use, source->id());
  // TODO(verwaest): Since we don't support deopt yet we can only deal with
  // direct branches. Add support for holes.
  return node->live_range().end >= target->first_id();
}
References v8::internal::maglev::BasicBlock::control_node(), v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::maglev::ValueNode::LiveRange::end, v8::internal::maglev::BasicBlock::first_id(), v8::internal::maglev::BasicBlock::FirstNonGapMoveId(), v8::internal::maglev::ValueNode::has_no_more_uses(), v8::internal::maglev::NodeBase::id(), v8::internal::maglev::BasicBlock::is_loop(), v8::internal::maglev::MergePointInterpreterFrameState::is_resumable_loop(), v8::internal::maglev::ValueNode::live_range(), and v8::internal::maglev::BasicBlock::state().
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::InitializeBranchTargetRegisterValues(), v8::internal::maglev::StraightForwardRegisterAllocator::InitializeEmptyBlockRegisterValues(), and v8::internal::maglev::StraightForwardRegisterAllocator::MergeRegisterValues().
IsTargetOfNodeFallthrough()
bool v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::IsTargetOfNodeFallthrough (ControlNode * node, BasicBlock * target)
Definition at line 60 of file maglev-regalloc.cc.
                                                                      {
  return node->id() + 1 == target->first_id();
}
References v8::internal::maglev::BasicBlock::first_id(), and v8::internal::maglev::NodeBase::id().
Referenced by NearestPostDominatingHole().
NearestPostDominatingHole()
ControlNode* v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::NearestPostDominatingHole (ControlNode * node)
Definition at line 64 of file maglev-regalloc.cc.
                                                          {
  // Conditional control nodes don't cause holes themselves. So, the nearest
  // post-dominating hole is the conditional control node's next post-dominating
  // hole.
  if (node->Is<BranchControlNode>()) {
    return node->next_post_dominating_hole();
  }
  // If the node is a Jump, it may be a hole, but only if it is not a
  // fallthrough (jump to the immediately next block). Otherwise, it will point
  // to the nearest post-dominating hole in its own "next" field.
  if (node->Is<Jump>() || node->Is<CheckpointedJump>()) {
    BasicBlock* target;
    if (auto jmp = node->TryCast<Jump>()) {
      target = jmp->target();
    } else {
      target = node->Cast<CheckpointedJump>()->target();
    }
    if (IsTargetOfNodeFallthrough(node, target)) {
      return node->next_post_dominating_hole();
    }
  }
  // If the node is a Switch, it can only have a hole if there is no
  // fallthrough.
  if (Switch* _switch = node->TryCast<Switch>()) {
    if (_switch->has_fallthrough()) {
      return _switch->next_post_dominating_hole();
    }
  }
  return node;
}
References v8::internal::maglev::NodeBase::Cast(), v8::internal::maglev::NodeBase::Is(), IsTargetOfNodeFallthrough(), v8::internal::maglev::ControlNode::next_post_dominating_hole(), and v8::internal::maglev::NodeBase::TryCast().
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisters(), and v8::internal::maglev::StraightForwardRegisterAllocator::ComputePostDominatingHoles().
OperandForNodeRegister()
template<typename RegisterT >
compiler::AllocatedOperand v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::OperandForNodeRegister (ValueNode * node, RegisterT reg)
Definition at line 1887 of file maglev-regalloc.cc.
                                                                 {
  return compiler::AllocatedOperand(compiler::LocationOperand::REGISTER,
                                    node->GetMachineRepresentation(),
                                    reg.code());
}
References v8::internal::maglev::ValueNode::GetMachineRepresentation().
Referenced by v8::internal::maglev::RegisterFrameState< RegisterT >::AllocateRegister(), v8::internal::maglev::RegisterFrameState< RegisterT >::TryChooseInputRegister(), and v8::internal::maglev::RegisterFrameState< RegisterT >::TryChooseUnblockedInputRegister().
SameAsInput()
bool v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::SameAsInput (ValueNode * node, Input & input)
Definition at line 1335 of file maglev-regalloc.cc.
                                                {
  auto operand = compiler::UnallocatedOperand::cast(node->result().operand());
  return operand.HasSameAsInputPolicy() &&
         &input == &node->input(operand.input_index());
}
References v8::internal::maglev::NodeBase::input(), v8::internal::maglev::ValueLocation::operand(), and v8::internal::maglev::ValueNode::result().
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AssignArbitraryRegisterInput(), and InputHint().
Variable Documentation
initialized_merge
constexpr RegisterStateFlags v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::initialized_merge {true, true} [constexpr]
Definition at line 52 of file maglev-regalloc.cc.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::MergeRegisterValues().
initialized_node
constexpr RegisterStateFlags v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::initialized_node {true, false} [constexpr]
Definition at line 51 of file maglev-regalloc.cc.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::InitializeBranchTargetRegisterValues(), v8::internal::maglev::StraightForwardRegisterAllocator::InitializeEmptyBlockRegisterValues(), and v8::internal::maglev::StraightForwardRegisterAllocator::MergeRegisterValues().