v8::internal::win64_unwindinfo::anonymous_namespace{unwinding-info-win64.cc} Namespace Reference
Functions
V8_DECLARE_ONCE (load_ntdll_unwinding_functions_once)
void LoadNtdllUnwindingFunctionsOnce ()
void LoadNtdllUnwindingFunctions ()
bool AddGrowableFunctionTable (PVOID *DynamicTable, PRUNTIME_FUNCTION FunctionTable, DWORD EntryCount, DWORD MaximumEntryCount, ULONG_PTR RangeBase, ULONG_PTR RangeEnd)
void DeleteGrowableFunctionTable (PVOID dynamic_table)
Variables
static decltype(&::RtlAddGrowableFunctionTable) add_growable_function_table_func = nullptr
static decltype(&::RtlDeleteGrowableFunctionTable) delete_growable_function_table_func
Function Documentation
AddGrowableFunctionTable()
bool v8::internal::win64_unwindinfo::anonymous_namespace{unwinding-info-win64.cc}::AddGrowableFunctionTable (PVOID * DynamicTable, PRUNTIME_FUNCTION FunctionTable, DWORD EntryCount, DWORD MaximumEntryCount, ULONG_PTR RangeBase, ULONG_PTR RangeEnd)
Definition at line 496 of file unwinding-info-win64.cc.
                                                  {
  DCHECK(::IsWindows8OrGreater());
  LoadNtdllUnwindingFunctions();
  DCHECK_NOT_NULL(add_growable_function_table_func);
  *DynamicTable = nullptr;
  DWORD status =
      add_growable_function_table_func(DynamicTable, FunctionTable, EntryCount,
                                       MaximumEntryCount, RangeBase, RangeEnd);
  DCHECK((status == 0 && *DynamicTable != nullptr) ||
         status == 0xC000009A); // STATUS_INSUFFICIENT_RESOURCES
  return (status == 0);
}
References add_growable_function_table_func, v8::internal::DCHECK(), DCHECK_NOT_NULL, LoadNtdllUnwindingFunctions(), and v8::internal::status.
Referenced by v8::internal::win64_unwindinfo::RegisterNonABICompliantCodeRange().
DeleteGrowableFunctionTable()
void v8::internal::win64_unwindinfo::anonymous_namespace{unwinding-info-win64.cc}::DeleteGrowableFunctionTable (PVOID dynamic_table)
Definition at line 514 of file unwinding-info-win64.cc.
                                                      {
  DCHECK(::IsWindows8OrGreater());
  LoadNtdllUnwindingFunctions();
  DCHECK_NOT_NULL(delete_growable_function_table_func);
  delete_growable_function_table_func(dynamic_table);
}
References v8::internal::DCHECK(), DCHECK_NOT_NULL, delete_growable_function_table_func, and LoadNtdllUnwindingFunctions().
Referenced by v8::internal::win64_unwindinfo::UnregisterNonABICompliantCodeRange().
LoadNtdllUnwindingFunctions()
void v8::internal::win64_unwindinfo::anonymous_namespace{unwinding-info-win64.cc}::LoadNtdllUnwindingFunctions ()
Definition at line 491 of file unwinding-info-win64.cc.
                                   {
  base::CallOnce(&load_ntdll_unwinding_functions_once,
                 &LoadNtdllUnwindingFunctionsOnce);
}
References v8::base::CallOnce(), and LoadNtdllUnwindingFunctionsOnce().
Referenced by AddGrowableFunctionTable(), and DeleteGrowableFunctionTable().
LoadNtdllUnwindingFunctionsOnce()
void v8::internal::win64_unwindinfo::anonymous_namespace{unwinding-info-win64.cc}::LoadNtdllUnwindingFunctionsOnce ()
Definition at line 473 of file unwinding-info-win64.cc.
                                       {
  // Load functions from the ntdll.dll module.
  HMODULE ntdll_module =
      LoadLibraryEx(L"ntdll.dll", nullptr, LOAD_LIBRARY_SEARCH_SYSTEM32);
  DCHECK_NOT_NULL(ntdll_module);
  // This fails on Windows 7.
  add_growable_function_table_func =
      reinterpret_cast<decltype(&::RtlAddGrowableFunctionTable)>(
          ::GetProcAddress(ntdll_module, "RtlAddGrowableFunctionTable"));
  DCHECK_IMPLIES(IsWindows8OrGreater(), add_growable_function_table_func);
  delete_growable_function_table_func =
      reinterpret_cast<decltype(&::RtlDeleteGrowableFunctionTable)>(
          ::GetProcAddress(ntdll_module, "RtlDeleteGrowableFunctionTable"));
  DCHECK_IMPLIES(IsWindows8OrGreater(), delete_growable_function_table_func);
}
References add_growable_function_table_func, DCHECK_IMPLIES, DCHECK_NOT_NULL, delete_growable_function_table_func, and v8::internal::L.
Referenced by LoadNtdllUnwindingFunctions().
V8_DECLARE_ONCE()
v8::internal::win64_unwindinfo::anonymous_namespace{unwinding-info-win64.cc}::V8_DECLARE_ONCE (load_ntdll_unwinding_functions_once)
Variable Documentation
add_growable_function_table_func
decltype(&::RtlAddGrowableFunctionTable) v8::internal::win64_unwindinfo::anonymous_namespace{unwinding-info-win64.cc}::add_growable_function_table_func = nullptr [static]
Definition at line 468 of file unwinding-info-win64.cc.
Referenced by AddGrowableFunctionTable(), and LoadNtdllUnwindingFunctionsOnce().
delete_growable_function_table_func
decltype(&::RtlDeleteGrowableFunctionTable) v8::internal::win64_unwindinfo::anonymous_namespace{unwinding-info-win64.cc}::delete_growable_function_table_func [static]
Initial value:
=
    nullptr
Definition at line 470 of file unwinding-info-win64.cc.
Referenced by DeleteGrowableFunctionTable(), and LoadNtdllUnwindingFunctionsOnce().