v8::internal::anonymous_namespace{api.cc} Namespace Reference
Functions
Tagged< FunctionTemplateInfo > GetTargetFunctionTemplateInfo (const v8::FunctionCallbackInfo< v8::Value > &info)
void InvokeFunctionCallback (const v8::FunctionCallbackInfo< v8::Value > &info, CallApiCallbackMode mode)
Function Documentation
GetTargetFunctionTemplateInfo()
Tagged<FunctionTemplateInfo> v8::internal::anonymous_namespace{api.cc}::GetTargetFunctionTemplateInfo (const v8::FunctionCallbackInfo< v8::Value > & info) [inline]
Definition at line 12150 of file api.cc.
                                                 {
  Tagged<Object> target = FunctionCallbackArguments::GetTarget(info);
  CHECK(IsFunctionTemplateInfo(target));
  return Cast<FunctionTemplateInfo>(target);
}
References CHECK, and v8::internal::FunctionCallbackArguments::GetTarget().
Referenced by InvokeFunctionCallback().
InvokeFunctionCallback()
void v8::internal::anonymous_namespace{api.cc}::InvokeFunctionCallback (const v8::FunctionCallbackInfo< v8::Value > & info, CallApiCallbackMode mode) [inline]
Definition at line 12157 of file api.cc.
                                                                           {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(info.GetIsolate());
  RCS_SCOPE(i_isolate, RuntimeCallCounterId::kFunctionCallback);
  Tagged<FunctionTemplateInfo> fti = GetTargetFunctionTemplateInfo(info);
  v8::FunctionCallback callback =
      reinterpret_cast<v8::FunctionCallback>(fti->callback(i_isolate));
  switch (mode) {
    case CallApiCallbackMode::kGeneric: {
      if (V8_UNLIKELY(i_isolate->should_check_side_effects())) {
        if (!i_isolate->debug()->PerformSideEffectCheckForCallback(
                handle(fti, i_isolate))) {
          // Failed side effect check.
          return;
        }
        if (DEBUG_BOOL) {
          // Clear raw pointer to ensure it's not accidentally used after
          // potential GC in PerformSideEffectCheckForCallback.
          fti = {};
        }
      }
      break;
    }
    case CallApiCallbackMode::kOptimized:
      // CallFunction builtin should deoptimize an optimized function when
      // side effects checking is enabled, so we don't have to handle side
      // effects checking in the optimized version of the builtin.
      DCHECK(!i_isolate->should_check_side_effects());
      break;
    case CallApiCallbackMode::kOptimizedNoProfiling:
      // This mode doesn't call InvokeFunctionCallback.
      UNREACHABLE();
  }
  ExternalCallbackScope call_scope(i_isolate, FUNCTION_ADDR(callback),
                                   info.IsConstructCall()
                                       ? v8::ExceptionContext::kConstructor
                                       : v8::ExceptionContext::kOperation,
                                   &info);
  callback(info);
}
References v8::internal::DCHECK(), v8::internal::Isolate::debug(), DEBUG_BOOL, FUNCTION_ADDR, v8::FunctionCallbackInfo< T >::GetIsolate(), GetTargetFunctionTemplateInfo(), v8::internal::handle(), v8::FunctionCallbackInfo< T >::IsConstructCall(), v8::kConstructor, v8::internal::kGeneric, v8::kOperation, v8::internal::kOptimized, v8::internal::kOptimizedNoProfiling, mode(), v8::internal::Debug::PerformSideEffectCheckForCallback(), RCS_SCOPE, v8::internal::Isolate::should_check_side_effects(), v8::internal::UNREACHABLE(), and V8_UNLIKELY.
Referenced by v8::internal::InvokeFunctionCallbackGeneric(), and v8::internal::InvokeFunctionCallbackOptimized().