cppgc::internal::anonymous_namespace{page-memory.cc} Namespace Reference
Functions
V8_WARN_UNUSED_RESULT bool TryUnprotect (PageAllocator &allocator, const MemoryRegion &memory_region)
V8_WARN_UNUSED_RESULT bool TryDiscard (PageAllocator &allocator, const MemoryRegion &memory_region)
std::optional< MemoryRegion > ReserveMemoryRegion (PageAllocator &allocator, size_t allocation_size)
void FreeMemoryRegion (PageAllocator &allocator, const MemoryRegion &reserved_region)
std::unique_ptr< PageMemoryRegion > CreateNormalPageMemoryRegion (PageAllocator &allocator)
std::unique_ptr< PageMemoryRegion > CreateLargePageMemoryRegion (PageAllocator &allocator, size_t length)
Function Documentation
CreateLargePageMemoryRegion()
std::unique_ptr<PageMemoryRegion> cppgc::internal::anonymous_namespace{page-memory.cc}::CreateLargePageMemoryRegion (PageAllocator & allocator, size_t length)
Definition at line 73 of file page-memory.cc.
                                             {
  const auto region = ReserveMemoryRegion(
      allocator, RoundUp(length, allocator.AllocatePageSize()));
  if (!region) return {};
  auto result = std::unique_ptr<PageMemoryRegion>(
      new PageMemoryRegion(allocator, *region));
  return result;
}
References v8::PageAllocator::AllocatePageSize(), v8::internal::length, ReserveMemoryRegion(), v8::base::internal::result, and RoundUp().
Referenced by cppgc::internal::PageBackend::TryAllocateLargePageMemory().
CreateNormalPageMemoryRegion()
std::unique_ptr<PageMemoryRegion> cppgc::internal::anonymous_namespace{page-memory.cc}::CreateNormalPageMemoryRegion (PageAllocator & allocator)
Definition at line 63 of file page-memory.cc.
                              {
  DCHECK_EQ(0u, kPageSize % allocator.AllocatePageSize());
  const auto region = ReserveMemoryRegion(allocator, kPageSize);
  if (!region) return {};
  auto result = std::unique_ptr<PageMemoryRegion>(
      new PageMemoryRegion(allocator, *region));
  return result;
}
References v8::PageAllocator::AllocatePageSize(), DCHECK_EQ, cppgc::internal::kPageSize, ReserveMemoryRegion(), and v8::base::internal::result.
Referenced by cppgc::internal::PageBackend::TryAllocateNormalPageMemory().
FreeMemoryRegion()
void cppgc::internal::anonymous_namespace{page-memory.cc}::FreeMemoryRegion (PageAllocator & allocator, const MemoryRegion & reserved_region)
Definition at line 56 of file page-memory.cc.
                                                           {
  // Make sure pages returned to OS are unpoisoned.
  ASAN_UNPOISON_MEMORY_REGION(reserved_region.base(), reserved_region.size());
  allocator.FreePages(reserved_region.base(), reserved_region.size());
}
References ASAN_UNPOISON_MEMORY_REGION, cppgc::internal::MemoryRegion::base(), v8::PageAllocator::FreePages(), and cppgc::internal::MemoryRegion::size().
Referenced by cppgc::internal::PageMemoryRegion::~PageMemoryRegion().
ReserveMemoryRegion()
std::optional<MemoryRegion> cppgc::internal::anonymous_namespace{page-memory.cc}::ReserveMemoryRegion (PageAllocator & allocator, size_t allocation_size)
Definition at line 42 of file page-memory.cc.
                                                                        {
  void* region_memory =
      allocator.AllocatePages(nullptr, allocation_size, kPageSize,
                              PageAllocator::Permission::kNoAccess);
  if (!region_memory) {
    return std::nullopt;
  }
  const MemoryRegion reserved_region(static_cast<Address>(region_memory),
                                     allocation_size);
  DCHECK_EQ(reserved_region.base() + allocation_size, reserved_region.end());
  return reserved_region;
}
References v8::PageAllocator::AllocatePages(), cppgc::internal::MemoryRegion::base(), DCHECK_EQ, cppgc::internal::MemoryRegion::end(), and cppgc::internal::kPageSize.
Referenced by CreateLargePageMemoryRegion(), and CreateNormalPageMemoryRegion().
TryDiscard()
V8_WARN_UNUSED_RESULT bool cppgc::internal::anonymous_namespace{page-memory.cc}::TryDiscard (PageAllocator & allocator, const MemoryRegion & memory_region)
Definition at line 34 of file page-memory.cc.
                                                                         {
  // See Unprotect().
  CHECK_EQ(0u, memory_region.size() % allocator.CommitPageSize());
  return allocator.DiscardSystemPages(memory_region.base(),
                                      memory_region.size());
}
References cppgc::internal::MemoryRegion::base(), CHECK_EQ, v8::PageAllocator::CommitPageSize(), v8::PageAllocator::DiscardSystemPages(), and cppgc::internal::MemoryRegion::size().
Referenced by cppgc::internal::NormalPageMemoryPool::ReleasePooledPages().
TryUnprotect()
V8_WARN_UNUSED_RESULT bool cppgc::internal::anonymous_namespace{page-memory.cc}::TryUnprotect (PageAllocator & allocator, const MemoryRegion & memory_region)
Definition at line 26 of file page-memory.cc.
                                                                           {
  // The allocator needs to support committing the overall range.
  CHECK_EQ(0u, memory_region.size() % allocator.CommitPageSize());
  return allocator.SetPermissions(memory_region.base(), memory_region.size(),
                                  PageAllocator::Permission::kReadWrite);
}
References cppgc::internal::MemoryRegion::base(), CHECK_EQ, v8::PageAllocator::CommitPageSize(), v8::PageAllocator::SetPermissions(), and cppgc::internal::MemoryRegion::size().
Referenced by cppgc::internal::PageBackend::TryAllocateLargePageMemory(), cppgc::internal::PageBackend::TryAllocateNormalPageMemory(), and cppgc::internal::PageMemoryRegion::UnprotectForTesting().