v8::internal::compiler::anonymous_namespace{gap-resolver.cc} Namespace Reference
Enumerations
enum MoveOperandKind : uint8_t { kConstant
, kGpReg
, kFpReg
, kStack
 }
Functions
MoveOperandKind GetKind (const InstructionOperand &move)
Enumeration Type Documentation
MoveOperandKind
enum v8::internal::compiler::anonymous_namespace{gap-resolver.cc}::MoveOperandKind : uint8_t
Enumerator
kConstant
kGpReg
kFpReg
kStack
Definition at line 19 of file gap-resolver.cc.
: uint8_t { kConstant, kGpReg, kFpReg, kStack };
Function Documentation
GetKind()
MoveOperandKind v8::internal::compiler::anonymous_namespace{gap-resolver.cc}::GetKind (const InstructionOperand & move)
Definition at line 21 of file gap-resolver.cc.
                                                        {
  if (move.IsConstant()) return kConstant;
  LocationOperand loc_op = LocationOperand::cast(move);
  if (loc_op.location_kind() != LocationOperand::REGISTER) return kStack;
  return IsFloatingPoint(loc_op.representation()) ? kFpReg : kGpReg;
}
References v8::internal::compiler::LocationOperand::cast(), v8::internal::IsFloatingPoint(), kConstant, kFpReg, kGpReg, kStack, v8::internal::compiler::LocationOperand::location_kind(), v8::internal::compiler::LocationOperand::REGISTER, and v8::internal::compiler::LocationOperand::representation().
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::DefineKeyedOwnProperty(), v8::internal::interpreter::BytecodeArrayBuilder::DefineNamedOwnProperty(), v8::internal::interpreter::BytecodeArrayBuilder::LoadGlobal(), v8::internal::compiler::GapResolver::Resolve(), v8::internal::interpreter::BytecodeArrayBuilder::SetKeyedProperty(), and v8::internal::interpreter::BytecodeArrayBuilder::SetNamedProperty().