v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc} Namespace Reference
Functions
bool IsConcat (Node *node)
bool IsLiteralString (Node *node, JSHeapBroker *broker)
bool HasConcatOrPhiUse (Node *node)
bool ComesBeforeInBlock (Node *first, Node *second, BasicBlock *block)
bool ComputePredecessors (BasicBlock *start, BasicBlock *end, base::SmallVector< BasicBlock *, kMaxPredecessors > *dst)
bool OpcodeIsAllowed (IrOpcode::Value op)
bool ValidControlFlowForStringBuilder (BasicBlock *sb_child_block, BasicBlock *other_child_block, BasicBlock *previous_block, ZoneVector< BasicBlock * > loop_headers)
bool IsClosebyDominator (BasicBlock *maybe_dominator, BasicBlock *maybe_dominee)
bool IsPhiContainingGivenInputs (Node *node, Node *input1, Node *input2, Schedule *schedule)
bool PhiInputsAreConcatsOrPhi (Node *phi)
Variables
static constexpr int kMaxPredecessors = 15
Function Documentation
ComesBeforeInBlock()
bool v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::ComesBeforeInBlock (Node * first, Node * second, BasicBlock * block)
Definition at line 446 of file string-builder-optimizer.cc.
                                                                      {
  for (Node* node : *block->nodes()) {
    if (node == first) {
      return true;
    }
    if (node == second) {
      return false;
    }
  }
  UNREACHABLE();
}
References v8::internal::compiler::BasicBlock::nodes(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::StringBuilderOptimizer::CheckNodeUses().
ComputePredecessors()
bool v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::ComputePredecessors (BasicBlock * start, BasicBlock * end, base::SmallVector< BasicBlock *, kMaxPredecessors > * dst)
Definition at line 463 of file string-builder-optimizer.cc.
                                                         {
  dst->push_back(start);
  size_t stack_pointer = 0;
  while (stack_pointer < dst->size()) {
    BasicBlock* current = (*dst)[stack_pointer++];
    if (current == end) continue;
    for (BasicBlock* pred : current->predecessors()) {
      if (std::find(dst->begin(), dst->end(), pred) == dst->end()) {
        if (dst->size() == kMaxPredecessors) return false;
        dst->push_back(pred);
      }
    }
  }
  return true;
}
References v8::base::SmallVector< T, kSize, Allocator >::begin(), v8::base::SmallVector< T, kSize, Allocator >::end(), v8::internal::compiler::end(), kMaxPredecessors, v8::internal::compiler::BasicBlock::predecessors(), v8::base::SmallVector< T, kSize, Allocator >::push_back(), v8::base::SmallVector< T, kSize, Allocator >::size(), and size().
Referenced by v8::internal::compiler::StringBuilderOptimizer::CheckNodeUses().
HasConcatOrPhiUse()
bool v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::HasConcatOrPhiUse (Node * node)
Definition at line 60 of file string-builder-optimizer.cc.
                                   {
  for (Node* use : node->uses()) {
    if (IsConcat(use) || use->opcode() == IrOpcode::kPhi) {
      return true;
    }
  }
  return false;
}
References IsConcat(), use(), and v8::internal::compiler::Node::uses().
Referenced by v8::internal::compiler::StringBuilderOptimizer::VisitNode().
IsClosebyDominator()
bool v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::IsClosebyDominator (BasicBlock * maybe_dominator, BasicBlock * maybe_dominee)
Definition at line 573 of file string-builder-optimizer.cc.
                                                   {
  static constexpr int kMaxDominatorSteps = 10;
  if (maybe_dominee->dominator_depth() + kMaxDominatorSteps <
      maybe_dominator->dominator_depth()) {
    // {maybe_dominee} is too far from {maybe_dominator} to compute quickly if
    // it's dominated by {maybe_dominator} or not.
    return false;
  }
  while (maybe_dominee != maybe_dominator &&
         maybe_dominator->dominator_depth() <
             maybe_dominee->dominator_depth()) {
    maybe_dominee = maybe_dominee->dominator();
  }
  return maybe_dominee == maybe_dominator;
}
References v8::internal::compiler::BasicBlock::dominator(), and v8::internal::compiler::BasicBlock::dominator_depth().
Referenced by v8::internal::compiler::StringBuilderOptimizer::CheckNodeUses().
IsConcat()
bool v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::IsConcat (Node * node)
Definition at line 36 of file string-builder-optimizer.cc.
                          {
  return node->opcode() == IrOpcode::kStringConcat ||
         node->opcode() == IrOpcode::kNewConsString;
}
References v8::internal::compiler::Node::opcode().
Referenced by v8::internal::compiler::StringBuilderOptimizer::CheckPreviousNodeUses(), v8::internal::compiler::StringBuilderOptimizer::ConcatIsInStringBuilder(), v8::internal::compiler::StringBuilderOptimizer::FinalizeStringBuilders(), v8::internal::compiler::StringBuilderOptimizer::GetStringBuilderIdForConcat(), HasConcatOrPhiUse(), PhiInputsAreConcatsOrPhi(), and v8::internal::compiler::StringBuilderOptimizer::VisitNode().
IsLiteralString()
bool v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::IsLiteralString (Node * node, JSHeapBroker * broker)
Definition at line 45 of file string-builder-optimizer.cc.
                                                       {
  switch (node->opcode()) {
    case IrOpcode::kHeapConstant: {
      HeapObjectMatcher m(node);
      return m.HasResolvedValue() && m.Ref(broker).IsString() &&
             m.Ref(broker).AsString().IsContentAccessible();
    }
    case IrOpcode::kStringFromSingleCharCode:
      return true;
    default:
      return false;
  }
}
References broker(), v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), v8::internal::compiler::Node::opcode(), and v8::internal::compiler::HeapObjectMatcherImpl< kHeapConstantOpcode >::Ref().
Referenced by v8::internal::compiler::OneOrTwoByteAnalysis::OneOrTwoByte(), v8::internal::compiler::StringBuilderOptimizer::ReplaceConcatInputIfNeeded(), and v8::internal::compiler::StringBuilderOptimizer::VisitNode().
IsPhiContainingGivenInputs()
bool v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::IsPhiContainingGivenInputs (Node * node, Node * input1, Node * input2, Schedule * schedule)
Definition at line 592 of file string-builder-optimizer.cc.
                                                    {
  if (node->opcode() != IrOpcode::kPhi ||
      schedule->block(node)->IsLoopHeader()) {
    return false;
  }
  bool has_input1 = false, has_input2 = false;
  for (Node* input : node->inputs()) {
    if (input == input1) {
      has_input1 = true;
    } else if (input == input2) {
      has_input2 = true;
    }
  }
  return has_input1 && has_input2;
}
References v8::internal::compiler::Schedule::block(), v8::internal::compiler::Node::inputs(), v8::internal::compiler::BasicBlock::IsLoopHeader(), and v8::internal::compiler::Node::opcode().
Referenced by v8::internal::compiler::StringBuilderOptimizer::CheckNodeUses().
OpcodeIsAllowed()
bool v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::OpcodeIsAllowed (IrOpcode::Value op)
Definition at line 484 of file string-builder-optimizer.cc.
                                       {
  switch (op) {
    case IrOpcode::kStringLength:
    case IrOpcode::kStringConcat:
    case IrOpcode::kNewConsString:
    case IrOpcode::kStringCharCodeAt:
    case IrOpcode::kStringCodePointAt:
    case IrOpcode::kStringIndexOf:
    case IrOpcode::kObjectIsString:
    case IrOpcode::kStringToLowerCaseIntl:
    case IrOpcode::kStringToNumber:
    case IrOpcode::kStringToUpperCaseIntl:
    case IrOpcode::kStringEqual:
    case IrOpcode::kStringLessThan:
    case IrOpcode::kStringLessThanOrEqual:
    case IrOpcode::kCheckString:
    case IrOpcode::kCheckStringOrStringWrapper:
    case IrOpcode::kTypedStateValues:
      return true;
    default:
      return false;
  }
}
Referenced by v8::internal::compiler::StringBuilderOptimizer::CheckNodeUses().
PhiInputsAreConcatsOrPhi()
bool v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::PhiInputsAreConcatsOrPhi (Node * phi)
Definition at line 613 of file string-builder-optimizer.cc.
                                         {
  DCHECK_EQ(phi->opcode(), IrOpcode::kPhi);
  return phi->InputCount() == 3 &&
         (phi->InputAt(0)->opcode() == IrOpcode::kPhi ||
          IsConcat(phi->InputAt(0))) &&
         (phi->InputAt(1)->opcode() == IrOpcode::kPhi ||
          IsConcat(phi->InputAt(1)));
}
References DCHECK_EQ, v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::InputCount(), IsConcat(), and v8::internal::compiler::Node::opcode().
Referenced by v8::internal::compiler::StringBuilderOptimizer::VisitNode().
ValidControlFlowForStringBuilder()
bool v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::ValidControlFlowForStringBuilder (BasicBlock * sb_child_block, BasicBlock * other_child_block, BasicBlock * previous_block, ZoneVector< BasicBlock * > loop_headers)
Definition at line 533 of file string-builder-optimizer.cc.
                                                                            {
  if (loop_headers.empty()) return true;
  // Due to how we visit the graph, {sb_child_block} is the block that
  // VisitGraph is currently visiting, which means that it has to be in all the
  // loops of {loop_headers} (and in particular in the latest one).
  // {other_child_block} on the other hand could be in the loop or not, which is
  // what this function tries to determine.
  DCHECK(loop_headers.back()->LoopContains(sb_child_block));
  if (sb_child_block->IsLoopHeader()) {
    // {sb_child_block} starts a loop. This is OK for {other_child_block} only
    // if {other_child_block} is before the loop (because if it's after, then
    // the value it will receive will be invalid), or if both
    // {other_child_block} and {previous_block} are inside the loop. The latter
    // case corresponds to:
    //
    // +--------> sb_child_block
    // | / \
    // | | \
    // | v v
    // | previous_block other_child_block
    // | |
    // +--------+
    //
    // Where {other_child_block} eventually reaches {previous_block} (or exits
    // the loop through some other path).
    return other_child_block->rpo_number() < sb_child_block->rpo_number() ||
           (sb_child_block->LoopContains(previous_block) &&
            (sb_child_block->LoopContains(other_child_block)));
  } else {
    // Both {sb_child_block} and {other_child_block} should be in the same loop.
    return loop_headers.back()->LoopContains(other_child_block);
  }
}
References v8::internal::ZoneVector< T >::back(), v8::internal::DCHECK(), v8::internal::ZoneVector< T >::empty(), v8::internal::compiler::BasicBlock::IsLoopHeader(), v8::internal::compiler::BasicBlock::LoopContains(), and v8::internal::compiler::BasicBlock::rpo_number().
Referenced by v8::internal::compiler::StringBuilderOptimizer::CheckNodeUses().
Variable Documentation
kMaxPredecessors
constexpr int v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::kMaxPredecessors = 15 [static], [constexpr]
Definition at line 458 of file string-builder-optimizer.cc.
Referenced by ComputePredecessors().