v8::internal::compiler::anonymous_namespace{wasm-compiler.cc} Namespace Reference
Classes
class WasmWrapperGraphBuilder
Functions
template<typename T >
bool ContainsSimd (const Signature< T > *sig)
bool ContainsInt64 (const wasm::CanonicalSig *sig)
MachineGraph * CreateCommonMachineGraph (Zone *zone)
Function Documentation
ContainsInt64()
bool v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::ContainsInt64 (const wasm::CanonicalSig * sig)
Definition at line 88 of file wasm-compiler.cc.
                                                {
  for (auto type : sig->all()) {
    if (type == wasm::kWasmI64) return true;
  }
  return false;
}
References v8::internal::wasm::kWasmI64, v8::internal::sig, and v8::internal::tracing::type.
Referenced by v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::BuildCWasmEntry(), and v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::BuildJSToWasmWrapper().
ContainsSimd()
template<typename T >
bool v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::ContainsSimd (const Signature< T > * sig)
Definition at line 81 of file wasm-compiler.cc.
                                           {
  for (auto type : sig->all()) {
    if (type == wasm::kWasmS128) return true;
  }
  return false;
}
References v8::internal::wasm::kWasmS128, v8::internal::sig, and v8::internal::tracing::type.
CreateCommonMachineGraph()
MachineGraph* v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::CreateCommonMachineGraph (Zone * zone)
Definition at line 1133 of file wasm-compiler.cc.
                                                   {
  return zone->New<MachineGraph>(
      zone->New<TFGraph>(zone), zone->New<CommonOperatorBuilder>(zone),
      zone->New<MachineOperatorBuilder>(
          zone, MachineType::PointerRepresentation(),
          InstructionSelector::SupportedMachineOperatorFlags(),
          InstructionSelector::AlignmentRequirements()));
}
References v8::internal::Zone::New(), and v8::internal::MachineType::PointerRepresentation().
Referenced by v8::internal::compiler::CompileWasmJSFastCallWrapper().