v8::internal::anonymous_namespace{object-stats.cc} Namespace Reference
Functions
int Log2ForSize (size_t size)
ObjectStats::VirtualInstanceType CodeKindToVirtualInstanceType (CodeKind kind)
void IterateHeap (Heap *heap, ObjectStatsVisitor *visitor)
Function Documentation
CodeKindToVirtualInstanceType()
ObjectStats::VirtualInstanceType v8::internal::anonymous_namespace{object-stats.cc}::CodeKindToVirtualInstanceType (CodeKind kind)
Definition at line 1091 of file object-stats.cc.
                                                                            {
  switch (kind) {
#define CODE_KIND_CASE(type) \
  case CodeKind::type: \
    return StatsEnum::type;
    CODE_KIND_LIST(CODE_KIND_CASE)
#undef CODE_KIND_CASE
  }
  UNREACHABLE();
}
References CODE_KIND_CASE, CODE_KIND_LIST, and v8::internal::UNREACHABLE().
Referenced by v8::internal::ObjectStatsCollectorImpl::RecordVirtualCodeDetails().
IterateHeap()
void v8::internal::anonymous_namespace{object-stats.cc}::IterateHeap (Heap * heap, ObjectStatsVisitor * visitor)
Definition at line 1188 of file object-stats.cc.
                                                          {
  // We don't perform a GC while collecting object stats but need this scope for
  // the nested SafepointScope inside CombinedHeapObjectIterator.
  AllowGarbageCollection allow_gc;
  CombinedHeapObjectIterator iterator(heap);
  for (Tagged<HeapObject> obj = iterator.Next(); !obj.is_null();
       obj = iterator.Next()) {
    visitor->Visit(obj);
  }
}
References v8::internal::Tagged< HeapObject >::is_null(), v8::internal::CombinedHeapObjectIterator::Next(), and v8::internal::ObjectStatsVisitor::Visit().
Referenced by v8::internal::ObjectStatsCollector::Collect().
Log2ForSize()
int v8::internal::anonymous_namespace{object-stats.cc}::Log2ForSize (size_t size)
Definition at line 347 of file object-stats.cc.
                             {
  DCHECK_GT(size, 0);
  return kSizetSize * 8 - 1 - base::bits::CountLeadingZeros(size);
}
References v8::base::bits::CountLeadingZeros(), DCHECK_GT, v8::internal::kSizetSize, and size().
Referenced by v8::internal::ObjectStats::HistogramIndexFromSize().