v8::internal::anonymous_namespace{js-atomics-synchronization.cc} Namespace Reference
Functions
MaybeDirectHandle< JSReceiver > PerformPromiseThen (Isolate *isolate, DirectHandle< JSReceiver > promise, DirectHandle< Object > fulfill_handler, MaybeDirectHandle< JSFunction > maybe_reject_handler={})
MaybeDirectHandle< Context > SetAsyncUnlockHandlers (Isolate *isolate, DirectHandle< JSAtomicsMutex > mutex, DirectHandle< JSReceiver > waiting_for_callback_promise, DirectHandle< JSPromise > unlocked_promise)
void AddPromiseToNativeContext (Isolate *isolate, DirectHandle< JSPromise > promise)
void RemovePromiseFromNativeContext (Isolate *isolate, DirectHandle< JSPromise > promise)
template<typename T >
Global< T > GetWeakGlobal (Isolate *isolate, Local< T > object)
Function Documentation
AddPromiseToNativeContext()
void v8::internal::anonymous_namespace{js-atomics-synchronization.cc}::AddPromiseToNativeContext (Isolate * isolate, DirectHandle< JSPromise > promise)
Definition at line 82 of file js-atomics-synchronization.cc.
                                                                {
  DirectHandle<NativeContext> native_context(isolate->native_context());
  Handle<OrderedHashSet> promises(native_context->atomics_waitasync_promises(),
                                  isolate);
  promises = OrderedHashSet::Add(isolate, promises, promise).ToHandleChecked();
  native_context->set_atomics_waitasync_promises(*promises);
}
References v8::bigint::Add(), v8::internal::Isolate::native_context(), and v8::internal::native_context.
Referenced by v8::internal::JSAtomicsMutex::LockAsync(), and v8::internal::JSAtomicsCondition::WaitAsync().
GetWeakGlobal()
template<typename T >
Global<T> v8::internal::anonymous_namespace{js-atomics-synchronization.cc}::GetWeakGlobal (Isolate * isolate, Local< T > object)
Definition at line 103 of file js-atomics-synchronization.cc.
                                                           {
  auto* v8_isolate = reinterpret_cast<v8::Isolate*>(isolate);
  v8::Global<T> global(v8_isolate, object);
  global.SetWeak();
  return global;
}
References v8::PersistentBase< T >::SetWeak().
Referenced by v8::internal::detail::AsyncWaiterQueueNode< T >::AsyncWaiterQueueNode().
PerformPromiseThen()
MaybeDirectHandle<JSReceiver> v8::internal::anonymous_namespace{js-atomics-synchronization.cc}::PerformPromiseThen (Isolate * isolate, DirectHandle< JSReceiver > promise, DirectHandle< Object > fulfill_handler, MaybeDirectHandle< JSFunction > maybe_reject_handler = {})
Definition at line 27 of file js-atomics-synchronization.cc.
                                                         {}) {
  DCHECK(IsCallable(*fulfill_handler));
  DirectHandle<Object> reject_handler = isolate->factory()->undefined_value();
  if (!maybe_reject_handler.is_null()) {
    reject_handler = maybe_reject_handler.ToHandleChecked();
  }
  DirectHandle<Object> args[] = {fulfill_handler, reject_handler};
  DirectHandle<Object> then_result;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, then_result,
      Execution::CallBuiltin(isolate, isolate->promise_then(), promise,
                             base::VectorOf(args)));
  return Cast<JSReceiver>(then_result);
}
Referenced by v8::internal::JSAtomicsMutex::LockOrEnqueuePromise(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeThen(), SetAsyncUnlockHandlers(), and v8::internal::JSAtomicsCondition::WaitAsync().
RemovePromiseFromNativeContext()
void v8::internal::anonymous_namespace{js-atomics-synchronization.cc}::RemovePromiseFromNativeContext (Isolate * isolate, DirectHandle< JSPromise > promise)
Definition at line 91 of file js-atomics-synchronization.cc.
                                                                     {
  Handle<OrderedHashSet> promises(
      isolate->native_context()->atomics_waitasync_promises(), isolate);
  bool was_deleted = OrderedHashSet::Delete(isolate, *promises, *promise);
  DCHECK(was_deleted);
  USE(was_deleted);
  promises = OrderedHashSet::Shrink(isolate, promises);
  isolate->native_context()->set_atomics_waitasync_promises(*promises);
}
References v8::internal::DCHECK(), v8::internal::OrderedHashTable< OrderedHashSet, 1 >::Delete(), v8::internal::Isolate::native_context(), cppgc::internal::anonymous_namespace{explicit-management.cc}::Shrink(), and USE.
Referenced by v8::internal::JSAtomicsMutex::HandleAsyncNotify(), v8::internal::JSAtomicsCondition::HandleAsyncNotify(), and v8::internal::JSAtomicsMutex::HandleAsyncTimeout().
SetAsyncUnlockHandlers()
MaybeDirectHandle<Context> v8::internal::anonymous_namespace{js-atomics-synchronization.cc}::SetAsyncUnlockHandlers (Isolate * isolate, DirectHandle< JSAtomicsMutex > mutex, DirectHandle< JSReceiver > waiting_for_callback_promise, DirectHandle< JSPromise > unlocked_promise)
Definition at line 47 of file js-atomics-synchronization.cc.
                                              {
  DirectHandle<Context> handlers_context =
      isolate->factory()->NewBuiltinContext(
          isolate->native_context(), JSAtomicsMutex::kAsyncContextLength);
  handlers_context->SetNoCell(JSAtomicsMutex::kMutexAsyncContextSlot, *mutex);
  handlers_context->SetNoCell(JSAtomicsMutex::kUnlockedPromiseAsyncContextSlot,
                              *unlocked_promise);
  DirectHandle<SharedFunctionInfo> resolve_info(
      isolate->heap()->atomics_mutex_async_unlock_resolve_handler_sfi(),
      isolate);
  DirectHandle<JSFunction> resolver_callback =
      Factory::JSFunctionBuilder{isolate, resolve_info, handlers_context}
          .set_map(isolate->strict_function_without_prototype_map())
          .set_allocation_type(AllocationType::kYoung)
          .Build();
  DirectHandle<SharedFunctionInfo> reject_info(
      isolate->heap()->atomics_mutex_async_unlock_reject_handler_sfi(),
      isolate);
  DirectHandle<JSFunction> reject_callback =
      Factory::JSFunctionBuilder{isolate, reject_info, handlers_context}
          .set_map(isolate->strict_function_without_prototype_map())
          .set_allocation_type(AllocationType::kYoung)
          .Build();
  RETURN_ON_EXCEPTION(isolate,
                      PerformPromiseThen(isolate, waiting_for_callback_promise,
                                         resolver_callback, reject_callback));
  return handlers_context;
}
References v8::internal::Isolate::factory(), v8::internal::Isolate::heap(), v8::internal::JSAtomicsMutex::kAsyncContextLength, v8::internal::JSAtomicsMutex::kMutexAsyncContextSlot, v8::internal::JSAtomicsMutex::kUnlockedPromiseAsyncContextSlot, v8::internal::kYoung, v8::internal::Isolate::native_context(), v8::internal::Factory::NewBuiltinContext(), PerformPromiseThen(), and RETURN_ON_EXCEPTION.
Referenced by v8::internal::JSAtomicsMutex::LockOrEnqueuePromise().