v8::internal::anonymous_namespace{setup-heap-internal.cc} Namespace Reference
Classes
struct ConstantStringInit
struct StringTypeInit
struct StructInit
Typedefs
using AllocationSiteWithoutWeakNext = AllocationSite
Functions
DirectHandle< SharedFunctionInfo > CreateSharedFunctionInfo (Isolate *isolate, Builtin builtin, int len, FunctionKind kind=FunctionKind::kNormalFunction)
constexpr bool is_important_struct (InstanceType type)
template<typename StructType >
constexpr int StructSize ()
void InitializePartialMap (Isolate *isolate, Tagged< Map > map, Tagged< Map > meta_map, InstanceType instance_type, int instance_size)
Variables
constexpr std::initializer_list< ConstantStringInit > kImportantConstantStringTable
constexpr std::initializer_list< ConstantStringInit > kNotImportantConstantStringTable
constexpr std::initializer_list< StringTypeInit > kStringTypeTable
constexpr std::initializer_list< StructInit > kStructTable
Typedef Documentation
AllocationSiteWithoutWeakNext
using v8::internal::anonymous_namespace{setup-heap-internal.cc}::AllocationSiteWithoutWeakNext = typedef AllocationSite
Definition at line 161 of file setup-heap-internal.cc.
Function Documentation
CreateSharedFunctionInfo()
DirectHandle<SharedFunctionInfo> v8::internal::anonymous_namespace{setup-heap-internal.cc}::CreateSharedFunctionInfo (Isolate * isolate, Builtin builtin, int len, FunctionKind kind = FunctionKind::kNormalFunction)
Definition at line 68 of file setup-heap-internal.cc.
                                                     {
  DirectHandle<SharedFunctionInfo> shared =
      isolate->factory()->NewSharedFunctionInfoForBuiltin(
          isolate->factory()->empty_string(), builtin, len, kAdapt, kind);
  return shared;
}
References v8::internal::Isolate::factory(), v8::internal::kAdapt, and v8::internal::Factory::NewSharedFunctionInfoForBuiltin().
Referenced by v8::internal::Heap::CreateInitialMutableObjects().
InitializePartialMap()
void v8::internal::anonymous_namespace{setup-heap-internal.cc}::InitializePartialMap (Isolate * isolate, Tagged< Map > map, Tagged< Map > meta_map, InstanceType instance_type, int instance_size)
Definition at line 280 of file setup-heap-internal.cc.
                                             {
  map->set_map_after_allocation(isolate, meta_map, SKIP_WRITE_BARRIER);
  map->set_instance_type(instance_type);
  map->set_instance_size(instance_size);
  map->set_visitor_id(Map::GetVisitorId(map));
  map->set_inobject_properties_start_or_constructor_function_index(0);
  DCHECK(!IsJSObjectMap(map));
  map->set_prototype_validity_cell(Map::kPrototypeChainValidSmi, kRelaxedStore);
  map->SetInObjectUnusedPropertyFields(0);
  map->set_bit_field(0);
  map->set_bit_field2(0);
  int bit_field3 =
      Map::Bits3::EnumLengthBits::encode(kInvalidEnumCacheSentinel) |
      Map::Bits3::OwnsDescriptorsBit::encode(true) |
      Map::Bits3::ConstructionCounterBits::encode(Map::kNoSlackTracking);
  map->set_bit_field3(bit_field3);
  DCHECK(!map->is_in_retained_map_list());
  map->clear_padding();
  map->set_elements_kind(TERMINAL_FAST_ELEMENTS_KIND);
}
References v8::internal::bit_field3, v8::internal::DCHECK(), v8::internal::Map::GetVisitorId(), v8::internal::kInvalidEnumCacheSentinel, v8::internal::Map::kNoSlackTracking, v8::internal::Map::kPrototypeChainValidSmi, v8::kRelaxedStore, v8::internal::SKIP_WRITE_BARRIER, and v8::internal::TERMINAL_FAST_ELEMENTS_KIND.
Referenced by v8::internal::Heap::AllocatePartialMap(), and v8::internal::Heap::CreateEarlyReadOnlyMapsAndObjects().
is_important_struct()
constexpr bool v8::internal::anonymous_namespace{setup-heap-internal.cc}::is_important_struct (InstanceType type) [constexpr]
Definition at line 148 of file setup-heap-internal.cc.
                                                      {
  return type == ENUM_CACHE_TYPE || type == CALL_SITE_INFO_TYPE;
}
References v8::internal::tracing::type.
Referenced by v8::internal::Heap::CreateEarlyReadOnlyMapsAndObjects(), and v8::internal::Heap::CreateLateReadOnlyNonJSReceiverMaps().
StructSize()
template<typename StructType >
constexpr int v8::internal::anonymous_namespace{setup-heap-internal.cc}::StructSize () [constexpr]
Definition at line 153 of file setup-heap-internal.cc.
                           {
  if constexpr (std::is_base_of_v<StructLayout, StructType>) {
    return sizeof(StructType);
  } else {
    return StructType::kSize;
  }
}
Variable Documentation
kImportantConstantStringTable
constexpr std::initializer_list<ConstantStringInit> v8::internal::anonymous_namespace{setup-heap-internal.cc}::kImportantConstantStringTable [constexpr]
Initial value:
{
#define CONSTANT_STRING_ELEMENT(_, name, contents)
        EXTRA_IMPORTANT_INTERNALIZED_STRING_LIST_GENERATOR(
            CONSTANT_STRING_ELEMENT,)
            IMPORTANT_INTERNALIZED_STRING_LIST_GENERATOR(
                CONSTANT_STRING_ELEMENT,)
    }
Definition at line 110 of file setup-heap-internal.cc.
Referenced by v8::internal::Heap::CreateImportantReadOnlyObjects().
kNotImportantConstantStringTable
constexpr std::initializer_list<ConstantStringInit> v8::internal::anonymous_namespace{setup-heap-internal.cc}::kNotImportantConstantStringTable [constexpr]
Initial value:
{
#define CONSTANT_STRING_ELEMENT(_, name, contents)
        NOT_IMPORTANT_INTERNALIZED_STRING_LIST_GENERATOR(
            CONSTANT_STRING_ELEMENT,)
    }
Definition at line 121 of file setup-heap-internal.cc.
Referenced by v8::internal::Heap::CreateReadOnlyObjects().
kStringTypeTable
constexpr std::initializer_list<StringTypeInit> v8::internal::anonymous_namespace{setup-heap-internal.cc}::kStringTypeTable [constexpr]
Initial value:
{
#define STRING_TYPE_ELEMENT(type, size, name, CamelName)
}
Definition at line 135 of file setup-heap-internal.cc.
Referenced by v8::internal::Heap::CreateEarlyReadOnlyMapsAndObjects().
kStructTable
constexpr std::initializer_list<StructInit> v8::internal::anonymous_namespace{setup-heap-internal.cc}::kStructTable [constexpr]
Initial value:
{
#define STRUCT_TABLE_ELEMENT(TYPE, Name, name)
#define ALLOCATION_SITE_ELEMENT(_, TYPE, Name, Size, name)
#define DATA_HANDLER_ELEMENT(_, TYPE, Name, Size, name)
}
Definition at line 162 of file setup-heap-internal.cc.
Referenced by v8::internal::Heap::CreateEarlyReadOnlyMapsAndObjects(), and v8::internal::Heap::CreateLateReadOnlyNonJSReceiverMaps().