v8::internal::anonymous_namespace{builtins-object.cc} Namespace Reference
Functions
template<AccessorComponent which_accessor>
Tagged< Object > ObjectDefineAccessor (Isolate *isolate, DirectHandle< JSAny > object, DirectHandle< Object > name, DirectHandle< Object > accessor)
Tagged< Object > ObjectLookupAccessor (Isolate *isolate, DirectHandle< JSAny > object, DirectHandle< Object > key, AccessorComponent component)
Tagged< Object > GetOwnPropertyKeys (Isolate *isolate, BuiltinArguments args, PropertyFilter filter)
Function Documentation
GetOwnPropertyKeys()
Tagged<Object> v8::internal::anonymous_namespace{builtins-object.cc}::GetOwnPropertyKeys (Isolate * isolate, BuiltinArguments args, PropertyFilter filter)
Definition at line 277 of file builtins-object.cc.
                                                         {
  HandleScope scope(isolate);
  DirectHandle<Object> object = args.atOrUndefined(isolate, 1);
  DirectHandle<JSReceiver> receiver;
  ASSIGN_RETURN_FAILURE_ON_EXCEPTION(isolate, receiver,
                                     Object::ToObject(isolate, object));
  DirectHandle<FixedArray> keys;
  ASSIGN_RETURN_FAILURE_ON_EXCEPTION(
      isolate, keys,
      KeyAccumulator::GetKeys(isolate, receiver, KeyCollectionMode::kOwnOnly,
                              filter, GetKeysConversion::kConvertToString));
  return *isolate->factory()->NewJSArrayWithElements(keys);
}
References v8::base::args, ASSIGN_RETURN_FAILURE_ON_EXCEPTION, v8::internal::Isolate::factory(), v8::internal::KeyAccumulator::GetKeys(), v8::internal::kConvertToString, v8::internal::kOwnOnly, v8::internal::Factory::NewJSArrayWithElements(), and v8::Value::ToObject().
Referenced by v8::internal::BUILTIN().
ObjectDefineAccessor()
template<AccessorComponent which_accessor>
Tagged<Object> v8::internal::anonymous_namespace{builtins-object.cc}::ObjectDefineAccessor (Isolate * isolate, DirectHandle< JSAny > object, DirectHandle< Object > name, DirectHandle< Object > accessor)
Definition at line 62 of file builtins-object.cc.
                                                                   {
  // 1. Let O be ? ToObject(this value).
  DirectHandle<JSReceiver> receiver;
  ASSIGN_RETURN_FAILURE_ON_EXCEPTION(isolate, receiver,
                                     Object::ToObject(isolate, object));
  // 2. If IsCallable(getter) is false, throw a TypeError exception.
  if (!IsCallable(*accessor)) {
    MessageTemplate message =
        which_accessor == ACCESSOR_GETTER
            ? MessageTemplate::kObjectGetterExpectingFunction
            : MessageTemplate::kObjectSetterExpectingFunction;
    THROW_NEW_ERROR_RETURN_FAILURE(isolate, NewTypeError(message));
  }
  // 3. Let desc be PropertyDescriptor{[[Get]]: getter, [[Enumerable]]: true,
  // [[Configurable]]: true}.
  PropertyDescriptor desc;
  if (which_accessor == ACCESSOR_GETTER) {
    desc.set_get(Cast<JSAny>(accessor));
  } else {
    DCHECK(which_accessor == ACCESSOR_SETTER);
    desc.set_set(Cast<JSAny>(accessor));
  }
  desc.set_enumerable(true);
  desc.set_configurable(true);
  // 4. Let key be ? ToPropertyKey(P).
  ASSIGN_RETURN_FAILURE_ON_EXCEPTION(isolate, name,
                                     Object::ToPropertyKey(isolate, name));
  // 5. Perform ? DefinePropertyOrThrow(O, key, desc).
  // To preserve legacy behavior, we ignore errors silently rather than
  // throwing an exception.
  Maybe<bool> success = JSReceiver::DefineOwnProperty(
      isolate, receiver, name, &desc, Just(kThrowOnError));
  MAYBE_RETURN(success, ReadOnlyRoots(isolate).exception());
  if (!success.FromJust()) {
    isolate->CountUsage(v8::Isolate::kDefineGetterOrSetterWouldThrow);
  }
  // 6. Return undefined.
  return ReadOnlyRoots(isolate).undefined_value();
}
References v8::internal::ACCESSOR_GETTER, v8::internal::ACCESSOR_SETTER, ASSIGN_RETURN_FAILURE_ON_EXCEPTION, v8::internal::Isolate::CountUsage(), v8::internal::DCHECK(), v8::internal::JSReceiver::DefineOwnProperty(), v8::Maybe< T >::FromJust(), v8::Just(), v8::Isolate::kDefineGetterOrSetterWouldThrow, v8::internal::kThrowOnError, MAYBE_RETURN, v8::internal::name, v8::internal::PropertyDescriptor::set_configurable(), v8::internal::PropertyDescriptor::set_enumerable(), v8::internal::PropertyDescriptor::set_get(), v8::internal::PropertyDescriptor::set_set(), THROW_NEW_ERROR_RETURN_FAILURE, and v8::Value::ToObject().
ObjectLookupAccessor()
Tagged<Object> v8::internal::anonymous_namespace{builtins-object.cc}::ObjectLookupAccessor (Isolate * isolate, DirectHandle< JSAny > object, DirectHandle< Object > key, AccessorComponent component)
Definition at line 105 of file builtins-object.cc.
                                                                 {
  ASSIGN_RETURN_FAILURE_ON_EXCEPTION(isolate, object,
                                     Object::ToObject(isolate, object));
  // TODO(jkummerow/verwaest): PropertyKey(..., bool*) performs a
  // functionally equivalent conversion, but handles element indices slightly
  // differently. Does one of the approaches have a performance advantage?
  ASSIGN_RETURN_FAILURE_ON_EXCEPTION(isolate, key,
                                     Object::ToPropertyKey(isolate, key));
  PropertyKey lookup_key(isolate, key);
  LookupIterator it(isolate, object, lookup_key,
                    LookupIterator::PROTOTYPE_CHAIN_SKIP_INTERCEPTOR);
  for (;; it.Next()) {
    switch (it.state()) {
      case LookupIterator::INTERCEPTOR:
      case LookupIterator::TRANSITION:
        UNREACHABLE();
      case LookupIterator::ACCESS_CHECK:
        if (it.HasAccess()) continue;
        RETURN_FAILURE_ON_EXCEPTION(isolate, isolate->ReportFailedAccessCheck(
                                                 it.GetHolder<JSObject>()));
        UNREACHABLE();
      case LookupIterator::JSPROXY: {
        PropertyDescriptor desc;
        Maybe<bool> found = JSProxy::GetOwnPropertyDescriptor(
            isolate, it.GetHolder<JSProxy>(), it.GetName(), &desc);
        MAYBE_RETURN(found, ReadOnlyRoots(isolate).exception());
        if (found.FromJust()) {
          if (component == ACCESSOR_GETTER && desc.has_get()) {
            return *desc.get();
          }
          if (component == ACCESSOR_SETTER && desc.has_set()) {
            return *desc.set();
          }
          return ReadOnlyRoots(isolate).undefined_value();
        }
        DirectHandle<JSPrototype> prototype;
        ASSIGN_RETURN_FAILURE_ON_EXCEPTION(
            isolate, prototype, JSProxy::GetPrototype(it.GetHolder<JSProxy>()));
        if (IsNull(*prototype, isolate)) {
          return ReadOnlyRoots(isolate).undefined_value();
        }
        return ObjectLookupAccessor(isolate, prototype, key, component);
      }
      case LookupIterator::STRING_LOOKUP_START_OBJECT:
      case LookupIterator::WASM_OBJECT:
        continue; // Continue to the prototype, if present.
      case LookupIterator::TYPED_ARRAY_INDEX_NOT_FOUND:
      case LookupIterator::DATA:
      case LookupIterator::NOT_FOUND:
        return ReadOnlyRoots(isolate).undefined_value();
      case LookupIterator::ACCESSOR: {
        DirectHandle<Object> maybe_pair = it.GetAccessors();
        if (IsAccessorPair(*maybe_pair)) {
          DirectHandle<NativeContext> holder_realm(
              it.GetHolder<JSReceiver>()->GetCreationContext().value(),
              isolate);
          return *AccessorPair::GetComponent(
              isolate, holder_realm, Cast<AccessorPair>(maybe_pair), component);
        }
        continue;
      }
    }
    UNREACHABLE();
  }
}
References v8::internal::LookupIterator::ACCESS_CHECK, v8::internal::LookupIterator::ACCESSOR, v8::internal::ACCESSOR_GETTER, v8::internal::ACCESSOR_SETTER, ASSIGN_RETURN_FAILURE_ON_EXCEPTION, v8::internal::LookupIterator::DATA, v8::Maybe< T >::FromJust(), v8::internal::PropertyDescriptor::get(), v8::internal::LookupIterator::GetAccessors(), v8::internal::AccessorPair::GetComponent(), v8::internal::JSReceiver::GetCreationContext(), v8::internal::LookupIterator::GetHolder(), v8::internal::LookupIterator::GetName(), v8::internal::JSProxy::GetOwnPropertyDescriptor(), v8::internal::JSProxy::GetPrototype(), v8::internal::PropertyDescriptor::has_get(), v8::internal::PropertyDescriptor::has_set(), v8::internal::LookupIterator::HasAccess(), v8::internal::LookupIterator::INTERCEPTOR, v8::internal::IsNull(), v8::internal::LookupIterator::JSPROXY, v8::internal::key, MAYBE_RETURN, v8::internal::LookupIterator::Next(), v8::internal::LookupIterator::NOT_FOUND, v8::internal::prototype, v8::internal::LookupIterator::PROTOTYPE_CHAIN_SKIP_INTERCEPTOR, v8::internal::Isolate::ReportFailedAccessCheck(), RETURN_FAILURE_ON_EXCEPTION, v8::internal::PropertyDescriptor::set(), v8::internal::LookupIterator::state(), v8::internal::LookupIterator::STRING_LOOKUP_START_OBJECT, v8::Value::ToObject(), v8::internal::LookupIterator::TRANSITION, v8::internal::LookupIterator::TYPED_ARRAY_INDEX_NOT_FOUND, v8::internal::UNREACHABLE(), and v8::internal::LookupIterator::WASM_OBJECT.
Referenced by v8::internal::BUILTIN().