v8::base::anonymous_namespace{platform-fuchsia.cc} Namespace Reference
Enumerations
enum class PlacementMode { kUseHint
, kAnywhere
, kFixed
 }
Functions
void SetVmexResource ()
zx_vm_option_t GetProtectionFromMemoryPermission (OS::MemoryPermission access)
zx_vm_option_t GetAlignmentOptionFromAlignment (size_t alignment)
void * MapVmo (const zx::vmar &vmar, void *vmar_base, size_t page_size, void *address, const zx::vmo &vmo, uint64_t offset, PlacementMode placement, size_t size, size_t alignment, OS::MemoryPermission access)
void * CreateAndMapVmo (const zx::vmar &vmar, void *vmar_base, size_t page_size, void *address, PlacementMode placement, size_t size, size_t alignment, OS::MemoryPermission access)
bool UnmapVmo (const zx::vmar &vmar, size_t page_size, void *address, size_t size)
bool SetPermissionsInternal (const zx::vmar &vmar, size_t page_size, void *address, size_t size, OS::MemoryPermission access)
bool DiscardSystemPagesInternal (const zx::vmar &vmar, size_t page_size, void *address, size_t size)
zx_status_t CreateAddressSpaceReservationInternal (const zx::vmar &vmar, void *vmar_base, size_t page_size, void *address, PlacementMode placement, size_t size, size_t alignment, OS::MemoryPermission max_permission, zx::vmar *child, zx_vaddr_t *child_addr)
Variables
static zx_handle_t g_vmex_resource = ZX_HANDLE_INVALID
static void * g_root_vmar_base = nullptr
Enumeration Type Documentation
PlacementMode
enum v8::base::anonymous_namespace{platform-fuchsia.cc}::PlacementMode [strong]
Enumerator
kUseHint
kAnywhere
kFixed
Definition at line 88 of file platform-fuchsia.cc.
                         {
  // Attempt to place the object at the provided address, otherwise elsewhere.
  kUseHint,
  // Place the object anywhere it fits.
  kAnywhere,
  // Place the object at the provided address, otherwise fail.
  kFixed
};
Function Documentation
CreateAddressSpaceReservationInternal()
zx_status_t v8::base::anonymous_namespace{platform-fuchsia.cc}::CreateAddressSpaceReservationInternal (const zx::vmar & vmar, void * vmar_base, size_t page_size, void * address, PlacementMode placement, size_t size, size_t alignment, OS::MemoryPermission max_permission, zx::vmar * child, zx_vaddr_t * child_addr)
Definition at line 206 of file platform-fuchsia.cc.
                            {
  DCHECK_EQ(0, size % page_size);
  DCHECK_EQ(0, alignment % page_size);
  DCHECK_EQ(0, reinterpret_cast<uintptr_t>(address) % alignment);
  DCHECK_IMPLIES(placement != PlacementMode::kAnywhere, address != nullptr);
  // TODO(v8) determine these based on max_permission.
  zx_vm_option_t options = ZX_VM_CAN_MAP_READ | ZX_VM_CAN_MAP_WRITE |
                           ZX_VM_CAN_MAP_EXECUTE | ZX_VM_CAN_MAP_SPECIFIC;
  zx_vm_option_t alignment_option = GetAlignmentOptionFromAlignment(alignment);
  CHECK_NE(0, alignment_option); // Invalid alignment specified
  options |= alignment_option;
  size_t vmar_offset = 0;
  if (placement != PlacementMode::kAnywhere) {
    // Try placing the mapping at the specified address.
    uintptr_t target_addr = reinterpret_cast<uintptr_t>(address);
    uintptr_t base = reinterpret_cast<uintptr_t>(vmar_base);
    DCHECK_GE(target_addr, base);
    vmar_offset = target_addr - base;
    options |= ZX_VM_SPECIFIC;
  }
  zx_status_t status =
      vmar.allocate(options, vmar_offset, size, child, child_addr);
  if (status != ZX_OK && placement == PlacementMode::kUseHint) {
    // If a placement hint was specified but couldn't be used (for example,
    // because the offset overlapped another mapping), then retry again without
    // a vmar_offset to let the kernel pick another location.
    options &= ~(ZX_VM_SPECIFIC);
    status = vmar.allocate(options, 0, size, child, child_addr);
  }
  return status;
}
References CHECK_NE, DCHECK_EQ, DCHECK_GE, DCHECK_IMPLIES, GetAlignmentOptionFromAlignment(), size(), and v8::internal::status.
Referenced by v8::base::OS::CreateAddressSpaceReservation(), and v8::base::AddressSpaceReservation::CreateSubReservation().
CreateAndMapVmo()
void* v8::base::anonymous_namespace{platform-fuchsia.cc}::CreateAndMapVmo (const zx::vmar & vmar, void * vmar_base, size_t page_size, void * address, PlacementMode placement, size_t size, size_t alignment, OS::MemoryPermission access)
Definition at line 148 of file platform-fuchsia.cc.
                                                                   {
  zx::vmo vmo;
  if (zx::vmo::create(size, 0, &vmo) != ZX_OK) {
    return nullptr;
  }
  static const char kVirtualMemoryName[] = "v8-virtualmem";
  vmo.set_property(ZX_PROP_NAME, kVirtualMemoryName,
                   strlen(kVirtualMemoryName));
  // Always call zx_vmo_replace_as_executable() in case the memory will need
  // to be marked as executable in the future.
  // TOOD(https://crbug.com/v8/8899): Only call this when we know that the
  // region will need to be marked as executable in the future.
  zx::unowned_resource vmex(g_vmex_resource);
  if (vmo.replace_as_executable(*vmex, &vmo) != ZX_OK) {
    return nullptr;
  }
  return MapVmo(vmar, vmar_base, page_size, address, vmo, 0, placement, size,
                alignment, access);
}
References g_vmex_resource, MapVmo(), and size().
Referenced by v8::base::AddressSpaceReservation::Allocate().
DiscardSystemPagesInternal()
bool v8::base::anonymous_namespace{platform-fuchsia.cc}::DiscardSystemPagesInternal (const zx::vmar & vmar, size_t page_size, void * address, size_t size)
Definition at line 197 of file platform-fuchsia.cc.
                                                            {
  DCHECK_EQ(0, reinterpret_cast<uintptr_t>(address) % page_size);
  DCHECK_EQ(0, size % page_size);
  uint64_t address_int = reinterpret_cast<uint64_t>(address);
  return vmar.op_range(ZX_VMO_OP_DECOMMIT, address_int, size, nullptr, 0) ==
         ZX_OK;
}
References DCHECK_EQ, and size().
Referenced by v8::base::AddressSpaceReservation::DiscardSystemPages().
GetAlignmentOptionFromAlignment()
zx_vm_option_t v8::base::anonymous_namespace{platform-fuchsia.cc}::GetAlignmentOptionFromAlignment (size_t alignment)
Definition at line 69 of file platform-fuchsia.cc.
                                                                 {
  // The alignment must be one of the ZX_VM_ALIGN_X constants.
  // See zircon/system/public/zircon/types.h.
  static_assert(
      ZX_VM_ALIGN_1KB == (10 << ZX_VM_ALIGN_BASE),
      "Fuchsia's ZX_VM_ALIGN_1KB constant doesn't match expected value");
  static_assert(
      ZX_VM_ALIGN_4GB == (32 << ZX_VM_ALIGN_BASE),
      "Fuchsia's ZX_VM_ALIGN_4GB constant doesn't match expected value");
  zx_vm_option_t alignment_log2 = 0;
  for (int shift = 10; shift <= 32; shift++) {
    if (alignment == (size_t{1} << shift)) {
      alignment_log2 = shift;
      break;
    }
  }
  return alignment_log2 << ZX_VM_ALIGN_BASE;
}
Referenced by CreateAddressSpaceReservationInternal(), and MapVmo().
GetProtectionFromMemoryPermission()
zx_vm_option_t v8::base::anonymous_namespace{platform-fuchsia.cc}::GetProtectionFromMemoryPermission (OS::MemoryPermission access)
Definition at line 50 of file platform-fuchsia.cc.
                                                                            {
  switch (access) {
    case OS::MemoryPermission::kNoAccess:
    case OS::MemoryPermission::kNoAccessWillJitLater:
      return 0; // no permissions
    case OS::MemoryPermission::kRead:
      return ZX_VM_PERM_READ;
    case OS::MemoryPermission::kReadWrite:
      return ZX_VM_PERM_READ | ZX_VM_PERM_WRITE;
    case OS::MemoryPermission::kReadWriteExecute:
      return ZX_VM_PERM_READ | ZX_VM_PERM_WRITE | ZX_VM_PERM_EXECUTE;
    case OS::MemoryPermission::kReadExecute:
      return ZX_VM_PERM_READ | ZX_VM_PERM_EXECUTE;
  }
  UNREACHABLE();
}
References v8::base::OS::kNoAccess, v8::base::OS::kNoAccessWillJitLater, v8::base::OS::kRead, v8::base::OS::kReadExecute, v8::base::OS::kReadWrite, v8::base::OS::kReadWriteExecute, and UNREACHABLE.
MapVmo()
void* v8::base::anonymous_namespace{platform-fuchsia.cc}::MapVmo (const zx::vmar & vmar, void * vmar_base, size_t page_size, void * address, const zx::vmo & vmo, uint64_t offset, PlacementMode placement, size_t size, size_t alignment, OS::MemoryPermission access)
Definition at line 97 of file platform-fuchsia.cc.
                                        {
  DCHECK_EQ(0, size % page_size);
  DCHECK_EQ(0, reinterpret_cast<uintptr_t>(address) % page_size);
  DCHECK_IMPLIES(placement != PlacementMode::kAnywhere, address != nullptr);
  zx_vm_option_t options = GetProtectionFromMemoryPermission(access);
  size_t vmar_offset = 0;
  if (placement == PlacementMode::kAnywhere) {
    zx_vm_option_t alignment_option =
        GetAlignmentOptionFromAlignment(alignment);
    if (alignment_option == 0) {
      // Invalid alignment specified, it is not possible to provide an
      // allocation with correct alignment.
      return nullptr;
    }
    options |= alignment_option;
  } else {
    CHECK_EQ(reinterpret_cast<intptr_t>(address) % alignment, 0);
    // Try placing the mapping at the specified address.
    uintptr_t target_addr = reinterpret_cast<uintptr_t>(address);
    uintptr_t base = reinterpret_cast<uintptr_t>(vmar_base);
    DCHECK_GE(target_addr, base);
    vmar_offset = target_addr - base;
    options |= ZX_VM_SPECIFIC;
  }
  zx_vaddr_t result;
  zx_status_t status = vmar.map(options, vmar_offset, vmo, 0, size, &result);
  if (status == ZX_OK) {
    DCHECK_EQ(result % alignment, 0);
    return reinterpret_cast<void*>(result);
  }
  if (placement != PlacementMode::kUseHint) {
    return nullptr;
  }
  // The hint failed, so we try again without the hint but with alignment
  // options.
  // TODO(404563927): Support alignment > 4GB. CppGC's HeapCage allocates with a
  // 32GB alignment, and the allocation fails on Fuchsia at the moment if the
  // provided placement hint is not available. PartitionAlloc already solved
  // this issue, so maybe that solution could be used here as well.
  return MapVmo(vmar, vmar_base, page_size, nullptr, vmo, offset,
                PlacementMode::kAnywhere, size, alignment, access);
}
References CHECK_EQ, DCHECK_EQ, DCHECK_GE, DCHECK_IMPLIES, GetAlignmentOptionFromAlignment(), v8::base::GetProtectionFromMemoryPermission(), v8::base::internal::result, size(), and v8::internal::status.
Referenced by CreateAndMapVmo().
SetPermissionsInternal()
bool v8::base::anonymous_namespace{platform-fuchsia.cc}::SetPermissionsInternal (const zx::vmar & vmar, size_t page_size, void * address, size_t size, OS::MemoryPermission access)
Definition at line 179 of file platform-fuchsia.cc.
                                                       {
  DCHECK_EQ(0, reinterpret_cast<uintptr_t>(address) % page_size);
  DCHECK_EQ(0, size % page_size);
  uint32_t prot = GetProtectionFromMemoryPermission(access);
  zx_status_t status =
      vmar.protect(prot, reinterpret_cast<uintptr_t>(address), size);
  // Any failure that's not OOM likely indicates a bug in the caller (e.g.
  // using an invalid mapping) so attempt to catch that here to facilitate
  // debugging of these failures. According to the documentation,
  // zx_vmar_protect cannot return ZX_ERR_NO_MEMORY, so any error here is
  // unexpected.
  CHECK_EQ(status, ZX_OK);
  return status == ZX_OK;
}
References CHECK_EQ, DCHECK_EQ, v8::base::GetProtectionFromMemoryPermission(), size(), and v8::internal::status.
Referenced by v8::base::AddressSpaceReservation::SetPermissions().
SetVmexResource()
void v8::base::anonymous_namespace{platform-fuchsia.cc}::SetVmexResource ()
Definition at line 31 of file platform-fuchsia.cc.
                       {
  DCHECK_EQ(g_vmex_resource, ZX_HANDLE_INVALID);
  auto vmex_resource_client =
      component::Connect<fuchsia_kernel::VmexResource>();
  if (vmex_resource_client.is_error()) {
    return;
  }
  fidl::SyncClient sync_vmex_resource_client(
      std::move(vmex_resource_client.value()));
  auto result = sync_vmex_resource_client->Get();
  if (result.is_error()) {
    return;
  }
  g_vmex_resource = result->resource().release();
}
References DCHECK_EQ, g_vmex_resource, and v8::base::internal::result.
Referenced by v8::base::OS::Initialize().
UnmapVmo()
bool v8::base::anonymous_namespace{platform-fuchsia.cc}::UnmapVmo (const zx::vmar & vmar, size_t page_size, void * address, size_t size)
Definition at line 172 of file platform-fuchsia.cc.
                           {
  DCHECK_EQ(0, reinterpret_cast<uintptr_t>(address) % page_size);
  DCHECK_EQ(0, size % page_size);
  return vmar.unmap(reinterpret_cast<uintptr_t>(address), size) == ZX_OK;
}
References DCHECK_EQ, and size().
Referenced by v8::base::AddressSpaceReservation::Free(), v8::base::OS::FreeShared(), and v8::base::AddressSpaceReservation::FreeShared().
Variable Documentation
g_root_vmar_base
void* v8::base::anonymous_namespace{platform-fuchsia.cc}::g_root_vmar_base = nullptr [static]
Definition at line 27 of file platform-fuchsia.cc.
Referenced by v8::base::OS::CreateAddressSpaceReservation(), and v8::base::OS::Initialize().
g_vmex_resource
zx_handle_t v8::base::anonymous_namespace{platform-fuchsia.cc}::g_vmex_resource = ZX_HANDLE_INVALID [static]
Definition at line 25 of file platform-fuchsia.cc.
Referenced by CreateAndMapVmo(), and SetVmexResource().