v8_inspector::anonymous_namespace{v8-deep-serializer.cc} Namespace Reference
Functions
std::unique_ptr< protocol::Value > DescriptionForDate (v8::Local< v8::Context > context, v8::Local< v8::Date > date)
String16 DescriptionForRegExpFlags (v8::Local< v8::RegExp > value)
Response SerializeRegexp (v8::Local< v8::RegExp > value, v8::Local< v8::Context > context, V8SerializationDuplicateTracker &duplicateTracker, protocol::DictionaryValue &result)
Response SerializeDate (v8::Local< v8::Date > value, v8::Local< v8::Context > context, V8SerializationDuplicateTracker &duplicateTracker, protocol::DictionaryValue &result)
Response SerializeArrayValue (v8::Local< v8::Array > value, v8::Local< v8::Context > context, int maxDepth, v8::Local< v8::Object > additionalParameters, V8SerializationDuplicateTracker &duplicateTracker, std::unique_ptr< protocol::ListValue > *result)
Response SerializeArray (v8::Local< v8::Array > value, v8::Local< v8::Context > context, int maxDepth, v8::Local< v8::Object > additionalParameters, V8SerializationDuplicateTracker &duplicateTracker, protocol::DictionaryValue &result)
Response SerializeMap (v8::Local< v8::Map > value, v8::Local< v8::Context > context, int maxDepth, v8::Local< v8::Object > additionalParameters, V8SerializationDuplicateTracker &duplicateTracker, protocol::DictionaryValue &result)
Response SerializeSet (v8::Local< v8::Set > value, v8::Local< v8::Context > context, int maxDepth, v8::Local< v8::Object > additionalParameters, V8SerializationDuplicateTracker &duplicateTracker, protocol::DictionaryValue &result)
Response SerializeObjectValue (v8::Local< v8::Object > value, v8::Local< v8::Context > context, int maxDepth, v8::Local< v8::Object > additionalParameters, V8SerializationDuplicateTracker &duplicateTracker, std::unique_ptr< protocol::ListValue > *result)
Response SerializeObject (v8::Local< v8::Object > value, v8::Local< v8::Context > context, int maxDepth, v8::Local< v8::Object > additionalParameters, V8SerializationDuplicateTracker &duplicateTracker, protocol::DictionaryValue &result)
Function Documentation
DescriptionForDate()
std::unique_ptr<protocol::Value> v8_inspector::anonymous_namespace{v8-deep-serializer.cc}::DescriptionForDate (v8::Local< v8::Context > context, v8::Local< v8::Date > date)
Definition at line 22 of file v8-deep-serializer.cc.
                                                      {
  v8::Isolate* isolate = v8::Isolate::GetCurrent();
  v8::TryCatch tryCatch(isolate);
  v8::Local<v8::String> dateISOString = date->ToISOString();
  return protocol::StringValue::create(
      toProtocolString(isolate, dateISOString));
}
References v8::internal::date, v8::Isolate::GetCurrent(), and v8_inspector::toProtocolString().
Referenced by SerializeDate().
DescriptionForRegExpFlags()
String16 v8_inspector::anonymous_namespace{v8-deep-serializer.cc}::DescriptionForRegExpFlags (v8::Local< v8::RegExp > value)
Definition at line 32 of file v8-deep-serializer.cc.
                                                            {
  String16Builder resultStringBuilder;
  v8::RegExp::Flags flags = value->GetFlags();
  if (flags & v8::RegExp::Flags::kHasIndices) resultStringBuilder.append('d');
  if (flags & v8::RegExp::Flags::kGlobal) resultStringBuilder.append('g');
  if (flags & v8::RegExp::Flags::kIgnoreCase) resultStringBuilder.append('i');
  if (flags & v8::RegExp::Flags::kLinear) resultStringBuilder.append('l');
  if (flags & v8::RegExp::Flags::kMultiline) resultStringBuilder.append('m');
  if (flags & v8::RegExp::Flags::kDotAll) resultStringBuilder.append('s');
  if (flags & v8::RegExp::Flags::kUnicode) resultStringBuilder.append('u');
  if (flags & v8::RegExp::Flags::kUnicodeSets) {
    resultStringBuilder.append('v');
  }
  if (flags & v8::RegExp::Flags::kSticky) resultStringBuilder.append('y');
  return resultStringBuilder.toString();
}
References v8_inspector::String16Builder::append(), flags(), v8_inspector::String16Builder::toString(), and v8::internal::value.
Referenced by SerializeRegexp().
SerializeArray()
Response v8_inspector::anonymous_namespace{v8-deep-serializer.cc}::SerializeArray (v8::Local< v8::Array > value, v8::Local< v8::Context > context, int maxDepth, v8::Local< v8::Object > additionalParameters, V8SerializationDuplicateTracker & duplicateTracker, protocol::DictionaryValue & result)
Definition at line 113 of file v8-deep-serializer.cc.
                                                         {
  result.setString("type",
                   protocol::Runtime::DeepSerializedValue::TypeEnum::Array);
  if (maxDepth > 0) {
    std::unique_ptr<protocol::ListValue> serializedValue;
    Response response =
        SerializeArrayValue(value, context, maxDepth, additionalParameters,
                            duplicateTracker, &serializedValue);
    if (!response.IsSuccess()) return response;
    result.setValue("value", std::move(serializedValue));
  }
  return Response::Success();
}
References v8::base::internal::result, SerializeArrayValue(), and v8::internal::value.
Referenced by v8_inspector::V8DeepSerializer::serializeV8Value().
SerializeArrayValue()
Response v8_inspector::anonymous_namespace{v8-deep-serializer.cc}::SerializeArrayValue (v8::Local< v8::Array > value, v8::Local< v8::Context > context, int maxDepth, v8::Local< v8::Object > additionalParameters, V8SerializationDuplicateTracker & duplicateTracker, std::unique_ptr< protocol::ListValue > * result)
Definition at line 86 of file v8-deep-serializer.cc.
                                                                       {
  std::unique_ptr<protocol::ListValue> serializedValue =
      protocol::ListValue::create();
  uint32_t length = value->Length();
  serializedValue->reserve(length);
  for (uint32_t i = 0; i < length; i++) {
    v8::Local<v8::Value> elementValue;
    bool success = value->Get(context, i).ToLocal(&elementValue);
    CHECK(success);
    USE(success);
    std::unique_ptr<protocol::DictionaryValue> elementProtocolValue;
    Response response = ValueMirror::create(context, elementValue)
                            ->buildDeepSerializedValue(
                                context, maxDepth - 1, additionalParameters,
                                duplicateTracker, &elementProtocolValue);
    if (!response.IsSuccess()) return response;
    serializedValue->pushValue(std::move(elementProtocolValue));
  }
  *result = std::move(serializedValue);
  return Response::Success();
}
References CHECK, v8_inspector::ValueMirror::create(), v8::internal::length, v8::base::internal::result, USE, and v8::internal::value.
Referenced by SerializeArray(), and SerializeSet().
SerializeDate()
Response v8_inspector::anonymous_namespace{v8-deep-serializer.cc}::SerializeDate (v8::Local< v8::Date > value, v8::Local< v8::Context > context, V8SerializationDuplicateTracker & duplicateTracker, protocol::DictionaryValue & result)
Definition at line 73 of file v8-deep-serializer.cc.
                                                        {
  result.setString("type",
                   protocol::Runtime::DeepSerializedValue::TypeEnum::Date);
  std::unique_ptr<protocol::Value> dateDescription =
      DescriptionForDate(context, value.As<v8::Date>());
  result.setValue("value", std::move(dateDescription));
  return Response::Success();
}
References DescriptionForDate(), v8::base::internal::result, and v8::internal::value.
Referenced by v8_inspector::V8DeepSerializer::serializeV8Value().
SerializeMap()
Response v8_inspector::anonymous_namespace{v8-deep-serializer.cc}::SerializeMap (v8::Local< v8::Map > value, v8::Local< v8::Context > context, int maxDepth, v8::Local< v8::Object > additionalParameters, V8SerializationDuplicateTracker & duplicateTracker, protocol::DictionaryValue & result)
Definition at line 134 of file v8-deep-serializer.cc.
                                                       {
  result.setString("type",
                   protocol::Runtime::DeepSerializedValue::TypeEnum::Map);
  if (maxDepth > 0) {
    std::unique_ptr<protocol::ListValue> serializedValue =
        protocol::ListValue::create();
    v8::Local<v8::Array> propertiesAndValues = value->AsArray();
    uint32_t length = propertiesAndValues->Length();
    serializedValue->reserve(length);
    for (uint32_t i = 0; i < length; i += 2) {
      v8::Local<v8::Value> keyV8Value, propertyV8Value;
      std::unique_ptr<protocol::Value> keyProtocolValue;
      std::unique_ptr<protocol::DictionaryValue> propertyProtocolValue;
      bool success = propertiesAndValues->Get(context, i).ToLocal(&keyV8Value);
      CHECK(success);
      success =
          propertiesAndValues->Get(context, i + 1).ToLocal(&propertyV8Value);
      CHECK(success);
      USE(success);
      if (keyV8Value->IsString()) {
        keyProtocolValue = protocol::StringValue::create(toProtocolString(
            v8::Isolate::GetCurrent(), keyV8Value.As<v8::String>()));
      } else {
        std::unique_ptr<protocol::DictionaryValue> keyDictionaryProtocolValue;
        Response response =
            ValueMirror::create(context, keyV8Value)
                ->buildDeepSerializedValue(
                    context, maxDepth - 1, additionalParameters,
                    duplicateTracker, &keyDictionaryProtocolValue);
        if (!response.IsSuccess()) return response;
        keyProtocolValue = std::move(keyDictionaryProtocolValue);
      }
      Response response = ValueMirror::create(context, propertyV8Value)
                              ->buildDeepSerializedValue(
                                  context, maxDepth - 1, additionalParameters,
                                  duplicateTracker, &propertyProtocolValue);
      if (!response.IsSuccess()) return response;
      std::unique_ptr<protocol::ListValue> keyValueList =
          protocol::ListValue::create();
      keyValueList->pushValue(std::move(keyProtocolValue));
      keyValueList->pushValue(std::move(propertyProtocolValue));
      serializedValue->pushValue(std::move(keyValueList));
    }
    result.setValue("value", std::move(serializedValue));
  }
  return Response::Success();
}
References v8::Local< T >::As(), CHECK, v8_inspector::ValueMirror::create(), v8::Object::Get(), v8::Isolate::GetCurrent(), v8::Value::IsString(), v8::Array::Length(), v8::internal::length, v8::internal::compiler::Map, v8::base::internal::result, v8::MaybeLocal< T >::ToLocal(), v8_inspector::toProtocolString(), USE, and v8::internal::value.
Referenced by v8_inspector::V8DeepSerializer::serializeV8Value().
SerializeObject()
Response v8_inspector::anonymous_namespace{v8-deep-serializer.cc}::SerializeObject (v8::Local< v8::Object > value, v8::Local< v8::Context > context, int maxDepth, v8::Local< v8::Object > additionalParameters, V8SerializationDuplicateTracker & duplicateTracker, protocol::DictionaryValue & result)
Definition at line 274 of file v8-deep-serializer.cc.
                                                          {
  result.setString("type",
                   protocol::Runtime::DeepSerializedValue::TypeEnum::Object);
  if (maxDepth > 0) {
    std::unique_ptr<protocol::ListValue> serializedValue;
    Response response = SerializeObjectValue(
        value.As<v8::Object>(), context, maxDepth, additionalParameters,
        duplicateTracker, &serializedValue);
    if (!response.IsSuccess()) return response;
    result.setValue("value", std::move(serializedValue));
  }
  return Response::Success();
}
References v8::internal::compiler::Object, v8::base::internal::result, SerializeObjectValue(), and v8::internal::value.
Referenced by v8::internal::requires(), v8::internal::FastJsonStringifier< Char >::SerializeObject(), and v8_inspector::V8DeepSerializer::serializeV8Value().
SerializeObjectValue()
Response v8_inspector::anonymous_namespace{v8-deep-serializer.cc}::SerializeObjectValue (v8::Local< v8::Object > value, v8::Local< v8::Context > context, int maxDepth, v8::Local< v8::Object > additionalParameters, V8SerializationDuplicateTracker & duplicateTracker, std::unique_ptr< protocol::ListValue > * result)
Definition at line 213 of file v8-deep-serializer.cc.
                                                                        {
  std::unique_ptr<protocol::ListValue> serializedValue =
      protocol::ListValue::create();
  // Iterate through object's enumerable properties ignoring symbols.
  v8::Local<v8::Array> propertyNames;
  bool success =
      value
          ->GetOwnPropertyNames(context,
                                static_cast<v8::PropertyFilter>(
                                    v8::PropertyFilter::ONLY_ENUMERABLE |
                                    v8::PropertyFilter::SKIP_SYMBOLS),
                                v8::KeyConversionMode::kConvertToString)
          .ToLocal(&propertyNames);
  CHECK(success);
  uint32_t length = propertyNames->Length();
  serializedValue->reserve(length);
  for (uint32_t i = 0; i < length; i++) {
    v8::Local<v8::Value> keyV8Value, propertyV8Value;
    std::unique_ptr<protocol::Value> keyProtocolValue;
    std::unique_ptr<protocol::DictionaryValue> propertyProtocolValue;
    success = propertyNames->Get(context, i).ToLocal(&keyV8Value);
    CHECK(success);
    CHECK(keyV8Value->IsString());
    v8::Maybe<bool> hasRealNamedProperty =
        value->HasRealNamedProperty(context, keyV8Value.As<v8::String>());
    // Don't access properties with interceptors.
    if (hasRealNamedProperty.IsNothing() || !hasRealNamedProperty.FromJust()) {
      continue;
    }
    keyProtocolValue = protocol::StringValue::create(toProtocolString(
        v8::Isolate::GetCurrent(), keyV8Value.As<v8::String>()));
    success = value->Get(context, keyV8Value).ToLocal(&propertyV8Value);
    CHECK(success);
    USE(success);
    Response response = ValueMirror::create(context, propertyV8Value)
                            ->buildDeepSerializedValue(
                                context, maxDepth - 1, additionalParameters,
                                duplicateTracker, &propertyProtocolValue);
    if (!response.IsSuccess()) return response;
    std::unique_ptr<protocol::ListValue> keyValueList =
        protocol::ListValue::create();
    keyValueList->pushValue(std::move(keyProtocolValue));
    keyValueList->pushValue(std::move(propertyProtocolValue));
    serializedValue->pushValue(std::move(keyValueList));
  }
  *result = std::move(serializedValue);
  return Response::Success();
}
References v8::Local< T >::As(), CHECK, v8_inspector::ValueMirror::create(), v8::Maybe< T >::FromJust(), v8::Object::Get(), v8::Isolate::GetCurrent(), v8::Maybe< T >::IsNothing(), v8::Value::IsString(), v8::kConvertToString, v8::Array::Length(), v8::internal::length, v8::internal::ONLY_ENUMERABLE, v8::base::internal::result, v8::internal::SKIP_SYMBOLS, v8::MaybeLocal< T >::ToLocal(), v8_inspector::toProtocolString(), USE, and v8::internal::value.
Referenced by SerializeObject().
SerializeRegexp()
Response v8_inspector::anonymous_namespace{v8-deep-serializer.cc}::SerializeRegexp (v8::Local< v8::RegExp > value, v8::Local< v8::Context > context, V8SerializationDuplicateTracker & duplicateTracker, protocol::DictionaryValue & result)
Definition at line 49 of file v8-deep-serializer.cc.
                                                          {
  result.setString("type",
                   protocol::Runtime::DeepSerializedValue::TypeEnum::Regexp);
  std::unique_ptr<protocol::DictionaryValue> resultValue =
      protocol::DictionaryValue::create();
  resultValue->setValue(protocol::String("pattern"),
                        protocol::StringValue::create(toProtocolString(
                            v8::Isolate::GetCurrent(), value->GetSource())));
  String16 flags = DescriptionForRegExpFlags(value);
  if (!flags.isEmpty()) {
    resultValue->setValue(protocol::String("flags"),
                          protocol::StringValue::create(flags));
  }
  result.setValue("value", std::move(resultValue));
  return Response::Success();
}
References DescriptionForRegExpFlags(), flags(), v8::Isolate::GetCurrent(), v8::base::internal::result, v8_inspector::toProtocolString(), and v8::internal::value.
Referenced by v8_inspector::V8DeepSerializer::serializeV8Value().
SerializeSet()
Response v8_inspector::anonymous_namespace{v8-deep-serializer.cc}::SerializeSet (v8::Local< v8::Set > value, v8::Local< v8::Context > context, int maxDepth, v8::Local< v8::Object > additionalParameters, V8SerializationDuplicateTracker & duplicateTracker, protocol::DictionaryValue & result)
Definition at line 195 of file v8-deep-serializer.cc.
                                                       {
  result.setString("type",
                   protocol::Runtime::DeepSerializedValue::TypeEnum::Set);
  if (maxDepth > 0) {
    std::unique_ptr<protocol::ListValue> serializedValue;
    Response response = SerializeArrayValue(value->AsArray(), context, maxDepth,
                                            additionalParameters,
                                            duplicateTracker, &serializedValue);
    result.setValue("value", std::move(serializedValue));
  }
  return Response::Success();
}
References v8::base::internal::result, SerializeArrayValue(), and v8::internal::value.
Referenced by v8_inspector::V8DeepSerializer::serializeV8Value().