v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc} Namespace Reference
Classes
class ValueTypeFieldIterator
class ValueTypeFieldsRange
class DebugFieldType
Enumerations
enum TypeStorage { kAsStoredInHeap
, kUncompressed
 }
Functions
void GenerateFieldAddressAccessor (const Field &field, const std::string &class_name, std::ostream &h_contents, std::ostream &cc_contents)
void GenerateFieldValueAccessor (const Field &field, const std::string &class_name, std::ostream &h_contents, std::ostream &cc_contents)
void GenerateGetPropsChunkForField (const Field &field, std::ostream &get_props_impl, std::string class_name)
void GenerateClassDebugReader (const ClassType &type, std::ostream &h_contents, std::ostream &cc_contents, std::ostream &visitor, std::unordered_set< const ClassType * > *done)
Enumeration Type Documentation
TypeStorage
enum v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::TypeStorage
Enumerator
kAsStoredInHeap
kUncompressed
Definition at line 22 of file class-debug-reader-generator.cc.
                 {
  kAsStoredInHeap,
  kUncompressed,
};
Function Documentation
GenerateClassDebugReader()
void v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::GenerateClassDebugReader (const ClassType & type, std::ostream & h_contents, std::ostream & cc_contents, std::ostream & visitor, std::unordered_set< const ClassType * > * done)
Definition at line 447 of file class-debug-reader-generator.cc.
                                                                        {
  // Make sure each class only gets generated once.
  if (!done->insert(&type).second) return;
  const ClassType* super_type = type.GetSuperClass();
  // We must emit the classes in dependency order. If the super class hasn't
  // been emitted yet, go handle it first.
  if (super_type != nullptr) {
    GenerateClassDebugReader(*super_type, h_contents, cc_contents, visitor,
                             done);
  }
  // Classes with undefined layout don't grant any particular value here and may
  // not correspond with actual C++ classes, so skip them.
  if (type.HasUndefinedLayout()) return;
  const std::string name = type.name();
  const std::string super_name =
      super_type == nullptr ? "Object" : super_type->name();
  h_contents << "\nclass Tq" << name << " : public Tq" << super_name << " {\n";
  h_contents << " public:\n";
  h_contents << " inline Tq" << name << "(uintptr_t address) : Tq"
             << super_name << "(address) {}\n";
  h_contents << kTqObjectOverrideDecls;
  cc_contents << "\nconst char* Tq" << name << "::GetName() const {\n";
  cc_contents << " return \"v8::internal::" << name << "\";\n";
  cc_contents << "}\n";
  cc_contents << "\nvoid Tq" << name
              << "::Visit(TqObjectVisitor* visitor) const {\n";
  cc_contents << " visitor->Visit" << name << "(this);\n";
  cc_contents << "}\n";
  cc_contents << "\nbool Tq" << name
              << "::IsSuperclassOf(const TqObject* other) const {\n";
  cc_contents
      << " return GetName() != other->GetName() && dynamic_cast<const Tq"
      << name << "*>(other) != nullptr;\n";
  cc_contents << "}\n";
  // By default, the visitor method for this class just calls the visitor method
  // for this class's parent. This allows custom visitors to only override a few
  // classes they care about without needing to know about the entire hierarchy.
  visitor << " virtual void Visit" << name << "(const Tq" << name
          << "* object) {\n";
  visitor << " Visit" << super_name << "(object);\n";
  visitor << " }\n";
  std::stringstream get_props_impl;
  for (const Field& field : type.fields()) {
    if (field.name_and_type.type == TypeOracle::GetVoidType()) continue;
    if (field.offset.has_value()) {
      GenerateFieldAddressAccessor(field, name, h_contents, cc_contents);
      GenerateFieldValueAccessor(field, name, h_contents, cc_contents);
    }
    GenerateGetPropsChunkForField(field, get_props_impl, name);
  }
  h_contents << "};\n";
  cc_contents << "\nstd::vector<std::unique_ptr<ObjectProperty>> Tq" << name
              << "::GetProperties(d::MemoryAccessor accessor) const {\n";
  // Start by getting the fields from the parent class.
  cc_contents << " std::vector<std::unique_ptr<ObjectProperty>> result = Tq"
              << super_name << "::GetProperties(accessor);\n";
  // Then add the fields from this class.
  cc_contents << get_props_impl.str();
  cc_contents << " return result;\n";
  cc_contents << "}\n";
}
References GenerateFieldAddressAccessor(), GenerateFieldValueAccessor(), GenerateGetPropsChunkForField(), v8::internal::torque::TypeOracle::GetVoidType(), v8::internal::torque::kTqObjectOverrideDecls, v8::internal::name, v8::internal::torque::AggregateType::name(), v8::internal::string, and v8::internal::tracing::type.
Referenced by v8::internal::torque::ImplementationVisitor::GenerateClassDebugReaders().
GenerateFieldAddressAccessor()
void v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::GenerateFieldAddressAccessor (const Field & field, const std::string & class_name, std::ostream & h_contents, std::ostream & cc_contents)
Definition at line 208 of file class-debug-reader-generator.cc.
                                                           {
  DebugFieldType debug_field_type(field);
  const std::string address_getter = debug_field_type.GetAddressGetter();
  h_contents << " uintptr_t " << address_getter << "() const;\n";
  cc_contents << "\nuintptr_t Tq" << class_name << "::" << address_getter
              << "() const {\n";
  cc_contents << " return address_ - i::kHeapObjectTag + " << *field.offset
              << ";\n";
  cc_contents << "}\n";
}
References v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::DebugFieldType::GetAddressGetter(), v8::internal::torque::Field::offset, and v8::internal::string.
Referenced by GenerateClassDebugReader().
GenerateFieldValueAccessor()
void v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::GenerateFieldValueAccessor (const Field & field, const std::string & class_name, std::ostream & h_contents, std::ostream & cc_contents)
Definition at line 252 of file class-debug-reader-generator.cc.
                                                         {
  // Currently not implemented for struct fields.
  if (field.name_and_type.type->StructSupertype()) return;
  DebugFieldType debug_field_type(field);
  const std::string address_getter = debug_field_type.GetAddressGetter();
  const std::string field_getter =
      "Get" + CamelifyString(field.name_and_type.name) + "Value";
  std::string index_param;
  std::string index_offset;
  if (field.index) {
    index_param = ", size_t offset";
    index_offset = " + offset * sizeof(value)";
  }
  std::string field_value_type = debug_field_type.GetValueType(kUncompressed);
  h_contents << " Value<" << field_value_type << "> " << field_getter
             << "(d::MemoryAccessor accessor " << index_param << ") const;\n";
  cc_contents << "\nValue<" << field_value_type << "> Tq" << class_name
              << "::" << field_getter << "(d::MemoryAccessor accessor"
              << index_param << ") const {\n";
  cc_contents << " " << debug_field_type.GetValueType(kAsStoredInHeap)
              << " value{};\n";
  cc_contents << " d::MemoryAccessResult validity = accessor("
              << address_getter << "()" << index_offset
              << ", reinterpret_cast<uint8_t*>(&value), sizeof(value));\n";
#ifdef V8_MAP_PACKING
  if (field_getter == "GetMapValue") {
    cc_contents << " value = i::MapWord::Unpack(value);\n";
  }
#endif
  cc_contents << " return {validity, "
              << (debug_field_type.IsTagged()
                      ? "EnsureDecompressed(value, address_)"
                      : "value")
              << "};\n";
  cc_contents << "}\n";
}
References v8::internal::torque::CamelifyString(), v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::DebugFieldType::GetAddressGetter(), v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::DebugFieldType::GetValueType(), v8::internal::torque::Field::index, v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::DebugFieldType::IsTagged(), kAsStoredInHeap, kUncompressed, v8::internal::torque::NameAndType::name, v8::internal::torque::Field::name_and_type, v8::internal::string, v8::internal::torque::Type::StructSupertype(), and v8::internal::torque::NameAndType::type.
Referenced by GenerateClassDebugReader().
GenerateGetPropsChunkForField()
void v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::GenerateGetPropsChunkForField (const Field & field, std::ostream & get_props_impl, std::string class_name)
Definition at line 352 of file class-debug-reader-generator.cc.
                                                         {
  DebugFieldType debug_field_type(field);
  // If the current field is a struct or bitfield struct, create a vector
  // describing its fields. Otherwise this vector will be empty.
  std::string struct_field_list =
      field.name_and_type.name + "_struct_field_list";
  get_props_impl << " std::vector<std::unique_ptr<StructProperty>> "
                 << struct_field_list << ";\n";
  for (const auto& struct_field :
       ValueTypeFieldsRange(field.name_and_type.type)) {
    DebugFieldType struct_field_type(struct_field.name_and_type,
                                     struct_field.pos);
    get_props_impl << " " << struct_field_list
                   << ".push_back(std::make_unique<StructProperty>(\""
                   << struct_field.name_and_type.name << "\", "
                   << struct_field_type.GetTypeString(kAsStoredInHeap) << ", "
                   << struct_field.offset_bytes << ", " << struct_field.num_bits
                   << ", " << struct_field.shift_bits << "));\n";
  }
  struct_field_list = "std::move(" + struct_field_list + ")";
  // The number of values and property kind for non-indexed properties:
  std::string count_value = "1";
  std::string property_kind = "d::PropertyKind::kSingle";
  // If the field is indexed, emit a fetch of the array length, and change
  // count_value and property_kind to be the correct values for an array.
  if (field.index) {
    std::string indexed_field_slice =
        "indexed_field_slice_" + field.name_and_type.name;
    get_props_impl << " auto " << indexed_field_slice << " = "
                   << "TqDebugFieldSlice" << class_name
                   << CamelifyString(field.name_and_type.name)
                   << "(accessor, address_);\n";
    std::string validity = indexed_field_slice + ".validity";
    std::string value = indexed_field_slice + ".value";
    property_kind = "GetArrayKind(" + validity + ")";
    get_props_impl << " if (" << validity
                   << " == d::MemoryAccessResult::kOk) {\n"
                   << " result.push_back(std::make_unique<ObjectProperty>(\""
                   << field.name_and_type.name << "\", "
                   << debug_field_type.GetTypeString(kAsStoredInHeap) << ", "
                   << "address_ - i::kHeapObjectTag + std::get<1>(" << value
                   << "), "
                   << "std::get<2>(" << value << ")"
                   << ", " << debug_field_type.GetSize() << ", "
                   << struct_field_list << ", " << property_kind << "));\n"
                   << " }\n";
    return;
  }
  get_props_impl << " result.push_back(std::make_unique<ObjectProperty>(\""
                 << field.name_and_type.name << "\", "
                 << debug_field_type.GetTypeString(kAsStoredInHeap) << ", "
                 << debug_field_type.GetAddressGetter() << "(), " << count_value
                 << ", " << debug_field_type.GetSize() << ", "
                 << struct_field_list << ", " << property_kind << "));\n";
}
References v8::internal::torque::CamelifyString(), v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::DebugFieldType::GetAddressGetter(), v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::DebugFieldType::GetSize(), v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::DebugFieldType::GetTypeString(), v8::internal::torque::Field::index, kAsStoredInHeap, v8::internal::torque::NameAndType::name, v8::internal::torque::Field::name_and_type, v8::internal::string, v8::internal::torque::NameAndType::type, and v8::internal::value.
Referenced by GenerateClassDebugReader().