v8::internal::anonymous_namespace{runtime-literals.cc} Namespace Reference
Classes
class JSObjectWalkVisitor
class DeprecationUpdateContext
class AllocationSiteCreationContext
struct ObjectLiteralHelper
struct ArrayLiteralHelper
Functions
bool IsUninitializedLiteralSite (Tagged< Object > literal_site)
bool HasBoilerplate (DirectHandle< Object > literal_site)
void PreInitializeLiteralSite (DirectHandle< FeedbackVector > vector, FeedbackSlot slot)
MaybeDirectHandle< JSObject > DeepWalk (Handle< JSObject > object, DeprecationUpdateContext *site_context)
MaybeDirectHandle< JSObject > DeepWalk (Handle< JSObject > object, AllocationSiteCreationContext *site_context)
MaybeDirectHandle< JSObject > DeepCopy (Handle< JSObject > object, AllocationSiteUsageContext *site_context)
Handle< JSObject > CreateObjectLiteral (Isolate *isolate, DirectHandle< ObjectBoilerplateDescription > object_boilerplate_description, int flags, AllocationType allocation)
Handle< JSObject > CreateArrayLiteral (Isolate *isolate, DirectHandle< ArrayBoilerplateDescription > array_boilerplate_description, AllocationType allocation)
template<typename LiteralHelper >
MaybeDirectHandle< JSObject > CreateLiteralWithoutAllocationSite (Isolate *isolate, Handle< HeapObject > description, int flags)
template<typename LiteralHelper >
MaybeDirectHandle< JSObject > CreateLiteral (Isolate *isolate, Handle< HeapObject > maybe_vector, int literals_index, Handle< HeapObject > description, int flags)
Function Documentation
CreateArrayLiteral()
Handle< JSObject > v8::internal::anonymous_namespace{runtime-literals.cc}::CreateArrayLiteral (Isolate * isolate, DirectHandle< ArrayBoilerplateDescription > array_boilerplate_description, AllocationType allocation)
Definition at line 438 of file runtime-literals.cc.
                               {
  ElementsKind constant_elements_kind =
      array_boilerplate_description->elements_kind();
  Handle<FixedArrayBase> constant_elements_values(
      array_boilerplate_description->constant_elements(isolate), isolate);
  // Create the JSArray.
  Handle<FixedArrayBase> copied_elements_values;
  if (IsDoubleElementsKind(constant_elements_kind)) {
    copied_elements_values = isolate->factory()->CopyFixedDoubleArray(
        Cast<FixedDoubleArray>(constant_elements_values));
  } else {
    DCHECK(IsSmiOrObjectElementsKind(constant_elements_kind));
    const bool is_cow = (constant_elements_values->map() ==
                         ReadOnlyRoots(isolate).fixed_cow_array_map());
    if (is_cow) {
      copied_elements_values = constant_elements_values;
      if (DEBUG_BOOL) {
        auto fixed_array_values = Cast<FixedArray>(copied_elements_values);
        for (int i = 0; i < fixed_array_values->length(); i++) {
          DCHECK(!IsFixedArray(fixed_array_values->get(i)));
        }
      }
    } else {
      Handle<FixedArray> fixed_array_values =
          Cast<FixedArray>(constant_elements_values);
      Handle<FixedArray> fixed_array_values_copy =
          isolate->factory()->CopyFixedArray(fixed_array_values);
      copied_elements_values = fixed_array_values_copy;
      for (int i = 0; i < fixed_array_values->length(); i++) {
        Tagged<Object> value = fixed_array_values_copy->get(i);
        Tagged<HeapObject> value_heap_object;
        if (value.GetHeapObject(isolate, &value_heap_object)) {
          if (IsArrayBoilerplateDescription(value_heap_object, isolate)) {
            HandleScope sub_scope(isolate);
            DirectHandle<ArrayBoilerplateDescription> boilerplate(
                Cast<ArrayBoilerplateDescription>(value_heap_object), isolate);
            DirectHandle<JSObject> result =
                CreateArrayLiteral(isolate, boilerplate, allocation);
            fixed_array_values_copy->set(i, *result);
          } else if (IsObjectBoilerplateDescription(value_heap_object,
                                                    isolate)) {
            HandleScope sub_scope(isolate);
            DirectHandle<ObjectBoilerplateDescription> boilerplate(
                Cast<ObjectBoilerplateDescription>(value_heap_object), isolate);
            DirectHandle<JSObject> result = CreateObjectLiteral(
                isolate, boilerplate, boilerplate->flags(), allocation);
            fixed_array_values_copy->set(i, *result);
          }
        }
      }
    }
  }
  return isolate->factory()->NewJSArrayWithElements(
      copied_elements_values, constant_elements_kind,
      copied_elements_values->length(), allocation);
}
References v8::internal::Factory::CopyFixedArray(), v8::internal::Factory::CopyFixedDoubleArray(), CreateObjectLiteral(), v8::internal::DCHECK(), DEBUG_BOOL, v8::internal::Isolate::factory(), v8::internal::IsDoubleElementsKind(), v8::internal::IsSmiOrObjectElementsKind(), v8::internal::Factory::NewJSArrayWithElements(), v8::base::internal::result, and v8::internal::value.
Referenced by v8::internal::anonymous_namespace{runtime-literals.cc}::ArrayLiteralHelper::Create(), and CreateObjectLiteral().
CreateLiteral()
template<typename LiteralHelper >
MaybeDirectHandle<JSObject> v8::internal::anonymous_namespace{runtime-literals.cc}::CreateLiteral (Isolate * isolate, Handle< HeapObject > maybe_vector, int literals_index, Handle< HeapObject > description, int flags)
Definition at line 512 of file runtime-literals.cc.
                                                     {
  if (!IsFeedbackVector(*maybe_vector)) {
    DCHECK(IsUndefined(*maybe_vector));
    return CreateLiteralWithoutAllocationSite<LiteralHelper>(
        isolate, description, flags);
  }
  auto vector = Cast<FeedbackVector>(maybe_vector);
  FeedbackSlot literals_slot(FeedbackVector::ToSlot(literals_index));
  CHECK(literals_slot.ToInt() < vector->length());
  Handle<Object> literal_site(Cast<Object>(vector->Get(literals_slot)),
                              isolate);
  Handle<AllocationSite> site;
  Handle<JSObject> boilerplate;
  if (HasBoilerplate(literal_site)) {
    site = Cast<AllocationSite>(literal_site);
    boilerplate = Handle<JSObject>(site->boilerplate(), isolate);
  } else {
    // Eagerly create AllocationSites for literals that contain an Array.
    bool needs_initial_allocation_site =
        (flags & AggregateLiteral::kNeedsInitialAllocationSite) != 0;
    if (!needs_initial_allocation_site &&
        IsUninitializedLiteralSite(*literal_site)) {
      PreInitializeLiteralSite(vector, literals_slot);
      return CreateLiteralWithoutAllocationSite<LiteralHelper>(
          isolate, description, flags);
    } else {
      boilerplate = LiteralHelper::Create(isolate, description, flags,
                                          AllocationType::kOld);
    }
    // Install AllocationSite objects.
    AllocationSiteCreationContext creation_context(isolate);
    site = creation_context.EnterNewScope();
    RETURN_ON_EXCEPTION(isolate, DeepWalk(boilerplate, &creation_context));
    creation_context.ExitScope(site, boilerplate);
    vector->SynchronizedSet(literals_slot, *site);
  }
  static_assert(static_cast<int>(ObjectLiteral::kDisableMementos) ==
                static_cast<int>(ArrayLiteral::kDisableMementos));
  bool enable_mementos = (flags & ObjectLiteral::kDisableMementos) == 0;
  // Copy the existing boilerplate.
  AllocationSiteUsageContext usage_context(isolate, site, enable_mementos);
  usage_context.EnterNewScope();
  MaybeDirectHandle<JSObject> copy = DeepCopy(boilerplate, &usage_context);
  usage_context.ExitScope(site, boilerplate);
  return copy;
}
References CHECK, v8::internal::DCHECK(), DeepCopy(), DeepWalk(), v8::internal::AllocationSiteUsageContext::EnterNewScope(), v8::internal::anonymous_namespace{runtime-literals.cc}::AllocationSiteCreationContext::EnterNewScope(), v8::internal::AllocationSiteUsageContext::ExitScope(), v8::internal::anonymous_namespace{runtime-literals.cc}::AllocationSiteCreationContext::ExitScope(), v8::internal::flags, HasBoilerplate(), IsUninitializedLiteralSite(), v8::internal::AggregateLiteral::kDisableMementos, v8::internal::AggregateLiteral::kNeedsInitialAllocationSite, v8::internal::kOld, PreInitializeLiteralSite(), RETURN_ON_EXCEPTION, v8::internal::FeedbackSlot::ToInt(), and v8::internal::FeedbackVector::ToSlot().
CreateLiteralWithoutAllocationSite()
template<typename LiteralHelper >
MaybeDirectHandle<JSObject> v8::internal::anonymous_namespace{runtime-literals.cc}::CreateLiteralWithoutAllocationSite (Isolate * isolate, Handle< HeapObject > description, int flags)
Definition at line 502 of file runtime-literals.cc.
                                                                 {
  Handle<JSObject> literal = LiteralHelper::Create(isolate, description, flags,
                                                   AllocationType::kYoung);
  DeprecationUpdateContext update_context(isolate);
  RETURN_ON_EXCEPTION(isolate, DeepWalk(literal, &update_context));
  return literal;
}
References DeepWalk(), v8::internal::flags, v8::internal::kYoung, and RETURN_ON_EXCEPTION.
CreateObjectLiteral()
Handle< JSObject > v8::internal::anonymous_namespace{runtime-literals.cc}::CreateObjectLiteral (Isolate * isolate, DirectHandle< ObjectBoilerplateDescription > object_boilerplate_description, int flags, AllocationType allocation)
Definition at line 367 of file runtime-literals.cc.
                                          {
  DirectHandle<NativeContext> native_context = isolate->native_context();
  bool use_fast_elements = (flags & ObjectLiteral::kFastElements) != 0;
  bool has_null_prototype = (flags & ObjectLiteral::kHasNullPrototype) != 0;
  // In case we have function literals, we want the object to be in
  // slow properties mode for now. We don't go in the map cache because
  // maps with constant functions can't be shared if the functions are
  // not the same (which is the common case).
  int number_of_properties =
      object_boilerplate_description->backing_store_size();
  // Ignoring number_of_properties for force dictionary map with
  // __proto__:null.
  DirectHandle<Map> map =
      has_null_prototype
          ? direct_handle(native_context->slow_object_with_null_prototype_map(),
                          isolate)
          : isolate->factory()->ObjectLiteralMapFromCache(native_context,
                                                          number_of_properties);
  Handle<JSObject> boilerplate =
      isolate->factory()->NewFastOrSlowJSObjectFromMap(
          map, number_of_properties, allocation);
  // Normalize the elements of the boilerplate to save space if needed.
  if (!use_fast_elements) JSObject::NormalizeElements(isolate, boilerplate);
  // Add the constant properties to the boilerplate.
  int length = object_boilerplate_description->boilerplate_properties_count();
  // TODO(verwaest): Support tracking representations in the boilerplate.
  for (int index = 0; index < length; index++) {
    DirectHandle<Object> key(object_boilerplate_description->name(index),
                             isolate);
    Handle<Object> value(object_boilerplate_description->value(index), isolate);
    if (IsHeapObject(*value)) {
      if (IsArrayBoilerplateDescription(Cast<HeapObject>(*value), isolate)) {
        auto array_boilerplate = Cast<ArrayBoilerplateDescription>(value);
        value = CreateArrayLiteral(isolate, array_boilerplate, allocation);
      } else if (IsObjectBoilerplateDescription(Cast<HeapObject>(*value),
                                                isolate)) {
        auto object_boilerplate = Cast<ObjectBoilerplateDescription>(value);
        value = CreateObjectLiteral(isolate, object_boilerplate,
                                    object_boilerplate->flags(), allocation);
      }
    }
    uint32_t element_index = 0;
    if (Object::ToArrayIndex(*key, &element_index)) {
      // Array index (uint32).
      if (IsUninitialized(*value, isolate)) {
        value = handle(Smi::zero(), isolate);
      }
      JSObject::SetOwnElementIgnoreAttributes(boilerplate, element_index, value,
                                              NONE)
          .Check();
    } else {
      DirectHandle<String> name = Cast<String>(key);
      DCHECK(!name->AsArrayIndex(&element_index));
      JSObject::SetOwnPropertyIgnoreAttributes(boilerplate, name, value, NONE)
          .Check();
    }
  }
  return boilerplate;
}
References CreateArrayLiteral(), v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::flags, v8::internal::handle(), v8::internal::index, v8::internal::IsHeapObject(), v8::internal::key, v8::internal::ObjectLiteral::kFastElements, v8::internal::ObjectLiteral::kHasNullPrototype, v8::internal::length, v8::internal::name, v8::internal::Isolate::native_context(), v8::internal::native_context, v8::internal::Factory::NewFastOrSlowJSObjectFromMap(), v8::internal::NONE, v8::internal::JSObject::NormalizeElements(), v8::internal::Factory::ObjectLiteralMapFromCache(), v8::internal::JSObject::SetOwnElementIgnoreAttributes(), v8::internal::JSObject::SetOwnPropertyIgnoreAttributes(), v8::internal::Object::ToArrayIndex(), v8::internal::value, and v8::internal::Smi::zero().
Referenced by v8::internal::anonymous_namespace{runtime-literals.cc}::ObjectLiteralHelper::Create(), and CreateArrayLiteral().
DeepCopy()
MaybeDirectHandle<JSObject> v8::internal::anonymous_namespace{runtime-literals.cc}::DeepCopy (Handle< JSObject > object, AllocationSiteUsageContext * site_context)
Definition at line 325 of file runtime-literals.cc.
                                                                               {
  JSObjectWalkVisitor<AllocationSiteUsageContext> v(site_context);
  MaybeDirectHandle<JSObject> copy = v.StructureWalk(object);
  DirectHandle<JSObject> for_assert;
  DCHECK(!copy.ToHandle(&for_assert) || !for_assert.is_identical_to(object));
  return copy;
}
References v8::internal::DCHECK(), v8::internal::DirectHandle< T >::is_identical_to(), v8::internal::anonymous_namespace{runtime-literals.cc}::JSObjectWalkVisitor< ContextObject >::StructureWalk(), and v8::internal::MaybeDirectHandle< T >::ToHandle().
Referenced by CreateLiteral().
DeepWalk() [1/2]
MaybeDirectHandle<JSObject> v8::internal::anonymous_namespace{runtime-literals.cc}::DeepWalk (Handle< JSObject > object, AllocationSiteCreationContext * site_context)
Definition at line 316 of file runtime-literals.cc.
                                                                          {
  JSObjectWalkVisitor<AllocationSiteCreationContext> v(site_context);
  MaybeDirectHandle<JSObject> result = v.StructureWalk(object);
  DirectHandle<JSObject> for_assert;
  DCHECK(!result.ToHandle(&for_assert) || for_assert.is_identical_to(object));
  return result;
}
References v8::internal::DCHECK(), v8::internal::DirectHandle< T >::is_identical_to(), v8::base::internal::result, and v8::internal::anonymous_namespace{runtime-literals.cc}::JSObjectWalkVisitor< ContextObject >::StructureWalk().
Referenced by CreateLiteral(), and CreateLiteralWithoutAllocationSite().
DeepWalk() [2/2]
MaybeDirectHandle<JSObject> v8::internal::anonymous_namespace{runtime-literals.cc}::DeepWalk (Handle< JSObject > object, DeprecationUpdateContext * site_context)
Definition at line 307 of file runtime-literals.cc.
                                                                             {
  JSObjectWalkVisitor<DeprecationUpdateContext> v(site_context);
  MaybeDirectHandle<JSObject> result = v.StructureWalk(object);
  DirectHandle<JSObject> for_assert;
  DCHECK(!result.ToHandle(&for_assert) || for_assert.is_identical_to(object));
  return result;
}
References v8::internal::DCHECK(), v8::internal::DirectHandle< T >::is_identical_to(), v8::base::internal::result, and v8::internal::anonymous_namespace{runtime-literals.cc}::JSObjectWalkVisitor< ContextObject >::StructureWalk().
HasBoilerplate()
bool v8::internal::anonymous_namespace{runtime-literals.cc}::HasBoilerplate (DirectHandle< Object > literal_site)
Definition at line 25 of file runtime-literals.cc.
                                                       {
  return !IsSmi(*literal_site);
}
References v8::internal::IsSmi().
Referenced by CreateLiteral(), v8::internal::RUNTIME_FUNCTION(), and v8::internal::TF_BUILTIN().
IsUninitializedLiteralSite()
bool v8::internal::anonymous_namespace{runtime-literals.cc}::IsUninitializedLiteralSite (Tagged< Object > literal_site)
Definition at line 21 of file runtime-literals.cc.
                                                             {
  return literal_site == Smi::zero();
}
References v8::internal::Smi::zero().
Referenced by CreateLiteral(), and v8::internal::RUNTIME_FUNCTION().
PreInitializeLiteralSite()
void v8::internal::anonymous_namespace{runtime-literals.cc}::PreInitializeLiteralSite (DirectHandle< FeedbackVector > vector, FeedbackSlot slot)
Definition at line 29 of file runtime-literals.cc.
                                                 {
  vector->SynchronizedSet(slot, Smi::FromInt(1));
}
References v8::internal::Smi::FromInt().
Referenced by CreateLiteral(), and v8::internal::RUNTIME_FUNCTION().