v8::base::ieee754 Namespace Reference
Namespaces
 anonymous_namespace{ieee754.cc}
 legacy
Functions
double acos (double x)
double acosh (double x)
double asin (double x)
double asinh (double x)
double atan (double x)
double atan2 (double y, double x)
double cos (double x)
double exp (double x)
double atanh (double x)
double log (double x)
double log1p (double x)
static double k_log1p (double f)
double log2 (double x)
double log10 (double x)
double expm1 (double x)
double cbrt (double x)
double sin (double x)
double tan (double x)
double cosh (double x)
double sinh (double x)
double tanh (double x)
Variables
static const double Lg1 = 6.666666666666735130e-01
static const double Lg2 = 3.999999999940941908e-01
static const double Lg3 = 2.857142874366239149e-01
static const double Lg4 = 2.222219843214978396e-01
static const double Lg5 = 1.818357216161805012e-01
static const double Lg6 = 1.531383769920937332e-01
static const double Lg7 = 1.479819860511658591e-01
Function Documentation
acos()
V8_BASE_EXPORT double v8::base::ieee754::acos (double x)
Definition at line 862 of file ieee754.cc.
                      {
  static const double
      one = 1.00000000000000000000e+00, /* 0x3FF00000, 0x00000000 */
      pi = 3.14159265358979311600e+00, /* 0x400921FB, 0x54442D18 */
      pio2_hi = 1.57079632679489655800e+00, /* 0x3FF921FB, 0x54442D18 */
      pio2_lo = 6.12323399573676603587e-17, /* 0x3C91A626, 0x33145C07 */
      pS0 = 1.66666666666666657415e-01, /* 0x3FC55555, 0x55555555 */
      pS1 = -3.25565818622400915405e-01, /* 0xBFD4D612, 0x03EB6F7D */
      pS2 = 2.01212532134862925881e-01, /* 0x3FC9C155, 0x0E884455 */
      pS3 = -4.00555345006794114027e-02, /* 0xBFA48228, 0xB5688F3B */
      pS4 = 7.91534994289814532176e-04, /* 0x3F49EFE0, 0x7501B288 */
      pS5 = 3.47933107596021167570e-05, /* 0x3F023DE1, 0x0DFDF709 */
      qS1 = -2.40339491173441421878e+00, /* 0xC0033A27, 0x1C8A2D4B */
      qS2 = 2.02094576023350569471e+00, /* 0x40002AE5, 0x9C598AC8 */
      qS3 = -6.88283971605453293030e-01, /* 0xBFE6066C, 0x1B8D0159 */
      qS4 = 7.70381505559019352791e-02; /* 0x3FB3B8C5, 0xB12E9282 */
  double z, p, q, r, w, s, c, df;
  int32_t hx, ix;
  GET_HIGH_WORD(hx, x);
  ix = hx & 0x7FFFFFFF;
  if (ix >= 0x3FF00000) { /* |x| >= 1 */
    uint32_t lx;
    GET_LOW_WORD(lx, x);
    if (((ix - 0x3FF00000) | lx) == 0) { /* |x|==1 */
      if (hx > 0)
        return 0.0; /* acos(1) = 0 */
      else
        return pi + 2.0 * pio2_lo; /* acos(-1)= pi */
    }
    return std::numeric_limits<double>::signaling_NaN(); // acos(|x|>1) is NaN
  }
  if (ix < 0x3FE00000) { /* |x| < 0.5 */
    if (ix <= 0x3C600000) return pio2_hi + pio2_lo; /*if|x|<2**-57*/
    z = x * x;
    p = z * (pS0 + z * (pS1 + z * (pS2 + z * (pS3 + z * (pS4 + z * pS5)))));
    q = one + z * (qS1 + z * (qS2 + z * (qS3 + z * qS4)));
    r = p / q;
    return pio2_hi - (x - (pio2_lo - x * r));
  } else if (hx < 0) { /* x < -0.5 */
    z = (one + x) * 0.5;
    p = z * (pS0 + z * (pS1 + z * (pS2 + z * (pS3 + z * (pS4 + z * pS5)))));
    q = one + z * (qS1 + z * (qS2 + z * (qS3 + z * qS4)));
    s = sqrt(z);
    r = p / q;
    w = r * s - pio2_lo;
    return pi - 2.0 * (s + w);
  } else { /* x > 0.5 */
    z = (one - x) * 0.5;
    s = sqrt(z);
    df = s;
    SET_LOW_WORD(df, 0);
    c = (z - df * df) / (s + df);
    p = z * (pS0 + z * (pS1 + z * (pS2 + z * (pS3 + z * (pS4 + z * pS5)))));
    q = one + z * (qS1 + z * (qS2 + z * (qS3 + z * qS4)));
    r = p / q;
    w = r * s + c;
    return 2.0 * (df + w);
  }
}
References GET_HIGH_WORD, GET_LOW_WORD, and one.
Referenced by v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::f64_acos_wrapper(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::FloatUnary(), and v8::internal::compiler::MachineOperatorReducer::Reduce().
acosh()
V8_BASE_EXPORT double v8::base::ieee754::acosh (double x)
Definition at line 936 of file ieee754.cc.
                       {
  static const double
      one = 1.0,
      ln2 = 6.93147180559945286227e-01; /* 0x3FE62E42, 0xFEFA39EF */
  double t;
  int32_t hx;
  uint32_t lx;
  EXTRACT_WORDS(hx, lx, x);
  if (hx < 0x3FF00000) { /* x < 1 */
    return std::numeric_limits<double>::signaling_NaN();
  } else if (hx >= 0x41B00000) { /* x > 2**28 */
    if (hx >= 0x7FF00000) { /* x is inf of NaN */
      return x + x;
    } else {
      return log(x) + ln2; /* acosh(huge)=log(2x) */
    }
  } else if (((hx - 0x3FF00000) | lx) == 0) {
    return 0.0; /* acosh(1) = 0 */
  } else if (hx > 0x40000000) { /* 2**28 > x > 2 */
    t = x * x;
    return log(2.0 * x - one / (x + sqrt(t - one)));
  } else { /* 1<x<2 */
    t = x - one;
    return log1p(t + sqrt(2.0 * t + t * t));
  }
}
References EXTRACT_WORDS, log(), log1p(), and one.
Referenced by v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::FloatUnary(), and v8::internal::compiler::MachineOperatorReducer::Reduce().
asin()
V8_BASE_EXPORT double v8::base::ieee754::asin (double x)
Definition at line 991 of file ieee754.cc.
                      {
  static const double
      one = 1.00000000000000000000e+00, /* 0x3FF00000, 0x00000000 */
      huge = 1.000e+300,
      pio2_hi = 1.57079632679489655800e+00, /* 0x3FF921FB, 0x54442D18 */
      pio2_lo = 6.12323399573676603587e-17, /* 0x3C91A626, 0x33145C07 */
      pio4_hi = 7.85398163397448278999e-01, /* 0x3FE921FB, 0x54442D18 */
                                            /* coefficient for R(x^2) */
      pS0 = 1.66666666666666657415e-01, /* 0x3FC55555, 0x55555555 */
      pS1 = -3.25565818622400915405e-01, /* 0xBFD4D612, 0x03EB6F7D */
      pS2 = 2.01212532134862925881e-01, /* 0x3FC9C155, 0x0E884455 */
      pS3 = -4.00555345006794114027e-02, /* 0xBFA48228, 0xB5688F3B */
      pS4 = 7.91534994289814532176e-04, /* 0x3F49EFE0, 0x7501B288 */
      pS5 = 3.47933107596021167570e-05, /* 0x3F023DE1, 0x0DFDF709 */
      qS1 = -2.40339491173441421878e+00, /* 0xC0033A27, 0x1C8A2D4B */
      qS2 = 2.02094576023350569471e+00, /* 0x40002AE5, 0x9C598AC8 */
      qS3 = -6.88283971605453293030e-01, /* 0xBFE6066C, 0x1B8D0159 */
      qS4 = 7.70381505559019352791e-02; /* 0x3FB3B8C5, 0xB12E9282 */
  double t, w, p, q, c, r, s;
  int32_t hx, ix;
  t = 0;
  GET_HIGH_WORD(hx, x);
  ix = hx & 0x7FFFFFFF;
  if (ix >= 0x3FF00000) { /* |x|>= 1 */
    uint32_t lx;
    GET_LOW_WORD(lx, x);
    if (((ix - 0x3FF00000) | lx) == 0) { /* asin(1)=+-pi/2 with inexact */
      return x * pio2_hi + x * pio2_lo;
    }
    return std::numeric_limits<double>::signaling_NaN(); // asin(|x|>1) is NaN
  } else if (ix < 0x3FE00000) { /* |x|<0.5 */
    if (ix < 0x3E400000) { /* if |x| < 2**-27 */
      if (huge + x > one) return x; /* return x with inexact if x!=0*/
    } else {
      t = x * x;
    }
    p = t * (pS0 + t * (pS1 + t * (pS2 + t * (pS3 + t * (pS4 + t * pS5)))));
    q = one + t * (qS1 + t * (qS2 + t * (qS3 + t * qS4)));
    w = p / q;
    return x + x * w;
  }
  /* 1> |x|>= 0.5 */
  w = one - fabs(x);
  t = w * 0.5;
  p = t * (pS0 + t * (pS1 + t * (pS2 + t * (pS3 + t * (pS4 + t * pS5)))));
  q = one + t * (qS1 + t * (qS2 + t * (qS3 + t * qS4)));
  s = sqrt(t);
  if (ix >= 0x3FEF3333) { /* if |x| > 0.975 */
    w = p / q;
    t = pio2_hi - (2.0 * (s + s * w) - pio2_lo);
  } else {
    w = s;
    SET_LOW_WORD(w, 0);
    c = (t - w * w) / (s + w);
    r = p / q;
    p = 2.0 * s * r - (pio2_lo - 2.0 * c);
    q = pio4_hi - 2.0 * w;
    t = pio4_hi - (p - q);
  }
  if (hx > 0)
    return t;
  else
    return -t;
}
References GET_HIGH_WORD, GET_LOW_WORD, and one.
Referenced by v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::f64_asin_wrapper(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::FloatUnary(), and v8::internal::compiler::MachineOperatorReducer::Reduce().
asinh()
V8_BASE_EXPORT double v8::base::ieee754::asinh (double x)
Definition at line 1067 of file ieee754.cc.
                       {
  static const double
      one = 1.00000000000000000000e+00, /* 0x3FF00000, 0x00000000 */
      ln2 = 6.93147180559945286227e-01, /* 0x3FE62E42, 0xFEFA39EF */
      huge = 1.00000000000000000000e+300;
  double t, w;
  int32_t hx, ix;
  GET_HIGH_WORD(hx, x);
  ix = hx & 0x7FFFFFFF;
  if (ix >= 0x7FF00000) return x + x; /* x is inf or NaN */
  if (ix < 0x3E300000) { /* |x|<2**-28 */
    if (huge + x > one) return x; /* return x inexact except 0 */
  }
  if (ix > 0x41B00000) { /* |x| > 2**28 */
    w = log(fabs(x)) + ln2;
  } else if (ix > 0x40000000) { /* 2**28 > |x| > 2.0 */
    t = fabs(x);
    w = log(2.0 * t + one / (sqrt(x * x + one) + t));
  } else { /* 2.0 > |x| > 2**-28 */
    t = x * x;
    w = log1p(fabs(x) + t / (one + sqrt(one + t)));
  }
  if (hx > 0) {
    return w;
  } else {
    return -w;
  }
}
References GET_HIGH_WORD, log(), log1p(), and one.
Referenced by v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::FloatUnary(), and v8::internal::compiler::MachineOperatorReducer::Reduce().
atan()
V8_BASE_EXPORT double v8::base::ieee754::atan (double x)
Definition at line 1116 of file ieee754.cc.
                      {
  static const double atanhi[] = {
      4.63647609000806093515e-01, /* atan(0.5)hi 0x3FDDAC67, 0x0561BB4F */
      7.85398163397448278999e-01, /* atan(1.0)hi 0x3FE921FB, 0x54442D18 */
      9.82793723247329054082e-01, /* atan(1.5)hi 0x3FEF730B, 0xD281F69B */
      1.57079632679489655800e+00, /* atan(inf)hi 0x3FF921FB, 0x54442D18 */
  };
  static const double atanlo[] = {
      2.26987774529616870924e-17, /* atan(0.5)lo 0x3C7A2B7F, 0x222F65E2 */
      3.06161699786838301793e-17, /* atan(1.0)lo 0x3C81A626, 0x33145C07 */
      1.39033110312309984516e-17, /* atan(1.5)lo 0x3C700788, 0x7AF0CBBD */
      6.12323399573676603587e-17, /* atan(inf)lo 0x3C91A626, 0x33145C07 */
  };
  static const double aT[] = {
      3.33333333333329318027e-01, /* 0x3FD55555, 0x5555550D */
      -1.99999999998764832476e-01, /* 0xBFC99999, 0x9998EBC4 */
      1.42857142725034663711e-01, /* 0x3FC24924, 0x920083FF */
      -1.11111104054623557880e-01, /* 0xBFBC71C6, 0xFE231671 */
      9.09088713343650656196e-02, /* 0x3FB745CD, 0xC54C206E */
      -7.69187620504482999495e-02, /* 0xBFB3B0F2, 0xAF749A6D */
      6.66107313738753120669e-02, /* 0x3FB10D66, 0xA0D03D51 */
      -5.83357013379057348645e-02, /* 0xBFADDE2D, 0x52DEFD9A */
      4.97687799461593236017e-02, /* 0x3FA97B4B, 0x24760DEB */
      -3.65315727442169155270e-02, /* 0xBFA2B444, 0x2C6A6C2F */
      1.62858201153657823623e-02, /* 0x3F90AD3A, 0xE322DA11 */
  };
  static const double one = 1.0, huge = 1.0e300;
  double w, s1, s2, z;
  int32_t ix, hx, id;
  GET_HIGH_WORD(hx, x);
  ix = hx & 0x7FFFFFFF;
  if (ix >= 0x44100000) { /* if |x| >= 2^66 */
    uint32_t low;
    GET_LOW_WORD(low, x);
    if (ix > 0x7FF00000 || (ix == 0x7FF00000 && (low != 0)))
      return x + x; /* NaN */
    if (hx > 0)
      return atanhi[3] + *const_cast<volatile double*>(&atanlo[3]);
    else
      return -atanhi[3] - *const_cast<volatile double*>(&atanlo[3]);
  }
  if (ix < 0x3FDC0000) { /* |x| < 0.4375 */
    if (ix < 0x3E400000) { /* |x| < 2^-27 */
      if (huge + x > one) return x; /* raise inexact */
    }
    id = -1;
  } else {
    x = fabs(x);
    if (ix < 0x3FF30000) { /* |x| < 1.1875 */
      if (ix < 0x3FE60000) { /* 7/16 <=|x|<11/16 */
        id = 0;
        x = (2.0 * x - one) / (2.0 + x);
      } else { /* 11/16<=|x|< 19/16 */
        id = 1;
        x = (x - one) / (x + one);
      }
    } else {
      if (ix < 0x40038000) { /* |x| < 2.4375 */
        id = 2;
        x = (x - 1.5) / (one + 1.5 * x);
      } else { /* 2.4375 <= |x| < 2^66 */
        id = 3;
        x = -1.0 / x;
      }
    }
  }
  /* end of argument reduction */
  z = x * x;
  w = z * z;
  /* break sum from i=0 to 10 aT[i]z**(i+1) into odd and even poly */
  s1 = z * (aT[0] +
            w * (aT[2] + w * (aT[4] + w * (aT[6] + w * (aT[8] + w * aT[10])))));
  s2 = w * (aT[1] + w * (aT[3] + w * (aT[5] + w * (aT[7] + w * aT[9]))));
  if (id < 0) {
    return x - x * (s1 + s2);
  } else {
    z = atanhi[id] - ((x * (s1 + s2) - atanlo[id]) - x);
    return (hx < 0) ? -z : z;
  }
}
References GET_HIGH_WORD, GET_LOW_WORD, and one.
Referenced by v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), atan2(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::FloatUnary(), and v8::internal::compiler::MachineOperatorReducer::Reduce().
atan2()
V8_BASE_EXPORT double v8::base::ieee754::atan2 (double y, double x)
Definition at line 1228 of file ieee754.cc.
                                 {
  static volatile double tiny = 1.0e-300;
  static const double
      zero = 0.0,
      pi_o_4 = 7.8539816339744827900E-01, /* 0x3FE921FB, 0x54442D18 */
      pi_o_2 = 1.5707963267948965580E+00, /* 0x3FF921FB, 0x54442D18 */
      pi = 3.1415926535897931160E+00; /* 0x400921FB, 0x54442D18 */
  static volatile double pi_lo =
      1.2246467991473531772E-16; /* 0x3CA1A626, 0x33145C07 */
  double z;
  int32_t k, m, hx, hy, ix, iy;
  uint32_t lx, ly;
  EXTRACT_WORDS(hx, lx, x);
  ix = hx & 0x7FFFFFFF;
  EXTRACT_WORDS(hy, ly, y);
  iy = hy & 0x7FFFFFFF;
  if (((ix | ((lx | NegateWithWraparound<int32_t>(lx)) >> 31)) > 0x7FF00000) ||
      ((iy | ((ly | NegateWithWraparound<int32_t>(ly)) >> 31)) > 0x7FF00000)) {
    return x + y; /* x or y is NaN */
  }
  if ((SubWithWraparound(hx, 0x3FF00000) | lx) == 0) {
    return atan(y); /* x=1.0 */
  }
  m = ((hy >> 31) & 1) | ((hx >> 30) & 2); /* 2*sign(x)+sign(y) */
  /* when y = 0 */
  if ((iy | ly) == 0) {
    switch (m) {
      case 0:
      case 1:
        return y; /* atan(+-0,+anything)=+-0 */
      case 2:
        return pi + tiny; /* atan(+0,-anything) = pi */
      case 3:
        return -pi - tiny; /* atan(-0,-anything) =-pi */
    }
  }
  /* when x = 0 */
  if ((ix | lx) == 0) return (hy < 0) ? -pi_o_2 - tiny : pi_o_2 + tiny;
  /* when x is INF */
  if (ix == 0x7FF00000) {
    if (iy == 0x7FF00000) {
      switch (m) {
        case 0:
          return pi_o_4 + tiny; /* atan(+INF,+INF) */
        case 1:
          return -pi_o_4 - tiny; /* atan(-INF,+INF) */
        case 2:
          return 3.0 * pi_o_4 + tiny; /*atan(+INF,-INF)*/
        case 3:
          return -3.0 * pi_o_4 - tiny; /*atan(-INF,-INF)*/
      }
    } else {
      switch (m) {
        case 0:
          return zero; /* atan(+...,+INF) */
        case 1:
          return -zero; /* atan(-...,+INF) */
        case 2:
          return pi + tiny; /* atan(+...,-INF) */
        case 3:
          return -pi - tiny; /* atan(-...,-INF) */
      }
    }
  }
  /* when y is INF */
  if (iy == 0x7FF00000) return (hy < 0) ? -pi_o_2 - tiny : pi_o_2 + tiny;
  /* compute y/x */
  k = (iy - ix) >> 20;
  if (k > 60) { /* |y/x| > 2**60 */
    z = pi_o_2 + 0.5 * pi_lo;
    m &= 1;
  } else if (hx < 0 && k < -60) {
    z = 0.0; /* 0 > |y|/x > -2**-60 */
  } else {
    z = atan(fabs(y / x)); /* safe to do y/x */
  }
  switch (m) {
    case 0:
      return z; /* atan(+,+) */
    case 1:
      return -z; /* atan(-,+) */
    case 2:
      return pi - (z - pi_lo); /* atan(+,-) */
    default: /* case 3 */
      return (z - pi_lo) - pi; /* atan(-,-) */
  }
}
References atan(), EXTRACT_WORDS, v8::base::internal::y, and v8::internal::zero.
Referenced by v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::FloatBinop(), and v8::internal::compiler::MachineOperatorReducer::Reduce().
atanh()
V8_BASE_EXPORT double v8::base::ieee754::atanh (double x)
Definition at line 1557 of file ieee754.cc.
                       {
  static const double one = 1.0, huge = 1e300;
  static const double zero = 0.0;
  double t;
  int32_t hx, ix;
  uint32_t lx;
  EXTRACT_WORDS(hx, lx, x);
  ix = hx & 0x7FFFFFFF;
  if ((ix | ((lx | NegateWithWraparound<int32_t>(lx)) >> 31)) > 0x3FF00000) {
    /* |x|>1 */
    return std::numeric_limits<double>::signaling_NaN();
  }
  if (ix == 0x3FF00000) {
    return x > 0 ? std::numeric_limits<double>::infinity()
                 : -std::numeric_limits<double>::infinity();
  }
  if (ix < 0x3E300000 && (huge + x) > zero) return x; /* x<2**-28 */
  SET_HIGH_WORD(x, ix);
  if (ix < 0x3FE00000) { /* x < 0.5 */
    t = x + x;
    t = 0.5 * log1p(t + t * x / (one - x));
  } else {
    t = 0.5 * log1p((x + x) / (one - x));
  }
  if (hx >= 0)
    return t;
  else
    return -t;
}
References EXTRACT_WORDS, log1p(), one, SET_HIGH_WORD, and v8::internal::zero.
Referenced by v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::FloatUnary(), and v8::internal::compiler::MachineOperatorReducer::Reduce().
cbrt()
V8_BASE_EXPORT double v8::base::ieee754::cbrt (double x)
Definition at line 2333 of file ieee754.cc.
                      {
  static const uint32_t
      B1 = 715094163, /* B1 = (1023-1023/3-0.03306235651)*2**20 */
      B2 = 696219795; /* B2 = (1023-1023/3-54/3-0.03306235651)*2**20 */
  /* |1/cbrt(x) - p(x)| < 2**-23.5 (~[-7.93e-8, 7.929e-8]). */
  static const double P0 = 1.87595182427177009643, /* 0x3FFE03E6, 0x0F61E692 */
      P1 = -1.88497979543377169875, /* 0xBFFE28E0, 0x92F02420 */
      P2 = 1.621429720105354466140, /* 0x3FF9F160, 0x4A49D6C2 */
      P3 = -0.758397934778766047437, /* 0xBFE844CB, 0xBEE751D9 */
      P4 = 0.145996192886612446982; /* 0x3FC2B000, 0xD4E4EDD7 */
  int32_t hx;
  double r, s, t = 0.0, w;
  uint32_t sign;
  uint32_t high, low;
  EXTRACT_WORDS(hx, low, x);
  sign = hx & 0x80000000; /* sign= sign(x) */
  hx ^= sign;
  if (hx >= 0x7FF00000) return (x + x); /* cbrt(NaN,INF) is itself */
  /*
   * Rough cbrt to 5 bits:
   * cbrt(2**e*(1+m) ~= 2**(e/3)*(1+(e%3+m)/3)
   * where e is integral and >= 0, m is real and in [0, 1), and "/" and
   * "%" are integer division and modulus with rounding towards minus
   * infinity. The RHS is always >= the LHS and has a maximum relative
   * error of about 1 in 16. Adding a bias of -0.03306235651 to the
   * (e%3+m)/3 term reduces the error to about 1 in 32. With the IEEE
   * floating point representation, for finite positive normal values,
   * ordinary integer division of the value in bits magically gives
   * almost exactly the RHS of the above provided we first subtract the
   * exponent bias (1023 for doubles) and later add it back. We do the
   * subtraction virtually to keep e >= 0 so that ordinary integer
   * division rounds towards minus infinity; this is also efficient.
   */
  if (hx < 0x00100000) { /* zero or subnormal? */
    if ((hx | low) == 0) return (x); /* cbrt(0) is itself */
    SET_HIGH_WORD(t, 0x43500000); /* set t= 2**54 */
    t *= x;
    GET_HIGH_WORD(high, t);
    INSERT_WORDS(t, sign | ((high & 0x7FFFFFFF) / 3 + B2), 0);
  } else {
    INSERT_WORDS(t, sign | (hx / 3 + B1), 0);
  }
  /*
   * New cbrt to 23 bits:
   * cbrt(x) = t*cbrt(x/t**3) ~= t*P(t**3/x)
   * where P(r) is a polynomial of degree 4 that approximates 1/cbrt(r)
   * to within 2**-23.5 when |r - 1| < 1/10. The rough approximation
   * has produced t such than |t/cbrt(x) - 1| ~< 1/32, and cubing this
   * gives us bounds for r = t**3/x.
   *
   * Try to optimize for parallel evaluation as in k_tanf.c.
   */
  r = (t * t) * (t / x);
  t = t * ((P0 + r * (P1 + r * P2)) + ((r * r) * r) * (P3 + r * P4));
  /*
   * Round t away from zero to 23 bits (sloppily except for ensuring that
   * the result is larger in magnitude than cbrt(x) but not much more than
   * 2 23-bit ulps larger). With rounding towards zero, the error bound
   * would be ~5/6 instead of ~4/6. With a maximum error of 2 23-bit ulps
   * in the rounded t, the infinite-precision error in the Newton
   * approximation barely affects third digit in the final error
   * 0.667; the error in the rounded t can be up to about 3 23-bit ulps
   * before the final error is larger than 0.667 ulps.
   */
  uint64_t bits = base::bit_cast<uint64_t>(t);
  bits = (bits + 0x80000000) & 0xFFFFFFFFC0000000ULL;
  t = base::bit_cast<double>(bits);
  /* one step Newton iteration to 53 bits with error < 0.667 ulps */
  s = t * t; /* t*t is exact */
  r = x / s; /* error <= 0.5 ulps; |r| < |t| */
  w = t + t; /* t+t is exact */
  r = (r - t) / (w + r); /* r-t is exact; w+r ~= 3*t */
  t = t + t * r; /* error <= 0.5 + 0.5/3 + epsilon */
  return (t);
}
References v8::internal::B1, v8::internal::B2, EXTRACT_WORDS, GET_HIGH_WORD, INSERT_WORDS, SET_HIGH_WORD, and v8::internal::sign.
Referenced by v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::FloatUnary(), and v8::internal::compiler::MachineOperatorReducer::Reduce().
cos()
V8_BASE_EXPORT double v8::base::ieee754::cos (double x)
Definition at line 1354 of file ieee754.cc.
                     {
#endif
  double y[2], z = 0.0;
  int32_t n, ix;
  /* High word of x. */
  GET_HIGH_WORD(ix, x);
  /* |x| ~< pi/4 */
  ix &= 0x7FFFFFFF;
  if (ix <= 0x3FE921FB) {
    return __kernel_cos(x, z);
  } else if (ix >= 0x7FF00000) {
    /* cos(Inf or NaN) is NaN */
    return x - x;
  } else {
    /* argument reduction needed */
    n = __ieee754_rem_pio2(x, y);
    switch (n & 3) {
      case 0:
        return __kernel_cos(y[0], y[1]);
      case 1:
        return -__kernel_sin(y[0], y[1], 1);
      case 2:
        return -__kernel_cos(y[0], y[1]);
      default:
        return __kernel_sin(y[0], y[1], 1);
    }
  }
}
References v8::base::ieee754::anonymous_namespace{ieee754.cc}::__ieee754_rem_pio2(), v8::base::ieee754::anonymous_namespace{ieee754.cc}::__kernel_cos(), v8::base::ieee754::anonymous_namespace{ieee754.cc}::__kernel_sin(), GET_HIGH_WORD, and v8::base::internal::y.
Referenced by v8::internal::compiler::CodeGenerator::AssembleArchInstruction().
cosh()
V8_BASE_EXPORT double v8::base::ieee754::cosh (double x)
Definition at line 2554 of file ieee754.cc.
                      {
  static const double KCOSH_OVERFLOW = 710.4758600739439;
  static const double one = 1.0, half = 0.5;
  static volatile double huge = 1.0e+300;
  int32_t ix;
  /* High word of |x|. */
  GET_HIGH_WORD(ix, x);
  ix &= 0x7FFFFFFF;
  // |x| in [0,0.5*log2], return 1+expm1(|x|)^2/(2*exp(|x|))
  if (ix < 0x3FD62E43) {
    double t = expm1(fabs(x));
    double w = one + t;
    // For |x| < 2^-55, cosh(x) = 1
    if (ix < 0x3C800000) return w;
    return one + (t * t) / (w + w);
  }
  // |x| in [0.5*log2, 22], return (exp(|x|)+1/exp(|x|)/2
  if (ix < 0x40360000) {
    double t = exp(fabs(x));
    return half * t + half / t;
  }
  // |x| in [22, log(maxdouble)], return half*exp(|x|)
  if (ix < 0x40862E42) return half * exp(fabs(x));
  // |x| in [log(maxdouble), overflowthreshold]
  if (fabs(x) <= KCOSH_OVERFLOW) {
    double w = exp(half * fabs(x));
    double t = half * w;
    return t * w;
  }
  /* x is INF or NaN */
  if (ix >= 0x7FF00000) return x * x;
  // |x| > overflowthreshold.
  return huge * huge;
}
References exp(), expm1(), GET_HIGH_WORD, and one.
Referenced by v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::FloatUnary(), and v8::internal::compiler::MachineOperatorReducer::Reduce().
exp()
V8_BASE_EXPORT double v8::base::ieee754::exp (double x)
Definition at line 1447 of file ieee754.cc.
                     {
  static const double
      one = 1.0,
      halF[2] = {0.5, -0.5},
      o_threshold = 7.09782712893383973096e+02, /* 0x40862E42, 0xFEFA39EF */
      u_threshold = -7.45133219101941108420e+02, /* 0xC0874910, 0xD52D3051 */
      ln2HI[2] = {6.93147180369123816490e-01, /* 0x3FE62E42, 0xFEE00000 */
                  -6.93147180369123816490e-01}, /* 0xBFE62E42, 0xFEE00000 */
      ln2LO[2] = {1.90821492927058770002e-10, /* 0x3DEA39EF, 0x35793C76 */
                  -1.90821492927058770002e-10}, /* 0xBDEA39EF, 0x35793C76 */
      invln2 = 1.44269504088896338700e+00, /* 0x3FF71547, 0x652B82FE */
      P1 = 1.66666666666666019037e-01, /* 0x3FC55555, 0x5555553E */
      P2 = -2.77777777770155933842e-03, /* 0xBF66C16C, 0x16BEBD93 */
      P3 = 6.61375632143793436117e-05, /* 0x3F11566A, 0xAF25DE2C */
      P4 = -1.65339022054652515390e-06, /* 0xBEBBBD41, 0xC5D26BF1 */
      P5 = 4.13813679705723846039e-08, /* 0x3E663769, 0x72BEA4D0 */
      E = 2.718281828459045; /* 0x4005BF0A, 0x8B145769 */
  static volatile double
      huge = 1.0e+300,
      twom1000 = 9.33263618503218878990e-302, /* 2**-1000=0x01700000,0*/
      two1023 = 8.988465674311579539e307; /* 0x1p1023 */
  double y, hi = 0.0, lo = 0.0, c, t, twopk;
  int32_t k = 0, xsb;
  uint32_t hx;
  GET_HIGH_WORD(hx, x);
  xsb = (hx >> 31) & 1; /* sign bit of x */
  hx &= 0x7FFFFFFF; /* high word of |x| */
  /* filter out non-finite argument */
  if (hx >= 0x40862E42) { /* if |x|>=709.78... */
    if (hx >= 0x7FF00000) {
      uint32_t lx;
      GET_LOW_WORD(lx, x);
      if (((hx & 0xFFFFF) | lx) != 0)
        return x + x; /* NaN */
      else
        return (xsb == 0) ? x : 0.0; /* exp(+-inf)={inf,0} */
    }
    if (x > o_threshold) return huge * huge; /* overflow */
    if (x < u_threshold) return twom1000 * twom1000; /* underflow */
  }
  /* argument reduction */
  if (hx > 0x3FD62E42) { /* if |x| > 0.5 ln2 */
    if (hx < 0x3FF0A2B2) { /* and |x| < 1.5 ln2 */
      /* TODO(rtoy): We special case exp(1) here to return the correct
       * value of E, as the computation below would get the last bit
       * wrong. We should probably fix the algorithm instead.
       */
      if (x == 1.0) return E;
      hi = x - ln2HI[xsb];
      lo = ln2LO[xsb];
      k = 1 - xsb - xsb;
    } else {
      k = static_cast<int>(invln2 * x + halF[xsb]);
      t = k;
      hi = x - t * ln2HI[0]; /* t*ln2HI is exact here */
      lo = t * ln2LO[0];
    }
    x = hi - lo;
  } else if (hx < 0x3E300000) { /* when |x|<2**-28 */
    if (huge + x > one) return one + x; /* trigger inexact */
  } else {
    k = 0;
  }
  /* x is now in primary range */
  t = x * x;
  if (k >= -1021) {
    INSERT_WORDS(
        twopk,
        0x3FF00000 + static_cast<int32_t>(static_cast<uint32_t>(k) << 20), 0);
  } else {
    INSERT_WORDS(twopk, 0x3FF00000 + (static_cast<uint32_t>(k + 1000) << 20),
                 0);
  }
  c = x - t * (P1 + t * (P2 + t * (P3 + t * (P4 + t * P5))));
  if (k == 0) {
    return one - ((x * c) / (c - 2.0) - x);
  } else {
    y = one - ((lo - (x * c) / (2.0 - c)) - hi);
  }
  if (k >= -1021) {
    if (k == 1024) return y * 2.0 * two1023;
    return y * twopk;
  } else {
    return y * twopk * twom1000;
  }
}
References GET_HIGH_WORD, GET_LOW_WORD, v8::internal::hi, INSERT_WORDS, v8::internal::lo, one, and v8::base::internal::y.
Referenced by v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), cosh(), v8::internal::wasm::ModuleDecoderImpl::DecodeExportSection(), wasm::ExportsImpl(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::FloatUnary(), v8::internal::wasm::JSPrototypesSetup::GetExportedFunction(), v8::internal::wasm::GetExports(), v8::internal::Genesis::InitializeGlobal(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeClassDeclaration(), v8::internal::wasm::DescriptorsSectionIterator::Entry::NextExport(), v8::internal::ParserBase< Impl >::ParseStandardForLoop(), v8::internal::wasm::InstanceBuilder::ProcessExports(), v8::internal::compiler::MachineOperatorReducer::Reduce(), v8::internal::compiler::TypedOptimization::ReduceCheckEqualsInternalizedString(), v8::internal::compiler::TypedOptimization::ReduceCheckEqualsSymbol(), v8::internal::RUNTIME_FUNCTION(), v8::internal::SamplingHeapProfiler::ScaleSample(), and sinh().
expm1()
V8_BASE_EXPORT double v8::base::ieee754::expm1 (double x)
Definition at line 2213 of file ieee754.cc.
                       {
  static const double
      one = 1.0,
      tiny = 1.0e-300,
      o_threshold = 7.09782712893383973096e+02, /* 0x40862E42, 0xFEFA39EF */
      ln2_hi = 6.93147180369123816490e-01, /* 0x3FE62E42, 0xFEE00000 */
      ln2_lo = 1.90821492927058770002e-10, /* 0x3DEA39EF, 0x35793C76 */
      invln2 = 1.44269504088896338700e+00, /* 0x3FF71547, 0x652B82FE */
      /* Scaled Q's: Qn_here = 2**n * Qn_above, for R(2*z) where z = hxs =
         x*x/2: */
      Q1 = -3.33333333333331316428e-02, /* BFA11111 111110F4 */
      Q2 = 1.58730158725481460165e-03, /* 3F5A01A0 19FE5585 */
      Q3 = -7.93650757867487942473e-05, /* BF14CE19 9EAADBB7 */
      Q4 = 4.00821782732936239552e-06, /* 3ED0CFCA 86E65239 */
      Q5 = -2.01099218183624371326e-07; /* BE8AFDB7 6E09C32D */
  static volatile double huge = 1.0e+300;
  double y, hi, lo, c, t, e, hxs, hfx, r1, twopk;
  int32_t k, xsb;
  uint32_t hx;
  GET_HIGH_WORD(hx, x);
  xsb = hx & 0x80000000; /* sign bit of x */
  hx &= 0x7FFFFFFF; /* high word of |x| */
  /* filter out huge and non-finite argument */
  if (hx >= 0x4043687A) { /* if |x|>=56*ln2 */
    if (hx >= 0x40862E42) { /* if |x|>=709.78... */
      if (hx >= 0x7FF00000) {
        uint32_t low;
        GET_LOW_WORD(low, x);
        if (((hx & 0xFFFFF) | low) != 0)
          return x + x; /* NaN */
        else
          return (xsb == 0) ? x : -1.0; /* exp(+-inf)={inf,-1} */
      }
      if (x > o_threshold) return huge * huge; /* overflow */
    }
    if (xsb != 0) { /* x < -56*ln2, return -1.0 with inexact */
      if (x + tiny < 0.0) /* raise inexact */
        return tiny - one; /* return -1 */
    }
  }
  /* argument reduction */
  if (hx > 0x3FD62E42) { /* if |x| > 0.5 ln2 */
    if (hx < 0x3FF0A2B2) { /* and |x| < 1.5 ln2 */
      if (xsb == 0) {
        hi = x - ln2_hi;
        lo = ln2_lo;
        k = 1;
      } else {
        hi = x + ln2_hi;
        lo = -ln2_lo;
        k = -1;
      }
    } else {
      k = invln2 * x + ((xsb == 0) ? 0.5 : -0.5);
      t = k;
      hi = x - t * ln2_hi; /* t*ln2_hi is exact here */
      lo = t * ln2_lo;
    }
    x = hi - lo;
    c = (hi - x) - lo;
  } else if (hx < 0x3C900000) { /* when |x|<2**-54, return x */
    t = huge + x; /* return x with inexact flags when x!=0 */
    return x - (t - (huge + x));
  } else {
    k = 0;
  }
  /* x is now in primary range */
  hfx = 0.5 * x;
  hxs = x * hfx;
  r1 = one + hxs * (Q1 + hxs * (Q2 + hxs * (Q3 + hxs * (Q4 + hxs * Q5))));
  t = 3.0 - r1 * hfx;
  e = hxs * ((r1 - t) / (6.0 - x * t));
  if (k == 0) {
    return x - (x * e - hxs); /* c is 0 */
  } else {
    INSERT_WORDS(
        twopk,
        0x3FF00000 + static_cast<int32_t>(static_cast<uint32_t>(k) << 20),
        0); /* 2^k */
    e = (x * (e - c) - c);
    e -= hxs;
    if (k == -1) return 0.5 * (x - e) - 0.5;
    if (k == 1) {
      if (x < -0.25)
        return -2.0 * (e - (x + 0.5));
      else
        return one + 2.0 * (x - e);
    }
    if (k <= -2 || k > 56) { /* suffice to return exp(x)-1 */
      y = one - (e - x);
      // TODO(mvstanton): is this replacement for the hex float
      // sufficient?
      // if (k == 1024) y = y*2.0*0x1p1023;
      if (k == 1024)
        y = y * 2.0 * 8.98846567431158e+307;
      else
        y = y * twopk;
      return y - one;
    }
    t = one;
    if (k < 20) {
      SET_HIGH_WORD(t, 0x3FF00000 - (0x200000 >> k)); /* t=1-2^-k */
      y = t - (e - x);
      y = y * twopk;
    } else {
      SET_HIGH_WORD(t, ((0x3FF - k) << 20)); /* 2^-k */
      y = x - (e + t);
      y += one;
      y = y * twopk;
    }
  }
  return y;
}
References GET_HIGH_WORD, GET_LOW_WORD, v8::internal::hi, INSERT_WORDS, v8::internal::lo, one, SET_HIGH_WORD, and v8::base::internal::y.
Referenced by v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), cosh(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::FloatUnary(), v8::internal::compiler::MachineOperatorReducer::Reduce(), sinh(), and tanh().
k_log1p()
static double v8::base::ieee754::k_log1p (double f) [inline], [static]
Definition at line 1951 of file ieee754.cc.
                                       {
  double hfsq, s, z, R, w, t1, t2;
  s = f / (2.0 + f);
  z = s * s;
  w = z * z;
  t1 = w * (Lg2 + w * (Lg4 + w * Lg6));
  t2 = z * (Lg1 + w * (Lg3 + w * (Lg5 + w * Lg7)));
  R = t2 + t1;
  hfsq = 0.5 * f * f;
  return s * (hfsq + R);
}
References Lg1, Lg2, Lg3, Lg4, Lg5, Lg6, and Lg7.
Referenced by log2().
log()
V8_BASE_EXPORT double v8::base::ieee754::log (double x)
Definition at line 1638 of file ieee754.cc.
                     {
  static const double /* -- */
      ln2_hi = 6.93147180369123816490e-01, /* 3fe62e42 fee00000 */
      ln2_lo = 1.90821492927058770002e-10, /* 3dea39ef 35793c76 */
      two54 = 1.80143985094819840000e+16, /* 43500000 00000000 */
      Lg1 = 6.666666666666735130e-01, /* 3FE55555 55555593 */
      Lg2 = 3.999999999940941908e-01, /* 3FD99999 9997FA04 */
      Lg3 = 2.857142874366239149e-01, /* 3FD24924 94229359 */
      Lg4 = 2.222219843214978396e-01, /* 3FCC71C5 1D8E78AF */
      Lg5 = 1.818357216161805012e-01, /* 3FC74664 96CB03DE */
      Lg6 = 1.531383769920937332e-01, /* 3FC39A09 D078C69F */
      Lg7 = 1.479819860511658591e-01; /* 3FC2F112 DF3E5244 */
  static const double zero = 0.0;
  double hfsq, f, s, z, R, w, t1, t2, dk;
  int32_t k, hx, i, j;
  uint32_t lx;
  EXTRACT_WORDS(hx, lx, x);
  k = 0;
  if (hx < 0x00100000) { /* x < 2**-1022 */
    if (((hx & 0x7FFFFFFF) | lx) == 0) {
      return -std::numeric_limits<double>::infinity(); /* log(+-0)=-inf */
    }
    if (hx < 0) {
      return std::numeric_limits<double>::signaling_NaN(); /* log(-#) = NaN */
    }
    k -= 54;
    x *= two54; /* subnormal number, scale up x */
    GET_HIGH_WORD(hx, x);
  }
  if (hx >= 0x7FF00000) return x + x;
  k += (hx >> 20) - 1023;
  hx &= 0x000FFFFF;
  i = (hx + 0x95F64) & 0x100000;
  SET_HIGH_WORD(x, hx | (i ^ 0x3FF00000)); /* normalize x or x/2 */
  k += (i >> 20);
  f = x - 1.0;
  if ((0x000FFFFF & (2 + hx)) < 3) { /* -2**-20 <= f < 2**-20 */
    if (f == zero) {
      if (k == 0) {
        return zero;
      } else {
        dk = static_cast<double>(k);
        return dk * ln2_hi + dk * ln2_lo;
      }
    }
    R = f * f * (0.5 - 0.33333333333333333 * f);
    if (k == 0) {
      return f - R;
    } else {
      dk = static_cast<double>(k);
      return dk * ln2_hi - ((R - dk * ln2_lo) - f);
    }
  }
  s = f / (2.0 + f);
  dk = static_cast<double>(k);
  z = s * s;
  i = hx - 0x6147A;
  w = z * z;
  j = 0x6B851 - hx;
  t1 = w * (Lg2 + w * (Lg4 + w * Lg6));
  t2 = z * (Lg1 + w * (Lg3 + w * (Lg5 + w * Lg7)));
  i |= j;
  R = t2 + t1;
  if (i > 0) {
    hfsq = 0.5 * f * f;
    if (k == 0)
      return f - (hfsq - s * (hfsq + R));
    else
      return dk * ln2_hi - ((hfsq - (s * (hfsq + R) + dk * ln2_lo)) - f);
  } else {
    if (k == 0)
      return f - s * (f - R);
    else
      return dk * ln2_hi - ((s * (f - R) - dk * ln2_lo) - f);
  }
}
References EXTRACT_WORDS, GET_HIGH_WORD, v8::internal::anonymous_namespace{json-stringifier.cc}::i, Lg1, Lg2, Lg3, Lg4, Lg5, Lg6, Lg7, SET_HIGH_WORD, and v8::internal::zero.
Referenced by acosh(), asinh(), v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::FloatUnary(), v8::internal::SamplingHeapProfiler::Observer::GetNextSampleInterval(), v8::internal::Genesis::InitializeGlobal(), log10(), and v8::internal::compiler::MachineOperatorReducer::Reduce().
log10()
V8_BASE_EXPORT double v8::base::ieee754::log10 (double x)
Definition at line 2079 of file ieee754.cc.
                       {
  static const double
      two54 = 1.80143985094819840000e+16, /* 0x43500000, 0x00000000 */
      ivln10 = 4.34294481903251816668e-01,
      log10_2hi = 3.01029995663611771306e-01, /* 0x3FD34413, 0x509F6000 */
      log10_2lo = 3.69423907715893078616e-13; /* 0x3D59FEF3, 0x11F12B36 */
  double y;
  int32_t i, k, hx;
  uint32_t lx;
  EXTRACT_WORDS(hx, lx, x);
  k = 0;
  if (hx < 0x00100000) { /* x < 2**-1022 */
    if (((hx & 0x7FFFFFFF) | lx) == 0) {
      return -std::numeric_limits<double>::infinity(); /* log(+-0)=-inf */
    }
    if (hx < 0) {
      return std::numeric_limits<double>::quiet_NaN(); /* log(-#) = NaN */
    }
    k -= 54;
    x *= two54; /* subnormal number, scale up x */
    GET_HIGH_WORD(hx, x);
    GET_LOW_WORD(lx, x);
  }
  if (hx >= 0x7FF00000) return x + x;
  if (hx == 0x3FF00000 && lx == 0) return 0.0; /* log(1) = +0 */
  k += (hx >> 20) - 1023;
  i = (k & 0x80000000) >> 31;
  hx = (hx & 0x000FFFFF) | ((0x3FF - i) << 20);
  y = k + i;
  SET_HIGH_WORD(x, hx);
  SET_LOW_WORD(x, lx);
  double z = y * log10_2lo + ivln10 * log(x);
  return z + y * log10_2hi;
}
References EXTRACT_WORDS, GET_HIGH_WORD, GET_LOW_WORD, v8::internal::anonymous_namespace{json-stringifier.cc}::i, log(), SET_HIGH_WORD, and v8::base::internal::y.
Referenced by v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::FloatUnary(), v8::internal::Genesis::InitializeGlobal(), and v8::internal::compiler::MachineOperatorReducer::Reduce().
log1p()
V8_BASE_EXPORT double v8::base::ieee754::log1p (double x)
Definition at line 1783 of file ieee754.cc.
                       {
  static const double /* -- */
      ln2_hi = 6.93147180369123816490e-01, /* 3fe62e42 fee00000 */
      ln2_lo = 1.90821492927058770002e-10, /* 3dea39ef 35793c76 */
      two54 = 1.80143985094819840000e+16, /* 43500000 00000000 */
      Lp1 = 6.666666666666735130e-01, /* 3FE55555 55555593 */
      Lp2 = 3.999999999940941908e-01, /* 3FD99999 9997FA04 */
      Lp3 = 2.857142874366239149e-01, /* 3FD24924 94229359 */
      Lp4 = 2.222219843214978396e-01, /* 3FCC71C5 1D8E78AF */
      Lp5 = 1.818357216161805012e-01, /* 3FC74664 96CB03DE */
      Lp6 = 1.531383769920937332e-01, /* 3FC39A09 D078C69F */
      Lp7 = 1.479819860511658591e-01; /* 3FC2F112 DF3E5244 */
  static const double zero = 0.0;
  double hfsq, f, c, s, z, R, u;
  int32_t k, hx, hu, ax;
  GET_HIGH_WORD(hx, x);
  ax = hx & 0x7FFFFFFF;
  k = 1;
  if (hx < 0x3FDA827A) { /* 1+x < sqrt(2)+ */
    if (ax >= 0x3FF00000) { /* x <= -1.0 */
      if (x == -1.0)
        return -std::numeric_limits<double>::infinity(); /* log1p(-1)=+inf */
      else
        return std::numeric_limits<double>::signaling_NaN(); // log1p(x<-1)=NaN
    }
    if (ax < 0x3E200000) { /* |x| < 2**-29 */
      if (two54 + x > zero /* raise inexact */
          && ax < 0x3C900000) /* |x| < 2**-54 */
        return x;
      else
        return x - x * x * 0.5;
    }
    if (hx > 0 || hx <= static_cast<int32_t>(0xBFD2BEC4)) {
      k = 0;
      f = x;
      hu = 1;
    } /* sqrt(2)/2- <= 1+x < sqrt(2)+ */
  }
  if (hx >= 0x7FF00000) return x + x;
  if (k != 0) {
    if (hx < 0x43400000) {
      u = 1.0 + x;
      GET_HIGH_WORD(hu, u);
      k = (hu >> 20) - 1023;
      c = (k > 0) ? 1.0 - (u - x) : x - (u - 1.0); /* correction term */
      c /= u;
    } else {
      u = x;
      GET_HIGH_WORD(hu, u);
      k = (hu >> 20) - 1023;
      c = 0;
    }
    hu &= 0x000FFFFF;
    /*
     * The approximation to sqrt(2) used in thresholds is not
     * critical. However, the ones used above must give less
     * strict bounds than the one here so that the k==0 case is
     * never reached from here, since here we have committed to
     * using the correction term but don't use it if k==0.
     */
    if (hu < 0x6A09E) { /* u ~< sqrt(2) */
      SET_HIGH_WORD(u, hu | 0x3FF00000); /* normalize u */
    } else {
      k += 1;
      SET_HIGH_WORD(u, hu | 0x3FE00000); /* normalize u/2 */
      hu = (0x00100000 - hu) >> 2;
    }
    f = u - 1.0;
  }
  hfsq = 0.5 * f * f;
  if (hu == 0) { /* |f| < 2**-20 */
    if (f == zero) {
      if (k == 0) {
        return zero;
      } else {
        c += k * ln2_lo;
        return k * ln2_hi + c;
      }
    }
    R = hfsq * (1.0 - 0.66666666666666666 * f);
    if (k == 0)
      return f - R;
    else
      return k * ln2_hi - ((R - (k * ln2_lo + c)) - f);
  }
  s = f / (2.0 + f);
  z = s * s;
  R = z * (Lp1 +
           z * (Lp2 + z * (Lp3 + z * (Lp4 + z * (Lp5 + z * (Lp6 + z * Lp7))))));
  if (k == 0)
    return f - (hfsq - s * (hfsq + R));
  else
    return k * ln2_hi - ((hfsq - (s * (hfsq + R) + (k * ln2_lo + c))) - f);
}
References GET_HIGH_WORD, SET_HIGH_WORD, and v8::internal::zero.
Referenced by acosh(), asinh(), v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), atanh(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::FloatUnary(), and v8::internal::compiler::MachineOperatorReducer::Reduce().
log2()
V8_BASE_EXPORT double v8::base::ieee754::log2 (double x)
Definition at line 1973 of file ieee754.cc.
                      {
  static const double
      two54 = 1.80143985094819840000e+16, /* 0x43500000, 0x00000000 */
      ivln2hi = 1.44269504072144627571e+00, /* 0x3FF71547, 0x65200000 */
      ivln2lo = 1.67517131648865118353e-10; /* 0x3DE705FC, 0x2EEFA200 */
  double f, hfsq, hi, lo, r, val_hi, val_lo, w, y;
  int32_t i, k, hx;
  uint32_t lx;
  EXTRACT_WORDS(hx, lx, x);
  k = 0;
  if (hx < 0x00100000) { /* x < 2**-1022 */
    if (((hx & 0x7FFFFFFF) | lx) == 0) {
      return -std::numeric_limits<double>::infinity(); /* log(+-0)=-inf */
    }
    if (hx < 0) {
      return std::numeric_limits<double>::signaling_NaN(); /* log(-#) = NaN */
    }
    k -= 54;
    x *= two54; /* subnormal number, scale up x */
    GET_HIGH_WORD(hx, x);
  }
  if (hx >= 0x7FF00000) return x + x;
  if (hx == 0x3FF00000 && lx == 0) return 0.0; /* log(1) = +0 */
  k += (hx >> 20) - 1023;
  hx &= 0x000FFFFF;
  i = (hx + 0x95F64) & 0x100000;
  SET_HIGH_WORD(x, hx | (i ^ 0x3FF00000)); /* normalize x or x/2 */
  k += (i >> 20);
  y = static_cast<double>(k);
  f = x - 1.0;
  hfsq = 0.5 * f * f;
  r = k_log1p(f);
  /*
   * f-hfsq must (for args near 1) be evaluated in extra precision
   * to avoid a large cancellation when x is near sqrt(2) or 1/sqrt(2).
   * This is fairly efficient since f-hfsq only depends on f, so can
   * be evaluated in parallel with R. Not combining hfsq with R also
   * keeps R small (though not as small as a true `lo' term would be),
   * so that extra precision is not needed for terms involving R.
   *
   * Compiler bugs involving extra precision used to break Dekker's
   * theorem for spitting f-hfsq as hi+lo, unless double_t was used
   * or the multi-precision calculations were avoided when double_t
   * has extra precision. These problems are now automatically
   * avoided as a side effect of the optimization of combining the
   * Dekker splitting step with the clear-low-bits step.
   *
   * y must (for args near sqrt(2) and 1/sqrt(2)) be added in extra
   * precision to avoid a very large cancellation when x is very near
   * these values. Unlike the above cancellations, this problem is
   * specific to base 2. It is strange that adding +-1 is so much
   * harder than adding +-ln2 or +-log10_2.
   *
   * This uses Dekker's theorem to normalize y+val_hi, so the
   * compiler bugs are back in some configurations, sigh. And I
   * don't want to used double_t to avoid them, since that gives a
   * pessimization and the support for avoiding the pessimization
   * is not yet available.
   *
   * The multi-precision calculations for the multiplications are
   * routine.
   */
  hi = f - hfsq;
  SET_LOW_WORD(hi, 0);
  lo = (f - hi) - hfsq + r;
  val_hi = hi * ivln2hi;
  val_lo = (lo + hi) * ivln2lo + lo * ivln2hi;
  /* spadd(val_hi, val_lo, y), except for not using double_t: */
  w = y + val_hi;
  val_lo += (y - w) + val_hi;
  val_hi = w;
  return val_lo + val_hi;
}
References EXTRACT_WORDS, GET_HIGH_WORD, v8::internal::hi, v8::internal::anonymous_namespace{json-stringifier.cc}::i, k_log1p(), v8::internal::lo, SET_HIGH_WORD, and v8::base::internal::y.
Referenced by v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::FloatUnary(), v8::internal::Genesis::InitializeGlobal(), v8::internal::compiler::MachineOperatorReducer::Reduce(), and v8::internal::StaticRootsTableGen::write().
sin()
V8_BASE_EXPORT double v8::base::ieee754::sin (double x)
Definition at line 2450 of file ieee754.cc.
                     {
#endif
  double y[2], z = 0.0;
  int32_t n, ix;
  /* High word of x. */
  GET_HIGH_WORD(ix, x);
  /* |x| ~< pi/4 */
  ix &= 0x7FFFFFFF;
  if (ix <= 0x3FE921FB) {
    return __kernel_sin(x, z, 0);
  } else if (ix >= 0x7FF00000) {
    /* sin(Inf or NaN) is NaN */
    return x - x;
  } else {
    /* argument reduction needed */
    n = __ieee754_rem_pio2(x, y);
    switch (n & 3) {
      case 0:
        return __kernel_sin(y[0], y[1], 1);
      case 1:
        return __kernel_cos(y[0], y[1]);
      case 2:
        return -__kernel_sin(y[0], y[1], 1);
      default:
        return -__kernel_cos(y[0], y[1]);
    }
  }
}
References v8::base::ieee754::anonymous_namespace{ieee754.cc}::__ieee754_rem_pio2(), v8::base::ieee754::anonymous_namespace{ieee754.cc}::__kernel_cos(), v8::base::ieee754::anonymous_namespace{ieee754.cc}::__kernel_sin(), GET_HIGH_WORD, and v8::base::internal::y.
Referenced by v8::internal::compiler::CodeGenerator::AssembleArchInstruction().
sinh()
V8_BASE_EXPORT double v8::base::ieee754::sinh (double x)
Definition at line 2930 of file ieee754.cc.
                      {
  static const double KSINH_OVERFLOW = 710.4758600739439,
                      TWO_M28 =
                          3.725290298461914e-9, // 2^-28, empty lower half
      LOG_MAXD = 709.7822265625; // 0x40862E42 00000000, empty lower half
  static const double shuge = 1.0e307;
  double h = (x < 0) ? -0.5 : 0.5;
  // |x| in [0, 22]. return sign(x)*0.5*(E+E/(E+1))
  double ax = fabs(x);
  if (ax < 22) {
    // For |x| < 2^-28, sinh(x) = x
    if (ax < TWO_M28) return x;
    double t = expm1(ax);
    if (ax < 1) {
      return h * (2 * t - t * t / (t + 1));
    }
    return h * (t + t / (t + 1));
  }
  // |x| in [22, log(maxdouble)], return 0.5 * exp(|x|)
  if (ax < LOG_MAXD) return h * exp(ax);
  // |x| in [log(maxdouble), overflowthreshold]
  // overflowthreshold = 710.4758600739426
  if (ax <= KSINH_OVERFLOW) {
    double w = exp(0.5 * ax);
    double t = h * w;
    return t * w;
  }
  // |x| > overflowthreshold or is NaN.
  // Return Infinity of the appropriate sign or NaN.
  return x * shuge;
}
References exp(), expm1(), and h().
Referenced by v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::FloatUnary(), and v8::internal::compiler::MachineOperatorReducer::Reduce().
tan()
V8_BASE_EXPORT double v8::base::ieee754::tan (double x)
Definition at line 2510 of file ieee754.cc.
                     {
  double y[2], z = 0.0;
  int32_t n, ix;
  /* High word of x. */
  GET_HIGH_WORD(ix, x);
  /* |x| ~< pi/4 */
  ix &= 0x7FFFFFFF;
  if (ix <= 0x3FE921FB) {
    return __kernel_tan(x, z, 1);
  } else if (ix >= 0x7FF00000) {
    /* tan(Inf or NaN) is NaN */
    return x - x; /* NaN */
  } else {
    /* argument reduction needed */
    n = __ieee754_rem_pio2(x, y);
    /* 1 -> n even, -1 -> n odd */
    return __kernel_tan(y[0], y[1], 1 - ((n & 1) << 1));
  }
}
References v8::base::ieee754::anonymous_namespace{ieee754.cc}::__ieee754_rem_pio2(), v8::base::ieee754::anonymous_namespace{ieee754.cc}::__kernel_tan(), GET_HIGH_WORD, and v8::base::internal::y.
Referenced by v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::FloatUnary(), and v8::internal::compiler::MachineOperatorReducer::Reduce().
tanh()
V8_BASE_EXPORT double v8::base::ieee754::tanh (double x)
Definition at line 2986 of file ieee754.cc.
                      {
  static const volatile double tiny = 1.0e-300;
  static const double one = 1.0, two = 2.0, huge = 1.0e300;
  double t, z;
  int32_t jx, ix;
  GET_HIGH_WORD(jx, x);
  ix = jx & 0x7FFFFFFF;
  /* x is INF or NaN */
  if (ix >= 0x7FF00000) {
    if (jx >= 0)
      return one / x + one; /* tanh(+-inf)=+-1 */
    else
      return one / x - one; /* tanh(NaN) = NaN */
  }
  /* |x| < 22 */
  if (ix < 0x40360000) { /* |x|<22 */
    if (ix < 0x3E300000) { /* |x|<2**-28 */
      if (huge + x > one) return x; /* tanh(tiny) = tiny with inexact */
    }
    if (ix >= 0x3FF00000) { /* |x|>=1 */
      t = expm1(two * fabs(x));
      z = one - two / (t + two);
    } else {
      t = expm1(-two * fabs(x));
      z = -t / (t + two);
    }
    /* |x| >= 22, return +-1 */
  } else {
    z = one - tiny; /* raise inexact flag */
  }
  return (jx >= 0) ? z : -z;
}
References expm1(), GET_HIGH_WORD, and one.
Referenced by v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::FloatUnary(), and v8::internal::compiler::MachineOperatorReducer::Reduce().
Variable Documentation
Lg1
const double v8::base::ieee754::Lg1 = 6.666666666666735130e-01 [static]
Definition at line 1939 of file ieee754.cc.
Referenced by k_log1p(), and log().
Lg2
const double v8::base::ieee754::Lg2 = 3.999999999940941908e-01 [static]
Definition at line 1940 of file ieee754.cc.
Referenced by k_log1p(), and log().
Lg3
const double v8::base::ieee754::Lg3 = 2.857142874366239149e-01 [static]
Definition at line 1941 of file ieee754.cc.
Referenced by k_log1p(), and log().
Lg4
const double v8::base::ieee754::Lg4 = 2.222219843214978396e-01 [static]
Definition at line 1942 of file ieee754.cc.
Referenced by k_log1p(), and log().
Lg5
const double v8::base::ieee754::Lg5 = 1.818357216161805012e-01 [static]
Definition at line 1943 of file ieee754.cc.
Referenced by k_log1p(), and log().
Lg6
const double v8::base::ieee754::Lg6 = 1.531383769920937332e-01 [static]
Definition at line 1944 of file ieee754.cc.
Referenced by k_log1p(), and log().
Lg7
const double v8::base::ieee754::Lg7 = 1.479819860511658591e-01 [static]
Definition at line 1945 of file ieee754.cc.
Referenced by k_log1p(), and log().