cppgc::internal Namespace Reference
Implementation details of cppgc.
Namespaces
 anonymous_namespace{caged-heap.cc}
 anonymous_namespace{compactor.cc}
 anonymous_namespace{concurrent-marker.cc}
 anonymous_namespace{explicit-management.cc}
 anonymous_namespace{free-list.cc}
 anonymous_namespace{gc-info-table.cc}
 anonymous_namespace{gc-info.cc}
 anonymous_namespace{heap-base.cc}
 anonymous_namespace{heap-growing.cc}
 anonymous_namespace{heap-page.cc}
 anonymous_namespace{heap-statistics-collector.cc}
 anonymous_namespace{heap.cc}
 anonymous_namespace{marker.cc}
 anonymous_namespace{marking-verifier.cc}
 anonymous_namespace{object-allocator.cc}
 anonymous_namespace{page-memory.cc}
 anonymous_namespace{platform.cc}
 anonymous_namespace{pointer-policies.cc}
 anonymous_namespace{process-heap.cc}
 anonymous_namespace{stats-collector.cc}
 anonymous_namespace{sweeper.cc}
 api_constants
 testing
Classes
class CagedHeap
class CompactionWorklists
class Compactor
class ConcurrentMarkerBase
class ConcurrentMarker
class Filler
class FreeList
class GarbageCollector
struct GCInfo
class GCInfoTable
class GlobalGCInfoTable
class GCInvoker
class MoveListener
class HeapBase
class ClassNameAsHeapObjectNameScope
struct MarkingConfig
struct SweepingConfig
struct GCConfig
class HeapGrowing
class HeapObjectHeader
class BasePage
class NormalPage
class LargePage
class BaseSpace
class NormalPageSpace
class LargePageSpace
class HeapStatisticsCollector
class HeapVisitor
class Heap
class LivenessBrokerFactory
class WeakCallbackJobTask
class MarkerBase
class Marker
class MarkingStateBase
class BasicMarkingState
class MutatorMarkingState
class ConcurrentMarkingState
class VerificationState
class MarkingVerifierBase
class MarkingVerifier
class MarkingVisitorBase
class MutatorMarkingVisitor
class ConcurrentMarkingVisitor
class RootMarkingVisitor
class ConservativeMarkingVisitor
class MarkingWorklists
class MemberDebugHelper
class MetricRecorder
Base class used for reporting GC statistics histograms.
class ObjectAllocator
class ObjectStartBitmap
class PlatformAwareObjectStartBitmap
class ObjectView
class MemoryRegion
class PageMemoryRegion
class PageMemoryRegionTree
class NormalPageMemoryPool
class PageBackend
class FatalOutOfMemoryHandler
struct PreFinalizer
class PreFinalizerHandler
class ProcessHeapStatisticsUpdater
class ProcessGlobalLock
class HeapRegistry
class RawHeap
class StatsCollector
class Sweeper
struct SingleThreadedHandle
class SequentialUnmarker
class VirtualMemory
class VisitorFactory
class VisitorBase
class RootVisitorBase
class ConservativeTracingVisitor
class MakeGarbageCollectedTraitInternal
class CrossThreadPersistentBase
class BasicCrossThreadPersistent
struct IsWeak< BasicCrossThreadPersistent< T, internal::WeakCrossThreadPersistentPolicy, LocationPolicy, CheckingPolicy > >
struct IsAllocatedOnCompactableSpaceImpl
struct IsAllocatedOnCompactableSpaceImpl< void >
struct IsAllocatedOnCompactableSpace
class ExplicitManagementImpl
class AtomicEntryFlag
class BasePageHandle
class ConditionalStackAllocatedBase
struct HasFinalizeGarbageCollectedObject
struct HasFinalizeGarbageCollectedObject< T, std::void_t< decltype(std::declval< T >().FinalizeGarbageCollectedObject())> >
struct FinalizerTraitImpl
struct FinalizerTraitImpl< T, true >
struct FinalizerTraitImpl< T, false >
struct FinalizerTrait
struct EnsureGCInfoIndexTrait
struct GCInfoFolding
struct EatParams
class RawPointer
struct HeapObjectName
class NameTraitBase
class NameTrait
class PersistentNode
class PersistentRegionBase
class PersistentRegion
class PersistentRegionLock
class CrossThreadPersistentRegion
struct DijkstraWriteBarrierPolicy
struct NoWriteBarrierPolicy
class SameThreadEnabledCheckingPolicyBase
class SameThreadEnabledCheckingPolicy
class DisabledCheckingPolicy
class KeepLocationPolicy
class IgnoreLocationPolicy
struct StrongPersistentPolicy
struct WeakPersistentPolicy
struct StrongCrossThreadPersistentPolicy
struct WeakCrossThreadPersistentPolicy
class BasicPersistent
class BasicMember
class WriteBarrier
class WriteBarrierTypeForNonCagedHeapPolicy
class MemberBase
struct IsWeak< BasicMember< T, WeakMemberTag, WriteBarrierPolicy, CheckingPolicy, StorageType > >
struct BaseObjectSizeTrait
class PersistentBase
struct IsWeak< BasicPersistent< T, internal::WeakPersistentPolicy, LocationPolicy, CheckingPolicy > >
class PrefinalizerRegistration
struct SentinelPointer
struct TraceTraitImpl
struct TraceTraitFromInnerAddressImpl
struct TraceTraitBase
Trait specifying how the garbage collector processes an object of type T.
struct TraceTraitImpl< T, false >
struct TraceTraitImpl< T, true >
struct IsWeak
struct IsTraceMethodConst
struct IsTraceMethodConst< T, std::void_t< decltype(std::declval< const T >().Trace(std::declval< Visitor * >()))> >
struct IsTraceable
struct IsTraceable< T, std::void_t< decltype(std::declval< T >().Trace(std::declval< Visitor * >()))> >
struct HasGarbageCollectedMixinTypeMarker
struct HasGarbageCollectedMixinTypeMarker< T, std::void_t< typename std::remove_const_t< T >::IsGarbageCollectedMixinTypeMarker > >
struct HasGarbageCollectedTypeMarker
struct HasGarbageCollectedTypeMarker< T, std::void_t< typename std::remove_const_t< T >::IsGarbageCollectedTypeMarker > >
struct IsGarbageCollectedMixinType
struct IsGarbageCollectedMixinType< T, false, true >
struct IsGarbageCollectedType
struct IsGarbageCollectedType< T, true >
struct IsGarbageCollectedOrMixinType
struct IsGarbageCollectedWithMixinType
struct IsGarbageCollectedWithMixinType< T, true >
struct IsSubclassOfBasicMemberTemplate
struct IsMemberType
struct IsMemberType< T, true >
struct IsWeakMemberType
struct IsWeakMemberType< T, true >
struct IsUntracedMemberType
struct IsUntracedMemberType< T, true >
struct IsComplete
class RootVisitor
Typedefs
using Address = uint8_t *
using ConstAddress = const uint8_t *
using StackState = cppgc::Heap::StackState
using PointerRepresentation = RawPointer
using AlignVal = std::align_val_t
using FinalizationCallback = void(*)(void *)
using GCInfoIndex = uint16_t
using DefaultMemberStorage = RawPointer
using NameCallback = HeapObjectName(*)(const void *, HeapObjectNameForUnnamedObject)
using DefaultMemberCheckingPolicy = DisabledCheckingPolicy
using DefaultPersistentCheckingPolicy = DisabledCheckingPolicy
using DefaultCrossThreadPersistentCheckingPolicy = DisabledCheckingPolicy
using DefaultLocationPolicy = IgnoreLocationPolicy
using TraceRootCallback = void(*)(RootVisitor &, const void *object)
Enumerations
enum class AccessMode : uint8_t { kNonAtomic
, kAtomic
 }
enum class StickyBits : uint8_t { kDisabled
, kEnabled
 }
enum class CollectionType : uint8_t { kMinor
, kMajor
 }
enum class FreeMemoryHandling : uint8_t { kDoNotDiscard
, kDiscardWherePossible
 }
enum class WriteBarrierSlotType { kCompressed
, kUncompressed
 }
enum class HeapObjectNameForUnnamedObject : uint8_t { kUseClassNameIfSupported
, kUseHiddenName
 }
Functions
template<AccessMode mode = AccessMode::kNonAtomic>
const HeapObjectHeader * ObjectHeaderFromInnerAddressImpl (const BasePage *page, const void *address)
void DCheckImpl (const char *message, const SourceLocation &loc)
void FatalImpl (const char *message, const SourceLocation &loc)
template<size_t kDeadlineCheckInterval, typename Predicate , typename CreateStatsScopeCallback , typename WorklistLocal , typename ProcessWorklistItemCallback >
bool DrainWorklistWithPredicate (Predicate ShouldYield, CreateStatsScopeCallback CreateStatsScope, WorklistLocal &worklist_local, ProcessWorklistItemCallback ProcessWorklistItem)
template<AccessMode mode>
void DynamicallyTraceMarkedObject (Visitor &visitor, const HeapObjectHeader &header)
V8_DEBUGGING_EXPORT C void * _cppgc_internal_Uncompress_Member (void *m)
void NoSanitizeMemset (void *address, char c, size_t bytes)
void ZapMemory (void *address, size_t size)
void CheckMemoryIsZapped (const void *address, size_t size)
void CheckMemoryIsZero (const void *address, size_t size)
void SetMemoryAccessible (void *address, size_t size)
void CheckMemoryIsInaccessible (const void *address, size_t size)
constexpr bool CheckMemoryIsInaccessibleIsNoop ()
void SetMemoryInaccessible (void *address, size_t size)
void Fatal (const std::string &reason, const SourceLocation &loc)
FatalOutOfMemoryHandler & GetGlobalOOMHandler ()
PageAllocator & GetGlobalPageAllocator ()
template<typename T >
requires (RequiresStackAllocated< T >) class ConditionalStackAllocatedBase< T >
template<typename T >
requires (!RequiresStackAllocated< T >) class ConditionalStackAllocatedBase< T >
DISPATCH (true, true, EnsureGCInfoIndex(registered_index, TraceTrait< T >::Trace, FinalizerTrait< T >::kCallback, NameTrait< T >::GetName)) DISPATCH(true
EnsureGCInfoIndex (registered_index, TraceTrait< T >::Trace, FinalizerTrait< T >::kCallback)) DISPATCH(false
EnsureGCInfoIndex (registered_index, TraceTrait< T >::Trace, NameTrait< T >::GetName)) DISPATCH(false
EnsureGCInfoIndex (registered_index, TraceTrait< T >::Trace)) template< typename T > struct GCInfoTrait final
template<WriteBarrier::Type type>
WriteBarrier::Type SetAndReturnType (WriteBarrier::Params &params)
template<typename T1 , typename WeaknessTag1 , typename WriteBarrierPolicy1 , typename CheckingPolicy1 , typename T2 , typename WeaknessTag2 , typename WriteBarrierPolicy2 , typename CheckingPolicy2 , typename StorageType >
bool operator== (const BasicMember< T1, WeaknessTag1, WriteBarrierPolicy1, CheckingPolicy1, StorageType > &member1, const BasicMember< T2, WeaknessTag2, WriteBarrierPolicy2, CheckingPolicy2, StorageType > &member2)
template<typename T1 , typename WeaknessTag1 , typename WriteBarrierPolicy1 , typename CheckingPolicy1 , typename T2 , typename WeaknessTag2 , typename WriteBarrierPolicy2 , typename CheckingPolicy2 , typename StorageType >
bool operator!= (const BasicMember< T1, WeaknessTag1, WriteBarrierPolicy1, CheckingPolicy1, StorageType > &member1, const BasicMember< T2, WeaknessTag2, WriteBarrierPolicy2, CheckingPolicy2, StorageType > &member2)
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType , typename U >
bool operator== (const BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType > &member, U *raw)
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType , typename U >
bool operator!= (const BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType > &member, U *raw)
template<typename T , typename U , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
bool operator== (T *raw, const BasicMember< U, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType > &member)
template<typename T , typename U , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
bool operator!= (T *raw, const BasicMember< U, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType > &member)
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
bool operator== (const BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType > &member, SentinelPointer)
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
bool operator!= (const BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType > &member, SentinelPointer s)
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
bool operator== (SentinelPointer s, const BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType > &member)
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
bool operator!= (SentinelPointer s, const BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType > &member)
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
bool operator== (const BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType > &member, std::nullptr_t)
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
bool operator!= (const BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType > &member, std::nullptr_t n)
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
bool operator== (std::nullptr_t n, const BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType > &member)
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
bool operator!= (std::nullptr_t n, const BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType > &member)
template<typename T1 , typename WeaknessTag1 , typename WriteBarrierPolicy1 , typename CheckingPolicy1 , typename T2 , typename WeaknessTag2 , typename WriteBarrierPolicy2 , typename CheckingPolicy2 , typename StorageType >
bool operator< (const BasicMember< T1, WeaknessTag1, WriteBarrierPolicy1, CheckingPolicy1, StorageType > &member1, const BasicMember< T2, WeaknessTag2, WriteBarrierPolicy2, CheckingPolicy2, StorageType > &member2)
template<typename T1 , typename WeaknessTag1 , typename WriteBarrierPolicy1 , typename CheckingPolicy1 , typename T2 , typename WeaknessTag2 , typename WriteBarrierPolicy2 , typename CheckingPolicy2 , typename StorageType >
bool operator<= (const BasicMember< T1, WeaknessTag1, WriteBarrierPolicy1, CheckingPolicy1, StorageType > &member1, const BasicMember< T2, WeaknessTag2, WriteBarrierPolicy2, CheckingPolicy2, StorageType > &member2)
template<typename T1 , typename WeaknessTag1 , typename WriteBarrierPolicy1 , typename CheckingPolicy1 , typename T2 , typename WeaknessTag2 , typename WriteBarrierPolicy2 , typename CheckingPolicy2 , typename StorageType >
bool operator> (const BasicMember< T1, WeaknessTag1, WriteBarrierPolicy1, CheckingPolicy1, StorageType > &member1, const BasicMember< T2, WeaknessTag2, WriteBarrierPolicy2, CheckingPolicy2, StorageType > &member2)
template<typename T1 , typename WeaknessTag1 , typename WriteBarrierPolicy1 , typename CheckingPolicy1 , typename T2 , typename WeaknessTag2 , typename WriteBarrierPolicy2 , typename CheckingPolicy2 , typename StorageType >
bool operator>= (const BasicMember< T1, WeaknessTag1, WriteBarrierPolicy1, CheckingPolicy1, StorageType > &member1, const BasicMember< T2, WeaknessTag2, WriteBarrierPolicy2, CheckingPolicy2, StorageType > &member2)
template<typename T1 , typename WeaknessPolicy1 , typename LocationPolicy1 , typename CheckingPolicy1 , typename T2 , typename WeaknessPolicy2 , typename LocationPolicy2 , typename CheckingPolicy2 >
bool operator== (const BasicPersistent< T1, WeaknessPolicy1, LocationPolicy1, CheckingPolicy1 > &p1, const BasicPersistent< T2, WeaknessPolicy2, LocationPolicy2, CheckingPolicy2 > &p2)
template<typename T1 , typename WeaknessPolicy1 , typename LocationPolicy1 , typename CheckingPolicy1 , typename T2 , typename WeaknessPolicy2 , typename LocationPolicy2 , typename CheckingPolicy2 >
bool operator!= (const BasicPersistent< T1, WeaknessPolicy1, LocationPolicy1, CheckingPolicy1 > &p1, const BasicPersistent< T2, WeaknessPolicy2, LocationPolicy2, CheckingPolicy2 > &p2)
template<typename T1 , typename PersistentWeaknessPolicy , typename PersistentLocationPolicy , typename PersistentCheckingPolicy , typename T2 , typename MemberWriteBarrierPolicy , typename MemberWeaknessTag , typename MemberCheckingPolicy , typename MemberStorageType >
bool operator== (const BasicPersistent< T1, PersistentWeaknessPolicy, PersistentLocationPolicy, PersistentCheckingPolicy > &p, const BasicMember< T2, MemberWeaknessTag, MemberWriteBarrierPolicy, MemberCheckingPolicy, MemberStorageType > &m)
template<typename T1 , typename PersistentWeaknessPolicy , typename PersistentLocationPolicy , typename PersistentCheckingPolicy , typename T2 , typename MemberWriteBarrierPolicy , typename MemberWeaknessTag , typename MemberCheckingPolicy , typename MemberStorageType >
bool operator!= (const BasicPersistent< T1, PersistentWeaknessPolicy, PersistentLocationPolicy, PersistentCheckingPolicy > &p, const BasicMember< T2, MemberWeaknessTag, MemberWriteBarrierPolicy, MemberCheckingPolicy, MemberStorageType > &m)
template<typename T1 , typename MemberWriteBarrierPolicy , typename MemberWeaknessTag , typename MemberCheckingPolicy , typename MemberStorageType , typename T2 , typename PersistentWeaknessPolicy , typename PersistentLocationPolicy , typename PersistentCheckingPolicy >
bool operator== (const BasicMember< T2, MemberWeaknessTag, MemberWriteBarrierPolicy, MemberCheckingPolicy, MemberStorageType > &m, const BasicPersistent< T1, PersistentWeaknessPolicy, PersistentLocationPolicy, PersistentCheckingPolicy > &p)
template<typename T1 , typename MemberWriteBarrierPolicy , typename MemberWeaknessTag , typename MemberCheckingPolicy , typename MemberStorageType , typename T2 , typename PersistentWeaknessPolicy , typename PersistentLocationPolicy , typename PersistentCheckingPolicy >
bool operator!= (const BasicMember< T2, MemberWeaknessTag, MemberWriteBarrierPolicy, MemberCheckingPolicy, MemberStorageType > &m, const BasicPersistent< T1, PersistentWeaknessPolicy, PersistentLocationPolicy, PersistentCheckingPolicy > &p)
Variables
constexpr size_t kKB = 1024
constexpr size_t kMB = kKB * 1024
constexpr size_t kGB = kMB * 1024
constexpr size_t kAllocationGranularity = 4
constexpr size_t kAllocationMask = kAllocationGranularity - 1
constexpr size_t kPageSizeLog2 = 17
constexpr size_t kPageSize = 1 << kPageSizeLog2
constexpr size_t kPageOffsetMask = kPageSize - 1
constexpr size_t kPageBaseMask = ~kPageOffsetMask
constexpr size_t kLargeObjectSizeThreshold = kPageSize / 2
constexpr GCInfoIndex kFreeListGCInfoIndex = 0
constexpr size_t kFreeListEntrySize = 2 * sizeof(uintptr_t)
constexpr size_t kSlotSize = sizeof(uintptr_t)
static constexpr uint8_t kZappedValue = 0xdc
template<typename T >
concept RequiresStackAllocated
false
true
static constexpr size_t kSizeOfMember = sizeof(Member<Dummy>)
static constexpr size_t kSizeOfUncompressedMember
template<typename T >
constexpr bool IsTraceableV = IsTraceable<T>::value
template<typename T , typename U >
constexpr bool IsDecayedSameV
template<typename B , typename D >
constexpr bool IsStrictlyBaseOfV
template<typename T >
constexpr bool IsAnyMemberTypeV = false
Detailed Description
Implementation details of cppgc.
Those details are considered internal and may change at any point in time without notice. Users should never rely on the contents of this namespace.
Typedef Documentation
Address
using cppgc::internal::Address = typedef uint8_t*
Definition at line 17 of file globals.h.
AlignVal
using cppgc::internal::AlignVal = typedef std::align_val_t
Definition at line 47 of file allocation.h.
ConstAddress
using cppgc::internal::ConstAddress = typedef const uint8_t*
Definition at line 18 of file globals.h.
DefaultCrossThreadPersistentCheckingPolicy
using cppgc::internal::DefaultCrossThreadPersistentCheckingPolicy = typedef DisabledCheckingPolicy
Definition at line 202 of file pointer-policies.h.
DefaultLocationPolicy
using cppgc::internal::DefaultLocationPolicy = typedef IgnoreLocationPolicy
Definition at line 237 of file pointer-policies.h.
DefaultMemberCheckingPolicy
using cppgc::internal::DefaultMemberCheckingPolicy = typedef DisabledCheckingPolicy
Definition at line 196 of file pointer-policies.h.
DefaultMemberStorage
using cppgc::internal::DefaultMemberStorage = typedef RawPointer
Definition at line 299 of file member-storage.h.
DefaultPersistentCheckingPolicy
using cppgc::internal::DefaultPersistentCheckingPolicy = typedef DisabledCheckingPolicy
Definition at line 197 of file pointer-policies.h.
FinalizationCallback
using cppgc::internal::FinalizationCallback = typedef void (*)(void*)
Definition at line 15 of file finalizer-trait.h.
GCInfoIndex
using cppgc::internal::GCInfoIndex = typedef uint16_t
Definition at line 21 of file gc-info.h.
NameCallback
using cppgc::internal::NameCallback = typedef HeapObjectName (*)(const void*, HeapObjectNameForUnnamedObject)
Definition at line 133 of file name-trait.h.
PointerRepresentation
using cppgc::internal::PointerRepresentation = typedef RawPointer
Definition at line 36 of file visitor.cc.
StackState
using cppgc::internal::StackState = typedef cppgc::Heap::StackState
Definition at line 13 of file heap-config.h.
TraceRootCallback
using cppgc::internal::TraceRootCallback = typedef void (*)(RootVisitor&, const void* object)
Definition at line 21 of file trace-trait.h.
Enumeration Type Documentation
AccessMode
enum cppgc::internal::AccessMode : uint8_t [strong]
Enumerator
kNonAtomic
kAtomic
Definition at line 25 of file globals.h.
: uint8_t { kNonAtomic, kAtomic };
CollectionType
enum cppgc::internal::CollectionType : uint8_t [strong]
Enumerator
kMinor
kMajor
Definition at line 15 of file heap-config.h.
                          : uint8_t {
  kMinor,
  kMajor,
};
FreeMemoryHandling
enum cppgc::internal::FreeMemoryHandling : uint8_t [strong]
Enumerator
kDoNotDiscard
kDiscardWherePossible
Definition at line 27 of file heap-config.h.
                              : uint8_t {
  kDoNotDiscard,
  kDiscardWherePossible
};
HeapObjectNameForUnnamedObject
enum cppgc::internal::HeapObjectNameForUnnamedObject : uint8_t [strong]
Enumerator
kUseClassNameIfSupported
kUseHiddenName
Definition at line 62 of file name-trait.h.
                                          : uint8_t {
  kUseClassNameIfSupported,
  kUseHiddenName,
};
StickyBits
enum cppgc::internal::StickyBits : uint8_t [strong]
Enumerator
kDisabled
kEnabled
Definition at line 67 of file heap-base.h.
                      : uint8_t {
  kDisabled,
  kEnabled,
};
WriteBarrierSlotType
enum cppgc::internal::WriteBarrierSlotType [strong]
Enumerator
kCompressed
kUncompressed
Definition at line 21 of file member-storage.h.
                                {
  kCompressed,
  kUncompressed,
};
Function Documentation
_cppgc_internal_Uncompress_Member()
V8_DEBUGGING_EXPORT C void* cppgc::internal::_cppgc_internal_Uncompress_Member (void * m)
Definition at line 36 of file member-storage.cc.
             {
  return MemberDebugHelper::Uncompress(
      static_cast<MemberBase<DefaultMemberStorage>*>(m));
}
References cppgc::internal::MemberDebugHelper::Uncompress().
CheckMemoryIsInaccessible()
void cppgc::internal::CheckMemoryIsInaccessible (const void * address, size_t size) [inline]
Definition at line 73 of file memory.h.
{}
Referenced by cppgc::internal::anonymous_namespace{sweeper.cc}::SweepNormalPage(), and cppgc::internal::NormalPage::TryCreate().
CheckMemoryIsInaccessibleIsNoop()
constexpr bool cppgc::internal::CheckMemoryIsInaccessibleIsNoop () [constexpr]
Definition at line 74 of file memory.h.
{ return true; }
Referenced by cppgc::internal::Sweeper::CanDiscardMemory().
CheckMemoryIsZapped()
void cppgc::internal::CheckMemoryIsZapped (const void * address, size_t size) [inline]
Definition at line 31 of file memory.h.
                                                                     {
  for (size_t i = 0; i < size; i++) {
    CHECK_EQ(kZappedValue, reinterpret_cast<ConstAddress>(address)[i]);
  }
}
References CHECK_EQ, kZappedValue, and size().
CheckMemoryIsZero()
void cppgc::internal::CheckMemoryIsZero (const void * address, size_t size) [inline]
Definition at line 37 of file memory.h.
                                                                   {
  for (size_t i = 0; i < size; i++) {
    CHECK_EQ(0, reinterpret_cast<ConstAddress>(address)[i]);
  }
}
References CHECK_EQ, and size().
Referenced by cppgc::internal::NormalPageMemoryPool::Take().
DCheckImpl()
void cppgc::internal::DCheckImpl (const char * message, const SourceLocation & loc)
Definition at line 13 of file logging.cc.
                                                                {
  V8_Dcheck(loc.FileName(), static_cast<int>(loc.Line()), message);
}
References v8::SourceLocation::FileName(), v8::SourceLocation::Line(), v8::internal::loc, and V8_Dcheck().
DISPATCH()
cppgc::internal::DISPATCH (true , true , EnsureGCInfoIndex(registered_index, TraceTrait< T >::Trace, FinalizerTrait< T >::kCallback, NameTrait< T >::GetName))
DrainWorklistWithPredicate()
template<size_t kDeadlineCheckInterval, typename Predicate , typename CreateStatsScopeCallback , typename WorklistLocal , typename ProcessWorklistItemCallback >
bool cppgc::internal::DrainWorklistWithPredicate (Predicate ShouldYield, CreateStatsScopeCallback CreateStatsScope, WorklistLocal & worklist_local, ProcessWorklistItemCallback ProcessWorklistItem)
Definition at line 494 of file marking-state.h.
                                                     {
  if (worklist_local.IsLocalAndGlobalEmpty()) {
    return true;
  }
  if (ShouldYield()) {
    return false;
  }
  const auto stats_scope = CreateStatsScope();
  size_t processed_callback_count = kDeadlineCheckInterval;
  typename WorklistLocal::ItemType item;
  while (worklist_local.Pop(&item)) {
    ProcessWorklistItem(item);
    if (V8_UNLIKELY(--processed_callback_count == 0)) {
      if (ShouldYield()) {
        return false;
      }
      processed_callback_count = kDeadlineCheckInterval;
    }
  }
  return true;
}
References v8::internal::anonymous_namespace{mark-compact.cc}::kDeadlineCheckInterval, and V8_UNLIKELY.
DynamicallyTraceMarkedObject()
template<AccessMode mode>
void cppgc::internal::DynamicallyTraceMarkedObject (Visitor & visitor, const HeapObjectHeader & header)
Definition at line 520 of file marking-state.h.
                                                                  {
  DCHECK(!header.IsInConstruction<mode>());
  DCHECK(header.IsMarked<AccessMode::kAtomic>());
  header.TraceImpl<mode>(&visitor);
}
References DCHECK, cppgc::internal::HeapObjectHeader::IsInConstruction(), cppgc::internal::HeapObjectHeader::IsMarked(), kAtomic, mode(), and cppgc::internal::HeapObjectHeader::TraceImpl().
EnsureGCInfoIndex() [1/3]
cppgc::internal::EnsureGCInfoIndex (registered_index , TraceTrait< T >::Trace) [final]
Definition at line 75 of file gc-info.h.
                         {
  V8_INLINE static GCInfoIndex Index() {
    static_assert(sizeof(T), "T must be fully defined");
    static std::atomic<GCInfoIndex>
        registered_index; // Uses zero initialization.
    GCInfoIndex index = registered_index.load(std::memory_order_acquire);
    if (V8_UNLIKELY(!index)) {
      index = EnsureGCInfoIndexTrait::EnsureIndex<T>(registered_index);
      CPPGC_DCHECK(index != 0);
      CPPGC_DCHECK(index == registered_index.load(std::memory_order_acquire));
    }
    return index;
  }
  static constexpr void CheckCallbacksAreDefined() {
    // No USE() macro available.
    (void)static_cast<TraceCallback>(TraceTrait<T>::Trace);
    (void)static_cast<FinalizationCallback>(FinalizerTrait<T>::kCallback);
    (void)static_cast<NameCallback>(NameTrait<T>::GetName);
  }
};
References CPPGC_DCHECK, v8::internal::index, V8_INLINE, V8_UNLIKELY, and v8::internal::wasm::void().
EnsureGCInfoIndex() [2/3]
cppgc::internal::EnsureGCInfoIndex (registered_index , TraceTrait< T >::Trace , FinalizerTrait< T >::kCallback)
EnsureGCInfoIndex() [3/3]
cppgc::internal::EnsureGCInfoIndex (registered_index , TraceTrait< T >::Trace , NameTrait< T >::GetName)
Fatal()
void cppgc::internal::Fatal (const std::string & reason, const SourceLocation & loc)
Definition at line 47 of file platform.cc.
                                                               {
#ifdef DEBUG
  V8_Fatal(loc.FileName(), static_cast<int>(loc.Line()), "%s", reason.c_str());
#else // !DEBUG
  V8_Fatal("%s", reason.c_str());
#endif // !DEBUG
}
References v8::SourceLocation::FileName(), v8::SourceLocation::Line(), v8::internal::loc, and V8_Fatal().
Referenced by cppgc::GarbageCollected< T >::operator delete(), and v8::FuzzerMonitor::SimulateErrors().
FatalImpl()
void cppgc::internal::FatalImpl (const char * message, const SourceLocation & loc)
Definition at line 17 of file logging.cc.
                                                               {
#if DEBUG
  V8_Fatal(loc.FileName(), static_cast<int>(loc.Line()), "Check failed: %s.",
           message);
#elif !defined(OFFICIAL_BUILD)
  V8_Fatal("Check failed: %s.", message);
#else
  V8_Fatal("ignored");
#endif
}
References v8::SourceLocation::FileName(), v8::SourceLocation::Line(), v8::internal::loc, and V8_Fatal().
GetGlobalOOMHandler()
FatalOutOfMemoryHandler & cppgc::internal::GetGlobalOOMHandler ()
Definition at line 73 of file platform.cc.
                                               {
  static FatalOutOfMemoryHandler oom_handler;
  return oom_handler;
}
Referenced by cppgc::internal::CagedHeap::CommitAgeTable(), cppgc::internal::GlobalGCInfoTable::Initialize(), v8::internal::CppHeap::InitializeOncePerProcess(), cppgc::internal::anonymous_namespace{caged-heap.cc}::ReserveCagedHeap(), and cppgc::internal::NormalPageMemoryPool::Take().
GetGlobalPageAllocator()
PageAllocator & cppgc::internal::GetGlobalPageAllocator ()
Definition at line 78 of file platform.cc.
                                        {
  CHECK_NOT_NULL(g_page_allocator);
  return *g_page_allocator;
}
References CHECK_NOT_NULL, and cppgc::internal::anonymous_namespace{platform.cc}::g_page_allocator.
NoSanitizeMemset()
V8_NOINLINE DISABLE_ASAN void cppgc::internal::NoSanitizeMemset (void * address, char c, size_t bytes)
Definition at line 14 of file memory.cc.
                                                           {
  volatile uint8_t* const base = static_cast<uint8_t*>(address);
  for (size_t i = 0; i < bytes; ++i) {
    base[i] = c;
  }
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i.
ObjectHeaderFromInnerAddressImpl()
template<AccessMode mode = AccessMode::kNonAtomic>
const HeapObjectHeader* cppgc::internal::ObjectHeaderFromInnerAddressImpl (const BasePage * page, const void * address)
Definition at line 324 of file heap-page.h.
                                                                              {
  if (page->is_large()) {
    return LargePage::From(page)->ObjectHeader();
  }
  const PlatformAwareObjectStartBitmap& bitmap =
      NormalPage::From(page)->object_start_bitmap();
  const HeapObjectHeader* header =
      bitmap.FindHeader<mode>(static_cast<ConstAddress>(address));
  DCHECK_LT(address, reinterpret_cast<ConstAddress>(header) +
                         header->AllocatedSize<AccessMode::kAtomic>());
  return header;
}
References cppgc::internal::HeapObjectHeader::AllocatedSize(), DCHECK_LT, cppgc::internal::ObjectStartBitmap::FindHeader(), cppgc::internal::NormalPage::From(), cppgc::internal::LargePage::From(), cppgc::internal::BasePage::is_large(), kAtomic, mode(), cppgc::internal::NormalPage::object_start_bitmap(), and cppgc::internal::LargePage::ObjectHeader().
Referenced by cppgc::internal::BasePage::TryObjectHeaderFromInnerAddress().
operator!=() [1/10]
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
bool cppgc::internal::operator!= (const BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType > & member, SentinelPointer s) [inline]
Definition at line 438 of file member.h.
                       {
  return !(member == s);
}
operator!=() [2/10]
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
bool cppgc::internal::operator!= (const BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType > & member, std::nullptr_t n) [inline]
Definition at line 473 of file member.h.
                    {
  return !(member == n);
}
operator!=() [3/10]
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType , typename U >
bool cppgc::internal::operator!= (const BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType > & member, U * raw) [inline]
Definition at line 401 of file member.h.
            {
  return !(member == raw);
}
operator!=() [4/10]
template<typename T1 , typename WeaknessTag1 , typename WriteBarrierPolicy1 , typename CheckingPolicy1 , typename T2 , typename WeaknessTag2 , typename WriteBarrierPolicy2 , typename CheckingPolicy2 , typename StorageType >
bool cppgc::internal::operator!= (const BasicMember< T1, WeaknessTag1, WriteBarrierPolicy1, CheckingPolicy1, StorageType > & member1, const BasicMember< T2, WeaknessTag2, WriteBarrierPolicy2, CheckingPolicy2, StorageType > & member2) [inline]
Definition at line 369 of file member.h.
                                             {
  return !(member1 == member2);
}
operator!=() [5/10]
template<typename T1 , typename MemberWriteBarrierPolicy , typename MemberWeaknessTag , typename MemberCheckingPolicy , typename MemberStorageType , typename T2 , typename PersistentWeaknessPolicy , typename PersistentLocationPolicy , typename PersistentCheckingPolicy >
bool cppgc::internal::operator!= (const BasicMember< T2, MemberWeaknessTag, MemberWriteBarrierPolicy, MemberCheckingPolicy, MemberStorageType > & m, const BasicPersistent< T1, PersistentWeaknessPolicy, PersistentLocationPolicy, PersistentCheckingPolicy > & p)
Definition at line 340 of file persistent.h.
           {
  return !(m == p);
}
operator!=() [6/10]
template<typename T1 , typename PersistentWeaknessPolicy , typename PersistentLocationPolicy , typename PersistentCheckingPolicy , typename T2 , typename MemberWriteBarrierPolicy , typename MemberWeaknessTag , typename MemberCheckingPolicy , typename MemberStorageType >
bool cppgc::internal::operator!= (const BasicPersistent< T1, PersistentWeaknessPolicy, PersistentLocationPolicy, PersistentCheckingPolicy > & p, const BasicMember< T2, MemberWeaknessTag, MemberWriteBarrierPolicy, MemberCheckingPolicy, MemberStorageType > & m)
Definition at line 312 of file persistent.h.
                                                                   {
  return !(p == m);
}
operator!=() [7/10]
template<typename T1 , typename WeaknessPolicy1 , typename LocationPolicy1 , typename CheckingPolicy1 , typename T2 , typename WeaknessPolicy2 , typename LocationPolicy2 , typename CheckingPolicy2 >
bool cppgc::internal::operator!= (const BasicPersistent< T1, WeaknessPolicy1, LocationPolicy1, CheckingPolicy1 > & p1, const BasicPersistent< T2, WeaknessPolicy2, LocationPolicy2, CheckingPolicy2 > & p2)
Definition at line 286 of file persistent.h.
                                                            {
  return !(p1 == p2);
}
References v8::internal::p1, and v8::internal::p2.
operator!=() [8/10]
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
bool cppgc::internal::operator!= (SentinelPointer s, const BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType > & member) [inline]
Definition at line 455 of file member.h.
                                                                               {
  return !(s == member);
}
operator!=() [9/10]
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
bool cppgc::internal::operator!= (std::nullptr_t n, const BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType > & member) [inline]
Definition at line 490 of file member.h.
                                                                              {
  return !(n == member);
}
operator!=() [10/10]
template<typename T , typename U , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
bool cppgc::internal::operator!= (T * raw, const BasicMember< U, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType > & member) [inline]
Definition at line 420 of file member.h.
                                                                    {
  return !(raw == member);
}
operator<()
template<typename T1 , typename WeaknessTag1 , typename WriteBarrierPolicy1 , typename CheckingPolicy1 , typename T2 , typename WeaknessTag2 , typename WriteBarrierPolicy2 , typename CheckingPolicy2 , typename StorageType >
bool cppgc::internal::operator< (const BasicMember< T1, WeaknessTag1, WriteBarrierPolicy1, CheckingPolicy1, StorageType > & member1, const BasicMember< T2, WeaknessTag2, WriteBarrierPolicy2, CheckingPolicy2, StorageType > & member2) [inline]
Definition at line 501 of file member.h.
                                             {
  static_assert(
      IsDecayedSameV<T1, T2>,
      "Comparison works only for same pointer type modulo cv-qualifiers");
  return member1.GetRawStorage() < member2.GetRawStorage();
}
operator<=()
template<typename T1 , typename WeaknessTag1 , typename WriteBarrierPolicy1 , typename CheckingPolicy1 , typename T2 , typename WeaknessTag2 , typename WriteBarrierPolicy2 , typename CheckingPolicy2 , typename StorageType >
bool cppgc::internal::operator<= (const BasicMember< T1, WeaknessTag1, WriteBarrierPolicy1, CheckingPolicy1, StorageType > & member1, const BasicMember< T2, WeaknessTag2, WriteBarrierPolicy2, CheckingPolicy2, StorageType > & member2) [inline]
Definition at line 516 of file member.h.
                                             {
  static_assert(
      IsDecayedSameV<T1, T2>,
      "Comparison works only for same pointer type modulo cv-qualifiers");
  return member1.GetRawStorage() <= member2.GetRawStorage();
}
Referenced by v8::internal::HandlerTable::LookupReturn().
operator==() [1/10]
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
bool cppgc::internal::operator== (const BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType > & member, SentinelPointer) [inline]
Definition at line 429 of file member.h.
                     {
  return member.GetRawStorage().IsSentinel();
}
operator==() [2/10]
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
bool cppgc::internal::operator== (const BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType > & member, std::nullptr_t) [inline]
Definition at line 464 of file member.h.
                  {
  return !static_cast<bool>(member);
}
operator==() [3/10]
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType , typename U >
bool cppgc::internal::operator== (const BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType > & member, U * raw) [inline]
Definition at line 380 of file member.h.
            {
  // Never allow comparison with erased pointers.
  static_assert(!IsDecayedSameV<void, U>);
  if constexpr (IsDecayedSameV<T, U>) {
    // Check compressed pointers if types are the same.
    return member.GetRawStorage() == StorageType(raw);
  } else if constexpr (IsStrictlyBaseOfV<T, U>) {
    // Cast the raw pointer to T, which may adjust the pointer.
    return member.GetRawStorage() == StorageType(static_cast<T*>(raw));
  } else {
    // Otherwise, decompressed the member.
    return member.Get() == raw;
  }
}
operator==() [4/10]
template<typename T1 , typename WeaknessTag1 , typename WriteBarrierPolicy1 , typename CheckingPolicy1 , typename T2 , typename WeaknessTag2 , typename WriteBarrierPolicy2 , typename CheckingPolicy2 , typename StorageType >
bool cppgc::internal::operator== (const BasicMember< T1, WeaknessTag1, WriteBarrierPolicy1, CheckingPolicy1, StorageType > & member1, const BasicMember< T2, WeaknessTag2, WriteBarrierPolicy2, CheckingPolicy2, StorageType > & member2) [inline]
Definition at line 350 of file member.h.
                                             {
  if constexpr (IsDecayedSameV<T1, T2>) {
    // Check compressed pointers if types are the same.
    return member1.GetRawStorage() == member2.GetRawStorage();
  } else {
    static_assert(IsStrictlyBaseOfV<T1, T2> || IsStrictlyBaseOfV<T2, T1>);
    // Otherwise, check decompressed pointers.
    return member1.Get() == member2.Get();
  }
}
operator==() [5/10]
template<typename T1 , typename MemberWriteBarrierPolicy , typename MemberWeaknessTag , typename MemberCheckingPolicy , typename MemberStorageType , typename T2 , typename PersistentWeaknessPolicy , typename PersistentLocationPolicy , typename PersistentCheckingPolicy >
bool cppgc::internal::operator== (const BasicMember< T2, MemberWeaknessTag, MemberWriteBarrierPolicy, MemberCheckingPolicy, MemberStorageType > & m, const BasicPersistent< T1, PersistentWeaknessPolicy, PersistentLocationPolicy, PersistentCheckingPolicy > & p)
Definition at line 326 of file persistent.h.
           {
  return m.Get() == p.Get();
}
operator==() [6/10]
template<typename T1 , typename PersistentWeaknessPolicy , typename PersistentLocationPolicy , typename PersistentCheckingPolicy , typename T2 , typename MemberWriteBarrierPolicy , typename MemberWeaknessTag , typename MemberCheckingPolicy , typename MemberStorageType >
bool cppgc::internal::operator== (const BasicPersistent< T1, PersistentWeaknessPolicy, PersistentLocationPolicy, PersistentCheckingPolicy > & p, const BasicMember< T2, MemberWeaknessTag, MemberWriteBarrierPolicy, MemberCheckingPolicy, MemberStorageType > & m)
Definition at line 298 of file persistent.h.
                                                                   {
  return p.Get() == m.Get();
}
operator==() [7/10]
template<typename T1 , typename WeaknessPolicy1 , typename LocationPolicy1 , typename CheckingPolicy1 , typename T2 , typename WeaknessPolicy2 , typename LocationPolicy2 , typename CheckingPolicy2 >
bool cppgc::internal::operator== (const BasicPersistent< T1, WeaknessPolicy1, LocationPolicy1, CheckingPolicy1 > & p1, const BasicPersistent< T2, WeaknessPolicy2, LocationPolicy2, CheckingPolicy2 > & p2)
Definition at line 276 of file persistent.h.
                                                            {
  return p1.Get() == p2.Get();
}
References v8::internal::p1, and v8::internal::p2.
operator==() [8/10]
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
bool cppgc::internal::operator== (SentinelPointer s, const BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType > & member) [inline]
Definition at line 447 of file member.h.
                                                                               {
  return member == s;
}
operator==() [9/10]
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
bool cppgc::internal::operator== (std::nullptr_t n, const BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType > & member) [inline]
Definition at line 482 of file member.h.
                                                                              {
  return member == n;
}
operator==() [10/10]
template<typename T , typename U , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
bool cppgc::internal::operator== (T * raw, const BasicMember< U, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType > & member) [inline]
Definition at line 411 of file member.h.
                                                                    {
  return member == raw;
}
operator>()
template<typename T1 , typename WeaknessTag1 , typename WriteBarrierPolicy1 , typename CheckingPolicy1 , typename T2 , typename WeaknessTag2 , typename WriteBarrierPolicy2 , typename CheckingPolicy2 , typename StorageType >
bool cppgc::internal::operator> (const BasicMember< T1, WeaknessTag1, WriteBarrierPolicy1, CheckingPolicy1, StorageType > & member1, const BasicMember< T2, WeaknessTag2, WriteBarrierPolicy2, CheckingPolicy2, StorageType > & member2) [inline]
Definition at line 531 of file member.h.
                                             {
  static_assert(
      IsDecayedSameV<T1, T2>,
      "Comparison works only for same pointer type modulo cv-qualifiers");
  return member1.GetRawStorage() > member2.GetRawStorage();
}
operator>=()
template<typename T1 , typename WeaknessTag1 , typename WriteBarrierPolicy1 , typename CheckingPolicy1 , typename T2 , typename WeaknessTag2 , typename WriteBarrierPolicy2 , typename CheckingPolicy2 , typename StorageType >
bool cppgc::internal::operator>= (const BasicMember< T1, WeaknessTag1, WriteBarrierPolicy1, CheckingPolicy1, StorageType > & member1, const BasicMember< T2, WeaknessTag2, WriteBarrierPolicy2, CheckingPolicy2, StorageType > & member2) [inline]
Definition at line 546 of file member.h.
                                             {
  static_assert(
      IsDecayedSameV<T1, T2>,
      "Comparison works only for same pointer type modulo cv-qualifiers");
  return member1.GetRawStorage() >= member2.GetRawStorage();
}
requires() [1/2]
template<typename T >
cppgc::internal::requires (!RequiresStackAllocated< T >)
Definition at line 35 of file conditional-stack-allocated.h.
                                       {};
requires() [2/2]
template<typename T >
cppgc::internal::requires (RequiresStackAllocated< T >)
Definition at line 28 of file conditional-stack-allocated.h.
                                       {
 public:
  CPPGC_STACK_ALLOCATED();
};
References CPPGC_STACK_ALLOCATED.
SetAndReturnType()
template<WriteBarrier::Type type>
WriteBarrier::Type cppgc::internal::SetAndReturnType (WriteBarrier::Params & params) [inline]
Definition at line 157 of file write-barrier.h.
                                                                        {
  if constexpr (type == WriteBarrier::Type::kNone)
    return WriteBarrier::Type::kNone;
#if V8_ENABLE_CHECKS
  params.type = type;
#endif // !V8_ENABLE_CHECKS
  return type;
}
References cppgc::internal::WriteBarrier::kNone, and v8::internal::tracing::type.
SetMemoryAccessible()
void cppgc::internal::SetMemoryAccessible (void * address, size_t size) [inline]
Definition at line 72 of file memory.h.
{}
Referenced by cppgc::internal::ObjectAllocator::AllocateObjectOnSpace(), and cppgc::internal::anonymous_namespace{explicit-management.cc}::Grow().
SetMemoryInaccessible()
void cppgc::internal::SetMemoryInaccessible (void * address, size_t size) [inline]
Definition at line 76 of file memory.h.
                                                                 {
  memset(address, 0, size);
}
References size().
Referenced by cppgc::internal::anonymous_namespace{sweeper.cc}::InlinedFinalizationBuilder< FreeHandler >::AddFinalizer(), cppgc::internal::anonymous_namespace{sweeper.cc}::DeferredFinalizationBuilder< FreeHandler >::AddFinalizer(), cppgc::internal::anonymous_namespace{sweeper.cc}::SweepFinalizer::FinalizePage(), cppgc::internal::anonymous_namespace{compactor.cc}::CompactionState::FinishCompactingSpace(), cppgc::internal::ExplicitManagementImpl::FreeUnreferencedObject(), cppgc::internal::anonymous_namespace{compactor.cc}::CompactionState::ReturnCurrentPageToSpace(), cppgc::internal::anonymous_namespace{explicit-management.cc}::Shrink(), and cppgc::internal::anonymous_namespace{sweeper.cc}::SweepNormalPage().
ZapMemory()
void cppgc::internal::ZapMemory (void * address, size_t size) [inline]
Definition at line 25 of file memory.h.
                                                     {
  // The lowest bit of the zapped value should be 0 so that zapped object are
  // never viewed as fully constructed objects.
  memset(address, kZappedValue, size);
}
References kZappedValue, and size().
Referenced by cppgc::internal::anonymous_namespace{compactor.cc}::CompactPage(), cppgc::internal::anonymous_namespace{compactor.cc}::CompactionState::FinishCompactingPage(), and cppgc::internal::NormalPage::TryCreate().
Variable Documentation
false
cppgc::internal::false
Definition at line 66 of file gc-info.h.
IsAnyMemberTypeV
template<typename T >
constexpr bool cppgc::internal::IsAnyMemberTypeV = false [constexpr]
Definition at line 185 of file type-traits.h.
IsDecayedSameV
template<typename T , typename U >
constexpr bool cppgc::internal::IsDecayedSameV [constexpr]
Initial value:
=
    std::is_same_v<std::decay_t<T>, std::decay_t<U>>
Definition at line 176 of file type-traits.h.
IsStrictlyBaseOfV
template<typename B , typename D >
constexpr bool cppgc::internal::IsStrictlyBaseOfV [constexpr]
Initial value:
=
    std::is_base_of_v<std::decay_t<B>, std::decay_t<D>> &&
    !IsDecayedSameV<B, D>
Definition at line 180 of file type-traits.h.
IsTraceableV
template<typename T >
constexpr bool cppgc::internal::IsTraceableV = IsTraceable<T>::value [constexpr]
Definition at line 59 of file type-traits.h.
kAllocationGranularity
constexpr size_t cppgc::internal::kAllocationGranularity = 4 [constexpr]
Definition at line 37 of file globals.h.
Referenced by cppgc::internal::BasePage::AllocatedSize(), cppgc::internal::ObjectAllocator::AllocateObjectOnSpace(), cppgc::internal::HeapObjectHeader::DecodeSize(), cppgc::internal::HeapObjectHeader::EncodeSize(), cppgc::internal::ObjectStartBitmap::FindHeader(), cppgc::internal::ObjectStartBitmap::Granularity(), cppgc::internal::anonymous_namespace{explicit-management.cc}::Grow(), cppgc::InitializeProcess(), cppgc::internal::ObjectStartBitmap::Iterate(), cppgc::internal::ObjectStartBitmap::ObjectStartIndexAndBit(), cppgc::internal::ObjectAllocator::OutOfLineAllocateImpl(), cppgc::internal::NormalPage::PayloadSize(), cppgc::internal::NormalPage::PayloadStart(), and cppgc::internal::anonymous_namespace{explicit-management.cc}::Shrink().
kAllocationMask
constexpr size_t cppgc::internal::kAllocationMask = kAllocationGranularity - 1 [constexpr]
Definition at line 39 of file globals.h.
Referenced by cppgc::internal::SameThreadEnabledCheckingPolicyBase::CheckPointerImpl(), cppgc::internal::ObjectStartBitmap::ObjectStartIndexAndBit(), and cppgc::internal::ObjectAllocator::OutOfLineAllocateImpl().
kFreeListEntrySize
constexpr size_t cppgc::internal::kFreeListEntrySize = 2 * sizeof(uintptr_t) [constexpr]
Definition at line 49 of file globals.h.
Referenced by cppgc::internal::FreeList::Entry::Entry(), cppgc::internal::ObjectAllocator::OutOfLineAllocateImpl(), and cppgc::internal::anonymous_namespace{sweeper.cc}::SweepNormalPage().
kFreeListGCInfoIndex
constexpr GCInfoIndex cppgc::internal::kFreeListGCInfoIndex = 0 [constexpr]
Definition at line 48 of file globals.h.
Referenced by cppgc::internal::HeapObjectHeader::IsFree(), cppgc::internal::BasePage::ObjectHeaderFromInnerAddress(), and cppgc::internal::BasePage::TryObjectHeaderFromInnerAddress().
kGB
constexpr size_t cppgc::internal::kGB = kMB * 1024 [constexpr]
Definition at line 22 of file globals.h.
kKB
constexpr size_t cppgc::internal::kKB = 1024 [constexpr]
Definition at line 20 of file globals.h.
kLargeObjectSizeThreshold
constexpr size_t cppgc::internal::kLargeObjectSizeThreshold = kPageSize / 2 [constexpr]
Definition at line 46 of file globals.h.
Referenced by cppgc::internal::NormalPage::NormalPage(), cppgc::internal::ObjectAllocator::OutOfLineAllocateImpl(), and cppgc::internal::LargePage::TryCreate().
kMB
constexpr size_t cppgc::internal::kMB = kKB * 1024 [constexpr]
Definition at line 21 of file globals.h.
kPageBaseMask
constexpr size_t cppgc::internal::kPageBaseMask = ~kPageOffsetMask [constexpr]
Definition at line 44 of file globals.h.
Referenced by cppgc::internal::ObjectStartBitmap::FindHeader(), and cppgc::internal::ObjectStartBitmap::Iterate().
kPageOffsetMask
constexpr size_t cppgc::internal::kPageOffsetMask = kPageSize - 1 [constexpr]
Definition at line 43 of file globals.h.
Referenced by cppgc::internal::BasePage::BasePage(), cppgc::internal::ObjectStartBitmap::FindHeader(), and cppgc::internal::ObjectStartBitmap::ObjectStartIndexAndBit().
kPageSize
constexpr size_t cppgc::internal::kPageSize = 1 << kPageSizeLog2 [constexpr]
Definition at line 42 of file globals.h.
Referenced by cppgc::internal::NormalPageMemoryPool::Add(), cppgc::internal::FreeList::AddReturningUnusedBounds(), cppgc::internal::CagedHeap::CagedHeap(), cppgc::internal::anonymous_namespace{compactor.cc}::CompactPage(), v8::internal::MinorGCHeapGrowing::ConfigureLimit(), cppgc::internal::anonymous_namespace{page-memory.cc}::CreateNormalPageMemoryRegion(), cppgc::internal::NormalPage::Destroy(), v8::base::OS::EnsureAlternativeSignalStackIsAvailableForCurrentThread(), v8::internal::PageEvacuationJob::GetMaxConcurrency(), v8::internal::CodeRange::InitReservation(), v8::internal::anonymous_namespace{tick-sample.cc}::IsSamePage(), cppgc::internal::NormalPage::PayloadSize(), cppgc::internal::anonymous_namespace{page-memory.cc}::ReserveMemoryRegion(), cppgc::internal::NormalPage::TryCreate(), and cppgc::internal::HeapStatisticsCollector::VisitNormalPage().
kPageSizeLog2
constexpr size_t cppgc::internal::kPageSizeLog2 = 17 [constexpr]
Definition at line 41 of file globals.h.
Referenced by cppgc::internal::FreeList::CollectStatistics().
kSizeOfMember
constexpr size_t cppgc::internal::kSizeOfMember = sizeof(Member<Dummy>) [static], [constexpr]
Definition at line 626 of file member.h.
kSizeOfUncompressedMember
constexpr size_t cppgc::internal::kSizeOfUncompressedMember [static], [constexpr]
Initial value:
=
    sizeof(subtle::UncompressedMember<Dummy>)
Definition at line 627 of file member.h.
Referenced by v8::internal::UnifiedHeapMarkingVisitorBase::VisitMultipleUncompressedMember(), cppgc::internal::MarkingVisitorBase::VisitMultipleUncompressedMember(), and cppgc::Visitor::VisitMultipleUncompressedMember().
kSlotSize
constexpr size_t cppgc::internal::kSlotSize = sizeof(uintptr_t) [constexpr]
Definition at line 54 of file globals.h.
Referenced by v8::internal::AlignedSlotAllocator::NumSlotsForWidth().
kZappedValue
constexpr uint8_t cppgc::internal::kZappedValue = 0xdc [static], [constexpr]
Definition at line 23 of file memory.h.
Referenced by CheckMemoryIsZapped(), and ZapMemory().
RequiresStackAllocated
template<typename T >
concept cppgc::internal::RequiresStackAllocated
Initial value:
=
    !std::is_void_v<T> &&
    (cppgc::IsStackAllocatedType<T> || cppgc::internal::IsTraceableV<T> ||
     cppgc::IsGarbageCollectedOrMixinTypeV<T>)
Definition at line 22 of file conditional-stack-allocated.h.
true
cppgc::internal::true
Definition at line 70 of file gc-info.h.