v8::internal::compiler::anonymous_namespace{js-create-lowering.cc} Namespace Reference
Functions
FrameState GetArgumentsFrameState (FrameState frame_state)
MapRef MapForCollectionIterationKind (JSHeapBroker *broker, NativeContextRef native_context, CollectionKind collection_kind, IterationKind iteration_kind)
OptionalMapRef GetObjectCreateMap (JSHeapBroker *broker, HeapObjectRef prototype)
Variables
const int kElementLoopUnrollLimit = 16
const int kFunctionContextAllocationLimit = 16
const int kBlockContextAllocationLimit = 16
Function Documentation
GetArgumentsFrameState()
FrameState v8::internal::compiler::anonymous_namespace{js-create-lowering.cc}::GetArgumentsFrameState (FrameState frame_state)
Definition at line 39 of file js-create-lowering.cc.
                                                          {
  FrameState outer_state{NodeProperties::GetFrameStateInput(frame_state)};
  return outer_state.frame_state_info().type() ==
                 FrameStateType::kInlinedExtraArguments
             ? outer_state
             : frame_state;
}
References v8::internal::compiler::NodeProperties::GetFrameStateInput(), v8::internal::compiler::kInlinedExtraArguments, and v8::internal::compiler::Node::type().
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateArguments().
GetObjectCreateMap()
OptionalMapRef v8::internal::compiler::anonymous_namespace{js-create-lowering.cc}::GetObjectCreateMap (JSHeapBroker * broker, HeapObjectRef prototype)
Definition at line 1374 of file js-create-lowering.cc.
                                                           {
  MapRef standard_map =
      broker->target_native_context().object_function(broker).initial_map(
          broker);
  if (prototype.equals(standard_map.prototype(broker))) {
    return standard_map;
  }
  if (prototype.map(broker).oddball_type(broker) == OddballType::kNull) {
    return broker->target_native_context().slow_object_with_null_prototype_map(
        broker);
  }
  if (prototype.IsJSObject()) {
    return prototype.AsJSObject().GetObjectCreateMap(broker);
  }
  return OptionalMapRef();
}
References broker(), v8::internal::compiler::kNull, v8::internal::compiler::MapRef::prototype(), and v8::internal::prototype.
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateObject().
MapForCollectionIterationKind()
MapRef v8::internal::compiler::anonymous_namespace{js-create-lowering.cc}::MapForCollectionIterationKind (JSHeapBroker * broker, NativeContextRef native_context, CollectionKind collection_kind, IterationKind iteration_kind)
Definition at line 832 of file js-create-lowering.cc.
                                                                   {
  switch (collection_kind) {
    case CollectionKind::kSet:
      switch (iteration_kind) {
        case IterationKind::kKeys:
          UNREACHABLE();
        case IterationKind::kValues:
          return native_context.set_value_iterator_map(broker);
        case IterationKind::kEntries:
          return native_context.set_key_value_iterator_map(broker);
      }
      break;
    case CollectionKind::kMap:
      switch (iteration_kind) {
        case IterationKind::kKeys:
          return native_context.map_key_iterator_map(broker);
        case IterationKind::kValues:
          return native_context.map_value_iterator_map(broker);
        case IterationKind::kEntries:
          return native_context.map_key_value_iterator_map(broker);
      }
      break;
  }
  UNREACHABLE();
}
References broker(), v8::internal::kEntries, v8::internal::kKeys, v8::internal::kMap, v8::internal::kSet, v8::internal::kValues, v8::internal::native_context, and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateCollectionIterator().
Variable Documentation
kBlockContextAllocationLimit
const int v8::internal::compiler::anonymous_namespace{js-create-lowering.cc}::kBlockContextAllocationLimit = 16
Definition at line 53 of file js-create-lowering.cc.
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateBlockContext().
kElementLoopUnrollLimit
const int v8::internal::compiler::anonymous_namespace{js-create-lowering.cc}::kElementLoopUnrollLimit = 16
Definition at line 49 of file js-create-lowering.cc.
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateArray().
kFunctionContextAllocationLimit
const int v8::internal::compiler::anonymous_namespace{js-create-lowering.cc}::kFunctionContextAllocationLimit = 16
Definition at line 52 of file js-create-lowering.cc.
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateFunctionContext().