v8::internal::torque::anonymous_namespace{types.cc} Namespace Reference
Functions
void ComputeSlotKindsHelper (std::vector< ObjectSlotKind > *slots, size_t start_offset, const std::vector< Field > &fields)
bool FirstTypeIsContext (const std::vector< const Type * > &parameter_types)
void AppendLoweredTypes (const Type *type, std::vector< const Type * > *result)
Function Documentation
AppendLoweredTypes()
void v8::internal::torque::anonymous_namespace{types.cc}::AppendLoweredTypes (const Type * type, std::vector< const Type * > * result)
Definition at line 1197 of file types.cc.
                                                                          {
  if (type->IsConstexpr()) return;
  if (type->IsVoidOrNever()) return;
  if (std::optional<const StructType*> s = type->StructSupertype()) {
    for (const Field& field : (*s)->fields()) {
      AppendLoweredTypes(field.name_and_type.type, result);
    }
  } else {
    result->push_back(type);
  }
}
References v8::base::internal::result, and v8::internal::tracing::type.
Referenced by v8::internal::torque::LowerParameterTypes(), and v8::internal::torque::LowerType().
ComputeSlotKindsHelper()
void v8::internal::torque::anonymous_namespace{types.cc}::ComputeSlotKindsHelper (std::vector< ObjectSlotKind > * slots, size_t start_offset, const std::vector< Field > & fields)
Definition at line 704 of file types.cc.
                                                            {
  size_t offset = start_offset;
  for (const Field& field : fields) {
    size_t field_size = std::get<0>(field.GetFieldSizeInformation());
    // Support optional padding fields.
    if (field_size == 0) continue;
    size_t slot_index = offset / TargetArchitecture::TaggedSize();
    // Rounding-up division to find the number of slots occupied by all the
    // fields up to and including the current one.
    size_t used_slots =
        (offset + field_size + TargetArchitecture::TaggedSize() - 1) /
        TargetArchitecture::TaggedSize();
    while (used_slots > slots->size()) {
      slots->push_back(ObjectSlotKind::kNoPointer);
    }
    const Type* type = field.name_and_type.type;
    if (auto struct_type = type->StructSupertype()) {
      ComputeSlotKindsHelper(slots, offset, (*struct_type)->fields());
    } else {
      ObjectSlotKind kind;
      if (type->IsSubtypeOf(TypeOracle::GetObjectType())) {
        if (field.custom_weak_marking) {
          kind = ObjectSlotKind::kCustomWeakPointer;
        } else {
          kind = ObjectSlotKind::kStrongPointer;
        }
      } else if (type->IsSubtypeOf(TypeOracle::GetTaggedType())) {
        DCHECK(!field.custom_weak_marking);
        kind = ObjectSlotKind::kMaybeObjectPointer;
      } else {
        kind = ObjectSlotKind::kNoPointer;
      }
      DCHECK(slots->at(slot_index) == ObjectSlotKind::kNoPointer);
      slots->at(slot_index) = kind;
    }
    offset += field_size;
  }
}
References v8::internal::DCHECK(), v8::internal::torque::TypeOracle::GetObjectType(), v8::internal::torque::TypeOracle::GetTaggedType(), v8::internal::torque::kCustomWeakPointer, v8::internal::torque::kMaybeObjectPointer, v8::internal::torque::kNoPointer, v8::internal::torque::kStrongPointer, v8::internal::torque::TargetArchitecture::TaggedSize(), and v8::internal::tracing::type.
Referenced by v8::internal::torque::ClassType::ComputeArraySlotKind(), and v8::internal::torque::ClassType::ComputeHeaderSlotKinds().
FirstTypeIsContext()
bool v8::internal::torque::anonymous_namespace{types.cc}::FirstTypeIsContext (const std::vector< const Type * > & parameter_types)
Definition at line 1154 of file types.cc.
                                                                       {
  return !parameter_types.empty() &&
         (parameter_types[0] == TypeOracle::GetContextType() ||
          parameter_types[0] == TypeOracle::GetNoContextType());
}
References v8::internal::torque::TypeOracle::GetContextType(), and v8::internal::torque::TypeOracle::GetNoContextType().
Referenced by v8::internal::torque::BuiltinPointerType::HasContextParameter(), and v8::internal::torque::Signature::HasContextParameter().