v8::internal::anonymous_namespace{debug-objects.cc} Namespace Reference
Functions
bool IsEqual (Tagged< BreakPoint > break_point1, Tagged< BreakPoint > break_point2)
Function Documentation
IsEqual()
bool v8::internal::anonymous_namespace{debug-objects.cc}::IsEqual (Tagged< BreakPoint > break_point1, Tagged< BreakPoint > break_point2)
Definition at line 239 of file debug-objects.cc.
                                                                               {
  return break_point1->id() == break_point2->id();
}
Referenced by v8::internal::BreakPointInfo::ClearBreakPoint(), v8::internal::BreakPointInfo::HasBreakPoint(), and v8::internal::BreakPointInfo::SetBreakPoint().