v8::internal::anonymous_namespace{runtime-regexp.cc} Namespace Reference
Classes
class MatchInfoBackedMatch
class VectorBackedMatch
Functions
uint32_t GetArgcForReplaceCallable (uint32_t num_captures, bool has_named_captures)
template<typename Matcher , typename = std::enable_if<std::is_invocable_r_v< bool, Matcher, Tagged<String>>>>
int LookupNamedCapture (Matcher name_matches, Tagged< FixedArray > capture_name_map, int *index_in_out)
std::vector< int > * GetRewoundRegexpIndicesList (Isolate *isolate)
void TruncateRegexpIndicesList (Isolate *isolate)
std::optional< int > RegExpExec (Isolate *isolate, DirectHandle< JSRegExp > regexp, DirectHandle< String > subject, int32_t index, int32_t *result_offsets_vector, uint32_t result_offsets_vector_length)
std::optional< int > ExperimentalOneshotExec (Isolate *isolate, DirectHandle< JSRegExp > regexp, DirectHandle< String > subject, int32_t index, int32_t *result_offsets_vector, uint32_t result_offsets_vector_length)
template<typename FunctionType , typename = std::enable_if_t<std::is_function_v<Tagged<Object>(int)>>>
DirectHandle< JSObject > ConstructNamedCaptureGroupsObject (Isolate *isolate, DirectHandle< FixedArray > capture_map, const FunctionType &f_get_capture)
template<bool has_capture>
static Tagged< Object > SearchRegExpMultiple (Isolate *isolate, DirectHandle< String > subject, DirectHandle< JSRegExp > regexp, DirectHandle< RegExpData > regexp_data, DirectHandle< RegExpMatchInfo > last_match_array)
V8_WARN_UNUSED_RESULT MaybeDirectHandle< String > RegExpReplace (Isolate *isolate, DirectHandle< JSRegExp > regexp, DirectHandle< String > string, DirectHandle< String > replace)
V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > ToUint32 (Isolate *isolate, DirectHandle< Object > object, uint32_t *out)
DirectHandle< JSArray > NewJSArrayWithElements (Isolate *isolate, DirectHandle< FixedArray > elems, int num_elems)
template<typename Char >
bool IsContainFlagImpl (Isolate *isolate, base::Vector< const Char > flags, const char *target, DisallowGarbageCollection &no_gc)
bool IsContainFlag (Isolate *isolate, String::FlatContent &flags, const char *target, DisallowGarbageCollection &no_gc)
template<typename SChar , typename PChar >
void RegExpMatchGlobalAtom_OneCharPattern (Isolate *isolate, base::Vector< const SChar > subject, const PChar pattern, int start_index, int *number_of_matches, int *last_match_index, const DisallowGarbageCollection &no_gc)
template<> void RegExpMatchGlobalAtom_OneCharPattern (Isolate *isolate, base::Vector< const uint8_t > subject, const base::uc16 pattern, int start_index, int *number_of_matches, int *last_match_index, const DisallowGarbageCollection &no_gc)=delete
template<typename Char >
int AdvanceStringIndex (base::Vector< const Char > subject, int index, bool is_unicode)
template<typename SChar , typename PChar >
void RegExpMatchGlobalAtom_Generic (Isolate *isolate, base::Vector< const SChar > subject, base::Vector< const PChar > pattern, bool is_unicode, int start_index, int *number_of_matches, int *last_match_index, const DisallowGarbageCollection &no_gc)
void RegExpMatchGlobalAtom_Dispatch (Isolate *isolate, const String::FlatContent &subject, const String::FlatContent &pattern, bool is_unicode, int start_index, int *number_of_matches, int *last_match_index, const DisallowGarbageCollection &no_gc)
Variables
constexpr int kStaticVectorSlots = 8
Function Documentation
AdvanceStringIndex()
template<typename Char >
int v8::internal::anonymous_namespace{runtime-regexp.cc}::AdvanceStringIndex (base::Vector< const Char > subject, int index, bool is_unicode) [inline]
Definition at line 2266 of file runtime-regexp.cc.
                                               {
  // Taken from RegExpUtils::AdvanceStringIndex:
  const int subject_length = subject.length();
  if (is_unicode && index < subject_length) {
    const uint16_t first = subject[index];
    if (first >= 0xD800 && first <= 0xDBFF && index + 1 < subject_length) {
      DCHECK_LT(index, std::numeric_limits<int>::max());
      const uint16_t second = subject[index + 1];
      if (second >= 0xDC00 && second <= 0xDFFF) {
        return index + 2;
      }
    }
  }
  return index + 1;
}
References DCHECK_LT, v8::internal::index, and v8::base::Vector< T >::length().
Referenced by RegExpMatchGlobalAtom_Generic().
ConstructNamedCaptureGroupsObject()
template<typename FunctionType , typename = std::enable_if_t<std::is_function_v<Tagged<Object>(int)>>>
DirectHandle<JSObject> v8::internal::anonymous_namespace{runtime-regexp.cc}::ConstructNamedCaptureGroupsObject (Isolate * isolate, DirectHandle< FixedArray > capture_map, const FunctionType & f_get_capture)
Definition at line 1215 of file runtime-regexp.cc.
                                       {
  DirectHandle<JSObject> groups =
      isolate->factory()->NewJSObjectWithNullProto();
  const int named_capture_count = capture_map->length() >> 1;
  for (int i = 0; i < named_capture_count; i++) {
    const int name_ix = i * 2;
    const int index_ix = i * 2 + 1;
    DirectHandle<String> capture_name(Cast<String>(capture_map->get(name_ix)),
                                      isolate);
    const int capture_ix = Smi::ToInt(capture_map->get(index_ix));
    DCHECK_GE(capture_ix, 1); // Explicit groups start at index 1.
    DirectHandle<Object> capture_value(f_get_capture(capture_ix), isolate);
    DCHECK(IsUndefined(*capture_value, isolate) || IsString(*capture_value));
    LookupIterator it(isolate, groups, capture_name, groups,
                      LookupIterator::OWN_SKIP_INTERCEPTOR);
    if (it.IsFound()) {
      DCHECK(v8_flags.js_regexp_duplicate_named_groups);
      if (!IsUndefined(*capture_value, isolate)) {
        DCHECK(IsUndefined(*it.GetDataValue(), isolate));
        CHECK(Object::SetDataProperty(&it, capture_value).ToChecked());
      }
    } else {
      CHECK(Object::AddDataProperty(&it, capture_value, NONE,
                                    Just(ShouldThrow::kThrowOnError),
                                    StoreOrigin::kNamed)
                .IsJust());
    }
  }
  return groups;
}
References v8::internal::Object::AddDataProperty(), CHECK, v8::internal::DCHECK(), DCHECK_GE, v8::internal::Isolate::factory(), v8::internal::LookupIterator::GetDataValue(), v8::internal::LookupIterator::IsFound(), v8::Just(), v8::internal::kNamed, v8::internal::kThrowOnError, v8::internal::Factory::NewJSObjectWithNullProto(), v8::internal::NONE, v8::internal::LookupIterator::OWN_SKIP_INTERCEPTOR, v8::internal::Object::SetDataProperty(), v8::internal::Smi::ToInt(), and v8::internal::v8_flags.
Referenced by v8::internal::RUNTIME_FUNCTION(), and SearchRegExpMultiple().
ExperimentalOneshotExec()
std::optional<int> v8::internal::anonymous_namespace{runtime-regexp.cc}::ExperimentalOneshotExec (Isolate * isolate, DirectHandle< JSRegExp > regexp, DirectHandle< String > subject, int32_t index, int32_t * result_offsets_vector, uint32_t result_offsets_vector_length)
Definition at line 938 of file runtime-regexp.cc.
                                           {
  CHECK_GE(result_offsets_vector_length,
           JSRegExp::RegistersForCaptureCount(
               regexp->data(isolate)->capture_count()));
  // Due to the way the JS calls are constructed this must be less than the
  // length of a string, i.e. it is always a Smi. We check anyway for security.
  CHECK_LE(0, index);
  CHECK_GE(subject->length(), index);
  isolate->counters()->regexp_entry_runtime()->Increment();
  return RegExp::ExperimentalOneshotExec(isolate, regexp, subject, index,
                                         result_offsets_vector,
                                         result_offsets_vector_length);
}
References CHECK_GE, CHECK_LE, v8::internal::Isolate::counters(), v8::internal::RegExp::ExperimentalOneshotExec(), v8::internal::index, and v8::internal::JSRegExp::RegistersForCaptureCount().
Referenced by v8::internal::RUNTIME_FUNCTION().
GetArgcForReplaceCallable()
uint32_t v8::internal::anonymous_namespace{runtime-regexp.cc}::GetArgcForReplaceCallable (uint32_t num_captures, bool has_named_captures)
Definition at line 39 of file runtime-regexp.cc.
                                                            {
  const uint32_t kAdditionalArgsWithoutNamedCaptures = 2;
  const uint32_t kAdditionalArgsWithNamedCaptures = 3;
  if (num_captures > Code::kMaxArguments) return -1;
  uint32_t argc = has_named_captures
                      ? num_captures + kAdditionalArgsWithNamedCaptures
                      : num_captures + kAdditionalArgsWithoutNamedCaptures;
  static_assert(Code::kMaxArguments < std::numeric_limits<uint32_t>::max() -
                                          kAdditionalArgsWithNamedCaptures);
  return (argc > Code::kMaxArguments) ? -1 : argc;
}
References v8::internal::Code::kMaxArguments.
Referenced by v8::internal::RUNTIME_FUNCTION().
GetRewoundRegexpIndicesList()
std::vector<int>* v8::internal::anonymous_namespace{runtime-regexp.cc}::GetRewoundRegexpIndicesList (Isolate * isolate)
Definition at line 549 of file runtime-regexp.cc.
                                                              {
  std::vector<int>* list = isolate->regexp_indices();
  list->clear();
  return list;
}
References v8::internal::Isolate::regexp_indices().
Referenced by v8::internal::RUNTIME_FUNCTION(), and v8::internal::StringReplaceGlobalAtomRegExpWithString().
IsContainFlag()
bool v8::internal::anonymous_namespace{runtime-regexp.cc}::IsContainFlag (Isolate * isolate, String::FlatContent & flags, const char * target, DisallowGarbageCollection & no_gc) [inline]
Definition at line 1895 of file runtime-regexp.cc.
                                                            {
  return flags.IsOneByte()
             ? IsContainFlagImpl<uint8_t>(isolate, flags.ToOneByteVector(),
                                          target, no_gc)
             : IsContainFlagImpl<base::uc16>(isolate, flags.ToUC16Vector(),
                                             target, no_gc);
}
References v8::internal::flags, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::internal::RUNTIME_FUNCTION().
IsContainFlagImpl()
template<typename Char >
bool v8::internal::anonymous_namespace{runtime-regexp.cc}::IsContainFlagImpl (Isolate * isolate, base::Vector< const Char > flags, const char * target, DisallowGarbageCollection & no_gc) [inline]
Definition at line 1888 of file runtime-regexp.cc.
                                                                {
  StringSearch<uint8_t, Char> search(isolate, base::OneByteVector(target));
  return search.Search(flags, 0) >= 0;
}
References v8::internal::flags, v8::base::OneByteVector(), and v8::internal::anonymous_namespace{simd.cc}::search().
LookupNamedCapture()
template<typename Matcher , typename = std::enable_if<std::is_invocable_r_v< bool, Matcher, Tagged<String>>>>
int v8::internal::anonymous_namespace{runtime-regexp.cc}::LookupNamedCapture (Matcher name_matches, Tagged< FixedArray > capture_name_map, int * index_in_out)
Definition at line 59 of file runtime-regexp.cc.
                                                                               {
  DCHECK_GE(*index_in_out, 0);
  // TODO(jgruber): Sort capture_name_map and do binary search via
  // internalized strings.
  int maybe_capture_index = -1;
  const int named_capture_count = capture_name_map->length() >> 1;
  DCHECK_LE(*index_in_out, named_capture_count);
  for (int j = *index_in_out; j < named_capture_count; j++) {
    // The format of {capture_name_map} is documented at
    // JSRegExp::kIrregexpCaptureNameMapIndex.
    const int name_ix = j * 2;
    const int index_ix = j * 2 + 1;
    Tagged<String> capture_name = Cast<String>(capture_name_map->get(name_ix));
    if (!name_matches(capture_name)) continue;
    maybe_capture_index = Smi::ToInt(capture_name_map->get(index_ix));
    *index_in_out = j + 1;
    break;
  }
  return maybe_capture_index;
}
References DCHECK_GE, DCHECK_LE, and v8::internal::Smi::ToInt().
Referenced by v8::internal::anonymous_namespace{runtime-regexp.cc}::MatchInfoBackedMatch::GetNamedCapture(), and v8::internal::CompiledReplacement::ParseReplacementPattern().
NewJSArrayWithElements()
DirectHandle<JSArray> v8::internal::anonymous_namespace{runtime-regexp.cc}::NewJSArrayWithElements (Isolate * isolate, DirectHandle< FixedArray > elems, int num_elems)
Definition at line 1722 of file runtime-regexp.cc.
                                                            {
  return isolate->factory()->NewJSArrayWithElements(
      FixedArray::RightTrimOrEmpty(isolate, elems, num_elems));
}
References v8::internal::Isolate::factory(), and v8::internal::Factory::NewJSArrayWithElements().
Referenced by v8::internal::RUNTIME_FUNCTION().
RegExpExec()
std::optional<int> v8::internal::anonymous_namespace{runtime-regexp.cc}::RegExpExec (Isolate * isolate, DirectHandle< JSRegExp > regexp, DirectHandle< String > subject, int32_t index, int32_t * result_offsets_vector, uint32_t result_offsets_vector_length)
Definition at line 925 of file runtime-regexp.cc.
                                                                     {
  // Due to the way the JS calls are constructed this must be less than the
  // length of a string, i.e. it is always a Smi. We check anyway for security.
  CHECK_LE(0, index);
  CHECK_GE(subject->length(), index);
  isolate->counters()->regexp_entry_runtime()->Increment();
  return RegExp::Exec(isolate, regexp, subject, index, result_offsets_vector,
                      result_offsets_vector_length);
}
References CHECK_GE, CHECK_LE, v8::internal::Isolate::counters(), v8::internal::RegExp::Exec(), and v8::internal::index.
Referenced by v8::internal::RUNTIME_FUNCTION().
RegExpMatchGlobalAtom_Dispatch()
void v8::internal::anonymous_namespace{runtime-regexp.cc}::RegExpMatchGlobalAtom_Dispatch (Isolate * isolate, const String::FlatContent & subject, const String::FlatContent & pattern, bool is_unicode, int start_index, int * number_of_matches, int * last_match_index, const DisallowGarbageCollection & no_gc) [inline]
Definition at line 2307 of file runtime-regexp.cc.
                                            {
#define CALL_Generic() \
  RegExpMatchGlobalAtom_Generic(isolate, sv, pv, is_unicode, start_index, \
                                number_of_matches, last_match_index, no_gc);
#define CALL_OneCharPattern() \
  RegExpMatchGlobalAtom_OneCharPattern(isolate, sv, pv[0], start_index, \
                                       number_of_matches, last_match_index, \
                                       no_gc);
  DCHECK_NOT_NULL(number_of_matches);
  DCHECK_NOT_NULL(last_match_index);
  if (pattern.IsOneByte()) {
    auto pv = pattern.ToOneByteVector();
    if (subject.IsOneByte()) {
      auto sv = subject.ToOneByteVector();
      if (pattern.length() == 1) {
        CALL_OneCharPattern();
      } else {
        CALL_Generic();
      }
    } else {
      auto sv = subject.ToUC16Vector();
      if (pattern.length() == 1) {
        CALL_OneCharPattern();
      } else {
        CALL_Generic();
      }
    }
  } else {
    auto pv = pattern.ToUC16Vector();
    if (subject.IsOneByte()) {
      auto sv = subject.ToOneByteVector();
      CALL_Generic();
    } else {
      auto sv = subject.ToUC16Vector();
      if (pattern.length() == 1) {
        CALL_OneCharPattern();
      } else {
        CALL_Generic();
      }
    }
  }
#undef CALL_OneCharPattern
#undef CALL_Generic
}
References CALL_Generic, CALL_OneCharPattern, DCHECK_NOT_NULL, v8::internal::String::FlatContent::IsOneByte(), v8::internal::String::FlatContent::length(), v8::internal::String::FlatContent::ToOneByteVector(), and v8::internal::String::FlatContent::ToUC16Vector().
Referenced by v8::internal::RUNTIME_FUNCTION().
RegExpMatchGlobalAtom_Generic()
template<typename SChar , typename PChar >
void v8::internal::anonymous_namespace{runtime-regexp.cc}::RegExpMatchGlobalAtom_Generic (Isolate * isolate, base::Vector< const SChar > subject, base::Vector< const PChar > pattern, bool is_unicode, int start_index, int * number_of_matches, int * last_match_index, const DisallowGarbageCollection & no_gc) [inline]
Definition at line 2286 of file runtime-regexp.cc.
                                            {
  const int pattern_length = pattern.length();
  StringSearch<PChar, SChar> search(isolate, pattern);
  int found_at_index;
  while (true) {
    found_at_index = search.Search(subject, start_index);
    if (found_at_index == -1) return;
    (*number_of_matches)++;
    (*last_match_index) = found_at_index;
    start_index = pattern_length > 0
                      ? found_at_index + pattern_length
                      : AdvanceStringIndex(subject, start_index, is_unicode);
  }
}
References AdvanceStringIndex(), v8::base::Vector< T >::length(), and v8::internal::anonymous_namespace{simd.cc}::search().
RegExpMatchGlobalAtom_OneCharPattern() [1/2]
template<typename SChar , typename PChar >
void v8::internal::anonymous_namespace{runtime-regexp.cc}::RegExpMatchGlobalAtom_OneCharPattern (Isolate * isolate, base::Vector< const SChar > subject, const PChar pattern, int start_index, int * number_of_matches, int * last_match_index, const DisallowGarbageCollection & no_gc) [inline]
Definition at line 2165 of file runtime-regexp.cc.
                                            {
  static_assert(std::is_unsigned_v<SChar>);
  static_assert(std::is_unsigned_v<PChar>);
  // We can utilize SIMD to check multiple characters at once.
  // Since the pattern is a single char, we create a mask setting each lane in
  // the vector to the pattern char.
  // Since reductions from a vector to a general purpose register (i.e.
  // ReduceSum in this algorithm) are expensive, we keep a count for each lane
  // in a vector until the count could potentially overflow and only reduce to
  // a general purpose register then. I.e. if SChar is uint8_t, we have a
  // 16xuint8_t vector to count matches, which we reduce to an int every 255
  // blocks.
  namespace hw = hwy::HWY_NAMESPACE;
  hw::ScalableTag<SChar> tag;
  // We need a wider tag to avoid overflows on lanes when summing up submatches.
  using WidenedTag = hw::RepartitionToWide<decltype(tag)>;
  WidenedTag sum_tag;
  static constexpr size_t stride = hw::Lanes(tag);
  // Subtle: the valid variants are {SChar,PChar} in:
  // {uint8_t,uint8_t}, {uc16,uc16}, {uc16,uint8_t}. In the latter case,
  // we cast the uint8_t pattern to uc16 for the comparison.
  const auto mask = hw::Set(tag, static_cast<const SChar>(pattern));
  int matches = 0;
  auto submatches = hw::Zero(tag);
  const SChar* last_match_block = nullptr;
  hw::Mask<decltype(tag)> last_match_vec;
  const SChar* block = subject.data() + start_index;
  const SChar* end = subject.data() + subject.length();
  // ReduceSum is expensive, so we gather matches into a vector. max_count is
  // the maximum number of matches we can count in the vector before it
  // overflows.
  int max_count = std::numeric_limits<SChar>::max();
  while (block + stride * max_count <= end) {
    for (int i = 0; i < max_count; i++, block += stride) {
      const auto input = hw::LoadU(tag, block);
      const auto match = input == mask;
      // Lanes with matches have all bits set, so we subtract to increase the
      // count by 1.
      submatches = hw::Sub(submatches, hw::VecFromMask(tag, match));
      if (!hw::AllFalse(tag, match)) {
        last_match_block = block;
        last_match_vec = match;
      }
    }
    // SumsOf2 promotes the sum of 2 consecutive lanes into a wider lane.
    auto promoted_submatches = hw::SumsOf2(submatches);
    // Wider lane sums can be reduces without overflows.
    matches += hw::ReduceSum(sum_tag, promoted_submatches);
    submatches = hw::Zero(tag);
  }
  // For blocks shorter than stride * max_count, lanes in submatches can't
  // overflow.
  DCHECK_LT(end - block, stride * max_count);
  for (; block + stride <= end; block += stride) {
    const auto input = hw::LoadU(tag, block);
    const auto match = input == mask;
    submatches = hw::Sub(submatches, hw::VecFromMask(tag, match));
    if (!hw::AllFalse(tag, match)) {
      last_match_block = block;
      last_match_vec = match;
    }
  }
  auto promoted_submatches = hw::SumsOf2(submatches);
  matches += hw::ReduceSum(sum_tag, promoted_submatches);
  // Handle remaining chars.
  // last_match_block already contains the last match position, so use a special
  // vector with lane 0 set to extract the last_match_index later.
  const auto scalar_last_match_vec = hw::FirstN(tag, 1);
  for (SChar c = *block; block < end; c = *(++block)) {
    if (c != static_cast<const SChar>(pattern)) continue;
    matches++;
    last_match_block = block;
    last_match_vec = scalar_last_match_vec;
  }
  // Store results.
  *number_of_matches += matches;
  if (last_match_block != nullptr) {
    DCHECK(!hw::AllFalse(tag, last_match_vec));
    *last_match_index = static_cast<int>(
        last_match_block + hw::FindKnownLastTrue(tag, last_match_vec) -
        subject.data());
  }
}
References v8::base::Vector< T >::data(), v8::internal::DCHECK(), DCHECK_LT, v8::internal::compiler::end(), v8::base::Vector< T >::length(), v8::internal::Mask, v8::internal::anonymous_namespace{json-stringifier.cc}::stride, and v8::internal::wasm::liftoff::Sub().
RegExpMatchGlobalAtom_OneCharPattern() [2/2]
template<>
void v8::internal::anonymous_namespace{runtime-regexp.cc}::RegExpMatchGlobalAtom_OneCharPattern (Isolate * isolate, base::Vector< const uint8_t > subject, const base::uc16 pattern, int start_index, int * number_of_matches, int * last_match_index, const DisallowGarbageCollection & no_gc) [inline], [delete]
RegExpReplace()
V8_WARN_UNUSED_RESULT MaybeDirectHandle<String> v8::internal::anonymous_namespace{runtime-regexp.cc}::RegExpReplace (Isolate * isolate, DirectHandle< JSRegExp > regexp, DirectHandle< String > string, DirectHandle< String > replace)
Definition at line 1439 of file runtime-regexp.cc.
                                                               {
  // Functional fast-paths are dispatched directly by replace builtin.
  DCHECK(RegExpUtils::IsUnmodifiedRegExp(isolate, regexp));
  Factory* factory = isolate->factory();
  const int flags = regexp->flags();
  const bool global = (flags & JSRegExp::kGlobal) != 0;
  const bool sticky = (flags & JSRegExp::kSticky) != 0;
  replace = String::Flatten(isolate, replace);
  DirectHandle<RegExpMatchInfo> last_match_info =
      isolate->regexp_last_match_info();
  DirectHandle<RegExpData> data(regexp->data(isolate), isolate);
  if (!global) {
    // Non-global regexp search, string replace.
    uint32_t last_index = 0;
    if (sticky) {
      DirectHandle<Object> last_index_obj(regexp->last_index(), isolate);
      ASSIGN_RETURN_ON_EXCEPTION(isolate, last_index_obj,
                                 Object::ToLength(isolate, last_index_obj));
      last_index = PositiveNumberToUint32(*last_index_obj);
    }
    DirectHandle<Object> match_indices_obj(ReadOnlyRoots(isolate).null_value(),
                                           isolate);
    // A lastIndex exceeding the string length always returns null (signalling
    // failure) in RegExpBuiltinExec, thus we can skip the call.
    if (last_index <= static_cast<uint32_t>(string->length())) {
      ASSIGN_RETURN_ON_EXCEPTION(
          isolate, match_indices_obj,
          RegExp::Exec_Single(isolate, regexp, string, last_index,
                              last_match_info));
    }
    if (IsNull(*match_indices_obj, isolate)) {
      if (sticky) regexp->set_last_index(Smi::zero(), SKIP_WRITE_BARRIER);
      return string;
    }
    auto match_indices = Cast<RegExpMatchInfo>(match_indices_obj);
    const int start_index = match_indices->capture(0);
    const int end_index = match_indices->capture(1);
    if (sticky) {
      regexp->set_last_index(Smi::FromInt(end_index), SKIP_WRITE_BARRIER);
    }
    IncrementalStringBuilder builder(isolate);
    builder.AppendString(factory->NewSubString(string, 0, start_index));
    if (replace->length() > 0) {
      MatchInfoBackedMatch m(isolate, regexp, data, string, match_indices);
      DirectHandle<String> replacement;
      ASSIGN_RETURN_ON_EXCEPTION(isolate, replacement,
                                 String::GetSubstitution(isolate, &m, replace));
      builder.AppendString(replacement);
    }
    builder.AppendString(
        factory->NewSubString(string, end_index, string->length()));
    return builder.Finish();
  } else {
    // Global regexp search, string replace.
    DCHECK(global);
    RETURN_ON_EXCEPTION(isolate, RegExpUtils::SetLastIndex(isolate, regexp, 0));
    // Force tier up to native code for global replaces. The global replace is
    // implemented differently for native code and bytecode execution, where the
    // native code expects an array to store all the matches, and the bytecode
    // matches one at a time, so it's easier to tier-up to native code from the
    // start.
    if (v8_flags.regexp_tier_up &&
        data->type_tag() == RegExpData::Type::IRREGEXP) {
      Cast<IrRegExpData>(data)->MarkTierUpForNextExec();
      if (v8_flags.trace_regexp_tier_up) {
        PrintF("Forcing tier-up of JSRegExp object %p in RegExpReplace\n",
               reinterpret_cast<void*>(regexp->ptr()));
      }
    }
    if (replace->length() == 0) {
      if (string->IsOneByteRepresentation()) {
        Tagged<Object> result =
            StringReplaceGlobalRegExpWithEmptyString<SeqOneByteString>(
                isolate, string, regexp, data, last_match_info);
        return direct_handle(Cast<String>(result), isolate);
      } else {
        Tagged<Object> result =
            StringReplaceGlobalRegExpWithEmptyString<SeqTwoByteString>(
                isolate, string, regexp, data, last_match_info);
        return direct_handle(Cast<String>(result), isolate);
      }
    }
    Tagged<Object> result = StringReplaceGlobalRegExpWithString(
        isolate, string, regexp, data, replace, last_match_info);
    if (IsString(result)) {
      return direct_handle(Cast<String>(result), isolate);
    } else {
      return MaybeDirectHandle<String>();
    }
  }
  UNREACHABLE();
}
References v8::internal::IncrementalStringBuilder::AppendString(), ASSIGN_RETURN_ON_EXCEPTION, v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::RegExp::Exec_Single(), v8::internal::Isolate::factory(), v8::internal::IncrementalStringBuilder::Finish(), v8::internal::flags, v8::internal::Smi::FromInt(), v8::internal::String::GetSubstitution(), v8::internal::RegExpData::IRREGEXP, v8::internal::IsNull(), v8::internal::RegExpUtils::IsUnmodifiedRegExp(), v8::internal::PositiveNumberToUint32(), v8::internal::PrintF(), v8::base::internal::result, RETURN_ON_EXCEPTION, v8::internal::RegExpUtils::SetLastIndex(), v8::internal::SKIP_WRITE_BARRIER, v8::internal::string, v8::internal::StringReplaceGlobalRegExpWithString(), v8::internal::Object::ToLength(), v8::internal::UNREACHABLE(), v8::internal::v8_flags, and v8::internal::Smi::zero().
Referenced by v8::internal::RUNTIME_FUNCTION().
SearchRegExpMultiple()
template<bool has_capture>
static Tagged<Object> v8::internal::anonymous_namespace{runtime-regexp.cc}::SearchRegExpMultiple (Isolate * isolate, DirectHandle< String > subject, DirectHandle< JSRegExp > regexp, DirectHandle< RegExpData > regexp_data, DirectHandle< RegExpMatchInfo > last_match_array) [static]
Definition at line 1256 of file runtime-regexp.cc.
                                                    {
  DCHECK(RegExpUtils::IsUnmodifiedRegExp(isolate, regexp));
  DCHECK_NE(has_capture, regexp_data->capture_count() == 0);
  DCHECK_IMPLIES(has_capture, Is<IrRegExpData>(*regexp_data));
  DCHECK(subject->IsFlat());
  // Force tier up to native code for global replaces. The global replace is
  // implemented differently for native code and bytecode execution, where the
  // native code expects an array to store all the matches, and the bytecode
  // matches one at a time, so it's easier to tier-up to native code from the
  // start.
  if (v8_flags.regexp_tier_up &&
      regexp_data->type_tag() == RegExpData::Type::IRREGEXP) {
    Cast<IrRegExpData>(regexp_data)->MarkTierUpForNextExec();
    if (v8_flags.trace_regexp_tier_up) {
      PrintF("Forcing tier-up of JSRegExp object %p in SearchRegExpMultiple\n",
             reinterpret_cast<void*>(regexp->ptr()));
    }
  }
  int capture_count = regexp_data->capture_count();
  int subject_length = subject->length();
  static const int kMinLengthToCache = 0x1000;
  if (subject_length > kMinLengthToCache) {
    Tagged<FixedArray> last_match_cache;
    Tagged<Object> cached_answer = RegExpResultsCache::Lookup(
        isolate->heap(), *subject, regexp_data->wrapper(), &last_match_cache,
        RegExpResultsCache::REGEXP_MULTIPLE_INDICES);
    if (IsFixedArray(cached_answer)) {
      int capture_registers = JSRegExp::RegistersForCaptureCount(capture_count);
      std::unique_ptr<int32_t[]> last_match(new int32_t[capture_registers]);
      int32_t* raw_last_match = last_match.get();
      for (int i = 0; i < capture_registers; i++) {
        raw_last_match[i] = Smi::ToInt(last_match_cache->get(i));
      }
      DirectHandle<FixedArray> cached_fixed_array(
          Cast<FixedArray>(cached_answer), isolate);
      // The cache FixedArray is a COW-array and we need to return a copy.
      DirectHandle<FixedArray> copied_fixed_array =
          isolate->factory()->CopyFixedArrayWithMap(
              cached_fixed_array, isolate->factory()->fixed_array_map());
      RegExp::SetLastMatchInfo(isolate, last_match_array, subject,
                               capture_count, raw_last_match);
      return *copied_fixed_array;
    }
  }
  RegExpGlobalExecRunner runner(direct_handle(*regexp_data, isolate), subject,
                                isolate);
  if (runner.HasException()) return ReadOnlyRoots(isolate).exception();
  FixedArrayBuilder builder = FixedArrayBuilder::Lazy(isolate);
  // Position to search from.
  int match_start = -1;
  int match_end = 0;
  bool first = true;
  // Two smis before and after the match, for very long strings.
  static const int kMaxBuilderEntriesPerRegExpMatch = 5;
  while (true) {
    int32_t* current_match = runner.FetchNext();
    if (current_match == nullptr) break;
    match_start = current_match[0];
    builder.EnsureCapacity(isolate, kMaxBuilderEntriesPerRegExpMatch);
    if (match_end < match_start) {
      ReplacementStringBuilder::AddSubjectSlice(&builder, match_end,
                                                match_start);
    }
    match_end = current_match[1];
    {
      // Avoid accumulating new handles inside loop.
      HandleScope temp_scope(isolate);
      DirectHandle<String> match;
      if (!first) {
        match = isolate->factory()->NewProperSubString(subject, match_start,
                                                       match_end);
      } else {
        match =
            isolate->factory()->NewSubString(subject, match_start, match_end);
        first = false;
      }
      if (has_capture) {
        // Arguments array to replace function is match, captures, index and
        // subject, i.e., 3 + capture count in total. If the RegExp contains
        // named captures, they are also passed as the last argument.
        // has_capture can only be true for IrRegExp.
        Tagged<IrRegExpData> re_data = Cast<IrRegExpData>(*regexp_data);
        DirectHandle<Object> maybe_capture_map(re_data->capture_name_map(),
                                               isolate);
        const bool has_named_captures = IsFixedArray(*maybe_capture_map);
        const int argc =
            has_named_captures ? 4 + capture_count : 3 + capture_count;
        DirectHandle<FixedArray> elements =
            isolate->factory()->NewFixedArray(argc);
        int cursor = 0;
        elements->set(cursor++, *match);
        for (int i = 1; i <= capture_count; i++) {
          int start = current_match[i * 2];
          if (start >= 0) {
            int end = current_match[i * 2 + 1];
            DCHECK(start <= end);
            DirectHandle<String> substring =
                isolate->factory()->NewSubString(subject, start, end);
            elements->set(cursor++, *substring);
          } else {
            DCHECK_GT(0, current_match[i * 2 + 1]);
            elements->set(cursor++, ReadOnlyRoots(isolate).undefined_value());
          }
        }
        elements->set(cursor++, Smi::FromInt(match_start));
        elements->set(cursor++, *subject);
        if (has_named_captures) {
          DirectHandle<FixedArray> capture_map =
              Cast<FixedArray>(maybe_capture_map);
          DirectHandle<JSObject> groups = ConstructNamedCaptureGroupsObject(
              isolate, capture_map, [=](int ix) { return elements->get(ix); });
          elements->set(cursor++, *groups);
        }
        DCHECK_EQ(cursor, argc);
        builder.Add(*isolate->factory()->NewJSArrayWithElements(elements));
      } else {
        builder.Add(*match);
      }
    }
  }
  if (runner.HasException()) return ReadOnlyRoots(isolate).exception();
  if (match_start >= 0) {
    // Finished matching, with at least one match.
    if (match_end < subject_length) {
      ReplacementStringBuilder::AddSubjectSlice(&builder, match_end,
                                                subject_length);
    }
    RegExp::SetLastMatchInfo(isolate, last_match_array, subject, capture_count,
                             runner.LastSuccessfulMatch());
    if (subject_length > kMinLengthToCache) {
      // Store the last successful match into the array for caching.
      int capture_registers = JSRegExp::RegistersForCaptureCount(capture_count);
      DirectHandle<FixedArray> last_match_cache =
          isolate->factory()->NewFixedArray(capture_registers);
      int32_t* last_match = runner.LastSuccessfulMatch();
      for (int i = 0; i < capture_registers; i++) {
        last_match_cache->set(i, Smi::FromInt(last_match[i]));
      }
      DirectHandle<FixedArray> result_fixed_array =
          FixedArray::RightTrimOrEmpty(isolate, builder.array(),
                                       builder.length());
      // Cache the result and copy the FixedArray into a COW array.
      DirectHandle<FixedArray> copied_fixed_array =
          isolate->factory()->CopyFixedArrayWithMap(
              result_fixed_array, isolate->factory()->fixed_array_map());
      RegExpResultsCache::Enter(
          isolate, subject,
          direct_handle(regexp->data(isolate)->wrapper(), isolate),
          copied_fixed_array, last_match_cache,
          RegExpResultsCache::REGEXP_MULTIPLE_INDICES);
    }
    return *builder.array();
  } else {
    return ReadOnlyRoots(isolate).null_value(); // No matches at all.
  }
}
References v8::internal::FixedArrayBuilder::Add(), v8::internal::ReplacementStringBuilder::AddSubjectSlice(), v8::internal::FixedArrayBuilder::array(), ConstructNamedCaptureGroupsObject(), v8::internal::Factory::CopyFixedArrayWithMap(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GT, DCHECK_IMPLIES, DCHECK_NE, v8::internal::direct_handle(), v8::internal::compiler::end(), v8::internal::FixedArrayBuilder::EnsureCapacity(), v8::internal::RegExpResultsCache::Enter(), v8::internal::Isolate::factory(), v8::internal::RegExpGlobalExecRunner::FetchNext(), v8::internal::Smi::FromInt(), v8::internal::RegExpGlobalExecRunner::HasException(), v8::internal::Isolate::heap(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::RegExpData::IRREGEXP, v8::internal::RegExpUtils::IsUnmodifiedRegExp(), v8::internal::RegExpGlobalExecRunner::LastSuccessfulMatch(), v8::internal::FixedArrayBuilder::Lazy(), v8::internal::FixedArrayBuilder::length(), v8::internal::RegExpResultsCache::Lookup(), v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::Factory::NewJSArrayWithElements(), v8::internal::Factory::NewProperSubString(), v8::internal::PrintF(), v8::internal::RegExpResultsCache::REGEXP_MULTIPLE_INDICES, v8::internal::JSRegExp::RegistersForCaptureCount(), v8::internal::RegExp::SetLastMatchInfo(), v8::internal::Smi::ToInt(), and v8::internal::v8_flags.
ToUint32()
V8_WARN_UNUSED_RESULT MaybeDirectHandle<Object> v8::internal::anonymous_namespace{runtime-regexp.cc}::ToUint32 (Isolate * isolate, DirectHandle< Object > object, uint32_t * out)
Definition at line 1708 of file runtime-regexp.cc.
                                                                  {
  if (IsUndefined(*object, isolate)) {
    *out = kMaxUInt32;
    return object;
  }
  DirectHandle<Object> number;
  ASSIGN_RETURN_ON_EXCEPTION(isolate, number,
                             Object::ToNumber(isolate, object));
  *out = NumberToUint32(*number);
  return object;
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::kMaxUInt32, v8::internal::NumberToUint32(), and v8::Value::ToNumber().
Referenced by v8::internal::RUNTIME_FUNCTION(), and v8::internal::TF_BUILTIN().
TruncateRegexpIndicesList()
void v8::internal::anonymous_namespace{runtime-regexp.cc}::TruncateRegexpIndicesList (Isolate * isolate)
Definition at line 555 of file runtime-regexp.cc.
                                                 {
  // Same size as smallest zone segment, preserving behavior from the
  // runtime zone.
  // TODO(jgruber): Consider removing the reusable regexp_indices list and
  // simply allocating a new list each time. It feels like we're needlessly
  // optimizing an edge case.
  static const int kMaxRegexpIndicesListCapacity = 8 * KB / kIntSize;
  std::vector<int>* indices = isolate->regexp_indices();
  if (indices->capacity() > kMaxRegexpIndicesListCapacity) {
    // Throw away backing storage.
    indices->clear();
    indices->shrink_to_fit();
  }
}
References v8::internal::KB, v8::internal::kIntSize, and v8::internal::Isolate::regexp_indices().
Referenced by v8::internal::RUNTIME_FUNCTION(), and v8::internal::StringReplaceGlobalAtomRegExpWithString().
Variable Documentation
kStaticVectorSlots
constexpr int v8::internal::anonymous_namespace{runtime-regexp.cc}::kStaticVectorSlots = 8 [constexpr]
Definition at line 36 of file runtime-regexp.cc.