v8_inspector::anonymous_namespace{v8-console-message.cc} Namespace Reference
Classes
class V8ValueStringBuilder
Functions
String16 consoleAPITypeValue (ConsoleAPIType type)
void TraceV8ConsoleMessageEvent (V8MessageOrigin origin, ConsoleAPIType type)
Variables
const char kGlobalConsoleMessageHandleLabel [] = `DevTools console`
const unsigned maxConsoleMessageCount = 1000
const int maxConsoleMessageV8Size = 10 * 1024 * 1024
const unsigned maxArrayItemsLimit = 10000
const unsigned maxStackDepthLimit = 32
Function Documentation
consoleAPITypeValue()
String16 v8_inspector::anonymous_namespace{v8-console-message.cc}::consoleAPITypeValue (ConsoleAPIType type)
Definition at line 28 of file v8-console-message.cc.
                                                  {
  switch (type) {
    case ConsoleAPIType::kLog:
      return protocol::Runtime::ConsoleAPICalled::TypeEnum::Log;
    case ConsoleAPIType::kDebug:
      return protocol::Runtime::ConsoleAPICalled::TypeEnum::Debug;
    case ConsoleAPIType::kInfo:
      return protocol::Runtime::ConsoleAPICalled::TypeEnum::Info;
    case ConsoleAPIType::kError:
      return protocol::Runtime::ConsoleAPICalled::TypeEnum::Error;
    case ConsoleAPIType::kWarning:
      return protocol::Runtime::ConsoleAPICalled::TypeEnum::Warning;
    case ConsoleAPIType::kClear:
      return protocol::Runtime::ConsoleAPICalled::TypeEnum::Clear;
    case ConsoleAPIType::kDir:
      return protocol::Runtime::ConsoleAPICalled::TypeEnum::Dir;
    case ConsoleAPIType::kDirXML:
      return protocol::Runtime::ConsoleAPICalled::TypeEnum::Dirxml;
    case ConsoleAPIType::kTable:
      return protocol::Runtime::ConsoleAPICalled::TypeEnum::Table;
    case ConsoleAPIType::kTrace:
      return protocol::Runtime::ConsoleAPICalled::TypeEnum::Trace;
    case ConsoleAPIType::kStartGroup:
      return protocol::Runtime::ConsoleAPICalled::TypeEnum::StartGroup;
    case ConsoleAPIType::kStartGroupCollapsed:
      return protocol::Runtime::ConsoleAPICalled::TypeEnum::StartGroupCollapsed;
    case ConsoleAPIType::kEndGroup:
      return protocol::Runtime::ConsoleAPICalled::TypeEnum::EndGroup;
    case ConsoleAPIType::kAssert:
      return protocol::Runtime::ConsoleAPICalled::TypeEnum::Assert;
    case ConsoleAPIType::kTimeEnd:
      return protocol::Runtime::ConsoleAPICalled::TypeEnum::TimeEnd;
    case ConsoleAPIType::kCount:
      return protocol::Runtime::ConsoleAPICalled::TypeEnum::Count;
  }
  return protocol::Runtime::ConsoleAPICalled::TypeEnum::Log;
}
References v8::internal::torque::Error(), v8_inspector::kAssert, v8_inspector::kClear, v8_inspector::kCount, v8_inspector::kDebug, v8_inspector::kDir, v8_inspector::kDirXML, v8_inspector::kEndGroup, v8_inspector::kError, v8_inspector::kInfo, v8_inspector::kLog, v8_inspector::kStartGroup, v8_inspector::kStartGroupCollapsed, v8_inspector::kTable, v8_inspector::kTimeEnd, v8_inspector::kTrace, v8_inspector::kWarning, and v8::internal::tracing::type.
Referenced by v8_inspector::V8ConsoleMessage::reportToFrontend().
TraceV8ConsoleMessageEvent()
void v8_inspector::anonymous_namespace{v8-console-message.cc}::TraceV8ConsoleMessageEvent (V8MessageOrigin origin, ConsoleAPIType type)
Definition at line 558 of file v8-console-message.cc.
                                                                             {
  // Change in this function requires adjustment of Catapult/Telemetry metric
  // tracing/tracing/metrics/console_error_metric.html.
  // See https://crbug.com/880432
  if (origin == V8MessageOrigin::kException) {
    TRACE_EVENT_INSTANT0("v8.console", "V8ConsoleMessage::Exception",
                         TRACE_EVENT_SCOPE_THREAD);
  } else if (type == ConsoleAPIType::kError) {
    TRACE_EVENT_INSTANT0("v8.console", "V8ConsoleMessage::Error",
                         TRACE_EVENT_SCOPE_THREAD);
  } else if (type == ConsoleAPIType::kAssert) {
    TRACE_EVENT_INSTANT0("v8.console", "V8ConsoleMessage::Assert",
                         TRACE_EVENT_SCOPE_THREAD);
  }
}
References v8_inspector::kAssert, v8_inspector::kError, v8_inspector::kException, TRACE_EVENT_INSTANT0, TRACE_EVENT_SCOPE_THREAD, and v8::internal::tracing::type.
Referenced by v8_inspector::V8ConsoleMessageStorage::addMessage().
Variable Documentation
kGlobalConsoleMessageHandleLabel
const char v8_inspector::anonymous_namespace{v8-console-message.cc}::kGlobalConsoleMessageHandleLabel[] = `DevTools console`
Definition at line 66 of file v8-console-message.cc.
Referenced by v8_inspector::V8ConsoleMessage::createForConsoleAPI().
maxArrayItemsLimit
const unsigned v8_inspector::anonymous_namespace{v8-console-message.cc}::maxArrayItemsLimit = 10000
Definition at line 69 of file v8-console-message.cc.
maxConsoleMessageCount
const unsigned v8_inspector::anonymous_namespace{v8-console-message.cc}::maxConsoleMessageCount = 1000
Definition at line 67 of file v8-console-message.cc.
Referenced by v8_inspector::V8ConsoleMessageStorage::addMessage().
maxConsoleMessageV8Size
const int v8_inspector::anonymous_namespace{v8-console-message.cc}::maxConsoleMessageV8Size = 10 * 1024 * 1024
Definition at line 68 of file v8-console-message.cc.
Referenced by v8_inspector::V8ConsoleMessageStorage::addMessage().
maxStackDepthLimit
const unsigned v8_inspector::anonymous_namespace{v8-console-message.cc}::maxStackDepthLimit = 32
Definition at line 70 of file v8-console-message.cc.
Referenced by v8_inspector::anonymous_namespace{v8-console-message.cc}::V8ValueStringBuilder::append().