v8::internal::anonymous_namespace{futex-emulation.cc} Namespace Reference
Functions
Tagged< Object > WaitJsTranslateReturn (Isolate *isolate, Tagged< Object > res)
template<typename T >
Global< T > GetWeakGlobal (Isolate *isolate, Local< T > object)
Function Documentation
GetWeakGlobal()
template<typename T >
Global<T> v8::internal::anonymous_namespace{futex-emulation.cc}::GetWeakGlobal (Isolate * isolate, Local< T > object)
Definition at line 480 of file futex-emulation.cc.
                                                           {
  auto* v8_isolate = reinterpret_cast<v8::Isolate*>(isolate);
  v8::Global<T> global{v8_isolate, object};
  global.SetWeak();
  return global;
}
References v8::PersistentBase< T >::SetWeak().
WaitJsTranslateReturn()
Tagged<Object> v8::internal::anonymous_namespace{futex-emulation.cc}::WaitJsTranslateReturn (Isolate * isolate, Tagged< Object > res)
Definition at line 268 of file futex-emulation.cc.
                                                                           {
  if (IsSmi(res)) {
    int val = Smi::ToInt(res);
    switch (val) {
      case WaitReturnValue::kOk:
        return ReadOnlyRoots(isolate).ok_string();
      case WaitReturnValue::kNotEqualValue:
        return ReadOnlyRoots(isolate).not_equal_string();
      case WaitReturnValue::kTimedOut:
        return ReadOnlyRoots(isolate).timed_out_string();
      default:
        UNREACHABLE();
    }
  }
  return res;
}
References v8::internal::IsSmi(), v8::internal::kNotEqualValue, v8::internal::kOk, v8::internal::kTimedOut, v8::internal::Smi::ToInt(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::FutexEmulation::WaitJs32(), and v8::internal::FutexEmulation::WaitJs64().