v8::internal::wasm::anonymous_namespace{module-instantiate.cc} Namespace Reference
Classes
class WriteOutPGOTask
Enumerations
enum class ReceiverKind { kFirstParamIsReceiver
, kAnyReceiver
 }
enum FunctionComputationMode { kLazyFunctionsAndNull
, kStrictFunctionsAndNull
 }
Functions
uint8_t * raw_buffer_ptr (MaybeDirectHandle< JSArrayBuffer > buffer, int offset)
bool CompareWithNormalizedCType (const CTypeInfo &info, CanonicalValueType expected, CFunctionInfo::Int64Representation int64_rep)
bool IsSupportedWasmFastApiFunction (Isolate *isolate, const wasm::CanonicalSig *expected_sig, Tagged< SharedFunctionInfo > shared, ReceiverKind receiver_kind, int *out_index)
bool ResolveBoundJSFastApiFunction (const wasm::CanonicalSig *expected_sig, DirectHandle< JSReceiver > callable)
bool IsStringRef (wasm::CanonicalValueType type)
bool IsExternRef (wasm::CanonicalValueType type)
bool IsStringOrExternRef (wasm::CanonicalValueType type)
bool IsDataViewGetterSig (const wasm::CanonicalSig *sig, wasm::CanonicalValueType return_type)
bool IsDataViewSetterSig (const wasm::CanonicalSig *sig, wasm::CanonicalValueType value_type)
const MachineSignature * GetFunctionSigForFastApiImport (Zone *zone, const CFunctionInfo *info)
WellKnownImport CheckForWellKnownImport (DirectHandle< WasmTrustedInstanceData > trusted_instance_data, int func_index, DirectHandle< JSReceiver > callable, const wasm::CanonicalSig *sig)
bool HasDefaultToNumberBehaviour (Isolate *isolate, DirectHandle< JSFunction > function)
bool MaybeMarkError (ValueOrError value, ErrorThrower *thrower)
void SetFunctionTablePlaceholder (Isolate *isolate, DirectHandle< WasmTrustedInstanceData > trusted_instance_data, DirectHandle< WasmTableObject > table_object, uint32_t entry_index, uint32_t func_index)
void SetFunctionTableNullEntry (Isolate *isolate, DirectHandle< WasmTableObject > table_object, uint32_t entry_index)
ValueOrError ConsumeElementSegmentEntry (Zone *zone, Isolate *isolate, DirectHandle< WasmTrustedInstanceData > trusted_instance_data, DirectHandle< WasmTrustedInstanceData > shared_trusted_instance_data, const WasmElemSegment &segment, Decoder &decoder, FunctionComputationMode function_mode)
Enumeration Type Documentation
FunctionComputationMode
enum v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::FunctionComputationMode
Enumerator
kLazyFunctionsAndNull
kStrictFunctionsAndNull
Definition at line 3158 of file module-instantiate.cc.
{ kLazyFunctionsAndNull, kStrictFunctionsAndNull };
ReceiverKind
enum v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::ReceiverKind [strong]
Enumerator
kFirstParamIsReceiver
kAnyReceiver
Definition at line 141 of file module-instantiate.cc.
{ kFirstParamIsReceiver, kAnyReceiver };
Function Documentation
CheckForWellKnownImport()
WellKnownImport v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::CheckForWellKnownImport (DirectHandle< WasmTrustedInstanceData > trusted_instance_data, int func_index, DirectHandle< JSReceiver > callable, const wasm::CanonicalSig * sig)
Definition at line 360 of file module-instantiate.cc.
                                                                    {
  WellKnownImport kGeneric = WellKnownImport::kGeneric; // "using" is C++20.
  if (trusted_instance_data.is_null()) return kGeneric;
  // Check for plain JS functions.
  if (IsJSFunction(*callable)) {
    Tagged<SharedFunctionInfo> sfi = Cast<JSFunction>(*callable)->shared();
    if (!sfi->HasBuiltinId()) return kGeneric;
    // This needs to be a separate switch because it allows other cases than
    // the one below. Merging them would be invalid, because we would then
    // recognize receiver-requiring methods even when they're (erroneously)
    // being imported such that they don't get a receiver.
    switch (sfi->builtin_id()) {
        // =================================================================
        // String-related imports that aren't part of the JS String Builtins
        // proposal.
      case Builtin::kNumberParseFloat:
        if (sig->parameter_count() == 1 && sig->return_count() == 1 &&
            IsStringRef(sig->GetParam(0)) &&
            sig->GetReturn(0) == wasm::kWasmF64) {
          return WellKnownImport::kParseFloat;
        }
        break;
        // =================================================================
        // Math functions.
#define COMPARE_MATH_BUILTIN_F64(name) \
  case Builtin::kMath##name: { \
    if (!v8_flags.wasm_math_intrinsics) return kGeneric; \
    const FunctionSig* builtin_sig = WasmOpcodes::Signature(kExprF64##name); \
    if (!builtin_sig) { \
      builtin_sig = WasmOpcodes::AsmjsSignature(kExprF64##name); \
    } \
    DCHECK_NOT_NULL(builtin_sig); \
    if (EquivalentNumericSig(sig, builtin_sig)) { \
      return WellKnownImport::kMathF64##name; \
    } \
    break; \
  }
        COMPARE_MATH_BUILTIN_F64(Acos)
        COMPARE_MATH_BUILTIN_F64(Asin)
        COMPARE_MATH_BUILTIN_F64(Atan)
        COMPARE_MATH_BUILTIN_F64(Atan2)
        COMPARE_MATH_BUILTIN_F64(Cos)
        COMPARE_MATH_BUILTIN_F64(Sin)
        COMPARE_MATH_BUILTIN_F64(Tan)
        COMPARE_MATH_BUILTIN_F64(Exp)
        COMPARE_MATH_BUILTIN_F64(Log)
        COMPARE_MATH_BUILTIN_F64(Pow)
        COMPARE_MATH_BUILTIN_F64(Sqrt)
#undef COMPARE_MATH_BUILTIN_F64
      default:
        break;
    }
    return kGeneric;
  }
  // Check for bound JS functions.
  // First part: check that the callable is a bound function whose target
  // is {Function.prototype.call}, and which only binds a receiver.
  if (!IsJSBoundFunction(*callable)) return kGeneric;
  auto bound = Cast<JSBoundFunction>(callable);
  if (bound->bound_arguments()->length() != 0) return kGeneric;
  if (!IsJSFunction(bound->bound_target_function())) return kGeneric;
  Tagged<SharedFunctionInfo> sfi =
      Cast<JSFunction>(bound->bound_target_function())->shared();
  if (!sfi->HasBuiltinId()) return kGeneric;
  if (sfi->builtin_id() != Builtin::kFunctionPrototypeCall) return kGeneric;
  // Second part: check if the bound receiver is one of the builtins for which
  // we have special-cased support.
  Tagged<Object> bound_this = bound->bound_this();
  if (!IsJSFunction(bound_this)) return kGeneric;
  sfi = Cast<JSFunction>(bound_this)->shared();
  Isolate* isolate = Isolate::Current();
  int out_api_function_index = -1;
  if (v8_flags.wasm_fast_api &&
      IsSupportedWasmFastApiFunction(isolate, sig, sfi,
                                     ReceiverKind::kFirstParamIsReceiver,
                                     &out_api_function_index)) {
    Tagged<FunctionTemplateInfo> func_data = sfi->api_func_data();
    NativeModule* native_module = trusted_instance_data->native_module();
    if (!native_module->TrySetFastApiCallTarget(
            func_index,
            func_data->GetCFunction(isolate, out_api_function_index))) {
      return kGeneric;
    }
#ifdef V8_USE_SIMULATOR_WITH_GENERIC_C_CALLS
    Address c_functions[] = {func_data->GetCFunction(isolate, 0)};
    const v8::CFunctionInfo* const c_signatures[] = {
        func_data->GetCSignature(isolate, 0)};
    isolate->simulator_data()->RegisterFunctionsAndSignatures(c_functions,
                                                              c_signatures, 1);
#endif // V8_USE_SIMULATOR_WITH_GENERIC_C_CALLS
    // Store the signature of the C++ function in the native_module. We check
    // first if the signature already exists in the native_module such that we
    // do not create a copy of the signature unnecessarily. Since
    // `has_fast_api_signature` and `set_fast_api_signature` don't happen
    // atomically, it is still possible that multiple copies of the signature
    // get created. However, the `TrySetFastApiCallTarget` above guarantees that
    // if there are concurrent calls to `set_cast_api_signature`, then all calls
    // would store the same signature to the native module.
    if (!native_module->has_fast_api_signature(func_index)) {
      // We have to use the lock of the NativeModule here because the
      // `signature_zone` may get accessed by another module instantiation
      // concurrently.
      NativeModule::NativeModuleAllocationLockScope lock(native_module);
      native_module->set_fast_api_signature(
          func_index,
          GetFunctionSigForFastApiImport(
              &native_module->module()->signature_zone,
              func_data->GetCSignature(isolate, out_api_function_index)));
    }
    DirectHandle<HeapObject> js_signature(sfi->api_func_data()->signature(),
                                          isolate);
    DirectHandle<Object> callback_data(
        sfi->api_func_data()->callback_data(kAcquireLoad), isolate);
    DirectHandle<WasmFastApiCallData> fast_api_call_data =
        isolate->factory()->NewWasmFastApiCallData(js_signature, callback_data);
    trusted_instance_data->well_known_imports()->set(func_index,
                                                     *fast_api_call_data);
    return WellKnownImport::kFastAPICall;
  }
  if (!sfi->HasBuiltinId()) return kGeneric;
  switch (sfi->builtin_id()) {
#if V8_INTL_SUPPORT
    case Builtin::kStringPrototypeToLocaleLowerCase:
      if (sig->parameter_count() == 2 && sig->return_count() == 1 &&
          IsStringRef(sig->GetParam(0)) && IsStringRef(sig->GetParam(1)) &&
          IsStringRef(sig->GetReturn(0))) {
        DCHECK_GE(func_index, 0);
        trusted_instance_data->well_known_imports()->set(func_index,
                                                         bound_this);
        return WellKnownImport::kStringToLocaleLowerCaseStringref;
      }
      break;
    case Builtin::kStringPrototypeToLowerCaseIntl:
      if (sig->parameter_count() == 1 && sig->return_count() == 1 &&
          IsStringRef(sig->GetParam(0)) && IsStringRef(sig->GetReturn(0))) {
        return WellKnownImport::kStringToLowerCaseStringref;
      } else if (sig->parameter_count() == 1 && sig->return_count() == 1 &&
                 sig->GetParam(0) == wasm::kWasmExternRef &&
                 sig->GetReturn(0) == wasm::kWasmExternRef) {
        return WellKnownImport::kStringToLowerCaseImported;
      }
      break;
#endif
    case Builtin::kDataViewPrototypeGetBigInt64:
      if (IsDataViewGetterSig(sig, wasm::kWasmI64)) {
        return WellKnownImport::kDataViewGetBigInt64;
      }
      break;
    case Builtin::kDataViewPrototypeGetBigUint64:
      if (IsDataViewGetterSig(sig, wasm::kWasmI64)) {
        return WellKnownImport::kDataViewGetBigUint64;
      }
      break;
    case Builtin::kDataViewPrototypeGetFloat32:
      if (IsDataViewGetterSig(sig, wasm::kWasmF32)) {
        return WellKnownImport::kDataViewGetFloat32;
      }
      break;
    case Builtin::kDataViewPrototypeGetFloat64:
      if (IsDataViewGetterSig(sig, wasm::kWasmF64)) {
        return WellKnownImport::kDataViewGetFloat64;
      }
      break;
    case Builtin::kDataViewPrototypeGetInt8:
      if (sig->parameter_count() == 2 && sig->return_count() == 1 &&
          sig->GetParam(0) == wasm::kWasmExternRef &&
          sig->GetParam(1) == wasm::kWasmI32 &&
          sig->GetReturn(0) == wasm::kWasmI32) {
        return WellKnownImport::kDataViewGetInt8;
      }
      break;
    case Builtin::kDataViewPrototypeGetInt16:
      if (IsDataViewGetterSig(sig, wasm::kWasmI32)) {
        return WellKnownImport::kDataViewGetInt16;
      }
      break;
    case Builtin::kDataViewPrototypeGetInt32:
      if (IsDataViewGetterSig(sig, wasm::kWasmI32)) {
        return WellKnownImport::kDataViewGetInt32;
      }
      break;
    case Builtin::kDataViewPrototypeGetUint8:
      if (sig->parameter_count() == 2 && sig->return_count() == 1 &&
          sig->GetParam(0) == wasm::kWasmExternRef &&
          sig->GetParam(1) == wasm::kWasmI32 &&
          sig->GetReturn(0) == wasm::kWasmI32) {
        return WellKnownImport::kDataViewGetUint8;
      }
      break;
    case Builtin::kDataViewPrototypeGetUint16:
      if (IsDataViewGetterSig(sig, wasm::kWasmI32)) {
        return WellKnownImport::kDataViewGetUint16;
      }
      break;
    case Builtin::kDataViewPrototypeGetUint32:
      if (IsDataViewGetterSig(sig, wasm::kWasmI32)) {
        return WellKnownImport::kDataViewGetUint32;
      }
      break;
    case Builtin::kDataViewPrototypeSetBigInt64:
      if (IsDataViewSetterSig(sig, wasm::kWasmI64)) {
        return WellKnownImport::kDataViewSetBigInt64;
      }
      break;
    case Builtin::kDataViewPrototypeSetBigUint64:
      if (IsDataViewSetterSig(sig, wasm::kWasmI64)) {
        return WellKnownImport::kDataViewSetBigUint64;
      }
      break;
    case Builtin::kDataViewPrototypeSetFloat32:
      if (IsDataViewSetterSig(sig, wasm::kWasmF32)) {
        return WellKnownImport::kDataViewSetFloat32;
      }
      break;
    case Builtin::kDataViewPrototypeSetFloat64:
      if (IsDataViewSetterSig(sig, wasm::kWasmF64)) {
        return WellKnownImport::kDataViewSetFloat64;
      }
      break;
    case Builtin::kDataViewPrototypeSetInt8:
      if (sig->parameter_count() == 3 && sig->return_count() == 0 &&
          sig->GetParam(0) == wasm::kWasmExternRef &&
          sig->GetParam(1) == wasm::kWasmI32 &&
          sig->GetParam(2) == wasm::kWasmI32) {
        return WellKnownImport::kDataViewSetInt8;
      }
      break;
    case Builtin::kDataViewPrototypeSetInt16:
      if (IsDataViewSetterSig(sig, wasm::kWasmI32)) {
        return WellKnownImport::kDataViewSetInt16;
      }
      break;
    case Builtin::kDataViewPrototypeSetInt32:
      if (IsDataViewSetterSig(sig, wasm::kWasmI32)) {
        return WellKnownImport::kDataViewSetInt32;
      }
      break;
    case Builtin::kDataViewPrototypeSetUint8:
      if (sig->parameter_count() == 3 && sig->return_count() == 0 &&
          sig->GetParam(0) == wasm::kWasmExternRef &&
          sig->GetParam(1) == wasm::kWasmI32 &&
          sig->GetParam(2) == wasm::kWasmI32) {
        return WellKnownImport::kDataViewSetUint8;
      }
      break;
    case Builtin::kDataViewPrototypeSetUint16:
      if (IsDataViewSetterSig(sig, wasm::kWasmI32)) {
        return WellKnownImport::kDataViewSetUint16;
      }
      break;
    case Builtin::kDataViewPrototypeSetUint32:
      if (IsDataViewSetterSig(sig, wasm::kWasmI32)) {
        return WellKnownImport::kDataViewSetUint32;
      }
      break;
    case Builtin::kDataViewPrototypeGetByteLength:
      if (sig->parameter_count() == 1 && sig->return_count() == 1 &&
          sig->GetParam(0) == wasm::kWasmExternRef &&
          sig->GetReturn(0) == kWasmF64) {
        return WellKnownImport::kDataViewByteLength;
      }
      break;
    case Builtin::kNumberPrototypeToString:
      if (sig->parameter_count() == 2 && sig->return_count() == 1 &&
          sig->GetParam(0) == wasm::kWasmI32 &&
          sig->GetParam(1) == wasm::kWasmI32 &&
          IsStringOrExternRef(sig->GetReturn(0))) {
        return WellKnownImport::kIntToString;
      }
      if (sig->parameter_count() == 1 && sig->return_count() == 1 &&
          sig->GetParam(0) == wasm::kWasmF64 &&
          IsStringOrExternRef(sig->GetReturn(0))) {
        return WellKnownImport::kDoubleToString;
      }
      break;
    case Builtin::kStringPrototypeIndexOf:
      // (string, string, i32) -> (i32).
      if (sig->parameter_count() == 3 && sig->return_count() == 1 &&
          IsStringRef(sig->GetParam(0)) && IsStringRef(sig->GetParam(1)) &&
          sig->GetParam(2) == wasm::kWasmI32 &&
          sig->GetReturn(0) == wasm::kWasmI32) {
        return WellKnownImport::kStringIndexOf;
      } else if (sig->parameter_count() == 3 && sig->return_count() == 1 &&
                 sig->GetParam(0) == wasm::kWasmExternRef &&
                 sig->GetParam(1) == wasm::kWasmExternRef &&
                 sig->GetParam(2) == wasm::kWasmI32 &&
                 sig->GetReturn(0) == wasm::kWasmI32) {
        return WellKnownImport::kStringIndexOfImported;
      }
      break;
    default:
      break;
  }
  return kGeneric;
}
References COMPARE_MATH_BUILTIN_F64, v8::internal::Isolate::Current(), DCHECK_GE, v8::internal::Isolate::factory(), GetFunctionSigForFastApiImport(), v8::internal::wasm::NativeModule::has_fast_api_signature(), v8::internal::DirectHandle< T >::is_null(), IsDataViewGetterSig(), IsDataViewSetterSig(), IsStringOrExternRef(), IsStringRef(), IsSupportedWasmFastApiFunction(), v8::kAcquireLoad, v8::internal::wasm::kDataViewByteLength, v8::internal::wasm::kDataViewGetBigInt64, v8::internal::wasm::kDataViewGetBigUint64, v8::internal::wasm::kDataViewGetFloat32, v8::internal::wasm::kDataViewGetFloat64, v8::internal::wasm::kDataViewGetInt16, v8::internal::wasm::kDataViewGetInt32, v8::internal::wasm::kDataViewGetInt8, v8::internal::wasm::kDataViewGetUint16, v8::internal::wasm::kDataViewGetUint32, v8::internal::wasm::kDataViewGetUint8, v8::internal::wasm::kDataViewSetBigInt64, v8::internal::wasm::kDataViewSetBigUint64, v8::internal::wasm::kDataViewSetFloat32, v8::internal::wasm::kDataViewSetFloat64, v8::internal::wasm::kDataViewSetInt16, v8::internal::wasm::kDataViewSetInt32, v8::internal::wasm::kDataViewSetInt8, v8::internal::wasm::kDataViewSetUint16, v8::internal::wasm::kDataViewSetUint32, v8::internal::wasm::kDataViewSetUint8, v8::internal::wasm::kDoubleToString, v8::internal::wasm::kFastAPICall, v8::internal::kGeneric, v8::internal::wasm::kGeneric, v8::internal::wasm::kIntToString, v8::internal::wasm::kParseFloat, v8::internal::wasm::kStringIndexOf, v8::internal::wasm::kStringIndexOfImported, v8::internal::wasm::kStringToLocaleLowerCaseStringref, v8::internal::wasm::kStringToLowerCaseImported, v8::internal::wasm::kStringToLowerCaseStringref, v8::internal::wasm::kWasmExternRef, v8::internal::wasm::kWasmF32, v8::internal::wasm::kWasmF64, v8::internal::wasm::kWasmI32, v8::internal::wasm::kWasmI64, v8::internal::wasm::NativeModule::module(), v8::internal::wasm::NativeModule::set_fast_api_signature(), v8::internal::sig, v8::internal::wasm::WasmModule::signature_zone, v8::internal::wasm::NativeModule::TrySetFastApiCallTarget(), and v8::internal::v8_flags.
Referenced by v8::internal::wasm::ResolvedWasmImport::ComputeKind().
CompareWithNormalizedCType()
bool v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::CompareWithNormalizedCType (const CTypeInfo & info, CanonicalValueType expected, CFunctionInfo::Int64Representation int64_rep)
Definition at line 117 of file module-instantiate.cc.
                                                                            {
  MachineType t = MachineType::TypeForCType(info);
  // Wasm representation of bool is i32 instead of i1.
  if (t.semantic() == MachineSemantic::kBool) {
    return expected == kWasmI32;
  }
  if (info.GetType() == CTypeInfo::Type::kSeqOneByteString) {
    // WebAssembly does not support one byte strings in fast API calls as
    // runtime type checks are not supported so far.
    return false;
  }
  if (t.representation() == MachineRepresentation::kWord64) {
    if (int64_rep == CFunctionInfo::Int64Representation::kBigInt) {
      return expected == kWasmI64;
    }
    DCHECK_EQ(int64_rep, CFunctionInfo::Int64Representation::kNumber);
    return expected == kWasmI32 || expected == kWasmF32 || expected == kWasmF64;
  }
  return t.representation() == expected.machine_representation();
}
References DCHECK_EQ, v8::CTypeInfo::GetType(), v8::CFunctionInfo::kBigInt, v8::internal::kBool, v8::CFunctionInfo::kNumber, v8::CTypeInfo::kSeqOneByteString, v8::internal::wasm::kWasmF32, v8::internal::wasm::kWasmF64, v8::internal::wasm::kWasmI32, v8::internal::wasm::kWasmI64, v8::internal::kWord64, v8::internal::wasm::ValueTypeBase::machine_representation(), v8::internal::MachineType::representation(), v8::internal::MachineType::semantic(), and v8::internal::MachineType::TypeForCType().
Referenced by IsSupportedWasmFastApiFunction().
ConsumeElementSegmentEntry()
ValueOrError v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::ConsumeElementSegmentEntry (Zone * zone, Isolate * isolate, DirectHandle< WasmTrustedInstanceData > trusted_instance_data, DirectHandle< WasmTrustedInstanceData > shared_trusted_instance_data, const WasmElemSegment & segment, Decoder & decoder, FunctionComputationMode function_mode)
Definition at line 3164 of file module-instantiate.cc.
                                           {
  const WasmModule* module = trusted_instance_data->module();
  if (segment.element_type == WasmElemSegment::kFunctionIndexElements) {
    uint32_t function_index = decoder.consume_u32v();
    return function_mode == kStrictFunctionsAndNull
               ? EvaluateConstantExpression(
                     zone, ConstantExpression::RefFunc(function_index),
                     segment.type, module, isolate, trusted_instance_data,
                     shared_trusted_instance_data)
               : ValueOrError(WasmValue(function_index));
  }
  switch (static_cast<WasmOpcode>(*decoder.pc())) {
    case kExprRefFunc: {
      auto [function_index, length] =
          decoder.read_u32v<Decoder::FullValidationTag>(decoder.pc() + 1,
                                                        "ref.func");
      if (V8_LIKELY(decoder.lookahead(1 + length, kExprEnd))) {
        decoder.consume_bytes(length + 2);
        return function_mode == kStrictFunctionsAndNull
                   ? EvaluateConstantExpression(
                         zone, ConstantExpression::RefFunc(function_index),
                         segment.type, module, isolate, trusted_instance_data,
                         shared_trusted_instance_data)
                   : ValueOrError(WasmValue(function_index));
      }
      break;
    }
    case kExprRefNull: {
      WasmDetectedFeatures detected;
      auto [heap_type, length] =
          value_type_reader::read_heap_type<Decoder::FullValidationTag>(
              &decoder, decoder.pc() + 1, WasmEnabledFeatures::All(),
              &detected);
      value_type_reader::Populate(&heap_type, module);
      if (V8_LIKELY(decoder.lookahead(1 + length, kExprEnd))) {
        decoder.consume_bytes(length + 2);
        return function_mode == kStrictFunctionsAndNull
                   ? EvaluateConstantExpression(
                         zone, ConstantExpression::RefNull(heap_type),
                         segment.type, module, isolate, trusted_instance_data,
                         shared_trusted_instance_data)
                   : WasmValue(int32_t{-1});
      }
      break;
    }
    default:
      break;
  }
  auto sig = FixedSizeSignature<ValueType>::Returns(segment.type);
  constexpr bool kIsShared = false; // TODO(14616): Is this correct?
  FunctionBody body(&sig, decoder.pc_offset(), decoder.pc(), decoder.end(),
                    kIsShared);
  WasmDetectedFeatures detected;
  ValueOrError result;
  {
    // We need a scope for the decoder because its destructor resets some Zone
    // elements, which has to be done before we reset the Zone afterwards.
    // We use FullValidationTag so we do not have to create another template
    // instance of WasmFullDecoder, which would cost us >50Kb binary code
    // size.
    WasmFullDecoder<Decoder::FullValidationTag, ConstantExpressionInterface,
                    kConstantExpression>
        full_decoder(zone, trusted_instance_data->module(),
                     WasmEnabledFeatures::All(), &detected, body,
                     trusted_instance_data->module(), isolate,
                     trusted_instance_data, shared_trusted_instance_data);
    full_decoder.DecodeFunctionBody();
    decoder.consume_bytes(static_cast<int>(full_decoder.pc() - decoder.pc()));
    result = full_decoder.interface().has_error()
                 ? ValueOrError(full_decoder.interface().error())
                 : ValueOrError(full_decoder.interface().computed_value());
  }
  zone->Reset();
  return result;
}
References v8::internal::wasm::WasmEnabledFeatures::All(), v8::internal::wasm::Decoder::consume_bytes(), v8::internal::wasm::Decoder::consume_u32v(), v8::internal::wasm::WasmElemSegment::element_type, v8::internal::wasm::Decoder::end(), v8::internal::wasm::EvaluateConstantExpression(), v8::internal::wasm::kConstantExpression, v8::internal::wasm::WasmElemSegment::kFunctionIndexElements, kStrictFunctionsAndNull, v8::internal::length, v8::internal::wasm::Decoder::lookahead(), v8::internal::wasm::Decoder::pc(), v8::internal::wasm::Decoder::pc_offset(), v8::internal::wasm::value_type_reader::Populate(), v8::internal::wasm::Decoder::read_u32v(), v8::internal::wasm::ConstantExpression::RefFunc(), v8::internal::wasm::ConstantExpression::RefNull(), v8::internal::Zone::Reset(), v8::base::internal::result, v8::internal::FixedSizeSignature< T, kNumReturns, kNumParams >::Returns(), v8::internal::sig, v8::internal::wasm::WasmElemSegment::type, and V8_LIKELY.
Referenced by v8::internal::wasm::InitializeElementSegment(), and v8::internal::wasm::InstanceBuilder::LoadTableSegments().
GetFunctionSigForFastApiImport()
const MachineSignature* v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::GetFunctionSigForFastApiImport (Zone * zone, const CFunctionInfo * info)
Definition at line 337 of file module-instantiate.cc.
                                           {
  uint32_t arg_count = info->ArgumentCount();
  uint32_t ret_count =
      info->ReturnInfo().GetType() == CTypeInfo::Type::kVoid ? 0 : 1;
  constexpr uint32_t param_offset = 1;
  MachineSignature::Builder sig_builder(zone, ret_count,
                                        arg_count - param_offset);
  if (ret_count) {
    sig_builder.AddReturn(MachineType::TypeForCType(info->ReturnInfo()));
  }
  for (uint32_t i = param_offset; i < arg_count; ++i) {
    sig_builder.AddParam(MachineType::TypeForCType(info->ArgumentInfo(i)));
  }
  return sig_builder.Get();
}
References v8::internal::SignatureBuilder< SigT, T >::AddParam(), v8::internal::SignatureBuilder< SigT, T >::AddReturn(), v8::CFunctionInfo::ArgumentCount(), v8::CFunctionInfo::ArgumentInfo(), v8::internal::SignatureBuilder< SigT, T >::Get(), v8::CTypeInfo::GetType(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::CTypeInfo::kVoid, v8::CFunctionInfo::ReturnInfo(), and v8::internal::MachineType::TypeForCType().
Referenced by CheckForWellKnownImport().
HasDefaultToNumberBehaviour()
bool v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::HasDefaultToNumberBehaviour (Isolate * isolate, DirectHandle< JSFunction > function)
Definition at line 2003 of file module-instantiate.cc.
                                                                    {
  // Disallow providing a [Symbol.toPrimitive] member.
  LookupIterator to_primitive_it{isolate, function,
                                 isolate->factory()->to_primitive_symbol()};
  if (to_primitive_it.state() != LookupIterator::NOT_FOUND) return false;
  // The {valueOf} member must be the default "ObjectPrototypeValueOf".
  LookupIterator value_of_it{isolate, function,
                             isolate->factory()->valueOf_string()};
  if (value_of_it.state() != LookupIterator::DATA) return false;
  DirectHandle<Object> value_of = value_of_it.GetDataValue();
  if (!IsJSFunction(*value_of)) return false;
  Builtin value_of_builtin_id =
      Cast<JSFunction>(value_of)->code(isolate)->builtin_id();
  if (value_of_builtin_id != Builtin::kObjectPrototypeValueOf) return false;
  // The {toString} member must be the default "FunctionPrototypeToString".
  LookupIterator to_string_it{isolate, function,
                              isolate->factory()->toString_string()};
  if (to_string_it.state() != LookupIterator::DATA) return false;
  DirectHandle<Object> to_string = to_string_it.GetDataValue();
  if (!IsJSFunction(*to_string)) return false;
  Builtin to_string_builtin_id =
      Cast<JSFunction>(to_string)->code(isolate)->builtin_id();
  if (to_string_builtin_id != Builtin::kFunctionPrototypeToString) return false;
  // Just a default function, which will convert to "Nan". Accept this.
  return true;
}
References v8::internal::LookupIterator::DATA, v8::internal::Isolate::factory(), and v8::internal::LookupIterator::NOT_FOUND.
Referenced by v8::internal::wasm::InstanceBuilder::LookupImportAsm().
IsDataViewGetterSig()
bool v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::IsDataViewGetterSig (const wasm::CanonicalSig * sig, wasm::CanonicalValueType return_type)
Definition at line 321 of file module-instantiate.cc.
                                                             {
  return sig->parameter_count() == 3 && sig->return_count() == 1 &&
         sig->GetParam(0) == wasm::kWasmExternRef &&
         sig->GetParam(1) == wasm::kWasmI32 &&
         sig->GetParam(2) == wasm::kWasmI32 && sig->GetReturn(0) == return_type;
}
References v8::internal::wasm::kWasmExternRef, v8::internal::wasm::kWasmI32, and v8::internal::sig.
Referenced by CheckForWellKnownImport().
IsDataViewSetterSig()
bool v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::IsDataViewSetterSig (const wasm::CanonicalSig * sig, wasm::CanonicalValueType value_type)
Definition at line 329 of file module-instantiate.cc.
                                                            {
  return sig->parameter_count() == 4 && sig->return_count() == 0 &&
         sig->GetParam(0) == wasm::kWasmExternRef &&
         sig->GetParam(1) == wasm::kWasmI32 && sig->GetParam(2) == value_type &&
         sig->GetParam(3) == wasm::kWasmI32;
}
References v8::internal::wasm::kWasmExternRef, v8::internal::wasm::kWasmI32, v8::internal::sig, and v8::internal::wasm::value_type().
Referenced by CheckForWellKnownImport().
IsExternRef()
bool v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::IsExternRef (wasm::CanonicalValueType type)
Definition at line 313 of file module-instantiate.cc.
                                              {
  return type.is_abstract_ref() && type.generic_kind() == GenericKind::kExtern;
}
References v8::internal::tracing::type.
Referenced by IsStringOrExternRef().
IsStringOrExternRef()
bool v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::IsStringOrExternRef (wasm::CanonicalValueType type)
Definition at line 317 of file module-instantiate.cc.
                                                      {
  return IsStringRef(type) || IsExternRef(type);
}
References IsExternRef(), IsStringRef(), and v8::internal::tracing::type.
Referenced by CheckForWellKnownImport().
IsStringRef()
bool v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::IsStringRef (wasm::CanonicalValueType type)
Definition at line 309 of file module-instantiate.cc.
                                              {
  return type.is_abstract_ref() && type.generic_kind() == GenericKind::kString;
}
References v8::internal::tracing::type.
Referenced by CheckForWellKnownImport(), and IsStringOrExternRef().
IsSupportedWasmFastApiFunction()
bool v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::IsSupportedWasmFastApiFunction (Isolate * isolate, const wasm::CanonicalSig * expected_sig, Tagged< SharedFunctionInfo > shared, ReceiverKind receiver_kind, int * out_index)
Definition at line 143 of file module-instantiate.cc.
                                                    {
  if (!shared->IsApiFunction()) {
    return false;
  }
  if (shared->api_func_data()->GetCFunctionsCount() == 0) {
    return false;
  }
  if (receiver_kind == ReceiverKind::kAnyReceiver &&
      !shared->api_func_data()->accept_any_receiver()) {
    return false;
  }
  if (receiver_kind == ReceiverKind::kAnyReceiver &&
      !IsUndefined(shared->api_func_data()->signature())) {
    // TODO(wasm): CFunctionInfo* signature check.
    return false;
  }
  const auto log_imported_function_mismatch = [&shared, isolate](
                                                  int func_index,
                                                  const char* reason) {
    if (v8_flags.trace_opt) {
      CodeTracer::Scope scope(isolate->GetCodeTracer());
      PrintF(scope.file(), "[disabled optimization for ");
      ShortPrint(*shared, scope.file());
      PrintF(scope.file(),
             " for C function %d, reason: the signature of the imported "
             "function in the Wasm module doesn't match that of the Fast API "
             "function (%s)]\n",
             func_index, reason);
    }
  };
  // C functions only have one return value.
  if (expected_sig->return_count() > 1) {
    // Here and below, we log when the function we call is declared as an Api
    // function but we cannot optimize the call, which might be unexpected. In
    // that case we use the "slow" path making a normal Wasm->JS call and
    // calling the "slow" callback specified in FunctionTemplate::New().
    log_imported_function_mismatch(0, "too many return values");
    return false;
  }
  for (int c_func_id = 0, end = shared->api_func_data()->GetCFunctionsCount();
       c_func_id < end; ++c_func_id) {
    const CFunctionInfo* info =
        shared->api_func_data()->GetCSignature(isolate, c_func_id);
    if (!compiler::IsFastCallSupportedSignature(info)) {
      log_imported_function_mismatch(c_func_id,
                                     "signature not supported by the fast API");
      continue;
    }
    CTypeInfo return_info = info->ReturnInfo();
    // Unsupported if return type doesn't match.
    if (expected_sig->return_count() == 0 &&
        return_info.GetType() != CTypeInfo::Type::kVoid) {
      log_imported_function_mismatch(c_func_id, "too few return values");
      continue;
    }
    // Unsupported if return type doesn't match.
    if (expected_sig->return_count() == 1) {
      if (return_info.GetType() == CTypeInfo::Type::kVoid) {
        log_imported_function_mismatch(c_func_id, "too many return values");
        continue;
      }
      if (!CompareWithNormalizedCType(return_info, expected_sig->GetReturn(0),
                                      info->GetInt64Representation())) {
        log_imported_function_mismatch(c_func_id, "mismatching return value");
        continue;
      }
    }
    if (receiver_kind == ReceiverKind::kFirstParamIsReceiver) {
      if (expected_sig->parameter_count() < 1) {
        log_imported_function_mismatch(
            c_func_id, "at least one parameter is needed as the receiver");
        continue;
      }
      if (!expected_sig->GetParam(0).is_reference()) {
        log_imported_function_mismatch(c_func_id,
                                       "the receiver has to be a reference");
        continue;
      }
    }
    int param_offset =
        receiver_kind == ReceiverKind::kFirstParamIsReceiver ? 1 : 0;
    // Unsupported if arity doesn't match.
    if (expected_sig->parameter_count() - param_offset !=
        info->ArgumentCount() - 1) {
      log_imported_function_mismatch(c_func_id, "mismatched arity");
      continue;
    }
    // Unsupported if any argument types don't match.
    bool param_mismatch = false;
    for (unsigned int i = 0; i < expected_sig->parameter_count() - param_offset;
         ++i) {
      int sig_index = i + param_offset;
      // Arg 0 is the receiver, skip over it since either the receiver does not
      // matter, or we already checked it above.
      CTypeInfo arg = info->ArgumentInfo(i + 1);
      if (!CompareWithNormalizedCType(arg, expected_sig->GetParam(sig_index),
                                      info->GetInt64Representation())) {
        log_imported_function_mismatch(c_func_id, "parameter type mismatch");
        param_mismatch = true;
        break;
      }
      START_ALLOW_USE_DEPRECATED()
      if (arg.GetSequenceType() == CTypeInfo::SequenceType::kIsSequence) {
        log_imported_function_mismatch(c_func_id,
                                       "sequence types are not allowed");
        param_mismatch = true;
        break;
      }
      END_ALLOW_USE_DEPRECATED()
    }
    if (param_mismatch) {
      continue;
    }
    *out_index = c_func_id;
    return true;
  }
  return false;
}
References v8::CFunctionInfo::ArgumentCount(), v8::CFunctionInfo::ArgumentInfo(), CompareWithNormalizedCType(), v8::internal::compiler::end(), END_ALLOW_USE_DEPRECATED, v8::internal::CodeTracer::Scope::file(), v8::internal::Isolate::GetCodeTracer(), v8::CFunctionInfo::GetInt64Representation(), v8::internal::Signature< T >::GetParam(), v8::internal::Signature< T >::GetReturn(), v8::CTypeInfo::GetSequenceType(), v8::CTypeInfo::GetType(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::ValueTypeBase::is_reference(), v8::internal::compiler::IsFastCallSupportedSignature(), v8::CTypeInfo::kVoid, v8::internal::Signature< T >::parameter_count(), v8::internal::PrintF(), v8::internal::Signature< T >::return_count(), v8::CFunctionInfo::ReturnInfo(), v8::internal::ShortPrint(), START_ALLOW_USE_DEPRECATED, and v8::internal::v8_flags.
Referenced by CheckForWellKnownImport(), and ResolveBoundJSFastApiFunction().
MaybeMarkError()
bool v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::MaybeMarkError (ValueOrError value, ErrorThrower * thrower)
Definition at line 2034 of file module-instantiate.cc.
                                                               {
  if (is_error(value)) {
    thrower->RuntimeError("%s",
                          MessageFormatter::TemplateString(to_error(value)));
    return true;
  }
  return false;
}
References v8::internal::wasm::is_error(), v8::internal::MessageFormatter::TemplateString(), v8::internal::wasm::to_error(), and v8::internal::value.
Referenced by v8::internal::wasm::InstanceBuilder::InitGlobals(), v8::internal::wasm::InstanceBuilder::LoadDataSegments(), v8::internal::wasm::InstanceBuilder::LoadTableSegments(), and v8::internal::wasm::InstanceBuilder::SetTableInitialValues().
raw_buffer_ptr()
uint8_t* v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::raw_buffer_ptr (MaybeDirectHandle< JSArrayBuffer > buffer, int offset)
Definition at line 50 of file module-instantiate.cc.
                                                                             {
  return static_cast<uint8_t*>(buffer.ToHandleChecked()->backing_store()) +
         offset;
}
References v8::internal::MaybeDirectHandle< T >::ToHandleChecked().
Referenced by v8::internal::wasm::InstanceBuilder::GetRawUntaggedGlobalPtr(), v8::internal::wasm::InstanceBuilder::ProcessImportedWasmGlobalObject(), and v8::internal::wasm::InstanceBuilder::WriteGlobalValue().
ResolveBoundJSFastApiFunction()
bool v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::ResolveBoundJSFastApiFunction (const wasm::CanonicalSig * expected_sig, DirectHandle< JSReceiver > callable)
Definition at line 272 of file module-instantiate.cc.
                                                                      {
  Isolate* isolate = Isolate::Current();
  DirectHandle<JSFunction> target;
  if (IsJSBoundFunction(*callable)) {
    auto bound_target = Cast<JSBoundFunction>(callable);
    // Nested bound functions and arguments not supported yet.
    if (bound_target->bound_arguments()->length() > 0) {
      return false;
    }
    if (IsJSBoundFunction(bound_target->bound_target_function())) {
      return false;
    }
    DirectHandle<JSReceiver> bound_target_function(
        bound_target->bound_target_function(), isolate);
    if (!IsJSFunction(*bound_target_function)) {
      return false;
    }
    target = Cast<JSFunction>(bound_target_function);
  } else if (IsJSFunction(*callable)) {
    target = Cast<JSFunction>(callable);
  } else {
    return false;
  }
  DirectHandle<SharedFunctionInfo> shared(target->shared(), isolate);
  int api_function_index = -1;
  // The fast API call wrapper currently does not support function overloading.
  // Therefore, if the matching function is not function 0, the fast API cannot
  // be used.
  return IsSupportedWasmFastApiFunction(isolate, expected_sig, *shared,
                                        ReceiverKind::kAnyReceiver,
                                        &api_function_index) &&
         api_function_index == 0;
}
References v8::internal::Isolate::Current(), and IsSupportedWasmFastApiFunction().
Referenced by v8::internal::wasm::ResolvedWasmImport::ComputeKind().
SetFunctionTableNullEntry()
void v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::SetFunctionTableNullEntry (Isolate * isolate, DirectHandle< WasmTableObject > table_object, uint32_t entry_index) [inline]
Definition at line 3106 of file module-instantiate.cc.
                          {
  table_object->entries()->set(entry_index, ReadOnlyRoots{isolate}.wasm_null());
  table_object->ClearDispatchTable(entry_index);
}
Referenced by v8::internal::wasm::InstanceBuilder::LoadTableSegments(), and v8::internal::wasm::InstanceBuilder::SetTableInitialValues().
SetFunctionTablePlaceholder()
void v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::SetFunctionTablePlaceholder (Isolate * isolate, DirectHandle< WasmTrustedInstanceData > trusted_instance_data, DirectHandle< WasmTableObject > table_object, uint32_t entry_index, uint32_t func_index) [inline]
Definition at line 3083 of file module-instantiate.cc.
                         {
  const WasmModule* module = trusted_instance_data->module();
  const WasmFunction* function = &module->functions[func_index];
  Tagged<WasmFuncRef> func_ref;
  if (trusted_instance_data->try_get_func_ref(func_index, &func_ref)) {
    table_object->entries()->set(entry_index, *func_ref);
  } else {
    WasmTableObject::SetFunctionTablePlaceholder(
        isolate, table_object, entry_index, trusted_instance_data, func_index);
  }
  WasmTableObject::UpdateDispatchTable(isolate, table_object, entry_index,
                                       function, trusted_instance_data
#if V8_ENABLE_DRUMBRAKE
                                       ,
                                       func_index
#endif // V8_ENABLE_DRUMBRAKE
  );
}
References v8::internal::wasm::WasmModule::functions, v8::internal::WasmTableObject::SetFunctionTablePlaceholder(), and v8::internal::WasmTableObject::UpdateDispatchTable().
Referenced by v8::internal::wasm::InstanceBuilder::LoadTableSegments(), and v8::internal::wasm::InstanceBuilder::SetTableInitialValues().