v8::internal::anonymous_namespace{wasm-js.cc} Namespace Reference
Functions
DirectHandle< JSFunction > CreateFunc (Isolate *isolate, DirectHandle< String > name, FunctionCallback func, bool has_prototype, SideEffectType side_effect_type=SideEffectType::kHasSideEffect, DirectHandle< FunctionTemplateInfo > parent={})
DirectHandle< JSFunction > InstallFunc (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< String > name, FunctionCallback func, int length, bool has_prototype=false, PropertyAttributes attributes=NONE, SideEffectType side_effect_type=SideEffectType::kHasSideEffect)
DirectHandle< JSFunction > InstallFunc (Isolate *isolate, DirectHandle< JSObject > object, const char *str, FunctionCallback func, int length, bool has_prototype=false, PropertyAttributes attributes=NONE, SideEffectType side_effect_type=SideEffectType::kHasSideEffect)
DirectHandle< JSFunction > InstallConstructorFunc (Isolate *isolate, DirectHandle< JSObject > object, const char *str, FunctionCallback func)
DirectHandle< String > GetterName (Isolate *isolate, DirectHandle< String > name)
void InstallGetter (Isolate *isolate, DirectHandle< JSObject > object, const char *str, FunctionCallback func)
DirectHandle< String > SetterName (Isolate *isolate, DirectHandle< String > name)
void InstallGetterSetter (Isolate *isolate, DirectHandle< JSObject > object, const char *str, FunctionCallback getter, FunctionCallback setter)
void SetDummyInstanceTemplate (Isolate *isolate, DirectHandle< JSFunction > fun)
DirectHandle< JSObject > SetupConstructor (Isolate *isolate, DirectHandle< JSFunction > constructor, InstanceType instance_type, int instance_size, const char *name=nullptr, int in_object_properties=0)
Variables
constexpr wasm::ValueType kWasmExceptionTagParams []
constexpr wasm::FunctionSig kWasmExceptionTagSignature
Function Documentation
CreateFunc()
DirectHandle<JSFunction> v8::internal::anonymous_namespace{wasm-js.cc}::CreateFunc (Isolate * isolate, DirectHandle< String > name, FunctionCallback func, bool has_prototype, SideEffectType side_effect_type = SideEffectType::kHasSideEffect, DirectHandle< FunctionTemplateInfo > parent = {})
Definition at line 3280 of file wasm-js.cc.
                                                {}) {
  DirectHandle<FunctionTemplateInfo> temp =
      NewFunctionTemplate(isolate, func, has_prototype, side_effect_type);
  if (!parent.is_null()) {
    DCHECK(has_prototype);
    FunctionTemplateInfo::SetParentTemplate(isolate, temp, parent);
  }
  DirectHandle<JSFunction> function =
      ApiNatives::InstantiateFunction(isolate, temp, name).ToHandleChecked();
  DCHECK(function->shared()->HasSharedName());
  return function;
}
Referenced by InstallFunc(), InstallGetter(), InstallGetterSetter(), and v8::internal::WasmJs::InstallModule().
GetterName()
DirectHandle<String> v8::internal::anonymous_namespace{wasm-js.cc}::GetterName (Isolate * isolate, DirectHandle< String > name)
Definition at line 3331 of file wasm-js.cc.
                                                                             {
  return Name::ToFunctionName(isolate, name, isolate->factory()->get_string())
      .ToHandleChecked();
}
References v8::internal::Isolate::factory(), and name.
Referenced by InstallGetter(), and InstallGetterSetter().
InstallConstructorFunc()
DirectHandle<JSFunction> v8::internal::anonymous_namespace{wasm-js.cc}::InstallConstructorFunc (Isolate * isolate, DirectHandle< JSObject > object, const char * str, FunctionCallback func)
Definition at line 3323 of file wasm-js.cc.
                                                                       {
  return InstallFunc(isolate, object, str, func, 1, true, DONT_ENUM,
                     SideEffectType::kHasNoSideEffect);
}
References v8::internal::DONT_ENUM, InstallFunc(), and v8::kHasNoSideEffect.
Referenced by v8::internal::WasmJs::InstallCustomDescriptors(), v8::internal::WasmJs::InstallJSPromiseIntegration(), v8::internal::WasmJs::InstallMemoryControl(), v8::internal::WasmJs::InstallModule(), v8::internal::WasmJs::InstallTypeReflection(), and v8::internal::WasmJs::PrepareForSnapshot().
InstallFunc() [1/2]
DirectHandle<JSFunction> v8::internal::anonymous_namespace{wasm-js.cc}::InstallFunc (Isolate * isolate, DirectHandle< JSObject > object, const char * str, FunctionCallback func, int length, bool has_prototype = false, PropertyAttributes attributes = NONE, SideEffectType side_effect_type = SideEffectType::kHasSideEffect)
Definition at line 3313 of file wasm-js.cc.
                                                                    {
  DirectHandle<String> name = v8_str(isolate, str);
  return InstallFunc(isolate, object, name, func, length, has_prototype,
                     attributes, side_effect_type);
}
References v8::internal::length, name, and v8::anonymous_namespace{wasm-js.cc}::v8_str().
Referenced by v8::internal::WasmJs::Install(), InstallConstructorFunc(), v8::internal::WasmJs::InstallJSPromiseIntegration(), v8::internal::WasmJs::InstallMemoryControl(), v8::internal::WasmJs::InstallModule(), v8::internal::WasmJs::InstallResizableBufferIntegration(), v8::internal::WasmJs::InstallTypeReflection(), and v8::internal::WasmJs::PrepareForSnapshot().
InstallFunc() [2/2]
DirectHandle<JSFunction> v8::internal::anonymous_namespace{wasm-js.cc}::InstallFunc (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< String > name, FunctionCallback func, int length, bool has_prototype = false, PropertyAttributes attributes = NONE, SideEffectType side_effect_type = SideEffectType::kHasSideEffect)
Definition at line 3299 of file wasm-js.cc.
                                                                    {
  DirectHandle<JSFunction> function =
      CreateFunc(isolate, name, func, has_prototype, side_effect_type);
  function->shared()->set_length(length);
  CHECK(!JSObject::HasRealNamedProperty(isolate, object, name).FromMaybe(true));
  CHECK(object->map()->is_extensible());
  JSObject::AddProperty(isolate, object, name, function, attributes);
  return function;
}
References CHECK, CreateFunc(), v8::internal::length, and name.
InstallGetter()
void v8::internal::anonymous_namespace{wasm-js.cc}::InstallGetter (Isolate * isolate, DirectHandle< JSObject > object, const char * str, FunctionCallback func)
Definition at line 3336 of file wasm-js.cc.
                                                           {
  DirectHandle<String> name = v8_str(isolate, str);
  DirectHandle<JSFunction> function =
      CreateFunc(isolate, GetterName(isolate, name), func, false,
                 SideEffectType::kHasNoSideEffect);
  Utils::ToLocal(object)->SetAccessorProperty(Utils::ToLocal(name),
                                              Utils::ToLocal(function),
                                              Local<Function>(), v8::None);
}
References CreateFunc(), GetterName(), v8::kHasNoSideEffect, name, v8::None, and v8::anonymous_namespace{wasm-js.cc}::v8_str().
Referenced by v8::internal::WasmJs::PrepareForSnapshot().
InstallGetterSetter()
void v8::internal::anonymous_namespace{wasm-js.cc}::InstallGetterSetter (Isolate * isolate, DirectHandle< JSObject > object, const char * str, FunctionCallback getter, FunctionCallback setter)
Definition at line 3353 of file wasm-js.cc.
                                                  {
  DirectHandle<String> name = v8_str(isolate, str);
  DirectHandle<JSFunction> getter_func =
      CreateFunc(isolate, GetterName(isolate, name), getter, false,
                 SideEffectType::kHasNoSideEffect);
  DirectHandle<JSFunction> setter_func =
      CreateFunc(isolate, SetterName(isolate, name), setter, false);
  setter_func->shared()->set_length(1);
  Utils::ToLocal(object)->SetAccessorProperty(
      Utils::ToLocal(name), Utils::ToLocal(getter_func),
      Utils::ToLocal(setter_func), v8::None);
}
References CreateFunc(), GetterName(), v8::kHasNoSideEffect, name, v8::None, v8::internal::setter, SetterName(), and v8::anonymous_namespace{wasm-js.cc}::v8_str().
Referenced by v8::internal::WasmJs::PrepareForSnapshot().
SetDummyInstanceTemplate()
void v8::internal::anonymous_namespace{wasm-js.cc}::SetDummyInstanceTemplate (Isolate * isolate, DirectHandle< JSFunction > fun)
Definition at line 3373 of file wasm-js.cc.
                                                                              {
  DirectHandle<ObjectTemplateInfo> instance_template =
      NewObjectTemplate(isolate);
  FunctionTemplateInfo::SetInstanceTemplate(
      isolate, direct_handle(fun->shared()->api_func_data(), isolate),
      instance_template);
}
References v8::internal::direct_handle(), and v8::NewObjectTemplate().
Referenced by v8::internal::WasmJs::InstallTypeReflection(), v8::internal::WasmJs::PrepareForSnapshot(), and SetupConstructor().
SetterName()
DirectHandle<String> v8::internal::anonymous_namespace{wasm-js.cc}::SetterName (Isolate * isolate, DirectHandle< String > name)
Definition at line 3348 of file wasm-js.cc.
                                                                             {
  return Name::ToFunctionName(isolate, name, isolate->factory()->set_string())
      .ToHandleChecked();
}
References v8::internal::Isolate::factory(), and name.
Referenced by InstallGetterSetter().
SetupConstructor()
DirectHandle<JSObject> v8::internal::anonymous_namespace{wasm-js.cc}::SetupConstructor (Isolate * isolate, DirectHandle< JSFunction > constructor, InstanceType instance_type, int instance_size, const char * name = nullptr, int in_object_properties = 0)
Definition at line 3381 of file wasm-js.cc.
                                                                      {
  SetDummyInstanceTemplate(isolate, constructor);
  JSFunction::EnsureHasInitialMap(isolate, constructor);
  DirectHandle<JSObject> proto(
      Cast<JSObject>(constructor->instance_prototype()), isolate);
  DirectHandle<Map> map = isolate->factory()->NewContextfulMap(
      constructor, instance_type, instance_size, TERMINAL_FAST_ELEMENTS_KIND,
      in_object_properties);
  JSFunction::SetInitialMap(isolate, constructor, map, proto);
  constexpr PropertyAttributes ro_attributes =
      static_cast<PropertyAttributes>(DONT_ENUM | READ_ONLY);
  if (name) {
    JSObject::AddProperty(isolate, proto,
                          isolate->factory()->to_string_tag_symbol(),
                          v8_str(isolate, name), ro_attributes);
  }
  return proto;
}
References v8::internal::DONT_ENUM, v8::internal::Isolate::factory(), name, v8::internal::Factory::NewContextfulMap(), v8::internal::READ_ONLY, SetDummyInstanceTemplate(), v8::internal::TERMINAL_FAST_ELEMENTS_KIND, and v8::anonymous_namespace{wasm-js.cc}::v8_str().
Referenced by v8::internal::WasmJs::InstallCustomDescriptors(), v8::internal::WasmJs::InstallJSPromiseIntegration(), v8::internal::WasmJs::InstallMemoryControl(), v8::internal::WasmJs::InstallModule(), and v8::internal::WasmJs::PrepareForSnapshot().
Variable Documentation
kWasmExceptionTagParams
constexpr wasm::ValueType v8::internal::anonymous_namespace{wasm-js.cc}::kWasmExceptionTagParams[] [constexpr]
Initial value:
= {
    wasm::kWasmExternRef,
}
Definition at line 3405 of file wasm-js.cc.
kWasmExceptionTagSignature
constexpr wasm::FunctionSig v8::internal::anonymous_namespace{wasm-js.cc}::kWasmExceptionTagSignature [constexpr]
Initial value:
{
    0, arraysize(kWasmExceptionTagParams), kWasmExceptionTagParams}
Definition at line 3408 of file wasm-js.cc.
Referenced by v8::internal::WasmJs::Install(), and v8::internal::WasmJs::PrepareForSnapshot().