cppgc::internal::anonymous_namespace{free-list.cc} Namespace Reference
Functions
uint32_t BucketIndexForSize (uint32_t size)
Function Documentation
BucketIndexForSize()
uint32_t cppgc::internal::anonymous_namespace{free-list.cc}::BucketIndexForSize (uint32_t size)
Definition at line 19 of file free-list.cc.
                                           {
  return v8::base::bits::WhichPowerOfTwo(
      v8::base::bits::RoundDownToPowerOfTwo32(size));
}
References v8::base::bits::RoundDownToPowerOfTwo32(), size(), and v8::base::bits::WhichPowerOfTwo().
Referenced by cppgc::internal::FreeList::AddReturningUnusedBounds().