v8::internal::anonymous_namespace{backing-store.cc} Namespace Reference
Classes
struct GlobalBackingStoreRegistryImpl
Enumerations
enum class AllocationStatus { kSuccess
, kSuccessAfterRetry
, kAddressSpaceLimitReachedFailure
, kOtherFailure
 }
Functions
size_t GetReservationSize (bool has_guard_regions, size_t byte_capacity, bool is_wasm_memory64)
base::AddressRegion GetReservedRegion (bool has_guard_regions, bool is_wasm_memory64, void *buffer_start, size_t byte_capacity)
void RecordStatus (Isolate *isolate, AllocationStatus status)
Variables
std::atomic< uint32_t > next_backing_store_id_ {1}
Enumeration Type Documentation
AllocationStatus
enum v8::internal::anonymous_namespace{backing-store.cc}::AllocationStatus [strong]
Enumerator
kSuccess
kSuccessAfterRetry
kAddressSpaceLimitReachedFailure
kOtherFailure
Definition at line 43 of file backing-store.cc.
                            {
  kSuccess, // Succeeded on the first try
  kSuccessAfterRetry, // Succeeded after garbage collection
  kAddressSpaceLimitReachedFailure, // Failed because Wasm is at its address
                                     // space limit
  kOtherFailure // Failed for an unknown reason
};
Function Documentation
GetReservationSize()
size_t v8::internal::anonymous_namespace{backing-store.cc}::GetReservationSize (bool has_guard_regions, size_t byte_capacity, bool is_wasm_memory64)
Definition at line 54 of file backing-store.cc.
                                                 {
#if V8_TARGET_ARCH_64_BIT && V8_ENABLE_WEBASSEMBLY
  DCHECK_IMPLIES(is_wasm_memory64 && has_guard_regions,
                 v8_flags.wasm_memory64_trap_handling);
  if (has_guard_regions) {
    if (is_wasm_memory64) {
      DCHECK_LE(byte_capacity, wasm::kMaxMemory64Size);
      return wasm::kMaxMemory64Size;
    } else {
      static_assert(kFullGuardSize32 >= size_t{4} * GB);
      DCHECK_LE(byte_capacity, size_t{4} * GB);
      return kFullGuardSize32;
    }
  }
#else
  DCHECK(!has_guard_regions);
#endif
  return byte_capacity;
}
References v8::internal::DCHECK(), DCHECK_IMPLIES, DCHECK_LE, v8::internal::GB, v8::internal::wasm::kMaxMemory64Size, and v8::internal::v8_flags.
Referenced by GetReservedRegion(), v8::internal::BackingStore::TryAllocateAndPartiallyCommitMemory(), and v8::internal::BackingStore::~BackingStore().
GetReservedRegion()
base::AddressRegion v8::internal::anonymous_namespace{backing-store.cc}::GetReservedRegion (bool has_guard_regions, bool is_wasm_memory64, void * buffer_start, size_t byte_capacity)
Definition at line 76 of file backing-store.cc.
                                                            {
  return base::AddressRegion(
      reinterpret_cast<Address>(buffer_start),
      GetReservationSize(has_guard_regions, byte_capacity, is_wasm_memory64));
}
References GetReservationSize().
Referenced by v8::internal::BackingStore::~BackingStore().
RecordStatus()
void v8::internal::anonymous_namespace{backing-store.cc}::RecordStatus (Isolate * isolate, AllocationStatus status)
Definition at line 84 of file backing-store.cc.
                                                             {
  isolate->counters()->wasm_memory_allocation_result()->AddSample(
      static_cast<int>(status));
}
References v8::internal::Isolate::counters(), and v8::internal::status.
Referenced by v8::internal::BackingStore::TryAllocateAndPartiallyCommitMemory().
Variable Documentation
next_backing_store_id_
std::atomic<uint32_t> v8::internal::anonymous_namespace{backing-store.cc}::next_backing_store_id_ {1}
Definition at line 38 of file backing-store.cc.