v8::internal::anonymous_namespace{factory-base.cc} Namespace Reference
Functions
template<typename Impl >
Handle< String > StringViewToString (FactoryBase< Impl > *factory, std::string_view string, NumberCacheMode mode)
Function Documentation
StringViewToString()
template<typename Impl >
Handle<String> v8::internal::anonymous_namespace{factory-base.cc}::StringViewToString (FactoryBase< Impl > * factory, std::string_view string, NumberCacheMode mode) [inline]
Definition at line 1010 of file factory-base.cc.
                                                                  {
  // We tenure the allocated string since it is referenced from the
  // number-string cache which lives in the old space.
  AllocationType type = mode == NumberCacheMode::kIgnore
                            ? AllocationType::kYoung
                            : AllocationType::kOld;
  return factory->NewStringFromAsciiChecked(string, type);
}
References v8::internal::kIgnore, v8::internal::kOld, v8::internal::kYoung, mode(), v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), and v8::internal::tracing::type.
Referenced by v8::internal::FactoryBase< Impl >::DoubleToString(), and v8::internal::FactoryBase< Impl >::SmiToString().