v8::internal::anonymous_namespace{builtins-array.cc} Namespace Reference
Classes
class ArrayConcatVisitor
A simple visitor visits every element of Array's.
Functions
bool IsJSArrayFastElementMovingAllowed (Isolate *isolate, Tagged< JSArray > receiver)
bool HasSimpleElements (Tagged< JSObject > current)
bool HasOnlySimpleReceiverElements (Isolate *isolate, Tagged< JSObject > receiver)
bool HasOnlySimpleElements (Isolate *isolate, Tagged< JSReceiver > receiver)
void MatchArrayElementsKindToArguments (Isolate *isolate, DirectHandle< JSArray > array, BuiltinArguments *args, int first_arg_index, int num_arguments)
V8_WARN_UNUSED_RESULT bool IsJSArrayWithExtensibleFastElements (Isolate *isolate, DirectHandle< Object > receiver, ElementsKind *elements_kind, DirectHandle< JSArray > *array)
V8_WARN_UNUSED_RESULT bool IsJSArrayWithAddableFastElements (Isolate *isolate, DirectHandle< Object > receiver, ElementsKind *kind, DirectHandle< JSArray > *array)
V8_WARN_UNUSED_RESULT Maybe< uint64_t > GetRelativeIndex (Isolate *isolate, uint64_t length, DirectHandle< Object > index, uint64_t init_if_undefined)
V8_WARN_UNUSED_RESULT Maybe< uint64_t > GetLengthProperty (Isolate *isolate, DirectHandle< JSReceiver > receiver)
V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > SetLengthProperty (Isolate *isolate, DirectHandle< JSReceiver > receiver, uint64_t length)
V8_WARN_UNUSED_RESULT Tagged< Object > GenericArrayFill (Isolate *isolate, DirectHandle< JSReceiver > receiver, DirectHandle< Object > value, double start, double end)
V8_WARN_UNUSED_RESULT MaybeDirectHandle< Map > GetReplacedElementsKindsMap (Isolate *isolate, DirectHandle< JSArray > array, ElementsKind origin_kind, ElementsKind target_kind)
V8_WARN_UNUSED_RESULT bool TryFastArrayFill (Isolate *isolate, BuiltinArguments *args, DirectHandle< JSReceiver > receiver, DirectHandle< Object > value, uint64_t start_index, uint64_t end_index)
V8_WARN_UNUSED_RESULT Tagged< Object > GenericArrayPush (Isolate *isolate, BuiltinArguments *args)
V8_WARN_UNUSED_RESULT Tagged< Object > GenericArrayPop (Isolate *isolate, BuiltinArguments *args)
V8_WARN_UNUSED_RESULT bool CanUseFastArrayModification (Isolate *isolate, DirectHandle< Object > receiver, ElementsKind *kind)
V8_WARN_UNUSED_RESULT Tagged< Object > GenericArrayShift (Isolate *isolate, DirectHandle< JSReceiver > receiver, double length)
uint32_t EstimateElementCount (Isolate *isolate, DirectHandle< JSArray > array)
void CollectElementIndices (Isolate *isolate, DirectHandle< JSObject > object, uint32_t range, std::vector< uint32_t > *indices)
bool IterateElementsSlow (Isolate *isolate, DirectHandle< JSReceiver > receiver, uint32_t length, ArrayConcatVisitor *visitor)
bool IterateElements (Isolate *isolate, DirectHandle< JSReceiver > receiver, ArrayConcatVisitor *visitor)
A helper function that visits `array` elements of a JSReceiver in numerical order.
static Maybe< bool > IsConcatSpreadable (Isolate *isolate, DirectHandle< Object > obj)
Tagged< Object > Slow_ArrayConcat (BuiltinArguments *args, DirectHandle< Object > species, Isolate *isolate)
bool IsSimpleArray (Isolate *isolate, DirectHandle< JSArray > obj)
MaybeDirectHandle< JSArray > Fast_ArrayConcat (Isolate *isolate, BuiltinArguments *args)
Function Documentation
CanUseFastArrayModification()
V8_WARN_UNUSED_RESULT bool v8::internal::anonymous_namespace{builtins-array.cc}::CanUseFastArrayModification (Isolate * isolate, DirectHandle< Object > receiver, ElementsKind * kind)
Definition at line 622 of file builtins-array.cc.
                                                                         {
#ifdef V8_ENABLE_FORCE_SLOW_PATH
  if (isolate->force_slow_path()) return false;
#endif
  if constexpr (V8_COMPRESS_POINTERS_8GB_BOOL) return false;
  DirectHandle<JSArray> array;
  return V8_LIKELY(
      IsJSArrayWithExtensibleFastElements(isolate, receiver, kind, &array) &&
      IsJSArrayFastElementMovingAllowed(isolate, *array) &&
      !JSArray::HasReadOnlyLength(array));
}
References v8::internal::Isolate::force_slow_path(), v8::internal::JSArray::HasReadOnlyLength(), IsJSArrayFastElementMovingAllowed(), IsJSArrayWithExtensibleFastElements(), V8_COMPRESS_POINTERS_8GB_BOOL, and V8_LIKELY.
Referenced by v8::internal::BUILTIN().
CollectElementIndices()
void v8::internal::anonymous_namespace{builtins-array.cc}::CollectElementIndices (Isolate * isolate, DirectHandle< JSObject > object, uint32_t range, std::vector< uint32_t > * indices)
Definition at line 1040 of file builtins-array.cc.
                                                                         {
  ElementsKind kind = object->GetElementsKind();
  switch (kind) {
    case PACKED_SMI_ELEMENTS:
    case PACKED_ELEMENTS:
    case PACKED_FROZEN_ELEMENTS:
    case PACKED_SEALED_ELEMENTS:
    case PACKED_NONEXTENSIBLE_ELEMENTS:
    case HOLEY_SMI_ELEMENTS:
    case HOLEY_FROZEN_ELEMENTS:
    case HOLEY_SEALED_ELEMENTS:
    case HOLEY_NONEXTENSIBLE_ELEMENTS:
    case HOLEY_ELEMENTS: {
      DisallowGarbageCollection no_gc;
      Tagged<FixedArray> elements = Cast<FixedArray>(object->elements());
      uint32_t length = static_cast<uint32_t>(elements->length());
      if (range < length) length = range;
      for (uint32_t i = 0; i < length; i++) {
        if (!IsTheHole(elements->get(i), isolate)) {
          indices->push_back(i);
        }
      }
      break;
    }
    case HOLEY_DOUBLE_ELEMENTS:
    case PACKED_DOUBLE_ELEMENTS: {
      if (IsFixedArray(object->elements())) {
        DCHECK_EQ(object->elements()->length(), 0);
        break;
      }
      DirectHandle<FixedDoubleArray> elements(
          Cast<FixedDoubleArray>(object->elements()), isolate);
      uint32_t length = static_cast<uint32_t>(elements->length());
      if (range < length) length = range;
      for (uint32_t i = 0; i < length; i++) {
        if (!elements->is_the_hole(i)) {
          indices->push_back(i);
        }
      }
      break;
    }
    case DICTIONARY_ELEMENTS: {
      DisallowGarbageCollection no_gc;
      Tagged<NumberDictionary> dict =
          Cast<NumberDictionary>(object->elements());
      uint32_t capacity = dict->Capacity();
      ReadOnlyRoots roots(isolate);
      FOR_WITH_HANDLE_SCOPE(isolate, uint32_t, j = 0, j, j < capacity, j++, {
        Tagged<Object> k = dict->KeyAt(InternalIndex(j));
        if (!dict->IsKey(roots, k)) continue;
        DCHECK(IsNumber(k));
        uint32_t index = static_cast<uint32_t>(Object::NumberValue(k));
        if (index < range) {
          indices->push_back(index);
        }
      });
      break;
    }
#define TYPED_ARRAY_CASE(Type, type, TYPE, ctype) case TYPE##_ELEMENTS:
      TYPED_ARRAYS(TYPED_ARRAY_CASE) RAB_GSAB_TYPED_ARRAYS(TYPED_ARRAY_CASE) {
        size_t length = Cast<JSTypedArray>(object)->GetLength();
        if (range <= length) {
          length = range;
          // We will add all indices, so we might as well clear it first
          // and avoid duplicates.
          indices->clear();
        }
        // {range} puts a cap on {length}.
        DCHECK_LE(length, std::numeric_limits<uint32_t>::max());
        for (uint32_t i = 0; i < length; i++) {
          indices->push_back(i);
        }
        if (length == range) return; // All indices accounted for already.
        break;
      }
#undef TYPED_ARRAY_CASE
    case FAST_SLOPPY_ARGUMENTS_ELEMENTS:
    case SLOW_SLOPPY_ARGUMENTS_ELEMENTS: {
      DisallowGarbageCollection no_gc;
      DisableGCMole no_gc_mole;
      Tagged<FixedArrayBase> elements = object->elements();
      Tagged<JSObject> raw_object = *object;
      ElementsAccessor* accessor = object->GetElementsAccessor();
      for (uint32_t i = 0; i < range; i++) {
        if (accessor->HasElement(isolate, raw_object, i, elements)) {
          indices->push_back(i);
        }
      }
      break;
    }
    case FAST_STRING_WRAPPER_ELEMENTS:
    case SLOW_STRING_WRAPPER_ELEMENTS: {
      DCHECK(IsJSPrimitiveWrapper(*object));
      auto js_value = Cast<JSPrimitiveWrapper>(object);
      DCHECK(IsString(js_value->value()));
      DirectHandle<String> string(Cast<String>(js_value->value()), isolate);
      uint32_t length = static_cast<uint32_t>(string->length());
      uint32_t i = 0;
      uint32_t limit = std::min(length, range);
      for (; i < limit; i++) {
        indices->push_back(i);
      }
      ElementsAccessor* accessor = object->GetElementsAccessor();
      for (; i < range; i++) {
        if (accessor->HasElement(isolate, *object, i)) {
          indices->push_back(i);
        }
      }
      break;
    }
    case WASM_ARRAY_ELEMENTS:
      // TODO(ishell): implement
      UNIMPLEMENTED();
    case SHARED_ARRAY_ELEMENTS: {
      uint32_t length = Cast<JSSharedArray>(object)->elements()->length();
      if (range <= length) {
        length = range;
        indices->clear();
      }
      for (uint32_t i = 0; i < length; i++) {
        // JSSharedArrays are created non-resizable and do not have holes.
        SLOW_DCHECK(object->GetElementsAccessor()->HasElement(
            isolate, *object, i, object->elements()));
        indices->push_back(i);
      }
      if (length == range) return;
      break;
    }
    case NO_ELEMENTS:
      break;
  }
  PrototypeIterator iter(isolate, object);
  if (!iter.IsAtEnd()) {
    // The prototype will usually have no inherited element indices,
    // but we have to check.
    // Casting to JSObject is safe because we ran {HasOnlySimpleElements} on
    // the receiver before, which checks the prototype chain.
    CollectElementIndices(
        isolate, PrototypeIterator::GetCurrent<JSObject>(iter), range, indices);
  }
}
References v8::internal::Cast< NumberDictionary >(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LE, v8::internal::DICTIONARY_ELEMENTS, v8::internal::FAST_SLOPPY_ARGUMENTS_ELEMENTS, v8::internal::FAST_STRING_WRAPPER_ELEMENTS, FOR_WITH_HANDLE_SCOPE, v8::internal::ElementsAccessor::HasElement(), v8::internal::HOLEY_DOUBLE_ELEMENTS, v8::internal::HOLEY_ELEMENTS, v8::internal::HOLEY_FROZEN_ELEMENTS, v8::internal::HOLEY_NONEXTENSIBLE_ELEMENTS, v8::internal::HOLEY_SEALED_ELEMENTS, v8::internal::HOLEY_SMI_ELEMENTS, v8::internal::index, v8::internal::PrototypeIterator::IsAtEnd(), v8::internal::IsNumber(), v8::internal::length, v8::internal::NO_ELEMENTS, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Object::NumberValue(), v8::internal::PACKED_DOUBLE_ELEMENTS, v8::internal::PACKED_ELEMENTS, v8::internal::PACKED_FROZEN_ELEMENTS, v8::internal::PACKED_NONEXTENSIBLE_ELEMENTS, v8::internal::PACKED_SEALED_ELEMENTS, v8::internal::PACKED_SMI_ELEMENTS, RAB_GSAB_TYPED_ARRAYS, v8::internal::SHARED_ARRAY_ELEMENTS, SLOW_DCHECK, v8::internal::SLOW_SLOPPY_ARGUMENTS_ELEMENTS, v8::internal::SLOW_STRING_WRAPPER_ELEMENTS, v8::internal::string, TYPED_ARRAY_CASE, TYPED_ARRAYS, v8::internal::UNIMPLEMENTED(), and v8::internal::WASM_ARRAY_ELEMENTS.
Referenced by IterateElements().
EstimateElementCount()
uint32_t v8::internal::anonymous_namespace{builtins-array.cc}::EstimateElementCount (Isolate * isolate, DirectHandle< JSArray > array)
Definition at line 963 of file builtins-array.cc.
                                                                             {
  DisallowGarbageCollection no_gc;
  uint32_t length = static_cast<uint32_t>(Object::NumberValue(array->length()));
  int element_count = 0;
  switch (array->GetElementsKind()) {
    case PACKED_SMI_ELEMENTS:
    case HOLEY_SMI_ELEMENTS:
    case PACKED_ELEMENTS:
    case PACKED_FROZEN_ELEMENTS:
    case PACKED_SEALED_ELEMENTS:
    case PACKED_NONEXTENSIBLE_ELEMENTS:
    case HOLEY_FROZEN_ELEMENTS:
    case HOLEY_SEALED_ELEMENTS:
    case HOLEY_NONEXTENSIBLE_ELEMENTS:
    case HOLEY_ELEMENTS: {
      // Fast elements can't have lengths that are not representable by
      // a 32-bit signed integer.
      static_assert(static_cast<int32_t>(FixedArray::kMaxLength) >= 0);
      int fast_length = static_cast<int>(length);
      Tagged<FixedArray> elements = Cast<FixedArray>(array->elements());
      for (int i = 0; i < fast_length; i++) {
        if (!IsTheHole(elements->get(i), isolate)) element_count++;
      }
      break;
    }
    case PACKED_DOUBLE_ELEMENTS:
    case HOLEY_DOUBLE_ELEMENTS: {
      // Fast elements can't have lengths that are not representable by
      // a 32-bit signed integer.
      static_assert(static_cast<int32_t>(FixedDoubleArray::kMaxLength) >= 0);
      int fast_length = static_cast<int>(length);
      if (IsFixedArray(array->elements())) {
        DCHECK_EQ(Cast<FixedArray>(array->elements())->length(), 0);
        break;
      }
      Tagged<FixedDoubleArray> elements =
          Cast<FixedDoubleArray>(array->elements());
      for (int i = 0; i < fast_length; i++) {
        if (!elements->is_the_hole(i)) element_count++;
      }
      break;
    }
    case DICTIONARY_ELEMENTS: {
      Tagged<NumberDictionary> dictionary =
          Cast<NumberDictionary>(array->elements());
      ReadOnlyRoots roots(isolate);
      for (InternalIndex i : dictionary->IterateEntries()) {
        Tagged<Object> key = dictionary->KeyAt(i);
        if (dictionary->IsKey(roots, key)) {
          element_count++;
        }
      }
      break;
    }
#define TYPED_ARRAY_CASE(Type, type, TYPE, ctype) case TYPE##_ELEMENTS:
      TYPED_ARRAYS(TYPED_ARRAY_CASE)
      RAB_GSAB_TYPED_ARRAYS(TYPED_ARRAY_CASE)
      // External arrays are always dense.
      return length;
#undef TYPED_ARRAY_CASE
    case NO_ELEMENTS:
      return 0;
    case FAST_SLOPPY_ARGUMENTS_ELEMENTS:
    case SLOW_SLOPPY_ARGUMENTS_ELEMENTS:
    case FAST_STRING_WRAPPER_ELEMENTS:
    case SLOW_STRING_WRAPPER_ELEMENTS:
    case WASM_ARRAY_ELEMENTS:
    case SHARED_ARRAY_ELEMENTS:
      UNREACHABLE();
  }
  // As an estimate, we assume that the prototype doesn't contain any
  // inherited elements.
  return element_count;
}
References v8::internal::Cast< NumberDictionary >(), DCHECK_EQ, v8::internal::DICTIONARY_ELEMENTS, v8::internal::FAST_SLOPPY_ARGUMENTS_ELEMENTS, v8::internal::FAST_STRING_WRAPPER_ELEMENTS, v8::internal::HOLEY_DOUBLE_ELEMENTS, v8::internal::HOLEY_ELEMENTS, v8::internal::HOLEY_FROZEN_ELEMENTS, v8::internal::HOLEY_NONEXTENSIBLE_ELEMENTS, v8::internal::HOLEY_SEALED_ELEMENTS, v8::internal::HOLEY_SMI_ELEMENTS, v8::internal::key, v8::internal::FixedArray::kMaxLength, v8::internal::PrimitiveArrayBase< FixedDoubleArray, FixedDoubleArrayShape >::kMaxLength, v8::internal::length, v8::internal::NO_ELEMENTS, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Object::NumberValue(), v8::internal::PACKED_DOUBLE_ELEMENTS, v8::internal::PACKED_ELEMENTS, v8::internal::PACKED_FROZEN_ELEMENTS, v8::internal::PACKED_NONEXTENSIBLE_ELEMENTS, v8::internal::PACKED_SEALED_ELEMENTS, v8::internal::PACKED_SMI_ELEMENTS, RAB_GSAB_TYPED_ARRAYS, v8::internal::SHARED_ARRAY_ELEMENTS, v8::internal::SLOW_SLOPPY_ARGUMENTS_ELEMENTS, v8::internal::SLOW_STRING_WRAPPER_ELEMENTS, TYPED_ARRAY_CASE, TYPED_ARRAYS, v8::internal::UNREACHABLE(), and v8::internal::WASM_ARRAY_ELEMENTS.
Referenced by Slow_ArrayConcat().
Fast_ArrayConcat()
MaybeDirectHandle<JSArray> v8::internal::anonymous_namespace{builtins-array.cc}::Fast_ArrayConcat (Isolate * isolate, BuiltinArguments * args)
Definition at line 1645 of file builtins-array.cc.
                                                                    {
  if (!Protectors::IsIsConcatSpreadableLookupChainIntact(isolate)) {
    return {};
  }
  // We shouldn't overflow when adding another len.
  const int kHalfOfMaxInt = 1 << (kBitsPerInt - 2);
  static_assert(FixedArray::kMaxLength < kHalfOfMaxInt);
  static_assert(FixedDoubleArray::kMaxLength < kHalfOfMaxInt);
  USE(kHalfOfMaxInt);
  int n_arguments = args->length();
  int result_len = 0;
  {
    DisallowGarbageCollection no_gc;
    // Iterate through all the arguments performing checks
    // and calculating total length.
    for (int i = 0; i < n_arguments; i++) {
      Tagged<Object> arg = (*args)[i];
      if (!IsJSArray(arg)) return {};
      if (!HasOnlySimpleReceiverElements(isolate, Cast<JSObject>(arg))) {
        return {};
      }
      // TODO(cbruni): support fast concatenation of DICTIONARY_ELEMENTS.
      if (!Cast<JSObject>(arg)->HasFastElements()) {
        return {};
      }
      DirectHandle<JSArray> array(Cast<JSArray>(arg), isolate);
      if (!IsSimpleArray(isolate, array)) {
        return {};
      }
      // The Array length is guaranteed to be <= kHalfOfMaxInt thus we won't
      // overflow.
      result_len += Smi::ToInt(array->length());
      DCHECK_GE(result_len, 0);
      // Throw an Error if we overflow the FixedArray limits
      if (FixedDoubleArray::kMaxLength < result_len ||
          FixedArray::kMaxLength < result_len) {
        AllowGarbageCollection gc;
        THROW_NEW_ERROR(isolate,
                        NewRangeError(MessageTemplate::kInvalidArrayLength));
      }
    }
  }
  return ElementsAccessor::Concat(isolate, args, n_arguments, result_len);
}
References v8::base::args, v8::internal::ElementsAccessor::Concat(), DCHECK_GE, HasOnlySimpleReceiverElements(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, IsSimpleArray(), v8::internal::kBitsPerInt, v8::internal::FixedArray::kMaxLength, v8::internal::PrimitiveArrayBase< FixedDoubleArray, FixedDoubleArrayShape >::kMaxLength, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, THROW_NEW_ERROR, v8::internal::Smi::ToInt(), and USE.
Referenced by v8::internal::BUILTIN().
GenericArrayFill()
V8_WARN_UNUSED_RESULT Tagged<Object> v8::internal::anonymous_namespace{builtins-array.cc}::GenericArrayFill (Isolate * isolate, DirectHandle< JSReceiver > receiver, DirectHandle< Object > value, double start, double end)
Definition at line 212 of file builtins-array.cc.
                                                          {
  // 7. Repeat, while k < final.
  FOR_WITH_HANDLE_SCOPE(isolate, double, k = start, k, k < end, k++, {
    // a. Let Pk be ! ToString(k).
    PropertyKey key(isolate, k);
    // b. Perform ? Set(O, Pk, value, true).
    RETURN_ON_EXCEPTION_VALUE(
        isolate,
        Object::SetPropertyOrElement(isolate, receiver, key, value,
                                     Just(ShouldThrow::kThrowOnError),
                                     StoreOrigin::kMaybeKeyed),
        ReadOnlyRoots(isolate).exception());
    // c. Increase k by 1.
  });
  // 8. Return O.
  return *receiver;
}
References v8::internal::compiler::end(), FOR_WITH_HANDLE_SCOPE, v8::Just(), v8::internal::key, v8::internal::kMaybeKeyed, v8::internal::kThrowOnError, RETURN_ON_EXCEPTION_VALUE, v8::internal::Object::SetPropertyOrElement(), and v8::internal::value.
Referenced by v8::internal::BUILTIN().
GenericArrayPop()
V8_WARN_UNUSED_RESULT Tagged<Object> v8::internal::anonymous_namespace{builtins-array.cc}::GenericArrayPop (Isolate * isolate, BuiltinArguments * args)
Definition at line 521 of file builtins-array.cc.
                                                                             {
  // 1. Let O be ? ToObject(this value).
  DirectHandle<JSReceiver> receiver;
  ASSIGN_RETURN_FAILURE_ON_EXCEPTION(
      isolate, receiver, Object::ToObject(isolate, args->receiver()));
  // 2. Let len be ? ToLength(? Get(O, "length")).
  DirectHandle<Object> raw_length_number;
  ASSIGN_RETURN_FAILURE_ON_EXCEPTION(
      isolate, raw_length_number,
      Object::GetLengthFromArrayLike(isolate, receiver));
  double length = Object::NumberValue(*raw_length_number);
  // 3. If len is zero, then.
  if (length == 0) {
    // a. Perform ? Set(O, "length", 0, true).
    RETURN_FAILURE_ON_EXCEPTION(
        isolate, Object::SetProperty(isolate, receiver,
                                     isolate->factory()->length_string(),
                                     direct_handle(Smi::zero(), isolate),
                                     StoreOrigin::kMaybeKeyed,
                                     Just(ShouldThrow::kThrowOnError)));
    // b. Return undefined.
    return ReadOnlyRoots(isolate).undefined_value();
  }
  // 4. Else len > 0.
  // a. Let new_len be len-1.
  DirectHandle<Object> new_length = isolate->factory()->NewNumber(length - 1);
  // b. Let index be ! ToString(newLen).
  PropertyKey index(isolate, new_length);
  // c. Let element be ? Get(O, index).
  DirectHandle<Object> element;
  ASSIGN_RETURN_FAILURE_ON_EXCEPTION(
      isolate, element, Object::GetPropertyOrElement(isolate, receiver, index));
  // d. Perform ? DeletePropertyOrThrow(O, index).
  MAYBE_RETURN(JSReceiver::DeletePropertyOrElement(isolate, receiver, index,
                                                   LanguageMode::kStrict),
               ReadOnlyRoots(isolate).exception());
  // e. Perform ? Set(O, "length", newLen, true).
  RETURN_FAILURE_ON_EXCEPTION(
      isolate, Object::SetProperty(isolate, receiver,
                                   isolate->factory()->length_string(),
                                   new_length, StoreOrigin::kMaybeKeyed,
                                   Just(ShouldThrow::kThrowOnError)));
  // f. Return element.
  return *element;
}
References v8::base::args, ASSIGN_RETURN_FAILURE_ON_EXCEPTION, v8::internal::JSReceiver::DeletePropertyOrElement(), v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::Object::GetLengthFromArrayLike(), v8::internal::Object::GetPropertyOrElement(), v8::internal::index, v8::Just(), v8::internal::kMaybeKeyed, v8::internal::kStrict, v8::internal::kThrowOnError, v8::internal::length, MAYBE_RETURN, v8::internal::FactoryBase< Impl >::NewNumber(), v8::internal::Object::NumberValue(), RETURN_FAILURE_ON_EXCEPTION, v8::internal::Object::SetProperty(), v8::Value::ToObject(), and v8::internal::Smi::zero().
Referenced by v8::internal::BUILTIN().
GenericArrayPush()
V8_WARN_UNUSED_RESULT Tagged<Object> v8::internal::anonymous_namespace{builtins-array.cc}::GenericArrayPush (Isolate * isolate, BuiltinArguments * args)
Definition at line 421 of file builtins-array.cc.
                                                                              {
  // 1. Let O be ? ToObject(this value).
  DirectHandle<JSReceiver> receiver;
  ASSIGN_RETURN_FAILURE_ON_EXCEPTION(
      isolate, receiver, Object::ToObject(isolate, args->receiver()));
  // 2. Let len be ? ToLength(? Get(O, "length")).
  DirectHandle<Object> raw_length_number;
  ASSIGN_RETURN_FAILURE_ON_EXCEPTION(
      isolate, raw_length_number,
      Object::GetLengthFromArrayLike(isolate, receiver));
  // 3. Let args be a List whose elements are, in left to right order,
  // the arguments that were passed to this function invocation.
  // 4. Let arg_count be the number of elements in args.
  int arg_count = args->length() - 1;
  // 5. If len + arg_count > 2^53-1, throw a TypeError exception.
  double length = Object::NumberValue(*raw_length_number);
  if (arg_count > kMaxSafeInteger - length) {
    THROW_NEW_ERROR_RETURN_FAILURE(
        isolate, NewTypeError(MessageTemplate::kPushPastSafeLength,
                              isolate->factory()->NewNumberFromInt(arg_count),
                              raw_length_number));
  }
  // 6. Repeat, while args is not empty.
  for (int i = 0; i < arg_count; ++i) {
    // a. Remove the first element from args and let E be the value of the
    // element.
    DirectHandle<Object> element = args->at(i + 1);
    // b. Perform ? Set(O, ! ToString(len), E, true).
    if (length <= JSObject::kMaxElementIndex) {
      RETURN_FAILURE_ON_EXCEPTION(
          isolate, Object::SetElement(isolate, receiver, length, element,
                                      ShouldThrow::kThrowOnError));
    } else {
      PropertyKey key(isolate, length);
      LookupIterator it(isolate, receiver, key);
      MAYBE_RETURN(Object::SetProperty(&it, element, StoreOrigin::kMaybeKeyed,
                                       Just(ShouldThrow::kThrowOnError)),
                   ReadOnlyRoots(isolate).exception());
    }
    // c. Let len be len+1.
    ++length;
  }
  // 7. Perform ? Set(O, "length", len, true).
  DirectHandle<Object> final_length = isolate->factory()->NewNumber(length);
  RETURN_FAILURE_ON_EXCEPTION(
      isolate, Object::SetProperty(isolate, receiver,
                                   isolate->factory()->length_string(),
                                   final_length, StoreOrigin::kMaybeKeyed,
                                   Just(ShouldThrow::kThrowOnError)));
  // 8. Return len.
  return *final_length;
}
References v8::base::args, ASSIGN_RETURN_FAILURE_ON_EXCEPTION, v8::internal::Isolate::factory(), v8::internal::Object::GetLengthFromArrayLike(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::Just(), v8::internal::key, v8::internal::JSObject::kMaxElementIndex, v8::internal::kMaxSafeInteger, v8::internal::kMaybeKeyed, v8::internal::kThrowOnError, v8::internal::length, MAYBE_RETURN, v8::internal::FactoryBase< Impl >::NewNumber(), v8::internal::FactoryBase< Impl >::NewNumberFromInt(), v8::internal::Object::NumberValue(), RETURN_FAILURE_ON_EXCEPTION, v8::internal::Object::SetElement(), v8::internal::Object::SetProperty(), THROW_NEW_ERROR_RETURN_FAILURE, and v8::Value::ToObject().
Referenced by v8::internal::BUILTIN().
GenericArrayShift()
V8_WARN_UNUSED_RESULT Tagged<Object> v8::internal::anonymous_namespace{builtins-array.cc}::GenericArrayShift (Isolate * isolate, DirectHandle< JSReceiver > receiver, double length)
Definition at line 636 of file builtins-array.cc.
                                                                        {
  // 4. Let first be ? Get(O, "0").
  DirectHandle<Object> first;
  ASSIGN_RETURN_FAILURE_ON_EXCEPTION(isolate, first,
                                     Object::GetElement(isolate, receiver, 0));
  // 5. Let k be 1.
  // 6. Repeat, while k < len.
  FOR_WITH_HANDLE_SCOPE(isolate, double, k = 1, k, k < length, k++, {
    // a. Let from be ! ToString(k).
    PropertyKey from(isolate, k);
    // b. Let to be ! ToString(k-1).
    PropertyKey to(isolate, k - 1);
    // c. Let fromPresent be ? HasProperty(O, from).
    bool from_present;
    MAYBE_ASSIGN_RETURN_FAILURE_ON_EXCEPTION(
        isolate, from_present,
        JSReceiver::HasPropertyOrElement(isolate, receiver, from));
    // d. If fromPresent is true, then.
    if (from_present) {
      // i. Let fromVal be ? Get(O, from).
      DirectHandle<Object> from_val;
      ASSIGN_RETURN_FAILURE_ON_EXCEPTION(
          isolate, from_val,
          Object::GetPropertyOrElement(isolate, receiver, from));
      // ii. Perform ? Set(O, to, fromVal, true).
      RETURN_FAILURE_ON_EXCEPTION(isolate, Object::SetPropertyOrElement(
                                               isolate, receiver, to, from_val,
                                               Just(ShouldThrow::kThrowOnError),
                                               StoreOrigin::kMaybeKeyed));
    } else { // e. Else fromPresent is false,
      // i. Perform ? DeletePropertyOrThrow(O, to).
      MAYBE_RETURN(JSReceiver::DeletePropertyOrElement(isolate, receiver, to,
                                                       LanguageMode::kStrict),
                   ReadOnlyRoots(isolate).exception());
    }
    // f. Increase k by 1.
  });
  // 7. Perform ? DeletePropertyOrThrow(O, ! ToString(len-1)).
  PropertyKey new_length_key(isolate, length - 1);
  MAYBE_RETURN(JSReceiver::DeletePropertyOrElement(
                   isolate, receiver, new_length_key, LanguageMode::kStrict),
               ReadOnlyRoots(isolate).exception());
  // 8. Perform ? Set(O, "length", len-1, true).
  RETURN_FAILURE_ON_EXCEPTION(isolate,
                              SetLengthProperty(isolate, receiver, length - 1));
  // 9. Return first.
  return *first;
}
References ASSIGN_RETURN_FAILURE_ON_EXCEPTION, v8::internal::JSReceiver::DeletePropertyOrElement(), FOR_WITH_HANDLE_SCOPE, v8::internal::Object::GetElement(), v8::internal::Object::GetPropertyOrElement(), v8::internal::JSReceiver::HasPropertyOrElement(), v8::Just(), v8::internal::kMaybeKeyed, v8::internal::kStrict, v8::internal::kThrowOnError, v8::internal::length, MAYBE_ASSIGN_RETURN_FAILURE_ON_EXCEPTION, MAYBE_RETURN, RETURN_FAILURE_ON_EXCEPTION, SetLengthProperty(), and v8::internal::Object::SetPropertyOrElement().
Referenced by v8::internal::BUILTIN().
GetLengthProperty()
V8_WARN_UNUSED_RESULT Maybe<uint64_t> v8::internal::anonymous_namespace{builtins-array.cc}::GetLengthProperty (Isolate * isolate, DirectHandle< JSReceiver > receiver)
Definition at line 174 of file builtins-array.cc.
                                                         {
  if (V8_LIKELY(IsJSArray(*receiver))) {
    auto array = Cast<JSArray>(receiver);
    uint32_t length;
    CHECK(Object::ToArrayLength(array->length(), &length));
    DCHECK(0 <= length && length <= kMaxSafeInteger);
    return Just(uint64_t{length});
  }
  DirectHandle<Object> raw_length_number;
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, raw_length_number,
      Object::GetLengthFromArrayLike(isolate, receiver), Nothing<uint64_t>());
  return Just(static_cast<uint64_t>(Object::NumberValue(*raw_length_number)));
}
References ASSIGN_RETURN_ON_EXCEPTION_VALUE, CHECK, v8::internal::DCHECK(), v8::internal::Object::GetLengthFromArrayLike(), v8::Just(), v8::internal::kMaxSafeInteger, v8::internal::length, v8::internal::Object::NumberValue(), v8::internal::Object::ToArrayLength(), and V8_LIKELY.
Referenced by v8::internal::BUILTIN().
GetRelativeIndex()
V8_WARN_UNUSED_RESULT Maybe<uint64_t> v8::internal::anonymous_namespace{builtins-array.cc}::GetRelativeIndex (Isolate * isolate, uint64_t length, DirectHandle< Object > index, uint64_t init_if_undefined)
Definition at line 150 of file builtins-array.cc.
                                {
  int64_t relative_index = init_if_undefined;
  if (!IsUndefined(*index)) {
    double provided_relative_index;
    MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(isolate, provided_relative_index,
                                           Object::IntegerValue(isolate, index),
                                           Nothing<uint64_t>());
    if (std::abs(provided_relative_index) > length) {
      return Just(provided_relative_index < 0 ? 0 : length);
    }
    relative_index = static_cast<int64_t>(provided_relative_index);
  }
  if (relative_index < 0) {
    return Just(static_cast<uint64_t>(
        std::max<int64_t>(static_cast<int64_t>(length) + relative_index, 0)));
  }
  return Just(std::min(static_cast<uint64_t>(relative_index), length));
}
References v8::internal::index, v8::Value::IntegerValue(), v8::Just(), v8::internal::length, and MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE.
Referenced by v8::internal::BUILTIN().
GetReplacedElementsKindsMap()
V8_WARN_UNUSED_RESULT MaybeDirectHandle<Map> v8::internal::anonymous_namespace{builtins-array.cc}::GetReplacedElementsKindsMap (Isolate * isolate, DirectHandle< JSArray > array, ElementsKind origin_kind, ElementsKind target_kind)
Definition at line 240 of file builtins-array.cc.
                              {
  Tagged<Map> map = array->map();
  // Fast check for JSArrays without properties.
  {
    DisallowGarbageCollection no_gc;
    Tagged<Context> native_context = map->map()->native_context();
    if (native_context->GetInitialJSArrayMap(origin_kind) == map) {
      Tagged<Object> maybe_target_map =
          native_context->GetNoCell(Context::ArrayMapIndex(target_kind));
      if (Tagged<Map> target_map; TryCast<Map>(maybe_target_map, &target_map)) {
        map->NotifyLeafMapLayoutChange(isolate);
        return direct_handle(target_map, isolate);
      }
    }
  }
  // Ideally here we would reconfigure the map to an earlier ElementsKind with:
  // ```
  // MapUpdater{isolate, direct_handle(map, isolate)}
  // .ReconfigureElementsKind(target_kind);
  // ```
  // However, this currently treats this as an invalid ElementsKind transition,
  // and normalizes the map.
  // TODO(leszeks): Handle this case.
  return {};
}
References v8::internal::Context::ArrayMapIndex(), v8::internal::direct_handle(), v8::internal::native_context, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by TryFastArrayFill().
HasOnlySimpleElements()
bool v8::internal::anonymous_namespace{builtins-array.cc}::HasOnlySimpleElements (Isolate * isolate, Tagged< JSReceiver > receiver) [inline]
Definition at line 57 of file builtins-array.cc.
                                                               {
  DisallowGarbageCollection no_gc;
  PrototypeIterator iter(isolate, receiver, kStartAtReceiver);
  for (; !iter.IsAtEnd(); iter.Advance()) {
    if (!IsJSObject(iter.GetCurrent())) return false;
    Tagged<JSObject> current = iter.GetCurrent<JSObject>();
    if (!HasSimpleElements(current)) return false;
  }
  return true;
}
References v8::internal::PrototypeIterator::Advance(), v8::internal::PrototypeIterator::GetCurrent(), HasSimpleElements(), v8::internal::PrototypeIterator::IsAtEnd(), v8::internal::kStartAtReceiver, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by IterateElements().
HasOnlySimpleReceiverElements()
bool v8::internal::anonymous_namespace{builtins-array.cc}::HasOnlySimpleReceiverElements (Isolate * isolate, Tagged< JSObject > receiver) [inline]
Definition at line 50 of file builtins-array.cc.
                                                                     {
  // Check that we have no accessors on the receiver's elements.
  if (!HasSimpleElements(receiver)) return false;
  return JSObject::PrototypeHasNoElements(isolate, receiver);
}
References HasSimpleElements(), and v8::internal::JSObject::PrototypeHasNoElements().
Referenced by Fast_ArrayConcat().
HasSimpleElements()
bool v8::internal::anonymous_namespace{builtins-array.cc}::HasSimpleElements (Tagged< JSObject > current) [inline]
Definition at line 45 of file builtins-array.cc.
                                                        {
  return !IsCustomElementsReceiverMap(current->map()) &&
         !current->GetElementsAccessor()->HasAccessors(current);
}
References v8::internal::IsCustomElementsReceiverMap().
Referenced by HasOnlySimpleElements(), and HasOnlySimpleReceiverElements().
IsConcatSpreadable()
static Maybe<bool> v8::internal::anonymous_namespace{builtins-array.cc}::IsConcatSpreadable (Isolate * isolate, DirectHandle< Object > obj) [static]
Definition at line 1385 of file builtins-array.cc.
                                                                {
  HandleScope handle_scope(isolate);
  DirectHandle<JSReceiver> receiver;
  if (!TryCast<JSReceiver>(obj, &receiver)) return Just(false);
  if (!Protectors::IsIsConcatSpreadableLookupChainIntact(isolate) ||
      receiver->HasProxyInPrototype(isolate)) {
    // Slow path if @@isConcatSpreadable has been used.
    DirectHandle<Symbol> key(isolate->factory()->is_concat_spreadable_symbol());
    DirectHandle<Object> value;
    MaybeDirectHandle<Object> maybeValue =
        i::Runtime::GetObjectProperty(isolate, receiver, key);
    if (!maybeValue.ToHandle(&value)) return Nothing<bool>();
    if (!IsUndefined(*value, isolate))
      return Just(Object::BooleanValue(*value, isolate));
  }
  return Object::IsArray(receiver);
}
References v8::internal::Object::BooleanValue(), v8::internal::Isolate::factory(), v8::internal::Runtime::GetObjectProperty(), v8::internal::Object::IsArray(), v8::Just(), v8::internal::key, v8::internal::MaybeDirectHandle< T >::ToHandle(), and v8::internal::value.
Referenced by Slow_ArrayConcat().
IsJSArrayFastElementMovingAllowed()
bool v8::internal::anonymous_namespace{builtins-array.cc}::IsJSArrayFastElementMovingAllowed (Isolate * isolate, Tagged< JSArray > receiver) [inline]
Definition at line 34 of file builtins-array.cc.
                                                                        {
  Tagged<NativeContext> context = receiver->GetCreationContext().value();
  Tagged<Map> map = receiver->map();
  if (V8_LIKELY(map->prototype() == context->initial_array_prototype()) &&
      Protectors::IsNoElementsIntact(isolate)) {
    return true;
  }
  return V8_LIKELY(JSObject::PrototypeHasNoElements(isolate, receiver));
}
References v8::internal::JSObject::PrototypeHasNoElements(), and V8_LIKELY.
Referenced by v8::internal::BUILTIN(), CanUseFastArrayModification(), and IsJSArrayWithAddableFastElements().
IsJSArrayWithAddableFastElements()
V8_WARN_UNUSED_RESULT bool v8::internal::anonymous_namespace{builtins-array.cc}::IsJSArrayWithAddableFastElements (Isolate * isolate, DirectHandle< Object > receiver, ElementsKind * kind, DirectHandle< JSArray > * array) [inline]
Definition at line 128 of file builtins-array.cc.
                                                                           {
  if (!IsJSArrayWithExtensibleFastElements(isolate, receiver, kind, array))
    return false;
  // If there may be elements accessors in the prototype chain, the fast path
  // cannot be used if there arguments to add to the array.
  if (!IsJSArrayFastElementMovingAllowed(isolate, **array)) return false;
  // Adding elements to the array prototype would break code that makes sure
  // it has no elements. Handle that elsewhere.
  if (isolate->IsInitialArrayPrototype(**array)) return false;
  return true;
}
References v8::internal::Isolate::IsInitialArrayPrototype(), IsJSArrayFastElementMovingAllowed(), and IsJSArrayWithExtensibleFastElements().
Referenced by v8::internal::BUILTIN(), and TryFastArrayFill().
IsJSArrayWithExtensibleFastElements()
V8_WARN_UNUSED_RESULT bool v8::internal::anonymous_namespace{builtins-array.cc}::IsJSArrayWithExtensibleFastElements (Isolate * isolate, DirectHandle< Object > receiver, ElementsKind * elements_kind, DirectHandle< JSArray > * array) [inline]
Definition at line 112 of file builtins-array.cc.
                                                               {
  if (V8_UNLIKELY(!TryCast<JSArray>(receiver, array))) return false;
  *elements_kind = (*array)->GetElementsKind();
  if (V8_LIKELY(IsFastElementsKind(*elements_kind))) {
    DCHECK(!IsDictionaryElementsKind(*elements_kind));
    DCHECK((*array)->map()->is_extensible());
    return true;
  }
  return false;
}
References v8::internal::DCHECK(), v8::internal::IsDictionaryElementsKind(), v8::internal::IsFastElementsKind(), V8_LIKELY, and V8_UNLIKELY.
Referenced by v8::internal::BUILTIN(), CanUseFastArrayModification(), and IsJSArrayWithAddableFastElements().
IsSimpleArray()
bool v8::internal::anonymous_namespace{builtins-array.cc}::IsSimpleArray (Isolate * isolate, DirectHandle< JSArray > obj)
Definition at line 1631 of file builtins-array.cc.
                                                                {
  DisallowGarbageCollection no_gc;
  Tagged<Map> map = obj->map();
  // If there is only the 'length' property we are fine.
  if (map->prototype() ==
          isolate->native_context()->initial_array_prototype() &&
      map->NumberOfOwnDescriptors() == 1) {
    return true;
  }
  // TODO(cbruni): slower lookup for array subclasses and support slow
  // @@IsConcatSpreadable lookup.
  return false;
}
References v8::internal::Isolate::native_context(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by Fast_ArrayConcat().
IterateElements()
bool v8::internal::anonymous_namespace{builtins-array.cc}::IterateElements (Isolate * isolate, DirectHandle< JSReceiver > receiver, ArrayConcatVisitor * visitor)
A helper function that visits `array` elements of a JSReceiver in numerical order.
The visitor argument called for each existing element in the array with the element index and the element's value. Afterwards it increments the base-index of the visitor by the array length. Returns false if any access threw an exception, otherwise true.
Definition at line 1212 of file builtins-array.cc.
                                                  {
  uint32_t length = 0;
  if (IsJSArray(*receiver)) {
    auto array = Cast<JSArray>(receiver);
    length = static_cast<uint32_t>(Object::NumberValue(array->length()));
  } else {
    DirectHandle<Object> val;
    ASSIGN_RETURN_ON_EXCEPTION_VALUE(
        isolate, val, Object::GetLengthFromArrayLike(isolate, receiver), false);
    if (visitor->index_offset() + Object::NumberValue(*val) > kMaxSafeInteger) {
      isolate->Throw(*isolate->factory()->NewTypeError(
          MessageTemplate::kInvalidArrayLength));
      return false;
    }
    // TODO(caitp): Support larger element indexes (up to 2^53-1).
    if (!Object::ToUint32(*val, &length)) {
      length = 0;
    }
    // TODO(cbruni): handle other element kind as well
    return IterateElementsSlow(isolate, receiver, length, visitor);
  }
  if (!visitor->has_simple_elements() ||
      !HasOnlySimpleElements(isolate, *receiver)) {
    return IterateElementsSlow(isolate, receiver, length, visitor);
  }
  DirectHandle<JSArray> array = Cast<JSArray>(receiver);
  switch (array->GetElementsKind()) {
    case PACKED_SMI_ELEMENTS:
    case PACKED_ELEMENTS:
    case PACKED_FROZEN_ELEMENTS:
    case PACKED_SEALED_ELEMENTS:
    case PACKED_NONEXTENSIBLE_ELEMENTS:
    case HOLEY_SMI_ELEMENTS:
    case HOLEY_FROZEN_ELEMENTS:
    case HOLEY_SEALED_ELEMENTS:
    case HOLEY_NONEXTENSIBLE_ELEMENTS:
    case HOLEY_ELEMENTS: {
      // Disallow execution so the cached elements won't change mid execution.
      DisallowJavascriptExecution no_js(isolate);
      // Run through the elements FixedArray and use HasElement and GetElement
      // to check the prototype for missing elements.
      DirectHandle<FixedArray> elements(Cast<FixedArray>(array->elements()),
                                        isolate);
      int fast_length = static_cast<int>(length);
      DCHECK(fast_length <= elements->length());
      FOR_WITH_HANDLE_SCOPE(isolate, int, j = 0, j, j < fast_length, j++, {
        DirectHandle<Object> element_value(elements->get(j), isolate);
        if (!IsTheHole(*element_value, isolate)) {
          if (!visitor->visit(j, element_value)) return false;
        } else {
          Maybe<bool> maybe = JSReceiver::HasElement(isolate, array, j);
          if (maybe.IsNothing()) return false;
          if (maybe.FromJust()) {
            // Call GetElement on array, not its prototype, or getters won't
            // have the correct receiver.
            ASSIGN_RETURN_ON_EXCEPTION_VALUE(
                isolate, element_value,
                JSReceiver::GetElement(isolate, array, j), false);
            if (!visitor->visit(j, element_value)) return false;
          }
        }
      });
      break;
    }
    case HOLEY_DOUBLE_ELEMENTS:
    case PACKED_DOUBLE_ELEMENTS: {
      // Disallow execution so the cached elements won't change mid execution.
      DisallowJavascriptExecution no_js(isolate);
      // Empty array is FixedArray but not FixedDoubleArray.
      if (length == 0) break;
      // Run through the elements FixedArray and use HasElement and GetElement
      // to check the prototype for missing elements.
      if (IsFixedArray(array->elements())) {
        DCHECK_EQ(array->elements()->length(), 0);
        break;
      }
      DirectHandle<FixedDoubleArray> elements(
          Cast<FixedDoubleArray>(array->elements()), isolate);
      int fast_length = static_cast<int>(length);
      DCHECK(fast_length <= elements->length());
      FOR_WITH_HANDLE_SCOPE(isolate, int, j = 0, j, j < fast_length, j++, {
        if (elements->is_the_hole(j)) {
          Maybe<bool> maybe = JSReceiver::HasElement(isolate, array, j);
          if (maybe.IsNothing()) return false;
          if (maybe.FromJust()) {
            // Call GetElement on array, not its prototype, or getters won't
            // have the correct receiver.
            DirectHandle<Object> element_value;
            ASSIGN_RETURN_ON_EXCEPTION_VALUE(
                isolate, element_value,
                JSReceiver::GetElement(isolate, array, j), false);
            if (!visitor->visit(j, element_value)) return false;
          }
#ifdef V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
        } else if (elements->is_undefined(j)) {
          DirectHandle<Object> element_value =
              isolate->factory()->undefined_value();
          if (!visitor->visit(j, element_value)) return false;
#endif // V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
        } else {
          double double_value = elements->get_scalar(j);
          DirectHandle<Object> element_value =
              isolate->factory()->NewNumber(double_value);
          if (!visitor->visit(j, element_value)) return false;
        }
      });
      break;
    }
    case DICTIONARY_ELEMENTS: {
      // Disallow execution so the cached dictionary won't change mid execution.
      DisallowJavascriptExecution no_js(isolate);
      DirectHandle<NumberDictionary> dict(array->element_dictionary(), isolate);
      std::vector<uint32_t> indices;
      indices.reserve(dict->Capacity() / 2);
      // Collect all indices in the object and the prototypes less
      // than length. This might introduce duplicates in the indices list.
      CollectElementIndices(isolate, array, length, &indices);
      std::sort(indices.begin(), indices.end());
      size_t n = indices.size();
      FOR_WITH_HANDLE_SCOPE(isolate, size_t, j = 0, j, j < n, (void)0, {
        uint32_t index = indices[j];
        DirectHandle<Object> element;
        ASSIGN_RETURN_ON_EXCEPTION_VALUE(
            isolate, element, JSReceiver::GetElement(isolate, array, index),
            false);
        if (!visitor->visit(index, element)) return false;
        // Skip to next different index (i.e., omit duplicates).
        do {
          j++;
        } while (j < n && indices[j] == index);
      });
      break;
    }
    case FAST_SLOPPY_ARGUMENTS_ELEMENTS:
    case SLOW_SLOPPY_ARGUMENTS_ELEMENTS: {
      FOR_WITH_HANDLE_SCOPE(
          isolate, uint32_t, index = 0, index, index < length, index++, {
            DirectHandle<Object> element;
            ASSIGN_RETURN_ON_EXCEPTION_VALUE(
                isolate, element, JSReceiver::GetElement(isolate, array, index),
                false);
            if (!visitor->visit(index, element)) return false;
          });
      break;
    }
    case WASM_ARRAY_ELEMENTS:
      // TODO(ishell): implement
      UNIMPLEMENTED();
    case NO_ELEMENTS:
      break;
      // JSArrays cannot have the following elements kinds:
#define TYPED_ARRAY_CASE(Type, type, TYPE, ctype) case TYPE##_ELEMENTS:
      TYPED_ARRAYS(TYPED_ARRAY_CASE)
      RAB_GSAB_TYPED_ARRAYS(TYPED_ARRAY_CASE)
#undef TYPED_ARRAY_CASE
    case FAST_STRING_WRAPPER_ELEMENTS:
    case SLOW_STRING_WRAPPER_ELEMENTS:
    case SHARED_ARRAY_ELEMENTS:
      UNREACHABLE();
  }
  visitor->increase_index_offset(length);
  return true;
}
References ASSIGN_RETURN_ON_EXCEPTION_VALUE, CollectElementIndices(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::DICTIONARY_ELEMENTS, v8::internal::Isolate::factory(), v8::internal::FAST_SLOPPY_ARGUMENTS_ELEMENTS, v8::internal::FAST_STRING_WRAPPER_ELEMENTS, FOR_WITH_HANDLE_SCOPE, v8::Maybe< T >::FromJust(), v8::internal::JSReceiver::GetElement(), v8::internal::Object::GetLengthFromArrayLike(), v8::internal::anonymous_namespace{builtins-array.cc}::ArrayConcatVisitor::has_simple_elements(), v8::internal::JSReceiver::HasElement(), HasOnlySimpleElements(), v8::internal::HOLEY_DOUBLE_ELEMENTS, v8::internal::HOLEY_ELEMENTS, v8::internal::HOLEY_FROZEN_ELEMENTS, v8::internal::HOLEY_NONEXTENSIBLE_ELEMENTS, v8::internal::HOLEY_SEALED_ELEMENTS, v8::internal::HOLEY_SMI_ELEMENTS, v8::internal::index, v8::internal::anonymous_namespace{builtins-array.cc}::ArrayConcatVisitor::index_offset(), v8::Maybe< T >::IsNothing(), IterateElementsSlow(), v8::internal::kMaxSafeInteger, v8::internal::length, v8::internal::NO_ELEMENTS, v8::internal::Object::NumberValue(), v8::internal::PACKED_DOUBLE_ELEMENTS, v8::internal::PACKED_ELEMENTS, v8::internal::PACKED_FROZEN_ELEMENTS, v8::internal::PACKED_NONEXTENSIBLE_ELEMENTS, v8::internal::PACKED_SEALED_ELEMENTS, v8::internal::PACKED_SMI_ELEMENTS, RAB_GSAB_TYPED_ARRAYS, v8::internal::SHARED_ARRAY_ELEMENTS, v8::internal::SLOW_SLOPPY_ARGUMENTS_ELEMENTS, v8::internal::SLOW_STRING_WRAPPER_ELEMENTS, v8::base::sort(), v8::internal::Isolate::Throw(), v8::internal::Object::ToUint32(), TYPED_ARRAY_CASE, TYPED_ARRAYS, v8::internal::UNIMPLEMENTED(), v8::internal::UNREACHABLE(), v8::internal::anonymous_namespace{builtins-array.cc}::ArrayConcatVisitor::visit(), and v8::internal::WASM_ARRAY_ELEMENTS.
Referenced by Slow_ArrayConcat().
IterateElementsSlow()
bool v8::internal::anonymous_namespace{builtins-array.cc}::IterateElementsSlow (Isolate * isolate, DirectHandle< JSReceiver > receiver, uint32_t length, ArrayConcatVisitor * visitor)
Definition at line 1186 of file builtins-array.cc.
                                                                       {
  FOR_WITH_HANDLE_SCOPE(isolate, uint32_t, i = 0, i, i < length, ++i, {
    Maybe<bool> maybe = JSReceiver::HasElement(isolate, receiver, i);
    if (maybe.IsNothing()) return false;
    if (maybe.FromJust()) {
      DirectHandle<Object> element_value;
      ASSIGN_RETURN_ON_EXCEPTION_VALUE(
          isolate, element_value, JSReceiver::GetElement(isolate, receiver, i),
          false);
      if (!visitor->visit(i, element_value)) return false;
    }
  });
  visitor->increase_index_offset(length);
  return true;
}
References ASSIGN_RETURN_ON_EXCEPTION_VALUE, FOR_WITH_HANDLE_SCOPE, v8::Maybe< T >::FromJust(), v8::internal::JSReceiver::GetElement(), v8::internal::JSReceiver::HasElement(), v8::internal::anonymous_namespace{builtins-array.cc}::ArrayConcatVisitor::increase_index_offset(), v8::Maybe< T >::IsNothing(), v8::internal::length, and v8::internal::anonymous_namespace{builtins-array.cc}::ArrayConcatVisitor::visit().
Referenced by IterateElements().
MatchArrayElementsKindToArguments()
void v8::internal::anonymous_namespace{builtins-array.cc}::MatchArrayElementsKindToArguments (Isolate * isolate, DirectHandle< JSArray > array, BuiltinArguments * args, int first_arg_index, int num_arguments)
Definition at line 72 of file builtins-array.cc.
                                                                               {
  int args_length = args->length();
  if (first_arg_index >= args_length) return;
  ElementsKind origin_kind = array->GetElementsKind();
  // We do not need to transition for PACKED/HOLEY_ELEMENTS.
  if (IsObjectElementsKind(origin_kind)) return;
  ElementsKind target_kind = origin_kind;
  {
    DisallowGarbageCollection no_gc;
    int last_arg_index = std::min(first_arg_index + num_arguments, args_length);
    for (int i = first_arg_index; i < last_arg_index; i++) {
      Tagged<Object> arg = (*args)[i];
      if (IsHeapObject(arg)) {
        if (IsHeapNumber(arg)) {
          target_kind = PACKED_DOUBLE_ELEMENTS;
        } else {
          target_kind = PACKED_ELEMENTS;
          break;
        }
      }
    }
  }
  if (target_kind != origin_kind) {
    // Use a short-lived HandleScope to avoid creating several copies of the
    // elements handle which would cause issues when left-trimming later-on.
    HandleScope scope(isolate);
    JSObject::TransitionElementsKind(isolate, array, target_kind);
  }
}
References v8::base::args, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::IsHeapObject(), v8::internal::IsObjectElementsKind(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::PACKED_DOUBLE_ELEMENTS, v8::internal::PACKED_ELEMENTS, and v8::internal::JSObject::TransitionElementsKind().
Referenced by v8::internal::BUILTIN().
SetLengthProperty()
V8_WARN_UNUSED_RESULT MaybeDirectHandle<Object> v8::internal::anonymous_namespace{builtins-array.cc}::SetLengthProperty (Isolate * isolate, DirectHandle< JSReceiver > receiver, uint64_t length)
Definition at line 194 of file builtins-array.cc.
                                                                          {
  if (IsJSArray(*receiver)) {
    DirectHandle<JSArray> array = Cast<JSArray>(receiver);
    if (!JSArray::HasReadOnlyLength(array)) {
      DCHECK_LE(length, kMaxUInt32);
      MAYBE_RETURN_NULL(
          JSArray::SetLength(isolate, array, static_cast<uint32_t>(length)));
      return receiver;
    }
  }
  return Object::SetProperty(
      isolate, receiver, isolate->factory()->length_string(),
      isolate->factory()->NewNumber(length), StoreOrigin::kMaybeKeyed,
      Just(ShouldThrow::kThrowOnError));
}
References DCHECK_LE, v8::internal::Isolate::factory(), v8::internal::JSArray::HasReadOnlyLength(), v8::Just(), v8::internal::kMaxUInt32, v8::internal::kMaybeKeyed, v8::internal::kThrowOnError, v8::internal::length, MAYBE_RETURN_NULL, v8::internal::FactoryBase< Impl >::NewNumber(), v8::internal::JSArray::SetLength(), and v8::internal::Object::SetProperty().
Referenced by v8::internal::BUILTIN(), and GenericArrayShift().
Slow_ArrayConcat()
Tagged<Object> v8::internal::anonymous_namespace{builtins-array.cc}::Slow_ArrayConcat (BuiltinArguments * args, DirectHandle< Object > species, Isolate * isolate)
Definition at line 1404 of file builtins-array.cc.
                                                  {
  int argument_count = args->length();
  bool is_array_species = *species == isolate->context()->array_function();
  // Pass 1: estimate the length and number of elements of the result.
  // The actual length can be larger if any of the arguments have getters
  // that mutate other arguments (but will otherwise be precise).
  // The number of elements is precise if there are no inherited elements.
  ElementsKind kind = PACKED_SMI_ELEMENTS;
  uint32_t estimate_result_length = 0;
  uint32_t estimate_nof = 0;
  FOR_WITH_HANDLE_SCOPE(isolate, int, i = 0, i, i < argument_count, i++, {
    DirectHandle<Object> obj = args->at(i);
    uint32_t length_estimate;
    uint32_t element_estimate;
    if (IsJSArray(*obj)) {
      auto array = Cast<JSArray>(obj);
      length_estimate =
          static_cast<uint32_t>(Object::NumberValue(array->length()));
      if (length_estimate != 0) {
        ElementsKind array_kind =
            GetPackedElementsKind(array->GetElementsKind());
        if (IsAnyNonextensibleElementsKind(array_kind)) {
          array_kind = PACKED_ELEMENTS;
        }
        kind = GetMoreGeneralElementsKind(kind, array_kind);
      }
      element_estimate = EstimateElementCount(isolate, array);
    } else {
      if (IsHeapObject(*obj)) {
        kind = GetMoreGeneralElementsKind(
            kind, IsNumber(*obj) ? PACKED_DOUBLE_ELEMENTS : PACKED_ELEMENTS);
      }
      length_estimate = 1;
      element_estimate = 1;
    }
    // Avoid overflows by capping at kMaxArrayLength.
    if (JSArray::kMaxArrayLength - estimate_result_length < length_estimate) {
      estimate_result_length = JSArray::kMaxArrayLength;
    } else {
      estimate_result_length += length_estimate;
    }
    if (JSArray::kMaxArrayLength - estimate_nof < element_estimate) {
      estimate_nof = JSArray::kMaxArrayLength;
    } else {
      estimate_nof += element_estimate;
    }
  });
  // If estimated number of elements is more than half of length, a
  // fixed array (fast case) is more time and space-efficient than a
  // dictionary.
  bool fast_case = is_array_species &&
                   (estimate_nof * 2) >= estimate_result_length &&
                   Protectors::IsIsConcatSpreadableLookupChainIntact(isolate);
  if (fast_case && kind == PACKED_DOUBLE_ELEMENTS) {
    DirectHandle<FixedArrayBase> storage =
        isolate->factory()->NewFixedDoubleArray(estimate_result_length);
    int j = 0;
    bool failure = false;
    if (estimate_result_length > 0) {
      auto double_storage = Cast<FixedDoubleArray>(storage);
      for (int i = 0; i < argument_count; i++) {
        DirectHandle<Object> obj = args->at(i);
        if (IsSmi(*obj)) {
          double_storage->set(j, Smi::ToInt(*obj));
          j++;
        } else if (IsNumber(*obj)) {
          double_storage->set(j, Object::NumberValue(*obj));
          j++;
        } else {
          DisallowGarbageCollection no_gc;
          Tagged<JSArray> array = Cast<JSArray>(*obj);
          uint32_t length =
              static_cast<uint32_t>(Object::NumberValue(array->length()));
          switch (array->GetElementsKind()) {
            case HOLEY_DOUBLE_ELEMENTS:
            case PACKED_DOUBLE_ELEMENTS: {
              // Empty array is FixedArray but not FixedDoubleArray.
              if (length == 0) break;
              Tagged<FixedDoubleArray> elements =
                  Cast<FixedDoubleArray>(array->elements());
              for (uint32_t k = 0; k < length; k++) {
                const bool is_hole = elements->is_the_hole(k);
                if (is_hole
#ifdef V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
                    || elements->is_undefined(k)
#endif // V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
                ) {
                  if (Protectors::IsNoElementsIntact(isolate)) {
                    // If we do not have elements on the prototype chain,
                    // we can generate a HOLEY_DOUBLE_ELEMENTS.
                    kind = HOLEY_DOUBLE_ELEMENTS;
#ifdef V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
                    if (is_hole) {
#endif // V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
                      double_storage->set_the_hole(j);
#ifdef V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
                    } else {
                      double_storage->set_undefined(j);
                    }
#endif // V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
                  } else {
                    failure = true;
                    break;
                  }
                } else {
                  double double_value = elements->get_scalar(k);
                  double_storage->set(j, double_value);
                }
                j++;
              }
              break;
            }
            case HOLEY_SMI_ELEMENTS:
            case PACKED_SMI_ELEMENTS: {
              Tagged<Object> the_hole = ReadOnlyRoots(isolate).the_hole_value();
              Tagged<FixedArray> elements(Cast<FixedArray>(array->elements()));
              for (uint32_t k = 0; k < length; k++) {
                Tagged<Object> element = elements->get(k);
                if (element == the_hole) {
                  if (Protectors::IsNoElementsIntact(isolate)) {
                    // If we do not have elements on the prototype chain,
                    // we can generate a HOLEY_DOUBLE_ELEMENTS.
                    kind = HOLEY_DOUBLE_ELEMENTS;
                    double_storage->set_the_hole(j);
                  } else {
                    failure = true;
                    break;
                  }
                } else {
                  int32_t int_value = Smi::ToInt(element);
                  double_storage->set(j, int_value);
                }
                j++;
              }
              break;
            }
            case HOLEY_ELEMENTS:
            case HOLEY_FROZEN_ELEMENTS:
            case HOLEY_SEALED_ELEMENTS:
            case HOLEY_NONEXTENSIBLE_ELEMENTS:
            case PACKED_ELEMENTS:
            case PACKED_FROZEN_ELEMENTS:
            case PACKED_SEALED_ELEMENTS:
            case PACKED_NONEXTENSIBLE_ELEMENTS:
            case DICTIONARY_ELEMENTS:
            case NO_ELEMENTS:
              DCHECK_EQ(0u, length);
              break;
            default:
              UNREACHABLE();
          }
        }
        if (failure) {
#ifdef VERIFY_HEAP
          // The allocated storage may contain uninitialized values which will
          // cause FixedDoubleArray::FixedDoubleArrayVerify to fail, when the
          // heap is verified (see: crbug.com/1415071). To prevent this, we
          // initialize the array with holes.
          if (v8_flags.verify_heap) {
            double_storage->FillWithHoles(0, estimate_result_length);
          }
#endif // VERIFY_HEAP
          break;
        }
      }
    }
    if (!failure) {
      return *isolate->factory()->NewJSArrayWithElements(storage, kind, j);
    }
    // In case of failure, fall through.
  }
  DirectHandle<UnionOf<JSReceiver, FixedArray, NumberDictionary>> storage;
  if (fast_case) {
    // The backing storage array must have non-existing elements to preserve
    // holes across concat operations.
    storage =
        isolate->factory()->NewFixedArrayWithHoles(estimate_result_length);
  } else if (is_array_species) {
    storage = NumberDictionary::New(isolate, estimate_nof);
  } else {
    DCHECK(IsConstructor(*species));
    DirectHandle<Object> length(Smi::zero(), isolate);
    DirectHandle<JSReceiver> storage_object;
    ASSIGN_RETURN_FAILURE_ON_EXCEPTION(
        isolate, storage_object,
        Execution::New(isolate, species, species, {&length, 1}));
    storage = storage_object;
  }
  ArrayConcatVisitor visitor(isolate, storage, fast_case);
  for (int i = 0; i < argument_count; i++) {
    DirectHandle<Object> obj = args->at(i);
    Maybe<bool> spreadable = IsConcatSpreadable(isolate, obj);
    MAYBE_RETURN(spreadable, ReadOnlyRoots(isolate).exception());
    if (spreadable.FromJust()) {
      DirectHandle<JSReceiver> object = Cast<JSReceiver>(obj);
      if (!IterateElements(isolate, object, &visitor)) {
        return ReadOnlyRoots(isolate).exception();
      }
    } else {
      if (!visitor.visit(0, obj)) return ReadOnlyRoots(isolate).exception();
      visitor.increase_index_offset(1);
    }
  }
  if (visitor.exceeds_array_limit()) {
    THROW_NEW_ERROR_RETURN_FAILURE(
        isolate, NewRangeError(MessageTemplate::kInvalidArrayLength));
  }
  if (is_array_species) {
    return *visitor.ToArray();
  } else {
    RETURN_RESULT_OR_FAILURE(isolate, visitor.ToJSReceiver());
  }
}
References v8::base::args, ASSIGN_RETURN_FAILURE_ON_EXCEPTION, v8::internal::Isolate::context(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::DICTIONARY_ELEMENTS, EstimateElementCount(), v8::internal::anonymous_namespace{builtins-array.cc}::ArrayConcatVisitor::exceeds_array_limit(), v8::internal::Isolate::factory(), FOR_WITH_HANDLE_SCOPE, v8::Maybe< T >::FromJust(), v8::internal::GetMoreGeneralElementsKind(), v8::internal::GetPackedElementsKind(), v8::internal::HOLEY_DOUBLE_ELEMENTS, v8::internal::HOLEY_ELEMENTS, v8::internal::HOLEY_FROZEN_ELEMENTS, v8::internal::HOLEY_NONEXTENSIBLE_ELEMENTS, v8::internal::HOLEY_SEALED_ELEMENTS, v8::internal::HOLEY_SMI_ELEMENTS, v8::internal::anonymous_namespace{builtins-array.cc}::ArrayConcatVisitor::increase_index_offset(), v8::internal::IsAnyNonextensibleElementsKind(), IsConcatSpreadable(), v8::internal::IsHeapObject(), v8::internal::IsNumber(), v8::internal::IsSmi(), IterateElements(), v8::internal::JSArray::kMaxArrayLength, v8::internal::length, MAYBE_RETURN, v8::internal::anonymous_namespace{intl-objects.cc}::New(), v8::internal::Execution::New(), v8::internal::FactoryBase< Impl >::NewFixedArrayWithHoles(), v8::internal::FactoryBase< Impl >::NewFixedDoubleArray(), v8::internal::Factory::NewJSArrayWithElements(), v8::internal::NO_ELEMENTS, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Object::NumberValue(), v8::internal::PACKED_DOUBLE_ELEMENTS, v8::internal::PACKED_ELEMENTS, v8::internal::PACKED_FROZEN_ELEMENTS, v8::internal::PACKED_NONEXTENSIBLE_ELEMENTS, v8::internal::PACKED_SEALED_ELEMENTS, v8::internal::PACKED_SMI_ELEMENTS, RETURN_RESULT_OR_FAILURE, THROW_NEW_ERROR_RETURN_FAILURE, v8::internal::anonymous_namespace{builtins-array.cc}::ArrayConcatVisitor::ToArray(), v8::internal::Smi::ToInt(), v8::internal::anonymous_namespace{builtins-array.cc}::ArrayConcatVisitor::ToJSReceiver(), v8::internal::UNREACHABLE(), v8::internal::v8_flags, v8::internal::anonymous_namespace{builtins-array.cc}::ArrayConcatVisitor::visit(), and v8::internal::Smi::zero().
Referenced by v8::internal::BUILTIN().
TryFastArrayFill()
V8_WARN_UNUSED_RESULT bool v8::internal::anonymous_namespace{builtins-array.cc}::TryFastArrayFill (Isolate * isolate, BuiltinArguments * args, DirectHandle< JSReceiver > receiver, DirectHandle< Object > value, uint64_t start_index, uint64_t end_index)
Definition at line 270 of file builtins-array.cc.
                                                                          {
  // If indices are too large, use generic path since they are stored as
  // properties, not in the element backing store.
  if (end_index > kMaxUInt32) return false;
  if (!IsJSObject(*receiver)) return false;
  DirectHandle<JSArray> array;
  ElementsKind kind;
  if (!IsJSArrayWithAddableFastElements(isolate, receiver, &kind, &array)) {
    return false;
  }
  DCHECK_LE(start_index, kMaxUInt32);
  DCHECK_LE(end_index, kMaxUInt32);
  DCHECK_LT(start_index, end_index);
  uint32_t start = static_cast<uint32_t>(start_index);
  uint32_t end = static_cast<uint32_t>(end_index);
  // The end index should be truncated to the array length in the argument
  // resolution part of Array.p.fill, which means it should be within the
  // FixedArray max length since we know the array has fast elements (and that
  // both FixedArray and FixedDoubleArray have the same max length).
  //
  // However, it _can_ be larger than the _current_ array length, because
  // of side-effects in Array.p.fill argument resolution (`ToInteger` on `start`
  // and `end`, see: https://tc39.es/ecma262/#sec-array.prototype.fill). In
  // particular, those could have transitioned a dictionary-elements array back
  // to fast elements, by adding enough data element properties to make it dense
  // (an easy way to do this is another call to Array.p.fill).
  static_assert(FixedArray::kMaxLength == FixedDoubleArray::kMaxLength);
  if (end > FixedArray::kMaxLength) return false;
  // Need to ensure that the fill value can be contained in the array.
  ElementsKind origin_kind = array->GetElementsKind();
  ElementsKind target_kind = Object::OptimalElementsKind(*value, isolate);
  if (target_kind != origin_kind) {
    // Use a short-lived HandleScope to avoid creating several copies of the
    // elements handle which would cause issues when left-trimming later-on.
    HandleScope scope(isolate);
    bool is_replacing_all_elements =
        (start == 0 && end == Object::NumberValue(array->length()));
    bool did_transition_map = false;
    if (is_replacing_all_elements) {
      // For the case where we are replacing all elements, we can migrate the
      // map backwards in the elements kind chain and ignore the current
      // contents of the elements array.
      DirectHandle<Map> new_map;
      if (GetReplacedElementsKindsMap(isolate, array, origin_kind, target_kind)
              .ToHandle(&new_map)) {
        DirectHandle<FixedArrayBase> elements(array->elements(), isolate);
        if (IsDoubleElementsKind(origin_kind) !=
                IsDoubleElementsKind(target_kind) ||
            elements->IsCowArray()) {
          // Reallocate the elements if doubleness doesn't match or the array is
          // copy-on-write.
          if (IsDoubleElementsKind(target_kind)) {
            elements = isolate->factory()->NewFixedDoubleArray(end);
          } else {
            elements = isolate->factory()->NewFixedArrayWithZeroes(end);
          }
        }
        JSObject::SetMapAndElements(isolate, array, new_map, elements);
        if (IsMoreGeneralElementsKindTransition(origin_kind, target_kind)) {
          // Transition through the allocation site as well if present, but
          // only if this is a forward transition.
          JSObject::UpdateAllocationSite(isolate, array, target_kind);
        }
        did_transition_map = true;
      }
    }
    if (!did_transition_map) {
      target_kind = GetMoreGeneralElementsKind(origin_kind, target_kind);
      JSObject::TransitionElementsKind(isolate, array, target_kind);
    }
  }
  ElementsAccessor* accessor = array->GetElementsAccessor();
  accessor->Fill(isolate, array, value, start, end).Check();
  // It's possible the JSArray's 'length' property was assigned to after the
  // length was loaded due to user code during argument coercion of the start
  // and end parameters. The spec algorithm does a Set, meaning the length would
  // grow as needed during the fill.
  //
  // ElementAccessor::Fill is able to grow the backing store as needed, but we
  // need to ensure the JSArray's length is correctly set in case the user
  // assigned a smaller value.
  if (Object::NumberValue(array->length()) < end) {
    CHECK(accessor->SetLength(isolate, array, end).FromJust());
  }
  return true;
}
References CHECK, DCHECK_LE, DCHECK_LT, v8::internal::compiler::end(), v8::internal::Isolate::factory(), v8::internal::ElementsAccessor::Fill(), v8::internal::GetMoreGeneralElementsKind(), GetReplacedElementsKindsMap(), v8::internal::IsDoubleElementsKind(), IsJSArrayWithAddableFastElements(), v8::internal::IsMoreGeneralElementsKindTransition(), v8::internal::FixedArray::kMaxLength, v8::internal::PrimitiveArrayBase< FixedDoubleArray, FixedDoubleArrayShape >::kMaxLength, v8::internal::kMaxUInt32, v8::internal::FactoryBase< Impl >::NewFixedArrayWithZeroes(), v8::internal::FactoryBase< Impl >::NewFixedDoubleArray(), v8::internal::Object::NumberValue(), v8::internal::Object::OptimalElementsKind(), v8::internal::ElementsAccessor::SetLength(), v8::internal::JSObject::SetMapAndElements(), v8::internal::JSObject::TransitionElementsKind(), v8::internal::JSObject::UpdateAllocationSite(), and v8::internal::value.
Referenced by v8::internal::BUILTIN().