v8::base::anonymous_namespace{logging.cc} Namespace Reference
Functions
void DefaultDcheckHandler (const char *file, int line, const char *message)
std::string PrettyPrintChar (int ch)
Variables
void(* g_print_stack_trace)() = nullptr
void(* g_dcheck_function)(const char *, int, const char *) = DefaultDcheckHandler
void(* g_fatal_function)(const char *, int, const char *) = nullptr
Function Documentation
DefaultDcheckHandler()
void v8::base::anonymous_namespace{logging.cc}::DefaultDcheckHandler (const char * file, int line, const char * message)
Definition at line 57 of file logging.cc.
                                                                           {
#ifdef DEBUG
  V8_Fatal(file, line, "Debug check failed: %s.", message);
#else
  // This case happens only for unit tests.
  V8_Fatal("Debug check failed: %s.", message);
#endif
}
References file(), and V8_Fatal().
Referenced by v8::base::SetDcheckFunction().
PrettyPrintChar()
std::string v8::base::anonymous_namespace{logging.cc}::PrettyPrintChar (int ch)
Definition at line 28 of file logging.cc.
                                  {
  std::ostringstream oss;
  switch (ch) {
#define CHAR_PRINT_CASE(ch) \
  case ch: \
    oss << #ch; \
    break;
    CHAR_PRINT_CASE('\0')
    CHAR_PRINT_CASE('\'')
    CHAR_PRINT_CASE('\\')
    CHAR_PRINT_CASE('\a')
    CHAR_PRINT_CASE('\b')
    CHAR_PRINT_CASE('\f')
    CHAR_PRINT_CASE('\n')
    CHAR_PRINT_CASE('\r')
    CHAR_PRINT_CASE('\t')
    CHAR_PRINT_CASE('\v')
#undef CHAR_PRINT_CASE
    default:
      if (std::isprint(ch)) {
        oss << '\'' << ch << '\'';
      } else {
        oss << std::hex << "\\x" << static_cast<unsigned int>(ch);
      }
  }
  return oss.str();
}
References CHAR_PRINT_CASE.
Variable Documentation
g_dcheck_function
void(* v8::base::anonymous_namespace{logging.cc}::g_dcheck_function) (const char *, int, const char *) (const char * , int , const char *) = DefaultDcheckHandler
Definition at line 24 of file logging.cc.
Referenced by v8::base::SetDcheckFunction(), and V8_Dcheck().
g_fatal_function
void(* v8::base::anonymous_namespace{logging.cc}::g_fatal_function) (const char *, int, const char *) (const char * , int , const char *) = nullptr
Definition at line 26 of file logging.cc.
Referenced by v8::base::SetFatalFunction(), and V8_Fatal().
g_print_stack_trace
void(* v8::base::anonymous_namespace{logging.cc}::g_print_stack_trace) () () = nullptr
Definition at line 22 of file logging.cc.
Referenced by v8::base::FatalOOM(), v8::base::SetPrintStackTrace(), and V8_Fatal().