v8::base::bits Namespace Reference
Classes
class BitsIterator
Functions
template<typename T >
auto IterateBits (T bits)
template<typename T >
auto IterateBitsBackwards (T bits)
int32_t SignedMulHigh32 (int32_t lhs, int32_t rhs)
int64_t SignedMulHigh64 (int64_t u, int64_t v)
uint64_t UnsignedMulHigh64 (uint64_t u, uint64_t v)
uint32_t UnsignedMulHigh32 (uint32_t lhs, uint32_t rhs)
int32_t SignedMulHighAndAdd32 (int32_t lhs, int32_t rhs, int32_t acc)
int32_t SignedDiv32 (int32_t lhs, int32_t rhs)
int64_t SignedDiv64 (int64_t lhs, int64_t rhs)
int32_t SignedMod32 (int32_t lhs, int32_t rhs)
int64_t SignedMod64 (int64_t lhs, int64_t rhs)
int64_t SignedSaturatedAdd64 (int64_t lhs, int64_t rhs)
int64_t SignedSaturatedSub64 (int64_t lhs, int64_t rhs)
template<typename T >
constexpr unsigned CountPopulation (T value) requires(std
template<typename T >
T ReverseBits (T value)
template<typename T >
T ReverseBytes (T value)
template<class T >
constexpr std::make_unsigned_t< T > Unsigned (T value)
template<class T >
constexpr std::make_signed_t< T > Signed (T value)
template<typename T , unsigned bits = sizeof(T) * 8>
constexpr unsigned CountLeadingZeros (T value) requires(std
constexpr unsigned CountLeadingZeros32 (uint32_t value)
constexpr unsigned CountLeadingZeros64 (uint64_t value)
template<class T >
constexpr unsigned CountLeadingSignBits (T value)
template<typename T , unsigned bits = sizeof(T) * 8>
constexpr unsigned CountTrailingZeros (T value) requires(std
constexpr unsigned CountTrailingZeros32 (uint32_t value)
constexpr unsigned CountTrailingZeros64 (uint64_t value)
template<typename T , unsigned bits = sizeof(T) * 8>
constexpr unsigned CountTrailingZerosNonZero (T value) requires(std
template<typename T >
constexpr bool IsPowerOfTwo (T value) requires(std
template<typename T >
constexpr int WhichPowerOfTwo (T value) requires std
constexpr V8_BASE_EXPORT uint64_t RoundUpToPowerOfTwo64 (uint64_t value)
constexpr size_t RoundUpToPowerOfTwo (size_t value)
uint32_t RoundDownToPowerOfTwo32 (uint32_t value)
constexpr uint32_t RotateRight32 (uint32_t value, uint32_t shift)
constexpr uint32_t RotateLeft32 (uint32_t value, uint32_t shift)
constexpr uint64_t RotateRight64 (uint64_t value, uint64_t shift)
constexpr uint64_t RotateLeft64 (uint64_t value, uint64_t shift)
bool SignedAddOverflow32 (int32_t lhs, int32_t rhs, int32_t *val)
bool SignedSubOverflow32 (int32_t lhs, int32_t rhs, int32_t *val)
bool SignedMulOverflow32 (int32_t lhs, int32_t rhs, int32_t *val)
bool SignedAddOverflow64 (int64_t lhs, int64_t rhs, int64_t *val)
bool SignedSubOverflow64 (int64_t lhs, int64_t rhs, int64_t *val)
bool SignedMulOverflow64 (int64_t lhs, int64_t rhs, int64_t *val)
bool UnsignedAddOverflow32 (uint32_t lhs, uint32_t rhs, uint32_t *val)
uint32_t UnsignedDiv32 (uint32_t lhs, uint32_t rhs)
uint64_t UnsignedDiv64 (uint64_t lhs, uint64_t rhs)
uint32_t UnsignedMod32 (uint32_t lhs, uint32_t rhs)
uint64_t UnsignedMod64 (uint64_t lhs, uint64_t rhs)
int32_t WraparoundAdd32 (int32_t lhs, int32_t rhs)
int32_t WraparoundNeg32 (int32_t x)
template<class T >
constexpr V8_BASE_EXPORT int BitWidth (T x)
Variables
template<typename T >
constexpr int ClearLsb (T value) requires std
Function Documentation
BitWidth()
template<class T >
constexpr V8_BASE_EXPORT int v8::base::bits::BitWidth (T x) [constexpr]
Definition at line 496 of file bits.h.
                                           {
  return std::numeric_limits<T>::digits - CountLeadingZeros(x);
}
References CountLeadingZeros().
CountLeadingSignBits()
template<class T >
constexpr unsigned v8::base::bits::CountLeadingSignBits (T value) [constexpr]
Definition at line 132 of file bits.h.
                                                 {
  static_assert(std::is_signed_v<T>);
  return value < 0 ? CountLeadingZeros(~Unsigned(value))
                   : CountLeadingZeros(Unsigned(value));
}
References CountLeadingZeros(), Unsigned(), and v8::internal::value.
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::CountLeadingSignBits().
CountLeadingZeros()
template<typename T , unsigned bits = sizeof(T) * 8>
constexpr unsigned v8::base::bits::CountLeadingZeros (T value) [inline], [constexpr]
Definition at line 100 of file bits.h.
{
  static_assert(bits > 0, "invalid instantiation");
#if V8_HAS_BUILTIN_CLZ
  return value == 0
             ? bits
             : bits == 64
                   ? __builtin_clzll(static_cast<uint64_t>(value))
                   : __builtin_clz(static_cast<uint32_t>(value)) - (32 - bits);
#else
  // Binary search algorithm taken from "Hacker's Delight" (by Henry S. Warren,
  // Jr.), figures 5-11 and 5-12.
  if (bits == 1) return static_cast<unsigned>(value) ^ 1;
  T upper_half = value >> (bits / 2);
  T next_value = upper_half != 0 ? upper_half : value;
  unsigned add = upper_half != 0 ? 0 : bits / 2;
  constexpr unsigned next_bits = bits == 1 ? 1 : bits / 2;
  return CountLeadingZeros<T, next_bits>(next_value) + add;
#endif
}
References v8::internal::value.
Referenced by BitWidth(), v8::internal::StringForwardingTable::BlockForIndex(), v8::internal::BigInt::CompareToDouble(), CountLeadingSignBits(), CountLeadingZeros32(), CountLeadingZeros64(), cppgc::internal::ObjectStartBitmap::FindHeader(), v8::internal::MarkingBitmap::FindPreviousValidObject(), v8::internal::wasm::LiftoffRegList::GetLastRegSet(), v8::internal::swiss_table::BitMask< T, SignificantBits, Shift >::HighestBitSet(), v8::internal::anonymous_namespace{js-function.cc}::HighestTierOf(), v8::internal::RegListBase< RegisterT >::last(), v8::internal::swiss_table::BitMask< T, SignificantBits, Shift >::LeadingZeros(), v8::internal::Smi::LexicographicCompare(), v8::internal::anonymous_namespace{object-stats.cc}::Log2ForSize(), v8::base::bits::BitsIterator< T, kMSBFirst >::operator*(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceBranchCondition(), v8::internal::compiler::MachineOperatorReducer::ReduceWordEqualForConstantRhs(), v8::internal::compiler::turboshaft::LayeredHashMap< Key, Value >::ResizeIfNeeded(), RoundUpToPowerOfTwo64(), v8::internal::SimdMemEqual(), v8::internal::MutableBigInt::ToDouble(), v8::internal::BigInt::ToString(), v8::internal::wasm::uint64_to_float32_wrapper(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordUnary().
CountLeadingZeros32()
constexpr unsigned v8::base::bits::CountLeadingZeros32 (uint32_t value) [inline], [constexpr]
Definition at line 122 of file bits.h.
                                                              {
  return CountLeadingZeros(value);
}
References CountLeadingZeros(), and v8::internal::value.
Referenced by v8::internal::compiler::CodeGenerator::FinishFrame(), v8::internal::compiler::IsContiguousMask32(), v8::internal::MaglevSafepointTable::Print(), and v8::internal::SafepointTable::Print().
CountLeadingZeros64()
constexpr unsigned v8::base::bits::CountLeadingZeros64 (uint64_t value) [inline], [constexpr]
Definition at line 125 of file bits.h.
                                                              {
  return CountLeadingZeros(value);
}
References CountLeadingZeros(), and v8::internal::value.
Referenced by v8::internal::CountLeadingZeros(), v8::internal::compiler::IsContiguousMask64(), and v8::internal::compiler::TryMatchShiftFromMul().
CountPopulation()
template<typename T >
constexpr unsigned v8::base::bits::CountPopulation (T value) [inline], [constexpr]
Definition at line 26 of file bits.h.
{
  static_assert(sizeof(T) <= 8);
#if V8_HAS_BUILTIN_POPCOUNT
  return sizeof(T) == 8 ? __builtin_popcountll(static_cast<uint64_t>(value))
                        : __builtin_popcount(static_cast<uint32_t>(value));
#else
  // Fall back to divide-and-conquer popcount (see "Hacker's Delight" by Henry
  // S. Warren, Jr.), chapter 5-1.
  constexpr uint64_t mask[] = {0x5555555555555555, 0x3333333333333333,
                               0x0f0f0f0f0f0f0f0f};
  // Start with 64 buckets of 1 bits, holding values from [0,1].
  value = ((value >> 1) & mask[0]) + (value & mask[0]);
  // Having 32 buckets of 2 bits, holding values from [0,2] now.
  value = ((value >> 2) & mask[1]) + (value & mask[1]);
  // Having 16 buckets of 4 bits, holding values from [0,4] now.
  value = ((value >> 4) & mask[2]) + (value & mask[2]);
  // Having 8 buckets of 8 bits, holding values from [0,8] now.
  // From this point on, the buckets are bigger than the number of bits
  // required to hold the values, and the buckets are bigger the maximum
  // result, so there's no need to mask value anymore, since there's no
  // more risk of overflow between buckets.
  if (sizeof(T) > 1) value = (value >> (sizeof(T) > 1 ? 8 : 0)) + value;
  // Having 4 buckets of 16 bits, holding values from [0,16] now.
  if (sizeof(T) > 2) value = (value >> (sizeof(T) > 2 ? 16 : 0)) + value;
  // Having 2 buckets of 32 bits, holding values from [0,32] now.
  if (sizeof(T) > 4) value = (value >> (sizeof(T) > 4 ? 32 : 0)) + value;
  // Having 1 buckets of 64 bits, holding values from [0,64] now.
  return static_cast<unsigned>(value & 0xff);
#endif
}
References T, and v8::internal::value.
Referenced by v8::platform::DefaultJobState::AcquireTaskId(), v8::internal::StringBuiltinsAssembler::AllocateConsString(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::CanInlineArrayResizingBuiltin(), v8::internal::compiler::turboshaft::TurbolevEarlyLoweringReducer< Next >::CheckedInternalizedString(), v8::internal::RegListBase< RegisterT >::Count(), v8::internal::BitVector::Count(), v8::internal::compiler::SparseInputMask::CountReal(), CountTrailingZeros(), v8::internal::EncodedCSignature::FPParameterCount(), v8::internal::wasm::LiftoffRegList::GetNumRegsSet(), v8::internal::WasmDebugBreakFrameConstants::GetPushedFpRegisterOffset(), v8::internal::WasmDebugBreakFrameConstants::GetPushedGpRegisterOffset(), v8::internal::FeedbackNexus::ic_state(), v8::internal::compiler::SparseInputMask::InputIterator::InputIterator(), v8::internal::compiler::IsContiguousMask32(), v8::internal::compiler::IsContiguousMask64(), v8::internal::maglev::MaglevAssembler::JumpIfSeqOneByteStringMap(), v8::internal::maglev::MaglevAssembler::LoadThinStringValue(), v8::internal::compiler::turboshaft::LayeredHashMap< Key, Value >::ResizeIfNeeded(), v8::internal::CodeStubAssembler::TryToName(), WhichPowerOfTwo(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordUnary().
CountTrailingZeros()
template<typename T , unsigned bits = sizeof(T) * 8>
constexpr unsigned v8::base::bits::CountTrailingZeros (T value) [inline], [constexpr]
Definition at line 144 of file bits.h.
{
#if V8_HAS_BUILTIN_CTZ
  return value == 0 ? bits
                    : bits == 64 ? __builtin_ctzll(static_cast<uint64_t>(value))
                                 : __builtin_ctz(static_cast<uint32_t>(value));
#else
  // Fall back to popcount (see "Hacker's Delight" by Henry S. Warren, Jr.),
  // chapter 5-4. On x64, since is faster than counting in a loop and faster
  // than doing binary search.
  using U = typename std::make_unsigned_t<T>;
  U u = value;
  return CountPopulation(static_cast<U>(~u & (u - 1u)));
#endif
}
References CountPopulation(), v8::base::internal::U, and v8::internal::value.
Referenced by v8::internal::LiveObjectRange::iterator::AdvanceToNextMarkedObject(), v8::internal::compiler::SparseInputMask::InputIterator::AdvanceToNextRealOrEnd(), v8::internal::torque::ResidueClass::AlignmentLog2(), v8::internal::anonymous_namespace{regexp-compiler.cc}::BitsetFirstSetBit(), v8::internal::MacroAssembler::Claim(), v8::internal::CountTrailingZeros(), CountTrailingZeros32(), CountTrailingZeros64(), v8::internal::MacroAssembler::Drop(), v8::internal::RegExpBuiltinsAssembler::FastFlagGetter(), v8::internal::wasm::LiftoffRegList::GetFirstRegSet(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TestAndBranchMatcherTurboshaft::Initialize(), heap::base::BasicSlotSet< SlotGranularity >::Iterate(), cppgc::internal::ObjectStartBitmap::Iterate(), v8::internal::MaglevFrame::Iterate(), v8::internal::BitVector::Iterator::Iterator(), v8::internal::SparseBitVector::Iterator::Iterator(), v8::base::bits::BitsIterator< T, kMSBFirst >::operator*(), v8::internal::BitVector::Iterator::operator++(), v8::internal::SparseBitVector::Iterator::operator++(), v8::internal::anonymous_namespace{dependent-code.cc}::PrintDependencyGroups(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceUnsignedDiv(), v8::internal::compiler::MachineOperatorReducer::ReduceWordNAnd(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Shift(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitCbzOrTbz(), v8::internal::compiler::MachineOperatorReducer::Uint32Div(), v8::internal::wasm::uint64_to_float32_wrapper(), v8::internal::compiler::MachineOperatorReducer::Uint64Div(), v8::internal::anonymous_namespace{frames.cc}::VisitSpillSlots(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordUnary().
CountTrailingZeros32()
constexpr unsigned v8::base::bits::CountTrailingZeros32 (uint32_t value) [inline], [constexpr]
Definition at line 161 of file bits.h.
                                                               {
  return CountTrailingZeros(value);
}
References CountTrailingZeros(), and v8::internal::value.
Referenced by v8::platform::DefaultJobState::AcquireTaskId(), v8::internal::compiler::CodeGenerator::FinishFrame(), and v8::internal::compiler::IsContiguousMask32().
CountTrailingZeros64()
constexpr unsigned v8::base::bits::CountTrailingZeros64 (uint64_t value) [inline], [constexpr]
Definition at line 164 of file bits.h.
                                                               {
  return CountTrailingZeros(value);
}
References CountTrailingZeros(), and v8::internal::value.
Referenced by v8::internal::compiler::IsContiguousMask64(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordBinop().
CountTrailingZerosNonZero()
template<typename T , unsigned bits = sizeof(T) * 8>
constexpr unsigned v8::base::bits::CountTrailingZerosNonZero (T value) [inline], [constexpr]
Definition at line 173 of file bits.h.
{
  DCHECK_NE(0, value);
#if V8_HAS_BUILTIN_CTZ
  return bits == 64 ? __builtin_ctzll(static_cast<uint64_t>(value))
                    : __builtin_ctz(static_cast<uint32_t>(value));
#else
  return CountTrailingZeros<T, bits>(value);
#endif
}
References DCHECK_NE, and v8::internal::value.
Referenced by v8::internal::RegListBase< RegisterT >::first(), v8::internal::maglev::IsInstanceOfNodeType(), v8::base::operator<<(), and v8::internal::swiss_table::BitMask< T, SignificantBits, Shift >::TrailingZeros().
IsPowerOfTwo()
template<typename T >
constexpr bool v8::base::bits::IsPowerOfTwo (T value) [inline], [constexpr]
Definition at line 187 of file bits.h.
{
  return value > 0 && (value & (value - 1)) == 0;
}
References v8::internal::value.
Referenced by v8::internal::wasm::ValidateFunctionsStreamingJobData::AddUnit(), v8::internal::Assembler::Align(), v8::internal::AlignedSlotAllocator::Align(), v8::base::AlignedAlloc(), v8::internal::compiler::Frame::AlignFrame(), v8::internal::compiler::Frame::AlignSavedCalleeRegisterSlots(), v8::internal::MacroAssembler::AssertStackIsAligned(), v8::internal::MacroAssembler::CallCFunctionHelper(), v8::internal::RegExpMacroAssemblerRISCV::CallCheckStackGuardState(), v8::internal::anonymous_namespace{regexp-compiler.cc}::CharMask(), v8::internal::MacroAssembler::Claim(), v8::internal::CountLeadingZeros(), v8::internal::CountTrailingZeros(), v8::internal::Assembler::DataAlign(), v8::internal::MacroAssembler::DecodeField(), v8::internal::MacroAssembler::Drop(), v8::internal::wasm::LiftoffAssembler::emit_i32_muli(), v8::internal::wasm::LiftoffAssembler::emit_i64_muli(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::EmitInt32MulWithOverflow(), v8::base::EmulatedVirtualAddressSubspace::EmulatedVirtualAddressSubspace(), v8::internal::MacroAssembler::EnterExitFrame(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::FloatBinop(), v8::internal::InnerPointerToCodeCache::GetCacheEntry(), v8::internal::wasm::WasmCodeLookupCache::GetCacheEntry(), v8::internal::JSFunction::HasAvailableHigherTierCodeThanWithFilter(), v8::internal::compiler::anonymous_namespace{move-optimizer.cc}::OperandSet::HasMixedFPReps(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TestAndBranchMatcherTurboshaft::Initialize(), v8::internal::StubCache::Initialize(), v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::Initialize(), v8::internal::MemoryAllocator::InitializeOncePerProcess(), v8::internal::compiler::FloatMatcher< T, kOpcode >::IsPositiveOrNegativePowerOf2(), v8::internal::anonymous_namespace{asm-js.cc}::IsValidAsmjsMemorySize(), v8::internal::VRegister::IsValidLaneCount(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::LeftShiftForReducedMultiply(), v8::internal::MemoryChunkLiveBytesMap::lookup_entry(), v8::internal::wasm::WasmExportWrapperCache::New(), v8::base::RandomNumberGenerator::NextInt(), v8::internal::NumberParseIntHelper::ParseInternal(), v8::internal::MacroAssembler::PrepareCallCFunction(), v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::Probe(), v8::internal::MarkCompactCollector::ProcessMarkingWorklist(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceBranchCondition(), v8::internal::compiler::MachineOperatorReducer::ReduceInt32Div(), v8::internal::compiler::MachineOperatorReducer::ReduceInt32Mod(), v8::internal::compiler::MachineOperatorReducer::ReduceInt64Div(), v8::internal::compiler::MachineOperatorReducer::ReduceInt64Mod(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateObject(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceSignedDiv(), v8::internal::compiler::MachineOperatorReducer::ReduceUint32Div(), v8::internal::compiler::MachineOperatorReducer::ReduceUint32Mod(), v8::internal::compiler::MachineOperatorReducer::ReduceUint64Div(), v8::internal::compiler::MachineOperatorReducer::ReduceUint64Mod(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceUnsignedDiv(), v8::base::RegionAllocator::RegionAllocator(), v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::SweepListFull(), v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::SweepYoung(), v8::internal::wasm::TriggerTierUp(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitCbzOrTbz(), v8::internal::compiler::TryMatchShiftFromMul(), v8::internal::compiler::anonymous_namespace{machine-operator-reducer.cc}::TrySimplifyCompareForTestBit(), v8::internal::wasm::AsmJsParser::ValidateCall(), v8::base::VirtualAddressSpace::VirtualAddressSpace(), WhichPowerOfTwo(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordBinop(), v8::internal::CodeStubAssembler::WordIsAligned(), and v8::internal::CodeStubAssembler::WordIsPowerOfTwo().
IterateBits()
template<typename T >
auto v8::base::bits::IterateBits (T bits)
Definition at line 42 of file bits-iterator.h.
                         {
  return make_iterator_range(BitsIterator<T>{bits}, BitsIterator<T>{0});
}
References v8::base::make_iterator_range().
Referenced by v8::internal::compiler::SpillPlacer::SecondBackwardPass().
IterateBitsBackwards()
template<typename T >
auto v8::base::bits::IterateBitsBackwards (T bits)
Definition at line 48 of file bits-iterator.h.
                                  {
  return make_iterator_range(BitsIterator<T, true>{bits},
                             BitsIterator<T, true>{0});
}
References v8::base::make_iterator_range().
ReverseBits()
template<typename T >
T v8::base::bits::ReverseBits (T value)
Definition at line 61 of file bits.h.
                       {
  static_assert((sizeof(value) == 1) || (sizeof(value) == 2) ||
                (sizeof(value) == 4) || (sizeof(value) == 8));
  T result = 0;
  for (unsigned i = 0; i < (sizeof(value) * 8); i++) {
    result = (result << 1) | (value & 1);
    value >>= 1;
  }
  return result;
}
References v8::base::internal::result, and v8::internal::value.
ReverseBytes()
template<typename T >
T v8::base::bits::ReverseBytes (T value)
Definition at line 74 of file bits.h.
                        {
  static_assert((sizeof(value) == 1) || (sizeof(value) == 2) ||
                (sizeof(value) == 4) || (sizeof(value) == 8));
  T result = 0;
  for (unsigned i = 0; i < sizeof(value); i++) {
    result = (result << 8) | (value & 0xff);
    value >>= 8;
  }
  return result;
}
References v8::base::internal::result, and v8::internal::value.
Referenced by v8::internal::wasm::SimdShuffle::TryMatch32x4OneLaneSwizzle(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordUnary().
RotateLeft32()
constexpr uint32_t v8::base::bits::RotateLeft32 (uint32_t value, uint32_t shift) [inline], [constexpr]
Definition at line 279 of file bits.h.
                                                                       {
  return (value << shift) | (value >> ((32 - shift) & 31));
}
References v8::internal::value.
Referenced by v8::internal::anonymous_namespace{strings-storage.cc}::ComputeStringHash(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Shift().
RotateLeft64()
constexpr uint64_t v8::base::bits::RotateLeft64 (uint64_t value, uint64_t shift) [inline], [constexpr]
Definition at line 289 of file bits.h.
                                                                       {
  return (value << shift) | (value >> ((64 - shift) & 63));
}
References v8::internal::value.
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Shift().
RotateRight32()
constexpr uint32_t v8::base::bits::RotateRight32 (uint32_t value, uint32_t shift) [inline], [constexpr]
Definition at line 274 of file bits.h.
                                                                        {
  return (value >> shift) | (value << ((32 - shift) & 31));
}
References v8::internal::value.
Referenced by v8::base::hash_combine(), v8::internal::compiler::MachineOperatorReducer::Reduce(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Shift().
RotateRight64()
constexpr uint64_t v8::base::bits::RotateRight64 (uint64_t value, uint64_t shift) [inline], [constexpr]
Definition at line 284 of file bits.h.
                                                                        {
  return (value >> shift) | (value << ((64 - shift) & 63));
}
References v8::internal::value.
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Shift().
RoundDownToPowerOfTwo32()
uint32_t v8::base::bits::RoundDownToPowerOfTwo32 (uint32_t value) [inline]
Definition at line 265 of file bits.h.
                                                        {
  if (value > 0x80000000u) return 0x80000000u;
  uint32_t result = RoundUpToPowerOfTwo32(value);
  if (result > value) result >>= 1;
  return result;
}
References v8::base::internal::result, and v8::internal::value.
Referenced by cppgc::internal::anonymous_namespace{free-list.cc}::BucketIndexForSize().
RoundUpToPowerOfTwo()
constexpr size_t v8::base::bits::RoundUpToPowerOfTwo (size_t value) [inline], [constexpr]
Definition at line 252 of file bits.h.
                                                          {
  if (sizeof(size_t) == sizeof(uint64_t)) {
    return RoundUpToPowerOfTwo64(value);
  } else {
    // Without windows.h included this line triggers a truncation warning on
    // 64-bit builds. Presumably windows.h disables the relevant warning.
    return RoundUpToPowerOfTwo32(static_cast<uint32_t>(value));
  }
}
References RoundUpToPowerOfTwo64(), and v8::internal::value.
Referenced by v8::internal::baseline::BaselineCompiler::BaselineCompiler(), v8::internal::wasm::FastZoneVector< T >::Grow(), and v8::base::SmallVector< T, kSize, Allocator >::Grow().
RoundUpToPowerOfTwo64()
constexpr V8_BASE_EXPORT uint64_t v8::base::bits::RoundUpToPowerOfTwo64 (uint64_t value) [constexpr]
Definition at line 235 of file bits.h.
                                                                        {
  DCHECK_LE(value, uint64_t{1} << 63);
  if (value) --value;
// Use computation based on leading zeros if we have compiler support for that.
#if V8_HAS_BUILTIN_CLZ
  return uint64_t{1} << (64 - CountLeadingZeros(value));
#else
  value |= value >> 1;
  value |= value >> 2;
  value |= value >> 4;
  value |= value >> 8;
  value |= value >> 16;
  value |= value >> 32;
  return value + 1;
#endif
}
References CountLeadingZeros(), DCHECK_LE, and v8::internal::value.
Referenced by cppgc::internal::CagedHeap::CagedHeap(), v8::internal::Heap::ConfigureHeap(), v8::internal::wasm::WasmInterpreterThread::EnsureRefStackSpace(), RoundUpToPowerOfTwo(), and v8::internal::wasm::anonymous_namespace{wasm-result.cc}::VPrintFToString().
Signed()
template<class T >
constexpr std::make_signed_t<T> v8::base::bits::Signed (T value) [inline], [constexpr]
Definition at line 91 of file bits.h.
                                                     {
  static_assert(std::is_unsigned_v<T>);
  return static_cast<std::make_signed_t<T>>(value);
}
References v8::internal::value.
Referenced by v8::internal::wasm::AsmJsParser::BitwiseANDExpression(), v8::internal::anonymous_namespace{unary-op-assembler.cc}::UnaryOpAssemblerImpl::BitwiseNot(), v8::internal::CodeStubAssembler::BitwiseOp(), v8::internal::wasm::AsmJsParser::BitwiseORExpression(), v8::internal::CodeStubAssembler::BitwiseSmiOp(), v8::internal::wasm::AsmJsParser::BitwiseXORExpression(), v8::internal::wasm::anonymous_namespace{asm-types.cc}::AsmFroundType::CanBeInvokedWith(), v8::internal::CodeStubAssembler::ChangePositiveInt32ToIntPtr(), v8::internal::wasm::AsmJsParser::ConvertSignature(), v8::internal::CodeStubAssembler::CreateAllocationSiteInFeedbackVector(), v8::internal::CodeStubAssembler::DecodeWord32FromWord(), v8::internal::CodeStubAssembler::ElementOffsetFromIndex(), v8::internal::CodeStubAssembler::EmitElementStore(), v8::internal::CodeStubAssembler::FixedArrayBoundsCheck(), v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER(), v8::internal::wasm::AsmJsParser::InitializeStdlibTypes(), v8::internal::compiler::CodeAssembler::Int32Add(), v8::internal::compiler::CodeAssembler::Int32Mul(), v8::internal::compiler::CodeAssembler::Int32Sub(), v8::internal::compiler::CodeAssembler::Int64Add(), v8::internal::compiler::CodeAssembler::Int64Mul(), v8::internal::compiler::CodeAssembler::Int64Sub(), v8::internal::compiler::CodeAssembler::IntPtrAdd(), v8::internal::compiler::CodeAssembler::IntPtrMul(), v8::internal::compiler::CodeAssembler::IntPtrSub(), v8::internal::CodeStubAssembler::LoadElementsKind(), v8::internal::CodeStubAssembler::LoadPropertyFromFastObject(), v8::internal::CodeStubAssembler::LoadVariableLengthJSTypedArrayByteLength(), v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::InterpreterLookupContextSlotAssembler::LookupContextSlot(), v8::internal::wasm::AsmJsParser::MultiplicativeExpression(), v8::internal::CodeStubAssembler::ParameterToIntPtr(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::CodeAssembler::RawPtrSub(), v8::internal::CodeStubAssembler::ReportFeedbackUpdate(), v8::internal::wasm::AsmJsParser::ReturnStatement(), v8::internal::wasm::AsmJsParser::ShiftExpression(), v8::internal::wasm::AsmJsParser::SwitchStatement(), v8::internal::TF_BUILTIN(), v8::internal::CodeStubAssembler::TimesDoubleSize(), v8::internal::CodeStubAssembler::TimesSystemPointerSize(), v8::internal::CodeStubAssembler::TimesTaggedSize(), v8::internal::wasm::AsmJsParser::UnaryExpression(), v8::internal::CodeStubAssembler::UpdateWordInWord32(), v8::internal::wasm::AsmJsParser::ValidateCall(), v8::internal::wasm::AsmJsParser::ValidateFloatCoercion(), v8::internal::wasm::AsmJsParser::ValidateModuleVar(), v8::internal::compiler::CodeAssembler::Word32And(), v8::internal::compiler::CodeAssembler::Word32BitwiseNot(), v8::internal::compiler::CodeAssembler::Word32Or(), v8::internal::compiler::CodeAssembler::Word32Sar(), v8::internal::compiler::CodeAssembler::Word32Shl(), v8::internal::compiler::CodeAssembler::Word64And(), v8::internal::compiler::CodeAssembler::Word64Not(), v8::internal::compiler::CodeAssembler::Word64Sar(), v8::internal::compiler::CodeAssembler::Word64Shl(), v8::internal::compiler::CodeAssembler::Word64Shr(), v8::internal::compiler::CodeAssembler::Word64Xor(), v8::internal::compiler::CodeAssembler::WordAnd(), v8::internal::compiler::CodeAssembler::WordNot(), v8::internal::compiler::CodeAssembler::WordOr(), v8::internal::compiler::CodeAssembler::WordSar(), and v8::internal::compiler::CodeAssembler::WordShl().
SignedAddOverflow32()
bool v8::base::bits::SignedAddOverflow32 (int32_t lhs, int32_t rhs, int32_t * val) [inline]
Definition at line 306 of file bits.h.
                                                                        {
#if V8_HAS_BUILTIN_SADD_OVERFLOW
  return __builtin_sadd_overflow(lhs, rhs, val);
#else
  uint32_t res = static_cast<uint32_t>(lhs) + static_cast<uint32_t>(rhs);
  *val = base::bit_cast<int32_t>(res);
  return ((res ^ lhs) & (res ^ rhs) & (1U << 31)) != 0;
#endif
}
Referenced by v8::internal::CodeStubAssembler::ConstexprInt31Add(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::OverflowCheckedBinop(), v8::internal::compiler::SimplifiedOperatorReducer::Reduce(), v8::internal::compiler::MachineOperatorReducer::ReduceProjection(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryAdjustOffset(), and v8::internal::compiler::OneOrTwoByteAnalysis::TryGetRange().
SignedAddOverflow64()
bool v8::base::bits::SignedAddOverflow64 (int64_t lhs, int64_t rhs, int64_t * val) [inline]
Definition at line 348 of file bits.h.
                                                                        {
#if V8_HAS_BUILTIN_ADD_OVERFLOW
  return __builtin_add_overflow(lhs, rhs, val);
#else
  uint64_t res = static_cast<uint64_t>(lhs) + static_cast<uint64_t>(rhs);
  *val = base::bit_cast<int64_t>(res);
  return ((res ^ lhs) & (res ^ rhs) & (1ULL << 63)) != 0;
#endif
}
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::OverflowCheckedBinop(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryAdjustIndex().
SignedDiv32()
V8_BASE_EXPORT int32_t v8::base::bits::SignedDiv32 (int32_t lhs, int32_t rhs)
Definition at line 69 of file bits.cc.
                                              {
  if (rhs == 0) return 0;
  if (rhs == -1) return lhs == std::numeric_limits<int32_t>::min() ? lhs : -lhs;
  return lhs / rhs;
}
Referenced by v8::internal::compiler::MachineOperatorReducer::ReduceInt32Div(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordBinop().
SignedDiv64()
V8_BASE_EXPORT int64_t v8::base::bits::SignedDiv64 (int64_t lhs, int64_t rhs)
Definition at line 75 of file bits.cc.
                                              {
  if (rhs == 0) return 0;
  if (rhs == -1) return lhs == std::numeric_limits<int64_t>::min() ? lhs : -lhs;
  return lhs / rhs;
}
Referenced by v8::internal::compiler::MachineOperatorReducer::ReduceInt64Div(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordBinop().
SignedMod32()
V8_BASE_EXPORT int32_t v8::base::bits::SignedMod32 (int32_t lhs, int32_t rhs)
Definition at line 81 of file bits.cc.
                                              {
  if (rhs == 0 || rhs == -1) return 0;
  return lhs % rhs;
}
Referenced by v8::internal::compiler::MachineOperatorReducer::ReduceInt32Mod(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordBinop().
SignedMod64()
V8_BASE_EXPORT int64_t v8::base::bits::SignedMod64 (int64_t lhs, int64_t rhs)
Definition at line 86 of file bits.cc.
                                              {
  if (rhs == 0 || rhs == -1) return 0;
  return lhs % rhs;
}
Referenced by v8::internal::compiler::MachineOperatorReducer::ReduceInt64Mod(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordBinop().
SignedMulHigh32()
V8_BASE_EXPORT int32_t v8::base::bits::SignedMulHigh32 (int32_t lhs, int32_t rhs)
Definition at line 15 of file bits.cc.
                                                  {
  int64_t const value = static_cast<int64_t>(lhs) * static_cast<int64_t>(rhs);
  return base::bit_cast<int32_t, uint32_t>(base::bit_cast<uint64_t>(value) >>
                                           32u);
}
References v8::internal::value.
Referenced by SignedMulHighAndAdd32(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordBinop().
SignedMulHigh64()
V8_BASE_EXPORT int64_t v8::base::bits::SignedMulHigh64 (int64_t u, int64_t v)
Definition at line 24 of file bits.cc.
                                              {
  uint64_t u0 = u & 0xFFFFFFFF;
  int64_t u1 = u >> 32;
  uint64_t v0 = v & 0xFFFFFFFF;
  int64_t v1 = v >> 32;
  uint64_t w0 = u0 * v0;
  int64_t t = u1 * v0 + (w0 >> 32);
  int64_t w1 = t & 0xFFFFFFFF;
  int64_t w2 = t >> 32;
  w1 = u0 * v1 + w1;
  return u1 * v1 + w2 + (w1 >> 32);
}
Referenced by v8::internal::FUNCTION_REFERENCE(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordBinop().
SignedMulHighAndAdd32()
V8_BASE_EXPORT int32_t v8::base::bits::SignedMulHighAndAdd32 (int32_t lhs, int32_t rhs, int32_t acc)
Definition at line 62 of file bits.cc.
                                                                     {
  return base::bit_cast<int32_t>(
      base::bit_cast<uint32_t>(acc) +
      base::bit_cast<uint32_t>(SignedMulHigh32(lhs, rhs)));
}
References SignedMulHigh32().
SignedMulOverflow32()
bool v8::base::bits::SignedMulOverflow32 (int32_t lhs, int32_t rhs, int32_t * val) [inline]
Definition at line 333 of file bits.h.
                                                                        {
#if V8_HAS_BUILTIN_SMUL_OVERFLOW
  return __builtin_smul_overflow(lhs, rhs, val);
#else
  // Compute the result as {int64_t}, then check for overflow.
  int64_t result = int64_t{lhs} * int64_t{rhs};
  *val = static_cast<int32_t>(result);
  using limits = std::numeric_limits<int32_t>;
  return result < limits::min() || result > limits::max();
#endif
}
References v8::base::internal::result.
Referenced by v8::internal::CodeStubAssembler::ConstexprInt31Mul(), v8::internal::TrustedPodArray< T >::New(), v8::internal::PodArray< T >::New(), v8::internal::FixedIntegerArrayBase< T, Base >::New(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::OverflowCheckedBinop(), v8::internal::compiler::MachineOperatorReducer::ReduceProjection(), and v8::internal::compiler::OneOrTwoByteAnalysis::TryGetRange().
SignedMulOverflow64()
bool v8::base::bits::SignedMulOverflow64 (int64_t lhs, int64_t rhs, int64_t * val) [inline]
Definition at line 375 of file bits.h.
                                                                        {
#if V8_HAS_BUILTIN_MUL_OVERFLOW
  return __builtin_mul_overflow(lhs, rhs, val);
#else
  int64_t res = base::bit_cast<int64_t>(static_cast<uint64_t>(lhs) *
                                        static_cast<uint64_t>(rhs));
  *val = res;
  // Check for INT64_MIN / -1 as it's undefined behaviour and could cause
  // hardware exceptions.
  if ((res == INT64_MIN && lhs == -1)) {
    return true;
  }
  return lhs != 0 && (res / lhs) != rhs;
#endif
}
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::OverflowCheckedBinop().
SignedSaturatedAdd64()
V8_BASE_EXPORT int64_t v8::base::bits::SignedSaturatedAdd64 (int64_t lhs, int64_t rhs)
Definition at line 91 of file bits.cc.
                                                       {
  using limits = std::numeric_limits<int64_t>;
  // Underflow if {lhs + rhs < min}. In that case, return {min}.
  if (rhs < 0 && lhs < limits::min() - rhs) return limits::min();
  // Overflow if {lhs + rhs > max}. In that case, return {max}.
  if (rhs >= 0 && lhs > limits::max() - rhs) return limits::max();
  return lhs + rhs;
}
Referenced by v8::base::time_internal::TimeBase< TimeClass >::operator+().
SignedSaturatedSub64()
V8_BASE_EXPORT int64_t v8::base::bits::SignedSaturatedSub64 (int64_t lhs, int64_t rhs)
Definition at line 100 of file bits.cc.
                                                       {
  using limits = std::numeric_limits<int64_t>;
  // Underflow if {lhs - rhs < min}. In that case, return {min}.
  if (rhs > 0 && lhs < limits::min() + rhs) return limits::min();
  // Overflow if {lhs - rhs > max}. In that case, return {max}.
  if (rhs <= 0 && lhs > limits::max() + rhs) return limits::max();
  return lhs - rhs;
}
Referenced by v8::base::time_internal::TimeBase< TimeClass >::operator-().
SignedSubOverflow32()
bool v8::base::bits::SignedSubOverflow32 (int32_t lhs, int32_t rhs, int32_t * val) [inline]
Definition at line 320 of file bits.h.
                                                                        {
#if V8_HAS_BUILTIN_SSUB_OVERFLOW
  return __builtin_ssub_overflow(lhs, rhs, val);
#else
  uint32_t res = static_cast<uint32_t>(lhs) - static_cast<uint32_t>(rhs);
  *val = base::bit_cast<int32_t>(res);
  return ((res ^ lhs) & (res ^ ~rhs) & (1U << 31)) != 0;
#endif
}
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::OverflowCheckedBinop(), v8::internal::compiler::MachineOperatorReducer::ReduceProjection(), and v8::internal::compiler::turboshaft::anonymous_namespace{loop-unrolling-reducer.cc}::SubWillOverflow().
SignedSubOverflow64()
bool v8::base::bits::SignedSubOverflow64 (int64_t lhs, int64_t rhs, int64_t * val) [inline]
Definition at line 362 of file bits.h.
                                                                        {
#if V8_HAS_BUILTIN_SUB_OVERFLOW
  return __builtin_sub_overflow(lhs, rhs, val);
#else
  uint64_t res = static_cast<uint64_t>(lhs) - static_cast<uint64_t>(rhs);
  *val = base::bit_cast<int64_t>(res);
  return ((res ^ lhs) & (res ^ ~rhs) & (1ULL << 63)) != 0;
#endif
}
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::OverflowCheckedBinop(), and v8::internal::compiler::turboshaft::anonymous_namespace{loop-unrolling-reducer.cc}::SubWillOverflow().
Unsigned()
template<class T >
constexpr std::make_unsigned_t<T> v8::base::bits::Unsigned (T value) [inline], [constexpr]
Definition at line 86 of file bits.h.
                                                         {
  static_assert(std::is_signed_v<T>);
  return static_cast<std::make_unsigned_t<T>>(value);
}
References v8::internal::value.
Referenced by v8::internal::CodeStubAssembler::BigIntToRawBytes(), v8::internal::CodeStubAssembler::BitwiseOp(), v8::internal::wasm::anonymous_namespace{asm-types.cc}::AsmFroundType::CanBeInvokedWith(), v8::internal::CodeStubAssembler::CheckForAssociatedProtector(), v8::internal::CodeStubAssembler::CheckForCapacityGrow(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Comparison(), CountLeadingSignBits(), v8::internal::CodeStubAssembler::ElementsKindToElementByteShift(), v8::internal::CodeStubAssembler::EmitElementStore(), v8::internal::CodeStubAssembler::GotoIfHasContextExtensionUpToDepth(), v8::internal::wasm::AsmJsParser::InitializeStdlibTypes(), v8::internal::CodeStubAssembler::LoadPropertyFromGlobalDictionary(), v8::internal::CodeStubAssembler::LoadVariableLengthJSTypedArrayByteLength(), v8::internal::wasm::AsmJsParser::MultiplicativeExpression(), v8::internal::wasm::AsmJsParser::NumericLiteral(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::wasm::Decoder::read_leb_tail(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceCompareEqual(), v8::internal::wasm::AsmJsParser::ShiftExpression(), v8::base::SignedDivisionByConstant(), v8::internal::TF_BUILTIN(), v8::internal::CodeStubAssembler::TimesDoubleSize(), v8::internal::CodeStubAssembler::TimesSystemPointerSize(), v8::internal::CodeStubAssembler::TimesTaggedSize(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryAdjustOffset(), v8::internal::compiler::CodeAssembler::Uint32Add(), v8::internal::compiler::CodeAssembler::Uint32Constant(), v8::internal::compiler::CodeAssembler::Uint32Mul(), v8::internal::compiler::CodeAssembler::Uint32Sub(), v8::internal::compiler::CodeAssembler::Uint64Add(), v8::internal::compiler::CodeAssembler::Uint64Constant(), v8::internal::compiler::CodeAssembler::Uint64Mul(), v8::internal::compiler::CodeAssembler::Uint64Sub(), v8::internal::compiler::CodeAssembler::UintPtrAdd(), v8::internal::compiler::CodeAssembler::UintPtrConstant(), v8::internal::compiler::CodeAssembler::UintPtrSub(), v8::internal::wasm::AsmJsParser::UnaryExpression(), v8::internal::compiler::CodeAssembler::UniqueUint32Constant(), v8::internal::wasm::AsmJsParser::ValidateCall(), v8::internal::wasm::AsmJsParser::ValidateFloatCoercion(), v8::internal::compiler::CodeAssembler::Word32And(), v8::internal::compiler::CodeAssembler::Word32Or(), v8::internal::compiler::CodeAssembler::Word32Shl(), v8::internal::compiler::CodeAssembler::Word32Shr(), v8::internal::compiler::CodeAssembler::Word64And(), v8::internal::compiler::CodeAssembler::Word64Not(), v8::internal::compiler::CodeAssembler::Word64Shl(), v8::internal::compiler::CodeAssembler::Word64Shr(), v8::internal::compiler::CodeAssembler::Word64Xor(), v8::internal::compiler::CodeAssembler::WordAnd(), v8::internal::compiler::CodeAssembler::WordShl(), v8::internal::compiler::CodeAssembler::WordShr(), v8::base::WrappingAdd(), and v8::base::WrappingSub().
UnsignedAddOverflow32()
bool v8::base::bits::UnsignedAddOverflow32 (uint32_t lhs, uint32_t rhs, uint32_t * val) [inline]
Definition at line 442 of file bits.h.
                                                                             {
#if V8_HAS_BUILTIN_SADD_OVERFLOW
  return __builtin_uadd_overflow(lhs, rhs, val);
#else
  *val = lhs + rhs;
  return *val < (lhs | rhs);
#endif
}
Referenced by v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::Advance().
UnsignedDiv32()
uint32_t v8::base::bits::UnsignedDiv32 (uint32_t lhs, uint32_t rhs) [inline]
Definition at line 454 of file bits.h.
                                                          {
  return rhs ? lhs / rhs : 0u;
}
Referenced by v8::internal::compiler::MachineOperatorReducer::ReduceUint32Div(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordBinop().
UnsignedDiv64()
uint64_t v8::base::bits::UnsignedDiv64 (uint64_t lhs, uint64_t rhs) [inline]
Definition at line 460 of file bits.h.
                                                          {
  return rhs ? lhs / rhs : 0u;
}
Referenced by v8::internal::compiler::MachineOperatorReducer::ReduceUint64Div(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordBinop().
UnsignedMod32()
uint32_t v8::base::bits::UnsignedMod32 (uint32_t lhs, uint32_t rhs) [inline]
Definition at line 466 of file bits.h.
                                                          {
  return rhs ? lhs % rhs : 0u;
}
Referenced by v8::internal::compiler::MachineOperatorReducer::ReduceUint32Mod(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordBinop().
UnsignedMod64()
uint64_t v8::base::bits::UnsignedMod64 (uint64_t lhs, uint64_t rhs) [inline]
Definition at line 472 of file bits.h.
                                                          {
  return rhs ? lhs % rhs : 0u;
}
Referenced by v8::internal::compiler::MachineOperatorReducer::ReduceUint64Mod(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordBinop().
UnsignedMulHigh32()
V8_BASE_EXPORT uint32_t v8::base::bits::UnsignedMulHigh32 (uint32_t lhs, uint32_t rhs)
Definition at line 56 of file bits.cc.
                                                       {
  uint64_t const value =
      static_cast<uint64_t>(lhs) * static_cast<uint64_t>(rhs);
  return static_cast<uint32_t>(value >> 32u);
}
References v8::internal::value.
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordBinop().
UnsignedMulHigh64()
V8_BASE_EXPORT uint64_t v8::base::bits::UnsignedMulHigh64 (uint64_t u, uint64_t v)
Definition at line 41 of file bits.cc.
                                                   {
  uint64_t u0 = u & 0xFFFFFFFF;
  uint64_t u1 = u >> 32;
  uint64_t v0 = v & 0xFFFFFFFF;
  uint64_t v1 = v >> 32;
  uint64_t w0 = u0 * v0;
  uint64_t t = u1 * v0 + (w0 >> 32);
  uint64_t w1 = t & 0xFFFFFFFFLL;
  uint64_t w2 = t >> 32;
  w1 = u0 * v1 + w1;
  return u1 * v1 + w2 + (w1 >> 32);
}
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordBinop().
WhichPowerOfTwo()
template<typename T >
constexpr int v8::base::bits::WhichPowerOfTwo (T value) [inline], [constexpr]
Definition at line 195 of file bits.h.
{
  DCHECK(IsPowerOfTwo(value));
#if V8_HAS_BUILTIN_CTZ
  static_assert(sizeof(T) <= 8);
  return sizeof(T) == 8 ? __builtin_ctzll(static_cast<uint64_t>(value))
                        : __builtin_ctz(static_cast<uint32_t>(value));
#else
  // Fall back to popcount (see "Hacker's Delight" by Henry S. Warren, Jr.),
  // chapter 5-4. On x64, since is faster than counting in a loop and faster
  // than doing binary search.
  using U = typename std::make_unsigned_t<T>;
  U u = value;
  return CountPopulation(static_cast<U>(u - 1));
#endif
}
// RoundUpToPowerOfTwo32(value) returns the smallest power of two which is
// greater than or equal to |value|. If you pass in a |value| that is already a
// power of two, it is returned as is. |value| must be less than or equal to
// 0x80000000u. Uses computation based on leading zeros if we have compiler
// support for that. Falls back to the implementation from "Hacker's Delight" by
// Henry S. Warren, Jr., figure 3-3, page 48, where the function is called clp2.
V8_BASE_EXPORT constexpr uint32_t RoundUpToPowerOfTwo32(uint32_t value) {
  DCHECK_LE(value, uint32_t{1} << 31);
  if (value) --value;
// Use computation based on leading zeros if we have compiler support for that.
#if V8_HAS_BUILTIN_CLZ || V8_CC_MSVC
  return 1u << (32 - CountLeadingZeros(value));
#else
  value |= value >> 1;
  value |= value >> 2;
  value |= value >> 4;
  value |= value >> 8;
  value |= value >> 16;
  return value + 1;
#endif
}
References CountPopulation(), DCHECK, IsPowerOfTwo(), T, v8::base::internal::U, and v8::internal::value.
Referenced by v8::internal::torque::AbstractType::AlignmentLog2(), cppgc::internal::anonymous_namespace{free-list.cc}::BucketIndexForSize(), v8::internal::wasm::LiftoffAssembler::emit_i32_muli(), v8::internal::wasm::LiftoffAssembler::emit_i64_muli(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::EmitInt32MulWithOverflow(), v8::internal::MemoryAllocator::InitializeOncePerProcess(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::LeftShiftForReducedMultiply(), v8::internal::compiler::MachineOperatorReducer::Reduce(), v8::internal::compiler::MachineOperatorReducer::ReduceInt32Div(), v8::internal::compiler::MachineOperatorReducer::ReduceInt64Div(), v8::internal::compiler::MachineOperatorReducer::ReduceInt64Mul(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceSignedDiv(), v8::internal::compiler::MachineOperatorReducer::ReduceUint32Div(), v8::internal::compiler::MachineOperatorReducer::ReduceUint64Div(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceUnsignedDiv(), v8::internal::compiler::turboshaft::InstructionSelectionNormalizationReducer< Next >::WordBinop(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordBinop(), and v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::WordBinopDeoptOnOverflow().
WraparoundAdd32()
int32_t v8::base::bits::WraparoundAdd32 (int32_t lhs, int32_t rhs) [inline]
Definition at line 478 of file bits.h.
                                                         {
  return static_cast<int32_t>(static_cast<uint32_t>(lhs) +
                              static_cast<uint32_t>(rhs));
}
Referenced by v8::internal::compiler::IA32OperandGenerator::GenerateMemoryOperandInputs().
WraparoundNeg32()
int32_t v8::base::bits::WraparoundNeg32 (int32_t x) [inline]
Definition at line 483 of file bits.h.
                                          {
  return static_cast<int32_t>(-static_cast<uint32_t>(x));
}
Referenced by v8::internal::compiler::IA32OperandGenerator::GenerateMemoryOperandInputs().
Variable Documentation
ClearLsb
template<typename T >
constexpr int v8::base::bits::ClearLsb(T value) requires std (T value) [inline], [constexpr]
Definition at line 301 of file bits.h.
Referenced by v8::internal::maglev::IsInstanceOfNodeType().