v8::internal::anonymous_namespace{code-memory-access.cc} Namespace Reference
Classes
class MutexUnlocker
Functions
size_t GetSize (ThreadIsolation::JitPage *jit_page)
size_t GetSize (ThreadIsolation::JitAllocation allocation)
template<class T >
void CheckForRegionOverlap (const T &map, Address addr, size_t size)
template<typename Iterator >
bool AllocationIsBehindRange (Address range_start, Address range_size, const Iterator &it)
Function Documentation
AllocationIsBehindRange()
template<typename Iterator >
bool v8::internal::anonymous_namespace{code-memory-access.cc}::AllocationIsBehindRange (Address range_start, Address range_size, const Iterator & it)
Definition at line 268 of file code-memory-access.cc.
                                                 {
  Address range_end = range_start + range_size;
  Address allocation_start = it->first;
  Address allocation_size = it->second.Size();
  Address allocation_end = allocation_start + allocation_size;
  if (allocation_start >= range_end) return true;
  CHECK_LE(allocation_end, range_end);
  return false;
}
References CHECK_LE.
Referenced by v8::internal::ThreadIsolation::JitPageReference::UnregisterRange().
CheckForRegionOverlap()
template<class T >
void v8::internal::anonymous_namespace{code-memory-access.cc}::CheckForRegionOverlap (const T & map, Address addr, size_t size)
Definition at line 240 of file code-memory-access.cc.
                                                                    {
  // The data is untrusted from the pov of CFI, so we check that there's no
  // overlaps with existing regions etc.
  CHECK_GE(addr + size, addr);
  // Find an entry in the map with key > addr
  auto it = map.upper_bound(addr);
  bool is_begin = it == map.begin();
  bool is_end = it == map.end();
  // Check for overlap with the next entry
  if (!is_end) {
    Address next_addr = it->first;
    Address offset = next_addr - addr;
    CHECK_LE(size, offset);
  }
  // Check the previous entry for overlap
  if (!is_begin) {
    it--;
    Address prev_addr = it->first;
    const typename T::value_type::second_type& prev_entry = it->second;
    Address offset = addr - prev_addr;
    CHECK_LE(GetSize(prev_entry), offset);
  }
}
References CHECK_GE, CHECK_LE, GetSize(), and size().
Referenced by v8::internal::ThreadIsolation::JitPageReference::RegisterAllocation(), and v8::internal::ThreadIsolation::RegisterJitPage().
GetSize() [1/2]
size_t v8::internal::anonymous_namespace{code-memory-access.cc}::GetSize (ThreadIsolation::JitAllocation allocation)
Definition at line 235 of file code-memory-access.cc.
                                                        {
  return allocation.Size();
}
References v8::internal::ThreadIsolation::JitAllocation::Size().
Referenced by CheckForRegionOverlap().
GetSize() [2/2]
size_t v8::internal::anonymous_namespace{code-memory-access.cc}::GetSize (ThreadIsolation::JitPage * jit_page)
Definition at line 231 of file code-memory-access.cc.
                                                 {
  return ThreadIsolation::JitPageReference(jit_page, 0).Size();
}
References v8::internal::ThreadIsolation::JitPageReference::Size().