v8::internal::anonymous_namespace{builtins-arraybuffer.cc} Namespace Reference
Enumerations
enum PreserveResizability { kToFixedLength
, kPreserveResizability
 }
Functions
std::pair< std::unique_ptr< BackingStore >, std::optional< MessageTemplate > > TryAllocateBackingStore (Isolate *isolate, SharedFlag shared, ResizableFlag resizable, DirectHandle< Object > length, DirectHandle< Object > max_length, InitializedFlag initialized)
Tagged< Object > ConstructBuffer (Isolate *isolate, DirectHandle< JSFunction > target, DirectHandle< JSReceiver > new_target, DirectHandle< Object > length, DirectHandle< Object > max_length, InitializedFlag initialized)
Tagged< Object > ArrayBufferTransfer (Isolate *isolate, DirectHandle< JSArrayBuffer > array_buffer, DirectHandle< Object > new_length, PreserveResizability preserve_resizability, const char *method_name)
Enumeration Type Documentation
PreserveResizability
enum v8::internal::anonymous_namespace{builtins-arraybuffer.cc}::PreserveResizability
Enumerator
kToFixedLength
kPreserveResizability
Definition at line 574 of file builtins-arraybuffer.cc.
{ kToFixedLength, kPreserveResizability };
Function Documentation
ArrayBufferTransfer()
Tagged<Object> v8::internal::anonymous_namespace{builtins-arraybuffer.cc}::ArrayBufferTransfer (Isolate * isolate, DirectHandle< JSArrayBuffer > array_buffer, DirectHandle< Object > new_length, PreserveResizability preserve_resizability, const char * method_name)
Definition at line 576 of file builtins-arraybuffer.cc.
                                                            {
  size_t max_allocatable =
      isolate->array_buffer_allocator()->MaxAllocationSize();
  DCHECK(max_allocatable <= JSArrayBuffer::kMaxByteLength);
  // 2. If IsSharedArrayBuffer(arrayBuffer) is true, throw a TypeError
  // exception.
  CHECK_SHARED(false, array_buffer, method_name);
  size_t new_byte_length;
  if (IsUndefined(*new_length, isolate)) {
    // 3. If newLength is undefined, then
    // a. Let newByteLength be arrayBuffer.[[ArrayBufferByteLength]].
    new_byte_length = array_buffer->GetByteLength();
  } else {
    // 4. Else,
    // a. Let newByteLength be ? ToIndex(newLength).
    DirectHandle<Object> number_new_byte_length;
    ASSIGN_RETURN_FAILURE_ON_EXCEPTION(isolate, number_new_byte_length,
                                       Object::ToInteger(isolate, new_length));
    if (Object::NumberValue(*number_new_byte_length) < 0.0) {
      THROW_NEW_ERROR_RETURN_FAILURE(
          isolate, NewRangeError(MessageTemplate::kInvalidArrayBufferLength));
    }
    if (!TryNumberToSize(*number_new_byte_length, &new_byte_length) ||
        new_byte_length > max_allocatable) {
      THROW_NEW_ERROR_RETURN_FAILURE(
          isolate,
          NewRangeError(
              MessageTemplate::kInvalidArrayBufferResizeLength,
              isolate->factory()->NewStringFromAsciiChecked(method_name)));
    }
  }
  // 5. If IsDetachedBuffer(arrayBuffer) is true, throw a TypeError exception.
  if (array_buffer->was_detached()) {
    THROW_NEW_ERROR_RETURN_FAILURE(
        isolate, NewTypeError(MessageTemplate::kDetachedOperation,
                              isolate->factory()->NewStringFromAsciiChecked(
                                  method_name)));
  }
  ResizableFlag resizable;
  size_t new_max_byte_length;
  if (preserve_resizability == kPreserveResizability &&
      array_buffer->is_resizable_by_js()) {
    // 6. If preserveResizability is preserve-resizability and
    // IsResizableArrayBuffer(arrayBuffer) is true, then
    // a. Let newMaxByteLength be arrayBuffer.[[ArrayBufferMaxByteLength]].
    new_max_byte_length = array_buffer->max_byte_length();
    resizable = ResizableFlag::kResizable;
  } else {
    // 7. Else,
    // a. Let newMaxByteLength be empty.
    new_max_byte_length = new_byte_length;
    resizable = ResizableFlag::kNotResizable;
  }
  // 8. If arrayBuffer.[[ArrayBufferDetachKey]] is not undefined, throw a
  // TypeError exception.
  if (!array_buffer->is_detachable()) {
    THROW_NEW_ERROR_RETURN_FAILURE(
        isolate,
        NewTypeError(MessageTemplate::kDataCloneErrorNonDetachableArrayBuffer));
  }
  // After this point the steps are not observable and are performed out of
  // spec order.
  // Case 1: We don't need a BackingStore.
  if (new_byte_length == 0) {
    // 15. Perform ! DetachArrayBuffer(arrayBuffer).
    JSArrayBuffer::Detach(array_buffer).Check();
    // 9. Let newBuffer be ? AllocateArrayBuffer(%ArrayBuffer%, newByteLength,
    // newMaxByteLength).
    //
    // Nothing to do for steps 10-14.
    //
    // 16. Return newBuffer.
    return *isolate->factory()
                ->NewJSArrayBufferAndBackingStore(
                    0, new_max_byte_length, InitializedFlag::kUninitialized,
                    resizable)
                .ToHandleChecked();
  }
  // Case 2: We can reuse the same BackingStore.
  auto from_backing_store = array_buffer->GetBackingStore();
  if (from_backing_store && !from_backing_store->is_resizable_by_js() &&
      resizable == ResizableFlag::kNotResizable &&
      new_byte_length == array_buffer->GetByteLength()) {
    // TODO(syg): Consider realloc when the default ArrayBuffer allocator's
    // Reallocate does better than copy.
    //
    // See https://crbug.com/330575496#comment27
    // 15. Perform ! DetachArrayBuffer(arrayBuffer).
    JSArrayBuffer::Detach(array_buffer).Check();
    // 9. Let newBuffer be ? AllocateArrayBuffer(%ArrayBuffer%, newByteLength,
    // newMaxByteLength).
    // 16. Return newBuffer.
    return *isolate->factory()->NewJSArrayBuffer(std::move(from_backing_store));
  }
  // Case 3: We can't reuse the same BackingStore. Copy the buffer.
  if (new_byte_length > new_max_byte_length) {
    THROW_NEW_ERROR_RETURN_FAILURE(
        isolate, NewRangeError(MessageTemplate::kInvalidArrayBufferLength));
  }
  // 9. Let newBuffer be ? AllocateArrayBuffer(%ArrayBuffer%, newByteLength,
  // newMaxByteLength).
  DirectHandle<JSArrayBuffer> new_buffer;
  MaybeDirectHandle<JSArrayBuffer> result =
      isolate->factory()->NewJSArrayBufferAndBackingStore(
          new_byte_length, new_max_byte_length, InitializedFlag::kUninitialized,
          resizable);
  if (!result.ToHandle(&new_buffer)) {
    THROW_NEW_ERROR_RETURN_FAILURE(
        isolate, NewRangeError(MessageTemplate::kArrayBufferAllocationFailed));
  }
  // 10. Let copyLength be min(newByteLength,
  // arrayBuffer.[[ArrayBufferByteLength]]).
  //
  // (Size comparison is done manually below instead of using min.)
  // 11. Let fromBlock be arrayBuffer.[[ArrayBufferData]].
  uint8_t* from_data =
      reinterpret_cast<uint8_t*>(array_buffer->backing_store());
  // 12. Let toBlock be newBuffer.[[ArrayBufferData]].
  uint8_t* to_data = reinterpret_cast<uint8_t*>(new_buffer->backing_store());
  // 13. Perform CopyDataBlockBytes(toBlock, 0, fromBlock, 0, copyLength).
  // 14. NOTE: Neither creation of the new Data Block nor copying from the old
  // Data Block are observable. Implementations reserve the right to
  // implement this method as a zero-copy move or a realloc.
  size_t from_byte_length = array_buffer->GetByteLength();
  if (new_byte_length <= from_byte_length) {
    CopyBytes(to_data, from_data, new_byte_length);
  } else {
    CopyBytes(to_data, from_data, from_byte_length);
    memset(to_data + from_byte_length, 0, new_byte_length - from_byte_length);
  }
  // 15. Perform ! DetachArrayBuffer(arrayBuffer).
  JSArrayBuffer::Detach(array_buffer).Check();
  // 16. Return newBuffer.
  return *new_buffer;
}
References v8::internal::Isolate::array_buffer_allocator(), ASSIGN_RETURN_FAILURE_ON_EXCEPTION, CHECK_SHARED, v8::internal::CopyBytes(), v8::internal::DCHECK(), v8::internal::JSArrayBuffer::Detach(), v8::internal::Isolate::factory(), v8::internal::JSArrayBuffer::kMaxByteLength, v8::internal::kNotResizable, kPreserveResizability, v8::internal::kResizable, v8::internal::kUninitialized, v8::ArrayBuffer::Allocator::MaxAllocationSize(), v8::internal::Factory::NewJSArrayBuffer(), v8::internal::Factory::NewJSArrayBufferAndBackingStore(), v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), v8::internal::Object::NumberValue(), v8::base::internal::result, THROW_NEW_ERROR_RETURN_FAILURE, v8::Value::ToInteger(), and v8::internal::TryNumberToSize().
Referenced by v8::internal::BUILTIN().
ConstructBuffer()
Tagged<Object> v8::internal::anonymous_namespace{builtins-arraybuffer.cc}::ConstructBuffer (Isolate * isolate, DirectHandle< JSFunction > target, DirectHandle< JSReceiver > new_target, DirectHandle< Object > length, DirectHandle< Object > max_length, InitializedFlag initialized)
Definition at line 101 of file builtins-arraybuffer.cc.
                                                            {
  // We first try to convert the sizes and collect any possible range errors. If
  // no errors are observable we create the BackingStore before the
  // JSArrayBuffer to avoid a complex dance during setup. We then always create
  // the AB before throwing a possible error as the creation is observable.
  const SharedFlag shared =
      *target != target->native_context()->array_buffer_fun()
          ? SharedFlag::kShared
          : SharedFlag::kNotShared;
  const ResizableFlag resizable = max_length.is_null()
                                      ? ResizableFlag::kNotResizable
                                      : ResizableFlag::kResizable;
  // BackingStore allocation may GC which is not observable itself.
  auto [backing_store, range_error] = TryAllocateBackingStore(
      isolate, shared, resizable, length, max_length, initialized);
  DirectHandle<JSObject> result;
  ASSIGN_RETURN_FAILURE_ON_EXCEPTION(
      isolate, result,
      JSObject::New(target, new_target, {}, NewJSObjectType::kAPIWrapper));
  auto array_buffer = Cast<JSArrayBuffer>(result);
  const bool backing_store_creation_failed = !backing_store;
  array_buffer->Setup(shared, resizable, std::move(backing_store), isolate);
  if (backing_store_creation_failed) {
    CHECK(range_error.has_value());
    THROW_NEW_ERROR_RETURN_FAILURE(isolate, NewRangeError(range_error.value()));
  }
  return *array_buffer;
}
References ASSIGN_RETURN_FAILURE_ON_EXCEPTION, CHECK, v8::internal::DirectHandle< T >::is_null(), v8::internal::kAPIWrapper, v8::internal::kNotResizable, v8::internal::kNotShared, v8::internal::kResizable, v8::internal::kShared, v8::internal::length, v8::internal::JSObject::New(), v8::base::internal::result, THROW_NEW_ERROR_RETURN_FAILURE, and TryAllocateBackingStore().
Referenced by v8::internal::BUILTIN().
TryAllocateBackingStore()
std::pair<std::unique_ptr<BackingStore>, std::optional<MessageTemplate> > v8::internal::anonymous_namespace{builtins-arraybuffer.cc}::TryAllocateBackingStore (Isolate * isolate, SharedFlag shared, ResizableFlag resizable, DirectHandle< Object > length, DirectHandle< Object > max_length, InitializedFlag initialized)
Definition at line 46 of file builtins-arraybuffer.cc.
                                                     {
  DisallowJavascriptExecution no_js(isolate);
  size_t byte_length;
  size_t max_byte_length = 0;
  std::unique_ptr<BackingStore> backing_store;
  size_t max_allocatable =
      isolate->array_buffer_allocator()->MaxAllocationSize();
  DCHECK(max_allocatable <= JSArrayBuffer::kMaxByteLength);
  static_assert(JSArrayBuffer::kMaxByteLength == JSTypedArray::kMaxByteLength);
  if (!TryNumberToSize(*length, &byte_length) ||
      byte_length > max_allocatable) {
    return {nullptr, MessageTemplate::kInvalidArrayBufferLength};
  }
  switch (resizable) {
    case ResizableFlag::kNotResizable:
      backing_store =
          BackingStore::Allocate(isolate, byte_length, shared, initialized);
      break;
    case ResizableFlag::kResizable:
      if (!TryNumberToSize(*max_length, &max_byte_length) ||
          max_byte_length > max_allocatable) {
        return {nullptr, MessageTemplate::kInvalidArrayBufferMaxLength};
      }
      if (byte_length > max_byte_length) {
        return {nullptr, MessageTemplate::kInvalidArrayBufferMaxLength};
      }
      size_t page_size, initial_pages, max_pages;
      const auto maybe_range_error =
          JSArrayBuffer::GetResizableBackingStorePageConfigurationImpl(
              isolate, byte_length, max_byte_length, &page_size, &initial_pages,
              &max_pages);
      if (maybe_range_error.has_value()) {
        return {nullptr, maybe_range_error.value()};
      }
      backing_store = BackingStore::TryAllocateAndPartiallyCommitMemory(
          isolate, byte_length, max_byte_length, page_size, initial_pages,
          max_pages, WasmMemoryFlag::kNotWasm, shared);
      break;
  }
  // Range errors bailed out earlier; only the failing allocation needs to be
  // caught here.
  if (!backing_store) {
    return {nullptr, MessageTemplate::kArrayBufferAllocationFailed};
  }
  return {std::move(backing_store), std::nullopt};
}
References v8::internal::BackingStore::Allocate(), v8::internal::Isolate::array_buffer_allocator(), v8::internal::DCHECK(), v8::internal::JSArrayBuffer::GetResizableBackingStorePageConfigurationImpl(), v8::internal::JSArrayBuffer::kMaxByteLength, v8::internal::JSTypedArray::kMaxByteLength, v8::internal::kNotResizable, v8::internal::kNotWasm, v8::internal::kResizable, v8::internal::length, v8::ArrayBuffer::Allocator::MaxAllocationSize(), v8::internal::BackingStore::TryAllocateAndPartiallyCommitMemory(), and v8::internal::TryNumberToSize().
Referenced by ConstructBuffer().