v8::base::detail Namespace Reference
Classes
struct nth_type
struct nth_type< 0, T, Ts... >
struct nth_type< N, T, Ts... >
Functions
template<typename... Ts>
std::string PrintToString (Ts &&... ts)
template<typename T >
auto GetUnderlyingEnumTypeForPrinting (T val)
template<typename Function , std::size_t... Indexes>
constexpr auto make_array_helper (Function f, std::index_sequence< Indexes... >) -> std::array< decltype(f(0)), sizeof...(Indexes)>
template<size_t N, typename T , size_t... Ints>
constexpr auto tuple_slice_impl (const T &tpl, std::index_sequence< Ints... >)
template<typename Tuple , typename Function , size_t... Index>
constexpr auto tuple_for_each_impl (const Tuple &tpl, Function &&function, std::index_sequence< Index... >)
template<typename Tuple , typename Function , size_t... Index>
constexpr auto tuple_for_each_with_index_impl (const Tuple &tpl, Function &&function, std::index_sequence< Index... >)
template<typename Tuple , typename Function , size_t... Index>
constexpr auto tuple_map_impl (Tuple &&tpl, const Function &function, std::index_sequence< Index... >)
template<typename TupleV , typename TupleU , typename Function , size_t... Index>
constexpr auto tuple_map2_impl (TupleV &&tplv, TupleU &&tplu, const Function &function, std::index_sequence< Index... >)
template<size_t I, typename T , typename Tuple , typename Function >
constexpr auto tuple_fold_impl (T &&initial, Tuple &&tpl, Function &&function)
Variables
template<size_t N, typename Tuple >
constexpr bool NIsNotGreaterThanTupleSize
Function Documentation
GetUnderlyingEnumTypeForPrinting()
template<typename T >
auto v8::base::detail::GetUnderlyingEnumTypeForPrinting (T val)
Definition at line 195 of file logging.h.
                                             {
  auto underlying_val = static_cast<std::underlying_type_t<T>>(val);
  // For single-byte enums, return a 16-bit integer to avoid printing the value
  // as a character.
  if constexpr (sizeof(underlying_val) == 1) {
    constexpr bool kIsSigned = std::is_signed_v<decltype(underlying_val)>;
    using int_t = std::conditional_t<kIsSigned, int16_t, uint16_t>;
    return static_cast<int_t>(underlying_val);
  } else {
    return underlying_val;
  }
}
Referenced by v8::base::requires().
make_array_helper()
template<typename Function , std::size_t... Indexes>
constexpr auto v8::base::detail::make_array_helper (Function f, std::index_sequence< Indexes... >) -> std::array<decltype(f(0)), sizeof...(Indexes)> [inline], [constexpr]
Definition at line 23 of file template-utils.h.
                                                    {
  return {{f(Indexes)...}};
}
Referenced by v8::base::make_array().
PrintToString()
template<typename... Ts>
std::string v8::base::detail::PrintToString (Ts &&... ts)
Definition at line 188 of file logging.h.
                                    {
  CheckMessageStream oss;
  (..., (oss << std::forward<Ts>(ts)));
  return oss.str();
}
Referenced by v8::base::requires().
tuple_fold_impl()
template<size_t I, typename T , typename Tuple , typename Function >
constexpr auto v8::base::detail::tuple_fold_impl (T && initial, Tuple && tpl, Function && function) [constexpr]
Definition at line 112 of file template-utils.h.
                                                                              {
  if constexpr (I == 0) {
    return function(std::forward<T>(initial), std::get<0>(tpl));
  } else {
    return function(tuple_fold_impl<I - 1>(std::forward<T>(initial),
                                           std::forward<Tuple>(tpl), function),
                    std::get<I>(tpl));
  }
}
References I.
tuple_for_each_impl()
template<typename Tuple , typename Function , size_t... Index>
constexpr auto v8::base::detail::tuple_for_each_impl (const Tuple & tpl, Function && function, std::index_sequence< Index... >) [constexpr]
Definition at line 83 of file template-utils.h.
                                                                {
  (function(std::get<Index>(tpl)), ...);
}
Referenced by v8::base::tuple_for_each().
tuple_for_each_with_index_impl()
template<typename Tuple , typename Function , size_t... Index>
constexpr auto v8::base::detail::tuple_for_each_with_index_impl (const Tuple & tpl, Function && function, std::index_sequence< Index... >) [constexpr]
Definition at line 89 of file template-utils.h.
                                                                           {
  (function(std::get<Index>(tpl), std::integral_constant<size_t, Index>()),
   ...);
}
Referenced by v8::base::tuple_for_each_with_index().
tuple_map2_impl()
template<typename TupleV , typename TupleU , typename Function , size_t... Index>
constexpr auto v8::base::detail::tuple_map2_impl (TupleV && tplv, TupleU && tplu, const Function & function, std::index_sequence< Index... >) [constexpr]
Definition at line 104 of file template-utils.h.
                                                            {
  return std::make_tuple(
      function(std::get<Index>(tplv), std::get<Index>(tplu))...);
}
Referenced by v8::base::tuple_map2().
tuple_map_impl()
template<typename Tuple , typename Function , size_t... Index>
constexpr auto v8::base::detail::tuple_map_impl (Tuple && tpl, const Function & function, std::index_sequence< Index... >) [constexpr]
Definition at line 97 of file template-utils.h.
                                                           {
  return std::make_tuple(
      function(std::get<Index>(std::forward<Tuple>(tpl)))...);
}
Referenced by v8::base::tuple_map().
tuple_slice_impl()
template<size_t N, typename T , size_t... Ints>
constexpr auto v8::base::detail::tuple_slice_impl (const T & tpl, std::index_sequence< Ints... >) [constexpr]
Definition at line 78 of file template-utils.h.
                                                                          {
  return std::tuple{std::get<N + Ints>(tpl)...};
}
Variable Documentation
NIsNotGreaterThanTupleSize
template<size_t N, typename Tuple >
constexpr bool v8::base::detail::NIsNotGreaterThanTupleSize [constexpr]
Initial value:
=
    N <= std::tuple_size_v<std::decay_t<Tuple>>
Definition at line 74 of file template-utils.h.