v8::internal::anonymous_namespace{pretenuring-handler.cc} Namespace Reference
Functions
double GetPretenuringRatioThreshold (size_t new_space_capacity)
bool MakePretenureDecision (Tagged< AllocationSite > site, AllocationSite::PretenureDecision current_decision, double ratio, bool new_space_capacity_was_above_pretenuring_threshold, size_t new_space_capacity)
void ResetPretenuringFeedback (Tagged< AllocationSite > site)
bool DigestPretenuringFeedback (Isolate *isolate, Tagged< AllocationSite > site, bool new_space_capacity_was_above_pretenuring_threshold, size_t new_space_capacity)
bool PretenureAllocationSiteManually (Isolate *isolate, Tagged< AllocationSite > site)
Variables
static constexpr int kMinMementoCount = 100
Function Documentation
DigestPretenuringFeedback()
bool v8::internal::anonymous_namespace{pretenuring-handler.cc}::DigestPretenuringFeedback (Isolate * isolate, Tagged< AllocationSite > site, bool new_space_capacity_was_above_pretenuring_threshold, size_t new_space_capacity) [inline]
Definition at line 74 of file pretenuring-handler.cc.
                               {
  bool deopt = false;
  int create_count = site->memento_create_count();
  int found_count = site->memento_found_count();
  bool minimum_mementos_created = create_count >= kMinMementoCount;
  double ratio =
      minimum_mementos_created || v8_flags.trace_pretenuring_statistics
          ? static_cast<double>(found_count) / create_count
          : 0.0;
  AllocationSite::PretenureDecision current_decision =
      site->pretenure_decision();
  if (minimum_mementos_created) {
    deopt = MakePretenureDecision(
        site, current_decision, ratio,
        new_space_capacity_was_above_pretenuring_threshold, new_space_capacity);
  }
  if (V8_UNLIKELY(v8_flags.trace_pretenuring_statistics)) {
    PrintIsolate(isolate,
                 "pretenuring: AllocationSite(%p): (created, found, ratio) "
                 "(%d, %d, %f) %s => %s\n",
                 reinterpret_cast<void*>(site.ptr()), create_count, found_count,
                 ratio, site->PretenureDecisionName(current_decision),
                 site->PretenureDecisionName(site->pretenure_decision()));
  }
  ResetPretenuringFeedback(site);
  return deopt;
}
References kMinMementoCount, MakePretenureDecision(), v8::internal::PrintIsolate(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), ResetPretenuringFeedback(), v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by v8::internal::PretenuringHandler::ProcessPretenuringFeedback().
GetPretenuringRatioThreshold()
double v8::internal::anonymous_namespace{pretenuring-handler.cc}::GetPretenuringRatioThreshold (size_t new_space_capacity)
Definition at line 28 of file pretenuring-handler.cc.
                                                               {
  static constexpr double kScavengerPretenureRatio = 0.85;
  // MinorMS allows for a much larger new space, thus we require a lower
  // survival rate for pretenuring.
  static constexpr double kMinorMSPretenureMaxRatio = 0.8;
  static constexpr double kMinorMSMinCapacity = 16 * MB;
  if (!v8_flags.minor_ms) return kScavengerPretenureRatio;
  if (new_space_capacity <= kMinorMSMinCapacity)
    return kMinorMSPretenureMaxRatio;
  // When capacity is 64MB, the pretenuring ratio would be 0.2.
  return kMinorMSPretenureMaxRatio * kMinorMSMinCapacity / new_space_capacity;
}
References v8::internal::MB, and v8::internal::v8_flags.
Referenced by MakePretenureDecision(), and v8::internal::PretenuringHandler::ProcessPretenuringFeedback().
MakePretenureDecision()
bool v8::internal::anonymous_namespace{pretenuring-handler.cc}::MakePretenureDecision (Tagged< AllocationSite > site, AllocationSite::PretenureDecision current_decision, double ratio, bool new_space_capacity_was_above_pretenuring_threshold, size_t new_space_capacity) [inline]
Definition at line 41 of file pretenuring-handler.cc.
                               {
  // Here we just allow state transitions from undecided or maybe tenure
  // to don't tenure, maybe tenure, or tenure.
  if ((current_decision == AllocationSite::kUndecided ||
       current_decision == AllocationSite::kMaybeTenure)) {
    if (ratio >= GetPretenuringRatioThreshold(new_space_capacity)) {
      // We just transition into tenure state when the semi-space was at
      // maximum capacity.
      if (new_space_capacity_was_above_pretenuring_threshold) {
        site->set_deopt_dependent_code(true);
        site->set_pretenure_decision(AllocationSite::kTenure);
        // Currently we just need to deopt when we make a state transition to
        // tenure.
        return true;
      }
      site->set_pretenure_decision(AllocationSite::kMaybeTenure);
    } else {
      site->set_pretenure_decision(AllocationSite::kDontTenure);
    }
  }
  return false;
}
References GetPretenuringRatioThreshold(), v8::internal::AllocationSite::kDontTenure, v8::internal::AllocationSite::kMaybeTenure, v8::internal::AllocationSite::kTenure, and v8::internal::AllocationSite::kUndecided.
Referenced by DigestPretenuringFeedback().
PretenureAllocationSiteManually()
bool v8::internal::anonymous_namespace{pretenuring-handler.cc}::PretenureAllocationSiteManually (Isolate * isolate, Tagged< AllocationSite > site)
Definition at line 108 of file pretenuring-handler.cc.
                                                                  {
  AllocationSite::PretenureDecision current_decision =
      site->pretenure_decision();
  bool deopt = true;
  if (current_decision == AllocationSite::kUndecided ||
      current_decision == AllocationSite::kMaybeTenure) {
    site->set_deopt_dependent_code(true);
    site->set_pretenure_decision(AllocationSite::kTenure);
  } else {
    deopt = false;
  }
  if (v8_flags.trace_pretenuring_statistics) {
    PrintIsolate(isolate,
                 "pretenuring manually requested: AllocationSite(%p): "
                 "%s => %s\n",
                 reinterpret_cast<void*>(site.ptr()),
                 site->PretenureDecisionName(current_decision),
                 site->PretenureDecisionName(site->pretenure_decision()));
  }
  ResetPretenuringFeedback(site);
  return deopt;
}
References v8::internal::AllocationSite::kMaybeTenure, v8::internal::AllocationSite::kTenure, v8::internal::AllocationSite::kUndecided, v8::internal::PrintIsolate(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), ResetPretenuringFeedback(), and v8::internal::v8_flags.
Referenced by v8::internal::PretenuringHandler::ProcessPretenuringFeedback().
ResetPretenuringFeedback()
void v8::internal::anonymous_namespace{pretenuring-handler.cc}::ResetPretenuringFeedback (Tagged< AllocationSite > site) [inline]
Definition at line 69 of file pretenuring-handler.cc.
                                                                  {
  site->set_memento_found_count(0);
  site->set_memento_create_count(0);
}
Referenced by DigestPretenuringFeedback(), and PretenureAllocationSiteManually().
Variable Documentation
kMinMementoCount
constexpr int v8::internal::anonymous_namespace{pretenuring-handler.cc}::kMinMementoCount = 100 [static], [constexpr]
Definition at line 26 of file pretenuring-handler.cc.
Referenced by DigestPretenuringFeedback(), v8::internal::PretenuringHandler::GetMinMementoCountForTesting(), and v8::internal::PretenuringHandler::MergeAllocationSitePretenuringFeedback().