v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc} Namespace Reference
Classes
struct BytecodeArgument
struct BytecodeArgumentMapping
struct BytecodeArgumentCheck
class BytecodeSequenceNode
class RegExpBytecodePeephole
Functions
template<typename T >
T GetValue (const uint8_t *buffer, int pos)
int32_t GetArgumentValue (const uint8_t *bytecode, int offset, int length)
Function Documentation
GetArgumentValue()
int32_t v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::GetArgumentValue (const uint8_t * bytecode, int offset, int length)
Definition at line 263 of file regexp-bytecode-peephole.cc.
                                                                          {
  switch (length) {
    case 1:
      return GetValue<uint8_t>(bytecode, offset);
    case 2:
      return GetValue<int16_t>(bytecode, offset);
    case 4:
      return GetValue<int32_t>(bytecode, offset);
    default:
      UNREACHABLE();
  }
}
References v8::internal::length, and v8::internal::UNREACHABLE().
Referenced by v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::CheckArguments().
GetValue()
template<typename T >
T v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::GetValue (const uint8_t * buffer, int pos)
Definition at line 258 of file regexp-bytecode-peephole.cc.
                                           {
  DCHECK(IsAligned(reinterpret_cast<Address>(buffer + pos), alignof(T)));
  return *reinterpret_cast<const T*>(buffer + pos);
}
References v8::internal::DCHECK(), and IsAligned().