v8::internal::anonymous_namespace{value-serializer.cc} Namespace Reference
Typedefs
using JSArrayBufferViewIsLengthTracking = base::BitField< bool, 0, 1 >
using JSArrayBufferViewIsBackedByRab = JSArrayBufferViewIsLengthTracking::Next< bool, 1 >
Enumerations
enum class ArrayBufferViewTag : uint8_t {
kInt8Array = 'b'
, kUint8Array = 'B'
, kUint8ClampedArray = 'C'
, kInt16Array = 'w'
,
kUint16Array = 'W'
, kInt32Array = 'd'
, kUint32Array = 'D'
, kFloat16Array = 'h'
,
kFloat32Array = 'f'
, kFloat64Array = 'F'
, kBigInt64Array = 'q'
, kBigUint64Array = 'Q'
,
kDataView = '?'
 }
enum class ErrorTag : uint8_t {
kEvalErrorPrototype = 'E'
, kRangeErrorPrototype = 'R'
, kReferenceErrorPrototype = 'F'
, kSyntaxErrorPrototype = 'S'
,
kTypeErrorPrototype = 'T'
, kUriErrorPrototype = 'U'
, kMessage = 'm'
, kCause = 'c'
,
kStack = 's'
, kEnd = '.'
 }
enum class WasmMemoryArrayBufferTag : uint8_t { kFixedLength = 'f'
, kResizableNotFollowedByWasmMemory = 'r'
, kResizableFollowedByWasmMemory = 'w'
 }
Functions
void ThrowDeserializationExceptionIfNonePending (Isolate *isolate)
Typedef Documentation
JSArrayBufferViewIsBackedByRab
using v8::internal::anonymous_namespace{value-serializer.cc}::JSArrayBufferViewIsBackedByRab = typedef JSArrayBufferViewIsLengthTracking::Next<bool, 1>
Definition at line 100 of file value-serializer.cc.
JSArrayBufferViewIsLengthTracking
using v8::internal::anonymous_namespace{value-serializer.cc}::JSArrayBufferViewIsLengthTracking = typedef base::BitField<bool, 0, 1>
Definition at line 99 of file value-serializer.cc.
Enumeration Type Documentation
ArrayBufferViewTag
enum v8::internal::anonymous_namespace{value-serializer.cc}::ArrayBufferViewTag : uint8_t [strong]
Enumerator
kInt8Array
kUint8Array
kUint8ClampedArray
kInt16Array
kUint16Array
kInt32Array
kUint32Array
kFloat16Array
kFloat32Array
kFloat64Array
kBigInt64Array
kBigUint64Array
kDataView
Definition at line 247 of file value-serializer.cc.
                              : uint8_t {
  kInt8Array = 'b',
  kUint8Array = 'B',
  kUint8ClampedArray = 'C',
  kInt16Array = 'w',
  kUint16Array = 'W',
  kInt32Array = 'd',
  kUint32Array = 'D',
  kFloat16Array = 'h',
  kFloat32Array = 'f',
  kFloat64Array = 'F',
  kBigInt64Array = 'q',
  kBigUint64Array = 'Q',
  kDataView = '?',
};
ErrorTag
enum v8::internal::anonymous_namespace{value-serializer.cc}::ErrorTag : uint8_t [strong]
Enumerator
kEvalErrorPrototype
kRangeErrorPrototype
kReferenceErrorPrototype
kSyntaxErrorPrototype
kTypeErrorPrototype
kUriErrorPrototype
kMessage
kCause
kStack
kEnd
Definition at line 264 of file value-serializer.cc.
                    : uint8_t {
  // The error is an EvalError. No accompanying data.
  kEvalErrorPrototype = 'E',
  // The error is a RangeError. No accompanying data.
  kRangeErrorPrototype = 'R',
  // The error is a ReferenceError. No accompanying data.
  kReferenceErrorPrototype = 'F',
  // The error is a SyntaxError. No accompanying data.
  kSyntaxErrorPrototype = 'S',
  // The error is a TypeError. No accompanying data.
  kTypeErrorPrototype = 'T',
  // The error is a URIError. No accompanying data.
  kUriErrorPrototype = 'U',
  // Followed by message: string.
  kMessage = 'm',
  // Followed by a JS object: cause.
  kCause = 'c',
  // Followed by stack: string.
  kStack = 's',
  // The end of this error information.
  kEnd = '.',
};
WasmMemoryArrayBufferTag
enum v8::internal::anonymous_namespace{value-serializer.cc}::WasmMemoryArrayBufferTag : uint8_t [strong]
Enumerator
kFixedLength
kResizableNotFollowedByWasmMemory
kResizableFollowedByWasmMemory
Definition at line 287 of file value-serializer.cc.
                                    : uint8_t {
  kFixedLength = 'f',
  kResizableNotFollowedByWasmMemory = 'r',
  kResizableFollowedByWasmMemory = 'w'
};
Function Documentation
ThrowDeserializationExceptionIfNonePending()
void v8::internal::anonymous_namespace{value-serializer.cc}::ThrowDeserializationExceptionIfNonePending (Isolate * isolate)
Definition at line 2462 of file value-serializer.cc.
                                                                  {
  if (!isolate->has_exception()) {
    isolate->Throw(*isolate->factory()->NewError(
        MessageTemplate::kDataCloneDeserializationError));
  }
  DCHECK(isolate->has_exception());
}
References v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::internal::Isolate::has_exception(), v8::internal::Factory::NewError(), and v8::internal::Isolate::Throw().
Referenced by v8::internal::ValueDeserializer::ReadObjectUsingEntireBufferForLegacyFormat(), and v8::internal::ValueDeserializer::ReadSharedObject().