v8::internal::compiler::anonymous_namespace{constant-folding-reducer.cc} Namespace Reference
Functions
Node * TryGetConstant (JSGraph *jsgraph, Node *node, JSHeapBroker *broker)
Function Documentation
TryGetConstant()
Node* v8::internal::compiler::anonymous_namespace{constant-folding-reducer.cc}::TryGetConstant (JSGraph * jsgraph, Node * node, JSHeapBroker * broker)
Definition at line 16 of file constant-folding-reducer.cc.
                                                                         {
  Type type = NodeProperties::GetType(node);
  Node* result;
  if (type.IsNone()) {
    result = nullptr;
  } else if (type.Is(Type::Null())) {
    result = jsgraph->NullConstant();
  } else if (type.Is(Type::Undefined())) {
    result = jsgraph->UndefinedConstant();
  } else if (type.Is(Type::MinusZero())) {
    result = jsgraph->MinusZeroConstant();
  } else if (type.Is(Type::NaN())) {
    result = jsgraph->NaNConstant();
  } else if (type.IsHeapConstant()) {
    result = jsgraph->ConstantNoHole(type.AsHeapConstant()->Ref(), broker);
  } else if (type.Is(Type::PlainNumber()) && type.Min() == type.Max()) {
    result = jsgraph->ConstantNoHole(type.Min());
  } else {
    result = nullptr;
  }
  DCHECK_EQ(result != nullptr, type.IsSingleton());
  DCHECK_IMPLIES(result != nullptr,
                 type.Equals(NodeProperties::GetType(result)));
  return result;
}
References broker(), v8::internal::compiler::JSGraph::ConstantNoHole(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::Null, v8::base::internal::result, v8::internal::tracing::type, and v8::internal::compiler::Undefined.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfUndefinedOrNull(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckNotHole(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckNumericalValue(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckValueByReference(), v8::internal::maglev::MaglevGraphBuilder::BuildConstruct(), v8::internal::maglev::MaglevGraphBuilder::BuildConvertHoleToUndefined(), v8::internal::maglev::MaglevGraphBuilder::GetConvertReceiver(), v8::internal::compiler::ConstantFoldingReducer::Reduce(), v8::internal::maglev::MaglevGraphBuilder::ReduceCall(), v8::internal::maglev::MaglevGraphBuilder::ReduceCallWithArrayLikeForArgumentsObject(), v8::internal::maglev::MaglevGraphBuilder::TryBuildAndAllocateJSGeneratorObject(), v8::internal::maglev::MaglevGraphBuilder::TryBuildFastInstanceOfWithFeedback(), v8::internal::maglev::MaglevGraphBuilder::TryBuildFindNonDefaultConstructorOrConstruct(), v8::internal::maglev::MaglevGraphBuilder::TryReduceConstantStringAt(), and v8::internal::maglev::MaglevGraphBuilder::TryReduceConstructGeneric().