v8::internal::wasm::anonymous_namespace{wasm-module.cc} Namespace Reference
Functions
DirectHandle< String > ToValueTypeString (Isolate *isolate, ValueType type)
Function Documentation
ToValueTypeString()
DirectHandle<String> v8::internal::wasm::anonymous_namespace{wasm-module.cc}::ToValueTypeString (Isolate * isolate, ValueType type)
Definition at line 285 of file wasm-module.cc.
                                                                         {
  return isolate->factory()->InternalizeUtf8String(base::VectorOf(type.name()));
}
References v8::internal::Isolate::factory(), v8::internal::Factory::InternalizeUtf8String(), v8::internal::tracing::type, and v8::base::VectorOf().
Referenced by v8::internal::wasm::GetTypeForFunction(), and v8::internal::wasm::GetTypeForGlobal().