v8::internal::anonymous_namespace{handler-configuration.cc} Namespace Reference
Functions
template<typename BitField >
Tagged< Smi > SetBitFieldValue (Isolate *isolate, Tagged< Smi > smi_handler, typename BitField::FieldType value)
template<typename ICHandler , bool fill_handler = true>
int InitPrototypeChecksImpl (Isolate *isolate, DirectHandle< ICHandler > handler, Tagged< Smi > *smi_handler, DirectHandle< Map > lookup_start_object_map, MaybeObjectDirectHandle data1, MaybeObjectDirectHandle maybe_data2)
template<typename ICHandler >
int GetHandlerDataSize (Isolate *isolate, Tagged< Smi > *smi_handler, DirectHandle< Map > lookup_start_object_map, MaybeObjectDirectHandle data1, MaybeObjectDirectHandle maybe_data2=MaybeObjectDirectHandle())
template<typename ICHandler >
void InitPrototypeChecks (Isolate *isolate, DirectHandle< ICHandler > handler, DirectHandle< Map > lookup_start_object_map, MaybeObjectDirectHandle data1, MaybeObjectDirectHandle maybe_data2=MaybeObjectDirectHandle())
Function Documentation
GetHandlerDataSize()
template<typename ICHandler >
int v8::internal::anonymous_namespace{handler-configuration.cc}::GetHandlerDataSize (Isolate * isolate, Tagged< Smi > * smi_handler, DirectHandle< Map > lookup_start_object_map, MaybeObjectDirectHandle data1, MaybeObjectDirectHandle maybe_data2 = MaybeObjectDirectHandle())
Definition at line 93 of file handler-configuration.cc.
                                                                     {
  DCHECK_NOT_NULL(smi_handler);
  return InitPrototypeChecksImpl<ICHandler, false>(
      isolate, DirectHandle<ICHandler>(), smi_handler, lookup_start_object_map,
      data1, maybe_data2);
}
References DCHECK_NOT_NULL.
InitPrototypeChecks()
template<typename ICHandler >
void v8::internal::anonymous_namespace{handler-configuration.cc}::InitPrototypeChecks (Isolate * isolate, DirectHandle< ICHandler > handler, DirectHandle< Map > lookup_start_object_map, MaybeObjectDirectHandle data1, MaybeObjectDirectHandle maybe_data2 = MaybeObjectDirectHandle())
Definition at line 104 of file handler-configuration.cc.
                                                                     {
  InitPrototypeChecksImpl<ICHandler, true>(
      isolate, handler, nullptr, lookup_start_object_map, data1, maybe_data2);
}
Referenced by v8::internal::LoadHandler::LoadFromPrototype(), v8::internal::LoadHandler::LoadFullChain(), v8::internal::LoadHandler::LoadNonExistent(), and v8::internal::StoreHandler::StoreThroughPrototype().
InitPrototypeChecksImpl()
template<typename ICHandler , bool fill_handler = true>
int v8::internal::anonymous_namespace{handler-configuration.cc}::InitPrototypeChecksImpl (Isolate * isolate, DirectHandle< ICHandler > handler, Tagged< Smi > * smi_handler, DirectHandle< Map > lookup_start_object_map, MaybeObjectDirectHandle data1, MaybeObjectDirectHandle maybe_data2)
Definition at line 29 of file handler-configuration.cc.
                                                                 {
  int data_size = 1;
  // Holder-is-receiver case itself does not add entries unless there is an
  // optional data2 value provided.
  DCHECK_IMPLIES(IsJSGlobalObjectMap(*lookup_start_object_map),
                 lookup_start_object_map->is_prototype_map());
  if (IsPrimitiveMap(*lookup_start_object_map) ||
      lookup_start_object_map->is_access_check_needed()) {
    DCHECK(!IsJSGlobalObjectMap(*lookup_start_object_map));
    // The validity cell check for primitive and global proxy receivers does
    // not guarantee that certain native context ever had access to other
    // native context. However, a handler created for one native context could
    // be used in other native context through the megamorphic stub cache.
    // So we record the original native context to which this handler
    // corresponds.
    if (fill_handler) {
      DirectHandle<Context> native_context = isolate->native_context();
      handler->set_data2(MakeWeak(*native_context));
    } else {
      // Enable access checks on the lookup start object.
      *smi_handler = SetBitFieldValue<
          typename ICHandler::DoAccessCheckOnLookupStartObjectBits>(
          isolate, *smi_handler, true);
    }
    data_size++;
  } else if (lookup_start_object_map->is_dictionary_map() &&
             !IsJSGlobalObjectMap(*lookup_start_object_map)) {
    if (!fill_handler) {
      // Enable lookup on lookup start object.
      *smi_handler =
          SetBitFieldValue<typename ICHandler::LookupOnLookupStartObjectBits>(
              isolate, *smi_handler, true);
    }
  }
  if (fill_handler) {
    handler->set_data1(*data1);
  }
  if (!maybe_data2.is_null()) {
    if (fill_handler) {
      // This value will go either to data2 or data3 slot depending on whether
      // data2 slot is already occupied by native context.
      if (data_size == 1) {
        handler->set_data2(*maybe_data2);
      } else {
        DCHECK_EQ(2, data_size);
        handler->set_data3(*maybe_data2);
      }
    }
    data_size++;
  }
  return data_size;
}
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::MaybeObjectDirectHandle::is_null(), v8::internal::IsPrimitiveMap(), v8::internal::MakeWeak(), v8::internal::Isolate::native_context(), v8::internal::native_context, and SetBitFieldValue().
SetBitFieldValue()
template<typename BitField >
Tagged<Smi> v8::internal::anonymous_namespace{handler-configuration.cc}::SetBitFieldValue (Isolate * isolate, Tagged< Smi > smi_handler, typename BitField::FieldType value)
Definition at line 19 of file handler-configuration.cc.
                                                               {
  int config = smi_handler.value();
  config = BitField::update(config, true);
  return Smi::FromInt(config);
}
References v8::internal::Smi::FromInt(), and v8::internal::Tagged< Smi >::value().
Referenced by InitPrototypeChecksImpl().