v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc} Namespace Reference
Classes
class Matcher
class DeferredMakeWeakScope
Enumerations
enum class BreakpointType {
kByUrl = 1
, kByUrlRegex
, kByScriptHash
, kByScriptId
,
kDebugCommand
, kMonitorCommand
, kBreakpointAtEntry
, kInstrumentationBreakpoint
 }
Functions
String16 generateBreakpointId (BreakpointType type, const String16 &scriptSelector, int lineNumber, int columnNumber)
String16 generateBreakpointId (BreakpointType type, v8::Local< v8::Function > function)
String16 generateInstrumentationBreakpointId (const String16 &instrumentation)
bool parseBreakpointId (const String16 &breakpointId, BreakpointType *type, String16 *scriptSelector=nullptr, int *lineNumber=nullptr, int *columnNumber=nullptr)
bool positionComparator (const std::pair< int, int > &a, const std::pair< int, int > &b)
std::unique_ptr< protocol::DictionaryValue > breakpointHint (const V8DebuggerScript &script, int breakpointLineNumber, int breakpointColumnNumber, int actualLineNumber, int actualColumnNumber)
void adjustBreakpointLocation (const V8DebuggerScript &script, const protocol::DictionaryValue *hintObject, int *lineNumber, int *columnNumber)
String16 breakLocationType (v8::debug::BreakLocationType type)
String16 scopeType (v8::debug::ScopeIterator::ScopeType type)
Response buildScopes (v8::Isolate *isolate, v8::debug::ScopeIterator *iterator, InjectedScript *injectedScript, std::unique_ptr< Array< Scope >> *scopes)
protocol::DictionaryValue * getOrCreateObject (protocol::DictionaryValue *object, const String16 &key)
Response isValidPosition (protocol::Debugger::ScriptPosition *position)
Response isValidRangeOfPositions (const std::vector< std::pair< int, int >> &positions)
bool hitBreakReasonEncodedAsOther (v8::debug::BreakReasons breakReasons)
const char * buildStatus (v8::debug::LiveEditResult::Status status)
Enumeration Type Documentation
BreakpointType
enum v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::BreakpointType [strong]
Enumerator
kByUrl
kByUrlRegex
kByScriptHash
kByScriptId
kDebugCommand
kMonitorCommand
kBreakpointAtEntry
kInstrumentationBreakpoint
Definition at line 95 of file v8-debugger-agent-impl.cc.
                          {
  kByUrl = 1,
  kByUrlRegex,
  kByScriptHash,
  kByScriptId,
  kDebugCommand,
  kMonitorCommand,
  kBreakpointAtEntry,
  kInstrumentationBreakpoint
};
Function Documentation
adjustBreakpointLocation()
void v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::adjustBreakpointLocation (const V8DebuggerScript & script, const protocol::DictionaryValue * hintObject, int * lineNumber, int * columnNumber)
Definition at line 228 of file v8-debugger-agent-impl.cc.
                                                                  {
  if (*lineNumber < script.startLine() || *lineNumber > script.endLine())
    return;
  if (*lineNumber == script.startLine() &&
      *columnNumber < script.startColumn()) {
    return;
  }
  if (*lineNumber == script.endLine() && script.endColumn() < *columnNumber) {
    return;
  }
  int sourceOffset;
  if (!script.offset(*lineNumber, *columnNumber).To(&sourceOffset)) return;
  int prefixLength = 0;
  hintObject->getInteger(DebuggerAgentState::breakpointHintPrefixLength,
                         &prefixLength);
  String16 hint;
  if (!hintObject->getString(DebuggerAgentState::breakpointHintText, &hint) ||
      hint.isEmpty())
    return;
  intptr_t searchRegionOffset = std::max(
      sourceOffset - kBreakpointHintMaxSearchOffset, static_cast<intptr_t>(0));
  size_t offset = sourceOffset - searchRegionOffset;
  size_t searchRegionSize =
      offset + std::max(kBreakpointHintMaxSearchOffset,
                        static_cast<intptr_t>(prefixLength + hint.length()));
  String16 searchArea = script.source(searchRegionOffset, searchRegionSize);
  // Let us see if the breakpoint hint text appears at the same location
  // as before, with the same prefix text in between. If yes, then we just use
  // that position.
  int prefixHash;
  if (hintObject->getInteger(DebuggerAgentState::breakpointHintPrefixHash,
                             &prefixHash) &&
      offset + prefixLength + hint.length() <= searchArea.length() &&
      searchArea.substring(offset + prefixLength, hint.length()) == hint &&
      computeCrc32(searchArea.substring(offset, prefixLength)) == prefixHash) {
    v8::debug::Location hintPosition = script.location(
        static_cast<int>(searchRegionOffset + offset + prefixLength));
    *lineNumber = hintPosition.GetLineNumber();
    *columnNumber = hintPosition.GetColumnNumber();
    return;
  }
  size_t nextMatch = searchArea.find(hint, offset);
  size_t prevMatch = searchArea.reverseFind(hint, offset);
  if (nextMatch == String16::kNotFound && prevMatch == String16::kNotFound) {
    return;
  }
  size_t bestMatch;
  if (nextMatch == String16::kNotFound ||
      nextMatch > offset + kBreakpointHintMaxSearchOffset) {
    bestMatch = prevMatch;
  } else if (prevMatch == String16::kNotFound) {
    bestMatch = nextMatch;
  } else {
    bestMatch = nextMatch - offset < offset - prevMatch ? nextMatch : prevMatch;
  }
  bestMatch += searchRegionOffset;
  v8::debug::Location hintPosition =
      script.location(static_cast<int>(bestMatch));
  if (hintPosition.IsEmpty()) return;
  *lineNumber = hintPosition.GetLineNumber();
  *columnNumber = hintPosition.GetColumnNumber();
}
References v8_inspector::DebuggerAgentState::breakpointHintPrefixHash, v8_inspector::DebuggerAgentState::breakpointHintPrefixLength, v8_inspector::DebuggerAgentState::breakpointHintText, v8_inspector::computeCrc32(), v8_inspector::String16::find(), v8::debug::Location::GetColumnNumber(), v8::debug::Location::GetLineNumber(), v8::debug::Location::IsEmpty(), v8_inspector::String16::isEmpty(), v8_inspector::kBreakpointHintMaxSearchOffset, v8_inspector::String16::kNotFound, v8_inspector::String16::length(), v8_inspector::String16::reverseFind(), v8::internal::script, and v8_inspector::String16::substring().
Referenced by v8_inspector::V8DebuggerAgentImpl::didParseSource(), and v8_inspector::V8DebuggerAgentImpl::setBreakpointByUrl().
breakLocationType()
String16 v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::breakLocationType (v8::debug::BreakLocationType type)
Definition at line 299 of file v8-debugger-agent-impl.cc.
                                                          {
  switch (type) {
    case v8::debug::kCallBreakLocation:
      return protocol::Debugger::BreakLocation::TypeEnum::Call;
    case v8::debug::kReturnBreakLocation:
      return protocol::Debugger::BreakLocation::TypeEnum::Return;
    case v8::debug::kDebuggerStatementBreakLocation:
      return protocol::Debugger::BreakLocation::TypeEnum::DebuggerStatement;
    case v8::debug::kCommonBreakLocation:
      return String16();
  }
  return String16();
}
References v8::debug::kCallBreakLocation, v8::debug::kCommonBreakLocation, v8::debug::kDebuggerStatementBreakLocation, v8::debug::kReturnBreakLocation, and v8::internal::tracing::type.
Referenced by v8_inspector::V8DebuggerAgentImpl::getPossibleBreakpoints().
breakpointHint()
std::unique_ptr<protocol::DictionaryValue> v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::breakpointHint (const V8DebuggerScript & script, int breakpointLineNumber, int breakpointColumnNumber, int actualLineNumber, int actualColumnNumber)
Definition at line 188 of file v8-debugger-agent-impl.cc.
                                                                              {
  int actualOffset;
  int breakpointOffset;
  if (!script.offset(actualLineNumber, actualColumnNumber).To(&actualOffset) ||
      !script.offset(breakpointLineNumber, breakpointColumnNumber)
           .To(&breakpointOffset)) {
    return {};
  }
  auto hintObject = protocol::DictionaryValue::create();
  String16 rawHint = script.source(actualOffset, kBreakpointHintMaxLength);
  std::pair<size_t, size_t> offsetAndLength =
      rawHint.getTrimmedOffsetAndLength();
  String16 hint =
      rawHint.substring(offsetAndLength.first, offsetAndLength.second);
  for (size_t i = 0; i < hint.length(); ++i) {
    if (hint[i] == '\r' || hint[i] == '\n' || hint[i] == ';') {
      hint = hint.substring(0, i);
      break;
    }
  }
  hintObject->setString(DebuggerAgentState::breakpointHintText, hint);
  // Also store the hash of the text between the requested breakpoint location
  // and the actual breakpoint location. If we see the same prefix text next
  // time, we will keep the breakpoint at the same location (so that
  // breakpoints do not slide around on reloads without any edits).
  if (breakpointOffset <= actualOffset) {
    size_t length = actualOffset - breakpointOffset + offsetAndLength.first;
    String16 prefix = script.source(breakpointOffset, length);
    int crc32 = computeCrc32(prefix);
    hintObject->setInteger(DebuggerAgentState::breakpointHintPrefixHash, crc32);
    hintObject->setInteger(DebuggerAgentState::breakpointHintPrefixLength,
                           v8::base::checked_cast<int32_t>(length));
  }
  return hintObject;
}
References v8_inspector::DebuggerAgentState::breakpointHintPrefixHash, v8_inspector::DebuggerAgentState::breakpointHintPrefixLength, v8_inspector::DebuggerAgentState::breakpointHintText, v8_inspector::computeCrc32(), v8_inspector::String16::getTrimmedOffsetAndLength(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8_inspector::kBreakpointHintMaxLength, v8::internal::length, v8_inspector::String16::length(), v8::internal::script, and v8_inspector::String16::substring().
Referenced by v8_inspector::V8DebuggerAgentImpl::setBreakpointByUrl().
buildScopes()
Response v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::buildScopes (v8::Isolate * isolate, v8::debug::ScopeIterator * iterator, InjectedScript * injectedScript, std::unique_ptr< Array< Scope >> * scopes)
Definition at line 339 of file v8-debugger-agent-impl.cc.
                                                          {
  *scopes = std::make_unique<Array<Scope>>();
  if (!injectedScript) return Response::Success();
  if (iterator->Done()) return Response::Success();
  String16 scriptId = String16::fromInteger(iterator->GetScriptId());
  for (; !iterator->Done(); iterator->Advance()) {
    std::unique_ptr<RemoteObject> object;
    Response result =
        injectedScript->wrapObject(iterator->GetObject(), kBacktraceObjectGroup,
                                   WrapOptions({WrapMode::kIdOnly}), &object);
    if (!result.IsSuccess()) return result;
    auto scope = Scope::create()
                     .setType(scopeType(iterator->GetType()))
                     .setObject(std::move(object))
                     .build();
    String16 name = toProtocolStringWithTypeCheck(
        isolate, iterator->GetFunctionDebugName());
    if (!name.isEmpty()) scope->setName(name);
    if (iterator->HasLocationInfo()) {
      v8::debug::Location start = iterator->GetStartLocation();
      scope->setStartLocation(protocol::Debugger::Location::create()
                                  .setScriptId(scriptId)
                                  .setLineNumber(start.GetLineNumber())
                                  .setColumnNumber(start.GetColumnNumber())
                                  .build());
      v8::debug::Location end = iterator->GetEndLocation();
      scope->setEndLocation(protocol::Debugger::Location::create()
                                .setScriptId(scriptId)
                                .setLineNumber(end.GetLineNumber())
                                .setColumnNumber(end.GetColumnNumber())
                                .build());
    }
    (*scopes)->emplace_back(std::move(scope));
  }
  return Response::Success();
}
References v8::debug::ScopeIterator::Advance(), v8::debug::ScopeIterator::Done(), v8::internal::compiler::end(), v8_inspector::String16::fromInteger(), v8::debug::Location::GetColumnNumber(), v8::debug::ScopeIterator::GetEndLocation(), v8::debug::ScopeIterator::GetFunctionDebugName(), v8::debug::Location::GetLineNumber(), v8::debug::ScopeIterator::GetObject(), v8::debug::ScopeIterator::GetScriptId(), v8::debug::ScopeIterator::GetStartLocation(), v8::debug::ScopeIterator::GetType(), v8::debug::ScopeIterator::HasLocationInfo(), v8_inspector::kBacktraceObjectGroup, v8_inspector::kIdOnly, name, v8::base::internal::result, scopeType(), v8_inspector::toProtocolStringWithTypeCheck(), and v8_inspector::InjectedScript::wrapObject().
Referenced by v8_inspector::V8DebuggerAgentImpl::currentCallFrames().
buildStatus()
const char* v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::buildStatus (v8::debug::LiveEditResult::Status status)
Definition at line 1128 of file v8-debugger-agent-impl.cc.
                                                            {
  switch (status) {
    case v8::debug::LiveEditResult::OK:
      return protocol::Debugger::SetScriptSource::StatusEnum::Ok;
    case v8::debug::LiveEditResult::COMPILE_ERROR:
      return protocol::Debugger::SetScriptSource::StatusEnum::CompileError;
    case v8::debug::LiveEditResult::BLOCKED_BY_ACTIVE_FUNCTION:
      return protocol::Debugger::SetScriptSource::StatusEnum::
          BlockedByActiveFunction;
    case v8::debug::LiveEditResult::BLOCKED_BY_RUNNING_GENERATOR:
      return protocol::Debugger::SetScriptSource::StatusEnum::
          BlockedByActiveGenerator;
    case v8::debug::LiveEditResult::BLOCKED_BY_TOP_LEVEL_ES_MODULE_CHANGE:
      return protocol::Debugger::SetScriptSource::StatusEnum::
          BlockedByTopLevelEsModuleChange;
  }
}
References v8::debug::LiveEditResult::BLOCKED_BY_ACTIVE_FUNCTION, v8::debug::LiveEditResult::BLOCKED_BY_RUNNING_GENERATOR, v8::debug::LiveEditResult::BLOCKED_BY_TOP_LEVEL_ES_MODULE_CHANGE, v8::debug::LiveEditResult::COMPILE_ERROR, v8::debug::LiveEditResult::OK, and v8::internal::status.
Referenced by v8_inspector::V8DebuggerAgentImpl::setScriptSource().
generateBreakpointId() [1/2]
String16 v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::generateBreakpointId (BreakpointType type, const String16 & scriptSelector, int lineNumber, int columnNumber)
Definition at line 106 of file v8-debugger-agent-impl.cc.
                                                {
  String16Builder builder;
  builder.appendNumber(static_cast<int>(type));
  builder.append(':');
  builder.appendNumber(lineNumber);
  builder.append(':');
  builder.appendNumber(columnNumber);
  builder.append(':');
  builder.append(scriptSelector);
  return builder.toString();
}
References v8_inspector::String16Builder::append(), v8_inspector::String16Builder::appendNumber(), v8_inspector::String16Builder::toString(), and v8::internal::tracing::type.
generateBreakpointId() [2/2]
String16 v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::generateBreakpointId (BreakpointType type, v8::Local< v8::Function > function)
Definition at line 120 of file v8-debugger-agent-impl.cc.
                                                            {
  String16Builder builder;
  builder.appendNumber(static_cast<int>(type));
  builder.append(':');
  builder.appendNumber(v8::debug::GetDebuggingId(function));
  return builder.toString();
}
References v8_inspector::String16Builder::append(), v8_inspector::String16Builder::appendNumber(), v8::debug::GetDebuggingId(), v8_inspector::String16Builder::toString(), and v8::internal::tracing::type.
Referenced by v8_inspector::V8DebuggerAgentImpl::removeBreakpointFor(), v8_inspector::V8DebuggerAgentImpl::setBreakpoint(), v8_inspector::V8DebuggerAgentImpl::setBreakpointByUrl(), v8_inspector::V8DebuggerAgentImpl::setBreakpointFor(), and v8_inspector::V8DebuggerAgentImpl::setBreakpointOnFunctionCall().
generateInstrumentationBreakpointId()
String16 v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::generateInstrumentationBreakpointId (const String16 & instrumentation)
Definition at line 129 of file v8-debugger-agent-impl.cc.
                                                                              {
  String16Builder builder;
  builder.appendNumber(
      static_cast<int>(BreakpointType::kInstrumentationBreakpoint));
  builder.append(':');
  builder.append(instrumentation);
  return builder.toString();
}
References v8_inspector::String16Builder::append(), v8_inspector::String16Builder::appendNumber(), and v8_inspector::String16Builder::toString().
Referenced by v8_inspector::V8DebuggerAgentImpl::setInstrumentationBreakpoint(), and v8_inspector::V8DebuggerAgentImpl::setScriptInstrumentationBreakpointIfNeeded().
getOrCreateObject()
protocol::DictionaryValue* v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::getOrCreateObject (protocol::DictionaryValue * object, const String16 & key)
Definition at line 384 of file v8-debugger-agent-impl.cc.
                                                                  {
  protocol::DictionaryValue* value = object->getObject(key);
  if (value) return value;
  std::unique_ptr<protocol::DictionaryValue> newDictionary =
      protocol::DictionaryValue::create();
  value = newDictionary.get();
  object->setObject(key, std::move(newDictionary));
  return value;
}
References v8::internal::key, and v8::internal::value.
Referenced by v8_inspector::V8DebuggerAgentImpl::setBreakpointByUrl(), and v8_inspector::V8DebuggerAgentImpl::setInstrumentationBreakpoint().
hitBreakReasonEncodedAsOther()
bool v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::hitBreakReasonEncodedAsOther (v8::debug::BreakReasons breakReasons)
Definition at line 416 of file v8-debugger-agent-impl.cc.
                                                                    {
  // The listed break reasons are not explicitly encoded in CDP when
  // reporting the break. They are summarized as 'other'.
  v8::debug::BreakReasons otherBreakReasons(
      {v8::debug::BreakReason::kDebuggerStatement,
       v8::debug::BreakReason::kScheduled,
       v8::debug::BreakReason::kAlreadyPaused});
  return breakReasons.contains_any(otherBreakReasons);
}
References v8::base::EnumSet< E, T >::contains_any(), v8::debug::kAlreadyPaused, v8::debug::kDebuggerStatement, and v8::debug::kScheduled.
Referenced by v8_inspector::V8DebuggerAgentImpl::didPause().
isValidPosition()
Response v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::isValidPosition (protocol::Debugger::ScriptPosition * position)
Definition at line 395 of file v8-debugger-agent-impl.cc.
                                                                   {
  if (position->getLineNumber() < 0)
    return Response::ServerError("Position missing 'line' or 'line' < 0.");
  if (position->getColumnNumber() < 0)
    return Response::ServerError("Position missing 'column' or 'column' < 0.");
  return Response::Success();
}
Referenced by v8_inspector::V8DebuggerAgentImpl::processSkipList(), and v8_inspector::V8DebuggerAgentImpl::setBlackboxedRanges().
isValidRangeOfPositions()
Response v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::isValidRangeOfPositions (const std::vector< std::pair< int, int >> & positions)
Definition at line 403 of file v8-debugger-agent-impl.cc.
                                                   {
  for (size_t i = 1; i < positions.size(); ++i) {
    if (positions[i - 1].first < positions[i].first) continue;
    if (positions[i - 1].first == positions[i].first &&
        positions[i - 1].second < positions[i].second)
      continue;
    return Response::ServerError(
        "Input positions array is not sorted or contains duplicate values.");
  }
  return Response::Success();
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i.
Referenced by v8_inspector::V8DebuggerAgentImpl::processSkipList(), and v8_inspector::V8DebuggerAgentImpl::setBlackboxedRanges().
parseBreakpointId()
bool v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::parseBreakpointId (const String16 & breakpointId, BreakpointType * type, String16 * scriptSelector = nullptr, int * lineNumber = nullptr, int * columnNumber = nullptr)
Definition at line 138 of file v8-debugger-agent-impl.cc.
                                                                               {
  size_t typeLineSeparator = breakpointId.find(':');
  if (typeLineSeparator == String16::kNotFound) return false;
  int rawType = breakpointId.substring(0, typeLineSeparator).toInteger();
  if (rawType < static_cast<int>(BreakpointType::kByUrl) ||
      rawType > static_cast<int>(BreakpointType::kInstrumentationBreakpoint)) {
    return false;
  }
  if (type) *type = static_cast<BreakpointType>(rawType);
  if (rawType == static_cast<int>(BreakpointType::kDebugCommand) ||
      rawType == static_cast<int>(BreakpointType::kMonitorCommand) ||
      rawType == static_cast<int>(BreakpointType::kBreakpointAtEntry) ||
      rawType == static_cast<int>(BreakpointType::kInstrumentationBreakpoint)) {
    // The script and source position are not encoded in this case.
    return true;
  }
  size_t lineColumnSeparator = breakpointId.find(':', typeLineSeparator + 1);
  if (lineColumnSeparator == String16::kNotFound) return false;
  size_t columnSelectorSeparator =
      breakpointId.find(':', lineColumnSeparator + 1);
  if (columnSelectorSeparator == String16::kNotFound) return false;
  if (scriptSelector) {
    *scriptSelector = breakpointId.substring(columnSelectorSeparator + 1);
  }
  if (lineNumber) {
    *lineNumber = breakpointId
                      .substring(typeLineSeparator + 1,
                                 lineColumnSeparator - typeLineSeparator - 1)
                      .toInteger();
  }
  if (columnNumber) {
    *columnNumber =
        breakpointId
            .substring(lineColumnSeparator + 1,
                       columnSelectorSeparator - lineColumnSeparator - 1)
            .toInteger();
  }
  return true;
}
References v8_inspector::String16::find(), v8_inspector::String16::kNotFound, v8_inspector::String16::substring(), v8_inspector::String16::toInteger(), and v8::internal::tracing::type.
Referenced by v8_inspector::V8DebuggerAgentImpl::didParseSource(), v8_inspector::V8DebuggerAgentImpl::didPause(), and v8_inspector::V8DebuggerAgentImpl::removeBreakpoint().
positionComparator()
bool v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::positionComparator (const std::pair< int, int > & a, const std::pair< int, int > & b)
Definition at line 182 of file v8-debugger-agent-impl.cc.
                                                    {
  if (a.first != b.first) return a.first < b.first;
  return a.second < b.second;
}
Referenced by v8_inspector::V8DebuggerAgentImpl::isFunctionBlackboxed(), and v8_inspector::V8DebuggerAgentImpl::shouldBeSkipped().
scopeType()
String16 v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::scopeType (v8::debug::ScopeIterator::ScopeType type)
Definition at line 313 of file v8-debugger-agent-impl.cc.
                                                       {
  switch (type) {
    case v8::debug::ScopeIterator::ScopeTypeGlobal:
      return Scope::TypeEnum::Global;
    case v8::debug::ScopeIterator::ScopeTypeLocal:
      return Scope::TypeEnum::Local;
    case v8::debug::ScopeIterator::ScopeTypeWith:
      return Scope::TypeEnum::With;
    case v8::debug::ScopeIterator::ScopeTypeClosure:
      return Scope::TypeEnum::Closure;
    case v8::debug::ScopeIterator::ScopeTypeCatch:
      return Scope::TypeEnum::Catch;
    case v8::debug::ScopeIterator::ScopeTypeBlock:
      return Scope::TypeEnum::Block;
    case v8::debug::ScopeIterator::ScopeTypeScript:
      return Scope::TypeEnum::Script;
    case v8::debug::ScopeIterator::ScopeTypeEval:
      return Scope::TypeEnum::Eval;
    case v8::debug::ScopeIterator::ScopeTypeModule:
      return Scope::TypeEnum::Module;
    case v8::debug::ScopeIterator::ScopeTypeWasmExpressionStack:
      return Scope::TypeEnum::WasmExpressionStack;
  }
  UNREACHABLE();
}
References v8::debug::ScopeIterator::ScopeTypeBlock, v8::debug::ScopeIterator::ScopeTypeCatch, v8::debug::ScopeIterator::ScopeTypeClosure, v8::debug::ScopeIterator::ScopeTypeEval, v8::debug::ScopeIterator::ScopeTypeGlobal, v8::debug::ScopeIterator::ScopeTypeLocal, v8::debug::ScopeIterator::ScopeTypeModule, v8::debug::ScopeIterator::ScopeTypeScript, v8::debug::ScopeIterator::ScopeTypeWasmExpressionStack, v8::debug::ScopeIterator::ScopeTypeWith, v8::internal::tracing::type, and UNREACHABLE.
Referenced by buildScopes().