v8::internal::anonymous_namespace{map.cc} Namespace Reference
Functions
Tagged< Map > SearchMigrationTarget (Isolate *isolate, Tagged< Map > old_map)
void EnsureInitialMap (Isolate *isolate, DirectHandle< Map > map)
bool CanHoldValue (Tagged< DescriptorArray > descriptors, InternalIndex descriptor, PropertyConstness constness, Tagged< Object > value)
DirectHandle< Map > UpdateDescriptorForValue (Isolate *isolate, DirectHandle< Map > map, InternalIndex descriptor, PropertyConstness constness, DirectHandle< Object > value)
bool CheckEquivalentModuloProto (const Tagged< Map > first, const Tagged< Map > second)
Function Documentation
CanHoldValue()
bool v8::internal::anonymous_namespace{map.cc}::CanHoldValue (Tagged< DescriptorArray > descriptors, InternalIndex descriptor, PropertyConstness constness, Tagged< Object > value)
Definition at line 1938 of file map.cc.
                                                                     {
  PropertyDetails details = descriptors->GetDetails(descriptor);
  if (details.location() == PropertyLocation::kField) {
    if (details.kind() == PropertyKind::kData) {
      return IsGeneralizableTo(constness, details.constness()) &&
             Object::FitsRepresentation(value, details.representation()) &&
             FieldType::NowContains(descriptors->GetFieldType(descriptor),
                                    value);
    } else {
      DCHECK_EQ(PropertyKind::kAccessor, details.kind());
      return false;
    }
  } else {
    DCHECK_EQ(PropertyLocation::kDescriptor, details.location());
    DCHECK_EQ(PropertyConstness::kConst, details.constness());
    DCHECK_EQ(PropertyKind::kAccessor, details.kind());
    return false;
  }
  UNREACHABLE();
}
References v8::internal::PropertyDetails::constness(), DCHECK_EQ, v8::internal::Object::FitsRepresentation(), v8::internal::IsGeneralizableTo(), v8::internal::kAccessor, v8::internal::kConst, v8::internal::kData, v8::internal::kDescriptor, v8::internal::kField, v8::internal::PropertyDetails::kind(), v8::internal::PropertyDetails::location(), v8::internal::FieldType::NowContains(), v8::internal::PropertyDetails::representation(), v8::internal::UNREACHABLE(), and v8::internal::value.
Referenced by UpdateDescriptorForValue().
CheckEquivalentModuloProto()
bool v8::internal::anonymous_namespace{map.cc}::CheckEquivalentModuloProto (const Tagged< Map > first, const Tagged< Map > second)
Definition at line 2279 of file map.cc.
                                                          {
  return first->GetConstructorRaw() == second->GetConstructorRaw() &&
         first->instance_type() == second->instance_type() &&
         first->bit_field() == second->bit_field() &&
         first->is_extensible() == second->is_extensible() &&
         first->new_target_is_base() == second->new_target_is_base();
}
Referenced by v8::internal::Map::EquivalentToForNormalization().
EnsureInitialMap()
void v8::internal::anonymous_namespace{map.cc}::EnsureInitialMap (Isolate * isolate, DirectHandle< Map > map)
Definition at line 1432 of file map.cc.
                                                               {
#ifdef DEBUG
  Tagged<Object> maybe_constructor = map->GetConstructor();
  DCHECK((IsJSFunction(maybe_constructor) &&
          *map == Cast<JSFunction>(maybe_constructor)->initial_map()) ||
         // Below are the exceptions to the check above.
         // |Function|'s initial map is a |sloppy_function_map| but
         // other function map variants such as sloppy with name or readonly
         // prototype or various strict function maps variants, etc. also
         // have Function as a constructor.
         *map == *isolate->strict_function_map() ||
         *map == *isolate->strict_function_with_name_map() ||
         // Same applies to |GeneratorFunction|'s initial map and generator
         // function map variants.
         *map == *isolate->generator_function_with_name_map() ||
         // Same applies to |AsyncFunction|'s initial map and other async
         // function map variants.
         *map == *isolate->async_function_with_name_map());
#endif
  // Initial maps must not contain descriptors in the descriptors array
  // that do not belong to the map.
  DCHECK_EQ(map->NumberOfOwnDescriptors(),
            map->instance_descriptors(isolate)->number_of_descriptors());
}
References v8::internal::DCHECK(), DCHECK_EQ, and v8::internal::compiler::initial_map.
Referenced by v8::internal::Map::CopyInitialMap(), and v8::internal::Map::CopyInitialMapNormalized().
SearchMigrationTarget()
Tagged<Map> v8::internal::anonymous_namespace{map.cc}::SearchMigrationTarget (Isolate * isolate, Tagged< Map > old_map)
Definition at line 746 of file map.cc.
                                                                         {
  DisallowGarbageCollection no_gc;
  Tagged<Map> target = old_map;
  do {
    target = TransitionsAccessor(isolate, target).GetMigrationTarget();
  } while (!target.is_null() && target->is_deprecated());
  if (target.is_null()) return Map();
  SLOW_DCHECK(MapUpdater::TryUpdateNoLock(
                  isolate, old_map, ConcurrencyMode::kSynchronous) == target);
  return target;
}
References v8::internal::TransitionsAccessor::GetMigrationTarget(), v8::internal::Tagged< HeapObject >::is_null(), v8::internal::kSynchronous, v8::internal::compiler::Map, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, SLOW_DCHECK, and v8::internal::MapUpdater::TryUpdateNoLock().
Referenced by v8::internal::Map::TryUpdate(), and v8::internal::Map::Update().
UpdateDescriptorForValue()
DirectHandle<Map> v8::internal::anonymous_namespace{map.cc}::UpdateDescriptorForValue (Isolate * isolate, DirectHandle< Map > map, InternalIndex descriptor, PropertyConstness constness, DirectHandle< Object > value)
Definition at line 1961 of file map.cc.
                                                                       {
  if (CanHoldValue(map->instance_descriptors(isolate), descriptor, constness,
                   *value)) {
    return map;
  }
  PropertyAttributes attributes =
      map->instance_descriptors(isolate)->GetDetails(descriptor).attributes();
  Representation representation =
      Object::OptimalRepresentation(*value, isolate);
  DirectHandle<FieldType> type =
      Object::OptimalType(*value, isolate, representation);
  MapUpdater mu(isolate, map);
  return mu.ReconfigureToDataField(descriptor, attributes, constness,
                                   representation, type);
}
References CanHoldValue(), v8::internal::mu, v8::internal::Object::OptimalRepresentation(), v8::internal::Object::OptimalType(), v8::internal::tracing::type, and v8::internal::value.
Referenced by v8::internal::Map::PrepareForDataProperty(), and v8::internal::Map::TransitionToDataProperty().