v8::internal::anonymous_namespace{utils.cc} Namespace Reference
Functions
std::vector< char > ReadCharsFromFile (FILE *file, bool *exists, bool verbose, const char *filename)
std::vector< char > ReadCharsFromFile (const char *filename, bool *exists, bool verbose)
std::string VectorToString (const std::vector< char > &chars)
int WriteCharsToFile (const char *str, int size, FILE *f)
Function Documentation
ReadCharsFromFile() [1/2]
std::vector<char> v8::internal::anonymous_namespace{utils.cc}::ReadCharsFromFile (const char * filename, bool * exists, bool verbose)
Definition at line 148 of file utils.cc.
                                                  {
  FILE* file = base::OS::FOpen(filename, "rb");
  std::vector<char> result = ReadCharsFromFile(file, exists, verbose, filename);
  if (file != nullptr) base::Fclose(file);
  return result;
}
References v8::base::Fclose(), file(), v8::base::OS::FOpen(), and v8::base::internal::result.
Referenced by v8::internal::ReadFile().
ReadCharsFromFile() [2/2]
std::vector<char> v8::internal::anonymous_namespace{utils.cc}::ReadCharsFromFile (FILE * file, bool * exists, bool verbose, const char * filename)
Definition at line 120 of file utils.cc.
                                                          {
  if (file == nullptr || fseek(file, 0, SEEK_END) != 0) {
    if (verbose) {
      base::OS::PrintError("Cannot read from file %s.\n", filename);
    }
    *exists = false;
    return std::vector<char>();
  }
  // Get the size of the file and rewind it.
  ptrdiff_t size = ftell(file);
  rewind(file);
  std::vector<char> result(size);
  for (ptrdiff_t i = 0; i < size && feof(file) == 0;) {
    ptrdiff_t read = fread(result.data() + i, 1, size - i, file);
    if (read != (size - i) && ferror(file) != 0) {
      base::Fclose(file);
      *exists = false;
      return std::vector<char>();
    }
    i += read;
  }
  *exists = true;
  return result;
}
References v8::base::Fclose(), file(), v8::base::internal::result, and size().
VectorToString()
std::string v8::internal::anonymous_namespace{utils.cc}::VectorToString (const std::vector< char > & chars)
Definition at line 156 of file utils.cc.
                                                       {
  if (chars.empty()) {
    return std::string();
  }
  return std::string(chars.begin(), chars.end());
}
References v8::internal::string.
Referenced by v8::internal::ReadFile().
WriteCharsToFile()
int v8::internal::anonymous_namespace{utils.cc}::WriteCharsToFile (const char * str, int size, FILE * f)
Definition at line 163 of file utils.cc.
                                                         {
  int total = 0;
  while (total < size) {
    int write = static_cast<int>(fwrite(str, 1, size - total, f));
    if (write == 0) {
      return total;
    }
    total += write;
    str += write;
  }
  return total;
}
References size().
Referenced by v8::internal::WriteChars().