v8::internal::win64_unwindinfo Namespace Reference
Namespaces
 anonymous_namespace{unwinding-info-win64.cc}
Functions
bool CanEmitUnwindInfoForBuiltins ()
bool CanRegisterUnwindInfoForNonABICompliantCodeRange ()
bool RegisterUnwindInfoForExceptionHandlingOnly ()
void SetUnhandledExceptionCallback (v8::UnhandledExceptionCallback unhandled_exception_callback)
__declspec (dllexport) int CRASH_HANDLER_FUNCTION_NAME(PEXCEPTION_RECORD ExceptionRecord
void RegisterNonABICompliantCodeRange (void *start, size_t size_in_bytes)
void UnregisterNonABICompliantCodeRange (void *start)
Variables
v8::UnhandledExceptionCallback unhandled_exception_callback_g = nullptr
ULONG64 EstablisherFrame
ULONG64 PCONTEXT ContextRecord
ULONG64 PCONTEXT PDISPATCHER_CONTEXT DispatcherContext
Function Documentation
__declspec()
v8::internal::win64_unwindinfo::__declspec (dllexport)
CanEmitUnwindInfoForBuiltins()
bool v8::internal::win64_unwindinfo::CanEmitUnwindInfoForBuiltins ()
Definition at line 28 of file unwinding-info-win64.cc.
{ return v8_flags.win64_unwinding_info; }
References v8::internal::v8_flags.
Referenced by v8::internal::PlatformEmbeddedFileWriterWin::MaybeEmitUnwindData().
CanRegisterUnwindInfoForNonABICompliantCodeRange()
bool v8::internal::win64_unwindinfo::CanRegisterUnwindInfoForNonABICompliantCodeRange ()
Definition at line 30 of file unwinding-info-win64.cc.
                                                        {
  return !v8_flags.jitless;
}
References v8::internal::v8_flags.
Referenced by v8::internal::CodeRange::Free(), v8::internal::wasm::WasmCodeManager::FreeNativeModule(), v8::internal::wasm::WasmCodeAllocator::InitializeCodeRange(), v8::internal::CodeRange::InitReservation(), RegisterNonABICompliantCodeRange(), RegisterUnwindInfoForExceptionHandlingOnly(), and UnregisterNonABICompliantCodeRange().
RegisterNonABICompliantCodeRange()
void v8::internal::win64_unwindinfo::RegisterNonABICompliantCodeRange (void * start, size_t size_in_bytes)
Definition at line 525 of file unwinding-info-win64.cc.
                                                                         {
  DCHECK(CanRegisterUnwindInfoForNonABICompliantCodeRange());
  // When the --win64-unwinding-info flag is set, we call
  // RtlAddGrowableFunctionTable to register unwinding info for the whole code
  // range of an isolate or Wasm module. This enables the Windows OS stack
  // unwinder to work correctly with V8-generated code, enabling stack walking
  // in Windows debuggers and performance tools. However, the
  // RtlAddGrowableFunctionTable API is only supported on Windows 8 and above.
  //
  // On Windows 7, or when --win64-unwinding-info is not set, we may still need
  // to call RtlAddFunctionTable to register a custom exception handler passed
  // by the embedder (like Crashpad).
  if (RegisterUnwindInfoForExceptionHandlingOnly()) {
#if defined(V8_OS_WIN_X64)
    // Windows ARM64 starts since 1709 Windows build, no need to have exception
    // handling only unwind info for compatibility.
    if (unhandled_exception_callback_g) {
      ExceptionHandlerRecord* record = new (start) ExceptionHandlerRecord();
      InitUnwindingRecord(record, size_in_bytes);
      CHECK(::RtlAddFunctionTable(record->runtime_function,
                                  kDefaultRuntimeFunctionCount,
                                  reinterpret_cast<DWORD64>(start)));
      // Protect reserved page against modifications.
      DWORD old_protect;
      CHECK(VirtualProtect(start, sizeof(ExceptionHandlerRecord),
                           PAGE_EXECUTE_READ, &old_protect));
    }
#endif // V8_OS_WIN_X64
  } else {
    CodeRangeUnwindingRecord* record = new (start) CodeRangeUnwindingRecord();
    InitUnwindingRecord(record, size_in_bytes);
    CHECK(AddGrowableFunctionTable(
        &record->dynamic_table, record->runtime_function,
        record->runtime_function_count, record->runtime_function_count,
        reinterpret_cast<DWORD64>(start),
        reinterpret_cast<DWORD64>(reinterpret_cast<uint8_t*>(start) +
                                  size_in_bytes)));
    // Protect reserved page against modifications.
    DWORD old_protect;
    CHECK(VirtualProtect(start, sizeof(CodeRangeUnwindingRecord),
                         PAGE_EXECUTE_READ, &old_protect));
  }
}
References v8::internal::win64_unwindinfo::anonymous_namespace{unwinding-info-win64.cc}::AddGrowableFunctionTable(), CanRegisterUnwindInfoForNonABICompliantCodeRange(), CHECK, v8::internal::DCHECK(), RegisterUnwindInfoForExceptionHandlingOnly(), and unhandled_exception_callback_g.
Referenced by v8::internal::wasm::WasmCodeAllocator::InitializeCodeRange(), and v8::internal::CodeRange::InitReservation().
RegisterUnwindInfoForExceptionHandlingOnly()
bool v8::internal::win64_unwindinfo::RegisterUnwindInfoForExceptionHandlingOnly ()
Definition at line 34 of file unwinding-info-win64.cc.
                                                  {
  DCHECK(CanRegisterUnwindInfoForNonABICompliantCodeRange());
#if defined(V8_OS_WIN_ARM64)
  return !v8_flags.win64_unwinding_info;
#else
  return !IsWindows8OrGreater() || !v8_flags.win64_unwinding_info;
#endif
}
References CanRegisterUnwindInfoForNonABICompliantCodeRange(), v8::internal::DCHECK(), and v8::internal::v8_flags.
Referenced by RegisterNonABICompliantCodeRange(), and UnregisterNonABICompliantCodeRange().
SetUnhandledExceptionCallback()
void v8::internal::win64_unwindinfo::SetUnhandledExceptionCallback (v8::UnhandledExceptionCallback unhandled_exception_callback)
Definition at line 45 of file unwinding-info-win64.cc.
                                                               {
  unhandled_exception_callback_g = unhandled_exception_callback;
}
References unhandled_exception_callback_g.
UnregisterNonABICompliantCodeRange()
void v8::internal::win64_unwindinfo::UnregisterNonABICompliantCodeRange (void * start)
Definition at line 575 of file unwinding-info-win64.cc.
                                                     {
  DCHECK(CanRegisterUnwindInfoForNonABICompliantCodeRange());
  if (RegisterUnwindInfoForExceptionHandlingOnly()) {
#if defined(V8_OS_WIN_X64)
    // Windows ARM64 starts since 1709 Windows build, no need to have exception
    // handling only unwind info for compatibility.
    if (unhandled_exception_callback_g) {
      ExceptionHandlerRecord* record =
          reinterpret_cast<ExceptionHandlerRecord*>(start);
      CHECK(::RtlDeleteFunctionTable(record->runtime_function));
      // Unprotect reserved page.
      DWORD old_protect;
      CHECK(VirtualProtect(start, sizeof(ExceptionHandlerRecord),
                           PAGE_READWRITE, &old_protect));
    }
#endif // V8_OS_WIN_X64
  } else {
    CodeRangeUnwindingRecord* record =
        reinterpret_cast<CodeRangeUnwindingRecord*>(start);
    if (record->dynamic_table) {
      DeleteGrowableFunctionTable(record->dynamic_table);
    }
    // Unprotect reserved page.
    DWORD old_protect;
    CHECK(VirtualProtect(start, sizeof(CodeRangeUnwindingRecord),
                         PAGE_READWRITE, &old_protect));
  }
}
References CanRegisterUnwindInfoForNonABICompliantCodeRange(), CHECK, v8::internal::DCHECK(), v8::internal::win64_unwindinfo::anonymous_namespace{unwinding-info-win64.cc}::DeleteGrowableFunctionTable(), RegisterUnwindInfoForExceptionHandlingOnly(), and unhandled_exception_callback_g.
Referenced by v8::internal::CodeRange::Free(), and v8::internal::wasm::WasmCodeManager::FreeNativeModule().
Variable Documentation
ContextRecord
ULONG64 PCONTEXT v8::internal::win64_unwindinfo::ContextRecord
Definition at line 56 of file unwinding-info-win64.cc.
DispatcherContext
ULONG64 PCONTEXT PDISPATCHER_CONTEXT v8::internal::win64_unwindinfo::DispatcherContext
Initial value:
{
  if (unhandled_exception_callback_g != nullptr) {
    EXCEPTION_POINTERS info = {ExceptionRecord, ContextRecord};
    return unhandled_exception_callback_g(&info);
  }
  return ExceptionContinueSearch
Definition at line 56 of file unwinding-info-win64.cc.
EstablisherFrame
ULONG64 v8::internal::win64_unwindinfo::EstablisherFrame
Definition at line 55 of file unwinding-info-win64.cc.
unhandled_exception_callback_g
v8::UnhandledExceptionCallback v8::internal::win64_unwindinfo::unhandled_exception_callback_g = nullptr
Definition at line 43 of file unwinding-info-win64.cc.
Referenced by RegisterNonABICompliantCodeRange(), SetUnhandledExceptionCallback(), and UnregisterNonABICompliantCodeRange().