v8::internal::anonymous_namespace{json-parser.cc} Namespace Reference
Typedefs
using EscapeKindField = base::BitField8< EscapeKind, 0, 3 >
using MayTerminateStringField = EscapeKindField::Next< bool, 1 >
using NumberPartField = MayTerminateStringField::Next< bool, 1 >
Enumerations
enum class EscapeKind : uint8_t {
kIllegal
, kSelf
, kBackspace
, kTab
,
kNewLine
, kFormFeed
, kCarriageReturn
, kUnicode
 }
Functions
constexpr JsonToken GetOneCharJsonToken (uint8_t c)
constexpr bool MayTerminateJsonString (uint8_t flags)
constexpr EscapeKind GetEscapeKind (uint8_t flags)
constexpr bool IsNumberPart (uint8_t flags)
constexpr uint8_t GetJsonScanFlags (uint8_t c)
template<typename Char >
JsonToken GetTokenForCharacter (Char c)
const uint8_t * GetFastKeyChars (Isolate *isolate, Tagged< String > key, Tagged< Map > map, const DisallowGarbageCollection &no_gc)
template<typename Char >
bool Matches (base::Vector< const Char > chars, DirectHandle< String > string)
Variables
static constexpr const JsonToken one_char_json_tokens [256]
static constexpr const uint8_t character_json_scan_flags [256]
Typedef Documentation
EscapeKindField
using v8::internal::anonymous_namespace{json-parser.cc}::EscapeKindField = typedef base::BitField8<EscapeKind, 0, 3>
Definition at line 81 of file json-parser.cc.
MayTerminateStringField
using v8::internal::anonymous_namespace{json-parser.cc}::MayTerminateStringField = typedef EscapeKindField::Next<bool, 1>
Definition at line 82 of file json-parser.cc.
NumberPartField
using v8::internal::anonymous_namespace{json-parser.cc}::NumberPartField = typedef MayTerminateStringField::Next<bool, 1>
Definition at line 83 of file json-parser.cc.
Enumeration Type Documentation
EscapeKind
enum v8::internal::anonymous_namespace{json-parser.cc}::EscapeKind : uint8_t [strong]
Enumerator
kIllegal
kSelf
kBackspace
kTab
kNewLine
kFormFeed
kCarriageReturn
kUnicode
Definition at line 70 of file json-parser.cc.
                      : uint8_t {
  kIllegal,
  kSelf,
  kBackspace,
  kTab,
  kNewLine,
  kFormFeed,
  kCarriageReturn,
  kUnicode
};
Function Documentation
GetEscapeKind()
constexpr EscapeKind v8::internal::anonymous_namespace{json-parser.cc}::GetEscapeKind (uint8_t flags) [constexpr]
Definition at line 89 of file json-parser.cc.
                                                  {
  return EscapeKindField::decode(flags);
}
References v8::internal::flags.
Referenced by v8::internal::JsonParser< Char >::DecodeString(), and v8::internal::JsonParser< Char >::ScanJsonString().
GetFastKeyChars()
const uint8_t* v8::internal::anonymous_namespace{json-parser.cc}::GetFastKeyChars (Isolate * isolate, Tagged< String > key, Tagged< Map > map, const DisallowGarbageCollection & no_gc)
Definition at line 1498 of file json-parser.cc.
                                                                       {
  DCHECK(InstanceTypeChecker::IsOneByteString(map));
#if V8_STATIC_ROOTS_BOOL
  ReadOnlyRoots roots(isolate);
  if (map == roots.internalized_one_byte_string_map()) {
    return Cast<SeqOneByteString>(key)->GetChars(no_gc);
  } else {
    DCHECK(map == roots.external_internalized_one_byte_string_map() ||
           map == roots.uncached_external_internalized_one_byte_string_map());
    return Cast<ExternalOneByteString>(key)->GetChars();
  }
#else
  InstanceType instance_type = map->instance_type();
  switch (instance_type) {
    case INTERNALIZED_ONE_BYTE_STRING_TYPE:
      return Cast<SeqOneByteString>(key)->GetChars(no_gc);
    case EXTERNAL_INTERNALIZED_ONE_BYTE_STRING_TYPE:
    case UNCACHED_EXTERNAL_INTERNALIZED_ONE_BYTE_STRING_TYPE:
      return Cast<ExternalOneByteString>(key)->GetChars();
    default:
      UNREACHABLE();
  }
#endif
}
References v8::internal::DCHECK(), v8::internal::EXTERNAL_INTERNALIZED_ONE_BYTE_STRING_TYPE, v8::internal::INTERNALIZED_ONE_BYTE_STRING_TYPE, v8::internal::InstanceTypeChecker::IsOneByteString(), v8::internal::key, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::UNCACHED_EXTERNAL_INTERNALIZED_ONE_BYTE_STRING_TYPE, and v8::internal::UNREACHABLE().
Referenced by v8::internal::JsonParser< Char >::ParseJsonObjectProperties().
GetJsonScanFlags()
constexpr uint8_t v8::internal::anonymous_namespace{json-parser.cc}::GetJsonScanFlags (uint8_t c) [constexpr]
Definition at line 97 of file json-parser.cc.
                                              {
  // clang-format off
  return (c == 'b' ? EscapeKindField::encode(EscapeKind::kBackspace)
          : c == 't' ? EscapeKindField::encode(EscapeKind::kTab)
          : c == 'n' ? EscapeKindField::encode(EscapeKind::kNewLine)
          : c == 'f' ? EscapeKindField::encode(EscapeKind::kFormFeed)
          : c == 'r' ? EscapeKindField::encode(EscapeKind::kCarriageReturn)
          : c == 'u' ? EscapeKindField::encode(EscapeKind::kUnicode)
          : c == '"' ? EscapeKindField::encode(EscapeKind::kSelf)
          : c == '\\' ? EscapeKindField::encode(EscapeKind::kSelf)
          : c == '/' ? EscapeKindField::encode(EscapeKind::kSelf)
          : EscapeKindField::encode(EscapeKind::kIllegal)) |
         (c < 0x20 ? MayTerminateStringField::encode(true)
          : c == '"' ? MayTerminateStringField::encode(true)
          : c == '\\' ? MayTerminateStringField::encode(true)
          : MayTerminateStringField::encode(false)) |
         NumberPartField::encode(c == '.' ||
                                 c == 'e' ||
                                 c == 'E' ||
                                 IsDecimalDigit(c) ||
                                 c == '-' ||
                                 c == '+');
  // clang-format on
}
References v8::internal::IsDecimalDigit().
GetOneCharJsonToken()
constexpr JsonToken v8::internal::anonymous_namespace{json-parser.cc}::GetOneCharJsonToken (uint8_t c) [constexpr]
Definition at line 37 of file json-parser.cc.
                                                   {
  // clang-format off
  return
     c == '"' ? JsonToken::STRING :
     IsDecimalDigit(c) ? JsonToken::NUMBER :
     c == '-' ? JsonToken::NUMBER :
     c == '[' ? JsonToken::LBRACK :
     c == '{' ? JsonToken::LBRACE :
     c == ']' ? JsonToken::RBRACK :
     c == '}' ? JsonToken::RBRACE :
     c == 't' ? JsonToken::TRUE_LITERAL :
     c == 'f' ? JsonToken::FALSE_LITERAL :
     c == 'n' ? JsonToken::NULL_LITERAL :
     c == ' ' ? JsonToken::WHITESPACE :
     c == '\t' ? JsonToken::WHITESPACE :
     c == '\r' ? JsonToken::WHITESPACE :
     c == '\n' ? JsonToken::WHITESPACE :
     c == ':' ? JsonToken::COLON :
     c == ',' ? JsonToken::COMMA :
     JsonToken::ILLEGAL;
  // clang-format on
}
References v8::internal::COLON, v8::internal::COMMA, v8::internal::FALSE_LITERAL, v8::internal::ILLEGAL, v8::internal::IsDecimalDigit(), v8::internal::LBRACE, v8::internal::LBRACK, v8::internal::NULL_LITERAL, v8::internal::NUMBER, v8::internal::RBRACE, v8::internal::RBRACK, v8::internal::STRING, v8::internal::TRUE_LITERAL, and v8::internal::WHITESPACE.
GetTokenForCharacter()
template<typename Char >
JsonToken v8::internal::anonymous_namespace{json-parser.cc}::GetTokenForCharacter (Char c)
Definition at line 559 of file json-parser.cc.
                                       {
  return V8_LIKELY(c <= unibrow::Latin1::kMaxChar) ? one_char_json_tokens[c]
                                                   : JsonToken::ILLEGAL;
}
References v8::internal::ILLEGAL, unibrow::Latin1::kMaxChar, one_char_json_tokens, and V8_LIKELY.
Referenced by v8::internal::JsonParser< Char >::ParseRawJson(), and v8::internal::JsonParser< Char >::SkipWhitespace().
IsNumberPart()
constexpr bool v8::internal::anonymous_namespace{json-parser.cc}::IsNumberPart (uint8_t flags) [constexpr]
Definition at line 93 of file json-parser.cc.
                                           {
  return NumberPartField::decode(flags);
}
References v8::internal::flags.
Referenced by v8::internal::JsonParser< Char >::ParseJsonNumberAsDoubleOrSmi().
Matches()
template<typename Char >
bool v8::internal::anonymous_namespace{json-parser.cc}::Matches (base::Vector< const Char > chars, DirectHandle< String > string)
Definition at line 2284 of file json-parser.cc.
                                                                        {
  DCHECK(!string.is_null());
  return string->IsEqualTo(chars);
}
References v8::internal::DCHECK().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::ExtendingLoadMatcher::base(), v8::internal::compiler::ExtendingLoadMatcher::base(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TestAndBranchMatcherTurboshaft::bit(), v8::internal::JsonParser< Char >::DecodeString(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::ExtendingLoadMatcher::immediate(), v8::internal::compiler::ExtendingLoadMatcher::immediate(), v8::internal::JsonParser< Char >::MakeString(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::ExtendingLoadMatcher::opcode(), and v8::internal::compiler::ExtendingLoadMatcher::opcode().
MayTerminateJsonString()
constexpr bool v8::internal::anonymous_namespace{json-parser.cc}::MayTerminateJsonString (uint8_t flags) [constexpr]
Definition at line 85 of file json-parser.cc.
                                                     {
  return MayTerminateStringField::decode(flags);
}
References v8::internal::flags.
Referenced by v8::internal::JsonParser< Char >::ScanJsonString().
Variable Documentation
character_json_scan_flags
constexpr const uint8_t v8::internal::anonymous_namespace{json-parser.cc}::character_json_scan_flags[256] [static], [constexpr]
Initial value:
= {
#define CALL_GET_SCAN_FLAGS(N)
#define CALL_GET_SCAN_FLAGS(N)
}
Definition at line 123 of file json-parser.cc.
Referenced by v8::internal::JsonParser< Char >::DecodeString(), v8::internal::JsonParser< Char >::ParseJsonNumberAsDoubleOrSmi(), and v8::internal::JsonParser< Char >::ScanJsonString().
one_char_json_tokens
constexpr const JsonToken v8::internal::anonymous_namespace{json-parser.cc}::one_char_json_tokens[256] [static], [constexpr]
Initial value:
= {
#define CALL_GET_SCAN_FLAGS(N)
#define CALL_GET_SCAN_FLAGS(N)
}
Definition at line 61 of file json-parser.cc.
Referenced by GetTokenForCharacter(), and v8::internal::JsonParser< Char >::ReportUnexpectedCharacter().