v8::internal::anonymous_namespace{assert-scope.cc} Namespace Reference
Functions
thread_local PerThreadAsserts current_per_thread_assert_data (kInitialValue)
Variables
constexpr PerThreadAsserts kInitialValue
constexpr PerThreadAsserts kClearedValue = PerThreadAsserts{}
Function Documentation
current_per_thread_assert_data()
thread_local PerThreadAsserts v8::internal::anonymous_namespace{assert-scope.cc}::current_per_thread_assert_data (kInitialValue)
Referenced by v8::internal::PerThreadAssertScope< kAllow, kTypes >::IsAllowed(), v8::internal::PerThreadAssertScope< kAllow, kTypes >::PerThreadAssertScope(), and v8::internal::PerThreadAssertScope< kAllow, kTypes >::Release().
Variable Documentation
kClearedValue
constexpr PerThreadAsserts v8::internal::anonymous_namespace{assert-scope.cc}::kClearedValue = PerThreadAsserts{} [constexpr]
Definition at line 23 of file assert-scope.cc.
Referenced by v8::internal::PerThreadAssertScope< kAllow, kTypes >::Release().
kInitialValue
constexpr PerThreadAsserts v8::internal::anonymous_namespace{assert-scope.cc}::kInitialValue [constexpr]
Initial value:
=
    ~PerThreadAsserts{HANDLE_USAGE_ON_ALL_THREADS_ASSERT}
Definition at line 17 of file assert-scope.cc.
Referenced by v8::internal::maglev::ValueNode::GetStaticType(), and v8::internal::maglev::KnownNodeAspects::UpdateMayHaveAliasingContexts().