v8::base::anonymous_namespace{platform-cygwin.cc} Namespace Reference
Functions
DWORD GetProtectionFromMemoryPermission (OS::MemoryPermission access)
uint8_t * RandomizedVirtualAlloc (size_t size, DWORD flags, DWORD protect, void *hint)
Function Documentation
GetProtectionFromMemoryPermission()
DWORD v8::base::anonymous_namespace{platform-cygwin.cc}::GetProtectionFromMemoryPermission (OS::MemoryPermission access)
Definition at line 33 of file platform-cygwin.cc.
                                                                   {
  switch (access) {
    case OS::MemoryPermission::kNoAccess:
    case OS::MemoryPermission::kNoAccessWillJitLater:
      return PAGE_NOACCESS;
    case OS::MemoryPermission::kRead:
      return PAGE_READONLY;
    case OS::MemoryPermission::kReadWrite:
      return PAGE_READWRITE;
    case OS::MemoryPermission::kReadWriteExecute:
      return PAGE_EXECUTE_READWRITE;
    case OS::MemoryPermission::kReadExecute:
      return PAGE_EXECUTE_READ;
  }
  UNREACHABLE();
}
References v8::base::OS::kNoAccess, v8::base::OS::kNoAccessWillJitLater, v8::base::OS::kRead, v8::base::OS::kReadExecute, v8::base::OS::kReadWrite, v8::base::OS::kReadWriteExecute, and UNREACHABLE.
RandomizedVirtualAlloc()
uint8_t* v8::base::anonymous_namespace{platform-cygwin.cc}::RandomizedVirtualAlloc (size_t size, DWORD flags, DWORD protect, void * hint)
Definition at line 50 of file platform-cygwin.cc.
                                            {
  LPVOID base = nullptr;
  // For executable or reserved pages try to use the address hint.
  if (protect != PAGE_READWRITE) {
    base = VirtualAlloc(hint, size, flags, protect);
  }
  // If that fails, let the OS find an address to use.
  if (base == nullptr) {
    base = VirtualAlloc(nullptr, size, flags, protect);
  }
  return reinterpret_cast<uint8_t*>(base);
}
References flags(), and size().
Referenced by v8::base::OS::Allocate().