v8::internal::compiler::anonymous_namespace{wasm-gc-lowering.cc} Namespace Reference
Functions
int TaggedOffset (FieldAccess access)
Variables
constexpr int32_t kInt31MaxValue = 0x3fffffff
constexpr int32_t kInt31MinValue = -kInt31MaxValue - 1
Function Documentation
TaggedOffset()
int v8::internal::compiler::anonymous_namespace{wasm-gc-lowering.cc}::TaggedOffset (FieldAccess access)
Definition at line 29 of file wasm-gc-lowering.cc.
                                     {
  DCHECK(access.base_is_tagged);
  return wasm::ObjectAccess::ToTagged(access.offset);
}
References v8::internal::compiler::FieldAccess::base_is_tagged, v8::internal::DCHECK(), v8::internal::compiler::FieldAccess::offset, and v8::internal::wasm::ObjectAccess::ToTagged().
Referenced by v8::internal::compiler::WasmGCLowering::ReduceStringPrepareForGetCodeunit().
Variable Documentation
kInt31MaxValue
constexpr int32_t v8::internal::compiler::anonymous_namespace{wasm-gc-lowering.cc}::kInt31MaxValue = 0x3fffffff [constexpr]
Definition at line 555 of file wasm-gc-lowering.cc.
Referenced by v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::AnyConvertExtern(), and v8::internal::compiler::WasmGCLowering::ReduceWasmAnyConvertExtern().
kInt31MinValue
constexpr int32_t v8::internal::compiler::anonymous_namespace{wasm-gc-lowering.cc}::kInt31MinValue = -kInt31MaxValue - 1 [constexpr]
Definition at line 556 of file wasm-gc-lowering.cc.
Referenced by v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::AnyConvertExtern(), and v8::internal::compiler::WasmGCLowering::ReduceWasmAnyConvertExtern().