v8::api_internal Namespace Reference
Classes
class StackAllocated
class StackAllocated< true >
class IndirectHandleBase
A base class for abstract handles containing indirect pointers.
Functions
i::Address * GlobalizeReference (i::Isolate *i_isolate, i::Address value)
i::Address * CopyGlobalReference (i::Address *from)
void MoveGlobalReference (internal::Address **from, internal::Address **to)
void MakeWeak (i::Address *location, void *parameter, WeakCallbackInfo< void >::Callback weak_callback, WeakCallbackType type)
void MakeWeak (i::Address **location_addr)
void * ClearWeak (i::Address *location)
void AnnotateStrongRetainer (i::Address *location, const char *label)
void DisposeGlobal (i::Address *location)
i::Address * Eternalize (Isolate *v8_isolate, Value *value)
void FromJustIsNothing ()
void ToLocalEmpty ()
void InternalFieldOutOfBounds (int index)
i::Address ConvertToJSGlobalProxyIfNecessary (i::Address holder_ptr)
v8::Local< v8::Value > GetFunctionTemplateData (v8::Isolate *isolate, v8::Local< v8::Data > raw_target)
Function Documentation
AnnotateStrongRetainer()
void v8::api_internal::AnnotateStrongRetainer (i::Address * location, const char * label)
Definition at line 667 of file api.cc.
                                                                   {
  i::GlobalHandles::AnnotateStrongRetainer(location, label);
}
References v8::internal::GlobalHandles::AnnotateStrongRetainer().
Referenced by v8::PersistentBase< T >::AnnotateStrongRetainer().
ClearWeak()
void * v8::api_internal::ClearWeak (i::Address * location)
Definition at line 663 of file api.cc.
                                    {
  return i::GlobalHandles::ClearWeakness(location);
}
References v8::internal::GlobalHandles::ClearWeakness().
Referenced by v8::PersistentBase< T >::ClearWeak().
ConvertToJSGlobalProxyIfNecessary()
internal::Address v8::api_internal::ConvertToJSGlobalProxyIfNecessary (i::Address holder_ptr)
Definition at line 3831 of file api.cc.
                                                                {
  i::Tagged<i::HeapObject> holder =
      i::Cast<i::HeapObject>(i::Tagged<i::Object>(holder_ptr));
  if (i::IsJSGlobalObject(holder)) {
    return i::Cast<i::JSGlobalObject>(holder)->global_proxy().ptr();
  }
  return holder_ptr;
}
Referenced by v8::PropertyCallbackInfo< T >::HolderV2().
CopyGlobalReference()
internal::Address * v8::api_internal::CopyGlobalReference (i::Address * from)
Definition at line 644 of file api.cc.
                                              {
  i::IndirectHandle<i::Object> result = i::GlobalHandles::CopyGlobal(from);
  return result.location();
}
References v8::internal::GlobalHandles::CopyGlobal(), and v8::base::internal::result.
Referenced by v8::Persistent< T, M >::Copy().
DisposeGlobal()
void v8::api_internal::DisposeGlobal (i::Address * location)
Definition at line 671 of file api.cc.
                                       {
  i::GlobalHandles::Destroy(location);
}
References v8::internal::GlobalHandles::Destroy().
Referenced by v8::PersistentBase< T >::Reset().
Eternalize()
internal::Address * v8::api_internal::Eternalize (Isolate * v8_isolate, Value * value)
Definition at line 675 of file api.cc.
                                                        {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  i::Tagged<i::Object> object = *Utils::OpenDirectHandle(value);
  int index = -1;
  i_isolate->eternal_handles()->Create(i_isolate, object, &index);
  return i_isolate->eternal_handles()->Get(index).location();
}
References v8::internal::EternalHandles::Create(), v8::internal::Isolate::eternal_handles(), v8::internal::EternalHandles::Get(), v8::internal::index, v8::Utils::OpenDirectHandle(), and v8::internal::value.
Referenced by v8::Eternal< T >::requires().
FromJustIsNothing()
void v8::api_internal::FromJustIsNothing ()
Definition at line 683 of file api.cc.
                         {
  Utils::ApiCheck(false, "v8::FromJust", "Maybe value is Nothing");
}
References v8::Utils::ApiCheck().
Referenced by v8::Maybe< T >::Check(), and v8::Maybe< T >::FromJust().
GetFunctionTemplateData()
v8::Local< v8::Value > v8::api_internal::GetFunctionTemplateData (v8::Isolate * isolate, v8::Local< v8::Data > raw_target)
Definition at line 11899 of file api.cc.
                                                    {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(isolate);
  i::DirectHandle<i::Object> target = Utils::OpenDirectHandle(*raw_target);
  if (i::IsFunctionTemplateInfo(*target)) {
    i::DirectHandle<i::Object> data(
        i::Cast<i::FunctionTemplateInfo>(*target)->callback_data(kAcquireLoad),
        i_isolate);
    return Utils::ToLocal(data);
  } else if (i::IsJSFunction(*target)) {
    i::DirectHandle<i::JSFunction> target_func = i::Cast<i::JSFunction>(target);
    auto shared = target_func->shared();
    if (shared->IsApiFunction()) {
      i::DirectHandle<i::Object> data(
          shared->api_func_data()->callback_data(kAcquireLoad), i_isolate);
      return Utils::ToLocal(data);
    }
  }
  Utils::ApiCheck(false, "api_internal::GetFunctionTemplateData",
                  "Target function is not an Api function");
  UNREACHABLE();
}
References v8::Utils::ApiCheck(), v8::kAcquireLoad, v8::Utils::OpenDirectHandle(), and UNREACHABLE.
Referenced by v8::FunctionCallbackInfo< T >::Data().
GlobalizeReference()
internal::Address * v8::api_internal::GlobalizeReference (i::Isolate * i_isolate, i::Address value)
Definition at line 632 of file api.cc.
                                                                  {
  ApiRuntimeCallStatsScope rcs_scope(i_isolate, RCCId::kAPI_Persistent_New);
  i::IndirectHandle<i::Object> result =
      i_isolate->global_handles()->Create(value);
#ifdef VERIFY_HEAP
  if (i::v8_flags.verify_heap) {
    i::Object::ObjectVerify(i::Tagged<i::Object>(value), i_isolate);
  }
#endif // VERIFY_HEAP
  return result.location();
}
References v8::internal::GlobalHandles::Create(), v8::internal::Isolate::global_handles(), v8::base::internal::result, v8::internal::v8_flags, and v8::internal::value.
Referenced by v8::PersistentBase< T >::New().
InternalFieldOutOfBounds()
void v8::api_internal::InternalFieldOutOfBounds (int index)
Definition at line 691 of file api.cc.
                                         {
  Utils::ApiCheck(0 <= index && index < kInternalFieldsInWeakCallback,
                  "WeakCallbackInfo::GetInternalField",
                  "Internal field out of bounds");
}
References v8::Utils::ApiCheck(), v8::internal::index, and v8::kInternalFieldsInWeakCallback.
Referenced by v8::WeakCallbackInfo< T >::GetInternalField().
MakeWeak() [1/2]
void v8::api_internal::MakeWeak (i::Address ** location_addr)
Definition at line 659 of file api.cc.
                                        {
  i::GlobalHandles::MakeWeak(location_addr);
}
References v8::internal::GlobalHandles::MakeWeak().
MakeWeak() [2/2]
void v8::api_internal::MakeWeak (i::Address * location, void * parameter, WeakCallbackInfo< void >::Callback weak_callback, WeakCallbackType type)
Definition at line 653 of file api.cc.
                                     {
  i::GlobalHandles::MakeWeak(location, parameter, weak_callback, type);
}
References v8::internal::GlobalHandles::MakeWeak(), and v8::internal::tracing::type.
Referenced by v8::internal::MarkCompactCollector::ClearPotentialSimpleMapTransition(), v8::PersistentBase< T >::SetWeak(), v8::internal::CodeStubAssembler::StoreWeakReferenceInFeedbackVector(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryMapDescriptorMapImpl().
MoveGlobalReference()
void v8::api_internal::MoveGlobalReference (internal::Address ** from, internal::Address ** to)
Definition at line 649 of file api.cc.
                                                                       {
  i::GlobalHandles::MoveGlobal(from, to);
}
References v8::internal::GlobalHandles::MoveGlobal().
Referenced by v8::Global< T >::Global(), and v8::Global< T >::operator=().
ToLocalEmpty()
void v8::api_internal::ToLocalEmpty ()
Definition at line 687 of file api.cc.
                    {
  Utils::ApiCheck(false, "v8::ToLocalChecked", "Empty MaybeLocal");
}
References v8::Utils::ApiCheck().
Referenced by v8::MaybeLocal< T >::ToLocalChecked().