v8::internal::anonymous_namespace{regexp-compiler-tonode.cc} Namespace Reference
Classes
class ModifiersScope
class AssertionSequenceRewriter
class RegExpExpansionLimiter
Typedefs
using UC16Range = uint32_t
Functions
bool CompareInverseRanges (ZoneList< CharacterRange > *ranges, const int *special_class, int length)
bool CompareRanges (ZoneList< CharacterRange > *ranges, const int *special_class, int length)
ZoneList< CharacterRange > * ToCanonicalZoneList (const UnicodeRangeSplitter::CharacterRangeVector *v, Zone *zone)
void AddBmpCharacters (RegExpCompiler *compiler, ChoiceNode *result, RegExpNode *on_success, UnicodeRangeSplitter *splitter)
constexpr UC16Range ToUC16Range (base::uc16 from, base::uc16 to)
constexpr base::uc16 ExtractFrom (UC16Range r)
constexpr base::uc16 ExtractTo (UC16Range r)
void AddNonBmpSurrogatePairs (RegExpCompiler *compiler, ChoiceNode *result, RegExpNode *on_success, UnicodeRangeSplitter *splitter)
RegExpNode * NegativeLookaroundAgainstReadDirectionAndMatch (RegExpCompiler *compiler, ZoneList< CharacterRange > *lookbehind, ZoneList< CharacterRange > *match, RegExpNode *on_success, bool read_backward)
RegExpNode * MatchAndNegativeLookaroundInReadDirection (RegExpCompiler *compiler, ZoneList< CharacterRange > *match, ZoneList< CharacterRange > *lookahead, RegExpNode *on_success, bool read_backward)
void AddLoneLeadSurrogates (RegExpCompiler *compiler, ChoiceNode *result, RegExpNode *on_success, UnicodeRangeSplitter *splitter)
void AddLoneTrailSurrogates (RegExpCompiler *compiler, ChoiceNode *result, RegExpNode *on_success, UnicodeRangeSplitter *splitter)
RegExpNode * UnanchoredAdvance (RegExpCompiler *compiler, RegExpNode *on_success)
bool StartsWithAtom (RegExpTree *tree)
RegExpAtom * FirstAtom (RegExpTree *tree)
int CompareFirstChar (RegExpTree *const *a, RegExpTree *const *b)
unibrow::uchar Canonical (unibrow::Mapping< unibrow::Ecma262Canonicalize > *canonicalize, unibrow::uchar c)
int CompareCaseInsensitive (unibrow::Mapping< unibrow::Ecma262Canonicalize > *canonicalize, unibrow::uchar a, unibrow::uchar b)
int CompareFirstCharCaseInsensitive (unibrow::Mapping< unibrow::Ecma262Canonicalize > *canonicalize, RegExpTree *const *a, RegExpTree *const *b)
bool Equals (bool ignore_case, unibrow::Mapping< unibrow::Ecma262Canonicalize > *canonicalize, unibrow::uchar a, unibrow::uchar b)
bool CharAtEquals (bool ignore_case, unibrow::Mapping< unibrow::Ecma262Canonicalize > *canonicalize, int index, const RegExpAtom *a, const RegExpAtom *b)
RegExpNode * BoundaryAssertionAsLookaround (RegExpCompiler *compiler, RegExpNode *on_success, RegExpAssertion::Type type)
void AddClass (const int *elmv, int elmc, ZoneList< CharacterRange > *ranges, Zone *zone)
void AddClassNegated (const int *elmv, int elmc, ZoneList< CharacterRange > *ranges, Zone *zone)
void MoveRanges (ZoneList< CharacterRange > *list, int from, int to, int count)
int InsertRangeInCanonicalList (ZoneList< CharacterRange > *list, int count, CharacterRange insert)
void SafeAdvanceRange (const ZoneList< CharacterRange > *range, int *index, base::uc32 *from, base::uc32 *to)
Typedef Documentation
UC16Range
using v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::UC16Range = typedef uint32_t
Definition at line 217 of file regexp-compiler-tonode.cc.
Function Documentation
AddBmpCharacters()
void v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AddBmpCharacters (RegExpCompiler * compiler, ChoiceNode * result, RegExpNode * on_success, UnicodeRangeSplitter * splitter)
Definition at line 208 of file regexp-compiler-tonode.cc.
                                                                              {
  ZoneList<CharacterRange>* bmp =
      ToCanonicalZoneList(splitter->bmp(), compiler->zone());
  if (bmp == nullptr) return;
  result->AddAlternative(GuardedAlternative(TextNode::CreateForCharacterRanges(
      compiler->zone(), bmp, compiler->read_backward(), on_success)));
}
References v8::internal::UnicodeRangeSplitter::bmp(), v8::internal::TextNode::CreateForCharacterRanges(), v8::internal::RegExpCompiler::read_backward(), v8::base::internal::result, ToCanonicalZoneList(), and v8::internal::RegExpCompiler::zone().
AddClass()
void v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AddClass (const int * elmv, int elmc, ZoneList< CharacterRange > * ranges, Zone * zone)
Definition at line 1402 of file regexp-compiler-tonode.cc.
                          {
  elmc--;
  DCHECK_EQ(kRangeEndMarker, elmv[elmc]);
  for (int i = 0; i < elmc; i += 2) {
    DCHECK(elmv[i] < elmv[i + 1]);
    ranges->Add(CharacterRange::Range(elmv[i], elmv[i + 1] - 1), zone);
  }
}
References v8::internal::ZoneList< T >::Add(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::regexp_compiler_constants::kRangeEndMarker, and v8::internal::CharacterRange::Range().
Referenced by v8::internal::CharacterRange::AddClassEscape().
AddClassNegated()
void v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AddClassNegated (const int * elmv, int elmc, ZoneList< CharacterRange > * ranges, Zone * zone)
Definition at line 1412 of file regexp-compiler-tonode.cc.
                                                                   {
  elmc--;
  DCHECK_EQ(kRangeEndMarker, elmv[elmc]);
  DCHECK_NE(0x0000, elmv[0]);
  DCHECK_NE(kMaxCodePoint, elmv[elmc - 1]);
  base::uc16 last = 0x0000;
  for (int i = 0; i < elmc; i += 2) {
    DCHECK(last <= elmv[i] - 1);
    DCHECK(elmv[i] < elmv[i + 1]);
    ranges->Add(CharacterRange::Range(last, elmv[i] - 1), zone);
    last = elmv[i + 1];
  }
  ranges->Add(CharacterRange::Range(last, kMaxCodePoint), zone);
}
References v8::internal::ZoneList< T >::Add(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NE, v8::internal::kMaxCodePoint, v8::internal::regexp_compiler_constants::kRangeEndMarker, and v8::internal::CharacterRange::Range().
Referenced by v8::internal::CharacterRange::AddClassEscape().
AddLoneLeadSurrogates()
void v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AddLoneLeadSurrogates (RegExpCompiler * compiler, ChoiceNode * result, RegExpNode * on_success, UnicodeRangeSplitter * splitter)
Definition at line 357 of file regexp-compiler-tonode.cc.
                                                           {
  ZoneList<CharacterRange>* lead_surrogates =
      ToCanonicalZoneList(splitter->lead_surrogates(), compiler->zone());
  if (lead_surrogates == nullptr) return;
  Zone* zone = compiler->zone();
  // E.g. \ud801 becomes \ud801(?![\udc00-\udfff]).
  ZoneList<CharacterRange>* trail_surrogates = CharacterRange::List(
      zone, CharacterRange::Range(kTrailSurrogateStart, kTrailSurrogateEnd));
  RegExpNode* match;
  if (compiler->read_backward()) {
    // Reading backward. Assert that reading forward, there is no trail
    // surrogate, and then backward match the lead surrogate.
    match = NegativeLookaroundAgainstReadDirectionAndMatch(
        compiler, trail_surrogates, lead_surrogates, on_success, true);
  } else {
    // Reading forward. Forward match the lead surrogate and assert that
    // no trail surrogate follows.
    match = MatchAndNegativeLookaroundInReadDirection(
        compiler, lead_surrogates, trail_surrogates, on_success, false);
  }
  result->AddAlternative(GuardedAlternative(match));
}
References v8::internal::kTrailSurrogateEnd, v8::internal::kTrailSurrogateStart, v8::internal::UnicodeRangeSplitter::lead_surrogates(), v8::internal::CharacterRange::List(), MatchAndNegativeLookaroundInReadDirection(), NegativeLookaroundAgainstReadDirectionAndMatch(), v8::internal::CharacterRange::Range(), v8::internal::RegExpCompiler::read_backward(), v8::base::internal::result, ToCanonicalZoneList(), and v8::internal::RegExpCompiler::zone().
AddLoneTrailSurrogates()
void v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AddLoneTrailSurrogates (RegExpCompiler * compiler, ChoiceNode * result, RegExpNode * on_success, UnicodeRangeSplitter * splitter)
Definition at line 383 of file regexp-compiler-tonode.cc.
                                                            {
  ZoneList<CharacterRange>* trail_surrogates =
      ToCanonicalZoneList(splitter->trail_surrogates(), compiler->zone());
  if (trail_surrogates == nullptr) return;
  Zone* zone = compiler->zone();
  // E.g. \udc01 becomes (?<![\ud800-\udbff])\udc01
  ZoneList<CharacterRange>* lead_surrogates = CharacterRange::List(
      zone, CharacterRange::Range(kLeadSurrogateStart, kLeadSurrogateEnd));
  RegExpNode* match;
  if (compiler->read_backward()) {
    // Reading backward. Backward match the trail surrogate and assert that no
    // lead surrogate precedes it.
    match = MatchAndNegativeLookaroundInReadDirection(
        compiler, trail_surrogates, lead_surrogates, on_success, true);
  } else {
    // Reading forward. Assert that reading backward, there is no lead
    // surrogate, and then forward match the trail surrogate.
    match = NegativeLookaroundAgainstReadDirectionAndMatch(
        compiler, lead_surrogates, trail_surrogates, on_success, false);
  }
  result->AddAlternative(GuardedAlternative(match));
}
References v8::internal::kLeadSurrogateEnd, v8::internal::kLeadSurrogateStart, v8::internal::CharacterRange::List(), MatchAndNegativeLookaroundInReadDirection(), NegativeLookaroundAgainstReadDirectionAndMatch(), v8::internal::CharacterRange::Range(), v8::internal::RegExpCompiler::read_backward(), v8::base::internal::result, ToCanonicalZoneList(), v8::internal::UnicodeRangeSplitter::trail_surrogates(), and v8::internal::RegExpCompiler::zone().
AddNonBmpSurrogatePairs()
void v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AddNonBmpSurrogatePairs (RegExpCompiler * compiler, ChoiceNode * result, RegExpNode * on_success, UnicodeRangeSplitter * splitter)
Definition at line 228 of file regexp-compiler-tonode.cc.
                                                             {
  DCHECK(!compiler->one_byte());
  Zone* const zone = compiler->zone();
  ZoneList<CharacterRange>* non_bmp =
      ToCanonicalZoneList(splitter->non_bmp(), zone);
  if (non_bmp == nullptr) return;
  // Translate each 32-bit code point range into the corresponding 16-bit code
  // unit representation consisting of the lead- and trail surrogate.
  //
  // The generated alternatives are grouped by the leading surrogate to avoid
  // emitting excessive code. For example, for
  //
  // { \ud800[\udc00-\udc01]
  // , \ud800[\udc05-\udc06]
  // }
  //
  // there's no need to emit matching code for the leading surrogate \ud800
  // twice. We also create a dedicated grouping for full trailing ranges, i.e.
  // [dc00-dfff].
  ZoneUnorderedMap<UC16Range, ZoneList<CharacterRange>*> grouped_by_leading(
      zone);
  ZoneList<CharacterRange>* leading_with_full_trailing_range =
      zone->New<ZoneList<CharacterRange>>(1, zone);
  const auto AddRange = [&](base::uc16 from_l, base::uc16 to_l,
                            base::uc16 from_t, base::uc16 to_t) {
    const UC16Range leading_range = ToUC16Range(from_l, to_l);
    if (grouped_by_leading.count(leading_range) == 0) {
      if (from_t == kTrailSurrogateStart && to_t == kTrailSurrogateEnd) {
        leading_with_full_trailing_range->Add(
            CharacterRange::Range(from_l, to_l), zone);
        return;
      }
      grouped_by_leading[leading_range] =
          zone->New<ZoneList<CharacterRange>>(2, zone);
    }
    grouped_by_leading[leading_range]->Add(CharacterRange::Range(from_t, to_t),
                                           zone);
  };
  // First, create the grouped ranges.
  CharacterRange::Canonicalize(non_bmp);
  for (int i = 0; i < non_bmp->length(); i++) {
    // Match surrogate pair.
    // E.g. [\u10005-\u11005] becomes
    // \ud800[\udc05-\udfff]|
    // [\ud801-\ud803][\udc00-\udfff]|
    // \ud804[\udc00-\udc05]
    base::uc32 from = non_bmp->at(i).from();
    base::uc32 to = non_bmp->at(i).to();
    base::uc16 from_l = unibrow::Utf16::LeadSurrogate(from);
    base::uc16 from_t = unibrow::Utf16::TrailSurrogate(from);
    base::uc16 to_l = unibrow::Utf16::LeadSurrogate(to);
    base::uc16 to_t = unibrow::Utf16::TrailSurrogate(to);
    if (from_l == to_l) {
      // The lead surrogate is the same.
      AddRange(from_l, to_l, from_t, to_t);
      continue;
    }
    if (from_t != kTrailSurrogateStart) {
      // Add [from_l][from_t-\udfff].
      AddRange(from_l, from_l, from_t, kTrailSurrogateEnd);
      from_l++;
    }
    if (to_t != kTrailSurrogateEnd) {
      // Add [to_l][\udc00-to_t].
      AddRange(to_l, to_l, kTrailSurrogateStart, to_t);
      to_l--;
    }
    if (from_l <= to_l) {
      // Add [from_l-to_l][\udc00-\udfff].
      AddRange(from_l, to_l, kTrailSurrogateStart, kTrailSurrogateEnd);
    }
  }
  // Create the actual TextNode now that ranges are fully grouped.
  if (!leading_with_full_trailing_range->is_empty()) {
    CharacterRange::Canonicalize(leading_with_full_trailing_range);
    result->AddAlternative(GuardedAlternative(TextNode::CreateForSurrogatePair(
        zone, leading_with_full_trailing_range,
        CharacterRange::Range(kTrailSurrogateStart, kTrailSurrogateEnd),
        compiler->read_backward(), on_success)));
  }
  for (const auto& it : grouped_by_leading) {
    CharacterRange leading_range =
        CharacterRange::Range(ExtractFrom(it.first), ExtractTo(it.first));
    ZoneList<CharacterRange>* trailing_ranges = it.second;
    CharacterRange::Canonicalize(trailing_ranges);
    result->AddAlternative(GuardedAlternative(TextNode::CreateForSurrogatePair(
        zone, leading_range, trailing_ranges, compiler->read_backward(),
        on_success)));
  }
}
References v8::internal::ZoneList< T >::Add(), v8::internal::anonymous_namespace{regexp-compiler.cc}::AddRange(), v8::internal::ZoneList< T >::at(), v8::internal::CharacterRange::Canonicalize(), v8::internal::TextNode::CreateForSurrogatePair(), v8::internal::DCHECK(), ExtractFrom(), ExtractTo(), v8::internal::ZoneList< T >::is_empty(), v8::internal::kTrailSurrogateEnd, v8::internal::kTrailSurrogateStart, unibrow::Utf16::LeadSurrogate(), v8::internal::ZoneList< T >::length(), v8::internal::Zone::New(), v8::internal::UnicodeRangeSplitter::non_bmp(), v8::internal::RegExpCompiler::one_byte(), v8::internal::CharacterRange::Range(), v8::internal::RegExpCompiler::read_backward(), v8::base::internal::result, ToCanonicalZoneList(), ToUC16Range(), unibrow::Utf16::TrailSurrogate(), and v8::internal::RegExpCompiler::zone().
BoundaryAssertionAsLookaround()
RegExpNode* v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::BoundaryAssertionAsLookaround (RegExpCompiler * compiler, RegExpNode * on_success, RegExpAssertion::Type type)
Definition at line 1061 of file regexp-compiler-tonode.cc.
                                                                    {
  CHECK(NeedsUnicodeCaseEquivalents(compiler->flags()));
  Zone* zone = compiler->zone();
  ZoneList<CharacterRange>* word_range =
      zone->New<ZoneList<CharacterRange>>(2, zone);
  CharacterRange::AddClassEscape(StandardCharacterSet::kWord, word_range, true,
                                 zone);
  int stack_register = compiler->UnicodeLookaroundStackRegister();
  int position_register = compiler->UnicodeLookaroundPositionRegister();
  ChoiceNode* result = zone->New<ChoiceNode>(2, zone);
  // Add two choices. The (non-)boundary could start with a word or
  // a non-word-character.
  for (int i = 0; i < 2; i++) {
    bool lookbehind_for_word = i == 0;
    bool lookahead_for_word =
        (type == RegExpAssertion::Type::BOUNDARY) ^ lookbehind_for_word;
    // Look to the left.
    RegExpLookaround::Builder lookbehind(lookbehind_for_word, on_success,
                                         stack_register, position_register);
    RegExpNode* backward = TextNode::CreateForCharacterRanges(
        zone, word_range, true, lookbehind.on_match_success());
    // Look to the right.
    RegExpLookaround::Builder lookahead(lookahead_for_word,
                                        lookbehind.ForMatch(backward),
                                        stack_register, position_register);
    RegExpNode* forward = TextNode::CreateForCharacterRanges(
        zone, word_range, false, lookahead.on_match_success());
    result->AddAlternative(GuardedAlternative(lookahead.ForMatch(forward)));
  }
  return result;
}
References v8::internal::CharacterRange::AddClassEscape(), v8::internal::RegExpAssertion::BOUNDARY, CHECK, v8::internal::TextNode::CreateForCharacterRanges(), v8::internal::RegExpCompiler::flags(), v8::internal::RegExpLookaround::Builder::ForMatch(), v8::internal::kWord, v8::internal::NeedsUnicodeCaseEquivalents(), v8::internal::Zone::New(), v8::internal::RegExpLookaround::Builder::on_match_success(), v8::base::internal::result, v8::internal::tracing::type, v8::internal::RegExpCompiler::UnicodeLookaroundPositionRegister(), v8::internal::RegExpCompiler::UnicodeLookaroundStackRegister(), and v8::internal::RegExpCompiler::zone().
Canonical()
unibrow::uchar v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::Canonical (unibrow::Mapping< unibrow::Ecma262Canonicalize > * canonicalize, unibrow::uchar c)
Definition at line 734 of file regexp-compiler-tonode.cc.
                    {
  unibrow::uchar chars[unibrow::Ecma262Canonicalize::kMaxWidth];
  int length = canonicalize->get(c, '\0', chars);
  DCHECK_LE(length, 1);
  unibrow::uchar canonical = c;
  if (length == 1) canonical = chars[0];
  return canonical;
}
References DCHECK_LE, unibrow::Mapping< T, size >::get(), unibrow::Ecma262Canonicalize::kMaxWidth, and v8::internal::length.
Referenced by CompareCaseInsensitive(), and v8::internal::RegExpDisjunction::RationalizeConsecutiveAtoms().
CharAtEquals()
bool v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::CharAtEquals (bool ignore_case, unibrow::Mapping< unibrow::Ecma262Canonicalize > * canonicalize, int index, const RegExpAtom * a, const RegExpAtom * b)
Definition at line 775 of file regexp-compiler-tonode.cc.
                                                                       {
  return Equals(ignore_case, canonicalize, a->data().at(index),
                b->data().at(index));
}
References v8::base::Vector< T >::at(), v8::internal::RegExpAtom::data(), Equals(), and v8::internal::index.
Referenced by v8::internal::RegExpDisjunction::RationalizeConsecutiveAtoms().
CompareCaseInsensitive()
int v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::CompareCaseInsensitive (unibrow::Mapping< unibrow::Ecma262Canonicalize > * canonicalize, unibrow::uchar a, unibrow::uchar b)
Definition at line 745 of file regexp-compiler-tonode.cc.
                                    {
  if (a == b) return 0;
  if (a >= 'a' || b >= 'a') {
    a = Canonical(canonicalize, a);
    b = Canonical(canonicalize, b);
  }
  return static_cast<int>(a) - static_cast<int>(b);
}
References Canonical().
Referenced by CompareFirstCharCaseInsensitive(), and Equals().
CompareFirstChar()
int v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::CompareFirstChar (RegExpTree *const * a, RegExpTree *const * b)
Definition at line 695 of file regexp-compiler-tonode.cc.
                                                                 {
  RegExpAtom* atom1 = FirstAtom(*a);
  RegExpAtom* atom2 = FirstAtom(*b);
  base::uc16 character1 = atom1->data().at(0);
  base::uc16 character2 = atom2->data().at(0);
  if (character1 < character2) return -1;
  if (character1 > character2) return 1;
  return 0;
}
References v8::base::Vector< T >::at(), v8::internal::RegExpAtom::data(), and FirstAtom().
Referenced by v8::internal::RegExpDisjunction::SortConsecutiveAtoms().
CompareFirstCharCaseInsensitive()
int v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::CompareFirstCharCaseInsensitive (unibrow::Mapping< unibrow::Ecma262Canonicalize > * canonicalize, RegExpTree *const * a, RegExpTree *const * b)
Definition at line 756 of file regexp-compiler-tonode.cc.
                                                {
  RegExpAtom* atom1 = FirstAtom(*a);
  RegExpAtom* atom2 = FirstAtom(*b);
  return CompareCaseInsensitive(canonicalize, atom1->data().at(0),
                                atom2->data().at(0));
}
References v8::base::Vector< T >::at(), CompareCaseInsensitive(), v8::internal::RegExpAtom::data(), and FirstAtom().
Referenced by v8::internal::RegExpDisjunction::SortConsecutiveAtoms().
CompareInverseRanges()
bool v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::CompareInverseRanges (ZoneList< CharacterRange > * ranges, const int * special_class, int length)
Definition at line 50 of file regexp-compiler-tonode.cc.
                                                                {
  length--; // Remove final marker.
  DCHECK_EQ(kRangeEndMarker, special_class[length]);
  DCHECK_NE(0, ranges->length());
  DCHECK_NE(0, length);
  DCHECK_NE(0, special_class[0]);
  if (ranges->length() != (length >> 1) + 1) return false;
  CharacterRange range = ranges->at(0);
  if (range.from() != 0) return false;
  for (int i = 0; i < length; i += 2) {
    if (static_cast<base::uc32>(special_class[i]) != (range.to() + 1)) {
      return false;
    }
    range = ranges->at((i >> 1) + 1);
    if (static_cast<base::uc32>(special_class[i + 1]) != range.from()) {
      return false;
    }
  }
  return range.to() == kMaxCodePoint;
}
References v8::internal::ZoneList< T >::at(), DCHECK_EQ, DCHECK_NE, v8::internal::CharacterRange::from(), v8::internal::kMaxCodePoint, v8::internal::regexp_compiler_constants::kRangeEndMarker, v8::internal::length, v8::internal::ZoneList< T >::length(), and v8::internal::CharacterRange::to().
Referenced by v8::internal::RegExpClassRanges::is_standard().
CompareRanges()
bool v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::CompareRanges (ZoneList< CharacterRange > * ranges, const int * special_class, int length)
Definition at line 77 of file regexp-compiler-tonode.cc.
                               {
  length--; // Remove final marker.
  DCHECK_EQ(kRangeEndMarker, special_class[length]);
  if (ranges->length() * 2 != length) return false;
  for (int i = 0; i < length; i += 2) {
    CharacterRange range = ranges->at(i >> 1);
    if (range.from() != static_cast<base::uc32>(special_class[i]) ||
        range.to() != static_cast<base::uc32>(special_class[i + 1] - 1)) {
      return false;
    }
  }
  return true;
}
References v8::internal::ZoneList< T >::at(), DCHECK_EQ, v8::internal::CharacterRange::from(), v8::internal::regexp_compiler_constants::kRangeEndMarker, v8::internal::length, v8::internal::ZoneList< T >::length(), and v8::internal::CharacterRange::to().
Referenced by v8::internal::RegExpClassRanges::is_standard().
Equals()
bool v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::Equals (bool ignore_case, unibrow::Mapping< unibrow::Ecma262Canonicalize > * canonicalize, unibrow::uchar a, unibrow::uchar b)
Definition at line 765 of file regexp-compiler-tonode.cc.
                                            {
  if (a == b) return true;
  if (ignore_case) {
    return CompareCaseInsensitive(canonicalize, a, b) == 0;
  }
  return false; // Case-sensitive equality already checked above.
}
References CompareCaseInsensitive().
Referenced by CharAtEquals(), v8::internal::compiler::InstructionOperand::EqualsCanonicalized(), v8::internal::ScriptCacheKey::MatchesScript(), v8::internal::compiler::LoadElimination::AbstractElements::Merge(), v8::internal::compiler::LoadElimination::AbstractField::Merge(), v8::internal::compiler::LoadElimination::AbstractMaps::Merge(), v8::internal::maglev::MaglevGraphBuilder::MergeIntoInlinedReturnFrameState(), v8::internal::wasm::NameBuiltinLength(), v8::internal::compiler::InstructionOperand::operator!=(), v8::internal::compiler::InstructionOperand::operator==(), v8::internal::StringStream::PrintPrototype(), v8::internal::RegExpDisjunction::RationalizeConsecutiveAtoms(), v8::internal::anonymous_namespace{liveedit-diff.cc}::MyersDiffer::ShortestEditForward(), and v8::internal::String::SlowEquals().
ExtractFrom()
constexpr base::uc16 v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::ExtractFrom (UC16Range r) [constexpr]
Definition at line 221 of file regexp-compiler-tonode.cc.
                                            {
  return static_cast<base::uc16>(r >> 16);
}
Referenced by AddNonBmpSurrogatePairs().
ExtractTo()
constexpr base::uc16 v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::ExtractTo (UC16Range r) [constexpr]
Definition at line 224 of file regexp-compiler-tonode.cc.
                                          {
  return static_cast<base::uc16>(r);
}
Referenced by AddNonBmpSurrogatePairs().
FirstAtom()
RegExpAtom* v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::FirstAtom (RegExpTree * tree)
Definition at line 690 of file regexp-compiler-tonode.cc.
                                        {
  if (tree->IsAtom()) return tree->AsAtom();
  return tree->AsText()->FirstAtom();
}
Referenced by CompareFirstChar(), CompareFirstCharCaseInsensitive(), and v8::internal::RegExpDisjunction::RationalizeConsecutiveAtoms().
InsertRangeInCanonicalList()
int v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::InsertRangeInCanonicalList (ZoneList< CharacterRange > * list, int count, CharacterRange insert)
Definition at line 1650 of file regexp-compiler-tonode.cc.
                                                      {
  // Inserts a range into list[0..count[, which must be sorted
  // by from value and non-overlapping and non-adjacent, using at most
  // list[0..count] for the result. Returns the number of resulting
  // canonicalized ranges. Inserting a range may collapse existing ranges into
  // fewer ranges, so the return value can be anything in the range 1..count+1.
  base::uc32 from = insert.from();
  base::uc32 to = insert.to();
  int start_pos = 0;
  int end_pos = count;
  for (int i = count - 1; i >= 0; i--) {
    CharacterRange current = list->at(i);
    if (current.from() > to + 1) {
      end_pos = i;
    } else if (current.to() + 1 < from) {
      start_pos = i + 1;
      break;
    }
  }
  // Inserted range overlaps, or is adjacent to, ranges at positions
  // [start_pos..end_pos[. Ranges before start_pos or at or after end_pos are
  // not affected by the insertion.
  // If start_pos == end_pos, the range must be inserted before start_pos.
  // if start_pos < end_pos, the entire range from start_pos to end_pos
  // must be merged with the insert range.
  if (start_pos == end_pos) {
    // Insert between existing ranges at position start_pos.
    if (start_pos < count) {
      MoveRanges(list, start_pos, start_pos + 1, count - start_pos);
    }
    list->at(start_pos) = insert;
    return count + 1;
  }
  if (start_pos + 1 == end_pos) {
    // Replace single existing range at position start_pos.
    CharacterRange to_replace = list->at(start_pos);
    int new_from = std::min(to_replace.from(), from);
    int new_to = std::max(to_replace.to(), to);
    list->at(start_pos) = CharacterRange::Range(new_from, new_to);
    return count;
  }
  // Replace a number of existing ranges from start_pos to end_pos - 1.
  // Move the remaining ranges down.
  int new_from = std::min(list->at(start_pos).from(), from);
  int new_to = std::max(list->at(end_pos - 1).to(), to);
  if (end_pos < count) {
    MoveRanges(list, end_pos, start_pos + 1, count - end_pos);
  }
  list->at(start_pos) = CharacterRange::Range(new_from, new_to);
  return count - (end_pos - start_pos) + 1;
}
References v8::internal::ZoneList< T >::at(), v8::internal::CharacterRange::from(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, MoveRanges(), v8::internal::CharacterRange::Range(), and v8::internal::CharacterRange::to().
Referenced by v8::internal::CharacterRange::Canonicalize().
MatchAndNegativeLookaroundInReadDirection()
RegExpNode* v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::MatchAndNegativeLookaroundInReadDirection (RegExpCompiler * compiler, ZoneList< CharacterRange > * match, ZoneList< CharacterRange > * lookahead, RegExpNode * on_success, bool read_backward)
Definition at line 342 of file regexp-compiler-tonode.cc.
                        {
  Zone* zone = compiler->zone();
  int stack_register = compiler->UnicodeLookaroundStackRegister();
  int position_register = compiler->UnicodeLookaroundPositionRegister();
  RegExpLookaround::Builder lookaround(false, on_success, stack_register,
                                       position_register);
  RegExpNode* negative_match = TextNode::CreateForCharacterRanges(
      zone, lookahead, read_backward, lookaround.on_match_success());
  return TextNode::CreateForCharacterRanges(
      zone, match, read_backward, lookaround.ForMatch(negative_match));
}
References v8::internal::TextNode::CreateForCharacterRanges(), v8::internal::RegExpLookaround::Builder::ForMatch(), v8::internal::RegExpLookaround::Builder::on_match_success(), v8::internal::RegExpCompiler::UnicodeLookaroundPositionRegister(), v8::internal::RegExpCompiler::UnicodeLookaroundStackRegister(), and v8::internal::RegExpCompiler::zone().
Referenced by AddLoneLeadSurrogates(), and AddLoneTrailSurrogates().
MoveRanges()
void v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::MoveRanges (ZoneList< CharacterRange > * list, int from, int to, int count)
Definition at line 1637 of file regexp-compiler-tonode.cc.
                                                                             {
  // Ranges are potentially overlapping.
  if (from < to) {
    for (int i = count - 1; i >= 0; i--) {
      list->at(to + i) = list->at(from + i);
    }
  } else {
    for (int i = 0; i < count; i++) {
      list->at(to + i) = list->at(from + i);
    }
  }
}
References v8::internal::ZoneList< T >::at().
Referenced by InsertRangeInCanonicalList().
NegativeLookaroundAgainstReadDirectionAndMatch()
RegExpNode* v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::NegativeLookaroundAgainstReadDirectionAndMatch (RegExpCompiler * compiler, ZoneList< CharacterRange > * lookbehind, ZoneList< CharacterRange > * match, RegExpNode * on_success, bool read_backward)
Definition at line 326 of file regexp-compiler-tonode.cc.
                        {
  Zone* zone = compiler->zone();
  RegExpNode* match_node = TextNode::CreateForCharacterRanges(
      zone, match, read_backward, on_success);
  int stack_register = compiler->UnicodeLookaroundStackRegister();
  int position_register = compiler->UnicodeLookaroundPositionRegister();
  RegExpLookaround::Builder lookaround(false, match_node, stack_register,
                                       position_register);
  RegExpNode* negative_match = TextNode::CreateForCharacterRanges(
      zone, lookbehind, !read_backward, lookaround.on_match_success());
  return lookaround.ForMatch(negative_match);
}
References v8::internal::TextNode::CreateForCharacterRanges(), v8::internal::RegExpLookaround::Builder::ForMatch(), v8::internal::RegExpLookaround::Builder::on_match_success(), v8::internal::RegExpCompiler::UnicodeLookaroundPositionRegister(), v8::internal::RegExpCompiler::UnicodeLookaroundStackRegister(), and v8::internal::RegExpCompiler::zone().
Referenced by AddLoneLeadSurrogates(), and AddLoneTrailSurrogates().
SafeAdvanceRange()
void v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::SafeAdvanceRange (const ZoneList< CharacterRange > * range, int * index, base::uc32 * from, base::uc32 * to)
Definition at line 1815 of file regexp-compiler-tonode.cc.
                                                    {
  ++(*index);
  if (*index < range->length()) {
    *from = range->at(*index).from();
    *to = range->at(*index).to();
  } else {
    *from = kMaxCodePoint + 1;
  }
}
References v8::internal::ZoneList< T >::at(), v8::internal::kMaxCodePoint, and v8::internal::length.
Referenced by v8::internal::CharacterRange::Subtract().
StartsWithAtom()
bool v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::StartsWithAtom (RegExpTree * tree)
Definition at line 685 of file regexp-compiler-tonode.cc.
                                      {
  if (tree->IsAtom()) return true;
  return tree->IsText() && tree->AsText()->StartsWithAtom();
}
Referenced by v8::internal::RegExpDisjunction::RationalizeConsecutiveAtoms(), and v8::internal::RegExpDisjunction::SortConsecutiveAtoms().
ToCanonicalZoneList()
ZoneList<CharacterRange>* v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::ToCanonicalZoneList (const UnicodeRangeSplitter::CharacterRangeVector * v, Zone * zone)
Definition at line 194 of file regexp-compiler-tonode.cc.
                                                                   {
  if (v->empty()) return nullptr;
  ZoneList<CharacterRange>* result =
      zone->New<ZoneList<CharacterRange>>(static_cast<int>(v->size()), zone);
  for (size_t i = 0; i < v->size(); i++) {
    result->Add(v->at(i), zone);
  }
  CharacterRange::Canonicalize(result);
  return result;
}
References v8::base::SmallVector< T, kSize, Allocator >::at(), v8::internal::CharacterRange::Canonicalize(), v8::base::SmallVector< T, kSize, Allocator >::empty(), v8::internal::Zone::New(), v8::base::internal::result, and v8::base::SmallVector< T, kSize, Allocator >::size().
Referenced by AddBmpCharacters(), AddLoneLeadSurrogates(), AddLoneTrailSurrogates(), and AddNonBmpSurrogatePairs().
ToUC16Range()
constexpr UC16Range v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::ToUC16Range (base::uc16 from, base::uc16 to) [constexpr]
Definition at line 218 of file regexp-compiler-tonode.cc.
                                                            {
  return (static_cast<uint32_t>(from) << 16) | to;
}
Referenced by AddNonBmpSurrogatePairs().
UnanchoredAdvance()
RegExpNode* v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::UnanchoredAdvance (RegExpCompiler * compiler, RegExpNode * on_success)
Definition at line 409 of file regexp-compiler-tonode.cc.
                                                      {
  // This implements ES2015 21.2.5.2.3, AdvanceStringIndex.
  DCHECK(!compiler->read_backward());
  Zone* zone = compiler->zone();
  // Advance any character. If the character happens to be a lead surrogate and
  // we advanced into the middle of a surrogate pair, it will work out, as
  // nothing will match from there. We will have to advance again, consuming
  // the associated trail surrogate.
  ZoneList<CharacterRange>* range =
      CharacterRange::List(zone, CharacterRange::Range(0, kMaxUtf16CodeUnit));
  return TextNode::CreateForCharacterRanges(zone, range, false, on_success);
}
References v8::internal::TextNode::CreateForCharacterRanges(), v8::internal::DCHECK(), v8::internal::kMaxUtf16CodeUnit, v8::internal::CharacterRange::List(), v8::internal::CharacterRange::Range(), v8::internal::RegExpCompiler::read_backward(), and v8::internal::RegExpCompiler::zone().