v8::internal::torque Namespace Reference
Namespaces
 anonymous_namespace{cc-generator.cc}
 anonymous_namespace{class-debug-reader-generator.cc}
 anonymous_namespace{csa-generator.cc}
 anonymous_namespace{declarations.cc}
 anonymous_namespace{earley-parser.cc}
 anonymous_namespace{implementation-visitor.cc}
 anonymous_namespace{instance-type-generator.cc}
 anonymous_namespace{instructions.cc}
 anonymous_namespace{kythe-data.cc}
 anonymous_namespace{torque-compiler.cc}
 anonymous_namespace{torque-parser.cc}
 anonymous_namespace{type-visitor.cc}
 anonymous_namespace{types.cc}
 anonymous_namespace{utils.cc}
 cpp
 ls
Classes
struct AstNode
struct AstNodeClassCheck
struct Expression
struct LocationExpression
struct TypeExpression
struct Declaration
struct Statement
struct NamespaceDeclaration
struct EnumDescription
class Ast
struct Identifier
struct IdentifierPtrValueEq
struct IdentifierExpression
struct IntrinsicCallExpression
struct CallMethodExpression
struct CallExpression
struct NameAndExpression
struct StructExpression
struct LogicalOrExpression
struct LogicalAndExpression
struct SpreadExpression
struct ConditionalExpression
struct StringLiteralExpression
struct IntegerLiteralExpression
struct FloatingPointLiteralExpression
struct ElementAccessExpression
struct FieldAccessExpression
struct DereferenceExpression
struct AssignmentExpression
struct IncrementDecrementExpression
struct AssumeTypeImpossibleExpression
struct NewExpression
struct ParameterList
struct BasicTypeExpression
struct FunctionTypeExpression
struct PrecomputedTypeExpression
struct UnionTypeExpression
struct ExpressionStatement
struct IfStatement
struct WhileStatement
struct ReturnStatement
struct DebugStatement
struct AssertStatement
struct TailCallStatement
struct VarDeclarationStatement
struct BreakStatement
struct ContinueStatement
struct GotoStatement
struct ForLoopStatement
struct TryHandler
struct StatementExpression
struct TryLabelExpression
struct BlockStatement
struct TypeDeclaration
struct InstanceTypeConstraints
struct AbstractTypeDeclaration
struct TypeAliasDeclaration
struct NameAndTypeExpression
struct ImplicitParameters
struct StructFieldExpression
struct BitFieldDeclaration
struct ConditionalAnnotation
struct AnnotationParameter
struct Annotation
struct ClassFieldIndexInfo
struct ClassFieldExpression
struct LabelAndTypes
struct CallableDeclaration
struct MacroDeclaration
struct ExternalMacroDeclaration
struct IntrinsicDeclaration
struct TorqueMacroDeclaration
struct BuiltinDeclaration
struct ExternalBuiltinDeclaration
struct TorqueBuiltinDeclaration
struct ExternalRuntimeDeclaration
struct ConstDeclaration
struct GenericParameter
struct GenericCallableDeclaration
struct GenericTypeDeclaration
struct SpecializationDeclaration
struct ExternConstDeclaration
struct StructDeclaration
struct BitFieldStructDeclaration
struct ClassBody
struct ClassDeclaration
struct CppIncludeDeclaration
class CCGenerator
class Block
class ControlFlowGraph
class CfgAssembler
class CfgAssemblerScopedTemporaryBlock
class CSAGenerator
struct QualifiedName
class Declarable
struct SpecializationRequester
class Scope
class Namespace
class Value
class NamespaceConstant
class ExternConstant
class Callable
class Macro
class ExternMacro
class TorqueMacro
class Method
class Builtin
class RuntimeFunction
class Intrinsic
class TypeConstraint
class GenericDeclarable
class GenericCallable
class GenericType
class TypeAlias
class PredeclarationVisitor
class DeclarationVisitor
class Declarations
class ParseResultHolderBase
class ParseResultHolder
class ParseResult
struct MatchedInput
class ParseResultIterator
struct LexerResult
class Rule
class Symbol
class Item
class Lexer
class Grammar
class GlobalContext
class TargetArchitecture
class Binding
class LocationReference
struct InitializerResults
struct LayoutForInitialization
class BindingsManager
class BlockBindings
class LocalValue
struct LocalLabel
struct Arguments
class ImplementationVisitor
class DefinitionLocation
struct InstructionBase
class Instruction
struct PeekInstruction
struct PokeInstruction
struct DeleteRangeInstruction
struct PushUninitializedInstruction
struct PushBuiltinPointerInstruction
struct NamespaceConstantInstruction
struct LoadReferenceInstruction
struct StoreReferenceInstruction
struct LoadBitFieldInstruction
struct StoreBitFieldInstruction
struct CallIntrinsicInstruction
struct CallCsaMacroInstruction
struct CallCsaMacroAndBranchInstruction
struct MakeLazyNodeInstruction
struct CallBuiltinInstruction
struct CallBuiltinPointerInstruction
struct CallRuntimeInstruction
struct BranchInstruction
struct ConstexprBranchInstruction
struct GotoInstruction
struct GotoExternalInstruction
struct ReturnInstruction
struct PrintErrorInstruction
struct AbortInstruction
struct UnsafeCastInstruction
struct KythePosition
class KytheConsumer
class KytheData
class Logger
class ParameterDifference
class LanguageServerData
class SourceId
struct LineAndColumn
struct SourcePosition
class SourceFileMap
class TorqueCodeGenerator
struct TorqueCompilerOptions
struct TorqueCompilerResult
struct TorqueCompilationUnit
struct ExpressionWithSource
struct TypeswitchCase
struct EnumEntry
class BuildFlags
class TypeArgumentInference
class TypeOracle
class TypeVisitor
class TypeBase
struct SpecializationKey
struct TypeChecker
class Type
struct NameAndType
struct Field
class TopType
class AbstractType
class BuiltinPointerType
struct TypeLess
class UnionType
struct BitField
class BitFieldStructType
class AggregateType
class StructType
class ClassType
class VisitResult
class VisitResultVector
struct LabelDefinition
struct LabelDeclaration
struct ParameterTypes
struct Signature
struct TorqueMessage
class MessageBuilder
struct TorqueAbortCompilation
class Deduplicator
struct ListPrintAdaptor
struct BottomOffset
class StackRange
class Stack
class NullStreambuf
class NullOStream
class IfDefScope
class NamespaceScope
class IncludeGuardScope
class IncludeObjectMacrosScope
class ResidueClass
class Worklist
Typedefs
using LabelAndTypesVector = std::vector< LabelAndTypes >
using GenericParameters = std::vector< GenericParameter >
using AbstractTypeFlags = base::Flags< AbstractTypeFlag >
using ClassFlags = base::Flags< ClassFlag >
using StructFlags = base::Flags< StructFlag >
using ParseResultTypeId = ParseResultHolderBase::TypeId
using InputPosition = const char *
using Action = std::optional< ParseResult >(*)(ParseResultIterator *child_results)
using kythe_entity_t = uint64_t
using DefinitionMapping = std::pair< SourcePosition, SourcePosition >
using Definitions = std::vector< DefinitionMapping >
using DefinitionsMap = std::map< SourceId, Definitions >
using Symbols = std::vector< Declarable * >
using SymbolsMap = std::map< SourceId, Symbols >
using TypeList = std::vector< TypeExpression * >
using TypeVector = std::vector< const Type * >
using MaybeSpecializationKey = std::optional< SpecializationKey< GenericType > >
using NameAndTypeVector = std::vector< NameAndType >
using LabelDefinitionVector = std::vector< LabelDefinition >
using LabelDeclarationVector = std::vector< LabelDeclaration >
using NameVector = std::vector< Identifier * >
Enumerations
enum class IncrementDecrementOperator { kIncrement
, kDecrement
 }
enum class ImplicitKind { kNoImplicit
, kJSImplicit
, kImplicit
 }
enum class ConditionalAnnotationType { kPositive
, kNegative
 }
enum class AbstractTypeFlag { kNone = 0
, kTransient = 1 << 0
, kConstexpr = 1 << 1
, kUseParentTypeChecker = 1 << 2
 }
enum class ClassFlag {
kNone = 0
, kExtern = 1 << 0
, kTransient = 1 << 1
, kAbstract = 1 << 2
,
kIsShape = 1 << 3
, kHasSameInstanceTypeAsParent = 1 << 4
, kGenerateCppClassDefinitions = 1 << 5
, kHighestInstanceTypeWithinParent = 1 << 6
,
kLowestInstanceTypeWithinParent = 1 << 7
, kUndefinedLayout = 1 << 8
, kGenerateBodyDescriptor = 1 << 9
, kExport = 1 << 10
,
kDoNotGenerateCast = 1 << 11
, kGenerateUniqueMap = 1 << 12
, kGenerateFactoryFunction = 1 << 13
, kCppObjectDefinition = 1 << 14
,
kCppObjectLayoutDefinition = 1 << 15
 }
enum class StructFlag { kNone = 0
, kExport = 1 << 0
 }
enum class FieldSynchronization { kNone
, kRelaxed
, kAcquireRelease
 }
enum class OutputType { kCSA
, kCC
, kCCDebug
 }
enum class InstructionKind { ENUM_ITEM
 }
enum class ObjectSlotKind : uint8_t { kNoPointer
, kStrongPointer
, kMaybeObjectPointer
, kCustomWeakPointer
 }
enum class ParameterMode { kProcessImplicit
, kIgnoreImplicit
 }
Functions
std::ostream & operator<< (std::ostream &os, Identifier *id)
bool IsDeferred (Statement *stmt)
DECLARE_CONTEXTUAL_VARIABLE (CurrentAst, Ast)
template<class T , class... Args>
T * MakeNode (Args... args)
FieldAccessExpression * MakeFieldAccessExpression (Expression *object, std::string field)
IdentifierExpression * MakeIdentifierExpression (std::vector< std::string > namespace_qualification, std::string name, std::vector< TypeExpression * > args={})
IdentifierExpression * MakeIdentifierExpression (std::string name)
CallExpression * MakeCallExpression (IdentifierExpression *callee, std::vector< Expression * > arguments, std::vector< Identifier * > labels={})
CallExpression * MakeCallExpression (std::string callee, std::vector< Expression * > arguments, std::vector< Identifier * > labels={})
VarDeclarationStatement * MakeConstDeclarationStatement (std::string name, Expression *initializer)
BasicTypeExpression * MakeBasicTypeExpression (std::vector< std::string > namespace_qualification, Identifier *name, std::vector< TypeExpression * > generic_arguments={})
StructExpression * MakeStructExpression (TypeExpression *type, std::vector< NameAndExpression > initializers)
std::vector< std::size_t > CountBlockPredecessors (const ControlFlowGraph &cfg)
bool IsConstexprName (const std::string &name)
std::string GetNonConstexprName (const std::string &name)
std::string GetConstexprName (const std::string &name)
std::ostream & operator<< (std::ostream &os, const QualifiedName &name)
std::ostream & operator<< (std::ostream &os, const Callable &m)
std::ostream & operator<< (std::ostream &os, const Builtin &b)
std::ostream & operator<< (std::ostream &os, const RuntimeFunction &b)
std::ostream & operator<< (std::ostream &os, const GenericCallable &g)
std::optional< std::string > FindConstraintViolation (const std::vector< const Type * > &types, const std::vector< TypeConstraint > &constraints)
std::vector< TypeConstraint > ComputeConstraints (Scope *scope, const GenericParameters &parameters)
DECLARE_CONTEXTUAL_VARIABLE (CurrentScope, Scope *)
Namespace * CurrentNamespace ()
Namespace * GetOrCreateNamespace (const std::string &name)
template<class T >
std::vector< T * > FilterDeclarables (const std::vector< Declarable * > list)
std::string UnwrapTNodeTypeName (const std::string &generates)
const Item * RunEarleyAlgorithm (Symbol *start, const LexerResult &tokens, std::unordered_set< Item, base::hash< Item >> *processed)
std::optional< ParseResult > DefaultAction (ParseResultIterator *child_results)
template<class T , Action action>
Action AsSingletonVector ()
std::optional< ParseResult > ParseTokens (Symbol *start, const LexerResult &tokens)
template<class T >
T * RegisterDeclarable (std::unique_ptr< T > d)
bool IsCompatibleSignature (const Signature &sig, const TypeVector &types, size_t label_count)
std::string MachineTypeString (const Type *type)
std::optional< std::string > MatchSimpleBodyDescriptor (const ClassType *type)
void ReportAllUnusedMacros ()
std::ostream & operator<< (std::ostream &os, const NamespaceConstantInstruction &instruction)
std::ostream & operator<< (std::ostream &os, const CallIntrinsicInstruction &instruction)
std::ostream & operator<< (std::ostream &os, const CallCsaMacroInstruction &instruction)
std::ostream & operator<< (std::ostream &os, const CallCsaMacroAndBranchInstruction &instruction)
std::ostream & operator<< (std::ostream &os, const CallBuiltinInstruction &instruction)
std::ostream & operator<< (std::ostream &os, const CallRuntimeInstruction &instruction)
std::ostream & operator<< (std::ostream &os, const BranchInstruction &instruction)
std::ostream & operator<< (std::ostream &os, const ConstexprBranchInstruction &instruction)
std::ostream & operator<< (std::ostream &os, const GotoInstruction &instruction)
std::ostream & operator<< (std::ostream &os, const MakeLazyNodeInstruction &instruction)
std::ostream & operator<< (std::ostream &stream, const DefinitionLocation &loc)
std::ostream & operator<< (std::ostream &os, const PeekInstruction &instruction)
std::ostream & operator<< (std::ostream &os, const PokeInstruction &instruction)
std::ostream & operator<< (std::ostream &os, const DeleteRangeInstruction &instruction)
std::ostream & operator<< (std::ostream &os, const PushUninitializedInstruction &instruction)
std::ostream & operator<< (std::ostream &os, const PushBuiltinPointerInstruction &instruction)
std::ostream & operator<< (std::ostream &os, const LoadReferenceInstruction &instruction)
std::ostream & operator<< (std::ostream &os, const StoreReferenceInstruction &instruction)
std::ostream & operator<< (std::ostream &os, const LoadBitFieldInstruction &instruction)
std::ostream & operator<< (std::ostream &os, const StoreBitFieldInstruction &instruction)
std::ostream & operator<< (std::ostream &os, const CallBuiltinPointerInstruction &instruction)
std::ostream & operator<< (std::ostream &os, const GotoExternalInstruction &instruction)
std::ostream & operator<< (std::ostream &os, const ReturnInstruction &instruction)
std::ostream & operator<< (std::ostream &os, const PrintErrorInstruction &instruction)
std::ostream & operator<< (std::ostream &os, const AbortInstruction &instruction)
std::ostream & operator<< (std::ostream &os, const UnsafeCastInstruction &instruction)
DECLARE_CONTEXTUAL_VARIABLE (TorqueFileList, std::vector< std::string >)
DECLARE_CONTEXTUAL_VARIABLE (DiagnosticsFiles, std::vector< SourceId >)
DECLARE_CONTEXTUAL_VARIABLE (CurrentSourceFile, SourceId)
DECLARE_CONTEXTUAL_VARIABLE (CurrentSourcePosition, SourcePosition)
std::string PositionAsString (SourcePosition pos)
std::ostream & operator<< (std::ostream &out, SourcePosition pos)
TorqueCompilerResult CompileTorque (const std::string &source, TorqueCompilerOptions options)
TorqueCompilerResult CompileTorque (const std::vector< std::string > &files, TorqueCompilerOptions options)
TorqueCompilerResult CompileTorqueForKythe (std::vector< TorqueCompilationUnit > units, TorqueCompilerOptions options, KytheConsumer *consumer)
void ParseTorque (const std::string &input)
std::string ErrorPrefixFor (TorqueMessage::Kind kind)
int WrappedMain (int argc, const char **argv)
void DeclareMethods (AggregateType *container_type, const std::vector< Declaration * > &methods)
const Type * SubtractType (const Type *a, const Type *b)
void PrintSignature (std::ostream &os, const Signature &sig, bool with_names)
std::ostream & operator<< (std::ostream &os, const NameAndType &name_and_type)
std::ostream & operator<< (std::ostream &os, const Field &field)
std::ostream & operator<< (std::ostream &os, const Signature &sig)
std::ostream & operator<< (std::ostream &os, const TypeVector &types)
std::ostream & operator<< (std::ostream &os, const ParameterTypes &p)
bool IsAssignableFrom (const Type *to, const Type *from)
bool operator< (const Type &a, const Type &b)
VisitResult ProjectStructField (VisitResult structure, const std::string &fieldname)
TypeVector LowerType (const Type *type)
size_t LoweredSlotCount (const Type *type)
TypeVector LowerParameterTypes (const TypeVector &parameters)
TypeVector LowerParameterTypes (const ParameterTypes &parameter_types, size_t arg_count)
std::optional< std::tuple< size_t, std::string > > SizeOf (const Type *type)
bool IsAnyUnsignedInteger (const Type *type)
bool IsAllowedAsBitField (const Type *type)
bool IsPointerSizeIntegralType (const Type *type)
bool Is32BitIntegralType (const Type *type)
std::optional< NameAndType > ExtractSimpleFieldArraySize (const ClassType &class_type, Expression *array_size)
size_t hash_value (const TypeVector &types)
std::optional< ObjectSlotKind > Combine (ObjectSlotKind a, ObjectSlotKind b)
std::ostream & operator<< (std::ostream &os, const Type &t)
template<bool success = false>
std::ostream & operator<< (std::ostream &os, const Type *t)
std::ostream & operator<< (base::CheckMessageStream &os, const Type *t)
std::string StringLiteralUnquote (const std::string &s)
std::string StringLiteralQuote (const std::string &s)
static int HexCharToInt (unsigned char c)
std::optional< std::string > FileUriDecode (const std::string &uri)
bool IsLowerCamelCase (const std::string &s)
bool IsUpperCamelCase (const std::string &s)
bool IsSnakeCase (const std::string &s)
bool IsValidNamespaceConstName (const std::string &s)
bool IsValidTypeName (const std::string &s)
std::string CapifyStringWithUnderscores (const std::string &camellified_string)
std::string CamelifyString (const std::string &underscore_string)
std::string SnakeifyString (const std::string &camel_string)
std::string DashifyString (const std::string &underscore_string)
std::string UnderlinifyPath (std::string path)
bool StartsWithSingleUnderscore (const std::string &str)
void ReplaceFileContentsIfDifferent (const std::string &file_path, const std::string &contents)
std::ostream & operator<< (std::ostream &os, const ResidueClass &a)
DECLARE_CONTEXTUAL_VARIABLE (TorqueMessages, std::vector< TorqueMessage >)
template<class... Args>
std::string ToString (Args &&... args)
template<class... Args>
static MessageBuilder Message (TorqueMessage::Kind kind, Args &&... args)
template<class... Args>
MessageBuilder Error (Args &&... args)
template<class... Args>
MessageBuilder Lint (Args &&... args)
template<class... Args>
void ReportError (Args &&... args)
template<class T >
T & DereferenceIfPointer (T *x)
template<class T >
T && DereferenceIfPointer (T &&x)
template<class T >
auto PrintList (const T &list, const std::string &separator=`, `)
template<class T , class L >
auto PrintList (const T &list, const std::string &separator, L &&transformer)
template<class C , class T >
void PrintCommaSeparatedList (std::ostream &os, const T &list, C &&transform)
template<class T >
void PrintCommaSeparatedList (std::ostream &os, const T &list)
std::ostream & operator<< (std::ostream &out, BottomOffset from_bottom)
std::ostream & operator<< (std::ostream &out, StackRange range)
template<class T >
T * CheckNotNull (T *x)
template<class T >
std::ostream & operator<< (std::ostream &os, const Stack< T > &t)
template<class Container , class F >
void EraseIf (Container *container, F f)
bool StringStartsWith (const std::string &s, const std::string &prefix)
bool StringEndsWith (const std::string &s, const std::string &suffix)
template<class T , class U , class F >
std::vector< T > TransformVector (const std::vector< U > &v, F f)
template<class T , class U >
std::vector< T > TransformVector (const std::vector< U > &v)
Variables
static const char *const kThisParameterName = `this`
constexpr char kTqObjectOverrideDecls []
static const char *const CONSTEXPR_TYPE_PREFIX = `constexpr `
static const char *const NEVER_TYPE_STRING = `never`
static const char *const CONSTEXPR_BOOL_TYPE_STRING = `constexpr bool`
static const char *const CONSTEXPR_STRING_TYPE_STRING = `constexpr string`
static const char *const CONSTEXPR_INTPTR_TYPE_STRING = `constexpr intptr`
static const char *const CONSTEXPR_INSTANCE_TYPE_TYPE_STRING
static const char *const BOOL_TYPE_STRING = `bool`
static const char *const VOID_TYPE_STRING = `void`
static const char *const ARGUMENTS_TYPE_STRING = `Arguments`
static const char *const CONTEXT_TYPE_STRING = `Context`
static const char *const NO_CONTEXT_TYPE_STRING = `NoContext`
static const char *const NATIVE_CONTEXT_TYPE_STRING = `NativeContext`
static const char *const JS_FUNCTION_TYPE_STRING = `JSFunction`
static const char *const MAP_TYPE_STRING = `Map`
static const char *const OBJECT_TYPE_STRING = `Object`
static const char *const HEAP_OBJECT_TYPE_STRING = `HeapObject`
static const char *const TAGGED_ZERO_PATTERN_TYPE_STRING = `TaggedZeroPattern`
static const char *const JSANY_TYPE_STRING = `JSAny`
static const char *const JSOBJECT_TYPE_STRING = `JSObject`
static const char *const SMI_TYPE_STRING = `Smi`
static const char *const TAGGED_TYPE_STRING = `Tagged`
static const char *const STRONG_TAGGED_TYPE_STRING = `StrongTagged`
static const char *const UNINITIALIZED_HEAP_OBJECT_TYPE_STRING
static const char *const RAWPTR_TYPE_STRING = `RawPtr`
static const char *const EXTERNALPTR_TYPE_STRING = `ExternalPointer`
static const char *const CPPHEAPPTR_TYPE_STRING = `CppHeapPointer`
static const char *const TRUSTEDPTR_TYPE_STRING = `TrustedPointer`
static const char *const PROTECTEDPTR_TYPE_STRING = `ProtectedPointer`
static const char *const DISPATCH_HANDLE_TYPE_STRING = `DispatchHandle`
static const char *const CONST_STRING_TYPE_STRING = `constexpr string`
static const char *const STRING_TYPE_STRING = `String`
static const char *const NUMBER_TYPE_STRING = `Number`
static const char *const BUILTIN_POINTER_TYPE_STRING = `BuiltinPtr`
static const char *const INTPTR_TYPE_STRING = `intptr`
static const char *const UINTPTR_TYPE_STRING = `uintptr`
static const char *const INT64_TYPE_STRING = `int64`
static const char *const UINT64_TYPE_STRING = `uint64`
static const char *const INT31_TYPE_STRING = `int31`
static const char *const INT32_TYPE_STRING = `int32`
static const char *const UINT31_TYPE_STRING = `uint31`
static const char *const UINT32_TYPE_STRING = `uint32`
static const char *const INT16_TYPE_STRING = `int16`
static const char *const UINT16_TYPE_STRING = `uint16`
static const char *const INT8_TYPE_STRING = `int8`
static const char *const UINT8_TYPE_STRING = `uint8`
static const char *const BINT_TYPE_STRING = `bint`
static const char *const CHAR8_TYPE_STRING = `char8`
static const char *const CHAR16_TYPE_STRING = `char16`
static const char *const FLOAT16_RAW_BITS_TYPE_STRING = `float16_raw_bits`
static const char *const FLOAT32_TYPE_STRING = `float32`
static const char *const FLOAT64_TYPE_STRING = `float64`
static const char *const FLOAT64_OR_UNDEFINED_OR_HOLE_TYPE_STRING
static const char *const CONST_INT31_TYPE_STRING = `constexpr int31`
static const char *const CONST_INT32_TYPE_STRING = `constexpr int32`
static const char *const CONST_FLOAT64_TYPE_STRING = `constexpr float64`
static const char *const INTEGER_LITERAL_TYPE_STRING
static const char *const TORQUE_INTERNAL_NAMESPACE_STRING = `torque_internal`
static const char *const MUTABLE_REFERENCE_TYPE_STRING = `MutableReference`
static const char *const CONST_REFERENCE_TYPE_STRING = `ConstReference`
static const char *const MUTABLE_SLICE_TYPE_STRING = `MutableSlice`
static const char *const CONST_SLICE_TYPE_STRING = `ConstSlice`
static const char *const WEAK_TYPE_STRING = `Weak`
static const char *const SMI_TAGGED_TYPE_STRING = `SmiTagged`
static const char *const LAZY_TYPE_STRING = `Lazy`
static const char *const UNINITIALIZED_ITERATOR_TYPE_STRING
static const char *const GENERIC_TYPE_INSTANTIATION_NAMESPACE_STRING
static const char *const FIXED_ARRAY_BASE_TYPE_STRING = `FixedArrayBase`
static const char *const WEAK_HEAP_OBJECT = `WeakHeapObject`
static const char *const STATIC_ASSERT_MACRO_STRING = `StaticAssert`
static const char *const ANNOTATION_ABSTRACT = `@abstract`
static const char *const ANNOTATION_HAS_SAME_INSTANCE_TYPE_AS_PARENT
static const char *const ANNOTATION_DO_NOT_GENERATE_CPP_CLASS
static const char *const ANNOTATION_CUSTOM_MAP = `@customMap`
static const char *const ANNOTATION_CUSTOM_CPP_CLASS = `@customCppClass`
static const char *const ANNOTATION_HIGHEST_INSTANCE_TYPE_WITHIN_PARENT
static const char *const ANNOTATION_LOWEST_INSTANCE_TYPE_WITHIN_PARENT
static const char *const ANNOTATION_RESERVE_BITS_IN_INSTANCE_TYPE
static const char *const ANNOTATION_INSTANCE_TYPE_VALUE
static const char *const ANNOTATION_IF = `@if`
static const char *const ANNOTATION_IFNOT = `@ifnot`
static const char *const ANNOTATION_GENERATE_BODY_DESCRIPTOR
static const char *const ANNOTATION_GENERATE_UNIQUE_MAP = `@generateUniqueMap`
static const char *const ANNOTATION_GENERATE_FACTORY_FUNCTION
static const char *const ANNOTATION_EXPORT = `@export`
static const char *const ANNOTATION_DO_NOT_GENERATE_CAST = `@doNotGenerateCast`
static const char *const ANNOTATION_USE_PARENT_TYPE_CHECKER
static const char *const ANNOTATION_CPP_OBJECT_DEFINITION
static const char *const ANNOTATION_CPP_OBJECT_LAYOUT_DEFINITION
static const char *const ANNOTATION_SAME_ENUM_VALUE_AS = `@sameEnumValueAs`
static const char *const ANNOTATION_CPP_RELAXED_STORE = `@cppRelaxedStore`
static const char *const ANNOTATION_CPP_RELAXED_LOAD = `@cppRelaxedLoad`
static const char *const ANNOTATION_CPP_RELEASE_STORE = `@cppReleaseStore`
static const char *const ANNOTATION_CPP_ACQUIRE_LOAD = `@cppAcquireLoad`
static const char *const ANNOTATION_CUSTOM_WEAK_MARKING = `@customWeakMarking`
static const char *const ANNOTATION_CUSTOM_INTERFACE_DESCRIPTOR
static const char *const ANNOTATION_INCREMENT_USE_COUNTER
static constexpr const char *const kFromConstexprMacroName = `FromConstexpr`
static constexpr const char * kMacroEndLabelName = `__macro_end`
static constexpr const char * kBreakLabelName = `__break`
static constexpr const char * kContinueLabelName = `__continue`
static constexpr const char * kCatchLabelName = `__catch`
static constexpr const char * kNextCaseLabelName = `__NextCase`
uint64_t next_unique_binding_index = 0
static const char kFileUriPrefix [] = `file://`
static const int kFileUriPrefixLength = sizeof(kFileUriPrefix) - 1
static const char *const kBaseNamespaceName = `base`
static const char *const kTestNamespaceName = `test`
Typedef Documentation
AbstractTypeFlags
using v8::internal::torque::AbstractTypeFlags = typedef base::Flags<AbstractTypeFlag>
Definition at line 164 of file constants.h.
Action
using v8::internal::torque::Action = typedef std::optional<ParseResult> (*)(ParseResultIterator* child_results)
Definition at line 193 of file earley-parser.h.
ClassFlags
using v8::internal::torque::ClassFlags = typedef base::Flags<ClassFlag>
Definition at line 185 of file constants.h.
DefinitionMapping
using v8::internal::torque::DefinitionMapping = typedef std::pair<SourcePosition, SourcePosition>
Definition at line 22 of file server-data.h.
Definitions
using v8::internal::torque::Definitions = typedef std::vector<DefinitionMapping>
Definition at line 24 of file server-data.h.
DefinitionsMap
using v8::internal::torque::DefinitionsMap = typedef std::map<SourceId, Definitions>
Definition at line 25 of file server-data.h.
GenericParameters
using v8::internal::torque::GenericParameters = typedef std::vector<GenericParameter>
Definition at line 1129 of file ast.h.
InputPosition
using v8::internal::torque::InputPosition = typedef const char*
Definition at line 150 of file earley-parser.h.
kythe_entity_t
using v8::internal::torque::kythe_entity_t = typedef uint64_t
Definition at line 23 of file kythe-data.h.
LabelAndTypesVector
using v8::internal::torque::LabelAndTypesVector = typedef std::vector<LabelAndTypes>
Definition at line 967 of file ast.h.
LabelDeclarationVector
using v8::internal::torque::LabelDeclarationVector = typedef std::vector<LabelDeclaration>
Definition at line 895 of file types.h.
LabelDefinitionVector
using v8::internal::torque::LabelDefinitionVector = typedef std::vector<LabelDefinition>
Definition at line 888 of file types.h.
MaybeSpecializationKey
using v8::internal::torque::MaybeSpecializationKey = typedef std::optional<SpecializationKey<GenericType> >
Definition at line 93 of file types.h.
NameAndTypeVector
using v8::internal::torque::NameAndTypeVector = typedef std::vector<NameAndType>
Definition at line 881 of file types.h.
NameVector
using v8::internal::torque::NameVector = typedef std::vector<Identifier*>
Definition at line 906 of file types.h.
ParseResultTypeId
using v8::internal::torque::ParseResultTypeId = typedef ParseResultHolderBase::TypeId
Definition at line 102 of file earley-parser.h.
StructFlags
using v8::internal::torque::StructFlags = typedef base::Flags<StructFlag>
Definition at line 188 of file constants.h.
Symbols
using v8::internal::torque::Symbols = typedef std::vector<Declarable*>
Definition at line 31 of file server-data.h.
SymbolsMap
using v8::internal::torque::SymbolsMap = typedef std::map<SourceId, Symbols>
Definition at line 32 of file server-data.h.
TypeList
using v8::internal::torque::TypeList = typedef std::vector<TypeExpression*>
Definition at line 26 of file torque-parser.cc.
TypeVector
using v8::internal::torque::TypeVector = typedef std::vector<const Type*>
Definition at line 85 of file types.h.
Enumeration Type Documentation
AbstractTypeFlag
enum v8::internal::torque::AbstractTypeFlag [strong]
Enumerator
kNone
kTransient
kConstexpr
kUseParentTypeChecker
Definition at line 158 of file constants.h.
                            {
  kNone = 0,
  kTransient = 1 << 0,
  kConstexpr = 1 << 1,
  kUseParentTypeChecker = 1 << 2,
};
ClassFlag
enum v8::internal::torque::ClassFlag [strong]
Enumerator
kNone
kExtern
kTransient
kAbstract
kIsShape
kHasSameInstanceTypeAsParent
kGenerateCppClassDefinitions
kHighestInstanceTypeWithinParent
kLowestInstanceTypeWithinParent
kUndefinedLayout
kGenerateBodyDescriptor
kExport
kDoNotGenerateCast
kGenerateUniqueMap
kGenerateFactoryFunction
kCppObjectDefinition
kCppObjectLayoutDefinition
Definition at line 166 of file constants.h.
                     {
  kNone = 0,
  kExtern = 1 << 0,
  kTransient = 1 << 1,
  kAbstract = 1 << 2,
  kIsShape = 1 << 3,
  kHasSameInstanceTypeAsParent = 1 << 4,
  kGenerateCppClassDefinitions = 1 << 5,
  kHighestInstanceTypeWithinParent = 1 << 6,
  kLowestInstanceTypeWithinParent = 1 << 7,
  kUndefinedLayout = 1 << 8,
  kGenerateBodyDescriptor = 1 << 9,
  kExport = 1 << 10,
  kDoNotGenerateCast = 1 << 11,
  kGenerateUniqueMap = 1 << 12,
  kGenerateFactoryFunction = 1 << 13,
  kCppObjectDefinition = 1 << 14,
  kCppObjectLayoutDefinition = 1 << 15,
};
ConditionalAnnotationType
enum v8::internal::torque::ConditionalAnnotationType [strong]
Enumerator
kPositive
kNegative
Definition at line 923 of file ast.h.
                                     {
  kPositive,
  kNegative,
};
FieldSynchronization
enum v8::internal::torque::FieldSynchronization [strong]
Enumerator
kNone
kRelaxed
kAcquireRelease
Definition at line 190 of file constants.h.
                                {
  kNone,
  kRelaxed,
  kAcquireRelease,
};
ImplicitKind
enum v8::internal::torque::ImplicitKind [strong]
Enumerator
kNoImplicit
kJSImplicit
kImplicit
Definition at line 623 of file ast.h.
{ kNoImplicit, kJSImplicit, kImplicit };
IncrementDecrementOperator
enum v8::internal::torque::IncrementDecrementOperator [strong]
Enumerator
kIncrement
kDecrement
Definition at line 559 of file ast.h.
{ kIncrement, kDecrement };
InstructionKind
enum v8::internal::torque::InstructionKind [strong]
Enumerator
ENUM_ITEM
Definition at line 71 of file instructions.h.
                           {
#define ENUM_ITEM(name) k##name,
  TORQUE_INSTRUCTION_LIST(ENUM_ITEM)
#undef ENUM_ITEM
};
ObjectSlotKind
enum v8::internal::torque::ObjectSlotKind : uint8_t [strong]
Enumerator
kNoPointer
kStrongPointer
kMaybeObjectPointer
kCustomWeakPointer
Definition at line 655 of file types.h.
                          : uint8_t {
  kNoPointer,
  kStrongPointer,
  kMaybeObjectPointer,
  kCustomWeakPointer
};
OutputType
enum v8::internal::torque::OutputType [strong]
Enumerator
kCSA
kCC
kCCDebug
Definition at line 295 of file declarable.h.
                      {
  kCSA,
  kCC,
  kCCDebug,
};
ParameterMode
enum v8::internal::torque::ParameterMode [strong]
Enumerator
kProcessImplicit
kIgnoreImplicit
Definition at line 904 of file types.h.
{ kProcessImplicit, kIgnoreImplicit };
StructFlag
enum v8::internal::torque::StructFlag [strong]
Enumerator
kNone
kExport
Definition at line 187 of file constants.h.
{ kNone = 0, kExport = 1 << 0 };
Function Documentation
AsSingletonVector()
template<class T , Action action>
Action v8::internal::torque::AsSingletonVector () [inline]
Definition at line 203 of file earley-parser.h.
                                  {
  return [](ParseResultIterator* child_results) -> std::optional<ParseResult> {
    auto result = action(child_results);
    if (!result) return result;
    return ParseResult{std::vector<T>{(*result).Cast<T>()}};
  };
}
References v8::internal::torque::ParseResult::Cast(), and v8::base::internal::result.
CamelifyString()
std::string v8::internal::torque::CamelifyString (const std::string & underscore_string)
Definition at line 278 of file utils.cc.
                                                             {
  std::string result;
  bool word_beginning = true;
  for (auto current : underscore_string) {
    if (current == '_' || current == '-') {
      word_beginning = true;
      continue;
    }
    if (word_beginning) {
      current = toupper(current);
    }
    result += current;
    word_beginning = false;
  }
  return result;
}
References v8::base::internal::result, and v8::internal::string.
Referenced by v8::internal::torque::ClassType::GenerateAccessors(), v8::internal::torque::ImplementationVisitor::GenerateBitFields(), v8::internal::torque::ImplementationVisitor::GenerateBuiltinDefinitionsAndInterfaceDescriptors(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::GenerateCppObjectDefinitionAsserts(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::GenerateCppObjectLayoutDefinitionAsserts(), v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::GenerateFieldValueAccessor(), v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::GenerateGetPropsChunkForField(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::GenerateStructLayoutDescription(), v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::DebugFieldType::GetAddressGetter(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::GetFieldOffsetForAccessor(), v8::internal::torque::ClassType::GetSliceMacroName(), v8::internal::torque::ImplementationVisitor::Visit(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::ClassFieldOffsetGenerator::WriteField(), and v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::ClassFieldOffsetGenerator::WriteFieldOffsetGetter().
CapifyStringWithUnderscores()
std::string v8::internal::torque::CapifyStringWithUnderscores (const std::string & camellified_string)
Definition at line 254 of file utils.cc.
                                                                           {
  // Special case: JSAbc yields JS_ABC, not JSABC, for any Abc.
  size_t js_position = camellified_string.find("JS");
  std::string result;
  bool previousWasLowerOrDigit = false;
  for (size_t index = 0; index < camellified_string.size(); ++index) {
    char current = camellified_string[index];
    if ((previousWasLowerOrDigit && isupper(current)) ||
        (js_position != std::string::npos &&
         index == js_position + strlen("JS"))) {
      result += "_";
    }
    if (current == '.' || current == '-') {
      result += "_";
      previousWasLowerOrDigit = false;
      continue;
    }
    result += toupper(current);
    previousWasLowerOrDigit = islower(current) || isdigit(current);
  }
  return result;
}
References v8::internal::index, v8::base::internal::result, and v8::internal::string.
Referenced by v8::internal::torque::ImplementationVisitor::GenerateBitFields(), v8::internal::torque::ImplementationVisitor::GenerateInstanceTypes(), v8::internal::torque::ImplementationVisitor::GenerateVisitorLists(), v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::PrintInstanceTypes(), and v8::internal::torque::ImplementationVisitor::Visit().
CheckNotNull()
template<class T >
T* v8::internal::torque::CheckNotNull (T * x)
Definition at line 308 of file utils.h.
                      {
  CHECK_NOT_NULL(x);
  return x;
}
References CHECK_NOT_NULL.
Combine()
std::optional<ObjectSlotKind> v8::internal::torque::Combine (ObjectSlotKind a, ObjectSlotKind b) [inline]
Definition at line 662 of file types.h.
                                                               {
  if (a == b) return {a};
  if (std::min(a, b) == ObjectSlotKind::kStrongPointer &&
      std::max(a, b) == ObjectSlotKind::kMaybeObjectPointer) {
    return {ObjectSlotKind::kMaybeObjectPointer};
  }
  return std::nullopt;
}
References kMaybeObjectPointer, and kStrongPointer.
CompileTorque() [1/2]
V8_EXPORT_PRIVATE TorqueCompilerResult v8::internal::torque::CompileTorque (const std::string & source, TorqueCompilerOptions options)
Definition at line 115 of file torque-compiler.cc.
                                                                  {
  TargetArchitecture::Scope target_architecture(options.force_32bit_output);
  SourceFileMap::Scope source_map_scope(options.v8_root);
  CurrentSourceFile::Scope no_file_scope(
      SourceFileMap::AddSource("dummy-filename.tq"));
  CurrentAst::Scope ast_scope;
  TorqueMessages::Scope messages_scope;
  LanguageServerData::Scope server_data_scope;
  TorqueCompilerResult result;
  try {
    ParseTorque(source);
    CompileCurrentAst(options);
  } catch (TorqueAbortCompilation&) {
    // Do nothing. The relevant TorqueMessage is part of the
    // TorqueMessages contextual.
  }
  result.source_file_map = SourceFileMap::Get();
  result.language_server_data = std::move(LanguageServerData::Get());
  result.messages = std::move(TorqueMessages::Get());
  return result;
}
References v8::internal::torque::SourceFileMap::AddSource(), v8::internal::torque::anonymous_namespace{torque-compiler.cc}::CompileCurrentAst(), v8::internal::torque::TorqueCompilerOptions::force_32bit_output, v8::base::ContextualVariable< Derived, VarType >::Get(), v8::internal::compiler::turboshaft::Get(), ParseTorque(), v8::base::internal::result, and v8::internal::torque::TorqueCompilerOptions::v8_root.
Referenced by v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::RecompileTorque(), and WrappedMain().
CompileTorque() [2/2]
TorqueCompilerResult v8::internal::torque::CompileTorque (const std::vector< std::string > & files, TorqueCompilerOptions options)
Definition at line 141 of file torque-compiler.cc.
                                                                  {
  TargetArchitecture::Scope target_architecture(options.force_32bit_output);
  SourceFileMap::Scope source_map_scope(options.v8_root);
  CurrentSourceFile::Scope unknown_source_file_scope(SourceId::Invalid());
  CurrentAst::Scope ast_scope;
  TorqueMessages::Scope messages_scope;
  LanguageServerData::Scope server_data_scope;
  TorqueCompilerResult result;
  try {
    for (const auto& path : files) {
      ReadAndParseTorqueFile(path);
    }
    CompileCurrentAst(options);
  } catch (TorqueAbortCompilation&) {
    // Do nothing. The relevant TorqueMessage is part of the
    // TorqueMessages contextual.
  }
  result.source_file_map = SourceFileMap::Get();
  result.language_server_data = std::move(LanguageServerData::Get());
  result.messages = std::move(TorqueMessages::Get());
  return result;
}
References v8::internal::torque::anonymous_namespace{torque-compiler.cc}::CompileCurrentAst(), v8::internal::torque::TorqueCompilerOptions::force_32bit_output, v8::base::ContextualVariable< Derived, VarType >::Get(), v8::internal::compiler::turboshaft::Get(), v8::internal::torque::SourceId::Invalid(), v8::internal::torque::anonymous_namespace{torque-compiler.cc}::ReadAndParseTorqueFile(), v8::base::internal::result, and v8::internal::torque::TorqueCompilerOptions::v8_root.
CompileTorqueForKythe()
V8_EXPORT_PRIVATE TorqueCompilerResult v8::internal::torque::CompileTorqueForKythe (std::vector< TorqueCompilationUnit > units, TorqueCompilerOptions options, KytheConsumer * consumer)
Definition at line 168 of file torque-compiler.cc.
                             {
  TargetArchitecture::Scope target_architecture(options.force_32bit_output);
  SourceFileMap::Scope source_map_scope(options.v8_root);
  CurrentSourceFile::Scope unknown_source_file_scope(SourceId::Invalid());
  CurrentAst::Scope ast_scope;
  TorqueMessages::Scope messages_scope;
  LanguageServerData::Scope server_data_scope;
  KytheData::Scope kythe_scope;
  KytheData::Get().SetConsumer(consumer);
  TorqueCompilerResult result;
  try {
    for (const auto& unit : units) {
      SourceId source_id = SourceFileMap::AddSource(unit.source_file_path);
      CurrentSourceFile::Scope source_id_scope(source_id);
      ParseTorque(unit.file_content);
    }
    CompileCurrentAst(options);
  } catch (TorqueAbortCompilation&) {
    // Do nothing. The relevant TorqueMessage is part of the
    // TorqueMessages contextual.
  }
  result.source_file_map = SourceFileMap::Get();
  result.language_server_data = std::move(LanguageServerData::Get());
  result.messages = std::move(TorqueMessages::Get());
  return result;
}
References v8::internal::torque::SourceFileMap::AddSource(), v8::internal::torque::anonymous_namespace{torque-compiler.cc}::CompileCurrentAst(), v8::internal::torque::TorqueCompilerOptions::force_32bit_output, v8::base::ContextualVariable< Derived, VarType >::Get(), v8::internal::compiler::turboshaft::Get(), v8::internal::torque::SourceId::Invalid(), ParseTorque(), v8::base::internal::result, and v8::internal::torque::TorqueCompilerOptions::v8_root.
ComputeConstraints()
std::vector< TypeConstraint > v8::internal::torque::ComputeConstraints (Scope * scope, const GenericParameters & parameters)
Definition at line 130 of file declarable.cc.
                                                       {
  CurrentScope::Scope scope_scope(scope);
  std::vector<TypeConstraint> result;
  for (const GenericParameter& parameter : parameters) {
    if (parameter.constraint) {
      result.push_back(TypeConstraint::SubtypeConstraint(
          TypeVisitor::ComputeType(*parameter.constraint)));
    } else {
      result.push_back(TypeConstraint::Unconstrained());
    }
  }
  return result;
}
References v8::internal::torque::TypeVisitor::ComputeType(), v8::base::internal::result, v8::internal::torque::TypeConstraint::SubtypeConstraint(), and v8::internal::torque::TypeConstraint::Unconstrained().
Referenced by v8::internal::torque::GenericDeclarable< SpecializationType, DeclarationType >::Constraints().
CountBlockPredecessors()
std::vector<std::size_t> v8::internal::torque::CountBlockPredecessors (const ControlFlowGraph & cfg)
Definition at line 163 of file cfg.cc.
                                                                         {
  std::vector<std::size_t> count(cfg.NumberOfBlockIds(), 0);
  count[cfg.start()->id()] = 1;
  for (const Block* block : cfg.blocks()) {
    std::vector<Block*> successors;
    for (const auto& instruction : block->instructions()) {
      instruction->AppendSuccessorBlocks(&successors);
    }
    for (Block* successor : successors) {
      DCHECK_LT(successor->id(), count.size());
      ++count[successor->id()];
    }
  }
  return count;
}
References v8::internal::torque::ControlFlowGraph::blocks(), DCHECK_LT, v8::internal::torque::Block::id(), v8::internal::torque::ControlFlowGraph::NumberOfBlockIds(), and v8::internal::torque::ControlFlowGraph::start().
Referenced by v8::internal::torque::CfgAssembler::OptimizeCfg().
CurrentNamespace()
Namespace* v8::internal::torque::CurrentNamespace () [inline]
Definition at line 230 of file declarable.h.
                                     {
  Scope* scope = CurrentScope::Get();
  while (true) {
    if (Namespace* n = Namespace::DynamicCast(scope)) {
      return n;
    }
    scope = scope->ParentScope();
  }
}
References v8::internal::compiler::turboshaft::Get(), and v8::internal::torque::Declarable::ParentScope().
Referenced by v8::internal::torque::TypeOracle::GetBitFieldStructType(), v8::internal::torque::TypeOracle::GetClassType(), and v8::internal::torque::TypeOracle::GetStructType().
DashifyString()
std::string v8::internal::torque::DashifyString (const std::string & underscore_string)
Definition at line 308 of file utils.cc.
                                                            {
  std::string result = underscore_string;
  std::replace(result.begin(), result.end(), '_', '-');
  return result;
}
References v8::base::internal::result, and v8::internal::string.
DECLARE_CONTEXTUAL_VARIABLE() [1/7]
v8::internal::torque::DECLARE_CONTEXTUAL_VARIABLE (CurrentAst , Ast)
DECLARE_CONTEXTUAL_VARIABLE() [2/7]
v8::internal::torque::DECLARE_CONTEXTUAL_VARIABLE (CurrentScope , Scope *)
DECLARE_CONTEXTUAL_VARIABLE() [3/7]
v8::internal::torque::DECLARE_CONTEXTUAL_VARIABLE (CurrentSourceFile , SourceId)
DECLARE_CONTEXTUAL_VARIABLE() [4/7]
v8::internal::torque::DECLARE_CONTEXTUAL_VARIABLE (CurrentSourcePosition , SourcePosition)
DECLARE_CONTEXTUAL_VARIABLE() [5/7]
v8::internal::torque::DECLARE_CONTEXTUAL_VARIABLE (DiagnosticsFiles , std::vector< SourceId >)
DECLARE_CONTEXTUAL_VARIABLE() [6/7]
v8::internal::torque::DECLARE_CONTEXTUAL_VARIABLE (TorqueFileList , std::vector< std::string >)
DECLARE_CONTEXTUAL_VARIABLE() [7/7]
v8::internal::torque::DECLARE_CONTEXTUAL_VARIABLE (TorqueMessages , std::vector< TorqueMessage >)
DeclareMethods()
void v8::internal::torque::DeclareMethods (AggregateType * container_type, const std::vector< Declaration * > & methods)
Definition at line 106 of file type-visitor.cc.
                                                            {
  for (auto declaration : methods) {
    CurrentSourcePosition::Scope pos_scope(declaration->pos);
    TorqueMacroDeclaration* method =
        TorqueMacroDeclaration::DynamicCast(declaration);
    Signature signature = TypeVisitor::MakeSignature(method);
    signature.parameter_names.insert(
        signature.parameter_names.begin() + signature.implicit_count,
        MakeNode<Identifier>(kThisParameterName));
    Statement* body = *(method->body);
    const std::string& method_name(method->name->value);
    signature.parameter_types.types.insert(
        signature.parameter_types.types.begin() + signature.implicit_count,
        container_type);
    Method* m = Declarations::CreateMethod(container_type, method_name,
                                           signature, body);
    m->SetPosition(method->pos);
    m->SetIdentifierPosition(method->name->pos);
  }
}
References v8::internal::torque::TorqueMacroDeclaration::body, v8::internal::torque::Declarations::CreateMethod(), v8::internal::torque::Signature::implicit_count, kThisParameterName, v8::internal::torque::TypeVisitor::MakeSignature(), v8::internal::torque::CallableDeclaration::name, v8::internal::torque::Signature::parameter_names, v8::internal::torque::Signature::parameter_types, v8::internal::torque::AstNode::pos, v8::internal::torque::Declarable::SetIdentifierPosition(), v8::internal::torque::Declarable::SetPosition(), v8::internal::string, v8::internal::torque::ParameterTypes::types, and v8::internal::torque::Identifier::value.
Referenced by v8::internal::torque::TypeVisitor::VisitClassFieldsAndMethods(), and v8::internal::torque::TypeVisitor::VisitStructMethods().
DefaultAction()
std::optional<ParseResult> v8::internal::torque::DefaultAction (ParseResultIterator * child_results) [inline]
Definition at line 196 of file earley-parser.h.
                                        {
  if (!child_results->HasNext()) return std::nullopt;
  return child_results->Next();
}
References v8::internal::torque::ParseResultIterator::HasNext(), and v8::internal::torque::ParseResultIterator::Next().
DereferenceIfPointer() [1/2]
template<class T >
T&& v8::internal::torque::DereferenceIfPointer (T && x)
Definition at line 125 of file utils.h.
                                {
  return std::forward<T>(x);
}
DereferenceIfPointer() [2/2]
template<class T >
T& v8::internal::torque::DereferenceIfPointer (T * x)
Definition at line 121 of file utils.h.
                              {
  return *x;
}
EraseIf()
template<class Container , class F >
void v8::internal::torque::EraseIf (Container * container, F f)
Definition at line 328 of file utils.h.
                                        {
  for (auto it = container->begin(); it != container->end();) {
    if (f(*it)) {
      it = container->erase(it);
    } else {
      ++it;
    }
  }
}
Referenced by v8::internal::torque::UnionType::Extend().
Error()
template<class... Args>
MessageBuilder v8::internal::torque::Error (Args &&... args)
Definition at line 81 of file utils.h.
                                     {
  return Message(TorqueMessage::Kind::kError, std::forward<Args>(args)...);
}
References v8::base::args, v8::internal::torque::TorqueMessage::kError, and Message().
Referenced by v8::internal::torque::anonymous_namespace{torque-parser.cc}::AddConstexpr(), v8::internal::torque::GenericDeclarable< SpecializationType, DeclarationType >::AddSpecialization(), v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::BuildInstanceTypeTree(), v8::internal::torque::ImplementationVisitor::CheckInitializersWellformed(), v8_inspector::clientMirror(), v8::internal::torque::ClassType::ComputeArraySlotKind(), v8::internal::torque::TypeVisitor::ComputeType(), v8_inspector::anonymous_namespace{v8-console-message.cc}::consoleAPITypeValue(), v8_inspector::ValueMirror::create(), v8::internal::torque::DeclarationVisitor::CreateBuiltin(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::DeprecatedMakeVoidType(), v8::internal::torque::ImplementationVisitor::GenerateAssignToLocation(), v8::internal::torque::ImplementationVisitor::GenerateCall(), v8::internal::torque::ImplementationVisitor::GenerateFieldAccess(), v8::internal::torque::Field::GetFieldSizeInformation(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::AnnotationSet::GetIntParam(), v8::internal::torque::LocalValue::GetLocationReference(), v8::internal::torque::ImplementationVisitor::GetLocationReference(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::FieldOffsetsGenerator::GetSectionFor(), v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::DebugFieldType::GetSize(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::AnnotationSet::GetStringParam(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::GetTypeNameForAccessor(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::anonymous_namespace{torque-parser.cc}::HasAnnotation(), v8::internal::Genesis::InstallSpecialObjects(), v8::internal::torque::MacroDeclaration::MacroDeclaration(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeClassDeclaration(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeClassField(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeEnumDeclaration(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeExternalBuiltin(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeExternalMacro(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeTryLabelExpression(), v8::internal::torque::TypeArgumentInference::MatchGeneric(), v8::internal::torque::SourceFileMap::PathFromV8RootWithoutExtension(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::ProcessTorqueImportDeclaration(), v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::PropagateInstanceTypeConstraints(), v8::internal::torque::anonymous_namespace{torque-compiler.cc}::ReadAndParseTorqueFile(), ReportError(), v8_inspector::V8ConsoleMessage::reportToFrontend(), v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::SelectOwnValues(), v8_inspector::V8DeepSerializer::serializeV8Value(), v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::SolveInstanceTypeConstraints(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::FieldOffsetsGenerator::UpdateSection(), v8::internal::torque::Field::ValidateAlignment(), v8::internal::torque::ImplementationVisitor::Visit(), v8::internal::torque::TypeVisitor::VisitClassFieldsAndMethods(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::YieldDouble(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::YieldInt32(), and v8::internal::torque::anonymous_namespace{torque-parser.cc}::YieldIntegerLiteral().
ErrorPrefixFor()
std::string v8::internal::torque::ErrorPrefixFor (TorqueMessage::Kind kind)
Definition at line 12 of file torque.cc.
                                                 {
  switch (kind) {
    case TorqueMessage::Kind::kError:
      return "Torque Error";
    case TorqueMessage::Kind::kLint:
      return "Lint error";
  }
}
References v8::internal::torque::TorqueMessage::kError, and v8::internal::torque::TorqueMessage::kLint.
Referenced by WrappedMain().
ExtractSimpleFieldArraySize()
std::optional< NameAndType > v8::internal::torque::ExtractSimpleFieldArraySize (const ClassType & class_type, Expression * array_size)
Definition at line 1433 of file types.cc.
                                                         {
  IdentifierExpression* identifier =
      IdentifierExpression::DynamicCast(array_size);
  if (!identifier || !identifier->generic_arguments.empty() ||
      !identifier->namespace_qualification.empty())
    return {};
  if (!class_type.HasField(identifier->name->value)) return {};
  return class_type.LookupField(identifier->name->value).name_and_type;
}
References v8::internal::torque::IdentifierExpression::generic_arguments, v8::internal::torque::AggregateType::HasField(), v8::internal::torque::AggregateType::LookupField(), v8::internal::torque::IdentifierExpression::name, v8::internal::torque::Field::name_and_type, v8::internal::torque::IdentifierExpression::namespace_qualification, and v8::internal::torque::Identifier::value.
Referenced by v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::anonymous_namespace{implementation-visitor.cc}::GenerateBoundsDCheck(), and v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::GetOrderedUniqueIndexFields().
FileUriDecode()
V8_EXPORT_PRIVATE std::optional< std::string > v8::internal::torque::FileUriDecode (const std::string & uri)
Definition at line 94 of file utils.cc.
                                                           {
  // Abort decoding of URIs that don't start with "file://".
  if (uri.rfind(kFileUriPrefix) != 0) return std::nullopt;
  const std::string path = uri.substr(kFileUriPrefixLength);
  std::ostringstream decoded;
  for (auto iter = path.begin(), end = path.end(); iter != end; ++iter) {
    std::string::value_type c = (*iter);
    // Normal characters are appended.
    if (c != '%') {
      decoded << c;
      continue;
    }
    // If '%' is not followed by at least two hex digits, we abort.
    if (std::distance(iter, end) <= 2) return std::nullopt;
    unsigned char first = (*++iter);
    unsigned char second = (*++iter);
    if (!isxdigit(first) || !isxdigit(second)) return std::nullopt;
    // An escaped hex value needs converting.
    unsigned char value = HexCharToInt(first) * 16 + HexCharToInt(second);
    decoded << value;
  }
  return decoded.str();
}
References v8::internal::compiler::end(), HexCharToInt(), kFileUriPrefix, kFileUriPrefixLength, v8::internal::string, v8::internal::value, and v8::internal::wasm::value_type().
Referenced by v8::internal::torque::anonymous_namespace{torque-compiler.cc}::ReadAndParseTorqueFile().
FilterDeclarables()
template<class T >
std::vector<T*> v8::internal::torque::FilterDeclarables (const std::vector< Declarable * > list)
Definition at line 25 of file declarations.h.
                                                                   {
  std::vector<T*> result;
  for (Declarable* declarable : list) {
    if (T* t = T::DynamicCast(declarable)) {
      result.push_back(t);
    }
  }
  return result;
}
References v8::base::internal::result.
FindConstraintViolation()
std::optional< std::string > v8::internal::torque::FindConstraintViolation (const std::vector< const Type * > & types, const std::vector< TypeConstraint > & constraints)
Definition at line 118 of file declarable.cc.
                                                  {
  DCHECK_EQ(constraints.size(), types.size());
  for (size_t i = 0; i < types.size(); ++i) {
    if (auto violation = constraints[i].IsViolated(types[i])) {
      return {"Could not instantiate generic, " + *violation + "."};
    }
  }
  return std::nullopt;
}
References DCHECK_EQ, and v8::internal::anonymous_namespace{json-stringifier.cc}::i.
Referenced by v8::internal::torque::GenericDeclarable< SpecializationType, DeclarationType >::AddSpecialization(), and v8::internal::torque::GenericCallable::InferSpecializationTypes().
GetConstexprName()
std::string v8::internal::torque::GetConstexprName (const std::string & name) [inline]
Definition at line 153 of file constants.h.
                                                         {
  if (IsConstexprName(name)) return name;
  return CONSTEXPR_TYPE_PREFIX + name;
}
References CONSTEXPR_TYPE_PREFIX, IsConstexprName(), and v8::internal::name.
Referenced by v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeBasicTypeExpression().
GetNonConstexprName()
std::string v8::internal::torque::GetNonConstexprName (const std::string & name) [inline]
Definition at line 148 of file constants.h.
                                                            {
  if (!IsConstexprName(name)) return name;
  return name.substr(std::strlen(CONSTEXPR_TYPE_PREFIX));
}
References CONSTEXPR_TYPE_PREFIX, IsConstexprName(), and v8::internal::name.
Referenced by v8::internal::torque::TypeVisitor::ComputeType().
GetOrCreateNamespace()
Namespace * v8::internal::torque::GetOrCreateNamespace (const std::string & name)
Definition at line 17 of file declaration-visitor.cc.
                                                       {
  std::vector<Namespace*> existing_namespaces = FilterDeclarables<Namespace>(
      Declarations::TryLookupShallow(QualifiedName(name)));
  if (existing_namespaces.empty()) {
    return Declarations::DeclareNamespace(name);
  }
  DCHECK_EQ(1, existing_namespaces.size());
  return existing_namespaces.front();
}
References DCHECK_EQ, v8::internal::torque::Declarations::DeclareNamespace(), v8::internal::name, and v8::internal::torque::Declarations::TryLookupShallow().
Referenced by v8::internal::torque::PredeclarationVisitor::Predeclare(), and v8::internal::torque::DeclarationVisitor::Visit().
hash_value()
size_t v8::internal::torque::hash_value (const TypeVector & types) [inline]
Definition at line 196 of file types.h.
                                                  {
  size_t hash = 0;
  for (const Type* t : types) {
    hash = base::hash_combine(hash, t);
  }
  return hash;
}
References v8::base::hash_combine().
HexCharToInt()
static int v8::internal::torque::HexCharToInt (unsigned char c) [static]
Definition at line 87 of file utils.cc.
                                         {
  if (isdigit(c)) return c - '0';
  if (isupper(c)) return c - 'A' + 10;
  DCHECK(islower(c));
  return c - 'a' + 10;
}
References v8::internal::DCHECK().
Referenced by FileUriDecode().
Is32BitIntegralType()
bool v8::internal::torque::Is32BitIntegralType (const Type * type)
Definition at line 1427 of file types.cc.
                                           {
  return type->IsSubtypeOf(TypeOracle::GetUint32Type()) ||
         type->IsSubtypeOf(TypeOracle::GetInt32Type()) ||
         type->IsSubtypeOf(TypeOracle::GetBoolType());
}
References v8::internal::torque::TypeOracle::GetBoolType(), v8::internal::torque::TypeOracle::GetInt32Type(), v8::internal::torque::TypeOracle::GetUint32Type(), and v8::internal::tracing::type.
Referenced by IsAllowedAsBitField().
IsAllowedAsBitField()
bool v8::internal::torque::IsAllowedAsBitField (const Type * type)
Definition at line 1410 of file types.cc.
                                           {
  if (type->IsBitFieldStructType()) {
    // No nested bitfield structs for now. We could reconsider if there's a
    // compelling use case.
    return false;
  }
  // Any integer-ish type, including bools and enums which inherit from integer
  // types, are allowed. Note, however, that we always zero-extend during
  // decoding regardless of signedness.
  return IsPointerSizeIntegralType(type) || Is32BitIntegralType(type);
}
References Is32BitIntegralType(), IsPointerSizeIntegralType(), and v8::internal::tracing::type.
Referenced by v8::internal::torque::TypeVisitor::ComputeType().
IsAnyUnsignedInteger()
bool v8::internal::torque::IsAnyUnsignedInteger (const Type * type)
Definition at line 1402 of file types.cc.
                                            {
  return type == TypeOracle::GetUint32Type() ||
         type == TypeOracle::GetUint31Type() ||
         type == TypeOracle::GetUint16Type() ||
         type == TypeOracle::GetUint8Type() ||
         type == TypeOracle::GetUIntPtrType();
}
References v8::internal::torque::TypeOracle::GetUint16Type(), v8::internal::torque::TypeOracle::GetUint31Type(), v8::internal::torque::TypeOracle::GetUint32Type(), v8::internal::torque::TypeOracle::GetUint8Type(), v8::internal::torque::TypeOracle::GetUIntPtrType(), and v8::internal::tracing::type.
Referenced by v8::internal::torque::TypeVisitor::ComputeType().
IsAssignableFrom()
bool v8::internal::torque::IsAssignableFrom (const Type * to, const Type * from)
Definition at line 1169 of file types.cc.
                                                        {
  if (to == from) return true;
  if (from->IsSubtypeOf(to)) return true;
  return TypeOracle::ImplicitlyConvertableFrom(to, from).has_value();
}
References v8::internal::torque::TypeOracle::ImplicitlyConvertableFrom(), and v8::internal::torque::Type::IsSubtypeOf().
Referenced by v8::internal::torque::ParameterDifference::AddParameter(), v8::internal::torque::ImplementationVisitor::GenerateImplicitConvert(), v8::internal::torque::ImplementationVisitor::GetCommonType(), and IsCompatibleSignature().
IsCompatibleSignature()
bool v8::internal::torque::IsCompatibleSignature (const Signature & sig, const TypeVector & types, size_t label_count)
Definition at line 3491 of file implementation-visitor.cc.
                                               {
  auto i = sig.parameter_types.types.begin() + sig.implicit_count;
  if ((sig.parameter_types.types.size() - sig.implicit_count) > types.size())
    return false;
  if (sig.labels.size() != label_count) return false;
  for (auto current : types) {
    if (i == sig.parameter_types.types.end()) {
      if (!sig.parameter_types.var_args) return false;
      if (!IsAssignableFrom(TypeOracle::GetObjectType(), current)) return false;
    } else {
      if (!IsAssignableFrom(*i++, current)) return false;
    }
  }
  return true;
}
References IsAssignableFrom(), and v8::internal::sig.
Referenced by v8::internal::torque::ImplementationVisitor::GeneratePointerCall(), and v8::internal::torque::ImplementationVisitor::LookupCallable().
IsConstexprName()
bool v8::internal::torque::IsConstexprName (const std::string & name) [inline]
Definition at line 143 of file constants.h.
                                                   {
  return name.substr(0, std::strlen(CONSTEXPR_TYPE_PREFIX)) ==
         CONSTEXPR_TYPE_PREFIX;
}
References CONSTEXPR_TYPE_PREFIX, and v8::internal::name.
Referenced by v8::internal::torque::AbstractType::AbstractType(), v8::internal::torque::AbstractTypeDeclaration::AbstractTypeDeclaration(), GetConstexprName(), and GetNonConstexprName().
IsDeferred()
bool v8::internal::torque::IsDeferred (Statement * stmt) [inline]
Definition at line 1276 of file ast.h.
                                        {
  if (auto* block = BlockStatement::DynamicCast(stmt)) {
    return block->deferred;
  }
  return false;
}
Referenced by v8::internal::compiler::LiveRangeConnector::ConnectRanges(), v8::internal::compiler::FrameElider::PropagateIntoBlock(), v8::internal::compiler::LiveRangeConnector::ResolveControlFlow(), v8::internal::compiler::MoveOptimizer::Run(), v8::internal::compiler::InstructionSequence::ValidateDeferredBlockEntryPaths(), v8::internal::compiler::InstructionSequence::ValidateDeferredBlockExitPaths(), and v8::internal::torque::ImplementationVisitor::Visit().
IsLowerCamelCase()
bool v8::internal::torque::IsLowerCamelCase (const std::string & s)
Definition at line 221 of file utils.cc.
                                          {
  if (s.empty()) return false;
  size_t start = 0;
  if (s[0] == '_') start = 1;
  return islower(s[start]) && !ContainsUnderscore(s.substr(start));
}
References v8::internal::torque::anonymous_namespace{utils.cc}::ContainsUnderscore().
Referenced by v8::internal::torque::anonymous_namespace{torque-parser.cc}::AddParameter(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeCatchBlock(), and v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeVarDeclarationStatement().
IsPointerSizeIntegralType()
bool v8::internal::torque::IsPointerSizeIntegralType (const Type * type)
Definition at line 1422 of file types.cc.
                                                 {
  return type->IsSubtypeOf(TypeOracle::GetUIntPtrType()) ||
         type->IsSubtypeOf(TypeOracle::GetIntPtrType());
}
References v8::internal::torque::TypeOracle::GetIntPtrType(), v8::internal::torque::TypeOracle::GetUIntPtrType(), and v8::internal::tracing::type.
Referenced by IsAllowedAsBitField().
IsSnakeCase()
bool v8::internal::torque::IsSnakeCase (const std::string & s)
Definition at line 235 of file utils.cc.
                                     {
  if (s.empty()) return false;
  return !ContainsUpperCase(s);
}
References v8::internal::torque::anonymous_namespace{utils.cc}::ContainsUpperCase().
Referenced by v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeNamespaceDeclaration().
IsUpperCamelCase()
bool v8::internal::torque::IsUpperCamelCase (const std::string & s)
Definition at line 228 of file utils.cc.
                                          {
  if (s.empty()) return false;
  size_t start = 0;
  if (s[0] == '_') start = 1;
  return isupper(s[start]);
}
Referenced by IsValidNamespaceConstName(), IsValidTypeName(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::LintGenericParameters(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeLabelAndTypes(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeLabelBlock(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeMethodDeclaration(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeTorqueBuiltinDeclaration(), and v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeTorqueMacroDeclaration().
IsValidNamespaceConstName()
bool v8::internal::torque::IsValidNamespaceConstName (const std::string & s)
Definition at line 240 of file utils.cc.
                                                   {
  if (s.empty()) return false;
  if (IsKeywordLikeName(s)) return true;
  return s[0] == 'k' && IsUpperCamelCase(s.substr(1));
}
References v8::internal::torque::anonymous_namespace{utils.cc}::IsKeywordLikeName(), and IsUpperCamelCase().
Referenced by v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeConstDeclaration().
IsValidTypeName()
bool v8::internal::torque::IsValidTypeName (const std::string & s)
Definition at line 247 of file utils.cc.
                                         {
  if (s.empty()) return false;
  if (IsMachineType(s)) return true;
  return IsUpperCamelCase(s);
}
References v8::internal::torque::anonymous_namespace{utils.cc}::IsMachineType(), and IsUpperCamelCase().
Referenced by v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeAbstractTypeDeclaration(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeBitFieldStructDeclaration(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeClassDeclaration(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeEnumDeclaration(), and v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeStructDeclaration().
Lint()
template<class... Args>
MessageBuilder v8::internal::torque::Lint (Args &&... args)
Definition at line 85 of file utils.h.
                                    {
  return Message(TorqueMessage::Kind::kLint, std::forward<Args>(args)...);
}
References v8::base::args, v8::internal::torque::TorqueMessage::kLint, and Message().
Referenced by v8::internal::torque::anonymous_namespace{torque-parser.cc}::AnnotationSet::AnnotationSet(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::CheckNotDeferredStatement(), v8::internal::torque::TypeVisitor::ComputeType(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeClassDeclaration(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeEnumDeclaration(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::NamingConventionError(), ReportAllUnusedMacros(), v8::internal::torque::ImplementationVisitor::Visit(), and v8::internal::torque::Binding< T >::~Binding().
LoweredSlotCount()
size_t v8::internal::torque::LoweredSlotCount (const Type * type)
Definition at line 1216 of file types.cc.
{ return LowerType(type).size(); }
References LowerType(), and v8::internal::tracing::type.
Referenced by v8::internal::torque::ImplementationVisitor::GenerateCall(), v8::internal::torque::ImplementationVisitor::GenerateFetchFromLocation(), v8::internal::torque::ImplementationVisitor::GeneratePointerCall(), v8::internal::torque::ImplementationVisitor::GetLocationReference(), v8::internal::torque::CCGenerator::ProcessArgumentsCommon(), v8::internal::torque::CSAGenerator::ProcessArgumentsCommon(), ProjectStructField(), and v8::internal::torque::ImplementationVisitor::Visit().
LowerParameterTypes() [1/2]
TypeVector v8::internal::torque::LowerParameterTypes (const ParameterTypes & parameter_types, size_t arg_count)
Definition at line 1226 of file types.cc.
                                                 {
  std::vector<const Type*> result = LowerParameterTypes(parameter_types.types);
  for (size_t i = parameter_types.types.size(); i < arg_count; ++i) {
    DCHECK(parameter_types.var_args);
    AppendLoweredTypes(TypeOracle::GetObjectType(), &result);
  }
  return result;
}
References v8::internal::torque::anonymous_namespace{types.cc}::AppendLoweredTypes(), v8::internal::DCHECK(), v8::internal::torque::TypeOracle::GetObjectType(), LowerParameterTypes(), v8::base::internal::result, v8::internal::torque::ParameterTypes::types, and v8::internal::torque::ParameterTypes::var_args.
LowerParameterTypes() [2/2]
TypeVector v8::internal::torque::LowerParameterTypes (const TypeVector & parameters)
Definition at line 1218 of file types.cc.
                                                             {
  std::vector<const Type*> result;
  for (const Type* t : parameters) {
    AppendLoweredTypes(t, &result);
  }
  return result;
}
References v8::internal::torque::anonymous_namespace{types.cc}::AppendLoweredTypes(), and v8::base::internal::result.
Referenced by v8::internal::torque::ImplementationVisitor::GenerateCall(), v8::internal::torque::CallCsaMacroAndBranchInstruction::GetLabelValueDefinitionCount(), and LowerParameterTypes().
LowerType()
TypeVector v8::internal::torque::LowerType (const Type * type)
Definition at line 1210 of file types.cc.
                                       {
  TypeVector result;
  AppendLoweredTypes(type, &result);
  return result;
}
References v8::internal::torque::anonymous_namespace{types.cc}::AppendLoweredTypes(), v8::base::internal::result, and v8::internal::tracing::type.
Referenced by v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::AddParameter(), v8::internal::torque::ImplementationVisitor::GenerateBuiltinDefinitionsAndInterfaceDescriptors(), v8::internal::torque::ImplementationVisitor::GenerateCSATypes(), v8::internal::torque::NamespaceConstantInstruction::GetValueDefinitionCount(), v8::internal::torque::CallIntrinsicInstruction::GetValueDefinitionCount(), v8::internal::torque::CallCsaMacroInstruction::GetValueDefinitionCount(), v8::internal::torque::CallCsaMacroAndBranchInstruction::GetValueDefinitionCount(), v8::internal::torque::CallBuiltinInstruction::GetValueDefinitionCount(), v8::internal::torque::CallBuiltinPointerInstruction::GetValueDefinitionCount(), v8::internal::torque::CallRuntimeInstruction::GetValueDefinitionCount(), v8::internal::torque::ImplementationVisitor::InlineMacro(), LoweredSlotCount(), v8::internal::torque::CfgAssembler::Peek(), v8::internal::torque::CfgAssembler::Poke(), v8::internal::torque::ImplementationVisitor::Visit(), and v8::internal::torque::ImplementationVisitor::VisitMacroCommon().
MachineTypeString()
std::string v8::internal::torque::MachineTypeString (const Type * type)
Definition at line 3617 of file implementation-visitor.cc.
                                              {
  if (type->IsSubtypeOf(TypeOracle::GetSmiType())) {
    return "MachineType::TaggedSigned()";
  }
  if (type->IsSubtypeOf(TypeOracle::GetHeapObjectType())) {
    return "MachineType::TaggedPointer()";
  }
  if (type->IsSubtypeOf(TypeOracle::GetTaggedType())) {
    return "MachineType::AnyTagged()";
  }
  return "MachineTypeOf<" + type->GetGeneratedTNodeTypeName() + ">::value";
}
References v8::internal::tracing::type.
Referenced by v8::internal::torque::ImplementationVisitor::GenerateBuiltinDefinitionsAndInterfaceDescriptors().
MakeBasicTypeExpression()
BasicTypeExpression* v8::internal::torque::MakeBasicTypeExpression (std::vector< std::string > namespace_qualification, Identifier * name, std::vector< TypeExpression * > generic_arguments = {}) [inline]
Definition at line 1330 of file ast.h.
                                                   {}) {
  return MakeNode<BasicTypeExpression>(std::move(namespace_qualification), name,
                                       std::move(generic_arguments));
}
MakeCallExpression() [1/2]
CallExpression* v8::internal::torque::MakeCallExpression (IdentifierExpression * callee, std::vector< Expression * > arguments, std::vector< Identifier * > labels = {}) [inline]
Definition at line 1309 of file ast.h.
                                    {}) {
  return MakeNode<CallExpression>(callee, std::move(arguments),
                                  std::move(labels));
}
Referenced by v8::internal::torque::ClassType::GenerateSliceAccessor().
MakeCallExpression() [2/2]
CallExpression* v8::internal::torque::MakeCallExpression (std::string callee, std::vector< Expression * > arguments, std::vector< Identifier * > labels = {}) [inline]
Definition at line 1316 of file ast.h.
                                    {}) {
  return MakeCallExpression(MakeIdentifierExpression(std::move(callee)),
                            std::move(arguments), std::move(labels));
}
MakeConstDeclarationStatement()
VarDeclarationStatement* v8::internal::torque::MakeConstDeclarationStatement (std::string name, Expression * initializer) [inline]
Definition at line 1323 of file ast.h.
                                             {
  return MakeNode<VarDeclarationStatement>(
      /*const_qualified=*/true, MakeNode<Identifier>(std::move(name)),
      std::optional<TypeExpression*>{}, initializer);
}
References v8::internal::torque::CallableDeclaration::name.
Referenced by v8::internal::torque::ClassType::GenerateSliceAccessor().
MakeFieldAccessExpression()
FieldAccessExpression* v8::internal::torque::MakeFieldAccessExpression (Expression * object, std::string field) [inline]
Definition at line 1291 of file ast.h.
                                                                         {
  return MakeNode<FieldAccessExpression>(
      object, MakeNode<Identifier>(std::move(field)));
}
Referenced by v8::internal::torque::ClassType::GenerateAccessors(), and v8::internal::torque::ClassType::GenerateSliceAccessor().
MakeIdentifierExpression() [1/2]
IdentifierExpression* v8::internal::torque::MakeIdentifierExpression (std::string name) [inline]
Definition at line 1305 of file ast.h.
                                                                      {
  return MakeIdentifierExpression({}, std::move(name));
}
References MakeIdentifierExpression(), and v8::internal::torque::CallableDeclaration::name.
MakeIdentifierExpression() [2/2]
IdentifierExpression* v8::internal::torque::MakeIdentifierExpression (std::vector< std::string > namespace_qualification, std::string name, std::vector< TypeExpression * > args = {}) [inline]
Definition at line 1297 of file ast.h.
                                      {}) {
  return MakeNode<IdentifierExpression>(std::move(namespace_qualification),
                                        MakeNode<Identifier>(std::move(name)),
                                        std::move(args));
}
Referenced by v8::internal::torque::ClassType::GenerateAccessors(), v8::internal::torque::ClassType::GenerateSliceAccessor(), and MakeIdentifierExpression().
MakeNode()
template<class T , class... Args>
T* v8::internal::torque::MakeNode (Args... args)
Definition at line 1286 of file ast.h.
                          {
  return CurrentAst::Get().AddNode(
      std::make_unique<T>(CurrentSourcePosition::Get(), std::move(args)...));
}
References v8::base::args, and v8::internal::compiler::turboshaft::Get().
Referenced by v8::internal::compiler::BytecodeGraphBuilder::BuildCall(), and v8::internal::compiler::BytecodeGraphBuilder::ProcessCallRuntimeArguments().
MakeStructExpression()
StructExpression* v8::internal::torque::MakeStructExpression (TypeExpression * type, std::vector< NameAndExpression > initializers) [inline]
Definition at line 1337 of file ast.h.
                                                                     {
  return MakeNode<StructExpression>(type, std::move(initializers));
}
References v8::internal::tracing::type.
MatchSimpleBodyDescriptor()
std::optional<std::string> v8::internal::torque::MatchSimpleBodyDescriptor (const ClassType * type)
Definition at line 5107 of file implementation-visitor.cc.
                                                                        {
  std::vector<ObjectSlotKind> slots = type->ComputeHeaderSlotKinds();
  if (!type->HasStaticSize()) {
    slots.push_back(*type->ComputeArraySlotKind());
  }
  // Skip the map slot.
  size_t i = 1;
  while (i < slots.size() && slots[i] == ObjectSlotKind::kNoPointer) ++i;
  if (i == slots.size()) return "DataOnlyBodyDescriptor";
  bool has_weak_pointers = false;
  size_t start_index = i;
  for (; i < slots.size(); ++i) {
    if (slots[i] == ObjectSlotKind::kStrongPointer) {
      continue;
    } else if (slots[i] == ObjectSlotKind::kMaybeObjectPointer) {
      has_weak_pointers = true;
    } else if (slots[i] == ObjectSlotKind::kNoPointer) {
      break;
    } else {
      return std::nullopt;
    }
  }
  size_t end_index = i;
  for (; i < slots.size(); ++i) {
    if (slots[i] != ObjectSlotKind::kNoPointer) return std::nullopt;
  }
  size_t start_offset = start_index * TargetArchitecture::TaggedSize();
  size_t end_offset = end_index * TargetArchitecture::TaggedSize();
  // We pick a suffix-range body descriptor even in cases where the object size
  // is fixed, to reduce the amount of code executed for object visitation.
  if (end_index == slots.size()) {
    return ToString("SuffixRange", has_weak_pointers ? "Weak" : "",
                    "BodyDescriptor<", start_offset, ">");
  }
  if (!has_weak_pointers) {
    return ToString("FixedRangeBodyDescriptor<", start_offset, ", ", end_offset,
                    ">");
  }
  return std::nullopt;
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::ToString(), and v8::internal::tracing::type.
Referenced by v8::internal::torque::ImplementationVisitor::GenerateBodyDescriptors().
Message()
template<class... Args>
static MessageBuilder v8::internal::torque::Message (TorqueMessage::Kind kind, Args &&... args) [static]
Definition at line 76 of file utils.h.
                                                                      {
  return MessageBuilder(ToString(std::forward<Args>(args)...), kind);
}
References v8::base::args, and ToString().
Referenced by Error(), and Lint().
operator<()
bool v8::internal::torque::operator< (const Type & a, const Type & b)
Definition at line 1175 of file types.cc.
{ return a.id() < b.id(); }
References v8::internal::torque::Type::id().
operator<<() [1/45]
std::ostream& v8::internal::torque::operator<< (base::CheckMessageStream & os, const Type * t) [inline]
Definition at line 828 of file types.h.
                                                                         {
  return os << static_cast<const void*>(t);
}
operator<<() [2/45]
std::ostream& v8::internal::torque::operator<< (std::ostream & os, const AbortInstruction & instruction) [inline]
Definition at line 754 of file instructions.h.
                                                                     {
  return os << "Abort " << AbortInstruction::KindToString(instruction.kind)
            << ", " << StringLiteralQuote(instruction.message);
}
References v8::internal::torque::AbortInstruction::kind, v8::internal::torque::AbortInstruction::KindToString(), v8::internal::torque::AbortInstruction::message, and StringLiteralQuote().
operator<<() [3/45]
std::ostream & v8::internal::torque::operator<< (std::ostream & os, const BranchInstruction & instruction)
Definition at line 607 of file instructions.cc.
                                                               {
  return os << "Branch true: " << instruction.if_true->id()
            << ", false: " << instruction.if_false->id();
}
References v8::internal::torque::Block::id(), v8::internal::torque::BranchInstruction::if_false, and v8::internal::torque::BranchInstruction::if_true.
operator<<() [4/45]
std::ostream & v8::internal::torque::operator<< (std::ostream & os, const Builtin & b)
Definition at line 58 of file declarable.cc.
                                                         {
  os << "builtin " << *b.signature().return_type << " " << b.ReadableName()
     << b.signature().parameter_types;
  return os;
}
References v8::internal::torque::Signature::parameter_types, v8::internal::torque::Callable::ReadableName(), v8::internal::torque::Signature::return_type, and v8::internal::torque::Callable::signature().
operator<<() [5/45]
std::ostream & v8::internal::torque::operator<< (std::ostream & os, const Callable & m)
Definition at line 37 of file declarable.cc.
                                                          {
  os << "callable " << m.ReadableName() << "(";
  if (m.signature().implicit_count != 0) {
    os << "implicit ";
    TypeVector implicit_parameter_types(
        m.signature().parameter_types.types.begin(),
        m.signature().parameter_types.types.begin() +
            m.signature().implicit_count);
    os << implicit_parameter_types << ")(";
    TypeVector explicit_parameter_types(
        m.signature().parameter_types.types.begin() +
            m.signature().implicit_count,
        m.signature().parameter_types.types.end());
    os << explicit_parameter_types;
  } else {
    os << m.signature().parameter_types;
  }
  os << "): " << *m.signature().return_type;
  return os;
}
References v8::internal::torque::Signature::implicit_count, v8::internal::torque::Signature::parameter_types, v8::internal::torque::Callable::ReadableName(), v8::internal::torque::Signature::return_type, v8::internal::torque::Callable::signature(), and v8::internal::torque::ParameterTypes::types.
operator<<() [6/45]
std::ostream & v8::internal::torque::operator<< (std::ostream & os, const CallBuiltinInstruction & instruction)
Definition at line 504 of file instructions.cc.
                                                                    {
  os << "CallBuiltin " << instruction.builtin->ReadableName()
     << ", argc: " << instruction.argc;
  if (instruction.is_tailcall) {
    os << ", is_tailcall";
  }
  if (instruction.catch_block) {
    os << ", catch block " << (*instruction.catch_block)->id();
  }
  return os;
}
References v8::internal::torque::CallBuiltinInstruction::argc, v8::internal::torque::CallBuiltinInstruction::builtin, v8::internal::torque::CallBuiltinInstruction::catch_block, v8::internal::torque::CallBuiltinInstruction::is_tailcall, and v8::internal::torque::Callable::ReadableName().
operator<<() [7/45]
std::ostream& v8::internal::torque::operator<< (std::ostream & os, const CallBuiltinPointerInstruction & instruction) [inline]
Definition at line 595 of file instructions.h.
                                                                      {
  os << "CallBuiltinPointer " << *instruction.type
     << ", argc: " << instruction.argc;
  if (instruction.is_tailcall) {
    os << ", is_tailcall";
  }
  return os;
}
References v8::internal::torque::CallBuiltinPointerInstruction::argc, v8::internal::torque::CallBuiltinPointerInstruction::is_tailcall, and v8::internal::torque::CallBuiltinPointerInstruction::type.
operator<<() [8/45]
std::ostream & v8::internal::torque::operator<< (std::ostream & os, const CallCsaMacroAndBranchInstruction & instruction)
Definition at line 400 of file instructions.cc.
                                                                              {
  os << "CallCsaMacroAndBranch " << instruction.macro->ReadableName();
  os << "(";
  PrintCommaSeparatedList(os, instruction.constexpr_arguments);
  os << ")";
  if (instruction.return_continuation) {
    os << ", return continuation " << (*instruction.return_continuation)->id();
  }
  if (!instruction.label_blocks.empty()) {
    os << ", label blocks ";
    PrintCommaSeparatedList(os, instruction.label_blocks,
                            [](Block* block) { return block->id(); });
  }
  if (instruction.catch_block) {
    os << ", catch block " << (*instruction.catch_block)->id();
  }
  return os;
}
References v8::internal::torque::CallCsaMacroAndBranchInstruction::catch_block, v8::internal::torque::CallCsaMacroAndBranchInstruction::constexpr_arguments, v8::internal::torque::CallCsaMacroAndBranchInstruction::label_blocks, v8::internal::torque::CallCsaMacroAndBranchInstruction::macro, PrintCommaSeparatedList(), v8::internal::torque::Callable::ReadableName(), and v8::internal::torque::CallCsaMacroAndBranchInstruction::return_continuation.
operator<<() [9/45]
std::ostream & v8::internal::torque::operator<< (std::ostream & os, const CallCsaMacroInstruction & instruction)
Definition at line 268 of file instructions.cc.
                                                                     {
  os << "CallCsaMacro " << instruction.macro->ReadableName();
  os << "(";
  PrintCommaSeparatedList(os, instruction.constexpr_arguments);
  os << ")";
  if (instruction.catch_block) {
    os << ", catch block " << (*instruction.catch_block)->id();
  }
  return os;
}
References v8::internal::torque::CallCsaMacroInstruction::catch_block, v8::internal::torque::CallCsaMacroInstruction::constexpr_arguments, v8::internal::torque::CallCsaMacroInstruction::macro, PrintCommaSeparatedList(), and v8::internal::torque::Callable::ReadableName().
operator<<() [10/45]
std::ostream & v8::internal::torque::operator<< (std::ostream & os, const CallIntrinsicInstruction & instruction)
Definition at line 192 of file instructions.cc.
                                                                      {
  os << "CallIntrinsic " << instruction.intrinsic->ReadableName();
  if (!instruction.specialization_types.empty()) {
    os << "<";
    PrintCommaSeparatedList(
        os, instruction.specialization_types,
        [](const Type* type) -> const Type& { return *type; });
    os << ">";
  }
  os << "(";
  PrintCommaSeparatedList(os, instruction.constexpr_arguments);
  os << ")";
  return os;
}
References v8::internal::torque::CallIntrinsicInstruction::constexpr_arguments, v8::internal::torque::CallIntrinsicInstruction::intrinsic, PrintCommaSeparatedList(), v8::internal::torque::Callable::ReadableName(), v8::internal::torque::CallIntrinsicInstruction::specialization_types, and v8::internal::tracing::type.
operator<<() [11/45]
std::ostream & v8::internal::torque::operator<< (std::ostream & os, const CallRuntimeInstruction & instruction)
Definition at line 577 of file instructions.cc.
                                                                    {
  os << "CallRuntime " << instruction.runtime_function->ReadableName()
     << ", argc: " << instruction.argc;
  if (instruction.is_tailcall) {
    os << ", is_tailcall";
  }
  if (instruction.catch_block) {
    os << ", catch block " << (*instruction.catch_block)->id();
  }
  return os;
}
References v8::internal::torque::CallRuntimeInstruction::argc, v8::internal::torque::CallRuntimeInstruction::catch_block, v8::internal::torque::CallRuntimeInstruction::is_tailcall, v8::internal::torque::Callable::ReadableName(), and v8::internal::torque::CallRuntimeInstruction::runtime_function.
operator<<() [12/45]
std::ostream & v8::internal::torque::operator<< (std::ostream & os, const ConstexprBranchInstruction & instruction)
Definition at line 625 of file instructions.cc.
                                                                        {
  return os << "ConstexprBranch " << instruction.condition
            << ", true: " << instruction.if_true->id()
            << ", false: " << instruction.if_false->id();
}
References v8::internal::torque::ConstexprBranchInstruction::condition, v8::internal::torque::Block::id(), v8::internal::torque::ConstexprBranchInstruction::if_false, and v8::internal::torque::ConstexprBranchInstruction::if_true.
operator<<() [13/45]
std::ostream& v8::internal::torque::operator<< (std::ostream & os, const DeleteRangeInstruction & instruction) [inline]
Definition at line 327 of file instructions.h.
                                                                           {
  return os << "DeleteRange " << instruction.range;
}
References v8::internal::torque::DeleteRangeInstruction::range.
operator<<() [14/45]
std::ostream & v8::internal::torque::operator<< (std::ostream & os, const Field & field)
Definition at line 1101 of file types.cc.
                                                           {
  os << field.name_and_type;
  if (field.custom_weak_marking) {
    os << " (custom weak)";
  }
  return os;
}
References v8::internal::torque::Field::custom_weak_marking, and v8::internal::torque::Field::name_and_type.
operator<<() [15/45]
std::ostream & v8::internal::torque::operator<< (std::ostream & os, const GenericCallable & g)
Definition at line 70 of file declarable.cc.
                                                                 {
  os << "generic " << g.name() << "<";
  PrintCommaSeparatedList(os, g.generic_parameters(),
                          [](const GenericParameter& identifier) {
                            return identifier.name->value;
                          });
  os << ">";
  return os;
}
References v8::internal::torque::GenericDeclarable< SpecializationType, DeclarationType >::generic_parameters(), v8::internal::torque::GenericDeclarable< SpecializationType, DeclarationType >::name(), and PrintCommaSeparatedList().
operator<<() [16/45]
std::ostream& v8::internal::torque::operator<< (std::ostream & os, const GotoExternalInstruction & instruction) [inline]
Definition at line 697 of file instructions.h.
                                                                            {
  os << "GotoExternal " << instruction.destination;
  for (const std::string& name : instruction.variable_names) {
    os << ", " << name;
  }
  return os;
}
References v8::internal::torque::GotoExternalInstruction::destination, v8::internal::name, v8::internal::string, and v8::internal::torque::GotoExternalInstruction::variable_names.
operator<<() [17/45]
std::ostream & v8::internal::torque::operator<< (std::ostream & os, const GotoInstruction & instruction)
Definition at line 642 of file instructions.cc.
                                                                           {
  return os << "Goto " << instruction.destination->id();
}
References v8::internal::torque::GotoInstruction::destination, and v8::internal::torque::Block::id().
operator<<() [18/45]
std::ostream& v8::internal::torque::operator<< (std::ostream & os, const LoadBitFieldInstruction & instruction) [inline]
Definition at line 421 of file instructions.h.
                                                                            {
  return os << "LoadBitField " << *instruction.bit_field_struct_type << ", "
            << instruction.bit_field.name_and_type.name;
}
References v8::internal::torque::LoadBitFieldInstruction::bit_field, v8::internal::torque::LoadBitFieldInstruction::bit_field_struct_type, v8::internal::torque::NameAndType::name, and v8::internal::torque::BitField::name_and_type.
operator<<() [19/45]
std::ostream& v8::internal::torque::operator<< (std::ostream & os, const LoadReferenceInstruction & instruction) [inline]
Definition at line 392 of file instructions.h.
                                                                             {
  return os << "LoadReference " << *instruction.type;
}
References v8::internal::torque::LoadReferenceInstruction::type.
operator<<() [20/45]
std::ostream & v8::internal::torque::operator<< (std::ostream & os, const MakeLazyNodeInstruction & instruction)
Definition at line 793 of file instructions.cc.
                                                                     {
  os << "MakeLazyNode " << instruction.macro->ReadableName() << ", "
     << *instruction.result_type;
  for (const std::string& arg : instruction.constexpr_arguments) {
    os << ", " << arg;
  }
  return os;
}
References v8::internal::torque::MakeLazyNodeInstruction::constexpr_arguments, v8::internal::torque::MakeLazyNodeInstruction::macro, v8::internal::torque::Callable::ReadableName(), v8::internal::torque::MakeLazyNodeInstruction::result_type, and v8::internal::string.
operator<<() [21/45]
std::ostream & v8::internal::torque::operator<< (std::ostream & os, const NameAndType & name_and_type)
Definition at line 1094 of file types.cc.
                                                                         {
  os << name_and_type.name;
  os << ": ";
  os << *name_and_type.type;
  return os;
}
References v8::internal::torque::NameAndType::name, and v8::internal::torque::NameAndType::type.
operator<<() [22/45]
std::ostream & v8::internal::torque::operator<< (std::ostream & os, const NamespaceConstantInstruction & instruction)
Definition at line 133 of file instructions.cc.
                                                                          {
  return os << "NamespaceConstant " << instruction.constant->external_name();
}
References v8::internal::torque::NamespaceConstantInstruction::constant, and v8::internal::torque::NamespaceConstant::external_name().
operator<<() [23/45]
std::ostream & v8::internal::torque::operator<< (std::ostream & os, const ParameterTypes & p)
Definition at line 1119 of file types.cc.
                                                                {
  PrintCommaSeparatedList(os, p.types);
  if (p.var_args) {
    if (!p.types.empty()) os << ", ";
    os << "...";
  }
  return os;
}
References PrintCommaSeparatedList(), v8::internal::torque::ParameterTypes::types, and v8::internal::torque::ParameterTypes::var_args.
operator<<() [24/45]
std::ostream& v8::internal::torque::operator<< (std::ostream & os, const PeekInstruction & instruction) [inline]
Definition at line 290 of file instructions.h.
                                                                    {
  os << "Peek " << instruction.slot;
  if (instruction.widened_type) {
    os << ", " << **instruction.widened_type;
  }
  return os;
}
References v8::internal::torque::PeekInstruction::slot, and v8::internal::torque::PeekInstruction::widened_type.
operator<<() [25/45]
std::ostream& v8::internal::torque::operator<< (std::ostream & os, const PokeInstruction & instruction) [inline]
Definition at line 309 of file instructions.h.
                                                                    {
  os << "Poke " << instruction.slot;
  if (instruction.widened_type) {
    os << ", " << **instruction.widened_type;
  }
  return os;
}
References v8::internal::torque::PokeInstruction::slot, and v8::internal::torque::PokeInstruction::widened_type.
operator<<() [26/45]
std::ostream& v8::internal::torque::operator<< (std::ostream & os, const PrintErrorInstruction & instruction) [inline]
Definition at line 727 of file instructions.h.
                                                                          {
  return os << "PrintConstantString "
            << StringLiteralQuote(instruction.message);
}
References v8::internal::torque::PrintErrorInstruction::message, and StringLiteralQuote().
operator<<() [27/45]
std::ostream& v8::internal::torque::operator<< (std::ostream & os, const PushBuiltinPointerInstruction & instruction) [inline]
Definition at line 359 of file instructions.h.
                                                                      {
  return os << "PushBuiltinPointer "
            << StringLiteralQuote(instruction.external_name) << ", "
            << *instruction.type;
}
References v8::internal::torque::PushBuiltinPointerInstruction::external_name, StringLiteralQuote(), and v8::internal::torque::PushBuiltinPointerInstruction::type.
operator<<() [28/45]
std::ostream& v8::internal::torque::operator<< (std::ostream & os, const PushUninitializedInstruction & instruction) [inline]
Definition at line 341 of file instructions.h.
                                                                     {
  return os << "PushUninitialized " << *instruction.type;
}
References v8::internal::torque::PushUninitializedInstruction::type.
operator<<() [29/45]
std::ostream& v8::internal::torque::operator<< (std::ostream & os, const QualifiedName & name)
Definition at line 30 of file declarable.cc.
                                                                  {
  for (const std::string& qualifier : name.namespace_qualification) {
    os << qualifier << "::";
  }
  return os << name.name;
}
operator<<() [30/45]
std::ostream& v8::internal::torque::operator<< (std::ostream & os, const ResidueClass & a)
Definition at line 390 of file utils.cc.
                                                              {
  if (a.SingleValue().has_value()) return os << *a.SingleValue();
  return os << "[" << a.value_ << " mod 2^" << a.modulus_log_2_ << "]";
}
operator<<() [31/45]
std::ostream& v8::internal::torque::operator<< (std::ostream & os, const ReturnInstruction & instruction) [inline]
Definition at line 714 of file instructions.h.
                                                                      {
  return os << "Return count: " << instruction.count;
}
References v8::internal::torque::ReturnInstruction::count.
operator<<() [32/45]
std::ostream & v8::internal::torque::operator<< (std::ostream & os, const RuntimeFunction & b)
Definition at line 64 of file declarable.cc.
                                                                 {
  os << "runtime function " << *b.signature().return_type << " "
     << b.ReadableName() << b.signature().parameter_types;
  return os;
}
References v8::internal::torque::Signature::parameter_types, v8::internal::torque::Callable::ReadableName(), v8::internal::torque::Signature::return_type, and v8::internal::torque::Callable::signature().
operator<<() [33/45]
std::ostream & v8::internal::torque::operator<< (std::ostream & os, const Signature & sig)
Definition at line 1109 of file types.cc.
                                                             {
  PrintSignature(os, sig, true);
  return os;
}
References PrintSignature(), and v8::internal::sig.
operator<<() [34/45]
template<class T >
std::ostream& v8::internal::torque::operator<< (std::ostream & os, const Stack< T > & t) [inline]
Definition at line 314 of file utils.h.
                                                                 {
  os << "Stack{";
  PrintCommaSeparatedList(os, t);
  os << "}";
  return os;
}
References PrintCommaSeparatedList().
operator<<() [35/45]
std::ostream& v8::internal::torque::operator<< (std::ostream & os, const StoreBitFieldInstruction & instruction) [inline]
Definition at line 445 of file instructions.h.
                                                                             {
  os << "StoreBitField " << *instruction.bit_field_struct_type << ", "
     << instruction.bit_field.name_and_type.name;
  if (instruction.starts_as_zero) {
    os << ", starts_as_zero";
  }
  return os;
}
References v8::internal::torque::StoreBitFieldInstruction::bit_field, v8::internal::torque::StoreBitFieldInstruction::bit_field_struct_type, v8::internal::torque::NameAndType::name, v8::internal::torque::BitField::name_and_type, and v8::internal::torque::StoreBitFieldInstruction::starts_as_zero.
operator<<() [36/45]
std::ostream& v8::internal::torque::operator<< (std::ostream & os, const StoreReferenceInstruction & instruction) [inline]
Definition at line 403 of file instructions.h.
                                                                              {
  return os << "StoreReference " << *instruction.type;
}
References v8::internal::torque::StoreReferenceInstruction::type.
operator<<() [37/45]
std::ostream& v8::internal::torque::operator<< (std::ostream & os, const Type & t) [inline]
Definition at line 813 of file types.h.
                                                             {
  os << t.ToString();
  return os;
}
References v8::internal::torque::Type::ToString().
operator<<() [38/45]
template<bool success = false>
std::ostream& v8::internal::torque::operator<< (std::ostream & os, const Type * t)
Definition at line 819 of file types.h.
                                                      {
  static_assert(success,
                "Using Type* with an ostream is usually a mistake. Did you "
                "mean to use Type& instead? If you actually intended to print "
                "a pointer, use static_cast<const void*>.");
  return os;
}
operator<<() [39/45]
std::ostream & v8::internal::torque::operator<< (std::ostream & os, const TypeVector & types)
Definition at line 1114 of file types.cc.
                                                                {
  PrintCommaSeparatedList(os, types);
  return os;
}
References PrintCommaSeparatedList().
operator<<() [40/45]
std::ostream& v8::internal::torque::operator<< (std::ostream & os, const UnsafeCastInstruction & instruction) [inline]
Definition at line 770 of file instructions.h.
                                                                          {
  return os << "UnsafeCast " << *instruction.destination_type;
}
References v8::internal::torque::UnsafeCastInstruction::destination_type.
operator<<() [41/45]
std::ostream& v8::internal::torque::operator<< (std::ostream & os, Identifier * id) [inline]
Definition at line 263 of file ast.h.
                                                              {
  return os << id->value;
}
operator<<() [42/45]
std::ostream& v8::internal::torque::operator<< (std::ostream & out, BottomOffset from_bottom) [inline]
Definition at line 202 of file utils.h.
                                                                         {
  return out << "BottomOffset{" << from_bottom.offset << "}";
}
References v8::internal::torque::BottomOffset::offset.
operator<<() [43/45]
std::ostream& v8::internal::torque::operator<< (std::ostream & out, SourcePosition pos) [inline]
Definition at line 112 of file source-positions.h.
                                                                   {
  return out << "https://source.chromium.org/chromium/chromium/src/+/main:v8/"
             << SourceFileMap::PathFromV8Root(pos.source)
             << "?l=" << (pos.start.line + 1)
             << "&c=" << (pos.start.column + 1);
}
References v8::internal::torque::LineAndColumn::column, v8::internal::torque::LineAndColumn::line, v8::internal::torque::SourceFileMap::PathFromV8Root(), v8::internal::torque::SourcePosition::source, and v8::internal::torque::SourcePosition::start.
operator<<() [44/45]
std::ostream& v8::internal::torque::operator<< (std::ostream & out, StackRange range) [inline]
Definition at line 231 of file utils.h.
                                                                 {
  return out << "StackRange{" << range.begin() << ", " << range.end() << "}";
}
References v8::internal::torque::StackRange::begin(), and v8::internal::torque::StackRange::end().
operator<<() [45/45]
std::ostream& v8::internal::torque::operator<< (std::ostream & stream, const DefinitionLocation & loc) [inline]
Definition at line 167 of file instructions.h.
                                                               {
  switch (loc.GetKind()) {
    case DefinitionLocation::Kind::kInvalid:
      return stream << "DefinitionLocation::Invalid()";
    case DefinitionLocation::Kind::kParameter:
      return stream << "DefinitionLocation::Parameter("
                    << loc.GetParameterIndex() << ")";
    case DefinitionLocation::Kind::kPhi:
      return stream << "DefinitionLocation::Phi(" << std::hex
                    << loc.GetPhiBlock() << std::dec << ", "
                    << loc.GetPhiIndex() << ")";
    case DefinitionLocation::Kind::kInstruction:
      return stream << "DefinitionLocation::Instruction(" << std::hex
                    << loc.GetInstruction() << std::dec << ", "
                    << loc.GetInstructionIndex() << ")";
  }
}
References v8::internal::torque::DefinitionLocation::kInstruction, v8::internal::torque::DefinitionLocation::kInvalid, v8::internal::torque::DefinitionLocation::kParameter, v8::internal::torque::DefinitionLocation::kPhi, and v8::internal::loc.
ParseTokens()
std::optional<ParseResult> v8::internal::torque::ParseTokens (Symbol * start, const LexerResult & tokens) [inline]
Definition at line 373 of file earley-parser.h.
                                                                         {
  std::unordered_set<Item, base::hash<Item>> table;
  const Item* final_item = RunEarleyAlgorithm(start, tokens, &table);
  return start->RunAction(final_item, tokens);
}
References v8::internal::torque::Symbol::RunAction(), and RunEarleyAlgorithm().
Referenced by v8::internal::torque::Grammar::Parse().
ParseTorque()
void v8::internal::torque::ParseTorque (const std::string & input)
Definition at line 2959 of file torque-parser.cc.
                                         {
  BuildFlags::Scope build_flags_scope;
  TorqueGrammar().Parse(input);
}
Referenced by CompileTorque(), CompileTorqueForKythe(), and v8::internal::torque::anonymous_namespace{torque-compiler.cc}::ReadAndParseTorqueFile().
PositionAsString()
std::string v8::internal::torque::PositionAsString (SourcePosition pos) [inline]
Definition at line 106 of file source-positions.h.
                                                      {
  return SourceFileMap::PathFromV8Root(pos.source) + ":" +
         std::to_string(pos.start.line + 1) + ":" +
         std::to_string(pos.start.column + 1);
}
References v8::internal::torque::LineAndColumn::column, v8::internal::torque::LineAndColumn::line, v8::internal::torque::SourceFileMap::PathFromV8Root(), v8::internal::torque::SourcePosition::source, and v8::internal::torque::SourcePosition::start.
Referenced by v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::FailCallableLookup(), v8::internal::torque::ImplementationVisitor::GenerateCall(), v8::internal::torque::InstructionBase::InvalidateTransientTypes(), v8::internal::torque::ImplementationVisitor::Visit(), and WrappedMain().
PrintCommaSeparatedList() [1/2]
template<class T >
void v8::internal::torque::PrintCommaSeparatedList (std::ostream & os, const T & list)
Definition at line 168 of file utils.h.
                                                            {
  os << PrintList(list, ", ");
}
References PrintList().
PrintCommaSeparatedList() [2/2]
template<class C , class T >
void v8::internal::torque::PrintCommaSeparatedList (std::ostream & os, const T & list, C && transform)
Definition at line 163 of file utils.h.
                                                                           {
  os << PrintList(list, ", ", std::forward<C>(transform));
}
References PrintList().
Referenced by v8::internal::torque::CCGenerator::EmitCCValue(), v8::internal::torque::ImplementationVisitor::GenerateBuiltinDefinitionsAndInterfaceDescriptors(), v8::internal::torque::ImplementationVisitor::GenerateCSATypes(), operator<<(), v8::internal::torque::ControlFlowGraph::SetReturnType(), and v8::internal::torque::BuiltinPointerType::ToExplicitString().
PrintList() [1/2]
template<class T , class L >
auto v8::internal::torque::PrintList (const T & list, const std::string & separator, L && transformer)
Definition at line 157 of file utils.h.
                                                                           {
  return ListPrintAdaptor<T, L&&>{list, separator,
                                  std::forward<L>(transformer)};
}
References v8::internal::separator.
PrintList() [2/2]
template<class T >
auto v8::internal::torque::PrintList (const T & list, const std::string & separator = `, `)
Definition at line 150 of file utils.h.
                                                                 {
  using ElementType = decltype(*list.begin());
  auto id = [](ElementType el) { return el; };
  return ListPrintAdaptor<T, decltype(id)>{list, separator, id};
}
References v8::internal::separator, and T.
Referenced by PrintCommaSeparatedList(), and v8::internal::torque::ImplementationVisitor::Visit().
PrintSignature()
void v8::internal::torque::PrintSignature (std::ostream & os, const Signature & sig, bool with_names)
Definition at line 1061 of file types.cc.
                                                                           {
  os << "(";
  for (size_t i = 0; i < sig.parameter_types.types.size(); ++i) {
    if (i == 0 && sig.implicit_count != 0) os << "implicit ";
    if (sig.implicit_count > 0 && sig.implicit_count == i) {
      os << ")(";
    } else {
      if (i > 0) os << ", ";
    }
    if (with_names && !sig.parameter_names.empty()) {
      if (i < sig.parameter_names.size()) {
        os << sig.parameter_names[i] << ": ";
      }
    }
    os << *sig.parameter_types.types[i];
  }
  if (sig.parameter_types.var_args) {
    if (!sig.parameter_names.empty()) os << ", ";
    os << "...";
  }
  os << ")";
  os << ": " << *sig.return_type;
  if (sig.labels.empty()) return;
  os << " labels ";
  for (size_t i = 0; i < sig.labels.size(); ++i) {
    if (i > 0) os << ", ";
    os << sig.labels[i].name;
    if (!sig.labels[i].types.empty()) os << "(" << sig.labels[i].types << ")";
  }
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::sig.
Referenced by v8::internal::compiler::CompileCWasmEntry(), v8::internal::compiler::CompileWasmImportCallWrapper(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::FailCallableLookup(), v8::internal::WasmExportedFunction::GetDebugName(), and operator<<().
ProjectStructField()
VisitResult v8::internal::torque::ProjectStructField (VisitResult structure, const std::string & fieldname)
Definition at line 1177 of file types.cc.
                                                           {
  BottomOffset begin = structure.stack_range().begin();
  // Check constructor this super classes for fields.
  const StructType* type = *structure.type()->StructSupertype();
  auto& fields = type->fields();
  for (auto& field : fields) {
    BottomOffset end = begin + LoweredSlotCount(field.name_and_type.type);
    if (field.name_and_type.name == fieldname) {
      return VisitResult(field.name_and_type.type, StackRange{begin, end});
    }
    begin = end;
  }
  ReportError("struct '", type->name(), "' doesn't contain a field '",
              fieldname, "'");
}
References v8::internal::torque::StackRange::begin(), v8::internal::compiler::begin(), v8::internal::compiler::end(), LoweredSlotCount(), ReportError(), v8::internal::torque::VisitResult::stack_range(), v8::internal::torque::Type::StructSupertype(), v8::internal::torque::VisitResult::type(), and v8::internal::tracing::type.
Referenced by v8::internal::torque::anonymous_namespace{cc-generator.cc}::CollectAllFields(), v8::internal::torque::CSAGenerator::EmitCSAValue(), v8::internal::torque::ImplementationVisitor::GenerateAssignToLocation(), and v8::internal::torque::ImplementationVisitor::GenerateFieldAccess().
RegisterDeclarable()
template<class T >
T* v8::internal::torque::RegisterDeclarable (std::unique_ptr< T > d)
Definition at line 154 of file global-context.h.
                                          {
  return GlobalContext::Get().RegisterDeclarable(std::move(d));
}
References v8::base::ContextualVariable< Derived, VarType >::Get().
Referenced by v8::internal::torque::Declarations::CreateBuiltin(), v8::internal::torque::Declarations::CreateExternMacro(), v8::internal::torque::Declarations::CreateIntrinsic(), v8::internal::torque::Declarations::CreateMethod(), v8::internal::torque::Declarations::CreateTorqueMacro(), v8::internal::torque::Declarations::Declare(), and v8::internal::torque::Declarations::DeclareRuntimeFunction().
ReplaceFileContentsIfDifferent()
void v8::internal::torque::ReplaceFileContentsIfDifferent (const std::string & file_path, const std::string & contents)
Definition at line 327 of file utils.cc.
                                                               {
  std::ifstream old_contents_stream(file_path.c_str());
  std::string old_contents;
  bool file_exists = false;
  if (old_contents_stream.good()) {
    file_exists = true;
    std::istreambuf_iterator<char> eos;
    old_contents =
        std::string(std::istreambuf_iterator<char>(old_contents_stream), eos);
    old_contents_stream.close();
  }
  if (!file_exists || old_contents != contents) {
    std::ofstream new_contents_stream;
    new_contents_stream.open(file_path.c_str());
    new_contents_stream << contents;
    new_contents_stream.close();
  }
}
References v8::internal::string.
Referenced by v8::internal::torque::ImplementationVisitor::WriteFile().
ReportAllUnusedMacros()
void v8::internal::torque::ReportAllUnusedMacros ()
Definition at line 5615 of file implementation-visitor.cc.
                             {
  for (const auto& declarable : GlobalContext::AllDeclarables()) {
    if (!declarable->IsMacro() || declarable->IsExternMacro()) continue;
    Macro* macro = Macro::cast(declarable.get());
    if (macro->IsUsed()) continue;
    if (macro->IsTorqueMacro() && TorqueMacro::cast(macro)->IsExportedToCSA()) {
      continue;
    }
    // TODO(gsps): Mark methods of generic structs used if they are used in any
    // instantiation
    if (Method* method = Method::DynamicCast(macro)) {
      if (StructType* struct_type =
              StructType::DynamicCast(method->aggregate_type())) {
        if (struct_type->GetSpecializedFrom().has_value()) {
          continue;
        }
      }
    }
    std::vector<std::string> ignored_prefixes = {"Convert<", "Cast<",
                                                 "FromConstexpr<"};
    const std::string name = macro->ReadableName();
    const bool ignore =
        StartsWithSingleUnderscore(name) ||
        std::any_of(ignored_prefixes.begin(), ignored_prefixes.end(),
                    [&name](const std::string& prefix) {
                      return StringStartsWith(name, prefix);
                    });
    if (!ignore) {
      Lint("Macro '", macro->ReadableName(), "' is never used.")
          .Position(macro->IdentifierPosition());
    }
  }
}
References v8::base::any_of(), v8::internal::torque::Declarable::IdentifierPosition(), wasm::ignore(), v8::internal::torque::Declarable::IsTorqueMacro(), v8::internal::torque::Macro::IsUsed(), Lint(), v8::internal::name, v8::internal::torque::MessageBuilder::Position(), v8::internal::torque::Callable::ReadableName(), StartsWithSingleUnderscore(), and v8::internal::string.
Referenced by v8::internal::torque::anonymous_namespace{torque-compiler.cc}::CompileCurrentAst().
ReportError()
template<class... Args>
void v8::internal::torque::ReportError (Args &&... args)
Definition at line 96 of file utils.h.
                                              {
  Error(std::forward<Args>(args)...).Throw();
}
References v8::base::args, Error(), and v8::internal::torque::MessageBuilder::Throw().
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::Advance(), v8::internal::torque::anonymous_namespace{declarations.cc}::CheckAlreadyDeclared(), v8::internal::torque::Item::CheckAmbiguity(), v8::internal::torque::AggregateType::CheckForDuplicateFields(), v8::internal::torque::ImplementationVisitor::CheckInitializersWellformed(), v8::internal::torque::TypeVisitor::ComputeType(), v8::internal::torque::TypeVisitor::ComputeTypeForStructExpression(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::CreateNamedCaptureAtIndex(), v8::internal::torque::Declarations::DeclareMacro(), v8::internal::torque::DeclarationVisitor::DeclareSpecializedTypes(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::EmitLoadFieldStatement(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::EmitStoreFieldStatement(), v8::internal::torque::anonymous_namespace{declarations.cc}::EnsureNonempty(), v8::internal::torque::anonymous_namespace{declarations.cc}::EnsureUnique(), v8::internal::torque::anonymous_namespace{instructions.cc}::ExpectSubtype(), v8::internal::torque::anonymous_namespace{instructions.cc}::ExpectType(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::FailCallableLookup(), v8::internal::torque::ClassType::GenerateAccessors(), v8::internal::torque::ImplementationVisitor::GenerateAssignToLocation(), v8::internal::torque::ImplementationVisitor::GenerateBuiltinDefinitionsAndInterfaceDescriptors(), v8::internal::torque::ImplementationVisitor::GenerateCall(), v8::internal::torque::ImplementationVisitor::GenerateFetchFromLocation(), v8::internal::torque::ImplementationVisitor::GenerateFieldAccess(), v8::internal::torque::ImplementationVisitor::GenerateFunction(), v8::internal::torque::ImplementationVisitor::GenerateImplicitConvert(), v8::internal::torque::ImplementationVisitor::GeneratePointerCall(), v8::internal::torque::ImplementationVisitor::GetBuiltinCode(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::GetClassInstanceTypeRange(), v8::internal::torque::BuildFlags::GetFlag(), v8::internal::torque::TypeOracle::GetGenericTypeInstance(), v8::internal::torque::ImplementationVisitor::GetLocationReference(), v8::internal::torque::ImplementationVisitor::InlineMacro(), v8::internal::torque::Intrinsic::Intrinsic(), v8::internal::torque::AggregateType::LastField(), v8::internal::torque::Declarations::Lookup(), v8::internal::torque::ImplementationVisitor::LookupCallable(), v8::internal::torque::BitFieldStructType::LookupField(), v8::internal::torque::AggregateType::LookupFieldInternal(), v8::internal::torque::Declarations::LookupGlobalScope(), v8::internal::torque::ImplementationVisitor::LookupLabel(), v8::internal::torque::Scope::LookupShallow(), v8::internal::torque::ImplementationVisitor::LookupSimpleLabel(), v8::internal::torque::Macro::Macro(), v8::internal::torque::ImplementationVisitor::MacroInliningScope::MacroInliningScope(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeCall(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeCatchBlock(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeClassDeclaration(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeEnumDeclaration(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeIfStatement(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeNameAndExpressionFromExpression(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeRightShiftIdentifier(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeTorqueBuiltinDeclaration(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeTorqueMacroDeclaration(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeVarDeclarationStatement(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseCaptureGroupName(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseCharacterClass(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseCharacterEscape(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseClassEscape(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseClassIntersection(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseClassRanges(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseClassSetCharacter(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseClassStringDisjunction(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseClassSubtraction(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseClassUnion(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseDisjunction(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseNamedBackReference(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseOpenParenthesis(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::PatchNamedBackReferences(), ProjectStructField(), v8::internal::torque::BlockBindings< T >::ReportErrorIfAlreadyBound(), v8::internal::torque::TypeAlias::Resolve(), RunEarleyAlgorithm(), v8::internal::torque::Lexer::RunLexer(), v8::internal::torque::Block::SetInputTypes(), v8::internal::torque::ControlFlowGraph::SetReturnType(), v8::internal::torque::AbstractType::SimpleNameImpl(), v8::internal::torque::DeclarationVisitor::Specialize(), v8::internal::torque::DeclarationVisitor::SpecializeImplicit(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::TryParseCharacterClassEscape(), UnwrapTNodeTypeName(), v8::internal::torque::ImplementationVisitor::Visit(), v8::internal::torque::DeclarationVisitor::Visit(), v8::internal::torque::TypeVisitor::VisitClassFieldsAndMethods(), and v8::internal::torque::ImplementationVisitor::VisitInitializerResults().
RunEarleyAlgorithm()
V8_EXPORT_PRIVATE const Item * v8::internal::torque::RunEarleyAlgorithm (Symbol * start, const LexerResult & tokens, std::unordered_set< Item, base::hash< Item >> * processed)
Definition at line 187 of file earley-parser.cc.
                                                       {
  // Worklist for items at the current position.
  std::vector<Item> worklist;
  // Worklist for items at the next position.
  std::vector<Item> future_items;
  CurrentSourcePosition::Scope source_position(
      SourcePosition{CurrentSourceFile::Get(), LineAndColumn::Invalid(),
                     LineAndColumn::Invalid()});
  std::vector<const Item*> completed_items;
  std::unordered_map<std::pair<size_t, Symbol*>, std::set<const Item*>,
                     base::hash<std::pair<size_t, Symbol*>>>
      waiting;
  std::vector<const Item*> debug_trace;
  // Start with one top_level symbol mapping to the start symbol of the grammar.
  // This simplifies things because the start symbol might have several
  // rules.
  Symbol top_level;
  top_level.AddRule(Rule({start}));
  worklist.push_back(Item{top_level.rule(0), 0, 0, 0});
  size_t input_length = tokens.token_symbols.size();
  for (size_t pos = 0; pos <= input_length; ++pos) {
    while (!worklist.empty()) {
      auto insert_result = processed->insert(worklist.back());
      const Item& item = *insert_result.first;
      DCHECK_EQ(pos, item.pos());
      MatchedInput last_token = tokens.token_contents[pos];
      CurrentSourcePosition::Get() = last_token.pos;
      bool is_new = insert_result.second;
      if (!is_new) item.CheckAmbiguity(worklist.back(), tokens);
      worklist.pop_back();
      if (!is_new) continue;
      debug_trace.push_back(&item);
      if (item.IsComplete()) {
        // 'Complete' phase: Advance all items that were waiting to match this
        // symbol next.
        for (const Item* parent : waiting[{item.start(), item.left()}]) {
          worklist.push_back(parent->Advance(pos, &item));
        }
      } else {
        Symbol* next = item.NextSymbol();
        // 'Scan' phase: Check if {next} is the next symbol in the input (this
        // is never the case if {next} is a non-terminal).
        if (pos < tokens.token_symbols.size() &&
            tokens.token_symbols[pos] == next) {
          future_items.push_back(item.Advance(pos + 1, nullptr));
        }
        // 'Predict' phase: Add items for every rule of the non-terminal.
        if (!next->IsTerminal()) {
          // Remember that this item is waiting for completion with {next}.
          waiting[{pos, next}].insert(&item);
        }
        for (size_t i = 0; i < next->rule_number(); ++i) {
          Rule* rule = next->rule(i);
          auto already_completed =
              processed->find(Item{rule, rule->right().size(), pos, pos});
          // As discussed in section 3 of
          // Aycock, John, and R. Nigel Horspool. "Practical earley
          // parsing." The Computer Journal 45.6 (2002): 620-630.
          // Earley parsing has the following problem with epsilon rules:
          // When we complete an item that started at the current position
          // (that is, it matched zero tokens), we might not yet have
          // predicted all items it can complete with. Thus we check for the
          // existence of such items here and complete them immediately.
          if (already_completed != processed->end()) {
            worklist.push_back(item.Advance(pos, &*already_completed));
          } else {
            worklist.push_back(Item{rule, 0, pos, pos});
          }
        }
      }
    }
    std::swap(worklist, future_items);
  }
  auto final_item =
      processed->find(Item{top_level.rule(0), 1, 0, input_length});
  if (final_item != processed->end()) {
    // Success: The {top_level} rule matches the complete input.
    return final_item->Children()[0];
  }
  std::string reason;
  const Item& last_item = *debug_trace.back();
  if (last_item.pos() < tokens.token_symbols.size()) {
    std::string next_token = tokens.token_contents[last_item.pos()].ToString();
    reason = "unexpected token \"" + next_token + "\"";
  } else {
    reason = "unexpected end of input";
  }
  ReportError("Parser Error: " + reason);
}
References v8::internal::torque::Symbol::AddRule(), v8::internal::torque::Item::Advance(), v8::internal::torque::Item::CheckAmbiguity(), DCHECK_EQ, v8::internal::compiler::turboshaft::Get(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::torque::LineAndColumn::Invalid(), v8::internal::torque::Item::IsComplete(), v8::internal::torque::Symbol::IsTerminal(), v8::internal::torque::Item::left(), v8::internal::torque::Item::NextSymbol(), v8::internal::torque::MatchedInput::pos, v8::internal::torque::Item::pos(), ReportError(), v8::internal::torque::Rule::right(), v8::internal::torque::Symbol::rule(), v8::internal::torque::Symbol::rule_number(), size(), v8::internal::torque::Item::start(), v8::internal::string, v8::internal::torque::LexerResult::token_contents, and v8::internal::torque::LexerResult::token_symbols.
Referenced by ParseTokens().
SizeOf()
std::optional< std::tuple< size_t, std::string > > v8::internal::torque::SizeOf (const Type * type)
Definition at line 1337 of file types.cc.
                                                                  {
  std::string size_string;
  size_t size;
  if (type->IsSubtypeOf(TypeOracle::GetTaggedType())) {
    size = TargetArchitecture::TaggedSize();
    size_string = "kTaggedSize";
  } else if (type->IsSubtypeOf(TypeOracle::GetRawPtrType())) {
    size = TargetArchitecture::RawPtrSize();
    size_string = "kSystemPointerSize";
  } else if (type->IsSubtypeOf(TypeOracle::GetExternalPointerType())) {
    size = TargetArchitecture::ExternalPointerSize();
    size_string = "kExternalPointerSlotSize";
  } else if (type->IsSubtypeOf(TypeOracle::GetCppHeapPointerType())) {
    size = TargetArchitecture::CppHeapPointerSize();
    size_string = "kCppHeapPointerSlotSize";
  } else if (type->IsSubtypeOf(TypeOracle::GetTrustedPointerType())) {
    size = TargetArchitecture::TrustedPointerSize();
    size_string = "kTrustedPointerSize";
  } else if (type->IsSubtypeOf(TypeOracle::GetProtectedPointerType())) {
    size = TargetArchitecture::ProtectedPointerSize();
    size_string = "kTaggedSize";
  } else if (type->IsSubtypeOf(TypeOracle::GetVoidType())) {
    size = 0;
    size_string = "0";
  } else if (type->IsSubtypeOf(TypeOracle::GetInt8Type())) {
    size = kUInt8Size;
    size_string = "kUInt8Size";
  } else if (type->IsSubtypeOf(TypeOracle::GetUint8Type())) {
    size = kUInt8Size;
    size_string = "kUInt8Size";
  } else if (type->IsSubtypeOf(TypeOracle::GetInt16Type())) {
    size = kUInt16Size;
    size_string = "kUInt16Size";
  } else if (type->IsSubtypeOf(TypeOracle::GetUint16Type())) {
    size = kUInt16Size;
    size_string = "kUInt16Size";
  } else if (type->IsSubtypeOf(TypeOracle::GetInt32Type())) {
    size = kInt32Size;
    size_string = "kInt32Size";
  } else if (type->IsSubtypeOf(TypeOracle::GetUint32Type())) {
    size = kInt32Size;
    size_string = "kInt32Size";
  } else if (type->IsSubtypeOf(TypeOracle::GetFloat64Type())) {
    size = kDoubleSize;
    size_string = "kDoubleSize";
  } else if (type->IsSubtypeOf(TypeOracle::GetIntPtrType())) {
    size = TargetArchitecture::RawPtrSize();
    size_string = "kIntptrSize";
  } else if (type->IsSubtypeOf(TypeOracle::GetUIntPtrType())) {
    size = TargetArchitecture::RawPtrSize();
    size_string = "kIntptrSize";
  } else if (auto struct_type = type->StructSupertype()) {
    if (type == TypeOracle::GetFloat64OrUndefinedOrHoleType()) {
      size = kDoubleSize;
      size_string = "kDoubleSize";
    } else {
      size = (*struct_type)->PackedSize();
      size_string = std::to_string(size);
    }
  } else {
    return {};
  }
  return std::make_tuple(size, size_string);
}
References v8::internal::torque::TargetArchitecture::CppHeapPointerSize(), v8::internal::torque::TargetArchitecture::ExternalPointerSize(), v8::internal::torque::TypeOracle::GetCppHeapPointerType(), v8::internal::torque::TypeOracle::GetExternalPointerType(), v8::internal::torque::TypeOracle::GetFloat64OrUndefinedOrHoleType(), v8::internal::torque::TypeOracle::GetFloat64Type(), v8::internal::torque::TypeOracle::GetInt16Type(), v8::internal::torque::TypeOracle::GetInt32Type(), v8::internal::torque::TypeOracle::GetInt8Type(), v8::internal::torque::TypeOracle::GetIntPtrType(), v8::internal::torque::TypeOracle::GetProtectedPointerType(), v8::internal::torque::TypeOracle::GetRawPtrType(), v8::internal::torque::TypeOracle::GetTaggedType(), v8::internal::torque::TypeOracle::GetTrustedPointerType(), v8::internal::torque::TypeOracle::GetUint16Type(), v8::internal::torque::TypeOracle::GetUint32Type(), v8::internal::torque::TypeOracle::GetUint8Type(), v8::internal::torque::TypeOracle::GetUIntPtrType(), v8::internal::torque::TypeOracle::GetVoidType(), v8::internal::kDoubleSize, v8::internal::kInt32Size, v8::internal::kUInt16Size, v8::internal::kUInt8Size, v8::internal::torque::TargetArchitecture::ProtectedPointerSize(), v8::internal::torque::TargetArchitecture::RawPtrSize(), size(), v8::internal::string, v8::internal::torque::TargetArchitecture::TaggedSize(), v8::internal::torque::TargetArchitecture::TrustedPointerSize(), and v8::internal::tracing::type.
Referenced by v8::internal::torque::TypeVisitor::ComputeType(), v8::internal::torque::ImplementationVisitor::GenerateCall(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::GenerateClass(), v8::internal::torque::ImplementationVisitor::GenerateLayoutForInitialization(), v8::internal::torque::ClassType::GenerateSliceAccessor(), v8::internal::torque::Field::GetFieldSizeInformation(), v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::DebugFieldType::GetSize(), v8::internal::SubclassBodyDescriptor< ParentBodyDescriptor, ChildBodyDescriptor >::SizeOf(), v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitDescriptorArray(), and v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitDescriptorArrayStrongly().
SnakeifyString()
std::string v8::internal::torque::SnakeifyString (const std::string & camel_string)
Definition at line 295 of file utils.cc.
                                                        {
  std::string result;
  bool previousWasLower = false;
  for (auto current : camel_string) {
    if (previousWasLower && isupper(current)) {
      result += "_";
    }
    result += tolower(current);
    previousWasLower = (islower(current));
  }
  return result;
}
References v8::base::internal::result, and v8::internal::string.
Referenced by v8::internal::torque::ImplementationVisitor::GenerateClassDefinitions(), and v8::internal::torque::ImplementationVisitor::GenerateInstanceTypes().
StartsWithSingleUnderscore()
bool v8::internal::torque::StartsWithSingleUnderscore (const std::string & str)
Definition at line 323 of file utils.cc.
                                                      {
  return str.length() >= 2 && str[0] == '_' && str[1] != '_';
}
Referenced by ReportAllUnusedMacros().
StringEndsWith()
bool v8::internal::torque::StringEndsWith (const std::string & s, const std::string & suffix) [inline]
Definition at line 361 of file utils.h.
                                                                        {
  if (s.size() < suffix.size()) return false;
  return s.substr(s.size() - suffix.size()) == suffix;
}
Referenced by v8::internal::torque::SourceFileMap::PathFromV8RootWithoutExtension(), and WrappedMain().
StringLiteralQuote()
std::string v8::internal::torque::StringLiteralQuote (const std::string & s)
Definition at line 54 of file utils.cc.
                                                 {
  std::stringstream result;
  result << '"';
  for (size_t i = 0; i < s.length(); ++i) {
    switch (s[i]) {
      case '\n':
        result << "\\n";
        break;
      case '\r':
        result << "\\r";
        break;
      case '\t':
        result << "\\t";
        break;
      case '"':
      case '\\':
        result << "\\" << s[i];
        break;
      default:
        result << s[i];
    }
  }
  result << '"';
  return result.str();
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::base::internal::result.
Referenced by v8::internal::torque::ImplementationVisitor::BeginGeneratedFiles(), v8::internal::torque::ImplementationVisitor::GenerateClassDebugReaders(), v8::internal::torque::ImplementationVisitor::GenerateEnumVerifiers(), v8::internal::torque::ImplementationVisitor::GenerateExportedMacrosAssembler(), v8::internal::torque::ClassType::GenerateSliceAccessor(), operator<<(), v8::internal::torque::Lexer::RunLexer(), v8::internal::torque::ls::anonymous_namespace{json.cc}::SerializeToString(), and v8::internal::torque::ImplementationVisitor::Visit().
StringLiteralUnquote()
std::string v8::internal::torque::StringLiteralUnquote (const std::string & s)
Definition at line 23 of file utils.cc.
                                                   {
  DCHECK(('"' == s.front() && '"' == s.back()) ||
         ('\'' == s.front() && '\'' == s.back()));
  std::stringstream result;
  for (size_t i = 1; i < s.length() - 1; ++i) {
    if (s[i] == '\\') {
      switch (s[++i]) {
        case 'n':
          result << '\n';
          break;
        case 'r':
          result << '\r';
          break;
        case 't':
          result << '\t';
          break;
        case '\'':
        case '"':
        case '\\':
          result << s[i];
          break;
        default:
          UNREACHABLE();
      }
    } else {
      result << s[i];
    }
  }
  return result.str();
}
References v8::internal::DCHECK(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::base::internal::result, and v8::internal::UNREACHABLE().
Referenced by v8::internal::torque::ImplementationVisitor::GenerateCall(), v8::internal::torque::ls::MakeMember(), v8::internal::torque::ls::MakeStringLiteral(), and v8::internal::torque::anonymous_namespace{torque-parser.cc}::StringLiteralUnquoteAction().
StringStartsWith()
bool v8::internal::torque::StringStartsWith (const std::string & s, const std::string & prefix) [inline]
Definition at line 357 of file utils.h.
                                                                          {
  if (s.size() < prefix.size()) return false;
  return s.substr(0, prefix.size()) == prefix;
}
Referenced by v8::internal::torque::SourceFileMap::AbsolutePath(), and v8::internal::torque::ClassType::AttributedToFile().
SubtractType()
const Type * v8::internal::torque::SubtractType (const Type * a, const Type * b)
Definition at line 411 of file types.cc.
                                                       {
  UnionType result = UnionType::FromType(a);
  result.Subtract(b);
  return TypeOracle::GetUnionType(result);
}
References v8::base::internal::result.
Referenced by v8::internal::torque::ImplementationVisitor::Visit().
ToString()
template<class... Args>
std::string v8::internal::torque::ToString (Args &&... args)
Definition at line 41 of file utils.h.
                                   {
  std::stringstream stream;
  USE((stream << std::forward<Args>(args))...);
  return stream.str();
}
References v8::base::args, and USE.
Referenced by v8::internal::torque::ImplementationVisitor::GenerateLayoutForInitialization(), v8::internal::torque::TypeConstraint::IsViolated(), Message(), and v8::internal::torque::ImplementationVisitor::Visit().
TransformVector() [1/2]
template<class T , class U >
std::vector<T> v8::internal::torque::TransformVector (const std::vector< U > & v)
Definition at line 532 of file utils.h.
                                                    {
  return TransformVector<T>(v, [](const U& x) -> T { return x; });
}
References v8::internal::U.
TransformVector() [2/2]
template<class T , class U , class F >
std::vector<T> v8::internal::torque::TransformVector (const std::vector< U > & v, F f)
Definition at line 526 of file utils.h.
                                                         {
  std::vector<T> result;
  std::transform(v.begin(), v.end(), std::back_inserter(result), f);
  return result;
}
References v8::base::internal::result.
Referenced by v8::internal::torque::TypeVisitor::ComputeTypeForStructExpression().
UnderlinifyPath()
std::string v8::internal::torque::UnderlinifyPath (std::string path)
Definition at line 314 of file utils.cc.
                                          {
  std::replace(path.begin(), path.end(), '-', '_');
  std::replace(path.begin(), path.end(), '/', '_');
  std::replace(path.begin(), path.end(), '\\', '_');
  std::replace(path.begin(), path.end(), '.', '_');
  transform(path.begin(), path.end(), path.begin(), ::toupper);
  return path;
}
Referenced by v8::internal::torque::ImplementationVisitor::BeginGeneratedFiles(), and v8::internal::torque::ImplementationVisitor::EndGeneratedFiles().
UnwrapTNodeTypeName()
std::string v8::internal::torque::UnwrapTNodeTypeName (const std::string & generates) [inline]
Definition at line 35 of file declarations.h.
                                                                 {
  if (generates.length() < 7 || generates.substr(0, 6) != "TNode<" ||
      generates.substr(generates.length() - 1, 1) != ">") {
    ReportError("generated type \"", generates,
                "\" should be of the form \"TNode<...>\"");
  }
  return generates.substr(6, generates.length() - 7);
}
References ReportError().
Referenced by v8::internal::torque::anonymous_namespace{type-visitor.cc}::ComputeGeneratesType().
WrappedMain()
int v8::internal::torque::WrappedMain (int argc, const char ** argv)
Definition at line 21 of file torque.cc.
                                             {
  TorqueCompilerOptions options;
  options.collect_language_server_data = false;
  options.force_assert_statements = false;
  std::vector<std::string> files;
  for (int i = 1; i < argc; ++i) {
    // Check for options
    std::string argument(argv[i]);
    if (argument == "-o") {
      options.output_directory = argv[++i];
    } else if (argument == "-v8-root") {
      options.v8_root = std::string(argv[++i]);
    } else if (argument == "-m32") {
#ifdef V8_COMPRESS_POINTERS
      std::cerr << "Pointer compression is incompatible with -m32.\n";
      base::OS::Abort();
#else
      options.force_32bit_output = true;
#endif
    } else if (argument == "-annotate-ir") {
      options.annotate_ir = true;
    } else if (argument == "-strip-v8-root") {
      options.strip_v8_root = true;
    } else {
      // Strip the v8-root in case it is a prefix of the file path itself.
      // This is used when building in Google3.
      if (options.strip_v8_root &&
          argument.substr(0, options.v8_root.size()) == options.v8_root) {
        argument = argument.substr(options.v8_root.size() + 1);
      }
      // Otherwise it's a .tq file. Remember it for compilation.
      files.emplace_back(std::move(argument));
      if (!StringEndsWith(files.back(), ".tq")) {
        std::cerr << "Unexpected command-line argument \"" << files.back()
                  << "\", expected a .tq file.\n";
        base::OS::Abort();
      }
    }
  }
  TorqueCompilerResult result = CompileTorque(files, options);
  // PositionAsString requires the SourceFileMap to be set to
  // resolve the file name. Needed to report errors and lint warnings.
  SourceFileMap::Scope source_file_map_scope(*result.source_file_map);
  for (const TorqueMessage& message : result.messages) {
    if (message.position) {
      std::cerr << PositionAsString(*message.position) << ": ";
    }
    std::cerr << ErrorPrefixFor(message.kind) << ": " << message.message
              << "\n";
  }
  if (!result.messages.empty()) v8::base::OS::Abort();
  return 0;
}
References v8::base::OS::Abort(), v8::internal::torque::TorqueCompilerOptions::annotate_ir, v8::internal::torque::TorqueCompilerOptions::collect_language_server_data, CompileTorque(), ErrorPrefixFor(), v8::internal::torque::TorqueCompilerOptions::force_32bit_output, v8::internal::torque::TorqueCompilerOptions::force_assert_statements, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::torque::TorqueMessage::kind, v8::internal::torque::TorqueMessage::message, v8::internal::torque::TorqueCompilerOptions::output_directory, v8::internal::torque::TorqueMessage::position, PositionAsString(), v8::base::internal::result, v8::internal::string, StringEndsWith(), v8::internal::torque::TorqueCompilerOptions::strip_v8_root, and v8::internal::torque::TorqueCompilerOptions::v8_root.
Referenced by main().
Variable Documentation
ANNOTATION_ABSTRACT
const char* const v8::internal::torque::ANNOTATION_ABSTRACT = `@abstract` [static]
Definition at line 93 of file constants.h.
Referenced by v8::internal::torque::TypeVisitor::ComputeType(), and v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeClassDeclaration().
ANNOTATION_CPP_ACQUIRE_LOAD
const char* const v8::internal::torque::ANNOTATION_CPP_ACQUIRE_LOAD = `@cppAcquireLoad` [static]
Definition at line 132 of file constants.h.
Referenced by v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeClassField().
ANNOTATION_CPP_OBJECT_DEFINITION
const char* const v8::internal::torque::ANNOTATION_CPP_OBJECT_DEFINITION [static]
Initial value:
=
    "@cppObjectDefinition"
Definition at line 119 of file constants.h.
Referenced by v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeClassDeclaration().
ANNOTATION_CPP_OBJECT_LAYOUT_DEFINITION
const char* const v8::internal::torque::ANNOTATION_CPP_OBJECT_LAYOUT_DEFINITION [static]
Initial value:
=
    "@cppObjectLayoutDefinition"
Definition at line 121 of file constants.h.
Referenced by v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeClassDeclaration().
ANNOTATION_CPP_RELAXED_LOAD
const char* const v8::internal::torque::ANNOTATION_CPP_RELAXED_LOAD = `@cppRelaxedLoad` [static]
Definition at line 128 of file constants.h.
Referenced by v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeClassField().
ANNOTATION_CPP_RELAXED_STORE
const char* const v8::internal::torque::ANNOTATION_CPP_RELAXED_STORE = `@cppRelaxedStore` [static]
Definition at line 126 of file constants.h.
Referenced by v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeClassField().
ANNOTATION_CPP_RELEASE_STORE
const char* const v8::internal::torque::ANNOTATION_CPP_RELEASE_STORE = `@cppReleaseStore` [static]
Definition at line 130 of file constants.h.
Referenced by v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeClassField().
ANNOTATION_CUSTOM_CPP_CLASS
const char* const v8::internal::torque::ANNOTATION_CUSTOM_CPP_CLASS = `@customCppClass` [static]
Definition at line 99 of file constants.h.
Referenced by v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeClassDeclaration().
ANNOTATION_CUSTOM_INTERFACE_DESCRIPTOR
const char* const v8::internal::torque::ANNOTATION_CUSTOM_INTERFACE_DESCRIPTOR [static]
Initial value:
=
    "@customInterfaceDescriptor"
Definition at line 136 of file constants.h.
Referenced by v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeTorqueBuiltinDeclaration().
ANNOTATION_CUSTOM_MAP
const char* const v8::internal::torque::ANNOTATION_CUSTOM_MAP = `@customMap` [static]
Definition at line 98 of file constants.h.
Referenced by v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeClassDeclaration().
ANNOTATION_CUSTOM_WEAK_MARKING
const char* const v8::internal::torque::ANNOTATION_CUSTOM_WEAK_MARKING = `@customWeakMarking` [static]
Definition at line 134 of file constants.h.
Referenced by v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeClassField().
ANNOTATION_DO_NOT_GENERATE_CAST
const char* const v8::internal::torque::ANNOTATION_DO_NOT_GENERATE_CAST = `@doNotGenerateCast` [static]
Definition at line 116 of file constants.h.
Referenced by v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeClassDeclaration().
ANNOTATION_DO_NOT_GENERATE_CPP_CLASS
const char* const v8::internal::torque::ANNOTATION_DO_NOT_GENERATE_CPP_CLASS [static]
Initial value:
=
    "@doNotGenerateCppClass"
Definition at line 96 of file constants.h.
Referenced by v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeClassDeclaration().
ANNOTATION_EXPORT
const char* const v8::internal::torque::ANNOTATION_EXPORT = `@export` [static]
Definition at line 115 of file constants.h.
Referenced by v8::internal::torque::anonymous_namespace{torque-parser.cc}::anonymous_namespace{torque-parser.cc}::HasExportAnnotation(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeClassDeclaration(), and v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeTorqueMacroDeclaration().
ANNOTATION_GENERATE_BODY_DESCRIPTOR
const char* const v8::internal::torque::ANNOTATION_GENERATE_BODY_DESCRIPTOR [static]
Initial value:
=
    "@generateBodyDescriptor"
Definition at line 110 of file constants.h.
Referenced by v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeClassDeclaration().
ANNOTATION_GENERATE_FACTORY_FUNCTION
const char* const v8::internal::torque::ANNOTATION_GENERATE_FACTORY_FUNCTION [static]
Initial value:
=
    "@generateFactoryFunction"
Definition at line 113 of file constants.h.
Referenced by v8::internal::torque::TypeVisitor::ComputeType(), and v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeClassDeclaration().
ANNOTATION_GENERATE_UNIQUE_MAP
const char* const v8::internal::torque::ANNOTATION_GENERATE_UNIQUE_MAP = `@generateUniqueMap` [static]
Definition at line 112 of file constants.h.
Referenced by v8::internal::torque::TypeVisitor::ComputeType(), and v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeClassDeclaration().
ANNOTATION_HAS_SAME_INSTANCE_TYPE_AS_PARENT
const char* const v8::internal::torque::ANNOTATION_HAS_SAME_INSTANCE_TYPE_AS_PARENT [static]
Initial value:
=
    "@hasSameInstanceTypeAsParent"
Definition at line 94 of file constants.h.
Referenced by v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeClassDeclaration().
ANNOTATION_HIGHEST_INSTANCE_TYPE_WITHIN_PARENT
const char* const v8::internal::torque::ANNOTATION_HIGHEST_INSTANCE_TYPE_WITHIN_PARENT [static]
Initial value:
=
    "@highestInstanceTypeWithinParentClassRange"
Definition at line 100 of file constants.h.
Referenced by v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeClassDeclaration().
ANNOTATION_IF
const char* const v8::internal::torque::ANNOTATION_IF = `@if` [static]
Definition at line 108 of file constants.h.
Referenced by v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeClassField(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeTorqueBuiltinDeclaration(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeTorqueMacroDeclaration(), and v8::internal::torque::anonymous_namespace{torque-parser.cc}::ProcessIfAnnotation().
ANNOTATION_IFNOT
const char* const v8::internal::torque::ANNOTATION_IFNOT = `@ifnot` [static]
Definition at line 109 of file constants.h.
Referenced by v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeClassField(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeTorqueMacroDeclaration(), and v8::internal::torque::anonymous_namespace{torque-parser.cc}::ProcessIfAnnotation().
ANNOTATION_INCREMENT_USE_COUNTER
const char* const v8::internal::torque::ANNOTATION_INCREMENT_USE_COUNTER [static]
Initial value:
=
    "@incrementUseCounter"
Definition at line 140 of file constants.h.
Referenced by v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeTorqueBuiltinDeclaration().
ANNOTATION_INSTANCE_TYPE_VALUE
const char* const v8::internal::torque::ANNOTATION_INSTANCE_TYPE_VALUE [static]
Initial value:
=
    "@apiExposedInstanceTypeValue"
Definition at line 106 of file constants.h.
Referenced by v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeClassDeclaration(), and v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeInstanceTypeConstraints().
ANNOTATION_LOWEST_INSTANCE_TYPE_WITHIN_PARENT
const char* const v8::internal::torque::ANNOTATION_LOWEST_INSTANCE_TYPE_WITHIN_PARENT [static]
Initial value:
=
    "@lowestInstanceTypeWithinParentClassRange"
Definition at line 102 of file constants.h.
Referenced by v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeClassDeclaration().
ANNOTATION_RESERVE_BITS_IN_INSTANCE_TYPE
const char* const v8::internal::torque::ANNOTATION_RESERVE_BITS_IN_INSTANCE_TYPE [static]
Initial value:
=
    "@reserveBitsInInstanceType"
Definition at line 104 of file constants.h.
Referenced by v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeClassDeclaration(), and v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeInstanceTypeConstraints().
ANNOTATION_SAME_ENUM_VALUE_AS
const char* const v8::internal::torque::ANNOTATION_SAME_ENUM_VALUE_AS = `@sameEnumValueAs` [static]
Definition at line 123 of file constants.h.
Referenced by v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeEnumEntry().
ANNOTATION_USE_PARENT_TYPE_CHECKER
const char* const v8::internal::torque::ANNOTATION_USE_PARENT_TYPE_CHECKER [static]
Initial value:
=
    "@useParentTypeChecker"
Definition at line 117 of file constants.h.
Referenced by v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeAbstractTypeDeclaration().
ARGUMENTS_TYPE_STRING
const char* const v8::internal::torque::ARGUMENTS_TYPE_STRING = `Arguments` [static]
Definition at line 26 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetArgumentsType().
BINT_TYPE_STRING
const char* const v8::internal::torque::BINT_TYPE_STRING = `bint` [static]
Definition at line 64 of file constants.h.
Referenced by v8::internal::torque::anonymous_namespace{utils.cc}::IsMachineType().
BOOL_TYPE_STRING
const char* const v8::internal::torque::BOOL_TYPE_STRING = `bool` [static]
Definition at line 24 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetBoolType(), v8::internal::torque::Type::IsBool(), and v8::internal::torque::anonymous_namespace{utils.cc}::IsMachineType().
BUILTIN_POINTER_TYPE_STRING
const char* const v8::internal::torque::BUILTIN_POINTER_TYPE_STRING = `BuiltinPtr` [static]
Definition at line 51 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetBuiltinPointerType().
CHAR16_TYPE_STRING
const char* const v8::internal::torque::CHAR16_TYPE_STRING = `char16` [static]
Definition at line 66 of file constants.h.
Referenced by v8::internal::torque::anonymous_namespace{utils.cc}::IsMachineType().
CHAR8_TYPE_STRING
const char* const v8::internal::torque::CHAR8_TYPE_STRING = `char8` [static]
Definition at line 65 of file constants.h.
Referenced by v8::internal::torque::anonymous_namespace{utils.cc}::IsMachineType().
CONST_FLOAT64_TYPE_STRING
const char* const v8::internal::torque::CONST_FLOAT64_TYPE_STRING = `constexpr float64` [static]
Definition at line 74 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetConstFloat64Type().
CONST_INT31_TYPE_STRING
const char* const v8::internal::torque::CONST_INT31_TYPE_STRING = `constexpr int31` [static]
Definition at line 72 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetConstInt31Type().
CONST_INT32_TYPE_STRING
const char* const v8::internal::torque::CONST_INT32_TYPE_STRING = `constexpr int32` [static]
Definition at line 73 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetConstInt32Type().
CONST_REFERENCE_TYPE_STRING
const char* const v8::internal::torque::CONST_REFERENCE_TYPE_STRING = `ConstReference` [static]
Definition at line 79 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetReferenceGeneric(), and v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeReferenceTypeExpression().
CONST_SLICE_TYPE_STRING
const char* const v8::internal::torque::CONST_SLICE_TYPE_STRING = `ConstSlice` [static]
Definition at line 81 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetConstSliceGeneric().
CONST_STRING_TYPE_STRING
const char* const v8::internal::torque::CONST_STRING_TYPE_STRING = `constexpr string` [static]
Definition at line 48 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetConstStringType().
CONSTEXPR_BOOL_TYPE_STRING
const char* const v8::internal::torque::CONSTEXPR_BOOL_TYPE_STRING = `constexpr bool` [static]
Definition at line 19 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetConstexprBoolType(), and v8::internal::torque::Type::IsConstexprBool().
CONSTEXPR_INSTANCE_TYPE_TYPE_STRING
const char* const v8::internal::torque::CONSTEXPR_INSTANCE_TYPE_TYPE_STRING [static]
Initial value:
=
    "constexpr InstanceType"
Definition at line 22 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetConstexprInstanceTypeType().
CONSTEXPR_INTPTR_TYPE_STRING
const char* const v8::internal::torque::CONSTEXPR_INTPTR_TYPE_STRING = `constexpr intptr` [static]
Definition at line 21 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetConstexprIntPtrType().
CONSTEXPR_STRING_TYPE_STRING
const char* const v8::internal::torque::CONSTEXPR_STRING_TYPE_STRING = `constexpr string` [static]
Definition at line 20 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetConstexprStringType().
CONSTEXPR_TYPE_PREFIX
const char* const v8::internal::torque::CONSTEXPR_TYPE_PREFIX = `constexpr ` [static]
Definition at line 17 of file constants.h.
Referenced by v8::internal::torque::anonymous_namespace{torque-parser.cc}::AddConstexpr(), GetConstexprName(), GetNonConstexprName(), IsConstexprName(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeAbstractTypeDeclaration(), and v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeEnumDeclaration().
CONTEXT_TYPE_STRING
const char* const v8::internal::torque::CONTEXT_TYPE_STRING = `Context` [static]
Definition at line 27 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetContextType().
CPPHEAPPTR_TYPE_STRING
const char* const v8::internal::torque::CPPHEAPPTR_TYPE_STRING = `CppHeapPointer` [static]
Definition at line 44 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetCppHeapPointerType().
DISPATCH_HANDLE_TYPE_STRING
const char* const v8::internal::torque::DISPATCH_HANDLE_TYPE_STRING = `DispatchHandle` [static]
Definition at line 47 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetDispatchHandleType().
EXTERNALPTR_TYPE_STRING
const char* const v8::internal::torque::EXTERNALPTR_TYPE_STRING = `ExternalPointer` [static]
Definition at line 43 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetExternalPointerType().
FIXED_ARRAY_BASE_TYPE_STRING
const char* const v8::internal::torque::FIXED_ARRAY_BASE_TYPE_STRING = `FixedArrayBase` [static]
Definition at line 89 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetFixedArrayBaseType().
FLOAT16_RAW_BITS_TYPE_STRING
const char* const v8::internal::torque::FLOAT16_RAW_BITS_TYPE_STRING = `float16_raw_bits` [static]
Definition at line 67 of file constants.h.
Referenced by v8::internal::torque::anonymous_namespace{utils.cc}::IsMachineType().
FLOAT32_TYPE_STRING
const char* const v8::internal::torque::FLOAT32_TYPE_STRING = `float32` [static]
Definition at line 68 of file constants.h.
Referenced by v8::internal::torque::Type::IsFloat32(), and v8::internal::torque::anonymous_namespace{utils.cc}::IsMachineType().
FLOAT64_OR_UNDEFINED_OR_HOLE_TYPE_STRING
const char* const v8::internal::torque::FLOAT64_OR_UNDEFINED_OR_HOLE_TYPE_STRING [static]
Initial value:
=
    "float64_or_undefined_or_hole"
Definition at line 70 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetFloat64OrUndefinedOrHoleType(), and v8::internal::torque::anonymous_namespace{utils.cc}::IsMachineType().
FLOAT64_TYPE_STRING
const char* const v8::internal::torque::FLOAT64_TYPE_STRING = `float64` [static]
Definition at line 69 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetFloat64Type(), v8::internal::torque::Type::IsFloat64(), and v8::internal::torque::anonymous_namespace{utils.cc}::IsMachineType().
GENERIC_TYPE_INSTANTIATION_NAMESPACE_STRING
const char* const v8::internal::torque::GENERIC_TYPE_INSTANTIATION_NAMESPACE_STRING [static]
Initial value:
=
    "_generic_type_instantiation_namespace"
Definition at line 87 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::CreateGenericTypeInstantiationNamespace().
HEAP_OBJECT_TYPE_STRING
const char* const v8::internal::torque::HEAP_OBJECT_TYPE_STRING = `HeapObject` [static]
Definition at line 33 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetHeapObjectType().
INT16_TYPE_STRING
const char* const v8::internal::torque::INT16_TYPE_STRING = `int16` [static]
Definition at line 60 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetInt16Type(), and v8::internal::torque::anonymous_namespace{utils.cc}::IsMachineType().
INT31_TYPE_STRING
const char* const v8::internal::torque::INT31_TYPE_STRING = `int31` [static]
Definition at line 56 of file constants.h.
Referenced by v8::internal::torque::anonymous_namespace{utils.cc}::IsMachineType().
INT32_TYPE_STRING
const char* const v8::internal::torque::INT32_TYPE_STRING = `int32` [static]
Definition at line 57 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetInt32Type(), and v8::internal::torque::anonymous_namespace{utils.cc}::IsMachineType().
INT64_TYPE_STRING
const char* const v8::internal::torque::INT64_TYPE_STRING = `int64` [static]
Definition at line 54 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetInt64Type(), and v8::internal::torque::anonymous_namespace{utils.cc}::IsMachineType().
INT8_TYPE_STRING
const char* const v8::internal::torque::INT8_TYPE_STRING = `int8` [static]
Definition at line 62 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetInt8Type(), and v8::internal::torque::anonymous_namespace{utils.cc}::IsMachineType().
INTEGER_LITERAL_TYPE_STRING
const char* const v8::internal::torque::INTEGER_LITERAL_TYPE_STRING [static]
Initial value:
=
    "constexpr IntegerLiteral"
Definition at line 75 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetIntegerLiteralType().
INTPTR_TYPE_STRING
const char* const v8::internal::torque::INTPTR_TYPE_STRING = `intptr` [static]
Definition at line 52 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetIntPtrType(), and v8::internal::torque::anonymous_namespace{utils.cc}::IsMachineType().
JS_FUNCTION_TYPE_STRING
const char* const v8::internal::torque::JS_FUNCTION_TYPE_STRING = `JSFunction` [static]
Definition at line 30 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetJSFunctionType().
JSANY_TYPE_STRING
const char* const v8::internal::torque::JSANY_TYPE_STRING = `JSAny` [static]
Definition at line 35 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetJSAnyType().
JSOBJECT_TYPE_STRING
const char* const v8::internal::torque::JSOBJECT_TYPE_STRING = `JSObject` [static]
Definition at line 36 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetJSObjectType().
kBaseNamespaceName
const char* const v8::internal::torque::kBaseNamespaceName = `base` [static]
Definition at line 321 of file utils.h.
Referenced by v8::internal::torque::GlobalContext::GlobalContext().
kBreakLabelName
constexpr const char* v8::internal::torque::kBreakLabelName = `__break` [static], [constexpr]
Definition at line 19 of file declarations.h.
Referenced by v8::internal::torque::ImplementationVisitor::Visit().
kCatchLabelName
constexpr const char* v8::internal::torque::kCatchLabelName = `__catch` [static], [constexpr]
Definition at line 21 of file declarations.h.
Referenced by v8::internal::torque::ImplementationVisitor::GenerateCatchBlock(), v8::internal::torque::ImplementationVisitor::GetCatchBlock(), and v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeCatchBlock().
kContinueLabelName
constexpr const char* v8::internal::torque::kContinueLabelName = `__continue` [static], [constexpr]
Definition at line 20 of file declarations.h.
Referenced by v8::internal::torque::ImplementationVisitor::Visit().
kFileUriPrefix
const char v8::internal::torque::kFileUriPrefix[] = `file://` [static]
Definition at line 83 of file utils.cc.
Referenced by FileUriDecode().
kFileUriPrefixLength
const int v8::internal::torque::kFileUriPrefixLength = sizeof(kFileUriPrefix) - 1 [static]
Definition at line 85 of file utils.cc.
Referenced by FileUriDecode().
kFromConstexprMacroName
constexpr const char* const v8::internal::torque::kFromConstexprMacroName = `FromConstexpr` [static], [constexpr]
Definition at line 17 of file declarations.h.
Referenced by v8::internal::torque::ImplementationVisitor::GenerateImplicitConvert(), and v8::internal::torque::TypeOracle::ImplicitlyConvertableFrom().
kMacroEndLabelName
constexpr const char* v8::internal::torque::kMacroEndLabelName = `__macro_end` [static], [constexpr]
Definition at line 18 of file declarations.h.
Referenced by v8::internal::torque::ImplementationVisitor::InlineMacro(), and v8::internal::torque::ImplementationVisitor::Visit().
kNextCaseLabelName
constexpr const char* v8::internal::torque::kNextCaseLabelName = `__NextCase` [static], [constexpr]
Definition at line 22 of file declarations.h.
Referenced by v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeTypeswitchStatement().
kTestNamespaceName
const char* const v8::internal::torque::kTestNamespaceName = `test` [static]
Definition at line 322 of file utils.h.
Referenced by v8::internal::torque::Namespace::IsTestNamespace().
kThisParameterName
const char* const v8::internal::torque::kThisParameterName = `this` [static]
Definition at line 253 of file ast.h.
Referenced by DeclareMethods(), v8::internal::torque::ImplementationVisitor::InlineMacro(), v8::internal::torque::IdentifierExpression::IsThis(), and v8::internal::torque::ImplementationVisitor::VisitMacroCommon().
kTqObjectOverrideDecls
constexpr char v8::internal::torque::kTqObjectOverrideDecls[] [constexpr]
Initial value:
=
    R"(std::vector<std::unique_ptr<ObjectProperty>> GetProperties(
      d::MemoryAccessor accessor) const override;
  const char* GetName() const override;
  void Visit(TqObjectVisitor* visitor) const override;
  bool IsSuperclassOf(const TqObject* other) const override;
)"
Definition at line 13 of file class-debug-reader-generator.cc.
Referenced by v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::GenerateClassDebugReader().
LAZY_TYPE_STRING
const char* const v8::internal::torque::LAZY_TYPE_STRING = `Lazy` [static]
Definition at line 84 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetLazyGeneric().
MAP_TYPE_STRING
const char* const v8::internal::torque::MAP_TYPE_STRING = `Map` [static]
Definition at line 31 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetMapType().
MUTABLE_REFERENCE_TYPE_STRING
const char* const v8::internal::torque::MUTABLE_REFERENCE_TYPE_STRING = `MutableReference` [static]
Definition at line 78 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetReferenceGeneric(), and v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeReferenceTypeExpression().
MUTABLE_SLICE_TYPE_STRING
const char* const v8::internal::torque::MUTABLE_SLICE_TYPE_STRING = `MutableSlice` [static]
Definition at line 80 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetMutableSliceGeneric().
NATIVE_CONTEXT_TYPE_STRING
const char* const v8::internal::torque::NATIVE_CONTEXT_TYPE_STRING = `NativeContext` [static]
Definition at line 29 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetNativeContextType().
NEVER_TYPE_STRING
const char* const v8::internal::torque::NEVER_TYPE_STRING = `never` [static]
Definition at line 18 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetNeverType(), v8::internal::torque::anonymous_namespace{utils.cc}::IsMachineType(), and v8::internal::torque::Type::IsNever().
next_unique_binding_index
uint64_t v8::internal::torque::next_unique_binding_index = 0
Definition at line 32 of file implementation-visitor.cc.
NO_CONTEXT_TYPE_STRING
const char* const v8::internal::torque::NO_CONTEXT_TYPE_STRING = `NoContext` [static]
Definition at line 28 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetNoContextType().
NUMBER_TYPE_STRING
const char* const v8::internal::torque::NUMBER_TYPE_STRING = `Number` [static]
Definition at line 50 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetNumberType().
OBJECT_TYPE_STRING
const char* const v8::internal::torque::OBJECT_TYPE_STRING = `Object` [static]
Definition at line 32 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetObjectType().
PROTECTEDPTR_TYPE_STRING
const char* const v8::internal::torque::PROTECTEDPTR_TYPE_STRING = `ProtectedPointer` [static]
Definition at line 46 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetProtectedPointerType().
RAWPTR_TYPE_STRING
const char* const v8::internal::torque::RAWPTR_TYPE_STRING = `RawPtr` [static]
Definition at line 42 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetRawPtrType().
SMI_TAGGED_TYPE_STRING
const char* const v8::internal::torque::SMI_TAGGED_TYPE_STRING = `SmiTagged` [static]
Definition at line 83 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetSmiTaggedGeneric().
SMI_TYPE_STRING
const char* const v8::internal::torque::SMI_TYPE_STRING = `Smi` [static]
Definition at line 37 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetSmiType().
STATIC_ASSERT_MACRO_STRING
const char* const v8::internal::torque::STATIC_ASSERT_MACRO_STRING = `StaticAssert` [static]
Definition at line 91 of file constants.h.
Referenced by v8::internal::torque::ImplementationVisitor::Visit().
STRING_TYPE_STRING
const char* const v8::internal::torque::STRING_TYPE_STRING = `String` [static]
Definition at line 49 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetStringType().
STRONG_TAGGED_TYPE_STRING
const char* const v8::internal::torque::STRONG_TAGGED_TYPE_STRING = `StrongTagged` [static]
Definition at line 39 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetStrongTaggedType().
TAGGED_TYPE_STRING
const char* const v8::internal::torque::TAGGED_TYPE_STRING = `Tagged` [static]
Definition at line 38 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetTaggedType().
TAGGED_ZERO_PATTERN_TYPE_STRING
const char* const v8::internal::torque::TAGGED_ZERO_PATTERN_TYPE_STRING = `TaggedZeroPattern` [static]
Definition at line 34 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetTaggedZeroPatternType().
TORQUE_INTERNAL_NAMESPACE_STRING
const char* const v8::internal::torque::TORQUE_INTERNAL_NAMESPACE_STRING = `torque_internal` [static]
Definition at line 77 of file constants.h.
Referenced by v8::internal::torque::ImplementationVisitor::GenerateAssignToLocation(), v8::internal::torque::ImplementationVisitor::GenerateCatchBlock(), v8::internal::torque::ImplementationVisitor::GenerateFetchFromLocation(), v8::internal::torque::ImplementationVisitor::GenerateLayoutForInitialization(), v8::internal::torque::TypeOracle::GetReferenceGeneric(), v8::internal::torque::TypeOracle::GetUninitializedHeapObjectType(), v8::internal::torque::ImplementationVisitor::InitializeClass(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeReferenceTypeExpression(), and v8::internal::torque::ImplementationVisitor::Visit().
TRUSTEDPTR_TYPE_STRING
const char* const v8::internal::torque::TRUSTEDPTR_TYPE_STRING = `TrustedPointer` [static]
Definition at line 45 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetTrustedPointerType().
UINT16_TYPE_STRING
const char* const v8::internal::torque::UINT16_TYPE_STRING = `uint16` [static]
Definition at line 61 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetUint16Type(), and v8::internal::torque::anonymous_namespace{utils.cc}::IsMachineType().
UINT31_TYPE_STRING
const char* const v8::internal::torque::UINT31_TYPE_STRING = `uint31` [static]
Definition at line 58 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetUint31Type(), and v8::internal::torque::anonymous_namespace{utils.cc}::IsMachineType().
UINT32_TYPE_STRING
const char* const v8::internal::torque::UINT32_TYPE_STRING = `uint32` [static]
Definition at line 59 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetUint32Type(), and v8::internal::torque::anonymous_namespace{utils.cc}::IsMachineType().
UINT64_TYPE_STRING
const char* const v8::internal::torque::UINT64_TYPE_STRING = `uint64` [static]
Definition at line 55 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetUint64Type(), and v8::internal::torque::anonymous_namespace{utils.cc}::IsMachineType().
UINT8_TYPE_STRING
const char* const v8::internal::torque::UINT8_TYPE_STRING = `uint8` [static]
Definition at line 63 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetUint8Type(), and v8::internal::torque::anonymous_namespace{utils.cc}::IsMachineType().
UINTPTR_TYPE_STRING
const char* const v8::internal::torque::UINTPTR_TYPE_STRING = `uintptr` [static]
Definition at line 53 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetUIntPtrType(), and v8::internal::torque::anonymous_namespace{utils.cc}::IsMachineType().
UNINITIALIZED_HEAP_OBJECT_TYPE_STRING
const char* const v8::internal::torque::UNINITIALIZED_HEAP_OBJECT_TYPE_STRING [static]
Initial value:
=
    "UninitializedHeapObject"
Definition at line 40 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetUninitializedHeapObjectType().
UNINITIALIZED_ITERATOR_TYPE_STRING
const char* const v8::internal::torque::UNINITIALIZED_ITERATOR_TYPE_STRING [static]
Initial value:
=
    "UninitializedIterator"
Definition at line 85 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetUninitializedIteratorType().
VOID_TYPE_STRING
const char* const v8::internal::torque::VOID_TYPE_STRING = `void` [static]
Definition at line 25 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetVoidType(), v8::internal::torque::anonymous_namespace{utils.cc}::IsMachineType(), and v8::internal::torque::Type::IsVoid().
WEAK_HEAP_OBJECT
const char* const v8::internal::torque::WEAK_HEAP_OBJECT = `WeakHeapObject` [static]
Definition at line 90 of file constants.h.
Referenced by v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::anonymous_namespace{implementation-visitor.cc}::GenerateRuntimeTypeCheck().
WEAK_TYPE_STRING
const char* const v8::internal::torque::WEAK_TYPE_STRING = `Weak` [static]
Definition at line 82 of file constants.h.
Referenced by v8::internal::torque::TypeOracle::GetWeakGeneric().