v8::internal::anonymous_namespace{compiler.cc} Namespace Reference
Namespaces
 anonymous_namespace{compiler.cc}
Classes
class CompilerTracer
class OptimizedCodeCache
struct ScriptCompileTimerScope
class StressBackgroundCompileThread
Enumerations
enum class CompileResultBehavior { kDefault
, kDiscardForTesting
 }
Functions
constexpr bool IsOSR (BytecodeOffset osr_offset)
ScriptOriginOptions OriginOptionsForEval (Tagged< Object > script, ParsingWhileDebugging parsing_while_debugging)
void LogUnoptimizedCompilation (Isolate *isolate, DirectHandle< SharedFunctionInfo > shared, LogEventListener::CodeTag code_type, base::TimeDelta time_taken_to_execute, base::TimeDelta time_taken_to_finalize)
uint64_t GetNextTraceId ()
template<typename IsolateT >
void InstallUnoptimizedCode (UnoptimizedCompilationInfo *compilation_info, DirectHandle< SharedFunctionInfo > shared_info, IsolateT *isolate)
template<typename IsolateT >
void EnsureInfosArrayOnScript (DirectHandle< Script > script, ParseInfo *parse_info, IsolateT *isolate)
void UpdateSharedFunctionFlagsAfterCompilation (FunctionLiteral *literal)
template<typename IsolateT >
CompilationJob::Status FinalizeSingleUnoptimizedCompilationJob (UnoptimizedCompilationJob *job, Handle< SharedFunctionInfo > shared_info, IsolateT *isolate, FinalizeUnoptimizedCompilationDataList *finalize_unoptimized_compilation_data_list)
std::unique_ptr< UnoptimizedCompilationJob > ExecuteSingleUnoptimizedCompilationJob (ParseInfo *parse_info, FunctionLiteral *literal, Handle< Script > script, AccountingAllocator *allocator, std::vector< FunctionLiteral * > *eager_inner_literals, LocalIsolate *local_isolate)
template<typename IsolateT >
bool IterativelyExecuteAndFinalizeUnoptimizedCompilationJobs (IsolateT *isolate, Handle< Script > script, ParseInfo *parse_info, AccountingAllocator *allocator, IsCompiledScope *is_compiled_scope, FinalizeUnoptimizedCompilationDataList *finalize_unoptimized_compilation_data_list, DeferredFinalizationJobDataList *jobs_to_retry_finalization_on_main_thread)
bool FinalizeDeferredUnoptimizedCompilationJobs (Isolate *isolate, DirectHandle< Script > script, DeferredFinalizationJobDataList *deferred_jobs, PendingCompilationErrorHandler *pending_error_handler, FinalizeUnoptimizedCompilationDataList *finalize_unoptimized_compilation_data_list)
bool PrepareJobWithHandleScope (OptimizedCompilationJob *job, Isolate *isolate, OptimizedCompilationInfo *compilation_info, ConcurrencyMode mode)
bool CompileTurbofan_NotConcurrent (Isolate *isolate, TurbofanCompilationJob *job)
bool CompileTurbofan_Concurrent (Isolate *isolate, std::unique_ptr< TurbofanCompilationJob > job)
bool ShouldOptimize (CodeKind code_kind, DirectHandle< SharedFunctionInfo > shared)
MaybeHandle< Code > CompileTurbofan (Isolate *isolate, Handle< JSFunction > function, DirectHandle< SharedFunctionInfo > shared, ConcurrencyMode mode, BytecodeOffset osr_offset, CompileResultBehavior result_behavior)
MaybeHandle< Code > CompileMaglev (Isolate *isolate, Handle< JSFunction > function, ConcurrencyMode mode, BytecodeOffset osr_offset, CompileResultBehavior result_behavior)
MaybeHandle< Code > GetOrCompileOptimized (Isolate *isolate, DirectHandle< JSFunction > function, ConcurrencyMode mode, CodeKind code_kind, BytecodeOffset osr_offset=BytecodeOffset::None(), CompileResultBehavior result_behavior=CompileResultBehavior::kDefault)
void SpawnDuplicateConcurrentJobForStressTesting (Isolate *isolate, DirectHandle< JSFunction > function, ConcurrencyMode mode, CodeKind code_kind)
bool FailAndClearException (Isolate *isolate)
template<typename IsolateT >
bool PrepareException (IsolateT *isolate, ParseInfo *parse_info)
bool FailWithPreparedException (Isolate *isolate, Handle< Script > script, const PendingCompilationErrorHandler *pending_error_handler, Compiler::ClearExceptionFlag flag=Compiler::KEEP_EXCEPTION)
bool FailWithException (Isolate *isolate, Handle< Script > script, ParseInfo *parse_info, Compiler::ClearExceptionFlag flag)
void FinalizeUnoptimizedCompilation (Isolate *isolate, Handle< Script > script, const UnoptimizedCompileFlags &flags, const UnoptimizedCompileState *compile_state, const FinalizeUnoptimizedCompilationDataList &finalize_unoptimized_compilation_data_list)
void FinalizeUnoptimizedScriptCompilation (Isolate *isolate, Handle< Script > script, const UnoptimizedCompileFlags &flags, const UnoptimizedCompileState *compile_state, const FinalizeUnoptimizedCompilationDataList &finalize_unoptimized_compilation_data_list)
void CompileAllWithBaseline (Isolate *isolate, const FinalizeUnoptimizedCompilationDataList &finalize_unoptimized_compilation_data_list)
template<typename IsolateT >
Handle< SharedFunctionInfo > CreateTopLevelSharedFunctionInfo (ParseInfo *parse_info, DirectHandle< Script > script, IsolateT *isolate)
Handle< SharedFunctionInfo > GetOrCreateTopLevelSharedFunctionInfo (ParseInfo *parse_info, DirectHandle< Script > script, Isolate *isolate, IsCompiledScope *is_compiled_scope)
MaybeHandle< SharedFunctionInfo > CompileToplevel (ParseInfo *parse_info, Handle< Script > script, MaybeDirectHandle< ScopeInfo > maybe_outer_scope_info, Isolate *isolate, IsCompiledScope *is_compiled_scope)
void VerifyCodeMerge (Isolate *isolate, DirectHandle< Script > script)
Handle< Script > NewScript (Isolate *isolate, ParseInfo *parse_info, DirectHandle< String > source, ScriptDetails script_details, NativesFlag natives)
MaybeDirectHandle< SharedFunctionInfo > CompileScriptOnMainThread (const UnoptimizedCompileFlags flags, DirectHandle< String > source, const ScriptDetails &script_details, NativesFlag natives, v8::Extension *extension, Isolate *isolate, MaybeHandle< Script > maybe_script, IsCompiledScope *is_compiled_scope, CompileHintCallback compile_hint_callback=nullptr, void *compile_hint_callback_data=nullptr)
bool CanBackgroundCompile (const ScriptDetails &script_details, v8::Extension *extension, ScriptCompiler::CompileOptions compile_options, NativesFlag natives)
bool CompilationExceptionIsRangeError (Isolate *isolate, DirectHandle< Object > obj)
MaybeDirectHandle< SharedFunctionInfo > CompileScriptOnBothBackgroundAndMainThread (Handle< String > source, const ScriptDetails &script_details, Isolate *isolate, IsCompiledScope *is_compiled_scope)
MaybeDirectHandle< SharedFunctionInfo > GetSharedFunctionInfoForScriptImpl (Isolate *isolate, Handle< String > source, const ScriptDetails &script_details, v8::Extension *extension, AlignedCachedData *cached_data, BackgroundDeserializeTask *deserialize_task, v8::CompileHintCallback compile_hint_callback, void *compile_hint_callback_data, ScriptCompiler::CompileOptions compile_options, ScriptCompiler::NoCacheReason no_cache_reason, NativesFlag natives, ScriptCompiler::CompilationDetails *compilation_details)
Enumeration Type Documentation
CompileResultBehavior
enum v8::internal::anonymous_namespace{compiler.cc}::CompileResultBehavior [strong]
Enumerator
kDefault
kDiscardForTesting
Definition at line 1199 of file compiler.cc.
                                 {
  // Default behavior, i.e. install the result, insert into caches, etc.
  kDefault,
  // Used only for stress testing. The compilation result should be discarded.
  kDiscardForTesting,
};
Function Documentation
CanBackgroundCompile()
bool v8::internal::anonymous_namespace{compiler.cc}::CanBackgroundCompile (const ScriptDetails & script_details, v8::Extension * extension, ScriptCompiler::CompileOptions compile_options, NativesFlag natives)
Definition at line 3815 of file compiler.cc.
                                               {
  // TODO(leszeks): Remove the module check once background compilation of
  // modules is supported.
  return !script_details.origin_options.IsModule() && !extension &&
         script_details.repl_mode == REPLMode::kNo &&
         (compile_options == ScriptCompiler::kNoCompileOptions) &&
         natives == NOT_NATIVES_CODE;
}
References v8::ScriptOriginOptions::IsModule(), v8::internal::kNo, v8::ScriptCompiler::kNoCompileOptions, v8::internal::NOT_NATIVES_CODE, v8::internal::ScriptDetails::origin_options, and v8::internal::ScriptDetails::repl_mode.
Referenced by GetSharedFunctionInfoForScriptImpl().
CompilationExceptionIsRangeError()
bool v8::internal::anonymous_namespace{compiler.cc}::CompilationExceptionIsRangeError (Isolate * isolate, DirectHandle< Object > obj)
Definition at line 3827 of file compiler.cc.
                                                                {
  if (!IsJSError(*obj, isolate)) return false;
  DirectHandle<JSReceiver> js_obj = Cast<JSReceiver>(obj);
  DirectHandle<JSReceiver> constructor;
  if (!JSReceiver::GetConstructor(isolate, js_obj).ToHandle(&constructor)) {
    return false;
  }
  return *constructor == *isolate->range_error_function();
}
References v8::internal::JSReceiver::GetConstructor(), and v8::anonymous_namespace{api.cc}::ToHandle().
Referenced by CompileScriptOnBothBackgroundAndMainThread().
CompileAllWithBaseline()
void v8::internal::anonymous_namespace{compiler.cc}::CompileAllWithBaseline (Isolate * isolate, const FinalizeUnoptimizedCompilationDataList & finalize_unoptimized_compilation_data_list)
Definition at line 1556 of file compiler.cc.
                                                                            {
  for (const auto& finalize_data : finalize_unoptimized_compilation_data_list) {
    Handle<SharedFunctionInfo> shared_info = finalize_data.function_handle();
    IsCompiledScope is_compiled_scope(*shared_info, isolate);
    if (!is_compiled_scope.is_compiled()) continue;
    if (!CanCompileWithBaseline(isolate, *shared_info)) continue;
    Compiler::CompileSharedWithBaseline(
        isolate, shared_info, Compiler::CLEAR_EXCEPTION, &is_compiled_scope);
  }
}
References v8::internal::CanCompileWithBaseline(), v8::internal::Compiler::CLEAR_EXCEPTION, v8::internal::Compiler::CompileSharedWithBaseline(), and v8::internal::IsCompiledScope::is_compiled().
Referenced by v8::internal::Compiler::Compile(), and CompileToplevel().
CompileMaglev()
MaybeHandle<Code> v8::internal::anonymous_namespace{compiler.cc}::CompileMaglev (Isolate * isolate, Handle< JSFunction > function, ConcurrencyMode mode, BytecodeOffset osr_offset, CompileResultBehavior result_behavior)
Definition at line 1284 of file compiler.cc.
                                                                       {
#ifdef V8_ENABLE_MAGLEV
  DCHECK(maglev::IsMaglevEnabled());
  CHECK(result_behavior == CompileResultBehavior::kDefault);
  // TODO(v8:7700): Tracing, see CompileTurbofan.
  DCHECK(!isolate->has_exception());
  PostponeInterruptsScope postpone(isolate);
  // TODO(v8:7700): See everything in CompileTurbofan_Concurrent.
  // - Tracing,
  // - timers,
  // - aborts on memory pressure,
  // ...
  // Prepare the job.
  auto job = maglev::MaglevCompilationJob::New(isolate, function, osr_offset);
  if (IsConcurrent(mode) &&
      !isolate->maglev_concurrent_dispatcher()->is_enabled()) {
    mode = ConcurrencyMode::kSynchronous;
  }
  {
    TRACE_EVENT_WITH_FLOW0(
        TRACE_DISABLED_BY_DEFAULT("v8.compile"),
        IsSynchronous(mode) ? "V8.MaglevPrepare" : "V8.MaglevConcurrentPrepare",
        job->trace_id(), TRACE_EVENT_FLAG_FLOW_OUT);
    CompilerTracer::TraceStartMaglevCompile(isolate, function, job->is_osr(),
                                            mode);
    CompilationJob::Status status = job->PrepareJob(isolate);
    CHECK_EQ(status, CompilationJob::SUCCEEDED); // TODO(v8:7700): Use status.
  }
  if (IsSynchronous(mode)) {
    CompilationJob::Status status =
        job->ExecuteJob(isolate->counters()->runtime_call_stats(),
                        isolate->main_thread_local_isolate());
    if (status == CompilationJob::FAILED) {
      return {};
    }
    CHECK_EQ(status, CompilationJob::SUCCEEDED);
    Compiler::FinalizeMaglevCompilationJob(job.get(), isolate);
    return job->code();
  }
  DCHECK(IsConcurrent(mode));
  // Enqueue it.
  isolate->maglev_concurrent_dispatcher()->EnqueueJob(std::move(job));
  // Remember that the function is currently being processed.
  function->SetTieringInProgress(isolate, true, osr_offset);
  function->SetInterruptBudget(isolate, BudgetModification::kRaise,
                               CodeKind::MAGLEV);
  return {};
#else // V8_ENABLE_MAGLEV
  UNREACHABLE();
#endif // V8_ENABLE_MAGLEV
}
References CHECK, CHECK_EQ, v8::internal::Isolate::counters(), v8::internal::DCHECK(), v8::internal::CompilationJob::FAILED, v8::internal::Compiler::FinalizeMaglevCompilationJob(), v8::internal::Isolate::has_exception(), v8::internal::IsConcurrent(), v8::internal::maglev::IsMaglevEnabled(), v8::internal::IsSynchronous(), v8::internal::kRaise, v8::internal::kSynchronous, v8::internal::Isolate::main_thread_local_isolate(), mode(), v8::internal::anonymous_namespace{intl-objects.cc}::New(), v8::internal::Counters::runtime_call_stats(), v8::internal::status, v8::internal::CompilationJob::SUCCEEDED, TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT_FLAG_FLOW_OUT, TRACE_EVENT_WITH_FLOW0, and v8::internal::UNREACHABLE().
Referenced by GetOrCompileOptimized().
CompileScriptOnBothBackgroundAndMainThread()
MaybeDirectHandle<SharedFunctionInfo> v8::internal::anonymous_namespace{compiler.cc}::CompileScriptOnBothBackgroundAndMainThread (Handle< String > source, const ScriptDetails & script_details, Isolate * isolate, IsCompiledScope * is_compiled_scope)
Definition at line 3839 of file compiler.cc.
                                                                               {
  // Start a background thread compiling the script.
  StressBackgroundCompileThread background_compile_thread(isolate, source,
                                                          script_details);
  UnoptimizedCompileFlags flags_copy =
      background_compile_thread.data()->task->flags();
  CHECK(background_compile_thread.Start());
  MaybeDirectHandle<SharedFunctionInfo> main_thread_maybe_result;
  bool main_thread_had_stack_overflow = false;
  // In parallel, compile on the main thread to flush out any data races.
  {
    IsCompiledScope inner_is_compiled_scope;
    // The background thread should also create any relevant exceptions, so we
    // can ignore the main-thread created ones.
    // TODO(leszeks): Maybe verify that any thrown (or unthrown) exceptions are
    // equivalent.
    TryCatch ignore_try_catch(reinterpret_cast<v8::Isolate*>(isolate));
    flags_copy.set_script_id(Script::kTemporaryScriptId);
    main_thread_maybe_result = CompileScriptOnMainThread(
        flags_copy, source, script_details, NOT_NATIVES_CODE, nullptr, isolate,
        MaybeHandle<Script>(), &inner_is_compiled_scope);
    if (main_thread_maybe_result.is_null()) {
      // Assume all range errors are stack overflows.
      main_thread_had_stack_overflow = CompilationExceptionIsRangeError(
          isolate, direct_handle(isolate->exception(), isolate));
      isolate->clear_exception();
    }
  }
  // Join with background thread and finalize compilation.
  background_compile_thread.ParkedJoin(isolate->main_thread_local_isolate());
  ScriptCompiler::CompilationDetails compilation_details;
  MaybeDirectHandle<SharedFunctionInfo> maybe_result =
      Compiler::GetSharedFunctionInfoForStreamedScript(
          isolate, source, script_details, background_compile_thread.data(),
          is_compiled_scope, &compilation_details);
  // Either both compiles should succeed, or both should fail. The one exception
  // to this is that the main-thread compilation might stack overflow while the
  // background compilation doesn't, so relax the check to include this case.
  // TODO(leszeks): Compare the contents of the results of the two compiles.
  if (main_thread_had_stack_overflow) {
    CHECK(main_thread_maybe_result.is_null());
  } else {
    CHECK_EQ(maybe_result.is_null(), main_thread_maybe_result.is_null());
  }
  return maybe_result;
}
References CHECK, CHECK_EQ, v8::internal::Isolate::clear_exception(), CompilationExceptionIsRangeError(), CompileScriptOnMainThread(), v8::internal::anonymous_namespace{compiler.cc}::StressBackgroundCompileThread::data(), v8::internal::direct_handle(), v8::internal::Isolate::exception(), v8::internal::Compiler::GetSharedFunctionInfoForStreamedScript(), v8::internal::MaybeDirectHandle< T >::is_null(), v8::internal::Script::kTemporaryScriptId, v8::internal::Isolate::main_thread_local_isolate(), v8::internal::NOT_NATIVES_CODE, v8::internal::ParkingThread::ParkedJoin(), v8::internal::UnoptimizedCompileFlags::set_script_id(), v8::base::Thread::Start(), and v8::internal::ScriptStreamingData::task.
Referenced by GetSharedFunctionInfoForScriptImpl().
CompileScriptOnMainThread()
MaybeDirectHandle<SharedFunctionInfo> v8::internal::anonymous_namespace{compiler.cc}::CompileScriptOnMainThread (const UnoptimizedCompileFlags flags, DirectHandle< String > source, const ScriptDetails & script_details, NativesFlag natives, v8::Extension * extension, Isolate * isolate, MaybeHandle< Script > maybe_script, IsCompiledScope * is_compiled_scope, CompileHintCallback compile_hint_callback = nullptr, void * compile_hint_callback_data = nullptr)
Definition at line 3738 of file compiler.cc.
                                                {
  UnoptimizedCompileState compile_state;
  ReusableUnoptimizedCompileState reusable_state(isolate);
  ParseInfo parse_info(isolate, flags, &compile_state, &reusable_state);
  parse_info.set_extension(extension);
  parse_info.SetCompileHintCallbackAndData(compile_hint_callback,
                                           compile_hint_callback_data);
  Handle<Script> script;
  if (!maybe_script.ToHandle(&script)) {
    script = NewScript(isolate, &parse_info, source, script_details, natives);
  }
  DCHECK_EQ(parse_info.flags().is_repl_mode(), script->is_repl_mode());
  return Compiler::CompileToplevel(&parse_info, script, isolate,
                                   is_compiled_scope);
}
References v8::internal::Compiler::CompileToplevel(), DCHECK_EQ, v8::internal::ParseInfo::flags(), v8::internal::flags, NewScript(), v8::internal::script, v8::internal::ParseInfo::set_extension(), v8::internal::ParseInfo::SetCompileHintCallbackAndData(), and v8::internal::MaybeHandle< T >::ToHandle().
Referenced by CompileScriptOnBothBackgroundAndMainThread(), and GetSharedFunctionInfoForScriptImpl().
CompileToplevel()
MaybeHandle<SharedFunctionInfo> v8::internal::anonymous_namespace{compiler.cc}::CompileToplevel (ParseInfo * parse_info, Handle< Script > script, MaybeDirectHandle< ScopeInfo > maybe_outer_scope_info, Isolate * isolate, IsCompiledScope * is_compiled_scope)
Definition at line 1596 of file compiler.cc.
                                        {
  TimerEventScope<TimerEventCompileCode> top_level_timer(isolate);
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.compile"), "V8.CompileCode");
  DCHECK_EQ(ThreadId::Current(), isolate->thread_id());
  PostponeInterruptsScope postpone(isolate);
  DCHECK(!isolate->native_context().is_null());
  RCS_SCOPE(isolate, parse_info->flags().is_eval()
                         ? RuntimeCallCounterId::kCompileEval
                         : RuntimeCallCounterId::kCompileScript);
  VMState<BYTECODE_COMPILER> state(isolate);
  if (parse_info->literal() == nullptr &&
      !parsing::ParseProgram(parse_info, script, maybe_outer_scope_info,
                             isolate, parsing::ReportStatisticsMode::kYes)) {
    FailWithException(isolate, script, parse_info,
                      Compiler::ClearExceptionFlag::KEEP_EXCEPTION);
    return MaybeHandle<SharedFunctionInfo>();
  }
  // Measure how long it takes to do the compilation; only take the
  // rest of the function into account to avoid overlap with the
  // parsing statistics.
  NestedTimedHistogram* rate = parse_info->flags().is_eval()
                                   ? isolate->counters()->compile_eval()
                                   : isolate->counters()->compile();
  NestedTimedHistogramScope timer(rate);
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.compile"),
               parse_info->flags().is_eval() ? "V8.CompileEval" : "V8.Compile");
  // Create the SharedFunctionInfo and add it to the script's list.
  Handle<SharedFunctionInfo> shared_info =
      GetOrCreateTopLevelSharedFunctionInfo(parse_info, script, isolate,
                                            is_compiled_scope);
  FinalizeUnoptimizedCompilationDataList
      finalize_unoptimized_compilation_data_list;
  // Prepare and execute compilation of the outer-most function.
  if (!IterativelyExecuteAndFinalizeUnoptimizedCompilationJobs(
          isolate, script, parse_info, isolate->allocator(), is_compiled_scope,
          &finalize_unoptimized_compilation_data_list, nullptr)) {
    FailWithException(isolate, script, parse_info,
                      Compiler::ClearExceptionFlag::KEEP_EXCEPTION);
    return MaybeHandle<SharedFunctionInfo>();
  }
  // Character stream shouldn't be used again.
  parse_info->ResetCharacterStream();
  FinalizeUnoptimizedScriptCompilation(
      isolate, script, parse_info->flags(), parse_info->state(),
      finalize_unoptimized_compilation_data_list);
  if (v8_flags.always_sparkplug) {
    CompileAllWithBaseline(isolate, finalize_unoptimized_compilation_data_list);
  }
  return shared_info;
}
References v8::internal::Isolate::allocator(), CompileAllWithBaseline(), v8::internal::Isolate::counters(), v8::internal::ThreadId::Current(), v8::internal::DCHECK(), DCHECK_EQ, FailWithException(), FinalizeUnoptimizedScriptCompilation(), v8::internal::ParseInfo::flags(), GetOrCreateTopLevelSharedFunctionInfo(), IterativelyExecuteAndFinalizeUnoptimizedCompilationJobs(), v8::internal::parsing::kYes, v8::internal::ParseInfo::literal(), v8::internal::Isolate::native_context(), v8::internal::parsing::ParseProgram(), RCS_SCOPE, v8::internal::ParseInfo::ResetCharacterStream(), v8::internal::script, v8::internal::ParseInfo::state(), v8::internal::Isolate::thread_id(), TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT0, and v8::internal::v8_flags.
Referenced by v8::internal::Compiler::CompileForLiveEdit(), v8::internal::Compiler::CompileToplevel(), v8::internal::Compiler::GetFunctionFromEval(), and v8::internal::Compiler::GetWrappedFunction().
CompileTurbofan()
MaybeHandle<Code> v8::internal::anonymous_namespace{compiler.cc}::CompileTurbofan (Isolate * isolate, Handle< JSFunction > function, DirectHandle< SharedFunctionInfo > shared, ConcurrencyMode mode, BytecodeOffset osr_offset, CompileResultBehavior result_behavior)
Definition at line 1220 of file compiler.cc.
                                                                         {
  VMState<COMPILER> state(isolate);
  TimerEventScope<TimerEventOptimizeCode> optimize_code_timer(isolate);
  RCS_SCOPE(isolate, RuntimeCallCounterId::kOptimizeCode);
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.compile"), "V8.OptimizeCode");
  DCHECK(!isolate->has_exception());
  PostponeInterruptsScope postpone(isolate);
  const compiler::IsScriptAvailable has_script =
      IsScript(shared->script()) ? compiler::IsScriptAvailable::kYes
                                 : compiler::IsScriptAvailable::kNo;
  // BUG(5946): This DCHECK is necessary to make certain that we won't
  // tolerate the lack of a script without bytecode.
  DCHECK_IMPLIES(has_script == compiler::IsScriptAvailable::kNo,
                 shared->HasBytecodeArray());
  std::unique_ptr<TurbofanCompilationJob> job(
      compiler::NewCompilationJob(isolate, function, has_script, osr_offset));
  if (result_behavior == CompileResultBehavior::kDiscardForTesting) {
    job->compilation_info()->set_discard_result_for_testing();
  }
  if (IsOSR(osr_offset)) {
    isolate->CountUsage(v8::Isolate::kTurboFanOsrCompileStarted);
  }
  // Prepare the job and launch concurrent compilation, or compile now.
  if (IsConcurrent(mode)) {
    if (CompileTurbofan_Concurrent(isolate, std::move(job))) return {};
  } else {
    DCHECK(IsSynchronous(mode));
    if (CompileTurbofan_NotConcurrent(isolate, job.get())) {
      return job->compilation_info()->code();
    }
  }
  if (isolate->has_exception()) isolate->clear_exception();
  return {};
}
References v8::internal::Isolate::clear_exception(), CompileTurbofan_Concurrent(), CompileTurbofan_NotConcurrent(), v8::internal::Isolate::CountUsage(), v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::Isolate::has_exception(), v8::internal::IsConcurrent(), IsOSR(), v8::internal::IsSynchronous(), v8::internal::compiler::kNo, v8::Isolate::kTurboFanOsrCompileStarted, v8::internal::compiler::kYes, mode(), v8::internal::compiler::NewCompilationJob(), RCS_SCOPE, TRACE_DISABLED_BY_DEFAULT, and TRACE_EVENT0.
Referenced by GetOrCompileOptimized().
CompileTurbofan_Concurrent()
bool v8::internal::anonymous_namespace{compiler.cc}::CompileTurbofan_Concurrent (Isolate * isolate, std::unique_ptr< TurbofanCompilationJob > job)
Definition at line 1136 of file compiler.cc.
                                                                           {
  OptimizedCompilationInfo* const compilation_info = job->compilation_info();
  DCHECK_EQ(compilation_info->code_kind(), CodeKind::TURBOFAN_JS);
  DirectHandle<JSFunction> function = compilation_info->closure();
  if (!isolate->optimizing_compile_dispatcher()->IsQueueAvailable()) {
    if (v8_flags.trace_concurrent_recompilation) {
      PrintF(" ** Compilation queue full, will retry optimizing ");
      ShortPrint(*function);
      PrintF(" later.\n");
    }
    return false;
  }
  if (isolate->heap()->HighMemoryPressure()) {
    if (v8_flags.trace_concurrent_recompilation) {
      PrintF(" ** High memory pressure, will retry optimizing ");
      ShortPrint(*function);
      PrintF(" later.\n");
    }
    return false;
  }
  TimerEventScope<TimerEventRecompileSynchronous> timer(isolate);
  RCS_SCOPE(isolate, RuntimeCallCounterId::kOptimizeConcurrentPrepare);
  TRACE_EVENT_WITH_FLOW0(TRACE_DISABLED_BY_DEFAULT("v8.compile"),
                         "V8.OptimizeConcurrentPrepare", job->trace_id(),
                         TRACE_EVENT_FLAG_FLOW_OUT);
  if (!PrepareJobWithHandleScope(job.get(), isolate, compilation_info,
                                 ConcurrencyMode::kConcurrent)) {
    return false;
  }
  if (V8_LIKELY(!compilation_info->discard_result_for_testing())) {
    function->SetTieringInProgress(isolate, true,
                                   compilation_info->osr_offset());
  }
  // The background recompile will own this job.
  if (!isolate->optimizing_compile_dispatcher()->TryQueueForOptimization(job)) {
    function->SetTieringInProgress(isolate, false,
                                   compilation_info->osr_offset());
    if (v8_flags.trace_concurrent_recompilation) {
      PrintF(" ** Compilation queue full, will retry optimizing ");
      ShortPrint(*function);
      PrintF(" later.\n");
    }
    return false;
  }
  if (v8_flags.trace_concurrent_recompilation) {
    PrintF(" ** Queued ");
    ShortPrint(*function);
    PrintF(" for concurrent optimization.\n");
  }
  DCHECK(compilation_info->shared_info()->HasBytecodeArray());
  return true;
}
References v8::internal::OptimizedCompilationInfo::closure(), v8::internal::OptimizedCompilationInfo::code_kind(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Isolate::heap(), v8::internal::Heap::HighMemoryPressure(), v8::internal::OptimizingCompileDispatcher::IsQueueAvailable(), v8::internal::kConcurrent, v8::internal::Isolate::optimizing_compile_dispatcher(), v8::internal::OptimizedCompilationInfo::osr_offset(), PrepareJobWithHandleScope(), v8::internal::PrintF(), RCS_SCOPE, v8::internal::OptimizedCompilationInfo::shared_info(), v8::internal::ShortPrint(), TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT_FLAG_FLOW_OUT, TRACE_EVENT_WITH_FLOW0, v8::internal::OptimizingCompileDispatcher::TryQueueForOptimization(), v8::internal::v8_flags, and V8_LIKELY.
Referenced by CompileTurbofan().
CompileTurbofan_NotConcurrent()
bool v8::internal::anonymous_namespace{compiler.cc}::CompileTurbofan_NotConcurrent (Isolate * isolate, TurbofanCompilationJob * job)
Definition at line 1090 of file compiler.cc.
                                                                {
  OptimizedCompilationInfo* const compilation_info = job->compilation_info();
  DCHECK_EQ(compilation_info->code_kind(), CodeKind::TURBOFAN_JS);
  TimerEventScope<TimerEventRecompileSynchronous> timer(isolate);
  RCS_SCOPE(isolate, RuntimeCallCounterId::kOptimizeSynchronous);
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.compile"),
               "V8.OptimizeNonConcurrent");
  if (!PrepareJobWithHandleScope(job, isolate, compilation_info,
                                 ConcurrencyMode::kSynchronous)) {
    CompilerTracer::TraceAbortedJob(isolate, compilation_info,
                                    job->prepare_in_ms(), job->execute_in_ms(),
                                    job->finalize_in_ms());
    return false;
  }
  if (job->ExecuteJob(isolate->counters()->runtime_call_stats(),
                      isolate->main_thread_local_isolate())) {
    CompilerTracer::TraceAbortedJob(isolate, compilation_info,
                                    job->prepare_in_ms(), job->execute_in_ms(),
                                    job->finalize_in_ms());
    return false;
  }
  if (job->FinalizeJob(isolate) != CompilationJob::SUCCEEDED) {
    CompilerTracer::TraceAbortedJob(isolate, compilation_info,
                                    job->prepare_in_ms(), job->execute_in_ms(),
                                    job->finalize_in_ms());
    return false;
  }
  // Success!
  job->RecordCompilationStats(ConcurrencyMode::kSynchronous, isolate);
  DCHECK(!isolate->has_exception());
  if (!V8_ENABLE_LEAPTIERING_BOOL || job->compilation_info()->is_osr()) {
    OptimizedCodeCache::Insert(
        isolate, *compilation_info->closure(), compilation_info->osr_offset(),
        *compilation_info->code(),
        compilation_info->function_context_specializing());
  }
  job->RecordFunctionCompilation(LogEventListener::CodeTag::kFunction, isolate);
  return true;
}
References v8::internal::OptimizedCompilationInfo::closure(), v8::internal::OptimizedCompilationInfo::code(), v8::internal::OptimizedCompilationInfo::code_kind(), v8::internal::TurbofanCompilationJob::compilation_info(), v8::internal::Isolate::counters(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::OptimizedCompilationJob::execute_in_ms(), v8::internal::OptimizedCompilationJob::ExecuteJob(), v8::internal::OptimizedCompilationJob::finalize_in_ms(), v8::internal::OptimizedCompilationJob::FinalizeJob(), v8::internal::Isolate::has_exception(), v8::internal::OptimizedCompilationInfo::is_osr(), v8::internal::torque::ls::kFunction, v8::internal::kSynchronous, v8::internal::Isolate::main_thread_local_isolate(), v8::internal::OptimizedCompilationInfo::osr_offset(), v8::internal::OptimizedCompilationJob::prepare_in_ms(), PrepareJobWithHandleScope(), RCS_SCOPE, v8::internal::TurbofanCompilationJob::RecordCompilationStats(), v8::internal::TurbofanCompilationJob::RecordFunctionCompilation(), v8::internal::Counters::runtime_call_stats(), v8::internal::CompilationJob::SUCCEEDED, TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT0, and V8_ENABLE_LEAPTIERING_BOOL.
Referenced by CompileTurbofan().
CreateTopLevelSharedFunctionInfo()
template<typename IsolateT >
Handle<SharedFunctionInfo> v8::internal::anonymous_namespace{compiler.cc}::CreateTopLevelSharedFunctionInfo (ParseInfo * parse_info, DirectHandle< Script > script, IsolateT * isolate)
Definition at line 1572 of file compiler.cc.
                                                                           {
  EnsureInfosArrayOnScript(script, parse_info, isolate);
  DCHECK_EQ(kNoSourcePosition,
            parse_info->literal()->function_token_position());
  return isolate->factory()->NewSharedFunctionInfoForLiteral(
      parse_info->literal(), script, true);
}
References DCHECK_EQ, EnsureInfosArrayOnScript(), v8::internal::FunctionLiteral::function_token_position(), v8::internal::kNoSourcePosition, v8::internal::ParseInfo::literal(), and v8::internal::script.
Referenced by GetOrCreateTopLevelSharedFunctionInfo(), and v8::internal::BackgroundCompileTask::Run().
EnsureInfosArrayOnScript()
template<typename IsolateT >
void v8::internal::anonymous_namespace{compiler.cc}::EnsureInfosArrayOnScript (DirectHandle< Script > script, ParseInfo * parse_info, IsolateT * isolate)
Definition at line 762 of file compiler.cc.
                                                                        {
  DCHECK(parse_info->flags().is_toplevel());
  if (script->infos()->length() > 0) {
    DCHECK_EQ(script->infos()->length(), parse_info->max_info_id() + 1);
    return;
  }
  DirectHandle<WeakFixedArray> infos(isolate->factory()->NewWeakFixedArray(
      parse_info->max_info_id() + 1, AllocationType::kOld));
  script->set_infos(*infos);
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::ParseInfo::flags(), v8::internal::kOld, v8::internal::ParseInfo::max_info_id(), and v8::internal::script.
Referenced by CreateTopLevelSharedFunctionInfo(), and GetOrCreateTopLevelSharedFunctionInfo().
ExecuteSingleUnoptimizedCompilationJob()
std::unique_ptr<UnoptimizedCompilationJob> v8::internal::anonymous_namespace{compiler.cc}::ExecuteSingleUnoptimizedCompilationJob (ParseInfo * parse_info, FunctionLiteral * literal, Handle< Script > script, AccountingAllocator * allocator, std::vector< FunctionLiteral * > * eager_inner_literals, LocalIsolate * local_isolate)
Definition at line 830 of file compiler.cc.
                                 {
#if V8_ENABLE_WEBASSEMBLY
  if (UseAsmWasm(literal, parse_info->flags().is_asm_wasm_broken())) {
    std::unique_ptr<UnoptimizedCompilationJob> asm_job(
        AsmJs::NewCompilationJob(parse_info, literal, allocator));
    if (asm_job->ExecuteJob() == CompilationJob::SUCCEEDED) {
      return asm_job;
    }
    // asm.js validation failed, fall through to standard unoptimized compile.
    // Note: we rely on the fact that AsmJs jobs have done all validation in the
    // PrepareJob and ExecuteJob phases and can't fail in FinalizeJob with
    // with a validation error or another error that could be solve by falling
    // through to standard unoptimized compile.
  }
#endif
  std::unique_ptr<UnoptimizedCompilationJob> job(
      interpreter::Interpreter::NewCompilationJob(
          parse_info, literal, script, allocator, eager_inner_literals,
          local_isolate));
  if (job->ExecuteJob() != CompilationJob::SUCCEEDED) {
    // Compilation failed, return null.
    return std::unique_ptr<UnoptimizedCompilationJob>();
  }
  return job;
}
References v8::internal::ParseInfo::flags(), v8::internal::AsmJs::NewCompilationJob(), v8::internal::interpreter::Interpreter::NewCompilationJob(), v8::internal::script, and v8::internal::CompilationJob::SUCCEEDED.
Referenced by IterativelyExecuteAndFinalizeUnoptimizedCompilationJobs().
FailAndClearException()
bool v8::internal::anonymous_namespace{compiler.cc}::FailAndClearException (Isolate * isolate)
Definition at line 1454 of file compiler.cc.
                                             {
  isolate->clear_internal_exception();
  return false;
}
References v8::internal::Isolate::clear_internal_exception().
Referenced by v8::internal::Compiler::CollectSourcePositions(), and FailWithPreparedException().
FailWithException()
bool v8::internal::anonymous_namespace{compiler.cc}::FailWithException (Isolate * isolate, Handle< Script > script, ParseInfo * parse_info, Compiler::ClearExceptionFlag flag)
Definition at line 1486 of file compiler.cc.
                                                        {
  PrepareException(isolate, parse_info);
  return FailWithPreparedException(isolate, script,
                                   parse_info->pending_error_handler(), flag);
}
References FailWithPreparedException(), v8::internal::ParseInfo::pending_error_handler(), PrepareException(), and v8::internal::script.
Referenced by v8::internal::Compiler::Compile(), and CompileToplevel().
FailWithPreparedException()
bool v8::internal::anonymous_namespace{compiler.cc}::FailWithPreparedException (Isolate * isolate, Handle< Script > script, const PendingCompilationErrorHandler * pending_error_handler, Compiler::ClearExceptionFlag flag = Compiler::KEEP_EXCEPTION)
Definition at line 1468 of file compiler.cc.
                                                              {
  if (flag == Compiler::CLEAR_EXCEPTION) {
    return FailAndClearException(isolate);
  }
  if (!isolate->has_exception()) {
    if (pending_error_handler->has_pending_error()) {
      pending_error_handler->ReportErrors(isolate, script);
    } else {
      isolate->StackOverflow();
    }
  }
  return false;
}
References v8::internal::Compiler::CLEAR_EXCEPTION, FailAndClearException(), v8::internal::Isolate::has_exception(), v8::internal::PendingCompilationErrorHandler::has_pending_error(), v8::internal::PendingCompilationErrorHandler::ReportErrors(), v8::internal::script, and v8::internal::Isolate::StackOverflow().
Referenced by FailWithException(), v8::internal::BackgroundCompileTask::FinalizeFunction(), and v8::internal::BackgroundCompileTask::FinalizeScript().
FinalizeDeferredUnoptimizedCompilationJobs()
bool v8::internal::anonymous_namespace{compiler.cc}::FinalizeDeferredUnoptimizedCompilationJobs (Isolate * isolate, DirectHandle< Script > script, DeferredFinalizationJobDataList * deferred_jobs, PendingCompilationErrorHandler * pending_error_handler, FinalizeUnoptimizedCompilationDataList * finalize_unoptimized_compilation_data_list)
Definition at line 948 of file compiler.cc.
                                                    {
  DCHECK(AllowCompilation::IsAllowed(isolate));
  if (deferred_jobs->empty()) return true;
  // TODO(rmcilroy): Clear native context in debug once AsmJS generates doesn't
  // rely on accessing native context during finalization.
  // Finalize the deferred compilation jobs.
  for (auto&& job : *deferred_jobs) {
    Handle<SharedFunctionInfo> shared_info = job.function_handle();
    if (FinalizeSingleUnoptimizedCompilationJob(
            job.job(), shared_info, isolate,
            finalize_unoptimized_compilation_data_list) !=
        CompilationJob::SUCCEEDED) {
      return false;
    }
  }
  // Report any warnings generated during deferred finalization.
  if (pending_error_handler->has_pending_warnings()) {
    pending_error_handler->PrepareWarnings(isolate);
  }
  return true;
}
References v8::internal::DCHECK(), FinalizeSingleUnoptimizedCompilationJob(), v8::internal::PendingCompilationErrorHandler::has_pending_warnings(), v8::internal::PendingCompilationErrorHandler::PrepareWarnings(), and v8::internal::CompilationJob::SUCCEEDED.
Referenced by v8::internal::BackgroundCompileTask::FinalizeFunction(), and v8::internal::BackgroundCompileTask::FinalizeScript().
FinalizeSingleUnoptimizedCompilationJob()
template<typename IsolateT >
CompilationJob::Status v8::internal::anonymous_namespace{compiler.cc}::FinalizeSingleUnoptimizedCompilationJob (UnoptimizedCompilationJob * job, Handle< SharedFunctionInfo > shared_info, IsolateT * isolate, FinalizeUnoptimizedCompilationDataList * finalize_unoptimized_compilation_data_list)
Definition at line 799 of file compiler.cc.
                                                    {
  UnoptimizedCompilationInfo* compilation_info = job->compilation_info();
  CompilationJob::Status status = job->FinalizeJob(shared_info, isolate);
  if (status == CompilationJob::SUCCEEDED) {
    InstallUnoptimizedCode(compilation_info, shared_info, isolate);
    MaybeHandle<CoverageInfo> coverage_info;
    if (compilation_info->has_coverage_info()) {
      MutexGuardIfOffThread<IsolateT> mutex_guard(
          isolate->shared_function_info_access(), isolate);
      if (!shared_info->HasCoverageInfo(
              isolate->GetMainThreadIsolateUnsafe())) {
        coverage_info = compilation_info->coverage_info();
      }
    }
    finalize_unoptimized_compilation_data_list->emplace_back(
        isolate, shared_info, coverage_info, job->time_taken_to_execute(),
        job->time_taken_to_finalize());
  }
  DCHECK_IMPLIES(status == CompilationJob::RETRY_ON_MAIN_THREAD,
                 (std::is_same_v<IsolateT, LocalIsolate>));
  return status;
}
References v8::internal::UnoptimizedCompilationJob::compilation_info(), v8::internal::UnoptimizedCompilationInfo::coverage_info(), DCHECK_IMPLIES, v8::internal::UnoptimizedCompilationJob::FinalizeJob(), v8::internal::UnoptimizedCompilationInfo::has_coverage_info(), InstallUnoptimizedCode(), v8::internal::CompilationJob::RETRY_ON_MAIN_THREAD, v8::internal::status, v8::internal::CompilationJob::SUCCEEDED, v8::internal::UnoptimizedCompilationJob::time_taken_to_execute(), and v8::internal::UnoptimizedCompilationJob::time_taken_to_finalize().
Referenced by FinalizeDeferredUnoptimizedCompilationJobs(), and IterativelyExecuteAndFinalizeUnoptimizedCompilationJobs().
FinalizeUnoptimizedCompilation()
void v8::internal::anonymous_namespace{compiler.cc}::FinalizeUnoptimizedCompilation (Isolate * isolate, Handle< Script > script, const UnoptimizedCompileFlags & flags, const UnoptimizedCompileState * compile_state, const FinalizeUnoptimizedCompilationDataList & finalize_unoptimized_compilation_data_list)
Definition at line 1494 of file compiler.cc.
                                                    {
  if (compile_state->pending_error_handler()->has_pending_warnings()) {
    compile_state->pending_error_handler()->ReportWarnings(isolate, script);
  }
  bool need_source_positions =
      v8_flags.stress_lazy_source_positions ||
      (!flags.collect_source_positions() && isolate->NeedsSourcePositions());
  for (const auto& finalize_data : finalize_unoptimized_compilation_data_list) {
    DirectHandle<SharedFunctionInfo> shared_info =
        finalize_data.function_handle();
    // It's unlikely, but possible, that the bytecode was flushed between being
    // allocated and now, so guard against that case, and against it being
    // flushed in the middle of this loop.
    IsCompiledScope is_compiled_scope(*shared_info, isolate);
    if (!is_compiled_scope.is_compiled()) continue;
    if (need_source_positions) {
      SharedFunctionInfo::EnsureSourcePositionsAvailable(isolate, shared_info);
    }
    LogEventListener::CodeTag log_tag;
    if (shared_info->is_toplevel()) {
      log_tag = flags.is_eval() ? LogEventListener::CodeTag::kEval
                                : LogEventListener::CodeTag::kScript;
    } else {
      log_tag = LogEventListener::CodeTag::kFunction;
    }
    log_tag = V8FileLogger::ToNativeByScript(log_tag, *script);
    if (isolate->interpreted_frames_native_stack() &&
        isolate->logger()->is_listening_to_code_events()) {
      Compiler::InstallInterpreterTrampolineCopy(isolate, shared_info, log_tag);
    }
    DirectHandle<CoverageInfo> coverage_info;
    if (finalize_data.coverage_info().ToHandle(&coverage_info)) {
      isolate->debug()->InstallCoverageInfo(shared_info, coverage_info);
    }
    LogUnoptimizedCompilation(isolate, shared_info, log_tag,
                              finalize_data.time_taken_to_execute(),
                              finalize_data.time_taken_to_finalize());
  }
}
References v8::internal::Isolate::debug(), v8::internal::SharedFunctionInfo::EnsureSourcePositionsAvailable(), v8::internal::flags, v8::internal::PendingCompilationErrorHandler::has_pending_warnings(), v8::internal::Debug::InstallCoverageInfo(), v8::internal::Compiler::InstallInterpreterTrampolineCopy(), v8::internal::Isolate::interpreted_frames_native_stack(), v8::internal::IsCompiledScope::is_compiled(), v8::internal::Logger::is_listening_to_code_events(), v8::internal::torque::ls::kFunction, v8::internal::Isolate::logger(), LogUnoptimizedCompilation(), v8::internal::Isolate::NeedsSourcePositions(), v8::internal::UnoptimizedCompileState::pending_error_handler(), v8::internal::PendingCompilationErrorHandler::ReportWarnings(), v8::internal::script, v8::internal::V8FileLogger::ToNativeByScript(), and v8::internal::v8_flags.
Referenced by v8::internal::Compiler::Compile(), v8::internal::BackgroundCompileTask::FinalizeFunction(), and FinalizeUnoptimizedScriptCompilation().
FinalizeUnoptimizedScriptCompilation()
void v8::internal::anonymous_namespace{compiler.cc}::FinalizeUnoptimizedScriptCompilation (Isolate * isolate, Handle< Script > script, const UnoptimizedCompileFlags & flags, const UnoptimizedCompileState * compile_state, const FinalizeUnoptimizedCompilationDataList & finalize_unoptimized_compilation_data_list)
Definition at line 1543 of file compiler.cc.
                                                    {
  FinalizeUnoptimizedCompilation(isolate, script, flags, compile_state,
                                 finalize_unoptimized_compilation_data_list);
  script->set_compilation_state(Script::CompilationState::kCompiled);
  DCHECK_IMPLIES(isolate->NeedsSourcePositions(), script->has_line_ends());
}
References DCHECK_IMPLIES, FinalizeUnoptimizedCompilation(), v8::internal::flags, v8::internal::Script::kCompiled, v8::internal::Isolate::NeedsSourcePositions(), and v8::internal::script.
Referenced by CompileToplevel(), and v8::internal::BackgroundCompileTask::FinalizeScript().
GetNextTraceId()
uint64_t v8::internal::anonymous_namespace{compiler.cc}::GetNextTraceId ()
Definition at line 514 of file compiler.cc.
                          {
  // Define a global counter for optimized compile trace ids, which
  // counts in the top 32 bits of a uint64_t. This will be mixed into
  // the TurbofanCompilationJob `this` pointer, which hopefully will
  // make the ids unique enough even when the job memory is reused
  // for future jobs.
  static std::atomic_uint32_t next_trace_id = 0xfa5701d0;
  return static_cast<uint64_t>(next_trace_id++) << 32;
}
GetOrCompileOptimized()
MaybeHandle<Code> v8::internal::anonymous_namespace{compiler.cc}::GetOrCompileOptimized (Isolate * isolate, DirectHandle< JSFunction > function, ConcurrencyMode mode, CodeKind code_kind, BytecodeOffset osr_offset = BytecodeOffset::None(), CompileResultBehavior result_behavior = CompileResultBehavior::kDefault)
Definition at line 1351 of file compiler.cc.
                                                                           {
  if (IsOSR(osr_offset)) {
    function->TraceOptimizationStatus(
        "^%s (osr %i)", CodeKindToString(code_kind), osr_offset.ToInt());
  } else {
    function->TraceOptimizationStatus("^%s", CodeKindToString(code_kind));
  }
  DCHECK(CodeKindIsOptimizedJSFunction(code_kind));
  DirectHandle<SharedFunctionInfo> shared(function->shared(), isolate);
  // Reset the OSR urgency. If we enter a function OSR should not be triggered.
  // If we are in fact in a loop we should avoid triggering this compilation
  // request on every iteration and thereby skipping other interrupts.
  function->feedback_vector()->reset_osr_urgency();
  // Clear the optimization marker on the function so that we don't try to
  // re-optimize.
  if (!IsOSR(osr_offset)) {
    function->ResetTieringRequests();
    // Always reset the OSR urgency to ensure we reset it on function entry.
    int invocation_count =
        function->feedback_vector()->invocation_count(kRelaxedLoad);
    if (!(V8_UNLIKELY(v8_flags.testing_d8_test_runner ||
                      v8_flags.allow_natives_syntax) &&
          ManualOptimizationTable::IsMarkedForManualOptimization(isolate,
                                                                 *function)) &&
        invocation_count < v8_flags.minimum_invocations_before_optimization) {
      function->feedback_vector()->set_invocation_count(invocation_count + 1,
                                                        kRelaxedStore);
      return {};
    }
  }
  if (shared->optimization_disabled(CodeKind::MAGLEV)) {
    return {};
  }
  // Do not optimize when debugger needs to hook into every call.
  if (isolate->debug()->needs_check_on_function_call()) {
    return {};
  }
  // Do not optimize if we need to be able to set break points.
  if (shared->HasBreakInfo(isolate)) return {};
  // Do not optimize if optimization is disabled or function doesn't pass
  // turbo_filter.
  if (!ShouldOptimize(code_kind, shared)) return {};
  if (!V8_ENABLE_LEAPTIERING_BOOL || IsOSR(osr_offset)) {
    Handle<Code> cached_code;
    if (OptimizedCodeCache::Get(isolate, function, osr_offset, code_kind)
            .ToHandle(&cached_code)) {
      DCHECK_IMPLIES(!IsOSR(osr_offset), cached_code->kind() <= code_kind);
      return cached_code;
    }
    if (IsOSR(osr_offset)) {
      // One OSR job per function at a time.
      if (function->osr_tiering_in_progress()) return {};
    }
  }
  DCHECK(shared->is_compiled());
  if (code_kind == CodeKind::TURBOFAN_JS) {
    return CompileTurbofan(isolate, indirect_handle(function, isolate), shared,
                           mode, osr_offset, result_behavior);
  } else {
    DCHECK_EQ(code_kind, CodeKind::MAGLEV);
    return CompileMaglev(isolate, indirect_handle(function, isolate), mode,
                         osr_offset, result_behavior);
  }
}
References v8::internal::CodeKindIsOptimizedJSFunction(), v8::internal::CodeKindToString(), CompileMaglev(), CompileTurbofan(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::Isolate::debug(), v8::internal::compiler::turboshaft::Get(), v8::internal::indirect_handle(), v8::internal::ManualOptimizationTable::IsMarkedForManualOptimization(), IsOSR(), v8::kRelaxedLoad, v8::kRelaxedStore, mode(), v8::internal::Debug::needs_check_on_function_call(), ShouldOptimize(), v8::anonymous_namespace{api.cc}::ToHandle(), V8_ENABLE_LEAPTIERING_BOOL, v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by v8::internal::Compiler::Compile(), v8::internal::Compiler::CompileOptimized(), v8::internal::Compiler::CompileOptimizedOSR(), and SpawnDuplicateConcurrentJobForStressTesting().
GetOrCreateTopLevelSharedFunctionInfo()
Handle<SharedFunctionInfo> v8::internal::anonymous_namespace{compiler.cc}::GetOrCreateTopLevelSharedFunctionInfo (ParseInfo * parse_info, DirectHandle< Script > script, Isolate * isolate, IsCompiledScope * is_compiled_scope)
Definition at line 1581 of file compiler.cc.
                                        {
  EnsureInfosArrayOnScript(script, parse_info, isolate);
  MaybeHandle<SharedFunctionInfo> maybe_shared =
      Script::FindSharedFunctionInfo(script, isolate, parse_info->literal());
  if (Handle<SharedFunctionInfo> shared; maybe_shared.ToHandle(&shared)) {
    DCHECK_EQ(shared->function_literal_id(kRelaxedLoad),
              parse_info->literal()->function_literal_id());
    *is_compiled_scope = shared->is_compiled_scope(isolate);
    return shared;
  }
  return CreateTopLevelSharedFunctionInfo(parse_info, script, isolate);
}
References CreateTopLevelSharedFunctionInfo(), DCHECK_EQ, EnsureInfosArrayOnScript(), v8::internal::Script::FindSharedFunctionInfo(), v8::internal::FunctionLiteral::function_literal_id(), v8::kRelaxedLoad, v8::internal::ParseInfo::literal(), v8::internal::script, and v8::internal::MaybeHandle< T >::ToHandle().
Referenced by CompileToplevel().
GetSharedFunctionInfoForScriptImpl()
MaybeDirectHandle<SharedFunctionInfo> v8::internal::anonymous_namespace{compiler.cc}::GetSharedFunctionInfoForScriptImpl (Isolate * isolate, Handle< String > source, const ScriptDetails & script_details, v8::Extension * extension, AlignedCachedData * cached_data, BackgroundDeserializeTask * deserialize_task, v8::CompileHintCallback compile_hint_callback, void * compile_hint_callback_data, ScriptCompiler::CompileOptions compile_options, ScriptCompiler::NoCacheReason no_cache_reason, NativesFlag natives, ScriptCompiler::CompilationDetails * compilation_details)
Definition at line 3906 of file compiler.cc.
                                                           {
  ScriptCompileTimerScope compile_timer(isolate, no_cache_reason,
                                        compilation_details);
  if (compile_options & ScriptCompiler::kConsumeCodeCache) {
    // Have to have exactly one of cached_data or deserialize_task.
    DCHECK(cached_data || deserialize_task);
    DCHECK(!(cached_data && deserialize_task));
    DCHECK_NULL(extension);
  } else {
    DCHECK_NULL(cached_data);
    DCHECK_NULL(deserialize_task);
  }
  if (compile_options & ScriptCompiler::kConsumeCompileHints) {
    DCHECK_NOT_NULL(compile_hint_callback);
    DCHECK_NOT_NULL(compile_hint_callback_data);
  } else {
    DCHECK_NULL(compile_hint_callback);
    DCHECK_NULL(compile_hint_callback_data);
  }
  compilation_details->background_time_in_microseconds =
      deserialize_task ? deserialize_task->background_time_in_microseconds()
                       : 0;
  LanguageMode language_mode = construct_language_mode(v8_flags.use_strict);
  CompilationCache* compilation_cache = isolate->compilation_cache();
  // For extensions or REPL mode scripts neither do a compilation cache lookup,
  // nor put the compilation result back into the cache.
  const bool use_compilation_cache =
      extension == nullptr && script_details.repl_mode == REPLMode::kNo;
  MaybeDirectHandle<SharedFunctionInfo> maybe_result;
  MaybeHandle<Script> maybe_script;
  IsCompiledScope is_compiled_scope;
  if (use_compilation_cache) {
    bool can_consume_code_cache =
        compile_options & ScriptCompiler::kConsumeCodeCache;
    if (can_consume_code_cache) {
      compile_timer.set_consuming_code_cache();
    }
    // First check per-isolate compilation cache.
    CompilationCacheScript::LookupResult lookup_result =
        compilation_cache->LookupScript(source, script_details, language_mode);
    compilation_details->in_memory_cache_result =
        CategorizeLookupResult(lookup_result);
    maybe_script = lookup_result.script();
    maybe_result = lookup_result.toplevel_sfi();
    is_compiled_scope = lookup_result.is_compiled_scope();
    if (!maybe_result.is_null()) {
      compile_timer.set_hit_isolate_cache();
    } else if (can_consume_code_cache) {
      compile_timer.set_consuming_code_cache();
      // Then check cached code provided by embedder.
      NestedTimedHistogramScope timer(
          isolate->counters()->compile_deserialize());
      RCS_SCOPE(isolate, RuntimeCallCounterId::kCompileDeserialize);
      TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.compile"),
                   "V8.CompileDeserialize");
      if (deserialize_task) {
        // If there's a cache consume task, finish it.
        maybe_result =
            deserialize_task->Finish(isolate, source, script_details);
        // It is possible at this point that there is a Script object for this
        // script in the compilation cache (held in the variable maybe_script),
        // which does not match maybe_result->script(). This could happen any of
        // three ways:
        // 1. The embedder didn't call MergeWithExistingScript.
        // 2. At the time the embedder called SourceTextAvailable, there was not
        // yet a Script in the compilation cache, but it arrived sometime
        // later.
        // 3. At the time the embedder called SourceTextAvailable, there was a
        // Script available, and the new content has been merged into that
        // Script. However, since then, the Script was replaced in the
        // compilation cache, such as by another evaluation of the script
        // hitting case 2, or DevTools clearing the cache.
        // This is okay; the new Script object will replace the current Script
        // held by the compilation cache. Both Scripts may remain in use
        // indefinitely, causing increased memory usage, but these cases are
        // sufficiently unlikely, and ensuring a correct merge in the third case
        // would be non-trivial.
      } else {
        maybe_result = CodeSerializer::Deserialize(
            isolate, cached_data, source, script_details, maybe_script);
      }
      bool consuming_code_cache_succeeded = false;
      DirectHandle<SharedFunctionInfo> result;
      if (maybe_result.ToHandle(&result)) {
        is_compiled_scope = result->is_compiled_scope(isolate);
        if (is_compiled_scope.is_compiled()) {
          consuming_code_cache_succeeded = true;
          // Promote to per-isolate compilation cache.
          compilation_cache->PutScript(source, language_mode, result);
        }
      }
      if (!consuming_code_cache_succeeded) {
        // Deserializer failed. Fall through to compile.
        compile_timer.set_consuming_code_cache_failed();
      }
    }
  }
  if (maybe_result.is_null()) {
    // No cache entry found compile the script.
    if (v8_flags.stress_background_compile &&
        CanBackgroundCompile(script_details, extension, compile_options,
                             natives)) {
      // If the --stress-background-compile flag is set, do the actual
      // compilation on a background thread, and wait for its result.
      maybe_result = CompileScriptOnBothBackgroundAndMainThread(
          source, script_details, isolate, &is_compiled_scope);
    } else {
      UnoptimizedCompileFlags flags =
          UnoptimizedCompileFlags::ForToplevelCompile(
              isolate, natives == NOT_NATIVES_CODE, language_mode,
              script_details.repl_mode,
              script_details.origin_options.IsModule() ? ScriptType::kModule
                                                       : ScriptType::kClassic,
              v8_flags.lazy);
      flags.set_is_eager(compile_options & ScriptCompiler::kEagerCompile);
      flags.set_compile_hints_magic_enabled(
          compile_options & ScriptCompiler::kFollowCompileHintsMagicComment);
      flags.set_compile_hints_per_function_magic_enabled(
          compile_options &
          ScriptCompiler::kFollowCompileHintsPerFunctionMagicComment);
      if (DirectHandle<Script> script; maybe_script.ToHandle(&script)) {
        flags.set_script_id(script->id());
      }
      maybe_result = CompileScriptOnMainThread(
          flags, source, script_details, natives, extension, isolate,
          maybe_script, &is_compiled_scope, compile_hint_callback,
          compile_hint_callback_data);
    }
    // Add the result to the isolate cache.
    DirectHandle<SharedFunctionInfo> result;
    if (use_compilation_cache && maybe_result.ToHandle(&result)) {
      DCHECK(is_compiled_scope.is_compiled());
      compilation_cache->PutScript(source, language_mode, result);
    } else if (maybe_result.is_null() && natives != EXTENSION_CODE) {
      isolate->ReportPendingMessages();
    }
  }
  DirectHandle<SharedFunctionInfo> result;
  if (compile_options & ScriptCompiler::CompileOptions::kProduceCompileHints &&
      maybe_result.ToHandle(&result)) {
    Cast<Script>(result->script())->set_produce_compile_hints(true);
  }
  return maybe_result;
}
References v8::ScriptCompiler::CompilationDetails::background_time_in_microseconds, v8::internal::BackgroundDeserializeTask::background_time_in_microseconds(), CanBackgroundCompile(), v8::internal::anonymous_namespace{compiler.cc}::anonymous_namespace{compiler.cc}::CategorizeLookupResult(), v8::internal::Isolate::compilation_cache(), CompileScriptOnBothBackgroundAndMainThread(), CompileScriptOnMainThread(), v8::internal::construct_language_mode(), v8::internal::Isolate::counters(), v8::internal::DCHECK(), DCHECK_NOT_NULL, DCHECK_NULL, v8::internal::CodeSerializer::Deserialize(), v8::internal::EXTENSION_CODE, v8::internal::BackgroundDeserializeTask::Finish(), v8::internal::flags, v8::internal::UnoptimizedCompileFlags::ForToplevelCompile(), v8::ScriptCompiler::CompilationDetails::in_memory_cache_result, v8::internal::IsCompiledScope::is_compiled(), v8::internal::CompilationCacheScriptLookupResult::is_compiled_scope(), v8::internal::MaybeDirectHandle< T >::is_null(), v8::ScriptOriginOptions::IsModule(), v8::kClassic, v8::ScriptCompiler::kConsumeCodeCache, v8::ScriptCompiler::kConsumeCompileHints, v8::ScriptCompiler::kEagerCompile, v8::ScriptCompiler::kFollowCompileHintsMagicComment, v8::ScriptCompiler::kFollowCompileHintsPerFunctionMagicComment, v8::kModule, v8::internal::kNo, v8::internal::CompilationCache::LookupScript(), v8::internal::NOT_NATIVES_CODE, v8::internal::ScriptDetails::origin_options, v8::internal::CompilationCache::PutScript(), RCS_SCOPE, v8::internal::ScriptDetails::repl_mode, v8::internal::Isolate::ReportPendingMessages(), v8::base::internal::result, v8::internal::CompilationCacheScriptLookupResult::script(), v8::internal::script, v8::internal::anonymous_namespace{compiler.cc}::ScriptCompileTimerScope::set_consuming_code_cache(), v8::internal::anonymous_namespace{compiler.cc}::ScriptCompileTimerScope::set_consuming_code_cache_failed(), v8::internal::anonymous_namespace{compiler.cc}::ScriptCompileTimerScope::set_hit_isolate_cache(), v8::internal::MaybeDirectHandle< T >::ToHandle(), v8::internal::MaybeHandle< T >::ToHandle(), v8::internal::CompilationCacheScriptLookupResult::toplevel_sfi(), TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT0, and v8::internal::v8_flags.
Referenced by v8::internal::Compiler::GetSharedFunctionInfoForScript(), v8::internal::Compiler::GetSharedFunctionInfoForScriptWithCachedData(), v8::internal::Compiler::GetSharedFunctionInfoForScriptWithCompileHints(), v8::internal::Compiler::GetSharedFunctionInfoForScriptWithDeserializeTask(), and v8::internal::Compiler::GetSharedFunctionInfoForScriptWithExtension().
InstallUnoptimizedCode()
template<typename IsolateT >
void v8::internal::anonymous_namespace{compiler.cc}::InstallUnoptimizedCode (UnoptimizedCompilationInfo * compilation_info, DirectHandle< SharedFunctionInfo > shared_info, IsolateT * isolate)
Definition at line 725 of file compiler.cc.
                                               {
  if (compilation_info->has_bytecode_array()) {
    DCHECK(!shared_info->HasBytecodeArray()); // Only compiled once.
    DCHECK(!compilation_info->has_asm_wasm_data());
    DCHECK(!shared_info->HasFeedbackMetadata());
#if V8_ENABLE_WEBASSEMBLY
    // If the function failed asm-wasm compilation, mark asm_wasm as broken
    // to ensure we don't try to compile as asm-wasm.
    if (compilation_info->literal()->scope()->IsAsmModule()) {
      shared_info->set_is_asm_wasm_broken(true);
    }
#endif // V8_ENABLE_WEBASSEMBLY
    DirectHandle<FeedbackMetadata> feedback_metadata = FeedbackMetadata::New(
        isolate, compilation_info->feedback_vector_spec());
    shared_info->set_feedback_metadata(*feedback_metadata, kReleaseStore);
    shared_info->set_age(0);
    shared_info->set_bytecode_array(*compilation_info->bytecode_array());
  } else {
#if V8_ENABLE_WEBASSEMBLY
    DCHECK(compilation_info->has_asm_wasm_data());
    // We should only have asm/wasm data when finalizing on the main thread.
    DCHECK((std::is_same_v<IsolateT, Isolate>));
    shared_info->set_asm_wasm_data(*compilation_info->asm_wasm_data());
    shared_info->set_feedback_metadata(
        ReadOnlyRoots(isolate).empty_feedback_metadata(), kReleaseStore);
#else
    UNREACHABLE();
#endif // V8_ENABLE_WEBASSEMBLY
  }
}
References v8::internal::UnoptimizedCompilationInfo::asm_wasm_data(), v8::internal::UnoptimizedCompilationInfo::bytecode_array(), v8::internal::DCHECK(), v8::internal::UnoptimizedCompilationInfo::feedback_vector_spec(), v8::internal::UnoptimizedCompilationInfo::has_asm_wasm_data(), v8::internal::UnoptimizedCompilationInfo::has_bytecode_array(), v8::kReleaseStore, v8::internal::UnoptimizedCompilationInfo::literal(), v8::internal::FeedbackMetadata::New(), v8::internal::FunctionLiteral::scope(), and v8::internal::UNREACHABLE().
Referenced by FinalizeSingleUnoptimizedCompilationJob().
IsOSR()
constexpr bool v8::internal::anonymous_namespace{compiler.cc}::IsOSR (BytecodeOffset osr_offset) [constexpr]
Definition at line 83 of file compiler.cc.
{ return !osr_offset.IsNone(); }
References v8::internal::BytecodeOffset::IsNone().
Referenced by v8::internal::Compiler::CompileOptimizedOSR(), CompileTurbofan(), v8::internal::Compiler::FinalizeMaglevCompilationJob(), v8::internal::Compiler::FinalizeTurbofanCompilationJob(), v8::internal::anonymous_namespace{compiler.cc}::OptimizedCodeCache::Get(), GetOrCompileOptimized(), v8::internal::anonymous_namespace{compiler.cc}::OptimizedCodeCache::Insert(), and v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceOptimizedCodeCacheHit().
IterativelyExecuteAndFinalizeUnoptimizedCompilationJobs()
template<typename IsolateT >
bool v8::internal::anonymous_namespace{compiler.cc}::IterativelyExecuteAndFinalizeUnoptimizedCompilationJobs (IsolateT * isolate, Handle< Script > script, ParseInfo * parse_info, AccountingAllocator * allocator, IsCompiledScope * is_compiled_scope, FinalizeUnoptimizedCompilationDataList * finalize_unoptimized_compilation_data_list, DeferredFinalizationJobDataList * jobs_to_retry_finalization_on_main_thread)
Definition at line 863 of file compiler.cc.
                                                   {
  DeclarationScope::AllocateScopeInfos(parse_info, script, isolate);
  std::vector<FunctionLiteral*> functions_to_compile;
  functions_to_compile.push_back(parse_info->literal());
  bool compilation_succeeded = true;
  while (!functions_to_compile.empty()) {
    FunctionLiteral* literal = functions_to_compile.back();
    functions_to_compile.pop_back();
    Handle<SharedFunctionInfo> shared_info = literal->shared_function_info();
    // It's possible that compilation of an outer function overflowed the stack,
    // so a literal we'd like to compile won't have its SFI yet. Skip compiling
    // the inner function in that case.
    if (shared_info.is_null()) continue;
    if (shared_info->is_compiled()) continue;
    std::unique_ptr<UnoptimizedCompilationJob> job =
        ExecuteSingleUnoptimizedCompilationJob(parse_info, literal, script,
                                               allocator, &functions_to_compile,
                                               isolate->AsLocalIsolate());
    if (!job) {
      // Compilation failed presumably because of stack overflow, make sure
      // the shared function info contains uncompiled data for the next
      // compilation attempts.
      if (!shared_info->HasUncompiledData(isolate)) {
        SharedFunctionInfo::CreateAndSetUncompiledData(isolate, literal);
      }
      compilation_succeeded = false;
      // Proceed finalizing other functions in case they don't have uncompiled
      // data.
      continue;
    }
    UpdateSharedFunctionFlagsAfterCompilation(literal);
    auto finalization_status = FinalizeSingleUnoptimizedCompilationJob(
        job.get(), shared_info, isolate,
        finalize_unoptimized_compilation_data_list);
    switch (finalization_status) {
      case CompilationJob::SUCCEEDED:
        if (literal == parse_info->literal()) {
          // Ensure that the top level function is retained.
          *is_compiled_scope = shared_info->is_compiled_scope(isolate);
          DCHECK(is_compiled_scope->is_compiled());
        }
        break;
      case CompilationJob::FAILED:
        compilation_succeeded = false;
        // Proceed finalizing other functions in case they don't have uncompiled
        // data.
        continue;
      case CompilationJob::RETRY_ON_MAIN_THREAD:
        // This should not happen on the main thread.
        DCHECK((!std::is_same_v<IsolateT, Isolate>));
        DCHECK_NOT_NULL(jobs_to_retry_finalization_on_main_thread);
        // Clear the literal and ParseInfo to prevent further attempts to
        // access them.
        job->compilation_info()->ClearLiteral();
        job->ClearParseInfo();
        jobs_to_retry_finalization_on_main_thread->emplace_back(
            isolate, shared_info, std::move(job));
        break;
    }
  }
  // Report any warnings generated during compilation.
  if (parse_info->pending_error_handler()->has_pending_warnings()) {
    parse_info->pending_error_handler()->PrepareWarnings(isolate);
  }
  return compilation_succeeded;
}
References v8::internal::DeclarationScope::AllocateScopeInfos(), v8::internal::SharedFunctionInfo::CreateAndSetUncompiledData(), v8::internal::DCHECK(), DCHECK_NOT_NULL, ExecuteSingleUnoptimizedCompilationJob(), v8::internal::CompilationJob::FAILED, FinalizeSingleUnoptimizedCompilationJob(), v8::internal::PendingCompilationErrorHandler::has_pending_warnings(), v8::internal::IsCompiledScope::is_compiled(), v8::internal::HandleBase::is_null(), v8::internal::ParseInfo::literal(), v8::internal::ParseInfo::pending_error_handler(), v8::internal::PendingCompilationErrorHandler::PrepareWarnings(), v8::internal::CompilationJob::RETRY_ON_MAIN_THREAD, v8::internal::script, v8::internal::FunctionLiteral::shared_function_info(), v8::internal::CompilationJob::SUCCEEDED, and UpdateSharedFunctionFlagsAfterCompilation().
Referenced by v8::internal::Compiler::Compile(), CompileToplevel(), and v8::internal::BackgroundCompileTask::Run().
LogUnoptimizedCompilation()
void v8::internal::anonymous_namespace{compiler.cc}::LogUnoptimizedCompilation (Isolate * isolate, DirectHandle< SharedFunctionInfo > shared, LogEventListener::CodeTag code_type, base::TimeDelta time_taken_to_execute, base::TimeDelta time_taken_to_finalize)
Definition at line 423 of file compiler.cc.
                                                                     {
  DirectHandle<AbstractCode> abstract_code;
  if (shared->HasBytecodeArray()) {
    abstract_code = direct_handle(
        Cast<AbstractCode>(shared->GetBytecodeArray(isolate)), isolate);
  } else {
#if V8_ENABLE_WEBASSEMBLY
    DCHECK(shared->HasAsmWasmData());
    abstract_code = Cast<AbstractCode>(BUILTIN_CODE(isolate, InstantiateAsmJs));
#else
    UNREACHABLE();
#endif // V8_ENABLE_WEBASSEMBLY
  }
  double time_taken_ms = time_taken_to_execute.InMillisecondsF() +
                         time_taken_to_finalize.InMillisecondsF();
  DirectHandle<Script> script(Cast<Script>(shared->script()), isolate);
  Compiler::LogFunctionCompilation(
      isolate, code_type, script, shared, DirectHandle<FeedbackVector>(),
      abstract_code, CodeKind::INTERPRETED_FUNCTION, time_taken_ms);
}
References BUILTIN_CODE, v8::internal::DCHECK(), v8::internal::direct_handle(), v8::base::TimeDelta::InMillisecondsF(), v8::internal::Compiler::LogFunctionCompilation(), v8::internal::script, and v8::internal::UNREACHABLE().
Referenced by FinalizeUnoptimizedCompilation().
NewScript()
Handle<Script> v8::internal::anonymous_namespace{compiler.cc}::NewScript (Isolate * isolate, ParseInfo * parse_info, DirectHandle< String > source, ScriptDetails script_details, NativesFlag natives)
Definition at line 3725 of file compiler.cc.
                                                                            {
  // Create a script object describing the script to be compiled.
  Handle<Script> script = parse_info->CreateScript(
      isolate, source, script_details.wrapped_arguments,
      script_details.origin_options, natives);
  DisallowGarbageCollection no_gc;
  SetScriptFieldsFromDetails(isolate, *script, script_details, &no_gc);
  LOG(isolate, ScriptDetails(*script));
  return script;
}
References v8::internal::ParseInfo::CreateScript(), LOG, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::ScriptDetails::origin_options, v8::internal::script, v8::internal::SetScriptFieldsFromDetails(), and v8::internal::ScriptDetails::wrapped_arguments.
Referenced by CompileScriptOnMainThread(), and v8::internal::Compiler::GetWrappedFunction().
OriginOptionsForEval()
ScriptOriginOptions v8::internal::anonymous_namespace{compiler.cc}::OriginOptionsForEval (Tagged< Object > script, ParsingWhileDebugging parsing_while_debugging)
Definition at line 370 of file compiler.cc.
                                                                          {
  bool is_shared_cross_origin =
      parsing_while_debugging == ParsingWhileDebugging::kYes;
  bool is_opaque = false;
  if (IsScript(script)) {
    auto script_origin_options = Cast<Script>(script)->origin_options();
    if (script_origin_options.IsSharedCrossOrigin()) {
      is_shared_cross_origin = true;
    }
    if (script_origin_options.IsOpaque()) {
      is_opaque = true;
    }
  }
  return ScriptOriginOptions(is_shared_cross_origin, is_opaque);
}
References v8::internal::kYes, and v8::internal::script.
Referenced by v8::internal::Compiler::GetFunctionFromEval().
PrepareException()
template<typename IsolateT >
bool v8::internal::anonymous_namespace{compiler.cc}::PrepareException (IsolateT * isolate, ParseInfo * parse_info)
Definition at line 1460 of file compiler.cc.
                                                                {
  if (parse_info->pending_error_handler()->has_pending_error()) {
    parse_info->pending_error_handler()->PrepareErrors(
        isolate, parse_info->ast_value_factory());
  }
  return false;
}
References v8::internal::ParseInfo::ast_value_factory(), v8::internal::PendingCompilationErrorHandler::has_pending_error(), v8::internal::ParseInfo::pending_error_handler(), and v8::internal::PendingCompilationErrorHandler::PrepareErrors().
Referenced by FailWithException(), and v8::internal::BackgroundCompileTask::Run().
PrepareJobWithHandleScope()
bool v8::internal::anonymous_namespace{compiler.cc}::PrepareJobWithHandleScope (OptimizedCompilationJob * job, Isolate * isolate, OptimizedCompilationInfo * compilation_info, ConcurrencyMode mode)
Definition at line 1081 of file compiler.cc.
                                                     {
  CompilationHandleScope compilation(isolate, compilation_info);
  CompilerTracer::TracePrepareJob(isolate, compilation_info, mode);
  compilation_info->ReopenAndCanonicalizeHandlesInNewScope(isolate);
  return job->PrepareJob(isolate) == CompilationJob::SUCCEEDED;
}
References mode(), v8::internal::OptimizedCompilationJob::PrepareJob(), v8::internal::OptimizedCompilationInfo::ReopenAndCanonicalizeHandlesInNewScope(), and v8::internal::CompilationJob::SUCCEEDED.
Referenced by CompileTurbofan_Concurrent(), and CompileTurbofan_NotConcurrent().
ShouldOptimize()
bool v8::internal::anonymous_namespace{compiler.cc}::ShouldOptimize (CodeKind code_kind, DirectHandle< SharedFunctionInfo > shared)
Definition at line 1206 of file compiler.cc.
                                                             {
  DCHECK(CodeKindIsOptimizedJSFunction(code_kind));
  switch (code_kind) {
    case CodeKind::TURBOFAN_JS:
      return v8_flags.turbofan && shared->PassesFilter(v8_flags.turbo_filter);
    case CodeKind::MAGLEV:
      return maglev::IsMaglevEnabled() &&
             shared->PassesFilter(v8_flags.maglev_filter);
    default:
      UNREACHABLE();
  }
}
References v8::internal::CodeKindIsOptimizedJSFunction(), v8::internal::DCHECK(), v8::internal::maglev::IsMaglevEnabled(), v8::internal::UNREACHABLE(), and v8::internal::v8_flags.
Referenced by GetOrCompileOptimized().
SpawnDuplicateConcurrentJobForStressTesting()
void v8::internal::anonymous_namespace{compiler.cc}::SpawnDuplicateConcurrentJobForStressTesting (Isolate * isolate, DirectHandle< JSFunction > function, ConcurrencyMode mode, CodeKind code_kind)
Definition at line 1434 of file compiler.cc.
                        {
  // TODO(v8:7700): Support Maglev.
  if (code_kind == CodeKind::MAGLEV) return;
  if (function->ActiveTierIsTurbofan(isolate)) return;
  DCHECK(v8_flags.stress_concurrent_inlining &&
         isolate->concurrent_recompilation_enabled() && IsSynchronous(mode) &&
         isolate->node_observer() == nullptr);
  CompileResultBehavior result_behavior =
      v8_flags.stress_concurrent_inlining_attach_code
          ? CompileResultBehavior::kDefault
          : CompileResultBehavior::kDiscardForTesting;
  USE(GetOrCompileOptimized(isolate, function, ConcurrencyMode::kConcurrent,
                            code_kind, BytecodeOffset::None(),
                            result_behavior));
}
References v8::internal::Isolate::concurrent_recompilation_enabled(), v8::internal::DCHECK(), GetOrCompileOptimized(), v8::internal::IsSynchronous(), v8::internal::kConcurrent, mode(), v8::internal::BytecodeOffset::None(), USE, and v8::internal::v8_flags.
Referenced by v8::internal::Compiler::Compile(), and v8::internal::Compiler::CompileOptimized().
UpdateSharedFunctionFlagsAfterCompilation()
void v8::internal::anonymous_namespace{compiler.cc}::UpdateSharedFunctionFlagsAfterCompilation (FunctionLiteral * literal)
Definition at line 774 of file compiler.cc.
                                                                         {
  Tagged<SharedFunctionInfo> shared_info = *literal->shared_function_info();
  DCHECK_EQ(shared_info->language_mode(), literal->language_mode());
  // These fields are all initialised in ParseInfo from the SharedFunctionInfo,
  // and then set back on the literal after parse. Hence, they should already
  // match.
  DCHECK_EQ(shared_info->requires_instance_members_initializer(),
            literal->requires_instance_members_initializer());
  DCHECK_EQ(shared_info->class_scope_has_private_brand(),
            literal->class_scope_has_private_brand());
  DCHECK_EQ(shared_info->has_static_private_methods_or_accessors(),
            literal->has_static_private_methods_or_accessors());
  shared_info->set_has_duplicate_parameters(
      literal->has_duplicate_parameters());
  shared_info->UpdateAndFinalizeExpectedNofPropertiesFromEstimate(literal);
  shared_info->SetScopeInfo(*literal->scope()->scope_info());
}
References v8::internal::FunctionLiteral::class_scope_has_private_brand(), DCHECK_EQ, v8::internal::FunctionLiteral::has_duplicate_parameters(), v8::internal::FunctionLiteral::has_static_private_methods_or_accessors(), v8::internal::FunctionLiteral::language_mode(), v8::internal::FunctionLiteral::requires_instance_members_initializer(), v8::internal::FunctionLiteral::scope(), v8::internal::Scope::scope_info(), and v8::internal::FunctionLiteral::shared_function_info().
Referenced by IterativelyExecuteAndFinalizeUnoptimizedCompilationJobs().
VerifyCodeMerge()
void v8::internal::anonymous_namespace{compiler.cc}::VerifyCodeMerge (Isolate * isolate, DirectHandle< Script > script)
Definition at line 2325 of file compiler.cc.
                                                                    {
  if (!v8_flags.reuse_scope_infos) return;
  // Check that:
  // * There aren't any duplicate scope info. Every scope/context should
  // correspond to at most one scope info.
  // * All published SFIs refer to the old script (i.e. we chose new vs old
  // correctly, and updated new SFIs where needed).
  // * All constant pool SFI entries point to an SFI referring to the old
  // script (i.e. references were updated correctly).
  std::unordered_map<int, Tagged<ScopeInfo>> scope_infos;
  for (int info_idx = 0; info_idx < script->infos()->length(); info_idx++) {
    Tagged<ScopeInfo> scope_info;
    if (!script->infos()->get(info_idx).IsWeak()) continue;
    Tagged<HeapObject> info =
        script->infos()->get(info_idx).GetHeapObjectAssumeWeak();
    if (Is<SharedFunctionInfo>(info)) {
      Tagged<SharedFunctionInfo> sfi = Cast<SharedFunctionInfo>(info);
      CHECK_EQ(sfi->script(), *script);
      if (sfi->HasBytecodeArray()) {
        Tagged<BytecodeArray> bytecode = sfi->GetBytecodeArray(isolate);
        Tagged<TrustedFixedArray> constant_pool = bytecode->constant_pool();
        for (int constant_idx = 0; constant_idx < constant_pool->length();
             ++constant_idx) {
          Tagged<Object> entry = constant_pool->get(constant_idx);
          if (Is<SharedFunctionInfo>(entry)) {
            Tagged<SharedFunctionInfo> inner_sfi =
                Cast<SharedFunctionInfo>(entry);
            int id = inner_sfi->function_literal_id(kRelaxedLoad);
            CHECK_EQ(MakeWeak(inner_sfi), script->infos()->get(id));
            CHECK_EQ(inner_sfi->script(), *script);
          }
        }
      }
      if (!sfi->scope_info()->IsEmpty()) {
        scope_info = sfi->scope_info();
      } else if (sfi->HasOuterScopeInfo()) {
        scope_info = sfi->GetOuterScopeInfo();
      } else {
        continue;
      }
    } else {
      scope_info = Cast<ScopeInfo>(info);
    }
    while (true) {
      auto it = scope_infos.find(scope_info->UniqueIdInScript());
      if (it != scope_infos.end()) {
        if (*it->second != scope_info) {
          isolate->PushParamsAndDie(reinterpret_cast<void*>(it->second->ptr()),
                                    reinterpret_cast<void*>(scope_info.ptr()));
          UNREACHABLE();
        }
        break;
      }
      scope_infos[scope_info->UniqueIdInScript()] = scope_info;
      if (!scope_info->HasOuterScopeInfo()) break;
      scope_info = scope_info->OuterScopeInfo();
    }
  }
}
References CHECK_EQ, v8::internal::constant_pool, v8::kRelaxedLoad, v8::internal::length, v8::internal::MakeWeak(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), v8::internal::Isolate::PushParamsAndDie(), v8::internal::script, v8::internal::UNREACHABLE(), and v8::internal::v8_flags.
Referenced by v8::internal::BackgroundMergeTask::CompleteMergeInForeground(), and v8::internal::BackgroundMergeTask::SetUpOnMainThread().