v8::internal::anonymous_namespace{js-collator.cc} Namespace Reference
Classes
class CollatorAvailableLocales
Enumerations
enum class Usage { SORT
, SEARCH
 }
enum class Sensitivity {
kBase
, kAccent
, kCase
, kVariant
,
kUndefined
 }
enum class CaseFirst { kUndefined
, kUpper
, kLower
, kFalse
 }
Functions
Maybe< CaseFirst > GetCaseFirst (Isolate *isolate, DirectHandle< JSReceiver > options, const char *method_name)
void CreateDataPropertyForOptions (Isolate *isolate, DirectHandle< JSObject > options, DirectHandle< String > key, const char *value)
void CreateDataPropertyForOptions (Isolate *isolate, DirectHandle< JSObject > options, DirectHandle< String > key, bool value)
CaseFirst ToCaseFirst (const char *str)
UColAttributeValue ToUColAttributeValue (CaseFirst case_first)
void SetNumericOption (icu::Collator *icu_collator, bool numeric)
void SetCaseFirstOption (icu::Collator *icu_collator, CaseFirst case_first)
Enumeration Type Documentation
CaseFirst
enum v8::internal::anonymous_namespace{js-collator.cc}::CaseFirst [strong]
Enumerator
kUndefined
kUpper
kLower
kFalse
Definition at line 44 of file js-collator.cc.
{ kUndefined, kUpper, kLower, kFalse };
Sensitivity
enum v8::internal::anonymous_namespace{js-collator.cc}::Sensitivity [strong]
Enumerator
kBase
kAccent
kCase
kVariant
kUndefined
Definition at line 35 of file js-collator.cc.
                       {
  kBase,
  kAccent,
  kCase,
  kVariant,
  kUndefined,
};
Usage
enum v8::internal::anonymous_namespace{js-collator.cc}::Usage [strong]
Enumerator
SORT
SEARCH
Definition at line 30 of file js-collator.cc.
                 {
  SORT,
  SEARCH,
};
Function Documentation
CreateDataPropertyForOptions() [1/2]
void v8::internal::anonymous_namespace{js-collator.cc}::CreateDataPropertyForOptions (Isolate * isolate, DirectHandle< JSObject > options, DirectHandle< String > key, bool value)
Definition at line 72 of file js-collator.cc.
                                                                        {
  DirectHandle<Object> value_obj = isolate->factory()->ToBoolean(value);
  // This is a brand new JSObject that shouldn't already have the same
  // key so this shouldn't fail.
  Maybe<bool> maybe = JSReceiver::CreateDataProperty(
      isolate, options, key, value_obj, Just(kDontThrow));
  DCHECK(maybe.FromJust());
  USE(maybe);
}
References v8::internal::JSReceiver::CreateDataProperty(), v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::Maybe< T >::FromJust(), v8::Just(), v8::internal::kDontThrow, v8::internal::key, v8::internal::FactoryBase< Impl >::ToBoolean(), USE, and v8::internal::value.
Referenced by v8::internal::JSCollator::ResolvedOptions().
CreateDataPropertyForOptions() [2/2]
void v8::internal::anonymous_namespace{js-collator.cc}::CreateDataPropertyForOptions (Isolate * isolate, DirectHandle< JSObject > options, DirectHandle< String > key, const char * value)
Definition at line 57 of file js-collator.cc.
                                                                               {
  DCHECK_NOT_NULL(value);
  DirectHandle<String> value_str =
      isolate->factory()->NewStringFromAsciiChecked(value);
  // This is a brand new JSObject that shouldn't already have the same
  // key so this shouldn't fail.
  Maybe<bool> maybe = JSReceiver::CreateDataProperty(
      isolate, options, key, value_str, Just(kDontThrow));
  DCHECK(maybe.FromJust());
  USE(maybe);
}
References v8::internal::JSReceiver::CreateDataProperty(), v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::Isolate::factory(), v8::Maybe< T >::FromJust(), v8::Just(), v8::internal::kDontThrow, v8::internal::key, v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), USE, and v8::internal::value.
GetCaseFirst()
Maybe<CaseFirst> v8::internal::anonymous_namespace{js-collator.cc}::GetCaseFirst (Isolate * isolate, DirectHandle< JSReceiver > options, const char * method_name)
Definition at line 46 of file js-collator.cc.
                                                       {
  return GetStringOption<CaseFirst>(
      isolate, options, "caseFirst", method_name,
      std::to_array<const std::string_view>({"upper", "lower", "false"}),
      std::array{CaseFirst::kUpper, CaseFirst::kLower, CaseFirst::kFalse},
      CaseFirst::kUndefined);
}
References v8::internal::kFalse.
Referenced by v8::internal::JSCollator::New().
SetCaseFirstOption()
void v8::internal::anonymous_namespace{js-collator.cc}::SetCaseFirstOption (icu::Collator * icu_collator, CaseFirst case_first)
Definition at line 270 of file js-collator.cc.
                                                                         {
  DCHECK_NOT_NULL(icu_collator);
  UErrorCode status = U_ZERO_ERROR;
  icu_collator->setAttribute(UCOL_CASE_FIRST, ToUColAttributeValue(case_first),
                             status);
  DCHECK(U_SUCCESS(status));
}
References v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::status, and ToUColAttributeValue().
Referenced by v8::internal::JSCollator::New().
SetNumericOption()
void v8::internal::anonymous_namespace{js-collator.cc}::SetNumericOption (icu::Collator * icu_collator, bool numeric)
Definition at line 262 of file js-collator.cc.
                                                               {
  DCHECK_NOT_NULL(icu_collator);
  UErrorCode status = U_ZERO_ERROR;
  icu_collator->setAttribute(UCOL_NUMERIC_COLLATION,
                             numeric ? UCOL_ON : UCOL_OFF, status);
  DCHECK(U_SUCCESS(status));
}
References v8::internal::DCHECK(), DCHECK_NOT_NULL, and v8::internal::status.
Referenced by v8::internal::JSCollator::New().
ToCaseFirst()
CaseFirst v8::internal::anonymous_namespace{js-collator.cc}::ToCaseFirst (const char * str)
Definition at line 243 of file js-collator.cc.
                                       {
  if (strcmp(str, "upper") == 0) return CaseFirst::kUpper;
  if (strcmp(str, "lower") == 0) return CaseFirst::kLower;
  if (strcmp(str, "false") == 0) return CaseFirst::kFalse;
  return CaseFirst::kUndefined;
}
References v8::internal::kFalse.
Referenced by v8::internal::JSCollator::New().
ToUColAttributeValue()
UColAttributeValue v8::internal::anonymous_namespace{js-collator.cc}::ToUColAttributeValue (CaseFirst case_first)
Definition at line 250 of file js-collator.cc.
                                                              {
  switch (case_first) {
    case CaseFirst::kUpper:
      return UCOL_UPPER_FIRST;
    case CaseFirst::kLower:
      return UCOL_LOWER_FIRST;
    case CaseFirst::kFalse:
    case CaseFirst::kUndefined:
      return UCOL_OFF;
  }
}
References v8::internal::kFalse.
Referenced by SetCaseFirstOption().