v8::internal::wasm::anonymous_namespace{wasm-objects.cc} Namespace Reference
Functions
bool CheckExpectedSharedness (Isolate *isolate, DirectHandle< Object > value, CanonicalValueType expected, const char **error_message)
bool ConvertToSharedIfExpected (Isolate *isolate, DirectHandle< Object > *value, CanonicalValueType expected, const char **error_message)
Function Documentation
CheckExpectedSharedness()
bool v8::internal::wasm::anonymous_namespace{wasm-objects.cc}::CheckExpectedSharedness (Isolate * isolate, DirectHandle< Object > value, CanonicalValueType expected, const char ** error_message) [inline]
Definition at line 3372 of file wasm-objects.cc.
                                                                {
  if (v8_flags.experimental_wasm_shared && (*value).IsHeapObject()) {
    Tagged<HeapObject> heap_obj = (*value).cast<HeapObject>();
    if (expected.is_shared() != HeapLayout::InWritableSharedSpace(heap_obj)) {
      *error_message =
          expected.is_shared()
              ? "unshared object is not allowed for shared heap types"
              : "shared object is not allowed for unshared heap types";
      return false;
    }
  }
  return true;
}
References v8::internal::Tagged< HeapObject >::cast(), v8::internal::HeapLayout::InWritableSharedSpace(), v8::internal::wasm::ValueTypeBase::is_shared(), and v8::internal::v8_flags.
Referenced by v8::internal::wasm::JSToWasmObject().
ConvertToSharedIfExpected()
bool v8::internal::wasm::anonymous_namespace{wasm-objects.cc}::ConvertToSharedIfExpected (Isolate * isolate, DirectHandle< Object > * value, CanonicalValueType expected, const char ** error_message) [inline]
Definition at line 3389 of file wasm-objects.cc.
                                                                  {
  if (v8_flags.experimental_wasm_shared && expected.is_shared() &&
      (**value).IsHeapObject()) {
    Tagged<HeapObject> heap_obj = (**value).cast<HeapObject>();
    if (!HeapLayout::InWritableSharedSpace(heap_obj)) {
      if (!Object::Share(isolate, *value, ShouldThrow::kDontThrow)
               .ToHandle(value)) {
        *error_message = "unshared object is not allowed for shared heap types";
        return false;
      }
    }
  }
  return true;
}
References v8::internal::Tagged< HeapObject >::cast(), v8::internal::HeapLayout::InWritableSharedSpace(), v8::internal::wasm::ValueTypeBase::is_shared(), v8::internal::kDontThrow, v8::internal::v8_flags, and v8::internal::value.
Referenced by v8::internal::wasm::JSToWasmObject().