v8::internal::compiler::anonymous_namespace{code-generator-ia32.cc} Namespace Reference
Classes
class OutOfLineLoadFloat32NaN
class OutOfLineLoadFloat64NaN
class OutOfLineTruncateDoubleToI
class OutOfLineRecordWrite
Functions
bool HasAddressingMode (Instruction *instr)
bool HasImmediateInput (Instruction *instr, size_t index)
bool HasRegisterInput (Instruction *instr, size_t index)
void AdjustStackPointerForTailCall (MacroAssembler *masm, FrameAccessState *state, int new_slot_above_sp, bool allow_shrinkage=true)
Function Documentation
AdjustStackPointerForTailCall()
void v8::internal::compiler::anonymous_namespace{code-generator-ia32.cc}::AdjustStackPointerForTailCall (MacroAssembler * masm, FrameAccessState * state, int new_slot_above_sp, bool allow_shrinkage = true)
Definition at line 558 of file code-generator-ia32.cc.
                                                                {
  int current_sp_offset = state->GetSPToFPSlotCount() +
                          StandardFrameConstants::kFixedSlotCountAboveFp;
  int stack_slot_delta = new_slot_above_sp - current_sp_offset;
  if (stack_slot_delta > 0) {
    masm->AllocateStackSpace(stack_slot_delta * kSystemPointerSize);
    state->IncreaseSPDelta(stack_slot_delta);
  } else if (allow_shrinkage && stack_slot_delta < 0) {
    masm->add(esp, Immediate(-stack_slot_delta * kSystemPointerSize));
    state->IncreaseSPDelta(stack_slot_delta);
  }
}
References v8::internal::Assembler::add(), v8::internal::MacroAssembler::AllocateStackSpace(), v8::internal::compiler::FrameAccessState::GetSPToFPSlotCount(), v8::internal::compiler::FrameAccessState::IncreaseSPDelta(), v8::internal::CommonFrameConstants::kFixedSlotCountAboveFp, and v8::internal::kSystemPointerSize.
HasAddressingMode()
bool v8::internal::compiler::anonymous_namespace{code-generator-ia32.cc}::HasAddressingMode (Instruction * instr)
Definition at line 208 of file code-generator-ia32.cc.
                                           {
  return instr->addressing_mode() != kMode_None;
}
References v8::internal::compiler::Instruction::addressing_mode().
HasImmediateInput()
bool v8::internal::compiler::anonymous_namespace{code-generator-ia32.cc}::HasImmediateInput (Instruction * instr, size_t index)
Definition at line 212 of file code-generator-ia32.cc.
                                                         {
  return instr->InputAt(index)->IsImmediate();
}
References v8::internal::index, and v8::internal::compiler::Instruction::InputAt().
HasRegisterInput()
bool v8::internal::compiler::anonymous_namespace{code-generator-ia32.cc}::HasRegisterInput (Instruction * instr, size_t index)
Definition at line 216 of file code-generator-ia32.cc.
                                                        {
  return instr->InputAt(index)->IsRegister();
}
References v8::internal::index, v8::internal::compiler::Instruction::InputAt(), and v8::internal::compiler::InstructionOperand::IsRegister().