v8::internal::compiler::anonymous_namespace{instruction.cc} Namespace Reference
Functions
size_t GetConservativeFrameSizeInBytes (FrameStateType type, size_t parameters_count, size_t locals_count, BytecodeOffset bailout_id, uint32_t wasm_liftoff_frame_size)
size_t GetTotalConservativeFrameSizeInBytes (FrameStateType type, size_t parameters_count, size_t locals_count, BytecodeOffset bailout_id, uint32_t wasm_liftoff_frame_size, FrameStateDescriptor *outer_state)
Function Documentation
GetConservativeFrameSizeInBytes()
size_t v8::internal::compiler::anonymous_namespace{instruction.cc}::GetConservativeFrameSizeInBytes (FrameStateType type, size_t parameters_count, size_t locals_count, BytecodeOffset bailout_id, uint32_t wasm_liftoff_frame_size)
Definition at line 1149 of file instruction.cc.
                                                                         {
  switch (type) {
    case FrameStateType::kUnoptimizedFunction: {
      auto info = UnoptimizedFrameInfo::Conservative(
          static_cast<int>(parameters_count), static_cast<int>(locals_count));
      return info.frame_size_in_bytes();
    }
    case FrameStateType::kInlinedExtraArguments:
      // The inlined extra arguments frame state is only used in the deoptimizer
      // and does not occupy any extra space in the stack.
      // Check out the design doc:
      // https://docs.google.com/document/d/150wGaUREaZI6YWqOQFD5l2mWQXaPbbZjcAIJLOFrzMs/edit
      // We just need to account for the additional parameters we might push
      // here.
      return UnoptimizedFrameInfo::GetStackSizeForAdditionalArguments(
          static_cast<int>(parameters_count));
#if V8_ENABLE_WEBASSEMBLY
    case FrameStateType::kWasmInlinedIntoJS:
#endif
    case FrameStateType::kConstructCreateStub: {
      auto info = ConstructStubFrameInfo::Conservative(
          static_cast<int>(parameters_count));
      return info.frame_size_in_bytes();
    }
    case FrameStateType::kConstructInvokeStub:
      return FastConstructStubFrameInfo::Conservative().frame_size_in_bytes();
    case FrameStateType::kBuiltinContinuation:
#if V8_ENABLE_WEBASSEMBLY
    case FrameStateType::kJSToWasmBuiltinContinuation:
#endif // V8_ENABLE_WEBASSEMBLY
    case FrameStateType::kJavaScriptBuiltinContinuation:
    case FrameStateType::kJavaScriptBuiltinContinuationWithCatch: {
      const RegisterConfiguration* config = RegisterConfiguration::Default();
      auto info = BuiltinContinuationFrameInfo::Conservative(
          static_cast<int>(parameters_count),
          Builtins::CallInterfaceDescriptorFor(
              Builtins::GetBuiltinFromBytecodeOffset(bailout_id)),
          config);
      return info.frame_size_in_bytes();
    }
#if V8_ENABLE_WEBASSEMBLY
    case FrameStateType::kLiftoffFunction:
      return wasm_liftoff_frame_size;
#endif // V8_ENABLE_WEBASSEMBLY
  }
  UNREACHABLE();
}
References v8::internal::Builtins::CallInterfaceDescriptorFor(), v8::internal::FastConstructStubFrameInfo::Conservative(), v8::internal::ConstructStubFrameInfo::Conservative(), v8::internal::BuiltinContinuationFrameInfo::Conservative(), v8::internal::UnoptimizedFrameInfo::Conservative(), v8::internal::RegisterConfiguration::Default(), v8::internal::FastConstructStubFrameInfo::frame_size_in_bytes(), v8::internal::Builtins::GetBuiltinFromBytecodeOffset(), v8::internal::UnoptimizedFrameInfo::GetStackSizeForAdditionalArguments(), v8::internal::compiler::kBuiltinContinuation, v8::internal::compiler::kConstructCreateStub, v8::internal::compiler::kConstructInvokeStub, v8::internal::compiler::kInlinedExtraArguments, v8::internal::compiler::kJavaScriptBuiltinContinuation, v8::internal::compiler::kJavaScriptBuiltinContinuationWithCatch, v8::internal::compiler::kUnoptimizedFunction, v8::internal::tracing::type, and v8::internal::UNREACHABLE().
Referenced by GetTotalConservativeFrameSizeInBytes().
GetTotalConservativeFrameSizeInBytes()
size_t v8::internal::compiler::anonymous_namespace{instruction.cc}::GetTotalConservativeFrameSizeInBytes (FrameStateType type, size_t parameters_count, size_t locals_count, BytecodeOffset bailout_id, uint32_t wasm_liftoff_frame_size, FrameStateDescriptor * outer_state)
Definition at line 1201 of file instruction.cc.
                                                                               {
  size_t outer_total_conservative_frame_size_in_bytes =
      (outer_state == nullptr)
          ? 0
          : outer_state->total_conservative_frame_size_in_bytes();
  return GetConservativeFrameSizeInBytes(type, parameters_count, locals_count,
                                         bailout_id, wasm_liftoff_frame_size) +
         outer_total_conservative_frame_size_in_bytes;
}
References GetConservativeFrameSizeInBytes(), v8::internal::compiler::FrameStateDescriptor::total_conservative_frame_size_in_bytes(), and v8::internal::tracing::type.