v8::internal::compiler::anonymous_namespace{simplified-lowering.cc} Namespace Reference
Classes
class JSONGraphWriterWithVerifierTypes
Functions
MachineRepresentation MachineRepresentationFromArrayType (ExternalArrayType array_type)
UseInfo CheckedUseInfoAsWord32FromHint (NumberOperationHint hint, IdentifyZeros identify_zeros=kDistinguishZeros, const FeedbackSource &feedback=FeedbackSource())
UseInfo CheckedUseInfoAsFloat64FromHint (NumberOperationHint hint, const FeedbackSource &feedback, IdentifyZeros identify_zeros=kDistinguishZeros)
UseInfo TruncatingUseInfoFromRepresentation (MachineRepresentation rep, const Type &type_hint=Type::Any())
UseInfo UseInfoForBasePointer (const FieldAccess &access)
UseInfo UseInfoForBasePointer (const ElementAccess &access)
void ReplaceEffectControlUses (Node *node, Node *effect, Node *control)
bool CanOverflowSigned32 (const Operator *op, Type left, Type right, TypeCache const *type_cache, Zone *type_zone)
bool IsSomePositiveOrderedNumber (Type type)
bool IsLargeBigInt (Type type)
bool IsLoadFloat16ArrayElement (Node *node)
Function Documentation
CanOverflowSigned32()
bool v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::CanOverflowSigned32 (const Operator * op, Type left, Type right, TypeCache const * type_cache, Zone * type_zone)
Definition at line 214 of file simplified-lowering.cc.
                                                                       {
  // We assume the inputs are checked Signed32 (or known statically to be
  // Signed32). Technically, the inputs could also be minus zero, which we treat
  // as 0 for the purpose of this function.
  if (left.Maybe(Type::MinusZero())) {
    left = Type::Union(left, type_cache->kSingletonZero, type_zone);
  }
  if (right.Maybe(Type::MinusZero())) {
    right = Type::Union(right, type_cache->kSingletonZero, type_zone);
  }
  left = Type::Intersect(left, Type::Signed32(), type_zone);
  right = Type::Intersect(right, Type::Signed32(), type_zone);
  if (left.IsNone() || right.IsNone()) return false;
  switch (op->opcode()) {
    case IrOpcode::kSpeculativeSmallIntegerAdd:
      return (left.Max() + right.Max() > kMaxInt) ||
             (left.Min() + right.Min() < kMinInt);
    case IrOpcode::kSpeculativeSmallIntegerSubtract:
      return (left.Max() - right.Min() > kMaxInt) ||
             (left.Min() - right.Max() < kMinInt);
    default:
      UNREACHABLE();
  }
}
References v8::internal::compiler::Type::Intersect(), v8::internal::compiler::Type::IsNone(), v8::internal::kMaxInt, v8::internal::kMinInt, v8::internal::compiler::TypeCache::kSingletonZero, v8::internal::compiler::Type::Max(), v8::internal::compiler::Type::Maybe(), v8::internal::compiler::Type::Min(), v8::internal::compiler::Operator::opcode(), v8::internal::compiler::Type::Union(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::RepresentationSelector::VisitSpeculativeSmallIntegerAdditiveOp().
CheckedUseInfoAsFloat64FromHint()
UseInfo v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::CheckedUseInfoAsFloat64FromHint (NumberOperationHint hint, const FeedbackSource & feedback, IdentifyZeros identify_zeros = kDistinguishZeros)
Definition at line 133 of file simplified-lowering.cc.
                                                      {
  switch (hint) {
    case NumberOperationHint::kSignedSmall:
    case NumberOperationHint::kSignedSmallInputs:
      // Not used currently.
      UNREACHABLE();
    case NumberOperationHint::kAdditiveSafeInteger:
    case NumberOperationHint::kNumber:
      return UseInfo::CheckedNumberAsFloat64(identify_zeros, feedback);
    case NumberOperationHint::kNumberOrBoolean:
      return UseInfo::CheckedNumberOrBooleanAsFloat64(identify_zeros, feedback);
    case NumberOperationHint::kNumberOrOddball:
      return UseInfo::CheckedNumberOrOddballAsFloat64(identify_zeros, feedback);
  }
  UNREACHABLE();
}
References v8::internal::compiler::UseInfo::CheckedNumberAsFloat64(), v8::internal::compiler::UseInfo::CheckedNumberOrBooleanAsFloat64(), v8::internal::compiler::UseInfo::CheckedNumberOrOddballAsFloat64(), v8::internal::compiler::kAdditiveSafeInteger, v8::internal::compiler::kNumber, v8::internal::compiler::kNumberOrBoolean, v8::internal::compiler::kNumberOrOddball, v8::internal::compiler::kSignedSmall, v8::internal::compiler::kSignedSmallInputs, and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::RepresentationSelector::VisitNode().
CheckedUseInfoAsWord32FromHint()
UseInfo v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::CheckedUseInfoAsWord32FromHint (NumberOperationHint hint, IdentifyZeros identify_zeros = kDistinguishZeros, const FeedbackSource & feedback = FeedbackSource())
Definition at line 112 of file simplified-lowering.cc.
                                                       {
  switch (hint) {
    case NumberOperationHint::kSignedSmall:
    case NumberOperationHint::kSignedSmallInputs:
      return UseInfo::CheckedSignedSmallAsWord32(identify_zeros, feedback);
    case NumberOperationHint::kAdditiveSafeInteger:
    case NumberOperationHint::kNumber:
      DCHECK_EQ(identify_zeros, kIdentifyZeros);
      return UseInfo::CheckedNumberAsWord32(feedback);
    case NumberOperationHint::kNumberOrBoolean:
      // Not used currently.
      UNREACHABLE();
    case NumberOperationHint::kNumberOrOddball:
      DCHECK_EQ(identify_zeros, kIdentifyZeros);
      return UseInfo::CheckedNumberOrOddballAsWord32(feedback);
  }
  UNREACHABLE();
}
References v8::internal::compiler::UseInfo::CheckedNumberAsWord32(), v8::internal::compiler::UseInfo::CheckedNumberOrOddballAsWord32(), v8::internal::compiler::UseInfo::CheckedSignedSmallAsWord32(), DCHECK_EQ, v8::internal::compiler::kAdditiveSafeInteger, v8::internal::compiler::kIdentifyZeros, v8::internal::compiler::kNumber, v8::internal::compiler::kNumberOrBoolean, v8::internal::compiler::kNumberOrOddball, v8::internal::compiler::kSignedSmall, v8::internal::compiler::kSignedSmallInputs, and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::RepresentationSelector::VisitNode(), v8::internal::compiler::RepresentationSelector::VisitSpeculativeInt32Binop(), v8::internal::compiler::RepresentationSelector::VisitSpeculativeNumberModulus(), and v8::internal::compiler::RepresentationSelector::VisitSpeculativeSmallIntegerAdditiveOp().
IsLargeBigInt()
bool v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::IsLargeBigInt (Type type) [inline]
Definition at line 246 of file simplified-lowering.cc.
                                     {
  return type.Is(Type::BigInt()) && !type.Is(Type::SignedBigInt64()) &&
         !type.Is(Type::UnsignedBigInt64());
}
References v8::internal::tracing::type.
Referenced by v8::internal::compiler::RepresentationSelector::VisitFrameState(), v8::internal::compiler::RepresentationSelector::VisitObjectState(), and v8::internal::compiler::RepresentationSelector::VisitStateValues().
IsLoadFloat16ArrayElement()
bool v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::IsLoadFloat16ArrayElement (Node * node)
Definition at line 268 of file simplified-lowering.cc.
                                           {
  Operator::Opcode opcode = node->op()->opcode();
  return (opcode == IrOpcode::kLoadTypedElement ||
          opcode == IrOpcode::kLoadDataViewElement) &&
         ExternalArrayTypeOf(node->op()) == kExternalFloat16Array;
}
References v8::internal::compiler::ExternalArrayTypeOf(), v8::internal::kExternalFloat16Array, v8::internal::compiler::Node::op(), and v8::internal::compiler::Operator::opcode().
Referenced by v8::internal::compiler::RepresentationSelector::VisitFrameState(), v8::internal::compiler::RepresentationSelector::VisitObjectState(), and v8::internal::compiler::RepresentationSelector::VisitStateValues().
IsSomePositiveOrderedNumber()
bool v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::IsSomePositiveOrderedNumber (Type type)
Definition at line 242 of file simplified-lowering.cc.
                                            {
  return type.Is(Type::OrderedNumber()) && (type.IsNone() || type.Min() > 0);
}
References v8::internal::tracing::type.
Referenced by v8::internal::compiler::RepresentationSelector::VisitForCheckedInt32Mul().
MachineRepresentationFromArrayType()
MachineRepresentation v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::MachineRepresentationFromArrayType (ExternalArrayType array_type)
Definition at line 86 of file simplified-lowering.cc.
                                  {
  switch (array_type) {
    case kExternalUint8Array:
    case kExternalUint8ClampedArray:
    case kExternalInt8Array:
      return MachineRepresentation::kWord8;
    case kExternalUint16Array:
    case kExternalInt16Array:
      return MachineRepresentation::kWord16;
    case kExternalUint32Array:
    case kExternalInt32Array:
      return MachineRepresentation::kWord32;
    case kExternalFloat16Array:
      return MachineRepresentation::kFloat16RawBits;
    case kExternalFloat32Array:
      return MachineRepresentation::kFloat32;
    case kExternalFloat64Array:
      return MachineRepresentation::kFloat64;
    case kExternalBigInt64Array:
    case kExternalBigUint64Array:
      return MachineRepresentation::kWord64;
  }
  UNREACHABLE();
}
References v8::internal::kExternalBigInt64Array, v8::internal::kExternalBigUint64Array, v8::internal::kExternalFloat16Array, v8::internal::kExternalFloat32Array, v8::internal::kExternalFloat64Array, v8::internal::kExternalInt16Array, v8::internal::kExternalInt32Array, v8::internal::kExternalInt8Array, v8::internal::kExternalUint16Array, v8::internal::kExternalUint32Array, v8::internal::kExternalUint8Array, v8::internal::kExternalUint8ClampedArray, v8::internal::kFloat16RawBits, v8::internal::kFloat32, v8::internal::kFloat64, v8::internal::kWord16, v8::internal::kWord32, v8::internal::kWord64, v8::internal::kWord8, and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::RepresentationSelector::VisitNode().
ReplaceEffectControlUses()
void v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::ReplaceEffectControlUses (Node * node, Node * effect, Node * control)
Definition at line 201 of file simplified-lowering.cc.
                                                                       {
  for (Edge edge : node->use_edges()) {
    if (NodeProperties::IsControlEdge(edge)) {
      edge.UpdateTo(control);
    } else if (NodeProperties::IsEffectEdge(edge)) {
      edge.UpdateTo(effect);
    } else {
      DCHECK(NodeProperties::IsValueEdge(edge) ||
             NodeProperties::IsContextEdge(edge));
    }
  }
}
References v8::internal::DCHECK(), v8::internal::compiler::NodeProperties::IsContextEdge(), v8::internal::compiler::NodeProperties::IsControlEdge(), v8::internal::compiler::NodeProperties::IsEffectEdge(), v8::internal::compiler::NodeProperties::IsValueEdge(), and v8::internal::compiler::Node::use_edges().
Referenced by v8::internal::compiler::RepresentationSelector::ChangeToDeadValue(), v8::internal::compiler::RepresentationSelector::ChangeToPureOp(), v8::internal::compiler::RepresentationSelector::ChangeUnaryToPureBinaryOp(), v8::internal::compiler::RepresentationSelector::DisconnectFromEffectAndControl(), and v8::internal::compiler::RepresentationSelector::ReplaceWithPureNode().
TruncatingUseInfoFromRepresentation()
UseInfo v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::TruncatingUseInfoFromRepresentation (MachineRepresentation rep, const Type & type_hint = Type::Any())
Definition at line 152 of file simplified-lowering.cc.
                                                                  {
  switch (rep) {
    case MachineRepresentation::kTaggedSigned:
      return UseInfo::TaggedSigned();
    case MachineRepresentation::kTaggedPointer:
    case MachineRepresentation::kTagged:
    case MachineRepresentation::kIndirectPointer:
    case MachineRepresentation::kMapWord:
      return UseInfo::AnyTagged();
    case MachineRepresentation::kFloat64:
#ifdef V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
      if (type_hint.Maybe(Type::Undefined())) {
        return UseInfo::TruncatingFloat64OrUndefined();
      }
#endif // V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
      return UseInfo::TruncatingFloat64();
    case MachineRepresentation::kFloat32:
      return UseInfo::Float32();
    case MachineRepresentation::kFloat16RawBits:
      return UseInfo::Float16RawBits();
    case MachineRepresentation::kWord8:
    case MachineRepresentation::kWord16:
    case MachineRepresentation::kWord32:
      return UseInfo::TruncatingWord32();
    case MachineRepresentation::kWord64:
      return UseInfo::TruncatingWord64();
    case MachineRepresentation::kBit:
      return UseInfo::Bool();
    case MachineRepresentation::kCompressedPointer:
    case MachineRepresentation::kCompressed:
    case MachineRepresentation::kProtectedPointer:
    case MachineRepresentation::kSandboxedPointer:
    case MachineRepresentation::kFloat16:
    case MachineRepresentation::kSimd128:
    case MachineRepresentation::kSimd256:
    case MachineRepresentation::kNone:
      UNREACHABLE();
  }
}
References v8::internal::compiler::UseInfo::AnyTagged(), v8::internal::compiler::UseInfo::Bool(), v8::internal::compiler::UseInfo::Float16RawBits(), v8::internal::compiler::UseInfo::Float32(), v8::internal::kBit, v8::internal::kCompressed, v8::internal::kCompressedPointer, v8::internal::kFloat16, v8::internal::kFloat16RawBits, v8::internal::kFloat32, v8::internal::kFloat64, v8::internal::kIndirectPointer, v8::internal::kMapWord, v8::internal::kNone, v8::internal::kProtectedPointer, v8::internal::kSandboxedPointer, v8::internal::kSimd128, v8::internal::kSimd256, v8::internal::kTagged, v8::internal::kTaggedPointer, v8::internal::kTaggedSigned, v8::internal::kWord16, v8::internal::kWord32, v8::internal::kWord64, v8::internal::kWord8, v8::internal::compiler::UseInfo::TaggedSigned(), v8::internal::compiler::UseInfo::TruncatingFloat64(), v8::internal::compiler::UseInfo::TruncatingFloat64OrUndefined(), v8::internal::compiler::UseInfo::TruncatingWord32(), v8::internal::compiler::UseInfo::TruncatingWord64(), v8::internal::compiler::Undefined, and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::RepresentationSelector::VisitCall(), v8::internal::compiler::RepresentationSelector::VisitFastApiCall(), and v8::internal::compiler::RepresentationSelector::VisitNode().
UseInfoForBasePointer() [1/2]
UseInfo v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::UseInfoForBasePointer (const ElementAccess & access)
Definition at line 197 of file simplified-lowering.cc.
                                                           {
  return access.tag() != 0 ? UseInfo::AnyTagged() : UseInfo::Word();
}
References v8::internal::compiler::UseInfo::AnyTagged(), v8::internal::compiler::ElementAccess::tag(), and v8::internal::compiler::UseInfo::Word().
Referenced by v8::internal::compiler::RepresentationSelector::VisitNode().
UseInfoForBasePointer() [2/2]
UseInfo v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::UseInfoForBasePointer (const FieldAccess & access)
Definition at line 193 of file simplified-lowering.cc.
                                                         {
  return access.tag() != 0 ? UseInfo::AnyTagged() : UseInfo::Word();
}
References v8::internal::compiler::UseInfo::AnyTagged(), v8::internal::compiler::FieldAccess::tag(), and v8::internal::compiler::UseInfo::Word().