cppgc::internal::anonymous_namespace{stats-collector.cc} Namespace Reference
Functions
int64_t SumPhases (const MetricRecorder::GCCycle::Phases &phases)
MetricRecorder::GCCycle GetCycleEventForMetricRecorder (CollectionType type, StatsCollector::MarkingType marking_type, StatsCollector::SweepingType sweeping_type, int64_t atomic_mark_us, int64_t atomic_weak_us, int64_t atomic_compact_us, int64_t atomic_sweep_us, int64_t incremental_mark_us, int64_t incremental_sweep_us, int64_t concurrent_mark_us, int64_t concurrent_sweep_us, int64_t objects_before_bytes, int64_t objects_after_bytes, int64_t objects_freed_bytes, int64_t memory_before_bytes, int64_t memory_after_bytes, int64_t memory_freed_bytes)
Function Documentation
GetCycleEventForMetricRecorder()
MetricRecorder::GCCycle cppgc::internal::anonymous_namespace{stats-collector.cc}::GetCycleEventForMetricRecorder (CollectionType type, StatsCollector::MarkingType marking_type, StatsCollector::SweepingType sweeping_type, int64_t atomic_mark_us, int64_t atomic_weak_us, int64_t atomic_compact_us, int64_t atomic_sweep_us, int64_t incremental_mark_us, int64_t incremental_sweep_us, int64_t concurrent_mark_us, int64_t concurrent_sweep_us, int64_t objects_before_bytes, int64_t objects_after_bytes, int64_t objects_freed_bytes, int64_t memory_before_bytes, int64_t memory_after_bytes, int64_t memory_freed_bytes)
Definition at line 181 of file stats-collector.cc.
                                                            {
  MetricRecorder::GCCycle event;
  event.type = (type == CollectionType::kMajor)
                   ? MetricRecorder::GCCycle::Type::kMajor
                   : MetricRecorder::GCCycle::Type::kMinor;
  // MainThread.Incremental:
  event.main_thread_incremental.mark_duration_us =
      marking_type != StatsCollector::MarkingType::kAtomic ? incremental_mark_us
                                                           : -1;
  event.main_thread_incremental.sweep_duration_us =
      sweeping_type != StatsCollector::SweepingType::kAtomic
          ? incremental_sweep_us
          : -1;
  // MainThread.Atomic:
  event.main_thread_atomic.mark_duration_us = atomic_mark_us;
  event.main_thread_atomic.weak_duration_us = atomic_weak_us;
  event.main_thread_atomic.compact_duration_us = atomic_compact_us;
  event.main_thread_atomic.sweep_duration_us = atomic_sweep_us;
  // MainThread:
  event.main_thread.mark_duration_us =
      event.main_thread_atomic.mark_duration_us + incremental_mark_us;
  event.main_thread.weak_duration_us =
      event.main_thread_atomic.weak_duration_us;
  event.main_thread.compact_duration_us =
      event.main_thread_atomic.compact_duration_us;
  event.main_thread.sweep_duration_us =
      event.main_thread_atomic.sweep_duration_us + incremental_sweep_us;
  // Total:
  event.total.mark_duration_us =
      event.main_thread.mark_duration_us + concurrent_mark_us;
  event.total.weak_duration_us = event.main_thread.weak_duration_us;
  event.total.compact_duration_us = event.main_thread.compact_duration_us;
  event.total.sweep_duration_us =
      event.main_thread.sweep_duration_us + concurrent_sweep_us;
  // Objects:
  event.objects.before_bytes = objects_before_bytes;
  event.objects.after_bytes = objects_after_bytes;
  event.objects.freed_bytes = objects_freed_bytes;
  // Memory:
  event.memory.before_bytes = memory_before_bytes;
  event.memory.after_bytes = memory_after_bytes;
  event.memory.freed_bytes = memory_freed_bytes;
  // Collection Rate:
  if (event.objects.before_bytes == 0) {
    event.collection_rate_in_percent = 0;
  } else {
    event.collection_rate_in_percent =
        static_cast<double>(event.objects.freed_bytes) /
        event.objects.before_bytes;
  }
  // Efficiency:
  if (event.objects.freed_bytes == 0) {
    event.efficiency_in_bytes_per_us = 0;
    event.main_thread_efficiency_in_bytes_per_us = 0;
  } else {
    // Here, SumPhases(event.main_thread) or even SumPhases(event.total) can be
    // zero if the clock resolution is not small enough and the entire GC was
    // very short, so the timed value was zero. This appears to happen on
    // Windows, see crbug.com/1338256 and crbug.com/1339180. In this case, we
    // are only here if the number of freed bytes is nonzero and the division
    // below produces an infinite value.
    event.efficiency_in_bytes_per_us =
        static_cast<double>(event.objects.freed_bytes) / SumPhases(event.total);
    event.main_thread_efficiency_in_bytes_per_us =
        static_cast<double>(event.objects.freed_bytes) /
        SumPhases(event.main_thread);
  }
  return event;
}
References cppgc::internal::MetricRecorder::GCCycle::Sizes::before_bytes, cppgc::internal::MetricRecorder::GCCycle::Sizes::freed_bytes, cppgc::Heap::kAtomic, cppgc::internal::kMajor, cppgc::internal::MetricRecorder::GCCycle::kMajor, cppgc::internal::MetricRecorder::GCCycle::kMinor, cppgc::internal::MetricRecorder::GCCycle::main_thread, cppgc::internal::MetricRecorder::GCCycle::objects, SumPhases(), cppgc::internal::MetricRecorder::GCCycle::total, cppgc::internal::MetricRecorder::GCCycle::type, and v8::internal::tracing::type.
Referenced by cppgc::internal::StatsCollector::NotifySweepingCompleted().
SumPhases()
int64_t cppgc::internal::anonymous_namespace{stats-collector.cc}::SumPhases (const MetricRecorder::GCCycle::Phases & phases)
Definition at line 172 of file stats-collector.cc.
                                                             {
  DCHECK_LE(0, phases.mark_duration_us);
  DCHECK_LE(0, phases.weak_duration_us);
  DCHECK_LE(0, phases.compact_duration_us);
  DCHECK_LE(0, phases.sweep_duration_us);
  return phases.mark_duration_us + phases.weak_duration_us +
         phases.compact_duration_us + phases.sweep_duration_us;
}
References cppgc::internal::MetricRecorder::GCCycle::Phases::compact_duration_us, DCHECK_LE, cppgc::internal::MetricRecorder::GCCycle::IncrementalPhases::mark_duration_us, cppgc::internal::MetricRecorder::GCCycle::IncrementalPhases::sweep_duration_us, and cppgc::internal::MetricRecorder::GCCycle::Phases::weak_duration_us.
Referenced by GetCycleEventForMetricRecorder().