v8::internal::wasm::anonymous_namespace{wasm-module-builder.cc} Namespace Reference
Functions
size_t EmitSection (SectionCode code, ZoneBuffer *buffer)
void FixupSection (ZoneBuffer *buffer, size_t start)
WasmOpcode FromInitExprOperator (WasmInitExpr::Operator op)
void WriteInitializerExpressionWithoutEnd (ZoneBuffer *buffer, const WasmInitExpr &init)
void WriteInitializerExpression (ZoneBuffer *buffer, const WasmInitExpr &init)
void WriteHeapType (ZoneBuffer *buffer, HeapType type)
void WriteValueType (ZoneBuffer *buffer, const ValueType &type)
Function Documentation
EmitSection()
size_t v8::internal::wasm::anonymous_namespace{wasm-module-builder.cc}::EmitSection (SectionCode code, ZoneBuffer * buffer)
Definition at line 23 of file wasm-module-builder.cc.
                                                         {
  // Emit the section code.
  buffer->write_u8(code);
  // Emit a placeholder for the length.
  return buffer->reserve_u32v();
}
References code, v8::internal::wasm::ZoneBuffer::reserve_u32v(), and v8::internal::wasm::ZoneBuffer::write_u8().
Referenced by v8::internal::wasm::WasmModuleBuilder::WriteTo().
FixupSection()
void v8::internal::wasm::anonymous_namespace{wasm-module-builder.cc}::FixupSection (ZoneBuffer * buffer, size_t start)
Definition at line 32 of file wasm-module-builder.cc.
                                                    {
  buffer->patch_u32v(start, static_cast<uint32_t>(buffer->offset() - start -
                                                  kPaddedVarInt32Size));
}
References v8::internal::wasm::kPaddedVarInt32Size, v8::internal::wasm::ZoneBuffer::offset(), and v8::internal::wasm::ZoneBuffer::patch_u32v().
Referenced by v8::internal::wasm::WasmModuleBuilder::WriteTo().
FromInitExprOperator()
WasmOpcode v8::internal::wasm::anonymous_namespace{wasm-module-builder.cc}::FromInitExprOperator (WasmInitExpr::Operator op)
Definition at line 37 of file wasm-module-builder.cc.
                                                         {
  switch (op) {
    case WasmInitExpr::kGlobalGet:
      return kExprGlobalGet;
    case WasmInitExpr::kI32Const:
      return kExprI32Const;
    case WasmInitExpr::kI64Const:
      return kExprI64Const;
    case WasmInitExpr::kF32Const:
      return kExprF32Const;
    case WasmInitExpr::kF64Const:
      return kExprF64Const;
    case WasmInitExpr::kS128Const:
      return kExprS128Const;
    case WasmInitExpr::kI32Add:
      return kExprI32Add;
    case WasmInitExpr::kI32Sub:
      return kExprI32Sub;
    case WasmInitExpr::kI32Mul:
      return kExprI32Mul;
    case WasmInitExpr::kI64Add:
      return kExprI64Add;
    case WasmInitExpr::kI64Sub:
      return kExprI64Sub;
    case WasmInitExpr::kI64Mul:
      return kExprI64Mul;
    case WasmInitExpr::kRefNullConst:
      return kExprRefNull;
    case WasmInitExpr::kRefFuncConst:
      return kExprRefFunc;
    case WasmInitExpr::kStructNew:
      return kExprStructNew;
    case WasmInitExpr::kStructNewDefault:
      return kExprStructNewDefault;
    case WasmInitExpr::kArrayNew:
      return kExprArrayNew;
    case WasmInitExpr::kArrayNewDefault:
      return kExprArrayNewDefault;
    case WasmInitExpr::kArrayNewFixed:
      return kExprArrayNewFixed;
    case WasmInitExpr::kRefI31:
      return kExprRefI31;
    case WasmInitExpr::kStringConst:
      return kExprStringConst;
    case WasmInitExpr::kAnyConvertExtern:
      return kExprAnyConvertExtern;
    case WasmInitExpr::kExternConvertAny:
      return kExprExternConvertAny;
  }
}
References v8::internal::wasm::WasmInitExpr::kAnyConvertExtern, v8::internal::wasm::WasmInitExpr::kArrayNew, v8::internal::wasm::WasmInitExpr::kArrayNewDefault, v8::internal::wasm::WasmInitExpr::kArrayNewFixed, v8::internal::wasm::WasmInitExpr::kExternConvertAny, v8::internal::wasm::WasmInitExpr::kF32Const, v8::internal::wasm::WasmInitExpr::kF64Const, v8::internal::wasm::WasmInitExpr::kGlobalGet, v8::internal::wasm::WasmInitExpr::kI32Add, v8::internal::wasm::WasmInitExpr::kI32Const, v8::internal::wasm::WasmInitExpr::kI32Mul, v8::internal::wasm::WasmInitExpr::kI32Sub, v8::internal::wasm::WasmInitExpr::kI64Add, v8::internal::wasm::WasmInitExpr::kI64Const, v8::internal::wasm::WasmInitExpr::kI64Mul, v8::internal::wasm::WasmInitExpr::kI64Sub, v8::internal::wasm::WasmInitExpr::kRefFuncConst, v8::internal::wasm::WasmInitExpr::kRefI31, v8::internal::wasm::WasmInitExpr::kRefNullConst, v8::internal::wasm::WasmInitExpr::kS128Const, v8::internal::wasm::WasmInitExpr::kStringConst, v8::internal::wasm::WasmInitExpr::kStructNew, and v8::internal::wasm::WasmInitExpr::kStructNewDefault.
Referenced by WriteInitializerExpressionWithoutEnd().
WriteHeapType()
void v8::internal::wasm::anonymous_namespace{wasm-module-builder.cc}::WriteHeapType (ZoneBuffer * buffer, HeapType type)
Definition at line 289 of file wasm-module-builder.cc.
                                                      {
  if (type.encoding_needs_exact()) buffer->write_u8(kExactCode);
  buffer->write_i32v(type.code());
}
References v8::internal::wasm::kExactCode, v8::internal::tracing::type, v8::internal::wasm::ZoneBuffer::write_i32v(), and v8::internal::wasm::ZoneBuffer::write_u8().
Referenced by v8::internal::wasm::WasmFunctionBuilder::EmitHeapType(), and WriteValueType().
WriteInitializerExpression()
void v8::internal::wasm::anonymous_namespace{wasm-module-builder.cc}::WriteInitializerExpression (ZoneBuffer * buffer, const WasmInitExpr & init)
Definition at line 183 of file wasm-module-builder.cc.
                                                                              {
  WriteInitializerExpressionWithoutEnd(buffer, init);
  buffer->write_u8(kExprEnd);
}
References v8::internal::wasm::ZoneBuffer::write_u8(), and WriteInitializerExpressionWithoutEnd().
Referenced by v8::internal::wasm::WasmFunctionBuilder::EmitFromInitializerExpression(), and v8::internal::wasm::WasmModuleBuilder::WriteTo().
WriteInitializerExpressionWithoutEnd()
void v8::internal::wasm::anonymous_namespace{wasm-module-builder.cc}::WriteInitializerExpressionWithoutEnd (ZoneBuffer * buffer, const WasmInitExpr & init)
Definition at line 88 of file wasm-module-builder.cc.
                                                                    {
  switch (init.kind()) {
    case WasmInitExpr::kI32Const:
      buffer->write_u8(kExprI32Const);
      buffer->write_i32v(init.immediate().i32_const);
      break;
    case WasmInitExpr::kI64Const:
      buffer->write_u8(kExprI64Const);
      buffer->write_i64v(init.immediate().i64_const);
      break;
    case WasmInitExpr::kF32Const:
      buffer->write_u8(kExprF32Const);
      buffer->write_f32(init.immediate().f32_const);
      break;
    case WasmInitExpr::kF64Const:
      buffer->write_u8(kExprF64Const);
      buffer->write_f64(init.immediate().f64_const);
      break;
    case WasmInitExpr::kS128Const:
      buffer->write_u8(kSimdPrefix);
      buffer->write_u8(kExprS128Const & 0xFF);
      buffer->write(init.immediate().s128_const.data(), kSimd128Size);
      break;
    case WasmInitExpr::kI32Add:
    case WasmInitExpr::kI32Sub:
    case WasmInitExpr::kI32Mul:
    case WasmInitExpr::kI64Add:
    case WasmInitExpr::kI64Sub:
    case WasmInitExpr::kI64Mul:
      WriteInitializerExpressionWithoutEnd(buffer, (*init.operands())[0]);
      WriteInitializerExpressionWithoutEnd(buffer, (*init.operands())[1]);
      buffer->write_u8(FromInitExprOperator(init.kind()));
      break;
    case WasmInitExpr::kGlobalGet:
      buffer->write_u8(kExprGlobalGet);
      buffer->write_u32v(init.immediate().index);
      break;
    case WasmInitExpr::kRefNullConst:
      buffer->write_u8(kExprRefNull);
      if (init.heap_type().encoding_needs_exact()) buffer->write_u8(kExactCode);
      buffer->write_i32v(init.heap_type().code());
      break;
    case WasmInitExpr::kRefFuncConst:
      buffer->write_u8(kExprRefFunc);
      buffer->write_u32v(init.immediate().index);
      break;
    case WasmInitExpr::kStructNew:
    case WasmInitExpr::kStructNewDefault:
    case WasmInitExpr::kArrayNew:
    case WasmInitExpr::kArrayNewDefault: {
      if (init.operands() != nullptr) {
        for (const WasmInitExpr& operand : *init.operands()) {
          WriteInitializerExpressionWithoutEnd(buffer, operand);
        }
      }
      WasmOpcode opcode = FromInitExprOperator(init.kind());
      DCHECK_EQ(opcode >> 8, kGCPrefix);
      DCHECK_EQ(opcode & 0x80, 0);
      buffer->write_u8(kGCPrefix);
      buffer->write_u8(static_cast<uint8_t>(opcode));
      buffer->write_u32v(init.immediate().index);
      break;
    }
    case WasmInitExpr::kArrayNewFixed: {
      static_assert((kExprArrayNewFixed >> 8) == kGCPrefix);
      static_assert((kExprArrayNewFixed & 0x80) == 0);
      for (const WasmInitExpr& operand : *init.operands()) {
        WriteInitializerExpressionWithoutEnd(buffer, operand);
      }
      buffer->write_u8(kGCPrefix);
      buffer->write_u8(static_cast<uint8_t>(kExprArrayNewFixed));
      buffer->write_u32v(init.immediate().index);
      buffer->write_u32v(static_cast<uint32_t>(init.operands()->size()));
      break;
    }
    case WasmInitExpr::kRefI31:
    case WasmInitExpr::kAnyConvertExtern:
    case WasmInitExpr::kExternConvertAny: {
      WriteInitializerExpressionWithoutEnd(buffer, (*init.operands())[0]);
      WasmOpcode opcode = FromInitExprOperator(init.kind());
      DCHECK_EQ(opcode >> 8, kGCPrefix);
      DCHECK_EQ(opcode & 0x80, 0);
      buffer->write_u8(kGCPrefix);
      buffer->write_u8(opcode);
      break;
    }
    case WasmInitExpr::kStringConst:
      buffer->write_u8(kGCPrefix);
      buffer->write_u32v(kExprStringConst & 0xFF);
      buffer->write_u32v(init.immediate().index);
      break;
  }
}
References v8::internal::wasm::HeapType::code(), DCHECK_EQ, v8::internal::wasm::ValueTypeBase::encoding_needs_exact(), v8::internal::wasm::WasmInitExpr::Immediate::f32_const, v8::internal::wasm::WasmInitExpr::Immediate::f64_const, FromInitExprOperator(), v8::internal::wasm::WasmInitExpr::heap_type(), v8::internal::wasm::WasmInitExpr::Immediate::i32_const, v8::internal::wasm::WasmInitExpr::Immediate::i64_const, v8::internal::wasm::WasmInitExpr::immediate(), v8::internal::wasm::WasmInitExpr::Immediate::index, v8::internal::wasm::WasmInitExpr::kAnyConvertExtern, v8::internal::wasm::WasmInitExpr::kArrayNew, v8::internal::wasm::WasmInitExpr::kArrayNewDefault, v8::internal::wasm::WasmInitExpr::kArrayNewFixed, v8::internal::wasm::kExactCode, v8::internal::wasm::WasmInitExpr::kExternConvertAny, v8::internal::wasm::WasmInitExpr::kF32Const, v8::internal::wasm::WasmInitExpr::kF64Const, v8::internal::wasm::WasmInitExpr::kGlobalGet, v8::internal::wasm::WasmInitExpr::kI32Add, v8::internal::wasm::WasmInitExpr::kI32Const, v8::internal::wasm::WasmInitExpr::kI32Mul, v8::internal::wasm::WasmInitExpr::kI32Sub, v8::internal::wasm::WasmInitExpr::kI64Add, v8::internal::wasm::WasmInitExpr::kI64Const, v8::internal::wasm::WasmInitExpr::kI64Mul, v8::internal::wasm::WasmInitExpr::kI64Sub, v8::internal::wasm::WasmInitExpr::kind(), v8::internal::wasm::WasmInitExpr::kRefFuncConst, v8::internal::wasm::WasmInitExpr::kRefI31, v8::internal::wasm::WasmInitExpr::kRefNullConst, v8::internal::wasm::WasmInitExpr::kS128Const, v8::internal::kSimd128Size, v8::internal::wasm::WasmInitExpr::kStringConst, v8::internal::wasm::WasmInitExpr::kStructNew, v8::internal::wasm::WasmInitExpr::kStructNewDefault, v8::internal::wasm::WasmInitExpr::operands(), v8::internal::wasm::WasmInitExpr::Immediate::s128_const, v8::internal::wasm::ZoneBuffer::write(), v8::internal::wasm::ZoneBuffer::write_f32(), v8::internal::wasm::ZoneBuffer::write_f64(), v8::internal::wasm::ZoneBuffer::write_i32v(), v8::internal::wasm::ZoneBuffer::write_i64v(), v8::internal::wasm::ZoneBuffer::write_u32v(), and v8::internal::wasm::ZoneBuffer::write_u8().
Referenced by WriteInitializerExpression().
WriteValueType()
void v8::internal::wasm::anonymous_namespace{wasm-module-builder.cc}::WriteValueType (ZoneBuffer * buffer, const ValueType & type)
Definition at line 293 of file wasm-module-builder.cc.
                                                               {
  buffer->write_u8(type.value_type_code());
  if (type.encoding_needs_shared()) {
    buffer->write_u8(kSharedFlagCode);
  }
  if (type.encoding_needs_heap_type()) {
    WriteHeapType(buffer, type.heap_type());
  }
}
References v8::internal::wasm::kSharedFlagCode, v8::internal::tracing::type, v8::internal::wasm::ZoneBuffer::write_u8(), and WriteHeapType().
Referenced by v8::internal::wasm::WasmFunctionBuilder::EmitValueType(), and v8::internal::wasm::WasmModuleBuilder::WriteTo().