v8::internal::anonymous_namespace{js-regexp.cc} Namespace Reference
Functions
bool IsLineTerminator (int c)
template<typename Char >
uint32_t CountAdditionalEscapeChars (DirectHandle< String > source, bool *needs_escapes_out)
template<typename Char >
void WriteStringToCharVector (base::Vector< Char > v, uint32_t *d, const char *string)
template<typename Char , typename StringType >
DirectHandle< StringType > WriteEscapedRegExpSource (DirectHandle< String > source, DirectHandle< StringType > result)
MaybeDirectHandle< String > EscapeRegExpSource (Isolate *isolate, DirectHandle< String > source)
Function Documentation
CountAdditionalEscapeChars()
template<typename Char >
uint32_t v8::internal::anonymous_namespace{js-regexp.cc}::CountAdditionalEscapeChars (DirectHandle< String > source, bool * needs_escapes_out)
Definition at line 192 of file js-regexp.cc.
                                                             {
  DisallowGarbageCollection no_gc;
  uint32_t escapes = 0;
  // The maximum growth-factor is 5 (for \u2028 and \u2029). Make sure that we
  // won't overflow |escapes| given the current constraints on string length.
  static_assert(uint64_t{String::kMaxLength} * 5 <
                std::numeric_limits<decltype(escapes)>::max());
  bool needs_escapes = false;
  bool in_character_class = false;
  base::Vector<const Char> src = source->GetCharVector<Char>(no_gc);
  for (int i = 0; i < src.length(); i++) {
    const Char c = src[i];
    if (c == '\\') {
      if (i + 1 < src.length() && IsLineTerminator(src[i + 1])) {
        // This '\' is ignored since the next character itself will be escaped.
        escapes--;
      } else {
        // Escape. Skip next character, which will be copied verbatim;
        i++;
      }
    } else if (c == '/' && !in_character_class) {
      // Not escaped forward-slash needs escape.
      needs_escapes = true;
      escapes++;
    } else if (c == '[') {
      in_character_class = true;
    } else if (c == ']') {
      in_character_class = false;
    } else if (c == '\n') {
      needs_escapes = true;
      escapes++;
    } else if (c == '\r') {
      needs_escapes = true;
      escapes++;
    } else if (static_cast<int>(c) == 0x2028) {
      needs_escapes = true;
      escapes += std::strlen("\\u2028") - 1;
    } else if (static_cast<int>(c) == 0x2029) {
      needs_escapes = true;
      escapes += std::strlen("\\u2029") - 1;
    } else {
      DCHECK(!IsLineTerminator(c));
    }
  }
  DCHECK(!in_character_class);
  DCHECK_IMPLIES(escapes != 0, needs_escapes);
  *needs_escapes_out = needs_escapes;
  return escapes;
}
References v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::anonymous_namespace{json-stringifier.cc}::i, IsLineTerminator(), v8::internal::String::kMaxLength, v8::base::Vector< T >::length(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
EscapeRegExpSource()
MaybeDirectHandle<String> v8::internal::anonymous_namespace{js-regexp.cc}::EscapeRegExpSource (Isolate * isolate, DirectHandle< String > source)
Definition at line 304 of file js-regexp.cc.
                                                                          {
  DCHECK(source->IsFlat());
  if (source->length() == 0) return isolate->factory()->query_colon_string();
  bool one_byte = String::IsOneByteRepresentationUnderneath(*source);
  bool needs_escapes = false;
  uint32_t additional_escape_chars =
      one_byte ? CountAdditionalEscapeChars<uint8_t>(source, &needs_escapes)
               : CountAdditionalEscapeChars<base::uc16>(source, &needs_escapes);
  if (!needs_escapes) return source;
  DCHECK_LE(static_cast<uint64_t>(source->length()) + additional_escape_chars,
            std::numeric_limits<uint32_t>::max());
  uint32_t length = source->length() + additional_escape_chars;
  if (one_byte) {
    DirectHandle<SeqOneByteString> result;
    ASSIGN_RETURN_ON_EXCEPTION(isolate, result,
                               isolate->factory()->NewRawOneByteString(length));
    return WriteEscapedRegExpSource<uint8_t>(source, result);
  } else {
    DirectHandle<SeqTwoByteString> result;
    ASSIGN_RETURN_ON_EXCEPTION(isolate, result,
                               isolate->factory()->NewRawTwoByteString(length));
    return WriteEscapedRegExpSource<base::uc16>(source, result);
  }
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::DCHECK(), DCHECK_LE, v8::internal::Isolate::factory(), v8::internal::String::IsOneByteRepresentationUnderneath(), v8::internal::length, v8::internal::FactoryBase< Impl >::NewRawOneByteString(), v8::internal::FactoryBase< Impl >::NewRawTwoByteString(), and v8::base::internal::result.
Referenced by v8::internal::JSRegExp::Initialize().
IsLineTerminator()
bool v8::internal::anonymous_namespace{js-regexp.cc}::IsLineTerminator (int c)
Definition at line 183 of file js-regexp.cc.
                             {
  // Expected to return true for '\n', '\r', 0x2028, and 0x2029.
  return unibrow::IsLineTerminator(static_cast<unibrow::uchar>(c));
}
References unibrow::IsLineTerminator().
Referenced by CountAdditionalEscapeChars(), and WriteEscapedRegExpSource().
WriteEscapedRegExpSource()
template<typename Char , typename StringType >
DirectHandle<StringType> v8::internal::anonymous_namespace{js-regexp.cc}::WriteEscapedRegExpSource (DirectHandle< String > source, DirectHandle< StringType > result)
Definition at line 251 of file js-regexp.cc.
                                                                  {
  DisallowGarbageCollection no_gc;
  base::Vector<const Char> src = source->GetCharVector<Char>(no_gc);
  base::Vector<Char> dst(result->GetChars(no_gc), result->length());
  uint32_t s = 0;
  uint32_t d = 0;
  bool in_character_class = false;
  while (s < src.size()) {
    const Char c = src[s];
    if (c == '\\') {
      if (s + 1 < src.size() && IsLineTerminator(src[s + 1])) {
        // This '\' is ignored since the next character itself will be escaped.
        s++;
        continue;
      } else {
        // Escape. Copy this and next character.
        dst[d++] = src[s++];
      }
      if (s == src.size()) break;
    } else if (c == '/' && !in_character_class) {
      // Not escaped forward-slash needs escape.
      dst[d++] = '\\';
    } else if (c == '[') {
      in_character_class = true;
    } else if (c == ']') {
      in_character_class = false;
    } else if (c == '\n') {
      WriteStringToCharVector(dst, &d, "\\n");
      s++;
      continue;
    } else if (c == '\r') {
      WriteStringToCharVector(dst, &d, "\\r");
      s++;
      continue;
    } else if (static_cast<int>(c) == 0x2028) {
      WriteStringToCharVector(dst, &d, "\\u2028");
      s++;
      continue;
    } else if (static_cast<int>(c) == 0x2029) {
      WriteStringToCharVector(dst, &d, "\\u2029");
      s++;
      continue;
    } else {
      DCHECK(!IsLineTerminator(c));
    }
    dst[d++] = src[s++];
  }
  DCHECK_EQ(result->length(), d);
  DCHECK(!in_character_class);
  return result;
}
References v8::internal::DCHECK(), DCHECK_EQ, IsLineTerminator(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, v8::base::Vector< T >::size(), and WriteStringToCharVector().
WriteStringToCharVector()
template<typename Char >
void v8::internal::anonymous_namespace{js-regexp.cc}::WriteStringToCharVector (base::Vector< Char > v, uint32_t * d, const char * string)
Definition at line 244 of file js-regexp.cc.
                                                 {
  int s = 0;
  while (string[s] != '\0') v[(*d)++] = string[s++];
}
Referenced by WriteEscapedRegExpSource().