v8::internal::anonymous_namespace{builtins-function.cc} Namespace Reference
Enumerations
enum class ProtoSource { kNormalFunction
, kUseTargetPrototype
 }
Functions
MaybeDirectHandle< Object > CreateDynamicFunction (Isolate *isolate, BuiltinArguments args, const char *token)
Tagged< Object > DoFunctionBind (Isolate *isolate, BuiltinArguments args, ProtoSource proto_source)
bool IsSloppyNormalJSFunction (Tagged< Object > receiver)
Enumeration Type Documentation
ProtoSource
enum v8::internal::anonymous_namespace{builtins-function.cc}::ProtoSource [strong]
Enumerator
kNormalFunction
kUseTargetPrototype
Definition at line 185 of file builtins-function.cc.
                       {
  kNormalFunction,
  kUseTargetPrototype,
};
Function Documentation
CreateDynamicFunction()
MaybeDirectHandle<Object> v8::internal::anonymous_namespace{builtins-function.cc}::CreateDynamicFunction (Isolate * isolate, BuiltinArguments args, const char * token)
Definition at line 23 of file builtins-function.cc.
                                                                   {
  // Compute number of arguments, ignoring the receiver.
  DCHECK_LE(1, args.length());
  int const argc = args.length() - 1;
  DirectHandle<JSFunction> target = args.target();
  DirectHandle<JSObject> target_global_proxy(target->global_proxy(), isolate);
  if (!Builtins::AllowDynamicFunction(isolate, target, target_global_proxy)) {
    isolate->CountUsage(v8::Isolate::kFunctionConstructorReturnedUndefined);
    // TODO(verwaest): We would like to throw using the calling context instead
    // of the entered context but we don't currently have access to that.
    HandleScopeImplementer* impl = isolate->handle_scope_implementer();
    SaveAndSwitchContext save(isolate,
                              impl->LastEnteredContext()->native_context());
    THROW_NEW_ERROR(isolate, NewTypeError(MessageTemplate::kNoAccess));
  }
  // Build the source string.
  DirectHandle<String> source;
  int parameters_end_pos = kNoSourcePosition;
  {
    IncrementalStringBuilder builder(isolate);
    builder.AppendCharacter('(');
    builder.AppendCString(token);
    builder.AppendCStringLiteral(" anonymous(");
    if (argc > 1) {
      for (int i = 1; i < argc; ++i) {
        if (i > 1) builder.AppendCharacter(',');
        DirectHandle<String> param;
        ASSIGN_RETURN_ON_EXCEPTION(isolate, param,
                                   Object::ToString(isolate, args.at(i)));
        param = String::Flatten(isolate, param);
        builder.AppendString(param);
      }
    }
    builder.AppendCharacter('\n');
    parameters_end_pos = builder.Length();
    builder.AppendCStringLiteral(") {\n");
    if (argc > 0) {
      DirectHandle<String> body;
      ASSIGN_RETURN_ON_EXCEPTION(isolate, body,
                                 Object::ToString(isolate, args.at(argc)));
      builder.AppendString(body);
    }
    builder.AppendCStringLiteral("\n})");
    ASSIGN_RETURN_ON_EXCEPTION(isolate, source, builder.Finish());
  }
  bool is_code_like = true;
  for (int i = 0; i < argc; ++i) {
    if (!Object::IsCodeLike(*args.at(i + 1), isolate)) {
      is_code_like = false;
      break;
    }
  }
  // Compile the string in the constructor and not a helper so that errors to
  // come from here.
  DirectHandle<JSFunction> function;
  {
    ASSIGN_RETURN_ON_EXCEPTION(
        isolate, function,
        Compiler::GetFunctionFromString(
            isolate, direct_handle(target->native_context(), isolate),
            indirect_handle(source, isolate), parameters_end_pos,
            is_code_like));
    DirectHandle<Object> result;
    ASSIGN_RETURN_ON_EXCEPTION(
        isolate, result,
        Execution::Call(isolate, function, target_global_proxy, {}));
    function = Cast<JSFunction>(result);
    function->shared()->set_name_should_print_as_anonymous(true);
  }
  // If new.target is equal to target then the function created
  // is already correctly setup and nothing else should be done
  // here. But if new.target is not equal to target then we are
  // have a Function builtin subclassing case and therefore the
  // function has wrong initial map. To fix that we create a new
  // function object with correct initial map.
  DirectHandle<Object> unchecked_new_target = args.new_target();
  if (!IsUndefined(*unchecked_new_target, isolate) &&
      !unchecked_new_target.is_identical_to(target)) {
    DirectHandle<JSReceiver> new_target =
        Cast<JSReceiver>(unchecked_new_target);
    DirectHandle<Map> initial_map;
    ASSIGN_RETURN_ON_EXCEPTION(
        isolate, initial_map,
        JSFunction::GetDerivedMap(isolate, target, new_target));
    DirectHandle<SharedFunctionInfo> shared_info(function->shared(), isolate);
    DirectHandle<Map> map =
        Map::AsLanguageMode(isolate, initial_map, shared_info);
    DirectHandle<Context> context(function->context(), isolate);
    function = Factory::JSFunctionBuilder{isolate, shared_info, context}
                   .set_map(map)
                   .set_allocation_type(AllocationType::kYoung)
                   .Build();
  }
  return function;
}
References v8::internal::Builtins::AllowDynamicFunction(), v8::internal::IncrementalStringBuilder::AppendCharacter(), v8::internal::IncrementalStringBuilder::AppendCString(), v8::internal::IncrementalStringBuilder::AppendCStringLiteral(), v8::internal::IncrementalStringBuilder::AppendString(), v8::base::args, v8::internal::Map::AsLanguageMode(), ASSIGN_RETURN_ON_EXCEPTION, v8::internal::Execution::Call(), v8::internal::Isolate::CountUsage(), DCHECK_LE, v8::internal::direct_handle(), v8::internal::IncrementalStringBuilder::Finish(), v8::internal::JSFunction::GetDerivedMap(), v8::internal::Compiler::GetFunctionFromString(), v8::internal::Isolate::handle_scope_implementer(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, wasm::impl(), v8::internal::indirect_handle(), v8::internal::compiler::initial_map, v8::internal::DirectHandle< T >::is_identical_to(), v8::internal::Object::IsCodeLike(), v8::Isolate::kFunctionConstructorReturnedUndefined, v8::internal::kNoSourcePosition, v8::internal::kYoung, v8::internal::IncrementalStringBuilder::Length(), v8::base::internal::result, THROW_NEW_ERROR, and v8::Value::ToString().
Referenced by v8::internal::BUILTIN().
DoFunctionBind()
Tagged<Object> v8::internal::anonymous_namespace{builtins-function.cc}::DoFunctionBind (Isolate * isolate, BuiltinArguments args, ProtoSource proto_source)
Definition at line 190 of file builtins-function.cc.
                                                        {
  HandleScope scope(isolate);
  DCHECK_LE(1, args.length());
  if (!IsCallable(*args.receiver())) {
    THROW_NEW_ERROR_RETURN_FAILURE(
        isolate, NewTypeError(MessageTemplate::kFunctionBind));
  }
  // Allocate the bound function with the given {this_arg} and {args}.
  DirectHandle<JSReceiver> target = args.at<JSReceiver>(0);
  DirectHandle<JSAny> this_arg = isolate->factory()->undefined_value();
  DirectHandleVector<Object> argv(isolate, std::max(0, args.length() - 2));
  if (args.length() > 1) {
    this_arg = args.at<JSAny>(1);
    for (int i = 2; i < args.length(); ++i) {
      argv[i - 2] = args.at(i);
    }
  }
  DirectHandle<JSPrototype> proto;
  if (proto_source == ProtoSource::kUseTargetPrototype) {
    // Determine the prototype of the {target_function}.
    ASSIGN_RETURN_FAILURE_ON_EXCEPTION(
        isolate, proto, JSReceiver::GetPrototype(isolate, target));
  } else if (proto_source == ProtoSource::kNormalFunction) {
    DirectHandle<NativeContext> native_context(
        isolate->global_object()->native_context(), isolate);
    auto function_proto = native_context->function_prototype();
    proto = direct_handle(function_proto, isolate);
  } else {
    UNREACHABLE();
  }
  DirectHandle<JSBoundFunction> function;
  ASSIGN_RETURN_FAILURE_ON_EXCEPTION(
      isolate, function,
      isolate->factory()->NewJSBoundFunction(
          target, this_arg, {argv.data(), argv.size()}, proto));
  Maybe<bool> result =
      JSFunctionOrBoundFunctionOrWrappedFunction::CopyNameAndLength(
          isolate, function, target, isolate->factory()->bound__string(),
          static_cast<int>(argv.size()));
  if (result.IsNothing()) {
    DCHECK(isolate->has_exception());
    return ReadOnlyRoots(isolate).exception();
  }
  return *function;
}
References v8::base::args, ASSIGN_RETURN_FAILURE_ON_EXCEPTION, v8::internal::JSFunctionOrBoundFunctionOrWrappedFunction::CopyNameAndLength(), v8::internal::DCHECK(), DCHECK_LE, v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::JSReceiver::GetPrototype(), v8::internal::Isolate::global_object(), v8::internal::Isolate::has_exception(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::native_context, v8::internal::Factory::NewJSBoundFunction(), v8::base::internal::result, v8::internal::DirectHandleVector< T >::size(), THROW_NEW_ERROR_RETURN_FAILURE, and v8::internal::UNREACHABLE().
Referenced by v8::internal::BUILTIN().
IsSloppyNormalJSFunction()
bool v8::internal::anonymous_namespace{builtins-function.cc}::IsSloppyNormalJSFunction (Tagged< Object > receiver)
Definition at line 280 of file builtins-function.cc.
                                                       {
  if (!IsJSFunction(receiver)) return false;
  Tagged<JSFunction> function = Cast<JSFunction>(receiver);
  return function->shared()->kind() == FunctionKind::kNormalFunction &&
         is_sloppy(function->shared()->language_mode());
}
References v8::internal::is_sloppy(), and v8::internal::kNormalFunction.
Referenced by v8::internal::BUILTIN().