v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc} Namespace Reference
Classes
class RegisterReuseMap
Enumerations
enum MergeKeepStackSlots : bool { kKeepStackSlots = true
, kTurnStackSlotsIntoRegisters = false
 }
enum MergeAllowConstants : bool { kConstantsAllowed = true
, kConstantsNotAllowed = false
 }
enum MergeAllowRegisters : bool { kRegistersAllowed = true
, kRegistersNotAllowed = false
 }
enum ReuseRegisters : bool { kReuseRegisters = true
, kNoReuseRegisters = false
 }
Functions
void InitMergeRegion (LiftoffAssembler::CacheState *target_state, const VarState *source, VarState *target, uint32_t count, MergeKeepStackSlots keep_stack_slots, MergeAllowConstants allow_constants, MergeAllowRegisters allow_registers, ReuseRegisters reuse_registers, LiftoffRegList used_regs, int new_stack_offset, ParallelMove &parallel_move)
int GetSafepointIndexForStackSlot (const VarState &slot)
AssemblerOptions DefaultLiftoffOptions ()
void PrepareStackTransfers (const ValueKindSig *sig, compiler::CallDescriptor *call_descriptor, const VarState *slots, LiftoffStackSlots *stack_slots, ParallelMove *parallel_move, LiftoffRegList *param_regs)
constexpr LiftoffRegList AllReturnRegs ()
Enumeration Type Documentation
MergeAllowConstants
enum v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::MergeAllowConstants : bool
Enumerator
kConstantsAllowed
kConstantsNotAllowed
Definition at line 62 of file liftoff-assembler.cc.
                         : bool {
  kConstantsAllowed = true,
  kConstantsNotAllowed = false
};
MergeAllowRegisters
enum v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::MergeAllowRegisters : bool
Enumerator
kRegistersAllowed
kRegistersNotAllowed
Definition at line 66 of file liftoff-assembler.cc.
                         : bool {
  kRegistersAllowed = true,
  kRegistersNotAllowed = false
};
MergeKeepStackSlots
enum v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::MergeKeepStackSlots : bool
Enumerator
kKeepStackSlots
kTurnStackSlotsIntoRegisters
Definition at line 58 of file liftoff-assembler.cc.
                         : bool {
  kKeepStackSlots = true,
  kTurnStackSlotsIntoRegisters = false
};
ReuseRegisters
enum v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::ReuseRegisters : bool
Enumerator
kReuseRegisters
kNoReuseRegisters
Definition at line 70 of file liftoff-assembler.cc.
                    : bool {
  kReuseRegisters = true,
  kNoReuseRegisters = false
};
Function Documentation
AllReturnRegs()
constexpr LiftoffRegList v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::AllReturnRegs () [constexpr]
Definition at line 857 of file liftoff-assembler.cc.
                                         {
  LiftoffRegList result;
  for (Register r : kGpReturnRegisters) result.set(r);
  for (DoubleRegister r : kFpReturnRegisters) result.set(r);
  return result;
}
References v8::internal::wasm::kFpReturnRegisters, v8::internal::wasm::kGpReturnRegisters, and v8::base::internal::result.
Referenced by v8::internal::wasm::LiftoffAssembler::FinishCall().
DefaultLiftoffOptions()
AssemblerOptions v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::DefaultLiftoffOptions ()
Definition at line 355 of file liftoff-assembler.cc.
                                         {
  return AssemblerOptions{
      .is_wasm = true,
  };
}
References v8::internal::AssemblerOptions::is_wasm.
GetSafepointIndexForStackSlot()
int v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::GetSafepointIndexForStackSlot (const VarState & slot)
Definition at line 275 of file liftoff-assembler.cc.
                                                        {
  // index = 0 is for the stack slot at 'fp + kFixedFrameSizeAboveFp -
  // kSystemPointerSize', the location of the current stack slot is 'fp -
  // slot.offset()'. The index we need is therefore '(fp +
  // kFixedFrameSizeAboveFp - kSystemPointerSize) - (fp - slot.offset())' =
  // 'slot.offset() + kFixedFrameSizeAboveFp - kSystemPointerSize'.
  // Concretely, the index of the first stack slot is '4'.
  return (slot.offset() + StandardFrameConstants::kFixedFrameSizeAboveFp -
          kSystemPointerSize) /
         kSystemPointerSize;
}
References v8::internal::CommonFrameConstants::kFixedFrameSizeAboveFp, v8::internal::kSystemPointerSize, and v8::internal::wasm::LiftoffVarState::offset().
Referenced by v8::internal::wasm::LiftoffAssembler::CacheState::DefineSafepoint(), v8::internal::wasm::LiftoffAssembler::CacheState::DefineSafepointWithCalleeSavedRegisters(), and v8::internal::wasm::LiftoffAssembler::CacheState::GetTaggedSlotsForOOLCode().
InitMergeRegion()
void v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::InitMergeRegion (LiftoffAssembler::CacheState * target_state, const VarState * source, VarState * target, uint32_t count, MergeKeepStackSlots keep_stack_slots, MergeAllowConstants allow_constants, MergeAllowRegisters allow_registers, ReuseRegisters reuse_registers, LiftoffRegList used_regs, int new_stack_offset, ParallelMove & parallel_move)
Definition at line 80 of file liftoff-assembler.cc.
                                                                        {
  RegisterReuseMap register_reuse_map;
  for (const VarState* source_end = source + count; source < source_end;
       ++source, ++target) {
    if (source->is_stack() && keep_stack_slots) {
      *target = *source;
      // If {new_stack_offset} is set, we want to recompute stack offsets for
      // the region we are initializing such that they are contiguous. If
      // {new_stack_offset} is zero (which is an illegal stack offset), we just
      // keep the source offsets.
      if (new_stack_offset) {
        new_stack_offset =
            LiftoffAssembler::NextSpillOffset(source->kind(), new_stack_offset);
        if (new_stack_offset != source->offset()) {
          target->set_offset(new_stack_offset);
          parallel_move.TransferToStack(new_stack_offset, *source);
        }
      }
      continue;
    }
    if (source->is_const() && allow_constants) {
      *target = *source;
      DCHECK(!new_stack_offset);
      continue;
    }
    std::optional<LiftoffRegister> reg;
    bool needs_reg_transfer = true;
    if (allow_registers) {
      // First try: Keep the same register, if it's free.
      if (source->is_reg() && target_state->is_free(source->reg())) {
        reg = source->reg();
        needs_reg_transfer = false;
      }
      // Second try: Use the same register we used before (if we reuse
      // registers).
      if (!reg && reuse_registers) {
        reg = register_reuse_map.Lookup(source->reg());
      }
      // Third try: Use any free register.
      RegClass rc = reg_class_for(source->kind());
      if (!reg && target_state->has_unused_register(rc, used_regs)) {
        reg = target_state->unused_register(rc, used_regs);
      }
    }
    // See above: Recompute the stack offset if requested.
    int target_offset = source->offset();
    if (new_stack_offset) {
      new_stack_offset =
          LiftoffAssembler::NextSpillOffset(source->kind(), new_stack_offset);
      target_offset = new_stack_offset;
    }
    if (reg) {
      if (needs_reg_transfer) parallel_move.LoadIntoRegister(*reg, *source);
      if (reuse_registers) register_reuse_map.Add(source->reg(), *reg);
      target_state->inc_used(*reg);
      *target = VarState(source->kind(), *reg, target_offset);
    } else {
      // No free register; make this a stack slot.
      *target = VarState(source->kind(), target_offset);
      parallel_move.TransferToStack(target_offset, *source);
    }
  }
}
References v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::RegisterReuseMap::Add(), v8::internal::DCHECK(), v8::internal::wasm::LiftoffAssembler::CacheState::has_unused_register(), v8::internal::wasm::LiftoffAssembler::CacheState::inc_used(), v8::internal::wasm::LiftoffVarState::is_const(), v8::internal::wasm::LiftoffAssembler::CacheState::is_free(), v8::internal::wasm::LiftoffVarState::is_reg(), v8::internal::wasm::LiftoffVarState::is_stack(), v8::internal::wasm::LiftoffVarState::kind(), v8::internal::wasm::ParallelMove::LoadIntoRegister(), v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::RegisterReuseMap::Lookup(), v8::internal::wasm::LiftoffAssembler::NextSpillOffset(), v8::internal::wasm::LiftoffVarState::offset(), v8::internal::wasm::LiftoffVarState::reg(), v8::internal::wasm::reg_class_for(), v8::internal::wasm::LiftoffVarState::set_offset(), v8::internal::wasm::ParallelMove::TransferToStack(), and v8::internal::wasm::LiftoffAssembler::CacheState::unused_register().
Referenced by v8::internal::wasm::LiftoffAssembler::MergeIntoNewState().
PrepareStackTransfers()
void v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::PrepareStackTransfers (const ValueKindSig * sig, compiler::CallDescriptor * call_descriptor, const VarState * slots, LiftoffStackSlots * stack_slots, ParallelMove * parallel_move, LiftoffRegList * param_regs)
Definition at line 699 of file liftoff-assembler.cc.
                                                       {
  // Process parameters backwards, to reduce the amount of Slot sorting for
  // the most common case - a normal Wasm Call. Slots will be mostly unsorted
  // in the Builtin call case.
  uint32_t call_desc_input_idx =
      static_cast<uint32_t>(call_descriptor->InputCount());
  uint32_t num_params = static_cast<uint32_t>(sig->parameter_count());
  for (uint32_t i = num_params; i > 0; --i) {
    const uint32_t param = i - 1;
    ValueKind kind = sig->GetParam(param);
    const bool is_gp_pair = kNeedI64RegPair && kind == kI64;
    const int num_lowered_params = is_gp_pair ? 2 : 1;
    const VarState& slot = slots[param];
    DCHECK(CompatibleStackSlotTypes(slot.kind(), kind));
    // Process both halfs of a register pair separately, because they are passed
    // as separate parameters. One or both of them could end up on the stack.
    for (int lowered_idx = 0; lowered_idx < num_lowered_params; ++lowered_idx) {
      const RegPairHalf half =
          is_gp_pair && lowered_idx == 0 ? kHighWord : kLowWord;
      --call_desc_input_idx;
      LinkageLocation loc =
          call_descriptor->GetInputLocation(call_desc_input_idx);
      if (loc.IsRegister()) {
        DCHECK(!loc.IsAnyRegister());
        RegClass rc = is_gp_pair ? kGpReg : reg_class_for(kind);
        int reg_code = loc.AsRegister();
        LiftoffRegister reg =
            LiftoffRegister::from_external_code(rc, kind, reg_code);
        param_regs->set(reg);
        if (is_gp_pair) {
          parallel_move->LoadI64HalfIntoRegister(reg, slot, half);
        } else {
          parallel_move->LoadIntoRegister(reg, slot);
        }
      } else {
        DCHECK(loc.IsCallerFrameSlot());
        int param_offset = -loc.GetLocation() - 1;
        stack_slots->Add(slot, slot.offset(), half, param_offset);
      }
    }
  }
}
References v8::internal::wasm::LiftoffStackSlots::Add(), v8::internal::DCHECK(), v8::internal::wasm::LiftoffRegister::from_external_code(), v8::internal::compiler::CallDescriptor::GetInputLocation(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::CallDescriptor::InputCount(), v8::internal::wasm::kGpReg, v8::internal::wasm::kHighWord, v8::internal::kI64, v8::internal::wasm::LiftoffVarState::kind(), v8::internal::wasm::kLowWord, v8::internal::wasm::kNeedI64RegPair, v8::internal::wasm::ParallelMove::LoadI64HalfIntoRegister(), v8::internal::wasm::ParallelMove::LoadIntoRegister(), v8::internal::loc, v8::internal::wasm::LiftoffVarState::offset(), v8::internal::wasm::reg_class_for(), v8::internal::wasm::LiftoffRegList::set(), and v8::internal::sig.
Referenced by v8::internal::wasm::LiftoffAssembler::PrepareBuiltinCall(), and v8::internal::wasm::LiftoffAssembler::PrepareCall().