v8::internal::baseline::anonymous_namespace{baseline-compiler.cc} Namespace Reference
Functions
AssemblerOptions BaselineAssemblerOptions (Isolate *isolate)
std::unique_ptr< AssemblerBuffer > AllocateBuffer (DirectHandle< BytecodeArray > bytecodes)
constexpr Builtin ConvertReceiverModeToCompactBuiltin (ConvertReceiverMode mode)
constexpr Builtin ConvertReceiverModeToBuiltin (ConvertReceiverMode mode)
Variables
const int kAverageBytecodeToInstructionRatio = 7
Function Documentation
AllocateBuffer()
std::unique_ptr<AssemblerBuffer> v8::internal::baseline::anonymous_namespace{baseline-compiler.cc}::AllocateBuffer (DirectHandle< BytecodeArray > bytecodes)
Definition at line 269 of file baseline-compiler.cc.
                                           {
  int estimated_size;
  {
    DisallowHeapAllocation no_gc;
    estimated_size = BaselineCompiler::EstimateInstructionSize(*bytecodes);
  }
  return NewAssemblerBuffer(RoundUp(estimated_size, 4 * KB));
}
References v8::internal::baseline::BaselineCompiler::EstimateInstructionSize(), v8::internal::KB, v8::internal::NewAssemblerBuffer(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and RoundUp().
BaselineAssemblerOptions()
AssemblerOptions v8::internal::baseline::anonymous_namespace{baseline-compiler.cc}::BaselineAssemblerOptions (Isolate * isolate)
Definition at line 253 of file baseline-compiler.cc.
                                                            {
  AssemblerOptions options = AssemblerOptions::Default(isolate);
  options.builtin_call_jump_mode =
      isolate->is_short_builtin_calls_enabled()
          ? BuiltinCallJumpMode::kPCRelative
          : kFallbackBuiltinCallJumpModeForBaseline;
  return options;
}
References v8::internal::AssemblerOptions::builtin_call_jump_mode, v8::internal::AssemblerOptions::Default(), v8::internal::Isolate::is_short_builtin_calls_enabled(), v8::internal::baseline::kFallbackBuiltinCallJumpModeForBaseline, and v8::internal::kPCRelative.
ConvertReceiverModeToBuiltin()
constexpr Builtin v8::internal::baseline::anonymous_namespace{baseline-compiler.cc}::ConvertReceiverModeToBuiltin (ConvertReceiverMode mode) [constexpr]
Definition at line 1300 of file baseline-compiler.cc.
                                                                         {
  switch (mode) {
    case ConvertReceiverMode::kAny:
      return Builtin::kCall_ReceiverIsAny_Baseline;
    case ConvertReceiverMode::kNullOrUndefined:
      return Builtin::kCall_ReceiverIsNullOrUndefined_Baseline;
    case ConvertReceiverMode::kNotNullOrUndefined:
      return Builtin::kCall_ReceiverIsNotNullOrUndefined_Baseline;
  }
}
References v8::internal::kAny, v8::internal::kNotNullOrUndefined, v8::internal::kNullOrUndefined, and mode().
ConvertReceiverModeToCompactBuiltin()
constexpr Builtin v8::internal::baseline::anonymous_namespace{baseline-compiler.cc}::ConvertReceiverModeToCompactBuiltin (ConvertReceiverMode mode) [constexpr]
Definition at line 1289 of file baseline-compiler.cc.
                              {
  switch (mode) {
    case ConvertReceiverMode::kAny:
      return Builtin::kCall_ReceiverIsAny_Baseline_Compact;
    case ConvertReceiverMode::kNullOrUndefined:
      return Builtin::kCall_ReceiverIsNullOrUndefined_Baseline_Compact;
    case ConvertReceiverMode::kNotNullOrUndefined:
      return Builtin::kCall_ReceiverIsNotNullOrUndefined_Baseline_Compact;
  }
}
References v8::internal::kAny, v8::internal::kNotNullOrUndefined, v8::internal::kNullOrUndefined, and mode().
Variable Documentation
kAverageBytecodeToInstructionRatio
const int v8::internal::baseline::anonymous_namespace{baseline-compiler.cc}::kAverageBytecodeToInstructionRatio = 7
Definition at line 267 of file baseline-compiler.cc.
Referenced by v8::internal::baseline::BaselineCompiler::EstimateInstructionSize().