v8::internal::maglev::anonymous_namespace{maglev-ir-riscv.cc} Namespace Reference
Enumerations
enum class ReduceInterruptBudgetType { kLoop
, kReturn
 }
Functions
void HandleInterruptsAndTiering (MaglevAssembler *masm, ZoneLabelRef done, Node *node, ReduceInterruptBudgetType type, Register scratch0)
void GenerateReduceInterruptBudget (MaglevAssembler *masm, Node *node, Register feedback_cell, ReduceInterruptBudgetType type, int amount)
Enumeration Type Documentation
ReduceInterruptBudgetType
enum v8::internal::maglev::anonymous_namespace{maglev-ir-riscv.cc}::ReduceInterruptBudgetType [strong]
Enumerator
kLoop
kReturn
Definition at line 824 of file maglev-ir-riscv.cc.
{ kLoop, kReturn };
Function Documentation
GenerateReduceInterruptBudget()
void v8::internal::maglev::anonymous_namespace{maglev-ir-riscv.cc}::GenerateReduceInterruptBudget (MaglevAssembler * masm, Node * node, Register feedback_cell, ReduceInterruptBudgetType type, int amount)
Definition at line 880 of file maglev-ir-riscv.cc.
                                                                               {
  MaglevAssembler::TemporaryRegisterScope temps(masm);
  Register scratch = temps.Acquire();
  Register budget = scratch;
  __ Lw(budget,
        FieldMemOperand(feedback_cell, FeedbackCell::kInterruptBudgetOffset));
  __ Sub32(budget, budget, Operand(amount));
  __ Sw(budget,
        FieldMemOperand(feedback_cell, FeedbackCell::kInterruptBudgetOffset));
  ZoneLabelRef done(masm);
  Label* deferred_code = __ MakeDeferredCode(
      [](MaglevAssembler* masm, ZoneLabelRef done, Node* node,
         ReduceInterruptBudgetType type, Register scratch) {
        HandleInterruptsAndTiering(masm, done, node, type, scratch);
      },
      done, node, type, scratch);
  __ MacroAssembler::Branch(deferred_code, lt, budget, Operand(zero_reg));
  __ bind(*done);
}
References __, v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::Acquire(), v8::internal::MacroAssembler::Branch(), v8::internal::FieldMemOperand(), HandleInterruptsAndTiering(), v8::internal::lt, and v8::internal::tracing::type.
HandleInterruptsAndTiering()
void v8::internal::maglev::anonymous_namespace{maglev-ir-riscv.cc}::HandleInterruptsAndTiering (MaglevAssembler * masm, ZoneLabelRef done, Node * node, ReduceInterruptBudgetType type, Register scratch0)
Definition at line 826 of file maglev-ir-riscv.cc.
                                                   {
  // For loops, first check for interrupts. Don't do this for returns, as we
  // can't lazy deopt to the end of a return.
  if (type == ReduceInterruptBudgetType::kLoop) {
    Label next;
    // Here, we only care about interrupts since we've already guarded against
    // real stack overflows on function entry.
    {
      Register stack_limit = scratch0;
      __ LoadStackLimit(stack_limit, StackLimitKind::kInterruptStackLimit);
      __ MacroAssembler::Branch(&next, ugt, sp, Operand(stack_limit),
                                Label::Distance::kNear);
    }
    // An interrupt has been requested and we must call into runtime to handle
    // it; since we already pay the call cost, combine with the TieringManager
    // call.
    {
      SaveRegisterStateForCall save_register_state(masm,
                                                   node->register_snapshot());
      Register function = scratch0;
      __ LoadWord(function,
                  MemOperand(fp, StandardFrameConstants::kFunctionOffset));
      __ Push(function);
      // Move into kContextRegister after the load into scratch0, just in case
      // scratch0 happens to be kContextRegister.
      __ Move(kContextRegister, masm->native_context().object());
      __ CallRuntime(Runtime::kBytecodeBudgetInterruptWithStackCheck_Maglev, 1);
      save_register_state.DefineSafepointWithLazyDeopt(node->lazy_deopt_info());
    }
    __ MacroAssembler::Branch(*done); // All done, continue.
    __ bind(&next);
  }
  // No pending interrupts. Call into the TieringManager if needed.
  {
    SaveRegisterStateForCall save_register_state(masm,
                                                 node->register_snapshot());
    Register function = scratch0;
    __ LoadWord(function,
                MemOperand(fp, StandardFrameConstants::kFunctionOffset));
    __ Push(function);
    // Move into kContextRegister after the load into scratch0, just in case
    // scratch0 happens to be kContextRegister.
    __ Move(kContextRegister, masm->native_context().object());
    // Note: must not cause a lazy deopt!
    __ CallRuntime(Runtime::kBytecodeBudgetInterrupt_Maglev, 1);
    save_register_state.DefineSafepoint();
  }
  __ MacroAssembler::Branch(*done);
}
References __, v8::internal::MacroAssembler::Branch(), v8::internal::maglev::SaveRegisterStateForCall::DefineSafepoint(), v8::internal::maglev::SaveRegisterStateForCall::DefineSafepointWithLazyDeopt(), v8::internal::kContextRegister, v8::internal::StandardFrameConstants::kFunctionOffset, v8::internal::kInterruptStackLimit, v8::internal::maglev::NodeBase::lazy_deopt_info(), v8::internal::maglev::MaglevAssembler::native_context(), v8::internal::compiler::NativeContextRef::object(), v8::internal::maglev::NodeBase::register_snapshot(), v8::internal::tracing::type, and v8::internal::ugt.
Referenced by GenerateReduceInterruptBudget().