v8::internal::temporal Namespace Reference
Namespaces
 anonymous_namespace{js-temporal-helpers.cc}
Classes
struct TimeDurationRecord
struct DurationRecord
Enumerations
enum DifferenceOperation { kSince
, kUntil
 }
Functions
bool IsValidDuration (Isolate *isolate, const DurationRecord &dur)
Maybe< DurationRecord > ToPartialDuration (Isolate *isolate, DirectHandle< Object > temporal_duration_like_obj, const DurationRecord &input)
Maybe< double > ToIntegerIfIntegral (Isolate *isolate, DirectHandle< Object > argument)
Maybe< double > ToIntegerWithTruncation (Isolate *isolate, DirectHandle< Object > argument)
bool IsValidTime (double hour, double minute, double second, double millisecond, double microsecond, double nanosecond)
int8_t ISODaysInMonth (int64_t year, uint8_t month)
bool IsValidIsoDate (double year, double month, double day)
Maybe< temporal_rs::ArithmeticOverflow > ToTemporalOverflowHandleUndefined (Isolate *isolate, DirectHandle< Object > options, const char *method_name)
Maybe< temporal_rs::Precision > GetTemporalFractionalSecondDigitsOption (Isolate *isolate, DirectHandle< JSReceiver > normalized_options, const char *method_name)
Maybe< std::optional< Unit > > GetTemporalUnit (Isolate *isolate, DirectHandle< JSReceiver > normalized_options, const char *key, UnitGroup unit_group, std::optional< Unit > default_value, bool default_is_required, const char *method_name, std::optional< Unit > extra_values=std::nullopt)
Maybe< temporal_rs::AnyCalendarKind > CanonicalizeCalendar (Isolate *isolate, DirectHandle< String > calendar)
Maybe< uint32_t > GetRoundingIncrementOption (Isolate *isolate, DirectHandle< JSReceiver > normalized_options)
Maybe< RoundingMode > GetRoundingModeOption (Isolate *isolate, DirectHandle< JSReceiver > options, RoundingMode fallback, const char *method_name)
Maybe< temporal_rs::DifferenceSettings > GetDifferenceSettingsWithoutChecks (Isolate *isolate, DirectHandle< Object > options_obj, UnitGroup unit_group, std::optional< Unit > fallback_smallest_unit, const char *method_name)
Maybe< temporal_rs::DisplayCalendar > GetTemporalShowCalendarNameOption (Isolate *isolate, DirectHandle< JSReceiver > options, const char *method_name)
MaybeDirectHandle< String > TemporalDurationToString (Isolate *isolate, DirectHandle< JSTemporalDuration > duration, const temporal_rs::ToStringRoundingOptions &&options)
MaybeDirectHandle< String > TemporalInstantToString (Isolate *isolate, DirectHandle< JSTemporalInstant > instant, const temporal_rs::TimeZone *time_zone, const temporal_rs::ToStringRoundingOptions &&options)
MaybeDirectHandle< String > TemporalDateToString (Isolate *isolate, DirectHandle< JSTemporalPlainDate > temporal_date, temporal_rs::DisplayCalendar show_calendar)
MaybeDirectHandle< String > ISODateTimeToString (Isolate *isolate, DirectHandle< JSTemporalPlainDateTime > temporal_date_time, const temporal_rs::ToStringRoundingOptions &&options, temporal_rs::DisplayCalendar show_calendar)
MaybeDirectHandle< String > TimeRecordToString (Isolate *isolate, DirectHandle< JSTemporalPlainTime > time, const temporal_rs::ToStringRoundingOptions &&options)
temporal_rs::PartialTime GetTimeRecord (DirectHandle< JSTemporalPlainTime > plain_time)
temporal_rs::PartialTime GetTimeRecord (DirectHandle< JSTemporalPlainDateTime > date_time)
temporal_rs::PartialTime GetTimeRecord (DirectHandle< JSTemporalZonedDateTime > zoned_date_time)
Maybe< std::optional< int64_t > > GetSingleDurationField (Isolate *isolate, DirectHandle< JSReceiver > duration_like, DirectHandle< String > field_name)
Maybe< std::unique_ptr< temporal_rs::TimeZone > > ToTemporalTimeZoneIdentifier (Isolate *isolate, DirectHandle< Object > tz_like)
Maybe< temporal_rs::PartialDuration > ToTemporalPartialDurationRecord (Isolate *isolate, DirectHandle< Object > duration_like_obj)
template<typename IntegerType >
Maybe< std::optional< IntegerType > > GetSingleTimeRecordField (Isolate *isolate, DirectHandle< JSReceiver > time_like, DirectHandle< String > field_name, bool *any)
Maybe< temporal_rs::PartialTime > ToTemporalTimeRecord (Isolate *isolate, DirectHandle< JSReceiver > time_like, const char *method_name, Completeness completeness=kComplete)
MaybeDirectHandle< JSTemporalDuration > ToTemporalDuration (Isolate *isolate, DirectHandle< Object > item, const char *method_name)
MaybeDirectHandle< JSTemporalInstant > ToTemporalInstant (Isolate *isolate, DirectHandle< Object > item, const char *method_name)
MaybeDirectHandle< JSTemporalPlainTime > ToTemporalTime (Isolate *isolate, DirectHandle< Object > item, std::optional< temporal_rs::ArithmeticOverflow > overflow, const char *method_name)
MaybeDirectHandle< JSTemporalDuration > DifferenceTemporalInstant (Isolate *isolate, DifferenceOperation operation, DirectHandle< JSTemporalInstant > handle, DirectHandle< Object > other_obj, DirectHandle< Object > options, const char *method_name)
MaybeDirectHandle< JSTemporalDuration > DifferenceTemporalPlainTime (Isolate *isolate, DifferenceOperation operation, DirectHandle< JSTemporalPlainTime > handle, DirectHandle< Object > other_obj, DirectHandle< Object > options, const char *method_name)
MaybeDirectHandle< JSTemporalInstant > CreateTemporalInstantWithValidityCheck (Isolate *isolate, DirectHandle< JSFunction > target, DirectHandle< HeapObject > new_target, DirectHandle< BigInt > epoch_nanoseconds)
MaybeDirectHandle< JSTemporalInstant > CreateTemporalInstantWithValidityCheck (Isolate *isolate, DirectHandle< BigInt > epoch_nanoseconds)
MaybeDirectHandle< JSTemporalInstant > BuiltinTimeZoneGetInstantForCompatible (Isolate *isolate, DirectHandle< JSReceiver > time_zone, DirectHandle< JSTemporalPlainDateTime > date_time, const char *method_name)
V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalPlainDateTime > BuiltinTimeZoneGetPlainDateTimeFor (Isolate *isolate, DirectHandle< JSReceiver > time_zone, DirectHandle< JSTemporalInstant > instant, DirectHandle< JSReceiver > calendar, const char *method_name)
V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > InvokeCalendarMethod (Isolate *isolate, DirectHandle< JSReceiver > calendar, DirectHandle< String > name, DirectHandle< JSReceiver > temporal_like)
V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSReceiver > ToTemporalTimeZone (Isolate *isolate, DirectHandle< Object > temporal_time_zone_like, const char *method_name)
Variables
constexpr temporal_rs::ToStringRoundingOptions kToStringAuto
Enumeration Type Documentation
DifferenceOperation
enum v8::internal::temporal::DifferenceOperation
Enumerator
kSince
kUntil
Definition at line 1358 of file js-temporal-objects.cc.
                         {
  kSince,
  kUntil,
};
Function Documentation
BuiltinTimeZoneGetInstantForCompatible()
MaybeDirectHandle<JSTemporalInstant> v8::internal::temporal::BuiltinTimeZoneGetInstantForCompatible (Isolate * isolate, DirectHandle< JSReceiver > time_zone, DirectHandle< JSTemporalPlainDateTime > date_time, const char * method_name)
Definition at line 3451 of file js-temporal-objects.cc.
                                                                              {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
BuiltinTimeZoneGetPlainDateTimeFor()
V8_WARN_UNUSED_RESULT MaybeDirectHandle<JSTemporalPlainDateTime> v8::internal::temporal::BuiltinTimeZoneGetPlainDateTimeFor (Isolate * isolate, DirectHandle< JSReceiver > time_zone, DirectHandle< JSTemporalInstant > instant, DirectHandle< JSReceiver > calendar, const char * method_name)
CanonicalizeCalendar()
Maybe<temporal_rs::AnyCalendarKind> v8::internal::temporal::CanonicalizeCalendar (Isolate * isolate, DirectHandle< String > calendar)
Definition at line 626 of file js-temporal-objects.cc.
                                                     {
  std::string s = calendar->ToStdString();
  // 2. If calendars does not contain the ASCII-lowercase of id, throw a
  // RangeError exception.
  std::transform(s.begin(), s.end(), s.begin(), ::tolower);
  auto cal = temporal_rs::AnyCalendarKind::get_for_str(s);
  if (!cal.has_value()) {
    THROW_NEW_ERROR_RETURN_VALUE(isolate,
                                 NEW_TEMPORAL_INVALID_ARG_RANGE_ERROR(),
                                 Nothing<temporal_rs::AnyCalendarKind>());
  }
  // Other steps unnecessary, we're not storing these as -u- values but rather
  // as enums.
  return Just(cal.value());
}
References v8::Just(), NEW_TEMPORAL_INVALID_ARG_RANGE_ERROR, v8::internal::string, and THROW_NEW_ERROR_RETURN_VALUE.
Referenced by v8::internal::JSTemporalPlainMonthDay::Constructor(), v8::internal::JSTemporalPlainYearMonth::Constructor(), v8::internal::JSTemporalPlainDate::Constructor(), and v8::internal::JSTemporalPlainDateTime::Constructor().
CreateTemporalInstantWithValidityCheck() [1/2]
V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalInstant > v8::internal::temporal::CreateTemporalInstantWithValidityCheck (Isolate * isolate, DirectHandle< BigInt > epoch_nanoseconds)
Definition at line 3115 of file js-temporal-objects.cc.
                                                              {
  TEMPORAL_ENTER_FUNC();
  return CreateTemporalInstantWithValidityCheck(
      isolate, CONSTRUCTOR(instant), CONSTRUCTOR(instant), epoch_nanoseconds);
}
References CONSTRUCTOR, CreateTemporalInstantWithValidityCheck(), and TEMPORAL_ENTER_FUNC.
CreateTemporalInstantWithValidityCheck() [2/2]
V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalInstant > v8::internal::temporal::CreateTemporalInstantWithValidityCheck (Isolate * isolate, DirectHandle< JSFunction > target, DirectHandle< HeapObject > new_target, DirectHandle< BigInt > epoch_nanoseconds)
Definition at line 3083 of file js-temporal-objects.cc.
                                            {
  TEMPORAL_ENTER_FUNC();
  if (epoch_nanoseconds->Words64Count() > 2) {
    // 3. If ! IsValidEpochNanoseconds(epochNanoseconds) is false, throw a
    // RangeError exception.
    // Most validation is performed by the Instant ctor.
    THROW_NEW_ERROR(isolate, NEW_TEMPORAL_INVALID_ARG_RANGE_ERROR());
  }
  uint64_t words[2] = {0, 0};
  uint32_t word_count = 2;
  int sign_bit = 0;
  epoch_nanoseconds->ToWordsArray64(&sign_bit, &word_count, words);
  if (words[1] > std::numeric_limits<int64_t>::max()) {
    THROW_NEW_ERROR(isolate, NEW_TEMPORAL_INVALID_ARG_RANGE_ERROR());
  }
  int64_t high = static_cast<int64_t>(words[1]);
  if (sign_bit == 1) {
    high = -high;
  }
  auto ns = temporal_rs::I128Nanoseconds{.high = high, .low = words[0]};
  return ConstructRustWrappingType<JSTemporalInstant>(
      isolate, target, new_target, temporal_rs::Instant::try_new(ns));
}
References NEW_TEMPORAL_INVALID_ARG_RANGE_ERROR, TEMPORAL_ENTER_FUNC, and THROW_NEW_ERROR.
Referenced by v8::internal::JSTemporalInstant::Constructor(), and CreateTemporalInstantWithValidityCheck().
DifferenceTemporalInstant()
MaybeDirectHandle<JSTemporalDuration> v8::internal::temporal::DifferenceTemporalInstant (Isolate * isolate, DifferenceOperation operation, DirectHandle< JSTemporalInstant > handle, DirectHandle< Object > other_obj, DirectHandle< Object > options, const char * method_name)
Definition at line 1363 of file js-temporal-objects.cc.
                                                           {
  // 1. Set other to ?ToTemporalInstant(other).
  DirectHandle<JSTemporalInstant> other;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, other,
      temporal::ToTemporalInstant(isolate, other_obj, method_name));
  auto settings = temporal_rs::DifferenceSettings{.largest_unit = std::nullopt,
                                                  .smallest_unit = std::nullopt,
                                                  .rounding_mode = std::nullopt,
                                                  .increment = std::nullopt};
  // 2. Let resolvedOptions be ? GetOptionsObject(options).
  // 3. Let settings be ? GetDifferenceSettings(operation, resolvedOptions,
  // time, « », nanosecond, second).
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, settings,
      temporal::GetDifferenceSettingsWithoutChecks(
          isolate, options, UnitGroup::kTime, Unit::Nanosecond, method_name),
      DirectHandle<JSTemporalDuration>());
  // Remaining steps handled by temporal_rs
  // operation negation (step 6) is also handled in temporal_rs
  auto this_rust = handle->instant()->raw();
  auto other_rust = other->instant()->raw();
  auto diff = operation == kUntil ? this_rust->until(*other_rust, settings)
                                  : this_rust->since(*other_rust, settings);
  return ConstructRustWrappingType<JSTemporalDuration>(
      isolate, CONSTRUCTOR(duration), CONSTRUCTOR(duration), std::move(diff));
}
References ASSIGN_RETURN_ON_EXCEPTION, CONSTRUCTOR, v8::internal::duration, GetDifferenceSettingsWithoutChecks(), v8::internal::handle(), kUntil, MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE, and ToTemporalInstant().
Referenced by v8::internal::JSTemporalInstant::Since(), and v8::internal::JSTemporalInstant::Until().
DifferenceTemporalPlainTime()
MaybeDirectHandle<JSTemporalDuration> v8::internal::temporal::DifferenceTemporalPlainTime (Isolate * isolate, DifferenceOperation operation, DirectHandle< JSTemporalPlainTime > handle, DirectHandle< Object > other_obj, DirectHandle< Object > options, const char * method_name)
Definition at line 1399 of file js-temporal-objects.cc.
                                                           {
  // 1. Set other to ?ToTemporalInstant(other).
  DirectHandle<JSTemporalPlainTime> other;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, other,
      temporal::ToTemporalTime(isolate, other_obj, std::nullopt, method_name));
  auto settings = temporal_rs::DifferenceSettings{.largest_unit = std::nullopt,
                                                  .smallest_unit = std::nullopt,
                                                  .rounding_mode = std::nullopt,
                                                  .increment = std::nullopt};
  // 2. Let resolvedOptions be ? GetOptionsObject(options).
  // 3. Let settings be ? GetDifferenceSettings(operation, resolvedOptions,
  // time, « », nanosecond, second).
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, settings,
      temporal::GetDifferenceSettingsWithoutChecks(
          isolate, options, UnitGroup::kTime, Unit::Nanosecond, method_name),
      DirectHandle<JSTemporalDuration>());
  // Remaining steps handled by temporal_rs
  // operation negation (step 6) is also handled in temporal_rs
  auto this_rust = handle->time()->raw();
  auto other_rust = other->time()->raw();
  auto diff = operation == kUntil ? this_rust->until(*other_rust, settings)
                                  : this_rust->since(*other_rust, settings);
  return ConstructRustWrappingType<JSTemporalDuration>(
      isolate, CONSTRUCTOR(duration), CONSTRUCTOR(duration), std::move(diff));
}
References ASSIGN_RETURN_ON_EXCEPTION, CONSTRUCTOR, v8::internal::duration, GetDifferenceSettingsWithoutChecks(), v8::internal::handle(), kUntil, MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE, and ToTemporalTime().
Referenced by v8::internal::JSTemporalPlainTime::Since(), and v8::internal::JSTemporalPlainTime::Until().
GetDifferenceSettingsWithoutChecks()
Maybe<temporal_rs::DifferenceSettings> v8::internal::temporal::GetDifferenceSettingsWithoutChecks (Isolate * isolate, DirectHandle< Object > options_obj, UnitGroup unit_group, std::optional< Unit > fallback_smallest_unit, const char * method_name)
Definition at line 703 of file js-temporal-objects.cc.
                                                                       {
  DirectHandle<JSReceiver> options;
  // 1. Set options to ? GetOptionsObject(options).
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, options, GetOptionsObject(isolate, options_obj, method_name),
      Nothing<temporal_rs::DifferenceSettings>());
  // 2. Let largestUnit be ?GetTemporalUnitValuedOption(options, "largestUnit",
  // unitGroup, auto).
  std::optional<Unit> largest_unit;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, largest_unit,
      GetTemporalUnit(isolate, options, "largestUnit", unit_group, Unit::Auto,
                      false, method_name),
      Nothing<temporal_rs::DifferenceSettings>());
  // 3. If disallowedUnits contains largestUnit, throw a RangeError exception.
  // (skip, to be validated in Rust code)
  // upstream spec issue on observability:
  // https://github.com/tc39/proposal-temporal/issues/3116
  // 4. Let roundingIncrement be ?GetRoundingIncrementOption(options).
  uint32_t rounding_increment;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, rounding_increment,
      temporal::GetRoundingIncrementOption(isolate, options),
      Nothing<temporal_rs::DifferenceSettings>());
  // 5. Let roundingMode be ?GetRoundingModeOption(options, trunc).
  RoundingMode rounding_mode;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, rounding_mode,
      temporal::GetRoundingModeOption(isolate, options, RoundingMode::Trunc,
                                      method_name),
      Nothing<temporal_rs::DifferenceSettings>());
  // 7. Let smallestUnit be ?GetTemporalUnitValuedOption(options,
  // "smallestUnit", unitGroup, fallbackSmallestUnit).
  std::optional<Unit> smallest_unit;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, largest_unit,
      GetTemporalUnit(isolate, options, "smallestUnit", unit_group,
                      fallback_smallest_unit,
                      !fallback_smallest_unit.has_value(), method_name),
      Nothing<temporal_rs::DifferenceSettings>());
  // remaining steps are validation, to be performed later
  return Just(temporal_rs::DifferenceSettings{.largest_unit = largest_unit,
                                              .smallest_unit = smallest_unit,
                                              .rounding_mode = rounding_mode,
                                              .increment = rounding_increment});
}
References ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::GetOptionsObject(), GetRoundingIncrementOption(), GetRoundingModeOption(), GetTemporalUnit(), v8::Just(), and MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE.
Referenced by DifferenceTemporalInstant(), and DifferenceTemporalPlainTime().
GetRoundingIncrementOption()
Maybe<uint32_t> v8::internal::temporal::GetRoundingIncrementOption (Isolate * isolate, DirectHandle< JSReceiver > normalized_options)
Definition at line 646 of file js-temporal-objects.cc.
                                                                   {
  DirectHandle<Object> value;
  // 1. Let value be ? Get(options, "roundingIncrement").
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, value,
      JSReceiver::GetProperty(isolate, normalized_options,
                              isolate->factory()->roundingIncrement_string()),
      Nothing<uint32_t>());
  // 2. If value is undefined, return 1𝔽.
  if (IsUndefined(*value)) {
    return Just(static_cast<uint32_t>(1));
  }
  // 3. Let integerIncrement be ? ToIntegerWithTruncation(value).
  double integer_increment;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, integer_increment, ToIntegerWithTruncation(isolate, value),
      Nothing<uint32_t>());
  // 4. If integerIncrement < 1 or integerIncrement > 10**9, throw a RangeError
  // exception.
  if (integer_increment < 1 || integer_increment > 1e9) {
    THROW_NEW_ERROR_RETURN_VALUE(
        isolate, NEW_TEMPORAL_INVALID_ARG_RANGE_ERROR(), Nothing<uint32_t>());
  }
  return Just(static_cast<uint32_t>(integer_increment));
}
References ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::Isolate::factory(), v8::internal::JSReceiver::GetProperty(), v8::Just(), MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE, NEW_TEMPORAL_INVALID_ARG_RANGE_ERROR, THROW_NEW_ERROR_RETURN_VALUE, ToIntegerWithTruncation(), and v8::internal::value.
Referenced by GetDifferenceSettingsWithoutChecks(), and v8::internal::JSTemporalInstant::Round().
GetRoundingModeOption()
Maybe<RoundingMode> v8::internal::temporal::GetRoundingModeOption (Isolate * isolate, DirectHandle< JSReceiver > options, RoundingMode fallback, const char * method_name)
Definition at line 678 of file js-temporal-objects.cc.
                                                                   {
  // 1. Return ? GetOption(normalizedOptions, "roundingMode", "string", «
  // "ceil", "floor", "expand", "trunc", "halfCeil", "halfFloor", "halfExpand",
  // "halfTrunc", "halfEven" », fallback).
  static const auto values = std::to_array<RoundingMode>(
      {RoundingMode::Ceil, RoundingMode::Floor, RoundingMode::Expand,
       RoundingMode::Trunc, RoundingMode::HalfCeil, RoundingMode::HalfFloor,
       RoundingMode::HalfExpand, RoundingMode::HalfTrunc,
       RoundingMode::HalfEven});
  return GetStringOption<RoundingMode>(
      isolate, options, "roundingMode", method_name,
      std::to_array<const std::string_view>(
          {"ceil", "floor", "expand", "trunc", "halfCeil", "halfFloor",
           "halfExpand", "halfTrunc", "halfEven"}),
      values, fallback);
}
Referenced by GetDifferenceSettingsWithoutChecks(), v8::internal::JSTemporalInstant::Round(), v8::internal::JSTemporalDuration::ToString(), v8::internal::JSTemporalInstant::ToString(), v8::internal::JSTemporalPlainDateTime::ToString(), and v8::internal::JSTemporalPlainTime::ToString().
GetSingleDurationField()
Maybe<std::optional<int64_t> > v8::internal::temporal::GetSingleDurationField (Isolate * isolate, DirectHandle< JSReceiver > duration_like, DirectHandle< String > field_name)
Definition at line 911 of file js-temporal-objects.cc.
                                     {
  DirectHandle<Object> val;
  // Let val be ? Get(temporalDurationLike, fieldName).
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, val, JSReceiver::GetProperty(isolate, duration_like, field_name),
      Nothing<std::optional<int64_t>>());
  // c. If val is not undefined, then
  if (IsUndefined(*val)) {
    return Just((std::optional<int64_t>)std::nullopt);
  } else {
    double field;
    // 5. If val is not undefined, set result.[[val]] to
    // ?ToIntegerIfIntegral(val).
    MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
        isolate, field, temporal::ToIntegerIfIntegral(isolate, val),
        Nothing<std::optional<int64_t>>());
    return Just(std::optional(static_cast<int64_t>(field)));
  }
}
References ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::JSReceiver::GetProperty(), v8::Just(), MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::Nothing(), and ToIntegerIfIntegral().
Referenced by ToTemporalPartialDurationRecord().
GetSingleTimeRecordField()
template<typename IntegerType >
Maybe<std::optional<IntegerType> > v8::internal::temporal::GetSingleTimeRecordField (Isolate * isolate, DirectHandle< JSReceiver > time_like, DirectHandle< String > field_name, bool * any)
Definition at line 1063 of file js-temporal-objects.cc.
                                                {
  DirectHandle<Object> val;
  // Let v be ?Get(temporalTimeLike, field_name).
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, val, JSReceiver::GetProperty(isolate, time_like, field_name),
      Nothing<std::optional<IntegerType>>());
  // If val is not undefined, then
  if (!IsUndefined(*val)) {
    double field;
    // 5. a. Set result.[[Hour]] to ?ToIntegerWithTruncation(hour).
    MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
        isolate, field, temporal::ToIntegerWithTruncation(isolate, val),
        Nothing<std::optional<IntegerType>>());
    // b. Set any to true.
    *any = true;
    // TODO(manishearth) We should ideally be casting later, see
    // https://github.com/boa-dev/temporal/issues/334
    return Just(std::optional(static_cast<IntegerType>(field)));
  } else {
    return Just((std::optional<IntegerType>)std::nullopt);
  }
}
References ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::JSReceiver::GetProperty(), v8::Just(), MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::Nothing(), and ToIntegerWithTruncation().
GetTemporalFractionalSecondDigitsOption()
Maybe<temporal_rs::Precision> v8::internal::temporal::GetTemporalFractionalSecondDigitsOption (Isolate * isolate, DirectHandle< JSReceiver > normalized_options, const char * method_name)
Definition at line 385 of file js-temporal-objects.cc.
                             {
  auto auto_val =
      temporal_rs::Precision{.is_minute = false, .precision = std::nullopt};
  Factory* factory = isolate->factory();
  // 1. Let digitsValue be ?Get(options, "fractionalSecondDigits").
  DirectHandle<Object> digits_val;
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, digits_val,
      JSReceiver::GetProperty(isolate, normalized_options,
                              factory->fractionalSecondDigits_string()),
      Nothing<temporal_rs::Precision>());
  // 2. If digitsValue is undefined, return auto.
  if (IsUndefined(*digits_val)) {
    return Just(auto_val);
  }
  // 3. If digitsValue is not a Number, then
  if (!IsNumber(*digits_val)) {
    DirectHandle<String> string;
    ASSIGN_RETURN_ON_EXCEPTION_VALUE(isolate, string,
                                     Object::ToString(isolate, digits_val),
                                     Nothing<temporal_rs::Precision>());
    // a. If ? ToString(digitsValue) is not "auto", throw a RangeError
    // exception.
    if (!String::Equals(isolate, string, factory->auto_string())) {
      THROW_NEW_ERROR_RETURN_VALUE(
          isolate,
          NewRangeError(MessageTemplate::kPropertyValueOutOfRange,
                        factory->fractionalSecondDigits_string()),
          Nothing<temporal_rs::Precision>());
    }
    // b. Return auto.
    return Just(auto_val);
  }
  // 4. If digitsValue is NaN, +∞𝔽, or -∞𝔽, throw a RangeError exception.
  auto digits_num = Cast<Number>(*digits_val);
  auto digits_float = Object::NumberValue(digits_num);
  if (std::isnan(digits_float) || std::isinf(digits_float)) {
    THROW_NEW_ERROR_RETURN_VALUE(
        isolate,
        NewRangeError(MessageTemplate::kPropertyValueOutOfRange,
                      factory->fractionalSecondDigits_string()),
        Nothing<temporal_rs::Precision>());
  }
  // 5. Let digitCount be floor(ℝ(digitsValue)).
  int64_t digit_count = std::floor(Object::NumberValue(digits_num));
  // 6. If digitCount < 0 or digitCount > 9, throw a RangeError exception.
  if (digit_count < 0 || digit_count > 9) {
    THROW_NEW_ERROR_RETURN_VALUE(
        isolate,
        NewRangeError(MessageTemplate::kPropertyValueOutOfRange,
                      factory->fractionalSecondDigits_string()),
        Nothing<temporal_rs::Precision>());
  }
  return Just(
      temporal_rs::Precision{.is_minute = false, .precision = digit_count});
}
References ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::String::Equals(), v8::internal::Isolate::factory(), v8::internal::JSReceiver::GetProperty(), v8::internal::IsNumber(), v8::Just(), v8::internal::Object::NumberValue(), v8::internal::string, THROW_NEW_ERROR_RETURN_VALUE, and v8::Value::ToString().
Referenced by v8::internal::JSTemporalDuration::ToString(), v8::internal::JSTemporalInstant::ToString(), v8::internal::JSTemporalPlainDateTime::ToString(), and v8::internal::JSTemporalPlainTime::ToString().
GetTemporalShowCalendarNameOption()
Maybe<temporal_rs::DisplayCalendar> v8::internal::temporal::GetTemporalShowCalendarNameOption (Isolate * isolate, DirectHandle< JSReceiver > options, const char * method_name)
Definition at line 760 of file js-temporal-objects.cc.
                             {
  // 1. Return ? GetOption(normalizedOptions, "calendarName", « String », «
  // "auto", "always", "never" », "auto").
  return GetStringOption<temporal_rs::DisplayCalendar>(
      isolate, options, "calendarName", method_name,
      std::to_array<const std::string_view>(
          {"auto", "always", "never", "critical"}),
      std::to_array<temporal_rs::DisplayCalendar>(
          {temporal_rs::DisplayCalendar::Auto,
           temporal_rs::DisplayCalendar::Always,
           temporal_rs::DisplayCalendar::Never,
           temporal_rs::DisplayCalendar::Critical}),
      temporal_rs::DisplayCalendar::Auto);
}
Referenced by v8::internal::JSTemporalPlainDate::ToString(), and v8::internal::JSTemporalPlainDateTime::ToString().
GetTemporalUnit()
Maybe<std::optional<Unit> > v8::internal::temporal::GetTemporalUnit (Isolate * isolate, DirectHandle< JSReceiver > normalized_options, const char * key, UnitGroup unit_group, std::optional< Unit > default_value, bool default_is_required, const char * method_name, std::optional< Unit > extra_values = std::nullopt)
Definition at line 471 of file js-temporal-objects.cc.
                                                 {
  std::span<const std::string_view> str_values;
  std::span<const std::optional<Unit::Value>> enum_values;
  switch (unit_group) {
    case UnitGroup::kDate:
      if (default_value == Unit::Auto || extra_values == Unit::Auto) {
        static auto strs = std::to_array<const std::string_view>(
            {"year", "month", "week", "day", "auto", "years", "months", "weeks",
             "days"});
        static auto enums = std::to_array<const std::optional<Unit::Value>>(
            {Unit::Year, Unit::Month, Unit::Week, Unit::Day, Unit::Auto,
             Unit::Year, Unit::Month, Unit::Week, Unit::Day});
        str_values = strs;
        enum_values = enums;
      } else {
        DCHECK(default_value == std::nullopt || default_value == Unit::Year ||
               default_value == Unit::Month || default_value == Unit::Week ||
               default_value == Unit::Day);
        static auto strs = std::to_array<const std::string_view>(
            {"year", "month", "week", "day", "years", "months", "weeks",
             "days"});
        static auto enums = std::to_array<const std::optional<Unit::Value>>(
            {Unit::Year, Unit::Month, Unit::Week, Unit::Day, Unit::Year,
             Unit::Month, Unit::Week, Unit::Day});
        str_values = strs;
        enum_values = enums;
      }
      break;
    case UnitGroup::kTime:
      if (default_value == Unit::Auto || extra_values == Unit::Auto) {
        static auto strs = std::to_array<const std::string_view>(
            {"hour", "minute", "second", "millisecond", "microsecond",
             "nanosecond", "auto", "hours", "minutes", "seconds",
             "milliseconds", "microseconds", "nanoseconds"});
        static auto enums = std::to_array<const std::optional<Unit::Value>>(
            {Unit::Hour, Unit::Minute, Unit::Second, Unit::Millisecond,
             Unit::Microsecond, Unit::Nanosecond, Unit::Auto, Unit::Hour,
             Unit::Minute, Unit::Second, Unit::Millisecond, Unit::Microsecond,
             Unit::Nanosecond});
        str_values = strs;
        enum_values = enums;
      } else if (default_value == Unit::Day || extra_values == Unit::Day) {
        static auto strs = std::to_array<const std::string_view>(
            {"hour", "minute", "second", "millisecond", "microsecond",
             "nanosecond", "day", "hours", "minutes", "seconds", "milliseconds",
             "microseconds", "nanoseconds", "days"});
        static auto enums = std::to_array<const std::optional<Unit::Value>>(
            {Unit::Hour, Unit::Minute, Unit::Second, Unit::Millisecond,
             Unit::Microsecond, Unit::Nanosecond, Unit::Day, Unit::Hour,
             Unit::Minute, Unit::Second, Unit::Millisecond, Unit::Microsecond,
             Unit::Nanosecond, Unit::Day});
        str_values = strs;
        enum_values = enums;
      } else {
        DCHECK(default_value == std::nullopt || default_value == Unit::Hour ||
               default_value == Unit::Minute || default_value == Unit::Second ||
               default_value == Unit::Millisecond ||
               default_value == Unit::Microsecond ||
               default_value == Unit::Nanosecond);
        static auto strs = std::to_array<const std::string_view>(
            {"hour", "minute", "second", "millisecond", "microsecond",
             "nanosecond", "hours", "minutes", "seconds", "milliseconds",
             "microseconds", "nanoseconds"});
        static auto enums = std::to_array<const std::optional<Unit::Value>>(
            {Unit::Hour, Unit::Minute, Unit::Second, Unit::Millisecond,
             Unit::Microsecond, Unit::Nanosecond, Unit::Hour, Unit::Minute,
             Unit::Second, Unit::Millisecond, Unit::Microsecond,
             Unit::Nanosecond});
        str_values = strs;
        enum_values = enums;
      }
      break;
    case UnitGroup::kDateTime:
      if (default_value == Unit::Auto || extra_values == Unit::Auto) {
        static auto strs = std::to_array<const std::string_view>(
            {"year", "month", "week", "day",
             "hour", "minute", "second", "millisecond",
             "microsecond", "nanosecond", "auto", "years",
             "months", "weeks", "days", "hours",
             "minutes", "seconds", "milliseconds", "microseconds",
             "nanoseconds"});
        static auto enums = std::to_array<const std::optional<Unit::Value>>(
            {Unit::Year, Unit::Month, Unit::Week,
             Unit::Day, Unit::Hour, Unit::Minute,
             Unit::Second, Unit::Millisecond, Unit::Microsecond,
             Unit::Nanosecond, Unit::Auto, Unit::Year,
             Unit::Month, Unit::Week, Unit::Day,
             Unit::Hour, Unit::Minute, Unit::Second,
             Unit::Millisecond, Unit::Microsecond, Unit::Nanosecond});
        str_values = strs;
        enum_values = enums;
      } else {
        static auto strs = std::to_array<const std::string_view>(
            {"year", "month", "week", "day",
             "hour", "minute", "second", "millisecond",
             "microsecond", "nanosecond", "years", "months",
             "weeks", "days", "hours", "minutes",
             "seconds", "milliseconds", "microseconds", "nanoseconds"});
        static auto enums = std::to_array<const std::optional<Unit::Value>>(
            {Unit::Year, Unit::Month, Unit::Week,
             Unit::Day, Unit::Hour, Unit::Minute,
             Unit::Second, Unit::Millisecond, Unit::Microsecond,
             Unit::Nanosecond, Unit::Year, Unit::Month,
             Unit::Week, Unit::Day, Unit::Hour,
             Unit::Minute, Unit::Second, Unit::Millisecond,
             Unit::Microsecond, Unit::Nanosecond});
        str_values = strs;
        enum_values = enums;
      }
      break;
  }
  // 4. If default is required, then
  if (default_is_required) default_value = std::nullopt;
  // a. Let defaultValue be undefined.
  // 5. Else,
  // a. Let defaultValue be default.
  // b. If defaultValue is not undefined and singularNames does not contain
  // defaultValue, then i. Append defaultValue to singularNames.
  // 9. Let value be ? GetOption(normalizedOptions, key, "string",
  // allowedValues, defaultValue).
  std::optional<Unit::Value> value;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, value,
      GetStringOption<std::optional<Unit::Value>>(isolate, normalized_options,
                                                  key, method_name, str_values,
                                                  enum_values, default_value),
      Nothing<std::optional<Unit>>());
  // 10. If value is undefined and default is required, throw a RangeError
  // exception.
  if (default_is_required && value == std::nullopt) {
    THROW_NEW_ERROR_RETURN_VALUE(
        isolate,
        NewRangeError(
            MessageTemplate::kValueOutOfRange,
            isolate->factory()->undefined_value(),
            isolate->factory()->NewStringFromAsciiChecked(method_name),
            isolate->factory()->NewStringFromAsciiChecked(key)),
        Nothing<std::optional<Unit>>());
  }
  // 12. Return value.
  if (value.has_value()) {
    return Just<std::optional<Unit>>((Unit)value.value());
  } else {
    return Just<std::optional<Unit>>(std::nullopt);
  }
}
References v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::internal::GetStringOption(), v8::internal::key, MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::Microsecond, v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), v8::Nothing(), THROW_NEW_ERROR_RETURN_VALUE, and v8::internal::value.
Referenced by GetDifferenceSettingsWithoutChecks(), v8::internal::JSTemporalInstant::Round(), v8::internal::JSTemporalDuration::ToString(), v8::internal::JSTemporalInstant::ToString(), v8::internal::JSTemporalPlainDateTime::ToString(), and v8::internal::JSTemporalPlainTime::ToString().
GetTimeRecord() [1/3]
temporal_rs::PartialTime v8::internal::temporal::GetTimeRecord (DirectHandle< JSTemporalPlainDateTime > date_time)
Definition at line 891 of file js-temporal-objects.cc.
                                                     {
  auto rust_object = date_time->date_time()->raw();
  return temporal_rs::PartialTime{
      .hour = rust_object->hour(),
      .minute = rust_object->minute(),
      .second = rust_object->second(),
      .millisecond = rust_object->millisecond(),
      .microsecond = rust_object->microsecond(),
      .nanosecond = rust_object->nanosecond(),
  };
}
References v8::internal::date_time.
GetTimeRecord() [2/3]
temporal_rs::PartialTime v8::internal::temporal::GetTimeRecord (DirectHandle< JSTemporalPlainTime > plain_time)
Definition at line 879 of file js-temporal-objects.cc.
                                                  {
  auto rust_object = plain_time->time()->raw();
  return temporal_rs::PartialTime{
      .hour = rust_object->hour(),
      .minute = rust_object->minute(),
      .second = rust_object->second(),
      .millisecond = rust_object->millisecond(),
      .microsecond = rust_object->microsecond(),
      .nanosecond = rust_object->nanosecond(),
  };
}
Referenced by ToTemporalTime().
GetTimeRecord() [3/3]
temporal_rs::PartialTime v8::internal::temporal::GetTimeRecord (DirectHandle< JSTemporalZonedDateTime > zoned_date_time)
Definition at line 903 of file js-temporal-objects.cc.
                                                           {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
InvokeCalendarMethod()
V8_WARN_UNUSED_RESULT MaybeDirectHandle<Object> v8::internal::temporal::InvokeCalendarMethod (Isolate * isolate, DirectHandle< JSReceiver > calendar, DirectHandle< String > name, DirectHandle< JSReceiver > temporal_like)
ISODateTimeToString()
MaybeDirectHandle<String> v8::internal::temporal::ISODateTimeToString (Isolate * isolate, DirectHandle< JSTemporalPlainDateTime > temporal_date_time, const temporal_rs::ToStringRoundingOptions && options, temporal_rs::DisplayCalendar show_calendar)
Definition at line 842 of file js-temporal-objects.cc.
                                              {
  std::string output;
  // This is currently inefficient, can be improved after
  // https://github.com/rust-diplomat/diplomat/issues/866 is fixed
  MAYBE_MOVE_RETURN_ON_EXCEPTION_VALUE(
      isolate, output,
      ExtractRustResult(isolate,
                        temporal_date_time->date_time()->raw()->to_ixdtf_string(
                            std::move(options), show_calendar)),
      MaybeDirectHandle<String>());
  IncrementalStringBuilder builder(isolate);
  builder.AppendString(output);
  return builder.Finish().ToHandleChecked();
}
References v8::internal::IncrementalStringBuilder::AppendString(), v8::internal::anonymous_namespace{js-temporal-objects.cc}::ExtractRustResult(), v8::internal::IncrementalStringBuilder::Finish(), MAYBE_MOVE_RETURN_ON_EXCEPTION_VALUE, and v8::internal::string.
Referenced by v8::internal::JSTemporalPlainDateTime::ToJSON(), v8::internal::JSTemporalPlainDateTime::ToLocaleString(), and v8::internal::JSTemporalPlainDateTime::ToString().
ISODaysInMonth()
int8_t v8::internal::temporal::ISODaysInMonth (int64_t year, uint8_t month)
Definition at line 303 of file js-temporal-objects.cc.
                                                   {
  switch (month) {
    // 1. If month is 1, 3, 5, 7, 8, 10, or 12, return 31.
    case 1:
    case 3:
    case 5:
    case 7:
    case 8:
    case 10:
    case 12:
      return 31;
    // 4. Return 28 + MathematicalInLeapYear(EpochTimeForYear(year)).
    case 2:
      if (year % 4 == 0 && (year % 100 != 0 || year % 400 == 0)) {
        return 29;
      } else {
        return 28;
      }
    // 2. If month is 4, 6, 9, or 11, return 30.
    default:
      return 30;
  }
}
Referenced by IsValidIsoDate().
IsValidDuration()
bool v8::internal::temporal::IsValidDuration (Isolate * isolate, const DurationRecord & dur)
Definition at line 90 of file js-temporal-helpers.cc.
                                                                  {
  // 1. Let sign be ! DurationSign(years, months, weeks, days, hours, minutes,
  // seconds, milliseconds, microseconds, nanoseconds).
  int32_t sign = DurationRecord::Sign(dur);
  // 2. For each value v of « years, months, weeks, days, hours, minutes,
  // seconds, milliseconds, microseconds, nanoseconds », do a. If v is not
  // finite, return false. b. If v < 0 and sign > 0, return false. c. If v > 0
  // and sign < 0, return false.
  // 3. Return true.
  const TimeDurationRecord& time = dur.time_duration;
  if (!(std::isfinite(dur.years) && std::isfinite(dur.months) &&
        std::isfinite(dur.weeks) && std::isfinite(time.days) &&
        std::isfinite(time.hours) && std::isfinite(time.minutes) &&
        std::isfinite(time.seconds) && std::isfinite(time.milliseconds) &&
        std::isfinite(time.microseconds) && std::isfinite(time.nanoseconds))) {
    return false;
  }
  if ((sign > 0 && (dur.years < 0 || dur.months < 0 || dur.weeks < 0 ||
                    time.days < 0 || time.hours < 0 || time.minutes < 0 ||
                    time.seconds < 0 || time.milliseconds < 0 ||
                    time.microseconds < 0 || time.nanoseconds < 0)) ||
      (sign < 0 && (dur.years > 0 || dur.months > 0 || dur.weeks > 0 ||
                    time.days > 0 || time.hours > 0 || time.minutes > 0 ||
                    time.seconds > 0 || time.milliseconds > 0 ||
                    time.microseconds > 0 || time.nanoseconds > 0))) {
    return false;
  }
  static const double kPower32Of2 = static_cast<double>(int64_t(1) << 32);
  static const int64_t kPower53Of2 = int64_t(1) << 53;
  // 3. If abs(years) ≥ 2**32, return false.
  if (std::abs(dur.years) >= kPower32Of2) {
    return false;
  }
  // 4. If abs(months) ≥ 2**32, return false.
  if (std::abs(dur.months) >= kPower32Of2) {
    return false;
  }
  // 5. If abs(weeks) ≥ 2**32, return false.
  if (std::abs(dur.weeks) >= kPower32Of2) {
    return false;
  }
  // 6. Let normalizedSeconds be days × 86,400 + hours × 3600 + minutes × 60 +
  // seconds + ℝ(𝔽(milliseconds)) × 10**-3 + ℝ(𝔽(microseconds)) × 10**-6 +
  // ℝ(𝔽(nanoseconds)) × 10**-9.
  // 7. NOTE: The above step cannot be implemented directly using floating-point
  // arithmetic. Multiplying by 10**-3, 10**-6, and 10**-9 respectively may be
  // imprecise when milliseconds, microseconds, or nanoseconds is an unsafe
  // integer. This multiplication can be implemented in C++ with an
  // implementation of std::remquo() with sufficient bits in the quotient.
  // String manipulation will also give an exact result, since the
  // multiplication is by a power of 10.
  // 8. If abs(normalizedSeconds) ≥ 2**53, return false.
  int64_t allowed = kPower53Of2;
  double in_seconds = std::abs(time.days * 86400.0 + time.hours * 3600.0 +
                               time.minutes * 60.0 + time.seconds);
  if (in_seconds >= allowed) {
    return false;
  }
  allowed -= in_seconds;
  // Check the part > 1 seconds.
  in_seconds = std::floor(std::abs(time.milliseconds / 1e3)) +
               std::floor(std::abs(time.microseconds / 1e6)) +
               std::floor(std::abs(time.nanoseconds / 1e9));
  if (in_seconds >= allowed) {
    return false;
  }
  allowed -= in_seconds;
  // Sum of the three remainings will surely < 3
  if (allowed > 3) {
    return true;
  }
  allowed *= 1000000000; // convert to ns
  int64_t remainders = std::abs(fmod(time.milliseconds, 1e3)) * 1000000 +
                       std::abs(fmod(time.microseconds, 1e6)) * 1000 +
                       std::abs(fmod(time.nanoseconds, 1e9));
  if (remainders >= allowed) {
    return false;
  }
  return true;
}
References v8::internal::temporal::DurationRecord::months, v8::internal::sign, v8::internal::temporal::DurationRecord::Sign(), v8::internal::time, v8::internal::temporal::DurationRecord::time_duration, v8::internal::temporal::DurationRecord::weeks, and v8::internal::temporal::DurationRecord::years.
Referenced by v8::internal::temporal::TimeDurationRecord::Create(), v8::internal::temporal::DurationRecord::Create(), and v8::internal::anonymous_namespace{js-duration-format.cc}::ToDurationRecord().
IsValidIsoDate()
bool v8::internal::temporal::IsValidIsoDate (double year, double month, double day)
Definition at line 328 of file js-temporal-objects.cc.
                                                           {
  // 1. If month < 1 or month > 12, then
  if (month < 1 || month > 12) {
    // a. Return false.
    return false;
  }
  // This check is technically needed later when we check if things are in the
  // Temporal range, but we do it now to ensure we can safely cast to int32_t
  // before passing to Rust See https://github.com/boa-dev/temporal/issues/334.
  if (year < std::numeric_limits<int32_t>::min() ||
      year > std::numeric_limits<int32_t>::max()) {
    return false;
  }
  // IsValidIsoDate does not care about years that are "out of Temporal range",
  // that gets handled later.
  int64_t year_int = static_cast<int32_t>(year);
  uint8_t month_int = static_cast<uint8_t>(month);
  // 2. Let daysInMonth be ISODaysInMonth(year, month).
  // 3. If day < 1 or day > daysInMonth, then
  if (day < 1 || day > ISODaysInMonth(year_int, month_int)) {
    // a. Return false.
    return false;
  }
  // 4. Return true.
  return true;
}
References ISODaysInMonth().
Referenced by v8::internal::JSTemporalPlainMonthDay::Constructor(), v8::internal::JSTemporalPlainYearMonth::Constructor(), v8::internal::JSTemporalPlainDate::Constructor(), and v8::internal::JSTemporalPlainDateTime::Constructor().
IsValidTime()
bool v8::internal::temporal::IsValidTime (double hour, double minute, double second, double millisecond, double microsecond, double nanosecond)
Definition at line 265 of file js-temporal-objects.cc.
                                                        {
  // 1. If hour < 0 or hour > 23, then
  // a. Return false.
  if (hour < 0 || hour > 23) {
    return false;
  }
  // 2. If minute < 0 or minute > 59, then
  // a. Return false.
  if (minute < 0 || minute > 59) {
    return false;
  }
  // 3. If second < 0 or second > 59, then
  // a. Return false.
  if (second < 0 || second > 59) {
    return false;
  }
  // 4. If millisecond < 0 or millisecond > 999, then
  // a. Return false.
  if (millisecond < 0 || millisecond > 999) {
    return false;
  }
  // 5. If microsecond < 0 or microsecond > 999, then
  // a. Return false.
  if (microsecond < 0 || microsecond > 999) {
    return false;
  }
  // 6. If nanosecond < 0 or nanosecond > 999, then
  // a. Return false.
  if (nanosecond < 0 || nanosecond > 999) {
    return false;
  }
  // 7. Return true.
  return true;
}
Referenced by v8::internal::JSTemporalPlainTime::Constructor(), and v8::internal::JSTemporalPlainDateTime::Constructor().
TemporalDateToString()
MaybeDirectHandle<String> v8::internal::temporal::TemporalDateToString (Isolate * isolate, DirectHandle< JSTemporalPlainDate > temporal_date, temporal_rs::DisplayCalendar show_calendar)
Definition at line 826 of file js-temporal-objects.cc.
                                              {
  // This is currently inefficient, can be improved after
  // https://github.com/rust-diplomat/diplomat/issues/866 is fixed
  auto output = temporal_date->date()->raw()->to_ixdtf_string(show_calendar);
  IncrementalStringBuilder builder(isolate);
  builder.AppendString(output);
  return builder.Finish().ToHandleChecked();
}
References v8::internal::IncrementalStringBuilder::AppendString(), and v8::internal::IncrementalStringBuilder::Finish().
Referenced by v8::internal::JSTemporalPlainDate::ToJSON(), v8::internal::JSTemporalPlainDate::ToLocaleString(), and v8::internal::JSTemporalPlainDate::ToString().
TemporalDurationToString()
MaybeDirectHandle<String> v8::internal::temporal::TemporalDurationToString (Isolate * isolate, DirectHandle< JSTemporalDuration > duration, const temporal_rs::ToStringRoundingOptions && options)
Definition at line 788 of file js-temporal-objects.cc.
                                                        {
  std::string output;
  // This is currently inefficient, can be improved after
  // https://github.com/rust-diplomat/diplomat/issues/866 is fixed
  MAYBE_MOVE_RETURN_ON_EXCEPTION_VALUE(
      isolate, output,
      ExtractRustResult(isolate,
                        duration->duration()->raw()->to_string(options)),
      MaybeDirectHandle<String>());
  IncrementalStringBuilder builder(isolate);
  builder.AppendString(output);
  return builder.Finish().ToHandleChecked();
}
References v8::internal::IncrementalStringBuilder::AppendString(), v8::internal::duration, v8::internal::anonymous_namespace{js-temporal-objects.cc}::ExtractRustResult(), v8::internal::IncrementalStringBuilder::Finish(), MAYBE_MOVE_RETURN_ON_EXCEPTION_VALUE, and v8::internal::string.
Referenced by v8::internal::JSTemporalDuration::ToJSON(), v8::internal::JSTemporalDuration::ToLocaleString(), and v8::internal::JSTemporalDuration::ToString().
TemporalInstantToString()
MaybeDirectHandle<String> v8::internal::temporal::TemporalInstantToString (Isolate * isolate, DirectHandle< JSTemporalInstant > instant, const temporal_rs::TimeZone * time_zone, const temporal_rs::ToStringRoundingOptions && options)
Definition at line 805 of file js-temporal-objects.cc.
                                                        {
  std::string output;
  // This is currently inefficient, can be improved after
  // https://github.com/rust-diplomat/diplomat/issues/866 is fixed
  MAYBE_MOVE_RETURN_ON_EXCEPTION_VALUE(
      isolate, output,
      ExtractRustResult(
          isolate,
          instant->instant()->raw()->to_ixdtf_string_with_compiled_data(
              time_zone, options)),
      MaybeDirectHandle<String>());
  IncrementalStringBuilder builder(isolate);
  builder.AppendString(output);
  return builder.Finish().ToHandleChecked();
}
References v8::internal::IncrementalStringBuilder::AppendString(), v8::internal::anonymous_namespace{js-temporal-objects.cc}::ExtractRustResult(), v8::internal::IncrementalStringBuilder::Finish(), MAYBE_MOVE_RETURN_ON_EXCEPTION_VALUE, and v8::internal::string.
Referenced by v8::internal::JSTemporalInstant::ToJSON(), v8::internal::JSTemporalInstant::ToLocaleString(), and v8::internal::JSTemporalInstant::ToString().
TimeRecordToString()
MaybeDirectHandle<String> v8::internal::temporal::TimeRecordToString (Isolate * isolate, DirectHandle< JSTemporalPlainTime > time, const temporal_rs::ToStringRoundingOptions && options)
Definition at line 861 of file js-temporal-objects.cc.
                                                        {
  std::string output;
  // This is currently inefficient, can be improved after
  // https://github.com/rust-diplomat/diplomat/issues/866 is fixed
  MAYBE_MOVE_RETURN_ON_EXCEPTION_VALUE(
      isolate, output,
      ExtractRustResult(isolate, time->time()->raw()->to_ixdtf_string(options)),
      MaybeDirectHandle<String>());
  IncrementalStringBuilder builder(isolate);
  builder.AppendString(output);
  return builder.Finish().ToHandleChecked();
}
References v8::internal::IncrementalStringBuilder::AppendString(), v8::internal::anonymous_namespace{js-temporal-objects.cc}::ExtractRustResult(), v8::internal::IncrementalStringBuilder::Finish(), MAYBE_MOVE_RETURN_ON_EXCEPTION_VALUE, v8::internal::string, and v8::internal::time.
Referenced by v8::internal::JSTemporalPlainTime::ToJSON(), v8::internal::JSTemporalPlainTime::ToLocaleString(), and v8::internal::JSTemporalPlainTime::ToString().
ToIntegerIfIntegral()
Maybe<double> v8::internal::temporal::ToIntegerIfIntegral (Isolate * isolate, DirectHandle< Object > argument)
Definition at line 230 of file js-temporal-objects.cc.
                                                                 {
  // 1. Let number be ? ToNumber(argument).
  DirectHandle<Number> number;
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, number, Object::ToNumber(isolate, argument), Nothing<double>());
  double number_double = Object::NumberValue(*number);
  // 2. If number is not an integral Number, throw a RangeError exception.
  if (!std::isfinite(number_double) ||
      nearbyint(number_double) != number_double) {
    THROW_NEW_ERROR_RETURN_VALUE(
        isolate, NEW_TEMPORAL_INVALID_ARG_RANGE_ERROR(), Nothing<double>());
  }
  // 3. Return ℝ(number).
  return Just(number_double);
}
References ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::Just(), NEW_TEMPORAL_INVALID_ARG_RANGE_ERROR, v8::internal::Object::NumberValue(), THROW_NEW_ERROR_RETURN_VALUE, and v8::Value::ToNumber().
Referenced by v8::internal::JSTemporalDuration::Constructor(), and GetSingleDurationField().
ToIntegerWithTruncation()
Maybe<double> v8::internal::temporal::ToIntegerWithTruncation (Isolate * isolate, DirectHandle< Object > argument)
Definition at line 248 of file js-temporal-objects.cc.
                                                                     {
  // 1. Let number be ? ToNumber(argument).
  double number;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, number, Object::IntegerValue(isolate, argument),
      Nothing<double>());
  // 2. If number is NaN, +∞𝔽 or -∞𝔽, throw a RangeError exception.
  if (!std::isfinite(number)) {
    THROW_NEW_ERROR_RETURN_VALUE(
        isolate, NEW_TEMPORAL_INVALID_ARG_RANGE_ERROR(), Nothing<double>());
  }
  // 3. Return truncate(number).
  return Just(number);
}
References v8::Value::IntegerValue(), v8::Just(), MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE, NEW_TEMPORAL_INVALID_ARG_RANGE_ERROR, and THROW_NEW_ERROR_RETURN_VALUE.
Referenced by v8::internal::JSTemporalPlainTime::Constructor(), v8::internal::JSTemporalPlainMonthDay::Constructor(), v8::internal::JSTemporalPlainYearMonth::Constructor(), v8::internal::JSTemporalPlainDate::Constructor(), v8::internal::JSTemporalPlainDateTime::Constructor(), GetRoundingIncrementOption(), and GetSingleTimeRecordField().
ToPartialDuration()
Maybe< DurationRecord > v8::internal::temporal::ToPartialDuration (Isolate * isolate, DirectHandle< Object > temporal_duration_like_obj, const DurationRecord & input)
Definition at line 255 of file js-temporal-helpers.cc.
                                 {
  // 1. If Type(temporalDurationLike) is not Object, then
  if (!IsJSReceiver(*temporal_duration_like_obj)) {
    // a. Throw a TypeError exception.
    THROW_NEW_ERROR_RETURN_VALUE(isolate, NEW_TEMPORAL_INVALID_ARG_TYPE_ERROR(),
                                 Nothing<DurationRecord>());
  }
  DirectHandle<JSReceiver> temporal_duration_like =
      Cast<JSReceiver>(temporal_duration_like_obj);
  // 2. Let result be a new partial Duration Record with each field set to
  // undefined.
  DurationRecord result = input;
  // 3. Let any be false.
  bool any = false;
  // Table 8: Duration Record Fields
  // #table-temporal-duration-record-fields
  // 4. For each row of Table 8, except the header row, in table order, do
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, any,
      IterateDurationRecordFieldsTable(
          isolate, temporal_duration_like,
          [](Isolate* isolate, DirectHandle<JSReceiver> temporal_duration_like,
             DirectHandle<String> prop, double* field) -> Maybe<bool> {
            bool not_undefined = false;
            // a. Let prop be the Property value of the current row.
            DirectHandle<Object> val;
            // b. Let val be ? Get(temporalDurationLike, prop).
            ASSIGN_RETURN_ON_EXCEPTION_VALUE(
                isolate, val,
                JSReceiver::GetProperty(isolate, temporal_duration_like, prop),
                Nothing<bool>());
            // c. If val is not undefined, then
            if (!IsUndefined(*val)) {
              // i. Set any to true.
              not_undefined = true;
              // ii. Let val be 𝔽(? ToIntegerWithoutRounding(val)).
              // iii. Set result's field whose name is the Field Name value of
              // the current row to val.
              MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
                  isolate, *field, ToIntegerWithoutRounding(isolate, val),
                  Nothing<bool>());
            }
            return Just(not_undefined);
          },
          &result),
      Nothing<DurationRecord>());
  // 5. If any is false, then
  if (!any) {
    // a. Throw a TypeError exception.
    THROW_NEW_ERROR_RETURN_VALUE(isolate, NEW_TEMPORAL_INVALID_ARG_TYPE_ERROR(),
                                 Nothing<DurationRecord>());
  }
  // 6. Return result.
  return Just(result);
}
References ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::JSReceiver::GetProperty(), v8::internal::temporal::anonymous_namespace{js-temporal-helpers.cc}::IterateDurationRecordFieldsTable(), v8::Just(), MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE, NEW_TEMPORAL_INVALID_ARG_TYPE_ERROR, v8::base::internal::result, THROW_NEW_ERROR_RETURN_VALUE, and v8::internal::temporal::anonymous_namespace{js-temporal-helpers.cc}::ToIntegerWithoutRounding().
Referenced by v8::internal::anonymous_namespace{js-duration-format.cc}::ToDurationRecord().
ToTemporalDuration()
MaybeDirectHandle<JSTemporalDuration> v8::internal::temporal::ToTemporalDuration (Isolate * isolate, DirectHandle< Object > item, const char * method_name)
Definition at line 1163 of file js-temporal-objects.cc.
                                                                          {
  TEMPORAL_ENTER_FUNC();
  // 1. If item is an Object and item has an [[InitializedTemporalDuration]]
  // internal slot, then a. a. Return ! CreateTemporalDuration(item.[[Years]],
  // item.[[Months]], item.[[Weeks]], item.[[Days]], item.[[Hours]],
  // item.[[Minutes]], item.[[Seconds]], item.[[Milliseconds]],
  // item.[[Microseconds]], item.[[Nanoseconds]]).
  if (IsJSTemporalDuration(*item)) {
    auto instant = Cast<JSTemporalDuration>(item);
    auto raw = instant->duration()->raw();
    auto years = raw->years();
    auto months = raw->months();
    auto weeks = raw->weeks();
    auto days = raw->days();
    auto hours = raw->hours();
    auto minutes = raw->minutes();
    auto seconds = raw->seconds();
    auto milliseconds = raw->milliseconds();
    auto microseconds = raw->microseconds();
    auto nanoseconds = raw->nanoseconds();
    // i. Return !CreateTemporalInstant(item.[[EpochNanoseconds]]).
    return ConstructRustWrappingType<JSTemporalDuration>(
        isolate, CONSTRUCTOR(duration), CONSTRUCTOR(duration),
        temporal_rs::Duration::create(years, months, weeks, days, hours,
                                      minutes, seconds, milliseconds,
                                      microseconds, nanoseconds));
  }
  // 2. If item is not an Object, then
  if (!IsJSReceiver(*item)) {
    // a. If item is not a String, throw a TypeError exception.
    if (!IsString(*item)) {
      THROW_NEW_ERROR(isolate, NEW_TEMPORAL_INVALID_ARG_TYPE_ERROR());
    }
    DirectHandle<String> str = Cast<String>(item);
    // b. Let result be ? ParseTemporalDurationString(string).
    DirectHandle<JSTemporalInstant> result;
    auto rust_result =
        HandleStringEncodings<TemporalAllocatedResult<temporal_rs::Duration>>(
            isolate, str,
            [](std::string_view view)
                -> TemporalAllocatedResult<temporal_rs::Duration> {
              return temporal_rs::Duration::from_utf8(view);
            },
            [](std::u16string_view view)
                -> TemporalAllocatedResult<temporal_rs::Duration> {
              return temporal_rs::Duration::from_utf16(view);
            });
    return ConstructRustWrappingType<JSTemporalDuration>(
        isolate, CONSTRUCTOR(duration), CONSTRUCTOR(duration),
        std::move(rust_result));
  }
  temporal_rs::PartialDuration partial;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, partial,
      temporal::ToTemporalPartialDurationRecord(isolate, item),
      DirectHandle<JSTemporalDuration>());
  return ConstructRustWrappingType<JSTemporalDuration>(
      isolate, CONSTRUCTOR(duration), CONSTRUCTOR(duration),
      temporal_rs::Duration::from_partial_duration(partial));
}
References CONSTRUCTOR, v8::internal::duration, MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::microseconds, v8::internal::nanoseconds, NEW_TEMPORAL_INVALID_ARG_TYPE_ERROR, v8::base::internal::result, v8::internal::seconds, TEMPORAL_ENTER_FUNC, THROW_NEW_ERROR, and ToTemporalPartialDurationRecord().
Referenced by v8::internal::JSTemporalDuration::Add(), v8::internal::JSTemporalInstant::Add(), v8::internal::JSTemporalPlainTime::Add(), v8::internal::JSTemporalDuration::From(), v8::internal::JSTemporalDuration::Subtract(), v8::internal::JSTemporalInstant::Subtract(), and v8::internal::JSTemporalPlainTime::Subtract().
ToTemporalInstant()
MaybeDirectHandle<JSTemporalInstant> v8::internal::temporal::ToTemporalInstant (Isolate * isolate, DirectHandle< Object > item, const char * method_name)
Definition at line 1231 of file js-temporal-objects.cc.
                                                                          {
  TEMPORAL_ENTER_FUNC();
  // 1. If item is an Object, then
  // a. If item has an [[InitializedTemporalInstant]] or
  // [[InitializedTemporalZonedDateTime]] internal slot, then
  if (IsJSTemporalInstant(*item)) {
    auto instant = Cast<JSTemporalInstant>(item);
    auto ns = instant->instant()->raw()->epoch_nanoseconds();
    // i. Return !CreateTemporalInstant(item.[[EpochNanoseconds]]).
    return ConstructRustWrappingType<JSTemporalInstant>(
        isolate, CONSTRUCTOR(instant), CONSTRUCTOR(instant),
        temporal_rs::Instant::try_new(ns));
  }
  // c. Set item to ?ToPrimitive(item, STRING).
  DirectHandle<Object> item_prim;
  if (IsJSReceiver(*item)) {
    ASSIGN_RETURN_ON_EXCEPTION(
        isolate, item_prim,
        JSReceiver::ToPrimitive(isolate, Cast<JSReceiver>(item),
                                ToPrimitiveHint::kString));
  } else {
    item_prim = item;
  }
  if (!IsString(*item_prim)) {
    THROW_NEW_ERROR(isolate, NEW_TEMPORAL_INVALID_ARG_TYPE_ERROR());
  }
  DirectHandle<String> item_string = Cast<String>(item_prim);
  DirectHandle<JSTemporalInstant> result;
  auto rust_result =
      HandleStringEncodings<TemporalAllocatedResult<temporal_rs::Instant>>(
          isolate, item_string,
          [](std::string_view view)
              -> TemporalAllocatedResult<temporal_rs::Instant> {
            return temporal_rs::Instant::from_utf8(view);
          },
          [](std::u16string_view view)
              -> TemporalAllocatedResult<temporal_rs::Instant> {
            return temporal_rs::Instant::from_utf16(view);
          });
  return ConstructRustWrappingType<JSTemporalInstant>(
      isolate, CONSTRUCTOR(instant), CONSTRUCTOR(instant),
      std::move(rust_result));
}
References ASSIGN_RETURN_ON_EXCEPTION, CONSTRUCTOR, v8::internal::kString, NEW_TEMPORAL_INVALID_ARG_TYPE_ERROR, v8::base::internal::result, TEMPORAL_ENTER_FUNC, and THROW_NEW_ERROR.
Referenced by DifferenceTemporalInstant(), v8::internal::JSTemporalInstant::Equals(), and v8::internal::JSTemporalInstant::From().
ToTemporalOverflowHandleUndefined()
Maybe<temporal_rs::ArithmeticOverflow> v8::internal::temporal::ToTemporalOverflowHandleUndefined (Isolate * isolate, DirectHandle< Object > options, const char * method_name)
Definition at line 362 of file js-temporal-objects.cc.
                                                                             {
  // Default is "constrain"
  if (IsUndefined(*options))
    return Just(temporal_rs::ArithmeticOverflow(
        temporal_rs::ArithmeticOverflow::Constrain));
  if (IsJSReceiver(*options)) {
    // (GetOptionsObject) 3. Throw a TypeError exception.
    THROW_NEW_ERROR_RETURN_VALUE(isolate, NEW_TEMPORAL_INVALID_ARG_TYPE_ERROR(),
                                 Nothing<temporal_rs::ArithmeticOverflow>());
  }
  // 2. Return ? GetOption(options, "overflow", « String », « "constrain",
  // "reject" », "constrain").
  return GetStringOption<temporal_rs::ArithmeticOverflow>(
      isolate, Cast<JSReceiver>(options), "overflow", method_name,
      std::to_array<const std::string_view>({"constrain", "reject"}),
      std::to_array<temporal_rs::ArithmeticOverflow>(
          {temporal_rs::ArithmeticOverflow::Constrain,
           temporal_rs::ArithmeticOverflow::Reject}),
      temporal_rs::ArithmeticOverflow::Constrain);
}
References v8::Just(), NEW_TEMPORAL_INVALID_ARG_TYPE_ERROR, and THROW_NEW_ERROR_RETURN_VALUE.
Referenced by v8::internal::JSTemporalPlainTime::From().
ToTemporalPartialDurationRecord()
Maybe<temporal_rs::PartialDuration> v8::internal::temporal::ToTemporalPartialDurationRecord (Isolate * isolate, DirectHandle< Object > duration_like_obj)
Definition at line 965 of file js-temporal-objects.cc.
                                                              {
  Factory* factory = isolate->factory();
  // 1. If temporalDurationLike is not an Object, then
  if (!IsJSReceiver(*duration_like_obj)) {
    // a. Throw a TypeError exception.
    THROW_NEW_ERROR_RETURN_VALUE(isolate, NEW_TEMPORAL_INVALID_ARG_TYPE_ERROR(),
                                 Nothing<temporal_rs::PartialDuration>());
  }
  DirectHandle<JSReceiver> duration_like = Cast<JSReceiver>(duration_like_obj);
  // 2. Let result be a new partial Duration Record with each field set to
  // undefined.
  auto result = temporal_rs::PartialDuration{
      .years = std::nullopt,
      .months = std::nullopt,
      .weeks = std::nullopt,
      .days = std::nullopt,
      .hours = std::nullopt,
      .minutes = std::nullopt,
      .seconds = std::nullopt,
      .milliseconds = std::nullopt,
      .microseconds = std::nullopt,
      .nanoseconds = std::nullopt,
  };
  // Steps 3-14: get each field in alphabetical order
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, result.days,
      temporal::GetSingleDurationField(isolate, duration_like,
                                       factory->days_string()),
      Nothing<temporal_rs::PartialDuration>());
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, result.hours,
      temporal::GetSingleDurationField(isolate, duration_like,
                                       factory->hours_string()),
      Nothing<temporal_rs::PartialDuration>());
  std::optional<int64_t> us;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, us,
      temporal::GetSingleDurationField(isolate, duration_like,
                                       factory->microseconds_string()),
      Nothing<temporal_rs::PartialDuration>());
  if (us.has_value()) {
    // This will improve after https://github.com/boa-dev/temporal/issues/189
    result.microseconds = static_cast<double>(us.value());
  }
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, result.milliseconds,
      temporal::GetSingleDurationField(isolate, duration_like,
                                       factory->milliseconds_string()),
      Nothing<temporal_rs::PartialDuration>());
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, result.minutes,
      temporal::GetSingleDurationField(isolate, duration_like,
                                       factory->minutes_string()),
      Nothing<temporal_rs::PartialDuration>());
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, result.months,
      temporal::GetSingleDurationField(isolate, duration_like,
                                       factory->months_string()),
      Nothing<temporal_rs::PartialDuration>());
  std::optional<int64_t> ns;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, ns,
      temporal::GetSingleDurationField(isolate, duration_like,
                                       factory->nanoseconds_string()),
      Nothing<temporal_rs::PartialDuration>());
  if (ns.has_value()) {
    // This will improve after https://github.com/boa-dev/temporal/issues/189
    result.microseconds = static_cast<double>(ns.value());
  }
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, result.seconds,
      temporal::GetSingleDurationField(isolate, duration_like,
                                       factory->seconds_string()),
      Nothing<temporal_rs::PartialDuration>());
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, result.weeks,
      temporal::GetSingleDurationField(isolate, duration_like,
                                       factory->weeks_string()),
      Nothing<temporal_rs::PartialDuration>());
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, result.years,
      temporal::GetSingleDurationField(isolate, duration_like,
                                       factory->years_string()),
      Nothing<temporal_rs::PartialDuration>());
  return Just(result);
}
References v8::internal::Isolate::factory(), GetSingleDurationField(), v8::Just(), MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE, NEW_TEMPORAL_INVALID_ARG_TYPE_ERROR, v8::base::internal::result, and THROW_NEW_ERROR_RETURN_VALUE.
Referenced by ToTemporalDuration(), and v8::internal::JSTemporalDuration::With().
ToTemporalTime()
MaybeDirectHandle<JSTemporalPlainTime> v8::internal::temporal::ToTemporalTime (Isolate * isolate, DirectHandle< Object > item, std::optional< temporal_rs::ArithmeticOverflow > overflow, const char * method_name)
Definition at line 1284 of file js-temporal-objects.cc.
                             {
  TEMPORAL_ENTER_FUNC();
  // 2. If item is an Object, then
  if (IsJSReceiver(*item)) {
    auto record = temporal_rs::PartialTime{
        .hour = std::nullopt,
        .minute = std::nullopt,
        .second = std::nullopt,
        .millisecond = std::nullopt,
        .microsecond = std::nullopt,
        .nanosecond = std::nullopt,
    };
    // a. If item has an [[InitializedTemporalTime]] internal slot, then
    if (IsJSTemporalPlainTime(*item)) {
      // iii. Return !CreateTemporalTime(item.[[Time]]).
      record = GetTimeRecord(Cast<JSTemporalPlainTime>(item));
      // b. If item has an [[InitializedTemporalDateTime]] internal slot, then
    } else if (IsJSTemporalPlainDateTime(*item)) {
      // iii. Return ! CreateTemporalTime(item.[[ISODateTime]].[[Time]]).
      record = GetTimeRecord(Cast<JSTemporalPlainDateTime>(item));
      // c. If item has an [[InitializedTemporalZonedDateTime]] internal slot,
      // then
    } else if (IsJSTemporalZonedDateTime(*item)) {
      // i. Let isoDateTime be GetISODateTimeFor(item.[[TimeZone]],
      // item.[[EpochNanoseconds]]).
      record = GetTimeRecord(Cast<JSTemporalZonedDateTime>(item));
      // iv. Return !CreateTemporalTime(isoDateTime.[[Time]]).
    } else {
      // d. Let result be ?ToTemporalTimeRecord(item).
      DirectHandle<JSReceiver> item_recvr = Cast<JSReceiver>(item);
      MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
          isolate, record,
          temporal::ToTemporalTimeRecord(isolate, item_recvr, method_name),
          DirectHandle<JSTemporalPlainTime>());
      // RegulateTime/etc is handled by temporal_rs
      // caveat: https://github.com/boa-dev/temporal/issues/334
    }
    return ConstructRustWrappingType<JSTemporalPlainTime>(
        isolate, CONSTRUCTOR(plain_time), CONSTRUCTOR(plain_time),
        temporal_rs::PlainTime::from_partial(record, overflow));
  } else {
    // a. If item is not a String, throw a TypeError exception.
    if (!IsString(*item)) {
      THROW_NEW_ERROR(isolate, NEW_TEMPORAL_INVALID_ARG_TYPE_ERROR());
    }
    DirectHandle<String> str = Cast<String>(item);
    DirectHandle<JSTemporalPlainTime> result;
    auto rust_result =
        HandleStringEncodings<TemporalAllocatedResult<temporal_rs::PlainTime>>(
            isolate, str,
            [](std::string_view view)
                -> TemporalAllocatedResult<temporal_rs::PlainTime> {
              return temporal_rs::PlainTime::from_utf8(view);
            },
            [](std::u16string_view view)
                -> TemporalAllocatedResult<temporal_rs::PlainTime> {
              return temporal_rs::PlainTime::from_utf16(view);
            });
    return ConstructRustWrappingType<JSTemporalPlainTime>(
        isolate, CONSTRUCTOR(plain_time), CONSTRUCTOR(plain_time),
        std::move(rust_result));
  }
}
References CONSTRUCTOR, GetTimeRecord(), MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE, NEW_TEMPORAL_INVALID_ARG_TYPE_ERROR, v8::internal::overflow, v8::base::internal::result, TEMPORAL_ENTER_FUNC, THROW_NEW_ERROR, and ToTemporalTimeRecord().
Referenced by v8::internal::JSTemporalPlainTime::Compare(), DifferenceTemporalPlainTime(), v8::internal::JSTemporalPlainTime::From(), and v8::internal::JSTemporalPlainDate::ToPlainDateTime().
ToTemporalTimeRecord()
Maybe<temporal_rs::PartialTime> v8::internal::temporal::ToTemporalTimeRecord (Isolate * isolate, DirectHandle< JSReceiver > time_like, const char * method_name, Completeness completeness = kComplete)
Definition at line 1090 of file js-temporal-objects.cc.
                                                                    {
  TEMPORAL_ENTER_FUNC();
  Factory* factory = isolate->factory();
  // 2. If completeness is complete, then
  // a. Let result be a new TemporalTimeLike Record with each field set to 0.
  // 3. Else,
  // a. Let result be a new TemporalTimeLike Record with each field set to
  // unset.
  auto result = completeness == kPartial ? temporal_rs::PartialTime {
    .hour = std::nullopt,
    .minute = std::nullopt,
    .second = std::nullopt,
    .millisecond = std::nullopt,
    .microsecond = std::nullopt,
    .nanosecond = std::nullopt,
  } : temporal_rs::PartialTime {
    .hour = 0,
    .minute = 0,
    .second = 0,
    .millisecond = 0,
    .microsecond = 0,
    .nanosecond = 0,
  };
  bool any = false;
  // Steps 3-14: get each field in alphabetical order
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, result.hour,
      temporal::GetSingleTimeRecordField<uint8_t>(isolate, time_like,
                                                  factory->hour_string(), &any),
      Nothing<temporal_rs::PartialTime>());
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, result.microsecond,
      temporal::GetSingleTimeRecordField<uint16_t>(
          isolate, time_like, factory->microsecond_string(), &any),
      Nothing<temporal_rs::PartialTime>());
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, result.millisecond,
      temporal::GetSingleTimeRecordField<uint16_t>(
          isolate, time_like, factory->millisecond_string(), &any),
      Nothing<temporal_rs::PartialTime>());
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, result.minute,
      temporal::GetSingleTimeRecordField<uint8_t>(
          isolate, time_like, factory->minute_string(), &any),
      Nothing<temporal_rs::PartialTime>());
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, result.nanosecond,
      temporal::GetSingleTimeRecordField<uint16_t>(
          isolate, time_like, factory->nanosecond_string(), &any),
      Nothing<temporal_rs::PartialTime>());
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, result.second,
      temporal::GetSingleTimeRecordField<uint8_t>(
          isolate, time_like, factory->second_string(), &any),
      Nothing<temporal_rs::PartialTime>());
  if (!any) {
    THROW_NEW_ERROR_RETURN_VALUE(isolate, NEW_TEMPORAL_INVALID_ARG_TYPE_ERROR(),
                                 Nothing<temporal_rs::PartialTime>());
  }
  return Just(result);
}
References v8::internal::Isolate::factory(), v8::Just(), v8::internal::anonymous_namespace{js-temporal-objects.cc}::kPartial, MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE, NEW_TEMPORAL_INVALID_ARG_TYPE_ERROR, v8::base::internal::result, TEMPORAL_ENTER_FUNC, and THROW_NEW_ERROR_RETURN_VALUE.
Referenced by ToTemporalTime().
ToTemporalTimeZone()
V8_WARN_UNUSED_RESULT MaybeDirectHandle<JSReceiver> v8::internal::temporal::ToTemporalTimeZone (Isolate * isolate, DirectHandle< Object > temporal_time_zone_like, const char * method_name)
ToTemporalTimeZoneIdentifier()
Maybe<std::unique_ptr<temporal_rs::TimeZone> > v8::internal::temporal::ToTemporalTimeZoneIdentifier (Isolate * isolate, DirectHandle< Object > tz_like)
Definition at line 934 of file js-temporal-objects.cc.
                                                    {
  // 1. If temporalTimeZoneLike is an Object, then
  // a. If temporalTimeZoneLike has an [[InitializedTemporalZonedDateTime]]
  // internal slot, then
  if (IsJSTemporalZonedDateTime(*tz_like)) {
    // i. Return temporalTimeZoneLike.[[TimeZone]].
    // TODO(manishearth) we don't currently have a nice way to clone timezones
    // See https://github.com/boa-dev/temporal/pull/344 and
    // https://github.com/boa-dev/temporal/issues/330.
    THROW_NEW_ERROR_RETURN_VALUE(
        isolate, NEW_TEMPORAL_INVALID_ARG_TYPE_ERROR(),
        Nothing<std::unique_ptr<temporal_rs::TimeZone>>());
  }
  // 2. If temporalTimeZoneLike is not a String, throw a TypeError exception.
  if (!IsString(*tz_like)) {
    THROW_NEW_ERROR_RETURN_VALUE(
        isolate, NEW_TEMPORAL_INVALID_ARG_TYPE_ERROR(),
        Nothing<std::unique_ptr<temporal_rs::TimeZone>>());
  }
  DirectHandle<String> str = Cast<String>(tz_like);
  auto std_str = str->ToStdString();
  return ExtractRustResult(isolate,
                           temporal_rs::TimeZone::try_from_str(std_str));
}
References v8::internal::anonymous_namespace{js-temporal-objects.cc}::ExtractRustResult(), NEW_TEMPORAL_INVALID_ARG_TYPE_ERROR, v8::Nothing(), and THROW_NEW_ERROR_RETURN_VALUE.
Referenced by v8::internal::JSTemporalInstant::ToString().
Variable Documentation
kToStringAuto
constexpr temporal_rs::ToStringRoundingOptions v8::internal::temporal::kToStringAuto [constexpr]
Initial value:
=
    temporal_rs::ToStringRoundingOptions{
        .precision = temporal_rs::Precision{.is_minute = false,
                                            .precision = std::nullopt},
        .smallest_unit = std::nullopt,
        .rounding_mode = std::nullopt,
    }
Definition at line 777 of file js-temporal-objects.cc.
Referenced by v8::internal::JSTemporalDuration::ToJSON(), v8::internal::JSTemporalInstant::ToJSON(), v8::internal::JSTemporalPlainDateTime::ToJSON(), v8::internal::JSTemporalPlainTime::ToJSON(), v8::internal::JSTemporalDuration::ToLocaleString(), v8::internal::JSTemporalInstant::ToLocaleString(), v8::internal::JSTemporalPlainDateTime::ToLocaleString(), and v8::internal::JSTemporalPlainTime::ToLocaleString().