v8::internal::compiler::anonymous_namespace{code-generator.cc} Namespace Reference
Functions
DirectHandle< TrustedPodArray< InliningPosition > > CreateInliningPositions (OptimizedCompilationInfo *info, Isolate *isolate)
Function Documentation
CreateInliningPositions()
DirectHandle<TrustedPodArray<InliningPosition> > v8::internal::compiler::anonymous_namespace{code-generator.cc}::CreateInliningPositions (OptimizedCompilationInfo * info, Isolate * isolate)
Definition at line 970 of file code-generator.cc.
                                                      {
  const OptimizedCompilationInfo::InlinedFunctionList& inlined_functions =
      info->inlined_functions();
  DirectHandle<TrustedPodArray<InliningPosition>> inl_positions =
      TrustedPodArray<InliningPosition>::New(
          isolate, static_cast<int>(inlined_functions.size()));
  for (size_t i = 0; i < inlined_functions.size(); ++i) {
    inl_positions->set(static_cast<int>(i), inlined_functions[i].position);
  }
  return inl_positions;
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::CodeGenerator::info(), v8::internal::OptimizedCompilationInfo::inlined_functions(), v8::internal::compiler::CodeGenerator::isolate(), and v8::internal::TrustedPodArray< T >::New().
Referenced by v8::internal::compiler::CodeGenerator::GenerateDeoptimizationData().