v8::internal::anonymous_namespace{builtins-bigint.cc} Namespace Reference
Functions
MaybeHandle< BigInt > ThisBigIntValue (Isolate *isolate, Handle< Object > value, const char *caller)
Tagged< Object > BigIntToStringImpl (Handle< Object > receiver, Handle< Object > radix, Isolate *isolate, const char *builtin_name)
Function Documentation
BigIntToStringImpl()
Tagged<Object> v8::internal::anonymous_namespace{builtins-bigint.cc}::BigIntToStringImpl (Handle< Object > receiver, Handle< Object > radix, Isolate * isolate, const char * builtin_name)
Definition at line 97 of file builtins-bigint.cc.
                                                                              {
  // 1. Let x be ? thisBigIntValue(this value).
  DirectHandle<BigInt> x;
  ASSIGN_RETURN_FAILURE_ON_EXCEPTION(
      isolate, x, ThisBigIntValue(isolate, receiver, builtin_name));
  // 2. If radix is not present, let radixNumber be 10.
  // 3. Else if radix is undefined, let radixNumber be 10.
  int radix_number = 10;
  if (!IsUndefined(*radix, isolate)) {
    // 4. Else, let radixNumber be ? ToInteger(radix).
    double radix_double;
    MAYBE_ASSIGN_RETURN_FAILURE_ON_EXCEPTION(
        isolate, radix_double, Object::IntegerValue(isolate, radix));
    // 5. If radixNumber < 2 or radixNumber > 36, throw a RangeError exception.
    if (radix_double < 2 || radix_double > 36) {
      THROW_NEW_ERROR_RETURN_FAILURE(
          isolate, NewRangeError(MessageTemplate::kToRadixFormatRange));
    }
    radix_number = static_cast<int>(radix_double);
  }
  // Return the String representation of this Number value using the radix
  // specified by radixNumber.
  RETURN_RESULT_OR_FAILURE(isolate, BigInt::ToString(isolate, x, radix_number));
}
References ASSIGN_RETURN_FAILURE_ON_EXCEPTION, v8::Value::IntegerValue(), MAYBE_ASSIGN_RETURN_FAILURE_ON_EXCEPTION, RETURN_RESULT_OR_FAILURE, ThisBigIntValue(), THROW_NEW_ERROR_RETURN_FAILURE, and v8::internal::BigInt::ToString().
Referenced by v8::internal::BUILTIN().
ThisBigIntValue()
MaybeHandle<BigInt> v8::internal::anonymous_namespace{builtins-bigint.cc}::ThisBigIntValue (Isolate * isolate, Handle< Object > value, const char * caller)
Definition at line 78 of file builtins-bigint.cc.
                                                        {
  // 1. If Type(value) is BigInt, return value.
  if (IsBigInt(*value)) return Cast<BigInt>(value);
  // 2. If Type(value) is Object and value has a [[BigIntData]] internal slot:
  if (IsJSPrimitiveWrapper(*value)) {
    // 2a. Assert: value.[[BigIntData]] is a BigInt value.
    // 2b. Return value.[[BigIntData]].
    Tagged<Object> data = Cast<JSPrimitiveWrapper>(*value)->value();
    if (IsBigInt(data)) return handle(Cast<BigInt>(data), isolate);
  }
  // 3. Throw a TypeError exception.
  THROW_NEW_ERROR(
      isolate,
      NewTypeError(MessageTemplate::kNotGeneric,
                   isolate->factory()->NewStringFromAsciiChecked(caller),
                   isolate->factory()->BigInt_string()));
}
References v8::internal::Isolate::factory(), v8::internal::handle(), v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), THROW_NEW_ERROR, and v8::internal::value.
Referenced by BigIntToStringImpl(), and v8::internal::BUILTIN().