v8::internal::compiler::anonymous_namespace{representation-change.cc} Namespace Reference
Functions
bool IsWord (MachineRepresentation rep)
bool TypeCheckIsBigInt (TypeCheckKind type_check)
constexpr bool SupportsFpParamsInCLinkage ()
Function Documentation
IsWord()
bool v8::internal::compiler::anonymous_namespace{representation-change.cc}::IsWord (MachineRepresentation rep)
Definition at line 147 of file representation-change.cc.
                                       {
  return rep == MachineRepresentation::kWord8 ||
         rep == MachineRepresentation::kWord16 ||
         rep == MachineRepresentation::kWord32;
}
References v8::internal::kWord16, v8::internal::kWord32, and v8::internal::kWord8.
Referenced by v8::internal::compiler::RepresentationChanger::GetBitRepresentationFor(), v8::internal::compiler::RepresentationChanger::GetFloat32RepresentationFor(), v8::internal::compiler::RepresentationChanger::GetFloat64RepresentationFor(), v8::internal::compiler::RepresentationChanger::GetRepresentationFor(), v8::internal::compiler::RepresentationChanger::GetTaggedPointerRepresentationFor(), v8::internal::compiler::RepresentationChanger::GetTaggedRepresentationFor(), v8::internal::compiler::RepresentationChanger::GetTaggedSignedRepresentationFor(), and v8::internal::compiler::RepresentationChanger::GetWord64RepresentationFor().
SupportsFpParamsInCLinkage()
constexpr bool v8::internal::compiler::anonymous_namespace{representation-change.cc}::SupportsFpParamsInCLinkage () [constexpr]
Definition at line 158 of file representation-change.cc.
                                            {
#ifdef V8_ENABLE_FP_PARAMS_IN_C_LINKAGE
  return Is64();
#else
  return false;
#endif
}
References v8::internal::Is64().
Referenced by v8::internal::compiler::RepresentationChanger::Ieee754Fp64ToFp16RawBitsCode(), v8::internal::compiler::RepresentationChanger::Ieee754Fp64ToFp16RawBitsOperator(), and v8::internal::compiler::RepresentationChanger::InsertTruncateFloat64ToFloat16RawBitsFallback().
TypeCheckIsBigInt()
bool v8::internal::compiler::anonymous_namespace{representation-change.cc}::TypeCheckIsBigInt (TypeCheckKind type_check)
Definition at line 153 of file representation-change.cc.
                                                 {
  return type_check == TypeCheckKind::kBigInt ||
         type_check == TypeCheckKind::kBigInt64;
}
References v8::internal::compiler::kBigInt, and v8::internal::compiler::kBigInt64.
Referenced by v8::internal::compiler::RepresentationChanger::GetFloat64RepresentationFor(), v8::internal::compiler::RepresentationChanger::GetRepresentationFor(), v8::internal::compiler::RepresentationChanger::GetTaggedPointerRepresentationFor(), and v8::internal::compiler::RepresentationChanger::GetWord64RepresentationFor().