v8::internal::anonymous_namespace{read-only-serializer.cc} Namespace Reference
Classes
class ObjectPreProcessor
struct ReadOnlySegmentForSerialization
class EncodeRelocationsVisitor
class ReadOnlyHeapImageSerializer
Functions
ro::EncodedTagged Encode (Isolate *isolate, Tagged< HeapObject > o)
std::vector< ReadOnlyHeapImageSerializer::MemoryRegion > GetUnmappedRegions (Isolate *isolate)
Function Documentation
Encode()
ro::EncodedTagged v8::internal::anonymous_namespace{read-only-serializer.cc}::Encode (Isolate * isolate, Tagged< HeapObject > o)
Definition at line 189 of file read-only-serializer.cc.
                                                               {
  Address o_address = o.address();
  MemoryChunkMetadata* chunk = MemoryChunkMetadata::FromAddress(o_address);
  ReadOnlySpace* ro_space = isolate->read_only_heap()->read_only_space();
  int index = static_cast<int>(ro_space->IndexOf(chunk));
  uint32_t offset = static_cast<int>(chunk->Offset(o_address));
  DCHECK(IsAligned(offset, kTaggedSize));
  return ro::EncodedTagged(index, offset / kTaggedSize);
}
References v8::internal::Tagged< HeapObject >::address(), v8::internal::DCHECK(), v8::internal::MemoryChunkMetadata::FromAddress(), v8::internal::index, v8::internal::ReadOnlySpace::IndexOf(), IsAligned(), v8::internal::kTaggedSize, v8::internal::MemoryChunkMetadata::Offset(), v8::internal::Isolate::read_only_heap(), and v8::internal::ReadOnlyHeap::read_only_space().
Referenced by v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlyHeapImageSerializer::EmitReadOnlyRootsTable(), and v8::internal::anonymous_namespace{read-only-serializer.cc}::EncodeRelocationsVisitor::ProcessSlot().
GetUnmappedRegions()
std::vector<ReadOnlyHeapImageSerializer::MemoryRegion> v8::internal::anonymous_namespace{read-only-serializer.cc}::GetUnmappedRegions (Isolate * isolate)
Definition at line 447 of file read-only-serializer.cc.
                      {
#ifdef V8_STATIC_ROOTS
  // WasmNull's payload is aligned to the OS page and consists of
  // WasmNull::kPayloadSize bytes of unmapped memory. To avoid inflating the
  // snapshot size and accessing uninitialized and/or unmapped memory, the
  // serializer skips the padding bytes and the payload.
  ReadOnlyRoots ro_roots(isolate);
  Tagged<WasmNull> wasm_null = ro_roots.wasm_null();
  Tagged<HeapObject> wasm_null_padding = ro_roots.wasm_null_padding();
  CHECK(IsFreeSpace(wasm_null_padding));
  Address wasm_null_padding_start =
      wasm_null_padding.address() + sizeof(FreeSpace);
  std::vector<ReadOnlyHeapImageSerializer::MemoryRegion> unmapped;
  if (wasm_null.address() > wasm_null_padding_start) {
    unmapped.push_back({wasm_null_padding_start,
                        wasm_null.address() - wasm_null_padding_start});
  }
  unmapped.push_back({wasm_null->payload(), WasmNull::kPayloadSize});
  return unmapped;
#else
  return {};
#endif // V8_STATIC_ROOTS
}
References v8::internal::Tagged< HeapObject >::address(), and CHECK.
Referenced by v8::internal::ReadOnlySerializer::Serialize().