v8::internal::anonymous_namespace{concurrent-marking.cc} Namespace Reference
Functions
bool IsYoungObjectInLab (MainAllocator *new_space_allocator, NewLargeObjectSpace *new_lo_space, Tagged< HeapObject > heap_object)
Function Documentation
IsYoungObjectInLab()
bool v8::internal::anonymous_namespace{concurrent-marking.cc}::IsYoungObjectInLab (MainAllocator * new_space_allocator, NewLargeObjectSpace * new_lo_space, Tagged< HeapObject > heap_object) [inline]
Definition at line 500 of file concurrent-marking.cc.
                                                                  {
  // The order of the two loads is important.
  auto [new_space_top, new_space_limit] =
      new_space_allocator->GetOriginalTopAndLimit();
  Address new_large_object = new_lo_space->pending_object();
  Address addr = heap_object.address();
  return (new_space_top <= addr && addr < new_space_limit) ||
         addr == new_large_object;
}
References v8::internal::Tagged< HeapObject >::address(), v8::internal::MainAllocator::GetOriginalTopAndLimit(), and v8::internal::LargeObjectSpace::pending_object().
Referenced by v8::internal::ConcurrentMarking::RunMinorImpl().