v8::internal::anonymous_namespace{experimental.cc} Namespace Reference
Classes
struct CompilationResult
Functions
std::optional< CompilationResult > CompileImpl (Isolate *isolate, DirectHandle< IrRegExpData > re_data)
int32_t ExecRawImpl (Isolate *isolate, RegExp::CallOrigin call_origin, Tagged< TrustedByteArray > bytecode, Tagged< String > subject, int capture_count, int32_t *output_registers, int32_t output_register_count, int32_t subject_index)
Function Documentation
CompileImpl()
std::optional<CompilationResult> v8::internal::anonymous_namespace{experimental.cc}::CompileImpl (Isolate * isolate, DirectHandle< IrRegExpData > re_data)
Definition at line 79 of file experimental.cc.
                                                          {
  Zone zone(isolate->allocator(), ZONE_NAME);
  DirectHandle<String> source(re_data->source(), isolate);
  // Parse and compile the regexp source.
  RegExpCompileData parse_result;
  DCHECK(!isolate->has_exception());
  RegExpFlags flags = JSRegExp::AsRegExpFlags(re_data->flags());
  bool parse_success = RegExpParser::ParseRegExpFromHeapString(
      isolate, &zone, source, flags, &parse_result);
  if (!parse_success) {
    // The pattern was already parsed successfully during initialization, so
    // the only way parsing can fail now is because of stack overflow.
    DCHECK_EQ(parse_result.error, RegExpError::kStackOverflow);
    USE(RegExp::ThrowRegExpException(isolate, flags, source,
                                     parse_result.error));
    return std::nullopt;
  }
  ZoneList<RegExpInstruction> bytecode = ExperimentalRegExpCompiler::Compile(
      parse_result.tree, JSRegExp::AsRegExpFlags(re_data->flags()), &zone);
  CompilationResult result;
  result.bytecode = VectorToByteArray(isolate, bytecode.ToVector());
  result.capture_name_map =
      RegExp::CreateCaptureNameMap(isolate, parse_result.named_captures);
  return result;
}
References v8::internal::Isolate::allocator(), v8::internal::JSRegExp::AsRegExpFlags(), v8::internal::ExperimentalRegExpCompiler::Compile(), v8::internal::RegExp::CreateCaptureNameMap(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::RegExpCompileData::error, v8::internal::flags, v8::internal::Isolate::has_exception(), v8::internal::RegExpCompileData::named_captures, v8::internal::RegExpParser::ParseRegExpFromHeapString(), v8::base::internal::result, v8::internal::RegExp::ThrowRegExpException(), v8::internal::ZoneList< T >::ToVector(), v8::internal::RegExpCompileData::tree, USE, v8::internal::VectorToByteArray(), and ZONE_NAME.
Referenced by v8::internal::ExperimentalRegExp::Compile(), and v8::internal::ExperimentalRegExp::OneshotExecRaw().
ExecRawImpl()
int32_t v8::internal::anonymous_namespace{experimental.cc}::ExecRawImpl (Isolate * isolate, RegExp::CallOrigin call_origin, Tagged< TrustedByteArray > bytecode, Tagged< String > subject, int capture_count, int32_t * output_registers, int32_t output_register_count, int32_t subject_index)
Definition at line 150 of file experimental.cc.
                                                                          {
  DisallowGarbageCollection no_gc;
  // TODO(cbruni): remove once gcmole is fixed.
  DisableGCMole no_gc_mole;
  int register_count_per_match =
      JSRegExp::RegistersForCaptureCount(capture_count);
  int32_t result;
  DCHECK(subject->IsFlat());
  Zone zone(isolate->allocator(), ZONE_NAME);
  result = ExperimentalRegExpInterpreter::FindMatches(
      isolate, call_origin, bytecode, register_count_per_match, subject,
      subject_index, output_registers, output_register_count, &zone);
  return result;
}
References v8::internal::Isolate::allocator(), v8::internal::call_origin, v8::internal::DCHECK(), v8::internal::ExperimentalRegExpInterpreter::FindMatches(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::JSRegExp::RegistersForCaptureCount(), v8::base::internal::result, and ZONE_NAME.
Referenced by v8::internal::ExperimentalRegExp::ExecRaw(), and v8::internal::ExperimentalRegExp::OneshotExecRaw().