v8::internal::wasm::anonymous_namespace{wasm-result.cc} Namespace Reference
Functions
void VPrintFToString (std::string *str, size_t str_offset, const char *format, va_list args)
void PrintFToString (std::string *str, size_t str_offset, const char *format,...)
Function Documentation
PrintFToString()
void v8::internal::wasm::anonymous_namespace{wasm-result.cc}::PrintFToString (std::string * str, size_t str_offset, const char * format, ...)
Definition at line 41 of file wasm-result.cc.
                         {
  va_list args;
  va_start(args, format);
  VPrintFToString(str, str_offset, format, args);
  va_end(args);
}
References v8::base::args, v8::internal::format, and VPrintFToString().
Referenced by v8::internal::wasm::ErrorThrower::Format().
VPrintFToString()
void v8::internal::wasm::anonymous_namespace{wasm-result.cc}::VPrintFToString (std::string * str, size_t str_offset, const char * format, va_list args)
Definition at line 19 of file wasm-result.cc.
                                   {
  DCHECK_LE(str_offset, str->size());
  size_t len = str_offset + strlen(format);
  // Allocate increasingly large buffers until the message fits.
  for (;; len = base::bits::RoundUpToPowerOfTwo64(len + 1)) {
    DCHECK_GE(kMaxInt, len);
    str->resize(len);
    va_list args_copy;
    va_copy(args_copy, args);
    int written =
        base::VSNPrintF(base::Vector<char>(&str->front() + str_offset,
                                           static_cast<int>(len - str_offset)),
                        format, args_copy);
    va_end(args_copy);
    if (written < 0) continue; // not enough space.
    str->resize(str_offset + written);
    return;
  }
}
References v8::base::args, DCHECK_GE, DCHECK_LE, v8::internal::format, v8::internal::kMaxInt, v8::base::bits::RoundUpToPowerOfTwo64(), and v8::base::VSNPrintF().
Referenced by v8::internal::wasm::ErrorThrower::Format(), v8::internal::wasm::WasmError::FormatError(), and PrintFToString().