v8::internal::anonymous_namespace{compiler.cc}::anonymous_namespace{compiler.cc} Namespace Reference
Functions
ScriptCompiler::InMemoryCacheResult CategorizeLookupResult (const CompilationCacheScript::LookupResult &lookup_result)
Function Documentation
CategorizeLookupResult()
ScriptCompiler::InMemoryCacheResult v8::internal::anonymous_namespace{compiler.cc}::anonymous_namespace{compiler.cc}::CategorizeLookupResult (const CompilationCacheScript::LookupResult & lookup_result)
Definition at line 3896 of file compiler.cc.
                                                             {
  return !lookup_result.toplevel_sfi().is_null()
             ? ScriptCompiler::InMemoryCacheResult::kHit
         : !lookup_result.script().is_null()
             ? ScriptCompiler::InMemoryCacheResult::kPartial
             : ScriptCompiler::InMemoryCacheResult::kMiss;
}
References v8::ScriptCompiler::kHit, v8::ScriptCompiler::kMiss, v8::ScriptCompiler::kPartial, v8::internal::CompilationCacheScriptLookupResult::script(), and v8::internal::CompilationCacheScriptLookupResult::toplevel_sfi().
Referenced by v8::internal::anonymous_namespace{compiler.cc}::GetSharedFunctionInfoForScriptImpl(), and v8::internal::Compiler::GetSharedFunctionInfoForStreamedScript().