v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc} Namespace Reference
Classes
class AsyncCompilationResolver
class InstantiateModuleResultResolver
class InstantiateBytesResultResolver
class AsyncInstantiateCompileResultResolver
class WasmJSApiScope
Enumerations
enum CompilationMethod {
kSyncCompilation = 0
, kAsyncCompilation = 1
, kStreamingCompilation = 2
, kAsyncInstantiation = 3
,
kStreamingInstantiation = 4
 }
Functions
i::MaybeDirectHandle< i::JSReceiver > ImportsAsMaybeReceiver (Local< Value > ffi)
std::string ToString (const char *name)
std::string ToString (const i::DirectHandle< i::String > name)
template<typename Name >
std::optional< uint32_t > EnforceUint32 (Name argument_name, Local< v8::Value > v, Local< Context > context, ErrorThrower *thrower)
template<typename Name >
std::optional< uint64_t > EnforceBigIntUint64 (Name argument_name, Local< Value > v, Local< Context > context, ErrorThrower *thrower)
void RecordCompilationMethod (i::Isolate *isolate, CompilationMethod method)
CompileTimeImports ArgumentToCompileOptions (Local< Value > arg_value, i::Isolate *isolate, WasmEnabledFeatures enabled_features)
bool TransferPrototype (i::Isolate *isolate, i::DirectHandle< i::JSObject > destination, i::DirectHandle< i::JSReceiver > source)
template<typename Name >
std::optional< uint64_t > AddressValueToU64 (ErrorThrower *thrower, Local< Context > context, v8::Local< v8::Value > value, Name property_name, AddressType address_type)
std::optional< uint64_t > AddressValueToBoundedU64 (ErrorThrower *thrower, Local< Context > context, v8::Local< v8::Value > value, i::DirectHandle< i::String > property_name, AddressType address_type, uint64_t lower_bound, uint64_t upper_bound)
std::optional< std::optional< uint64_t > > GetOptionalAddressValue (ErrorThrower *thrower, Local< Context > context, Local< v8::Object > descriptor, Local< String > property, AddressType address_type, int64_t lower_bound, uint64_t upper_bound)
std::optional< uint64_t > GetInitialOrMinimumProperty (v8::Isolate *isolate, ErrorThrower *thrower, Local< Context > context, Local< v8::Object > descriptor, AddressType address_type, uint64_t upper_bound)
v8::Local< Value > AddressValueFromUnsigned (Isolate *isolate, i::wasm::AddressType type, unsigned value)
i::DirectHandle< i::HeapObject > DefaultReferenceValue (i::Isolate *isolate, i::wasm::ValueType type)
std::optional< AddressType > GetAddressType (Isolate *isolate, Local< Context > context, Local< v8::Object > descriptor, ErrorThrower *thrower)
bool ToI32 (Local< v8::Value > value, Local< Context > context, int32_t *i32_value)
bool ToI64 (Local< v8::Value > value, Local< Context > context, int64_t *i64_value)
bool ToF32 (Local< v8::Value > value, Local< Context > context, float *f32_value)
bool ToF64 (Local< v8::Value > value, Local< Context > context, double *f64_value)
uint32_t GetIterableLength (i::Isolate *isolate, Local< Context > context, Local< Object > iterable)
uint32_t GetEncodedSize (i::DirectHandle< i::WasmTagObject > tag_object)
V8_WARN_UNUSED_RESULT bool EncodeExceptionValues (v8::Isolate *isolate, i::DirectHandle< i::PodArray< i::wasm::ValueType >> signature, i::DirectHandle< i::WasmTagObject > tag_object, const Local< Value > &arg, ErrorThrower *thrower, i::DirectHandle< i::FixedArray > values_out)
V8_WARN_UNUSED_RESULT bool WasmObjectToJSReturnValue (v8::ReturnValue< v8::Value > &return_value, i::DirectHandle< i::Object > value, i::wasm::ValueType type, i::Isolate *isolate, ErrorThrower *thrower)
Enumeration Type Documentation
CompilationMethod
enum v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::CompilationMethod
Enumerator
kSyncCompilation
kAsyncCompilation
kStreamingCompilation
kAsyncInstantiation
kStreamingInstantiation
Definition at line 565 of file wasm-js.cc.
                       {
  kSyncCompilation = 0,
  kAsyncCompilation = 1,
  kStreamingCompilation = 2,
  kAsyncInstantiation = 3,
  kStreamingInstantiation = 4,
};
Function Documentation
AddressValueFromUnsigned()
v8::Local<Value> v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::AddressValueFromUnsigned (Isolate * isolate, i::wasm::AddressType type, unsigned value)
Definition at line 1375 of file wasm-js.cc.
                                                          {
  return type == i::wasm::AddressType::kI64
             ? BigInt::NewFromUnsigned(isolate, value).As<Value>()
             : Integer::NewFromUnsigned(isolate, value).As<Value>();
}
References v8::Integer::NewFromUnsigned(), v8::BigInt::NewFromUnsigned(), v8::internal::tracing::type, and v8::internal::value.
Referenced by v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryGrowImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableGetLengthImpl(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableGrowImpl().
AddressValueToBoundedU64()
std::optional<uint64_t> v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::AddressValueToBoundedU64 (ErrorThrower * thrower, Local< Context > context, v8::Local< v8::Value > value, i::DirectHandle< i::String > property_name, AddressType address_type, uint64_t lower_bound, uint64_t upper_bound)
Definition at line 1277 of file wasm-js.cc.
                                                {
  std::optional<uint64_t> maybe_address_value =
      AddressValueToU64(thrower, context, value, property_name, address_type);
  if (!maybe_address_value) return std::nullopt;
  uint64_t address_value = *maybe_address_value;
  if (address_value < lower_bound) {
    thrower->RangeError(
        "Property '%s': value %" PRIu64 " is below the lower bound %" PRIx64,
        property_name->ToCString().get(), address_value, lower_bound);
    return std::nullopt;
  }
  if (address_value > upper_bound) {
    thrower->RangeError(
        "Property '%s': value %" PRIu64 " is above the upper bound %" PRIu64,
        property_name->ToCString().get(), address_value, upper_bound);
    return std::nullopt;
  }
  return address_value;
}
References AddressValueToU64(), and v8::internal::value.
Referenced by GetOptionalAddressValue().
AddressValueToU64()
template<typename Name >
std::optional<uint64_t> v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::AddressValueToU64 (ErrorThrower * thrower, Local< Context > context, v8::Local< v8::Value > value, Name property_name, AddressType address_type)
Definition at line 1260 of file wasm-js.cc.
                                                                    {
  switch (address_type) {
    case AddressType::kI32:
      return EnforceUint32(property_name, value, context, thrower);
    case AddressType::kI64:
      return EnforceBigIntUint64(property_name, value, context, thrower);
  }
  // The enum value is coming from inside the sandbox and while the switch is
  // exhaustive, it's not guaranteed that value is one of the declared values.
  SBXCHECK(false);
}
References EnforceBigIntUint64(), EnforceUint32(), SBXCHECK, and v8::internal::value.
Referenced by AddressValueToBoundedU64(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryGrowImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableGetImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableGrowImpl(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableSetImpl().
ArgumentToCompileOptions()
CompileTimeImports v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::ArgumentToCompileOptions (Local< Value > arg_value, i::Isolate * isolate, WasmEnabledFeatures enabled_features)
Definition at line 577 of file wasm-js.cc.
                                          {
  CompileTimeImports result;
  if (base::FPU::GetFlushDenormals()) {
    result.Add(CompileTimeImport::kDisableDenormalFloats);
  }
  if (!enabled_features.has_imported_strings()) return result;
  i::DirectHandle<i::Object> arg = Utils::OpenDirectHandle(*arg_value);
  if (!i::IsJSReceiver(*arg)) return result;
  i::DirectHandle<i::JSReceiver> receiver = i::Cast<i::JSReceiver>(arg);
  // ==================== Builtins ====================
  i::DirectHandle<i::JSAny> builtins;
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(isolate, builtins,
                                   i::Cast<i::JSAny>(i::JSReceiver::GetProperty(
                                       isolate, receiver, "builtins")),
                                   {});
  if (i::IsJSReceiver(*builtins)) {
    i::DirectHandle<i::Object> length_obj;
    ASSIGN_RETURN_ON_EXCEPTION_VALUE(
        isolate, length_obj,
        i::Object::GetLengthFromArrayLike(isolate,
                                          i::Cast<i::JSReceiver>(builtins)),
        {});
    double raw_length = i::Object::NumberValue(*length_obj);
    // Technically we should probably iterate up to 2^53-1 if {length_obj} says
    // so, but lengths above 2^32 probably don't happen in practice (and would
    // be very slow if they do), so just use a saturating to-uint32 conversion
    // for simplicity.
    uint32_t len = raw_length >= i::kMaxUInt32
                       ? i::kMaxUInt32
                       : static_cast<uint32_t>(raw_length);
    for (uint32_t i = 0; i < len; i++) {
      i::LookupIterator it(isolate, builtins, i);
      Maybe<bool> maybe_found = i::JSReceiver::HasProperty(&it);
      MAYBE_RETURN(maybe_found, {});
      if (!maybe_found.FromJust()) continue;
      i::DirectHandle<i::Object> value;
      ASSIGN_RETURN_ON_EXCEPTION_VALUE(isolate, value,
                                       i::Object::GetProperty(&it), {});
      if (i::IsString(*value)) {
        i::Tagged<i::String> builtin = i::Cast<i::String>(*value);
        // TODO(jkummerow): We could make other string comparisons to known
        // constants in this file more efficient by migrating them to this
        // style (rather than `...->StringEquals(v8_str(...))`).
        if (builtin->IsEqualTo(base::CStrVector("js-string"))) {
          result.Add(CompileTimeImport::kJsString);
          continue;
        }
        if (enabled_features.has_imported_strings_utf8()) {
          if (builtin->IsEqualTo(base::CStrVector("text-encoder"))) {
            result.Add(CompileTimeImport::kTextEncoder);
            continue;
          }
          if (builtin->IsEqualTo(base::CStrVector("text-decoder"))) {
            result.Add(CompileTimeImport::kTextDecoder);
            continue;
          }
        }
      }
    }
  }
  // ==================== String constants ====================
  i::DirectHandle<i::String> importedStringConstants =
      isolate->factory()->InternalizeUtf8String("importedStringConstants");
  if (i::JSReceiver::HasProperty(isolate, receiver, importedStringConstants)
          .FromMaybe(false)) {
    i::DirectHandle<i::Object> constants_value;
    ASSIGN_RETURN_ON_EXCEPTION_VALUE(
        isolate, constants_value,
        i::JSReceiver::GetProperty(isolate, receiver, importedStringConstants),
        {});
    if (i::IsString(*constants_value)) {
      i::ToUtf8Lossy(isolate, i::Cast<i::String>(constants_value),
                     result.constants_module());
      result.Add(CompileTimeImport::kStringConstants);
    }
  }
  return result;
}
References ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::base::CStrVector(), v8::internal::Isolate::factory(), v8::Maybe< T >::FromJust(), v8::base::FPU::GetFlushDenormals(), v8::internal::Object::GetLengthFromArrayLike(), v8::internal::JSReceiver::GetProperty(), v8::internal::Object::GetProperty(), v8::internal::JSReceiver::HasProperty(), v8::internal::Factory::InternalizeUtf8String(), v8::internal::kMaxUInt32, MAYBE_RETURN, v8::internal::Object::NumberValue(), v8::Utils::OpenDirectHandle(), v8::base::internal::result, v8::internal::ToUtf8Lossy(), and v8::internal::value.
Referenced by v8::anonymous_namespace{wasm-js.cc}::StartAsyncCompilationWithResolver(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyCompileImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyInstantiateImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyModuleImpl(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyValidateImpl().
DefaultReferenceValue()
i::DirectHandle<i::HeapObject> v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::DefaultReferenceValue (i::Isolate * isolate, i::wasm::ValueType type)
Definition at line 1383 of file wasm-js.cc.
                                                                          {
  DCHECK(type.is_object_reference());
  // Use undefined for JS type (externref) but null for wasm types as wasm does
  // not know undefined.
  if (type.heap_representation() == i::wasm::HeapType::kExtern) {
    return isolate->factory()->undefined_value();
  } else if (!type.use_wasm_null()) {
    return isolate->factory()->null_value();
  }
  return isolate->factory()->wasm_null();
}
References DCHECK, v8::internal::Isolate::factory(), and v8::internal::tracing::type.
Referenced by v8::anonymous_namespace{wasm-js.cc}::WebAssemblyGlobalImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableGrowImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableImpl(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableSetImpl().
EncodeExceptionValues()
V8_WARN_UNUSED_RESULT bool v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::EncodeExceptionValues (v8::Isolate * isolate, i::DirectHandle< i::PodArray< i::wasm::ValueType >> signature, i::DirectHandle< i::WasmTagObject > tag_object, const Local< Value > & arg, ErrorThrower * thrower, i::DirectHandle< i::FixedArray > values_out)
Definition at line 2051 of file wasm-js.cc.
                                                                  {
  Local<Context> context = isolate->GetCurrentContext();
  uint32_t index = 0;
  if (!arg->IsObject()) {
    thrower->TypeError("Exception values must be an iterable object");
    return false;
  }
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(isolate);
  auto values = arg.As<Object>();
  uint32_t length = GetIterableLength(i_isolate, context, values);
  if (length == i::kMaxUInt32) {
    thrower->TypeError("Exception values argument has no length");
    return false;
  }
  if (length != static_cast<uint32_t>(signature->length())) {
    thrower->TypeError(
        "Number of exception values does not match signature length");
    return false;
  }
  for (int i = 0; i < signature->length(); ++i) {
    Local<Value> value;
    if (!values->Get(context, i).ToLocal(&value)) return false;
    i::wasm::ValueType type = signature->get(i);
    switch (type.kind()) {
      case i::wasm::kI32: {
        int32_t i32 = 0;
        if (!ToI32(value, context, &i32)) return false;
        i::EncodeI32ExceptionValue(values_out, &index, i32);
        break;
      }
      case i::wasm::kI64: {
        int64_t i64 = 0;
        if (!ToI64(value, context, &i64)) return false;
        i::EncodeI64ExceptionValue(values_out, &index, i64);
        break;
      }
      case i::wasm::kF32: {
        float f32 = 0;
        if (!ToF32(value, context, &f32)) return false;
        int32_t i32 = base::bit_cast<int32_t>(f32);
        i::EncodeI32ExceptionValue(values_out, &index, i32);
        break;
      }
      case i::wasm::kF64: {
        double f64 = 0;
        if (!ToF64(value, context, &f64)) return false;
        int64_t i64 = base::bit_cast<int64_t>(f64);
        i::EncodeI64ExceptionValue(values_out, &index, i64);
        break;
      }
      case i::wasm::kRef:
      case i::wasm::kRefNull: {
        const char* error_message;
        i::DirectHandle<i::Object> value_handle =
            Utils::OpenDirectHandle(*value);
        i::wasm::CanonicalValueType canonical_type = i::wasm::kWasmBottom;
        if (type.has_index()) {
          // Canonicalize the type using the tag's original module.
          // Indexed types are guaranteed to come from an instance.
          DCHECK(tag_object->has_trusted_data());
          i::Tagged<i::WasmTrustedInstanceData> wtid =
              tag_object->trusted_data(i_isolate);
          const i::wasm::WasmModule* module = wtid->module();
          canonical_type =
              type.Canonicalize(module->canonical_type_id(type.ref_index()));
        } else {
          canonical_type = i::wasm::CanonicalValueType{type};
        }
        if (!i::wasm::JSToWasmObject(i_isolate, value_handle, canonical_type,
                                     &error_message)
                 .ToHandle(&value_handle)) {
          thrower->TypeError("%s", error_message);
          return false;
        }
        values_out->set(index++, *value_handle);
        break;
      }
      case i::wasm::kS128:
        thrower->TypeError("Invalid type v128");
        return false;
      case i::wasm::kI8:
      case i::wasm::kI16:
      case i::wasm::kF16:
      case i::wasm::kVoid:
      case i::wasm::kTop:
      case i::wasm::kBottom:
        UNREACHABLE();
    }
  }
  return true;
}
References v8::Local< T >::As(), DCHECK, v8::internal::EncodeI32ExceptionValue(), v8::internal::EncodeI64ExceptionValue(), v8::Isolate::GetCurrentContext(), GetIterableLength(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::wasm::JSToWasmObject(), v8::internal::kMaxUInt32, v8::internal::wasm::kWasmBottom, v8::internal::length, v8::Utils::OpenDirectHandle(), ToF32(), ToF64(), v8::anonymous_namespace{api.cc}::ToHandle(), ToI32(), ToI64(), v8::internal::tracing::type, UNREACHABLE, and v8::internal::value.
Referenced by v8::anonymous_namespace{wasm-js.cc}::WebAssemblyExceptionImpl().
EnforceBigIntUint64()
template<typename Name >
std::optional<uint64_t> v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::EnforceBigIntUint64 (Name argument_name, Local< Value > v, Local< Context > context, ErrorThrower * thrower)
Definition at line 541 of file wasm-js.cc.
                                                                   {
  // Use the internal API, as v8::Value::ToBigInt clears exceptions.
  i::DirectHandle<i::BigInt> bigint;
  i::Isolate* i_isolate = i::Isolate::Current();
  if (!i::BigInt::FromObject(i_isolate, Utils::OpenDirectHandle(*v))
           .ToHandle(&bigint)) {
    return std::nullopt;
  }
  bool lossless;
  uint64_t result = bigint->AsUint64(&lossless);
  if (!lossless) {
    thrower->TypeError("%s must be in u64 range",
                       ToString(argument_name).c_str());
    return std::nullopt;
  }
  return result;
}
References v8::internal::Isolate::Current(), v8::Utils::OpenDirectHandle(), v8::base::internal::result, v8::anonymous_namespace{api.cc}::ToHandle(), and ToString().
Referenced by AddressValueToU64().
EnforceUint32()
template<typename Name >
std::optional<uint32_t> v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::EnforceUint32 (Name argument_name, Local< v8::Value > v, Local< Context > context, ErrorThrower * thrower)
Definition at line 511 of file wasm-js.cc.
                                                             {
  double double_number;
  if (!v->NumberValue(context).To(&double_number)) {
    thrower->TypeError("%s must be convertible to a number",
                       ToString(argument_name).c_str());
    return std::nullopt;
  }
  if (!std::isfinite(double_number)) {
    thrower->TypeError("%s must be convertible to a valid number",
                       ToString(argument_name).c_str());
    return std::nullopt;
  }
  if (double_number < 0) {
    thrower->TypeError("%s must be non-negative",
                       ToString(argument_name).c_str());
    return std::nullopt;
  }
  if (double_number > std::numeric_limits<uint32_t>::max()) {
    thrower->TypeError("%s must be in the unsigned long range",
                       ToString(argument_name).c_str());
    return std::nullopt;
  }
  return static_cast<uint32_t>(double_number);
}
References v8::Value::NumberValue(), and ToString().
Referenced by AddressValueToU64(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyExceptionGetArgImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryMapDescriptorImpl(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryMapDescriptorMapImpl().
GetAddressType()
std::optional<AddressType> v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::GetAddressType (Isolate * isolate, Local< Context > context, Local< v8::Object > descriptor, ErrorThrower * thrower)
Definition at line 1397 of file wasm-js.cc.
                                                                 {
  v8::Local<v8::Value> address_value;
  if (!descriptor->Get(context, v8_str(isolate, "address"))
           .ToLocal(&address_value)) {
    return std::nullopt;
  }
  if (address_value->IsUndefined()) return AddressType::kI32;
  i::DirectHandle<i::String> address;
  if (!i::Object::ToString(reinterpret_cast<i::Isolate*>(isolate),
                           Utils::OpenDirectHandle(*address_value))
           .ToHandle(&address)) {
    return std::nullopt;
  }
  if (address->IsEqualTo(base::CStrVector("i64"))) return AddressType::kI64;
  if (address->IsEqualTo(base::CStrVector("i32"))) return AddressType::kI32;
  thrower->TypeError("Unknown address type '%s'; pass 'i32' or 'i64'",
                     address->ToCString().get());
  return std::nullopt;
}
References v8::base::CStrVector(), v8::Object::Get(), v8::Value::IsUndefined(), v8::Utils::OpenDirectHandle(), v8::anonymous_namespace{api.cc}::ToHandle(), ToString(), and v8::anonymous_namespace{wasm-js.cc}::v8_str().
Referenced by v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryImpl(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableImpl().
GetEncodedSize()
uint32_t v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::GetEncodedSize (i::DirectHandle< i::WasmTagObject > tag_object)
Definition at line 2043 of file wasm-js.cc.
                                                                  {
  auto serialized_sig = tag_object->serialized_signature();
  i::wasm::WasmTagSig sig{
      0, static_cast<size_t>(serialized_sig->length()),
      reinterpret_cast<i::wasm::ValueType*>(serialized_sig->begin())};
  return i::WasmExceptionPackage::GetEncodedSize(&sig);
}
References v8::internal::WasmExceptionPackage::GetEncodedSize(), and v8::internal::sig.
Referenced by v8::anonymous_namespace{wasm-js.cc}::WebAssemblyExceptionImpl().
GetInitialOrMinimumProperty()
std::optional<uint64_t> v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::GetInitialOrMinimumProperty (v8::Isolate * isolate, ErrorThrower * thrower, Local< Context > context, Local< v8::Object > descriptor, AddressType address_type, uint64_t upper_bound)
Definition at line 1337 of file wasm-js.cc.
                          {
  auto maybe_maybe_initial = GetOptionalAddressValue(
      thrower, context, descriptor, v8_str(isolate, "initial"), address_type, 0,
      upper_bound);
  if (!maybe_maybe_initial) return std::nullopt;
  std::optional<uint64_t> maybe_initial = *maybe_maybe_initial;
  auto enabled_features =
      WasmEnabledFeatures::FromIsolate(reinterpret_cast<i::Isolate*>(isolate));
  if (enabled_features.has_type_reflection()) {
    auto maybe_maybe_minimum = GetOptionalAddressValue(
        thrower, context, descriptor, v8_str(isolate, "minimum"), address_type,
        0, upper_bound);
    if (!maybe_maybe_minimum) return std::nullopt;
    std::optional<uint64_t> maybe_minimum = *maybe_maybe_minimum;
    if (maybe_initial && maybe_minimum) {
      thrower->TypeError(
          "The properties 'initial' and 'minimum' are not allowed at the same "
          "time");
      return std::nullopt;
    }
    if (maybe_minimum) {
      // Only 'minimum' exists, so we use 'minimum' as 'initial'.
      return *maybe_minimum;
    }
  }
  if (!maybe_initial) {
    // TODO(aseemgarg): update error message when the spec issue is resolved.
    thrower->TypeError("Property 'initial' is required");
    return std::nullopt;
  }
  return *maybe_initial;
}
References GetOptionalAddressValue(), and v8::anonymous_namespace{wasm-js.cc}::v8_str().
Referenced by v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryImpl(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableImpl().
GetIterableLength()
uint32_t v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::GetIterableLength (i::Isolate * isolate, Local< Context > context, Local< Object > iterable)
Definition at line 1959 of file wasm-js.cc.
                                                   {
  Local<String> length = Utils::ToLocal(isolate->factory()->length_string());
  MaybeLocal<Value> property = iterable->Get(context, length);
  if (property.IsEmpty()) return i::kMaxUInt32;
  MaybeLocal<Uint32> number = property.ToLocalChecked()->ToArrayIndex(context);
  if (number.IsEmpty()) return i::kMaxUInt32;
  DCHECK_NE(i::kMaxUInt32, number.ToLocalChecked()->Value());
  return number.ToLocalChecked()->Value();
}
References DCHECK_NE, v8::internal::Isolate::factory(), v8::Object::Get(), v8::MaybeLocal< T >::IsEmpty(), v8::internal::kMaxUInt32, v8::internal::length, and v8::MaybeLocal< T >::ToLocalChecked().
Referenced by EncodeExceptionValues(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyFunction(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTagImpl().
GetOptionalAddressValue()
std::optional<std::optional<uint64_t> > v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::GetOptionalAddressValue (ErrorThrower * thrower, Local< Context > context, Local< v8::Object > descriptor, Local< String > property, AddressType address_type, int64_t lower_bound, uint64_t upper_bound)
Definition at line 1306 of file wasm-js.cc.
                          {
  v8::Local<v8::Value> value;
  if (!descriptor->Get(context, property).ToLocal(&value)) {
    return std::nullopt;
  }
  // Web IDL: dictionary presence
  // https://heycam.github.io/webidl/#dfn-present
  if (value->IsUndefined()) {
    // No exception, but no value either.
    return std::optional<uint64_t>{};
  }
  i::DirectHandle<i::String> property_name =
      v8::Utils::OpenDirectHandle(*property);
  std::optional<uint64_t> maybe_address_value =
      AddressValueToBoundedU64(thrower, context, value, property_name,
                               address_type, lower_bound, upper_bound);
  if (!maybe_address_value) return std::nullopt;
  return *maybe_address_value;
}
References AddressValueToBoundedU64(), v8::Object::Get(), v8::Utils::OpenDirectHandle(), v8::MaybeLocal< T >::ToLocal(), and v8::internal::value.
Referenced by GetInitialOrMinimumProperty(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryImpl(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableImpl().
ImportsAsMaybeReceiver()
i::MaybeDirectHandle<i::JSReceiver> v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::ImportsAsMaybeReceiver (Local< Value > ffi)
Definition at line 263 of file wasm-js.cc.
                                                                         {
  if (ffi->IsUndefined()) return {};
  Local<Object> obj = Local<Object>::Cast(ffi);
  return i::Cast<i::JSReceiver>(v8::Utils::OpenDirectHandle(*obj));
}
References v8::Local< T >::Cast(), and v8::Utils::OpenDirectHandle().
Referenced by v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::AsyncInstantiateCompileResultResolver::OnCompilationSucceeded(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyInstanceImpl(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyInstantiateImpl().
RecordCompilationMethod()
void v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::RecordCompilationMethod (i::Isolate * isolate, CompilationMethod method)
Definition at line 573 of file wasm-js.cc.
                                                                          {
  isolate->counters()->wasm_compilation_method()->AddSample(method);
}
References v8::internal::Isolate::counters().
Referenced by v8::anonymous_namespace{wasm-js.cc}::WebAssemblyCompileImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyCompileStreaming(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyInstanceImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyInstantiateStreaming(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyModuleImpl().
ToF32()
bool v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::ToF32 (Local< v8::Value > value, Local< Context > context, float * f32_value)
Definition at line 1785 of file wasm-js.cc.
                                                                           {
  if (!value->IsUndefined()) {
    double f64_value = 0;
    v8::Local<v8::Number> number_value;
    if (!value->ToNumber(context).ToLocal(&number_value)) return false;
    if (!number_value->NumberValue(context).To(&f64_value)) return false;
    *f32_value = i::DoubleToFloat32(f64_value);
  }
  return true;
}
References v8::internal::DoubleToFloat32(), and v8::internal::value.
Referenced by EncodeExceptionValues(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyGlobalImpl().
ToF64()
bool v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::ToF64 (Local< v8::Value > value, Local< Context > context, double * f64_value)
Definition at line 1796 of file wasm-js.cc.
                                                                            {
  if (!value->IsUndefined()) {
    v8::Local<v8::Number> number_value;
    if (!value->ToNumber(context).ToLocal(&number_value)) return false;
    if (!number_value->NumberValue(context).To(f64_value)) return false;
  }
  return true;
}
References v8::internal::value.
Referenced by EncodeExceptionValues(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyGlobalImpl().
ToI32()
bool v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::ToI32 (Local< v8::Value > value, Local< Context > context, int32_t * i32_value)
Definition at line 1767 of file wasm-js.cc.
                                                                             {
  if (!value->IsUndefined()) {
    v8::Local<v8::Int32> int32_value;
    if (!value->ToInt32(context).ToLocal(&int32_value)) return false;
    if (!int32_value->Int32Value(context).To(i32_value)) return false;
  }
  return true;
}
References v8::internal::value.
Referenced by EncodeExceptionValues(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyGlobalImpl().
ToI64()
bool v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::ToI64 (Local< v8::Value > value, Local< Context > context, int64_t * i64_value)
Definition at line 1776 of file wasm-js.cc.
                                                                             {
  if (!value->IsUndefined()) {
    v8::Local<v8::BigInt> bigint_value;
    if (!value->ToBigInt(context).ToLocal(&bigint_value)) return false;
    *i64_value = bigint_value->Int64Value();
  }
  return true;
}
References v8::internal::value.
Referenced by EncodeExceptionValues(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyGlobalImpl().
ToString() [1/2]
std::string v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::ToString (const char * name)
Definition at line 502 of file wasm-js.cc.
{ return std::string(name); }
References name, and v8::internal::string.
ToString() [2/2]
std::string v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::ToString (const i::DirectHandle< i::String > name)
Definition at line 504 of file wasm-js.cc.
                                                      {
  return std::string("Property '") + name->ToStdString() + "'";
}
References name, and v8::internal::string.
TransferPrototype()
bool v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::TransferPrototype (i::Isolate * isolate, i::DirectHandle< i::JSObject > destination, i::DirectHandle< i::JSReceiver > source)
Definition at line 936 of file wasm-js.cc.
                                                          {
  i::MaybeDirectHandle<i::HeapObject> maybe_prototype =
      i::JSObject::GetPrototype(isolate, source);
  i::DirectHandle<i::HeapObject> prototype;
  if (maybe_prototype.ToHandle(&prototype)) {
    Maybe<bool> result = i::JSObject::SetPrototype(
        isolate, destination, prototype,
        /*from_javascript=*/false, internal::kThrowOnError);
    if (!result.FromJust()) {
      DCHECK(isolate->has_exception());
      return false;
    }
  }
  return true;
}
References DCHECK, v8::internal::Isolate::has_exception(), v8::internal::kThrowOnError, v8::internal::prototype, v8::base::internal::result, v8::internal::JSObject::SetPrototype(), and v8::internal::MaybeDirectHandle< T >::ToHandle().
Referenced by v8::anonymous_namespace{wasm-js.cc}::WebAssemblyGlobalImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyInstanceImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryMapDescriptorImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyModuleImpl(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableImpl().
WasmObjectToJSReturnValue()
V8_WARN_UNUSED_RESULT bool v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::WasmObjectToJSReturnValue (v8::ReturnValue< v8::Value > & return_value, i::DirectHandle< i::Object > value, i::wasm::ValueType type, i::Isolate * isolate, ErrorThrower * thrower)
Definition at line 2641 of file wasm-js.cc.
                                                                   {
  switch (type.heap_type().representation()) {
    case internal::wasm::HeapType::kStringViewWtf8:
      thrower->TypeError("%s", "stringview_wtf8 has no JS representation");
      return false;
    case internal::wasm::HeapType::kStringViewWtf16:
      thrower->TypeError("%s", "stringview_wtf16 has no JS representation");
      return false;
    case internal::wasm::HeapType::kStringViewIter:
      thrower->TypeError("%s", "stringview_iter has no JS representation");
      return false;
    case internal::wasm::HeapType::kExn:
    case internal::wasm::HeapType::kNoExn:
    case internal::wasm::HeapType::kCont:
    case internal::wasm::HeapType::kNoCont:
      thrower->TypeError("invalid type %s", type.name().c_str());
      return false;
    default:
      return_value.Set(Utils::ToLocal(i::wasm::WasmToJSObject(isolate, value)));
      return true;
  }
}
References v8::internal::wasm::HeapType::kCont, v8::internal::wasm::HeapType::kExn, v8::internal::wasm::HeapType::kNoCont, v8::internal::wasm::HeapType::kNoExn, v8::internal::wasm::HeapType::kStringViewIter, v8::internal::wasm::HeapType::kStringViewWtf16, v8::internal::wasm::HeapType::kStringViewWtf8, v8::ReturnValue< T >::Set(), v8::internal::tracing::type, v8::internal::value, and v8::internal::wasm::WasmToJSObject().
Referenced by v8::anonymous_namespace{wasm-js.cc}::WebAssemblyExceptionGetArgImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyGlobalGetValueCommon(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableGetImpl().