v8::internal::interpreter Namespace Reference
Namespaces
 anonymous_namespace{bytecode-array-builder.cc}
 anonymous_namespace{bytecode-decoder.cc}
 anonymous_namespace{bytecode-generator.cc}
 anonymous_namespace{bytecode-operands.cc}
 anonymous_namespace{interpreter-generator.cc}
 anonymous_namespace{interpreter.cc}
 bytecode_array_writer_unittest
Classes
class BlockCoverageBuilder
class RegisterTransferWriter
class BytecodeNodeBuilder
class BytecodeArrayBuilder
struct JumpTableTargetOffset
class JumpTableTargetOffsets
class BytecodeArrayIterator
class BytecodeArrayRandomIterator
class BytecodeArrayWriter
class BytecodeDecoder
class CreateArrayLiteralFlags
class CreateObjectLiteralFlags
class CreateClosureFlags
class TestTypeOfFlags
class StoreLookupSlotFlags
class BytecodeGenerator
class BytecodeJumpTable
class BytecodeLoopHeader
class BytecodeLabel
class BytecodeLabels
class BytecodeNode
class BytecodeOperands
class BytecodeRegisterAllocator
struct VariableHint
class BytecodeRegisterOptimizer
class Register
class RegisterList
class BytecodeSourceInfo
struct OperandTypeInfoTraits
struct OperandTraits
struct OperandScaler
struct BytecodeTraits
struct BytecodeTraits< implicit_register_use >
class Bytecodes
class ConstantArrayBuilder
class ControlFlowBuilder
class BreakableControlFlowBuilder
class BlockBuilder
class LoopBuilder
class SwitchBuilder
class TryCatchBuilder
class TryFinallyBuilder
class ConditionalChainControlFlowBuilder
class ConditionalControlFlowBuilder
class HandlerTableBuilder
class InterpreterAssembler
class BytecodeHandlerReducer
class TurboshaftBytecodeHandlerAssembler
class IntrinsicsGenerator
class IntrinsicsHelper
class InterpreterCompilationJob
class Interpreter
Typedefs
using TypeHint = BytecodeRegisterOptimizer::TypeHint
using NumberBuiltinsBytecodeHandlerAssembler = TurboshaftBytecodeHandlerAssembler< NumberBuiltinsReducer >
using BytecodeHandlerData = compiler::turboshaft::BytecodeHandlerData
Enumerations
enum class TryFinallyContinuationToken : int { kFallthroughToken = -1
, kRethrowToken = 0
 }
enum class OperandScale : uint8_t { DECLARE_OPERAND_SCALE
, kLast = kQuadruple
 }
enum class OperandSize : uint8_t {
kNone = 0
, kByte = 1
, kShort = 2
, kQuad = 4
,
kLast = kQuad
 }
enum class OperandTypeInfo : uint8_t { DECLARE_OPERAND_TYPE_INFO
 }
enum class OperandType : uint8_t { DECLARE_OPERAND_TYPE
, COUNT_OPERAND_TYPES
, kLast = -1 OPERAND_TYPE_LIST(COUNT_OPERAND_TYPES)
 }
enum class ImplicitRegisterUse : uint8_t {
kNone = 0
, kReadAccumulator = 1 << 0
, kWriteAccumulator = 1 << 1
, kClobberAccumulator = 1 << 2
,
kWriteShortStar = 1 << 3
, kReadWriteAccumulator = kReadAccumulator | kWriteAccumulator
, kReadAndClobberAccumulator = kReadAccumulator | kClobberAccumulator
, kReadAccumulatorWriteShortStar = kReadAccumulator | kWriteShortStar
 }
enum class VariableHintMode { kDefinitelyHasVariable
, kMightHaveVariable
 }
enum class MaterializedInfo { kNotMaterialized
, kMaterialized
 }
enum class ResetVariableHint { kDontReset
, kReset
 }
enum class Bytecode : uint8_t {
DECLARE_BYTECODE
, COUNT_BYTECODE
, kLast = -1 BYTECODE_LIST(COUNT_BYTECODE, COUNT_BYTECODE)
, kFirstShortStar = kStar15
,
kLastShortStar = kStar0
 }
Functions
void WriteBytecode (std::ofstream &out, Bytecode bytecode, OperandScale operand_scale, int *count, int offset_table[], int table_index)
void WriteHeader (const char *header_filename)
std::ostream & operator<< (std::ostream &os, const BytecodeArrayBuilder::ToBooleanMode &mode)
Bytecode GetJumpWithConstantOperand (Bytecode jump_bytecode)
static bool IsTypeof (Expression *expr)
static bool IsCharU (const AstRawString *str)
static bool IsLiteralCompareTypeof (CompareOperation *expr, Expression **sub_expr, TestTypeOfFlags::LiteralFlag *flag, const AstStringConstants *ast_constants)
std::ostream & operator<< (std::ostream &os, const BytecodeNode &node)
std::ostream & operator<< (std::ostream &os, const ImplicitRegisterUse &use)
std::ostream & operator<< (std::ostream &os, const OperandSize &operand_size)
std::ostream & operator<< (std::ostream &os, const OperandScale &operand_scale)
std::ostream & operator<< (std::ostream &os, const OperandType &operand_type)
constexpr ImplicitRegisterUse operator& (ImplicitRegisterUse lhs, ImplicitRegisterUse rhs)
constexpr ImplicitRegisterUse operator| (ImplicitRegisterUse lhs, ImplicitRegisterUse rhs)
constexpr int OffsetFromFPToRegisterIndex (int offset)
std::ostream & operator<< (std::ostream &os, const BytecodeSourceInfo &info)
std::ostream & operator<< (std::ostream &os, const Bytecode &bytecode)
IGNITION_HANDLER_TS (BitwiseNot, NumberBuiltinsBytecodeHandlerAssembler)
void BitwiseNotAssemblerTS_Generate (compiler::turboshaft::PipelineData *data, Isolate *isolate, compiler::turboshaft::Graph &graph, Zone *zone)
void GenerateBytecodeHandler (compiler::CodeAssemblerState *state, Bytecode bytecode, OperandScale operand_scale)
TNode< Object > GenerateInvokeIntrinsic (InterpreterAssembler *assembler, TNode< Uint32T > function_id, TNode< Context > context, const InterpreterAssembler::RegListNodePair &args)
Variables
const int kIllegalBytecodeHandler = -1
const int kIllegalBytecodeHandlerEncoding = 255
Typedef Documentation
BytecodeHandlerData
using v8::internal::interpreter::BytecodeHandlerData = typedef compiler::turboshaft::BytecodeHandlerData
Definition at line 12 of file interpreter-generator-tsa.h.
NumberBuiltinsBytecodeHandlerAssembler
using v8::internal::interpreter::NumberBuiltinsBytecodeHandlerAssembler = typedef TurboshaftBytecodeHandlerAssembler<NumberBuiltinsReducer>
Definition at line 330 of file interpreter-generator-tsa.cc.
TypeHint
using v8::internal::interpreter::TypeHint = typedef BytecodeRegisterOptimizer::TypeHint
Definition at line 15 of file bytecode-register-optimizer.cc.
Enumeration Type Documentation
Bytecode
enum v8::internal::interpreter::Bytecode : uint8_t [strong]
Enumerator
DECLARE_BYTECODE
COUNT_BYTECODE
kLast
kFirstShortStar
kLastShortStar
Definition at line 595 of file bytecodes.h.
                    : uint8_t {
#define DECLARE_BYTECODE(Name, ...) k##Name,
  BYTECODE_LIST(DECLARE_BYTECODE, DECLARE_BYTECODE)
#undef DECLARE_BYTECODE
#define COUNT_BYTECODE(x, ...) +1
  // The COUNT_BYTECODE macro will turn this into kLast = -1 +1 +1... which will
  // evaluate to the same value as the last real bytecode.
  kLast = -1 BYTECODE_LIST(COUNT_BYTECODE, COUNT_BYTECODE),
  kFirstShortStar = kStar15,
  kLastShortStar = kStar0
#undef COUNT_BYTECODE
};
ImplicitRegisterUse
enum v8::internal::interpreter::ImplicitRegisterUse : uint8_t [strong]
Enumerator
kNone
kReadAccumulator
kWriteAccumulator
kClobberAccumulator
kWriteShortStar
kReadWriteAccumulator
kReadAndClobberAccumulator
kReadAccumulatorWriteShortStar
Definition at line 114 of file bytecode-operands.h.
                               : uint8_t {
  kNone = 0,
  kReadAccumulator = 1 << 0,
  kWriteAccumulator = 1 << 1,
  kClobberAccumulator = 1 << 2,
  kWriteShortStar = 1 << 3,
  kReadWriteAccumulator = kReadAccumulator | kWriteAccumulator,
  kReadAndClobberAccumulator = kReadAccumulator | kClobberAccumulator,
  kReadAccumulatorWriteShortStar = kReadAccumulator | kWriteShortStar
};
MaterializedInfo
enum v8::internal::interpreter::MaterializedInfo [strong]
Enumerator
kNotMaterialized
kMaterialized
Definition at line 26 of file bytecode-register-optimizer.cc.
{ kNotMaterialized, kMaterialized };
OperandScale
enum v8::internal::interpreter::OperandScale : uint8_t [strong]
Enumerator
DECLARE_OPERAND_SCALE
kLast
Definition at line 69 of file bytecode-operands.h.
                        : uint8_t {
#define DECLARE_OPERAND_SCALE(Name, Scale) k##Name = Scale,
  OPERAND_SCALE_LIST(DECLARE_OPERAND_SCALE)
#undef DECLARE_OPERAND_SCALE
      kLast = kQuadruple
};
OperandSize
enum v8::internal::interpreter::OperandSize : uint8_t [strong]
Enumerator
kNone
kByte
kShort
kQuad
kLast
Definition at line 79 of file bytecode-operands.h.
                       : uint8_t {
  kNone = 0,
  kByte = 1,
  kShort = 2,
  kQuad = 4,
  kLast = kQuad
};
OperandType
enum v8::internal::interpreter::OperandType : uint8_t [strong]
Enumerator
DECLARE_OPERAND_TYPE
COUNT_OPERAND_TYPES
kLast
Definition at line 103 of file bytecode-operands.h.
                       : uint8_t {
#define DECLARE_OPERAND_TYPE(Name, _) k##Name,
  OPERAND_TYPE_LIST(DECLARE_OPERAND_TYPE)
#undef DECLARE_OPERAND_TYPE
#define COUNT_OPERAND_TYPES(x, _) +1
  // The COUNT_OPERAND macro will turn this into kLast = -1 +1 +1... which will
  // evaluate to the same value as the last operand.
  kLast = -1 OPERAND_TYPE_LIST(COUNT_OPERAND_TYPES)
#undef COUNT_OPERAND_TYPES
};
OperandTypeInfo
enum v8::internal::interpreter::OperandTypeInfo : uint8_t [strong]
Enumerator
DECLARE_OPERAND_TYPE_INFO
Definition at line 96 of file bytecode-operands.h.
                           : uint8_t {
#define DECLARE_OPERAND_TYPE_INFO(Name, ...) k##Name,
  OPERAND_TYPE_INFO_LIST(DECLARE_OPERAND_TYPE_INFO)
#undef DECLARE_OPERAND_TYPE_INFO
};
ResetVariableHint
enum v8::internal::interpreter::ResetVariableHint [strong]
Enumerator
kDontReset
kReset
Definition at line 28 of file bytecode-register-optimizer.cc.
{ kDontReset, kReset };
TryFinallyContinuationToken
enum v8::internal::interpreter::TryFinallyContinuationToken : int [strong]
Enumerator
kFallthroughToken
kRethrowToken
Definition at line 100 of file bytecode-flags-and-tokens.h.
                                      : int {
  // Fixed value tokens for paths we know we need.
  // Fallthrough is set to -1 to make it the fallthrough case of the jump table,
  // where the remaining cases start at 0.
  kFallthroughToken = -1,
  // TODO(leszeks): Rethrow being 0 makes it use up a valuable LdaZero, which
  // means that other commands (such as break or return) have to use LdaSmi.
  // This can very slightly bloat bytecode, so perhaps token values should all
  // be shifted down by 1.
  kRethrowToken = 0
};
VariableHintMode
enum v8::internal::interpreter::VariableHintMode [strong]
Enumerator
kDefinitelyHasVariable
kMightHaveVariable
Definition at line 19 of file bytecode-register-optimizer.cc.
{ kDefinitelyHasVariable, kMightHaveVariable };
Function Documentation
BitwiseNotAssemblerTS_Generate()
void v8::internal::interpreter::BitwiseNotAssemblerTS_Generate (compiler::turboshaft::PipelineData * data, Isolate * isolate, compiler::turboshaft::Graph & graph, Zone * zone)
GenerateBytecodeHandler()
void v8::internal::interpreter::GenerateBytecodeHandler (compiler::CodeAssemblerState * state, Bytecode bytecode, OperandScale operand_scale)
Definition at line 3424 of file interpreter-generator.cc.
                                                                            {
  switch (bytecode) {
#define CALL_GENERATOR(Name, ...) \
  case Bytecode::k##Name: \
    Name##Assembler::Generate(state, operand_scale); \
    break;
#define CALL_GENERATOR_TS(Name, ...) \
  /* FIXME(348031042): This doesn't compile since the \
   * CodeAssemblerCompilationJob refactor. */ \
  case Bytecode::k##Name: \
    code = compiler::turboshaft::BuildWithTurboshaftAssemblerImpl(\
        isolate, builtin, &Name##AssemblerTS_Generate, descriptor_builder, \
        debug_name, options, CodeKind::BYTECODE_HANDLER, \
        BytecodeHandlerData(bytecode, operand_scale)); \
    break;
    BYTECODE_LIST_WITH_UNIQUE_HANDLERS(CALL_GENERATOR, CALL_GENERATOR_TS);
#undef CALL_GENERATOR
#undef CALL_GENERATOR_TS
    case Bytecode::kIllegal:
      IllegalAssembler::Generate(state, operand_scale);
      break;
    case Bytecode::kStar0:
      Star0Assembler::Generate(state, operand_scale);
      break;
    default:
      // Others (the rest of the short stars, and the rest of the illegal range)
      // must not get their own handler generated. Rather, multiple entries in
      // the jump table point to those handlers.
      UNREACHABLE();
  }
References BYTECODE_LIST_WITH_UNIQUE_HANDLERS, CALL_GENERATOR, CALL_GENERATOR_TS, and v8::internal::UNREACHABLE().
Referenced by v8::internal::anonymous_namespace{setup-builtins-internal.cc}::CompileBytecodeHandler().
GenerateInvokeIntrinsic()
TNode< Object > v8::internal::interpreter::GenerateInvokeIntrinsic (InterpreterAssembler * assembler, TNode< Uint32T > function_id, TNode< Context > context, const InterpreterAssembler::RegListNodePair & args)
Definition at line 54 of file interpreter-intrinsics-generator.cc.
                                                                             {
  IntrinsicsGenerator generator(assembler);
  return generator.InvokeIntrinsic(function_id, context, args);
}
References v8::base::args, and v8::internal::interpreter::IntrinsicsGenerator::InvokeIntrinsic().
Referenced by v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER().
GetJumpWithConstantOperand()
Bytecode v8::internal::interpreter::GetJumpWithConstantOperand (Bytecode jump_bytecode)
Definition at line 320 of file bytecode-array-writer.cc.
                                                            {
  switch (jump_bytecode) {
    case Bytecode::kJump:
      return Bytecode::kJumpConstant;
    case Bytecode::kJumpIfTrue:
      return Bytecode::kJumpIfTrueConstant;
    case Bytecode::kJumpIfFalse:
      return Bytecode::kJumpIfFalseConstant;
    case Bytecode::kJumpIfToBooleanTrue:
      return Bytecode::kJumpIfToBooleanTrueConstant;
    case Bytecode::kJumpIfToBooleanFalse:
      return Bytecode::kJumpIfToBooleanFalseConstant;
    case Bytecode::kJumpIfNull:
      return Bytecode::kJumpIfNullConstant;
    case Bytecode::kJumpIfNotNull:
      return Bytecode::kJumpIfNotNullConstant;
    case Bytecode::kJumpIfUndefined:
      return Bytecode::kJumpIfUndefinedConstant;
    case Bytecode::kJumpIfNotUndefined:
      return Bytecode::kJumpIfNotUndefinedConstant;
    case Bytecode::kJumpIfUndefinedOrNull:
      return Bytecode::kJumpIfUndefinedOrNullConstant;
    case Bytecode::kJumpIfJSReceiver:
      return Bytecode::kJumpIfJSReceiverConstant;
    case Bytecode::kJumpIfForInDone:
      return Bytecode::kJumpIfForInDoneConstant;
    default:
      UNREACHABLE();
  }
}
References v8::internal::UNREACHABLE().
Referenced by v8::internal::interpreter::BytecodeArrayWriter::PatchJumpWith16BitOperand(), and v8::internal::interpreter::BytecodeArrayWriter::PatchJumpWith8BitOperand().
IGNITION_HANDLER_TS()
v8::internal::interpreter::IGNITION_HANDLER_TS (BitwiseNot , NumberBuiltinsBytecodeHandlerAssembler)
Definition at line 333 of file interpreter-generator-tsa.cc.
                                                                        {
  V<Object> value = GetAccumulator();
  V<Context> context = GetContext();
  constexpr int kSlotIndex = 0;
  SetFeedbackSlot(
      __ ChangeUint32ToUintPtr(__ BytecodeOperandIdxInt32(kSlotIndex)));
  LoadFeedbackVectorOrUndefinedIfJitless();
  V<Object> result = BitwiseNot(context, value);
  SetAccumulator(result);
  UpdateFeedback();
  Dispatch();
}
References __, v8::base::internal::result, and v8::internal::value.
IsCharU()
static bool v8::internal::interpreter::IsCharU (const AstRawString * str) [static]
Definition at line 7449 of file bytecode-generator.cc.
                                             {
  return str->length() == 1 && str->FirstCharacter() == 'u';
}
References v8::internal::AstRawString::FirstCharacter(), and v8::internal::AstRawString::length().
Referenced by IsLiteralCompareTypeof().
IsLiteralCompareTypeof()
static bool v8::internal::interpreter::IsLiteralCompareTypeof (CompareOperation * expr, Expression ** sub_expr, TestTypeOfFlags::LiteralFlag * flag, const AstStringConstants * ast_constants) [static]
Definition at line 7453 of file bytecode-generator.cc.
                                                                            {
  if (IsTypeof(expr->left()) && expr->right()->IsStringLiteral()) {
    Literal* right_lit = expr->right()->AsLiteral();
    if (Token::IsEqualityOp(expr->op())) {
      // typeof(x) === 'string'
      *flag = TestTypeOfFlags::GetFlagForLiteral(ast_constants, right_lit);
    } else if (expr->op() == Token::kGreaterThan &&
               IsCharU(right_lit->AsRawString())) {
      // typeof(x) > 'u'
      // Minifier may convert `typeof(x) === 'undefined'` to this form,
      // since `undefined` is the only valid value that is greater than 'u'.
      // Check the test OnlyUndefinedGreaterThanU in bytecodes-unittest.cc
      *flag = TestTypeOfFlags::LiteralFlag::kUndefined;
    } else {
      return false;
    }
    *sub_expr = expr->left()->AsUnaryOperation()->expression();
    return true;
  }
  if (IsTypeof(expr->right()) && expr->left()->IsStringLiteral()) {
    Literal* left_lit = expr->left()->AsLiteral();
    if (Token::IsEqualityOp(expr->op())) {
      // 'string' === typeof(x)
      *flag = TestTypeOfFlags::GetFlagForLiteral(ast_constants, left_lit);
    } else if (expr->op() == Token::kLessThan &&
               IsCharU(left_lit->AsRawString())) {
      // 'u' < typeof(x)
      *flag = TestTypeOfFlags::LiteralFlag::kUndefined;
    } else {
      return false;
    }
    *sub_expr = expr->right()->AsUnaryOperation()->expression();
    return true;
  }
  return false;
}
References v8::internal::Literal::AsRawString(), v8::internal::interpreter::TestTypeOfFlags::GetFlagForLiteral(), IsCharU(), v8::internal::Token::IsEqualityOp(), v8::internal::Expression::IsStringLiteral(), IsTypeof(), v8::internal::kGreaterThan, v8::internal::kLessThan, v8::internal::CompareOperation::left(), v8::internal::CompareOperation::op(), and v8::internal::CompareOperation::right().
IsTypeof()
static bool v8::internal::interpreter::IsTypeof (Expression * expr) [static]
Definition at line 7444 of file bytecode-generator.cc.
                                       {
  UnaryOperation* maybe_unary = expr->AsUnaryOperation();
  return maybe_unary != nullptr && maybe_unary->op() == Token::kTypeOf;
}
References v8::internal::UnaryOperation::op().
Referenced by IsLiteralCompareTypeof().
OffsetFromFPToRegisterIndex()
constexpr int v8::internal::interpreter::OffsetFromFPToRegisterIndex (int offset) [constexpr]
Definition at line 20 of file bytecode-register.h.
                                                      {
  return (InterpreterFrameConstants::kRegisterFileFromFp - offset) /
         kSystemPointerSize;
}
References v8::internal::UnoptimizedFrameConstants::kRegisterFileFromFp, and v8::internal::kSystemPointerSize.
operator&()
constexpr ImplicitRegisterUse v8::internal::interpreter::operator& (ImplicitRegisterUse lhs, ImplicitRegisterUse rhs) [inline], [constexpr]
Definition at line 125 of file bytecode-operands.h.
                                                                        {
  return static_cast<ImplicitRegisterUse>(static_cast<int>(lhs) &
                                          static_cast<int>(rhs));
}
operator<<() [1/8]
V8_EXPORT_PRIVATE std::ostream & v8::internal::interpreter::operator<< (std::ostream & os, const Bytecode & bytecode)
Definition at line 340 of file bytecodes.cc.
                                                                 {
  return os << Bytecodes::ToString(bytecode);
}
References v8::internal::interpreter::Bytecodes::ToString().
operator<<() [2/8]
V8_EXPORT_PRIVATE std::ostream & v8::internal::interpreter::operator<< (std::ostream & os, const BytecodeArrayBuilder::ToBooleanMode & mode)
Definition at line 1773 of file bytecode-array-builder.cc.
                                                                        {
  switch (mode) {
    case BytecodeArrayBuilder::ToBooleanMode::kAlreadyBoolean:
      return os << "AlreadyBoolean";
    case BytecodeArrayBuilder::ToBooleanMode::kConvertToBoolean:
      return os << "ConvertToBoolean";
  }
  UNREACHABLE();
}
References v8::internal::interpreter::BytecodeArrayBuilder::kAlreadyBoolean, v8::internal::interpreter::BytecodeArrayBuilder::kConvertToBoolean, mode(), and v8::internal::UNREACHABLE().
operator<<() [3/8]
V8_EXPORT_PRIVATE std::ostream & v8::internal::interpreter::operator<< (std::ostream & os, const BytecodeNode & node)
Definition at line 49 of file bytecode-node.cc.
                                                                 {
  node.Print(os);
  return os;
}
References v8::internal::interpreter::BytecodeNode::Print().
operator<<() [4/8]
V8_EXPORT_PRIVATE std::ostream & v8::internal::interpreter::operator<< (std::ostream & os, const BytecodeSourceInfo & info)
Definition at line 13 of file bytecode-source-info.cc.
                                                                       {
  if (info.is_valid()) {
    char description = info.is_statement() ? 'S' : 'E';
    os << info.source_position() << ' ' << description << '>';
  }
  return os;
}
References v8::internal::interpreter::BytecodeSourceInfo::is_statement(), v8::internal::interpreter::BytecodeSourceInfo::is_valid(), and v8::internal::interpreter::BytecodeSourceInfo::source_position().
operator<<() [5/8]
V8_EXPORT_PRIVATE std::ostream & v8::internal::interpreter::operator<< (std::ostream & os, const ImplicitRegisterUse & use)
Definition at line 76 of file bytecode-operands.cc.
                                                                       {
  return os << ImplicitRegisterUseToString(use);
}
References v8::internal::interpreter::anonymous_namespace{bytecode-operands.cc}::ImplicitRegisterUseToString(), and use().
operator<<() [6/8]
V8_EXPORT_PRIVATE std::ostream & v8::internal::interpreter::operator<< (std::ostream & os, const OperandScale & operand_scale)
Definition at line 84 of file bytecode-operands.cc.
                                                                          {
  return os << OperandScaleToString(operand_scale);
}
References v8::internal::interpreter::anonymous_namespace{bytecode-operands.cc}::OperandScaleToString().
operator<<() [7/8]
V8_EXPORT_PRIVATE std::ostream & v8::internal::interpreter::operator<< (std::ostream & os, const OperandSize & operand_size)
Definition at line 80 of file bytecode-operands.cc.
                                                                        {
  return os << OperandSizeToString(operand_size);
}
References v8::internal::interpreter::anonymous_namespace{bytecode-operands.cc}::OperandSizeToString().
operator<<() [8/8]
V8_EXPORT_PRIVATE std::ostream & v8::internal::interpreter::operator<< (std::ostream & os, const OperandType & operand_type)
Definition at line 88 of file bytecode-operands.cc.
                                                                        {
  return os << OperandTypeToString(operand_type);
}
References v8::internal::interpreter::anonymous_namespace{bytecode-operands.cc}::OperandTypeToString().
operator|()
constexpr ImplicitRegisterUse v8::internal::interpreter::operator| (ImplicitRegisterUse lhs, ImplicitRegisterUse rhs) [inline], [constexpr]
Definition at line 131 of file bytecode-operands.h.
                                                                        {
  return static_cast<ImplicitRegisterUse>(static_cast<int>(lhs) |
                                          static_cast<int>(rhs));
}
WriteBytecode()
void v8::internal::interpreter::WriteBytecode (std::ofstream & out, Bytecode bytecode, OperandScale operand_scale, int * count, int offset_table[], int table_index)
Definition at line 17 of file generate-bytecodes-builtins-list.cc.
                                    {
  DCHECK_NOT_NULL(count);
  if (Bytecodes::BytecodeHasHandler(bytecode, operand_scale)) {
    std::string name = Bytecodes::ToString(bytecode, operand_scale, "");
    // The handler for Star0 is used for all short star codes. Rename it to
    // something more generic.
    if (bytecode == Bytecode::kStar0) {
      DCHECK_EQ(operand_scale, OperandScale::kSingle);
      name = "ShortStar";
    }
    out << " \\\n V(" << name << "Handler, interpreter::OperandScale::k"
        << operand_scale << ", interpreter::Bytecode::k"
        << Bytecodes::ToString(bytecode) << ")";
    offset_table[table_index] = *count;
    (*count)++;
  } else {
    offset_table[table_index] = kIllegalBytecodeHandler;
  }
}
References v8::internal::interpreter::Bytecodes::BytecodeHasHandler(), DCHECK_EQ, DCHECK_NOT_NULL, kIllegalBytecodeHandler, v8::internal::name, v8::internal::string, and v8::internal::interpreter::Bytecodes::ToString().
WriteHeader()
void v8::internal::interpreter::WriteHeader (const char * header_filename)
Definition at line 41 of file generate-bytecodes-builtins-list.cc.
                                              {
  std::ofstream out(header_filename);
  out << "// Automatically generated from interpreter/bytecodes.h\n"
      << "// The following list macro is used to populate the builtins list\n"
      << "// with the bytecode handlers\n\n"
      << "#include <stdint.h>\n\n"
      << "#ifndef V8_BUILTINS_GENERATED_BYTECODES_BUILTINS_LIST\n"
      << "#define V8_BUILTINS_GENERATED_BYTECODES_BUILTINS_LIST\n\n"
      << "namespace v8 {\n"
      << "namespace internal {\n\n"
      << "#define BUILTIN_LIST_BYTECODE_HANDLERS(V)";
  constexpr int kTableSize =
      BytecodeOperands::kOperandScaleCount * Bytecodes::kBytecodeCount;
  int offset_table[kTableSize];
  int count = 0;
  int index = 0;
#define ADD_BYTECODES(Name, ...) \
  WriteBytecode(out, Bytecode::k##Name, operand_scale, &count, offset_table, \
                index++);
  OperandScale operand_scale = OperandScale::kSingle;
  BYTECODE_LIST(ADD_BYTECODES, ADD_BYTECODES)
  int single_count = count;
  operand_scale = OperandScale::kDouble;
  BYTECODE_LIST(ADD_BYTECODES, ADD_BYTECODES)
  int wide_count = count - single_count;
  operand_scale = OperandScale::kQuadruple;
  BYTECODE_LIST(ADD_BYTECODES, ADD_BYTECODES)
#undef ADD_BYTECODES
  int extra_wide_count = count - wide_count - single_count;
  CHECK_GT(single_count, wide_count);
  CHECK_EQ(single_count,
           Bytecodes::kBytecodeCount - Bytecodes::kShortStarCount + 1);
  CHECK_EQ(wide_count, extra_wide_count);
  out << "\n\nconstexpr int kNumberOfBytecodeHandlers = " << single_count
      << ";\n"
      << "constexpr int kNumberOfWideBytecodeHandlers = " << wide_count
      << ";\n\n"
      << "constexpr uint8_t kIllegalBytecodeHandlerEncoding = "
      << kIllegalBytecodeHandlerEncoding << ";\n\n"
      << "// Mapping from Bytecode to a dense form with all the illegal\n"
      << "// wide Bytecodes removed. Used to index into the builtins table.\n"
      << "constexpr uint8_t kWideBytecodeToBuiltinsMapping["
      << Bytecodes::kBytecodeCount << "] = { \n";
  for (int i = Bytecodes::kBytecodeCount; i < 2 * Bytecodes::kBytecodeCount;
       ++i) {
    int offset = offset_table[i];
    if (offset == kIllegalBytecodeHandler) {
      offset = kIllegalBytecodeHandlerEncoding;
    } else {
      offset -= single_count;
    }
    out << offset << ", ";
  }
  out << "};\n\n"
      << "} // namespace internal\n"
      << "} // namespace v8\n"
      << "#endif // V8_BUILTINS_GENERATED_BYTECODES_BUILTINS_LIST\n";
}
References ADD_BYTECODES, BYTECODE_LIST, CHECK_EQ, CHECK_GT, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::interpreter::Bytecodes::kBytecodeCount, kIllegalBytecodeHandler, kIllegalBytecodeHandlerEncoding, v8::internal::interpreter::BytecodeOperands::kOperandScaleCount, and v8::internal::interpreter::Bytecodes::kShortStarCount.
Referenced by main().
Variable Documentation
kIllegalBytecodeHandler
const int v8::internal::interpreter::kIllegalBytecodeHandler = -1
Definition at line 14 of file generate-bytecodes-builtins-list.cc.
Referenced by WriteBytecode(), and WriteHeader().
kIllegalBytecodeHandlerEncoding
const int v8::internal::interpreter::kIllegalBytecodeHandlerEncoding = 255
Definition at line 15 of file generate-bytecodes-builtins-list.cc.
Referenced by v8::internal::interpreter::anonymous_namespace{interpreter.cc}::BuiltinIndexFromBytecode(), and WriteHeader().