v8::internal::torque::anonymous_namespace{utils.cc} Namespace Reference
Functions
bool ContainsUnderscore (const std::string &s)
bool ContainsUpperCase (const std::string &s)
bool IsKeywordLikeName (const std::string &s)
bool IsMachineType (const std::string &s)
Function Documentation
ContainsUnderscore()
bool v8::internal::torque::anonymous_namespace{utils.cc}::ContainsUnderscore (const std::string & s)
Definition at line 166 of file utils.cc.
                                            {
  if (s.empty()) return false;
  return s.find("_") != std::string::npos;
}
Referenced by v8::internal::torque::IsLowerCamelCase().
ContainsUpperCase()
bool v8::internal::torque::anonymous_namespace{utils.cc}::ContainsUpperCase (const std::string & s)
Definition at line 171 of file utils.cc.
                                           {
  if (s.empty()) return false;
  return std::any_of(s.begin(), s.end(), [](char c) { return isupper(c); });
}
References v8::base::any_of().
Referenced by v8::internal::torque::IsSnakeCase().
IsKeywordLikeName()
bool v8::internal::torque::anonymous_namespace{utils.cc}::IsKeywordLikeName (const std::string & s)
Definition at line 179 of file utils.cc.
                                           {
  static const char* const keyword_like_constants[]{
      "True", "False", "TheHole", "PromiseHole", "Null", "Undefined"};
  return std::find(std::begin(keyword_like_constants),
                   std::end(keyword_like_constants),
                   s) != std::end(keyword_like_constants);
}
References v8::internal::compiler::begin(), and v8::internal::compiler::end().
Referenced by v8::internal::torque::IsValidNamespaceConstName().
IsMachineType()
bool v8::internal::torque::anonymous_namespace{utils.cc}::IsMachineType (const std::string & s)
Definition at line 190 of file utils.cc.
                                       {
  static const char* const machine_types[]{
      VOID_TYPE_STRING,
      NEVER_TYPE_STRING,
      INT8_TYPE_STRING,
      UINT8_TYPE_STRING,
      INT16_TYPE_STRING,
      UINT16_TYPE_STRING,
      INT31_TYPE_STRING,
      UINT31_TYPE_STRING,
      INT32_TYPE_STRING,
      UINT32_TYPE_STRING,
      INT64_TYPE_STRING,
      UINT64_TYPE_STRING,
      INTPTR_TYPE_STRING,
      UINTPTR_TYPE_STRING,
      FLOAT16_RAW_BITS_TYPE_STRING,
      FLOAT32_TYPE_STRING,
      FLOAT64_TYPE_STRING,
      FLOAT64_OR_UNDEFINED_OR_HOLE_TYPE_STRING,
      BOOL_TYPE_STRING,
      "string",
      BINT_TYPE_STRING,
      CHAR8_TYPE_STRING,
      CHAR16_TYPE_STRING};
  return std::find(std::begin(machine_types), std::end(machine_types), s) !=
         std::end(machine_types);
}
References v8::internal::compiler::begin(), v8::internal::torque::BINT_TYPE_STRING, v8::internal::torque::BOOL_TYPE_STRING, v8::internal::torque::CHAR16_TYPE_STRING, v8::internal::torque::CHAR8_TYPE_STRING, v8::internal::compiler::end(), v8::internal::torque::FLOAT16_RAW_BITS_TYPE_STRING, v8::internal::torque::FLOAT32_TYPE_STRING, v8::internal::torque::FLOAT64_OR_UNDEFINED_OR_HOLE_TYPE_STRING, v8::internal::torque::FLOAT64_TYPE_STRING, v8::internal::torque::INT16_TYPE_STRING, v8::internal::torque::INT31_TYPE_STRING, v8::internal::torque::INT32_TYPE_STRING, v8::internal::torque::INT64_TYPE_STRING, v8::internal::torque::INT8_TYPE_STRING, v8::internal::torque::INTPTR_TYPE_STRING, v8::internal::torque::NEVER_TYPE_STRING, v8::internal::torque::UINT16_TYPE_STRING, v8::internal::torque::UINT31_TYPE_STRING, v8::internal::torque::UINT32_TYPE_STRING, v8::internal::torque::UINT64_TYPE_STRING, v8::internal::torque::UINT8_TYPE_STRING, v8::internal::torque::UINTPTR_TYPE_STRING, and v8::internal::torque::VOID_TYPE_STRING.
Referenced by v8::internal::torque::IsValidTypeName().