v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc} Namespace Reference
Classes
class InterpreterLoadGlobalAssembler
class InterpreterLookupContextSlotAssembler
class InterpreterLookupGlobalAssembler
class InterpreterSetNamedPropertyAssembler
class InterpreterBinaryOpAssembler
class InterpreterBitwiseBinaryOpAssembler
class InterpreterJSCallAssembler
class InterpreterCompareOpAssembler
Typedefs
using Label = CodeStubAssembler::Label
Functions
IGNITION_HANDLER (LdaZero, InterpreterAssembler)
IGNITION_HANDLER (LdaSmi, InterpreterAssembler)
IGNITION_HANDLER (LdaConstant, InterpreterAssembler)
IGNITION_HANDLER (LdaUndefined, InterpreterAssembler)
IGNITION_HANDLER (LdaNull, InterpreterAssembler)
IGNITION_HANDLER (LdaTheHole, InterpreterAssembler)
IGNITION_HANDLER (LdaTrue, InterpreterAssembler)
IGNITION_HANDLER (LdaFalse, InterpreterAssembler)
IGNITION_HANDLER (Ldar, InterpreterAssembler)
IGNITION_HANDLER (Star, InterpreterAssembler)
IGNITION_HANDLER (Star0, InterpreterAssembler)
IGNITION_HANDLER (Mov, InterpreterAssembler)
IGNITION_HANDLER (LdaGlobal, InterpreterLoadGlobalAssembler)
IGNITION_HANDLER (LdaGlobalInsideTypeof, InterpreterLoadGlobalAssembler)
IGNITION_HANDLER (StaGlobal, InterpreterAssembler)
IGNITION_HANDLER (LdaContextSlotNoCell, InterpreterAssembler)
IGNITION_HANDLER (LdaContextSlot, InterpreterAssembler)
IGNITION_HANDLER (LdaImmutableContextSlot, InterpreterAssembler)
IGNITION_HANDLER (LdaCurrentContextSlotNoCell, InterpreterAssembler)
IGNITION_HANDLER (LdaCurrentContextSlot, InterpreterAssembler)
IGNITION_HANDLER (LdaImmutableCurrentContextSlot, InterpreterAssembler)
IGNITION_HANDLER (StaContextSlotNoCell, InterpreterAssembler)
IGNITION_HANDLER (StaCurrentContextSlotNoCell, InterpreterAssembler)
IGNITION_HANDLER (StaContextSlot, InterpreterAssembler)
IGNITION_HANDLER (StaCurrentContextSlot, InterpreterAssembler)
IGNITION_HANDLER (LdaLookupSlot, InterpreterAssembler)
IGNITION_HANDLER (LdaLookupSlotInsideTypeof, InterpreterAssembler)
IGNITION_HANDLER (LdaLookupContextSlotNoCell, InterpreterLookupContextSlotAssembler)
IGNITION_HANDLER (LdaLookupContextSlot, InterpreterLookupContextSlotAssembler)
IGNITION_HANDLER (LdaLookupContextSlotNoCellInsideTypeof, InterpreterLookupContextSlotAssembler)
IGNITION_HANDLER (LdaLookupContextSlotInsideTypeof, InterpreterLookupContextSlotAssembler)
IGNITION_HANDLER (LdaLookupGlobalSlot, InterpreterLookupGlobalAssembler)
IGNITION_HANDLER (LdaLookupGlobalSlotInsideTypeof, InterpreterLookupGlobalAssembler)
IGNITION_HANDLER (StaLookupSlot, InterpreterAssembler)
IGNITION_HANDLER (GetNamedProperty, InterpreterAssembler)
IGNITION_HANDLER (GetNamedPropertyFromSuper, InterpreterAssembler)
IGNITION_HANDLER (GetKeyedProperty, InterpreterAssembler)
IGNITION_HANDLER (GetEnumeratedKeyedProperty, InterpreterAssembler)
IGNITION_HANDLER (SetNamedProperty, InterpreterSetNamedPropertyAssembler)
IGNITION_HANDLER (DefineNamedOwnProperty, InterpreterSetNamedPropertyAssembler)
IGNITION_HANDLER (SetKeyedProperty, InterpreterAssembler)
IGNITION_HANDLER (DefineKeyedOwnProperty, InterpreterAssembler)
IGNITION_HANDLER (StaInArrayLiteral, InterpreterAssembler)
IGNITION_HANDLER (DefineKeyedOwnPropertyInLiteral, InterpreterAssembler)
IGNITION_HANDLER (LdaModuleVariable, InterpreterAssembler)
IGNITION_HANDLER (StaModuleVariable, InterpreterAssembler)
IGNITION_HANDLER (PushContext, InterpreterAssembler)
IGNITION_HANDLER (PopContext, InterpreterAssembler)
IGNITION_HANDLER (Add, InterpreterBinaryOpAssembler)
IGNITION_HANDLER (Add_StringConstant_Internalize, InterpreterBinaryOpAssembler)
IGNITION_HANDLER (Sub, InterpreterBinaryOpAssembler)
IGNITION_HANDLER (Mul, InterpreterBinaryOpAssembler)
IGNITION_HANDLER (Div, InterpreterBinaryOpAssembler)
IGNITION_HANDLER (Mod, InterpreterBinaryOpAssembler)
IGNITION_HANDLER (Exp, InterpreterBinaryOpAssembler)
IGNITION_HANDLER (AddSmi, InterpreterBinaryOpAssembler)
IGNITION_HANDLER (SubSmi, InterpreterBinaryOpAssembler)
IGNITION_HANDLER (MulSmi, InterpreterBinaryOpAssembler)
IGNITION_HANDLER (DivSmi, InterpreterBinaryOpAssembler)
IGNITION_HANDLER (ModSmi, InterpreterBinaryOpAssembler)
IGNITION_HANDLER (ExpSmi, InterpreterBinaryOpAssembler)
IGNITION_HANDLER (BitwiseOr, InterpreterBitwiseBinaryOpAssembler)
IGNITION_HANDLER (BitwiseXor, InterpreterBitwiseBinaryOpAssembler)
IGNITION_HANDLER (BitwiseAnd, InterpreterBitwiseBinaryOpAssembler)
IGNITION_HANDLER (ShiftLeft, InterpreterBitwiseBinaryOpAssembler)
IGNITION_HANDLER (ShiftRight, InterpreterBitwiseBinaryOpAssembler)
IGNITION_HANDLER (ShiftRightLogical, InterpreterBitwiseBinaryOpAssembler)
IGNITION_HANDLER (BitwiseOrSmi, InterpreterBitwiseBinaryOpAssembler)
IGNITION_HANDLER (BitwiseXorSmi, InterpreterBitwiseBinaryOpAssembler)
IGNITION_HANDLER (BitwiseAndSmi, InterpreterBitwiseBinaryOpAssembler)
IGNITION_HANDLER (BitwiseNot, InterpreterAssembler)
IGNITION_HANDLER (ShiftLeftSmi, InterpreterBitwiseBinaryOpAssembler)
IGNITION_HANDLER (ShiftRightSmi, InterpreterBitwiseBinaryOpAssembler)
IGNITION_HANDLER (ShiftRightLogicalSmi, InterpreterBitwiseBinaryOpAssembler)
IGNITION_HANDLER (Negate, InterpreterAssembler)
IGNITION_HANDLER (ToName, InterpreterAssembler)
IGNITION_HANDLER (ToNumber, InterpreterAssembler)
IGNITION_HANDLER (ToNumeric, InterpreterAssembler)
IGNITION_HANDLER (ToObject, InterpreterAssembler)
IGNITION_HANDLER (ToString, InterpreterAssembler)
IGNITION_HANDLER (ToBoolean, InterpreterAssembler)
IGNITION_HANDLER (Inc, InterpreterAssembler)
IGNITION_HANDLER (Dec, InterpreterAssembler)
IGNITION_HANDLER (ToBooleanLogicalNot, InterpreterAssembler)
IGNITION_HANDLER (LogicalNot, InterpreterAssembler)
IGNITION_HANDLER (TypeOf, InterpreterAssembler)
IGNITION_HANDLER (DeletePropertyStrict, InterpreterAssembler)
IGNITION_HANDLER (DeletePropertySloppy, InterpreterAssembler)
IGNITION_HANDLER (GetSuperConstructor, InterpreterAssembler)
IGNITION_HANDLER (CallAnyReceiver, InterpreterJSCallAssembler)
IGNITION_HANDLER (CallProperty, InterpreterJSCallAssembler)
IGNITION_HANDLER (CallProperty0, InterpreterJSCallAssembler)
IGNITION_HANDLER (CallProperty1, InterpreterJSCallAssembler)
IGNITION_HANDLER (CallProperty2, InterpreterJSCallAssembler)
IGNITION_HANDLER (CallUndefinedReceiver, InterpreterJSCallAssembler)
IGNITION_HANDLER (CallUndefinedReceiver0, InterpreterJSCallAssembler)
IGNITION_HANDLER (CallUndefinedReceiver1, InterpreterJSCallAssembler)
IGNITION_HANDLER (CallUndefinedReceiver2, InterpreterJSCallAssembler)
IGNITION_HANDLER (CallRuntime, InterpreterAssembler)
IGNITION_HANDLER (InvokeIntrinsic, InterpreterAssembler)
IGNITION_HANDLER (CallRuntimeForPair, InterpreterAssembler)
IGNITION_HANDLER (CallJSRuntime, InterpreterAssembler)
IGNITION_HANDLER (CallWithSpread, InterpreterAssembler)
IGNITION_HANDLER (ConstructWithSpread, InterpreterAssembler)
IGNITION_HANDLER (ConstructForwardAllArgs, InterpreterAssembler)
IGNITION_HANDLER (Construct, InterpreterAssembler)
IGNITION_HANDLER (TestEqual, InterpreterCompareOpAssembler)
IGNITION_HANDLER (TestEqualStrict, InterpreterCompareOpAssembler)
IGNITION_HANDLER (TestLessThan, InterpreterCompareOpAssembler)
IGNITION_HANDLER (TestGreaterThan, InterpreterCompareOpAssembler)
IGNITION_HANDLER (TestLessThanOrEqual, InterpreterCompareOpAssembler)
IGNITION_HANDLER (TestGreaterThanOrEqual, InterpreterCompareOpAssembler)
IGNITION_HANDLER (TestReferenceEqual, InterpreterAssembler)
IGNITION_HANDLER (TestIn, InterpreterAssembler)
IGNITION_HANDLER (TestInstanceOf, InterpreterAssembler)
IGNITION_HANDLER (TestUndetectable, InterpreterAssembler)
IGNITION_HANDLER (TestNull, InterpreterAssembler)
IGNITION_HANDLER (TestUndefined, InterpreterAssembler)
IGNITION_HANDLER (TestTypeOf, InterpreterAssembler)
IGNITION_HANDLER (Jump, InterpreterAssembler)
IGNITION_HANDLER (JumpConstant, InterpreterAssembler)
IGNITION_HANDLER (JumpIfTrue, InterpreterAssembler)
IGNITION_HANDLER (JumpIfTrueConstant, InterpreterAssembler)
IGNITION_HANDLER (JumpIfFalse, InterpreterAssembler)
IGNITION_HANDLER (JumpIfFalseConstant, InterpreterAssembler)
IGNITION_HANDLER (JumpIfToBooleanTrue, InterpreterAssembler)
IGNITION_HANDLER (JumpIfToBooleanTrueConstant, InterpreterAssembler)
IGNITION_HANDLER (JumpIfToBooleanFalse, InterpreterAssembler)
IGNITION_HANDLER (JumpIfToBooleanFalseConstant, InterpreterAssembler)
IGNITION_HANDLER (JumpIfNull, InterpreterAssembler)
IGNITION_HANDLER (JumpIfNullConstant, InterpreterAssembler)
IGNITION_HANDLER (JumpIfNotNull, InterpreterAssembler)
IGNITION_HANDLER (JumpIfNotNullConstant, InterpreterAssembler)
IGNITION_HANDLER (JumpIfUndefined, InterpreterAssembler)
IGNITION_HANDLER (JumpIfUndefinedConstant, InterpreterAssembler)
IGNITION_HANDLER (JumpIfNotUndefined, InterpreterAssembler)
IGNITION_HANDLER (JumpIfNotUndefinedConstant, InterpreterAssembler)
IGNITION_HANDLER (JumpIfUndefinedOrNull, InterpreterAssembler)
IGNITION_HANDLER (JumpIfUndefinedOrNullConstant, InterpreterAssembler)
IGNITION_HANDLER (JumpIfJSReceiver, InterpreterAssembler)
IGNITION_HANDLER (JumpIfJSReceiverConstant, InterpreterAssembler)
IGNITION_HANDLER (JumpIfForInDone, InterpreterAssembler)
IGNITION_HANDLER (JumpIfForInDoneConstant, InterpreterAssembler)
IGNITION_HANDLER (JumpLoop, InterpreterAssembler)
IGNITION_HANDLER (SwitchOnSmiNoFeedback, InterpreterAssembler)
IGNITION_HANDLER (CreateRegExpLiteral, InterpreterAssembler)
IGNITION_HANDLER (CreateArrayLiteral, InterpreterAssembler)
IGNITION_HANDLER (CreateEmptyArrayLiteral, InterpreterAssembler)
IGNITION_HANDLER (CreateArrayFromIterable, InterpreterAssembler)
IGNITION_HANDLER (CreateObjectLiteral, InterpreterAssembler)
IGNITION_HANDLER (CreateEmptyObjectLiteral, InterpreterAssembler)
IGNITION_HANDLER (CloneObject, InterpreterAssembler)
IGNITION_HANDLER (GetTemplateObject, InterpreterAssembler)
IGNITION_HANDLER (CreateClosure, InterpreterAssembler)
IGNITION_HANDLER (CreateBlockContext, InterpreterAssembler)
IGNITION_HANDLER (CreateCatchContext, InterpreterAssembler)
IGNITION_HANDLER (CreateFunctionContext, InterpreterAssembler)
IGNITION_HANDLER (CreateFunctionContextWithCells, InterpreterAssembler)
IGNITION_HANDLER (CreateEvalContext, InterpreterAssembler)
IGNITION_HANDLER (CreateWithContext, InterpreterAssembler)
IGNITION_HANDLER (CreateMappedArguments, InterpreterAssembler)
IGNITION_HANDLER (CreateUnmappedArguments, InterpreterAssembler)
IGNITION_HANDLER (CreateRestParameter, InterpreterAssembler)
IGNITION_HANDLER (SetPendingMessage, InterpreterAssembler)
IGNITION_HANDLER (Throw, InterpreterAssembler)
IGNITION_HANDLER (ReThrow, InterpreterAssembler)
IGNITION_HANDLER (Abort, InterpreterAssembler)
IGNITION_HANDLER (Return, InterpreterAssembler)
IGNITION_HANDLER (ThrowReferenceErrorIfHole, InterpreterAssembler)
IGNITION_HANDLER (ThrowSuperNotCalledIfHole, InterpreterAssembler)
IGNITION_HANDLER (ThrowSuperAlreadyCalledIfNotHole, InterpreterAssembler)
IGNITION_HANDLER (ThrowIfNotSuperConstructor, InterpreterAssembler)
IGNITION_HANDLER (FindNonDefaultConstructorOrConstruct, InterpreterAssembler)
IGNITION_HANDLER (Debugger, InterpreterAssembler)
IGNITION_HANDLER (IncBlockCounter, InterpreterAssembler)
IGNITION_HANDLER (ForInEnumerate, InterpreterAssembler)
IGNITION_HANDLER (ForInPrepare, InterpreterAssembler)
IGNITION_HANDLER (ForInNext, InterpreterAssembler)
IGNITION_HANDLER (ForInStep, InterpreterAssembler)
IGNITION_HANDLER (GetIterator, InterpreterAssembler)
IGNITION_HANDLER (Wide, InterpreterAssembler)
IGNITION_HANDLER (ExtraWide, InterpreterAssembler)
IGNITION_HANDLER (Illegal, InterpreterAssembler)
IGNITION_HANDLER (SuspendGenerator, InterpreterAssembler)
IGNITION_HANDLER (SwitchOnGeneratorState, InterpreterAssembler)
IGNITION_HANDLER (ResumeGenerator, InterpreterAssembler)
Typedef Documentation
Label
using v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::Label = typedef CodeStubAssembler::Label
Definition at line 43 of file interpreter-generator.cc.
Function Documentation
IGNITION_HANDLER() [1/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (Abort , InterpreterAssembler)
Definition at line 2996 of file interpreter-generator.cc.
                                              {
  TNode<UintPtrT> reason = BytecodeOperandIdx(0);
  CallRuntime(Runtime::kAbort, NoContextConstant(), SmiTag(Signed(reason)));
  Unreachable();
}
References v8::base::bits::Signed().
IGNITION_HANDLER() [2/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (Add , InterpreterBinaryOpAssembler)
Definition at line 1009 of file interpreter-generator.cc.
                                                    {
  BinaryOpWithFeedback(&BinaryOpAssembler::Generate_AddWithFeedback);
}
References v8::internal::BinaryOpAssembler::Generate_AddWithFeedback().
IGNITION_HANDLER() [3/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (Add_StringConstant_Internalize , InterpreterBinaryOpAssembler)
Definition at line 1016 of file interpreter-generator.cc.
                                                                               {
  auto as_variant = UncheckedCast<Int32T>(BytecodeOperandFlag8(2));
  using ASVariant = AddStringConstantAndInternalizeVariant;
  auto lhs_is_sc =
      Int32Constant(static_cast<uint8_t>(ASVariant::kLhsIsStringConstant));
  Label if_lhs_is_string_constant(this), if_rhs_is_string_constant(this),
      done(this);
  Branch(Word32Equal(as_variant, lhs_is_sc), &if_lhs_is_string_constant,
         &if_rhs_is_string_constant);
  BIND(&if_lhs_is_string_constant);
  CSA_DCHECK(this, Word32Equal(as_variant, lhs_is_sc));
  BinaryOpWithFeedback_WithoutDispatch(
      &BinaryOpAssembler::
          Generate_AddLhsIsStringConstantInternalizeWithFeedback);
  Goto(&done);
  BIND(&if_rhs_is_string_constant);
#ifdef DEBUG
  auto rhs_is_sc =
      Int32Constant(static_cast<uint8_t>(ASVariant::kRhsIsStringConstant));
  CSA_DCHECK(this, Word32Equal(as_variant, rhs_is_sc));
#endif // DEBUG
  BinaryOpWithFeedback_WithoutDispatch(
      &BinaryOpAssembler::
          Generate_AddRhsIsStringConstantInternalizeWithFeedback);
  Goto(&done);
  BIND(&done);
  Dispatch();
}
References v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::Word32Equal().
IGNITION_HANDLER() [4/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (AddSmi , InterpreterBinaryOpAssembler)
Definition at line 1087 of file interpreter-generator.cc.
                                                       {
  BinaryOpSmiWithFeedback(&BinaryOpAssembler::Generate_AddWithFeedback);
}
References v8::internal::BinaryOpAssembler::Generate_AddWithFeedback().
IGNITION_HANDLER() [5/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (BitwiseAnd , InterpreterBitwiseBinaryOpAssembler)
Definition at line 1188 of file interpreter-generator.cc.
                                                                  {
  BitwiseBinaryOpWithFeedback(Operation::kBitwiseAnd);
}
IGNITION_HANDLER() [6/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (BitwiseAndSmi , InterpreterBitwiseBinaryOpAssembler)
Definition at line 1239 of file interpreter-generator.cc.
                                                                     {
  BitwiseBinaryOpWithSmi(Operation::kBitwiseAnd);
}
IGNITION_HANDLER() [7/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (BitwiseNot , InterpreterAssembler)
Definition at line 1248 of file interpreter-generator.cc.
                                                   {
  TNode<Object> value = GetAccumulator();
  TNode<Context> context = GetContext();
  TNode<UintPtrT> slot_index = BytecodeOperandIdx(0);
  TNode<Union<FeedbackVector, Undefined>> maybe_feedback_vector =
      LoadFeedbackVectorOrUndefinedIfJitless();
  static constexpr UpdateFeedbackMode mode = DefaultUpdateFeedbackMode();
  UnaryOpAssembler unary_op_asm(state());
  TNode<Object> result = unary_op_asm.Generate_BitwiseNotWithFeedback(
      context, value, slot_index, maybe_feedback_vector, mode);
  SetAccumulator(result);
  Dispatch();
}
References v8::internal::UnaryOpAssembler::Generate_BitwiseNotWithFeedback(), mode(), v8::base::internal::result, and v8::internal::value.
IGNITION_HANDLER() [8/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (BitwiseOr , InterpreterBitwiseBinaryOpAssembler)
Definition at line 1174 of file interpreter-generator.cc.
                                                                 {
  BitwiseBinaryOpWithFeedback(Operation::kBitwiseOr);
}
IGNITION_HANDLER() [9/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (BitwiseOrSmi , InterpreterBitwiseBinaryOpAssembler)
Definition at line 1225 of file interpreter-generator.cc.
                                                                    {
  BitwiseBinaryOpWithSmi(Operation::kBitwiseOr);
}
IGNITION_HANDLER() [10/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (BitwiseXor , InterpreterBitwiseBinaryOpAssembler)
Definition at line 1181 of file interpreter-generator.cc.
                                                                  {
  BitwiseBinaryOpWithFeedback(Operation::kBitwiseXor);
}
IGNITION_HANDLER() [11/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (BitwiseXorSmi , InterpreterBitwiseBinaryOpAssembler)
Definition at line 1232 of file interpreter-generator.cc.
                                                                     {
  BitwiseBinaryOpWithSmi(Operation::kBitwiseXor);
}
IGNITION_HANDLER() [12/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (CallAnyReceiver , InterpreterJSCallAssembler)
Definition at line 1615 of file interpreter-generator.cc.
                                                              {
  JSCall(ConvertReceiverMode::kAny);
}
References v8::internal::kAny.
IGNITION_HANDLER() [13/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (CallJSRuntime , InterpreterAssembler)
Definition at line 1705 of file interpreter-generator.cc.
                                                      {
  TNode<IntPtrT> context_index = Signed(BytecodeOperandNativeContextIndex(0));
  RegListNodePair args = GetRegisterListAtOperandIndex(1);
  // Get the function to call from the native context.
  TNode<Context> context = GetContext();
  TNode<NativeContext> native_context = LoadNativeContext(context);
  TNode<JSAny> function =
      CAST(LoadContextElementNoCell(native_context, context_index));
  // Call the function.
  CallJSAndDispatch(function, context, args,
                    ConvertReceiverMode::kNullOrUndefined);
}
References v8::base::args, CAST, v8::internal::kNullOrUndefined, v8::internal::native_context, and v8::base::bits::Signed().
IGNITION_HANDLER() [14/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (CallProperty , InterpreterJSCallAssembler)
Definition at line 1619 of file interpreter-generator.cc.
                                                           {
  JSCall(ConvertReceiverMode::kNotNullOrUndefined);
}
References v8::internal::kNotNullOrUndefined.
IGNITION_HANDLER() [15/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (CallProperty0 , InterpreterJSCallAssembler)
Definition at line 1623 of file interpreter-generator.cc.
                                                            {
  JSCallN(0, ConvertReceiverMode::kNotNullOrUndefined);
}
References v8::internal::kNotNullOrUndefined.
IGNITION_HANDLER() [16/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (CallProperty1 , InterpreterJSCallAssembler)
Definition at line 1627 of file interpreter-generator.cc.
                                                            {
  JSCallN(1, ConvertReceiverMode::kNotNullOrUndefined);
}
References v8::internal::kNotNullOrUndefined.
IGNITION_HANDLER() [17/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (CallProperty2 , InterpreterJSCallAssembler)
Definition at line 1631 of file interpreter-generator.cc.
                                                            {
  JSCallN(2, ConvertReceiverMode::kNotNullOrUndefined);
}
References v8::internal::kNotNullOrUndefined.
IGNITION_HANDLER() [18/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (CallRuntime , InterpreterAssembler)
Definition at line 1656 of file interpreter-generator.cc.
                                                    {
  TNode<Uint32T> function_id = BytecodeOperandRuntimeId(0);
  RegListNodePair args = GetRegisterListAtOperandIndex(1);
  TNode<Context> context = GetContext();
  TNode<Object> result = CallRuntimeN(function_id, context, args, 1);
  SetAccumulator(result);
  Dispatch();
}
References v8::base::args, and v8::base::internal::result.
IGNITION_HANDLER() [19/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (CallRuntimeForPair , InterpreterAssembler)
Definition at line 1686 of file interpreter-generator.cc.
                                                           {
  // Call the runtime function.
  TNode<Uint32T> function_id = BytecodeOperandRuntimeId(0);
  RegListNodePair args = GetRegisterListAtOperandIndex(1);
  TNode<Context> context = GetContext();
  auto result_pair =
      CallRuntimeN<PairT<Object, Object>>(function_id, context, args, 2);
  // Store the results in <first_return> and <first_return + 1>
  TNode<Object> result0 = Projection<0>(result_pair);
  TNode<Object> result1 = Projection<1>(result_pair);
  StoreRegisterPairAtOperandIndex(result0, result1, 3);
  ClobberAccumulator(result0);
  Dispatch();
}
References v8::base::args.
IGNITION_HANDLER() [20/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (CallUndefinedReceiver , InterpreterJSCallAssembler)
Definition at line 1635 of file interpreter-generator.cc.
                                                                    {
  JSCall(ConvertReceiverMode::kNullOrUndefined);
}
References v8::internal::kNullOrUndefined.
IGNITION_HANDLER() [21/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (CallUndefinedReceiver0 , InterpreterJSCallAssembler)
Definition at line 1639 of file interpreter-generator.cc.
                                                                     {
  JSCallN(0, ConvertReceiverMode::kNullOrUndefined);
}
References v8::internal::kNullOrUndefined.
IGNITION_HANDLER() [22/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (CallUndefinedReceiver1 , InterpreterJSCallAssembler)
Definition at line 1643 of file interpreter-generator.cc.
                                                                     {
  JSCallN(1, ConvertReceiverMode::kNullOrUndefined);
}
References v8::internal::kNullOrUndefined.
IGNITION_HANDLER() [23/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (CallUndefinedReceiver2 , InterpreterJSCallAssembler)
Definition at line 1647 of file interpreter-generator.cc.
                                                                     {
  JSCallN(2, ConvertReceiverMode::kNullOrUndefined);
}
References v8::internal::kNullOrUndefined.
IGNITION_HANDLER() [24/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (CallWithSpread , InterpreterAssembler)
Definition at line 1726 of file interpreter-generator.cc.
                                                       {
  TNode<JSAny> callable = CAST(LoadRegisterAtOperandIndex(0));
  RegListNodePair args = GetRegisterListAtOperandIndex(1);
  TNode<UintPtrT> slot_id = BytecodeOperandIdx(3);
  TNode<Context> context = GetContext();
  // Call into Runtime function CallWithSpread which does everything.
  CallJSWithSpreadAndDispatch(callable, context, args, slot_id);
}
References v8::base::args, and CAST.
IGNITION_HANDLER() [25/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (CloneObject , InterpreterAssembler)
Definition at line 2724 of file interpreter-generator.cc.
                                                    {
  TNode<Object> source = LoadRegisterAtOperandIndex(0);
  TNode<Uint32T> bytecode_flags = BytecodeOperandFlag8(1);
  TNode<UintPtrT> raw_flags =
      DecodeWordFromWord32<CreateObjectLiteralFlags::FlagsBits>(bytecode_flags);
  TNode<Smi> smi_flags = SmiTag(Signed(raw_flags));
  TNode<TaggedIndex> slot = BytecodeOperandIdxTaggedIndex(2);
  TNode<Union<FeedbackVector, Undefined>> maybe_feedback_vector =
      LoadFeedbackVector();
  TNode<Context> context = GetContext();
  TNode<Object> result = CallBuiltin(Builtin::kCloneObjectIC, context, source,
                                     smi_flags, slot, maybe_feedback_vector);
  SetAccumulator(result);
  Dispatch();
}
References v8::base::internal::result, and v8::base::bits::Signed().
IGNITION_HANDLER() [26/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (Construct , InterpreterAssembler)
Definition at line 1776 of file interpreter-generator.cc.
                                                  {
  TNode<JSAny> new_target = CAST(GetAccumulator());
  TNode<JSAny> constructor = CAST(LoadRegisterAtOperandIndex(0));
  RegListNodePair args = GetRegisterListAtOperandIndex(1);
  TNode<UintPtrT> slot_id = BytecodeOperandIdx(3);
  TNode<Union<FeedbackVector, Undefined>> maybe_feedback_vector =
      LoadFeedbackVector();
  TNode<Context> context = GetContext();
  TNode<Object> result = Construct(constructor, context, new_target, args,
                                   slot_id, maybe_feedback_vector);
  SetAccumulator(result);
  Dispatch();
}
References v8::base::args, CAST, v8::internal::anonymous_namespace{js-locale.cc}::Construct(), and v8::base::internal::result.
IGNITION_HANDLER() [27/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (ConstructForwardAllArgs , InterpreterAssembler)
Definition at line 1759 of file interpreter-generator.cc.
                                                                {
  TNode<JSAny> new_target = CAST(GetAccumulator());
  TNode<JSAny> constructor = CAST(LoadRegisterAtOperandIndex(0));
  TNode<TaggedIndex> slot_id = BytecodeOperandIdxTaggedIndex(1);
  TNode<Context> context = GetContext();
  TNode<Object> result =
      ConstructForwardAllArgs(constructor, context, new_target, slot_id);
  SetAccumulator(result);
  Dispatch();
}
References CAST, and v8::base::internal::result.
IGNITION_HANDLER() [28/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (ConstructWithSpread , InterpreterAssembler)
Definition at line 1742 of file interpreter-generator.cc.
                                                            {
  TNode<JSAny> new_target = CAST(GetAccumulator());
  TNode<JSAny> constructor = CAST(LoadRegisterAtOperandIndex(0));
  RegListNodePair args = GetRegisterListAtOperandIndex(1);
  TNode<UintPtrT> slot_id = BytecodeOperandIdx(3);
  TNode<Context> context = GetContext();
  TNode<Object> result =
      ConstructWithSpread(constructor, context, new_target, args, slot_id);
  SetAccumulator(result);
  Dispatch();
}
References v8::base::args, CAST, and v8::base::internal::result.
IGNITION_HANDLER() [29/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (CreateArrayFromIterable , InterpreterAssembler)
Definition at line 2642 of file interpreter-generator.cc.
                                                                {
  TNode<Object> iterable = GetAccumulator();
  TNode<Context> context = GetContext();
  TNode<Object> result =
      CallBuiltin(Builtin::kIterableToListWithSymbolLookup, context, iterable);
  SetAccumulator(result);
  Dispatch();
}
References v8::base::internal::result.
IGNITION_HANDLER() [30/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (CreateArrayLiteral , InterpreterAssembler)
Definition at line 2552 of file interpreter-generator.cc.
                                                           {
  TNode<HeapObject> feedback_vector = LoadFeedbackVector();
  TNode<TaggedIndex> slot = BytecodeOperandIdxTaggedIndex(1);
  TNode<Context> context = GetContext();
  TNode<Uint32T> bytecode_flags = BytecodeOperandFlag8(2);
  Label fast_shallow_clone(this), slow_clone(this, Label::kDeferred),
      call_runtime(this, Label::kDeferred);
  TNode<UintPtrT> flags_raw =
      DecodeWordFromWord32<CreateArrayLiteralFlags::FlagsBits>(bytecode_flags);
  TNode<Smi> flags = SmiTag(Signed(flags_raw));
  TNode<Object> array_boilerplate_description =
      LoadConstantPoolEntryAtOperandIndex(0);
  // No feedback, so handle it as a slow case.
  GotoIf(IsUndefined(feedback_vector), &call_runtime);
  Branch(IsSetWord32<CreateArrayLiteralFlags::FastCloneSupportedBit>(
             bytecode_flags),
         &fast_shallow_clone, &slow_clone);
  BIND(&fast_shallow_clone);
  {
    ConstructorBuiltinsAssembler constructor_assembler(state());
    TNode<JSArray> result = constructor_assembler.CreateShallowArrayLiteral(
        CAST(feedback_vector), slot, context, TRACK_ALLOCATION_SITE,
        &call_runtime);
    SetAccumulator(result);
    Dispatch();
  }
  BIND(&slow_clone);
  {
    TNode<JSArray> result = CAST(CallBuiltin(
        Builtin::kCreateArrayFromSlowBoilerplate, context, feedback_vector,
        slot, array_boilerplate_description, flags));
    SetAccumulator(result);
    Dispatch();
  }
  BIND(&call_runtime);
  {
    TNode<Object> result =
        CallRuntime(Runtime::kCreateArrayLiteral, context, feedback_vector,
                    slot, array_boilerplate_description, flags);
    SetAccumulator(result);
    Dispatch();
  }
}
References CAST, v8::internal::ConstructorBuiltinsAssembler::CreateShallowArrayLiteral(), v8::internal::flags, v8::base::internal::result, v8::base::bits::Signed(), and v8::internal::TRACK_ALLOCATION_SITE.
IGNITION_HANDLER() [31/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (CreateBlockContext , InterpreterAssembler)
Definition at line 2817 of file interpreter-generator.cc.
                                                           {
  TNode<ScopeInfo> scope_info = CAST(LoadConstantPoolEntryAtOperandIndex(0));
  TNode<Context> context = GetContext();
  SetAccumulator(CallRuntime(Runtime::kPushBlockContext, context, scope_info));
  Dispatch();
}
References CAST.
IGNITION_HANDLER() [32/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (CreateCatchContext , InterpreterAssembler)
Definition at line 2828 of file interpreter-generator.cc.
                                                           {
  TNode<Object> exception = LoadRegisterAtOperandIndex(0);
  TNode<ScopeInfo> scope_info = CAST(LoadConstantPoolEntryAtOperandIndex(1));
  TNode<Context> context = GetContext();
  SetAccumulator(
      CallRuntime(Runtime::kPushCatchContext, context, exception, scope_info));
  Dispatch();
}
References CAST.
IGNITION_HANDLER() [33/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (CreateClosure , InterpreterAssembler)
Definition at line 2766 of file interpreter-generator.cc.
                                                      {
  TNode<Object> shared = LoadConstantPoolEntryAtOperandIndex(0);
  TNode<Uint32T> flags = BytecodeOperandFlag8(2);
  TNode<Context> context = GetContext();
  TNode<UintPtrT> slot = BytecodeOperandIdx(1);
  Label if_undefined(this);
  TNode<ClosureFeedbackCellArray> feedback_cell_array =
      LoadClosureFeedbackArray(LoadFunctionClosure());
  TNode<FeedbackCell> feedback_cell =
      LoadArrayElement(feedback_cell_array, slot);
  Label if_fast(this), if_slow(this, Label::kDeferred);
  Branch(IsSetWord32<CreateClosureFlags::FastNewClosureBit>(flags), &if_fast,
         &if_slow);
  BIND(&if_fast);
  {
    TNode<Object> result =
        CallBuiltin(Builtin::kFastNewClosure, context, shared, feedback_cell);
    SetAccumulator(result);
    Dispatch();
  }
  BIND(&if_slow);
  {
    Label if_newspace(this), if_oldspace(this);
    Branch(IsSetWord32<CreateClosureFlags::PretenuredBit>(flags), &if_oldspace,
           &if_newspace);
    BIND(&if_newspace);
    {
      TNode<Object> result =
          CallRuntime(Runtime::kNewClosure, context, shared, feedback_cell);
      SetAccumulator(result);
      Dispatch();
    }
    BIND(&if_oldspace);
    {
      TNode<Object> result = CallRuntime(Runtime::kNewClosure_Tenured, context,
                                         shared, feedback_cell);
      SetAccumulator(result);
      Dispatch();
    }
  }
}
References v8::internal::flags, and v8::base::internal::result.
IGNITION_HANDLER() [34/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (CreateEmptyArrayLiteral , InterpreterAssembler)
Definition at line 2607 of file interpreter-generator.cc.
                                                                {
  TNode<Union<FeedbackVector, Undefined>> maybe_feedback_vector =
      LoadFeedbackVector();
  TNode<TaggedIndex> slot = BytecodeOperandIdxTaggedIndex(0);
  TNode<Context> context = GetContext();
  Label no_feedback(this, Label::kDeferred), end(this);
  TVARIABLE(JSArray, result);
  GotoIf(IsUndefined(maybe_feedback_vector), &no_feedback);
  ConstructorBuiltinsAssembler constructor_assembler(state());
  result = constructor_assembler.CreateEmptyArrayLiteral(
      CAST(maybe_feedback_vector), slot, context);
  Goto(&end);
  BIND(&no_feedback);
  {
    TNode<Map> array_map = LoadJSArrayElementsMap(GetInitialFastElementsKind(),
                                                  LoadNativeContext(context));
    TNode<Smi> length = SmiConstant(0);
    TNode<IntPtrT> capacity = IntPtrConstant(0);
    result = AllocateJSArray(GetInitialFastElementsKind(), array_map, capacity,
                             length);
    Goto(&end);
  }
  BIND(&end);
  SetAccumulator(result.value());
  Dispatch();
}
References CAST, v8::internal::ConstructorBuiltinsAssembler::CreateEmptyArrayLiteral(), v8::internal::compiler::end(), v8::internal::GetInitialFastElementsKind(), v8::internal::compiler::IntPtrConstant(), v8::internal::length, and v8::base::internal::result.
IGNITION_HANDLER() [35/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (CreateEmptyObjectLiteral , InterpreterAssembler)
Definition at line 2711 of file interpreter-generator.cc.
                                                                 {
  TNode<Context> context = GetContext();
  ConstructorBuiltinsAssembler constructor_assembler(state());
  TNode<JSObject> result =
      constructor_assembler.CreateEmptyObjectLiteral(context);
  SetAccumulator(result);
  Dispatch();
}
References v8::internal::ConstructorBuiltinsAssembler::CreateEmptyObjectLiteral(), and v8::base::internal::result.
IGNITION_HANDLER() [36/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (CreateEvalContext , InterpreterAssembler)
Definition at line 2870 of file interpreter-generator.cc.
                                                          {
  TNode<UintPtrT> scope_info_idx = BytecodeOperandIdx(0);
  TNode<ScopeInfo> scope_info = CAST(LoadConstantPoolEntry(scope_info_idx));
  TNode<Uint32T> slots = BytecodeOperandUImm(1);
  TNode<Context> context = GetContext();
  ConstructorBuiltinsAssembler constructor_assembler(state());
  SetAccumulator(constructor_assembler.FastNewFunctionContext(
      scope_info, slots, context, EVAL_SCOPE, ContextMode::kNoContextCells));
  Dispatch();
}
References CAST, v8::internal::EVAL_SCOPE, v8::internal::ConstructorBuiltinsAssembler::FastNewFunctionContext(), and v8::internal::kNoContextCells.
IGNITION_HANDLER() [37/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (CreateFunctionContext , InterpreterAssembler)
Definition at line 2840 of file interpreter-generator.cc.
                                                              {
  TNode<UintPtrT> scope_info_idx = BytecodeOperandIdx(0);
  TNode<ScopeInfo> scope_info = CAST(LoadConstantPoolEntry(scope_info_idx));
  TNode<Uint32T> slots = BytecodeOperandUImm(1);
  TNode<Context> context = GetContext();
  ConstructorBuiltinsAssembler constructor_assembler(state());
  SetAccumulator(constructor_assembler.FastNewFunctionContext(
      scope_info, slots, context, FUNCTION_SCOPE,
      ContextMode::kNoContextCells));
  Dispatch();
}
References CAST, v8::internal::ConstructorBuiltinsAssembler::FastNewFunctionContext(), v8::internal::FUNCTION_SCOPE, and v8::internal::kNoContextCells.
IGNITION_HANDLER() [38/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (CreateFunctionContextWithCells , InterpreterAssembler)
Definition at line 2855 of file interpreter-generator.cc.
                                                                       {
  TNode<UintPtrT> scope_info_idx = BytecodeOperandIdx(0);
  TNode<ScopeInfo> scope_info = CAST(LoadConstantPoolEntry(scope_info_idx));
  TNode<Uint32T> slots = BytecodeOperandUImm(1);
  TNode<Context> context = GetContext();
  ConstructorBuiltinsAssembler constructor_assembler(state());
  SetAccumulator(constructor_assembler.FastNewFunctionContext(
      scope_info, slots, context, FUNCTION_SCOPE,
      ContextMode::kHasContextCells));
  Dispatch();
}
References CAST, v8::internal::ConstructorBuiltinsAssembler::FastNewFunctionContext(), v8::internal::FUNCTION_SCOPE, and v8::internal::kHasContextCells.
IGNITION_HANDLER() [39/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (CreateMappedArguments , InterpreterAssembler)
Definition at line 2897 of file interpreter-generator.cc.
                                                              {
  TNode<JSFunction> closure = LoadFunctionClosure();
  TNode<Context> context = GetContext();
  Label if_duplicate_parameters(this, Label::kDeferred);
  Label if_not_duplicate_parameters(this);
  // Check if function has duplicate parameters.
  // TODO(rmcilroy): Remove this check when FastNewSloppyArgumentsStub supports
  // duplicate parameters.
  TNode<SharedFunctionInfo> shared_info = LoadObjectField<SharedFunctionInfo>(
      closure, JSFunction::kSharedFunctionInfoOffset);
  TNode<Uint32T> flags =
      LoadObjectField<Uint32T>(shared_info, SharedFunctionInfo::kFlagsOffset);
  TNode<BoolT> has_duplicate_parameters =
      IsSetWord32<SharedFunctionInfo::HasDuplicateParametersBit>(flags);
  Branch(has_duplicate_parameters, &if_duplicate_parameters,
         &if_not_duplicate_parameters);
  BIND(&if_not_duplicate_parameters);
  {
    TNode<JSObject> result = EmitFastNewSloppyArguments(context, closure);
    SetAccumulator(result);
    Dispatch();
  }
  BIND(&if_duplicate_parameters);
  {
    TNode<Object> result =
        CallRuntime(Runtime::kNewSloppyArguments, context, closure);
    SetAccumulator(result);
    Dispatch();
  }
}
References v8::internal::flags, v8::internal::has_duplicate_parameters, and v8::base::internal::result.
IGNITION_HANDLER() [40/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (CreateObjectLiteral , InterpreterAssembler)
Definition at line 2655 of file interpreter-generator.cc.
                                                            {
  TNode<HeapObject> feedback_vector = LoadFeedbackVector();
  TNode<Context> context = GetContext();
  TNode<TaggedIndex> slot = BytecodeOperandIdxTaggedIndex(1);
  TNode<Uint32T> bytecode_flags = BytecodeOperandFlag8(2);
  TNode<ObjectBoilerplateDescription> object_boilerplate_description =
      CAST(LoadConstantPoolEntryAtOperandIndex(0));
  TNode<UintPtrT> flags_raw =
      DecodeWordFromWord32<CreateObjectLiteralFlags::FlagsBits>(bytecode_flags);
  TNode<Smi> flags = SmiTag(Signed(flags_raw));
  Label fast_shallow_clone(this), Slow_clone(this, Label::kDeferred),
      call_runtime(this, Label::kDeferred);
  // No feedback, so handle it as a slow case.
  GotoIf(IsUndefined(feedback_vector), &call_runtime);
  // Check if we can do a fast clone or have to call the runtime.
  Branch(IsSetWord32<CreateObjectLiteralFlags::FastCloneSupportedBit>(
             bytecode_flags),
         &fast_shallow_clone, &Slow_clone);
  BIND(&fast_shallow_clone);
  {
    // If we can do a fast clone do the fast-path in CreateShallowObjectLiteral.
    ConstructorBuiltinsAssembler constructor_assembler(state());
    TNode<HeapObject> result = constructor_assembler.CreateShallowObjectLiteral(
        CAST(feedback_vector), slot, &call_runtime);
    SetAccumulator(result);
    Dispatch();
  }
  BIND(&Slow_clone);
  {
    TNode<JSObject> result = CAST(CallBuiltin(
        Builtin::kCreateObjectFromSlowBoilerplate, context, feedback_vector,
        slot, object_boilerplate_description, flags));
    SetAccumulator(result);
    Dispatch();
  }
  BIND(&call_runtime);
  {
    TNode<Object> result =
        CallRuntime(Runtime::kCreateObjectLiteral, context, feedback_vector,
                    slot, object_boilerplate_description, flags);
    SetAccumulator(result);
    // TODO(klaasb) build a single dispatch once the call is inlined
    Dispatch();
  }
}
References CAST, v8::internal::ConstructorBuiltinsAssembler::CreateShallowObjectLiteral(), v8::internal::flags, v8::base::internal::result, and v8::base::bits::Signed().
IGNITION_HANDLER() [41/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (CreateRegExpLiteral , InterpreterAssembler)
Definition at line 2531 of file interpreter-generator.cc.
                                                            {
  TNode<String> pattern = CAST(LoadConstantPoolEntryAtOperandIndex(0));
  TNode<HeapObject> feedback_vector = LoadFeedbackVector();
  TNode<TaggedIndex> slot = BytecodeOperandIdxTaggedIndex(1);
  TNode<Smi> flags =
      SmiFromInt32(UncheckedCast<Int32T>(BytecodeOperandFlag16(2)));
  TNode<Context> context = GetContext();
  TVARIABLE(JSRegExp, result);
  ConstructorBuiltinsAssembler constructor_assembler(state());
  result = constructor_assembler.CreateRegExpLiteral(feedback_vector, slot,
                                                     pattern, flags, context);
  SetAccumulator(result.value());
  Dispatch();
}
References CAST, v8::internal::ConstructorBuiltinsAssembler::CreateRegExpLiteral(), v8::internal::flags, and v8::base::internal::result.
IGNITION_HANDLER() [42/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (CreateRestParameter , InterpreterAssembler)
Definition at line 2948 of file interpreter-generator.cc.
                                                            {
  TNode<JSFunction> closure = LoadFunctionClosure();
  TNode<Context> context = GetContext();
  TorqueGeneratedExportedMacrosAssembler builtins_assembler(state());
  TNode<JSObject> result =
      builtins_assembler.EmitFastNewRestArguments(context, closure);
  SetAccumulator(result);
  Dispatch();
}
References v8::base::internal::result.
IGNITION_HANDLER() [43/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (CreateUnmappedArguments , InterpreterAssembler)
Definition at line 2935 of file interpreter-generator.cc.
                                                                {
  TNode<Context> context = GetContext();
  TNode<JSFunction> closure = LoadFunctionClosure();
  TorqueGeneratedExportedMacrosAssembler builtins_assembler(state());
  TNode<JSObject> result =
      builtins_assembler.EmitFastNewStrictArguments(context, closure);
  SetAccumulator(result);
  Dispatch();
}
References v8::base::internal::result.
IGNITION_HANDLER() [44/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (CreateWithContext , InterpreterAssembler)
Definition at line 2885 of file interpreter-generator.cc.
                                                          {
  TNode<Object> object = LoadRegisterAtOperandIndex(0);
  TNode<ScopeInfo> scope_info = CAST(LoadConstantPoolEntryAtOperandIndex(1));
  TNode<Context> context = GetContext();
  SetAccumulator(
      CallRuntime(Runtime::kPushWithContext, context, object, scope_info));
  Dispatch();
}
References CAST.
IGNITION_HANDLER() [45/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (Debugger , InterpreterAssembler)
Definition at line 3135 of file interpreter-generator.cc.
                                                 {
  TNode<Context> context = GetContext();
  TNode<Object> result =
      CallRuntime(Runtime::kHandleDebuggerStatement, context);
  ClobberAccumulator(result);
  Dispatch();
}
References v8::base::internal::result.
IGNITION_HANDLER() [46/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (Dec , InterpreterAssembler)
Definition at line 1401 of file interpreter-generator.cc.
                                            {
  TNode<Object> value = GetAccumulator();
  TNode<Context> context = GetContext();
  TNode<UintPtrT> slot_index = BytecodeOperandIdx(0);
  TNode<Union<FeedbackVector, Undefined>> maybe_feedback_vector =
      LoadFeedbackVectorOrUndefinedIfJitless();
  static constexpr UpdateFeedbackMode mode = DefaultUpdateFeedbackMode();
  UnaryOpAssembler unary_op_asm(state());
  TNode<Object> result = unary_op_asm.Generate_DecrementWithFeedback(
      context, value, slot_index, maybe_feedback_vector, mode);
  SetAccumulator(result);
  Dispatch();
}
References v8::internal::UnaryOpAssembler::Generate_DecrementWithFeedback(), mode(), v8::base::internal::result, and v8::internal::value.
IGNITION_HANDLER() [47/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (DefineKeyedOwnProperty , InterpreterAssembler)
Definition at line 780 of file interpreter-generator.cc.
                                                               {
  TNode<Object> object = LoadRegisterAtOperandIndex(0);
  TNode<Object> name = LoadRegisterAtOperandIndex(1);
  TNode<Object> value = GetAccumulator();
  TNode<Smi> flags =
      SmiFromInt32(UncheckedCast<Int32T>(BytecodeOperandFlag8(2)));
  TNode<TaggedIndex> slot = BytecodeOperandIdxTaggedIndex(3);
  TNode<HeapObject> maybe_vector = LoadFeedbackVector();
  TNode<Context> context = GetContext();
  TNode<Object> result =
      CallBuiltin(Builtin::kDefineKeyedOwnIC, context, object, name, value,
                  flags, slot, maybe_vector);
  // To avoid special logic in the deoptimizer to re-materialize the value in
  // the accumulator, we clobber the accumulator after the IC call. It
  // doesn't really matter what we write to the accumulator here, since we
  // restore to the correct value on the outside. Storing the result means we
  // don't need to keep unnecessary state alive across the callstub.
  ClobberAccumulator(result);
  Dispatch();
}
References v8::internal::flags, v8::internal::name, v8::base::internal::result, and v8::internal::value.
IGNITION_HANDLER() [48/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (DefineKeyedOwnPropertyInLiteral , InterpreterAssembler)
Definition at line 834 of file interpreter-generator.cc.
                                                                        {
  TNode<Object> object = LoadRegisterAtOperandIndex(0);
  TNode<Object> name = LoadRegisterAtOperandIndex(1);
  TNode<Object> value = GetAccumulator();
  TNode<Smi> flags =
      SmiFromInt32(UncheckedCast<Int32T>(BytecodeOperandFlag8(2)));
  TNode<TaggedIndex> slot = BytecodeOperandIdxTaggedIndex(3);
  TNode<HeapObject> feedback_vector = LoadFeedbackVector();
  TNode<Context> context = GetContext();
  CallRuntime(Runtime::kDefineKeyedOwnPropertyInLiteral, context, object, name,
              value, flags, feedback_vector, slot);
  Dispatch();
}
References v8::internal::flags, v8::internal::name, and v8::internal::value.
IGNITION_HANDLER() [49/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (DefineNamedOwnProperty , InterpreterSetNamedPropertyAssembler)
Definition at line 738 of file interpreter-generator.cc.
                                                                               {
  SetNamedProperty(Builtin::kDefineNamedOwnIC, NamedPropertyType::kOwn);
}
References v8::internal::kOwn.
IGNITION_HANDLER() [50/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (DeletePropertySloppy , InterpreterAssembler)
Definition at line 1501 of file interpreter-generator.cc.
                                                             {
  TNode<Object> object = LoadRegisterAtOperandIndex(0);
  TNode<Object> key = GetAccumulator();
  TNode<Context> context = GetContext();
  TNode<Object> result =
      CallBuiltin(Builtin::kDeleteProperty, context, object, key,
                  SmiConstant(Smi::FromEnum(LanguageMode::kSloppy)));
  SetAccumulator(result);
  Dispatch();
}
References v8::internal::Smi::FromEnum(), v8::internal::key, v8::internal::kSloppy, and v8::base::internal::result.
IGNITION_HANDLER() [51/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (DeletePropertyStrict , InterpreterAssembler)
Definition at line 1486 of file interpreter-generator.cc.
                                                             {
  TNode<Object> object = LoadRegisterAtOperandIndex(0);
  TNode<Object> key = GetAccumulator();
  TNode<Context> context = GetContext();
  TNode<Object> result =
      CallBuiltin(Builtin::kDeleteProperty, context, object, key,
                  SmiConstant(Smi::FromEnum(LanguageMode::kStrict)));
  SetAccumulator(result);
  Dispatch();
}
References v8::internal::Smi::FromEnum(), v8::internal::key, v8::internal::kStrict, and v8::base::internal::result.
IGNITION_HANDLER() [52/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (Div , InterpreterBinaryOpAssembler)
Definition at line 1066 of file interpreter-generator.cc.
                                                    {
  BinaryOpWithFeedback(&BinaryOpAssembler::Generate_DivideWithFeedback);
}
References v8::internal::BinaryOpAssembler::Generate_DivideWithFeedback().
IGNITION_HANDLER() [53/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (DivSmi , InterpreterBinaryOpAssembler)
Definition at line 1108 of file interpreter-generator.cc.
                                                       {
  BinaryOpSmiWithFeedback(&BinaryOpAssembler::Generate_DivideWithFeedback);
}
References v8::internal::BinaryOpAssembler::Generate_DivideWithFeedback().
IGNITION_HANDLER() [54/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (Exp , InterpreterBinaryOpAssembler)
Definition at line 1080 of file interpreter-generator.cc.
                                                    {
  BinaryOpWithFeedback(&BinaryOpAssembler::Generate_ExponentiateWithFeedback);
}
References v8::internal::BinaryOpAssembler::Generate_ExponentiateWithFeedback().
IGNITION_HANDLER() [55/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (ExpSmi , InterpreterBinaryOpAssembler)
Definition at line 1122 of file interpreter-generator.cc.
                                                       {
  BinaryOpSmiWithFeedback(
      &BinaryOpAssembler::Generate_ExponentiateWithFeedback);
}
References v8::internal::BinaryOpAssembler::Generate_ExponentiateWithFeedback().
IGNITION_HANDLER() [56/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (ExtraWide , InterpreterAssembler)
Definition at line 3308 of file interpreter-generator.cc.
                                                  {
  DispatchWide(OperandScale::kQuadruple);
}
IGNITION_HANDLER() [57/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (FindNonDefaultConstructorOrConstruct , InterpreterAssembler)
Definition at line 3102 of file interpreter-generator.cc.
                                                                             {
  TNode<Context> context = GetContext();
  TVARIABLE(Object, constructor);
  Label found_default_base_ctor(this, &constructor),
      found_something_else(this, &constructor);
  TNode<JSFunction> this_function = CAST(LoadRegisterAtOperandIndex(0));
  FindNonDefaultConstructor(this_function, constructor,
                            &found_default_base_ctor, &found_something_else);
  BIND(&found_default_base_ctor);
  {
    // Create an object directly, without calling the default base ctor.
    TNode<Object> new_target = LoadRegisterAtOperandIndex(1);
    TNode<Object> instance = CallBuiltin(Builtin::kFastNewObject, context,
                                         constructor.value(), new_target);
    StoreRegisterPairAtOperandIndex(TrueConstant(), instance, 2);
    Dispatch();
  }
  BIND(&found_something_else);
  {
    // Not a base ctor (or bailed out).
    StoreRegisterPairAtOperandIndex(FalseConstant(), constructor.value(), 2);
    Dispatch();
  }
}
References CAST.
IGNITION_HANDLER() [58/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (ForInEnumerate , InterpreterAssembler)
Definition at line 3179 of file interpreter-generator.cc.
                                                       {
  TNode<JSReceiver> receiver = CAST(LoadRegisterAtOperandIndex(0));
  TNode<Context> context = GetContext();
  Label if_empty(this), if_runtime(this, Label::kDeferred);
  TNode<Map> receiver_map = CheckEnumCache(receiver, &if_empty, &if_runtime);
  SetAccumulator(receiver_map);
  Dispatch();
  BIND(&if_empty);
  {
    TNode<FixedArray> result = EmptyFixedArrayConstant();
    SetAccumulator(result);
    Dispatch();
  }
  BIND(&if_runtime);
  {
    TNode<Object> result =
        CallRuntime(Runtime::kForInEnumerate, context, receiver);
    SetAccumulator(result);
    Dispatch();
  }
}
References CAST, and v8::base::internal::result.
IGNITION_HANDLER() [59/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (ForInNext , InterpreterAssembler)
Definition at line 3234 of file interpreter-generator.cc.
                                                  {
  TNode<JSAnyNotSmi> receiver = CAST(LoadRegisterAtOperandIndex(0));
  TNode<Smi> index = CAST(LoadRegisterAtOperandIndex(1));
  TNode<Object> cache_type;
  TNode<Object> cache_array;
  std::tie(cache_type, cache_array) = LoadRegisterPairAtOperandIndex(2);
  TNode<UintPtrT> vector_index = BytecodeOperandIdx(3);
  TNode<Union<FeedbackVector, Undefined>> maybe_feedback_vector =
      LoadFeedbackVector();
  // Load the next key from the enumeration array.
  TNode<JSAny> key = CAST(LoadFixedArrayElement(CAST(cache_array), index, 0));
  // Check if we can use the for-in fast path potentially using the enum cache.
  Label if_fast(this), if_slow(this, Label::kDeferred);
  TNode<Map> receiver_map = LoadMap(receiver);
  Branch(TaggedEqual(receiver_map, cache_type), &if_fast, &if_slow);
  BIND(&if_fast);
  {
    // Enum cache in use for {receiver}, the {key} is definitely valid.
    SetAccumulator(key);
    Dispatch();
  }
  BIND(&if_slow);
  {
    TNode<Object> result = ForInNextSlow(GetContext(), vector_index, receiver,
                                         key, cache_type, maybe_feedback_vector,
                                         UpdateFeedbackMode::kOptionalFeedback);
    SetAccumulator(result);
    Dispatch();
  }
}
References CAST, v8::internal::index, v8::internal::key, v8::internal::kOptionalFeedback, and v8::base::internal::result.
IGNITION_HANDLER() [60/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (ForInPrepare , InterpreterAssembler)
Definition at line 3212 of file interpreter-generator.cc.
                                                     {
  // The {enumerator} is either a Map or a FixedArray.
  TNode<HeapObject> enumerator = CAST(GetAccumulator());
  TNode<UintPtrT> vector_index = BytecodeOperandIdx(1);
  TNode<Union<FeedbackVector, Undefined>> maybe_feedback_vector =
      LoadFeedbackVector();
  TNode<HeapObject> cache_type = enumerator; // Just to clarify the rename.
  TNode<FixedArray> cache_array;
  TNode<Smi> cache_length;
  ForInPrepare(enumerator, vector_index, maybe_feedback_vector, &cache_array,
               &cache_length, UpdateFeedbackMode::kOptionalFeedback);
  ClobberAccumulator(SmiConstant(0));
  StoreRegisterTripleAtOperandIndex(cache_type, cache_array, cache_length, 0);
  Dispatch();
}
References CAST, and v8::internal::kOptionalFeedback.
IGNITION_HANDLER() [61/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (ForInStep , InterpreterAssembler)
Definition at line 3271 of file interpreter-generator.cc.
                                                  {
  TNode<Smi> index = CAST(LoadRegisterAtOperandIndex(0));
  TNode<Smi> one = SmiConstant(1);
  TNode<Smi> result = SmiAdd(index, one);
  StoreRegisterAtOperandIndex(result, 0);
  Dispatch();
}
References CAST, v8::internal::index, one, and v8::base::internal::result.
IGNITION_HANDLER() [62/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (GetEnumeratedKeyedProperty , InterpreterAssembler)
Definition at line 676 of file interpreter-generator.cc.
                                                                   {
  TNode<Object> object = LoadRegisterAtOperandIndex(0);
  TNode<Object> name = GetAccumulator();
  TNode<Smi> enum_index = CAST(LoadRegisterAtOperandIndex(1));
  TNode<Object> cache_type = LoadRegisterAtOperandIndex(2);
  TNode<TaggedIndex> slot = BytecodeOperandIdxTaggedIndex(3);
  TNode<HeapObject> feedback_vector = LoadFeedbackVector();
  TNode<Context> context = GetContext();
  TVARIABLE(Object, var_result);
  var_result = CallBuiltin(Builtin::kEnumeratedKeyedLoadIC, context, object,
                           name, enum_index, cache_type, slot, feedback_vector);
  SetAccumulator(var_result.value());
  Dispatch();
}
References CAST, and v8::internal::name.
IGNITION_HANDLER() [63/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (GetIterator , InterpreterAssembler)
Definition at line 3284 of file interpreter-generator.cc.
                                                    {
  TNode<Object> receiver = LoadRegisterAtOperandIndex(0);
  TNode<Context> context = GetContext();
  TNode<HeapObject> feedback_vector = LoadFeedbackVector();
  TNode<TaggedIndex> load_slot = BytecodeOperandIdxTaggedIndex(1);
  TNode<TaggedIndex> call_slot = BytecodeOperandIdxTaggedIndex(2);
  TNode<Object> iterator =
      CallBuiltin(Builtin::kGetIteratorWithFeedback, context, receiver,
                  load_slot, call_slot, feedback_vector);
  SetAccumulator(iterator);
  Dispatch();
}
IGNITION_HANDLER() [64/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (GetKeyedProperty , InterpreterAssembler)
Definition at line 657 of file interpreter-generator.cc.
                                                         {
  TNode<Object> object = LoadRegisterAtOperandIndex(0);
  TNode<Object> name = GetAccumulator();
  TNode<TaggedIndex> slot = BytecodeOperandIdxTaggedIndex(1);
  TNode<HeapObject> feedback_vector = LoadFeedbackVector();
  TNode<Context> context = GetContext();
  TVARIABLE(Object, var_result);
  var_result = CallBuiltin(Builtin::kKeyedLoadIC, context, object, name, slot,
                           feedback_vector);
  SetAccumulator(var_result.value());
  Dispatch();
}
References v8::internal::name.
IGNITION_HANDLER() [65/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (GetNamedProperty , InterpreterAssembler)
Definition at line 601 of file interpreter-generator.cc.
                                                         {
  TNode<HeapObject> feedback_vector = LoadFeedbackVector();
  // Load receiver.
  TNode<JSAny> recv = CAST(LoadRegisterAtOperandIndex(0));
  // Load the name and context lazily.
  LazyNode<TaggedIndex> lazy_slot = [=, this] {
    return BytecodeOperandIdxTaggedIndex(2);
  };
  LazyNode<Name> lazy_name = [=, this] {
    return CAST(LoadConstantPoolEntryAtOperandIndex(1));
  };
  LazyNode<Context> lazy_context = [=, this] { return GetContext(); };
  Label done(this);
  TVARIABLE(Object, var_result);
  ExitPoint exit_point(this, &done, &var_result);
  AccessorAssembler::LazyLoadICParameters params(lazy_context, recv, lazy_name,
                                                 lazy_slot, feedback_vector);
  AccessorAssembler accessor_asm(state());
  accessor_asm.LoadIC_BytecodeHandler(&params, &exit_point);
  BIND(&done);
  {
    SetAccumulator(var_result.value());
    Dispatch();
  }
}
References CAST, and v8::internal::AccessorAssembler::LoadIC_BytecodeHandler().
IGNITION_HANDLER() [66/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (GetNamedPropertyFromSuper , InterpreterAssembler)
Definition at line 637 of file interpreter-generator.cc.
                                                                  {
  TNode<Object> receiver = LoadRegisterAtOperandIndex(0);
  TNode<HeapObject> home_object = CAST(GetAccumulator());
  TNode<Object> home_object_prototype = LoadMapPrototype(LoadMap(home_object));
  TNode<Object> name = LoadConstantPoolEntryAtOperandIndex(1);
  TNode<TaggedIndex> slot = BytecodeOperandIdxTaggedIndex(2);
  TNode<HeapObject> feedback_vector = LoadFeedbackVector();
  TNode<Context> context = GetContext();
  TNode<Object> result =
      CallBuiltin(Builtin::kLoadSuperIC, context, receiver,
                  home_object_prototype, name, slot, feedback_vector);
  SetAccumulator(result);
  Dispatch();
}
References CAST, v8::internal::name, and v8::base::internal::result.
IGNITION_HANDLER() [67/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (GetSuperConstructor , InterpreterAssembler)
Definition at line 1516 of file interpreter-generator.cc.
                                                            {
  TNode<JSFunction> active_function = CAST(GetAccumulator());
  TNode<Object> result = GetSuperConstructor(active_function);
  StoreRegisterAtOperandIndex(result, 0);
  Dispatch();
}
References CAST, and v8::base::internal::result.
IGNITION_HANDLER() [68/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (GetTemplateObject , InterpreterAssembler)
Definition at line 2746 of file interpreter-generator.cc.
                                                          {
  TNode<Context> context = GetContext();
  TNode<JSFunction> closure = LoadFunctionClosure();
  TNode<SharedFunctionInfo> shared_info = LoadObjectField<SharedFunctionInfo>(
      closure, JSFunction::kSharedFunctionInfoOffset);
  TNode<Object> description = LoadConstantPoolEntryAtOperandIndex(0);
  TNode<UintPtrT> slot = BytecodeOperandIdx(1);
  TNode<Union<FeedbackVector, Undefined>> maybe_feedback_vector =
      LoadFeedbackVector();
  TNode<Object> result =
      CallBuiltin(Builtin::kGetTemplateObject, context, shared_info,
                  description, slot, maybe_feedback_vector);
  SetAccumulator(result);
  Dispatch();
}
References v8::base::internal::result.
IGNITION_HANDLER() [69/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (Illegal , InterpreterAssembler)
Definition at line 3315 of file interpreter-generator.cc.
                                                {
  Abort(AbortReason::kInvalidBytecode);
  Unreachable();
}
IGNITION_HANDLER() [70/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (Inc , InterpreterAssembler)
Definition at line 1382 of file interpreter-generator.cc.
                                            {
  TNode<Object> value = GetAccumulator();
  TNode<Context> context = GetContext();
  TNode<UintPtrT> slot_index = BytecodeOperandIdx(0);
  TNode<Union<FeedbackVector, Undefined>> maybe_feedback_vector =
      LoadFeedbackVectorOrUndefinedIfJitless();
  static constexpr UpdateFeedbackMode mode = DefaultUpdateFeedbackMode();
  UnaryOpAssembler unary_op_asm(state());
  TNode<Object> result = unary_op_asm.Generate_IncrementWithFeedback(
      context, value, slot_index, maybe_feedback_vector, mode);
  SetAccumulator(result);
  Dispatch();
}
References v8::internal::UnaryOpAssembler::Generate_IncrementWithFeedback(), mode(), v8::base::internal::result, and v8::internal::value.
IGNITION_HANDLER() [71/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (IncBlockCounter , InterpreterAssembler)
Definition at line 3164 of file interpreter-generator.cc.
                                                        {
  TNode<JSFunction> closure = LoadFunctionClosure();
  TNode<Smi> coverage_array_slot = BytecodeOperandIdxSmi(0);
  TNode<Context> context = GetContext();
  CallBuiltin(Builtin::kIncBlockCounter, context, closure, coverage_array_slot);
  Dispatch();
}
IGNITION_HANDLER() [72/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (InvokeIntrinsic , InterpreterAssembler)
Definition at line 1670 of file interpreter-generator.cc.
                                                        {
  TNode<Uint32T> function_id = BytecodeOperandIntrinsicId(0);
  RegListNodePair args = GetRegisterListAtOperandIndex(1);
  TNode<Context> context = GetContext();
  TNode<Object> result =
      GenerateInvokeIntrinsic(this, function_id, context, args);
  SetAccumulator(result);
  Dispatch();
}
References v8::base::args, v8::internal::interpreter::GenerateInvokeIntrinsic(), and v8::base::internal::result.
IGNITION_HANDLER() [73/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (Jump , InterpreterAssembler)
Definition at line 2105 of file interpreter-generator.cc.
                                             {
  TNode<IntPtrT> relative_jump = Signed(BytecodeOperandUImmWord(0));
  Jump(relative_jump);
}
References v8::base::bits::Signed().
IGNITION_HANDLER() [74/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (JumpConstant , InterpreterAssembler)
Definition at line 2114 of file interpreter-generator.cc.
                                                     {
  TNode<IntPtrT> relative_jump = LoadAndUntagConstantPoolEntryAtOperandIndex(0);
  Jump(relative_jump);
}
IGNITION_HANDLER() [75/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (JumpIfFalse , InterpreterAssembler)
Definition at line 2146 of file interpreter-generator.cc.
                                                    {
  TNode<Object> accumulator = GetAccumulator();
  CSA_DCHECK(this, IsBoolean(CAST(accumulator)));
  JumpIfTaggedEqual(accumulator, FalseConstant(), 0);
}
References CAST.
IGNITION_HANDLER() [76/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (JumpIfFalseConstant , InterpreterAssembler)
Definition at line 2157 of file interpreter-generator.cc.
                                                            {
  TNode<Object> accumulator = GetAccumulator();
  CSA_DCHECK(this, IsBoolean(CAST(accumulator)));
  JumpIfTaggedEqualConstant(accumulator, FalseConstant(), 0);
}
References CAST.
IGNITION_HANDLER() [77/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (JumpIfForInDone , InterpreterAssembler)
Definition at line 2378 of file interpreter-generator.cc.
                                                        {
  TNode<Object> index = LoadRegisterAtOperandIndex(1);
  TNode<Object> cache_length = LoadRegisterAtOperandIndex(2);
  // Check if {index} is at {cache_length} already.
  Label if_done(this), if_not_done(this), end(this);
  Branch(TaggedEqual(index, cache_length), &if_done, &if_not_done);
  BIND(&if_done);
  TNode<IntPtrT> relative_jump = Signed(BytecodeOperandUImmWord(0));
  Jump(relative_jump);
  BIND(&if_not_done);
  Dispatch();
}
References v8::internal::compiler::end(), v8::internal::index, and v8::base::bits::Signed().
IGNITION_HANDLER() [78/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (JumpIfForInDoneConstant , InterpreterAssembler)
Definition at line 2398 of file interpreter-generator.cc.
                                                                {
  TNode<Object> index = LoadRegisterAtOperandIndex(1);
  TNode<Object> cache_length = LoadRegisterAtOperandIndex(2);
  // Check if {index} is at {cache_length} already.
  Label if_done(this), if_not_done(this), end(this);
  Branch(TaggedEqual(index, cache_length), &if_done, &if_not_done);
  BIND(&if_done);
  TNode<IntPtrT> relative_jump = LoadAndUntagConstantPoolEntryAtOperandIndex(0);
  Jump(relative_jump);
  BIND(&if_not_done);
  Dispatch();
}
References v8::internal::compiler::end(), and v8::internal::index.
IGNITION_HANDLER() [79/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (JumpIfJSReceiver , InterpreterAssembler)
Definition at line 2337 of file interpreter-generator.cc.
                                                         {
  TNode<Object> accumulator = GetAccumulator();
  Label if_object(this), if_notobject(this, Label::kDeferred), if_notsmi(this);
  Branch(TaggedIsSmi(accumulator), &if_notobject, &if_notsmi);
  BIND(&if_notsmi);
  Branch(IsJSReceiver(CAST(accumulator)), &if_object, &if_notobject);
  BIND(&if_object);
  TNode<IntPtrT> relative_jump = Signed(BytecodeOperandUImmWord(0));
  Jump(relative_jump);
  BIND(&if_notobject);
  Dispatch();
}
References CAST, and v8::base::bits::Signed().
IGNITION_HANDLER() [80/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (JumpIfJSReceiverConstant , InterpreterAssembler)
Definition at line 2357 of file interpreter-generator.cc.
                                                                 {
  TNode<Object> accumulator = GetAccumulator();
  Label if_object(this), if_notobject(this), if_notsmi(this);
  Branch(TaggedIsSmi(accumulator), &if_notobject, &if_notsmi);
  BIND(&if_notsmi);
  Branch(IsJSReceiver(CAST(accumulator)), &if_object, &if_notobject);
  BIND(&if_object);
  TNode<IntPtrT> relative_jump = LoadAndUntagConstantPoolEntryAtOperandIndex(0);
  Jump(relative_jump);
  BIND(&if_notobject);
  Dispatch();
}
References CAST.
IGNITION_HANDLER() [81/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (JumpIfNotNull , InterpreterAssembler)
Definition at line 2247 of file interpreter-generator.cc.
                                                      {
  TNode<Object> accumulator = GetAccumulator();
  JumpIfTaggedNotEqual(accumulator, NullConstant(), 0);
}
IGNITION_HANDLER() [82/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (JumpIfNotNullConstant , InterpreterAssembler)
Definition at line 2256 of file interpreter-generator.cc.
                                                              {
  TNode<Object> accumulator = GetAccumulator();
  JumpIfTaggedNotEqualConstant(accumulator, NullConstant(), 0);
}
IGNITION_HANDLER() [83/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (JumpIfNotUndefined , InterpreterAssembler)
Definition at line 2283 of file interpreter-generator.cc.
                                                           {
  TNode<Object> accumulator = GetAccumulator();
  JumpIfTaggedNotEqual(accumulator, UndefinedConstant(), 0);
}
References v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant().
IGNITION_HANDLER() [84/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (JumpIfNotUndefinedConstant , InterpreterAssembler)
Definition at line 2293 of file interpreter-generator.cc.
                                                                   {
  TNode<Object> accumulator = GetAccumulator();
  JumpIfTaggedNotEqualConstant(accumulator, UndefinedConstant(), 0);
}
References v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant().
IGNITION_HANDLER() [85/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (JumpIfNull , InterpreterAssembler)
Definition at line 2229 of file interpreter-generator.cc.
                                                   {
  TNode<Object> accumulator = GetAccumulator();
  JumpIfTaggedEqual(accumulator, NullConstant(), 0);
}
IGNITION_HANDLER() [86/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (JumpIfNullConstant , InterpreterAssembler)
Definition at line 2238 of file interpreter-generator.cc.
                                                           {
  TNode<Object> accumulator = GetAccumulator();
  JumpIfTaggedEqualConstant(accumulator, NullConstant(), 0);
}
IGNITION_HANDLER() [87/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (JumpIfToBooleanFalse , InterpreterAssembler)
Definition at line 2198 of file interpreter-generator.cc.
                                                             {
  TNode<Object> value = GetAccumulator();
  Label if_true(this), if_false(this);
  BranchIfToBooleanIsTrue(value, &if_true, &if_false);
  BIND(&if_true);
  Dispatch();
  BIND(&if_false);
  TNode<IntPtrT> relative_jump = Signed(BytecodeOperandUImmWord(0));
  Jump(relative_jump);
}
References v8::base::bits::Signed(), and v8::internal::value.
IGNITION_HANDLER() [88/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (JumpIfToBooleanFalseConstant , InterpreterAssembler)
Definition at line 2214 of file interpreter-generator.cc.
                                                                     {
  TNode<Object> value = GetAccumulator();
  Label if_true(this), if_false(this);
  BranchIfToBooleanIsTrue(value, &if_true, &if_false);
  BIND(&if_true);
  Dispatch();
  BIND(&if_false);
  TNode<IntPtrT> relative_jump = LoadAndUntagConstantPoolEntryAtOperandIndex(0);
  Jump(relative_jump);
}
References v8::internal::value.
IGNITION_HANDLER() [89/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (JumpIfToBooleanTrue , InterpreterAssembler)
Definition at line 2167 of file interpreter-generator.cc.
                                                            {
  TNode<Object> value = GetAccumulator();
  Label if_true(this), if_false(this);
  BranchIfToBooleanIsTrue(value, &if_true, &if_false);
  BIND(&if_true);
  TNode<IntPtrT> relative_jump = Signed(BytecodeOperandUImmWord(0));
  Jump(relative_jump);
  BIND(&if_false);
  Dispatch();
}
References v8::base::bits::Signed(), and v8::internal::value.
IGNITION_HANDLER() [90/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (JumpIfToBooleanTrueConstant , InterpreterAssembler)
Definition at line 2183 of file interpreter-generator.cc.
                                                                    {
  TNode<Object> value = GetAccumulator();
  Label if_true(this), if_false(this);
  BranchIfToBooleanIsTrue(value, &if_true, &if_false);
  BIND(&if_true);
  TNode<IntPtrT> relative_jump = LoadAndUntagConstantPoolEntryAtOperandIndex(0);
  Jump(relative_jump);
  BIND(&if_false);
  Dispatch();
}
References v8::internal::value.
IGNITION_HANDLER() [91/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (JumpIfTrue , InterpreterAssembler)
Definition at line 2124 of file interpreter-generator.cc.
                                                   {
  TNode<Object> accumulator = GetAccumulator();
  CSA_DCHECK(this, IsBoolean(CAST(accumulator)));
  JumpIfTaggedEqual(accumulator, TrueConstant(), 0);
}
References CAST.
IGNITION_HANDLER() [92/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (JumpIfTrueConstant , InterpreterAssembler)
Definition at line 2135 of file interpreter-generator.cc.
                                                           {
  TNode<Object> accumulator = GetAccumulator();
  CSA_DCHECK(this, IsBoolean(CAST(accumulator)));
  JumpIfTaggedEqualConstant(accumulator, TrueConstant(), 0);
}
References CAST.
IGNITION_HANDLER() [93/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (JumpIfUndefined , InterpreterAssembler)
Definition at line 2265 of file interpreter-generator.cc.
                                                        {
  TNode<Object> accumulator = GetAccumulator();
  JumpIfTaggedEqual(accumulator, UndefinedConstant(), 0);
}
References v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant().
IGNITION_HANDLER() [94/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (JumpIfUndefinedConstant , InterpreterAssembler)
Definition at line 2274 of file interpreter-generator.cc.
                                                                {
  TNode<Object> accumulator = GetAccumulator();
  JumpIfTaggedEqualConstant(accumulator, UndefinedConstant(), 0);
}
References v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant().
IGNITION_HANDLER() [95/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (JumpIfUndefinedOrNull , InterpreterAssembler)
Definition at line 2302 of file interpreter-generator.cc.
                                                              {
  TNode<Object> accumulator = GetAccumulator();
  Label do_jump(this);
  GotoIf(IsUndefined(accumulator), &do_jump);
  GotoIf(IsNull(accumulator), &do_jump);
  Dispatch();
  BIND(&do_jump);
  TNode<IntPtrT> relative_jump = Signed(BytecodeOperandUImmWord(0));
  Jump(relative_jump);
}
References v8::internal::IsNull(), and v8::base::bits::Signed().
IGNITION_HANDLER() [96/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (JumpIfUndefinedOrNullConstant , InterpreterAssembler)
Definition at line 2320 of file interpreter-generator.cc.
                                                                      {
  TNode<Object> accumulator = GetAccumulator();
  Label do_jump(this);
  GotoIf(IsUndefined(accumulator), &do_jump);
  GotoIf(IsNull(accumulator), &do_jump);
  Dispatch();
  BIND(&do_jump);
  TNode<IntPtrT> relative_jump = LoadAndUntagConstantPoolEntryAtOperandIndex(0);
  Jump(relative_jump);
}
References v8::internal::IsNull().
IGNITION_HANDLER() [97/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (JumpLoop , InterpreterAssembler)
Definition at line 2418 of file interpreter-generator.cc.
                                                 {
  TNode<IntPtrT> relative_jump = Signed(BytecodeOperandUImmWord(0));
  ClobberAccumulator(UndefinedConstant());
#ifndef V8_JITLESS
  TVARIABLE(HeapObject, maybe_feedback_vector);
  Label ok(this);
  Label fbv_loaded(this);
  // Load FeedbackVector from Cache.
  maybe_feedback_vector = LoadFeedbackVector();
  // If cache is empty, try to load from function closure.
  GotoIfNot(IsUndefined(maybe_feedback_vector.value()), &fbv_loaded);
  maybe_feedback_vector =
      CodeStubAssembler::LoadFeedbackVector(LoadFunctionClosure(), &ok);
  // Update feedback vector stack cache.
  StoreRegister(maybe_feedback_vector.value(), Register::feedback_vector());
  Goto(&fbv_loaded);
  BIND(&fbv_loaded);
  TNode<FeedbackVector> feedback_vector = CAST(maybe_feedback_vector.value());
  TNode<Int8T> osr_state = LoadOsrState(feedback_vector);
  TNode<Int32T> loop_depth = BytecodeOperandImm(1);
  Label maybe_osr_because_osr_state(this, Label::kDeferred);
  // The quick initial OSR check. If it passes, we proceed on to more expensive
  // OSR logic.
  static_assert(FeedbackVector::MaybeHasMaglevOsrCodeBit::encode(true) >
                FeedbackVector::kMaxOsrUrgency);
  static_assert(FeedbackVector::MaybeHasTurbofanOsrCodeBit::encode(true) >
                FeedbackVector::kMaxOsrUrgency);
  GotoIfNot(Uint32GreaterThanOrEqual(loop_depth, osr_state),
            &maybe_osr_because_osr_state);
  // Perhaps we've got cached baseline code?
  Label maybe_osr_because_baseline(this);
  TNode<SharedFunctionInfo> sfi = LoadObjectField<SharedFunctionInfo>(
      LoadFunctionClosure(), JSFunction::kSharedFunctionInfoOffset);
  Branch(SharedFunctionInfoHasBaselineCode(sfi), &maybe_osr_because_baseline,
         &ok);
  BIND(&ok);
#endif // !V8_JITLESS
  // The backward jump can trigger a budget interrupt, which can handle stack
  // interrupts, so we don't need to explicitly handle them here.
  JumpBackward(relative_jump);
#ifndef V8_JITLESS
  BIND(&maybe_osr_because_baseline);
  {
    TNode<Context> context = GetContext();
    TNode<IntPtrT> slot_index = Signed(BytecodeOperandIdx(2));
    OnStackReplacement(context, feedback_vector, relative_jump, loop_depth,
                       slot_index, osr_state,
                       OnStackReplacementParams::kBaselineCodeIsCached);
  }
  BIND(&maybe_osr_because_osr_state);
  {
    TNode<Context> context = GetContext();
    TNode<IntPtrT> slot_index = Signed(BytecodeOperandIdx(2));
    OnStackReplacement(context, feedback_vector, relative_jump, loop_depth,
                       slot_index, osr_state,
                       OnStackReplacementParams::kDefault);
  }
#endif // !V8_JITLESS
}
References CAST, v8::internal::interpreter::Register::feedback_vector(), v8::internal::FeedbackVector::kMaxOsrUrgency, v8::internal::CodeStubAssembler::LoadFeedbackVector(), v8::internal::anonymous_namespace{builtins-riscv.cc}::OnStackReplacement(), v8::base::bits::Signed(), and v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant().
IGNITION_HANDLER() [98/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (LdaConstant , InterpreterAssembler)
Definition at line 88 of file interpreter-generator.cc.
                                                    {
  TNode<Object> constant = LoadConstantPoolEntryAtOperandIndex(0);
  SetAccumulator(constant);
  Dispatch();
}
IGNITION_HANDLER() [99/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (LdaContextSlot , InterpreterAssembler)
Definition at line 274 of file interpreter-generator.cc.
                                                       {
  TNode<Context> context = CAST(LoadRegisterAtOperandIndex(0));
  TNode<IntPtrT> slot_index = Signed(BytecodeOperandIdx(1));
  TNode<Uint32T> depth = BytecodeOperandUImm(2);
  TNode<Context> slot_context = GetContextAtDepth(context, depth);
  TNode<Object> result = LoadContextElement(slot_context, slot_index);
  SetAccumulator(result);
  Dispatch();
}
References CAST, v8::base::internal::result, and v8::base::bits::Signed().
IGNITION_HANDLER() [100/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (LdaContextSlotNoCell , InterpreterAssembler)
Definition at line 260 of file interpreter-generator.cc.
                                                             {
  TNode<Context> context = CAST(LoadRegisterAtOperandIndex(0));
  TNode<IntPtrT> slot_index = Signed(BytecodeOperandIdx(1));
  TNode<Uint32T> depth = BytecodeOperandUImm(2);
  TNode<Context> slot_context = GetContextAtDepth(context, depth);
  TNode<Object> result = LoadContextElementNoCell(slot_context, slot_index);
  SetAccumulator(result);
  Dispatch();
}
References CAST, v8::base::internal::result, and v8::base::bits::Signed().
IGNITION_HANDLER() [101/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (LdaCurrentContextSlot , InterpreterAssembler)
Definition at line 312 of file interpreter-generator.cc.
                                                              {
  TNode<IntPtrT> slot_index = Signed(BytecodeOperandIdx(0));
  TNode<Context> slot_context = GetContext();
  TNode<Object> result = LoadContextElement(slot_context, slot_index);
  SetAccumulator(result);
  Dispatch();
}
References v8::base::internal::result, and v8::base::bits::Signed().
IGNITION_HANDLER() [102/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (LdaCurrentContextSlotNoCell , InterpreterAssembler)
Definition at line 301 of file interpreter-generator.cc.
                                                                    {
  TNode<IntPtrT> slot_index = Signed(BytecodeOperandIdx(0));
  TNode<Context> slot_context = GetContext();
  TNode<Object> result = LoadContextElementNoCell(slot_context, slot_index);
  SetAccumulator(result);
  Dispatch();
}
References v8::base::internal::result, and v8::base::bits::Signed().
IGNITION_HANDLER() [103/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (LdaFalse , InterpreterAssembler)
Definition at line 129 of file interpreter-generator.cc.
                                                 {
  SetAccumulator(FalseConstant());
  Dispatch();
}
IGNITION_HANDLER() [104/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (LdaGlobal , InterpreterLoadGlobalAssembler)
Definition at line 213 of file interpreter-generator.cc.
                                                            {
  static const int kNameOperandIndex = 0;
  static const int kSlotOperandIndex = 1;
  LdaGlobal(kSlotOperandIndex, kNameOperandIndex, TypeofMode::kNotInside);
}
References v8::internal::kNotInside.
IGNITION_HANDLER() [105/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (LdaGlobalInsideTypeof , InterpreterLoadGlobalAssembler)
Definition at line 224 of file interpreter-generator.cc.
                                                                        {
  static const int kNameOperandIndex = 0;
  static const int kSlotOperandIndex = 1;
  LdaGlobal(kSlotOperandIndex, kNameOperandIndex, TypeofMode::kInside);
}
References v8::internal::kInside.
IGNITION_HANDLER() [106/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (LdaImmutableContextSlot , InterpreterAssembler)
Definition at line 288 of file interpreter-generator.cc.
                                                                {
  TNode<Context> context = CAST(LoadRegisterAtOperandIndex(0));
  TNode<IntPtrT> slot_index = Signed(BytecodeOperandIdx(1));
  TNode<Uint32T> depth = BytecodeOperandUImm(2);
  TNode<Context> slot_context = GetContextAtDepth(context, depth);
  TNode<Object> result = LoadContextElementNoCell(slot_context, slot_index);
  SetAccumulator(result);
  Dispatch();
}
References CAST, v8::base::internal::result, and v8::base::bits::Signed().
IGNITION_HANDLER() [107/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (LdaImmutableCurrentContextSlot , InterpreterAssembler)
Definition at line 323 of file interpreter-generator.cc.
                                                                       {
  TNode<IntPtrT> slot_index = Signed(BytecodeOperandIdx(0));
  TNode<Context> slot_context = GetContext();
  TNode<Object> result = LoadContextElementNoCell(slot_context, slot_index);
  SetAccumulator(result);
  Dispatch();
}
References v8::base::internal::result, and v8::base::bits::Signed().
IGNITION_HANDLER() [108/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (LdaLookupContextSlot , InterpreterLookupContextSlotAssembler)
Definition at line 460 of file interpreter-generator.cc.
                                                                              {
  LookupContextSlot(Runtime::kLoadLookupSlot, ContextMode::kHasContextCells);
}
References v8::internal::kHasContextCells.
IGNITION_HANDLER() [109/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (LdaLookupContextSlotInsideTypeof , InterpreterLookupContextSlotAssembler)
Definition at line 478 of file interpreter-generator.cc.
                                                        {
  LookupContextSlot(Runtime::kLoadLookupSlotInsideTypeof,
                    ContextMode::kHasContextCells);
}
References v8::internal::kHasContextCells.
IGNITION_HANDLER() [110/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (LdaLookupContextSlotNoCell , InterpreterLookupContextSlotAssembler)
Definition at line 451 of file interpreter-generator.cc.
                                                        {
  LookupContextSlot(Runtime::kLoadLookupSlot, ContextMode::kNoContextCells);
}
References v8::internal::kNoContextCells.
IGNITION_HANDLER() [111/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (LdaLookupContextSlotNoCellInsideTypeof , InterpreterLookupContextSlotAssembler)
Definition at line 468 of file interpreter-generator.cc.
                                                        {
  LookupContextSlot(Runtime::kLoadLookupSlotInsideTypeof,
                    ContextMode::kNoContextCells);
}
References v8::internal::kNoContextCells.
IGNITION_HANDLER() [112/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (LdaLookupGlobalSlot , InterpreterLookupGlobalAssembler)
Definition at line 527 of file interpreter-generator.cc.
                                                                        {
  LookupGlobalSlot(Runtime::kLoadLookupSlot);
}
IGNITION_HANDLER() [113/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (LdaLookupGlobalSlotInsideTypeof , InterpreterLookupGlobalAssembler)
Definition at line 535 of file interpreter-generator.cc.
                                                   {
  LookupGlobalSlot(Runtime::kLoadLookupSlotInsideTypeof);
}
IGNITION_HANDLER() [114/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (LdaLookupSlot , InterpreterAssembler)
Definition at line 387 of file interpreter-generator.cc.
                                                      {
  TNode<Name> name = CAST(LoadConstantPoolEntryAtOperandIndex(0));
  TNode<Context> context = GetContext();
  TNode<Object> result = CallRuntime(Runtime::kLoadLookupSlot, context, name);
  SetAccumulator(result);
  Dispatch();
}
References CAST, v8::internal::name, and v8::base::internal::result.
IGNITION_HANDLER() [115/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (LdaLookupSlotInsideTypeof , InterpreterAssembler)
Definition at line 399 of file interpreter-generator.cc.
                                                                  {
  TNode<Name> name = CAST(LoadConstantPoolEntryAtOperandIndex(0));
  TNode<Context> context = GetContext();
  TNode<Object> result =
      CallRuntime(Runtime::kLoadLookupSlotInsideTypeof, context, name);
  SetAccumulator(result);
  Dispatch();
}
References CAST, v8::internal::name, and v8::base::internal::result.
IGNITION_HANDLER() [116/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (LdaModuleVariable , InterpreterAssembler)
Definition at line 855 of file interpreter-generator.cc.
                                                          {
  TNode<IntPtrT> cell_index = BytecodeOperandImmIntPtr(0);
  TNode<Uint32T> depth = BytecodeOperandUImm(1);
  TNode<Context> module_context = GetContextAtDepth(GetContext(), depth);
  TNode<SourceTextModule> module =
      CAST(LoadContextElementNoCell(module_context, Context::EXTENSION_INDEX));
  Label if_export(this), if_import(this), end(this);
  Branch(IntPtrGreaterThan(cell_index, IntPtrConstant(0)), &if_export,
         &if_import);
  BIND(&if_export);
  {
    TNode<FixedArray> regular_exports = LoadObjectField<FixedArray>(
        module, SourceTextModule::kRegularExportsOffset);
    // The actual array index is (cell_index - 1).
    TNode<IntPtrT> export_index = IntPtrSub(cell_index, IntPtrConstant(1));
    TNode<Cell> cell =
        CAST(LoadFixedArrayElement(regular_exports, export_index));
    SetAccumulator(LoadObjectField(cell, Cell::kValueOffset));
    Goto(&end);
  }
  BIND(&if_import);
  {
    TNode<FixedArray> regular_imports = LoadObjectField<FixedArray>(
        module, SourceTextModule::kRegularImportsOffset);
    // The actual array index is (-cell_index - 1).
    TNode<IntPtrT> import_index = IntPtrSub(IntPtrConstant(-1), cell_index);
    TNode<Cell> cell =
        CAST(LoadFixedArrayElement(regular_imports, import_index));
    SetAccumulator(LoadObjectField(cell, Cell::kValueOffset));
    Goto(&end);
  }
  BIND(&end);
  Dispatch();
}
References CAST, v8::internal::compiler::end(), v8::internal::Context::EXTENSION_INDEX, and v8::internal::compiler::IntPtrConstant().
IGNITION_HANDLER() [117/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (LdaNull , InterpreterAssembler)
Definition at line 105 of file interpreter-generator.cc.
                                                {
  SetAccumulator(NullConstant());
  Dispatch();
}
IGNITION_HANDLER() [118/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (Ldar , InterpreterAssembler)
Definition at line 137 of file interpreter-generator.cc.
                                             {
  TNode<Object> value = LoadRegisterAtOperandIndex(0);
  SetAccumulator(value);
  Dispatch();
}
References v8::internal::value.
IGNITION_HANDLER() [119/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (LdaSmi , InterpreterAssembler)
Definition at line 79 of file interpreter-generator.cc.
                                               {
  TNode<Smi> smi_int = BytecodeOperandImmSmi(0);
  SetAccumulator(smi_int);
  Dispatch();
}
IGNITION_HANDLER() [120/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (LdaTheHole , InterpreterAssembler)
Definition at line 113 of file interpreter-generator.cc.
                                                   {
  SetAccumulator(TheHoleConstant());
  Dispatch();
}
IGNITION_HANDLER() [121/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (LdaTrue , InterpreterAssembler)
Definition at line 121 of file interpreter-generator.cc.
                                                {
  SetAccumulator(TrueConstant());
  Dispatch();
}
IGNITION_HANDLER() [122/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (LdaUndefined , InterpreterAssembler)
Definition at line 97 of file interpreter-generator.cc.
                                                     {
  SetAccumulator(UndefinedConstant());
  Dispatch();
}
References v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant().
IGNITION_HANDLER() [123/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (LdaZero , InterpreterAssembler)
Definition at line 70 of file interpreter-generator.cc.
                                                {
  TNode<Number> zero_value = NumberConstant(0.0);
  SetAccumulator(zero_value);
  Dispatch();
}
References v8::internal::compiler::NumberConstant().
IGNITION_HANDLER() [124/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (LogicalNot , InterpreterAssembler)
Definition at line 1445 of file interpreter-generator.cc.
                                                   {
  TNode<Object> value = GetAccumulator();
  TVARIABLE(Boolean, result);
  Label if_true(this), if_false(this), end(this);
  TNode<True> true_value = TrueConstant();
  TNode<False> false_value = FalseConstant();
  Branch(TaggedEqual(value, true_value), &if_true, &if_false);
  BIND(&if_true);
  {
    result = false_value;
    Goto(&end);
  }
  BIND(&if_false);
  {
    CSA_DCHECK(this, TaggedEqual(value, false_value));
    result = true_value;
    Goto(&end);
  }
  BIND(&end);
  SetAccumulator(result.value());
  Dispatch();
}
References v8::internal::compiler::end(), v8::base::internal::result, and v8::internal::value.
IGNITION_HANDLER() [125/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (Mod , InterpreterBinaryOpAssembler)
Definition at line 1073 of file interpreter-generator.cc.
                                                    {
  BinaryOpWithFeedback(&BinaryOpAssembler::Generate_ModulusWithFeedback);
}
References v8::internal::BinaryOpAssembler::Generate_ModulusWithFeedback().
IGNITION_HANDLER() [126/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (ModSmi , InterpreterBinaryOpAssembler)
Definition at line 1115 of file interpreter-generator.cc.
                                                       {
  BinaryOpSmiWithFeedback(&BinaryOpAssembler::Generate_ModulusWithFeedback);
}
References v8::internal::BinaryOpAssembler::Generate_ModulusWithFeedback().
IGNITION_HANDLER() [127/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (Mov , InterpreterAssembler)
Definition at line 169 of file interpreter-generator.cc.
                                            {
  TNode<Object> src_value = LoadRegisterAtOperandIndex(0);
  StoreRegisterAtOperandIndex(src_value, 1);
  Dispatch();
}
IGNITION_HANDLER() [128/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (Mul , InterpreterBinaryOpAssembler)
Definition at line 1059 of file interpreter-generator.cc.
                                                    {
  BinaryOpWithFeedback(&BinaryOpAssembler::Generate_MultiplyWithFeedback);
}
References v8::internal::BinaryOpAssembler::Generate_MultiplyWithFeedback().
IGNITION_HANDLER() [129/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (MulSmi , InterpreterBinaryOpAssembler)
Definition at line 1101 of file interpreter-generator.cc.
                                                       {
  BinaryOpSmiWithFeedback(&BinaryOpAssembler::Generate_MultiplyWithFeedback);
}
References v8::internal::BinaryOpAssembler::Generate_MultiplyWithFeedback().
IGNITION_HANDLER() [130/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (Negate , InterpreterAssembler)
Definition at line 1296 of file interpreter-generator.cc.
                                               {
  TNode<Object> value = GetAccumulator();
  TNode<Context> context = GetContext();
  TNode<UintPtrT> slot_index = BytecodeOperandIdx(0);
  TNode<Union<FeedbackVector, Undefined>> maybe_feedback_vector =
      LoadFeedbackVectorOrUndefinedIfJitless();
  static constexpr UpdateFeedbackMode mode = DefaultUpdateFeedbackMode();
  UnaryOpAssembler unary_op_asm(state());
  TNode<Object> result = unary_op_asm.Generate_NegateWithFeedback(
      context, value, slot_index, maybe_feedback_vector, mode);
  SetAccumulator(result);
  Dispatch();
}
References v8::internal::UnaryOpAssembler::Generate_NegateWithFeedback(), mode(), v8::base::internal::result, and v8::internal::value.
IGNITION_HANDLER() [131/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (PopContext , InterpreterAssembler)
Definition at line 950 of file interpreter-generator.cc.
                                                   {
  TNode<Context> context = CAST(LoadRegisterAtOperandIndex(0));
  SetContext(context);
  Dispatch();
}
References CAST.
IGNITION_HANDLER() [132/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (PushContext , InterpreterAssembler)
Definition at line 939 of file interpreter-generator.cc.
                                                    {
  TNode<Context> new_context = CAST(GetAccumulator());
  TNode<Context> old_context = GetContext();
  StoreRegisterAtOperandIndex(old_context, 0);
  SetContext(new_context);
  Dispatch();
}
References CAST.
IGNITION_HANDLER() [133/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (ResumeGenerator , InterpreterAssembler)
Definition at line 3399 of file interpreter-generator.cc.
                                                        {
  TNode<JSGeneratorObject> generator = CAST(LoadRegisterAtOperandIndex(0));
  RegListNodePair registers = GetRegisterListAtOperandIndex(1);
  ImportRegisterFile(
      CAST(LoadObjectField(generator,
                           JSGeneratorObject::kParametersAndRegistersOffset)),
      registers);
  // Return the generator's input_or_debug_pos in the accumulator.
  SetAccumulator(
      LoadObjectField(generator, JSGeneratorObject::kInputOrDebugPosOffset));
  Dispatch();
}
References CAST.
IGNITION_HANDLER() [134/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (ReThrow , InterpreterAssembler)
Definition at line 2984 of file interpreter-generator.cc.
                                                {
  TNode<Object> exception = GetAccumulator();
  TNode<Context> context = GetContext();
  CallRuntime(Runtime::kReThrow, context, exception);
  // We shouldn't ever return from a throw.
  Abort(AbortReason::kUnexpectedReturnFromThrow);
  Unreachable();
}
IGNITION_HANDLER() [135/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (Return , InterpreterAssembler)
Definition at line 3005 of file interpreter-generator.cc.
                                               {
  UpdateInterruptBudgetOnReturn();
  TNode<Object> accumulator = GetAccumulator();
  Return(accumulator);
}
IGNITION_HANDLER() [136/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (SetKeyedProperty , InterpreterAssembler)
Definition at line 747 of file interpreter-generator.cc.
                                                         {
  TNode<Object> object = LoadRegisterAtOperandIndex(0);
  TNode<Object> name = LoadRegisterAtOperandIndex(1);
  TNode<Object> value = GetAccumulator();
  TNode<TaggedIndex> slot = BytecodeOperandIdxTaggedIndex(2);
  TNode<HeapObject> maybe_vector = LoadFeedbackVector();
  TNode<Context> context = GetContext();
  // KeyedStoreIC is currently a base class for multiple keyed property store
  // operations and contains mixed logic for set and define operations,
  // the paths are controlled by feedback.
  // TODO(v8:12548): refactor SetKeyedIC as a subclass of KeyedStoreIC, which
  // can be called here.
  TNode<Object> result = CallBuiltin(Builtin::kKeyedStoreIC, context, object,
                                     name, value, slot, maybe_vector);
  // To avoid special logic in the deoptimizer to re-materialize the value in
  // the accumulator, we clobber the accumulator after the IC call. It
  // doesn't really matter what we write to the accumulator here, since we
  // restore to the correct value on the outside. Storing the result means we
  // don't need to keep unnecessary state alive across the callstub.
  ClobberAccumulator(result);
  Dispatch();
}
References v8::internal::name, v8::base::internal::result, and v8::internal::value.
IGNITION_HANDLER() [137/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (SetNamedProperty , InterpreterSetNamedPropertyAssembler)
Definition at line 724 of file interpreter-generator.cc.
                                                                         {
  // StoreIC is currently a base class for multiple property store operations
  // and contains mixed logic for named and keyed, set and define operations,
  // the paths are controlled by feedback.
  // TODO(v8:12548): refactor SetNamedIC as a subclass of StoreIC, which can be
  // called here.
  SetNamedProperty(Builtin::kStoreIC, NamedPropertyType::kNotOwn);
}
References v8::internal::kNotOwn.
IGNITION_HANDLER() [138/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (SetPendingMessage , InterpreterAssembler)
Definition at line 2962 of file interpreter-generator.cc.
                                                          {
  TNode<HeapObject> previous_message = GetPendingMessage();
  SetPendingMessage(CAST(GetAccumulator()));
  SetAccumulator(previous_message);
  Dispatch();
}
References CAST.
IGNITION_HANDLER() [139/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (ShiftLeft , InterpreterBitwiseBinaryOpAssembler)
Definition at line 1198 of file interpreter-generator.cc.
                                                                 {
  BitwiseBinaryOpWithFeedback(Operation::kShiftLeft);
}
IGNITION_HANDLER() [140/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (ShiftLeftSmi , InterpreterBitwiseBinaryOpAssembler)
Definition at line 1271 of file interpreter-generator.cc.
                                                                    {
  BitwiseBinaryOpWithSmi(Operation::kShiftLeft);
}
IGNITION_HANDLER() [141/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (ShiftRight , InterpreterBitwiseBinaryOpAssembler)
Definition at line 1208 of file interpreter-generator.cc.
                                                                  {
  BitwiseBinaryOpWithFeedback(Operation::kShiftRight);
}
IGNITION_HANDLER() [142/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (ShiftRightLogical , InterpreterBitwiseBinaryOpAssembler)
Definition at line 1218 of file interpreter-generator.cc.
                                                                         {
  BitwiseBinaryOpWithFeedback(Operation::kShiftRightLogical);
}
IGNITION_HANDLER() [143/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (ShiftRightLogicalSmi , InterpreterBitwiseBinaryOpAssembler)
Definition at line 1289 of file interpreter-generator.cc.
                                                                            {
  BitwiseBinaryOpWithSmi(Operation::kShiftRightLogical);
}
IGNITION_HANDLER() [144/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (ShiftRightSmi , InterpreterBitwiseBinaryOpAssembler)
Definition at line 1280 of file interpreter-generator.cc.
                                                                     {
  BitwiseBinaryOpWithSmi(Operation::kShiftRight);
}
IGNITION_HANDLER() [145/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (StaContextSlot , InterpreterAssembler)
Definition at line 361 of file interpreter-generator.cc.
                                                       {
  TNode<Object> value = GetAccumulator();
  TNode<Context> context = CAST(LoadRegisterAtOperandIndex(0));
  TNode<IntPtrT> slot_index = Signed(BytecodeOperandIdx(1));
  TNode<Uint32T> depth = BytecodeOperandUImm(2);
  TNode<Context> slot_context = GetContextAtDepth(context, depth);
  StoreContextElement(slot_context, slot_index, value);
  Dispatch();
}
References CAST, v8::base::bits::Signed(), and v8::internal::value.
IGNITION_HANDLER() [146/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (StaContextSlotNoCell , InterpreterAssembler)
Definition at line 335 of file interpreter-generator.cc.
                                                             {
  TNode<Object> value = GetAccumulator();
  TNode<Context> context = CAST(LoadRegisterAtOperandIndex(0));
  TNode<IntPtrT> slot_index = Signed(BytecodeOperandIdx(1));
  TNode<Uint32T> depth = BytecodeOperandUImm(2);
  TNode<Context> slot_context = GetContextAtDepth(context, depth);
  StoreContextElementNoCell(slot_context, slot_index, value);
  Dispatch();
}
References CAST, v8::base::bits::Signed(), and v8::internal::value.
IGNITION_HANDLER() [147/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (StaCurrentContextSlot , InterpreterAssembler)
Definition at line 375 of file interpreter-generator.cc.
                                                              {
  TNode<Object> value = GetAccumulator();
  TNode<IntPtrT> slot_index = Signed(BytecodeOperandIdx(0));
  TNode<Context> slot_context = GetContext();
  StoreContextElement(slot_context, slot_index, value);
  Dispatch();
}
References v8::base::bits::Signed(), and v8::internal::value.
IGNITION_HANDLER() [148/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (StaCurrentContextSlotNoCell , InterpreterAssembler)
Definition at line 349 of file interpreter-generator.cc.
                                                                    {
  TNode<Object> value = GetAccumulator();
  TNode<IntPtrT> slot_index = Signed(BytecodeOperandIdx(0));
  TNode<Context> slot_context = GetContext();
  StoreContextElementNoCell(slot_context, slot_index, value);
  Dispatch();
}
References v8::base::bits::Signed(), and v8::internal::value.
IGNITION_HANDLER() [149/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (StaGlobal , InterpreterAssembler)
Definition at line 235 of file interpreter-generator.cc.
                                                  {
  TNode<Context> context = GetContext();
  // Store the global via the StoreGlobalIC.
  TNode<Name> name = CAST(LoadConstantPoolEntryAtOperandIndex(0));
  TNode<Object> value = GetAccumulator();
  TNode<TaggedIndex> slot = BytecodeOperandIdxTaggedIndex(1);
  TNode<HeapObject> maybe_vector = LoadFeedbackVector();
  TNode<Object> result = CallBuiltin(Builtin::kStoreGlobalIC, context, name,
                                     value, slot, maybe_vector);
  // To avoid special logic in the deoptimizer to re-materialize the value in
  // the accumulator, we clobber the accumulator after the IC call. It
  // doesn't really matter what we write to the accumulator here, since we
  // restore to the correct value on the outside. Storing the result means we
  // don't need to keep unnecessary state alive across the callstub.
  ClobberAccumulator(result);
  Dispatch();
}
References CAST, v8::internal::name, v8::base::internal::result, and v8::internal::value.
IGNITION_HANDLER() [150/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (StaInArrayLiteral , InterpreterAssembler)
Definition at line 806 of file interpreter-generator.cc.
                                                          {
  TNode<Object> array = LoadRegisterAtOperandIndex(0);
  TNode<Object> index = LoadRegisterAtOperandIndex(1);
  TNode<Object> value = GetAccumulator();
  TNode<TaggedIndex> slot = BytecodeOperandIdxTaggedIndex(2);
  TNode<HeapObject> feedback_vector = LoadFeedbackVector();
  TNode<Context> context = GetContext();
  TNode<Object> result =
      CallBuiltin(Builtin::kStoreInArrayLiteralIC, context, array, index, value,
                  slot, feedback_vector);
  // To avoid special logic in the deoptimizer to re-materialize the value in
  // the accumulator, we clobber the accumulator after the IC call. It
  // doesn't really matter what we write to the accumulator here, since we
  // restore to the correct value on the outside. Storing the result means we
  // don't need to keep unnecessary state alive across the callstub.
  ClobberAccumulator(result);
  Dispatch();
}
References v8::internal::index, v8::base::internal::result, and v8::internal::value.
IGNITION_HANDLER() [151/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (StaLookupSlot , InterpreterAssembler)
Definition at line 544 of file interpreter-generator.cc.
                                                      {
  TNode<Object> value = GetAccumulator();
  TNode<Name> name = CAST(LoadConstantPoolEntryAtOperandIndex(0));
  TNode<Uint32T> bytecode_flags = BytecodeOperandFlag8(1);
  TNode<Context> context = GetContext();
  TVARIABLE(Object, var_result);
  Label sloppy(this), strict(this), end(this);
  DCHECK_EQ(0, LanguageMode::kSloppy);
  DCHECK_EQ(1, LanguageMode::kStrict);
  DCHECK_EQ(0, static_cast<int>(LookupHoistingMode::kNormal));
  DCHECK_EQ(1, static_cast<int>(LookupHoistingMode::kLegacySloppy));
  Branch(IsSetWord32<StoreLookupSlotFlags::LanguageModeBit>(bytecode_flags),
         &strict, &sloppy);
  BIND(&strict);
  {
    CSA_DCHECK(this, IsClearWord32<StoreLookupSlotFlags::LookupHoistingModeBit>(
                         bytecode_flags));
    var_result =
        CallRuntime(Runtime::kStoreLookupSlot_Strict, context, name, value);
    Goto(&end);
  }
  BIND(&sloppy);
  {
    Label hoisting(this), ordinary(this);
    Branch(IsSetWord32<StoreLookupSlotFlags::LookupHoistingModeBit>(
               bytecode_flags),
           &hoisting, &ordinary);
    BIND(&hoisting);
    {
      var_result = CallRuntime(Runtime::kStoreLookupSlot_SloppyHoisting,
                               context, name, value);
      Goto(&end);
    }
    BIND(&ordinary);
    {
      var_result =
          CallRuntime(Runtime::kStoreLookupSlot_Sloppy, context, name, value);
      Goto(&end);
    }
  }
  BIND(&end);
  {
    SetAccumulator(var_result.value());
    Dispatch();
  }
}
References CAST, DCHECK_EQ, v8::internal::compiler::end(), v8::internal::kLegacySloppy, v8::internal::kNormal, v8::internal::kSloppy, v8::internal::kStrict, v8::internal::name, and v8::internal::value.
IGNITION_HANDLER() [152/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (StaModuleVariable , InterpreterAssembler)
Definition at line 899 of file interpreter-generator.cc.
                                                          {
  TNode<Object> value = GetAccumulator();
  TNode<IntPtrT> cell_index = BytecodeOperandImmIntPtr(0);
  TNode<Uint32T> depth = BytecodeOperandUImm(1);
  TNode<Context> module_context = GetContextAtDepth(GetContext(), depth);
  TNode<SourceTextModule> module =
      CAST(LoadContextElementNoCell(module_context, Context::EXTENSION_INDEX));
  Label if_export(this), if_import(this), end(this);
  Branch(IntPtrGreaterThan(cell_index, IntPtrConstant(0)), &if_export,
         &if_import);
  BIND(&if_export);
  {
    TNode<FixedArray> regular_exports = LoadObjectField<FixedArray>(
        module, SourceTextModule::kRegularExportsOffset);
    // The actual array index is (cell_index - 1).
    TNode<IntPtrT> export_index = IntPtrSub(cell_index, IntPtrConstant(1));
    TNode<HeapObject> cell =
        CAST(LoadFixedArrayElement(regular_exports, export_index));
    StoreObjectField(cell, Cell::kValueOffset, value);
    Goto(&end);
  }
  BIND(&if_import);
  {
    // Not supported (probably never).
    Abort(AbortReason::kUnsupportedModuleOperation);
    Goto(&end);
  }
  BIND(&end);
  Dispatch();
}
References CAST, v8::internal::compiler::end(), v8::internal::Context::EXTENSION_INDEX, v8::internal::compiler::IntPtrConstant(), and v8::internal::value.
IGNITION_HANDLER() [153/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (Star , InterpreterAssembler)
Definition at line 146 of file interpreter-generator.cc.
                                             {
  TNode<Object> accumulator = GetAccumulator();
  StoreRegisterAtOperandIndex(accumulator, 0);
  Dispatch();
}
IGNITION_HANDLER() [154/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (Star0 , InterpreterAssembler)
Definition at line 159 of file interpreter-generator.cc.
                                              {
  TNode<Object> accumulator = GetAccumulator();
  TNode<WordT> opcode = LoadBytecode(BytecodeOffset());
  StoreRegisterForShortStar(accumulator, opcode);
  Dispatch();
}
IGNITION_HANDLER() [155/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (Sub , InterpreterBinaryOpAssembler)
Definition at line 1052 of file interpreter-generator.cc.
                                                    {
  BinaryOpWithFeedback(&BinaryOpAssembler::Generate_SubtractWithFeedback);
}
References v8::internal::BinaryOpAssembler::Generate_SubtractWithFeedback().
IGNITION_HANDLER() [156/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (SubSmi , InterpreterBinaryOpAssembler)
Definition at line 1094 of file interpreter-generator.cc.
                                                       {
  BinaryOpSmiWithFeedback(&BinaryOpAssembler::Generate_SubtractWithFeedback);
}
References v8::internal::BinaryOpAssembler::Generate_SubtractWithFeedback().
IGNITION_HANDLER() [157/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (SuspendGenerator , InterpreterAssembler)
Definition at line 3327 of file interpreter-generator.cc.
                                                         {
  TNode<JSGeneratorObject> generator = CAST(LoadRegisterAtOperandIndex(0));
  TNode<FixedArray> array = CAST(LoadObjectField(
      generator, JSGeneratorObject::kParametersAndRegistersOffset));
  TNode<Context> context = GetContext();
  RegListNodePair registers = GetRegisterListAtOperandIndex(1);
  TNode<Smi> suspend_id = BytecodeOperandUImmSmi(3);
  ExportParametersAndRegisterFile(array, registers);
  StoreObjectField(generator, JSGeneratorObject::kContextOffset, context);
  StoreObjectField(generator, JSGeneratorObject::kContinuationOffset,
                   suspend_id);
  // Store the bytecode offset in the [input_or_debug_pos] field, to be used by
  // the inspector.
  TNode<Smi> offset = SmiTag(BytecodeOffset());
  StoreObjectField(generator, JSGeneratorObject::kInputOrDebugPosOffset,
                   offset);
  Return(GetAccumulator());
}
References CAST.
IGNITION_HANDLER() [158/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (SwitchOnGeneratorState , InterpreterAssembler)
Definition at line 3356 of file interpreter-generator.cc.
                                                               {
  TNode<Object> maybe_generator = LoadRegisterAtOperandIndex(0);
  Label fallthrough(this);
  GotoIf(TaggedEqual(maybe_generator, UndefinedConstant()), &fallthrough);
  TNode<JSGeneratorObject> generator = CAST(maybe_generator);
  TNode<Smi> state =
      CAST(LoadObjectField(generator, JSGeneratorObject::kContinuationOffset));
  TNode<Smi> new_state = SmiConstant(JSGeneratorObject::kGeneratorExecuting);
  StoreObjectField(generator, JSGeneratorObject::kContinuationOffset,
                   new_state);
  TNode<Context> context =
      CAST(LoadObjectField(generator, JSGeneratorObject::kContextOffset));
  SetContext(context);
  TNode<UintPtrT> table_start = BytecodeOperandIdx(1);
  TNode<UintPtrT> table_length = BytecodeOperandUImmWord(2);
  // The state must be a Smi.
  CSA_DCHECK(this, TaggedIsSmi(state));
  TNode<IntPtrT> case_value = SmiUntag(state);
  // When the sandbox is enabled, the generator state must be assumed to be
  // untrusted as it is located inside the sandbox, so validate it here.
  CSA_SBXCHECK(this, UintPtrLessThan(case_value, table_length));
  USE(table_length); // SBXCHECK is a DCHECK when the sandbox is disabled.
  TNode<WordT> entry = IntPtrAdd(table_start, case_value);
  TNode<IntPtrT> relative_jump = LoadAndUntagConstantPoolEntry(entry);
  Jump(relative_jump);
  BIND(&fallthrough);
  Dispatch();
}
References CAST, v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::IntPtrAdd(), v8::internal::JSGeneratorObject::kGeneratorExecuting, v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::SmiUntag(), v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::UintPtrLessThan(), v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant(), and USE.
IGNITION_HANDLER() [159/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (SwitchOnSmiNoFeedback , InterpreterAssembler)
Definition at line 2497 of file interpreter-generator.cc.
                                                              {
  // The accumulator must be a Smi.
  TNode<Object> acc = GetAccumulator();
  TNode<UintPtrT> table_start = BytecodeOperandIdx(0);
  TNode<UintPtrT> table_length = BytecodeOperandUImmWord(1);
  TNode<IntPtrT> case_value_base = BytecodeOperandImmIntPtr(2);
  Label fall_through(this);
  // TODO(leszeks): Use this as an alternative to adding extra bytecodes ahead
  // of a jump-table optimized switch statement, using this code, in lieu of the
  // current case_value line.
  // TNode<IntPtrT> acc_intptr = TryTaggedToInt32AsIntPtr(acc, &fall_through);
  // TNode<IntPtrT> case_value = IntPtrSub(acc_intptr, case_value_base);
  CSA_DCHECK(this, TaggedIsSmi(acc));
  TNode<IntPtrT> case_value = IntPtrSub(SmiUntag(CAST(acc)), case_value_base);
  GotoIf(IntPtrLessThan(case_value, IntPtrConstant(0)), &fall_through);
  GotoIf(IntPtrGreaterThanOrEqual(case_value, table_length), &fall_through);
  TNode<WordT> entry = IntPtrAdd(table_start, case_value);
  TNode<IntPtrT> relative_jump = LoadAndUntagConstantPoolEntry(entry);
  Jump(relative_jump);
  BIND(&fall_through);
  Dispatch();
}
References CAST, v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::IntPtrAdd(), v8::internal::compiler::IntPtrConstant(), v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::IntPtrLessThan(), and v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::SmiUntag().
IGNITION_HANDLER() [160/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (TestEqual , InterpreterCompareOpAssembler)
Definition at line 1848 of file interpreter-generator.cc.
                                                           {
  CompareOpWithFeedback(Operation::kEqual);
}
References v8::internal::kEqual.
IGNITION_HANDLER() [161/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (TestEqualStrict , InterpreterCompareOpAssembler)
Definition at line 1855 of file interpreter-generator.cc.
                                                                 {
  CompareOpWithFeedback(Operation::kStrictEqual);
}
IGNITION_HANDLER() [162/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (TestGreaterThan , InterpreterCompareOpAssembler)
Definition at line 1869 of file interpreter-generator.cc.
                                                                 {
  CompareOpWithFeedback(Operation::kGreaterThan);
}
References v8::internal::kGreaterThan.
IGNITION_HANDLER() [163/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (TestGreaterThanOrEqual , InterpreterCompareOpAssembler)
Definition at line 1885 of file interpreter-generator.cc.
                                                                        {
  CompareOpWithFeedback(Operation::kGreaterThanOrEqual);
}
IGNITION_HANDLER() [164/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (TestIn , InterpreterAssembler)
Definition at line 1905 of file interpreter-generator.cc.
                                               {
  TNode<Object> name = LoadRegisterAtOperandIndex(0);
  TNode<Object> object = GetAccumulator();
  TNode<TaggedIndex> slot = BytecodeOperandIdxTaggedIndex(1);
  TNode<HeapObject> feedback_vector = LoadFeedbackVector();
  TNode<Context> context = GetContext();
  TVARIABLE(Object, var_result);
  var_result = CallBuiltin(Builtin::kKeyedHasIC, context, object, name, slot,
                           feedback_vector);
  SetAccumulator(var_result.value());
  Dispatch();
}
References v8::internal::name.
IGNITION_HANDLER() [165/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (TestInstanceOf , InterpreterAssembler)
Definition at line 1923 of file interpreter-generator.cc.
                                                       {
  TNode<Object> object = LoadRegisterAtOperandIndex(0);
  TNode<JSAny> callable = CAST(GetAccumulator());
  TNode<Context> context = GetContext();
#ifndef V8_JITLESS
  TNode<Union<FeedbackVector, Undefined>> maybe_feedback_vector =
      LoadFeedbackVector();
  TNode<UintPtrT> slot_id = BytecodeOperandIdx(1);
  CollectInstanceOfFeedback(callable, context, maybe_feedback_vector, slot_id);
#endif // !V8_JITLESS
  SetAccumulator(InstanceOf(object, callable, context));
  Dispatch();
}
References CAST.
IGNITION_HANDLER() [166/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (TestLessThan , InterpreterCompareOpAssembler)
Definition at line 1862 of file interpreter-generator.cc.
                                                              {
  CompareOpWithFeedback(Operation::kLessThan);
}
References v8::internal::kLessThan.
IGNITION_HANDLER() [167/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (TestLessThanOrEqual , InterpreterCompareOpAssembler)
Definition at line 1877 of file interpreter-generator.cc.
                                                                     {
  CompareOpWithFeedback(Operation::kLessThanOrEqual);
}
IGNITION_HANDLER() [168/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (TestNull , InterpreterAssembler)
Definition at line 1964 of file interpreter-generator.cc.
                                                 {
  TNode<Object> object = GetAccumulator();
  TNode<Boolean> result =
      SelectBooleanConstant(TaggedEqual(object, NullConstant()));
  SetAccumulator(result);
  Dispatch();
}
References v8::base::internal::result.
IGNITION_HANDLER() [169/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (TestReferenceEqual , InterpreterAssembler)
Definition at line 1893 of file interpreter-generator.cc.
                                                           {
  TNode<Object> lhs = LoadRegisterAtOperandIndex(0);
  TNode<Object> rhs = GetAccumulator();
  TNode<Boolean> result = SelectBooleanConstant(TaggedEqual(lhs, rhs));
  SetAccumulator(result);
  Dispatch();
}
References v8::base::internal::result.
IGNITION_HANDLER() [170/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (TestTypeOf , InterpreterAssembler)
Definition at line 1987 of file interpreter-generator.cc.
                                                   {
  TNode<Object> object = GetAccumulator();
  TNode<Uint32T> literal_flag = BytecodeOperandFlag8(0);
#define MAKE_LABEL(name, lower_case) Label if_##lower_case(this);
  TYPEOF_LITERAL_LIST(MAKE_LABEL)
#undef MAKE_LABEL
#define LABEL_POINTER(name, lower_case) &if_##lower_case,
  Label* labels[] = {TYPEOF_LITERAL_LIST(LABEL_POINTER)};
#undef LABEL_POINTER
#define CASE(name, lower_case) \
  static_cast<int32_t>(TestTypeOfFlags::LiteralFlag::k##name),
  int32_t cases[] = {TYPEOF_LITERAL_LIST(CASE)};
#undef CASE
  Label if_true(this), if_false(this), end(this);
  // We just use the final label as the default and properly CSA_DCHECK
  // that the {literal_flag} is valid here; this significantly improves
  // the generated code (compared to having a default label that aborts).
  unsigned const num_cases = arraysize(cases);
  CSA_DCHECK(this, Uint32LessThan(literal_flag, Int32Constant(num_cases)));
  Switch(literal_flag, labels[num_cases - 1], cases, labels, num_cases - 1);
  BIND(&if_number);
  {
    Comment("IfNumber");
    GotoIfNumber(object, &if_true);
    Goto(&if_false);
  }
  BIND(&if_string);
  {
    Comment("IfString");
    GotoIf(TaggedIsSmi(object), &if_false);
    Branch(IsString(CAST(object)), &if_true, &if_false);
  }
  BIND(&if_symbol);
  {
    Comment("IfSymbol");
    GotoIf(TaggedIsSmi(object), &if_false);
    Branch(IsSymbol(CAST(object)), &if_true, &if_false);
  }
  BIND(&if_boolean);
  {
    Comment("IfBoolean");
    GotoIf(TaggedEqual(object, TrueConstant()), &if_true);
    Branch(TaggedEqual(object, FalseConstant()), &if_true, &if_false);
  }
  BIND(&if_bigint);
  {
    Comment("IfBigInt");
    GotoIf(TaggedIsSmi(object), &if_false);
    Branch(IsBigInt(CAST(object)), &if_true, &if_false);
  }
  BIND(&if_undefined);
  {
    Comment("IfUndefined");
    GotoIf(TaggedIsSmi(object), &if_false);
    // Check it is not null and the map has the undetectable bit set.
    GotoIf(IsNull(object), &if_false);
    Branch(IsUndetectableMap(LoadMap(CAST(object))), &if_true, &if_false);
  }
  BIND(&if_function);
  {
    Comment("IfFunction");
    GotoIf(TaggedIsSmi(object), &if_false);
    // Check if callable bit is set and not undetectable.
    TNode<Int32T> map_bitfield = LoadMapBitField(LoadMap(CAST(object)));
    TNode<Int32T> callable_undetectable = Word32And(
        map_bitfield, Int32Constant(Map::Bits1::IsUndetectableBit::kMask |
                                    Map::Bits1::IsCallableBit::kMask));
    Branch(Word32Equal(callable_undetectable,
                       Int32Constant(Map::Bits1::IsCallableBit::kMask)),
           &if_true, &if_false);
  }
  BIND(&if_object);
  {
    Comment("IfObject");
    GotoIf(TaggedIsSmi(object), &if_false);
    // If the object is null then return true.
    GotoIf(IsNull(object), &if_true);
    // Check if the object is a receiver type and is not undefined or callable.
    TNode<Map> map = LoadMap(CAST(object));
    GotoIfNot(IsJSReceiverMap(map), &if_false);
    TNode<Int32T> map_bitfield = LoadMapBitField(map);
    TNode<Int32T> callable_undetectable = Word32And(
        map_bitfield, Int32Constant(Map::Bits1::IsUndetectableBit::kMask |
                                    Map::Bits1::IsCallableBit::kMask));
    Branch(Word32Equal(callable_undetectable, Int32Constant(0)), &if_true,
           &if_false);
  }
  BIND(&if_other);
  {
    // Typeof doesn't return any other string value.
    Goto(&if_false);
  }
  BIND(&if_false);
  {
    SetAccumulator(FalseConstant());
    Goto(&end);
  }
  BIND(&if_true);
  {
    SetAccumulator(TrueConstant());
    Goto(&end);
  }
  BIND(&end);
  Dispatch();
}
References arraysize, CASE, CAST, v8::internal::compiler::end(), v8::internal::IsNull(), LABEL_POINTER, MAKE_LABEL, TYPEOF_LITERAL_LIST, and v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::Word32Equal().
IGNITION_HANDLER() [171/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (TestUndefined , InterpreterAssembler)
Definition at line 1975 of file interpreter-generator.cc.
                                                      {
  TNode<Object> object = GetAccumulator();
  TNode<Boolean> result =
      SelectBooleanConstant(TaggedEqual(object, UndefinedConstant()));
  SetAccumulator(result);
  Dispatch();
}
References v8::base::internal::result, and v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant().
IGNITION_HANDLER() [172/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (TestUndetectable , InterpreterAssembler)
Definition at line 1943 of file interpreter-generator.cc.
                                                         {
  Label return_false(this), end(this);
  TNode<Object> object = GetAccumulator();
  // If the object is an Smi then return false.
  SetAccumulator(FalseConstant());
  GotoIf(TaggedIsSmi(object), &end);
  // If it is a HeapObject, load the map and check for undetectable bit.
  TNode<Boolean> result =
      SelectBooleanConstant(IsUndetectableMap(LoadMap(CAST(object))));
  SetAccumulator(result);
  Goto(&end);
  BIND(&end);
  Dispatch();
}
References CAST, v8::internal::compiler::end(), and v8::base::internal::result.
IGNITION_HANDLER() [173/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (Throw , InterpreterAssembler)
Definition at line 2972 of file interpreter-generator.cc.
                                              {
  TNode<Object> exception = GetAccumulator();
  TNode<Context> context = GetContext();
  CallRuntime(Runtime::kThrow, context, exception);
  // We shouldn't ever return from a throw.
  Abort(AbortReason::kUnexpectedReturnFromThrow);
  Unreachable();
}
IGNITION_HANDLER() [174/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (ThrowIfNotSuperConstructor , InterpreterAssembler)
Definition at line 3075 of file interpreter-generator.cc.
                                                                   {
  TNode<HeapObject> constructor = CAST(LoadRegisterAtOperandIndex(0));
  TNode<Context> context = GetContext();
  Label is_not_constructor(this, Label::kDeferred);
  TNode<Map> constructor_map = LoadMap(constructor);
  GotoIfNot(IsConstructorMap(constructor_map), &is_not_constructor);
  Dispatch();
  BIND(&is_not_constructor);
  {
    TNode<JSFunction> function = LoadFunctionClosure();
    CallRuntime(Runtime::kThrowNotSuperConstructor, context, constructor,
                function);
    // We shouldn't ever return from a throw.
    Abort(AbortReason::kUnexpectedReturnFromThrow);
    Unreachable();
  }
}
References CAST.
IGNITION_HANDLER() [175/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (ThrowReferenceErrorIfHole , InterpreterAssembler)
Definition at line 3014 of file interpreter-generator.cc.
                                                                  {
  TNode<Object> value = GetAccumulator();
  Label throw_error(this, Label::kDeferred);
  GotoIf(TaggedEqual(value, TheHoleConstant()), &throw_error);
  Dispatch();
  BIND(&throw_error);
  {
    TNode<Name> name = CAST(LoadConstantPoolEntryAtOperandIndex(0));
    CallRuntime(Runtime::kThrowAccessedUninitializedVariable, GetContext(),
                name);
    // We shouldn't ever return from a throw.
    Abort(AbortReason::kUnexpectedReturnFromThrow);
    Unreachable();
  }
}
References CAST, v8::internal::name, and v8::internal::value.
IGNITION_HANDLER() [176/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (ThrowSuperAlreadyCalledIfNotHole , InterpreterAssembler)
Definition at line 3055 of file interpreter-generator.cc.
                                                                         {
  TNode<Object> value = GetAccumulator();
  Label throw_error(this, Label::kDeferred);
  GotoIf(TaggedNotEqual(value, TheHoleConstant()), &throw_error);
  Dispatch();
  BIND(&throw_error);
  {
    CallRuntime(Runtime::kThrowSuperAlreadyCalledError, GetContext());
    // We shouldn't ever return from a throw.
    Abort(AbortReason::kUnexpectedReturnFromThrow);
    Unreachable();
  }
}
References v8::internal::value.
IGNITION_HANDLER() [177/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (ThrowSuperNotCalledIfHole , InterpreterAssembler)
Definition at line 3035 of file interpreter-generator.cc.
                                                                  {
  TNode<Object> value = GetAccumulator();
  Label throw_error(this, Label::kDeferred);
  GotoIf(TaggedEqual(value, TheHoleConstant()), &throw_error);
  Dispatch();
  BIND(&throw_error);
  {
    CallRuntime(Runtime::kThrowSuperNotCalled, GetContext());
    // We shouldn't ever return from a throw.
    Abort(AbortReason::kUnexpectedReturnFromThrow);
    Unreachable();
  }
}
References v8::internal::value.
IGNITION_HANDLER() [178/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (ToBoolean , InterpreterAssembler)
Definition at line 1359 of file interpreter-generator.cc.
                                                  {
  TNode<Object> value = GetAccumulator();
  TVARIABLE(Boolean, result);
  Label if_true(this), if_false(this), end(this);
  BranchIfToBooleanIsTrue(value, &if_true, &if_false);
  BIND(&if_true);
  {
    result = TrueConstant();
    Goto(&end);
  }
  BIND(&if_false);
  {
    result = FalseConstant();
    Goto(&end);
  }
  BIND(&end);
  SetAccumulator(result.value());
  Dispatch();
}
References v8::internal::compiler::end(), v8::base::internal::result, and v8::internal::value.
IGNITION_HANDLER() [179/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (ToBooleanLogicalNot , InterpreterAssembler)
Definition at line 1421 of file interpreter-generator.cc.
                                                            {
  TNode<Object> value = GetAccumulator();
  TVARIABLE(Boolean, result);
  Label if_true(this), if_false(this), end(this);
  BranchIfToBooleanIsTrue(value, &if_true, &if_false);
  BIND(&if_true);
  {
    result = FalseConstant();
    Goto(&end);
  }
  BIND(&if_false);
  {
    result = TrueConstant();
    Goto(&end);
  }
  BIND(&end);
  SetAccumulator(result.value());
  Dispatch();
}
References v8::internal::compiler::end(), v8::base::internal::result, and v8::internal::value.
IGNITION_HANDLER() [180/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (ToName , InterpreterAssembler)
Definition at line 1315 of file interpreter-generator.cc.
                                               {
  TNode<Object> object = GetAccumulator();
  TNode<Context> context = GetContext();
  TNode<Object> result = CallBuiltin(Builtin::kToName, context, object);
  SetAccumulator(result);
  Dispatch();
}
References v8::base::internal::result.
IGNITION_HANDLER() [181/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (ToNumber , InterpreterAssembler)
Definition at line 1326 of file interpreter-generator.cc.
                                                 {
  ToNumberOrNumeric(Object::Conversion::kToNumber);
}
References v8::internal::Object::kToNumber.
IGNITION_HANDLER() [182/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (ToNumeric , InterpreterAssembler)
Definition at line 1333 of file interpreter-generator.cc.
                                                  {
  ToNumberOrNumeric(Object::Conversion::kToNumeric);
}
References v8::internal::Object::kToNumeric.
IGNITION_HANDLER() [183/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (ToObject , InterpreterAssembler)
Definition at line 1340 of file interpreter-generator.cc.
                                                 {
  TNode<Object> accumulator = GetAccumulator();
  TNode<Context> context = GetContext();
  TNode<Object> result = CallBuiltin(Builtin::kToObject, context, accumulator);
  StoreRegisterAtOperandIndex(result, 0);
  Dispatch();
}
References v8::base::internal::result.
IGNITION_HANDLER() [184/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (ToString , InterpreterAssembler)
Definition at line 1351 of file interpreter-generator.cc.
                                                 {
  SetAccumulator(ToString_Inline(GetContext(), GetAccumulator()));
  Dispatch();
}
IGNITION_HANDLER() [185/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (TypeOf , InterpreterAssembler)
Definition at line 1472 of file interpreter-generator.cc.
                                               {
  TNode<Object> value = GetAccumulator();
  TNode<UintPtrT> slot_id = BytecodeOperandIdx(0);
  TNode<Union<FeedbackVector, Undefined>> maybe_feedback_vector =
      LoadFeedbackVector();
  TNode<String> result = Typeof(value, slot_id, maybe_feedback_vector);
  SetAccumulator(result);
  Dispatch();
}
References v8::base::internal::result, and v8::internal::value.
IGNITION_HANDLER() [186/186]
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER (Wide , InterpreterAssembler)
Definition at line 3301 of file interpreter-generator.cc.
                                             {
  DispatchWide(OperandScale::kDouble);
}