v8::internal::anonymous_namespace{deoptimized-frame-info.cc} Namespace Reference
Functions
Handle< Object > GetValueForDebugger (TranslatedFrame::iterator it, Isolate *isolate)
Function Documentation
GetValueForDebugger()
Handle<Object> v8::internal::anonymous_namespace{deoptimized-frame-info.cc}::GetValueForDebugger (TranslatedFrame::iterator it, Isolate * isolate)
Definition at line 15 of file deoptimized-frame-info.cc.
                                                     {
  if (it->GetRawValue() == ReadOnlyRoots(isolate).arguments_marker() &&
      !it->IsMaterializableByDebugger()) {
    return isolate->factory()->optimized_out();
  }
  return it->GetValue();
}
References v8::internal::Isolate::factory(), v8::internal::TranslatedValue::GetRawValue(), v8::internal::TranslatedValue::GetValue(), and v8::internal::TranslatedValue::IsMaterializableByDebugger().
Referenced by v8::internal::DeoptimizedFrameInfo::DeoptimizedFrameInfo().