v8::internal::anonymous_namespace{builtins-string.cc} Namespace Reference
Functions
bool IsValidCodePoint (Isolate *isolate, DirectHandle< Object > value)
base::uc32 NextCodePoint (Isolate *isolate, BuiltinArguments args, int index)
bool ToUpperOverflows (base::uc32 character)
template<class Converter >
static V8_WARN_UNUSED_RESULT Tagged< Object > ConvertCaseHelper (Isolate *isolate, Tagged< String > string, Tagged< SeqString > result, uint32_t result_length, unibrow::Mapping< Converter, 128 > *mapping)
template<class Converter >
static V8_WARN_UNUSED_RESULT Tagged< Object > ConvertCase (DirectHandle< String > s, Isolate *isolate, unibrow::Mapping< Converter, 128 > *mapping)
Variables
static constexpr base::uc32 kInvalidCodePoint = static_cast<base::uc32>(-1)
Function Documentation
ConvertCase()
template<class Converter >
static V8_WARN_UNUSED_RESULT Tagged<Object> v8::internal::anonymous_namespace{builtins-string.cc}::ConvertCase (DirectHandle< String > s, Isolate * isolate, unibrow::Mapping< Converter, 128 > * mapping) [static]
Definition at line 333 of file builtins-string.cc.
                                             {
  s = String::Flatten(isolate, s);
  uint32_t length = s->length();
  // Assume that the string is not empty; we need this assumption later
  if (length == 0) return *s;
  // Simpler handling of ASCII strings.
  //
  // NOTE: This assumes that the upper/lower case of an ASCII
  // character is also ASCII. This is currently the case, but it
  // might break in the future if we implement more context and locale
  // dependent upper/lower conversions.
  if (String::IsOneByteRepresentationUnderneath(*s)) {
    uint32_t prefix;
    {
      DisallowGarbageCollection no_gc;
      String::FlatContent flat = s->GetFlatContent(no_gc);
      prefix = FastAsciiCasePrefixLength<Converter>(
          reinterpret_cast<const char*>(flat.ToOneByteVector().begin()),
          length);
      if (prefix == length) return *s;
    }
    // Same length as input.
    DirectHandle<SeqOneByteString> result =
        isolate->factory()->NewRawOneByteString(length).ToHandleChecked();
    DisallowGarbageCollection no_gc;
    String::FlatContent flat = s->GetFlatContent(no_gc);
    DCHECK(flat.IsFlat());
    uint8_t* dest = result->GetChars(no_gc);
    base::Vector<const uint8_t> src = flat.ToOneByteVector();
    std::memcpy(dest, src.begin(), prefix);
    uint32_t index_to_first_unprocessed =
        FastAsciiConvert<Converter>(
            reinterpret_cast<char*>(dest + prefix),
            reinterpret_cast<const char*>(src.begin() + prefix),
            length - prefix) +
        prefix;
    // If not ASCII, we discard the result and take the 2 byte path.
    if (index_to_first_unprocessed == length) return *result;
  }
  DirectHandle<SeqString> result; // Same length as input.
  if (s->IsOneByteRepresentation()) {
    result = isolate->factory()->NewRawOneByteString(length).ToHandleChecked();
  } else {
    result = isolate->factory()->NewRawTwoByteString(length).ToHandleChecked();
  }
  Tagged<Object> answer =
      ConvertCaseHelper(isolate, *s, *result, length, mapping);
  if (IsException(answer, isolate) || IsString(answer)) return answer;
  DCHECK(IsSmi(answer));
  // In this case we need to retry with a new string of the given length.
  // If the value is negative, the string must be a two-byte string.
  int int_answer = Smi::ToInt(answer);
  if (s->IsOneByteRepresentation() && int_answer > 0) {
    length = int_answer;
    ASSIGN_RETURN_FAILURE_ON_EXCEPTION(
        isolate, result, isolate->factory()->NewRawOneByteString(length));
  } else {
    length = abs(int_answer);
    ASSIGN_RETURN_FAILURE_ON_EXCEPTION(
        isolate, result, isolate->factory()->NewRawTwoByteString(length));
  }
  return ConvertCaseHelper(isolate, *s, *result, length, mapping);
}
References ASSIGN_RETURN_FAILURE_ON_EXCEPTION, v8::base::Vector< T >::begin(), ConvertCaseHelper(), v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::internal::String::FlatContent::IsFlat(), v8::internal::String::IsOneByteRepresentationUnderneath(), v8::internal::IsSmi(), v8::internal::length, v8::internal::FactoryBase< Impl >::NewRawOneByteString(), v8::internal::FactoryBase< Impl >::NewRawTwoByteString(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, v8::internal::Smi::ToInt(), and v8::internal::String::FlatContent::ToOneByteVector().
Referenced by v8::internal::BUILTIN().
ConvertCaseHelper()
template<class Converter >
static V8_WARN_UNUSED_RESULT Tagged<Object> v8::internal::anonymous_namespace{builtins-string.cc}::ConvertCaseHelper (Isolate * isolate, Tagged< String > string, Tagged< SeqString > result, uint32_t result_length, unibrow::Mapping< Converter, 128 > * mapping) [static]
Definition at line 236 of file builtins-string.cc.
                                                                     {
  DisallowGarbageCollection no_gc;
  // We try this twice, once with the assumption that the result is no longer
  // than the input and, if that assumption breaks, again with the exact
  // length. This may not be pretty, but it is nicer than what was here before
  // and I hereby claim my vaffel-is.
  //
  // NOTE: This assumes that the upper/lower case of an ASCII
  // character is also ASCII. This is currently the case, but it
  // might break in the future if we implement more context and locale
  // dependent upper/lower conversions.
  bool has_changed_character = false;
  // Convert all characters to upper case, assuming that they will fit
  // in the buffer
  StringCharacterStream stream(string);
  unibrow::uchar chars[Converter::kMaxWidth];
  // We can assume that the string is not empty
  base::uc32 current = stream.GetNext();
  bool ignore_overflow = Converter::kIsToLower || IsSeqTwoByteString(result);
  for (uint32_t i = 0; i < result_length;) {
    bool has_next = stream.HasMore();
    base::uc32 next = has_next ? stream.GetNext() : 0;
    uint32_t char_length = mapping->get(current, next, chars);
    if (char_length == 0) {
      // The case conversion of this character is the character itself.
      result->Set(i, current);
      i++;
    } else if (char_length == 1 &&
               (ignore_overflow || !ToUpperOverflows(current))) {
      // Common case: converting the letter resulted in one character.
      DCHECK(static_cast<base::uc32>(chars[0]) != current);
      result->Set(i, chars[0]);
      has_changed_character = true;
      i++;
    } else if (result_length == string->length()) {
      bool overflows = ToUpperOverflows(current);
      // We've assumed that the result would be as long as the
      // input but here is a character that converts to several
      // characters. No matter, we calculate the exact length
      // of the result and try the whole thing again.
      //
      // Note that this leaves room for optimization. We could just
      // memcpy what we already have to the result string. Also,
      // the result string is the last object allocated we could
      // "realloc" it and probably, in the vast majority of cases,
      // extend the existing string to be able to hold the full
      // result.
      uint32_t next_length = 0;
      if (has_next) {
        next_length = mapping->get(next, 0, chars);
        if (next_length == 0) next_length = 1;
      }
      uint32_t current_length = i + char_length + next_length;
      while (stream.HasMore()) {
        current = stream.GetNext();
        overflows |= ToUpperOverflows(current);
        // NOTE: we use 0 as the next character here because, while
        // the next character may affect what a character converts to,
        // it does not in any case affect the length of what it convert
        // to.
        int char_len = mapping->get(current, 0, chars);
        if (char_len == 0) char_len = 1;
        current_length += char_len;
        if (current_length > String::kMaxLength) {
          AllowGarbageCollection allocate_error_and_return;
          THROW_NEW_ERROR_RETURN_FAILURE(isolate,
                                         NewInvalidStringLengthError());
        }
      }
      // Try again with the real length. Return signed if we need
      // to allocate a two-byte string for to uppercase.
      return (overflows && !ignore_overflow) ? Smi::FromInt(-current_length)
                                             : Smi::FromInt(current_length);
    } else {
      for (uint32_t j = 0; j < char_length; j++) {
        result->Set(i, chars[j]);
        i++;
      }
      has_changed_character = true;
    }
    current = next;
  }
  if (has_changed_character) {
    return result;
  } else {
    // If we didn't actually change anything in doing the conversion
    // we simple return the result and let the converted string
    // become garbage; there is no reason to keep two identical strings
    // alive.
    return string;
  }
}
References v8::internal::DCHECK(), v8::internal::Smi::FromInt(), unibrow::Mapping< T, size >::get(), v8::internal::StringCharacterStream::GetNext(), v8::internal::StringCharacterStream::HasMore(), v8::internal::String::kMaxLength, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, v8::internal::string, THROW_NEW_ERROR_RETURN_FAILURE, and ToUpperOverflows().
Referenced by ConvertCase().
IsValidCodePoint()
bool v8::internal::anonymous_namespace{builtins-string.cc}::IsValidCodePoint (Isolate * isolate, DirectHandle< Object > value)
Definition at line 28 of file builtins-string.cc.
                                                                    {
  if (!IsNumber(*value) && !Object::ToNumber(isolate, value).ToHandle(&value)) {
    return false;
  }
  if (Object::IntegerValue(isolate, value).ToChecked() !=
      Object::NumberValue(*value)) {
    return false;
  }
  if (Object::NumberValue(*value) < 0 ||
      Object::NumberValue(*value) > 0x10FFFF) {
    return false;
  }
  return true;
}
References v8::Value::IntegerValue(), v8::internal::IsNumber(), v8::internal::Object::NumberValue(), v8::anonymous_namespace{api.cc}::ToHandle(), v8::Value::ToNumber(), and v8::internal::value.
Referenced by NextCodePoint().
NextCodePoint()
base::uc32 v8::internal::anonymous_namespace{builtins-string.cc}::NextCodePoint (Isolate * isolate, BuiltinArguments args, int index)
Definition at line 48 of file builtins-string.cc.
                                                                           {
  DirectHandle<Object> value = args.at(1 + index);
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, value, Object::ToNumber(isolate, value), kInvalidCodePoint);
  if (!IsValidCodePoint(isolate, value)) {
    isolate->Throw(*isolate->factory()->NewRangeError(
        MessageTemplate::kInvalidCodePoint, value));
    return kInvalidCodePoint;
  }
  return DoubleToUint32(Object::NumberValue(*value));
}
References v8::base::args, ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::DoubleToUint32(), v8::internal::Isolate::factory(), v8::internal::index, IsValidCodePoint(), kInvalidCodePoint, v8::internal::Object::NumberValue(), v8::internal::Isolate::Throw(), v8::Value::ToNumber(), and v8::internal::value.
Referenced by v8::internal::BUILTIN().
ToUpperOverflows()
bool v8::internal::anonymous_namespace{builtins-string.cc}::ToUpperOverflows (base::uc32 character) [inline]
Definition at line 227 of file builtins-string.cc.
                                                 {
  // y with umlauts and the micro sign are the only characters that stop
  // fitting into one-byte when converting to uppercase.
  static const base::uc32 yuml_code = 0xFF;
  static const base::uc32 micro_code = 0xB5;
  return (character == yuml_code || character == micro_code);
}
References v8::internal::character.
Referenced by ConvertCaseHelper().
Variable Documentation
kInvalidCodePoint
constexpr base::uc32 v8::internal::anonymous_namespace{builtins-string.cc}::kInvalidCodePoint = static_cast<base::uc32>(-1) [static], [constexpr]
Definition at line 46 of file builtins-string.cc.
Referenced by v8::internal::BUILTIN(), NextCodePoint(), and v8::internal::RUNTIME_FUNCTION().