v8::internal::anonymous_namespace{accessors.cc} Namespace Reference
Functions
Handle< JSObject > ArgumentsFromDeoptInfo (JavaScriptFrame *frame, int inlined_frame_index)
int FindFunctionInFrame (JavaScriptFrame *frame, DirectHandle< JSFunction > function)
Handle< JSObject > GetFrameArguments (Isolate *isolate, JavaScriptStackFrameIterator *it, int function_index)
MaybeDirectHandle< JSFunction > FindCaller (Isolate *isolate, DirectHandle< JSFunction > function)
Function Documentation
ArgumentsFromDeoptInfo()
Handle<JSObject> v8::internal::anonymous_namespace{accessors.cc}::ArgumentsFromDeoptInfo (JavaScriptFrame * frame, int inlined_frame_index)
Definition at line 398 of file accessors.cc.
                                                                 {
  Isolate* isolate = frame->isolate();
  Factory* factory = isolate->factory();
  TranslatedState translated_values(frame);
  translated_values.Prepare(frame->fp());
  int argument_count = 0;
  TranslatedFrame* translated_frame =
      translated_values.GetArgumentsInfoFromJSFrameIndex(inlined_frame_index,
                                                         &argument_count);
  TranslatedFrame::iterator iter = translated_frame->begin();
  // Materialize the function.
  bool should_deoptimize = iter->IsMaterializedObject();
  DirectHandle<JSFunction> function = Cast<JSFunction>(iter->GetValue());
  iter++;
  // Skip the receiver.
  iter++;
  argument_count--;
  Handle<JSObject> arguments =
      factory->NewArgumentsObject(function, argument_count);
  DirectHandle<FixedArray> array = factory->NewFixedArray(argument_count);
  for (int i = 0; i < argument_count; ++i) {
    // If we materialize any object, we should deoptimize the frame because we
    // might alias an object that was eliminated by escape analysis.
    should_deoptimize = should_deoptimize || iter->IsMaterializedObject();
    DirectHandle<Object> value = iter->GetValue();
    array->set(i, *value);
    iter++;
  }
  arguments->set_elements(*array);
  if (should_deoptimize) {
    translated_values.StoreMaterializedValuesAndDeopt(frame);
  }
  // Return the freshly allocated arguments object.
  return arguments;
}
References v8::internal::TranslatedFrame::begin(), v8::internal::Isolate::factory(), v8::internal::StackFrame::fp(), v8::internal::TranslatedState::GetArgumentsInfoFromJSFrameIndex(), v8::internal::TranslatedValue::GetValue(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::TranslatedValue::IsMaterializedObject(), v8::internal::StackFrame::isolate(), v8::internal::Factory::NewArgumentsObject(), v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::TranslatedState::Prepare(), v8::internal::TranslatedState::StoreMaterializedValuesAndDeopt(), and v8::internal::value.
Referenced by GetFrameArguments().
FindCaller()
MaybeDirectHandle<JSFunction> v8::internal::anonymous_namespace{accessors.cc}::FindCaller (Isolate * isolate, DirectHandle< JSFunction > function)
Definition at line 661 of file accessors.cc.
                                                                            {
  FrameFunctionIterator it(isolate);
  if (function->shared()->native()) {
    return {};
  }
  // Find the function from the frames. Return null in case no frame
  // corresponding to the given function was found.
  if (!it.Find(function)) {
    return {};
  }
  // Find previously called non-toplevel function that is also a user-land
  // JavaScript function (or the entry point into native JavaScript builtins
  // in case such a builtin was the caller).
  if (!it.FindNextNonTopLevelNativeOrUserJavaScript()) {
    return {};
  }
  // Materialize the function that the iterator is currently sitting on. Note
  // that this might trigger deoptimization in case the function was actually
  // materialized. Identity of the function must be preserved because we are
  // going to return it to JavaScript after this point.
  DirectHandle<JSFunction> caller = it.MaterializeFunction();
  // Censor if the caller is not a sloppy mode function.
  // Change from ES5, which used to throw, see:
  // https://bugs.ecmascript.org/show_bug.cgi?id=310
  if (is_strict(caller->shared()->language_mode())) {
    return {};
  }
  // Don't return caller from another security context.
  if (!AllowAccessToFunction(isolate->context(), *caller)) {
    return {};
  }
  return caller;
}
References v8::internal::AllowAccessToFunction(), v8::internal::Isolate::context(), v8::internal::FrameFunctionIterator::Find(), v8::internal::FrameFunctionIterator::FindNextNonTopLevelNativeOrUserJavaScript(), v8::internal::is_strict(), and v8::internal::FrameFunctionIterator::MaterializeFunction().
Referenced by v8::internal::Accessors::GetLegacyFunctionCaller().
FindFunctionInFrame()
int v8::internal::anonymous_namespace{accessors.cc}::FindFunctionInFrame (JavaScriptFrame * frame, DirectHandle< JSFunction > function)
Definition at line 442 of file accessors.cc.
                                                           {
  FrameSummaries summaries = frame->Summarize();
  for (int i = summaries.size(); i != 0; i--) {
    if (*summaries.frames[i - 1].AsJavaScript().function() == *function) {
      return static_cast<int>(i) - 1;
    }
  }
  return -1;
}
References v8::internal::FrameSummaries::frames, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::FrameSummaries::size(), and v8::internal::CommonFrameWithJSLinkage::Summarize().
Referenced by v8::internal::Accessors::GetLegacyFunctionArguments().
GetFrameArguments()
Handle<JSObject> v8::internal::anonymous_namespace{accessors.cc}::GetFrameArguments (Isolate * isolate, JavaScriptStackFrameIterator * it, int function_index)
Definition at line 453 of file accessors.cc.
                                                       {
  JavaScriptFrame* frame = it->frame();
  if (function_index > 0) {
    // The function in question was inlined. Inlined functions have the
    // correct number of arguments and no allocated arguments object, so
    // we can construct a fresh one by interpreting the function's
    // deoptimization input data.
    return ArgumentsFromDeoptInfo(frame, function_index);
  }
  // Construct an arguments object mirror for the right frame and the underlying
  // function.
  const int length = frame->GetActualArgumentCount();
  DirectHandle<JSFunction> function(frame->function(), isolate);
  Handle<JSObject> arguments =
      isolate->factory()->NewArgumentsObject(function, length);
  DirectHandle<FixedArray> array = isolate->factory()->NewFixedArray(length);
  // Copy the parameters to the arguments object.
  DCHECK(array->length() == length);
  for (int i = 0; i < length; i++) {
    Tagged<Object> value = frame->GetParameter(i);
    if (IsTheHole(value, isolate)) {
      // Generators currently use holes as dummy arguments when resuming. We
      // must not leak those.
      DCHECK(IsResumableFunction(function->shared()->kind()));
      value = ReadOnlyRoots(isolate).undefined_value();
    }
    array->set(i, value);
  }
  arguments->set_elements(*array);
  // For optimized functions, the frame arguments may be outdated, so we should
  // update them with the deopt info, while keeping the length and extra
  // arguments from the actual frame.
  if (CodeKindCanDeoptimize(frame->LookupCode()->kind()) && length > 0) {
    DirectHandle<JSObject> arguments_from_deopt_info =
        ArgumentsFromDeoptInfo(frame, function_index);
    DirectHandle<FixedArray> elements_from_deopt_info(
        Cast<FixedArray>(arguments_from_deopt_info->elements()), isolate);
    int common_length = std::min(length, elements_from_deopt_info->length());
    for (int i = 0; i < common_length; i++) {
      array->set(i, elements_from_deopt_info->get(i));
    }
  }
  // Return the freshly allocated arguments object.
  return arguments;
}
References ArgumentsFromDeoptInfo(), v8::internal::CodeKindCanDeoptimize(), v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::internal::JavaScriptStackFrameIterator::frame(), v8::internal::JavaScriptFrame::function(), v8::internal::JavaScriptFrame::GetActualArgumentCount(), v8::internal::CommonFrameWithJSLinkage::GetParameter(), v8::internal::IsResumableFunction(), v8::internal::length, v8::internal::StackFrame::LookupCode(), v8::internal::Factory::NewArgumentsObject(), v8::internal::FactoryBase< Impl >::NewFixedArray(), and v8::internal::value.
Referenced by v8::internal::Accessors::FunctionGetArguments(), and v8::internal::Accessors::GetLegacyFunctionArguments().