v8::internal::anonymous_namespace{bootstrapper.cc} Namespace Reference
Classes
class TryCallScope
Functions
DirectHandle< SharedFunctionInfo > CreateSharedFunctionInfoForBuiltin (Isolate *isolate, DirectHandle< String > name, Builtin builtin, int len, AdaptArguments adapt)
V8_NOINLINE DirectHandle< JSFunction > CreateFunctionForBuiltin (Isolate *isolate, DirectHandle< String > name, DirectHandle< Map > map, Builtin builtin, int len, AdaptArguments adapt)
V8_NOINLINE DirectHandle< JSFunction > CreateFunctionForBuiltinWithPrototype (Isolate *isolate, DirectHandle< String > name, Builtin builtin, DirectHandle< UnionOf< JSPrototype, Hole >> prototype, InstanceType type, int instance_size, int inobject_properties, MutableMode prototype_mutability, int len, AdaptArguments adapt)
V8_NOINLINE Handle< JSFunction > CreateFunctionForBuiltinWithoutPrototype (Isolate *isolate, DirectHandle< String > name, Builtin builtin, int len, AdaptArguments adapt)
V8_NOINLINE DirectHandle< JSFunction > CreateFunction (Isolate *isolate, DirectHandle< String > name, InstanceType type, int instance_size, int inobject_properties, DirectHandle< UnionOf< JSPrototype, Hole >> prototype, Builtin builtin, int len, AdaptArguments adapt)
V8_NOINLINE DirectHandle< JSFunction > CreateFunction (Isolate *isolate, const char *name, InstanceType type, int instance_size, int inobject_properties, DirectHandle< UnionOf< JSPrototype, Hole >> prototype, Builtin builtin, int len, AdaptArguments adapt)
V8_NOINLINE DirectHandle< JSFunction > InstallFunction (Isolate *isolate, DirectHandle< JSObject > target, DirectHandle< String > name, InstanceType type, int instance_size, int inobject_properties, DirectHandle< UnionOf< JSPrototype, Hole >> prototype, Builtin call, int len, AdaptArguments adapt)
V8_NOINLINE DirectHandle< JSFunction > InstallFunction (Isolate *isolate, DirectHandle< JSObject > target, const char *name, InstanceType type, int instance_size, int inobject_properties, DirectHandle< UnionOf< JSPrototype, Hole >> prototype, Builtin call, int len, AdaptArguments adapt)
V8_NOINLINE void SetConstructorInstanceType (Isolate *isolate, DirectHandle< JSFunction > constructor, InstanceType constructor_type)
V8_NOINLINE Handle< JSFunction > SimpleCreateFunction (Isolate *isolate, DirectHandle< String > name, Builtin call, int len, AdaptArguments adapt)
V8_NOINLINE Handle< JSFunction > InstallFunctionWithBuiltinId (Isolate *isolate, DirectHandle< JSObject > base, const char *name, Builtin call, int len, AdaptArguments adapt)
V8_NOINLINE Handle< JSFunction > InstallFunctionAtSymbol (Isolate *isolate, DirectHandle< JSObject > base, DirectHandle< Symbol > symbol, const char *symbol_string, Builtin call, int len, AdaptArguments adapt, PropertyAttributes attrs=DONT_ENUM)
V8_NOINLINE DirectHandle< JSFunction > CreateSharedObjectConstructor (Isolate *isolate, DirectHandle< String > name, DirectHandle< Map > instance_map, Builtin builtin, int len, AdaptArguments adapt)
V8_NOINLINE void SimpleInstallGetterSetter (Isolate *isolate, DirectHandle< JSObject > base, DirectHandle< Name > name, Builtin call_getter, Builtin call_setter)
void SimpleInstallGetterSetter (Isolate *isolate, DirectHandle< JSObject > base, const char *name, Builtin call_getter, Builtin call_setter)
V8_NOINLINE Handle< JSFunction > SimpleInstallGetter (Isolate *isolate, DirectHandle< JSObject > base, DirectHandle< Name > name, DirectHandle< Name > property_name, Builtin call, AdaptArguments adapt)
V8_NOINLINE Handle< JSFunction > SimpleInstallGetter (Isolate *isolate, DirectHandle< JSObject > base, DirectHandle< Name > name, Builtin call, AdaptArguments adapt)
V8_NOINLINE void InstallConstant (Isolate *isolate, DirectHandle< JSObject > holder, const char *name, DirectHandle< Object > value)
V8_NOINLINE void InstallTrueValuedProperty (Isolate *isolate, DirectHandle< JSObject > holder, const char *name)
V8_NOINLINE void InstallSpeciesGetter (Isolate *isolate, DirectHandle< JSFunction > constructor)
V8_NOINLINE void InstallToStringTag (Isolate *isolate, DirectHandle< JSObject > holder, DirectHandle< String > value)
void InstallToStringTag (Isolate *isolate, DirectHandle< JSObject > holder, const char *value)
template<size_t N>
DirectHandle< Map > CreateLiteralObjectMapFromCache (Isolate *isolate, const std::array< DirectHandle< Name >, N > &properties)
DirectHandle< Map > CreateNonConstructorMap (Isolate *isolate, DirectHandle< Map > source_map, DirectHandle< JSObject > prototype, const char *reason)
void ReplaceAccessors (Isolate *isolate, DirectHandle< Map > map, DirectHandle< String > name, PropertyAttributes attributes, DirectHandle< AccessorPair > accessor_pair)
void InitializeJSArrayMaps (Isolate *isolate, DirectHandle< Context > native_context, DirectHandle< Map > initial_map)
Function Documentation
CreateFunction() [1/2]
V8_NOINLINE DirectHandle<JSFunction> v8::internal::anonymous_namespace{bootstrapper.cc}::CreateFunction (Isolate * isolate, const char * name, InstanceType type, int instance_size, int inobject_properties, DirectHandle< UnionOf< JSPrototype, Hole >> prototype, Builtin builtin, int len, AdaptArguments adapt)
Definition at line 535 of file bootstrapper.cc.
                                                    {
  return CreateFunction(
      isolate, isolate->factory()->InternalizeUtf8String(name), type,
      instance_size, inobject_properties, prototype, builtin, len, adapt);
}
References v8::internal::Isolate::factory(), v8::internal::Factory::InternalizeUtf8String(), v8::internal::name, v8::internal::prototype, and v8::internal::tracing::type.
Referenced by v8::internal::Genesis::CreateArrayBuffer(), v8::internal::Genesis::CreateObjectFunction(), v8::internal::Genesis::InitializeCallSiteBuiltins(), v8::internal::Genesis::InitializeGlobal(), v8::internal::Genesis::InitializeIteratorFunctions(), and InstallFunction().
CreateFunction() [2/2]
V8_NOINLINE DirectHandle<JSFunction> v8::internal::anonymous_namespace{bootstrapper.cc}::CreateFunction (Isolate * isolate, DirectHandle< String > name, InstanceType type, int instance_size, int inobject_properties, DirectHandle< UnionOf< JSPrototype, Hole >> prototype, Builtin builtin, int len, AdaptArguments adapt)
Definition at line 514 of file bootstrapper.cc.
                                   {
  DCHECK(Builtins::HasJSLinkage(builtin));
  DirectHandle<JSFunction> result = CreateFunctionForBuiltinWithPrototype(
      isolate, name, builtin, prototype, type, instance_size,
      inobject_properties, IMMUTABLE, len, adapt);
  // Make the JSFunction's prototype object fast.
  JSObject::MakePrototypesFast(direct_handle(result->prototype(), isolate),
                               kStartAtReceiver, isolate);
  // Make the resulting JSFunction object fast.
  JSObject::MakePrototypesFast(result, kStartAtReceiver, isolate);
  result->shared()->set_native(true);
  return result;
}
References CreateFunctionForBuiltinWithPrototype(), v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::Builtins::HasJSLinkage(), v8::internal::IMMUTABLE, v8::internal::kStartAtReceiver, v8::internal::JSObject::MakePrototypesFast(), v8::internal::name, v8::internal::prototype, v8::base::internal::result, and v8::internal::tracing::type.
CreateFunctionForBuiltin()
V8_NOINLINE DirectHandle<JSFunction> v8::internal::anonymous_namespace{bootstrapper.cc}::CreateFunctionForBuiltin (Isolate * isolate, DirectHandle< String > name, DirectHandle< Map > map, Builtin builtin, int len, AdaptArguments adapt)
Definition at line 432 of file bootstrapper.cc.
                                                    {
  DirectHandle<NativeContext> context(isolate->native_context());
  DCHECK(IsFunctionMapOrSpecialBuiltin(map, builtin, context));
  DirectHandle<SharedFunctionInfo> info =
      CreateSharedFunctionInfoForBuiltin(isolate, name, builtin, len, adapt);
  return Factory::JSFunctionBuilder{isolate, info, context}
      .set_map(map)
      .Build();
}
References CreateSharedFunctionInfoForBuiltin(), v8::internal::DCHECK(), v8::internal::name, and v8::internal::Isolate::native_context().
Referenced by v8::internal::Genesis::CreateEmptyFunction(), and v8::internal::Genesis::InitializeGlobal().
CreateFunctionForBuiltinWithoutPrototype()
V8_NOINLINE Handle<JSFunction> v8::internal::anonymous_namespace{bootstrapper.cc}::CreateFunctionForBuiltinWithoutPrototype (Isolate * isolate, DirectHandle< String > name, Builtin builtin, int len, AdaptArguments adapt)
Definition at line 499 of file bootstrapper.cc.
                          {
  DirectHandle<NativeContext> context(isolate->native_context());
  DirectHandle<Map> map = isolate->strict_function_without_prototype_map();
  DCHECK(IsFunctionMapOrSpecialBuiltin(map, builtin, context));
  DirectHandle<SharedFunctionInfo> info =
      CreateSharedFunctionInfoForBuiltin(isolate, name, builtin, len, adapt);
  return Factory::JSFunctionBuilder{isolate, info, context}
      .set_map(map)
      .Build();
}
References CreateSharedFunctionInfoForBuiltin(), v8::internal::DCHECK(), v8::internal::name, and v8::internal::Isolate::native_context().
Referenced by v8::internal::Genesis::GetThrowTypeErrorIntrinsic(), and SimpleCreateFunction().
CreateFunctionForBuiltinWithPrototype()
V8_NOINLINE DirectHandle<JSFunction> v8::internal::anonymous_namespace{bootstrapper.cc}::CreateFunctionForBuiltinWithPrototype (Isolate * isolate, DirectHandle< String > name, Builtin builtin, DirectHandle< UnionOf< JSPrototype, Hole >> prototype, InstanceType type, int instance_size, int inobject_properties, MutableMode prototype_mutability, int len, AdaptArguments adapt)
Definition at line 446 of file bootstrapper.cc.
                                                                     {
  Factory* factory = isolate->factory();
  DirectHandle<NativeContext> context(isolate->native_context());
  DirectHandle<Map> map =
      prototype_mutability == MUTABLE
          ? isolate->strict_function_map()
          : isolate->strict_function_with_readonly_prototype_map();
  DCHECK(IsFunctionMapOrSpecialBuiltin(map, builtin, context));
  DirectHandle<SharedFunctionInfo> info =
      CreateSharedFunctionInfoForBuiltin(isolate, name, builtin, len, adapt);
  info->set_expected_nof_properties(inobject_properties);
  DirectHandle<JSFunction> result =
      Factory::JSFunctionBuilder{isolate, info, context}.set_map(map).Build();
  ElementsKind elements_kind;
  switch (type) {
    case JS_ARRAY_TYPE:
      elements_kind = PACKED_SMI_ELEMENTS;
      break;
    case JS_ARGUMENTS_OBJECT_TYPE:
      elements_kind = PACKED_ELEMENTS;
      break;
    default:
      elements_kind = TERMINAL_FAST_ELEMENTS_KIND;
      break;
  }
  DirectHandle<Map> initial_map = factory->NewContextfulMapForCurrentContext(
      type, instance_size, elements_kind, inobject_properties);
  initial_map->SetConstructor(*result);
  if (type == JS_FUNCTION_TYPE) {
    DCHECK_EQ(instance_size, JSFunction::kSizeWithPrototype);
    // Since we are creating an initial map for JSFunction objects with
    // prototype slot, set the respective bit.
    initial_map->set_has_prototype_slot(true);
  }
  // TODO(littledan): Why do we have this is_generator test when
  // NewFunctionPrototype already handles finding an appropriately
  // shared prototype?
  if (!IsResumableFunction(info->kind()) && IsTheHole(*prototype, isolate)) {
    prototype = factory->NewFunctionPrototype(result);
  }
  JSFunction::SetInitialMap(isolate, result, initial_map,
                            Cast<JSPrototype>(prototype));
  return result;
}
References CreateSharedFunctionInfoForBuiltin(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Isolate::factory(), v8::internal::compiler::initial_map, v8::internal::IsResumableFunction(), v8::internal::JSFunction::kSizeWithPrototype, v8::internal::MUTABLE, v8::internal::name, v8::internal::Isolate::native_context(), v8::internal::Factory::NewContextfulMapForCurrentContext(), v8::internal::Factory::NewFunctionPrototype(), v8::internal::PACKED_ELEMENTS, v8::internal::PACKED_SMI_ELEMENTS, v8::internal::prototype, v8::base::internal::result, v8::internal::JSFunction::SetInitialMap(), v8::internal::TERMINAL_FAST_ELEMENTS_KIND, and v8::internal::tracing::type.
Referenced by CreateFunction(), v8::internal::Genesis::CreateNewGlobals(), and v8::internal::Genesis::InitializeGlobal().
CreateLiteralObjectMapFromCache()
template<size_t N>
DirectHandle<Map> v8::internal::anonymous_namespace{bootstrapper.cc}::CreateLiteralObjectMapFromCache (Isolate * isolate, const std::array< DirectHandle< Name >, N > & properties)
Definition at line 757 of file bootstrapper.cc.
                                                                         {
  Factory* factory = isolate->factory();
  DirectHandle<NativeContext> native_context = isolate->native_context();
  DirectHandle<Map> map = factory->ObjectLiteralMapFromCache(native_context, N);
  for (DirectHandle<Name> name : properties) {
    map = Map::CopyWithField(isolate, map, name, FieldType::Any(isolate), NONE,
                             PropertyConstness::kConst,
                             Representation::Tagged(), INSERT_TRANSITION)
              .ToHandleChecked();
  }
  return map;
}
References v8::internal::FieldType::Any(), v8::internal::Map::CopyWithField(), v8::internal::Isolate::factory(), v8::internal::INSERT_TRANSITION, v8::internal::kConst, v8::internal::N, v8::internal::name, v8::internal::Isolate::native_context(), v8::internal::native_context, v8::internal::NONE, v8::internal::Factory::ObjectLiteralMapFromCache(), and v8::internal::Representation::Tagged().
Referenced by v8::internal::Genesis::InitializeGlobal().
CreateNonConstructorMap()
DirectHandle<Map> v8::internal::anonymous_namespace{bootstrapper.cc}::CreateNonConstructorMap (Isolate * isolate, DirectHandle< Map > source_map, DirectHandle< JSObject > prototype, const char * reason)
Definition at line 970 of file bootstrapper.cc.
                                                              {
  DirectHandle<Map> map = Map::Copy(isolate, source_map, reason);
  // Ensure the resulting map has prototype slot (it is necessary for storing
  // initial map even when the prototype property is not required).
  if (!map->has_prototype_slot()) {
    // Re-set the unused property fields after changing the instance size.
    int unused_property_fields = map->UnusedPropertyFields();
    map->set_instance_size(map->instance_size() + kTaggedSize);
    // The prototype slot shifts the in-object properties area by one slot.
    map->SetInObjectPropertiesStartInWords(
        map->GetInObjectPropertiesStartInWords() + 1);
    map->set_has_prototype_slot(true);
    map->SetInObjectUnusedPropertyFields(unused_property_fields);
  }
  map->set_is_constructor(false);
  Map::SetPrototype(isolate, map, prototype);
  return map;
}
References v8::internal::Map::Copy(), v8::internal::kTaggedSize, v8::internal::prototype, and v8::internal::Map::SetPrototype().
Referenced by v8::internal::Genesis::CreateAsyncIteratorMaps(), and v8::internal::Genesis::CreateIteratorMaps().
CreateSharedFunctionInfoForBuiltin()
DirectHandle<SharedFunctionInfo> v8::internal::anonymous_namespace{bootstrapper.cc}::CreateSharedFunctionInfoForBuiltin (Isolate * isolate, DirectHandle< String > name, Builtin builtin, int len, AdaptArguments adapt)
Definition at line 413 of file bootstrapper.cc.
                          {
  DirectHandle<SharedFunctionInfo> info =
      isolate->factory()->NewSharedFunctionInfoForBuiltin(name, builtin, len,
                                                          adapt);
  info->set_language_mode(LanguageMode::kStrict);
#ifdef DEBUG
  Tagged<Code> code = info->GetCode(isolate);
  if (code->parameter_count() != kDontAdaptArgumentsSentinel) {
    DCHECK_EQ(info->internal_formal_parameter_count_with_receiver(),
              code->parameter_count());
  }
#endif
  return info;
}
References code, DCHECK_EQ, v8::internal::Isolate::factory(), v8::internal::kDontAdaptArgumentsSentinel, v8::internal::kStrict, v8::internal::name, and v8::internal::Factory::NewSharedFunctionInfoForBuiltin().
Referenced by CreateFunctionForBuiltin(), CreateFunctionForBuiltinWithoutPrototype(), and CreateFunctionForBuiltinWithPrototype().
CreateSharedObjectConstructor()
V8_NOINLINE DirectHandle<JSFunction> v8::internal::anonymous_namespace{bootstrapper.cc}::CreateSharedObjectConstructor (Isolate * isolate, DirectHandle< String > name, DirectHandle< Map > instance_map, Builtin builtin, int len, AdaptArguments adapt)
Definition at line 630 of file bootstrapper.cc.
                                                    {
  Factory* factory = isolate->factory();
  DirectHandle<SharedFunctionInfo> info =
      factory->NewSharedFunctionInfoForBuiltin(name, builtin, len, adapt);
  info->set_language_mode(LanguageMode::kStrict);
  DirectHandle<JSFunction> constructor =
      Factory::JSFunctionBuilder{isolate, info, isolate->native_context()}
          .set_map(isolate->strict_function_with_readonly_prototype_map())
          .Build();
  constructor->set_prototype_or_initial_map(*instance_map, kReleaseStore);
  JSObject::AddProperty(
      isolate, constructor, factory->has_instance_symbol(),
      direct_handle(
          isolate->native_context()->shared_space_js_object_has_instance(),
          isolate),
      static_cast<PropertyAttributes>(DONT_ENUM | DONT_DELETE | READ_ONLY));
  return constructor;
}
References v8::internal::JSObject::AddProperty(), v8::internal::direct_handle(), v8::internal::DONT_DELETE, v8::internal::DONT_ENUM, v8::internal::Isolate::factory(), v8::kReleaseStore, v8::internal::kStrict, v8::internal::name, v8::internal::Isolate::native_context(), v8::internal::Factory::NewSharedFunctionInfoForBuiltin(), and v8::internal::READ_ONLY.
InitializeJSArrayMaps()
void v8::internal::anonymous_namespace{bootstrapper.cc}::InitializeJSArrayMaps (Isolate * isolate, DirectHandle< Context > native_context, DirectHandle< Map > initial_map)
Definition at line 1283 of file bootstrapper.cc.
                                                          {
  // Replace all of the cached initial array maps in the native context with
  // the appropriate transitioned elements kind maps.
  DirectHandle<Map> current_map = initial_map;
  ElementsKind kind = current_map->elements_kind();
  DCHECK_EQ(GetInitialFastElementsKind(), kind);
  DCHECK_EQ(PACKED_SMI_ELEMENTS, kind);
  DCHECK_EQ(Context::ArrayMapIndex(kind),
            Context::JS_ARRAY_PACKED_SMI_ELEMENTS_MAP_INDEX);
  native_context->SetNoCell(Context::ArrayMapIndex(kind), *current_map,
                            kReleaseStore);
  for (int i = GetSequenceIndexFromFastElementsKind(kind) + 1;
       i < kFastElementsKindCount; ++i) {
    DirectHandle<Map> new_map;
    ElementsKind next_kind = GetFastElementsKindFromSequenceIndex(i);
    Tagged<Map> maybe_elements_transition = current_map->ElementsTransitionMap(
        isolate, ConcurrencyMode::kSynchronous);
    if (!maybe_elements_transition.is_null()) {
      new_map = direct_handle(maybe_elements_transition, isolate);
    } else {
      new_map = Map::CopyAsElementsKind(isolate, current_map, next_kind,
                                        INSERT_TRANSITION);
    }
    DCHECK_EQ(next_kind, new_map->elements_kind());
    native_context->SetNoCell(Context::ArrayMapIndex(next_kind), *new_map,
                              kReleaseStore);
    current_map = new_map;
  }
}
References v8::internal::Context::ArrayMapIndex(), v8::internal::Map::CopyAsElementsKind(), DCHECK_EQ, v8::internal::direct_handle(), v8::internal::GetFastElementsKindFromSequenceIndex(), v8::internal::GetInitialFastElementsKind(), v8::internal::GetSequenceIndexFromFastElementsKind(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::initial_map, v8::internal::INSERT_TRANSITION, v8::internal::Tagged< HeapObject >::is_null(), v8::internal::kFastElementsKindCount, v8::kReleaseStore, v8::internal::kSynchronous, v8::internal::native_context, and v8::internal::PACKED_SMI_ELEMENTS.
Referenced by v8::internal::Genesis::InitializeGlobal().
InstallConstant()
V8_NOINLINE void v8::internal::anonymous_namespace{bootstrapper.cc}::InstallConstant (Isolate * isolate, DirectHandle< JSObject > holder, const char * name, DirectHandle< Object > value)
Definition at line 708 of file bootstrapper.cc.
                                                                               {
  JSObject::AddProperty(
      isolate, holder, isolate->factory()->InternalizeUtf8String(name), value,
      static_cast<PropertyAttributes>(DONT_DELETE | DONT_ENUM | READ_ONLY));
}
References v8::internal::JSObject::AddProperty(), v8::internal::DONT_DELETE, v8::internal::DONT_ENUM, v8::internal::Isolate::factory(), v8::internal::Factory::InternalizeUtf8String(), v8::internal::name, v8::internal::READ_ONLY, and v8::internal::value.
Referenced by v8::internal::Genesis::InitializeGlobal(), and v8::internal::Genesis::InstallTypedArray().
InstallFunction() [1/2]
V8_NOINLINE DirectHandle<JSFunction> v8::internal::anonymous_namespace{bootstrapper.cc}::InstallFunction (Isolate * isolate, DirectHandle< JSObject > target, const char * name, InstanceType type, int instance_size, int inobject_properties, DirectHandle< UnionOf< JSPrototype, Hole >> prototype, Builtin call, int len, AdaptArguments adapt)
Definition at line 557 of file bootstrapper.cc.
                          {
  return InstallFunction(
      isolate, target, isolate->factory()->InternalizeUtf8String(name), type,
      instance_size, inobject_properties, prototype, call, len, adapt);
}
References v8::internal::Isolate::factory(), v8::internal::Factory::InternalizeUtf8String(), v8::internal::name, v8::internal::prototype, and v8::internal::tracing::type.
Referenced by v8::internal::Genesis::InitializeGlobal(), v8::internal::InstallError(), and v8::internal::Genesis::InstallTypedArray().
InstallFunction() [2/2]
V8_NOINLINE DirectHandle<JSFunction> v8::internal::anonymous_namespace{bootstrapper.cc}::InstallFunction (Isolate * isolate, DirectHandle< JSObject > target, DirectHandle< String > name, InstanceType type, int instance_size, int inobject_properties, DirectHandle< UnionOf< JSPrototype, Hole >> prototype, Builtin call, int len, AdaptArguments adapt)
Definition at line 544 of file bootstrapper.cc.
                          {
  DCHECK(Builtins::HasJSLinkage(call));
  DirectHandle<JSFunction> function =
      CreateFunction(isolate, name, type, instance_size, inobject_properties,
                     prototype, call, len, adapt);
  JSObject::AddProperty(isolate, target, name, function, DONT_ENUM);
  return function;
}
References v8::internal::JSObject::AddProperty(), CreateFunction(), v8::internal::DCHECK(), v8::internal::DONT_ENUM, v8::internal::Builtins::HasJSLinkage(), v8::internal::name, v8::internal::prototype, and v8::internal::tracing::type.
InstallFunctionAtSymbol()
V8_NOINLINE Handle<JSFunction> v8::internal::anonymous_namespace{bootstrapper.cc}::InstallFunctionAtSymbol (Isolate * isolate, DirectHandle< JSObject > base, DirectHandle< Symbol > symbol, const char * symbol_string, Builtin call, int len, AdaptArguments adapt, PropertyAttributes attrs = DONT_ENUM)
Definition at line 618 of file bootstrapper.cc.
                                          {
  DirectHandle<String> internalized_symbol =
      isolate->factory()->InternalizeUtf8String(symbol_string);
  Handle<JSFunction> fun =
      SimpleCreateFunction(isolate, internalized_symbol, call, len, adapt);
  JSObject::AddProperty(isolate, base, symbol, fun, attrs);
  return fun;
}
References v8::internal::JSObject::AddProperty(), v8::internal::Isolate::factory(), v8::internal::Factory::InternalizeUtf8String(), and SimpleCreateFunction().
Referenced by v8::internal::Genesis::CreateAsyncIteratorMaps(), v8::internal::Genesis::CreateIteratorMaps(), and v8::internal::Genesis::InitializeGlobal().
InstallFunctionWithBuiltinId()
V8_NOINLINE Handle<JSFunction> v8::internal::anonymous_namespace{bootstrapper.cc}::InstallFunctionWithBuiltinId (Isolate * isolate, DirectHandle< JSObject > base, const char * name, Builtin call, int len, AdaptArguments adapt)
Definition at line 607 of file bootstrapper.cc.
                                                 {
  DirectHandle<String> internalized_name =
      isolate->factory()->InternalizeUtf8String(name);
  Handle<JSFunction> fun =
      SimpleCreateFunction(isolate, internalized_name, call, len, adapt);
  JSObject::AddProperty(isolate, base, internalized_name, fun, DONT_ENUM);
  return fun;
}
References v8::internal::JSObject::AddProperty(), v8::internal::DONT_ENUM, v8::internal::Isolate::factory(), v8::internal::Factory::InternalizeUtf8String(), v8::internal::name, and SimpleCreateFunction().
Referenced by v8::internal::Genesis::CreateArrayBuffer(), v8::internal::Genesis::InitializeGlobal(), v8::internal::Genesis::InitializeIteratorFunctions(), and v8::internal::Genesis::InstallABunchOfRandomThings().
InstallSpeciesGetter()
V8_NOINLINE void v8::internal::anonymous_namespace{bootstrapper.cc}::InstallSpeciesGetter (Isolate * isolate, DirectHandle< JSFunction > constructor)
Definition at line 724 of file bootstrapper.cc.
                                                                            {
  Factory* factory = isolate->factory();
  // TODO(adamk): We should be able to share a SharedFunctionInfo
  // between all these JSFunctions.
  SimpleInstallGetter(isolate, constructor, factory->symbol_species_string(),
                      factory->species_symbol(), Builtin::kReturnReceiver,
                      kAdapt);
}
References v8::internal::Isolate::factory(), v8::internal::kAdapt, and SimpleInstallGetter().
Referenced by v8::internal::Genesis::InitializeGlobal().
InstallToStringTag() [1/2]
void v8::internal::anonymous_namespace{bootstrapper.cc}::InstallToStringTag (Isolate * isolate, DirectHandle< JSObject > holder, const char * value)
Definition at line 742 of file bootstrapper.cc.
                                           {
  InstallToStringTag(isolate, holder,
                     isolate->factory()->InternalizeUtf8String(value));
}
References v8::internal::Isolate::factory(), v8::internal::Factory::InternalizeUtf8String(), and v8::internal::value.
Referenced by v8::internal::Genesis::CreateArrayBuffer(), v8::internal::Genesis::CreateAsyncFunctionMaps(), v8::internal::Genesis::CreateAsyncIteratorMaps(), v8::internal::Genesis::CreateIteratorMaps(), v8::internal::Genesis::InitializeConsole(), v8::internal::Genesis::InitializeGlobal(), and v8::internal::Genesis::InitializeIteratorFunctions().
InstallToStringTag() [2/2]
V8_NOINLINE void v8::internal::anonymous_namespace{bootstrapper.cc}::InstallToStringTag (Isolate * isolate, DirectHandle< JSObject > holder, DirectHandle< String > value)
Definition at line 734 of file bootstrapper.cc.
                                                                {
  JSObject::AddProperty(isolate, holder,
                        isolate->factory()->to_string_tag_symbol(), value,
                        static_cast<PropertyAttributes>(DONT_ENUM | READ_ONLY));
}
References v8::internal::JSObject::AddProperty(), v8::internal::DONT_ENUM, v8::internal::Isolate::factory(), v8::internal::READ_ONLY, and v8::internal::value.
InstallTrueValuedProperty()
V8_NOINLINE void v8::internal::anonymous_namespace{bootstrapper.cc}::InstallTrueValuedProperty (Isolate * isolate, DirectHandle< JSObject > holder, const char * name)
Definition at line 716 of file bootstrapper.cc.
                                                             {
  JSObject::AddProperty(isolate, holder,
                        isolate->factory()->InternalizeUtf8String(name),
                        isolate->factory()->true_value(), NONE);
}
References v8::internal::JSObject::AddProperty(), v8::internal::Isolate::factory(), v8::internal::Factory::InternalizeUtf8String(), v8::internal::name, and v8::internal::NONE.
Referenced by v8::internal::Genesis::InitializeGlobal().
ReplaceAccessors()
void v8::internal::anonymous_namespace{bootstrapper.cc}::ReplaceAccessors (Isolate * isolate, DirectHandle< Map > map, DirectHandle< String > name, PropertyAttributes attributes, DirectHandle< AccessorPair > accessor_pair)
Definition at line 1274 of file bootstrapper.cc.
                                                                {
  Tagged<DescriptorArray> descriptors = map->instance_descriptors(isolate);
  InternalIndex entry = descriptors->SearchWithCache(isolate, *name, *map);
  Descriptor d = Descriptor::AccessorConstant(name, accessor_pair, attributes);
  descriptors->Replace(entry, &d);
}
References v8::internal::Descriptor::AccessorConstant(), and v8::internal::name.
Referenced by v8::internal::Genesis::AddRestrictedFunctionProperties().
SetConstructorInstanceType()
V8_NOINLINE void v8::internal::anonymous_namespace{bootstrapper.cc}::SetConstructorInstanceType (Isolate * isolate, DirectHandle< JSFunction > constructor, InstanceType constructor_type)
Definition at line 574 of file bootstrapper.cc.
                                   {
  DCHECK(InstanceTypeChecker::IsJSFunction(constructor_type));
  DCHECK_NE(constructor_type, JS_FUNCTION_TYPE);
  Tagged<Map> map = constructor->map();
  // Check we don't accidentally change one of the existing maps.
  DCHECK_NE(map, *isolate->strict_function_map());
  DCHECK_NE(map, *isolate->strict_function_with_readonly_prototype_map());
  // Constructor function map is always a root map, and thus we don't have to
  // deal with updating the whole transition tree.
  DCHECK(IsUndefined(map->GetBackPointer(), isolate));
  DCHECK_EQ(JS_FUNCTION_TYPE, map->instance_type());
  map->set_instance_type(constructor_type);
}
References v8::internal::DCHECK(), DCHECK_EQ, and DCHECK_NE.
Referenced by v8::internal::Genesis::InitializeGlobal(), and v8::internal::Genesis::InstallTypedArray().
SimpleCreateFunction()
V8_NOINLINE Handle<JSFunction> v8::internal::anonymous_namespace{bootstrapper.cc}::SimpleCreateFunction (Isolate * isolate, DirectHandle< String > name, Builtin call, int len, AdaptArguments adapt)
Definition at line 593 of file bootstrapper.cc.
                                                                          {
  DCHECK(Builtins::HasJSLinkage(call));
  name = String::Flatten(isolate, name, AllocationType::kOld);
  Handle<JSFunction> fun =
      CreateFunctionForBuiltinWithoutPrototype(isolate, name, call, len, adapt);
  // Make the resulting JSFunction object fast.
  JSObject::MakePrototypesFast(fun, kStartAtReceiver, isolate);
  fun->shared()->set_native(true);
  return fun;
}
References CreateFunctionForBuiltinWithoutPrototype(), v8::internal::DCHECK(), v8::internal::Builtins::HasJSLinkage(), v8::internal::kOld, v8::internal::kStartAtReceiver, v8::internal::JSObject::MakePrototypesFast(), and v8::internal::name.
Referenced by v8::internal::Genesis::CreateIteratorMaps(), v8::internal::Genesis::InitializeGlobal(), InstallFunctionAtSymbol(), InstallFunctionWithBuiltinId(), v8::internal::SimpleInstallFunction(), SimpleInstallGetter(), and SimpleInstallGetterSetter().
SimpleInstallGetter() [1/2]
V8_NOINLINE Handle<JSFunction> v8::internal::anonymous_namespace{bootstrapper.cc}::SimpleInstallGetter (Isolate * isolate, DirectHandle< JSObject > base, DirectHandle< Name > name, Builtin call, AdaptArguments adapt)
Definition at line 700 of file bootstrapper.cc.
                                                                         {
  return SimpleInstallGetter(isolate, base, name, name, call, adapt);
}
References v8::internal::name.
Referenced by v8::internal::Genesis::CreateArrayBuffer(), v8::internal::Genesis::InitializeGlobal(), v8::internal::Genesis::InitializeGlobal_regexp_linear_flag(), and InstallSpeciesGetter().
SimpleInstallGetter() [2/2]
V8_NOINLINE Handle<JSFunction> v8::internal::anonymous_namespace{bootstrapper.cc}::SimpleInstallGetter (Isolate * isolate, DirectHandle< JSObject > base, DirectHandle< Name > name, DirectHandle< Name > property_name, Builtin call, AdaptArguments adapt)
Definition at line 682 of file bootstrapper.cc.
                                                                          {
  DirectHandle<String> getter_name =
      Name::ToFunctionName(isolate, name, isolate->factory()->get_string())
          .ToHandleChecked();
  Handle<JSFunction> getter =
      SimpleCreateFunction(isolate, getter_name, call, 0, adapt);
  DirectHandle<Object> setter = isolate->factory()->undefined_value();
  JSObject::DefineOwnAccessorIgnoreAttributes(base, property_name, getter,
                                              setter, DONT_ENUM)
      .Check();
  return getter;
}
References v8::internal::JSObject::DefineOwnAccessorIgnoreAttributes(), v8::internal::DONT_ENUM, v8::internal::Isolate::factory(), v8::internal::name, v8::internal::setter, SimpleCreateFunction(), and v8::internal::Name::ToFunctionName().
SimpleInstallGetterSetter() [1/2]
void v8::internal::anonymous_namespace{bootstrapper.cc}::SimpleInstallGetterSetter (Isolate * isolate, DirectHandle< JSObject > base, const char * name, Builtin call_getter, Builtin call_setter)
Definition at line 674 of file bootstrapper.cc.
                                                    {
  SimpleInstallGetterSetter(isolate, base,
                            isolate->factory()->InternalizeUtf8String(name),
                            call_getter, call_setter);
}
References v8::internal::Isolate::factory(), v8::internal::Factory::InternalizeUtf8String(), and v8::internal::name.
Referenced by v8::internal::Genesis::InitializeGlobal().
SimpleInstallGetterSetter() [2/2]
V8_NOINLINE void v8::internal::anonymous_namespace{bootstrapper.cc}::SimpleInstallGetterSetter (Isolate * isolate, DirectHandle< JSObject > base, DirectHandle< Name > name, Builtin call_getter, Builtin call_setter)
Definition at line 652 of file bootstrapper.cc.
                                                                {
  DirectHandle<String> getter_name =
      Name::ToFunctionName(isolate, name, isolate->factory()->get_string())
          .ToHandleChecked();
  DirectHandle<JSFunction> getter =
      SimpleCreateFunction(isolate, getter_name, call_getter, 0, kAdapt);
  DirectHandle<String> setter_name =
      Name::ToFunctionName(isolate, name, isolate->factory()->set_string())
          .ToHandleChecked();
  DirectHandle<JSFunction> setter =
      SimpleCreateFunction(isolate, setter_name, call_setter, 1, kAdapt);
  JSObject::DefineOwnAccessorIgnoreAttributes(base, name, getter, setter,
                                              DONT_ENUM)
      .Check();
}
References v8::internal::JSObject::DefineOwnAccessorIgnoreAttributes(), v8::internal::DONT_ENUM, v8::internal::Isolate::factory(), v8::internal::kAdapt, v8::internal::name, v8::internal::setter, SimpleCreateFunction(), and v8::internal::Name::ToFunctionName().