v8::internal::compiler::anonymous_namespace{checkpoint-elimination.cc} Namespace Reference
Functions
FrameStateFunctionInfo const * GetFunctionInfo (Node *checkpoint)
bool IsRedundantCheckpoint (Node *node)
Function Documentation
GetFunctionInfo()
FrameStateFunctionInfo const* v8::internal::compiler::anonymous_namespace{checkpoint-elimination.cc}::GetFunctionInfo (Node * checkpoint)
Definition at line 19 of file checkpoint-elimination.cc.
                                                                {
  DCHECK_EQ(IrOpcode::kCheckpoint, checkpoint->opcode());
  Node* frame_state = NodeProperties::GetFrameStateInput(checkpoint);
  return frame_state->opcode() == IrOpcode::kFrameState
             ? FrameStateInfoOf(frame_state->op()).function_info()
             : nullptr;
}
References DCHECK_EQ, v8::internal::compiler::FrameStateInfoOf(), v8::internal::compiler::FrameStateInfo::function_info(), v8::internal::compiler::NodeProperties::GetFrameStateInput(), v8::internal::compiler::Node::op(), and v8::internal::compiler::Node::opcode().
Referenced by IsRedundantCheckpoint().
IsRedundantCheckpoint()
bool v8::internal::compiler::anonymous_namespace{checkpoint-elimination.cc}::IsRedundantCheckpoint (Node * node)
Definition at line 38 of file checkpoint-elimination.cc.
                                       {
  FrameStateFunctionInfo const* function_info = GetFunctionInfo(node);
  if (function_info == nullptr) return false;
  Node* effect = NodeProperties::GetEffectInput(node);
  while (effect->op()->HasProperty(Operator::kNoWrite) &&
         effect->op()->EffectInputCount() == 1) {
    if (effect->opcode() == IrOpcode::kCheckpoint) {
      return GetFunctionInfo(effect) == function_info;
    }
    effect = NodeProperties::GetEffectInput(effect);
  }
  return false;
}
References v8::internal::compiler::Operator::EffectInputCount(), v8::internal::compiler::NodeProperties::GetEffectInput(), GetFunctionInfo(), v8::internal::compiler::Operator::HasProperty(), v8::internal::compiler::Operator::kNoWrite, v8::internal::compiler::Node::op(), and v8::internal::compiler::Node::opcode().
Referenced by v8::internal::compiler::CheckpointElimination::ReduceCheckpoint().