v8::internal::anonymous_namespace{objects.cc} Namespace Reference
Classes
struct FixedArrayAppender
Functions
bool IsErrorObject (Isolate *isolate, DirectHandle< Object > object)
DirectHandle< String > AsStringOrEmpty (Isolate *isolate, DirectHandle< Object > object)
DirectHandle< String > NoSideEffectsErrorToString (Isolate *isolate, DirectHandle< JSReceiver > error)
ComparisonResult StrictNumberCompare (double x, double y)
bool StrictNumberEquals (double x, double y)
bool StrictNumberEquals (const Tagged< Number > x, const Tagged< Number > y)
bool StrictNumberEquals (DirectHandle< Number > x, DirectHandle< Number > y)
ComparisonResult Reverse (ComparisonResult result)
MaybeDirectHandle< FixedArray > CreateListFromArrayLikeFastPath (Isolate *isolate, DirectHandle< Object > object, ElementTypes element_types)
template<class T >
int AppendUniqueCallbacks (Isolate *isolate, DirectHandle< ArrayList > callbacks, DirectHandle< typename T::Array > array, int valid_descriptors)
template<typename sinkchar >
void WriteFixedArrayToFlat (Tagged< FixedArray > fixed_array, int length, Tagged< String > separator, sinkchar *sink, int sink_length)
template<typename Char >
bool GetPositionInfoSlowImpl (base::Vector< Char > source, int position, Script::PositionInfo *info)
bool GetPositionInfoSlow (const Tagged< Script > script, int position, const DisallowGarbageCollection &no_gc, Script::PositionInfo *info)
int GetLineEnd (const String::LineEndsVector &vector, int line)
int GetLineEnd (const Tagged< FixedArray > &array, int line)
int GetLength (const String::LineEndsVector &vector)
int GetLength (const Tagged< FixedArray > &array)
template<typename LineEndsContainer >
bool GetLineEndsContainerPositionInfo (const LineEndsContainer &ends, int position, Script::PositionInfo *info, const DisallowGarbageCollection &no_gc)
template<typename T , template< typename > typename HandleType>
void RehashObjectHashTableAndGCIfNeeded (Isolate *isolate, HandleType< T > table)
Function Documentation
AppendUniqueCallbacks()
template<class T >
int v8::internal::anonymous_namespace{objects.cc}::AppendUniqueCallbacks (Isolate * isolate, DirectHandle< ArrayList > callbacks, DirectHandle< typename T::Array > array, int valid_descriptors)
Definition at line 2830 of file objects.cc.
                                                 {
  int nof_callbacks = callbacks->length();
  // Fill in new callback descriptors. Process the callbacks from
  // back to front so that the last callback with a given name takes
  // precedence over previously added callbacks with that name.
  for (int i = nof_callbacks - 1; i >= 0; i--) {
    DirectHandle<AccessorInfo> entry(Cast<AccessorInfo>(callbacks->get(i)),
                                     isolate);
    DirectHandle<Name> key(Cast<Name>(entry->name()), isolate);
    DCHECK(IsUniqueName(*key));
    // Check if a descriptor with this name already exists before writing.
    if (!T::Contains(key, entry, valid_descriptors, array)) {
      T::Insert(key, entry, valid_descriptors, array);
      valid_descriptors++;
    }
  }
  return valid_descriptors;
}
References v8::internal::anonymous_namespace{read-only-promotion.cc}::Contains(), v8::internal::DCHECK(), v8::internal::IsUniqueName(), and v8::internal::key.
AsStringOrEmpty()
DirectHandle<String> v8::internal::anonymous_namespace{objects.cc}::AsStringOrEmpty (Isolate * isolate, DirectHandle< Object > object)
Definition at line 532 of file objects.cc.
                                                                  {
  return IsString(*object) ? Cast<String>(object)
                           : isolate->factory()->empty_string();
}
References v8::internal::Isolate::factory().
Referenced by NoSideEffectsErrorToString().
CreateListFromArrayLikeFastPath()
MaybeDirectHandle<FixedArray> v8::internal::anonymous_namespace{objects.cc}::CreateListFromArrayLikeFastPath (Isolate * isolate, DirectHandle< Object > object, ElementTypes element_types)
Definition at line 1145 of file objects.cc.
                                                                               {
  if (element_types == ElementTypes::kAll) {
    if (IsJSArray(*object)) {
      DirectHandle<JSArray> array = Cast<JSArray>(object);
      uint32_t length;
      if (!array->HasArrayPrototype(isolate) ||
          !Object::ToUint32(array->length(), &length) ||
          !array->HasFastElements() ||
          !JSObject::PrototypeHasNoElements(isolate, *array)) {
        return MaybeDirectHandle<FixedArray>();
      }
      return array->GetElementsAccessor()->CreateListFromArrayLike(
          isolate, array, length);
    } else if (IsJSTypedArray(*object)) {
      DirectHandle<JSTypedArray> array = Cast<JSTypedArray>(object);
      size_t length = array->GetLength();
      if (array->IsDetachedOrOutOfBounds() ||
          length > static_cast<size_t>(FixedArray::kMaxLength)) {
        return MaybeDirectHandle<FixedArray>();
      }
      static_assert(FixedArray::kMaxLength <=
                    std::numeric_limits<uint32_t>::max());
      return array->GetElementsAccessor()->CreateListFromArrayLike(
          isolate, array, static_cast<uint32_t>(length));
    }
  }
  return MaybeDirectHandle<FixedArray>();
}
References v8::internal::kAll, v8::internal::FixedArray::kMaxLength, v8::internal::length, v8::internal::JSObject::PrototypeHasNoElements(), and v8::internal::Object::ToUint32().
Referenced by v8::internal::Object::CreateListFromArrayLike().
GetLength() [1/2]
int v8::internal::anonymous_namespace{objects.cc}::GetLength (const String::LineEndsVector & vector)
Definition at line 4586 of file objects.cc.
                                                  {
  return static_cast<int>(vector.size());
}
References v8::base::SmallVector< T, kSize, Allocator >::size().
GetLength() [2/2]
int v8::internal::anonymous_namespace{objects.cc}::GetLength (const Tagged< FixedArray > & array)
Definition at line 4590 of file objects.cc.
{ return array->length(); }
GetLineEnd() [1/2]
int v8::internal::anonymous_namespace{objects.cc}::GetLineEnd (const String::LineEndsVector & vector, int line)
Definition at line 4578 of file objects.cc.
                                                             {
  return vector[line];
}
Referenced by v8::internal::anonymous_namespace{liveedit.cc}::LineEndsWrapper::GetLineStart().
GetLineEnd() [2/2]
int v8::internal::anonymous_namespace{objects.cc}::GetLineEnd (const Tagged< FixedArray > & array, int line)
Definition at line 4582 of file objects.cc.
                                                          {
  return Smi::ToInt(array->get(line));
}
References v8::internal::Smi::ToInt().
Referenced by GetLineEndsContainerPositionInfo(), and v8::internal::Script::GetPositionInfoInternal().
GetLineEndsContainerPositionInfo()
template<typename LineEndsContainer >
bool v8::internal::anonymous_namespace{objects.cc}::GetLineEndsContainerPositionInfo (const LineEndsContainer & ends, int position, Script::PositionInfo * info, const DisallowGarbageCollection & no_gc)
Definition at line 4593 of file objects.cc.
                                                                              {
  const int ends_len = GetLength(ends);
  if (ends_len == 0) return false;
  // Return early on invalid positions. Negative positions behave as if 0 was
  // passed, and positions beyond the end of the script return as failure.
  if (position < 0) {
    position = 0;
  } else if (position > GetLineEnd(ends, ends_len - 1)) {
    return false;
  }
  // Determine line number by doing a binary search on the line ends array.
  if (GetLineEnd(ends, 0) >= position) {
    info->line = 0;
    info->line_start = 0;
    info->column = position;
  } else {
    int left = 0;
    int right = ends_len - 1;
    while (right > 0) {
      DCHECK_LE(left, right);
      const int mid = left + (right - left) / 2;
      if (position > GetLineEnd(ends, mid)) {
        left = mid + 1;
      } else if (position <= GetLineEnd(ends, mid - 1)) {
        right = mid - 1;
      } else {
        info->line = mid;
        break;
      }
    }
    DCHECK(GetLineEnd(ends, info->line) >= position &&
           GetLineEnd(ends, info->line - 1) < position);
    info->line_start = GetLineEnd(ends, info->line - 1) + 1;
    info->column = position - info->line_start;
  }
  return true;
}
References v8::internal::Script::PositionInfo::column, v8::internal::DCHECK(), DCHECK_LE, v8::internal::GetLength(), GetLineEnd(), v8::internal::Script::PositionInfo::line, and v8::internal::Script::PositionInfo::line_start.
Referenced by v8::internal::Script::GetLineColumnWithLineEnds(), and v8::internal::Script::GetPositionInfoInternal().
GetPositionInfoSlow()
bool v8::internal::anonymous_namespace{objects.cc}::GetPositionInfoSlow (const Tagged< Script > script, int position, const DisallowGarbageCollection & no_gc, Script::PositionInfo * info)
Definition at line 4565 of file objects.cc.
                                                   {
  if (!IsString(script->source())) {
    return false;
  }
  auto source = Cast<String>(script->source());
  const auto flat = source->GetFlatContent(no_gc);
  return flat.IsOneByte()
             ? GetPositionInfoSlowImpl(flat.ToOneByteVector(), position, info)
             : GetPositionInfoSlowImpl(flat.ToUC16Vector(), position, info);
}
References GetPositionInfoSlowImpl(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::script.
Referenced by v8::internal::Script::GetPositionInfo().
GetPositionInfoSlowImpl()
template<typename Char >
bool v8::internal::anonymous_namespace{objects.cc}::GetPositionInfoSlowImpl (base::Vector< Char > source, int position, Script::PositionInfo * info)
Definition at line 4542 of file objects.cc.
                                                       {
  DCHECK(DisallowPositionInfoSlow::IsAllowed());
  if (position < 0) {
    position = 0;
  }
  int line = 0;
  const auto begin = std::cbegin(source);
  const auto end = std::cend(source);
  for (auto line_begin = begin; line_begin < end;) {
    const auto line_end = std::find(line_begin, end, '\n');
    if (position <= (line_end - begin)) {
      info->line = line;
      info->column = static_cast<int>((begin + position) - line_begin);
      info->line_start = static_cast<int>(line_begin - begin);
      info->line_end = static_cast<int>(line_end - begin);
      return true;
    }
    ++line;
    line_begin = line_end + 1;
  }
  return false;
}
References v8::internal::compiler::begin(), v8::internal::Script::PositionInfo::column, v8::internal::DCHECK(), v8::internal::compiler::end(), v8::internal::Script::PositionInfo::line, v8::internal::Script::PositionInfo::line_end, and v8::internal::Script::PositionInfo::line_start.
Referenced by GetPositionInfoSlow().
IsErrorObject()
bool v8::internal::anonymous_namespace{objects.cc}::IsErrorObject (Isolate * isolate, DirectHandle< Object > object)
Definition at line 526 of file objects.cc.
                                                                  {
  if (!IsJSObject(*object)) return false;
  return ErrorUtils::HasErrorStackSymbolOwnProperty(isolate,
                                                    Cast<JSObject>(object));
}
References v8::internal::ErrorUtils::HasErrorStackSymbolOwnProperty().
Referenced by v8::internal::Object::NoSideEffectsToMaybeString().
NoSideEffectsErrorToString()
DirectHandle<String> v8::internal::anonymous_namespace{objects.cc}::NoSideEffectsErrorToString (Isolate * isolate, DirectHandle< JSReceiver > error)
Definition at line 538 of file objects.cc.
                                                      {
  DirectHandle<Name> name_key = isolate->factory()->name_string();
  DirectHandle<Object> name =
      JSReceiver::GetDataProperty(isolate, error, name_key);
  DirectHandle<String> name_str = AsStringOrEmpty(isolate, name);
  DirectHandle<Name> msg_key = isolate->factory()->message_string();
  DirectHandle<Object> msg =
      JSReceiver::GetDataProperty(isolate, error, msg_key);
  DirectHandle<String> msg_str = AsStringOrEmpty(isolate, msg);
  if (name_str->length() == 0) return msg_str;
  if (msg_str->length() == 0) return name_str;
  constexpr const char error_suffix[] = "<a very large string>";
  constexpr uint32_t error_suffix_size = sizeof(error_suffix);
  uint32_t suffix_size = std::min(error_suffix_size, msg_str->length());
  IncrementalStringBuilder builder(isolate);
  if (name_str->length() + suffix_size + 2 /* ": " */ > String::kMaxLength) {
    constexpr const char connector[] = "... : ";
    int connector_size = sizeof(connector);
    DirectHandle<String> truncated_name =
        isolate->factory()->NewProperSubString(
            name_str, 0,
            name_str->length() - error_suffix_size - connector_size);
    builder.AppendString(truncated_name);
    builder.AppendCStringLiteral(connector);
    builder.AppendCStringLiteral(error_suffix);
  } else {
    builder.AppendString(name_str);
    builder.AppendCStringLiteral(": ");
    if (builder.Length() + msg_str->length() <= String::kMaxLength) {
      builder.AppendString(msg_str);
    } else {
      builder.AppendCStringLiteral(error_suffix);
    }
  }
  return builder.Finish().ToHandleChecked();
}
References v8::internal::IncrementalStringBuilder::AppendCStringLiteral(), v8::internal::IncrementalStringBuilder::AppendString(), AsStringOrEmpty(), v8::internal::Isolate::factory(), v8::internal::IncrementalStringBuilder::Finish(), v8::internal::JSReceiver::GetDataProperty(), v8::internal::String::kMaxLength, v8::internal::IncrementalStringBuilder::Length(), v8::internal::name, and v8::internal::Factory::NewProperSubString().
Referenced by v8::internal::Object::NoSideEffectsToMaybeString().
RehashObjectHashTableAndGCIfNeeded()
template<typename T , template< typename > typename HandleType>
void v8::internal::anonymous_namespace{objects.cc}::RehashObjectHashTableAndGCIfNeeded (Isolate * isolate, HandleType< T > table)
Definition at line 6127 of file objects.cc.
                                                                               {
  // Rehash if more than 33% of the entries are deleted entries.
  // TODO(verwaest): Consider to shrink the fixed array in place.
  if ((table->NumberOfDeletedElements() << 1) > table->NumberOfElements()) {
    table->Rehash(isolate);
  }
  // If we're out of luck, we didn't get a GC recently, and so rehashing
  // isn't enough to avoid a crash.
  if (!table->HasSufficientCapacityToAdd(1)) {
    uint32_t nof = table->NumberOfElements() + 1;
    uint32_t capacity = T::ComputeCapacity(nof);
    if (capacity > T::kMaxCapacity) {
      for (size_t i = 0; i < 2; ++i) {
        isolate->heap()->CollectAllGarbage(
            GCFlag::kNoFlags, GarbageCollectionReason::kFullHashtable);
      }
      table->Rehash(isolate);
    }
  }
}
References v8::internal::Heap::CollectAllGarbage(), v8::internal::Isolate::heap(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::kFullHashtable, and v8::internal::kNoFlags.
Referenced by v8::internal::ObjectMultiHashTableBase< Derived, N >::Put().
Reverse()
ComparisonResult v8::internal::anonymous_namespace{objects.cc}::Reverse (ComparisonResult result)
Definition at line 830 of file objects.cc.
                                                  {
  if (result == ComparisonResult::kLessThan) {
    return ComparisonResult::kGreaterThan;
  }
  if (result == ComparisonResult::kGreaterThan) {
    return ComparisonResult::kLessThan;
  }
  return result;
}
References v8::internal::kGreaterThan, v8::internal::kLessThan, and v8::base::internal::result.
Referenced by v8::internal::Object::Compare().
StrictNumberCompare()
ComparisonResult v8::internal::anonymous_namespace{objects.cc}::StrictNumberCompare (double x, double y)
Definition at line 802 of file objects.cc.
                                                         {
  if (std::isnan(x) || std::isnan(y)) {
    return ComparisonResult::kUndefined;
  } else if (x < y) {
    return ComparisonResult::kLessThan;
  } else if (x > y) {
    return ComparisonResult::kGreaterThan;
  } else {
    return ComparisonResult::kEqual;
  }
}
References v8::internal::kEqual, v8::internal::kGreaterThan, v8::internal::kLessThan, v8::internal::kUndefined, and v8::internal::y.
Referenced by v8::internal::Object::Compare().
StrictNumberEquals() [1/3]
bool v8::internal::anonymous_namespace{objects.cc}::StrictNumberEquals (const Tagged< Number > x, const Tagged< Number > y)
Definition at line 822 of file objects.cc.
                                                                        {
  return StrictNumberEquals(Object::NumberValue(x), Object::NumberValue(y));
}
References v8::internal::Object::NumberValue(), StrictNumberEquals(), and v8::internal::y.
StrictNumberEquals() [2/3]
bool v8::internal::anonymous_namespace{objects.cc}::StrictNumberEquals (DirectHandle< Number > x, DirectHandle< Number > y)
Definition at line 826 of file objects.cc.
                                                                        {
  return StrictNumberEquals(*x, *y);
}
References v8::internal::y.
Referenced by v8::internal::Object::Equals(), v8::internal::Object::StrictEquals(), and StrictNumberEquals().
StrictNumberEquals() [3/3]
bool v8::internal::anonymous_namespace{objects.cc}::StrictNumberEquals (double x, double y)
Definition at line 816 of file objects.cc.
                                            {
  // Must check explicitly for NaN's on Windows, but -0 works fine.
  if (std::isnan(x) || std::isnan(y)) return false;
  return x == y;
}
References v8::internal::y.
WriteFixedArrayToFlat()
template<typename sinkchar >
void v8::internal::anonymous_namespace{objects.cc}::WriteFixedArrayToFlat (Tagged< FixedArray > fixed_array, int length, Tagged< String > separator, sinkchar * sink, int sink_length)
Definition at line 4161 of file objects.cc.
                                            {
  DisallowGarbageCollection no_gc;
  CHECK_GT(length, 0);
  CHECK_LE(length, fixed_array->length());
#ifdef DEBUG
  sinkchar* sink_end = sink + sink_length;
#endif
  const int separator_length = separator->length();
  const bool use_one_byte_separator_fast_path =
      separator_length == 1 && sizeof(sinkchar) == 1 &&
      StringShape(separator).IsSequentialOneByte();
  uint8_t separator_one_char;
  if (use_one_byte_separator_fast_path) {
    CHECK(StringShape(separator).IsSequentialOneByte());
    CHECK_EQ(separator->length(), 1);
    separator_one_char = Cast<SeqOneByteString>(separator)->GetChars(no_gc)[0];
  }
  uint32_t num_separators = 0;
  uint32_t repeat_last = 0;
  for (int i = 0; i < length; i++) {
    Tagged<Object> element = fixed_array->get(i);
    const bool element_is_special = IsSmi(element);
    // If element is a positive Smi, it represents the number of separators to
    // write. If it is a negative Smi, it represents the number of times the
    // last string is repeated.
    if (V8_UNLIKELY(element_is_special)) {
      int count;
      CHECK(Object::ToInt32(element, &count));
      if (count > 0) {
        num_separators = count;
        // Verify that Smis (number of separators) only occur when necessary:
        // 1) at the beginning
        // 2) at the end
        // 3) when the number of separators > 1
        // - It is assumed that consecutive Strings will have one
        // separator,
        // so there is no need for a Smi.
        DCHECK(i == 0 || i == length - 1 || num_separators > 1);
      } else {
        repeat_last = -count;
        // Repeat is only possible when the previous element is not special.
        DCHECK_GT(i, 0);
        DCHECK(IsString(fixed_array->get(i - 1)));
      }
    }
    // Write separator(s) if necessary.
    if (num_separators > 0 && separator_length > 0) {
      // TODO(pwong): Consider doubling strategy employed by runtime-strings.cc
      // WriteRepeatToFlat().
      // Fast path for single character, single byte separators.
      if (use_one_byte_separator_fast_path) {
        DCHECK_LE(sink + num_separators, sink_end);
        memset(sink, separator_one_char, num_separators);
        DCHECK_EQ(separator_length, 1);
        sink += num_separators;
      } else {
        for (uint32_t j = 0; j < num_separators; j++) {
          DCHECK_LE(sink + separator_length, sink_end);
          String::WriteToFlat(separator, sink, 0, separator_length);
          sink += separator_length;
        }
      }
      num_separators = 0;
    }
    // Repeat the last written string |repeat_last| times (including
    // separators).
    if (V8_UNLIKELY(repeat_last > 0)) {
      Tagged<Object> last_element = fixed_array->get(i - 1);
      int string_length = Cast<String>(last_element)->length();
      // The implemented logic requires that string length is > 0. Empty strings
      // are handled by repeating the separator (positive smi in the fixed
      // array) already.
      DCHECK_GT(string_length, 0);
      int length_with_sep = string_length + separator_length;
      // Only copy separators between elements, not at the start or beginning.
      sinkchar* copy_end =
          sink + (length_with_sep * repeat_last) - separator_length;
      int copy_length = length_with_sep;
      while (sink < copy_end - copy_length) {
        DCHECK_LE(sink + copy_length, sink_end);
        memcpy(sink, sink - copy_length, copy_length * sizeof(sinkchar));
        sink += copy_length;
        copy_length *= 2;
      }
      int remaining = static_cast<int>(copy_end - sink);
      if (remaining > 0) {
        DCHECK_LE(sink + remaining, sink_end);
        memcpy(sink, sink - remaining - separator_length,
               remaining * sizeof(sinkchar));
        sink += remaining;
      }
      repeat_last = 0;
      num_separators = 1;
    }
    if (V8_LIKELY(!element_is_special)) {
      DCHECK(IsString(element));
      Tagged<String> string = Cast<String>(element);
      const int string_length = string->length();
      DCHECK(string_length == 0 || sink < sink_end);
      String::WriteToFlat(string, sink, 0, string_length);
      sink += string_length;
      // Next string element, needs at least one separator preceding it.
      num_separators = 1;
    }
  }
  // Verify we have written to the end of the sink.
  DCHECK_EQ(sink, sink_end);
}
References CHECK, CHECK_EQ, CHECK_GT, CHECK_LE, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GT, DCHECK_LE, v8::internal::StringShape::IsSequentialOneByte(), v8::internal::IsSmi(), v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::separator, v8::internal::Object::ToInt32(), V8_LIKELY, V8_UNLIKELY, and v8::internal::String::WriteToFlat().
Referenced by v8::internal::JSArray::ArrayJoinConcatToSequentialString().