v8::internal::anonymous_namespace{debug-property-iterator.cc} Namespace Reference
Functions
base::Flags< debug::NativeAccessorType, int > GetNativeAccessorDescriptorInternal (DirectHandle< JSReceiver > object, DirectHandle< Name > name)
Function Documentation
GetNativeAccessorDescriptorInternal()
base::Flags<debug::NativeAccessorType, int> v8::internal::anonymous_namespace{debug-property-iterator.cc}::GetNativeAccessorDescriptorInternal (DirectHandle< JSReceiver > object, DirectHandle< Name > name)
Definition at line 213 of file debug-property-iterator.cc.
                                                              {
  Isolate* isolate = Isolate::Current();
  PropertyKey key(isolate, name);
  if (key.is_element()) return debug::NativeAccessorType::None;
  LookupIterator it(isolate, object, key, LookupIterator::OWN);
  if (!it.IsFound()) return debug::NativeAccessorType::None;
  if (it.state() != LookupIterator::ACCESSOR) {
    return debug::NativeAccessorType::None;
  }
  DirectHandle<Object> structure = it.GetAccessors();
  if (!IsAccessorInfo(*structure)) return debug::NativeAccessorType::None;
  base::Flags<debug::NativeAccessorType, int> result;
  if (*structure == *isolate->factory()->value_unavailable_accessor()) {
    return debug::NativeAccessorType::IsValueUnavailable;
  }
#define IS_BUILTIN_ACCESSOR(_, name, ...) \
  if (*structure == *isolate->factory()->name##_accessor()) \
    return debug::NativeAccessorType::None;
  ACCESSOR_INFO_LIST_GENERATOR(IS_BUILTIN_ACCESSOR, /* not used */)
#undef IS_BUILTIN_ACCESSOR
  auto accessor_info = Cast<AccessorInfo>(structure);
  if (accessor_info->has_getter(isolate)) {
    result |= debug::NativeAccessorType::HasGetter;
  }
  if (accessor_info->has_setter(isolate)) {
    result |= debug::NativeAccessorType::HasSetter;
  }
  return result;
}
References v8::internal::LookupIterator::ACCESSOR, ACCESSOR_INFO_LIST_GENERATOR, v8::internal::Isolate::Current(), v8::internal::Isolate::factory(), v8::internal::LookupIterator::GetAccessors(), v8::debug::HasGetter, v8::debug::HasSetter, IS_BUILTIN_ACCESSOR, v8::internal::LookupIterator::IsFound(), v8::debug::IsValueUnavailable, v8::internal::key, v8::internal::name, v8::debug::None, v8::internal::LookupIterator::OWN, v8::base::internal::result, and v8::internal::LookupIterator::state().
Referenced by v8::internal::DebugPropertyIterator::CalculateNativeAccessorFlags().