v8::internal::anonymous_namespace{bigint.cc} Namespace Reference
Functions
ComparisonResult UnequalSign (bool left_negative)
ComparisonResult AbsoluteGreater (bool both_negative)
ComparisonResult AbsoluteLess (bool both_negative)
void RightTrimString (Isolate *isolate, DirectHandle< SeqOneByteString > string, int chars_allocated, int chars_written)
Function Documentation
AbsoluteGreater()
ComparisonResult v8::internal::anonymous_namespace{bigint.cc}::AbsoluteGreater (bool both_negative)
Definition at line 561 of file bigint.cc.
                                                     {
  return both_negative ? ComparisonResult::kLessThan
                       : ComparisonResult::kGreaterThan;
}
References v8::internal::kGreaterThan, and v8::internal::kLessThan.
Referenced by v8::internal::BigInt::CompareToBigInt(), v8::internal::BigInt::CompareToDouble(), and v8::internal::BigInt::CompareToNumber().
AbsoluteLess()
ComparisonResult v8::internal::anonymous_namespace{bigint.cc}::AbsoluteLess (bool both_negative)
Definition at line 567 of file bigint.cc.
                                                  {
  return both_negative ? ComparisonResult::kGreaterThan
                       : ComparisonResult::kLessThan;
}
References v8::internal::kGreaterThan, and v8::internal::kLessThan.
Referenced by v8::internal::BigInt::CompareToBigInt(), v8::internal::BigInt::CompareToDouble(), and v8::internal::BigInt::CompareToNumber().
RightTrimString()
void v8::internal::anonymous_namespace{bigint.cc}::RightTrimString (Isolate * isolate, DirectHandle< SeqOneByteString > string, int chars_allocated, int chars_written)
Definition at line 814 of file bigint.cc.
                                                             {
  DCHECK_LE(chars_written, chars_allocated);
  if (chars_written == chars_allocated) return;
  int string_size =
      ALIGN_TO_ALLOCATION_ALIGNMENT(SeqOneByteString::SizeFor(chars_allocated));
  int needed_size =
      ALIGN_TO_ALLOCATION_ALIGNMENT(SeqOneByteString::SizeFor(chars_written));
  if (needed_size < string_size && !isolate->heap()->IsLargeObject(*string)) {
    isolate->heap()->NotifyObjectSizeChange(*string, string_size, needed_size,
                                            ClearRecordedSlots::kNo);
  }
  string->set_length(chars_written, kReleaseStore);
}
References ALIGN_TO_ALLOCATION_ALIGNMENT, DCHECK_LE, v8::internal::Isolate::heap(), heap(), v8::internal::kNo, v8::kReleaseStore, v8::internal::Heap::NotifyObjectSizeChange(), and v8::internal::SeqOneByteString::SizeFor().
Referenced by v8::internal::BigInt::NoSideEffectsToString(), and v8::internal::BigInt::ToString().
UnequalSign()
ComparisonResult v8::internal::anonymous_namespace{bigint.cc}::UnequalSign (bool left_negative)
Definition at line 555 of file bigint.cc.
                                                 {
  return left_negative ? ComparisonResult::kLessThan
                       : ComparisonResult::kGreaterThan;
}
References v8::internal::kGreaterThan, and v8::internal::kLessThan.
Referenced by v8::internal::BigInt::CompareToBigInt(), v8::internal::BigInt::CompareToDouble(), and v8::internal::BigInt::CompareToNumber().