v8::internal::anonymous_namespace{source-position-table.cc} Namespace Reference
Typedefs
using MoreBit = base::BitField8< bool, 7, 1 >
using ValueBits = base::BitField8< unsigned, 0, 7 >
Functions
void AddAndSetEntry (PositionTableEntry *value, const PositionTableEntry &other)
void SubtractFromEntry (PositionTableEntry *value, const PositionTableEntry &other)
template<typename T >
void EncodeUInt (ZoneVector< uint8_t > *bytes, T value)
template<typename T >
void EncodeInt (ZoneVector< uint8_t > *bytes, T value)
void EncodeEntry (ZoneVector< uint8_t > *bytes, const PositionTableEntry &entry)
template<typename T >
T DecodeUInt (base::Vector< const uint8_t > bytes, int *index)
template<typename T >
T DecodeInt (base::Vector< const uint8_t > bytes, int *index)
void DecodeEntry (base::Vector< const uint8_t > bytes, int *index, PositionTableEntry *entry)
base::Vector< const uint8_t > VectorFromByteArray (Tagged< TrustedByteArray > byte_array)
Typedef Documentation
MoreBit
using v8::internal::anonymous_namespace{source-position-table.cc}::MoreBit = typedef base::BitField8<bool, 7, 1>
Definition at line 34 of file source-position-table.cc.
ValueBits
using v8::internal::anonymous_namespace{source-position-table.cc}::ValueBits = typedef base::BitField8<unsigned, 0, 7>
Definition at line 35 of file source-position-table.cc.
Function Documentation
AddAndSetEntry()
void v8::internal::anonymous_namespace{source-position-table.cc}::AddAndSetEntry (PositionTableEntry * value, const PositionTableEntry & other)
Definition at line 38 of file source-position-table.cc.
                                                     {
  value->code_offset += other.code_offset;
  DCHECK_IMPLIES(value->code_offset != kFunctionEntryBytecodeOffset,
                 value->code_offset >= 0);
  value->source_position += other.source_position;
  DCHECK_LE(0, value->source_position);
  value->is_statement = other.is_statement;
  value->is_breakable = other.is_breakable;
}
References v8::internal::PositionTableEntry::code_offset, DCHECK_IMPLIES, DCHECK_LE, v8::internal::PositionTableEntry::is_breakable, v8::internal::PositionTableEntry::is_statement, v8::internal::kFunctionEntryBytecodeOffset, v8::internal::PositionTableEntry::source_position, and v8::internal::value.
Referenced by v8::internal::SourcePositionTableIterator::Advance().
DecodeEntry()
void v8::internal::anonymous_namespace{source-position-table.cc}::DecodeEntry (base::Vector< const uint8_t > bytes, int * index, PositionTableEntry * entry)
Definition at line 125 of file source-position-table.cc.
                                            {
  // The least significant bit is used to encode is_breakable.
  // The second least significant bit is used to encode is_statement.
  int tmp = DecodeUInt<int>(bytes, index);
  entry->code_offset = tmp >> 2;
  entry->is_breakable = (tmp & 0b10) >> 1;
  entry->is_statement = tmp & 1;
  entry->source_position = DecodeInt<int64_t>(bytes, index);
}
References v8::internal::PositionTableEntry::code_offset, v8::internal::index, v8::internal::PositionTableEntry::is_breakable, v8::internal::PositionTableEntry::is_statement, and v8::internal::PositionTableEntry::source_position.
Referenced by v8::internal::SourcePositionTableIterator::Advance().
DecodeInt()
template<typename T >
T v8::internal::anonymous_namespace{source-position-table.cc}::DecodeInt (base::Vector< const uint8_t > bytes, int * index)
Definition at line 117 of file source-position-table.cc.
                                                         {
  using unsigned_type = std::make_unsigned_t<T>;
  unsigned_type zigzag_value = DecodeUInt<unsigned_type>(bytes, index);
  T result = static_cast<T>((zigzag_value >> 1) ^ (-(zigzag_value & 1)));
  return result;
}
References v8::internal::index, and v8::base::internal::result.
DecodeUInt()
template<typename T >
T v8::internal::anonymous_namespace{source-position-table.cc}::DecodeUInt (base::Vector< const uint8_t > bytes, int * index)
Definition at line 99 of file source-position-table.cc.
                                                          {
  uint8_t current;
  int shift = 0;
  T decoded = 0;
  bool more;
  do {
    current = bytes[(*index)++];
    decoded |= static_cast<std::make_unsigned_t<T>>(ValueBits::decode(current))
               << shift;
    more = MoreBit::decode(current);
    shift += ValueBits::kSize;
  } while (more);
  DCHECK_GE(decoded, 0);
  return decoded;
}
References DCHECK_GE.
EncodeEntry()
void v8::internal::anonymous_namespace{source-position-table.cc}::EncodeEntry (ZoneVector< uint8_t > * bytes, const PositionTableEntry & entry)
Definition at line 82 of file source-position-table.cc.
                                                                              {
  // We only accept ascending code offsets.
  DCHECK_LE(0, entry.code_offset);
  // All but the first entry must be *strictly* ascending (no two entries for
  // the same position).
  // TODO(11496): This DCHECK fails tests.
  // DCHECK_IMPLIES(!bytes->empty(), entry.code_offset > 0);
  // The least significant bit is used to encode is_breakable.
  // The second least significant bit is used to encode is_statement.
  uint32_t encoded_entry = (entry.code_offset << 2) |
                           (entry.is_breakable << 1) | (entry.is_statement);
  EncodeUInt(bytes, encoded_entry);
  EncodeInt(bytes, entry.source_position);
}
References v8::internal::PositionTableEntry::code_offset, DCHECK_LE, EncodeInt(), EncodeUInt(), v8::internal::PositionTableEntry::is_breakable, v8::internal::PositionTableEntry::is_statement, and v8::internal::PositionTableEntry::source_position.
Referenced by v8::internal::SourcePositionTableBuilder::AddEntry().
EncodeInt()
template<typename T >
void v8::internal::anonymous_namespace{source-position-table.cc}::EncodeInt (ZoneVector< uint8_t > * bytes, T value) [inline]
Definition at line 70 of file source-position-table.cc.
                                                           {
  using unsigned_type = std::make_unsigned_t<T>;
  // Zig-zag encoding.
  static constexpr int kShift = sizeof(T) * kBitsPerByte - 1;
  value = ((static_cast<unsigned_type>(value) << 1) ^ (value >> kShift));
  DCHECK_GE(value, 0);
  unsigned_type encoded = static_cast<unsigned_type>(value);
  EncodeUInt(bytes, encoded);
}
References DCHECK_GE, EncodeUInt(), v8::internal::kBitsPerByte, T, and v8::internal::value.
Referenced by EncodeEntry().
EncodeUInt()
template<typename T >
void v8::internal::anonymous_namespace{source-position-table.cc}::EncodeUInt (ZoneVector< uint8_t > * bytes, T value) [inline]
Definition at line 57 of file source-position-table.cc.
                                                            {
  bool more;
  do {
    more = value > ValueBits::kMax;
    uint8_t current =
        MoreBit::encode(more) | ValueBits::encode(value & ValueBits::kMask);
    bytes->push_back(current);
    value >>= ValueBits::kSize;
  } while (more);
}
References v8::internal::ZoneVector< T >::push_back(), and v8::internal::value.
Referenced by EncodeEntry(), and EncodeInt().
SubtractFromEntry()
void v8::internal::anonymous_namespace{source-position-table.cc}::SubtractFromEntry (PositionTableEntry * value, const PositionTableEntry & other)
Definition at line 50 of file source-position-table.cc.
                                                        {
  value->code_offset -= other.code_offset;
  value->source_position -= other.source_position;
}
References v8::internal::PositionTableEntry::code_offset, v8::internal::PositionTableEntry::source_position, and v8::internal::value.
Referenced by v8::internal::SourcePositionTableBuilder::AddEntry().
VectorFromByteArray()
base::Vector<const uint8_t> v8::internal::anonymous_namespace{source-position-table.cc}::VectorFromByteArray (Tagged< TrustedByteArray > byte_array)
Definition at line 136 of file source-position-table.cc.
                                         {
  return base::Vector<const uint8_t>(byte_array->begin(), byte_array->length());
}
Referenced by v8::internal::SourcePositionTableIterator::Advance().