v8::internal::anonymous_namespace{messages.cc} Namespace Reference
Classes
class PrepareStackTraceScope
Functions
MaybeDirectHandle< JSArray > GetStackFrames (Isolate *isolate, DirectHandle< FixedArray > frames)
MaybeDirectHandle< Object > AppendErrorString (Isolate *isolate, DirectHandle< Object > error, IncrementalStringBuilder *builder)
MaybeHandle< String > GetStringPropertyOrDefault (Isolate *isolate, DirectHandle< JSReceiver > recv, DirectHandle< String > key, Handle< String > default_str)
bool ComputeLocation (Isolate *isolate, MessageLocation *target)
DirectHandle< String > BuildDefaultCallSite (Isolate *isolate, DirectHandle< Object > object)
DirectHandle< String > RenderCallSite (Isolate *isolate, DirectHandle< Object > object, MessageLocation *location, CallPrinter::ErrorHint *hint)
MessageTemplate UpdateErrorTemplate (CallPrinter::ErrorHint hint, MessageTemplate default_id)
Function Documentation
AppendErrorString()
MaybeDirectHandle<Object> v8::internal::anonymous_namespace{messages.cc}::AppendErrorString (Isolate * isolate, DirectHandle< Object > error, IncrementalStringBuilder * builder)
Definition at line 228 of file messages.cc.
                                                                               {
  v8::TryCatch try_catch(reinterpret_cast<v8::Isolate*>(isolate));
  try_catch.SetVerbose(false);
  try_catch.SetCaptureMessage(false);
  MaybeDirectHandle<String> err_str = ErrorUtils::ToString(
      isolate, Cast<Object>(error),
      ErrorUtils::ToStringMessageSource::kPreferOriginalMessage);
  if (err_str.is_null()) {
    // Error.toString threw. Try to return a string representation of the thrown
    // exception instead.
    DCHECK(isolate->has_exception());
    if (isolate->is_execution_terminating()) {
      return {};
    }
    DirectHandle<Object> exception(isolate->exception(), isolate);
    try_catch.Reset();
    err_str = ErrorUtils::ToString(
        isolate, exception,
        ErrorUtils::ToStringMessageSource::kPreferOriginalMessage);
    if (err_str.is_null()) {
      // Formatting the thrown exception threw again, give up.
      DCHECK(isolate->has_exception());
      if (isolate->is_execution_terminating()) return {};
      builder->AppendCStringLiteral("<error>");
    } else {
      // Formatted thrown exception successfully, append it.
      builder->AppendCStringLiteral("<error: ");
      builder->AppendString(err_str.ToHandleChecked());
      builder->AppendCharacter('>');
    }
  } else {
    builder->AppendString(err_str.ToHandleChecked());
  }
  return error;
}
References v8::internal::IncrementalStringBuilder::AppendCharacter(), v8::internal::IncrementalStringBuilder::AppendCStringLiteral(), v8::internal::IncrementalStringBuilder::AppendString(), v8::internal::DCHECK(), v8::internal::Isolate::exception(), v8::internal::Isolate::has_exception(), v8::internal::Isolate::is_execution_terminating(), v8::internal::MaybeDirectHandle< T >::is_null(), v8::internal::ErrorUtils::kPreferOriginalMessage, v8::TryCatch::Reset(), v8::TryCatch::SetCaptureMessage(), v8::TryCatch::SetVerbose(), v8::internal::MaybeDirectHandle< T >::ToHandleChecked(), and v8::internal::ErrorUtils::ToString().
Referenced by v8::internal::ErrorUtils::FormatStackTrace().
BuildDefaultCallSite()
DirectHandle<String> v8::internal::anonymous_namespace{messages.cc}::BuildDefaultCallSite (Isolate * isolate, DirectHandle< Object > object)
Definition at line 850 of file messages.cc.
                                                                       {
  IncrementalStringBuilder builder(isolate);
  builder.AppendString(Object::TypeOf(isolate, object));
  if (IsString(*object)) {
    builder.AppendCStringLiteral(" \"");
    DirectHandle<String> string = Cast<String>(object);
    // This threshold must be sufficiently far below String::kMaxLength that
    // the {builder}'s result can never exceed that limit.
    constexpr int kMaxPrintedStringLength = 100;
    if (string->length() <= kMaxPrintedStringLength) {
      builder.AppendString(string);
    } else {
      string = isolate->factory()->NewProperSubString(string, 0,
                                                      kMaxPrintedStringLength);
      builder.AppendString(string);
      builder.AppendCStringLiteral("<...>");
    }
    builder.AppendCStringLiteral("\"");
  } else if (IsNull(*object, isolate)) {
    builder.AppendCStringLiteral(" null");
  } else if (IsTrue(*object, isolate)) {
    builder.AppendCStringLiteral(" true");
  } else if (IsFalse(*object, isolate)) {
    builder.AppendCStringLiteral(" false");
  } else if (IsNumber(*object)) {
    builder.AppendCharacter(' ');
    builder.AppendString(isolate->factory()->NumberToString(object));
  }
  return builder.Finish().ToHandleChecked();
}
References v8::internal::IncrementalStringBuilder::AppendCharacter(), v8::internal::IncrementalStringBuilder::AppendCStringLiteral(), v8::internal::IncrementalStringBuilder::AppendString(), v8::internal::Isolate::factory(), v8::internal::IncrementalStringBuilder::Finish(), v8::internal::IsNull(), v8::internal::IsNumber(), v8::internal::Factory::NewProperSubString(), v8::internal::FactoryBase< Impl >::NumberToString(), v8::internal::string, and v8::internal::Object::TypeOf().
Referenced by RenderCallSite(), v8::internal::ErrorUtils::ThrowLoadFromNullOrUndefined(), and v8::internal::ErrorUtils::ThrowSpreadArgError().
ComputeLocation()
bool v8::internal::anonymous_namespace{messages.cc}::ComputeLocation (Isolate * isolate, MessageLocation * target)
Definition at line 827 of file messages.cc.
                                                                {
  JavaScriptStackFrameIterator it(isolate);
  if (!it.done()) {
    // Compute the location from the function and the relocation info of the
    // baseline code. For optimized code this will use the deoptimization
    // information to get canonical location information.
    FrameSummaries summaries = it.frame()->Summarize();
    auto& summary = summaries.frames.back().AsJavaScript();
    Handle<SharedFunctionInfo> shared(summary.function()->shared(), isolate);
    Handle<Object> script(shared->script(), isolate);
    SharedFunctionInfo::EnsureSourcePositionsAvailable(isolate, shared);
    int pos =
        summary.abstract_code()->SourcePosition(isolate, summary.code_offset());
    if (IsScript(*script) &&
        !(IsUndefined(Cast<Script>(script)->source(), isolate))) {
      Handle<Script> casted_script = Cast<Script>(script);
      *target = MessageLocation(casted_script, pos, pos + 1, shared);
      return true;
    }
  }
  return false;
}
References v8::internal::JavaScriptStackFrameIterator::done(), v8::internal::SharedFunctionInfo::EnsureSourcePositionsAvailable(), v8::internal::JavaScriptStackFrameIterator::frame(), v8::internal::FrameSummaries::frames, v8::internal::script, and v8::internal::CommonFrameWithJSLinkage::Summarize().
Referenced by RenderCallSite(), v8::internal::ErrorUtils::ThrowLoadFromNullOrUndefined(), and v8::internal::ErrorUtils::ThrowSpreadArgError().
GetStackFrames()
MaybeDirectHandle<JSArray> v8::internal::anonymous_namespace{messages.cc}::GetStackFrames (Isolate * isolate, DirectHandle< FixedArray > frames)
Definition at line 205 of file messages.cc.
                                                                           {
  int frame_count = frames->length();
  DirectHandle<JSFunction> constructor = isolate->callsite_function();
  DirectHandle<FixedArray> sites =
      isolate->factory()->NewFixedArray(frame_count);
  for (int i = 0; i < frame_count; ++i) {
    DirectHandle<CallSiteInfo> frame(Cast<CallSiteInfo>(frames->get(i)),
                                     isolate);
    DirectHandle<JSObject> site;
    ASSIGN_RETURN_ON_EXCEPTION(isolate, site,
                               JSObject::New(constructor, constructor,
                                             Handle<AllocationSite>::null()));
    RETURN_ON_EXCEPTION(
        isolate, JSObject::SetOwnPropertyIgnoreAttributes(
                     site, isolate->factory()->call_site_info_symbol(), frame,
                     DONT_ENUM));
    sites->set(i, *site);
  }
  return isolate->factory()->NewJSArrayWithElements(sites);
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::DONT_ENUM, v8::internal::Isolate::factory(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::JSObject::New(), v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::Factory::NewJSArrayWithElements(), RETURN_ON_EXCEPTION, and v8::internal::JSObject::SetOwnPropertyIgnoreAttributes().
Referenced by v8::internal::ErrorUtils::FormatStackTrace().
GetStringPropertyOrDefault()
MaybeHandle<String> v8::internal::anonymous_namespace{messages.cc}::GetStringPropertyOrDefault (Isolate * isolate, DirectHandle< JSReceiver > recv, DirectHandle< String > key, Handle< String > default_str)
Definition at line 638 of file messages.cc.
                                                                           {
  Handle<Object> obj;
  ASSIGN_RETURN_ON_EXCEPTION(isolate, obj,
                             JSObject::GetProperty(isolate, recv, key));
  Handle<String> str;
  if (IsUndefined(*obj, isolate)) {
    str = default_str;
  } else {
    ASSIGN_RETURN_ON_EXCEPTION(isolate, str, Object::ToString(isolate, obj));
  }
  return str;
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::key, and v8::Value::ToString().
Referenced by v8::internal::ErrorUtils::ToString().
RenderCallSite()
DirectHandle<String> v8::internal::anonymous_namespace{messages.cc}::RenderCallSite (Isolate * isolate, DirectHandle< Object > object, MessageLocation * location, CallPrinter::ErrorHint * hint)
Definition at line 884 of file messages.cc.
                                                                {
  if (ComputeLocation(isolate, location)) {
    UnoptimizedCompileFlags flags = UnoptimizedCompileFlags::ForFunctionCompile(
        isolate, *location->shared());
    flags.set_is_reparse(true);
    UnoptimizedCompileState compile_state;
    ReusableUnoptimizedCompileState reusable_state(isolate);
    ParseInfo info(isolate, flags, &compile_state, &reusable_state);
    if (parsing::ParseAny(&info, location->shared(), isolate,
                          parsing::ReportStatisticsMode::kNo)) {
      info.ast_value_factory()->Internalize(isolate);
      CallPrinter printer(isolate, location->shared()->IsUserJavaScript());
      DirectHandle<String> str =
          printer.Print(info.literal(), location->start_pos());
      *hint = printer.GetErrorHint();
      if (str->length() > 0) return str;
    }
  }
  return BuildDefaultCallSite(isolate, object);
}
References v8::internal::ParseInfo::ast_value_factory(), BuildDefaultCallSite(), ComputeLocation(), v8::internal::flags, v8::internal::UnoptimizedCompileFlags::ForFunctionCompile(), v8::internal::CallPrinter::GetErrorHint(), v8::internal::AstValueFactory::Internalize(), v8::internal::parsing::kNo, v8::internal::ParseInfo::literal(), v8::internal::parsing::ParseAny(), v8::internal::CallPrinter::Print(), v8::internal::MessageLocation::shared(), and v8::internal::MessageLocation::start_pos().
Referenced by v8::internal::ErrorUtils::NewCalledNonCallableError(), v8::internal::ErrorUtils::NewConstructedNonConstructable(), and v8::internal::ErrorUtils::NewIteratorError().
UpdateErrorTemplate()
MessageTemplate v8::internal::anonymous_namespace{messages.cc}::UpdateErrorTemplate (CallPrinter::ErrorHint hint, MessageTemplate default_id)
Definition at line 908 of file messages.cc.
                                                                {
  switch (hint) {
    case CallPrinter::ErrorHint::kNormalIterator:
      return MessageTemplate::kNotIterable;
    case CallPrinter::ErrorHint::kCallAndNormalIterator:
      return MessageTemplate::kNotCallableOrIterable;
    case CallPrinter::ErrorHint::kAsyncIterator:
      return MessageTemplate::kNotAsyncIterable;
    case CallPrinter::ErrorHint::kCallAndAsyncIterator:
      return MessageTemplate::kNotCallableOrAsyncIterable;
    case CallPrinter::ErrorHint::kNone:
      return default_id;
  }
}
References v8::internal::CallPrinter::kAsyncIterator, v8::internal::CallPrinter::kCallAndAsyncIterator, v8::internal::CallPrinter::kCallAndNormalIterator, v8::internal::CallPrinter::kNone, and v8::internal::CallPrinter::kNormalIterator.
Referenced by v8::internal::ErrorUtils::NewCalledNonCallableError(), and v8::internal::ErrorUtils::NewIteratorError().