v8::internal::wasm::anonymous_namespace{wasm-engine.cc} Namespace Reference
Classes
class WasmGCForegroundTask
class ClearWeakScriptHandleTask
class WeakScriptHandle
struct GlobalWasmState
Functions
void CheckNoArchivedThreads (Isolate *isolate)
DirectHandle< Script > CreateWasmScript (Isolate *isolate, std::shared_ptr< NativeModule > native_module, base::Vector< const char > source_url)
void ReportLiveCodeFromFrameForGC (Isolate *isolate, StackFrame *frame, std::unordered_set< wasm::WasmCode * > &live_wasm_code)
Variables
std::vector< std::shared_ptr< NativeModule > > * native_modules_kept_alive_for_pgo
GlobalWasmState * global_wasm_state = nullptr
Function Documentation
CheckNoArchivedThreads()
void v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::CheckNoArchivedThreads (Isolate * isolate)
Definition at line 173 of file wasm-engine.cc.
                                              {
  class ArchivedThreadsVisitor : public ThreadVisitor {
    void VisitThread(Isolate* isolate, ThreadLocalTop* top) override {
      // Archived threads are rarely used, and not combined with Wasm at the
      // moment. Implement this and test it properly once we have a use case for
      // that.
      FATAL("archived threads in combination with wasm not supported");
    }
  } archived_threads_visitor;
  isolate->thread_manager()->IterateArchivedThreads(&archived_threads_visitor);
}
References FATAL, v8::internal::ThreadManager::IterateArchivedThreads(), and v8::internal::Isolate::thread_manager().
Referenced by v8::internal::wasm::WasmEngine::ReportLiveCodeFromStackForGC().
CreateWasmScript()
DirectHandle<Script> v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::CreateWasmScript (Isolate * isolate, std::shared_ptr< NativeModule > native_module, base::Vector< const char > source_url)
Definition at line 953 of file wasm-engine.cc.
                                       {
  base::Vector<const uint8_t> wire_bytes = native_module->wire_bytes();
  // The source URL of the script is
  // - the original source URL if available (from the streaming API),
  // - wasm://wasm/<module name>-<hash> if a module name has been set, or
  // - wasm://wasm/<hash> otherwise.
  const WasmModule* module = native_module->module();
  DirectHandle<String> url_str;
  if (!source_url.empty()) {
    url_str = isolate->factory()
                  ->NewStringFromUtf8(source_url, AllocationType::kOld)
                  .ToHandleChecked();
  } else {
    // Limit the printed hash to 8 characters.
    uint32_t hash = static_cast<uint32_t>(GetWireBytesHash(wire_bytes));
    base::EmbeddedVector<char, 32> buffer;
    if (module->name.is_empty()) {
      // Build the URL in the form "wasm://wasm/<hash>".
      int url_len = SNPrintF(buffer, "wasm://wasm/%08x", hash);
      DCHECK(url_len >= 0 && url_len < buffer.length());
      url_str = isolate->factory()
                    ->NewStringFromUtf8(buffer.SubVector(0, url_len),
                                        AllocationType::kOld)
                    .ToHandleChecked();
    } else {
      // Build the URL in the form "wasm://wasm/<module name>-<hash>".
      int hash_len = SNPrintF(buffer, "-%08x", hash);
      DCHECK(hash_len >= 0 && hash_len < buffer.length());
      DirectHandle<String> prefix =
          isolate->factory()->NewStringFromStaticChars("wasm://wasm/");
      DirectHandle<String> module_name =
          WasmModuleObject::ExtractUtf8StringFromModuleBytes(
              isolate, wire_bytes, module->name, kNoInternalize);
      DirectHandle<String> hash_str =
          isolate->factory()
              ->NewStringFromUtf8(buffer.SubVector(0, hash_len))
              .ToHandleChecked();
      // Concatenate the three parts.
      url_str = isolate->factory()
                    ->NewConsString(prefix, module_name)
                    .ToHandleChecked();
      url_str = isolate->factory()
                    ->NewConsString(url_str, hash_str)
                    .ToHandleChecked();
    }
  }
  DirectHandle<PrimitiveHeapObject> source_map_url =
      isolate->factory()->undefined_value();
  if (module->debug_symbols[WasmDebugSymbols::Type::SourceMap].type !=
      WasmDebugSymbols::Type::None) {
    auto source_map_symbols =
        module->debug_symbols[WasmDebugSymbols::Type::SourceMap];
    base::Vector<const char> external_url =
        ModuleWireBytes(wire_bytes)
            .GetNameOrNull(source_map_symbols.external_url);
    MaybeDirectHandle<String> src_map_str =
        isolate->factory()->NewStringFromUtf8(external_url,
                                              AllocationType::kOld);
    source_map_url = src_map_str.ToHandleChecked();
  }
  // Use the given shared {NativeModule}, but increase its reference count by
  // allocating a new {Managed<T>} that the {Script} references.
  size_t code_size_estimate = native_module->committed_code_space();
  size_t memory_estimate =
      code_size_estimate +
      wasm::WasmCodeManager::EstimateNativeModuleMetaDataSize(module);
  DirectHandle<Managed<wasm::NativeModule>> managed_native_module =
      Managed<wasm::NativeModule>::From(isolate, memory_estimate,
                                        std::move(native_module));
  DirectHandle<Script> script =
      isolate->factory()->NewScript(isolate->factory()->undefined_value());
  {
    DisallowGarbageCollection no_gc;
    Tagged<Script> raw_script = *script;
    raw_script->set_compilation_state(Script::CompilationState::kCompiled);
    raw_script->set_context_data(isolate->native_context()->debug_context_id());
    raw_script->set_name(*url_str);
    raw_script->set_type(Script::Type::kWasm);
    raw_script->set_source_mapping_url(*source_map_url);
    raw_script->set_line_ends(ReadOnlyRoots(isolate).empty_fixed_array(),
                              SKIP_WRITE_BARRIER);
    raw_script->set_wasm_managed_native_module(*managed_native_module);
    raw_script->set_wasm_breakpoint_infos(
        ReadOnlyRoots(isolate).empty_fixed_array(), SKIP_WRITE_BARRIER);
    raw_script->set_wasm_weak_instance_list(
        ReadOnlyRoots(isolate).empty_weak_array_list(), SKIP_WRITE_BARRIER);
    // For correct exception handling (in particular, the onunhandledrejection
    // callback), we must set the origin options from the nearest calling JS
    // frame.
    // Considering all Wasm modules as shared across origins isn't a privacy
    // issue, because in order to instantiate and use them, a site needs to
    // already have access to their wire bytes anyway.
    static constexpr bool kIsSharedCrossOrigin = true;
    static constexpr bool kIsOpaque = false;
    static constexpr bool kIsWasm = true;
    static constexpr bool kIsModule = false;
    raw_script->set_origin_options(ScriptOriginOptions(
        kIsSharedCrossOrigin, kIsOpaque, kIsWasm, kIsModule));
  }
  return script;
}
References v8::internal::DCHECK(), v8::internal::wasm::WasmModule::debug_symbols, v8::base::Vector< T >::empty(), v8::internal::wasm::WasmCodeManager::EstimateNativeModuleMetaDataSize(), v8::internal::WasmModuleObject::ExtractUtf8StringFromModuleBytes(), v8::internal::Isolate::factory(), v8::internal::Managed< CppType >::From(), v8::internal::wasm::ModuleWireBytes::GetNameOrNull(), v8::internal::wasm::GetWireBytesHash(), v8::internal::wasm::WireBytesRef::is_empty(), v8::internal::Script::kCompiled, v8::internal::kNoInternalize, v8::internal::kOld, v8::base::Vector< T >::length(), v8::internal::wasm::WasmModule::name, v8::internal::Isolate::native_context(), v8::internal::FactoryBase< Impl >::NewConsString(), v8::internal::FactoryBase< Impl >::NewScript(), v8::internal::Factory::NewStringFromStaticChars(), v8::internal::Factory::NewStringFromUtf8(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::None, v8::internal::script, v8::internal::SKIP_WRITE_BARRIER, v8::base::SNPrintF(), v8::base::Vector< T >::SubVector(), and v8::internal::MaybeDirectHandle< T >::ToHandleChecked().
Referenced by v8::internal::wasm::WasmEngine::GetOrCreateScript().
ReportLiveCodeFromFrameForGC()
void v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::ReportLiveCodeFromFrameForGC (Isolate * isolate, StackFrame * frame, std::unordered_set< wasm::WasmCode * > & live_wasm_code)
Definition at line 1762 of file wasm-engine.cc.
                                                     {
  if (frame->type() == StackFrame::WASM) {
    WasmFrame* wasm_frame = WasmFrame::cast(frame);
    WasmCode* code = wasm_frame->wasm_code();
    live_wasm_code.insert(code);
#if V8_TARGET_ARCH_X64
    if (code->for_debugging()) {
      Address osr_target =
          base::Memory<Address>(wasm_frame->fp() - kOSRTargetOffset);
      if (osr_target) {
        WasmCode* osr_code =
            GetWasmCodeManager()->LookupCode(isolate, osr_target);
        DCHECK_NOT_NULL(osr_code);
        live_wasm_code.insert(osr_code);
      }
    }
#endif
  } else if (frame->type() == StackFrame::WASM_TO_JS) {
    live_wasm_code.insert(static_cast<WasmToJsFrame*>(frame)->wasm_code());
  }
}
References code, DCHECK_NOT_NULL, v8::internal::wasm::GetWasmCodeManager(), v8::internal::wasm::WasmCodeManager::LookupCode(), and v8::internal::StackFrame::type().
Referenced by v8::internal::wasm::WasmEngine::ReportLiveCodeFromStackForGC().
Variable Documentation
global_wasm_state
GlobalWasmState* v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::global_wasm_state = nullptr
Definition at line 2090 of file wasm-engine.cc.
Referenced by v8::internal::wasm::GetCanonicalTypeNamesProvider(), v8::internal::wasm::GetWasmCodeManager(), v8::internal::wasm::GetWasmEngine(), v8::internal::wasm::GetWasmImportWrapperCache(), v8::internal::wasm::WasmEngine::GlobalTearDown(), and v8::internal::wasm::WasmEngine::InitializeOncePerProcess().
native_modules_kept_alive_for_pgo
std::vector<std::shared_ptr<NativeModule> >* v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::native_modules_kept_alive_for_pgo
Definition at line 291 of file wasm-engine.cc.
Referenced by v8::internal::wasm::WasmEngine::NewNativeModule(), and v8::internal::wasm::WasmEngine::~WasmEngine().