v8::internal::anonymous_namespace{lazy-compile-dispatcher.cc} Namespace Reference
Functions
void SetUncompiledDataJobPointer (LocalIsolate *isolate, DirectHandle< SharedFunctionInfo > shared_info, Address job_address)
Function Documentation
SetUncompiledDataJobPointer()
void v8::internal::anonymous_namespace{lazy-compile-dispatcher.cc}::SetUncompiledDataJobPointer (LocalIsolate * isolate, DirectHandle< SharedFunctionInfo > shared_info, Address job_address)
Definition at line 95 of file lazy-compile-dispatcher.cc.
                                                      {
  Tagged<UncompiledData> uncompiled_data =
      shared_info->uncompiled_data(isolate);
  switch (uncompiled_data->map(isolate)->instance_type()) {
    // The easy cases -- we already have a job slot, so can write into it and
    // return.
    case UNCOMPILED_DATA_WITH_PREPARSE_DATA_AND_JOB_TYPE:
      Cast<UncompiledDataWithPreparseDataAndJob>(uncompiled_data)
          ->set_job(job_address);
      break;
    case UNCOMPILED_DATA_WITHOUT_PREPARSE_DATA_WITH_JOB_TYPE:
      Cast<UncompiledDataWithoutPreparseDataWithJob>(uncompiled_data)
          ->set_job(job_address);
      break;
    // Otherwise, we'll have to allocate a new UncompiledData (with or without
    // preparse data as appropriate), set the job pointer on that, and update
    // the SharedFunctionInfo to use the new UncompiledData
    case UNCOMPILED_DATA_WITH_PREPARSE_DATA_TYPE: {
      Handle<String> inferred_name(uncompiled_data->inferred_name(), isolate);
      Handle<PreparseData> preparse_data(
          Cast<UncompiledDataWithPreparseData>(uncompiled_data)
              ->preparse_data(),
          isolate);
      DirectHandle<UncompiledDataWithPreparseDataAndJob> new_uncompiled_data =
          isolate->factory()->NewUncompiledDataWithPreparseDataAndJob(
              inferred_name, uncompiled_data->start_position(),
              uncompiled_data->end_position(), preparse_data);
      new_uncompiled_data->set_job(job_address);
      shared_info->set_uncompiled_data(*new_uncompiled_data);
      break;
    }
    case UNCOMPILED_DATA_WITHOUT_PREPARSE_DATA_TYPE: {
      DCHECK(IsUncompiledDataWithoutPreparseData(uncompiled_data));
      Handle<String> inferred_name(uncompiled_data->inferred_name(), isolate);
      DirectHandle<UncompiledDataWithoutPreparseDataWithJob>
          new_uncompiled_data =
              isolate->factory()->NewUncompiledDataWithoutPreparseDataWithJob(
                  inferred_name, uncompiled_data->start_position(),
                  uncompiled_data->end_position());
      new_uncompiled_data->set_job(job_address);
      shared_info->set_uncompiled_data(*new_uncompiled_data);
      break;
    }
    default:
      UNREACHABLE();
  }
}
References v8::internal::DCHECK(), v8::internal::LocalIsolate::factory(), v8::internal::FactoryBase< Impl >::NewUncompiledDataWithoutPreparseDataWithJob(), v8::internal::FactoryBase< Impl >::NewUncompiledDataWithPreparseDataAndJob(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::LazyCompileDispatcher::Enqueue().