v8::internal::anonymous_namespace{isolate-group.cc} Namespace Reference
Functions
void InitCodeRangeOnce (std::unique_ptr< CodeRange > *code_range_member, v8::PageAllocator *page_allocator, size_t requested_size, bool immutable)
Function Documentation
InitCodeRangeOnce()
void v8::internal::anonymous_namespace{isolate-group.cc}::InitCodeRangeOnce (std::unique_ptr< CodeRange > * code_range_member, v8::PageAllocator * page_allocator, size_t requested_size, bool immutable)
Definition at line 237 of file isolate-group.cc.
                                       {
  CodeRange* code_range = new CodeRange();
  if (!code_range->InitReservation(page_allocator, requested_size, immutable)) {
    V8::FatalProcessOutOfMemory(
        nullptr, "Failed to reserve virtual memory for CodeRange");
  }
  code_range_member->reset(code_range);
#ifdef V8_EXTERNAL_CODE_SPACE
#ifdef V8_COMPRESS_POINTERS_IN_SHARED_CAGE
  ExternalCodeCompressionScheme::InitBase(
      ExternalCodeCompressionScheme::PrepareCageBaseAddress(
          code_range->base()));
#endif // V8_COMPRESS_POINTERS_IN_SHARED_CAGE
#endif // V8_EXTERNAL_CODE_SPACE
}
References v8::internal::VirtualMemoryCage::base(), v8::internal::V8::FatalProcessOutOfMemory(), and v8::internal::CodeRange::InitReservation().
Referenced by v8::internal::IsolateGroup::EnsureCodeRange().