v8::internal::anonymous_namespace{js-duration-format.cc} Namespace Reference
Classes
struct DurationUnitOptions
struct Part
Enumerations
enum class StylesList { k3Styles
, k4Styles
, k5Styles
 }
enum class Unit {
kYears
, kMonths
, kWeeks
, kDays
,
kHours
, kMinutes
, kSeconds
, kMilliseconds
,
kMicroseconds
, kNanoseconds
 }
Functions
Maybe< DurationUnitOptions > GetDurationUnitOptions (Isolate *isolate, Unit unit, const char *unit_string, const char *display_field, DirectHandle< JSReceiver > options, JSDurationFormat::Style base_style, const std::span< const std::string_view > value_strings, const std::span< const JSDurationFormat::FieldStyle > value_enums, JSDurationFormat::FieldStyle digital_base, JSDurationFormat::FieldStyle prev_style)
JSDurationFormat::Separator GetSeparator (const icu::Locale &l)
DirectHandle< String > StyleToString (Isolate *isolate, JSDurationFormat::Style style)
DirectHandle< String > StyleToString (Isolate *isolate, JSDurationFormat::FieldStyle style)
DirectHandle< String > DisplayToString (Isolate *isolate, JSDurationFormat::Display display)
UNumberUnitWidth ToUNumberUnitWidth (JSDurationFormat::FieldStyle style)
char16_t SeparatorToChar (JSDurationFormat::Separator separator)
bool FormattedToParts (const char *, icu::number::FormattedNumber &, bool, bool, JSDurationFormat::Separator, std::vector< std::vector< Part >> *, std::vector< icu::UnicodeString > *)
bool Output (const char *type, double value, const icu::number::LocalizedNumberFormatter &fmt, bool addToLast, bool display_negative_sign, bool negative_duration, JSDurationFormat::Separator separator, std::vector< std::vector< Part >> *parts, std::vector< icu::UnicodeString > *strings)
bool OutputLongShortOrNarrow (const char *type, double value, JSDurationFormat::Display display, const icu::number::LocalizedNumberFormatter &fmt, bool addToLast, bool display_negative_sign, bool negative_duration, JSDurationFormat::Separator separator, std::vector< std::vector< Part >> *parts, std::vector< icu::UnicodeString > *strings)
bool OutputLongShortNarrowOrNumeric (const char *type, double value, JSDurationFormat::Display display, JSDurationFormat::FieldStyle style, const icu::number::LocalizedNumberFormatter &fmt, icu::MeasureUnit unit, bool addToLast, bool display_negative_sign, bool negative_duration, JSDurationFormat::Separator separator, std::vector< std::vector< Part >> *parts, std::vector< icu::UnicodeString > *strings)
bool OutputLongShortNarrowNumericOr2Digit (const char *type, double value, JSDurationFormat::Display display, JSDurationFormat::FieldStyle style, const icu::number::LocalizedNumberFormatter &fmt, icu::MeasureUnit unit, bool maybeAddToLast, bool displayRequired, bool display_negative_sign, bool negative_duration, JSDurationFormat::Separator separator, std::vector< std::vector< Part >> *parts, std::vector< icu::UnicodeString > *strings)
bool DisplayRequired (DirectHandle< JSDurationFormat > df, const DurationRecord &record)
void DurationRecordToListOfFormattedNumber (DirectHandle< JSDurationFormat > df, const icu::number::LocalizedNumberFormatter &fmt, const DurationRecord &record, std::vector< std::vector< Part >> *parts, std::vector< icu::UnicodeString > *strings)
UListFormatterWidth StyleToWidth (JSDurationFormat::Style style)
template<typename T , bool Details, MaybeDirectHandle< T >(*)(Isolate *, const icu::FormattedValue &, const std::vector< std::vector< Part >> *, JSDurationFormat::Separator separator) Format>
MaybeDirectHandle< T > PartitionDurationFormatPattern (Isolate *isolate, DirectHandle< JSDurationFormat > df, const DurationRecord &record, const char *method_name)
Maybe< DurationRecord > ToDurationRecord (Isolate *isolate, Handle< Object > input, const DurationRecord &default_value)
template<typename T , bool Details, MaybeDirectHandle< T >(*)(Isolate *, const icu::FormattedValue &, const std::vector< std::vector< Part >> *, JSDurationFormat::Separator) Format>
MaybeDirectHandle< T > FormatCommon (Isolate *isolate, DirectHandle< JSDurationFormat > df, Handle< Object > duration, const char *method_name)
Variables
const auto kLongShortNarrowStrings
const auto kLongShortNarrowNumericStrings
const auto kLongShortNarrowNumeric2DigitStrings
const std::initializer_list< JSDurationFormat::FieldStyle > kLongShortNarrowEnums
const std::initializer_list< JSDurationFormat::FieldStyle > kLongShortNarrowNumericEnums
const std::initializer_list< JSDurationFormat::FieldStyle > kLongShortNarrowNumeric2DigitEnums
Enumeration Type Documentation
StylesList
enum v8::internal::anonymous_namespace{js-duration-format.cc}::StylesList [strong]
Enumerator
k3Styles
k4Styles
k5Styles
Definition at line 44 of file js-duration-format.cc.
{ k3Styles, k4Styles, k5Styles };
Unit
enum v8::internal::anonymous_namespace{js-duration-format.cc}::Unit [strong]
Enumerator
kYears
kMonths
kWeeks
kDays
kHours
kMinutes
kSeconds
kMilliseconds
kMicroseconds
kNanoseconds
Definition at line 45 of file js-duration-format.cc.
                {
  kYears,
  kMonths,
  kWeeks,
  kDays,
  kHours,
  kMinutes,
  kSeconds,
  kMilliseconds,
  kMicroseconds,
  kNanoseconds
};
Function Documentation
DisplayRequired()
bool v8::internal::anonymous_namespace{js-duration-format.cc}::DisplayRequired (DirectHandle< JSDurationFormat > df, const DurationRecord & record)
Definition at line 800 of file js-duration-format.cc.
                                                   {
  // 9-h. Let displayRequired be "false".
  // 9-i. Let hoursStyle be durationFormat.[[HoursStyle]].
  // 9-j-i. If hoursStyle is "numeric" or "2-digit", then
  if (df->hours_style() == JSDurationFormat::FieldStyle::kNumeric ||
      df->hours_style() == JSDurationFormat::FieldStyle::k2Digit) {
    // 1. Let hoursDisplay be durationFormat.[[HoursDisplay]].
    // 2. Let hoursValue be durationFormat.[[HoursValue]].
    // 3. If hoursDisplay is "always" or hoursValue is not 0, then
    if (df->hours_display() == JSDurationFormat::Display::kAlways ||
        record.time_duration.hours != 0) {
      // a. Let secondsDisplay be durationFormat.[[SecondsDisplay]].
      // c. If secondsDisplay is "always" or duration.[[Second]] is not 0, or
      // duration.[[Milliseconds]] is not 0, or duration.[[Microseconds]] is not
      // 0, or duration.[[Nanoseconds]] is not 0, then
      if (df->seconds_display() == JSDurationFormat::Display::kAlways ||
          record.time_duration.seconds != 0 ||
          record.time_duration.milliseconds != 0 ||
          record.time_duration.microseconds != 0 ||
          record.time_duration.nanoseconds != 0) {
        // i. Set displayRequired to "true".
        return true;
      }
    }
  }
  return false;
}
References v8::internal::temporal::TimeDurationRecord::hours, v8::internal::JSDurationFormat::k2Digit, v8::internal::JSDurationFormat::kAlways, v8::internal::JSDurationFormat::kNumeric, v8::internal::temporal::TimeDurationRecord::microseconds, v8::internal::temporal::TimeDurationRecord::milliseconds, v8::internal::temporal::TimeDurationRecord::nanoseconds, v8::internal::temporal::TimeDurationRecord::seconds, and v8::internal::temporal::DurationRecord::time_duration.
Referenced by DurationRecordToListOfFormattedNumber().
DisplayToString()
DirectHandle<String> v8::internal::anonymous_namespace{js-duration-format.cc}::DisplayToString (Isolate * isolate, JSDurationFormat::Display display)
Definition at line 544 of file js-duration-format.cc.
                                                                      {
  switch (display) {
    case JSDurationFormat::Display::kAuto:
      return isolate->factory()->auto_string();
    case JSDurationFormat::Display::kAlways:
      return isolate->factory()->always_string();
  }
  // Avoid undefined behavior for enum values not handled by the exhaustive
  // switch, since they're read from inside the sandbox.
  SBXCHECK(false);
}
References v8::internal::Isolate::factory(), v8::internal::JSDurationFormat::kAlways, v8::internal::JSDurationFormat::kAuto, and SBXCHECK.
DurationRecordToListOfFormattedNumber()
void v8::internal::anonymous_namespace{js-duration-format.cc}::DurationRecordToListOfFormattedNumber (DirectHandle< JSDurationFormat > df, const icu::number::LocalizedNumberFormatter & fmt, const DurationRecord & record, std::vector< std::vector< Part >> * parts, std::vector< icu::UnicodeString > * strings)
Definition at line 829 of file js-duration-format.cc.
                                          {
  JSDurationFormat::Separator separator = df->separator();
  // 4. Let displayNegativeSign be true.
  bool display_negative_sign = true;
  bool negative_duration = DurationRecord::Sign(record) == -1;
  display_negative_sign = OutputLongShortOrNarrow(
      "year", record.years, df->years_display(),
      fmt.unit(icu::MeasureUnit::getYear())
          .unitWidth(ToUNumberUnitWidth(df->years_style())),
      false, display_negative_sign, negative_duration, separator, parts,
      strings);
  display_negative_sign = OutputLongShortOrNarrow(
      "month", record.months, df->months_display(),
      fmt.unit(icu::MeasureUnit::getMonth())
          .unitWidth(ToUNumberUnitWidth(df->months_style())),
      false, display_negative_sign, negative_duration, separator, parts,
      strings);
  display_negative_sign = OutputLongShortOrNarrow(
      "week", record.weeks, df->weeks_display(),
      fmt.unit(icu::MeasureUnit::getWeek())
          .unitWidth(ToUNumberUnitWidth(df->weeks_style())),
      false, display_negative_sign, negative_duration, separator, parts,
      strings);
  display_negative_sign = OutputLongShortOrNarrow(
      "day", record.time_duration.days, df->days_display(),
      fmt.unit(icu::MeasureUnit::getDay())
          .unitWidth(ToUNumberUnitWidth(df->days_style())),
      false, display_negative_sign, negative_duration, separator, parts,
      strings);
  display_negative_sign = OutputLongShortNarrowNumericOr2Digit(
      "hour", record.time_duration.hours, df->hours_display(),
      df->hours_style(), fmt, icu::MeasureUnit::getHour(), false, false,
      display_negative_sign, negative_duration, separator, parts, strings);
  bool minuteCouldAddToLast =
      df->hours_style() == JSDurationFormat::FieldStyle::kNumeric ||
      df->hours_style() == JSDurationFormat::FieldStyle::k2Digit;
  display_negative_sign = OutputLongShortNarrowNumericOr2Digit(
      "minute", record.time_duration.minutes, df->minutes_display(),
      df->minutes_style(), fmt, icu::MeasureUnit::getMinute(),
      minuteCouldAddToLast, DisplayRequired(df, record), display_negative_sign,
      negative_duration, separator, parts, strings);
  int32_t fractional_digits = df->fractional_digits();
  int32_t maximumFractionDigits;
  int32_t minimumFractionDigits;
  // 2. If durationFormat.[[FractionalDigits]] is undefined, then
  if (fractional_digits == JSDurationFormat::kUndefinedFractionalDigits) {
    // a. Let maximumFractionDigits be 9.
    maximumFractionDigits = 9;
    // b. Let minimumFractionDigits be +0.
    minimumFractionDigits = 0;
  } else { // 3. Else,
    // a. Let maximumFractionDigits be (durationFormat.[[FractionalDigits]]).
    maximumFractionDigits = fractional_digits;
    // b. Let minimumFractionDigits be (durationFormat.[[FractionalDigits]]).
    minimumFractionDigits = fractional_digits;
  }
  // 4. Perform ! CreateDataPropertyOrThrow(nfOpts, "maximumFractionDigits",
  // maximumFractionDigits).
  // 5. Perform ! CreateDataPropertyOrThrow(nfOpts, "minimumFractionDigits",
  // minimumFractionDigits).
  icu::number::LocalizedNumberFormatter nfOps =
      fmt.precision(icu::number::Precision::minMaxFraction(
                        minimumFractionDigits, maximumFractionDigits))
          // 6. Perform ! CreateDataPropertyOrThrow(nfOpts, "roundingMode",
          // "trunc").
          .roundingMode(UNumberFormatRoundingMode::UNUM_ROUND_DOWN);
  if (df->milliseconds_style() == JSDurationFormat::FieldStyle::kFractional) {
    // 1. Set value to value + AddFractionalDigits(durationFormat, duration).
    double value = record.time_duration.nanoseconds / 1e9 +
                   record.time_duration.microseconds / 1e6 +
                   record.time_duration.milliseconds / 1e3 +
                   record.time_duration.seconds;
    OutputLongShortNarrowNumericOr2Digit(
        "second", value, df->seconds_display(), df->seconds_style(), nfOps,
        icu::MeasureUnit::getSecond(), true, false, display_negative_sign,
        negative_duration, separator, parts, strings);
    return;
  }
  display_negative_sign = OutputLongShortNarrowNumericOr2Digit(
      "second", record.time_duration.seconds, df->seconds_display(),
      df->seconds_style(), fmt, icu::MeasureUnit::getSecond(), true, false,
      display_negative_sign, negative_duration, separator, parts, strings);
  if (df->microseconds_style() == JSDurationFormat::FieldStyle::kFractional) {
    // 1. Set value to value + AddFractionalDigits(durationFormat, duration).
    double value = record.time_duration.nanoseconds / 1e6 +
                   record.time_duration.microseconds / 1e3 +
                   record.time_duration.milliseconds;
    OutputLongShortNarrowOrNumeric(
        "millisecond", value, df->milliseconds_display(),
        df->milliseconds_style(), nfOps, icu::MeasureUnit::getMillisecond(),
        false, display_negative_sign, negative_duration, separator, parts,
        strings);
    return;
  }
  display_negative_sign = OutputLongShortNarrowOrNumeric(
      "millisecond", record.time_duration.milliseconds,
      df->milliseconds_display(), df->milliseconds_style(), fmt,
      icu::MeasureUnit::getMillisecond(), false, display_negative_sign,
      negative_duration, separator, parts, strings);
  if (df->nanoseconds_style() == JSDurationFormat::FieldStyle::kFractional) {
    // 1. Set value to value + AddFractionalDigits(durationFormat, duration).
    double value = record.time_duration.nanoseconds / 1e3 +
                   record.time_duration.microseconds;
    OutputLongShortNarrowOrNumeric(
        "microsecond", value, df->microseconds_display(),
        df->microseconds_style(), nfOps, icu::MeasureUnit::getMicrosecond(),
        false, display_negative_sign, negative_duration, separator, parts,
        strings);
    return;
  }
  display_negative_sign = OutputLongShortNarrowOrNumeric(
      "microsecond", record.time_duration.microseconds,
      df->microseconds_display(), df->microseconds_style(), fmt,
      icu::MeasureUnit::getMicrosecond(), false, display_negative_sign,
      negative_duration, separator, parts, strings);
  OutputLongShortNarrowOrNumeric(
      "nanosecond", record.time_duration.nanoseconds, df->nanoseconds_display(),
      df->nanoseconds_style(), fmt, icu::MeasureUnit::getNanosecond(), false,
      display_negative_sign, negative_duration, separator, parts, strings);
}
References v8::internal::temporal::TimeDurationRecord::days, DisplayRequired(), v8::internal::temporal::TimeDurationRecord::hours, v8::internal::JSDurationFormat::k2Digit, v8::internal::JSDurationFormat::kFractional, v8::internal::JSDurationFormat::kNumeric, v8::internal::JSDurationFormat::kUndefinedFractionalDigits, v8::internal::temporal::TimeDurationRecord::microseconds, v8::internal::temporal::TimeDurationRecord::milliseconds, v8::internal::temporal::TimeDurationRecord::minutes, v8::internal::temporal::DurationRecord::months, v8::internal::temporal::TimeDurationRecord::nanoseconds, OutputLongShortNarrowNumericOr2Digit(), OutputLongShortNarrowOrNumeric(), OutputLongShortOrNarrow(), v8::internal::temporal::TimeDurationRecord::seconds, v8::internal::separator, v8::internal::temporal::DurationRecord::Sign(), v8::internal::temporal::DurationRecord::time_duration, ToUNumberUnitWidth(), v8::internal::value, v8::internal::temporal::DurationRecord::weeks, and v8::internal::temporal::DurationRecord::years.
Referenced by PartitionDurationFormatPattern().
FormatCommon()
template<typename T , bool Details, MaybeDirectHandle< T >(*)(Isolate *, const icu::FormattedValue &, const std::vector< std::vector< Part >> *, JSDurationFormat::Separator) Format>
MaybeDirectHandle<T> v8::internal::anonymous_namespace{js-duration-format.cc}::FormatCommon (Isolate * isolate, DirectHandle< JSDurationFormat > df, Handle< Object > duration, const char * method_name)
Definition at line 1050 of file js-duration-format.cc.
                                                           {
  // 1. Let df be this value.
  // 2. Perform ? RequireInternalSlot(df, [[InitializedDurationFormat]]).
  // 3. Let record be ? ToDurationRecord(duration).
  DurationRecord record;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, record,
      ToDurationRecord(isolate, duration, {0, 0, 0, {0, 0, 0, 0, 0, 0, 0}}),
      DirectHandle<T>());
  // 5. Let parts be ! PartitionDurationFormatPattern(df, record).
  return PartitionDurationFormatPattern<T, Details, Format>(isolate, df, record,
                                                            method_name);
}
References v8::internal::duration, MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE, and ToDurationRecord().
FormattedToParts()
bool v8::internal::anonymous_namespace{js-duration-format.cc}::FormattedToParts (const char * type, icu::number::FormattedNumber & formatted, bool addToLast, bool display_negative_sign, JSDurationFormat::Separator separator, std::vector< std::vector< Part >> * parts, std::vector< icu::UnicodeString > * strings)
Definition at line 706 of file js-duration-format.cc.
                                                            {
  UErrorCode status = U_ZERO_ERROR;
  icu::UnicodeString unit_string = formatted.toString(status);
  DCHECK(U_SUCCESS(status));
  Part p = {Part::Type::kFormatted, std::string(type), std::move(formatted)};
  if (addToLast && !strings->empty()) {
    strings->back().append(SeparatorToChar(separator));
    strings->back() += unit_string;
    if (parts != nullptr) {
      icu::number::FormattedNumber dummy;
      Part s = {Part::Type::kSeparator, std::string(), std::move(dummy)};
      parts->back().push_back(std::move(s));
      parts->back().push_back(std::move(p));
    }
    return display_negative_sign;
  }
  strings->push_back(unit_string);
  if (parts != nullptr) {
    std::vector<Part> v;
    v.push_back(std::move(p));
    parts->push_back(std::move(v));
  }
  return display_negative_sign;
}
References v8::internal::DCHECK(), v8::internal::separator, SeparatorToChar(), v8::internal::status, v8::internal::string, and v8::internal::tracing::type.
Referenced by Output().
GetDurationUnitOptions()
Maybe<DurationUnitOptions> v8::internal::anonymous_namespace{js-duration-format.cc}::GetDurationUnitOptions (Isolate * isolate, Unit unit, const char * unit_string, const char * display_field, DirectHandle< JSReceiver > options, JSDurationFormat::Style base_style, const std::span< const std::string_view > value_strings, const std::span< const JSDurationFormat::FieldStyle > value_enums, JSDurationFormat::FieldStyle digital_base, JSDurationFormat::FieldStyle prev_style)
Definition at line 88 of file js-duration-format.cc.
                                           {
  const char* method_name = "Intl.DurationFormat";
  JSDurationFormat::FieldStyle style;
  // 1. Let style be ? GetOption(options, unit, "string", stylesList,
  // undefined).
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, style,
      GetStringOption<JSDurationFormat::FieldStyle>(
          isolate, options, unit_string, method_name, value_strings,
          value_enums, JSDurationFormat::FieldStyle::kUndefined),
      Nothing<DurationUnitOptions>());
  // 2. Let displayDefault be "always".
  JSDurationFormat::Display display_default =
      JSDurationFormat::Display::kAlways;
  // 3. If style is undefined, then
  if (style == JSDurationFormat::FieldStyle::kUndefined) {
    // a. If baseStyle is "digital", then
    if (base_style == JSDurationFormat::Style::kDigital) {
      // i. If unit is not one of "hours", "minutes", or "seconds", then
      if (unit != Unit::kHours && unit != Unit::kMinutes &&
          unit != Unit::kSeconds) {
        // a. Set displayDefault to "auto".
        display_default = JSDurationFormat::Display::kAuto;
      }
      // ii. Set style to digitalBase.
      style = digital_base;
      // b. Else
    } else {
      // i. if prevStyle is "fractional", "numeric", or "2-digit", then
      if (prev_style == JSDurationFormat::FieldStyle::kFractional ||
          prev_style == JSDurationFormat::FieldStyle::kNumeric ||
          prev_style == JSDurationFormat::FieldStyle::k2Digit) {
        // 1. If unit is not one of "minutes" or "seconds", then
        if (unit != Unit::kMinutes && unit != Unit::kSeconds) {
          // a. Set displayDefault to "auto".
          display_default = JSDurationFormat::Display::kAuto;
        }
        // 2. Set style to "numeric".
        style = JSDurationFormat::FieldStyle::kNumeric;
        // iii. Else,
      } else {
        // 1. Set displayDefault to "auto".
        display_default = JSDurationFormat::Display::kAuto;
        // 2. Set style to baseStyle.
        switch (base_style) {
          case JSDurationFormat::Style::kLong:
            style = JSDurationFormat::FieldStyle::kLong;
            break;
          case JSDurationFormat::Style::kShort:
            style = JSDurationFormat::FieldStyle::kShort;
            break;
          case JSDurationFormat::Style::kNarrow:
            style = JSDurationFormat::FieldStyle::kNarrow;
            break;
          default:
            UNREACHABLE();
        }
      }
    }
  }
  // 4. If style is "numeric", then
  if (style == JSDurationFormat::FieldStyle::kNumeric) {
    // a. If unit is one of "milliseconds", "microseconds", or "nanoseconds",
    // then
    if (unit == Unit::kMilliseconds || unit == Unit::kMicroseconds ||
        unit == Unit::kNanoseconds) {
      // i. Set style to "fractional".
      style = JSDurationFormat::FieldStyle::kFractional;
      // ii. Set displayDefault to "auto".
      display_default = JSDurationFormat::Display::kAuto;
    }
  }
  // 5. Let displayField be the string-concatenation of unit and "Display".
  // 6. Let display be ? GetOption(options, displayField, "string", "auto",
  // "always" , displayDefault).
  JSDurationFormat::Display display;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, display,
      GetStringOption<JSDurationFormat::Display>(
          isolate, options, display_field, method_name,
          std::to_array<const std::string_view>({"auto", "always"}),
          std::array{JSDurationFormat::Display::kAuto,
                     JSDurationFormat::Display::kAlways},
          display_default),
      Nothing<DurationUnitOptions>());
  // 7. If display is "always" and style is "fractional", then
  if (display == JSDurationFormat::Display::kAlways &&
      style == JSDurationFormat::FieldStyle::kFractional) {
    // a. Throw a RangeError exception.
    THROW_NEW_ERROR_RETURN_VALUE(
        isolate,
        NewRangeError(MessageTemplate::kInvalid,
                      isolate->factory()->object_string(), options),
        Nothing<DurationUnitOptions>());
  }
  // 8. If prevStyle is "fractional", then
  if (prev_style == JSDurationFormat::FieldStyle::kFractional) {
    // a. If style is not "fractional", then
    if (style != JSDurationFormat::FieldStyle::kFractional) {
      // i. Throw a RangeError exception.
      THROW_NEW_ERROR_RETURN_VALUE(
          isolate,
          NewRangeError(MessageTemplate::kInvalid,
                        isolate->factory()->object_string(), options),
          Nothing<DurationUnitOptions>());
    }
  }
  // 7. If prevStyle is "numeric" or "2-digit", then
  if (prev_style == JSDurationFormat::FieldStyle::kNumeric ||
      prev_style == JSDurationFormat::FieldStyle::k2Digit) {
    // a. If style is not "fractional", "numeric" or "2-digit", then
    if (style != JSDurationFormat::FieldStyle::kFractional &&
        style != JSDurationFormat::FieldStyle::kNumeric &&
        style != JSDurationFormat::FieldStyle::k2Digit) {
      // i. Throw a RangeError exception.
      THROW_NEW_ERROR_RETURN_VALUE(
          isolate,
          NewRangeError(MessageTemplate::kInvalid,
                        isolate->factory()->object_string(), options),
          Nothing<DurationUnitOptions>());
    }
    // b. If unit is "minutes" or "seconds", then
    if (unit == Unit::kMinutes || unit == Unit::kSeconds) {
      // i. Set style to "2-digit".
      style = JSDurationFormat::FieldStyle::k2Digit;
    }
  }
  // 8. Return the Record { [[Style]]: style, [[Display]]: display }.
  return Just(DurationUnitOptions({style, display}));
}
References v8::internal::Isolate::factory(), v8::Just(), v8::internal::JSDurationFormat::k2Digit, v8::internal::JSDurationFormat::kAlways, v8::internal::JSDurationFormat::kAuto, v8::internal::JSDurationFormat::kDigital, v8::internal::JSDurationFormat::kFractional, v8::internal::anonymous_namespace{isolate.cc}::kInvalid, v8::internal::JSDurationFormat::kLong, v8::internal::JSDurationFormat::kNarrow, v8::internal::JSDurationFormat::kNumeric, v8::internal::JSDurationFormat::kShort, v8::internal::JSDurationFormat::kUndefined, MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE, THROW_NEW_ERROR_RETURN_VALUE, and v8::internal::UNREACHABLE().
GetSeparator()
JSDurationFormat::Separator v8::internal::anonymous_namespace{js-duration-format.cc}::GetSeparator (const icu::Locale & l)
Definition at line 227 of file js-duration-format.cc.
                                                           {
  UErrorCode status = U_ZERO_ERROR;
  icu::DateFormatSymbols sym(l, status);
  if (U_FAILURE(status)) return JSDurationFormat::Separator::kColon;
  icu::UnicodeString sep;
  sym.getTimeSeparatorString(sep);
  if (sep.length() != 1) return JSDurationFormat::Separator::kColon;
  switch (sep.charAt(0)) {
    case u'.':
      return JSDurationFormat::Separator::kFullStop;
    case u'\uFF1A':
      return JSDurationFormat::Separator::kFullwidthColon;
    case u'\u066B':
      return JSDurationFormat::Separator::kArabicDecimalSeparator;
    // By default, or if we get anything else, just use ':'.
    default:
      return JSDurationFormat::Separator::kColon;
  }
}
References v8::internal::JSDurationFormat::kArabicDecimalSeparator, v8::internal::JSDurationFormat::kColon, v8::internal::JSDurationFormat::kFullStop, v8::internal::JSDurationFormat::kFullwidthColon, v8::internal::compiler::turboshaft::l, and v8::internal::status.
Referenced by v8::internal::JSDurationFormat::New().
Output()
bool v8::internal::anonymous_namespace{js-duration-format.cc}::Output (const char * type, double value, const icu::number::LocalizedNumberFormatter & fmt, bool addToLast, bool display_negative_sign, bool negative_duration, JSDurationFormat::Separator separator, std::vector< std::vector< Part >> * parts, std::vector< icu::UnicodeString > * strings)
Definition at line 678 of file js-duration-format.cc.
                                                  {
  icu::number::LocalizedNumberFormatter nfOpts(fmt);
  // i. If displayNegativeSign is true, then
  if (display_negative_sign) {
    // 1. Set displayNegativeSign to false.
    display_negative_sign = false;
    // 2. If value is 0 and DurationRecordSign(duration) is -1, then
    if (value == 0.0 && negative_duration) {
      // a. Set value to negative-zero.
      value = -0.0;
    }
  } else { // ii. Else,
    // 1. Perform ! CreateDataPropertyOrThrow(nfOpts, "signDisplay", "never").
    nfOpts = nfOpts.sign(UNumberSignDisplay::UNUM_SIGN_NEVER);
  }
  UErrorCode status = U_ZERO_ERROR;
  icu::number::FormattedNumber formatted = nfOpts.formatDouble(value, status);
  DCHECK(U_SUCCESS(status));
  return FormattedToParts(type, formatted, addToLast, display_negative_sign,
                          separator, parts, strings);
}
References v8::internal::DCHECK(), FormattedToParts(), v8::internal::separator, v8::internal::status, v8::internal::tracing::type, and v8::internal::value.
Referenced by OutputLongShortNarrowNumericOr2Digit(), OutputLongShortNarrowOrNumeric(), OutputLongShortOrNarrow(), and v8::internal::GCTracer::Print().
OutputLongShortNarrowNumericOr2Digit()
bool v8::internal::anonymous_namespace{js-duration-format.cc}::OutputLongShortNarrowNumericOr2Digit (const char * type, double value, JSDurationFormat::Display display, JSDurationFormat::FieldStyle style, const icu::number::LocalizedNumberFormatter & fmt, icu::MeasureUnit unit, bool maybeAddToLast, bool displayRequired, bool display_negative_sign, bool negative_duration, JSDurationFormat::Separator separator, std::vector< std::vector< Part >> * parts, std::vector< icu::UnicodeString > * strings)
Definition at line 772 of file js-duration-format.cc.
                                          {
  // k. If value is not 0 or display is not "auto" or displayRequired is "true",
  // then
  if ((value != 0) || (display != JSDurationFormat::Display::kAuto) ||
      displayRequired) {
    if (style == JSDurationFormat::FieldStyle::k2Digit) {
      return Output(type, value,
                    fmt.integerWidth(icu::number::IntegerWidth::zeroFillTo(2))
                        .grouping(UNumberGroupingStrategy::UNUM_GROUPING_OFF),
                    maybeAddToLast, display_negative_sign, negative_duration,
                    separator, parts, strings);
    }
    bool addToLast =
        maybeAddToLast && (JSDurationFormat::FieldStyle::kNumeric == style);
    return OutputLongShortNarrowOrNumeric(
        type, value, display, style, fmt, unit, addToLast,
        display_negative_sign, negative_duration, separator, parts, strings);
  }
  return display_negative_sign;
}
References v8::internal::JSDurationFormat::k2Digit, v8::internal::JSDurationFormat::kAuto, v8::internal::JSDurationFormat::kNumeric, Output(), OutputLongShortNarrowOrNumeric(), v8::internal::separator, v8::internal::tracing::type, and v8::internal::value.
Referenced by DurationRecordToListOfFormattedNumber().
OutputLongShortNarrowOrNumeric()
bool v8::internal::anonymous_namespace{js-duration-format.cc}::OutputLongShortNarrowOrNumeric (const char * type, double value, JSDurationFormat::Display display, JSDurationFormat::FieldStyle style, const icu::number::LocalizedNumberFormatter & fmt, icu::MeasureUnit unit, bool addToLast, bool display_negative_sign, bool negative_duration, JSDurationFormat::Separator separator, std::vector< std::vector< Part >> * parts, std::vector< icu::UnicodeString > * strings)
Definition at line 750 of file js-duration-format.cc.
                                          {
  if (value == 0 && display == JSDurationFormat::Display::kAuto)
    return display_negative_sign;
  if (style == JSDurationFormat::FieldStyle::kNumeric) {
    return Output(type, value,
                  fmt.grouping(UNumberGroupingStrategy::UNUM_GROUPING_OFF),
                  addToLast, display_negative_sign, negative_duration,
                  separator, parts, strings);
  }
  return OutputLongShortOrNarrow(
      type, value, display, fmt.unit(unit).unitWidth(ToUNumberUnitWidth(style)),
      addToLast, display_negative_sign, negative_duration, separator, parts,
      strings);
}
References v8::internal::JSDurationFormat::kAuto, v8::internal::JSDurationFormat::kNumeric, Output(), OutputLongShortOrNarrow(), v8::internal::separator, ToUNumberUnitWidth(), v8::internal::tracing::type, and v8::internal::value.
Referenced by DurationRecordToListOfFormattedNumber(), and OutputLongShortNarrowNumericOr2Digit().
OutputLongShortOrNarrow()
bool v8::internal::anonymous_namespace{js-duration-format.cc}::OutputLongShortOrNarrow (const char * type, double value, JSDurationFormat::Display display, const icu::number::LocalizedNumberFormatter & fmt, bool addToLast, bool display_negative_sign, bool negative_duration, JSDurationFormat::Separator separator, std::vector< std::vector< Part >> * parts, std::vector< icu::UnicodeString > * strings)
Definition at line 736 of file js-duration-format.cc.
                                                                   {
  if (value == 0 && display == JSDurationFormat::Display::kAuto)
    return display_negative_sign;
  return Output(type, value, fmt, addToLast, display_negative_sign,
                negative_duration, separator, parts, strings);
}
References v8::internal::JSDurationFormat::kAuto, Output(), v8::internal::separator, v8::internal::tracing::type, and v8::internal::value.
Referenced by DurationRecordToListOfFormattedNumber(), and OutputLongShortNarrowOrNumeric().
PartitionDurationFormatPattern()
template<typename T , bool Details, MaybeDirectHandle< T >(*)(Isolate *, const icu::FormattedValue &, const std::vector< std::vector< Part >> *, JSDurationFormat::Separator separator) Format>
MaybeDirectHandle<T> v8::internal::anonymous_namespace{js-duration-format.cc}::PartitionDurationFormatPattern (Isolate * isolate, DirectHandle< JSDurationFormat > df, const DurationRecord & record, const char * method_name)
Definition at line 981 of file js-duration-format.cc.
                                                           {
  // 4. Let lfOpts be ! OrdinaryObjectCreate(null).
  // 5. Perform ! CreateDataPropertyOrThrow(lfOpts, "type", "unit").
  UListFormatterType type = ULISTFMT_TYPE_UNITS;
  // 6. Let listStyle be durationFormat.[[Style]].
  // 7. If listStyle is "digital", then
  // a. Set listStyle to "short".
  // 8. Perform ! CreateDataPropertyOrThrow(lfOpts, "style", listStyle).
  UListFormatterWidth list_style = StyleToWidth(df->style());
  // 9. Let lf be ! Construct(%ListFormat%, durationFormat.[[Locale]], lfOpts
  //).
  UErrorCode status = U_ZERO_ERROR;
  icu::Locale icu_locale = *df->icu_locale()->raw();
  std::unique_ptr<icu::ListFormatter> formatter(
      icu::ListFormatter::createInstance(icu_locale, type, list_style, status));
  DCHECK(U_SUCCESS(status));
  std::vector<std::vector<Part>> list;
  std::vector<std::vector<Part>>* parts = Details ? &list : nullptr;
  std::vector<icu::UnicodeString> string_list;
  DurationRecordToListOfFormattedNumber(
      df, *(df->icu_number_formatter()->raw()), record, parts, &string_list);
  icu::FormattedList formatted = formatter->formatStringsToValue(
      string_list.data(), static_cast<int32_t>(string_list.size()), status);
  DCHECK(U_SUCCESS(status));
  return Format(isolate, formatted, parts, df->separator());
}
References v8::internal::DCHECK(), DurationRecordToListOfFormattedNumber(), v8::internal::status, StyleToWidth(), and v8::internal::tracing::type.
SeparatorToChar()
char16_t v8::internal::anonymous_namespace{js-duration-format.cc}::SeparatorToChar (JSDurationFormat::Separator separator)
Definition at line 660 of file js-duration-format.cc.
                                                              {
  switch (separator) {
    case JSDurationFormat::Separator::kColon:
      return u':';
    case JSDurationFormat::Separator::kFullStop:
      return u'.';
    case JSDurationFormat::Separator::kFullwidthColon:
      return u'\uFF1A';
    case JSDurationFormat::Separator::kArabicDecimalSeparator:
      return u'\u066B';
  }
}
References v8::internal::JSDurationFormat::kArabicDecimalSeparator, v8::internal::JSDurationFormat::kColon, v8::internal::JSDurationFormat::kFullStop, v8::internal::JSDurationFormat::kFullwidthColon, and v8::internal::separator.
Referenced by v8::internal::FormattedListToJSArray(), and FormattedToParts().
StyleToString() [1/2]
DirectHandle<String> v8::internal::anonymous_namespace{js-duration-format.cc}::StyleToString (Isolate * isolate, JSDurationFormat::FieldStyle style)
Definition at line 518 of file js-duration-format.cc.
                                                                     {
  switch (style) {
    case JSDurationFormat::FieldStyle::kLong:
      return isolate->factory()->long_string();
    case JSDurationFormat::FieldStyle::kShort:
      return isolate->factory()->short_string();
    case JSDurationFormat::FieldStyle::kNarrow:
      return isolate->factory()->narrow_string();
    case JSDurationFormat::FieldStyle::kNumeric:
      return isolate->factory()->numeric_string();
    case JSDurationFormat::FieldStyle::k2Digit:
      return isolate->factory()->two_digit_string();
    case JSDurationFormat::FieldStyle::kFractional:
      // Step 3 in Intl.DurationFormat.prototype.resolvedOptions ()
      // e. If v is "fractional", then
      // ii. Set v to "numeric".
      return isolate->factory()->numeric_string();
    case JSDurationFormat::FieldStyle::kUndefined:
      UNREACHABLE();
  }
  // Avoid undefined behavior for enum values not handled by the exhaustive
  // switch, since they're read from inside the sandbox.
  SBXCHECK(false);
}
References v8::internal::Isolate::factory(), v8::internal::JSDurationFormat::k2Digit, v8::internal::JSDurationFormat::kFractional, v8::internal::JSDurationFormat::kLong, v8::internal::JSDurationFormat::kNarrow, v8::internal::JSDurationFormat::kNumeric, v8::internal::JSDurationFormat::kShort, v8::internal::JSDurationFormat::kUndefined, SBXCHECK, and v8::internal::UNREACHABLE().
Referenced by v8::internal::JSDurationFormat::ResolvedOptions().
StyleToString() [2/2]
DirectHandle<String> v8::internal::anonymous_namespace{js-duration-format.cc}::StyleToString (Isolate * isolate, JSDurationFormat::Style style)
Definition at line 501 of file js-duration-format.cc.
                                                                {
  switch (style) {
    case JSDurationFormat::Style::kLong:
      return isolate->factory()->long_string();
    case JSDurationFormat::Style::kShort:
      return isolate->factory()->short_string();
    case JSDurationFormat::Style::kNarrow:
      return isolate->factory()->narrow_string();
    case JSDurationFormat::Style::kDigital:
      return isolate->factory()->digital_string();
  }
  // Avoid undefined behavior for enum values not handled by the exhaustive
  // switch, since they're read from inside the sandbox.
  SBXCHECK(false);
}
References v8::internal::Isolate::factory(), v8::internal::JSDurationFormat::kDigital, v8::internal::JSDurationFormat::kLong, v8::internal::JSDurationFormat::kNarrow, v8::internal::JSDurationFormat::kShort, and SBXCHECK.
StyleToWidth()
UListFormatterWidth v8::internal::anonymous_namespace{js-duration-format.cc}::StyleToWidth (JSDurationFormat::Style style)
Definition at line 961 of file js-duration-format.cc.
                                                              {
  switch (style) {
    case JSDurationFormat::Style::kLong:
      return ULISTFMT_WIDTH_WIDE;
    case JSDurationFormat::Style::kNarrow:
      return ULISTFMT_WIDTH_NARROW;
    case JSDurationFormat::Style::kShort:
    case JSDurationFormat::Style::kDigital:
      return ULISTFMT_WIDTH_SHORT;
  }
  UNREACHABLE();
}
References v8::internal::JSDurationFormat::kDigital, v8::internal::JSDurationFormat::kLong, v8::internal::JSDurationFormat::kNarrow, v8::internal::JSDurationFormat::kShort, and v8::internal::UNREACHABLE().
Referenced by PartitionDurationFormatPattern().
ToDurationRecord()
Maybe<DurationRecord> v8::internal::anonymous_namespace{js-duration-format.cc}::ToDurationRecord (Isolate * isolate, Handle< Object > input, const DurationRecord & default_value)
Definition at line 1018 of file js-duration-format.cc.
                                                                            {
  // 1-a. If Type(input) is String, throw a RangeError exception.
  if (IsString(*input)) {
    THROW_NEW_ERROR_RETURN_VALUE(
        isolate,
        NewRangeError(MessageTemplate::kInvalid,
                      isolate->factory()->object_string(), input),
        Nothing<DurationRecord>());
  }
  // Step 1-b - 23. Same as ToTemporalPartialDurationRecord.
  DurationRecord record;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, record,
      temporal::ToPartialDuration(isolate, input, default_value),
      Nothing<DurationRecord>());
  // 24. If IsValidDurationRecord(result) is false, throw a RangeError
  // exception.
  if (!temporal::IsValidDuration(isolate, record)) {
    THROW_NEW_ERROR_RETURN_VALUE(
        isolate,
        NewRangeError(MessageTemplate::kInvalid,
                      isolate->factory()->object_string(), input),
        Nothing<DurationRecord>());
  }
  return Just(record);
}
References v8::internal::Isolate::factory(), v8::internal::temporal::IsValidDuration(), v8::Just(), v8::internal::anonymous_namespace{isolate.cc}::kInvalid, MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE, THROW_NEW_ERROR_RETURN_VALUE, and v8::internal::temporal::ToPartialDuration().
Referenced by FormatCommon().
ToUNumberUnitWidth()
UNumberUnitWidth v8::internal::anonymous_namespace{js-duration-format.cc}::ToUNumberUnitWidth (JSDurationFormat::FieldStyle style)
Definition at line 637 of file js-duration-format.cc.
                                                                      {
  switch (style) {
    case JSDurationFormat::FieldStyle::kShort:
      return UNumberUnitWidth::UNUM_UNIT_WIDTH_SHORT;
    case JSDurationFormat::FieldStyle::kLong:
      return UNumberUnitWidth::UNUM_UNIT_WIDTH_FULL_NAME;
    case JSDurationFormat::FieldStyle::kNarrow:
      return UNumberUnitWidth::UNUM_UNIT_WIDTH_NARROW;
    default:
      UNREACHABLE();
  }
  // Avoid undefined behavior for enum values not handled by the exhaustive
  // switch, since they're read from inside the sandbox.
  SBXCHECK(false);
}
References v8::internal::JSDurationFormat::kLong, v8::internal::JSDurationFormat::kNarrow, v8::internal::JSDurationFormat::kShort, SBXCHECK, and v8::internal::UNREACHABLE().
Referenced by DurationRecordToListOfFormattedNumber(), and OutputLongShortNarrowOrNumeric().
Variable Documentation
kLongShortNarrowEnums
const std::initializer_list<JSDurationFormat::FieldStyle> v8::internal::anonymous_namespace{js-duration-format.cc}::kLongShortNarrowEnums
Initial value:
= {JSDurationFormat::FieldStyle::kLong,
                             JSDurationFormat::FieldStyle::kShort,
                             JSDurationFormat::FieldStyle::kNarrow}
Definition at line 72 of file js-duration-format.cc.
Referenced by v8::internal::JSDurationFormat::New().
kLongShortNarrowNumeric2DigitEnums
const std::initializer_list<JSDurationFormat::FieldStyle> v8::internal::anonymous_namespace{js-duration-format.cc}::kLongShortNarrowNumeric2DigitEnums
Initial value:
= {
        JSDurationFormat::FieldStyle::kLong,
        JSDurationFormat::FieldStyle::kShort,
        JSDurationFormat::FieldStyle::kNarrow,
        JSDurationFormat::FieldStyle::kNumeric,
        JSDurationFormat::FieldStyle::k2Digit}
Definition at line 81 of file js-duration-format.cc.
Referenced by v8::internal::JSDurationFormat::New().
kLongShortNarrowNumeric2DigitStrings
const auto v8::internal::anonymous_namespace{js-duration-format.cc}::kLongShortNarrowNumeric2DigitStrings
Initial value:
=
    std::to_array<const std::string_view>(
        {"long", "short", "narrow", "numeric", "2-digit"})
Definition at line 67 of file js-duration-format.cc.
Referenced by v8::internal::JSDurationFormat::New().
kLongShortNarrowNumericEnums
const std::initializer_list<JSDurationFormat::FieldStyle> v8::internal::anonymous_namespace{js-duration-format.cc}::kLongShortNarrowNumericEnums
Initial value:
= {JSDurationFormat::FieldStyle::kLong,
                                    JSDurationFormat::FieldStyle::kShort,
                                    JSDurationFormat::FieldStyle::kNarrow,
                                    JSDurationFormat::FieldStyle::kNumeric}
Definition at line 76 of file js-duration-format.cc.
Referenced by v8::internal::JSDurationFormat::New().
kLongShortNarrowNumericStrings
const auto v8::internal::anonymous_namespace{js-duration-format.cc}::kLongShortNarrowNumericStrings
Initial value:
=
    std::to_array<const std::string_view>(
        {"long", "short", "narrow", "numeric"})
Definition at line 64 of file js-duration-format.cc.
Referenced by v8::internal::JSDurationFormat::New().
kLongShortNarrowStrings
const auto v8::internal::anonymous_namespace{js-duration-format.cc}::kLongShortNarrowStrings
Initial value:
=
    std::to_array<const std::string_view>({"long", "short", "narrow"})
Definition at line 62 of file js-duration-format.cc.
Referenced by v8::internal::JSDurationFormat::New().