v8::internal::anonymous_namespace{builtins-shadow-realm.cc} Namespace Reference
Functions
MaybeDirectHandle< Object > GetWrappedValue (Isolate *isolate, DirectHandle< NativeContext > creation_context, Handle< Object > value)
Function Documentation
GetWrappedValue()
MaybeDirectHandle<Object> v8::internal::anonymous_namespace{builtins-shadow-realm.cc}::GetWrappedValue (Isolate * isolate, DirectHandle< NativeContext > creation_context, Handle< Object > value)
Definition at line 61 of file builtins-shadow-realm.cc.
                          {
  // 1. If Type(value) is Object, then
  if (!IsJSReceiver(*value)) {
    // 2. Return value.
    return value;
  }
  // 1a. If IsCallable(value) is false, throw a TypeError exception.
  if (!IsCallable(*value)) {
    // The TypeError thrown is created with creation Realm's TypeError
    // constructor instead of the executing Realm's.
    THROW_NEW_ERROR_RETURN_VALUE(
        isolate,
        NewError(
            direct_handle(creation_context->type_error_function(), isolate),
            MessageTemplate::kNotCallable, value),
        {});
  }
  // 1b. Return ? WrappedFunctionCreate(callerRealm, value).
  return JSWrappedFunction::Create(isolate, creation_context,
                                   Cast<JSReceiver>(value));
}
References v8::internal::JSWrappedFunction::Create(), v8::internal::direct_handle(), v8::internal::anonymous_namespace{runtime-internal.cc}::NewError(), THROW_NEW_ERROR_RETURN_VALUE, and v8::internal::value.
Referenced by v8::internal::BUILTIN().