v8_inspector::protocol::anonymous_namespace{string-util.cc} Namespace Reference
Functions
std::pair< uint8_t, uint8_t > SplitByte (uint8_t byte, uint8_t split)
v8::Maybe< uint8_t > DecodeByte (char byte)
Function Documentation
DecodeByte()
v8::Maybe<uint8_t> v8_inspector::protocol::anonymous_namespace{string-util.cc}::DecodeByte (char byte)
Definition at line 23 of file string-util.cc.
                                       {
  if ('A' <= byte && byte <= 'Z') return v8::Just<uint8_t>(byte - 'A');
  if ('a' <= byte && byte <= 'z') return v8::Just<uint8_t>(byte - 'a' + 26);
  if ('0' <= byte && byte <= '9')
    return v8::Just<uint8_t>(byte - '0' + 26 + 26);
  if (byte == '+') return v8::Just<uint8_t>(62);
  if (byte == '/') return v8::Just<uint8_t>(63);
  return v8::Nothing<uint8_t>();
}
Referenced by v8_inspector::protocol::Binary::fromBase64().
SplitByte()
std::pair<uint8_t, uint8_t> v8_inspector::protocol::anonymous_namespace{string-util.cc}::SplitByte (uint8_t byte, uint8_t split)
Definition at line 19 of file string-util.cc.
                                                                 {
  return {byte >> split, (byte & ((1 << split) - 1)) << (6 - split)};
}
References v8::internal::libvtune::split().
Referenced by v8_inspector::protocol::Binary::toBase64().