v8::internal::anonymous_namespace{macro-assembler-riscv.cc} Namespace Reference
Functions
static void TailCallOptimizedCodeSlot (MacroAssembler *masm, Register optimized_code_entry, Register scratch1, Register scratch2)
Function Documentation
TailCallOptimizedCodeSlot()
static void v8::internal::anonymous_namespace{macro-assembler-riscv.cc}::TailCallOptimizedCodeSlot (MacroAssembler * masm, Register optimized_code_entry, Register scratch1, Register scratch2) [static]
Definition at line 101 of file macro-assembler-riscv.cc.
                                                                            {
  // ----------- S t a t e -------------
  // -- a0 : actual argument count
  // -- a3 : new target (preserved for callee if needed, and caller)
  // -- a1 : target function (preserved for callee if needed, and caller)
  // -----------------------------------
  ASM_CODE_COMMENT(masm);
  DCHECK(!AreAliased(optimized_code_entry, a1, a3, scratch1, scratch2));
  Label heal_optimized_code_slot;
  // If the optimized code is cleared, go to runtime to update the optimization
  // marker field.
  __ LoadWeakValue(optimized_code_entry, optimized_code_entry,
                   &heal_optimized_code_slot);
  // The entry references a CodeWrapper object. Unwrap it now.
  __ LoadCodePointerField(
      optimized_code_entry,
      FieldMemOperand(optimized_code_entry, CodeWrapper::kCodeOffset));
  // Check if the optimized code is marked for deopt. If it is, call the
  // runtime to clear it.
  __ JumpIfCodeIsMarkedForDeoptimization(optimized_code_entry, scratch1,
                                         &heal_optimized_code_slot);
  // Optimized code is good, get it into the closure and link the closure into
  // the optimized functions list, then tail call the optimized code.
  // The feedback vector is no longer used, so reuse it as a scratch
  // register.
  __ ReplaceClosureCodeWithOptimizedCode(optimized_code_entry, a1);
  static_assert(kJavaScriptCallCodeStartRegister == a2, "ABI mismatch");
  __ LoadCodeInstructionStart(a2, optimized_code_entry, kJSEntrypointTag);
  __ Jump(a2);
  // Optimized code slot contains deoptimized code or code is cleared and
  // optimized code marker isn't updated. Evict the code, update the marker
  // and re-enter the closure's code.
  __ bind(&heal_optimized_code_slot);
  __ GenerateTailCallToReturnedCode(Runtime::kHealOptimizedCodeSlot);
}
References __, v8::internal::AreAliased(), ASM_CODE_COMMENT, v8::internal::DCHECK(), v8::internal::FieldMemOperand(), v8::internal::kJavaScriptCallCodeStartRegister, and v8::internal::kJSEntrypointTag.
Referenced by v8::internal::MacroAssembler::OptimizeCodeOrTailCallOptimizedCodeSlot().