v8::internal::anonymous_namespace{js-temporal-objects.cc} Namespace Reference
Typedefs
template<typename T >
using TemporalResult = diplomat::result< T, temporal_rs::TemporalError >
This header declare the Abstract Operations defined in the Temporal spec with the enum and struct for them.
template<typename T >
using TemporalAllocatedResult = TemporalResult< std::unique_ptr< T > >
Enumerations
enum class Disambiguation { kCompatible
, kEarlier
, kLater
, kReject
 }
enum class ShowCalendar { kAuto
, kAlways
, kNever
 }
enum class UnsignedRoundingMode {
kInfinity
, kZero
, kHalfInfinity
, kHalfZero
,
kHalfEven
 }
enum class UnitGroup { kDate
, kTime
, kDateTime
 }
enum Completeness { kComplete
, kPartial
 }
Functions
template<typename RetVal >
RetVal HandleStringEncodings (Isolate *isolate, DirectHandle< String > string, std::function< RetVal(std::string_view)> utf8_fn, std::function< RetVal(std::u16string_view)> utf16_fn)
template<typename ContainedValue >
Maybe< ContainedValue > ExtractRustResult (Isolate *isolate, TemporalResult< ContainedValue > &&rust_result)
template<typename JSType >
MaybeDirectHandle< JSType > ConstructRustWrappingType (Isolate *isolate, DirectHandle< JSFunction > target, DirectHandle< HeapObject > new_target, std::unique_ptr< typename JSType::RustType > &&rust_value)
template<typename JSType >
MaybeDirectHandle< JSType > ConstructRustWrappingType (Isolate *isolate, DirectHandle< JSFunction > target, DirectHandle< HeapObject > new_target, TemporalResult< std::unique_ptr< typename JSType::RustType >> &&rust_result)
Typedef Documentation
TemporalAllocatedResult
template<typename T >
using v8::internal::anonymous_namespace{js-temporal-objects.cc}::TemporalAllocatedResult = typedef TemporalResult<std::unique_ptr<T> >
Definition at line 54 of file js-temporal-objects.cc.
TemporalResult
template<typename T >
using v8::internal::anonymous_namespace{js-temporal-objects.cc}::TemporalResult = typedef diplomat::result<T, temporal_rs::TemporalError>
This header declare the Abstract Operations defined in the Temporal spec with the enum and struct for them.
Definition at line 52 of file js-temporal-objects.cc.
Enumeration Type Documentation
Completeness
enum v8::internal::anonymous_namespace{js-temporal-objects.cc}::Completeness
Enumerator
kComplete
kPartial
Definition at line 86 of file js-temporal-objects.cc.
                  {
  kComplete,
  kPartial,
};
Disambiguation
enum v8::internal::anonymous_namespace{js-temporal-objects.cc}::Disambiguation [strong]
Enumerator
kCompatible
kEarlier
kLater
kReject
Definition at line 64 of file js-temporal-objects.cc.
{ kCompatible, kEarlier, kLater, kReject };
ShowCalendar
enum v8::internal::anonymous_namespace{js-temporal-objects.cc}::ShowCalendar [strong]
Enumerator
kAuto
kAlways
kNever
Definition at line 67 of file js-temporal-objects.cc.
{ kAuto, kAlways, kNever };
UnitGroup
enum v8::internal::anonymous_namespace{js-temporal-objects.cc}::UnitGroup [strong]
Enumerator
kDate
kTime
kDateTime
Definition at line 79 of file js-temporal-objects.cc.
                     {
  kDate,
  kTime,
  kDateTime,
};
UnsignedRoundingMode
enum v8::internal::anonymous_namespace{js-temporal-objects.cc}::UnsignedRoundingMode [strong]
Enumerator
kInfinity
kZero
kHalfInfinity
kHalfZero
kHalfEven
Definition at line 70 of file js-temporal-objects.cc.
                                {
  kInfinity,
  kZero,
  kHalfInfinity,
  kHalfZero,
  kHalfEven
};
Function Documentation
ConstructRustWrappingType() [1/2]
template<typename JSType >
MaybeDirectHandle<JSType> v8::internal::anonymous_namespace{js-temporal-objects.cc}::ConstructRustWrappingType (Isolate * isolate, DirectHandle< JSFunction > target, DirectHandle< HeapObject > new_target, std::unique_ptr< typename JSType::RustType > && rust_value)
Definition at line 175 of file js-temporal-objects.cc.
                                                         {
  // Managed requires shared ownership
  std::shared_ptr<typename JSType::RustType> rust_shared =
      std::move(rust_value);
  DirectHandle<Managed<typename JSType::RustType>> managed =
      Managed<typename JSType::RustType>::From(isolate, 0, rust_shared);
  ORDINARY_CREATE_FROM_CONSTRUCTOR(object, target, new_target, JSType)
  object->initialize_with_wrapped_rust_value(*managed);
  return object;
}
References v8::internal::Managed< CppType >::From(), v8::internal::compiler::anonymous_namespace{operation-typer.cc}::JSType(), and ORDINARY_CREATE_FROM_CONSTRUCTOR.
ConstructRustWrappingType() [2/2]
template<typename JSType >
MaybeDirectHandle<JSType> v8::internal::anonymous_namespace{js-temporal-objects.cc}::ConstructRustWrappingType (Isolate * isolate, DirectHandle< JSFunction > target, DirectHandle< HeapObject > new_target, TemporalResult< std::unique_ptr< typename JSType::RustType >> && rust_result)
Definition at line 193 of file js-temporal-objects.cc.
                                                                          {
  std::unique_ptr<typename JSType::RustType> rust_value = nullptr;
  MAYBE_MOVE_RETURN_ON_EXCEPTION_VALUE(
      isolate, rust_value, ExtractRustResult(isolate, std::move(rust_result)),
      MaybeDirectHandle<JSType>());
  return ConstructRustWrappingType<JSType>(isolate, target, new_target,
                                           std::move(rust_value));
}
References ExtractRustResult(), and MAYBE_MOVE_RETURN_ON_EXCEPTION_VALUE.
ExtractRustResult()
template<typename ContainedValue >
Maybe<ContainedValue> v8::internal::anonymous_namespace{js-temporal-objects.cc}::ExtractRustResult (Isolate * isolate, TemporalResult< ContainedValue > && rust_result)
Definition at line 144 of file js-temporal-objects.cc.
                                                                    {
  if (rust_result.is_err()) {
    auto err = std::move(rust_result).err().value();
    switch (err.kind) {
      case temporal_rs::ErrorKind::Type:
        THROW_NEW_ERROR_RETURN_VALUE(isolate,
                                     NEW_TEMPORAL_INVALID_ARG_TYPE_ERROR(),
                                     Nothing<ContainedValue>());
        break;
      case temporal_rs::ErrorKind::Range:
        THROW_NEW_ERROR_RETURN_VALUE(isolate,
                                     NEW_TEMPORAL_INVALID_ARG_RANGE_ERROR(),
                                     Nothing<ContainedValue>());
        break;
      case temporal_rs::ErrorKind::Syntax:
      case temporal_rs::ErrorKind::Assert:
      case temporal_rs::ErrorKind::Generic:
      default:
        // These cases shouldn't happen; the spec doesn't currently trigger
        // these errors
        THROW_NEW_ERROR_RETURN_VALUE(isolate, NEW_TEMPORAL_INTERNAL_ERROR(),
                                     Nothing<ContainedValue>());
    }
    return Nothing<ContainedValue>();
  }
  return Just(std::move(rust_result).ok().value());
}
References v8::Just(), NEW_TEMPORAL_INTERNAL_ERROR, NEW_TEMPORAL_INVALID_ARG_RANGE_ERROR, NEW_TEMPORAL_INVALID_ARG_TYPE_ERROR, v8::internal::compiler::turboshaft::Range(), THROW_NEW_ERROR_RETURN_VALUE, and v8::internal::value.
Referenced by ConstructRustWrappingType(), v8::internal::temporal::ISODateTimeToString(), v8::internal::temporal::TemporalDurationToString(), v8::internal::temporal::TemporalInstantToString(), v8::internal::temporal::TimeRecordToString(), and v8::internal::temporal::ToTemporalTimeZoneIdentifier().
HandleStringEncodings()
template<typename RetVal >
RetVal v8::internal::anonymous_namespace{js-temporal-objects.cc}::HandleStringEncodings (Isolate * isolate, DirectHandle< String > string, std::function< RetVal(std::string_view)> utf8_fn, std::function< RetVal(std::u16string_view)> utf16_fn)
Definition at line 116 of file js-temporal-objects.cc.
                                                     {
  string = String::Flatten(isolate, string);
  DisallowGarbageCollection no_gc;
  auto flat = string->GetFlatContent(no_gc);
  if (flat.IsOneByte()) {
    auto content = flat.ToOneByteVector();
    // reinterpret_cast since std string types accept signed chars
    std::string_view view(reinterpret_cast<const char*>(content.data()),
                          content.size());
    return utf8_fn(view);
  } else {
    auto content = flat.ToUC16Vector();
    std::u16string_view view(reinterpret_cast<const char16_t*>(content.data()),
                             content.size());
    return utf16_fn(view);
  }
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.