v8::internal::anonymous_namespace{runtime-test-wasm.cc} Namespace Reference
Classes
struct WasmCompileControls
Typedefs
using WasmCompileControlsMap = std::map< v8::Isolate *, WasmCompileControls >
Functions
V8_WARN_UNUSED_RESULT Tagged< Object > CrashUnlessFuzzing (Isolate *isolate)
DEFINE_LAZY_LEAKY_OBJECT_GETTER(WasmCompileControlsMap, GetPerIsolateWasmControls) base bool IsWasmCompileAllowed (v8::Isolate *isolate, v8::Local< v8::Value > value, bool is_async)
bool IsWasmInstantiateAllowed (v8::Isolate *isolate, v8::Local< v8::Value > module_or_bytes, bool is_async)
v8::Local< v8::Value > NewRangeException (v8::Isolate *isolate, const char *message)
void ThrowRangeException (v8::Isolate *isolate, const char *message)
bool WasmModuleOverride (const v8::FunctionCallbackInfo< v8::Value > &info)
bool WasmInstanceOverride (const v8::FunctionCallbackInfo< v8::Value > &info)
void PrintIndentation (int stack_size)
int WasmStackSize (Isolate *isolate)
bool DisallowWasmCodegenFromStringsCallback (v8::Local< v8::Context > context, v8::Local< v8::String > source)
template<typename T1 , typename T2 = T1>
void PrintRep (Address address, const char *str)
V8_WARN_UNUSED_RESULT bool ValidateFunctionNowIfNeeded (Isolate *isolate, wasm::NativeModule *native_module, int func_index)
Typedef Documentation
WasmCompileControlsMap
using v8::internal::anonymous_namespace{runtime-test-wasm.cc}::WasmCompileControlsMap = typedef std::map<v8::Isolate*, WasmCompileControls>
Definition at line 42 of file runtime-test-wasm.cc.
Function Documentation
CrashUnlessFuzzing()
V8_WARN_UNUSED_RESULT Tagged<Object> v8::internal::anonymous_namespace{runtime-test-wasm.cc}::CrashUnlessFuzzing (Isolate * isolate)
Definition at line 33 of file runtime-test-wasm.cc.
                                                                          {
  CHECK(v8_flags.fuzzing);
  return ReadOnlyRoots(isolate).undefined_value();
}
References CHECK, and v8::internal::v8_flags.
Referenced by v8::internal::CreateWasmObject(), and v8::internal::RUNTIME_FUNCTION().
DisallowWasmCodegenFromStringsCallback()
bool v8::internal::anonymous_namespace{runtime-test-wasm.cc}::DisallowWasmCodegenFromStringsCallback (v8::Local< v8::Context > context, v8::Local< v8::String > source)
Definition at line 370 of file runtime-test-wasm.cc.
                                                                      {
  return false;
}
Referenced by v8::internal::RUNTIME_FUNCTION().
IsWasmCompileAllowed()
DEFINE_LAZY_LEAKY_OBJECT_GETTER (WasmCompileControlsMap, GetPerIsolateWasmControls) base bool v8::internal::anonymous_namespace{runtime-test-wasm.cc}::IsWasmCompileAllowed (v8::Isolate * isolate, v8::Local< v8::Value > value, bool is_async)
Definition at line 51 of file runtime-test-wasm.cc.
                                         {
  base::MutexGuard guard(g_PerIsolateWasmControlsMutex.Pointer());
  DCHECK_GT(GetPerIsolateWasmControls()->count(isolate), 0);
  const WasmCompileControls& ctrls = GetPerIsolateWasmControls()->at(isolate);
  return (is_async && ctrls.AllowAnySizeForAsync) ||
         (value->IsArrayBuffer() && value.As<v8::ArrayBuffer>()->ByteLength() <=
                                        ctrls.MaxWasmBufferSize) ||
         (value->IsArrayBufferView() &&
          value.As<v8::ArrayBufferView>()->ByteLength() <=
              ctrls.MaxWasmBufferSize);
}
References v8::internal::anonymous_namespace{runtime-test-wasm.cc}::WasmCompileControls::AllowAnySizeForAsync, DCHECK_GT, v8::internal::anonymous_namespace{runtime-test-wasm.cc}::WasmCompileControls::MaxWasmBufferSize, v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::Pointer(), and v8::internal::value.
Referenced by IsWasmInstantiateAllowed(), and WasmModuleOverride().
IsWasmInstantiateAllowed()
bool v8::internal::anonymous_namespace{runtime-test-wasm.cc}::IsWasmInstantiateAllowed (v8::Isolate * isolate, v8::Local< v8::Value > module_or_bytes, bool is_async)
Definition at line 65 of file runtime-test-wasm.cc.
                                             {
  base::MutexGuard guard(g_PerIsolateWasmControlsMutex.Pointer());
  DCHECK_GT(GetPerIsolateWasmControls()->count(isolate), 0);
  const WasmCompileControls& ctrls = GetPerIsolateWasmControls()->at(isolate);
  if (is_async && ctrls.AllowAnySizeForAsync) return true;
  if (!module_or_bytes->IsWasmModuleObject()) {
    return IsWasmCompileAllowed(isolate, module_or_bytes, is_async);
  }
  v8::Local<v8::WasmModuleObject> module =
      v8::Local<v8::WasmModuleObject>::Cast(module_or_bytes);
  return static_cast<uint32_t>(
             module->GetCompiledModule().GetWireBytesRef().size()) <=
         ctrls.MaxWasmBufferSize;
}
References v8::internal::anonymous_namespace{runtime-test-wasm.cc}::WasmCompileControls::AllowAnySizeForAsync, v8::Local< T >::Cast(), DCHECK_GT, IsWasmCompileAllowed(), v8::Value::IsWasmModuleObject(), v8::internal::anonymous_namespace{runtime-test-wasm.cc}::WasmCompileControls::MaxWasmBufferSize, and v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::Pointer().
Referenced by WasmInstanceOverride().
NewRangeException()
v8::Local<v8::Value> v8::internal::anonymous_namespace{runtime-test-wasm.cc}::NewRangeException (v8::Isolate * isolate, const char * message)
Definition at line 82 of file runtime-test-wasm.cc.
                                                            {
  return v8::Exception::RangeError(
      v8::String::NewFromOneByte(isolate,
                                 reinterpret_cast<const uint8_t*>(message))
          .ToLocalChecked());
}
References v8::String::NewFromOneByte(), and v8::Exception::RangeError().
Referenced by ThrowRangeException().
PrintIndentation()
void v8::internal::anonymous_namespace{runtime-test-wasm.cc}::PrintIndentation (int stack_size)
Definition at line 137 of file runtime-test-wasm.cc.
                                      {
  const int max_display = 80;
  if (stack_size <= max_display) {
    PrintF("%4d:%*s", stack_size, stack_size, "");
  } else {
    PrintF("%4d:%*s", stack_size, max_display, "...");
  }
}
References v8::internal::PrintF().
Referenced by v8::internal::RUNTIME_FUNCTION().
PrintRep()
template<typename T1 , typename T2 = T1>
void v8::internal::anonymous_namespace{runtime-test-wasm.cc}::PrintRep (Address address, const char * str)
Definition at line 583 of file runtime-test-wasm.cc.
                                                {
  PrintF("%4s:", str);
  const auto t1 = base::ReadLittleEndianValue<T1>(address);
  if constexpr (std::is_floating_point_v<T1>) {
    PrintF("%f", t1);
  } else if constexpr (sizeof(T1) > sizeof(uint32_t)) {
    PrintF("%" PRIu64, t1);
  } else {
    PrintF("%u", t1);
  }
  const auto t2 = base::ReadLittleEndianValue<T2>(address);
  if constexpr (sizeof(T1) > sizeof(uint32_t)) {
    PrintF(" / %016" PRIx64 "\n", t2);
  } else {
    PrintF(" / %0*x\n", static_cast<int>(2 * sizeof(T2)), t2);
  }
}
References v8::internal::PrintF(), T1, and T2.
ThrowRangeException()
void v8::internal::anonymous_namespace{runtime-test-wasm.cc}::ThrowRangeException (v8::Isolate * isolate, const char * message)
Definition at line 90 of file runtime-test-wasm.cc.
                                                                  {
  isolate->ThrowException(NewRangeException(isolate, message));
}
References NewRangeException(), and v8::Isolate::ThrowException().
Referenced by WasmInstanceOverride(), and WasmModuleOverride().
ValidateFunctionNowIfNeeded()
V8_WARN_UNUSED_RESULT bool v8::internal::anonymous_namespace{runtime-test-wasm.cc}::ValidateFunctionNowIfNeeded (Isolate * isolate, wasm::NativeModule * native_module, int func_index)
Definition at line 679 of file runtime-test-wasm.cc.
                                                 {
  const wasm::WasmModule* module = native_module->module();
  if (module->function_was_validated(func_index)) return true;
  DCHECK(v8_flags.wasm_lazy_validation);
  Zone validation_zone(isolate->allocator(), ZONE_NAME);
  wasm::WasmDetectedFeatures unused_detected_features;
  const wasm::WasmFunction* func = &module->functions[func_index];
  bool is_shared = module->type(func->sig_index).is_shared;
  base::Vector<const uint8_t> wire_bytes = native_module->wire_bytes();
  wasm::FunctionBody body{
      func->sig, func->code.offset(), wire_bytes.begin() + func->code.offset(),
      wire_bytes.begin() + func->code.end_offset(), is_shared};
  if (ValidateFunctionBody(&validation_zone, native_module->enabled_features(),
                           module, &unused_detected_features, body)
          .failed()) {
    return false;
  }
  module->set_function_validated(func_index);
  return true;
}
References v8::internal::Isolate::allocator(), v8::base::Vector< T >::begin(), v8::internal::wasm::WasmFunction::code, v8::internal::DCHECK(), v8::internal::wasm::NativeModule::enabled_features(), v8::internal::wasm::WireBytesRef::end_offset(), v8::internal::wasm::Result< T >::failed(), v8::internal::wasm::WasmModule::function_was_validated(), v8::internal::wasm::WasmModule::functions, v8::internal::is_shared, v8::internal::wasm::TypeDefinition::is_shared, v8::internal::wasm::NativeModule::module(), v8::internal::wasm::WireBytesRef::offset(), v8::internal::wasm::WasmModule::set_function_validated(), v8::internal::wasm::WasmFunction::sig, v8::internal::wasm::WasmFunction::sig_index, v8::internal::wasm::WasmModule::type(), v8::internal::v8_flags, v8::internal::wasm::ValidateFunctionBody(), v8::internal::wasm::NativeModule::wire_bytes(), and ZONE_NAME.
Referenced by v8::internal::RUNTIME_FUNCTION().
WasmInstanceOverride()
bool v8::internal::anonymous_namespace{runtime-test-wasm.cc}::WasmInstanceOverride (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 101 of file runtime-test-wasm.cc.
                                                                       {
  DCHECK(ValidateCallbackInfo(info));
  if (IsWasmInstantiateAllowed(info.GetIsolate(), info[0], false)) return false;
  ThrowRangeException(info.GetIsolate(), "Sync instantiate not allowed");
  return true;
}
References v8::internal::DCHECK(), v8::FunctionCallbackInfo< T >::GetIsolate(), IsWasmInstantiateAllowed(), ThrowRangeException(), and v8::internal::ValidateCallbackInfo().
Referenced by v8::internal::RUNTIME_FUNCTION().
WasmModuleOverride()
bool v8::internal::anonymous_namespace{runtime-test-wasm.cc}::WasmModuleOverride (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 94 of file runtime-test-wasm.cc.
                                                                     {
  DCHECK(ValidateCallbackInfo(info));
  if (IsWasmCompileAllowed(info.GetIsolate(), info[0], false)) return false;
  ThrowRangeException(info.GetIsolate(), "Sync compile not allowed");
  return true;
}
References v8::internal::DCHECK(), v8::FunctionCallbackInfo< T >::GetIsolate(), IsWasmCompileAllowed(), ThrowRangeException(), and v8::internal::ValidateCallbackInfo().
Referenced by v8::internal::RUNTIME_FUNCTION().
WasmStackSize()
int v8::internal::anonymous_namespace{runtime-test-wasm.cc}::WasmStackSize (Isolate * isolate)
Definition at line 146 of file runtime-test-wasm.cc.
                                    {
  // TODO(wasm): Fix this for mixed JS/Wasm stacks with both --trace and
  // --trace-wasm.
  int n = 0;
  for (DebuggableStackFrameIterator it(isolate); !it.done(); it.Advance()) {
    if (it.is_wasm()) n++;
  }
  return n;
}
References v8::internal::DebuggableStackFrameIterator::done().
Referenced by v8::internal::RUNTIME_FUNCTION().