v8::internal::wasm::anonymous_namespace{wasm-interpreter-runtime.cc} Namespace Reference
Functions
void RedirectCodeToUnwindHandler (const uint8_t *&code)
Function Documentation
RedirectCodeToUnwindHandler()
void v8::internal::wasm::anonymous_namespace{wasm-interpreter-runtime.cc}::RedirectCodeToUnwindHandler (const uint8_t *& code)
Definition at line 660 of file wasm-interpreter-runtime.cc.
                                                       {
  // Resume execution from s2s_Unwind, which unwinds the Wasm stack frames
  code = reinterpret_cast<uint8_t*>(&s_unwind_code);
}
References code, and v8::internal::wasm::s_unwind_code.
Referenced by v8::internal::wasm::WasmInterpreterRuntime::ExecuteCallRef(), v8::internal::wasm::WasmInterpreterRuntime::ExecuteFunction(), v8::internal::wasm::WasmInterpreterRuntime::ExecuteImportedFunction(), v8::internal::wasm::WasmInterpreterRuntime::ExecuteIndirectCall(), v8::internal::wasm::WasmInterpreterRuntime::SetTrap(), and v8::internal::wasm::WasmInterpreterRuntime::ThrowException().