v8::internal::anonymous_namespace{runtime-compiler.cc} Namespace Reference
Functions
void LogExecution (Isolate *isolate, DirectHandle< JSFunction > function)
bool TryGetOptimizedOsrCode (Isolate *isolate, Tagged< FeedbackVector > vector, const interpreter::BytecodeArrayIterator &it, Tagged< Code > *code_out)
bool DeoptAllOsrLoopsContainingDeoptExit (Isolate *isolate, Tagged< JSFunction > function, BytecodeOffset deopt_exit_offset)
void GetOsrOffsetAndFunctionForOSR (Isolate *isolate, BytecodeOffset *osr_offset, Handle< JSFunction > *function)
Tagged< Object > CompileOptimizedOSR (Isolate *isolate, DirectHandle< JSFunction > function, CodeKind min_opt_level, BytecodeOffset osr_offset)
Tagged< Object > CompileOptimizedOSRFromMaglev (Isolate *isolate, DirectHandle< JSFunction > function, BytecodeOffset osr_offset)
Function Documentation
CompileOptimizedOSR()
Tagged<Object> v8::internal::anonymous_namespace{runtime-compiler.cc}::CompileOptimizedOSR (Isolate * isolate, DirectHandle< JSFunction > function, CodeKind min_opt_level, BytecodeOffset osr_offset)
Definition at line 618 of file runtime-compiler.cc.
                                                              {
  ConcurrencyMode mode =
      V8_LIKELY(isolate->concurrent_recompilation_enabled() &&
                v8_flags.concurrent_osr)
          ? ConcurrencyMode::kConcurrent
          : ConcurrencyMode::kSynchronous;
  if (V8_UNLIKELY(isolate->EfficiencyModeEnabledForTiering() &&
                  min_opt_level == CodeKind::MAGLEV)) {
    mode = ConcurrencyMode::kSynchronous;
  }
  DirectHandle<Code> result;
  if (!Compiler::CompileOptimizedOSR(
           isolate, function, osr_offset, mode,
           (maglev::IsMaglevOsrEnabled() && min_opt_level == CodeKind::MAGLEV)
               ? CodeKind::MAGLEV
               : CodeKind::TURBOFAN_JS)
           .ToHandle(&result) ||
      result->marked_for_deoptimization()) {
    // An empty result can mean one of two things:
    // 1) we've started a concurrent compilation job - everything is fine.
    // 2) synchronous compilation failed for some reason.
#ifndef V8_ENABLE_LEAPTIERING
    if (!function->HasAttachedOptimizedCode(isolate)) {
      function->UpdateCode(isolate, function->shared()->GetCode(isolate));
    }
#endif // V8_ENABLE_LEAPTIERING
    return Smi::zero();
  }
  DCHECK(!result.is_null());
  DCHECK(result->is_turbofanned() || result->is_maglevved());
  DCHECK(CodeKindIsOptimizedJSFunction(result->kind()));
#ifdef DEBUG
  Tagged<DeoptimizationData> data =
      Cast<DeoptimizationData>(result->deoptimization_data());
  DCHECK_EQ(BytecodeOffset(data->OsrBytecodeOffset().value()), osr_offset);
  DCHECK_GE(data->OsrPcOffset().value(), 0);
#endif // DEBUG
  // First execution logging happens in LogOrTraceOptimizedOSREntry
  return *result;
}
References v8::internal::CodeKindIsOptimizedJSFunction(), v8::internal::Isolate::concurrent_recompilation_enabled(), DCHECK, DCHECK_EQ, DCHECK_GE, v8::internal::Isolate::EfficiencyModeEnabledForTiering(), v8::internal::maglev::IsMaglevOsrEnabled(), mode(), v8::base::internal::result, v8::anonymous_namespace{api.cc}::ToHandle(), v8::internal::v8_flags, V8_LIKELY, V8_UNLIKELY, and v8::internal::zero.
Referenced by CompileOptimizedOSRFromMaglev(), and v8::internal::RUNTIME_FUNCTION().
CompileOptimizedOSRFromMaglev()
Tagged<Object> v8::internal::anonymous_namespace{runtime-compiler.cc}::CompileOptimizedOSRFromMaglev (Isolate * isolate, DirectHandle< JSFunction > function, BytecodeOffset osr_offset)
Definition at line 685 of file runtime-compiler.cc.
                                                                        {
  // This path is only relevant for tests (all production configurations enable
  // concurrent OSR). It's quite subtle, if interested read on:
  if (V8_UNLIKELY(!isolate->concurrent_recompilation_enabled() ||
                  !v8_flags.concurrent_osr)) {
    // - Synchronous Turbofan compilation may trigger lazy deoptimization (e.g.
    // through compilation dependency finalization actions).
    // - Maglev (currently) disallows marking an opcode as both can_lazy_deopt
    // and can_eager_deopt.
    // - Maglev's JumpLoop opcode (the logical caller of this runtime function)
    // is marked as can_eager_deopt since OSR'ing to Turbofan involves
    // deoptimizing to Ignition under the hood.
    // - Thus this runtime function *must not* trigger a lazy deopt, and
    // therefore cannot trigger synchronous Turbofan compilation (see above).
    //
    // We solve this synchronous OSR case by bailing out early to Ignition, and
    // letting it handle OSR. How do we trigger the early bailout? Returning
    // any non-null InstructionStream from this function triggers the deopt in
    // JumpLoop.
    if (v8_flags.trace_osr) {
      CodeTracer::Scope scope(isolate->GetCodeTracer());
      PrintF(scope.file(),
             "[OSR - Tiering from Maglev to Turbofan failed because "
             "concurrent_osr is disabled. function: %s, osr offset: %d]\n",
             function->DebugNameCStr().get(), osr_offset.ToInt());
    }
    return Smi::zero();
  }
  if (V8_UNLIKELY(isolate->EfficiencyModeEnabledForTiering() ||
                  isolate->BatterySaverModeEnabled())) {
    function->feedback_vector()->reset_osr_urgency();
    function->SetInterruptBudget(isolate, BudgetModification::kRaise);
    return Smi::zero();
  }
  return CompileOptimizedOSR(isolate, function, CodeKind::TURBOFAN_JS,
                             osr_offset);
}
References v8::internal::Isolate::BatterySaverModeEnabled(), CompileOptimizedOSR(), v8::internal::Isolate::concurrent_recompilation_enabled(), v8::internal::Isolate::EfficiencyModeEnabledForTiering(), v8::internal::CodeTracer::Scope::file(), v8::internal::Isolate::GetCodeTracer(), v8::internal::PrintF(), v8::internal::BytecodeOffset::ToInt(), v8::internal::v8_flags, V8_UNLIKELY, and v8::internal::zero.
Referenced by v8::internal::RUNTIME_FUNCTION().
DeoptAllOsrLoopsContainingDeoptExit()
bool v8::internal::anonymous_namespace{runtime-compiler.cc}::DeoptAllOsrLoopsContainingDeoptExit (Isolate * isolate, Tagged< JSFunction > function, BytecodeOffset deopt_exit_offset)
Definition at line 421 of file runtime-compiler.cc.
                                                                           {
  DisallowGarbageCollection no_gc;
  DCHECK(!deopt_exit_offset.IsNone());
  if (!v8_flags.use_ic ||
      !function->feedback_vector()->maybe_has_optimized_osr_code()) {
    return false;
  }
  Handle<BytecodeArray> bytecode_array(
      function->shared()->GetBytecodeArray(isolate), isolate);
  DCHECK(interpreter::BytecodeArrayIterator::IsValidOffset(
      bytecode_array, deopt_exit_offset.ToInt()));
  Tagged<FeedbackVector> vector = function->feedback_vector();
  Tagged<Code> code;
  bool any_marked = false;
  bool has_maglev_code = false;
  bool has_turbofan_code = false;
  interpreter::BytecodeArrayIterator it(bytecode_array);
  for (; !it.done(); it.Advance()) {
    // We're only interested in loop ranges.
    if (it.current_bytecode() != interpreter::Bytecode::kJumpLoop) continue;
    bool has_osr_code = TryGetOptimizedOsrCode(isolate, vector, it, &code);
    if (has_osr_code) {
      if (base::IsInRange(deopt_exit_offset.ToInt(), it.GetJumpTargetOffset(),
                          it.current_offset())) {
        code->SetMarkedForDeoptimization(isolate,
                                         LazyDeoptimizeReason::kEagerDeopt);
        any_marked = true;
      } else {
        has_turbofan_code |= code->is_turbofanned();
        has_maglev_code |= code->is_maglevved();
      }
    }
  }
  Tagged<FeedbackVector> fbv = function->feedback_vector();
  if (!has_maglev_code && fbv->maybe_has_maglev_osr_code()) {
    fbv->set_maybe_has_optimized_osr_code(false, CodeKind::MAGLEV);
  }
  if (!has_turbofan_code && fbv->maybe_has_turbofan_osr_code()) {
    fbv->set_maybe_has_optimized_osr_code(false, CodeKind::TURBOFAN_JS);
  }
  return any_marked;
}
References v8::internal::interpreter::BytecodeArrayIterator::Advance(), code, v8::internal::interpreter::BytecodeArrayIterator::current_bytecode(), v8::internal::interpreter::BytecodeArrayIterator::current_offset(), DCHECK, v8::internal::interpreter::BytecodeArrayIterator::done(), v8::internal::interpreter::BytecodeArrayIterator::GetJumpTargetOffset(), v8::internal::BytecodeOffset::IsNone(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::BytecodeOffset::ToInt(), TryGetOptimizedOsrCode(), and v8::internal::v8_flags.
Referenced by v8::internal::RUNTIME_FUNCTION().
GetOsrOffsetAndFunctionForOSR()
void v8::internal::anonymous_namespace{runtime-compiler.cc}::GetOsrOffsetAndFunctionForOSR (Isolate * isolate, BytecodeOffset * osr_offset, Handle< JSFunction > * function)
Definition at line 598 of file runtime-compiler.cc.
                                                                 {
  DCHECK(osr_offset->IsNone());
  DCHECK(function->is_null());
  // Determine the frame that triggered the OSR request.
  JavaScriptStackFrameIterator it(isolate);
  UnoptimizedJSFrame* frame = UnoptimizedJSFrame::cast(it.frame());
  DCHECK_IMPLIES(frame->is_interpreted(),
                 frame->LookupCode()->is_interpreter_trampoline_builtin());
  DCHECK_IMPLIES(frame->is_baseline(),
                 frame->LookupCode()->kind() == CodeKind::BASELINE);
  *osr_offset = BytecodeOffset(frame->GetBytecodeOffset());
  *function = handle(frame->function(), isolate);
  DCHECK(!osr_offset->IsNone());
  DCHECK((*function)->shared()->HasBytecodeArray());
}
References DCHECK, DCHECK_IMPLIES, v8::internal::JavaScriptStackFrameIterator::frame(), v8::internal::JavaScriptFrame::function(), v8::internal::UnoptimizedJSFrame::GetBytecodeOffset(), v8::internal::handle(), v8::internal::StackFrame::is_baseline(), v8::internal::StackFrame::is_interpreted(), v8::internal::BytecodeOffset::IsNone(), and v8::internal::StackFrame::LookupCode().
Referenced by v8::internal::RUNTIME_FUNCTION().
LogExecution()
void v8::internal::anonymous_namespace{runtime-compiler.cc}::LogExecution (Isolate * isolate, DirectHandle< JSFunction > function)
Definition at line 25 of file runtime-compiler.cc.
                                                                       {
  DCHECK(v8_flags.log_function_events);
  if (!function->has_feedback_vector()) return;
#ifdef V8_ENABLE_LEAPTIERING
  DCHECK(function->IsLoggingRequested(isolate));
  IsolateGroup::current()->js_dispatch_table()->ResetTieringRequest(
      function->dispatch_handle());
#else
  if (!function->feedback_vector()->log_next_execution()) return;
#endif
  DirectHandle<SharedFunctionInfo> sfi(function->shared(), isolate);
  DirectHandle<String> name = SharedFunctionInfo::DebugName(isolate, sfi);
  DisallowGarbageCollection no_gc;
  Tagged<SharedFunctionInfo> raw_sfi = *sfi;
  std::string event_name = "first-execution";
  CodeKind kind = function->abstract_code(isolate)->kind(isolate);
  // Not adding "-interpreter" for tooling backwards compatibility.
  if (kind != CodeKind::INTERPRETED_FUNCTION) {
    event_name += "-";
    event_name += CodeKindToString(kind);
  }
  LOG(isolate, FunctionEvent(
                   event_name.c_str(), Cast<Script>(raw_sfi->script())->id(), 0,
                   raw_sfi->StartPosition(), raw_sfi->EndPosition(), *name));
#ifndef V8_ENABLE_LEAPTIERING
  function->feedback_vector()->set_log_next_execution(false);
#endif // !V8_ENABLE_LEAPTIERING
}
References v8::internal::CodeKindToString(), v8::internal::IsolateGroup::current(), v8::internal::DCHECK(), v8::internal::SharedFunctionInfo::DebugName(), LOG, v8::internal::name, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::string, and v8::internal::v8_flags.
Referenced by v8::internal::RUNTIME_FUNCTION().
TryGetOptimizedOsrCode()
bool v8::internal::anonymous_namespace{runtime-compiler.cc}::TryGetOptimizedOsrCode (Isolate * isolate, Tagged< FeedbackVector > vector, const interpreter::BytecodeArrayIterator & it, Tagged< Code > * code_out)
Definition at line 403 of file runtime-compiler.cc.
                                                    {
  std::optional<Tagged<Code>> maybe_code =
      vector->GetOptimizedOsrCode(isolate, {}, it.GetSlotOperand(2));
  if (maybe_code.has_value()) {
    *code_out = maybe_code.value();
    return true;
  }
  return false;
}
References v8::internal::interpreter::BytecodeArrayIterator::GetSlotOperand().
Referenced by DeoptAllOsrLoopsContainingDeoptExit().