v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc} Namespace Reference
Classes
struct LoadStoreView
struct ScaledIndexMatch
struct BaseWithScaledIndexAndDisplacementMatch
Functions
bool MatchScaledIndex (InstructionSelector *selector, OpIndex node, OpIndex *index, int *scale, bool *power_of_two_plus_one)
std::optional< ScaledIndexMatch > TryMatchScaledIndex (InstructionSelector *selector, OpIndex node, bool allow_power_of_two_plus_one)
std::optional< BaseWithScaledIndexAndDisplacementMatch > TryMatchBaseWithScaledIndexAndDisplacementForWordBinop (InstructionSelector *selector, OpIndex left, OpIndex right)
std::optional< BaseWithScaledIndexAndDisplacementMatch > TryMatchBaseWithScaledIndexAndDisplacement (InstructionSelector *selector, OpIndex node)
ArchOpcode GetLoadOpcode (LoadRepresentation load_rep)
void VisitRO (InstructionSelector *selector, OpIndex node, ArchOpcode opcode)
void VisitROWithTemp (InstructionSelector *selector, OpIndex node, ArchOpcode opcode)
void VisitROWithTempSimd (InstructionSelector *selector, OpIndex node, ArchOpcode opcode)
void VisitRR (InstructionSelector *selector, OpIndex node, InstructionCode opcode)
void VisitRROFloat (InstructionSelector *selector, OpIndex node, ArchOpcode opcode)
void VisitFloatUnop (InstructionSelector *selector, OpIndex node, OpIndex input, ArchOpcode opcode)
ArchOpcode GetStoreOpcode (MachineRepresentation rep)
ArchOpcode GetSeqCstStoreOpcode (MachineRepresentation rep)
void VisitAtomicExchange (InstructionSelector *selector, OpIndex node, ArchOpcode opcode, MachineRepresentation rep)
void VisitStoreCommon (InstructionSelector *selector, const InstructionSelector::StoreView &store)
void VisitBinop (InstructionSelector *selector, OpIndex node, InstructionCode opcode, FlagsContinuation *cont)
void VisitBinop (InstructionSelector *selector, OpIndex node, InstructionCode opcode)
void VisitMulHigh (InstructionSelector *selector, OpIndex node, ArchOpcode opcode)
void VisitDiv (InstructionSelector *selector, OpIndex node, ArchOpcode opcode)
void VisitMod (InstructionSelector *selector, OpIndex node, ArchOpcode opcode)
template<typename Displacement >
void EmitLea (InstructionSelector *selector, OpIndex result, OpIndex index, int scale, OpIndex base, Displacement displacement, DisplacementMode displacement_mode)
void VisitCompareWithMemoryOperand (InstructionSelector *selector, InstructionCode opcode, OpIndex left, InstructionOperand right, FlagsContinuation *cont)
void VisitCompare (InstructionSelector *selector, InstructionCode opcode, InstructionOperand left, InstructionOperand right, FlagsContinuation *cont)
void VisitCompare (InstructionSelector *selector, InstructionCode opcode, OpIndex left, OpIndex right, FlagsContinuation *cont, bool commutative)
MachineType MachineTypeForNarrow (InstructionSelector *selector, OpIndex node, OpIndex hint_node)
InstructionCode TryNarrowOpcodeSize (InstructionSelector *selector, InstructionCode opcode, OpIndex left, OpIndex right, FlagsContinuation *cont)
void VisitFloat32Compare (InstructionSelector *selector, OpIndex node, FlagsContinuation *cont)
void VisitFloat64Compare (InstructionSelector *selector, OpIndex node, FlagsContinuation *cont)
void VisitWordCompare (InstructionSelector *selector, OpIndex node, InstructionCode opcode, FlagsContinuation *cont)
void VisitWordCompare (InstructionSelector *selector, OpIndex node, FlagsContinuation *cont)
void VisitAtomicBinOp (InstructionSelector *selector, OpIndex node, ArchOpcode opcode, MachineRepresentation rep)
void VisitPairAtomicBinOp (InstructionSelector *selector, OpIndex node, ArchOpcode opcode)
Function Documentation
EmitLea()
template<typename Displacement >
void v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::EmitLea (InstructionSelector * selector, OpIndex result, OpIndex index, int scale, OpIndex base, Displacement displacement, DisplacementMode displacement_mode)
Definition at line 1344 of file instruction-selector-ia32.cc.
                                                 {
  IA32OperandGenerator g(selector);
  InstructionOperand inputs[4];
  size_t input_count = 0;
  AddressingMode mode =
      g.GenerateMemoryOperandInputs(index, scale, base, displacement,
                                    displacement_mode, inputs, &input_count);
  DCHECK_NE(0u, input_count);
  DCHECK_GE(arraysize(inputs), input_count);
  InstructionOperand outputs[1];
  outputs[0] = g.DefineAsRegister(result);
  InstructionCode opcode = AddressingModeField::encode(mode) | kIA32Lea;
  selector->Emit(opcode, 1, outputs, input_count, inputs);
}
References arraysize, DCHECK_GE, DCHECK_NE, v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::InstructionSelector::Emit(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::IA32OperandGenerator::GenerateMemoryOperandInputs(), v8::internal::index, v8::internal::compiler::turboshaft::detail::input_count(), mode(), and v8::base::internal::result.
GetLoadOpcode()
ArchOpcode v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::GetLoadOpcode (LoadRepresentation load_rep)
Definition at line 548 of file instruction-selector-ia32.cc.
                                                      {
  ArchOpcode opcode;
  switch (load_rep.representation()) {
    case MachineRepresentation::kFloat32:
      opcode = kIA32Movss;
      break;
    case MachineRepresentation::kFloat64:
      opcode = kIA32Movsd;
      break;
    case MachineRepresentation::kBit: // Fall through.
    case MachineRepresentation::kWord8:
      opcode = load_rep.IsSigned() ? kIA32Movsxbl : kIA32Movzxbl;
      break;
    case MachineRepresentation::kWord16:
      opcode = load_rep.IsSigned() ? kIA32Movsxwl : kIA32Movzxwl;
      break;
    case MachineRepresentation::kTaggedSigned: // Fall through.
    case MachineRepresentation::kTaggedPointer: // Fall through.
    case MachineRepresentation::kTagged: // Fall through.
    case MachineRepresentation::kWord32:
      opcode = kIA32Movl;
      break;
    case MachineRepresentation::kSimd128:
      opcode = kIA32Movdqu;
      break;
    case MachineRepresentation::kFloat16:
      UNIMPLEMENTED();
    case MachineRepresentation::kSimd256: // Fall through.
    case MachineRepresentation::kCompressedPointer: // Fall through.
    case MachineRepresentation::kCompressed: // Fall through.
    case MachineRepresentation::kProtectedPointer: // Fall through.
    case MachineRepresentation::kIndirectPointer: // Fall through.
    case MachineRepresentation::kSandboxedPointer: // Fall through.
    case MachineRepresentation::kWord64: // Fall through.
    case MachineRepresentation::kMapWord: // Fall through.
    case MachineRepresentation::kFloat16RawBits: // Fall through.
    case MachineRepresentation::kNone:
      UNREACHABLE();
  }
  return opcode;
}
References v8::internal::MachineType::IsSigned(), v8::internal::kBit, v8::internal::kCompressed, v8::internal::kCompressedPointer, v8::internal::kFloat16, v8::internal::kFloat16RawBits, v8::internal::kFloat32, v8::internal::kFloat64, v8::internal::kIndirectPointer, v8::internal::kMapWord, v8::internal::kNone, v8::internal::kProtectedPointer, v8::internal::kSandboxedPointer, v8::internal::kSimd128, v8::internal::kSimd256, v8::internal::kTagged, v8::internal::kTaggedPointer, v8::internal::kTaggedSigned, v8::internal::kWord16, v8::internal::kWord32, v8::internal::kWord64, v8::internal::kWord8, v8::internal::MachineType::representation(), v8::internal::compiler::UNIMPLEMENTED(), and v8::internal::UNREACHABLE().
GetSeqCstStoreOpcode()
ArchOpcode v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::GetSeqCstStoreOpcode (MachineRepresentation rep)
Definition at line 969 of file instruction-selector-ia32.cc.
                                                           {
  switch (rep) {
    case MachineRepresentation::kWord8:
      return kAtomicExchangeInt8;
    case MachineRepresentation::kWord16:
      return kAtomicExchangeInt16;
    case MachineRepresentation::kTaggedSigned: // Fall through.
    case MachineRepresentation::kTaggedPointer: // Fall through.
    case MachineRepresentation::kTagged: // Fall through.
    case MachineRepresentation::kWord32:
      return kAtomicExchangeWord32;
    default:
      UNREACHABLE();
  }
}
References v8::internal::kTagged, v8::internal::kTaggedPointer, v8::internal::kTaggedSigned, v8::internal::kWord16, v8::internal::kWord32, v8::internal::kWord8, and v8::internal::UNREACHABLE().
Referenced by VisitStoreCommon().
GetStoreOpcode()
ArchOpcode v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::GetStoreOpcode (MachineRepresentation rep)
Definition at line 935 of file instruction-selector-ia32.cc.
                                                     {
  switch (rep) {
    case MachineRepresentation::kFloat32:
      return kIA32Movss;
    case MachineRepresentation::kFloat64:
      return kIA32Movsd;
    case MachineRepresentation::kBit: // Fall through.
    case MachineRepresentation::kWord8:
      return kIA32Movb;
    case MachineRepresentation::kWord16:
      return kIA32Movw;
    case MachineRepresentation::kTaggedSigned: // Fall through.
    case MachineRepresentation::kTaggedPointer: // Fall through.
    case MachineRepresentation::kTagged: // Fall through.
    case MachineRepresentation::kWord32:
      return kIA32Movl;
    case MachineRepresentation::kSimd128:
      return kIA32Movdqu;
    case MachineRepresentation::kFloat16:
      UNIMPLEMENTED();
    case MachineRepresentation::kSimd256: // Fall through.
    case MachineRepresentation::kCompressedPointer: // Fall through.
    case MachineRepresentation::kCompressed: // Fall through.
    case MachineRepresentation::kProtectedPointer: // Fall through.
    case MachineRepresentation::kIndirectPointer: // Fall through.
    case MachineRepresentation::kSandboxedPointer: // Fall through.
    case MachineRepresentation::kWord64: // Fall through.
    case MachineRepresentation::kMapWord: // Fall through.
    case MachineRepresentation::kFloat16RawBits: // Fall through.
    case MachineRepresentation::kNone:
      UNREACHABLE();
  }
}
References v8::internal::kBit, v8::internal::kCompressed, v8::internal::kCompressedPointer, v8::internal::kFloat16, v8::internal::kFloat16RawBits, v8::internal::kFloat32, v8::internal::kFloat64, v8::internal::kIndirectPointer, v8::internal::kMapWord, v8::internal::kNone, v8::internal::kProtectedPointer, v8::internal::kSandboxedPointer, v8::internal::kSimd128, v8::internal::kSimd256, v8::internal::kTagged, v8::internal::kTaggedPointer, v8::internal::kTaggedSigned, v8::internal::kWord16, v8::internal::kWord32, v8::internal::kWord64, v8::internal::kWord8, v8::internal::compiler::UNIMPLEMENTED(), and v8::internal::UNREACHABLE().
Referenced by VisitStoreCommon().
MachineTypeForNarrow()
MachineType v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::MachineTypeForNarrow (InstructionSelector * selector, OpIndex node, OpIndex hint_node)
Definition at line 1935 of file instruction-selector-ia32.cc.
                                                    {
  if (selector->IsLoadOrLoadImmutable(hint_node)) {
    MachineType hint = selector->load_view(hint_node).loaded_rep();
    if (int64_t constant;
        selector->MatchSignedIntegralConstant(node, &constant)) {
      if (hint == MachineType::Int8()) {
        if (constant >= std::numeric_limits<int8_t>::min() &&
            constant <= std::numeric_limits<int8_t>::max()) {
          return hint;
        }
      } else if (hint == MachineType::Uint8()) {
        if (constant >= std::numeric_limits<uint8_t>::min() &&
            constant <= std::numeric_limits<uint8_t>::max()) {
          return hint;
        }
      } else if (hint == MachineType::Int16()) {
        if (constant >= std::numeric_limits<int16_t>::min() &&
            constant <= std::numeric_limits<int16_t>::max()) {
          return hint;
        }
      } else if (hint == MachineType::Uint16()) {
        if (constant >= std::numeric_limits<uint16_t>::min() &&
            constant <= std::numeric_limits<uint16_t>::max()) {
          return hint;
        }
      } else if (hint == MachineType::Int32()) {
        return hint;
      } else if (hint == MachineType::Uint32()) {
        if (constant >= 0) return hint;
      }
    }
  }
  return selector->IsLoadOrLoadImmutable(node)
             ? selector->load_view(node).loaded_rep()
             : MachineType::None();
}
References v8::internal::MachineType::Int16(), v8::internal::MachineType::Int32(), v8::internal::MachineType::Int8(), v8::internal::compiler::InstructionSelector::IsLoadOrLoadImmutable(), v8::internal::compiler::InstructionSelector::load_view(), v8::internal::compiler::InstructionSelector::LoadView::loaded_rep(), v8::internal::compiler::turboshaft::OperationMatcher::MatchSignedIntegralConstant(), v8::internal::MachineType::None(), v8::internal::MachineType::Uint16(), v8::internal::MachineType::Uint32(), and v8::internal::MachineType::Uint8().
Referenced by TryNarrowOpcodeSize().
MatchScaledIndex()
bool v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::MatchScaledIndex (InstructionSelector * selector, OpIndex node, OpIndex * index, int * scale, bool * power_of_two_plus_one)
Definition at line 84 of file instruction-selector-ia32.cc.
                                                                               {
  DCHECK_NOT_NULL(index);
  DCHECK_NOT_NULL(scale);
  auto MatchScaleConstant = [](const Operation& op, int& scale,
                               bool* plus_one) {
    const ConstantOp* constant = op.TryCast<ConstantOp>();
    if (constant == nullptr) return false;
    if (constant->kind != ConstantOp::Kind::kWord32) return false;
    uint64_t value = constant->integral();
    if (plus_one) *plus_one = false;
    if (value == 1) return (scale = 0), true;
    if (value == 2) return (scale = 1), true;
    if (value == 4) return (scale = 2), true;
    if (value == 8) return (scale = 3), true;
    if (plus_one == nullptr) return false;
    *plus_one = true;
    if (value == 3) return (scale = 1), true;
    if (value == 5) return (scale = 2), true;
    if (value == 9) return (scale = 3), true;
    return false;
  };
  const Operation& op = selector->Get(node);
  if (const WordBinopOp* binop = op.TryCast<WordBinopOp>()) {
    if (binop->kind != WordBinopOp::Kind::kMul) return false;
    if (MatchScaleConstant(selector->Get(binop->right()), *scale,
                           power_of_two_plus_one)) {
      *index = binop->left();
      return true;
    }
    if (MatchScaleConstant(selector->Get(binop->left()), *scale,
                           power_of_two_plus_one)) {
      *index = binop->right();
      return true;
    }
    return false;
  } else if (const ShiftOp* shift = op.TryCast<ShiftOp>()) {
    if (shift->kind != ShiftOp::Kind::kShiftLeft) return false;
    int32_t scale_value;
    if (selector->MatchIntegralWord32Constant(shift->right(), &scale_value)) {
      if (scale_value < 0 || scale_value > 3) return false;
      *index = shift->left();
      *scale = static_cast<int>(scale_value);
      if (power_of_two_plus_one) *power_of_two_plus_one = false;
      return true;
    }
  }
  return false;
}
References DCHECK_NOT_NULL, v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::index, v8::internal::compiler::turboshaft::ConstantOp::integral(), v8::internal::compiler::turboshaft::ConstantOp::kind, v8::internal::compiler::turboshaft::WordBinopOp::kMul, v8::internal::compiler::turboshaft::ConstantOp::kWord32, v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralWord32Constant(), v8::internal::compiler::turboshaft::Operation::TryCast(), and v8::internal::value.
TryMatchBaseWithScaledIndexAndDisplacement()
std::optional<BaseWithScaledIndexAndDisplacementMatch> v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::TryMatchBaseWithScaledIndexAndDisplacement (InstructionSelector * selector, OpIndex node)
Definition at line 260 of file instruction-selector-ia32.cc.
                                                         {
  // The BaseWithIndexAndDisplacementMatcher canonicalizes the order of
  // displacements and scale factors that are used as inputs, so instead of
  // enumerating all possible patterns by brute force, checking for node
  // clusters using the following templates in the following order suffices
  // to find all of the interesting cases (S = index * scale, B = base
  // input, D = displacement input):
  //
  // (S + (B + D))
  // (S + (B + B))
  // (S + D)
  // (S + B)
  // ((S + D) + B)
  // ((S + B) + D)
  // ((B + D) + B)
  // ((B + B) + D)
  // (B + D)
  // (B + B)
  BaseWithScaledIndexAndDisplacementMatch result;
  result.displacement_mode = kPositiveDisplacement;
  const Operation& op = selector->Get(node);
  if (const LoadOp* load = op.TryCast<LoadOp>()) {
    result.base = load->base();
    result.index = load->index().value_or_invalid();
    result.scale = load->element_size_log2;
    result.displacement = load->offset;
    if (load->kind.tagged_base) result.displacement -= kHeapObjectTag;
    return result;
  } else if (const StoreOp* store = op.TryCast<StoreOp>()) {
    result.base = store->base();
    result.index = store->index().value_or_invalid();
    result.scale = store->element_size_log2;
    result.displacement = store->offset;
    if (store->kind.tagged_base) result.displacement -= kHeapObjectTag;
    return result;
  } else if (op.Is<WordBinopOp>()) {
    // Nothing to do here, fall into the case below.
#ifdef V8_ENABLE_WEBASSEMBLY
  } else if (const Simd128LaneMemoryOp* lane_op =
                 op.TryCast<Simd128LaneMemoryOp>()) {
    result.base = lane_op->base();
    result.index = lane_op->index();
    result.scale = 0;
    result.displacement = 0;
    if (lane_op->kind.tagged_base) result.displacement -= kHeapObjectTag;
    return result;
  } else if (const Simd128LoadTransformOp* load_transform =
                 op.TryCast<Simd128LoadTransformOp>()) {
    result.base = load_transform->base();
    result.index = load_transform->index();
    DCHECK_EQ(load_transform->offset, 0);
    result.scale = 0;
    result.displacement = 0;
    DCHECK(!load_transform->load_kind.tagged_base);
    return result;
#endif // V8_ENABLE_WEBASSEMBLY
  } else {
    return std::nullopt;
  }
  const WordBinopOp& binop = op.Cast<WordBinopOp>();
  OpIndex left = binop.left();
  OpIndex right = binop.right();
  return TryMatchBaseWithScaledIndexAndDisplacementForWordBinop(selector, left,
                                                                right);
}
References v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::kHeapObjectTag, v8::internal::compiler::kPositiveDisplacement, v8::internal::compiler::turboshaft::WordBinopOp::left(), v8::internal::compiler::turboshaft::OpIndex::offset(), v8::base::internal::result, v8::internal::compiler::turboshaft::WordBinopOp::right(), store(), v8::internal::compiler::turboshaft::Operation::TryCast(), and TryMatchBaseWithScaledIndexAndDisplacementForWordBinop().
Referenced by v8::internal::compiler::IA32OperandGenerator::GetEffectiveAddressMemoryOperand().
TryMatchBaseWithScaledIndexAndDisplacementForWordBinop()
std::optional<BaseWithScaledIndexAndDisplacementMatch> v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::TryMatchBaseWithScaledIndexAndDisplacementForWordBinop (InstructionSelector * selector, OpIndex left, OpIndex right)
Definition at line 152 of file instruction-selector-ia32.cc.
                                                                {
  BaseWithScaledIndexAndDisplacementMatch result;
  result.displacement_mode = kPositiveDisplacement;
  auto OwnedByAddressingOperand = [](OpIndex) {
    // TODO(nicohartmann@): Consider providing this. For now we just allow
    // everything to be covered regardless of other uses.
    return true;
  };
  // Check (S + ...)
  if (MatchScaledIndex(selector, left, &result.index, &result.scale, nullptr) &&
      OwnedByAddressingOperand(left)) {
    result.displacement_mode = kPositiveDisplacement;
    // Check (S + (... binop ...))
    if (const WordBinopOp* right_binop =
            selector->Get(right).TryCast<WordBinopOp>()) {
      // Check (S + (B - D))
      if (right_binop->kind == WordBinopOp::Kind::kSub &&
          OwnedByAddressingOperand(right)) {
        if (!selector->MatchIntegralWord32Constant(right_binop->right(),
                                                   &result.displacement)) {
          return std::nullopt;
        }
        result.base = right_binop->left();
        result.displacement_mode = kNegativeDisplacement;
        return result;
      }
      // Check (S + (... + ...))
      if (right_binop->kind == WordBinopOp::Kind::kAdd &&
          OwnedByAddressingOperand(right)) {
        if (selector->MatchIntegralWord32Constant(right_binop->right(),
                                                  &result.displacement)) {
          // (S + (B + D))
          result.base = right_binop->left();
        } else if (selector->MatchIntegralWord32Constant(
                       right_binop->left(), &result.displacement)) {
          // (S + (D + B))
          result.base = right_binop->right();
        } else {
          // Treat it as (S + B)
          result.base = right;
          result.displacement = 0;
        }
        return result;
      }
    }
    // Check (S + D)
    if (selector->MatchIntegralWord32Constant(right, &result.displacement)) {
      result.base = OpIndex{};
      return result;
    }
    // Treat it as (S + B)
    result.base = right;
    result.displacement = 0;
    return result;
  }
  // Check ((... + ...) + ...)
  if (const WordBinopOp* left_add = selector->Get(left).TryCast<WordBinopOp>();
      left_add && left_add->kind == WordBinopOp::Kind::kAdd &&
      OwnedByAddressingOperand(left)) {
    // Check ((S + ...) + ...)
    if (MatchScaledIndex(selector, left_add->left(), &result.index,
                         &result.scale, nullptr)) {
      result.displacement_mode = kPositiveDisplacement;
      // Check ((S + D) + B)
      if (selector->MatchIntegralWord32Constant(left_add->right(),
                                                &result.displacement)) {
        result.base = right;
        return result;
      }
      // Check ((S + B) + D)
      if (selector->MatchIntegralWord32Constant(right, &result.displacement)) {
        result.base = left_add->right();
        return result;
      }
      // Treat it as (B + B) and use index as right B.
      result.base = left;
      result.index = right;
      result.scale = 0;
      DCHECK_EQ(result.displacement, 0);
      return result;
    }
  }
  DCHECK_EQ(result.index, OpIndex{});
  DCHECK_EQ(result.scale, 0);
  result.displacement_mode = kPositiveDisplacement;
  // Check (B + D)
  if (selector->MatchIntegralWord32Constant(right, &result.displacement)) {
    result.base = left;
    return result;
  }
  // Treat as (B + B) and use index as left B.
  result.index = left;
  result.base = right;
  return result;
}
References DCHECK_EQ, v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::WordBinopOp::kAdd, v8::internal::compiler::turboshaft::WordBinopOp::kind, v8::internal::compiler::kNegativeDisplacement, v8::internal::compiler::kPositiveDisplacement, v8::internal::compiler::turboshaft::WordBinopOp::kSub, v8::internal::compiler::turboshaft::OperationMatcher::left, v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralWord32Constant(), v8::internal::compiler::MatchScaledIndex(), v8::internal::compiler::turboshaft::OpIndex, v8::base::internal::result, and v8::internal::compiler::turboshaft::Operation::TryCast().
Referenced by TryMatchBaseWithScaledIndexAndDisplacement().
TryMatchScaledIndex()
std::optional<ScaledIndexMatch> v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::TryMatchScaledIndex (InstructionSelector * selector, OpIndex node, bool allow_power_of_two_plus_one)
Definition at line 137 of file instruction-selector-ia32.cc.
                                      {
  ScaledIndexMatch match;
  bool plus_one = false;
  if (MatchScaledIndex(selector, node, &match.index, &match.scale,
                       allow_power_of_two_plus_one ? &plus_one : nullptr)) {
    match.base = plus_one ? match.index : OpIndex{};
    return match;
  }
  return std::nullopt;
}
References v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::ScaledIndexMatch::base, v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::ScaledIndexMatch::index, v8::internal::compiler::MatchScaledIndex(), and v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::ScaledIndexMatch::scale.
TryNarrowOpcodeSize()
InstructionCode v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::TryNarrowOpcodeSize (InstructionSelector * selector, InstructionCode opcode, OpIndex left, OpIndex right, FlagsContinuation * cont)
Definition at line 1975 of file instruction-selector-ia32.cc.
                                                                            {
  // TODO(epertoso): we can probably get some size information out of phi nodes.
  // If the load representations don't match, both operands will be
  // zero/sign-extended to 32bit.
  MachineType left_type = MachineTypeForNarrow(selector, left, right);
  MachineType right_type = MachineTypeForNarrow(selector, right, left);
  if (left_type == right_type) {
    switch (left_type.representation()) {
      case MachineRepresentation::kBit:
      case MachineRepresentation::kWord8: {
        if (opcode == kIA32Test) return kIA32Test8;
        if (opcode == kIA32Cmp) {
          if (left_type.semantic() == MachineSemantic::kUint32) {
            cont->OverwriteUnsignedIfSigned();
          } else {
            CHECK_EQ(MachineSemantic::kInt32, left_type.semantic());
          }
          return kIA32Cmp8;
        }
        break;
      }
      case MachineRepresentation::kWord16:
        if (opcode == kIA32Test) return kIA32Test16;
        if (opcode == kIA32Cmp) {
          if (left_type.semantic() == MachineSemantic::kUint32) {
            cont->OverwriteUnsignedIfSigned();
          } else {
            CHECK_EQ(MachineSemantic::kInt32, left_type.semantic());
          }
          return kIA32Cmp16;
        }
        break;
      default:
        break;
    }
  }
  return opcode;
}
References CHECK_EQ, v8::internal::kBit, v8::internal::kInt32, v8::internal::kUint32, v8::internal::kWord16, v8::internal::kWord8, MachineTypeForNarrow(), v8::internal::compiler::FlagsContinuation::OverwriteUnsignedIfSigned(), v8::internal::MachineType::representation(), and v8::internal::MachineType::semantic().
Referenced by VisitWordCompare().
VisitAtomicBinOp()
void v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitAtomicBinOp (InstructionSelector * selector, OpIndex node, ArchOpcode opcode, MachineRepresentation rep)
Definition at line 2081 of file instruction-selector-ia32.cc.
                                                                    {
  AddressingMode addressing_mode;
  IA32OperandGenerator g(selector);
  const AtomicRMWOp& op = selector->Cast<AtomicRMWOp>(node);
  InstructionOperand inputs[] = {
      g.UseUniqueRegister(op.value()), g.UseUniqueRegister(op.base()),
      g.GetEffectiveIndexOperand(op.index(), &addressing_mode)};
  InstructionOperand outputs[] = {g.DefineAsFixed(node, eax)};
  InstructionOperand temp[] = {(rep == MachineRepresentation::kWord8)
                                   ? g.UseByteRegister(node)
                                   : g.TempRegister()};
  InstructionCode code = opcode | AddressingModeField::encode(addressing_mode);
  selector->Emit(code, arraysize(outputs), outputs, arraysize(inputs), inputs,
                 arraysize(temp), temp);
}
References arraysize, v8::internal::compiler::turboshaft::AtomicRMWOp::base(), v8::internal::compiler::turboshaft::OperationMatcher::Cast(), code, v8::internal::compiler::OperandGenerator::DefineAsFixed(), v8::internal::compiler::InstructionSelector::Emit(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::IA32OperandGenerator::GetEffectiveIndexOperand(), v8::internal::compiler::turboshaft::AtomicRMWOp::index(), v8::internal::kWord8, v8::internal::compiler::OperandGenerator::TempRegister(), v8::internal::compiler::IA32OperandGenerator::UseByteRegister(), v8::internal::compiler::OperandGenerator::UseUniqueRegister(), and v8::internal::compiler::turboshaft::AtomicRMWOp::value().
VisitAtomicExchange()
void v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitAtomicExchange (InstructionSelector * selector, OpIndex node, ArchOpcode opcode, MachineRepresentation rep)
Definition at line 985 of file instruction-selector-ia32.cc.
                                                                       {
  IA32OperandGenerator g(selector);
  const AtomicRMWOp& op = selector->Cast<AtomicRMWOp>(node);
  AddressingMode addressing_mode;
  InstructionOperand value_operand = (rep == MachineRepresentation::kWord8)
                                         ? g.UseFixed(op.value(), edx)
                                         : g.UseUniqueRegister(op.value());
  InstructionOperand inputs[] = {
      value_operand, g.UseUniqueRegister(op.base()),
      g.GetEffectiveIndexOperand(op.index(), &addressing_mode)};
  base::SmallVector<InstructionOperand, 2> temps;
  if (opcode == kAtomicExchangeWithWriteBarrier) {
    temps.push_back(g.TempRegister());
    temps.push_back(g.TempRegister());
  }
  InstructionOperand outputs[] = {
      (rep == MachineRepresentation::kWord8)
          // Using DefineSameAsFirst requires the register to be unallocated.
          ? g.DefineAsFixed(node, edx)
          : g.DefineSameAsFirst(node)};
  InstructionCode code = opcode | AddressingModeField::encode(addressing_mode);
  selector->Emit(code, 1, outputs, arraysize(inputs), inputs, temps.size(),
                 temps.data());
}
References arraysize, v8::internal::compiler::turboshaft::AtomicRMWOp::base(), v8::internal::compiler::turboshaft::OperationMatcher::Cast(), code, v8::base::SmallVector< T, kSize, Allocator >::data(), v8::internal::compiler::OperandGenerator::DefineAsFixed(), v8::internal::compiler::OperandGenerator::DefineSameAsFirst(), v8::internal::compiler::InstructionSelector::Emit(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::IA32OperandGenerator::GetEffectiveIndexOperand(), v8::internal::compiler::turboshaft::AtomicRMWOp::index(), v8::internal::kWord8, v8::base::SmallVector< T, kSize, Allocator >::push_back(), v8::base::SmallVector< T, kSize, Allocator >::size(), v8::internal::compiler::OperandGenerator::TempRegister(), v8::internal::compiler::OperandGenerator::UseFixed(), v8::internal::compiler::OperandGenerator::UseUniqueRegister(), and v8::internal::compiler::turboshaft::AtomicRMWOp::value().
VisitBinop() [1/2]
void v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitBinop (InstructionSelector * selector, OpIndex node, InstructionCode opcode)
Definition at line 1220 of file instruction-selector-ia32.cc.
                                        {
  FlagsContinuation cont;
  VisitBinop(selector, node, opcode, &cont);
}
References v8::internal::compiler::VisitBinop().
VisitBinop() [2/2]
void v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitBinop (InstructionSelector * selector, OpIndex node, InstructionCode opcode, FlagsContinuation * cont)
Definition at line 1166 of file instruction-selector-ia32.cc.
                                                                 {
  IA32OperandGenerator g(selector);
  auto [left, right] = selector->Inputs<2>(node);
  InstructionOperand inputs[6];
  size_t input_count = 0;
  InstructionOperand outputs[1];
  size_t output_count = 0;
  // TODO(turbofan): match complex addressing modes.
  if (left == right) {
    // If both inputs refer to the same operand, enforce allocating a register
    // for both of them to ensure that we don't end up generating code like
    // this:
    //
    // mov eax, [ebp-0x10]
    // add eax, [ebp-0x10]
    // jo label
    InstructionOperand const input = g.UseRegister(left);
    inputs[input_count++] = input;
    inputs[input_count++] = input;
  } else if (g.CanBeImmediate(right)) {
    inputs[input_count++] = g.UseRegister(left);
    inputs[input_count++] = g.UseImmediate(right);
  } else {
    int effect_level = selector->GetEffectLevel(node, cont);
    if (selector->IsCommutative(node) && g.CanBeBetterLeftOperand(right) &&
        (!g.CanBeBetterLeftOperand(left) ||
         !g.CanBeMemoryOperand(opcode, node, right, effect_level))) {
      std::swap(left, right);
    }
    if (g.CanBeMemoryOperand(opcode, node, right, effect_level)) {
      inputs[input_count++] = g.UseRegister(left);
      AddressingMode addressing_mode =
          g.GetEffectiveAddressMemoryOperand(right, inputs, &input_count);
      opcode |= AddressingModeField::encode(addressing_mode);
    } else {
      inputs[input_count++] = g.UseRegister(left);
      inputs[input_count++] = g.Use(right);
    }
  }
  outputs[output_count++] = g.DefineSameAsFirst(node);
  DCHECK_NE(0u, input_count);
  DCHECK_EQ(1u, output_count);
  DCHECK_GE(arraysize(inputs), input_count);
  DCHECK_GE(arraysize(outputs), output_count);
  selector->EmitWithContinuation(opcode, output_count, outputs, input_count,
                                 inputs, cont);
}
References arraysize, v8::internal::compiler::IA32OperandGenerator::CanBeBetterLeftOperand(), v8::internal::compiler::IA32OperandGenerator::CanBeImmediate(), v8::internal::compiler::IA32OperandGenerator::CanBeMemoryOperand(), DCHECK_EQ, DCHECK_GE, DCHECK_NE, v8::internal::compiler::OperandGenerator::DefineSameAsFirst(), v8::internal::compiler::InstructionSelector::EmitWithContinuation(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::IA32OperandGenerator::GetEffectiveAddressMemoryOperand(), v8::internal::compiler::InstructionSelector::GetEffectLevel(), v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::InstructionSelector::Inputs(), v8::internal::compiler::InstructionSelector::IsCommutative(), v8::internal::compiler::OperandGenerator::Use(), v8::internal::compiler::OperandGenerator::UseImmediate(), and v8::internal::compiler::OperandGenerator::UseRegister().
VisitCompare() [1/2]
void v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitCompare (InstructionSelector * selector, InstructionCode opcode, InstructionOperand left, InstructionOperand right, FlagsContinuation * cont)
Definition at line 1918 of file instruction-selector-ia32.cc.
                                           {
  selector->EmitWithContinuation(opcode, left, right, cont);
}
References v8::internal::compiler::InstructionSelector::EmitWithContinuation().
VisitCompare() [2/2]
void v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitCompare (InstructionSelector * selector, InstructionCode opcode, OpIndex left, OpIndex right, FlagsContinuation * cont, bool commutative)
Definition at line 1925 of file instruction-selector-ia32.cc.
                                    {
  IA32OperandGenerator g(selector);
  if (commutative && g.CanBeBetterLeftOperand(right)) {
    std::swap(left, right);
  }
  VisitCompare(selector, opcode, g.UseRegister(left), g.Use(right), cont);
}
References v8::internal::compiler::IA32OperandGenerator::CanBeBetterLeftOperand(), v8::internal::compiler::OperandGenerator::Use(), v8::internal::compiler::OperandGenerator::UseRegister(), and v8::internal::compiler::VisitCompare().
VisitCompareWithMemoryOperand()
void v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitCompareWithMemoryOperand (InstructionSelector * selector, InstructionCode opcode, OpIndex left, InstructionOperand right, FlagsContinuation * cont)
Definition at line 1901 of file instruction-selector-ia32.cc.
                                                            {
  DCHECK(selector->IsLoadOrLoadImmutable(left));
  IA32OperandGenerator g(selector);
  size_t input_count = 0;
  InstructionOperand inputs[4];
  AddressingMode addressing_mode =
      g.GetEffectiveAddressMemoryOperand(left, inputs, &input_count);
  opcode |= AddressingModeField::encode(addressing_mode);
  inputs[input_count++] = right;
  selector->EmitWithContinuation(opcode, 0, nullptr, input_count, inputs, cont);
}
References v8::internal::DCHECK(), v8::internal::compiler::InstructionSelector::EmitWithContinuation(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::IA32OperandGenerator::GetEffectiveAddressMemoryOperand(), v8::internal::compiler::turboshaft::detail::input_count(), and v8::internal::compiler::InstructionSelector::IsLoadOrLoadImmutable().
Referenced by VisitWordCompare().
VisitDiv()
void v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitDiv (InstructionSelector * selector, OpIndex node, ArchOpcode opcode)
Definition at line 1326 of file instruction-selector-ia32.cc.
                                                                              {
  IA32OperandGenerator g(selector);
  const WordBinopOp& op = selector->Cast<WordBinopOp>(node);
  InstructionOperand temps[] = {g.TempRegister(edx)};
  selector->Emit(opcode, g.DefineAsFixed(node, eax), g.UseFixed(op.left(), eax),
                 g.UseUnique(op.right()), arraysize(temps), temps);
}
References arraysize, v8::internal::compiler::turboshaft::OperationMatcher::Cast(), v8::internal::compiler::OperandGenerator::DefineAsFixed(), v8::internal::compiler::InstructionSelector::Emit(), v8::internal::compiler::turboshaft::WordBinopOp::left(), v8::internal::compiler::turboshaft::WordBinopOp::right(), v8::internal::compiler::OperandGenerator::TempRegister(), v8::internal::compiler::OperandGenerator::UseFixed(), and v8::internal::compiler::OperandGenerator::UseUnique().
VisitFloat32Compare()
void v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitFloat32Compare (InstructionSelector * selector, OpIndex node, FlagsContinuation * cont)
Definition at line 2017 of file instruction-selector-ia32.cc.
                                                  {
  auto [left, right] = selector->Inputs<ComparisonOp>(node);
  VisitCompare(selector, kIA32Float32Cmp, right, left, cont, false);
}
References v8::internal::compiler::InstructionSelector::Inputs(), and v8::internal::compiler::VisitCompare().
VisitFloat64Compare()
void v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitFloat64Compare (InstructionSelector * selector, OpIndex node, FlagsContinuation * cont)
Definition at line 2024 of file instruction-selector-ia32.cc.
                                                  {
  auto [left, right] = selector->Inputs<ComparisonOp>(node);
  VisitCompare(selector, kIA32Float64Cmp, right, left, cont, false);
}
References v8::internal::compiler::InstructionSelector::Inputs(), and v8::internal::compiler::VisitCompare().
VisitFloatUnop()
void v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitFloatUnop (InstructionSelector * selector, OpIndex node, OpIndex input, ArchOpcode opcode)
Definition at line 640 of file instruction-selector-ia32.cc.
                                       {
  IA32OperandGenerator g(selector);
  InstructionOperand temps[] = {g.TempRegister()};
  // No need for unique because inputs are float but temp is general.
  if (selector->IsSupported(AVX)) {
    selector->Emit(opcode, g.DefineAsRegister(node), g.UseRegister(input),
                   arraysize(temps), temps);
  } else {
    selector->Emit(opcode, g.DefineSameAsFirst(node), g.UseRegister(input),
                   arraysize(temps), temps);
  }
}
References arraysize, v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::OperandGenerator::DefineSameAsFirst(), v8::internal::compiler::InstructionSelector::Emit(), v8::internal::compiler::InstructionSelector::IsSupported(), v8::internal::compiler::OperandGenerator::TempRegister(), and v8::internal::compiler::OperandGenerator::UseRegister().
VisitMod()
void v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitMod (InstructionSelector * selector, OpIndex node, ArchOpcode opcode)
Definition at line 1334 of file instruction-selector-ia32.cc.
                                                                              {
  IA32OperandGenerator g(selector);
  const WordBinopOp& op = selector->Cast<WordBinopOp>(node);
  InstructionOperand temps[] = {g.TempRegister(eax)};
  selector->Emit(opcode, g.DefineAsFixed(node, edx), g.UseFixed(op.left(), eax),
                 g.UseUnique(op.right()), arraysize(temps), temps);
}
References arraysize, v8::internal::compiler::turboshaft::OperationMatcher::Cast(), v8::internal::compiler::OperandGenerator::DefineAsFixed(), v8::internal::compiler::InstructionSelector::Emit(), v8::internal::compiler::turboshaft::WordBinopOp::left(), v8::internal::compiler::turboshaft::WordBinopOp::right(), v8::internal::compiler::OperandGenerator::TempRegister(), v8::internal::compiler::OperandGenerator::UseFixed(), and v8::internal::compiler::OperandGenerator::UseUnique().
VisitMulHigh()
void v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitMulHigh (InstructionSelector * selector, OpIndex node, ArchOpcode opcode)
Definition at line 1317 of file instruction-selector-ia32.cc.
                                     {
  IA32OperandGenerator g(selector);
  const WordBinopOp& op = selector->Cast<WordBinopOp>(node);
  InstructionOperand temps[] = {g.TempRegister(eax)};
  selector->Emit(opcode, g.DefineAsFixed(node, edx), g.UseFixed(op.left(), eax),
                 g.UseUniqueRegister(op.right()), arraysize(temps), temps);
}
References arraysize, v8::internal::compiler::turboshaft::OperationMatcher::Cast(), v8::internal::compiler::OperandGenerator::DefineAsFixed(), v8::internal::compiler::InstructionSelector::Emit(), v8::internal::compiler::turboshaft::WordBinopOp::left(), v8::internal::compiler::turboshaft::WordBinopOp::right(), v8::internal::compiler::OperandGenerator::TempRegister(), v8::internal::compiler::OperandGenerator::UseFixed(), and v8::internal::compiler::OperandGenerator::UseUniqueRegister().
VisitPairAtomicBinOp()
void v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitPairAtomicBinOp (InstructionSelector * selector, OpIndex node, ArchOpcode opcode)
Definition at line 2098 of file instruction-selector-ia32.cc.
                                             {
  IA32OperandGenerator g(selector);
  const AtomicWord32PairOp& op = selector->Cast<AtomicWord32PairOp>(node);
  OpIndex index = op.index().value();
  // For Word64 operations, the value input is split into the a high node,
  // and a low node in the int64-lowering phase.
  OpIndex value_low = op.value_low().value();
  OpIndex value_high = op.value_high().value();
  // Wasm lives in 32-bit address space, so we do not need to worry about
  // base/index lowering. This will need to be fixed for Wasm64.
  AddressingMode addressing_mode;
  InstructionOperand inputs[] = {
      g.UseUniqueRegisterOrSlotOrConstant(value_low),
      g.UseFixed(value_high, ecx), g.UseUniqueRegister(op.base()),
      g.GetEffectiveIndexOperand(index, &addressing_mode)};
  InstructionCode code = opcode | AddressingModeField::encode(addressing_mode);
  OptionalOpIndex projection0 = selector->FindProjection(node, 0);
  OptionalOpIndex projection1 = selector->FindProjection(node, 1);
  InstructionOperand outputs[2];
  size_t output_count = 0;
  InstructionOperand temps[2];
  size_t temp_count = 0;
  if (projection0.valid()) {
    outputs[output_count++] = g.DefineAsFixed(projection0.value(), eax);
  } else {
    temps[temp_count++] = g.TempRegister(eax);
  }
  if (projection1.valid()) {
    outputs[output_count++] = g.DefineAsFixed(projection1.value(), edx);
  } else {
    temps[temp_count++] = g.TempRegister(edx);
  }
  selector->Emit(code, output_count, outputs, arraysize(inputs), inputs,
                 temp_count, temps);
}
References arraysize, v8::internal::compiler::turboshaft::AtomicWord32PairOp::base(), v8::internal::compiler::turboshaft::OperationMatcher::Cast(), code, v8::internal::compiler::OperandGenerator::DefineAsFixed(), v8::internal::compiler::InstructionSelector::Emit(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::InstructionSelector::FindProjection(), v8::internal::compiler::IA32OperandGenerator::GetEffectiveIndexOperand(), v8::internal::compiler::turboshaft::AtomicWord32PairOp::index(), v8::internal::index, v8::internal::compiler::OperandGenerator::TempRegister(), v8::internal::compiler::OperandGenerator::UseFixed(), v8::internal::compiler::OperandGenerator::UseUniqueRegister(), v8::internal::compiler::OperandGenerator::UseUniqueRegisterOrSlotOrConstant(), v8::internal::compiler::turboshaft::OptionalOpIndex::valid(), v8::internal::compiler::turboshaft::OptionalOpIndex::value(), v8::internal::compiler::turboshaft::AtomicWord32PairOp::value_high(), and v8::internal::compiler::turboshaft::AtomicWord32PairOp::value_low().
VisitRO()
void v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitRO (InstructionSelector * selector, OpIndex node, ArchOpcode opcode)
Definition at line 590 of file instruction-selector-ia32.cc.
                                                                             {
  IA32OperandGenerator g(selector);
  OpIndex input = selector->Get(node).input(0);
  // We have to use a byte register as input to movsxb.
  InstructionOperand input_op =
      opcode == kIA32Movsxbl ? g.UseFixed(input, eax) : g.Use(input);
  selector->Emit(opcode, g.DefineAsRegister(node), input_op);
}
References v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::InstructionSelector::Emit(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::OperandGenerator::Use(), and v8::internal::compiler::OperandGenerator::UseFixed().
VisitROWithTemp()
void v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitROWithTemp (InstructionSelector * selector, OpIndex node, ArchOpcode opcode)
Definition at line 599 of file instruction-selector-ia32.cc.
                                        {
  IA32OperandGenerator g(selector);
  OpIndex input = selector->Get(node).input(0);
  InstructionOperand temps[] = {g.TempRegister()};
  selector->Emit(opcode, g.DefineAsRegister(node), g.Use(input),
                 arraysize(temps), temps);
}
References arraysize, v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::InstructionSelector::Emit(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::OperandGenerator::TempRegister(), and v8::internal::compiler::OperandGenerator::Use().
VisitROWithTempSimd()
void v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitROWithTempSimd (InstructionSelector * selector, OpIndex node, ArchOpcode opcode)
Definition at line 608 of file instruction-selector-ia32.cc.
                                            {
  IA32OperandGenerator g(selector);
  OpIndex input = selector->Get(node).input(0);
  InstructionOperand temps[] = {g.TempSimd128Register()};
  selector->Emit(opcode, g.DefineAsRegister(node), g.UseUniqueRegister(input),
                 arraysize(temps), temps);
}
References arraysize, v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::InstructionSelector::Emit(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::OperandGenerator::TempSimd128Register(), and v8::internal::compiler::OperandGenerator::UseUniqueRegister().
VisitRR()
void v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitRR (InstructionSelector * selector, OpIndex node, InstructionCode opcode)
Definition at line 617 of file instruction-selector-ia32.cc.
                                     {
  IA32OperandGenerator g(selector);
  OpIndex input = selector->Get(node).input(0);
  selector->Emit(opcode, g.DefineAsRegister(node), g.UseRegister(input));
}
References v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::InstructionSelector::Emit(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::input(), and v8::internal::compiler::OperandGenerator::UseRegister().
VisitRROFloat()
void v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitRROFloat (InstructionSelector * selector, OpIndex node, ArchOpcode opcode)
Definition at line 624 of file instruction-selector-ia32.cc.
                                      {
  IA32OperandGenerator g(selector);
  const Operation& op = selector->Get(node);
  InstructionOperand operand0 = g.UseRegister(op.input(0));
  InstructionOperand operand1 = g.Use(op.input(1));
  if (selector->IsSupported(AVX)) {
    selector->Emit(opcode, g.DefineAsRegister(node), operand0, operand1);
  } else {
    selector->Emit(opcode, g.DefineSameAsFirst(node), operand0, operand1);
  }
}
References v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::OperandGenerator::DefineSameAsFirst(), v8::internal::compiler::InstructionSelector::Emit(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::InstructionSelector::IsSupported(), v8::internal::compiler::OperandGenerator::Use(), and v8::internal::compiler::OperandGenerator::UseRegister().
VisitStoreCommon()
void v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitStoreCommon (InstructionSelector * selector, const InstructionSelector::StoreView & store)
Definition at line 1011 of file instruction-selector-ia32.cc.
                                                                 {
  IA32OperandGenerator g(selector);
  OpIndex base = store.base();
  OptionalOpIndex index = store.index();
  OpIndex value = store.value();
  int32_t displacement = store.displacement();
  uint8_t element_size_log2 = store.element_size_log2();
  std::optional<AtomicMemoryOrder> atomic_order = store.memory_order();
  StoreRepresentation store_rep = store.stored_rep();
  WriteBarrierKind write_barrier_kind = store_rep.write_barrier_kind();
  MachineRepresentation rep = store_rep.representation();
  const bool is_seqcst =
      atomic_order && *atomic_order == AtomicMemoryOrder::kSeqCst;
  if (v8_flags.enable_unconditional_write_barriers && CanBeTaggedPointer(rep)) {
    write_barrier_kind = kFullWriteBarrier;
  }
  if (write_barrier_kind != kNoWriteBarrier &&
      !v8_flags.disable_write_barriers) {
    DCHECK(CanBeTaggedPointer(rep));
    AddressingMode addressing_mode;
    InstructionOperand inputs[4];
    size_t input_count = 0;
    addressing_mode = g.GenerateMemoryOperandInputs(
        index, element_size_log2, base, displacement,
        DisplacementMode::kPositiveDisplacement, inputs, &input_count,
        IA32OperandGenerator::RegisterMode::kUniqueRegister);
    DCHECK_LT(input_count, 4);
    inputs[input_count++] = g.UseUniqueRegister(value);
    RecordWriteMode record_write_mode =
        WriteBarrierKindToRecordWriteMode(write_barrier_kind);
    InstructionOperand temps[] = {g.TempRegister()};
    size_t const temp_count = arraysize(temps);
    InstructionCode code = is_seqcst ? kArchAtomicStoreWithWriteBarrier
                                     : kArchStoreWithWriteBarrier;
    code |= AddressingModeField::encode(addressing_mode);
    code |= RecordWriteModeField::encode(record_write_mode);
    selector->Emit(code, 0, nullptr, input_count, inputs, temp_count, temps);
  } else {
    InstructionOperand inputs[4];
    size_t input_count = 0;
    // To inform the register allocator that xchg clobbered its input.
    InstructionOperand outputs[1];
    size_t output_count = 0;
    ArchOpcode opcode;
    AddressingMode addressing_mode;
    if (is_seqcst) {
      // SeqCst stores emit XCHG instead of MOV, so encode the inputs as we
      // would for XCHG. XCHG can't encode the value as an immediate and has
      // fewer addressing modes available.
      if (rep == MachineRepresentation::kWord8 ||
          rep == MachineRepresentation::kBit) {
        inputs[input_count++] = g.UseFixed(value, edx);
        outputs[output_count++] = g.DefineAsFixed(store, edx);
      } else {
        inputs[input_count++] = g.UseUniqueRegister(value);
        outputs[output_count++] = g.DefineSameAsFirst(store);
      }
      addressing_mode = g.GetEffectiveAddressMemoryOperand(
          store, inputs, &input_count,
          IA32OperandGenerator::RegisterMode::kUniqueRegister);
      opcode = GetSeqCstStoreOpcode(rep);
    } else {
      // Release and non-atomic stores emit MOV.
      // https://www.cl.cam.ac.uk/~pes20/cpp/cpp0xmappings.html
      InstructionOperand val;
      if (g.CanBeImmediate(value)) {
        val = g.UseImmediate(value);
      } else if (!atomic_order && (rep == MachineRepresentation::kWord8 ||
                                   rep == MachineRepresentation::kBit)) {
        val = g.UseByteRegister(value);
      } else {
        val = g.UseUniqueRegister(value);
      }
      addressing_mode = g.GetEffectiveAddressMemoryOperand(
          store, inputs, &input_count,
          IA32OperandGenerator::RegisterMode::kUniqueRegister);
      inputs[input_count++] = val;
      opcode = GetStoreOpcode(rep);
    }
    InstructionCode code =
        opcode | AddressingModeField::encode(addressing_mode);
    selector->Emit(code, output_count, outputs, input_count, inputs);
  }
}
References arraysize, v8::internal::compiler::IA32OperandGenerator::CanBeImmediate(), v8::internal::CanBeTaggedPointer(), code, v8::internal::DCHECK(), DCHECK_LT, v8::internal::compiler::OperandGenerator::DefineAsFixed(), v8::internal::compiler::OperandGenerator::DefineSameAsFirst(), v8::internal::compiler::InstructionSelector::Emit(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::IA32OperandGenerator::GenerateMemoryOperandInputs(), v8::internal::compiler::IA32OperandGenerator::GetEffectiveAddressMemoryOperand(), GetSeqCstStoreOpcode(), GetStoreOpcode(), v8::internal::index, v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::kBit, v8::internal::compiler::kFullWriteBarrier, v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kPositiveDisplacement, v8::internal::kSeqCst, v8::internal::kWord8, v8::internal::compiler::StoreRepresentation::representation(), store(), v8::internal::compiler::OperandGenerator::TempRegister(), v8::internal::compiler::IA32OperandGenerator::UseByteRegister(), v8::internal::compiler::OperandGenerator::UseFixed(), v8::internal::compiler::OperandGenerator::UseImmediate(), v8::internal::compiler::OperandGenerator::UseUniqueRegister(), v8::internal::v8_flags, v8::internal::value, v8::internal::compiler::StoreRepresentation::write_barrier_kind(), and v8::internal::compiler::WriteBarrierKindToRecordWriteMode().
VisitWordCompare() [1/2]
void v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitWordCompare (InstructionSelector * selector, OpIndex node, FlagsContinuation * cont)
Definition at line 2076 of file instruction-selector-ia32.cc.
                                               {
  VisitWordCompare(selector, node, kIA32Cmp, cont);
}
References v8::internal::compiler::VisitWordCompare().
VisitWordCompare() [2/2]
void v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitWordCompare (InstructionSelector * selector, OpIndex node, InstructionCode opcode, FlagsContinuation * cont)
Definition at line 2031 of file instruction-selector-ia32.cc.
                                                                       {
  { // Temporary scope to minimize indentation change churn below.
    IA32OperandGenerator g(selector);
    auto [left, right] = selector->Inputs<2>(node);
    InstructionCode narrowed_opcode =
        TryNarrowOpcodeSize(selector, opcode, left, right, cont);
    int effect_level = selector->GetEffectLevel(node, cont);
    // If one of the two inputs is an immediate, make sure it's on the right, or
    // if one of the two inputs is a memory operand, make sure it's on the left.
    if ((!g.CanBeImmediate(right) && g.CanBeImmediate(left)) ||
        (g.CanBeMemoryOperand(narrowed_opcode, node, right, effect_level) &&
         !g.CanBeMemoryOperand(narrowed_opcode, node, left, effect_level))) {
      if (!selector->IsCommutative(node)) cont->Commute();
      std::swap(left, right);
    }
    // Match immediates on right side of comparison.
    if (g.CanBeImmediate(right)) {
      if (g.CanBeMemoryOperand(narrowed_opcode, node, left, effect_level)) {
        return VisitCompareWithMemoryOperand(selector, narrowed_opcode, left,
                                             g.UseImmediate(right), cont);
      }
      return VisitCompare(selector, opcode, g.Use(left), g.UseImmediate(right),
                          cont);
    }
    // Match memory operands on left side of comparison.
    if (g.CanBeMemoryOperand(narrowed_opcode, node, left, effect_level)) {
      bool needs_byte_register =
          narrowed_opcode == kIA32Test8 || narrowed_opcode == kIA32Cmp8;
      return VisitCompareWithMemoryOperand(
          selector, narrowed_opcode, left,
          needs_byte_register ? g.UseByteRegister(right) : g.UseRegister(right),
          cont);
    }
    return VisitCompare(selector, opcode, left, right, cont,
                        selector->IsCommutative(node));
  }
}
References v8::internal::compiler::IA32OperandGenerator::CanBeImmediate(), v8::internal::compiler::IA32OperandGenerator::CanBeMemoryOperand(), v8::internal::compiler::FlagsContinuation::Commute(), v8::internal::compiler::InstructionSelector::GetEffectLevel(), v8::internal::compiler::InstructionSelector::Inputs(), v8::internal::compiler::InstructionSelector::IsCommutative(), TryNarrowOpcodeSize(), v8::internal::compiler::OperandGenerator::Use(), v8::internal::compiler::IA32OperandGenerator::UseByteRegister(), v8::internal::compiler::OperandGenerator::UseImmediate(), v8::internal::compiler::OperandGenerator::UseRegister(), v8::internal::compiler::VisitCompare(), and VisitCompareWithMemoryOperand().