v8::internal::anonymous_namespace{managed.cc} Namespace Reference
Functions
void ManagedObjectFinalizerSecondPass (const v8::WeakCallbackInfo< void > &data)
Function Documentation
ManagedObjectFinalizerSecondPass()
void v8::internal::anonymous_namespace{managed.cc}::ManagedObjectFinalizerSecondPass (const v8::WeakCallbackInfo< void > & data)
Definition at line 16 of file managed.cc.
                                                                            {
  auto destructor =
      reinterpret_cast<ManagedPtrDestructor*>(data.GetParameter());
  Isolate* isolate = reinterpret_cast<Isolate*>(data.GetIsolate());
  isolate->UnregisterManagedPtrDestructor(destructor);
  destructor->destructor_(destructor->shared_ptr_ptr_);
  destructor->external_memory_accounter_.Decrease(
      reinterpret_cast<v8::Isolate*>(isolate), destructor->estimated_size_);
#ifdef V8_ENABLE_SANDBOX
  destructor->ZapExternalPointerTableEntry();
#endif // V8_ENABLE_SANDBOX
  delete destructor;
}
References v8::WeakCallbackInfo< T >::GetIsolate(), v8::WeakCallbackInfo< T >::GetParameter(), and v8::internal::Isolate::UnregisterManagedPtrDestructor().
Referenced by v8::internal::ManagedObjectFinalizer().