v8::internal::anonymous_namespace{builtins-callsite.cc} Namespace Reference
Functions
Tagged< Object > PositiveNumberOrNull (int value, Isolate *isolate)
bool NativeContextIsForShadowRealm (Tagged< NativeContext > native_context)
Function Documentation
NativeContextIsForShadowRealm()
bool v8::internal::anonymous_namespace{builtins-callsite.cc}::NativeContextIsForShadowRealm (Tagged< NativeContext > native_context)
Definition at line 35 of file builtins-callsite.cc.
                                                                         {
  return native_context->scope_info()->scope_type() == SHADOW_REALM_SCOPE;
}
References v8::internal::native_context, and v8::internal::SHADOW_REALM_SCOPE.
Referenced by v8::internal::BUILTIN().
PositiveNumberOrNull()
Tagged<Object> v8::internal::anonymous_namespace{builtins-callsite.cc}::PositiveNumberOrNull (int value, Isolate * isolate)
Definition at line 30 of file builtins-callsite.cc.
                                                                 {
  if (value > 0) return *isolate->factory()->NewNumberFromInt(value);
  return ReadOnlyRoots(isolate).null_value();
}
References v8::internal::Isolate::factory(), v8::internal::FactoryBase< Impl >::NewNumberFromInt(), and v8::internal::value.
Referenced by v8::internal::BUILTIN().