v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc} Namespace Reference
Functions
void VisitRR (InstructionSelector *selector, InstructionCode opcode, OpIndex node)
void VisitRRR (InstructionSelector *selector, InstructionCode opcode, OpIndex node)
template<typename OpmaskT , int kImmMin, int kImmMax, AddressingMode kImmMode, AddressingMode kRegMode>
bool TryMatchShift (InstructionSelector *selector, InstructionCode *opcode_return, OpIndex node, InstructionOperand *value_return, InstructionOperand *shift_return)
template<typename OpmaskT , int kImmMin, int kImmMax, AddressingMode kImmMode>
bool TryMatchShiftImmediate (InstructionSelector *selector, InstructionCode *opcode_return, OpIndex node, InstructionOperand *value_return, InstructionOperand *shift_return)
bool TryMatchROR (InstructionSelector *selector, InstructionCode *opcode_return, OpIndex node, InstructionOperand *value_return, InstructionOperand *shift_return)
bool TryMatchASR (InstructionSelector *selector, InstructionCode *opcode_return, OpIndex node, InstructionOperand *value_return, InstructionOperand *shift_return)
bool TryMatchLSL (InstructionSelector *selector, InstructionCode *opcode_return, OpIndex node, InstructionOperand *value_return, InstructionOperand *shift_return)
bool TryMatchLSLImmediate (InstructionSelector *selector, InstructionCode *opcode_return, OpIndex node, InstructionOperand *value_return, InstructionOperand *shift_return)
bool TryMatchLSR (InstructionSelector *selector, InstructionCode *opcode_return, OpIndex node, InstructionOperand *value_return, InstructionOperand *shift_return)
bool TryMatchImmediateOrShift (InstructionSelector *selector, InstructionCode *opcode_return, OpIndex node, size_t *input_count_return, InstructionOperand *inputs)
void VisitBinop (InstructionSelector *selector, OpIndex node, InstructionCode opcode, InstructionCode reverse_opcode, FlagsContinuation *cont)
void VisitBinop (InstructionSelector *selector, OpIndex node, InstructionCode opcode, InstructionCode reverse_opcode)
void EmitDiv (InstructionSelector *selector, ArchOpcode div_opcode, ArchOpcode f64i32_opcode, ArchOpcode i32f64_opcode, InstructionOperand result_operand, InstructionOperand left_operand, InstructionOperand right_operand)
void VisitDiv (InstructionSelector *selector, OpIndex node, ArchOpcode div_opcode, ArchOpcode f64i32_opcode, ArchOpcode i32f64_opcode)
void VisitMod (InstructionSelector *selector, OpIndex node, ArchOpcode div_opcode, ArchOpcode f64i32_opcode, ArchOpcode i32f64_opcode)
void EmitAddBeforeS128LoadStore (InstructionSelector *selector, InstructionCode *opcode_return, size_t *input_count_return, InstructionOperand *inputs)
void EmitLoad (InstructionSelector *selector, InstructionCode opcode, InstructionOperand *output, OpIndex base, OpIndex index)
void EmitStore (InstructionSelector *selector, InstructionCode opcode, size_t input_count, InstructionOperand *inputs, OpIndex index)
void VisitPairAtomicBinOp (InstructionSelector *selector, OpIndex node, ArchOpcode opcode)
ArchOpcode GetStoreOpcode (MachineRepresentation rep)
ArchOpcode GetAtomicStoreOpcode (MachineRepresentation rep)
void VisitStoreCommon (InstructionSelector *selector, OpIndex node, StoreRepresentation store_rep, std::optional< AtomicMemoryOrder > atomic_order)
void EmitBic (InstructionSelector *selector, OpIndex node, OpIndex left, OpIndex right)
void EmitUbfx (InstructionSelector *selector, OpIndex node, OpIndex left, uint32_t lsb, uint32_t width)
template<typename TryMatchShift >
void VisitShift (InstructionSelector *selector, OpIndex node, TryMatchShift try_match_shift, FlagsContinuation *cont)
template<typename TryMatchShift >
void VisitShift (InstructionSelector *selector, OpIndex node, TryMatchShift try_match_shift)
void VisitWord32PairShift (InstructionSelector *selector, InstructionCode opcode, OpIndex node)
void EmitInt32MulWithOverflow (InstructionSelector *selector, OpIndex node, FlagsContinuation *cont)
void VisitCompare (InstructionSelector *selector, InstructionCode opcode, InstructionOperand left, InstructionOperand right, FlagsContinuation *cont)
void VisitFloat32Compare (InstructionSelector *selector, OpIndex node, FlagsContinuation *cont)
void VisitFloat64Compare (InstructionSelector *selector, OpIndex node, FlagsContinuation *cont)
bool CanUseFlagSettingBinop (FlagsCondition cond)
FlagsCondition MapForFlagSettingBinop (FlagsCondition cond)
void MaybeReplaceCmpZeroWithFlagSettingBinop (InstructionSelector *selector, OpIndex *node, OpIndex binop, InstructionCode *opcode, FlagsCondition cond, FlagsContinuation *cont)
void VisitWordCompare (InstructionSelector *selector, OpIndex node, InstructionCode opcode, FlagsContinuation *cont)
void VisitWordCompare (InstructionSelector *selector, OpIndex node, FlagsContinuation *cont)
template<ArchOpcode opcode>
void VisitBitMask (InstructionSelector *selector, OpIndex node)
Function Documentation
CanUseFlagSettingBinop()
bool v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::CanUseFlagSettingBinop (FlagsCondition cond)
Definition at line 1961 of file instruction-selector-arm.cc.
                                                 {
  switch (cond) {
    case kEqual:
    case kNotEqual:
    case kSignedLessThan:
    case kSignedGreaterThanOrEqual:
    case kUnsignedLessThanOrEqual: // x <= 0 -> x == 0
    case kUnsignedGreaterThan: // x > 0 -> x != 0
      return true;
    default:
      return false;
  }
}
References v8::internal::kEqual, v8::internal::compiler::kNotEqual, v8::internal::compiler::kSignedGreaterThanOrEqual, v8::internal::compiler::kSignedLessThan, v8::internal::compiler::kUnsignedGreaterThan, and v8::internal::compiler::kUnsignedLessThanOrEqual.
Referenced by MapForFlagSettingBinop(), and VisitWordCompare().
EmitAddBeforeS128LoadStore()
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitAddBeforeS128LoadStore (InstructionSelector * selector, InstructionCode * opcode_return, size_t * input_count_return, InstructionOperand * inputs)
Definition at line 393 of file instruction-selector-arm.cc.
                                                            {
  ArmOperandGenerator g(selector);
  InstructionOperand addr = g.TempRegister();
  InstructionCode op = kArmAdd;
  op |= AddressingModeField::encode(kMode_Operand2_R);
  selector->Emit(op, 1, &addr, 2, inputs);
  *opcode_return |= AddressingModeField::encode(kMode_Operand2_R);
  *input_count_return -= 1;
  inputs[0] = addr;
}
References v8::internal::compiler::InstructionSelector::Emit(), v8::base::BitField< T, shift, size, U >::encode(), and v8::internal::compiler::OperandGenerator::TempRegister().
Referenced by EmitLoad(), and EmitStore().
EmitBic()
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitBic (InstructionSelector * selector, OpIndex node, OpIndex left, OpIndex right)
Definition at line 1029 of file instruction-selector-arm.cc.
                            {
  ArmOperandGenerator g(selector);
  InstructionCode opcode = kArmBic;
  InstructionOperand value_operand;
  InstructionOperand shift_operand;
  if (TryMatchShift(selector, &opcode, right, &value_operand, &shift_operand)) {
    selector->Emit(opcode, g.DefineAsRegister(node), g.UseRegister(left),
                   value_operand, shift_operand);
    return;
  }
  selector->Emit(opcode | AddressingModeField::encode(kMode_Operand2_R),
                 g.DefineAsRegister(node), g.UseRegister(left),
                 g.UseRegister(right));
}
References v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::InstructionSelector::Emit(), v8::base::BitField< T, shift, size, U >::encode(), TryMatchShift(), and v8::internal::compiler::OperandGenerator::UseRegister().
EmitDiv()
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitDiv (InstructionSelector * selector, ArchOpcode div_opcode, ArchOpcode f64i32_opcode, ArchOpcode i32f64_opcode, InstructionOperand result_operand, InstructionOperand left_operand, InstructionOperand right_operand)
Definition at line 337 of file instruction-selector-arm.cc.
                                               {
  ArmOperandGenerator g(selector);
  if (selector->IsSupported(SUDIV)) {
    selector->Emit(div_opcode, result_operand, left_operand, right_operand);
    return;
  }
  InstructionOperand left_double_operand = g.TempDoubleRegister();
  InstructionOperand right_double_operand = g.TempDoubleRegister();
  InstructionOperand result_double_operand = g.TempDoubleRegister();
  selector->Emit(f64i32_opcode, left_double_operand, left_operand);
  selector->Emit(f64i32_opcode, right_double_operand, right_operand);
  selector->Emit(kArmVdivF64, result_double_operand, left_double_operand,
                 right_double_operand);
  selector->Emit(i32f64_opcode, result_operand, result_double_operand);
}
References v8::internal::compiler::InstructionSelector::Emit(), v8::internal::compiler::InstructionSelector::IsSupported(), and v8::internal::compiler::OperandGenerator::TempDoubleRegister().
Referenced by VisitDiv(), and VisitMod().
EmitInt32MulWithOverflow()
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitInt32MulWithOverflow (InstructionSelector * selector, OpIndex node, FlagsContinuation * cont)
Definition at line 1593 of file instruction-selector-arm.cc.
                                                       {
  ArmOperandGenerator g(selector);
  const OverflowCheckedBinopOp& binop =
      selector->Cast<OverflowCheckedBinopOp>(node);
  InstructionOperand result_operand = g.DefineAsRegister(node);
  InstructionOperand temp_operand = g.TempRegister();
  InstructionOperand outputs[] = {result_operand, temp_operand};
  InstructionOperand inputs[] = {g.UseRegister(binop.left()),
                                 g.UseRegister(binop.right())};
  selector->Emit(kArmSmull, 2, outputs, 2, inputs);
  // result operand needs shift operator.
  InstructionOperand shift_31 = g.UseImmediate(31);
  InstructionCode opcode =
      kArmCmp | AddressingModeField::encode(kMode_Operand2_R_ASR_I);
  selector->EmitWithContinuation(opcode, temp_operand, result_operand, shift_31,
                                 cont);
}
References v8::internal::compiler::turboshaft::OperationMatcher::Cast(), v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::InstructionSelector::Emit(), v8::internal::compiler::InstructionSelector::EmitWithContinuation(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::left(), v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::right(), v8::internal::compiler::OperandGenerator::TempRegister(), v8::internal::compiler::OperandGenerator::UseImmediate(), and v8::internal::compiler::OperandGenerator::UseRegister().
Referenced by v8::internal::compiler::InstructionSelector::VisitWordCompareZero().
EmitLoad()
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitLoad (InstructionSelector * selector, InstructionCode opcode, InstructionOperand * output, OpIndex base, OpIndex index)
Definition at line 407 of file instruction-selector-arm.cc.
                                                                       {
  ArmOperandGenerator g(selector);
  InstructionOperand inputs[3];
  size_t input_count = 2;
  const Operation& base_op = selector->Get(base);
  int64_t index_constant;
  const bool is_index_constant =
      selector->MatchSignedIntegralConstant(index, &index_constant);
  if (base_op.Is<Opmask::kExternalConstant>() && is_index_constant) {
    const ConstantOp& constant_base = base_op.Cast<ConstantOp>();
    if (selector->CanAddressRelativeToRootsRegister(
            constant_base.external_reference())) {
      ptrdiff_t const delta =
          index_constant +
          MacroAssemblerBase::RootRegisterOffsetForExternalReference(
              selector->isolate(), constant_base.external_reference());
      input_count = 1;
      inputs[0] = g.UseImmediate(static_cast<int32_t>(delta));
      opcode |= AddressingModeField::encode(kMode_Root);
      selector->Emit(opcode, 1, output, input_count, inputs);
      return;
    }
  }
  if (base_op.Is<LoadRootRegisterOp>() && is_index_constant) {
    input_count = 1;
    // This will only work if {index} is a constant.
    DCHECK(is_int32(index_constant));
    inputs[0] = g.UseImmediate(static_cast<int32_t>(index_constant));
    opcode |= AddressingModeField::encode(kMode_Root);
    selector->Emit(opcode, 1, output, input_count, inputs);
    return;
  }
  inputs[0] = g.UseRegister(base);
  if (g.CanBeImmediate(index, opcode)) {
    inputs[1] = g.UseImmediate(index);
    opcode |= AddressingModeField::encode(kMode_Offset_RI);
  } else if ((opcode == kArmLdr) &&
             TryMatchLSLImmediate(selector, &opcode, index, &inputs[1],
                                  &inputs[2])) {
    input_count = 3;
  } else {
    inputs[1] = g.UseRegister(index);
    if (opcode == kArmVld1S128) {
      EmitAddBeforeS128LoadStore(selector, &opcode, &input_count, &inputs[0]);
    } else {
      opcode |= AddressingModeField::encode(kMode_Offset_RR);
    }
  }
  selector->Emit(opcode, 1, output, input_count, inputs);
}
References v8::internal::compiler::InstructionSelector::CanAddressRelativeToRootsRegister(), v8::internal::compiler::ArmOperandGenerator::CanBeImmediate(), v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::DCHECK(), v8::internal::compiler::InstructionSelector::Emit(), EmitAddBeforeS128LoadStore(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::turboshaft::ConstantOp::external_reference(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::index, v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::compiler::InstructionSelector::isolate(), v8::internal::compiler::turboshaft::OperationMatcher::MatchSignedIntegralConstant(), v8::internal::MacroAssemblerBase::RootRegisterOffsetForExternalReference(), TryMatchLSLImmediate(), v8::internal::compiler::OperandGenerator::UseImmediate(), and v8::internal::compiler::OperandGenerator::UseRegister().
EmitStore()
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitStore (InstructionSelector * selector, InstructionCode opcode, size_t input_count, InstructionOperand * inputs, OpIndex index)
Definition at line 462 of file instruction-selector-arm.cc.
                                                                              {
  ArmOperandGenerator g(selector);
  ArchOpcode arch_opcode = ArchOpcodeField::decode(opcode);
  if (g.CanBeImmediate(index, opcode)) {
    inputs[input_count++] = g.UseImmediate(index);
    opcode |= AddressingModeField::encode(kMode_Offset_RI);
  } else if ((arch_opcode == kArmStr || arch_opcode == kAtomicStoreWord32) &&
             TryMatchLSLImmediate(selector, &opcode, index, &inputs[2],
                                  &inputs[3])) {
    input_count = 4;
  } else {
    inputs[input_count++] = g.UseRegister(index);
    if (arch_opcode == kArmVst1S128) {
      // Inputs are value, base, index, only care about base and index.
      EmitAddBeforeS128LoadStore(selector, &opcode, &input_count, &inputs[1]);
    } else {
      opcode |= AddressingModeField::encode(kMode_Offset_RR);
    }
  }
  selector->Emit(opcode, 0, nullptr, input_count, inputs);
}
References v8::internal::compiler::ArmOperandGenerator::CanBeImmediate(), v8::base::BitField< T, shift, size, U >::decode(), v8::internal::compiler::InstructionSelector::Emit(), EmitAddBeforeS128LoadStore(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::index, v8::internal::compiler::turboshaft::detail::input_count(), TryMatchLSLImmediate(), v8::internal::compiler::OperandGenerator::UseImmediate(), and v8::internal::compiler::OperandGenerator::UseRegister().
Referenced by VisitStoreCommon().
EmitUbfx()
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitUbfx (InstructionSelector * selector, OpIndex node, OpIndex left, uint32_t lsb, uint32_t width)
Definition at line 1045 of file instruction-selector-arm.cc.
                                            {
  DCHECK_LE(lsb, 31u);
  DCHECK_LE(1u, width);
  DCHECK_LE(width, 32u - lsb);
  ArmOperandGenerator g(selector);
  selector->Emit(kArmUbfx, g.DefineAsRegister(node), g.UseRegister(left),
                 g.TempImmediate(lsb), g.TempImmediate(width));
}
References DCHECK_LE, v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::InstructionSelector::Emit(), v8::internal::compiler::OperandGenerator::TempImmediate(), and v8::internal::compiler::OperandGenerator::UseRegister().
GetAtomicStoreOpcode()
ArchOpcode v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::GetAtomicStoreOpcode (MachineRepresentation rep)
Definition at line 742 of file instruction-selector-arm.cc.
                                                           {
  switch (rep) {
    case MachineRepresentation::kWord8:
      return kAtomicStoreWord8;
    case MachineRepresentation::kWord16:
      return kAtomicStoreWord16;
    case MachineRepresentation::kTaggedSigned: // Fall through.
    case MachineRepresentation::kTaggedPointer: // Fall through.
    case MachineRepresentation::kTagged: // Fall through.
    case MachineRepresentation::kWord32:
      return kAtomicStoreWord32;
    default:
      UNREACHABLE();
  }
}
References v8::internal::kTagged, v8::internal::kTaggedPointer, v8::internal::kTaggedSigned, v8::internal::kWord16, v8::internal::kWord32, v8::internal::kWord8, and v8::internal::UNREACHABLE().
Referenced by VisitStoreCommon().
GetStoreOpcode()
ArchOpcode v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::GetStoreOpcode (MachineRepresentation rep)
Definition at line 708 of file instruction-selector-arm.cc.
                                                     {
  switch (rep) {
    case MachineRepresentation::kFloat32:
      return kArmVstrF32;
    case MachineRepresentation::kFloat64:
      return kArmVstrF64;
    case MachineRepresentation::kBit: // Fall through.
    case MachineRepresentation::kWord8:
      return kArmStrb;
    case MachineRepresentation::kWord16:
      return kArmStrh;
    case MachineRepresentation::kTaggedSigned: // Fall through.
    case MachineRepresentation::kTaggedPointer: // Fall through.
    case MachineRepresentation::kTagged: // Fall through.
    case MachineRepresentation::kWord32:
      return kArmStr;
    case MachineRepresentation::kSimd128:
      return kArmVst1S128;
    case MachineRepresentation::kFloat16:
      UNIMPLEMENTED();
    case MachineRepresentation::kSimd256: // Fall through.
    case MachineRepresentation::kCompressedPointer: // Fall through.
    case MachineRepresentation::kCompressed: // Fall through.
    case MachineRepresentation::kProtectedPointer: // Fall through.
    case MachineRepresentation::kIndirectPointer: // Fall through.
    case MachineRepresentation::kSandboxedPointer: // Fall through.
    case MachineRepresentation::kWord64: // Fall through.
    case MachineRepresentation::kMapWord: // Fall through.
    case MachineRepresentation::kFloat16RawBits: // Fall through.
    case MachineRepresentation::kNone:
      UNREACHABLE();
  }
}
References v8::internal::kBit, v8::internal::kCompressed, v8::internal::kCompressedPointer, v8::internal::kFloat16, v8::internal::kFloat16RawBits, v8::internal::kFloat32, v8::internal::kFloat64, v8::internal::kIndirectPointer, v8::internal::kMapWord, v8::internal::kNone, v8::internal::kProtectedPointer, v8::internal::kSandboxedPointer, v8::internal::kSimd128, v8::internal::kSimd256, v8::internal::kTagged, v8::internal::kTaggedPointer, v8::internal::kTaggedSigned, v8::internal::kWord16, v8::internal::kWord32, v8::internal::kWord64, v8::internal::kWord8, v8::internal::compiler::UNIMPLEMENTED(), and v8::internal::UNREACHABLE().
Referenced by VisitStoreCommon().
MapForFlagSettingBinop()
FlagsCondition v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::MapForFlagSettingBinop (FlagsCondition cond)
Definition at line 1980 of file instruction-selector-arm.cc.
                                                           {
  DCHECK(CanUseFlagSettingBinop(cond));
  switch (cond) {
    case kEqual:
    case kNotEqual:
      return cond;
    case kSignedLessThan:
      return kNegative;
    case kSignedGreaterThanOrEqual:
      return kPositiveOrZero;
    case kUnsignedLessThanOrEqual: // x <= 0 -> x == 0
      return kEqual;
    case kUnsignedGreaterThan: // x > 0 -> x != 0
      return kNotEqual;
    default:
      UNREACHABLE();
  }
}
References CanUseFlagSettingBinop(), v8::internal::DCHECK(), v8::internal::kEqual, v8::internal::compiler::kNegative, v8::internal::compiler::kNotEqual, v8::internal::compiler::kPositiveOrZero, v8::internal::compiler::kSignedGreaterThanOrEqual, v8::internal::compiler::kSignedLessThan, v8::internal::compiler::kUnsignedGreaterThan, v8::internal::compiler::kUnsignedLessThanOrEqual, and v8::internal::UNREACHABLE().
Referenced by MaybeReplaceCmpZeroWithFlagSettingBinop().
MaybeReplaceCmpZeroWithFlagSettingBinop()
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::MaybeReplaceCmpZeroWithFlagSettingBinop (InstructionSelector * selector, OpIndex * node, OpIndex binop, InstructionCode * opcode, FlagsCondition cond, FlagsContinuation * cont)
Definition at line 2005 of file instruction-selector-arm.cc.
                                                                      {
  InstructionCode binop_opcode;
  InstructionCode no_output_opcode;
  const Operation& op = selector->Get(binop);
  if (op.Is<Opmask::kWord32Add>()) {
    binop_opcode = kArmAdd;
    no_output_opcode = kArmCmn;
  } else if (op.Is<Opmask::kWord32BitwiseAnd>()) {
    binop_opcode = kArmAnd;
    no_output_opcode = kArmTst;
  } else if (op.Is<Opmask::kWord32BitwiseOr>()) {
    binop_opcode = kArmOrr;
    no_output_opcode = kArmOrr;
  } else if (op.Is<Opmask::kWord32BitwiseXor>()) {
    binop_opcode = kArmEor;
    no_output_opcode = kArmTeq;
  }
  if (selector->CanCover(*node, binop)) {
    // The comparison is the only user of {node}.
    cont->Overwrite(MapForFlagSettingBinop(cond));
    *opcode = no_output_opcode;
    *node = binop;
  } else if (selector->IsOnlyUserOfNodeInSameBlock(*node, binop)) {
    // We can also handle the case where the {node} and the comparison are in
    // the same basic block, and the comparison is the only user of {node} in
    // this basic block ({node} has users in other basic blocks).
    cont->Overwrite(MapForFlagSettingBinop(cond));
    *opcode = binop_opcode;
    *node = binop;
  }
}
References v8::internal::compiler::InstructionSelector::CanCover(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::compiler::InstructionSelector::IsOnlyUserOfNodeInSameBlock(), MapForFlagSettingBinop(), and v8::internal::compiler::FlagsContinuation::Overwrite().
Referenced by VisitWordCompare().
TryMatchASR()
bool v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::TryMatchASR (InstructionSelector * selector, InstructionCode * opcode_return, OpIndex node, InstructionOperand * value_return, InstructionOperand * shift_return)
Definition at line 214 of file instruction-selector-arm.cc.
                                                   {
  return TryMatchShift<Opmask::kWord32ShiftRightArithmetic, 1, 32,
                       kMode_Operand2_R_ASR_I, kMode_Operand2_R_ASR_R>(
             selector, opcode_return, node, value_return, shift_return) ||
         TryMatchShift<Opmask::kWord32ShiftRightArithmeticShiftOutZeros, 1, 32,
                       kMode_Operand2_R_ASR_I, kMode_Operand2_R_ASR_R>(
             selector, opcode_return, node, value_return, shift_return);
}
References TryMatchShift().
Referenced by v8::internal::compiler::InstructionSelector::VisitWordCompareZero().
TryMatchImmediateOrShift()
bool v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::TryMatchImmediateOrShift (InstructionSelector * selector, InstructionCode * opcode_return, OpIndex node, size_t * input_count_return, InstructionOperand * inputs)
Definition at line 261 of file instruction-selector-arm.cc.
                                                          {
  ArmOperandGenerator g(selector);
  if (g.CanBeImmediate(node, *opcode_return)) {
    *opcode_return |= AddressingModeField::encode(kMode_Operand2_I);
    inputs[0] = g.UseImmediate(node);
    *input_count_return = 1;
    return true;
  }
  if (TryMatchShift(selector, opcode_return, node, &inputs[0], &inputs[1])) {
    *input_count_return = 2;
    return true;
  }
  return false;
}
References v8::internal::compiler::ArmOperandGenerator::CanBeImmediate(), v8::base::BitField< T, shift, size, U >::encode(), TryMatchShift(), and v8::internal::compiler::OperandGenerator::UseImmediate().
Referenced by VisitBinop(), and VisitWordCompare().
TryMatchLSL()
bool v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::TryMatchLSL (InstructionSelector * selector, InstructionCode * opcode_return, OpIndex node, InstructionOperand * value_return, InstructionOperand * shift_return)
Definition at line 225 of file instruction-selector-arm.cc.
                                                   {
  return TryMatchShift<Opmask::kWord32ShiftLeft, 0, 31, kMode_Operand2_R_LSL_I,
                       kMode_Operand2_R_LSL_R>(selector, opcode_return, node,
                                               value_return, shift_return);
}
References TryMatchShift().
Referenced by v8::internal::compiler::InstructionSelector::VisitWordCompareZero().
TryMatchLSLImmediate()
bool v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::TryMatchLSLImmediate (InstructionSelector * selector, InstructionCode * opcode_return, OpIndex node, InstructionOperand * value_return, InstructionOperand * shift_return)
Definition at line 233 of file instruction-selector-arm.cc.
                                                            {
  return TryMatchShiftImmediate<Opmask::kWord32ShiftLeft, 0, 31,
                                kMode_Operand2_R_LSL_I>(
      selector, opcode_return, node, value_return, shift_return);
}
References TryMatchShiftImmediate().
Referenced by EmitLoad(), and EmitStore().
TryMatchLSR()
bool v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::TryMatchLSR (InstructionSelector * selector, InstructionCode * opcode_return, OpIndex node, InstructionOperand * value_return, InstructionOperand * shift_return)
Definition at line 242 of file instruction-selector-arm.cc.
                                                   {
  return TryMatchShift<Opmask::kWord32ShiftRightLogical, 1, 32,
                       kMode_Operand2_R_LSR_I, kMode_Operand2_R_LSR_R>(
      selector, opcode_return, node, value_return, shift_return);
}
References TryMatchShift().
Referenced by v8::internal::compiler::InstructionSelector::VisitWordCompareZero().
TryMatchROR()
bool v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::TryMatchROR (InstructionSelector * selector, InstructionCode * opcode_return, OpIndex node, InstructionOperand * value_return, InstructionOperand * shift_return)
Definition at line 206 of file instruction-selector-arm.cc.
                                                   {
  return TryMatchShift<Opmask::kWord32RotateRight, 1, 31,
                       kMode_Operand2_R_ROR_I, kMode_Operand2_R_ROR_R>(
      selector, opcode_return, node, value_return, shift_return);
}
References TryMatchShift().
Referenced by v8::internal::compiler::InstructionSelector::VisitWordCompareZero().
TryMatchShift()
template<typename OpmaskT , int kImmMin, int kImmMax, AddressingMode kImmMode, AddressingMode kRegMode>
bool v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::TryMatchShift (InstructionSelector * selector, InstructionCode * opcode_return, OpIndex node, InstructionOperand * value_return, InstructionOperand * shift_return)
Definition at line 162 of file instruction-selector-arm.cc.
                                                     {
  ArmOperandGenerator g(selector);
  const Operation& op = selector->Get(node);
  if (op.Is<OpmaskT>()) {
    const ShiftOp& shift = op.Cast<ShiftOp>();
    *value_return = g.UseRegister(shift.left());
    int32_t shift_by;
    if (selector->MatchIntegralWord32Constant(shift.right(), &shift_by) &&
        base::IsInRange(shift_by, kImmMin, kImmMax)) {
      *opcode_return |= AddressingModeField::encode(kImmMode);
      *shift_return = g.UseImmediate(shift.right());
    } else {
      *opcode_return |= AddressingModeField::encode(kRegMode);
      *shift_return = g.UseRegister(shift.right());
    }
    return true;
  }
  return false;
}
References v8::internal::compiler::turboshaft::Operation::Cast(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralWord32Constant(), v8::internal::compiler::turboshaft::ShiftOp::right(), v8::internal::compiler::OperandGenerator::UseImmediate(), and v8::internal::compiler::OperandGenerator::UseRegister().
Referenced by EmitBic(), TryMatchASR(), TryMatchImmediateOrShift(), TryMatchLSL(), TryMatchLSR(), and TryMatchROR().
TryMatchShiftImmediate()
template<typename OpmaskT , int kImmMin, int kImmMax, AddressingMode kImmMode>
bool v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::TryMatchShiftImmediate (InstructionSelector * selector, InstructionCode * opcode_return, OpIndex node, InstructionOperand * value_return, InstructionOperand * shift_return)
Definition at line 186 of file instruction-selector-arm.cc.
                                                              {
  ArmOperandGenerator g(selector);
  const Operation& op = selector->Get(node);
  if (op.Is<OpmaskT>()) {
    const ShiftOp& shift = op.Cast<ShiftOp>();
    int32_t shift_by;
    if (selector->MatchIntegralWord32Constant(shift.right(), &shift_by) &&
        base::IsInRange(shift_by, kImmMin, kImmMax)) {
      *opcode_return |= AddressingModeField::encode(kImmMode);
      *value_return = g.UseRegister(shift.left());
      *shift_return = g.UseImmediate(shift.right());
      return true;
    }
  }
  return false;
}
References v8::internal::compiler::turboshaft::Operation::Cast(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralWord32Constant(), v8::internal::compiler::turboshaft::ShiftOp::right(), v8::internal::compiler::OperandGenerator::UseImmediate(), and v8::internal::compiler::OperandGenerator::UseRegister().
Referenced by TryMatchLSLImmediate().
VisitBinop() [1/2]
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitBinop (InstructionSelector * selector, OpIndex node, InstructionCode opcode, InstructionCode reverse_opcode)
Definition at line 331 of file instruction-selector-arm.cc.
                                                                        {
  FlagsContinuation cont;
  VisitBinop(selector, node, opcode, reverse_opcode, &cont);
}
References v8::internal::compiler::VisitBinop().
VisitBinop() [2/2]
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitBinop (InstructionSelector * selector, OpIndex node, InstructionCode opcode, InstructionCode reverse_opcode, FlagsContinuation * cont)
Definition at line 279 of file instruction-selector-arm.cc.
                                         {
  using OpIndex = OpIndex;
  ArmOperandGenerator g(selector);
  const Operation& op = selector->Get(node);
  OpIndex lhs = op.input(0);
  OpIndex rhs = op.input(1);
  InstructionOperand inputs[3];
  size_t input_count = 0;
  InstructionOperand outputs[1];
  size_t output_count = 0;
  if (lhs == rhs) {
    // If both inputs refer to the same operand, enforce allocating a register
    // for both of them to ensure that we don't end up generating code like
    // this:
    //
    // mov r0, r1, asr #16
    // adds r0, r0, r1, asr #16
    // bvs label
    InstructionOperand const input = g.UseRegister(lhs);
    opcode |= AddressingModeField::encode(kMode_Operand2_R);
    inputs[input_count++] = input;
    inputs[input_count++] = input;
  } else if (TryMatchImmediateOrShift(selector, &opcode, rhs, &input_count,
                                      &inputs[1])) {
    inputs[0] = g.UseRegister(lhs);
    input_count++;
  } else if (TryMatchImmediateOrShift(selector, &reverse_opcode, lhs,
                                      &input_count, &inputs[1])) {
    inputs[0] = g.UseRegister(rhs);
    opcode = reverse_opcode;
    input_count++;
  } else {
    opcode |= AddressingModeField::encode(kMode_Operand2_R);
    inputs[input_count++] = g.UseRegister(lhs);
    inputs[input_count++] = g.UseRegister(rhs);
  }
  outputs[output_count++] = g.DefineAsRegister(node);
  DCHECK_NE(0u, input_count);
  DCHECK_EQ(1u, output_count);
  DCHECK_GE(arraysize(inputs), input_count);
  DCHECK_GE(arraysize(outputs), output_count);
  DCHECK_NE(kMode_None, AddressingModeField::decode(opcode));
  selector->EmitWithContinuation(opcode, output_count, outputs, input_count,
                                 inputs, cont);
}
References arraysize, DCHECK_EQ, DCHECK_GE, DCHECK_NE, v8::base::BitField< T, shift, size, U >::decode(), v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::InstructionSelector::EmitWithContinuation(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::turboshaft::OpIndex, TryMatchImmediateOrShift(), and v8::internal::compiler::OperandGenerator::UseRegister().
VisitBitMask()
template<ArchOpcode opcode>
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitBitMask (InstructionSelector * selector, OpIndex node)
Definition at line 3352 of file instruction-selector-arm.cc.
                                                               {
  ArmOperandGenerator g(selector);
  InstructionOperand temps[] = {g.TempSimd128Register()};
  selector->Emit(opcode, g.DefineAsRegister(node),
                 g.UseRegister(selector->Get(node).input(0)), arraysize(temps),
                 temps);
}
References arraysize, v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::InstructionSelector::Emit(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::OperandGenerator::TempSimd128Register(), and v8::internal::compiler::OperandGenerator::UseRegister().
VisitCompare()
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitCompare (InstructionSelector * selector, InstructionCode opcode, InstructionOperand left, InstructionOperand right, FlagsContinuation * cont)
Definition at line 1911 of file instruction-selector-arm.cc.
                                           {
  selector->EmitWithContinuation(opcode, left, right, cont);
}
References v8::internal::compiler::InstructionSelector::EmitWithContinuation().
VisitDiv()
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitDiv (InstructionSelector * selector, OpIndex node, ArchOpcode div_opcode, ArchOpcode f64i32_opcode, ArchOpcode i32f64_opcode)
Definition at line 356 of file instruction-selector-arm.cc.
                                        {
  ArmOperandGenerator g(selector);
  const WordBinopOp& binop = selector->Cast<WordBinopOp>(node);
  EmitDiv(selector, div_opcode, f64i32_opcode, i32f64_opcode,
          g.DefineAsRegister(node), g.UseRegister(binop.left()),
          g.UseRegister(binop.right()));
}
References v8::internal::compiler::turboshaft::OperationMatcher::Cast(), v8::internal::compiler::OperandGenerator::DefineAsRegister(), EmitDiv(), v8::internal::compiler::turboshaft::WordBinopOp::left(), v8::internal::compiler::turboshaft::WordBinopOp::right(), and v8::internal::compiler::OperandGenerator::UseRegister().
VisitFloat32Compare()
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitFloat32Compare (InstructionSelector * selector, OpIndex node, FlagsContinuation * cont)
Definition at line 1918 of file instruction-selector-arm.cc.
                                                  {
  ArmOperandGenerator g(selector);
  const ComparisonOp& cmp = selector->Get(node).template Cast<ComparisonOp>();
  if (selector->MatchZero(cmp.right())) {
    VisitCompare(selector, kArmVcmpF32, g.UseRegister(cmp.left()),
                 g.UseImmediate(cmp.right()), cont);
  } else if (selector->MatchZero(cmp.left())) {
    cont->Commute();
    VisitCompare(selector, kArmVcmpF32, g.UseRegister(cmp.right()),
                 g.UseImmediate(cmp.left()), cont);
  } else {
    VisitCompare(selector, kArmVcmpF32, g.UseRegister(cmp.left()),
                 g.UseRegister(cmp.right()), cont);
  }
}
References v8::internal::compiler::FlagsContinuation::Commute(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::ComparisonOp::left(), v8::internal::compiler::turboshaft::OperationMatcher::MatchZero(), v8::internal::compiler::turboshaft::ComparisonOp::right(), v8::internal::compiler::OperandGenerator::UseImmediate(), v8::internal::compiler::OperandGenerator::UseRegister(), and v8::internal::compiler::VisitCompare().
VisitFloat64Compare()
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitFloat64Compare (InstructionSelector * selector, OpIndex node, FlagsContinuation * cont)
Definition at line 1936 of file instruction-selector-arm.cc.
                                                  {
  ArmOperandGenerator g(selector);
  const ComparisonOp& op = selector->Get(node).template Cast<ComparisonOp>();
  if (selector->MatchZero(op.right())) {
    VisitCompare(selector, kArmVcmpF64, g.UseRegister(op.left()),
                 g.UseImmediate(op.right()), cont);
  } else if (selector->MatchZero(op.left())) {
    cont->Commute();
    VisitCompare(selector, kArmVcmpF64, g.UseRegister(op.right()),
                 g.UseImmediate(op.left()), cont);
  } else {
    VisitCompare(selector, kArmVcmpF64, g.UseRegister(op.left()),
                 g.UseRegister(op.right()), cont);
  }
}
References v8::internal::compiler::FlagsContinuation::Commute(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::ComparisonOp::left(), v8::internal::compiler::turboshaft::OperationMatcher::MatchZero(), v8::internal::compiler::turboshaft::ComparisonOp::right(), v8::internal::compiler::OperandGenerator::UseImmediate(), v8::internal::compiler::OperandGenerator::UseRegister(), and v8::internal::compiler::VisitCompare().
VisitMod()
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitMod (InstructionSelector * selector, OpIndex node, ArchOpcode div_opcode, ArchOpcode f64i32_opcode, ArchOpcode i32f64_opcode)
Definition at line 366 of file instruction-selector-arm.cc.
                                        {
  ArmOperandGenerator g(selector);
  const WordBinopOp& binop = selector->Cast<WordBinopOp>(node);
  InstructionOperand div_operand = g.TempRegister();
  InstructionOperand result_operand = g.DefineAsRegister(node);
  InstructionOperand left_operand = g.UseRegister(binop.left());
  InstructionOperand right_operand = g.UseRegister(binop.right());
  EmitDiv(selector, div_opcode, f64i32_opcode, i32f64_opcode, div_operand,
          left_operand, right_operand);
  if (selector->IsSupported(ARMv7)) {
    selector->Emit(kArmMls, result_operand, div_operand, right_operand,
                   left_operand);
  } else {
    InstructionOperand mul_operand = g.TempRegister();
    selector->Emit(kArmMul, mul_operand, div_operand, right_operand);
    selector->Emit(kArmSub | AddressingModeField::encode(kMode_Operand2_R),
                   result_operand, left_operand, mul_operand);
  }
}
References v8::internal::compiler::turboshaft::OperationMatcher::Cast(), v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::InstructionSelector::Emit(), EmitDiv(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::InstructionSelector::IsSupported(), v8::internal::compiler::turboshaft::WordBinopOp::left(), v8::internal::compiler::turboshaft::WordBinopOp::right(), v8::internal::compiler::OperandGenerator::TempRegister(), and v8::internal::compiler::OperandGenerator::UseRegister().
VisitPairAtomicBinOp()
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitPairAtomicBinOp (InstructionSelector * selector, OpIndex node, ArchOpcode opcode)
Definition at line 486 of file instruction-selector-arm.cc.
                                             {
  ArmOperandGenerator g(selector);
  const AtomicWord32PairOp& pair_binop =
      selector->Cast<AtomicWord32PairOp>(node);
  AddressingMode addressing_mode = kMode_Offset_RR;
  InstructionCode code = opcode | AddressingModeField::encode(addressing_mode);
  InstructionOperand inputs[] = {
      g.UseUniqueRegister(pair_binop.value_low().value()),
      g.UseUniqueRegister(pair_binop.value_high().value()),
      g.UseUniqueRegister(pair_binop.base()),
      g.UseUniqueRegister(pair_binop.index().value())};
  InstructionOperand outputs[2];
  size_t output_count = 0;
  InstructionOperand temps[6];
  size_t temp_count = 0;
  temps[temp_count++] = g.TempRegister();
  temps[temp_count++] = g.TempRegister(r6);
  temps[temp_count++] = g.TempRegister(r7);
  temps[temp_count++] = g.TempRegister();
  OptionalOpIndex projection0 = selector->FindProjection(node, 0);
  OptionalOpIndex projection1 = selector->FindProjection(node, 1);
  if (projection0.valid()) {
    outputs[output_count++] = g.DefineAsFixed(projection0.value(), r2);
  } else {
    temps[temp_count++] = g.TempRegister(r2);
  }
  if (projection1.valid()) {
    outputs[output_count++] = g.DefineAsFixed(projection1.value(), r3);
  } else {
    temps[temp_count++] = g.TempRegister(r3);
  }
  selector->Emit(code, output_count, outputs, arraysize(inputs), inputs,
                 temp_count, temps);
}
References arraysize, v8::internal::compiler::turboshaft::AtomicWord32PairOp::base(), v8::internal::compiler::turboshaft::OperationMatcher::Cast(), code, v8::internal::compiler::OperandGenerator::DefineAsFixed(), v8::internal::compiler::InstructionSelector::Emit(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::InstructionSelector::FindProjection(), v8::internal::compiler::turboshaft::AtomicWord32PairOp::index(), v8::internal::compiler::OperandGenerator::TempRegister(), v8::internal::compiler::OperandGenerator::UseUniqueRegister(), v8::internal::compiler::turboshaft::OptionalOpIndex::valid(), v8::internal::compiler::turboshaft::OptionalOpIndex::value(), v8::internal::compiler::turboshaft::AtomicWord32PairOp::value_high(), and v8::internal::compiler::turboshaft::AtomicWord32PairOp::value_low().
VisitRR()
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitRR (InstructionSelector * selector, InstructionCode opcode, OpIndex node)
Definition at line 91 of file instruction-selector-arm.cc.
                           {
  ArmOperandGenerator g(selector);
  const Operation& op = selector->Get(node);
  DCHECK_EQ(op.input_count, 1);
  selector->Emit(opcode, g.DefineAsRegister(node), g.UseRegister(op.input(0)));
}
References DCHECK_EQ, v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::InstructionSelector::Emit(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::turboshaft::Operation::input_count, and v8::internal::compiler::OperandGenerator::UseRegister().
VisitRRR()
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitRRR (InstructionSelector * selector, InstructionCode opcode, OpIndex node)
Definition at line 99 of file instruction-selector-arm.cc.
                            {
  ArmOperandGenerator g(selector);
  const Operation& op = selector->Get(node);
  DCHECK_EQ(op.input_count, 2);
  selector->Emit(opcode, g.DefineAsRegister(node), g.UseRegister(op.input(0)),
                 g.UseRegister(op.input(1)));
}
References DCHECK_EQ, v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::InstructionSelector::Emit(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::turboshaft::Operation::input_count, and v8::internal::compiler::OperandGenerator::UseRegister().
VisitShift() [1/2]
template<typename TryMatchShift >
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitShift (InstructionSelector * selector, OpIndex node, TryMatchShift try_match_shift)
Definition at line 1250 of file instruction-selector-arm.cc.
                                               {
  FlagsContinuation cont;
  VisitShift(selector, node, try_match_shift, &cont);
}
References v8::internal::compiler::VisitShift().
VisitShift() [2/2]
template<typename TryMatchShift >
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitShift (InstructionSelector * selector, OpIndex node, TryMatchShift try_match_shift, FlagsContinuation * cont)
Definition at line 1226 of file instruction-selector-arm.cc.
                                                                        {
  ArmOperandGenerator g(selector);
  InstructionCode opcode = kArmMov;
  InstructionOperand inputs[2];
  size_t input_count = 2;
  InstructionOperand outputs[1];
  size_t output_count = 0;
  CHECK(try_match_shift(selector, &opcode, node, &inputs[0], &inputs[1]));
  outputs[output_count++] = g.DefineAsRegister(node);
  DCHECK_NE(0u, input_count);
  DCHECK_NE(0u, output_count);
  DCHECK_GE(arraysize(inputs), input_count);
  DCHECK_GE(arraysize(outputs), output_count);
  DCHECK_NE(kMode_None, AddressingModeField::decode(opcode));
  selector->EmitWithContinuation(opcode, output_count, outputs, input_count,
                                 inputs, cont);
}
References arraysize, CHECK, DCHECK_GE, DCHECK_NE, v8::base::BitField< T, shift, size, U >::decode(), v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::InstructionSelector::EmitWithContinuation(), and v8::internal::compiler::turboshaft::detail::input_count().
VisitStoreCommon()
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitStoreCommon (InstructionSelector * selector, OpIndex node, StoreRepresentation store_rep, std::optional< AtomicMemoryOrder > atomic_order)
Definition at line 758 of file instruction-selector-arm.cc.
                                                                   {
  using OpIndex = OpIndex;
  ArmOperandGenerator g(selector);
  auto store_view = selector->store_view(node);
  OpIndex base = store_view.base();
  OpIndex index = store_view.index().value();
  OpIndex value = store_view.value();
  WriteBarrierKind write_barrier_kind = store_rep.write_barrier_kind();
  MachineRepresentation rep = store_rep.representation();
  if (v8_flags.enable_unconditional_write_barriers && CanBeTaggedPointer(rep)) {
    write_barrier_kind = kFullWriteBarrier;
  }
  if (write_barrier_kind != kNoWriteBarrier &&
      !v8_flags.disable_write_barriers) {
    DCHECK(CanBeTaggedPointer(rep));
    AddressingMode addressing_mode;
    InstructionOperand inputs[3];
    size_t input_count = 0;
    inputs[input_count++] = g.UseUniqueRegister(base);
    // OutOfLineRecordWrite uses the index in an 'add' instruction as well as
    // for the store itself, so we must check compatibility with both.
    if (g.CanBeImmediate(index, kArmAdd) && g.CanBeImmediate(index, kArmStr)) {
      inputs[input_count++] = g.UseImmediate(index);
      addressing_mode = kMode_Offset_RI;
    } else {
      inputs[input_count++] = g.UseUniqueRegister(index);
      addressing_mode = kMode_Offset_RR;
    }
    inputs[input_count++] = g.UseUniqueRegister(value);
    RecordWriteMode record_write_mode =
        WriteBarrierKindToRecordWriteMode(write_barrier_kind);
    InstructionCode code;
    if (!atomic_order) {
      code = kArchStoreWithWriteBarrier;
      code |= RecordWriteModeField::encode(record_write_mode);
    } else {
      code = kArchAtomicStoreWithWriteBarrier;
      code |= AtomicMemoryOrderField::encode(*atomic_order);
      code |= AtomicStoreRecordWriteModeField::encode(record_write_mode);
    }
    code |= AddressingModeField::encode(addressing_mode);
    selector->Emit(code, 0, nullptr, input_count, inputs);
  } else {
    InstructionCode opcode = kArchNop;
    if (!atomic_order) {
      opcode = GetStoreOpcode(rep);
    } else {
      // Release stores emit DMB ISH; STR while sequentially consistent stores
      // emit DMB ISH; STR; DMB ISH.
      // https://www.cl.cam.ac.uk/~pes20/cpp/cpp0xmappings.html
      opcode = GetAtomicStoreOpcode(rep);
      opcode |= AtomicMemoryOrderField::encode(*atomic_order);
    }
    std::optional<ExternalReference> external_base;
    {
      ExternalReference reference_value;
      if (selector->MatchExternalConstant(store_view.base(),
                                          &reference_value)) {
        external_base = reference_value;
      }
    }
    if (external_base &&
        selector->CanAddressRelativeToRootsRegister(*external_base)) {
      int64_t index_constant;
      if (selector->MatchSignedIntegralConstant(index, &index_constant)) {
        ptrdiff_t const delta =
            index_constant +
            MacroAssemblerBase::RootRegisterOffsetForExternalReference(
                selector->isolate(), *external_base);
        int input_count = 2;
        InstructionOperand inputs[2];
        inputs[0] = g.UseRegister(value);
        inputs[1] = g.UseImmediate(static_cast<int32_t>(delta));
        opcode |= AddressingModeField::encode(kMode_Root);
        selector->Emit(opcode, 0, nullptr, input_count, inputs);
        return;
      }
    }
    if (selector->Is<LoadRootRegisterOp>(base)) {
      int input_count = 2;
      InstructionOperand inputs[2];
      inputs[0] = g.UseRegister(value);
      inputs[1] = g.UseImmediate(index);
      opcode |= AddressingModeField::encode(kMode_Root);
      selector->Emit(opcode, 0, nullptr, input_count, inputs);
      return;
    }
    InstructionOperand inputs[4];
    size_t input_count = 0;
    inputs[input_count++] = g.UseRegister(value);
    inputs[input_count++] = g.UseRegister(base);
    EmitStore(selector, opcode, input_count, inputs, index);
  }
}
References v8::internal::compiler::InstructionSelector::CanAddressRelativeToRootsRegister(), v8::internal::compiler::ArmOperandGenerator::CanBeImmediate(), v8::internal::CanBeTaggedPointer(), code, v8::internal::DCHECK(), v8::internal::compiler::InstructionSelector::Emit(), EmitStore(), v8::base::BitField< T, shift, size, U >::encode(), GetAtomicStoreOpcode(), GetStoreOpcode(), v8::internal::index, v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::turboshaft::OperationMatcher::Is(), v8::internal::compiler::InstructionSelector::isolate(), v8::internal::compiler::kFullWriteBarrier, v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::turboshaft::OperationMatcher::MatchExternalConstant(), v8::internal::compiler::turboshaft::OperationMatcher::MatchSignedIntegralConstant(), v8::internal::compiler::turboshaft::OpIndex, v8::internal::compiler::StoreRepresentation::representation(), v8::internal::MacroAssemblerBase::RootRegisterOffsetForExternalReference(), v8::internal::compiler::InstructionSelector::store_view(), v8::internal::compiler::OperandGenerator::UseImmediate(), v8::internal::compiler::OperandGenerator::UseRegister(), v8::internal::compiler::OperandGenerator::UseUniqueRegister(), v8::internal::v8_flags, v8::internal::value, v8::internal::compiler::StoreRepresentation::write_barrier_kind(), and v8::internal::compiler::WriteBarrierKindToRecordWriteMode().
VisitWord32PairShift()
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitWord32PairShift (InstructionSelector * selector, InstructionCode opcode, OpIndex node)
Definition at line 1391 of file instruction-selector-arm.cc.
                                        {
  ArmOperandGenerator g(selector);
  const Word32PairBinopOp& pair_binop = selector->Cast<Word32PairBinopOp>(node);
  // We use g.UseUniqueRegister here to guarantee that there is
  // no register aliasing of input registers with output registers.
  InstructionOperand shift_operand;
  OpIndex shift_by = pair_binop.right_low();
  int64_t unused;
  if (selector->MatchSignedIntegralConstant(shift_by, &unused)) {
    shift_operand = g.UseImmediate(shift_by);
  } else {
    shift_operand = g.UseUniqueRegister(shift_by);
  }
  InstructionOperand inputs[] = {g.UseUniqueRegister(pair_binop.left_low()),
                                 g.UseUniqueRegister(pair_binop.left_high()),
                                 shift_operand};
  OptionalOpIndex projection1 = selector->FindProjection(node, 1);
  InstructionOperand outputs[2];
  InstructionOperand temps[1];
  int32_t output_count = 0;
  int32_t temp_count = 0;
  outputs[output_count++] = g.DefineAsRegister(node);
  if (projection1.valid()) {
    outputs[output_count++] = g.DefineAsRegister(projection1.value());
  } else {
    temps[temp_count++] = g.TempRegister();
  }
  selector->Emit(opcode, output_count, outputs, 3, inputs, temp_count, temps);
}
References v8::internal::compiler::turboshaft::OperationMatcher::Cast(), v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::InstructionSelector::Emit(), v8::internal::compiler::InstructionSelector::FindProjection(), v8::internal::compiler::turboshaft::Word32PairBinopOp::left_high(), v8::internal::compiler::turboshaft::Word32PairBinopOp::left_low(), v8::internal::compiler::turboshaft::OperationMatcher::MatchSignedIntegralConstant(), v8::internal::compiler::turboshaft::Word32PairBinopOp::right_low(), v8::internal::compiler::OperandGenerator::TempRegister(), v8::internal::compiler::OperandGenerator::UseImmediate(), v8::internal::compiler::OperandGenerator::UseUniqueRegister(), v8::internal::compiler::turboshaft::OptionalOpIndex::valid(), and v8::internal::compiler::turboshaft::OptionalOpIndex::value().
VisitWordCompare() [1/2]
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitWordCompare (InstructionSelector * selector, OpIndex node, FlagsContinuation * cont)
Definition at line 2098 of file instruction-selector-arm.cc.
                                               {
  InstructionCode opcode = kArmCmp;
  const ComparisonOp& comparison =
      selector->Get(node).template Cast<ComparisonOp>();
  const Operation& lhs = selector->Get(comparison.left());
  const Operation& rhs = selector->Get(comparison.right());
  FlagsCondition cond = cont->condition();
  if (selector->MatchIntegralZero(comparison.right()) &&
      (lhs.Is<Opmask::kWord32Add>() || lhs.Is<Opmask::kWord32BitwiseOr>() ||
       lhs.Is<Opmask::kWord32BitwiseAnd>() ||
       lhs.Is<Opmask::kWord32BitwiseXor>())) {
    // Emit flag setting instructions for comparisons against zero.
    if (CanUseFlagSettingBinop(cond)) {
      MaybeReplaceCmpZeroWithFlagSettingBinop(
          selector, &node, comparison.left(), &opcode, cond, cont);
    }
  } else if (selector->MatchIntegralZero(comparison.left()) &&
             (rhs.Is<Opmask::kWord32Add>() ||
              rhs.Is<Opmask::kWord32BitwiseOr>() ||
              rhs.Is<Opmask::kWord32BitwiseAnd>() ||
              rhs.Is<Opmask::kWord32BitwiseXor>())) {
    // Same as above, but we need to commute the condition before we
    // continue with the rest of the checks.
    cond = CommuteFlagsCondition(cond);
    if (CanUseFlagSettingBinop(cond)) {
      MaybeReplaceCmpZeroWithFlagSettingBinop(
          selector, &node, comparison.right(), &opcode, cond, cont);
    }
  }
  VisitWordCompare(selector, node, opcode, cont);
}
References CanUseFlagSettingBinop(), v8::internal::compiler::CommuteFlagsCondition(), v8::internal::compiler::FlagsContinuation::condition(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::compiler::turboshaft::ComparisonOp::left(), v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralZero(), MaybeReplaceCmpZeroWithFlagSettingBinop(), v8::internal::compiler::turboshaft::ComparisonOp::right(), and v8::internal::compiler::VisitWordCompare().
VisitWordCompare() [2/2]
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitWordCompare (InstructionSelector * selector, OpIndex node, InstructionCode opcode, FlagsContinuation * cont)
Definition at line 2043 of file instruction-selector-arm.cc.
                                                                       {
  ArmOperandGenerator g(selector);
  const Operation& op = selector->Get(node);
  OpIndex lhs = op.input(0);
  OpIndex rhs = op.input(1);
  InstructionOperand inputs[3];
  size_t input_count = 0;
  InstructionOperand outputs[2];
  size_t output_count = 0;
  bool has_result = (opcode != kArmCmp) && (opcode != kArmCmn) &&
                    (opcode != kArmTst) && (opcode != kArmTeq);
  if (TryMatchImmediateOrShift(selector, &opcode, rhs, &input_count,
                               &inputs[1])) {
    inputs[0] = g.UseRegister(lhs);
    input_count++;
  } else if (TryMatchImmediateOrShift(selector, &opcode, lhs, &input_count,
                                      &inputs[1])) {
    const Operation& op = selector->Get(node);
    if (const ComparisonOp* cmp = op.TryCast<ComparisonOp>()) {
      if (!ComparisonOp::IsCommutative(cmp->kind)) cont->Commute();
    } else if (const WordBinopOp* binop = op.TryCast<WordBinopOp>()) {
      if (!WordBinopOp::IsCommutative(binop->kind)) cont->Commute();
    } else {
      UNREACHABLE();
    }
    inputs[0] = g.UseRegister(rhs);
    input_count++;
  } else {
    opcode |= AddressingModeField::encode(kMode_Operand2_R);
    inputs[input_count++] = g.UseRegister(lhs);
    inputs[input_count++] = g.UseRegister(rhs);
  }
  if (has_result) {
    if (cont->IsDeoptimize()) {
      // If we can deoptimize as a result of the binop, we need to make sure
      // that the deopt inputs are not overwritten by the binop result. One
      // way to achieve that is to declare the output register as
      // same-as-first.
      outputs[output_count++] = g.DefineSameAsFirst(node);
    } else {
      outputs[output_count++] = g.DefineAsRegister(node);
    }
  }
  DCHECK_NE(0u, input_count);
  DCHECK_GE(arraysize(inputs), input_count);
  DCHECK_GE(arraysize(outputs), output_count);
  selector->EmitWithContinuation(opcode, output_count, outputs, input_count,
                                 inputs, cont);
}
References arraysize, v8::internal::compiler::FlagsContinuation::Commute(), DCHECK_GE, DCHECK_NE, v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::OperandGenerator::DefineSameAsFirst(), v8::internal::compiler::InstructionSelector::EmitWithContinuation(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::turboshaft::WordBinopOp::IsCommutative(), v8::internal::compiler::turboshaft::ComparisonOp::IsCommutative(), v8::internal::compiler::FlagsContinuation::IsDeoptimize(), v8::internal::compiler::turboshaft::Operation::TryCast(), TryMatchImmediateOrShift(), v8::internal::UNREACHABLE(), and v8::internal::compiler::OperandGenerator::UseRegister().