cppgc::subtle Namespace Reference
Classes
class HeapConsistency
DO NOT USE: Use the appropriate managed types.
class DisallowGarbageCollectionScope
Disallows garbage collection finalizations.
class NoGarbageCollectionScope
Avoids invoking garbage collection finalizations.
class HeapState
Helpers to peek into heap-internal state.
class TaggedUncompressedMember
struct ObjectSizeTrait
Trait specifying how to get the size of an object that was allocated using MakeGarbageCollected().
struct ObjectSizeTrait< T, false >
struct ObjectSizeTrait< T, true >
Typedefs
template<typename T >
using CrossThreadPersistent = internal::BasicCrossThreadPersistent< T, internal::StrongCrossThreadPersistentPolicy >
DO NOT USE: Has known caveats, see below.
template<typename T >
using WeakCrossThreadPersistent = internal::BasicCrossThreadPersistent< T, internal::WeakCrossThreadPersistentPolicy >
DO NOT USE: Has known caveats, see below.
template<typename T >
using UncompressedMember = internal::BasicMember< T, internal::StrongMemberTag, internal::DijkstraWriteBarrierPolicy, internal::DefaultMemberCheckingPolicy, internal::RawPointer >
UncompressedMember.
Functions
template<typename T >
void FreeUnreferencedObject (HeapHandle &heap_handle, T &object)
Informs the garbage collector that object can be immediately reclaimed.
template<typename T >
bool Resize (T &object, AdditionalBytes additional_bytes)
Tries to resize object of type T with additional bytes on top of sizeof(T).
Typedef Documentation
CrossThreadPersistent
template<typename T >
using cppgc::subtle::CrossThreadPersistent = typedef internal::BasicCrossThreadPersistent< T, internal::StrongCrossThreadPersistentPolicy>
DO NOT USE: Has known caveats, see below.
CrossThreadPersistent allows retaining objects from threads other than the thread the owning heap is operating on.
Known caveats:
Does not protect the heap owning an object from terminating.
Reaching transitively through the graph is unsupported as objects may be moved concurrently on the thread owning the object.
Definition at line 445 of file cross-thread-persistent.h.
UncompressedMember
template<typename T >
using cppgc::subtle::UncompressedMember = typedef internal::BasicMember< T, internal::StrongMemberTag, internal::DijkstraWriteBarrierPolicy, internal::DefaultMemberCheckingPolicy, internal::RawPointer>
UncompressedMember.
Use with care in hot paths that would otherwise cause many decompression cycles.
Definition at line 605 of file member.h.
WeakCrossThreadPersistent
template<typename T >
using cppgc::subtle::WeakCrossThreadPersistent = typedef internal::BasicCrossThreadPersistent< T, internal::WeakCrossThreadPersistentPolicy>
DO NOT USE: Has known caveats, see below.
CrossThreadPersistent allows weakly retaining objects from threads other than the thread the owning heap is operating on.
Known caveats:
Does not protect the heap owning an object from terminating.
Reaching transitively through the graph is unsupported as objects may be moved concurrently on the thread owning the object.
Definition at line 460 of file cross-thread-persistent.h.
Function Documentation
FreeUnreferencedObject()
template<typename T >
void cppgc::subtle::FreeUnreferencedObject (HeapHandle & heap_handle, T & object)
Informs the garbage collector that object can be immediately reclaimed.
The destructor may not be invoked immediately but only on next garbage collection.
It is up to the embedder to guarantee that no other object holds a reference to object after calling FreeUnreferencedObject(). In case such a reference exists, it's use results in a use-after-free.
To aid in using the API, FreeUnreferencedObject() may be called from destructors on objects that would be reclaimed in the same garbage collection cycle.
Parameters
heap_handle The corresponding heap.
object Reference to an object that is of type GarbageCollected and should be immediately reclaimed.
Definition at line 61 of file explicit-management.h.
                                                                {
  static_assert(IsGarbageCollectedTypeV<T>,
                "Object must be of type GarbageCollected.");
  internal::ExplicitManagementImpl::FreeUnreferencedObject(heap_handle,
                                                           &object);
}
References cppgc::internal::ExplicitManagementImpl::FreeUnreferencedObject().
Resize()
template<typename T >
bool cppgc::subtle::Resize (T & object, AdditionalBytes additional_bytes)
Tries to resize object of type T with additional bytes on top of sizeof(T).
Resizing is only useful with trailing inlined storage, see e.g. MakeGarbageCollected(AllocationHandle&, AdditionalBytes).
Resize() performs growing or shrinking as needed and may skip the operation for internal reasons, see return value.
It is up to the embedder to guarantee that in case of shrinking a larger object down, the reclaimed area is not used anymore. Any subsequent use results in a use-after-free.
The object must be live when calling Resize().
Parameters
object Reference to an object that is of type GarbageCollected and should be resized.
additional_bytes Bytes in addition to sizeof(T) that the object should provide.
Returns
true when the operation was successful and the result can be relied on, and false otherwise.
Definition at line 90 of file explicit-management.h.
                                                         {
  static_assert(IsGarbageCollectedTypeV<T>,
                "Object must be of type GarbageCollected.");
  return internal::ExplicitManagementImpl::Resize(
      &object, sizeof(T) + additional_bytes.value);
}
References cppgc::internal::ExplicitManagementImpl::Resize(), and cppgc::AdditionalBytes::value.
Referenced by v8::internal::ZoneList< T >::AddAll(), v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::FillEmptyEntry(), and v8::internal::ZoneList< T >::ResizeAddInternal().