v8::internal::compiler::anonymous_namespace{register-allocator.cc} Namespace Reference
Functions
const InstructionBlock * GetContainingLoop (const InstructionSequence *sequence, const InstructionBlock *block)
const InstructionBlock * GetInstructionBlock (const InstructionSequence *code, LifetimePosition pos)
Instruction * GetLastInstruction (InstructionSequence *code, const InstructionBlock *block)
void PrintBlockRow (std::ostream &os, const InstructionBlocks &blocks)
Variables
static constexpr int kFloat32Bit
static constexpr int kSimd128Bit
Function Documentation
GetContainingLoop()
const InstructionBlock* v8::internal::compiler::anonymous_namespace{register-allocator.cc}::GetContainingLoop (const InstructionSequence * sequence, const InstructionBlock * block)
Definition at line 37 of file register-allocator.cc.
                                                                         {
  RpoNumber index = block->loop_header();
  if (!index.IsValid()) return nullptr;
  return sequence->InstructionBlockAt(index);
}
References v8::internal::index, v8::internal::compiler::InstructionSequence::InstructionBlockAt(), and v8::internal::compiler::InstructionBlock::loop_header().
Referenced by v8::internal::compiler::RegisterAllocator::FindOptimalSpillingPos(), and v8::internal::compiler::RegisterAllocator::FindOptimalSplitPos().
GetInstructionBlock()
const InstructionBlock* v8::internal::compiler::anonymous_namespace{register-allocator.cc}::GetInstructionBlock (const InstructionSequence * code, LifetimePosition pos)
Definition at line 44 of file register-allocator.cc.
                                                                  {
  return code->GetInstructionBlock(pos.ToInstructionIndex());
}
References code, and v8::internal::compiler::LifetimePosition::ToInstructionIndex().
Referenced by v8::internal::compiler::LiveRangeConnector::ConnectRanges(), v8::internal::compiler::OperandAssigner::DecideSpillingMode(), v8::internal::compiler::RegisterAllocator::FindOptimalSpillingPos(), v8::internal::compiler::RegisterAllocator::FindOptimalSplitPos(), v8::internal::compiler::RegisterAllocationData::RangesDefinedInDeferredStayInDeferred(), v8::internal::compiler::LiveRangeConnector::ResolveControlFlow(), v8::internal::compiler::RegisterAllocator::Spill(), v8::internal::compiler::LinearScanAllocator::SpillBetweenUntil(), and v8::internal::compiler::RegisterAllocator::SplitRangeAt().
GetLastInstruction()
Instruction* v8::internal::compiler::anonymous_namespace{register-allocator.cc}::GetLastInstruction (InstructionSequence * code, const InstructionBlock * block)
Definition at line 49 of file register-allocator.cc.
                                                               {
  return code->InstructionAt(block->last_instruction_index());
}
References code, and v8::internal::compiler::InstructionBlock::last_instruction_index().
Referenced by v8::internal::compiler::LiveRangeBuilder::ProcessPhis().
PrintBlockRow()
void v8::internal::compiler::anonymous_namespace{register-allocator.cc}::PrintBlockRow (std::ostream & os, const InstructionBlocks & blocks)
Definition at line 938 of file register-allocator.cc.
                                                                    {
  os << " ";
  for (auto block : blocks) {
    LifetimePosition start_pos = LifetimePosition::GapFromInstructionIndex(
        block->first_instruction_index());
    LifetimePosition end_pos = LifetimePosition::GapFromInstructionIndex(
                                   block->last_instruction_index())
                                   .NextFullStart();
    int length = end_pos.value() - start_pos.value();
    constexpr int kMaxPrefixLength = 32;
    char buffer[kMaxPrefixLength];
    int rpo_number = block->rpo_number().ToInt();
    const char* deferred_marker = block->IsDeferred() ? "(deferred)" : "";
    int max_prefix_length = std::min(length, kMaxPrefixLength);
    int prefix = snprintf(buffer, max_prefix_length, "[-B%d-%s", rpo_number,
                          deferred_marker);
    os << buffer;
    int remaining = length - std::min(prefix, max_prefix_length) - 1;
    for (int i = 0; i < remaining; ++i) os << '-';
    os << ']';
  }
  os << '\n';
}
References v8::internal::compiler::LifetimePosition::GapFromInstructionIndex(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::length, v8::internal::compiler::LifetimePosition::NextFullStart(), and v8::internal::compiler::LifetimePosition::value().
Referenced by v8::internal::compiler::LinearScanAllocator::PrintRangeOverview().
Variable Documentation
kFloat32Bit
constexpr int v8::internal::compiler::anonymous_namespace{register-allocator.cc}::kFloat32Bit [static], [constexpr]
Initial value:
=
    RepresentationBit(MachineRepresentation::kFloat32)
Definition at line 32 of file register-allocator.cc.
Referenced by v8::internal::compiler::LiveRangeBuilder::ProcessInstructions(), and v8::internal::compiler::RegisterAllocator::RegisterAllocator().
kSimd128Bit
constexpr int v8::internal::compiler::anonymous_namespace{register-allocator.cc}::kSimd128Bit [static], [constexpr]
Initial value:
=
    RepresentationBit(MachineRepresentation::kSimd128)
Definition at line 34 of file register-allocator.cc.
Referenced by v8::internal::compiler::LiveRangeBuilder::ProcessInstructions(), and v8::internal::compiler::RegisterAllocator::RegisterAllocator().