v8::internal::wasm::anonymous_namespace{module-decoder.cc} Namespace Reference
Classes
class ValidateFunctionsTask
Enumerations
enum class EmptyNames : bool { kAllow
, kSkip
 }
Functions
bool FindNameSection (Decoder *decoder)
void DecodeNameMapInternal (NameMap &target, Decoder &decoder, EmptyNames empty_names=EmptyNames::kSkip)
void DecodeNameMap (NameMap &target, Decoder &decoder, uint32_t subsection_payload_length, EmptyNames empty_names=EmptyNames::kSkip)
void DecodeIndirectNameMap (IndirectNameMap &target, Decoder &decoder, uint32_t subsection_payload_length)
Enumeration Type Documentation
EmptyNames
enum v8::internal::wasm::anonymous_namespace{module-decoder.cc}::EmptyNames : bool [strong]
Enumerator
kAllow
kSkip
Definition at line 338 of file module-decoder.cc.
: bool { kAllow, kSkip };
Function Documentation
DecodeIndirectNameMap()
void v8::internal::wasm::anonymous_namespace{module-decoder.cc}::DecodeIndirectNameMap (IndirectNameMap & target, Decoder & decoder, uint32_t subsection_payload_length)
Definition at line 366 of file module-decoder.cc.
                                                               {
  if (target.is_set()) {
    decoder.consume_bytes(subsection_payload_length);
    return;
  }
  uint32_t outer_count = decoder.consume_u32v("outer count");
  for (uint32_t i = 0; i < outer_count; ++i) {
    uint32_t outer_index = decoder.consume_u32v("outer index");
    // TODO(jkummerow): Should we try to skip only the invalid entry?
    if (outer_index > IndirectNameMap::kMaxKey) break;
    NameMap names;
    DecodeNameMapInternal(names, decoder);
    target.Put(outer_index, std::move(names));
    if (!decoder.ok()) break;
  }
  target.FinishInitialization();
}
References v8::internal::wasm::Decoder::consume_bytes(), v8::internal::wasm::Decoder::consume_u32v(), DecodeNameMapInternal(), v8::internal::wasm::AdaptiveMap< Value >::FinishInitialization(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::AdaptiveMap< Value >::is_set(), v8::internal::wasm::AdaptiveMap< AdaptiveMap< WireBytesRef > >::kMaxKey, v8::internal::wasm::Decoder::ok(), and v8::internal::wasm::AdaptiveMap< Value >::Put().
Referenced by v8::internal::wasm::DecodedNameSection::DecodedNameSection().
DecodeNameMap()
void v8::internal::wasm::anonymous_namespace{module-decoder.cc}::DecodeNameMap (NameMap & target, Decoder & decoder, uint32_t subsection_payload_length, EmptyNames empty_names = EmptyNames::kSkip)
Definition at line 356 of file module-decoder.cc.
                                                             {
  if (target.is_set()) {
    decoder.consume_bytes(subsection_payload_length);
    return;
  }
  DecodeNameMapInternal(target, decoder, empty_names);
}
References v8::internal::wasm::Decoder::consume_bytes(), DecodeNameMapInternal(), and v8::internal::wasm::AdaptiveMap< Value >::is_set().
Referenced by v8::internal::wasm::DecodedNameSection::DecodedNameSection().
DecodeNameMapInternal()
void v8::internal::wasm::anonymous_namespace{module-decoder.cc}::DecodeNameMapInternal (NameMap & target, Decoder & decoder, EmptyNames empty_names = EmptyNames::kSkip)
Definition at line 340 of file module-decoder.cc.
                                                                     {
  uint32_t count = decoder.consume_u32v("names count");
  for (uint32_t i = 0; i < count; i++) {
    uint32_t index = decoder.consume_u32v("index");
    WireBytesRef name =
        consume_string(&decoder, unibrow::Utf8Variant::kLossyUtf8, "name");
    if (!decoder.ok()) break;
    if (index > NameMap::kMaxKey) continue;
    if (empty_names == EmptyNames::kSkip && name.is_empty()) continue;
    if (!validate_utf8(&decoder, name)) continue;
    target.Put(index, name);
  }
  target.FinishInitialization();
}
References v8::internal::wasm::consume_string(), v8::internal::wasm::Decoder::consume_u32v(), v8::internal::wasm::AdaptiveMap< Value >::FinishInitialization(), v8::internal::index, unibrow::kLossyUtf8, v8::internal::wasm::AdaptiveMap< WireBytesRef >::kMaxKey, v8::internal::wasm::name(), v8::internal::wasm::Decoder::ok(), v8::internal::wasm::AdaptiveMap< Value >::Put(), and v8::internal::wasm::validate_utf8().
Referenced by v8::internal::wasm::DecodeFunctionNames(), DecodeIndirectNameMap(), and DecodeNameMap().
FindNameSection()
bool v8::internal::wasm::anonymous_namespace{module-decoder.cc}::FindNameSection (Decoder * decoder)
Definition at line 321 of file module-decoder.cc.
                                       {
  static constexpr int kModuleHeaderSize = 8;
  decoder->consume_bytes(kModuleHeaderSize, "module header");
  WasmSectionIterator section_iter(decoder, ITracer::NoTrace);
  while (decoder->ok() && section_iter.more() &&
         section_iter.section_code() != kNameSectionCode) {
    section_iter.advance(true);
  }
  if (!section_iter.more()) return false;
  // Reset the decoder to not read beyond the name section end.
  decoder->Reset(section_iter.payload(), decoder->pc_offset());
  return true;
}
References v8::internal::wasm::WasmSectionIterator::advance(), v8::internal::wasm::Decoder::consume_bytes(), v8::internal::wasm::kNameSectionCode, v8::internal::wasm::WasmSectionIterator::more(), v8::internal::wasm::ITracer::NoTrace, v8::internal::wasm::Decoder::ok(), v8::internal::wasm::WasmSectionIterator::payload(), v8::internal::wasm::Decoder::pc_offset(), v8::internal::wasm::Decoder::Reset(), and v8::internal::wasm::WasmSectionIterator::section_code().
Referenced by v8::internal::wasm::DecodeCanonicalTypeNames(), and v8::internal::wasm::DecodeFunctionNames().