v8::bigint::anonymous_namespace{div-burnikel.cc} Namespace Reference
Classes
class BZ
Functions
int SpecialCompare (digit_t a_high, Digits A, Digits B)
void SetOnes (RWDigits X)
Function Documentation
SetOnes()
void v8::bigint::anonymous_namespace{div-burnikel.cc}::SetOnes (RWDigits X)
Definition at line 49 of file div-burnikel.cc.
                         {
  memset(X.digits(), 0xFF, X.len() * sizeof(digit_t));
}
References X().
Referenced by v8::bigint::anonymous_namespace{div-burnikel.cc}::BZ::D3n2n().
SpecialCompare()
int v8::bigint::anonymous_namespace{div-burnikel.cc}::SpecialCompare (digit_t a_high, Digits A, Digits B)
Definition at line 27 of file div-burnikel.cc.
                                                       {
  B.Normalize();
  int a_len;
  if (a_high == 0) {
    A.Normalize();
    a_len = A.len();
  } else {
    a_len = A.len() + 1;
  }
  int diff = a_len - B.len();
  if (diff != 0) return diff;
  int i = a_len - 1;
  if (a_high != 0) {
    if (a_high > B[i]) return 1;
    if (a_high < B[i]) return -1;
    i--;
  }
  while (i >= 0 && A[i] == B[i]) i--;
  if (i < 0) return 0;
  return A[i] > B[i] ? 1 : -1;
}
References v8::internal::A, v8::internal::B, and v8::internal::anonymous_namespace{json-stringifier.cc}::i.
Referenced by v8::bigint::anonymous_namespace{div-burnikel.cc}::BZ::D3n2n().