v8::internal::anonymous_namespace{regexp-macro-assembler.cc} Namespace Reference
Functions
uint32_t Hash (const ZoneList< CharacterRange > *ranges)
constexpr base::uc32 MaskEndOfRangeMarker (base::uc32 c)
int RangeArrayLengthFor (const ZoneList< CharacterRange > *ranges)
bool Equals (const ZoneList< CharacterRange > *lhs, const DirectHandle< FixedUInt16Array > &rhs)
Handle< FixedUInt16Array > MakeRangeArray (Isolate *isolate, const ZoneList< CharacterRange > *ranges)
Function Documentation
Equals()
bool v8::internal::anonymous_namespace{regexp-macro-assembler.cc}::Equals (const ZoneList< CharacterRange > * lhs, const DirectHandle< FixedUInt16Array > & rhs)
Definition at line 132 of file regexp-macro-assembler.cc.
                                                       {
  const int rhs_length = rhs->length();
  if (rhs_length != RangeArrayLengthFor(lhs)) return false;
  for (int i = 0; i < lhs->length(); i++) {
    const CharacterRange& r = lhs->at(i);
    if (rhs->get(i * 2 + 0) != r.from()) return false;
    if (i * 2 + 1 == rhs_length) break;
    if (rhs->get(i * 2 + 1) != r.to() + 1) return false;
  }
  return true;
}
References v8::internal::ZoneList< T >::at(), v8::internal::CharacterRange::from(), v8::internal::ZoneList< T >::length(), RangeArrayLengthFor(), and v8::internal::CharacterRange::to().
Referenced by v8::internal::NativeRegExpMacroAssembler::GetOrAddRangeArray().
Hash()
uint32_t v8::internal::anonymous_namespace{regexp-macro-assembler.cc}::Hash (const ZoneList< CharacterRange > * ranges)
Definition at line 109 of file regexp-macro-assembler.cc.
                                                      {
  size_t seed = 0;
  for (int i = 0; i < ranges->length(); i++) {
    const CharacterRange& r = ranges->at(i);
    seed = base::hash_combine(seed, r.from(), r.to());
  }
  return static_cast<uint32_t>(seed);
}
References v8::internal::ZoneList< T >::at(), v8::internal::CharacterRange::from(), v8::base::hash_combine(), v8::internal::ZoneList< T >::length(), and v8::internal::CharacterRange::to().
MakeRangeArray()
Handle<FixedUInt16Array> v8::internal::anonymous_namespace{regexp-macro-assembler.cc}::MakeRangeArray (Isolate * isolate, const ZoneList< CharacterRange > * ranges)
Definition at line 145 of file regexp-macro-assembler.cc.
                                                              {
  const int ranges_length = ranges->length();
  const int range_array_length = RangeArrayLengthFor(ranges);
  Handle<FixedUInt16Array> range_array =
      FixedUInt16Array::New(isolate, range_array_length);
  for (int i = 0; i < ranges_length; i++) {
    const CharacterRange& r = ranges->at(i);
    DCHECK_LE(r.from(), kMaxUInt16);
    range_array->set(i * 2 + 0, r.from());
    const base::uc32 to = MaskEndOfRangeMarker(r.to());
    if (i == ranges_length - 1 && to == kMaxUInt16) {
      DCHECK_EQ(range_array_length, ranges_length * 2 - 1);
      break; // Avoid overflow by leaving the last range open-ended.
    }
    DCHECK_LT(to, kMaxUInt16);
    range_array->set(i * 2 + 1, to + 1); // Exclusive.
  }
  return range_array;
}
References v8::internal::ZoneList< T >::at(), DCHECK_EQ, DCHECK_LE, DCHECK_LT, v8::internal::CharacterRange::from(), v8::internal::kMaxUInt16, v8::internal::ZoneList< T >::length(), MaskEndOfRangeMarker(), v8::internal::FixedIntegerArrayBase< T, Base >::New(), RangeArrayLengthFor(), and v8::internal::CharacterRange::to().
Referenced by v8::internal::NativeRegExpMacroAssembler::GetOrAddRangeArray().
MaskEndOfRangeMarker()
constexpr base::uc32 v8::internal::anonymous_namespace{regexp-macro-assembler.cc}::MaskEndOfRangeMarker (base::uc32 c) [constexpr]
Definition at line 118 of file regexp-macro-assembler.cc.
                                                    {
  // CharacterRanges may use 0x10ffff as the end-of-range marker irrespective
  // of whether the regexp IsUnicode or not; translate the marker value here.
  DCHECK_IMPLIES(c > kMaxUInt16, c == String::kMaxCodePoint);
  return c & 0xffff;
}
References DCHECK_IMPLIES, v8::internal::String::kMaxCodePoint, and v8::internal::kMaxUInt16.
Referenced by MakeRangeArray(), and RangeArrayLengthFor().
RangeArrayLengthFor()
int v8::internal::anonymous_namespace{regexp-macro-assembler.cc}::RangeArrayLengthFor (const ZoneList< CharacterRange > * ranges)
Definition at line 125 of file regexp-macro-assembler.cc.
                                                                {
  const int ranges_length = ranges->length();
  return MaskEndOfRangeMarker(ranges->at(ranges_length - 1).to()) == kMaxUInt16
             ? ranges_length * 2 - 1
             : ranges_length * 2;
}
References v8::internal::ZoneList< T >::at(), v8::internal::kMaxUInt16, v8::internal::ZoneList< T >::length(), and MaskEndOfRangeMarker().
Referenced by Equals(), and MakeRangeArray().