v8::internal::anonymous_namespace{scopes.cc} Namespace Reference
Functions
bool WasLazilyParsed (Scope *scope)
void SetNeedsHoleCheck (Variable *var, VariableProxy *proxy, Variable::ForceHoleInitializationFlag flag)
void UpdateNeedsHoleCheck (Variable *var, VariableProxy *proxy, Scope *scope)
Function Documentation
SetNeedsHoleCheck()
void v8::internal::anonymous_namespace{scopes.cc}::SetNeedsHoleCheck (Variable * var, VariableProxy * proxy, Variable::ForceHoleInitializationFlag flag)
Definition at line 2285 of file scopes.cc.
                                                                 {
  proxy->set_needs_hole_check();
  var->ForceHoleInitialization(flag);
}
References v8::internal::Variable::ForceHoleInitialization(), and v8::internal::VariableProxy::set_needs_hole_check().
Referenced by UpdateNeedsHoleCheck().
UpdateNeedsHoleCheck()
void v8::internal::anonymous_namespace{scopes.cc}::UpdateNeedsHoleCheck (Variable * var, VariableProxy * proxy, Scope * scope)
Definition at line 2291 of file scopes.cc.
                                                                             {
  if (var->mode() == VariableMode::kDynamicLocal) {
    // Dynamically introduced variables never need a hole check (since they're
    // VariableMode::kVar bindings, either from var or function declarations),
    // but the variable they shadow might need a hole check, which we want to do
    // if we decide that no shadowing variable was dynamically introduced.
    DCHECK_EQ(kCreatedInitialized, var->initialization_flag());
    return UpdateNeedsHoleCheck(var->local_if_not_shadowed(), proxy, scope);
  }
  if (var->initialization_flag() == kCreatedInitialized) return;
  // It's impossible to eliminate module import hole checks here, because it's
  // unknown at compilation time whether the binding referred to in the
  // exporting module itself requires hole checks.
  if (var->location() == VariableLocation::MODULE && !var->IsExport()) {
    SetNeedsHoleCheck(var, proxy, Variable::kHasHoleCheckUseInUnknownScope);
    return;
  }
  // Check if the binding really needs an initialization check. The check
  // can be skipped in the following situation: we have a VariableMode::kLet or
  // VariableMode::kConst binding, both the Variable and the VariableProxy have
  // the same declaration scope (i.e. they are both in global code, in the same
  // function or in the same eval code), the VariableProxy is in the source
  // physically located after the initializer of the variable, and that the
  // initializer cannot be skipped due to a nonlinear scope.
  //
  // The condition on the closure scopes is a conservative check for
  // nested functions that access a binding and are called before the
  // binding is initialized:
  // function() { f(); let x = 1; function f() { x = 2; } }
  //
  // The check cannot be skipped on non-linear scopes, namely switch
  // scopes, to ensure tests are done in cases like the following:
  // switch (1) { case 0: let x = 2; case 1: f(x); }
  // The scope of the variable needs to be checked, in case the use is
  // in a sub-block which may be linear.
  if (var->scope()->GetClosureScope() != scope->GetClosureScope()) {
    SetNeedsHoleCheck(var, proxy,
                      Variable::kHasHoleCheckUseInDifferentClosureScope);
    return;
  }
  // We should always have valid source positions.
  DCHECK_NE(var->initializer_position(), kNoSourcePosition);
  DCHECK_NE(proxy->position(), kNoSourcePosition);
  if (var->scope()->is_nonlinear() ||
      var->initializer_position() >= proxy->position()) {
    SetNeedsHoleCheck(var, proxy, Variable::kHasHoleCheckUseInSameClosureScope);
    return;
  }
}
References DCHECK_EQ, DCHECK_NE, v8::internal::Scope::GetClosureScope(), v8::internal::Variable::initialization_flag(), v8::internal::Variable::initializer_position(), v8::internal::Scope::is_nonlinear(), v8::internal::Variable::IsExport(), v8::internal::kCreatedInitialized, v8::internal::kDynamicLocal, v8::internal::Variable::kHasHoleCheckUseInDifferentClosureScope, v8::internal::Variable::kHasHoleCheckUseInSameClosureScope, v8::internal::Variable::kHasHoleCheckUseInUnknownScope, v8::internal::kNoSourcePosition, v8::internal::Variable::local_if_not_shadowed(), v8::internal::Variable::location(), v8::internal::Variable::mode(), v8::internal::MODULE, v8::internal::AstNode::position(), v8::internal::Variable::scope(), and SetNeedsHoleCheck().
Referenced by v8::internal::Scope::ResolveTo().
WasLazilyParsed()
bool v8::internal::anonymous_namespace{scopes.cc}::WasLazilyParsed (Scope * scope)
Definition at line 1584 of file scopes.cc.
                                   {
  return scope->is_declaration_scope() &&
         scope->AsDeclarationScope()->was_lazily_parsed();
}
References v8::internal::Scope::AsDeclarationScope(), v8::internal::Scope::is_declaration_scope(), and v8::internal::DeclarationScope::was_lazily_parsed().
Referenced by v8::internal::Scope::AllocateVariablesRecursively(), v8::internal::Scope::AnalyzePartially(), and v8::internal::Scope::ResolveVariablesRecursively().