v8::internal::compiler::turboshaft Namespace Reference
Namespaces
 anonymous_namespace{decompression-optimization.cc}
 anonymous_namespace{graph-builder.cc}
 anonymous_namespace{instruction-selection-phase.cc}
 anonymous_namespace{late-load-elimination-reducer.cc}
 anonymous_namespace{loop-unrolling-reducer.cc}
 anonymous_namespace{operations.cc}
 anonymous_namespace{pretenuring-propagation-reducer.cc}
 anonymous_namespace{turbolev-graph-builder.cc}
 anonymous_namespace{types.cc}
 detail
 details
 Opmask
 wle
Classes
class CompareSequence
class CompareChainNode
struct FieldAccessTS
struct ElementAccessTS
class AccessBuilderTS
class AnalyzerIterator
class CatchScopeImpl
class Range
class IndexRange
class Sequence
class Zip
class ConditionWithHint
class LabelBase
class Label
class LoopLabel
class TurboshaftAssemblerOpInterface
class Uninitialized
class GraphVisitor
class ValueNumberingReducer
class EmitProjectionReducer
struct StackBottom
struct ReducerStack
class GenericReducerBase
class Var
class ScopedVar
class TSReducerBase
class ReducerBaseForwarder
class GenericAssemblerOpInterface
struct AssemblerData
class Assembler
class TSAssembler
class AssertTypesReducer
struct BlockInstrumentationPhase
class BlockInstrumentationReducer
class VariableReducer
class BranchEliminationReducer
struct BuildGraphPhase
struct BuiltinCallDescriptor
struct BytecodeHandlerData
struct CodeEliminationAndSimplificationPhase
struct PaddingSpace
class WasmRevecReducer
class OutputGraphAssembler
class CopyingPhaseImpl
class CopyingPhase
struct CsaBranchEliminationPhase
struct CsaEarlyMachineOptimizationPhase
struct CallView
struct CsaEffectsComputationPhase
struct CsaLateEscapeAnalysisPhase
struct CsaLoadEliminationPhase
struct CsaMemoryOptimizationPhase
class DataViewLoweringReducer
struct ControlState
struct OperationState
class DeadCodeAnalysis
class DeadCodeEliminationReducer
struct DebugFeatureLoweringPhase
class DebugFeatureLoweringReducer
struct DecompressionOptimizationPhase
struct FrameStateData
class DuplicationOptimizationReducer
class ExplicitTruncationReducer
class FastApiCallLoweringReducer
struct fast_hash
struct fast_hash< std::optional< T > >
struct fast_hash< std::pair< T1, T2 > >
struct fast_hash< std::tuple< Ts... > >
struct fast_hash< base::Vector< T > >
struct TurboshaftGraphAsJSON
class JSONTurboshaftGraphWriter
class OperationBuffer
class DominatorForwardTreeNode
class RandomAccessStackDominatorNode
class PredecessorIterator
class NeighboringPredecessorIterable
class Block
class Graph
struct PrintAsBlockHeader
class GrowableStacksReducer
class IfElseCascadeToSwitchReducer
class ConstOrV
class OpIndex
class OptionalOpIndex
struct nullrep_t
struct Any
struct None
struct WordWithBits
struct FloatWithBits
struct Compressed
struct InternalTag
struct FrameState
struct UntaggedUnion
struct Tuple
struct v_traits
struct v_traits< Any >
struct v_traits< None >
struct v_traits< Compressed >
struct v_traits< Word32 >
struct v_traits< Word64 >
struct v_traits< Float32 >
struct v_traits< Float64 >
struct v_traits< Simd128 >
struct v_traits< Simd256 >
struct v_traits< T, std::enable_if_t< is_taggable_v< T > &&!is_union_v< T > > >
struct v_traits< Union< T, Ts... > >
struct v_traits< UntaggedUnion< Ts... > >
struct v_traits< T, std::enable_if_t< std::is_base_of_v< InternalTag, T > > >
struct v_traits< Tuple< Ts... > >
class V
class OptionalV
struct fast_hash< OpIndex >
class ShadowyOpIndex
class ShadowyOpIndexVectorWrapper
class BlockIndex
struct fast_hash< BlockIndex >
class InstructionSelectionNormalizationReducer
class TurboshaftSpecialRPONumberer
struct ProfileApplicationPhase
struct SpecialRPOSchedulingPhase
struct InstructionSelectionPhase
struct Int64LoweringPhase
class Int64LoweringReducer
class JSGenericLoweringReducer
class LateEscapeAnalysisAnalyzer
class LateEscapeAnalysisReducer
struct MapMaskAndOr
struct MemoryAddress
struct KeyData
struct OffsetListTraits
struct BaseListTraits
struct BaseData
class LoadEliminationReplacement
class MemoryContentTable
class LateLoadEliminationAnalyzer
class LateLoadEliminationReducer
class LayeredHashMap
struct LoadStoreSimplificationConfiguration
class LoadStoreSimplificationReducer
class LoopFinder
struct LoopPeelingPhase
class LoopUnrollingReducer
class LoopPeelingReducer
struct LoopUnrollingPhase
class IterationCount
class StaticCanonicalForLoopMatcher
class LoopUnrollingAnalyzer
class LoopStackCheckElisionReducer
struct MachineLoweringPhase
class MachineLoweringReducer
class MachineOptimizationReducer
struct MemoryAnalyzer
class MemoryOptimizationReducer
class OperationMatcher
struct VariableData
struct operation_to_opcode
struct OpMaskT
class InputsRepFactory
struct EffectDimensions
struct OpEffects
class SaturatedUint8
struct underlying_operation
struct underlying_operation< OpMaskT< T, M, V > >
struct Operation
struct OperationPrintStyle
struct HasStaticEffects
struct HasStaticEffects< Op, std::void_t< decltype(Op::effects)> >
struct OperationT
struct FixedArityOperationT
class SupportedOperations
struct DeadOp
struct AbortCSADcheckOp
struct GenericBinopOp
struct GenericUnopOp
struct ToNumberOrNumericOp
struct Word32SignHintOp
struct WordBinopOp
struct FloatBinopOp
struct Word32PairBinopOp
struct WordBinopDeoptOnOverflowOp
struct OverflowCheckedBinopOp
struct WordUnaryOp
struct OverflowCheckedUnaryOp
struct FloatUnaryOp
struct ShiftOp
struct ComparisonOp
struct ChangeOp
struct ChangeOrDeoptOp
struct TryChangeOp
struct BitcastWord32PairToFloat64Op
struct TaggedBitcastOp
struct SelectOp
struct PhiOp
struct PendingLoopPhiOp
struct ConstantOp
struct LoadOp
struct AtomicRMWOp
struct AtomicWord32PairOp
struct MemoryBarrierOp
struct StoreOp
struct AllocateOp
struct DecodeExternalPointerOp
struct JSStackCheckOp
struct RetainOp
struct StackPointerGreaterThanOp
struct StackSlotOp
struct FrameConstantOp
struct FrameStateOp
struct DeoptimizeOp
struct DeoptimizeIfOp
struct StaticAssertOp
struct ParameterOp
struct OsrValueOp
struct TSCallDescriptor
struct fast_hash< TSCallDescriptor >
struct CallOp
struct CheckExceptionOp
struct CatchBlockBeginOp
struct DidntThrowOp
struct TailCallOp
struct UnreachableOp
struct ReturnOp
struct GotoOp
struct BranchOp
struct SwitchOp
struct fast_hash< SwitchOp::Case >
struct TupleOp
struct ProjectionOp
struct CheckTurboshaftTypeOfOp
struct ObjectIsOp
struct Float64IsOp
struct ObjectIsNumericValueOp
struct ConvertOp
struct ConvertUntaggedToJSPrimitiveOp
struct ConvertUntaggedToJSPrimitiveOrDeoptOp
struct ConvertJSPrimitiveToUntaggedOp
struct ConvertJSPrimitiveToUntaggedOrDeoptOp
struct TruncateJSPrimitiveToUntaggedOp
struct TruncateJSPrimitiveToUntaggedOrDeoptOp
struct ConvertJSPrimitiveToObjectOp
struct NewConsStringOp
struct NewArrayOp
struct DoubleArrayMinMaxOp
struct LoadFieldByIndexOp
struct DebugBreakOp
struct DebugPrintOp
struct BigIntBinopOp
struct BigIntComparisonOp
struct BigIntUnaryOp
struct LoadRootRegisterOp
struct StringAtOp
struct StringLengthOp
struct TypedArrayLengthOp
struct StringIndexOfOp
struct StringFromCodePointAtOp
struct StringSubstringOp
struct StringConcatOp
struct StringComparisonOp
struct StringOrOddballStrictEqualOp
struct ArgumentsLengthOp
struct NewArgumentsElementsOp
struct LoadTypedElementOp
struct LoadDataViewElementOp
struct LoadStackArgumentOp
struct StoreTypedElementOp
struct StoreDataViewElementOp
struct TransitionAndStoreArrayElementOp
struct CompareMapsOp
struct CheckMapsOp
struct AssumeMapOp
struct CheckedClosureOp
struct CheckEqualsInternalizedStringOp
struct LoadMessageOp
struct StoreMessageOp
struct SameValueOp
struct Float64SameValueOp
struct FastApiCallParameters
struct FastApiCallOp
struct RuntimeAbortOp
struct EnsureWritableFastElementsOp
struct MaybeGrowFastElementsOp
struct TransitionElementsKindOp
struct TransitionElementsKindOrCheckMapOp
struct FindOrderedHashEntryOp
struct CommentOp
struct opcode_to_operation_map
struct static_operation_input_count
struct static_operation_input_count< Op, std::void_t< decltype(Op::inputs)> >
struct OptimizePhase
struct HasProperRunMethod
struct produces_printable_graph
class PipelineData
struct SimplificationAndNormalizationPhase
class Pipeline
class BuiltinPipeline
class PretenuringPropagationAnalyzer
class PretenuringPropagationReducer
struct reducer_list_length
struct reducer_list_contains
struct reducer_list_starts_with
struct reducer_list_index_of
struct reducer_list_insert_at
struct reducer_list_to_stack
struct next_reducer_is
struct next_contains_reducer
struct next_contains_reducer< R< T >, Reducer >
struct next_is_bottom_of_assembler_stack
struct MeetRegisterConstraintsPhase
struct ResolvePhisPhase
struct BuildLiveRangesPhase
struct BuildLiveRangeBundlesPhase
struct AllocateGeneralRegistersPhase
struct AllocateFPRegistersPhase
struct AllocateSimd128RegistersPhase
struct DecideSpillingModePhase
struct AssignSpillSlotsPhase
struct CommitAssignmentPhase
struct PopulateReferenceMapsPhase
struct ConnectRangesPhase
struct ResolveControlFlowPhase
struct OptimizeMovesPhase
struct FrameElisionPhase
struct JumpThreadingPhase
struct AssembleCodePhase
struct FinalizeCodePhase
class MaybeRegisterRepresentation
class RegisterRepresentation
struct MultiSwitch< T, std::enable_if_t< std::is_base_of_v< MaybeRegisterRepresentation, T > > >
class WordRepresentation
class FloatRepresentation
class MemoryRepresentation
class RequiredOptimizationReducer
struct RuntimeCallDescriptor
class SelectLoweringReducer
class GrowingBlockSidetable
class FixedBlockSidetable
class GrowingOpIndexSidetable
class FixedOpIndexSidetable
class SparseOpIndexSideTable
class SparseOpIndexSnapshotTable
struct NoKeyData
struct NoChangeCallback
class SnapshotTable
struct SnapshotTableEntry
class SnapshotTableKey
class ChangeTrackingSnapshotTable
class StackCheckLoweringReducer
struct StoreStoreEliminationPhase
struct MaybeRedundantStoresKeyData
class MaybeRedundantStoresTable
class RedundantStoreAnalysis
class StoreStoreEliminationReducer
class StringEscapeAnalyzer
class StringEscapeAnalysisReducer
class StringView
class Tracing
class TurbolevEarlyLoweringReducer
class BlockOriginTrackingReducer
class GeneratorAnalyzer
class GraphBuildingNodeProcessor
class NodeProcessorBase
struct TurbolevGraphBuildingPhase
struct TypeAssertionsPhase
class TypeInferenceAnalysis
struct TypeInferenceReducerArgs
class TypeInferenceReducer
class TypeParser
struct TypedOptimizationsPhase
class TypedOptimizationsReducer
struct WordOperationTyper
struct FloatOperationTyper
class Typer
class WordType
class FloatType
class Type
class TupleType
struct fast_hash< Type >
class UniformReducerAdapter
class UseMap
class Simd128UseMap
struct any_of
struct all_of
class ScopedModification
struct MultiSwitch
struct MultiSwitchIntegral
class ScopeCounter
class DisableValueNumbering
struct RootTypes
struct WasmDeadCodeEliminationPhase
struct WasmGCOptimizePhase
class WasmGCTypeAnalyzer
class WasmGCTypedOptimizationReducer
struct WasmInJSInliningPhase
class WasmInJSInliningReducer
class WasmInJsInliningInterface
class WasmJSLoweringReducer
class WasmLoadEliminationAnalyzer
class WasmLoadEliminationReducer
struct WasmLoweringPhase
class WasmLoweringReducer
struct WasmOptimizePhase
class WasmRevecVerifier
struct WasmRevecPhase
class OffsetDiff
class StoreLoadInfo
struct StoreInfoCompare
class NodeGroup
class PackNode
class ForcePackNode
class ShufflePackNode
class BundlePackNode
class SLPTree
class WasmRevecAnalyzer
class DemandedElementAnalysis
class WasmShuffleAnalyzer
class WasmShuffleReducer
struct WasmSimdPhase
class TurboshaftCompilationJob
class ZoneWithName
Typedefs
template<typename T >
using LoopLabelFor = detail::LoopLabelForHelper< T >::type
using TurboshaftAssemblerGenerator = void(*)(compiler::turboshaft::PipelineData *, Isolate *, compiler::turboshaft::Graph &, Zone *)
using MaybeVariable = std::optional< Variable >
using OperationStorageSlot = uint64_t
using Word32 = WordWithBits< 32 >
using Word64 = WordWithBits< 64 >
using WordPtr = std::conditional_t< Is64(), Word64, Word32 >
using Float32 = FloatWithBits< 32 >
using Float64 = FloatWithBits< 64 >
using Simd128 = WordWithBits< 128 >
using Simd256 = WordWithBits< 256 >
using Word = UntaggedUnion< Word32, Word64 >
using Float = UntaggedUnion< Float32, Float64 >
using Float64OrWord32 = UntaggedUnion< Float64, Word32 >
using Untagged = UntaggedUnion< Word, Float >
using BooleanOrNullOrUndefined = UnionOf< Boolean, Null, Undefined >
using NumberOrString = UnionOf< Number, String >
using PlainPrimitive = UnionOf< NumberOrString, BooleanOrNullOrUndefined >
using StringOrNull = UnionOf< String, Null >
using NumberOrUndefined = UnionOf< Number, Undefined >
using AnyFixedArray = UnionOf< FixedArray, FixedDoubleArray >
using NonBigIntPrimitive = UnionOf< Symbol, PlainPrimitive >
using Primitive = UnionOf< BigInt, NonBigIntPrimitive >
using CallTarget = UntaggedUnion< WordPtr, Code, JSFunction, Word32 >
using AnyOrNone = UntaggedUnion< Any, None >
using Word32Pair = Tuple< Word32, Word32 >
template<typename T >
using maybe_const_or_v_t = typename detail::ConstOrVTypeHelper< T >::type
using MapMask = uint64_t
using CmpOp = StaticCanonicalForLoopMatcher::CmpOp
using BinOp = StaticCanonicalForLoopMatcher::BinOp
using Variable = SnapshotTable< OpIndex, VariableData >::Key
template<typename T >
using underlying_operation_t = typename underlying_operation< T >::type
template<template< typename > typename... Ts>
using reducer_list = base::tmp::list1< Ts... >
template<size_t Bits>
using float_type = (T v) requires std typename detail::TypeForBits< Bits >::float_type
using Word32Type = WordType< 32 >
using Word64Type = WordType< 64 >
using Float32Type = FloatType< 32 >
using Float64Type = FloatType< 64 >
typedef bool(* FunctionType) (const Graph &graph, const Operation &op, Zone *zone)
using StoreInfoSet = ZoneSet< StoreLoadInfo< StoreOp >, StoreInfoCompare >
using SmallShuffleVector = SmallZoneVector< const Simd128ShuffleOp *, 8 >
template<typename T , auto >
using ZoneWithNamePointer = T *
Enumerations
enum ConditionalGotoStatus { kGotoDestination = 1
, kGotoEliminated = 2
, kBranch = 3
 }
enum class HashingStrategy { kDefault
, kMakeSnapshotStable
 }
enum class Opcode : uint8_t { ENUM_CONSTANT
 }
enum class NumericKind : uint8_t {
kFloat64Hole
, kFinite
, kInteger
, kSafeInteger
,
kInt32
, kSmi
, kMinusZero
, kNaN
 }
enum class TurboshaftPipelineKind {
kJS
, kWasm
, kCSA
, kTSABuiltin
,
kJSToWasm
 }
enum class StoreObservability { kUnobservable = 0
, kGCObservable = 1
, kObservable = 2
 }
Functions
static std::optional< FlagsCondition > GetFlagsCondition (OpIndex node, InstructionSelector *selector)
static std::optional< CompareChainNode * > FindCompareChain (OpIndex user, OpIndex node, InstructionSelector *selector, Zone *zone, ZoneVector< CompareChainNode * > &nodes)
void CombineFlagSettingOps (CompareChainNode *logic_node, InstructionSelector *selector, CompareSequence *sequence)
static std::optional< FlagsCondition > TryMatchConditionalCompareChainShared (InstructionSelector *selector, Zone *zone, OpIndex node, CompareSequence *sequence)
static void VisitCompareChain (InstructionSelector *selector, OpIndex left_node, OpIndex right_node, RegisterRepresentation rep, InstructionCode opcode, ImmediateMode operand_mode, FlagsContinuation *cont)
static bool TryMatchConditionalCompareChainBranch (InstructionSelector *selector, Zone *zone, OpIndex node, FlagsContinuation *cont)
static bool TryMatchConditionalCompareChainSet (InstructionSelector *selector, Zone *zone, OpIndex node)
Handle< Code > BuiltinCodeHandle (Builtin builtin, Isolate *isolate)
template<typename T >
Range (V< T >, V< T >, V< T >) -> Range< T >
template<typename T >
Range (V< T >, V< T >, typename ConstOrV< T >::constant_type) -> Range< T >
template<typename T >
Range (V< T >, typename ConstOrV< T >::constant_type, typename ConstOrV< T >::constant_type) -> Range< T >
template<typename T >
Sequence (V< T >, V< T >) -> Sequence< T >
template<typename T >
Sequence (V< T >, typename ConstOrV< T >::constant_type) -> Sequence< T >
template<typename T >
Sequence (V< T >) -> Sequence< T >
template<typename... Iterables>
Zip (Iterables... iterables) -> Zip< Iterables... >
DirectHandle< Code > BuildWithTurboshaftAssemblerImpl (Isolate *isolate, Builtin builtin, TurboshaftAssemblerGenerator generator, std::function< compiler::CallDescriptor *(Zone *)> call_descriptor_builder, const char *name, const AssemblerOptions &options, CodeKind code_kind, std::optional< BytecodeHandlerData > bytecode_handler_data)
int CountDecimalDigits (uint32_t value)
std::ostream & operator<< (std::ostream &os, PaddingSpace padding)
std::optional< Builtin > TryGetBuiltin (V< Any > node, Graph &graph)
void AnalyzeCall (CallView call, std::unordered_set< Builtin > &called_builtins, BuiltinAllocateEffect *can_allocate, Graph &graph, Builtin current_builtin)
std::ostream & operator<< (std::ostream &stream, const ControlState &state)
bool operator== (const ControlState &lhs, const ControlState &rhs)
bool operator!= (const ControlState &lhs, const ControlState &rhs)
std::ostream & operator<< (std::ostream &stream, OperationState::Liveness liveness)
void RunDecompressionOptimization (Graph &graph, Zone *phase_zone)
bool operator== (const FrameStateData &lhs, const FrameStateData &rhs)
size_t fast_hash_combine ()
size_t fast_hash_combine (size_t acc)
size_t fast_hash_combine (size_t acc, size_t value)
template<typename T , typename... Ts>
size_t fast_hash_combine (T const &v, Ts const &... vs)
template<typename Iterator >
size_t fast_hash_range (Iterator first, Iterator last)
std::optional< BailoutReason > BuildGraph (PipelineData *data, Schedule *schedule, Zone *phase_zone, Linkage *linkage, JsWasmCallsSidetable *js_wasm_calls_sidetable)
std::ostream & operator<< (std::ostream &os, const TurboshaftGraphAsJSON &ad)
void PrintTurboshaftCustomDataPerOperation (std::ofstream &stream, const char *data_name, const Graph &graph, std::function< bool(std::ostream &, const Graph &, OpIndex)> printer)
void PrintTurboshaftCustomDataPerBlock (std::ofstream &stream, const char *data_name, const Graph &graph, std::function< bool(std::ostream &, const Graph &, BlockIndex)> printer)
V8_EXPORT_PRIVATE TurboshaftGraphAsJSON AsJSON (const Graph &graph, NodeOriginTable *origins, Zone *temp_zone)
std::ostream & operator<< (std::ostream &os, PrintAsBlockHeader block_header)
std::ostream & operator<< (std::ostream &os, const Graph &graph)
std::ostream & operator<< (std::ostream &os, const Block::Kind &kind)
V8_EXPORT_PRIVATE std::ostream & operator<< (std::ostream &os, const Block *b)
OperationStorageSlot * AllocateOpStorage (Graph *graph, size_t slot_count)
const Operation & Get (const Graph &graph, OpIndex index)
V8_EXPORT_PRIVATE std::ostream & operator<< (std::ostream &os, OpIndex idx)
std::ostream & operator<< (std::ostream &os, OptionalOpIndex idx)
constexpr bool operator== (nullrep_t, nullrep_t)
constexpr bool operator== (nullrep_t, RegisterRepresentation)
constexpr bool operator== (RegisterRepresentation, nullrep_t)
constexpr bool operator!= (nullrep_t, nullrep_t)
constexpr bool operator!= (nullrep_t, RegisterRepresentation)
constexpr bool operator!= (RegisterRepresentation, nullrep_t)
template<typename T >
constexpr bool IsWord ()
template<typename T >
constexpr bool IsValidTypeFor (RegisterRepresentation repr)
template<typename T >
OptionalV (V< T >) -> OptionalV< T >
template<typename T >
ConstOrV (V< T >) -> ConstOrV< T >
size_t hash_value (OpIndex op)
size_t hash_value (OptionalOpIndex op)
size_t hash_value (BlockIndex op)
V8_EXPORT_PRIVATE std::ostream & operator<< (std::ostream &os, BlockIndex b)
DEFINE_STRONG_ORDERING_COMPARISON (OptionalOpIndex, OptionalOpIndex, l.value_or_invalid(), r.value_or_invalid()) DEFINE_STRONG_ORDERING_COMPARISON(OpIndex
r value_or_invalid ()) DEFINE_STRONG_ORDERING_COMPARISON(OptionalOpIndex
void PropagateDeferred (Graph &graph)
std::ostream & operator<< (std::ostream &os, const MemoryAddress &mem)
bool IsInt32TruncatedLoadPattern (const Graph &graph, OpIndex change_idx, const ChangeOp &change, OpIndex *bitcast_idx, OpIndex *load_idx)
bool is_empty (MapMaskAndOr minmax)
MapMask ComputeMapHash (MapRef map)
MapMaskAndOr ComputeMinMaxHash (ZoneRefSet< Map > maps)
MapMaskAndOr CombineMinMax (MapMaskAndOr a, MapMaskAndOr b)
bool CouldHaveSameMap (MapMaskAndOr a, MapMaskAndOr b)
size_t hash_value (MemoryAddress const &mem)
std::ostream & operator<< (std::ostream &os, const IterationCount &count)
std::ostream & operator<< (std::ostream &os, const CmpOp &cmp)
std::ostream & operator<< (std::ostream &os, const BinOp &binop)
const TSCallDescriptor * CreateAllocateBuiltinDescriptor (Zone *zone, Isolate *isolate)
bool ValueNeedsWriteBarrier (const Graph *graph, const Operation &value, Isolate *isolate)
const AllocateOp * UnwrapAllocate (const Graph *graph, const Operation *op)
Zone * get_zone (Graph *graph)
std::optional< Builtin > TryGetBuiltinId (const ConstantOp *target, JSHeapBroker *broker)
const char * OpcodeName (Opcode opcode)
std::ostream & operator<< (std::ostream &os, OperationPrintStyle styled_op)
std::ostream & operator<< (std::ostream &os, RootIndex index)
std::ostream & operator<< (std::ostream &os, GenericBinopOp::Kind kind)
std::ostream & operator<< (std::ostream &os, GenericUnopOp::Kind kind)
std::ostream & operator<< (std::ostream &os, Word32SignHintOp::Sign sign)
std::ostream & operator<< (std::ostream &os, WordUnaryOp::Kind kind)
std::ostream & operator<< (std::ostream &os, OverflowCheckedUnaryOp::Kind kind)
std::ostream & operator<< (std::ostream &os, FloatUnaryOp::Kind kind)
std::ostream & operator<< (std::ostream &os, ShiftOp::Kind kind)
std::ostream & operator<< (std::ostream &os, ComparisonOp::Kind kind)
std::ostream & operator<< (std::ostream &os, ChangeOp::Kind kind)
std::ostream & operator<< (std::ostream &os, ChangeOrDeoptOp::Kind kind)
std::ostream & operator<< (std::ostream &os, TryChangeOp::Kind kind)
std::ostream & operator<< (std::ostream &os, TaggedBitcastOp::Kind kind)
std::ostream & operator<< (std::ostream &os, ChangeOp::Assumption assumption)
std::ostream & operator<< (std::ostream &os, SelectOp::Implementation kind)
std::ostream & operator<< (std::ostream &os, AtomicRMWOp::BinOp bin_op)
std::ostream & operator<< (std::ostream &os, AtomicWord32PairOp::Kind bin_op)
std::ostream & operator<< (std::ostream &os, FrameConstantOp::Kind kind)
std::ostream & operator<< (std::ostream &os, OpEffects effects)
std::ostream & operator<< (std::ostream &os, ObjectIsOp::Kind kind)
std::ostream & operator<< (std::ostream &os, ObjectIsOp::InputAssumptions input_assumptions)
std::ostream & operator<< (std::ostream &os, NumericKind kind)
std::ostream & operator<< (std::ostream &os, ConvertOp::Kind kind)
std::ostream & operator<< (std::ostream &os, ConvertUntaggedToJSPrimitiveOp::JSPrimitiveKind kind)
std::ostream & operator<< (std::ostream &os, ConvertUntaggedToJSPrimitiveOp::InputInterpretation input_interpretation)
std::ostream & operator<< (std::ostream &os, ConvertUntaggedToJSPrimitiveOrDeoptOp::JSPrimitiveKind kind)
std::ostream & operator<< (std::ostream &os, ConvertUntaggedToJSPrimitiveOrDeoptOp::InputInterpretation input_interpretation)
std::ostream & operator<< (std::ostream &os, ConvertJSPrimitiveToUntaggedOp::UntaggedKind kind)
std::ostream & operator<< (std::ostream &os, ConvertJSPrimitiveToUntaggedOp::InputAssumptions input_assumptions)
std::ostream & operator<< (std::ostream &os, ConvertJSPrimitiveToUntaggedOrDeoptOp::UntaggedKind kind)
std::ostream & operator<< (std::ostream &os, ConvertJSPrimitiveToUntaggedOrDeoptOp::JSPrimitiveKind kind)
std::ostream & operator<< (std::ostream &os, TruncateJSPrimitiveToUntaggedOp::UntaggedKind kind)
std::ostream & operator<< (std::ostream &os, TruncateJSPrimitiveToUntaggedOp::InputAssumptions input_assumptions)
std::ostream & operator<< (std::ostream &os, TruncateJSPrimitiveToUntaggedOrDeoptOp::UntaggedKind kind)
std::ostream & operator<< (std::ostream &os, NewArrayOp::Kind kind)
std::ostream & operator<< (std::ostream &os, DoubleArrayMinMaxOp::Kind kind)
std::ostream & operator<< (std::ostream &os, BigIntBinopOp::Kind kind)
std::ostream & operator<< (std::ostream &os, BigIntComparisonOp::Kind kind)
std::ostream & operator<< (std::ostream &os, BigIntUnaryOp::Kind kind)
std::ostream & operator<< (std::ostream &os, StringAtOp::Kind kind)
std::ostream & operator<< (std::ostream &os, StringComparisonOp::Kind kind)
std::ostream & operator<< (std::ostream &os, ArgumentsLengthOp::Kind kind)
std::ostream & operator<< (std::ostream &os, TransitionAndStoreArrayElementOp::Kind kind)
void PrintMapSet (std::ostream &os, const ZoneRefSet< Map > &maps)
std::ostream & operator<< (std::ostream &os, SameValueOp::Mode mode)
std::ostream & operator<< (std::ostream &os, FindOrderedHashEntryOp::Kind kind)
std::ostream & operator<< (std::ostream &os, JSStackCheckOp::Kind kind)
base::SmallVector< Block *, 4 > SuccessorBlocks (const Block &block, const Graph &graph)
bool IsUnlikelySuccessor (const Block *block, const Block *successor, const Graph &graph)
constexpr std::underlying_type_t< Opcode > OpcodeIndex (Opcode x)
constexpr bool IsBlockTerminator (Opcode opcode)
constexpr bool MayThrow (Opcode opcode)
template<typename T >
base::Vector< T > InitVectorOf (ZoneVector< T > &storage, std::initializer_list< RegisterRepresentation > values)
size_t hash_value (OpEffects effects)
bool CannotSwapOperations (OpEffects first, OpEffects second)
bool CannotSwapProtectedLoads (OpEffects first, OpEffects second)
std::ostream & operator<< (std::ostream &os, const Operation &op)
template<RegisterRepresentation::Enum... reps>
base::Vector< const RegisterRepresentation > RepVector ()
template<MaybeRegisterRepresentation::Enum... reps>
base::Vector< const MaybeRegisterRepresentation > MaybeRepVector ()
size_t hash_value (LoadOp::Kind kind)
base::SmallVector< Block *, 4 > SuccessorBlocks (const Operation &op)
constexpr RegisterRepresentation RegisterRepresentationForArrayType (ExternalArrayType array_type)
base::Vector< const RegisterRepresentation > VectorForRep (RegisterRepresentation rep)
bool CanBeUsedAsInput (const Operation &op)
V8_EXPORT_PRIVATE bool ShouldSkipOperation (const Operation &op)
template<typename Op , typename... Args>
Op * CreateOperation (base::SmallVector< OperationStorageSlot, 32 > &storage, Args... args)
template<typename F >
auto VisitOperation (const Operation &op, F &&f)
void PrintTurboshaftGraph (PipelineData *data, Zone *temp_zone, CodeTracer *code_tracer, const char *phase_name)
void PrintTurboshaftGraphForTurbolizer (std::ofstream &stream, const Graph &graph, const char *phase_name, NodeOriginTable *node_origins, Zone *temp_zone)
std::ostream & operator<< (std::ostream &os, MaybeRegisterRepresentation rep)
std::ostream & operator<< (std::ostream &os, MemoryRepresentation rep)
constexpr bool operator== (MaybeRegisterRepresentation a, MaybeRegisterRepresentation b)
constexpr bool operator!= (MaybeRegisterRepresentation a, MaybeRegisterRepresentation b)
size_t hash_value (MaybeRegisterRepresentation rep)
constexpr bool operator== (MemoryRepresentation a, MemoryRepresentation b)
constexpr bool operator!= (MemoryRepresentation a, MemoryRepresentation b)
size_t hash_value (MemoryRepresentation rep)
std::ostream & operator<< (std::ostream &os, StoreObservability observability)
constexpr bool TooManyArgumentsForCall (size_t arguments_count)
void PrintBytecode (PipelineData &data, maglev::MaglevCompilationInfo *compilation_info)
void PrintMaglevGraph (PipelineData &data, maglev::Graph *maglev_graph, const char *msg)
void RunMaglevOptimizations (PipelineData *data, maglev::MaglevCompilationInfo *compilation_info, maglev::Graph *maglev_graph)
template<typename Op >
bool CanBeTyped (const Op &operation)
template<typename T , size_t N>
T array_min (const std::array< T, N > &a)
template<typename T , size_t N>
T array_max (const std::array< T, N > &a)
template<size_t Bits, typename word_t = typename WordType<Bits>::word_t>
WordType< Bits > LeastUpperBoundFromRanges (word_t l_from, word_t l_to, word_t r_from, word_t r_to, Zone *zone)
template class EXPORT_TEMPLATE_DEFINE (V8_EXPORT_PRIVATE) WordType< 32 >
template class EXPORT_TEMPLATE_DECLARE (V8_EXPORT_PRIVATE) WordType< 32 >
std::ostream & operator<< (std::ostream &stream, Type::Kind kind)
std::ostream & operator<< (std::ostream &stream, const Type &type)
bool operator== (const Type &lhs, const Type &rhs)
bool operator!= (const Type &lhs, const Type &rhs)
template<class... Args>
any_of (const Args &...) -> any_of< Args... >
template<class T , class... Ts>
bool operator== (const T &value, any_of< Ts... > options)
template<class... Ts>
std::ostream & operator<< (std::ostream &os, any_of< Ts... > any)
template<class... Args>
all_of (const Args &...) -> all_of< Args... >
template<class T , class... Ts>
bool operator== (all_of< Ts... > values, const T &target)
template<class... Ts>
std::ostream & operator<< (std::ostream &os, all_of< Ts... > all)
V8_EXPORT_PRIVATE bool ShouldSkipOptimizationStep ()
template<typename... Ts>
constexpr uint64_t multi (const Ts &... values)
template<typename AssemblerT >
OpIndex LoadRootHelper (AssemblerT &&assembler, RootIndex index)
bool RepIsCompatible (RegisterRepresentation actual, RegisterRepresentation expected_reg_repr, uint8_t in_memory_size)
bool IsSameOpAndKind (const Operation &op0, const Operation &op1)
std::string GetSimdOpcodeName (Operation const &op)
template<class Op , class Info >
bool LoadStrideEqualTo (const Graph &graph, const NodeGroup &node_group, int stride)
template<typename T >
bool IsSplat (const T &node_group)
template<typename FunctionType >
void ForEach (FunctionType callback, const ZoneUnorderedMap< OpIndex, PackNode * > &node_map)
template<typename FunctionType >
void ForEach (FunctionType callback, const ZoneUnorderedMap< OpIndex, ZoneVector< PackNode * >> &node_map)
bool IsSignExtensionOp (Operation &op)
bool IsLoadExtend (const Simd128LoadTransformOp &op)
bool IsLoadSplat (const Simd128LoadTransformOp &op)
wasm::WasmCompilationResult ExecuteTurboshaftWasmCompilation (wasm::CompilationEnv *env, compiler::WasmCompilationData &data, wasm::WasmDetectedFeatures *detected, Counters *counters)
Variables
template<typename It , typename A >
concept ForeachIterable
constexpr char kBuiltinCompilationZoneName []
constexpr size_t kSlotsPerId = 2
constexpr nullrep_t nullrep
template<typename T >
concept IsUntagged
template<typename T >
concept IsTagged
template<typename T >
constexpr bool const_or_v_exists_v = detail::ConstOrVTypeHelper<T>::exists
OptionalOpIndex
l
r OpIndex
constexpr char kCompilationZoneName [] = `compilation-zone`
template<typename Op >
constexpr Opcode operation_to_opcode_v = operation_to_opcode<Op>::value
constexpr uint16_t kNumberOfBlockTerminatorOpcodes
constexpr uint16_t kNumberOfOpcodes
static constexpr std::optional< OpEffects > kOperationEffectsTable [kNumberOfOpcodes]
constexpr size_t kOperationSizeTable [kNumberOfOpcodes]
constexpr size_t kOperationSizeDividedBySizeofOpIndexTable [kNumberOfOpcodes]
template<typename Phase , typename... Args>
concept TurboshaftPhase
template<typename Phase >
concept TurbofanPhase = requires(Phase p) { p.kKind == PhaseKind::kTurbofan; }
template<typename Phase >
concept CompilerPhase = TurboshaftPhase<Phase> || TurbofanPhase<Phase>
constexpr char kTempZoneName [] = `temp-zone`
template<size_t Bits>
constexpr float_type< Bits > nan_v = detail::TypeForBits<Bits>::nan
Typedef Documentation
AnyFixedArray
using v8::internal::compiler::turboshaft::AnyFixedArray = typedef UnionOf<FixedArray, FixedDoubleArray>
Definition at line 550 of file index.h.
AnyOrNone
using v8::internal::compiler::turboshaft::AnyOrNone = typedef UntaggedUnion<Any, None>
Definition at line 554 of file index.h.
BinOp
using v8::internal::compiler::turboshaft::BinOp = typedef StaticCanonicalForLoopMatcher::BinOp
Definition at line 25 of file loop-unrolling-reducer.cc.
BooleanOrNullOrUndefined
using v8::internal::compiler::turboshaft::BooleanOrNullOrUndefined = typedef UnionOf<Boolean, Null, Undefined>
Definition at line 545 of file index.h.
CallTarget
using v8::internal::compiler::turboshaft::CallTarget = typedef UntaggedUnion<WordPtr, Code, JSFunction, Word32>
Definition at line 553 of file index.h.
CmpOp
using v8::internal::compiler::turboshaft::CmpOp = typedef StaticCanonicalForLoopMatcher::CmpOp
Definition at line 24 of file loop-unrolling-reducer.cc.
Float
using v8::internal::compiler::turboshaft::Float = typedef UntaggedUnion<Float32, Float64>
Definition at line 542 of file index.h.
Float32
using v8::internal::compiler::turboshaft::Float32 = typedef FloatWithBits<32>
Definition at line 239 of file index.h.
Float32Type
using v8::internal::compiler::turboshaft::Float32Type = typedef FloatType<32>
Definition at line 171 of file types.h.
Float64
using v8::internal::compiler::turboshaft::Float64 = typedef FloatWithBits<64>
Definition at line 240 of file index.h.
Float64OrWord32
using v8::internal::compiler::turboshaft::Float64OrWord32 = typedef UntaggedUnion<Float64, Word32>
Definition at line 543 of file index.h.
Float64Type
using v8::internal::compiler::turboshaft::Float64Type = typedef FloatType<64>
Definition at line 172 of file types.h.
float_type
template<size_t Bits>
using v8::internal::compiler::turboshaft::float_type = typedef (T v) requires std typename detail::TypeForBits<Bits>::float_type
Definition at line 159 of file types.h.
FunctionType
typedef bool(* v8::internal::compiler::turboshaft::FunctionType) (const Graph &graph, const Operation &op, Zone *zone)
Definition at line 13 of file use-map.h.
LoopLabelFor
template<typename T >
using v8::internal::compiler::turboshaft::LoopLabelFor = typedef detail::LoopLabelForHelper<T>::type
Definition at line 732 of file assembler.h.
MapMask
using v8::internal::compiler::turboshaft::MapMask = typedef uint64_t
Definition at line 147 of file late-load-elimination-reducer.h.
maybe_const_or_v_t
template<typename T >
using v8::internal::compiler::turboshaft::maybe_const_or_v_t = typedef typename detail::ConstOrVTypeHelper<T>::type
Definition at line 798 of file index.h.
MaybeVariable
using v8::internal::compiler::turboshaft::MaybeVariable = typedef std::optional<Variable>
Definition at line 34 of file copying-phase.h.
NonBigIntPrimitive
using v8::internal::compiler::turboshaft::NonBigIntPrimitive = typedef UnionOf<Symbol, PlainPrimitive>
Definition at line 551 of file index.h.
NumberOrString
using v8::internal::compiler::turboshaft::NumberOrString = typedef UnionOf<Number, String>
Definition at line 546 of file index.h.
NumberOrUndefined
using v8::internal::compiler::turboshaft::NumberOrUndefined = typedef UnionOf<Number, Undefined>
Definition at line 549 of file index.h.
OperationStorageSlot
using v8::internal::compiler::turboshaft::OperationStorageSlot = typedef uint64_t
Definition at line 29 of file index.h.
PlainPrimitive
using v8::internal::compiler::turboshaft::PlainPrimitive = typedef UnionOf<NumberOrString, BooleanOrNullOrUndefined>
Definition at line 547 of file index.h.
Primitive
using v8::internal::compiler::turboshaft::Primitive = typedef UnionOf<BigInt, NonBigIntPrimitive>
Definition at line 552 of file index.h.
reducer_list
template<template< typename > typename... Ts>
using v8::internal::compiler::turboshaft::reducer_list = typedef base::tmp::list1<Ts...>
Definition at line 24 of file reducer-traits.h.
Simd128
using v8::internal::compiler::turboshaft::Simd128 = typedef WordWithBits<128>
Definition at line 242 of file index.h.
Simd256
using v8::internal::compiler::turboshaft::Simd256 = typedef WordWithBits<256>
Definition at line 243 of file index.h.
SmallShuffleVector
using v8::internal::compiler::turboshaft::SmallShuffleVector = typedef SmallZoneVector<const Simd128ShuffleOp*, 8>
Definition at line 27 of file wasm-shuffle-reducer.h.
StoreInfoSet
using v8::internal::compiler::turboshaft::StoreInfoSet = typedef ZoneSet<StoreLoadInfo<StoreOp>, StoreInfoCompare>
Definition at line 201 of file wasm-revec-reducer.cc.
StringOrNull
using v8::internal::compiler::turboshaft::StringOrNull = typedef UnionOf<String, Null>
Definition at line 548 of file index.h.
TurboshaftAssemblerGenerator
using v8::internal::compiler::turboshaft::TurboshaftAssemblerGenerator = typedef void (*)(compiler::turboshaft::PipelineData*, Isolate*, compiler::turboshaft::Graph&, Zone*)
Definition at line 42 of file builtin-compiler.h.
underlying_operation_t
template<typename T >
using v8::internal::compiler::turboshaft::underlying_operation_t = typedef typename underlying_operation<T>::type
Definition at line 920 of file operations.h.
Untagged
using v8::internal::compiler::turboshaft::Untagged = typedef UntaggedUnion<Word, Float>
Definition at line 544 of file index.h.
Variable
using v8::internal::compiler::turboshaft::Variable = typedef SnapshotTable<OpIndex, VariableData>::Key
Definition at line 81 of file operations.h.
Word
using v8::internal::compiler::turboshaft::Word = typedef UntaggedUnion<Word32, Word64>
Definition at line 541 of file index.h.
Word32
using v8::internal::compiler::turboshaft::Word32 = typedef WordWithBits<32>
Definition at line 229 of file index.h.
Word32Pair
using v8::internal::compiler::turboshaft::Word32Pair = typedef Tuple<Word32, Word32>
Definition at line 555 of file index.h.
Word32Type
using v8::internal::compiler::turboshaft::Word32Type = typedef WordType<32>
Definition at line 169 of file types.h.
Word64
using v8::internal::compiler::turboshaft::Word64 = typedef WordWithBits<64>
Definition at line 230 of file index.h.
Word64Type
using v8::internal::compiler::turboshaft::Word64Type = typedef WordType<64>
Definition at line 170 of file types.h.
WordPtr
using v8::internal::compiler::turboshaft::WordPtr = typedef std::conditional_t<Is64(), Word64, Word32>
Definition at line 231 of file index.h.
ZoneWithNamePointer
template<typename T , auto >
using v8::internal::compiler::turboshaft::ZoneWithNamePointer = typedef T*
Definition at line 73 of file zone-with-name.h.
Enumeration Type Documentation
ConditionalGotoStatus
enum v8::internal::compiler::turboshaft::ConditionalGotoStatus
Enumerator
kGotoDestination
kGotoEliminated
kBranch
Definition at line 84 of file assembler.h.
                           {
  kGotoDestination = 1, // The conditional Goto became an unconditional Goto to
                         // the destination.
  kGotoEliminated = 2, // The conditional GotoIf/GotoIfNot would never be
                         // executed and only the fallthrough path remains.
  kBranch = 3 // The conditional Goto became a branch.
  // Some examples of this:
  // GotoIf(true, dst) ===> kGotoDestination
  // GotoIf(false, dst) ===> kGotoEliminated
  // GotoIf(var, dst) ===> kBranch
  // GotoIfNot(true, dst) ===> kGotoEliminated
  // GotoIfNot(false, dst) ===> kGotoDestination
  // GotoIfNot(var, dst) ===> kBranch
};
HashingStrategy
enum v8::internal::compiler::turboshaft::HashingStrategy [strong]
Enumerator
kDefault
kMakeSnapshotStable
Definition at line 66 of file operations.h.
                           {
  kDefault,
  // This strategy requires that hashing a graph during builtin construction
  // (mksnapshot) produces the same hash for repeated runs of mksnapshot. This
  // requires that no pointers and external constants are used in hashes.
  kMakeSnapshotStable,
};
NumericKind
enum v8::internal::compiler::turboshaft::NumericKind : uint8_t [strong]
Enumerator
kFloat64Hole
kFinite
kInteger
kSafeInteger
kInt32
kSmi
kMinusZero
kNaN
Definition at line 4665 of file operations.h.
                       : uint8_t {
  kFloat64Hole,
#ifdef V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
  kFloat64Undefined,
#endif // V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
  kFinite,
  kInteger,
  kSafeInteger,
  kInt32,
  kSmi,
  kMinusZero,
  kNaN,
};
Opcode
enum v8::internal::compiler::turboshaft::Opcode : uint8_t [strong]
Enumerator
ENUM_CONSTANT
Definition at line 368 of file operations.h.
                  : uint8_t {
#define ENUM_CONSTANT(Name) k##Name,
  TURBOSHAFT_OPERATION_LIST(ENUM_CONSTANT)
#undef ENUM_CONSTANT
};
StoreObservability
enum v8::internal::compiler::turboshaft::StoreObservability [strong]
Enumerator
kUnobservable
kGCObservable
kObservable
Definition at line 78 of file store-store-elimination-reducer-inl.h.
                              {
  kUnobservable = 0,
  kGCObservable = 1,
  kObservable = 2,
};
TurboshaftPipelineKind
enum v8::internal::compiler::turboshaft::TurboshaftPipelineKind [strong]
Enumerator
kJS
kWasm
kCSA
kTSABuiltin
kJSToWasm
Definition at line 171 of file phase.h.
{ kJS, kWasm, kCSA, kTSABuiltin, kJSToWasm };
Function Documentation
all_of()
template<class... Args>
v8::internal::compiler::turboshaft::all_of (const Args & ...) -> all_of< Args... >
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TaggedBitcast().
AllocateOpStorage()
OperationStorageSlot * v8::internal::compiler::turboshaft::AllocateOpStorage (Graph * graph, size_t slot_count) [inline]
Definition at line 1237 of file graph.h.
                                                                     {
  return graph->Allocate(slot_count);
}
References graph().
Referenced by v8::internal::compiler::turboshaft::OperationT< Derived >::New().
AnalyzeCall()
void v8::internal::compiler::turboshaft::AnalyzeCall (CallView call, std::unordered_set< Builtin > & called_builtins, BuiltinAllocateEffect * can_allocate, Graph & graph, Builtin current_builtin)
Definition at line 61 of file csa-effects-computation.cc.
                                          {
  if (*can_allocate == BuiltinAllocateEffect::kYes) {
    // No need to bother with allocations through builtin calls: this builtin
    // allocates directly.
    return;
  }
  V<CallTarget> target = call.target;
  if (std::optional<Builtin> builtin = TryGetBuiltin(target, graph)) {
    if (*builtin == current_builtin) {
      // Recursive call, no need to record anything.
      return;
    } else if (std::optional<Runtime::FunctionId> runtime_function_id =
                   call.descriptor->descriptor->runtime_function_id()) {
      // We special case Abort, which can allocate, but always result from
      // something unexpected already having happened, and never resumes
      // execution afterwards. This could lead to the GC seeing uninitialized
      // memory, which is unfortunate, but it's better this way rather than
      // having over-conservative effects because we try to terminate execution
      // cleanly through Abort rather than just segfaulting abruptly.
      if (Runtime::kCanTriggerGC[runtime_function_id.value()] &&
          runtime_function_id.value() != Runtime::kAbort) {
        *can_allocate = BuiltinAllocateEffect::kYes;
      }
      return;
    } else {
      called_builtins.insert(*builtin);
      *can_allocate = BuiltinAllocateEffect::kMaybeWithBuiltinCall;
      return;
    }
  } else if (graph.Get(target).Is<Opmask::kExternalConstant>()) {
    // External functions cannot allocate without conservative stack scanning.
    return;
  }
  *can_allocate = BuiltinAllocateEffect::kYes;
}
References v8::internal::compiler::turboshaft::CallView::descriptor, v8::internal::compiler::turboshaft::TSCallDescriptor::descriptor, graph(), v8::internal::Runtime::kCanTriggerGC, v8::internal::kMaybeWithBuiltinCall, v8::internal::kYes, v8::internal::compiler::CallDescriptor::runtime_function_id(), v8::internal::compiler::turboshaft::CallView::target, and TryGetBuiltin().
Referenced by v8::internal::compiler::turboshaft::CsaEffectsComputationPhase::Run().
any_of()
template<class... Args>
v8::internal::compiler::turboshaft::any_of (const Args & ...) -> any_of< Args... >
Referenced by v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::Allocate(), v8::internal::compiler::turboshaft::RegisterRepresentation::AllowImplicitRepresentationChangeTo(), v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::Bind(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Comparison(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::ConvertUntaggedToJSPrimitive(), v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::CountIterationsImpl(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::IsInt16(), v8::internal::compiler::InstructionSelector::IsRelocatableWasmConstant(), v8::internal::compiler::turboshaft::IterationCount::IterationCount(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::OverflowCheckedBinop(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Shift(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryReduceToRor(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordBinop().
array_max()
template<typename T , size_t N>
T v8::internal::compiler::turboshaft::array_max (const std::array< T, N > & a)
Definition at line 38 of file typer.h.
                                     {
  DCHECK_NE(0, N);
  T x = -std::numeric_limits<T>::infinity();
  for (size_t i = 0; i < N; ++i) {
    if (!std::isnan(a[i])) {
      x = std::max(a[i], x);
    }
  }
  DCHECK(!std::isnan(x));
  return x == T{0} ? T{0} : x; // -0 -> 0
}
References v8::internal::DCHECK(), DCHECK_NE, v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::N.
Referenced by v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Add(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Divide(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Multiply(), and v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Subtract().
array_min()
template<typename T , size_t N>
T v8::internal::compiler::turboshaft::array_min (const std::array< T, N > & a)
Definition at line 22 of file typer.h.
                                     {
  DCHECK_NE(0, N);
  T x = +std::numeric_limits<T>::infinity();
  for (size_t i = 0; i < N; ++i) {
    if (!std::isnan(a[i])) {
      x = std::min(a[i], x);
    }
  }
  DCHECK(!std::isnan(x));
  return x == T{0} ? T{0} : x; // -0 -> 0
}
References v8::internal::DCHECK(), DCHECK_NE, v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::N.
Referenced by v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Add(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Divide(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Multiply(), and v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Subtract().
AsJSON()
V8_EXPORT_PRIVATE TurboshaftGraphAsJSON v8::internal::compiler::turboshaft::AsJSON (const Graph & graph, NodeOriginTable * origins, Zone * temp_zone) [inline]
Definition at line 22 of file graph-visualizer.h.
                                                                      {
  return TurboshaftGraphAsJSON{graph, origins, temp_zone};
}
References graph().
Referenced by v8::internal::compiler::turboshaft::JSONTurboshaftGraphWriter::PrintNodes(), and PrintTurboshaftGraphForTurbolizer().
BuildGraph()
std::optional< BailoutReason > v8::internal::compiler::turboshaft::BuildGraph (PipelineData * data, Schedule * schedule, Zone * phase_zone, Linkage * linkage, JsWasmCallsSidetable * js_wasm_calls_sidetable)
Definition at line 2801 of file graph-builder.cc.
                                                   {
  GraphBuilder builder{data, phase_zone, *schedule, linkage,
                       js_wasm_calls_sidetable};
#if DEBUG
  data->graph().SetCreatedFromTurbofan();
  data->graph().set_broker(data->broker());
#endif
  return builder.Run();
}
References v8::internal::compiler::turboshaft::PipelineData::broker(), and v8::internal::compiler::turboshaft::PipelineData::graph().
Referenced by v8::internal::compiler::turboshaft::BuildGraphPhase::Run().
BuildWithTurboshaftAssemblerImpl()
V8_EXPORT_PRIVATE DirectHandle< Code > v8::internal::compiler::turboshaft::BuildWithTurboshaftAssemblerImpl (Isolate * isolate, Builtin builtin, TurboshaftAssemblerGenerator generator, std::function< compiler::CallDescriptor *(Zone *)> call_descriptor_builder, const char * name, const AssemblerOptions & options, CodeKind code_kind, std::optional< BytecodeHandlerData > bytecode_handler_data)
Definition at line 21 of file builtin-compiler.cc.
                                                            {
  using namespace compiler::turboshaft; // NOLINT(build/namespaces)
  DCHECK_EQ(code_kind == CodeKind::BYTECODE_HANDLER,
            bytecode_handler_data.has_value());
  compiler::ZoneStats zone_stats(isolate->allocator());
  ZoneWithName<kBuiltinCompilationZoneName> zone(&zone_stats,
                                                 kBuiltinCompilationZoneName);
  OptimizedCompilationInfo info(base::CStrVector(name), zone, code_kind,
                                builtin);
  compiler::CallDescriptor* call_descriptor = call_descriptor_builder(zone);
  PipelineData data(&zone_stats, TurboshaftPipelineKind::kTSABuiltin, isolate,
                    &info, options);
  data.InitializeBuiltinComponent(call_descriptor,
                                  std::move(bytecode_handler_data));
  data.InitializeGraphComponent(nullptr);
  ZoneWithName<kTempZoneName> temp_zone(&zone_stats, kTempZoneName);
  generator(&data, isolate, data.graph(), temp_zone);
  DirectHandle<Code> code =
      compiler::Pipeline::GenerateCodeForTurboshaftBuiltin(
          &data, call_descriptor, builtin, name,
          ProfileDataFromFile::TryRead(name))
          .ToHandleChecked();
  return code;
}
References v8::internal::Isolate::allocator(), code, v8::base::CStrVector(), DCHECK_EQ, v8::internal::compiler::Pipeline::GenerateCodeForTurboshaftBuiltin(), v8::internal::compiler::turboshaft::PipelineData::graph(), v8::internal::compiler::turboshaft::PipelineData::InitializeBuiltinComponent(), v8::internal::compiler::turboshaft::PipelineData::InitializeGraphComponent(), kBuiltinCompilationZoneName, kTempZoneName, kTSABuiltin, v8::internal::name, and v8::internal::ProfileDataFromFile::TryRead().
Referenced by v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuildWithTurboshaftAssemblerCS(), and v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuildWithTurboshaftAssemblerJS().
BuiltinCodeHandle()
Handle< Code > v8::internal::compiler::turboshaft::BuiltinCodeHandle (Builtin builtin, Isolate * isolate)
Definition at line 12 of file assembler.cc.
                                                                  {
  return isolate->builtins()->code_handle(builtin);
}
References v8::internal::Isolate::builtins(), and v8::internal::Builtins::code_handle().
Referenced by v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::BuiltinCode().
CanBeTyped()
template<typename Op >
bool v8::internal::compiler::turboshaft::CanBeTyped (const Op & operation) [inline]
Definition at line 31 of file type-inference-reducer.h.
                                               {
  return operation.outputs_rep().size() > 0;
}
Referenced by v8::internal::compiler::turboshaft::AssertTypesReducer< Next >::ReduceInputGraphOperation(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::ReduceInputGraphOperation(), v8::internal::compiler::turboshaft::TypedOptimizationsReducer< Next >::ReduceInputGraphOperation(), and v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::ReduceOperation().
CanBeUsedAsInput()
bool v8::internal::compiler::turboshaft::CanBeUsedAsInput (const Operation & op) [inline]
Definition at line 9457 of file operations.h.
                                                     {
  return op.Is<FrameStateOp>() || op.outputs_rep().size() > 0;
}
References v8::internal::compiler::turboshaft::Operation::Is(), and v8::internal::compiler::turboshaft::Operation::outputs_rep().
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitOpAndUpdateMapping(), and v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitOpNoMappingUpdate().
CannotSwapOperations()
bool v8::internal::compiler::turboshaft::CannotSwapOperations (OpEffects first, OpEffects second) [inline]
Definition at line 845 of file operations.h.
                                                                    {
  return first.produces.bits() & (second.consumes.bits());
}
References v8::internal::compiler::turboshaft::EffectDimensions::bits(), v8::internal::compiler::turboshaft::OpEffects::consumes, and v8::internal::compiler::turboshaft::OpEffects::produces.
Referenced by v8::internal::compiler::turboshaft::SLPTree::IsSideEffectFree().
CannotSwapProtectedLoads()
bool v8::internal::compiler::turboshaft::CannotSwapProtectedLoads (OpEffects first, OpEffects second) [inline]
Definition at line 849 of file operations.h.
                                                                        {
  EffectDimensions produces = first.produces;
  // The control flow effects produced by Loads are due to trap handler. We can
  // ignore this kind of effect when swapping two Loads that both have trap
  // handler.
  produces.control_flow = false;
  return produces.bits() & (second.consumes.bits());
}
References v8::internal::compiler::turboshaft::EffectDimensions::bits(), v8::internal::compiler::turboshaft::OpEffects::consumes, v8::internal::compiler::turboshaft::EffectDimensions::control_flow, and v8::internal::compiler::turboshaft::OpEffects::produces.
Referenced by v8::internal::compiler::turboshaft::SLPTree::IsSideEffectFree().
CombineFlagSettingOps()
void v8::internal::compiler::turboshaft::CombineFlagSettingOps (CompareChainNode * logic_node, InstructionSelector * selector, CompareSequence * sequence)
Definition at line 1666 of file instruction-selector-arm64.cc.
                                                      {
  CompareChainNode* lhs = logic_node->lhs();
  CompareChainNode* rhs = logic_node->rhs();
  Arm64OperandGenerator g(selector);
  if (!sequence->HasCompare()) {
    // This is the beginning of the conditional compare chain.
    DCHECK(lhs->IsFlagSetting());
    DCHECK(rhs->IsFlagSetting());
    {
      // ccmp has a much smaller immediate range than cmp, so swap the
      // operations if possible.
      OpIndex cmp = lhs->node();
      OpIndex ccmp = rhs->node();
      const Operation& cmp_op = selector->Get(cmp);
      const Operation& ccmp_op = selector->Get(ccmp);
      OpIndex cmp_right = cmp_op.input(1);
      OpIndex ccmp_right = ccmp_op.input(1);
      if (g.CanBeImmediate(cmp_right, kConditionalCompareImm) &&
          !g.CanBeImmediate(ccmp_right, kConditionalCompareImm)) {
        // If the ccmp could use the cmp immediate, swap them.
        std::swap(lhs, rhs);
      } else if (g.CanBeImmediate(ccmp_right, kArithmeticImm) &&
                 !g.CanBeImmediate(ccmp_right, kConditionalCompareImm)) {
        // If the ccmp can't use its immediate, but a cmp could, swap them.
        std::swap(lhs, rhs);
      }
    }
    OpIndex cmp = lhs->node();
    const ComparisonOp& cmp_op = selector->Cast<ComparisonOp>(cmp);
    // Initialize chain with the compare which will hold the continuation.
    sequence->InitialCompare(cmp, cmp_op.left(), cmp_op.right(), cmp_op.rep);
  }
  bool is_logical_or =
      selector->Get(logic_node->node()).Is<Opmask::kWord32BitwiseOr>();
  FlagsCondition ccmp_condition =
      is_logical_or ? NegateFlagsCondition(lhs->user_condition())
                    : lhs->user_condition();
  FlagsCondition default_flags =
      is_logical_or ? rhs->user_condition()
                    : NegateFlagsCondition(rhs->user_condition());
  // We canonicalise the chain so that the rhs is always a cmp, whereas lhs
  // will either be the initial cmp or the previous logic, now ccmp, op and
  // only provides ccmp_condition.
  FlagsCondition user_condition = rhs->user_condition();
  OpIndex ccmp = rhs->node();
  const ComparisonOp& ccmp_op = selector->Cast<ComparisonOp>(ccmp);
  OpIndex ccmp_lhs = ccmp_op.left();
  OpIndex ccmp_rhs = ccmp_op.right();
  // Switch ccmp lhs/rhs if lhs is a small immediate.
  if (g.CanBeImmediate(ccmp_lhs, kConditionalCompareImm)) {
    user_condition = CommuteFlagsCondition(user_condition);
    default_flags = CommuteFlagsCondition(default_flags);
    std::swap(ccmp_lhs, ccmp_rhs);
  }
  sequence->AddConditionalCompare(ccmp_op.rep, ccmp_condition, default_flags,
                                  ccmp_lhs, ccmp_rhs);
  // Ensure the user_condition is kept up-to-date for the next ccmp/cset.
  logic_node->SetCondition(user_condition);
}
References v8::internal::compiler::turboshaft::CompareSequence::AddConditionalCompare(), v8::internal::compiler::Arm64OperandGenerator::CanBeImmediate(), v8::internal::compiler::turboshaft::OperationMatcher::Cast(), v8::internal::compiler::CommuteFlagsCondition(), v8::internal::DCHECK(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::CompareSequence::HasCompare(), v8::internal::compiler::turboshaft::CompareSequence::InitialCompare(), v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::turboshaft::CompareChainNode::IsFlagSetting(), v8::internal::compiler::kArithmeticImm, v8::internal::compiler::kConditionalCompareImm, v8::internal::compiler::turboshaft::ComparisonOp::left(), v8::internal::compiler::turboshaft::CompareChainNode::lhs(), v8::internal::compiler::NegateFlagsCondition(), v8::internal::compiler::turboshaft::CompareChainNode::node(), v8::internal::compiler::turboshaft::ComparisonOp::rep, v8::internal::compiler::turboshaft::CompareChainNode::rhs(), v8::internal::compiler::turboshaft::ComparisonOp::right(), v8::internal::compiler::turboshaft::CompareChainNode::SetCondition(), and v8::internal::compiler::turboshaft::CompareChainNode::user_condition().
Referenced by TryMatchConditionalCompareChainShared().
CombineMinMax()
MapMaskAndOr v8::internal::compiler::turboshaft::CombineMinMax (MapMaskAndOr a, MapMaskAndOr b) [inline]
Definition at line 181 of file late-load-elimination-reducer.h.
                                                                  {
  return {a.or_ | b.or_, a.and_ & b.and_};
}
References v8::internal::compiler::turboshaft::MapMaskAndOr::and_, and v8::internal::compiler::turboshaft::MapMaskAndOr::or_.
Referenced by v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::BeginBlock(), and v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessAssumeMap().
ComputeMapHash()
MapMask v8::internal::compiler::turboshaft::ComputeMapHash (MapRef map) [inline]
Definition at line 161 of file late-load-elimination-reducer.h.
                                          {
  // `map.hash_value()` is probably not a good enough hash, since most user maps
  // will have the same upper bits, so we re-hash. We're using xorshift64* (from
  // "An experimental exploration of Marsaglias xorshift generators, scrambled"
  // by Vigna in ACM Transactions on Mathematical Software, Volume 42).
  MapMask hash = map.hash_value();
  hash ^= hash >> 12;
  hash ^= hash << 25;
  hash ^= hash >> 27;
  return hash * 0x2545f4914f6cdd1d;
}
Referenced by ComputeMinMaxHash().
ComputeMinMaxHash()
MapMaskAndOr v8::internal::compiler::turboshaft::ComputeMinMaxHash (ZoneRefSet< Map > maps) [inline]
Definition at line 172 of file late-load-elimination-reducer.h.
                                                            {
  MapMaskAndOr minmax;
  for (MapRef map : maps) {
    MapMask hash = ComputeMapHash(map);
    minmax.or_ |= hash;
    minmax.and_ &= hash;
  }
  return minmax;
}
References v8::internal::compiler::turboshaft::MapMaskAndOr::and_, ComputeMapHash(), and v8::internal::compiler::turboshaft::MapMaskAndOr::or_.
Referenced by v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessAssumeMap().
ConstOrV()
template<typename T >
v8::internal::compiler::turboshaft::ConstOrV (V< T >) -> ConstOrV< T >
CouldHaveSameMap()
bool v8::internal::compiler::turboshaft::CouldHaveSameMap (MapMaskAndOr a, MapMaskAndOr b) [inline]
Definition at line 185 of file late-load-elimination-reducer.h.
                                                             {
  return ((a.and_ & b.or_) == a.and_) || ((b.and_ & a.or_) == b.and_);
}
References v8::internal::compiler::turboshaft::MapMaskAndOr::and_, and v8::internal::compiler::turboshaft::MapMaskAndOr::or_.
Referenced by v8::internal::compiler::turboshaft::MemoryContentTable::InvalidateAtOffset().
CountDecimalDigits()
V8_EXPORT_PRIVATE int v8::internal::compiler::turboshaft::CountDecimalDigits (uint32_t value)
Definition at line 9 of file copying-phase.cc.
                                       {
  int result = 1;
  while (value > 9) {
    result++;
    value = value / 10;
  }
  return result;
}
References v8::base::internal::result, and v8::internal::value.
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::TraceReductionResult(), and v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::TraceReductionStart().
CreateAllocateBuiltinDescriptor()
const TSCallDescriptor * v8::internal::compiler::turboshaft::CreateAllocateBuiltinDescriptor (Zone * zone, Isolate * isolate)
Definition at line 15 of file memory-optimization-reducer.cc.
                                                                          {
  return TSCallDescriptor::Create(
      Linkage::GetStubCallDescriptor(
          zone, AllocateDescriptor{},
          AllocateDescriptor{}.GetStackParameterCount(),
          CallDescriptor::kCanUseRoots, Operator::kNoThrow,
          isolate != nullptr ? StubCallMode::kCallCodeObject
                             : StubCallMode::kCallBuiltinPointer),
      CanThrow::kNo, LazyDeoptOnThrow::kNo, zone);
}
References v8::internal::compiler::turboshaft::TSCallDescriptor::Create(), v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >::GetStackParameterCount(), v8::internal::compiler::Linkage::GetStubCallDescriptor(), v8::internal::kCallBuiltinPointer, v8::internal::kCallCodeObject, v8::internal::compiler::CallDescriptor::kCanUseRoots, v8::internal::compiler::kNo, and v8::internal::compiler::Operator::kNoThrow.
Referenced by v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::AllocateBuiltinDescriptor().
CreateOperation()
template<typename Op , typename... Args>
Op* v8::internal::compiler::turboshaft::CreateOperation (base::SmallVector< OperationStorageSlot, 32 > & storage, Args... args)
Definition at line 9586 of file operations.h.
                                  {
  size_t input_count = (0 + ... + detail::input_count(args));
  size_t size = Operation::StorageSlotCount(Op::opcode, input_count);
  storage.resize(size);
  Op* op = new (storage.data()) Op(args...);
  // Checking that the {input_count} we computed is at least the actual
  // input_count of the operation. {input_count} could be greater in the case of
  // OptionalOpIndex: they count for 1 input when computing {input_count} here,
  // but in Operations, they only count for 1 input when they are valid.
  DCHECK_GE(input_count, op->input_count);
  return op;
}
References v8::base::args, v8::base::SmallVector< T, kSize, Allocator >::data(), DCHECK_GE, v8::internal::compiler::turboshaft::detail::input_count(), v8::base::SmallVector< T, kSize, Allocator >::resize(), size(), and v8::internal::compiler::turboshaft::Operation::StorageSlotCount().
DEFINE_STRONG_ORDERING_COMPARISON()
v8::internal::compiler::turboshaft::DEFINE_STRONG_ORDERING_COMPARISON (OptionalOpIndex , OptionalOpIndex , l. value_or_invalid(), r. value_or_invalid())
ExecuteTurboshaftWasmCompilation()
wasm::WasmCompilationResult v8::internal::compiler::turboshaft::ExecuteTurboshaftWasmCompilation (wasm::CompilationEnv * env, compiler::WasmCompilationData & data, wasm::WasmDetectedFeatures * detected, Counters * counters)
Definition at line 21 of file wasm-turboshaft-compiler.cc.
                                                            {
  wasm::WasmCompilationResult result =
      Pipeline::GenerateWasmCode(env, data, detected, counters);
  DCHECK(result.succeeded());
  DCHECK_EQ(wasm::ExecutionTier::kTurbofan, result.result_tier);
  DCHECK_NULL(result.assumptions);
  result.assumptions = std::move(data.assumptions);
  DCHECK_IMPLIES(result.assumptions, !result.assumptions->empty());
  return result;
}
References v8::internal::compiler::WasmCompilationData::assumptions, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, DCHECK_NULL, v8::internal::wasm::kTurbofan, and v8::base::internal::result.
Referenced by v8::internal::wasm::WasmCompilationUnit::ExecuteCompilation().
EXPORT_TEMPLATE_DECLARE()
template class v8::internal::compiler::turboshaft::EXPORT_TEMPLATE_DECLARE (V8_EXPORT_PRIVATE)
EXPORT_TEMPLATE_DEFINE()
template class v8::internal::compiler::turboshaft::EXPORT_TEMPLATE_DEFINE (V8_EXPORT_PRIVATE)
fast_hash_combine() [1/4]
size_t v8::internal::compiler::turboshaft::fast_hash_combine () [inline]
Definition at line 20 of file fast-hash.h.
{ return 0u; }
Referenced by v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::ComputeHash(), fast_hash_combine(), fast_hash_range(), v8::internal::maglev::MaglevGraphBuilder::gvn_hash_value(), v8::internal::compiler::turboshaft::DeoptimizeIfOp::hash_value(), v8::internal::compiler::turboshaft::SwitchOp::hash_value(), hash_value(), v8::internal::compiler::turboshaft::wle::hash_value(), v8::internal::compiler::anonymous_namespace{pipeline.cc}::HashGraphForPGO(), v8::internal::compiler::turboshaft::OperationT< Derived >::HashWithOptions(), v8::internal::compiler::turboshaft::fast_hash< std::tuple< Ts... > >::impl(), v8::internal::compiler::turboshaft::fast_hash< std::pair< T1, T2 > >::operator()(), v8::internal::compiler::turboshaft::fast_hash< TSCallDescriptor >::operator()(), and v8::internal::compiler::turboshaft::fast_hash< SwitchOp::Case >::operator()().
fast_hash_combine() [2/4]
size_t v8::internal::compiler::turboshaft::fast_hash_combine (size_t acc) [inline]
Definition at line 21 of file fast-hash.h.
{ return acc; }
fast_hash_combine() [3/4]
size_t v8::internal::compiler::turboshaft::fast_hash_combine (size_t acc, size_t value) [inline]
Definition at line 22 of file fast-hash.h.
                                                             {
  return 17 * acc + value;
}
References v8::internal::value.
fast_hash_combine() [4/4]
template<typename T , typename... Ts>
size_t v8::internal::compiler::turboshaft::fast_hash_combine (T const & v, Ts const &... vs) [inline]
Definition at line 67 of file fast-hash.h.
                                                                {
  return fast_hash_combine(fast_hash_combine(vs...), fast_hash<T>()(v));
}
References fast_hash_combine(), and v8::internal::vs.
fast_hash_range()
template<typename Iterator >
size_t v8::internal::compiler::turboshaft::fast_hash_range (Iterator first, Iterator last) [inline]
Definition at line 72 of file fast-hash.h.
                                                                {
  size_t acc = 0;
  for (; first != last; ++first) {
    acc = fast_hash_combine(acc, *first);
  }
  return acc;
}
References fast_hash_combine().
Referenced by v8::internal::compiler::turboshaft::fast_hash< base::Vector< T > >::operator()().
FindCompareChain()
static std::optional<CompareChainNode*> v8::internal::compiler::turboshaft::FindCompareChain (OpIndex user, OpIndex node, InstructionSelector * selector, Zone * zone, ZoneVector< CompareChainNode * > & nodes) [static]
Definition at line 1535 of file instruction-selector-arm64.cc.
                                          {
  const Operation& op = selector->Get(node);
  if (op.Is<Opmask::kWord32BitwiseAnd>() || op.Is<Opmask::kWord32BitwiseOr>()) {
    const WordBinopOp& binop = op.Cast<WordBinopOp>();
    auto maybe_lhs =
        FindCompareChain(node, binop.left(), selector, zone, nodes);
    auto maybe_rhs =
        FindCompareChain(node, binop.right(), selector, zone, nodes);
    if (maybe_lhs.has_value() && maybe_rhs.has_value()) {
      CompareChainNode* lhs = maybe_lhs.value();
      CompareChainNode* rhs = maybe_rhs.value();
      // Ensure we don't try to combine a logic operation with two logic inputs.
      if (lhs->IsFlagSetting() || rhs->IsFlagSetting()) {
        nodes.push_back(std::move(zone->New<CompareChainNode>(node, lhs, rhs)));
        return nodes.back();
      }
    }
    // Ensure we remove any valid sub-trees that now cannot be used.
    nodes.clear();
    return std::nullopt;
  } else if (user.valid() && selector->CanCover(user, node)) {
    std::optional<FlagsCondition> user_condition =
        GetFlagsCondition(node, selector);
    if (!user_condition.has_value()) {
      return std::nullopt;
    }
    const ComparisonOp& comparison = selector->Cast<ComparisonOp>(node);
    if (comparison.kind == ComparisonOp::Kind::kEqual &&
        selector->MatchIntegralZero(comparison.right())) {
      auto maybe_negated =
          FindCompareChain(node, comparison.left(), selector, zone, nodes);
      if (maybe_negated.has_value()) {
        CompareChainNode* negated = maybe_negated.value();
        negated->MarkRequiresNegation();
        return negated;
      }
    }
    return zone->New<CompareChainNode>(node, user_condition.value());
  }
  return std::nullopt;
}
References v8::internal::ZoneVector< T >::back(), v8::internal::compiler::InstructionSelector::CanCover(), v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::compiler::turboshaft::OperationMatcher::Cast(), v8::internal::ZoneVector< T >::clear(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), GetFlagsCondition(), v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::compiler::turboshaft::CompareChainNode::IsFlagSetting(), v8::internal::compiler::turboshaft::ComparisonOp::kEqual, v8::internal::compiler::turboshaft::ComparisonOp::kind, v8::internal::compiler::turboshaft::ComparisonOp::left(), v8::internal::compiler::turboshaft::WordBinopOp::left(), v8::internal::compiler::turboshaft::CompareChainNode::MarkRequiresNegation(), v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralZero(), v8::internal::Zone::New(), v8::internal::ZoneVector< T >::push_back(), v8::internal::compiler::turboshaft::ComparisonOp::right(), v8::internal::compiler::turboshaft::WordBinopOp::right(), and v8::internal::compiler::turboshaft::OpIndex::valid().
Referenced by TryMatchConditionalCompareChainShared().
ForEach() [1/2]
template<typename FunctionType >
void v8::internal::compiler::turboshaft::ForEach (FunctionType callback, const ZoneUnorderedMap< OpIndex, PackNode * > & node_map)
Definition at line 251 of file wasm-revec-reducer.cc.
                                                                   {
  absl::flat_hash_set<PackNode const*> visited;
  for (auto& entry : node_map) {
    PackNode const* pnode = entry.second;
    if (!pnode || visited.find(pnode) != visited.end()) {
      continue;
    }
    visited.insert(pnode);
    callback(pnode);
  }
}
Referenced by v8::internal::compiler::turboshaft::WasmRevecAnalyzer::DecideVectorize(), v8::internal::compiler::turboshaft::SLPTree::Print(), and v8::internal::compiler::turboshaft::WasmRevecAnalyzer::Print().
ForEach() [2/2]
template<typename FunctionType >
void v8::internal::compiler::turboshaft::ForEach (FunctionType callback, const ZoneUnorderedMap< OpIndex, ZoneVector< PackNode * >> & node_map)
Definition at line 267 of file wasm-revec-reducer.cc.
                                                                               {
  absl::flat_hash_set<PackNode const*> visited;
  for (const auto& entry : node_map) {
    for (auto* pnode : entry.second) {
      if (visited.find(pnode) != visited.end()) {
        continue;
      }
      visited.insert(pnode);
      callback(pnode);
    }
  }
}
Get()
V8_EXPORT_PRIVATE const Operation & v8::internal::compiler::turboshaft::Get (const Graph & graph, OpIndex index) [inline]
Definition at line 1242 of file graph.h.
                                                                  {
  return graph.Get(index);
}
References graph(), and v8::internal::index.
Referenced by v8::internal::torque::anonymous_namespace{torque-parser.cc}::AddGlobalDeclarations(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphCheckException(), cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::Assign(), v8::internal::wasm::TurboshaftGraphBuildingInterface::AtomicOp(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::AtomicRMW(), cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::BasicPersistent(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::Bind(), v8::internal::compiler::IA32OperandGenerator::CanBeImmediate(), v8::internal::compiler::turboshaft::GenericReducerBase< Next >::CatchBlockBegin(), v8::internal::anonymous_namespace{intl-objects.cc}::CharCanFastCompareOrOutOfBounds(), v8::internal::anonymous_namespace{intl-objects.cc}::CharIsAsciiOrOutOfBounds(), v8::internal::torque::anonymous_namespace{declarations.cc}::CheckAlreadyDeclared(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::CheckPairOrPairOp(), v8::internal::compiler::turboshaft::DebugFeatureLoweringReducer< Next >::CheckTurboshaftTypeOf(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::CheckTurboshaftTypeOf(), v8::internal::torque::anonymous_namespace{torque-compiler.cc}::CompileCurrentAst(), v8::internal::torque::CompileTorque(), v8::internal::torque::CompileTorqueForKythe(), v8::internal::torque::TypeVisitor::ComputeType(), v8::PersistentValueMapBase< K, V, Traits >::Contains(), v8::internal::compiler::turboshaft::LayeredHashMap< Key, Value >::Contains(), v8::internal::wasm::NativeModuleDeserializer::CopyAndRelocate(), v8::internal::torque::TypeOracle::CreateGenericTypeInstantiationNamespace(), v8::internal::torque::ImplementationVisitor::csa_ccfile(), v8::internal::torque::ImplementationVisitor::csa_headerfile(), v8::internal::torque::CurrentNamespace(), v8::internal::torque::Declarations::Declare(), v8::internal::torque::Ast::DeclareImportForCurrentFile(), v8::internal::torque::Declarations::DeclareMacro(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::DeoptimizeIf(), v8::internal::ContextDeserializer::DeserializeApiWrapperFields(), v8::internal::ContextDeserializer::DeserializeEmbedderFields(), v8::internal::compiler::turboshaft::GenericReducerBase< Next >::FastApiCall(), cppgc::internal::anonymous_namespace{sweeper.cc}::SweepFinalizer::FinalizePage(), v8::internal::compiler::turboshaft::GenericReducerBase< Next >::FixLoopPhi(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::FixLoopPhi(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::FixLoopPhi(), cppgc::internal::GlobalGCInfoTable::GCInfoFromIndex(), v8::internal::torque::ImplementationVisitor::GenerateArrayLength(), v8::internal::torque::ImplementationVisitor::GenerateBuiltinDefinitionsAndInterfaceDescriptors(), v8::internal::torque::ImplementationVisitor::GenerateCall(), v8::internal::torque::ImplementationVisitor::GenerateEnumVerifiers(), v8::internal::compiler::IA32OperandGenerator::GenerateMemoryOperandInputs(), v8::base::ContextualVariableWithDefault< Derived, VarType, default_args >::Get(), v8::PersistentValueMapBase< K, V, Traits >::Get(), cppgc::internal::WriteBarrierTypeForNonCagedHeapPolicy::Get(), v8::internal::torque::ImplementationVisitor::GetAndClearReturnValue(), v8::internal::interpreter::BytecodeGenerator::GetCachedLoadGlobalICSlot(), v8::internal::interpreter::BytecodeGenerator::GetCachedLoadICSlot(), v8::internal::interpreter::BytecodeGenerator::GetCachedLoadSuperICSlot(), v8::internal::interpreter::BytecodeGenerator::GetCachedStoreGlobalICSlot(), v8::internal::interpreter::BytecodeGenerator::GetCachedStoreICSlot(), v8::internal::torque::TypeOracle::GetClasses(), v8::internal::compiler::IA32OperandGenerator::GetEffectiveAddressMemoryOperand(), v8::internal::compiler::S390OperandGenerator::GetEffectiveAddressMemoryOperand(), v8::internal::compiler::X64OperandGenerator::GetEffectiveAddressMemoryOperand(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::GetExtractOpIfNeeded(), cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::GetFromGC(), v8::internal::torque::TypeOracle::GetGenericTypeInstance(), v8::internal::compiler::IA32OperandGenerator::GetImmediateIntegerValue(), v8_inspector::InspectedContext::getInternalType(), v8::internal::torque::ImplementationVisitor::GetLocationReference(), v8::internal::anonymous_namespace{compiler.cc}::GetOrCompileOptimized(), v8::Object::GetPrivate(), v8::PersistentValueMapBase< K, V, Traits >::GetReference(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::GetStringEncoding(), v8::internal::LookupIterator::GetStringPropertyValue(), v8::internal::torque::GlobalContext::GlobalContext(), v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::Goto(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::Goto(), v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::HandleTorqueFileListNotification(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::IndexedDebugProxy< T, id, Provider >::IndexedDescriptor(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::IndexedDebugProxy< T, id, Provider >::IndexedGetter(), v8::ExecArgs::Init(), v8::internal::torque::ImplementationVisitor::InlineMacro(), v8::internal::compiler::InstructionSelector::Inputs(), v8::internal::compiler::turboshaft::AssertTypesReducer< Next >::InsertTypeAssert(), v8::internal::compiler::InstructionSelector::is_load(), v8::internal::compiler::turboshaft::InstructionSelectionNormalizationReducer< Next >::IsComplexConstant(), v8::internal::compiler::Arm64OperandGenerator::IsImmediateZero(), v8::internal::compiler::InstructionSelector::IsLoadOrLoadImmutable(), v8::internal::compiler::InstructionSelector::IsRetain(), v8::internal::compiler::turboshaft::SLPTree::IsSideEffectFree(), v8::internal::compiler::turboshaft::InstructionSelectionNormalizationReducer< Next >::IsSimpleConstant(), v8::internal::compiler::turboshaft::LateLoadEliminationReducer< Next >::Load(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeEnumDeclaration(), v8::internal::torque::MakeNode(), cppgc::internal::anonymous_namespace{object-allocator.cc}::MarkRangeAsYoung(), v8::internal::compiler::turboshaft::DuplicationOptimizationReducer< Next >::MaybeCanDuplicateGenericBinop(), v8::internal::compiler::turboshaft::DuplicationOptimizationReducer< Next >::MaybeDuplicateOutputGraphShift(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::MergeFrameState(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::MergeOpIndices(), v8::internal::torque::MessageBuilder::MessageBuilder(), v8::Shell::ModuleResolutionSuccessCallback(), v8::internal::Map::Normalize(), cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator bool(), cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator bool(), cppgc::internal::BasicMember< K >::operator K*(), v8::internal::compiler::turboshaft::Var< T, Assembler >::operator OpIndex(), v8::internal::compiler::turboshaft::Var< T, Assembler >::operator OptionalOpIndex(), cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator T*(), cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator T*(), v8::internal::compiler::turboshaft::Var< T, Assembler >::operator V<U >(), cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator*(), cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::operator*(), cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator*(), cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator->(), cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::operator->(), cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator->(), cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator=(), cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator=(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Parameter(), v8::internal::torque::ls::ParseJson(), v8::internal::compiler::turboshaft::RequiredOptimizationReducer< Next >::Phi(), v8::internal::String::PrintOn(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::ProcessTorqueImportDeclaration(), v8_inspector::V8Debugger::queryObjects(), v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::RecompileTorque(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::ReduceInputsOfOp(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::ReduceOperation(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::RefineOperationType(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::RefineTypeFromInputGraph(), cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::Release(), cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::Release(), cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::Release(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::RemoveLast(), v8::internal::torque::MessageBuilder::Report(), v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::ResetCompilationErrorDiagnostics(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::Run(), v8::internal::torque::RunEarleyAlgorithm(), v8::internal::RUNTIME_FUNCTION(), v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::SendCompilationDiagnostics(), v8::PersistentValueMapBase< K, V, Traits >::SetReturnValue(), v8::internal::torque::ImplementationVisitor::SetReturnValue(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::SetType(), v8::internal::String::SlowEquals(), v8::internal::torque::DeclarationVisitor::SpecializeImplicit(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::StartMultiPredecessorExceptionBlock(), v8::internal::compiler::turboshaft::LoadStoreSimplificationReducer< Next >::Store(), v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::StringLength(), cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::To(), cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::To(), v8::internal::torque::anonymous_namespace{earley-parser.cc}::LineAndColumnTracker::ToSourcePosition(), v8::internal::torque::Declarations::TryLookup(), v8::internal::torque::ImplementationVisitor::TryLookupLabel(), v8::internal::torque::ImplementationVisitor::TryLookupLocalValue(), v8::internal::torque::Declarations::TryLookupShallow(), v8::internal::compiler::turboshaft::DeadCodeEliminationReducer< Next >::TryRewriteBranch(), v8::internal::compiler::Arm64OperandGenerator::UseImmediateOrTemp(), v8::internal::compiler::Loong64OperandGenerator::UseRegisterOrImmediateZero(), v8::internal::compiler::Mips64OperandGenerator::UseRegisterOrImmediateZero(), v8::internal::compiler::RiscvOperandGenerator::UseRegisterOrImmediateZero(), v8::internal::compiler::turboshaft::ChangeOrDeoptOp::Validate(), v8::internal::compiler::turboshaft::FrameStateOp::Validate(), v8::internal::compiler::turboshaft::DeoptimizeOp::Validate(), v8::internal::compiler::turboshaft::DeoptimizeIfOp::Validate(), v8::internal::compiler::turboshaft::CallOp::Validate(), v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOrDeoptOp::Validate(), v8::internal::compiler::turboshaft::ConvertJSPrimitiveToUntaggedOrDeoptOp::Validate(), v8::internal::compiler::turboshaft::TruncateJSPrimitiveToUntaggedOrDeoptOp::Validate(), v8::internal::compiler::turboshaft::BigIntBinopOp::Validate(), v8::internal::compiler::turboshaft::CheckMapsOp::Validate(), v8::internal::compiler::turboshaft::CheckedClosureOp::Validate(), v8::internal::compiler::turboshaft::CheckEqualsInternalizedStringOp::Validate(), v8::internal::compiler::turboshaft::MaybeGrowFastElementsOp::Validate(), v8::internal::torque::ImplementationVisitor::Visit(), v8::internal::compiler::InstructionSelector::VisitBitcastWord32PairToFloat64(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitBlockBody(), cppgc::internal::MarkingVerifierBase::VisitHeapObjectHeader(), v8::internal::compiler::VisitWordCompare(), v8::internal::compiler::InstructionSelector::VisitWordCompareZero(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordBinop(), v8_inspector::V8ConsoleMessage::wrapArguments(), and v8::internal::wasm::NativeModuleSerializer::WriteCode().
get_zone()
V8_EXPORT_PRIVATE Zone * v8::internal::compiler::turboshaft::get_zone (Graph * graph)
Definition at line 45 of file operations.cc.
{ return graph->graph_zone(); }
References graph().
Referenced by v8::internal::compiler::turboshaft::OperationT< Derived >::New().
GetFlagsCondition()
static std::optional<FlagsCondition> v8::internal::compiler::turboshaft::GetFlagsCondition (OpIndex node, InstructionSelector * selector) [static]
Definition at line 1481 of file instruction-selector-arm64.cc.
                                                 {
  if (const ComparisonOp* comparison =
          selector->Get(node).TryCast<ComparisonOp>()) {
    if (comparison->rep == RegisterRepresentation::Word32() ||
        comparison->rep == RegisterRepresentation::Word64() ||
        comparison->rep == RegisterRepresentation::Tagged()) {
      switch (comparison->kind) {
        case ComparisonOp::Kind::kEqual:
          return FlagsCondition::kEqual;
        case ComparisonOp::Kind::kSignedLessThan:
          return FlagsCondition::kSignedLessThan;
        case ComparisonOp::Kind::kSignedLessThanOrEqual:
          return FlagsCondition::kSignedLessThanOrEqual;
        case ComparisonOp::Kind::kUnsignedLessThan:
          return FlagsCondition::kUnsignedLessThan;
        case ComparisonOp::Kind::kUnsignedLessThanOrEqual:
          return FlagsCondition::kUnsignedLessThanOrEqual;
        default:
          UNREACHABLE();
      }
    } else if (comparison->rep == RegisterRepresentation::Float32() ||
               comparison->rep == RegisterRepresentation::Float64()) {
      switch (comparison->kind) {
        case ComparisonOp::Kind::kEqual:
          return FlagsCondition::kEqual;
        case ComparisonOp::Kind::kSignedLessThan:
          return FlagsCondition::kFloatLessThan;
        case ComparisonOp::Kind::kSignedLessThanOrEqual:
          return FlagsCondition::kFloatLessThanOrEqual;
        default:
          UNREACHABLE();
      }
    }
  }
  return std::nullopt;
}
References v8::internal::compiler::turboshaft::RegisterRepresentation::Float32(), v8::internal::compiler::turboshaft::RegisterRepresentation::Float64(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::kEqual, v8::internal::compiler::turboshaft::ComparisonOp::kEqual, v8::internal::compiler::kFloatLessThan, v8::internal::compiler::kFloatLessThanOrEqual, v8::internal::compiler::kSignedLessThan, v8::internal::compiler::turboshaft::ComparisonOp::kSignedLessThan, v8::internal::compiler::kSignedLessThanOrEqual, v8::internal::compiler::turboshaft::ComparisonOp::kSignedLessThanOrEqual, v8::internal::kUnsignedLessThan, v8::internal::compiler::turboshaft::ComparisonOp::kUnsignedLessThan, v8::internal::compiler::kUnsignedLessThanOrEqual, v8::internal::compiler::turboshaft::ComparisonOp::kUnsignedLessThanOrEqual, v8::internal::compiler::turboshaft::RegisterRepresentation::Tagged(), v8::internal::compiler::turboshaft::Operation::TryCast(), v8::internal::UNREACHABLE(), v8::internal::compiler::turboshaft::RegisterRepresentation::Word32(), and v8::internal::compiler::turboshaft::RegisterRepresentation::Word64().
Referenced by FindCompareChain().
GetSimdOpcodeName()
std::string v8::internal::compiler::turboshaft::GetSimdOpcodeName (Operation const & op)
Definition at line 45 of file wasm-revec-reducer.cc.
                                                 {
  std::ostringstream oss;
  if (op.Is<Simd128BinopOp>() || op.Is<Simd128UnaryOp>() ||
      op.Is<Simd128ShiftOp>() || op.Is<Simd128TestOp>() ||
      op.Is<Simd128TernaryOp>()) {
    op.PrintOptions(oss);
  } else {
    oss << OpcodeName(op.opcode);
  }
  return oss.str();
}
References v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::compiler::turboshaft::Operation::opcode, OpcodeName(), and v8::internal::compiler::turboshaft::Operation::PrintOptions().
Referenced by v8::internal::compiler::turboshaft::SLPTree::BuildTreeRec(), v8::internal::compiler::turboshaft::SLPTree::CanBePacked(), v8::internal::compiler::turboshaft::SLPTree::NewBundlePackNode(), v8::internal::compiler::turboshaft::SLPTree::NewForcePackNode(), v8::internal::compiler::turboshaft::SLPTree::NewIntersectPackNode(), v8::internal::compiler::turboshaft::SLPTree::NewPackNode(), v8::internal::compiler::turboshaft::SLPTree::NewShufflePackNode(), and v8::internal::compiler::turboshaft::PackNode::Print().
hash_value() [1/8]
size_t v8::internal::compiler::turboshaft::hash_value (BlockIndex op) [inline]
Definition at line 901 of file index.h.
{ return base::hash_value(op.id()); }
References v8::base::hash_value(), and v8::internal::compiler::turboshaft::BlockIndex::id().
hash_value() [2/8]
size_t v8::internal::compiler::turboshaft::hash_value (LoadOp::Kind kind) [inline]
Definition at line 3082 of file operations.h.
                                             {
  return base::hash_value(
      static_cast<int>(kind.tagged_base) | (kind.maybe_unaligned << 1) |
      (kind.load_eliminable << 2) | (kind.is_immutable << 3) |
      (kind.with_trap_handler << 4) | (kind.is_atomic << 5));
}
References v8::base::hash_value(), v8::internal::compiler::turboshaft::LoadOp::Kind::is_atomic, v8::internal::compiler::turboshaft::LoadOp::Kind::is_immutable, v8::internal::compiler::turboshaft::LoadOp::Kind::load_eliminable, v8::internal::compiler::turboshaft::LoadOp::Kind::maybe_unaligned, v8::internal::compiler::turboshaft::LoadOp::Kind::tagged_base, and v8::internal::compiler::turboshaft::LoadOp::Kind::with_trap_handler.
hash_value() [3/8]
size_t v8::internal::compiler::turboshaft::hash_value (MaybeRegisterRepresentation rep) [inline]
Definition at line 358 of file representations.h.
                                                             {
  return static_cast<size_t>(rep.value());
}
References v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::value().
hash_value() [4/8]
size_t v8::internal::compiler::turboshaft::hash_value (MemoryAddress const & mem) [inline]
Definition at line 210 of file late-load-elimination-reducer.h.
                                                   {
  return fast_hash_combine(mem.base, mem.index, mem.offset,
                           mem.element_size_log2, mem.size);
}
References v8::internal::compiler::turboshaft::MemoryAddress::base, v8::internal::compiler::turboshaft::MemoryAddress::element_size_log2, fast_hash_combine(), v8::internal::compiler::turboshaft::MemoryAddress::index, v8::internal::compiler::turboshaft::MemoryAddress::offset, and v8::internal::compiler::turboshaft::MemoryAddress::size.
hash_value() [5/8]
size_t v8::internal::compiler::turboshaft::hash_value (MemoryRepresentation rep) [inline]
Definition at line 947 of file representations.h.
                                                      {
  return static_cast<size_t>(rep.value());
}
References v8::internal::compiler::turboshaft::MemoryRepresentation::value().
hash_value() [6/8]
size_t v8::internal::compiler::turboshaft::hash_value (OpEffects effects) [inline]
Definition at line 841 of file operations.h.
                                               {
  return static_cast<size_t>(effects.bits());
}
References v8::internal::compiler::turboshaft::OpEffects::bits().
hash_value() [7/8]
size_t v8::internal::compiler::turboshaft::hash_value (OpIndex op) [inline]
Definition at line 779 of file index.h.
{ return base::hash_value(op.hash()); }
References v8::internal::compiler::turboshaft::OpIndex::hash(), and v8::base::hash_value().
hash_value() [8/8]
size_t v8::internal::compiler::turboshaft::hash_value (OptionalOpIndex op) [inline]
Definition at line 780 of file index.h.
                                                {
  return base::hash_value(op.hash());
}
References v8::internal::compiler::turboshaft::OptionalOpIndex::hash(), and v8::base::hash_value().
InitVectorOf()
template<typename T >
base::Vector<T> v8::internal::compiler::turboshaft::InitVectorOf (ZoneVector< T > & storage, std::initializer_list< RegisterRepresentation > values) [inline]
Definition at line 471 of file operations.h.
                                                        {
  storage.resize(values.size());
  size_t i = 0;
  for (auto&& value : values) {
    storage[i++] = value;
  }
  return base::VectorOf(storage);
}
References v8::internal::ZoneVector< T >::resize(), v8::internal::value, and v8::base::VectorOf().
Referenced by v8::internal::compiler::turboshaft::ShiftOp::inputs_rep(), v8::internal::compiler::turboshaft::SelectOp::inputs_rep(), v8::internal::compiler::turboshaft::AtomicRMWOp::inputs_rep(), v8::internal::compiler::turboshaft::StoreOp::inputs_rep(), v8::internal::compiler::turboshaft::StoreTypedElementOp::inputs_rep(), v8::internal::compiler::turboshaft::StoreDataViewElementOp::inputs_rep(), and v8::internal::compiler::turboshaft::TransitionAndStoreArrayElementOp::inputs_rep().
is_empty()
bool v8::internal::compiler::turboshaft::is_empty (MapMaskAndOr minmax) [inline]
Definition at line 158 of file late-load-elimination-reducer.h.
                                          {
  return minmax.or_ == 0 && minmax.and_ == -1ull;
}
References v8::internal::compiler::turboshaft::MapMaskAndOr::and_, and v8::internal::compiler::turboshaft::MapMaskAndOr::or_.
Referenced by v8::internal::maglev::RegisterFrameState< RegisterT >::AllocateRegister(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::BeginBlock(), v8::internal::BIT_FIELD_ACCESSORS(), v8::internal::interpreter::BytecodeGenerator::BuildCreateArrayLiteral(), cppgc::internal::anonymous_namespace{sweeper.cc}::InlinedFinalizationBuilder< FreeHandler >::GetResult(), cppgc::internal::anonymous_namespace{sweeper.cc}::DeferredFinalizationBuilder< FreeHandler >::GetResult(), v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::Include(), v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::IncludeDouble(), v8::internal::compiler::turboshaft::MemoryContentTable::InvalidateAtOffset(), cppgc::internal::PersistentRegionBase::Iterate(), v8::internal::MacroAssembler::MultiPop(), v8::internal::MacroAssembler::MultiPush(), cppgc::internal::anonymous_namespace{sweeper.cc}::SweepNormalPage(), and v8::internal::VerifyHandleIsNonEmpty().
IsBlockTerminator()
constexpr bool v8::internal::compiler::turboshaft::IsBlockTerminator (Opcode opcode) [inline], [constexpr]
Definition at line 418 of file operations.h.
                                                       {
  return OpcodeIndex(opcode) < kNumberOfBlockTerminatorOpcodes;
}
References kNumberOfBlockTerminatorOpcodes, and OpcodeIndex().
Referenced by v8::internal::compiler::turboshaft::OperationT< Derived >::IsBlockTerminator(), v8::internal::compiler::turboshaft::Operation::IsBlockTerminator(), v8::internal::compiler::turboshaft::Operation::IsRequiredWhenUnused(), and v8::internal::compiler::turboshaft::OperationT< Derived >::IsRequiredWhenUnused().
IsInt32TruncatedLoadPattern()
V8_EXPORT_PRIVATE bool v8::internal::compiler::turboshaft::IsInt32TruncatedLoadPattern (const Graph & graph, OpIndex change_idx, const ChangeOp & change, OpIndex * bitcast_idx, OpIndex * load_idx)
Definition at line 587 of file late-load-elimination-reducer.cc.
                                                    {
  DCHECK_EQ(change_idx, graph.Index(change));
  if (!change.Is<Opmask::kTruncateWord64ToWord32>()) return false;
  const TaggedBitcastOp* bitcast =
      graph.Get(change.input())
          .TryCast<Opmask::kBitcastTaggedToWordPtrForTagAndSmiBits>();
  if (bitcast == nullptr) return false;
  // We require that the bitcast has no other uses. This could be slightly
  // generalized by allowing multiple int32-truncating uses, but that is more
  // expensive to detect and it is very unlikely that we ever see such a case
  // (e.g. because of GVN).
  if (!bitcast->saturated_use_count.IsOne()) return false;
  const LoadOp* load = graph.Get(bitcast->input()).TryCast<LoadOp>();
  if (load == nullptr) return false;
  if (load->loaded_rep.SizeInBytesLog2() !=
      MemoryRepresentation::Int32().SizeInBytesLog2()) {
    return false;
  }
  if (bitcast_idx) *bitcast_idx = change.input();
  if (load_idx) *load_idx = bitcast->input();
  return true;
}
References DCHECK_EQ, graph(), v8::internal::compiler::turboshaft::ChangeOp::input(), v8::internal::compiler::turboshaft::TaggedBitcastOp::input(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int32(), v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::compiler::turboshaft::SaturatedUint8::IsOne(), v8::internal::compiler::turboshaft::LoadOp::loaded_rep, v8::internal::compiler::turboshaft::Operation::saturated_use_count, and v8::internal::compiler::turboshaft::MemoryRepresentation::SizeInBytesLog2().
Referenced by v8::internal::compiler::turboshaft::LateLoadEliminationReducer< Next >::Change(), and v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessChange().
IsLoadExtend()
bool v8::internal::compiler::turboshaft::IsLoadExtend (const Simd128LoadTransformOp & op)
Definition at line 897 of file wasm-revec-reducer.cc.
                                                    {
  switch (op.transform_kind) {
    case Simd128LoadTransformOp::TransformKind::k8x8S:
    case Simd128LoadTransformOp::TransformKind::k8x8U:
    case Simd128LoadTransformOp::TransformKind::k16x4S:
    case Simd128LoadTransformOp::TransformKind::k16x4U:
    case Simd128LoadTransformOp::TransformKind::k32x2S:
    case Simd128LoadTransformOp::TransformKind::k32x2U:
      return true;
    default:
      return false;
  }
}
Referenced by v8::internal::compiler::turboshaft::SLPTree::BuildTreeRec().
IsLoadSplat()
bool v8::internal::compiler::turboshaft::IsLoadSplat (const Simd128LoadTransformOp & op)
Definition at line 911 of file wasm-revec-reducer.cc.
                                                   {
  switch (op.transform_kind) {
    case Simd128LoadTransformOp::TransformKind::k8Splat:
    case Simd128LoadTransformOp::TransformKind::k16Splat:
    case Simd128LoadTransformOp::TransformKind::k32Splat:
    case Simd128LoadTransformOp::TransformKind::k64Splat:
      return true;
    default:
      return false;
  }
}
Referenced by v8::internal::compiler::turboshaft::SLPTree::BuildTreeRec().
IsSameOpAndKind()
bool v8::internal::compiler::turboshaft::IsSameOpAndKind (const Operation & op0, const Operation & op1)
Definition at line 24 of file wasm-revec-reducer.cc.
                                                                 {
#define CASE(operation) \
  case Opcode::k##operation: { \
    using Op = operation##Op; \
    return op0.Cast<Op>().kind == op1.Cast<Op>().kind; \
  }
  if (op0.opcode != op1.opcode) {
    return false;
  }
  switch (op0.opcode) {
    CASE(Simd128Unary)
    CASE(Simd128Binop)
    CASE(Simd128Shift)
    CASE(Simd128Ternary)
    CASE(Simd128Splat)
    default:
      return true;
  }
#undef CASE
}
References CASE, and v8::internal::compiler::turboshaft::Operation::opcode.
Referenced by v8::internal::compiler::turboshaft::SLPTree::CanBePacked(), v8::internal::compiler::turboshaft::SLPTree::NewCommutativePackNodeAndRecurs(), and v8::internal::compiler::turboshaft::WasmRevecAnalyzer::ProcessBlock().
IsSignExtensionOp()
bool v8::internal::compiler::turboshaft::IsSignExtensionOp (Operation & op)
Definition at line 839 of file wasm-revec-reducer.cc.
                                      {
  if (const Simd128UnaryOp* unop = op.TryCast<Simd128UnaryOp>()) {
    return unop->kind >= Simd128UnaryOp::Kind::kFirstSignExtensionOp &&
           unop->kind <= Simd128UnaryOp::Kind::kLastSignExtensionOp;
  } else if (const Simd128BinopOp* binop = op.TryCast<Simd128BinopOp>()) {
    return binop->kind >= Simd128BinopOp::Kind::kFirstSignExtensionOp &&
           binop->kind <= Simd128BinopOp::Kind::kLastSignExtensionOp;
  }
  return false;
}
References v8::internal::compiler::turboshaft::Operation::TryCast().
Referenced by v8::internal::compiler::turboshaft::SLPTree::CanBePacked().
IsSplat()
template<typename T >
bool v8::internal::compiler::turboshaft::IsSplat (const T & node_group)
Definition at line 223 of file wasm-revec-reducer.cc.
                                  {
  DCHECK_EQ(node_group.size(), 2);
  return node_group[1] == node_group[0];
}
References DCHECK_EQ.
Referenced by v8::internal::compiler::turboshaft::SLPTree::BuildTreeRec(), and v8::internal::compiler::turboshaft::WasmRevecAnalyzer::DecideVectorize().
IsUnlikelySuccessor()
bool v8::internal::compiler::turboshaft::IsUnlikelySuccessor (const Block * block, const Block * successor, const Graph & graph)
Definition at line 2182 of file operations.cc.
                                             {
  DCHECK(base::contains(successor->Predecessors(), block));
  const Operation& terminator = block->LastOperation(graph);
  switch (terminator.opcode) {
    case Opcode::kCheckException: {
      const CheckExceptionOp& check_exception =
          terminator.Cast<CheckExceptionOp>();
      return successor == check_exception.catch_block;
    }
    case Opcode::kGoto:
      return false;
    case Opcode::kBranch: {
      const BranchOp& branch = terminator.Cast<BranchOp>();
      return (branch.hint == BranchHint::kTrue &&
              successor == branch.if_false) ||
             (branch.hint == BranchHint::kFalse && successor == branch.if_true);
    }
    case Opcode::kSwitch: {
      const SwitchOp& swtch = terminator.Cast<SwitchOp>();
      if (successor == swtch.default_case) {
        return swtch.default_hint == BranchHint::kFalse;
      }
      auto it = std::find_if(swtch.cases.begin(), swtch.cases.end(),
                             [successor](const SwitchOp::Case& c) {
                               return c.destination == successor;
                             });
      DCHECK_NE(it, swtch.cases.end());
      return it->hint == BranchHint::kFalse;
    }
    case Opcode::kDeoptimize:
    case Opcode::kTailCall:
    case Opcode::kUnreachable:
    case Opcode::kReturn:
      UNREACHABLE();
#define NON_TERMINATOR_CASE(op) case Opcode::k##op:
      TURBOSHAFT_OPERATION_LIST_NOT_BLOCK_TERMINATOR(NON_TERMINATOR_CASE)
      UNREACHABLE();
#undef NON_TERMINATOR_CASE
  }
}
References v8::internal::compiler::turboshaft::SwitchOp::cases, v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::compiler::turboshaft::CheckExceptionOp::catch_block, v8::base::contains(), v8::internal::DCHECK(), DCHECK_NE, v8::internal::compiler::turboshaft::SwitchOp::default_case, v8::internal::compiler::turboshaft::SwitchOp::default_hint, graph(), v8::internal::compiler::turboshaft::BranchOp::hint, v8::internal::compiler::turboshaft::BranchOp::if_false, v8::internal::compiler::turboshaft::BranchOp::if_true, kBranch, v8::internal::kFalse, v8::internal::wasm::kSwitch, v8::internal::wasm::kTailCall, v8::internal::kTrue, v8::internal::wasm::kUnreachable, v8::internal::compiler::turboshaft::Block::LastOperation(), NON_TERMINATOR_CASE, v8::internal::compiler::turboshaft::Operation::opcode, v8::internal::compiler::turboshaft::Block::Predecessors(), TURBOSHAFT_OPERATION_LIST_NOT_BLOCK_TERMINATOR, and v8::internal::UNREACHABLE().
Referenced by PropagateDeferred().
IsValidTypeFor()
template<typename T >
constexpr bool v8::internal::compiler::turboshaft::IsValidTypeFor (RegisterRepresentation repr) [constexpr]
Definition at line 581 of file index.h.
                                                           {
  if (std::is_same_v<T, Any>) return true;
  switch (repr.value()) {
    case RegisterRepresentation::Enum::kWord32:
      return std::is_same_v<T, Word> || std::is_same_v<T, Word32> ||
             std::is_same_v<T, Untagged>;
    case RegisterRepresentation::Enum::kWord64:
      return std::is_same_v<T, Word> || std::is_same_v<T, Word64> ||
             std::is_same_v<T, Untagged>;
    case RegisterRepresentation::Enum::kFloat32:
      return std::is_same_v<T, Float> || std::is_same_v<T, Float32> ||
             std::is_same_v<T, Untagged>;
    case RegisterRepresentation::Enum::kFloat64:
      return std::is_same_v<T, Float> || std::is_same_v<T, Float64> ||
             std::is_same_v<T, Untagged>;
    case RegisterRepresentation::Enum::kTagged:
      return is_subtype_v<T, Object>;
    case RegisterRepresentation::Enum::kCompressed:
      return is_subtype_v<T, Object>;
    case RegisterRepresentation::Enum::kSimd128:
      return std::is_same_v<T, Simd128>;
    case RegisterRepresentation::Enum::kSimd256:
      return std::is_same_v<T, Simd256>;
  }
}
References v8::internal::compiler::turboshaft::RegisterRepresentation::kCompressed, v8::internal::compiler::turboshaft::RegisterRepresentation::kFloat32, v8::internal::compiler::turboshaft::RegisterRepresentation::kFloat64, v8::internal::compiler::turboshaft::RegisterRepresentation::kSimd128, v8::internal::compiler::turboshaft::RegisterRepresentation::kSimd256, v8::internal::compiler::turboshaft::RegisterRepresentation::kTagged, v8::internal::compiler::turboshaft::RegisterRepresentation::kWord32, v8::internal::compiler::turboshaft::RegisterRepresentation::kWord64, and v8::internal::compiler::turboshaft::RegisterRepresentation::value().
IsWord()
template<typename T >
constexpr bool v8::internal::compiler::turboshaft::IsWord () [constexpr]
Definition at line 575 of file index.h.
                        {
  return std::is_same_v<T, Word32> || std::is_same_v<T, Word64> ||
         std::is_same_v<T, Word>;
}
LeastUpperBoundFromRanges()
template<size_t Bits, typename word_t = typename WordType<Bits>::word_t>
WordType<Bits> v8::internal::compiler::turboshaft::LeastUpperBoundFromRanges (word_t l_from, word_t l_to, word_t r_from, word_t r_to, Zone * zone)
Definition at line 234 of file types.cc.
                                                     {
  const bool lhs_wrapping = l_to < l_from;
  const bool rhs_wrapping = r_to < r_from;
  // Case 1: Both ranges non-wrapping
  // lhs ---|XXX|-- --|XXX|--- -|XXXXXX|- ---|XX|--- -|XX|------
  // rhs -|XXX|---- ----|XXX|- ---|XX|--- -|XXXXXX|- ------|XX|-
  // ==> -|XXXXX|-- --|XXXXX|- -|XXXXXX|- -|XXXXXX|- -|XXXXXXX|-
  if (!lhs_wrapping && !rhs_wrapping) {
    return WordType<Bits>::Range(std::min(l_from, r_from), std::max(l_to, r_to),
                                 zone);
  }
  // Case 2: Both ranges wrapping
  // lhs XXX|----|XXX X|---|XXXXXX XXXXXX|---|X XX|--|XXXXXX
  // rhs X|---|XXXXXX XXX|----|XXX XX|--|XXXXXX XXXXXX|--|XX
  // ==> XXX|-|XXXXXX XXX|-|XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX
  if (lhs_wrapping && rhs_wrapping) {
    const auto from = std::min(l_from, r_from);
    const auto to = std::max(l_to, r_to);
    if (to >= from) return WordType<Bits>::Any();
    auto result = WordType<Bits>::Range(from, to, zone);
    DCHECK(result.is_wrapping());
    return result;
  }
  if (rhs_wrapping)
    return LeastUpperBoundFromRanges<Bits>(r_from, r_to, l_from, l_to, zone);
  DCHECK(lhs_wrapping);
  DCHECK(!rhs_wrapping);
  // Case 3 & 4: lhs is wrapping, rhs is not
  // lhs XXX|----|XXX XXX|----|XXX XXXXX|--|XXX X|-------|XX
  // rhs -------|XX|- -|XX|------- ----|XXXXX|- ---|XX|-----
  // ==> XXX|---|XXXX XXXX|---|XXX XXXXXXXXXXXX XXXXXX|--|XX
  if (r_from <= l_to) {
    if (r_to <= l_to)
      return WordType<Bits>::Range(l_from, l_to, zone); // y covered by x
    if (r_to >= l_from) return WordType<Bits>::Any(); // ex3
    auto result = WordType<Bits>::Range(l_from, r_to, zone); // ex 1
    DCHECK(result.is_wrapping());
    return result;
  } else if (r_to >= l_from) {
    if (r_from >= l_from)
      return WordType<Bits>::Range(l_from, l_to, zone); // y covered by x
    DCHECK_GT(r_from, l_to); // handled above
    auto result = WordType<Bits>::Range(r_from, l_to, zone); // ex 2
    DCHECK(result.is_wrapping());
    return result;
  } else {
    const auto df = r_from - l_to;
    const auto dt = l_from - r_to;
    WordType<Bits> result =
        df > dt ? WordType<Bits>::Range(r_from, l_to, zone) // ex 4
                : WordType<Bits>::Range(l_from, r_to, zone);
    DCHECK(result.is_wrapping());
    return result;
  }
}
References v8::internal::compiler::turboshaft::WordType< Bits >::Any(), v8::internal::DCHECK(), DCHECK_GT, v8::internal::compiler::turboshaft::WordType< Bits >::Range(), and v8::base::internal::result.
LoadRootHelper()
template<typename AssemblerT >
OpIndex v8::internal::compiler::turboshaft::LoadRootHelper (AssemblerT && assembler, RootIndex index)
Definition at line 24 of file wasm-assembler-helpers.h.
                                                                {
  if (RootsTable::IsImmortalImmovable(index)) {
    // Note that we skip the bit cast here as the value does not need to be
    // tagged as the object will never be collected / moved.
    return assembler.Load(
        assembler.LoadRootRegister(), LoadOp::Kind::RawAligned().Immutable(),
        MemoryRepresentation::UintPtr(), IsolateData::root_slot_offset(index));
  } else {
    return assembler.BitcastWordPtrToTagged(assembler.Load(
        assembler.LoadRootRegister(), LoadOp::Kind::RawAligned(),
        MemoryRepresentation::UintPtr(), IsolateData::root_slot_offset(index)));
  }
}
References v8::internal::compiler::turboshaft::LoadOp::Kind::Immutable(), v8::internal::index, v8::internal::RootsTable::IsImmortalImmovable(), v8::internal::compiler::turboshaft::LoadOp::Kind::RawAligned(), v8::internal::IsolateData::root_slot_offset(), and v8::internal::compiler::turboshaft::MemoryRepresentation::UintPtr().
LoadStrideEqualTo()
template<class Op , class Info >
bool v8::internal::compiler::turboshaft::LoadStrideEqualTo (const Graph & graph, const NodeGroup & node_group, int stride)
Definition at line 205 of file wasm-revec-reducer.cc.
                                   {
  base::SmallVector<Info, 2> load_infos;
  for (OpIndex op_idx : node_group) {
    const Operation& op = graph.Get(op_idx);
    const Op& load_op = op.Cast<Op>();
    Info info(&graph, &load_op);
    if (!info.IsValid()) {
      return false;
    }
    load_infos.push_back(info);
  }
  return load_infos[1] - load_infos[0] == stride;
}
References v8::internal::compiler::turboshaft::Operation::Cast(), graph(), v8::base::SmallVector< T, kSize, Allocator >::push_back(), and v8::internal::anonymous_namespace{json-stringifier.cc}::stride.
MaybeRepVector()
template<MaybeRegisterRepresentation::Enum... reps>
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::MaybeRepVector ()
Definition at line 1372 of file operations.h.
                                                               {
  static constexpr std::array<MaybeRegisterRepresentation, sizeof...(reps)>
      rep_array{MaybeRegisterRepresentation{reps}...};
  return base::VectorOf(rep_array);
}
References v8::base::VectorOf().
Referenced by v8::internal::compiler::turboshaft::Word32PairBinopOp::inputs_rep(), v8::internal::compiler::turboshaft::GenericBinopOp::inputs_rep(), v8::internal::compiler::turboshaft::BitcastWord32PairToFloat64Op::inputs_rep(), v8::internal::compiler::turboshaft::LoadOp::inputs_rep(), v8::internal::compiler::turboshaft::ConvertJSPrimitiveToObjectOp::inputs_rep(), v8::internal::compiler::turboshaft::NewConsStringOp::inputs_rep(), v8::internal::compiler::turboshaft::LoadFieldByIndexOp::inputs_rep(), v8::internal::compiler::turboshaft::BigIntBinopOp::inputs_rep(), v8::internal::compiler::turboshaft::BigIntComparisonOp::inputs_rep(), v8::internal::compiler::turboshaft::StringAtOp::inputs_rep(), v8::internal::compiler::turboshaft::StringIndexOfOp::inputs_rep(), v8::internal::compiler::turboshaft::StringFromCodePointAtOp::inputs_rep(), v8::internal::compiler::turboshaft::StringSubstringOp::inputs_rep(), v8::internal::compiler::turboshaft::StringConcatOp::inputs_rep(), v8::internal::compiler::turboshaft::StringComparisonOp::inputs_rep(), v8::internal::compiler::turboshaft::StringOrOddballStrictEqualOp::inputs_rep(), v8::internal::compiler::turboshaft::LoadTypedElementOp::inputs_rep(), v8::internal::compiler::turboshaft::LoadDataViewElementOp::inputs_rep(), v8::internal::compiler::turboshaft::LoadStackArgumentOp::inputs_rep(), v8::internal::compiler::turboshaft::CheckEqualsInternalizedStringOp::inputs_rep(), v8::internal::compiler::turboshaft::StoreMessageOp::inputs_rep(), v8::internal::compiler::turboshaft::SameValueOp::inputs_rep(), v8::internal::compiler::turboshaft::Float64SameValueOp::inputs_rep(), v8::internal::compiler::turboshaft::EnsureWritableFastElementsOp::inputs_rep(), v8::internal::compiler::turboshaft::MaybeGrowFastElementsOp::inputs_rep(), and v8::internal::compiler::turboshaft::FindOrderedHashEntryOp::inputs_rep().
MayThrow()
constexpr bool v8::internal::compiler::turboshaft::MayThrow (Opcode opcode) [inline], [constexpr]
Definition at line 434 of file operations.h.
                                              {
#define CASE(Name) case Opcode::k##Name:
  switch (opcode) {
    TURBOSHAFT_THROWING_OPERATIONS_LIST(CASE)
    return true;
    default:
      return false;
  }
#undef CASE
}
References CASE, and TURBOSHAFT_THROWING_OPERATIONS_LIST.
Referenced by v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::CanBeGVNed(), v8::internal::compiler::turboshaft::EmitProjectionReducer< Next >::ReduceOperation(), and v8::internal::compiler::turboshaft::DidntThrowOp::Validate().
multi()
template<typename... Ts>
constexpr uint64_t v8::internal::compiler::turboshaft::multi (const Ts &... values) [inline], [constexpr]
Definition at line 177 of file utils.h.
                                                     {
  return detail::multi_encode(values...);
}
References v8::internal::compiler::turboshaft::detail::multi_encode().
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Change(), and v8::internal::compiler::InstructionSelector::VisitNode().
OpcodeIndex()
constexpr std::underlying_type_t<Opcode> v8::internal::compiler::turboshaft::OpcodeIndex (Opcode x) [constexpr]
Definition at line 375 of file operations.h.
                                                             {
  return static_cast<std::underlying_type_t<Opcode>>(x);
}
Referenced by v8::internal::compiler::turboshaft::Graph::Get(), IsBlockTerminator(), and OpcodeName().
OpcodeName()
const char * v8::internal::compiler::turboshaft::OpcodeName (Opcode opcode)
Definition at line 139 of file operations.cc.
                                      {
#define OPCODE_NAME(Name) #Name,
  const char* table[kNumberOfOpcodes] = {
      TURBOSHAFT_OPERATION_LIST(OPCODE_NAME)};
#undef OPCODE_NAME
  return table[OpcodeIndex(opcode)];
}
References kNumberOfOpcodes, OPCODE_NAME, OpcodeIndex(), and TURBOSHAFT_OPERATION_LIST.
Referenced by v8::internal::compiler::turboshaft::WasmRevecAnalyzer::DecideVectorize(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeAtomicOpcode(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeGCOpcode(), GetSimdOpcodeName(), v8::internal::compiler::anonymous_namespace{pipeline.cc}::HashGraphForPGO(), operator<<(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::ParseBrOnCast(), v8::internal::compiler::turboshaft::JSONTurboshaftGraphWriter::PrintNodes(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessBranchOnTarget(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessPhi(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::RefineTypeKnowledge(), and v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::RefineTypeKnowledgeNotNull().
operator!=() [1/7]
bool v8::internal::compiler::turboshaft::operator!= (const ControlState & lhs, const ControlState & rhs) [inline]
Definition at line 144 of file dead-code-elimination-reducer.h.
                                                                         {
  return !(lhs == rhs);
}
operator!=() [2/7]
bool v8::internal::compiler::turboshaft::operator!= (const Type & lhs, const Type & rhs) [inline]
Definition at line 915 of file types.h.
                                                         {
  return !lhs.Equals(rhs);
}
References v8::internal::compiler::turboshaft::Type::Equals().
operator!=() [3/7]
constexpr bool v8::internal::compiler::turboshaft::operator!= (MaybeRegisterRepresentation a, MaybeRegisterRepresentation b) [inline], [constexpr]
Definition at line 353 of file representations.h.
                                                                   {
  return a.value() != b.value();
}
References v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::value().
operator!=() [4/7]
constexpr bool v8::internal::compiler::turboshaft::operator!= (MemoryRepresentation a, MemoryRepresentation b) [inline], [constexpr]
Definition at line 942 of file representations.h.
                                                            {
  return a.value() != b.value();
}
References v8::internal::compiler::turboshaft::MemoryRepresentation::value().
operator!=() [5/7]
constexpr bool v8::internal::compiler::turboshaft::operator!= (nullrep_t , nullrep_t) [inline], [constexpr]
Definition at line 211 of file index.h.
{ return false; }
operator!=() [6/7]
constexpr bool v8::internal::compiler::turboshaft::operator!= (nullrep_t , RegisterRepresentation) [inline], [constexpr]
Definition at line 212 of file index.h.
                                                                    {
  return true;
}
operator!=() [7/7]
constexpr bool v8::internal::compiler::turboshaft::operator!= (RegisterRepresentation , nullrep_t) [inline], [constexpr]
Definition at line 215 of file index.h.
                                                                    {
  return true;
}
operator<<() [1/70]
template<class... Ts>
std::ostream& v8::internal::compiler::turboshaft::operator<< (std::ostream & os, all_of< Ts... > all)
Definition at line 77 of file utils.h.
                                                          {
  return all.PrintTo(os, std::index_sequence_for<Ts...>{});
}
References all.
operator<<() [2/70]
template<class... Ts>
std::ostream& v8::internal::compiler::turboshaft::operator<< (std::ostream & os, any_of< Ts... > any)
Definition at line 45 of file utils.h.
                                                          {
  return any.PrintTo(os, std::index_sequence_for<Ts...>{});
}
References v8::internal::compiler::turboshaft::any_of< Ts >::PrintTo().
operator<<() [3/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, ArgumentsLengthOp::Kind kind)
Definition at line 1529 of file operations.cc.
                                                                   {
  switch (kind) {
    case ArgumentsLengthOp::Kind::kArguments:
      return os << "Arguments";
    case ArgumentsLengthOp::Kind::kRest:
      return os << "Rest";
  }
}
References v8::internal::compiler::turboshaft::ArgumentsLengthOp::kArguments, and v8::internal::compiler::turboshaft::ArgumentsLengthOp::kRest.
operator<<() [4/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, AtomicRMWOp::BinOp bin_op)
Definition at line 456 of file operations.cc.
                                                                {
  switch (bin_op) {
    case AtomicRMWOp::BinOp::kAdd:
      return os << "add";
    case AtomicRMWOp::BinOp::kSub:
      return os << "sub";
    case AtomicRMWOp::BinOp::kAnd:
      return os << "and";
    case AtomicRMWOp::BinOp::kOr:
      return os << "or";
    case AtomicRMWOp::BinOp::kXor:
      return os << "xor";
    case AtomicRMWOp::BinOp::kExchange:
      return os << "exchange";
    case AtomicRMWOp::BinOp::kCompareExchange:
      return os << "compare-exchange";
  }
}
References v8::internal::compiler::turboshaft::AtomicRMWOp::kAdd, v8::internal::compiler::turboshaft::AtomicRMWOp::kAnd, v8::internal::compiler::turboshaft::AtomicRMWOp::kCompareExchange, v8::internal::compiler::turboshaft::AtomicRMWOp::kExchange, v8::internal::compiler::turboshaft::AtomicRMWOp::kOr, v8::internal::compiler::turboshaft::AtomicRMWOp::kSub, and v8::internal::compiler::turboshaft::AtomicRMWOp::kXor.
operator<<() [5/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, AtomicWord32PairOp::Kind bin_op)
Definition at line 475 of file operations.cc.
                                                                      {
  switch (bin_op) {
    case AtomicWord32PairOp::Kind::kAdd:
      return os << "add";
    case AtomicWord32PairOp::Kind::kSub:
      return os << "sub";
    case AtomicWord32PairOp::Kind::kAnd:
      return os << "and";
    case AtomicWord32PairOp::Kind::kOr:
      return os << "or";
    case AtomicWord32PairOp::Kind::kXor:
      return os << "xor";
    case AtomicWord32PairOp::Kind::kExchange:
      return os << "exchange";
    case AtomicWord32PairOp::Kind::kCompareExchange:
      return os << "compare-exchange";
    case AtomicWord32PairOp::Kind::kLoad:
      return os << "load";
    case AtomicWord32PairOp::Kind::kStore:
      return os << "store";
  }
}
References v8::internal::compiler::turboshaft::AtomicWord32PairOp::kAdd, v8::internal::compiler::turboshaft::AtomicWord32PairOp::kAnd, v8::internal::compiler::turboshaft::AtomicWord32PairOp::kCompareExchange, v8::internal::compiler::turboshaft::AtomicWord32PairOp::kExchange, v8::internal::compiler::turboshaft::AtomicWord32PairOp::kLoad, v8::internal::compiler::turboshaft::AtomicWord32PairOp::kOr, v8::internal::compiler::turboshaft::AtomicWord32PairOp::kStore, v8::internal::compiler::turboshaft::AtomicWord32PairOp::kSub, and v8::internal::compiler::turboshaft::AtomicWord32PairOp::kXor.
operator<<() [6/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, BigIntBinopOp::Kind kind)
Definition at line 1455 of file operations.cc.
                                                               {
  switch (kind) {
    case BigIntBinopOp::Kind::kAdd:
      return os << "Add";
    case BigIntBinopOp::Kind::kSub:
      return os << "Sub";
    case BigIntBinopOp::Kind::kMul:
      return os << "Mul";
    case BigIntBinopOp::Kind::kDiv:
      return os << "Div";
    case BigIntBinopOp::Kind::kMod:
      return os << "Mod";
    case BigIntBinopOp::Kind::kBitwiseAnd:
      return os << "BitwiseAnd";
    case BigIntBinopOp::Kind::kBitwiseOr:
      return os << "BitwiseOr";
    case BigIntBinopOp::Kind::kBitwiseXor:
      return os << "BitwiseXor";
    case BigIntBinopOp::Kind::kShiftLeft:
      return os << "ShiftLeft";
    case BigIntBinopOp::Kind::kShiftRightArithmetic:
      return os << "ShiftRightArithmetic";
  }
}
References v8::internal::compiler::turboshaft::BigIntBinopOp::kAdd, v8::internal::compiler::turboshaft::BigIntBinopOp::kBitwiseAnd, v8::internal::compiler::turboshaft::BigIntBinopOp::kBitwiseOr, v8::internal::compiler::turboshaft::BigIntBinopOp::kBitwiseXor, v8::internal::compiler::turboshaft::BigIntBinopOp::kDiv, v8::internal::compiler::turboshaft::BigIntBinopOp::kMod, v8::internal::compiler::turboshaft::BigIntBinopOp::kMul, v8::internal::compiler::turboshaft::BigIntBinopOp::kShiftLeft, v8::internal::compiler::turboshaft::BigIntBinopOp::kShiftRightArithmetic, and v8::internal::compiler::turboshaft::BigIntBinopOp::kSub.
operator<<() [7/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, BigIntComparisonOp::Kind kind)
Definition at line 1480 of file operations.cc.
                                                                    {
  switch (kind) {
    case BigIntComparisonOp::Kind::kEqual:
      return os << "Equal";
    case BigIntComparisonOp::Kind::kLessThan:
      return os << "LessThan";
    case BigIntComparisonOp::Kind::kLessThanOrEqual:
      return os << "LessThanOrEqual";
  }
}
References v8::internal::compiler::turboshaft::BigIntComparisonOp::kEqual, v8::internal::compiler::turboshaft::BigIntComparisonOp::kLessThan, and v8::internal::compiler::turboshaft::BigIntComparisonOp::kLessThanOrEqual.
operator<<() [8/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, BigIntUnaryOp::Kind kind)
Definition at line 1491 of file operations.cc.
                                                               {
  switch (kind) {
    case BigIntUnaryOp::Kind::kNegate:
      return os << "Negate";
  }
}
References v8::internal::compiler::turboshaft::BigIntUnaryOp::kNegate.
operator<<() [9/70]
std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, BlockIndex b)
Definition at line 1090 of file operations.cc.
                                                     {
  if (!b.valid()) {
    return os << "<invalid block>";
  }
  return os << 'B' << b.id();
}
References v8::internal::compiler::turboshaft::BlockIndex::id(), and v8::internal::compiler::turboshaft::BlockIndex::valid().
operator<<() [10/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, ChangeOp::Assumption assumption)
Definition at line 436 of file operations.cc.
                                                                      {
  switch (assumption) {
    case ChangeOp::Assumption::kNoAssumption:
      return os << "NoAssumption";
    case ChangeOp::Assumption::kNoOverflow:
      return os << "NoOverflow";
    case ChangeOp::Assumption::kReversible:
      return os << "Reversible";
  }
}
References v8::internal::compiler::turboshaft::ChangeOp::kNoAssumption, v8::internal::compiler::turboshaft::ChangeOp::kNoOverflow, and v8::internal::compiler::turboshaft::ChangeOp::kReversible.
operator<<() [11/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, ChangeOp::Kind kind)
Definition at line 356 of file operations.cc.
                                                          {
  switch (kind) {
    case ChangeOp::Kind::kFloatConversion:
      return os << "FloatConversion";
    case ChangeOp::Kind::kJSFloatTruncate:
      return os << "JSFloatTruncate";
    case ChangeOp::Kind::kJSFloat16ChangeWithBitcast:
      return os << "JSFloat16ChangeWithBitcast";
    case ChangeOp::Kind::kJSFloat16TruncateWithBitcast:
      return os << "JSFloat16TruncateWithBitcast";
    case ChangeOp::Kind::kSignedFloatTruncateOverflowToMin:
      return os << "SignedFloatTruncateOverflowToMin";
    case ChangeOp::Kind::kUnsignedFloatTruncateOverflowToMin:
      return os << "UnsignedFloatTruncateOverflowToMin";
    case ChangeOp::Kind::kSignedToFloat:
      return os << "SignedToFloat";
    case ChangeOp::Kind::kUnsignedToFloat:
      return os << "UnsignedToFloat";
    case ChangeOp::Kind::kExtractHighHalf:
      return os << "ExtractHighHalf";
    case ChangeOp::Kind::kExtractLowHalf:
      return os << "ExtractLowHalf";
    case ChangeOp::Kind::kZeroExtend:
      return os << "ZeroExtend";
    case ChangeOp::Kind::kSignExtend:
      return os << "SignExtend";
    case ChangeOp::Kind::kTruncate:
      return os << "Truncate";
    case ChangeOp::Kind::kBitcast:
      return os << "Bitcast";
  }
}
References v8::internal::compiler::turboshaft::ChangeOp::kBitcast, v8::internal::compiler::turboshaft::ChangeOp::kExtractHighHalf, v8::internal::compiler::turboshaft::ChangeOp::kExtractLowHalf, v8::internal::compiler::turboshaft::ChangeOp::kFloatConversion, v8::internal::compiler::turboshaft::ChangeOp::kJSFloat16ChangeWithBitcast, v8::internal::compiler::turboshaft::ChangeOp::kJSFloat16TruncateWithBitcast, v8::internal::compiler::turboshaft::ChangeOp::kJSFloatTruncate, v8::internal::compiler::turboshaft::ChangeOp::kSignedFloatTruncateOverflowToMin, v8::internal::compiler::turboshaft::ChangeOp::kSignedToFloat, v8::internal::compiler::turboshaft::ChangeOp::kSignExtend, v8::internal::compiler::turboshaft::ChangeOp::kTruncate, v8::internal::compiler::turboshaft::ChangeOp::kUnsignedFloatTruncateOverflowToMin, v8::internal::compiler::turboshaft::ChangeOp::kUnsignedToFloat, and v8::internal::compiler::turboshaft::ChangeOp::kZeroExtend.
operator<<() [12/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, ChangeOrDeoptOp::Kind kind)
Definition at line 389 of file operations.cc.
                                                                 {
  switch (kind) {
    case ChangeOrDeoptOp::Kind::kUint32ToInt32:
      return os << "Uint32ToInt32";
    case ChangeOrDeoptOp::Kind::kInt64ToInt32:
      return os << "Int64ToInt32";
    case ChangeOrDeoptOp::Kind::kInt64ToAdditiveSafeInteger:
      return os << "Int64ToAdditiveSafeInteger";
    case ChangeOrDeoptOp::Kind::kUint64ToInt32:
      return os << "Uint64ToInt32";
    case ChangeOrDeoptOp::Kind::kUint64ToInt64:
      return os << "Uint64ToInt64";
    case ChangeOrDeoptOp::Kind::kFloat64ToInt32:
      return os << "Float64ToInt32";
    case ChangeOrDeoptOp::Kind::kFloat64ToUint32:
      return os << "Float64ToUint32";
    case ChangeOrDeoptOp::Kind::kFloat64ToAdditiveSafeInteger:
      return os << "Float64ToAdditiveSafeInteger";
    case ChangeOrDeoptOp::Kind::kFloat64ToInt64:
      return os << "Float64ToInt64";
    case ChangeOrDeoptOp::Kind::kFloat64NotHole:
      return os << "Float64NotHole";
  }
}
References v8::internal::compiler::turboshaft::ChangeOrDeoptOp::kFloat64NotHole, v8::internal::compiler::turboshaft::ChangeOrDeoptOp::kFloat64ToAdditiveSafeInteger, v8::internal::compiler::turboshaft::ChangeOrDeoptOp::kFloat64ToInt32, v8::internal::compiler::turboshaft::ChangeOrDeoptOp::kFloat64ToInt64, v8::internal::compiler::turboshaft::ChangeOrDeoptOp::kFloat64ToUint32, v8::internal::compiler::turboshaft::ChangeOrDeoptOp::kInt64ToAdditiveSafeInteger, v8::internal::compiler::turboshaft::ChangeOrDeoptOp::kInt64ToInt32, v8::internal::compiler::turboshaft::ChangeOrDeoptOp::kUint32ToInt32, v8::internal::compiler::turboshaft::ChangeOrDeoptOp::kUint64ToInt32, and v8::internal::compiler::turboshaft::ChangeOrDeoptOp::kUint64ToInt64.
operator<<() [13/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, ComparisonOp::Kind kind)
Definition at line 341 of file operations.cc.
                                                              {
  switch (kind) {
    case ComparisonOp::Kind::kEqual:
      return os << "Equal";
    case ComparisonOp::Kind::kSignedLessThan:
      return os << "SignedLessThan";
    case ComparisonOp::Kind::kSignedLessThanOrEqual:
      return os << "SignedLessThanOrEqual";
    case ComparisonOp::Kind::kUnsignedLessThan:
      return os << "UnsignedLessThan";
    case ComparisonOp::Kind::kUnsignedLessThanOrEqual:
      return os << "UnsignedLessThanOrEqual";
  }
}
References v8::internal::compiler::turboshaft::ComparisonOp::kEqual, v8::internal::compiler::turboshaft::ComparisonOp::kSignedLessThan, v8::internal::compiler::turboshaft::ComparisonOp::kSignedLessThanOrEqual, v8::internal::compiler::turboshaft::ComparisonOp::kUnsignedLessThan, and v8::internal::compiler::turboshaft::ComparisonOp::kUnsignedLessThanOrEqual.
operator<<() [14/70]
std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, const BinOp & binop)
Definition at line 280 of file loop-unrolling-reducer.cc.
                                                           {
  switch (binop) {
    case BinOp::kAdd:
      return os << "+";
    case BinOp::kMul:
      return os << "*";
    case BinOp::kSub:
      return os << "-";
    case BinOp::kBitwiseAnd:
      return os << "&";
    case BinOp::kBitwiseOr:
      return os << "|";
    case BinOp::kBitwiseXor:
      return os << "^";
    case BinOp::kOverflowCheckedAdd:
      return os << "+";
    case BinOp::kOverflowCheckedMul:
      return os << "*";
    case BinOp::kOverflowCheckedSub:
      return os << "-";
  }
}
References v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::kAdd, v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::kBitwiseAnd, v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::kBitwiseOr, v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::kBitwiseXor, v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::kMul, v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::kOverflowCheckedAdd, v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::kOverflowCheckedMul, v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::kOverflowCheckedSub, and v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::kSub.
operator<<() [15/70]
std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, const Block * b)
Definition at line 1097 of file operations.cc.
                                                       {
  return os << b->index();
}
References v8::internal::compiler::turboshaft::Block::index().
operator<<() [16/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, const Block::Kind & kind)
Definition at line 89 of file graph.cc.
                                                              {
  switch (kind) {
    case Block::Kind::kLoopHeader:
      return os << "LOOP";
    case Block::Kind::kMerge:
      return os << "MERGE";
    case Block::Kind::kBranchTarget:
      return os << "BLOCK";
  }
}
References v8::internal::compiler::turboshaft::Block::kBranchTarget, v8::internal::compiler::turboshaft::Block::kLoopHeader, and v8::internal::compiler::turboshaft::Block::kMerge.
operator<<() [17/70]
std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, const CmpOp & cmp)
Definition at line 257 of file loop-unrolling-reducer.cc.
                                                         {
  switch (cmp) {
    case CmpOp::kEqual:
      return os << "==";
    case CmpOp::kSignedLessThan:
      return os << "<";
    case CmpOp::kSignedLessThanOrEqual:
      return os << "<=";
    case CmpOp::kUnsignedLessThan:
      return os << "<";
    case CmpOp::kUnsignedLessThanOrEqual:
      return os << "<=";
    case CmpOp::kSignedGreaterThan:
      return os << ">";
    case CmpOp::kSignedGreaterThanOrEqual:
      return os << ">=";
    case CmpOp::kUnsignedGreaterThan:
      return os << ">";
    case CmpOp::kUnsignedGreaterThanOrEqual:
      return os << ">=";
  }
}
References v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::kEqual, v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::kSignedGreaterThan, v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::kSignedGreaterThanOrEqual, v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::kSignedLessThan, v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::kSignedLessThanOrEqual, v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::kUnsignedGreaterThan, v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::kUnsignedGreaterThanOrEqual, v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::kUnsignedLessThan, and v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::kUnsignedLessThanOrEqual.
operator<<() [18/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, const Graph & graph)
Definition at line 79 of file graph.cc.
                                                           {
  for (const Block& block : graph.blocks()) {
    os << "\n" << PrintAsBlockHeader{block} << "\n";
    for (const Operation& op : graph.operations(block)) {
      os << std::setw(5) << graph.Index(op).id() << ": " << op << "\n";
    }
  }
  return os;
}
References graph().
operator<<() [19/70]
std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, const IterationCount & count)
Definition at line 246 of file loop-unrolling-reducer.cc.
                                                                    {
  if (count.IsExact()) {
    return os << "Exact[" << count.exact_count() << "]";
  } else if (count.IsApprox()) {
    return os << "Approx[" << count.approx_count() << "]";
  } else {
    DCHECK(count.IsUnknown());
    return os << "Unknown";
  }
}
References v8::internal::DCHECK().
operator<<() [20/70]
std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, const MemoryAddress & mem)
Definition at line 28 of file late-load-elimination-reducer.cc.
                                                                 {
  return os << "MemoryAddress{base=" << mem.base << ", index=" << mem.index
            << ", offset=" << mem.offset << ", elem_size_log2="
            << static_cast<uint32_t>(mem.element_size_log2)
            << ", size=" << static_cast<uint32_t>(mem.size) << "}";
}
References v8::internal::compiler::turboshaft::MemoryAddress::base, v8::internal::compiler::turboshaft::MemoryAddress::element_size_log2, v8::internal::compiler::turboshaft::MemoryAddress::index, v8::internal::compiler::turboshaft::MemoryAddress::offset, and v8::internal::compiler::turboshaft::MemoryAddress::size.
operator<<() [21/70]
std::ostream& v8::internal::compiler::turboshaft::operator<< (std::ostream & os, const Operation & op) [inline]
Definition at line 1047 of file operations.h.
                                                                   {
  return os << OperationPrintStyle{op};
}
operator<<() [22/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, const TurboshaftGraphAsJSON & ad)
Definition at line 100 of file graph-visualizer.cc.
                                                                        {
  JSONTurboshaftGraphWriter writer(os, ad.turboshaft_graph, ad.origins,
                                   ad.temp_zone);
  writer.Print();
  return os;
}
References v8::internal::compiler::turboshaft::TurboshaftGraphAsJSON::origins, v8::internal::compiler::turboshaft::JSONTurboshaftGraphWriter::Print(), v8::internal::compiler::turboshaft::TurboshaftGraphAsJSON::temp_zone, and v8::internal::compiler::turboshaft::TurboshaftGraphAsJSON::turboshaft_graph.
operator<<() [23/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, ConvertJSPrimitiveToUntaggedOp::InputAssumptions input_assumptions)
Definition at line 1341 of file operations.cc.
                                                                      {
  switch (input_assumptions) {
    case ConvertJSPrimitiveToUntaggedOp::InputAssumptions::kBoolean:
      return os << "Boolean";
    case ConvertJSPrimitiveToUntaggedOp::InputAssumptions::kSmi:
      return os << "Smi";
    case ConvertJSPrimitiveToUntaggedOp::InputAssumptions::kNumberOrOddball:
      return os << "NumberOrOddball";
    case ConvertJSPrimitiveToUntaggedOp::InputAssumptions::kPlainPrimitive:
      return os << "PlainPrimitive";
  }
}
References v8::internal::compiler::turboshaft::ConvertJSPrimitiveToUntaggedOp::kBoolean, v8::internal::compiler::turboshaft::ConvertJSPrimitiveToUntaggedOp::kNumberOrOddball, v8::internal::compiler::turboshaft::ConvertJSPrimitiveToUntaggedOp::kPlainPrimitive, and v8::internal::compiler::turboshaft::ConvertJSPrimitiveToUntaggedOp::kSmi.
operator<<() [24/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, ConvertJSPrimitiveToUntaggedOp::UntaggedKind kind)
Definition at line 1321 of file operations.cc.
                                                                          {
  switch (kind) {
    case ConvertJSPrimitiveToUntaggedOp::UntaggedKind::kInt32:
      return os << "Int32";
    case ConvertJSPrimitiveToUntaggedOp::UntaggedKind::kInt64:
      return os << "Int64";
    case ConvertJSPrimitiveToUntaggedOp::UntaggedKind::kUint32:
      return os << "Uint32";
    case ConvertJSPrimitiveToUntaggedOp::UntaggedKind::kBit:
      return os << "Bit";
    case ConvertJSPrimitiveToUntaggedOp::UntaggedKind::kFloat64:
      return os << "Float64";
#ifdef V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
    case ConvertJSPrimitiveToUntaggedOp::UntaggedKind::kHoleyFloat64:
      return os << "HoleyFloat64";
#endif // V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
  }
}
References v8::internal::compiler::turboshaft::ConvertJSPrimitiveToUntaggedOp::kBit, v8::internal::compiler::turboshaft::ConvertJSPrimitiveToUntaggedOp::kFloat64, v8::internal::compiler::turboshaft::ConvertJSPrimitiveToUntaggedOp::kInt32, v8::internal::compiler::turboshaft::ConvertJSPrimitiveToUntaggedOp::kInt64, and v8::internal::compiler::turboshaft::ConvertJSPrimitiveToUntaggedOp::kUint32.
operator<<() [25/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, ConvertJSPrimitiveToUntaggedOrDeoptOp::JSPrimitiveKind kind)
Definition at line 1378 of file operations.cc.
                                                               {
  switch (kind) {
    case ConvertJSPrimitiveToUntaggedOrDeoptOp::JSPrimitiveKind::
        kAdditiveSafeInteger:
      return os << "AdditiveSafeInteger";
    case ConvertJSPrimitiveToUntaggedOrDeoptOp::JSPrimitiveKind::kNumber:
      return os << "Number";
    case ConvertJSPrimitiveToUntaggedOrDeoptOp::JSPrimitiveKind::
        kNumberOrBoolean:
      return os << "NumberOrBoolean";
    case ConvertJSPrimitiveToUntaggedOrDeoptOp::JSPrimitiveKind::
        kNumberOrOddball:
      return os << "NumberOrOddball";
    case ConvertJSPrimitiveToUntaggedOrDeoptOp::JSPrimitiveKind::
        kNumberOrString:
      return os << "NumberOrString";
    case ConvertJSPrimitiveToUntaggedOrDeoptOp::JSPrimitiveKind::kSmi:
      return os << "Smi";
  }
}
References v8::internal::compiler::turboshaft::ConvertJSPrimitiveToUntaggedOrDeoptOp::kAdditiveSafeInteger, v8::internal::compiler::turboshaft::ConvertJSPrimitiveToUntaggedOrDeoptOp::kNumber, v8::internal::compiler::turboshaft::ConvertJSPrimitiveToUntaggedOrDeoptOp::kNumberOrBoolean, v8::internal::compiler::turboshaft::ConvertJSPrimitiveToUntaggedOrDeoptOp::kNumberOrOddball, v8::internal::compiler::turboshaft::ConvertJSPrimitiveToUntaggedOrDeoptOp::kNumberOrString, and v8::internal::compiler::turboshaft::ConvertJSPrimitiveToUntaggedOrDeoptOp::kSmi.
operator<<() [26/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, ConvertJSPrimitiveToUntaggedOrDeoptOp::UntaggedKind kind)
Definition at line 1356 of file operations.cc.
                                                            {
  switch (kind) {
    case ConvertJSPrimitiveToUntaggedOrDeoptOp::UntaggedKind::kInt32:
      return os << "Int32";
    case ConvertJSPrimitiveToUntaggedOrDeoptOp::UntaggedKind::
        kAdditiveSafeInteger:
      return os << "AdditiveSafeInteger";
    case ConvertJSPrimitiveToUntaggedOrDeoptOp::UntaggedKind::kInt64:
      return os << "Int64";
    case ConvertJSPrimitiveToUntaggedOrDeoptOp::UntaggedKind::kFloat64:
      return os << "Float64";
#ifdef V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
    case ConvertJSPrimitiveToUntaggedOrDeoptOp::UntaggedKind::kHoleyFloat64:
      return os << "HoleyFloat64";
#endif // V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
    case ConvertJSPrimitiveToUntaggedOrDeoptOp::UntaggedKind::kArrayIndex:
      return os << "ArrayIndex";
  }
}
References v8::internal::compiler::turboshaft::ConvertJSPrimitiveToUntaggedOrDeoptOp::kAdditiveSafeInteger, v8::internal::compiler::turboshaft::ConvertJSPrimitiveToUntaggedOrDeoptOp::kArrayIndex, v8::internal::compiler::turboshaft::ConvertJSPrimitiveToUntaggedOrDeoptOp::kFloat64, v8::internal::compiler::turboshaft::ConvertJSPrimitiveToUntaggedOrDeoptOp::kInt32, and v8::internal::compiler::turboshaft::ConvertJSPrimitiveToUntaggedOrDeoptOp::kInt64.
operator<<() [27/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, ConvertOp::Kind kind)
Definition at line 1236 of file operations.cc.
                                                           {
  switch (kind) {
    case ConvertOp::Kind::kObject:
      return os << "Object";
    case ConvertOp::Kind::kBoolean:
      return os << "Boolean";
    case ConvertOp::Kind::kNumber:
      return os << "Number";
    case ConvertOp::Kind::kNumberOrOddball:
      return os << "NumberOrOddball";
    case ConvertOp::Kind::kPlainPrimitive:
      return os << "PlainPrimitive";
    case ConvertOp::Kind::kString:
      return os << "String";
    case ConvertOp::Kind::kSmi:
      return os << "Smi";
  }
}
References v8::internal::compiler::turboshaft::ConvertOp::kBoolean, v8::internal::compiler::turboshaft::ConvertOp::kNumber, v8::internal::compiler::turboshaft::ConvertOp::kNumberOrOddball, v8::internal::compiler::turboshaft::ConvertOp::kObject, v8::internal::compiler::turboshaft::ConvertOp::kPlainPrimitive, v8::internal::compiler::turboshaft::ConvertOp::kSmi, and v8::internal::compiler::turboshaft::ConvertOp::kString.
operator<<() [28/70]
std::ostream& v8::internal::compiler::turboshaft::operator<< (std::ostream & os, ConvertUntaggedToJSPrimitiveOp::InputInterpretation input_interpretation)
Definition at line 1276 of file operations.cc.
                                                                            {
  switch (input_interpretation) {
    case ConvertUntaggedToJSPrimitiveOp::InputInterpretation::kSigned:
      return os << "Signed";
    case ConvertUntaggedToJSPrimitiveOp::InputInterpretation::kUnsigned:
      return os << "Unsigned";
    case ConvertUntaggedToJSPrimitiveOp::InputInterpretation::kDouble:
      return os << "Double";
    case ConvertUntaggedToJSPrimitiveOp::InputInterpretation::kDoubleOrHole:
      return os << "DoubleOrHole";
    case ConvertUntaggedToJSPrimitiveOp::InputInterpretation::
        kDoubleOrUndefined:
      return os << "DoubleOrUndefined";
    case ConvertUntaggedToJSPrimitiveOp::InputInterpretation::
        kDoubleOrUndefinedOrHole:
      return os << "DoubleOrUndefinedOrHole";
    case ConvertUntaggedToJSPrimitiveOp::InputInterpretation::kCharCode:
      return os << "CharCode";
    case ConvertUntaggedToJSPrimitiveOp::InputInterpretation::kCodePoint:
      return os << "CodePoint";
  }
}
References v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOp::kCharCode, v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOp::kCodePoint, v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOp::kDouble, v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOp::kDoubleOrHole, v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOp::kDoubleOrUndefined, v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOp::kDoubleOrUndefinedOrHole, v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOp::kSigned, and v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOp::kUnsigned.
operator<<() [29/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, ConvertUntaggedToJSPrimitiveOp::JSPrimitiveKind kind)
Definition at line 1255 of file operations.cc.
                                                                             {
  switch (kind) {
    case ConvertUntaggedToJSPrimitiveOp::JSPrimitiveKind::kBigInt:
      return os << "BigInt";
    case ConvertUntaggedToJSPrimitiveOp::JSPrimitiveKind::kBoolean:
      return os << "Boolean";
    case ConvertUntaggedToJSPrimitiveOp::JSPrimitiveKind::kHeapNumber:
      return os << "HeapNumber";
    case ConvertUntaggedToJSPrimitiveOp::JSPrimitiveKind::
        kHeapNumberOrUndefined:
      return os << "HeapNumberOrUndefined";
    case ConvertUntaggedToJSPrimitiveOp::JSPrimitiveKind::kNumber:
      return os << "Number";
    case ConvertUntaggedToJSPrimitiveOp::JSPrimitiveKind::kSmi:
      return os << "Smi";
    case ConvertUntaggedToJSPrimitiveOp::JSPrimitiveKind::kString:
      return os << "String";
  }
}
References v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOp::kBigInt, v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOp::kBoolean, v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOp::kHeapNumber, v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOp::kHeapNumberOrUndefined, v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOp::kNumber, v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOp::kSmi, and v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOp::kString.
operator<<() [30/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, ConvertUntaggedToJSPrimitiveOrDeoptOp::InputInterpretation input_interpretation)
Definition at line 1310 of file operations.cc.
                                                {
  switch (input_interpretation) {
    case ConvertUntaggedToJSPrimitiveOrDeoptOp::InputInterpretation::kSigned:
      return os << "Signed";
    case ConvertUntaggedToJSPrimitiveOrDeoptOp::InputInterpretation::kUnsigned:
      return os << "Unsigned";
  }
}
References v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOrDeoptOp::kSigned, and v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOrDeoptOp::kUnsigned.
operator<<() [31/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, ConvertUntaggedToJSPrimitiveOrDeoptOp::JSPrimitiveKind kind)
Definition at line 1301 of file operations.cc.
                                                               {
  switch (kind) {
    case ConvertUntaggedToJSPrimitiveOrDeoptOp::JSPrimitiveKind::kSmi:
      return os << "Smi";
  }
}
References v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOrDeoptOp::kSmi.
operator<<() [32/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, DoubleArrayMinMaxOp::Kind kind)
Definition at line 1446 of file operations.cc.
                                                                     {
  switch (kind) {
    case DoubleArrayMinMaxOp::Kind::kMin:
      return os << "Min";
    case DoubleArrayMinMaxOp::Kind::kMax:
      return os << "Max";
  }
}
References v8::internal::compiler::turboshaft::DoubleArrayMinMaxOp::kMax, and v8::internal::compiler::turboshaft::DoubleArrayMinMaxOp::kMin.
operator<<() [33/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, FindOrderedHashEntryOp::Kind kind)
Definition at line 1590 of file operations.cc.
                                                                        {
  switch (kind) {
    case FindOrderedHashEntryOp::Kind::kFindOrderedHashMapEntry:
      return os << "FindOrderedHashMapEntry";
    case FindOrderedHashEntryOp::Kind::kFindOrderedHashMapEntryForInt32Key:
      return os << "FindOrderedHashMapEntryForInt32Key";
    case FindOrderedHashEntryOp::Kind::kFindOrderedHashSetEntry:
      return os << "FindOrderedHashSetEntry";
  }
}
References v8::internal::compiler::turboshaft::FindOrderedHashEntryOp::kFindOrderedHashMapEntry, v8::internal::compiler::turboshaft::FindOrderedHashEntryOp::kFindOrderedHashMapEntryForInt32Key, and v8::internal::compiler::turboshaft::FindOrderedHashEntryOp::kFindOrderedHashSetEntry.
operator<<() [34/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, FloatUnaryOp::Kind kind)
Definition at line 214 of file operations.cc.
                                                              {
  switch (kind) {
    case FloatUnaryOp::Kind::kAbs:
      return os << "Abs";
    case FloatUnaryOp::Kind::kNegate:
      return os << "Negate";
    case FloatUnaryOp::Kind::kSilenceNaN:
      return os << "SilenceNaN";
    case FloatUnaryOp::Kind::kRoundUp:
      return os << "RoundUp";
    case FloatUnaryOp::Kind::kRoundDown:
      return os << "RoundDown";
    case FloatUnaryOp::Kind::kRoundToZero:
      return os << "RoundToZero";
    case FloatUnaryOp::Kind::kRoundTiesEven:
      return os << "RoundTiesEven";
    case FloatUnaryOp::Kind::kLog:
      return os << "Log";
    case FloatUnaryOp::Kind::kLog2:
      return os << "Log2";
    case FloatUnaryOp::Kind::kLog10:
      return os << "Log10";
    case FloatUnaryOp::Kind::kLog1p:
      return os << "Log1p";
    case FloatUnaryOp::Kind::kSqrt:
      return os << "Sqrt";
    case FloatUnaryOp::Kind::kCbrt:
      return os << "Cbrt";
    case FloatUnaryOp::Kind::kExp:
      return os << "Exp";
    case FloatUnaryOp::Kind::kExpm1:
      return os << "Expm1";
    case FloatUnaryOp::Kind::kSin:
      return os << "Sin";
    case FloatUnaryOp::Kind::kCos:
      return os << "Cos";
    case FloatUnaryOp::Kind::kAsin:
      return os << "Asin";
    case FloatUnaryOp::Kind::kAcos:
      return os << "Acos";
    case FloatUnaryOp::Kind::kSinh:
      return os << "Sinh";
    case FloatUnaryOp::Kind::kCosh:
      return os << "Cosh";
    case FloatUnaryOp::Kind::kAsinh:
      return os << "Asinh";
    case FloatUnaryOp::Kind::kAcosh:
      return os << "Acosh";
    case FloatUnaryOp::Kind::kTan:
      return os << "Tan";
    case FloatUnaryOp::Kind::kTanh:
      return os << "Tanh";
    case FloatUnaryOp::Kind::kAtan:
      return os << "Atan";
    case FloatUnaryOp::Kind::kAtanh:
      return os << "Atanh";
  }
}
References v8::internal::compiler::turboshaft::FloatUnaryOp::kAbs, v8::internal::compiler::turboshaft::FloatUnaryOp::kAcos, v8::internal::compiler::turboshaft::FloatUnaryOp::kAcosh, v8::internal::compiler::turboshaft::FloatUnaryOp::kAsin, v8::internal::compiler::turboshaft::FloatUnaryOp::kAsinh, v8::internal::compiler::turboshaft::FloatUnaryOp::kAtan, v8::internal::compiler::turboshaft::FloatUnaryOp::kAtanh, v8::internal::compiler::turboshaft::FloatUnaryOp::kCbrt, v8::internal::compiler::turboshaft::FloatUnaryOp::kCos, v8::internal::compiler::turboshaft::FloatUnaryOp::kCosh, v8::internal::compiler::turboshaft::FloatUnaryOp::kExp, v8::internal::compiler::turboshaft::FloatUnaryOp::kExpm1, v8::internal::compiler::turboshaft::FloatUnaryOp::kLog, v8::internal::compiler::turboshaft::FloatUnaryOp::kLog10, v8::internal::compiler::turboshaft::FloatUnaryOp::kLog1p, v8::internal::compiler::turboshaft::FloatUnaryOp::kLog2, v8::internal::compiler::turboshaft::FloatUnaryOp::kNegate, v8::internal::compiler::turboshaft::FloatUnaryOp::kRoundDown, v8::internal::compiler::turboshaft::FloatUnaryOp::kRoundTiesEven, v8::internal::compiler::turboshaft::FloatUnaryOp::kRoundToZero, v8::internal::compiler::turboshaft::FloatUnaryOp::kRoundUp, v8::internal::compiler::turboshaft::FloatUnaryOp::kSilenceNaN, v8::internal::compiler::turboshaft::FloatUnaryOp::kSin, v8::internal::compiler::turboshaft::FloatUnaryOp::kSinh, v8::internal::compiler::turboshaft::FloatUnaryOp::kSqrt, v8::internal::compiler::turboshaft::FloatUnaryOp::kTan, and v8::internal::compiler::turboshaft::FloatUnaryOp::kTanh.
operator<<() [35/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, FrameConstantOp::Kind kind)
Definition at line 498 of file operations.cc.
                                                                 {
  switch (kind) {
    case FrameConstantOp::Kind::kStackCheckOffset:
      return os << "stack check offset";
    case FrameConstantOp::Kind::kFramePointer:
      return os << "frame pointer";
    case FrameConstantOp::Kind::kParentFramePointer:
      return os << "parent frame pointer";
  }
}
References v8::internal::compiler::turboshaft::FrameConstantOp::kFramePointer, v8::internal::compiler::turboshaft::FrameConstantOp::kParentFramePointer, and v8::internal::compiler::turboshaft::FrameConstantOp::kStackCheckOffset.
operator<<() [36/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, GenericBinopOp::Kind kind)
Definition at line 161 of file operations.cc.
                                                                {
  switch (kind) {
#define PRINT_KIND(Name) \
  case GenericBinopOp::Kind::k##Name: \
    return os << #Name;
    GENERIC_BINOP_LIST(PRINT_KIND)
#undef PRINT_KIND
  }
}
References GENERIC_BINOP_LIST, and PRINT_KIND.
operator<<() [37/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, GenericUnopOp::Kind kind)
Definition at line 171 of file operations.cc.
                                                               {
  switch (kind) {
#define PRINT_KIND(Name) \
  case GenericUnopOp::Kind::k##Name: \
    return os << #Name;
    GENERIC_UNOP_LIST(PRINT_KIND)
#undef PRINT_KIND
  }
}
References GENERIC_UNOP_LIST, and PRINT_KIND.
operator<<() [38/70]
std::ostream& v8::internal::compiler::turboshaft::operator<< (std::ostream & os, JSStackCheckOp::Kind kind)
Definition at line 1601 of file operations.cc.
                                                                {
  switch (kind) {
    case JSStackCheckOp::Kind::kFunctionEntry:
      return os << "function-entry";
    case JSStackCheckOp::Kind::kBuiltinEntry:
      return os << "builtin-entry";
    case JSStackCheckOp::Kind::kLoop:
      return os << "loop";
  }
}
References v8::internal::compiler::turboshaft::JSStackCheckOp::kBuiltinEntry, v8::internal::compiler::turboshaft::JSStackCheckOp::kFunctionEntry, and v8::internal::compiler::turboshaft::JSStackCheckOp::kLoop.
operator<<() [39/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, MaybeRegisterRepresentation rep)
Definition at line 9 of file representations.cc.
                                                                        {
  switch (rep) {
    case MaybeRegisterRepresentation::Word32():
      return os << "Word32";
    case MaybeRegisterRepresentation::Word64():
      return os << "Word64";
    case MaybeRegisterRepresentation::Float32():
      return os << "Float32";
    case MaybeRegisterRepresentation::Float64():
      return os << "Float64";
    case MaybeRegisterRepresentation::Tagged():
      return os << "Tagged";
    case MaybeRegisterRepresentation::Compressed():
      return os << "Compressed";
    case MaybeRegisterRepresentation::Simd128():
      return os << "Simd128";
    case MaybeRegisterRepresentation::Simd256():
      return os << "Simd256";
    case MaybeRegisterRepresentation::None():
      return os << "None";
  }
}
References v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::Compressed(), v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::Float32(), v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::Float64(), v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::None(), v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::Simd128(), v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::Simd256(), v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::Tagged(), v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::Word32(), and v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::Word64().
operator<<() [40/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, MemoryRepresentation rep)
Definition at line 32 of file representations.cc.
                                                                 {
  switch (rep) {
    case MemoryRepresentation::Int8():
      return os << "Int8";
    case MemoryRepresentation::Uint8():
      return os << "Uint8";
    case MemoryRepresentation::Int16():
      return os << "Int16";
    case MemoryRepresentation::Uint16():
      return os << "Uint16";
    case MemoryRepresentation::Int32():
      return os << "Int32";
    case MemoryRepresentation::Uint32():
      return os << "Uint32";
    case MemoryRepresentation::Int64():
      return os << "Int64";
    case MemoryRepresentation::Uint64():
      return os << "Uint64";
    case MemoryRepresentation::Float16():
      return os << "Float16";
    case MemoryRepresentation::Float32():
      return os << "Float32";
    case MemoryRepresentation::Float64():
      return os << "Float64";
    case MemoryRepresentation::AnyTagged():
      return os << "AnyTagged";
    case MemoryRepresentation::TaggedPointer():
      return os << "TaggedPointer";
    case MemoryRepresentation::TaggedSigned():
      return os << "TaggedSigned";
    case MemoryRepresentation::AnyUncompressedTagged():
      return os << "AnyUncompressedTagged";
    case MemoryRepresentation::UncompressedTaggedPointer():
      return os << "UncompressedTaggedPointer";
    case MemoryRepresentation::UncompressedTaggedSigned():
      return os << "UncompressedTaggedSigned";
    case MemoryRepresentation::ProtectedPointer():
      return os << "ProtectedPointer";
    case MemoryRepresentation::IndirectPointer():
      return os << "IndirectPointer";
    case MemoryRepresentation::SandboxedPointer():
      return os << "SandboxedPointer";
    case MemoryRepresentation::Simd128():
      return os << "Simd128";
    case MemoryRepresentation::Simd256():
      return os << "Simd256";
  }
}
References v8::internal::compiler::turboshaft::MemoryRepresentation::AnyTagged(), v8::internal::compiler::turboshaft::MemoryRepresentation::AnyUncompressedTagged(), v8::internal::compiler::turboshaft::MemoryRepresentation::Float16(), v8::internal::compiler::turboshaft::MemoryRepresentation::Float32(), v8::internal::compiler::turboshaft::MemoryRepresentation::Float64(), v8::internal::compiler::turboshaft::MemoryRepresentation::IndirectPointer(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int16(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int32(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int64(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int8(), v8::internal::compiler::turboshaft::MemoryRepresentation::ProtectedPointer(), v8::internal::compiler::turboshaft::MemoryRepresentation::SandboxedPointer(), v8::internal::compiler::turboshaft::MemoryRepresentation::Simd128(), v8::internal::compiler::turboshaft::MemoryRepresentation::Simd256(), v8::internal::compiler::turboshaft::MemoryRepresentation::TaggedPointer(), v8::internal::compiler::turboshaft::MemoryRepresentation::TaggedSigned(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint16(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint32(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint64(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint8(), v8::internal::compiler::turboshaft::MemoryRepresentation::UncompressedTaggedPointer(), and v8::internal::compiler::turboshaft::MemoryRepresentation::UncompressedTaggedSigned().
operator<<() [41/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, NewArrayOp::Kind kind)
Definition at line 1437 of file operations.cc.
                                                            {
  switch (kind) {
    case NewArrayOp::Kind::kDouble:
      return os << "Double";
    case NewArrayOp::Kind::kObject:
      return os << "Object";
  }
}
References v8::internal::compiler::turboshaft::NewArrayOp::kDouble, and v8::internal::compiler::turboshaft::NewArrayOp::kObject.
operator<<() [42/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, NumericKind kind)
Definition at line 1211 of file operations.cc.
                                                         {
  switch (kind) {
    case NumericKind::kFloat64Hole:
      return os << "Float64Hole";
#ifdef V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
    case NumericKind::kFloat64Undefined:
      return os << "Float64Undefined";
#endif // V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
    case NumericKind::kFinite:
      return os << "Finite";
    case NumericKind::kInteger:
      return os << "Integer";
    case NumericKind::kSafeInteger:
      return os << "SafeInteger";
    case NumericKind::kInt32:
      return os << "kInt32";
    case NumericKind::kSmi:
      return os << "kSmi";
    case NumericKind::kMinusZero:
      return os << "MinusZero";
    case NumericKind::kNaN:
      return os << "NaN";
  }
}
References kFinite, kFloat64Hole, kInt32, kInteger, kMinusZero, kNaN, kSafeInteger, and kSmi.
operator<<() [43/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, ObjectIsOp::InputAssumptions input_assumptions)
Definition at line 1199 of file operations.cc.
                                                                       {
  switch (input_assumptions) {
    case ObjectIsOp::InputAssumptions::kNone:
      return os << "None";
    case ObjectIsOp::InputAssumptions::kHeapObject:
      return os << "HeapObject";
    case ObjectIsOp::InputAssumptions::kBigInt:
      return os << "BigInt";
  }
}
References v8::internal::compiler::turboshaft::ObjectIsOp::kBigInt, v8::internal::compiler::turboshaft::ObjectIsOp::kHeapObject, and v8::internal::compiler::turboshaft::ObjectIsOp::kNone.
operator<<() [44/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, ObjectIsOp::Kind kind)
Definition at line 1154 of file operations.cc.
                                                            {
  switch (kind) {
    case ObjectIsOp::Kind::kArrayBufferView:
      return os << "ArrayBufferView";
    case ObjectIsOp::Kind::kBigInt:
      return os << "BigInt";
    case ObjectIsOp::Kind::kBigInt64:
      return os << "BigInt64";
    case ObjectIsOp::Kind::kCallable:
      return os << "Callable";
    case ObjectIsOp::Kind::kConstructor:
      return os << "Constructor";
    case ObjectIsOp::Kind::kDetectableCallable:
      return os << "DetectableCallable";
    case ObjectIsOp::Kind::kInternalizedString:
      return os << "InternalizedString";
    case ObjectIsOp::Kind::kNonCallable:
      return os << "NonCallable";
    case ObjectIsOp::Kind::kNumber:
      return os << "Number";
    case ObjectIsOp::Kind::kNumberOrUndefined:
      return os << "NumberOrUndefined";
    case ObjectIsOp::Kind::kNumberFitsInt32:
      return os << "NumberFitsInt32";
    case ObjectIsOp::Kind::kNumberOrBigInt:
      return os << "NumberOrBigInt";
    case ObjectIsOp::Kind::kReceiver:
      return os << "Receiver";
    case ObjectIsOp::Kind::kReceiverOrNullOrUndefined:
      return os << "ReceiverOrNullOrUndefined";
    case ObjectIsOp::Kind::kSmi:
      return os << "Smi";
    case ObjectIsOp::Kind::kString:
      return os << "String";
    case ObjectIsOp::Kind::kStringOrStringWrapper:
      return os << "StringOrStringWrapper";
    case ObjectIsOp::Kind::kStringOrOddball:
      return os << "StringOrOddball";
    case ObjectIsOp::Kind::kSymbol:
      return os << "Symbol";
    case ObjectIsOp::Kind::kUndetectable:
      return os << "Undetectable";
  }
}
References v8::internal::compiler::turboshaft::ObjectIsOp::kArrayBufferView, v8::internal::compiler::turboshaft::ObjectIsOp::kBigInt, v8::internal::compiler::turboshaft::ObjectIsOp::kBigInt64, v8::internal::compiler::turboshaft::ObjectIsOp::kCallable, v8::internal::compiler::turboshaft::ObjectIsOp::kConstructor, v8::internal::compiler::turboshaft::ObjectIsOp::kDetectableCallable, v8::internal::compiler::turboshaft::ObjectIsOp::kInternalizedString, v8::internal::compiler::turboshaft::ObjectIsOp::kNonCallable, v8::internal::compiler::turboshaft::ObjectIsOp::kNumber, v8::internal::compiler::turboshaft::ObjectIsOp::kNumberFitsInt32, v8::internal::compiler::turboshaft::ObjectIsOp::kNumberOrBigInt, v8::internal::compiler::turboshaft::ObjectIsOp::kNumberOrUndefined, v8::internal::compiler::turboshaft::ObjectIsOp::kReceiver, v8::internal::compiler::turboshaft::ObjectIsOp::kReceiverOrNullOrUndefined, v8::internal::compiler::turboshaft::ObjectIsOp::kSmi, v8::internal::compiler::turboshaft::ObjectIsOp::kString, v8::internal::compiler::turboshaft::ObjectIsOp::kStringOrOddball, v8::internal::compiler::turboshaft::ObjectIsOp::kStringOrStringWrapper, v8::internal::compiler::turboshaft::ObjectIsOp::kSymbol, and v8::internal::compiler::turboshaft::ObjectIsOp::kUndetectable.
operator<<() [45/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, OpEffects effects)
Definition at line 1101 of file operations.cc.
                                                          {
  auto produce_consume = [](bool produces, bool consumes) {
    if (!produces && !consumes) {
      return "";
    } else if (produces && !consumes) {
      return "";
    } else if (!produces && consumes) {
      return "";
    } else if (produces && consumes) {
      return "";
    }
    UNREACHABLE();
  };
  os << produce_consume(effects.produces.load_heap_memory,
                        effects.consumes.load_heap_memory);
  os << produce_consume(effects.produces.load_off_heap_memory,
                        effects.consumes.load_off_heap_memory);
  os << "\u2003"; // em space
  os << produce_consume(effects.produces.store_heap_memory,
                        effects.consumes.store_heap_memory);
  os << produce_consume(effects.produces.store_off_heap_memory,
                        effects.consumes.store_off_heap_memory);
  os << "\u2003"; // em space
  os << produce_consume(effects.produces.before_raw_heap_access,
                        effects.consumes.before_raw_heap_access);
  os << produce_consume(effects.produces.after_raw_heap_access,
                        effects.consumes.after_raw_heap_access);
  os << "\u2003"; // em space
  os << produce_consume(effects.produces.control_flow,
                        effects.consumes.control_flow);
  os << "\u2003"; // em space
  os << (effects.can_create_identity ? 'i' : '_');
  os << ' ' << (effects.can_allocate ? 'a' : '_');
  return os;
}
References v8::internal::compiler::turboshaft::EffectDimensions::after_raw_heap_access, v8::internal::compiler::turboshaft::EffectDimensions::before_raw_heap_access, v8::internal::compiler::turboshaft::OpEffects::can_allocate, v8::internal::compiler::turboshaft::OpEffects::can_create_identity, v8::internal::compiler::turboshaft::OpEffects::consumes, v8::internal::compiler::turboshaft::EffectDimensions::control_flow, v8::internal::compiler::turboshaft::EffectDimensions::load_heap_memory, v8::internal::compiler::turboshaft::EffectDimensions::load_off_heap_memory, v8::internal::compiler::turboshaft::OpEffects::produces, v8::internal::compiler::turboshaft::EffectDimensions::store_heap_memory, v8::internal::compiler::turboshaft::EffectDimensions::store_off_heap_memory, and v8::internal::UNREACHABLE().
operator<<() [46/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, OperationPrintStyle styled_op)
Definition at line 147 of file operations.cc.
                                                                      {
  const Operation& op = styled_op.op;
  os << OpcodeName(op.opcode);
  op.PrintInputs(os, styled_op.op_index_prefix);
  op.PrintOptions(os);
  return os;
}
References v8::internal::compiler::turboshaft::OperationPrintStyle::op, v8::internal::compiler::turboshaft::OperationPrintStyle::op_index_prefix, v8::internal::compiler::turboshaft::Operation::opcode, OpcodeName(), v8::internal::compiler::turboshaft::Operation::PrintInputs(), and v8::internal::compiler::turboshaft::Operation::PrintOptions().
operator<<() [47/70]
std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, OpIndex idx)
Definition at line 1083 of file operations.cc.
                                                    {
  if (!idx.valid()) {
    return os << "<invalid OpIndex>";
  }
  return os << idx.id();
}
References v8::internal::compiler::turboshaft::OpIndex::id(), and v8::internal::compiler::turboshaft::OpIndex::valid().
operator<<() [48/70]
std::ostream& v8::internal::compiler::turboshaft::operator<< (std::ostream & os, OptionalOpIndex idx) [inline]
Definition at line 196 of file index.h.
                                                                      {
  return os << idx.value_or_invalid();
}
References v8::internal::compiler::turboshaft::OptionalOpIndex::value_or_invalid().
operator<<() [49/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, OverflowCheckedUnaryOp::Kind kind)
Definition at line 207 of file operations.cc.
                                                                        {
  switch (kind) {
    case OverflowCheckedUnaryOp::Kind::kAbs:
      return os << "kAbs";
  }
}
References v8::internal::compiler::turboshaft::OverflowCheckedUnaryOp::kAbs.
operator<<() [50/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, PaddingSpace padding)
Definition at line 18 of file copying-phase.cc.
                                                             {
  if (padding.spaces > 10000) return os;
  for (int i = 0; i < padding.spaces; ++i) {
    os << ' ';
  }
  return os;
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::compiler::turboshaft::PaddingSpace::spaces.
operator<<() [51/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, PrintAsBlockHeader block_header)
Definition at line 64 of file graph.cc.
                                                                        {
  const Block& block = block_header.block;
  os << block.kind() << " " << block_header.block_id;
  if (!block.Predecessors().empty()) {
    os << " <- ";
    bool first = true;
    for (const Block* pred : block.Predecessors()) {
      if (!first) os << ", ";
      os << pred->index();
      first = false;
    }
  }
  return os;
}
References v8::internal::compiler::turboshaft::PrintAsBlockHeader::block, v8::internal::compiler::turboshaft::PrintAsBlockHeader::block_id, v8::internal::compiler::turboshaft::Block::kind(), and v8::internal::compiler::turboshaft::Block::Predecessors().
operator<<() [52/70]
std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, RootIndex index)
Definition at line 155 of file operations.cc.
                                                        {
  // Clearly this doesn't maximize convenience, but we don't want to include
  // all those names in the binary.
  return os << static_cast<uint16_t>(index);
}
References v8::internal::index.
operator<<() [53/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, SameValueOp::Mode mode)
Definition at line 1581 of file operations.cc.
                                                             {
  switch (mode) {
    case SameValueOp::Mode::kSameValue:
      return os << "SameValue";
    case SameValueOp::Mode::kSameValueNumbersOnly:
      return os << "SameValueNumbersOnly";
  }
}
References v8::internal::compiler::turboshaft::SameValueOp::kSameValue, v8::internal::compiler::turboshaft::SameValueOp::kSameValueNumbersOnly, and mode().
operator<<() [54/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, SelectOp::Implementation kind)
Definition at line 447 of file operations.cc.
                                                                    {
  switch (kind) {
    case SelectOp::Implementation::kBranch:
      return os << "Branch";
    case SelectOp::Implementation::kCMove:
      return os << "CMove";
  }
}
References v8::internal::compiler::turboshaft::SelectOp::kBranch, and v8::internal::compiler::turboshaft::SelectOp::kCMove.
operator<<() [55/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, ShiftOp::Kind kind)
Definition at line 324 of file operations.cc.
                                                         {
  switch (kind) {
    case ShiftOp::Kind::kShiftRightArithmeticShiftOutZeros:
      return os << "ShiftRightArithmeticShiftOutZeros";
    case ShiftOp::Kind::kShiftRightArithmetic:
      return os << "ShiftRightArithmetic";
    case ShiftOp::Kind::kShiftRightLogical:
      return os << "ShiftRightLogical";
    case ShiftOp::Kind::kShiftLeft:
      return os << "ShiftLeft";
    case ShiftOp::Kind::kRotateRight:
      return os << "RotateRight";
    case ShiftOp::Kind::kRotateLeft:
      return os << "RotateLeft";
  }
}
operator<<() [56/70]
std::ostream& v8::internal::compiler::turboshaft::operator<< (std::ostream & os, StoreObservability observability) [inline]
Definition at line 84 of file store-store-elimination-reducer-inl.h.
                                                                  {
  switch (observability) {
    case StoreObservability::kUnobservable:
      return os << "Unobservable";
    case StoreObservability::kGCObservable:
      return os << "GCObservable";
    case StoreObservability::kObservable:
      return os << "Observable";
  }
}
References kGCObservable, kObservable, and kUnobservable.
operator<<() [57/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, StringAtOp::Kind kind)
Definition at line 1498 of file operations.cc.
                                                            {
  switch (kind) {
    case StringAtOp::Kind::kCharCode:
      return os << "CharCode";
    case StringAtOp::Kind::kCodePoint:
      return os << "CodePoint";
  }
}
References v8::internal::compiler::turboshaft::StringAtOp::kCharCode, and v8::internal::compiler::turboshaft::StringAtOp::kCodePoint.
operator<<() [58/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, StringComparisonOp::Kind kind)
Definition at line 1518 of file operations.cc.
                                                                    {
  switch (kind) {
    case StringComparisonOp::Kind::kEqual:
      return os << "Equal";
    case StringComparisonOp::Kind::kLessThan:
      return os << "LessThan";
    case StringComparisonOp::Kind::kLessThanOrEqual:
      return os << "LessThanOrEqual";
  }
}
References v8::internal::compiler::turboshaft::StringComparisonOp::kEqual, v8::internal::compiler::turboshaft::StringComparisonOp::kLessThan, and v8::internal::compiler::turboshaft::StringComparisonOp::kLessThanOrEqual.
operator<<() [59/70]
std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, TaggedBitcastOp::Kind kind)
Definition at line 423 of file operations.cc.
                                                                 {
  switch (kind) {
    case TaggedBitcastOp::Kind::kSmi:
      return os << "Smi";
    case TaggedBitcastOp::Kind::kHeapObject:
      return os << "HeapObject";
    case TaggedBitcastOp::Kind::kTagAndSmiBits:
      return os << "TagAndSmiBits";
    case TaggedBitcastOp::Kind::kAny:
      return os << "Any";
  }
}
References v8::internal::compiler::turboshaft::TaggedBitcastOp::kAny, v8::internal::compiler::turboshaft::TaggedBitcastOp::kHeapObject, v8::internal::compiler::turboshaft::TaggedBitcastOp::kSmi, and v8::internal::compiler::turboshaft::TaggedBitcastOp::kTagAndSmiBits.
operator<<() [60/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, TransitionAndStoreArrayElementOp::Kind kind)
Definition at line 1538 of file operations.cc.
                                                                    {
  switch (kind) {
    case TransitionAndStoreArrayElementOp::Kind::kElement:
      return os << "Element";
    case TransitionAndStoreArrayElementOp::Kind::kNumberElement:
      return os << "NumberElement";
    case TransitionAndStoreArrayElementOp::Kind::kOddballElement:
      return os << "OddballElement";
    case TransitionAndStoreArrayElementOp::Kind::kNonNumberElement:
      return os << "NonNumberElement";
    case TransitionAndStoreArrayElementOp::Kind::kSignedSmallElement:
      return os << "SignedSmallElement";
  }
}
References v8::internal::compiler::turboshaft::TransitionAndStoreArrayElementOp::kElement, v8::internal::compiler::turboshaft::TransitionAndStoreArrayElementOp::kNonNumberElement, v8::internal::compiler::turboshaft::TransitionAndStoreArrayElementOp::kNumberElement, v8::internal::compiler::turboshaft::TransitionAndStoreArrayElementOp::kOddballElement, and v8::internal::compiler::turboshaft::TransitionAndStoreArrayElementOp::kSignedSmallElement.
operator<<() [61/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, TruncateJSPrimitiveToUntaggedOp::InputAssumptions input_assumptions)
Definition at line 1413 of file operations.cc.
                                                                       {
  switch (input_assumptions) {
    case TruncateJSPrimitiveToUntaggedOp::InputAssumptions::kBigInt:
      return os << "BigInt";
    case TruncateJSPrimitiveToUntaggedOp::InputAssumptions::kNumberOrOddball:
      return os << "NumberOrOddball";
    case TruncateJSPrimitiveToUntaggedOp::InputAssumptions::kHeapObject:
      return os << "HeapObject";
    case TruncateJSPrimitiveToUntaggedOp::InputAssumptions::kObject:
      return os << "Object";
  }
}
References v8::internal::compiler::turboshaft::TruncateJSPrimitiveToUntaggedOp::kBigInt, v8::internal::compiler::turboshaft::TruncateJSPrimitiveToUntaggedOp::kHeapObject, v8::internal::compiler::turboshaft::TruncateJSPrimitiveToUntaggedOp::kNumberOrOddball, and v8::internal::compiler::turboshaft::TruncateJSPrimitiveToUntaggedOp::kObject.
operator<<() [62/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, TruncateJSPrimitiveToUntaggedOp::UntaggedKind kind)
Definition at line 1401 of file operations.cc.
                                                                           {
  switch (kind) {
    case TruncateJSPrimitiveToUntaggedOp::UntaggedKind::kInt32:
      return os << "Int32";
    case TruncateJSPrimitiveToUntaggedOp::UntaggedKind::kInt64:
      return os << "Int64";
    case TruncateJSPrimitiveToUntaggedOp::UntaggedKind::kBit:
      return os << "Bit";
  }
}
References v8::internal::compiler::turboshaft::TruncateJSPrimitiveToUntaggedOp::kBit, v8::internal::compiler::turboshaft::TruncateJSPrimitiveToUntaggedOp::kInt32, and v8::internal::compiler::turboshaft::TruncateJSPrimitiveToUntaggedOp::kInt64.
operator<<() [63/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, TruncateJSPrimitiveToUntaggedOrDeoptOp::UntaggedKind kind)
Definition at line 1428 of file operations.cc.
                                                             {
  switch (kind) {
    case TruncateJSPrimitiveToUntaggedOrDeoptOp::UntaggedKind::kInt32:
      return os << "Int32";
  }
}
References v8::internal::compiler::turboshaft::TruncateJSPrimitiveToUntaggedOrDeoptOp::kInt32.
operator<<() [64/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, TryChangeOp::Kind kind)
Definition at line 414 of file operations.cc.
                                                             {
  switch (kind) {
    case TryChangeOp::Kind::kSignedFloatTruncateOverflowUndefined:
      return os << "SignedFloatTruncateOverflowUndefined";
    case TryChangeOp::Kind::kUnsignedFloatTruncateOverflowUndefined:
      return os << "UnsignedFloatTruncateOverflowUndefined";
  }
}
References v8::internal::compiler::turboshaft::TryChangeOp::kSignedFloatTruncateOverflowUndefined, and v8::internal::compiler::turboshaft::TryChangeOp::kUnsignedFloatTruncateOverflowUndefined.
operator<<() [65/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, Word32SignHintOp::Sign sign)
Definition at line 181 of file operations.cc.
                                                                  {
  switch (sign) {
    case Word32SignHintOp::Sign::kSigned:
      return os << "Signed";
    case Word32SignHintOp::Sign::kUnsigned:
      return os << "Unsigned";
  }
}
References v8::internal::compiler::turboshaft::Word32SignHintOp::kSigned, v8::internal::compiler::turboshaft::Word32SignHintOp::kUnsigned, and v8::internal::sign.
operator<<() [66/70]
V8_EXPORT_PRIVATE std::ostream & v8::internal::compiler::turboshaft::operator<< (std::ostream & os, WordUnaryOp::Kind kind)
Definition at line 190 of file operations.cc.
                                                             {
  switch (kind) {
    case WordUnaryOp::Kind::kReverseBytes:
      return os << "ReverseBytes";
    case WordUnaryOp::Kind::kCountLeadingZeros:
      return os << "CountLeadingZeros";
    case WordUnaryOp::Kind::kCountTrailingZeros:
      return os << "CountTrailingZeros";
    case WordUnaryOp::Kind::kPopCount:
      return os << "PopCount";
    case WordUnaryOp::Kind::kSignExtend8:
      return os << "SignExtend8";
    case WordUnaryOp::Kind::kSignExtend16:
      return os << "SignExtend16";
  }
}
References v8::internal::compiler::turboshaft::WordUnaryOp::kCountLeadingZeros, v8::internal::compiler::turboshaft::WordUnaryOp::kCountTrailingZeros, v8::internal::compiler::turboshaft::WordUnaryOp::kPopCount, v8::internal::compiler::turboshaft::WordUnaryOp::kReverseBytes, v8::internal::compiler::turboshaft::WordUnaryOp::kSignExtend16, and v8::internal::compiler::turboshaft::WordUnaryOp::kSignExtend8.
operator<<() [67/70]
std::ostream& v8::internal::compiler::turboshaft::operator<< (std::ostream & stream, const ControlState & state) [inline]
Definition at line 123 of file dead-code-elimination-reducer.h.
                                                           {
  switch (state.kind) {
    case ControlState::kNotEliminatable:
      return stream << "NotEliminatable";
    case ControlState::kBlock:
      return stream << "Block(" << state.block << ")";
    case ControlState::kUnreachable:
      return stream << "Unreachable";
  }
}
References v8::internal::compiler::turboshaft::ControlState::block, v8::internal::compiler::turboshaft::ControlState::kBlock, v8::internal::compiler::turboshaft::ControlState::kind, v8::internal::compiler::turboshaft::ControlState::kNotEliminatable, and v8::internal::compiler::turboshaft::ControlState::kUnreachable.
operator<<() [68/70]
std::ostream& v8::internal::compiler::turboshaft::operator<< (std::ostream & stream, const Type & type) [inline]
Definition at line 906 of file types.h.
                                                                    {
  type.PrintTo(stream);
  return stream;
}
References v8::internal::tracing::type.
operator<<() [69/70]
std::ostream& v8::internal::compiler::turboshaft::operator<< (std::ostream & stream, OperationState::Liveness liveness) [inline]
Definition at line 167 of file dead-code-elimination-reducer.h.
                                                                 {
  switch (liveness) {
    case OperationState::kDead:
      return stream << "Dead";
    case OperationState::kLive:
      return stream << "Live";
  }
  UNREACHABLE();
}
References v8::internal::compiler::turboshaft::OperationState::kDead, v8::internal::compiler::turboshaft::OperationState::kLive, and v8::internal::UNREACHABLE().
operator<<() [70/70]
std::ostream& v8::internal::compiler::turboshaft::operator<< (std::ostream & stream, Type::Kind kind) [inline]
Definition at line 885 of file types.h.
                                                                 {
  switch (kind) {
    case Type::Kind::kInvalid:
      return stream << "Invalid";
    case Type::Kind::kNone:
      return stream << "None";
    case Type::Kind::kWord32:
      return stream << "Word32";
    case Type::Kind::kWord64:
      return stream << "Word64";
    case Type::Kind::kFloat32:
      return stream << "Float32";
    case Type::Kind::kFloat64:
      return stream << "Float64";
    case Type::Kind::kTuple:
      return stream << "Tuple";
    case Type::Kind::kAny:
      return stream << "Any";
  }
}
References v8::internal::anonymous_namespace{isolate.cc}::kInvalid.
operator==() [1/10]
template<class T , class... Ts>
bool v8::internal::compiler::turboshaft::operator== (all_of< Ts... > values, const T & target)
Definition at line 72 of file utils.h.
                                                       {
  return values.AllEqualTo(target, std::index_sequence_for<Ts...>{});
}
References v8::internal::compiler::turboshaft::all_of< Ts >::AllEqualTo().
operator==() [2/10]
bool v8::internal::compiler::turboshaft::operator== (const ControlState & lhs, const ControlState & rhs) [inline]
Definition at line 135 of file dead-code-elimination-reducer.h.
                                                                         {
  if (lhs.kind != rhs.kind) return false;
  if (lhs.kind == ControlState::kBlock) {
    DCHECK_EQ(rhs.kind, ControlState::kBlock);
    return lhs.block == rhs.block;
  }
  return true;
}
References v8::internal::compiler::turboshaft::ControlState::block, DCHECK_EQ, v8::internal::compiler::turboshaft::ControlState::kBlock, and v8::internal::compiler::turboshaft::ControlState::kind.
operator==() [3/10]
bool v8::internal::compiler::turboshaft::operator== (const FrameStateData & lhs, const FrameStateData & rhs) [inline]
Definition at line 181 of file deopt-data.h.
                                                                             {
  return lhs.frame_state_info == rhs.frame_state_info &&
         lhs.instructions == rhs.instructions &&
         lhs.machine_types == rhs.machine_types &&
         lhs.int_operands == rhs.int_operands;
}
References v8::internal::compiler::turboshaft::FrameStateData::frame_state_info, v8::internal::compiler::turboshaft::FrameStateData::instructions, v8::internal::compiler::turboshaft::FrameStateData::int_operands, and v8::internal::compiler::turboshaft::FrameStateData::machine_types.
operator==() [4/10]
template<class T , class... Ts>
bool v8::internal::compiler::turboshaft::operator== (const T & value, any_of< Ts... > options)
Definition at line 40 of file utils.h.
                                                       {
  return options.Contains(value, std::index_sequence_for<Ts...>{});
}
References v8::internal::compiler::turboshaft::any_of< Ts >::Contains(), and v8::internal::value.
operator==() [5/10]
bool v8::internal::compiler::turboshaft::operator== (const Type & lhs, const Type & rhs) [inline]
Definition at line 911 of file types.h.
                                                         {
  return lhs.Equals(rhs);
}
References v8::internal::compiler::turboshaft::Type::Equals().
operator==() [6/10]
constexpr bool v8::internal::compiler::turboshaft::operator== (MaybeRegisterRepresentation a, MaybeRegisterRepresentation b) [inline], [constexpr]
Definition at line 349 of file representations.h.
                                                                   {
  return a.value() == b.value();
}
References v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::value().
operator==() [7/10]
constexpr bool v8::internal::compiler::turboshaft::operator== (MemoryRepresentation a, MemoryRepresentation b) [inline], [constexpr]
Definition at line 938 of file representations.h.
                                                            {
  return a.value() == b.value();
}
References v8::internal::compiler::turboshaft::MemoryRepresentation::value().
operator==() [8/10]
constexpr bool v8::internal::compiler::turboshaft::operator== (nullrep_t , nullrep_t) [inline], [constexpr]
Definition at line 204 of file index.h.
{ return true; }
operator==() [9/10]
constexpr bool v8::internal::compiler::turboshaft::operator== (nullrep_t , RegisterRepresentation) [inline], [constexpr]
Definition at line 205 of file index.h.
                                                                    {
  return false;
}
operator==() [10/10]
constexpr bool v8::internal::compiler::turboshaft::operator== (RegisterRepresentation , nullrep_t) [inline], [constexpr]
Definition at line 208 of file index.h.
                                                                    {
  return false;
}
OptionalV()
template<typename T >
v8::internal::compiler::turboshaft::OptionalV (V< T >) -> OptionalV< T >
PrintBytecode()
void v8::internal::compiler::turboshaft::PrintBytecode (PipelineData & data, maglev::MaglevCompilationInfo * compilation_info)
Definition at line 6232 of file turbolev-graph-builder.cc.
                                                                  {
  DCHECK(data.info()->trace_turbo_graph());
  maglev::MaglevCompilationUnit* top_level_unit =
      compilation_info->toplevel_compilation_unit();
  CodeTracer* code_tracer = data.GetCodeTracer();
  CodeTracer::StreamScope tracing_scope(code_tracer);
  tracing_scope.stream()
      << "\n----- Bytecode before MaglevGraphBuilding -----\n"
      << std::endl;
  tracing_scope.stream() << "Function: "
                         << Brief(*compilation_info->toplevel_function())
                         << std::endl;
  BytecodeArray::Disassemble(top_level_unit->bytecode().object(),
PrintMaglevGraph()
void v8::internal::compiler::turboshaft::PrintMaglevGraph (PipelineData & data, maglev::Graph * maglev_graph, const char * msg)
Definition at line 6250 of file turbolev-graph-builder.cc.
                                                                  {
  CodeTracer* code_tracer = data.GetCodeTracer();
  CodeTracer::StreamScope tracing_scope(code_tracer);
Referenced by RunMaglevOptimizations().
PrintMapSet()
void v8::internal::compiler::turboshaft::PrintMapSet (std::ostream & os, const ZoneRefSet< Map > & maps)
Definition at line 1554 of file operations.cc.
                                                              {
  os << "{";
  for (size_t i = 0; i < maps.size(); ++i) {
    if (i != 0) os << ",";
    os << JSONEscaped(maps[i].object());
  }
  os << "}";
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::ZoneCompactSet< T >::size().
Referenced by v8::internal::compiler::turboshaft::CompareMapsOp::PrintOptions(), v8::internal::compiler::turboshaft::CheckMapsOp::PrintOptions(), and v8::internal::compiler::turboshaft::AssumeMapOp::PrintOptions().
PrintTurboshaftCustomDataPerBlock()
void v8::internal::compiler::turboshaft::PrintTurboshaftCustomDataPerBlock (std::ofstream & stream, const char * data_name, const Graph & graph, std::function< bool(std::ostream &, const Graph &, BlockIndex)> printer)
Definition at line 126 of file graph-visualizer.cc.
                                                                      {
  DCHECK(printer);
  stream << "{\"name\":\"" << data_name
         << "\", \"type\":\"turboshaft_custom_data\", "
            "\"data_target\":\"blocks\", \"data\":[";
  bool first = true;
  for (const Block& block : graph.blocks()) {
    std::stringstream sstream;
    BlockIndex index = block.index();
    if (printer(sstream, graph, index)) {
      stream << (first ? "\n" : ",\n") << "{\"key\":" << index.id()
             << ", \"value\":\"" << sstream.str() << "\"}";
      first = false;
    }
  }
  stream << "]},\n";
}
References v8::internal::DCHECK(), graph(), and v8::internal::index.
Referenced by v8::internal::compiler::turboshaft::Tracing::PrintPerBlockData(), and PrintTurboshaftGraphForTurbolizer().
PrintTurboshaftCustomDataPerOperation()
void v8::internal::compiler::turboshaft::PrintTurboshaftCustomDataPerOperation (std::ofstream & stream, const char * data_name, const Graph & graph, std::function< bool(std::ostream &, const Graph &, OpIndex)> printer)
Definition at line 107 of file graph-visualizer.cc.
                                                                   {
  DCHECK(printer);
  stream << "{\"name\":\"" << data_name
         << "\", \"type\":\"turboshaft_custom_data\", "
            "\"data_target\":\"operations\", \"data\":[";
  bool first = true;
  for (auto index : graph.AllOperationIndices()) {
    std::stringstream sstream;
    if (printer(sstream, graph, index)) {
      stream << (first ? "\n" : ",\n") << "{\"key\":" << index.id()
             << ", \"value\":\"" << sstream.str() << "\"}";
      first = false;
    }
  }
  stream << "]},\n";
}
References v8::internal::DCHECK(), graph(), and v8::internal::index.
Referenced by v8::internal::compiler::turboshaft::Tracing::PrintPerOperationData(), and PrintTurboshaftGraphForTurbolizer().
PrintTurboshaftGraph()
void v8::internal::compiler::turboshaft::PrintTurboshaftGraph (PipelineData * data, Zone * temp_zone, CodeTracer * code_tracer, const char * phase_name)
Definition at line 39 of file phase.cc.
                                                                           {
  if (data->info()->trace_turbo_json()) {
    UnparkedScopeIfNeeded scope(data->broker());
    AllowHandleDereference allow_deref;
    turboshaft::Graph& graph = data->graph();
    TurboJsonFile json_of(data->info(), std::ios_base::app);
    PrintTurboshaftGraphForTurbolizer(json_of, graph, phase_name,
                                      data->node_origins(), temp_zone);
  }
  if (data->info()->trace_turbo_graph()) {
    DCHECK(code_tracer);
    UnparkedScopeIfNeeded scope(data->broker());
    AllowHandleDereference allow_deref;
    CodeTracer::StreamScope tracing_scope(code_tracer);
    tracing_scope.stream() << "\n----- " << phase_name << " -----\n"
                           << data->graph();
  }
}
References v8::internal::compiler::turboshaft::PipelineData::broker(), v8::internal::DCHECK(), v8::internal::compiler::turboshaft::PipelineData::graph(), graph(), v8::internal::compiler::turboshaft::PipelineData::info(), v8::internal::compiler::turboshaft::PipelineData::node_origins(), PrintTurboshaftGraphForTurbolizer(), and v8::internal::CodeTracer::StreamScope::stream().
Referenced by v8::internal::compiler::turboshaft::Pipeline::PrintGraph().
PrintTurboshaftGraphForTurbolizer()
void v8::internal::compiler::turboshaft::PrintTurboshaftGraphForTurbolizer (std::ofstream & stream, const Graph & graph, const char * phase_name, NodeOriginTable * node_origins, Zone * temp_zone)
Definition at line 62 of file phase.cc.
                                                        {
  stream << "{\"name\":\"" << phase_name
         << "\",\"type\":\"turboshaft_graph\",\"data\":"
         << AsJSON(graph, node_origins, temp_zone) << "},\n";
  PrintTurboshaftCustomDataPerOperation(
      stream, "Properties", graph,
      [](std::ostream& stream, const turboshaft::Graph& graph,
         turboshaft::OpIndex index) -> bool {
        const auto& op = graph.Get(index);
        op.PrintOptions(stream);
        return true;
      });
  PrintTurboshaftCustomDataPerOperation(
      stream, "Types", graph,
      [](std::ostream& stream, const turboshaft::Graph& graph,
         turboshaft::OpIndex index) -> bool {
        turboshaft::Type type = graph.operation_types()[index];
        if (!type.IsInvalid() && !type.IsNone()) {
          type.PrintTo(stream);
          return true;
        }
        return false;
      });
  PrintTurboshaftCustomDataPerOperation(
      stream, "Representations", graph,
      [](std::ostream& stream, const turboshaft::Graph& graph,
         turboshaft::OpIndex index) -> bool {
        const Operation& op = graph.Get(index);
        stream << PrintCollection(op.outputs_rep());
        return true;
      });
  PrintTurboshaftCustomDataPerOperation(
      stream, "Use Count (saturated)", graph,
      [](std::ostream& stream, const turboshaft::Graph& graph,
         turboshaft::OpIndex index) -> bool {
        stream << static_cast<int>(graph.Get(index).saturated_use_count.Get());
        return true;
      });
#ifdef DEBUG
  PrintTurboshaftCustomDataPerBlock(
      stream, "Type Refinements", graph,
      [](std::ostream& stream, const turboshaft::Graph& graph,
         turboshaft::BlockIndex index) -> bool {
        const std::vector<std::pair<turboshaft::OpIndex, turboshaft::Type>>&
            refinements = graph.block_type_refinement()[index];
        if (refinements.empty()) return false;
        stream << "\\n";
        for (const auto& [op, type] : refinements) {
          stream << op << " : " << type << "\\n";
        }
        return true;
      });
#endif // DEBUG
}
References AsJSON(), v8::internal::anonymous_namespace{json-stringifier.cc}::for(), graph(), v8::internal::index, v8::internal::compiler::turboshaft::Operation::outputs_rep(), v8::internal::PrintCollection(), PrintTurboshaftCustomDataPerBlock(), PrintTurboshaftCustomDataPerOperation(), and v8::internal::tracing::type.
Referenced by v8::internal::compiler::Pipeline::GenerateTurboshaftCodeForTesting(), and PrintTurboshaftGraph().
PropagateDeferred()
V8_EXPORT_PRIVATE void v8::internal::compiler::turboshaft::PropagateDeferred (Graph & graph)
Definition at line 257 of file instruction-selection-phase.cc.
                                     {
  graph.StartBlock().set_custom_data(
      0, Block::CustomDataKind::kDeferredInSchedule);
  for (Block& block : graph.blocks()) {
    const Block* predecessor = block.LastPredecessor();
    if (predecessor == nullptr) {
      continue;
    } else if (block.IsLoop()) {
      // We only consider the forward edge for loop headers.
      predecessor = predecessor->NeighboringPredecessor();
      DCHECK_NOT_NULL(predecessor);
      DCHECK_EQ(predecessor->NeighboringPredecessor(), nullptr);
      block.set_custom_data(predecessor->get_custom_data(
                                Block::CustomDataKind::kDeferredInSchedule),
                            Block::CustomDataKind::kDeferredInSchedule);
    } else if (predecessor->NeighboringPredecessor() == nullptr) {
      // This block has only a single predecessor. Due to edge-split form, those
      // are the only blocks that can be the target of a branch-like op which
      // might potentially provide a BranchHint to defer this block.
      const bool is_deferred =
          predecessor->get_custom_data(
              Block::CustomDataKind::kDeferredInSchedule) ||
          IsUnlikelySuccessor(predecessor, &block, graph);
      block.set_custom_data(is_deferred,
                            Block::CustomDataKind::kDeferredInSchedule);
    } else {
      block.set_custom_data(true, Block::CustomDataKind::kDeferredInSchedule);
      for (; predecessor; predecessor = predecessor->NeighboringPredecessor()) {
        // If there is a single predecessor that is not deferred, then block is
        // also not deferred.
        if (!predecessor->get_custom_data(
                Block::CustomDataKind::kDeferredInSchedule)) {
          block.set_custom_data(false,
                                Block::CustomDataKind::kDeferredInSchedule);
          break;
        }
      }
    }
  }
}
References DCHECK_EQ, DCHECK_NOT_NULL, v8::internal::compiler::turboshaft::Block::get_custom_data(), graph(), IsUnlikelySuccessor(), v8::internal::compiler::turboshaft::Block::kDeferredInSchedule, v8::internal::compiler::turboshaft::Block::LastPredecessor(), and v8::internal::compiler::turboshaft::Block::NeighboringPredecessor().
Referenced by v8::internal::compiler::turboshaft::SpecialRPOSchedulingPhase::Run().
Range() [1/3]
template<typename T >
v8::internal::compiler::turboshaft::Range (V< T > , typename ConstOrV< T >::constant_type , typename ConstOrV< T >::constant_type) -> Range< T >
Range() [2/3]
template<typename T >
v8::internal::compiler::turboshaft::Range (V< T > , V< T > , typename ConstOrV< T >::constant_type) -> Range< T >
Range() [3/3]
template<typename T >
v8::internal::compiler::turboshaft::Range (V< T > , V< T > , V< T >) -> Range< T >
Referenced by v8::internal::CharacterRange::AddUnicodeCaseEquivalents(), v8::internal::compiler::turboshaft::FloatType< Bits >::Any(), v8::internal::anonymous_namespace{js-temporal-objects.cc}::ExtractRustResult(), v8::internal::compiler::turboshaft::FloatType< Bits >::Intersect(), v8::internal::compiler::turboshaft::WordType< Bits >::Intersect(), v8::internal::OrderedHashTable< Derived, entrysize >::IterateEntries(), v8::internal::SmallOrderedHashTable< Derived >::IterateEntries(), v8::internal::HashTableBase::IterateEntries(), v8::internal::Map::IterateOwnDescriptors(), v8::internal::compiler::turboshaft::FloatType< Bits >::LeastUpperBound(), v8::internal::compiler::turboshaft::WordType< Bits >::LeastUpperBound(), v8::internal::compiler::turboshaft::TypeParser::ParseRange(), and v8::internal::compiler::turboshaft::FloatType< Bits >::Range().
RegisterRepresentationForArrayType()
constexpr RegisterRepresentation v8::internal::compiler::turboshaft::RegisterRepresentationForArrayType (ExternalArrayType array_type) [inline], [constexpr]
Definition at line 5862 of file operations.h.
                                  {
  switch (array_type) {
    case kExternalInt8Array:
    case kExternalUint8Array:
    case kExternalUint8ClampedArray:
    case kExternalInt16Array:
    case kExternalUint16Array:
    case kExternalInt32Array:
    case kExternalUint32Array:
    case kExternalFloat16Array:
      return RegisterRepresentation::Word32();
    case kExternalFloat32Array:
      return RegisterRepresentation::Float32();
    case kExternalFloat64Array:
      return RegisterRepresentation::Float64();
    case kExternalBigInt64Array:
    case kExternalBigUint64Array:
      return RegisterRepresentation::Word64();
  }
}
References v8::internal::compiler::turboshaft::RegisterRepresentation::Float32(), v8::internal::compiler::turboshaft::RegisterRepresentation::Float64(), v8::internal::kExternalBigInt64Array, v8::internal::kExternalBigUint64Array, v8::internal::kExternalFloat16Array, v8::internal::kExternalFloat32Array, v8::internal::kExternalFloat64Array, v8::internal::kExternalInt16Array, v8::internal::kExternalInt32Array, v8::internal::kExternalInt8Array, v8::internal::kExternalUint16Array, v8::internal::kExternalUint32Array, v8::internal::kExternalUint8Array, v8::internal::kExternalUint8ClampedArray, v8::internal::compiler::turboshaft::RegisterRepresentation::Word32(), and v8::internal::compiler::turboshaft::RegisterRepresentation::Word64().
Referenced by v8::internal::compiler::turboshaft::StoreTypedElementOp::inputs_rep(), v8::internal::compiler::turboshaft::StoreDataViewElementOp::inputs_rep(), v8::internal::compiler::turboshaft::DataViewLoweringReducer< Next >::LoadDataViewElement(), v8::internal::compiler::turboshaft::LoadTypedElementOp::outputs_rep(), v8::internal::compiler::turboshaft::LoadDataViewElementOp::outputs_rep(), and v8::internal::compiler::turboshaft::DataViewLoweringReducer< Next >::StoreDataViewElement().
RepIsCompatible()
bool v8::internal::compiler::turboshaft::RepIsCompatible (RegisterRepresentation actual, RegisterRepresentation expected_reg_repr, uint8_t in_memory_size)
Definition at line 729 of file wasm-load-elimination-reducer.h.
                                             {
  if (in_memory_size !=
      MemoryRepresentation::FromRegisterRepresentation(actual, true)
          .SizeInBytes()) {
    // The replacement was truncated when being stored or should be truncated
    // (or sign-extended) during the load. Since we don't have enough
    // truncations operators in Turboshaft (eg, we don't have Int32 to Int8
    // truncation), we just prevent load elimination in this case.
    // TODO(jkummerow): support eliminating repeated loads of the same i8/i16
    // field.
    return false;
  }
  return expected_reg_repr == actual;
}
References v8::internal::compiler::turboshaft::MemoryRepresentation::FromRegisterRepresentation().
Referenced by v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessLoad(), and v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessStructGet().
RepVector()
template<RegisterRepresentation::Enum... reps>
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::RepVector ()
Definition at line 1365 of file operations.h.
                                                     {
  static constexpr std::array<RegisterRepresentation, sizeof...(reps)>
      rep_array{RegisterRepresentation{reps}...};
  return base::VectorOf(rep_array);
}
References v8::base::VectorOf().
Referenced by v8::internal::compiler::turboshaft::Word32PairBinopOp::outputs_rep(), v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::outputs_rep(), v8::internal::compiler::turboshaft::OverflowCheckedUnaryOp::outputs_rep(), v8::internal::compiler::turboshaft::TryChangeOp::outputs_rep(), and v8::internal::compiler::turboshaft::AtomicWord32PairOp::outputs_rep().
RunDecompressionOptimization()
void v8::internal::compiler::turboshaft::RunDecompressionOptimization (Graph & graph, Zone * phase_zone)
Definition at line 211 of file decompression-optimization.cc.
                                                                  {
  DecompressionAnalyzer analyzer(graph, phase_zone);
  analyzer.Run();
  for (OpIndex op_idx : analyzer.candidates) {
    Operation& op = graph.Get(op_idx);
    if (analyzer.NeedsDecompression(op)) continue;
    switch (op.opcode) {
      case Opcode::kConstant: {
        auto& constant = op.Cast<ConstantOp>();
        if (constant.kind == ConstantOp::Kind::kHeapObject) {
          constant.kind = ConstantOp::Kind::kCompressedHeapObject;
        }
        break;
      }
      case Opcode::kPhi: {
        auto& phi = op.Cast<PhiOp>();
        if (phi.rep == RegisterRepresentation::Tagged()) {
          phi.rep = RegisterRepresentation::Compressed();
        }
        break;
      }
      case Opcode::kLoad: {
        auto& load = op.Cast<LoadOp>();
        if (load.loaded_rep.IsCompressibleTagged()) {
          DCHECK_EQ(load.result_rep,
                    any_of(RegisterRepresentation::Tagged(),
                           RegisterRepresentation::Compressed()));
          load.result_rep = RegisterRepresentation::Compressed();
        }
        break;
      }
      case Opcode::kTaggedBitcast: {
        auto& bitcast = op.Cast<TaggedBitcastOp>();
        if (bitcast.from == RegisterRepresentation::Tagged() &&
            (bitcast.to == RegisterRepresentation::WordPtr() ||
             bitcast.kind == TaggedBitcastOp::Kind::kSmi)) {
          bitcast.from = RegisterRepresentation::Compressed();
          bitcast.to = RegisterRepresentation::Word32();
        }
        break;
      }
      default:
        break;
    }
  }
}
References v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::compiler::turboshaft::RegisterRepresentation::Compressed(), DCHECK_EQ, v8::internal::compiler::turboshaft::TaggedBitcastOp::from, graph(), v8::internal::compiler::turboshaft::ConstantOp::kCompressedHeapObject, v8::internal::compiler::anonymous_namespace{gap-resolver.cc}::kConstant, v8::internal::compiler::turboshaft::ConstantOp::kHeapObject, v8::internal::compiler::turboshaft::ConstantOp::kind, v8::internal::compiler::turboshaft::TaggedBitcastOp::kSmi, v8::internal::compiler::turboshaft::Operation::opcode, v8::internal::compiler::turboshaft::PhiOp::rep, v8::internal::compiler::turboshaft::RegisterRepresentation::Tagged(), v8::internal::compiler::turboshaft::RegisterRepresentation::Word32(), and v8::internal::compiler::turboshaft::RegisterRepresentation::WordPtr().
Referenced by v8::internal::compiler::turboshaft::DecompressionOptimizationPhase::Run().
RunMaglevOptimizations()
void v8::internal::compiler::turboshaft::RunMaglevOptimizations (PipelineData * data, maglev::MaglevCompilationInfo * compilation_info, maglev::Graph * maglev_graph)
Definition at line 6264 of file turbolev-graph-builder.cc.
                                                       {
  // Non-eager inlining.
  if (v8_flags.turbolev_non_eager_inlining) {
    maglev::MaglevInliner inliner(maglev_graph);
    inliner.Run(data->info()->trace_turbo_graph());
    maglev::GraphProcessor<maglev::SweepIdentityNodes,
                           /* visit_identity_nodes */ true>
        sweep;
    sweep.ProcessGraph(maglev_graph);
  }
  // Phi untagging.
  {
    maglev::GraphProcessor<maglev::MaglevPhiRepresentationSelector> processor(
        maglev_graph);
    processor.ProcessGraph(maglev_graph);
  }
  if (V8_UNLIKELY(data->info()->trace_turbo_graph())) {
    PrintMaglevGraph(*data, maglev_graph, "After phi untagging");
  }
  // Escape analysis.
  {
    maglev::GraphMultiProcessor<maglev::AnyUseMarkingProcessor> processor;
    processor.ProcessGraph(maglev_graph);
  }
#ifdef DEBUG
  maglev::GraphProcessor<maglev::MaglevGraphVerifier> verifier(
      compilation_info);
  verifier.ProcessGraph(maglev_graph);
#endif
  // Dead nodes elimination (which, amongst other things, cleans up the left
  // overs of escape analysis).
  {
    maglev::GraphMultiProcessor<maglev::DeadNodeSweepingProcessor> processor;
    processor.ProcessGraph(maglev_graph);
  }
  if (V8_UNLIKELY(data->info()->trace_turbo_graph())) {
    PrintMaglevGraph(*data, maglev_graph,
References v8::internal::compiler::turboshaft::PipelineData::info(), PrintMaglevGraph(), v8::internal::maglev::GraphProcessor< NodeProcessor, visit_identity_nodes >::ProcessGraph(), v8::internal::maglev::MaglevInliner::Run(), v8::internal::v8_flags, and V8_UNLIKELY.
Sequence() [1/3]
template<typename T >
v8::internal::compiler::turboshaft::Sequence (V< T >) -> Sequence< T >
Sequence() [2/3]
template<typename T >
v8::internal::compiler::turboshaft::Sequence (V< T > , typename ConstOrV< T >::constant_type) -> Sequence< T >
Sequence() [3/3]
template<typename T >
v8::internal::compiler::turboshaft::Sequence (V< T > , V< T >) -> Sequence< T >
Referenced by v8::internal::StringBuiltinsReducer< Next >::CopyStringCharacters().
ShouldSkipOperation()
V8_EXPORT_PRIVATE bool v8::internal::compiler::turboshaft::ShouldSkipOperation (const Operation & op) [inline]
Definition at line 9496 of file operations.h.
                                                                          {
  if (op.Is<DeadOp>()) return true;
  return op.saturated_use_count.IsZero() && !op.IsRequiredWhenUnused();
}
References v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::compiler::turboshaft::Operation::IsRequiredWhenUnused(), v8::internal::compiler::turboshaft::SaturatedUint8::IsZero(), and v8::internal::compiler::turboshaft::Operation::saturated_use_count.
Referenced by v8::internal::compiler::turboshaft::PretenuringPropagationAnalyzer::BuildStoreInputGraph(), v8::internal::compiler::turboshaft::LateEscapeAnalysisAnalyzer::CollectUsesAndAllocations(), v8::internal::compiler::turboshaft::LateEscapeAnalysisAnalyzer::EscapesThroughUse(), v8::internal::compiler::turboshaft::LateEscapeAnalysisAnalyzer::FindRemovableAllocations(), v8::internal::compiler::InstructionSelector::IsReallyUsed(), v8::internal::compiler::InstructionSelector::IsUsed(), v8::internal::compiler::turboshaft::MemoryAnalyzer::Process(), v8::internal::compiler::turboshaft::WasmShuffleAnalyzer::Process(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessBlock(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessBlock(), v8::internal::compiler::turboshaft::MemoryAnalyzer::ProcessBlockTerminator(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitBlockBody(), and v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitOpNoMappingUpdate().
ShouldSkipOptimizationStep()
V8_EXPORT_PRIVATE bool v8::internal::compiler::turboshaft::ShouldSkipOptimizationStep () [inline]
Definition at line 84 of file utils.h.
{ return false; }
Referenced by v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::AnyConvertExtern(), v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::ArrayLength(), v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::AssertNotNull(), v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::Bind(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::BitcastWord32PairToFloat64(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Branch(), v8::internal::compiler::turboshaft::DuplicationOptimizationReducer< Next >::Branch(), v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::Branch(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Change(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Comparison(), v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::DeoptimizeIf(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::DeoptimizeIf(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::DeoptimizeIf(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::FloatBinop(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::FloatUnary(), v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::Goto(), v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::Goto(), v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::Goto(), v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::IsNull(), v8::internal::compiler::InstructionSelector::IsReallyUsed(), v8::internal::compiler::InstructionSelector::IsUsed(), v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::JSStackCheck(), v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::JSStackCheck(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Load(), v8::internal::compiler::turboshaft::LateEscapeAnalysisAnalyzer::MarkToRemove(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::OverflowCheckedBinop(), v8::internal::compiler::turboshaft::MemoryAnalyzer::ProcessAllocation(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessBlock(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessBlock(), v8::internal::compiler::turboshaft::TypedOptimizationsReducer< Next >::ReduceInputGraphBranch(), v8::internal::compiler::turboshaft::IfElseCascadeToSwitchReducer< Next >::ReduceInputGraphBranch(), v8::internal::compiler::turboshaft::TypedOptimizationsReducer< Next >::ReduceInputGraphOperation(), v8::internal::compiler::turboshaft::DuplicationOptimizationReducer< Next >::Select(), v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::Select(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Select(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Shift(), v8::internal::compiler::turboshaft::WasmShuffleReducer< Next >::Simd128Shuffle(), v8::internal::compiler::turboshaft::MemoryAnalyzer::SkipWriteBarrier(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Store(), v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::Store(), v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::StructGet(), v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::StructSet(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Switch(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TaggedBitcast(), v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::WasmTypeCast(), v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::WasmTypeCheck(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordBinop(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordUnary().
SuccessorBlocks() [1/2]
V8_EXPORT_PRIVATE base::SmallVector< Block *, 4 > v8::internal::compiler::turboshaft::SuccessorBlocks (const Block & block, const Graph & graph)
Definition at line 2059 of file operations.cc.
                                                                 {
  return SuccessorBlocks(block.LastOperation(graph));
}
References graph(), and v8::internal::compiler::turboshaft::Block::LastOperation().
Referenced by v8::internal::compiler::turboshaft::MaybeRedundantStoresTable::BeginBlock(), v8::internal::compiler::turboshaft::TurboshaftSpecialRPONumberer::ComputeLoopInfo(), v8::internal::compiler::turboshaft::TurboshaftSpecialRPONumberer::ComputeSpecialRPO(), v8::internal::compiler::turboshaft::Block::EndsWithBranchingOp(), v8::internal::compiler::InstructionBlockFor(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessBlock(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessBlock(), v8::internal::compiler::turboshaft::DeadCodeAnalysis::ProcessBlock(), v8::internal::compiler::turboshaft::MemoryAnalyzer::ProcessBlockTerminator(), and v8::internal::compiler::InstructionSelector::VisitControl().
SuccessorBlocks() [2/2]
base::SmallVector<Block*, 4> v8::internal::compiler::turboshaft::SuccessorBlocks (const Operation & op) [inline]
Definition at line 4493 of file operations.h.
                                                                       {
  switch (op.opcode) {
    case Opcode::kCheckException: {
      auto& casted = op.Cast<CheckExceptionOp>();
      return {casted.didnt_throw_block, casted.catch_block};
    }
    case Opcode::kGoto: {
      auto& casted = op.Cast<GotoOp>();
      return {casted.destination};
    }
    case Opcode::kBranch: {
      auto& casted = op.Cast<BranchOp>();
      return {casted.if_true, casted.if_false};
    }
    case Opcode::kReturn:
    case Opcode::kTailCall:
    case Opcode::kDeoptimize:
    case Opcode::kUnreachable:
      return base::SmallVector<Block*, 4>{};
    case Opcode::kSwitch: {
      auto& casted = op.Cast<SwitchOp>();
      base::SmallVector<Block*, 4> result;
      for (const SwitchOp::Case& c : casted.cases) {
        result.push_back(c.destination);
      }
      result.push_back(casted.default_case);
      return result;
    }
#define NON_TERMINATOR_CASE(op) case Opcode::k##op:
      TURBOSHAFT_OPERATION_LIST_NOT_BLOCK_TERMINATOR(NON_TERMINATOR_CASE)
      UNREACHABLE();
#undef NON_TERMINATOR_CASE
  }
}
References v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::compiler::turboshaft::GotoOp::destination, v8::internal::compiler::turboshaft::SwitchOp::Case::destination, v8::internal::compiler::turboshaft::CheckExceptionOp::didnt_throw_block, v8::internal::compiler::turboshaft::BranchOp::if_true, kBranch, v8::internal::wasm::kSwitch, v8::internal::wasm::kTailCall, v8::internal::wasm::kUnreachable, NON_TERMINATOR_CASE, v8::internal::compiler::turboshaft::Operation::opcode, v8::base::internal::result, TURBOSHAFT_OPERATION_LIST_NOT_BLOCK_TERMINATOR, and v8::internal::UNREACHABLE().
TooManyArgumentsForCall()
constexpr bool v8::internal::compiler::turboshaft::TooManyArgumentsForCall (size_t arguments_count) [constexpr]
Definition at line 425 of file turbolev-graph-builder.cc.
                                                               {
  constexpr int kCalleeCount = 1;
  constexpr int kFrameStateCount = 1;
  return (arguments_count + kCalleeCount + kFrameStateCount) >
         std::numeric_limits<decltype(Operation::input_count)>::max();
}
References v8::internal::compiler::turboshaft::Operation::input_count.
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::GenerateBuiltinCall().
TryGetBuiltin()
std::optional<Builtin> v8::internal::compiler::turboshaft::TryGetBuiltin (V< Any > node, Graph & graph)
Definition at line 47 of file csa-effects-computation.cc.
                                                              {
  if (const ConstantOp* target_obj_cst =
          graph.Get(node).TryCast<Opmask::kHeapConstant>()) {
    IndirectHandle<HeapObject> target_obj = target_obj_cst->handle();
    if (IsCode(*target_obj)) {
      IndirectHandle<Code> target_code = Cast<Code>(target_obj);
      if (target_code->is_builtin()) {
        return target_code->builtin_id();
      }
    }
  }
  return {};
}
References graph().
Referenced by AnalyzeCall().
TryGetBuiltinId()
std::optional< Builtin > v8::internal::compiler::turboshaft::TryGetBuiltinId (const ConstantOp * target, JSHeapBroker * broker)
Definition at line 47 of file operations.cc.
                                                             {
  if (!target) return std::nullopt;
  if (target->kind != ConstantOp::Kind::kHeapObject) return std::nullopt;
  // TODO(nicohartmann@): For builtin compilation we don't have a broker. We
  // could try to access the heap directly instead.
  if (broker == nullptr) return std::nullopt;
  UnparkedScopeIfNeeded scope(broker);
  AllowHandleDereference allow_handle_dereference;
  HeapObjectRef ref = MakeRef(broker, target->handle());
  if (ref.IsCode()) {
    CodeRef code = ref.AsCode();
    if (code.object()->is_builtin()) {
      return code.object()->builtin_id();
    }
  }
  return std::nullopt;
}
References broker(), code, v8::internal::compiler::turboshaft::ConstantOp::handle(), v8::internal::compiler::turboshaft::ConstantOp::kHeapObject, v8::internal::compiler::turboshaft::ConstantOp::kind, and v8::internal::compiler::MakeRef().
Referenced by v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessCall(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessCall(), and v8::internal::compiler::turboshaft::CallOp::Validate().
TryMatchConditionalCompareChainBranch()
static bool v8::internal::compiler::turboshaft::TryMatchConditionalCompareChainBranch (InstructionSelector * selector, Zone * zone, OpIndex node, FlagsContinuation * cont) [static]
Definition at line 1823 of file instruction-selector-arm64.cc.
                                                                           {
  if (!cont->IsBranch()) return false;
  DCHECK(cont->condition() == kNotEqual || cont->condition() == kEqual);
  CompareSequence sequence;
  auto final_cond =
      TryMatchConditionalCompareChainShared(selector, zone, node, &sequence);
  if (final_cond.has_value()) {
    FlagsCondition condition = cont->condition() == kNotEqual
                                   ? final_cond.value()
                                   : NegateFlagsCondition(final_cond.value());
    FlagsContinuation new_cont = FlagsContinuation::ForConditionalBranch(
        sequence.ccmps(), sequence.num_ccmps(), condition, cont->true_block(),
        cont->false_block());
    ImmediateMode imm_mode =
        sequence.IsFloatCmp() ? kNoImmediate : kArithmeticImm;
    VisitCompareChain(selector, sequence.left(), sequence.right(),
                      selector->Get(sequence.cmp()).Cast<ComparisonOp>().rep,
                      sequence.opcode(), imm_mode, &new_cont);
    return true;
  }
  return false;
}
References v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::compiler::turboshaft::CompareSequence::ccmps(), v8::internal::compiler::turboshaft::CompareSequence::cmp(), v8::internal::compiler::FlagsContinuation::condition(), v8::internal::DCHECK(), v8::internal::compiler::FlagsContinuation::false_block(), v8::internal::compiler::FlagsContinuation::ForConditionalBranch(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::FlagsContinuation::IsBranch(), v8::internal::compiler::turboshaft::CompareSequence::IsFloatCmp(), v8::internal::compiler::kArithmeticImm, v8::internal::kEqual, v8::internal::compiler::kNoImmediate, v8::internal::compiler::kNotEqual, v8::internal::compiler::turboshaft::CompareSequence::left(), v8::internal::compiler::NegateFlagsCondition(), v8::internal::compiler::turboshaft::CompareSequence::num_ccmps(), v8::internal::compiler::turboshaft::CompareSequence::opcode(), v8::internal::compiler::turboshaft::ComparisonOp::rep, v8::internal::compiler::turboshaft::CompareSequence::right(), v8::internal::compiler::FlagsContinuation::true_block(), TryMatchConditionalCompareChainShared(), and VisitCompareChain().
TryMatchConditionalCompareChainSet()
static bool v8::internal::compiler::turboshaft::TryMatchConditionalCompareChainSet (InstructionSelector * selector, Zone * zone, OpIndex node) [static]
Definition at line 1851 of file instruction-selector-arm64.cc.
                                                                         {
  // Create the cmp + ccmp ... sequence.
  CompareSequence sequence;
  auto final_cond =
      TryMatchConditionalCompareChainShared(selector, zone, node, &sequence);
  if (final_cond.has_value()) {
    // The continuation performs the conditional compare and cset.
    FlagsContinuation cont = FlagsContinuation::ForConditionalSet(
        sequence.ccmps(), sequence.num_ccmps(), final_cond.value(), node);
    ImmediateMode imm_mode =
        sequence.IsFloatCmp() ? kNoImmediate : kArithmeticImm;
    VisitCompareChain(selector, sequence.left(), sequence.right(),
                      selector->Get(sequence.cmp()).Cast<ComparisonOp>().rep,
                      sequence.opcode(), imm_mode, &cont);
    return true;
  }
  return false;
}
References v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::compiler::turboshaft::CompareSequence::ccmps(), v8::internal::compiler::turboshaft::CompareSequence::cmp(), v8::internal::compiler::FlagsContinuation::ForConditionalSet(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::CompareSequence::IsFloatCmp(), v8::internal::compiler::kArithmeticImm, v8::internal::compiler::kNoImmediate, v8::internal::compiler::turboshaft::CompareSequence::left(), v8::internal::compiler::turboshaft::CompareSequence::num_ccmps(), v8::internal::compiler::turboshaft::CompareSequence::opcode(), v8::internal::compiler::turboshaft::ComparisonOp::rep, v8::internal::compiler::turboshaft::CompareSequence::right(), TryMatchConditionalCompareChainShared(), and VisitCompareChain().
Referenced by v8::internal::compiler::VisitLogical().
TryMatchConditionalCompareChainShared()
static std::optional<FlagsCondition> v8::internal::compiler::turboshaft::TryMatchConditionalCompareChainShared (InstructionSelector * selector, Zone * zone, OpIndex node, CompareSequence * sequence) [static]
Definition at line 1735 of file instruction-selector-arm64.cc.
                               {
  // Instead of:
  // cmp x0, y0
  // cset cc0
  // cmp x1, y1
  // cset cc1
  // and/orr
  // Try to merge logical combinations of flags into:
  // cmp x0, y0
  // ccmp x1, y1 ..
  // cset ..
  // So, for AND:
  // (cset cc1 (ccmp x1 y1 !cc1 cc0 (cmp x0, y0)))
  // and for ORR:
  // (cset cc1 (ccmp x1 y1 cc1 !cc0 (cmp x0, y0))
  // Look for a potential chain.
  ZoneVector<CompareChainNode*> logic_nodes(zone);
  auto root =
      FindCompareChain(OpIndex::Invalid(), node, selector, zone, logic_nodes);
  if (!root.has_value()) return std::nullopt;
  if (logic_nodes.size() > FlagsContinuation::kMaxCompareChainSize) {
    return std::nullopt;
  }
  if (!logic_nodes.front()->IsLegalFirstCombine()) {
    return std::nullopt;
  }
  for (auto* logic_node : logic_nodes) {
    CombineFlagSettingOps(logic_node, selector, sequence);
  }
  DCHECK_LE(sequence->num_ccmps(), FlagsContinuation::kMaxCompareChainSize);
  return logic_nodes.back()->user_condition();
}
References v8::internal::ZoneVector< T >::back(), CombineFlagSettingOps(), DCHECK_LE, FindCompareChain(), v8::internal::ZoneVector< T >::front(), v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::compiler::FlagsContinuation::kMaxCompareChainSize, v8::internal::compiler::turboshaft::CompareSequence::num_ccmps(), and v8::internal::ZoneVector< T >::size().
Referenced by TryMatchConditionalCompareChainBranch(), and TryMatchConditionalCompareChainSet().
UnwrapAllocate()
const AllocateOp* v8::internal::compiler::turboshaft::UnwrapAllocate (const Graph * graph, const Operation * op) [inline]
Definition at line 63 of file memory-optimization-reducer.h.
                                                             {
  while (true) {
    if (const AllocateOp* allocate = op->TryCast<AllocateOp>()) {
      return allocate;
    } else if (const TaggedBitcastOp* bitcast =
                   op->TryCast<TaggedBitcastOp>()) {
      op = &graph->Get(bitcast->input());
    } else if (const WordBinopOp* binop = op->TryCast<WordBinopOp>();
               binop && binop->kind == any_of(WordBinopOp::Kind::kAdd,
                                              WordBinopOp::Kind::kSub)) {
      op = &graph->Get(binop->left());
    } else {
      return nullptr;
    }
  }
}
References graph(), v8::internal::compiler::turboshaft::WordBinopOp::kAdd, v8::internal::compiler::turboshaft::WordBinopOp::kind, v8::internal::compiler::turboshaft::WordBinopOp::kSub, and v8::internal::compiler::turboshaft::Operation::TryCast().
Referenced by v8::internal::compiler::turboshaft::MemoryAnalyzer::IsPartOfLastAllocation().
value_or_invalid()
r l v8::internal::compiler::turboshaft::value_or_invalid ()
ValueNeedsWriteBarrier()
bool v8::internal::compiler::turboshaft::ValueNeedsWriteBarrier (const Graph * graph, const Operation & value, Isolate * isolate) [inline]
Definition at line 34 of file memory-optimization-reducer.h.
                                                     {
  if (value.Is<Opmask::kBitcastWordPtrToSmi>()) {
    return false;
  } else if (const ConstantOp* constant = value.TryCast<ConstantOp>()) {
    if (constant->kind == ConstantOp::Kind::kHeapObject) {
      RootIndex root_index;
      if (isolate->roots_table().IsRootHandle(constant->handle(),
                                              &root_index) &&
          RootsTable::IsImmortalImmovable(root_index)) {
        return false;
      }
    } else if (constant->kind == ConstantOp::Kind::kSmi) {
      return false;
    }
  } else if (const PhiOp* phi = value.TryCast<PhiOp>()) {
    if (phi->rep == RegisterRepresentation::Tagged()) {
      return base::any_of(phi->inputs(), [graph, isolate](OpIndex input) {
        const Operation& input_op = graph->Get(input);
        // If we have a Phi as the Phi's input, we give up to avoid infinite
        // recursion.
        if (input_op.Is<PhiOp>()) return true;
        return ValueNeedsWriteBarrier(graph, input_op, isolate);
      });
    }
  }
  return true;
}
References v8::base::any_of(), graph(), v8::internal::RootsTable::IsImmortalImmovable(), v8::internal::RootsTable::IsRootHandle(), v8::internal::compiler::turboshaft::ConstantOp::kHeapObject, v8::internal::compiler::turboshaft::ConstantOp::kSmi, v8::internal::Isolate::roots_table(), v8::internal::compiler::turboshaft::RegisterRepresentation::Tagged(), and v8::internal::value.
Referenced by v8::internal::compiler::turboshaft::MemoryAnalyzer::SkipWriteBarrier().
VectorForRep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::VectorForRep (RegisterRepresentation rep) [inline]
Definition at line 5884 of file operations.h.
                                {
  static constexpr std::array<RegisterRepresentation, 6> table{
      RegisterRepresentation::Word32(), RegisterRepresentation::Word64(),
      RegisterRepresentation::Float32(), RegisterRepresentation::Float64(),
      RegisterRepresentation::Tagged(), RegisterRepresentation::Compressed()};
  return base::VectorOf(&table[static_cast<size_t>(rep.value())], 1);
}
References v8::internal::compiler::turboshaft::RegisterRepresentation::Compressed(), v8::internal::compiler::turboshaft::RegisterRepresentation::Float32(), v8::internal::compiler::turboshaft::RegisterRepresentation::Float64(), v8::internal::compiler::turboshaft::RegisterRepresentation::Tagged(), v8::internal::compiler::turboshaft::RegisterRepresentation::value(), v8::base::VectorOf(), v8::internal::compiler::turboshaft::RegisterRepresentation::Word32(), and v8::internal::compiler::turboshaft::RegisterRepresentation::Word64().
Referenced by v8::internal::compiler::turboshaft::LoadTypedElementOp::outputs_rep(), and v8::internal::compiler::turboshaft::LoadDataViewElementOp::outputs_rep().
VisitCompareChain()
static void v8::internal::compiler::turboshaft::VisitCompareChain (InstructionSelector * selector, OpIndex left_node, OpIndex right_node, RegisterRepresentation rep, InstructionCode opcode, ImmediateMode operand_mode, FlagsContinuation * cont) [static]
Definition at line 1773 of file instruction-selector-arm64.cc.
                                                       {
  DCHECK(cont->IsConditionalSet() || cont->IsConditionalBranch());
  Arm64OperandGenerator g(selector);
  constexpr uint32_t kMaxFlagSetInputs = 2;
  constexpr uint32_t kMaxCcmpOperands =
      FlagsContinuation::kMaxCompareChainSize * kNumCcmpOperands;
  constexpr uint32_t kExtraCcmpInputs = 2;
  constexpr uint32_t kMaxInputs =
      kMaxFlagSetInputs + kMaxCcmpOperands + kExtraCcmpInputs;
  InstructionOperand inputs[kMaxInputs];
  size_t input_count = 0;
  if (g.CanBeImmediate(right_node, operand_mode)) {
    inputs[input_count++] = g.UseRegister(left_node);
    inputs[input_count++] = g.UseImmediate(right_node);
  } else {
    inputs[input_count++] = g.UseRegisterOrImmediateZero(left_node);
    inputs[input_count++] = g.UseRegister(right_node);
  }
  auto& compares = cont->compares();
  for (unsigned i = 0; i < cont->num_conditional_compares(); ++i) {
    auto compare = compares[i];
    inputs[input_count + kCcmpOffsetOfOpcode] = g.TempImmediate(compare.code);
    inputs[input_count + kCcmpOffsetOfLhs] = g.UseRegisterAtEnd(compare.lhs);
    if ((compare.code == kArm64Cmp32 || compare.code == kArm64Cmp) &&
        g.CanBeImmediate(compare.rhs, kConditionalCompareImm)) {
      inputs[input_count + kCcmpOffsetOfRhs] = g.UseImmediate(compare.rhs);
    } else {
      inputs[input_count + kCcmpOffsetOfRhs] = g.UseRegisterAtEnd(compare.rhs);
    }
    inputs[input_count + kCcmpOffsetOfDefaultFlags] =
        g.TempImmediate(compare.default_flags);
    inputs[input_count + kCcmpOffsetOfCompareCondition] =
        g.TempImmediate(compare.compare_condition);
    input_count += kNumCcmpOperands;
  }
  inputs[input_count++] = g.TempImmediate(cont->final_condition());
  inputs[input_count++] =
      g.TempImmediate(static_cast<int32_t>(cont->num_conditional_compares()));
  DCHECK_GE(arraysize(inputs), input_count);
  selector->EmitWithContinuation(opcode, 0, nullptr, input_count, inputs, cont);
}
References arraysize, v8::internal::compiler::Arm64OperandGenerator::CanBeImmediate(), v8::internal::compiler::FlagsContinuation::compares(), v8::internal::DCHECK(), DCHECK_GE, v8::internal::compiler::InstructionSelector::EmitWithContinuation(), v8::internal::compiler::FlagsContinuation::final_condition(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::FlagsContinuation::IsConditionalBranch(), v8::internal::compiler::FlagsContinuation::IsConditionalSet(), v8::internal::compiler::kCcmpOffsetOfCompareCondition, v8::internal::compiler::kCcmpOffsetOfDefaultFlags, v8::internal::compiler::kCcmpOffsetOfLhs, v8::internal::compiler::kCcmpOffsetOfOpcode, v8::internal::compiler::kCcmpOffsetOfRhs, v8::internal::compiler::kConditionalCompareImm, v8::internal::compiler::FlagsContinuation::kMaxCompareChainSize, v8::internal::compiler::kNumCcmpOperands, v8::internal::compiler::FlagsContinuation::num_conditional_compares(), v8::internal::compiler::OperandGenerator::TempImmediate(), v8::internal::compiler::OperandGenerator::UseImmediate(), v8::internal::compiler::OperandGenerator::UseRegister(), v8::internal::compiler::OperandGenerator::UseRegisterAtEnd(), and v8::internal::compiler::Arm64OperandGenerator::UseRegisterOrImmediateZero().
Referenced by TryMatchConditionalCompareChainBranch(), and TryMatchConditionalCompareChainSet().
VisitOperation()
template<typename F >
auto v8::internal::compiler::turboshaft::VisitOperation (const Operation & op, F && f)
Definition at line 9601 of file operations.h.
                                                {
  switch (op.opcode) {
#define CASE(name) \
  case Opcode::k##name: \
    return f(op.Cast<name##Op>());
    TURBOSHAFT_OPERATION_LIST(CASE)
#undef CASE
  }
}
References CASE, v8::internal::compiler::turboshaft::Operation::opcode, and TURBOSHAFT_OPERATION_LIST.
Referenced by v8::internal::compiler::anonymous_namespace{pipeline.cc}::HashGraphForPGO().
Zip()
template<typename... Iterables>
v8::internal::compiler::turboshaft::Zip (Iterables... iterables) -> Zip< Iterables... >
Referenced by v8::internal::StringBuiltinsReducer< Next >::CopyStringCharacters().
Variable Documentation
CompilerPhase
template<typename Phase >
concept v8::internal::compiler::turboshaft::CompilerPhase = TurboshaftPhase<Phase> || TurbofanPhase<Phase>
Definition at line 84 of file phase.h.
const_or_v_exists_v
template<typename T >
constexpr bool v8::internal::compiler::turboshaft::const_or_v_exists_v = detail::ConstOrVTypeHelper<T>::exists [constexpr]
Definition at line 800 of file index.h.
ForeachIterable
template<typename It , typename A >
concept v8::internal::compiler::turboshaft::ForeachIterable
Initial value:
= requires(It iterator, A& assembler) {
  { iterator.Begin(assembler) } -> std::same_as<typename It::iterator_type>;
  {
    iterator.IsEnd(assembler, typename It::iterator_type{})
  } -> std::same_as<OptionalV<Word32>>;
  {
    iterator.Advance(assembler, typename It::iterator_type{})
  } -> std::same_as<typename It::iterator_type>;
  {
    iterator.Dereference(assembler, typename It::iterator_type{})
  } -> std::same_as<typename It::value_type>;
}
Definition at line 104 of file assembler.h.
IsTagged
template<typename T >
concept v8::internal::compiler::turboshaft::IsTagged
Initial value:
= !std::is_same_v<T, Any> &&
                   v_traits<Object>::implicitly_constructible_from<T>::value
Definition at line 563 of file index.h.
Referenced by v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::DebugFieldType::GetOriginalType(), v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::DebugFieldType::GetTypeString(), v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::DebugFieldType::GetValueType(), and v8::internal::compiler::CodeAssembler::Return().
IsUntagged
template<typename T >
concept v8::internal::compiler::turboshaft::IsUntagged
Initial value:
=
    !std::is_same_v<T, Any> &&
    v_traits<Untagged>::implicitly_constructible_from<T>::value
Definition at line 558 of file index.h.
kBuiltinCompilationZoneName
constexpr char v8::internal::compiler::turboshaft::kBuiltinCompilationZoneName[] [inline], [constexpr]
Initial value:
=
    "builtin-compilation-zone"
Definition at line 18 of file builtin-compiler.cc.
Referenced by BuildWithTurboshaftAssemblerImpl().
kCompilationZoneName
constexpr char v8::internal::compiler::turboshaft::kCompilationZoneName[] = `compilation-zone` [inline], [constexpr]
Definition at line 59 of file operations.h.
kNumberOfBlockTerminatorOpcodes
constexpr uint16_t v8::internal::compiler::turboshaft::kNumberOfBlockTerminatorOpcodes [constexpr]
Initial value:
=
    0 TURBOSHAFT_OPERATION_LIST_BLOCK_TERMINATOR(COUNT_OPCODES)
Definition at line 409 of file operations.h.
Referenced by IsBlockTerminator().
kNumberOfOpcodes
constexpr uint16_t v8::internal::compiler::turboshaft::kNumberOfOpcodes [constexpr]
Initial value:
=
    0 TURBOSHAFT_OPERATION_LIST(COUNT_OPCODES)
Definition at line 414 of file operations.h.
Referenced by v8::internal::compiler::turboshaft::Graph::Get(), and OpcodeName().
kOperationEffectsTable
constexpr std::optional<OpEffects> v8::internal::compiler::turboshaft::kOperationEffectsTable[kNumberOfOpcodes] [static], [constexpr]
Initial value:
= {
        TURBOSHAFT_OPERATION_LIST(OPERATION_EFFECTS_CASE)}
Definition at line 9354 of file operations.h.
kOperationSizeDividedBySizeofOpIndexTable
constexpr size_t v8::internal::compiler::turboshaft::kOperationSizeDividedBySizeofOpIndexTable[kNumberOfOpcodes] [constexpr]
Initial value:
= {
#define OPERATION_SIZE(Name)
}
Definition at line 9382 of file operations.h.
kOperationSizeTable
constexpr size_t v8::internal::compiler::turboshaft::kOperationSizeTable[kNumberOfOpcodes] [constexpr]
Initial value:
= {
#define OPERATION_SIZE(Name)
}
Definition at line 9377 of file operations.h.
kSlotsPerId
constexpr size_t v8::internal::compiler::turboshaft::kSlotsPerId = 2 [constexpr]
Definition at line 31 of file index.h.
Referenced by v8::internal::compiler::turboshaft::OperationBuffer::Grow(), v8::internal::compiler::turboshaft::OpIndex::hash(), v8::internal::compiler::turboshaft::OpIndex::id(), v8::internal::compiler::turboshaft::Graph::op_id_capacity(), v8::internal::compiler::turboshaft::Graph::op_id_count(), and v8::internal::compiler::turboshaft::OperationBuffer::OperationBuffer().
kTempZoneName
constexpr char v8::internal::compiler::turboshaft::kTempZoneName[] = `temp-zone` [inline], [constexpr]
Definition at line 40 of file pipelines.h.
Referenced by BuildWithTurboshaftAssemblerImpl(), v8::internal::compiler::Pipeline::GenerateCodeForTurboshaftBuiltin(), and v8::internal::compiler::turboshaft::Pipeline::PrepareForInstructionSelection().
l
v8::internal::compiler::turboshaft::l
Definition at line 927 of file index.h.
Referenced by v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Add(), v8::internal::RegExpMacroAssemblerRISCV::AssertAboveStackLimitMinusSlack(), v8::internal::Assembler::b(), v8::internal::Assembler::bc_long(), v8::internal::Assembler::bc_short(), v8::internal::Assembler::beq(), v8::internal::Assembler::bge(), v8::internal::Assembler::bgt(), v8::internal::RegExpBytecodeGenerator::Bind(), v8::internal::Assembler::ble(), v8::internal::Assembler::blt(), v8::internal::Assembler::bne(), v8::internal::Assembler::bordered(), v8::internal::anonymous_namespace{intl-objects.cc}::BuildLocaleMatcher(), v8::internal::Assembler::bunordered(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Divide(), v8::internal::Assembler::emit_vex2_byte1(), v8::internal::Assembler::emit_vex3_byte2(), v8::internal::Assembler::emit_vex_prefix(), v8::internal::wasm::liftoff::EmitAllTrue(), v8::internal::RegExpBytecodeGenerator::EmitOrLink(), v8::internal::AstRawString::Equal(), v8::internal::V8HeapExplorer::ExtractFixedArrayReferences(), v8::internal::anonymous_namespace{intl-objects.cc}::FastCompareFlatString(), v8::internal::anonymous_namespace{intl-objects.cc}::FastCompareStringFlatContent(), v8::internal::anonymous_namespace{js-duration-format.cc}::GetSeparator(), v8::internal::RegExpBytecodeGenerator::GoTo(), v8::internal::torque::Signature::HasSameTypesAs(), v8::internal::Assembler::ImmNEONHLM(), v8::internal::compiler::turboshaft::CompareSequence::InitialCompare(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::insert(), v8::internal::interpreter::BytecodeLabels::is_bound(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::IsZeroish(), v8::internal::Assembler::jmp(), v8::internal::torque::Grammar::MakeExtendedVector(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::MakeExtendedVectorIfAnnotation(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Max(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Min(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Modulus(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Multiply(), v8::internal::anonymous_namespace{js-display-names.cc}::LanguageNames::of(), v8::internal::compiler::operator<(), v8::internal::compiler::operator==(), v8::internal::wasm::MultiLineStringBuilder::PatchLabel(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Power(), v8::internal::Assembler::print(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::ProductSet(), v8::internal::RegExpBytecodeGenerator::PushBacktrack(), v8::internal::compiler::MachineOperatorReducer::ReduceWord32Shl(), v8::internal::compiler::MachineOperatorReducer::ReduceWord64Shl(), v8::internal::compiler::turboshaft::Typer::BranchRefinements::RefineTypes(), v8::internal::Isolate::ReleaseSharedPtrs(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Shift(), v8::internal::anonymous_namespace{liveedit-diff.cc}::MyersDiffer::ShortestEditForward(), v8::internal::anonymous_namespace{liveedit-diff.cc}::MyersDiffer::ShortestEditReverse(), v8::internal::ZoneList< T >::StableSort(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Subtract(), v8::internal::compiler::JSBinopReduction::SwapInputs(), v8::internal::wasm::MultiLineStringBuilder::ToDisassemblyCollector(), v8::internal::compiler::turboshaft::Typer::TypeWord32Add(), v8::internal::compiler::turboshaft::Typer::TypeWord32Comparison(), v8::internal::compiler::turboshaft::Typer::TypeWord32OverflowCheckedAdd(), v8::internal::compiler::turboshaft::Typer::TypeWord32Sub(), v8::internal::compiler::turboshaft::Typer::TypeWord64Add(), v8::internal::compiler::turboshaft::Typer::TypeWord64Sub(), and v8::internal::wasm::MultiLineStringBuilder::WriteTo().
nan_v
template<size_t Bits>
constexpr float_type<Bits> v8::internal::compiler::turboshaft::nan_v = detail::TypeForBits<Bits>::nan [constexpr]
Definition at line 161 of file types.h.
nullrep
constexpr nullrep_t v8::internal::compiler::turboshaft::nullrep [constexpr]
Definition at line 203 of file index.h.
Referenced by v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Projection().
operation_to_opcode_v
template<typename Op >
constexpr Opcode v8::internal::compiler::turboshaft::operation_to_opcode_v = operation_to_opcode<Op>::value [constexpr]
Definition at line 399 of file operations.h.
Referenced by v8::internal::compiler::anonymous_namespace{pipeline.cc}::HashGraphForPGO().
OpIndex
r v8::internal::compiler::turboshaft::OpIndex
Definition at line 929 of file index.h.
Referenced by v8::internal::compiler::turboshaft::OperationBuffer::Allocate(), v8::internal::compiler::turboshaft::OperationBuffer::BeginIndex(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin(), v8::internal::compiler::turboshaft::OperationBuffer::Index(), v8::internal::compiler::turboshaft::OperationBuffer::Next(), v8::internal::compiler::turboshaft::OperationBuffer::Previous(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::TryMatchBaseWithScaledIndexAndDisplacementForWordBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicCompareExchange(), v8::internal::compiler::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicExchange(), v8::internal::compiler::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitBinop(), v8::internal::compiler::VisitPairAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitStoreCommon(), and v8::internal::compiler::turboshaft::OperationBuffer::ReplaceScope::~ReplaceScope().
OptionalOpIndex
v8::internal::compiler::turboshaft::OptionalOpIndex
Definition at line 927 of file index.h.
TurbofanPhase
template<typename Phase >
concept v8::internal::compiler::turboshaft::TurbofanPhase = requires(Phase p) { p.kKind == PhaseKind::kTurbofan; }
Definition at line 81 of file phase.h.
TurboshaftPhase
template<typename Phase , typename... Args>
concept v8::internal::compiler::turboshaft::TurboshaftPhase
Initial value:
=
    HasProperRunMethod<Phase>::value &&
    requires(Phase p) { p.kKind == PhaseKind::kTurboshaft; }
Definition at line 76 of file phase.h.