v8::internal::parsing::anonymous_namespace{parsing.cc} Namespace Reference
Functions
void MaybeReportStatistics (ParseInfo *info, DirectHandle< Script > script, Isolate *isolate, Parser *parser, ReportStatisticsMode mode)
Function Documentation
MaybeReportStatistics()
void v8::internal::parsing::anonymous_namespace{parsing.cc}::MaybeReportStatistics (ParseInfo * info, DirectHandle< Script > script, Isolate * isolate, Parser * parser, ReportStatisticsMode mode)
Definition at line 25 of file parsing.cc.
                                                      {
  switch (mode) {
    case ReportStatisticsMode::kYes:
      parser->UpdateStatistics(isolate, script);
      break;
    case ReportStatisticsMode::kNo:
      break;
  }
}
References v8::internal::parsing::kNo, v8::internal::parsing::kYes, mode(), v8::internal::script, and v8::internal::Parser::UpdateStatistics().
Referenced by v8::internal::parsing::ParseFunction(), and v8::internal::parsing::ParseProgram().