v8::internal::anonymous_namespace{debug-coverage.cc} Namespace Reference
Classes
class CoverageBlockIterator
struct SharedFunctionInfoAndCount
Functions
int StartPosition (Tagged< SharedFunctionInfo > info)
bool CompareCoverageBlock (const CoverageBlock &a, const CoverageBlock &b)
void SortBlockData (std::vector< CoverageBlock > &v)
std::vector< CoverageBlock > GetSortedBlockData (Isolate *isolate, Tagged< SharedFunctionInfo > shared)
bool HaveSameSourceRange (const CoverageBlock &lhs, const CoverageBlock &rhs)
void MergeDuplicateRanges (CoverageFunction *function)
void RewritePositionSingletonsToRanges (CoverageFunction *function)
void MergeConsecutiveRanges (CoverageFunction *function)
void MergeNestedRanges (CoverageFunction *function)
void RewriteFunctionScopeCounter (CoverageFunction *function)
void FilterAliasedSingletons (CoverageFunction *function)
void FilterUncoveredRanges (CoverageFunction *function)
void FilterEmptyRanges (CoverageFunction *function)
void ClampToBinary (CoverageFunction *function)
void ResetAllBlockCounts (Isolate *isolate, Tagged< SharedFunctionInfo > shared)
bool IsBlockMode (debug::CoverageMode mode)
bool IsBinaryMode (debug::CoverageMode mode)
void CollectBlockCoverageInternal (Isolate *isolate, CoverageFunction *function, Tagged< SharedFunctionInfo > info, debug::CoverageMode mode)
void CollectBlockCoverage (Isolate *isolate, CoverageFunction *function, Tagged< SharedFunctionInfo > info, debug::CoverageMode mode)
void PrintBlockCoverage (const CoverageFunction *function, Tagged< SharedFunctionInfo > info, bool has_nonempty_source_range, bool function_is_relevant)
void CollectAndMaybeResetCounts (Isolate *isolate, SharedToCounterMap *counter_map, v8::debug::CoverageMode coverage_mode)
Function Documentation
ClampToBinary()
void v8::internal::anonymous_namespace{debug-coverage.cc}::ClampToBinary (CoverageFunction * function)
Definition at line 380 of file debug-coverage.cc.
                                               {
  CoverageBlockIterator iter(function);
  while (iter.Next()) {
    CoverageBlock& block = iter.GetBlock();
    if (block.count > 0) block.count = 1;
  }
}
References v8::internal::CoverageBlock::count, v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::GetBlock(), and v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::Next().
Referenced by CollectBlockCoverageInternal().
CollectAndMaybeResetCounts()
void v8::internal::anonymous_namespace{debug-coverage.cc}::CollectAndMaybeResetCounts (Isolate * isolate, SharedToCounterMap * counter_map, v8::debug::CoverageMode coverage_mode)
Definition at line 506 of file debug-coverage.cc.
                                                                   {
  const bool reset_count =
      coverage_mode != v8::debug::CoverageMode::kBestEffort;
  switch (isolate->code_coverage_mode()) {
    case v8::debug::CoverageMode::kBlockBinary:
    case v8::debug::CoverageMode::kBlockCount:
    case v8::debug::CoverageMode::kPreciseBinary:
    case v8::debug::CoverageMode::kPreciseCount: {
      // Feedback vectors are already listed to prevent losing them to GC.
      DCHECK(IsArrayList(
          *isolate->factory()->feedback_vectors_for_profiling_tools()));
      auto list = Cast<ArrayList>(
          isolate->factory()->feedback_vectors_for_profiling_tools());
      for (int i = 0; i < list->length(); i++) {
        Tagged<FeedbackVector> vector = Cast<FeedbackVector>(list->get(i));
        Tagged<SharedFunctionInfo> shared = vector->shared_function_info();
        DCHECK(shared->IsSubjectToDebugging());
        uint32_t count = static_cast<uint32_t>(vector->invocation_count());
        if (reset_count) vector->clear_invocation_count(kRelaxedStore);
        counter_map->Add(shared, count);
      }
      break;
    }
    case v8::debug::CoverageMode::kBestEffort: {
      DCHECK(!IsArrayList(
          *isolate->factory()->feedback_vectors_for_profiling_tools()));
      DCHECK_EQ(v8::debug::CoverageMode::kBestEffort, coverage_mode);
      AllowGarbageCollection allow_gc;
      HeapObjectIterator heap_iterator(isolate->heap());
      for (Tagged<HeapObject> current_obj = heap_iterator.Next();
           !current_obj.is_null(); current_obj = heap_iterator.Next()) {
        if (!IsJSFunction(current_obj)) continue;
        Tagged<JSFunction> func = Cast<JSFunction>(current_obj);
        Tagged<SharedFunctionInfo> shared = func->shared();
        if (!shared->IsSubjectToDebugging()) continue;
        if (!(func->has_feedback_vector() ||
              func->has_closure_feedback_cell_array())) {
          continue;
        }
        uint32_t count = 0;
        if (func->has_feedback_vector()) {
          count = static_cast<uint32_t>(
              func->feedback_vector()->invocation_count());
        } else if (func->shared()->HasBytecodeArray() &&
                   func->raw_feedback_cell()->interrupt_budget() <
                       TieringManager::InterruptBudgetFor(isolate, func, {})) {
          // We haven't allocated feedback vector, but executed the function
          // atleast once. We don't have precise invocation count here.
          count = 1;
        }
        counter_map->Add(shared, count);
      }
      // Also check functions on the stack to collect the count map. With lazy
      // feedback allocation we may miss counting functions if the feedback
      // vector wasn't allocated yet and the function's interrupt budget wasn't
      // updated (i.e. it didn't execute return / jump).
      for (JavaScriptStackFrameIterator it(isolate); !it.done(); it.Advance()) {
        Tagged<SharedFunctionInfo> shared = it.frame()->function()->shared();
        if (counter_map->Get(shared) != 0) continue;
        counter_map->Add(shared, 1);
      }
      break;
    }
  }
}
References v8::internal::SharedToCounterMap::Add(), v8::internal::Isolate::code_coverage_mode(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::JavaScriptStackFrameIterator::done(), v8::internal::Isolate::factory(), v8::internal::SharedToCounterMap::Get(), v8::internal::Isolate::heap(), v8::internal::TieringManager::InterruptBudgetFor(), v8::internal::Tagged< HeapObject >::is_null(), v8::debug::kBestEffort, v8::debug::kBlockBinary, v8::debug::kBlockCount, v8::debug::kPreciseBinary, v8::debug::kPreciseCount, v8::kRelaxedStore, and v8::internal::HeapObjectIterator::Next().
Referenced by v8::internal::Coverage::Collect().
CollectBlockCoverage()
void v8::internal::anonymous_namespace{debug-coverage.cc}::CollectBlockCoverage (Isolate * isolate, CoverageFunction * function, Tagged< SharedFunctionInfo > info, debug::CoverageMode mode)
Definition at line 478 of file debug-coverage.cc.
                                                  {
  CollectBlockCoverageInternal(isolate, function, info, mode);
  // Reset all counters on the DebugInfo to zero.
  ResetAllBlockCounts(isolate, info);
}
References CollectBlockCoverageInternal(), mode(), and ResetAllBlockCounts().
Referenced by v8::internal::Coverage::Collect().
CollectBlockCoverageInternal()
void v8::internal::anonymous_namespace{debug-coverage.cc}::CollectBlockCoverageInternal (Isolate * isolate, CoverageFunction * function, Tagged< SharedFunctionInfo > info, debug::CoverageMode mode)
Definition at line 420 of file debug-coverage.cc.
                                                          {
  DCHECK(IsBlockMode(mode));
  // Functions with empty source ranges are not interesting to report. This can
  // happen e.g. for internally-generated functions like class constructors.
  if (!function->HasNonEmptySourceRange()) return;
  function->has_block_coverage = true;
  function->blocks = GetSortedBlockData(isolate, info);
  // If in binary mode, only report counts of 0/1.
  if (mode == debug::CoverageMode::kBlockBinary) ClampToBinary(function);
  // To stay compatible with non-block coverage modes, the function-scope count
  // is expected to be in the CoverageFunction, not as part of its blocks.
  // This finds the function-scope counter, overwrites CoverageFunction::count,
  // and removes it from the block list.
  //
  // Important: Must be called before other transformation passes.
  RewriteFunctionScopeCounter(function);
  // Functions without blocks don't need to be processed further.
  if (!function->HasBlocks()) return;
  // Remove singleton ranges with the same start position as a full range and
  // throw away their counts.
  // Singleton ranges are only intended to split existing full ranges and should
  // never expand into a full range. Consider 'if (cond) { ... } else { ... }'
  // as a problematic example; if the then-block produces a continuation
  // singleton, it would incorrectly expand into the else range.
  // For more context, see https://crbug.com/v8/8237.
  FilterAliasedSingletons(function);
  // Rewrite all singletons (created e.g. by continuations and unconditional
  // control flow) to ranges.
  RewritePositionSingletonsToRanges(function);
  // Merge nested and consecutive ranges with identical counts.
  // Note that it's necessary to merge duplicate ranges prior to merging nested
  // changes in order to avoid invalid transformations. See crbug.com/827530.
  MergeConsecutiveRanges(function);
  SortBlockData(function->blocks);
  MergeDuplicateRanges(function);
  MergeNestedRanges(function);
  MergeConsecutiveRanges(function);
  // Filter out ranges with count == 0 unless the immediate parent range has
  // a count != 0.
  FilterUncoveredRanges(function);
  // Filter out ranges of zero length.
  FilterEmptyRanges(function);
}
References ClampToBinary(), v8::internal::DCHECK(), FilterAliasedSingletons(), FilterEmptyRanges(), FilterUncoveredRanges(), GetSortedBlockData(), IsBlockMode(), v8::debug::kBlockBinary, MergeConsecutiveRanges(), MergeDuplicateRanges(), MergeNestedRanges(), mode(), RewriteFunctionScopeCounter(), RewritePositionSingletonsToRanges(), and SortBlockData().
Referenced by CollectBlockCoverage().
CompareCoverageBlock()
bool v8::internal::anonymous_namespace{debug-coverage.cc}::CompareCoverageBlock (const CoverageBlock & a, const CoverageBlock & b)
Definition at line 64 of file debug-coverage.cc.
                                                                          {
  DCHECK_NE(kNoSourcePosition, a.start);
  DCHECK_NE(kNoSourcePosition, b.start);
  if (a.start == b.start) return a.end > b.end;
  return a.start < b.start;
}
References DCHECK_NE, v8::internal::CoverageBlock::end, v8::internal::kNoSourcePosition, and v8::internal::CoverageBlock::start.
Referenced by v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::CoverageBlockIterator(), SortBlockData(), and v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::~CoverageBlockIterator().
FilterAliasedSingletons()
void v8::internal::anonymous_namespace{debug-coverage.cc}::FilterAliasedSingletons (CoverageFunction * function)
Definition at line 337 of file debug-coverage.cc.
                                                         {
  CoverageBlockIterator iter(function);
  iter.Next(); // Advance once since we reference the previous block later.
  while (iter.Next()) {
    CoverageBlock& previous_block = iter.GetPreviousBlock();
    CoverageBlock& block = iter.GetBlock();
    bool is_singleton = block.end == kNoSourcePosition;
    bool aliases_start = block.start == previous_block.start;
    if (is_singleton && aliases_start) {
      // The previous block must have a full range since duplicate singletons
      // have already been merged.
      DCHECK_NE(previous_block.end, kNoSourcePosition);
      // Likewise, the next block must have another start position since
      // singletons are sorted to the end.
      DCHECK_IMPLIES(iter.HasNext(), iter.GetNextBlock().start != block.start);
      iter.DeleteBlock();
    }
  }
}
References DCHECK_IMPLIES, DCHECK_NE, v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::DeleteBlock(), v8::internal::CoverageBlock::end, v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::GetBlock(), v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::GetNextBlock(), v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::GetPreviousBlock(), v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::HasNext(), v8::internal::kNoSourcePosition, v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::Next(), and v8::internal::CoverageBlock::start.
Referenced by CollectBlockCoverageInternal().
FilterEmptyRanges()
void v8::internal::anonymous_namespace{debug-coverage.cc}::FilterEmptyRanges (CoverageFunction * function)
Definition at line 371 of file debug-coverage.cc.
                                                   {
  CoverageBlockIterator iter(function);
  while (iter.Next()) {
    CoverageBlock& block = iter.GetBlock();
    if (block.start == block.end) iter.DeleteBlock();
  }
}
References v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::DeleteBlock(), v8::internal::CoverageBlock::end, v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::GetBlock(), v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::Next(), and v8::internal::CoverageBlock::start.
Referenced by CollectBlockCoverageInternal().
FilterUncoveredRanges()
void v8::internal::anonymous_namespace{debug-coverage.cc}::FilterUncoveredRanges (CoverageFunction * function)
Definition at line 361 of file debug-coverage.cc.
                                                       {
  CoverageBlockIterator iter(function);
  while (iter.Next()) {
    CoverageBlock& block = iter.GetBlock();
    CoverageBlock& parent = iter.GetParent();
    if (block.count == 0 && parent.count == 0) iter.DeleteBlock();
  }
}
References v8::internal::CoverageBlock::count, v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::DeleteBlock(), v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::GetBlock(), v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::GetParent(), and v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::Next().
Referenced by CollectBlockCoverageInternal().
GetSortedBlockData()
std::vector<CoverageBlock> v8::internal::anonymous_namespace{debug-coverage.cc}::GetSortedBlockData (Isolate * isolate, Tagged< SharedFunctionInfo > shared)
Definition at line 76 of file debug-coverage.cc.
                                                         {
  DCHECK(shared->HasCoverageInfo(isolate));
  Tagged<CoverageInfo> coverage_info =
      Cast<CoverageInfo>(shared->GetDebugInfo(isolate)->coverage_info());
  std::vector<CoverageBlock> result;
  if (coverage_info->slot_count() == 0) return result;
  for (int i = 0; i < coverage_info->slot_count(); i++) {
    const int start_pos = coverage_info->slots_start_source_position(i);
    const int until_pos = coverage_info->slots_end_source_position(i);
    const int count = coverage_info->slots_block_count(i);
    DCHECK_NE(kNoSourcePosition, start_pos);
    result.emplace_back(start_pos, until_pos, count);
  }
  SortBlockData(result);
  return result;
}
References v8::internal::DCHECK(), DCHECK_NE, v8::internal::kNoSourcePosition, v8::base::internal::result, and SortBlockData().
Referenced by CollectBlockCoverageInternal().
HaveSameSourceRange()
bool v8::internal::anonymous_namespace{debug-coverage.cc}::HaveSameSourceRange (const CoverageBlock & lhs, const CoverageBlock & rhs)
Definition at line 230 of file debug-coverage.cc.
                                                                             {
  return lhs.start == rhs.start && lhs.end == rhs.end;
}
References v8::internal::CoverageBlock::end, and v8::internal::CoverageBlock::start.
Referenced by MergeDuplicateRanges().
IsBinaryMode()
bool v8::internal::anonymous_namespace{debug-coverage.cc}::IsBinaryMode (debug::CoverageMode mode)
Definition at line 410 of file debug-coverage.cc.
                                          {
  switch (mode) {
    case debug::CoverageMode::kBlockBinary:
    case debug::CoverageMode::kPreciseBinary:
      return true;
    default:
      return false;
  }
}
References v8::debug::kBlockBinary, v8::debug::kPreciseBinary, and mode().
Referenced by v8::internal::Coverage::SelectMode().
IsBlockMode()
bool v8::internal::anonymous_namespace{debug-coverage.cc}::IsBlockMode (debug::CoverageMode mode)
Definition at line 400 of file debug-coverage.cc.
                                         {
  switch (mode) {
    case debug::CoverageMode::kBlockBinary:
    case debug::CoverageMode::kBlockCount:
      return true;
    default:
      return false;
  }
}
References v8::debug::kBlockBinary, v8::debug::kBlockCount, and mode().
Referenced by v8::internal::Coverage::Collect(), and CollectBlockCoverageInternal().
MergeConsecutiveRanges()
void v8::internal::anonymous_namespace{debug-coverage.cc}::MergeConsecutiveRanges (CoverageFunction * function)
Definition at line 280 of file debug-coverage.cc.
                                                        {
  CoverageBlockIterator iter(function);
  while (iter.Next()) {
    CoverageBlock& block = iter.GetBlock();
    if (iter.HasSiblingOrChild()) {
      CoverageBlock& sibling = iter.GetSiblingOrChild();
      if (sibling.start == block.end && sibling.count == block.count) {
        // Best-effort: this pass may miss mergeable siblings in the presence of
        // child blocks.
        sibling.start = block.start;
        iter.DeleteBlock();
      }
    }
  }
}
References v8::internal::CoverageBlock::count, v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::DeleteBlock(), v8::internal::CoverageBlock::end, v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::GetBlock(), v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::GetSiblingOrChild(), v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::HasSiblingOrChild(), v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::Next(), and v8::internal::CoverageBlock::start.
Referenced by CollectBlockCoverageInternal().
MergeDuplicateRanges()
void v8::internal::anonymous_namespace{debug-coverage.cc}::MergeDuplicateRanges (CoverageFunction * function)
Definition at line 234 of file debug-coverage.cc.
                                                      {
  CoverageBlockIterator iter(function);
  while (iter.Next() && iter.HasNext()) {
    CoverageBlock& block = iter.GetBlock();
    CoverageBlock& next_block = iter.GetNextBlock();
    if (!HaveSameSourceRange(block, next_block)) continue;
    DCHECK_NE(kNoSourcePosition, block.end); // Non-singleton range.
    next_block.count = std::max(block.count, next_block.count);
    iter.DeleteBlock();
  }
}
References v8::internal::CoverageBlock::count, DCHECK_NE, v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::DeleteBlock(), v8::internal::CoverageBlock::end, v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::GetBlock(), v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::GetNextBlock(), v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::HasNext(), HaveSameSourceRange(), v8::internal::kNoSourcePosition, and v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::Next().
Referenced by CollectBlockCoverageInternal().
MergeNestedRanges()
void v8::internal::anonymous_namespace{debug-coverage.cc}::MergeNestedRanges (CoverageFunction * function)
Definition at line 298 of file debug-coverage.cc.
                                                   {
  CoverageBlockIterator iter(function);
  while (iter.Next()) {
    CoverageBlock& block = iter.GetBlock();
    CoverageBlock& parent = iter.GetParent();
    if (parent.count == block.count) {
      // Transformation may not be valid if sibling blocks exist with a
      // differing count.
      iter.DeleteBlock();
    }
  }
}
References v8::internal::CoverageBlock::count, v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::DeleteBlock(), v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::GetBlock(), v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::GetParent(), and v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::Next().
Referenced by CollectBlockCoverageInternal().
PrintBlockCoverage()
void v8::internal::anonymous_namespace{debug-coverage.cc}::PrintBlockCoverage (const CoverageFunction * function, Tagged< SharedFunctionInfo > info, bool has_nonempty_source_range, bool function_is_relevant)
Definition at line 487 of file debug-coverage.cc.
                                                   {
  DCHECK(v8_flags.trace_block_coverage);
  std::unique_ptr<char[]> function_name = function->name->ToCString();
  i::PrintF(
      "Coverage for function='%s', SFI=%p, has_nonempty_source_range=%d, "
      "function_is_relevant=%d\n",
      function_name.get(), reinterpret_cast<void*>(info.ptr()),
      has_nonempty_source_range, function_is_relevant);
  i::PrintF("{start: %d, end: %d, count: %d}\n", function->start, function->end,
            function->count);
  for (const auto& block : function->blocks) {
    i::PrintF("{start: %d, end: %d, count: %d}\n", block.start, block.end,
              block.count);
  }
}
References v8::internal::DCHECK(), v8::internal::PrintF(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), and v8::internal::v8_flags.
Referenced by v8::internal::Coverage::Collect().
ResetAllBlockCounts()
void v8::internal::anonymous_namespace{debug-coverage.cc}::ResetAllBlockCounts (Isolate * isolate, Tagged< SharedFunctionInfo > shared)
Definition at line 389 of file debug-coverage.cc.
                                                                              {
  DCHECK(shared->HasCoverageInfo(isolate));
  Tagged<CoverageInfo> coverage_info =
      Cast<CoverageInfo>(shared->GetDebugInfo(isolate)->coverage_info());
  for (int i = 0; i < coverage_info->slot_count(); i++) {
    coverage_info->ResetBlockCount(i);
  }
}
References v8::internal::DCHECK().
Referenced by CollectBlockCoverage().
RewriteFunctionScopeCounter()
void v8::internal::anonymous_namespace{debug-coverage.cc}::RewriteFunctionScopeCounter (CoverageFunction * function)
Definition at line 313 of file debug-coverage.cc.
                                                             {
  // Every function must have at least the top-level function counter.
  DCHECK(!function->blocks.empty());
  CoverageBlockIterator iter(function);
  if (iter.Next()) {
    DCHECK(iter.IsTopLevel());
    CoverageBlock& block = iter.GetBlock();
    if (block.start == SourceRange::kFunctionLiteralSourcePosition &&
        block.end == SourceRange::kFunctionLiteralSourcePosition) {
      // If a function-scope block exists, overwrite the function count. It has
      // a more reliable count than what we get from the FeedbackVector (which
      // is imprecise e.g. for generator functions and optimized code).
      function->count = block.count;
      // Then delete it; for compatibility with non-block coverage modes, the
      // function-scope block is expected in CoverageFunction, not as a
      // CoverageBlock.
      iter.DeleteBlock();
    }
  }
}
References v8::internal::CoverageBlock::count, v8::internal::DCHECK(), v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::DeleteBlock(), v8::internal::CoverageBlock::end, v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::GetBlock(), v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::IsTopLevel(), v8::internal::SourceRange::kFunctionLiteralSourcePosition, v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::Next(), and v8::internal::CoverageBlock::start.
Referenced by CollectBlockCoverageInternal().
RewritePositionSingletonsToRanges()
void v8::internal::anonymous_namespace{debug-coverage.cc}::RewritePositionSingletonsToRanges (CoverageFunction * function)
Definition at line 253 of file debug-coverage.cc.
                                                                   {
  CoverageBlockIterator iter(function);
  while (iter.Next()) {
    CoverageBlock& block = iter.GetBlock();
    CoverageBlock& parent = iter.GetParent();
    if (block.start >= function->end) {
      DCHECK_EQ(block.end, kNoSourcePosition);
      iter.DeleteBlock();
    } else if (block.end == kNoSourcePosition) {
      // The current block ends at the next sibling block (if it exists) or the
      // end of the parent block otherwise.
      if (iter.HasSiblingOrChild()) {
        block.end = iter.GetSiblingOrChild().start;
      } else if (iter.IsTopLevel()) {
        // See https://crbug.com/v8/6661. Functions are special-cased because
        // we never want the closing brace to be uncovered. This is mainly to
        // avoid a noisy UI.
        block.end = parent.end - 1;
      } else {
        block.end = parent.end;
      }
    }
  }
}
References DCHECK_EQ, v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::DeleteBlock(), v8::internal::CoverageBlock::end, v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::GetBlock(), v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::GetParent(), v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::GetSiblingOrChild(), v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::HasSiblingOrChild(), v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::IsTopLevel(), v8::internal::kNoSourcePosition, v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::Next(), and v8::internal::CoverageBlock::start.
Referenced by CollectBlockCoverageInternal().
SortBlockData()
void v8::internal::anonymous_namespace{debug-coverage.cc}::SortBlockData (std::vector< CoverageBlock > & v)
Definition at line 71 of file debug-coverage.cc.
                                                {
  // Sort according to the block nesting structure.
  std::sort(v.begin(), v.end(), CompareCoverageBlock);
}
References CompareCoverageBlock(), and v8::base::sort().
Referenced by CollectBlockCoverageInternal(), and GetSortedBlockData().
StartPosition()
int v8::internal::anonymous_namespace{debug-coverage.cc}::StartPosition (Tagged< SharedFunctionInfo > info)
Definition at line 58 of file debug-coverage.cc.
                                                   {
  int start = info->function_token_position();
  if (start == kNoSourcePosition) start = info->StartPosition();
  return start;
}
References v8::internal::kNoSourcePosition.
Referenced by v8::internal::compiler::PipelineCompilationJob::PrepareJobImpl().