v8::internal::compiler::anonymous_namespace{wasm-gc-operator-reducer.cc} Namespace Reference
Functions
bool InDeadBranch (Node *node)
Node * GetAlias (Node *node)
wasm::TypeInModule Intersection (wasm::TypeInModule type1, wasm::TypeInModule type2)
Function Documentation
GetAlias()
Node* v8::internal::compiler::anonymous_namespace{wasm-gc-operator-reducer.cc}::GetAlias (Node * node)
Definition at line 79 of file wasm-gc-operator-reducer.cc.
                           {
  switch (node->opcode()) {
    case IrOpcode::kWasmTypeCast:
    case IrOpcode::kWasmTypeCastAbstract:
    case IrOpcode::kTypeGuard:
    case IrOpcode::kAssertNotNull:
      return NodeProperties::GetValueInput(node, 0);
    default:
      return nullptr;
  }
}
References v8::internal::compiler::NodeProperties::GetValueInput(), and v8::internal::compiler::Node::opcode().
Referenced by v8::internal::compiler::WasmGCOperatorReducer::UpdateNodeAndAliasesTypes().
InDeadBranch()
bool v8::internal::compiler::anonymous_namespace{wasm-gc-operator-reducer.cc}::InDeadBranch (Node * node)
Definition at line 73 of file wasm-gc-operator-reducer.cc.
                              {
  return node->opcode() == IrOpcode::kDead ||
         node->opcode() == IrOpcode::kDeadValue ||
         NodeProperties::GetType(node).AsWasm().type.is_uninhabited();
}
References v8::internal::compiler::NodeProperties::GetType(), and v8::internal::compiler::Node::opcode().
Referenced by v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCast(), and v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCheck().
Intersection()
wasm::TypeInModule v8::internal::compiler::anonymous_namespace{wasm-gc-operator-reducer.cc}::Intersection (wasm::TypeInModule type1, wasm::TypeInModule type2)
Definition at line 91 of file wasm-gc-operator-reducer.cc.
                                                        {
  DCHECK_EQ(type1.module, type2.module);
  return wasm::Intersection(type1.type, type2.type, type1.module);
}
References DCHECK_EQ, v8::internal::wasm::Intersection(), v8::internal::wasm::TypeInModule::module, and v8::internal::wasm::TypeInModule::type.
Referenced by v8::internal::compiler::WasmGCOperatorReducer::ObjectTypeFromContext(), and v8::internal::compiler::WasmGCOperatorReducer::ReduceTypeGuard().