v8::internal::anonymous_namespace{weak-code-registry.cc} Namespace Reference
Functions
void Untrack (CodeEntry *entry)
Function Documentation
Untrack()
void v8::internal::anonymous_namespace{weak-code-registry.cc}::Untrack (CodeEntry * entry)
Definition at line 16 of file weak-code-registry.cc.
                               {
  if (Address** heap_object_location_address =
          entry->heap_object_location_address()) {
    GlobalHandles::Destroy(*heap_object_location_address);
    *heap_object_location_address = nullptr;
  }
}
References v8::internal::GlobalHandles::Destroy(), and v8::internal::CodeEntry::heap_object_location_address().
Referenced by v8::internal::WeakCodeRegistry::Clear().