v8::internal::anonymous_namespace{builtins-date.cc} Namespace Reference
Functions
Tagged< Object > SetLocalDateValue (Isolate *isolate, DirectHandle< JSDate > date, double time_val)
Tagged< Object > SetDateValue (Isolate *isolate, DirectHandle< JSDate > date, double time_val)
Function Documentation
SetDateValue()
Tagged<Object> v8::internal::anonymous_namespace{builtins-date.cc}::SetDateValue (Isolate * isolate, DirectHandle< JSDate > date, double time_val)
Definition at line 45 of file builtins-date.cc.
                                             {
  if (DateCache::TryTimeClip(&time_val)) {
    date->SetValue(isolate, time_val);
    return *isolate->factory()->NewNumber(time_val);
  }
  date->SetNanValue();
  return ReadOnlyRoots(isolate).nan_value();
}
References v8::internal::date, v8::internal::Isolate::factory(), v8::internal::FactoryBase< Impl >::NewNumber(), and v8::internal::DateCache::TryTimeClip().
Referenced by v8::internal::BUILTIN().
SetLocalDateValue()
Tagged<Object> v8::internal::anonymous_namespace{builtins-date.cc}::SetLocalDateValue (Isolate * isolate, DirectHandle< JSDate > date, double time_val)
Definition at line 31 of file builtins-date.cc.
                                                  {
  if (time_val >= -DateCache::kMaxTimeBeforeUTCInMs &&
      time_val <= DateCache::kMaxTimeBeforeUTCInMs) {
    time_val = isolate->date_cache()->ToUTC(static_cast<int64_t>(time_val));
    if (DateCache::TryTimeClip(&time_val)) {
      date->SetValue(isolate, time_val);
      return *isolate->factory()->NewNumber(time_val);
    }
  }
  date->SetNanValue();
  return ReadOnlyRoots(isolate).nan_value();
}
References v8::internal::date, v8::internal::Isolate::date_cache(), v8::internal::Isolate::factory(), v8::internal::DateCache::kMaxTimeBeforeUTCInMs, v8::internal::FactoryBase< Impl >::NewNumber(), v8::internal::DateCache::ToUTC(), and v8::internal::DateCache::TryTimeClip().
Referenced by v8::internal::BUILTIN().