cppgc::internal::anonymous_namespace{concurrent-marker.cc} Namespace Reference
Classes
class ConcurrentMarkingTask
Functions
template<StatsCollector::ConcurrentScopeId scope_id, size_t kDeadlineCheckInterval = kDefaultDeadlineCheckInterval, typename WorklistLocal , typename Callback >
bool DrainWorklistWithYielding (JobDelegate *job_delegate, StatsCollector *stats_collector, ConcurrentMarkingState &marking_state, ConcurrentMarkerBase &concurrent_marker, WorklistLocal &worklist_local, Callback callback)
size_t WorkSizeForConcurrentMarking (MarkingWorklists &marking_worklists)
bool HasWorkForConcurrentMarking (MarkingWorklists &marking_worklists)
Variables
static constexpr double kMarkingScheduleRatioBeforeConcurrentPriorityIncrease
static constexpr size_t kDefaultDeadlineCheckInterval = 750u
Function Documentation
DrainWorklistWithYielding()
template<StatsCollector::ConcurrentScopeId scope_id, size_t kDeadlineCheckInterval = kDefaultDeadlineCheckInterval, typename WorklistLocal , typename Callback >
bool cppgc::internal::anonymous_namespace{concurrent-marker.cc}::DrainWorklistWithYielding (JobDelegate * job_delegate, StatsCollector * stats_collector, ConcurrentMarkingState & marking_state, ConcurrentMarkerBase & concurrent_marker, WorklistLocal & worklist_local, Callback callback)
Definition at line 27 of file concurrent-marker.cc.
                                                  {
  return DrainWorklistWithPredicate<kDeadlineCheckInterval>(
      [&concurrent_marker, &marking_state, job_delegate]() {
        concurrent_marker.AddConcurrentlyMarkedBytes(
            marking_state.RecentlyMarkedBytes());
        return job_delegate->ShouldYield();
      },
      [stats_collector]() {
        return StatsCollector::DisabledConcurrentScope(stats_collector,
                                                       scope_id);
      },
      worklist_local, callback);
}
References cppgc::internal::ConcurrentMarkerBase::AddConcurrentlyMarkedBytes(), cppgc::internal::BasicMarkingState::RecentlyMarkedBytes(), and v8::JobDelegate::ShouldYield().
Referenced by cppgc::internal::anonymous_namespace{concurrent-marker.cc}::ConcurrentMarkingTask::ProcessWorklists().
HasWorkForConcurrentMarking()
bool cppgc::internal::anonymous_namespace{concurrent-marker.cc}::HasWorkForConcurrentMarking (MarkingWorklists & marking_worklists)
Definition at line 55 of file concurrent-marker.cc.
                                                                      {
  return !marking_worklists.marking_worklist()->IsEmpty() ||
         !marking_worklists.write_barrier_worklist()->IsEmpty() ||
         !marking_worklists.previously_not_fully_constructed_worklist()
              ->IsEmpty();
}
References heap::base::Worklist< EntryType, MinSegmentSize >::IsEmpty(), cppgc::internal::MarkingWorklists::marking_worklist(), cppgc::internal::MarkingWorklists::previously_not_fully_constructed_worklist(), and cppgc::internal::MarkingWorklists::write_barrier_worklist().
Referenced by cppgc::internal::ConcurrentMarkerBase::NotifyIncrementalMutatorStepCompleted(), cppgc::internal::ConcurrentMarkerBase::NotifyOfWorkIfNeeded(), and cppgc::internal::anonymous_namespace{concurrent-marker.cc}::ConcurrentMarkingTask::Run().
WorkSizeForConcurrentMarking()
size_t cppgc::internal::anonymous_namespace{concurrent-marker.cc}::WorkSizeForConcurrentMarking (MarkingWorklists & marking_worklists)
Definition at line 46 of file concurrent-marker.cc.
                                                                         {
  return marking_worklists.marking_worklist()->Size() +
         marking_worklists.write_barrier_worklist()->Size() +
         marking_worklists.previously_not_fully_constructed_worklist()->Size();
}
References cppgc::internal::MarkingWorklists::marking_worklist(), cppgc::internal::MarkingWorklists::previously_not_fully_constructed_worklist(), heap::base::Worklist< EntryType, MinSegmentSize >::Size(), and cppgc::internal::MarkingWorklists::write_barrier_worklist().
Referenced by cppgc::internal::anonymous_namespace{concurrent-marker.cc}::ConcurrentMarkingTask::GetMaxConcurrency().
Variable Documentation
kDefaultDeadlineCheckInterval
constexpr size_t cppgc::internal::anonymous_namespace{concurrent-marker.cc}::kDefaultDeadlineCheckInterval = 750u [static], [constexpr]
Definition at line 22 of file concurrent-marker.cc.
kMarkingScheduleRatioBeforeConcurrentPriorityIncrease
constexpr double cppgc::internal::anonymous_namespace{concurrent-marker.cc}::kMarkingScheduleRatioBeforeConcurrentPriorityIncrease [static], [constexpr]
Initial value:
=
    0.5
Definition at line 19 of file concurrent-marker.cc.
Referenced by cppgc::internal::ConcurrentMarkerBase::IncreaseMarkingPriorityIfNeeded().