v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc} Namespace Reference
Functions
ArchOpcode GetLoadOpcode (MemoryRepresentation loaded_rep, RegisterRepresentation result_rep)
ArchOpcode GetStoreOpcode (MemoryRepresentation stored_rep)
bool IsNodeUnsigned (InstructionSelector *selector, OpIndex n)
bool CanUseOptimizedWord32Compare (InstructionSelector *selector, OpIndex node)
void VisitFullWord32Compare (InstructionSelector *selector, OpIndex node, InstructionCode opcode, FlagsContinuation *cont)
void VisitOptimizedWord32Compare (InstructionSelector *selector, OpIndex node, InstructionCode opcode, FlagsContinuation *cont)
void VisitWord32Compare (InstructionSelector *selector, OpIndex node, FlagsContinuation *cont)
void VisitWord64Compare (InstructionSelector *selector, OpIndex node, FlagsContinuation *cont)
void VisitAtomicLoad (InstructionSelector *selector, OpIndex node, AtomicWidth width)
AtomicStoreParameters AtomicStoreParametersOf (InstructionSelector *selector, OpIndex node)
void VisitAtomicStore (InstructionSelector *selector, OpIndex node, AtomicWidth width)
void VisitAtomicBinop (InstructionSelector *selector, OpIndex node, ArchOpcode opcode, AtomicWidth width, MemoryAccessKind access_kind)
Function Documentation
AtomicStoreParametersOf()
AtomicStoreParameters v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::AtomicStoreParametersOf (InstructionSelector * selector, OpIndex node)
Definition at line 1580 of file instruction-selector-riscv64.cc.
                                                            {
  auto store = selector->store_view(node);
  return AtomicStoreParameters(store.stored_rep().representation(),
                               store.stored_rep().write_barrier_kind(),
                               store.memory_order().value(),
                               store.access_kind());
}
References store(), and v8::internal::compiler::InstructionSelector::store_view().
CanUseOptimizedWord32Compare()
bool v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::CanUseOptimizedWord32Compare (InstructionSelector * selector, OpIndex node)
Definition at line 1411 of file instruction-selector-riscv64.cc.
                                                                               {
  if (COMPRESS_POINTERS_BOOL) {
    return false;
  }
  const Operation& op = selector->Get(node);
  DCHECK_EQ(op.input_count, 2);
  if (IsNodeUnsigned(selector, op.input(0)) ==
      IsNodeUnsigned(selector, op.input(1))) {
    return true;
  }
  return false;
}
References COMPRESS_POINTERS_BOOL, DCHECK_EQ, v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::turboshaft::Operation::input_count, and IsNodeUnsigned().
Referenced by VisitWord32Compare().
GetLoadOpcode()
ArchOpcode v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetLoadOpcode (MemoryRepresentation loaded_rep, RegisterRepresentation result_rep)
Definition at line 279 of file instruction-selector-riscv64.cc.
                                                            {
  // NOTE: The meaning of `loaded_rep` = `MemoryRepresentation::AnyTagged()` is
  // we are loading a compressed tagged field, while `result_rep` =
  // `RegisterRepresentation::Tagged()` refers to an uncompressed tagged value.
  switch (loaded_rep) {
    case MemoryRepresentation::Int8():
      DCHECK_EQ(result_rep, RegisterRepresentation::Word32());
      return kRiscvLb;
    case MemoryRepresentation::Uint8():
      DCHECK_EQ(result_rep, RegisterRepresentation::Word32());
      return kRiscvLbu;
    case MemoryRepresentation::Int16():
      DCHECK_EQ(result_rep, RegisterRepresentation::Word32());
      return kRiscvLh;
    case MemoryRepresentation::Uint16():
      DCHECK_EQ(result_rep, RegisterRepresentation::Word32());
      return kRiscvLhu;
    case MemoryRepresentation::Int32():
      DCHECK_EQ(result_rep, RegisterRepresentation::Word32());
      return kRiscvLw;
    case MemoryRepresentation::Uint32():
      DCHECK_EQ(result_rep, RegisterRepresentation::Word32());
      return kRiscvLwu;
    case MemoryRepresentation::Int64():
    case MemoryRepresentation::Uint64():
      DCHECK_EQ(result_rep, RegisterRepresentation::Word64());
      return kRiscvLd;
    case MemoryRepresentation::Float16():
      UNIMPLEMENTED();
    case MemoryRepresentation::Float32():
      DCHECK_EQ(result_rep, RegisterRepresentation::Float32());
      return kRiscvLoadFloat;
    case MemoryRepresentation::Float64():
      DCHECK_EQ(result_rep, RegisterRepresentation::Float64());
      return kRiscvLoadDouble;
#ifdef V8_COMPRESS_POINTERS
    case MemoryRepresentation::AnyTagged():
    case MemoryRepresentation::TaggedPointer():
      if (result_rep == RegisterRepresentation::Compressed()) {
        return kRiscvLwu;
      }
      DCHECK_EQ(result_rep, RegisterRepresentation::Tagged());
      return kRiscvLoadDecompressTagged;
    case MemoryRepresentation::TaggedSigned():
      if (result_rep == RegisterRepresentation::Compressed()) {
        return kRiscvLwu;
      }
      DCHECK_EQ(result_rep, RegisterRepresentation::Tagged());
      return kRiscvLoadDecompressTaggedSigned;
#else
    case MemoryRepresentation::AnyTagged():
    case MemoryRepresentation::TaggedPointer():
    case MemoryRepresentation::TaggedSigned():
      DCHECK_EQ(result_rep, RegisterRepresentation::Tagged());
      return kRiscvLd;
#endif
    case MemoryRepresentation::AnyUncompressedTagged():
    case MemoryRepresentation::UncompressedTaggedPointer():
    case MemoryRepresentation::UncompressedTaggedSigned():
      DCHECK_EQ(result_rep, RegisterRepresentation::Tagged());
      return kRiscvLd;
    case MemoryRepresentation::ProtectedPointer():
      CHECK(V8_ENABLE_SANDBOX_BOOL);
      return kRiscvLoadDecompressProtected;
    case MemoryRepresentation::IndirectPointer():
      UNREACHABLE();
    case MemoryRepresentation::SandboxedPointer():
      return kRiscvLoadDecodeSandboxedPointer;
    case MemoryRepresentation::Simd128():
      return kRiscvRvvLd;
    case MemoryRepresentation::Simd256():
      UNREACHABLE();
  }
}
References v8::internal::compiler::turboshaft::MemoryRepresentation::AnyTagged(), v8::internal::compiler::turboshaft::MemoryRepresentation::AnyUncompressedTagged(), CHECK, v8::internal::compiler::turboshaft::RegisterRepresentation::Compressed(), DCHECK_EQ, v8::internal::compiler::turboshaft::MemoryRepresentation::Float16(), v8::internal::compiler::turboshaft::RegisterRepresentation::Float32(), v8::internal::compiler::turboshaft::MemoryRepresentation::Float32(), v8::internal::compiler::turboshaft::RegisterRepresentation::Float64(), v8::internal::compiler::turboshaft::MemoryRepresentation::Float64(), v8::internal::compiler::turboshaft::MemoryRepresentation::IndirectPointer(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int16(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int32(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int64(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int8(), v8::internal::compiler::turboshaft::MemoryRepresentation::ProtectedPointer(), v8::internal::compiler::turboshaft::MemoryRepresentation::SandboxedPointer(), v8::internal::compiler::turboshaft::MemoryRepresentation::Simd128(), v8::internal::compiler::turboshaft::MemoryRepresentation::Simd256(), v8::internal::compiler::turboshaft::RegisterRepresentation::Tagged(), v8::internal::compiler::turboshaft::MemoryRepresentation::TaggedPointer(), v8::internal::compiler::turboshaft::MemoryRepresentation::TaggedSigned(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint16(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint32(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint64(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint8(), v8::internal::compiler::turboshaft::MemoryRepresentation::UncompressedTaggedPointer(), v8::internal::compiler::turboshaft::MemoryRepresentation::UncompressedTaggedSigned(), v8::internal::compiler::UNIMPLEMENTED(), v8::internal::UNREACHABLE(), V8_ENABLE_SANDBOX_BOOL, v8::internal::compiler::turboshaft::RegisterRepresentation::Word32(), and v8::internal::compiler::turboshaft::RegisterRepresentation::Word64().
GetStoreOpcode()
ArchOpcode v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetStoreOpcode (MemoryRepresentation stored_rep)
Definition at line 356 of file instruction-selector-riscv64.cc.
                                                           {
  switch (stored_rep) {
    case MemoryRepresentation::Int8():
    case MemoryRepresentation::Uint8():
      return kRiscvSb;
    case MemoryRepresentation::Int16():
    case MemoryRepresentation::Uint16():
      return kRiscvSh;
    case MemoryRepresentation::Int32():
    case MemoryRepresentation::Uint32():
      return kRiscvSw;
    case MemoryRepresentation::Int64():
    case MemoryRepresentation::Uint64():
      return kRiscvSd;
    case MemoryRepresentation::Float16():
      UNIMPLEMENTED();
    case MemoryRepresentation::Float32():
      return kRiscvStoreFloat;
    case MemoryRepresentation::Float64():
      return kRiscvStoreDouble;
    case MemoryRepresentation::AnyTagged():
    case MemoryRepresentation::TaggedPointer():
    case MemoryRepresentation::TaggedSigned():
      return kRiscvStoreCompressTagged;
    case MemoryRepresentation::AnyUncompressedTagged():
    case MemoryRepresentation::UncompressedTaggedPointer():
    case MemoryRepresentation::UncompressedTaggedSigned():
      return kRiscvSd;
    case MemoryRepresentation::ProtectedPointer():
      // We never store directly to protected pointers from generated code.
      UNREACHABLE();
    case MemoryRepresentation::IndirectPointer():
      return kRiscvStoreIndirectPointer;
    case MemoryRepresentation::SandboxedPointer():
      return kRiscvStoreEncodeSandboxedPointer;
    case MemoryRepresentation::Simd128():
      return kRiscvRvvSt;
    case MemoryRepresentation::Simd256():
      UNREACHABLE();
  }
}
References v8::internal::compiler::turboshaft::MemoryRepresentation::AnyTagged(), v8::internal::compiler::turboshaft::MemoryRepresentation::AnyUncompressedTagged(), v8::internal::compiler::turboshaft::MemoryRepresentation::Float16(), v8::internal::compiler::turboshaft::MemoryRepresentation::Float32(), v8::internal::compiler::turboshaft::MemoryRepresentation::Float64(), v8::internal::compiler::turboshaft::MemoryRepresentation::IndirectPointer(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int16(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int32(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int64(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int8(), v8::internal::compiler::turboshaft::MemoryRepresentation::ProtectedPointer(), v8::internal::compiler::turboshaft::MemoryRepresentation::SandboxedPointer(), v8::internal::compiler::turboshaft::MemoryRepresentation::Simd128(), v8::internal::compiler::turboshaft::MemoryRepresentation::Simd256(), v8::internal::compiler::turboshaft::MemoryRepresentation::TaggedPointer(), v8::internal::compiler::turboshaft::MemoryRepresentation::TaggedSigned(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint16(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint32(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint64(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint8(), v8::internal::compiler::turboshaft::MemoryRepresentation::UncompressedTaggedPointer(), v8::internal::compiler::turboshaft::MemoryRepresentation::UncompressedTaggedSigned(), v8::internal::compiler::UNIMPLEMENTED(), and v8::internal::UNREACHABLE().
IsNodeUnsigned()
bool v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::IsNodeUnsigned (InstructionSelector * selector, OpIndex n)
Definition at line 1379 of file instruction-selector-riscv64.cc.
                                                              {
  const Operation& op = selector->Get(n);
  if (op.Is<LoadOp>()) {
    const LoadOp& load = op.Cast<LoadOp>();
    return load.machine_type().IsUnsigned() ||
           load.machine_type().IsCompressed();
  } else if (op.Is<WordBinopOp>()) {
    const WordBinopOp& binop = op.Cast<WordBinopOp>();
    switch (binop.kind) {
      case WordBinopOp::Kind::kUnsignedDiv:
      case WordBinopOp::Kind::kUnsignedMod:
      case WordBinopOp::Kind::kUnsignedMulOverflownBits:
        return true;
      default:
        return false;
    }
  } else if (op.Is<ChangeOrDeoptOp>()) {
    const ChangeOrDeoptOp& change = op.Cast<ChangeOrDeoptOp>();
    return change.kind == ChangeOrDeoptOp::Kind::kFloat64ToUint32;
  } else if (op.Is<ConvertJSPrimitiveToUntaggedOp>()) {
    const ConvertJSPrimitiveToUntaggedOp& convert =
        op.Cast<ConvertJSPrimitiveToUntaggedOp>();
    return convert.kind ==
           ConvertJSPrimitiveToUntaggedOp::UntaggedKind::kUint32;
  } else if (op.Is<ConstantOp>()) {
    const ConstantOp& constant = op.Cast<ConstantOp>();
    return constant.kind == ConstantOp::Kind::kCompressedHeapObject;
  } else {
    return false;
  }
}
References v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::MachineType::IsCompressed(), v8::internal::MachineType::IsUnsigned(), v8::internal::compiler::turboshaft::WordBinopOp::kind, v8::internal::compiler::turboshaft::ChangeOrDeoptOp::kind, v8::internal::compiler::turboshaft::ConstantOp::kind, v8::internal::compiler::turboshaft::ConvertJSPrimitiveToUntaggedOp::kind, and v8::internal::compiler::turboshaft::LoadOp::machine_type().
Referenced by CanUseOptimizedWord32Compare().
VisitAtomicBinop()
void v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitAtomicBinop (InstructionSelector * selector, OpIndex node, ArchOpcode opcode, AtomicWidth width, MemoryAccessKind access_kind)
Definition at line 1678 of file instruction-selector-riscv64.cc.
                                                    {
  using OpIndex = OpIndex;
  RiscvOperandGenerator g(selector);
  const AtomicRMWOp& atomic_op = selector->Cast<AtomicRMWOp>(node);
  OpIndex base = atomic_op.base();
  OpIndex index = atomic_op.index();
  OpIndex value = atomic_op.value();
  AddressingMode addressing_mode = kMode_MRI;
  InstructionOperand inputs[3];
  size_t input_count = 0;
  inputs[input_count++] = g.UseUniqueRegister(base);
  inputs[input_count++] = g.UseUniqueRegister(index);
  inputs[input_count++] = g.UseUniqueRegister(value);
  InstructionOperand outputs[1];
  outputs[0] = g.UseUniqueRegister(node);
  InstructionOperand temps[4];
  temps[0] = g.TempRegister();
  temps[1] = g.TempRegister();
  temps[2] = g.TempRegister();
  temps[3] = g.TempRegister();
  InstructionCode code = opcode | AddressingModeField::encode(addressing_mode) |
                         AtomicWidthField::encode(width);
  if (access_kind == MemoryAccessKind::kProtectedByTrapHandler) {
    code |= AccessModeField::encode(kMemoryAccessProtectedMemOutOfBounds);
  }
  selector->Emit(code, 1, outputs, input_count, inputs, 4, temps);
}
References v8::internal::compiler::turboshaft::AtomicRMWOp::base(), v8::internal::compiler::turboshaft::OperationMatcher::Cast(), code, v8::internal::compiler::InstructionSelector::Emit(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::turboshaft::AtomicRMWOp::index(), v8::internal::index, v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::kMemoryAccessProtectedMemOutOfBounds, v8::internal::compiler::kProtectedByTrapHandler, v8::internal::compiler::turboshaft::OpIndex, v8::internal::compiler::OperandGenerator::TempRegister(), v8::internal::compiler::OperandGenerator::UseUniqueRegister(), v8::internal::compiler::turboshaft::AtomicRMWOp::value(), and v8::internal::value.
VisitAtomicLoad()
void v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitAtomicLoad (InstructionSelector * selector, OpIndex node, AtomicWidth width)
Definition at line 1499 of file instruction-selector-riscv64.cc.
                                        {
  using OpIndex = OpIndex;
  RiscvOperandGenerator g(selector);
  auto load = selector->load_view(node);
  OpIndex base = load.base();
  OpIndex index = load.index();
  // The memory order is ignored as both acquire and sequentially consistent
  // loads can emit LDAR.
  // https://www.cl.cam.ac.uk/~pes20/cpp/cpp0xmappings.html
  LoadRepresentation load_rep = load.loaded_rep();
  InstructionCode code;
  switch (load_rep.representation()) {
    case MachineRepresentation::kWord8:
      DCHECK_IMPLIES(load_rep.IsSigned(), width == AtomicWidth::kWord32);
      code = load_rep.IsSigned() ? kAtomicLoadInt8 : kAtomicLoadUint8;
      break;
    case MachineRepresentation::kWord16:
      DCHECK_IMPLIES(load_rep.IsSigned(), width == AtomicWidth::kWord32);
      code = load_rep.IsSigned() ? kAtomicLoadInt16 : kAtomicLoadUint16;
      break;
    case MachineRepresentation::kWord32:
      code = kAtomicLoadWord32;
      break;
    case MachineRepresentation::kWord64:
      code = kRiscvWord64AtomicLoadUint64;
      break;
#ifdef V8_COMPRESS_POINTERS
    case MachineRepresentation::kTaggedSigned:
      code = kRiscvAtomicLoadDecompressTaggedSigned;
      break;
    case MachineRepresentation::kTaggedPointer:
    case MachineRepresentation::kTagged:
      code = kRiscvAtomicLoadDecompressTagged;
      break;
#else
    case MachineRepresentation::kTaggedSigned: // Fall through.
    case MachineRepresentation::kTaggedPointer: // Fall through.
    case MachineRepresentation::kTagged:
      if (kTaggedSize == 8) {
        code = kRiscvWord64AtomicLoadUint64;
      } else {
        code = kAtomicLoadWord32;
      }
      break;
#endif
    case MachineRepresentation::kCompressedPointer: // Fall through.
    case MachineRepresentation::kCompressed:
      DCHECK(COMPRESS_POINTERS_BOOL);
      code = kAtomicLoadWord32;
      break;
    default:
      UNREACHABLE();
  }
  bool traps_on_null;
  if (load.is_protected(&traps_on_null)) {
    // Atomic loads and null dereference are mutually exclusive. This might
    // change with multi-threaded wasm-gc in which case the access mode should
    // probably be kMemoryAccessProtectedNullDereference.
    DCHECK(!traps_on_null);
    code |= AccessModeField::encode(kMemoryAccessProtectedMemOutOfBounds);
  }
  if (g.CanBeImmediate(index, code)) {
    selector->Emit(code | AddressingModeField::encode(kMode_MRI) |
                       AtomicWidthField::encode(width),
                   g.DefineAsRegister(node), g.UseRegister(base),
                   g.UseImmediate(index));
  } else {
    InstructionOperand addr_reg = g.TempRegister();
    selector->Emit(kRiscvAdd64 | AddressingModeField::encode(kMode_None),
                   addr_reg, g.UseRegister(base), g.UseRegister(index));
    // Emit desired load opcode, using temp addr_reg.
    selector->Emit(code | AddressingModeField::encode(kMode_MRI) |
                       AtomicWidthField::encode(width),
                   g.DefineAsRegister(node), addr_reg, g.TempImmediate(0));
  }
}
References v8::internal::compiler::RiscvOperandGenerator::CanBeImmediate(), code, COMPRESS_POINTERS_BOOL, v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::InstructionSelector::Emit(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::index, v8::internal::MachineType::IsSigned(), v8::internal::kCompressed, v8::internal::kCompressedPointer, v8::internal::compiler::kMemoryAccessProtectedMemOutOfBounds, v8::internal::kTagged, v8::internal::kTaggedPointer, v8::internal::kTaggedSigned, v8::internal::kTaggedSize, v8::internal::kWord16, v8::internal::kWord32, v8::internal::compiler::kWord32, v8::internal::kWord64, v8::internal::kWord8, v8::internal::compiler::InstructionSelector::load_view(), v8::internal::compiler::turboshaft::OpIndex, v8::internal::MachineType::representation(), v8::internal::compiler::OperandGenerator::TempImmediate(), v8::internal::compiler::OperandGenerator::TempRegister(), v8::internal::UNREACHABLE(), v8::internal::compiler::OperandGenerator::UseImmediate(), and v8::internal::compiler::OperandGenerator::UseRegister().
VisitAtomicStore()
void v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitAtomicStore (InstructionSelector * selector, OpIndex node, AtomicWidth width)
Definition at line 1589 of file instruction-selector-riscv64.cc.
                                         {
  using OpIndex = OpIndex;
  RiscvOperandGenerator g(selector);
  auto store = selector->store_view(node);
  OpIndex base = store.base();
  OpIndex index = store.index().value();
  OpIndex value = store.value();
  DCHECK_EQ(store.displacement(), 0);
  // The memory order is ignored.
  AtomicStoreParameters store_params = AtomicStoreParametersOf(selector, node);
  WriteBarrierKind write_barrier_kind = store_params.write_barrier_kind();
  MachineRepresentation rep = store_params.representation();
  if (v8_flags.enable_unconditional_write_barriers &&
      CanBeTaggedOrCompressedPointer(rep)) {
    write_barrier_kind = kFullWriteBarrier;
  }
  InstructionCode code;
  if (write_barrier_kind != kNoWriteBarrier &&
      !v8_flags.disable_write_barriers) {
    DCHECK(CanBeTaggedPointer(rep));
    DCHECK_EQ(AtomicWidthSize(width), kTaggedSize);
    InstructionOperand inputs[3];
    size_t input_count = 0;
    inputs[input_count++] = g.UseUniqueRegister(base);
    inputs[input_count++] = g.UseUniqueRegister(index);
    inputs[input_count++] = g.UseUniqueRegister(value);
    RecordWriteMode record_write_mode =
        WriteBarrierKindToRecordWriteMode(write_barrier_kind);
    InstructionOperand temps[] = {g.TempRegister(), g.TempRegister()};
    size_t const temp_count = arraysize(temps);
    code = kArchAtomicStoreWithWriteBarrier;
    code |= RecordWriteModeField::encode(record_write_mode);
    selector->Emit(code, 0, nullptr, input_count, inputs, temp_count, temps);
  } else {
    switch (rep) {
      case MachineRepresentation::kWord8:
        code = kAtomicStoreWord8;
        break;
      case MachineRepresentation::kWord16:
        code = kAtomicStoreWord16;
        break;
      case MachineRepresentation::kWord32:
        code = kAtomicStoreWord32;
        break;
      case MachineRepresentation::kWord64:
        DCHECK_EQ(width, AtomicWidth::kWord64);
        code = kRiscvWord64AtomicStoreWord64;
        break;
      case MachineRepresentation::kTaggedSigned: // Fall through.
      case MachineRepresentation::kTaggedPointer: // Fall through.
      case MachineRepresentation::kTagged:
        DCHECK_EQ(AtomicWidthSize(width), kTaggedSize);
        code = kRiscvStoreCompressTagged;
        break;
      default:
        UNREACHABLE();
    }
    code |= AtomicWidthField::encode(width);
    if (store.is_store_trap_on_null()) {
      code |= AccessModeField::encode(kMemoryAccessProtectedNullDereference);
    } else if (store_params.kind() ==
               MemoryAccessKind::kProtectedByTrapHandler) {
      code |= AccessModeField::encode(kMemoryAccessProtectedMemOutOfBounds);
    }
    if (g.CanBeImmediate(index, code)) {
      selector->Emit(code | AddressingModeField::encode(kMode_MRI) |
                         AtomicWidthField::encode(width),
                     g.NoOutput(), g.UseRegisterOrImmediateZero(value),
                     g.UseRegister(base), g.UseImmediate(index));
    } else {
      InstructionOperand addr_reg = g.TempRegister();
      selector->Emit(kRiscvAdd64 | AddressingModeField::encode(kMode_None),
                     addr_reg, g.UseRegister(index), g.UseRegister(base));
      // Emit desired store opcode, using temp addr_reg.
      selector->Emit(code | AddressingModeField::encode(kMode_MRI) |
                         AtomicWidthField::encode(width),
                     g.NoOutput(), g.UseRegisterOrImmediateZero(value),
                     addr_reg, g.TempImmediate(0));
    }
  }
}
References arraysize, v8::internal::compiler::AtomicStoreParametersOf(), v8::internal::compiler::AtomicWidthSize(), v8::internal::compiler::RiscvOperandGenerator::CanBeImmediate(), v8::internal::CanBeTaggedOrCompressedPointer(), v8::internal::CanBeTaggedPointer(), code, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::InstructionSelector::Emit(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::index, v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::kFullWriteBarrier, v8::internal::compiler::AtomicStoreParameters::kind(), v8::internal::compiler::kMemoryAccessProtectedMemOutOfBounds, v8::internal::compiler::kMemoryAccessProtectedNullDereference, v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kProtectedByTrapHandler, v8::internal::kTagged, v8::internal::kTaggedPointer, v8::internal::kTaggedSigned, v8::internal::kTaggedSize, v8::internal::kWord16, v8::internal::kWord32, v8::internal::kWord64, v8::internal::compiler::kWord64, v8::internal::kWord8, v8::internal::compiler::OperandGenerator::NoOutput(), v8::internal::compiler::turboshaft::OpIndex, v8::internal::compiler::AtomicStoreParameters::representation(), store(), v8::internal::compiler::InstructionSelector::store_view(), v8::internal::compiler::OperandGenerator::TempImmediate(), v8::internal::compiler::OperandGenerator::TempRegister(), v8::internal::UNREACHABLE(), v8::internal::compiler::OperandGenerator::UseImmediate(), v8::internal::compiler::OperandGenerator::UseRegister(), v8::internal::compiler::RiscvOperandGenerator::UseRegisterOrImmediateZero(), v8::internal::compiler::OperandGenerator::UseUniqueRegister(), v8::internal::v8_flags, v8::internal::value, v8::internal::compiler::AtomicStoreParameters::write_barrier_kind(), and v8::internal::compiler::WriteBarrierKindToRecordWriteMode().
VisitFullWord32Compare()
void v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitFullWord32Compare (InstructionSelector * selector, OpIndex node, InstructionCode opcode, FlagsContinuation * cont)
Definition at line 1426 of file instruction-selector-riscv64.cc.
                                                                             {
  RiscvOperandGenerator g(selector);
  InstructionOperand leftOp = g.TempRegister();
  InstructionOperand rightOp = g.TempRegister();
  const Operation& op = selector->Get(node);
  DCHECK_EQ(op.input_count, 2);
  selector->Emit(kRiscvShl64, leftOp, g.UseRegister(op.input(0)),
                 g.TempImmediate(32));
  selector->Emit(kRiscvShl64, rightOp, g.UseRegister(op.input(1)),
                 g.TempImmediate(32));
  Instruction* instr = VisitCompare(selector, opcode, leftOp, rightOp, cont);
  selector->UpdateSourcePosition(instr, node);
}
References DCHECK_EQ, v8::internal::compiler::InstructionSelector::Emit(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::turboshaft::Operation::input_count, v8::internal::compiler::OperandGenerator::TempImmediate(), v8::internal::compiler::OperandGenerator::TempRegister(), v8::internal::compiler::InstructionSelector::UpdateSourcePosition(), v8::internal::compiler::OperandGenerator::UseRegister(), and v8::internal::compiler::VisitCompare().
Referenced by VisitWord32Compare().
VisitOptimizedWord32Compare()
void v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitOptimizedWord32Compare (InstructionSelector * selector, OpIndex node, InstructionCode opcode, FlagsContinuation * cont)
Definition at line 1442 of file instruction-selector-riscv64.cc.
                                                          {
  if (v8_flags.debug_code) {
    RiscvOperandGenerator g(selector);
    InstructionOperand leftOp = g.TempRegister();
    InstructionOperand rightOp = g.TempRegister();
    InstructionOperand optimizedResult = g.TempRegister();
    InstructionOperand fullResult = g.TempRegister();
    FlagsCondition condition = cont->condition();
    InstructionCode testOpcode = opcode |
                                 FlagsConditionField::encode(condition) |
                                 FlagsModeField::encode(kFlags_set);
    const Operation& op = selector->Get(node);
    DCHECK_EQ(op.input_count, 2);
    selector->Emit(testOpcode, optimizedResult, g.UseRegister(op.input(0)),
                   g.UseRegister(op.input(1)));
    selector->Emit(kRiscvShl64, leftOp, g.UseRegister(op.input(0)),
                   g.TempImmediate(32));
    selector->Emit(kRiscvShl64, rightOp, g.UseRegister(op.input(1)),
                   g.TempImmediate(32));
    selector->Emit(testOpcode, fullResult, leftOp, rightOp);
    selector->Emit(kRiscvAssertEqual, g.NoOutput(), optimizedResult, fullResult,
                   g.TempImmediate(static_cast<int>(
                       AbortReason::kUnsupportedNonPrimitiveCompare)));
  }
  Instruction* instr = VisitWordCompare(selector, node, opcode, cont, false);
  selector->UpdateSourcePosition(instr, node);
}
References v8::internal::compiler::FlagsContinuation::condition(), DCHECK_EQ, v8::internal::compiler::InstructionSelector::Emit(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::turboshaft::Operation::input_count, v8::internal::compiler::kFlags_set, v8::internal::compiler::OperandGenerator::NoOutput(), v8::internal::compiler::OperandGenerator::TempImmediate(), v8::internal::compiler::OperandGenerator::TempRegister(), v8::internal::compiler::InstructionSelector::UpdateSourcePosition(), v8::internal::compiler::OperandGenerator::UseRegister(), v8::internal::v8_flags, and v8::internal::compiler::VisitWordCompare().
Referenced by VisitWord32Compare().
VisitWord32Compare()
void v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitWord32Compare (InstructionSelector * selector, OpIndex node, FlagsContinuation * cont)
Definition at line 1475 of file instruction-selector-riscv64.cc.
                                                 {
#ifdef USE_SIMULATOR
  const Operation& op = selector->Get(node);
  DCHECK_EQ(op.input_count, 2);
  const Operation& lhs = selector->Get(op.input(0));
  const Operation& rhs = selector->Get(op.input(1));
  if (lhs.Is<DidntThrowOp>() || rhs.Is<DidntThrowOp>()) {
    VisitFullWord32Compare(selector, node, kRiscvCmp, cont);
  } else if (!CanUseOptimizedWord32Compare(selector, node)) {
#else
  if (!CanUseOptimizedWord32Compare(selector, node)) {
#endif
      VisitFullWord32Compare(selector, node, kRiscvCmp, cont);
    } else {
      VisitOptimizedWord32Compare(selector, node, kRiscvCmp, cont);
    }
}
References CanUseOptimizedWord32Compare(), DCHECK_EQ, v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::turboshaft::Operation::input_count, v8::internal::compiler::turboshaft::Operation::Is(), VisitFullWord32Compare(), and VisitOptimizedWord32Compare().
VisitWord64Compare()
void v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitWord64Compare (InstructionSelector * selector, OpIndex node, FlagsContinuation * cont)
Definition at line 1494 of file instruction-selector-riscv64.cc.
                                                 {
  VisitWordCompare(selector, node, kRiscvCmp, cont, false);
}
References v8::internal::compiler::VisitWordCompare().