cppgc::internal::anonymous_namespace{heap-statistics-collector.cc} Namespace Reference
Functions
std::string GetNormalPageSpaceName (size_t index)
HeapStatistics::SpaceStatistics * InitializeSpace (HeapStatistics *stats, std::string name)
HeapStatistics::PageStatistics * InitializePage (HeapStatistics::SpaceStatistics *stats)
void FinalizePage (HeapStatistics::SpaceStatistics *space_stats, HeapStatistics::PageStatistics **page_stats)
void FinalizeSpace (HeapStatistics *stats, HeapStatistics::SpaceStatistics **space_stats, HeapStatistics::PageStatistics **page_stats)
void RecordObjectType (std::unordered_map< const void *, size_t > &type_map, std::vector< HeapStatistics::ObjectStatsEntry > &object_statistics, HeapObjectHeader *header, size_t object_size)
Function Documentation
FinalizePage()
void cppgc::internal::anonymous_namespace{heap-statistics-collector.cc}::FinalizePage (HeapStatistics::SpaceStatistics * space_stats, HeapStatistics::PageStatistics ** page_stats)
Definition at line 52 of file heap-statistics-collector.cc.
                                                             {
  if (*page_stats) {
    DCHECK_NOT_NULL(space_stats);
    space_stats->committed_size_bytes += (*page_stats)->committed_size_bytes;
    space_stats->resident_size_bytes += (*page_stats)->resident_size_bytes;
    space_stats->used_size_bytes += (*page_stats)->used_size_bytes;
  }
  *page_stats = nullptr;
}
References cppgc::HeapStatistics::SpaceStatistics::committed_size_bytes, DCHECK_NOT_NULL, cppgc::HeapStatistics::SpaceStatistics::resident_size_bytes, and cppgc::HeapStatistics::SpaceStatistics::used_size_bytes.
Referenced by cppgc::internal::anonymous_namespace{sweeper.cc}::SweepFinalizer::Finalize(), FinalizeSpace(), cppgc::internal::anonymous_namespace{sweeper.cc}::SweepFinalizer::FinalizeWithDeadline(), cppgc::internal::anonymous_namespace{sweeper.cc}::SweepFinalizer::FinalizeWithDeadlineAndSize(), cppgc::internal::HeapStatisticsCollector::VisitLargePage(), and cppgc::internal::HeapStatisticsCollector::VisitNormalPage().
FinalizeSpace()
void cppgc::internal::anonymous_namespace{heap-statistics-collector.cc}::FinalizeSpace (HeapStatistics * stats, HeapStatistics::SpaceStatistics ** space_stats, HeapStatistics::PageStatistics ** page_stats)
Definition at line 63 of file heap-statistics-collector.cc.
                                                              {
  FinalizePage(*space_stats, page_stats);
  if (*space_stats) {
    DCHECK_NOT_NULL(stats);
    stats->committed_size_bytes += (*space_stats)->committed_size_bytes;
    stats->resident_size_bytes += (*space_stats)->resident_size_bytes;
    stats->used_size_bytes += (*space_stats)->used_size_bytes;
  }
  *space_stats = nullptr;
}
References cppgc::HeapStatistics::committed_size_bytes, DCHECK_NOT_NULL, FinalizePage(), cppgc::HeapStatistics::resident_size_bytes, and cppgc::HeapStatistics::used_size_bytes.
Referenced by cppgc::internal::HeapStatisticsCollector::CollectDetailedStatistics(), cppgc::internal::HeapStatisticsCollector::VisitLargePageSpace(), and cppgc::internal::HeapStatisticsCollector::VisitNormalPageSpace().
GetNormalPageSpaceName()
std::string cppgc::internal::anonymous_namespace{heap-statistics-collector.cc}::GetNormalPageSpaceName (size_t index)
Definition at line 25 of file heap-statistics-collector.cc.
                                               {
  // Check that space is not a large object space.
  DCHECK_NE(RawHeap::kNumberOfRegularSpaces - 1, index);
  // Handle regular normal page spaces.
  if (index < RawHeap::kNumberOfRegularSpaces) {
    return "NormalPageSpace" + std::to_string(index);
  }
  // Space is a custom space.
  return "CustomSpace" +
         std::to_string(index - RawHeap::kNumberOfRegularSpaces);
}
References DCHECK_NE, v8::internal::index, and cppgc::internal::RawHeap::kNumberOfRegularSpaces.
Referenced by cppgc::internal::HeapStatisticsCollector::VisitNormalPageSpace().
InitializePage()
HeapStatistics::PageStatistics* cppgc::internal::anonymous_namespace{heap-statistics-collector.cc}::InitializePage (HeapStatistics::SpaceStatistics * stats)
Definition at line 45 of file heap-statistics-collector.cc.
                                          {
  stats->page_stats.emplace_back();
  HeapStatistics::PageStatistics* page_stats = &stats->page_stats.back();
  return page_stats;
}
References cppgc::HeapStatistics::SpaceStatistics::page_stats.
Referenced by cppgc::internal::HeapStatisticsCollector::VisitLargePage(), and cppgc::internal::HeapStatisticsCollector::VisitNormalPage().
InitializeSpace()
HeapStatistics::SpaceStatistics* cppgc::internal::anonymous_namespace{heap-statistics-collector.cc}::InitializeSpace (HeapStatistics * stats, std::string name)
Definition at line 37 of file heap-statistics-collector.cc.
                                                                 {
  stats->space_stats.emplace_back();
  HeapStatistics::SpaceStatistics* space_stats = &stats->space_stats.back();
  space_stats->name = std::move(name);
  return space_stats;
}
References cppgc::HeapStatistics::SpaceStatistics::name, name, and cppgc::HeapStatistics::space_stats.
Referenced by cppgc::internal::HeapStatisticsCollector::VisitLargePageSpace(), and cppgc::internal::HeapStatisticsCollector::VisitNormalPageSpace().
RecordObjectType()
void cppgc::internal::anonymous_namespace{heap-statistics-collector.cc}::RecordObjectType (std::unordered_map< const void *, size_t > & type_map, std::vector< HeapStatistics::ObjectStatsEntry > & object_statistics, HeapObjectHeader * header, size_t object_size)
Definition at line 76 of file heap-statistics-collector.cc.
                                                  {
  if (NameProvider::SupportsCppClassNamesAsObjectNames()) {
    // Tries to insert a new entry into the typemap with a running counter. If
    // the entry is already present, just returns the old one.
    const auto it = type_map.insert({header->GetName().value, type_map.size()});
    const size_t type_index = it.first->second;
    if (object_statistics.size() <= type_index) {
      object_statistics.resize(type_index + 1);
    }
    object_statistics[type_index].allocated_bytes += object_size;
    object_statistics[type_index].object_count++;
  }
}
References cppgc::internal::HeapObjectHeader::GetName(), cppgc::NameProvider::SupportsCppClassNamesAsObjectNames(), and v8::internal::value.
Referenced by cppgc::internal::HeapStatisticsCollector::VisitHeapObjectHeader().