v8::internal::anonymous_namespace{js-objects.cc} Namespace Reference
Functions
bool HasExcludedProperty (base::Vector< DirectHandle< Object >> excluded_properties, DirectHandle< Object > search_element)
V8_WARN_UNUSED_RESULT Maybe< bool > FastAssign (Isolate *isolate, DirectHandle< JSReceiver > target, DirectHandle< Object > source, PropertiesEnumerationMode mode, base::Vector< DirectHandle< Object >> excluded_properties, bool use_set)
std::pair< MaybeDirectHandle< JSFunction >, DirectHandle< String > > GetConstructorHelper (Isolate *isolate, DirectHandle< JSReceiver > receiver)
Tagged< Object > SetHashAndUpdateProperties (Tagged< HeapObject > properties, int hash)
int GetIdentityHashHelper (Tagged< JSReceiver > object)
MaybeHandle< JSAny > GetPropertyWithInterceptorInternal (LookupIterator *it, DirectHandle< InterceptorInfo > interceptor, bool *done)
Maybe< PropertyAttributes > GetPropertyAttributesWithInterceptorInternal (LookupIterator *it, DirectHandle< InterceptorInfo > interceptor)
Maybe< InterceptorResult > SetPropertyWithInterceptorInternal (LookupIterator *it, DirectHandle< InterceptorInfo > interceptor, Maybe< ShouldThrow > should_throw, DirectHandle< Object > value)
Maybe< InterceptorResult > DefinePropertyWithInterceptorInternal (LookupIterator *it, DirectHandle< InterceptorInfo > interceptor, Maybe< ShouldThrow > should_throw, PropertyDescriptor *desc)
Maybe< bool > GetPropertyDescriptorWithInterceptor (LookupIterator *it, PropertyDescriptor *desc)
Maybe< bool > GenericTestIntegrityLevel (Isolate *isolate, DirectHandle< JSReceiver > receiver, PropertyAttributes level)
void MigrateFastToFast (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< Map > new_map)
void MigrateFastToSlow (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< Map > new_map, int expected_additional_properties)
bool TryFastAddDataProperty (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< Name > name, DirectHandle< Object > value, PropertyAttributes attributes)
template<typename Dictionary >
bool TestDictionaryPropertiesIntegrityLevel (Tagged< Dictionary > dict, ReadOnlyRoots roots, PropertyAttributes level)
bool TestFastPropertiesIntegrityLevel (Tagged< Map > map, PropertyAttributes level)
bool TestPropertiesIntegrityLevel (Tagged< JSObject > object, PropertyAttributes level)
bool TestElementsIntegrityLevel (Isolate *isolate, Tagged< JSObject > object, PropertyAttributes level)
bool FastTestIntegrityLevel (Isolate *isolate, Tagged< JSObject > object, PropertyAttributes level)
void InvalidateOnePrototypeValidityCellInternal (Tagged< Map > map)
void InvalidatePrototypeChainsInternal (Tagged< Map > map)
Function Documentation
DefinePropertyWithInterceptorInternal()
Maybe<InterceptorResult> v8::internal::anonymous_namespace{js-objects.cc}::DefinePropertyWithInterceptorInternal (LookupIterator * it, DirectHandle< InterceptorInfo > interceptor, Maybe< ShouldThrow > should_throw, PropertyDescriptor * desc)
Definition at line 1322 of file js-objects.cc.
                                                               {
  Isolate* isolate = it->isolate();
  // Make sure that the top context does not change when doing callbacks or
  // interceptor calls.
  AssertNoContextChange ncc(isolate);
  if (!interceptor->has_definer()) {
    return Just(InterceptorResult::kNotIntercepted);
  }
  DirectHandle<JSObject> holder = it->GetHolder<JSObject>();
  DirectHandle<Object> receiver = it->GetReceiver();
  if (!IsJSReceiver(*receiver)) {
    ASSIGN_RETURN_ON_EXCEPTION_VALUE(isolate, receiver,
                                     Object::ConvertReceiver(isolate, receiver),
                                     Nothing<InterceptorResult>());
  }
  std::unique_ptr<v8::PropertyDescriptor> descriptor(
      new v8::PropertyDescriptor());
  if (PropertyDescriptor::IsAccessorDescriptor(desc)) {
    DirectHandle<Object> getter = desc->get();
    if (!getter.is_null() && IsFunctionTemplateInfo(*getter)) {
      ASSIGN_RETURN_ON_EXCEPTION_VALUE(
          isolate, getter,
          ApiNatives::InstantiateFunction(isolate,
                                          Cast<FunctionTemplateInfo>(getter),
                                          MaybeDirectHandle<Name>()),
          Nothing<InterceptorResult>());
    }
    DirectHandle<Object> setter = desc->set();
    if (!setter.is_null() && IsFunctionTemplateInfo(*setter)) {
      ASSIGN_RETURN_ON_EXCEPTION_VALUE(
          isolate, setter,
          ApiNatives::InstantiateFunction(isolate,
                                          Cast<FunctionTemplateInfo>(setter),
                                          MaybeDirectHandle<Name>()),
          Nothing<InterceptorResult>());
    }
    descriptor.reset(new v8::PropertyDescriptor(v8::Utils::ToLocal(getter),
                                                v8::Utils::ToLocal(setter)));
  } else if (PropertyDescriptor::IsDataDescriptor(desc)) {
    if (desc->has_writable()) {
      descriptor.reset(new v8::PropertyDescriptor(
          v8::Utils::ToLocal(desc->value()), desc->writable()));
    } else {
      descriptor.reset(
          new v8::PropertyDescriptor(v8::Utils::ToLocal(desc->value())));
    }
  }
  if (desc->has_enumerable()) {
    descriptor->set_enumerable(desc->enumerable());
  }
  if (desc->has_configurable()) {
    descriptor->set_configurable(desc->configurable());
  }
  PropertyCallbackArguments args(isolate, interceptor->data(), *receiver,
                                 *holder, should_throw);
  v8::Intercepted intercepted =
      it->IsElement(*holder)
          ? args.CallIndexedDefiner(interceptor, it->array_index(), *descriptor)
          : args.CallNamedDefiner(interceptor, it->name(), *descriptor);
  return args.GetBooleanReturnValue(intercepted, "Definer");
}
References v8::base::args, v8::internal::LookupIterator::array_index(), ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::PropertyDescriptor::configurable(), v8::internal::Object::ConvertReceiver(), v8::internal::PropertyDescriptor::enumerable(), v8::internal::PropertyDescriptor::get(), v8::internal::LookupIterator::GetHolder(), v8::internal::LookupIterator::GetReceiver(), v8::internal::PropertyDescriptor::has_configurable(), v8::internal::PropertyDescriptor::has_enumerable(), v8::internal::PropertyDescriptor::has_writable(), v8::internal::ApiNatives::InstantiateFunction(), v8::internal::DirectHandle< T >::is_null(), v8::internal::PropertyDescriptor::IsAccessorDescriptor(), v8::internal::PropertyDescriptor::IsDataDescriptor(), v8::internal::LookupIterator::IsElement(), v8::internal::LookupIterator::isolate(), v8::Just(), v8::internal::kNotIntercepted, v8::internal::LookupIterator::name(), v8::internal::PropertyDescriptor::set(), v8::internal::setter, v8::internal::PropertyDescriptor::value(), and v8::internal::PropertyDescriptor::writable().
Referenced by v8::internal::JSObject::DefineOwnPropertyIgnoreAttributes(), and v8::internal::JSReceiver::OrdinaryDefineOwnProperty().
FastAssign()
V8_WARN_UNUSED_RESULT Maybe<bool> v8::internal::anonymous_namespace{js-objects.cc}::FastAssign (Isolate * isolate, DirectHandle< JSReceiver > target, DirectHandle< Object > source, PropertiesEnumerationMode mode, base::Vector< DirectHandle< Object >> excluded_properties, bool use_set)
Definition at line 282 of file js-objects.cc.
                                                                        {
  // Non-empty strings are the only non-JSReceivers that need to be handled
  // explicitly by Object.assign.
  if (!IsJSReceiver(*source)) {
    return Just(!IsString(*source) || Cast<String>(*source)->length() == 0);
  }
  // If the target is deprecated, the object will be updated on first store. If
  // the source for that store equals the target, this will invalidate the
  // cached representation of the source. Preventively upgrade the target.
  // Do this on each iteration since any property load could cause deprecation.
  if (target->map()->is_deprecated()) {
    JSObject::MigrateInstance(isolate, Cast<JSObject>(target));
  }
  DirectHandle<Map> map(Cast<JSReceiver>(*source)->map(), isolate);
  if (!IsJSObjectMap(*map)) return Just(false);
  if (!map->OnlyHasSimpleProperties()) return Just(false);
  DirectHandle<JSObject> from = Cast<JSObject>(source);
  if (from->elements() != ReadOnlyRoots(isolate).empty_fixed_array()) {
    return Just(false);
  }
  // We should never try to copy properties from an object itself.
  CHECK_IMPLIES(!use_set, !target.is_identical_to(from));
  bool stable = true;
  // Process symbols last and only do that if we found symbols.
  bool has_symbol = false;
  bool process_symbol_only = false;
  while (true) {
    for (InternalIndex i : map->IterateOwnDescriptors()) {
      HandleScope inner_scope(isolate);
      // The descriptor array is not cached on purpose since it has to stay in
      // sync with map->instance_descriptors to avoid it from being pruned.
      DirectHandle<Name> next_key(map->instance_descriptors(isolate)->GetKey(i),
                                  isolate);
      if (mode == PropertiesEnumerationMode::kEnumerationOrder) {
        if (IsSymbol(*next_key)) {
          has_symbol = true;
          if (!process_symbol_only) continue;
        } else {
          if (process_symbol_only) continue;
        }
      }
      DirectHandle<Object> prop_value;
      // Directly decode from the descriptor array if |from| did not change
      // shape.
      if (stable) {
        DCHECK_EQ(from->map(), *map);
        PropertyDetails details =
            map->instance_descriptors(isolate)->GetDetails(i);
        if (!details.IsEnumerable()) continue;
        if (details.kind() == PropertyKind::kData) {
          CHECK_EQ(details.location(), PropertyLocation::kField);
          Representation representation = details.representation();
          FieldIndex index = FieldIndex::ForPropertyIndex(
              *map, details.field_index(), representation);
          prop_value =
              JSObject::FastPropertyAt(isolate, from, representation, index);
        } else {
          LookupIterator it(isolate, from, next_key,
                            LookupIterator::OWN_SKIP_INTERCEPTOR);
          ASSIGN_RETURN_ON_EXCEPTION_VALUE(
              isolate, prop_value, Object::GetProperty(&it), Nothing<bool>());
          stable = from->map() == *map;
        }
      } else {
        // If the map did change, do a slower lookup. We are still guaranteed
        // that the object has a simple shape, and that the key is a name.
        LookupIterator it(isolate, from, next_key, from,
                          LookupIterator::OWN_SKIP_INTERCEPTOR);
        if (!it.IsFound()) continue;
        DCHECK(it.state() == LookupIterator::DATA ||
               it.state() == LookupIterator::ACCESSOR);
        if (!it.IsEnumerable()) continue;
        ASSIGN_RETURN_ON_EXCEPTION_VALUE(
            isolate, prop_value, Object::GetProperty(&it), Nothing<bool>());
      }
      if (use_set) {
        // The lookup will walk the prototype chain, so we have to be careful
        // to treat any key correctly for any receiver/holder.
        PropertyKey key(isolate, next_key);
        LookupIterator it(isolate, target, key);
        Maybe<bool> result =
            Object::SetProperty(&it, prop_value, StoreOrigin::kNamed,
                                Just(ShouldThrow::kThrowOnError));
        if (result.IsNothing()) return result;
        if (stable) {
          stable = from->map() == *map;
        }
      } else {
        // No element indexes should get here or the exclusion check may
        // yield false negatives for type mismatch.
        if (!excluded_properties.empty() &&
            HasExcludedProperty(excluded_properties, next_key)) {
          continue;
        }
        // 4a ii 2. Perform ? CreateDataProperty(target, nextKey, propValue).
        // This is an OWN lookup, so constructing a named-mode LookupIterator
        // from {next_key} is safe.
        CHECK(JSReceiver::CreateDataProperty(isolate, target, next_key,
                                             prop_value, Just(kThrowOnError))
                  .FromJust());
      }
    }
    if (mode == PropertiesEnumerationMode::kEnumerationOrder) {
      if (process_symbol_only || !has_symbol) {
        return Just(true);
      }
      if (has_symbol) {
        process_symbol_only = true;
      }
    } else {
      DCHECK_EQ(mode, PropertiesEnumerationMode::kPropertyAdditionOrder);
      return Just(true);
    }
  }
  UNREACHABLE();
}
References v8::internal::LookupIterator::ACCESSOR, ASSIGN_RETURN_ON_EXCEPTION_VALUE, CHECK, CHECK_EQ, CHECK_IMPLIES, v8::internal::JSReceiver::CreateDataProperty(), v8::internal::LookupIterator::DATA, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::JSObject::FastPropertyAt(), v8::internal::PropertyDetails::field_index(), v8::internal::FieldIndex::ForPropertyIndex(), v8::internal::Object::GetProperty(), HasExcludedProperty(), v8::internal::index, v8::internal::DirectHandle< T >::is_identical_to(), v8::internal::LookupIterator::IsEnumerable(), v8::internal::PropertyDetails::IsEnumerable(), v8::internal::LookupIterator::IsFound(), v8::Just(), v8::internal::kData, v8::internal::kEnumerationOrder, v8::internal::key, v8::internal::kField, v8::internal::PropertyDetails::kind(), v8::internal::kNamed, v8::internal::kPropertyAdditionOrder, v8::internal::kThrowOnError, v8::internal::PropertyDetails::location(), v8::internal::JSObject::MigrateInstance(), mode(), v8::internal::LookupIterator::OWN_SKIP_INTERCEPTOR, v8::internal::PropertyDetails::representation(), v8::base::internal::result, v8::internal::Object::SetProperty(), v8::internal::LookupIterator::state(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::JSReceiver::SetOrCopyDataProperties().
FastTestIntegrityLevel()
bool v8::internal::anonymous_namespace{js-objects.cc}::FastTestIntegrityLevel (Isolate * isolate, Tagged< JSObject > object, PropertyAttributes level)
Definition at line 4278 of file js-objects.cc.
                                                      {
  DCHECK(!IsCustomElementsReceiverMap(object->map()));
  return !object->map()->is_extensible() &&
         TestElementsIntegrityLevel(isolate, object, level) &&
         TestPropertiesIntegrityLevel(object, level);
}
References v8::internal::DCHECK(), v8::internal::IsCustomElementsReceiverMap(), TestElementsIntegrityLevel(), and TestPropertiesIntegrityLevel().
Referenced by v8::internal::JSObject::PreventExtensionsWithTransition(), and v8::internal::JSObject::TestIntegrityLevel().
GenericTestIntegrityLevel()
Maybe<bool> v8::internal::anonymous_namespace{js-objects.cc}::GenericTestIntegrityLevel (Isolate * isolate, DirectHandle< JSReceiver > receiver, PropertyAttributes level)
Definition at line 2043 of file js-objects.cc.
                                                                {
  DCHECK(level == SEALED || level == FROZEN);
  Maybe<bool> extensible = JSReceiver::IsExtensible(isolate, receiver);
  MAYBE_RETURN(extensible, Nothing<bool>());
  if (extensible.FromJust()) return Just(false);
  DirectHandle<FixedArray> keys;
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, keys, JSReceiver::OwnPropertyKeys(isolate, receiver),
      Nothing<bool>());
  for (int i = 0; i < keys->length(); ++i) {
    DirectHandle<Object> key(keys->get(i), isolate);
    PropertyDescriptor current_desc;
    Maybe<bool> owned = JSReceiver::GetOwnPropertyDescriptor(
        isolate, receiver, key, &current_desc);
    MAYBE_RETURN(owned, Nothing<bool>());
    if (owned.FromJust()) {
      if (current_desc.configurable()) return Just(false);
      if (level == FROZEN &&
          PropertyDescriptor::IsDataDescriptor(&current_desc) &&
          current_desc.writable()) {
        return Just(false);
      }
    }
  }
  return Just(true);
}
References ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::PropertyDescriptor::configurable(), v8::internal::DCHECK(), v8::Maybe< T >::FromJust(), v8::internal::FROZEN, v8::internal::JSReceiver::GetOwnPropertyDescriptor(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::PropertyDescriptor::IsDataDescriptor(), v8::internal::JSReceiver::IsExtensible(), v8::Just(), v8::internal::key, MAYBE_RETURN, v8::internal::JSReceiver::OwnPropertyKeys(), v8::internal::SEALED, and v8::internal::PropertyDescriptor::writable().
Referenced by v8::internal::JSObject::TestIntegrityLevel(), and v8::internal::JSReceiver::TestIntegrityLevel().
GetConstructorHelper()
std::pair<MaybeDirectHandle<JSFunction>, DirectHandle<String> > v8::internal::anonymous_namespace{js-objects.cc}::GetConstructorHelper (Isolate * isolate, DirectHandle< JSReceiver > receiver)
Definition at line 562 of file js-objects.cc.
                                                                          {
  // If the object was instantiated simply with base == new.target, the
  // constructor on the map provides the most accurate name.
  // Don't provide the info for prototypes, since their constructors are
  // reclaimed and replaced by Object in OptimizeAsPrototype.
  if (!IsJSProxy(*receiver) && receiver->map()->new_target_is_base() &&
      !receiver->map()->is_prototype_map()) {
    DirectHandle<Object> maybe_constructor(receiver->map()->GetConstructor(),
                                           isolate);
    if (IsJSFunction(*maybe_constructor)) {
      DirectHandle<JSFunction> constructor =
          Cast<JSFunction>(maybe_constructor);
      Handle<String> name = SharedFunctionInfo::DebugName(
          isolate, direct_handle(constructor->shared(), isolate));
      if (name->length() != 0 &&
          !name->Equals(ReadOnlyRoots(isolate).Object_string())) {
        return std::make_pair(indirect_handle(constructor, isolate), name);
      }
    } else if (IsFunctionTemplateInfo(*maybe_constructor)) {
      DirectHandle<FunctionTemplateInfo> function_template =
          Cast<FunctionTemplateInfo>(maybe_constructor);
      if (!IsUndefined(function_template->class_name(), isolate)) {
        return std::make_pair(
            MaybeHandle<JSFunction>(),
            handle(Cast<String>(function_template->class_name()), isolate));
      }
    }
  }
  for (PrototypeIterator it(isolate, receiver, kStartAtReceiver); !it.IsAtEnd();
       it.AdvanceIgnoringProxies()) {
    auto current = PrototypeIterator::GetCurrent<JSReceiver>(it);
    LookupIterator it_to_string_tag(
        isolate, receiver, isolate->factory()->to_string_tag_symbol(), current,
        LookupIterator::OWN_SKIP_INTERCEPTOR);
    auto maybe_to_string_tag = JSReceiver::GetDataProperty(
        &it_to_string_tag, AllocationPolicy::kAllocationDisallowed);
    if (IsString(*maybe_to_string_tag)) {
      return std::make_pair(MaybeHandle<JSFunction>(),
                            Cast<String>(maybe_to_string_tag));
    }
    // Consider the following example:
    //
    // function A() {}
    // function B() {}
    // B.prototype = new A();
    // B.prototype.constructor = B;
    //
    // The constructor name for `B.prototype` must yield "A", so we don't take
    // "constructor" into account for the receiver itself, but only starting
    // on the prototype chain.
    if (!receiver.is_identical_to(current)) {
      LookupIterator it_constructor(
          isolate, receiver, isolate->factory()->constructor_string(), current,
          LookupIterator::OWN_SKIP_INTERCEPTOR);
      auto maybe_constructor = JSReceiver::GetDataProperty(
          &it_constructor, AllocationPolicy::kAllocationDisallowed);
      if (IsJSFunction(*maybe_constructor)) {
        auto constructor = Cast<JSFunction>(maybe_constructor);
        auto name = SharedFunctionInfo::DebugName(
            isolate, direct_handle(constructor->shared(), isolate));
        if (name->length() != 0 &&
            !name->Equals(ReadOnlyRoots(isolate).Object_string())) {
          return std::make_pair(constructor, name);
        }
      }
    }
  }
  return std::make_pair(MaybeHandle<JSFunction>(),
                        handle(receiver->class_name(), isolate));
}
References v8::internal::SharedFunctionInfo::DebugName(), v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::JSReceiver::GetDataProperty(), v8::internal::handle(), v8::internal::indirect_handle(), v8::internal::DirectHandle< T >::is_identical_to(), v8::internal::PrototypeIterator::IsAtEnd(), v8::internal::kAllocationDisallowed, v8::internal::kStartAtReceiver, v8::internal::name, and v8::internal::LookupIterator::OWN_SKIP_INTERCEPTOR.
Referenced by v8::internal::JSReceiver::GetConstructor(), and v8::internal::JSReceiver::GetConstructorName().
GetIdentityHashHelper()
int v8::internal::anonymous_namespace{js-objects.cc}::GetIdentityHashHelper (Tagged< JSReceiver > object)
Definition at line 782 of file js-objects.cc.
                                                     {
  DisallowGarbageCollection no_gc;
  Tagged<Object> properties = object->raw_properties_or_hash();
  if (IsSmi(properties)) {
    return Smi::ToInt(properties);
  }
  if (IsPropertyArray(properties)) {
    return Cast<PropertyArray>(properties)->Hash();
  }
  if (IsPropertyDictionary(properties)) {
    return Cast<PropertyDictionary>(properties)->Hash();
  }
  if (IsGlobalDictionary(properties)) {
    return Cast<GlobalDictionary>(properties)->Hash();
  }
#ifdef DEBUG
  ReadOnlyRoots roots = GetReadOnlyRoots();
  DCHECK(properties == roots.empty_fixed_array() ||
         properties == roots.empty_property_dictionary() ||
         properties == roots.empty_swiss_property_dictionary());
#endif
  return PropertyArray::kNoHashSentinel;
}
References v8::internal::DCHECK(), v8::internal::GetReadOnlyRoots(), v8::internal::InstanceTypeChecker::IsPropertyDictionary(), v8::internal::IsSmi(), v8::internal::PropertyArray::kNoHashSentinel, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::Smi::ToInt().
Referenced by v8::internal::JSReceiver::GetIdentityHash(), v8::internal::JSReceiver::GetOrCreateIdentityHash(), and v8::internal::JSReceiver::SetProperties().
GetPropertyAttributesWithInterceptorInternal()
Maybe<PropertyAttributes> v8::internal::anonymous_namespace{js-objects.cc}::GetPropertyAttributesWithInterceptorInternal (LookupIterator * it, DirectHandle< InterceptorInfo > interceptor)
Definition at line 1229 of file js-objects.cc.
                                                                   {
  Isolate* isolate = it->isolate();
  // Make sure that the top context does not change when doing
  // callbacks or interceptor calls.
  AssertNoContextChange ncc(isolate);
  HandleScope scope(isolate);
  DirectHandle<JSObject> holder = it->GetHolder<JSObject>();
  DCHECK_IMPLIES(!it->IsElement(*holder) && IsSymbol(*it->name()),
                 interceptor->can_intercept_symbols());
  DirectHandle<Object> receiver = it->GetReceiver();
  if (!IsJSReceiver(*receiver)) {
    ASSIGN_RETURN_ON_EXCEPTION_VALUE(isolate, receiver,
                                     Object::ConvertReceiver(isolate, receiver),
                                     Nothing<PropertyAttributes>());
  }
  PropertyCallbackArguments args(isolate, interceptor->data(), *receiver,
                                 *holder, Just(kDontThrow));
  if (interceptor->has_query()) {
    DirectHandle<Object> result;
    if (it->IsElement(*holder)) {
      result = args.CallIndexedQuery(interceptor, it->array_index());
    } else {
      result = args.CallNamedQuery(interceptor, it->name());
    }
    // An exception was thrown in the interceptor. Propagate.
    RETURN_VALUE_IF_EXCEPTION_DETECTOR(isolate, args,
                                       Nothing<PropertyAttributes>());
    if (!result.is_null()) {
      int32_t value;
      CHECK(Object::ToInt32(*result, &value));
      DCHECK_IMPLIES((value & ~PropertyAttributes::ALL_ATTRIBUTES_MASK) != 0,
                     value == PropertyAttributes::ABSENT);
      // In case of absent property side effects are not allowed.
      // TODO(ishell): PropertyAttributes::ABSENT is not exposed in the Api,
      // so it can't be officially returned. We should fix the tests instead.
      if (value != PropertyAttributes::ABSENT) {
        args.AcceptSideEffects();
      }
      return Just(static_cast<PropertyAttributes>(value));
    }
  } else if (interceptor->has_getter()) {
    // TODO(verwaest): Use GetPropertyWithInterceptor?
    DirectHandle<Object> result;
    if (it->IsElement(*holder)) {
      result = args.CallIndexedGetter(interceptor, it->array_index());
    } else {
      result = args.CallNamedGetter(interceptor, it->name());
    }
    // An exception was thrown in the interceptor. Propagate.
    RETURN_VALUE_IF_EXCEPTION_DETECTOR(isolate, args,
                                       Nothing<PropertyAttributes>());
    if (!result.is_null()) {
      args.AcceptSideEffects();
      return Just(DONT_ENUM);
    }
  }
  return Just(ABSENT);
}
References v8::internal::ABSENT, v8::internal::ALL_ATTRIBUTES_MASK, v8::base::args, v8::internal::LookupIterator::array_index(), ASSIGN_RETURN_ON_EXCEPTION_VALUE, CHECK, v8::internal::Object::ConvertReceiver(), DCHECK_IMPLIES, v8::internal::DONT_ENUM, v8::internal::LookupIterator::GetHolder(), v8::internal::LookupIterator::GetReceiver(), v8::internal::LookupIterator::IsElement(), v8::internal::LookupIterator::isolate(), v8::Just(), v8::internal::kDontThrow, v8::internal::LookupIterator::name(), v8::base::internal::result, RETURN_VALUE_IF_EXCEPTION_DETECTOR, v8::internal::Object::ToInt32(), and v8::internal::value.
Referenced by v8::internal::JSObject::GetPropertyAttributesWithFailedAccessCheck(), and v8::internal::JSObject::GetPropertyAttributesWithInterceptor().
GetPropertyDescriptorWithInterceptor()
Maybe<bool> v8::internal::anonymous_namespace{js-objects.cc}::GetPropertyDescriptorWithInterceptor (LookupIterator * it, PropertyDescriptor * desc)
Definition at line 1844 of file js-objects.cc.
                                                                           {
  DirectHandle<InterceptorInfo> interceptor;
  while (it->state() == LookupIterator::ACCESS_CHECK) {
    if (it->HasAccess()) {
      it->Next();
    } else {
      interceptor = it->GetInterceptorForFailedAccessCheck();
      if (interceptor.is_null()) {
        it->Restart();
        return Just(false);
      }
      CHECK(!interceptor.is_null());
      break;
    }
  }
  if (it->state() == LookupIterator::INTERCEPTOR) {
    interceptor = it->GetInterceptor();
  }
  if (interceptor.is_null()) return Just(false);
  Isolate* isolate = it->isolate();
  if (!interceptor->has_descriptor()) return Just(false);
  Handle<JSAny> result;
  DirectHandle<JSObject> holder = it->GetHolder<JSObject>();
  DirectHandle<Object> receiver = it->GetReceiver();
  if (!IsJSReceiver(*receiver)) {
    ASSIGN_RETURN_ON_EXCEPTION_VALUE(isolate, receiver,
                                     Object::ConvertReceiver(isolate, receiver),
                                     Nothing<bool>());
  }
  PropertyCallbackArguments args(isolate, interceptor->data(), *receiver,
                                 *holder, Just(kDontThrow));
  if (it->IsElement(*holder)) {
    result = args.CallIndexedDescriptor(interceptor, it->array_index());
  } else {
    result = args.CallNamedDescriptor(interceptor, it->name());
  }
  // An exception was thrown in the interceptor. Propagate.
  RETURN_VALUE_IF_EXCEPTION_DETECTOR(isolate, args, Nothing<bool>());
  if (!result.is_null()) {
    // Request was successfully intercepted, try to set the property
    // descriptor.
    args.AcceptSideEffects();
    Utils::ApiCheck(
        PropertyDescriptor::ToPropertyDescriptor(isolate, result, desc),
        it->IsElement(*holder) ? "v8::IndexedPropertyDescriptorCallback"
                               : "v8::NamedPropertyDescriptorCallback",
        "Invalid property descriptor.");
    return Just(true);
  }
  it->Next();
  return Just(false);
}
References v8::internal::LookupIterator::ACCESS_CHECK, v8::Utils::ApiCheck(), v8::base::args, v8::internal::LookupIterator::array_index(), ASSIGN_RETURN_ON_EXCEPTION_VALUE, CHECK, v8::internal::Object::ConvertReceiver(), v8::internal::LookupIterator::GetHolder(), v8::internal::LookupIterator::GetInterceptor(), v8::internal::LookupIterator::GetInterceptorForFailedAccessCheck(), v8::internal::LookupIterator::GetReceiver(), v8::internal::LookupIterator::HasAccess(), v8::internal::LookupIterator::INTERCEPTOR, v8::internal::DirectHandle< T >::is_null(), v8::internal::LookupIterator::IsElement(), v8::internal::LookupIterator::isolate(), v8::Just(), v8::internal::kDontThrow, v8::internal::LookupIterator::name(), v8::internal::LookupIterator::Next(), v8::internal::LookupIterator::Restart(), v8::base::internal::result, RETURN_VALUE_IF_EXCEPTION_DETECTOR, v8::internal::LookupIterator::state(), and v8::internal::PropertyDescriptor::ToPropertyDescriptor().
Referenced by v8::internal::JSReceiver::GetOwnPropertyDescriptor().
GetPropertyWithInterceptorInternal()
MaybeHandle<JSAny> v8::internal::anonymous_namespace{js-objects.cc}::GetPropertyWithInterceptorInternal (LookupIterator * it, DirectHandle< InterceptorInfo > interceptor, bool * done)
Definition at line 1193 of file js-objects.cc.
                                                                               {
  *done = false;
  Isolate* isolate = it->isolate();
  // Make sure that the top context does not change when doing callbacks or
  // interceptor calls.
  AssertNoContextChange ncc(isolate);
  if (!interceptor->has_getter()) {
    return isolate->factory()->undefined_value();
  }
  DirectHandle<JSObject> holder = it->GetHolder<JSObject>();
  DirectHandle<JSAny> result;
  DirectHandle<Object> receiver = it->GetReceiver();
  if (!IsJSReceiver(*receiver)) {
    ASSIGN_RETURN_ON_EXCEPTION(isolate, receiver,
                               Object::ConvertReceiver(isolate, receiver));
  }
  PropertyCallbackArguments args(isolate, interceptor->data(), *receiver,
                                 *holder, Just(kDontThrow));
  if (it->IsElement(*holder)) {
    result = args.CallIndexedGetter(interceptor, it->array_index());
  } else {
    result = args.CallNamedGetter(interceptor, it->name());
  }
  // An exception was thrown in the interceptor. Propagate.
  RETURN_VALUE_IF_EXCEPTION_DETECTOR(isolate, args, kNullMaybeHandle);
  if (result.is_null()) return isolate->factory()->undefined_value();
  *done = true;
  args.AcceptSideEffects();
  // Rebox handle before return
  return handle(*result, isolate);
}
References v8::base::args, v8::internal::LookupIterator::array_index(), ASSIGN_RETURN_ON_EXCEPTION, v8::internal::Object::ConvertReceiver(), v8::internal::Isolate::factory(), v8::internal::LookupIterator::GetHolder(), v8::internal::LookupIterator::GetReceiver(), v8::internal::handle(), v8::internal::LookupIterator::IsElement(), v8::internal::LookupIterator::isolate(), v8::Just(), v8::internal::kDontThrow, v8::internal::kNullMaybeHandle, v8::internal::LookupIterator::name(), v8::base::internal::result, and RETURN_VALUE_IF_EXCEPTION_DETECTOR.
Referenced by v8::internal::JSObject::GetPropertyWithFailedAccessCheck(), and v8::internal::JSObject::GetPropertyWithInterceptor().
HasExcludedProperty()
bool v8::internal::anonymous_namespace{js-objects.cc}::HasExcludedProperty (base::Vector< DirectHandle< Object >> excluded_properties, DirectHandle< Object > search_element)
Definition at line 267 of file js-objects.cc.
                                                              {
  // TODO(gsathya): Change this to be a hashtable.
  for (DirectHandle<Object> object : excluded_properties) {
    if (Object::SameValue(*search_element, *object)) {
      return true;
    }
  }
  return false;
}
References v8::internal::Object::SameValue().
Referenced by FastAssign(), and v8::internal::JSReceiver::SetOrCopyDataProperties().
InvalidateOnePrototypeValidityCellInternal()
void v8::internal::anonymous_namespace{js-objects.cc}::InvalidateOnePrototypeValidityCellInternal (Tagged< Map > map)
Definition at line 5155 of file js-objects.cc.
                                                                 {
  DCHECK(map->is_prototype_map());
  if (v8_flags.trace_prototype_users) {
    PrintF("Invalidating prototype map %p 's cell\n",
           reinterpret_cast<void*>(map.ptr()));
  }
  Tagged<Object> maybe_cell = map->prototype_validity_cell(kRelaxedLoad);
  if (IsCell(maybe_cell)) {
    // Just set the value; the cell will be replaced lazily.
    Tagged<Cell> cell = Cast<Cell>(maybe_cell);
    Tagged<Smi> invalid_value = Smi::FromInt(Map::kPrototypeChainInvalid);
    if (cell->value() != invalid_value) {
      cell->set_value(invalid_value, SKIP_WRITE_BARRIER);
    }
  }
  Tagged<PrototypeInfo> prototype_info;
  if (map->TryGetPrototypeInfo(&prototype_info)) {
    prototype_info->set_prototype_chain_enum_cache(Smi::zero());
    // Previously created non-existent data handlers might no longer be valid,
    // ensure they are re-created if necessary.
    for (int i = 0; i < PrototypeInfo::kCachedHandlerCount; i++) {
      prototype_info->set_cached_handler(i, Smi::zero(), SKIP_WRITE_BARRIER);
    }
  }
  // We may inline accesses to constants stored in dictionary mode prototypes in
  // optimized code. When doing so, we install dependencies of group
  // |kPrototypeCheckGroup| on each prototype between the receiver's immediate
  // prototype and the holder of the constant property. This dependency is used
  // both to detect changes to the constant value itself, and other changes to
  // the prototype chain that invalidate the access to the given property from
  // the given receiver (like adding the property to another prototype between
  // the receiver and the (previous) holder). This works by de-opting this group
  // whenever the validity cell would be invalidated. However, the actual value
  // of the validity cell is not used. Therefore, we always trigger the de-opt
  // here, even if the cell was already invalid.
  if (V8_DICT_PROPERTY_CONST_TRACKING_BOOL && map->is_dictionary_map()) {
    // TODO(11527): pass Isolate as an argument.
    Isolate* isolate = GetIsolateFromWritableObject(map);
    DependentCode::DeoptimizeDependencyGroups(
        isolate, map, DependentCode::kPrototypeCheckGroup);
  }
}
References v8::internal::DCHECK(), v8::internal::DependentCode::DeoptimizeDependencyGroups(), v8::internal::Smi::FromInt(), v8::internal::GetIsolateFromWritableObject(), v8::internal::PrototypeInfo::kCachedHandlerCount, v8::internal::Map::kPrototypeChainInvalid, v8::internal::DependentCode::kPrototypeCheckGroup, v8::kRelaxedLoad, v8::internal::PrintF(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), v8::internal::SKIP_WRITE_BARRIER, V8_DICT_PROPERTY_CONST_TRACKING_BOOL, v8::internal::v8_flags, and v8::internal::Smi::zero().
Referenced by InvalidatePrototypeChainsInternal(), and v8::internal::JSObject::InvalidatePrototypeValidityCell().
InvalidatePrototypeChainsInternal()
void v8::internal::anonymous_namespace{js-objects.cc}::InvalidatePrototypeChainsInternal (Tagged< Map > map)
Definition at line 5199 of file js-objects.cc.
                                                        {
  // We handle linear prototype chains by looping, and multiple children
  // by recursion, in order to reduce the likelihood of running into stack
  // overflows. So, conceptually, the outer loop iterates the depth of the
  // prototype tree, and the inner loop iterates the breadth of a node.
  Tagged<Map> next_map;
  for (; !map.is_null(); map = next_map, next_map = Map()) {
    InvalidateOnePrototypeValidityCellInternal(map);
    Tagged<PrototypeInfo> proto_info;
    if (!map->TryGetPrototypeInfo(&proto_info)) return;
    if (!IsWeakArrayList(proto_info->prototype_users())) {
      return;
    }
    Tagged<WeakArrayList> prototype_users =
        Cast<WeakArrayList>(proto_info->prototype_users());
    // For now, only maps register themselves as users.
    for (int i = PrototypeUsers::kFirstIndex; i < prototype_users->length();
         ++i) {
      Tagged<HeapObject> heap_object;
      if (prototype_users->Get(i).GetHeapObjectIfWeak(&heap_object) &&
          IsMap(heap_object)) {
        // Walk the prototype chain (backwards, towards leaf objects) if
        // necessary.
        if (next_map.is_null()) {
          next_map = Cast<Map>(heap_object);
        } else {
          InvalidatePrototypeChainsInternal(Cast<Map>(heap_object));
        }
      }
    }
  }
}
References v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectIfWeak(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, InvalidateOnePrototypeValidityCellInternal(), v8::internal::Tagged< HeapObject >::is_null(), v8::internal::PrototypeUsers::kFirstIndex, and v8::internal::compiler::Map.
Referenced by v8::internal::JSObject::InvalidatePrototypeChains().
MigrateFastToFast()
void v8::internal::anonymous_namespace{js-objects.cc}::MigrateFastToFast (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< Map > new_map)
Definition at line 3118 of file js-objects.cc.
                                                  {
  DirectHandle<Map> old_map(object->map(), isolate);
  // In case of a regular transition.
  if (new_map->GetBackPointer(isolate) == *old_map) {
    // If the map does not add named properties, simply set the map.
    if (old_map->NumberOfOwnDescriptors() ==
        new_map->NumberOfOwnDescriptors()) {
      object->set_map(isolate, *new_map, kReleaseStore);
      return;
    }
    // If the map adds a new kDescriptor property, simply set the map.
    PropertyDetails details = new_map->GetLastDescriptorDetails(isolate);
    if (details.location() == PropertyLocation::kDescriptor) {
      object->set_map(isolate, *new_map, kReleaseStore);
      return;
    }
    // Check if we still have space in the {object}, in which case we
    // can also simply set the map (modulo a special case for mutable
    // double boxes).
    FieldIndex index = FieldIndex::ForDetails(*new_map, details);
    if (index.is_inobject() || index.outobject_array_index() <
                                   object->property_array(isolate)->length()) {
      // Allocate HeapNumbers for double fields.
      if (index.is_double()) {
        auto value = isolate->factory()->NewHeapNumberWithHoleNaN();
        object->FastPropertyAtPut(index, *value);
      }
      object->set_map(isolate, *new_map, kReleaseStore);
      return;
    }
    // This migration is a transition from a map that has run out of property
    // space. Extend the backing store.
    int grow_by = new_map->UnusedPropertyFields() + 1;
    DirectHandle<PropertyArray> old_storage(object->property_array(isolate),
                                            isolate);
    DirectHandle<PropertyArray> new_storage =
        isolate->factory()->CopyPropertyArrayAndGrow(old_storage, grow_by);
    // Properly initialize newly added property.
    DirectHandle<Object> value;
    if (details.representation().IsDouble()) {
      value = isolate->factory()->NewHeapNumberWithHoleNaN();
    } else {
      value = isolate->factory()->uninitialized_value();
    }
    DCHECK_EQ(PropertyLocation::kField, details.location());
    DCHECK_EQ(PropertyKind::kData, details.kind());
    DCHECK(!index.is_inobject()); // Must be a backing store index.
    new_storage->set(index.outobject_array_index(), *value);
    // From here on we cannot fail and we shouldn't GC anymore.
    DisallowGarbageCollection no_gc;
    // Set the new property value and do the map transition.
    object->SetProperties(*new_storage);
    object->set_map(isolate, *new_map, kReleaseStore);
    return;
  }
  int old_number_of_fields;
  int number_of_fields = new_map->NumberOfFields(ConcurrencyMode::kSynchronous);
  int inobject = new_map->GetInObjectProperties();
  int unused = new_map->UnusedPropertyFields();
  // Nothing to do if no functions were converted to fields and no smis were
  // converted to doubles.
  if (!old_map->InstancesNeedRewriting(*new_map, number_of_fields, inobject,
                                       unused, &old_number_of_fields,
                                       ConcurrencyMode::kSynchronous)) {
    object->set_map(isolate, *new_map, kReleaseStore);
    return;
  }
  int total_size = number_of_fields + unused;
  int external = total_size - inobject;
  DirectHandle<PropertyArray> array =
      isolate->factory()->NewPropertyArray(external);
  // We use this array to temporarily store the inobject properties.
  DirectHandle<FixedArray> inobject_props =
      isolate->factory()->NewFixedArray(inobject);
  DirectHandle<DescriptorArray> old_descriptors(
      old_map->instance_descriptors(isolate), isolate);
  DirectHandle<DescriptorArray> new_descriptors(
      new_map->instance_descriptors(isolate), isolate);
  int old_nof = old_map->NumberOfOwnDescriptors();
  int new_nof = new_map->NumberOfOwnDescriptors();
  // This method only supports generalizing instances to at least the same
  // number of properties.
  DCHECK(old_nof <= new_nof);
  for (InternalIndex i : InternalIndex::Range(old_nof)) {
    PropertyDetails details = new_descriptors->GetDetails(i);
    if (details.location() != PropertyLocation::kField) continue;
    DCHECK_EQ(PropertyKind::kData, details.kind());
    PropertyDetails old_details = old_descriptors->GetDetails(i);
    Representation old_representation = old_details.representation();
    Representation representation = details.representation();
    Handle<UnionOf<JSAny, Hole>> value;
    if (old_details.location() == PropertyLocation::kDescriptor) {
      if (old_details.kind() == PropertyKind::kAccessor) {
        // In case of kAccessor -> kData property reconfiguration, the property
        // must already be prepared for data of certain type.
        DCHECK(!details.representation().IsNone());
        if (details.representation().IsDouble()) {
          value = isolate->factory()->NewHeapNumberWithHoleNaN();
        } else {
          value = isolate->factory()->uninitialized_value();
        }
      } else {
        DCHECK_EQ(PropertyKind::kData, old_details.kind());
        value = handle(Cast<JSAny>(old_descriptors->GetStrongValue(isolate, i)),
                       isolate);
        DCHECK(!old_representation.IsDouble() && !representation.IsDouble());
      }
    } else {
      DCHECK_EQ(PropertyLocation::kField, old_details.location());
      FieldIndex index = FieldIndex::ForDetails(*old_map, old_details);
      value = handle(object->RawFastPropertyAt(isolate, index), isolate);
      if (!old_representation.IsDouble() && representation.IsDouble()) {
        DCHECK_IMPLIES(old_representation.IsNone(),
                       IsUninitialized(*value, isolate));
        value = Object::NewStorageFor(isolate, value, representation);
      } else if (old_representation.IsDouble() && !representation.IsDouble()) {
        value = Object::WrapForRead(isolate, Cast<JSAny>(value),
                                    old_representation);
      }
    }
    DCHECK(!(representation.IsDouble() && IsSmi(*value)));
    int target_index = new_descriptors->GetFieldIndex(i);
    if (target_index < inobject) {
      inobject_props->set(target_index, *value);
    } else {
      array->set(target_index - inobject, *value);
    }
  }
  for (InternalIndex i : InternalIndex::Range(old_nof, new_nof)) {
    PropertyDetails details = new_descriptors->GetDetails(i);
    if (details.location() != PropertyLocation::kField) continue;
    DCHECK_EQ(PropertyKind::kData, details.kind());
    DirectHandle<Object> value;
    if (details.representation().IsDouble()) {
      value = isolate->factory()->NewHeapNumberWithHoleNaN();
    } else {
      value = isolate->factory()->uninitialized_value();
    }
    int target_index = new_descriptors->GetFieldIndex(i);
    if (target_index < inobject) {
      inobject_props->set(target_index, *value);
    } else {
      array->set(target_index - inobject, *value);
    }
  }
  // From here on we cannot fail and we shouldn't GC anymore.
  DisallowGarbageCollection no_gc;
  Heap* heap = isolate->heap();
  // Copy (real) inobject properties. If necessary, stop at number_of_fields to
  // avoid overwriting |one_pointer_filler_map|.
  int limit = std::min(inobject, number_of_fields);
  for (int i = 0; i < limit; i++) {
    FieldIndex index = FieldIndex::ForPropertyIndex(*new_map, i);
    Tagged<Object> value = inobject_props->get(i);
    object->FastPropertyAtPut(index, value);
  }
  object->SetProperties(*array);
  // Create filler object past the new instance size.
  int old_instance_size = old_map->instance_size();
  int new_instance_size = new_map->instance_size();
  int instance_size_delta = old_instance_size - new_instance_size;
  DCHECK_GE(instance_size_delta, 0);
  if (instance_size_delta > 0) {
    heap->NotifyObjectSizeChange(*object, old_instance_size, new_instance_size,
                                 ClearRecordedSlots::kYes);
  }
  // We are storing the new map using release store after creating a filler for
  // the left-over space to avoid races with the sweeper thread.
  object->set_map(isolate, *new_map, kReleaseStore);
}
References v8::internal::Factory::CopyPropertyArrayAndGrow(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GE, DCHECK_IMPLIES, v8::internal::Isolate::factory(), v8::internal::FieldIndex::ForDetails(), v8::internal::FieldIndex::ForPropertyIndex(), v8::internal::handle(), v8::internal::Isolate::heap(), v8::internal::index, v8::internal::Representation::IsDouble(), v8::internal::Representation::IsNone(), v8::internal::IsSmi(), v8::internal::kAccessor, v8::internal::kData, v8::internal::kDescriptor, v8::internal::kField, v8::internal::PropertyDetails::kind(), v8::kReleaseStore, v8::internal::kSynchronous, v8::internal::kYes, v8::internal::PropertyDetails::location(), v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::FactoryBase< Impl >::NewHeapNumberWithHoleNaN(), v8::internal::Factory::NewPropertyArray(), v8::internal::Object::NewStorageFor(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::PropertyDetails::representation(), v8::internal::value, and v8::internal::Object::WrapForRead().
Referenced by v8::internal::JSObject::MigrateToMap().
MigrateFastToSlow()
void v8::internal::anonymous_namespace{js-objects.cc}::MigrateFastToSlow (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< Map > new_map, int expected_additional_properties)
Definition at line 3311 of file js-objects.cc.
                                                           {
  // The global object is always normalized.
  DCHECK(!IsJSGlobalObject(*object, isolate));
  // JSGlobalProxy must never be normalized
  DCHECK(!IsJSGlobalProxy(*object, isolate));
  DCHECK_IMPLIES(new_map->is_prototype_map(),
                 Map::IsPrototypeChainInvalidated(*new_map));
  HandleScope scope(isolate);
  DirectHandle<Map> map(object->map(isolate), isolate);
  // Allocate new content.
  int real_size = map->NumberOfOwnDescriptors();
  int property_count = real_size;
  if (expected_additional_properties > 0) {
    property_count += expected_additional_properties;
  } else {
    // Make space for two more properties.
    constexpr int initial_capacity = PropertyDictionary::kInitialCapacity;
    property_count += initial_capacity;
  }
  DirectHandle<NameDictionary> dictionary;
  DirectHandle<SwissNameDictionary> ord_dictionary;
  if constexpr (V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
    ord_dictionary = isolate->factory()->NewSwissNameDictionary(property_count);
  } else {
    dictionary = isolate->factory()->NewNameDictionary(property_count);
  }
  DirectHandle<DescriptorArray> descs(map->instance_descriptors(isolate),
                                      isolate);
  for (InternalIndex i : InternalIndex::Range(real_size)) {
    PropertyDetails details = descs->GetDetails(i);
    DirectHandle<Name> key(descs->GetKey(isolate, i), isolate);
    DirectHandle<Object> value;
    if (details.location() == PropertyLocation::kField) {
      FieldIndex index = FieldIndex::ForDetails(*map, details);
      if (details.kind() == PropertyKind::kData) {
        value =
            direct_handle(object->RawFastPropertyAt(isolate, index), isolate);
        if (details.representation().IsDouble()) {
          DCHECK(IsHeapNumber(*value, isolate));
          double old_value = Cast<HeapNumber>(value)->value();
          value = isolate->factory()->NewHeapNumber(old_value);
        }
      } else {
        DCHECK_EQ(PropertyKind::kAccessor, details.kind());
        value =
            direct_handle(object->RawFastPropertyAt(isolate, index), isolate);
      }
    } else {
      DCHECK_EQ(PropertyLocation::kDescriptor, details.location());
      value = direct_handle(descs->GetStrongValue(isolate, i), isolate);
    }
    DCHECK(!value.is_null());
    PropertyConstness constness = V8_DICT_PROPERTY_CONST_TRACKING_BOOL
                                      ? details.constness()
                                      : PropertyConstness::kMutable;
    PropertyDetails d(details.kind(), details.attributes(), constness);
    if constexpr (V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
      ord_dictionary =
          SwissNameDictionary::Add(isolate, ord_dictionary, key, value, d);
    } else {
      dictionary = NameDictionary::Add(isolate, dictionary, key, value, d);
    }
  }
  if constexpr (!V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
    // Copy the next enumeration index from instance descriptor.
    dictionary->set_next_enumeration_index(real_size + 1);
    // TODO(pthier): Add flags to swiss dictionaries.
    dictionary->set_may_have_interesting_properties(
        map->may_have_interesting_properties());
  }
  // From here on we cannot fail and we shouldn't GC anymore.
  DisallowGarbageCollection no_gc;
  Heap* heap = isolate->heap();
  // Resize the object in the heap if necessary.
  int old_instance_size = map->instance_size();
  int new_instance_size = new_map->instance_size();
  int instance_size_delta = old_instance_size - new_instance_size;
  DCHECK_GE(instance_size_delta, 0);
  if (instance_size_delta > 0) {
    heap->NotifyObjectSizeChange(*object, old_instance_size, new_instance_size,
                                 ClearRecordedSlots::kYes);
  }
  // We are storing the new map using release store after creating a filler for
  // the left-over space to avoid races with the sweeper thread.
  object->set_map(isolate, *new_map, kReleaseStore);
  if constexpr (V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
    object->SetProperties(*ord_dictionary);
  } else {
    object->SetProperties(*dictionary);
  }
  // Ensure that in-object space of slow-mode object does not contain random
  // garbage.
  int inobject_properties = new_map->GetInObjectProperties();
  if (inobject_properties) {
    for (int i = 0; i < inobject_properties; i++) {
      FieldIndex index = FieldIndex::ForPropertyIndex(*new_map, i);
      object->FastPropertyAtPut(index, Smi::zero());
    }
  }
#ifdef DEBUG
  if (v8_flags.trace_normalization) {
    StdoutStream os;
    os << "Object properties have been normalized:\n";
    Print(*object, os);
  }
#endif
}
References v8::bigint::Add(), v8::internal::PropertyDetails::attributes(), v8::internal::PropertyDetails::constness(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GE, DCHECK_IMPLIES, v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::FieldIndex::ForDetails(), v8::internal::FieldIndex::ForPropertyIndex(), v8::internal::Isolate::heap(), v8::internal::index, v8::internal::Representation::IsDouble(), v8::internal::Map::IsPrototypeChainInvalidated(), v8::internal::kAccessor, v8::internal::kData, v8::internal::kDescriptor, v8::internal::key, v8::internal::kField, v8::internal::PropertyDetails::kind(), v8::internal::NameDictionary::kInitialCapacity, v8::internal::kMutable, v8::kReleaseStore, v8::internal::kYes, v8::internal::PropertyDetails::location(), v8::internal::FactoryBase< Impl >::NewHeapNumber(), v8::internal::Factory::NewNameDictionary(), v8::internal::FactoryBase< Impl >::NewSwissNameDictionary(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Print(), v8::internal::PropertyDetails::representation(), V8_DICT_PROPERTY_CONST_TRACKING_BOOL, V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL, v8::internal::v8_flags, v8::internal::value, and v8::internal::Smi::zero().
Referenced by v8::internal::JSObject::MigrateToMap().
SetHashAndUpdateProperties()
Tagged<Object> v8::internal::anonymous_namespace{js-objects.cc}::SetHashAndUpdateProperties (Tagged< HeapObject > properties, int hash)
Definition at line 752 of file js-objects.cc.
                                                    {
  DCHECK_NE(PropertyArray::kNoHashSentinel, hash);
  DCHECK(PropertyArray::HashField::is_valid(hash));
  ReadOnlyRoots roots = GetReadOnlyRoots();
  if (properties == roots.empty_fixed_array() ||
      properties == roots.empty_property_array() ||
      properties == roots.empty_property_dictionary() ||
      properties == roots.empty_swiss_property_dictionary()) {
    return Smi::FromInt(hash);
  }
  if (IsPropertyArray(properties)) {
    Cast<PropertyArray>(properties)->SetHash(hash);
    DCHECK_LT(0, Cast<PropertyArray>(properties)->length());
    return properties;
  }
  if (IsGlobalDictionary(properties)) {
    Cast<GlobalDictionary>(properties)->SetHash(hash);
    return properties;
  }
  DCHECK(IsPropertyDictionary(properties));
  Cast<PropertyDictionary>(properties)->SetHash(hash);
  return properties;
}
References v8::internal::DCHECK(), DCHECK_LT, DCHECK_NE, v8::internal::Smi::FromInt(), v8::internal::GetReadOnlyRoots(), v8::base::BitField< T, shift, size, U >::is_valid(), v8::internal::InstanceTypeChecker::IsPropertyDictionary(), v8::internal::PropertyArray::kNoHashSentinel, and v8::internal::length.
Referenced by v8::internal::JSReceiver::SetIdentityHash(), and v8::internal::JSReceiver::SetProperties().
SetPropertyWithInterceptorInternal()
Maybe<InterceptorResult> v8::internal::anonymous_namespace{js-objects.cc}::SetPropertyWithInterceptorInternal (LookupIterator * it, DirectHandle< InterceptorInfo > interceptor, Maybe< ShouldThrow > should_throw, DirectHandle< Object > value)
Definition at line 1292 of file js-objects.cc.
                                                                 {
  Isolate* isolate = it->isolate();
  // Make sure that the top context does not change when doing callbacks or
  // interceptor calls.
  AssertNoContextChange ncc(isolate);
  if (!interceptor->has_setter()) {
    return Just(InterceptorResult::kNotIntercepted);
  }
  DirectHandle<JSObject> holder = it->GetHolder<JSObject>();
  DirectHandle<Object> receiver = it->GetReceiver();
  if (!IsJSReceiver(*receiver)) {
    ASSIGN_RETURN_ON_EXCEPTION_VALUE(isolate, receiver,
                                     Object::ConvertReceiver(isolate, receiver),
                                     Nothing<InterceptorResult>());
  }
  PropertyCallbackArguments args(isolate, interceptor->data(), *receiver,
                                 *holder, should_throw);
  v8::Intercepted intercepted =
      it->IsElement(*holder)
          ? args.CallIndexedSetter(interceptor, it->array_index(), value)
          : args.CallNamedSetter(interceptor, it->name(), value);
  return args.GetBooleanReturnValue(intercepted, "Setter");
}
References v8::base::args, v8::internal::LookupIterator::array_index(), ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::Object::ConvertReceiver(), v8::internal::LookupIterator::GetHolder(), v8::internal::LookupIterator::GetReceiver(), v8::internal::LookupIterator::IsElement(), v8::internal::LookupIterator::isolate(), v8::Just(), v8::internal::kNotIntercepted, v8::internal::LookupIterator::name(), and v8::internal::value.
Referenced by v8::internal::JSObject::SetPropertyWithFailedAccessCheck(), and v8::internal::JSObject::SetPropertyWithInterceptor().
TestDictionaryPropertiesIntegrityLevel()
template<typename Dictionary >
bool v8::internal::anonymous_namespace{js-objects.cc}::TestDictionaryPropertiesIntegrityLevel (Tagged< Dictionary > dict, ReadOnlyRoots roots, PropertyAttributes level)
Definition at line 4197 of file js-objects.cc.
                                                                      {
  DCHECK(level == SEALED || level == FROZEN);
  for (InternalIndex i : dict->IterateEntries()) {
    Tagged<Object> key;
    if (!dict->ToKey(roots, i, &key)) continue;
    if (Object::FilterKey(key, ALL_PROPERTIES)) continue;
    PropertyDetails details = dict->DetailsAt(i);
    if (details.IsConfigurable()) return false;
    if (level == FROZEN && details.kind() == PropertyKind::kData &&
        !details.IsReadOnly()) {
      return false;
    }
  }
  return true;
}
References v8::internal::ALL_PROPERTIES, v8::internal::DCHECK(), v8::internal::Object::FilterKey(), v8::internal::FROZEN, v8::internal::PropertyDetails::IsConfigurable(), v8::internal::PropertyDetails::IsReadOnly(), v8::internal::kData, v8::internal::key, v8::internal::PropertyDetails::kind(), and v8::internal::SEALED.
Referenced by TestElementsIntegrityLevel(), and TestPropertiesIntegrityLevel().
TestElementsIntegrityLevel()
bool v8::internal::anonymous_namespace{js-objects.cc}::TestElementsIntegrityLevel (Isolate * isolate, Tagged< JSObject > object, PropertyAttributes level)
Definition at line 4252 of file js-objects.cc.
                                                          {
  DCHECK(!object->HasSloppyArgumentsElements());
  ElementsKind kind = object->GetElementsKind();
  if (IsDictionaryElementsKind(kind)) {
    return TestDictionaryPropertiesIntegrityLevel(
        Cast<NumberDictionary>(object->elements()), GetReadOnlyRoots(), level);
  }
  if (IsTypedArrayOrRabGsabTypedArrayElementsKind(kind)) {
    if (level == FROZEN && Cast<JSArrayBufferView>(object)->byte_length() > 0) {
      return false; // TypedArrays with elements can't be frozen.
    }
    return TestPropertiesIntegrityLevel(object, level);
  }
  if (IsFrozenElementsKind(kind)) return true;
  if (IsSealedElementsKind(kind) && level != FROZEN) return true;
  if (IsNonextensibleElementsKind(kind) && level == NONE) return true;
  ElementsAccessor* accessor = ElementsAccessor::ForKind(kind);
  // Only DICTIONARY_ELEMENTS and SLOW_SLOPPY_ARGUMENTS_ELEMENTS have
  // PropertyAttributes so just test if empty
  return accessor->NumberOfElements(isolate, object) == 0;
}
References v8::internal::Cast< NumberDictionary >(), v8::internal::DCHECK(), v8::internal::ElementsAccessor::ForKind(), v8::internal::FROZEN, v8::internal::GetReadOnlyRoots(), v8::internal::IsDictionaryElementsKind(), v8::internal::IsFrozenElementsKind(), v8::internal::IsNonextensibleElementsKind(), v8::internal::IsSealedElementsKind(), v8::internal::IsTypedArrayOrRabGsabTypedArrayElementsKind(), v8::internal::NONE, v8::internal::ElementsAccessor::NumberOfElements(), TestDictionaryPropertiesIntegrityLevel(), and TestPropertiesIntegrityLevel().
Referenced by FastTestIntegrityLevel().
TestFastPropertiesIntegrityLevel()
bool v8::internal::anonymous_namespace{js-objects.cc}::TestFastPropertiesIntegrityLevel (Tagged< Map > map, PropertyAttributes level)
Definition at line 4216 of file js-objects.cc.
                                                                {
  DCHECK(level == SEALED || level == FROZEN);
  DCHECK(!IsCustomElementsReceiverMap(map));
  DCHECK(!map->is_dictionary_map());
  Tagged<DescriptorArray> descriptors = map->instance_descriptors();
  for (InternalIndex i : map->IterateOwnDescriptors()) {
    if (descriptors->GetKey(i)->IsPrivate()) continue;
    PropertyDetails details = descriptors->GetDetails(i);
    if (details.IsConfigurable()) return false;
    if (level == FROZEN && details.kind() == PropertyKind::kData &&
        !details.IsReadOnly()) {
      return false;
    }
  }
  return true;
}
References v8::internal::DCHECK(), v8::internal::FROZEN, v8::internal::PropertyDetails::IsConfigurable(), v8::internal::IsCustomElementsReceiverMap(), v8::internal::PropertyDetails::IsReadOnly(), v8::internal::kData, v8::internal::PropertyDetails::kind(), and v8::internal::SEALED.
Referenced by TestPropertiesIntegrityLevel().
TestPropertiesIntegrityLevel()
bool v8::internal::anonymous_namespace{js-objects.cc}::TestPropertiesIntegrityLevel (Tagged< JSObject > object, PropertyAttributes level)
Definition at line 4235 of file js-objects.cc.
                                                            {
  DCHECK(!IsCustomElementsReceiverMap(object->map()));
  if (object->HasFastProperties()) {
    return TestFastPropertiesIntegrityLevel(object->map(), level);
  }
  if constexpr (V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
    return TestDictionaryPropertiesIntegrityLevel(
        object->property_dictionary_swiss(), GetReadOnlyRoots(), level);
  } else {
    return TestDictionaryPropertiesIntegrityLevel(object->property_dictionary(),
                                                  GetReadOnlyRoots(), level);
  }
}
References v8::internal::DCHECK(), v8::internal::GetReadOnlyRoots(), v8::internal::IsCustomElementsReceiverMap(), TestDictionaryPropertiesIntegrityLevel(), TestFastPropertiesIntegrityLevel(), and V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL.
Referenced by FastTestIntegrityLevel(), and TestElementsIntegrityLevel().
TryFastAddDataProperty()
bool v8::internal::anonymous_namespace{js-objects.cc}::TryFastAddDataProperty (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< Name > name, DirectHandle< Object > value, PropertyAttributes attributes)
Definition at line 3604 of file js-objects.cc.
                                                           {
  DCHECK(IsUniqueName(*name));
  Tagged<Map> map =
      TransitionsAccessor(isolate, object->map())
          .SearchTransition(*name, PropertyKind::kData, attributes);
  if (map.is_null()) return false;
  DCHECK(!map->is_dictionary_map());
  DirectHandle<Map> new_map(map, isolate);
  if (map->is_deprecated()) {
    new_map = Map::Update(isolate, new_map);
    if (new_map->is_dictionary_map()) return false;
  }
  InternalIndex descriptor = new_map->LastAdded();
  new_map = Map::PrepareForDataProperty(isolate, new_map, descriptor,
                                        PropertyConstness::kConst, value);
  JSObject::MigrateToMap(isolate, object, new_map);
  // TODO(leszeks): Avoid re-loading the property details, which we already
  // loaded in PrepareForDataProperty.
  object->WriteToField(descriptor,
                       new_map->instance_descriptors()->GetDetails(descriptor),
                       *value);
  return true;
}
References v8::internal::DCHECK(), v8::internal::Tagged< HeapObject >::is_null(), v8::internal::IsUniqueName(), v8::internal::kConst, v8::internal::kData, v8::internal::JSObject::MigrateToMap(), v8::internal::name, v8::internal::Map::PrepareForDataProperty(), v8::internal::TransitionsAccessor::SearchTransition(), v8::internal::Map::Update(), and v8::internal::value.
Referenced by v8::internal::JSObject::AddProperty(), and v8::internal::JSObject::CreateDataProperty().