v8::internal::anonymous_namespace{js-date-time-format.cc} Namespace Reference
Classes
class PatternMap
class PatternItem
class PatternItems
class PatternData
class Pattern
class SpecialTimeZoneMap
struct DateTimeValueRecord
class CalendarCache
class DateFormatCache
class DateTimePatternGeneratorCache
Enumerations
enum class PatternKind {
kDate
, kPlainDate
, kPlainDateTime
, kPlainTime
,
kPlainYearMonth
, kPlainMonthDay
, kZonedDateTime
, kInstant
 }
Functions
std::string ToHourCycleString (JSDateTimeFormat::HourCycle hc)
JSDateTimeFormat::HourCycle ToHourCycle (const std::string &hc)
JSDateTimeFormat::HourCycle ToHourCycle (UDateFormatHourCycle hc)
JSDateTimeFormat::HourCycle DefaultHourCycle12 (const icu::Locale &locale, JSDateTimeFormat::HourCycle defaultHourCycle)
JSDateTimeFormat::HourCycle DefaultHourCycle24 (const icu::Locale &locale, JSDateTimeFormat::HourCycle defaultHourCycle)
Maybe< JSDateTimeFormat::HourCycle > GetHourCycle (Isolate *isolate, DirectHandle< JSReceiver > options, const char *method_name)
static std::vector< PatternItem > BuildPatternItems ()
static const std::vector< PatternItem > & GetPatternItems ()
const std::vector< PatternData > CreateCommonData (const PatternData &hour_data)
const std::vector< PatternData > CreateData (const char *digit2, const char *numeric)
const std::vector< PatternData > & GetPatternData (JSDateTimeFormat::HourCycle hour_cycle)
std::string GetGMTTzID (const std::string &input)
bool IsAsciiAlpha (char ch)
char LocaleIndependentAsciiToUpper (char ch)
char LocaleIndependentAsciiToLower (char ch)
std::string ToTitleCaseTimezoneLocation (const std::string &input)
DirectHandle< String > DateTimeStyleAsString (Isolate *isolate, JSDateTimeFormat::DateTimeStyle style)
int FractionalSecondDigitsFromPattern (const std::string &pattern)
DirectHandle< String > GetCalendar (Isolate *isolate, const icu::SimpleDateFormat &simple_date_format)
DirectHandle< Object > GetTimeZone (Isolate *isolate, const icu::SimpleDateFormat &simple_date_format)
bool IsTemporalObject (DirectHandle< Object > value)
bool SameTemporalType (DirectHandle< Object > x, DirectHandle< Object > y)
Maybe< DateTimeValueRecord > HandleDateTimeOthers (Isolate *isolate, const icu::SimpleDateFormat &date_time_format, DirectHandle< Object > x_obj, const char *method_name)
Maybe< DateTimeValueRecord > HandleDateTimeValue (Isolate *isolate, const icu::SimpleDateFormat &date_time_format, DirectHandle< String > date_time_format_calendar, DirectHandle< Object > x, const char *method_name)
icu::UnicodeString KeepSupportedAddDefault (const icu::UnicodeString &input, const std::set< char16_t > &keep, const std::set< char16_t > &add_default)
icu::UnicodeString GetSkeletonForPatternKind (const icu::UnicodeString &input, PatternKind kind)
icu::UnicodeString SkeletonFromDateFormat (const icu::SimpleDateFormat &icu_date_format)
std::unique_ptr< icu::SimpleDateFormat > GetSimpleDateTimeForTemporal (const icu::SimpleDateFormat &date_format, PatternKind kind)
icu::UnicodeString CallICUFormat (const icu::SimpleDateFormat &date_format, PatternKind kind, double time_in_milliseconds, icu::FieldPositionIterator *fp_iter, UErrorCode &status)
MaybeDirectHandle< String > FormatDateTime (Isolate *isolate, const icu::SimpleDateFormat &date_format, double x)
MaybeDirectHandle< String > FormatMillisecondsByKindToString (Isolate *isolate, const icu::SimpleDateFormat &date_format, PatternKind kind, double x)
MaybeDirectHandle< String > FormatDateTimeWithTemporalSupport (Isolate *isolate, const icu::SimpleDateFormat &date_format, DirectHandle< String > date_time_format_calendar, DirectHandle< Object > x, const char *method_name)
MaybeDirectHandle< String > FormatDateTimeWithTemporalSupport (Isolate *isolate, DirectHandle< JSDateTimeFormat > date_time_format, DirectHandle< Object > x, const char *method_name)
Isolate::ICUObjectCacheType ConvertToCacheType (JSDateTimeFormat::DefaultsOption type)
icu::Calendar * CreateCalendar (Isolate *isolate, const icu::Locale &icu_locale, icu::TimeZone *tz)
icu::UnicodeString ReplaceHourCycleInPattern (icu::UnicodeString pattern, JSDateTimeFormat::HourCycle hc)
std::unique_ptr< icu::SimpleDateFormat > CreateICUDateFormat (const icu::Locale &icu_locale, const icu::UnicodeString &skeleton, icu::DateTimePatternGenerator *generator, JSDateTimeFormat::HourCycle hc)
std::unique_ptr< icu::SimpleDateFormat > CreateICUDateFormatFromCache (const icu::Locale &icu_locale, const icu::UnicodeString &skeleton, icu::DateTimePatternGenerator *generator, JSDateTimeFormat::HourCycle hc)
std::unique_ptr< icu::DateIntervalFormat > LazyCreateDateIntervalFormat (Isolate *isolate, DirectHandle< JSDateTimeFormat > date_time_format, PatternKind kind)
JSDateTimeFormat::HourCycle HourCycleFromPattern (const icu::UnicodeString pattern)
icu::DateFormat::EStyle DateTimeStyleToEStyle (JSDateTimeFormat::DateTimeStyle style)
icu::UnicodeString ReplaceSkeleton (const icu::UnicodeString input, JSDateTimeFormat::HourCycle hc)
std::unique_ptr< icu::SimpleDateFormat > DateTimeStylePattern (JSDateTimeFormat::DateTimeStyle date_style, JSDateTimeFormat::DateTimeStyle time_style, icu::Locale &icu_locale, JSDateTimeFormat::HourCycle hc, icu::DateTimePatternGenerator *generator)
DirectHandle< String > IcuDateFieldIdToDateType (int32_t field_id, Isolate *isolate)
MaybeDirectHandle< JSArray > FieldPositionIteratorToArray (Isolate *isolate, const icu::UnicodeString &formatted, icu::FieldPositionIterator fp_iter, bool output_source)
MaybeDirectHandle< JSArray > FormatMillisecondsByKindToArray (Isolate *isolate, const icu::SimpleDateFormat &date_format, PatternKind kind, double x, bool output_source)
MaybeDirectHandle< JSArray > FormatMillisecondsByKindToArrayOutputSource (Isolate *isolate, const icu::SimpleDateFormat &date_format, PatternKind kind, double x)
MaybeDirectHandle< JSArray > FormatToPartsWithTemporalSupport (Isolate *isolate, DirectHandle< JSDateTimeFormat > date_time_format, DirectHandle< Object > x, bool output_source, const char *method_name)
MaybeDirectHandle< JSArray > FormatMillisecondsToArray (Isolate *isolate, const icu::SimpleDateFormat &format, double value, bool output_source)
MaybeDirectHandle< JSArray > FormatMillisecondsToArrayOutputSource (Isolate *isolate, const icu::SimpleDateFormat &format, double value)
Maybe< bool > AddPartForFormatRange (Isolate *isolate, DirectHandle< JSArray > array, const icu::UnicodeString &string, int32_t index, int32_t field, int32_t start, int32_t end, const Intl::FormatRangeSourceTracker &tracker)
std::optional< MaybeDirectHandle< String > > FormattedToString (Isolate *isolate, const icu::FormattedValue &formatted)
std::optional< MaybeDirectHandle< JSArray > > FormattedDateIntervalToJSArray (Isolate *isolate, const icu::FormattedValue &formatted)
template<typename T , std::optional< MaybeDirectHandle< T >>(*)(Isolate *, const icu::FormattedValue &) Format>
std::optional< MaybeDirectHandle< T > > CallICUFormatRange (Isolate *isolate, const icu::DateIntervalFormat *format, const icu::Calendar *calendar, double x, double y)
template<typename T , std::optional< MaybeDirectHandle< T >>(*)(Isolate *, const icu::FormattedValue &) Format>
std::optional< MaybeDirectHandle< T > > PartitionDateTimeRangePattern (Isolate *isolate, DirectHandle< JSDateTimeFormat > date_time_format, double x, double y, const char *method_name)
template<typename T , std::optional< MaybeDirectHandle< T >>(*)(Isolate *, const icu::FormattedValue &) Format, MaybeDirectHandle< T >(*)(Isolate *, const icu::SimpleDateFormat &, PatternKind, double) Fallback>
MaybeDirectHandle< T > FormatRangeCommonWithTemporalSupport (Isolate *isolate, DirectHandle< JSDateTimeFormat > date_time_format, DirectHandle< Object > x_obj, DirectHandle< Object > y_obj, const char *method_name)
template<typename T , std::optional< MaybeDirectHandle< T >>(*)(Isolate *, const icu::FormattedValue &) Format, MaybeDirectHandle< T >(*)(Isolate *, const icu::SimpleDateFormat &, double) Fallback>
MaybeDirectHandle< T > FormatRangeCommon (Isolate *isolate, DirectHandle< JSDateTimeFormat > date_time_format, DirectHandle< Object > x_obj, DirectHandle< Object > y_obj, const char *method_name)
Variables
static const auto k2DigitNumeric
Enumeration Type Documentation
PatternKind
enum v8::internal::anonymous_namespace{js-date-time-format.cc}::PatternKind [strong]
Enumerator
kDate
kPlainDate
kPlainDateTime
kPlainTime
kPlainYearMonth
kPlainMonthDay
kZonedDateTime
kInstant
Definition at line 881 of file js-date-time-format.cc.
                       {
  kDate,
  kPlainDate,
  kPlainDateTime,
  kPlainTime,
  kPlainYearMonth,
  kPlainMonthDay,
  kZonedDateTime,
  kInstant,
};
Function Documentation
AddPartForFormatRange()
Maybe<bool> v8::internal::anonymous_namespace{js-date-time-format.cc}::AddPartForFormatRange (Isolate * isolate, DirectHandle< JSArray > array, const icu::UnicodeString & string, int32_t index, int32_t field, int32_t start, int32_t end, const Intl::FormatRangeSourceTracker & tracker)
Definition at line 2726 of file js-date-time-format.cc.
                                                                             {
  DirectHandle<String> substring;
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(isolate, substring,
                                   Intl::ToString(isolate, string, start, end),
                                   Nothing<bool>());
  Intl::AddElement(isolate, array, index,
                   IcuDateFieldIdToDateType(field, isolate), substring,
                   isolate->factory()->source_string(),
                   Intl::SourceString(isolate, tracker.GetSource(start, end)));
  return Just(true);
}
References v8::internal::Intl::AddElement(), ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::compiler::end(), v8::internal::Isolate::factory(), v8::internal::Intl::FormatRangeSourceTracker::GetSource(), IcuDateFieldIdToDateType(), v8::internal::index, v8::Just(), v8::internal::Intl::SourceString(), and v8::internal::Intl::ToString().
Referenced by FormattedDateIntervalToJSArray().
BuildPatternItems()
static std::vector<PatternItem> v8::internal::anonymous_namespace{js-date-time-format.cc}::BuildPatternItems () [static]
Definition at line 168 of file js-date-time-format.cc.
                                                  {
  static const auto kNarrowLongShort =
      std::to_array<std::string_view>({"narrow", "long", "short"});
  static const auto kNarrowLongShort2DigitNumeric =
      std::to_array<std::string_view>(
          {"narrow", "long", "short", "2-digit", "numeric"});
  std::vector<PatternItem> items = {
      PatternItem(Weekday::kShift, "weekday",
                  {{"EEEEE", "narrow"},
                   {"EEEE", "long"},
                   {"EEE", "short"},
                   {"ccccc", "narrow"},
                   {"cccc", "long"},
                   {"ccc", "short"}},
                  kNarrowLongShort),
      PatternItem(Era::kShift, "era",
                  {{"GGGGG", "narrow"}, {"GGGG", "long"}, {"GGG", "short"}},
                  kNarrowLongShort),
      PatternItem(Year::kShift, "year", {{"yy", "2-digit"}, {"y", "numeric"}},
                  k2DigitNumeric)};
  // Sometimes we get L instead of M for month - standalone name.
  items.push_back(PatternItem(Month::kShift, "month",
                              {{"MMMMM", "narrow"},
                               {"MMMM", "long"},
                               {"MMM", "short"},
                               {"MM", "2-digit"},
                               {"M", "numeric"},
                               {"LLLLL", "narrow"},
                               {"LLLL", "long"},
                               {"LLL", "short"},
                               {"LL", "2-digit"},
                               {"L", "numeric"}},
                              kNarrowLongShort2DigitNumeric));
  items.push_back(PatternItem(Day::kShift, "day",
                              {{"dd", "2-digit"}, {"d", "numeric"}},
                              k2DigitNumeric));
  items.push_back(PatternItem(DayPeriod::kShift, "dayPeriod",
                              {{"BBBBB", "narrow"},
                               {"bbbbb", "narrow"},
                               {"BBBB", "long"},
                               {"bbbb", "long"},
                               {"B", "short"},
                               {"b", "short"}},
                              kNarrowLongShort));
  items.push_back(PatternItem(Hour::kShift, "hour",
                              {{"HH", "2-digit"},
                               {"H", "numeric"},
                               {"hh", "2-digit"},
                               {"h", "numeric"},
                               {"kk", "2-digit"},
                               {"k", "numeric"},
                               {"KK", "2-digit"},
                               {"K", "numeric"}},
                              k2DigitNumeric));
  items.push_back(PatternItem(Minute::kShift, "minute",
                              {{"mm", "2-digit"}, {"m", "numeric"}},
                              k2DigitNumeric));
  items.push_back(PatternItem(Second::kShift, "second",
                              {{"ss", "2-digit"}, {"s", "numeric"}},
                              k2DigitNumeric));
  static const auto kTimezone = std::to_array<std::string_view>(
      {"long", "short", "longOffset", "shortOffset", "longGeneric",
       "shortGeneric"});
  items.push_back(PatternItem(TimeZoneName::kShift, "timeZoneName",
                              {{"zzzz", "long"},
                               {"z", "short"},
                               {"OOOO", "longOffset"},
                               {"O", "shortOffset"},
                               {"vvvv", "longGeneric"},
                               {"v", "shortGeneric"}},
                              kTimezone));
  return items;
}
References k2DigitNumeric.
CallICUFormat()
icu::UnicodeString v8::internal::anonymous_namespace{js-date-time-format.cc}::CallICUFormat (const icu::SimpleDateFormat & date_format, PatternKind kind, double time_in_milliseconds, icu::FieldPositionIterator * fp_iter, UErrorCode & status)
Definition at line 1236 of file js-date-time-format.cc.
                                                     {
  icu::UnicodeString result;
  // Use the date_format directly for Date value.
  if (kind == PatternKind::kDate) {
    date_format.format(time_in_milliseconds, result, fp_iter, status);
    return result;
  }
  // For other Temporal objects, lazy generate a SimpleDateFormat for the kind.
  std::unique_ptr<icu::SimpleDateFormat> pattern(
      GetSimpleDateTimeForTemporal(date_format, kind));
  pattern->format(time_in_milliseconds, result, fp_iter, status);
  return result;
}
References GetSimpleDateTimeForTemporal(), v8::base::internal::result, and v8::internal::status.
Referenced by FormatMillisecondsByKindToArray(), and FormatMillisecondsByKindToString().
CallICUFormatRange()
template<typename T , std::optional< MaybeDirectHandle< T >>(*)(Isolate *, const icu::FormattedValue &) Format>
std::optional< MaybeDirectHandle< T > > v8::internal::anonymous_namespace{js-date-time-format.cc}::CallICUFormatRange (Isolate * isolate, const icu::DateIntervalFormat * format, const icu::Calendar * calendar, double x, double y)
Definition at line 2862 of file js-date-time-format.cc.
                                                     {
  UErrorCode status = U_ZERO_ERROR;
  std::unique_ptr<icu::Calendar> c1(calendar->clone());
  std::unique_ptr<icu::Calendar> c2(calendar->clone());
  c1->setTime(x, status);
  c2->setTime(y, status);
  // We need to format by Calendar because we need the Gregorian change
  // adjustment already in the SimpleDateFormat to set the correct value of date
  // older than Oct 15, 1582.
  icu::FormattedDateInterval formatted =
      format->formatToValue(*c1, *c2, status);
  if (U_FAILURE(status)) {
    THROW_NEW_ERROR(isolate, NewTypeError(MessageTemplate::kIcuError));
  }
  return Format(isolate, formatted);
}
References v8::internal::format, v8::internal::status, THROW_NEW_ERROR, and v8::internal::y.
ConvertToCacheType()
Isolate::ICUObjectCacheType v8::internal::anonymous_namespace{js-date-time-format.cc}::ConvertToCacheType (JSDateTimeFormat::DefaultsOption type)
Definition at line 1338 of file js-date-time-format.cc.
                                         {
  switch (type) {
    case JSDateTimeFormat::DefaultsOption::kDate:
      return Isolate::ICUObjectCacheType::kDefaultSimpleDateFormatForDate;
    case JSDateTimeFormat::DefaultsOption::kTime:
      return Isolate::ICUObjectCacheType::kDefaultSimpleDateFormatForTime;
    case JSDateTimeFormat::DefaultsOption::kAll:
      return Isolate::ICUObjectCacheType::kDefaultSimpleDateFormat;
  }
}
References v8::internal::JSDateTimeFormat::kAll, v8::internal::JSDateTimeFormat::kDate, v8::internal::JSDateTimeFormat::kTime, and v8::internal::tracing::type.
Referenced by v8::internal::JSDateTimeFormat::ToLocaleDateTime().
CreateCalendar()
icu::Calendar* v8::internal::anonymous_namespace{js-date-time-format.cc}::CreateCalendar (Isolate * isolate, const icu::Locale & icu_locale, icu::TimeZone * tz)
Definition at line 1595 of file js-date-time-format.cc.
                                               {
  static base::LazyInstance<CalendarCache>::type calendar_cache =
      LAZY_INSTANCE_INITIALIZER;
  return calendar_cache.Pointer()->CreateCalendar(icu_locale, tz);
}
References LAZY_INSTANCE_INITIALIZER.
Referenced by v8::internal::JSDateTimeFormat::CreateDateTimeFormat().
CreateCommonData()
const std::vector<PatternData> v8::internal::anonymous_namespace{js-date-time-format.cc}::CreateCommonData (const PatternData & hour_data)
Definition at line 281 of file js-date-time-format.cc.
                                                                            {
  std::vector<PatternData> build;
  for (const PatternItem& item : GetPatternItems()) {
    if (item.property == "hour") {
      build.push_back(hour_data);
    } else {
      build.push_back(PatternData(item.bitShift, item.property, item.pairs,
                                  item.allowed_values));
    }
  }
  return build;
}
References GetPatternItems().
Referenced by CreateData().
CreateData()
const std::vector<PatternData> v8::internal::anonymous_namespace{js-date-time-format.cc}::CreateData (const char * digit2, const char * numeric)
Definition at line 294 of file js-date-time-format.cc.
                                                               {
  return CreateCommonData(
      PatternData(Hour::kShift, "hour",
                  {{digit2, "2-digit"}, {numeric, "numeric"}}, k2DigitNumeric));
}
References CreateCommonData(), and k2DigitNumeric.
CreateICUDateFormat()
std::unique_ptr<icu::SimpleDateFormat> v8::internal::anonymous_namespace{js-date-time-format.cc}::CreateICUDateFormat (const icu::Locale & icu_locale, const icu::UnicodeString & skeleton, icu::DateTimePatternGenerator * generator, JSDateTimeFormat::HourCycle hc)
Definition at line 1653 of file js-date-time-format.cc.
                                                                          {
  // See https://github.com/tc39/ecma402/issues/225 . The best pattern
  // generation needs to be done in the base locale according to the
  // current spec however odd it may be. See also crbug.com/826549 .
  // This is a temporary work-around to get v8's external behavior to match
  // the current spec, but does not follow the spec provisions mentioned
  // in the above Ecma 402 issue.
  // TODO(jshin): The spec may need to be revised because using the base
  // locale for the pattern match is not quite right. Moreover, what to
  // do with 'related year' part when 'chinese/dangi' calendar is specified
  // has to be discussed. Revisit once the spec is clarified/revised.
  icu::UnicodeString pattern;
  UErrorCode status = U_ZERO_ERROR;
  pattern = generator->getBestPattern(skeleton, UDATPG_MATCH_HOUR_FIELD_LENGTH,
                                      status);
  pattern = ReplaceHourCycleInPattern(pattern, hc);
  DCHECK(U_SUCCESS(status));
  // Make formatter from skeleton. Calendar and numbering system are added
  // to the locale as Unicode extension (if they were specified at all).
  status = U_ZERO_ERROR;
  std::unique_ptr<icu::SimpleDateFormat> date_format(
      new icu::SimpleDateFormat(pattern, icu_locale, status));
  if (U_FAILURE(status)) return std::unique_ptr<icu::SimpleDateFormat>();
  DCHECK_NOT_NULL(date_format.get());
  return date_format;
}
References v8::internal::DCHECK(), DCHECK_NOT_NULL, ReplaceHourCycleInPattern(), and v8::internal::status.
Referenced by v8::internal::anonymous_namespace{js-date-time-format.cc}::DateFormatCache::Create().
CreateICUDateFormatFromCache()
std::unique_ptr<icu::SimpleDateFormat> v8::internal::anonymous_namespace{js-date-time-format.cc}::CreateICUDateFormatFromCache (const icu::Locale & icu_locale, const icu::UnicodeString & skeleton, icu::DateTimePatternGenerator * generator, JSDateTimeFormat::HourCycle hc)
Definition at line 1716 of file js-date-time-format.cc.
                                                                          {
  static base::LazyInstance<DateFormatCache>::type cache =
      LAZY_INSTANCE_INITIALIZER;
  return std::unique_ptr<icu::SimpleDateFormat>(
      cache.Pointer()->Create(icu_locale, skeleton, generator, hc));
}
References LAZY_INSTANCE_INITIALIZER.
Referenced by v8::internal::JSDateTimeFormat::CreateDateTimeFormat(), and DateTimeStylePattern().
DateTimeStyleAsString()
DirectHandle<String> v8::internal::anonymous_namespace{js-date-time-format.cc}::DateTimeStyleAsString (Isolate * isolate, JSDateTimeFormat::DateTimeStyle style)
Definition at line 533 of file js-date-time-format.cc.
                                                           {
  switch (style) {
    case JSDateTimeFormat::DateTimeStyle::kFull:
      return isolate->factory()->full_string();
    case JSDateTimeFormat::DateTimeStyle::kLong:
      return isolate->factory()->long_string();
    case JSDateTimeFormat::DateTimeStyle::kMedium:
      return isolate->factory()->medium_string();
    case JSDateTimeFormat::DateTimeStyle::kShort:
      return isolate->factory()->short_string();
    case JSDateTimeFormat::DateTimeStyle::kUndefined:
      UNREACHABLE();
  }
  UNREACHABLE();
}
References v8::internal::Isolate::factory(), v8::internal::JSDateTimeFormat::kFull, v8::internal::JSDateTimeFormat::kLong, v8::internal::JSDateTimeFormat::kMedium, v8::internal::JSDateTimeFormat::kShort, v8::internal::JSDateTimeFormat::kUndefined, and v8::internal::UNREACHABLE().
Referenced by v8::internal::JSDateTimeFormat::ResolvedOptions().
DateTimeStylePattern()
std::unique_ptr<icu::SimpleDateFormat> v8::internal::anonymous_namespace{js-date-time-format.cc}::DateTimeStylePattern (JSDateTimeFormat::DateTimeStyle date_style, JSDateTimeFormat::DateTimeStyle time_style, icu::Locale & icu_locale, JSDateTimeFormat::HourCycle hc, icu::DateTimePatternGenerator * generator)
Definition at line 1862 of file js-date-time-format.cc.
                                                                          {
  std::unique_ptr<icu::SimpleDateFormat> result;
  if (date_style != JSDateTimeFormat::DateTimeStyle::kUndefined) {
    if (time_style != JSDateTimeFormat::DateTimeStyle::kUndefined) {
      result.reset(reinterpret_cast<icu::SimpleDateFormat*>(
          icu::DateFormat::createDateTimeInstance(
              DateTimeStyleToEStyle(date_style),
              DateTimeStyleToEStyle(time_style), icu_locale)));
    } else {
      result.reset(reinterpret_cast<icu::SimpleDateFormat*>(
          icu::DateFormat::createDateInstance(DateTimeStyleToEStyle(date_style),
                                              icu_locale)));
      // For instance without time, we do not need to worry about the hour cycle
      // impact so we can return directly.
      if (result != nullptr) {
        return result;
      }
    }
  } else {
    if (time_style != JSDateTimeFormat::DateTimeStyle::kUndefined) {
      result.reset(reinterpret_cast<icu::SimpleDateFormat*>(
          icu::DateFormat::createTimeInstance(DateTimeStyleToEStyle(time_style),
                                              icu_locale)));
    } else {
      UNREACHABLE();
    }
  }
  UErrorCode status = U_ZERO_ERROR;
  // Somehow we fail to create the instance.
  if (result.get() == nullptr) {
    // Fallback to the locale without "nu".
    if (!icu_locale.getUnicodeKeywordValue<std::string>("nu", status).empty()) {
      status = U_ZERO_ERROR;
      icu_locale.setUnicodeKeywordValue("nu", nullptr, status);
      return DateTimeStylePattern(date_style, time_style, icu_locale, hc,
                                  generator);
    }
    status = U_ZERO_ERROR;
    // Fallback to the locale without "hc".
    if (!icu_locale.getUnicodeKeywordValue<std::string>("hc", status).empty()) {
      status = U_ZERO_ERROR;
      icu_locale.setUnicodeKeywordValue("hc", nullptr, status);
      return DateTimeStylePattern(date_style, time_style, icu_locale, hc,
                                  generator);
    }
    status = U_ZERO_ERROR;
    // Fallback to the locale without "ca".
    if (!icu_locale.getUnicodeKeywordValue<std::string>("ca", status).empty()) {
      status = U_ZERO_ERROR;
      icu_locale.setUnicodeKeywordValue("ca", nullptr, status);
      return DateTimeStylePattern(date_style, time_style, icu_locale, hc,
                                  generator);
    }
    return nullptr;
  }
  icu::UnicodeString pattern;
  pattern = result->toPattern(pattern);
  status = U_ZERO_ERROR;
  icu::UnicodeString skeleton =
      icu::DateTimePatternGenerator::staticGetSkeleton(pattern, status);
  DCHECK(U_SUCCESS(status));
  // If the skeleton match the HourCycle, we just return it.
  if (hc == HourCycleFromPattern(pattern)) {
    return result;
  }
  return CreateICUDateFormatFromCache(icu_locale, ReplaceSkeleton(skeleton, hc),
                                      generator, hc);
}
References CreateICUDateFormatFromCache(), DateTimeStyleToEStyle(), v8::internal::DCHECK(), HourCycleFromPattern(), v8::internal::JSDateTimeFormat::kUndefined, ReplaceSkeleton(), v8::base::internal::result, v8::internal::status, v8::internal::string, and v8::internal::UNREACHABLE().
Referenced by v8::internal::JSDateTimeFormat::CreateDateTimeFormat().
DateTimeStyleToEStyle()
icu::DateFormat::EStyle v8::internal::anonymous_namespace{js-date-time-format.cc}::DateTimeStyleToEStyle (JSDateTimeFormat::DateTimeStyle style)
Definition at line 1798 of file js-date-time-format.cc.
                                         {
  switch (style) {
    case JSDateTimeFormat::DateTimeStyle::kFull:
      return icu::DateFormat::EStyle::kFull;
    case JSDateTimeFormat::DateTimeStyle::kLong:
      return icu::DateFormat::EStyle::kLong;
    case JSDateTimeFormat::DateTimeStyle::kMedium:
      return icu::DateFormat::EStyle::kMedium;
    case JSDateTimeFormat::DateTimeStyle::kShort:
      return icu::DateFormat::EStyle::kShort;
    case JSDateTimeFormat::DateTimeStyle::kUndefined:
      UNREACHABLE();
  }
}
References v8::internal::JSDateTimeFormat::kFull, v8::internal::JSDateTimeFormat::kLong, v8::internal::kLong, v8::internal::JSDateTimeFormat::kMedium, v8::internal::JSDateTimeFormat::kShort, v8::internal::JSDateTimeFormat::kUndefined, and v8::internal::UNREACHABLE().
Referenced by DateTimeStylePattern().
DefaultHourCycle12()
JSDateTimeFormat::HourCycle v8::internal::anonymous_namespace{js-date-time-format.cc}::DefaultHourCycle12 (const icu::Locale & locale, JSDateTimeFormat::HourCycle defaultHourCycle)
Definition at line 90 of file js-date-time-format.cc.
                                                                         {
  if (defaultHourCycle == JSDateTimeFormat::HourCycle::kH11 ||
      defaultHourCycle == JSDateTimeFormat::HourCycle::kH12) {
    return defaultHourCycle;
  }
  if (std::strcmp(locale.getCountry(), "JP") == 0) {
    return JSDateTimeFormat::HourCycle::kH11;
  }
  return JSDateTimeFormat::HourCycle::kH12;
}
References v8::internal::JSDateTimeFormat::kH11, and v8::internal::JSDateTimeFormat::kH12.
Referenced by v8::internal::JSDateTimeFormat::CreateDateTimeFormat().
DefaultHourCycle24()
JSDateTimeFormat::HourCycle v8::internal::anonymous_namespace{js-date-time-format.cc}::DefaultHourCycle24 (const icu::Locale & locale, JSDateTimeFormat::HourCycle defaultHourCycle)
Definition at line 102 of file js-date-time-format.cc.
                                                                         {
  if (defaultHourCycle == JSDateTimeFormat::HourCycle::kH23 ||
      defaultHourCycle == JSDateTimeFormat::HourCycle::kH24) {
    return defaultHourCycle;
  }
  return JSDateTimeFormat::HourCycle::kH23;
}
References v8::internal::JSDateTimeFormat::kH23, and v8::internal::JSDateTimeFormat::kH24.
Referenced by v8::internal::JSDateTimeFormat::CreateDateTimeFormat().
FieldPositionIteratorToArray()
MaybeDirectHandle< JSArray > v8::internal::anonymous_namespace{js-date-time-format.cc}::FieldPositionIteratorToArray (Isolate * isolate, const icu::UnicodeString & formatted, icu::FieldPositionIterator fp_iter, bool output_source)
Definition at line 2636 of file js-date-time-format.cc.
                                                          {
  Factory* factory = isolate->factory();
  icu::FieldPosition fp;
  DirectHandle<JSArray> result = factory->NewJSArray(0);
  int32_t length = formatted.length();
  if (length == 0) return result;
  int index = 0;
  int32_t previous_end_pos = 0;
  DirectHandle<String> substring;
  while (fp_iter.next(fp)) {
    int32_t begin_pos = fp.getBeginIndex();
    int32_t end_pos = fp.getEndIndex();
    if (previous_end_pos < begin_pos) {
      ASSIGN_RETURN_ON_EXCEPTION(
          isolate, substring,
          Intl::ToString(isolate, formatted, previous_end_pos, begin_pos));
      if (output_source) {
        Intl::AddElement(isolate, result, index,
                         IcuDateFieldIdToDateType(-1, isolate), substring,
                         isolate->factory()->source_string(),
                         isolate->factory()->shared_string());
      } else {
        Intl::AddElement(isolate, result, index,
                         IcuDateFieldIdToDateType(-1, isolate), substring);
      }
      ++index;
    }
    ASSIGN_RETURN_ON_EXCEPTION(
        isolate, substring,
        Intl::ToString(isolate, formatted, begin_pos, end_pos));
    if (output_source) {
      Intl::AddElement(isolate, result, index,
                       IcuDateFieldIdToDateType(fp.getField(), isolate),
                       substring, isolate->factory()->source_string(),
                       isolate->factory()->shared_string());
    } else {
      Intl::AddElement(isolate, result, index,
                       IcuDateFieldIdToDateType(fp.getField(), isolate),
                       substring);
    }
    previous_end_pos = end_pos;
    ++index;
  }
  if (previous_end_pos < length) {
    ASSIGN_RETURN_ON_EXCEPTION(
        isolate, substring,
        Intl::ToString(isolate, formatted, previous_end_pos, length));
    if (output_source) {
      Intl::AddElement(isolate, result, index,
                       IcuDateFieldIdToDateType(-1, isolate), substring,
                       isolate->factory()->source_string(),
                       isolate->factory()->shared_string());
    } else {
      Intl::AddElement(isolate, result, index,
                       IcuDateFieldIdToDateType(-1, isolate), substring);
    }
  }
  JSObject::ValidateElements(isolate, *result);
  return result;
}
References v8::internal::Intl::AddElement(), ASSIGN_RETURN_ON_EXCEPTION, v8::internal::Isolate::factory(), IcuDateFieldIdToDateType(), v8::internal::index, v8::internal::length, v8::internal::Factory::NewJSArray(), v8::base::internal::result, v8::internal::Intl::ToString(), and v8::internal::JSObject::ValidateElements().
Referenced by FormatMillisecondsByKindToArray(), and FormatMillisecondsToArray().
FormatDateTime()
MaybeDirectHandle<String> v8::internal::anonymous_namespace{js-date-time-format.cc}::FormatDateTime (Isolate * isolate, const icu::SimpleDateFormat & date_format, double x)
Definition at line 1255 of file js-date-time-format.cc.
                                                                        {
  if (!DateCache::TryTimeClip(&x)) {
    THROW_NEW_ERROR(isolate, NewRangeError(MessageTemplate::kInvalidTimeValue));
  }
  icu::UnicodeString result;
  date_format.format(x, result);
  // Revert ICU 72 change that introduced U+202F instead of U+0020
  // to separate time from AM/PM. See https://crbug.com/1414292.
  result = result.findAndReplace(icu::UnicodeString(0x202f),
                                 icu::UnicodeString(0x20));
  return Intl::ToString(isolate, result);
}
References v8::base::internal::result, THROW_NEW_ERROR, v8::internal::Intl::ToString(), and v8::internal::DateCache::TryTimeClip().
Referenced by v8::internal::JSDateTimeFormat::DateTimeFormat(), and v8::internal::JSDateTimeFormat::ToLocaleDateTime().
FormatDateTimeWithTemporalSupport() [1/2]
MaybeDirectHandle<String> v8::internal::anonymous_namespace{js-date-time-format.cc}::FormatDateTimeWithTemporalSupport (Isolate * isolate, const icu::SimpleDateFormat & date_format, DirectHandle< String > date_time_format_calendar, DirectHandle< Object > x, const char * method_name)
Definition at line 1283 of file js-date-time-format.cc.
                             {
  DateTimeValueRecord record;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, record,
      HandleDateTimeValue(isolate, date_format, date_time_format_calendar, x,
                          method_name),
      {});
  return FormatMillisecondsByKindToString(isolate, date_format, record.kind,
                                          record.epoch_milliseconds);
}
References v8::internal::anonymous_namespace{js-date-time-format.cc}::DateTimeValueRecord::epoch_milliseconds, FormatMillisecondsByKindToString(), HandleDateTimeValue(), v8::internal::anonymous_namespace{js-date-time-format.cc}::DateTimeValueRecord::kind, and MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE.
FormatDateTimeWithTemporalSupport() [2/2]
MaybeDirectHandle<String> v8::internal::anonymous_namespace{js-date-time-format.cc}::FormatDateTimeWithTemporalSupport (Isolate * isolate, DirectHandle< JSDateTimeFormat > date_time_format, DirectHandle< Object > x, const char * method_name)
Definition at line 1297 of file js-date-time-format.cc.
                                                     {
  return FormatDateTimeWithTemporalSupport(
      isolate, *(date_time_format->icu_simple_date_format()->raw()),
      JSDateTimeFormat::Calendar(isolate, date_time_format), x, method_name);
}
References v8::internal::JSDateTimeFormat::Calendar().
Referenced by v8::internal::JSDateTimeFormat::DateTimeFormat(), and v8::internal::JSDateTimeFormat::TemporalToLocaleString().
FormatMillisecondsByKindToArray()
MaybeDirectHandle<JSArray> v8::internal::anonymous_namespace{js-date-time-format.cc}::FormatMillisecondsByKindToArray (Isolate * isolate, const icu::SimpleDateFormat & date_format, PatternKind kind, double x, bool output_source)
Definition at line 2551 of file js-date-time-format.cc.
                                                    {
  icu::FieldPositionIterator fp_iter;
  UErrorCode status = U_ZERO_ERROR;
  icu::UnicodeString formatted =
      CallICUFormat(date_format, kind, x, &fp_iter, status);
  if (U_FAILURE(status)) {
    THROW_NEW_ERROR(isolate, NewTypeError(MessageTemplate::kIcuError));
  }
  return FieldPositionIteratorToArray(isolate, formatted, fp_iter,
                                      output_source);
}
References CallICUFormat(), FieldPositionIteratorToArray(), v8::internal::status, and THROW_NEW_ERROR.
Referenced by FormatMillisecondsByKindToArrayOutputSource(), and FormatToPartsWithTemporalSupport().
FormatMillisecondsByKindToArrayOutputSource()
MaybeDirectHandle<JSArray> v8::internal::anonymous_namespace{js-date-time-format.cc}::FormatMillisecondsByKindToArrayOutputSource (Isolate * isolate, const icu::SimpleDateFormat & date_format, PatternKind kind, double x)
Definition at line 2565 of file js-date-time-format.cc.
                                {
  return FormatMillisecondsByKindToArray(isolate, date_format, kind, x, true);
}
References FormatMillisecondsByKindToArray().
Referenced by v8::internal::JSDateTimeFormat::FormatRangeToParts().
FormatMillisecondsByKindToString()
MaybeDirectHandle<String> v8::internal::anonymous_namespace{js-date-time-format.cc}::FormatMillisecondsByKindToString (Isolate * isolate, const icu::SimpleDateFormat & date_format, PatternKind kind, double x)
Definition at line 1272 of file js-date-time-format.cc.
                                {
  UErrorCode status = U_ZERO_ERROR;
  icu::UnicodeString result =
      CallICUFormat(date_format, kind, x, nullptr, status);
  DCHECK(U_SUCCESS(status));
  return Intl::ToString(isolate, result);
}
References CallICUFormat(), v8::internal::DCHECK(), v8::base::internal::result, v8::internal::status, and v8::internal::Intl::ToString().
Referenced by FormatDateTimeWithTemporalSupport(), and v8::internal::JSDateTimeFormat::FormatRange().
FormatMillisecondsToArray()
MaybeDirectHandle<JSArray> v8::internal::anonymous_namespace{js-date-time-format.cc}::FormatMillisecondsToArray (Isolate * isolate, const icu::SimpleDateFormat & format, double value, bool output_source)
Definition at line 2591 of file js-date-time-format.cc.
                        {
  icu::UnicodeString formatted;
  icu::FieldPositionIterator fp_iter;
  UErrorCode status = U_ZERO_ERROR;
  format.format(value, formatted, &fp_iter, status);
  if (U_FAILURE(status)) {
    THROW_NEW_ERROR(isolate, NewTypeError(MessageTemplate::kIcuError));
  }
  return FieldPositionIteratorToArray(isolate, formatted, fp_iter,
                                      output_source);
}
References FieldPositionIteratorToArray(), v8::internal::format, v8::internal::status, THROW_NEW_ERROR, and v8::internal::value.
Referenced by FormatMillisecondsToArrayOutputSource(), and v8::internal::JSDateTimeFormat::FormatToParts().
FormatMillisecondsToArrayOutputSource()
MaybeDirectHandle<JSArray> v8::internal::anonymous_namespace{js-date-time-format.cc}::FormatMillisecondsToArrayOutputSource (Isolate * isolate, const icu::SimpleDateFormat & format, double value)
Definition at line 2605 of file js-date-time-format.cc.
                                                                       {
  return FormatMillisecondsToArray(isolate, format, value, true);
}
References v8::internal::format, FormatMillisecondsToArray(), and v8::internal::value.
Referenced by v8::internal::JSDateTimeFormat::FormatRangeToParts().
FormatRangeCommon()
template<typename T , std::optional< MaybeDirectHandle< T >>(*)(Isolate *, const icu::FormattedValue &) Format, MaybeDirectHandle< T >(*)(Isolate *, const icu::SimpleDateFormat &, double) Fallback>
MaybeDirectHandle<T> v8::internal::anonymous_namespace{js-date-time-format.cc}::FormatRangeCommon (Isolate * isolate, DirectHandle< JSDateTimeFormat > date_time_format, DirectHandle< Object > x_obj, DirectHandle< Object > y_obj, const char * method_name)
Definition at line 2943 of file js-date-time-format.cc.
                             {
  // 4. Let x be ? ToNumber(startDate).
  ASSIGN_RETURN_ON_EXCEPTION(isolate, x_obj, Object::ToNumber(isolate, x_obj));
  double x = Object::NumberValue(*x_obj);
  // 5. Let y be ? ToNumber(endDate).
  ASSIGN_RETURN_ON_EXCEPTION(isolate, y_obj, Object::ToNumber(isolate, y_obj));
  double y = Object::NumberValue(*y_obj);
  std::optional<MaybeDirectHandle<T>> result =
      PartitionDateTimeRangePattern<T, Format>(isolate, date_time_format, x, y,
                                               method_name);
  if (result.has_value()) return *result;
  return Fallback(isolate, *(date_time_format->icu_simple_date_format()->raw()),
                  x);
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::Object::NumberValue(), v8::base::internal::result, v8::Value::ToNumber(), and v8::internal::y.
Referenced by v8::internal::JSDateTimeFormat::FormatRangeToParts().
FormatRangeCommonWithTemporalSupport()
template<typename T , std::optional< MaybeDirectHandle< T >>(*)(Isolate *, const icu::FormattedValue &) Format, MaybeDirectHandle< T >(*)(Isolate *, const icu::SimpleDateFormat &, PatternKind, double) Fallback>
MaybeDirectHandle<T> v8::internal::anonymous_namespace{js-date-time-format.cc}::FormatRangeCommonWithTemporalSupport (Isolate * isolate, DirectHandle< JSDateTimeFormat > date_time_format, DirectHandle< Object > x_obj, DirectHandle< Object > y_obj, const char * method_name)
Definition at line 2887 of file js-date-time-format.cc.
                             {
  // 5. If either of ! IsTemporalObject(x) or ! IsTemporalObject(y) is true,
  // then
  if (IsTemporalObject(x_obj) || IsTemporalObject(y_obj)) {
    // a. If ! SameTemporalType(x, y) is false, throw a TypeError exception.
    if (!SameTemporalType(x_obj, y_obj)) {
      THROW_NEW_ERROR(
          isolate,
          NewTypeError(MessageTemplate::kInvalidArgumentForTemporal, y_obj));
    }
  }
  // 6. Let x be ? HandleDateTimeValue(dateTimeFormat, x).
  icu::SimpleDateFormat* icu_simple_date_format =
      date_time_format->icu_simple_date_format()->raw();
  DirectHandle<String> date_time_format_calendar =
      GetCalendar(isolate, *icu_simple_date_format);
  DateTimeValueRecord x_record;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, x_record,
      HandleDateTimeValue(isolate, *icu_simple_date_format,
                          date_time_format_calendar, x_obj, method_name),
      {});
  // 7. Let y be ? HandleDateTimeValue(dateTimeFormat, y).
  DateTimeValueRecord y_record;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, y_record,
      HandleDateTimeValue(isolate, *icu_simple_date_format,
                          date_time_format_calendar, y_obj, method_name),
      {});
  std::unique_ptr<icu::DateIntervalFormat> format(
      LazyCreateDateIntervalFormat(isolate, date_time_format, x_record.kind));
  if (format.get() == nullptr) {
    THROW_NEW_ERROR(isolate, NewTypeError(MessageTemplate::kIcuError));
  }
  const icu::Calendar* calendar =
      date_time_format->icu_simple_date_format()->raw()->getCalendar();
  std::optional<MaybeDirectHandle<T>> result = CallICUFormatRange<T, Format>(
      isolate, format.get(), calendar, x_record.epoch_milliseconds,
      y_record.epoch_milliseconds);
  if (result.has_value()) return *result;
  return Fallback(isolate, *icu_simple_date_format, x_record.kind,
                  x_record.epoch_milliseconds);
}
References v8::internal::anonymous_namespace{js-date-time-format.cc}::DateTimeValueRecord::epoch_milliseconds, v8::internal::format, GetCalendar(), HandleDateTimeValue(), v8::internal::icu_simple_date_format, IsTemporalObject(), v8::internal::anonymous_namespace{js-date-time-format.cc}::DateTimeValueRecord::kind, LazyCreateDateIntervalFormat(), MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::base::internal::result, SameTemporalType(), and THROW_NEW_ERROR.
Referenced by v8::internal::JSDateTimeFormat::FormatRange(), and v8::internal::JSDateTimeFormat::FormatRangeToParts().
FormattedDateIntervalToJSArray()
std::optional<MaybeDirectHandle<JSArray> > v8::internal::anonymous_namespace{js-date-time-format.cc}::FormattedDateIntervalToJSArray (Isolate * isolate, const icu::FormattedValue & formatted)
Definition at line 2765 of file js-date-time-format.cc.
                                                          {
  UErrorCode status = U_ZERO_ERROR;
  icu::UnicodeString result = formatted.toString(status);
  Factory* factory = isolate->factory();
  DirectHandle<JSArray> array = factory->NewJSArray(0);
  icu::ConstrainedFieldPosition cfpos;
  int index = 0;
  int32_t previous_end_pos = 0;
  Intl::FormatRangeSourceTracker tracker;
  bool output_range = false;
  while (formatted.nextPosition(cfpos, status)) {
    int32_t category = cfpos.getCategory();
    int32_t field = cfpos.getField();
    int32_t start = cfpos.getStart();
    int32_t limit = cfpos.getLimit();
    if (category == UFIELD_CATEGORY_DATE_INTERVAL_SPAN) {
      DCHECK_LE(field, 2);
      output_range = true;
      tracker.Add(field, start, limit);
    } else {
      DCHECK(category == UFIELD_CATEGORY_DATE);
      if (start > previous_end_pos) {
        // Add "literal" from the previous end position to the start if
        // necessary.
        Maybe<bool> maybe_added =
            AddPartForFormatRange(isolate, array, result, index, -1,
                                  previous_end_pos, start, tracker);
        MAYBE_RETURN(maybe_added, Handle<JSArray>());
        previous_end_pos = start;
        index++;
      }
      Maybe<bool> maybe_added = AddPartForFormatRange(
          isolate, array, result, index, field, start, limit, tracker);
      MAYBE_RETURN(maybe_added, Handle<JSArray>());
      previous_end_pos = limit;
      ++index;
    }
  }
  int32_t end = result.length();
  // Add "literal" in the end if necessary.
  if (end > previous_end_pos) {
    Maybe<bool> maybe_added = AddPartForFormatRange(
        isolate, array, result, index, -1, previous_end_pos, end, tracker);
    MAYBE_RETURN(maybe_added, Handle<JSArray>());
  }
  if (U_FAILURE(status)) {
    THROW_NEW_ERROR(isolate, NewTypeError(MessageTemplate::kIcuError));
  }
  JSObject::ValidateElements(isolate, *array);
  if (output_range) return array;
  return std::nullopt;
}
References v8::internal::Intl::FormatRangeSourceTracker::Add(), AddPartForFormatRange(), v8::internal::DCHECK(), DCHECK_LE, v8::internal::compiler::end(), v8::internal::Isolate::factory(), v8::internal::index, MAYBE_RETURN, v8::internal::Factory::NewJSArray(), v8::base::internal::result, v8::internal::status, THROW_NEW_ERROR, and v8::internal::JSObject::ValidateElements().
Referenced by v8::internal::JSDateTimeFormat::FormatRangeToParts().
FormattedToString()
std::optional<MaybeDirectHandle<String> > v8::internal::anonymous_namespace{js-date-time-format.cc}::FormattedToString (Isolate * isolate, const icu::FormattedValue & formatted)
Definition at line 2744 of file js-date-time-format.cc.
                                                          {
  UErrorCode status = U_ZERO_ERROR;
  icu::UnicodeString result = formatted.toString(status);
  if (U_FAILURE(status)) {
    THROW_NEW_ERROR(isolate, NewTypeError(MessageTemplate::kIcuError));
  }
  icu::ConstrainedFieldPosition cfpos;
  while (formatted.nextPosition(cfpos, status)) {
    if (cfpos.getCategory() == UFIELD_CATEGORY_DATE_INTERVAL_SPAN) {
      return Intl::ToString(isolate, result);
    }
  }
  return std::nullopt;
}
References v8::base::internal::result, v8::internal::status, THROW_NEW_ERROR, and v8::internal::Intl::ToString().
FormatToPartsWithTemporalSupport()
MaybeDirectHandle<JSArray> v8::internal::anonymous_namespace{js-date-time-format.cc}::FormatToPartsWithTemporalSupport (Isolate * isolate, DirectHandle< JSDateTimeFormat > date_time_format, DirectHandle< Object > x, bool output_source, const char * method_name)
Definition at line 2571 of file js-date-time-format.cc.
                                                                         {
  icu::SimpleDateFormat* format =
      date_time_format->icu_simple_date_format()->raw();
  DCHECK_NOT_NULL(format);
  // 1. Let x be ? HandleDateTimeValue(dateTimeFormat, x).
  DateTimeValueRecord x_record;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, x_record,
      HandleDateTimeValue(isolate, *format, GetCalendar(isolate, *format), x,
                          method_name),
      {});
  return FormatMillisecondsByKindToArray(isolate, *format, x_record.kind,
                                         x_record.epoch_milliseconds,
                                         output_source);
}
References DCHECK_NOT_NULL, v8::internal::anonymous_namespace{js-date-time-format.cc}::DateTimeValueRecord::epoch_milliseconds, v8::internal::format, FormatMillisecondsByKindToArray(), GetCalendar(), HandleDateTimeValue(), v8::internal::anonymous_namespace{js-date-time-format.cc}::DateTimeValueRecord::kind, and MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE.
Referenced by v8::internal::JSDateTimeFormat::FormatToParts().
FractionalSecondDigitsFromPattern()
int v8::internal::anonymous_namespace{js-date-time-format.cc}::FractionalSecondDigitsFromPattern (const std::string & pattern)
Definition at line 550 of file js-date-time-format.cc.
                                                                {
  int result = 0;
  for (size_t i = 0; i < pattern.length() && result < 3; i++) {
    if (pattern[i] == 'S') {
      result++;
    }
  }
  return result;
}
References v8::base::internal::result.
Referenced by v8::internal::JSDateTimeFormat::ResolvedOptions().
GetCalendar()
DirectHandle<String> v8::internal::anonymous_namespace{js-date-time-format.cc}::GetCalendar (Isolate * isolate, const icu::SimpleDateFormat & simple_date_format)
Definition at line 606 of file js-date-time-format.cc.
                                                                     {
  // getType() returns legacy calendar type name instead of LDML/BCP47 calendar
  // key values. intl.js maps them to BCP47 values for key "ca".
  // TODO(jshin): Consider doing it here, instead.
  std::string calendar_str = simple_date_format.getCalendar()->getType();
  // Maps ICU calendar names to LDML/BCP47 types for key 'ca'.
  // See typeMap section in third_party/icu/source/data/misc/keyTypeData.txt
  // and
  // http://www.unicode.org/repos/cldr/tags/latest/common/bcp47/calendar.xml
  if (calendar_str == "gregorian") {
    calendar_str = "gregory";
  } else if (calendar_str == "ethiopic-amete-alem") {
    calendar_str = "ethioaa";
  }
  return isolate->factory()->NewStringFromAsciiChecked(calendar_str.c_str());
}
References v8::internal::Isolate::factory(), v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), and v8::internal::string.
Referenced by v8::internal::JSDateTimeFormat::Calendar(), FormatRangeCommonWithTemporalSupport(), and FormatToPartsWithTemporalSupport().
GetGMTTzID()
std::string v8::internal::anonymous_namespace{js-date-time-format.cc}::GetGMTTzID (const std::string & input)
Definition at line 369 of file js-date-time-format.cc.
                                             {
  std::string ret = "Etc/GMT";
  switch (input.length()) {
    case 8:
      if (input[7] == '0') return ret + '0';
      break;
    case 9:
      if ((input[7] == '+' || input[7] == '-') &&
          base::IsInRange(input[8], '0', '9')) {
        return ret + input[7] + input[8];
      }
      break;
    case 10:
      if ((input[7] == '+' || input[7] == '-') && (input[8] == '1') &&
          base::IsInRange(input[9], '0', '4')) {
        return ret + input[7] + input[8] + input[9];
      }
      break;
  }
  return "";
}
References v8::internal::string.
Referenced by v8::internal::JSDateTimeFormat::CanonicalizeTimeZoneID().
GetHourCycle()
Maybe<JSDateTimeFormat::HourCycle> v8::internal::anonymous_namespace{js-date-time-format.cc}::GetHourCycle (Isolate * isolate, DirectHandle< JSReceiver > options, const char * method_name)
Definition at line 111 of file js-date-time-format.cc.
                             {
  return GetStringOption<JSDateTimeFormat::HourCycle>(
      isolate, options, "hourCycle", method_name,
      std::to_array<const std::string_view>({"h11", "h12", "h23", "h24"}),
      std::array{
          JSDateTimeFormat::HourCycle::kH11, JSDateTimeFormat::HourCycle::kH12,
          JSDateTimeFormat::HourCycle::kH23, JSDateTimeFormat::HourCycle::kH24},
      JSDateTimeFormat::HourCycle::kUndefined);
}
References v8::internal::JSDateTimeFormat::kH11, v8::internal::JSDateTimeFormat::kH12, v8::internal::JSDateTimeFormat::kH23, v8::internal::JSDateTimeFormat::kH24, and v8::internal::JSDateTimeFormat::kUndefined.
Referenced by v8::internal::JSDateTimeFormat::CreateDateTimeFormat().
GetPatternData()
const std::vector<PatternData>& v8::internal::anonymous_namespace{js-date-time-format.cc}::GetPatternData (JSDateTimeFormat::HourCycle hour_cycle)
Definition at line 336 of file js-date-time-format.cc.
                                          {
  switch (hour_cycle) {
    case JSDateTimeFormat::HourCycle::kH11: {
      static base::LazyInstance<Pattern, H11Trait>::type h11 =
          LAZY_INSTANCE_INITIALIZER;
      return h11.Pointer()->Get();
    }
    case JSDateTimeFormat::HourCycle::kH12: {
      static base::LazyInstance<Pattern, H12Trait>::type h12 =
          LAZY_INSTANCE_INITIALIZER;
      return h12.Pointer()->Get();
    }
    case JSDateTimeFormat::HourCycle::kH23: {
      static base::LazyInstance<Pattern, H23Trait>::type h23 =
          LAZY_INSTANCE_INITIALIZER;
      return h23.Pointer()->Get();
    }
    case JSDateTimeFormat::HourCycle::kH24: {
      static base::LazyInstance<Pattern, H24Trait>::type h24 =
          LAZY_INSTANCE_INITIALIZER;
      return h24.Pointer()->Get();
    }
    case JSDateTimeFormat::HourCycle::kUndefined: {
      static base::LazyInstance<Pattern, HDefaultTrait>::type hDefault =
          LAZY_INSTANCE_INITIALIZER;
      return hDefault.Pointer()->Get();
    }
    default:
      UNREACHABLE();
  }
}
References v8::internal::JSDateTimeFormat::kH11, v8::internal::JSDateTimeFormat::kH12, v8::internal::JSDateTimeFormat::kH23, v8::internal::JSDateTimeFormat::kH24, v8::internal::JSDateTimeFormat::kUndefined, LAZY_INSTANCE_INITIALIZER, and v8::internal::UNREACHABLE().
Referenced by v8::internal::JSDateTimeFormat::CreateDateTimeFormat().
GetPatternItems()
static const std::vector<PatternItem>& v8::internal::anonymous_namespace{js-date-time-format.cc}::GetPatternItems () [static]
Definition at line 253 of file js-date-time-format.cc.
                                                       {
  static base::LazyInstance<PatternItems>::type items =
      LAZY_INSTANCE_INITIALIZER;
  return items.Pointer()->Get();
}
References LAZY_INSTANCE_INITIALIZER.
Referenced by CreateCommonData(), and v8::internal::JSDateTimeFormat::ResolvedOptions().
GetSimpleDateTimeForTemporal()
std::unique_ptr<icu::SimpleDateFormat> v8::internal::anonymous_namespace{js-date-time-format.cc}::GetSimpleDateTimeForTemporal (const icu::SimpleDateFormat & date_format, PatternKind kind)
Definition at line 1220 of file js-date-time-format.cc.
                                                              {
  DCHECK_NE(kind, PatternKind::kDate);
  icu::UnicodeString skeleton =
      GetSkeletonForPatternKind(SkeletonFromDateFormat(date_format), kind);
  UErrorCode status = U_ZERO_ERROR;
  std::unique_ptr<icu::SimpleDateFormat> result(
      static_cast<icu::SimpleDateFormat*>(
          icu::DateFormat::createInstanceForSkeleton(
              skeleton, date_format.getSmpFmtLocale(), status)));
  DCHECK(result);
  DCHECK(U_SUCCESS(status));
  result->setTimeZone(date_format.getTimeZone());
  return result;
}
References v8::internal::DCHECK(), DCHECK_NE, GetSkeletonForPatternKind(), v8::base::internal::result, SkeletonFromDateFormat(), and v8::internal::status.
Referenced by CallICUFormat().
GetSkeletonForPatternKind()
icu::UnicodeString v8::internal::anonymous_namespace{js-date-time-format.cc}::GetSkeletonForPatternKind (const icu::UnicodeString & input, PatternKind kind)
Definition at line 1131 of file js-date-time-format.cc.
                                                               {
  // [[weekday]] skeleton could be one or more 'E' or 'c'.
  // [[era]] skeleton could be one or more 'G'.
  // [[year]] skeleton could be one or more 'y'.
  // [[month]] skeleton could be one or more 'M' or 'L'.
  // [[day]] skeleton could be one or more 'd'.
  // [[hour]] skeleton could be one or more 'h', 'H', 'k', 'K', or 'j'.
  // [[minute]] skeleton could be one or more 'm'.
  // [[second]] skeleton could be one or more 's'.
  // [[dayPeriod]] skeleton could be one or more 'b', 'B' or 'a'.
  // [[fractionalSecondDigits]] skeleton could be one or more 'S'.
  // [[timeZoneName]] skeleton could be one or more 'z', 'O', or 'v'.
  switch (kind) {
    case PatternKind::kDate:
      return input;
    case PatternKind::kPlainDate:
      return KeepSupportedAddDefault(
          // Supported fields: [[weekday]], [[era]], [[year]], [[month]],
          // [[day]]
          input, {'E', 'c', 'G', 'y', 'M', 'L', 'd'},
          // Default fields: [[year]], [[month]], [[day]]
          {'y', 'M', 'd'});
    case PatternKind::kPlainYearMonth:
      return KeepSupportedAddDefault(
          // Supported fields: [[era]], [[year]], [[month]]
          input, {'G', 'y', 'M', 'L'},
          // Default fields: [[year]], [[month]]
          {'y', 'M'});
    case PatternKind::kPlainMonthDay:
      return KeepSupportedAddDefault(
          // Supported fields: [[month]] [[day]]
          input, {'M', 'L', 'd'},
          // Default fields: [[month]] [[day]]
          {'M', 'd'});
    case PatternKind::kPlainTime:
      return KeepSupportedAddDefault(
          input,
          // Supported fields: [[hour]], [[minute]], [[second]], [[dayPeriod]],
          // [[fractionalSecondDigits]]
          {'h', 'H', 'k', 'K', 'j', 'm', 's', 'B', 'b', 'a', 'S'},
          // Default fields: [[hour]], [[minute]],
          // [[second]]
          {'j', 'm', 's'});
    case PatternKind::kPlainDateTime:
      // Row TemporalInstantPattern is the same as TemporalPlainDateTimePattern
      // in Table 16: Supported fields for Temporal patterns
      // #table-temporal-patterns
      [[fallthrough]];
    case PatternKind::kInstant:
      return KeepSupportedAddDefault(
          input,
          // Supported fields: [[weekday]], [[era]], [[year]], [[month]],
          // [[day]], [[hour]], [[minute]], [[second]], [[dayPeriod]],
          // [[fractionalSecondDigits]]
          {'E', 'c', 'G', 'y', 'M', 'L', 'd', 'h', 'H', 'k', 'K', 'j', 'm', 's',
           'B', 'b', 'a', 'S'},
          // Default fields: [[year]], [[month]], [[day]], [[hour]], [[minute]],
          // [[second]]
          {'y', 'M', 'd', 'j', 'm', 's'});
    case PatternKind::kZonedDateTime:
      return KeepSupportedAddDefault(
          // Supported fields: [[weekday]], [[era]], [[year]], [[month]],
          // [[day]], [[hour]], [[minute]], [[second]], [[dayPeriod]],
          // [[fractionalSecondDigits]], [[timeZoneName]]
          input, {'E', 'c', 'G', 'y', 'M', 'L', 'd', 'h', 'H', 'k', 'K',
                  'j', 'm', 's', 'B', 'b', 'a', 'S', 'z', 'O', 'v'},
          // Default fields: [[year]], [[month]], [[day]], [[hour]], [[minute]],
          // [[second]], [[timeZoneName]]
          {'y', 'M', 'd', 'j', 'm', 's', 'z'});
  }
}
References KeepSupportedAddDefault().
Referenced by GetSimpleDateTimeForTemporal(), and LazyCreateDateIntervalFormat().
GetTimeZone()
DirectHandle<Object> v8::internal::anonymous_namespace{js-date-time-format.cc}::GetTimeZone (Isolate * isolate, const icu::SimpleDateFormat & simple_date_format)
Definition at line 625 of file js-date-time-format.cc.
                                                                     {
  return JSDateTimeFormat::TimeZoneId(
      isolate, simple_date_format.getCalendar()->getTimeZone());
}
References v8::internal::JSDateTimeFormat::TimeZoneId().
Referenced by v8::internal::JSDateTimeFormat::TimeZone().
HandleDateTimeOthers()
Maybe<DateTimeValueRecord> v8::internal::anonymous_namespace{js-date-time-format.cc}::HandleDateTimeOthers (Isolate * isolate, const icu::SimpleDateFormat & date_time_format, DirectHandle< Object > x_obj, const char * method_name)
Definition at line 996 of file js-date-time-format.cc.
                                                         {
  // 1. Assert: ! IsTemporalObject(x) is false.
  DCHECK(!IsTemporalObject(x_obj));
  // 2. Let pattern be dateTimeFormat.[[Pattern]].
  // 3. Let rangePatterns be dateTimeFormat.[[RangePatterns]].
  // 4. If x is undefined, then
  double x;
  if (IsUndefined(*x_obj)) {
    // a. Set x to ! Call(%Date.now%, undefined).
    x = static_cast<double>(JSDate::CurrentTimeValue(isolate));
    // 5. Else,
  } else {
    // a. Set x to ? ToNumber(x).
    ASSIGN_RETURN_ON_EXCEPTION_VALUE(isolate, x_obj,
                                     Object::ToNumber(isolate, x_obj),
                                     Nothing<DateTimeValueRecord>());
    x = Object::NumberValue(*x_obj);
  }
  // 6. Set x to TimeClip(x).
  // 7. If x is NaN, throw a RangeError exception.
  if (!DateCache::TryTimeClip(&x)) {
    THROW_NEW_ERROR_RETURN_VALUE(
        isolate, NewRangeError(MessageTemplate::kInvalidTimeValue),
        Nothing<DateTimeValueRecord>());
  }
  // 8. Let epochNanoseconds be (x) 10^6.
  // 9. Return the Record { [[pattern]]: pattern, [[rangePatterns]]:
  // rangePatterns, [[epochNanoseconds]]: epochNanoseconds }.
  return Just(DateTimeValueRecord({x, PatternKind::kDate}));
}
References ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::JSDate::CurrentTimeValue(), v8::internal::DCHECK(), IsTemporalObject(), v8::Just(), v8::internal::Object::NumberValue(), THROW_NEW_ERROR_RETURN_VALUE, v8::Value::ToNumber(), and v8::internal::DateCache::TryTimeClip().
Referenced by HandleDateTimeValue().
HandleDateTimeValue()
Maybe<DateTimeValueRecord> v8::internal::anonymous_namespace{js-date-time-format.cc}::HandleDateTimeValue (Isolate * isolate, const icu::SimpleDateFormat & date_time_format, DirectHandle< String > date_time_format_calendar, DirectHandle< Object > x, const char * method_name)
Definition at line 1034 of file js-date-time-format.cc.
                             {
#ifdef V8_TEMPORAL_SUPPORT
  if (IsTemporalObject(x)) {
    // a. If x has an [[InitializedTemporalDate]] internal slot, then
    if (IsJSTemporalPlainDate(*x)) {
      // i. Return ? HandleDateTimeTemporalDate(dateTimeFormat, x).
      return HandleDateTimeTemporalDate(
          isolate, date_time_format, date_time_format_calendar,
          Cast<JSTemporalPlainDate>(x), method_name);
    }
    // b. If x has an [[InitializedTemporalYearMonth]] internal slot, then
    if (IsJSTemporalPlainYearMonth(*x)) {
      // i. Return ? HandleDateTimeTemporalYearMonth(dateTimeFormat, x).
      return HandleDateTimeTemporalYearMonth(
          isolate, date_time_format, date_time_format_calendar,
          Cast<JSTemporalPlainYearMonth>(x), method_name);
    }
    // c. If x has an [[InitializedTemporalMonthDay]] internal slot, then
    if (IsJSTemporalPlainMonthDay(*x)) {
      // i. Return ? HandleDateTimeTemporalMonthDay(dateTimeFormat, x).
      return HandleDateTimeTemporalMonthDay(
          isolate, date_time_format, date_time_format_calendar,
          Cast<JSTemporalPlainMonthDay>(x), method_name);
    }
    // d. If x has an [[InitializedTemporalTime]] internal slot, then
    if (IsJSTemporalPlainTime(*x)) {
      // i. Return ? HandleDateTimeTemporalTime(dateTimeFormat, x).
      return HandleDateTimeTemporalTime(
          isolate, date_time_format, Cast<JSTemporalPlainTime>(x), method_name);
    }
    // e. If x has an [[InitializedTemporalDateTime]] internal slot, then
    if (IsJSTemporalPlainDateTime(*x)) {
      // i. Return ? HandleDateTimeTemporalDateTime(dateTimeFormat, x).
      return HandleDateTimeTemporalDateTime(
          isolate, date_time_format, date_time_format_calendar,
          Cast<JSTemporalPlainDateTime>(x), method_name);
    }
    // f. If x has an [[InitializedTemporalInstant]] internal slot, then
    if (IsJSTemporalInstant(*x)) {
      // i. Return ? HandleDateTimeTemporalInstant(dateTimeFormat, x).
      return HandleDateTimeTemporalInstant(
          isolate, date_time_format, Cast<JSTemporalInstant>(x), method_name);
    }
    // g. Assert: x has an [[InitializedTemporalZonedDateTime]] internal slot.
    DCHECK(IsJSTemporalZonedDateTime(*x));
    // h. Return ? HandleDateTimeTemporalZonedDateTime(dateTimeFormat, x).
    return HandleDateTimeTemporalZonedDateTime(
        isolate, date_time_format, date_time_format_calendar,
        Cast<JSTemporalZonedDateTime>(x), method_name);
  }
#endif // V8_TEMPORAL_SUPPORT
  // 2. Return ? HandleDateTimeOthers(dateTimeFormat, x).
  return HandleDateTimeOthers(isolate, date_time_format, x, method_name);
}
References v8::internal::DCHECK(), HandleDateTimeOthers(), and IsTemporalObject().
Referenced by FormatDateTimeWithTemporalSupport(), FormatRangeCommonWithTemporalSupport(), and FormatToPartsWithTemporalSupport().
HourCycleFromPattern()
JSDateTimeFormat::HourCycle v8::internal::anonymous_namespace{js-date-time-format.cc}::HourCycleFromPattern (const icu::UnicodeString pattern)
Definition at line 1772 of file js-date-time-format.cc.
                                    {
  bool in_quote = false;
  for (int32_t i = 0; i < pattern.length(); i++) {
    char16_t ch = pattern[i];
    switch (ch) {
      case '\'':
        in_quote = !in_quote;
        break;
      case 'K':
        if (!in_quote) return JSDateTimeFormat::HourCycle::kH11;
        break;
      case 'h':
        if (!in_quote) return JSDateTimeFormat::HourCycle::kH12;
        break;
      case 'H':
        if (!in_quote) return JSDateTimeFormat::HourCycle::kH23;
        break;
      case 'k':
        if (!in_quote) return JSDateTimeFormat::HourCycle::kH24;
        break;
    }
  }
  return JSDateTimeFormat::HourCycle::kUndefined;
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::JSDateTimeFormat::kH11, v8::internal::JSDateTimeFormat::kH12, v8::internal::JSDateTimeFormat::kH23, v8::internal::JSDateTimeFormat::kH24, and v8::internal::JSDateTimeFormat::kUndefined.
Referenced by DateTimeStylePattern().
IcuDateFieldIdToDateType()
DirectHandle<String> v8::internal::anonymous_namespace{js-date-time-format.cc}::IcuDateFieldIdToDateType (int32_t field_id, Isolate * isolate)
Definition at line 2491 of file js-date-time-format.cc.
                                                                {
  switch (field_id) {
    case -1:
      return isolate->factory()->literal_string();
    case UDAT_YEAR_FIELD:
    case UDAT_EXTENDED_YEAR_FIELD:
      return isolate->factory()->year_string();
    case UDAT_YEAR_NAME_FIELD:
      return isolate->factory()->yearName_string();
    case UDAT_MONTH_FIELD:
    case UDAT_STANDALONE_MONTH_FIELD:
      return isolate->factory()->month_string();
    case UDAT_DATE_FIELD:
      return isolate->factory()->day_string();
    case UDAT_HOUR_OF_DAY1_FIELD:
    case UDAT_HOUR_OF_DAY0_FIELD:
    case UDAT_HOUR1_FIELD:
    case UDAT_HOUR0_FIELD:
      return isolate->factory()->hour_string();
    case UDAT_MINUTE_FIELD:
      return isolate->factory()->minute_string();
    case UDAT_SECOND_FIELD:
      return isolate->factory()->second_string();
    case UDAT_DAY_OF_WEEK_FIELD:
    case UDAT_DOW_LOCAL_FIELD:
    case UDAT_STANDALONE_DAY_FIELD:
      return isolate->factory()->weekday_string();
    case UDAT_AM_PM_FIELD:
    case UDAT_AM_PM_MIDNIGHT_NOON_FIELD:
    case UDAT_FLEXIBLE_DAY_PERIOD_FIELD:
      return isolate->factory()->dayPeriod_string();
    case UDAT_TIMEZONE_FIELD:
    case UDAT_TIMEZONE_RFC_FIELD:
    case UDAT_TIMEZONE_GENERIC_FIELD:
    case UDAT_TIMEZONE_SPECIAL_FIELD:
    case UDAT_TIMEZONE_LOCALIZED_GMT_OFFSET_FIELD:
    case UDAT_TIMEZONE_ISO_FIELD:
    case UDAT_TIMEZONE_ISO_LOCAL_FIELD:
      return isolate->factory()->timeZoneName_string();
    case UDAT_ERA_FIELD:
      return isolate->factory()->era_string();
    case UDAT_FRACTIONAL_SECOND_FIELD:
      return isolate->factory()->fractionalSecond_string();
    case UDAT_RELATED_YEAR_FIELD:
      return isolate->factory()->relatedYear_string();
    case UDAT_QUARTER_FIELD:
    case UDAT_STANDALONE_QUARTER_FIELD:
    default:
      // Other UDAT_*_FIELD's cannot show up because there is no way to specify
      // them via options of Intl.DateTimeFormat.
      UNREACHABLE();
  }
}
References v8::internal::Isolate::factory(), and v8::internal::UNREACHABLE().
Referenced by AddPartForFormatRange(), and FieldPositionIteratorToArray().
IsAsciiAlpha()
bool v8::internal::anonymous_namespace{js-date-time-format.cc}::IsAsciiAlpha (char ch)
Definition at line 393 of file js-date-time-format.cc.
                           {
  return base::IsInRange(ch, 'A', 'Z') || base::IsInRange(ch, 'a', 'z');
}
Referenced by ToTitleCaseTimezoneLocation().
IsTemporalObject()
bool v8::internal::anonymous_namespace{js-date-time-format.cc}::IsTemporalObject (DirectHandle< Object > value)
Definition at line 811 of file js-date-time-format.cc.
                                                  {
#ifdef V8_TEMPORAL_SUPPORT
  // 1. If Type(value) is not Object, then
  if (!IsJSReceiver(*value)) {
    // a. Return false.
    return false;
  }
  // 2. If value does not have an [[InitializedTemporalDate]],
  // [[InitializedTemporalTime]], [[InitializedTemporalDateTime]],
  // [[InitializedTemporalZonedDateTime]], [[InitializedTemporalYearMonth]],
  // [[InitializedTemporalMonthDay]], or [[InitializedTemporalInstant]] internal
  // slot, then
  if (!IsJSTemporalPlainDate(*value) && !IsJSTemporalPlainTime(*value) &&
      !IsJSTemporalPlainDateTime(*value) &&
      !IsJSTemporalZonedDateTime(*value) &&
      !IsJSTemporalPlainYearMonth(*value) &&
      !IsJSTemporalPlainMonthDay(*value) && !IsJSTemporalInstant(*value)) {
    // a. Return false.
    return false;
  }
  // 3. Return true.
  return true;
#else // V8_TEMPORAL_SUPPORT
  return false;
#endif // V8_TEMPORAL_SUPPORT
}
References v8::internal::value.
Referenced by FormatRangeCommonWithTemporalSupport(), HandleDateTimeOthers(), HandleDateTimeValue(), and SameTemporalType().
KeepSupportedAddDefault()
icu::UnicodeString v8::internal::anonymous_namespace{js-date-time-format.cc}::KeepSupportedAddDefault (const icu::UnicodeString & input, const std::set< char16_t > & keep, const std::set< char16_t > & add_default)
Definition at line 1102 of file js-date-time-format.cc.
                                         {
  const std::map<char16_t, char16_t> equivalent({{'L', 'M'},
                                                 {'h', 'j'},
                                                 {'H', 'j'},
                                                 {'k', 'j'},
                                                 {'K', 'j'},
                                                 {'O', 'z'},
                                                 {'v', 'z'}});
  std::set<char16_t> to_be_added(add_default);
  icu::UnicodeString result;
  for (int32_t i = 0; i < input.length(); i++) {
    char16_t ch = input.charAt(i);
    if (keep.find(ch) != keep.end()) {
      to_be_added.erase(ch);
      auto also = equivalent.find(ch);
      if (also != equivalent.end()) {
        to_be_added.erase(also->second);
      }
      result.append(ch);
    }
  }
  for (auto it = to_be_added.begin(); it != to_be_added.end(); ++it) {
    result.append(*it);
  }
  return result;
}
References v8::base::internal::result.
Referenced by GetSkeletonForPatternKind().
LazyCreateDateIntervalFormat()
std::unique_ptr<icu::DateIntervalFormat> v8::internal::anonymous_namespace{js-date-time-format.cc}::LazyCreateDateIntervalFormat (Isolate * isolate, DirectHandle< JSDateTimeFormat > date_time_format, PatternKind kind)
Definition at line 1732 of file js-date-time-format.cc.
                      {
  Tagged<Managed<icu::DateIntervalFormat>> managed_format =
      date_time_format->icu_date_interval_format();
  if (kind == PatternKind::kDate && managed_format->get()) {
    return std::unique_ptr<icu::DateIntervalFormat>(
        managed_format->raw()->clone());
  }
  UErrorCode status = U_ZERO_ERROR;
  icu::Locale loc = *(date_time_format->icu_locale()->raw());
  // We need to pass in the hc to DateIntervalFormat by using Unicode 'hc'
  // extension.
  std::string hcString = ToHourCycleString(date_time_format->hour_cycle());
  if (!hcString.empty()) {
    loc.setUnicodeKeywordValue("hc", hcString, status);
  }
  icu::SimpleDateFormat* icu_simple_date_format =
      date_time_format->icu_simple_date_format()->raw();
  icu::UnicodeString skeleton = GetSkeletonForPatternKind(
      SkeletonFromDateFormat(*icu_simple_date_format), kind);
  std::unique_ptr<icu::DateIntervalFormat> date_interval_format(
      icu::DateIntervalFormat::createInstance(skeleton, loc, status));
  DCHECK(U_SUCCESS(status));
  date_interval_format->setTimeZone(icu_simple_date_format->getTimeZone());
  if (kind != PatternKind::kDate) {
    return date_interval_format;
  }
  DirectHandle<Managed<icu::DateIntervalFormat>> managed_interval_format =
      Managed<icu::DateIntervalFormat>::From(isolate, 0,
                                             std::move(date_interval_format));
  date_time_format->set_icu_date_interval_format(*managed_interval_format);
  return std::unique_ptr<icu::DateIntervalFormat>(
      managed_interval_format->raw()->clone());
}
References v8::internal::DCHECK(), v8::internal::Managed< CppType >::From(), GetSkeletonForPatternKind(), v8::internal::icu_simple_date_format, v8::internal::loc, SkeletonFromDateFormat(), v8::internal::status, v8::internal::string, and ToHourCycleString().
Referenced by FormatRangeCommonWithTemporalSupport(), and PartitionDateTimeRangePattern().
LocaleIndependentAsciiToLower()
char v8::internal::anonymous_namespace{js-date-time-format.cc}::LocaleIndependentAsciiToLower (char ch)
Definition at line 404 of file js-date-time-format.cc.
                                            {
  return (base::IsInRange(ch, 'A', 'Z')) ? (ch - 'A' + 'a') : ch;
}
Referenced by ToTitleCaseTimezoneLocation().
LocaleIndependentAsciiToUpper()
char v8::internal::anonymous_namespace{js-date-time-format.cc}::LocaleIndependentAsciiToUpper (char ch)
Definition at line 399 of file js-date-time-format.cc.
                                            {
  return (base::IsInRange(ch, 'a', 'z')) ? (ch - 'a' + 'A') : ch;
}
Referenced by v8::internal::anonymous_namespace{js-date-time-format.cc}::SpecialTimeZoneMap::Add(), v8::internal::JSDateTimeFormat::CanonicalizeTimeZoneID(), and ToTitleCaseTimezoneLocation().
PartitionDateTimeRangePattern()
template<typename T , std::optional< MaybeDirectHandle< T >>(*)(Isolate *, const icu::FormattedValue &) Format>
std::optional<MaybeDirectHandle<T> > v8::internal::anonymous_namespace{js-date-time-format.cc}::PartitionDateTimeRangePattern (Isolate * isolate, DirectHandle< JSDateTimeFormat > date_time_format, double x, double y, const char * method_name)
Definition at line 2833 of file js-date-time-format.cc.
                                       {
  // 1. Let x be TimeClip(x).
  // 2. If x is NaN, throw a RangeError exception.
  if (!DateCache::TryTimeClip(&x)) {
    THROW_NEW_ERROR(isolate, NewRangeError(MessageTemplate::kInvalidTimeValue));
  }
  // 3. Let y be TimeClip(y).
  // 4. If y is NaN, throw a RangeError exception.
  if (!DateCache::TryTimeClip(&y)) {
    THROW_NEW_ERROR(isolate, NewRangeError(MessageTemplate::kInvalidTimeValue));
  }
  std::unique_ptr<icu::DateIntervalFormat> format(LazyCreateDateIntervalFormat(
      isolate, date_time_format, PatternKind::kDate));
  if (format.get() == nullptr) {
    THROW_NEW_ERROR(isolate, NewTypeError(MessageTemplate::kIcuError));
  }
  icu::SimpleDateFormat* date_format =
      date_time_format->icu_simple_date_format()->raw();
  const icu::Calendar* calendar = date_format->getCalendar();
  return CallICUFormatRange<T, Format>(isolate, format.get(), calendar, x, y);
}
References v8::internal::format, LazyCreateDateIntervalFormat(), THROW_NEW_ERROR, v8::internal::DateCache::TryTimeClip(), and v8::internal::y.
ReplaceHourCycleInPattern()
icu::UnicodeString v8::internal::anonymous_namespace{js-date-time-format.cc}::ReplaceHourCycleInPattern (icu::UnicodeString pattern, JSDateTimeFormat::HourCycle hc)
Definition at line 1602 of file js-date-time-format.cc.
                                                                           {
  char16_t replacement;
  switch (hc) {
    case JSDateTimeFormat::HourCycle::kUndefined:
      return pattern;
    case JSDateTimeFormat::HourCycle::kH11:
      replacement = 'K';
      break;
    case JSDateTimeFormat::HourCycle::kH12:
      replacement = 'h';
      break;
    case JSDateTimeFormat::HourCycle::kH23:
      replacement = 'H';
      break;
    case JSDateTimeFormat::HourCycle::kH24:
      replacement = 'k';
      break;
  }
  bool replace = true;
  icu::UnicodeString result;
  char16_t last = u'\0';
  for (int32_t i = 0; i < pattern.length(); i++) {
    char16_t ch = pattern.charAt(i);
    switch (ch) {
      case '\'':
        replace = !replace;
        result.append(ch);
        break;
      case 'H':
        [[fallthrough]];
      case 'h':
        [[fallthrough]];
      case 'K':
        [[fallthrough]];
      case 'k':
        // If the previous field is a day, add a space before the hour.
        if (replace && last == u'd') {
          result.append(' ');
        }
        result.append(replace ? replacement : ch);
        break;
      default:
        result.append(ch);
        break;
    }
    last = ch;
  }
  return result;
}
References v8::internal::JSDateTimeFormat::kH11, v8::internal::JSDateTimeFormat::kH12, v8::internal::JSDateTimeFormat::kH23, v8::internal::JSDateTimeFormat::kH24, v8::internal::JSDateTimeFormat::kUndefined, and v8::base::internal::result.
Referenced by CreateICUDateFormat().
ReplaceSkeleton()
icu::UnicodeString v8::internal::anonymous_namespace{js-date-time-format.cc}::ReplaceSkeleton (const icu::UnicodeString input, JSDateTimeFormat::HourCycle hc)
Definition at line 1814 of file js-date-time-format.cc.
                                                                 {
  icu::UnicodeString result;
  char16_t to;
  switch (hc) {
    case JSDateTimeFormat::HourCycle::kH11:
      to = 'K';
      break;
    case JSDateTimeFormat::HourCycle::kH12:
      to = 'h';
      break;
    case JSDateTimeFormat::HourCycle::kH23:
      to = 'H';
      break;
    case JSDateTimeFormat::HourCycle::kH24:
      to = 'k';
      break;
    case JSDateTimeFormat::HourCycle::kUndefined:
      UNREACHABLE();
  }
  for (int32_t i = 0; i < input.length(); i++) {
    switch (input[i]) {
      // We need to skip 'a', 'b', 'B' here due to
      // https://unicode-org.atlassian.net/browse/ICU-20437
      case 'a':
        [[fallthrough]];
      case 'b':
        [[fallthrough]];
      case 'B':
        // ignore
        break;
      case 'h':
        [[fallthrough]];
      case 'H':
        [[fallthrough]];
      case 'K':
        [[fallthrough]];
      case 'k':
        result += to;
        break;
      default:
        result += input[i];
        break;
    }
  }
  return result;
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::JSDateTimeFormat::kH11, v8::internal::JSDateTimeFormat::kH12, v8::internal::JSDateTimeFormat::kH23, v8::internal::JSDateTimeFormat::kH24, v8::internal::JSDateTimeFormat::kUndefined, v8::base::internal::result, and v8::internal::UNREACHABLE().
Referenced by DateTimeStylePattern().
SameTemporalType()
bool v8::internal::anonymous_namespace{js-date-time-format.cc}::SameTemporalType (DirectHandle< Object > x, DirectHandle< Object > y)
Definition at line 839 of file js-date-time-format.cc.
                                                                      {
#ifdef V8_TEMPORAL_SUPPORT
  // 1. If either of ! IsTemporalObject(x) or ! IsTemporalObject(y) is false,
  // return false.
  if (!IsTemporalObject(x)) return false;
  if (!IsTemporalObject(y)) return false;
  // 2. If x has an [[InitializedTemporalDate]] internal slot and y does not,
  // return false.
  if (IsJSTemporalPlainDate(*x) && !IsJSTemporalPlainDate(*y)) return false;
  // 3. If x has an [[InitializedTemporalTime]] internal slot and y does not,
  // return false.
  if (IsJSTemporalPlainTime(*x) && !IsJSTemporalPlainTime(*y)) return false;
  // 4. If x has an [[InitializedTemporalDateTime]] internal slot and y does
  // not, return false.
  if (IsJSTemporalPlainDateTime(*x) && !IsJSTemporalPlainDateTime(*y)) {
    return false;
  }
  // 5. If x has an [[InitializedTemporalZonedDateTime]] internal slot and y
  // does not, return false.
  if (IsJSTemporalZonedDateTime(*x) && !IsJSTemporalZonedDateTime(*y)) {
    return false;
  }
  // 6. If x has an [[InitializedTemporalYearMonth]] internal slot and y does
  // not, return false.
  if (IsJSTemporalPlainYearMonth(*x) && !IsJSTemporalPlainYearMonth(*y)) {
    return false;
  }
  // 7. If x has an [[InitializedTemporalMonthDay]] internal slot and y does
  // not, return false.
  if (IsJSTemporalPlainMonthDay(*x) && !IsJSTemporalPlainMonthDay(*y)) {
    return false;
  }
  // 8. If x has an [[InitializedTemporalInstant]] internal slot and y does not,
  // return false.
  if (IsJSTemporalInstant(*x) && !IsJSTemporalInstant(*y)) return false;
  // 9. Return true.
  return true;
#else // V8_TEMPORAL_SUPPORT
  return false;
#endif // V8_TEMPORAL_SUPPORT
}
References IsTemporalObject(), and v8::internal::y.
Referenced by FormatRangeCommonWithTemporalSupport().
SkeletonFromDateFormat()
icu::UnicodeString v8::internal::anonymous_namespace{js-date-time-format.cc}::SkeletonFromDateFormat (const icu::SimpleDateFormat & icu_date_format)
Definition at line 1208 of file js-date-time-format.cc.
                                                {
  icu::UnicodeString pattern;
  pattern = icu_date_format.toPattern(pattern);
  UErrorCode status = U_ZERO_ERROR;
  icu::UnicodeString skeleton =
      icu::DateTimePatternGenerator::staticGetSkeleton(pattern, status);
  DCHECK(U_SUCCESS(status));
  return skeleton;
}
References v8::internal::DCHECK(), and v8::internal::status.
Referenced by GetSimpleDateTimeForTemporal(), and LazyCreateDateIntervalFormat().
ToHourCycle() [1/2]
JSDateTimeFormat::HourCycle v8::internal::anonymous_namespace{js-date-time-format.cc}::ToHourCycle (const std::string & hc)
Definition at line 60 of file js-date-time-format.cc.
                                                           {
  if (hc == "h11") return JSDateTimeFormat::HourCycle::kH11;
  if (hc == "h12") return JSDateTimeFormat::HourCycle::kH12;
  if (hc == "h23") return JSDateTimeFormat::HourCycle::kH23;
  if (hc == "h24") return JSDateTimeFormat::HourCycle::kH24;
  return JSDateTimeFormat::HourCycle::kUndefined;
}
References v8::internal::JSDateTimeFormat::kH11, v8::internal::JSDateTimeFormat::kH12, v8::internal::JSDateTimeFormat::kH23, v8::internal::JSDateTimeFormat::kH24, and v8::internal::JSDateTimeFormat::kUndefined.
ToHourCycle() [2/2]
JSDateTimeFormat::HourCycle v8::internal::anonymous_namespace{js-date-time-format.cc}::ToHourCycle (UDateFormatHourCycle hc)
Definition at line 68 of file js-date-time-format.cc.
                                                               {
  switch (hc) {
    case UDAT_HOUR_CYCLE_11:
      return JSDateTimeFormat::HourCycle::kH11;
    case UDAT_HOUR_CYCLE_12:
      return JSDateTimeFormat::HourCycle::kH12;
    case UDAT_HOUR_CYCLE_23:
      return JSDateTimeFormat::HourCycle::kH23;
    case UDAT_HOUR_CYCLE_24:
      return JSDateTimeFormat::HourCycle::kH24;
    default:
      return JSDateTimeFormat::HourCycle::kUndefined;
  }
}
References v8::internal::JSDateTimeFormat::kH11, v8::internal::JSDateTimeFormat::kH12, v8::internal::JSDateTimeFormat::kH23, v8::internal::JSDateTimeFormat::kH24, and v8::internal::JSDateTimeFormat::kUndefined.
Referenced by v8::internal::JSDateTimeFormat::CreateDateTimeFormat().
ToHourCycleString()
std::string v8::internal::anonymous_namespace{js-date-time-format.cc}::ToHourCycleString (JSDateTimeFormat::HourCycle hc)
Definition at line 43 of file js-date-time-format.cc.
                                                          {
  switch (hc) {
    case JSDateTimeFormat::HourCycle::kH11:
      return "h11";
    case JSDateTimeFormat::HourCycle::kH12:
      return "h12";
    case JSDateTimeFormat::HourCycle::kH23:
      return "h23";
    case JSDateTimeFormat::HourCycle::kH24:
      return "h24";
    case JSDateTimeFormat::HourCycle::kUndefined:
      return "";
    default:
      UNREACHABLE();
  }
}
References v8::internal::JSDateTimeFormat::kH11, v8::internal::JSDateTimeFormat::kH12, v8::internal::JSDateTimeFormat::kH23, v8::internal::JSDateTimeFormat::kH24, v8::internal::JSDateTimeFormat::kUndefined, and v8::internal::UNREACHABLE().
Referenced by LazyCreateDateIntervalFormat().
ToTitleCaseTimezoneLocation()
std::string v8::internal::anonymous_namespace{js-date-time-format.cc}::ToTitleCaseTimezoneLocation (const std::string & input)
Definition at line 413 of file js-date-time-format.cc.
                                                              {
  std::string title_cased;
  int word_length = 0;
  for (char ch : input) {
    // Convert first char to upper case, the rest to lower case
    if (IsAsciiAlpha(ch)) {
      title_cased += word_length == 0 ? LocaleIndependentAsciiToUpper(ch)
                                      : LocaleIndependentAsciiToLower(ch);
      word_length++;
    } else if (ch == '_' || ch == '-' || ch == '/') {
      // Special case Au/Es/Of to be lower case.
      if (word_length == 2) {
        size_t pos = title_cased.length() - 2;
        std::string substr = title_cased.substr(pos, 2);
        if (substr == "Of" || substr == "Es" || substr == "Au") {
          title_cased[pos] = LocaleIndependentAsciiToLower(title_cased[pos]);
        }
      }
      title_cased += ch;
      word_length = 0;
    } else {
      // Invalid input
      return std::string();
    }
  }
  return title_cased;
}
References IsAsciiAlpha(), LocaleIndependentAsciiToLower(), LocaleIndependentAsciiToUpper(), and v8::internal::string.
Referenced by v8::internal::JSDateTimeFormat::CanonicalizeTimeZoneID().
Variable Documentation
k2DigitNumeric
const auto v8::internal::anonymous_namespace{js-date-time-format.cc}::k2DigitNumeric [static]
Initial value:
=
    std::to_array<std::string_view>({"2-digit", "numeric"})
Definition at line 165 of file js-date-time-format.cc.
Referenced by BuildPatternItems(), and CreateData().