wasm Namespace Reference
Namespaces
 anonymous_namespace{c-api.cc}
Classes
struct implement
struct ConfigImpl
struct implement< Config >
struct EngineImpl
struct implement< Engine >
struct ManagedData
struct implement< Store >
struct ValTypeImpl
struct implement< ValType >
struct ExternTypeImpl
struct implement< ExternType >
struct FuncTypeImpl
struct implement< FuncType >
struct GlobalTypeImpl
struct implement< GlobalType >
struct TableTypeImpl
struct implement< TableType >
struct MemoryTypeImpl
struct implement< MemoryType >
struct ImportTypeImpl
struct implement< ImportType >
struct ExportTypeImpl
struct implement< ExportType >
class RefImpl
struct implement< Ref >
struct implement< Frame >
struct implement< Trap >
struct implement< Foreign >
struct implement< Module >
struct implement< Shared< Module > >
struct implement< Extern >
struct implement< Func >
struct FuncData
struct implement< Global >
struct implement< Table >
struct implement< Memory >
struct implement< Instance >
class StoreImpl
Functions
void WASM_UNIMPLEMENTED (const char *s)
BEGIN FILE wasm-v8.cc.
template<class T >
void ignore (T)
template<class C >
auto impl (C *x) -> typename implement< C >::type *
template<class C >
auto impl (const C *x) -> const typename implement< C >::type *
template<class C >
auto seal (typename implement< C >::type *x) -> C *
template<class C >
auto seal (const typename implement< C >::type *x) -> const C *
void CheckAndHandleInterrupts (i::Isolate *isolate)
i::DirectHandle< i::String > VecToString (i::Isolate *isolate, const vec< byte_t > &chars)
ownvec< ExportType > ExportsImpl (i::DirectHandle< i::WasmModuleObject > module_obj)
auto extern_to_v8 (const Extern *ex) -> i::DirectHandle< i::JSReceiver >
Variables
ValTypeImpl * valtype_i32 = new ValTypeImpl(ValKind::I32)
ValTypeImpl * valtype_i64 = new ValTypeImpl(ValKind::I64)
ValTypeImpl * valtype_f32 = new ValTypeImpl(ValKind::F32)
ValTypeImpl * valtype_f64 = new ValTypeImpl(ValKind::F64)
ValTypeImpl * valtype_externref = new ValTypeImpl(ValKind::EXTERNREF)
ValTypeImpl * valtype_funcref = new ValTypeImpl(ValKind::FUNCREF)
Function Documentation
CheckAndHandleInterrupts()
void wasm::CheckAndHandleInterrupts (i::Isolate * isolate)
Definition at line 460 of file c-api.cc.
                                                 {
  i::StackLimitCheck check(isolate);
  if (check.InterruptRequested()) {
    isolate->stack_guard()->HandleInterrupts();
  }
}
References v8::internal::StackGuard::HandleInterrupts(), v8::internal::StackLimitCheck::InterruptRequested(), and v8::internal::Isolate::stack_guard().
Referenced by wasm::anonymous_namespace{c-api.cc}::make_func().
ExportsImpl()
ownvec<ExportType> wasm::ExportsImpl (i::DirectHandle< i::WasmModuleObject > module_obj)
Definition at line 1275 of file c-api.cc.
                                                 {
  const i::wasm::NativeModule* native_module = module_obj->native_module();
  const i::wasm::WasmModule* module = native_module->module();
  const v8::base::Vector<const uint8_t> wire_bytes =
      native_module->wire_bytes();
  const std::vector<i::wasm::WasmExport>& export_table = module->export_table;
  size_t size = export_table.size();
  ownvec<ExportType> exports = ownvec<ExportType>::make_uninitialized(size);
  for (uint32_t i = 0; i < size; i++) {
    const i::wasm::WasmExport& exp = export_table[i];
    Name name = GetNameFromWireBytes(exp.name, wire_bytes);
    own<ExternType> type = GetImportExportType(module, exp.kind, exp.index);
    exports[i] = ExportType::make(std::move(name), std::move(type));
  }
  return exports;
}
References v8::base::ieee754::exp(), wasm::anonymous_namespace{c-api.cc}::GetImportExportType(), wasm::anonymous_namespace{c-api.cc}::GetNameFromWireBytes(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, name, size(), and v8::internal::tracing::type.
extern_to_v8()
auto wasm::extern_to_v8 (const Extern * ex) -> i::DirectHandle<i::JSReceiver>
Definition at line 1466 of file c-api.cc.
                                                                  {
  return impl(ex)->v8_object();
}
References impl().
ignore()
template<class T >
void wasm::ignore (T)
Definition at line 237 of file c-api.cc.
{}
Referenced by v8::internal::torque::TypeVisitor::ComputeType(), v8::internal::torque::ClassType::GenerateSliceAccessor(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::NextInIgnoreList(), v8::internal::PrintSpecial(), v8::internal::MarkCompactCollector::ProcessEphemerons(), v8::internal::torque::ReportAllUnusedMacros(), v8::internal::Isolate::ReportExceptionPropertyCallback(), v8::internal::RUNTIME_FUNCTION(), and v8::internal::IncrementalMarking::Step().
impl() [1/2]
template<class C >
auto wasm::impl (C * x) -> typename implement<C>::type*
Definition at line 243 of file c-api.cc.
                                              {
  return reinterpret_cast<typename implement<C>::type*>(x);
}
Referenced by v8::internal::FactoryBase< Impl >::AllocateRaw(), v8::internal::FactoryBase< Impl >::AllocateRawOneByteInternalizedString(), v8::internal::Builtins::AllowDynamicFunction(), v8::StdMapTraits< K, V >::Begin(), v8::internal::anonymous_namespace{builtins-function.cc}::CreateDynamicFunction(), v8::bigint::Processor::Divide(), v8::internal::Parser::DoParseFunction(), v8::StdMapTraits< K, V >::Empty(), v8::StdMapTraits< K, V >::End(), v8::Context::Enter(), v8::Context::Exit(), v8::internal::HandleScope::Extend(), extern_to_v8(), v8::internal::SharedMacroAssembler< Impl >::ExternalReferenceAsOperand(), v8::bigint::Processor::FromString(), v8::internal::torque::ImplementationVisitor::GeneratePrintDefinitions(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::GeneratePrintDefinitionsForClass(), v8::StdMapTraits< K, V >::Get(), v8::internal::RegExpMacroAssembler::ImplementationToString(), v8::internal::FactoryBase< Impl >::isolate(), wasm::anonymous_namespace{c-api.cc}::make_func(), v8::internal::compiler::PeeledIteration::map(), v8::bigint::Processor::Modulo(), v8::bigint::Processor::Multiply(), v8::bigint::Processor::New(), v8::internal::FactoryBase< Impl >::NewFixedArrayWithHoles(), v8::internal::FactoryBase< Impl >::NewFixedArrayWithZeroes(), v8::internal::FactoryBase< Impl >::NewFunctionTemplateRareData(), v8::internal::FactoryBase< Impl >::NewSwissNameDictionaryWithCapacity(), v8::internal::HandleScope::NumberOfHandles(), v8::internal::compiler::turboshaft::fast_hash< std::tuple< Ts... > >::operator()(), v8::internal::Parser::ParseClassForMemberInitialization(), v8::internal::Parser::ParseREPLProgram(), v8::internal::SharedMacroAssembler< Impl >::Pextrd(), v8::internal::SharedMacroAssembler< Impl >::Pinsrd(), v8::internal::GlobalBackingStoreRegistry::Purge(), v8::internal::FactoryBase< Impl >::read_only_roots(), v8::internal::FactoryBase< Impl >::RefineAllocationTypeForInPlaceInternalizableString(), v8::internal::GlobalBackingStoreRegistry::Register(), v8::StdMapTraits< K, V >::Remove(), v8::internal::RUNTIME_FUNCTION(), v8::StdMapTraits< K, V >::Set(), v8::Context::SetMicrotaskQueue(), v8::StdMapTraits< K, V >::Size(), v8::internal::FactoryBase< Impl >::ToBoolean(), v8::bigint::Processor::ToString(), v8::internal::GlobalBackingStoreRegistry::Unregister(), wasm::FuncData::v8_callback(), and wasm::anonymous_namespace{c-api.cc}::WasmRefToV8().
impl() [2/2]
template<class C >
auto wasm::impl (const C * x) -> const typename implement<C>::type*
Definition at line 248 of file c-api.cc.
                                                          {
  return reinterpret_cast<const typename implement<C>::type*>(x);
}
seal() [1/2]
template<class C >
auto wasm::seal (const typename implement< C >::type * x) -> const C*
Definition at line 258 of file c-api.cc.
                                                          {
  return reinterpret_cast<const C*>(x);
}
seal() [2/2]
template<class C >
auto wasm::seal (typename implement< C >::type * x) -> C*
Definition at line 253 of file c-api.cc.
                                              {
  return reinterpret_cast<C*>(x);
}
VecToString()
i::DirectHandle<i::String> wasm::VecToString (i::Isolate * isolate, const vec< byte_t > & chars)
Definition at line 946 of file c-api.cc.
                                                                 {
  size_t length = chars.size();
  // Some, but not all, {chars} vectors we get here are null-terminated,
  // so let's be robust to that.
  if (length > 0 && chars[length - 1] == 0) length--;
  return isolate->factory()
      ->NewStringFromUtf8({chars.get(), length})
      .ToHandleChecked();
}
References v8::internal::Isolate::factory(), v8::internal::length, and v8::internal::Factory::NewStringFromUtf8().
WASM_UNIMPLEMENTED()
void wasm::WASM_UNIMPLEMENTED (const char * s)
BEGIN FILE wasm-v8.cc.
Definition at line 231 of file c-api.cc.
                                                    {
  std::cerr << "Wasm API: " << s << " not supported yet!\n";
  exit(1);
}
Variable Documentation
valtype_externref
ValTypeImpl* wasm::valtype_externref = new ValTypeImpl(ValKind::EXTERNREF)
Definition at line 598 of file c-api.cc.
valtype_f32
ValTypeImpl* wasm::valtype_f32 = new ValTypeImpl(ValKind::F32)
Definition at line 596 of file c-api.cc.
valtype_f64
ValTypeImpl* wasm::valtype_f64 = new ValTypeImpl(ValKind::F64)
Definition at line 597 of file c-api.cc.
valtype_funcref
ValTypeImpl* wasm::valtype_funcref = new ValTypeImpl(ValKind::FUNCREF)
Definition at line 599 of file c-api.cc.
valtype_i32
ValTypeImpl* wasm::valtype_i32 = new ValTypeImpl(ValKind::I32)
Definition at line 594 of file c-api.cc.
valtype_i64
ValTypeImpl* wasm::valtype_i64 = new ValTypeImpl(ValKind::I64)
Definition at line 595 of file c-api.cc.