v8::platform Namespace Reference
Namespaces
 anonymous_namespace{default-job.cc}
 anonymous_namespace{default-platform.cc}
 tracing
Classes
class DefaultForegroundTaskRunner
class DefaultJobState
class DefaultJobHandle
class DefaultJobWorker
class DefaultPlatform
class DefaultThreadIsolatedAllocator
class DefaultWorkerThreadsTaskRunner
class DelayedTaskQueue
class TaskQueue
class WorkerThread
Enumerations
enum class IdleTaskSupport { kDisabled
, kEnabled
 }
enum class InProcessStackDumping { kDisabled
, kEnabled
 }
enum class MessageLoopBehavior : bool { kDoNotWait = false
, kWaitForWork = true
 }
enum class PriorityMode : bool { kDontApply
, kApply
 }
Functions
std::unique_ptr< v8::Platform > NewDefaultPlatform (int thread_pool_size=0, IdleTaskSupport idle_task_support=IdleTaskSupport::kDisabled, InProcessStackDumping in_process_stack_dumping=InProcessStackDumping::kDisabled, std::unique_ptr< v8::TracingController > tracing_controller={}, PriorityMode priority_mode=PriorityMode::kDontApply)
Returns a new instance of the default v8::Platform implementation.
std::unique_ptr< v8::Platform > NewSingleThreadedDefaultPlatform (IdleTaskSupport idle_task_support=IdleTaskSupport::kDisabled, InProcessStackDumping in_process_stack_dumping=InProcessStackDumping::kDisabled, std::unique_ptr< v8::TracingController > tracing_controller={})
The same as NewDefaultPlatform but disables the worker thread pool.
V8_PLATFORM_EXPORT std::unique_ptr< JobHandle > NewDefaultJobHandle (v8::Platform *platform, v8::TaskPriority priority, std::unique_ptr< v8::JobTask > job_task, size_t num_worker_threads)
Returns a new instance of the default v8::JobHandle implementation.
bool PumpMessageLoop (v8::Platform *platform, v8::Isolate *isolate, MessageLoopBehavior behavior=MessageLoopBehavior::kDoNotWait)
Pumps the message loop for the given isolate.
void RunIdleTasks (v8::Platform *platform, v8::Isolate *isolate, double idle_time_in_seconds)
Runs pending idle tasks for at most |idle_time_in_seconds| seconds.
void NotifyIsolateShutdown (v8::Platform *platform, Isolate *isolate)
Notifies the given platform about the Isolate getting deleted soon.
Enumeration Type Documentation
IdleTaskSupport
enum v8::platform::IdleTaskSupport [strong]
Enumerator
kDisabled
kEnabled
Definition at line 18 of file libplatform.h.
{ kDisabled, kEnabled };
InProcessStackDumping
enum v8::platform::InProcessStackDumping [strong]
Enumerator
kDisabled
kEnabled
Definition at line 19 of file libplatform.h.
{ kDisabled, kEnabled };
MessageLoopBehavior
enum v8::platform::MessageLoopBehavior : bool [strong]
Enumerator
kDoNotWait
kWaitForWork
Definition at line 21 of file libplatform.h.
                               : bool {
  kDoNotWait = false,
  kWaitForWork = true
};
PriorityMode
enum v8::platform::PriorityMode : bool [strong]
Enumerator
kDontApply
kApply
Definition at line 26 of file libplatform.h.
: bool { kDontApply, kApply };
Function Documentation
NewDefaultJobHandle()
V8_PLATFORM_EXPORT std::unique_ptr< v8::JobHandle > v8::platform::NewDefaultJobHandle (v8::Platform * platform, v8::TaskPriority priority, std::unique_ptr< v8::JobTask > job_task, size_t num_worker_threads)
Returns a new instance of the default v8::JobHandle implementation.
The job will be executed by spawning up to |num_worker_threads| many worker threads on the provided |platform| with the given |priority|.
Definition at line 72 of file default-platform.cc.
                                                                {
  return std::make_unique<DefaultJobHandle>(std::make_shared<DefaultJobState>(
      platform, std::move(job_task), priority, num_worker_threads));
}
Referenced by v8::platform::DefaultPlatform::CreateJobImpl(), and v8::PredictablePlatform::CreateJobImpl().
NewDefaultPlatform()
V8_PLATFORM_EXPORT std::unique_ptr< v8::Platform > v8::platform::NewDefaultPlatform (int thread_pool_size = 0, IdleTaskSupport idle_task_support = IdleTaskSupport::kDisabled, InProcessStackDumping in_process_stack_dumping = InProcessStackDumping::kDisabled, std::unique_ptr< v8::TracingController > tracing_controller = {}, PriorityMode priority_mode = PriorityMode::kDontApply)
Returns a new instance of the default v8::Platform implementation.
The caller will take ownership of the returned pointer. |thread_pool_size| is the number of worker threads to allocate for background jobs. If a value of zero is passed, a suitable default based on the current number of processors online will be chosen. If |idle_task_support| is enabled then the platform will accept idle tasks (IdleTasksEnabled will return true) and will rely on the embedder calling v8::platform::RunIdleTasks to process the idle tasks. If |tracing_controller| is nullptr, the default platform will create a v8::platform::TracingController instance and use it. If |priority_mode| is PriorityMode::kApply, the default platform will use multiple task queues executed by threads different system-level priorities (where available) to schedule tasks.
Definition at line 45 of file default-platform.cc.
                                {
  if (in_process_stack_dumping == InProcessStackDumping::kEnabled) {
    v8::base::debug::EnableInProcessStackDumping();
  }
  thread_pool_size = GetActualThreadPoolSize(thread_pool_size);
  auto platform = std::make_unique<DefaultPlatform>(
      thread_pool_size, idle_task_support, std::move(tracing_controller),
      priority_mode);
  return platform;
}
References v8::base::debug::EnableInProcessStackDumping(), v8::platform::anonymous_namespace{default-platform.cc}::GetActualThreadPoolSize(), and kEnabled.
Referenced by main(), and v8::Shell::Main().
NewSingleThreadedDefaultPlatform()
V8_PLATFORM_EXPORT std::unique_ptr< v8::Platform > v8::platform::NewSingleThreadedDefaultPlatform (IdleTaskSupport idle_task_support = IdleTaskSupport::kDisabled, InProcessStackDumping in_process_stack_dumping = InProcessStackDumping::kDisabled, std::unique_ptr< v8::TracingController > tracing_controller = {})
The same as NewDefaultPlatform but disables the worker thread pool.
It must be used with the --single-threaded V8 flag.
Definition at line 60 of file default-platform.cc.
                                                           {
  if (in_process_stack_dumping == InProcessStackDumping::kEnabled) {
    v8::base::debug::EnableInProcessStackDumping();
  }
  auto platform = std::make_unique<DefaultPlatform>(
      0, idle_task_support, std::move(tracing_controller));
  return platform;
}
References v8::base::debug::EnableInProcessStackDumping(), and kEnabled.
Referenced by v8::Shell::Main().
NotifyIsolateShutdown()
V8_PLATFORM_EXPORT void v8::platform::NotifyIsolateShutdown (v8::Platform * platform, Isolate * isolate)
Notifies the given platform about the Isolate getting deleted soon.
Has to be called for all Isolates which are deleted - unless we're shutting down the platform.
The |platform| has to be created using |NewDefaultPlatform|.
Definition at line 91 of file default-platform.cc.
                                                                   {
  static_cast<DefaultPlatform*>(platform)->NotifyIsolateShutdown(isolate);
}
Referenced by v8::Worker::ExecuteInThread(), v8::Shell::Main(), and v8::Shell::OnExit().
PumpMessageLoop()
V8_PLATFORM_EXPORT bool v8::platform::PumpMessageLoop (v8::Platform * platform, v8::Isolate * isolate, MessageLoopBehavior behavior = MessageLoopBehavior::kDoNotWait)
Pumps the message loop for the given isolate.
The caller has to make sure that this is called from the right thread. Returns true if a task was executed, and false otherwise. If the call to PumpMessageLoop is nested within another call to PumpMessageLoop, only nestable tasks may run. Otherwise, any task may run. Unless requested through the |behavior| parameter, this call does not block if no task is pending. The |platform| has to be created using |NewDefaultPlatform|.
Definition at line 79 of file default-platform.cc.
                                                   {
  return static_cast<DefaultPlatform*>(platform)->PumpMessageLoop(isolate,
                                                                  behavior);
}
Referenced by v8::Worker::ProcessMessages(), and v8::anonymous_namespace{d8.cc}::ProcessMessages().
RunIdleTasks()
V8_PLATFORM_EXPORT void v8::platform::RunIdleTasks (v8::Platform * platform, v8::Isolate * isolate, double idle_time_in_seconds)
Runs pending idle tasks for at most |idle_time_in_seconds| seconds.
The caller has to make sure that this is called from the right thread. This call does not block if no task is pending. The |platform| has to be created using |NewDefaultPlatform|.
Definition at line 85 of file default-platform.cc.
                                               {
  static_cast<DefaultPlatform*>(platform)->RunIdleTasks(isolate,
                                                        idle_time_in_seconds);
}
Referenced by v8::anonymous_namespace{d8.cc}::ProcessMessages().