v8::internal::trap_handler::anonymous_namespace{handler-outside.cc} Namespace Reference
Functions
void VerifyCodeRangeIsDisjoint (const CodeProtectionInfo *code_info)
void ValidateCodeObjects ()
Function Documentation
ValidateCodeObjects()
void v8::internal::trap_handler::anonymous_namespace{handler-outside.cc}::ValidateCodeObjects ()
Definition at line 72 of file handler-outside.cc.
                           {
  // Sanity-check the code objects
  for (unsigned i = 0; i < gNumCodeObjects; ++i) {
    const auto* data = gCodeObjects[i].code_info;
    if (data == nullptr) continue;
    // Do some sanity checks on the protected instruction data
    for (unsigned j = 0; j < data->num_protected_instructions; ++j) {
      TH_DCHECK(data->instructions[j].instr_offset >= 0);
      TH_DCHECK(data->instructions[j].instr_offset < data->size);
    }
  }
  // Check the validity of the free list.
#ifdef DEBUG
  size_t free_count = 0;
  for (size_t i = gNextCodeObject; i != gNumCodeObjects;
       i = gCodeObjects[i].next_free) {
    TH_DCHECK(i < gNumCodeObjects);
    ++free_count;
    // This check will fail if we encounter a cycle.
    TH_DCHECK(free_count <= gNumCodeObjects);
  }
  // Check that all free entries are reachable via the free list.
  size_t free_count2 = 0;
  for (size_t i = 0; i < gNumCodeObjects; ++i) {
    if (gCodeObjects[i].code_info == nullptr) {
      ++free_count2;
    }
  }
  TH_DCHECK(free_count == free_count2);
#endif
}
References v8::internal::trap_handler::CodeProtectionInfoListEntry::code_info, v8::internal::trap_handler::gCodeObjects, anonymous_namespace{handler-outside.cc}::gNextCodeObject, v8::internal::trap_handler::gNumCodeObjects, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::trap_handler::CodeProtectionInfoListEntry::next_free, and TH_DCHECK.
Referenced by v8::internal::trap_handler::RegisterHandlerData(), and v8::internal::trap_handler::ReleaseHandlerData().
VerifyCodeRangeIsDisjoint()
void v8::internal::trap_handler::anonymous_namespace{handler-outside.cc}::VerifyCodeRangeIsDisjoint (const CodeProtectionInfo * code_info)
Definition at line 66 of file handler-outside.cc.
                                                                    {
  for (size_t i = 0; i < gNumCodeObjects; ++i) {
    TH_DCHECK(IsDisjoint(code_info, gCodeObjects[i].code_info));
  }
}
References v8::internal::trap_handler::gCodeObjects, v8::internal::trap_handler::gNumCodeObjects, v8::internal::anonymous_namespace{json-stringifier.cc}::i, and TH_DCHECK.
Referenced by v8::internal::trap_handler::RegisterHandlerData().