anonymous_namespace{objects-printer.cc} Namespace Reference
Functions
i::Tagged< i::Object > GetObjectFromRaw (void *object)
Function Documentation
GetObjectFromRaw()
i::Tagged<i::Object> anonymous_namespace{objects-printer.cc}::GetObjectFromRaw (void * object) [inline]
Definition at line 4329 of file objects-printer.cc.
                                                       {
  i::Address object_ptr = reinterpret_cast<i::Address>(object);
#ifdef V8_COMPRESS_POINTERS
  if (RoundDown<i::kPtrComprCageBaseAlignment>(object_ptr) == i::kNullAddress) {
    // Try to decompress pointer.
    i::Isolate* isolate = i::Isolate::TryGetCurrent();
    if (isolate != nullptr) {
      object_ptr = i::V8HeapCompressionScheme::DecompressTagged(
          static_cast<i::Tagged_t>(object_ptr));
    } else {
      object_ptr = i::V8HeapCompressionScheme::DecompressTagged(
          static_cast<i::Tagged_t>(object_ptr));
    }
  }
#endif
  return i::Tagged<i::Object>(object_ptr);
}
References v8::internal::V8HeapCompressionSchemeImpl< Cage >::DecompressTagged(), and v8::base::kNullAddress.
Referenced by _v8_internal_Get_Object(), _v8_internal_Print_LoadHandler(), _v8_internal_Print_Object(), _v8_internal_Print_Object_To_String(), _v8_internal_Print_StoreHandler(), and _v8_internal_Print_TransitionTree().