v8::internal::anonymous_namespace{api-natives.cc}::anonymous_namespace{api-natives.cc} Namespace Reference
Functions
MaybeDirectHandle< Object > GetInstancePrototype (Isolate *isolate, DirectHandle< Object > function_template)
Function Documentation
GetInstancePrototype()
MaybeDirectHandle<Object> v8::internal::anonymous_namespace{api-natives.cc}::anonymous_namespace{api-natives.cc}::GetInstancePrototype (Isolate * isolate, DirectHandle< Object > function_template)
Definition at line 365 of file api-natives.cc.
                                                              {
  // Enter a new scope. Recursion could otherwise create a lot of handles.
  HandleScope scope(isolate);
  DirectHandle<JSFunction> parent_instance;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, parent_instance,
      InstantiateFunction(isolate,
                          Cast<FunctionTemplateInfo>(function_template)));
  Handle<Object> instance_prototype;
  // TODO(cbruni): decide what to do here.
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, instance_prototype,
      JSObject::GetProperty(isolate, parent_instance,
                            isolate->factory()->prototype_string()));
  return scope.CloseAndEscape(instance_prototype);
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::Isolate::factory(), and v8::internal::anonymous_namespace{api-natives.cc}::InstantiateFunction().
Referenced by v8::internal::anonymous_namespace{api-natives.cc}::InstantiateFunction().