v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc} Namespace Reference
Functions
ArchOpcode GetLoadOpcode (turboshaft::MemoryRepresentation loaded_rep, turboshaft::RegisterRepresentation result_rep)
ArchOpcode GetStoreOpcode (turboshaft::MemoryRepresentation stored_rep)
static Instruction * VisitCompare (InstructionSelector *selector, InstructionCode opcode, InstructionOperand left, InstructionOperand right, FlagsContinuation *cont)
void VisitFloat32Compare (InstructionSelector *selector, OpIndex node, FlagsContinuation *cont)
void VisitFloat64Compare (InstructionSelector *selector, OpIndex node, FlagsContinuation *cont)
void VisitWordCompare (InstructionSelector *selector, OpIndex node, InstructionCode opcode, FlagsContinuation *cont, bool commutative)
void VisitFullWord32Compare (InstructionSelector *selector, OpIndex node, InstructionCode opcode, FlagsContinuation *cont)
void VisitWord32Compare (InstructionSelector *selector, OpIndex node, FlagsContinuation *cont)
void VisitWord64Compare (InstructionSelector *selector, OpIndex node, FlagsContinuation *cont)
void VisitAtomicLoad (InstructionSelector *selector, OpIndex node, AtomicWidth width)
AtomicStoreParameters AtomicStoreParametersOf (InstructionSelector *selector, OpIndex node)
void VisitAtomicStore (InstructionSelector *selector, OpIndex node, AtomicWidth width)
void VisitAtomicExchange (InstructionSelector *selector, OpIndex node, ArchOpcode opcode, AtomicWidth width, MemoryAccessKind access_kind)
void VisitAtomicCompareExchange (InstructionSelector *selector, OpIndex node, ArchOpcode opcode, AtomicWidth width, MemoryAccessKind access_kind)
void VisitAtomicBinop (InstructionSelector *selector, OpIndex node, ArchOpcode opcode, AtomicWidth width, MemoryAccessKind access_kind)
Function Documentation
AtomicStoreParametersOf()
AtomicStoreParameters v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::AtomicStoreParametersOf (InstructionSelector * selector, OpIndex node)
Definition at line 1760 of file instruction-selector-loong64.cc.
                                                            {
  auto store = selector->store_view(node);
  return AtomicStoreParameters(store.stored_rep().representation(),
                               store.stored_rep().write_barrier_kind(),
                               store.memory_order().value(),
                               store.access_kind());
}
References store(), and v8::internal::compiler::InstructionSelector::store_view().
GetLoadOpcode()
ArchOpcode v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetLoadOpcode (turboshaft::MemoryRepresentation loaded_rep, turboshaft::RegisterRepresentation result_rep)
Definition at line 439 of file instruction-selector-loong64.cc.
                                                                      {
  // NOTE: The meaning of `loaded_rep` = `MemoryRepresentation::AnyTagged()` is
  // we are loading a compressed tagged field, while `result_rep` =
  // `RegisterRepresentation::Tagged()` refers to an uncompressed tagged value.
  switch (loaded_rep) {
    case MemoryRepresentation::Int8():
      DCHECK_EQ(result_rep, RegisterRepresentation::Word32());
      return kLoong64Ld_b;
    case MemoryRepresentation::Uint8():
      DCHECK_EQ(result_rep, RegisterRepresentation::Word32());
      return kLoong64Ld_bu;
    case MemoryRepresentation::Int16():
      DCHECK_EQ(result_rep, RegisterRepresentation::Word32());
      return kLoong64Ld_h;
    case MemoryRepresentation::Uint16():
      DCHECK_EQ(result_rep, RegisterRepresentation::Word32());
      return kLoong64Ld_hu;
    case MemoryRepresentation::Int32():
    case MemoryRepresentation::Uint32():
      DCHECK_EQ(result_rep, RegisterRepresentation::Word32());
      return kLoong64Ld_w;
    case MemoryRepresentation::Int64():
    case MemoryRepresentation::Uint64():
      DCHECK_EQ(result_rep, RegisterRepresentation::Word64());
      return kLoong64Ld_d;
    case MemoryRepresentation::Float16():
      UNIMPLEMENTED();
    case MemoryRepresentation::Float32():
      DCHECK_EQ(result_rep, RegisterRepresentation::Float32());
      return kLoong64Fld_s;
    case MemoryRepresentation::Float64():
      DCHECK_EQ(result_rep, RegisterRepresentation::Float64());
      return kLoong64Fld_d;
#ifdef V8_COMPRESS_POINTERS
    case MemoryRepresentation::AnyTagged():
    case MemoryRepresentation::TaggedPointer():
      if (result_rep == RegisterRepresentation::Compressed()) {
        return kLoong64Ld_wu;
      }
      DCHECK_EQ(result_rep, RegisterRepresentation::Tagged());
      return kLoong64LoadDecompressTagged;
    case MemoryRepresentation::TaggedSigned():
      if (result_rep == RegisterRepresentation::Compressed()) {
        return kLoong64Ld_wu;
      }
      DCHECK_EQ(result_rep, RegisterRepresentation::Tagged());
      return kLoong64LoadDecompressTaggedSigned;
#else
    case MemoryRepresentation::AnyTagged():
    case MemoryRepresentation::TaggedPointer():
    case MemoryRepresentation::TaggedSigned():
      DCHECK_EQ(result_rep, RegisterRepresentation::Tagged());
      return kLoong64Ld_d;
#endif
    case MemoryRepresentation::AnyUncompressedTagged():
    case MemoryRepresentation::UncompressedTaggedPointer():
    case MemoryRepresentation::UncompressedTaggedSigned():
      DCHECK_EQ(result_rep, RegisterRepresentation::Tagged());
      return kLoong64Ld_d;
    case MemoryRepresentation::ProtectedPointer():
      CHECK(V8_ENABLE_SANDBOX_BOOL);
      return kLoong64LoadDecompressProtected;
    case MemoryRepresentation::IndirectPointer():
      UNREACHABLE();
    case MemoryRepresentation::SandboxedPointer():
      return kLoong64LoadDecodeSandboxedPointer;
    case MemoryRepresentation::Simd128(): // Fall through.
    case MemoryRepresentation::Simd256():
      UNREACHABLE();
  }
}
References v8::internal::compiler::turboshaft::MemoryRepresentation::AnyTagged(), v8::internal::compiler::turboshaft::MemoryRepresentation::AnyUncompressedTagged(), CHECK, v8::internal::compiler::turboshaft::RegisterRepresentation::Compressed(), DCHECK_EQ, v8::internal::compiler::turboshaft::MemoryRepresentation::Float16(), v8::internal::compiler::turboshaft::RegisterRepresentation::Float32(), v8::internal::compiler::turboshaft::MemoryRepresentation::Float32(), v8::internal::compiler::turboshaft::RegisterRepresentation::Float64(), v8::internal::compiler::turboshaft::MemoryRepresentation::Float64(), v8::internal::compiler::turboshaft::MemoryRepresentation::IndirectPointer(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int16(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int32(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int64(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int8(), v8::internal::compiler::turboshaft::MemoryRepresentation::ProtectedPointer(), v8::internal::compiler::turboshaft::MemoryRepresentation::SandboxedPointer(), v8::internal::compiler::turboshaft::MemoryRepresentation::Simd128(), v8::internal::compiler::turboshaft::MemoryRepresentation::Simd256(), v8::internal::compiler::turboshaft::RegisterRepresentation::Tagged(), v8::internal::compiler::turboshaft::MemoryRepresentation::TaggedPointer(), v8::internal::compiler::turboshaft::MemoryRepresentation::TaggedSigned(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint16(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint32(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint64(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint8(), v8::internal::compiler::turboshaft::MemoryRepresentation::UncompressedTaggedPointer(), v8::internal::compiler::turboshaft::MemoryRepresentation::UncompressedTaggedSigned(), v8::internal::compiler::UNIMPLEMENTED(), v8::internal::UNREACHABLE(), V8_ENABLE_SANDBOX_BOOL, v8::internal::compiler::turboshaft::RegisterRepresentation::Word32(), and v8::internal::compiler::turboshaft::RegisterRepresentation::Word64().
GetStoreOpcode()
ArchOpcode v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetStoreOpcode (turboshaft::MemoryRepresentation stored_rep)
Definition at line 512 of file instruction-selector-loong64.cc.
                                                                     {
  switch (stored_rep) {
    case MemoryRepresentation::Int8():
    case MemoryRepresentation::Uint8():
      return kLoong64St_b;
    case MemoryRepresentation::Int16():
    case MemoryRepresentation::Uint16():
      return kLoong64St_h;
    case MemoryRepresentation::Int32():
    case MemoryRepresentation::Uint32():
      return kLoong64St_w;
    case MemoryRepresentation::Int64():
    case MemoryRepresentation::Uint64():
      return kLoong64St_d;
    case MemoryRepresentation::Float16():
      UNIMPLEMENTED();
    case MemoryRepresentation::Float32():
      return kLoong64Fst_s;
    case MemoryRepresentation::Float64():
      return kLoong64Fst_d;
    case MemoryRepresentation::AnyTagged():
    case MemoryRepresentation::TaggedPointer():
    case MemoryRepresentation::TaggedSigned():
      return kLoong64StoreCompressTagged;
    case MemoryRepresentation::AnyUncompressedTagged():
    case MemoryRepresentation::UncompressedTaggedPointer():
    case MemoryRepresentation::UncompressedTaggedSigned():
      return kLoong64St_d;
    case MemoryRepresentation::ProtectedPointer():
      // We never store directly to protected pointers from generated code.
      UNREACHABLE();
    case MemoryRepresentation::IndirectPointer():
      return kLoong64StoreIndirectPointer;
    case MemoryRepresentation::SandboxedPointer():
      return kLoong64StoreEncodeSandboxedPointer;
    case MemoryRepresentation::Simd128():
    case MemoryRepresentation::Simd256():
      UNREACHABLE();
  }
}
References v8::internal::compiler::turboshaft::MemoryRepresentation::AnyTagged(), v8::internal::compiler::turboshaft::MemoryRepresentation::AnyUncompressedTagged(), v8::internal::compiler::turboshaft::MemoryRepresentation::Float16(), v8::internal::compiler::turboshaft::MemoryRepresentation::Float32(), v8::internal::compiler::turboshaft::MemoryRepresentation::Float64(), v8::internal::compiler::turboshaft::MemoryRepresentation::IndirectPointer(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int16(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int32(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int64(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int8(), v8::internal::compiler::turboshaft::MemoryRepresentation::ProtectedPointer(), v8::internal::compiler::turboshaft::MemoryRepresentation::SandboxedPointer(), v8::internal::compiler::turboshaft::MemoryRepresentation::Simd128(), v8::internal::compiler::turboshaft::MemoryRepresentation::Simd256(), v8::internal::compiler::turboshaft::MemoryRepresentation::TaggedPointer(), v8::internal::compiler::turboshaft::MemoryRepresentation::TaggedSigned(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint16(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint32(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint64(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint8(), v8::internal::compiler::turboshaft::MemoryRepresentation::UncompressedTaggedPointer(), v8::internal::compiler::turboshaft::MemoryRepresentation::UncompressedTaggedSigned(), v8::internal::compiler::UNIMPLEMENTED(), and v8::internal::UNREACHABLE().
VisitAtomicBinop()
void v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicBinop (InstructionSelector * selector, OpIndex node, ArchOpcode opcode, AtomicWidth width, MemoryAccessKind access_kind)
Definition at line 1921 of file instruction-selector-loong64.cc.
                                                    {
  using OpIndex = OpIndex;
  Loong64OperandGenerator g(selector);
  const AtomicRMWOp& atomic_op = selector->Cast<AtomicRMWOp>(node);
  OpIndex base = atomic_op.base();
  OpIndex index = atomic_op.index();
  OpIndex value = atomic_op.value();
  AddressingMode addressing_mode = kMode_MRI;
  InstructionOperand inputs[3];
  size_t input_count = 0;
  inputs[input_count++] = g.UseUniqueRegister(base);
  inputs[input_count++] = g.UseUniqueRegister(index);
  inputs[input_count++] = g.UseUniqueRegister(value);
  InstructionOperand outputs[1];
  outputs[0] = g.UseUniqueRegister(node);
  InstructionOperand temps[4];
  temps[0] = g.TempRegister();
  temps[1] = g.TempRegister();
  temps[2] = g.TempRegister();
  temps[3] = g.TempRegister();
  InstructionCode code = opcode | AddressingModeField::encode(addressing_mode) |
                         AtomicWidthField::encode(width);
  if (access_kind == MemoryAccessKind::kProtectedByTrapHandler) {
    code |= AccessModeField::encode(kMemoryAccessProtectedMemOutOfBounds);
  }
  selector->Emit(code, 1, outputs, input_count, inputs, 4, temps);
}
References v8::internal::compiler::turboshaft::AtomicRMWOp::base(), v8::internal::compiler::turboshaft::OperationMatcher::Cast(), code, v8::internal::compiler::InstructionSelector::Emit(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::turboshaft::AtomicRMWOp::index(), v8::internal::index, v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::kMemoryAccessProtectedMemOutOfBounds, v8::internal::compiler::kProtectedByTrapHandler, v8::internal::compiler::turboshaft::OpIndex, v8::internal::compiler::OperandGenerator::TempRegister(), v8::internal::compiler::OperandGenerator::UseUniqueRegister(), v8::internal::compiler::turboshaft::AtomicRMWOp::value(), and v8::internal::value.
VisitAtomicCompareExchange()
void v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicCompareExchange (InstructionSelector * selector, OpIndex node, ArchOpcode opcode, AtomicWidth width, MemoryAccessKind access_kind)
Definition at line 1889 of file instruction-selector-loong64.cc.
                                                              {
  using OpIndex = OpIndex;
  Loong64OperandGenerator g(selector);
  const AtomicRMWOp& atomic_op = selector->Cast<AtomicRMWOp>(node);
  OpIndex base = atomic_op.base();
  OpIndex index = atomic_op.index();
  OpIndex old_value = atomic_op.expected().value();
  OpIndex new_value = atomic_op.value();
  AddressingMode addressing_mode = kMode_MRI;
  InstructionOperand inputs[4];
  size_t input_count = 0;
  inputs[input_count++] = g.UseUniqueRegister(base);
  inputs[input_count++] = g.UseUniqueRegister(index);
  inputs[input_count++] = g.UseUniqueRegister(old_value);
  inputs[input_count++] = g.UseUniqueRegister(new_value);
  InstructionOperand outputs[1];
  outputs[0] = g.UseUniqueRegister(node);
  InstructionOperand temp[3];
  temp[0] = g.TempRegister();
  temp[1] = g.TempRegister();
  temp[2] = g.TempRegister();
  InstructionCode code = opcode | AddressingModeField::encode(addressing_mode) |
                         AtomicWidthField::encode(width);
  if (access_kind == MemoryAccessKind::kProtectedByTrapHandler) {
    code |= AccessModeField::encode(kMemoryAccessProtectedMemOutOfBounds);
  }
  selector->Emit(code, 1, outputs, input_count, inputs, 3, temp);
}
References v8::internal::compiler::turboshaft::AtomicRMWOp::base(), v8::internal::compiler::turboshaft::OperationMatcher::Cast(), code, v8::internal::compiler::InstructionSelector::Emit(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::turboshaft::AtomicRMWOp::expected(), v8::internal::compiler::turboshaft::AtomicRMWOp::index(), v8::internal::index, v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::kMemoryAccessProtectedMemOutOfBounds, v8::internal::compiler::kProtectedByTrapHandler, v8::internal::compiler::turboshaft::OpIndex, v8::internal::compiler::OperandGenerator::TempRegister(), v8::internal::compiler::OperandGenerator::UseUniqueRegister(), v8::internal::compiler::turboshaft::OptionalOpIndex::value(), and v8::internal::compiler::turboshaft::AtomicRMWOp::value().
VisitAtomicExchange()
void v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicExchange (InstructionSelector * selector, OpIndex node, ArchOpcode opcode, AtomicWidth width, MemoryAccessKind access_kind)
Definition at line 1851 of file instruction-selector-loong64.cc.
                                                       {
  using OpIndex = OpIndex;
  Loong64OperandGenerator g(selector);
  const AtomicRMWOp& atomic_op = selector->Cast<AtomicRMWOp>(node);
  OpIndex base = atomic_op.base();
  OpIndex index = atomic_op.index();
  OpIndex value = atomic_op.value();
  AddressingMode addressing_mode = kMode_MRI;
  InstructionOperand inputs[3];
  if (opcode == kAtomicExchangeWithWriteBarrier) {
    // All inputs registers need to be non-aliasing with the temp registers as
    // the original inputs are still needed when emitting the write barrier.
    inputs[0] = g.UseUniqueRegister(base);
    inputs[1] = g.UseUniqueRegister(index);
    inputs[2] = g.UseUniqueRegister(value);
  } else {
    inputs[0] = g.UseRegister(base);
    inputs[1] = g.UseRegister(index);
    inputs[2] = g.UseUniqueRegister(value);
  }
  InstructionOperand outputs[1];
  outputs[0] = g.UseUniqueRegister(node);
  InstructionOperand temps[3];
  temps[0] = g.TempRegister();
  temps[1] = g.TempRegister();
  temps[2] = g.TempRegister();
  InstructionCode code = opcode | AddressingModeField::encode(addressing_mode) |
                         AtomicWidthField::encode(width);
  if (access_kind == MemoryAccessKind::kProtectedByTrapHandler) {
    code |= AccessModeField::encode(kMemoryAccessProtectedMemOutOfBounds);
  }
  selector->Emit(code, arraysize(outputs), outputs, arraysize(inputs), inputs,
                 arraysize(temps), temps);
}
References arraysize, v8::internal::compiler::turboshaft::AtomicRMWOp::base(), v8::internal::compiler::turboshaft::OperationMatcher::Cast(), code, v8::internal::compiler::InstructionSelector::Emit(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::turboshaft::AtomicRMWOp::index(), v8::internal::index, v8::internal::compiler::kMemoryAccessProtectedMemOutOfBounds, v8::internal::compiler::kProtectedByTrapHandler, v8::internal::compiler::turboshaft::OpIndex, v8::internal::compiler::OperandGenerator::TempRegister(), v8::internal::compiler::OperandGenerator::UseRegister(), v8::internal::compiler::OperandGenerator::UseUniqueRegister(), v8::internal::compiler::turboshaft::AtomicRMWOp::value(), and v8::internal::value.
VisitAtomicLoad()
void v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicLoad (InstructionSelector * selector, OpIndex node, AtomicWidth width)
Definition at line 1687 of file instruction-selector-loong64.cc.
                                        {
  using OpIndex = OpIndex;
  Loong64OperandGenerator g(selector);
  auto load = selector->load_view(node);
  OpIndex base = load.base();
  OpIndex index = load.index();
  // The memory order is ignored.
  LoadRepresentation load_rep = load.loaded_rep();
  InstructionCode code;
  switch (load_rep.representation()) {
    case MachineRepresentation::kWord8:
      DCHECK_IMPLIES(load_rep.IsSigned(), width == AtomicWidth::kWord32);
      code = load_rep.IsSigned() ? kAtomicLoadInt8 : kAtomicLoadUint8;
      break;
    case MachineRepresentation::kWord16:
      DCHECK_IMPLIES(load_rep.IsSigned(), width == AtomicWidth::kWord32);
      code = load_rep.IsSigned() ? kAtomicLoadInt16 : kAtomicLoadUint16;
      break;
    case MachineRepresentation::kWord32:
      code = (width == AtomicWidth::kWord32) ? kAtomicLoadWord32
                                             : kLoong64Word64AtomicLoadUint32;
      break;
    case MachineRepresentation::kWord64:
      code = kLoong64Word64AtomicLoadUint64;
      break;
#ifdef V8_COMPRESS_POINTERS
    case MachineRepresentation::kTaggedSigned:
      code = kLoong64AtomicLoadDecompressTaggedSigned;
      break;
    case MachineRepresentation::kTaggedPointer:
    case MachineRepresentation::kTagged:
      code = kLoong64AtomicLoadDecompressTagged;
      break;
#else
    case MachineRepresentation::kTaggedSigned: // Fall through.
    case MachineRepresentation::kTaggedPointer: // Fall through.
    case MachineRepresentation::kTagged:
      code = kLoong64Word64AtomicLoadUint64;
      break;
#endif
    case MachineRepresentation::kCompressedPointer: // Fall through.
    case MachineRepresentation::kCompressed:
      DCHECK(COMPRESS_POINTERS_BOOL);
      code = kLoong64Word64AtomicLoadUint32;
      break;
    default:
      UNREACHABLE();
  }
  bool traps_on_null;
  if (load.is_protected(&traps_on_null)) {
    // Atomic loads and null dereference are mutually exclusive. This might
    // change with multi-threaded wasm-gc in which case the access mode should
    // probably be kMemoryAccessProtectedNullDereference.
    DCHECK(!traps_on_null);
    code |= AccessModeField::encode(kMemoryAccessProtectedMemOutOfBounds);
  }
  if (g.CanBeImmediate(index, code)) {
    selector->Emit(code | AddressingModeField::encode(kMode_MRI) |
                       AtomicWidthField::encode(width),
                   g.DefineAsRegister(node), g.UseRegister(base),
                   g.UseImmediate(index));
  } else {
    selector->Emit(code | AddressingModeField::encode(kMode_MRR) |
                       AtomicWidthField::encode(width),
                   g.DefineAsRegister(node), g.UseRegister(base),
                   g.UseRegister(index));
  }
}
References v8::internal::compiler::Loong64OperandGenerator::CanBeImmediate(), code, COMPRESS_POINTERS_BOOL, v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::InstructionSelector::Emit(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::index, v8::internal::MachineType::IsSigned(), v8::internal::kCompressed, v8::internal::kCompressedPointer, v8::internal::compiler::kMemoryAccessProtectedMemOutOfBounds, v8::internal::kTagged, v8::internal::kTaggedPointer, v8::internal::kTaggedSigned, v8::internal::kWord16, v8::internal::kWord32, v8::internal::compiler::kWord32, v8::internal::kWord64, v8::internal::kWord8, v8::internal::compiler::InstructionSelector::load_view(), v8::internal::compiler::turboshaft::OpIndex, v8::internal::MachineType::representation(), v8::internal::UNREACHABLE(), v8::internal::compiler::OperandGenerator::UseImmediate(), and v8::internal::compiler::OperandGenerator::UseRegister().
VisitAtomicStore()
void v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicStore (InstructionSelector * selector, OpIndex node, AtomicWidth width)
Definition at line 1769 of file instruction-selector-loong64.cc.
                                         {
  using OpIndex = OpIndex;
  Loong64OperandGenerator g(selector);
  auto store = selector->store_view(node);
  OpIndex base = store.base();
  OpIndex index = store.index().value();
  OpIndex value = store.value();
  DCHECK_EQ(store.displacement(), 0);
  // The memory order is ignored.
  AtomicStoreParameters store_params = AtomicStoreParametersOf(selector, node);
  WriteBarrierKind write_barrier_kind = store_params.write_barrier_kind();
  MachineRepresentation rep = store_params.representation();
  if (v8_flags.enable_unconditional_write_barriers &&
      CanBeTaggedOrCompressedPointer(rep)) {
    write_barrier_kind = kFullWriteBarrier;
  }
  InstructionCode code;
  if (write_barrier_kind != kNoWriteBarrier &&
      !v8_flags.disable_write_barriers) {
    DCHECK(CanBeTaggedPointer(rep));
    DCHECK_EQ(AtomicWidthSize(width), kTaggedSize);
    RecordWriteMode record_write_mode =
        WriteBarrierKindToRecordWriteMode(write_barrier_kind);
    code = kArchAtomicStoreWithWriteBarrier;
    code |= RecordWriteModeField::encode(record_write_mode);
  } else {
    switch (rep) {
      case MachineRepresentation::kWord8:
        code = kAtomicStoreWord8;
        break;
      case MachineRepresentation::kWord16:
        code = kAtomicStoreWord16;
        break;
      case MachineRepresentation::kWord32:
        code = kAtomicStoreWord32;
        break;
      case MachineRepresentation::kWord64:
        DCHECK_EQ(width, AtomicWidth::kWord64);
        code = kLoong64Word64AtomicStoreWord64;
        break;
      case MachineRepresentation::kTaggedSigned: // Fall through.
      case MachineRepresentation::kTaggedPointer: // Fall through.
      case MachineRepresentation::kTagged:
        DCHECK_EQ(AtomicWidthSize(width), kTaggedSize);
        code = kLoong64AtomicStoreCompressTagged;
        break;
      case MachineRepresentation::kCompressedPointer: // Fall through.
      case MachineRepresentation::kCompressed:
        DCHECK(COMPRESS_POINTERS_BOOL);
        DCHECK_EQ(width, AtomicWidth::kWord32);
        code = kLoong64AtomicStoreCompressTagged;
        break;
      default:
        UNREACHABLE();
    }
  }
  if (store.is_store_trap_on_null()) {
    code |= AccessModeField::encode(kMemoryAccessProtectedNullDereference);
  } else if (store_params.kind() == MemoryAccessKind::kProtectedByTrapHandler) {
    code |= AccessModeField::encode(kMemoryAccessProtectedMemOutOfBounds);
  }
  if (g.CanBeImmediate(index, code)) {
    selector->Emit(code | AddressingModeField::encode(kMode_MRI) |
                       AtomicWidthField::encode(width),
                   g.NoOutput(), g.UseRegister(base), g.UseImmediate(index),
                   g.UseRegisterOrImmediateZero(value));
  } else {
    selector->Emit(code | AddressingModeField::encode(kMode_MRR) |
                       AtomicWidthField::encode(width),
                   g.NoOutput(), g.UseRegister(base), g.UseRegister(index),
                   g.UseRegisterOrImmediateZero(value));
  }
}
References v8::internal::compiler::AtomicStoreParametersOf(), v8::internal::compiler::AtomicWidthSize(), v8::internal::compiler::Loong64OperandGenerator::CanBeImmediate(), v8::internal::CanBeTaggedOrCompressedPointer(), v8::internal::CanBeTaggedPointer(), code, COMPRESS_POINTERS_BOOL, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::InstructionSelector::Emit(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::index, v8::internal::kCompressed, v8::internal::kCompressedPointer, v8::internal::compiler::kFullWriteBarrier, v8::internal::compiler::AtomicStoreParameters::kind(), v8::internal::compiler::kMemoryAccessProtectedMemOutOfBounds, v8::internal::compiler::kMemoryAccessProtectedNullDereference, v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kProtectedByTrapHandler, v8::internal::kTagged, v8::internal::kTaggedPointer, v8::internal::kTaggedSigned, v8::internal::kTaggedSize, v8::internal::kWord16, v8::internal::kWord32, v8::internal::compiler::kWord32, v8::internal::kWord64, v8::internal::compiler::kWord64, v8::internal::kWord8, v8::internal::compiler::OperandGenerator::NoOutput(), v8::internal::compiler::turboshaft::OpIndex, v8::internal::compiler::AtomicStoreParameters::representation(), store(), v8::internal::compiler::InstructionSelector::store_view(), v8::internal::UNREACHABLE(), v8::internal::compiler::OperandGenerator::UseImmediate(), v8::internal::compiler::OperandGenerator::UseRegister(), v8::internal::compiler::Loong64OperandGenerator::UseRegisterOrImmediateZero(), v8::internal::v8_flags, v8::internal::value, v8::internal::compiler::AtomicStoreParameters::write_barrier_kind(), and v8::internal::compiler::WriteBarrierKindToRecordWriteMode().
VisitCompare()
static Instruction* v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitCompare (InstructionSelector * selector, InstructionCode opcode, InstructionOperand left, InstructionOperand right, FlagsContinuation * cont) [static]
Definition at line 1519 of file instruction-selector-loong64.cc.
                                                          {
#ifdef V8_COMPRESS_POINTERS
  if (opcode == kLoong64Cmp32) {
    Loong64OperandGenerator g(selector);
    InstructionOperand inputs[] = {left, right};
    if (right.IsImmediate()) {
      InstructionOperand temps[1] = {g.TempRegister()};
      return selector->EmitWithContinuation(opcode, 0, nullptr,
                                            arraysize(inputs), inputs,
                                            arraysize(temps), temps, cont);
    } else {
      InstructionOperand temps[2] = {g.TempRegister(), g.TempRegister()};
      return selector->EmitWithContinuation(opcode, 0, nullptr,
                                            arraysize(inputs), inputs,
                                            arraysize(temps), temps, cont);
    }
  }
#endif
  return selector->EmitWithContinuation(opcode, left, right, cont);
}
References arraysize, v8::internal::compiler::InstructionSelector::EmitWithContinuation(), and v8::internal::compiler::OperandGenerator::TempRegister().
VisitFloat32Compare()
void v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitFloat32Compare (InstructionSelector * selector, OpIndex node, FlagsContinuation * cont)
Definition at line 1545 of file instruction-selector-loong64.cc.
                                                  {
  Loong64OperandGenerator g(selector);
  const ComparisonOp& op = selector->Get(node).template Cast<ComparisonOp>();
  OpIndex left = op.left();
  OpIndex right = op.right();
  InstructionOperand lhs, rhs;
  lhs = selector->MatchZero(left) ? g.UseImmediate(left) : g.UseRegister(left);
  rhs =
      selector->MatchZero(right) ? g.UseImmediate(right) : g.UseRegister(right);
  VisitCompare(selector, kLoong64Float32Cmp, lhs, rhs, cont);
}
References v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::ComparisonOp::left(), v8::internal::compiler::turboshaft::OperationMatcher::MatchZero(), v8::internal::compiler::turboshaft::ComparisonOp::right(), v8::internal::compiler::OperandGenerator::UseImmediate(), v8::internal::compiler::OperandGenerator::UseRegister(), and v8::internal::compiler::VisitCompare().
VisitFloat64Compare()
void v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitFloat64Compare (InstructionSelector * selector, OpIndex node, FlagsContinuation * cont)
Definition at line 1560 of file instruction-selector-loong64.cc.
                                                  {
  Loong64OperandGenerator g(selector);
  const Operation& compare = selector->Get(node);
  DCHECK(compare.Is<ComparisonOp>());
  OpIndex lhs = compare.input(0);
  OpIndex rhs = compare.input(1);
  if (selector->MatchZero(rhs)) {
    VisitCompare(selector, kLoong64Float64Cmp, g.UseRegister(lhs),
                 g.UseImmediate(rhs), cont);
  } else if (selector->MatchZero(lhs)) {
    VisitCompare(selector, kLoong64Float64Cmp, g.UseImmediate(lhs),
                 g.UseRegister(rhs), cont);
  } else {
    VisitCompare(selector, kLoong64Float64Cmp, g.UseRegister(lhs),
                 g.UseRegister(rhs), cont);
  }
}
References v8::internal::DCHECK(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::compiler::turboshaft::OperationMatcher::MatchZero(), v8::internal::compiler::OperandGenerator::UseImmediate(), v8::internal::compiler::OperandGenerator::UseRegister(), and v8::internal::compiler::VisitCompare().
VisitFullWord32Compare()
void v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitFullWord32Compare (InstructionSelector * selector, OpIndex node, InstructionCode opcode, FlagsContinuation * cont)
Definition at line 1660 of file instruction-selector-loong64.cc.
                                                                             {
  Loong64OperandGenerator g(selector);
  const Operation& op = selector->Get(node);
  DCHECK_EQ(op.input_count, 2);
  InstructionOperand leftOp = g.TempRegister();
  InstructionOperand rightOp = g.TempRegister();
  selector->Emit(kLoong64Sll_d, leftOp, g.UseRegister(op.input(0)),
                 g.TempImmediate(32));
  selector->Emit(kLoong64Sll_d, rightOp, g.UseRegister(op.input(1)),
                 g.TempImmediate(32));
  Instruction* instr = VisitCompare(selector, opcode, leftOp, rightOp, cont);
  selector->UpdateSourcePosition(instr, node);
}
References DCHECK_EQ, v8::internal::compiler::InstructionSelector::Emit(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::turboshaft::Operation::input_count, v8::internal::compiler::OperandGenerator::TempImmediate(), v8::internal::compiler::OperandGenerator::TempRegister(), v8::internal::compiler::InstructionSelector::UpdateSourcePosition(), v8::internal::compiler::OperandGenerator::UseRegister(), and v8::internal::compiler::VisitCompare().
Referenced by VisitWord32Compare().
VisitWord32Compare()
void v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitWord32Compare (InstructionSelector * selector, OpIndex node, FlagsContinuation * cont)
Definition at line 1677 of file instruction-selector-loong64.cc.
                                                 {
  VisitFullWord32Compare(selector, node, kLoong64Cmp64, cont);
}
References VisitFullWord32Compare().
VisitWord64Compare()
void v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitWord64Compare (InstructionSelector * selector, OpIndex node, FlagsContinuation * cont)
Definition at line 1682 of file instruction-selector-loong64.cc.
                                                 {
  VisitWordCompare(selector, node, kLoong64Cmp64, cont, false);
}
References v8::internal::compiler::VisitWordCompare().
VisitWordCompare()
void v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitWordCompare (InstructionSelector * selector, OpIndex node, InstructionCode opcode, FlagsContinuation * cont, bool commutative)
Definition at line 1580 of file instruction-selector-loong64.cc.
                                        {
  Loong64OperandGenerator g(selector);
  const Operation& op = selector->Get(node);
  DCHECK_EQ(op.input_count, 2);
  auto left = op.input(0);
  auto right = op.input(1);
  // Match immediates on left or right side of comparison.
  if (g.CanBeImmediate(right, opcode)) {
    if (opcode == kLoong64Tst) {
      VisitCompare(selector, opcode, g.UseRegister(left), g.UseImmediate(right),
                   cont);
    } else {
      switch (cont->condition()) {
        case kEqual:
        case kNotEqual:
          if (cont->IsSet()) {
            VisitCompare(selector, opcode, g.UseUniqueRegister(left),
                         g.UseImmediate(right), cont);
          } else {
            VisitCompare(selector, opcode, g.UseUniqueRegister(left),
                         g.UseImmediate(right), cont);
          }
          break;
        case kSignedLessThan:
        case kSignedGreaterThanOrEqual:
        case kSignedLessThanOrEqual:
        case kSignedGreaterThan:
        case kUnsignedLessThan:
        case kUnsignedGreaterThanOrEqual:
        case kUnsignedLessThanOrEqual:
        case kUnsignedGreaterThan:
          VisitCompare(selector, opcode, g.UseUniqueRegister(left),
                       g.UseImmediate(right), cont);
          break;
        default:
          UNREACHABLE();
      }
    }
  } else if (g.CanBeImmediate(left, opcode)) {
    if (!commutative) cont->Commute();
    if (opcode == kLoong64Tst) {
      VisitCompare(selector, opcode, g.UseRegister(right), g.UseImmediate(left),
                   cont);
    } else {
      switch (cont->condition()) {
        case kEqual:
        case kNotEqual:
          if (cont->IsSet()) {
            VisitCompare(selector, opcode, g.UseUniqueRegister(right),
                         g.UseImmediate(left), cont);
          } else {
            VisitCompare(selector, opcode, g.UseUniqueRegister(right),
                         g.UseImmediate(left), cont);
          }
          break;
        case kSignedLessThan:
        case kSignedGreaterThanOrEqual:
        case kSignedLessThanOrEqual:
        case kSignedGreaterThan:
        case kUnsignedLessThan:
        case kUnsignedGreaterThanOrEqual:
        case kUnsignedLessThanOrEqual:
        case kUnsignedGreaterThan:
          VisitCompare(selector, opcode, g.UseUniqueRegister(right),
                       g.UseImmediate(left), cont);
          break;
        default:
          UNREACHABLE();
      }
    }
  } else {
    VisitCompare(selector, opcode, g.UseUniqueRegister(left),
                 g.UseUniqueRegister(right), cont);
  }
}
References v8::internal::compiler::Loong64OperandGenerator::CanBeImmediate(), v8::internal::compiler::FlagsContinuation::Commute(), v8::internal::compiler::FlagsContinuation::condition(), DCHECK_EQ, v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::turboshaft::Operation::input_count, v8::internal::compiler::FlagsContinuation::IsSet(), v8::internal::kEqual, v8::internal::compiler::kNotEqual, v8::internal::compiler::kSignedGreaterThan, v8::internal::compiler::kSignedGreaterThanOrEqual, v8::internal::compiler::kSignedLessThan, v8::internal::compiler::kSignedLessThanOrEqual, v8::internal::compiler::kUnsignedGreaterThan, v8::internal::compiler::kUnsignedGreaterThanOrEqual, v8::internal::compiler::kUnsignedLessThan, v8::internal::compiler::kUnsignedLessThanOrEqual, v8::internal::UNREACHABLE(), v8::internal::compiler::OperandGenerator::UseImmediate(), v8::internal::compiler::OperandGenerator::UseRegister(), v8::internal::compiler::OperandGenerator::UseUniqueRegister(), and v8::internal::compiler::VisitCompare().