v8::base::anonymous_namespace{platform-linux.cc} Namespace Reference
Functions
std::unique_ptr< std::vector< MemoryRegion > > ParseProcSelfMaps (FILE *fp, std::function< bool(const MemoryRegion &)> predicate, bool early_stopping)
MemoryRegion FindEnclosingMapping (uintptr_t target_start, size_t size)
Function Documentation
FindEnclosingMapping()
MemoryRegion v8::base::anonymous_namespace{platform-linux.cc}::FindEnclosingMapping (uintptr_t target_start, size_t size)
Definition at line 227 of file platform-linux.cc.
                                                                       {
  auto result = ParseProcSelfMaps(
      nullptr,
      [=](const MemoryRegion& region) {
        return region.start <= target_start && target_start + size < region.end;
      },
      true);
  if (result)
    return (*result)[0];
  else
    return {};
}
References v8::base::MemoryRegion::end, ParseProcSelfMaps(), v8::base::internal::result, size(), and v8::base::MemoryRegion::start.
ParseProcSelfMaps()
std::unique_ptr<std::vector<MemoryRegion> > v8::base::anonymous_namespace{platform-linux.cc}::ParseProcSelfMaps (FILE * fp, std::function< bool(const MemoryRegion &)> predicate, bool early_stopping)
Definition at line 174 of file platform-linux.cc.
                         {
  auto result = std::make_unique<std::vector<MemoryRegion>>();
  if (!fp) fp = fopen("/proc/self/maps", "r");
  if (!fp) return nullptr;
  // Allocate enough room to be able to store a full file name.
  // 55ac243aa000-55ac243ac000 r--p 00000000 fe:01 31594735 /usr/bin/head
  const int kMaxLineLength = 2 * FILENAME_MAX;
  std::unique_ptr<char[]> line = std::make_unique<char[]>(kMaxLineLength);
  // This loop will terminate once the scanning hits an EOF.
  bool error = false;
  while (true) {
    error = true;
    // Read to the end of the line. Exit if the read fails.
    if (fgets(line.get(), kMaxLineLength, fp) == nullptr) {
      if (feof(fp)) error = false;
      break;
    }
    size_t line_length = strlen(line.get());
    // Empty line at the end.
    if (!line_length) {
      error = false;
      break;
    }
    // Line was truncated.
    if (line.get()[line_length - 1] != '\n') break;
    line.get()[line_length - 1] = '\0';
    std::optional<MemoryRegion> region = MemoryRegion::FromMapsLine(line.get());
    if (!region) {
      break;
    }
    error = false;
    if (predicate(*region)) {
      result->push_back(std::move(*region));
      if (early_stopping) break;
    }
  }
  fclose(fp);
  if (!error && !result->empty()) return result;
  return nullptr;
}
References v8::base::MemoryRegion::FromMapsLine(), and v8::base::internal::result.
Referenced by FindEnclosingMapping(), and v8::base::GetSharedLibraryAddresses().