v8::internal::compiler::fast_api_call Namespace Reference
Classes
class FastApiCallBuilder
struct OverloadsResolutionResult
Typedefs
using GetParameter = std::function< Node *(int, GraphAssemblerLabel< 0 > *)>
using ConvertReturnValue = std::function< Node *(const CFunctionInfo *, Node *)>
using InitializeOptions = std::function< void(Node *)>
using GenerateSlowApiCall = std::function< Node *()>
Functions
ElementsKind GetTypedArrayElementsKind (CTypeInfo::Type type)
bool CanOptimizeFastSignature (const CFunctionInfo *c_signature)
Node * BuildFastApiCall (Isolate *isolate, TFGraph *graph, GraphAssembler *graph_assembler, FastApiCallFunction c_function, Node *data_argument, const GetParameter &get_parameter, const ConvertReturnValue &convert_return_value, const InitializeOptions &initialize_options, const GenerateSlowApiCall &generate_slow_api_call)
FastApiCallFunction GetFastApiCallTarget (JSHeapBroker *broker, FunctionTemplateInfoRef function_template_info, size_t arg_count)
Typedef Documentation
ConvertReturnValue
using v8::internal::compiler::fast_api_call::ConvertReturnValue = typedef std::function<Node*(const CFunctionInfo*, Node*)>
Definition at line 46 of file fast-api-calls.h.
GenerateSlowApiCall
using v8::internal::compiler::fast_api_call::GenerateSlowApiCall = typedef std::function<Node*()>
Definition at line 48 of file fast-api-calls.h.
GetParameter
using v8::internal::compiler::fast_api_call::GetParameter = typedef std::function<Node*(int, GraphAssemblerLabel<0>*)>
Definition at line 45 of file fast-api-calls.h.
InitializeOptions
using v8::internal::compiler::fast_api_call::InitializeOptions = typedef std::function<void(Node*)>
Definition at line 47 of file fast-api-calls.h.
Function Documentation
BuildFastApiCall()
Node * v8::internal::compiler::fast_api_call::BuildFastApiCall (Isolate * isolate, TFGraph * graph, GraphAssembler * graph_assembler, FastApiCallFunction c_function, Node * data_argument, const GetParameter & get_parameter, const ConvertReturnValue & convert_return_value, const InitializeOptions & initialize_options, const GenerateSlowApiCall & generate_slow_api_call)
Definition at line 371 of file fast-api-calls.cc.
                                                                          {
  FastApiCallBuilder builder(isolate, graph, graph_assembler, get_parameter,
                             convert_return_value, initialize_options,
                             generate_slow_api_call);
  return builder.Build(c_function, data_argument);
}
References v8::internal::compiler::fast_api_call::FastApiCallBuilder::Build(), and graph().
Referenced by v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::BuildJSFastApiCallWrapper().
CanOptimizeFastSignature()
bool v8::internal::compiler::fast_api_call::CanOptimizeFastSignature (const CFunctionInfo * c_signature)
Definition at line 65 of file fast-api-calls.cc.
                                                                {
  USE(c_signature);
#if defined(V8_OS_MACOS) && defined(V8_TARGET_ARCH_ARM64)
  // On MacArm64 hardware we don't support passing of arguments on the stack.
  if (c_signature->ArgumentCount() > 8) {
    return false;
  }
#endif // defined(V8_OS_MACOS) && defined(V8_TARGET_ARCH_ARM64)
#ifndef V8_ENABLE_FP_PARAMS_IN_C_LINKAGE
  if (c_signature->ReturnInfo().GetType() == CTypeInfo::Type::kFloat32 ||
      c_signature->ReturnInfo().GetType() == CTypeInfo::Type::kFloat64) {
    return false;
  }
#endif
#ifdef V8_USE_SIMULATOR_WITH_GENERIC_C_CALLS
  if (!v8_flags.fast_api_allow_float_in_sim &&
      (c_signature->ReturnInfo().GetType() == CTypeInfo::Type::kFloat32 ||
       c_signature->ReturnInfo().GetType() == CTypeInfo::Type::kFloat64)) {
    return false;
  }
#endif
#ifndef V8_TARGET_ARCH_64_BIT
  if (c_signature->ReturnInfo().GetType() == CTypeInfo::Type::kInt64 ||
      c_signature->ReturnInfo().GetType() == CTypeInfo::Type::kUint64) {
    return false;
  }
#endif
  for (unsigned int i = 0; i < c_signature->ArgumentCount(); ++i) {
    USE(i);
#ifdef V8_TARGET_ARCH_X64
    // Clamp lowering in EffectControlLinearizer uses rounding.
    uint8_t flags = uint8_t(c_signature->ArgumentInfo(i).GetFlags());
    if (flags & uint8_t(CTypeInfo::Flags::kClampBit)) {
      return CpuFeatures::IsSupported(SSE4_2);
    }
#endif // V8_TARGET_ARCH_X64
#ifndef V8_ENABLE_FP_PARAMS_IN_C_LINKAGE
    if (c_signature->ArgumentInfo(i).GetType() == CTypeInfo::Type::kFloat32 ||
        c_signature->ArgumentInfo(i).GetType() == CTypeInfo::Type::kFloat64) {
      return false;
    }
#endif
#ifdef V8_USE_SIMULATOR_WITH_GENERIC_C_CALLS
    if (!v8_flags.fast_api_allow_float_in_sim &&
        (c_signature->ArgumentInfo(i).GetType() == CTypeInfo::Type::kFloat32 ||
         c_signature->ArgumentInfo(i).GetType() == CTypeInfo::Type::kFloat64)) {
      return false;
    }
#endif
#ifndef V8_TARGET_ARCH_64_BIT
    if (c_signature->ArgumentInfo(i).GetType() == CTypeInfo::Type::kInt64 ||
        c_signature->ArgumentInfo(i).GetType() == CTypeInfo::Type::kUint64) {
      return false;
    }
#endif
  }
  return true;
}
References v8::CFunctionInfo::ArgumentCount(), v8::CFunctionInfo::ArgumentInfo(), v8::internal::flags, v8::CTypeInfo::GetFlags(), v8::CTypeInfo::GetType(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::CpuFeatures::IsSupported(), v8::CTypeInfo::kClampBit, v8::CTypeInfo::kFloat32, v8::CTypeInfo::kFloat64, v8::CTypeInfo::kInt64, v8::CTypeInfo::kUint64, v8::CFunctionInfo::ReturnInfo(), USE, and v8::internal::v8_flags.
Referenced by GetFastApiCallTarget(), and v8::internal::compiler::IsFastCallSupportedSignature().
GetFastApiCallTarget()
FastApiCallFunction v8::internal::compiler::fast_api_call::GetFastApiCallTarget (JSHeapBroker * broker, FunctionTemplateInfoRef function_template_info, size_t arg_count)
Definition at line 384 of file fast-api-calls.cc.
                      {
  if (!v8_flags.turbo_fast_api_calls) return {0, nullptr};
  static constexpr int kReceiver = 1;
  const ZoneVector<const CFunctionInfo*>& signatures =
      function_template_info.c_signatures(broker);
  const size_t overloads_count = signatures.size();
  // Only considers entries whose type list length matches arg_count.
  for (size_t i = 0; i < overloads_count; i++) {
    const CFunctionInfo* c_signature = signatures[i];
    const size_t len = c_signature->ArgumentCount() - kReceiver;
    bool optimize_to_fast_call =
        (len == arg_count) &&
        fast_api_call::CanOptimizeFastSignature(c_signature);
    if (optimize_to_fast_call) {
      // TODO(nicohartmann@): {Flags::kEnforceRangeBit} is currently only
      // supported on 64 bit architectures. We should support this on 32 bit
      // architectures.
#if defined(V8_TARGET_ARCH_32_BIT)
      for (unsigned int j = 0; j < c_signature->ArgumentCount(); ++j) {
        const uint8_t flags =
            static_cast<uint8_t>(c_signature->ArgumentInfo(j).GetFlags());
        if (flags & static_cast<uint8_t>(CTypeInfo::Flags::kEnforceRangeBit)) {
          // Bailout
          return {0, nullptr};
        }
      }
#endif
      return {function_template_info.c_functions(broker)[i], c_signature};
    }
  }
  return {0, nullptr};
}
References v8::CFunctionInfo::ArgumentCount(), v8::CFunctionInfo::ArgumentInfo(), broker(), v8::internal::compiler::FunctionTemplateInfoRef::c_functions(), v8::internal::compiler::FunctionTemplateInfoRef::c_signatures(), CanOptimizeFastSignature(), v8::internal::flags, v8::CTypeInfo::GetFlags(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::CTypeInfo::kEnforceRangeBit, v8::internal::kReceiver, v8::internal::ZoneVector< T >::size(), and v8::internal::v8_flags.
Referenced by v8::internal::compiler::JSNativeContextSpecialization::InlineApiCall(), and v8::internal::compiler::JSCallReducer::ReduceCallApiFunction().
GetTypedArrayElementsKind()
ElementsKind v8::internal::compiler::fast_api_call::GetTypedArrayElementsKind (CTypeInfo::Type type)
Definition at line 38 of file fast-api-calls.cc.
                                                           {
  switch (type) {
    case CTypeInfo::Type::kUint8:
      return UINT8_ELEMENTS;
    case CTypeInfo::Type::kInt32:
      return INT32_ELEMENTS;
    case CTypeInfo::Type::kUint32:
      return UINT32_ELEMENTS;
    case CTypeInfo::Type::kInt64:
      return BIGINT64_ELEMENTS;
    case CTypeInfo::Type::kUint64:
      return BIGUINT64_ELEMENTS;
    case CTypeInfo::Type::kFloat32:
      return FLOAT32_ELEMENTS;
    case CTypeInfo::Type::kFloat64:
      return FLOAT64_ELEMENTS;
    case CTypeInfo::Type::kVoid:
    case CTypeInfo::Type::kSeqOneByteString:
    case CTypeInfo::Type::kBool:
    case CTypeInfo::Type::kPointer:
    case CTypeInfo::Type::kV8Value:
    case CTypeInfo::Type::kApiObject:
    case CTypeInfo::Type::kAny:
      UNREACHABLE();
  }
}
References v8::internal::maglev::FLOAT32_ELEMENTS, v8::CTypeInfo::kAny, v8::CTypeInfo::kApiObject, v8::CTypeInfo::kBool, v8::CTypeInfo::kFloat32, v8::CTypeInfo::kFloat64, v8::CTypeInfo::kInt32, v8::CTypeInfo::kInt64, v8::CTypeInfo::kPointer, v8::CTypeInfo::kSeqOneByteString, v8::CTypeInfo::kUint32, v8::CTypeInfo::kUint64, v8::CTypeInfo::kUint8, v8::CTypeInfo::kV8Value, v8::CTypeInfo::kVoid, v8::internal::tracing::type, v8::internal::maglev::UINT8_ELEMENTS, and v8::internal::UNREACHABLE().