v8::internal::compiler::turboshaft::anonymous_namespace{instruction-selection-phase.cc} Namespace Reference
Functions
void TraceSequence (OptimizedCompilationInfo *info, InstructionSequence *sequence, JSHeapBroker *broker, CodeTracer *code_tracer, const char *phase_name)
Function Documentation
TraceSequence()
void v8::internal::compiler::turboshaft::anonymous_namespace{instruction-selection-phase.cc}::TraceSequence (OptimizedCompilationInfo * info, InstructionSequence * sequence, JSHeapBroker * broker, CodeTracer * code_tracer, const char * phase_name)
Definition at line 26 of file instruction-selection-phase.cc.
                                                                    {
  if (info->trace_turbo_json()) {
    UnparkedScopeIfNeeded scope(broker);
    AllowHandleDereference allow_deref;
    TurboJsonFile json_of(info, std::ios_base::app);
    json_of << "{\"name\":\"" << phase_name << "\",\"type\":\"sequence\""
            << ",\"blocks\":" << InstructionSequenceAsJSON{sequence}
            << ",\"register_allocation\":{"
            << "\"fixed_double_live_ranges\": {}"
            << ",\"fixed_live_ranges\": {}"
            << ",\"live_ranges\": {}"
            << "}},\n";
  }
  if (info->trace_turbo_graph()) {
    UnparkedScopeIfNeeded scope(broker);
    AllowHandleDereference allow_deref;
    CodeTracer::StreamScope tracing_scope(code_tracer);
    tracing_scope.stream() << "----- Instruction sequence " << phase_name
                           << " -----\n"
                           << *sequence;
  }
}
References broker(), and v8::internal::CodeTracer::StreamScope::stream().
Referenced by v8::internal::compiler::turboshaft::InstructionSelectionPhase::Run().