v8::internal::compiler::anonymous_namespace{raw-machine-assembler.cc} Namespace Reference
Enumerations
enum FunctionDescriptorMode { kHasFunctionDescriptor
, kNoFunctionDescriptor
 }
Functions
Node * CallCFunctionImpl (RawMachineAssembler *rasm, Node *function, std::optional< MachineType > return_type, std::initializer_list< RawMachineAssembler::CFunctionArg > args, bool caller_saved_regs, SaveFPRegsMode mode, FunctionDescriptorMode no_function_descriptor)
Enumeration Type Documentation
FunctionDescriptorMode
enum v8::internal::compiler::anonymous_namespace{raw-machine-assembler.cc}::FunctionDescriptorMode
Enumerator
kHasFunctionDescriptor
kNoFunctionDescriptor
Definition at line 729 of file raw-machine-assembler.cc.
{ kHasFunctionDescriptor, kNoFunctionDescriptor };
Function Documentation
CallCFunctionImpl()
Node* v8::internal::compiler::anonymous_namespace{raw-machine-assembler.cc}::CallCFunctionImpl (RawMachineAssembler * rasm, Node * function, std::optional< MachineType > return_type, std::initializer_list< RawMachineAssembler::CFunctionArg > args, bool caller_saved_regs, SaveFPRegsMode mode, FunctionDescriptorMode no_function_descriptor)
Definition at line 731 of file raw-machine-assembler.cc.
                                                   {
  static constexpr std::size_t kNumCArgs = 10;
  MachineSignature::Builder builder(rasm->zone(), return_type ? 1 : 0,
                                    args.size());
  if (return_type) {
    builder.AddReturn(*return_type);
  }
  for (const auto& arg : args) builder.AddParam(arg.first);
  bool caller_saved_fp_regs =
      caller_saved_regs && (mode == SaveFPRegsMode::kSave);
  CallDescriptor::Flags flags = CallDescriptor::kNoFlags;
  if (caller_saved_regs) flags |= CallDescriptor::kCallerSavedRegisters;
  if (caller_saved_fp_regs) flags |= CallDescriptor::kCallerSavedFPRegisters;
  if (no_function_descriptor) flags |= CallDescriptor::kNoFunctionDescriptor;
  auto call_descriptor =
      Linkage::GetSimplifiedCDescriptor(rasm->zone(), builder.Get(), flags);
  base::SmallVector<Node*, kNumCArgs> nodes(args.size() + 1);
  nodes[0] = function;
  std::transform(
      args.begin(), args.end(), std::next(nodes.begin()),
      [](const RawMachineAssembler::CFunctionArg& arg) { return arg.second; });
  auto common = rasm->common();
  return rasm->AddNode(common->Call(call_descriptor),
                       static_cast<int>(nodes.size()), nodes.begin());
}
References v8::internal::compiler::RawMachineAssembler::AddNode(), v8::internal::SignatureBuilder< SigT, T >::AddParam(), v8::internal::SignatureBuilder< SigT, T >::AddReturn(), v8::base::args, v8::base::SmallVector< T, kSize, Allocator >::begin(), v8::internal::compiler::RawMachineAssembler::common(), v8::internal::flags, v8::internal::SignatureBuilder< SigT, T >::Get(), v8::internal::compiler::Linkage::GetSimplifiedCDescriptor(), v8::internal::compiler::CallDescriptor::kCallerSavedFPRegisters, v8::internal::compiler::CallDescriptor::kCallerSavedRegisters, v8::internal::compiler::CallDescriptor::kNoFlags, v8::internal::compiler::CallDescriptor::kNoFunctionDescriptor, v8::internal::kSave, mode(), v8::base::SmallVector< T, kSize, Allocator >::size(), v8::internal::size_t, and v8::internal::compiler::RawMachineAssembler::zone().