v8::internal::anonymous_namespace{log.cc} Namespace Reference
Functions
v8::CodeEventType GetCodeEventTypeForTag (LogEventListener::CodeTag tag)
const char * ComputeMarker (Tagged< SharedFunctionInfo > shared, Tagged< AbstractCode > code)
void InitializeCodeEvent (Isolate *isolate, CodeEvent *event, Address previous_code_start_address, Address code_start_address, int code_size)
void AppendCodeCreateHeader (LogFile::MessageBuilder &msg, LogEventListener::CodeTag tag, CodeKind kind, uint8_t *address, int size, uint64_t time)
void AppendCodeCreateHeader (Isolate *isolate, LogFile::MessageBuilder &msg, LogEventListener::CodeTag tag, Tagged< AbstractCode > code, uint64_t time)
void CodeLinePosEvent (JitLogger &jit_logger, Address code_start, SourcePositionTableIterator &iter, JitCodeEvent::CodeType code_type)
void AppendFunctionMessage (LogFile::MessageBuilder &msg, const char *reason, int script_id, double time_delta, int start_position, int end_position, uint64_t time)
Function Documentation
AppendCodeCreateHeader() [1/2]
void v8::internal::anonymous_namespace{log.cc}::AppendCodeCreateHeader (Isolate * isolate, LogFile::MessageBuilder & msg, LogEventListener::CodeTag tag, Tagged< AbstractCode > code, uint64_t time)
Definition at line 1373 of file log.cc.
                                                                      {
  PtrComprCageBase cage_base(isolate);
  AppendCodeCreateHeader(
      msg, tag, code->kind(cage_base),
      reinterpret_cast<uint8_t*>(code->InstructionStart(cage_base)),
      code->InstructionSize(cage_base), time);
}
References code, and v8::internal::time.
Referenced by v8::internal::V8FileLogger::CodeCreateEvent(), and v8::internal::V8FileLogger::RegExpCodeCreateEvent().
AppendCodeCreateHeader() [2/2]
void v8::internal::anonymous_namespace{log.cc}::AppendCodeCreateHeader (LogFile::MessageBuilder & msg, LogEventListener::CodeTag tag, CodeKind kind, uint8_t * address, int size, uint64_t time)
Definition at line 1364 of file log.cc.
                                                                       {
  msg << LogEventListener::Event::kCodeCreation << V8FileLogger::kNext << tag
      << V8FileLogger::kNext << static_cast<int>(kind) << V8FileLogger::kNext
      << time << V8FileLogger::kNext << reinterpret_cast<void*>(address)
      << V8FileLogger::kNext << size << V8FileLogger::kNext;
}
References v8::internal::V8FileLogger::kNext, and size().
AppendFunctionMessage()
void v8::internal::anonymous_namespace{log.cc}::AppendFunctionMessage (LogFile::MessageBuilder & msg, const char * reason, int script_id, double time_delta, int start_position, int end_position, uint64_t time)
Definition at line 1811 of file log.cc.
                                                            {
  msg << "function" << V8FileLogger::kNext << reason << V8FileLogger::kNext
      << script_id << V8FileLogger::kNext << start_position
      << V8FileLogger::kNext << end_position << V8FileLogger::kNext;
  if (V8_UNLIKELY(v8_flags.predictable)) {
    msg << 0.1;
  } else {
    msg << time_delta;
  }
  msg << V8FileLogger::kNext << time << V8FileLogger::kNext;
}
References v8::internal::V8FileLogger::kNext, v8::internal::time, v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by v8::internal::V8FileLogger::FunctionEvent().
CodeLinePosEvent()
void v8::internal::anonymous_namespace{log.cc}::CodeLinePosEvent (JitLogger & jit_logger, Address code_start, SourcePositionTableIterator & iter, JitCodeEvent::CodeType code_type)
Definition at line 1753 of file log.cc.
                                                      {
  void* jit_handler_data = jit_logger.StartCodePosInfoEvent(code_type);
  for (; !iter.done(); iter.Advance()) {
    if (iter.is_statement()) {
      jit_logger.AddCodeLinePosInfoEvent(jit_handler_data, iter.code_offset(),
                                         iter.source_position().ScriptOffset(),
                                         JitCodeEvent::STATEMENT_POSITION,
                                         code_type);
    }
    jit_logger.AddCodeLinePosInfoEvent(jit_handler_data, iter.code_offset(),
                                       iter.source_position().ScriptOffset(),
                                       JitCodeEvent::POSITION, code_type);
  }
  jit_logger.EndCodePosInfoEvent(code_start, jit_handler_data, code_type);
}
References v8::internal::JitLogger::AddCodeLinePosInfoEvent(), v8::internal::SourcePositionTableIterator::Advance(), v8::internal::SourcePositionTableIterator::code_offset(), v8::internal::SourcePositionTableIterator::done(), v8::internal::JitLogger::EndCodePosInfoEvent(), v8::internal::SourcePositionTableIterator::is_statement(), v8::JitCodeEvent::POSITION, v8::internal::SourcePosition::ScriptOffset(), v8::internal::SourcePositionTableIterator::source_position(), v8::internal::JitLogger::StartCodePosInfoEvent(), and v8::JitCodeEvent::STATEMENT_POSITION.
Referenced by v8::internal::V8FileLogger::CodeLinePosInfoRecordEvent().
ComputeMarker()
const char* v8::internal::anonymous_namespace{log.cc}::ComputeMarker (Tagged< SharedFunctionInfo > shared, Tagged< AbstractCode > code)
Definition at line 129 of file log.cc.
                                                     {
  PtrComprCageBase cage_base = GetPtrComprCageBase(shared);
  CodeKind kind = code->kind(cage_base);
  // We record interpreter trampoline builtin copies as having the
  // "interpreted" marker.
  if (v8_flags.interpreted_frames_native_stack && kind == CodeKind::BUILTIN &&
      code->has_instruction_stream(cage_base) &&
      code->builtin_id(cage_base) == Builtin::kInterpreterEntryTrampoline) {
    kind = CodeKind::INTERPRETED_FUNCTION;
  }
  if (shared->all_optimization_disabled() &&
      kind == CodeKind::INTERPRETED_FUNCTION) {
    return "";
  }
  return CodeKindToMarker(
      kind, IsCode(code) && code->GetCode()->is_context_specialized());
}
References BUILTIN, code, v8::internal::CodeKindToMarker(), v8::internal::GetPtrComprCageBase(), and v8::internal::v8_flags.
Referenced by v8::internal::V8FileLogger::CodeCreateEvent(), and v8::internal::CodeEventLogger::CodeCreateEvent().
GetCodeEventTypeForTag()
v8::CodeEventType v8::internal::anonymous_namespace{log.cc}::GetCodeEventTypeForTag (LogEventListener::CodeTag tag)
Definition at line 93 of file log.cc.
                                                                    {
  switch (tag) {
    case LogEventListener::CodeTag::kLength:
    // Manually create this switch, since v8::CodeEventType is API expose and
    // cannot be easily modified.
    case LogEventListener::CodeTag::kBuiltin:
      return v8::CodeEventType::kBuiltinType;
    case LogEventListener::CodeTag::kCallback:
      return v8::CodeEventType::kCallbackType;
    case LogEventListener::CodeTag::kEval:
      return v8::CodeEventType::kEvalType;
    case LogEventListener::CodeTag::kNativeFunction:
    case LogEventListener::CodeTag::kFunction:
      return v8::CodeEventType::kFunctionType;
    case LogEventListener::CodeTag::kHandler:
      return v8::CodeEventType::kHandlerType;
    case LogEventListener::CodeTag::kBytecodeHandler:
      return v8::CodeEventType::kBytecodeHandlerType;
    case LogEventListener::CodeTag::kRegExp:
      return v8::CodeEventType::kRegExpType;
    case LogEventListener::CodeTag::kNativeScript:
    case LogEventListener::CodeTag::kScript:
      return v8::CodeEventType::kScriptType;
    case LogEventListener::CodeTag::kStub:
      return v8::CodeEventType::kStubType;
  }
  UNREACHABLE();
}
References v8::internal::torque::ls::kFunction, and v8::internal::UNREACHABLE().
Referenced by v8::internal::ExternalLogEventListener::CodeCreateEvent(), and v8::internal::ExternalLogEventListener::RegExpCodeCreateEvent().
InitializeCodeEvent()
void v8::internal::anonymous_namespace{log.cc}::InitializeCodeEvent (Isolate * isolate, CodeEvent * event, Address previous_code_start_address, Address code_start_address, int code_size)
Definition at line 637 of file log.cc.
                                                                    {
  event->previous_code_start_address =
      static_cast<uintptr_t>(previous_code_start_address);
  event->code_start_address = static_cast<uintptr_t>(code_start_address);
  event->code_size = static_cast<size_t>(code_size);
  event->function_name = isolate->factory()->empty_string();
  event->script_name = isolate->factory()->empty_string();
  event->script_line = 0;
  event->script_column = 0;
  event->code_type = v8::CodeEventType::kRelocationType;
  event->comment = "";
}
References v8::internal::Isolate::factory().
Referenced by v8::internal::ExternalLogEventListener::BytecodeMoveEvent(), and v8::internal::ExternalLogEventListener::CodeMoveEvent().