v8::internal::anonymous_namespace{asm-scanner.cc} Namespace Reference
Functions
bool IsValidImplicitOctal (std::string_view number)
Variables
static const int kMaxIdentifierCount = 0xF000000
Function Documentation
IsValidImplicitOctal()
bool v8::internal::anonymous_namespace{asm-scanner.cc}::IsValidImplicitOctal (std::string_view number)
Definition at line 276 of file asm-scanner.cc.
                                                 {
  DCHECK_EQ(number[0], '0');
  return std::all_of(number.begin() + 1, number.end(), IsOctalDigit);
}
References v8::base::all_of(), DCHECK_EQ, and v8::internal::IsOctalDigit().
Referenced by v8::internal::AsmJsScanner::ConsumeNumber().
Variable Documentation
kMaxIdentifierCount
const int v8::internal::anonymous_namespace{asm-scanner.cc}::kMaxIdentifierCount = 0xF000000 [static]
Definition at line 21 of file asm-scanner.cc.
Referenced by v8::internal::AsmJsScanner::ConsumeIdentifier().