v8::internal::anonymous_namespace{protectors.cc} Namespace Reference
Functions
void TraceProtectorInvalidation (const char *protector_name)
constexpr bool IsDefined (v8::Isolate::UseCounterFeature)
Function Documentation
IsDefined()
constexpr bool v8::internal::anonymous_namespace{protectors.cc}::IsDefined (v8::Isolate::UseCounterFeature) [constexpr]
Definition at line 39 of file protectors.cc.
{ return true; }
Referenced by v8::internal::compiler::InstructionSelector::IsLive(), and v8::internal::compiler::InstructionSelector::IsReallyLive().
TraceProtectorInvalidation()
void v8::internal::anonymous_namespace{protectors.cc}::TraceProtectorInvalidation (const char * protector_name)
Definition at line 21 of file protectors.cc.
                                                            {
  DCHECK(v8_flags.trace_protector_invalidation);
  static constexpr char kInvalidateProtectorTracingCategory[] =
      "V8.InvalidateProtector";
  static constexpr char kInvalidateProtectorTracingArg[] = "protector-name";
  DCHECK(v8_flags.trace_protector_invalidation);
  // TODO(jgruber): Remove the PrintF once tracing can output to stdout.
  i::PrintF("Invalidating protector cell %s\n", protector_name);
  TRACE_EVENT_INSTANT1("v8", kInvalidateProtectorTracingCategory,
                       TRACE_EVENT_SCOPE_THREAD, kInvalidateProtectorTracingArg,
                       protector_name);
}
References v8::internal::DCHECK(), v8::internal::PrintF(), TRACE_EVENT_INSTANT1, TRACE_EVENT_SCOPE_THREAD, and v8::internal::v8_flags.