v8::internal::anonymous_namespace{js-relative-time-format.cc} Namespace Reference
Enumerations
enum class Style { LONG
, SHORT
, NARROW
 }
Functions
UDateRelativeDateTimeFormatterStyle toIcuStyle (Style style)
Style fromIcuStyle (UDateRelativeDateTimeFormatterStyle icu_style)
DirectHandle< String > StyleAsString (Isolate *isolate, Style style)
DirectHandle< String > UnitAsString (Isolate *isolate, URelativeDateTimeUnit unit_enum)
bool GetURelativeDateTimeUnit (DirectHandle< String > unit, URelativeDateTimeUnit *unit_enum)
template<typename T >
MaybeDirectHandle< T > FormatCommon (Isolate *isolate, DirectHandle< JSRelativeTimeFormat > format, Handle< Object > value_obj, Handle< Object > unit_obj, const char *func_name, MaybeDirectHandle< T >(*formatToResult)(Isolate *, const icu::FormattedRelativeDateTime &, DirectHandle< String >, bool))
MaybeDirectHandle< String > FormatToString (Isolate *isolate, const icu::FormattedRelativeDateTime &formatted, DirectHandle< String > unit, bool is_nan)
Maybe< bool > AddLiteral (Isolate *isolate, DirectHandle< JSArray > array, const icu::UnicodeString &string, int32_t index, int32_t start, int32_t limit)
Maybe< bool > AddUnit (Isolate *isolate, DirectHandle< JSArray > array, const icu::UnicodeString &string, int32_t index, const NumberFormatSpan &part, DirectHandle< String > unit, bool is_nan)
MaybeDirectHandle< JSArray > FormatToJSArray (Isolate *isolate, const icu::FormattedRelativeDateTime &formatted, DirectHandle< String > unit, bool is_nan)
Enumeration Type Documentation
Style
enum v8::internal::anonymous_namespace{js-relative-time-format.cc}::Style [strong]
Enumerator
LONG
SHORT
NARROW
Definition at line 36 of file js-relative-time-format.cc.
                 {
  LONG, // Everything spelled out.
  SHORT, // Abbreviations used when possible.
  NARROW // Use the shortest possible form.
};
Function Documentation
AddLiteral()
Maybe<bool> v8::internal::anonymous_namespace{js-relative-time-format.cc}::AddLiteral (Isolate * isolate, DirectHandle< JSArray > array, const icu::UnicodeString & string, int32_t index, int32_t start, int32_t limit)
Definition at line 391 of file js-relative-time-format.cc.
                                                     {
  DirectHandle<String> substring;
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, substring, Intl::ToString(isolate, string, start, limit),
      Nothing<bool>());
  Intl::AddElement(isolate, array, index, isolate->factory()->literal_string(),
                   substring);
  return Just(true);
}
References v8::internal::Intl::AddElement(), ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::Isolate::factory(), v8::internal::index, v8::Just(), and v8::internal::Intl::ToString().
Referenced by FormatToJSArray().
AddUnit()
Maybe<bool> v8::internal::anonymous_namespace{js-relative-time-format.cc}::AddUnit (Isolate * isolate, DirectHandle< JSArray > array, const icu::UnicodeString & string, int32_t index, const NumberFormatSpan & part, DirectHandle< String > unit, bool is_nan)
Definition at line 403 of file js-relative-time-format.cc.
                                 {
  DirectHandle<String> substring;
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, substring,
      Intl::ToString(isolate, string, part.begin_pos, part.end_pos),
      Nothing<bool>());
  Intl::AddElement(isolate, array, index,
                   Intl::NumberFieldToType(isolate, part, string, is_nan),
                   substring, isolate->factory()->unit_string(), unit);
  return Just(true);
}
References v8::internal::Intl::AddElement(), ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::NumberFormatSpan::begin_pos, v8::internal::NumberFormatSpan::end_pos, v8::internal::Isolate::factory(), v8::internal::index, v8::Just(), v8::internal::Intl::NumberFieldToType(), and v8::internal::Intl::ToString().
Referenced by FormatToJSArray().
FormatCommon()
template<typename T >
MaybeDirectHandle<T> v8::internal::anonymous_namespace{js-relative-time-format.cc}::FormatCommon (Isolate * isolate, DirectHandle< JSRelativeTimeFormat > format, Handle< Object > value_obj, Handle< Object > unit_obj, const char * func_name, MaybeDirectHandle< T >(*)(Isolate *, const icu::FormattedRelativeDateTime &, DirectHandle< String >, bool) formatToResult)
Definition at line 336 of file js-relative-time-format.cc.
               {
  // 3. Let value be ? ToNumber(value).
  DirectHandle<Object> value;
  ASSIGN_RETURN_ON_EXCEPTION(isolate, value,
                             Object::ToNumber(isolate, value_obj));
  double number = Object::NumberValue(*value);
  // 4. Let unit be ? ToString(unit).
  Handle<String> unit;
  ASSIGN_RETURN_ON_EXCEPTION(isolate, unit,
                             Object::ToString(isolate, unit_obj));
  // 4. If isFinite(value) is false, then throw a RangeError exception.
  if (!std::isfinite(number)) {
    THROW_NEW_ERROR(
        isolate, NewRangeError(
                     MessageTemplate::kNotFiniteNumber,
                     isolate->factory()->NewStringFromAsciiChecked(func_name)));
  }
  icu::RelativeDateTimeFormatter* formatter = format->icu_formatter()->raw();
  DCHECK_NOT_NULL(formatter);
  URelativeDateTimeUnit unit_enum;
  if (!GetURelativeDateTimeUnit(unit, &unit_enum)) {
    THROW_NEW_ERROR(
        isolate,
        NewRangeError(MessageTemplate::kInvalidUnit,
                      isolate->factory()->NewStringFromAsciiChecked(func_name),
                      unit));
  }
  UErrorCode status = U_ZERO_ERROR;
  icu::FormattedRelativeDateTime formatted =
      (format->numeric() == JSRelativeTimeFormat::Numeric::ALWAYS)
          ? formatter->formatNumericToValue(number, unit_enum, status)
          : formatter->formatToValue(number, unit_enum, status);
  if (U_FAILURE(status)) {
    THROW_NEW_ERROR(isolate, NewTypeError(MessageTemplate::kIcuError));
  }
  return formatToResult(isolate, formatted, UnitAsString(isolate, unit_enum),
                        IsNaN(*value));
}
References v8::internal::JSRelativeTimeFormat::ALWAYS, ASSIGN_RETURN_ON_EXCEPTION, DCHECK_NOT_NULL, v8::internal::Isolate::factory(), v8::internal::format, GetURelativeDateTimeUnit(), v8::internal::IsNaN(), v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), v8::internal::Object::NumberValue(), v8::internal::status, THROW_NEW_ERROR, v8::Value::ToNumber(), v8::Value::ToString(), UnitAsString(), and v8::internal::value.
FormatToJSArray()
MaybeDirectHandle<JSArray> v8::internal::anonymous_namespace{js-relative-time-format.cc}::FormatToJSArray (Isolate * isolate, const icu::FormattedRelativeDateTime & formatted, DirectHandle< String > unit, bool is_nan)
Definition at line 418 of file js-relative-time-format.cc.
                                            {
  UErrorCode status = U_ZERO_ERROR;
  icu::UnicodeString string = formatted.toString(status);
  Factory* factory = isolate->factory();
  DirectHandle<JSArray> array = factory->NewJSArray(0);
  icu::ConstrainedFieldPosition cfpos;
  cfpos.constrainCategory(UFIELD_CATEGORY_NUMBER);
  int32_t index = 0;
  int32_t previous_end = 0;
  DirectHandle<String> substring;
  std::vector<std::pair<int32_t, int32_t>> groups;
  while (formatted.nextPosition(cfpos, status) && U_SUCCESS(status)) {
    int32_t category = cfpos.getCategory();
    int32_t field = cfpos.getField();
    int32_t start = cfpos.getStart();
    int32_t limit = cfpos.getLimit();
    if (category == UFIELD_CATEGORY_NUMBER) {
      if (field == UNUM_GROUPING_SEPARATOR_FIELD) {
        groups.push_back(std::pair<int32_t, int32_t>(start, limit));
        continue;
      }
      if (start > previous_end) {
        Maybe<bool> maybe_added =
            AddLiteral(isolate, array, string, index++, previous_end, start);
        MAYBE_RETURN(maybe_added, DirectHandle<JSArray>());
      }
      if (field == UNUM_INTEGER_FIELD) {
        for (auto start_limit : groups) {
          if (start_limit.first > start) {
            Maybe<bool> maybe_added =
                AddUnit(isolate, array, string, index++,
                        NumberFormatSpan(field, start, start_limit.first), unit,
                        is_nan);
            MAYBE_RETURN(maybe_added, DirectHandle<JSArray>());
            maybe_added =
                AddUnit(isolate, array, string, index++,
                        NumberFormatSpan(UNUM_GROUPING_SEPARATOR_FIELD,
                                         start_limit.first, start_limit.second),
                        unit, is_nan);
            MAYBE_RETURN(maybe_added, DirectHandle<JSArray>());
            start = start_limit.second;
          }
        }
      }
      Maybe<bool> maybe_added =
          AddUnit(isolate, array, string, index++,
                  NumberFormatSpan(field, start, limit), unit, is_nan);
      MAYBE_RETURN(maybe_added, DirectHandle<JSArray>());
      previous_end = limit;
    }
  }
  if (U_FAILURE(status)) {
    THROW_NEW_ERROR(isolate, NewTypeError(MessageTemplate::kIcuError));
  }
  if (string.length() > previous_end) {
    Maybe<bool> maybe_added = AddLiteral(isolate, array, string, index,
                                         previous_end, string.length());
    MAYBE_RETURN(maybe_added, DirectHandle<JSArray>());
  }
  JSObject::ValidateElements(isolate, *array);
  return array;
}
References AddLiteral(), AddUnit(), v8::internal::Isolate::factory(), v8::internal::index, v8::internal::length, MAYBE_RETURN, v8::internal::Factory::NewJSArray(), v8::internal::status, THROW_NEW_ERROR, and v8::internal::JSObject::ValidateElements().
Referenced by v8::internal::JSRelativeTimeFormat::FormatToParts().
FormatToString()
MaybeDirectHandle<String> v8::internal::anonymous_namespace{js-relative-time-format.cc}::FormatToString (Isolate * isolate, const icu::FormattedRelativeDateTime & formatted, DirectHandle< String > unit, bool is_nan)
Definition at line 380 of file js-relative-time-format.cc.
                                            {
  UErrorCode status = U_ZERO_ERROR;
  icu::UnicodeString result = formatted.toString(status);
  if (U_FAILURE(status)) {
    THROW_NEW_ERROR(isolate, NewTypeError(MessageTemplate::kIcuError));
  }
  return Intl::ToString(isolate, result);
}
References v8::base::internal::result, v8::internal::status, THROW_NEW_ERROR, and v8::internal::Intl::ToString().
Referenced by v8::internal::JSRelativeTimeFormat::Format().
fromIcuStyle()
Style v8::internal::anonymous_namespace{js-relative-time-format.cc}::fromIcuStyle (UDateRelativeDateTimeFormatterStyle icu_style)
Definition at line 54 of file js-relative-time-format.cc.
                                                                  {
  switch (icu_style) {
    case UDAT_STYLE_LONG:
      return Style::LONG;
    case UDAT_STYLE_SHORT:
      return Style::SHORT;
    case UDAT_STYLE_NARROW:
      return Style::NARROW;
    case UDAT_STYLE_COUNT:
      UNREACHABLE();
  }
  UNREACHABLE();
}
References v8::internal::UNREACHABLE().
Referenced by v8::internal::JSRelativeTimeFormat::ResolvedOptions().
GetURelativeDateTimeUnit()
bool v8::internal::anonymous_namespace{js-relative-time-format.cc}::GetURelativeDateTimeUnit (DirectHandle< String > unit, URelativeDateTimeUnit * unit_enum)
Definition at line 310 of file js-relative-time-format.cc.
                                                                {
  std::string unit_str = unit->ToStdString();
  if (unit_str == "second" || unit_str == "seconds") {
    *unit_enum = UDAT_REL_UNIT_SECOND;
  } else if (unit_str == "minute" || unit_str == "minutes") {
    *unit_enum = UDAT_REL_UNIT_MINUTE;
  } else if (unit_str == "hour" || unit_str == "hours") {
    *unit_enum = UDAT_REL_UNIT_HOUR;
  } else if (unit_str == "day" || unit_str == "days") {
    *unit_enum = UDAT_REL_UNIT_DAY;
  } else if (unit_str == "week" || unit_str == "weeks") {
    *unit_enum = UDAT_REL_UNIT_WEEK;
  } else if (unit_str == "month" || unit_str == "months") {
    *unit_enum = UDAT_REL_UNIT_MONTH;
  } else if (unit_str == "quarter" || unit_str == "quarters") {
    *unit_enum = UDAT_REL_UNIT_QUARTER;
  } else if (unit_str == "year" || unit_str == "years") {
    *unit_enum = UDAT_REL_UNIT_YEAR;
  } else {
    return false;
  }
  return true;
}
References v8::internal::string.
Referenced by FormatCommon().
StyleAsString()
DirectHandle<String> v8::internal::anonymous_namespace{js-relative-time-format.cc}::StyleAsString (Isolate * isolate, Style style)
Definition at line 236 of file js-relative-time-format.cc.
                                                                  {
  switch (style) {
    case Style::LONG:
      return isolate->factory()->long_string();
    case Style::SHORT:
      return isolate->factory()->short_string();
    case Style::NARROW:
      return isolate->factory()->narrow_string();
  }
  UNREACHABLE();
}
References v8::internal::Isolate::factory(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::JSRelativeTimeFormat::ResolvedOptions().
toIcuStyle()
UDateRelativeDateTimeFormatterStyle v8::internal::anonymous_namespace{js-relative-time-format.cc}::toIcuStyle (Style style)
Definition at line 42 of file js-relative-time-format.cc.
                                                            {
  switch (style) {
    case Style::LONG:
      return UDAT_STYLE_LONG;
    case Style::SHORT:
      return UDAT_STYLE_SHORT;
    case Style::NARROW:
      return UDAT_STYLE_NARROW;
  }
  UNREACHABLE();
}
References v8::internal::UNREACHABLE().
Referenced by v8::internal::JSRelativeTimeFormat::New().
UnitAsString()
DirectHandle<String> v8::internal::anonymous_namespace{js-relative-time-format.cc}::UnitAsString (Isolate * isolate, URelativeDateTimeUnit unit_enum)
Definition at line 285 of file js-relative-time-format.cc.
                                                                   {
  Factory* factory = isolate->factory();
  switch (unit_enum) {
    case UDAT_REL_UNIT_SECOND:
      return factory->second_string();
    case UDAT_REL_UNIT_MINUTE:
      return factory->minute_string();
    case UDAT_REL_UNIT_HOUR:
      return factory->hour_string();
    case UDAT_REL_UNIT_DAY:
      return factory->day_string();
    case UDAT_REL_UNIT_WEEK:
      return factory->week_string();
    case UDAT_REL_UNIT_MONTH:
      return factory->month_string();
    case UDAT_REL_UNIT_QUARTER:
      return factory->quarter_string();
    case UDAT_REL_UNIT_YEAR:
      return factory->year_string();
    default:
      UNREACHABLE();
  }
}
References v8::internal::Isolate::factory(), and v8::internal::UNREACHABLE().
Referenced by FormatCommon().