v8_inspector::anonymous_namespace{search-util.cc} Namespace Reference
Functions
String16 findMagicComment (const String16 &content, const String16 &name, bool multiline)
String16 createSearchRegexSource (const String16 &text)
std::unique_ptr< std::vector< size_t > > lineEndings (const String16 &text)
std::vector< std::pair< int, String16 > > scriptRegexpMatchesByLines (const V8Regex &regex, const String16 &text)
std::unique_ptr< protocol::Debugger::SearchMatch > buildObjectForSearchMatch (int lineNumber, const String16 &lineContent)
std::unique_ptr< V8Regex > createSearchRegex (V8InspectorImpl *inspector, const String16 &query, bool caseSensitive, bool isRegex)
Function Documentation
buildObjectForSearchMatch()
std::unique_ptr<protocol::Debugger::SearchMatch> v8_inspector::anonymous_namespace{search-util.cc}::buildObjectForSearchMatch (int lineNumber, const String16 & lineContent)
Definition at line 125 of file search-util.cc.
                                                 {
  return protocol::Debugger::SearchMatch::create()
      .setLineNumber(lineNumber)
      .setLineContent(lineContent)
      .build();
}
Referenced by v8_inspector::searchInTextByLinesImpl().
createSearchRegex()
std::unique_ptr<V8Regex> v8_inspector::anonymous_namespace{search-util.cc}::createSearchRegex (V8InspectorImpl * inspector, const String16 & query, bool caseSensitive, bool isRegex)
Definition at line 133 of file search-util.cc.
                                                                             {
  String16 regexSource = isRegex ? query : createSearchRegexSource(query);
  return std::unique_ptr<V8Regex>(
      new V8Regex(inspector, regexSource, caseSensitive));
}
References createSearchRegexSource().
Referenced by v8_inspector::searchInTextByLinesImpl().
createSearchRegexSource()
String16 v8_inspector::anonymous_namespace{search-util.cc}::createSearchRegexSource (const String16 & text)
Definition at line 69 of file search-util.cc.
                                                       {
  String16Builder result;
  for (size_t i = 0; i < text.length(); i++) {
    UChar c = text[i];
    if (c == '[' || c == ']' || c == '(' || c == ')' || c == '{' || c == '}' ||
        c == '+' || c == '-' || c == '*' || c == '.' || c == ',' || c == '?' ||
        c == '\\' || c == '^' || c == '$' || c == '|') {
      result.append('\\');
    }
    result.append(c);
  }
  return result.toString();
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8_inspector::String16::length(), and v8::base::internal::result.
Referenced by createSearchRegex().
findMagicComment()
String16 v8_inspector::anonymous_namespace{search-util.cc}::findMagicComment (const String16 & content, const String16 & name, bool multiline)
Definition at line 16 of file search-util.cc.
                                          {
  DCHECK_EQ(String16::kNotFound, name.find("="));
  size_t length = content.length();
  size_t nameLength = name.length();
  size_t pos = length;
  size_t equalSignPos = 0;
  size_t closingCommentPos = 0;
  while (true) {
    pos = content.reverseFind(name, pos);
    if (pos == String16::kNotFound) return String16();
    // Check for a /\/[\/*][@#][ \t]/ regexp (length of 4) before found name.
    if (pos < 4) return String16();
    pos -= 4;
    if (content[pos] != '/') continue;
    if ((content[pos + 1] != '/' || multiline) &&
        (content[pos + 1] != '*' || !multiline))
      continue;
    if (content[pos + 2] != '#' && content[pos + 2] != '@') continue;
    if (content[pos + 3] != ' ' && content[pos + 3] != '\t') continue;
    equalSignPos = pos + 4 + nameLength;
    if (equalSignPos >= length) continue;
    if (content[equalSignPos] != '=') continue;
    if (multiline) {
      closingCommentPos = content.find("*/", equalSignPos + 1);
      if (closingCommentPos == String16::kNotFound) return String16();
    }
    break;
  }
  DCHECK(equalSignPos);
  DCHECK_LT(equalSignPos, length);
  DCHECK(!multiline || closingCommentPos);
  size_t urlPos = equalSignPos + 1;
  String16 match = multiline
                       ? content.substring(urlPos, closingCommentPos - urlPos)
                       : content.substring(urlPos);
  size_t newLine = match.find("\n");
  if (newLine != String16::kNotFound) match = match.substring(0, newLine);
  match = match.stripWhiteSpace();
  for (size_t i = 0; i < match.length(); ++i) {
    UChar c = match[i];
    if (c == '"' || c == '\'' || c == ' ' || c == '\t') return "";
  }
  return match;
}
References DCHECK, DCHECK_EQ, DCHECK_LT, v8_inspector::String16::find(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8_inspector::String16::kNotFound, v8::internal::length, v8_inspector::String16::length(), name, v8_inspector::String16::reverseFind(), v8_inspector::String16::stripWhiteSpace(), and v8_inspector::String16::substring().
Referenced by v8_inspector::findDebugId(), v8_inspector::findSourceMapURL(), and v8_inspector::findSourceURL().
lineEndings()
std::unique_ptr<std::vector<size_t> > v8_inspector::anonymous_namespace{search-util.cc}::lineEndings (const String16 & text)
Definition at line 85 of file search-util.cc.
                                                                   {
  std::unique_ptr<std::vector<size_t>> result(new std::vector<size_t>());
  const String16 lineEndString = "\n";
  size_t start = 0;
  while (start < text.length()) {
    size_t lineEnd = text.find(lineEndString, start);
    if (lineEnd == String16::kNotFound) break;
    result->push_back(lineEnd);
    start = lineEnd + 1;
  }
  result->push_back(text.length());
  return result;
}
References v8_inspector::String16::find(), v8_inspector::String16::kNotFound, v8_inspector::String16::length(), and v8::base::internal::result.
Referenced by scriptRegexpMatchesByLines().
scriptRegexpMatchesByLines()
std::vector<std::pair<int, String16> > v8_inspector::anonymous_namespace{search-util.cc}::scriptRegexpMatchesByLines (const V8Regex & regex, const String16 & text)
Definition at line 102 of file search-util.cc.
                                                {
  std::vector<std::pair<int, String16>> result;
  if (text.isEmpty()) return result;
  std::unique_ptr<std::vector<size_t>> endings(lineEndings(text));
  size_t size = endings->size();
  size_t start = 0;
  for (size_t lineNumber = 0; lineNumber < size; ++lineNumber) {
    size_t lineEnd = endings->at(lineNumber);
    String16 line = text.substring(start, lineEnd - start);
    if (line.length() && line[line.length() - 1] == '\r')
      line = line.substring(0, line.length() - 1);
    int matchLength;
    if (regex.match(line, 0, &matchLength) != -1)
      result.push_back(std::pair<int, String16>(lineNumber, line));
    start = lineEnd + 1;
  }
  return result;
}
References v8_inspector::String16::isEmpty(), v8_inspector::String16::length(), lineEndings(), v8_inspector::V8Regex::match(), v8::base::internal::result, size(), and v8_inspector::String16::substring().
Referenced by v8_inspector::searchInTextByLinesImpl().