v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc} Namespace Reference
Namespaces
 HeapProfilerAgentState
Classes
class HeapSnapshotProgress
class GlobalObjectNameResolver
class HeapSnapshotOutputStream
class InspectableHeapObject
class HeapStatsStream
Functions
v8::Local< v8::Object > objectByHeapObjectId (v8::Isolate *isolate, int id)
std::unique_ptr< protocol::HeapProfiler::SamplingHeapProfileNode > buildSampingHeapProfileNode (v8::Isolate *isolate, const v8::AllocationProfile::Node *node)
Function Documentation
buildSampingHeapProfileNode()
std::unique_ptr<protocol::HeapProfiler::SamplingHeapProfileNode> v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc}::buildSampingHeapProfileNode (v8::Isolate * isolate, const v8::AllocationProfile::Node * node)
Definition at line 582 of file v8-heap-profiler-agent-impl.cc.
                                                                 {
  auto children = std::make_unique<
      protocol::Array<protocol::HeapProfiler::SamplingHeapProfileNode>>();
  for (const auto* child : node->children)
    children->emplace_back(buildSampingHeapProfileNode(isolate, child));
  size_t selfSize = 0;
  for (const auto& allocation : node->allocations)
    selfSize += allocation.size * allocation.count;
  std::unique_ptr<protocol::Runtime::CallFrame> callFrame =
      protocol::Runtime::CallFrame::create()
          .setFunctionName(toProtocolString(isolate, node->name))
          .setScriptId(String16::fromInteger(node->script_id))
          .setUrl(toProtocolString(isolate, node->script_name))
          .setLineNumber(node->line_number - 1)
          .setColumnNumber(node->column_number - 1)
          .build();
  std::unique_ptr<protocol::HeapProfiler::SamplingHeapProfileNode> result =
      protocol::HeapProfiler::SamplingHeapProfileNode::create()
          .setCallFrame(std::move(callFrame))
          .setSelfSize(selfSize)
          .setChildren(std::move(children))
          .setId(node->node_id)
          .build();
  return result;
}
References v8::AllocationProfile::Node::allocations, v8::AllocationProfile::Node::children, v8::AllocationProfile::Node::column_number, v8_inspector::String16::fromInteger(), v8::AllocationProfile::Node::line_number, v8::AllocationProfile::Node::name, v8::AllocationProfile::Node::node_id, v8::base::internal::result, v8::AllocationProfile::Node::script_id, v8::AllocationProfile::Node::script_name, and v8_inspector::toProtocolString().
Referenced by v8_inspector::V8HeapProfilerAgentImpl::getSamplingProfile().
objectByHeapObjectId()
v8::Local<v8::Object> v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc}::objectByHeapObjectId (v8::Isolate * isolate, int id)
Definition at line 103 of file v8-heap-profiler-agent-impl.cc.
                                                                   {
  v8::HeapProfiler* profiler = isolate->GetHeapProfiler();
  v8::Local<v8::Value> value = profiler->FindObjectById(id);
  if (value.IsEmpty() || !value->IsObject()) return v8::Local<v8::Object>();
  return value.As<v8::Object>();
}
References v8::HeapProfiler::FindObjectById(), v8::Isolate::GetHeapProfiler(), and v8::internal::value.
Referenced by v8_inspector::V8HeapProfilerAgentImpl::addInspectedHeapObject(), v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc}::InspectableHeapObject::get(), and v8_inspector::V8HeapProfilerAgentImpl::getObjectByHeapObjectId().