cppgc::internal::anonymous_namespace{explicit-management.cc} Namespace Reference
Functions
bool InGC (HeapHandle &heap_handle)
bool Grow (HeapObjectHeader &header, BasePage &base_page, size_t new_size, size_t size_delta)
bool Shrink (HeapObjectHeader &header, BasePage &base_page, size_t new_size, size_t size_delta)
Function Documentation
Grow()
bool cppgc::internal::anonymous_namespace{explicit-management.cc}::Grow (HeapObjectHeader & header, BasePage & base_page, size_t new_size, size_t size_delta)
Definition at line 91 of file explicit-management.cc.
                             {
  DCHECK_GE(new_size, header.AllocatedSize() + kAllocationGranularity);
  DCHECK_GE(size_delta, kAllocationGranularity);
  DCHECK(!base_page.is_large());
  auto& normal_space = *static_cast<NormalPageSpace*>(&base_page.space());
  auto& lab = normal_space.linear_allocation_buffer();
  if (lab.start() == header.ObjectEnd() && lab.size() >= size_delta) {
    // LABs are considered used memory which means that no allocated size
    // adjustments are needed.
    Address delta_start = lab.Allocate(size_delta);
    SetMemoryAccessible(delta_start, size_delta);
    header.SetAllocatedSize(new_size);
#if defined(CPPGC_YOUNG_GENERATION)
    if (auto& heap_base = *normal_space.raw_heap()->heap();
        heap_base.generational_gc_supported()) {
      if (header.IsMarked()) {
        base_page.IncrementMarkedBytes(
            header.AllocatedSize<AccessMode::kNonAtomic>());
      }
    }
#endif // defined(CPPGC_YOUNG_GENERATION)
    return true;
  }
  return false;
}
References cppgc::internal::NormalPageSpace::LinearAllocationBuffer::Allocate(), cppgc::internal::HeapObjectHeader::AllocatedSize(), DCHECK, DCHECK_GE, cppgc::internal::BasePage::IncrementMarkedBytes(), cppgc::internal::BasePage::is_large(), cppgc::internal::HeapObjectHeader::IsMarked(), cppgc::internal::kAllocationGranularity, cppgc::internal::kNonAtomic, cppgc::internal::NormalPageSpace::linear_allocation_buffer(), cppgc::internal::HeapObjectHeader::ObjectEnd(), cppgc::internal::HeapObjectHeader::SetAllocatedSize(), cppgc::internal::SetMemoryAccessible(), and cppgc::internal::BasePage::space().
Referenced by v8::internal::SmallOrderedHashMap::Add(), v8::internal::SmallOrderedHashSet::Add(), v8::internal::SmallOrderedNameDictionary::Add(), v8::internal::compiler::ValueNumberingReducer::Reduce(), and cppgc::internal::ExplicitManagementImpl::Resize().
InGC()
bool cppgc::internal::anonymous_namespace{explicit-management.cc}::InGC (HeapHandle & heap_handle)
Definition at line 21 of file explicit-management.cc.
                                   {
  const auto& heap = HeapBase::From(heap_handle);
  // Whenever the GC is active, avoid modifying the object as it may mess with
  // state that the GC needs.
  return heap.in_atomic_pause() || heap.marker() ||
         heap.sweeper().IsSweepingInProgress();
}
References cppgc::internal::HeapBase::From().
Referenced by cppgc::internal::ExplicitManagementImpl::FreeUnreferencedObject(), and cppgc::internal::ExplicitManagementImpl::Resize().
Shrink()
bool cppgc::internal::anonymous_namespace{explicit-management.cc}::Shrink (HeapObjectHeader & header, BasePage & base_page, size_t new_size, size_t size_delta)
Definition at line 119 of file explicit-management.cc.
                               {
  DCHECK_GE(header.AllocatedSize(), new_size + kAllocationGranularity);
  DCHECK_GE(size_delta, kAllocationGranularity);
  DCHECK(!base_page.is_large());
  auto& normal_space = *static_cast<NormalPageSpace*>(&base_page.space());
  auto& lab = normal_space.linear_allocation_buffer();
  Address free_start = header.ObjectEnd() - size_delta;
  if (lab.start() == header.ObjectEnd()) {
    DCHECK_EQ(free_start, lab.start() - size_delta);
    // LABs are considered used memory which means that no allocated size
    // adjustments are needed.
    lab.Set(free_start, lab.size() + size_delta);
    SetMemoryInaccessible(lab.start(), size_delta);
    header.SetAllocatedSize(new_size);
  } else if (size_delta >= ObjectAllocator::kSmallestSpaceSize) {
    // Heuristic: Only return memory to the free list if the block is larger
    // than the smallest size class.
    SetMemoryInaccessible(free_start, size_delta);
    base_page.heap().stats_collector()->NotifyExplicitFree(size_delta);
    normal_space.free_list().Add({free_start, size_delta});
    NormalPage::From(&base_page)->object_start_bitmap().SetBit(free_start);
    header.SetAllocatedSize(new_size);
  }
#if defined(CPPGC_YOUNG_GENERATION)
  auto& heap = base_page.heap();
  if (heap.generational_gc_supported()) {
    heap.remembered_set().InvalidateRememberedSlotsInRange(
        free_start, free_start + size_delta);
    if (header.IsMarked()) {
      base_page.DecrementMarkedBytes(
          header.AllocatedSize<AccessMode::kNonAtomic>());
    }
  }
#endif // defined(CPPGC_YOUNG_GENERATION)
  // Return success in any case, as we want to avoid that embedders start
  // copying memory because of small deltas.
  return true;
}
References cppgc::internal::HeapObjectHeader::AllocatedSize(), DCHECK, DCHECK_EQ, DCHECK_GE, cppgc::internal::BasePage::DecrementMarkedBytes(), cppgc::internal::NormalPage::From(), cppgc::internal::BasePage::heap(), cppgc::internal::BasePage::is_large(), cppgc::internal::HeapObjectHeader::IsMarked(), cppgc::internal::kAllocationGranularity, cppgc::internal::kNonAtomic, cppgc::internal::ObjectAllocator::kSmallestSpaceSize, cppgc::internal::NormalPageSpace::linear_allocation_buffer(), cppgc::internal::StatsCollector::NotifyExplicitFree(), cppgc::internal::NormalPage::object_start_bitmap(), cppgc::internal::HeapObjectHeader::ObjectEnd(), cppgc::internal::HeapObjectHeader::SetAllocatedSize(), cppgc::internal::PlatformAwareObjectStartBitmap::SetBit(), cppgc::internal::SetMemoryInaccessible(), cppgc::internal::BasePage::space(), and cppgc::internal::HeapBase::stats_collector().
Referenced by v8::internal::FutexEmulation::CleanupAsyncWaiterPromise(), v8::internal::OrderedNameDictionary::DeleteEntry(), v8::internal::SmallOrderedNameDictionary::DeleteEntry(), v8::internal::anonymous_namespace{js-atomics-synchronization.cc}::RemovePromiseFromNativeContext(), v8::internal::requires(), cppgc::internal::ExplicitManagementImpl::Resize(), v8::internal::RUNTIME_FUNCTION(), v8::internal::OrderedNameDictionaryHandler::Shrink(), and v8::internal::JSFinalizationRegistry::ShrinkKeyMap().