v8::internal::anonymous_namespace{runtime-object.cc} Namespace Reference
Functions
Tagged< Object > DeleteProperty (Isolate *isolate, DirectHandle< Object > object, DirectHandle< Object > key, LanguageMode language_mode)
void CheckExcludedPropertiesAreOnCallerStack (Isolate *isolate, Address base, int count)
void CollectPrivateMethodsAndAccessorsFromContext (Isolate *isolate, DirectHandle< Context > context, DirectHandle< String > desc, Handle< Object > brand, IsStaticFlag is_static_flag, std::vector< PrivateMember > *results)
Maybe< bool > CollectPrivateMembersFromReceiver (Isolate *isolate, DirectHandle< JSReceiver > receiver, DirectHandle< String > desc, std::vector< PrivateMember > *results)
Maybe< bool > FindPrivateMembersFromReceiver (Isolate *isolate, DirectHandle< JSReceiver > receiver, DirectHandle< String > desc, MessageTemplate not_found_message, PrivateMember *result)
Function Documentation
CheckExcludedPropertiesAreOnCallerStack()
void v8::internal::anonymous_namespace{runtime-object.cc}::CheckExcludedPropertiesAreOnCallerStack (Isolate * isolate, Address base, int count)
Definition at line 1149 of file runtime-object.cc.
                                                        {
#ifdef DEBUG
  StackFrameIterator it(isolate);
  // Don't need to check when there's no excluded properties.
  if (count == 0) return;
  DCHECK(!it.done());
  // Properties are pass in order on the stack, which means that their addresses
  // are in reverse order in memory (because stacks grow backwards). So, we
  // need to check if the _last_ property address is before the stack end...
  Address last_property = base - (count - 1) * kSystemPointerSize;
  DCHECK_GE(last_property, it.frame()->sp());
  // ... and for the first JS frame, make sure the _first_ property address is
  // after that stack frame's start.
  for (; !it.done(); it.Advance()) {
    if (it.frame()->is_javascript()) {
      DCHECK_LT(base, it.frame()->fp());
      return;
    }
  }
  // We should always find a JS frame.
  UNREACHABLE();
#endif
}
References v8::internal::StackFrameIterator::Advance(), v8::internal::DCHECK(), DCHECK_GE, DCHECK_LT, v8::internal::StackFrameIteratorBase::done(), v8::internal::StackFrame::fp(), v8::internal::StackFrameIterator::frame(), v8::internal::StackFrame::is_javascript(), v8::internal::kSystemPointerSize, v8::internal::StackFrame::sp(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::RUNTIME_FUNCTION().
CollectPrivateMembersFromReceiver()
Maybe<bool> v8::internal::anonymous_namespace{runtime-object.cc}::CollectPrivateMembersFromReceiver (Isolate * isolate, DirectHandle< JSReceiver > receiver, DirectHandle< String > desc, std::vector< PrivateMember > * results)
Definition at line 1406 of file runtime-object.cc.
                                                                  {
  PropertyFilter key_filter =
      static_cast<PropertyFilter>(PropertyFilter::PRIVATE_NAMES_ONLY);
  DirectHandle<FixedArray> keys;
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, keys,
      KeyAccumulator::GetKeys(isolate, receiver, KeyCollectionMode::kOwnOnly,
                              key_filter, GetKeysConversion::kConvertToString),
      Nothing<bool>());
  if (IsJSFunction(*receiver)) {
    Handle<JSFunction> func(Cast<JSFunction>(*receiver), isolate);
    DirectHandle<SharedFunctionInfo> shared(func->shared(), isolate);
    if (shared->is_class_constructor() &&
        shared->has_static_private_methods_or_accessors()) {
      DirectHandle<Context> receiver_context(
          Cast<JSFunction>(*receiver)->context(), isolate);
      CollectPrivateMethodsAndAccessorsFromContext(
          isolate, receiver_context, desc, func, IsStaticFlag::kStatic,
          results);
    }
  }
  for (int i = 0; i < keys->length(); ++i) {
    DirectHandle<Object> obj_key(keys->get(i), isolate);
    Handle<Symbol> symbol(Cast<Symbol>(*obj_key), isolate);
    CHECK(symbol->is_private_name());
    Handle<Object> value;
    ASSIGN_RETURN_ON_EXCEPTION_VALUE(
        isolate, value, Object::GetProperty(isolate, receiver, symbol),
        Nothing<bool>());
    if (symbol->is_private_brand()) {
      DirectHandle<Context> value_context(Cast<Context>(*value), isolate);
      CollectPrivateMethodsAndAccessorsFromContext(
          isolate, value_context, desc, symbol, IsStaticFlag::kNotStatic,
          results);
    } else {
      DirectHandle<String> symbol_desc(Cast<String>(symbol->description()),
                                       isolate);
      if (symbol_desc->Equals(*desc)) {
        results->push_back({
            PrivateMemberType::kPrivateField,
            symbol,
            value,
        });
      }
    }
  }
  return Just(true);
}
References ASSIGN_RETURN_ON_EXCEPTION_VALUE, CHECK, CollectPrivateMethodsAndAccessorsFromContext(), v8::internal::KeyAccumulator::GetKeys(), v8::internal::Object::GetProperty(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::Just(), v8::internal::kConvertToString, v8::internal::kNotStatic, v8::internal::kOwnOnly, v8::internal::kPrivateField, v8::internal::kStatic, v8::internal::PRIVATE_NAMES_ONLY, and v8::internal::value.
Referenced by FindPrivateMembersFromReceiver().
CollectPrivateMethodsAndAccessorsFromContext()
void v8::internal::anonymous_namespace{runtime-object.cc}::CollectPrivateMethodsAndAccessorsFromContext (Isolate * isolate, DirectHandle< Context > context, DirectHandle< String > desc, Handle< Object > brand, IsStaticFlag is_static_flag, std::vector< PrivateMember > * results)
Definition at line 1379 of file runtime-object.cc.
                                       {
  DirectHandle<ScopeInfo> scope_info(context->scope_info(), isolate);
  VariableLookupResult lookup_result;
  int context_index = scope_info->ContextSlotIndex(*desc, &lookup_result);
  if (context_index == -1 ||
      !IsPrivateMethodOrAccessorVariableMode(lookup_result.mode) ||
      lookup_result.is_static_flag != is_static_flag) {
    return;
  }
  Handle<Object> slot_value(context->GetNoCell(context_index), isolate);
  DCHECK_IMPLIES(lookup_result.mode == VariableMode::kPrivateMethod,
                 IsJSFunction(*slot_value));
  DCHECK_IMPLIES(lookup_result.mode != VariableMode::kPrivateMethod,
                 IsAccessorPair(*slot_value));
  results->push_back({
      lookup_result.mode == VariableMode::kPrivateMethod
          ? PrivateMemberType::kPrivateMethod
          : PrivateMemberType::kPrivateAccessor,
      brand,
      slot_value,
  });
}
References DCHECK_IMPLIES, v8::internal::VariableLookupResult::is_static_flag, v8::internal::IsPrivateMethodOrAccessorVariableMode(), v8::internal::kPrivateAccessor, v8::internal::kPrivateMethod, and v8::internal::VariableLookupResult::mode.
Referenced by CollectPrivateMembersFromReceiver().
DeleteProperty()
Tagged<Object> v8::internal::anonymous_namespace{runtime-object.cc}::DeleteProperty (Isolate * isolate, DirectHandle< Object > object, DirectHandle< Object > key, LanguageMode language_mode)
Definition at line 777 of file runtime-object.cc.
                                                          {
  DirectHandle<JSReceiver> receiver;
  ASSIGN_RETURN_FAILURE_ON_EXCEPTION(isolate, receiver,
                                     Object::ToObject(isolate, object));
  Maybe<bool> result =
      Runtime::DeleteObjectProperty(isolate, receiver, key, language_mode);
  MAYBE_RETURN(result, ReadOnlyRoots(isolate).exception());
  return isolate->heap()->ToBoolean(result.FromJust());
}
References ASSIGN_RETURN_FAILURE_ON_EXCEPTION, v8::internal::Runtime::DeleteObjectProperty(), v8::internal::Isolate::heap(), v8::internal::key, MAYBE_RETURN, v8::base::internal::result, v8::internal::Heap::ToBoolean(), and v8::Value::ToObject().
Referenced by v8::internal::compiler::BytecodeGraphBuilder::BuildDelete(), and v8::internal::RUNTIME_FUNCTION().
FindPrivateMembersFromReceiver()
Maybe<bool> v8::internal::anonymous_namespace{runtime-object.cc}::FindPrivateMembersFromReceiver (Isolate * isolate, DirectHandle< JSReceiver > receiver, DirectHandle< String > desc, MessageTemplate not_found_message, PrivateMember * result)
Definition at line 1461 of file runtime-object.cc.
                                                                  {
  std::vector<PrivateMember> results;
  MAYBE_RETURN(
      CollectPrivateMembersFromReceiver(isolate, receiver, desc, &results),
      Nothing<bool>());
  if (results.empty()) {
    THROW_NEW_ERROR_RETURN_VALUE(isolate, NewError(not_found_message, desc),
                                 Nothing<bool>());
  } else if (results.size() > 1) {
    THROW_NEW_ERROR_RETURN_VALUE(
        isolate, NewError(MessageTemplate::kConflictingPrivateName, desc),
        Nothing<bool>());
  }
  *result = results[0];
  return Just(true);
}
References CollectPrivateMembersFromReceiver(), v8::Just(), MAYBE_RETURN, v8::internal::anonymous_namespace{runtime-internal.cc}::NewError(), v8::base::internal::result, and THROW_NEW_ERROR_RETURN_VALUE.
Referenced by v8::internal::Runtime::GetPrivateMember(), and v8::internal::Runtime::SetPrivateMember().