v8::internal::compiler::anonymous_namespace{linkage.cc} Namespace Reference
Functions
LinkageLocation regloc (Register reg, MachineType type)
LinkageLocation regloc (DoubleRegister reg, MachineType type)
bool IsTaggedReg (const LinkageLocation &loc, Register reg)
Variables
constexpr int kFirstCallerSlotOffset = 1
constexpr int kNoCallerSlotOffset = 0
Function Documentation
IsTaggedReg()
bool v8::internal::compiler::anonymous_namespace{linkage.cc}::IsTaggedReg (const LinkageLocation & loc, Register reg) [inline]
Definition at line 757 of file linkage.cc.
                                                                  {
  return loc.IsRegister() && loc.AsRegister() == reg.code() &&
         loc.GetType().representation() ==
             MachineRepresentation::kTaggedPointer;
}
References v8::internal::kTaggedPointer, and v8::internal::loc.
Referenced by v8::internal::compiler::Linkage::GetParameterSecondaryLocation(), and v8::internal::compiler::Linkage::ParameterHasSecondaryLocation().
regloc() [1/2]
LinkageLocation v8::internal::compiler::anonymous_namespace{linkage.cc}::regloc (DoubleRegister reg, MachineType type) [inline]
Definition at line 34 of file linkage.cc.
                                                                    {
  return LinkageLocation::ForRegister(reg.code(), type);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::LinkageLocation::ForRegister(), and v8::internal::tracing::type.
Referenced by v8::internal::compiler::Linkage::GetBytecodeDispatchCallDescriptor(), v8::internal::compiler::Linkage::GetCEntryStubCallDescriptor(), v8::internal::compiler::Linkage::GetJSCallDescriptor(), and v8::internal::compiler::Linkage::GetStubCallDescriptor().
regloc() [2/2]
LinkageLocation v8::internal::compiler::anonymous_namespace{linkage.cc}::regloc (Register reg, MachineType type) [inline]
Definition at line 30 of file linkage.cc.
                                                              {
  return LinkageLocation::ForRegister(reg.code(), type);
}
References v8::internal::LinkageLocation::ForRegister(), and v8::internal::tracing::type.
Variable Documentation
kFirstCallerSlotOffset
constexpr int v8::internal::compiler::anonymous_namespace{linkage.cc}::kFirstCallerSlotOffset = 1 [constexpr]
Definition at line 27 of file linkage.cc.
Referenced by v8::internal::compiler::CallDescriptor::GetOffsetToFirstUnusedStackSlot().
kNoCallerSlotOffset
constexpr int v8::internal::compiler::anonymous_namespace{linkage.cc}::kNoCallerSlotOffset = 0 [constexpr]
Definition at line 28 of file linkage.cc.
Referenced by v8::internal::compiler::CallDescriptor::GetOffsetToReturns().