v8::internal::anonymous_namespace{gc-tracer.cc} Namespace Reference
Typedefs
using BytesAndDuration = ::heap::base::BytesAndDuration
Functions
CollectionEpoch next_epoch ()
std::optional< double > BoundedAverageSpeed (const base::RingBuffer< BytesAndDuration > &buffer)
double BoundedThroughput (const ::heap::base::SmoothedBytesAndDuration &buffer)
constexpr v8::base::TimeDelta YoungGenerationWallTime (const GCTracer::Event &event)
int TruncateToMs (base::TimeDelta delta)
void CopyTimeMetrics (::v8::metrics::GarbageCollectionPhases &metrics, const cppgc::internal::MetricRecorder::GCCycle::IncrementalPhases &cppgc_metrics)
void CopyTimeMetrics (::v8::metrics::GarbageCollectionPhases &metrics, const cppgc::internal::MetricRecorder::GCCycle::Phases &cppgc_metrics)
void CopySizeMetrics (::v8::metrics::GarbageCollectionSizes &metrics, const cppgc::internal::MetricRecorder::GCCycle::Sizes &cppgc_metrics)
::v8::metrics::Recorder::ContextId GetContextId (v8::internal::Isolate *isolate)
template<typename EventType >
void FlushBatchedEvents (v8::metrics::GarbageCollectionBatchedEvents< EventType > &batched_events, Isolate *isolate)
Variables
std::atomic< CollectionEpoch > global_epoch {0}
Typedef Documentation
BytesAndDuration
using v8::internal::anonymous_namespace{gc-tracer.cc}::BytesAndDuration = typedef ::heap::base::BytesAndDuration
Definition at line 53 of file gc-tracer.cc.
Function Documentation
BoundedAverageSpeed()
std::optional<double> v8::internal::anonymous_namespace{gc-tracer.cc}::BoundedAverageSpeed (const base::RingBuffer< BytesAndDuration > & buffer)
Definition at line 55 of file gc-tracer.cc.
                                                    {
  constexpr size_t kMinNonEmptySpeedInBytesPerMs = 1;
  constexpr size_t kMaxSpeedInBytesPerMs = GB;
  return ::heap::base::AverageSpeed(buffer, BytesAndDuration(), std::nullopt,
                                    kMinNonEmptySpeedInBytesPerMs,
                                    kMaxSpeedInBytesPerMs);
}
References heap::base::AverageSpeed(), and v8::internal::GB.
Referenced by v8::internal::GCTracer::CompactionSpeedInBytesPerMillisecond(), v8::internal::GCTracer::EmbedderSpeedInBytesPerMillisecond(), v8::internal::GCTracer::FinalIncrementalMarkCompactSpeedInBytesPerMillisecond(), v8::internal::GCTracer::MarkCompactSpeedInBytesPerMillisecond(), v8::internal::GCTracer::OldGenerationSpeedInBytesPerMillisecond(), and v8::internal::GCTracer::YoungGenerationSpeedInBytesPerMillisecond().
BoundedThroughput()
double v8::internal::anonymous_namespace{gc-tracer.cc}::BoundedThroughput (const ::heap::base::SmoothedBytesAndDuration & buffer)
Definition at line 64 of file gc-tracer.cc.
                                                                         {
  constexpr double kMaxSpeedInBytesPerMs = static_cast<double>(GB);
  return std::min(buffer.GetThroughput(), kMaxSpeedInBytesPerMs);
}
References v8::internal::GB.
Referenced by v8::internal::GCTracer::EmbedderAllocationThroughputInBytesPerMillisecond(), v8::internal::GCTracer::NewSpaceAllocationThroughputInBytesPerMillisecond(), and v8::internal::GCTracer::OldGenerationAllocationThroughputInBytesPerMillisecond().
CopySizeMetrics()
void v8::internal::anonymous_namespace{gc-tracer.cc}::CopySizeMetrics (::v8::metrics::GarbageCollectionSizes & metrics, const cppgc::internal::MetricRecorder::GCCycle::Sizes & cppgc_metrics)
Definition at line 1578 of file gc-tracer.cc.
                                                                  {
  DCHECK_NE(-1, cppgc_metrics.after_bytes);
  metrics.bytes_after = cppgc_metrics.after_bytes;
  DCHECK_NE(-1, cppgc_metrics.before_bytes);
  metrics.bytes_before = cppgc_metrics.before_bytes;
  DCHECK_NE(-1, cppgc_metrics.freed_bytes);
  metrics.bytes_freed = cppgc_metrics.freed_bytes;
}
References cppgc::internal::MetricRecorder::GCCycle::Sizes::after_bytes, cppgc::internal::MetricRecorder::GCCycle::Sizes::before_bytes, v8::metrics::GarbageCollectionSizes::bytes_after, v8::metrics::GarbageCollectionSizes::bytes_before, v8::metrics::GarbageCollectionSizes::bytes_freed, DCHECK_NE, and cppgc::internal::MetricRecorder::GCCycle::Sizes::freed_bytes.
Referenced by v8::internal::GCTracer::ReportFullCycleToRecorder(), and v8::internal::GCTracer::ReportYoungCycleToRecorder().
CopyTimeMetrics() [1/2]
void v8::internal::anonymous_namespace{gc-tracer.cc}::CopyTimeMetrics (::v8::metrics::GarbageCollectionPhases & metrics, const cppgc::internal::MetricRecorder::GCCycle::IncrementalPhases & cppgc_metrics)
Definition at line 1543 of file gc-tracer.cc.
                       {
  // Allow for uninitialized values (-1), in case incremental marking/sweeping
  // were not used.
  DCHECK_LE(-1, cppgc_metrics.mark_duration_us);
  metrics.mark_wall_clock_duration_in_us = cppgc_metrics.mark_duration_us;
  DCHECK_LE(-1, cppgc_metrics.sweep_duration_us);
  metrics.sweep_wall_clock_duration_in_us = cppgc_metrics.sweep_duration_us;
  // The total duration is initialized, even if both incremental
  // marking and sweeping were not used.
  metrics.total_wall_clock_duration_in_us =
      std::max(INT64_C(0), metrics.mark_wall_clock_duration_in_us) +
      std::max(INT64_C(0), metrics.sweep_wall_clock_duration_in_us);
}
References DCHECK_LE, cppgc::internal::MetricRecorder::GCCycle::IncrementalPhases::mark_duration_us, v8::metrics::GarbageCollectionPhases::mark_wall_clock_duration_in_us, cppgc::internal::MetricRecorder::GCCycle::IncrementalPhases::sweep_duration_us, v8::metrics::GarbageCollectionPhases::sweep_wall_clock_duration_in_us, and v8::metrics::GarbageCollectionPhases::total_wall_clock_duration_in_us.
CopyTimeMetrics() [2/2]
void v8::internal::anonymous_namespace{gc-tracer.cc}::CopyTimeMetrics (::v8::metrics::GarbageCollectionPhases & metrics, const cppgc::internal::MetricRecorder::GCCycle::Phases & cppgc_metrics)
Definition at line 1560 of file gc-tracer.cc.
                                                                   {
  DCHECK_NE(-1, cppgc_metrics.compact_duration_us);
  metrics.compact_wall_clock_duration_in_us = cppgc_metrics.compact_duration_us;
  DCHECK_NE(-1, cppgc_metrics.mark_duration_us);
  metrics.mark_wall_clock_duration_in_us = cppgc_metrics.mark_duration_us;
  DCHECK_NE(-1, cppgc_metrics.sweep_duration_us);
  metrics.sweep_wall_clock_duration_in_us = cppgc_metrics.sweep_duration_us;
  DCHECK_NE(-1, cppgc_metrics.weak_duration_us);
  metrics.weak_wall_clock_duration_in_us = cppgc_metrics.weak_duration_us;
  metrics.total_wall_clock_duration_in_us =
      metrics.compact_wall_clock_duration_in_us +
      metrics.mark_wall_clock_duration_in_us +
      metrics.sweep_wall_clock_duration_in_us +
      metrics.weak_wall_clock_duration_in_us;
}
References cppgc::internal::MetricRecorder::GCCycle::Phases::compact_duration_us, v8::metrics::GarbageCollectionPhases::compact_wall_clock_duration_in_us, DCHECK_NE, cppgc::internal::MetricRecorder::GCCycle::IncrementalPhases::mark_duration_us, v8::metrics::GarbageCollectionPhases::mark_wall_clock_duration_in_us, cppgc::internal::MetricRecorder::GCCycle::IncrementalPhases::sweep_duration_us, v8::metrics::GarbageCollectionPhases::sweep_wall_clock_duration_in_us, v8::metrics::GarbageCollectionPhases::total_wall_clock_duration_in_us, cppgc::internal::MetricRecorder::GCCycle::Phases::weak_duration_us, and v8::metrics::GarbageCollectionPhases::weak_wall_clock_duration_in_us.
Referenced by v8::internal::GCTracer::ReportFullCycleToRecorder(), and v8::internal::GCTracer::ReportYoungCycleToRecorder().
FlushBatchedEvents()
template<typename EventType >
void v8::internal::anonymous_namespace{gc-tracer.cc}::FlushBatchedEvents (v8::metrics::GarbageCollectionBatchedEvents< EventType > & batched_events, Isolate * isolate)
Definition at line 1599 of file gc-tracer.cc.
                      {
  DCHECK_NOT_NULL(isolate->metrics_recorder());
  DCHECK(!batched_events.events.empty());
  isolate->metrics_recorder()->AddMainThreadEvent(std::move(batched_events),
                                                  GetContextId(isolate));
  batched_events = {};
}
References v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::metrics::GarbageCollectionBatchedEvents< EventType >::events, GetContextId(), and v8::internal::Isolate::metrics_recorder().
Referenced by v8::internal::GCTracer::ReportFullCycleToRecorder(), v8::internal::GCTracer::ReportIncrementalMarkingStepToRecorder(), and v8::internal::GCTracer::ReportIncrementalSweepingStepToRecorder().
GetContextId()
::v8::metrics::Recorder::ContextId v8::internal::anonymous_namespace{gc-tracer.cc}::GetContextId (v8::internal::Isolate * isolate)
Definition at line 1589 of file gc-tracer.cc.
                                {
  DCHECK_NOT_NULL(isolate);
  if (isolate->context().is_null())
    return v8::metrics::Recorder::ContextId::Empty();
  HandleScope scope(isolate);
  return isolate->GetOrRegisterRecorderContextId(isolate->native_context());
}
References v8::internal::Isolate::context(), DCHECK_NOT_NULL, v8::metrics::Recorder::ContextId::Empty(), v8::internal::Isolate::GetOrRegisterRecorderContextId(), and v8::internal::Isolate::native_context().
Referenced by FlushBatchedEvents(), v8::internal::GCTracer::ReportFullCycleToRecorder(), and v8::internal::GCTracer::ReportYoungCycleToRecorder().
next_epoch()
CollectionEpoch v8::internal::anonymous_namespace{gc-tracer.cc}::next_epoch ()
Definition at line 49 of file gc-tracer.cc.
                             {
  return global_epoch.fetch_add(1, std::memory_order_relaxed) + 1;
}
References global_epoch.
Referenced by v8::internal::GCTracer::StartCycle().
TruncateToMs()
int v8::internal::anonymous_namespace{gc-tracer.cc}::TruncateToMs (base::TimeDelta delta) [inline]
Definition at line 1442 of file gc-tracer.cc.
                                                {
  return static_cast<int>(delta.InMilliseconds());
}
References v8::base::TimeDelta::InMilliseconds().
Referenced by v8::internal::GCTracer::RecordGCPhasesHistograms().
YoungGenerationWallTime()
constexpr v8::base::TimeDelta v8::internal::anonymous_namespace{gc-tracer.cc}::YoungGenerationWallTime (const GCTracer::Event & event) [constexpr]
Definition at line 452 of file gc-tracer.cc.
                                {
  return
      // Scavenger events.
      event.scopes[GCTracer::Scope::SCAVENGER] +
      event.scopes[GCTracer::Scope::SCAVENGER_BACKGROUND_SCAVENGE_PARALLEL] +
      // Minor MS events.
      event.scopes[GCTracer::Scope::MINOR_MS] +
      event.scopes[GCTracer::Scope::MINOR_MS_BACKGROUND_MARKING];
}
Referenced by v8::internal::GCTracer::ReportYoungCycleToRecorder(), and v8::internal::GCTracer::StopCycle().
Variable Documentation
global_epoch
std::atomic<CollectionEpoch> v8::internal::anonymous_namespace{gc-tracer.cc}::global_epoch {0}
Definition at line 47 of file gc-tracer.cc.
Referenced by next_epoch().