v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler Namespace Reference
Functions
bool BoolConstant (bool b)
intptr_t ChangeInt32ToIntPtr (int32_t i)
uintptr_t ChangeUint32ToWord (uint32_t u)
intptr_t IntPtrAdd (intptr_t a, intptr_t b)
intptr_t IntPtrMul (intptr_t a, intptr_t b)
bool IntPtrLessThan (intptr_t a, intptr_t b)
bool IntPtrLessThanOrEqual (intptr_t a, intptr_t b)
intptr_t Signed (uintptr_t u)
template<typename Smi >
int32_t SmiUntag (Smi s)
bool UintPtrLessThan (uintptr_t a, uintptr_t b)
uint32_t Unsigned (int32_t s)
bool Word32Equal (uint32_t a, uint32_t b)
bool Word32NotEqual (uint32_t a, uint32_t b)
int32_t ConstexprIntegerLiteralToInt32 (const IntegerLiteral &i)
int31_t ConstexprIntegerLiteralToInt31 (const IntegerLiteral &i)
intptr_t ConstexprIntegerLiteralToIntptr (const IntegerLiteral &i)
void Print (const char *str)
Function Documentation
BoolConstant()
bool v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::BoolConstant (bool b) [inline]
Definition at line 22 of file runtime-macro-shims.h.
{ return b; }
Referenced by v8::internal::CodeStubAssembler::EmitElementStore(), v8::internal::CodeStubAssembler::IsAdditiveSafeIntegerFeedbackEnabled(), v8::internal::CodeStubAssembler::IsInterestingProperty(), and v8::internal::CodeStubAssembler::IsJSArrayBufferViewDetachedOrOutOfBoundsBoolean().
ChangeInt32ToIntPtr()
intptr_t v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::ChangeInt32ToIntPtr (int32_t i) [inline]
Definition at line 23 of file runtime-macro-shims.h.
{ return i; }
References v8::internal::anonymous_namespace{json-stringifier.cc}::i.
Referenced by v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ArrayAtomicRMW(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ArrayGet(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ArraySet(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildChangeInt32ToNumber(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildIndirectCallTargetAndImplicitArg(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ChangeTaggedNumberToIntPtr(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::ConvertJSPrimitiveToUntaggedOrDeopt(), v8::internal::wasm::TurboshaftGraphBuildingInterface::DataViewGetter(), v8::internal::wasm::TurboshaftGraphBuildingInterface::DataViewSetter(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::DoubleArrayMinMax(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::FindOrderedHashEntry(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::GenerateStringEqualBuiltinCall(), v8::internal::wasm::TurboshaftGraphBuildingInterface::GetCodeUnitImpl(), v8::internal::interpreter::BytecodeHandlerReducer< Next >::LoadAndUntagRegister(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::LoadFieldByIndex(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::LowerGlobalSetOrGet(), v8::internal::CodeStubAssembler::PageMetadataFromMemoryChunk(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::CodeStubAssembler::SmiSar(), v8::internal::CodeStubAssembler::SmiShr(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::StringAt(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StringCodePointAt(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StringEqImpl(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::StringPrepareForGetCodeUnit(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::StringSubstring(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::TagSmi(), v8::internal::TF_BUILTIN(), and v8::internal::CodeStubAssembler::UnsignedSmiShl().
ChangeUint32ToWord()
uintptr_t v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::ChangeUint32ToWord (uint32_t u) [inline]
Definition at line 24 of file runtime-macro-shims.h.
{ return u; }
Referenced by v8::internal::CodeStubAssembler::ChangePositiveInt32ToIntPtr(), v8::internal::CodeStubAssembler::DecodeWordFromWord32(), v8::internal::CodeStubAssembler::ElementsKindToElementByteShift(), v8::internal::TF_BUILTIN(), v8::internal::CodeStubAssembler::UpdateWord32InWord(), and v8::internal::CodeStubAssembler::UpdateWordInWord32().
ConstexprIntegerLiteralToInt31()
int31_t v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::ConstexprIntegerLiteralToInt31 (const IntegerLiteral & i) [inline]
Definition at line 44 of file runtime-macro-shims.h.
                                                                       {
  return int31_t(ConstexprIntegerLiteralToInt32(i));
}
References ConstexprIntegerLiteralToInt32().
ConstexprIntegerLiteralToInt32()
int32_t v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::ConstexprIntegerLiteralToInt32 (const IntegerLiteral & i) [inline]
Definition at line 41 of file runtime-macro-shims.h.
                                                                       {
  return i.To<int32_t>();
}
Referenced by ConstexprIntegerLiteralToInt31().
ConstexprIntegerLiteralToIntptr()
intptr_t v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::ConstexprIntegerLiteralToIntptr (const IntegerLiteral & i) [inline]
Definition at line 47 of file runtime-macro-shims.h.
                                                                         {
  return i.To<intptr_t>();
}
IntPtrAdd()
intptr_t v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::IntPtrAdd (intptr_t a, intptr_t b) [inline]
Definition at line 25 of file runtime-macro-shims.h.
{ return a + b; }
Referenced by v8::internal::compiler::MemoryLowering::AlignToAllocationAlignment(), v8::internal::CodeStubAssembler::CheckForCapacityGrow(), v8::internal::CodeStubAssembler::ElementOffsetFromIndex(), v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER(), v8::internal::CodeStubAssembler::InitializeFieldsWithRoot(), v8::internal::compiler::CodeAssembler::IntPtrAdd(), v8::internal::CodeStubAssembler::LoadPropertyFromFastObject(), v8::internal::compiler::CodeAssembler::RawPtrAdd(), v8::internal::CodeStubAssembler::StoreElementTypedArrayBigInt(), v8::internal::TF_BUILTIN(), v8::internal::CodeStubAssembler::TrapAllocationMemento(), and v8::internal::compiler::CodeAssembler::UintPtrAdd().
IntPtrLessThan()
bool v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::IntPtrLessThan (intptr_t a, intptr_t b) [inline]
Definition at line 27 of file runtime-macro-shims.h.
{ return a < b; }
Referenced by v8::internal::CollectionsBuiltinsAssembler::AddToOrderedHashTable(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::ArgumentsLength(), v8::internal::CodeStubAssembler::BigInt64Comparison(), v8::internal::CodeStubAssembler::BigIntFromInt32Pair(), v8::internal::CodeStubAssembler::CheckForCapacityGrow(), v8::internal::WeakCollectionsBuiltinsAssembler::Coefficient(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::ConvertJSPrimitiveToUntaggedOrDeopt(), v8::internal::wasm::TurboshaftGraphBuildingInterface::DataViewBoundsCheck(), v8::internal::wasm::TurboshaftGraphBuildingInterface::DataViewRangeCheck(), v8::internal::AccessorAssembler::EmitElementLoad(), v8::internal::AccessorAssembler::ExtendPropertiesBackingStore(), v8::internal::ArrayIncludesIndexofAssembler::GenerateHoleyDoubles(), v8::internal::ArrayIncludesIndexofAssembler::GeneratePackedDoubles(), v8::internal::StringBuiltinsAssembler::GenerateSeqStringRelationalComparison(), v8::internal::ArrayIncludesIndexofAssembler::GenerateSmiOrObject(), v8::internal::AccessorAssembler::GenericElementLoad(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerCase(), v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER(), v8::internal::WriteBarrierCodeStubAssembler::LoadBucket(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::LoadFieldByIndex(), v8::internal::StringBuiltinsAssembler::LoadSurrogatePairAt(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::LoadSurrogatePairAt(), v8::internal::CodeStubAssembler::MoveElements(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal_Batched(), v8::internal::RegExpBuiltinsAssembler::RegExpPrototypeSplitBody(), v8::internal::GrowableFixedArray::Reserve(), v8::internal::MicrotaskQueueBuiltinsAssembler::RewindEnteredContext(), v8::internal::CodeStubAssembler::SmiFromUint32(), v8::internal::StringBuiltinsAssembler::SubString(), v8::internal::TF_BUILTIN(), v8::internal::CodeStubAssembler::TryLookupElement(), and v8::internal::CodeStubAssembler::TryToName().
IntPtrLessThanOrEqual()
bool v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::IntPtrLessThanOrEqual (intptr_t a, intptr_t b) [inline]
Definition at line 28 of file runtime-macro-shims.h.
{ return a <= b; }
Referenced by v8::internal::StringBuiltinsAssembler::AllocAndCopyStringCharacters(), v8::internal::CodeStubAssembler::AllocateByteArray(), v8::internal::CodeStubAssembler::AllocateOrderedHashTableWithCapacity(), v8::internal::WeakCollectionsBuiltinsAssembler::AllocateTable(), v8::internal::CodeStubAssembler::BigInt64Comparison(), v8::internal::CodeStubAssembler::CopyElements(), v8::internal::CodeStubAssembler::FillFixedArrayWithSmiZero(), v8::internal::CodeStubAssembler::FillFixedDoubleArrayWithZero(), v8::internal::ArrayIncludesIndexofAssembler::Generate(), v8::internal::CodeStubAssembler::InitializePropertyArrayLength(), v8::internal::CodeStubAssembler::IntPtrMin(), v8::internal::CodeStubAssembler::IsOffsetInBounds(), v8::internal::FeedbackCollectorReducer< Next >::IsOffsetInBounds(), v8::internal::CodeStubAssembler::MoveElements(), v8::internal::MicrotaskQueueBuiltinsAssembler::RewindEnteredContext(), v8::internal::WeakCollectionsBuiltinsAssembler::ShouldShrink(), and v8::internal::TF_BUILTIN().
IntPtrMul()
intptr_t v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::IntPtrMul (intptr_t a, intptr_t b) [inline]
Definition at line 26 of file runtime-macro-shims.h.
{ return a * b; }
Referenced by v8::internal::compiler::CodeAssembler::IntPtrMul().
Print()
void v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::Print (const char * str) [inline]
Definition at line 51 of file runtime-macro-shims.h.
{ PrintF("%s", str); }
References v8::internal::PrintF().
Signed()
intptr_t v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::Signed (uintptr_t u) [inline]
Definition at line 29 of file runtime-macro-shims.h.
{ return static_cast<intptr_t>(u); }
SmiUntag()
template<typename Smi >
int32_t v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::SmiUntag (Smi s) [inline]
Definition at line 31 of file runtime-macro-shims.h.
                               {
  return s.value();
}
Referenced by v8::internal::Builtins::Generate_CallFunction(), v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_ContinueToBuiltinHelper(), v8::internal::Generate_InterpreterEnterBytecode(), v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_PushBoundArguments(), v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER(), v8::internal::anonymous_namespace{builtins-riscv.cc}::NewImplicitReceiver(), v8::internal::anonymous_namespace{builtins-riscv.cc}::OnStackReplacement(), v8::internal::CodeStubAssembler::ParameterToIntPtr(), v8::internal::MacroAssembler::SmiToInt32(), v8::internal::CodeStubAssembler::SmiToIntPtr(), v8::internal::MacroAssembler::SmiUntag(), v8::internal::MacroAssembler::SmiUntagField(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::TableSize(), v8::internal::TF_BUILTIN(), and v8::internal::CodeStubAssembler::TryToIntptr().
UintPtrLessThan()
bool v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::UintPtrLessThan (uintptr_t a, uintptr_t b) [inline]
Definition at line 34 of file runtime-macro-shims.h.
{ return a < b; }
Referenced by v8::internal::RegExpBuiltinsAssembler::AdvanceStringIndex(), v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::Allocate(), v8::internal::wasm::TurboshaftGraphBuildingInterface::AsmjsLoadMem(), v8::internal::wasm::TurboshaftGraphBuildingInterface::AsmjsStoreMem(), v8::internal::detail::BuiltinArgumentsTS< Assembler >::AtIndex(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BoundsCheckMem(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildIndirectCallTargetAndImplicitArg(), v8::internal::CodeStubAssembler::ChangeUintPtrToTagged(), v8::internal::CodeStubAssembler::CheckForCapacityGrow(), v8::internal::RegExpBuiltinsAssembler::ConstructNewResultFromMatchInfo(), v8::internal::SharedArrayBufferBuiltinsAssembler::DebugCheckAtomicIndex(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::DoubleArrayMinMax(), v8::internal::AccessorAssembler::EmitElementLoad(), v8::internal::CodeStubAssembler::EmitElementStore(), v8::internal::CodeStubAssembler::EmitElementStoreTypedArray(), v8::internal::AccessorAssembler::EmitFastElementsBoundsCheck(), v8::internal::KeyedStoreGenericAssembler::EmitGenericElementStore(), v8::internal::interpreter::InterpreterAssembler::ExportParametersAndRegisterFile(), v8::internal::AccessorAssembler::ExtendPropertiesBackingStore(), v8::internal::CodeStubAssembler::FillFixedArrayWithSmiZero(), v8::internal::CodeStubAssembler::FillFixedDoubleArrayWithZero(), v8::internal::CollectionsBuiltinsAssembler::FindOrderedHashTableEntry(), v8::internal::CodeStubAssembler::FixedArrayBoundsCheck(), v8::internal::ArrayIncludesIndexofAssembler::GenerateHoleyDoubles(), v8::internal::ArrayIncludesIndexofAssembler::GeneratePackedDoubles(), v8::internal::ArrayIncludesIndexofAssembler::GenerateSmiOrObject(), v8::internal::AccessorAssembler::GenericElementLoad(), v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER(), v8::internal::interpreter::InterpreterAssembler::ImportRegisterFile(), v8::internal::CodeStubAssembler::LoadCachedMap(), v8::internal::CodeStubAssembler::LoadPropertyFromFastObject(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::NewArray(), v8::internal::AccessorAssembler::OverwriteExistingFastDataProperty(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::AccessorAssembler::StoreJSSharedStructField(), v8::internal::CodeStubAssembler::StoreSandboxedPointerToObject(), v8::internal::CodeStubAssembler::StringCharCodeAt(), v8::internal::CodeStubAssembler::SwissNameDictionarySetCtrl(), v8::internal::wasm::TurboshaftGraphBuildingInterface::TableGet(), v8::internal::TF_BUILTIN(), v8::internal::CodeStubAssembler::TryLookupElement(), and v8::internal::SharedArrayBufferBuiltinsAssembler::ValidateAtomicAccess().
Unsigned()
uint32_t v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::Unsigned (int32_t s) [inline]
Definition at line 35 of file runtime-macro-shims.h.
{ return static_cast<uint32_t>(s); }
Word32Equal()
bool v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::Word32Equal (uint32_t a, uint32_t b) [inline]
Definition at line 39 of file runtime-macro-shims.h.
{ return a == b; }
Referenced by v8::internal::interpreter::IntrinsicsGenerator::AbortIfArgCountMismatch(), v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::AdaptFastCallArgument(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::AnyConvertExtern(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayCopy(), v8::internal::CodeStubAssembler::BigIntToRawBytes(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::BinOpImpl(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BinOpImpl(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BoundsCheckMem(), v8::internal::CodeStubAssembler::BranchIfMaybeSpecialIndex(), v8::internal::CodeStubAssembler::BranchIfSameNumberValue(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BrOnCastFailImpl(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTable(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildCcallConvertFloat(), v8::internal::compiler::WasmGraphAssembler::BuildDecodeSandboxedExternalPointer(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildDiv64Call(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildIndirectCallTargetAndImplicitArg(), v8::internal::wasm::WasmGraphBuilderBase::BuildModifyThreadInWasmFlagHelper(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::BuildUint32Mod(), v8::internal::CodeStubAssembler::CallGetterIfAccessor(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallIndirect(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::ChangeOrDeopt(), v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::Checked(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::CheckEqualsInternalizedString(), v8::internal::compiler::JSGraphAssembler::CheckIfTypedArrayWasDetachedOrOutOfBounds(), v8::internal::compiler::turboshaft::TurbolevEarlyLoweringReducer< Next >::CheckInstanceType(), v8::internal::CodeStubAssembler::CollectFeedbackForString(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Comparison(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::ConvertHeapObjectToFloat64OrDeopt(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::ConvertUntaggedToJSPrimitive(), v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::DecodeExternalPointer(), v8::internal::compiler::SimplifiedLowering::DoOrderedNumberToBit(), v8::internal::CodeStubAssembler::ElementsKindEqual(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ExtractTruncationProjections(), v8::internal::CodeStubAssembler::FindNonDefaultConstructor(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::FindOrderedHashEntry(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::Float64Is(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::Float64SameValue(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::GenerateStringEqualBuiltinCall(), v8::internal::compiler::RepresentationChanger::GetBitRepresentationFor(), v8::internal::wasm::TurboshaftGraphBuildingInterface::GetCodeUnitImpl(), v8::internal::compiler::turboshaft::TurbolevEarlyLoweringReducer< Next >::HasInPrototypeChain(), v8::internal::compiler::WasmGraphAssembler::HasInstanceType(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::HasInstanceType(), v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER(), v8::internal::BuiltinsReducer< Next >::InstanceTypeEqual(), v8::internal::compiler::SimplifiedLowering::Int32Div(), v8::internal::CodeStubAssembler::IsAllSetWord32(), v8::internal::CodeStubAssembler::IsBothEqualInWord32(), v8::internal::CodeStubAssembler::IsClearWord32(), v8::internal::CodeStubAssembler::IsEqualInWord32(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::IsNonZero(), v8::internal::CodeStubAssembler::IsNotSetWord32(), v8::internal::compiler::WasmGraphAssembler::IsSmi(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::IsSmi(), v8::internal::compiler::turboshaft::StackCheckLoweringReducer< Next >::JSStackCheck(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::LoadFieldByIndex(), v8::internal::CodeStubAssembler::LoadPropertyFromFastObject(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::LoadSurrogatePairAt(), v8::internal::CodeStubAssembler::Lookup(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerClz(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerCtz(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::NewConsString(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::ObjectIs(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceBranchCondition(), v8::internal::compiler::turboshaft::GrowableStacksReducer< Next >::Return(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ReturnCallIndirect(), v8::internal::anonymous_namespace{builtins-internal-gen.cc}::SetOrCopyDataPropertiesAssembler::SetOrCopyDataProperties(), v8::internal::FeedbackCollectorReducer< Next >::SmiEqual(), v8::internal::CodeStubAssembler::StoreElementTypedArrayWord32(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::StringAsWtf16(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::StringAt(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StringCodePointAt(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StringEqImpl(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::StringOrOddballStrictEqual(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::StringPrepareForGetCodeUnit(), v8::internal::wasm::TurboshaftGraphBuildingInterface::TableGet(), v8::internal::compiler::MachineOperatorBuilder::TaggedEqual(), v8::internal::compiler::GraphAssembler::TaggedEqual(), v8::internal::CodeStubAssembler::TaggedEqual(), v8::internal::TF_BUILTIN(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::TransitionAndStoreArrayElement(), v8::internal::compiler::turboshaft::WasmJSLoweringReducer< Next >::TrapIf(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::TruncateJSPrimitiveToUntagged(), v8::internal::CodeStubAssembler::Typeof(), v8::internal::compiler::SimplifiedLowering::Uint32Div(), v8::internal::compiler::SimplifiedLowering::Uint32Mod(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::UnOpImpl(), v8::internal::wasm::TurboshaftGraphBuildingInterface::UnOpImpl(), v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::WasmTypeCheck(), v8::internal::wasm::TurboshaftGraphBuildingInterface::WellKnown_FastApi(), v8::internal::compiler::RawMachineAssembler::Word32BinaryNot(), v8::internal::compiler::RawMachineAssembler::Word32Equal(), v8::internal::compiler::CodeAssembler::Word32Equal(), v8::internal::compiler::RawMachineAssembler::Word32NotEqual(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordBinop(), and v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::WordBinopDeoptOnOverflow().
Word32NotEqual()
bool v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::Word32NotEqual (uint32_t a, uint32_t b) [inline]
Definition at line 40 of file runtime-macro-shims.h.
{ return a != b; }
Referenced by v8::internal::CodeStubAssembler::Equal(), v8::internal::CodeStubAssembler::FindNonDefaultConstructor(), v8::internal::CodeStubAssembler::ForInPrepare(), v8::internal::CodeStubAssembler::GotoIfHasContextExtensionUpToDepth(), v8::internal::CodeStubAssembler::IsSetWord32(), v8::internal::CodeStubAssembler::LoadExternalStringResourceDataPtr(), v8::internal::CodeStubAssembler::LoadPropertyFromFastObject(), v8::internal::CodeStubAssembler::LoadRuntimeFlag(), and v8::internal::TF_BUILTIN().