v8::internal::anonymous_namespace{read-only-spaces.cc} Namespace Reference
Classes
class ReadOnlySpaceObjectIterator
Functions
constexpr int ReadOnlyAreaSize ()
Function Documentation
ReadOnlyAreaSize()
constexpr int v8::internal::anonymous_namespace{read-only-spaces.cc}::ReadOnlyAreaSize () [inline], [constexpr]
Definition at line 360 of file read-only-spaces.cc.
                                        {
  return static_cast<int>(
      MemoryChunkLayout::AllocatableMemoryInMemoryChunk(RO_SPACE));
}
References v8::internal::MemoryChunkLayout::AllocatableMemoryInMemoryChunk(), and v8::internal::RO_SPACE.
Referenced by v8::internal::ReadOnlySpace::AllocateNextPage(), v8::internal::ReadOnlySpace::AllocateNextPageAt(), and v8::internal::ReadOnlySpace::EnsureSpaceForAllocation().