v8::internal::anonymous_namespace{regexp-ast.cc} Namespace Reference
Classes
class RegExpUnparser
Functions
Interval ListCaptureRegisters (ZoneList< RegExpTree * > *children)
int IncreaseBy (int previous, int increase)
Function Documentation
IncreaseBy()
int v8::internal::anonymous_namespace{regexp-ast.cc}::IncreaseBy (int previous, int increase)
Definition at line 365 of file regexp-ast.cc.
                                           {
  if (RegExpTree::kInfinity - previous < increase) {
    return RegExpTree::kInfinity;
  } else {
    return previous + increase;
  }
}
References v8::internal::RegExpTree::kInfinity.
Referenced by v8::internal::RegExpAlternative::RegExpAlternative().
ListCaptureRegisters()
Interval v8::internal::anonymous_namespace{regexp-ast.cc}::ListCaptureRegisters (ZoneList< RegExpTree * > * children)
Definition at line 34 of file regexp-ast.cc.
                                                               {
  Interval result = Interval::Empty();
  for (int i = 0; i < children->length(); i++)
    result = result.Union(children->at(i)->CaptureRegisters());
  return result;
}
References v8::internal::ZoneList< T >::at(), v8::internal::Interval::Empty(), v8::internal::ZoneList< T >::length(), and v8::base::internal::result.
Referenced by v8::internal::RegExpDisjunction::CaptureRegisters(), and v8::internal::RegExpAlternative::CaptureRegisters().