v8::internal::anonymous_namespace{runtime-forin.cc} Namespace Reference
Functions
MaybeDirectHandle< HeapObject > Enumerate (Isolate *isolate, DirectHandle< JSReceiver > receiver)
MaybeDirectHandle< Object > HasEnumerableProperty (Isolate *isolate, DirectHandle< JSReceiver > receiver, DirectHandle< Object > key)
Function Documentation
Enumerate()
MaybeDirectHandle<HeapObject> v8::internal::anonymous_namespace{runtime-forin.cc}::Enumerate (Isolate * isolate, DirectHandle< JSReceiver > receiver)
Definition at line 21 of file runtime-forin.cc.
                                                                           {
  JSObject::MakePrototypesFast(receiver, kStartAtReceiver, isolate);
  FastKeyAccumulator accumulator(isolate, receiver,
                                 KeyCollectionMode::kIncludePrototypes,
                                 ENUMERABLE_STRINGS, true);
  // Test if we have an enum cache for {receiver}.
  if (!accumulator.is_receiver_simple_enum()) {
    DirectHandle<FixedArray> keys;
    ASSIGN_RETURN_ON_EXCEPTION(
        isolate, keys,
        accumulator.GetKeys(accumulator.may_have_elements()
                                ? GetKeysConversion::kConvertToString
                                : GetKeysConversion::kNoNumbers));
    // Test again, since cache may have been built by GetKeys() calls above.
    if (!accumulator.is_receiver_simple_enum()) return keys;
  }
  DCHECK(!IsJSModuleNamespace(*receiver));
  return direct_handle(receiver->map(), isolate);
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::ENUMERABLE_STRINGS, v8::internal::FastKeyAccumulator::GetKeys(), v8::internal::FastKeyAccumulator::is_receiver_simple_enum(), v8::internal::kConvertToString, v8::internal::kIncludePrototypes, v8::internal::kNoNumbers, v8::internal::kStartAtReceiver, v8::internal::JSObject::MakePrototypesFast(), and v8::internal::FastKeyAccumulator::may_have_elements().
Referenced by v8::internal::RUNTIME_FUNCTION().
HasEnumerableProperty()
MaybeDirectHandle<Object> v8::internal::anonymous_namespace{runtime-forin.cc}::HasEnumerableProperty (Isolate * isolate, DirectHandle< JSReceiver > receiver, DirectHandle< Object > key)
Definition at line 44 of file runtime-forin.cc.
                              {
  bool success = false;
  Maybe<PropertyAttributes> result = Just(ABSENT);
  PropertyKey lookup_key(isolate, key, &success);
  if (!success) return isolate->factory()->undefined_value();
  LookupIterator it(isolate, receiver, lookup_key);
  for (;; it.Next()) {
    switch (it.state()) {
      case LookupIterator::TRANSITION:
        UNREACHABLE();
      case LookupIterator::JSPROXY: {
        // For proxies we have to invoke the [[GetOwnProperty]] trap.
        result = JSProxy::GetPropertyAttributes(&it);
        if (result.IsNothing()) return MaybeDirectHandle<Object>();
        if (result.FromJust() == ABSENT) {
          // Continue lookup on the proxy's prototype.
          DirectHandle<JSProxy> proxy = it.GetHolder<JSProxy>();
          DirectHandle<Object> prototype;
          ASSIGN_RETURN_ON_EXCEPTION(isolate, prototype,
                                     JSProxy::GetPrototype(proxy));
          if (IsNull(*prototype, isolate)) {
            return isolate->factory()->undefined_value();
          }
          // We already have a stack-check in JSProxy::GetPrototype.
          return HasEnumerableProperty(isolate, Cast<JSReceiver>(prototype),
                                       key);
        } else if (result.FromJust() & DONT_ENUM) {
          return isolate->factory()->undefined_value();
        } else {
          return it.GetName();
        }
      }
      case LookupIterator::STRING_LOOKUP_START_OBJECT:
        UNREACHABLE();
      case LookupIterator::WASM_OBJECT:
        continue; // Continue to the prototype, if present.
      case LookupIterator::INTERCEPTOR: {
        result = JSObject::GetPropertyAttributesWithInterceptor(&it);
        if (result.IsNothing()) return MaybeDirectHandle<Object>();
        if (result.FromJust() != ABSENT) return it.GetName();
        continue;
      }
      case LookupIterator::ACCESS_CHECK: {
        if (it.HasAccess()) continue;
        result = JSObject::GetPropertyAttributesWithFailedAccessCheck(&it);
        if (result.IsNothing()) return MaybeDirectHandle<Object>();
        if (result.FromJust() != ABSENT) return it.GetName();
        return isolate->factory()->undefined_value();
      }
      case LookupIterator::TYPED_ARRAY_INDEX_NOT_FOUND:
        // TypedArray out-of-bounds access.
        return isolate->factory()->undefined_value();
      case LookupIterator::ACCESSOR: {
        if (IsJSModuleNamespace(*it.GetHolder<Object>())) {
          result = JSModuleNamespace::GetPropertyAttributes(&it);
          if (result.IsNothing()) return MaybeDirectHandle<Object>();
          DCHECK_EQ(0, result.FromJust() & DONT_ENUM);
        }
        return it.GetName();
      }
      case LookupIterator::DATA:
        return it.GetName();
      case LookupIterator::NOT_FOUND:
        return isolate->factory()->undefined_value();
    }
    UNREACHABLE();
  }
}
References v8::internal::ABSENT, v8::internal::LookupIterator::ACCESS_CHECK, v8::internal::LookupIterator::ACCESSOR, ASSIGN_RETURN_ON_EXCEPTION, v8::internal::LookupIterator::DATA, DCHECK_EQ, v8::internal::DONT_ENUM, v8::internal::Isolate::factory(), v8::internal::LookupIterator::GetHolder(), v8::internal::LookupIterator::GetName(), v8::internal::JSProxy::GetPropertyAttributes(), v8::internal::JSModuleNamespace::GetPropertyAttributes(), v8::internal::JSObject::GetPropertyAttributesWithFailedAccessCheck(), v8::internal::JSObject::GetPropertyAttributesWithInterceptor(), v8::internal::JSProxy::GetPrototype(), v8::internal::LookupIterator::HasAccess(), v8::internal::LookupIterator::INTERCEPTOR, v8::internal::IsNull(), v8::internal::LookupIterator::JSPROXY, v8::Just(), v8::internal::key, v8::internal::LookupIterator::Next(), v8::internal::LookupIterator::NOT_FOUND, v8::internal::prototype, v8::base::internal::result, v8::internal::LookupIterator::state(), v8::internal::LookupIterator::STRING_LOOKUP_START_OBJECT, v8::internal::LookupIterator::TRANSITION, v8::internal::LookupIterator::TYPED_ARRAY_INDEX_NOT_FOUND, v8::internal::UNREACHABLE(), and v8::internal::LookupIterator::WASM_OBJECT.
Referenced by v8::internal::RUNTIME_FUNCTION().