v8::internal::wasm::fuzzing Namespace Reference
Namespaces
 anonymous_namespace{random-module-generation.cc}
Functions
base::Vector< uint8_t > GenerateRandomWasmModule (Zone *zone, WasmModuleGenerationOptions options, base::Vector< const uint8_t > data)
base::Vector< uint8_t > GenerateWasmModuleForInitExpressions (Zone *zone, base::Vector< const uint8_t > data, size_t *count)
base::Vector< uint8_t > GenerateWasmModuleForDeopt (Zone *zone, base::Vector< const uint8_t > data, std::vector< std::string > &callees, std::vector< std::string > &inlinees)
base::Vector< uint8_t > GenerateWasmModuleForRevec (Zone *zone, base::Vector< const uint8_t > data)
Function Documentation
GenerateRandomWasmModule()
base::Vector<uint8_t> v8::internal::wasm::fuzzing::GenerateRandomWasmModule (Zone * zone, WasmModuleGenerationOptions options, base::Vector< const uint8_t > data)
Definition at line 4345 of file random-module-generation.cc.
                                    {
  WasmModuleBuilder builder(zone);
  // Split input data in two parts:
  // - One for the "module" (types, globals, ..)
  // - One for all the function bodies
  // This prevents using a too large portion on the module resulting in
  // uninteresting function bodies.
  DataRange module_range(data);
  DataRange functions_range = module_range.split();
  std::vector<ModuleTypeIndex> function_signatures;
  // At least 1 function is needed.
  int max_num_functions = MaxNumOfFunctions();
  CHECK_GE(max_num_functions, 1);
  uint8_t num_functions = 1 + (module_range.get<uint8_t>() % max_num_functions);
  // In case of WasmGC expressions:
  // Add struct and array types first so that we get a chance to generate
  // these types in function signatures.
  // Currently, `BodyGen` assumes this order for struct/array/signature
  // definitions.
  // Otherwise, for non-WasmGC we can't use structs/arrays.
  uint8_t num_structs = 0;
  uint8_t num_arrays = 0;
  std::vector<ModuleTypeIndex> array_types;
  std::vector<ModuleTypeIndex> struct_types;
  // In case of WasmGC expressions:
  // We always add two default array types with mutable i8 and i16 elements,
  // respectively.
  constexpr uint8_t kNumDefaultArrayTypesForWasmGC = 2;
  if (options.generate_wasm_gc()) {
    // We need at least one struct and one array in order to support
    // WasmInitExpr for abstract types.
    num_structs = 1 + module_range.get<uint8_t>() % kMaxStructs;
    num_arrays = kNumDefaultArrayTypesForWasmGC +
                 module_range.get<uint8_t>() % kMaxArrays;
  }
  uint8_t num_signatures = num_functions;
  ModuleGen gen_module(zone, options, &builder, &module_range, num_functions,
                       num_structs, num_arrays, num_signatures);
  // Add random number of memories.
  // TODO(v8:14674): Add a mode without declaring any memory or memory
  // instructions.
  gen_module.GenerateRandomMemories();
  uint8_t current_type_index = 0;
  // In case of WasmGC expressions, we create recursive groups for the recursive
  // types.
  std::map<uint8_t, uint8_t> explicit_rec_groups;
  if (options.generate_wasm_gc()) {
    // Put the types into random recursive groups.
    explicit_rec_groups = gen_module.GenerateRandomRecursiveGroups(
        kNumDefaultArrayTypesForWasmGC);
    // Add default array types.
    static constexpr ModuleTypeIndex kArrayI8{0};
    static constexpr ModuleTypeIndex kArrayI16{1};
    {
      ArrayType* a8 = zone->New<ArrayType>(kWasmI8, 1);
      CHECK_EQ(kArrayI8, builder.AddArrayType(a8, true, kNoSuperType));
      array_types.push_back(kArrayI8);
      ArrayType* a16 = zone->New<ArrayType>(kWasmI16, 1);
      CHECK_EQ(kArrayI16, builder.AddArrayType(a16, true, kNoSuperType));
      array_types.push_back(kArrayI16);
    }
    static_assert(kNumDefaultArrayTypesForWasmGC == kArrayI16.index + 1);
    current_type_index = kNumDefaultArrayTypesForWasmGC;
    // Add randomly generated structs.
    gen_module.GenerateRandomStructs(explicit_rec_groups, struct_types,
                                     current_type_index,
                                     kNumDefaultArrayTypesForWasmGC);
    DCHECK_EQ(current_type_index, kNumDefaultArrayTypesForWasmGC + num_structs);
    // Add randomly generated arrays.
    gen_module.GenerateRandomArrays(explicit_rec_groups, array_types,
                                    current_type_index);
    DCHECK_EQ(current_type_index, num_structs + num_arrays);
  }
  // We keep the signature for the first (main) function constant.
  constexpr bool kIsFinal = true;
  auto kMainFnSig = FixedSizeSignature<ValueType>::Returns(kWasmI32).Params(
      kWasmI32, kWasmI32, kWasmI32);
  function_signatures.push_back(
      builder.ForceAddSignature(&kMainFnSig, kIsFinal));
  current_type_index++;
  // Add randomly generated signatures.
  gen_module.GenerateRandomFunctionSigs(
      explicit_rec_groups, function_signatures, current_type_index, kIsFinal);
  DCHECK_EQ(current_type_index, num_functions + num_structs + num_arrays);
  // Add exceptions.
  int num_exceptions = 1 + (module_range.get<uint8_t>() % kMaxExceptions);
  gen_module.GenerateRandomExceptions(num_exceptions);
  // In case of WasmGC expressions:
  // Add the "wasm:js-string" imports to the module. They may or may not be
  // used later, but they'll always be available.
  StringImports strings = options.generate_wasm_gc()
                              ? gen_module.AddImportedStringImports()
                              : StringImports();
  // Generate function declarations before tables. This will be needed once we
  // have typed-function tables.
  std::vector<WasmFunctionBuilder*> functions;
  functions.reserve(num_functions);
  for (uint8_t i = 0; i < num_functions; i++) {
    // If we are using wasm-gc, we cannot allow signature normalization
    // performed by adding a function by {FunctionSig}, because we emit
    // everything in one recursive group which blocks signature
    // canonicalization.
    // TODO(14034): Relax this when we implement proper recursive-group
    // support.
    functions.push_back(builder.AddFunction(function_signatures[i]));
  }
  // Generate tables before function bodies, so they are available for table
  // operations. Generate tables before the globals, so tables don't
  // accidentally use globals in their initializer expressions.
  // Always generate at least one table for call_indirect.
  gen_module.GenerateRandomTables(array_types, struct_types);
  // Add globals.
  auto [globals, mutable_globals] =
      gen_module.GenerateRandomGlobals(array_types, struct_types);
  // Add passive data segments.
  int num_data_segments = module_range.get<uint8_t>() % kMaxPassiveDataSegments;
  for (int i = 0; i < num_data_segments; i++) {
    GeneratePassiveDataSegment(&module_range, &builder);
  }
  // Generate function bodies.
  for (int i = 0; i < num_functions; ++i) {
    WasmFunctionBuilder* f = functions[i];
    // On the last function don't split the DataRange but just use the
    // existing DataRange.
    DataRange function_range = i != num_functions - 1
                                   ? functions_range.split()
                                   : std::move(functions_range);
    BodyGen gen_body(options, f, function_signatures, globals, mutable_globals,
                     struct_types, array_types, strings, &function_range);
    const FunctionSig* sig = f->signature();
    base::Vector<const ValueType> return_types(sig->returns().begin(),
                                               sig->return_count());
    gen_body.InitializeNonDefaultableLocals(&function_range);
    gen_body.Generate(return_types, &function_range);
    f->Emit(kExprEnd);
    if (i == 0) builder.AddExport(base::CStrVector("main"), f);
  }
  ZoneBuffer buffer{zone};
  builder.WriteTo(&buffer);
  return base::VectorOf(buffer);
}
References v8::internal::wasm::WasmModuleBuilder::AddArrayType(), v8::internal::wasm::WasmModuleBuilder::AddExport(), v8::internal::wasm::WasmModuleBuilder::AddFunction(), CHECK_EQ, CHECK_GE, v8::base::CStrVector(), DCHECK_EQ, v8::internal::wasm::WasmFunctionBuilder::Emit(), v8::internal::wasm::WasmModuleBuilder::ForceAddSignature(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GeneratePassiveDataSegment(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kMaxArrays, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kMaxExceptions, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kMaxPassiveDataSegments, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kMaxStructs, v8::internal::wasm::kNoSuperType, v8::internal::wasm::kWasmI16, v8::internal::wasm::kWasmI32, v8::internal::wasm::kWasmI8, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::MaxNumOfFunctions(), v8::internal::Zone::New(), v8::internal::FixedSizeSignature< T, kNumReturns, kNumParams >::Returns(), v8::internal::sig, v8::internal::wasm::WasmFunctionBuilder::signature(), v8::base::VectorOf(), and v8::internal::wasm::WasmModuleBuilder::WriteTo().
GenerateWasmModuleForDeopt()
base::Vector<uint8_t> v8::internal::wasm::fuzzing::GenerateWasmModuleForDeopt (Zone * zone, base::Vector< const uint8_t > data, std::vector< std::string > & callees, std::vector< std::string > & inlinees)
Definition at line 4780 of file random-module-generation.cc.
                                                                   {
  // Don't limit the features for the deopt fuzzer.
  constexpr WasmModuleGenerationOptions options =
      WasmModuleGenerationOptions::All();
  WasmModuleBuilder builder(zone);
  DataRange range(data);
  std::vector<ModuleTypeIndex> function_signatures;
  std::vector<ModuleTypeIndex> array_types;
  std::vector<ModuleTypeIndex> struct_types;
  const int kMaxCallTargets = 5;
  const int kMaxInlinees = 3;
  // We need at least 2 call targets to be able to trigger a deopt.
  const int num_call_targets = 2 + range.get<uint8_t>() % (kMaxCallTargets - 1);
  const int num_inlinees = range.get<uint8_t>() % (kMaxInlinees + 1);
  // 1 main function + x inlinees + x callees.
  uint8_t num_functions = 1 + num_inlinees + num_call_targets;
  // 1 signature for all the callees, 1 signature for the main function +
  // 1 signature per inlinee.
  uint8_t num_signatures = 2 + num_inlinees;
  uint8_t num_structs = 1 + range.get<uint8_t>() % kMaxStructs;
  // In case of WasmGC expressions:
  // We always add two default array types with mutable i8 and i16 elements,
  // respectively.
  constexpr uint8_t kNumDefaultArrayTypesForWasmGC = 2;
  uint8_t num_arrays =
      range.get<uint8_t>() % kMaxArrays + kNumDefaultArrayTypesForWasmGC;
  // Just ignoring user-defined signature types in the signatures.
  uint16_t num_types = num_structs + num_arrays;
  uint8_t current_type_index = kNumDefaultArrayTypesForWasmGC;
  // Add random-generated types.
  ModuleGen gen_module(zone, options, &builder, &range, num_functions,
                       num_structs, num_arrays, num_signatures);
  gen_module.GenerateRandomMemories();
  std::map<uint8_t, uint8_t> explicit_rec_groups =
      gen_module.GenerateRandomRecursiveGroups(kNumDefaultArrayTypesForWasmGC);
  // Add default array types.
  static constexpr ModuleTypeIndex kArrayI8{0};
  static constexpr ModuleTypeIndex kArrayI16{1};
  {
    ArrayType* a8 = zone->New<ArrayType>(kWasmI8, true);
    CHECK_EQ(kArrayI8, builder.AddArrayType(a8, true, kNoSuperType));
    array_types.push_back(kArrayI8);
    ArrayType* a16 = zone->New<ArrayType>(kWasmI16, true);
    CHECK_EQ(kArrayI16, builder.AddArrayType(a16, true, kNoSuperType));
    array_types.push_back(kArrayI16);
  }
  static_assert(kNumDefaultArrayTypesForWasmGC == kArrayI16.index + 1);
  gen_module.GenerateRandomStructs(explicit_rec_groups, struct_types,
                                   current_type_index,
                                   kNumDefaultArrayTypesForWasmGC);
  DCHECK_EQ(current_type_index, kNumDefaultArrayTypesForWasmGC + num_structs);
  gen_module.GenerateRandomArrays(explicit_rec_groups, array_types,
                                  current_type_index);
  DCHECK_EQ(current_type_index, num_structs + num_arrays);
  // Create signature for call target.
  std::vector<ValueType> return_types =
      GenerateTypes(options, &range, num_types);
  constexpr bool kIsFinal = true;
  const FunctionSig* target_sig = CreateSignature(
      builder.zone(), base::VectorOf(GenerateTypes(options, &range, num_types)),
      base::VectorOf(return_types));
  ModuleTypeIndex target_sig_index =
      builder.ForceAddSignature(target_sig, kIsFinal);
  function_signatures.reserve(num_call_targets);
  for (int i = 0; i < num_call_targets; ++i) {
    // Simplification: All call targets of a call_ref / call_indirect have the
    // same signature.
    function_signatures.push_back(target_sig_index);
  }
  // Create signatures for inlinees.
  // Use the same return types with a certain chance. This increases the chance
  // to emit return calls.
  uint8_t use_same_return = range.get<uint8_t>();
  for (int i = 0; i < num_inlinees; ++i) {
    if ((use_same_return & (1 << i)) == 0) {
      return_types = GenerateTypes(options, &range, num_types);
    }
    const FunctionSig* inlinee_sig = CreateSignature(
        builder.zone(),
        base::VectorOf(GenerateTypes(options, &range, num_types)),
        base::VectorOf(return_types));
    function_signatures.push_back(
        builder.ForceAddSignature(inlinee_sig, kIsFinal));
  }
  // Create signature for main function.
  const FunctionSig* main_sig =
      CreateSignature(builder.zone(), base::VectorOf({ValueType{kWasmI32}}),
                      base::VectorOf({ValueType{kWasmI32}}));
  function_signatures.push_back(builder.ForceAddSignature(main_sig, kIsFinal));
  DCHECK_EQ(function_signatures.back().index,
            num_structs + num_arrays + num_signatures - 1);
  // This needs to be done after the signatures are added.
  int num_exceptions = 1 + range.get<uint8_t>() % kMaxExceptions;
  gen_module.GenerateRandomExceptions(num_exceptions);
  StringImports strings = gen_module.AddImportedStringImports();
  // Add functions to module.
  std::vector<WasmFunctionBuilder*> functions;
  DCHECK_EQ(num_functions, function_signatures.size());
  functions.reserve(num_functions);
  for (uint8_t i = 0; i < num_functions; i++) {
    functions.push_back(builder.AddFunction(function_signatures[i]));
  }
  uint32_t num_entries = num_call_targets + num_inlinees;
  bool use_table64 = range.get<bool>();
  AddressType address_type =
      use_table64 ? AddressType::kI64 : AddressType::kI32;
  uint32_t table_index =
      builder.AddTable(kWasmFuncRef, num_entries, num_entries, address_type);
  WasmModuleBuilder::WasmElemSegment segment(
      zone, kWasmFuncRef, table_index,
      use_table64 ? WasmInitExpr(int64_t{0}) : WasmInitExpr(0));
  for (uint32_t i = 0; i < num_entries; i++) {
    segment.entries.emplace_back(
        WasmModuleBuilder::WasmElemSegment::Entry::kRefFuncEntry,
        builder.NumImportedFunctions() + i);
  }
  builder.AddElementSegment(std::move(segment));
  gen_module.GenerateRandomTables(array_types, struct_types);
  // Create global for call target index.
  // Simplification: This global is used to specify the call target at the deopt
  // point instead of passing the call target around dynamically.
  uint32_t global_index =
      builder.AddExportedGlobal(kWasmI32, true, WasmInitExpr(0),
                                base::StaticCharVector("call_target_index"));
  // Create inlinee bodies.
  for (int i = 0; i < num_inlinees; ++i) {
    uint32_t declared_func_index = i + num_call_targets;
    WasmFunctionBuilder* f = functions[declared_func_index];
    DataRange function_range = range.split();
    BodyGen gen_body(options, f, function_signatures, {}, {}, struct_types,
                     array_types, strings, &function_range);
    gen_body.InitializeNonDefaultableLocals(&function_range);
    if (i == 0) {
      // For the inner-most inlinee, emit the deopt point (e.g. a call_ref).
      EmitDeoptAndReturnValues(gen_body, f, target_sig, target_sig_index,
                               global_index, table_index, use_table64,
                               &function_range);
    } else {
      // All other inlinees call the previous inlinee.
      uint32_t callee_declared_index = declared_func_index - 1;
      EmitCallAndReturnValues(gen_body, f, functions[callee_declared_index],
                              table_index, use_table64, &function_range);
    }
    f->Emit(kExprEnd);
    auto buffer = zone->AllocateVector<char>(32);
    size_t len = base::SNPrintF(buffer, "inlinee_%i", i);
    builder.AddExport({buffer.begin(), len}, f);
    inlinees.emplace_back(buffer.begin(), len);
  }
  // Create main function body.
  {
    uint32_t declared_func_index = num_functions - 1;
    WasmFunctionBuilder* f = functions[declared_func_index];
    DataRange function_range = range.split();
    BodyGen gen_body(options, f, function_signatures, {}, {}, struct_types,
                     array_types, strings, &function_range);
    gen_body.InitializeNonDefaultableLocals(&function_range);
    // Store the call target
    f->EmitWithU32V(kExprLocalGet, 0);
    f->EmitWithU32V(kExprGlobalSet, 0);
    // Call inlinee or emit deopt.
    if (num_inlinees == 0) {
      // If we don't have any inlinees, directly emit the deopt point.
      EmitDeoptAndReturnValues(gen_body, f, target_sig, target_sig_index,
                               global_index, table_index, use_table64,
                               &function_range);
    } else {
      // Otherwise call the "outer-most" inlinee.
      uint32_t callee_declared_index = declared_func_index - 1;
      EmitCallAndReturnValues(gen_body, f, functions[callee_declared_index],
                              table_index, use_table64, &function_range);
    }
    f->Emit(kExprEnd);
    builder.AddExport(base::StaticCharVector("main"), f);
  }
  // Create call target bodies.
  // This is done last as we care much less about the content of these
  // functions, so it's less of an issue if there aren't (m)any random bytes
  // left.
  for (int i = 0; i < num_call_targets; ++i) {
    WasmFunctionBuilder* f = functions[i];
    DataRange function_range = range.split();
    BodyGen gen_body(options, f, function_signatures, {}, {}, struct_types,
                     array_types, strings, &function_range);
    const FunctionSig* sig = f->signature();
    base::Vector<const ValueType> target_return_types(sig->returns().begin(),
                                                      sig->return_count());
    gen_body.InitializeNonDefaultableLocals(&function_range);
    gen_body.Generate(target_return_types, &function_range);
    f->Emit(kExprEnd);
    auto buffer = zone->AllocateVector<char>(32);
    size_t len = base::SNPrintF(buffer, "callee_%i", i);
    builder.AddExport({buffer.begin(), len}, f);
    callees.emplace_back(buffer.begin(), len);
  }
  ZoneBuffer buffer{zone};
  builder.WriteTo(&buffer);
  return base::VectorOf(buffer);
}
References v8::internal::wasm::WasmModuleBuilder::AddArrayType(), CHECK_EQ, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::CreateSignature(), DCHECK_EQ, v8::internal::wasm::WasmModuleBuilder::ForceAddSignature(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateTypes(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kMaxArrays, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kMaxStructs, v8::internal::wasm::kNoSuperType, v8::internal::wasm::kWasmI16, v8::internal::wasm::kWasmI8, v8::internal::Zone::New(), v8::base::VectorOf(), and v8::internal::wasm::WasmModuleBuilder::zone().
GenerateWasmModuleForInitExpressions()
base::Vector<uint8_t> v8::internal::wasm::fuzzing::GenerateWasmModuleForInitExpressions (Zone * zone, base::Vector< const uint8_t > data, size_t * count)
Definition at line 4510 of file random-module-generation.cc.
                                                               {
  // Don't limit expressions for the initializer expression fuzzer.
  constexpr WasmModuleGenerationOptions options =
      WasmModuleGenerationOptions::All();
  WasmModuleBuilder builder(zone);
  DataRange module_range(data);
  std::vector<ModuleTypeIndex> function_signatures;
  std::vector<ModuleTypeIndex> array_types;
  std::vector<ModuleTypeIndex> struct_types;
  int num_globals = 1 + module_range.get<uint8_t>() % (kMaxGlobals + 1);
  uint8_t num_functions = num_globals;
  *count = num_functions;
  // We need at least one struct and one array in order to support
  // WasmInitExpr for abstract types.
  uint8_t num_structs = 1 + module_range.get<uint8_t>() % kMaxStructs;
  uint8_t num_arrays = 1 + module_range.get<uint8_t>() % kMaxArrays;
  uint16_t num_types = num_functions + num_structs + num_arrays;
  uint8_t current_type_index = 0;
  // Add random-generated types.
  uint8_t last_struct_type = current_type_index + num_structs;
  for (; current_type_index < last_struct_type; current_type_index++) {
    ModuleTypeIndex supertype = kNoSuperType;
    uint8_t num_fields = module_range.get<uint8_t>() % (kMaxStructFields + 1);
    uint32_t existing_struct_types = current_type_index;
    if (existing_struct_types > 0 && module_range.get<bool>()) {
      supertype =
          ModuleTypeIndex{module_range.get<uint8_t>() % existing_struct_types};
      num_fields += builder.GetStructType(supertype)->field_count();
    }
    // TODO(403372470): Add support for custom descriptors.
    // TODO(42204563): Add support for shared structs.
    StructType::Builder struct_builder(zone, num_fields, false, false);
    // Add all fields from super type.
    uint32_t field_index = 0;
    if (supertype != kNoSuperType) {
      const StructType* parent = builder.GetStructType(supertype);
      for (; field_index < parent->field_count(); ++field_index) {
        struct_builder.AddField(parent->field(field_index),
                                parent->mutability(field_index));
      }
    }
    for (; field_index < num_fields; field_index++) {
      ValueType type = GetValueTypeHelper(
          options, &module_range, current_type_index, current_type_index,
          kIncludeNumericTypes, kIncludePackedTypes, kExcludeSomeGenerics);
      // To prevent huge initializer expressions, limit the existence of
      // non-nullable references to the first 2 struct types (for non-inherited
      // fields).
      if (current_type_index >= 2 && type.is_non_nullable()) {
        type = type.AsNullable();
      }
      bool mutability = module_range.get<bool>();
      struct_builder.AddField(type, mutability);
    }
    StructType* struct_fuz = struct_builder.Build();
    ModuleTypeIndex index = builder.AddStructType(struct_fuz, false, supertype);
    struct_types.push_back(index);
  }
  for (; current_type_index < num_structs + num_arrays; current_type_index++) {
    ValueType type = GetValueTypeHelper(
        options, &module_range, current_type_index, current_type_index,
        kIncludeNumericTypes, kIncludePackedTypes, kExcludeSomeGenerics);
    ModuleTypeIndex supertype = kNoSuperType;
    if (current_type_index > last_struct_type && module_range.get<bool>()) {
      uint32_t existing_array_types = current_type_index - last_struct_type;
      supertype =
          ModuleTypeIndex{last_struct_type +
                          (module_range.get<uint8_t>() % existing_array_types)};
      type = builder.GetArrayType(supertype)->element_type();
    }
    ArrayType* array_fuz = zone->New<ArrayType>(type, true);
    ModuleTypeIndex index = builder.AddArrayType(array_fuz, false, supertype);
    array_types.push_back(index);
  }
  // Choose global types and create function signatures.
  constexpr bool kIsFinal = true;
  std::vector<ValueType> globals;
  for (; current_type_index < num_types; current_type_index++) {
    ValueType return_type = GetValueTypeHelper(
        options, &module_range, num_types - num_globals,
        num_types - num_globals, kIncludeNumericTypes, kExcludePackedTypes,
        kIncludeAllGenerics, kExcludeS128);
    globals.push_back(return_type);
    // Create a new function signature for each global. These functions will be
    // used to compare against the initializer value of the global.
    FunctionSig::Builder sig_builder(zone, 1, 0);
    sig_builder.AddReturn(return_type);
    ModuleTypeIndex signature_index =
        builder.ForceAddSignature(sig_builder.Get(), kIsFinal);
    function_signatures.push_back(signature_index);
  }
  std::vector<WasmFunctionBuilder*> functions;
  functions.reserve(num_functions);
  for (uint8_t i = 0; i < num_functions; i++) {
    functions.push_back(builder.AddFunction(function_signatures[i]));
  }
  // Create globals.
  std::vector<uint8_t> mutable_globals;
  std::vector<WasmInitExpr> init_exprs;
  init_exprs.reserve(num_globals);
  mutable_globals.reserve(num_globals);
  CHECK_EQ(globals.size(), num_globals);
  uint64_t mutabilities = module_range.get<uint64_t>();
  for (int i = 0; i < num_globals; ++i) {
    ValueType type = globals[i];
    // 50% of globals are immutable.
    const bool mutability = mutabilities & 1;
    mutabilities >>= 1;
    WasmInitExpr init_expr = GenerateInitExpr(
        zone, module_range, &builder, type, struct_types, array_types, 0);
    init_exprs.push_back(init_expr);
    auto buffer = zone->AllocateVector<char>(8);
    size_t len = base::SNPrintF(buffer, "g%i", i);
    builder.AddExportedGlobal(type, mutability, init_expr,
                              {buffer.begin(), len});
    if (mutability) mutable_globals.push_back(static_cast<uint8_t>(i));
  }
  // Create functions containing the initializer of each global as its function
  // body.
  for (int i = 0; i < num_functions; ++i) {
    WasmFunctionBuilder* f = functions[i];
    f->EmitFromInitializerExpression(init_exprs[i]);
    auto buffer = zone->AllocateVector<char>(8);
    size_t len = base::SNPrintF(buffer, "f%i", i);
    builder.AddExport({buffer.begin(), len}, f);
  }
  ZoneBuffer buffer{zone};
  builder.WriteTo(&buffer);
  return base::VectorOf(buffer);
}
References v8::internal::wasm::WasmModuleBuilder::AddArrayType(), v8::internal::wasm::WasmModuleBuilder::AddExport(), v8::internal::wasm::WasmModuleBuilder::AddExportedGlobal(), v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::AddField(), v8::internal::wasm::WasmModuleBuilder::AddFunction(), v8::internal::SignatureBuilder< SigT, T >::AddReturn(), v8::internal::wasm::WasmModuleBuilder::AddStructType(), v8::internal::Zone::AllocateVector(), v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::Build(), CHECK_EQ, v8::internal::wasm::ArrayType::element_type(), v8::internal::wasm::WasmFunctionBuilder::EmitFromInitializerExpression(), v8::internal::wasm::StructType::field(), v8::internal::wasm::StructTypeBase::field_count(), v8::internal::wasm::WasmModuleBuilder::ForceAddSignature(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateInitExpr(), v8::internal::SignatureBuilder< SigT, T >::Get(), v8::internal::wasm::WasmModuleBuilder::GetArrayType(), v8::internal::wasm::WasmModuleBuilder::GetStructType(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GetValueTypeHelper(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kExcludePackedTypes, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kExcludeS128, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kExcludeSomeGenerics, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kIncludeAllGenerics, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kIncludeNumericTypes, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kIncludePackedTypes, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kMaxArrays, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kMaxGlobals, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kMaxStructFields, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kMaxStructs, v8::internal::wasm::kNoSuperType, v8::internal::wasm::StructTypeBase::mutability(), v8::internal::Zone::New(), v8::base::SNPrintF(), v8::internal::tracing::type, v8::base::VectorOf(), and v8::internal::wasm::WasmModuleBuilder::WriteTo().
GenerateWasmModuleForRevec()
base::Vector<uint8_t> v8::internal::wasm::fuzzing::GenerateWasmModuleForRevec (Zone * zone, base::Vector< const uint8_t > data)
Definition at line 5006 of file random-module-generation.cc.
                                                {
  constexpr WasmModuleGenerationOptions options = {
      {WasmModuleGenerationOption::kGenerateSIMD}};
  WasmModuleBuilder builder(zone);
  // Split input data in two parts:
  // - One for the "module" (types, globals, ..)
  // - One for all the function bodies
  // This prevents using a too large portion on the module resulting in
  // uninteresting function bodies.
  DataRange module_range(data);
  DataRange functions_range = module_range.split();
  std::vector<ModuleTypeIndex> function_signatures;
  // At least 1 function is needed.
  int max_num_functions = MaxNumOfFunctions();
  CHECK_GE(max_num_functions, 1);
  uint8_t num_functions = 1 + (module_range.get<uint8_t>() % max_num_functions);
  constexpr uint8_t kNumStructs = 0;
  constexpr uint8_t kNumArrays = 0;
  constexpr uint16_t kNumTypes = kNumStructs + kNumArrays;
  std::vector<ModuleTypeIndex> array_types;
  std::vector<ModuleTypeIndex> struct_types;
  uint8_t num_signatures = num_functions;
  ModuleGen gen_module(zone, options, &builder, &module_range, num_functions,
                       kNumStructs, kNumArrays, num_signatures);
  gen_module.GenerateRandomMemories();
  // We keep the signature for the first (main) function constant.
  constexpr bool kIsFinal = true;
  auto kMainFnSig = FixedSizeSignature<ValueType>::Returns(kWasmI32).Params(
      kWasmI32, kWasmI32, kWasmI32);
  function_signatures.push_back(
      builder.ForceAddSignature(&kMainFnSig, kIsFinal));
  // Other function signatures: return void with random params.
  constexpr base::Vector<const ValueType> kNoReturnType;
  for (int i = 1; i < num_signatures; ++i) {
    const FunctionSig* function_sig = CreateSignature(
        builder.zone(),
        base::VectorOf(GenerateTypes(options, &module_range, kNumTypes)),
        kNoReturnType);
    function_signatures.push_back(
        builder.ForceAddSignature(function_sig, kIsFinal));
  }
  // Add exceptions.
  int num_exceptions = 1 + (module_range.get<uint8_t>() % kMaxExceptions);
  gen_module.GenerateRandomExceptions(num_exceptions);
  StringImports strings = StringImports();
  // Generate function declarations before tables. This will be needed once we
  // have typed-function tables.
  std::vector<WasmFunctionBuilder*> functions;
  functions.reserve(num_functions);
  for (uint8_t i = 0; i < num_functions; i++) {
    functions.push_back(builder.AddFunction(function_signatures[i]));
  }
  gen_module.GenerateRandomTables(array_types, struct_types);
  // Add globals.
  auto [globals, mutable_globals] =
      gen_module.GenerateRandomGlobals(array_types, struct_types);
  // Add passive data segments.
  int num_data_segments = module_range.get<uint8_t>() % kMaxPassiveDataSegments;
  for (int i = 0; i < num_data_segments; i++) {
    GeneratePassiveDataSegment(&module_range, &builder);
  }
  // Generate function bodies.
  // Revec uses two contiguous S128Store instructions as seeds, the two
  // instructions share the same memory_index/alignment/index, the values to be
  // stored should be generated from the same DataRange. The second offset is 16
  // bytes larger than the first offset.
  for (int i = 0; i < num_functions; ++i) {
    WasmFunctionBuilder* f = functions[i];
    // On the last function don't split the DataRange but just use the
    // existing DataRange.
    DataRange function_range = i != num_functions - 1
                                   ? functions_range.split()
                                   : std::move(functions_range);
    BodyGen gen_body(options, f, function_signatures, globals, mutable_globals,
                     struct_types, array_types, strings, &function_range);
    const FunctionSig* sig = f->signature();
    base::Vector<const ValueType> return_types(sig->returns().begin(),
                                               sig->return_count());
    gen_body.InitializeNonDefaultableLocals(&function_range);
    // Atomic operations need to be aligned exactly to their max alignment.
    const uint8_t align = function_range.getPseudoRandom<uint8_t>() % (4 + 1);
    // Only memory0 is supported in revec for now.
    constexpr uint8_t kMemoryIndex0 = 0;
    uint64_t offset = function_range.get<uint16_t>();
    // With a 1/256 chance generate potentially very large offsets.
    if ((offset & 0xff) == 0xff) {
      offset = f->builder()->IsMemory64(kMemoryIndex0)
                   ? function_range.getPseudoRandom<uint64_t>() & 0x1ffffffff
                   : function_range.getPseudoRandom<uint32_t>();
    }
    auto first_data = function_range.split();
    // === The first store. ===
    // Generate the index.
    uint32_t index;
    if (f->builder()->IsMemory64(kMemoryIndex0)) {
      index = f->AddLocal(kWasmI64);
      gen_body.Generate<kI64>(&first_data);
    } else {
      index = f->AddLocal(kWasmI32);
      gen_body.Generate<kI32>(&first_data);
    }
    f->EmitTeeLocal(index);
    // Generate the S128 value to be stored.
    // With 50% chance generated from the same sequence.
    DataRange store2_range = function_range.get<bool>()
                                 ? function_range.clone()
                                 : function_range.split();
    gen_body.Generate<kS128>(&function_range);
    // Format of the instruction (supports multi-memory):
    // memory_op (align | 0x40) memory_index offset
    f->EmitWithPrefix(kExprS128StoreMem);
    f->EmitU32V(align | 0x40);
    f->EmitU32V(kMemoryIndex0);
    f->EmitU64V(offset);
    // === The second store. ===
    // Share the same index, value generated from same
    // DataRange and offset is 16 larger.
    f->EmitGetLocal(index);
    gen_body.Generate<kS128>(&store2_range);
    f->EmitWithPrefix(kExprS128StoreMem);
    f->EmitU32V(align | 0x40);
    f->EmitU32V(kMemoryIndex0);
    uint64_t offset2;
    // offset + 16 shouldn't exceed the 32-bit range.
    if (!f->builder()->IsMemory64(kMemoryIndex0) &&
        offset + 16 >= std::numeric_limits<uint32_t>::max()) {
      offset2 = offset - 16;
    } else {
      offset2 = offset + 16;
    }
    f->EmitU64V(offset2);
    // int32_t main(int32_t, int32_t, int32_t)
    // S128 a = load(index + offset)
    // S128 b = load(index + offset2)
    // S128 c = a ^ b
    // return lane(c, 0) ^ lane(c, 1) ^ lane(c, 2) ^ lane(c, 3)
    if (i == 0) {
      // a = load(index + offset)
      f->EmitGetLocal(index);
      f->EmitWithPrefix(kExprS128LoadMem);
      f->EmitU32V(align | 0x40);
      f->EmitU32V(kMemoryIndex0);
      f->EmitU64V(offset);
      // b = load(index + offset2)
      f->EmitGetLocal(index);
      f->EmitWithPrefix(kExprS128LoadMem);
      f->EmitU32V(align | 0x40);
      f->EmitU32V(kMemoryIndex0);
      f->EmitU64V(offset2);
      // c = a ^ b
      f->EmitWithPrefix(kExprS128Xor);
      uint32_t xor_result = f->AddLocal(kWasmS128);
      f->EmitTeeLocal(xor_result);
      f->EmitWithPrefix(kExprI32x4ExtractLane);
      f->EmitByte(0);
      f->EmitGetLocal(xor_result);
      f->EmitWithPrefix(kExprI32x4ExtractLane);
      f->EmitByte(1);
      // lane(c, 0) ^ lane(c, 1)
      f->Emit(kExprI32Xor);
      f->EmitGetLocal(xor_result);
      f->EmitWithPrefix(kExprI32x4ExtractLane);
      f->EmitByte(2);
      f->EmitGetLocal(xor_result);
      f->EmitWithPrefix(kExprI32x4ExtractLane);
      f->EmitByte(3);
      // lane(c, 2) ^ lane(c, 3)
      f->Emit(kExprI32Xor);
      // lane(c, 0) ^ lane(c, 1) ^ lane(c, 2) ^ lane(c, 3)
      f->Emit(kExprI32Xor);
    }
    f->Emit(kExprEnd);
    if (i == 0) builder.AddExport(base::CStrVector("main"), f);
  }
  ZoneBuffer buffer{zone};
  builder.WriteTo(&buffer);
  return base::VectorOf(buffer);
}
References v8::internal::wasm::WasmModuleBuilder::AddExport(), v8::internal::wasm::WasmModuleBuilder::AddFunction(), v8::internal::wasm::WasmFunctionBuilder::AddLocal(), v8::internal::wasm::WasmFunctionBuilder::builder(), CHECK_GE, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::CreateSignature(), v8::base::CStrVector(), v8::internal::wasm::WasmFunctionBuilder::Emit(), v8::internal::wasm::WasmFunctionBuilder::EmitByte(), v8::internal::wasm::WasmFunctionBuilder::EmitGetLocal(), v8::internal::wasm::WasmFunctionBuilder::EmitTeeLocal(), v8::internal::wasm::WasmFunctionBuilder::EmitU32V(), v8::internal::wasm::WasmFunctionBuilder::EmitU64V(), v8::internal::wasm::WasmFunctionBuilder::EmitWithPrefix(), v8::internal::wasm::WasmModuleBuilder::ForceAddSignature(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GeneratePassiveDataSegment(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateTypes(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::wasm::WasmModuleBuilder::IsMemory64(), v8::internal::kI32, v8::internal::kI64, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kMaxExceptions, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kMaxPassiveDataSegments, v8::internal::kNumTypes, v8::internal::kS128, v8::internal::wasm::kWasmI32, v8::internal::wasm::kWasmI64, v8::internal::wasm::kWasmS128, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::MaxNumOfFunctions(), v8::internal::FixedSizeSignature< T, kNumReturns, kNumParams >::Params(), v8::internal::sig, v8::internal::wasm::WasmFunctionBuilder::signature(), v8::base::VectorOf(), v8::internal::wasm::WasmModuleBuilder::WriteTo(), and v8::internal::wasm::WasmModuleBuilder::zone().