v8::internal::anonymous_namespace{ic.cc} Namespace Reference
Enumerations
enum KeyType { kIntPtr
, kName
, kBailout
 }
enum class FastCloneObjectMode {
kIdenticalMap
, kEmptyObject
, kDifferentMap
, kNotSupported
,
kMaybeSupported
 }
Functions
const char * GetModifier (KeyedAccessLoadMode mode)
const char * GetModifier (KeyedAccessStoreMode mode)
bool MigrateDeprecated (Isolate *isolate, DirectHandle< Object > object)
bool AddOneReceiverMapIfMissing (MapHandles *receiver_maps, Handle< Map > new_receiver_map)
bool AddOneReceiverMapIfMissing (MapsAndHandlers *receiver_maps_and_handlers, Handle< Map > new_receiver_map)
DirectHandle< NativeContext > GetAccessorContext (const CallOptimization &call_optimization, Tagged< Map > holder_map, Isolate *isolate)
bool AllowConvertHoleElementToUndefined (Isolate *isolate, DirectHandle< Map > receiver_map)
bool IsOutOfBoundsAccess (DirectHandle< Object > receiver, size_t index)
bool AllowReadingHoleElement (ElementsKind elements_kind)
KeyedAccessLoadMode GetNewKeyedLoadMode (Isolate *isolate, DirectHandle< HeapObject > receiver, size_t index, bool is_found, MaybeDirectHandle< Object > result)
KeyedAccessLoadMode GetUpdatedLoadModeForMap (Isolate *isolate, DirectHandle< Map > map, KeyedAccessLoadMode load_mode)
KeyType TryConvertKey (Handle< Object > key, Isolate *isolate, intptr_t *index_out, Handle< Name > *name_out)
bool IntPtrKeyToSize (intptr_t index, DirectHandle< HeapObject > receiver, size_t *out)
bool CanCache (DirectHandle< Object > receiver, InlineCacheState state)
Maybe< bool > DefineOwnDataProperty (LookupIterator *it, LookupIterator::State original_state, DirectHandle< JSAny > value, Maybe< ShouldThrow > should_throw, StoreOrigin store_origin)
bool MayHaveTypedArrayInPrototypeChain (Isolate *isolate, DirectHandle< JSObject > object)
KeyedAccessStoreMode GetStoreMode (DirectHandle< JSObject > receiver, size_t index)
Maybe< bool > StoreOwnElement (Isolate *isolate, DirectHandle< JSArray > array, Handle< Object > index, DirectHandle< Object > value)
FastCloneObjectMode GetCloneModeForMapPreCheck (DirectHandle< Map > map, bool null_proto_literal, Isolate *isolate)
FastCloneObjectMode GetCloneModeForMap (DirectHandle< Map > map, bool null_proto_literal, Isolate *isolate)
bool CanCacheCloneTargetMapTransition (DirectHandle< Map > source_map, std::optional< DirectHandle< Map >> target_map, bool null_proto_literal, Isolate *isolate)
bool CanFastCloneObjectToObjectLiteral (DirectHandle< Map > source_map, DirectHandle< Map > target_map, DirectHandle< Map > override_map, bool null_proto_literal, Isolate *isolate)
template<SideStepTransition::Kind kind>
Tagged< Object > GetCloneTargetMap (Isolate *isolate, DirectHandle< Map > source_map, DirectHandle< Map > override_map)
template<SideStepTransition::Kind kind>
void SetCloneTargetMap (Isolate *isolate, DirectHandle< Map > source_map, DirectHandle< Map > new_target_map, DirectHandle< Map > override_map)
template<SideStepTransition::Kind kind>
void SetCloneTargetMapUnsupported (Isolate *isolate, DirectHandle< Map > source_map, DirectHandle< Map > override_map)
bool MaybeCanCloneObjectForObjectAssign (DirectHandle< JSReceiver > source, DirectHandle< Map > source_map, DirectHandle< JSReceiver > target, Isolate *isolate)
Enumeration Type Documentation
FastCloneObjectMode
enum v8::internal::anonymous_namespace{ic.cc}::FastCloneObjectMode [strong]
Enumerator
kIdenticalMap
kEmptyObject
kDifferentMap
kNotSupported
kMaybeSupported
Definition at line 3280 of file ic.cc.
                               {
  // The clone has the same map as the input.
  kIdenticalMap,
  // The clone is the empty object literal.
  kEmptyObject,
  // The clone has an empty object literal map.
  kDifferentMap,
  // The source map is to complicated to handle.
  kNotSupported,
  // Returned by PreCheck
  kMaybeSupported
};
KeyType
enum v8::internal::anonymous_namespace{ic.cc}::KeyType
Enumerator
kIntPtr
kName
kBailout
Definition at line 1494 of file ic.cc.
{ kIntPtr, kName, kBailout };
Function Documentation
AddOneReceiverMapIfMissing() [1/2]
bool v8::internal::anonymous_namespace{ic.cc}::AddOneReceiverMapIfMissing (MapHandles * receiver_maps, Handle< Map > new_receiver_map)
Definition at line 514 of file ic.cc.
                                                              {
  DCHECK(!new_receiver_map.is_null());
  for (DirectHandle<Map> map : *receiver_maps) {
    if (!map.is_null() && map.is_identical_to(new_receiver_map)) {
      return false;
    }
  }
  receiver_maps->push_back(new_receiver_map);
  return true;
}
References v8::internal::DCHECK(), v8::internal::HandleBase::is_null(), and v8::internal::DirectHandleSmallVector< T, kSize >::push_back().
AddOneReceiverMapIfMissing() [2/2]
bool v8::internal::anonymous_namespace{ic.cc}::AddOneReceiverMapIfMissing (MapsAndHandlers * receiver_maps_and_handlers, Handle< Map > new_receiver_map)
Definition at line 526 of file ic.cc.
                                                              {
  DCHECK(!new_receiver_map.is_null());
  if (new_receiver_map->is_deprecated()) return false;
  for (DirectHandle<Map> map : receiver_maps_and_handlers->maps()) {
    if (!map.is_null() && map.is_identical_to(new_receiver_map)) {
      return false;
    }
  }
  receiver_maps_and_handlers->emplace_back(new_receiver_map, {});
  return true;
}
References v8::internal::DCHECK(), v8::internal::MapsAndHandlers::emplace_back(), v8::internal::HandleBase::is_null(), and v8::internal::MapsAndHandlers::maps().
Referenced by v8::internal::KeyedLoadIC::UpdateLoadElement(), and v8::internal::KeyedStoreIC::UpdateStoreElement().
AllowConvertHoleElementToUndefined()
bool v8::internal::anonymous_namespace{ic.cc}::AllowConvertHoleElementToUndefined (Isolate * isolate, DirectHandle< Map > receiver_map)
Definition at line 1262 of file ic.cc.
                                                                        {
  if (IsJSTypedArrayMap(*receiver_map)) {
    // For JSTypedArray we never lookup elements in the prototype chain.
    return true;
  }
  // For other {receiver}s we need to check the "no elements" protector.
  if (Protectors::IsNoElementsIntact(isolate)) {
    if (IsStringMap(*receiver_map)) {
      return true;
    }
    if (IsJSObjectMap(*receiver_map)) {
      // For other JSObjects (including JSArrays) we can only continue if
      // the {receiver}s prototype is either the initial Object.prototype
      // or the initial Array.prototype, which are both guarded by the
      // "no elements" protector checked above.
      DirectHandle<HeapObject> receiver_prototype(receiver_map->prototype(),
                                                  isolate);
      InstanceType prototype_type = receiver_prototype->map()->instance_type();
      if (prototype_type == JS_OBJECT_PROTOTYPE_TYPE ||
          (prototype_type == JS_ARRAY_TYPE &&
           isolate->IsInCreationContext(
               Cast<JSObject>(*receiver_prototype),
               Context::INITIAL_ARRAY_PROTOTYPE_INDEX))) {
        return true;
      }
    }
  }
  return false;
}
References v8::internal::Isolate::IsInCreationContext().
Referenced by GetNewKeyedLoadMode(), GetUpdatedLoadModeForMap(), and v8::internal::KeyedLoadIC::LoadElementHandler().
AllowReadingHoleElement()
bool v8::internal::anonymous_namespace{ic.cc}::AllowReadingHoleElement (ElementsKind elements_kind)
Definition at line 1311 of file ic.cc.
                                                         {
  return IsHoleyElementsKind(elements_kind);
}
References v8::internal::IsHoleyElementsKind().
Referenced by GetNewKeyedLoadMode(), GetUpdatedLoadModeForMap(), and v8::internal::KeyedLoadIC::LoadElementHandler().
CanCache()
bool v8::internal::anonymous_namespace{ic.cc}::CanCache (DirectHandle< Object > receiver, InlineCacheState state)
Definition at line 1561 of file ic.cc.
                                                                     {
  if (!v8_flags.use_ic || state == NO_FEEDBACK) return false;
  if (!IsJSReceiver(*receiver) && !IsString(*receiver)) return false;
  return !IsAccessCheckNeeded(*receiver) && !IsJSPrimitiveWrapper(*receiver);
}
References v8::internal::NO_FEEDBACK, and v8::internal::v8_flags.
Referenced by v8::internal::KeyedLoadIC::Load().
CanCacheCloneTargetMapTransition()
bool v8::internal::anonymous_namespace{ic.cc}::CanCacheCloneTargetMapTransition (DirectHandle< Map > source_map, std::optional< DirectHandle< Map >> target_map, bool null_proto_literal, Isolate * isolate)
Definition at line 3368 of file ic.cc.
                                               {
  if (!v8_flags.clone_object_sidestep_transitions || null_proto_literal) {
    return false;
  }
  // As of now any R/O source object should end up in the kEmptyObject case, but
  // there is not really a way of ensuring it. Thus, we also check it below.
  // This is a performance dcheck. If it fails, the clone IC does not handle a
  // case it probably could.
  // TODO(olivf): Either remove that dcheck or move it to GetCloneModeForMap.
  DCHECK(!HeapLayout::InReadOnlySpace(*source_map));
  if (HeapLayout::InReadOnlySpace(*source_map) || source_map->is_deprecated() ||
      source_map->is_prototype_map()) {
    return false;
  }
  if (!target_map) {
    return true;
  }
  CHECK(!HeapLayout::InReadOnlySpace(**target_map));
  return !(*target_map)->is_deprecated();
}
References CHECK, v8::internal::DCHECK(), v8::internal::HeapLayout::InReadOnlySpace(), and v8::internal::v8_flags.
Referenced by CanFastCloneObjectToObjectLiteral(), v8::internal::RUNTIME_FUNCTION(), SetCloneTargetMap(), and SetCloneTargetMapUnsupported().
CanFastCloneObjectToObjectLiteral()
bool v8::internal::anonymous_namespace{ic.cc}::CanFastCloneObjectToObjectLiteral (DirectHandle< Map > source_map, DirectHandle< Map > target_map, DirectHandle< Map > override_map, bool null_proto_literal, Isolate * isolate)
Definition at line 3396 of file ic.cc.
                                                         {
  DisallowGarbageCollection no_gc;
  DCHECK(!target_map->is_deprecated());
  DCHECK(source_map->OnlyHasSimpleProperties());
  DCHECK(!source_map->IsInobjectSlackTrackingInProgress());
  DCHECK(!target_map->IsInobjectSlackTrackingInProgress());
  DCHECK_EQ(*target_map->map(), *source_map->map());
  DCHECK_EQ(target_map->GetConstructor(), *isolate->object_function());
  DCHECK_IMPLIES(
      !null_proto_literal,
      *target_map->prototype() == *isolate->object_function_prototype());
  // Ensure source and target have identical binary representation of properties
  // and elements as the IC relies on copying the raw bytes. This also excludes
  // cases with non-enumerable properties or accessors on the source object.
  if (source_map->instance_type() != JS_OBJECT_TYPE ||
      target_map->instance_type() != JS_OBJECT_TYPE ||
      !target_map->OnlyHasSimpleProperties() ||
      !target_map->has_fast_elements()) {
    return false;
  }
  if (!override_map.is_null()) {
    // No cross-context object reuse.
    if (target_map->map() != override_map->map()) {
      return false;
    }
    // In case we want to clone into an existing target object, we must ensure
    // that this existing object has a compatible size. In particular we cannot
    // shrink or grow the already given object. We also exclude a different
    // start offset, since this doesn't allow us to change the object in-place
    // in a GC safe way.
    DCHECK_EQ(*override_map, isolate->object_function()->initial_map());
    DCHECK(override_map->instance_type() == JS_OBJECT_TYPE);
    DCHECK_EQ(override_map->NumberOfOwnDescriptors(), 0);
    DCHECK(!override_map->IsInobjectSlackTrackingInProgress());
    if (override_map->instance_size() != target_map->instance_size() ||
        override_map->GetInObjectPropertiesStartInWords() !=
            target_map->GetInObjectPropertiesStartInWords()) {
      return false;
    }
  }
#ifdef DEBUG
  ElementsKind source_elements_kind = source_map->elements_kind();
  ElementsKind target_elements_kind = target_map->elements_kind();
  DCHECK(IsSmiOrObjectElementsKind(source_elements_kind) ||
         IsAnyNonextensibleElementsKind(source_elements_kind));
  DCHECK(IsSmiOrObjectElementsKind(target_elements_kind));
  DCHECK_IMPLIES(IsHoleyElementsKindForRead(source_elements_kind),
                 IsHoleyElementsKind(target_elements_kind));
#endif // DEBUG
  // There are no transitions between prototype maps.
  if (source_map->is_prototype_map() || target_map->is_prototype_map()) {
    return false;
  }
  // Exclude edge-cases like not copying a __proto__ property.
  if (source_map->NumberOfOwnDescriptors() !=
      target_map->NumberOfOwnDescriptors()) {
    return false;
  }
  // Check that the source inobject properties fit into the target.
  int source_used_inobj_properties = source_map->GetInObjectProperties() -
                                     source_map->UnusedInObjectProperties();
  int target_used_inobj_properties = target_map->GetInObjectProperties() -
                                     target_map->UnusedInObjectProperties();
  if (source_used_inobj_properties != target_used_inobj_properties) {
    return false;
  }
  // The properties backing store must be of the same size as the clone ic again
  // blindly copies it.
  if (source_map->HasOutOfObjectProperties() !=
          target_map->HasOutOfObjectProperties() ||
      (target_map->HasOutOfObjectProperties() &&
       source_map->UnusedPropertyFields() !=
           target_map->UnusedPropertyFields())) {
    return false;
  }
  Tagged<DescriptorArray> descriptors = source_map->instance_descriptors();
  Tagged<DescriptorArray> target_descriptors =
      target_map->instance_descriptors();
  for (InternalIndex i : target_map->IterateOwnDescriptors()) {
    if (descriptors->GetKey(i) != target_descriptors->GetKey(i)) {
      return false;
    }
    PropertyDetails details = descriptors->GetDetails(i);
    PropertyDetails target_details = target_descriptors->GetDetails(i);
    DCHECK_EQ(details.kind(), PropertyKind::kData);
    DCHECK_EQ(target_details.kind(), PropertyKind::kData);
    Tagged<FieldType> type = descriptors->GetFieldType(i);
    Tagged<FieldType> target_type = target_descriptors->GetFieldType(i);
    // This DCHECK rests on the fact that we only clear field types when there
    // are no instances of the host map left. Thus, to enter the clone IC at
    // least one object of the source map needs to be created, which in turn
    // will re-initialize the source maps field type. This is guaranteed to also
    // update the target map through the sidestep transition, unless the target
    // map is deprecated.
    DCHECK(!IsNone(type));
    DCHECK(!IsNone(target_type));
    // With move_prototype_transitions_first enabled field updates don't
    // generalize across prototype transitions, because the transitions happen
    // on root maps (i.e., before any field is added). In other words we cannot
    // rely on changes in the source map propagating to the target map when
    // there is a SetPrototype involved. NB, technically without
    // move_prototype_transitions_first we also don't update field types across
    // prototype transitions, however we preemptively generalize all fields of
    // prototype transition target maps.
    bool prototype_transition_is_shortcutted =
        v8_flags.move_prototype_transitions_first &&
        source_map->prototype() != target_map->prototype();
    if (!prototype_transition_is_shortcutted &&
        CanCacheCloneTargetMapTransition(source_map, target_map,
                                         null_proto_literal, isolate)) {
      if (!details.representation().fits_into(
              target_details.representation()) ||
          (target_details.representation().IsDouble() &&
           details.representation().IsSmi())) {
        return false;
      }
      if (!FieldType::NowIs(type, target_type)) {
        return false;
      }
    } else {
      // In the case we cannot connect the maps in the transition tree (e.g.,
      // the clone also involves a proto transition) we cannot keep track of
      // representation dependencies. We can only allow the most generic target
      // representation. The same goes for field types.
      if (!details.representation().MostGenericInPlaceChange().Equals(
              target_details.representation()) ||
          !IsAny(target_type)) {
        return false;
      }
    }
  }
  return true;
}
References CanCacheCloneTargetMapTransition(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::Representation::Equals(), v8::internal::Representation::fits_into(), v8::internal::DirectHandle< T >::is_null(), v8::internal::IsAny(), v8::internal::IsAnyNonextensibleElementsKind(), v8::internal::Representation::IsDouble(), v8::internal::IsHoleyElementsKind(), v8::internal::IsHoleyElementsKindForRead(), v8::internal::IsNone(), v8::internal::Representation::IsSmi(), v8::internal::IsSmiOrObjectElementsKind(), v8::internal::kData, v8::internal::PropertyDetails::kind(), v8::internal::Representation::MostGenericInPlaceChange(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::FieldType::NowIs(), v8::internal::PropertyDetails::representation(), v8::internal::tracing::type, and v8::internal::v8_flags.
Referenced by GetCloneTargetMap(), and v8::internal::RUNTIME_FUNCTION().
DefineOwnDataProperty()
Maybe<bool> v8::internal::anonymous_namespace{ic.cc}::DefineOwnDataProperty (LookupIterator * it, LookupIterator::State original_state, DirectHandle< JSAny > value, Maybe< ShouldThrow > should_throw, StoreOrigin store_origin)
Definition at line 1794 of file ic.cc.
                                                            {
  // It should not be possible to call DefineOwnDataProperty in a
  // contextual store (indicated by IsJSGlobalObject()).
  DCHECK(!IsJSGlobalObject(*it->GetReceiver(), it->isolate()));
  // Handle special cases that can't be handled by
  // DefineOwnPropertyIgnoreAttributes first.
  switch (it->state()) {
    case LookupIterator::JSPROXY: {
      PropertyDescriptor new_desc;
      new_desc.set_value(value);
      new_desc.set_writable(true);
      new_desc.set_enumerable(true);
      new_desc.set_configurable(true);
      DCHECK_EQ(original_state, LookupIterator::JSPROXY);
      // TODO(joyee): this will start the lookup again. Ideally we should
      // implement something that reuses the existing LookupIterator.
      return JSProxy::DefineOwnProperty(it->isolate(), it->GetHolder<JSProxy>(),
                                        it->GetName(), &new_desc, should_throw);
    }
    case LookupIterator::WASM_OBJECT:
      RETURN_FAILURE(it->isolate(), kThrowOnError,
                     NewTypeError(MessageTemplate::kWasmObjectsAreOpaque));
    // When lazy feedback is disabled, the original state could be different
    // while the object is already prepared for TRANSITION.
    case LookupIterator::TRANSITION: {
      switch (original_state) {
        case LookupIterator::JSPROXY:
        case LookupIterator::WASM_OBJECT:
        case LookupIterator::TRANSITION:
        case LookupIterator::DATA:
        case LookupIterator::INTERCEPTOR:
        case LookupIterator::ACCESSOR:
        case LookupIterator::TYPED_ARRAY_INDEX_NOT_FOUND:
        case LookupIterator::STRING_LOOKUP_START_OBJECT:
          UNREACHABLE();
        case LookupIterator::ACCESS_CHECK: {
          DCHECK(!IsAccessCheckNeeded(*it->GetHolder<JSObject>()));
          [[fallthrough]];
        }
        case LookupIterator::NOT_FOUND:
          return Object::AddDataProperty(it, value, NONE,
                                         Nothing<ShouldThrow>(), store_origin,
                                         EnforceDefineSemantics::kDefine);
      }
    }
    case LookupIterator::ACCESS_CHECK:
    case LookupIterator::NOT_FOUND:
    case LookupIterator::DATA:
    case LookupIterator::ACCESSOR:
    case LookupIterator::INTERCEPTOR:
    case LookupIterator::TYPED_ARRAY_INDEX_NOT_FOUND:
      break;
    case LookupIterator::STRING_LOOKUP_START_OBJECT:
      UNREACHABLE();
  }
  // We need to restart to handle interceptors properly.
  it->Restart();
  return JSObject::DefineOwnPropertyIgnoreAttributes(
      it, value, NONE, should_throw, JSObject::DONT_FORCE_FIELD,
      EnforceDefineSemantics::kDefine, store_origin);
}
References v8::internal::LookupIterator::ACCESS_CHECK, v8::internal::LookupIterator::ACCESSOR, v8::internal::Object::AddDataProperty(), v8::internal::LookupIterator::DATA, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::JSProxy::DefineOwnProperty(), v8::internal::JSObject::DefineOwnPropertyIgnoreAttributes(), v8::internal::JSObject::DONT_FORCE_FIELD, v8::internal::LookupIterator::GetHolder(), v8::internal::LookupIterator::GetName(), v8::internal::LookupIterator::GetReceiver(), v8::internal::LookupIterator::INTERCEPTOR, v8::internal::LookupIterator::isolate(), v8::internal::LookupIterator::JSPROXY, v8::internal::kDefine, v8::internal::kThrowOnError, v8::internal::NONE, v8::internal::LookupIterator::NOT_FOUND, v8::internal::LookupIterator::Restart(), RETURN_FAILURE, v8::internal::PropertyDescriptor::set_configurable(), v8::internal::PropertyDescriptor::set_enumerable(), v8::internal::PropertyDescriptor::set_value(), v8::internal::PropertyDescriptor::set_writable(), v8::internal::LookupIterator::state(), v8::internal::LookupIterator::STRING_LOOKUP_START_OBJECT, v8::internal::LookupIterator::TRANSITION, v8::internal::LookupIterator::TYPED_ARRAY_INDEX_NOT_FOUND, v8::internal::UNREACHABLE(), v8::internal::value, and v8::internal::LookupIterator::WASM_OBJECT.
Referenced by v8::internal::StoreIC::Store().
GetAccessorContext()
DirectHandle<NativeContext> v8::internal::anonymous_namespace{ic.cc}::GetAccessorContext (const CallOptimization & call_optimization, Tagged< Map > holder_map, Isolate * isolate)
Definition at line 539 of file ic.cc.
                      {
  std::optional<Tagged<NativeContext>> maybe_context =
      call_optimization.GetAccessorContext(holder_map);
  // Holders which are remote objects are not expected in the IC system.
  CHECK(maybe_context.has_value());
  return direct_handle(maybe_context.value(), isolate);
}
References CHECK, v8::internal::direct_handle(), and v8::internal::CallOptimization::GetAccessorContext().
Referenced by v8::internal::LoadIC::ComputeHandler(), v8::internal::StoreIC::ComputeHandler(), and v8::internal::IC::UpdateMegaDOMIC().
GetCloneModeForMap()
FastCloneObjectMode v8::internal::anonymous_namespace{ic.cc}::GetCloneModeForMap (DirectHandle< Map > map, bool null_proto_literal, Isolate * isolate)
Definition at line 3323 of file ic.cc.
                                                         {
  FastCloneObjectMode pre_check =
      GetCloneModeForMapPreCheck(map, null_proto_literal, isolate);
  if (pre_check != FastCloneObjectMode::kMaybeSupported) {
    return pre_check;
  }
  // The clone must always start from an object literal map, it must be an
  // instance of the object function, have the default prototype and not be a
  // prototype itself. Only if the source map fits that criterion we can
  // directly use it as the target map.
  FastCloneObjectMode mode =
      map->instance_type() == JS_OBJECT_TYPE &&
              !IsAnyNonextensibleElementsKind(map->elements_kind()) &&
              map->GetConstructor() == *isolate->object_function() &&
              map->prototype() == *isolate->object_function_prototype() &&
              !map->is_prototype_map()
          ? FastCloneObjectMode::kIdenticalMap
          : FastCloneObjectMode::kDifferentMap;
  if (null_proto_literal || IsNull(map->prototype())) {
    mode = FastCloneObjectMode::kDifferentMap;
  }
  Tagged<DescriptorArray> descriptors = map->instance_descriptors();
  for (InternalIndex i : map->IterateOwnDescriptors()) {
    PropertyDetails details = descriptors->GetDetails(i);
    Tagged<Name> key = descriptors->GetKey(i);
    if (details.kind() != PropertyKind::kData || !details.IsEnumerable() ||
        key->IsPrivateName()) {
      return FastCloneObjectMode::kNotSupported;
    }
    if (!details.IsConfigurable() || details.IsReadOnly()) {
      mode = FastCloneObjectMode::kDifferentMap;
    }
  }
  DCHECK_IMPLIES(mode == FastCloneObjectMode::kIdenticalMap,
                 !map->is_prototype_map());
  return mode;
}
References DCHECK_IMPLIES, GetCloneModeForMapPreCheck(), v8::internal::IsAnyNonextensibleElementsKind(), v8::internal::PropertyDetails::IsConfigurable(), v8::internal::PropertyDetails::IsEnumerable(), v8::internal::IsNull(), v8::internal::PropertyDetails::IsReadOnly(), v8::internal::kData, v8::internal::key, v8::internal::PropertyDetails::kind(), and mode().
Referenced by GetCloneTargetMap(), MaybeCanCloneObjectForObjectAssign(), and v8::internal::RUNTIME_FUNCTION().
GetCloneModeForMapPreCheck()
FastCloneObjectMode v8::internal::anonymous_namespace{ic.cc}::GetCloneModeForMapPreCheck (DirectHandle< Map > map, bool null_proto_literal, Isolate * isolate)
Definition at line 3293 of file ic.cc.
                                                                 {
  DisallowGarbageCollection no_gc;
  if (!IsJSObjectMap(*map)) {
    // Everything that produces the empty object literal can be supported since
    // we have a special case for that.
    if (null_proto_literal) return FastCloneObjectMode::kNotSupported;
    return IsNullOrUndefinedMap(*map) || IsBooleanMap(*map) ||
                   IsHeapNumberMap(*map)
               ? FastCloneObjectMode::kEmptyObject
               : FastCloneObjectMode::kNotSupported;
  }
  ElementsKind elements_kind = map->elements_kind();
  if (!IsSmiOrObjectElementsKind(elements_kind) &&
      !IsAnyNonextensibleElementsKind(elements_kind)) {
    return FastCloneObjectMode::kNotSupported;
  }
  if (!map->OnlyHasSimpleProperties()) {
    return FastCloneObjectMode::kNotSupported;
  }
  // TODO(olivf): Think about cases where cross-context copies are safe.
  if (!map->BelongsToSameNativeContextAs(isolate->context())) {
    return FastCloneObjectMode::kNotSupported;
  }
  return FastCloneObjectMode::kMaybeSupported;
}
References v8::internal::Isolate::context(), v8::internal::IsAnyNonextensibleElementsKind(), v8::internal::IsBooleanMap(), v8::internal::IsNullOrUndefinedMap(), v8::internal::IsSmiOrObjectElementsKind(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by GetCloneModeForMap(), and GetCloneTargetMap().
GetCloneTargetMap()
template<SideStepTransition::Kind kind>
Tagged<Object> v8::internal::anonymous_namespace{ic.cc}::GetCloneTargetMap (Isolate * isolate, DirectHandle< Map > source_map, DirectHandle< Map > override_map)
Definition at line 3583 of file ic.cc.
                                                                 {
  static_assert(kind == SideStepTransition::Kind::kObjectAssign ||
                kind == SideStepTransition::Kind::kCloneObject);
  if (!v8_flags.clone_object_sidestep_transitions) {
    return SideStepTransition::Empty;
  }
  // Ensure we can follow the sidestep transition NativeContext-wise.
  if (!source_map->BelongsToSameNativeContextAs(isolate->context())) {
    return SideStepTransition::Empty;
  }
  Tagged<Object> result = SideStepTransition::Empty;
  TransitionsAccessor transitions(isolate, *source_map);
  if (transitions.HasSideStepTransitions()) {
    result = transitions.GetSideStepTransition(kind);
    if (result.IsHeapObject()) {
      // Exclude deprecated maps.
      auto map = Cast<Map>(result.GetHeapObject());
      bool is_valid = !map->is_deprecated();
      // In the case of object assign we need to check the prototype validity
      // cell on the override map. If the override map changed we cannot assume
      // that it is correct to set all properties without any getter/setter in
      // the prototype chain interfering.
      if constexpr (kind == SideStepTransition::Kind::kObjectAssign) {
        if (is_valid) {
          DCHECK_EQ(*override_map, isolate->object_function()->initial_map());
          Tagged<Object> validity_cell = transitions.GetSideStepTransition(
              SideStepTransition::Kind::kObjectAssignValidityCell);
          is_valid = validity_cell.IsHeapObject() &&
                     Cast<Cell>(validity_cell)->value().ToSmi().value() ==
                         Map::kPrototypeChainValid;
        }
      }
      if (V8_LIKELY(is_valid)) {
        if (result.IsHeapObject()) {
          CHECK_EQ(GetCloneModeForMapPreCheck(source_map, false, isolate),
                   FastCloneObjectMode::kMaybeSupported);
        }
      } else {
        result = SideStepTransition::Empty;
      }
    }
  }
#ifdef DEBUG
  FastCloneObjectMode clone_mode =
      GetCloneModeForMap(source_map, false, isolate);
  if (result == SideStepTransition::Unreachable) {
    switch (clone_mode) {
      case FastCloneObjectMode::kNotSupported:
      case FastCloneObjectMode::kDifferentMap:
        break;
      case FastCloneObjectMode::kEmptyObject:
      case FastCloneObjectMode::kIdenticalMap:
        DCHECK_EQ(kind, SideStepTransition::Kind::kObjectAssign);
        break;
      case FastCloneObjectMode::kMaybeSupported:
        UNREACHABLE();
    }
  } else if (result != SideStepTransition::Empty) {
    Tagged<Map> target = Cast<Map>(result.GetHeapObject());
    switch (clone_mode) {
      case FastCloneObjectMode::kIdenticalMap:
        if (kind == SideStepTransition::Kind::kCloneObject) {
          DCHECK_EQ(*source_map, target);
          break;
        }
        DCHECK_EQ(kind, SideStepTransition::Kind::kObjectAssign);
        [[fallthrough]];
      case FastCloneObjectMode::kDifferentMap:
        DCHECK(CanFastCloneObjectToObjectLiteral(source_map,
                                                 direct_handle(target, isolate),
                                                 override_map, false, isolate));
        break;
      default:
        UNREACHABLE();
    }
  } else {
    DCHECK_EQ(result, SideStepTransition::Empty);
  }
#endif // DEBUG
  return result;
}
References CanFastCloneObjectToObjectLiteral(), CHECK_EQ, v8::internal::Isolate::context(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::direct_handle(), v8::internal::SideStepTransition::Empty, GetCloneModeForMap(), GetCloneModeForMapPreCheck(), v8::internal::TransitionsAccessor::GetSideStepTransition(), v8::internal::TransitionsAccessor::HasSideStepTransitions(), v8::internal::TaggedImpl< kRefType, StorageType >::IsHeapObject(), v8::internal::SideStepTransition::kCloneObject, v8::internal::SideStepTransition::kObjectAssign, v8::internal::SideStepTransition::kObjectAssignValidityCell, v8::internal::Map::kPrototypeChainValid, v8::base::internal::result, v8::internal::UNREACHABLE(), v8::internal::SideStepTransition::Unreachable, v8::internal::v8_flags, and V8_LIKELY.
GetModifier() [1/2]
const char* v8::internal::anonymous_namespace{ic.cc}::GetModifier (KeyedAccessLoadMode mode)
Definition at line 79 of file ic.cc.
                                                  {
  switch (mode) {
    case KeyedAccessLoadMode::kHandleOOB:
      return ".OOB";
    case KeyedAccessLoadMode::kHandleHoles:
      return ".HOLES";
    case KeyedAccessLoadMode::kHandleOOBAndHoles:
      return ".OOB+HOLES";
    case KeyedAccessLoadMode::kInBounds:
      return "";
  }
}
References v8::internal::kHandleHoles, v8::internal::kHandleOOB, v8::internal::kHandleOOBAndHoles, v8::internal::kInBounds, and mode().
GetModifier() [2/2]
const char* v8::internal::anonymous_namespace{ic.cc}::GetModifier (KeyedAccessStoreMode mode)
Definition at line 92 of file ic.cc.
                                                   {
  switch (mode) {
    case KeyedAccessStoreMode::kHandleCOW:
      return ".COW";
    case KeyedAccessStoreMode::kGrowAndHandleCOW:
      return ".STORE+COW";
    case KeyedAccessStoreMode::kIgnoreTypedArrayOOB:
      return ".IGNORE_OOB";
    case KeyedAccessStoreMode::kInBounds:
      return "";
  }
  UNREACHABLE();
}
References v8::internal::kGrowAndHandleCOW, v8::internal::kHandleCOW, v8::internal::kIgnoreTypedArrayOOB, v8::internal::kInBounds, mode(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::IC::TraceIC().
GetNewKeyedLoadMode()
KeyedAccessLoadMode v8::internal::anonymous_namespace{ic.cc}::GetNewKeyedLoadMode (Isolate * isolate, DirectHandle< HeapObject > receiver, size_t index, bool is_found, MaybeDirectHandle< Object > result)
Definition at line 1315 of file ic.cc.
                                                                          {
  DirectHandle<Map> receiver_map(Cast<HeapObject>(receiver)->map(), isolate);
  if (!AllowConvertHoleElementToUndefined(isolate, receiver_map)) {
    return KeyedAccessLoadMode::kInBounds;
  }
  // Always handle holes when the elements kind is HOLEY_ELEMENTS, since the
  // optimizer compilers can not benefit from this information to narrow the
  // type. That is, the load type will always just be a generic tagged value.
  // This avoid an IC miss if we see a hole.
  ElementsKind elements_kind = receiver_map->elements_kind();
  bool always_handle_holes = (elements_kind == HOLEY_ELEMENTS);
  // In bound access and did not read a hole.
  if (is_found) {
#ifdef V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
    // We can encode undefined in HOLEY_DOUBLE_ELEMENTS, so we always have to
    // check for those even if we found a value.
    if (elements_kind == HOLEY_DOUBLE_ELEMENTS) {
      DirectHandle<Object> result_handle;
      if (result.ToHandle(&result_handle)) {
        if (Is<Undefined>(result_handle)) {
          always_handle_holes = true;
        }
      }
    }
#endif // V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
    return always_handle_holes ? KeyedAccessLoadMode::kHandleHoles
                               : KeyedAccessLoadMode::kInBounds;
  }
  // OOB access.
  bool is_oob_access = IsOutOfBoundsAccess(receiver, index);
  if (is_oob_access) {
    return always_handle_holes ? KeyedAccessLoadMode::kHandleOOBAndHoles
                               : KeyedAccessLoadMode::kHandleOOB;
  }
  // Read a hole.
  DCHECK(!is_found && !is_oob_access);
  bool handle_hole = AllowReadingHoleElement(elements_kind);
  DCHECK_IMPLIES(always_handle_holes, handle_hole);
  return handle_hole ? KeyedAccessLoadMode::kHandleHoles
                     : KeyedAccessLoadMode::kInBounds;
}
References AllowConvertHoleElementToUndefined(), AllowReadingHoleElement(), v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::HOLEY_DOUBLE_ELEMENTS, v8::internal::HOLEY_ELEMENTS, v8::internal::index, IsOutOfBoundsAccess(), v8::internal::kHandleHoles, v8::internal::kHandleOOB, v8::internal::kHandleOOBAndHoles, v8::internal::kInBounds, and v8::base::internal::result.
Referenced by v8::internal::KeyedLoadIC::Load().
GetStoreMode()
KeyedAccessStoreMode v8::internal::anonymous_namespace{ic.cc}::GetStoreMode (DirectHandle< JSObject > receiver, size_t index)
Definition at line 2578 of file ic.cc.
                                                {
  bool oob_access = IsOutOfBoundsAccess(receiver, index);
  // Don't consider this a growing store if the store would send the receiver to
  // dictionary mode.
  bool allow_growth =
      IsJSArray(*receiver) && oob_access && index <= JSArray::kMaxArrayIndex &&
      !receiver->WouldConvertToSlowElements(static_cast<uint32_t>(index));
  if (allow_growth) {
    return KeyedAccessStoreMode::kGrowAndHandleCOW;
  }
  if (receiver->map()->has_typed_array_or_rab_gsab_typed_array_elements() &&
      oob_access) {
    return KeyedAccessStoreMode::kIgnoreTypedArrayOOB;
  }
  return receiver->elements()->IsCowArray() ? KeyedAccessStoreMode::kHandleCOW
                                            : KeyedAccessStoreMode::kInBounds;
}
References v8::internal::index, IsOutOfBoundsAccess(), v8::internal::kGrowAndHandleCOW, v8::internal::kHandleCOW, v8::internal::kIgnoreTypedArrayOOB, v8::internal::kInBounds, and v8::internal::JSArray::kMaxArrayIndex.
Referenced by v8::internal::StoreInArrayLiteralIC::Store(), and v8::internal::KeyedStoreIC::Store().
GetUpdatedLoadModeForMap()
KeyedAccessLoadMode v8::internal::anonymous_namespace{ic.cc}::GetUpdatedLoadModeForMap (Isolate * isolate, DirectHandle< Map > map, KeyedAccessLoadMode load_mode)
Definition at line 1364 of file ic.cc.
                                                                            {
  // If we are not allowed to convert a hole to undefined, then we should not
  // handle OOB nor reading holes.
  if (!AllowConvertHoleElementToUndefined(isolate, map)) {
    return KeyedAccessLoadMode::kInBounds;
  }
  // Check if the elements kind allow reading a hole.
  bool allow_reading_hole_element =
      AllowReadingHoleElement(map->elements_kind());
  switch (load_mode) {
    case KeyedAccessLoadMode::kInBounds:
    case KeyedAccessLoadMode::kHandleOOB:
      return load_mode;
    case KeyedAccessLoadMode::kHandleHoles:
      return allow_reading_hole_element ? KeyedAccessLoadMode::kHandleHoles
                                        : KeyedAccessLoadMode::kInBounds;
    case KeyedAccessLoadMode::kHandleOOBAndHoles:
      return allow_reading_hole_element
                 ? KeyedAccessLoadMode::kHandleOOBAndHoles
                 : KeyedAccessLoadMode::kHandleOOB;
  }
}
References AllowConvertHoleElementToUndefined(), AllowReadingHoleElement(), v8::internal::kHandleHoles, v8::internal::kHandleOOB, v8::internal::kHandleOOBAndHoles, and v8::internal::kInBounds.
Referenced by v8::internal::KeyedLoadIC::LoadElementPolymorphicHandlers().
IntPtrKeyToSize()
bool v8::internal::anonymous_namespace{ic.cc}::IntPtrKeyToSize (intptr_t index, DirectHandle< HeapObject > receiver, size_t * out)
Definition at line 1534 of file ic.cc.
                                  {
  if (index < 0) {
    if (IsJSTypedArray(*receiver)) {
      // For JSTypedArray receivers, we can support negative keys, which we
      // just map to a very large value. This is valid because all OOB accesses
      // (negative or positive) are handled the same way, and size_t::max is
      // guaranteed to be an OOB access.
      *out = std::numeric_limits<size_t>::max();
      return true;
    }
    return false;
  }
#if V8_HOST_ARCH_64_BIT
  if (index > JSObject::kMaxElementIndex && !IsJSTypedArray(*receiver)) {
    return false;
  }
#else
  // On 32-bit platforms, any intptr_t is less than kMaxElementIndex.
  static_assert(
      static_cast<double>(std::numeric_limits<decltype(index)>::max()) <=
      static_cast<double>(JSObject::kMaxElementIndex));
#endif
  *out = static_cast<size_t>(index);
  return true;
}
References v8::internal::index, and v8::internal::JSObject::kMaxElementIndex.
Referenced by v8::internal::KeyedLoadIC::Load(), and v8::internal::KeyedStoreIC::Store().
IsOutOfBoundsAccess()
bool v8::internal::anonymous_namespace{ic.cc}::IsOutOfBoundsAccess (DirectHandle< Object > receiver, size_t index)
Definition at line 1295 of file ic.cc.
                                                                      {
  size_t length;
  if (IsJSArray(*receiver)) {
    length = Object::NumberValue(Cast<JSArray>(*receiver)->length());
  } else if (IsJSTypedArray(*receiver)) {
    length = Cast<JSTypedArray>(*receiver)->GetLength();
  } else if (IsJSObject(*receiver)) {
    length = Cast<JSObject>(*receiver)->elements()->length();
  } else if (IsString(*receiver)) {
    length = Cast<String>(*receiver)->length();
  } else {
    return false;
  }
  return index >= length;
}
References v8::internal::index, v8::internal::length, and v8::internal::Object::NumberValue().
Referenced by GetNewKeyedLoadMode(), and GetStoreMode().
MaybeCanCloneObjectForObjectAssign()
bool v8::internal::anonymous_namespace{ic.cc}::MaybeCanCloneObjectForObjectAssign (DirectHandle< JSReceiver > source, DirectHandle< Map > source_map, DirectHandle< JSReceiver > target, Isolate * isolate)
Definition at line 3859 of file ic.cc.
                                                          {
  FastCloneObjectMode clone_mode =
      GetCloneModeForMap(source_map, false, isolate);
  switch (clone_mode) {
    case FastCloneObjectMode::kIdenticalMap:
    case FastCloneObjectMode::kDifferentMap:
      break;
    case FastCloneObjectMode::kNotSupported:
      return false;
    case FastCloneObjectMode::kEmptyObject:
    case FastCloneObjectMode::kMaybeSupported:
      // Cannot happen since we should only be called with JSObjects.
      UNREACHABLE();
  }
  // We need to be sure that there are no setters or other nastiness installed
  // on the Object.prototype which clash with the properties we intende to copy.
  DirectHandle<FixedArray> keys;
  auto res =
      KeyAccumulator::GetKeys(isolate, source, KeyCollectionMode::kOwnOnly,
                              ONLY_ENUMERABLE, GetKeysConversion::kKeepNumbers);
  CHECK(res.ToHandle(&keys));
  for (int i = 0; i < keys->length(); ++i) {
    Handle<Object> next_key(keys->get(i), isolate);
    PropertyKey key(isolate, next_key);
    LookupIterator it(isolate, target, key);
    switch (it.state()) {
      case LookupIterator::NOT_FOUND:
        continue;
      case LookupIterator::DATA:
        if (it.property_attributes() & PropertyAttributes::READ_ONLY) {
          return false;
        }
        continue;
      case LookupIterator::INTERCEPTOR:
      case LookupIterator::TRANSITION:
      case LookupIterator::ACCESS_CHECK:
      case LookupIterator::JSPROXY:
      case LookupIterator::WASM_OBJECT:
      case LookupIterator::TYPED_ARRAY_INDEX_NOT_FOUND:
      case LookupIterator::ACCESSOR:
        return false;
      case LookupIterator::STRING_LOOKUP_START_OBJECT:
        UNREACHABLE();
    }
    UNREACHABLE();
  }
  return true;
}
References v8::internal::LookupIterator::ACCESS_CHECK, v8::internal::LookupIterator::ACCESSOR, CHECK, v8::internal::LookupIterator::DATA, GetCloneModeForMap(), v8::internal::KeyAccumulator::GetKeys(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::LookupIterator::INTERCEPTOR, v8::internal::LookupIterator::JSPROXY, v8::internal::key, v8::internal::kKeepNumbers, v8::internal::kOwnOnly, v8::internal::LookupIterator::NOT_FOUND, v8::internal::ONLY_ENUMERABLE, v8::internal::LookupIterator::property_attributes(), v8::internal::READ_ONLY, v8::internal::LookupIterator::state(), v8::internal::LookupIterator::STRING_LOOKUP_START_OBJECT, v8::internal::LookupIterator::TRANSITION, v8::internal::LookupIterator::TYPED_ARRAY_INDEX_NOT_FOUND, v8::internal::UNREACHABLE(), and v8::internal::LookupIterator::WASM_OBJECT.
Referenced by v8::internal::RUNTIME_FUNCTION().
MayHaveTypedArrayInPrototypeChain()
bool v8::internal::anonymous_namespace{ic.cc}::MayHaveTypedArrayInPrototypeChain (Isolate * isolate, DirectHandle< JSObject > object)
Definition at line 2567 of file ic.cc.
                                                                      {
  for (PrototypeIterator iter(isolate, *object); !iter.IsAtEnd();
       iter.Advance()) {
    // Be conservative, don't walk into proxies.
    if (IsJSProxy(iter.GetCurrent())) return true;
    if (IsJSTypedArray(iter.GetCurrent())) return true;
  }
  return false;
}
References v8::internal::PrototypeIterator::IsAtEnd().
Referenced by v8::internal::KeyedStoreIC::Store().
MigrateDeprecated()
bool v8::internal::anonymous_namespace{ic.cc}::MigrateDeprecated (Isolate * isolate, DirectHandle< Object > object)
Definition at line 326 of file ic.cc.
                                                                      {
  if (!IsJSObject(*object)) return false;
  DirectHandle<JSObject> receiver = Cast<JSObject>(object);
  if (!receiver->map()->is_deprecated()) return false;
  JSObject::MigrateInstance(isolate, receiver);
  return true;
}
References v8::internal::JSObject::MigrateInstance().
Referenced by v8::internal::LoadIC::Load(), v8::internal::KeyedLoadIC::Load(), v8::internal::RUNTIME_FUNCTION(), v8::internal::StoreInArrayLiteralIC::Store(), v8::internal::StoreIC::Store(), and v8::internal::KeyedStoreIC::Store().
SetCloneTargetMap()
template<SideStepTransition::Kind kind>
void v8::internal::anonymous_namespace{ic.cc}::SetCloneTargetMap (Isolate * isolate, DirectHandle< Map > source_map, DirectHandle< Map > new_target_map, DirectHandle< Map > override_map)
Definition at line 3668 of file ic.cc.
                                                       {
  if (!v8_flags.clone_object_sidestep_transitions) return;
  DCHECK(CanCacheCloneTargetMapTransition(source_map, new_target_map, false,
                                          isolate));
  DCHECK_EQ(GetCloneTargetMap<kind>(isolate, source_map, override_map),
            SideStepTransition::Empty);
  DCHECK(!new_target_map->is_deprecated());
  // Adding this transition also ensures that when the source map field
  // generalizes, we also generalize the target map.
  DCHECK(IsSmiOrObjectElementsKind(new_target_map->elements_kind()));
  constexpr bool need_validity_cell =
      kind == SideStepTransition::Kind::kObjectAssign;
  DirectHandle<Cell> validity_cell;
  if constexpr (need_validity_cell) {
    // Since we only clone into empty object literals we only need one validity
    // cell on that prototype chain.
    DCHECK_EQ(*override_map, isolate->object_function()->initial_map());
    validity_cell = Cast<Cell>(
        Map::GetOrCreatePrototypeChainValidityCell(override_map, isolate));
  }
  TransitionsAccessor::EnsureHasSideStepTransitions(isolate, source_map);
  TransitionsAccessor transitions(isolate, *source_map);
  transitions.SetSideStepTransition(kind, *new_target_map);
  if constexpr (need_validity_cell) {
    transitions.SetSideStepTransition(
        SideStepTransition::Kind::kObjectAssignValidityCell, *validity_cell);
  }
  DCHECK_EQ(GetCloneTargetMap<kind>(isolate, source_map, override_map),
            *new_target_map);
}
References CanCacheCloneTargetMapTransition(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::SideStepTransition::Empty, v8::internal::TransitionsAccessor::EnsureHasSideStepTransitions(), v8::internal::Map::GetOrCreatePrototypeChainValidityCell(), v8::internal::IsSmiOrObjectElementsKind(), v8::internal::SideStepTransition::kObjectAssign, v8::internal::SideStepTransition::kObjectAssignValidityCell, v8::internal::TransitionsAccessor::SetSideStepTransition(), and v8::internal::v8_flags.
SetCloneTargetMapUnsupported()
template<SideStepTransition::Kind kind>
void v8::internal::anonymous_namespace{ic.cc}::SetCloneTargetMapUnsupported (Isolate * isolate, DirectHandle< Map > source_map, DirectHandle< Map > override_map)
Definition at line 3704 of file ic.cc.
                                                                  {
  if (!v8_flags.clone_object_sidestep_transitions) return;
  DCHECK_EQ(GetCloneTargetMap<kind>(isolate, source_map, override_map),
            SideStepTransition::Empty);
  DCHECK(CanCacheCloneTargetMapTransition(source_map, {}, false, isolate));
  // Adding this transition also ensures that when the source map field
  // generalizes, we also generalize the target map.
  TransitionsAccessor::EnsureHasSideStepTransitions(isolate, source_map);
  TransitionsAccessor(isolate, *source_map)
      .SetSideStepTransition(kind, SideStepTransition::Unreachable);
  DCHECK_EQ(GetCloneTargetMap<kind>(isolate, source_map, override_map),
            SideStepTransition::Unreachable);
}
References CanCacheCloneTargetMapTransition(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::SideStepTransition::Empty, v8::internal::TransitionsAccessor::EnsureHasSideStepTransitions(), v8::internal::TransitionsAccessor::SetSideStepTransition(), v8::internal::SideStepTransition::Unreachable, and v8::internal::v8_flags.
Referenced by v8::internal::RUNTIME_FUNCTION().
StoreOwnElement()
Maybe<bool> v8::internal::anonymous_namespace{ic.cc}::StoreOwnElement (Isolate * isolate, DirectHandle< JSArray > array, Handle< Object > index, DirectHandle< Object > value)
Definition at line 2743 of file ic.cc.
                                                                              {
  DCHECK(IsNumber(*index));
  PropertyKey key(isolate, index);
  LookupIterator it(isolate, array, key, LookupIterator::OWN);
  MAYBE_RETURN(JSObject::DefineOwnPropertyIgnoreAttributes(
                   &it, value, NONE, Just(ShouldThrow::kThrowOnError)),
               Nothing<bool>());
  return Just(true);
}
References v8::internal::DCHECK(), v8::internal::JSObject::DefineOwnPropertyIgnoreAttributes(), v8::internal::index, v8::internal::IsNumber(), v8::Just(), v8::internal::key, v8::internal::kThrowOnError, MAYBE_RETURN, v8::internal::NONE, v8::internal::LookupIterator::OWN, and v8::internal::value.
Referenced by v8::internal::RUNTIME_FUNCTION(), and v8::internal::StoreInArrayLiteralIC::Store().
TryConvertKey()
KeyType v8::internal::anonymous_namespace{ic.cc}::TryConvertKey (Handle< Object > key, Isolate * isolate, intptr_t * index_out, Handle< Name > * name_out)
Definition at line 1498 of file ic.cc.
                                              {
  if (IsSmi(*key)) {
    *index_out = Smi::ToInt(*key);
    return kIntPtr;
  }
  if (IsHeapNumber(*key)) {
    double num = Cast<HeapNumber>(*key)->value();
    if (!(num >= -kMaxSafeInteger)) return kBailout;
    if (num > kMaxSafeInteger) return kBailout;
    *index_out = static_cast<intptr_t>(num);
    if (*index_out != num) return kBailout;
    return kIntPtr;
  }
  if (IsString(*key)) {
    key = isolate->factory()->InternalizeString(Cast<String>(key));
    uint32_t maybe_array_index;
    if (Cast<String>(*key)->AsArrayIndex(&maybe_array_index)) {
      if (maybe_array_index <= INT_MAX) {
        *index_out = static_cast<intptr_t>(maybe_array_index);
        return kIntPtr;
      }
      // {key} is a string representation of an array index beyond the range
      // that the IC could handle. Don't try to take the named-property path.
      return kBailout;
    }
    *name_out = Cast<String>(key);
    return kName;
  }
  if (IsSymbol(*key)) {
    *name_out = Cast<Symbol>(key);
    return kName;
  }
  return kBailout;
}
References v8::internal::Isolate::factory(), v8::internal::Factory::InternalizeString(), v8::internal::IsSmi(), kBailout, v8::internal::key, kIntPtr, v8::internal::kMaxSafeInteger, kName, and v8::internal::Smi::ToInt().
Referenced by v8::internal::KeyedLoadIC::Load(), and v8::internal::KeyedStoreIC::Store().