v8::internal::anonymous_namespace{code-stub-assembler.cc} Namespace Reference
Classes
struct OffsetOfArrayDataStart
struct OffsetOfArrayDataStart< TransitionArray >
struct OffsetOfArrayDataStart< DescriptorArray >
class MetaTableAccessor
Typedefs
using MetaTableAccessFunction = std::function< void(MetaTableAccessor &)>
Functions
Builtin BigIntComparisonBuiltinOf (Operation const &op)
TNode< FixedArrayBase > InnerAllocateElements (CodeStubAssembler *csa, TNode< JSArray > js_array, int offset)
TNode< HeapObject > InnerAllocateMemento (CodeStubAssembler *csa, TNode< HeapObject > previous, TNode< IntPtrT > offset)
MachineRepresentation ElementsKindToMachineRepresentation (ElementsKind kind)
Operation Reverse (Operation op)
void GenerateMetaTableAccess (CodeStubAssembler *csa, TNode< IntPtrT > capacity, MetaTableAccessFunction builder)
Typedef Documentation
MetaTableAccessFunction
using v8::internal::anonymous_namespace{code-stub-assembler.cc}::MetaTableAccessFunction = typedef std::function<void(MetaTableAccessor&)>
Definition at line 18720 of file code-stub-assembler.cc.
Function Documentation
BigIntComparisonBuiltinOf()
Builtin v8::internal::anonymous_namespace{code-stub-assembler.cc}::BigIntComparisonBuiltinOf (Operation const & op)
Definition at line 57 of file code-stub-assembler.cc.
                                                       {
  switch (op) {
    case Operation::kLessThan:
      return Builtin::kBigIntLessThan;
    case Operation::kGreaterThan:
      return Builtin::kBigIntGreaterThan;
    case Operation::kLessThanOrEqual:
      return Builtin::kBigIntLessThanOrEqual;
    case Operation::kGreaterThanOrEqual:
      return Builtin::kBigIntGreaterThanOrEqual;
    default:
      UNREACHABLE();
  }
}
References v8::internal::kGreaterThan, v8::internal::kLessThan, and v8::internal::UNREACHABLE().
Referenced by v8::internal::CodeStubAssembler::RelationalComparison().
ElementsKindToMachineRepresentation()
MachineRepresentation v8::internal::anonymous_namespace{code-stub-assembler.cc}::ElementsKindToMachineRepresentation (ElementsKind kind)
Definition at line 13280 of file code-stub-assembler.cc.
                                                                             {
  switch (kind) {
    case UINT8_CLAMPED_ELEMENTS:
    case UINT8_ELEMENTS:
    case INT8_ELEMENTS:
      return MachineRepresentation::kWord8;
    case UINT16_ELEMENTS:
    case INT16_ELEMENTS:
    case FLOAT16_ELEMENTS:
      return MachineRepresentation::kWord16;
    case UINT32_ELEMENTS:
    case INT32_ELEMENTS:
      return MachineRepresentation::kWord32;
    case FLOAT32_ELEMENTS:
      return MachineRepresentation::kFloat32;
    case FLOAT64_ELEMENTS:
      return MachineRepresentation::kFloat64;
    default:
      UNREACHABLE();
  }
}
References v8::internal::maglev::FLOAT32_ELEMENTS, v8::internal::maglev::INT16_ELEMENTS, v8::internal::maglev::INT8_ELEMENTS, v8::internal::maglev::UINT16_ELEMENTS, v8::internal::maglev::UINT8_CLAMPED_ELEMENTS, v8::internal::maglev::UINT8_ELEMENTS, and UNREACHABLE.
Referenced by v8::internal::CodeStubAssembler::StoreElementTypedArray(), and v8::internal::CodeStubAssembler::StoreElementTypedArrayWord32().
GenerateMetaTableAccess()
void v8::internal::anonymous_namespace{code-stub-assembler.cc}::GenerateMetaTableAccess (CodeStubAssembler * csa, TNode< IntPtrT > capacity, MetaTableAccessFunction builder)
Definition at line 18726 of file code-stub-assembler.cc.
                                                              {
  MetaTableAccessor mta8 = MetaTableAccessor(*csa, MachineType::Uint8());
  MetaTableAccessor mta16 = MetaTableAccessor(*csa, MachineType::Uint16());
  MetaTableAccessor mta32 = MetaTableAccessor(*csa, MachineType::Uint32());
  using Label = compiler::CodeAssemblerLabel;
  Label small(csa), medium(csa), done(csa);
  csa->GotoIf(
      csa->IntPtrLessThanOrEqual(
          capacity,
          csa->IntPtrConstant(SwissNameDictionary::kMax1ByteMetaTableCapacity)),
      &small);
  csa->GotoIf(
      csa->IntPtrLessThanOrEqual(
          capacity,
          csa->IntPtrConstant(SwissNameDictionary::kMax2ByteMetaTableCapacity)),
      &medium);
  builder(mta32);
  csa->Goto(&done);
  csa->Bind(&medium);
  builder(mta16);
  csa->Goto(&done);
  csa->Bind(&small);
  builder(mta8);
  csa->Goto(&done);
  csa->Bind(&done);
}
References v8::internal::CodeStubAssembler::Bind(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::SwissNameDictionary::kMax1ByteMetaTableCapacity, v8::internal::SwissNameDictionary::kMax2ByteMetaTableCapacity, v8::internal::MachineType::Uint16(), v8::internal::MachineType::Uint32(), and v8::internal::MachineType::Uint8().
Referenced by v8::internal::CodeStubAssembler::AllocateSwissNameDictionaryWithCapacity(), v8::internal::CodeStubAssembler::LoadSwissNameDictionaryNumberOfDeletedElements(), v8::internal::CodeStubAssembler::LoadSwissNameDictionaryNumberOfElements(), v8::internal::CodeStubAssembler::StoreSwissNameDictionaryEnumToEntryMapping(), v8::internal::CodeStubAssembler::SwissNameDictionaryIncreaseElementCountOrBailout(), and v8::internal::CodeStubAssembler::SwissNameDictionaryUpdateCountsForDeletion().
InnerAllocateElements()
TNode<FixedArrayBase> v8::internal::anonymous_namespace{code-stub-assembler.cc}::InnerAllocateElements (CodeStubAssembler * csa, TNode< JSArray > js_array, int offset)
Definition at line 5135 of file code-stub-assembler.cc.
                                                        {
  return csa->UncheckedCast<FixedArrayBase>(
      csa->BitcastWordToTagged(csa->IntPtrAdd(
          csa->BitcastTaggedToWord(js_array), csa->IntPtrConstant(offset))));
}
References v8::internal::compiler::CodeAssembler::BitcastTaggedToWord(), v8::internal::compiler::CodeAssembler::IntPtrAdd(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), and v8::internal::compiler::CodeAssembler::UncheckedCast().
Referenced by v8::internal::CodeStubAssembler::AllocateUninitializedJSArrayWithElements().
InnerAllocateMemento()
TNode<HeapObject> v8::internal::anonymous_namespace{code-stub-assembler.cc}::InnerAllocateMemento (CodeStubAssembler * csa, TNode< HeapObject > previous, TNode< IntPtrT > offset)
Definition at line 6615 of file code-stub-assembler.cc.
                                                              {
  return csa->UncheckedCast<HeapObject>(csa->BitcastWordToTagged(
      csa->IntPtrAdd(csa->BitcastTaggedToWord(previous), offset)));
}
References v8::internal::compiler::CodeAssembler::BitcastTaggedToWord(), v8::internal::compiler::CodeAssembler::IntPtrAdd(), and v8::internal::compiler::CodeAssembler::UncheckedCast().
Referenced by v8::internal::CodeStubAssembler::InitializeAllocationMemento().
Reverse()
Operation v8::internal::anonymous_namespace{code-stub-assembler.cc}::Reverse (Operation op)
Definition at line 14813 of file code-stub-assembler.cc.
                                {
  switch (op) {
    case Operation::kLessThan:
      return Operation::kGreaterThan;
    case Operation::kLessThanOrEqual:
      return Operation::kGreaterThanOrEqual;
    case Operation::kGreaterThan:
      return Operation::kLessThan;
    case Operation::kGreaterThanOrEqual:
      return Operation::kLessThanOrEqual;
    default:
      break;
  }
  UNREACHABLE();
}
References v8::internal::kGreaterThan, v8::internal::kLessThan, and UNREACHABLE.
Referenced by v8::internal::CodeStubAssembler::RelationalComparison().