v8::internal::impl Namespace Reference
Functions
Address SignPC (Address pc, Address sp)
Address AuthPAC (Address pc, Address sp)
Function Documentation
AuthPAC()
Address v8::internal::impl::AuthPAC (Address pc, Address sp) [inline]
Definition at line 37 of file pointer-authentication-arm64.h.
                                                  {
#ifdef USE_SIMULATOR
  pc = Simulator::AuthPAC(pc, sp, Simulator::kPACKeyIB,
                          Simulator::kInstructionPointer);
#else
  asm volatile(
      " mov x17, %[pc]\n"
      " mov x16, %[stack_ptr]\n"
      " autib1716\n"
      " mov %[pc], x17\n"
      // Save LR.
      " mov x16, x30\n"
      // Check if authentication was successful, otherwise crash.
      " mov x30, x17\n"
      " xpaclri\n"
      " cmp x30, x17\n"
      // Restore LR, to help with unwinding in case `brk #0` is hit below.
      " mov x30, x16\n"
      " b.eq 1f\n"
      " brk #0\n"
      "1:\n"
      : [pc] "+r"(pc)
      : [stack_ptr] "r"(sp)
      : "x16", "x17", "x30", "cc");
#endif
  return pc;
}
Referenced by v8::internal::PointerAuthentication::AuthenticatePC(), v8::internal::PointerAuthentication::MoveSignedPC(), and v8::internal::PointerAuthentication::ReplacePC().
SignPC()
Address v8::internal::impl::SignPC (Address pc, Address sp) [inline]
Definition at line 20 of file pointer-authentication-arm64.h.
                                                 {
#ifdef USE_SIMULATOR
  pc = Simulator::AddPAC(pc, sp, Simulator::kPACKeyIB,
                         Simulator::kInstructionPointer);
#else
  asm volatile(
      " mov x17, %[pc]\n"
      " mov x16, %[sp]\n"
      " pacib1716\n"
      " mov %[pc], x17\n"
      : [pc] "+r"(pc)
      : [sp] "r"(sp)
      : "x16", "x17");
#endif
  return pc;
}
Referenced by v8::internal::PointerAuthentication::MoveSignedPC(), and v8::internal::PointerAuthentication::SignAndCheckPC().