v8::internal::compiler::turboshaft::anonymous_namespace{loop-unrolling-reducer.cc} Namespace Reference
Functions
template<class Int >
std::optional< Int > Next (Int val, Int incr, StaticCanonicalForLoopMatcher::BinOp binop_op, WordRepresentation binop_rep)
template<class Int >
bool Cmp (Int val, Int max, CmpOp cmp_op)
template<class Int >
bool SubWillOverflow (Int lhs, Int rhs)
template<class Int >
bool DivWillOverflow (Int dividend, Int divisor)
Function Documentation
Cmp()
template<class Int >
bool v8::internal::compiler::turboshaft::anonymous_namespace{loop-unrolling-reducer.cc}::Cmp (Int val, Int max, CmpOp cmp_op)
Definition at line 346 of file loop-unrolling-reducer.cc.
                                         {
  switch (cmp_op) {
    case CmpOp::kSignedLessThan:
    case CmpOp::kUnsignedLessThan:
      return val < max;
    case CmpOp::kSignedLessThanOrEqual:
    case CmpOp::kUnsignedLessThanOrEqual:
      return val <= max;
    case CmpOp::kSignedGreaterThan:
    case CmpOp::kUnsignedGreaterThan:
      return val > max;
    case CmpOp::kSignedGreaterThanOrEqual:
    case CmpOp::kUnsignedGreaterThanOrEqual:
      return val >= max;
    case CmpOp::kEqual:
      return val == max;
  }
}
References v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::kEqual, v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::kSignedGreaterThan, v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::kSignedGreaterThanOrEqual, v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::kSignedLessThan, v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::kSignedLessThanOrEqual, v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::kUnsignedGreaterThan, v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::kUnsignedGreaterThanOrEqual, v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::kUnsignedLessThan, and v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::kUnsignedLessThanOrEqual.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-assembler-arm64.cc}::AllocateRaw(), v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::CountIterationsImpl(), and v8::internal::maglev::anonymous_namespace{maglev-ir-arm64.cc}::HandleInterruptsAndTiering().
DivWillOverflow()
template<class Int >
bool v8::internal::compiler::turboshaft::anonymous_namespace{loop-unrolling-reducer.cc}::DivWillOverflow (Int dividend, Int divisor)
Definition at line 379 of file loop-unrolling-reducer.cc.
                                                {
  if constexpr (std::is_unsigned_v<Int>) {
    return false;
  } else {
    return dividend == std::numeric_limits<Int>::min() && divisor == -1;
  }
}
Referenced by v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::CountIterationsImpl().
Next()
template<class Int >
std::optional<Int> v8::internal::compiler::turboshaft::anonymous_namespace{loop-unrolling-reducer.cc}::Next (Int val, Int incr, StaticCanonicalForLoopMatcher::BinOp binop_op, WordRepresentation binop_rep)
Definition at line 306 of file loop-unrolling-reducer.cc.
                                                      {
  switch (binop_op) {
    case BinOp::kBitwiseAnd:
      return val & incr;
    case BinOp::kBitwiseOr:
      return val | incr;
    case BinOp::kBitwiseXor:
      return val ^ incr;
      // Even regular Add/Sub/Mul probably shouldn't under/overflow here, so we
      // check for overflow in all cases (and C++ signed integer overflow is
      // undefined behavior, so have to use something from base::bits anyways).
#define CASE_ARITH(op) \
  case BinOp::k##op: \
  case BinOp::kOverflowChecked##op: { \
    if (binop_rep == WordRepresentation::Word32()) { \
      int32_t res; \
      if (base::bits::Signed##op##Overflow32(\
              static_cast<int32_t>(val), static_cast<int32_t>(incr), &res)) { \
        return std::nullopt; \
      } \
      return static_cast<Int>(res); \
    } else { \
      DCHECK_EQ(binop_rep, WordRepresentation::Word64()); \
      int64_t res; \
      if (base::bits::Signed##op##Overflow64(val, incr, &res)) { \
        return std::nullopt; \
      } \
      return static_cast<Int>(res); \
    } \
  }
      CASE_ARITH(Add)
      CASE_ARITH(Mul)
      CASE_ARITH(Sub)
#undef CASE_CHECKED
  }
}
References v8::bigint::Add(), CASE_ARITH, v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::kBitwiseAnd, v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::kBitwiseOr, v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::kBitwiseXor, and v8::internal::wasm::liftoff::Sub().
Referenced by v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::CountIterationsImpl(), v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::Finalize(), v8::internal::SamplingCircularQueue< v8::internal::TickSampleEventRecord, kTickSampleQueueLength >::FinishEnqueue(), v8::internal::SamplingCircularQueue< T, Length >::FinishEnqueue(), v8::base::RandomNumberGenerator::NextBool(), v8::base::RandomNumberGenerator::NextInt(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseBackReferenceIndex(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseCaptureGroupName(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseCharacterClass(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseCharacterEscape(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseClassEscape(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseClassIntersection(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseClassSetCharacter(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseClassSetOperand(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseClassStringDisjunction(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseClassSubtraction(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseClassUnion(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseDisjunction(), v8::internal::Parser::ParseExportClause(), v8::internal::Parser::ParseExportSpecifierName(), v8::internal::Parser::ParseFunctionLiteral(), v8::internal::Parser::ParseImportWithOrAssertClause(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseOpenParenthesis(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseUnicodeEscape(), v8::internal::SetScopeVariableValue(), v8::internal::DateParser::InputReader< Char >::SkipParentheses(), v8::internal::BreakIterator::SkipTo(), v8::internal::DateParser::InputReader< Char >::SkipWhiteSpace(), v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::Start(), and v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::TryParseCharacterClassEscape().
SubWillOverflow()
template<class Int >
bool v8::internal::compiler::turboshaft::anonymous_namespace{loop-unrolling-reducer.cc}::SubWillOverflow (Int lhs, Int rhs)
Definition at line 366 of file loop-unrolling-reducer.cc.
                                       {
  if constexpr (std::is_same_v<Int, int32_t> || std::is_same_v<Int, uint32_t>) {
    int32_t unused;
    return base::bits::SignedSubOverflow32(lhs, rhs, &unused);
  } else {
    static_assert(std::is_same_v<Int, int64_t> ||
                  std::is_same_v<Int, uint64_t>);
    int64_t unused;
    return base::bits::SignedSubOverflow64(lhs, rhs, &unused);
  }
}
References v8::base::bits::SignedSubOverflow32(), and v8::base::bits::SignedSubOverflow64().
Referenced by v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::CountIterationsImpl().