v8::anonymous_namespace{d8-console.cc} Namespace Reference
Functions
void WriteToFile (const char *prefix, FILE *file, Isolate *isolate, const debug::ConsoleCallArguments &args)
std::optional< std::string > GetTimerLabel (const debug::ConsoleCallArguments &args)
Variables
static constexpr const char * kCpuProfileOutputFilename = `v8.prof`
Function Documentation
GetTimerLabel()
std::optional<std::string> v8::anonymous_namespace{d8-console.cc}::GetTimerLabel (const debug::ConsoleCallArguments & args)
Definition at line 47 of file d8-console.cc.
                                           {
  if (args.Length() == 0) return "default";
  Isolate* isolate = args.GetIsolate();
  v8::TryCatch try_catch(isolate);
  v8::String::Utf8Value label(isolate, args[0]);
  if (*label == nullptr) return std::nullopt;
  return std::string(*label, label.length());
}
References v8::base::args, v8::String::Utf8Value::length(), and v8::internal::string.
Referenced by v8::D8Console::Time(), v8::D8Console::TimeEnd(), v8::D8Console::TimeLog(), and v8::D8Console::TimeStamp().
WriteToFile()
void v8::anonymous_namespace{d8-console.cc}::WriteToFile (const char * prefix, FILE * file, Isolate * isolate, const debug::ConsoleCallArguments & args)
Definition at line 19 of file d8-console.cc.
                                                        {
  if (prefix) fprintf(file, "%s: ", prefix);
  for (int i = 0; i < args.Length(); i++) {
    HandleScope handle_scope(isolate);
    if (i > 0) fprintf(file, " ");
    Local<Value> arg = args[i];
    Local<String> str_obj;
    if (arg->IsSymbol()) arg = Local<Symbol>::Cast(arg)->Description(isolate);
    if (!arg->ToString(isolate->GetCurrentContext()).ToLocal(&str_obj)) return;
    v8::String::Utf8Value str(isolate, str_obj);
    size_t n = fwrite(*str, sizeof(**str), str.length(), file);
    if (n != str.length()) {
      printf("Error in fwrite\n");
      base::OS::ExitProcess(1);
    }
  }
  fprintf(file, "\n");
  // Flush the file to avoid output to pile up in a buffer. Console output is
  // often used for timing, so it should appear as soon as the code is executed.
  fflush(file);
}
References v8::base::args, v8::Local< T >::Cast(), v8::base::OS::ExitProcess(), file(), v8::Isolate::GetCurrentContext(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::String::Utf8Value::length().
Variable Documentation
kCpuProfileOutputFilename
constexpr const char* v8::anonymous_namespace{d8-console.cc}::kCpuProfileOutputFilename = `v8.prof` [static], [constexpr]
Definition at line 45 of file d8-console.cc.
Referenced by v8::D8Console::ProfileEnd().