v8::internal::anonymous_namespace{runtime-internal.cc} Namespace Reference
Functions
Tagged< Object > NewError (Isolate *isolate, RuntimeArguments args, Handle< JSFunction >(Isolate::*constructor_fn)())
Tagged< Object > ThrowError (Isolate *isolate, RuntimeArguments args, Handle< JSFunction >(Isolate::*constructor_fn)())
const char * ElementsKindToType (ElementsKind fixed_elements_kind)
Tagged< Object > BytecodeBudgetInterruptWithStackCheck (Isolate *isolate, RuntimeArguments &args, CodeKind code_kind)
Tagged< Object > BytecodeBudgetInterrupt (Isolate *isolate, RuntimeArguments &args, CodeKind code_kind)
Function Documentation
BytecodeBudgetInterrupt()
Tagged<Object> v8::internal::anonymous_namespace{runtime-internal.cc}::BytecodeBudgetInterrupt (Isolate * isolate, RuntimeArguments & args, CodeKind code_kind)
Definition at line 400 of file runtime-internal.cc.
                                                           {
  HandleScope scope(isolate);
  DCHECK_EQ(1, args.length());
  DirectHandle<JSFunction> function = args.at<JSFunction>(0);
  function->TraceOptimizationStatus("budget from %s",
                                    CodeKindToString(code_kind));
  TRACE_EVENT0("v8.execute", "V8.BytecodeBudgetInterrupt");
  isolate->tiering_manager()->OnInterruptTick(function, code_kind);
  return ReadOnlyRoots(isolate).undefined_value();
}
References v8::base::args, v8::internal::CodeKindToString(), DCHECK_EQ, v8::internal::TieringManager::OnInterruptTick(), v8::internal::Isolate::tiering_manager(), and TRACE_EVENT0.
Referenced by v8::internal::RUNTIME_FUNCTION().
BytecodeBudgetInterruptWithStackCheck()
Tagged<Object> v8::internal::anonymous_namespace{runtime-internal.cc}::BytecodeBudgetInterruptWithStackCheck (Isolate * isolate, RuntimeArguments & args, CodeKind code_kind)
Definition at line 373 of file runtime-internal.cc.
                                                                         {
  HandleScope scope(isolate);
  DCHECK_EQ(1, args.length());
  DirectHandle<JSFunction> function = args.at<JSFunction>(0);
  TRACE_EVENT0("v8.execute", "V8.BytecodeBudgetInterruptWithStackCheck");
  // Check for stack interrupts here so that we can fold the interrupt check
  // into bytecode budget interrupts.
  StackLimitCheck check(isolate);
  if (check.JsHasOverflowed()) {
    // We ideally wouldn't actually get StackOverflows here, since we stack
    // check on bytecode entry, but it's possible that this check fires due to
    // the runtime function call being what overflows the stack.
    return isolate->StackOverflow();
  } else if (check.InterruptRequested()) {
    Tagged<Object> return_value = isolate->stack_guard()->HandleInterrupts();
    if (!IsUndefined(return_value, isolate)) {
      return return_value;
    }
  }
  isolate->tiering_manager()->OnInterruptTick(function, code_kind);
  return ReadOnlyRoots(isolate).undefined_value();
}
References v8::base::args, DCHECK_EQ, v8::internal::StackGuard::HandleInterrupts(), v8::internal::StackLimitCheck::InterruptRequested(), v8::internal::StackLimitCheck::JsHasOverflowed(), v8::internal::TieringManager::OnInterruptTick(), v8::internal::Isolate::stack_guard(), v8::internal::Isolate::StackOverflow(), v8::internal::Isolate::tiering_manager(), and TRACE_EVENT0.
Referenced by v8::internal::RUNTIME_FUNCTION().
ElementsKindToType()
const char* v8::internal::anonymous_namespace{runtime-internal.cc}::ElementsKindToType (ElementsKind fixed_elements_kind)
Definition at line 162 of file runtime-internal.cc.
                                                                 {
  switch (fixed_elements_kind) {
#define ELEMENTS_KIND_CASE(Type, type, TYPE, ctype) \
  case TYPE##_ELEMENTS: \
    return #Type "Array";
    TYPED_ARRAYS(ELEMENTS_KIND_CASE)
    RAB_GSAB_TYPED_ARRAYS_WITH_TYPED_ARRAY_TYPE(ELEMENTS_KIND_CASE)
#undef ELEMENTS_KIND_CASE
    default:
      UNREACHABLE();
  }
}
References ELEMENTS_KIND_CASE, RAB_GSAB_TYPED_ARRAYS_WITH_TYPED_ARRAY_TYPE, TYPED_ARRAYS, and v8::internal::UNREACHABLE().
Referenced by v8::internal::RUNTIME_FUNCTION().
NewError()
Tagged<Object> v8::internal::anonymous_namespace{runtime-internal.cc}::NewError (Isolate * isolate, RuntimeArguments args, Handle< JSFunction >(Isolate::*)() constructor_fn)
Definition at line 99 of file runtime-internal.cc.
                                                                       {
  HandleScope scope(isolate);
  DCHECK_LE(1, args.length());
  int message_id_smi = args.smi_value_at(0);
  constexpr int kMaxMessageArgs = 3;
  DirectHandle<Object> message_args[kMaxMessageArgs];
  int num_message_args = 0;
  while (num_message_args < kMaxMessageArgs &&
         args.length() > num_message_args + 1) {
    message_args[num_message_args] = args.at(num_message_args + 1);
    ++num_message_args;
  }
  MessageTemplate message_id = MessageTemplateFromInt(message_id_smi);
  return *isolate->factory()->NewError(
      (isolate->*constructor_fn)(), message_id,
      base::VectorOf(message_args, num_message_args));
}
References v8::base::args, DCHECK_LE, v8::internal::Isolate::factory(), v8::internal::MessageTemplateFromInt(), v8::internal::Factory::NewError(), and v8::base::VectorOf().
Referenced by v8::internal::BUILTIN(), v8::internal::anonymous_namespace{builtins-sharedarraybuffer.cc}::CheckAtomicsPauseIterationNumber(), v8::internal::JSWrappedFunction::Create(), v8::internal::anonymous_namespace{runtime-object.cc}::FindPrivateMembersFromReceiver(), v8::internal::Runtime::GetPrivateMember(), v8::internal::anonymous_namespace{builtins-shadow-realm.cc}::GetWrappedValue(), v8::internal::Factory::NewError(), v8::internal::RUNTIME_FUNCTION(), v8::internal::Runtime::SetPrivateMember(), ThrowError(), and v8::ValueSerializer::Delegate::WriteHostObject().
ThrowError()
Tagged<Object> v8::internal::anonymous_namespace{runtime-internal.cc}::ThrowError (Isolate * isolate, RuntimeArguments args, Handle< JSFunction >(Isolate::*)() constructor_fn)
Definition at line 121 of file runtime-internal.cc.
                                                                         {
  return isolate->Throw(NewError(isolate, args, constructor_fn));
}
References v8::base::args, NewError(), and v8::internal::Isolate::Throw().
Referenced by v8::internal::RUNTIME_FUNCTION().