v8::internal::anonymous_namespace{runtime-wasm.cc} Namespace Reference
Classes
class FrameFinder
class ClearThreadInWasmScope
Functions
Tagged< WasmTrustedInstanceData > GetWasmInstanceDataOnStackTop (Isolate *isolate)
Tagged< Context > GetNativeContextFromWasmInstanceOnStackTop (Isolate *isolate)
Tagged< Object > ThrowWasmError (Isolate *isolate, MessageTemplate message, std::initializer_list< DirectHandle< Object >> args={})
Tagged< Object > ThrowWasmSuspendError (Isolate *isolate, MessageTemplate message)
Tagged< FixedArray > AllocateFeedbackVector (Isolate *isolate, DirectHandle< WasmTrustedInstanceData > trusted_instance_data, int declared_func_index)
void ReplaceJSToWasmWrapper (Isolate *isolate, Tagged< WasmTrustedInstanceData > trusted_instance_data, int function_index, Tagged< Code > wrapper_code, bool receiver_is_first_param)
Tagged< Object > ThrowTableOutOfBounds (Isolate *isolate, DirectHandle< WasmTrustedInstanceData > trusted_instance_data)
bool ExecuteWasmDebugBreaks (Isolate *isolate, DirectHandle< WasmTrustedInstanceData > trusted_instance_data, WasmFrame *frame)
template<typename T >
int MeasureWtf8 (base::Vector< const T > wtf16)
int MeasureWtf8 (Isolate *isolate, DirectHandle< String > string)
size_t MaxEncodedSize (base::Vector< const uint8_t > wtf16)
size_t MaxEncodedSize (base::Vector< const base::uc16 > wtf16)
bool HasUnpairedSurrogate (base::Vector< const uint8_t > wtf16)
bool HasUnpairedSurrogate (base::Vector< const base::uc16 > wtf16)
template<typename T >
int EncodeWtf8 (base::Vector< char > bytes, size_t offset, base::Vector< const T > wtf16, unibrow::Utf8Variant variant, MessageTemplate *message, MessageTemplate out_of_bounds)
template<typename GetWritableBytes >
Tagged< Object > EncodeWtf8 (Isolate *isolate, unibrow::Utf8Variant variant, DirectHandle< String > string, GetWritableBytes get_writable_bytes, size_t offset, MessageTemplate out_of_bounds_message)
Function Documentation
AllocateFeedbackVector()
Tagged<FixedArray> v8::internal::anonymous_namespace{runtime-wasm.cc}::AllocateFeedbackVector (Isolate * isolate, DirectHandle< WasmTrustedInstanceData > trusted_instance_data, int declared_func_index)
Definition at line 460 of file runtime-wasm.cc.
                             {
  DCHECK(isolate->context().is_null());
  isolate->set_context(trusted_instance_data->native_context());
  const wasm::WasmModule* module =
      trusted_instance_data->native_module()->module();
  int func_index = declared_func_index + module->num_imported_functions;
  int num_slots = NumFeedbackSlots(module, func_index);
  DirectHandle<FixedArray> vector =
      isolate->factory()->NewFixedArrayWithZeroes(num_slots);
  DCHECK_EQ(trusted_instance_data->feedback_vectors()->get(declared_func_index),
            Smi::zero());
  trusted_instance_data->feedback_vectors()->set(declared_func_index, *vector);
  isolate->set_context(Tagged<Context>());
  return *vector;
}
References v8::internal::Isolate::context(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Isolate::factory(), v8::internal::FactoryBase< Impl >::NewFixedArrayWithZeroes(), v8::internal::wasm::WasmModule::num_imported_functions, v8::internal::wasm::NumFeedbackSlots(), v8::internal::Isolate::set_context(), and v8::internal::Smi::zero().
Referenced by v8::internal::RUNTIME_FUNCTION().
EncodeWtf8() [1/2]
template<typename T >
int v8::internal::anonymous_namespace{runtime-wasm.cc}::EncodeWtf8 (base::Vector< char > bytes, size_t offset, base::Vector< const T > wtf16, unibrow::Utf8Variant variant, MessageTemplate * message, MessageTemplate out_of_bounds)
Definition at line 1629 of file runtime-wasm.cc.
                                                                        {
  // The first check is a quick estimate to decide whether the second check
  // is worth the computation.
  if (!base::IsInBounds<size_t>(offset, MaxEncodedSize(wtf16), bytes.size()) &&
      !base::IsInBounds<size_t>(offset, MeasureWtf8(wtf16), bytes.size())) {
    *message = out_of_bounds;
    return -1;
  }
  bool replace_invalid = false;
  switch (variant) {
    case unibrow::Utf8Variant::kWtf8:
      break;
    case unibrow::Utf8Variant::kUtf8:
      if (HasUnpairedSurrogate(wtf16)) {
        *message = MessageTemplate::kWasmTrapStringIsolatedSurrogate;
        return -1;
      }
      break;
    case unibrow::Utf8Variant::kLossyUtf8:
      replace_invalid = true;
      break;
    default:
      UNREACHABLE();
  }
  bool write_null = false;
  unibrow::Utf8::EncodingResult result =
      unibrow::Utf8::Encode(wtf16, bytes.begin() + offset,
                            bytes.size() - offset, write_null, replace_invalid);
  DCHECK_EQ(result.characters_processed, wtf16.size());
  DCHECK_LE(result.bytes_written, kMaxInt);
  return static_cast<int>(result.bytes_written);
}
References v8::base::Vector< T >::begin(), DCHECK_EQ, DCHECK_LE, unibrow::Utf8::Encode(), HasUnpairedSurrogate(), unibrow::kLossyUtf8, v8::internal::kMaxInt, MaxEncodedSize(), MeasureWtf8(), v8::base::internal::result, v8::base::Vector< T >::size(), and v8::internal::UNREACHABLE().
EncodeWtf8() [2/2]
template<typename GetWritableBytes >
Tagged<Object> v8::internal::anonymous_namespace{runtime-wasm.cc}::EncodeWtf8 (Isolate * isolate, unibrow::Utf8Variant variant, DirectHandle< String > string, GetWritableBytes get_writable_bytes, size_t offset, MessageTemplate out_of_bounds_message)
Definition at line 1666 of file runtime-wasm.cc.
                                                                 {
  string = String::Flatten(isolate, string);
  MessageTemplate message;
  int written;
  {
    DisallowGarbageCollection no_gc;
    String::FlatContent content = string->GetFlatContent(no_gc);
    base::Vector<char> dst = get_writable_bytes(no_gc);
    written = content.IsOneByte()
                  ? EncodeWtf8(dst, offset, content.ToOneByteVector(), variant,
                               &message, out_of_bounds_message)
                  : EncodeWtf8(dst, offset, content.ToUC16Vector(), variant,
                               &message, out_of_bounds_message);
  }
  if (written < 0) {
    DCHECK_NE(message, MessageTemplate::kNone);
    return ThrowWasmError(isolate, message);
  }
  return *isolate->factory()->NewNumberFromInt(written);
}
References DCHECK_NE, v8::internal::Isolate::factory(), v8::internal::String::FlatContent::IsOneByte(), v8::internal::FactoryBase< Impl >::NewNumberFromInt(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, ThrowWasmError(), v8::internal::String::FlatContent::ToOneByteVector(), and v8::internal::String::FlatContent::ToUC16Vector().
Referenced by v8::internal::RUNTIME_FUNCTION(), and v8::internal::ToUtf8Lossy().
ExecuteWasmDebugBreaks()
bool v8::internal::anonymous_namespace{runtime-wasm.cc}::ExecuteWasmDebugBreaks (Isolate * isolate, DirectHandle< WasmTrustedInstanceData > trusted_instance_data, WasmFrame * frame)
Definition at line 1016 of file runtime-wasm.cc.
                      {
  DirectHandle<Script> script{trusted_instance_data->module_object()->script(),
                              isolate};
  auto* debug_info = trusted_instance_data->native_module()->GetDebugInfo();
  // Enter the debugger.
  DebugScope debug_scope(isolate->debug());
  // Check for instrumentation breakpoints first, but still execute regular
  // breakpoints afterwards.
  bool paused_on_instrumentation = false;
  DCHECK_EQ(script->break_on_entry(),
            !!trusted_instance_data->break_on_entry());
  if (script->break_on_entry()) {
    MaybeDirectHandle<FixedArray> maybe_on_entry_breakpoints =
        WasmScript::CheckBreakPoints(isolate, script,
                                     WasmScript::kOnEntryBreakpointPosition,
                                     frame->id());
    script->set_break_on_entry(false);
    // Update the "break_on_entry" flag on all live instances.
    i::Tagged<i::WeakArrayList> weak_instance_list =
        script->wasm_weak_instance_list();
    for (int i = 0; i < weak_instance_list->length(); ++i) {
      if (weak_instance_list->Get(i).IsCleared()) continue;
      i::Cast<i::WasmInstanceObject>(weak_instance_list->Get(i).GetHeapObject())
          ->trusted_data(isolate)
          ->set_break_on_entry(false);
    }
    DCHECK(!trusted_instance_data->break_on_entry());
    if (!maybe_on_entry_breakpoints.is_null()) {
      isolate->debug()->OnInstrumentationBreak();
      paused_on_instrumentation = true;
    }
  }
  if (debug_info->IsStepping(frame) && !debug_info->IsFrameBlackboxed(frame)) {
    debug_info->ClearStepping(isolate);
    StepAction step_action = isolate->debug()->last_step_action();
    isolate->debug()->ClearStepping();
    isolate->debug()->OnDebugBreak(isolate->factory()->empty_fixed_array(),
                                   step_action);
    return true;
  }
  // Check whether we hit a breakpoint.
  DirectHandle<FixedArray> breakpoints;
  if (WasmScript::CheckBreakPoints(isolate, script, frame->position(),
                                   frame->id())
          .ToHandle(&breakpoints)) {
    debug_info->ClearStepping(isolate);
    StepAction step_action = isolate->debug()->last_step_action();
    isolate->debug()->ClearStepping();
    if (isolate->debug()->break_points_active()) {
      // We hit one or several breakpoints. Notify the debug listeners.
      isolate->debug()->OnDebugBreak(breakpoints, step_action);
    }
    return true;
  }
  return paused_on_instrumentation;
}
References v8::internal::Debug::break_points_active(), v8::internal::WasmScript::CheckBreakPoints(), v8::internal::Debug::ClearStepping(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Isolate::debug(), v8::internal::Isolate::factory(), v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObject(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::MaybeDirectHandle< T >::is_null(), v8::internal::TaggedImpl< kRefType, StorageType >::IsCleared(), v8::internal::WasmScript::kOnEntryBreakpointPosition, v8::internal::Debug::last_step_action(), v8::internal::Debug::OnDebugBreak(), v8::internal::Debug::OnInstrumentationBreak(), and v8::internal::script.
Referenced by v8::internal::RUNTIME_FUNCTION().
GetNativeContextFromWasmInstanceOnStackTop()
Tagged<Context> v8::internal::anonymous_namespace{runtime-wasm.cc}::GetNativeContextFromWasmInstanceOnStackTop (Isolate * isolate)
Definition at line 102 of file runtime-wasm.cc.
                                                                             {
  return GetWasmInstanceDataOnStackTop(isolate)->native_context();
}
References GetWasmInstanceDataOnStackTop().
Referenced by v8::internal::RUNTIME_FUNCTION().
GetWasmInstanceDataOnStackTop()
Tagged<WasmTrustedInstanceData> v8::internal::anonymous_namespace{runtime-wasm.cc}::GetWasmInstanceDataOnStackTop (Isolate * isolate)
Definition at line 87 of file runtime-wasm.cc.
                      {
  Address fp = Isolate::c_entry_fp(isolate->thread_local_top());
  fp = Memory<Address>(fp + ExitFrameConstants::kCallerFPOffset);
#ifdef DEBUG
  intptr_t marker =
      Memory<intptr_t>(fp + CommonFrameConstants::kContextOrFrameTypeOffset);
  DCHECK(StackFrame::MarkerToType(marker) == StackFrame::WASM ||
         StackFrame::MarkerToType(marker) == StackFrame::WASM_SEGMENT_START);
#endif
  Tagged<Object> trusted_instance_data(
      Memory<Address>(fp + WasmFrameConstants::kWasmInstanceDataOffset));
  return Cast<WasmTrustedInstanceData>(trusted_instance_data);
}
References v8::internal::Isolate::c_entry_fp(), v8::internal::DCHECK(), v8::internal::CommonFrameConstants::kCallerFPOffset, v8::internal::CommonFrameConstants::kContextOrFrameTypeOffset, v8::internal::StackFrame::MarkerToType(), and v8::internal::Isolate::thread_local_top().
Referenced by GetNativeContextFromWasmInstanceOnStackTop().
HasUnpairedSurrogate() [1/2]
bool v8::internal::anonymous_namespace{runtime-wasm.cc}::HasUnpairedSurrogate (base::Vector< const base::uc16 > wtf16)
Definition at line 1625 of file runtime-wasm.cc.
                                                            {
  return unibrow::Utf16::HasUnpairedSurrogate(wtf16.begin(), wtf16.size());
}
References v8::base::Vector< T >::begin(), unibrow::Utf16::HasUnpairedSurrogate(), and v8::base::Vector< T >::size().
Referenced by EncodeWtf8().
HasUnpairedSurrogate() [2/2]
bool v8::internal::anonymous_namespace{runtime-wasm.cc}::HasUnpairedSurrogate (base::Vector< const uint8_t > wtf16)
Definition at line 1624 of file runtime-wasm.cc.
{ return false; }
MaxEncodedSize() [1/2]
size_t v8::internal::anonymous_namespace{runtime-wasm.cc}::MaxEncodedSize (base::Vector< const base::uc16 > wtf16)
Definition at line 1619 of file runtime-wasm.cc.
                                                        {
  DCHECK(wtf16.size() < std::numeric_limits<size_t>::max() /
                            unibrow::Utf8::kMax16BitCodeUnitSize);
  return wtf16.size() * unibrow::Utf8::kMax16BitCodeUnitSize;
}
References v8::internal::DCHECK(), unibrow::Utf8::kMax16BitCodeUnitSize, and v8::base::Vector< T >::size().
Referenced by EncodeWtf8().
MaxEncodedSize() [2/2]
size_t v8::internal::anonymous_namespace{runtime-wasm.cc}::MaxEncodedSize (base::Vector< const uint8_t > wtf16)
Definition at line 1614 of file runtime-wasm.cc.
                                                       {
  DCHECK(wtf16.size() < std::numeric_limits<size_t>::max() /
                            unibrow::Utf8::kMax8BitCodeUnitSize);
  return wtf16.size() * unibrow::Utf8::kMax8BitCodeUnitSize;
}
References v8::internal::DCHECK(), unibrow::Utf8::kMax8BitCodeUnitSize, and v8::base::Vector< T >::size().
MeasureWtf8() [1/2]
template<typename T >
int v8::internal::anonymous_namespace{runtime-wasm.cc}::MeasureWtf8 (base::Vector< const T > wtf16)
Definition at line 1593 of file runtime-wasm.cc.
                                           {
  int previous = unibrow::Utf16::kNoPreviousCharacter;
  int length = 0;
  DCHECK(wtf16.size() <= String::kMaxLength);
  static_assert(String::kMaxLength <=
                (kMaxInt / unibrow::Utf8::kMaxEncodedSize));
  for (size_t i = 0; i < wtf16.size(); i++) {
    int current = wtf16[i];
    length += unibrow::Utf8::Length(current, previous);
    previous = current;
  }
  return length;
}
References v8::internal::DCHECK(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, unibrow::Utf8::kMaxEncodedSize, v8::internal::kMaxInt, v8::internal::String::kMaxLength, unibrow::Utf16::kNoPreviousCharacter, v8::internal::length, unibrow::Utf8::Length(), and v8::base::Vector< T >::size().
MeasureWtf8() [2/2]
int v8::internal::anonymous_namespace{runtime-wasm.cc}::MeasureWtf8 (Isolate * isolate, DirectHandle< String > string)
Definition at line 1606 of file runtime-wasm.cc.
                                                               {
  string = String::Flatten(isolate, string);
  DisallowGarbageCollection no_gc;
  String::FlatContent content = string->GetFlatContent(no_gc);
  DCHECK(content.IsFlat());
  return content.IsOneByte() ? MeasureWtf8(content.ToOneByteVector())
                             : MeasureWtf8(content.ToUC16Vector());
}
References v8::internal::DCHECK(), v8::internal::String::FlatContent::IsFlat(), v8::internal::String::FlatContent::IsOneByte(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::String::FlatContent::ToOneByteVector(), and v8::internal::String::FlatContent::ToUC16Vector().
Referenced by EncodeWtf8(), v8::internal::RUNTIME_FUNCTION(), and v8::internal::ToUtf8Lossy().
ReplaceJSToWasmWrapper()
void v8::internal::anonymous_namespace{runtime-wasm.cc}::ReplaceJSToWasmWrapper (Isolate * isolate, Tagged< WasmTrustedInstanceData > trusted_instance_data, int function_index, Tagged< Code > wrapper_code, bool receiver_is_first_param)
Definition at line 553 of file runtime-wasm.cc.
                                  {
  Tagged<WasmFuncRef> func_ref;
  // Always expect a func_ref. If this fails, we are maybe compiling a wrapper
  // for the start function. This function is only called once, so this should
  // not happen.
  CHECK(trusted_instance_data->try_get_func_ref(function_index, &func_ref));
  Tagged<JSFunction> external_function;
  CHECK(func_ref->internal(isolate)->try_get_external(&external_function));
  if (external_function->shared()->HasWasmJSFunctionData(isolate)) return;
  CHECK(external_function->shared()->HasWasmExportedFunctionData(isolate));
  Tagged<WasmExportedFunctionData> function_data =
      external_function->shared()->wasm_exported_function_data();
  if ((function_data->receiver_is_first_param() != 0) !=
      receiver_is_first_param) {
    // Different "receiver is first parameter" settings, do nothing.
    return;
  }
  external_function->UpdateCode(isolate, wrapper_code);
  function_data->set_wrapper_code(wrapper_code);
}
References CHECK.
Referenced by v8::internal::RUNTIME_FUNCTION().
ThrowTableOutOfBounds()
Tagged<Object> v8::internal::anonymous_namespace{runtime-wasm.cc}::ThrowTableOutOfBounds (Isolate * isolate, DirectHandle< WasmTrustedInstanceData > trusted_instance_data)
Definition at line 832 of file runtime-wasm.cc.
                                                                 {
  // Handle out-of-bounds access here in the runtime call, rather
  // than having the lower-level layers deal with JS exceptions.
  if (isolate->context().is_null()) {
    isolate->set_context(trusted_instance_data->native_context());
  }
  return ThrowWasmError(isolate, MessageTemplate::kWasmTrapTableOutOfBounds);
}
References v8::internal::Isolate::context(), v8::internal::Isolate::set_context(), and ThrowWasmError().
Referenced by v8::internal::RUNTIME_FUNCTION().
ThrowWasmError()
Tagged<Object> v8::internal::anonymous_namespace{runtime-wasm.cc}::ThrowWasmError (Isolate * isolate, MessageTemplate message, std::initializer_list< DirectHandle< Object >> args = {})
Definition at line 146 of file runtime-wasm.cc.
                                                     {}) {
#if V8_ENABLE_DRUMBRAKE
  if (v8_flags.wasm_jitless) {
    // Store the trap reason to be retrieved later when the interpreter will
    // trap while detecting the thrown exception.
    wasm::WasmInterpreterThread::SetRuntimeLastWasmError(isolate, message);
  }
#endif // V8_ENABLE_DRUMBRAKE
  DirectHandle<JSObject> error_obj =
      isolate->factory()->NewWasmRuntimeError(message, base::VectorOf(args));
  JSObject::AddProperty(isolate, error_obj,
                        isolate->factory()->wasm_uncatchable_symbol(),
                        isolate->factory()->true_value(), NONE);
  return isolate->Throw(*error_obj);
}
Referenced by EncodeWtf8(), v8::internal::RUNTIME_FUNCTION(), and ThrowTableOutOfBounds().
ThrowWasmSuspendError()
Tagged<Object> v8::internal::anonymous_namespace{runtime-wasm.cc}::ThrowWasmSuspendError (Isolate * isolate, MessageTemplate message)
Definition at line 165 of file runtime-wasm.cc.
                                                              {
  DirectHandle<JSObject> error_obj =
      isolate->factory()->NewWasmSuspendError(message);
  return isolate->Throw(*error_obj);
}
References v8::internal::Isolate::factory(), and v8::internal::Isolate::Throw().
Referenced by v8::internal::RUNTIME_FUNCTION().