cppgc::internal::anonymous_namespace{marker.cc} Namespace Reference
Functions
bool EnterIncrementalMarkingIfNeeded (MarkingConfig config, HeapBase &heap)
bool ExitIncrementalMarkingIfNeeded (MarkingConfig config, HeapBase &heap)
template<StatsCollector::ScopeId scope_id, size_t kDeadlineCheckInterval = kDefaultDeadlineCheckInterval, typename WorklistLocal , typename Callback >
bool DrainWorklistWithBytesAndTimeDeadline (StatsCollector *stats_collector, BasicMarkingState &marking_state, size_t marked_bytes_deadline, v8::base::TimeTicks time_deadline, WorklistLocal &worklist_local, Callback callback)
size_t GetNextIncrementalStepDuration (heap::base::IncrementalMarkingSchedule &schedule, HeapBase &heap)
Variables
static constexpr size_t kDefaultDeadlineCheckInterval = 150u
Function Documentation
DrainWorklistWithBytesAndTimeDeadline()
template<StatsCollector::ScopeId scope_id, size_t kDeadlineCheckInterval = kDefaultDeadlineCheckInterval, typename WorklistLocal , typename Callback >
bool cppgc::internal::anonymous_namespace{marker.cc}::DrainWorklistWithBytesAndTimeDeadline (StatsCollector * stats_collector, BasicMarkingState & marking_state, size_t marked_bytes_deadline, v8::base::TimeTicks time_deadline, WorklistLocal & worklist_local, Callback callback)
Definition at line 65 of file marker.cc.
                                                              {
  return DrainWorklistWithPredicate<kDeadlineCheckInterval>(
      [&marking_state, marked_bytes_deadline, time_deadline]() {
        return (marked_bytes_deadline <= marking_state.marked_bytes()) ||
               (time_deadline <= v8::base::TimeTicks::Now());
      },
      [stats_collector]() {
        return StatsCollector::DisabledScope(stats_collector, scope_id);
      },
      worklist_local, callback);
}
References cppgc::internal::BasicMarkingState::marked_bytes(), and v8::base::TimeTicks::Now().
Referenced by cppgc::internal::MarkerBase::ProcessWorklistsWithDeadline().
EnterIncrementalMarkingIfNeeded()
bool cppgc::internal::anonymous_namespace{marker.cc}::EnterIncrementalMarkingIfNeeded (MarkingConfig config, HeapBase & heap)
Definition at line 38 of file marker.cc.
                                                                           {
  if (config.marking_type == MarkingConfig::MarkingType::kIncremental ||
      config.marking_type ==
          MarkingConfig::MarkingType::kIncrementalAndConcurrent) {
    WriteBarrier::FlagUpdater::Enter();
    heap.set_incremental_marking_in_progress(true);
    return true;
  }
  return false;
}
References cppgc::internal::WriteBarrier::FlagUpdater::Enter(), cppgc::Heap::kIncremental, cppgc::Heap::kIncrementalAndConcurrent, and cppgc::internal::MarkingConfig::marking_type.
Referenced by cppgc::internal::MarkerBase::StartMarking().
ExitIncrementalMarkingIfNeeded()
bool cppgc::internal::anonymous_namespace{marker.cc}::ExitIncrementalMarkingIfNeeded (MarkingConfig config, HeapBase & heap)
Definition at line 49 of file marker.cc.
                                                                          {
  if (config.marking_type == MarkingConfig::MarkingType::kIncremental ||
      config.marking_type ==
          MarkingConfig::MarkingType::kIncrementalAndConcurrent) {
    WriteBarrier::FlagUpdater::Exit();
    heap.set_incremental_marking_in_progress(false);
    return true;
  }
  return false;
}
References cppgc::internal::WriteBarrier::FlagUpdater::Exit(), cppgc::Heap::kIncremental, cppgc::Heap::kIncrementalAndConcurrent, and cppgc::internal::MarkingConfig::marking_type.
Referenced by cppgc::internal::MarkerBase::EnterAtomicPause().
GetNextIncrementalStepDuration()
size_t cppgc::internal::anonymous_namespace{marker.cc}::GetNextIncrementalStepDuration (heap::base::IncrementalMarkingSchedule & schedule, HeapBase & heap)
Definition at line 82 of file marker.cc.
                                                                  {
  return schedule.GetNextIncrementalStepDuration(
      heap.stats_collector()->allocated_object_size());
}
References heap::base::IncrementalMarkingSchedule::GetNextIncrementalStepDuration().
Referenced by cppgc::internal::MarkerBase::AdvanceMarkingWithLimits().
Variable Documentation
kDefaultDeadlineCheckInterval
constexpr size_t cppgc::internal::anonymous_namespace{marker.cc}::kDefaultDeadlineCheckInterval = 150u [static], [constexpr]
Definition at line 60 of file marker.cc.
Referenced by cppgc::internal::MarkerBase::ProcessWorklistsWithDeadline().