v8::internal::swiss_table Namespace Reference
Classes
class ProbeSequence
class BitMask
struct GroupSse2Polyfill
struct GroupPortableImpl
Typedefs
using ctrl_t = signed char
using h2_t = uint8_t
using Group = GroupPortableImpl
Enumerations
enum Ctrl : ctrl_t { kEmpty = -128
, kDeleted = -2
, kSentinel = -1
 }
Functions
static uint32_t H1 (uint32_t hash)
static swiss_table::ctrl_t H2 (uint32_t hash)
Variables
static constexpr int kH2Bits = 7
static constexpr int kNotFullMask = (1 << kH2Bits)
Typedef Documentation
ctrl_t
using v8::internal::swiss_table::ctrl_t = typedef signed char
Definition at line 171 of file swiss-hash-table-helpers.h.
Group
using v8::internal::swiss_table::Group = typedef GroupPortableImpl
Definition at line 357 of file swiss-hash-table-helpers.h.
h2_t
using v8::internal::swiss_table::h2_t = typedef uint8_t
Definition at line 172 of file swiss-hash-table-helpers.h.
Enumeration Type Documentation
Ctrl
enum v8::internal::swiss_table::Ctrl : ctrl_t
Enumerator
kEmpty
kDeleted
kSentinel
Definition at line 176 of file swiss-hash-table-helpers.h.
          : ctrl_t {
  kEmpty = -128, // 0b10000000
  kDeleted = -2, // 0b11111110
  kSentinel = -1, // 0b11111111
};
Function Documentation
H1()
static uint32_t v8::internal::swiss_table::H1 (uint32_t hash) [inline], [static]
Definition at line 212 of file swiss-hash-table-helpers.h.
{ return (hash >> kH2Bits); }
References kH2Bits.
Referenced by v8::internal::SwissNameDictionary::probe().
H2()
static swiss_table::ctrl_t v8::internal::swiss_table::H2 (uint32_t hash) [inline], [static]
Definition at line 217 of file swiss-hash-table-helpers.h.
                                                  {
  return hash & ((1 << kH2Bits) - 1);
}
References kH2Bits.
Referenced by v8::internal::SwissNameDictionary::AddInternal(), and v8::internal::SwissNameDictionary::FindEntry().
Variable Documentation
kH2Bits
constexpr int v8::internal::swiss_table::kH2Bits = 7 [static], [constexpr]
Definition at line 203 of file swiss-hash-table-helpers.h.
Referenced by H1(), and H2().
kNotFullMask
constexpr int v8::internal::swiss_table::kNotFullMask = (1 << kH2Bits) [static], [constexpr]
Definition at line 205 of file swiss-hash-table-helpers.h.
Referenced by v8::internal::CodeStubAssembler::CopySwissNameDictionary().