v8::internal::anonymous_namespace{regexp-compiler.cc} Namespace Reference
Classes
class AssertionPropagator
class EatsAtLeastPropagator
Functions
constexpr base::uc32 MaxCodeUnit (const bool one_byte)
constexpr uint32_t CharMask (const bool one_byte)
int GetCaseIndependentLetters (Isolate *isolate, base::uc16 character, RegExpCompiler *compiler, unibrow::uchar *letters, int letter_length)
bool EmitSimpleCharacter (Isolate *isolate, RegExpCompiler *compiler, base::uc16 c, Label *on_failure, int cp_offset, bool check, bool preloaded)
bool EmitAtomNonLetter (Isolate *isolate, RegExpCompiler *compiler, base::uc16 c, Label *on_failure, int cp_offset, bool check, bool preloaded)
bool ShortCutEmitCharacterPair (RegExpMacroAssembler *macro_assembler, bool one_byte, base::uc16 c1, base::uc16 c2, Label *on_failure)
bool EmitAtomLetter (Isolate *isolate, RegExpCompiler *compiler, base::uc16 c, Label *on_failure, int cp_offset, bool check, bool preloaded)
void EmitBoundaryTest (RegExpMacroAssembler *masm, int border, Label *fall_through, Label *above_or_equal, Label *below)
void EmitDoubleBoundaryTest (RegExpMacroAssembler *masm, int first, int last, Label *fall_through, Label *in_range, Label *out_of_range)
void EmitUseLookupTable (RegExpMacroAssembler *masm, ZoneList< base::uc32 > *ranges, uint32_t start_index, uint32_t end_index, base::uc32 min_char, Label *fall_through, Label *even_label, Label *odd_label)
void CutOutRange (RegExpMacroAssembler *masm, ZoneList< base::uc32 > *ranges, uint32_t start_index, uint32_t end_index, uint32_t cut_index, Label *even_label, Label *odd_label)
void SplitSearchSpace (ZoneList< base::uc32 > *ranges, uint32_t start_index, uint32_t end_index, uint32_t *new_start_index, uint32_t *new_end_index, base::uc32 *border)
void GenerateBranches (RegExpMacroAssembler *masm, ZoneList< base::uc32 > *ranges, uint32_t start_index, uint32_t end_index, base::uc32 min_char, base::uc32 max_char, Label *fall_through, Label *even_label, Label *odd_label)
void EmitClassRanges (RegExpMacroAssembler *macro_assembler, RegExpClassRanges *cr, bool one_byte, Label *on_failure, int cp_offset, bool check_offset, bool preloaded, Zone *zone)
uint32_t SmearBitsRight (uint32_t v)
bool RangesContainLatin1Equivalents (ZoneList< CharacterRange > *ranges)
void EmitWordCheck (RegExpMacroAssembler *assembler, Label *word, Label *non_word, bool fall_through_on_word)
void EmitHat (RegExpCompiler *compiler, RegExpNode *on_success, Trace *trace)
bool DeterminedAlready (const QuickCheckDetails *quick_check, int offset)
void UpdateBoundsCheck (int index, int *checked_up_to)
ContainedInLattice AddRange (ContainedInLattice containment, const int *ranges, int ranges_length, Interval new_range)
int BitsetFirstSetBit (BoyerMoorePositionInfo::Bitset bitset)
Function Documentation
AddRange()
ContainedInLattice v8::internal::anonymous_namespace{regexp-compiler.cc}::AddRange (ContainedInLattice containment, const int * ranges, int ranges_length, Interval new_range)
Definition at line 2800 of file regexp-compiler.cc.
                                                                   {
  DCHECK_EQ(1, ranges_length & 1);
  DCHECK_EQ(String::kMaxCodePoint + 1, ranges[ranges_length - 1]);
  if (containment == kLatticeUnknown) return containment;
  bool inside = false;
  int last = 0;
  for (int i = 0; i < ranges_length; inside = !inside, last = ranges[i], i++) {
    // Consider the range from last to ranges[i].
    // We haven't got to the new range yet.
    if (ranges[i] <= new_range.from()) continue;
    // New range is wholly inside last-ranges[i]. Note that new_range.to() is
    // inclusive, but the values in ranges are not.
    if (last <= new_range.from() && new_range.to() < ranges[i]) {
      return Combine(containment, inside ? kLatticeIn : kLatticeOut);
    }
    return kLatticeUnknown;
  }
  return containment;
}
References v8::internal::Combine(), DCHECK_EQ, v8::internal::Interval::from(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::kLatticeIn, v8::internal::kLatticeOut, v8::internal::kLatticeUnknown, v8::internal::String::kMaxCodePoint, and v8::internal::Interval::to().
Referenced by v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AddNonBmpSurrogatePairs(), v8::internal::AddressToTraceMap::MoveObject(), v8::internal::BoyerMoorePositionInfo::SetInterval(), and v8::internal::UnicodeRangeSplitter::UnicodeRangeSplitter().
BitsetFirstSetBit()
int v8::internal::anonymous_namespace{regexp-compiler.cc}::BitsetFirstSetBit (BoyerMoorePositionInfo::Bitset bitset)
Definition at line 2821 of file regexp-compiler.cc.
                                                           {
  static_assert(BoyerMoorePositionInfo::kMapSize ==
                2 * kInt64Size * kBitsPerByte);
  // Slight fiddling is needed here, since the bitset is of length 128 while
  // CountTrailingZeros requires an integral type and std::bitset can only
  // convert to unsigned long long. So we handle the most- and least-significant
  // bits separately.
  {
    static constexpr BoyerMoorePositionInfo::Bitset mask(~uint64_t{0});
    BoyerMoorePositionInfo::Bitset masked_bitset = bitset & mask;
    static_assert(kInt64Size >= sizeof(decltype(masked_bitset.to_ullong())));
    uint64_t lsb = masked_bitset.to_ullong();
    if (lsb != 0) return base::bits::CountTrailingZeros(lsb);
  }
  {
    BoyerMoorePositionInfo::Bitset masked_bitset = bitset >> 64;
    uint64_t msb = masked_bitset.to_ullong();
    if (msb != 0) return 64 + base::bits::CountTrailingZeros(msb);
  }
  return -1;
}
References v8::base::bits::CountTrailingZeros(), v8::internal::kBitsPerByte, v8::internal::kInt64Size, and v8::internal::BoyerMoorePositionInfo::kMapSize.
Referenced by v8::internal::BoyerMooreLookahead::EmitSkipInstructions(), v8::internal::BoyerMooreLookahead::FindBestInterval(), and v8::internal::BoyerMooreLookahead::GetSkipTable().
CharMask()
constexpr uint32_t v8::internal::anonymous_namespace{regexp-compiler.cc}::CharMask (const bool one_byte) [constexpr]
Definition at line 187 of file regexp-compiler.cc.
                                                 {
  static_assert(base::bits::IsPowerOfTwo(String::kMaxOneByteCharCodeU + 1));
  static_assert(base::bits::IsPowerOfTwo(String::kMaxUtf16CodeUnitU + 1));
  return MaxCodeUnit(one_byte);
}
References v8::base::bits::IsPowerOfTwo(), v8::internal::String::kMaxOneByteCharCodeU, v8::internal::String::kMaxUtf16CodeUnitU, and MaxCodeUnit().
Referenced by v8::internal::RegExpNode::EmitQuickCheck(), v8::internal::TextNode::GetQuickCheckDetails(), v8::internal::QuickCheckDetails::Rationalize(), and ShortCutEmitCharacterPair().
CutOutRange()
void v8::internal::anonymous_namespace{regexp-compiler.cc}::CutOutRange (RegExpMacroAssembler * masm, ZoneList< base::uc32 > * ranges, uint32_t start_index, uint32_t end_index, uint32_t cut_index, Label * even_label, Label * odd_label)
Definition at line 1049 of file regexp-compiler.cc.
                                                      {
  bool odd = (((cut_index - start_index) & 1) == 1);
  Label* in_range_label = odd ? odd_label : even_label;
  Label dummy;
  EmitDoubleBoundaryTest(masm, ranges->at(cut_index),
                         ranges->at(cut_index + 1) - 1, &dummy, in_range_label,
                         &dummy);
  DCHECK(!dummy.is_linked());
  // Cut out the single range by rewriting the array. This creates a new
  // range that is a merger of the two ranges on either side of the one we
  // are cutting out. The oddity of the labels is preserved.
  for (uint32_t j = cut_index; j > start_index; j--) {
    ranges->at(j) = ranges->at(j - 1);
  }
  for (uint32_t j = cut_index + 1; j < end_index; j++) {
    ranges->at(j) = ranges->at(j + 1);
  }
}
References v8::internal::ZoneList< T >::at(), v8::internal::DCHECK(), EmitDoubleBoundaryTest(), and v8::internal::Label::is_linked().
Referenced by GenerateBranches().
DeterminedAlready()
bool v8::internal::anonymous_namespace{regexp-compiler.cc}::DeterminedAlready (const QuickCheckDetails * quick_check, int offset)
Definition at line 2372 of file regexp-compiler.cc.
                                                                         {
  if (quick_check == nullptr) return false;
  if (offset >= quick_check->characters()) return false;
  return quick_check->positions(offset)->determines_perfectly;
}
References v8::internal::QuickCheckDetails::characters(), and v8::internal::QuickCheckDetails::positions().
Referenced by v8::internal::TextNode::TextEmitPass().
EmitAtomLetter()
bool v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitAtomLetter (Isolate * isolate, RegExpCompiler * compiler, base::uc16 c, Label * on_failure, int cp_offset, bool check, bool preloaded) [inline]
Definition at line 921 of file regexp-compiler.cc.
                                                       {
  RegExpMacroAssembler* macro_assembler = compiler->macro_assembler();
  bool one_byte = compiler->one_byte();
  unibrow::uchar chars[4];
  int length = GetCaseIndependentLetters(isolate, c, compiler, chars, 4);
  // The 0 and 1 case are handled by earlier passes.
  if (length <= 1) return false;
  // We may not need to check against the end of the input string
  // if this character lies before a character that matched.
  if (!preloaded) {
    macro_assembler->LoadCurrentCharacter(cp_offset, on_failure, check);
  }
  Label ok;
  switch (length) {
    case 2: {
      if (ShortCutEmitCharacterPair(macro_assembler, one_byte, chars[0],
                                    chars[1], on_failure)) {
      } else {
        macro_assembler->CheckCharacter(chars[0], &ok);
        macro_assembler->CheckNotCharacter(chars[1], on_failure);
        macro_assembler->Bind(&ok);
      }
      break;
    }
    case 4:
      macro_assembler->CheckCharacter(chars[3], &ok);
      [[fallthrough]];
    case 3:
      macro_assembler->CheckCharacter(chars[0], &ok);
      macro_assembler->CheckCharacter(chars[1], &ok);
      macro_assembler->CheckNotCharacter(chars[2], on_failure);
      macro_assembler->Bind(&ok);
      break;
    default:
      UNREACHABLE();
  }
  return true;
}
References v8::internal::RegExpMacroAssembler::Bind(), v8::internal::RegExpMacroAssembler::CheckCharacter(), v8::internal::RegExpMacroAssembler::CheckNotCharacter(), GetCaseIndependentLetters(), v8::internal::length, v8::internal::RegExpMacroAssembler::LoadCurrentCharacter(), v8::internal::RegExpCompiler::macro_assembler(), v8::internal::RegExpCompiler::one_byte(), ShortCutEmitCharacterPair(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::TextNode::TextEmitPass().
EmitAtomNonLetter()
bool v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitAtomNonLetter (Isolate * isolate, RegExpCompiler * compiler, base::uc16 c, Label * on_failure, int cp_offset, bool check, bool preloaded) [inline]
Definition at line 860 of file regexp-compiler.cc.
                                                          {
  RegExpMacroAssembler* macro_assembler = compiler->macro_assembler();
  bool one_byte = compiler->one_byte();
  unibrow::uchar chars[4];
  int length = GetCaseIndependentLetters(isolate, c, compiler, chars, 4);
  if (length < 1) {
    // This can't match. Must be an one-byte subject and a non-one-byte
    // character. We do not need to do anything since the one-byte pass
    // already handled this.
    CHECK(one_byte);
    return false; // Bounds not checked.
  }
  bool checked = false;
  // We handle the length > 1 case in a later pass.
  if (length == 1) {
    // GetCaseIndependentLetters promises not to return characters that can't
    // match because of the subject encoding. This case is already handled by
    // the one-byte pass.
    CHECK_IMPLIES(one_byte, chars[0] <= String::kMaxOneByteCharCodeU);
    if (!preloaded) {
      macro_assembler->LoadCurrentCharacter(cp_offset, on_failure, check);
      checked = check;
    }
    macro_assembler->CheckNotCharacter(chars[0], on_failure);
  }
  return checked;
}
References CHECK, CHECK_IMPLIES, v8::internal::RegExpMacroAssembler::CheckNotCharacter(), GetCaseIndependentLetters(), v8::internal::String::kMaxOneByteCharCodeU, v8::internal::length, v8::internal::RegExpMacroAssembler::LoadCurrentCharacter(), v8::internal::RegExpCompiler::macro_assembler(), and v8::internal::RegExpCompiler::one_byte().
Referenced by v8::internal::TextNode::TextEmitPass().
EmitBoundaryTest()
void v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitBoundaryTest (RegExpMacroAssembler * masm, int border, Label * fall_through, Label * above_or_equal, Label * below)
Definition at line 962 of file regexp-compiler.cc.
                                    {
  if (below != fall_through) {
    masm->CheckCharacterLT(border, below);
    if (above_or_equal != fall_through) masm->GoTo(above_or_equal);
  } else {
    masm->CheckCharacterGT(border - 1, above_or_equal);
  }
}
References v8::internal::below, v8::internal::RegExpMacroAssembler::CheckCharacterGT(), v8::internal::RegExpMacroAssembler::CheckCharacterLT(), and v8::internal::RegExpMacroAssembler::GoTo().
Referenced by GenerateBranches().
EmitClassRanges()
void v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitClassRanges (RegExpMacroAssembler * macro_assembler, RegExpClassRanges * cr, bool one_byte, Label * on_failure, int cp_offset, bool check_offset, bool preloaded, Zone * zone)
Definition at line 1250 of file regexp-compiler.cc.
                                 {
  ZoneList<CharacterRange>* ranges = cr->ranges(zone);
  CharacterRange::Canonicalize(ranges);
  // Now that all processing (like case-insensitivity) is done, clamp the
  // ranges to the set of ranges that may actually occur in the subject string.
  if (one_byte) CharacterRange::ClampToOneByte(ranges);
  const int ranges_length = ranges->length();
  if (ranges_length == 0) {
    if (!cr->is_negated()) {
      macro_assembler->GoTo(on_failure);
    }
    if (check_offset) {
      macro_assembler->CheckPosition(cp_offset, on_failure);
    }
    return;
  }
  const base::uc32 max_char = MaxCodeUnit(one_byte);
  if (ranges_length == 1 && ranges->at(0).IsEverything(max_char)) {
    if (cr->is_negated()) {
      macro_assembler->GoTo(on_failure);
    } else {
      // This is a common case hit by non-anchored expressions.
      if (check_offset) {
        macro_assembler->CheckPosition(cp_offset, on_failure);
      }
    }
    return;
  }
  if (!preloaded) {
    macro_assembler->LoadCurrentCharacter(cp_offset, on_failure, check_offset);
  }
  if (cr->is_standard(zone) && macro_assembler->CheckSpecialClassRanges(
                                   cr->standard_type(), on_failure)) {
    return;
  }
  static constexpr int kMaxRangesForInlineBranchGeneration = 16;
  if (ranges_length > kMaxRangesForInlineBranchGeneration) {
    // For large range sets, emit a more compact instruction sequence to avoid
    // a potentially problematic increase in code size.
    // Note the flipped logic below (we check InRange if negated, NotInRange if
    // not negated); this is necessary since the method falls through on
    // failure whereas we want to fall through on success.
    if (cr->is_negated()) {
      if (macro_assembler->CheckCharacterInRangeArray(ranges, on_failure)) {
        return;
      }
    } else {
      if (macro_assembler->CheckCharacterNotInRangeArray(ranges, on_failure)) {
        return;
      }
    }
  }
  // Generate a flat list of range boundaries for consumption by
  // GenerateBranches. See the comment on that function for how the list should
  // be structured
  ZoneList<base::uc32>* range_boundaries =
      zone->New<ZoneList<base::uc32>>(ranges_length * 2, zone);
  bool zeroth_entry_is_failure = !cr->is_negated();
  for (int i = 0; i < ranges_length; i++) {
    CharacterRange& range = ranges->at(i);
    if (range.from() == 0) {
      DCHECK_EQ(i, 0);
      zeroth_entry_is_failure = !zeroth_entry_is_failure;
    } else {
      range_boundaries->Add(range.from(), zone);
    }
    // `+ 1` to convert from inclusive to exclusive `to`.
    // [from, to] == [from, to+1[.
    range_boundaries->Add(range.to() + 1, zone);
  }
  int end_index = range_boundaries->length() - 1;
  if (range_boundaries->at(end_index) > max_char) {
    end_index--;
  }
  Label fall_through;
  GenerateBranches(macro_assembler, range_boundaries,
                   0, // start_index.
                   end_index,
                   0, // min_char.
                   max_char, &fall_through,
                   zeroth_entry_is_failure ? &fall_through : on_failure,
                   zeroth_entry_is_failure ? on_failure : &fall_through);
  macro_assembler->Bind(&fall_through);
}
References v8::internal::ZoneList< T >::Add(), v8::internal::ZoneList< T >::at(), v8::internal::RegExpMacroAssembler::Bind(), v8::internal::CharacterRange::Canonicalize(), v8::internal::RegExpMacroAssembler::CheckCharacterInRangeArray(), v8::internal::RegExpMacroAssembler::CheckCharacterNotInRangeArray(), v8::internal::RegExpMacroAssembler::CheckPosition(), v8::internal::RegExpMacroAssembler::CheckSpecialClassRanges(), v8::internal::CharacterRange::ClampToOneByte(), DCHECK_EQ, v8::internal::CharacterRange::from(), GenerateBranches(), v8::internal::RegExpMacroAssembler::GoTo(), v8::internal::RegExpClassRanges::is_negated(), v8::internal::RegExpClassRanges::is_standard(), v8::internal::ZoneList< T >::length(), v8::internal::RegExpMacroAssembler::LoadCurrentCharacter(), MaxCodeUnit(), v8::internal::Zone::New(), v8::internal::RegExpClassRanges::ranges(), v8::internal::RegExpClassRanges::standard_type(), and v8::internal::CharacterRange::to().
Referenced by v8::internal::TextNode::TextEmitPass().
EmitDoubleBoundaryTest()
void v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitDoubleBoundaryTest (RegExpMacroAssembler * masm, int first, int last, Label * fall_through, Label * in_range, Label * out_of_range)
Definition at line 973 of file regexp-compiler.cc.
                                                 {
  if (in_range == fall_through) {
    if (first == last) {
      masm->CheckNotCharacter(first, out_of_range);
    } else {
      masm->CheckCharacterNotInRange(first, last, out_of_range);
    }
  } else {
    if (first == last) {
      masm->CheckCharacter(first, in_range);
    } else {
      masm->CheckCharacterInRange(first, last, in_range);
    }
    if (out_of_range != fall_through) masm->GoTo(out_of_range);
  }
}
References v8::internal::RegExpMacroAssembler::CheckCharacter(), v8::internal::RegExpMacroAssembler::CheckCharacterInRange(), v8::internal::RegExpMacroAssembler::CheckCharacterNotInRange(), v8::internal::RegExpMacroAssembler::CheckNotCharacter(), and v8::internal::RegExpMacroAssembler::GoTo().
Referenced by CutOutRange(), and GenerateBranches().
EmitHat()
void v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitHat (RegExpCompiler * compiler, RegExpNode * on_success, Trace * trace)
Definition at line 2198 of file regexp-compiler.cc.
                                                                             {
  RegExpMacroAssembler* assembler = compiler->macro_assembler();
  // We will load the previous character into the current character register.
  Trace new_trace(*trace);
  new_trace.InvalidateCurrentCharacter();
  // A positive (> 0) cp_offset means we've already successfully matched a
  // non-empty-width part of the pattern, and thus cannot be at or before the
  // start of the subject string. We can thus skip both at-start and
  // bounds-checks when loading the one-character lookbehind.
  const bool may_be_at_or_before_subject_string_start =
      new_trace.cp_offset() <= 0;
  Label ok;
  if (may_be_at_or_before_subject_string_start) {
    // The start of input counts as a newline in this context, so skip to ok if
    // we are at the start.
    assembler->CheckAtStart(new_trace.cp_offset(), &ok);
  }
  // If we've already checked that we are not at the start of input, it's okay
  // to load the previous character without bounds checks.
  const bool can_skip_bounds_check = !may_be_at_or_before_subject_string_start;
  assembler->LoadCurrentCharacter(new_trace.cp_offset() - 1,
                                  new_trace.backtrack(), can_skip_bounds_check);
  if (!assembler->CheckSpecialClassRanges(StandardCharacterSet::kLineTerminator,
                                          new_trace.backtrack())) {
    // Newline means \n, \r, 0x2028 or 0x2029.
    if (!compiler->one_byte()) {
      assembler->CheckCharacterAfterAnd(0x2028, 0xFFFE, &ok);
    }
    assembler->CheckCharacter('\n', &ok);
    assembler->CheckNotCharacter('\r', new_trace.backtrack());
  }
  assembler->Bind(&ok);
  on_success->Emit(compiler, &new_trace);
}
References v8::internal::Trace::backtrack(), v8::internal::RegExpMacroAssembler::Bind(), v8::internal::RegExpMacroAssembler::CheckAtStart(), v8::internal::RegExpMacroAssembler::CheckCharacter(), v8::internal::RegExpMacroAssembler::CheckCharacterAfterAnd(), v8::internal::RegExpMacroAssembler::CheckNotCharacter(), v8::internal::RegExpMacroAssembler::CheckSpecialClassRanges(), v8::internal::Trace::cp_offset(), v8::internal::RegExpNode::Emit(), v8::internal::Trace::InvalidateCurrentCharacter(), v8::internal::kLineTerminator, v8::internal::RegExpMacroAssembler::LoadCurrentCharacter(), v8::internal::RegExpCompiler::macro_assembler(), and v8::internal::RegExpCompiler::one_byte().
Referenced by v8::internal::AssertionNode::Emit().
EmitSimpleCharacter()
bool v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitSimpleCharacter (Isolate * isolate, RegExpCompiler * compiler, base::uc16 c, Label * on_failure, int cp_offset, bool check, bool preloaded) [inline]
Definition at line 845 of file regexp-compiler.cc.
                                                            {
  RegExpMacroAssembler* assembler = compiler->macro_assembler();
  bool bound_checked = false;
  if (!preloaded) {
    assembler->LoadCurrentCharacter(cp_offset, on_failure, check);
    bound_checked = true;
  }
  assembler->CheckNotCharacter(c, on_failure);
  return bound_checked;
}
References v8::internal::RegExpMacroAssembler::CheckNotCharacter(), v8::internal::RegExpMacroAssembler::LoadCurrentCharacter(), and v8::internal::RegExpCompiler::macro_assembler().
Referenced by v8::internal::TextNode::TextEmitPass().
EmitUseLookupTable()
void v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitUseLookupTable (RegExpMacroAssembler * masm, ZoneList< base::uc32 > * ranges, uint32_t start_index, uint32_t end_index, base::uc32 min_char, Label * fall_through, Label * even_label, Label * odd_label)
Definition at line 994 of file regexp-compiler.cc.
                                          {
  static const uint32_t kSize = RegExpMacroAssembler::kTableSize;
  static const uint32_t kMask = RegExpMacroAssembler::kTableMask;
  base::uc32 base = (min_char & ~kMask);
  USE(base);
  // Assert that everything is on one kTableSize page.
  for (uint32_t i = start_index; i <= end_index; i++) {
    DCHECK_EQ(ranges->at(i) & ~kMask, base);
  }
  DCHECK(start_index == 0 || (ranges->at(start_index - 1) & ~kMask) <= base);
  char templ[kSize];
  Label* on_bit_set;
  Label* on_bit_clear;
  int bit;
  if (even_label == fall_through) {
    on_bit_set = odd_label;
    on_bit_clear = even_label;
    bit = 1;
  } else {
    on_bit_set = even_label;
    on_bit_clear = odd_label;
    bit = 0;
  }
  for (uint32_t i = 0; i < (ranges->at(start_index) & kMask) && i < kSize;
       i++) {
    templ[i] = bit;
  }
  uint32_t j = 0;
  bit ^= 1;
  for (uint32_t i = start_index; i < end_index; i++) {
    for (j = (ranges->at(i) & kMask); j < (ranges->at(i + 1) & kMask); j++) {
      templ[j] = bit;
    }
    bit ^= 1;
  }
  for (uint32_t i = j; i < kSize; i++) {
    templ[i] = bit;
  }
  Factory* factory = masm->isolate()->factory();
  // TODO(erikcorry): Cache these.
  Handle<ByteArray> ba = factory->NewByteArray(kSize, AllocationType::kOld);
  for (uint32_t i = 0; i < kSize; i++) {
    ba->set(i, templ[i]);
  }
  masm->CheckBitInTable(ba, on_bit_set);
  if (on_bit_clear != fall_through) masm->GoTo(on_bit_clear);
}
References v8::internal::ZoneList< T >::at(), v8::internal::RegExpMacroAssembler::CheckBitInTable(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Isolate::factory(), v8::internal::RegExpMacroAssembler::GoTo(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::RegExpMacroAssembler::isolate(), v8::internal::kOld, v8::internal::RegExpMacroAssembler::kTableMask, v8::internal::RegExpMacroAssembler::kTableSize, v8::internal::FactoryBase< Impl >::NewByteArray(), and USE.
Referenced by GenerateBranches().
EmitWordCheck()
void v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitWordCheck (RegExpMacroAssembler * assembler, Label * word, Label * non_word, bool fall_through_on_word)
Definition at line 2174 of file regexp-compiler.cc.
                                                               {
  if (assembler->CheckSpecialClassRanges(
          fall_through_on_word ? StandardCharacterSet::kWord
                               : StandardCharacterSet::kNotWord,
          fall_through_on_word ? non_word : word)) {
    // Optimized implementation available.
    return;
  }
  assembler->CheckCharacterGT('z', non_word);
  assembler->CheckCharacterLT('0', non_word);
  assembler->CheckCharacterGT('a' - 1, word);
  assembler->CheckCharacterLT('9' + 1, word);
  assembler->CheckCharacterLT('A', non_word);
  assembler->CheckCharacterLT('Z' + 1, word);
  if (fall_through_on_word) {
    assembler->CheckNotCharacter('_', non_word);
  } else {
    assembler->CheckCharacter('_', word);
  }
}
References v8::internal::RegExpMacroAssembler::CheckCharacter(), v8::internal::RegExpMacroAssembler::CheckCharacterGT(), v8::internal::RegExpMacroAssembler::CheckCharacterLT(), v8::internal::RegExpMacroAssembler::CheckNotCharacter(), v8::internal::RegExpMacroAssembler::CheckSpecialClassRanges(), v8::internal::kNotWord, and v8::internal::kWord.
Referenced by v8::internal::AssertionNode::BacktrackIfPrevious(), and v8::internal::AssertionNode::EmitBoundaryCheck().
GenerateBranches()
void v8::internal::anonymous_namespace{regexp-compiler.cc}::GenerateBranches (RegExpMacroAssembler * masm, ZoneList< base::uc32 > * ranges, uint32_t start_index, uint32_t end_index, base::uc32 min_char, base::uc32 max_char, Label * fall_through, Label * even_label, Label * odd_label)
Definition at line 1138 of file regexp-compiler.cc.
                                        {
  DCHECK_LE(min_char, String::kMaxUtf16CodeUnit);
  DCHECK_LE(max_char, String::kMaxUtf16CodeUnit);
  base::uc32 first = ranges->at(start_index);
  base::uc32 last = ranges->at(end_index) - 1;
  DCHECK_LT(min_char, first);
  // Just need to test if the character is before or on-or-after
  // a particular character.
  if (start_index == end_index) {
    EmitBoundaryTest(masm, first, fall_through, even_label, odd_label);
    return;
  }
  // Another almost trivial case: There is one interval in the middle that is
  // different from the end intervals.
  if (start_index + 1 == end_index) {
    EmitDoubleBoundaryTest(masm, first, last, fall_through, even_label,
                           odd_label);
    return;
  }
  // It's not worth using table lookup if there are very few intervals in the
  // character class.
  if (end_index - start_index <= 6) {
    // It is faster to test for individual characters, so we look for those
    // first, then try arbitrary ranges in the second round.
    static uint32_t kNoCutIndex = -1;
    uint32_t cut = kNoCutIndex;
    for (uint32_t i = start_index; i < end_index; i++) {
      if (ranges->at(i) == ranges->at(i + 1) - 1) {
        cut = i;
        break;
      }
    }
    if (cut == kNoCutIndex) cut = start_index;
    CutOutRange(masm, ranges, start_index, end_index, cut, even_label,
                odd_label);
    DCHECK_GE(end_index - start_index, 2);
    GenerateBranches(masm, ranges, start_index + 1, end_index - 1, min_char,
                     max_char, fall_through, even_label, odd_label);
    return;
  }
  // If there are a lot of intervals in the regexp, then we will use tables to
  // determine whether the character is inside or outside the character class.
  static const int kBits = RegExpMacroAssembler::kTableSizeBits;
  if ((max_char >> kBits) == (min_char >> kBits)) {
    EmitUseLookupTable(masm, ranges, start_index, end_index, min_char,
                       fall_through, even_label, odd_label);
    return;
  }
  if ((min_char >> kBits) != first >> kBits) {
    masm->CheckCharacterLT(first, odd_label);
    GenerateBranches(masm, ranges, start_index + 1, end_index, first, max_char,
                     fall_through, odd_label, even_label);
    return;
  }
  uint32_t new_start_index = 0;
  uint32_t new_end_index = 0;
  base::uc32 border = 0;
  SplitSearchSpace(ranges, start_index, end_index, &new_start_index,
                   &new_end_index, &border);
  Label handle_rest;
  Label* above = &handle_rest;
  if (border == last + 1) {
    // We didn't find any section that started after the limit, so everything
    // above the border is one of the terminal labels.
    above = (end_index & 1) != (start_index & 1) ? odd_label : even_label;
    DCHECK(new_end_index == end_index - 1);
  }
  DCHECK_LE(start_index, new_end_index);
  DCHECK_LE(new_start_index, end_index);
  DCHECK_LT(start_index, new_start_index);
  DCHECK_LT(new_end_index, end_index);
  DCHECK(new_end_index + 1 == new_start_index ||
         (new_end_index + 2 == new_start_index &&
          border == ranges->at(new_end_index + 1)));
  DCHECK_LT(min_char, border - 1);
  DCHECK_LT(border, max_char);
  DCHECK_LT(ranges->at(new_end_index), border);
  DCHECK(border < ranges->at(new_start_index) ||
         (border == ranges->at(new_start_index) &&
          new_start_index == end_index && new_end_index == end_index - 1 &&
          border == last + 1));
  DCHECK(new_start_index == 0 || border >= ranges->at(new_start_index - 1));
  masm->CheckCharacterGT(border - 1, above);
  Label dummy;
  GenerateBranches(masm, ranges, start_index, new_end_index, min_char,
                   border - 1, &dummy, even_label, odd_label);
  if (handle_rest.is_linked()) {
    masm->Bind(&handle_rest);
    bool flip = (new_start_index & 1) != (start_index & 1);
    GenerateBranches(masm, ranges, new_start_index, end_index, border, max_char,
                     &dummy, flip ? odd_label : even_label,
                     flip ? even_label : odd_label);
  }
}
References v8::internal::above, v8::internal::ZoneList< T >::at(), v8::internal::RegExpMacroAssembler::Bind(), v8::internal::RegExpMacroAssembler::CheckCharacterGT(), v8::internal::RegExpMacroAssembler::CheckCharacterLT(), CutOutRange(), v8::internal::DCHECK(), DCHECK_GE, DCHECK_LE, DCHECK_LT, EmitBoundaryTest(), EmitDoubleBoundaryTest(), EmitUseLookupTable(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::Label::is_linked(), v8::internal::String::kMaxUtf16CodeUnit, v8::internal::RegExpMacroAssembler::kTableSizeBits, and SplitSearchSpace().
Referenced by EmitClassRanges().
GetCaseIndependentLetters()
int v8::internal::anonymous_namespace{regexp-compiler.cc}::GetCaseIndependentLetters (Isolate * isolate, base::uc16 character, RegExpCompiler * compiler, unibrow::uchar * letters, int letter_length)
Definition at line 761 of file regexp-compiler.cc.
                                                 {
  bool one_byte_subject = compiler->one_byte();
  bool unicode = IsEitherUnicode(compiler->flags());
  static const base::uc16 kMaxAscii = 0x7f;
  if (!unicode && character <= kMaxAscii) {
    // Fast case for common characters.
    base::uc16 upper = character & ~0x20;
    if ('A' <= upper && upper <= 'Z') {
      letters[0] = upper;
      letters[1] = upper | 0x20;
      return 2;
    }
    letters[0] = character;
    return 1;
  }
#ifdef V8_INTL_SUPPORT
  if (!unicode && RegExpCaseFolding::IgnoreSet().contains(character)) {
    if (one_byte_subject && character > String::kMaxOneByteCharCode) {
      // This function promises not to return a character that is impossible
      // for the subject encoding.
      return 0;
    }
    letters[0] = character;
    DCHECK(ContainsOnlyUtf16CodeUnits(letters, 1));
    return 1;
  }
  bool in_special_add_set =
      RegExpCaseFolding::SpecialAddSet().contains(character);
  icu::UnicodeSet set;
  set.add(character);
  set = set.closeOver(unicode ? USET_SIMPLE_CASE_INSENSITIVE
                              : USET_CASE_INSENSITIVE);
  UChar32 canon = 0;
  if (in_special_add_set && !unicode) {
    canon = RegExpCaseFolding::Canonicalize(character);
  }
  int32_t range_count = set.getRangeCount();
  int items = 0;
  for (int32_t i = 0; i < range_count; i++) {
    UChar32 start = set.getRangeStart(i);
    UChar32 end = set.getRangeEnd(i);
    CHECK(end - start + items <= letter_length);
    for (UChar32 cu = start; cu <= end; cu++) {
      if (one_byte_subject && cu > String::kMaxOneByteCharCode) continue;
      if (!unicode && in_special_add_set &&
          RegExpCaseFolding::Canonicalize(cu) != canon) {
        continue;
      }
      letters[items++] = static_cast<unibrow::uchar>(cu);
    }
  }
  DCHECK(ContainsOnlyUtf16CodeUnits(letters, items));
  return items;
#else
  int length =
      isolate->jsregexp_uncanonicalize()->get(character, '\0', letters);
  // Unibrow returns 0 or 1 for characters where case independence is
  // trivial.
  if (length == 0) {
    letters[0] = character;
    length = 1;
  }
  if (one_byte_subject) {
    int new_length = 0;
    for (int i = 0; i < length; i++) {
      if (letters[i] <= String::kMaxOneByteCharCode) {
        letters[new_length++] = letters[i];
      }
    }
    length = new_length;
  }
  DCHECK(ContainsOnlyUtf16CodeUnits(letters, length));
  return length;
#endif // V8_INTL_SUPPORT
}
References v8::internal::character, CHECK, v8::base::contains(), v8::internal::DCHECK(), v8::internal::compiler::end(), v8::internal::RegExpCompiler::flags(), unibrow::Mapping< T, size >::get(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::IsEitherUnicode(), v8::internal::Isolate::jsregexp_uncanonicalize(), v8::internal::String::kMaxOneByteCharCode, v8::internal::length, and v8::internal::RegExpCompiler::one_byte().
Referenced by EmitAtomLetter(), EmitAtomNonLetter(), v8::internal::TextNode::FillInBMInfo(), v8::internal::TextNode::FilterOneByte(), v8::internal::TextNode::GetQuickCheckDetails(), and v8::internal::TextNode::TextEmitPass().
MaxCodeUnit()
constexpr base::uc32 v8::internal::anonymous_namespace{regexp-compiler.cc}::MaxCodeUnit (const bool one_byte) [constexpr]
Definition at line 179 of file regexp-compiler.cc.
                                                    {
  static_assert(String::kMaxOneByteCharCodeU <=
                std::numeric_limits<uint16_t>::max());
  static_assert(String::kMaxUtf16CodeUnitU <=
                std::numeric_limits<uint16_t>::max());
  return one_byte ? String::kMaxOneByteCharCodeU : String::kMaxUtf16CodeUnitU;
}
References v8::internal::String::kMaxOneByteCharCodeU, and v8::internal::String::kMaxUtf16CodeUnitU.
Referenced by CharMask(), EmitClassRanges(), and v8::internal::TextNode::GetSuccessorOfOmnivorousTextNode().
RangesContainLatin1Equivalents()
bool v8::internal::anonymous_namespace{regexp-compiler.cc}::RangesContainLatin1Equivalents (ZoneList< CharacterRange > * ranges)
Definition at line 1930 of file regexp-compiler.cc.
                                                                      {
  for (int i = 0; i < ranges->length(); i++) {
    // TODO(dcarney): this could be a lot more efficient.
    if (RangeContainsLatin1Equivalents(ranges->at(i))) return true;
  }
  return false;
}
References v8::internal::ZoneList< T >::at(), v8::internal::ZoneList< T >::length(), and v8::internal::RangeContainsLatin1Equivalents().
Referenced by v8::internal::TextNode::FilterOneByte().
ShortCutEmitCharacterPair()
bool v8::internal::anonymous_namespace{regexp-compiler.cc}::ShortCutEmitCharacterPair (RegExpMacroAssembler * macro_assembler, bool one_byte, base::uc16 c1, base::uc16 c2, Label * on_failure)
Definition at line 890 of file regexp-compiler.cc.
                                                  {
  const uint32_t char_mask = CharMask(one_byte);
  base::uc16 exor = c1 ^ c2;
  // Check whether exor has only one bit set.
  if (((exor - 1) & exor) == 0) {
    // If c1 and c2 differ only by one bit.
    // Ecma262UnCanonicalize always gives the highest number last.
    DCHECK(c2 > c1);
    base::uc16 mask = char_mask ^ exor;
    macro_assembler->CheckNotCharacterAfterAnd(c1, mask, on_failure);
    return true;
  }
  DCHECK(c2 > c1);
  base::uc16 diff = c2 - c1;
  if (((diff - 1) & diff) == 0 && c1 >= diff) {
    // If the characters differ by 2^n but don't differ by one bit then
    // subtract the difference from the found character, then do the or
    // trick. We avoid the theoretical case where negative numbers are
    // involved in order to simplify code generation.
    base::uc16 mask = char_mask ^ diff;
    macro_assembler->CheckNotCharacterAfterMinusAnd(c1 - diff, diff, mask,
                                                    on_failure);
    return true;
  }
  return false;
}
References CharMask(), v8::internal::RegExpMacroAssembler::CheckNotCharacterAfterAnd(), v8::internal::RegExpMacroAssembler::CheckNotCharacterAfterMinusAnd(), and v8::internal::DCHECK().
Referenced by EmitAtomLetter().
SmearBitsRight()
uint32_t v8::internal::anonymous_namespace{regexp-compiler.cc}::SmearBitsRight (uint32_t v) [inline]
Definition at line 1475 of file regexp-compiler.cc.
                                           {
  v |= v >> 1;
  v |= v >> 2;
  v |= v >> 4;
  v |= v >> 8;
  v |= v >> 16;
  return v;
}
Referenced by v8::internal::TextNode::GetQuickCheckDetails().
SplitSearchSpace()
void v8::internal::anonymous_namespace{regexp-compiler.cc}::SplitSearchSpace (ZoneList< base::uc32 > * ranges, uint32_t start_index, uint32_t end_index, uint32_t * new_start_index, uint32_t * new_end_index, base::uc32 * border)
Definition at line 1072 of file regexp-compiler.cc.
                                                                 {
  static const uint32_t kSize = RegExpMacroAssembler::kTableSize;
  static const uint32_t kMask = RegExpMacroAssembler::kTableMask;
  base::uc32 first = ranges->at(start_index);
  base::uc32 last = ranges->at(end_index) - 1;
  *new_start_index = start_index;
  *border = (ranges->at(start_index) & ~kMask) + kSize;
  while (*new_start_index < end_index) {
    if (ranges->at(*new_start_index) > *border) break;
    (*new_start_index)++;
  }
  // new_start_index is the index of the first edge that is beyond the
  // current kSize space.
  // For very large search spaces we do a binary chop search of the non-Latin1
  // space instead of just going to the end of the current kSize space. The
  // heuristics are complicated a little by the fact that any 128-character
  // encoding space can be quickly tested with a table lookup, so we don't
  // wish to do binary chop search at a smaller granularity than that. A
  // 128-character space can take up a lot of space in the ranges array if,
  // for example, we only want to match every second character (eg. the lower
  // case characters on some Unicode pages).
  uint32_t binary_chop_index = (end_index + start_index) / 2;
  // The first test ensures that we get to the code that handles the Latin1
  // range with a single not-taken branch, speeding up this important
  // character range (even non-Latin1 charset-based text has spaces and
  // punctuation).
  if (*border - 1 > String::kMaxOneByteCharCode && // Latin1 case.
      end_index - start_index > (*new_start_index - start_index) * 2 &&
      last - first > kSize * 2 && binary_chop_index > *new_start_index &&
      ranges->at(binary_chop_index) >= first + 2 * kSize) {
    uint32_t scan_forward_for_section_border = binary_chop_index;
    uint32_t new_border = (ranges->at(binary_chop_index) | kMask) + 1;
    while (scan_forward_for_section_border < end_index) {
      if (ranges->at(scan_forward_for_section_border) > new_border) {
        *new_start_index = scan_forward_for_section_border;
        *border = new_border;
        break;
      }
      scan_forward_for_section_border++;
    }
  }
  DCHECK(*new_start_index > start_index);
  *new_end_index = *new_start_index - 1;
  if (ranges->at(*new_end_index) == *border) {
    (*new_end_index)--;
  }
  if (*border >= ranges->at(end_index)) {
    *border = ranges->at(end_index);
    *new_start_index = end_index; // Won't be used.
    *new_end_index = end_index - 1;
  }
}
References v8::internal::ZoneList< T >::at(), v8::internal::DCHECK(), v8::internal::String::kMaxOneByteCharCode, v8::internal::RegExpMacroAssembler::kTableMask, and v8::internal::RegExpMacroAssembler::kTableSize.
Referenced by GenerateBranches().
UpdateBoundsCheck()
void v8::internal::anonymous_namespace{regexp-compiler.cc}::UpdateBoundsCheck (int index, int * checked_up_to)
Definition at line 2378 of file regexp-compiler.cc.
                                                      {
  if (index > *checked_up_to) {
    *checked_up_to = index;
  }
}
References v8::internal::index.
Referenced by v8::internal::TextNode::TextEmitPass().