v8::internal::anonymous_namespace{snapshot.cc} Namespace Reference
Classes
class SnapshotImpl
Functions
base::Vector< const uint8_t > ExtractData (const v8::StartupData *snapshot, uint32_t start_offset, uint32_t end_offset)
bool RunExtraCode (v8::Isolate *isolate, v8::Local< v8::Context > context, const char *utf8_source, const char *name)
void ConvertSerializedObjectsToFixedArray (Isolate *isolate)
void ConvertSerializedObjectsToFixedArray (Isolate *isolate, DirectHandle< NativeContext > context)
Function Documentation
ConvertSerializedObjectsToFixedArray() [1/2]
void v8::internal::anonymous_namespace{snapshot.cc}::ConvertSerializedObjectsToFixedArray (Isolate * isolate)
Definition at line 1010 of file snapshot.cc.
                                                            {
  if (!IsArrayList(isolate->heap()->serialized_objects())) {
    isolate->heap()->SetSerializedObjects(
        ReadOnlyRoots(isolate).empty_fixed_array());
  } else {
    DirectHandle<ArrayList> list(
        Cast<ArrayList>(isolate->heap()->serialized_objects()), isolate);
    DirectHandle<FixedArray> elements = ArrayList::ToFixedArray(isolate, list);
    isolate->heap()->SetSerializedObjects(*elements);
  }
}
References v8::internal::Isolate::heap(), v8::internal::Heap::SetSerializedObjects(), and v8::internal::ArrayList::ToFixedArray().
ConvertSerializedObjectsToFixedArray() [2/2]
void v8::internal::anonymous_namespace{snapshot.cc}::ConvertSerializedObjectsToFixedArray (Isolate * isolate, DirectHandle< NativeContext > context)
Definition at line 1022 of file snapshot.cc.
                                                                               {
  if (!IsArrayList(context->serialized_objects())) {
    context->set_serialized_objects(ReadOnlyRoots(isolate).empty_fixed_array());
  } else {
    DirectHandle<ArrayList> list(Cast<ArrayList>(context->serialized_objects()),
                                 isolate);
    DirectHandle<FixedArray> elements = ArrayList::ToFixedArray(isolate, list);
    context->set_serialized_objects(*elements);
  }
}
References v8::internal::ArrayList::ToFixedArray().
Referenced by v8::internal::SnapshotCreatorImpl::CreateBlob().
ExtractData()
base::Vector<const uint8_t> v8::internal::anonymous_namespace{snapshot.cc}::ExtractData (const v8::StartupData * snapshot, uint32_t start_offset, uint32_t end_offset)
Definition at line 678 of file snapshot.cc.
                                                             {
  CHECK_LT(start_offset, end_offset);
  CHECK_LT(end_offset, snapshot->raw_size);
  uint32_t length = end_offset - start_offset;
  const uint8_t* data =
      reinterpret_cast<const uint8_t*>(snapshot->data + start_offset);
  return base::Vector<const uint8_t>(data, length);
}
References CHECK_LT, v8::StartupData::data, v8::internal::length, and v8::StartupData::raw_size.
Referenced by v8::internal::anonymous_namespace{snapshot.cc}::SnapshotImpl::ExtractReadOnlyData(), v8::internal::anonymous_namespace{snapshot.cc}::SnapshotImpl::ExtractSharedHeapData(), and v8::internal::anonymous_namespace{snapshot.cc}::SnapshotImpl::ExtractStartupData().
RunExtraCode()
bool v8::internal::anonymous_namespace{snapshot.cc}::RunExtraCode (v8::Isolate * isolate, v8::Local< v8::Context > context, const char * utf8_source, const char * name)
Definition at line 755 of file snapshot.cc.
                                                             {
  v8::Context::Scope context_scope(context);
  v8::TryCatch try_catch(isolate);
  v8::Local<v8::String> source_string;
  if (!v8::String::NewFromUtf8(isolate, utf8_source).ToLocal(&source_string)) {
    return false;
  }
  v8::Local<v8::String> resource_name =
      v8::String::NewFromUtf8(isolate, name).ToLocalChecked();
  v8::ScriptOrigin origin(resource_name);
  v8::ScriptCompiler::Source source(source_string, origin);
  v8::Local<v8::Script> script;
  if (!v8::ScriptCompiler::Compile(context, &source).ToLocal(&script)) {
    return false;
  }
  if (script->Run(context).IsEmpty()) return false;
  CHECK(!try_catch.HasCaught());
  return true;
}
References CHECK, v8::ScriptCompiler::Compile(), v8::TryCatch::HasCaught(), v8::internal::name, v8::String::NewFromUtf8(), and v8::internal::script.
Referenced by v8::internal::CreateSnapshotDataBlobInternal(), and v8::internal::WarmUpSnapshotDataBlobInternal().