v8::internal::anonymous_namespace{builtins-riscv.cc} Namespace Reference
Classes
class RegisterAllocator
Enumerations
enum class ArgumentsElementType { kRaw
, kHandle
 }
enum class OsrSourceTier { kInterpreter
, kBaseline
 }
Functions
void Generate_PushArguments (MacroAssembler *masm, Register array, Register argc, Register scratch, Register scratch2, ArgumentsElementType element_type)
void Generate_JSBuiltinsConstructStubHelper (MacroAssembler *masm)
void Generate_JSEntryVariant (MacroAssembler *masm, StackFrame::Type type, Builtin entry_trampoline)
void ResetSharedFunctionInfoAge (MacroAssembler *masm, Register sfi)
void ResetJSFunctionAge (MacroAssembler *masm, Register js_function, Register scratch)
void ResetFeedbackVectorOsrUrgency (MacroAssembler *masm, Register feedback_vector, Register scratch)
void NewImplicitReceiver (MacroAssembler *masm)
void Generate_ContinueToBuiltinHelper (MacroAssembler *masm, bool javascript_builtin, bool with_result)
void Generate_OSREntry (MacroAssembler *masm, Register entry_address, Operand offset=Operand(0))
void OnStackReplacement (MacroAssembler *masm, OsrSourceTier source, Register maybe_target_code, Register expected_param_count)
void Generate_AllocateSpaceAndShiftExistingArguments (MacroAssembler *masm, Register count, Register argc_in_out, Register pointer_to_new_space_out)
void Generate_PushBoundArguments (MacroAssembler *masm)
void SwitchSimulatorStackLimit (MacroAssembler *masm)
void SwitchToTheCentralStackIfNeeded (MacroAssembler *masm, Register argc_input, Register target_input, Register argv_input)
void SwitchFromTheCentralStackIfNeeded (MacroAssembler *masm)
void SwitchStackState (MacroAssembler *masm, Register stack, Register tmp, wasm::JumpBuffer::StackState old_state, wasm::JumpBuffer::StackState new_state)
void SwitchStackPointerAndSimulatorStackLimit (MacroAssembler *masm, Register stack)
void FillJumpBuffer (MacroAssembler *masm, Register stack, Label *pc, Register tmp)
void LoadJumpBuffer (MacroAssembler *masm, Register stack, bool load_pc, Register tmp, wasm::JumpBuffer::StackState expected_state)
void SwitchStacks (MacroAssembler *masm, Register old_stack, bool return_switch, Register tmp, const std::initializer_list< Register > keep)
void ReloadParentStack (MacroAssembler *masm, Register return_reg, Register return_value, Register context, Register tmp1, Register tmp2, Register tmp3)
void RestoreParentSuspender (MacroAssembler *masm, Register tmp1)
void ResetStackSwitchFrameStackSlots (MacroAssembler *masm)
void LoadTargetJumpBuffer (MacroAssembler *masm, Register target_stack, Register tmp, wasm::JumpBuffer::StackState expected_state)
void Generate_WasmResumeHelper (MacroAssembler *masm, wasm::OnResume on_resume)
void SwitchToAllocatedStack (MacroAssembler *masm, RegisterAllocator &regs, Register wasm_instance, Register wrapper_buffer, Register &original_fp, Register &new_wrapper_buffer, Label *suspend)
void GetContextFromImplicitArg (MacroAssembler *masm, Register data, Register scratch)
void SwitchBackAndReturnPromise (MacroAssembler *masm, RegisterAllocator &regs, wasm::Promise mode, Label *return_promise)
void GenerateExceptionHandlingLandingPad (MacroAssembler *masm, RegisterAllocator &regs, Label *return_promise)
void JSToWasmWrapperHelper (MacroAssembler *masm, wasm::Promise mode)
void Generate_DeoptimizationEntry (MacroAssembler *masm, DeoptimizeKind deopt_kind)
Variables
static constexpr Register kOldSPRegister = s9
static constexpr Register kSwitchFlagRegister = s10
Enumeration Type Documentation
ArgumentsElementType
enum v8::internal::anonymous_namespace{builtins-riscv.cc}::ArgumentsElementType [strong]
Enumerator
kRaw
kHandle
Definition at line 49 of file builtins-riscv.cc.
                                {
  kRaw, // Push arguments as they are.
  kHandle // Dereference arguments before pushing.
};
OsrSourceTier
enum v8::internal::anonymous_namespace{builtins-riscv.cc}::OsrSourceTier [strong]
Enumerator
kInterpreter
kBaseline
Definition at line 1985 of file builtins-riscv.cc.
                         {
  kInterpreter,
  kBaseline,
};
Function Documentation
FillJumpBuffer()
void v8::internal::anonymous_namespace{builtins-riscv.cc}::FillJumpBuffer (MacroAssembler * masm, Register stack, Label * pc, Register tmp)
Definition at line 3629 of file builtins-riscv.cc.
                                  {
  ASM_CODE_COMMENT(masm);
  __ mv(tmp, sp);
  __ StoreWord(tmp, MemOperand(stack, wasm::kStackSpOffset));
  __ StoreWord(fp, MemOperand(stack, wasm::kStackFpOffset));
  __ LoadStackLimit(tmp, StackLimitKind::kRealStackLimit);
  __ StoreWord(tmp, MemOperand(stack, wasm::kStackLimitOffset));
  __ LoadAddress(tmp, pc);
  __ StoreWord(tmp, MemOperand(stack, wasm::kStackPcOffset));
}
References __, ASM_CODE_COMMENT, v8::internal::kRealStackLimit, v8::internal::wasm::kStackFpOffset, v8::internal::wasm::kStackLimitOffset, v8::internal::wasm::kStackPcOffset, v8::internal::wasm::kStackSpOffset, and v8::internal::stack.
Referenced by Generate_WasmResumeHelper(), and SwitchToAllocatedStack().
Generate_AllocateSpaceAndShiftExistingArguments()
void v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_AllocateSpaceAndShiftExistingArguments (MacroAssembler * masm, Register count, Register argc_in_out, Register pointer_to_new_space_out)
Definition at line 2393 of file builtins-riscv.cc.
                                       {
  UseScratchRegisterScope temps(masm);
  Register scratch1 = temps.Acquire();
  Register scratch2 = temps.Acquire();
  Register scratch3 = temps.Acquire();
  DCHECK(!AreAliased(count, argc_in_out, pointer_to_new_space_out, scratch1,
                     scratch2));
  Register old_sp = scratch1;
  Register new_space = scratch2;
  __ mv(old_sp, sp);
  __ slli(new_space, count, kSystemPointerSizeLog2);
  __ SubWord(sp, sp, Operand(new_space));
  Register end = scratch2;
  Register value = scratch3;
  Register dest = pointer_to_new_space_out;
  __ mv(dest, sp);
  __ CalcScaledAddress(end, old_sp, argc_in_out, kSystemPointerSizeLog2);
  Label loop, done;
  __ Branch(&done, ge, old_sp, Operand(end));
  __ bind(&loop);
  __ LoadWord(value, MemOperand(old_sp, 0));
  __ StoreWord(value, MemOperand(dest, 0));
  __ AddWord(old_sp, old_sp, Operand(kSystemPointerSize));
  __ AddWord(dest, dest, Operand(kSystemPointerSize));
  __ Branch(&loop, lt, old_sp, Operand(end));
  __ bind(&done);
  // Update total number of arguments.
  __ AddWord(argc_in_out, argc_in_out, count);
}
References __, v8::internal::UseScratchRegisterScope::Acquire(), v8::internal::AreAliased(), v8::internal::DCHECK(), v8::internal::compiler::end(), v8::internal::ge, v8::internal::kSystemPointerSize, v8::internal::kSystemPointerSizeLog2, v8::internal::lt, and v8::internal::value.
Referenced by v8::internal::Builtins::Generate_CallOrConstructForwardVarargs(), and v8::internal::Builtins::Generate_CallOrConstructVarargs().
Generate_ContinueToBuiltinHelper()
void v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_ContinueToBuiltinHelper (MacroAssembler * masm, bool javascript_builtin, bool with_result)
Definition at line 1890 of file builtins-riscv.cc.
                                                        {
  const RegisterConfiguration* config(RegisterConfiguration::Default());
  int allocatable_register_count = config->num_allocatable_general_registers();
  UseScratchRegisterScope temp(masm);
  Register scratch = temp.Acquire();
  if (with_result) {
    if (javascript_builtin) {
      __ Move(scratch, a0);
    } else {
      // Overwrite the hole inserted by the deoptimizer with the return value
      // from the LAZY deopt point.
      __ StoreWord(
          a0, MemOperand(
                  sp, config->num_allocatable_general_registers() *
                              kSystemPointerSize +
                          BuiltinContinuationFrameConstants::kFixedFrameSize));
    }
  }
  for (int i = allocatable_register_count - 1; i >= 0; --i) {
    int code = config->GetAllocatableGeneralCode(i);
    __ Pop(Register::from_code(code));
    if (javascript_builtin && code == kJavaScriptCallArgCountRegister.code()) {
      __ SmiUntag(Register::from_code(code));
    }
  }
  if (with_result && javascript_builtin) {
    // Overwrite the hole inserted by the deoptimizer with the return value from
    // the LAZY deopt point. t0 contains the arguments count, the return value
    // from LAZY is always the last argument.
    constexpr int return_value_offset =
        BuiltinContinuationFrameConstants::kFixedSlotCount -
        kJSArgcReceiverSlots;
    __ AddWord(a0, a0, Operand(return_value_offset));
    __ CalcScaledAddress(t0, sp, a0, kSystemPointerSizeLog2);
    __ StoreWord(scratch, MemOperand(t0));
    // Recover arguments count.
    __ SubWord(a0, a0, Operand(return_value_offset));
  }
  __ LoadWord(
      fp,
      MemOperand(sp, BuiltinContinuationFrameConstants::kFixedFrameSizeFromFp));
  // Load builtin index (stored as a Smi) and use it to get the builtin start
  // address from the builtins table.
  __ Pop(t6);
  __ AddWord(sp, sp,
             Operand(BuiltinContinuationFrameConstants::kFixedFrameSizeFromFp));
  __ Pop(ra);
  __ LoadEntryFromBuiltinIndex(t6, t6);
  __ Jump(t6);
}
References __, v8::internal::UseScratchRegisterScope::Acquire(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), code, v8::internal::RegisterConfiguration::Default(), v8::internal::Register::from_code(), v8::internal::RegisterConfiguration::GetAllocatableGeneralCode(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::TypedFrameConstants::kFixedFrameSize, v8::internal::TypedFrameConstants::kFixedFrameSizeFromFp, v8::internal::TypedFrameConstants::kFixedSlotCount, v8::internal::kJavaScriptCallArgCountRegister, v8::internal::kJSArgcReceiverSlots, v8::internal::kSystemPointerSize, v8::internal::kSystemPointerSizeLog2, v8::internal::RegisterConfiguration::num_allocatable_general_registers(), and v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::SmiUntag().
Generate_DeoptimizationEntry()
void v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_DeoptimizationEntry (MacroAssembler * masm, DeoptimizeKind deopt_kind)
Definition at line 4792 of file builtins-riscv.cc.
                                                             {
  Isolate* isolate = masm->isolate();
  // Unlike on ARM we don't save all the registers, just the useful ones.
  // For the rest, there are gaps on the stack, so the offsets remain the same.
  const int kNumberOfRegisters = Register::kNumRegisters;
  RegList restored_regs = kJSCallerSaved | kCalleeSaved;
  RegList saved_regs = restored_regs | sp | ra;
  const int kDoubleRegsSize = kDoubleSize * DoubleRegister::kNumRegisters;
  // Save all double FPU registers before messing with them.
  __ SubWord(sp, sp, Operand(kDoubleRegsSize));
  const RegisterConfiguration* config = RegisterConfiguration::Default();
  for (int i = 0; i < config->num_allocatable_double_registers(); ++i) {
    int code = config->GetAllocatableDoubleCode(i);
    const DoubleRegister fpu_reg = DoubleRegister::from_code(code);
    int offset = code * kDoubleSize;
    __ StoreDouble(fpu_reg, MemOperand(sp, offset));
  }
  // Push saved_regs (needed to populate FrameDescription::registers_).
  // Leave gaps for other registers.
  __ SubWord(sp, sp, kNumberOfRegisters * kSystemPointerSize);
  for (int16_t i = kNumberOfRegisters - 1; i >= 0; i--) {
    if ((saved_regs.bits() & (1 << i)) != 0) {
      __ StoreWord(ToRegister(i), MemOperand(sp, kSystemPointerSize * i));
    }
  }
  __ li(a2,
        ExternalReference::Create(IsolateAddressId::kCEntryFPAddress, isolate));
  __ StoreWord(fp, MemOperand(a2));
  const int kSavedRegistersAreaSize =
      (kNumberOfRegisters * kSystemPointerSize) + kDoubleRegsSize;
  // Get the address of the location in the code object (a2) (return
  // address for lazy deoptimization) and compute the fp-to-sp delta in
  // register a4.
  __ Move(a2, ra);
  __ AddWord(a3, sp, Operand(kSavedRegistersAreaSize));
  __ SubWord(a3, fp, a3);
  // Allocate a new deoptimizer object.
  __ PrepareCallCFunction(5, a4);
  // Pass five arguments, according to n64 ABI.
  __ Move(a0, zero_reg);
  Label context_check;
  __ LoadWord(a1,
              MemOperand(fp, CommonFrameConstants::kContextOrFrameTypeOffset));
  __ JumpIfSmi(a1, &context_check);
  __ LoadWord(a0, MemOperand(fp, StandardFrameConstants::kFunctionOffset));
  __ bind(&context_check);
  __ li(a1, Operand(static_cast<int64_t>(deopt_kind)));
  // a2: code object address
  // a3: fp-to-sp delta
  __ li(a4, ExternalReference::isolate_address());
  // Call Deoptimizer::New().
  {
    AllowExternalCallThatCantCauseGC scope(masm);
    __ CallCFunction(ExternalReference::new_deoptimizer_function(), 5);
  }
  // Preserve "deoptimizer" object in register a0 and get the input
  // frame descriptor pointer to a1 (deoptimizer->input_);
  __ LoadWord(a1, MemOperand(a0, Deoptimizer::input_offset()));
  // Copy core registers into FrameDescription::registers_[kNumRegisters].
  DCHECK_EQ(Register::kNumRegisters, kNumberOfRegisters);
  for (int i = 0; i < kNumberOfRegisters; i++) {
    int offset =
        (i * kSystemPointerSize) + FrameDescription::registers_offset();
    if ((saved_regs.bits() & (1 << i)) != 0) {
      __ LoadWord(a2, MemOperand(sp, i * kSystemPointerSize));
      __ StoreWord(a2, MemOperand(a1, offset));
    } else if (v8_flags.debug_code) {
      __ li(a2, kDebugZapValue);
      __ StoreWord(a2, MemOperand(a1, offset));
    }
  }
  int double_regs_offset = FrameDescription::double_registers_offset();
  // int simd128_regs_offset = FrameDescription::simd128_registers_offset();
  // Copy FPU registers to
  // double_registers_[DoubleRegister::kNumAllocatableRegisters]
  for (int i = 0; i < config->num_allocatable_double_registers(); ++i) {
    int code = config->GetAllocatableDoubleCode(i);
    int dst_offset = code * kDoubleSize + double_regs_offset;
    int src_offset =
        code * kDoubleSize + kNumberOfRegisters * kSystemPointerSize;
    __ LoadDouble(ft0, MemOperand(sp, src_offset));
    __ StoreDouble(ft0, MemOperand(a1, dst_offset));
  }
  // TODO(riscv): Add Simd128 copy
  // Remove the saved registers from the stack.
  __ AddWord(sp, sp, Operand(kSavedRegistersAreaSize));
  // Compute a pointer to the unwinding limit in register a2; that is
  // the first stack slot not part of the input frame.
  __ LoadWord(a2, MemOperand(a1, FrameDescription::frame_size_offset()));
  __ AddWord(a2, a2, sp);
  // Unwind the stack down to - but not including - the unwinding
  // limit and copy the contents of the activation frame to the input
  // frame description.
  __ AddWord(a3, a1, Operand(FrameDescription::frame_content_offset()));
  Label pop_loop;
  Label pop_loop_header;
  __ BranchShort(&pop_loop_header);
  __ bind(&pop_loop);
  __ pop(a4);
  __ StoreWord(a4, MemOperand(a3, 0));
  __ AddWord(a3, a3, kSystemPointerSize);
  __ bind(&pop_loop_header);
  __ Branch(&pop_loop, ne, a2, Operand(sp), Label::Distance::kNear);
  // Compute the output frame in the deoptimizer.
  __ push(a0); // Preserve deoptimizer object across call.
  // a0: deoptimizer object; a1: scratch.
  __ PrepareCallCFunction(1, a1);
  // Call Deoptimizer::ComputeOutputFrames().
  {
    AllowExternalCallThatCantCauseGC scope(masm);
    __ CallCFunction(ExternalReference::compute_output_frames_function(), 1);
  }
  __ pop(a0); // Restore deoptimizer object (class Deoptimizer).
  __ LoadWord(sp, MemOperand(a0, Deoptimizer::caller_frame_top_offset()));
  // Replace the current (input) frame with the output frames.
  Label outer_push_loop, inner_push_loop, outer_loop_header, inner_loop_header;
  // Outer loop state: a4 = current "FrameDescription** output_",
  // a1 = one past the last FrameDescription**.
  __ Lw(a1, MemOperand(a0, Deoptimizer::output_count_offset()));
  __ LoadWord(a4,
              MemOperand(a0, Deoptimizer::output_offset())); // a4 is output_.
  __ CalcScaledAddress(a1, a4, a1, kSystemPointerSizeLog2);
  __ BranchShort(&outer_loop_header);
  __ bind(&outer_push_loop);
  // Inner loop state: a2 = current FrameDescription*, a3 = loop index.
  __ LoadWord(a2, MemOperand(a4, 0)); // output_[ix]
  __ LoadWord(a3, MemOperand(a2, FrameDescription::frame_size_offset()));
  __ BranchShort(&inner_loop_header);
  __ bind(&inner_push_loop);
  __ SubWord(a3, a3, Operand(kSystemPointerSize));
  __ AddWord(a6, a2, Operand(a3));
  __ LoadWord(a7, MemOperand(a6, FrameDescription::frame_content_offset()));
  __ push(a7);
  __ bind(&inner_loop_header);
  __ Branch(&inner_push_loop, ne, a3, Operand(zero_reg));
  __ AddWord(a4, a4, Operand(kSystemPointerSize));
  __ bind(&outer_loop_header);
  __ Branch(&outer_push_loop, lt, a4, Operand(a1));
  __ LoadWord(a1, MemOperand(a0, Deoptimizer::input_offset()));
  for (int i = 0; i < config->num_allocatable_double_registers(); ++i) {
    int code = config->GetAllocatableDoubleCode(i);
    const DoubleRegister fpu_reg = DoubleRegister::from_code(code);
    int src_offset = code * kDoubleSize + double_regs_offset;
    __ LoadDouble(fpu_reg, MemOperand(a1, src_offset));
  }
  // Push pc and continuation from the last output frame.
  __ LoadWord(a6, MemOperand(a2, FrameDescription::pc_offset()));
  __ push(a6);
  __ LoadWord(a6, MemOperand(a2, FrameDescription::continuation_offset()));
  __ push(a6);
  // Technically restoring 't3' should work unless zero_reg is also restored
  // but it's safer to check for this.
  DCHECK(!(restored_regs.has(t3)));
  // Restore the registers from the last output frame.
  __ Move(t3, a2);
  for (int i = kNumberOfRegisters - 1; i >= 0; i--) {
    int offset =
        (i * kSystemPointerSize) + FrameDescription::registers_offset();
    if ((restored_regs.bits() & (1 << i)) != 0) {
      __ LoadWord(ToRegister(i), MemOperand(t3, offset));
    }
  }
  __ pop(t6); // Get continuation, leave pc on stack.
  __ pop(ra);
  Label end;
  __ Branch(&end, eq, t6, Operand(zero_reg));
  __ Jump(t6);
  __ bind(&end);
  __ Ret();
  __ stop();
}
References __, v8::internal::RegListBase< RegisterT >::bits(), v8::internal::Deoptimizer::caller_frame_top_offset(), code, v8::internal::FrameDescription::continuation_offset(), v8::internal::ExternalReference::Create(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::RegisterConfiguration::Default(), v8::internal::compiler::end(), v8::internal::eq, v8::internal::FrameDescription::frame_content_offset(), v8::internal::FrameDescription::frame_size_offset(), v8::internal::RegisterBase< DoubleRegister, kDoubleAfterLast >::from_code(), v8::internal::RegisterConfiguration::GetAllocatableDoubleCode(), v8::internal::RegListBase< RegisterT >::has(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::Deoptimizer::input_offset(), v8::internal::MacroAssemblerBase::isolate(), v8::internal::ExternalReference::isolate_address(), v8::internal::kCalleeSaved, v8::internal::CommonFrameConstants::kContextOrFrameTypeOffset, v8::internal::kDebugZapValue, v8::internal::kDoubleSize, v8::internal::StandardFrameConstants::kFunctionOffset, v8::internal::kJSCallerSaved, v8::internal::kNumberOfRegisters, v8::internal::RegisterBase< Register, kRegAfterLast >::kNumRegisters, v8::internal::RegisterBase< DoubleRegister, kDoubleAfterLast >::kNumRegisters, v8::internal::kSystemPointerSize, v8::internal::kSystemPointerSizeLog2, v8::internal::lt, v8::internal::ne, v8::internal::RegisterConfiguration::num_allocatable_double_registers(), v8::internal::Deoptimizer::output_count_offset(), v8::internal::Deoptimizer::output_offset(), v8::internal::FrameDescription::pc_offset(), v8::internal::wasm::liftoff::push(), v8::internal::FrameDescription::registers_offset(), v8::internal::ToRegister(), and v8::internal::v8_flags.
Generate_JSBuiltinsConstructStubHelper()
void v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_JSBuiltinsConstructStubHelper (MacroAssembler * masm)
Definition at line 74 of file builtins-riscv.cc.
                                                                  {
  // ----------- S t a t e -------------
  // -- a0 : number of arguments
  // -- a1 : constructor function
  // -- a3 : new target
  // -- cp : context
  // -- ra : return address
  // -- sp[...]: constructor arguments
  // -----------------------------------
  // Enter a construct frame.
  {
    FrameScope scope(masm, StackFrame::CONSTRUCT);
    // Preserve the incoming parameters on the stack.
    __ Push(cp, a0);
    // Set up pointer to first argument (skip receiver).
    __ AddWord(
        t2, fp,
        Operand(StandardFrameConstants::kCallerSPOffset + kSystemPointerSize));
    // t2: Pointer to start of arguments.
    // a0: Number of arguments.
    {
      UseScratchRegisterScope temps(masm);
      temps.Include(t0);
      Generate_PushArguments(masm, t2, a0, temps.Acquire(), temps.Acquire(),
                             ArgumentsElementType::kRaw);
    }
    // The receiver for the builtin/api call.
    __ PushRoot(RootIndex::kTheHoleValue);
    // Call the function.
    // a0: number of arguments (untagged)
    // a1: constructor function
    // a3: new target
    __ InvokeFunctionWithNewTarget(a1, a3, a0, InvokeType::kCall);
    // Restore context from the frame.
    __ LoadWord(cp, MemOperand(fp, ConstructFrameConstants::kContextOffset));
    // Restore arguments count from the frame.
    __ LoadWord(kScratchReg,
                MemOperand(fp, ConstructFrameConstants::kLengthOffset));
    // Leave construct frame.
  }
  // Remove caller arguments from the stack and return.
  __ DropArguments(kScratchReg);
  __ Ret();
}
References __, v8::internal::UseScratchRegisterScope::Acquire(), v8::internal::cp, Generate_PushArguments(), v8::internal::UseScratchRegisterScope::Include(), kCall, v8::internal::CommonFrameConstants::kCallerSPOffset, v8::internal::ConstructFrameConstants::kContextOffset, v8::internal::ConstructFrameConstants::kLengthOffset, v8::internal::kScratchReg, and v8::internal::kSystemPointerSize.
Generate_JSEntryVariant()
void v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_JSEntryVariant (MacroAssembler * masm, StackFrame::Type type, Builtin entry_trampoline)
Definition at line 536 of file builtins-riscv.cc.
                                                       {
  Label invoke, handler_entry, exit;
  {
    NoRootArrayScope no_root_array(masm);
    // TODO(plind): unify the ABI description here.
    // Registers:
    // either
    // a0: root register value
    // a1: entry address
    // a2: function
    // a3: receiver
    // a4: argc
    // a5: argv
    // or
    // a0: root register value
    // a1: microtask_queue
    // Save callee saved registers on the stack.
    __ MultiPush(kCalleeSaved | ra);
    // Save callee-saved FPU registers.
    __ MultiPushFPU(kCalleeSavedFPU);
    // Set up the reserved register for 0.0.
    __ LoadFPRImmediate(kDoubleRegZero, 0.0);
    __ LoadFPRImmediate(kSingleRegZero, 0.0f);
    // Initialize the root register.
    // C calling convention. The first argument is passed in a0.
    __ Move(kRootRegister, a0);
#ifdef V8_COMPRESS_POINTERS
    // Initialize the pointer cage base register.
    __ LoadRootRelative(kPtrComprCageBaseRegister,
                        IsolateData::cage_base_offset());
#endif
  }
  // a1: entry address
  // a2: function
  // a3: receiver
  // a4: argc
  // a5: argv
  // We build an EntryFrame.
  __ li(s1, Operand(-1)); // Push a bad frame pointer to fail if it is used.
  __ li(s2, Operand(StackFrame::TypeToMarker(type)));
  __ li(s3, Operand(StackFrame::TypeToMarker(type)));
  ExternalReference c_entry_fp = ExternalReference::Create(
      IsolateAddressId::kCEntryFPAddress, masm->isolate());
  __ li(s5, c_entry_fp);
  __ LoadWord(s4, MemOperand(s5));
  __ Push(s1, s2, s3, s4);
  // Clear c_entry_fp, now we've pushed its previous value to the stack.
  // If the c_entry_fp is not already zero and we don't clear it, the
  // StackFrameIteratorForProfiler will assume we are executing C++ and miss the
  // JS frames on top.
  __ StoreWord(zero_reg, MemOperand(s5));
  __ LoadIsolateField(s1, IsolateFieldId::kFastCCallCallerFP);
  __ LoadWord(s2, MemOperand(s1, 0));
  __ StoreWord(zero_reg, MemOperand(s1, 0));
  __ LoadIsolateField(s1, IsolateFieldId::kFastCCallCallerPC);
  __ LoadWord(s3, MemOperand(s1, 0));
  __ StoreWord(zero_reg, MemOperand(s1, 0));
  __ Push(s2, s3);
  // Set up frame pointer for the frame to be pushed.
  __ AddWord(fp, sp, -EntryFrameConstants::kNextFastCallFramePCOffset);
  // Registers:
  // either
  // a1: entry address
  // a2: function
  // a3: receiver
  // a4: argc
  // a5: argv
  // or
  // a1: microtask_queue
  //
  // Stack:
  // fast api call pc
  // fast api call fp
  // caller fp |
  // function slot | entry frame
  // context slot |
  // bad fp (0xFF...F) |
  // callee saved registers + ra
  // If this is the outermost JS call, set js_entry_sp value.
  Label non_outermost_js;
  ExternalReference js_entry_sp = ExternalReference::Create(
      IsolateAddressId::kJSEntrySPAddress, masm->isolate());
  __ li(s1, js_entry_sp);
  __ LoadWord(s2, MemOperand(s1));
  __ Branch(&non_outermost_js, ne, s2, Operand(zero_reg),
            Label::Distance::kNear);
  __ StoreWord(fp, MemOperand(s1));
  __ li(s3, Operand(StackFrame::OUTERMOST_JSENTRY_FRAME));
  Label cont;
  __ Branch(&cont);
  __ bind(&non_outermost_js);
  __ li(s3, Operand(StackFrame::INNER_JSENTRY_FRAME));
  __ bind(&cont);
  __ push(s3);
  // Jump to a faked try block that does the invoke, with a faked catch
  // block that sets the exception.
  __ BranchShort(&invoke);
  __ bind(&handler_entry);
  // Store the current pc as the handler offset. It's used later to create the
  // handler table.
  masm->isolate()->builtins()->SetJSEntryHandlerOffset(handler_entry.pos());
  // Caught exception: Store result (exception) in the exception
  // field in the JSEnv and return a failure sentinel. Coming in here the
  // fp will be invalid because the PushStackHandler below sets it to 0 to
  // signal the existence of the JSEntry frame.
  __ li(s1, ExternalReference::Create(IsolateAddressId::kExceptionAddress,
                                      masm->isolate()));
  __ StoreWord(a0,
               MemOperand(s1)); // We come back from 'invoke'. result is in a0.
  __ LoadRoot(a0, RootIndex::kException);
  __ BranchShort(&exit);
  // Invoke: Link this frame into the handler chain.
  __ bind(&invoke);
  __ PushStackHandler();
  // If an exception not caught by another handler occurs, this handler
  // returns control to the code after the bal(&invoke) above, which
  // restores all kCalleeSaved registers (including cp and fp) to their
  // saved values before returning a failure to C.
  //
  // Registers:
  // either
  // a0: root register value
  // a1: entry address
  // a2: function
  // a3: receiver
  // a4: argc
  // a5: argv
  // or
  // a0: root register value
  // a1: microtask_queue
  //
  // Stack:
  // fast api call pc.
  // fast api call fp.
  // JS entry frame marker
  // caller fp |
  // function slot | entry frame
  // context slot |
  // bad fp (0xFF...F) |
  // handler frame
  // entry frame
  // callee saved registers + ra
  // [ O32: 4 args slots]
  // args
  //
  // Invoke the function by calling through JS entry trampoline builtin and
  // pop the faked function when we return.
  __ CallBuiltin(entry_trampoline);
  // Unlink this frame from the handler chain.
  __ PopStackHandler();
  __ bind(&exit); // a0 holds result
  // Check if the current stack frame is marked as the outermost JS frame.
  Label non_outermost_js_2;
  __ pop(a5);
  __ Branch(&non_outermost_js_2, ne, a5,
            Operand(StackFrame::OUTERMOST_JSENTRY_FRAME),
            Label::Distance::kNear);
  __ li(a5, js_entry_sp);
  __ StoreWord(zero_reg, MemOperand(a5));
  __ bind(&non_outermost_js_2);
  __ Pop(s2, s3);
  __ LoadIsolateField(s1, IsolateFieldId::kFastCCallCallerFP);
  __ StoreWord(s2, MemOperand(s1, 0));
  __ LoadIsolateField(s1, IsolateFieldId::kFastCCallCallerPC);
  __ StoreWord(s3, MemOperand(s1, 0));
  // Restore the top frame descriptors from the stack.
  __ pop(a5);
  __ li(a4, ExternalReference::Create(IsolateAddressId::kCEntryFPAddress,
                                      masm->isolate()));
  __ StoreWord(a5, MemOperand(a4));
  // Reset the stack to the callee saved registers.
  __ AddWord(sp, sp, -EntryFrameConstants::kNextExitFrameFPOffset);
  // Restore callee-saved fpu registers.
  __ MultiPopFPU(kCalleeSavedFPU);
  // Restore callee saved registers from the stack.
  __ MultiPop(kCalleeSaved | ra);
  // Return.
  __ Jump(ra);
}
References __, v8::internal::Isolate::builtins(), v8::internal::ExternalReference::Create(), v8::internal::StackFrame::INNER_JSENTRY_FRAME, v8::internal::libvtune::invoke(), v8::internal::MacroAssemblerBase::isolate(), v8::internal::kCalleeSaved, v8::internal::kCalleeSavedFPU, v8::internal::kDoubleRegZero, v8::debug::kException, v8::internal::EntryFrameConstants::kNextExitFrameFPOffset, v8::internal::EntryFrameConstants::kNextFastCallFramePCOffset, v8::internal::kPtrComprCageBaseRegister, v8::internal::kRootRegister, v8::internal::kSingleRegZero, v8::internal::ne, v8::internal::StackFrame::OUTERMOST_JSENTRY_FRAME, v8::internal::Label::pos(), v8::internal::wasm::liftoff::push(), v8::internal::Builtins::SetJSEntryHandlerOffset(), v8::internal::tracing::type, and v8::internal::StackFrame::TypeToMarker().
Generate_OSREntry()
void v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_OSREntry (MacroAssembler * masm, Register entry_address, Operand offset = Operand(0))
Definition at line 1978 of file builtins-riscv.cc.
                                                    {
  __ AddWord(ra, entry_address, offset);
  // And "return" to the OSR entry point of the function.
  __ Ret();
}
References __.
Referenced by OnStackReplacement().
Generate_PushArguments()
void v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_PushArguments (MacroAssembler * masm, Register array, Register argc, Register scratch, Register scratch2, ArgumentsElementType element_type)
Definition at line 54 of file builtins-riscv.cc.
                                                               {
  ASM_CODE_COMMENT(masm);
  DCHECK(!AreAliased(array, argc, scratch));
  Label loop, entry;
  __ SubWord(scratch, argc, Operand(kJSArgcReceiverSlots));
  __ Branch(&entry);
  __ bind(&loop);
  __ CalcScaledAddress(scratch2, array, scratch, kSystemPointerSizeLog2);
  __ LoadWord(scratch2, MemOperand(scratch2));
  if (element_type == ArgumentsElementType::kHandle) {
    __ LoadWord(scratch2, MemOperand(scratch2));
  }
  __ push(scratch2);
  __ bind(&entry);
  __ AddWord(scratch, scratch, Operand(-1));
  __ Branch(&loop, greater_equal, scratch, Operand(zero_reg));
}
References __, v8::internal::AreAliased(), ASM_CODE_COMMENT, v8::internal::DCHECK(), v8::internal::greater_equal, v8::internal::kJSArgcReceiverSlots, v8::internal::kSystemPointerSizeLog2, and v8::internal::wasm::liftoff::push().
Referenced by Generate_JSBuiltinsConstructStubHelper(), and v8::internal::Generate_JSEntryTrampolineHelper().
Generate_PushBoundArguments()
void v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_PushBoundArguments (MacroAssembler * masm)
Definition at line 2690 of file builtins-riscv.cc.
                                                       {
  // ----------- S t a t e -------------
  // -- a0 : the number of arguments
  // -- a1 : target (checked to be a JSBoundFunction)
  // -- a3 : new.target (only in case of [[Construct]])
  // -----------------------------------
  UseScratchRegisterScope temps(masm);
  temps.Include(t0, t1);
  Register bound_argc = a4;
  Register bound_argv = a2;
  // Load [[BoundArguments]] into a2 and length of that into a4.
  Label no_bound_arguments;
  __ LoadTaggedField(
      bound_argv, FieldMemOperand(a1, JSBoundFunction::kBoundArgumentsOffset));
  __ SmiUntagField(bound_argc,
                   FieldMemOperand(bound_argv, offsetof(FixedArray, length_)));
  __ Branch(&no_bound_arguments, eq, bound_argc, Operand(zero_reg));
  {
    // ----------- S t a t e -------------
    // -- a0 : the number of arguments
    // -- a1 : target (checked to be a JSBoundFunction)
    // -- a2 : the [[BoundArguments]] (implemented as FixedArray)
    // -- a3 : new.target (only in case of [[Construct]])
    // -- a4: the number of [[BoundArguments]]
    // -----------------------------------
    UseScratchRegisterScope temps(masm);
    Register scratch = temps.Acquire();
    Label done;
    // Reserve stack space for the [[BoundArguments]].
    {
      // Check the stack for overflow. We are not trying to catch interruptions
      // (i.e. debug break and preemption) here, so check the "real stack
      // limit".
      __ StackOverflowCheck(a4, temps.Acquire(), temps.Acquire(), nullptr,
                            &done);
      {
        FrameScope scope(masm, StackFrame::MANUAL);
        __ EnterFrame(StackFrame::INTERNAL);
        __ CallRuntime(Runtime::kThrowStackOverflow);
      }
      __ bind(&done);
    }
    // Pop receiver.
    __ Pop(scratch);
    // Push [[BoundArguments]].
    {
      Label loop, done_loop;
      __ SmiUntag(a4, FieldMemOperand(a2, offsetof(FixedArray, length_)));
      __ AddWord(a0, a0, Operand(a4));
      __ AddWord(a2, a2,
                 Operand(OFFSET_OF_DATA_START(FixedArray) - kHeapObjectTag));
      __ bind(&loop);
      __ SubWord(a4, a4, Operand(1));
      __ Branch(&done_loop, lt, a4, Operand(zero_reg), Label::Distance::kNear);
      __ CalcScaledAddress(a5, a2, a4, kTaggedSizeLog2);
      __ LoadTaggedField(kScratchReg, MemOperand(a5));
      __ Push(kScratchReg);
      __ Branch(&loop);
      __ bind(&done_loop);
    }
    // Push receiver.
    __ Push(scratch);
  }
  __ bind(&no_bound_arguments);
}
References __, v8::internal::UseScratchRegisterScope::Acquire(), v8::internal::eq, v8::internal::FieldMemOperand(), v8::internal::UseScratchRegisterScope::Include(), v8::internal::kHeapObjectTag, v8::internal::kScratchReg, v8::internal::kTaggedSizeLog2, v8::internal::lt, v8::internal::StackFrame::MANUAL, OFFSET_OF_DATA_START, and v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::SmiUntag().
Referenced by v8::internal::Builtins::Generate_CallBoundFunctionImpl().
Generate_WasmResumeHelper()
void v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_WasmResumeHelper (MacroAssembler * masm, wasm::OnResume on_resume)
Definition at line 3946 of file builtins-riscv.cc.
                                                                             {
  auto regs = RegisterAllocator::WithAllocatableGeneralRegisters();
  UseScratchRegisterScope temps(masm);
  __ EnterFrame(StackFrame::STACK_SWITCH);
  DEFINE_PINNED(closure, kJSFunctionRegister); // a1
  __ SubWord(
      sp, sp,
      Operand(StackSwitchFrameConstants::kNumSpillSlots * kSystemPointerSize));
  // Set a sentinel value for the spill slots visited by the GC.
  ResetStackSwitchFrameStackSlots(masm);
  regs.ResetExcept(closure);
  // -------------------------------------------
  // Load suspender from closure.
  // -------------------------------------------
  DEFINE_REG(sfi);
  __ LoadTaggedField(
      sfi,
      MemOperand(
          closure,
          wasm::ObjectAccess::SharedFunctionInfoOffsetInTaggedJSFunction()));
  FREE_REG(closure);
  // Suspender should be ObjectRegister register to be used in
  // RecordWriteField calls later.
  DEFINE_PINNED(suspender, WriteBarrierDescriptor::ObjectRegister());
  DEFINE_REG(resume_data);
  __ LoadTaggedField(
      resume_data,
      FieldMemOperand(sfi, SharedFunctionInfo::kUntrustedFunctionDataOffset));
  __ LoadTaggedField(
      suspender,
      FieldMemOperand(resume_data, WasmResumeData::kSuspenderOffset));
  regs.ResetExcept(suspender);
  // -------------------------------------------
  // Save current state.
  // -------------------------------------------
  Label suspend;
  DEFINE_REG(active_stack);
  __ LoadRootRelative(active_stack, IsolateData::active_stack_offset());
  DEFINE_REG(scratch);
  FillJumpBuffer(masm, active_stack, &suspend, scratch);
  SwitchStackState(masm, active_stack, scratch, wasm::JumpBuffer::Active,
                   wasm::JumpBuffer::Inactive);
  // -------------------------------------------
  // Set the suspender and stack parents and update the roots
  // -------------------------------------------
  DEFINE_REG(active_suspender);
  __ LoadRoot(active_suspender, RootIndex::kActiveSuspender);
  __ StoreTaggedField(
      active_suspender,
      FieldMemOperand(suspender, WasmSuspenderObject::kParentOffset));
  __ RecordWriteField(suspender, WasmSuspenderObject::kParentOffset,
                      active_suspender, kRAHasBeenSaved,
                      SaveFPRegsMode::kIgnore);
  FREE_REG(active_suspender);
  int32_t active_suspender_offset =
      MacroAssembler::RootRegisterOffsetForRootIndex(
          RootIndex::kActiveSuspender);
  __ StoreWord(suspender, MemOperand(kRootRegister, active_suspender_offset));
  regs.Reserve(kReturnRegister0);
  DEFINE_REG(target_stack);
  __ LoadExternalPointerField(
      target_stack,
      FieldMemOperand(suspender, WasmSuspenderObject::kStackOffset),
      kWasmStackMemoryTag);
  FREE_REG(suspender);
  __ StoreRootRelative(IsolateData::active_stack_offset(), target_stack);
  SwitchStacks(masm, active_stack, false, scratch, {target_stack});
  regs.ResetExcept(target_stack, kReturnRegister0);
  // -------------------------------------------
  // Load state from target jmpbuf (longjmp).
  // -------------------------------------------
  ASSIGN_REG(scratch);
  // Move resolved value to return register.
  __ LoadWord(kReturnRegister0, MemOperand(fp, 3 * kSystemPointerSize));
  MemOperand GCScanSlotPlace =
      MemOperand(fp, StackSwitchFrameConstants::kGCScanSlotCountOffset);
  __ StoreWord(zero_reg, GCScanSlotPlace);
  if (on_resume == wasm::OnResume::kThrow) {
    // Switch without restoring the PC.
    LoadJumpBuffer(masm, target_stack, false, scratch,
                   wasm::JumpBuffer::Suspended);
    // Pop this frame now. The unwinder expects that the first STACK_SWITCH
    // frame is the outermost one.
    __ LeaveFrame(StackFrame::STACK_SWITCH);
    // Forward the onRejected value to kThrow.
    __ Push(kReturnRegister0);
    __ CallRuntime(Runtime::kThrow);
  } else {
    // Resume the stack normally.
    LoadJumpBuffer(masm, target_stack, true, scratch,
                   wasm::JumpBuffer::Suspended);
  }
  __ Trap();
  __ bind(&suspend);
  __ LeaveFrame(StackFrame::STACK_SWITCH);
  // Pop receiver + parameter.
  // __ DropArguments(2);
  __ AddWord(sp, sp, Operand(2 * kSystemPointerSize));
  __ Ret();
}
References __, v8::internal::wasm::JumpBuffer::Active, ASSIGN_REG, DEFINE_PINNED, DEFINE_REG, v8::internal::FieldMemOperand(), FillJumpBuffer(), FREE_REG, v8::internal::wasm::JumpBuffer::Inactive, v8::internal::kIgnore, v8::internal::kJSFunctionRegister, v8::internal::kRAHasBeenSaved, v8::internal::kReturnRegister0, v8::internal::kRootRegister, v8::internal::kStackOffset, v8::internal::kSystemPointerSize, v8::internal::wasm::kThrow, v8::internal::kWasmStackMemoryTag, LoadJumpBuffer(), v8::internal::WriteBarrierDescriptor::ObjectRegister(), ResetStackSwitchFrameStackSlots(), v8::internal::MacroAssemblerBase::RootRegisterOffsetForRootIndex(), v8::internal::wasm::ObjectAccess::SharedFunctionInfoOffsetInTaggedJSFunction(), v8::internal::wasm::JumpBuffer::Suspended, SwitchStacks(), and SwitchStackState().
GenerateExceptionHandlingLandingPad()
void v8::internal::anonymous_namespace{builtins-riscv.cc}::GenerateExceptionHandlingLandingPad (MacroAssembler * masm, RegisterAllocator & regs, Label * return_promise)
Definition at line 4197 of file builtins-riscv.cc.
                                                                {
  ASM_CODE_COMMENT(masm);
  regs.ResetExcept();
  static const Builtin_RejectPromise_InterfaceDescriptor desc;
  DEFINE_PINNED(promise, desc.GetRegisterParameter(0));
  DEFINE_PINNED(reason, desc.GetRegisterParameter(1));
  DEFINE_PINNED(debug_event, desc.GetRegisterParameter(2));
  int catch_handler = __ pc_offset();
  DEFINE_SCOPED(thread_in_wasm_flag_addr);
  thread_in_wasm_flag_addr = a2;
  // Unset thread_in_wasm_flag.
  __ LoadWord(
      thread_in_wasm_flag_addr,
      MemOperand(kRootRegister, Isolate::thread_in_wasm_flag_address_offset()));
  __ StoreWord(zero_reg, MemOperand(thread_in_wasm_flag_addr, 0));
  // The exception becomes the parameter of the RejectPromise builtin, and the
  // promise is the return value of this wrapper.
  __ mv(reason, kReturnRegister0);
  __ LoadRoot(promise, RootIndex::kActiveSuspender);
  __ LoadTaggedField(
      promise, FieldMemOperand(promise, WasmSuspenderObject::kPromiseOffset));
  __ LoadWord(kContextRegister,
              MemOperand(fp, StackSwitchFrameConstants::kImplicitArgOffset));
  DEFINE_SCOPED(tmp);
  DEFINE_SCOPED(tmp2);
  DEFINE_SCOPED(tmp3);
  GetContextFromImplicitArg(masm, kContextRegister, tmp);
  ReloadParentStack(masm, promise, reason, kContextRegister, tmp, tmp2, tmp3);
  RestoreParentSuspender(masm, tmp);
  __ li(tmp, 1);
  __ StoreWord(
      tmp, MemOperand(fp, StackSwitchFrameConstants::kGCScanSlotCountOffset));
  __ Push(promise);
  __ LoadRoot(debug_event, RootIndex::kTrueValue);
  __ CallBuiltin(Builtin::kRejectPromise);
  __ Pop(promise);
  // Run the rest of the wrapper normally (deconstruct the frame, ...).
  __ jmp(return_promise);
  masm->isolate()->builtins()->SetJSPIPromptHandlerOffset(catch_handler);
}
References __, ASM_CODE_COMMENT, v8::internal::Isolate::builtins(), DEFINE_PINNED, DEFINE_SCOPED, v8::internal::FieldMemOperand(), GetContextFromImplicitArg(), v8::internal::MacroAssemblerBase::isolate(), v8::internal::kContextRegister, v8::internal::kReturnRegister0, v8::internal::kRootRegister, ReloadParentStack(), v8::internal::anonymous_namespace{builtins-riscv.cc}::RegisterAllocator::ResetExcept(), RestoreParentSuspender(), v8::internal::Builtins::SetJSPIPromptHandlerOffset(), and v8::internal::Isolate::thread_in_wasm_flag_address_offset().
Referenced by JSToWasmWrapperHelper().
GetContextFromImplicitArg()
void v8::internal::anonymous_namespace{builtins-riscv.cc}::GetContextFromImplicitArg (MacroAssembler * masm, Register data, Register scratch)
Definition at line 4137 of file builtins-riscv.cc.
                                                 {
  __ LoadTaggedField(scratch, FieldMemOperand(data, HeapObject::kMapOffset));
  Label instance;
  Label end;
  __ GetInstanceTypeRange(scratch, scratch, WASM_TRUSTED_INSTANCE_DATA_TYPE,
                          scratch);
  // __ CompareInstanceType(scratch, scratch, WASM_TRUSTED_INSTANCE_DATA_TYPE);
  __ Branch(&instance, eq, scratch, Operand(zero_reg));
  __ LoadTaggedField(
      data, FieldMemOperand(data, WasmImportData::kNativeContextOffset));
  __ Branch(&end);
  __ bind(&instance);
  __ LoadTaggedField(
      data,
      FieldMemOperand(data, WasmTrustedInstanceData::kNativeContextOffset));
  __ bind(&end);
}
References __, v8::internal::compiler::end(), v8::internal::eq, v8::internal::FieldMemOperand(), and v8::internal::HeapObject::kMapOffset.
Referenced by GenerateExceptionHandlingLandingPad(), JSToWasmWrapperHelper(), and SwitchBackAndReturnPromise().
JSToWasmWrapperHelper()
void v8::internal::anonymous_namespace{builtins-riscv.cc}::JSToWasmWrapperHelper (MacroAssembler * masm, wasm::Promise mode)
Definition at line 4245 of file builtins-riscv.cc.
                                                                   {
  bool stack_switch = mode == wasm::kPromise || mode == wasm::kStressSwitch;
  auto regs = RegisterAllocator::WithAllocatableGeneralRegisters();
  __ EnterFrame(stack_switch ? StackFrame::STACK_SWITCH
                             : StackFrame::JS_TO_WASM);
  __ SubWord(
      sp, sp,
      Operand(StackSwitchFrameConstants::kNumSpillSlots * kSystemPointerSize));
  // Load the implicit argument (instance data or import data) from the frame.
  DEFINE_PINNED(implicit_arg, kWasmImplicitArgRegister);
  __ LoadWord(
      implicit_arg,
      MemOperand(fp, JSToWasmWrapperFrameConstants::kImplicitArgOffset));
  DEFINE_PINNED(wrapper_buffer,
                WasmJSToWasmWrapperDescriptor::WrapperBufferRegister());
  Label suspend;
  Register original_fp = no_reg;
  Register new_wrapper_buffer = no_reg;
  if (stack_switch) {
    SwitchToAllocatedStack(masm, regs, implicit_arg, wrapper_buffer,
                           original_fp, new_wrapper_buffer, &suspend);
  } else {
    original_fp = fp;
    new_wrapper_buffer = wrapper_buffer;
  }
  regs.ResetExcept(original_fp, wrapper_buffer, implicit_arg,
                   new_wrapper_buffer);
  {
    __ StoreWord(
        new_wrapper_buffer,
        MemOperand(fp, JSToWasmWrapperFrameConstants::kWrapperBufferOffset));
    if (stack_switch) {
      __ StoreWord(
          implicit_arg,
          MemOperand(fp, StackSwitchFrameConstants::kImplicitArgOffset));
      UseScratchRegisterScope temps(masm);
      Register scratch = temps.Acquire();
      __ LoadWord(
          scratch,
          MemOperand(original_fp,
                     JSToWasmWrapperFrameConstants::kResultArrayParamOffset));
      __ StoreWord(
          scratch,
          MemOperand(fp, StackSwitchFrameConstants::kResultArrayOffset));
    }
  }
  {
    DEFINE_SCOPED(result_size);
    __ LoadWord(
        result_size,
        MemOperand(wrapper_buffer, JSToWasmWrapperFrameConstants::
                                       kWrapperBufferStackReturnBufferSize));
    __ SllWord(result_size, result_size, kSystemPointerSizeLog2);
    __ SubWord(sp, sp, Operand(result_size));
  }
  __ StoreWord(
      sp,
      MemOperand(
          new_wrapper_buffer,
          JSToWasmWrapperFrameConstants::kWrapperBufferStackReturnBufferStart));
  if (stack_switch) {
    FREE_REG(new_wrapper_buffer)
  }
  FREE_REG(implicit_arg)
  for (auto reg : wasm::kGpParamRegisters) {
    regs.Reserve(reg);
  }
  // The first GP parameter holds the trusted instance data or the import data.
  // This is handled specially.
  int stack_params_offset =
      (arraysize(wasm::kGpParamRegisters) - 1) * kSystemPointerSize +
      arraysize(wasm::kFpParamRegisters) * kDoubleSize;
  {
    DEFINE_SCOPED(params_start);
    __ LoadWord(
        params_start,
        MemOperand(wrapper_buffer,
                   JSToWasmWrapperFrameConstants::kWrapperBufferParamStart));
    {
      // Push stack parameters on the stack.
      DEFINE_SCOPED(params_end);
      __ LoadWord(
          params_end,
          MemOperand(wrapper_buffer,
                     JSToWasmWrapperFrameConstants::kWrapperBufferParamEnd));
      DEFINE_SCOPED(last_stack_param);
      __ AddWord(last_stack_param, params_start, Operand(stack_params_offset));
      Label loop_start;
      __ bind(&loop_start);
      Label finish_stack_params;
      __ Branch(&finish_stack_params, ge, last_stack_param,
                Operand(params_end));
      // Push parameter
      {
        DEFINE_SCOPED(scratch);
        __ SubWord(params_end, params_end, Operand(kSystemPointerSize));
        __ LoadWord(scratch, MemOperand(params_end, 0));
        __ Push(scratch);
      }
      __ Branch(&loop_start);
      __ bind(&finish_stack_params);
    }
    int32_t next_offset = 0;
    for (size_t i = 1; i < arraysize(wasm::kGpParamRegisters); ++i) {
      // Check that {params_start} does not overlap with any of the parameter
      // registers, so that we don't overwrite it by accident with the loads
      // below.
      DCHECK_NE(params_start, wasm::kGpParamRegisters[i]);
      __ LoadWord(wasm::kGpParamRegisters[i],
                  MemOperand(params_start, next_offset));
      next_offset += kSystemPointerSize;
    }
    for (size_t i = 0; i < arraysize(wasm::kFpParamRegisters); ++i) {
      __ LoadDouble(wasm::kFpParamRegisters[i],
                    MemOperand(params_start, next_offset));
      next_offset += kDoubleSize;
    }
    DCHECK_EQ(next_offset, stack_params_offset);
  }
  {
    DEFINE_SCOPED(thread_in_wasm_flag_addr);
    __ LoadWord(thread_in_wasm_flag_addr,
                MemOperand(kRootRegister,
                           Isolate::thread_in_wasm_flag_address_offset()));
    DEFINE_SCOPED(scratch);
    __ li(scratch, 1);
    __ Sw(scratch, MemOperand(thread_in_wasm_flag_addr, 0));
  }
  __ StoreWord(
      zero_reg,
      MemOperand(fp, StackSwitchFrameConstants::kGCScanSlotCountOffset));
  {
    DEFINE_SCOPED(call_target);
    __ LoadWasmCodePointer(
        call_target,
        MemOperand(wrapper_buffer,
                   JSToWasmWrapperFrameConstants::kWrapperBufferCallTarget));
    // We do the call without a signature check here, since the wrapper loaded
    // the signature from the same trusted object as the call target to set up
    // the stack layout. We could add a signature hash and pass it through to
    // verify it here, but an attacker that could corrupt the signature could
    // also corrupt that signature hash (which is outside of the sandbox).
    __ CallWasmCodePointerNoSignatureCheck(call_target);
  }
  regs.ResetExcept();
  // The wrapper_buffer has to be in a2 as the correct parameter register.
  regs.Reserve(kReturnRegister0, kReturnRegister1);
  ASSIGN_PINNED(wrapper_buffer, a2);
  {
    DEFINE_SCOPED(thread_in_wasm_flag_addr);
    __ LoadWord(thread_in_wasm_flag_addr,
                MemOperand(kRootRegister,
                           Isolate::thread_in_wasm_flag_address_offset()));
    __ Sw(zero_reg, MemOperand(thread_in_wasm_flag_addr, 0));
  }
  __ LoadWord(
      wrapper_buffer,
      MemOperand(fp, JSToWasmWrapperFrameConstants::kWrapperBufferOffset));
  __ StoreDouble(
      wasm::kFpReturnRegisters[0],
      MemOperand(
          wrapper_buffer,
          JSToWasmWrapperFrameConstants::kWrapperBufferFPReturnRegister1));
  __ StoreDouble(
      wasm::kFpReturnRegisters[1],
      MemOperand(
          wrapper_buffer,
          JSToWasmWrapperFrameConstants::kWrapperBufferFPReturnRegister2));
  __ StoreWord(
      wasm::kGpReturnRegisters[0],
      MemOperand(
          wrapper_buffer,
          JSToWasmWrapperFrameConstants::kWrapperBufferGPReturnRegister1));
  __ StoreWord(
      wasm::kGpReturnRegisters[1],
      MemOperand(
          wrapper_buffer,
          JSToWasmWrapperFrameConstants::kWrapperBufferGPReturnRegister2));
  // Call the return value builtin with
  // a0: wasm instance.
  // a1: the result JSArray for multi-return.
  // a2: pointer to the byte buffer which contains all parameters.
  if (stack_switch) {
    __ LoadWord(a1,
                MemOperand(fp, StackSwitchFrameConstants::kResultArrayOffset));
    __ LoadWord(a0,
                MemOperand(fp, StackSwitchFrameConstants::kImplicitArgOffset));
  } else {
    __ LoadWord(
        a1,
        MemOperand(fp, JSToWasmWrapperFrameConstants::kResultArrayParamOffset));
    __ LoadWord(
        a0, MemOperand(fp, JSToWasmWrapperFrameConstants::kImplicitArgOffset));
  }
  {
    UseScratchRegisterScope temps(masm);
    GetContextFromImplicitArg(masm, a0, temps.Acquire());
  }
  __ CallBuiltin(Builtin::kJSToWasmHandleReturns);
  Label return_promise;
  if (stack_switch) {
    SwitchBackAndReturnPromise(masm, regs, mode, &return_promise);
  }
  __ bind(&suspend);
  __ LeaveFrame(stack_switch ? StackFrame::STACK_SWITCH
                             : StackFrame::JS_TO_WASM);
  // Despite returning to the different location for regular and stack switching
  // versions, incoming argument count matches both cases:
  // instance and result array without suspend or
  // or promise resolve/reject params for callback.
  constexpr int64_t stack_arguments_in = 2;
  // __ DropArguments(stack_arguments_in);
  __ AddWord(sp, sp, Operand(stack_arguments_in * kSystemPointerSize));
  __ Ret();
  // Catch handler for the stack-switching wrapper: reject the promise with the
  // thrown exception.
  if (mode == wasm::kPromise) {
    GenerateExceptionHandlingLandingPad(masm, regs, &return_promise);
  }
}
References __, v8::internal::UseScratchRegisterScope::Acquire(), arraysize, ASSIGN_PINNED, DCHECK_EQ, DCHECK_NE, DEFINE_PINNED, DEFINE_SCOPED, FREE_REG, v8::internal::ge, GenerateExceptionHandlingLandingPad(), GetContextFromImplicitArg(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::kDoubleSize, v8::internal::wasm::kFpParamRegisters, v8::internal::wasm::kFpReturnRegisters, v8::internal::wasm::kGpParamRegisters, v8::internal::wasm::kGpReturnRegisters, v8::internal::wasm::kPromise, v8::internal::kReturnRegister0, v8::internal::kReturnRegister1, v8::internal::kRootRegister, v8::internal::wasm::kStressSwitch, v8::internal::kSystemPointerSize, v8::internal::kSystemPointerSizeLog2, v8::internal::kWasmImplicitArgRegister, mode(), v8::internal::no_reg, SwitchBackAndReturnPromise(), SwitchToAllocatedStack(), v8::internal::Isolate::thread_in_wasm_flag_address_offset(), and v8::internal::WasmJSToWasmWrapperDescriptor::WrapperBufferRegister().
LoadJumpBuffer()
void v8::internal::anonymous_namespace{builtins-riscv.cc}::LoadJumpBuffer (MacroAssembler * masm, Register stack, bool load_pc, Register tmp, wasm::JumpBuffer::StackState expected_state)
Definition at line 3641 of file builtins-riscv.cc.
                                                                           {
  ASM_CODE_COMMENT(masm);
  SwitchStackPointerAndSimulatorStackLimit(masm, stack);
  __ LoadWord(fp, MemOperand(stack, wasm::kStackFpOffset));
  SwitchStackState(masm, stack, tmp, expected_state, wasm::JumpBuffer::Active);
  if (load_pc) {
    __ LoadWord(tmp, MemOperand(stack, wasm::kStackPcOffset));
    __ Jump(tmp);
  }
  // The stack limit in StackGuard is set separately under the ExecutionAccess
  // lock.
}
References __, v8::internal::wasm::JumpBuffer::Active, ASM_CODE_COMMENT, v8::internal::wasm::kStackFpOffset, v8::internal::wasm::kStackPcOffset, v8::internal::stack, SwitchStackPointerAndSimulatorStackLimit(), and SwitchStackState().
Referenced by Generate_WasmResumeHelper(), LoadTargetJumpBuffer(), and ReloadParentStack().
LoadTargetJumpBuffer()
void v8::internal::anonymous_namespace{builtins-riscv.cc}::LoadTargetJumpBuffer (MacroAssembler * masm, Register target_stack, Register tmp, wasm::JumpBuffer::StackState expected_state)
Definition at line 3852 of file builtins-riscv.cc.
                                                                   {
  ASM_CODE_COMMENT(masm);
  __ StoreWord(
      zero_reg,
      MemOperand(fp, StackSwitchFrameConstants::kGCScanSlotCountOffset));
  // Switch stack!
  LoadJumpBuffer(masm, target_stack, false, tmp, expected_state);
}
References __, ASM_CODE_COMMENT, and LoadJumpBuffer().
Referenced by SwitchToAllocatedStack().
NewImplicitReceiver()
void v8::internal::anonymous_namespace{builtins-riscv.cc}::NewImplicitReceiver (MacroAssembler * masm)
Definition at line 1592 of file builtins-riscv.cc.
                                               {
  // ----------- S t a t e -------------
  // -- a0 : the number of arguments
  // -- a1 : constructor to call (checked to be a JSFunction)
  // -- a3 : new target
  //
  // Stack:
  // -- Implicit Receiver
  // -- [arguments without receiver]
  // -- Implicit Receiver
  // -- Context
  // -- FastConstructMarker
  // -- FramePointer
  // -----------------------------------
  Register implicit_receiver = a4;
  // Save live registers.
  __ SmiTag(a0);
  __ Push(a0, a1, a3);
  __ CallBuiltin(Builtin::kFastNewObject);
  // Save result.
  __ mv(implicit_receiver, a0);
  __ Pop(a0, a1, a3);
  __ SmiUntag(a0);
  // Patch implicit receiver (in arguments)
  __ StoreReceiver(implicit_receiver);
  // Patch second implicit (in construct frame)
  __ StoreWord(
      implicit_receiver,
      MemOperand(fp, FastConstructFrameConstants::kImplicitReceiverOffset));
  // Restore context.
  __ LoadWord(cp, MemOperand(fp, FastConstructFrameConstants::kContextOffset));
}
References __, v8::internal::cp, v8::internal::FastConstructFrameConstants::kContextOffset, v8::internal::FastConstructFrameConstants::kImplicitReceiverOffset, and v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::SmiUntag().
OnStackReplacement()
void v8::internal::anonymous_namespace{builtins-riscv.cc}::OnStackReplacement (MacroAssembler * masm, OsrSourceTier source, Register maybe_target_code, Register expected_param_count)
Definition at line 1990 of file builtins-riscv.cc.
                                                       {
  Label jump_to_optimized_code;
  {
    // If maybe_target_code is not null, no need to call into runtime. A
    // precondition here is: if maybe_target_code is an InstructionStream
    // object, it must NOT be marked_for_deoptimization (callers must ensure
    // this).
    __ CompareTaggedAndBranch(&jump_to_optimized_code, ne, maybe_target_code,
                              Operand(Smi::zero()));
  }
  ASM_CODE_COMMENT(masm);
  {
    FrameScope scope(masm, StackFrame::INTERNAL);
    __ Push(expected_param_count);
    __ CallRuntime(Runtime::kCompileOptimizedOSR);
    __ Pop(expected_param_count);
  }
  // If the code object is null, just return to the caller.
  // If the code object is null, just return to the caller.
  __ CompareTaggedAndBranch(&jump_to_optimized_code, ne, maybe_target_code,
                            Operand(Smi::zero()));
  __ Ret();
  DCHECK_EQ(maybe_target_code, a0); // Already in the right spot.
  __ bind(&jump_to_optimized_code);
  const Register scratch(a2);
  CHECK(!AreAliased(maybe_target_code, expected_param_count, scratch));
  // OSR entry tracing.
  {
    Label next;
    __ li(scratch, ExternalReference::address_of_log_or_trace_osr());
    __ Lbu(scratch, MemOperand(scratch));
    __ Branch(&next, eq, scratch, Operand(zero_reg));
    {
      FrameScope scope(masm, StackFrame::INTERNAL);
      __ Push(maybe_target_code, expected_param_count);
      __ CallRuntime(Runtime::kLogOrTraceOptimizedOSREntry, 0);
      __ Pop(maybe_target_code, expected_param_count);
    }
    __ bind(&next);
  }
  if (source == OsrSourceTier::kInterpreter) {
    // Drop the handler frame that is be sitting on top of the actual
    // JavaScript frame. This is the case then OSR is triggered from bytecode.
    __ LeaveFrame(StackFrame::STUB);
  }
  // Check we are actually jumping to an OSR code object. This among other
  // things ensures that the object contains deoptimization data below.
  __ Load32U(scratch,
             FieldMemOperand(maybe_target_code, Code::kOsrOffsetOffset));
  __ SbxCheck(ne, AbortReason::kExpectedOsrCode, scratch,
              Operand(BytecodeOffset::None().ToInt()));
  // Check the target has a matching parameter count. This ensures that the OSR
  // code will correctly tear down our frame when leaving.
  __ Lhu(scratch,
         FieldMemOperand(maybe_target_code, Code::kParameterCountOffset));
  __ SmiUntag(expected_param_count);
  __ SbxCheck(eq, AbortReason::kOsrUnexpectedStackSize, scratch,
              Operand(expected_param_count));
  // Load deoptimization data from the code object.
  // <deopt_data> = <code>[#deoptimization_data_offset]
  __ LoadProtectedPointerField(
      scratch,
      FieldMemOperand(maybe_target_code,
                      Code::kDeoptimizationDataOrInterpreterDataOffset));
  // Load the OSR entrypoint offset from the deoptimization data.
  // <osr_offset> = <deopt_data>[#header_size + #osr_pc_offset]
  __ SmiUntagField(
      scratch,
      FieldMemOperand(scratch, TrustedFixedArray::OffsetOfElementAt(
                                   DeoptimizationData::kOsrPcOffsetIndex)));
  __ LoadCodeInstructionStart(maybe_target_code, maybe_target_code,
                              kJSEntrypointTag);
  // Compute the target address = code_entry + osr_offset
  // <entry_addr> = <code_entry> + <osr_offset>
  Generate_OSREntry(masm, maybe_target_code, Operand(scratch));
}
References __, v8::internal::AreAliased(), ASM_CODE_COMMENT, CHECK, DCHECK_EQ, v8::internal::eq, v8::internal::FieldMemOperand(), Generate_OSREntry(), v8::internal::kJSEntrypointTag, v8::internal::DeoptimizationData::kOsrPcOffsetIndex, v8::internal::ne, v8::internal::BytecodeOffset::None(), v8::internal::TaggedArrayBase< TrustedFixedArray, TrustedArrayShape, TrustedObjectLayout >::OffsetOfElementAt(), v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::SmiUntag(), v8::internal::anonymous_namespace{temporal-parser.cc}::ToInt(), and v8::internal::Smi::zero().
Referenced by v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER().
ReloadParentStack()
void v8::internal::anonymous_namespace{builtins-riscv.cc}::ReloadParentStack (MacroAssembler * masm, Register return_reg, Register return_value, Register context, Register tmp1, Register tmp2, Register tmp3)
Definition at line 3677 of file builtins-riscv.cc.
                                                     {
  ASM_CODE_COMMENT(masm);
  Register active_stack = tmp1;
  __ LoadRootRelative(active_stack, IsolateData::active_stack_offset());
  // Set a null pointer in the jump buffer's SP slot to indicate to the stack
  // frame iterator that this stack is empty.
  __ StoreWord(zero_reg, MemOperand(active_stack, wasm::kStackSpOffset));
  {
    UseScratchRegisterScope temps(masm);
    Register scratch = temps.Acquire();
    SwitchStackState(masm, active_stack, scratch, wasm::JumpBuffer::Active,
                     wasm::JumpBuffer::Retired);
  }
  Register parent = tmp2;
  __ LoadWord(parent, MemOperand(active_stack, wasm::kStackParentOffset));
  // Update active stack.
  __ StoreRootRelative(IsolateData::active_stack_offset(), parent);
  // Switch stack!
  SwitchStacks(masm, active_stack, true, tmp3,
               {return_reg, return_value, context, parent});
  LoadJumpBuffer(masm, parent, false, tmp3, wasm::JumpBuffer::Inactive);
}
References __, v8::internal::UseScratchRegisterScope::Acquire(), v8::internal::wasm::JumpBuffer::Active, ASM_CODE_COMMENT, v8::internal::wasm::JumpBuffer::Inactive, v8::internal::wasm::kStackParentOffset, v8::internal::wasm::kStackSpOffset, LoadJumpBuffer(), v8::internal::wasm::JumpBuffer::Retired, SwitchStacks(), and SwitchStackState().
Referenced by GenerateExceptionHandlingLandingPad(), and SwitchBackAndReturnPromise().
ResetFeedbackVectorOsrUrgency()
void v8::internal::anonymous_namespace{builtins-riscv.cc}::ResetFeedbackVectorOsrUrgency (MacroAssembler * masm, Register feedback_vector, Register scratch)
Definition at line 968 of file builtins-riscv.cc.
                                                                               {
  DCHECK(!AreAliased(feedback_vector, scratch));
  __ Lbu(scratch,
         FieldMemOperand(feedback_vector, FeedbackVector::kOsrStateOffset));
  __ And(scratch, scratch, Operand(~FeedbackVector::OsrUrgencyBits::kMask));
  __ Sb(scratch,
        FieldMemOperand(feedback_vector, FeedbackVector::kOsrStateOffset));
}
References __, v8::internal::wasm::liftoff::And(), v8::internal::AreAliased(), v8::internal::DCHECK(), and v8::internal::FieldMemOperand().
ResetJSFunctionAge()
void v8::internal::anonymous_namespace{builtins-riscv.cc}::ResetJSFunctionAge (MacroAssembler * masm, Register js_function, Register scratch)
Definition at line 959 of file builtins-riscv.cc.
                                          {
  const Register shared_function_info(scratch);
  __ LoadTaggedField(
      shared_function_info,
      FieldMemOperand(js_function, JSFunction::kSharedFunctionInfoOffset));
  ResetSharedFunctionInfoAge(masm, shared_function_info);
}
References __, v8::internal::FieldMemOperand(), and ResetSharedFunctionInfoAge().
ResetSharedFunctionInfoAge()
void v8::internal::anonymous_namespace{builtins-riscv.cc}::ResetSharedFunctionInfoAge (MacroAssembler * masm, Register sfi)
Definition at line 955 of file builtins-riscv.cc.
                                                                    {
  __ Sh(zero_reg, FieldMemOperand(sfi, SharedFunctionInfo::kAgeOffset));
}
References __, and v8::internal::FieldMemOperand().
Referenced by ResetJSFunctionAge().
ResetStackSwitchFrameStackSlots()
void v8::internal::anonymous_namespace{builtins-riscv.cc}::ResetStackSwitchFrameStackSlots (MacroAssembler * masm)
Definition at line 3844 of file builtins-riscv.cc.
                                                           {
  ASM_CODE_COMMENT(masm);
  __ StoreWord(zero_reg,
               MemOperand(fp, StackSwitchFrameConstants::kResultArrayOffset));
  __ StoreWord(zero_reg,
               MemOperand(fp, StackSwitchFrameConstants::kImplicitArgOffset));
}
References __, and ASM_CODE_COMMENT.
Referenced by Generate_WasmResumeHelper(), and SwitchToAllocatedStack().
RestoreParentSuspender()
void v8::internal::anonymous_namespace{builtins-riscv.cc}::RestoreParentSuspender (MacroAssembler * masm, Register tmp1)
Definition at line 3706 of file builtins-riscv.cc.
                                                                 {
  ASM_CODE_COMMENT(masm);
  Register suspender = tmp1;
  __ LoadRoot(suspender, RootIndex::kActiveSuspender);
  __ LoadTaggedField(
      suspender,
      FieldMemOperand(suspender, WasmSuspenderObject::kParentOffset));
  int32_t active_suspender_offset =
      MacroAssembler::RootRegisterOffsetForRootIndex(
          RootIndex::kActiveSuspender);
  __ StoreWord(suspender, MemOperand(kRootRegister, active_suspender_offset));
}
References __, ASM_CODE_COMMENT, v8::internal::FieldMemOperand(), v8::internal::kRootRegister, and v8::internal::MacroAssemblerBase::RootRegisterOffsetForRootIndex().
Referenced by GenerateExceptionHandlingLandingPad(), and SwitchBackAndReturnPromise().
SwitchBackAndReturnPromise()
void v8::internal::anonymous_namespace{builtins-riscv.cc}::SwitchBackAndReturnPromise (MacroAssembler * masm, RegisterAllocator & regs, wasm::Promise mode, Label * return_promise)
Definition at line 4156 of file builtins-riscv.cc.
                                                                         {
  ASM_CODE_COMMENT(masm);
  regs.ResetExcept();
  UseScratchRegisterScope temps(masm);
  // The return value of the wasm function becomes the parameter of the
  // FulfillPromise builtin, and the promise is the return value of this
  // wrapper.
  static const Builtin_FulfillPromise_InterfaceDescriptor desc;
  DEFINE_PINNED(promise, desc.GetRegisterParameter(0));
  DEFINE_PINNED(return_value, desc.GetRegisterParameter(1));
  DEFINE_SCOPED(tmp);
  DEFINE_SCOPED(tmp2);
  DEFINE_SCOPED(tmp3);
  if (mode == wasm::kPromise) {
    __ Move(return_value, kReturnRegister0);
    __ LoadRoot(promise, RootIndex::kActiveSuspender);
    __ LoadTaggedField(
        promise, FieldMemOperand(promise, WasmSuspenderObject::kPromiseOffset));
  }
  __ LoadWord(kContextRegister,
              MemOperand(fp, StackSwitchFrameConstants::kImplicitArgOffset));
  GetContextFromImplicitArg(masm, kContextRegister, tmp);
  ReloadParentStack(masm, promise, return_value, kContextRegister, tmp, tmp2,
                    tmp3);
  RestoreParentSuspender(masm, tmp);
  if (mode == wasm::kPromise) {
    __ li(tmp, 1);
    __ StoreWord(
        tmp, MemOperand(fp, StackSwitchFrameConstants::kGCScanSlotCountOffset));
    __ Push(promise);
    __ CallBuiltin(Builtin::kFulfillPromise);
    __ Pop(promise);
  }
  FREE_REG(promise);
  FREE_REG(return_value);
  __ bind(return_promise);
}
References __, ASM_CODE_COMMENT, DEFINE_PINNED, DEFINE_SCOPED, v8::internal::FieldMemOperand(), FREE_REG, GetContextFromImplicitArg(), v8::internal::kContextRegister, v8::internal::wasm::kPromise, v8::internal::kReturnRegister0, mode(), ReloadParentStack(), v8::internal::anonymous_namespace{builtins-riscv.cc}::RegisterAllocator::ResetExcept(), and RestoreParentSuspender().
Referenced by JSToWasmWrapperHelper().
SwitchFromTheCentralStackIfNeeded()
void v8::internal::anonymous_namespace{builtins-riscv.cc}::SwitchFromTheCentralStackIfNeeded (MacroAssembler * masm)
Definition at line 3202 of file builtins-riscv.cc.
                                                             {
  using ER = ExternalReference;
  Label no_stack_change;
  __ Branch(&no_stack_change, eq, kSwitchFlagRegister, Operand(zero_reg));
  {
    __ Push(kReturnRegister0, kReturnRegister1);
    __ li(kCArgRegs[0], ER::isolate_address(masm->isolate()));
    DCHECK_NE(kReturnRegister1, kCArgRegs[0]);
    __ PrepareCallCFunction(1, kReturnRegister1);
    __ CallCFunction(ER::wasm_switch_from_the_central_stack(), 1,
                     SetIsolateDataSlots::kNo);
    __ Pop(kReturnRegister0, kReturnRegister1);
  }
  SwitchSimulatorStackLimit(masm);
  __ mv(sp, kOldSPRegister);
  __ bind(&no_stack_change);
}
References __, DCHECK_NE, v8::internal::eq, v8::internal::MacroAssemblerBase::isolate(), v8::internal::kCArgRegs, kNo, kOldSPRegister, v8::internal::kReturnRegister0, v8::internal::kReturnRegister1, kSwitchFlagRegister, and SwitchSimulatorStackLimit().
Referenced by v8::internal::Builtins::Generate_CEntry().
SwitchSimulatorStackLimit()
void v8::internal::anonymous_namespace{builtins-riscv.cc}::SwitchSimulatorStackLimit (MacroAssembler * masm)
Definition at line 3134 of file builtins-riscv.cc.
                                                     {
  if (masm->options().enable_simulator_code) {
    UseScratchRegisterScope temps(masm);
    temps.Exclude(kSimulatorBreakArgument);
    __ RecordComment("-- Set simulator stack limit --");
    __ LoadStackLimit(kSimulatorBreakArgument, StackLimitKind::kRealStackLimit);
    __ break_(kExceptionIsSwitchStackLimit, false);
  }
}
References __, v8::internal::AssemblerOptions::enable_simulator_code, v8::internal::UseScratchRegisterScope::Exclude(), v8::internal::kExceptionIsSwitchStackLimit, v8::internal::kRealStackLimit, v8::internal::kSimulatorBreakArgument, and v8::internal::AssemblerBase::options().
Referenced by SwitchFromTheCentralStackIfNeeded(), and SwitchToTheCentralStackIfNeeded().
SwitchStackPointerAndSimulatorStackLimit()
void v8::internal::anonymous_namespace{builtins-riscv.cc}::SwitchStackPointerAndSimulatorStackLimit (MacroAssembler * masm, Register stack)
Definition at line 3614 of file builtins-riscv.cc.
                                                              {
  ASM_CODE_COMMENT(masm);
  if (masm->options().enable_simulator_code) {
    UseScratchRegisterScope temps(masm);
    temps.Exclude(kSimulatorBreakArgument);
    __ LoadWord(sp, MemOperand(stack, wasm::kStackSpOffset));
    __ LoadWord(kSimulatorBreakArgument,
                MemOperand(stack, wasm::kStackLimitOffset));
    __ break_(kExceptionIsSwitchStackLimit);
  } else {
    __ LoadWord(sp, MemOperand(stack, wasm::kStackSpOffset));
  }
}
References __, ASM_CODE_COMMENT, v8::internal::AssemblerOptions::enable_simulator_code, v8::internal::UseScratchRegisterScope::Exclude(), v8::internal::kExceptionIsSwitchStackLimit, v8::internal::kSimulatorBreakArgument, v8::internal::wasm::kStackLimitOffset, v8::internal::wasm::kStackSpOffset, v8::internal::AssemblerBase::options(), and v8::internal::stack.
Referenced by LoadJumpBuffer().
SwitchStacks()
void v8::internal::anonymous_namespace{builtins-riscv.cc}::SwitchStacks (MacroAssembler * masm, Register old_stack, bool return_switch, Register tmp, const std::initializer_list< Register > keep)
Definition at line 3656 of file builtins-riscv.cc.
                                                                          {
  ASM_CODE_COMMENT(masm);
  using ER = ExternalReference;
  for (auto reg : keep) {
    __ Push(reg);
  }
  {
    FrameScope scope(masm, StackFrame::MANUAL);
    // Move {old_stack} first in case it aliases kCArgRegs[0].
    __ mv(kCArgRegs[1], old_stack);
    __ li(kCArgRegs[0], ExternalReference::isolate_address(masm->isolate()));
    __ PrepareCallCFunction(2, tmp);
    __ CallCFunction(
        return_switch ? ER::wasm_return_switch() : ER::wasm_switch_stacks(), 2);
  }
  for (auto it = std::rbegin(keep); it != std::rend(keep); ++it) {
    __ Pop(*it);
  }
}
References __, ASM_CODE_COMMENT, v8::internal::MacroAssemblerBase::isolate(), v8::internal::ExternalReference::isolate_address(), v8::internal::kCArgRegs, v8::internal::StackFrame::MANUAL, and v8::internal::wasm::return_switch().
Referenced by Generate_WasmResumeHelper(), ReloadParentStack(), SwitchToAllocatedStack(), and v8::internal::Isolate::UnwindAndFindHandler().
SwitchStackState()
void v8::internal::anonymous_namespace{builtins-riscv.cc}::SwitchStackState (MacroAssembler * masm, Register stack, Register tmp, wasm::JumpBuffer::StackState old_state, wasm::JumpBuffer::StackState new_state)
Definition at line 3594 of file builtins-riscv.cc.
                                                          {
  ASM_CODE_COMMENT(masm);
#if V8_ENABLE_SANDBOX
  __ Lw(tmp, MemOperand(stack, wasm::kStackStateOffset));
  Label ok;
  // is branch32?
  __ Branch(&ok, eq, tmp, Operand(old_state));
  __ Trap();
  __ bind(&ok);
#endif
  __ li(tmp, new_state);
  __ Sw(tmp, MemOperand(stack, wasm::kStackStateOffset));
}
References __, ASM_CODE_COMMENT, v8::internal::eq, v8::internal::wasm::kStackStateOffset, and v8::internal::stack.
Referenced by Generate_WasmResumeHelper(), LoadJumpBuffer(), and ReloadParentStack().
SwitchToAllocatedStack()
void v8::internal::anonymous_namespace{builtins-riscv.cc}::SwitchToAllocatedStack (MacroAssembler * masm, RegisterAllocator & regs, Register wasm_instance, Register wrapper_buffer, Register & original_fp, Register & new_wrapper_buffer, Label * suspend)
Definition at line 4070 of file builtins-riscv.cc.
                                            {
  ASM_CODE_COMMENT(masm);
  UseScratchRegisterScope temps(masm);
  ResetStackSwitchFrameStackSlots(masm);
  DEFINE_SCOPED(scratch)
  DEFINE_REG(parent_stack)
  __ LoadRootRelative(parent_stack, IsolateData::active_stack_offset());
  __ LoadWord(parent_stack, MemOperand(parent_stack, wasm::kStackParentOffset));
  FillJumpBuffer(masm, parent_stack, suspend, scratch);
  SwitchStacks(masm, parent_stack, false, scratch,
               {wasm_instance, wrapper_buffer});
  FREE_REG(parent_stack);
  // Save the old stack's fp in t4, and use it to access the parameters in
  // the parent frame.
  regs.Pinned(t4, &original_fp);
  __ mv(original_fp, fp);
  DEFINE_REG(target_stack);
  __ LoadRootRelative(target_stack, IsolateData::active_stack_offset());
  LoadTargetJumpBuffer(masm, target_stack, scratch,
                       wasm::JumpBuffer::Suspended);
  FREE_REG(target_stack);
  // Push the loaded fp. We know it is null, because there is no frame yet,
  // so we could also push 0 directly. In any case we need to push it,
  // because this marks the base of the stack segment for
  // the stack frame iterator.
  __ EnterFrame(StackFrame::STACK_SWITCH);
  int stack_space =
      RoundUp(StackSwitchFrameConstants::kNumSpillSlots * kSystemPointerSize +
                  JSToWasmWrapperFrameConstants::kWrapperBufferSize,
              16);
  __ SubWord(sp, sp, Operand(stack_space));
  ASSIGN_REG(new_wrapper_buffer)
  __ mv(new_wrapper_buffer, sp);
  // Copy data needed for return handling from old wrapper buffer to new one.
  // kWrapperBufferRefReturnCount will be copied too, because 8 bytes are copied
  // at the same time.
  static_assert(JSToWasmWrapperFrameConstants::kWrapperBufferRefReturnCount ==
                JSToWasmWrapperFrameConstants::kWrapperBufferReturnCount + 4);
  __ LoadWord(
      scratch,
      MemOperand(wrapper_buffer,
                 JSToWasmWrapperFrameConstants::kWrapperBufferReturnCount));
  __ StoreWord(
      scratch,
      MemOperand(new_wrapper_buffer,
                 JSToWasmWrapperFrameConstants::kWrapperBufferReturnCount));
  __ LoadWord(
      scratch,
      MemOperand(
          wrapper_buffer,
          JSToWasmWrapperFrameConstants::kWrapperBufferSigRepresentationArray));
  __ StoreWord(
      scratch,
      MemOperand(
          new_wrapper_buffer,
          JSToWasmWrapperFrameConstants::kWrapperBufferSigRepresentationArray));
}
References __, ASM_CODE_COMMENT, ASSIGN_REG, DEFINE_REG, DEFINE_SCOPED, FillJumpBuffer(), FREE_REG, v8::internal::wasm::kStackParentOffset, v8::internal::kSystemPointerSize, LoadTargetJumpBuffer(), v8::internal::anonymous_namespace{builtins-riscv.cc}::RegisterAllocator::Pinned(), ResetStackSwitchFrameStackSlots(), RoundUp(), v8::internal::wasm::JumpBuffer::Suspended, and SwitchStacks().
Referenced by JSToWasmWrapperHelper().
SwitchToTheCentralStackIfNeeded()
void v8::internal::anonymous_namespace{builtins-riscv.cc}::SwitchToTheCentralStackIfNeeded (MacroAssembler * masm, Register argc_input, Register target_input, Register argv_input)
Definition at line 3147 of file builtins-riscv.cc.
                                                          {
  using ER = ExternalReference;
  __ li(kSwitchFlagRegister, 0);
  __ mv(kOldSPRegister, sp);
  // Using x2-x4 as temporary registers, because they will be rewritten
  // before exiting to native code anyway.
  ER on_central_stack_flag_loc = ER::Create(
      IsolateAddressId::kIsOnCentralStackFlagAddress, masm->isolate());
  const Register& on_central_stack_flag = a2;
  __ li(on_central_stack_flag, on_central_stack_flag_loc);
  __ Lb(on_central_stack_flag, MemOperand(on_central_stack_flag));
  Label do_not_need_to_switch;
  __ Branch(&do_not_need_to_switch, ne, on_central_stack_flag,
            Operand(zero_reg));
  // Switch to central stack.
  static constexpr Register central_stack_sp = a4;
  DCHECK(!AreAliased(central_stack_sp, argc_input, argv_input, target_input));
  {
    __ Push(argc_input, target_input, argv_input);
    __ PrepareCallCFunction(2, argc_input);
    __ li(kCArgRegs[0], ER::isolate_address(masm->isolate()));
    __ mv(kCArgRegs[1], kOldSPRegister);
    __ CallCFunction(ER::wasm_switch_to_the_central_stack(), 2,
                     SetIsolateDataSlots::kNo);
    __ mv(central_stack_sp, kReturnRegister0);
    __ Pop(argc_input, target_input, argv_input);
  }
  SwitchSimulatorStackLimit(masm);
  static constexpr int kReturnAddressSlotOffset = 1 * kSystemPointerSize;
  static constexpr int kPadding = 1 * kSystemPointerSize;
  __ SubWord(sp, central_stack_sp, kReturnAddressSlotOffset + kPadding);
#ifdef V8_TARGET_ARCH_RISCV32
  __ EnforceStackAlignment();
#endif
  __ li(kSwitchFlagRegister, 1);
  // Update the sp saved in the frame.
  // It will be used to calculate the callee pc during GC.
  // The pc is going to be on the new stack segment, so rewrite it here.
  __ AddWord(central_stack_sp, sp, kSystemPointerSize);
  __ StoreWord(central_stack_sp, MemOperand(fp, ExitFrameConstants::kSPOffset));
  __ bind(&do_not_need_to_switch);
}
References __, v8::internal::AreAliased(), v8::internal::DCHECK(), v8::internal::MacroAssemblerBase::isolate(), v8::internal::kCArgRegs, kNo, kOldSPRegister, v8::internal::kPadding, v8::internal::kReturnRegister0, v8::internal::ExitFrameConstants::kSPOffset, kSwitchFlagRegister, v8::internal::kSystemPointerSize, v8::internal::ne, and SwitchSimulatorStackLimit().
Referenced by v8::internal::compiler::CodeAssembler::CallBuiltin(), and v8::internal::Builtins::Generate_CEntry().
Variable Documentation
kOldSPRegister
constexpr Register v8::internal::anonymous_namespace{builtins-riscv.cc}::kOldSPRegister = s9 [static], [constexpr]
Definition at line 3144 of file builtins-riscv.cc.
Referenced by SwitchFromTheCentralStackIfNeeded(), and SwitchToTheCentralStackIfNeeded().
kSwitchFlagRegister
constexpr Register v8::internal::anonymous_namespace{builtins-riscv.cc}::kSwitchFlagRegister = s10 [static], [constexpr]
Definition at line 3145 of file builtins-riscv.cc.
Referenced by SwitchFromTheCentralStackIfNeeded(), and SwitchToTheCentralStackIfNeeded().