v8::internal::anonymous_namespace{builtins-struct.cc} Namespace Reference
Classes
struct NameHandleHasher
struct UniqueNameHandleEqual
Typedefs
using UniqueNameHandleSet = std::unordered_set< IndirectHandle< Name >, NameHandleHasher, UniqueNameHandleEqual >
Functions
Maybe< bool > CollectFieldsAndElements (Isolate *isolate, DirectHandle< JSReceiver > property_names, int num_properties, DirectHandleVector< Name > &field_names, std::set< uint32_t > &element_names)
Typedef Documentation
UniqueNameHandleSet
using v8::internal::anonymous_namespace{builtins-struct.cc}::UniqueNameHandleSet = typedef std::unordered_set<IndirectHandle<Name>, NameHandleHasher, UniqueNameHandleEqual>
Definition at line 34 of file builtins-struct.cc.
Function Documentation
CollectFieldsAndElements()
Maybe<bool> v8::internal::anonymous_namespace{builtins-struct.cc}::CollectFieldsAndElements (Isolate * isolate, DirectHandle< JSReceiver > property_names, int num_properties, DirectHandleVector< Name > & field_names, std::set< uint32_t > & element_names)
Definition at line 57 of file builtins-struct.cc.
                                                                      {
  Handle<Object> raw_property_name;
  Handle<Name> property_name;
  UniqueNameHandleSet field_names_set;
  for (int i = 0; i < num_properties; i++) {
    ASSIGN_RETURN_ON_EXCEPTION_VALUE(
        isolate, raw_property_name,
        JSReceiver::GetElement(isolate, property_names, i), Nothing<bool>());
    ASSIGN_RETURN_ON_EXCEPTION_VALUE(isolate, property_name,
                                     Object::ToName(isolate, raw_property_name),
                                     Nothing<bool>());
    bool is_duplicate;
    size_t index;
    if (!property_name->AsIntegerIndex(&index) ||
        index > JSObject::kMaxElementIndex) {
      property_name = isolate->factory()->InternalizeName(property_name);
      // TODO(v8:12547): Support Symbols?
      if (IsSymbol(*property_name)) {
        THROW_NEW_ERROR_RETURN_VALUE(
            isolate, NewTypeError(MessageTemplate::kSymbolToString),
            Nothing<bool>());
      }
      is_duplicate = !field_names_set.insert(property_name).second;
      // Keep the field names in the original order.
      if (!is_duplicate) field_names.push_back(property_name);
    } else {
      is_duplicate = !element_names.insert(static_cast<uint32_t>(index)).second;
    }
    if (is_duplicate) {
      THROW_NEW_ERROR_RETURN_VALUE(
          isolate,
          NewTypeError(MessageTemplate::kDuplicateTemplateProperty,
                       property_name),
          Nothing<bool>());
    }
  }
  return Just(true);
}
References ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::Isolate::factory(), v8::internal::JSReceiver::GetElement(), v8::internal::index, v8::Just(), v8::internal::JSObject::kMaxElementIndex, v8::internal::DirectHandleVector< T >::push_back(), and THROW_NEW_ERROR_RETURN_VALUE.
Referenced by v8::internal::BUILTIN().