v8::internal::compiler::anonymous_namespace{operation-typer.cc} Namespace Reference
Functions
double array_min (double a[], size_t n)
double array_max (double a[], size_t n)
Type JSType (Type type)
Function Documentation
array_max()
double v8::internal::compiler::anonymous_namespace{operation-typer.cc}::array_max (double a[], size_t n)
Definition at line 151 of file operation-typer.cc.
                                       {
  DCHECK_NE(0, n);
  double x = -V8_INFINITY;
  for (size_t i = 0; i < n; ++i) {
    if (!std::isnan(a[i])) {
      x = std::max(a[i], x);
    }
  }
  DCHECK(!std::isnan(x));
  return x == 0 ? 0 : x; // -0 -> 0
}
References v8::internal::DCHECK(), DCHECK_NE, v8::internal::anonymous_namespace{json-stringifier.cc}::i, and V8_INFINITY.
Referenced by v8::internal::compiler::OperationTyper::AddRanger(), v8::internal::compiler::OperationTyper::MultiplyRanger(), and v8::internal::compiler::OperationTyper::SubtractRanger().
array_min()
double v8::internal::compiler::anonymous_namespace{operation-typer.cc}::array_min (double a[], size_t n)
Definition at line 136 of file operation-typer.cc.
                                       {
  DCHECK_NE(0, n);
  double x = +V8_INFINITY;
  for (size_t i = 0; i < n; ++i) {
    if (!std::isnan(a[i])) {
      x = std::min(a[i], x);
    }
  }
  DCHECK(!std::isnan(x));
  return x == 0 ? 0 : x; // -0 -> 0
}
References v8::internal::DCHECK(), DCHECK_NE, v8::internal::anonymous_namespace{json-stringifier.cc}::i, and V8_INFINITY.
Referenced by v8::internal::compiler::OperationTyper::AddRanger(), v8::internal::compiler::OperationTyper::MultiplyRanger(), and v8::internal::compiler::OperationTyper::SubtractRanger().
JSType()
Type v8::internal::compiler::anonymous_namespace{operation-typer.cc}::JSType (Type type)
Definition at line 1277 of file operation-typer.cc.
                       {
  if (type.Is(Type::Boolean())) return Type::Boolean();
  if (type.Is(Type::String())) return Type::String();
  if (type.Is(Type::Number())) return Type::Number();
  if (type.Is(Type::BigInt())) return Type::BigInt();
  if (type.Is(Type::Undefined())) return Type::Undefined();
  if (type.Is(Type::Null())) return Type::Null();
  if (type.Is(Type::Symbol())) return Type::Symbol();
  if (type.Is(Type::Receiver())) return Type::Receiver(); // JS "Object"
  return Type::Any();
}
References v8::internal::compiler::turboshaft::Type::Any(), v8::internal::compiler::Null, v8::internal::tracing::type, and v8::internal::compiler::Undefined.
Referenced by v8::internal::anonymous_namespace{js-temporal-objects.cc}::ConstructRustWrappingType(), v8::internal::compiler::OperationTyper::SameValue(), and v8::internal::compiler::OperationTyper::StrictEqual().