v8::internal::anonymous_namespace{platform-embedded-file-writer-base.cc} Namespace Reference
Functions
EmbeddedTargetArch DefaultEmbeddedTargetArch ()
EmbeddedTargetArch ToEmbeddedTargetArch (const char *s)
EmbeddedTargetOs DefaultEmbeddedTargetOs ()
EmbeddedTargetOs ToEmbeddedTargetOs (const char *s)
Function Documentation
DefaultEmbeddedTargetArch()
EmbeddedTargetArch v8::internal::anonymous_namespace{platform-embedded-file-writer-base.cc}::DefaultEmbeddedTargetArch ()
Definition at line 83 of file platform-embedded-file-writer-base.cc.
                                               {
#if defined(V8_TARGET_ARCH_ARM)
  return EmbeddedTargetArch::kArm;
#elif defined(V8_TARGET_ARCH_ARM64)
  return EmbeddedTargetArch::kArm64;
#elif defined(V8_TARGET_ARCH_IA32)
  return EmbeddedTargetArch::kIA32;
#elif defined(V8_TARGET_ARCH_X64)
  return EmbeddedTargetArch::kX64;
#else
  return EmbeddedTargetArch::kGeneric;
#endif
}
References v8::internal::kArm, v8::internal::kArm64, v8::internal::kGeneric, v8::internal::kIA32, and v8::internal::kX64.
Referenced by ToEmbeddedTargetArch().
DefaultEmbeddedTargetOs()
EmbeddedTargetOs v8::internal::anonymous_namespace{platform-embedded-file-writer-base.cc}::DefaultEmbeddedTargetOs ()
Definition at line 116 of file platform-embedded-file-writer-base.cc.
                                           {
#if defined(V8_OS_AIX)
  return EmbeddedTargetOs::kAIX;
#elif defined(V8_OS_DARWIN)
  return EmbeddedTargetOs::kMac;
#elif defined(V8_OS_WIN)
  return EmbeddedTargetOs::kWin;
#elif defined(V8_OS_ZOS)
  return EmbeddedTargetOs::kZOS;
#else
  return EmbeddedTargetOs::kGeneric;
#endif
}
References v8::internal::kAIX, v8::internal::kGeneric, v8::internal::kMac, v8::internal::kWin, and v8::internal::kZOS.
Referenced by v8::internal::NewPlatformEmbeddedFileWriter(), and ToEmbeddedTargetOs().
ToEmbeddedTargetArch()
EmbeddedTargetArch v8::internal::anonymous_namespace{platform-embedded-file-writer-base.cc}::ToEmbeddedTargetArch (const char * s)
Definition at line 97 of file platform-embedded-file-writer-base.cc.
                                                       {
  if (s == nullptr) {
    return DefaultEmbeddedTargetArch();
  }
  std::string string(s);
  if (string == "arm") {
    return EmbeddedTargetArch::kArm;
  } else if (string == "arm64") {
    return EmbeddedTargetArch::kArm64;
  } else if (string == "ia32") {
    return EmbeddedTargetArch::kIA32;
  } else if (string == "x64") {
    return EmbeddedTargetArch::kX64;
  } else {
    return EmbeddedTargetArch::kGeneric;
  }
}
References DefaultEmbeddedTargetArch(), v8::internal::kArm, v8::internal::kArm64, v8::internal::kGeneric, v8::internal::kIA32, v8::internal::kX64, and v8::internal::string.
Referenced by v8::internal::NewPlatformEmbeddedFileWriter().
ToEmbeddedTargetOs()
EmbeddedTargetOs v8::internal::anonymous_namespace{platform-embedded-file-writer-base.cc}::ToEmbeddedTargetOs (const char * s)
Definition at line 130 of file platform-embedded-file-writer-base.cc.
                                                   {
  if (s == nullptr) {
    return DefaultEmbeddedTargetOs();
  }
  std::string string(s);
  // Python 3.9+ on IBM i returns os400 as sys.platform instead of aix
  if (string == "aix" || string == "os400") {
    return EmbeddedTargetOs::kAIX;
  } else if (string == "chromeos") {
    return EmbeddedTargetOs::kChromeOS;
  } else if (string == "fuchsia") {
    return EmbeddedTargetOs::kFuchsia;
  } else if (string == "ios" || string == "mac") {
    return EmbeddedTargetOs::kMac;
  } else if (string == "win") {
    return EmbeddedTargetOs::kWin;
  } else if (string == "starboard") {
    return EmbeddedTargetOs::kStarboard;
  } else if (string == "zos") {
    return EmbeddedTargetOs::kZOS;
  } else {
    return EmbeddedTargetOs::kGeneric;
  }
}
References DefaultEmbeddedTargetOs(), v8::internal::kAIX, v8::internal::kChromeOS, v8::internal::kFuchsia, v8::internal::kGeneric, v8::internal::kMac, v8::internal::kStarboard, v8::internal::kWin, v8::internal::kZOS, and v8::internal::string.
Referenced by v8::internal::NewPlatformEmbeddedFileWriter().