v8::anonymous_namespace{unwinder.cc} Namespace Reference
Functions
const uint8_t * CalculateEnd (const void *start, size_t length_in_bytes)
bool PCIsInCodeRange (const v8::MemoryRange &code_range, void *pc)
bool PCIsInCodePages (size_t code_pages_length, const MemoryRange *code_pages, void *pc)
bool IsInJSEntryRange (const JSEntryStubs &entry_stubs, void *pc)
bool IsInUnsafeJSEntryRange (const JSEntryStubs &entry_stubs, void *pc)
bool AddressIsInStack (const void *address, const void *stack_base, const void *stack_top)
void * GetReturnAddressFromFP (void *fp, void *pc, const JSEntryStubs &entry_stubs)
void * GetCallerFPFromFP (void *fp, void *pc, const JSEntryStubs &entry_stubs)
void * GetCallerSPFromFP (void *fp, void *pc, const JSEntryStubs &entry_stubs)
Function Documentation
AddressIsInStack()
bool v8::anonymous_namespace{unwinder.cc}::AddressIsInStack (const void * address, const void * stack_base, const void * stack_top)
Definition at line 73 of file unwinder.cc.
                                             {
  return address <= stack_base && address >= stack_top;
}
Referenced by v8::Unwinder::TryUnwindV8Frames().
CalculateEnd()
const uint8_t* v8::anonymous_namespace{unwinder.cc}::CalculateEnd (const void * start, size_t length_in_bytes)
Definition at line 25 of file unwinder.cc.
                                                                       {
  // Given that the length of the memory range is in bytes and it is not
  // necessarily aligned, we need to do the pointer arithmetic in uint8_t* here.
  const uint8_t* start_as_byte = reinterpret_cast<const uint8_t*>(start);
  return start_as_byte + length_in_bytes;
}
Referenced by PCIsInCodePages(), and PCIsInCodeRange().
GetCallerFPFromFP()
void* v8::anonymous_namespace{unwinder.cc}::GetCallerFPFromFP (void * fp, void * pc, const JSEntryStubs & entry_stubs)
Definition at line 92 of file unwinder.cc.
                                                                             {
  int caller_fp_offset = i::CommonFrameConstants::kCallerFPOffset;
#if V8_TARGET_ARCH_ARM64 || V8_TARGET_ARCH_ARM
  if (IsInJSEntryRange(entry_stubs, pc)) {
    caller_fp_offset = i::EntryFrameConstants::kDirectCallerFPOffset;
  }
#endif
  return reinterpret_cast<void*>(
      Load(reinterpret_cast<i::Address>(fp) + caller_fp_offset));
}
References IsInJSEntryRange(), v8::internal::CommonFrameConstants::kCallerFPOffset, v8::internal::EntryFrameConstants::kDirectCallerFPOffset, and v8::Load().
Referenced by v8::Unwinder::TryUnwindV8Frames().
GetCallerSPFromFP()
void* v8::anonymous_namespace{unwinder.cc}::GetCallerSPFromFP (void * fp, void * pc, const JSEntryStubs & entry_stubs)
Definition at line 103 of file unwinder.cc.
                                                                             {
  int caller_sp_offset = i::CommonFrameConstants::kCallerSPOffset;
#if V8_TARGET_ARCH_ARM64 || V8_TARGET_ARCH_ARM
  if (IsInJSEntryRange(entry_stubs, pc)) {
    caller_sp_offset = i::EntryFrameConstants::kDirectCallerSPOffset;
  }
#endif
  return reinterpret_cast<void*>(reinterpret_cast<i::Address>(fp) +
                                 caller_sp_offset);
}
References IsInJSEntryRange(), v8::internal::CommonFrameConstants::kCallerSPOffset, and v8::internal::EntryFrameConstants::kDirectCallerSPOffset.
Referenced by v8::Unwinder::TryUnwindV8Frames().
GetReturnAddressFromFP()
void* v8::anonymous_namespace{unwinder.cc}::GetReturnAddressFromFP (void * fp, void * pc, const JSEntryStubs & entry_stubs)
Definition at line 78 of file unwinder.cc.
                                                              {
  int caller_pc_offset = i::CommonFrameConstants::kCallerPCOffset;
// TODO(solanes): Implement the JSEntry range case also for x64 here and below.
#if V8_TARGET_ARCH_ARM64 || V8_TARGET_ARCH_ARM
  if (IsInJSEntryRange(entry_stubs, pc)) {
    caller_pc_offset = i::EntryFrameConstants::kDirectCallerPCOffset;
  }
#endif
  i::Address ret_addr =
      Load(reinterpret_cast<i::Address>(fp) + caller_pc_offset);
  return reinterpret_cast<void*>(i::PointerAuthentication::StripPAC(ret_addr));
}
References IsInJSEntryRange(), v8::internal::CommonFrameConstants::kCallerPCOffset, v8::internal::EntryFrameConstants::kDirectCallerPCOffset, v8::Load(), and v8::internal::PointerAuthentication::StripPAC().
Referenced by v8::Unwinder::TryUnwindV8Frames().
IsInJSEntryRange()
bool v8::anonymous_namespace{unwinder.cc}::IsInJSEntryRange (const JSEntryStubs & entry_stubs, void * pc)
Definition at line 58 of file unwinder.cc.
                                                                 {
  return PCIsInCodeRange(entry_stubs.js_entry_stub.code, pc) ||
         PCIsInCodeRange(entry_stubs.js_construct_entry_stub.code, pc) ||
         PCIsInCodeRange(entry_stubs.js_run_microtasks_entry_stub.code, pc);
}
References v8::JSEntryStub::code, v8::JSEntryStubs::js_construct_entry_stub, v8::JSEntryStubs::js_entry_stub, v8::JSEntryStubs::js_run_microtasks_entry_stub, and PCIsInCodeRange().
Referenced by GetCallerFPFromFP(), GetCallerSPFromFP(), GetReturnAddressFromFP(), IsInUnsafeJSEntryRange(), and v8::Unwinder::TryUnwindV8Frames().
IsInUnsafeJSEntryRange()
bool v8::anonymous_namespace{unwinder.cc}::IsInUnsafeJSEntryRange (const JSEntryStubs & entry_stubs, void * pc)
Definition at line 64 of file unwinder.cc.
                                                                       {
  return IsInJSEntryRange(entry_stubs, pc);
  // TODO(petermarshall): We can be more precise by checking whether we are
  // in JSEntry but after frame setup and before frame teardown, in which case
  // we are safe to unwind the stack. For now, we bail out if the PC is anywhere
  // within JSEntry.
}
References IsInJSEntryRange().
Referenced by v8::Unwinder::TryUnwindV8Frames().
PCIsInCodePages()
bool v8::anonymous_namespace{unwinder.cc}::PCIsInCodePages (size_t code_pages_length, const MemoryRange * code_pages, void * pc)
Definition at line 39 of file unwinder.cc.
                               {
  DCHECK(std::is_sorted(code_pages, code_pages + code_pages_length,
                        [](const MemoryRange& a, const MemoryRange& b) {
                          return a.start < b.start;
                        }));
  MemoryRange fake_range{pc, 1};
  auto it =
      std::upper_bound(code_pages, code_pages + code_pages_length, fake_range,
                       [](const MemoryRange& a, const MemoryRange& b) {
                         return a.start < b.start;
                       });
  DCHECK_IMPLIES(it != code_pages + code_pages_length, pc < it->start);
  if (it == code_pages) return false;
  --it;
  return it->start <= pc && pc < CalculateEnd(it->start, it->length_in_bytes);
}
References CalculateEnd(), DCHECK, DCHECK_IMPLIES, and v8::MemoryRange::start.
Referenced by v8::Unwinder::PCIsInV8().
PCIsInCodeRange()
bool v8::anonymous_namespace{unwinder.cc}::PCIsInCodeRange (const v8::MemoryRange & code_range, void * pc)
Definition at line 32 of file unwinder.cc.
                                                                {
  return pc >= code_range.start &&
         pc < CalculateEnd(code_range.start, code_range.length_in_bytes);
}
References CalculateEnd(), v8::MemoryRange::length_in_bytes, and v8::MemoryRange::start.
Referenced by IsInJSEntryRange().