v8::internal::anonymous_namespace{marking-barrier.cc} Namespace Reference
Functions
template<typename Space >
void SetGenerationPageFlags (Space *space, MarkingMode marking_mode)
template<typename Space >
void ActivateSpace (Space *space, MarkingMode marking_mode)
template<typename Space >
void DeactivateSpace (Space *space)
void ActivateSpaces (Heap *heap, MarkingMode marking_mode)
void DeactivateSpaces (Heap *heap, MarkingMode marking_mode)
Function Documentation
ActivateSpace()
template<typename Space >
void v8::internal::anonymous_namespace{marking-barrier.cc}::ActivateSpace (Space * space, MarkingMode marking_mode)
Definition at line 247 of file marking-barrier.cc.
                                                           {
  SetGenerationPageFlags(space, marking_mode);
}
References SetGenerationPageFlags(), and space.
Referenced by ActivateSpaces().
ActivateSpaces()
void v8::internal::anonymous_namespace{marking-barrier.cc}::ActivateSpaces (Heap * heap, MarkingMode marking_mode)
Definition at line 256 of file marking-barrier.cc.
                                                          {
  ActivateSpace(heap->old_space(), marking_mode);
  ActivateSpace(heap->lo_space(), marking_mode);
  if (heap->new_space()) {
    DCHECK(!v8_flags.sticky_mark_bits);
    ActivateSpace(heap->new_space(), marking_mode);
  }
  ActivateSpace(heap->new_lo_space(), marking_mode);
  {
    RwxMemoryWriteScope scope("For writing flags.");
    ActivateSpace(heap->code_space(), marking_mode);
    ActivateSpace(heap->code_lo_space(), marking_mode);
  }
  if (marking_mode == MarkingMode::kMajorMarking) {
    if (heap->shared_space()) {
      ActivateSpace(heap->shared_space(), marking_mode);
    }
    if (heap->shared_lo_space()) {
      ActivateSpace(heap->shared_lo_space(), marking_mode);
    }
  }
  ActivateSpace(heap->trusted_space(), marking_mode);
  ActivateSpace(heap->trusted_lo_space(), marking_mode);
}
References ActivateSpace(), v8::internal::DCHECK(), v8::internal::kMajorMarking, and v8::internal::v8_flags.
Referenced by v8::internal::MarkingBarrier::ActivateAll(), and v8::internal::MarkingBarrier::ActivateYoung().
DeactivateSpace()
template<typename Space >
void v8::internal::anonymous_namespace{marking-barrier.cc}::DeactivateSpace (Space * space)
Definition at line 252 of file marking-barrier.cc.
                                   {
  SetGenerationPageFlags(space, MarkingMode::kNoMarking);
}
References v8::internal::kNoMarking, SetGenerationPageFlags(), and space.
Referenced by DeactivateSpaces().
DeactivateSpaces()
void v8::internal::anonymous_namespace{marking-barrier.cc}::DeactivateSpaces (Heap * heap, MarkingMode marking_mode)
Definition at line 283 of file marking-barrier.cc.
                                                            {
  DeactivateSpace(heap->old_space());
  DeactivateSpace(heap->lo_space());
  if (heap->new_space()) {
    DCHECK(!v8_flags.sticky_mark_bits);
    DeactivateSpace(heap->new_space());
  }
  DeactivateSpace(heap->new_lo_space());
  {
    RwxMemoryWriteScope scope("For writing flags.");
    DeactivateSpace(heap->code_space());
    DeactivateSpace(heap->code_lo_space());
  }
  if (marking_mode == MarkingMode::kMajorMarking) {
    if (heap->shared_space()) {
      DeactivateSpace(heap->shared_space());
    }
    if (heap->shared_lo_space()) {
      DeactivateSpace(heap->shared_lo_space());
    }
  }
  DeactivateSpace(heap->trusted_space());
  DeactivateSpace(heap->trusted_lo_space());
}
References v8::internal::DCHECK(), DeactivateSpace(), v8::internal::kMajorMarking, and v8::internal::v8_flags.
Referenced by v8::internal::MarkingBarrier::DeactivateAll(), and v8::internal::MarkingBarrier::DeactivateYoung().
SetGenerationPageFlags()
template<typename Space >
void v8::internal::anonymous_namespace{marking-barrier.cc}::SetGenerationPageFlags (Space * space, MarkingMode marking_mode)
Definition at line 217 of file marking-barrier.cc.
                                                                    {
  if constexpr (std::is_same_v<Space, OldSpace> ||
                std::is_same_v<Space, SharedSpace> ||
                std::is_same_v<Space, TrustedSpace> ||
                std::is_same_v<Space, CodeSpace>) {
    for (auto* p : *space) {
      p->SetOldGenerationPageFlags(marking_mode);
    }
  } else if constexpr (std::is_same_v<Space, OldLargeObjectSpace> ||
                       std::is_same_v<Space, SharedLargeObjectSpace> ||
                       std::is_same_v<Space, TrustedLargeObjectSpace> ||
                       std::is_same_v<Space, CodeLargeObjectSpace>) {
    for (auto* p : *space) {
      DCHECK(p->Chunk()->IsLargePage());
      p->SetOldGenerationPageFlags(marking_mode);
    }
  } else if constexpr (std::is_same_v<Space, NewSpace>) {
    for (auto* p : *space) {
      p->SetYoungGenerationPageFlags(marking_mode);
    }
  } else {
    static_assert(std::is_same_v<Space, NewLargeObjectSpace>);
    for (auto* p : *space) {
      DCHECK(p->Chunk()->IsLargePage());
      p->SetYoungGenerationPageFlags(marking_mode);
    }
  }
}
References v8::internal::DCHECK(), and space.
Referenced by ActivateSpace(), and DeactivateSpace().