v8::internal::anonymous_namespace{factory.cc} Namespace Reference
Functions
void ThrowInvalidEncodedStringBytes (Isolate *isolate, MessageTemplate message)
template<typename Decoder , typename PeekBytes >
MaybeHandle< String > NewStringFromBytes (Isolate *isolate, PeekBytes peek_bytes, AllocationType allocation, MessageTemplate message)
template<typename PeekBytes >
MaybeHandle< String > NewStringFromUtf8Variant (Isolate *isolate, PeekBytes peek_bytes, unibrow::Utf8Variant utf8_variant, AllocationType allocation)
template<typename T >
void initialize_length (Tagged< T > array, int length)
template<> void initialize_length< PropertyArray > (Tagged< PropertyArray > array, int length)
void InitEmbedderFields (Tagged< JSObject > obj, Tagged< Object > initial_value)
void InitializeTemplate (Tagged< TemplateInfo > that, bool is_cacheable)
void InitializeTemplateWithProperties (Tagged< TemplateInfoWithProperties > that, ReadOnlyRoots roots, bool is_cacheable)
Function Documentation
InitEmbedderFields()
void v8::internal::anonymous_namespace{factory.cc}::InitEmbedderFields (Tagged< JSObject > obj, Tagged< Object > initial_value) [inline]
Definition at line 2617 of file factory.cc.
                                                             {
  for (int i = 0; i < obj->GetEmbedderFieldCount(); i++) {
    EmbedderDataSlot(obj, i).Initialize(initial_value);
  }
}
References v8::internal::EmbedderDataSlot::Initialize().
Referenced by v8::internal::Factory::NewJSArrayBufferView(), and v8::internal::Factory::NewJSPromiseWithoutHook().
initialize_length()
template<typename T >
void v8::internal::anonymous_namespace{factory.cc}::initialize_length (Tagged< T > array, int length)
Definition at line 2608 of file factory.cc.
                                                    {
  array->set_length(length);
}
References v8::internal::Factory::length.
Referenced by v8::internal::Factory::CopyArrayAndGrow(), and v8::internal::Factory::CopyArrayWithMap().
initialize_length< PropertyArray >()
template<>
void v8::internal::anonymous_namespace{factory.cc}::initialize_length< PropertyArray > (Tagged< PropertyArray > array, int length)
Definition at line 2613 of file factory.cc.
                                                                               {
  array->initialize_length(length);
}
References v8::internal::Factory::length.
InitializeTemplate()
void v8::internal::anonymous_namespace{factory.cc}::InitializeTemplate (Tagged< TemplateInfo > that, bool is_cacheable) [inline]
Definition at line 4663 of file factory.cc.
                                                                             {
  that->set_template_info_flags(0);
  that->set_serial_number(TemplateInfo::kUninitializedSerialNumber);
  that->set_is_cacheable(is_cacheable);
}
References v8::internal::TemplateInfo::kUninitializedSerialNumber.
Referenced by InitializeTemplateWithProperties(), and v8::internal::Factory::NewDictionaryTemplateInfo().
InitializeTemplateWithProperties()
void v8::internal::anonymous_namespace{factory.cc}::InitializeTemplateWithProperties (Tagged< TemplateInfoWithProperties > that, ReadOnlyRoots roots, bool is_cacheable) [inline]
Definition at line 4669 of file factory.cc.
                       {
  InitializeTemplate(that, is_cacheable);
  that->set_number_of_properties(0);
  that->set_property_list(roots.undefined_value(), SKIP_WRITE_BARRIER);
  that->set_property_accessors(roots.undefined_value(), SKIP_WRITE_BARRIER);
}
References InitializeTemplate(), and v8::internal::SKIP_WRITE_BARRIER.
Referenced by v8::internal::Factory::NewFunctionTemplateInfo(), and v8::internal::Factory::NewObjectTemplateInfo().
NewStringFromBytes()
template<typename Decoder , typename PeekBytes >
MaybeHandle<String> v8::internal::anonymous_namespace{factory.cc}::NewStringFromBytes (Isolate * isolate, PeekBytes peek_bytes, AllocationType allocation, MessageTemplate message)
Definition at line 678 of file factory.cc.
                                                                {
  Decoder decoder(peek_bytes());
  if (decoder.is_invalid()) {
    if (message != MessageTemplate::kNone) {
      ThrowInvalidEncodedStringBytes(isolate, message);
    }
    return MaybeHandle<String>();
  }
  if (decoder.utf16_length() == 0) return isolate->factory()->empty_string();
  if (decoder.is_one_byte()) {
    if (decoder.utf16_length() == 1) {
      uint8_t codepoint;
      decoder.Decode(&codepoint, peek_bytes());
      return isolate->factory()->LookupSingleCharacterStringFromCode(codepoint);
    }
    // Allocate string.
    Handle<SeqOneByteString> result;
    ASSIGN_RETURN_ON_EXCEPTION(isolate, result,
                               isolate->factory()->NewRawOneByteString(
                                   decoder.utf16_length(), allocation));
    DisallowGarbageCollection no_gc;
    decoder.Decode(result->GetChars(no_gc), peek_bytes());
    return result;
  }
  // Allocate string.
  Handle<SeqTwoByteString> result;
  ASSIGN_RETURN_ON_EXCEPTION(isolate, result,
                             isolate->factory()->NewRawTwoByteString(
                                 decoder.utf16_length(), allocation));
  DisallowGarbageCollection no_gc;
  decoder.Decode(result->GetChars(no_gc), peek_bytes());
  return result;
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::Decoder< V >::Decode(), v8::internal::Isolate::factory(), v8::internal::Factory::isolate(), v8::internal::FactoryBase< Impl >::LookupSingleCharacterStringFromCode(), v8::internal::FactoryBase< Impl >::NewRawOneByteString(), v8::internal::FactoryBase< Impl >::NewRawTwoByteString(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, and ThrowInvalidEncodedStringBytes().
NewStringFromUtf8Variant()
template<typename PeekBytes >
MaybeHandle<String> v8::internal::anonymous_namespace{factory.cc}::NewStringFromUtf8Variant (Isolate * isolate, PeekBytes peek_bytes, unibrow::Utf8Variant utf8_variant, AllocationType allocation)
Definition at line 720 of file factory.cc.
                                                                        {
  switch (utf8_variant) {
    case unibrow::Utf8Variant::kLossyUtf8:
      return NewStringFromBytes<Utf8Decoder>(isolate, peek_bytes, allocation,
                                             MessageTemplate::kNone);
#if V8_ENABLE_WEBASSEMBLY
    case unibrow::Utf8Variant::kUtf8:
      return NewStringFromBytes<StrictUtf8Decoder>(
          isolate, peek_bytes, allocation,
          MessageTemplate::kWasmTrapStringInvalidUtf8);
    case unibrow::Utf8Variant::kUtf8NoTrap:
      return NewStringFromBytes<StrictUtf8Decoder>(
          isolate, peek_bytes, allocation, MessageTemplate::kNone);
    case unibrow::Utf8Variant::kWtf8:
      return NewStringFromBytes<Wtf8Decoder>(
          isolate, peek_bytes, allocation,
          MessageTemplate::kWasmTrapStringInvalidWtf8);
#endif
  }
}
References v8::internal::Factory::isolate(), and unibrow::kLossyUtf8.
Referenced by v8::internal::Factory::NewStringFromUtf8().
ThrowInvalidEncodedStringBytes()
void v8::internal::anonymous_namespace{factory.cc}::ThrowInvalidEncodedStringBytes (Isolate * isolate, MessageTemplate message)
Definition at line 659 of file factory.cc.
                                                                               {
#if V8_ENABLE_WEBASSEMBLY
  DCHECK(message == MessageTemplate::kWasmTrapStringInvalidWtf8 ||
         message == MessageTemplate::kWasmTrapStringInvalidUtf8);
  DirectHandle<JSObject> error_obj =
      isolate->factory()->NewWasmRuntimeError(message);
  JSObject::AddProperty(isolate, error_obj,
                        isolate->factory()->wasm_uncatchable_symbol(),
                        isolate->factory()->true_value(), NONE);
  isolate->Throw(*error_obj);
#else
  // The default in JS-land is to use Utf8Variant::kLossyUtf8, which never
  // throws an error, so if there is no WebAssembly compiled in we'll never
  // get here.
  UNREACHABLE();
#endif // V8_ENABLE_WEBASSEMBLY
}
References v8::internal::JSObject::AddProperty(), v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::internal::Factory::isolate(), v8::internal::NONE, v8::internal::Isolate::Throw(), and v8::internal::UNREACHABLE().
Referenced by NewStringFromBytes().