v8::internal::interpreter::anonymous_namespace{interpreter.cc} Namespace Reference
Functions
Builtin BuiltinIndexFromBytecode (Bytecode bytecode, OperandScale operand_scale)
void MaybePrintAst (ParseInfo *parse_info, UnoptimizedCompilationInfo *compilation_info)
bool ShouldPrintBytecode (DirectHandle< SharedFunctionInfo > shared)
Function Documentation
BuiltinIndexFromBytecode()
Builtin v8::internal::interpreter::anonymous_namespace{interpreter.cc}::BuiltinIndexFromBytecode (Bytecode bytecode, OperandScale operand_scale)
Definition at line 85 of file interpreter.cc.
                                                             {
  int index = static_cast<int>(bytecode);
  if (operand_scale == OperandScale::kSingle) {
    if (Bytecodes::IsShortStar(bytecode)) {
      index = static_cast<int>(Bytecode::kFirstShortStar);
    } else if (bytecode > Bytecode::kLastShortStar) {
      // Adjust the index due to repeated handlers.
      index -= Bytecodes::kShortStarCount - 1;
    }
  } else {
    // The table contains uint8_t offsets starting at 0 with
    // kIllegalBytecodeHandlerEncoding for illegal bytecode/scale combinations.
    uint8_t offset = kWideBytecodeToBuiltinsMapping[index];
    if (offset == kIllegalBytecodeHandlerEncoding) {
      return Builtin::kIllegalHandler;
    } else {
      index = kNumberOfBytecodeHandlers + offset;
      if (operand_scale == OperandScale::kQuadruple) {
        index += kNumberOfWideBytecodeHandlers;
      }
    }
  }
  return Builtins::FromInt(static_cast<int>(Builtin::kFirstBytecodeHandler) +
                           index);
}
References v8::internal::Builtins::FromInt(), v8::internal::index, v8::internal::interpreter::Bytecodes::IsShortStar(), v8::internal::interpreter::kFirstShortStar, v8::internal::interpreter::kIllegalBytecodeHandlerEncoding, v8::internal::interpreter::kLastShortStar, and v8::internal::interpreter::Bytecodes::kShortStarCount.
Referenced by v8::internal::interpreter::Interpreter::GetBytecodeHandler(), and v8::internal::interpreter::Interpreter::Initialize().
MaybePrintAst()
void v8::internal::interpreter::anonymous_namespace{interpreter.cc}::MaybePrintAst (ParseInfo * parse_info, UnoptimizedCompilationInfo * compilation_info)
Definition at line 140 of file interpreter.cc.
                                                                 {
  if (!v8_flags.print_ast) return;
  StdoutStream os;
  std::unique_ptr<char[]> name = compilation_info->literal()->GetDebugName();
  os << "[generating bytecode for function: " << name.get() << "]" << std::endl;
#ifdef DEBUG
  os << "--- AST ---" << std::endl
     << AstPrinter(parse_info->stack_limit())
            .PrintProgram(compilation_info->literal())
     << std::endl;
#endif // DEBUG
}
References v8::internal::FunctionLiteral::GetDebugName(), v8::internal::UnoptimizedCompilationInfo::literal(), v8::internal::name, v8::internal::ParseInfo::stack_limit(), and v8::internal::v8_flags.
Referenced by v8::internal::interpreter::InterpreterCompilationJob::ExecuteJobImpl().
ShouldPrintBytecode()
bool v8::internal::interpreter::anonymous_namespace{interpreter.cc}::ShouldPrintBytecode (DirectHandle< SharedFunctionInfo > shared)
Definition at line 155 of file interpreter.cc.
                                                                  {
  if (!v8_flags.print_bytecode) return false;
  // Checks whether function passed the filter.
  if (shared->is_toplevel()) {
    base::Vector<const char> filter =
        base::CStrVector(v8_flags.print_bytecode_filter);
    return filter.empty() || (filter.length() == 1 && filter[0] == '*');
  } else {
    return shared->PassesFilter(v8_flags.print_bytecode_filter);
  }
}
References v8::base::CStrVector(), v8::base::Vector< T >::empty(), v8::base::Vector< T >::length(), and v8::internal::v8_flags.
Referenced by v8::internal::interpreter::InterpreterCompilationJob::DoFinalizeJobImpl().