v8::internal::anonymous_namespace{flags.cc} Namespace Reference
Classes
class ImplicationProcessor
Functions
void PrintFlagsJSONArray (std::ostream &os, const std::vector< const char * > &flags)
void PrintFeatureFlagsJSONObject (std::ostream &os, const std::vector< const char * > &inprogress_flags, const std::vector< const char * > &staged_flags, const std::vector< const char * > &shipping_flags)
Function Documentation
PrintFeatureFlagsJSONObject()
void v8::internal::anonymous_namespace{flags.cc}::PrintFeatureFlagsJSONObject (std::ostream & os, const std::vector< const char * > & inprogress_flags, const std::vector< const char * > & staged_flags, const std::vector< const char * > & shipping_flags)
Definition at line 890 of file flags.cc.
                                                  {
  os << "{\n";
  os << " \"in-progress\": ";
  PrintFlagsJSONArray(os, inprogress_flags);
  os << ",\n";
  os << " \"staged\": ";
  PrintFlagsJSONArray(os, staged_flags);
  os << ",\n";
  os << " \"shipping\": ";
  PrintFlagsJSONArray(os, shipping_flags);
  os << "\n";
  os << " }";
}
References PrintFlagsJSONArray().
Referenced by v8::internal::FlagList::PrintFeatureFlagsJSON().
PrintFlagsJSONArray()
void v8::internal::anonymous_namespace{flags.cc}::PrintFlagsJSONArray (std::ostream & os, const std::vector< const char * > & flags)
Definition at line 874 of file flags.cc.
                                                              {
  if (flags.empty()) {
    os << "[]";
  } else {
    os << "[\n";
    bool first = true;
    for (const auto& flag : flags) {
      if (!first) os << ",\n";
      os << " \"" << flag << "\"";
      first = false;
    }
    os << "\n" << " ]";
  }
}
References v8::internal::flags.
Referenced by PrintFeatureFlagsJSONObject().