v8::internal::anonymous_namespace{incremental-marking.cc} Namespace Reference
Functions
base::TimeDelta GetMaxDuration (StepOrigin step_origin)
Variables
static constexpr size_t kMajorGCYoungGenerationAllocationObserverStep = 64 * KB
static constexpr size_t kMajorGCOldGenerationAllocationObserverStep = 256 * KB
static constexpr v8::base::TimeDelta kMaxStepSizeOnTask
static constexpr v8::base::TimeDelta kMaxStepSizeOnAllocation
static constexpr size_t kV8ActivationThreshold = 8 * MB
static constexpr size_t kEmbedderActivationThreshold = 8 * MB
Function Documentation
GetMaxDuration()
base::TimeDelta v8::internal::anonymous_namespace{incremental-marking.cc}::GetMaxDuration (StepOrigin step_origin)
Definition at line 66 of file incremental-marking.cc.
                                                     {
  if (v8_flags.predictable) {
    return base::TimeDelta::Max();
  }
  switch (step_origin) {
    case StepOrigin::kTask:
      return kMaxStepSizeOnTask;
    case StepOrigin::kV8:
      return kMaxStepSizeOnAllocation;
  }
}
References kMaxStepSizeOnAllocation, kMaxStepSizeOnTask, v8::internal::kTask, v8::internal::kV8, v8::base::TimeDelta::Max(), and v8::internal::v8_flags.
Referenced by v8::internal::IncrementalMarking::AdvanceAndFinalizeIfComplete(), and v8::internal::IncrementalMarking::AdvanceOnAllocation().
Variable Documentation
kEmbedderActivationThreshold
constexpr size_t v8::internal::anonymous_namespace{incremental-marking.cc}::kEmbedderActivationThreshold = 8 * MB [static], [constexpr]
Definition at line 60 of file incremental-marking.cc.
Referenced by v8::internal::IncrementalMarking::IsBelowActivationThresholds().
kMajorGCOldGenerationAllocationObserverStep
constexpr size_t v8::internal::anonymous_namespace{incremental-marking.cc}::kMajorGCOldGenerationAllocationObserverStep = 256 * KB [static], [constexpr]
Definition at line 51 of file incremental-marking.cc.
kMajorGCYoungGenerationAllocationObserverStep
constexpr size_t v8::internal::anonymous_namespace{incremental-marking.cc}::kMajorGCYoungGenerationAllocationObserverStep = 64 * KB [static], [constexpr]
Definition at line 50 of file incremental-marking.cc.
kMaxStepSizeOnAllocation
constexpr v8::base::TimeDelta v8::internal::anonymous_namespace{incremental-marking.cc}::kMaxStepSizeOnAllocation [static], [constexpr]
Initial value:
=
    v8::base::TimeDelta::FromMilliseconds(5)
Definition at line 55 of file incremental-marking.cc.
Referenced by GetMaxDuration().
kMaxStepSizeOnTask
constexpr v8::base::TimeDelta v8::internal::anonymous_namespace{incremental-marking.cc}::kMaxStepSizeOnTask [static], [constexpr]
Initial value:
=
    v8::base::TimeDelta::FromMilliseconds(1)
Definition at line 53 of file incremental-marking.cc.
Referenced by GetMaxDuration().
kV8ActivationThreshold
constexpr size_t v8::internal::anonymous_namespace{incremental-marking.cc}::kV8ActivationThreshold = 8 * MB [static], [constexpr]
Definition at line 59 of file incremental-marking.cc.
Referenced by v8::internal::IncrementalMarking::IsBelowActivationThresholds().