v8::internal::compiler::anonymous_namespace{access-info.cc} Namespace Reference
Typedefs
using AccessorsObjectGetter = std::function< Handle< Object >()>
Functions
bool CanInlinePropertyAccess (MapRef map, AccessMode access_mode)
template<class RefT >
bool OptionalRefEquals (OptionalRef< RefT > lhs, OptionalRef< RefT > rhs)
template<class T >
void AppendVector (ZoneVector< T > *dst, const ZoneVector< T > &src)
PropertyAccessInfo AccessorAccessInfoHelper (Isolate *isolate, Zone *zone, JSHeapBroker *broker, const AccessInfoFactory *ai_factory, MapRef receiver_map, NameRef name, MapRef holder_map, OptionalJSObjectRef holder, AccessMode access_mode, AccessorsObjectGetter get_accessors)
Maybe< ElementsKind > GeneralizeElementsKind (ElementsKind this_kind, ElementsKind that_kind)
Typedef Documentation
AccessorsObjectGetter
using v8::internal::compiler::anonymous_namespace{access-info.cc}::AccessorsObjectGetter = typedef std::function<Handle<Object>()>
Definition at line 694 of file access-info.cc.
Function Documentation
AccessorAccessInfoHelper()
PropertyAccessInfo v8::internal::compiler::anonymous_namespace{access-info.cc}::AccessorAccessInfoHelper (Isolate * isolate, Zone * zone, JSHeapBroker * broker, const AccessInfoFactory * ai_factory, MapRef receiver_map, NameRef name, MapRef holder_map, OptionalJSObjectRef holder, AccessMode access_mode, AccessorsObjectGetter get_accessors)
Definition at line 696 of file access-info.cc.
                                         {
  if (holder_map.instance_type() == JS_MODULE_NAMESPACE_TYPE) {
    DCHECK(holder_map.object()->is_prototype_map());
    DirectHandle<PrototypeInfo> proto_info = broker->CanonicalPersistentHandle(
        Cast<PrototypeInfo>(holder_map.object()->prototype_info()));
    DirectHandle<JSModuleNamespace> module_namespace =
        broker->CanonicalPersistentHandle(
            Cast<JSModuleNamespace>(proto_info->module_namespace()));
    Handle<Cell> cell = broker->CanonicalPersistentHandle(
        Cast<Cell>(module_namespace->module()->exports()->Lookup(
            isolate, name.object(),
            Smi::ToInt(Object::GetHash(*name.object())))));
    if (IsAnyStore(access_mode)) {
      // ES#sec-module-namespace-exotic-objects-set-p-v-receiver
      // ES#sec-module-namespace-exotic-objects-defineownproperty-p-desc
      //
      // Storing to a module namespace object is always an error or a no-op in
      // JS.
      return PropertyAccessInfo::Invalid(zone);
    }
    if (IsTheHole(cell->value(kRelaxedLoad), isolate)) {
      // This module has not been fully initialized yet.
      return PropertyAccessInfo::Invalid(zone);
    }
    OptionalCellRef cell_ref = TryMakeRef(broker, cell);
    if (!cell_ref.has_value()) {
      return PropertyAccessInfo::Invalid(zone);
    }
    return PropertyAccessInfo::ModuleExport(zone, receiver_map,
                                            cell_ref.value());
  }
  if (access_mode == AccessMode::kHas) {
    // kHas is not supported for dictionary mode objects.
    DCHECK(!holder_map.is_dictionary_map());
    // HasProperty checks don't call getter/setters, existence is sufficient.
    return PropertyAccessInfo::FastAccessorConstant(zone, receiver_map, holder,
                                                    {}, {});
  }
  DirectHandle<Object> maybe_accessors = get_accessors();
  if (!IsAccessorPair(*maybe_accessors)) {
    return PropertyAccessInfo::Invalid(zone);
  }
  DirectHandle<AccessorPair> accessors = Cast<AccessorPair>(maybe_accessors);
  Handle<Object> accessor = broker->CanonicalPersistentHandle(
      access_mode == AccessMode::kLoad ? accessors->getter(kAcquireLoad)
                                       : accessors->setter(kAcquireLoad));
  OptionalObjectRef accessor_ref = TryMakeRef(broker, accessor);
  if (!accessor_ref.has_value()) return PropertyAccessInfo::Invalid(zone);
  OptionalJSObjectRef api_holder_ref;
  if (!IsJSFunction(*accessor)) {
    CallOptimization optimization(broker->local_isolate_or_isolate(), accessor);
    if (!optimization.is_simple_api_call() ||
        optimization.IsCrossContextLazyAccessorPair(
            *broker->target_native_context().object(), *holder_map.object())) {
      return PropertyAccessInfo::Invalid(zone);
    }
    if (DEBUG_BOOL && holder.has_value()) {
      std::optional<Tagged<NativeContext>> holder_creation_context =
          holder->object()->GetCreationContext();
      CHECK(holder_creation_context.has_value());
      CHECK_EQ(*broker->target_native_context().object(),
               holder_creation_context.value());
    }
    CallOptimization::HolderLookup holder_lookup;
    Handle<JSObject> api_holder = broker->CanonicalPersistentHandle(
        optimization.LookupHolderOfExpectedType(
            broker->local_isolate_or_isolate(), receiver_map.object(),
            &holder_lookup));
    if (holder_lookup == CallOptimization::kHolderNotFound) {
      return PropertyAccessInfo::Invalid(zone);
    }
    DCHECK_IMPLIES(holder_lookup == CallOptimization::kHolderIsReceiver,
                   api_holder.is_null());
    DCHECK_IMPLIES(holder_lookup == CallOptimization::kHolderFound,
                   !api_holder.is_null());
    if (!api_holder.is_null()) {
      api_holder_ref = TryMakeRef(broker, api_holder);
      if (!api_holder_ref.has_value()) return PropertyAccessInfo::Invalid(zone);
    }
  }
  if (access_mode == AccessMode::kLoad) {
    std::optional<Tagged<Name>> cached_property_name =
        FunctionTemplateInfo::TryGetCachedPropertyName(isolate, *accessor);
    if (cached_property_name.has_value()) {
      OptionalNameRef cached_property_name_ref =
          TryMakeRef(broker, cached_property_name.value());
      if (cached_property_name_ref.has_value()) {
        PropertyAccessInfo access_info = ai_factory->ComputePropertyAccessInfo(
            holder_map, cached_property_name_ref.value(), access_mode);
        if (!access_info.IsInvalid()) return access_info;
      }
    }
  }
  if (holder_map.is_dictionary_map()) {
    CHECK(!api_holder_ref.has_value());
    return PropertyAccessInfo::DictionaryProtoAccessorConstant(
        zone, receiver_map, holder, accessor_ref.value(), api_holder_ref, name);
  } else {
    return PropertyAccessInfo::FastAccessorConstant(
        zone, receiver_map, holder, accessor_ref.value(), api_holder_ref);
  }
}
References broker(), CHECK, CHECK_EQ, v8::internal::compiler::AccessInfoFactory::ComputePropertyAccessInfo(), v8::internal::DCHECK(), DCHECK_IMPLIES, DEBUG_BOOL, v8::internal::compiler::PropertyAccessInfo::DictionaryProtoAccessorConstant(), v8::internal::compiler::PropertyAccessInfo::FastAccessorConstant(), v8::internal::Object::GetHash(), v8::internal::compiler::MapRef::instance_type(), v8::internal::compiler::PropertyAccessInfo::Invalid(), v8::internal::compiler::MapRef::is_dictionary_map(), v8::internal::HandleBase::is_null(), v8::internal::compiler::IsAnyStore(), v8::internal::compiler::PropertyAccessInfo::IsInvalid(), v8::kAcquireLoad, v8::internal::compiler::kHas, v8::internal::CallOptimization::kHolderFound, v8::internal::CallOptimization::kHolderIsReceiver, v8::internal::CallOptimization::kHolderNotFound, v8::internal::compiler::kLoad, v8::kRelaxedLoad, v8::internal::compiler::PropertyAccessInfo::ModuleExport(), v8::internal::name, v8::internal::compiler::MapRef::object(), optimization, v8::internal::Smi::ToInt(), v8::internal::FunctionTemplateInfo::TryGetCachedPropertyName(), and v8::internal::compiler::TryMakeRef().
Referenced by v8::internal::compiler::AccessInfoFactory::ComputeAccessorDescriptorAccessInfo(), and v8::internal::compiler::AccessInfoFactory::ComputeDictionaryProtoAccessInfo().
AppendVector()
template<class T >
void v8::internal::compiler::anonymous_namespace{access-info.cc}::AppendVector (ZoneVector< T > * dst, const ZoneVector< T > & src)
Definition at line 301 of file access-info.cc.
                                                                {
  dst->insert(dst->end(), src.begin(), src.end());
}
References v8::internal::ZoneVector< T >::begin(), v8::internal::ZoneVector< T >::end(), and v8::internal::ZoneVector< T >::insert().
Referenced by v8::internal::compiler::PropertyAccessInfo::Merge().
CanInlinePropertyAccess()
bool v8::internal::compiler::anonymous_namespace{access-info.cc}::CanInlinePropertyAccess (MapRef map, AccessMode access_mode)
Definition at line 34 of file access-info.cc.
                                                                 {
  // We can inline property access to prototypes of all primitives, except
  // the special Oddball ones that have no wrapper counterparts (i.e. Null,
  // Undefined and TheHole).
  // We can only inline accesses to dictionary mode holders if the access is a
  // load and the holder is a prototype. The latter ensures a 1:1
  // relationship between the map and the object (and therefore the property
  // dictionary).
  static_assert(ODDBALL_TYPE == LAST_PRIMITIVE_HEAP_OBJECT_TYPE);
  if (IsBooleanMap(*map.object())) return true;
  if (map.instance_type() < LAST_PRIMITIVE_HEAP_OBJECT_TYPE) return true;
  if (IsJSObjectMap(*map.object())) {
    if (map.is_dictionary_map()) {
      if (!V8_DICT_PROPERTY_CONST_TRACKING_BOOL) return false;
      return access_mode == AccessMode::kLoad &&
             map.object()->is_prototype_map();
    }
    return !map.object()->has_named_interceptor() &&
           // TODO(verwaest): Allowlist contexts to which we have access.
           !map.is_access_check_needed();
  }
#if V8_ENABLE_WEBASSEMBLY
  if (IsWasmObjectMap(*map.object())) {
    DCHECK(!map.object()->has_named_interceptor());
    DCHECK(!map.is_access_check_needed());
    // Accesses to Wasm objects all go through the prototype chain, but
    // we can't express that in this helper function.
    return true;
  }
#endif // V8_ENABLE_WEBASSEMBLY
  return false;
}
References v8::internal::DCHECK(), v8::internal::compiler::MapRef::instance_type(), v8::internal::compiler::MapRef::is_access_check_needed(), v8::internal::compiler::MapRef::is_dictionary_map(), v8::internal::IsBooleanMap(), v8::internal::compiler::kLoad, v8::internal::compiler::MapRef::object(), and V8_DICT_PROPERTY_CONST_TRACKING_BOOL.
Referenced by v8::internal::compiler::AccessInfoFactory::ComputePropertyAccessInfo().
GeneralizeElementsKind()
Maybe<ElementsKind> v8::internal::compiler::anonymous_namespace{access-info.cc}::GeneralizeElementsKind (ElementsKind this_kind, ElementsKind that_kind)
Definition at line 1206 of file access-info.cc.
                                                                   {
  if (IsHoleyElementsKind(this_kind)) {
    that_kind = GetHoleyElementsKind(that_kind);
  } else if (IsHoleyElementsKind(that_kind)) {
    this_kind = GetHoleyElementsKind(this_kind);
  }
  if (this_kind == that_kind) return Just(this_kind);
  if (IsDoubleElementsKind(that_kind) == IsDoubleElementsKind(this_kind)) {
    if (IsMoreGeneralElementsKindTransition(that_kind, this_kind)) {
      return Just(this_kind);
    }
    if (IsMoreGeneralElementsKindTransition(this_kind, that_kind)) {
      return Just(that_kind);
    }
  }
  return Nothing<ElementsKind>();
}
References v8::internal::GetHoleyElementsKind(), v8::internal::IsDoubleElementsKind(), v8::internal::IsHoleyElementsKind(), v8::internal::IsMoreGeneralElementsKindTransition(), and v8::Just().
Referenced by v8::internal::compiler::AccessInfoFactory::ConsolidateElementLoad().
OptionalRefEquals()
template<class RefT >
bool v8::internal::compiler::anonymous_namespace{access-info.cc}::OptionalRefEquals (OptionalRef< RefT > lhs, OptionalRef< RefT > rhs)
Definition at line 294 of file access-info.cc.
                                                                     {
  if (!lhs.has_value()) return !rhs.has_value();
  if (!rhs.has_value()) return false;
  return lhs->equals(rhs.value());
}
References v8::internal::compiler::OptionalRef< TRef >::has_value(), and v8::internal::compiler::OptionalRef< TRef >::value().
Referenced by v8::internal::compiler::PropertyAccessInfo::Merge().