v8::debug::anonymous_namespace{debug-interface.cc} Namespace Reference
Typedefs
using FlagFilter = std::function< bool(i::IsStaticFlag)>
using VariableModeFilter = std::function< bool(i::VariableMode)>
using ContextLocalIterator = std::function< void(i::VariableMode, i::Handle< i::String >, i::Handle< i::Object >)>
Functions
i::Handle< i::String > GetBigIntStringPresentationHandle (i::Isolate *i_isolate, i::DirectHandle< i::BigInt > i_bigint)
void ForEachContextLocal (i::Isolate *isolate, i::DirectHandle< i::Context > context, const VariableModeFilter &var_mode_filter, const FlagFilter &flag_filter, const ContextLocalIterator &context_local_it)
int GetSmiValue (i::DirectHandle< i::FixedArray > array, int index)
bool CompareBreakLocation (const i::BreakLocation &loc1, const i::BreakLocation &loc2)
Typedef Documentation
ContextLocalIterator
using v8::debug::anonymous_namespace{debug-interface.cc}::ContextLocalIterator = typedef std::function<void(i::VariableMode, i::Handle<i::String>, i::Handle<i::Object>)>
Definition at line 202 of file debug-interface.cc.
FlagFilter
using v8::debug::anonymous_namespace{debug-interface.cc}::FlagFilter = typedef std::function<bool(i::IsStaticFlag)>
Definition at line 200 of file debug-interface.cc.
VariableModeFilter
using v8::debug::anonymous_namespace{debug-interface.cc}::VariableModeFilter = typedef std::function<bool(i::VariableMode)>
Definition at line 201 of file debug-interface.cc.
Function Documentation
CompareBreakLocation()
bool v8::debug::anonymous_namespace{debug-interface.cc}::CompareBreakLocation (const i::BreakLocation & loc1, const i::BreakLocation & loc2)
Definition at line 613 of file debug-interface.cc.
                                                      {
  return loc1.position() < loc2.position();
}
References v8::internal::BreakLocation::position().
Referenced by v8::debug::Script::GetPossibleBreakpoints().
ForEachContextLocal()
void v8::debug::anonymous_namespace{debug-interface.cc}::ForEachContextLocal (i::Isolate * isolate, i::DirectHandle< i::Context > context, const VariableModeFilter & var_mode_filter, const FlagFilter & flag_filter, const ContextLocalIterator & context_local_it)
Definition at line 205 of file debug-interface.cc.
                                                                       {
  i::DisallowJavascriptExecutionDebugOnly no_execution(isolate);
  i::DisallowExceptionsDebugOnly no_exceptions(isolate);
  i::DirectHandle<i::ScopeInfo> scope_info(context->scope_info(), isolate);
  for (auto it : i::ScopeInfo::IterateLocalNames(scope_info)) {
    i::Handle<i::String> name(it->name(), isolate);
    i::VariableMode mode = scope_info->ContextLocalMode(it->index());
    if (!var_mode_filter(mode)) {
      continue;
    }
    i::IsStaticFlag flag = scope_info->ContextLocalIsStaticFlag(it->index());
    if (!flag_filter(flag)) {
      continue;
    }
    int context_index = scope_info->ContextHeaderLength() + it->index();
    i::Handle<i::Object> slot_value(context->GetNoCell(context_index), isolate);
    context_local_it(mode, name, slot_value);
  }
}
References v8::internal::ScopeInfo::IterateLocalNames(), mode(), and name.
Referenced by v8::debug::GetPrivateMembers().
GetBigIntStringPresentationHandle()
i::Handle<i::String> v8::debug::anonymous_namespace{debug-interface.cc}::GetBigIntStringPresentationHandle (i::Isolate * i_isolate, i::DirectHandle< i::BigInt > i_bigint)
Definition at line 70 of file debug-interface.cc.
                                                          {
  // For large BigInts computing the decimal string representation
  // can take a long time, so we go with hexadecimal in that case.
  int radix = (i_bigint->Words64Count() > 100 * 1000) ? 16 : 10;
  i::Handle<i::String> string_value =
      i::BigInt::ToString(i_isolate, i_bigint, radix, i::kDontThrow)
          .ToHandleChecked();
  if (radix == 16) {
    if (i_bigint->IsNegative()) {
      string_value =
          i_isolate->factory()
              ->NewConsString(
                  i_isolate->factory()->NewStringFromAsciiChecked("-0x"),
                  i_isolate->factory()->NewProperSubString(
                      string_value, 1, string_value->length() - 1))
              .ToHandleChecked();
    } else {
      string_value =
          i_isolate->factory()
              ->NewConsString(
                  i_isolate->factory()->NewStringFromAsciiChecked("0x"),
                  string_value)
              .ToHandleChecked();
    }
  }
  return string_value;
}
References v8::internal::Isolate::factory(), v8::internal::kDontThrow, v8::internal::FactoryBase< Impl >::NewConsString(), v8::internal::Factory::NewProperSubString(), v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), and v8::internal::BigInt::ToString().
Referenced by v8::debug::GetBigIntDescription(), and v8::debug::GetBigIntStringValue().
GetSmiValue()
int v8::debug::anonymous_namespace{debug-interface.cc}::GetSmiValue (i::DirectHandle< i::FixedArray > array, int index)
Definition at line 609 of file debug-interface.cc.
                                                             {
  return i::Smi::ToInt(array->get(index));
}
References v8::internal::index, and v8::internal::Smi::ToInt().
Referenced by v8::internal::maglev::MaglevGraphBuilder::ConvertForStoring(), v8::internal::maglev::MaglevGraphBuilder::CreateJSArray(), v8::internal::maglev::MaglevGraphBuilder::GetAccumulatorSmi(), v8::internal::maglev::MaglevGraphBuilder::GetSmiValue(), and v8::debug::Script::GetSourceOffset().