v8::bigint Namespace Reference
Namespaces
 anonymous_namespace{bitwise.cc}
 anonymous_namespace{div-barrett.cc}
 anonymous_namespace{div-burnikel.cc}
 anonymous_namespace{div-helpers.cc}
 anonymous_namespace{mul-fft.cc}
 anonymous_namespace{mul-karatsuba.cc}
 anonymous_namespace{mul-toom.cc}
 anonymous_namespace{tostring.cc}
Classes
class ProcessorImpl
class Storage
class ScratchDigits
class Digits
class RWDigits
class Platform
struct RightShiftState
class Processor
class FromStringAccumulator
class ShiftedDigits
Typedefs
using digit_t = uintptr_t
using signed_digit_t = intptr_t
Enumerations
enum class Status { kOk
, kInterrupted
 }
Functions
constexpr int DivideBarrettScratchSpace (int n)
constexpr int InvertNewtonScratchSpace (int n)
constexpr int InvertScratchSpace (int n)
int Compare (Digits A, Digits B)
void Add (RWDigits Z, Digits X, Digits Y)
bool AddSigned (RWDigits Z, Digits X, bool x_negative, Digits Y, bool y_negative)
void AddOne (RWDigits Z, Digits X)
void Subtract (RWDigits Z, Digits X, Digits Y)
bool SubtractSigned (RWDigits Z, Digits X, bool x_negative, Digits Y, bool y_negative)
void SubtractOne (RWDigits Z, Digits X)
void BitwiseAnd_PosPos (RWDigits Z, Digits X, Digits Y)
void BitwiseAnd_NegNeg (RWDigits Z, Digits X, Digits Y)
void BitwiseAnd_PosNeg (RWDigits Z, Digits X, Digits Y)
void BitwiseOr_PosPos (RWDigits Z, Digits X, Digits Y)
void BitwiseOr_NegNeg (RWDigits Z, Digits X, Digits Y)
void BitwiseOr_PosNeg (RWDigits Z, Digits X, Digits Y)
void BitwiseXor_PosPos (RWDigits Z, Digits X, Digits Y)
void BitwiseXor_NegNeg (RWDigits Z, Digits X, Digits Y)
void BitwiseXor_PosNeg (RWDigits Z, Digits X, Digits Y)
void LeftShift (RWDigits Z, Digits X, digit_t shift)
void RightShift (RWDigits Z, Digits X, digit_t shift, const RightShiftState &state)
bool AsIntN (RWDigits Z, Digits X, bool x_negative, int n)
void AsUintN_Pos (RWDigits Z, Digits X, int n)
void AsUintN_Neg (RWDigits Z, Digits X, int n)
int AddResultLength (int x_length, int y_length)
int AddSignedResultLength (int x_length, int y_length, bool same_sign)
int SubtractResultLength (int x_length, int y_length)
int SubtractSignedResultLength (int x_length, int y_length, bool same_sign)
int MultiplyResultLength (Digits X, Digits Y)
int DivideResultLength (Digits A, Digits B)
int ModuloResultLength (Digits B)
uint32_t ToStringResultLength (Digits X, int radix, bool sign)
int RightShift_ResultLength (Digits X, bool x_sign, digit_t shift, RightShiftState *state)
int AsIntNResultLength (Digits X, bool x_negative, int n)
int AsUintN_Pos_ResultLength (Digits X, int n)
int AsUintN_Neg_ResultLength (int n)
constexpr bool digit_ismax (digit_t x)
digit_t digit_add2 (digit_t a, digit_t b, digit_t *carry)
digit_t digit_add3 (digit_t a, digit_t b, digit_t c, digit_t *carry)
digit_t digit_sub (digit_t a, digit_t b, digit_t *borrow)
digit_t digit_sub2 (digit_t a, digit_t b, digit_t borrow_in, digit_t *borrow_out)
digit_t digit_mul (digit_t a, digit_t b, digit_t *high)
static digit_t digit_div (digit_t high, digit_t low, digit_t divisor, digit_t *remainder)
void LeftShift (RWDigits Z, Digits X, int shift)
void RightShift (RWDigits Z, Digits X, int shift)
void PutAt (RWDigits Z, Digits A, int count)
digit_t InplaceAdd (RWDigits Z, Digits X)
digit_t InplaceSub (RWDigits Z, Digits X)
bool ProductGreaterThan (digit_t factor1, digit_t factor2, digit_t high, digit_t low)
constexpr int RoundUp (int x, int y)
template<typename T >
constexpr int CountLeadingZeros (T value) requires(std
constexpr int CountLeadingZeros (uint32_t value)
constexpr int CountTrailingZeros (uint32_t value)
constexpr int BitLength (int n)
constexpr bool IsPowerOfTwo (int value)
digit_t AddAndReturnOverflow (RWDigits Z, Digits X)
digit_t SubAndReturnBorrow (RWDigits Z, Digits X)
digit_t AddAndReturnCarry (RWDigits Z, Digits X, Digits Y)
digit_t SubtractAndReturnBorrow (RWDigits Z, Digits X, Digits Y)
void Add (RWDigits X, digit_t y)
void Subtract (RWDigits X, digit_t y)
bool IsDigitNormalized (Digits X)
bool IsBitNormalized (Digits X)
bool GreaterThanOrEqual (Digits A, Digits B)
int BitLength (Digits X)
Variables
constexpr int kKaratsubaThreshold = 34
constexpr int kToomThreshold = 193
constexpr int kFftThreshold = 1500
constexpr int kFftInnerThreshold = 200
constexpr int kBurnikelThreshold = 57
constexpr int kNewtonInversionThreshold = 50
constexpr int kToStringFastThreshold = 43
constexpr int kFromStringLargeThreshold = 300
constexpr int kInvertNewtonExtraSpace = 5
static constexpr int kDigitBits = 1 << kLog2DigitBits
constexpr int kBarrettThreshold = 13310
constexpr char kStringZapValue = '?'
static constexpr int kStackParts = 8
static constexpr uint8_t kCharValue []
static constexpr uint8_t kCharBits [] = {1, 2, 3, 0, 4, 0, 0, 0, 5}
static constexpr int kHalfDigitBits = kDigitBits / 2
static constexpr digit_t kHalfDigitBase = digit_t{1} << kHalfDigitBits
static constexpr digit_t kHalfDigitMask = kHalfDigitBase - 1
Typedef Documentation
digit_t
using v8::bigint::digit_t = typedef uintptr_t
Definition at line 34 of file bigint.h.
signed_digit_t
using v8::bigint::signed_digit_t = typedef intptr_t
Definition at line 35 of file bigint.h.
Enumeration Type Documentation
Status
enum v8::bigint::Status [strong]
Enumerator
kOk
kInterrupted
Definition at line 283 of file bigint.h.
{ kOk, kInterrupted };
Function Documentation
Add() [1/2]
void v8::bigint::Add (RWDigits X, digit_t y) [inline]
Definition at line 23 of file vector-arithmetic.h.
                                       {
  digit_t carry = y;
  int i = 0;
  do {
    X[i] = digit_add2(X[i], carry, &carry);
    i++;
  } while (carry != 0);
}
References v8::internal::carry, digit_add2(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, X(), and v8::base::internal::y.
Add() [2/2]
void v8::bigint::Add (RWDigits Z, Digits X, Digits Y)
Definition at line 41 of file vector-arithmetic.cc.
                                         {
  if (X.len() < Y.len()) {
    return Add(Z, Y, X);
  }
  int i = 0;
  digit_t carry = 0;
  for (; i < Y.len(); i++) {
    Z[i] = digit_add3(X[i], Y[i], carry, &carry);
  }
  for (; i < X.len(); i++) {
    Z[i] = digit_add2(X[i], carry, &carry);
  }
  for (; i < Z.len(); i++) {
    Z[i] = carry;
    carry = 0;
  }
}
References v8::internal::carry, digit_add2(), digit_add3(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::bigint::Digits::len(), and X().
Referenced by v8::internal::OrderedNameDictionaryHandler::Add(), v8::internal::OrderedHashSetHandler::Add(), v8::internal::OrderedHashMapHandler::Add(), v8::internal::ZoneList< T >::AddBlock(), v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::AddImpl(), v8::internal::anonymous_namespace{elements.cc}::SlowSloppyArgumentsElementsAccessor::AddImpl(), v8::internal::KeyAccumulator::AddKey(), v8::internal::anonymous_namespace{js-atomics-synchronization.cc}::AddPromiseToNativeContext(), v8::anonymous_namespace{api.cc}::AddPropertiesAndElementsToObject(), AddSigned(), v8::internal::OrderedHashMapHandler::AdjustRepresentation(), v8::internal::OrderedHashSetHandler::AdjustRepresentation(), v8::internal::OrderedNameDictionaryHandler::AdjustRepresentation(), v8::internal::maglev::anonymous_namespace{maglev-assembler-arm64.cc}::AllocateRaw(), v8::internal::LookupIterator::ApplyTransitionToDataProperty(), v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::compiler::turboshaft::Assembler< Reducers >::Bind(), BitwiseAnd_NegNeg(), BitwiseOr_NegNeg(), BitwiseOr_PosNeg(), BitwiseXor_PosNeg(), v8::internal::JSRegExpResultIndices::BuildIndices(), v8::internal::anonymous_namespace{templates.cc}::CreateSlowJSObjectWithProperties(), v8::internal::anonymous_namespace{literal-objects.cc}::DictionaryAddNoUpdateNextEnumerationIndex(), v8::bigint::ProcessorImpl::FromStringClassic(), v8::internal::BaseConsumedPreparseData< Tagged< PreparseData > >::GetDataForSkippableFunction(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::NamedDebugProxy< T, id, Provider >::GetNameTable(), v8::internal::JsonStringifier::InitializeReplacer(), v8::internal::ZoneList< T >::InsertAt(), v8::internal::Heap::KeepDuringJob(), v8::internal::anonymous_namespace{js-objects.cc}::MigrateFastToSlow(), v8::internal::MutableBigInt_AbsoluteAddAndCanonicalize(), v8::internal::Factory::NewJSGlobalObject(), v8::internal::compiler::turboshaft::anonymous_namespace{loop-unrolling-reducer.cc}::Next(), v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::NormalizeImpl(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::anonymous_namespace{elements.cc}::SlowSloppyArgumentsElementsAccessor::ReconfigureImpl(), v8::internal::compiler::JSTypedLowering::ReduceJSIncrement(), v8::internal::compiler::JSTypeHintLowering::ReduceUnaryOperation(), RightShift(), v8::internal::RUNTIME_FUNCTION(), v8::internal::JSObject::SetNormalizedProperty(), v8::internal::JSProxy::SetPrivateSymbol(), v8::internal::wasm::TurboshaftGraphBuildingInterface::SimdOp(), v8::internal::anonymous_namespace{js-date-time-format.cc}::SpecialTimeZoneMap::SpecialTimeZoneMap(), v8::internal::maglev::anonymous_namespace{maglev-assembler-arm64.cc}::SubSizeAndTagObject(), SubtractSigned(), v8::internal::compiler::turboshaft::Typer::TypeFloatBinop(), v8::internal::FutexEmulation::WaitAsync(), v8::internal::PreparseDataBuilder::ByteData::WriteQuarter(), v8::internal::PreparseDataBuilder::ByteData::WriteUint8(), and v8::internal::PreparseDataBuilder::ByteData::WriteVarint32().
AddAndReturnCarry()
digit_t v8::bigint::AddAndReturnCarry (RWDigits Z, Digits X, Digits Y)
Definition at line 75 of file vector-arithmetic.cc.
                                                          {
  DCHECK(Z.len() >= Y.len() && X.len() >= Y.len());
  digit_t carry = 0;
  for (int i = 0; i < Y.len(); i++) {
    Z[i] = digit_add3(X[i], Y[i], carry, &carry);
  }
  return carry;
}
References v8::internal::carry, DCHECK, digit_add3(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::bigint::Digits::len(), and X().
Referenced by v8::bigint::anonymous_namespace{div-burnikel.cc}::BZ::D3n2n(), and InplaceAdd().
AddAndReturnOverflow()
digit_t v8::bigint::AddAndReturnOverflow (RWDigits Z, Digits X)
Definition at line 13 of file vector-arithmetic.cc.
                                                   {
  X.Normalize();
  if (X.len() == 0) return 0;
  digit_t carry = 0;
  int i = 0;
  for (; i < X.len(); i++) {
    Z[i] = digit_add3(Z[i], X[i], carry, &carry);
  }
  for (; i < Z.len() && carry != 0; i++) {
    Z[i] = digit_add2(Z[i], carry, &carry);
  }
  return carry;
}
References v8::internal::carry, digit_add2(), digit_add3(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::bigint::Digits::len(), and X().
Referenced by v8::bigint::ProcessorImpl::FromStringLarge(), v8::bigint::ProcessorImpl::KaratsubaMain(), and v8::bigint::ProcessorImpl::KaratsubaStart().
AddOne()
void v8::bigint::AddOne (RWDigits Z, Digits X)
Definition at line 121 of file vector-arithmetic.cc.
                                  {
  digit_t carry = 1;
  int i = 0;
  for (; carry > 0 && i < X.len(); i++) Z[i] = digit_add2(X[i], carry, &carry);
  if (carry > 0) Z[i++] = carry;
  for (; i < X.len(); i++) Z[i] = X[i];
  for (; i < Z.len(); i++) Z[i] = 0;
}
References v8::internal::carry, digit_add2(), v8::bigint::Digits::len(), and X().
Referenced by v8::internal::MutableBigInt::AbsoluteAddOne().
AddResultLength()
int v8::bigint::AddResultLength (int x_length, int y_length) [inline]
Definition at line 321 of file bigint.h.
                                                       {
  return std::max(x_length, y_length) + 1;
}
Referenced by AddSignedResultLength(), and SubtractSignedResultLength().
AddSigned()
bool v8::bigint::AddSigned (RWDigits Z, Digits X, bool x_negative, Digits Y, bool y_negative)
Definition at line 93 of file vector-arithmetic.cc.
                                {
  if (x_negative == y_negative) {
    Add(Z, X, Y);
    return x_negative;
  }
  if (GreaterThanOrEqual(X, Y)) {
    Subtract(Z, X, Y);
    return x_negative;
  }
  Subtract(Z, Y, X);
  return !x_negative;
}
References Add(), GreaterThanOrEqual(), Subtract(), and X().
Referenced by v8::internal::BigInt::Add().
AddSignedResultLength()
int v8::bigint::AddSignedResultLength (int x_length, int y_length, bool same_sign) [inline]
Definition at line 324 of file bigint.h.
                                                                             {
  return same_sign ? AddResultLength(x_length, y_length)
                   : std::max(x_length, y_length);
}
References AddResultLength().
Referenced by v8::internal::BigInt::Add().
AsIntN()
bool v8::bigint::AsIntN (RWDigits Z, Digits X, bool x_negative, int n)
Definition at line 290 of file bitwise.cc.
                                                          {
  DCHECK(X.len() > 0);
  DCHECK(n > 0);
  DCHECK(AsIntNResultLength(X, x_negative, n) > 0);
  int needed_digits = DIV_CEIL(n, kDigitBits);
  digit_t top_digit = X[needed_digits - 1];
  digit_t compare_digit = digit_t{1} << ((n - 1) % kDigitBits);
  // The canonical algorithm would be: convert negative numbers to two's
  // complement representation, truncate, convert back to sign+magnitude. To
  // avoid the conversions, we predict what the result would be:
  // When the (n-1)th bit is not set:
  // - truncate the absolute value
  // - preserve the sign.
  // When the (n-1)th bit is set:
  // - subtract the truncated absolute value from 2**n to simulate two's
  // complement representation
  // - flip the sign, unless it's the special case where the input is negative
  // and the result is the minimum n-bit integer. E.g. asIntN(3, -12) => -4.
  bool has_bit = (top_digit & compare_digit) == compare_digit;
  if (!has_bit) {
    TruncateToNBits(Z, X, n);
    return x_negative;
  }
  TruncateAndSubFromPowerOfTwo(Z, X, n);
  if (!x_negative) return true; // Result is negative.
  // Scan for the special case (see above): if all bits below the (n-1)th
  // digit are zero, the result is negative.
  if ((top_digit & (compare_digit - 1)) != 0) return false;
  for (int i = needed_digits - 2; i >= 0; i--) {
    if (X[i] != 0) return false;
  }
  return true;
}
References AsIntNResultLength(), DCHECK, DIV_CEIL, kDigitBits, v8::bigint::anonymous_namespace{bitwise.cc}::TruncateAndSubFromPowerOfTwo(), v8::bigint::anonymous_namespace{bitwise.cc}::TruncateToNBits(), and X().
Referenced by v8::internal::BigInt::AsIntN().
AsIntNResultLength()
int v8::bigint::AsIntNResultLength (Digits X, bool x_negative, int n)
Definition at line 273 of file bitwise.cc.
                                                         {
  int needed_digits = DIV_CEIL(n, kDigitBits);
  // Generally: decide based on number of digits, and bits in the top digit.
  if (X.len() < needed_digits) return -1;
  if (X.len() > needed_digits) return needed_digits;
  digit_t top_digit = X[needed_digits - 1];
  digit_t compare_digit = digit_t{1} << ((n - 1) % kDigitBits);
  if (top_digit < compare_digit) return -1;
  if (top_digit > compare_digit) return needed_digits;
  // Special case: if X == -2**(n-1), truncation is a no-op.
  if (!x_negative) return needed_digits;
  for (int i = needed_digits - 2; i >= 0; i--) {
    if (X[i] != 0) return needed_digits;
  }
  return -1;
}
References DIV_CEIL, kDigitBits, and X().
Referenced by v8::internal::BigInt::AsIntN(), and AsIntN().
AsUintN_Neg()
void v8::bigint::AsUintN_Neg (RWDigits Z, Digits X, int n)
Definition at line 341 of file bitwise.cc.
                                              {
  TruncateAndSubFromPowerOfTwo(Z, X, n);
}
References v8::bigint::anonymous_namespace{bitwise.cc}::TruncateAndSubFromPowerOfTwo(), and X().
Referenced by v8::internal::BigInt::AsUintN().
AsUintN_Neg_ResultLength()
int v8::bigint::AsUintN_Neg_ResultLength (int n) [inline]
Definition at line 364 of file bigint.h.
                                           {
  return ((n - 1) / kDigitBits) + 1;
}
References kDigitBits.
Referenced by v8::internal::BigInt::AsUintN().
AsUintN_Pos()
void v8::bigint::AsUintN_Pos (RWDigits Z, Digits X, int n)
Definition at line 336 of file bitwise.cc.
                                              {
  DCHECK(AsUintN_Pos_ResultLength(X, n) > 0);
  TruncateToNBits(Z, X, n);
}
References AsUintN_Pos_ResultLength(), DCHECK, v8::bigint::anonymous_namespace{bitwise.cc}::TruncateToNBits(), and X().
Referenced by v8::internal::BigInt::AsUintN().
AsUintN_Pos_ResultLength()
int v8::bigint::AsUintN_Pos_ResultLength (Digits X, int n)
Definition at line 325 of file bitwise.cc.
                                              {
  int needed_digits = DIV_CEIL(n, kDigitBits);
  if (X.len() < needed_digits) return -1;
  if (X.len() > needed_digits) return needed_digits;
  int bits_in_top_digit = n % kDigitBits;
  if (bits_in_top_digit == 0) return -1;
  digit_t top_digit = X[needed_digits - 1];
  if ((top_digit >> bits_in_top_digit) == 0) return -1;
  return needed_digits;
}
References DIV_CEIL, kDigitBits, and X().
Referenced by v8::internal::BigInt::AsUintN(), and AsUintN_Pos().
BitLength() [1/2]
int v8::bigint::BitLength (Digits X) [inline]
Definition at line 56 of file vector-arithmetic.h.
                               {
  return X.len() * kDigitBits - CountLeadingZeros(X.msd());
}
References CountLeadingZeros(), kDigitBits, and X().
BitLength() [2/2]
constexpr int v8::bigint::BitLength (int n) [inline], [constexpr]
Definition at line 65 of file util.h.
                                      {
  return 32 - CountLeadingZeros(static_cast<uint32_t>(n));
}
References CountLeadingZeros().
Referenced by v8::bigint::anonymous_namespace{mul-fft.cc}::ComputeParameters_Inner(), v8::bigint::ProcessorImpl::DivideBurnikelZiegler(), v8::bigint::ProcessorImpl::FromStringBasePowerOfTwo(), v8::bigint::anonymous_namespace{mul-fft.cc}::GetParameters(), v8::bigint::anonymous_namespace{mul-karatsuba.cc}::RoundUpLen(), and ToStringResultLength().
BitwiseAnd_NegNeg()
void v8::bigint::BitwiseAnd_NegNeg (RWDigits Z, Digits X, Digits Y)
Definition at line 21 of file bitwise.cc.
                                                       {
  // (-x) & (-y) == ~(x-1) & ~(y-1)
  // == ~((x-1) | (y-1))
  // == -(((x-1) | (y-1)) + 1)
  int pairs = std::min(X.len(), Y.len());
  digit_t x_borrow = 1;
  digit_t y_borrow = 1;
  int i = 0;
  for (; i < pairs; i++) {
    Z[i] = digit_sub(X[i], x_borrow, &x_borrow) |
           digit_sub(Y[i], y_borrow, &y_borrow);
  }
  // (At least) one of the next two loops will perform zero iterations:
  for (; i < X.len(); i++) Z[i] = digit_sub(X[i], x_borrow, &x_borrow);
  for (; i < Y.len(); i++) Z[i] = digit_sub(Y[i], y_borrow, &y_borrow);
  DCHECK(x_borrow == 0);
  DCHECK(y_borrow == 0);
  for (; i < Z.len(); i++) Z[i] = 0;
  Add(Z, 1);
}
References Add(), DCHECK, digit_sub(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::bigint::Digits::len(), and X().
Referenced by v8::internal::MutableBigInt_BitwiseAndNegNegAndCanonicalize().
BitwiseAnd_PosNeg()
void v8::bigint::BitwiseAnd_PosNeg (RWDigits Z, Digits X, Digits Y)
Definition at line 42 of file bitwise.cc.
                                                       {
  // x & (-y) == x & ~(y-1)
  int pairs = std::min(X.len(), Y.len());
  digit_t borrow = 1;
  int i = 0;
  for (; i < pairs; i++) Z[i] = X[i] & ~digit_sub(Y[i], borrow, &borrow);
  for (; i < X.len(); i++) Z[i] = X[i];
  for (; i < Z.len(); i++) Z[i] = 0;
}
References digit_sub(), v8::bigint::Digits::len(), and X().
Referenced by v8::internal::MutableBigInt_BitwiseAndPosNegAndCanonicalize().
BitwiseAnd_PosPos()
void v8::bigint::BitwiseAnd_PosPos (RWDigits Z, Digits X, Digits Y)
Definition at line 13 of file bitwise.cc.
                                                       {
  int pairs = std::min(X.len(), Y.len());
  DCHECK(Z.len() >= pairs);
  int i = 0;
  for (; i < pairs; i++) Z[i] = X[i] & Y[i];
  for (; i < Z.len(); i++) Z[i] = 0;
}
References DCHECK, v8::bigint::Digits::len(), and X().
Referenced by v8::internal::MutableBigInt_BitwiseAndPosPosAndCanonicalize().
BitwiseOr_NegNeg()
void v8::bigint::BitwiseOr_NegNeg (RWDigits Z, Digits X, Digits Y)
Definition at line 62 of file bitwise.cc.
                                                      {
  // (-x) | (-y) == ~(x-1) | ~(y-1)
  // == ~((x-1) & (y-1))
  // == -(((x-1) & (y-1)) + 1)
  int pairs = std::min(X.len(), Y.len());
  digit_t x_borrow = 1;
  digit_t y_borrow = 1;
  int i = 0;
  for (; i < pairs; i++) {
    Z[i] = digit_sub(X[i], x_borrow, &x_borrow) &
           digit_sub(Y[i], y_borrow, &y_borrow);
  }
  // Any leftover borrows don't matter, the '&' would drop them anyway.
  for (; i < Z.len(); i++) Z[i] = 0;
  Add(Z, 1);
}
References Add(), digit_sub(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::bigint::Digits::len(), and X().
Referenced by v8::internal::MutableBigInt_BitwiseOrNegNegAndCanonicalize().
BitwiseOr_PosNeg()
void v8::bigint::BitwiseOr_PosNeg (RWDigits Z, Digits X, Digits Y)
Definition at line 79 of file bitwise.cc.
                                                      {
  // x | (-y) == x | ~(y-1) == ~((y-1) &~ x) == -(((y-1) &~ x) + 1)
  int pairs = std::min(X.len(), Y.len());
  digit_t borrow = 1;
  int i = 0;
  for (; i < pairs; i++) Z[i] = digit_sub(Y[i], borrow, &borrow) & ~X[i];
  for (; i < Y.len(); i++) Z[i] = digit_sub(Y[i], borrow, &borrow);
  DCHECK(borrow == 0);
  for (; i < Z.len(); i++) Z[i] = 0;
  Add(Z, 1);
}
References Add(), DCHECK, digit_sub(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::bigint::Digits::len(), and X().
Referenced by v8::internal::MutableBigInt_BitwiseOrPosNegAndCanonicalize().
BitwiseOr_PosPos()
void v8::bigint::BitwiseOr_PosPos (RWDigits Z, Digits X, Digits Y)
Definition at line 52 of file bitwise.cc.
                                                      {
  int pairs = std::min(X.len(), Y.len());
  int i = 0;
  for (; i < pairs; i++) Z[i] = X[i] | Y[i];
  // (At least) one of the next two loops will perform zero iterations:
  for (; i < X.len(); i++) Z[i] = X[i];
  for (; i < Y.len(); i++) Z[i] = Y[i];
  for (; i < Z.len(); i++) Z[i] = 0;
}
References v8::bigint::Digits::len(), and X().
Referenced by v8::internal::MutableBigInt_BitwiseOrPosPosAndCanonicalize().
BitwiseXor_NegNeg()
void v8::bigint::BitwiseXor_NegNeg (RWDigits Z, Digits X, Digits Y)
Definition at line 104 of file bitwise.cc.
                                                       {
  // (-x) ^ (-y) == ~(x-1) ^ ~(y-1) == (x-1) ^ (y-1)
  int pairs = std::min(X.len(), Y.len());
  digit_t x_borrow = 1;
  digit_t y_borrow = 1;
  int i = 0;
  for (; i < pairs; i++) {
    Z[i] = digit_sub(X[i], x_borrow, &x_borrow) ^
           digit_sub(Y[i], y_borrow, &y_borrow);
  }
  // (At least) one of the next two loops will perform zero iterations:
  for (; i < X.len(); i++) Z[i] = digit_sub(X[i], x_borrow, &x_borrow);
  for (; i < Y.len(); i++) Z[i] = digit_sub(Y[i], y_borrow, &y_borrow);
  DCHECK(x_borrow == 0);
  DCHECK(y_borrow == 0);
  for (; i < Z.len(); i++) Z[i] = 0;
}
References DCHECK, digit_sub(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::bigint::Digits::len(), and X().
Referenced by v8::internal::MutableBigInt_BitwiseXorNegNegAndCanonicalize().
BitwiseXor_PosNeg()
void v8::bigint::BitwiseXor_PosNeg (RWDigits Z, Digits X, Digits Y)
Definition at line 122 of file bitwise.cc.
                                                       {
  // x ^ (-y) == x ^ ~(y-1) == ~(x ^ (y-1)) == -((x ^ (y-1)) + 1)
  int pairs = std::min(X.len(), Y.len());
  digit_t borrow = 1;
  int i = 0;
  for (; i < pairs; i++) Z[i] = X[i] ^ digit_sub(Y[i], borrow, &borrow);
  // (At least) one of the next two loops will perform zero iterations:
  for (; i < X.len(); i++) Z[i] = X[i];
  for (; i < Y.len(); i++) Z[i] = digit_sub(Y[i], borrow, &borrow);
  DCHECK(borrow == 0);
  for (; i < Z.len(); i++) Z[i] = 0;
  Add(Z, 1);
}
References Add(), DCHECK, digit_sub(), v8::bigint::Digits::len(), and X().
Referenced by v8::internal::MutableBigInt_BitwiseXorPosNegAndCanonicalize().
BitwiseXor_PosPos()
void v8::bigint::BitwiseXor_PosPos (RWDigits Z, Digits X, Digits Y)
Definition at line 91 of file bitwise.cc.
                                                       {
  int pairs = X.len();
  if (Y.len() < X.len()) {
    std::swap(X, Y);
    pairs = X.len();
  }
  DCHECK(X.len() <= Y.len());
  int i = 0;
  for (; i < pairs; i++) Z[i] = X[i] ^ Y[i];
  for (; i < Y.len(); i++) Z[i] = Y[i];
  for (; i < Z.len(); i++) Z[i] = 0;
}
References DCHECK, v8::bigint::Digits::len(), and X().
Referenced by v8::internal::MutableBigInt_BitwiseXorPosPosAndCanonicalize().
Compare()
int v8::bigint::Compare (Digits A, Digits B) [inline]
Definition at line 224 of file bigint.h.
                                       {
  A.Normalize();
  B.Normalize();
  int diff = A.len() - B.len();
  if (diff != 0) return diff;
  int i = A.len() - 1;
  while (i >= 0 && A[i] == B[i]) i--;
  if (i < 0) return 0;
  return A[i] > B[i] ? 1 : -1;
}
References v8::internal::A, v8::internal::B, and v8::internal::anonymous_namespace{json-stringifier.cc}::i.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::AspectIncludes(), v8::internal::BigInt::CompareToBigInt(), v8::bigint::anonymous_namespace{div-burnikel.cc}::BZ::D2n1n(), v8::bigint::anonymous_namespace{div-burnikel.cc}::BZ::D3n2n(), v8::internal::BigInt::Divide(), v8::bigint::ProcessorImpl::Divide(), v8::bigint::anonymous_namespace{div-burnikel.cc}::BZ::DivideBasecase(), v8::base::Bignum::Equal(), v8::bigint::ProcessorImpl::FromStringLarge(), GreaterThanOrEqual(), v8::base::Bignum::Less(), v8::base::Bignum::LessEqual(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::MaybeEmptyAspectIncludes(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::MaybeNullAspectIncludes(), v8::bigint::ProcessorImpl::Modulo(), v8::internal::MutableBigInt_AbsoluteCompare(), v8::internal::wasm::NameBuiltinLength(), and v8::internal::BigInt::Remainder().
CountLeadingZeros() [1/2]
template<typename T >
constexpr int v8::bigint::CountLeadingZeros (T value) [constexpr]
Definition at line 30 of file util.h.
{
#if __GNUC__ || __clang__
  return value == 0 ? 64 : __builtin_clzll(value);
#elif _MSC_VER
  unsigned long index = 0; // NOLINT(runtime/int). MSVC insists.
  return _BitScanReverse64(&index, value) ? 63 - index : 64;
#else
#error Unsupported compiler.
#endif
}
References v8::internal::index, and v8::internal::value.
Referenced by BitLength(), digit_div(), v8::bigint::ProcessorImpl::DivideBurnikelZiegler(), and v8::bigint::ShiftedDigits::ShiftedDigits().
CountLeadingZeros() [2/2]
constexpr int v8::bigint::CountLeadingZeros (uint32_t value) [constexpr]
Definition at line 43 of file util.h.
                                                {
#if __GNUC__ || __clang__
  return value == 0 ? 32 : __builtin_clz(value);
#elif _MSC_VER
  unsigned long index = 0; // NOLINT(runtime/int). MSVC insists.
  return _BitScanReverse(&index, value) ? 31 - index : 32;
#else
#error Unsupported compiler.
#endif
}
References v8::internal::index, and v8::internal::value.
CountTrailingZeros()
constexpr int v8::bigint::CountTrailingZeros (uint32_t value) [inline], [constexpr]
Definition at line 54 of file util.h.
                                                        {
#if __GNUC__ || __clang__
  return value == 0 ? 32 : __builtin_ctz(value);
#elif _MSC_VER
  unsigned long index = 0; // NOLINT(runtime/int).
  return _BitScanForward(&index, value) ? index : 32;
#else
#error Unsupported compiler.
#endif
}
References v8::internal::index, and v8::internal::value.
Referenced by v8::bigint::anonymous_namespace{tostring.cc}::ToStringFormatter::BasePowerOfTwo(), v8::bigint::anonymous_namespace{mul-fft.cc}::ComputeParameters(), v8::bigint::anonymous_namespace{mul-fft.cc}::ComputeParameters_Inner(), and ToStringResultLength().
digit_add2()
digit_t v8::bigint::digit_add2 (digit_t a, digit_t b, digit_t * carry) [inline]
Definition at line 23 of file digit-arithmetic.h.
                                                                {
#if HAVE_TWODIGIT_T
  twodigit_t result = twodigit_t{a} + b;
  *carry = result >> kDigitBits;
  return static_cast<digit_t>(result);
#else
  digit_t result = a + b;
  *carry = (result < a) ? 1 : 0;
  return result;
#endif
}
References v8::internal::carry, kDigitBits, and v8::base::internal::result.
Referenced by Add(), AddAndReturnOverflow(), AddOne(), v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::CounterWeightAndRecombine(), v8::bigint::ProcessorImpl::FromStringLarge(), v8::bigint::anonymous_namespace{mul-fft.cc}::ModFn_Helper(), v8::bigint::ProcessorImpl::MultiplySchoolbook(), v8::bigint::anonymous_namespace{mul-fft.cc}::ShiftModFn(), and v8::bigint::anonymous_namespace{mul-fft.cc}::ShiftModFn_Large().
digit_add3()
digit_t v8::bigint::digit_add3 (digit_t a, digit_t b, digit_t c, digit_t * carry) [inline]
Definition at line 37 of file digit-arithmetic.h.
                                                                           {
#if HAVE_TWODIGIT_T
  twodigit_t result = twodigit_t{a} + b + c;
  *carry = result >> kDigitBits;
  return static_cast<digit_t>(result);
#else
  digit_t result = a + b;
  *carry = (result < a) ? 1 : 0;
  result += c;
  if (result < c) *carry += 1;
  return result;
#endif
}
References v8::internal::carry, kDigitBits, and v8::base::internal::result.
Referenced by Add(), AddAndReturnCarry(), AddAndReturnOverflow(), v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::CounterWeightAndRecombine(), digit_mul(), v8::bigint::ProcessorImpl::MultiplySingle(), v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::NormalizeAndRecombine(), and v8::bigint::anonymous_namespace{mul-fft.cc}::SumDiff().
digit_div()
static digit_t v8::bigint::digit_div (digit_t high, digit_t low, digit_t divisor, digit_t * remainder) [inline], [static]
Definition at line 119 of file digit-arithmetic.h.
                                                    {
#if defined(DCHECK)
  DCHECK(high < divisor);
  DCHECK(divisor != 0);
#endif
#if __x86_64__ && (__GNUC__ || __clang__)
  digit_t quotient;
  digit_t rem;
  __asm__("divq %[divisor]"
          // Outputs: {quotient} will be in rax, {rem} in rdx.
          : "=a"(quotient), "=d"(rem)
          // Inputs: put {high} into rdx, {low} into rax, and {divisor} into
          // any register or stack slot.
          : "d"(high), "a"(low), [divisor] "rm"(divisor));
  *remainder = rem;
  return quotient;
#elif __i386__ && (__GNUC__ || __clang__)
  digit_t quotient;
  digit_t rem;
  __asm__("divl %[divisor]"
          // Outputs: {quotient} will be in eax, {rem} in edx.
          : "=a"(quotient), "=d"(rem)
          // Inputs: put {high} into edx, {low} into eax, and {divisor} into
          // any register or stack slot.
          : "d"(high), "a"(low), [divisor] "rm"(divisor));
  *remainder = rem;
  return quotient;
#else
  // Adapted from Warren, Hacker's Delight, p. 152.
  int s = CountLeadingZeros(divisor);
#if defined(DCHECK)
  DCHECK(s != kDigitBits); // {divisor} is not 0.
#endif
  divisor <<= s;
  digit_t vn1 = divisor >> kHalfDigitBits;
  digit_t vn0 = divisor & kHalfDigitMask;
  // {s} can be 0. {low >> kDigitBits} would be undefined behavior, so
  // we mask the shift amount with {kShiftMask}, and the result with
  // {s_zero_mask} which is 0 if s == 0 and all 1-bits otherwise.
  static_assert(sizeof(intptr_t) == sizeof(digit_t),
                "intptr_t and digit_t must have the same size");
  const int kShiftMask = kDigitBits - 1;
  digit_t s_zero_mask =
      static_cast<digit_t>(static_cast<intptr_t>(-s) >> (kDigitBits - 1));
  digit_t un32 =
      (high << s) | ((low >> ((kDigitBits - s) & kShiftMask)) & s_zero_mask);
  digit_t un10 = low << s;
  digit_t un1 = un10 >> kHalfDigitBits;
  digit_t un0 = un10 & kHalfDigitMask;
  digit_t q1 = un32 / vn1;
  digit_t rhat = un32 - q1 * vn1;
  while (q1 >= kHalfDigitBase || q1 * vn0 > rhat * kHalfDigitBase + un1) {
    q1--;
    rhat += vn1;
    if (rhat >= kHalfDigitBase) break;
  }
  digit_t un21 = un32 * kHalfDigitBase + un1 - q1 * divisor;
  digit_t q0 = un21 / vn1;
  rhat = un21 - q0 * vn1;
  while (q0 >= kHalfDigitBase || q0 * vn0 > rhat * kHalfDigitBase + un0) {
    q0--;
    rhat += vn1;
    if (rhat >= kHalfDigitBase) break;
  }
  *remainder = (un21 * kHalfDigitBase + un0 - q0 * divisor) >> s;
  return q1 * kHalfDigitBase + q0;
#endif
}
References CountLeadingZeros(), DCHECK, kDigitBits, kHalfDigitBase, kHalfDigitBits, and kHalfDigitMask.
Referenced by v8::bigint::ProcessorImpl::DivideSchoolbook(), and v8::bigint::ProcessorImpl::DivideSingle().
digit_ismax()
constexpr bool v8::bigint::digit_ismax (digit_t x) [constexpr]
Definition at line 20 of file digit-arithmetic.h.
{ return static_cast<digit_t>(~x) == 0; }
Referenced by RightShift_ResultLength().
digit_mul()
digit_t v8::bigint::digit_mul (digit_t a, digit_t b, digit_t * high) [inline]
Definition at line 82 of file digit-arithmetic.h.
                                                              {
#if HAVE_TWODIGIT_T
  twodigit_t result = twodigit_t{a} * b;
  *high = result >> kDigitBits;
  return static_cast<digit_t>(result);
#else
  // Multiply in half-pointer-sized chunks.
  // For inputs [AH AL]*[BH BL], the result is:
  //
  // [AL*BL] // r_low
  // + [AL*BH] // r_mid1
  // + [AH*BL] // r_mid2
  // + [AH*BH] // r_high
  // = [R4 R3 R2 R1] // high = [R4 R3], low = [R2 R1]
  //
  // Where of course we must be careful with carries between the columns.
  digit_t a_low = a & kHalfDigitMask;
  digit_t a_high = a >> kHalfDigitBits;
  digit_t b_low = b & kHalfDigitMask;
  digit_t b_high = b >> kHalfDigitBits;
  digit_t r_low = a_low * b_low;
  digit_t r_mid1 = a_low * b_high;
  digit_t r_mid2 = a_high * b_low;
  digit_t r_high = a_high * b_high;
  digit_t carry = 0;
  digit_t low = digit_add3(r_low, r_mid1 << kHalfDigitBits,
                           r_mid2 << kHalfDigitBits, &carry);
  *high =
      (r_mid1 >> kHalfDigitBits) + (r_mid2 >> kHalfDigitBits) + r_high + carry;
  return low;
#endif
}
References v8::internal::carry, digit_add3(), kDigitBits, kHalfDigitBits, kHalfDigitMask, and v8::base::internal::result.
Referenced by v8::bigint::ProcessorImpl::FromStringLarge(), v8::bigint::ProcessorImpl::MultiplySchoolbook(), v8::bigint::ProcessorImpl::MultiplySingle(), and ProductGreaterThan().
digit_sub()
digit_t v8::bigint::digit_sub (digit_t a, digit_t b, digit_t * borrow) [inline]
Definition at line 52 of file digit-arithmetic.h.
                                                                {
#if HAVE_TWODIGIT_T
  twodigit_t result = twodigit_t{a} - b;
  *borrow = (result >> kDigitBits) & 1;
  return static_cast<digit_t>(result);
#else
  digit_t result = a - b;
  *borrow = (result > a) ? 1 : 0;
  return result;
#endif
}
References kDigitBits, and v8::base::internal::result.
Referenced by BitwiseAnd_NegNeg(), BitwiseAnd_PosNeg(), BitwiseOr_NegNeg(), BitwiseOr_PosNeg(), BitwiseXor_NegNeg(), BitwiseXor_PosNeg(), v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::CounterWeightAndRecombine(), v8::bigint::anonymous_namespace{mul-karatsuba.cc}::KaratsubaSubtractionHelper(), v8::bigint::anonymous_namespace{mul-fft.cc}::ModFn_Helper(), v8::bigint::anonymous_namespace{mul-fft.cc}::ShiftModFn(), v8::bigint::anonymous_namespace{mul-fft.cc}::ShiftModFn_Large(), SubAndReturnBorrow(), Subtract(), SubtractOne(), and v8::bigint::anonymous_namespace{bitwise.cc}::TruncateAndSubFromPowerOfTwo().
digit_sub2()
digit_t v8::bigint::digit_sub2 (digit_t a, digit_t b, digit_t borrow_in, digit_t * borrow_out) [inline]
Definition at line 65 of file digit-arithmetic.h.
                                               {
#if HAVE_TWODIGIT_T
  twodigit_t subtrahend = twodigit_t{b} + borrow_in;
  twodigit_t result = twodigit_t{a} - subtrahend;
  *borrow_out = (result >> kDigitBits) & 1;
  return static_cast<digit_t>(result);
#else
  digit_t result = a - b;
  *borrow_out = (result > a) ? 1 : 0;
  if (result < borrow_in) *borrow_out += 1;
  result -= borrow_in;
  return result;
#endif
}
References kDigitBits, and v8::base::internal::result.
Referenced by v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::CounterWeightAndRecombine(), v8::bigint::anonymous_namespace{mul-karatsuba.cc}::KaratsubaSubtractionHelper(), v8::bigint::anonymous_namespace{mul-fft.cc}::ModFnDoubleWidth(), v8::bigint::anonymous_namespace{mul-fft.cc}::ShiftModFn(), v8::bigint::anonymous_namespace{mul-fft.cc}::ShiftModFn_Large(), SubAndReturnBorrow(), Subtract(), SubtractAndReturnBorrow(), v8::bigint::anonymous_namespace{mul-fft.cc}::SumDiff(), and v8::bigint::anonymous_namespace{bitwise.cc}::TruncateAndSubFromPowerOfTwo().
DivideBarrettScratchSpace()
constexpr int v8::bigint::DivideBarrettScratchSpace (int n) [constexpr]
Definition at line 104 of file bigint-internal.h.
{ return n + 2; }
DivideResultLength()
int v8::bigint::DivideResultLength (Digits A, Digits B) [inline]
Definition at line 338 of file bigint.h.
                                                  {
#if V8_ADVANCED_BIGINT_ALGORITHMS
  BIGINT_H_DCHECK(kAdvancedAlgorithmsEnabledInLibrary);
  // The Barrett division algorithm needs one extra digit for temporary use.
  int kBarrettExtraScratch = B.len() >= kBarrettThreshold ? 1 : 0;
#else
  // If this fails, set -DV8_ADVANCED_BIGINT_ALGORITHMS in any compilation unit
  // that #includes this header.
  BIGINT_H_DCHECK(!kAdvancedAlgorithmsEnabledInLibrary);
  constexpr int kBarrettExtraScratch = 0;
#endif
  return A.len() - B.len() + 1 + kBarrettExtraScratch;
}
References v8::internal::A, v8::internal::B, BIGINT_H_DCHECK, and kBarrettThreshold.
Referenced by v8::internal::BigInt::Divide(), v8::bigint::ProcessorImpl::Modulo(), and v8::internal::MutableBigInt_AbsoluteDivAndCanonicalize().
GreaterThanOrEqual()
bool v8::bigint::GreaterThanOrEqual (Digits A, Digits B) [inline]
Definition at line 52 of file vector-arithmetic.h.
                                                   {
  return Compare(A, B) >= 0;
}
References v8::internal::A, v8::internal::B, and Compare().
Referenced by AddSigned(), v8::bigint::anonymous_namespace{mul-karatsuba.cc}::KaratsubaSubtractionHelper(), and SubtractSigned().
InplaceAdd()
digit_t v8::bigint::InplaceAdd (RWDigits Z, Digits X) [inline]
Definition at line 58 of file div-schoolbook.cc.
                                                {
  return AddAndReturnCarry(Z, Z, X);
}
References AddAndReturnCarry(), and X().
Referenced by v8::bigint::ProcessorImpl::DivideSchoolbook().
InplaceSub()
digit_t v8::bigint::InplaceSub (RWDigits Z, Digits X) [inline]
Definition at line 63 of file div-schoolbook.cc.
                                                {
  return SubtractAndReturnBorrow(Z, Z, X);
}
References SubtractAndReturnBorrow(), and X().
Referenced by v8::bigint::ProcessorImpl::DivideSchoolbook().
InvertNewtonScratchSpace()
constexpr int v8::bigint::InvertNewtonScratchSpace (int n) [constexpr]
Definition at line 109 of file bigint-internal.h.
                                              {
  return 3 * n + 2 * kInvertNewtonExtraSpace;
}
References kInvertNewtonExtraSpace.
Referenced by InvertScratchSpace().
InvertScratchSpace()
constexpr int v8::bigint::InvertScratchSpace (int n) [constexpr]
Definition at line 112 of file bigint-internal.h.
                                        {
  return n < kNewtonInversionThreshold ? 2 * n : InvertNewtonScratchSpace(n);
}
References InvertNewtonScratchSpace(), and kNewtonInversionThreshold.
IsBitNormalized()
bool v8::bigint::IsBitNormalized (Digits X) [inline]
Definition at line 48 of file vector-arithmetic.h.
                                      {
  return (X.msd() >> (kDigitBits - 1)) == 1;
}
References kDigitBits, and X().
IsDigitNormalized()
bool v8::bigint::IsDigitNormalized (Digits X) [inline]
Definition at line 47 of file vector-arithmetic.h.
{ return X.len() == 0 || X.msd() != 0; }
References X().
Referenced by v8::bigint::ProcessorImpl::MultiplySchoolbook().
IsPowerOfTwo()
constexpr bool v8::bigint::IsPowerOfTwo (int value) [inline], [constexpr]
Definition at line 69 of file util.h.
                                              {
  return value > 0 && (value & (value - 1)) == 0;
}
References v8::internal::value.
Referenced by v8::bigint::ProcessorImpl::FromString(), v8::bigint::ProcessorImpl::ToStringImpl(), and ToStringResultLength().
LeftShift() [1/2]
void v8::bigint::LeftShift (RWDigits Z, Digits X, digit_t shift)
Definition at line 136 of file bitwise.cc.
                                                    {
  int digit_shift = static_cast<int>(shift / kDigitBits);
  int bits_shift = static_cast<int>(shift % kDigitBits);
  int i = 0;
  for (; i < digit_shift; ++i) Z[i] = 0;
  if (bits_shift == 0) {
    for (; i < X.len() + digit_shift; ++i) Z[i] = X[i - digit_shift];
    for (; i < Z.len(); ++i) Z[i] = 0;
  } else {
    digit_t carry = 0;
    for (; i < X.len() + digit_shift; ++i) {
      digit_t d = X[i - digit_shift];
      Z[i] = (d << bits_shift) | carry;
      carry = d >> (kDigitBits - bits_shift);
    }
    if (carry != 0) Z[i++] = carry;
    for (; i < Z.len(); ++i) Z[i] = 0;
  }
}
References v8::internal::carry, v8::internal::anonymous_namespace{json-stringifier.cc}::i, kDigitBits, v8::bigint::Digits::len(), and X().
Referenced by v8::bigint::ProcessorImpl::DivideBurnikelZiegler(), v8::bigint::ProcessorImpl::DivideSchoolbook(), v8::internal::MutableBigInt_LeftShiftAndCanonicalize(), and v8::bigint::ShiftedDigits::ShiftedDigits().
LeftShift() [2/2]
void v8::bigint::LeftShift (RWDigits Z, Digits X, int shift)
Definition at line 25 of file div-helpers.cc.
                                                {
  DCHECK(shift >= 0);
  DCHECK(shift < kDigitBits);
  DCHECK(Z.len() >= X.len());
  if (shift == 0) return Copy(Z, X);
  digit_t carry = 0;
  int i = 0;
  for (; i < X.len(); i++) {
    digit_t d = X[i];
    Z[i] = (d << shift) | carry;
    carry = d >> (kDigitBits - shift);
  }
  if (i < Z.len()) {
    Z[i++] = carry;
  } else {
    DCHECK(carry == 0);
  }
  for (; i < Z.len(); i++) Z[i] = 0;
}
References v8::internal::carry, v8::bigint::anonymous_namespace{div-helpers.cc}::Copy(), DCHECK, v8::internal::anonymous_namespace{json-stringifier.cc}::i, kDigitBits, v8::bigint::Digits::len(), and X().
ModuloResultLength()
int v8::bigint::ModuloResultLength (Digits B) [inline]
Definition at line 351 of file bigint.h.
{ return B.len(); }
References v8::internal::B.
Referenced by v8::internal::BigInt::Remainder().
MultiplyResultLength()
int v8::bigint::MultiplyResultLength (Digits X, Digits Y) [inline]
Definition at line 334 of file bigint.h.
                                                    {
  return X.len() + Y.len();
}
References v8::bigint::Digits::len(), and X().
Referenced by v8::internal::BigInt::Multiply().
ProductGreaterThan()
bool v8::bigint::ProductGreaterThan (digit_t factor1, digit_t factor2, digit_t high, digit_t low)
Definition at line 68 of file div-schoolbook.cc.
                                     {
  digit_t result_high;
  digit_t result_low = digit_mul(factor1, factor2, &result_high);
  return result_high > high || (result_high == high && result_low > low);
}
References digit_mul().
Referenced by v8::bigint::ProcessorImpl::DivideSchoolbook().
PutAt()
void v8::bigint::PutAt (RWDigits Z, Digits A, int count) [inline]
Definition at line 19 of file div-helpers.h.
                                                   {
  int len = std::min(A.len(), count);
  int i = 0;
  for (; i < len; i++) Z[i] = A[i];
  for (; i < count; i++) Z[i] = 0;
}
References v8::internal::A.
Referenced by v8::bigint::anonymous_namespace{div-burnikel.cc}::BZ::D3n2n(), v8::bigint::anonymous_namespace{div-burnikel.cc}::BZ::DivideBasecase(), and v8::bigint::ProcessorImpl::DivideBurnikelZiegler().
RightShift() [1/2]
void v8::bigint::RightShift (RWDigits Z, Digits X, digit_t shift, const RightShiftState & state)
Definition at line 195 of file bitwise.cc.
                                              {
  int digit_shift = static_cast<int>(shift / kDigitBits);
  int bits_shift = static_cast<int>(shift % kDigitBits);
  int i = 0;
  if (bits_shift == 0) {
    for (; i < X.len() - digit_shift; ++i) Z[i] = X[i + digit_shift];
  } else {
    digit_t carry = X[digit_shift] >> bits_shift;
    for (; i < X.len() - digit_shift - 1; ++i) {
      digit_t d = X[i + digit_shift + 1];
      Z[i] = (d << (kDigitBits - bits_shift)) | carry;
      carry = d >> bits_shift;
    }
    Z[i++] = carry;
  }
  for (; i < Z.len(); ++i) Z[i] = 0;
  if (state.must_round_down) {
    // Rounding down (a negative value) means adding one to
    // its absolute value. This cannot overflow.
    Add(Z, 1);
  }
}
References Add(), v8::internal::carry, v8::internal::anonymous_namespace{json-stringifier.cc}::i, kDigitBits, v8::bigint::Digits::len(), v8::bigint::RightShiftState::must_round_down, and X().
Referenced by v8::bigint::ProcessorImpl::DivideBurnikelZiegler(), v8::bigint::ProcessorImpl::DivideSchoolbook(), v8::internal::MutableBigInt_RightShiftAndCanonicalize(), and v8::bigint::ShiftedDigits::Reset().
RightShift() [2/2]
void v8::bigint::RightShift (RWDigits Z, Digits X, int shift)
Definition at line 47 of file div-helpers.cc.
                                                 {
  DCHECK(shift >= 0);
  DCHECK(shift < kDigitBits);
  X.Normalize();
  DCHECK(Z.len() >= X.len());
  if (shift == 0) return Copy(Z, X);
  int i = 0;
  if (X.len() > 0) {
    digit_t carry = X[0] >> shift;
    int last = X.len() - 1;
    for (; i < last; i++) {
      digit_t d = X[i + 1];
      Z[i] = (d << (kDigitBits - shift)) | carry;
      carry = d >> shift;
    }
    Z[i++] = carry;
  }
  for (; i < Z.len(); i++) Z[i] = 0;
}
References v8::internal::carry, v8::bigint::anonymous_namespace{div-helpers.cc}::Copy(), DCHECK, v8::internal::anonymous_namespace{json-stringifier.cc}::i, kDigitBits, v8::bigint::Digits::len(), and X().
RightShift_ResultLength()
int v8::bigint::RightShift_ResultLength (Digits X, bool x_sign, digit_t shift, RightShiftState * state)
Definition at line 157 of file bitwise.cc.
                                                    {
  int digit_shift = static_cast<int>(shift / kDigitBits);
  int bits_shift = static_cast<int>(shift % kDigitBits);
  int result_length = X.len() - digit_shift;
  if (result_length <= 0) return 0;
  // For negative numbers, round down if any bit was shifted out (so that e.g.
  // -5n >> 1n == -3n and not -2n). Check now whether this will happen and
  // whether it can cause overflow into a new digit.
  bool must_round_down = false;
  if (x_sign) {
    const digit_t mask = (static_cast<digit_t>(1) << bits_shift) - 1;
    if ((X[digit_shift] & mask) != 0) {
      must_round_down = true;
    } else {
      for (int i = 0; i < digit_shift; i++) {
        if (X[i] != 0) {
          must_round_down = true;
          break;
        }
      }
    }
  }
  // If bits_shift is non-zero, it frees up bits, preventing overflow.
  if (must_round_down && bits_shift == 0) {
    // Overflow cannot happen if the most significant digit has unset bits.
    const bool rounding_can_overflow = digit_ismax(X.msd());
    if (rounding_can_overflow) ++result_length;
  }
  if (state) {
    DCHECK(!must_round_down || x_sign);
    state->must_round_down = must_round_down;
  }
  return result_length;
}
References DCHECK, digit_ismax(), kDigitBits, v8::bigint::RightShiftState::must_round_down, and X().
Referenced by v8::internal::RightShiftResultLength().
RoundUp()
constexpr int v8::bigint::RoundUp (int x, int y) [inline], [constexpr]
Definition at line 25 of file util.h.
{ return (x + y - 1) & -y; }
References v8::base::internal::y.
Referenced by v8::bigint::anonymous_namespace{mul-fft.cc}::ComputeParameters(), v8::bigint::anonymous_namespace{mul-fft.cc}::ComputeParameters_Inner(), and v8::bigint::anonymous_namespace{mul-karatsuba.cc}::RoundUpLen().
SubAndReturnBorrow()
digit_t v8::bigint::SubAndReturnBorrow (RWDigits Z, Digits X)
Definition at line 27 of file vector-arithmetic.cc.
                                                 {
  X.Normalize();
  if (X.len() == 0) return 0;
  digit_t borrow = 0;
  int i = 0;
  for (; i < X.len(); i++) {
    Z[i] = digit_sub2(Z[i], X[i], borrow, &borrow);
  }
  for (; i < Z.len() && borrow != 0; i++) {
    Z[i] = digit_sub(Z[i], borrow, &borrow);
  }
  return borrow;
}
References digit_sub(), digit_sub2(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::bigint::Digits::len(), and X().
Referenced by v8::bigint::ProcessorImpl::KaratsubaMain().
Subtract() [1/2]
void v8::bigint::Subtract (RWDigits X, digit_t y) [inline]
Definition at line 33 of file vector-arithmetic.h.
                                            {
  digit_t borrow = y;
  int i = 0;
  do {
    X[i] = digit_sub(X[i], borrow, &borrow);
    i++;
  } while (borrow != 0);
}
References digit_sub(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, X(), and v8::base::internal::y.
Subtract() [2/2]
void v8::bigint::Subtract (RWDigits Z, Digits X, Digits Y)
Definition at line 59 of file vector-arithmetic.cc.
                                              {
  X.Normalize();
  Y.Normalize();
  DCHECK(X.len() >= Y.len());
  int i = 0;
  digit_t borrow = 0;
  for (; i < Y.len(); i++) {
    Z[i] = digit_sub2(X[i], Y[i], borrow, &borrow);
  }
  for (; i < X.len(); i++) {
    Z[i] = digit_sub(X[i], borrow, &borrow);
  }
  DCHECK(borrow == 0);
  for (; i < Z.len(); i++) Z[i] = 0;
}
References DCHECK, digit_sub(), digit_sub2(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::bigint::Digits::len(), v8::bigint::Digits::Normalize(), and X().
Referenced by AddSigned(), v8::bigint::anonymous_namespace{div-burnikel.cc}::BZ::D3n2n(), v8::internal::MutableBigInt_AbsoluteSubAndCanonicalize(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::JSTypedLowering::ReduceJSDecrement(), v8::internal::compiler::JSTypeHintLowering::ReduceUnaryOperation(), and SubtractSigned().
SubtractAndReturnBorrow()
digit_t v8::bigint::SubtractAndReturnBorrow (RWDigits Z, Digits X, Digits Y)
Definition at line 84 of file vector-arithmetic.cc.
                                                                {
  DCHECK(Z.len() >= Y.len() && X.len() >= Y.len());
  digit_t borrow = 0;
  for (int i = 0; i < Y.len(); i++) {
    Z[i] = digit_sub2(X[i], Y[i], borrow, &borrow);
  }
  return borrow;
}
References DCHECK, digit_sub2(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::bigint::Digits::len(), and X().
Referenced by v8::bigint::anonymous_namespace{div-burnikel.cc}::BZ::D3n2n(), and InplaceSub().
SubtractOne()
void v8::bigint::SubtractOne (RWDigits Z, Digits X)
Definition at line 130 of file vector-arithmetic.cc.
                                       {
  digit_t borrow = 1;
  int i = 0;
  for (; borrow > 0; i++) Z[i] = digit_sub(X[i], borrow, &borrow);
  for (; i < X.len(); i++) Z[i] = X[i];
  for (; i < Z.len(); i++) Z[i] = 0;
}
References digit_sub(), v8::bigint::Digits::len(), and X().
Referenced by v8::internal::MutableBigInt::AbsoluteSubOne().
SubtractResultLength()
int v8::bigint::SubtractResultLength (int x_length, int y_length) [inline]
Definition at line 328 of file bigint.h.
{ return x_length; }
SubtractSigned()
bool v8::bigint::SubtractSigned (RWDigits Z, Digits X, bool x_negative, Digits Y, bool y_negative)
Definition at line 107 of file vector-arithmetic.cc.
                                     {
  if (x_negative != y_negative) {
    Add(Z, X, Y);
    return x_negative;
  }
  if (GreaterThanOrEqual(X, Y)) {
    Subtract(Z, X, Y);
    return x_negative;
  }
  Subtract(Z, Y, X);
  return !x_negative;
}
References Add(), GreaterThanOrEqual(), Subtract(), and X().
Referenced by v8::internal::BigInt::Subtract().
SubtractSignedResultLength()
int v8::bigint::SubtractSignedResultLength (int x_length, int y_length, bool same_sign) [inline]
Definition at line 329 of file bigint.h.
                                                      {
  return same_sign ? std::max(x_length, y_length)
                   : AddResultLength(x_length, y_length);
}
References AddResultLength().
Referenced by v8::internal::BigInt::Subtract().
ToStringResultLength()
uint32_t v8::bigint::ToStringResultLength (Digits X, int radix, bool sign)
Definition at line 597 of file tostring.cc.
                                                              {
  const uint32_t bit_length = BitLength(X);
  uint32_t result;
  if (IsPowerOfTwo(radix)) {
    const uint32_t bits_per_char = CountTrailingZeros(radix);
    result = DIV_CEIL(bit_length, bits_per_char) + sign;
  } else {
    // Maximum number of bits we can represent with one character.
    const uint8_t max_bits_per_char = kMaxBitsPerChar[radix];
    // For estimating the result length, we have to be pessimistic and work with
    // the minimum number of bits one character can represent.
    const uint8_t min_bits_per_char = max_bits_per_char - 1;
    // Perform the following computation with uint64_t to avoid overflows.
    uint64_t chars_required = bit_length;
    chars_required *= kBitsPerCharTableMultiplier;
    chars_required = DIV_CEIL(chars_required, min_bits_per_char);
    DCHECK(chars_required <
           static_cast<uint64_t>(std::numeric_limits<uint32_t>::max()));
    result = static_cast<uint32_t>(chars_required);
  }
  result += sign;
  return result;
}
References BitLength(), CountTrailingZeros(), DCHECK, DIV_CEIL, IsPowerOfTwo(), v8::bigint::anonymous_namespace{tostring.cc}::kBitsPerCharTableMultiplier, v8::bigint::anonymous_namespace{tostring.cc}::kMaxBitsPerChar, v8::base::internal::result, v8::internal::sign, and X().
Referenced by v8::internal::StringToBigIntHelper< IsolateT >::DecimalString(), v8::internal::BigInt::NoSideEffectsToString(), v8::internal::BigInt::ToString(), and v8::bigint::anonymous_namespace{tostring.cc}::ToStringFormatter::ToStringFormatter().
Variable Documentation
kBarrettThreshold
constexpr int v8::bigint::kBarrettThreshold = 13310 [constexpr]
Definition at line 337 of file bigint.h.
Referenced by v8::bigint::ProcessorImpl::Divide(), DivideResultLength(), and v8::bigint::ProcessorImpl::Modulo().
kBurnikelThreshold
constexpr int v8::bigint::kBurnikelThreshold = 57 [constexpr]
Definition at line 20 of file bigint-internal.h.
Referenced by v8::bigint::anonymous_namespace{div-burnikel.cc}::BZ::D2n1n(), v8::bigint::ProcessorImpl::Divide(), v8::bigint::ProcessorImpl::DivideBurnikelZiegler(), and v8::bigint::ProcessorImpl::Modulo().
kCharBits
constexpr uint8_t v8::bigint::kCharBits[] = {1, 2, 3, 0, 4, 0, 0, 0, 5} [static], [constexpr]
Definition at line 476 of file bigint.h.
Referenced by v8::bigint::FromStringAccumulator::ParsePowerTwo().
kCharValue
constexpr uint8_t v8::bigint::kCharValue[] [static], [constexpr]
Initial value:
= {
    255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255,
    0, 1, 2, 3, 4, 5, 6, 7,
    8, 9, 255, 255, 255, 255, 255, 255,
    255, 10, 11, 12, 13, 14, 15, 16,
    17, 18, 19, 20, 21, 22, 23, 24,
    25, 26, 27, 28, 29, 30, 31, 32,
    33, 34, 35, 255, 255, 255, 255, 255,
    255, 10, 11, 12, 13, 14, 15, 16,
    17, 18, 19, 20, 21, 22, 23, 24,
    25, 26, 27, 28, 29, 30, 31, 32,
    33, 34, 35, 255, 255, 255, 255, 255,
}
Definition at line 456 of file bigint.h.
Referenced by v8::bigint::FromStringAccumulator::Parse(), and v8::bigint::FromStringAccumulator::ParsePowerTwo().
kDigitBits
constexpr int v8::bigint::kDigitBits = 1 << kLog2DigitBits [static], [constexpr]
Definition at line 51 of file bigint.h.
Referenced by v8::bigint::FromStringAccumulator::AddPart(), AsIntN(), AsIntNResultLength(), AsUintN_Neg_ResultLength(), AsUintN_Pos_ResultLength(), v8::bigint::anonymous_namespace{tostring.cc}::ToStringFormatter::BasePowerOfTwo(), BitLength(), v8::bigint::anonymous_namespace{mul-fft.cc}::ComputeParameters(), v8::bigint::anonymous_namespace{mul-fft.cc}::ComputeParameters_Inner(), digit_add2(), digit_add3(), digit_div(), digit_mul(), digit_sub(), digit_sub2(), v8::bigint::anonymous_namespace{mul-toom.cc}::DivideByTwo(), v8::bigint::ProcessorImpl::FromStringBasePowerOfTwo(), IsBitNormalized(), LeftShift(), v8::bigint::FromStringAccumulator::Parse(), v8::bigint::FromStringAccumulator::ParsePowerTwo(), RightShift(), RightShift_ResultLength(), v8::bigint::anonymous_namespace{mul-fft.cc}::ShiftModFn(), v8::bigint::anonymous_namespace{mul-fft.cc}::ShiftModFn_Large(), v8::bigint::anonymous_namespace{tostring.cc}::ToStringFormatter::Start(), v8::bigint::anonymous_namespace{mul-toom.cc}::TimesTwo(), v8::bigint::anonymous_namespace{bitwise.cc}::TruncateAndSubFromPowerOfTwo(), and v8::bigint::anonymous_namespace{bitwise.cc}::TruncateToNBits().
kFftInnerThreshold
constexpr int v8::bigint::kFftInnerThreshold = 200 [constexpr]
Definition at line 18 of file bigint-internal.h.
Referenced by v8::bigint::anonymous_namespace{mul-fft.cc}::ComputeParameters(), and v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::DoPointwiseMultiplication().
kFftThreshold
constexpr int v8::bigint::kFftThreshold = 1500 [constexpr]
Definition at line 17 of file bigint-internal.h.
Referenced by v8::bigint::ProcessorImpl::Multiply().
kFromStringLargeThreshold
constexpr int v8::bigint::kFromStringLargeThreshold = 300 [constexpr]
Definition at line 25 of file bigint-internal.h.
Referenced by v8::bigint::ProcessorImpl::FromString().
kHalfDigitBase
constexpr digit_t v8::bigint::kHalfDigitBase = digit_t{1} << kHalfDigitBits [static], [constexpr]
Definition at line 17 of file digit-arithmetic.h.
Referenced by digit_div().
kHalfDigitBits
constexpr int v8::bigint::kHalfDigitBits = kDigitBits / 2 [static], [constexpr]
Definition at line 16 of file digit-arithmetic.h.
Referenced by digit_div(), digit_mul(), v8::bigint::anonymous_namespace{tostring.cc}::DivideByMagic(), and v8::bigint::anonymous_namespace{mul-toom.cc}::DivideByThree().
kHalfDigitMask
constexpr digit_t v8::bigint::kHalfDigitMask = kHalfDigitBase - 1 [static], [constexpr]
Definition at line 18 of file digit-arithmetic.h.
Referenced by digit_div(), digit_mul(), v8::bigint::anonymous_namespace{tostring.cc}::DivideByMagic(), and v8::bigint::anonymous_namespace{mul-toom.cc}::DivideByThree().
kInvertNewtonExtraSpace
constexpr int v8::bigint::kInvertNewtonExtraSpace = 5 [constexpr]
Definition at line 108 of file bigint-internal.h.
Referenced by InvertNewtonScratchSpace().
kKaratsubaThreshold
constexpr int v8::bigint::kKaratsubaThreshold = 34 [constexpr]
Definition at line 15 of file bigint-internal.h.
Referenced by v8::bigint::ProcessorImpl::KaratsubaChunk(), v8::bigint::anonymous_namespace{mul-karatsuba.cc}::KaratsubaLength(), v8::bigint::ProcessorImpl::KaratsubaMain(), v8::bigint::ProcessorImpl::Multiply(), and v8::bigint::ProcessorImpl::MultiplyKaratsuba().
kNewtonInversionThreshold
constexpr int v8::bigint::kNewtonInversionThreshold = 50 [constexpr]
Definition at line 21 of file bigint-internal.h.
Referenced by InvertScratchSpace().
kStackParts
constexpr int v8::bigint::kStackParts = 8 [static], [constexpr]
Definition at line 382 of file bigint.h.
Referenced by v8::bigint::FromStringAccumulator::AddPart(), and v8::bigint::FromStringAccumulator::Parse().
kStringZapValue
constexpr char v8::bigint::kStringZapValue = '?' [constexpr]
Definition at line 355 of file bigint.h.
Referenced by v8::bigint::anonymous_namespace{tostring.cc}::BasecaseFixedLast(), v8::bigint::anonymous_namespace{tostring.cc}::ToStringFormatter::BasecaseLast(), v8::bigint::anonymous_namespace{tostring.cc}::ToStringFormatter::BasecaseMiddle(), v8::bigint::anonymous_namespace{tostring.cc}::DivideByMagic(), v8::internal::BigInt::ToString(), and v8::bigint::ProcessorImpl::ToStringImpl().
kToomThreshold
constexpr int v8::bigint::kToomThreshold = 193 [constexpr]
Definition at line 16 of file bigint-internal.h.
Referenced by v8::bigint::ProcessorImpl::Multiply().
kToStringFastThreshold
constexpr int v8::bigint::kToStringFastThreshold = 43 [constexpr]
Definition at line 24 of file bigint-internal.h.
Referenced by v8::bigint::ProcessorImpl::ToString().