v8::internal::anonymous_namespace{uri.cc} Namespace Reference
Functions
bool IsReservedPredicate (base::uc16 c)
bool IsReplacementCharacter (const uint8_t *octets, int length)
bool DecodeOctets (const uint8_t *octets, int length, std::vector< base::uc16 > *buffer)
int TwoDigitHex (base::uc16 character1, base::uc16 character2)
template<typename T >
void AddToBuffer (base::uc16 decoded, String::FlatContent *uri_content, int index, bool is_uri, std::vector< T > *buffer)
bool IntoTwoByte (int index, bool is_uri, int uri_length, String::FlatContent *uri_content, std::vector< base::uc16 > *buffer)
bool IntoOneAndTwoByte (DirectHandle< String > uri, bool is_uri, std::vector< uint8_t > *one_byte_buffer, std::vector< base::uc16 > *two_byte_buffer)
bool IsUnescapePredicateInUriComponent (base::uc16 c)
bool IsUriSeparator (base::uc16 c)
void AddEncodedOctetToBuffer (uint8_t octet, std::vector< uint8_t > *buffer)
void EncodeSingle (base::uc16 c, std::vector< uint8_t > *buffer)
void EncodePair (base::uc16 cc1, base::uc16 cc2, std::vector< uint8_t > *buffer)
template<typename Char >
int UnescapeChar (base::Vector< const Char > vector, int i, int length, int *step)
template<typename Char >
MaybeHandle< String > UnescapeSlow (Isolate *isolate, DirectHandle< String > string, int start_index)
bool IsNotEscaped (uint16_t c)
template<typename Char >
static MaybeHandle< String > UnescapePrivate (Isolate *isolate, Handle< String > source)
template<typename Char >
static MaybeHandle< String > EscapePrivate (Isolate *isolate, Handle< String > string)
Function Documentation
AddEncodedOctetToBuffer()
void v8::internal::anonymous_namespace{uri.cc}::AddEncodedOctetToBuffer (uint8_t octet, std::vector< uint8_t > * buffer)
Definition at line 252 of file uri.cc.
                                                                        {
  buffer->push_back('%');
  buffer->push_back(base::HexCharOfValue(octet >> 4));
  buffer->push_back(base::HexCharOfValue(octet & 0x0F));
}
References v8::base::HexCharOfValue().
Referenced by EncodePair(), and EncodeSingle().
AddToBuffer()
template<typename T >
void v8::internal::anonymous_namespace{uri.cc}::AddToBuffer (base::uc16 decoded, String::FlatContent * uri_content, int index, bool is_uri, std::vector< T > * buffer)
Definition at line 77 of file uri.cc.
                                                               {
  if (is_uri && IsReservedPredicate(decoded)) {
    buffer->push_back('%');
    base::uc16 first = uri_content->Get(index + 1);
    base::uc16 second = uri_content->Get(index + 2);
    DCHECK_GT(std::numeric_limits<T>::max(), first);
    DCHECK_GT(std::numeric_limits<T>::max(), second);
    buffer->push_back(first);
    buffer->push_back(second);
  } else {
    buffer->push_back(decoded);
  }
}
References DCHECK_GT, v8::internal::String::FlatContent::Get(), v8::internal::index, and IsReservedPredicate().
Referenced by IntoOneAndTwoByte(), and IntoTwoByte().
DecodeOctets()
bool v8::internal::anonymous_namespace{uri.cc}::DecodeOctets (const uint8_t * octets, int length, std::vector< base::uc16 > * buffer)
Definition at line 47 of file uri.cc.
                                               {
  size_t cursor = 0;
  base::uc32 value = unibrow::Utf8::ValueOf(octets, length, &cursor);
  if (value == unibrow::Utf8::kBadChar &&
      !IsReplacementCharacter(octets, length)) {
    return false;
  }
  if (value <=
      static_cast<base::uc32>(unibrow::Utf16::kMaxNonSurrogateCharCode)) {
    buffer->push_back(value);
  } else {
    buffer->push_back(unibrow::Utf16::LeadSurrogate(value));
    buffer->push_back(unibrow::Utf16::TrailSurrogate(value));
  }
  return true;
}
References IsReplacementCharacter(), unibrow::Utf8::kBadChar, unibrow::Utf16::kMaxNonSurrogateCharCode, unibrow::Utf16::LeadSurrogate(), v8::internal::length, unibrow::Utf16::TrailSurrogate(), v8::internal::value, and unibrow::Utf8::ValueOf().
Referenced by IntoTwoByte().
EncodePair()
void v8::internal::anonymous_namespace{uri.cc}::EncodePair (base::uc16 cc1, base::uc16 cc2, std::vector< uint8_t > * buffer)
Definition at line 268 of file uri.cc.
                                                                        {
  char s[4] = {};
  int number_of_bytes =
      unibrow::Utf8::Encode(s, unibrow::Utf16::CombineSurrogatePair(cc1, cc2),
                            unibrow::Utf16::kNoPreviousCharacter, false);
  for (int k = 0; k < number_of_bytes; k++) {
    AddEncodedOctetToBuffer(s[k], buffer);
  }
}
References AddEncodedOctetToBuffer(), unibrow::Utf16::CombineSurrogatePair(), unibrow::Utf8::Encode(), and unibrow::Utf16::kNoPreviousCharacter.
Referenced by v8::internal::Uri::Encode().
EncodeSingle()
void v8::internal::anonymous_namespace{uri.cc}::EncodeSingle (base::uc16 c, std::vector< uint8_t > * buffer)
Definition at line 258 of file uri.cc.
                                                          {
  char s[4] = {};
  int number_of_bytes;
  number_of_bytes =
      unibrow::Utf8::Encode(s, c, unibrow::Utf16::kNoPreviousCharacter, false);
  for (int k = 0; k < number_of_bytes; k++) {
    AddEncodedOctetToBuffer(s[k], buffer);
  }
}
References AddEncodedOctetToBuffer(), unibrow::Utf8::Encode(), and unibrow::Utf16::kNoPreviousCharacter.
Referenced by v8::internal::Uri::Encode().
EscapePrivate()
template<typename Char >
static MaybeHandle<String> v8::internal::anonymous_namespace{uri.cc}::EscapePrivate (Isolate * isolate, Handle< String > string) [static]
Definition at line 441 of file uri.cc.
                                                                {
  DCHECK(string->IsFlat());
  uint32_t escaped_length = 0;
  uint32_t length = string->length();
  {
    DisallowGarbageCollection no_gc;
    base::Vector<const Char> vector = string->GetCharVector<Char>(no_gc);
    for (uint32_t i = 0; i < length; i++) {
      uint16_t c = vector[i];
      if (c >= 256) {
        escaped_length += 6;
      } else if (IsNotEscaped(c)) {
        escaped_length++;
      } else {
        escaped_length += 3;
      }
      // We don't allow strings that are longer than a maximal length.
      DCHECK_LT(String::kMaxLength, 0x7FFFFFFF - 6); // Cannot overflow.
      if (escaped_length > String::kMaxLength) break; // Provoke exception.
    }
  }
  // No length change implies no change. Return original string if no change.
  if (escaped_length == length) return string;
  Handle<SeqOneByteString> dest;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, dest, isolate->factory()->NewRawOneByteString(escaped_length));
  int dest_position = 0;
  {
    DisallowGarbageCollection no_gc;
    base::Vector<const Char> vector = string->GetCharVector<Char>(no_gc);
    for (uint32_t i = 0; i < length; i++) {
      uint16_t c = vector[i];
      if (c >= 256) {
        dest->SeqOneByteStringSet(dest_position, '%');
        dest->SeqOneByteStringSet(dest_position + 1, 'u');
        dest->SeqOneByteStringSet(dest_position + 2,
                                  base::HexCharOfValue(c >> 12));
        dest->SeqOneByteStringSet(dest_position + 3,
                                  base::HexCharOfValue((c >> 8) & 0xF));
        dest->SeqOneByteStringSet(dest_position + 4,
                                  base::HexCharOfValue((c >> 4) & 0xF));
        dest->SeqOneByteStringSet(dest_position + 5,
                                  base::HexCharOfValue(c & 0xF));
        dest_position += 6;
      } else if (IsNotEscaped(c)) {
        dest->SeqOneByteStringSet(dest_position, c);
        dest_position++;
      } else {
        dest->SeqOneByteStringSet(dest_position, '%');
        dest->SeqOneByteStringSet(dest_position + 1,
                                  base::HexCharOfValue(c >> 4));
        dest->SeqOneByteStringSet(dest_position + 2,
                                  base::HexCharOfValue(c & 0xF));
        dest_position += 3;
      }
    }
  }
  return dest;
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::DCHECK(), DCHECK_LT, v8::internal::Isolate::factory(), v8::base::HexCharOfValue(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, IsNotEscaped(), v8::internal::String::kMaxLength, v8::internal::length, v8::internal::FactoryBase< Impl >::NewRawOneByteString(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::string.
IntoOneAndTwoByte()
bool v8::internal::anonymous_namespace{uri.cc}::IntoOneAndTwoByte (DirectHandle< String > uri, bool is_uri, std::vector< uint8_t > * one_byte_buffer, std::vector< base::uc16 > * two_byte_buffer)
Definition at line 139 of file uri.cc.
                                                             {
  DisallowGarbageCollection no_gc;
  String::FlatContent uri_content = uri->GetFlatContent(no_gc);
  int uri_length = uri->length();
  for (int k = 0; k < uri_length; k++) {
    base::uc16 code = uri_content.Get(k);
    if (code == '%') {
      int two_digits;
      if (k + 2 >= uri_length ||
          (two_digits = TwoDigitHex(uri_content.Get(k + 1),
                                    uri_content.Get(k + 2))) < 0) {
        return false;
      }
      base::uc16 decoded = static_cast<base::uc16>(two_digits);
      if (decoded > unibrow::Utf8::kMaxOneByteChar) {
        return IntoTwoByte(k, is_uri, uri_length, &uri_content,
                           two_byte_buffer);
      }
      AddToBuffer(decoded, &uri_content, k, is_uri, one_byte_buffer);
      k += 2;
    } else {
      if (code > unibrow::Utf8::kMaxOneByteChar) {
        return IntoTwoByte(k, is_uri, uri_length, &uri_content,
                           two_byte_buffer);
      }
      one_byte_buffer->push_back(code);
    }
  }
  return true;
}
References AddToBuffer(), code, v8::internal::String::FlatContent::Get(), IntoTwoByte(), unibrow::Utf8::kMaxOneByteChar, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and TwoDigitHex().
Referenced by v8::internal::Uri::Decode().
IntoTwoByte()
bool v8::internal::anonymous_namespace{uri.cc}::IntoTwoByte (int index, bool is_uri, int uri_length, String::FlatContent * uri_content, std::vector< base::uc16 > * buffer)
Definition at line 93 of file uri.cc.
                                              {
  for (int k = index; k < uri_length; k++) {
    base::uc16 code = uri_content->Get(k);
    if (code == '%') {
      int two_digits;
      if (k + 2 >= uri_length ||
          (two_digits = TwoDigitHex(uri_content->Get(k + 1),
                                    uri_content->Get(k + 2))) < 0) {
        return false;
      }
      k += 2;
      base::uc16 decoded = static_cast<base::uc16>(two_digits);
      if (decoded > unibrow::Utf8::kMaxOneByteChar) {
        uint8_t octets[unibrow::Utf8::kMaxEncodedSize];
        octets[0] = decoded;
        int number_of_continuation_bytes = 0;
        while ((decoded << ++number_of_continuation_bytes) & 0x80) {
          if (number_of_continuation_bytes > 3 || k + 3 >= uri_length) {
            return false;
          }
          if (uri_content->Get(++k) != '%' ||
              (two_digits = TwoDigitHex(uri_content->Get(k + 1),
                                        uri_content->Get(k + 2))) < 0) {
            return false;
          }
          k += 2;
          base::uc16 continuation_byte = static_cast<base::uc16>(two_digits);
          octets[number_of_continuation_bytes] = continuation_byte;
        }
        if (!DecodeOctets(octets, number_of_continuation_bytes, buffer)) {
          return false;
        }
      } else {
        AddToBuffer(decoded, uri_content, k - 2, is_uri, buffer);
      }
    } else {
      buffer->push_back(code);
    }
  }
  return true;
}
References AddToBuffer(), code, DecodeOctets(), v8::internal::String::FlatContent::Get(), v8::internal::index, unibrow::Utf8::kMaxEncodedSize, unibrow::Utf8::kMaxOneByteChar, and TwoDigitHex().
Referenced by IntoOneAndTwoByte().
IsNotEscaped()
bool v8::internal::anonymous_namespace{uri.cc}::IsNotEscaped (uint16_t c)
Definition at line 408 of file uri.cc.
                              {
  if (IsAlphaNumeric(c)) {
    return true;
  }
  // @*_+-./
  switch (c) {
    case '@':
    case '*':
    case '_':
    case '+':
    case '-':
    case '.':
    case '/':
      return true;
    default:
      return false;
  }
}
References v8::internal::IsAlphaNumeric().
Referenced by EscapePrivate().
IsReplacementCharacter()
bool v8::internal::anonymous_namespace{uri.cc}::IsReplacementCharacter (const uint8_t * octets, int length)
Definition at line 37 of file uri.cc.
                                                               {
  // The replacement character is at codepoint U+FFFD in the Unicode Specials
  // table. Its UTF-8 encoding is 0xEF 0xBF 0xBD.
  if (length != 3 || octets[0] != 0xEF || octets[1] != 0xBF ||
      octets[2] != 0xBD) {
    return false;
  }
  return true;
}
References v8::internal::length.
Referenced by DecodeOctets().
IsReservedPredicate()
bool v8::internal::anonymous_namespace{uri.cc}::IsReservedPredicate (base::uc16 c)
Definition at line 18 of file uri.cc.
                                     {
  switch (c) {
    case '#':
    case '$':
    case '&':
    case '+':
    case ',':
    case '/':
    case ':':
    case ';':
    case '=':
    case '?':
    case '@':
      return true;
    default:
      return false;
  }
}
Referenced by AddToBuffer().
IsUnescapePredicateInUriComponent()
bool v8::internal::anonymous_namespace{uri.cc}::IsUnescapePredicateInUriComponent (base::uc16 c)
Definition at line 212 of file uri.cc.
                                                   {
  if (IsAlphaNumeric(c)) {
    return true;
  }
  switch (c) {
    case '!':
    case '\'':
    case '(':
    case ')':
    case '*':
    case '-':
    case '.':
    case '_':
    case '~':
      return true;
    default:
      return false;
  }
}
References v8::internal::IsAlphaNumeric().
Referenced by v8::internal::Uri::Encode().
IsUriSeparator()
bool v8::internal::anonymous_namespace{uri.cc}::IsUriSeparator (base::uc16 c)
Definition at line 233 of file uri.cc.
                                {
  switch (c) {
    case '#':
    case ':':
    case ';':
    case '/':
    case '?':
    case '$':
    case '&':
    case '+':
    case ',':
    case '@':
    case '=':
      return true;
    default:
      return false;
  }
}
Referenced by v8::internal::Uri::Encode().
TwoDigitHex()
int v8::internal::anonymous_namespace{uri.cc}::TwoDigitHex (base::uc16 character1, base::uc16 character2)
Definition at line 66 of file uri.cc.
                                                          {
  if (character1 > 'f') return -1;
  int high = base::HexValue(character1);
  if (high == -1) return -1;
  if (character2 > 'f') return -1;
  int low = base::HexValue(character2);
  if (low == -1) return -1;
  return (high << 4) + low;
}
References v8::base::HexValue().
Referenced by IntoOneAndTwoByte(), IntoTwoByte(), and UnescapeChar().
UnescapeChar()
template<typename Char >
int v8::internal::anonymous_namespace{uri.cc}::UnescapeChar (base::Vector< const Char > vector, int i, int length, int * step)
Definition at line 331 of file uri.cc.
                            {
  uint16_t character = vector[i];
  int32_t hi = 0;
  int32_t lo = 0;
  if (character == '%' && i <= length - 6 && vector[i + 1] == 'u' &&
      (hi = TwoDigitHex(vector[i + 2], vector[i + 3])) > -1 &&
      (lo = TwoDigitHex(vector[i + 4], vector[i + 5])) > -1) {
    *step = 6;
    return (hi << 8) + lo;
  } else if (character == '%' && i <= length - 3 &&
             (lo = TwoDigitHex(vector[i + 1], vector[i + 2])) > -1) {
    *step = 3;
    return lo;
  } else {
    *step = 1;
    return character;
  }
}
References v8::internal::character, v8::internal::hi, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::length, v8::internal::lo, and TwoDigitHex().
Referenced by UnescapeSlow().
UnescapePrivate()
template<typename Char >
static MaybeHandle<String> v8::internal::anonymous_namespace{uri.cc}::UnescapePrivate (Isolate * isolate, Handle< String > source) [static]
Definition at line 428 of file uri.cc.
                                                                  {
  int index;
  {
    DisallowGarbageCollection no_gc;
    StringSearch<uint8_t, Char> search(isolate, base::StaticOneByteVector("%"));
    index = search.Search(source->GetCharVector<Char>(no_gc), 0);
    if (index < 0) return source;
  }
  return UnescapeSlow<Char>(isolate, source, index);
}
References v8::internal::index, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::anonymous_namespace{simd.cc}::search(), and v8::base::StaticOneByteVector().
UnescapeSlow()
template<typename Char >
MaybeHandle<String> v8::internal::anonymous_namespace{uri.cc}::UnescapeSlow (Isolate * isolate, DirectHandle< String > string, int start_index)
Definition at line 352 of file uri.cc.
                                                  {
  bool one_byte = true;
  uint32_t length = string->length();
  int unescaped_length = 0;
  {
    DisallowGarbageCollection no_gc;
    base::Vector<const Char> vector = string->GetCharVector<Char>(no_gc);
    for (uint32_t i = start_index; i < length; unescaped_length++) {
      int step;
      if (UnescapeChar(vector, i, length, &step) >
          String::kMaxOneByteCharCode) {
        one_byte = false;
      }
      i += step;
    }
  }
  DCHECK_LT(start_index, length);
  Handle<String> first_part =
      isolate->factory()->NewProperSubString(string, 0, start_index);
  int dest_position = 0;
  Handle<String> second_part;
  DCHECK_LE(unescaped_length, String::kMaxLength);
  if (one_byte) {
    Handle<SeqOneByteString> dest = isolate->factory()
                                        ->NewRawOneByteString(unescaped_length)
                                        .ToHandleChecked();
    DisallowGarbageCollection no_gc;
    base::Vector<const Char> vector = string->GetCharVector<Char>(no_gc);
    for (uint32_t i = start_index; i < length; dest_position++) {
      int step;
      dest->SeqOneByteStringSet(dest_position,
                                UnescapeChar(vector, i, length, &step));
      i += step;
    }
    second_part = dest;
  } else {
    Handle<SeqTwoByteString> dest = isolate->factory()
                                        ->NewRawTwoByteString(unescaped_length)
                                        .ToHandleChecked();
    DisallowGarbageCollection no_gc;
    base::Vector<const Char> vector = string->GetCharVector<Char>(no_gc);
    for (uint32_t i = start_index; i < length; dest_position++) {
      int step;
      dest->SeqTwoByteStringSet(dest_position,
                                UnescapeChar(vector, i, length, &step));
      i += step;
    }
    second_part = dest;
  }
  return isolate->factory()->NewConsString(first_part, second_part);
}
References DCHECK_LE, DCHECK_LT, v8::internal::Isolate::factory(), v8::internal::String::kMaxLength, v8::internal::String::kMaxOneByteCharCode, v8::internal::length, v8::internal::FactoryBase< Impl >::NewConsString(), v8::internal::Factory::NewProperSubString(), v8::internal::FactoryBase< Impl >::NewRawOneByteString(), v8::internal::FactoryBase< Impl >::NewRawTwoByteString(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and UnescapeChar().