v8::internal::anonymous_namespace{regexp-macro-assembler-tracer.cc} Namespace Reference
Classes
class PrintablePrinter
Functions
void PrintRangeArray (const ZoneList< CharacterRange > *ranges)
Function Documentation
PrintRangeArray()
void v8::internal::anonymous_namespace{regexp-macro-assembler-tracer.cc}::PrintRangeArray (const ZoneList< CharacterRange > * ranges)
Definition at line 322 of file regexp-macro-assembler-tracer.cc.
                                                             {
  for (int i = 0; i < ranges->length(); i++) {
    base::uc16 from = ranges->at(i).from();
    base::uc16 to = ranges->at(i).to();
    PrintablePrinter printable_from(from);
    PrintablePrinter printable_to(to);
    PrintF(" [from=0x%04x%s, to=%04x%s],\n", from, *printable_from, to,
           *printable_to);
  }
}
References v8::internal::ZoneList< T >::at(), v8::internal::ZoneList< T >::length(), and v8::internal::PrintF().
Referenced by v8::internal::RegExpMacroAssemblerTracer::CheckCharacterInRangeArray(), and v8::internal::RegExpMacroAssemblerTracer::CheckCharacterNotInRangeArray().