v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc} Namespace Reference
Classes
class FunctionContextSpecialization
struct GetResultLocationAndSizeHelper
struct GetResultLocationAndSizeHelper< index >
struct GetResultLocationAndSizeHelper< index, interpreter::OperandType::kRegOut, operands... >
struct GetResultLocationAndSizeHelper< index, interpreter::OperandType::kRegOutPair, operands... >
struct GetResultLocationAndSizeHelper< index, interpreter::OperandType::kRegOutTriple, operands... >
struct GetResultLocationAndSizeHelper< index, interpreter::OperandType::kRegOutList, operands... >
struct GetResultLocationAndSizeHelper< index, operand, operands... >
struct NodeForOperationHelper
struct Int32NodeForHelper
struct Float64NodeForHelper
class KnownMapsMerger
Typedefs
template<Operation kOperation>
using GenericNodeForOperation = typename NodeForOperationHelper< kOperation >::generic_type
template<Operation kOperation>
using Int32NodeFor = typename Int32NodeForHelper< kOperation >::type
template<Operation kOperation>
using Float64NodeFor = typename Float64NodeForHelper< kOperation >::type
Enumerations
enum class CpuOperation { kFloat64Round
, kMathClz32
 }
Functions
bool IsSupported (CpuOperation op)
template<interpreter::Bytecode bytecode, interpreter::ImplicitRegisterUse implicit_use, interpreter::OperandType... operands>
std::pair< interpreter::Register, int > GetResultLocationAndSizeForBytecode (const interpreter::BytecodeArrayIterator &iterator)
CheckType GetCheckType (NodeType type)
int32_t ClampToUint8 (int32_t value)
template<Operation kOperation>
constexpr bool BinaryOperationIsBitwiseInt32 ()
std::tuple< NodeType, TaggedToFloat64ConversionType > BinopHintToNodeTypeAndConversionType (BinaryOperationHint hint)
Runtime::FunctionId StaLookupSlotFunction (uint8_t sta_lookup_slot_flags)
AllocationBlock * GetAllocation (ValueNode *object)
bool IsEscaping (Graph *graph, InlinedAllocation *alloc)
bool VerifyIsNotEscaping (VirtualObjectList vos, InlinedAllocation *alloc)
bool AccessInfoGuaranteedConst (compiler::PropertyAccessInfo const &access_info)
MaybeReduceResult TryFindLoadedProperty (const KnownNodeAspects::LoadedPropertyMap &loaded_properties, ValueNode *lookup_start_object, KnownNodeAspects::LoadedPropertyMapKey name)
bool CheckConditionIn32 (int32_t lhs, int32_t rhs, AssertCondition condition)
bool CompareInt32 (int32_t lhs, int32_t rhs, Operation operation)
bool CompareUint32 (uint32_t lhs, uint32_t rhs, Operation operation)
void ForceEscapeIfAllocation (ValueNode *value)
bool CanInlineArrayIteratingBuiltin (compiler::JSHeapBroker *broker, const PossibleMaps &maps, ElementsKind *kind_return)
bool AllOfInstanceTypesUnsafe (const PossibleMaps &maps, std::function< bool(InstanceType)> f)
bool AllOfInstanceTypesAre (const PossibleMaps &maps, InstanceType type)
template<size_t MaxKindCount, typename KindsToIndexFunc >
bool CanInlineArrayResizingBuiltin (compiler::JSHeapBroker *broker, const PossibleMaps &possible_maps, std::array< SmallZoneVector< compiler::MapRef, 2 >, MaxKindCount > &map_kinds, KindsToIndexFunc &&elements_kind_to_index, int *unique_kind_count, bool is_loading)
bool IsSloppyMappedArgumentsObject (compiler::JSHeapBroker *broker, compiler::MapRef map)
compiler::OptionalMapRef GetArrayConstructorInitialMap (compiler::JSHeapBroker *broker, compiler::JSFunctionRef array_function, ElementsKind elements_kind, size_t argc, std::optional< int > maybe_length)
Typedef Documentation
Float64NodeFor
template<Operation kOperation>
using v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::Float64NodeFor = typedef typename Float64NodeForHelper<kOperation>::type
Definition at line 2272 of file maglev-graph-builder.cc.
GenericNodeForOperation
template<Operation kOperation>
using v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::GenericNodeForOperation = typedef typename NodeForOperationHelper<kOperation>::generic_type
Definition at line 2177 of file maglev-graph-builder.cc.
Int32NodeFor
template<Operation kOperation>
using v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::Int32NodeFor = typedef typename Int32NodeForHelper<kOperation>::type
Definition at line 2259 of file maglev-graph-builder.cc.
Enumeration Type Documentation
CpuOperation
enum v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::CpuOperation [strong]
Enumerator
kFloat64Round
kMathClz32
Definition at line 89 of file maglev-graph-builder.cc.
                        {
  kFloat64Round,
  kMathClz32,
};
Function Documentation
AccessInfoGuaranteedConst()
bool v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::AccessInfoGuaranteedConst (compiler::PropertyAccessInfo const & access_info)
Definition at line 5774 of file maglev-graph-builder.cc.
                                                   {
  if (!access_info.IsFastDataConstant() && !access_info.IsStringLength()) {
    return false;
  }
  // Even if we have a constant load, if the map is not stable, we cannot
  // guarantee that the load is preserved across side-effecting calls.
  // TODO(v8:7700): It might be possible to track it as const if we know
  // that we're still on the main transition tree; and if we add a
  // dependency on the stable end-maps of the entire tree.
  for (auto& map : access_info.lookup_start_object_maps()) {
    if (!map.is_stable()) {
      return false;
    }
  }
  return true;
}
References v8::internal::compiler::PropertyAccessInfo::IsFastDataConstant(), v8::internal::compiler::PropertyAccessInfo::IsStringLength(), and v8::internal::compiler::PropertyAccessInfo::lookup_start_object_maps().
Referenced by v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyLoad(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyStore().
AllOfInstanceTypesAre()
bool v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::AllOfInstanceTypesAre (const PossibleMaps & maps, InstanceType type)
Definition at line 9782 of file maglev-graph-builder.cc.
                                                                        {
  CHECK(!InstanceTypeChecker::IsString(type));
  return AllOfInstanceTypesUnsafe(
      maps, [type](InstanceType other) { return type == other; });
}
References AllOfInstanceTypesUnsafe(), CHECK, and v8::internal::tracing::type.
Referenced by v8::internal::maglev::MaglevGraphBuilder::TryReduceDatePrototypeGetField().
AllOfInstanceTypesUnsafe()
bool v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::AllOfInstanceTypesUnsafe (const PossibleMaps & maps, std::function< bool(InstanceType)> f)
Definition at line 9775 of file maglev-graph-builder.cc.
                                                                 {
  auto instance_type = [f](compiler::MapRef map) {
    return f(map.instance_type());
  };
  return std::all_of(maps.begin(), maps.end(), instance_type);
}
References v8::base::all_of(), v8::internal::ZoneCompactSet< T >::begin(), and v8::internal::ZoneCompactSet< T >::end().
Referenced by AllOfInstanceTypesAre().
BinaryOperationIsBitwiseInt32()
template<Operation kOperation>
constexpr bool v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::BinaryOperationIsBitwiseInt32 () [constexpr]
Definition at line 2183 of file maglev-graph-builder.cc.
                                               {
  switch (kOperation) {
    case Operation::kBitwiseNot:
    case Operation::kBitwiseAnd:
    case Operation::kBitwiseOr:
    case Operation::kBitwiseXor:
    case Operation::kShiftLeft:
    case Operation::kShiftRight:
    case Operation::kShiftRightLogical:
      return true;
    default:
      return false;
  }
}
References v8::kOperation.
BinopHintToNodeTypeAndConversionType()
std::tuple<NodeType, TaggedToFloat64ConversionType> v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::BinopHintToNodeTypeAndConversionType (BinaryOperationHint hint)
Definition at line 2637 of file maglev-graph-builder.cc.
                                                               {
  switch (hint) {
    case BinaryOperationHint::kSignedSmall:
      return std::make_tuple(NodeType::kSmi,
                             TaggedToFloat64ConversionType::kOnlyNumber);
    case BinaryOperationHint::kSignedSmallInputs:
    case BinaryOperationHint::kAdditiveSafeInteger:
    case BinaryOperationHint::kNumber:
      return std::make_tuple(NodeType::kNumber,
                             TaggedToFloat64ConversionType::kOnlyNumber);
    case BinaryOperationHint::kNumberOrOddball:
      return std::make_tuple(NodeType::kNumberOrOddball,
                             TaggedToFloat64ConversionType::kNumberOrOddball);
    case BinaryOperationHint::kNone:
    case BinaryOperationHint::kString:
    case BinaryOperationHint::kStringOrStringWrapper:
    case BinaryOperationHint::kBigInt:
    case BinaryOperationHint::kBigInt64:
    case BinaryOperationHint::kAny:
      UNREACHABLE();
  }
}
References v8::internal::kAdditiveSafeInteger, v8::internal::kAny, v8::internal::kBigInt, v8::internal::kBigInt64, v8::internal::kNone, v8::internal::kNumber, v8::internal::maglev::kNumberOrOddball, v8::internal::kNumberOrOddball, v8::internal::maglev::kOnlyNumber, v8::internal::kSignedSmall, v8::internal::kSignedSmallInputs, v8::internal::compiler::kSmi, v8::internal::kString, v8::internal::kStringOrStringWrapper, and v8::internal::UNREACHABLE().
Referenced by v8::internal::maglev::MaglevGraphBuilder::VisitBinaryOperation(), v8::internal::maglev::MaglevGraphBuilder::VisitBinarySmiOperation(), and v8::internal::maglev::MaglevGraphBuilder::VisitUnaryOperation().
CanInlineArrayIteratingBuiltin()
bool v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::CanInlineArrayIteratingBuiltin (compiler::JSHeapBroker * broker, const PossibleMaps & maps, ElementsKind * kind_return)
Definition at line 8654 of file maglev-graph-builder.cc.
                                                               {
  DCHECK_NE(0, maps.size());
  *kind_return = maps.at(0).elements_kind();
  for (compiler::MapRef map : maps) {
    if (!map.supports_fast_array_iteration(broker) ||
        !UnionElementsKindUptoSize(kind_return, map.elements_kind())) {
      return false;
    }
  }
  return true;
}
References v8::internal::ZoneCompactSet< T >::at(), broker(), DCHECK_NE, v8::internal::ZoneCompactSet< T >::size(), and v8::internal::UnionElementsKindUptoSize().
Referenced by v8::internal::maglev::MaglevGraphBuilder::TryReduceArrayIteratingBuiltin().
CanInlineArrayResizingBuiltin()
template<size_t MaxKindCount, typename KindsToIndexFunc >
bool v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::CanInlineArrayResizingBuiltin (compiler::JSHeapBroker * broker, const PossibleMaps & possible_maps, std::array< SmallZoneVector< compiler::MapRef, 2 >, MaxKindCount > & map_kinds, KindsToIndexFunc && elements_kind_to_index, int * unique_kind_count, bool is_loading)
Definition at line 9915 of file maglev-graph-builder.cc.
                     {
  uint8_t kind_bitmap = 0;
  for (compiler::MapRef map : possible_maps) {
    if (!map.supports_fast_array_resize(broker)) {
      return false;
    }
    ElementsKind kind = map.elements_kind();
    if (is_loading && kind == HOLEY_DOUBLE_ELEMENTS) {
      return false;
    }
    // Group maps by elements kind, using the provided function to translate
    // elements kinds to indices.
    // kind_bitmap is used to get the unique kinds (predecessor count for the
    // next block).
    uint8_t kind_index = elements_kind_to_index(kind);
    kind_bitmap |= 1 << kind_index;
    map_kinds[kind_index].push_back(map);
  }
  *unique_kind_count = base::bits::CountPopulation(kind_bitmap);
  DCHECK_GE(*unique_kind_count, 1);
  return true;
}
References broker(), v8::base::bits::CountPopulation(), DCHECK_GE, and v8::internal::HOLEY_DOUBLE_ELEMENTS.
CheckConditionIn32()
bool v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::CheckConditionIn32 (int32_t lhs, int32_t rhs, AssertCondition condition)
Definition at line 6203 of file maglev-graph-builder.cc.
                                                                             {
  switch (condition) {
    case AssertCondition::kEqual:
      return lhs == rhs;
    case AssertCondition::kNotEqual:
      return lhs != rhs;
    case AssertCondition::kLessThan:
      return lhs < rhs;
    case AssertCondition::kLessThanEqual:
      return lhs <= rhs;
    case AssertCondition::kGreaterThan:
      return lhs > rhs;
    case AssertCondition::kGreaterThanEqual:
      return lhs >= rhs;
    case AssertCondition::kUnsignedLessThan:
      return static_cast<uint32_t>(lhs) < static_cast<uint32_t>(rhs);
    case AssertCondition::kUnsignedLessThanEqual:
      return static_cast<uint32_t>(lhs) <= static_cast<uint32_t>(rhs);
    case AssertCondition::kUnsignedGreaterThan:
      return static_cast<uint32_t>(lhs) > static_cast<uint32_t>(rhs);
    case AssertCondition::kUnsignedGreaterThanEqual:
      return static_cast<uint32_t>(lhs) >= static_cast<uint32_t>(rhs);
  }
}
References v8::internal::kEqual, v8::internal::kGreaterThan, v8::internal::kGreaterThanEqual, v8::internal::kLessThan, v8::internal::kLessThanEqual, v8::internal::kNotEqual, v8::internal::kUnsignedGreaterThan, v8::internal::kUnsignedGreaterThanEqual, v8::internal::kUnsignedLessThan, and v8::internal::kUnsignedLessThanEqual.
Referenced by v8::internal::maglev::MaglevGraphBuilder::TryBuildCheckInt32Condition().
ClampToUint8()
int32_t v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::ClampToUint8 (int32_t value)
Definition at line 2120 of file maglev-graph-builder.cc.
                                    {
  if (value < 0) return 0;
  if (value > 255) return 255;
  return value;
}
References v8::internal::value.
Referenced by v8::internal::maglev::MaglevGraphBuilder::GetUint8ClampedForToNumber().
CompareInt32()
bool v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::CompareInt32 (int32_t lhs, int32_t rhs, Operation operation)
Definition at line 6228 of file maglev-graph-builder.cc.
                                                                 {
  switch (operation) {
    case Operation::kEqual:
    case Operation::kStrictEqual:
      return lhs == rhs;
    case Operation::kLessThan:
      return lhs < rhs;
    case Operation::kLessThanOrEqual:
      return lhs <= rhs;
    case Operation::kGreaterThan:
      return lhs > rhs;
    case Operation::kGreaterThanOrEqual:
      return lhs >= rhs;
    default:
      UNREACHABLE();
  }
}
References v8::internal::kEqual, v8::internal::kGreaterThan, v8::internal::kLessThan, and v8::internal::UNREACHABLE().
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfInt32Compare().
CompareUint32()
bool v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::CompareUint32 (uint32_t lhs, uint32_t rhs, Operation operation)
Definition at line 6246 of file maglev-graph-builder.cc.
                                                                    {
  switch (operation) {
    case Operation::kEqual:
    case Operation::kStrictEqual:
      return lhs == rhs;
    case Operation::kLessThan:
      return lhs < rhs;
    case Operation::kLessThanOrEqual:
      return lhs <= rhs;
    case Operation::kGreaterThan:
      return lhs > rhs;
    case Operation::kGreaterThanOrEqual:
      return lhs >= rhs;
    default:
      UNREACHABLE();
  }
}
References v8::internal::kEqual, v8::internal::kGreaterThan, v8::internal::kLessThan, and v8::internal::UNREACHABLE().
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfUint32Compare().
ForceEscapeIfAllocation()
void v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::ForceEscapeIfAllocation (ValueNode * value)
Definition at line 8317 of file maglev-graph-builder.cc.
                                               {
  if (InlinedAllocation* alloc = value->TryCast<InlinedAllocation>()) {
    alloc->ForceEscaping();
  }
}
References v8::internal::value.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildInlineFunction().
GetAllocation()
AllocationBlock* v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::GetAllocation (ValueNode * object)
Definition at line 5045 of file maglev-graph-builder.cc.
                                                  {
  if (object->Is<InlinedAllocation>()) {
    object = object->Cast<InlinedAllocation>()->input(0).node();
  }
  if (object->Is<AllocationBlock>()) {
    return object->Cast<AllocationBlock>();
  }
  return nullptr;
}
References v8::internal::maglev::NodeBase::Is().
Referenced by v8::internal::maglev::MaglevGraphBuilder::CanElideWriteBarrier().
GetArrayConstructorInitialMap()
compiler::OptionalMapRef v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::GetArrayConstructorInitialMap (compiler::JSHeapBroker * broker, compiler::JSFunctionRef array_function, ElementsKind elements_kind, size_t argc, std::optional< int > maybe_length)
Definition at line 12186 of file maglev-graph-builder.cc.
                                                                            {
  compiler::MapRef initial_map = array_function.initial_map(broker);
  if (argc == 1 && (!maybe_length.has_value() || *maybe_length > 0)) {
    // Constructing an Array via new Array(N) where N is an unsigned
    // integer, always creates a holey backing store.
    elements_kind = GetHoleyElementsKind(elements_kind);
  }
  return initial_map.AsElementsKind(broker, elements_kind);
}
References broker(), v8::internal::GetHoleyElementsKind(), v8::internal::compiler::initial_map, and v8::internal::compiler::JSFunctionRef::initial_map().
Referenced by v8::internal::maglev::MaglevGraphBuilder::TryReduceConstructArrayConstructor().
GetCheckType()
CheckType v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::GetCheckType (NodeType type)
Definition at line 1652 of file maglev-graph-builder.cc.
                                      {
  return NodeTypeIs(type, NodeType::kAnyHeapObject)
             ? CheckType::kOmitHeapObjectCheck
             : CheckType::kCheckHeapObject;
}
References v8::internal::maglev::kCheckHeapObject, v8::internal::maglev::kOmitHeapObjectCheck, v8::internal::maglev::NodeTypeIs(), and v8::internal::tracing::type.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfToBooleanTrue(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckJSFunction(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckJSReceiver(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckJSReceiverOrNullOrUndefined(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckMaps(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckSeqOneByteString(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckString(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckStringOrOddball(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckStringOrStringWrapper(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckSymbol(), v8::internal::maglev::MaglevGraphBuilder::BuildTestUndetectable(), v8::internal::maglev::MaglevGraphBuilder::BuildToBoolean(), v8::internal::maglev::MaglevGraphBuilder::GetInt32ElementIndex(), and v8::internal::maglev::MaglevGraphBuilder::GetInternalizedString().
GetResultLocationAndSizeForBytecode()
template<interpreter::Bytecode bytecode, interpreter::ImplicitRegisterUse implicit_use, interpreter::OperandType... operands>
std::pair<interpreter::Register, int> v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::GetResultLocationAndSizeForBytecode (const interpreter::BytecodeArrayIterator & iterator)
Definition at line 1266 of file maglev-graph-builder.cc.
                                                      {
  // We don't support output registers for implicit registers.
  DCHECK(!interpreter::BytecodeOperands::WritesImplicitRegister(implicit_use));
  if (interpreter::BytecodeOperands::WritesAccumulator(implicit_use)) {
    // If we write the accumulator, we shouldn't also write an output register.
    DCHECK(!(GetResultLocationAndSizeHelper<
             0, operands...>::HasOutputRegisterOperand()));
    return {interpreter::Register::virtual_accumulator(), 1};
  }
  // Use template magic to output a the appropriate GetRegisterOperand call and
  // size for this bytecode.
  return GetResultLocationAndSizeHelper<
      0, operands...>::GetResultLocationAndSize(iterator);
}
References v8::internal::DCHECK(), v8::internal::interpreter::Register::virtual_accumulator(), v8::internal::interpreter::BytecodeOperands::WritesAccumulator(), and v8::internal::interpreter::BytecodeOperands::WritesImplicitRegister().
IsEscaping()
bool v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::IsEscaping (Graph * graph, InlinedAllocation * alloc)
Definition at line 5113 of file maglev-graph-builder.cc.
                                                        {
  if (alloc->IsEscaping()) return true;
  auto it = graph->allocations_elide_map().find(alloc);
  if (it == graph->allocations_elide_map().end()) return false;
  for (InlinedAllocation* inner_alloc : it->second) {
    if (IsEscaping(graph, inner_alloc)) {
      return true;
    }
  }
  return false;
}
References graph(), and v8::internal::maglev::InlinedAllocation::IsEscaping().
Referenced by v8::internal::maglev::MaglevGraphBuilder::CanTrackObjectChanges().
IsSloppyMappedArgumentsObject()
bool v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::IsSloppyMappedArgumentsObject (compiler::JSHeapBroker * broker, compiler::MapRef map)
Definition at line 11660 of file maglev-graph-builder.cc.
                                                       {
  return broker->target_native_context()
      .fast_aliased_arguments_map(broker)
      .equals(map);
}
References broker().
Referenced by v8::internal::maglev::MaglevGraphBuilder::TryGetNonEscapingArgumentsObject().
IsSupported()
bool v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::IsSupported (CpuOperation op)
Definition at line 96 of file maglev-graph-builder.cc.
                                  {
  switch (op) {
    case CpuOperation::kFloat64Round:
#if defined(V8_TARGET_ARCH_X64) || defined(V8_TARGET_ARCH_IA32)
      return CpuFeatures::IsSupported(SSE4_1) || CpuFeatures::IsSupported(AVX);
#elif defined(V8_TARGET_ARCH_ARM)
      return CpuFeatures::IsSupported(ARMv8);
#elif defined(V8_TARGET_ARCH_ARM64) || defined(V8_TARGET_ARCH_PPC64) || \
    defined(V8_TARGET_ARCH_S390X) || defined(V8_TARGET_ARCH_RISCV64) || \
    defined(V8_TARGET_ARCH_RISCV32) || defined(V8_TARGET_ARCH_LOONG64) || \
    defined(V8_TARGET_ARCH_MIPS64)
      return true;
#else
#error "V8 does not support this architecture."
#endif
    case CpuOperation::kMathClz32:
#if defined(V8_TARGET_ARCH_ARM64) || defined(V8_TARGET_ARCH_S390X)
      return true;
#elif defined(V8_TARGET_ARCH_ARM)
      return CpuFeatures::IsSupported(ARMv8);
#elif defined(V8_TARGET_ARCH_X64)
      return CpuFeatures::IsSupported(LZCNT);
#elif defined(V8_TARGET_ARCH_RISCV64) || defined(V8_TARGET_ARCH_RISCV32)
      return CpuFeatures::IsSupported(ZBB);
#elif defined(V8_TARGET_ARCH_IA32) || defined(V8_TARGET_ARCH_PPC64) || \
    defined(V8_TARGET_ARCH_LOONG64) || defined(V8_TARGET_ARCH_MIPS64)
      return false;
#else
#error "V8 does not support this architecture."
#endif
  }
}
References v8::internal::CpuFeatures::IsSupported().
Referenced by v8::internal::maglev::MaglevGraphBuilder::DoTryReduceMathRound(), v8::internal::compiler::GraphAssembler::Float64RoundDown(), v8::internal::compiler::GraphAssembler::Float64RoundTruncate(), v8::internal::compiler::RepresentationChanger::GetFloat16RawBitsRepresentationFor(), v8::internal::compiler::RepresentationChanger::GetRepresentationFor(), v8::internal::compiler::RepresentationChanger::InsertChangeFloat16RawBitsToFloat64Fallback(), v8::internal::compiler::RepresentationChanger::InsertTruncateFloat64ToFloat16RawBitsFallback(), v8::internal::compiler::MachineOperatorReducer::Reduce(), v8::internal::compiler::CommonOperatorReducer::ReducePhi(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildElementAccessOnTypedArray().
StaLookupSlotFunction()
Runtime::FunctionId v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::StaLookupSlotFunction (uint8_t sta_lookup_slot_flags)
Definition at line 4482 of file maglev-graph-builder.cc.
                                                                       {
  using Flags = interpreter::StoreLookupSlotFlags;
  switch (Flags::GetLanguageMode(sta_lookup_slot_flags)) {
    case LanguageMode::kStrict:
      return Runtime::kStoreLookupSlot_Strict;
    case LanguageMode::kSloppy:
      if (Flags::IsLookupHoistingMode(sta_lookup_slot_flags)) {
        return Runtime::kStoreLookupSlot_SloppyHoisting;
      } else {
        return Runtime::kStoreLookupSlot_Sloppy;
      }
  }
}
References v8::internal::Flags(), v8::internal::kSloppy, and v8::internal::kStrict.
TryFindLoadedProperty()
MaybeReduceResult v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::TryFindLoadedProperty (const KnownNodeAspects::LoadedPropertyMap & loaded_properties, ValueNode * lookup_start_object, KnownNodeAspects::LoadedPropertyMapKey name)
Definition at line 6190 of file maglev-graph-builder.cc.
                                               {
  auto props_for_name = loaded_properties.find(name);
  if (props_for_name == loaded_properties.end()) return {};
  auto it = props_for_name->second.find(lookup_start_object);
  if (it == props_for_name->second.end()) return {};
  return it->second;
}
References v8::internal::name.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildLoadElements(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadStringLength(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadTypedArrayLength(), and v8::internal::maglev::MaglevGraphBuilder::TryReuseKnownPropertyLoad().
VerifyIsNotEscaping()
bool v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::VerifyIsNotEscaping (VirtualObjectList vos, InlinedAllocation * alloc)
Definition at line 5125 of file maglev-graph-builder.cc.
                                                                          {
  for (VirtualObject* vo : vos) {
    if (vo->allocation() == alloc) continue;
    bool escaped = false;
    vo->ForEachInput([&](ValueNode* nested_value) {
      if (escaped) return;
      if (!nested_value->Is<InlinedAllocation>()) return;
      ValueNode* nested_alloc = nested_value->Cast<InlinedAllocation>();
      if (nested_alloc == alloc) {
        if (vo->allocation()->IsEscaping() ||
            !VerifyIsNotEscaping(vos, vo->allocation())) {
          escaped = true;
        }
      }
    });
    if (escaped) return false;
  }
  return true;
}
References v8::internal::maglev::NodeBase::Cast(), v8::internal::if(), and v8::internal::maglev::NodeBase::Is().
Referenced by v8::internal::maglev::MaglevGraphBuilder::CanTrackObjectChanges().