v8::internal::maglev::anonymous_namespace{maglev-assembler-arm.cc} Namespace Reference
Functions
void SubSizeAndTagObject (MaglevAssembler *masm, Register object, Register size_in_bytes)
void SubSizeAndTagObject (MaglevAssembler *masm, Register object, int size_in_bytes)
template<typename T >
void AllocateRaw (MaglevAssembler *masm, Isolate *isolate, RegisterSnapshot register_snapshot, Register object, T size_in_bytes, AllocationType alloc_type, AllocationAlignment alignment)
Function Documentation
AllocateRaw()
template<typename T >
void v8::internal::maglev::anonymous_namespace{maglev-assembler-arm.cc}::AllocateRaw (MaglevAssembler * masm, Isolate * isolate, RegisterSnapshot register_snapshot, Register object, T size_in_bytes, AllocationType alloc_type, AllocationAlignment alignment)
Definition at line 29 of file maglev-assembler-arm.cc.
                                                {
  // TODO(victorgomes): Call the runtime for large object allocation.
  // TODO(victorgomes): Support double alignment.
  DCHECK(masm->allow_allocate());
  DCHECK_EQ(alignment, kTaggedAligned);
  if (v8_flags.single_generation) {
    alloc_type = AllocationType::kOld;
  }
  ExternalReference top = SpaceAllocationTopAddress(isolate, alloc_type);
  ExternalReference limit = SpaceAllocationLimitAddress(isolate, alloc_type);
  ZoneLabelRef done(masm);
  MaglevAssembler::TemporaryRegisterScope temps(masm);
  Register scratch = temps.AcquireScratch();
  // We are a bit short on registers, so we use the same register for {object}
  // and {new_top}. Once we have defined {new_top}, we don't use {object} until
  // {new_top} is used for the last time. And there (at the end of this
  // function), we recover the original {object} from {new_top} by subtracting
  // {size_in_bytes}.
  Register new_top = object;
  // Check if there is enough space.
  __ ldr(object, __ ExternalReferenceAsOperand(top, scratch));
  __ add(new_top, object, Operand(size_in_bytes), LeaveCC);
  __ ldr(scratch, __ ExternalReferenceAsOperand(limit, scratch));
  __ cmp(new_top, scratch);
  // Otherwise call runtime.
  __ JumpToDeferredIf(kUnsignedGreaterThanEqual, AllocateSlow<T>,
                      register_snapshot, object, AllocateBuiltin(alloc_type),
                      size_in_bytes, done);
  // Store new top and tag object.
  __ Move(__ ExternalReferenceAsOperand(top, scratch), new_top);
  SubSizeAndTagObject(masm, object, size_in_bytes);
  __ bind(*done);
}
References __, v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), v8::internal::maglev::AllocateBuiltin(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::kOld, v8::internal::kTaggedAligned, v8::internal::kUnsignedGreaterThanEqual, v8::internal::LeaveCC, v8::internal::maglev::SpaceAllocationLimitAddress(), v8::internal::maglev::SpaceAllocationTopAddress(), v8::internal::maglev::SubSizeAndTagObject(), and v8::internal::v8_flags.
Referenced by v8::internal::compiler::JSGraphAssembler::Allocate(), v8::internal::FactoryBase< Impl >::AllocateRawArray(), v8::internal::FactoryBase< Impl >::AllocateRawWithImmortalMap(), and v8::internal::compiler::RawMachineAssembler::OptimizedAllocate().
SubSizeAndTagObject() [1/2]
void v8::internal::maglev::anonymous_namespace{maglev-assembler-arm.cc}::SubSizeAndTagObject (MaglevAssembler * masm, Register object, int size_in_bytes)
Definition at line 23 of file maglev-assembler-arm.cc.
                                            {
  __ add(object, object, Operand(kHeapObjectTag - size_in_bytes), LeaveCC);
}
References __, v8::internal::kHeapObjectTag, and v8::internal::LeaveCC.
SubSizeAndTagObject() [2/2]
void v8::internal::maglev::anonymous_namespace{maglev-assembler-arm.cc}::SubSizeAndTagObject (MaglevAssembler * masm, Register object, Register size_in_bytes)
Definition at line 17 of file maglev-assembler-arm.cc.
                                                 {
  __ sub(object, object, size_in_bytes, LeaveCC);
  __ add(object, object, Operand(kHeapObjectTag), LeaveCC);
}
References __, v8::internal::kHeapObjectTag, and v8::internal::LeaveCC.