v8::internal::anonymous_namespace{builtins-console.cc} Namespace Reference
Enumerations
enum { CONSOLE_CONTEXT_ID_INDEX = Context::MIN_CONTEXT_SLOTS
, CONSOLE_CONTEXT_NAME_INDEX
, CONSOLE_CONTEXT_SLOTS
 }
Functions
bool Formatter (Isolate *isolate, BuiltinArguments &args, int index)
void ConsoleCall (Isolate *isolate, const internal::BuiltinArguments &args, void(debug::ConsoleDelegate::*func)(const v8::debug::ConsoleCallArguments &, const v8::debug::ConsoleContext &))
void LogTimerEvent (Isolate *isolate, BuiltinArguments args, v8::LogEventStatus se)
void InstallContextFunction (Isolate *isolate, DirectHandle< JSObject > target, const char *name, Builtin builtin, DirectHandle< Context > context)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
CONSOLE_CONTEXT_ID_INDEX
CONSOLE_CONTEXT_NAME_INDEX
CONSOLE_CONTEXT_SLOTS
Definition at line 146 of file builtins-console.cc.
     {
  CONSOLE_CONTEXT_ID_INDEX = Context::MIN_CONTEXT_SLOTS,
  CONSOLE_CONTEXT_NAME_INDEX,
  CONSOLE_CONTEXT_SLOTS,
};
Function Documentation
ConsoleCall()
void v8::internal::anonymous_namespace{builtins-console.cc}::ConsoleCall (Isolate * isolate, const internal::BuiltinArguments & args, void(debug::ConsoleDelegate::*)(const v8::debug::ConsoleCallArguments &, const v8::debug::ConsoleContext &) func)
Definition at line 152 of file builtins-console.cc.
                                                                        {
  if (isolate->is_execution_terminating()) return;
  CHECK(!isolate->has_exception());
  if (!isolate->console_delegate()) return;
  HandleScope scope(isolate);
  int context_id = 0;
  DirectHandle<String> context_name = isolate->factory()->anonymous_string();
  if (!IsNativeContext(args.target()->context())) {
    DirectHandle<Context> context(args.target()->context(), isolate);
    CHECK_EQ(CONSOLE_CONTEXT_SLOTS, context->length());
    context_id =
        Cast<Smi>(context->GetNoCell(CONSOLE_CONTEXT_ID_INDEX)).value();
    context_name = direct_handle(
        Cast<String>(context->GetNoCell(CONSOLE_CONTEXT_NAME_INDEX)), isolate);
  }
  (isolate->console_delegate()->*func)(
      debug::ConsoleCallArguments(isolate, args),
      v8::debug::ConsoleContext(context_id, Utils::ToLocal(context_name)));
}
References v8::base::args, CHECK, CHECK_EQ, CONSOLE_CONTEXT_ID_INDEX, CONSOLE_CONTEXT_NAME_INDEX, CONSOLE_CONTEXT_SLOTS, v8::internal::Isolate::console_delegate(), v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::Isolate::has_exception(), and v8::internal::Isolate::is_execution_terminating().
Referenced by v8::internal::BUILTIN().
Formatter()
bool v8::internal::anonymous_namespace{builtins-console.cc}::Formatter (Isolate * isolate, BuiltinArguments & args, int index)
Definition at line 64 of file builtins-console.cc.
                                                                    {
  if (args.length() < index + 2 || !IsString(args[index])) {
    return true;
  }
  struct State {
    IndirectHandle<String> str;
    int off;
  };
  std::stack<State> states;
  HandleScope scope(isolate);
  auto percent = isolate->factory()->percent_sign_string();
  states.push({args.at<String>(index++), 0});
  while (!states.empty() && index < args.length()) {
    State& state = states.top();
    state.off = String::IndexOf(isolate, state.str, percent, state.off);
    if (state.off < 0 ||
        state.off == static_cast<int>(state.str->length()) - 1) {
      states.pop();
      continue;
    }
    IndirectHandle<Object> current = args.at(index);
    uint16_t specifier = state.str->Get(state.off + 1, isolate);
    if (specifier == 'd' || specifier == 'f' || specifier == 'i') {
      if (IsSymbol(*current)) {
        current = isolate->factory()->nan_value();
      } else {
        DirectHandle<Object> params[] = {
            current, isolate->factory()->NewNumberFromInt(10)};
        auto builtin = specifier == 'f' ? isolate->global_parse_float_fun()
                                        : isolate->global_parse_int_fun();
        if (!Execution::CallBuiltin(isolate, builtin,
                                    isolate->factory()->undefined_value(),
                                    base::VectorOf(params))
                 .ToHandle(&current)) {
          return false;
        }
      }
    } else if (specifier == 's') {
      DirectHandle<Object> params[] = {current};
      if (!Execution::CallBuiltin(isolate, isolate->string_function(),
                                  isolate->factory()->undefined_value(),
                                  base::VectorOf(params))
               .ToHandle(&current)) {
        return false;
      }
      // Recurse into string results from type conversions, as they
      // can themselves contain formatting specifiers.
      states.push({Cast<String>(current), 0});
    } else if (specifier == 'c' || specifier == 'o' || specifier == 'O' ||
               specifier == '_') {
      // We leave the interpretation of %c (CSS), %o (optimally useful
      // formatting), and %O (generic JavaScript object formatting) as
      // well as the non-standard %_ (bypass formatter in Chrome) to
      // the debugger front-end, and preserve these specifiers as well
      // as their arguments verbatim.
      index++;
      state.off += 2;
      continue;
    } else if (specifier == '%') {
      // Chrome also supports %% as a way to generate a single % in the
      // output.
      state.off += 2;
      continue;
    } else {
      state.off++;
      continue;
    }
    // Replace the |specifier| (including the '%' character) in |target|
    // with the |current| value. We perform the replacement only morally
    // by updating the argument to the conversion result, but leave it to
    // the debugger front-end to perform the actual substitution.
    args.set_at(index++, *current);
    state.off += 2;
  }
  return true;
}
References v8::base::args, v8::internal::Execution::CallBuiltin(), v8::internal::Isolate::factory(), v8::internal::index, v8::internal::String::IndexOf(), v8::internal::FactoryBase< Impl >::NewNumberFromInt(), and v8::base::VectorOf().
InstallContextFunction()
void v8::internal::anonymous_namespace{builtins-console.cc}::InstallContextFunction (Isolate * isolate, DirectHandle< JSObject > target, const char * name, Builtin builtin, DirectHandle< Context > context)
Definition at line 241 of file builtins-console.cc.
                                                           {
  Factory* const factory = isolate->factory();
  DirectHandle<Map> map = isolate->sloppy_function_without_prototype_map();
  DirectHandle<String> name_string = factory->InternalizeUtf8String(name);
  DirectHandle<SharedFunctionInfo> info =
      factory->NewSharedFunctionInfoForBuiltin(name_string, builtin, 1,
                                               kDontAdapt);
  info->set_language_mode(LanguageMode::kSloppy);
  info->set_native(true);
  DirectHandle<JSFunction> fun =
      Factory::JSFunctionBuilder{isolate, info, context}.set_map(map).Build();
  JSObject::AddProperty(isolate, target, name_string, fun, NONE);
}
References v8::internal::JSObject::AddProperty(), v8::internal::Isolate::factory(), v8::internal::Factory::InternalizeUtf8String(), v8::internal::kDontAdapt, v8::internal::kSloppy, v8::internal::name, v8::internal::Factory::NewSharedFunctionInfoForBuiltin(), and v8::internal::NONE.
LogTimerEvent()
void v8::internal::anonymous_namespace{builtins-console.cc}::LogTimerEvent (Isolate * isolate, BuiltinArguments args, v8::LogEventStatus se)
Definition at line 175 of file builtins-console.cc.
                                        {
  if (!v8_flags.log_timer_events) return;
  HandleScope scope(isolate);
  std::unique_ptr<char[]> name;
  const char* raw_name = "default";
  if (args.length() > 1 && IsString(args[1])) {
    // Try converting the first argument to a string.
    name = args.at<String>(1)->ToCString();
    raw_name = name.get();
  }
  LOG(isolate, TimerEvent(se, raw_name));
}
References v8::base::args, LOG, v8::internal::name, and v8::internal::v8_flags.
Referenced by v8::internal::BUILTIN(), v8::internal::TimerEventScope< TimerEvent >::TimerEventScope(), and v8::internal::TimerEventScope< TimerEvent >::~TimerEventScope().