v8::internal::anonymous_namespace{gc-extension.cc} Namespace Reference
Classes
struct GCOptions
class AsyncGC
Enumerations
enum class GCType { kMinor
, kMajor
, kMajorWithSnapshot
 }
enum class ExecutionType { kAsync
, kSync
 }
enum class Flavor { kRegular
, kLastResort
 }
Functions
MaybeLocal< v8::String > ReadProperty (v8::Isolate *isolate, v8::Local< v8::Context > ctx, v8::Local< v8::Object > object, const char *key)
void ParseType (v8::Isolate *isolate, MaybeLocal< v8::String > maybe_type, GCOptions *options, bool *found_options_object)
void ParseExecution (v8::Isolate *isolate, MaybeLocal< v8::String > maybe_execution, GCOptions *options, bool *found_options_object)
void ParseFlavor (v8::Isolate *isolate, MaybeLocal< v8::String > maybe_execution, GCOptions *options, bool *found_options_object)
Maybe< GCOptions > Parse (v8::Isolate *isolate, const v8::FunctionCallbackInfo< v8::Value > &info)
void InvokeGC (v8::Isolate *isolate, const GCOptions gc_options)
Enumeration Type Documentation
ExecutionType
enum v8::internal::anonymous_namespace{gc-extension.cc}::ExecutionType [strong]
Enumerator
kAsync
kSync
Definition at line 27 of file gc-extension.cc.
{ kAsync, kSync };
Flavor
enum v8::internal::anonymous_namespace{gc-extension.cc}::Flavor [strong]
Enumerator
kRegular
kLastResort
Definition at line 28 of file gc-extension.cc.
{ kRegular, kLastResort };
GCType
enum v8::internal::anonymous_namespace{gc-extension.cc}::GCType [strong]
Enumerator
kMinor
kMajor
kMajorWithSnapshot
Definition at line 26 of file gc-extension.cc.
{ kMinor, kMajor, kMajorWithSnapshot };
Function Documentation
InvokeGC()
void v8::internal::anonymous_namespace{gc-extension.cc}::InvokeGC (v8::Isolate * isolate, const GCOptions gc_options)
Definition at line 186 of file gc-extension.cc.
                                                              {
  Heap* heap = reinterpret_cast<Isolate*>(isolate)->heap();
  EmbedderStackStateScope stack_scope(
      heap,
      gc_options.execution == ExecutionType::kAsync
          ? EmbedderStackStateOrigin::kImplicitThroughTask
          : EmbedderStackStateOrigin::kExplicitInvocation,
      gc_options.execution == ExecutionType::kAsync
          ? StackState::kNoHeapPointers
          : StackState::kMayContainHeapPointers);
  switch (gc_options.type) {
    case GCType::kMinor:
      heap->CollectGarbage(i::NEW_SPACE, i::GarbageCollectionReason::kTesting,
                           kGCCallbackFlagForced);
      break;
    case GCType::kMajor:
      switch (gc_options.flavor) {
        case Flavor::kRegular:
          heap->PreciseCollectAllGarbage(i::GCFlag::kNoFlags,
                                         i::GarbageCollectionReason::kTesting,
                                         kGCCallbackFlagForced);
          break;
        case Flavor::kLastResort:
          heap->CollectAllAvailableGarbage(
              i::GarbageCollectionReason::kTesting);
          break;
      }
      break;
    case GCType::kMajorWithSnapshot:
      heap->PreciseCollectAllGarbage(i::GCFlag::kNoFlags,
                                     i::GarbageCollectionReason::kTesting,
                                     kGCCallbackFlagForced);
      HeapProfiler* heap_profiler = heap->heap_profiler();
      // Since this API is intended for V8 devs, we do not treat globals as
      // roots here on purpose.
      v8::HeapProfiler::HeapSnapshotOptions options;
      options.numerics_mode =
          v8::HeapProfiler::NumericsMode::kExposeNumericValues;
      options.snapshot_mode =
          v8::HeapProfiler::HeapSnapshotMode::kExposeInternals;
      heap_profiler->TakeSnapshotToFile(options, gc_options.filename);
      break;
  }
}
References v8::internal::anonymous_namespace{gc-extension.cc}::GCOptions::execution, v8::internal::anonymous_namespace{gc-extension.cc}::GCOptions::filename, v8::internal::anonymous_namespace{gc-extension.cc}::GCOptions::flavor, heap(), v8::internal::kExplicitInvocation, v8::HeapProfiler::kExposeInternals, v8::HeapProfiler::kExposeNumericValues, v8::kGCCallbackFlagForced, v8::internal::kImplicitThroughTask, v8::internal::kNoFlags, v8_inspector::anonymous_namespace{v8-console.cc}::kRegular, v8::internal::NEW_SPACE, v8::HeapProfiler::HeapSnapshotOptions::numerics_mode, v8::HeapProfiler::HeapSnapshotOptions::snapshot_mode, v8::internal::HeapProfiler::TakeSnapshotToFile(), and v8::internal::anonymous_namespace{gc-extension.cc}::GCOptions::type.
Referenced by v8::internal::GCExtension::GC(), and v8::internal::anonymous_namespace{gc-extension.cc}::AsyncGC::RunInternal().
Parse()
Maybe<GCOptions> v8::internal::anonymous_namespace{gc-extension.cc}::Parse (v8::Isolate * isolate, const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 121 of file gc-extension.cc.
                                                                    {
  DCHECK(ValidateCallbackInfo(info));
  DCHECK_LT(0, info.Length());
  // Default values.
  auto options = GCOptions::GetDefault();
  // This will only ever transition to true if one property is found. It will
  // never toggle.
  bool found_options_object = false;
  if (info[0]->IsObject()) {
    v8::HandleScope scope(isolate);
    auto ctx = isolate->GetCurrentContext();
    auto param = v8::Local<v8::Object>::Cast(info[0]);
    v8::TryCatch catch_block(isolate);
    ParseType(isolate, ReadProperty(isolate, ctx, param, "type"), &options,
              &found_options_object);
    if (catch_block.HasCaught()) {
      catch_block.ReThrow();
      return Nothing<GCOptions>();
    }
    ParseExecution(isolate, ReadProperty(isolate, ctx, param, "execution"),
                   &options, &found_options_object);
    if (catch_block.HasCaught()) {
      catch_block.ReThrow();
      return Nothing<GCOptions>();
    }
    ParseFlavor(isolate, ReadProperty(isolate, ctx, param, "flavor"), &options,
                &found_options_object);
    if (catch_block.HasCaught()) {
      catch_block.ReThrow();
      return Nothing<GCOptions>();
    }
    if (options.type == GCType::kMajorWithSnapshot) {
      auto maybe_filename = ReadProperty(isolate, ctx, param, "filename");
      if (catch_block.HasCaught()) {
        catch_block.ReThrow();
        return Nothing<GCOptions>();
      }
      Local<v8::String> filename;
      if (maybe_filename.ToLocal(&filename)) {
        size_t buffer_size = filename->Utf8LengthV2(isolate) + 1;
        std::unique_ptr<char[]> buffer(new char[buffer_size]);
        filename->WriteUtf8V2(isolate, buffer.get(), buffer_size,
                              v8::String::WriteFlags::kNullTerminate);
        options.filename = std::string(buffer.get());
        // Not setting found_options_object as the option only makes sense with
        // properly set type anyways.
        CHECK(found_options_object);
      }
    }
  }
  // If the parameter is not an object or if it does not define any relevant
  // options, default to legacy behavior.
  if (!found_options_object) {
    return Just<GCOptions>(GCOptions::GetDefaultForTruthyWithoutOptionsBag());
  }
  return Just<GCOptions>(options);
}
References v8::Local< T >::Cast(), CHECK, v8::internal::DCHECK(), DCHECK_LT, v8::Isolate::GetCurrentContext(), v8::TryCatch::HasCaught(), v8::internal::IsObject(), v8::String::WriteFlags::kNullTerminate, v8::FunctionCallbackInfo< T >::Length(), ParseExecution(), ParseFlavor(), ParseType(), ReadProperty(), v8::TryCatch::ReThrow(), v8::internal::string, v8::String::Utf8LengthV2(), v8::internal::ValidateCallbackInfo(), and v8::String::WriteUtf8V2().
Referenced by v8::internal::GCExtension::GC(), and v8::internal::torque::ImplementationVisitor::GenerateCall().
ParseExecution()
void v8::internal::anonymous_namespace{gc-extension.cc}::ParseExecution (v8::Isolate * isolate, MaybeLocal< v8::String > maybe_execution, GCOptions * options, bool * found_options_object)
Definition at line 88 of file gc-extension.cc.
                                                {
  if (maybe_execution.IsEmpty()) return;
  auto type = maybe_execution.ToLocalChecked();
  if (type->StrictEquals(
          v8::String::NewFromUtf8(isolate, "async").ToLocalChecked())) {
    *found_options_object = true;
    options->execution = ExecutionType::kAsync;
  } else if (type->StrictEquals(
                 v8::String::NewFromUtf8(isolate, "sync").ToLocalChecked())) {
    *found_options_object = true;
    options->execution = ExecutionType::kSync;
  }
}
References v8::internal::anonymous_namespace{gc-extension.cc}::GCOptions::execution, v8::MaybeLocal< T >::IsEmpty(), v8::String::NewFromUtf8(), v8::MaybeLocal< T >::ToLocalChecked(), and v8::internal::tracing::type.
Referenced by Parse().
ParseFlavor()
void v8::internal::anonymous_namespace{gc-extension.cc}::ParseFlavor (v8::Isolate * isolate, MaybeLocal< v8::String > maybe_execution, GCOptions * options, bool * found_options_object)
Definition at line 105 of file gc-extension.cc.
                                                                 {
  if (maybe_execution.IsEmpty()) return;
  auto type = maybe_execution.ToLocalChecked();
  if (type->StrictEquals(
          v8::String::NewFromUtf8(isolate, "regular").ToLocalChecked())) {
    *found_options_object = true;
    options->flavor = Flavor::kRegular;
  } else if (type->StrictEquals(v8::String::NewFromUtf8(isolate, "last-resort")
                                    .ToLocalChecked())) {
    *found_options_object = true;
    options->flavor = Flavor::kLastResort;
  }
}
References v8::internal::anonymous_namespace{gc-extension.cc}::GCOptions::flavor, v8::MaybeLocal< T >::IsEmpty(), v8_inspector::anonymous_namespace{v8-console.cc}::kRegular, v8::String::NewFromUtf8(), v8::MaybeLocal< T >::ToLocalChecked(), and v8::internal::tracing::type.
Referenced by Parse().
ParseType()
void v8::internal::anonymous_namespace{gc-extension.cc}::ParseType (v8::Isolate * isolate, MaybeLocal< v8::String > maybe_type, GCOptions * options, bool * found_options_object)
Definition at line 67 of file gc-extension.cc.
                                                               {
  if (maybe_type.IsEmpty()) return;
  auto type = maybe_type.ToLocalChecked();
  if (type->StrictEquals(
          v8::String::NewFromUtf8(isolate, "minor").ToLocalChecked())) {
    *found_options_object = true;
    options->type = GCType::kMinor;
  } else if (type->StrictEquals(
                 v8::String::NewFromUtf8(isolate, "major").ToLocalChecked())) {
    *found_options_object = true;
    options->type = GCType::kMajor;
  } else if (type->StrictEquals(
                 v8::String::NewFromUtf8(isolate, "major-snapshot")
                     .ToLocalChecked())) {
    *found_options_object = true;
    options->type = GCType::kMajorWithSnapshot;
  }
}
References v8::MaybeLocal< T >::IsEmpty(), v8::String::NewFromUtf8(), v8::MaybeLocal< T >::ToLocalChecked(), v8::internal::anonymous_namespace{gc-extension.cc}::GCOptions::type, and v8::internal::tracing::type.
Referenced by Parse().
ReadProperty()
MaybeLocal<v8::String> v8::internal::anonymous_namespace{gc-extension.cc}::ReadProperty (v8::Isolate * isolate, v8::Local< v8::Context > ctx, v8::Local< v8::Object > object, const char * key)
Definition at line 54 of file gc-extension.cc.
                                                     {
  auto k = v8::String::NewFromUtf8(isolate, key).ToLocalChecked();
  auto maybe_property = object->Get(ctx, k);
  v8::Local<v8::Value> property;
  if (!maybe_property.ToLocal(&property) || !property->IsString()) {
    return {};
  }
  return MaybeLocal<v8::String>(property.As<v8::String>());
}
References v8::Local< T >::As(), v8::Value::IsString(), v8::internal::key, and v8::String::NewFromUtf8().
Referenced by Parse().