v8::internal::compiler::anonymous_namespace{code-generator-loong64.cc} Namespace Reference
Classes
class OutOfLineRecordWrite
Functions
CREATE_OOL_CLASS (OutOfLineFloat32Max, Float32MaxOutOfLine, FPURegister)
CREATE_OOL_CLASS (OutOfLineFloat32Min, Float32MinOutOfLine, FPURegister)
CREATE_OOL_CLASS (OutOfLineFloat64Max, Float64MaxOutOfLine, FPURegister)
CREATE_OOL_CLASS (OutOfLineFloat64Min, Float64MinOutOfLine, FPURegister)
void RecordTrapInfoIfNeeded (Zone *zone, CodeGenerator *codegen, InstructionCode opcode, Instruction *instr, int pc)
Condition FlagsConditionToConditionCmp (FlagsCondition condition)
Condition FlagsConditionToConditionTst (FlagsCondition condition)
Condition FlagsConditionToConditionOvf (FlagsCondition condition)
FPUCondition FlagsConditionToConditionCmpFPU (bool *predicate, FlagsCondition condition)
void AdjustStackPointerForTailCall (MacroAssembler *masm, FrameAccessState *state, int new_slot_above_sp, bool allow_shrinkage=true)
bool Is32BitOperand (InstructionOperand *operand)
bool Use32BitMove (InstructionOperand *source, InstructionOperand *destination)
Function Documentation
AdjustStackPointerForTailCall()
void v8::internal::compiler::anonymous_namespace{code-generator-loong64.cc}::AdjustStackPointerForTailCall (MacroAssembler * masm, FrameAccessState * state, int new_slot_above_sp, bool allow_shrinkage = true)
Definition at line 588 of file code-generator-loong64.cc.
                                                                {
  int current_sp_offset = state->GetSPToFPSlotCount() +
                          StandardFrameConstants::kFixedSlotCountAboveFp;
  int stack_slot_delta = new_slot_above_sp - current_sp_offset;
  if (stack_slot_delta > 0) {
    masm->Sub_d(sp, sp, stack_slot_delta * kSystemPointerSize);
    state->IncreaseSPDelta(stack_slot_delta);
  } else if (allow_shrinkage && stack_slot_delta < 0) {
    masm->Add_d(sp, sp, -stack_slot_delta * kSystemPointerSize);
    state->IncreaseSPDelta(stack_slot_delta);
  }
}
References v8::internal::compiler::FrameAccessState::GetSPToFPSlotCount(), v8::internal::compiler::FrameAccessState::IncreaseSPDelta(), v8::internal::CommonFrameConstants::kFixedSlotCountAboveFp, and v8::internal::kSystemPointerSize.
CREATE_OOL_CLASS() [1/4]
v8::internal::compiler::anonymous_namespace{code-generator-loong64.cc}::CREATE_OOL_CLASS (OutOfLineFloat32Max , Float32MaxOutOfLine , FPURegister)
CREATE_OOL_CLASS() [2/4]
v8::internal::compiler::anonymous_namespace{code-generator-loong64.cc}::CREATE_OOL_CLASS (OutOfLineFloat32Min , Float32MinOutOfLine , FPURegister)
CREATE_OOL_CLASS() [3/4]
v8::internal::compiler::anonymous_namespace{code-generator-loong64.cc}::CREATE_OOL_CLASS (OutOfLineFloat64Max , Float64MaxOutOfLine , FPURegister)
CREATE_OOL_CLASS() [4/4]
v8::internal::compiler::anonymous_namespace{code-generator-loong64.cc}::CREATE_OOL_CLASS (OutOfLineFloat64Min , Float64MinOutOfLine , FPURegister)
FlagsConditionToConditionCmp()
Condition v8::internal::compiler::anonymous_namespace{code-generator-loong64.cc}::FlagsConditionToConditionCmp (FlagsCondition condition)
Definition at line 294 of file code-generator-loong64.cc.
                                                                 {
  switch (condition) {
    case kEqual:
      return eq;
    case kNotEqual:
      return ne;
    case kSignedLessThan:
      return lt;
    case kSignedGreaterThanOrEqual:
      return ge;
    case kSignedLessThanOrEqual:
      return le;
    case kSignedGreaterThan:
      return gt;
    case kUnsignedLessThan:
      return lo;
    case kUnsignedGreaterThanOrEqual:
      return hs;
    case kUnsignedLessThanOrEqual:
      return ls;
    case kUnsignedGreaterThan:
      return hi;
    case kUnorderedEqual:
    case kUnorderedNotEqual:
      break;
    default:
      break;
  }
  UNREACHABLE();
}
References v8::internal::eq, v8::internal::ge, v8::internal::gt, v8::internal::hi, v8::internal::hs, v8::internal::compiler::kEqual, v8::internal::compiler::kNotEqual, v8::internal::compiler::kSignedGreaterThan, v8::internal::compiler::kSignedGreaterThanOrEqual, v8::internal::compiler::kSignedLessThan, v8::internal::compiler::kSignedLessThanOrEqual, v8::internal::compiler::kUnorderedEqual, v8::internal::compiler::kUnorderedNotEqual, v8::internal::compiler::kUnsignedGreaterThan, v8::internal::compiler::kUnsignedGreaterThanOrEqual, v8::internal::compiler::kUnsignedLessThan, v8::internal::compiler::kUnsignedLessThanOrEqual, v8::internal::le, v8::internal::lo, v8::internal::ls, v8::internal::lt, v8::internal::ne, and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::AssembleBranchToLabels().
FlagsConditionToConditionCmpFPU()
FPUCondition v8::internal::compiler::anonymous_namespace{code-generator-loong64.cc}::FlagsConditionToConditionCmpFPU (bool * predicate, FlagsCondition condition)
Definition at line 349 of file code-generator-loong64.cc.
                                                                       {
  switch (condition) {
    case kEqual:
      *predicate = true;
      return CEQ;
    case kNotEqual:
      *predicate = false;
      return CEQ;
    case kUnsignedLessThan:
    case kFloatLessThan:
      *predicate = true;
      return CLT;
    case kUnsignedGreaterThanOrEqual:
      *predicate = false;
      return CLT;
    case kUnsignedLessThanOrEqual:
    case kFloatLessThanOrEqual:
      *predicate = true;
      return CLE;
    case kUnsignedGreaterThan:
      *predicate = false;
      return CLE;
    case kFloatGreaterThan:
      *predicate = false;
      return CULE;
    case kFloatGreaterThanOrEqual:
      *predicate = false;
      return CULT;
    case kFloatLessThanOrUnordered:
      *predicate = true;
      return CULT;
    case kFloatGreaterThanOrUnordered:
      *predicate = false;
      return CLE;
    case kFloatGreaterThanOrEqualOrUnordered:
      *predicate = false;
      return CLT;
    case kFloatLessThanOrEqualOrUnordered:
      *predicate = true;
      return CULE;
    case kUnorderedEqual:
    case kUnorderedNotEqual:
      *predicate = true;
      break;
    default:
      *predicate = true;
      break;
  }
  UNREACHABLE();
}
References v8::internal::CEQ, v8::internal::CLE, v8::internal::CLT, v8::internal::CULE, v8::internal::CULT, v8::internal::compiler::kEqual, v8::internal::compiler::kFloatGreaterThan, v8::internal::compiler::kFloatGreaterThanOrEqual, v8::internal::compiler::kFloatGreaterThanOrEqualOrUnordered, v8::internal::compiler::kFloatGreaterThanOrUnordered, v8::internal::compiler::kFloatLessThan, v8::internal::compiler::kFloatLessThanOrEqual, v8::internal::compiler::kFloatLessThanOrEqualOrUnordered, v8::internal::compiler::kFloatLessThanOrUnordered, v8::internal::compiler::kNotEqual, v8::internal::compiler::kUnorderedEqual, v8::internal::compiler::kUnorderedNotEqual, v8::internal::compiler::kUnsignedGreaterThan, v8::internal::compiler::kUnsignedGreaterThanOrEqual, v8::internal::compiler::kUnsignedLessThan, v8::internal::compiler::kUnsignedLessThanOrEqual, and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::AssembleBranchToLabels().
FlagsConditionToConditionOvf()
Condition v8::internal::compiler::anonymous_namespace{code-generator-loong64.cc}::FlagsConditionToConditionOvf (FlagsCondition condition)
Definition at line 337 of file code-generator-loong64.cc.
                                                                 {
  switch (condition) {
    case kOverflow:
      return ne;
    case kNotOverflow:
      return eq;
    default:
      break;
  }
  UNREACHABLE();
}
References v8::internal::eq, v8::internal::compiler::kNotOverflow, v8::internal::compiler::kOverflow, v8::internal::ne, and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::AssembleBranchToLabels().
FlagsConditionToConditionTst()
Condition v8::internal::compiler::anonymous_namespace{code-generator-loong64.cc}::FlagsConditionToConditionTst (FlagsCondition condition)
Definition at line 325 of file code-generator-loong64.cc.
                                                                 {
  switch (condition) {
    case kNotEqual:
      return ne;
    case kEqual:
      return eq;
    default:
      break;
  }
  UNREACHABLE();
}
References v8::internal::eq, v8::internal::compiler::kEqual, v8::internal::compiler::kNotEqual, v8::internal::ne, and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::AssembleBranchToLabels().
Is32BitOperand()
bool v8::internal::compiler::anonymous_namespace{code-generator-loong64.cc}::Is32BitOperand (InstructionOperand * operand)
Definition at line 2990 of file code-generator-loong64.cc.
                                                 {
  DCHECK(operand->IsStackSlot() || operand->IsRegister());
  MachineRepresentation mr = LocationOperand::cast(operand)->representation();
  return mr == MachineRepresentation::kWord32 ||
         mr == MachineRepresentation::kCompressed ||
         mr == MachineRepresentation::kCompressedPointer;
}
References v8::internal::compiler::LocationOperand::cast(), v8::internal::DCHECK(), v8::internal::compiler::InstructionOperand::IsRegister(), v8::internal::compiler::InstructionOperand::IsStackSlot(), v8::internal::kCompressed, v8::internal::kCompressedPointer, v8::internal::kWord32, and v8::internal::compiler::LocationOperand::representation().
Referenced by Use32BitMove().
RecordTrapInfoIfNeeded()
void v8::internal::compiler::anonymous_namespace{code-generator-loong64.cc}::RecordTrapInfoIfNeeded (Zone * zone, CodeGenerator * codegen, InstructionCode opcode, Instruction * instr, int pc)
Definition at line 287 of file code-generator-loong64.cc.
                                    {
  DCHECK_EQ(kMemoryAccessDirect, AccessModeField::decode(opcode));
}
References DCHECK_EQ, v8::base::BitField< T, shift, size, U >::decode(), and v8::internal::compiler::kMemoryAccessDirect.
Use32BitMove()
bool v8::internal::compiler::anonymous_namespace{code-generator-loong64.cc}::Use32BitMove (InstructionOperand * source, InstructionOperand * destination)
Definition at line 3000 of file code-generator-loong64.cc.
                                                                               {
  return Is32BitOperand(source) && Is32BitOperand(destination);
}
References Is32BitOperand().