v8::internal::anonymous_namespace{builtins-api.cc} Namespace Reference
Classes
class RelocatableArguments
Functions
bool IsCompatibleReceiver (Isolate *isolate, Tagged< FunctionTemplateInfo > info, Tagged< JSReceiver > receiver)
template<bool is_construct>
V8_WARN_UNUSED_RESULT MaybeHandle< Object > HandleApiCallHelper (Isolate *isolate, DirectHandle< HeapObject > new_target, DirectHandle< FunctionTemplateInfo > fun_data, DirectHandle< Object > receiver, Address *argv, int argc)
Function Documentation
HandleApiCallHelper()
template<bool is_construct>
V8_WARN_UNUSED_RESULT MaybeHandle<Object> v8::internal::anonymous_namespace{builtins-api.cc}::HandleApiCallHelper (Isolate * isolate, DirectHandle< HeapObject > new_target, DirectHandle< FunctionTemplateInfo > fun_data, DirectHandle< Object > receiver, Address * argv, int argc)
Definition at line 57 of file builtins-api.cc.
                             {
  Handle<JSReceiver> js_receiver;
  if (is_construct) {
    DCHECK(IsTheHole(*receiver, isolate));
    if (IsUndefined(fun_data->GetInstanceTemplate(), isolate)) {
      v8::Local<ObjectTemplate> templ =
          ObjectTemplate::New(reinterpret_cast<v8::Isolate*>(isolate),
                              ToApiHandle<v8::FunctionTemplate>(fun_data));
      FunctionTemplateInfo::SetInstanceTemplate(
          isolate, fun_data, Utils::OpenDirectHandle(*templ));
    }
    DirectHandle<ObjectTemplateInfo> instance_template(
        Cast<ObjectTemplateInfo>(fun_data->GetInstanceTemplate()), isolate);
    ASSIGN_RETURN_ON_EXCEPTION(
        isolate, js_receiver,
        ApiNatives::InstantiateObject(isolate, instance_template,
                                      Cast<JSReceiver>(new_target)));
    argv[BuiltinArguments::kReceiverArgsIndex] = js_receiver->ptr();
  } else {
    DCHECK(IsJSReceiver(*receiver));
    js_receiver = indirect_handle(Cast<JSReceiver>(receiver), isolate);
    if (!fun_data->accept_any_receiver() && IsAccessCheckNeeded(*js_receiver)) {
      // Proxies never need access checks.
      DCHECK(IsJSObject(*js_receiver));
      DirectHandle<JSObject> js_object = Cast<JSObject>(js_receiver);
      if (!isolate->MayAccess(isolate->native_context(), js_object)) {
        RETURN_ON_EXCEPTION(isolate,
                            isolate->ReportFailedAccessCheck(js_object));
        UNREACHABLE();
      }
    }
    if (!IsCompatibleReceiver(isolate, *fun_data, *js_receiver)) {
      // This function cannot be called with the given receiver. Abort!
      THROW_NEW_ERROR(isolate,
                      NewTypeError(MessageTemplate::kIllegalInvocation));
    }
  }
  if (fun_data->has_callback(isolate)) {
    FunctionCallbackArguments custom(isolate, *fun_data, *new_target, argv,
                                     argc);
    DirectHandle<Object> result =
        custom.CallOrConstruct(*fun_data, is_construct);
    RETURN_EXCEPTION_IF_EXCEPTION(isolate);
    if (result.is_null()) {
      if (is_construct) return js_receiver;
      return isolate->factory()->undefined_value();
    }
    // Rebox the result.
    {
      DisallowGarbageCollection no_gc;
      Tagged<Object> raw_result = *result;
      DCHECK(Is<JSAny>(raw_result));
      if (!is_construct || IsJSReceiver(raw_result))
        return handle(raw_result, isolate);
    }
  }
  return js_receiver;
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::FunctionCallbackArguments::CallOrConstruct(), v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::internal::handle(), v8::internal::indirect_handle(), v8::internal::ApiNatives::InstantiateObject(), IsCompatibleReceiver(), v8::internal::BuiltinArguments::kReceiverArgsIndex, v8::internal::Isolate::MayAccess(), v8::internal::Isolate::native_context(), v8::ObjectTemplate::New(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::Utils::OpenDirectHandle(), v8::internal::Isolate::ReportFailedAccessCheck(), v8::base::internal::result, RETURN_EXCEPTION_IF_EXCEPTION, RETURN_ON_EXCEPTION, THROW_NEW_ERROR, and v8::internal::UNREACHABLE().
IsCompatibleReceiver()
bool v8::internal::anonymous_namespace{builtins-api.cc}::IsCompatibleReceiver (Isolate * isolate, Tagged< FunctionTemplateInfo > info, Tagged< JSReceiver > receiver)
Definition at line 26 of file builtins-api.cc.
                                                       {
  RCS_SCOPE(isolate, RuntimeCallCounterId::kGetCompatibleReceiver);
  Tagged<Object> recv_type = info->signature();
  // No signature, so function can be called with any receiver.
  if (!IsFunctionTemplateInfo(recv_type)) return true;
  // A Proxy cannot have been created from the signature template.
  if (!IsJSObject(receiver)) return false;
  Tagged<JSObject> js_obj_receiver = Cast<JSObject>(receiver);
  Tagged<FunctionTemplateInfo> signature =
      Cast<FunctionTemplateInfo>(recv_type);
  // Check the receiver.
  if (signature->IsTemplateFor(js_obj_receiver)) return true;
  // The JSGlobalProxy might have a hidden prototype.
  if (V8_UNLIKELY(IsJSGlobalProxy(js_obj_receiver))) {
    Tagged<HeapObject> prototype = js_obj_receiver->map()->prototype();
    if (!IsNull(prototype, isolate)) {
      Tagged<JSObject> js_obj_prototype = Cast<JSObject>(prototype);
      if (signature->IsTemplateFor(js_obj_prototype)) return true;
    }
  }
  return false;
}
References v8::internal::IsNull(), v8::internal::prototype, RCS_SCOPE, and V8_UNLIKELY.
Referenced by HandleApiCallHelper().