v8::internal::compiler::anonymous_namespace{js-call-reducer.cc} Namespace Reference
Classes
struct ForEachFrameStateParams
struct ReduceFrameStateParams
struct MapFrameStateParams
struct FilterFrameStateParams
struct FindFrameStateParams
struct EverySomeFrameStateParams
struct PromiseCtorFrameStateParams
class IteratingArrayBuiltinHelper
Functions
FrameState ForEachLoopLazyFrameState (const ForEachFrameStateParams &params, TNode< Object > k)
FrameState ForEachLoopEagerFrameState (const ForEachFrameStateParams &params, TNode< Object > k)
FrameState ReducePreLoopLazyFrameState (const ReduceFrameStateParams &params, TNode< Object > receiver, TNode< Object > callback, TNode< Object > k, TNode< Number > original_length)
FrameState ReducePreLoopEagerFrameState (const ReduceFrameStateParams &params, TNode< Object > receiver, TNode< Object > callback, TNode< Number > original_length)
FrameState ReduceLoopLazyFrameState (const ReduceFrameStateParams &params, TNode< Object > receiver, TNode< Object > callback, TNode< Object > k, TNode< Number > original_length)
FrameState ReduceLoopEagerFrameState (const ReduceFrameStateParams &params, TNode< Object > receiver, TNode< Object > callback, TNode< Object > k, TNode< Number > original_length, TNode< Object > accumulator)
FrameState MapPreLoopLazyFrameState (const MapFrameStateParams &params)
FrameState MapLoopLazyFrameState (const MapFrameStateParams &params, TNode< Number > k)
FrameState MapLoopEagerFrameState (const MapFrameStateParams &params, TNode< Number > k)
FrameState FilterLoopLazyFrameState (const FilterFrameStateParams &params, TNode< Number > k, TNode< Number > to, TNode< Object > element)
FrameState FilterLoopEagerPostCallbackFrameState (const FilterFrameStateParams &params, TNode< Number > k, TNode< Number > to, TNode< Object > element, TNode< Object > callback_value)
FrameState FilterLoopEagerFrameState (const FilterFrameStateParams &params, TNode< Number > k, TNode< Number > to)
FrameState FindLoopLazyFrameState (const FindFrameStateParams &params, TNode< Number > k, ArrayFindVariant variant)
FrameState FindLoopEagerFrameState (const FindFrameStateParams &params, TNode< Number > k, ArrayFindVariant variant)
FrameState FindLoopAfterCallbackLazyFrameState (const FindFrameStateParams &params, TNode< Number > next_k, TNode< Object > if_found_value, ArrayFindVariant variant)
FrameState EverySomeLoopLazyFrameState (const EverySomeFrameStateParams &params, TNode< Number > k, ArrayEverySomeVariant variant)
FrameState EverySomeLoopEagerFrameState (const EverySomeFrameStateParams &params, TNode< Number > k, ArrayEverySomeVariant variant)
Callable GetCallableForArrayIndexOfIncludes (ArrayIndexOfIncludesVariant variant, ElementsKind elements_kind, Isolate *isolate)
FrameState CreateConstructInvokeStubFrameState (Node *node, Node *outer_frame_state, SharedFunctionInfoRef shared, Node *context, CommonOperatorBuilder *common, TFGraph *graph)
FrameState PromiseConstructorFrameState (const PromiseCtorFrameStateParams &params, CommonOperatorBuilder *common, TFGraph *graph)
FrameState PromiseConstructorLazyFrameState (const PromiseCtorFrameStateParams &params, FrameState constructor_frame_state)
FrameState PromiseConstructorLazyWithCatchFrameState (const PromiseCtorFrameStateParams &params, FrameState constructor_frame_state, TNode< JSPromise > promise, TNode< JSFunction > reject)
bool CanInlineArrayIteratingBuiltin (JSHeapBroker *broker, ZoneRefSet< Map > const &receiver_maps, ElementsKind *kind_return)
bool CanInlineArrayResizingBuiltin (JSHeapBroker *broker, ZoneRefSet< Map > const &receiver_maps, std::vector< ElementsKind > *kinds, bool builtin_is_push=false)
bool IsSafeArgumentsElements (Node *node)
bool IsCallOrConstructWithSpread (Node *node)
bool IsCallWithArrayLikeOrSpread (Node *node)
bool ShouldUseCallICFeedback (Node *node)
bool TargetIsClassConstructor (Node *node, JSHeapBroker *broker)
FrameState CreateStringCreateLazyDeoptContinuationFrameState (JSGraph *graph, SharedFunctionInfoRef shared, Node *target, Node *context, Node *outer_frame_state)
InstanceType InstanceTypeForCollectionKind (CollectionKind kind)
Function Documentation
CanInlineArrayIteratingBuiltin()
bool v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::CanInlineArrayIteratingBuiltin (JSHeapBroker * broker, ZoneRefSet< Map > const & receiver_maps, ElementsKind * kind_return)
Definition at line 3647 of file js-call-reducer.cc.
                                                               {
  DCHECK_NE(0, receiver_maps.size());
  *kind_return = receiver_maps[0].elements_kind();
  for (MapRef map : receiver_maps) {
    if (!map.supports_fast_array_iteration(broker) ||
        !UnionElementsKindUptoSize(kind_return, map.elements_kind())) {
      return false;
    }
  }
  return true;
}
References broker(), DCHECK_NE, v8::internal::ZoneCompactSet< T >::size(), and v8::internal::UnionElementsKindUptoSize().
Referenced by v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::IteratingArrayBuiltinHelper::IteratingArrayBuiltinHelper(), and v8::internal::compiler::JSCallReducer::ReduceArrayIteratorPrototypeNext().
CanInlineArrayResizingBuiltin()
bool v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::CanInlineArrayResizingBuiltin (JSHeapBroker * broker, ZoneRefSet< Map > const & receiver_maps, std::vector< ElementsKind > * kinds, bool builtin_is_push = false)
Definition at line 3661 of file js-call-reducer.cc.
                                                                 {
  DCHECK_NE(0, receiver_maps.size());
  for (MapRef map : receiver_maps) {
    if (!map.supports_fast_array_resize(broker)) return false;
    // TODO(turbofan): We should also handle fast holey double elements once
    // we got the hole NaN mess sorted out in TurboFan/V8.
    if (map.elements_kind() == HOLEY_DOUBLE_ELEMENTS && !builtin_is_push) {
      return false;
    }
    ElementsKind current_kind = map.elements_kind();
    auto kind_ptr = kinds->data();
    size_t i;
    for (i = 0; i < kinds->size(); i++, kind_ptr++) {
      if (UnionElementsKindUptoPackedness(kind_ptr, current_kind)) {
        break;
      }
    }
    if (i == kinds->size()) kinds->push_back(current_kind);
  }
  return true;
}
References broker(), DCHECK_NE, v8::internal::HOLEY_DOUBLE_ELEMENTS, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::ZoneCompactSet< T >::size(), and v8::internal::UnionElementsKindUptoPackedness().
Referenced by v8::internal::compiler::JSCallReducer::ReduceArrayPrototypePop(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypePush(), and v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeShift().
CreateConstructInvokeStubFrameState()
FrameState v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::CreateConstructInvokeStubFrameState (Node * node, Node * outer_frame_state, SharedFunctionInfoRef shared, Node * context, CommonOperatorBuilder * common, TFGraph * graph)
Definition at line 2431 of file js-call-reducer.cc.
                                                                  {
  const FrameStateFunctionInfo* state_info =
      common->CreateFrameStateFunctionInfo(FrameStateType::kConstructInvokeStub,
                                           1, 0, 0, shared.object(), {});
  const Operator* op = common->FrameState(
      BytecodeOffset::None(), OutputFrameStateCombine::Ignore(), state_info);
  const Operator* op0 = common->StateValues(0, SparseInputMask::Dense());
  Node* node0 = graph->NewNode(op0);
  static constexpr int kTargetInputIndex = 0;
  static constexpr int kReceiverInputIndex = 1;
  std::vector<Node*> params;
  params.push_back(node->InputAt(kReceiverInputIndex));
  const Operator* op_param = common->StateValues(
      static_cast<int>(params.size()), SparseInputMask::Dense());
  Node* params_node = graph->NewNode(op_param, static_cast<int>(params.size()),
                                     &params.front());
  DCHECK(context);
  return FrameState(graph->NewNode(op, params_node, node0, node0, context,
                                   node->InputAt(kTargetInputIndex),
                                   outer_frame_state));
}
References v8::internal::compiler::CommonOperatorBuilder::CreateFrameStateFunctionInfo(), v8::internal::DCHECK(), v8::internal::compiler::SparseInputMask::Dense(), v8::internal::compiler::CommonOperatorBuilder::FrameState(), graph(), v8::internal::compiler::OutputFrameStateCombine::Ignore(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::kConstructInvokeStub, v8::internal::BytecodeOffset::None(), v8::internal::compiler::SharedFunctionInfoRef::object(), and v8::internal::compiler::CommonOperatorBuilder::StateValues().
Referenced by PromiseConstructorFrameState(), v8::internal::compiler::JSCallReducer::ReduceStringConstructor(), and v8::internal::compiler::JSCallReducer::ReduceTypedArrayConstructor().
CreateStringCreateLazyDeoptContinuationFrameState()
FrameState v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::CreateStringCreateLazyDeoptContinuationFrameState (JSGraph * graph, SharedFunctionInfoRef shared, Node * target, Node * context, Node * outer_frame_state)
Definition at line 7401 of file js-call-reducer.cc.
                             {
  Node* const receiver = graph->TheHoleConstant();
  Node* stack_parameters[]{receiver};
  const int stack_parameter_count = arraysize(stack_parameters);
  return CreateJavaScriptBuiltinContinuationFrameState(
      graph, shared, Builtin::kStringCreateLazyDeoptContinuation, target,
      context, stack_parameters, stack_parameter_count, outer_frame_state,
      ContinuationFrameStateMode::LAZY);
}
References arraysize, v8::internal::compiler::CreateJavaScriptBuiltinContinuationFrameState(), graph(), and v8::internal::compiler::LAZY.
Referenced by v8::internal::compiler::JSCallReducer::ReduceStringConstructor().
EverySomeLoopEagerFrameState()
FrameState v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::EverySomeLoopEagerFrameState (const EverySomeFrameStateParams & params, TNode< Number > k, ArrayEverySomeVariant variant)
Definition at line 2265 of file js-call-reducer.cc.
                                                                       {
  Builtin builtin = (variant == ArrayEverySomeVariant::kEvery)
                        ? Builtin::kArrayEveryLoopEagerDeoptContinuation
                        : Builtin::kArraySomeLoopEagerDeoptContinuation;
  Node* checkpoint_params[] = {params.receiver, params.callback,
                               params.this_arg, k, params.original_length};
  return CreateJavaScriptBuiltinContinuationFrameState(
      params.jsgraph, params.shared, builtin, params.target, params.context,
      checkpoint_params, arraysize(checkpoint_params), params.outer_frame_state,
      ContinuationFrameStateMode::EAGER);
}
References arraysize, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::EverySomeFrameStateParams::callback, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::EverySomeFrameStateParams::context, v8::internal::compiler::CreateJavaScriptBuiltinContinuationFrameState(), v8::internal::compiler::EAGER, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::EverySomeFrameStateParams::jsgraph, v8::internal::compiler::kEvery, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::EverySomeFrameStateParams::original_length, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::EverySomeFrameStateParams::outer_frame_state, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::EverySomeFrameStateParams::receiver, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::EverySomeFrameStateParams::shared, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::EverySomeFrameStateParams::target, and v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::EverySomeFrameStateParams::this_arg.
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeEverySome().
EverySomeLoopLazyFrameState()
FrameState v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::EverySomeLoopLazyFrameState (const EverySomeFrameStateParams & params, TNode< Number > k, ArrayEverySomeVariant variant)
Definition at line 2251 of file js-call-reducer.cc.
                                                                      {
  Builtin builtin = (variant == ArrayEverySomeVariant::kEvery)
                        ? Builtin::kArrayEveryLoopLazyDeoptContinuation
                        : Builtin::kArraySomeLoopLazyDeoptContinuation;
  Node* checkpoint_params[] = {params.receiver, params.callback,
                               params.this_arg, k, params.original_length};
  return CreateJavaScriptBuiltinContinuationFrameState(
      params.jsgraph, params.shared, builtin, params.target, params.context,
      checkpoint_params, arraysize(checkpoint_params), params.outer_frame_state,
      ContinuationFrameStateMode::LAZY);
}
References arraysize, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::EverySomeFrameStateParams::callback, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::EverySomeFrameStateParams::context, v8::internal::compiler::CreateJavaScriptBuiltinContinuationFrameState(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::EverySomeFrameStateParams::jsgraph, v8::internal::compiler::kEvery, v8::internal::compiler::LAZY, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::EverySomeFrameStateParams::original_length, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::EverySomeFrameStateParams::outer_frame_state, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::EverySomeFrameStateParams::receiver, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::EverySomeFrameStateParams::shared, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::EverySomeFrameStateParams::target, and v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::EverySomeFrameStateParams::this_arg.
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeEverySome().
FilterLoopEagerFrameState()
FrameState v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FilterLoopEagerFrameState (const FilterFrameStateParams & params, TNode< Number > k, TNode< Number > to)
Definition at line 2015 of file js-call-reducer.cc.
                                                                        {
  Node* checkpoint_params[] = {params.receiver,
                               params.callback,
                               params.this_arg,
                               params.a,
                               k,
                               params.original_length,
                               to};
  return CreateJavaScriptBuiltinContinuationFrameState(
      params.jsgraph, params.shared,
      Builtin::kArrayFilterLoopEagerDeoptContinuation, params.target,
      params.context, checkpoint_params, arraysize(checkpoint_params),
      params.outer_frame_state, ContinuationFrameStateMode::EAGER);
}
References v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FilterFrameStateParams::a, arraysize, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FilterFrameStateParams::callback, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FilterFrameStateParams::context, v8::internal::compiler::CreateJavaScriptBuiltinContinuationFrameState(), v8::internal::compiler::EAGER, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FilterFrameStateParams::jsgraph, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FilterFrameStateParams::original_length, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FilterFrameStateParams::outer_frame_state, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FilterFrameStateParams::receiver, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FilterFrameStateParams::shared, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FilterFrameStateParams::target, and v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FilterFrameStateParams::this_arg.
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFilter().
FilterLoopEagerPostCallbackFrameState()
FrameState v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FilterLoopEagerPostCallbackFrameState (const FilterFrameStateParams & params, TNode< Number > k, TNode< Number > to, TNode< Object > element, TNode< Object > callback_value)
Definition at line 1992 of file js-call-reducer.cc.
                                                         {
  // Note that we are intentionally reusing the
  // Builtin::kArrayFilterLoopLazyDeoptContinuation as an *eager* entry
  // point in this case. This is safe, because re-evaluating a [ToBoolean]
  // coercion is safe.
  Node* checkpoint_params[] = {params.receiver,
                               params.callback,
                               params.this_arg,
                               params.a,
                               k,
                               params.original_length,
                               element,
                               to,
                               callback_value};
  return CreateJavaScriptBuiltinContinuationFrameState(
      params.jsgraph, params.shared,
      Builtin::kArrayFilterLoopLazyDeoptContinuation, params.target,
      params.context, checkpoint_params, arraysize(checkpoint_params),
      params.outer_frame_state, ContinuationFrameStateMode::EAGER);
}
References v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FilterFrameStateParams::a, arraysize, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FilterFrameStateParams::callback, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FilterFrameStateParams::context, v8::internal::compiler::CreateJavaScriptBuiltinContinuationFrameState(), v8::internal::compiler::EAGER, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FilterFrameStateParams::jsgraph, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FilterFrameStateParams::original_length, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FilterFrameStateParams::outer_frame_state, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FilterFrameStateParams::receiver, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FilterFrameStateParams::shared, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FilterFrameStateParams::target, and v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FilterFrameStateParams::this_arg.
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFilter().
FilterLoopLazyFrameState()
FrameState v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FilterLoopLazyFrameState (const FilterFrameStateParams & params, TNode< Number > k, TNode< Number > to, TNode< Object > element)
Definition at line 1974 of file js-call-reducer.cc.
                                                           {
  Node* checkpoint_params[] = {params.receiver,
                               params.callback,
                               params.this_arg,
                               params.a,
                               k,
                               params.original_length,
                               element,
                               to};
  return CreateJavaScriptBuiltinContinuationFrameState(
      params.jsgraph, params.shared,
      Builtin::kArrayFilterLoopLazyDeoptContinuation, params.target,
      params.context, checkpoint_params, arraysize(checkpoint_params),
      params.outer_frame_state, ContinuationFrameStateMode::LAZY);
}
References v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FilterFrameStateParams::a, arraysize, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FilterFrameStateParams::callback, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FilterFrameStateParams::context, v8::internal::compiler::CreateJavaScriptBuiltinContinuationFrameState(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FilterFrameStateParams::jsgraph, v8::internal::compiler::LAZY, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FilterFrameStateParams::original_length, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FilterFrameStateParams::outer_frame_state, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FilterFrameStateParams::receiver, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FilterFrameStateParams::shared, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FilterFrameStateParams::target, and v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FilterFrameStateParams::this_arg.
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFilter().
FindLoopAfterCallbackLazyFrameState()
FrameState v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FindLoopAfterCallbackLazyFrameState (const FindFrameStateParams & params, TNode< Number > next_k, TNode< Object > if_found_value, ArrayFindVariant variant)
Definition at line 2162 of file js-call-reducer.cc.
                                                            {
  Builtin builtin =
      (variant == ArrayFindVariant::kFind)
          ? Builtin::kArrayFindLoopAfterCallbackLazyDeoptContinuation
          : Builtin::kArrayFindIndexLoopAfterCallbackLazyDeoptContinuation;
  Node* checkpoint_params[] = {params.receiver, params.callback,
                               params.this_arg, next_k,
                               params.original_length, if_found_value};
  return CreateJavaScriptBuiltinContinuationFrameState(
      params.jsgraph, params.shared, builtin, params.target, params.context,
      checkpoint_params, arraysize(checkpoint_params), params.outer_frame_state,
      ContinuationFrameStateMode::LAZY);
}
References arraysize, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FindFrameStateParams::callback, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FindFrameStateParams::context, v8::internal::compiler::CreateJavaScriptBuiltinContinuationFrameState(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FindFrameStateParams::jsgraph, v8::internal::compiler::kFind, v8::internal::compiler::LAZY, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FindFrameStateParams::original_length, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FindFrameStateParams::outer_frame_state, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FindFrameStateParams::receiver, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FindFrameStateParams::shared, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FindFrameStateParams::target, and v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FindFrameStateParams::this_arg.
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFind().
FindLoopEagerFrameState()
FrameState v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FindLoopEagerFrameState (const FindFrameStateParams & params, TNode< Number > k, ArrayFindVariant variant)
Definition at line 2149 of file js-call-reducer.cc.
                                                                              {
  Builtin builtin = (variant == ArrayFindVariant::kFind)
                        ? Builtin::kArrayFindLoopEagerDeoptContinuation
                        : Builtin::kArrayFindIndexLoopEagerDeoptContinuation;
  Node* checkpoint_params[] = {params.receiver, params.callback,
                               params.this_arg, k, params.original_length};
  return CreateJavaScriptBuiltinContinuationFrameState(
      params.jsgraph, params.shared, builtin, params.target, params.context,
      checkpoint_params, arraysize(checkpoint_params), params.outer_frame_state,
      ContinuationFrameStateMode::EAGER);
}
References arraysize, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FindFrameStateParams::callback, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FindFrameStateParams::context, v8::internal::compiler::CreateJavaScriptBuiltinContinuationFrameState(), v8::internal::compiler::EAGER, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FindFrameStateParams::jsgraph, v8::internal::compiler::kFind, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FindFrameStateParams::original_length, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FindFrameStateParams::outer_frame_state, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FindFrameStateParams::receiver, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FindFrameStateParams::shared, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FindFrameStateParams::target, and v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FindFrameStateParams::this_arg.
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFind().
FindLoopLazyFrameState()
FrameState v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FindLoopLazyFrameState (const FindFrameStateParams & params, TNode< Number > k, ArrayFindVariant variant)
Definition at line 2136 of file js-call-reducer.cc.
                                                                             {
  Builtin builtin = (variant == ArrayFindVariant::kFind)
                        ? Builtin::kArrayFindLoopLazyDeoptContinuation
                        : Builtin::kArrayFindIndexLoopLazyDeoptContinuation;
  Node* checkpoint_params[] = {params.receiver, params.callback,
                               params.this_arg, k, params.original_length};
  return CreateJavaScriptBuiltinContinuationFrameState(
      params.jsgraph, params.shared, builtin, params.target, params.context,
      checkpoint_params, arraysize(checkpoint_params), params.outer_frame_state,
      ContinuationFrameStateMode::LAZY);
}
References arraysize, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FindFrameStateParams::callback, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FindFrameStateParams::context, v8::internal::compiler::CreateJavaScriptBuiltinContinuationFrameState(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FindFrameStateParams::jsgraph, v8::internal::compiler::kFind, v8::internal::compiler::LAZY, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FindFrameStateParams::original_length, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FindFrameStateParams::outer_frame_state, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FindFrameStateParams::receiver, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FindFrameStateParams::shared, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FindFrameStateParams::target, and v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FindFrameStateParams::this_arg.
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFind().
ForEachLoopEagerFrameState()
FrameState v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ForEachLoopEagerFrameState (const ForEachFrameStateParams & params, TNode< Object > k)
Definition at line 1609 of file js-call-reducer.cc.
                                                       {
  Builtin builtin = Builtin::kArrayForEachLoopEagerDeoptContinuation;
  Node* checkpoint_params[] = {params.receiver, params.callback,
                               params.this_arg, k, params.original_length};
  return CreateJavaScriptBuiltinContinuationFrameState(
      params.jsgraph, params.shared, builtin, params.target, params.context,
      checkpoint_params, arraysize(checkpoint_params), params.outer_frame_state,
      ContinuationFrameStateMode::EAGER);
}
References arraysize, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ForEachFrameStateParams::callback, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ForEachFrameStateParams::context, v8::internal::compiler::CreateJavaScriptBuiltinContinuationFrameState(), v8::internal::compiler::EAGER, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ForEachFrameStateParams::jsgraph, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ForEachFrameStateParams::original_length, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ForEachFrameStateParams::outer_frame_state, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ForEachFrameStateParams::receiver, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ForEachFrameStateParams::shared, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ForEachFrameStateParams::target, and v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ForEachFrameStateParams::this_arg.
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeForEach().
ForEachLoopLazyFrameState()
FrameState v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ForEachLoopLazyFrameState (const ForEachFrameStateParams & params, TNode< Object > k)
Definition at line 1598 of file js-call-reducer.cc.
                                                      {
  Builtin builtin = Builtin::kArrayForEachLoopLazyDeoptContinuation;
  Node* checkpoint_params[] = {params.receiver, params.callback,
                               params.this_arg, k, params.original_length};
  return CreateJavaScriptBuiltinContinuationFrameState(
      params.jsgraph, params.shared, builtin, params.target, params.context,
      checkpoint_params, arraysize(checkpoint_params), params.outer_frame_state,
      ContinuationFrameStateMode::LAZY);
}
References arraysize, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ForEachFrameStateParams::callback, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ForEachFrameStateParams::context, v8::internal::compiler::CreateJavaScriptBuiltinContinuationFrameState(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ForEachFrameStateParams::jsgraph, v8::internal::compiler::LAZY, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ForEachFrameStateParams::original_length, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ForEachFrameStateParams::outer_frame_state, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ForEachFrameStateParams::receiver, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ForEachFrameStateParams::shared, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ForEachFrameStateParams::target, and v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ForEachFrameStateParams::this_arg.
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeForEach().
GetCallableForArrayIndexOfIncludes()
Callable v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::GetCallableForArrayIndexOfIncludes (ArrayIndexOfIncludesVariant variant, ElementsKind elements_kind, Isolate * isolate)
Definition at line 2338 of file js-call-reducer.cc.
                                                              {
  if (variant == ArrayIndexOfIncludesVariant::kIndexOf) {
    switch (elements_kind) {
      case PACKED_SMI_ELEMENTS:
      case HOLEY_SMI_ELEMENTS:
        return Builtins::CallableFor(isolate, Builtin::kArrayIndexOfSmi);
      case PACKED_ELEMENTS:
      case HOLEY_ELEMENTS:
        return Builtins::CallableFor(isolate,
                                     Builtin::kArrayIndexOfSmiOrObject);
      case PACKED_DOUBLE_ELEMENTS:
        return Builtins::CallableFor(isolate,
                                     Builtin::kArrayIndexOfPackedDoubles);
      default:
        DCHECK_EQ(HOLEY_DOUBLE_ELEMENTS, elements_kind);
        return Builtins::CallableFor(isolate,
                                     Builtin::kArrayIndexOfHoleyDoubles);
    }
  } else {
    DCHECK_EQ(variant, ArrayIndexOfIncludesVariant::kIncludes);
    switch (elements_kind) {
      case PACKED_SMI_ELEMENTS:
      case HOLEY_SMI_ELEMENTS:
        return Builtins::CallableFor(isolate, Builtin::kArrayIncludesSmi);
      case PACKED_ELEMENTS:
      case HOLEY_ELEMENTS:
        return Builtins::CallableFor(isolate,
                                     Builtin::kArrayIncludesSmiOrObject);
      case PACKED_DOUBLE_ELEMENTS:
        return Builtins::CallableFor(isolate,
                                     Builtin::kArrayIncludesPackedDoubles);
      default:
        DCHECK_EQ(HOLEY_DOUBLE_ELEMENTS, elements_kind);
        return Builtins::CallableFor(isolate,
                                     Builtin::kArrayIncludesHoleyDoubles);
    }
  }
  UNREACHABLE();
}
References v8::internal::Builtins::CallableFor(), DCHECK_EQ, v8::internal::HOLEY_DOUBLE_ELEMENTS, v8::internal::HOLEY_ELEMENTS, v8::internal::HOLEY_SMI_ELEMENTS, v8::internal::compiler::kIncludes, v8::internal::compiler::kIndexOf, v8::internal::PACKED_DOUBLE_ELEMENTS, v8::internal::PACKED_ELEMENTS, v8::internal::PACKED_SMI_ELEMENTS, and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeIndexOfIncludes().
InstanceTypeForCollectionKind()
InstanceType v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::InstanceTypeForCollectionKind (CollectionKind kind)
Definition at line 8143 of file js-call-reducer.cc.
                                                                {
  switch (kind) {
    case CollectionKind::kMap:
      return JS_MAP_TYPE;
    case CollectionKind::kSet:
      return JS_SET_TYPE;
  }
  UNREACHABLE();
}
References v8::internal::kMap, v8::internal::kSet, and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::JSCallReducer::ReduceCollectionIteration(), v8::internal::compiler::JSCallReducer::ReduceCollectionPrototypeHas(), and v8::internal::compiler::JSCallReducer::ReduceCollectionPrototypeSize().
IsCallOrConstructWithSpread()
bool v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::IsCallOrConstructWithSpread (Node * node)
Definition at line 4248 of file js-call-reducer.cc.
                                             {
  return node->opcode() == IrOpcode::kJSCallWithSpread ||
         node->opcode() == IrOpcode::kJSConstructWithSpread;
}
References v8::internal::compiler::Node::opcode().
Referenced by v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpread(), and v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpreadOfCreateArguments().
IsCallWithArrayLikeOrSpread()
bool v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::IsCallWithArrayLikeOrSpread (Node * node)
Definition at line 4253 of file js-call-reducer.cc.
                                             {
  return node->opcode() == IrOpcode::kJSCallWithArrayLike ||
         node->opcode() == IrOpcode::kJSCallWithSpread;
}
References v8::internal::compiler::Node::opcode().
Referenced by v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpread(), and v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpreadOfCreateArguments().
IsSafeArgumentsElements()
bool v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::IsSafeArgumentsElements (Node * node)
Definition at line 4230 of file js-call-reducer.cc.
                                         {
  for (Edge const edge : node->use_edges()) {
    if (!NodeProperties::IsValueEdge(edge)) continue;
    if (edge.from()->opcode() != IrOpcode::kLoadField &&
        edge.from()->opcode() != IrOpcode::kLoadElement) {
      return false;
    }
  }
  return true;
}
References v8::internal::compiler::NodeProperties::IsValueEdge(), and v8::internal::compiler::Node::use_edges().
Referenced by v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpreadOfCreateArguments().
MapLoopEagerFrameState()
FrameState v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::MapLoopEagerFrameState (const MapFrameStateParams & params, TNode< Number > k)
Definition at line 1878 of file js-call-reducer.cc.
                                                   {
  Node* checkpoint_params[] = {
      params.receiver, params.callback, params.this_arg, *params.a, k,
      params.original_length};
  return CreateJavaScriptBuiltinContinuationFrameState(
      params.jsgraph, params.shared,
      Builtin::kArrayMapLoopEagerDeoptContinuation, params.target,
      params.context, checkpoint_params, arraysize(checkpoint_params),
      params.outer_frame_state, ContinuationFrameStateMode::EAGER);
}
References v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::MapFrameStateParams::a, arraysize, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::MapFrameStateParams::callback, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::MapFrameStateParams::context, v8::internal::compiler::CreateJavaScriptBuiltinContinuationFrameState(), v8::internal::compiler::EAGER, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::MapFrameStateParams::jsgraph, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::MapFrameStateParams::original_length, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::MapFrameStateParams::outer_frame_state, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::MapFrameStateParams::receiver, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::MapFrameStateParams::shared, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::MapFrameStateParams::target, and v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::MapFrameStateParams::this_arg.
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeMap().
MapLoopLazyFrameState()
FrameState v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::MapLoopLazyFrameState (const MapFrameStateParams & params, TNode< Number > k)
Definition at line 1866 of file js-call-reducer.cc.
                                                  {
  Node* checkpoint_params[] = {
      params.receiver, params.callback, params.this_arg, *params.a, k,
      params.original_length};
  return CreateJavaScriptBuiltinContinuationFrameState(
      params.jsgraph, params.shared,
      Builtin::kArrayMapLoopLazyDeoptContinuation, params.target,
      params.context, checkpoint_params, arraysize(checkpoint_params),
      params.outer_frame_state, ContinuationFrameStateMode::LAZY);
}
References v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::MapFrameStateParams::a, arraysize, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::MapFrameStateParams::callback, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::MapFrameStateParams::context, v8::internal::compiler::CreateJavaScriptBuiltinContinuationFrameState(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::MapFrameStateParams::jsgraph, v8::internal::compiler::LAZY, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::MapFrameStateParams::original_length, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::MapFrameStateParams::outer_frame_state, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::MapFrameStateParams::receiver, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::MapFrameStateParams::shared, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::MapFrameStateParams::target, and v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::MapFrameStateParams::this_arg.
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeMap().
MapPreLoopLazyFrameState()
FrameState v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::MapPreLoopLazyFrameState (const MapFrameStateParams & params)
Definition at line 1855 of file js-call-reducer.cc.
                                                                       {
  DCHECK(!params.a);
  Node* checkpoint_params[] = {params.receiver, params.callback,
                               params.this_arg, params.original_length};
  return CreateJavaScriptBuiltinContinuationFrameState(
      params.jsgraph, params.shared,
      Builtin::kArrayMapPreLoopLazyDeoptContinuation, params.target,
      params.context, checkpoint_params, arraysize(checkpoint_params),
      params.outer_frame_state, ContinuationFrameStateMode::LAZY);
}
References v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::MapFrameStateParams::a, arraysize, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::MapFrameStateParams::callback, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::MapFrameStateParams::context, v8::internal::compiler::CreateJavaScriptBuiltinContinuationFrameState(), v8::internal::DCHECK(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::MapFrameStateParams::jsgraph, v8::internal::compiler::LAZY, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::MapFrameStateParams::original_length, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::MapFrameStateParams::outer_frame_state, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::MapFrameStateParams::receiver, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::MapFrameStateParams::shared, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::MapFrameStateParams::target, and v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::MapFrameStateParams::this_arg.
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeMap().
PromiseConstructorFrameState()
FrameState v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::PromiseConstructorFrameState (const PromiseCtorFrameStateParams & params, CommonOperatorBuilder * common, TFGraph * graph)
Definition at line 2457 of file js-call-reducer.cc.
                    {
  DCHECK_EQ(1,
            params.shared
                .internal_formal_parameter_count_without_receiver_deprecated());
  return CreateConstructInvokeStubFrameState(
      params.node_ptr, params.outer_frame_state, params.shared, params.context,
      common, graph);
}
References v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::PromiseCtorFrameStateParams::context, CreateConstructInvokeStubFrameState(), DCHECK_EQ, graph(), v8::internal::compiler::SharedFunctionInfoRef::internal_formal_parameter_count_without_receiver_deprecated(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::PromiseCtorFrameStateParams::node_ptr, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::PromiseCtorFrameStateParams::outer_frame_state, and v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::PromiseCtorFrameStateParams::shared.
Referenced by v8::internal::compiler::PromiseBuiltinReducerAssembler::ReducePromiseConstructor().
PromiseConstructorLazyFrameState()
FrameState v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::PromiseConstructorLazyFrameState (const PromiseCtorFrameStateParams & params, FrameState constructor_frame_state)
Definition at line 2468 of file js-call-reducer.cc.
                                        {
  // The deopt continuation of this frame state is never called; the frame state
  // is only necessary to obtain the right stack trace.
  JSGraph* jsgraph = params.jsgraph;
  Node* checkpoint_params[] = {
      jsgraph->UndefinedConstant(), /* receiver */
      jsgraph->UndefinedConstant(), /* promise */
      jsgraph->UndefinedConstant(), /* reject function */
      jsgraph->TheHoleConstant() /* exception */
  };
  return CreateJavaScriptBuiltinContinuationFrameState(
      jsgraph, params.shared, Builtin::kPromiseConstructorLazyDeoptContinuation,
      params.target, params.context, checkpoint_params,
      arraysize(checkpoint_params), constructor_frame_state,
      ContinuationFrameStateMode::LAZY);
}
References arraysize, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::PromiseCtorFrameStateParams::context, v8::internal::compiler::CreateJavaScriptBuiltinContinuationFrameState(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::PromiseCtorFrameStateParams::jsgraph, v8::internal::compiler::LAZY, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::PromiseCtorFrameStateParams::shared, and v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::PromiseCtorFrameStateParams::target.
Referenced by v8::internal::compiler::PromiseBuiltinReducerAssembler::ReducePromiseConstructor().
PromiseConstructorLazyWithCatchFrameState()
FrameState v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::PromiseConstructorLazyWithCatchFrameState (const PromiseCtorFrameStateParams & params, FrameState constructor_frame_state, TNode< JSPromise > promise, TNode< JSFunction > reject)
Definition at line 2487 of file js-call-reducer.cc.
                              {
  // This continuation just returns the created promise and takes care of
  // exceptions thrown by the executor.
  Node* checkpoint_params[] = {
      params.jsgraph->UndefinedConstant(), /* receiver */
      promise, reject};
  return CreateJavaScriptBuiltinContinuationFrameState(
      params.jsgraph, params.shared,
      Builtin::kPromiseConstructorLazyDeoptContinuation, params.target,
      params.context, checkpoint_params, arraysize(checkpoint_params),
      constructor_frame_state, ContinuationFrameStateMode::LAZY_WITH_CATCH);
}
References arraysize, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::PromiseCtorFrameStateParams::context, v8::internal::compiler::CreateJavaScriptBuiltinContinuationFrameState(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::PromiseCtorFrameStateParams::jsgraph, v8::internal::compiler::LAZY_WITH_CATCH, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::PromiseCtorFrameStateParams::shared, and v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::PromiseCtorFrameStateParams::target.
Referenced by v8::internal::compiler::PromiseBuiltinReducerAssembler::ReducePromiseConstructor().
ReduceLoopEagerFrameState()
FrameState v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ReduceLoopEagerFrameState (const ReduceFrameStateParams & params, TNode< Object > receiver, TNode< Object > callback, TNode< Object > k, TNode< Number > original_length, TNode< Object > accumulator)
Definition at line 1719 of file js-call-reducer.cc.
                                                                {
  Builtin builtin = (params.direction == ArrayReduceDirection::kLeft)
                        ? Builtin::kArrayReduceLoopEagerDeoptContinuation
                        : Builtin::kArrayReduceRightLoopEagerDeoptContinuation;
  Node* checkpoint_params[] = {receiver, callback, k, original_length,
                               accumulator};
  return CreateJavaScriptBuiltinContinuationFrameState(
      params.jsgraph, params.shared, builtin, params.target, params.context,
      checkpoint_params, arraysize(checkpoint_params), params.outer_frame_state,
      ContinuationFrameStateMode::EAGER);
}
References arraysize, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ReduceFrameStateParams::context, v8::internal::compiler::CreateJavaScriptBuiltinContinuationFrameState(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ReduceFrameStateParams::direction, v8::internal::compiler::EAGER, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ReduceFrameStateParams::jsgraph, v8::internal::compiler::kLeft, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ReduceFrameStateParams::outer_frame_state, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ReduceFrameStateParams::shared, and v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ReduceFrameStateParams::target.
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeReduce().
ReduceLoopLazyFrameState()
FrameState v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ReduceLoopLazyFrameState (const ReduceFrameStateParams & params, TNode< Object > receiver, TNode< Object > callback, TNode< Object > k, TNode< Number > original_length)
Definition at line 1705 of file js-call-reducer.cc.
                                                                   {
  Builtin builtin = (params.direction == ArrayReduceDirection::kLeft)
                        ? Builtin::kArrayReduceLoopLazyDeoptContinuation
                        : Builtin::kArrayReduceRightLoopLazyDeoptContinuation;
  Node* checkpoint_params[] = {receiver, callback, k, original_length};
  return CreateJavaScriptBuiltinContinuationFrameState(
      params.jsgraph, params.shared, builtin, params.target, params.context,
      checkpoint_params, arraysize(checkpoint_params), params.outer_frame_state,
      ContinuationFrameStateMode::LAZY);
}
References arraysize, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ReduceFrameStateParams::context, v8::internal::compiler::CreateJavaScriptBuiltinContinuationFrameState(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ReduceFrameStateParams::direction, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ReduceFrameStateParams::jsgraph, v8::internal::compiler::kLeft, v8::internal::compiler::LAZY, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ReduceFrameStateParams::outer_frame_state, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ReduceFrameStateParams::shared, and v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ReduceFrameStateParams::target.
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeReduce().
ReducePreLoopEagerFrameState()
FrameState v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ReducePreLoopEagerFrameState (const ReduceFrameStateParams & params, TNode< Object > receiver, TNode< Object > callback, TNode< Number > original_length)
Definition at line 1690 of file js-call-reducer.cc.
                                                                       {
  Builtin builtin =
      (params.direction == ArrayReduceDirection::kLeft)
          ? Builtin::kArrayReducePreLoopEagerDeoptContinuation
          : Builtin::kArrayReduceRightPreLoopEagerDeoptContinuation;
  Node* checkpoint_params[] = {receiver, callback, original_length};
  return CreateJavaScriptBuiltinContinuationFrameState(
      params.jsgraph, params.shared, builtin, params.target, params.context,
      checkpoint_params, arraysize(checkpoint_params), params.outer_frame_state,
      ContinuationFrameStateMode::EAGER);
}
References arraysize, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ReduceFrameStateParams::context, v8::internal::compiler::CreateJavaScriptBuiltinContinuationFrameState(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ReduceFrameStateParams::direction, v8::internal::compiler::EAGER, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ReduceFrameStateParams::jsgraph, v8::internal::compiler::kLeft, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ReduceFrameStateParams::outer_frame_state, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ReduceFrameStateParams::shared, and v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ReduceFrameStateParams::target.
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeReduce().
ReducePreLoopLazyFrameState()
FrameState v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ReducePreLoopLazyFrameState (const ReduceFrameStateParams & params, TNode< Object > receiver, TNode< Object > callback, TNode< Object > k, TNode< Number > original_length)
Definition at line 1676 of file js-call-reducer.cc.
                                                                      {
  Builtin builtin = (params.direction == ArrayReduceDirection::kLeft)
                        ? Builtin::kArrayReduceLoopLazyDeoptContinuation
                        : Builtin::kArrayReduceRightLoopLazyDeoptContinuation;
  Node* checkpoint_params[] = {receiver, callback, k, original_length};
  return CreateJavaScriptBuiltinContinuationFrameState(
      params.jsgraph, params.shared, builtin, params.target, params.context,
      checkpoint_params, arraysize(checkpoint_params), params.outer_frame_state,
      ContinuationFrameStateMode::LAZY);
}
References arraysize, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ReduceFrameStateParams::context, v8::internal::compiler::CreateJavaScriptBuiltinContinuationFrameState(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ReduceFrameStateParams::direction, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ReduceFrameStateParams::jsgraph, v8::internal::compiler::kLeft, v8::internal::compiler::LAZY, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ReduceFrameStateParams::outer_frame_state, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ReduceFrameStateParams::shared, and v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ReduceFrameStateParams::target.
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeReduce().
ShouldUseCallICFeedback()
bool v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ShouldUseCallICFeedback (Node * node)
Definition at line 4323 of file js-call-reducer.cc.
                                         {
  HeapObjectMatcher m(node);
  if (m.HasResolvedValue() || m.IsCheckClosure() || m.IsJSCreateClosure()) {
    // Don't use CallIC feedback when we know the function
    // being called, i.e. either know the closure itself or
    // at least the SharedFunctionInfo.
    return false;
  } else if (m.IsPhi()) {
    // Protect against endless loops here.
    Node* control = NodeProperties::GetControlInput(node);
    if (control->opcode() == IrOpcode::kLoop ||
        control->opcode() == IrOpcode::kDead) {
      return true;
    }
    // Check if {node} is a Phi of nodes which shouldn't
    // use CallIC feedback (not looking through loops).
    int const value_input_count = m.node()->op()->ValueInputCount();
    for (int n = 0; n < value_input_count; ++n) {
      if (ShouldUseCallICFeedback(node->InputAt(n))) return true;
    }
    return false;
  }
  return true;
}
References v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::NodeMatcher::node(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), and v8::internal::compiler::Operator::ValueInputCount().
Referenced by v8::internal::compiler::JSCallReducer::ReduceJSCall(), and v8::internal::compiler::JSCallReducer::TryReduceJSCallMathMinMaxWithArrayLike().
TargetIsClassConstructor()
bool v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::TargetIsClassConstructor (Node * node, JSHeapBroker * broker)
Definition at line 5406 of file js-call-reducer.cc.
                                                                {
  Node* target = NodeProperties::GetValueInput(node, 0);
  OptionalSharedFunctionInfoRef shared;
  HeapObjectMatcher m(target);
  if (m.HasResolvedValue()) {
    ObjectRef target_ref = m.Ref(broker);
    if (target_ref.IsJSFunction()) {
      JSFunctionRef function = target_ref.AsJSFunction();
      shared = function.shared(broker);
    }
  } else if (target->opcode() == IrOpcode::kJSCreateClosure) {
    CreateClosureParameters const& ccp =
        JSCreateClosureNode{target}.Parameters();
    shared = ccp.shared_info();
  } else if (target->opcode() == IrOpcode::kCheckClosure) {
    FeedbackCellRef cell = MakeRef(broker, FeedbackCellOf(target->op()));
    shared = cell.shared_function_info(broker);
  }
  if (shared.has_value() && IsClassConstructor(shared->kind())) return true;
  return false;
}
References broker(), v8::internal::compiler::FeedbackCellOf(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), v8::internal::IsClassConstructor(), v8::internal::compiler::MakeRef(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::HeapObjectMatcherImpl< kHeapConstantOpcode >::Ref(), v8::internal::compiler::FeedbackCellRef::shared_function_info(), and v8::internal::compiler::CreateClosureParameters::shared_info().
Referenced by v8::internal::compiler::JSCallReducer::ReduceJSCallWithArrayLike(), and v8::internal::compiler::JSCallReducer::ReduceJSCallWithSpread().