v8::internal::anonymous_namespace{wasm-objects.cc} Namespace Reference
Functions
void SetUsedLength (Tagged< ProtectedWeakFixedArray > uses, int length)
int GetUsedLength (Tagged< ProtectedWeakFixedArray > uses)
void SetEntry (Tagged< ProtectedWeakFixedArray > uses, int slot_index, Tagged< WasmTrustedInstanceData > user, int table_index)
Tagged< WasmTrustedInstanceData > GetInstance (Tagged< ProtectedWeakFixedArray > uses, int slot_index)
int GetTableIndex (Tagged< ProtectedWeakFixedArray > uses, int slot_index)
void CopyEntry (Tagged< ProtectedWeakFixedArray > dst, int dst_index, Tagged< ProtectedWeakFixedArray > src, int src_index)
void SetInstanceMemory (Tagged< WasmTrustedInstanceData > trusted_instance_data, Tagged< JSArrayBuffer > buffer, int memory_index)
DirectHandle< Object > CanonicalizeHeapNumber (DirectHandle< Object > number, Isolate *isolate, bool is_shared)
DirectHandle< Object > CanonicalizeSmi (DirectHandle< Object > smi, Isolate *isolate, bool is_shared)
Variables
static constexpr int kReservedSlotOffset = 1
constexpr int32_t kInt31MaxValue = 0x3fffffff
constexpr int32_t kInt31MinValue = -kInt31MaxValue - 1
Function Documentation
CanonicalizeHeapNumber()
DirectHandle<Object> v8::internal::anonymous_namespace{wasm-objects.cc}::CanonicalizeHeapNumber (DirectHandle< Object > number, Isolate * isolate, bool is_shared)
Definition at line 3336 of file wasm-objects.cc.
                                                                              {
  auto heap_number = Cast<HeapNumber>(number);
  double double_value = heap_number->value();
  if (double_value >= kInt31MinValue && double_value <= kInt31MaxValue &&
      !IsMinusZero(double_value) &&
      double_value == FastI2D(FastD2I(double_value))) {
    return direct_handle(Smi::FromInt(FastD2I(double_value)), isolate);
  }
  if (is_shared && !HeapLayout::InWritableSharedSpace(*heap_number)) {
    return isolate->factory()->NewHeapNumber<AllocationType::kSharedOld>(
        double_value);
  }
  return number;
}
References v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::FastD2I(), v8::internal::FastI2D(), v8::internal::Smi::FromInt(), v8::internal::HeapLayout::InWritableSharedSpace(), v8::internal::is_shared, v8::internal::IsMinusZero(), kInt31MaxValue, kInt31MinValue, v8::internal::kSharedOld, and v8::internal::FactoryBase< Impl >::NewHeapNumber().
Referenced by v8::internal::wasm::JSToWasmObject().
CanonicalizeSmi()
DirectHandle<Object> v8::internal::anonymous_namespace{wasm-objects.cc}::CanonicalizeSmi (DirectHandle< Object > smi, Isolate * isolate, bool is_shared)
Definition at line 3354 of file wasm-objects.cc.
                                                     {
  if constexpr (SmiValuesAre31Bits()) return smi;
  int32_t value = Cast<Smi>(*smi).value();
  if (value <= kInt31MaxValue && value >= kInt31MinValue) {
    return smi;
  } else if (is_shared) {
    return isolate->factory()->NewHeapNumber<AllocationType::kSharedOld>(value);
  } else {
    return isolate->factory()->NewHeapNumber(value);
  }
}
References v8::internal::Isolate::factory(), v8::internal::is_shared, kInt31MinValue, v8::internal::kSharedOld, v8::internal::FactoryBase< Impl >::NewHeapNumber(), v8::internal::SmiValuesAre31Bits(), and v8::internal::value.
Referenced by v8::internal::wasm::JSToWasmObject().
CopyEntry()
void v8::internal::anonymous_namespace{wasm-objects.cc}::CopyEntry (Tagged< ProtectedWeakFixedArray > dst, int dst_index, Tagged< ProtectedWeakFixedArray > src, int src_index)
Definition at line 94 of file wasm-objects.cc.
                                                                   {
  DCHECK(dst_index & 1);
  DCHECK(src_index & 1);
  // There shouldn't be a reason to copy cleared entries.
  DCHECK(
      IsWasmTrustedInstanceData(src->get(src_index).GetHeapObjectAssumeWeak()));
  DCHECK(IsSmi(src->get(src_index + 1)));
  dst->set(dst_index, src->get(src_index));
  dst->set(dst_index + 1, src->get(src_index + 1));
}
References v8::internal::DCHECK(), v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectAssumeWeak(), and v8::internal::IsSmi().
Referenced by v8::internal::WasmDispatchTable::MaybeGrowUsesList().
GetInstance()
Tagged<WasmTrustedInstanceData> v8::internal::anonymous_namespace{wasm-objects.cc}::GetInstance (Tagged< ProtectedWeakFixedArray > uses, int slot_index)
Definition at line 84 of file wasm-objects.cc.
                                                          {
  DCHECK(slot_index & 1);
  return Cast<WasmTrustedInstanceData>(
      uses->get(slot_index).GetHeapObjectAssumeWeak());
}
References v8::internal::DCHECK(), and v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectAssumeWeak().
Referenced by v8::internal::WasmTableObject::ClearDispatchTable(), v8::internal::WasmDispatchTable::Grow(), v8::internal::WasmTableObject::Grow(), and v8::internal::WasmTableObject::UpdateDispatchTable().
GetTableIndex()
int v8::internal::anonymous_namespace{wasm-objects.cc}::GetTableIndex (Tagged< ProtectedWeakFixedArray > uses, int slot_index)
Definition at line 90 of file wasm-objects.cc.
                                                                        {
  DCHECK(slot_index & 1);
  return Cast<Smi>(uses->get(slot_index + 1)).value();
}
References v8::internal::DCHECK().
Referenced by v8::internal::WasmTableObject::ClearDispatchTable(), v8::internal::WasmDispatchTable::Grow(), v8::internal::WasmTableObject::Grow(), and v8::internal::WasmTableObject::UpdateDispatchTable().
GetUsedLength()
int v8::internal::anonymous_namespace{wasm-objects.cc}::GetUsedLength (Tagged< ProtectedWeakFixedArray > uses)
Definition at line 72 of file wasm-objects.cc.
                                                        {
  if (uses->length() == 0) return 0;
  return Cast<Smi>(uses->get(0)).value();
}
Referenced by v8::internal::WasmDispatchTable::AddUse(), v8::internal::WasmTableObject::ClearDispatchTable(), v8::internal::WasmDispatchTable::Grow(), v8::internal::WasmTableObject::Grow(), v8::internal::WasmDispatchTable::MaybeGrowUsesList(), and v8::internal::WasmTableObject::UpdateDispatchTable().
SetEntry()
void v8::internal::anonymous_namespace{wasm-objects.cc}::SetEntry (Tagged< ProtectedWeakFixedArray > uses, int slot_index, Tagged< WasmTrustedInstanceData > user, int table_index)
Definition at line 76 of file wasm-objects.cc.
                                                                     {
  DCHECK(slot_index & 1);
  uses->set(slot_index, MakeWeak(user));
  uses->set(slot_index + 1, Smi::FromInt(table_index));
}
References v8::internal::DCHECK(), v8::internal::Smi::FromInt(), and v8::internal::MakeWeak().
Referenced by v8::internal::WasmDispatchTable::AddUse().
SetInstanceMemory()
void v8::internal::anonymous_namespace{wasm-objects.cc}::SetInstanceMemory (Tagged< WasmTrustedInstanceData > trusted_instance_data, Tagged< JSArrayBuffer > buffer, int memory_index)
Definition at line 834 of file wasm-objects.cc.
                                                                       {
  DisallowHeapAllocation no_gc;
  const WasmModule* module = trusted_instance_data->module();
  const wasm::WasmMemory& memory = module->memories[memory_index];
  bool is_wasm_module = module->origin == wasm::kWasmOrigin;
  bool use_trap_handler = memory.bounds_checks == wasm::kTrapHandler;
  // Asm.js does not use trap handling.
  CHECK_IMPLIES(use_trap_handler, is_wasm_module);
  // ArrayBuffers allocated for Wasm do always have a BackingStore.
  std::shared_ptr<BackingStore> backing_store = buffer->GetBackingStore();
  CHECK_IMPLIES(is_wasm_module, backing_store);
  CHECK_IMPLIES(is_wasm_module, backing_store->is_wasm_memory());
  // Wasm modules compiled to use the trap handler don't have bounds checks,
  // so they must have a memory that has guard regions.
  // Note: This CHECK can fail when in-sandbox corruption modified a
  // WasmMemoryObject. We currently believe that this would at worst
  // corrupt the contents of other Wasm memories or ArrayBuffers, but having
  // this CHECK in release mode is nice as an additional layer of defense.
  CHECK_IMPLIES(use_trap_handler, backing_store->has_guard_regions());
  // We checked this before, but a malicious worker thread with an in-sandbox
  // corruption primitive could have modified it since then.
  size_t byte_length = buffer->GetByteLength();
  SBXCHECK_GE(byte_length, memory.min_memory_size);
  trusted_instance_data->SetRawMemory(
      memory_index, reinterpret_cast<uint8_t*>(buffer->backing_store()),
      byte_length);
#if V8_ENABLE_DRUMBRAKE
  if (v8_flags.wasm_jitless &&
      trusted_instance_data->has_interpreter_object()) {
    AllowHeapAllocation allow_heap;
    Isolate* isolate = Isolate::Current();
    HandleScope scope(isolate);
    wasm::WasmInterpreterRuntime::UpdateMemoryAddress(
        direct_handle(trusted_instance_data->instance_object(), isolate));
  }
#endif // V8_ENABLE_DRUMBRAKE
}
References v8::internal::wasm::WasmMemory::bounds_checks, CHECK_IMPLIES, v8::internal::Isolate::Current(), v8::internal::direct_handle(), v8::internal::wasm::kTrapHandler, v8::internal::wasm::kWasmOrigin, v8::internal::wasm::WasmModule::memories, v8::internal::wasm::WasmMemory::min_memory_size, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::wasm::WasmModule::origin, SBXCHECK_GE, v8::internal::wasm::WasmInterpreterRuntime::UpdateMemoryAddress(), and v8::internal::v8_flags.
Referenced by v8::internal::WasmMemoryObject::UpdateInstances(), and v8::internal::WasmMemoryObject::UseInInstance().
SetUsedLength()
void v8::internal::anonymous_namespace{wasm-objects.cc}::SetUsedLength (Tagged< ProtectedWeakFixedArray > uses, int length)
Definition at line 68 of file wasm-objects.cc.
                                                                     {
  // {set} includes a DCHECK for sufficient capacity.
  uses->set(0, Smi::FromInt(length));
}
References v8::internal::Smi::FromInt(), and v8::internal::length.
Referenced by v8::internal::WasmDispatchTable::AddUse(), and v8::internal::WasmDispatchTable::MaybeGrowUsesList().
Variable Documentation
kInt31MaxValue
constexpr int32_t v8::internal::anonymous_namespace{wasm-objects.cc}::kInt31MaxValue = 0x3fffffff [constexpr]
Definition at line 3331 of file wasm-objects.cc.
Referenced by CanonicalizeHeapNumber().
kInt31MinValue
constexpr int32_t v8::internal::anonymous_namespace{wasm-objects.cc}::kInt31MinValue = -kInt31MaxValue - 1 [constexpr]
Definition at line 3332 of file wasm-objects.cc.
Referenced by CanonicalizeHeapNumber(), and CanonicalizeSmi().
kReservedSlotOffset
constexpr int v8::internal::anonymous_namespace{wasm-objects.cc}::kReservedSlotOffset = 1 [static], [constexpr]
Definition at line 67 of file wasm-objects.cc.
Referenced by v8::internal::WasmTableObject::ClearDispatchTable(), v8::internal::WasmDispatchTable::Grow(), v8::internal::WasmTableObject::Grow(), v8::internal::WasmDispatchTable::MaybeGrowUsesList(), and v8::internal::WasmTableObject::UpdateDispatchTable().