cppgc::internal::anonymous_namespace{heap.cc} Namespace Reference
Functions
void CheckConfig (GCConfig config, HeapBase::MarkingType marking_support, HeapBase::SweepingType sweeping_support)
Function Documentation
CheckConfig()
void cppgc::internal::anonymous_namespace{heap.cc}::CheckConfig (GCConfig config, HeapBase::MarkingType marking_support, HeapBase::SweepingType sweeping_support)
Definition at line 65 of file heap.cc.
                                                        {
  CHECK_LE(static_cast<int>(config.marking_type),
           static_cast<int>(marking_support));
  CHECK_LE(static_cast<int>(config.sweeping_type),
           static_cast<int>(sweeping_support));
}
References CHECK_LE, cppgc::internal::GCConfig::marking_type, and cppgc::internal::GCConfig::sweeping_type.
Referenced by cppgc::internal::Heap::CollectGarbage(), cppgc::internal::Heap::FinalizeIncrementalGarbageCollectionIfRunning(), and cppgc::internal::Heap::StartIncrementalGarbageCollection().