v8::internal::anonymous_namespace{scanner.cc} Namespace Reference
Functions
void ProcessPerFunctionCompileHints (const base::Vector< const uint8_t > &data, int current_position, std::vector< int > &positions)
Function Documentation
ProcessPerFunctionCompileHints()
void v8::internal::anonymous_namespace{scanner.cc}::ProcessPerFunctionCompileHints (const base::Vector< const uint8_t > & data, int current_position, std::vector< int > & positions)
Definition at line 255 of file scanner.cc.
                                                               {
  // Compile hints are relative to the position of the comment end.
  int last_position = current_position;
  size_t pos = 0;
  const char* char_data = reinterpret_cast<const char*>(data.data());
  while (pos < static_cast<size_t>(data.length())) {
    int32_t delta = base::VLQBase64Decode(char_data, data.length(), &pos);
    if (delta == std::numeric_limits<int32_t>::min()) {
      // Invalid data, bail out and clear the data we read so far. (Not using
      // the data until the invalid portion is consistent with 2-byte data not
      // being handled at all.)
      positions.clear();
      return;
    }
    last_position += delta;
    positions.push_back(last_position);
  }
  positions.shrink_to_fit();
}
References v8::base::Vector< T >::data(), v8::base::Vector< T >::length(), and v8::base::VLQBase64Decode().
Referenced by v8::internal::Scanner::TryToParseMagicComment().