v8::internal::torque::anonymous_namespace{instance-type-generator.cc} Namespace Reference
Classes
struct InstanceTypeTree
struct CompareUnconstrainedTypes
Functions
std::unique_ptr< InstanceTypeTree > BuildInstanceTypeTree ()
void PropagateInstanceTypeConstraints (InstanceTypeTree *root)
int SelectOwnValues (InstanceTypeTree *root, int start_value)
int SolveInstanceTypeConstraints (std::unique_ptr< InstanceTypeTree > root, int start_value, std::vector< std::unique_ptr< InstanceTypeTree >> *destination)
std::unique_ptr< InstanceTypeTree > SolveInstanceTypeConstraints (std::unique_ptr< InstanceTypeTree > root)
std::unique_ptr< InstanceTypeTree > AssignInstanceTypes ()
void PrintInstanceTypes (InstanceTypeTree *root, std::ostream &definitions, std::ostream &values, std::ostream &fully_defined_single_instance_types, std::ostream &fully_defined_multiple_instance_types, std::ostream &only_declared_single_instance_types, std::ostream &only_declared_multiple_instance_types, std::ostream &fully_defined_range_instance_types, std::ostream &only_declared_range_instance_types, const std::string &indent)
Function Documentation
AssignInstanceTypes()
std::unique_ptr<InstanceTypeTree> v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::AssignInstanceTypes ()
Definition at line 276 of file instance-type-generator.cc.
                                                      {
  std::unique_ptr<InstanceTypeTree> root = BuildInstanceTypeTree();
  if (root != nullptr) {
    PropagateInstanceTypeConstraints(root.get());
    root = SolveInstanceTypeConstraints(std::move(root));
  }
  return root;
}
References BuildInstanceTypeTree(), PropagateInstanceTypeConstraints(), and SolveInstanceTypeConstraints().
Referenced by v8::internal::torque::ImplementationVisitor::GenerateInstanceTypes().
BuildInstanceTypeTree()
std::unique_ptr<InstanceTypeTree> v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::BuildInstanceTypeTree ()
Definition at line 35 of file instance-type-generator.cc.
                                                        {
  // First, build InstanceTypeTree instances for every class but don't try to
  // attach them to their subclasses yet.
  std::unordered_map<const ClassType*, InstanceTypeTree*> map_by_type;
  std::vector<std::unique_ptr<InstanceTypeTree>> unparented_types;
  for (auto& p : GlobalContext::AllDeclarables()) {
    if (const TypeAlias* alias = TypeAlias::DynamicCast(p.get())) {
      const Type* type = alias->type();
      const ClassType* class_type = ClassType::DynamicCast(type);
      if (class_type == nullptr) {
        continue;
      }
      auto& map_slot = map_by_type[class_type];
      if (map_slot != nullptr) {
        continue; // We already encountered this type.
      }
      std::unique_ptr<InstanceTypeTree> type_tree =
          std::make_unique<InstanceTypeTree>(class_type);
      map_slot = type_tree.get();
      unparented_types.push_back(std::move(type_tree));
    }
  }
  // Second, assemble them all into a tree following the inheritance hierarchy.
  std::unique_ptr<InstanceTypeTree> root;
  for (auto& type_tree : unparented_types) {
    const ClassType* parent = type_tree->type->GetSuperClass();
    if (parent == nullptr) {
      if (root != nullptr)
        Error("Expected only one root class type. Found: ", root->type->name(),
              " and ", type_tree->type->name())
            .Position(type_tree->type->GetPosition());
      root = std::move(type_tree);
    } else {
      map_by_type[parent]->children.push_back(std::move(type_tree));
    }
  }
  return root;
}
References v8::internal::torque::GlobalContext::AllDeclarables(), v8::internal::torque::Error(), v8::internal::torque::ClassType::GetSuperClass(), v8::internal::torque::MessageBuilder::Position(), and v8::internal::tracing::type.
Referenced by AssignInstanceTypes().
PrintInstanceTypes()
void v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::PrintInstanceTypes (InstanceTypeTree * root, std::ostream & definitions, std::ostream & values, std::ostream & fully_defined_single_instance_types, std::ostream & fully_defined_multiple_instance_types, std::ostream & only_declared_single_instance_types, std::ostream & only_declared_multiple_instance_types, std::ostream & fully_defined_range_instance_types, std::ostream & only_declared_range_instance_types, const std::string & indent)
Definition at line 310 of file instance-type-generator.cc.
                                                 {
  std::string type_name =
      CapifyStringWithUnderscores(root->type->name()) + "_TYPE";
  std::string inner_indent = indent;
  if (root->num_values > 1) {
    definitions << indent << "V(FIRST_" << type_name << ", " << root->start
                << ") \\\n";
    inner_indent += " ";
  }
  if (root->num_own_values == 1) {
    definitions << inner_indent << "V(" << type_name << ", " << root->value
                << ") /* " << root->type->GetPosition() << " */\\\n";
    values << " V(" << type_name << ") /* " << root->type->GetPosition()
           << " */\\\n";
    std::ostream& type_checker_list =
        root->type->HasUndefinedLayout()
            ? (root->num_values == 1 ? only_declared_single_instance_types
                                     : only_declared_multiple_instance_types)
            : (root->num_values == 1 ? fully_defined_single_instance_types
                                     : fully_defined_multiple_instance_types);
    type_checker_list << " V(" << root->type->name() << ", " << type_name
                      << ") /* " << root->type->GetPosition() << " */ \\\n";
  }
  for (auto& child : root->children) {
    PrintInstanceTypes(child.get(), definitions, values,
                       fully_defined_single_instance_types,
                       fully_defined_multiple_instance_types,
                       only_declared_single_instance_types,
                       only_declared_multiple_instance_types,
                       fully_defined_range_instance_types,
                       only_declared_range_instance_types, inner_indent);
  }
  if (root->num_values > 1) {
    // We can't emit LAST_STRING_TYPE because it's not a valid flags
    // combination. So if the class type has multiple own values, which only
    // happens when using ANNOTATION_RESERVE_BITS_IN_INSTANCE_TYPE, then omit
    // the end marker.
    if (root->num_own_values <= 1) {
      definitions << indent << "V(LAST_" << type_name << ", " << root->end
                  << ") \\\n";
    }
    // Only output the instance type range for things other than the root type.
    if (root->type->GetSuperClass() != nullptr) {
      std::ostream& range_instance_types =
          root->type->HasUndefinedLayout() ? only_declared_range_instance_types
                                           : fully_defined_range_instance_types;
      range_instance_types << " V(" << root->type->name() << ", FIRST_"
                           << type_name << ", LAST_" << type_name << ") \\\n";
    }
  }
}
References v8::internal::torque::CapifyStringWithUnderscores(), v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::InstanceTypeTree::children, v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::InstanceTypeTree::end, v8::internal::torque::ClassType::GetPosition(), v8::internal::torque::ClassType::GetSuperClass(), v8::internal::torque::ClassType::HasUndefinedLayout(), v8::internal::torque::AggregateType::name(), v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::InstanceTypeTree::num_own_values, v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::InstanceTypeTree::num_values, v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::InstanceTypeTree::start, v8::internal::string, v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::InstanceTypeTree::type, and v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::InstanceTypeTree::value.
Referenced by v8::internal::torque::ImplementationVisitor::GenerateInstanceTypes().
PropagateInstanceTypeConstraints()
void v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::PropagateInstanceTypeConstraints (InstanceTypeTree * root)
Definition at line 76 of file instance-type-generator.cc.
                                                              {
  for (auto& child : root->children) {
    PropagateInstanceTypeConstraints(child.get());
    if (child->start < root->start) root->start = child->start;
    if (child->end > root->end) root->end = child->end;
    root->num_values += child->num_values;
  }
  const InstanceTypeConstraints& constraints =
      root->type->GetInstanceTypeConstraints();
  if (!root->type->IsAbstract() && !root->type->HasSameInstanceTypeAsParent()) {
    root->num_own_values = 1;
  }
  root->num_values += root->num_own_values;
  if (constraints.num_flags_bits != -1) {
    // Children won't get any types assigned; must be done manually in C++.
    root->children.clear();
    root->num_values = 1 << constraints.num_flags_bits;
    root->num_own_values = root->num_values;
    root->start = 0;
    root->end = root->num_values - 1;
  }
  if (constraints.value != -1) {
    if (root->num_own_values != 1) {
      Error("Instance type value requested for abstract class ",
            root->type->name())
          .Position(root->type->GetPosition());
    }
    root->value = constraints.value;
    if (constraints.value < root->start) root->start = constraints.value;
    if (constraints.value > root->end) root->end = constraints.value;
  }
}
References v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::InstanceTypeTree::children, v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::InstanceTypeTree::end, v8::internal::torque::Error(), v8::internal::torque::ClassType::GetInstanceTypeConstraints(), v8::internal::torque::ClassType::GetPosition(), v8::internal::torque::ClassType::HasSameInstanceTypeAsParent(), v8::internal::torque::ClassType::IsAbstract(), v8::internal::torque::AggregateType::name(), v8::internal::torque::InstanceTypeConstraints::num_flags_bits, v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::InstanceTypeTree::num_own_values, v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::InstanceTypeTree::num_values, v8::internal::torque::MessageBuilder::Position(), v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::InstanceTypeTree::start, v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::InstanceTypeTree::type, v8::internal::torque::InstanceTypeConstraints::value, and v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::InstanceTypeTree::value.
Referenced by AssignInstanceTypes().
SelectOwnValues()
int v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::SelectOwnValues (InstanceTypeTree * root, int start_value)
Definition at line 111 of file instance-type-generator.cc.
                                                             {
  if (root->value == -1) {
    root->value = start_value;
  } else if (root->value < start_value) {
    Error("Failed to assign instance type ", root->value, " to ",
          root->type->name())
        .Position(root->type->GetPosition());
  }
  return root->value + root->num_own_values;
}
References v8::internal::torque::Error(), v8::internal::torque::ClassType::GetPosition(), v8::internal::torque::AggregateType::name(), v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::InstanceTypeTree::num_own_values, v8::internal::torque::MessageBuilder::Position(), v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::InstanceTypeTree::type, and v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::InstanceTypeTree::value.
Referenced by SolveInstanceTypeConstraints().
SolveInstanceTypeConstraints() [1/2]
std::unique_ptr<InstanceTypeTree> v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::SolveInstanceTypeConstraints (std::unique_ptr< InstanceTypeTree > root)
Definition at line 269 of file instance-type-generator.cc.
                                          {
  std::vector<std::unique_ptr<InstanceTypeTree>> destination;
  SolveInstanceTypeConstraints(std::move(root), 0, &destination);
  return destination.empty() ? nullptr : std::move(destination.front());
}
References nullptr.
Referenced by AssignInstanceTypes(), and SolveInstanceTypeConstraints().
SolveInstanceTypeConstraints() [2/2]
int v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::SolveInstanceTypeConstraints (std::unique_ptr< InstanceTypeTree > root, int start_value, std::vector< std::unique_ptr< InstanceTypeTree >> * destination)
Definition at line 141 of file instance-type-generator.cc.
                                                             {
  if (root->start < start_value) {
    Error("Failed to assign instance type ", root->start, " to ",
          root->type->name())
        .Position(root->type->GetPosition());
  }
  // First, separate the children into four groups:
  // - The one child that must go first, if it exists;
  // - Children with specific value requirements ("constrained");
  // - Children without specific value requirements ("unconstrained");
  // - The one child that must go last, if it exists.
  std::unique_ptr<InstanceTypeTree> lowest_child;
  std::unique_ptr<InstanceTypeTree> highest_child;
  std::multimap<int, std::unique_ptr<InstanceTypeTree>>
      constrained_children_by_start;
  // Using std::map because you can't std::move out of a std::set until C++17.
  std::map<InstanceTypeTree*, std::unique_ptr<InstanceTypeTree>,
           CompareUnconstrainedTypes>
      unconstrained_children_by_size;
  for (auto& child : root->children) {
    if (child->type->IsHighestInstanceTypeWithinParent()) {
      if (highest_child) {
        Error("Two classes requested to be the highest instance type: ",
              highest_child->type->name(), " and ", child->type->name(),
              " within range for parent class ", root->type->name())
            .Position(child->type->GetPosition());
      }
      if (child->type->IsLowestInstanceTypeWithinParent()) {
        Error(
            "Class requested to be both highest and lowest instance type "
            "within its parent range: ",
            child->type->name())
            .Position(child->type->GetPosition());
      }
      highest_child = std::move(child);
    } else if (child->type->IsLowestInstanceTypeWithinParent()) {
      if (lowest_child) {
        Error("Two classes requested to be the lowest instance type: ",
              lowest_child->type->name(), " and ", child->type->name(),
              " within range for parent class ", root->type->name())
            .Position(child->type->GetPosition());
      }
      lowest_child = std::move(child);
    } else if (child->start > child->end) {
      unconstrained_children_by_size.insert(
          std::make_pair(child.get(), std::move(child)));
    } else {
      constrained_children_by_start.insert(
          std::make_pair(child->start, std::move(child)));
    }
  }
  root->children.clear();
  bool own_type_pending = root->num_own_values > 0;
  // Second, iterate and place the children in ascending order.
  if (lowest_child != nullptr) {
    start_value = SolveInstanceTypeConstraints(std::move(lowest_child),
                                               start_value, &root->children);
  }
  for (auto& constrained_child_pair : constrained_children_by_start) {
    // Select the next constrained child type in ascending order.
    std::unique_ptr<InstanceTypeTree> constrained_child =
        std::move(constrained_child_pair.second);
    // Try to place the root type before the constrained child type if it fits.
    if (own_type_pending) {
      if ((root->value != -1 && root->value < constrained_child->start) ||
          (root->value == -1 &&
           start_value + root->num_own_values <= constrained_child->start)) {
        start_value = SelectOwnValues(root.get(), start_value);
        own_type_pending = false;
      }
    }
    // Try to find any unconstrained children that fit before the constrained
    // one. This simple greedy algorithm just puts the biggest unconstrained
    // children in first, which might not fill the space as efficiently as
    // possible but is good enough for our needs.
    for (auto it = unconstrained_children_by_size.begin();
         it != unconstrained_children_by_size.end();) {
      if (it->second->num_values + start_value <= constrained_child->start) {
        start_value = SolveInstanceTypeConstraints(
            std::move(it->second), start_value, &root->children);
        it = unconstrained_children_by_size.erase(it);
      } else {
        ++it;
      }
    }
    // Place the constrained child type.
    start_value = SolveInstanceTypeConstraints(std::move(constrained_child),
                                               start_value, &root->children);
  }
  if (own_type_pending) {
    start_value = SelectOwnValues(root.get(), start_value);
    own_type_pending = false;
  }
  for (auto& child_pair : unconstrained_children_by_size) {
    start_value = SolveInstanceTypeConstraints(std::move(child_pair.second),
                                               start_value, &root->children);
  }
  if (highest_child != nullptr) {
    start_value = SolveInstanceTypeConstraints(std::move(highest_child),
                                               start_value, &root->children);
  }
  // Finally, set the range for this class to include all placed subclasses.
  root->end = start_value - 1;
  root->start =
      root->children.empty() ? start_value : root->children.front()->start;
  if (root->value != -1 && root->value < root->start) {
    root->start = root->value;
  }
  root->num_values = root->end - root->start + 1;
  root->type->InitializeInstanceTypes(
      root->value == -1 ? std::optional<int>{} : root->value,
      std::make_pair(root->start, root->end));
  if (root->num_values > 0) {
    destination->push_back(std::move(root));
  }
  return start_value;
}
References v8::internal::torque::Error(), v8::internal::torque::MessageBuilder::Position(), SelectOwnValues(), and SolveInstanceTypeConstraints().