v8::base Namespace Reference
Namespaces
 anonymous_namespace{logging.cc}
 anonymous_namespace{platform-cygwin.cc}
 anonymous_namespace{platform-darwin.cc}
 anonymous_namespace{platform-fuchsia.cc}
 anonymous_namespace{platform-linux.cc}
 anonymous_namespace{platform-posix.cc}
 anonymous_namespace{platform-starboard.cc}
 anonymous_namespace{platform-win32.cc}
 anonymous_namespace{platform.cc}
 anonymous_namespace{region-allocator.cc}
 anonymous_namespace{virtual-address-space.cc}
 anonymous_namespace{vlq-base64.cc}
 bits
 debug
 detail
 helper
 ieee754
 impl
 internal
 numerics
 time_internal
 tmp
Classes
struct PointerWithPayloadTraits< v8::internal::Scope >
class AddressRegion
class AtomicValue
class AsAtomicImpl
struct AtomicTypeFromByteWidth
struct AtomicTypeFromByteWidth< 1 >
struct AtomicTypeFromByteWidth< 2 >
struct AtomicTypeFromByteWidth< 4 >
class AsAtomicPointerImpl
class BitField
class BitFieldUnion
class BitSetComputer
class BoundedPageAllocator
class ContextualVariable
class ContextualVariableWithDefault
class CPU
class DiscriminatedUnion
struct DoublyThreadedListTraits
class DoublyThreadedList
class EmulatedVirtualAddressSubspace
Emulates a virtual address subspace.
class EnumSet
class Flags
class FPU
class FlushDenormalsScope
struct FreeDeleter
struct hash
class Hasher
struct hash< T >
struct bit_equal_to
struct bit_hash
struct NoHashMapValue
struct TemplateHashMapEntry
struct TemplateHashMapEntry< Key, NoHashMapValue >
class DefaultAllocationPolicy
class TemplateHashMapImpl
struct HashEqualityThenKeyMatcher
class CustomMatcherTemplateHashMapImpl
struct KeyEqualityMatcher
class PointerTemplateHashMapImpl
class TemplateHashMap
class IntrusiveSetIndex
class IntrusiveSet
struct iterator
class iterator_range
struct DerefPtrIterator
class TupleIterator
struct LeakyInstanceTrait
struct StaticallyAllocatedInstanceTrait
struct DynamicallyAllocatedInstanceTrait
struct DefaultConstructTrait
struct DefaultCreateTrait
struct ThreadSafeInitOnceTrait
struct SingleThreadInitOnceTrait
struct LazyInstanceImpl
struct LazyStaticInstance
struct LazyInstance
struct LazyDynamicInstance
class LeakyObject
class CheckMessageStream
struct is_signed_vs_unsigned
struct is_unsigned_vs_signed
struct is_trivially_copyable
struct is_trivially_destructible
struct Use
class Bignum
struct CachedPower
class PowersOfTenCache
class DiyFp
class Double
struct DivMagic
class UInt128
struct FunctionWithArgs
class SharedMemoryMapping
class SharedMemory
class PageAllocator
class ConditionVariable
class ElapsedTimer
struct ScopedTimer
struct AllocationResult
class Mutex
class RecursiveMutex
class LockGuard
class MutexGuardIf
class AIXTimezoneCache
class CygwinTimezoneCache
struct MemoryRegion
class PosixDefaultTimezoneCache
class PosixMemoryMappedFile
class PosixTimezoneCache
class SolarisTimezoneCache
class StarboardMemoryMappedFile
class StarboardTimezoneCache
class StarboardDefaultTimezoneCache
class WindowsTimezoneCache
class Win32Time
class Win32MemoryMappedFile
class PreciseSleepTimer
class ZOSTimezoneCache
class OS
class AddressSpaceReservation
class Thread
class Stack
class Semaphore
struct CreateSemaphoreTrait
struct LazySemaphore
class TimeConstants
class TimeDelta
class Time
class TimeTicks
class ThreadTicks
struct PointerWithPayloadTraits
struct PointerWithPayloadTraits< void >
class PointerWithPayload
class RegionAllocator
class RingBuffer
class LsanPageAllocator
class LsanVirtualAddressSpace
class SmallMap
class SmallVector
class FormattedString
class StrongAlias
class SysInfo
struct pass_value_or_ref
struct index_of_type
struct index_of_type< SearchT >
struct index_of_type< SearchT, SearchT, Ts... >
struct index_of_type< SearchT, T, Ts... >
struct ThreadedListTraits
class ThreadedListBase
struct EmptyBase
class TimezoneCache
class RandomNumberGenerator
class Vector
class ScopedVector
class OwnedVector
class EmbeddedVector
class VirtualAddressSpacePageAllocator
class VirtualAddressSpaceBase
class VirtualAddressSpace
class VirtualAddressSubspace
struct hash< const cppgc::internal::BasePage * >
struct hash< i::LargePageMetadata * >
struct hash< const i::LargePageMetadata * >
struct hash< const i::MemoryChunkMetadata * >
struct hash< i::MemoryChunkMetadata * >
struct hash< const i::MemoryChunk * >
struct hash< i::MemoryChunk * >
struct hash< i::MutablePageMetadata * >
struct hash< const i::MutablePageMetadata * >
struct hash< i::PageMetadata * >
struct hash< const i::PageMetadata * >
struct hash< i::ReadOnlyPageMetadata * >
struct hash< const i::ReadOnlyPageMetadata * >
struct PointerWithPayloadTraits< v8::internal::AstRawString >
Typedefs
using AsAtomic8 = AsAtomicImpl< base::Atomic8 >
using AsAtomic16 = AsAtomicImpl< base::Atomic16 >
using AsAtomic32 = AsAtomicImpl< base::Atomic32 >
using AsAtomicWord = AsAtomicImpl< base::AtomicWord >
using AsAtomicPointer = AsAtomicPointerImpl< base::AtomicWord >
using Atomic8 = char
using Atomic16 = int16_t
using Atomic32 = int32_t
using AtomicWord = Atomic32
template<class T , int shift, int size>
using BitField8 = BitField< T, shift, size, uint8_t >
template<class T , int shift, int size>
using BitField16 = BitField< T, shift, size, uint16_t >
template<class T , int shift, int size>
using BitField64 = BitField< T, shift, size, uint64_t >
template<class T >
using ContextualClass = ContextualVariable< T, T >
using CustomMatcherHashMap = CustomMatcherTemplateHashMapImpl< DefaultAllocationPolicy >
using HashMap = PointerTemplateHashMapImpl< DefaultAllocationPolicy >
using Address = uintptr_t
using SizeT = StrictNumeric< size_t >
using OnceType = std::atomic< uint8_t >
using PointerArgFunction = void(*)(void *arg)
using LazyConditionVariable = LazyStaticInstance< ConditionVariable, DefaultConstructTrait< ConditionVariable >, ThreadSafeInitOnceTrait >::type
using LazyMutex = LazyStaticInstance< Mutex, DefaultConstructTrait< Mutex >, ThreadSafeInitOnceTrait >::type
using LazyRecursiveMutex = LazyStaticInstance< RecursiveMutex, DefaultConstructTrait< RecursiveMutex >, ThreadSafeInitOnceTrait >::type
using MutexGuard = LockGuard< Mutex >
using RecursiveMutexGuard = LockGuard< RecursiveMutex >
typedef PVOID(__stdcall * VirtualAlloc2_t) (HANDLE, PVOID, SIZE_T, ULONG, ULONG, MEM_EXTENDED_PARAMETER *, ULONG)
typedef PVOID(__stdcall * MapViewOfFile3_t) (HANDLE, HANDLE, PVOID, ULONG64, SIZE_T, ULONG, ULONG, MEM_EXTENDED_PARAMETER *, ULONG)
typedef PVOID(__stdcall * UnmapViewOfFile2_t) (HANDLE, PVOID, ULONG)
using SymInitialize = BOOL(__stdcall *)(IN HANDLE hProcess, IN PSTR UserSearchPath, IN BOOL fInvadeProcess)
using SymGetOptions = DWORD(__stdcall *)(VOID)
using SymSetOptions = DWORD(__stdcall *)(IN DWORD SymOptions)
using SymGetSearchPath = BOOL(__stdcall *)(IN HANDLE hProcess, OUT PSTR SearchPath, IN DWORD SearchPathLength)
using SymLoadModule64 = DWORD64(__stdcall *)(IN HANDLE hProcess, IN HANDLE hFile, IN PSTR ImageName, IN PSTR ModuleName, IN DWORD64 BaseOfDll, IN DWORD SizeOfDll)
using StackWalk64 = BOOL(__stdcall *)(DWORD MachineType, HANDLE hProcess, HANDLE hThread, LPSTACKFRAME64 StackFrame, PVOID ContextRecord, PREAD_PROCESS_MEMORY_ROUTINE64 ReadMemoryRoutine, PFUNCTION_TABLE_ACCESS_ROUTINE64 FunctionTableAccessRoutine, PGET_MODULE_BASE_ROUTINE64 GetModuleBaseRoutine, PTRANSLATE_ADDRESS_ROUTINE64 TranslateAddress)
using SymGetSymFromAddr64 = BOOL(__stdcall *)(IN HANDLE hProcess, IN DWORD64 qwAddr, OUT PDWORD64 pdwDisplacement, OUT PIMAGEHLP_SYMBOL64 Symbol)
using SymGetLineFromAddr64 = BOOL(__stdcall *)(IN HANDLE hProcess, IN DWORD64 qwAddr, OUT PDWORD pdwDisplacement, OUT PIMAGEHLP_LINE64 Line64)
using SymFunctionTableAccess64 = PVOID(__stdcall *)(HANDLE hProcess, DWORD64 AddrBase)
using SymGetModuleBase64 = DWORD64(__stdcall *)(HANDLE hProcess, DWORD64 AddrBase)
using CreateToolhelp32Snapshot = HANDLE(__stdcall *)(DWORD dwFlags, DWORD th32ProcessID)
using Module32FirstW = BOOL(__stdcall *)(HANDLE hSnapshot, LPMODULEENTRY32W lpme)
using Module32NextW = BOOL(__stdcall *)(HANDLE hSnapshot, LPMODULEENTRY32W lpme)
using uc16 = uint16_t
using uc32 = uint32_t
template<class Tuple , class T >
using append_tuple_type = decltype(std::tuple_cat(std::declval< Tuple >(), std::declval< std::tuple< T > >()))
template<class T , class Tuple >
using prepend_tuple_type = decltype(std::tuple_cat(std::declval< std::tuple< T > >(), std::declval< Tuple >()))
template<size_t N, typename... T>
using nth_type_t = typename detail::nth_type< N, T... >::type
template<typename T , typename TLTraits = ThreadedListTraits<T>>
using ThreadedList = ThreadedListBase< T, EmptyBase, TLTraits >
template<typename T , typename TLTraits = ThreadedListTraits<T>>
using ThreadedListWithUnsafeInsertions = ThreadedListBase< T, EmptyBase, TLTraits, kUnsafeInsertion >
Enumerations
enum class AbortMode { kExitWithSuccessAndIgnoreDcheckFailures
, kExitWithFailureAndIgnoreDcheckFailures
, kImmediateCrash
, kDefault
 }
enum class PageInitializationMode { kAllocatedPagesMustBeZeroInitialized
, kAllocatedPagesCanBeUninitialized
, kRecommitOnly
 }
enum class PageFreeingMode { kMakeInaccessible
, kDiscard
 }
enum class OOMType { kJavaScript
, kProcess
 }
enum BignumDtoaMode { BIGNUM_DTOA_SHORTEST
, BIGNUM_DTOA_FIXED
, BIGNUM_DTOA_PRECISION
 }
enum DtoaMode { DTOA_SHORTEST
, DTOA_FIXED
, DTOA_PRECISION
 }
enum FastDtoaMode { FAST_DTOA_SHORTEST
, FAST_DTOA_PRECISION
 }
enum : uint8_t { ONCE_STATE_UNINITIALIZED = 0
, ONCE_STATE_EXECUTING_FUNCTION = 1
, ONCE_STATE_DONE = 2
 }
enum OutputMode { UNKNOWN
, CONSOLE
, ODS
 }
Functions
bool ControlledCrashesAreHarmless ()
bool DcheckFailuresAreIgnored ()
ASSERT_TRIVIALLY_COPYABLE (AddressRegion)
template<typename T >
AddressRegion AddressRegionOf (T *ptr, size_t size)
template<typename Container >
auto AddressRegionOf (Container &&c) -> decltype(AddressRegionOf(c.data(), c.size()))
std::ostream & operator<< (std::ostream &out, AddressRegion region)
template<typename T >
void CheckedIncrement (std::atomic< T > *number, T amount, std::memory_order order=std::memory_order_seq_cst) requires std
template<typename T >
const std::atomic< T > * AsAtomicPtr (const T *t)
void SeqCst_MemoryFence ()
Atomic8 Relaxed_CompareAndSwap (volatile Atomic8 *ptr, Atomic8 old_value, Atomic8 new_value)
Atomic16 Relaxed_CompareAndSwap (volatile Atomic16 *ptr, Atomic16 old_value, Atomic16 new_value)
Atomic32 Relaxed_CompareAndSwap (volatile Atomic32 *ptr, Atomic32 old_value, Atomic32 new_value)
Atomic32 Relaxed_AtomicExchange (volatile Atomic32 *ptr, Atomic32 new_value)
Atomic32 SeqCst_AtomicExchange (volatile Atomic32 *ptr, Atomic32 new_value)
Atomic32 Relaxed_AtomicIncrement (volatile Atomic32 *ptr, Atomic32 increment)
Atomic32 Acquire_CompareAndSwap (volatile Atomic32 *ptr, Atomic32 old_value, Atomic32 new_value)
Atomic8 Release_CompareAndSwap (volatile Atomic8 *ptr, Atomic8 old_value, Atomic8 new_value)
Atomic32 Release_CompareAndSwap (volatile Atomic32 *ptr, Atomic32 old_value, Atomic32 new_value)
Atomic32 AcquireRelease_CompareAndSwap (volatile Atomic32 *ptr, Atomic32 old_value, Atomic32 new_value)
Atomic32 SeqCst_CompareAndSwap (volatile Atomic32 *ptr, Atomic32 old_value, Atomic32 new_value)
void Relaxed_Store (volatile Atomic8 *ptr, Atomic8 value)
void Relaxed_Store (volatile Atomic16 *ptr, Atomic16 value)
void Relaxed_Store (volatile Atomic32 *ptr, Atomic32 value)
void Release_Store (volatile Atomic8 *ptr, Atomic8 value)
void Release_Store (volatile Atomic16 *ptr, Atomic16 value)
void Release_Store (volatile Atomic32 *ptr, Atomic32 value)
void SeqCst_Store (volatile Atomic8 *ptr, Atomic8 value)
void SeqCst_Store (volatile Atomic16 *ptr, Atomic16 value)
void SeqCst_Store (volatile Atomic32 *ptr, Atomic32 value)
Atomic8 Relaxed_Load (volatile const Atomic8 *ptr)
Atomic16 Relaxed_Load (volatile const Atomic16 *ptr)
Atomic32 Relaxed_Load (volatile const Atomic32 *ptr)
Atomic8 Acquire_Load (volatile const Atomic8 *ptr)
Atomic32 Acquire_Load (volatile const Atomic32 *ptr)
Atomic8 SeqCst_Load (volatile const Atomic8 *ptr)
Atomic32 SeqCst_Load (volatile const Atomic32 *ptr)
void Relaxed_Memcpy (volatile Atomic8 *dst, volatile const Atomic8 *src, size_t bytes)
void Relaxed_Memmove (volatile Atomic8 *dst, volatile const Atomic8 *src, size_t bytes)
int Relaxed_Memcmp (volatile const Atomic8 *s1, volatile const Atomic8 *s2, size_t len)
template<typename T , typename U >
requires ((std::is_integral_v< T >||std::is_enum_v< T >) &&(std::is_integral_v< U >||std::is_enum_v< U >)) &&(sizeof(U)<
template<typename C , typename T >
bool contains (const C &container, const T &element)
template<typename C , typename T >
std::optional< size_t > index_of (const C &container, const T &element)
template<typename C , typename P >
std::optional< size_t > index_of_if (const C &container, const P &predicate)
template<typename C >
size_t erase_at (C &container, size_t index, size_t count=1)
template<typename C , typename P >
size_t erase_if (C &container, const P &predicate)
template<typename C , typename P >
size_t count_if (const C &container, const P &predicate)
template<typename C , typename P >
bool all_of (const C &container, const P &predicate)
template<typename C >
bool all_of (const C &container)
template<typename C , typename P >
bool any_of (const C &container, const P &predicate)
template<typename C >
bool any_of (const C &container)
template<typename C , typename P >
bool none_of (const C &container, const P &predicate)
template<typename C >
void sort (C &container)
template<typename C , typename Comp >
void sort (C &container, Comp comp)
template<typename C >
bool all_equal (const C &container)
template<typename C , typename T >
bool all_equal (const C &container, const T &value)
template<typename V , typename C >
void vector_append (V &v, const C &container)
template<typename T >
requires std::unsigned_integral< T > MagicNumbersForDivision< T > SignedDivisionByConstant (T d)
template<class T >
MagicNumbersForDivision< T > UnsignedDivisionByConstant (T d, unsigned leading_zeros)
template struct EXPORT_TEMPLATE_DEFINE (V8_BASE_EXPORT) MagicNumbersForDivision< uint32_t >
template<class T >
struct EXPORT_TEMPLATE_DECLARE (V8_BASE_EXPORT) MagicNumbersForDivision
template<typename T >
requires std::signed_integral< T > MagicNumbersForDivision< T > SignedDivisionByConstant (T d)
template<typename E , typename T >
std::ostream & operator<< (std::ostream &os, EnumSet< E, T > set)
std::unique_ptr< char[]> RelativePath (const char *exec_path, const char *name)
size_t hash_combine (size_t seed, size_t hash)
template<typename T >
size_t hash_value_unsigned_impl (T v)
V8_BASE_HASH_VALUE_TRIVIAL (unsigned short) inline size_t hash_value(unsigned int v)
size_t hash_value (unsigned long v)
size_t hash_value (unsigned long long v)
V8_BASE_HASH_VALUE_SIGNED (short) V8_BASE_HASH_VALUE_SIGNED(int) V8_BASE_HASH_VALUE_SIGNED(long) V8_BASE_HASH_VALUE_SIGNED(long long) inline size_t hash_value(float v)
size_t hash_value (double v)
template<typename T , size_t N>
size_t hash_value (const T(&v)[N])
template<typename T , size_t N>
size_t hash_value (T(&v)[N])
template<typename T >
size_t hash_value (T *const &v)
template<typename T1 , typename T2 >
size_t hash_value (std::pair< T1, T2 > const &v)
template<typename... T, size_t... I>
size_t hash_value_impl (std::tuple< T... > const &v, std::index_sequence< I... >)
template<typename... T>
size_t hash_value (std::tuple< T... > const &v)
template<typename T >
size_t hash_value (T v) requires std
size_t hash_value (const T &v)
template<typename... Ts>
size_t hash_combine (Ts const &... vs)
template<typename Iterator >
size_t hash_range (Iterator first, Iterator last)
template<typename ForwardIterator >
auto make_iterator_range (ForwardIterator begin, ForwardIterator end)
template<typename T >
auto Reversed (T &t)
template<typename T >
auto Reversed (const iterator_range< T > &t)
template<typename T >
auto IterateWithoutLast (T &t)
template<typename T >
auto IterateWithoutLast (const iterator_range< T > &t)
template<typename T >
auto IterateWithoutFirst (T &t)
template<typename T >
auto IterateWithoutFirst (const iterator_range< T > &t)
template<class... Containers>
auto zip (Containers &... containers)
void SetPrintStackTrace (void(*print_stack_trace)())
void SetDcheckFunction (void(*dcheck_function)(const char *, int, const char *))
void SetFatalFunction (void(*fatal_function)(const char *, int, const char *))
void FatalOOM (OOMType type, const char *msg)
template<typename T >
std::string PrintCheckOperand (T val)
template<typename T >
requires (!std::is_function_v< std::remove_pointer_t< T >> &&!std::is_enum_v< T > &&has_output_operator< T, CheckMessageStream >) std
template<typename T >
requires (std::is_function_v< typename std::remove_pointer_t< T >>) std
template<typename T >
requires (std::is_enum_v< T >) std
template<typename T >
requires (!has_output_operator< T, CheckMessageStream > &&requires(T t) { { t.begin() } -> std::forward_iterator;}) std
template<typename Lhs , typename Rhs >
V8_NOINLINE std::string * MakeCheckOpString (Lhs lhs, Rhs rhs, char const *msg)
EXPLICIT_CHECK_OP_INSTANTIATION (long) EXPLICIT_CHECK_OP_INSTANTIATION(long long) EXPLICIT_CHECK_OP_INSTANTIATION(unsigned long) EXPLICIT_CHECK_OP_INSTANTIATION(unsigned long long) template< typename T > struct comparison_underlying_type
DEFINE_SIGNED_MISMATCH_COMP (is_signed_vs_unsigned, EQ, lhs >=0 &&MAKE_UNSIGNED(Lhs, lhs)==MAKE_UNDERLYING(Rhs, rhs)) DEFINE_SIGNED_MISMATCH_COMP(is_signed_vs_unsigned
template<class Dest , class Source >
Dest bit_cast (Source const &source)
template<class T >
T & Memory (Address addr)
template<class T >
T & Memory (uint8_t *addr)
template<typename V >
static V ReadUnalignedValue (Address p)
template<typename V >
static V ReadUnalignedValue (const char p[sizeof(V)])
template<typename V >
static void WriteUnalignedValue (Address p, V value)
template<typename V >
static void WriteUnalignedValue (char p[sizeof(V)], V value)
template<typename V >
static V ReadLittleEndianValue (Address p)
template<typename V >
static void WriteLittleEndianValue (Address p, V value)
template<typename V >
static V ReadLittleEndianValue (V *p)
template<typename V >
static void WriteLittleEndianValue (V *p, V value)
static int NormalizedExponent (uint64_t significand, int exponent)
static int EstimatePower (int exponent)
static void InitialScaledStartValues (double v, int estimated_power, bool need_boundary_deltas, Bignum *numerator, Bignum *denominator, Bignum *delta_minus, Bignum *delta_plus)
static void FixupMultiply10 (int estimated_power, bool is_even, int *decimal_point, Bignum *numerator, Bignum *denominator, Bignum *delta_minus, Bignum *delta_plus)
static void GenerateShortestDigits (Bignum *numerator, Bignum *denominator, Bignum *delta_minus, Bignum *delta_plus, bool is_even, Vector< char > buffer, int *length)
static void BignumToFixed (int requested_digits, int *decimal_point, Bignum *numerator, Bignum *denominator, Vector< char >(buffer), int *length)
static void GenerateCountedDigits (int count, int *decimal_point, Bignum *numerator, Bignum *denominator, Vector< char >(buffer), int *length)
void BignumDtoa (double v, BignumDtoaMode mode, int requested_digits, Vector< char > buffer, int *length, int *decimal_point)
static void InitialScaledStartValuesPositiveExponent (double v, int estimated_power, bool need_boundary_deltas, Bignum *numerator, Bignum *denominator, Bignum *delta_minus, Bignum *delta_plus)
static void InitialScaledStartValuesNegativeExponentPositivePower (double v, int estimated_power, bool need_boundary_deltas, Bignum *numerator, Bignum *denominator, Bignum *delta_minus, Bignum *delta_plus)
static void InitialScaledStartValuesNegativeExponentNegativePower (double v, int estimated_power, bool need_boundary_deltas, Bignum *numerator, Bignum *denominator, Bignum *delta_minus, Bignum *delta_plus)
template<typename S >
static int BitSize (S value)
static uint64_t ReadUInt64 (Vector< const char > buffer, int from, int digits_to_read)
static int HexCharValue (char c)
template<typename S >
static int SizeInHexChars (S number)
constexpr uint64_t double_to_uint64 (double d)
constexpr double uint64_to_double (uint64_t d64)
static BignumDtoaMode DtoaToBignumDtoaMode (DtoaMode dtoa_mode)
void DoubleToAscii (double v, DtoaMode mode, int requested_digits, Vector< char > buffer, int *sign, int *length, int *point)
static bool RoundWeed (char *last_digit, uint64_t distance_too_high_w, uint64_t unsafe_interval, uint64_t rest, uint64_t ten_kappa, uint64_t unit)
static bool RoundWeedCounted (Vector< char > buffer, int length, uint64_t rest, uint64_t ten_kappa, uint64_t unit, int *kappa)
static uint32_t fast_divmod (uint32_t *val, uint32_t divisor, const DivMagic &d)
static void BiggestPowerTen (uint32_t number, int number_bits, uint32_t *power, unsigned *exponent)
static bool DigitGen (DiyFp low, DiyFp w, DiyFp high, char **outptr, int *kappa)
static bool DigitGenCounted (DiyFp w, int requested_digits, Vector< char > buffer, int *length, int *kappa)
static bool Grisu3 (double v, char **outptr, int *decimal_exponent)
static bool Grisu3Counted (double v, int requested_digits, Vector< char > buffer, int *length, int *decimal_exponent)
bool FastDtoa (double v, FastDtoaMode mode, int requested_digits, Vector< char > buffer, int *length, int *decimal_point)
static void FillDigits32FixedLength (uint32_t number, int requested_length, Vector< char > buffer, int *length)
static void FillDigits32 (uint32_t number, Vector< char > buffer, int *length)
static void FillDigits64FixedLength (uint64_t number, int requested_length, Vector< char > buffer, int *length)
static void FillDigits64 (uint64_t number, Vector< char > buffer, int *length)
static void DtoaRoundUp (Vector< char > buffer, int *length, int *decimal_point)
static void FillFractionals (uint64_t fractionals, int exponent, int fractional_count, Vector< char > buffer, int *length, int *decimal_point)
static void TrimZeros (Vector< char > buffer, int *length, int *decimal_point)
bool FastFixedDtoa (double v, int fractional_count, Vector< char > buffer, int *length, int *decimal_point)
static Vector< const char > TrimLeadingZeros (Vector< const char > buffer)
static Vector< const char > TrimTrailingZeros (Vector< const char > buffer)
static void TrimToMaxSignificantDigits (Vector< const char > buffer, int exponent, char *significant_buffer, int *significant_exponent)
static uint64_t ReadUint64 (Vector< const char > buffer, int *number_of_read_digits)
static void ReadDiyFp (Vector< const char > buffer, DiyFp *result, int *remaining_decimals)
static bool DoubleStrtod (Vector< const char > trimmed, int exponent, double *result)
static DiyFp AdjustmentPowerOfTen (int exponent)
static bool DiyFpStrtod (Vector< const char > buffer, int exponent, double *result)
static double BignumStrtod (Vector< const char > buffer, int exponent, double guess)
double Strtod (Vector< const char > buffer, int exponent)
template<typename T >
requires constexpr std::floating_point< T > T DegToRad (T deg)
template<typename T >
requires constexpr std::floating_point< T > T RadToDeg (T rad)
template<class T >
requires (std::is_integral_v< T >) inline const expr T ByteSwap(T value)
constexpr uint8_t U8FromNativeEndian (std::span< const uint8_t, 1u > bytes)
constexpr uint16_t U16FromNativeEndian (std::span< const uint8_t, 2u > bytes)
constexpr uint32_t U32FromNativeEndian (std::span< const uint8_t, 4u > bytes)
constexpr uint64_t U64FromNativeEndian (std::span< const uint8_t, 8u > bytes)
constexpr int8_t I8FromNativeEndian (std::span< const uint8_t, 1u > bytes)
constexpr int16_t I16FromNativeEndian (std::span< const uint8_t, 2u > bytes)
constexpr int32_t I32FromNativeEndian (std::span< const uint8_t, 4u > bytes)
constexpr int64_t I64FromNativeEndian (std::span< const uint8_t, 8u > bytes)
constexpr float FloatFromNativeEndian (std::span< const uint8_t, 4u > bytes)
constexpr double DoubleFromNativeEndian (std::span< const uint8_t, 8u > bytes)
constexpr uint8_t U8FromLittleEndian (std::span< const uint8_t, 1u > bytes)
constexpr uint16_t U16FromLittleEndian (std::span< const uint8_t, 2u > bytes)
constexpr uint32_t U32FromLittleEndian (std::span< const uint8_t, 4u > bytes)
constexpr uint64_t U64FromLittleEndian (std::span< const uint8_t, 8u > bytes)
constexpr int8_t I8FromLittleEndian (std::span< const uint8_t, 1u > bytes)
constexpr int16_t I16FromLittleEndian (std::span< const uint8_t, 2u > bytes)
constexpr int32_t I32FromLittleEndian (std::span< const uint8_t, 4u > bytes)
constexpr int64_t I64FromLittleEndian (std::span< const uint8_t, 8u > bytes)
constexpr float FloatFromLittleEndian (std::span< const uint8_t, 4u > bytes)
constexpr double DoubleFromLittleEndian (std::span< const uint8_t, 8u > bytes)
constexpr uint8_t U8FromBigEndian (std::span< const uint8_t, 1u > bytes)
constexpr uint16_t U16FromBigEndian (std::span< const uint8_t, 2u > bytes)
constexpr uint32_t U32FromBigEndian (std::span< const uint8_t, 4u > bytes)
constexpr uint64_t U64FromBigEndian (std::span< const uint8_t, 8u > bytes)
constexpr int8_t I8FromBigEndian (std::span< const uint8_t, 1u > bytes)
constexpr int16_t I16FromBigEndian (std::span< const uint8_t, 2u > bytes)
constexpr int32_t I32FromBigEndian (std::span< const uint8_t, 4u > bytes)
constexpr int64_t I64FromBigEndian (std::span< const uint8_t, 8u > bytes)
constexpr float FloatFromBigEndian (std::span< const uint8_t, 4u > bytes)
constexpr double DoubleFromBigEndian (std::span< const uint8_t, 8u > bytes)
constexpr std::array< uint8_t, 1u > U8ToNativeEndian (uint8_t val)
constexpr std::array< uint8_t, 2u > U16ToNativeEndian (uint16_t val)
constexpr std::array< uint8_t, 4u > U32ToNativeEndian (uint32_t val)
constexpr std::array< uint8_t, 8u > U64ToNativeEndian (uint64_t val)
constexpr std::array< uint8_t, 1u > I8ToNativeEndian (int8_t val)
constexpr std::array< uint8_t, 2u > I16ToNativeEndian (int16_t val)
constexpr std::array< uint8_t, 4u > I32ToNativeEndian (int32_t val)
constexpr std::array< uint8_t, 8u > I64ToNativeEndian (int64_t val)
constexpr std::array< uint8_t, 4u > FloatToNativeEndian (float val)
constexpr std::array< uint8_t, 8u > DoubleToNativeEndian (double val)
constexpr std::array< uint8_t, 1u > U8ToLittleEndian (uint8_t val)
constexpr std::array< uint8_t, 2u > U16ToLittleEndian (uint16_t val)
constexpr std::array< uint8_t, 4u > U32ToLittleEndian (uint32_t val)
constexpr std::array< uint8_t, 8u > U64ToLittleEndian (uint64_t val)
constexpr std::array< uint8_t, 1u > I8ToLittleEndian (int8_t val)
constexpr std::array< uint8_t, 2u > I16ToLittleEndian (int16_t val)
constexpr std::array< uint8_t, 4u > I32ToLittleEndian (int32_t val)
constexpr std::array< uint8_t, 8u > I64ToLittleEndian (int64_t val)
constexpr std::array< uint8_t, 4u > FloatToLittleEndian (float val)
constexpr std::array< uint8_t, 8u > DoubleToLittleEndian (double val)
constexpr std::array< uint8_t, 1u > U8ToBigEndian (uint8_t val)
constexpr std::array< uint8_t, 2u > U16ToBigEndian (uint16_t val)
constexpr std::array< uint8_t, 4u > U32ToBigEndian (uint32_t val)
constexpr std::array< uint8_t, 8u > U64ToBigEndian (uint64_t val)
constexpr std::array< uint8_t, 1u > I8ToBigEndian (int8_t val)
constexpr std::array< uint8_t, 2u > I16ToBigEndian (int16_t val)
constexpr std::array< uint8_t, 4u > I32ToBigEndian (int32_t val)
constexpr std::array< uint8_t, 8u > I64ToBigEndian (int64_t val)
constexpr std::array< uint8_t, 4u > FloatToBigEndian (float val)
constexpr std::array< uint8_t, 8u > DoubleToBigEndian (double val)
template<typename T >
constexpr bool IsApproximatelyEqual (T lhs, T rhs, T tolerance)
template<typename Dst = int, typename Src >
requires (std::integral< Dst > &&std::floating_point< Src >) Dst ClampFloor(Src value)
template<typename T >
constexpr T WrappingAdd (T a, T b)
template<typename T >
constexpr T WrappingSub (T a, T b)
void CallOnceImpl (OnceType *once, std::function< void()> init_func)
void CallOnce (OnceType *once, std::function< void()> init_func)
template<typename... Args>
void CallOnce (OnceType *once, typename FunctionWithArgs< Args... >::type init_func, Args... args) requires(std
template<> int16_t MulWithWraparound (int16_t a, int16_t b)
template<typename signed_type >
signed_type NegateWithWraparound (signed_type a)
template<typename signed_type >
signed_type ShlWithWraparound (signed_type a, signed_type b)
template<typename T >
T Divide (T x, T y)
float Recip (float a)
float RecipSqrt (float a)
STATIC_ASSERT_ENUM (PageAllocator::kNoAccess, base::OS::MemoryPermission::kNoAccess)
STATIC_ASSERT_ENUM (PageAllocator::kReadWrite, base::OS::MemoryPermission::kReadWrite)
STATIC_ASSERT_ENUM (PageAllocator::kReadWriteExecute, base::OS::MemoryPermission::kReadWriteExecute)
STATIC_ASSERT_ENUM (PageAllocator::kReadExecute, base::OS::MemoryPermission::kReadExecute)
STATIC_ASSERT_ENUM (PageAllocator::kNoAccessWillJitLater, base::OS::MemoryPermission::kNoAccessWillJitLater)
void * Malloc (size_t size)
void * Realloc (void *memory, size_t size)
void Free (void *memory)
void * Calloc (size_t count, size_t size)
void * AlignedAlloc (size_t size, size_t alignment)
void AlignedFree (void *ptr)
template<typename T >
AllocationResult< T * > AllocateAtLeast (size_t n)
int64_t get_gmt_offset (const tm &localtm)
static unsigned StringToLong (char *buffer)
double LocalTimeOffset (double time_ms, bool is_utc)
static unsigned StringToLong (char *buffer)
std::vector< OS::SharedLibraryAddress > GetSharedLibraryAddresses (FILE *fp)
int GetProtectionFromMemoryPermission (OS::MemoryPermission access)
void PosixInitializeCommon (AbortMode abort_mode, const char *const gc_fake_mmap)
static void SetThreadName (const char *name)
static void * ThreadEntry (void *arg)
static Thread::LocalStorageKey PthreadKeyToLocalKey (pthread_key_t pthread_key)
static pthread_key_t LocalKeyToPthreadKey (Thread::LocalStorageKey local_key)
void * Allocate (void *address, size_t size, OS::MemoryPermission access)
static void SetThreadName (const char *name)
static void * ThreadEntry (void *arg)
static bool HasConsole ()
static void VPrintHelper (FILE *stream, const char *format, va_list args)
static std::wstring ConvertUtf8StringToUtf16 (const char *str)
DEFINE_LAZY_LEAKY_OBJECT_GETTER (RandomNumberGenerator, GetPlatformRandomNumberGenerator) static LazyMutex rng_mutex
static bool LoadDbgHelpAndTlHelp32 ()
static std::vector< OS::SharedLibraryAddress > LoadSymbols (HANDLE process_handle)
static unsigned int __stdcall ThreadEntry (void *arg)
void EnsureConsoleOutput ()
std::ostream & operator<< (std::ostream &os, const Time &time)
Time operator+ (const TimeDelta &delta, const Time &time)
TimeTicks operator+ (const TimeDelta &delta, const TimeTicks &ticks)
FILE * Fopen (const char *filename, const char *mode)
int Fclose (FILE *stream)
template<typename PointerType , typename PayloadType , int NumPayloadBits>
bool operator== (PointerWithPayload< PointerType, PayloadType, NumPayloadBits > lhs, PointerWithPayload< PointerType, PayloadType, NumPayloadBits > rhs)
FormattedString () -> FormattedString<>
int VSNPrintF (Vector< char > str, const char *format, va_list args)
int SNPrintF (Vector< char > str, const char *format,...)
void StrNCpy (base::Vector< char > dest, const char *src, size_t n)
V8_BASE_EXPORT int PRINTF_FORMAT (2, 0) VSNPrintF(Vector< char > str
V8_BASE_EXPORT int PRINTF_FORMAT (2, 3) SNPrintF(Vector< char > str
int HexValue (uc32 c)
char HexCharOfValue (int value)
template<typename TagType , typename UnderlyingType >
requires requires (std::ostream &stream, const UnderlyingType &value)
std::ostream & operator<< (std::ostream &stream, const StrongAlias< TagType, UnderlyingType > &alias)
template<std::size_t Size, class Function >
constexpr auto make_array (Function f)
template<size_t N, typename Tuple >
constexpr auto tuple_head (Tuple &&tpl)
template<size_t N, typename Tuple >
requires (detail::NIsNotGreaterThanTupleSize< N, Tuple >) const expr auto tuple_drop(Tuple &&tpl)
template<typename Tuple , typename Function >
constexpr void tuple_for_each (Tuple &&tpl, Function &&function)
template<typename Tuple , typename Function >
constexpr void tuple_for_each_with_index (Tuple &&tpl, Function &&function)
template<typename Tuple , typename Function >
constexpr auto tuple_map (Tuple &&tpl, Function &&function)
template<typename TupleV , typename TupleU , typename Function >
constexpr auto tuple_map2 (TupleV &&tplv, TupleU &&tplu, Function &&function)
template<typename T , typename Tuple , typename Function >
constexpr auto tuple_fold (T &&initial, Tuple &&tpl, Function &&function)
static std::vector< uint64_t > ComplementSample (const std::unordered_set< uint64_t > &set, uint64_t max)
template<typename T >
size_t hash_value (base::Vector< T > v)
template<size_t N>
constexpr Vector< const char > StaticCharVector (const char(&array)[N])
Vector< const char > CStrVector (const char *data)
Vector< const uint8_t > OneByteVector (const char *data, size_t length)
Vector< const uint8_t > OneByteVector (const char *data)
template<size_t N>
Vector< const uint8_t > StaticOneByteVector (const char(&array)[N])
template<typename T , size_t N>
constexpr Vector< T > ArrayVector (T(&arr)[N])
template<typename T >
constexpr Vector< T > VectorOf (T *start, size_t size)
template<typename Container >
constexpr auto VectorOf (Container &&c) -> decltype(VectorOf(std::data(c), std::size(c)))
template<typename T >
constexpr Vector< const T > VectorOf (std::initializer_list< T > list)
template<typename T >
OwnedVector< T > OwnedCopyOf (const T *data, size_t size)
template<typename Container >
auto OwnedCopyOf (const Container &c) -> decltype(OwnedCopyOf(std::data(c), std::size(c)))
STATIC_ASSERT_ENUM (PagePermissions::kNoAccess, OS::MemoryPermission::kNoAccess)
STATIC_ASSERT_ENUM (PagePermissions::kReadWrite, OS::MemoryPermission::kReadWrite)
STATIC_ASSERT_ENUM (PagePermissions::kReadWriteExecute, OS::MemoryPermission::kReadWriteExecute)
STATIC_ASSERT_ENUM (PagePermissions::kReadExecute, OS::MemoryPermission::kReadExecute)
bool IsSubset (PagePermissions lhs, PagePermissions rhs)
int8_t charToDigitDecodeForTesting (uint8_t c)
int32_t VLQBase64Decode (const char *start, size_t sz, size_t *pos)
template<typename Function >
void VLQEncodeUnsigned (Function &&process_byte, uint32_t value)
uint32_t VLQConvertToUnsigned (int32_t value)
template<typename Function >
void VLQEncode (Function &&process_byte, int32_t value)
template<typename A >
void VLQEncode (std::vector< uint8_t, A > *data, int32_t value)
template<typename A >
void VLQEncodeUnsigned (std::vector< uint8_t, A > *data, uint32_t value)
template<typename GetNextFunction >
uint32_t VLQDecodeUnsigned (GetNextFunction &&get_next) requires std
int32_t VLQDecode (const uint8_t *data_start, int *index)
size_t hash_value (const i::Float64 &f64)
Variables
AbortMode g_abort_mode = AbortMode::kDefault
template unsigned leading_zeros
template<typename T >
concept Hashable
constexpr const char * kUnimplementedCodeMessage = `unimplemented code`
constexpr const char * kUnreachableCodeMessage = `unreachable code`
LT
static const CachedPower kCachedPowers []
static const int kCachedPowersOffset = 348
static const double kD_1_LOG2_10 = 0.30102999566398114
const int kBase10MaximalLength = 17
static const int kMinimalTargetExponent = -60
static const int kMaximalTargetExponent = -32
static const uint32_t kTen4 = 10000
static const uint32_t kTen5 = 100000
static const uint32_t kTen6 = 1000000
static const uint32_t kTen7 = 10000000
static const uint32_t kTen8 = 100000000
static const uint32_t kTen9 = 1000000000
static const DivMagic div []
const int kFastDtoaMaximalLength = 17
static const int kDoubleSignificandSize = 53
static const int kMaxExactDoubleIntegerDecimalDigits = 15
static const int kMaxUint64DecimalDigits = 19
static const int kMaxDecimalPower = 309
static const int kMinDecimalPower = -324
static const uint64_t kMaxUint64 = 0xFFFF'FFFF'FFFF'FFFF
static const double exact_powers_of_ten []
static const int kExactPowersOfTenSize = arraysize(exact_powers_of_ten)
static const int kMaxSignificantDecimalDigits = 780
template<typename T >
concept IntegralConstantLike
constexpr double kMeanGravityDouble = 9.80665
constexpr float kMeanGravityFloat = 9.80665f
static const pthread_t kNoThread = (pthread_t) 0
static OutputMode output_mode = UNKNOWN
VirtualAlloc2_t VirtualAlloc2 = nullptr
MapViewOfFile3_t MapViewOfFile3 = nullptr
UnmapViewOfFile2_t UnmapViewOfFile2 = nullptr
static const HANDLE kNoThread = INVALID_HANDLE_VALUE
constexpr double kMaxLoadFactorForRandomization = 0.40
constexpr int kMaxRandomizationAttempts = 3
constexpr int kUC16Size = sizeof(uc16)
V8_BASE_EXPORT int const char * format
V8_BASE_EXPORT int const char va_list args
template<typename T , typename TStream = std::ostream>
concept has_output_operator = requires(T t, TStream stream) { stream << t; }
template<typename SearchT , typename... Ts>
constexpr size_t index_of_type_v = index_of_type<SearchT, Ts...>::value
template<typename SearchT , typename... Ts>
constexpr bool has_type_v
static constexpr bool kUnsafeInsertion = true
static LazyMutex entropy_mutex = LAZY_MUTEX_INITIALIZER
static RandomNumberGenerator::EntropySource entropy_source = nullptr
constexpr Address kNullAddress = 0
static constexpr uint32_t kContinueShift = 7
static constexpr uint32_t kContinueBit = 1 << kContinueShift
static constexpr uint32_t kDataMask = kContinueBit - 1
Typedef Documentation
Address
typedef uintptr_t v8::base::Address
Definition at line 13 of file memory.h.
append_tuple_type
template<class Tuple , class T >
using v8::base::append_tuple_type = typedef decltype(std::tuple_cat(std::declval<Tuple>(), std::declval<std::tuple<T> >()))
Definition at line 63 of file template-utils.h.
AsAtomic16
using v8::base::AsAtomic16 = typedef AsAtomicImpl<base::Atomic16>
Definition at line 231 of file atomic-utils.h.
AsAtomic32
using v8::base::AsAtomic32 = typedef AsAtomicImpl<base::Atomic32>
Definition at line 232 of file atomic-utils.h.
AsAtomic8
using v8::base::AsAtomic8 = typedef AsAtomicImpl<base::Atomic8>
Definition at line 230 of file atomic-utils.h.
AsAtomicPointer
using v8::base::AsAtomicPointer = typedef AsAtomicPointerImpl<base::AtomicWord>
Definition at line 265 of file atomic-utils.h.
AsAtomicWord
using v8::base::AsAtomicWord = typedef AsAtomicImpl<base::AtomicWord>
Definition at line 233 of file atomic-utils.h.
Atomic16
using v8::base::Atomic16 = typedef int16_t
Definition at line 58 of file atomicops.h.
Atomic32
using v8::base::Atomic32 = typedef int32_t
Definition at line 59 of file atomicops.h.
Atomic8
using v8::base::Atomic8 = typedef char
Definition at line 57 of file atomicops.h.
AtomicWord
using v8::base::AtomicWord = typedef Atomic32
Definition at line 76 of file atomicops.h.
BitField16
template<class T , int shift, int size>
using v8::base::BitField16 = typedef BitField<T, shift, size, uint16_t>
Definition at line 92 of file bit-field.h.
BitField64
template<class T , int shift, int size>
using v8::base::BitField64 = typedef BitField<T, shift, size, uint64_t>
Definition at line 95 of file bit-field.h.
BitField8
template<class T , int shift, int size>
using v8::base::BitField8 = typedef BitField<T, shift, size, uint8_t>
Definition at line 89 of file bit-field.h.
ContextualClass
template<class T >
using v8::base::ContextualClass = typedef ContextualVariable<T, T>
Definition at line 106 of file contextual.h.
CreateToolhelp32Snapshot
using v8::base::CreateToolhelp32Snapshot = typedef HANDLE(__stdcall*)(DWORD dwFlags, DWORD th32ProcessID)
Definition at line 1523 of file platform-win32.cc.
CustomMatcherHashMap
using v8::base::CustomMatcherHashMap = typedef CustomMatcherTemplateHashMapImpl<DefaultAllocationPolicy>
Definition at line 491 of file hashmap.h.
HashMap
using v8::base::HashMap = typedef PointerTemplateHashMapImpl<DefaultAllocationPolicy>
Definition at line 531 of file hashmap.h.
LazyConditionVariable
using v8::base::LazyConditionVariable = typedef LazyStaticInstance<ConditionVariable, DefaultConstructTrait<ConditionVariable>, ThreadSafeInitOnceTrait>::type
Definition at line 83 of file condition-variable.h.
LazyMutex
using v8::base::LazyMutex = typedef LazyStaticInstance<Mutex, DefaultConstructTrait<Mutex>, ThreadSafeInitOnceTrait>::type
Definition at line 103 of file mutex.h.
LazyRecursiveMutex
using v8::base::LazyRecursiveMutex = typedef LazyStaticInstance<RecursiveMutex, DefaultConstructTrait<RecursiveMutex>, ThreadSafeInitOnceTrait>::type
Definition at line 176 of file mutex.h.
MapViewOfFile3_t
typedef PVOID(__stdcall* v8::base::MapViewOfFile3_t) (HANDLE, HANDLE, PVOID, ULONG64, SIZE_T, ULONG, ULONG, MEM_EXTENDED_PARAMETER *, ULONG)
Definition at line 793 of file platform-win32.cc.
Module32FirstW
using v8::base::Module32FirstW = typedef BOOL(__stdcall*)(HANDLE hSnapshot, LPMODULEENTRY32W lpme)
Definition at line 1525 of file platform-win32.cc.
Module32NextW
using v8::base::Module32NextW = typedef BOOL(__stdcall*)(HANDLE hSnapshot, LPMODULEENTRY32W lpme)
Definition at line 1527 of file platform-win32.cc.
MutexGuard
using v8::base::MutexGuard = typedef LockGuard<Mutex>
Definition at line 219 of file mutex.h.
nth_type_t
template<size_t N, typename... T>
using v8::base::nth_type_t = typedef typename detail::nth_type<N, T...>::type
Definition at line 214 of file template-utils.h.
OnceType
using v8::base::OnceType = typedef std::atomic<uint8_t>
Definition at line 67 of file once.h.
PointerArgFunction
using v8::base::PointerArgFunction = typedef void (*)(void* arg)
Definition at line 80 of file once.h.
prepend_tuple_type
template<class T , class Tuple >
using v8::base::prepend_tuple_type = typedef decltype(std::tuple_cat(std::declval<std::tuple<T> >(), std::declval<Tuple>()))
Definition at line 68 of file template-utils.h.
RecursiveMutexGuard
using v8::base::RecursiveMutexGuard = typedef LockGuard<RecursiveMutex>
Definition at line 220 of file mutex.h.
SizeT
using v8::base::SizeT = typedef StrictNumeric<size_t>
Definition at line 343 of file safe_conversions.h.
StackWalk64
using v8::base::StackWalk64 = typedef BOOL(__stdcall*)(DWORD MachineType, HANDLE hProcess, HANDLE hThread, LPSTACKFRAME64 StackFrame, PVOID ContextRecord, PREAD_PROCESS_MEMORY_ROUTINE64 ReadMemoryRoutine, PFUNCTION_TABLE_ACCESS_ROUTINE64 FunctionTableAccessRoutine, PGET_MODULE_BASE_ROUTINE64 GetModuleBaseRoutine, PTRANSLATE_ADDRESS_ROUTINE64 TranslateAddress)
Definition at line 1501 of file platform-win32.cc.
SymFunctionTableAccess64
using v8::base::SymFunctionTableAccess64 = typedef PVOID(__stdcall*)(HANDLE hProcess, DWORD64 AddrBase)
Definition at line 1515 of file platform-win32.cc.
SymGetLineFromAddr64
using v8::base::SymGetLineFromAddr64 = typedef BOOL(__stdcall*)(IN HANDLE hProcess, IN DWORD64 qwAddr, OUT PDWORD pdwDisplacement, OUT PIMAGEHLP_LINE64 Line64)
Definition at line 1511 of file platform-win32.cc.
SymGetModuleBase64
using v8::base::SymGetModuleBase64 = typedef DWORD64(__stdcall*)(HANDLE hProcess, DWORD64 AddrBase)
Definition at line 1518 of file platform-win32.cc.
SymGetOptions
using v8::base::SymGetOptions = typedef DWORD(__stdcall*)(VOID)
Definition at line 1494 of file platform-win32.cc.
SymGetSearchPath
using v8::base::SymGetSearchPath = typedef BOOL(__stdcall*)(IN HANDLE hProcess, OUT PSTR SearchPath, IN DWORD SearchPathLength)
Definition at line 1496 of file platform-win32.cc.
SymGetSymFromAddr64
using v8::base::SymGetSymFromAddr64 = typedef BOOL(__stdcall*)(IN HANDLE hProcess, IN DWORD64 qwAddr, OUT PDWORD64 pdwDisplacement, OUT PIMAGEHLP_SYMBOL64 Symbol)
Definition at line 1508 of file platform-win32.cc.
SymInitialize
using v8::base::SymInitialize = typedef BOOL(__stdcall*)(IN HANDLE hProcess, IN PSTR UserSearchPath, IN BOOL fInvadeProcess)
Definition at line 1491 of file platform-win32.cc.
SymLoadModule64
using v8::base::SymLoadModule64 = typedef DWORD64(__stdcall*)(IN HANDLE hProcess, IN HANDLE hFile, IN PSTR ImageName, IN PSTR ModuleName, IN DWORD64 BaseOfDll, IN DWORD SizeOfDll)
Definition at line 1498 of file platform-win32.cc.
SymSetOptions
using v8::base::SymSetOptions = typedef DWORD(__stdcall*)(IN DWORD SymOptions)
Definition at line 1495 of file platform-win32.cc.
ThreadedList
template<typename T , typename TLTraits = ThreadedListTraits<T>>
using v8::base::ThreadedList = typedef ThreadedListBase<T, EmptyBase, TLTraits>
Definition at line 373 of file threaded-list.h.
ThreadedListWithUnsafeInsertions
template<typename T , typename TLTraits = ThreadedListTraits<T>>
using v8::base::ThreadedListWithUnsafeInsertions = typedef ThreadedListBase<T, EmptyBase, TLTraits, kUnsafeInsertion>
Definition at line 376 of file threaded-list.h.
uc16
using v8::base::uc16 = typedef uint16_t
Definition at line 18 of file strings.h.
uc32
using v8::base::uc32 = typedef uint32_t
Definition at line 19 of file strings.h.
UnmapViewOfFile2_t
typedef PVOID(__stdcall* v8::base::UnmapViewOfFile2_t) (HANDLE, PVOID, ULONG)
Definition at line 798 of file platform-win32.cc.
VirtualAlloc2_t
typedef PVOID(__stdcall* v8::base::VirtualAlloc2_t) (HANDLE, PVOID, SIZE_T, ULONG, ULONG, MEM_EXTENDED_PARAMETER *, ULONG)
Definition at line 789 of file platform-win32.cc.
Enumeration Type Documentation
anonymous enum
anonymous enum : uint8_t
Enumerator
ONCE_STATE_UNINITIALIZED
ONCE_STATE_EXECUTING_FUNCTION
ONCE_STATE_DONE
Definition at line 74 of file once.h.
     : uint8_t {
  ONCE_STATE_UNINITIALIZED = 0,
  ONCE_STATE_EXECUTING_FUNCTION = 1,
  ONCE_STATE_DONE = 2
};
AbortMode
enum v8::base::AbortMode [strong]
Enumerator
kExitWithSuccessAndIgnoreDcheckFailures
kExitWithFailureAndIgnoreDcheckFailures
kImmediateCrash
kDefault
Definition at line 16 of file abort-mode.h.
                     {
  // Used for example for fuzzing when controlled crashes are harmless, such
  // as for example for the sandbox. With this:
  // - DCHECKs are turned into No-ops and as such V8 is allowed to continue
  // execution. This way, the fuzzer can progress past them.
  // - CHECKs, FATAL, etc. are turned into regular exits, which allows fuzzers
  // to ignore them, as they are harmless in this context.
  // - The exit code will either be zero (signaling success) or non-zero
  // (signaling failure). The former is for example used in tests in which a
  // controlled crash counts as success (for example in sandbox regression
  // tests), the latter is typically used for fuzzing where samples that exit
  // in this way should be discarded and not mutated further.
  kExitWithSuccessAndIgnoreDcheckFailures,
  kExitWithFailureAndIgnoreDcheckFailures,
  // DCHECKs, CHECKs, etc. use IMMEDIATE_CRASH() to signal abnormal program
  // termination. See the --hard-abort flag for more details.
  kImmediateCrash,
  // CHECKs, DCHECKs, etc. use abort() to signal abnormal program termination.
  kDefault
};
BignumDtoaMode
enum v8::base::BignumDtoaMode
Enumerator
BIGNUM_DTOA_SHORTEST
BIGNUM_DTOA_FIXED
BIGNUM_DTOA_PRECISION
Definition at line 13 of file bignum-dtoa.h.
                    {
  // Return the shortest correct representation.
  // For example the output of 0.299999999999999988897 is (the less accurate but
  // correct) 0.3.
  BIGNUM_DTOA_SHORTEST,
  // Return a fixed number of digits after the decimal point.
  // For instance fixed(0.1, 4) becomes 0.1000
  // If the input number is big, the output will be big.
  BIGNUM_DTOA_FIXED,
  // Return a fixed number of digits, no matter what the exponent is.
  BIGNUM_DTOA_PRECISION
};
DtoaMode
enum v8::base::DtoaMode
Enumerator
DTOA_SHORTEST
DTOA_FIXED
DTOA_PRECISION
Definition at line 13 of file dtoa.h.
              {
  // Return the shortest correct representation.
  // For example the output of 0.299999999999999988897 is (the less accurate but
  // correct) 0.3.
  DTOA_SHORTEST,
  // Return a fixed number of digits after the decimal point.
  // For instance fixed(0.1, 4) becomes 0.1000
  // If the input number is big, the output will be big.
  DTOA_FIXED,
  // Return a fixed number of digits, no matter what the exponent is.
  DTOA_PRECISION
};
FastDtoaMode
enum v8::base::FastDtoaMode
Enumerator
FAST_DTOA_SHORTEST
FAST_DTOA_PRECISION
Definition at line 13 of file fast-dtoa.h.
                  {
  // Computes the shortest representation of the given input. The returned
  // result will be the most accurate number of this length. Longer
  // representations might be more accurate.
  FAST_DTOA_SHORTEST,
  // Computes a representation where the precision (number of digits) is
  // given as input. The precision is independent of the decimal point.
  FAST_DTOA_PRECISION
};
OOMType
enum v8::base::OOMType [strong]
Enumerator
kJavaScript
kProcess
Definition at line 92 of file logging.h.
                   {
  // We ran out of memory in the JavaScript heap.
  kJavaScript,
  // The process ran out of memory.
  kProcess,
};
OutputMode
enum v8::base::OutputMode
Enumerator
UNKNOWN
CONSOLE
ODS
Definition at line 571 of file platform-win32.cc.
                {
  UNKNOWN, // Output method has not yet been determined.
  CONSOLE, // Output is written to stdout.
  ODS // Output is written to debug facility.
};
PageFreeingMode
enum v8::base::PageFreeingMode [strong]
Enumerator
kMakeInaccessible
kDiscard
Definition at line 31 of file bounded-page-allocator.h.
                           {
  // Pages are freed/released by setting permissions to kNoAccess. This is the
  // preferred mode when current platform/configuration allows any page
  // permissions reconfiguration.
  kMakeInaccessible,
  // Pages are freed/released by using DiscardSystemPages of the underlying
  // page allocator. This mode should be used for the cases when page permission
  // reconfiguration is not allowed. In particular, on MacOS on ARM64 ("Apple
  // M1"/Apple Silicon) it's not allowed to reconfigure RWX pages to anything
  // else.
  // This mode is not compatible with kAllocatedPagesMustBeZeroInitialized
  // page initialization mode.
  kDiscard,
};
PageInitializationMode
enum v8::base::PageInitializationMode [strong]
Enumerator
kAllocatedPagesMustBeZeroInitialized
kAllocatedPagesCanBeUninitialized
kRecommitOnly
Definition at line 16 of file bounded-page-allocator.h.
                                  {
  // The contents of allocated pages must be zero initialized. This causes any
  // committed pages to be decommitted during FreePages and ReleasePages.
  kAllocatedPagesMustBeZeroInitialized,
  // Allocated pages do not have to be be zero initialized and can contain old
  // data. This is slightly faster as comitted pages are not decommitted
  // during FreePages and ReleasePages, but only made inaccessible.
  kAllocatedPagesCanBeUninitialized,
  // Assume pages are in discarded state and already have the right page
  // permissions. Using this mode requires PageFreeingMode::kDiscard.
  kRecommitOnly,
};
Function Documentation
Acquire_CompareAndSwap()
Atomic32 v8::base::Acquire_CompareAndSwap (volatile Atomic32 * ptr, Atomic32 old_value, Atomic32 new_value) [inline]
Definition at line 147 of file atomicops.h.
                                                                               {
  atomic_compare_exchange_strong_explicit(
      helper::to_std_atomic(ptr), &old_value, new_value,
      std::memory_order_acquire, std::memory_order_acquire);
  return old_value;
}
References v8::base::helper::to_std_atomic().
Acquire_Load() [1/2]
Atomic32 v8::base::Acquire_Load (volatile const Atomic32 * ptr) [inline]
Definition at line 254 of file atomicops.h.
                                                           {
  return std::atomic_load_explicit(helper::to_std_atomic_const(ptr),
                                   std::memory_order_acquire);
}
References v8::base::helper::to_std_atomic_const().
Acquire_Load() [2/2]
Atomic8 v8::base::Acquire_Load (volatile const Atomic8 * ptr) [inline]
Definition at line 249 of file atomicops.h.
                                                         {
  return std::atomic_load_explicit(helper::to_std_atomic_const(ptr),
                                   std::memory_order_acquire);
}
References v8::base::helper::to_std_atomic_const().
Referenced by v8::base::AsAtomicImpl< TAtomicStorageType >::Acquire_Load(), v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Acquire_Load(), v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Acquire_Load_No_Unpack(), v8::platform::tracing::TracingController::GetCategoryGroupEnabled(), v8::internal::Profiler::Insert(), v8::internal::SamplingCircularQueue< T, Length >::Peek(), v8::internal::JSObject::RawInobjectPropertyAt(), v8::internal::TrustedObject::ReadProtectedPointerField(), v8::internal::SamplingCircularQueue< v8::internal::TickSampleEventRecord, kTickSampleQueueLength >::Remove(), v8::internal::Debug::SetTerminateOnResume(), v8::platform::tracing::TracingController::UpdateCategoryGroupEnabledFlags(), and v8::base::AtomicValue< T >::Value().
AcquireRelease_CompareAndSwap()
Atomic32 v8::base::AcquireRelease_CompareAndSwap (volatile Atomic32 * ptr, Atomic32 old_value, Atomic32 new_value) [inline]
Definition at line 172 of file atomicops.h.
                                                                  {
  atomic_compare_exchange_strong_explicit(
      helper::to_std_atomic(ptr), &old_value, new_value,
      std::memory_order_acq_rel, std::memory_order_acquire);
  return old_value;
}
References v8::base::helper::to_std_atomic().
Referenced by v8::base::AsAtomicImpl< TAtomicStorageType >::AcquireRelease_CompareAndSwap(), and v8::internal::DescriptorArrayMarkingState::SwapState().
AddressRegionOf() [1/2]
template<typename Container >
auto v8::base::AddressRegionOf (Container && c) -> decltype(AddressRegionOf(c.data(), c.size())) [inline]
Definition at line 83 of file address-region.h.
                                                     {
  return AddressRegionOf(c.data(), c.size());
}
References AddressRegionOf().
AddressRegionOf() [2/2]
template<typename T >
AddressRegion v8::base::AddressRegionOf (T * ptr, size_t size) [inline]
Definition at line 75 of file address-region.h.
                                                          {
  return AddressRegion{reinterpret_cast<AddressRegion::Address>(ptr),
                       sizeof(T) * size};
}
References size().
Referenced by v8::internal::wasm::NativeModule::AddCode(), v8::internal::wasm::NativeModule::AddCodeForTesting(), v8::internal::wasm::NativeModule::AddCompiledCode(), AddressRegionOf(), and v8::internal::wasm::NativeModule::AllocateForDeserializedCode().
AdjustmentPowerOfTen()
static DiyFp v8::base::AdjustmentPowerOfTen (int exponent) [static]
Definition at line 205 of file strtod.cc.
                                                {
  DCHECK_LT(0, exponent);
  DCHECK_LT(exponent, PowersOfTenCache::kDecimalExponentDistance);
  // Simply hardcode the remaining powers for the given decimal exponent
  // distance.
  DCHECK_EQ(PowersOfTenCache::kDecimalExponentDistance, 8);
  switch (exponent) {
    case 1:
      return DiyFp(0xA000'0000'0000'0000, -60);
    case 2:
      return DiyFp(0xC800'0000'0000'0000, -57);
    case 3:
      return DiyFp(0xFA00'0000'0000'0000, -54);
    case 4:
      return DiyFp(0x9C40'0000'0000'0000, -50);
    case 5:
      return DiyFp(0xC350'0000'0000'0000, -47);
    case 6:
      return DiyFp(0xF424'0000'0000'0000, -44);
    case 7:
      return DiyFp(0x9896'8000'0000'0000, -40);
    default:
      UNREACHABLE();
  }
}
References DCHECK_EQ, DCHECK_LT, v8::base::PowersOfTenCache::kDecimalExponentDistance, and UNREACHABLE.
Referenced by DiyFpStrtod().
AlignedAlloc()
void* v8::base::AlignedAlloc (size_t size, size_t alignment) [inline]
Definition at line 84 of file memory.h.
                                                         {
  DCHECK_LE(alignof(void*), alignment);
  DCHECK(base::bits::IsPowerOfTwo(alignment));
#if V8_OS_WIN
  return _aligned_malloc(size, alignment);
#elif V8_LIBC_BIONIC
  // posix_memalign is not exposed in some Android versions, so we fall back to
  // memalign. See http://code.google.com/p/android/issues/detail?id=35391.
  return memalign(alignment, size);
#elif V8_OS_ZOS
  return __aligned_malloc(size, alignment);
#else // POSIX
  void* ptr;
  if (posix_memalign(&ptr, alignment, size)) ptr = nullptr;
  return ptr;
#endif // POSIX
}
References DCHECK, DCHECK_LE, v8::base::bits::IsPowerOfTwo(), and size().
Referenced by v8::internal::AlignedAllocWithRetry(), v8::internal::Isolate::Allocate(), and heap::base::BasicSlotSet< SlotGranularity >::Allocate().
AlignedFree()
void v8::base::AlignedFree (void * ptr) [inline]
Definition at line 102 of file memory.h.
                                   {
#if V8_OS_WIN
  _aligned_free(ptr);
#elif V8_OS_ZOS
  __aligned_free(ptr);
#else
  // Using regular Free() is not correct in general. For most platforms,
  // including V8_LIBC_BIONIC, it is though.
  base::Free(ptr);
#endif
}
References Free().
Referenced by v8::internal::AlignedFree(), heap::base::BasicSlotSet< SlotGranularity >::Delete(), and v8::internal::Isolate::Free().
all_equal() [1/2]
template<typename C >
bool v8::base::all_equal (const C & container) [inline]
Definition at line 121 of file container-utils.h.
                                          {
  if (std::size(container) <= 1) return true;
  auto b = std::begin(container);
  const auto& value = *b;
  return std::all_of(++b, std::end(container),
                     [&](const auto& v) { return v == value; });
}
References all_of(), v8::internal::compiler::begin(), v8::internal::compiler::end(), size(), and v8::internal::value.
Referenced by v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::BeginBlock(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::BeginBlock(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), and v8::internal::compiler::turboshaft::LabelBase< loop, Ts >::RecordValuesImpl().
all_equal() [2/2]
template<typename C , typename T >
bool v8::base::all_equal (const C & container, const T & value) [inline]
Definition at line 132 of file container-utils.h.
                                                          {
  return std::all_of(std::begin(container), std::end(container),
                     [&](const auto& v) { return v == value; });
}
References all_of(), v8::internal::compiler::begin(), v8::internal::compiler::end(), and v8::internal::value.
all_of() [1/2]
template<typename C >
bool v8::base::all_of (const C & container) [inline]
Definition at line 85 of file container-utils.h.
                                       {
  return std::all_of(
      std::begin(container), std::end(container),
      [](const auto& value) { return static_cast<bool>(value); });
}
References v8::internal::compiler::begin(), v8::internal::compiler::end(), and v8::internal::value.
Referenced by all_equal(), and all_of().
all_of() [2/2]
template<typename C , typename P >
bool v8::base::all_of (const C & container, const P & predicate) [inline]
Definition at line 81 of file container-utils.h.
                                                           {
  return std::all_of(std::begin(container), std::end(container), predicate);
}
References all_of(), v8::internal::compiler::begin(), and v8::internal::compiler::end().
Referenced by v8::internal::wasm::SimdSwizzle::AllInRangeOrTopBitSet(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::AllOfInstanceTypesUnsafe(), v8::internal::compiler::MapInference::AllOfInstanceTypesUnsafe(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::BeginBlock(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::BeginBlock(), v8::internal::maglev::MaglevGraphBuilder::BuildTestUndetectable(), v8::internal::torque::CfgAssembler::CfgIsComplete(), v8::internal::SparseBitVector::Segment::empty(), cppgc::internal::Sweeper::SweeperImpl::FinishIfOutOfWork(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::FromElements(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateStructNewInitExpr(), v8::internal::anonymous_namespace{scavenger.cc}::ObjectPinningVisitorBase< ConcreteVisitor >::HandleHeapObject(), v8::internal::interpreter::BytecodeLabels::is_bound(), cppgc::internal::FreeList::IsEmpty(), v8::internal::BitVector::IsEmpty(), v8::internal::anonymous_namespace{asm-scanner.cc}::IsValidImplicitOctal(), v8::internal::compiler::ArrayBufferViewAccessBuilder::maybe_rab_gsab(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::new_object(), v8::internal::Sweeper::LocalSweeper::ParallelSweepSpace(), v8::internal::wasm::LiftoffAssembler::PrepareCall(), v8::internal::compiler::turboshaft::WasmShuffleAnalyzer::ProcessShuffleOfShuffle(), v8::internal::compiler::MapInference::RelyOnMapsHelper(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::S128Const(), v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::SetupSimd256ImmediateInRegister(), cppgc::internal::Sweeper::SweeperImpl::SynchronizeAndFinalizeConcurrentAndIncrementalSweeping(), v8::internal::maglev::MaglevGraphBuilder::TryBuildElementAccessOnString(), v8::internal::maglev::MaglevGraphBuilder::TryBuildNamedAccess(), v8::internal::compiler::ArrayBufferViewAccessBuilder::TryComputeStaticElementShift(), v8::internal::compiler::ArrayBufferViewAccessBuilder::TryComputeStaticElementSize(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryMatchHeapObject(), v8::internal::anonymous_namespace{scavenger.cc}::YoungGenerationConservativeStackVisitor::YoungGenerationConservativeStackVisitor(), and v8::internal::anonymous_namespace{scavenger.cc}::YoungGenerationConservativeStackVisitor::~YoungGenerationConservativeStackVisitor().
Allocate()
void* v8::base::Allocate (void * address, size_t size, OS::MemoryPermission access)
Definition at line 125 of file platform-starboard.cc.
                                                                      {
  int prot_flags;
  switch (access) {
    case OS::MemoryPermission::kNoAccess:
      prot_flags = PROT_NONE;
      break;
    case OS::MemoryPermission::kReadWrite:
      prot_flags = PROT_READ | PROT_WRITE;
      break;
    default:
      SB_LOG(ERROR) << "The requested memory allocation access is not"
                       " implemented for Starboard: "
                    << static_cast<int>(access);
      return nullptr;
  }
  void* result = mmap(nullptr, size, prot_flags, MAP_PRIVATE | MAP_ANON, -1, 0);
  if (result == MAP_FAILED) {
    return nullptr;
  }
  return result;
}
References v8::base::OS::kNoAccess, v8::base::OS::kReadWrite, v8::base::internal::result, and size().
Referenced by v8::base::OS::AllocateShared().
AllocateAtLeast()
template<typename T >
AllocationResult<T*> v8::base::AllocateAtLeast (size_t n)
Definition at line 144 of file memory.h.
                                                            {
  const size_t min_wanted_size = n * sizeof(T);
  auto* memory = static_cast<T*>(Malloc(min_wanted_size));
#if !V8_HAS_MALLOC_USABLE_SIZE
  return {memory, min_wanted_size};
#else // V8_HAS_MALLOC_USABLE_SIZE
  const size_t usable_size = MallocUsableSize(memory);
#if V8_USE_UNDEFINED_BEHAVIOR_SANITIZER
  if (memory == nullptr)
    return {nullptr, 0};
  // UBSan (specifically, -fsanitize=bounds) assumes that any access outside
  // of the requested size for malloc is UB and will trap in ud2 instructions.
  // This can be worked around by using `Realloc()` on the specific memory
  // region.
  if (usable_size != min_wanted_size) {
    memory = static_cast<T*>(Realloc(memory, usable_size));
  }
#endif // V8_USE_UNDEFINED_BEHAVIOR_SANITIZER
  return {memory, usable_size};
#endif // V8_HAS_MALLOC_USABLE_SIZE
}
References Malloc(), Realloc(), and T.
any_of() [1/2]
template<typename C >
bool v8::base::any_of (const C & container) [inline]
Definition at line 97 of file container-utils.h.
                                       {
  return std::any_of(
      std::begin(container), std::end(container),
      [](const auto& value) { return static_cast<bool>(value); });
}
References v8::internal::compiler::begin(), v8::internal::compiler::end(), and v8::internal::value.
Referenced by any_of().
any_of() [2/2]
template<typename C , typename P >
bool v8::base::any_of (const C & container, const P & predicate) [inline]
Definition at line 93 of file container-utils.h.
                                                           {
  return std::any_of(std::begin(container), std::end(container), predicate);
}
References any_of(), v8::internal::compiler::begin(), and v8::internal::compiler::end().
Referenced by v8::internal::compiler::AnyMapIsHeapNumber(), v8::internal::compiler::MapInference::AnyOfInstanceTypesUnsafe(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::BranchAndBind(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallRuntime_BigIntUnaryOp(), v8::internal::torque::anonymous_namespace{utils.cc}::ContainsUpperCase(), v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOp::ConvertUntaggedToJSPrimitiveOp(), v8::internal::wasm::AsyncCompileJob::CreateNativeModule(), cppgc::internal::Sweeper::SweeperImpl::FinishIfOutOfWork(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::HasCatchAll(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::InitializeIndexMaps(), v8::internal::compiler::turboshaft::ChangeOp::IsReversible(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::RelocatableConstant(), v8::internal::wasm::WasmEngine::RemoveIsolate(), v8::internal::torque::ReportAllUnusedMacros(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ReturnImpl(), v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::Run(), v8::internal::CpuProfile::StreamPendingTraceEvents(), v8::internal::maglev::MaglevGraphBuilder::TryReduceArrayIteratingBuiltin(), v8::internal::MaglevSafepointTableBuilder::UpdateDeoptimizationInfo(), v8::internal::SafepointTableBuilder::UpdateDeoptimizationInfo(), v8::internal::compiler::turboshaft::FloatBinopOp::Validate(), v8::internal::compiler::turboshaft::ComparisonOp::Validate(), v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOp::Validate(), v8::internal::compiler::turboshaft::ValueNeedsWriteBarrier(), v8::internal::compiler::WasmGraphBuilder::WasmGraphBuilder(), and v8::internal::wasm::WasmModuleBuilder::WriteTo().
ArrayVector()
template<typename T , size_t N>
constexpr Vector<T> v8::base::ArrayVector (T(&) arr[N]) [inline], [constexpr]
Definition at line 353 of file vector.h.
                                                    {
  return {arr, N};
}
References v8::internal::N.
Referenced by v8::internal::StringStream::Add(), v8::internal::IncrementalStringBuilder::AppendInt(), v8::internal::wasm::AsyncStreamingDecoder::DecodeVarInt32::buffer(), v8::internal::wasm::AsyncStreamingDecoder::DecodeModuleHeader::buffer(), v8::internal::BUILTIN(), v8::internal::V8HeapExplorer::ExtractNumberReference(), v8::internal::Flags(), v8::internal::wasm::DebugInfoImpl::FloodWithBreakpoints(), v8_inspector::String16::fromDouble(), v8_inspector::String16::fromInteger(), v8::internal::wasm::GenerateLiftoffDebugSideTable(), v8::internal::OptimizedCompilationInfo::GetDebugName(), v8::internal::Parser::GetNumberAsSymbol(), v8::internal::anonymous_namespace{builtins-regexp.cc}::RegExpEscapeImpl(), v8::internal::compiler::WasmGraphBuilder::Return(), v8::internal::RUNTIME_FUNCTION(), v8::internal::JsonStringifier::SerializeString_(), and v8::internal::JsonStringifier::SerializeStringUnchecked_().
AsAtomicPtr()
template<typename T >
const std::atomic<T>* v8::base::AsAtomicPtr (const T * t) [inline]
Definition at line 297 of file atomic-utils.h.
                                                      {
  static_assert(sizeof(T) == sizeof(std::atomic<T>));
  static_assert(alignof(T) >= alignof(std::atomic<T>));
  return reinterpret_cast<const std::atomic<T>*>(t);
}
Referenced by v8::internal::JSAtomicsMutex::AtomicOwnerThreadIdPtr(), v8::internal::JSSynchronizationPrimitive::AtomicStatePtr(), v8::internal::anonymous_namespace{sweeper.cc}::AtomicZapBlock(), cppgc::internal::HeapObjectHeader::HeapObjectHeader(), cppgc::internal::ObjectStartBitmap::load(), cppgc::internal::HeapObjectHeader::LoadEncoded(), v8::internal::StatsCounter::SetupPtrFromStatsTable(), cppgc::internal::ObjectStartBitmap::store(), cppgc::internal::HeapObjectHeader::StoreEncoded(), v8::internal::Sweeper::SweepEmptyNewSpacePage(), cppgc::internal::BasePage::SynchronizedLoad(), cppgc::internal::BasePage::SynchronizedStore(), and cppgc::internal::HeapObjectHeader::TryMarkAtomic().
ASSERT_TRIVIALLY_COPYABLE()
v8::base::ASSERT_TRIVIALLY_COPYABLE (AddressRegion)
Referenced by ReadUnalignedValue(), and WriteUnalignedValue().
BiggestPowerTen()
static void v8::base::BiggestPowerTen (uint32_t number, int number_bits, uint32_t * power, unsigned * exponent) [inline], [static]
Definition at line 256 of file fast-dtoa.cc.
                                                                        {
  switch (number_bits) {
    case 32:
    case 31:
    case 30:
      if (kTen9 <= number) {
        *power = kTen9;
        *exponent = 9;
        break;
      }
      [[fallthrough]];
    case 29:
    case 28:
    case 27:
      if (kTen8 <= number) {
        *power = kTen8;
        *exponent = 8;
        break;
      }
      [[fallthrough]];
    case 26:
    case 25:
    case 24:
      if (kTen7 <= number) {
        *power = kTen7;
        *exponent = 7;
        break;
      }
      [[fallthrough]];
    case 23:
    case 22:
    case 21:
    case 20:
      if (kTen6 <= number) {
        *power = kTen6;
        *exponent = 6;
        break;
      }
      [[fallthrough]];
    case 19:
    case 18:
    case 17:
      if (kTen5 <= number) {
        *power = kTen5;
        *exponent = 5;
        break;
      }
      [[fallthrough]];
    case 16:
    case 15:
    case 14:
      if (kTen4 <= number) {
        *power = kTen4;
        *exponent = 4;
        break;
      }
      [[fallthrough]];
    case 13:
    case 12:
    case 11:
    case 10:
      if (1000 <= number) {
        *power = 1000;
        *exponent = 3;
        break;
      }
      [[fallthrough]];
    case 9:
    case 8:
    case 7:
      if (100 <= number) {
        *power = 100;
        *exponent = 2;
        break;
      }
      [[fallthrough]];
    case 6:
    case 5:
    case 4:
      if (10 <= number) {
        *power = 10;
        *exponent = 1;
        break;
      }
      [[fallthrough]];
    case 3:
    case 2:
    case 1:
      if (1 <= number) {
        *power = 1;
        *exponent = 0;
        break;
      }
      [[fallthrough]];
    case 0:
      *power = 0;
      *exponent = -1;
      break;
    default:
      // Following assignments are here to silence compiler warnings.
      *power = 0;
      *exponent = 0;
      UNREACHABLE();
  }
}
References kTen4, kTen5, kTen6, kTen7, kTen8, kTen9, and UNREACHABLE.
Referenced by DigitGen(), and DigitGenCounted().
BignumDtoa()
V8_BASE_EXPORT void v8::base::BignumDtoa (double v, BignumDtoaMode mode, int requested_digits, Vector< char > buffer, int * length, int * decimal_point)
Definition at line 61 of file bignum-dtoa.cc.
                                                                      {
  DCHECK_GT(v, 0);
  DCHECK(!Double(v).IsSpecial());
  uint64_t significand = Double(v).Significand();
  bool is_even = (significand & 1) == 0;
  int exponent = Double(v).Exponent();
  int normalized_exponent = NormalizedExponent(significand, exponent);
  // estimated_power might be too low by 1.
  int estimated_power = EstimatePower(normalized_exponent);
  // Shortcut for Fixed.
  // The requested digits correspond to the digits after the point. If the
  // number is much too small, then there is no need in trying to get any
  // digits.
  if (mode == BIGNUM_DTOA_FIXED && -estimated_power - 1 > requested_digits) {
    buffer[0] = '\0';
    *length = 0;
    // Set decimal-point to -requested_digits. This is what Gay does.
    // Note that it should not have any effect anyways since the string is
    // empty.
    *decimal_point = -requested_digits;
    return;
  }
  Bignum numerator;
  Bignum denominator;
  Bignum delta_minus;
  Bignum delta_plus;
  // Make sure the bignum can grow large enough. The smallest double equals
  // 4e-324. In this case the denominator needs fewer than 324*4 binary digits.
  // The maximum double is 1.7976931348623157e308 which needs fewer than
  // 308*4 binary digits.
  DCHECK_GE(Bignum::kMaxSignificantBits, 324 * 4);
  bool need_boundary_deltas = (mode == BIGNUM_DTOA_SHORTEST);
  InitialScaledStartValues(v, estimated_power, need_boundary_deltas, &numerator,
                           &denominator, &delta_minus, &delta_plus);
  // We now have v = (numerator / denominator) * 10^estimated_power.
  FixupMultiply10(estimated_power, is_even, decimal_point, &numerator,
                  &denominator, &delta_minus, &delta_plus);
  // We now have v = (numerator / denominator) * 10^(decimal_point-1), and
  // 1 <= (numerator + delta_plus) / denominator < 10
  switch (mode) {
    case BIGNUM_DTOA_SHORTEST:
      GenerateShortestDigits(&numerator, &denominator, &delta_minus,
                             &delta_plus, is_even, buffer, length);
      break;
    case BIGNUM_DTOA_FIXED:
      BignumToFixed(requested_digits, decimal_point, &numerator, &denominator,
                    buffer, length);
      break;
    case BIGNUM_DTOA_PRECISION:
      GenerateCountedDigits(requested_digits, decimal_point, &numerator,
                            &denominator, buffer, length);
      break;
    default:
      UNREACHABLE();
  }
  buffer[*length] = '\0';
}
References BIGNUM_DTOA_FIXED, BIGNUM_DTOA_PRECISION, BIGNUM_DTOA_SHORTEST, BignumToFixed(), DCHECK, DCHECK_GE, DCHECK_GT, EstimatePower(), v8::base::Double::Exponent(), FixupMultiply10(), GenerateCountedDigits(), GenerateShortestDigits(), InitialScaledStartValues(), v8::base::Bignum::kMaxSignificantBits, v8::internal::length, mode(), NormalizedExponent(), v8::base::Double::Significand(), and UNREACHABLE.
Referenced by DoubleToAscii().
BignumStrtod()
static double v8::base::BignumStrtod (Vector< const char > buffer, int exponent, double guess) [static]
Definition at line 348 of file strtod.cc.
                                         {
  if (guess == std::numeric_limits<double>::infinity()) {
    return guess;
  }
  DiyFp upper_boundary = Double(guess).UpperBoundary();
  DCHECK(buffer.length() + exponent <= kMaxDecimalPower + 1);
  DCHECK_GT(buffer.length() + exponent, kMinDecimalPower);
  DCHECK_LE(buffer.length(), kMaxSignificantDecimalDigits);
  // Make sure that the Bignum will be able to hold all our numbers.
  // Our Bignum implementation has a separate field for exponents. Shifts will
  // consume at most one bigit (< 64 bits).
  // ln(10) == 3.3219...
  DCHECK_LT((kMaxDecimalPower + 1) * 333 / 100, Bignum::kMaxSignificantBits);
  Bignum input;
  Bignum boundary;
  input.AssignDecimalString(buffer);
  boundary.AssignUInt64(upper_boundary.f());
  if (exponent >= 0) {
    input.MultiplyByPowerOfTen(exponent);
  } else {
    boundary.MultiplyByPowerOfTen(-exponent);
  }
  if (upper_boundary.e() > 0) {
    boundary.ShiftLeft(upper_boundary.e());
  } else {
    input.ShiftLeft(-upper_boundary.e());
  }
  int comparison = Bignum::Compare(input, boundary);
  if (comparison < 0) {
    return guess;
  } else if (comparison > 0) {
    return Double(guess).NextDouble();
  } else if ((Double(guess).Significand() & 1) == 0) {
    // Round towards even.
    return guess;
  } else {
    return Double(guess).NextDouble();
  }
}
References v8::base::Bignum::AssignDecimalString(), v8::base::Bignum::AssignUInt64(), v8::base::Bignum::Compare(), DCHECK, DCHECK_GT, DCHECK_LE, DCHECK_LT, v8::base::DiyFp::e(), v8::base::DiyFp::f(), kMaxDecimalPower, v8::base::Bignum::kMaxSignificantBits, kMaxSignificantDecimalDigits, kMinDecimalPower, v8::base::Vector< T >::length(), v8::base::Bignum::MultiplyByPowerOfTen(), v8::base::Double::NextDouble(), v8::base::Bignum::ShiftLeft(), and v8::base::Double::UpperBoundary().
Referenced by Strtod().
BignumToFixed()
static void v8::base::BignumToFixed (int requested_digits, int * decimal_point, Bignum * numerator, Bignum * denominator, Vector< char > buffer, int * length) [static]
Definition at line 273 of file bignum-dtoa.cc.
                                                             {
  // Note that we have to look at more than just the requested_digits, since
  // a number could be rounded up. Example: v=0.5 with requested_digits=0.
  // Even though the power of v equals 0 we can't just stop here.
  if (-(*decimal_point) > requested_digits) {
    // The number is definitively too small.
    // Ex: 0.001 with requested_digits == 1.
    // Set decimal-point to -requested_digits. This is what Gay does.
    // Note that it should not have any effect anyways since the string is
    // empty.
    *decimal_point = -requested_digits;
    *length = 0;
    return;
  } else if (-(*decimal_point) == requested_digits) {
    // We only need to verify if the number rounds down or up.
    // Ex: 0.04 and 0.06 with requested_digits == 1.
    DCHECK(*decimal_point == -requested_digits);
    // Initially the fraction lies in range (1, 10]. Multiply the denominator
    // by 10 so that we can compare more easily.
    denominator->Times10();
    if (Bignum::PlusCompare(*numerator, *numerator, *denominator) >= 0) {
      // If the fraction is >= 0.5 then we have to include the rounded
      // digit.
      buffer[0] = '1';
      *length = 1;
      (*decimal_point)++;
    } else {
      // Note that we caught most of similar cases earlier.
      *length = 0;
    }
    return;
  } else {
    // The requested digits correspond to the digits after the point.
    // The variable 'needed_digits' includes the digits before the point.
    int needed_digits = (*decimal_point) + requested_digits;
    GenerateCountedDigits(needed_digits, decimal_point, numerator, denominator,
                          buffer, length);
  }
}
References DCHECK, GenerateCountedDigits(), v8::internal::length, v8::base::Bignum::PlusCompare(), and v8::base::Bignum::Times10().
Referenced by BignumDtoa().
bit_cast()
template<class Dest , class Source >
Dest v8::base::bit_cast (Source const & source) [inline]
Definition at line 95 of file macros.h.
                                              {
  static_assert(!std::is_pointer_v<Source>,
                "bit_cast must not be used on pointer types");
  static_assert(!std::is_pointer_v<Dest>,
                "bit_cast must not be used on pointer types");
  static_assert(!std::is_reference_v<Dest>,
                "bit_cast must not be used on reference types");
  static_assert(
      sizeof(Dest) == sizeof(Source),
      "bit_cast requires source and destination types to be the same size");
  static_assert(std::is_trivially_copyable_v<Source>,
                "bit_cast requires the source type to be trivially copyable");
  static_assert(
      std::is_trivially_copyable_v<Dest>,
      "bit_cast requires the destination type to be trivially copyable");
#if V8_HAS_BUILTIN_BIT_CAST
  return __builtin_bit_cast(Dest, source);
#else
  Dest dest;
  memcpy(&dest, &source, sizeof(dest));
  return dest;
#endif
}
BitSize()
template<typename S >
static int v8::base::BitSize (S value) [static]
Definition at line 20 of file bignum.cc.
                            {
  return 8 * sizeof(value);
}
References v8::internal::value.
Referenced by v8::base::Bignum::AssignUInt16().
Calloc()
void* v8::base::Calloc (size_t count, size_t size) [inline]
Definition at line 71 of file memory.h.
                                               {
#if V8_OS_STARBOARD
  return SbMemoryCalloc(count, size);
#elif V8_OS_AIX && _LINUX_SOURCE_COMPAT
  // Work around for GCC bug on AIX, see Malloc().
  return __linux_calloc(count, size);
#else
  return calloc(count, size);
#endif
}
References size().
Referenced by v8::anonymous_namespace{api.cc}::ArrayBufferAllocator::Allocate().
CallOnce() [1/2]
void v8::base::CallOnce (OnceType * once, std::function< void()> init_func) [inline]
Definition at line 90 of file once.h.
                                                                    {
  if (once->load(std::memory_order_acquire) != ONCE_STATE_DONE) {
    CallOnceImpl(once, init_func);
  }
}
References CallOnceImpl(), and ONCE_STATE_DONE.
Referenced by v8::internal::IsolateGroup::EnsureCodeRange(), v8::internal::Runtime::FunctionForName(), v8::base::ThreadSafeInitOnceTrait::Init(), v8::internal::win64_unwindinfo::anonymous_namespace{unwinding-info-win64.cc}::LoadNtdllUnwindingFunctions(), v8::Shell::Quit(), v8::internal::V8::SetSnapshotBlob(), and v8::internal::wasm::WasmInterpreter::WasmInterpreter().
CallOnce() [2/2]
template<typename... Args>
void v8::base::CallOnce (OnceType * once, typename FunctionWithArgs< Args... >::type init_func, Args... args) [inline]
Definition at line 97 of file once.h.
{
  if (once->load(std::memory_order_acquire) != ONCE_STATE_DONE) {
    CallOnceImpl(once, [=]() { init_func(args...); });
  }
}
References args, CallOnceImpl(), and ONCE_STATE_DONE.
CallOnceImpl()
V8_BASE_EXPORT void v8::base::CallOnceImpl (OnceType * once, std::function< void()> init_func)
Definition at line 18 of file once.cc.
                                                                 {
  // Fast path. The provided function was already executed.
  if (once->load(std::memory_order_acquire) == ONCE_STATE_DONE) {
    return;
  }
  // The function execution did not complete yet. The once object can be in one
  // of the two following states:
  // - UNINITIALIZED: We are the first thread calling this function.
  // - EXECUTING_FUNCTION: Another thread is already executing the function.
  //
  // First, try to change the state from UNINITIALIZED to EXECUTING_FUNCTION
  // atomically.
  uint8_t expected = ONCE_STATE_UNINITIALIZED;
  if (once->compare_exchange_strong(expected, ONCE_STATE_EXECUTING_FUNCTION,
                                    std::memory_order_acq_rel)) {
    // We are the first thread to call this function, so we have to call the
    // function.
    init_func();
    once->store(ONCE_STATE_DONE, std::memory_order_release);
  } else {
    // Another thread has already started executing the function. We need to
    // wait until it completes the initialization.
    while (once->load(std::memory_order_acquire) ==
           ONCE_STATE_EXECUTING_FUNCTION) {
#ifdef _WIN32
      ::Sleep(0);
#elif defined(V8_OS_STARBOARD)
      SbThreadYield();
#else
      sched_yield();
#endif
    }
  }
}
References ONCE_STATE_DONE, ONCE_STATE_EXECUTING_FUNCTION, and ONCE_STATE_UNINITIALIZED.
Referenced by CallOnce().
charToDigitDecodeForTesting()
V8_BASE_EXPORT int8_t v8::base::charToDigitDecodeForTesting (uint8_t c)
Definition at line 35 of file vlq-base64.cc.
{ return charToDigitDecode(c); }
References v8::base::anonymous_namespace{vlq-base64.cc}::charToDigitDecode().
CheckedIncrement()
template<typename T >
void v8::base::CheckedIncrement (std::atomic< T > * number, T amount, std::memory_order order = std::memory_order_seq_cst) [inline]
Definition at line 268 of file atomic-utils.h.
{
  const T old = number->fetch_add(amount, order);
  DCHECK_GE(old + amount, old);
  USE(old);
}
template <typename T>
inline void CheckedDecrement(
    std::atomic<T>* number, T amount,
    std::memory_order order = std::memory_order_seq_cst)
  requires std::is_unsigned_v<T>
{
  const T old = number->fetch_sub(amount, order);
  DCHECK_GE(old, amount);
  USE(old);
}
template <typename T>
V8_INLINE std::atomic<T>* AsAtomicPtr(T* t) {
  static_assert(sizeof(T) == sizeof(std::atomic<T>));
  static_assert(alignof(T) >= alignof(std::atomic<T>));
  return reinterpret_cast<std::atomic<T>*>(t);
}
References DCHECK_GE, and USE.
Referenced by v8::internal::Heap::IncrementExternalBackingStoreBytes(), v8::internal::MutablePageMetadata::IncrementExternalBackingStoreBytes(), v8::internal::Space::IncrementExternalBackingStoreBytes(), v8::internal::MutablePageMetadata::MoveExternalBackingStoreBytes(), and v8::internal::Space::MoveExternalBackingStoreBytes().
ComplementSample()
static std::vector<uint64_t> v8::base::ComplementSample (const std::unordered_set< uint64_t > & set, uint64_t max) [static]
Definition at line 132 of file random-number-generator.cc.
                                                         {
  std::vector<uint64_t> result;
  result.reserve(max - set.size());
  for (uint64_t i = 0; i < max; i++) {
    if (!set.count(i)) {
      result.push_back(i);
    }
  }
  return result;
}
References v8::base::internal::result.
Referenced by v8::base::RandomNumberGenerator::NextSample(), and v8::base::RandomNumberGenerator::NextSampleSlow().
contains()
template<typename C , typename T >
bool v8::base::contains (const C & container, const T & element)
Definition at line 19 of file container-utils.h.
                                                    {
  const auto e = std::end(container);
  return std::find(std::begin(container), e, element) != e;
}
References v8::internal::compiler::begin(), and v8::internal::compiler::end().
Referenced by v8::internal::anonymous_namespace{regexp-compiler.cc}::GetCaseIndependentLetters(), v8::internal::compiler::turboshaft::IsUnlikelySuccessor(), v8::internal::Builtins::Lookup(), v8::internal::Isolate::MaybeRemapEmbeddedBuiltinsIntoCodeRange(), v8::internal::compiler::LoadElimination::ReduceTransitionElementsKind(), and v8::internal::compiler::LoadElimination::ReduceTransitionElementsKindOrCheckMap().
ControlledCrashesAreHarmless()
bool v8::base::ControlledCrashesAreHarmless () [inline]
Definition at line 41 of file abort-mode.h.
                                              {
  return g_abort_mode == AbortMode::kExitWithSuccessAndIgnoreDcheckFailures ||
         g_abort_mode == AbortMode::kExitWithFailureAndIgnoreDcheckFailures;
}
References g_abort_mode, kExitWithFailureAndIgnoreDcheckFailures, and kExitWithSuccessAndIgnoreDcheckFailures.
Referenced by v8::internal::RUNTIME_FUNCTION(), and V8_Fatal().
ConvertUtf8StringToUtf16()
static std::wstring v8::base::ConvertUtf8StringToUtf16 (const char * str) [static]
Definition at line 613 of file platform-win32.cc.
                                                            {
  // On Windows wchar_t must be a 16-bit value.
  static_assert(sizeof(wchar_t) == 2, "wrong wchar_t size");
  std::wstring utf16_str;
  int name_length = static_cast<int>(strlen(str));
  int len = MultiByteToWideChar(CP_UTF8, 0, str, name_length, nullptr, 0);
  if (len > 0) {
    utf16_str.resize(len);
    MultiByteToWideChar(CP_UTF8, 0, str, name_length, &utf16_str[0], len);
  }
  return utf16_str;
}
count_if()
template<typename C , typename P >
size_t v8::base::count_if (const C & container, const P & predicate) [inline]
Definition at line 75 of file container-utils.h.
                                                               {
  return std::count_if(std::begin(container), std::end(container), predicate);
}
References v8::internal::compiler::begin(), and v8::internal::compiler::end().
Referenced by v8::internal::compiler::ElementAccessFeedback::AddGroup(), v8::internal::wasm::WasmEngine::DisableCodeLogging(), v8::internal::wasm::WasmEngine::EnableCodeLogging(), v8::internal::SourceTextModule::FinishInstantiate(), v8::internal::SourceTextModule::InnerModuleEvaluation(), v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::is_exclusive_user_of(), v8::internal::SourceTextModule::MaybeTransitionComponent(), and v8::internal::DictionaryTemplateInfo::NewInstance().
CStrVector()
Vector<const char> v8::base::CStrVector (const char * data) [inline]
Definition at line 330 of file vector.h.
                                                       {
  return {data, strlen(data)};
}
Referenced by v8::internal::StringStream::Add(), v8::internal::PendingCompilationErrorHandler::MessageDetails::ArgString(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::ArgumentToCompileOptions(), v8::internal::compiler::turboshaft::BuildWithTurboshaftAssemblerImpl(), v8::internal::Intl::CompareStringsOptionsFor(), v8::internal::Genesis::CompileExtension(), v8::internal::anonymous_namespace{intl-objects.cc}::CreateArrayFromList(), v8::internal::SharedFunctionInfo::DebugName(), v8::internal::wasm::fuzzing::GenerateRandomWasmModule(), v8::internal::wasm::fuzzing::GenerateWasmModuleForRevec(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::GetAddressType(), v8::internal::CallSiteInfo::GetMethodName(), v8::anonymous_namespace{wasm-js.cc}::GetValueType(), v8::internal::Factory::InternalizeUtf8String(), v8::internal::OptimizedCompilationInfo::OptimizedCompilationInfo(), v8::internal::SharedFunctionInfo::PassesFilter(), v8::internal::Builtins::PrintBuiltinCode(), v8::internal::anonymous_namespace{asm-js.cc}::ReportInstantiationFailure(), v8::internal::interpreter::anonymous_namespace{interpreter.cc}::ShouldPrintBytecode(), v8::internal::RegExp::ThrowRegExpException(), v8::internal::wasm::AsmJsParser::ValidateExport(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableImpl(), v8::internal::ValueSerializer::WriteJSError(), and v8::internal::wasm::WasmModuleBuilder::WriteTo().
DcheckFailuresAreIgnored()
bool v8::base::DcheckFailuresAreIgnored () [inline]
Definition at line 46 of file abort-mode.h.
                                          {
  return g_abort_mode == AbortMode::kExitWithSuccessAndIgnoreDcheckFailures ||
         g_abort_mode == AbortMode::kExitWithFailureAndIgnoreDcheckFailures;
}
References g_abort_mode, kExitWithFailureAndIgnoreDcheckFailures, and kExitWithSuccessAndIgnoreDcheckFailures.
Referenced by V8_Dcheck().
DEFINE_LAZY_LEAKY_OBJECT_GETTER()
v8::base::DEFINE_LAZY_LEAKY_OBJECT_GETTER (RandomNumberGenerator , GetPlatformRandomNumberGenerator)
DEFINE_SIGNED_MISMATCH_COMP()
v8::base::DEFINE_SIGNED_MISMATCH_COMP (is_signed_vs_unsigned , EQ , lhs >=0 && MAKE_UNSIGNEDLhs, lhs = = MAKE_UNDERLYING(Rhs, rhs))
DegToRad()
template<typename T >
requires constexpr std::floating_point<T> T v8::base::DegToRad (T deg) [constexpr]
Definition at line 18 of file angle_conversions.h.
                            {
  return deg * std::numbers::pi_v<T> / 180;
}
DigitGen()
static bool v8::base::DigitGen (DiyFp low, DiyFp w, DiyFp high, char ** outptr, int * kappa) [static]
Definition at line 405 of file fast-dtoa.cc.
                                 {
  DCHECK(low.e() == w.e() && w.e() == high.e());
  DCHECK(low.f() + 1 <= high.f() - 1);
  DCHECK(kMinimalTargetExponent <= w.e() && w.e() <= kMaximalTargetExponent);
  // low, w and high are imprecise, but by less than one ulp (unit in the last
  // place).
  // If we remove (resp. add) 1 ulp from low (resp. high) we are certain that
  // the new numbers are outside of the interval we want the final
  // representation to lie in.
  // Inversely adding (resp. removing) 1 ulp from low (resp. high) would yield
  // numbers that are certain to lie in the interval. We will use this fact
  // later on.
  // We will now start by generating the digits within the uncertain
  // interval. Later we will weed out representations that lie outside the safe
  // interval and thus _might_ lie outside the correct interval.
  uint64_t unit = 1;
  DiyFp too_low = DiyFp(low.f() - unit, low.e());
  DiyFp too_high = DiyFp(high.f() + unit, high.e());
  // too_low and too_high are guaranteed to lie outside the interval we want the
  // generated number in.
  DiyFp unsafe_interval = DiyFp::Minus(too_high, too_low);
  // We now cut the input number into two parts: the integral digits and the
  // fractionals. We will not write any decimal separator though, but adapt
  // kappa instead.
  // Reminder: we are currently computing the digits (stored inside the buffer)
  // such that: too_low < buffer * 10^kappa < too_high
  // We use too_high for the digit_generation and stop as soon as possible.
  // If we stop early we effectively round down.
  DiyFp one = DiyFp(static_cast<uint64_t>(1) << -w.e(), w.e());
  // Division by one is a shift.
  uint32_t integrals = static_cast<uint32_t>(too_high.f() >> -one.e());
  // Modulo by one is an and.
  uint64_t fractionals = too_high.f() & (one.f() - 1);
  uint32_t divisor;
  unsigned divisor_exponent;
  BiggestPowerTen(integrals, DiyFp::kSignificandSize - (-one.e()), &divisor,
                  &divisor_exponent);
  *kappa = divisor_exponent + 1;
  // Loop invariant: buffer = too_high / 10^kappa (integer division)
  // The invariant holds for the first iteration: kappa has been initialized
  // with the divisor exponent + 1. And the divisor is the biggest power of ten
  // that is smaller than integrals.
  while (*kappa > 0) {
    uint32_t digit = fast_divmod(&integrals, divisor, div[divisor_exponent]);
    **outptr = '0' + digit;
    (*outptr)++;
    (*kappa)--;
    // Note that kappa now equals the exponent of the divisor and that the
    // invariant thus holds again.
    uint64_t rest =
        (static_cast<uint64_t>(integrals) << -one.e()) + fractionals;
    // Invariant: too_high = buffer * 10^kappa + DiyFp(rest, one.e())
    // Reminder: unsafe_interval.e() == one.e()
    if (rest < unsafe_interval.f()) {
      // Rounding down (by not emitting the remaining digits) yields a number
      // that lies within the unsafe interval.
      return RoundWeed(*outptr - 1, DiyFp::Minus(too_high, w).f(),
                       unsafe_interval.f(), rest,
                       static_cast<uint64_t>(divisor) << -one.e(), unit);
    }
    if (*kappa <= 0) {
      // Don't bother doing the division below. (The compiler ought to
      // figure this out itself, but it doesn't.)
      break;
    }
    divisor /= 10;
    --divisor_exponent;
  }
  // The integrals have been generated. We are at the point of the decimal
  // separator. In the following loop we simply multiply the remaining digits by
  // 10 and divide by one. We just need to pay attention to multiply associated
  // data (like the interval or 'unit'), too.
  // Note that the multiplication by 10 does not overflow, because w.e >= -60
  // and thus one.e >= -60.
  DCHECK_GE(one.e(), -60);
  DCHECK(fractionals < one.f());
  DCHECK(0xFFFF'FFFF'FFFF'FFFF / 10 >= one.f());
  while (true) {
    fractionals *= 10;
    unit *= 10;
    unsafe_interval.set_f(unsafe_interval.f() * 10);
    // Integer division by one.
    int digit = static_cast<int>(fractionals >> -one.e());
    **outptr = '0' + digit;
    (*outptr)++;
    fractionals &= one.f() - 1; // Modulo by one.
    (*kappa)--;
    if (fractionals < unsafe_interval.f()) {
      return RoundWeed(*outptr - 1, DiyFp::Minus(too_high, w).f() * unit,
                       unsafe_interval.f(), fractionals, one.f(), unit);
    }
  }
}
References BiggestPowerTen(), DCHECK, DCHECK_GE, div, v8::base::DiyFp::e(), v8::base::DiyFp::f(), fast_divmod(), kMaximalTargetExponent, kMinimalTargetExponent, v8::base::DiyFp::kSignificandSize, v8::base::DiyFp::Minus(), one, RoundWeed(), and v8::base::DiyFp::set_f().
Referenced by Grisu3().
DigitGenCounted()
static bool v8::base::DigitGenCounted (DiyFp w, int requested_digits, Vector< char > buffer, int * length, int * kappa) [static]
Definition at line 529 of file fast-dtoa.cc.
                                                     {
  DCHECK(kMinimalTargetExponent <= w.e() && w.e() <= kMaximalTargetExponent);
  DCHECK_GE(kMinimalTargetExponent, -60);
  DCHECK_LE(kMaximalTargetExponent, -32);
  // w is assumed to have an error less than 1 unit. Whenever w is scaled we
  // also scale its error.
  uint64_t w_error = 1;
  // We cut the input number into two parts: the integral digits and the
  // fractional digits. We don't emit any decimal separator, but adapt kappa
  // instead. Example: instead of writing "1.2" we put "12" into the buffer and
  // increase kappa by 1.
  DiyFp one = DiyFp(static_cast<uint64_t>(1) << -w.e(), w.e());
  // Division by one is a shift.
  uint32_t integrals = static_cast<uint32_t>(w.f() >> -one.e());
  // Modulo by one is an and.
  uint64_t fractionals = w.f() & (one.f() - 1);
  uint32_t divisor;
  unsigned divisor_exponent;
  BiggestPowerTen(integrals, DiyFp::kSignificandSize - (-one.e()), &divisor,
                  &divisor_exponent);
  *kappa = divisor_exponent + 1;
  *length = 0;
  // Loop invariant: buffer = w / 10^kappa (integer division)
  // The invariant holds for the first iteration: kappa has been initialized
  // with the divisor exponent + 1. And the divisor is the biggest power of ten
  // that is smaller than 'integrals'.
  while (*kappa > 0) {
    uint32_t digit = fast_divmod(&integrals, divisor, div[divisor_exponent]);
    buffer[*length] = '0' + digit;
    (*length)++;
    requested_digits--;
    (*kappa)--;
    // Note that kappa now equals the exponent of the divisor and that the
    // invariant thus holds again.
    if (requested_digits == 0) break;
    divisor /= 10;
    --divisor_exponent;
  }
  if (requested_digits == 0) {
    uint64_t rest =
        (static_cast<uint64_t>(integrals) << -one.e()) + fractionals;
    return RoundWeedCounted(buffer, *length, rest,
                            static_cast<uint64_t>(divisor) << -one.e(), w_error,
                            kappa);
  }
  // The integrals have been generated. We are at the point of the decimal
  // separator. In the following loop we simply multiply the remaining digits by
  // 10 and divide by one. We just need to pay attention to multiply associated
  // data (the 'unit'), too.
  // Note that the multiplication by 10 does not overflow, because w.e >= -60
  // and thus one.e >= -60.
  DCHECK_GE(one.e(), -60);
  DCHECK(fractionals < one.f());
  DCHECK(0xFFFF'FFFF'FFFF'FFFF / 10 >= one.f());
  while (requested_digits > 0 && fractionals > w_error) {
    fractionals *= 10;
    w_error *= 10;
    // Integer division by one.
    int digit = static_cast<int>(fractionals >> -one.e());
    buffer[*length] = '0' + digit;
    (*length)++;
    requested_digits--;
    fractionals &= one.f() - 1; // Modulo by one.
    (*kappa)--;
  }
  if (requested_digits != 0) return false;
  return RoundWeedCounted(buffer, *length, fractionals, one.f(), w_error,
                          kappa);
}
References BiggestPowerTen(), DCHECK, DCHECK_GE, DCHECK_LE, div, v8::base::DiyFp::e(), v8::base::DiyFp::f(), fast_divmod(), kMaximalTargetExponent, kMinimalTargetExponent, v8::base::DiyFp::kSignificandSize, v8::internal::length, one, and RoundWeedCounted().
Referenced by Grisu3Counted().
Divide()
template<typename T >
T v8::base::Divide (T x, T y) [inline]
Definition at line 69 of file overflowing-math.h.
                          {
  if (y != 0) return x / y;
  if (x == 0 || x != x) return std::numeric_limits<T>::quiet_NaN();
  if ((x >= 0) == (std::signbit(y) == 0)) {
    return std::numeric_limits<T>::infinity();
  }
  return -std::numeric_limits<T>::infinity();
}
References v8::base::internal::y.
Referenced by v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction(), v8::internal::wasm::f16_div(), v8::base::ieee754::legacy::pow(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), Recip(), v8::internal::compiler::MachineOperatorReducer::Reduce(), and v8::internal::Parser::ShortcutLiteralBinaryExpression().
DiyFpStrtod()
static bool v8::base::DiyFpStrtod (Vector< const char > buffer, int exponent, double * result) [static]
Definition at line 234 of file strtod.cc.
                                        {
  DiyFp input;
  int remaining_decimals;
  ReadDiyFp(buffer, &input, &remaining_decimals);
  // Since we may have dropped some digits the input is not accurate.
  // If remaining_decimals is different than 0 than the error is at most
  // .5 ulp (unit in the last place).
  // We don't want to deal with fractions and therefore keep a common
  // denominator.
  const int kDenominatorLog = 3;
  const int kDenominator = 1 << kDenominatorLog;
  // Move the remaining decimals into the exponent.
  exponent += remaining_decimals;
  int64_t error = (remaining_decimals == 0 ? 0 : kDenominator / 2);
  int old_e = input.e();
  input.Normalize();
  error <<= old_e - input.e();
  DCHECK_LE(exponent, PowersOfTenCache::kMaxDecimalExponent);
  if (exponent < PowersOfTenCache::kMinDecimalExponent) {
    *result = 0.0;
    return true;
  }
  DiyFp cached_power;
  int cached_decimal_exponent;
  PowersOfTenCache::GetCachedPowerForDecimalExponent(exponent, &cached_power,
                                                     &cached_decimal_exponent);
  if (cached_decimal_exponent != exponent) {
    int adjustment_exponent = exponent - cached_decimal_exponent;
    DiyFp adjustment_power = AdjustmentPowerOfTen(adjustment_exponent);
    input.Multiply(adjustment_power);
    if (kMaxUint64DecimalDigits - buffer.length() >= adjustment_exponent) {
      // The product of input with the adjustment power fits into a 64 bit
      // integer.
      DCHECK_EQ(DiyFp::kSignificandSize, 64);
    } else {
      // The adjustment power is exact. There is hence only an error of 0.5.
      error += kDenominator / 2;
    }
  }
  input.Multiply(cached_power);
  // The error introduced by a multiplication of a*b equals
  // error_a + error_b + error_a*error_b/2^64 + 0.5
  // Substituting a with 'input' and b with 'cached_power' we have
  // error_b = 0.5 (all cached powers have an error of less than 0.5 ulp),
  // error_ab = 0 or 1 / kDenominator > error_a*error_b/ 2^64
  int error_b = kDenominator / 2;
  int error_ab = (error == 0 ? 0 : 1); // We round up to 1.
  int fixed_error = kDenominator / 2;
  error += error_b + error_ab + fixed_error;
  old_e = input.e();
  input.Normalize();
  error <<= old_e - input.e();
  // See if the double's significand changes if we add/subtract the error.
  int order_of_magnitude = DiyFp::kSignificandSize + input.e();
  int effective_significand_size =
      Double::SignificandSizeForOrderOfMagnitude(order_of_magnitude);
  int precision_digits_count =
      DiyFp::kSignificandSize - effective_significand_size;
  if (precision_digits_count + kDenominatorLog >= DiyFp::kSignificandSize) {
    // This can only happen for very small denormals. In this case the
    // half-way multiplied by the denominator exceeds the range of an uint64.
    // Simply shift everything to the right.
    int shift_amount = (precision_digits_count + kDenominatorLog) -
                       DiyFp::kSignificandSize + 1;
    input.set_f(input.f() >> shift_amount);
    input.set_e(input.e() + shift_amount);
    // We add 1 for the lost precision of error, and kDenominator for
    // the lost precision of input.f().
    error = (error >> shift_amount) + 1 + kDenominator;
    precision_digits_count -= shift_amount;
  }
  // We use uint64_ts now. This only works if the DiyFp uses uint64_ts too.
  DCHECK_EQ(DiyFp::kSignificandSize, 64);
  DCHECK_LT(precision_digits_count, 64);
  uint64_t one64 = 1;
  uint64_t precision_bits_mask = (one64 << precision_digits_count) - 1;
  uint64_t precision_bits = input.f() & precision_bits_mask;
  uint64_t half_way = one64 << (precision_digits_count - 1);
  precision_bits *= kDenominator;
  half_way *= kDenominator;
  DiyFp rounded_input(input.f() >> precision_digits_count,
                      input.e() + precision_digits_count);
  if (precision_bits >= half_way + error) {
    rounded_input.set_f(rounded_input.f() + 1);
  }
  // If the last_bits are too close to the half-way case than we are too
  // inaccurate and round down. In this case we return false so that we can
  // fall back to a more precise algorithm.
  *result = Double(rounded_input).value();
  if (half_way - error < precision_bits && precision_bits < half_way + error) {
    // Too imprecise. The caller will have to fall back to a slower version.
    // However the returned number is guaranteed to be either the correct
    // double, or the next-lower double.
    return false;
  } else {
    return true;
  }
}
References AdjustmentPowerOfTen(), DCHECK_EQ, DCHECK_LE, DCHECK_LT, v8::base::DiyFp::e(), v8::base::DiyFp::f(), v8::base::PowersOfTenCache::GetCachedPowerForDecimalExponent(), v8::base::PowersOfTenCache::kMaxDecimalExponent, kMaxUint64DecimalDigits, v8::base::PowersOfTenCache::kMinDecimalExponent, v8::base::DiyFp::kSignificandSize, v8::base::Vector< T >::length(), v8::base::DiyFp::Multiply(), v8::base::DiyFp::Normalize(), ReadDiyFp(), v8::base::internal::result, v8::base::DiyFp::set_e(), v8::base::DiyFp::set_f(), v8::base::Double::SignificandSizeForOrderOfMagnitude(), and v8::base::Double::value().
Referenced by Strtod().
double_to_uint64()
constexpr uint64_t v8::base::double_to_uint64 (double d) [inline], [constexpr]
Definition at line 17 of file double.h.
                                                     {
  return std::bit_cast<uint64_t>(d);
}
Referenced by v8::internal::maglev::Graph::GetFloat64Constant(), v8::internal::Object::GetSimpleHash(), and v8::internal::Literal::Hash().
DoubleFromBigEndian()
constexpr double v8::base::DoubleFromBigEndian (std::span< const uint8_t, 8u > bytes) [inline], [constexpr]
Definition at line 386 of file byte_conversions.h.
                                      {
  return std::bit_cast<double>(U64FromBigEndian(bytes));
}
References U64FromBigEndian().
Referenced by v8::base::numerics::TEST().
DoubleFromLittleEndian()
constexpr double v8::base::DoubleFromLittleEndian (std::span< const uint8_t, 8u > bytes) [inline], [constexpr]
Definition at line 276 of file byte_conversions.h.
                                      {
  return std::bit_cast<double>(U64FromLittleEndian(bytes));
}
References U64FromLittleEndian().
Referenced by v8::base::numerics::TEST().
DoubleFromNativeEndian()
constexpr double v8::base::DoubleFromNativeEndian (std::span< const uint8_t, 8u > bytes) [inline], [constexpr]
Definition at line 148 of file byte_conversions.h.
                                      {
  return std::bit_cast<double>(U64FromNativeEndian(bytes));
}
References U64FromNativeEndian().
Referenced by v8::base::numerics::TEST().
DoubleStrtod()
static bool v8::base::DoubleStrtod (Vector< const char > trimmed, int exponent, double * result) [static]
Definition at line 148 of file strtod.cc.
                                         {
#if (V8_TARGET_ARCH_IA32 || defined(USE_SIMULATOR)) && !defined(_MSC_VER)
  // On x86 the floating-point stack can be 64 or 80 bits wide. If it is
  // 80 bits wide (as is the case on Linux) then double-rounding occurs and the
  // result is not accurate.
  // We know that Windows32 with MSVC, unlike with MinGW32, uses 64 bits and is
  // therefore accurate.
  // Note that the ARM simulators are compiled for 32bits. They
  // therefore exhibit the same problem.
  USE(exact_powers_of_ten);
  USE(kMaxExactDoubleIntegerDecimalDigits);
  USE(kExactPowersOfTenSize);
  return false;
#else
  if (trimmed.length() <= kMaxExactDoubleIntegerDecimalDigits) {
    int read_digits;
    // The trimmed input fits into a double.
    // If the 10^exponent (resp. 10^-exponent) fits into a double too then we
    // can compute the result-double simply by multiplying (resp. dividing) the
    // two numbers.
    // This is possible because IEEE guarantees that floating-point operations
    // return the best possible approximation.
    if (exponent < 0 && -exponent < kExactPowersOfTenSize) {
      // 10^-exponent fits into a double.
      *result = static_cast<double>(ReadUint64(trimmed, &read_digits));
      DCHECK(read_digits == trimmed.length());
      *result /= exact_powers_of_ten[-exponent];
      return true;
    }
    if (0 <= exponent && exponent < kExactPowersOfTenSize) {
      // 10^exponent fits into a double.
      *result = static_cast<double>(ReadUint64(trimmed, &read_digits));
      DCHECK(read_digits == trimmed.length());
      *result *= exact_powers_of_ten[exponent];
      return true;
    }
    int remaining_digits =
        kMaxExactDoubleIntegerDecimalDigits - trimmed.length();
    if ((0 <= exponent) &&
        (exponent - remaining_digits < kExactPowersOfTenSize)) {
      // The trimmed string was short and we can multiply it with
      // 10^remaining_digits. As a result the remaining exponent now fits
      // into a double too.
      *result = static_cast<double>(ReadUint64(trimmed, &read_digits));
      DCHECK(read_digits == trimmed.length());
      *result *= exact_powers_of_ten[remaining_digits];
      *result *= exact_powers_of_ten[exponent - remaining_digits];
      return true;
    }
  }
  return false;
#endif
}
References DCHECK, exact_powers_of_ten, kExactPowersOfTenSize, kMaxExactDoubleIntegerDecimalDigits, v8::base::Vector< T >::length(), ReadUint64(), v8::base::internal::result, and USE.
Referenced by Strtod().
DoubleToAscii()
V8_BASE_EXPORT void v8::base::DoubleToAscii (double v, DtoaMode mode, int requested_digits, Vector< char > buffer, int * sign, int * length, int * point)
Definition at line 31 of file dtoa.cc.
                                                                            {
  DCHECK(!Double(v).IsSpecial());
  DCHECK(mode == DTOA_SHORTEST || requested_digits >= 0);
  if (Double(v).Sign() < 0) {
    *sign = 1;
    v = -v;
  } else {
    *sign = 0;
  }
  if (v == 0) {
    buffer[0] = '0';
    buffer[1] = '\0';
    *length = 1;
    *point = 1;
    return;
  }
  if (mode == DTOA_PRECISION && requested_digits == 0) {
    buffer[0] = '\0';
    *length = 0;
    return;
  }
  bool fast_worked;
  switch (mode) {
    case DTOA_SHORTEST:
      fast_worked = FastDtoa(v, FAST_DTOA_SHORTEST, 0, buffer, length, point);
      break;
    case DTOA_FIXED:
      fast_worked = FastFixedDtoa(v, requested_digits, buffer, length, point);
      break;
    case DTOA_PRECISION:
      fast_worked = FastDtoa(v, FAST_DTOA_PRECISION, requested_digits, buffer,
                             length, point);
      break;
    default:
      UNREACHABLE();
  }
  if (fast_worked) return;
  // If the fast dtoa didn't succeed use the slower bignum version.
  BignumDtoaMode bignum_mode = DtoaToBignumDtoaMode(mode);
  BignumDtoa(v, bignum_mode, requested_digits, buffer, length, point);
  buffer[*length] = '\0';
}
References BignumDtoa(), DCHECK, DTOA_FIXED, DTOA_PRECISION, DTOA_SHORTEST, DtoaToBignumDtoaMode(), FAST_DTOA_PRECISION, FAST_DTOA_SHORTEST, FastDtoa(), FastFixedDtoa(), v8::internal::length, mode(), v8::internal::sign, and UNREACHABLE.
Referenced by v8::internal::DoubleToExponentialStringView(), v8::internal::DoubleToFixedStringView(), and v8::internal::DoubleToPrecisionStringView().
DoubleToBigEndian()
constexpr std::array<uint8_t, 8u> v8::base::DoubleToBigEndian (double val) [inline], [constexpr]
Definition at line 710 of file byte_conversions.h.
                                                                     {
  return internal::ToLittleEndian(ByteSwap(std::bit_cast<uint64_t>(val)));
}
Referenced by v8::base::numerics::TEST().
DoubleToLittleEndian()
constexpr std::array<uint8_t, 8u> v8::base::DoubleToLittleEndian (double val) [inline], [constexpr]
Definition at line 599 of file byte_conversions.h.
                                                                        {
  return internal::ToLittleEndian(std::bit_cast<uint64_t>(val));
}
Referenced by v8::base::numerics::TEST().
DoubleToNativeEndian()
constexpr std::array<uint8_t, 8u> v8::base::DoubleToNativeEndian (double val) [inline], [constexpr]
Definition at line 488 of file byte_conversions.h.
                                                                        {
  return U64ToNativeEndian(std::bit_cast<uint64_t>(val));
}
References U64ToNativeEndian().
Referenced by v8::base::numerics::TEST().
DtoaRoundUp()
static void v8::base::DtoaRoundUp (Vector< char > buffer, int * length, int * decimal_point) [static]
Definition at line 163 of file fixed-dtoa.cc.
                                                                              {
  // An empty buffer represents 0.
  if (*length == 0) {
    buffer[0] = '1';
    *decimal_point = 1;
    *length = 1;
    return;
  }
  // Round the last digit until we either have a digit that was not '9' or until
  // we reached the first digit.
  buffer[(*length) - 1]++;
  for (int i = (*length) - 1; i > 0; --i) {
    if (buffer[i] != '0' + 10) {
      return;
    }
    buffer[i] = '0';
    buffer[i - 1]++;
  }
  // If the first digit is now '0' + 10, we would need to set it to '0' and add
  // a '1' in front. However we reach the first digit only if all following
  // digits had been '9' before rounding up. Now all trailing digits are '0' and
  // we simply switch the first digit to '1' and update the decimal-point
  // (indicating that the point is now one digit to the right).
  if (buffer[0] == '0' + 10) {
    buffer[0] = '1';
    (*decimal_point)++;
  }
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::length.
Referenced by FillFractionals().
DtoaToBignumDtoaMode()
static BignumDtoaMode v8::base::DtoaToBignumDtoaMode (DtoaMode dtoa_mode) [static]
Definition at line 18 of file dtoa.cc.
                                                               {
  switch (dtoa_mode) {
    case DTOA_SHORTEST:
      return BIGNUM_DTOA_SHORTEST;
    case DTOA_FIXED:
      return BIGNUM_DTOA_FIXED;
    case DTOA_PRECISION:
      return BIGNUM_DTOA_PRECISION;
    default:
      UNREACHABLE();
  }
}
References BIGNUM_DTOA_FIXED, BIGNUM_DTOA_PRECISION, BIGNUM_DTOA_SHORTEST, DTOA_FIXED, DTOA_PRECISION, DTOA_SHORTEST, and UNREACHABLE.
Referenced by DoubleToAscii().
EnsureConsoleOutput()
void v8::base::EnsureConsoleOutput () [inline]
Definition at line 440 of file platform.h.
                                  {
#if defined(V8_OS_WIN)
  // Windows requires extra calls to send assert output to the console
  // rather than a dialog box.
  EnsureConsoleOutputWin32();
#endif // defined(V8_OS_WIN)
}
Referenced by main(), and v8::Shell::Main().
erase_at()
template<typename C >
size_t v8::base::erase_at (C & container, size_t index, size_t count = 1) [inline]
Definition at line 52 of file container-utils.h.
                                                                     {
  // TODO(C++20): Replace with std::erase.
  if (std::size(container) <= index) return 0;
  auto start = std::begin(container) + index;
  count = std::min<size_t>(count, std::distance(start, std::end(container)));
  container.erase(start, start + count);
  return count;
}
References v8::internal::compiler::begin(), v8::internal::compiler::end(), v8::internal::index, and size().
erase_if()
template<typename C , typename P >
size_t v8::base::erase_if (C & container, const P & predicate) [inline]
Definition at line 65 of file container-utils.h.
                                                         {
  auto it =
      std::remove_if(std::begin(container), std::end(container), predicate);
  auto count = std::distance(it, std::end(container));
  container.erase(it, std::end(container));
  return count;
}
References v8::internal::compiler::begin(), and v8::internal::compiler::end().
Referenced by v8::internal::PagePool::LargePagePoolImpl::Add(), v8::internal::OptimizingCompileInputQueue::FlushJobsForIsolate(), v8::internal::wasm::WasmEngine::FreeNativeModule(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::ProductSet(), v8::internal::PagePool::PoolImpl< PoolEntry >::ReleaseUpTo(), v8::internal::PagePool::LargePagePoolImpl::ReleaseUpTo(), and v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Set().
EstimatePower()
static int v8::base::EstimatePower (int exponent) [static]
Definition at line 330 of file bignum-dtoa.cc.
                                       {
  // This function estimates log10 of v where v = f*2^e (with e == exponent).
  // Note that 10^floor(log10(v)) <= v, but v <= 10^ceil(log10(v)).
  // Note that f is bounded by its container size. Let p = 53 (the double's
  // significand size). Then 2^(p-1) <= f < 2^p.
  //
  // Given that log10(v) == log2(v)/log2(10) and e+(len(f)-1) is quite close
  // to log2(v) the function is simplified to (e+(len(f)-1)/log2(10)).
  // The computed number undershoots by less than 0.631 (when we compute log3
  // and not log10).
  //
  // Optimization: since we only need an approximated result this computation
  // can be performed on 64 bit integers. On x86/x64 architecture the speedup is
  // not really measurable, though.
  //
  // Since we want to avoid overshooting we decrement by 1e10 so that
  // floating-point imprecisions don't affect us.
  //
  // Explanation for v's boundary m+: the computation takes advantage of
  // the fact that 2^(p-1) <= f < 2^p. Boundaries still satisfy this requirement
  // (even for denormals where the delta can be much more important).
  const double k1Log10 = 0.30102999566398114; // 1/lg(10)
  // For doubles len(f) == 53 (don't forget the hidden bit).
  const int kSignificandSize = 53;
  double estimate =
      std::ceil((exponent + kSignificandSize - 1) * k1Log10 - 1e-10);
  return static_cast<int>(estimate);
}
Referenced by BignumDtoa().
EXPLICIT_CHECK_OP_INSTANTIATION()
v8::base::EXPLICIT_CHECK_OP_INSTANTIATION (long)
Definition at line 324 of file logging.h.
                                  {
  // std::underlying_type must only be used with enum types, thus use this
  // {Dummy} type if the given type is not an enum.
  enum Dummy {};
  using decay = std::decay_t<T>;
  static constexpr bool is_enum = std::is_enum_v<decay>;
  using underlying =
      std::underlying_type_t<std::conditional_t<is_enum, decay, Dummy>>;
  using type_or_bool = std::conditional_t<is_enum, underlying, decay>;
  using type = std::conditional_t<std::is_same_v<type_or_bool, bool>,
                                  unsigned int, type_or_bool>;
};
References v8::Dummy(), and v8::internal::tracing::type.
EXPORT_TEMPLATE_DECLARE()
template<class T >
template v8::base::EXPORT_TEMPLATE_DECLARE (V8_BASE_EXPORT)
Definition at line 1 of file division-by-constant.h.
                                                                       {
  static_assert(std::is_integral_v<T>);
  MagicNumbersForDivision(T m, unsigned s, bool a)
      : multiplier(m), shift(s), add(a) {}
  bool operator==(const MagicNumbersForDivision& rhs) const {
    return multiplier == rhs.multiplier && shift == rhs.shift && add == rhs.add;
  }
  T multiplier;
  unsigned shift;
  bool add;
};
References operator==(), requires(), SignedDivisionByConstant(), and V8_BASE_EXPORT.
EXPORT_TEMPLATE_DEFINE()
template v8::base::EXPORT_TEMPLATE_DEFINE (V8_BASE_EXPORT)
fast_divmod()
static uint32_t v8::base::fast_divmod (uint32_t * val, uint32_t divisor, const DivMagic & d) [inline], [static]
Definition at line 236 of file fast-dtoa.cc.
                                                      {
  if (divisor == 1) {
    uint32_t digit = *val;
    *val = 0;
    return digit;
  } else {
    uint32_t q = (static_cast<uint64_t>(*val) * d.mul) >> 32;
    uint32_t t = ((*val - q) >> 1) + q;
    uint32_t digit = t >> d.shift;
    *val -= digit * divisor;
    return digit;
  }
}
References v8::base::DivMagic::mul, and v8::base::DivMagic::shift.
Referenced by DigitGen(), and DigitGenCounted().
FastDtoa()
V8_BASE_EXPORT bool v8::base::FastDtoa (double v, FastDtoaMode mode, int requested_digits, Vector< char > buffer, int * length, int * decimal_point)
Definition at line 713 of file fast-dtoa.cc.
                                                                    {
  DCHECK_GT(v, 0);
  DCHECK(!Double(v).IsSpecial());
  bool result = false;
  char* outptr = buffer.data();
  int decimal_exponent = 0;
  switch (mode) {
    case FAST_DTOA_SHORTEST:
      result = Grisu3(v, &outptr, &decimal_exponent);
      *length = static_cast<int>(outptr - buffer.data());
      break;
    case FAST_DTOA_PRECISION: {
      int local_length = 0;
      result = Grisu3Counted(v, requested_digits, buffer, &local_length,
                             &decimal_exponent);
      *length = local_length;
      break;
    }
    default:
      UNREACHABLE();
  }
  if (result) {
    *decimal_point = *length + decimal_exponent;
    buffer[*length] = '\0';
  }
  return result;
}
References v8::base::Vector< T >::data(), DCHECK, DCHECK_GT, FAST_DTOA_PRECISION, FAST_DTOA_SHORTEST, Grisu3(), Grisu3Counted(), v8::internal::length, mode(), v8::base::internal::result, and UNREACHABLE.
Referenced by DoubleToAscii().
FastFixedDtoa()
V8_BASE_EXPORT bool v8::base::FastFixedDtoa (double v, int fractional_count, Vector< char > buffer, int * length, int * decimal_point)
Definition at line 278 of file fixed-dtoa.cc.
                                                    {
  const uint32_t kMaxUInt32 = 0xFFFFFFFF;
  uint64_t significand = Double(v).Significand();
  int exponent = Double(v).Exponent();
  // v = significand * 2^exponent (with significand a 53bit integer).
  // If the exponent is larger than 20 (i.e. we may have a 73bit number) then we
  // don't know how to compute the representation. 2^73 ~= 9.5*10^21.
  // If necessary this limit could probably be increased, but we don't need
  // more.
  if (exponent > 20) return false;
  if (fractional_count > 20) return false;
  *length = 0;
  // At most kDoubleSignificandSize bits of the significand are non-zero.
  // Given a 64 bit integer we have 11 0s followed by 53 potentially non-zero
  // bits: 0..11*..0xxx..53*..xx
  if (exponent + kDoubleSignificandSize > 64) {
    // The exponent must be > 11.
    //
    // We know that v = significand * 2^exponent.
    // And the exponent > 11.
    // We simplify the task by dividing v by 10^17.
    // The quotient delivers the first digits, and the remainder fits into a 64
    // bit number.
    // Dividing by 10^17 is equivalent to dividing by 5^17*2^17.
    const uint64_t kFive17 = 0xB1'A2BC'2EC5; // 5^17
    uint64_t divisor = kFive17;
    int divisor_power = 17;
    uint64_t dividend = significand;
    uint32_t quotient;
    uint64_t remainder;
    // Let v = f * 2^e with f == significand and e == exponent.
    // Then need q (quotient) and r (remainder) as follows:
    // v = q * 10^17 + r
    // f * 2^e = q * 10^17 + r
    // f * 2^e = q * 5^17 * 2^17 + r
    // If e > 17 then
    // f * 2^(e-17) = q * 5^17 + r/2^17
    // else
    // f = q * 5^17 * 2^(17-e) + r/2^e
    if (exponent > divisor_power) {
      // We only allow exponents of up to 20 and therefore (17 - e) <= 3
      dividend <<= exponent - divisor_power;
      quotient = static_cast<uint32_t>(dividend / divisor);
      remainder = (dividend % divisor) << divisor_power;
    } else {
      divisor <<= divisor_power - exponent;
      quotient = static_cast<uint32_t>(dividend / divisor);
      remainder = (dividend % divisor) << exponent;
    }
    FillDigits32(quotient, buffer, length);
    FillDigits64FixedLength(remainder, divisor_power, buffer, length);
    *decimal_point = *length;
  } else if (exponent >= 0) {
    // 0 <= exponent <= 11
    significand <<= exponent;
    FillDigits64(significand, buffer, length);
    *decimal_point = *length;
  } else if (exponent > -kDoubleSignificandSize) {
    // We have to cut the number.
    uint64_t integrals = significand >> -exponent;
    uint64_t fractionals = significand - (integrals << -exponent);
    if (integrals > kMaxUInt32) {
      FillDigits64(integrals, buffer, length);
    } else {
      FillDigits32(static_cast<uint32_t>(integrals), buffer, length);
    }
    *decimal_point = *length;
    FillFractionals(fractionals, exponent, fractional_count, buffer, length,
                    decimal_point);
  } else if (exponent < -128) {
    // This configuration (with at most 20 digits) means that all digits must be
    // 0.
    DCHECK_LE(fractional_count, 20);
    buffer[0] = '\0';
    *length = 0;
    *decimal_point = -fractional_count;
  } else {
    *decimal_point = 0;
    FillFractionals(significand, exponent, fractional_count, buffer, length,
                    decimal_point);
  }
  TrimZeros(buffer, length, decimal_point);
  buffer[*length] = '\0';
  if ((*length) == 0) {
    // The string is empty and the decimal_point thus has no importance. Mimick
    // Gay's dtoa and and set it to -fractional_count.
    *decimal_point = -fractional_count;
  }
  return true;
}
References DCHECK_LE, v8::base::Double::Exponent(), FillDigits32(), FillDigits64(), FillDigits64FixedLength(), FillFractionals(), kDoubleSignificandSize, v8::internal::kMaxUInt32, v8::internal::length, v8::base::Double::Significand(), and TrimZeros().
Referenced by DoubleToAscii().
FatalOOM()
V8_BASE_EXPORT void v8::base::FatalOOM (OOMType type, const char * msg)
Definition at line 80 of file logging.cc.
                                             {
  // Instead of directly aborting here with a message, it could make sense to
  // call a global callback function that would then in turn call (the
  // equivalent of) V8::FatalProcessOutOfMemory. This way, calling this
  // function directly would not bypass any OOM handler installed by the
  // embedder. We might still want to keep a function like this though that
  // contains the fallback implementation if no callback has been installed.
  const char* type_str = type == OOMType::kProcess ? "process" : "JavaScript";
  OS::PrintError("\n\n#\n# Fatal %s out of memory: %s\n#", type_str, msg);
  if (g_print_stack_trace) v8::base::g_print_stack_trace();
  fflush(stderr);
#ifdef V8_FUZZILLI
  // When fuzzing, we generally want to ignore OOM failures.
  // It's important that we exit with a non-zero exit status here so that the
  // fuzzer treats it as a failed execution.
  _exit(1);
#else
  OS::Abort();
#endif // V8_FUZZILLI
}
References v8::base::OS::Abort(), v8::base::anonymous_namespace{logging.cc}::g_print_stack_trace, kProcess, and v8::internal::tracing::type.
Referenced by heap::base::Worklist< EntryType, MinSegmentSize >::Segment::Create(), v8::base::VirtualAddressSubspace::FreePages(), v8::base::SmallVector< T, kSize, Allocator >::Grow(), and v8::Utils::ReportOOMFailure().
Fclose()
int v8::base::Fclose (FILE * stream) [inline]
Definition at line 22 of file wrappers.h.
                                {
#if V8_OS_STARBOARD
  return -1;
#else
  return fclose(stream);
#endif
}
Referenced by v8::internal::CodeTracer::CloseFile(), v8::base::CPU::CPU(), v8::internal::Isolate::Deinit(), v8::internal::wasm::DumpModule(), v8::internal::wasm::DumpProfileToFile(), anonymous_namespace{mksnapshot.cc}::GetExtraCode(), v8::internal::InitializeICU(), v8::internal::wasm::LoadProfileFromFile(), v8::Shell::LogGetAndStop(), v8::internal::EmbeddedFileWriter::MaybeWriteEmbeddedFile(), anonymous_namespace{mksnapshot.cc}::SnapshotFileWriter::MaybeWriteSnapshotFile(), anonymous_namespace{mksnapshot.cc}::SnapshotFileWriter::MaybeWriteStartupBlob(), v8::base::RandomNumberGenerator::RandomNumberGenerator(), v8::Shell::ReadChars(), v8::internal::anonymous_namespace{utils.cc}::ReadCharsFromFile(), v8::internal::WriteChars(), v8::Shell::WriteChars(), v8::Shell::WriteFile(), and v8::internal::LowLevelLogger::~LowLevelLogger().
FillDigits32()
static void v8::base::FillDigits32 (uint32_t number, Vector< char > buffer, int * length) [static]
Definition at line 107 of file fixed-dtoa.cc.
                                                                            {
  int number_length = 0;
  // We fill the digits in reverse order and exchange them afterwards.
  while (number != 0) {
    int digit = number % 10;
    number /= 10;
    buffer[(*length) + number_length] = '0' + digit;
    number_length++;
  }
  // Exchange the digits.
  int i = *length;
  int j = *length + number_length - 1;
  while (i < j) {
    char tmp = buffer[i];
    buffer[i] = buffer[j];
    buffer[j] = tmp;
    i++;
    j--;
  }
  *length += number_length;
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::length.
Referenced by FastFixedDtoa(), and FillDigits64().
FillDigits32FixedLength()
static void v8::base::FillDigits32FixedLength (uint32_t number, int requested_length, Vector< char > buffer, int * length) [static]
Definition at line 98 of file fixed-dtoa.cc.
                                                                      {
  for (int i = requested_length - 1; i >= 0; --i) {
    buffer[(*length) + i] = '0' + number % 10;
    number /= 10;
  }
  *length += requested_length;
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::length.
Referenced by FillDigits64(), and FillDigits64FixedLength().
FillDigits64()
static void v8::base::FillDigits64 (uint64_t number, Vector< char > buffer, int * length) [static]
Definition at line 143 of file fixed-dtoa.cc.
                                                                            {
  const uint32_t kTen7 = 10000000;
  // For efficiency cut the number into 3 uint32_t parts, and print those.
  uint32_t part2 = static_cast<uint32_t>(number % kTen7);
  number /= kTen7;
  uint32_t part1 = static_cast<uint32_t>(number % kTen7);
  uint32_t part0 = static_cast<uint32_t>(number / kTen7);
  if (part0 != 0) {
    FillDigits32(part0, buffer, length);
    FillDigits32FixedLength(part1, 7, buffer, length);
    FillDigits32FixedLength(part2, 7, buffer, length);
  } else if (part1 != 0) {
    FillDigits32(part1, buffer, length);
    FillDigits32FixedLength(part2, 7, buffer, length);
  } else {
    FillDigits32(part2, buffer, length);
  }
}
References FillDigits32(), FillDigits32FixedLength(), kTen7, and v8::internal::length.
Referenced by FastFixedDtoa().
FillDigits64FixedLength()
static void v8::base::FillDigits64FixedLength (uint64_t number, int requested_length, Vector< char > buffer, int * length) [static]
Definition at line 129 of file fixed-dtoa.cc.
                                                                      {
  const uint32_t kTen7 = 10000000;
  // For efficiency cut the number into 3 uint32_t parts, and print those.
  uint32_t part2 = static_cast<uint32_t>(number % kTen7);
  number /= kTen7;
  uint32_t part1 = static_cast<uint32_t>(number % kTen7);
  uint32_t part0 = static_cast<uint32_t>(number / kTen7);
  FillDigits32FixedLength(part0, 3, buffer, length);
  FillDigits32FixedLength(part1, 7, buffer, length);
  FillDigits32FixedLength(part2, 7, buffer, length);
}
References FillDigits32FixedLength(), kTen7, and v8::internal::length.
Referenced by FastFixedDtoa().
FillFractionals()
static void v8::base::FillFractionals (uint64_t fractionals, int exponent, int fractional_count, Vector< char > buffer, int * length, int * decimal_point) [static]
Definition at line 203 of file fixed-dtoa.cc.
                                                             {
  DCHECK(-128 <= exponent && exponent <= 0);
  // 'fractionals' is a fixed-point number, with binary point at bit
  // (-exponent). Inside the function the non-converted remainder of fractionals
  // is a fixed-point number, with binary point at bit 'point'.
  if (-exponent <= 64) {
    // One 64 bit number is sufficient.
    DCHECK_EQ(fractionals >> 56, 0);
    int point = -exponent;
    for (int i = 0; i < fractional_count; ++i) {
      if (fractionals == 0) break;
      // Instead of multiplying by 10 we multiply by 5 and adjust the point
      // location. This way the fractionals variable will not overflow.
      // Invariant at the beginning of the loop: fractionals < 2^point.
      // Initially we have: point <= 64 and fractionals < 2^56
      // After each iteration the point is decremented by one.
      // Note that 5^3 = 125 < 128 = 2^7.
      // Therefore three iterations of this loop will not overflow fractionals
      // (even without the subtraction at the end of the loop body). At this
      // time point will satisfy point <= 61 and therefore fractionals < 2^point
      // and any further multiplication of fractionals by 5 will not overflow.
      fractionals *= 5;
      point--;
      int digit = static_cast<int>(fractionals >> point);
      buffer[*length] = '0' + digit;
      (*length)++;
      fractionals -= static_cast<uint64_t>(digit) << point;
    }
    // If the first bit after the point is set we have to round up.
    if (point > 0 && ((fractionals >> (point - 1)) & 1) == 1) {
      DtoaRoundUp(buffer, length, decimal_point);
    }
  } else { // We need 128 bits.
    DCHECK(64 < -exponent && -exponent <= 128);
    UInt128 fractionals128 = UInt128(fractionals, 0);
    fractionals128.Shift(-exponent - 64);
    int point = 128;
    for (int i = 0; i < fractional_count; ++i) {
      if (fractionals128.IsZero()) break;
      // As before: instead of multiplying by 10 we multiply by 5 and adjust the
      // point location.
      // This multiplication will not overflow for the same reasons as before.
      fractionals128.Multiply(5);
      point--;
      int digit = fractionals128.DivModPowerOf2(point);
      buffer[*length] = '0' + digit;
      (*length)++;
    }
    if (fractionals128.BitAt(point - 1) == 1) {
      DtoaRoundUp(buffer, length, decimal_point);
    }
  }
}
References v8::base::UInt128::BitAt(), DCHECK, DCHECK_EQ, v8::base::UInt128::DivModPowerOf2(), DtoaRoundUp(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::base::UInt128::IsZero(), v8::internal::length, v8::base::UInt128::Multiply(), and v8::base::UInt128::Shift().
Referenced by FastFixedDtoa().
FixupMultiply10()
static void v8::base::FixupMultiply10 (int estimated_power, bool is_even, int * decimal_point, Bignum * numerator, Bignum * denominator, Bignum * delta_minus, Bignum * delta_plus) [static]
Definition at line 577 of file bignum-dtoa.cc.
                                                {
  bool in_range;
  if (is_even) {
    // For IEEE doubles half-way cases (in decimal system numbers ending with 5)
    // are rounded to the closest floating-point number with even significand.
    in_range = Bignum::PlusCompare(*numerator, *delta_plus, *denominator) >= 0;
  } else {
    in_range = Bignum::PlusCompare(*numerator, *delta_plus, *denominator) > 0;
  }
  if (in_range) {
    // Since numerator + delta_plus >= denominator we already have
    // 1 <= numerator/denominator < 10. Simply update the estimated_power.
    *decimal_point = estimated_power + 1;
  } else {
    *decimal_point = estimated_power;
    numerator->Times10();
    if (Bignum::Equal(*delta_minus, *delta_plus)) {
      delta_minus->Times10();
      delta_plus->AssignBignum(*delta_minus);
    } else {
      delta_minus->Times10();
      delta_plus->Times10();
    }
  }
}
References v8::base::Bignum::AssignBignum(), v8::base::Bignum::Equal(), v8::base::Bignum::PlusCompare(), and v8::base::Bignum::Times10().
Referenced by BignumDtoa().
FloatFromBigEndian()
constexpr float v8::base::FloatFromBigEndian (std::span< const uint8_t, 4u > bytes) [inline], [constexpr]
Definition at line 376 of file byte_conversions.h.
                                                                            {
  return std::bit_cast<float>(U32FromBigEndian(bytes));
}
References U32FromBigEndian().
Referenced by v8::base::numerics::TEST().
FloatFromLittleEndian()
constexpr float v8::base::FloatFromLittleEndian (std::span< const uint8_t, 4u > bytes) [inline], [constexpr]
Definition at line 264 of file byte_conversions.h.
                                      {
  return std::bit_cast<float>(U32FromLittleEndian(bytes));
}
References U32FromLittleEndian().
Referenced by v8::base::numerics::TEST().
FloatFromNativeEndian()
constexpr float v8::base::FloatFromNativeEndian (std::span< const uint8_t, 4u > bytes) [inline], [constexpr]
Definition at line 137 of file byte_conversions.h.
                                      {
  return std::bit_cast<float>(U32FromNativeEndian(bytes));
}
References U32FromNativeEndian().
Referenced by v8::base::numerics::TEST().
FloatToBigEndian()
constexpr std::array<uint8_t, 4u> v8::base::FloatToBigEndian (float val) [inline], [constexpr]
Definition at line 699 of file byte_conversions.h.
                                                                   {
  return internal::ToLittleEndian(ByteSwap(std::bit_cast<uint32_t>(val)));
}
Referenced by v8::base::numerics::TEST().
FloatToLittleEndian()
constexpr std::array<uint8_t, 4u> v8::base::FloatToLittleEndian (float val) [inline], [constexpr]
Definition at line 588 of file byte_conversions.h.
                                                                      {
  return internal::ToLittleEndian(std::bit_cast<uint32_t>(val));
}
Referenced by v8::base::numerics::TEST().
FloatToNativeEndian()
constexpr std::array<uint8_t, 4u> v8::base::FloatToNativeEndian (float val) [inline], [constexpr]
Definition at line 478 of file byte_conversions.h.
                                                                      {
  return U32ToNativeEndian(std::bit_cast<uint32_t>(val));
}
References U32ToNativeEndian().
Referenced by v8::base::numerics::TEST().
Fopen()
FILE* v8::base::Fopen (const char * filename, const char * mode) [inline]
Definition at line 14 of file wrappers.h.
                                                           {
#if V8_OS_STARBOARD
  return NULL;
#else
  return fopen(filename, mode);
#endif
}
References mode().
Referenced by v8::base::CPU::CPU(), v8::internal::InitializeICU(), v8::base::RandomNumberGenerator::RandomNumberGenerator(), v8::Shell::WriteChars(), and v8::Shell::WriteFile().
FormattedString()
v8::base::FormattedString () -> FormattedString<>
Definition at line 176 of file string-format.h.
Free()
void v8::base::Free (void * memory) [inline]
Definition at line 63 of file memory.h.
                               {
#if V8_OS_STARBOARD
  return SbMemoryDeallocate(memory);
#else // !V8_OS_STARBOARD
  return free(memory);
#endif // !V8_OS_STARBOARD
}
Referenced by cppgc::internal::anonymous_namespace{sweeper.cc}::InlinedFinalizationBuilder< FreeHandler >::AddFreeListEntry(), cppgc::internal::anonymous_namespace{sweeper.cc}::DeferredFinalizationBuilder< FreeHandler >::AddFreeListEntry(), AlignedFree(), v8::internal::StrongRootAllocatorBase::deallocate_impl(), heap::base::Worklist< EntryType, MinSegmentSize >::Segment::Delete(), v8::base::DefaultAllocationPolicy::DeleteArray(), v8::anonymous_namespace{d8.cc}::ShellArrayBufferAllocator::Free(), v8::anonymous_namespace{d8.cc}::MockArrayBufferAllocator::Free(), v8::anonymous_namespace{d8.cc}::MockArrayBufferAllocatiorWithLimit::Free(), v8::anonymous_namespace{api.cc}::ArrayBufferAllocator::Free(), v8::ValueSerializer::Delegate::FreeBufferMemory(), v8::Serializer::FreeBufferMemory(), cppgc::internal::anonymous_namespace{sweeper.cc}::DiscardingFreeHandler::FreeFreeList(), cppgc::internal::anonymous_namespace{sweeper.cc}::RegularFreeHandler::FreeFreeList(), v8::internal::FrameDescription::operator delete(), v8::internal::StringTable::Data::operator delete(), v8::internal::Malloced::operator delete(), v8::SerializationData::DataDeleter::operator()(), v8::base::FreeDeleter::operator()(), v8::internal::ExternalReferenceTable::ResolveSymbol(), v8::internal::wasm::LiftoffAssembler::~LiftoffAssembler(), and v8::internal::ValueSerializer::~ValueSerializer().
GenerateCountedDigits()
static void v8::base::GenerateCountedDigits (int count, int * decimal_point, Bignum * numerator, Bignum * denominator, Vector< char > buffer, int * length) [static]
Definition at line 232 of file bignum-dtoa.cc.
                                                                     {
  DCHECK_GE(count, 0);
  for (int i = 0; i < count - 1; ++i) {
    uint16_t digit;
    digit = numerator->DivideModuloIntBignum(*denominator);
    DCHECK_LE(digit, 9); // digit is a uint16_t and therefore always positive.
    // digit = numerator / denominator (integer division).
    // numerator = numerator % denominator.
    buffer[i] = digit + '0';
    // Prepare for next iteration.
    numerator->Times10();
  }
  // Generate the last digit.
  uint16_t digit;
  digit = numerator->DivideModuloIntBignum(*denominator);
  if (Bignum::PlusCompare(*numerator, *numerator, *denominator) >= 0) {
    digit++;
  }
  buffer[count - 1] = digit + '0';
  // Correct bad digits (in case we had a sequence of '9's). Propagate the
  // carry until we hat a non-'9' or til we reach the first digit.
  for (int i = count - 1; i > 0; --i) {
    if (buffer[i] != '0' + 10) break;
    buffer[i] = '0';
    buffer[i - 1]++;
  }
  if (buffer[0] == '0' + 10) {
    // Propagate a carry past the top place.
    buffer[0] = '1';
    (*decimal_point)++;
  }
  *length = count;
}
References DCHECK_GE, DCHECK_LE, v8::base::Bignum::DivideModuloIntBignum(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::length, v8::base::Bignum::PlusCompare(), and v8::base::Bignum::Times10().
Referenced by BignumDtoa(), and BignumToFixed().
GenerateShortestDigits()
static void v8::base::GenerateShortestDigits (Bignum * numerator, Bignum * denominator, Bignum * delta_minus, Bignum * delta_plus, bool is_even, Vector< char > buffer, int * length) [static]
Definition at line 135 of file bignum-dtoa.cc.
                                                {
  // Small optimization: if delta_minus and delta_plus are the same just reuse
  // one of the two bignums.
  if (Bignum::Equal(*delta_minus, *delta_plus)) {
    delta_plus = delta_minus;
  }
  *length = 0;
  while (true) {
    uint16_t digit;
    digit = numerator->DivideModuloIntBignum(*denominator);
    DCHECK_LE(digit, 9); // digit is a uint16_t and therefore always positive.
    // digit = numerator / denominator (integer division).
    // numerator = numerator % denominator.
    buffer[(*length)++] = digit + '0';
    // Can we stop already?
    // If the remainder of the division is less than the distance to the lower
    // boundary we can stop. In this case we simply round down (discarding the
    // remainder).
    // Similarly we test if we can round up (using the upper boundary).
    bool in_delta_room_minus;
    bool in_delta_room_plus;
    if (is_even) {
      in_delta_room_minus = Bignum::LessEqual(*numerator, *delta_minus);
    } else {
      in_delta_room_minus = Bignum::Less(*numerator, *delta_minus);
    }
    if (is_even) {
      in_delta_room_plus =
          Bignum::PlusCompare(*numerator, *delta_plus, *denominator) >= 0;
    } else {
      in_delta_room_plus =
          Bignum::PlusCompare(*numerator, *delta_plus, *denominator) > 0;
    }
    if (!in_delta_room_minus && !in_delta_room_plus) {
      // Prepare for next iteration.
      numerator->Times10();
      delta_minus->Times10();
      // We optimized delta_plus to be equal to delta_minus (if they share the
      // same value). So don't multiply delta_plus if they point to the same
      // object.
      if (delta_minus != delta_plus) {
        delta_plus->Times10();
      }
    } else if (in_delta_room_minus && in_delta_room_plus) {
      // Let's see if 2*numerator < denominator.
      // If yes, then the next digit would be < 5 and we can round down.
      int compare = Bignum::PlusCompare(*numerator, *numerator, *denominator);
      if (compare < 0) {
        // Remaining digits are less than .5. -> Round down (== do nothing).
      } else if (compare > 0) {
        // Remaining digits are more than .5 of denominator. -> Round up.
        // Note that the last digit could not be a '9' as otherwise the whole
        // loop would have stopped earlier.
        // We still have an assert here in case the preconditions were not
        // satisfied.
        DCHECK_NE(buffer[(*length) - 1], '9');
        buffer[(*length) - 1]++;
      } else {
        // Halfway case.
        // TODO(floitsch): need a way to solve half-way cases.
        // For now let's round towards even (since this is what Gay seems to
        // do).
        if ((buffer[(*length) - 1] - '0') % 2 == 0) {
          // Round down => Do nothing.
        } else {
          DCHECK_NE(buffer[(*length) - 1], '9');
          buffer[(*length) - 1]++;
        }
      }
      return;
    } else if (in_delta_room_minus) {
      // Round down (== do nothing).
      return;
    } else { // in_delta_room_plus
      // Round up.
      // Note again that the last digit could not be '9' since this would have
      // stopped the loop earlier.
      // We still have an DCHECK here, in case the preconditions were not
      // satisfied.
      DCHECK_NE(buffer[(*length) - 1], '9');
      buffer[(*length) - 1]++;
      return;
    }
  }
}
References DCHECK_LE, DCHECK_NE, v8::base::Bignum::DivideModuloIntBignum(), v8::base::Bignum::Equal(), v8::internal::length, v8::base::Bignum::Less(), v8::base::Bignum::LessEqual(), v8::base::Bignum::PlusCompare(), and v8::base::Bignum::Times10().
Referenced by BignumDtoa().
get_gmt_offset()
int64_t v8::base::get_gmt_offset (const tm & localtm)
Definition at line 39 of file platform-aix.cc.
                                          {
  // replacement for tm->tm_gmtoff field in glibc
  // returns seconds east of UTC, taking DST into account
  struct timeval tv;
  struct timezone tz;
  int ret_code = gettimeofday(&tv, &tz);
  // 0 = success, -1 = failure
  DCHECK_NE(ret_code, -1);
  if (ret_code == -1) {
    return 0;
  }
  return (-tz.tz_minuteswest * 60) + (localtm.tm_isdst > 0 ? 3600 : 0);
}
References DCHECK_NE.
Referenced by v8::base::AIXTimezoneCache::LocalTimeOffset().
GetProtectionFromMemoryPermission()
int v8::base::GetProtectionFromMemoryPermission (OS::MemoryPermission access)
Definition at line 202 of file platform-posix.cc.
                                                                 {
  switch (access) {
    case OS::MemoryPermission::kNoAccess:
    case OS::MemoryPermission::kNoAccessWillJitLater:
      return PROT_NONE;
    case OS::MemoryPermission::kRead:
      return PROT_READ;
    case OS::MemoryPermission::kReadWrite:
      return PROT_READ | PROT_WRITE;
    case OS::MemoryPermission::kReadWriteExecute:
      return PROT_READ | PROT_WRITE | PROT_EXEC;
    case OS::MemoryPermission::kReadExecute:
      return PROT_READ | PROT_EXEC;
  }
  UNREACHABLE();
}
References v8::base::OS::kNoAccess, v8::base::OS::kNoAccessWillJitLater, v8::base::OS::kRead, v8::base::OS::kReadExecute, v8::base::OS::kReadWrite, v8::base::OS::kReadWriteExecute, and UNREACHABLE.
Referenced by v8::base::OS::Allocate(), v8::base::anonymous_namespace{platform-posix.cc}::Allocate(), v8::base::anonymous_namespace{platform-fuchsia.cc}::MapVmo(), v8::base::OS::SetPermissions(), and v8::base::anonymous_namespace{platform-fuchsia.cc}::SetPermissionsInternal().
GetSharedLibraryAddresses()
V8_BASE_EXPORT std::vector< OS::SharedLibraryAddress > v8::base::GetSharedLibraryAddresses (FILE * fp)
Definition at line 242 of file platform-linux.cc.
                                                                      {
  auto regions = ParseProcSelfMaps(
      fp,
      [](const MemoryRegion& region) {
        if (region.permissions[0] == 'r' && region.permissions[1] == '-' &&
            region.permissions[2] == 'x') {
          return true;
        }
        return false;
      },
      false);
  if (!regions) return {};
  std::vector<OS::SharedLibraryAddress> result;
  for (const MemoryRegion& region : *regions) {
    uintptr_t start = region.start;
#ifdef V8_OS_ANDROID
    if (region.pathname.size() < 4 ||
        region.pathname.compare(region.pathname.size() - 4, 4, ".apk") != 0) {
      // Only adjust {start} based on {offset} if the file isn't the APK,
      // since we load the library directly from the APK and don't want to
      // apply the offset of the .so in the APK as the libraries offset.
      start -= region.offset;
    }
#else
    start -= region.offset;
#endif
    result.emplace_back(region.pathname, start, region.end);
  }
  return result;
}
References v8::base::MemoryRegion::end, v8::base::MemoryRegion::offset, v8::base::anonymous_namespace{platform-linux.cc}::ParseProcSelfMaps(), v8::base::MemoryRegion::pathname, v8::base::MemoryRegion::permissions, v8::base::internal::result, and v8::base::MemoryRegion::start.
Grisu3()
static bool v8::base::Grisu3 (double v, char ** outptr, int * decimal_exponent) [static]
Definition at line 614 of file fast-dtoa.cc.
                                                                   {
  DiyFp w = Double(v).AsNormalizedDiyFp();
  // boundary_minus and boundary_plus are the boundaries between v and its
  // closest floating-point neighbors. Any number strictly between
  // boundary_minus and boundary_plus will round to v when convert to a double.
  // Grisu3 will never output representations that lie exactly on a boundary.
  DiyFp boundary_minus, boundary_plus;
  Double(v).NormalizedBoundaries(&boundary_minus, &boundary_plus);
  DCHECK(boundary_plus.e() == w.e());
  DiyFp ten_mk; // Cached power of ten: 10^-k
  int mk; // -k
  int ten_mk_minimal_binary_exponent =
      kMinimalTargetExponent - (w.e() + DiyFp::kSignificandSize);
  int ten_mk_maximal_binary_exponent =
      kMaximalTargetExponent - (w.e() + DiyFp::kSignificandSize);
  PowersOfTenCache::GetCachedPowerForBinaryExponentRange(
      ten_mk_minimal_binary_exponent, ten_mk_maximal_binary_exponent, &ten_mk,
      &mk);
  DCHECK(
      (kMinimalTargetExponent <=
       w.e() + ten_mk.e() + DiyFp::kSignificandSize) &&
      (kMaximalTargetExponent >= w.e() + ten_mk.e() + DiyFp::kSignificandSize));
  // Note that ten_mk is only an approximation of 10^-k. A DiyFp only contains a
  // 64 bit significand and ten_mk is thus only precise up to 64 bits.
  // The DiyFp::Times procedure rounds its result, and ten_mk is approximated
  // too. The variable scaled_w (as well as scaled_boundary_minus/plus) are now
  // off by a small amount.
  // In fact: scaled_w - w*10^k < 1ulp (unit in the last place) of scaled_w.
  // In other words: let f = scaled_w.f() and e = scaled_w.e(), then
  // (f-1) * 2^e < w*10^k < (f+1) * 2^e
  DiyFp scaled_w = DiyFp::Times(w, ten_mk);
  DCHECK(scaled_w.e() ==
         boundary_plus.e() + ten_mk.e() + DiyFp::kSignificandSize);
  // In theory it would be possible to avoid some recomputations by computing
  // the difference between w and boundary_minus/plus (a power of 2) and to
  // compute scaled_boundary_minus/plus by subtracting/adding from
  // scaled_w. However the code becomes much less readable and the speed
  // enhancements are not terriffic.
  DiyFp scaled_boundary_minus = DiyFp::Times(boundary_minus, ten_mk);
  DiyFp scaled_boundary_plus = DiyFp::Times(boundary_plus, ten_mk);
  // DigitGen will generate the digits of scaled_w. Therefore we have
  // v == (double) (scaled_w * 10^-mk).
  // Set decimal_exponent == -mk and pass it to DigitGen. If scaled_w is not an
  // integer than it will be updated. For instance if scaled_w == 1.23 then
  // the buffer will be filled with "123" und the decimal_exponent will be
  // decreased by 2.
  int kappa;
  bool result = DigitGen(scaled_boundary_minus, scaled_w, scaled_boundary_plus,
                         outptr, &kappa);
  *decimal_exponent = -mk + kappa;
  return result;
}
References v8::base::Double::AsNormalizedDiyFp(), DCHECK, DigitGen(), v8::base::DiyFp::e(), v8::base::PowersOfTenCache::GetCachedPowerForBinaryExponentRange(), kMaximalTargetExponent, kMinimalTargetExponent, v8::base::DiyFp::kSignificandSize, v8::base::Double::NormalizedBoundaries(), v8::base::internal::result, and v8::base::DiyFp::Times().
Referenced by FastDtoa().
Grisu3Counted()
static bool v8::base::Grisu3Counted (double v, int requested_digits, Vector< char > buffer, int * length, int * decimal_exponent) [static]
Definition at line 674 of file fast-dtoa.cc.
                                                              {
  DiyFp w = Double(v).AsNormalizedDiyFp();
  DiyFp ten_mk; // Cached power of ten: 10^-k
  int mk; // -k
  int ten_mk_minimal_binary_exponent =
      kMinimalTargetExponent - (w.e() + DiyFp::kSignificandSize);
  int ten_mk_maximal_binary_exponent =
      kMaximalTargetExponent - (w.e() + DiyFp::kSignificandSize);
  PowersOfTenCache::GetCachedPowerForBinaryExponentRange(
      ten_mk_minimal_binary_exponent, ten_mk_maximal_binary_exponent, &ten_mk,
      &mk);
  DCHECK(
      (kMinimalTargetExponent <=
       w.e() + ten_mk.e() + DiyFp::kSignificandSize) &&
      (kMaximalTargetExponent >= w.e() + ten_mk.e() + DiyFp::kSignificandSize));
  // Note that ten_mk is only an approximation of 10^-k. A DiyFp only contains a
  // 64 bit significand and ten_mk is thus only precise up to 64 bits.
  // The DiyFp::Times procedure rounds its result, and ten_mk is approximated
  // too. The variable scaled_w (as well as scaled_boundary_minus/plus) are now
  // off by a small amount.
  // In fact: scaled_w - w*10^k < 1ulp (unit in the last place) of scaled_w.
  // In other words: let f = scaled_w.f() and e = scaled_w.e(), then
  // (f-1) * 2^e < w*10^k < (f+1) * 2^e
  DiyFp scaled_w = DiyFp::Times(w, ten_mk);
  // We now have (double) (scaled_w * 10^-mk).
  // DigitGen will generate the first requested_digits digits of scaled_w and
  // return together with a kappa such that scaled_w ~= buffer * 10^kappa. (It
  // will not always be exactly the same since DigitGenCounted only produces a
  // limited number of digits.)
  int kappa;
  bool result =
      DigitGenCounted(scaled_w, requested_digits, buffer, length, &kappa);
  *decimal_exponent = -mk + kappa;
  return result;
}
References v8::base::Double::AsNormalizedDiyFp(), DCHECK, DigitGenCounted(), v8::base::DiyFp::e(), v8::base::PowersOfTenCache::GetCachedPowerForBinaryExponentRange(), kMaximalTargetExponent, kMinimalTargetExponent, v8::base::DiyFp::kSignificandSize, v8::internal::length, v8::base::internal::result, and v8::base::DiyFp::Times().
Referenced by FastDtoa().
HasConsole()
static bool v8::base::HasConsole () [static]
Definition at line 581 of file platform-win32.cc.
                         {
  // Only check the first time. Eventual race conditions are not a problem,
  // because all threads will eventually determine the same mode.
  if (output_mode == UNKNOWN) {
    // We cannot just check that the standard output is attached to a console
    // because this would fail if output is redirected to a file. Therefore we
    // say that a process does not have an output console if either the
    // standard output handle is invalid or its file type is unknown.
    if (GetStdHandle(STD_OUTPUT_HANDLE) != INVALID_HANDLE_VALUE &&
        GetFileType(GetStdHandle(STD_OUTPUT_HANDLE)) != FILE_TYPE_UNKNOWN)
      output_mode = CONSOLE;
    else
      output_mode = ODS;
  }
  return output_mode == CONSOLE;
}
References CONSOLE, ODS, output_mode, and UNKNOWN.
Referenced by VPrintHelper().
hash_combine() [1/2]
size_t v8::base::hash_combine (size_t seed, size_t hash) [inline]
Definition at line 77 of file hashing.h.
                                                        {
#if V8_HOST_ARCH_32_BIT
  const uint32_t c1 = 0xCC9E2D51;
  const uint32_t c2 = 0x1B873593;
  hash *= c1;
  hash = bits::RotateRight32(hash, 15);
  hash *= c2;
  seed ^= hash;
  seed = bits::RotateRight32(seed, 13);
  seed = seed * 5 + 0xE6546B64;
#else
  const uint64_t m = uint64_t{0xC6A4A7935BD1E995};
  const uint32_t r = 47;
  hash *= m;
  hash ^= hash >> r;
  hash *= m;
  seed ^= hash;
  seed *= m;
#endif // V8_HOST_ARCH_32_BIT
  return seed;
}
References v8::base::bits::RotateRight32().
Referenced by v8::base::Hasher::AddHash(), v8::ScriptCompiler::CachedDataVersionTag(), v8::internal::EnumerateCompiledFunctions(), v8::internal::ScopeInfo::Hash(), v8::internal::SharedFunctionInfo::Hash(), v8::internal::Version::Hash(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::InitialMapDependency::Hash(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PrototypePropertyDependency::Hash(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::StableMapDependency::Hash(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ConstantInDictionaryPrototypeChainDependency::Hash(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDataPropertyDependency::Hash(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDoublePropertyDependency::Hash(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDictionaryPropertyDependency::Hash(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ConsistentJSFunctionViewDependency::Hash(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::TransitionDependency::Hash(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PretenureModeDependency::Hash(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldRepresentationDependency::Hash(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldTypeDependency::Hash(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldConstnessDependency::Hash(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::GlobalPropertyDependency::Hash(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ContextCellDependency::Hash(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::EmptyContextExtensionDependency::Hash(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ProtectorDependency::Hash(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ObjectSlotValueDependency::Hash(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ElementsKindDependency::Hash(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantElementDependency::Hash(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::NoSlackTrackingChangeDependency::Hash(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::InitialMapInstanceSizePredictionDependency::Hash(), v8::internal::anonymous_namespace{regexp-macro-assembler.cc}::Hash(), v8::internal::maglev::PolymorphicAccessInfo::hash_value(), v8::internal::compiler::hash_value(), v8::internal::torque::hash_value(), v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::hash_value(), v8::internal::compiler::Operator1< T, Pred, Hash >::HashCode(), v8::internal::compiler::NodeProperties::HashCode(), v8::internal::compiler::anonymous_namespace{pipeline.cc}::HashGraphForPGO(), v8::internal::Isolate::HashIsolateForEmbeddedBlob(), v8::internal::wasm::WasmImportWrapperCache::CacheKeyHash::operator()(), v8::internal::compiler::CompilationDependencies::CompilationDependencyHash::operator()(), v8::internal::compiler::PropertyAccessTarget::Hash::operator()(), v8::internal::compiler::FeedbackSource::Hash::operator()(), v8::internal::compiler::InstructionSelector::FrameStateInput::Hash::operator()(), v8::Shell::PerformanceMeasure(), v8::internal::anonymous_namespace{compilation-cache-table.cc}::ScriptHash(), v8::internal::compiler::V(), and v8::internal::compiler::turboshaft::Pipeline::VerifyGeneratedCodeIsIdempotent().
hash_combine() [2/2]
template<typename... Ts>
size_t v8::base::hash_combine (Ts const &... vs) [inline]
Definition at line 302 of file hashing.h.
                                               {
  return Hasher{}.Combine(vs...);
}
References v8::base::Hasher::Combine(), and v8::internal::vs.
hash_range()
template<typename Iterator >
size_t v8::base::hash_range (Iterator first, Iterator last) [inline]
Definition at line 308 of file hashing.h.
                                                           {
  return Hasher{}.AddRange(first, last).hash();
}
References v8::base::Hasher::AddRange(), and v8::base::Hasher::hash().
Referenced by v8::internal::ComputeFlagListHash(), hash_value(), and v8::internal::compiler::hash_value().
hash_value() [1/12]
template<typename T >
size_t v8::base::hash_value (base::Vector< T > v) [inline]
Definition at line 184 of file vector.h.
                                             {
  return hash_range(v.begin(), v.end());
}
References v8::base::Vector< T >::begin(), v8::base::Vector< T >::end(), and hash_range().
hash_value() [2/12]
size_t v8::base::hash_value (const i::Float64 & f64) [inline]
Definition at line 154 of file boxed-float.h.
                                              {
  return f64.is_nan() ? hash_value(f64.is_hole_nan())
                      : hash_value(f64.get_bits());
}
References v8::internal::Float64::get_bits(), hash_value(), v8::internal::Float64::is_hole_nan(), and v8::internal::Float64::is_nan().
hash_value() [3/12]
size_t v8::base::hash_value (const T & v) [inline]
Definition at line 281 of file hashing.h.
                                        {
  return v.hash_value();
}
hash_value() [4/12]
template<typename T , size_t N>
size_t v8::base::hash_value (const T(&) v[N]) [inline]
Definition at line 239 of file hashing.h.
                                             {
  return Hasher{}.AddRange(v, v + N).hash();
}
References v8::base::Hasher::AddRange(), v8::base::Hasher::hash(), and v8::internal::N.
hash_value() [5/12]
size_t v8::base::hash_value (double v) [inline]
Definition at line 233 of file hashing.h.
                                      {
  // 0 and -0 both hash to zero.
  return v != 0.0 ? hash_value(base::bit_cast<uint64_t>(v)) : 0;
}
References hash_value().
hash_value() [6/12]
template<typename T1 , typename T2 >
size_t v8::base::hash_value (std::pair< T1, T2 > const & v) [inline]
Definition at line 254 of file hashing.h.
                                                      {
  return Hasher::Combine(v.first, v.second);
}
References v8::base::Hasher::Combine().
hash_value() [7/12]
template<typename... T>
size_t v8::base::hash_value (std::tuple< T... > const & v) [inline]
Definition at line 265 of file hashing.h.
                                                     {
  return hash_value_impl(v, std::make_index_sequence<sizeof...(T)>());
}
References hash_value_impl().
hash_value() [8/12]
template<typename T >
size_t v8::base::hash_value (T *const & v) [inline]
Definition at line 249 of file hashing.h.
                                         {
  return hash_value(reinterpret_cast<uintptr_t>(v));
}
References hash_value().
hash_value() [9/12]
template<typename T >
size_t v8::base::hash_value (T v) [inline]
Definition at line 270 of file hashing.h.
{
  return hash_value(static_cast<std::underlying_type_t<T>>(v));
}
// Provide a hash_value function for each T with a hash_value member function.
template <typename T>
  requires requires(const T& t) {
    { t.hash_value() } -> std::convertible_to<size_t>;
  }
References hash_value().
hash_value() [10/12]
template<typename T , size_t N>
size_t v8::base::hash_value (T(&) v[N]) [inline]
Definition at line 244 of file hashing.h.
                                       {
  return Hasher{}.AddRange(v, v + N).hash();
}
References v8::base::Hasher::AddRange(), v8::base::Hasher::hash(), and v8::internal::N.
hash_value() [11/12]
size_t v8::base::hash_value (unsigned long long v) [inline]
Definition at line 213 of file hashing.h.
                                                  { // NOLINT(runtime/int)
  return hash_value_unsigned_impl(v);
}
References hash_value_unsigned_impl().
hash_value() [12/12]
size_t v8::base::hash_value (unsigned long v) [inline]
Definition at line 209 of file hashing.h.
                                             { // NOLINT(runtime/int)
  return hash_value_unsigned_impl(v);
}
References hash_value_unsigned_impl().
Referenced by v8::internal::maglev::MaglevGraphBuilder::AddNewNodeOrGetEquivalent(), v8::internal::maglev::MaglevGraphBuilder::gvn_hash_value(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PendingDependencies::HandleValueHash(), v8::internal::compiler::OptionalRef< TRef >::hash_value(), v8::internal::maglev::PolymorphicAccessInfo::hash_value(), hash_value(), v8::internal::compiler::turboshaft::hash_value(), v8::internal::compiler::hash_value(), v8::internal::interpreter::ConstantArrayBuilder::Insert(), v8::base::hash< T >::operator()(), and V8_BASE_HASH_VALUE_SIGNED().
hash_value_impl()
template<typename... T, size_t... I>
size_t v8::base::hash_value_impl (std::tuple< T... > const & v, std::index_sequence< I... >) [inline]
Definition at line 259 of file hashing.h.
                                                          {
  return Hasher::Combine(std::get<I>(v)...);
}
References v8::base::Hasher::Combine().
Referenced by hash_value().
hash_value_unsigned_impl()
template<typename T >
size_t v8::base::hash_value_unsigned_impl (T v) [inline]
Definition at line 157 of file hashing.h.
                                               {
  switch (sizeof(T)) {
    case 4: {
      // "32 bit Mix Functions"
      v = ~v + (v << 15); // v = (v << 15) - v - 1;
      v = v ^ (v >> 12);
      v = v + (v << 2);
      v = v ^ (v >> 4);
      v = v * 2057; // v = (v + (v << 3)) + (v << 11);
      v = v ^ (v >> 16);
      return static_cast<size_t>(v);
    }
    case 8: {
      switch (sizeof(size_t)) {
        case 4: {
          // "64 bit to 32 bit Hash Functions"
          v = ~v + (v << 18); // v = (v << 18) - v - 1;
          v = v ^ (v >> 31);
          v = v * 21; // v = (v + (v << 2)) + (v << 4);
          v = v ^ (v >> 11);
          v = v + (v << 6);
          v = v ^ (v >> 22);
          return static_cast<size_t>(v);
        }
        case 8: {
          // "64 bit Mix Functions"
          v = ~v + (v << 21); // v = (v << 21) - v - 1;
          v = v ^ (v >> 24);
          v = (v + (v << 3)) + (v << 8); // v * 265
          v = v ^ (v >> 14);
          v = (v + (v << 2)) + (v << 4); // v * 21
          v = v ^ (v >> 28);
          v = v + (v << 31);
          return static_cast<size_t>(v);
        }
      }
    }
  }
  UNREACHABLE();
}
References UNREACHABLE.
Referenced by hash_value(), and V8_BASE_HASH_VALUE_TRIVIAL().
HexCharOfValue()
char v8::base::HexCharOfValue (int value) [inline]
Definition at line 42 of file strings.h.
                                      {
  DCHECK(0 <= value && value <= 16);
  if (value < 10) return value + '0';
  return value - 10 + 'A';
}
References DCHECK, and v8::internal::value.
Referenced by v8::internal::anonymous_namespace{uri.cc}::AddEncodedOctetToBuffer(), v8::internal::anonymous_namespace{uri.cc}::EscapePrivate(), and v8::base::Bignum::ToHexString().
HexCharValue()
static int v8::base::HexCharValue (char c) [static]
Definition at line 96 of file bignum.cc.
                                {
  if ('0' <= c && c <= '9') return c - '0';
  if ('a' <= c && c <= 'f') return 10 + c - 'a';
  if ('A' <= c && c <= 'F') return 10 + c - 'A';
  UNREACHABLE();
}
References UNREACHABLE.
Referenced by v8::base::Bignum::AssignHexString().
HexValue()
int v8::base::HexValue (uc32 c) [inline]
Definition at line 34 of file strings.h.
                            {
  c -= '0';
  if (static_cast<unsigned>(c) <= 9) return c;
  c = (c | 0x20) - ('a' - '0'); // detect 0x11..0x16 and 0x31..0x36.
  if (static_cast<unsigned>(c) <= 5) return c + 10;
  return -1;
}
Referenced by v8::internal::JsonParser< Char >::DecodeString(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseHexEscape(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseUnlimitedLengthHexNumber(), v8::internal::Scanner::ScanHexNumber(), v8::internal::JsonParser< Char >::ScanUnicodeCharacter(), v8::internal::Scanner::ScanUnlimitedLengthHexNumber(), and v8::internal::anonymous_namespace{uri.cc}::TwoDigitHex().
I16FromBigEndian()
constexpr int16_t v8::base::I16FromBigEndian (std::span< const uint8_t, 2u > bytes) [inline], [constexpr]
Definition at line 346 of file byte_conversions.h.
                                                                            {
  return ByteSwap(internal::FromLittleEndian<int16_t>(bytes));
}
Referenced by v8::base::numerics::TEST().
I16FromLittleEndian()
constexpr int16_t v8::base::I16FromLittleEndian (std::span< const uint8_t, 2u > bytes) [inline], [constexpr]
Definition at line 228 of file byte_conversions.h.
                                      {
  return internal::FromLittleEndian<int16_t>(bytes);
}
Referenced by v8::base::numerics::TEST().
I16FromNativeEndian()
constexpr int16_t v8::base::I16FromNativeEndian (std::span< const uint8_t, 2u > bytes) [inline], [constexpr]
Definition at line 103 of file byte_conversions.h.
                                      {
  return internal::FromLittleEndian<int16_t>(bytes);
}
Referenced by v8::base::numerics::TEST().
I16ToBigEndian()
constexpr std::array<uint8_t, 2u> v8::base::I16ToBigEndian (int16_t val) [inline], [constexpr]
Definition at line 666 of file byte_conversions.h.
                                                                   {
  return internal::ToLittleEndian(ByteSwap(val));
}
Referenced by v8::base::numerics::TEST().
I16ToLittleEndian()
constexpr std::array<uint8_t, 2u> v8::base::I16ToLittleEndian (int16_t val) [inline], [constexpr]
Definition at line 555 of file byte_conversions.h.
                                                                      {
  return internal::ToLittleEndian(val);
}
Referenced by v8::base::numerics::TEST().
I16ToNativeEndian()
constexpr std::array<uint8_t, 2u> v8::base::I16ToNativeEndian (int16_t val) [inline], [constexpr]
Definition at line 448 of file byte_conversions.h.
                                                                      {
  return internal::ToLittleEndian(val);
}
Referenced by v8::base::numerics::TEST().
I32FromBigEndian()
constexpr int32_t v8::base::I32FromBigEndian (std::span< const uint8_t, 4u > bytes) [inline], [constexpr]
Definition at line 356 of file byte_conversions.h.
                                                                            {
  return ByteSwap(internal::FromLittleEndian<int32_t>(bytes));
}
Referenced by v8::base::numerics::TEST().
I32FromLittleEndian()
constexpr int32_t v8::base::I32FromLittleEndian (std::span< const uint8_t, 4u > bytes) [inline], [constexpr]
Definition at line 240 of file byte_conversions.h.
                                      {
  return internal::FromLittleEndian<int32_t>(bytes);
}
Referenced by v8::base::numerics::TEST().
I32FromNativeEndian()
constexpr int32_t v8::base::I32FromNativeEndian (std::span< const uint8_t, 4u > bytes) [inline], [constexpr]
Definition at line 114 of file byte_conversions.h.
                                      {
  return internal::FromLittleEndian<int32_t>(bytes);
}
Referenced by v8::base::numerics::TEST().
I32ToBigEndian()
constexpr std::array<uint8_t, 4u> v8::base::I32ToBigEndian (int32_t val) [inline], [constexpr]
Definition at line 677 of file byte_conversions.h.
                                                                   {
  return internal::ToLittleEndian(ByteSwap(val));
}
Referenced by v8::base::numerics::TEST().
I32ToLittleEndian()
constexpr std::array<uint8_t, 4u> v8::base::I32ToLittleEndian (int32_t val) [inline], [constexpr]
Definition at line 566 of file byte_conversions.h.
                                                                      {
  return internal::ToLittleEndian(val);
}
Referenced by v8::base::numerics::TEST().
I32ToNativeEndian()
constexpr std::array<uint8_t, 4u> v8::base::I32ToNativeEndian (int32_t val) [inline], [constexpr]
Definition at line 458 of file byte_conversions.h.
                                                                      {
  return internal::ToLittleEndian(val);
}
Referenced by v8::base::numerics::TEST().
I64FromBigEndian()
constexpr int64_t v8::base::I64FromBigEndian (std::span< const uint8_t, 8u > bytes) [inline], [constexpr]
Definition at line 366 of file byte_conversions.h.
                                                                            {
  return ByteSwap(internal::FromLittleEndian<int64_t>(bytes));
}
Referenced by v8::base::numerics::TEST().
I64FromLittleEndian()
constexpr int64_t v8::base::I64FromLittleEndian (std::span< const uint8_t, 8u > bytes) [inline], [constexpr]
Definition at line 252 of file byte_conversions.h.
                                      {
  return internal::FromLittleEndian<int64_t>(bytes);
}
Referenced by v8::base::numerics::TEST().
I64FromNativeEndian()
constexpr int64_t v8::base::I64FromNativeEndian (std::span< const uint8_t, 8u > bytes) [inline], [constexpr]
Definition at line 125 of file byte_conversions.h.
                                      {
  return internal::FromLittleEndian<int64_t>(bytes);
}
Referenced by v8::base::numerics::TEST().
I64ToBigEndian()
constexpr std::array<uint8_t, 8u> v8::base::I64ToBigEndian (int64_t val) [inline], [constexpr]
Definition at line 688 of file byte_conversions.h.
                                                                   {
  return internal::ToLittleEndian(ByteSwap(val));
}
Referenced by v8::base::numerics::TEST().
I64ToLittleEndian()
constexpr std::array<uint8_t, 8u> v8::base::I64ToLittleEndian (int64_t val) [inline], [constexpr]
Definition at line 577 of file byte_conversions.h.
                                                                      {
  return internal::ToLittleEndian(val);
}
Referenced by v8::base::numerics::TEST().
I64ToNativeEndian()
constexpr std::array<uint8_t, 8u> v8::base::I64ToNativeEndian (int64_t val) [inline], [constexpr]
Definition at line 468 of file byte_conversions.h.
                                                                      {
  return internal::ToLittleEndian(val);
}
Referenced by v8::base::numerics::TEST().
I8FromBigEndian()
constexpr int8_t v8::base::I8FromBigEndian (std::span< const uint8_t, 1u > bytes) [inline], [constexpr]
Definition at line 336 of file byte_conversions.h.
                                                                          {
  return static_cast<int8_t>(bytes[0]);
}
Referenced by v8::base::numerics::TEST().
I8FromLittleEndian()
constexpr int8_t v8::base::I8FromLittleEndian (std::span< const uint8_t, 1u > bytes) [inline], [constexpr]
Definition at line 217 of file byte_conversions.h.
                                                                             {
  return static_cast<int8_t>(bytes[0]);
}
Referenced by v8::base::numerics::TEST().
I8FromNativeEndian()
constexpr int8_t v8::base::I8FromNativeEndian (std::span< const uint8_t, 1u > bytes) [inline], [constexpr]
Definition at line 93 of file byte_conversions.h.
                                                                             {
  return static_cast<int8_t>(bytes[0]);
}
Referenced by v8::base::numerics::TEST().
I8ToBigEndian()
constexpr std::array<uint8_t, 1u> v8::base::I8ToBigEndian (int8_t val) [inline], [constexpr]
Definition at line 655 of file byte_conversions.h.
                                                                 {
  return {static_cast<uint8_t>(val)};
}
Referenced by v8::base::numerics::TEST().
I8ToLittleEndian()
constexpr std::array<uint8_t, 1u> v8::base::I8ToLittleEndian (int8_t val) [inline], [constexpr]
Definition at line 544 of file byte_conversions.h.
                                                                    {
  return {static_cast<uint8_t>(val)};
}
Referenced by v8::base::numerics::TEST().
I8ToNativeEndian()
constexpr std::array<uint8_t, 1u> v8::base::I8ToNativeEndian (int8_t val) [inline], [constexpr]
Definition at line 438 of file byte_conversions.h.
                                                                    {
  return {static_cast<uint8_t>(val)};
}
Referenced by v8::base::numerics::TEST().
index_of()
template<typename C , typename T >
std::optional<size_t> v8::base::index_of (const C & container, const T & element)
Definition at line 27 of file container-utils.h.
                                                                   {
  const auto b = std::begin(container);
  const auto e = std::end(container);
  if (auto it = std::find(b, e, element); it != e) {
    return {std::distance(b, it)};
  }
  return std::nullopt;
}
References v8::internal::compiler::begin(), and v8::internal::compiler::end().
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::ComputePredecessorPermutations().
index_of_if()
template<typename C , typename P >
std::optional<size_t> v8::base::index_of_if (const C & container, const P & predicate)
Definition at line 39 of file container-utils.h.
                                                                        {
  const auto b = std::begin(container);
  const auto e = std::end(container);
  if (auto it = std::find_if(b, e, predicate); it != e) {
    return {std::distance(b, it)};
  }
  return std::nullopt;
}
References v8::internal::compiler::begin(), and v8::internal::compiler::end().
InitialScaledStartValues()
static void v8::base::InitialScaledStartValues (double v, int estimated_power, bool need_boundary_deltas, Bignum * numerator, Bignum * denominator, Bignum * delta_minus, Bignum * delta_plus) [static]
Definition at line 547 of file bignum-dtoa.cc.
                                                                              {
  if (Double(v).Exponent() >= 0) {
    InitialScaledStartValuesPositiveExponent(
        v, estimated_power, need_boundary_deltas, numerator, denominator,
        delta_minus, delta_plus);
  } else if (estimated_power >= 0) {
    InitialScaledStartValuesNegativeExponentPositivePower(
        v, estimated_power, need_boundary_deltas, numerator, denominator,
        delta_minus, delta_plus);
  } else {
    InitialScaledStartValuesNegativeExponentNegativePower(
        v, estimated_power, need_boundary_deltas, numerator, denominator,
        delta_minus, delta_plus);
  }
}
References InitialScaledStartValuesNegativeExponentNegativePower(), InitialScaledStartValuesNegativeExponentPositivePower(), and InitialScaledStartValuesPositiveExponent().
Referenced by BignumDtoa().
InitialScaledStartValuesNegativeExponentNegativePower()
static void v8::base::InitialScaledStartValuesNegativeExponentNegativePower (double v, int estimated_power, bool need_boundary_deltas, Bignum * numerator, Bignum * denominator, Bignum * delta_minus, Bignum * delta_plus) [static]
Definition at line 454 of file bignum-dtoa.cc.
                                                                  {
  const uint64_t kMinimalNormalizedExponent = 0x0010'0000'0000'0000;
  uint64_t significand = Double(v).Significand();
  int exponent = Double(v).Exponent();
  // Instead of multiplying the denominator with 10^estimated_power we
  // multiply all values (numerator and deltas) by 10^-estimated_power.
  // Use numerator as temporary container for power_ten.
  Bignum* power_ten = numerator;
  power_ten->AssignPowerUInt16(10, -estimated_power);
  if (need_boundary_deltas) {
    // Since power_ten == numerator we must make a copy of 10^estimated_power
    // before we complete the computation of the numerator.
    // delta_plus = delta_minus = 10^estimated_power
    delta_plus->AssignBignum(*power_ten);
    delta_minus->AssignBignum(*power_ten);
  }
  // numerator = significand * 2 * 10^-estimated_power
  // since v = significand * 2^exponent this is equivalent to
  // numerator = v * 10^-estimated_power * 2 * 2^-exponent.
  // Remember: numerator has been abused as power_ten. So no need to assign it
  // to itself.
  DCHECK(numerator == power_ten);
  numerator->MultiplyByUInt64(significand);
  // denominator = 2 * 2^-exponent with exponent < 0.
  denominator->AssignUInt16(1);
  denominator->ShiftLeft(-exponent);
  if (need_boundary_deltas) {
    // Introduce a common denominator so that the deltas to the boundaries are
    // integers.
    numerator->ShiftLeft(1);
    denominator->ShiftLeft(1);
    // With this shift the boundaries have their correct value, since
    // delta_plus = 10^-estimated_power, and
    // delta_minus = 10^-estimated_power.
    // These assignments have been done earlier.
    // The special case where the lower boundary is twice as close.
    // This time we have to look out for the exception too.
    uint64_t v_bits = Double(v).AsUint64();
    if ((v_bits & Double::kSignificandMask) == 0 &&
        // The only exception where a significand == 0 has its boundaries at
        // "normal" distances:
        (v_bits & Double::kExponentMask) != kMinimalNormalizedExponent) {
      numerator->ShiftLeft(1); // *2
      denominator->ShiftLeft(1); // *2
      delta_plus->ShiftLeft(1); // *2
    }
  }
}
References v8::base::Bignum::AssignBignum(), v8::base::Bignum::AssignPowerUInt16(), v8::base::Bignum::AssignUInt16(), v8::base::Double::AsUint64(), DCHECK, v8::base::Double::Exponent(), v8::base::Double::kExponentMask, v8::base::Double::kSignificandMask, v8::base::Bignum::MultiplyByUInt64(), v8::base::Bignum::ShiftLeft(), and v8::base::Double::Significand().
Referenced by InitialScaledStartValues().
InitialScaledStartValuesNegativeExponentPositivePower()
static void v8::base::InitialScaledStartValuesNegativeExponentPositivePower (double v, int estimated_power, bool need_boundary_deltas, Bignum * numerator, Bignum * denominator, Bignum * delta_minus, Bignum * delta_plus) [static]
Definition at line 406 of file bignum-dtoa.cc.
                                                                  {
  uint64_t significand = Double(v).Significand();
  int exponent = Double(v).Exponent();
  // v = f * 2^e with e < 0, and with estimated_power >= 0.
  // This means that e is close to 0 (have a look at how estimated_power is
  // computed).
  // numerator = significand
  // since v = significand * 2^exponent this is equivalent to
  // numerator = v * / 2^-exponent
  numerator->AssignUInt64(significand);
  // denominator = 10^estimated_power * 2^-exponent (with exponent < 0)
  denominator->AssignPowerUInt16(10, estimated_power);
  denominator->ShiftLeft(-exponent);
  if (need_boundary_deltas) {
    // Introduce a common denominator so that the deltas to the boundaries are
    // integers.
    denominator->ShiftLeft(1);
    numerator->ShiftLeft(1);
    // Let v = f * 2^e, then m+ - v = 1/2 * 2^e; With the common
    // denominator (of 2) delta_plus equals 2^e.
    // Given that the denominator already includes v's exponent the distance
    // to the boundaries is simply 1.
    delta_plus->AssignUInt16(1);
    // Same for delta_minus (with adjustments below if f == 2^p-1).
    delta_minus->AssignUInt16(1);
    // If the significand (without the hidden bit) is 0, then the lower
    // boundary is closer than just one ulp (unit in the last place).
    // There is only one exception: if the next lower number is a denormal
    // then the distance is 1 ulp. Since the exponent is close to zero
    // (otherwise estimated_power would have been negative) this cannot happen
    // here either.
    uint64_t v_bits = Double(v).AsUint64();
    if ((v_bits & Double::kSignificandMask) == 0) {
      // The lower boundary is closer at half the distance of "normal" numbers.
      // Increase the denominator and adapt all but the delta_minus.
      denominator->ShiftLeft(1); // *2
      numerator->ShiftLeft(1); // *2
      delta_plus->ShiftLeft(1); // *2
    }
  }
}
References v8::base::Bignum::AssignPowerUInt16(), v8::base::Bignum::AssignUInt16(), v8::base::Bignum::AssignUInt64(), v8::base::Double::AsUint64(), v8::base::Double::Exponent(), v8::base::Double::kSignificandMask, v8::base::Bignum::ShiftLeft(), and v8::base::Double::Significand().
Referenced by InitialScaledStartValues().
InitialScaledStartValuesPositiveExponent()
static void v8::base::InitialScaledStartValuesPositiveExponent (double v, int estimated_power, bool need_boundary_deltas, Bignum * numerator, Bignum * denominator, Bignum * delta_minus, Bignum * delta_plus) [static]
Definition at line 362 of file bignum-dtoa.cc.
                                                                  {
  // A positive exponent implies a positive power.
  DCHECK_GE(estimated_power, 0);
  // Since the estimated_power is positive we simply multiply the denominator
  // by 10^estimated_power.
  // numerator = v.
  numerator->AssignUInt64(Double(v).Significand());
  numerator->ShiftLeft(Double(v).Exponent());
  // denominator = 10^estimated_power.
  denominator->AssignPowerUInt16(10, estimated_power);
  if (need_boundary_deltas) {
    // Introduce a common denominator so that the deltas to the boundaries are
    // integers.
    denominator->ShiftLeft(1);
    numerator->ShiftLeft(1);
    // Let v = f * 2^e, then m+ - v = 1/2 * 2^e; With the common
    // denominator (of 2) delta_plus equals 2^e.
    delta_plus->AssignUInt16(1);
    delta_plus->ShiftLeft(Double(v).Exponent());
    // Same for delta_minus (with adjustments below if f == 2^p-1).
    delta_minus->AssignUInt16(1);
    delta_minus->ShiftLeft(Double(v).Exponent());
    // If the significand (without the hidden bit) is 0, then the lower
    // boundary is closer than just half a ulp (unit in the last place).
    // There is only one exception: if the next lower number is a denormal then
    // the distance is 1 ulp. This cannot be the case for exponent >= 0 (but we
    // have to test it in the other function where exponent < 0).
    uint64_t v_bits = Double(v).AsUint64();
    if ((v_bits & Double::kSignificandMask) == 0) {
      // The lower boundary is closer at half the distance of "normal" numbers.
      // Increase the common denominator and adapt all but the delta_minus.
      denominator->ShiftLeft(1); // *2
      numerator->ShiftLeft(1); // *2
      delta_plus->ShiftLeft(1); // *2
    }
  }
}
References v8::base::Bignum::AssignPowerUInt16(), v8::base::Bignum::AssignUInt16(), v8::base::Bignum::AssignUInt64(), v8::base::Double::AsUint64(), DCHECK_GE, v8::base::Double::kSignificandMask, and v8::base::Bignum::ShiftLeft().
Referenced by InitialScaledStartValues().
IsApproximatelyEqual()
template<typename T >
constexpr bool v8::base::IsApproximatelyEqual (T lhs, T rhs, T tolerance) [constexpr]
Definition at line 17 of file ranges.h.
                                                               {
  static_assert(std::is_arithmetic_v<T>, "Argument must be arithmetic");
  return std::abs(rhs - lhs) <= tolerance;
}
IsSubset()
V8_BASE_EXPORT bool v8::base::IsSubset (PagePermissions lhs, PagePermissions rhs)
Definition at line 47 of file virtual-address-space.cc.
                                                        {
  uint8_t lhs_bits = PagePermissionsToBitset(lhs);
  uint8_t rhs_bits = PagePermissionsToBitset(rhs);
  return (lhs_bits & rhs_bits) == lhs_bits;
}
References v8::base::anonymous_namespace{virtual-address-space.cc}::PagePermissionsToBitset().
Referenced by v8::base::VirtualAddressSubspace::AllocatePages(), v8::base::VirtualAddressSubspace::AllocateSubspace(), v8::base::VirtualAddressSubspace::RecommitPages(), and v8::base::VirtualAddressSubspace::SetPagePermissions().
IterateWithoutFirst() [1/2]
template<typename T >
auto v8::base::IterateWithoutFirst (const iterator_range< T > & t)
Definition at line 150 of file iterator.h.
                                                     {
  iterator_range<T> range_copy = {t.begin(), t.end()};
  return IterateWithoutFirst(range_copy);
}
References v8::base::iterator_range< ForwardIterator >::begin(), v8::base::iterator_range< ForwardIterator >::end(), and IterateWithoutFirst().
IterateWithoutFirst() [2/2]
template<typename T >
auto v8::base::IterateWithoutFirst (T & t)
Definition at line 143 of file iterator.h.
                               {
  DCHECK_NE(std::begin(t), std::end(t));
  auto new_begin = std::begin(t);
  return make_iterator_range(++new_begin, std::end(t));
}
References v8::internal::compiler::begin(), DCHECK_NE, v8::internal::compiler::end(), and make_iterator_range().
Referenced by v8::internal::interpreter::BytecodeGenerator::ControlScope::DeferredCommands::ApplyDeferredCommands(), and IterateWithoutFirst().
IterateWithoutLast() [1/2]
template<typename T >
auto v8::base::IterateWithoutLast (const iterator_range< T > & t)
Definition at line 134 of file iterator.h.
                                                    {
  iterator_range<T> range_copy = {t.begin(), t.end()};
  return IterateWithoutLast(range_copy);
}
References v8::base::iterator_range< ForwardIterator >::begin(), v8::base::iterator_range< ForwardIterator >::end(), and IterateWithoutLast().
IterateWithoutLast() [2/2]
template<typename T >
auto v8::base::IterateWithoutLast (T & t)
Definition at line 127 of file iterator.h.
                              {
  DCHECK_NE(std::begin(t), std::end(t));
  auto new_end = std::end(t);
  return make_iterator_range(std::begin(t), --new_end);
}
References v8::internal::compiler::begin(), DCHECK_NE, v8::internal::compiler::end(), and make_iterator_range().
Referenced by v8::internal::compiler::turboshaft::IfElseCascadeToSwitchReducer< Next >::ContainsOnlyPureOps(), v8::internal::compiler::turboshaft::IfElseCascadeToSwitchReducer< Next >::InlineAllOperationsWithoutLast(), IterateWithoutLast(), and v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitBlockBody().
LoadDbgHelpAndTlHelp32()
static bool v8::base::LoadDbgHelpAndTlHelp32 () [static]
Definition at line 1542 of file platform-win32.cc.
                                     {
  static bool dbghelp_loaded = false;
  if (dbghelp_loaded) return true;
  HMODULE module;
  // Load functions from the dbghelp.dll module.
  module = LoadLibrary(TEXT("dbghelp.dll"));
  if (module == nullptr) {
    return false;
  }
#define LOAD_DLL_FUNC(name) \
  DLL_FUNC_VAR(name) = \
      reinterpret_cast<DLL_FUNC_TYPE(name)>(GetProcAddress(module, #name));
DBGHELP_FUNCTION_LIST(LOAD_DLL_FUNC)
#undef LOAD_DLL_FUNC
  // Load functions from the kernel32.dll module (the TlHelp32.h function used
  // to be in tlhelp32.dll but are now moved to kernel32.dll).
  module = LoadLibrary(TEXT("kernel32.dll"));
  if (module == nullptr) {
    return false;
  }
#define LOAD_DLL_FUNC(name) \
  DLL_FUNC_VAR(name) = \
      reinterpret_cast<DLL_FUNC_TYPE(name)>(GetProcAddress(module, #name));
TLHELP32_FUNCTION_LIST(LOAD_DLL_FUNC)
#undef LOAD_DLL_FUNC
  // Check that all functions where loaded.
bool result =
#define DLL_FUNC_LOADED(name) (DLL_FUNC_VAR(name) != nullptr)&&
    DBGHELP_FUNCTION_LIST(DLL_FUNC_LOADED)
        TLHELP32_FUNCTION_LIST(DLL_FUNC_LOADED)
#undef DLL_FUNC_LOADED
            true;
  dbghelp_loaded = result;
  return result;
  // NOTE: The modules are never unloaded and will stay around until the
  // application is closed.
}
References DBGHELP_FUNCTION_LIST, DLL_FUNC_LOADED, LOAD_DLL_FUNC, v8::base::internal::result, and TLHELP32_FUNCTION_LIST.
LoadSymbols()
static std::vector<OS::SharedLibraryAddress> v8::base::LoadSymbols (HANDLE process_handle) [static]
Definition at line 1601 of file platform-win32.cc.
                           {
  static std::vector<OS::SharedLibraryAddress> result;
  static bool symbols_loaded = false;
  if (symbols_loaded) return result;
  BOOL ok;
  // Initialize the symbol engine.
  ok = _SymInitialize(process_handle, // hProcess
                      nullptr, // UserSearchPath
                      false); // fInvadeProcess
  if (!ok) return result;
  DWORD options = _SymGetOptions();
  options |= SYMOPT_LOAD_LINES;
  options |= SYMOPT_FAIL_CRITICAL_ERRORS;
  options = _SymSetOptions(options);
  char buf[OS::kStackWalkMaxNameLen] = {0};
  ok = _SymGetSearchPath(process_handle, buf, OS::kStackWalkMaxNameLen);
  if (!ok) {
    int err = GetLastError();
    OS::Print("%d\n", err);
    return result;
  }
  HANDLE snapshot = _CreateToolhelp32Snapshot(
      TH32CS_SNAPMODULE, // dwFlags
      GetCurrentProcessId()); // th32ProcessId
  if (snapshot == INVALID_HANDLE_VALUE) return result;
  MODULEENTRY32W module_entry;
  module_entry.dwSize = sizeof(module_entry); // Set the size of the structure.
  BOOL cont = _Module32FirstW(snapshot, &module_entry);
  while (cont) {
    DWORD64 base;
    // NOTE the SymLoadModule64 function has the peculiarity of accepting a
    // both unicode and ASCII strings even though the parameter is PSTR.
    base = _SymLoadModule64(
        process_handle, // hProcess
        0, // hFile
        reinterpret_cast<PSTR>(module_entry.szExePath), // ImageName
        reinterpret_cast<PSTR>(module_entry.szModule), // ModuleName
        reinterpret_cast<DWORD64>(module_entry.modBaseAddr), // BaseOfDll
        module_entry.modBaseSize); // SizeOfDll
    if (base == 0) {
      int err = GetLastError();
      if (err != ERROR_MOD_NOT_FOUND &&
          err != ERROR_INVALID_HANDLE) {
        result.clear();
        return result;
      }
    }
    int lib_name_length = WideCharToMultiByte(
        CP_UTF8, 0, module_entry.szExePath, -1, nullptr, 0, nullptr, nullptr);
    std::string lib_name(lib_name_length, 0);
    WideCharToMultiByte(CP_UTF8, 0, module_entry.szExePath, -1, &lib_name[0],
                        lib_name_length, nullptr, nullptr);
    result.push_back(OS::SharedLibraryAddress(
        lib_name, reinterpret_cast<uintptr_t>(module_entry.modBaseAddr),
        reinterpret_cast<uintptr_t>(module_entry.modBaseAddr +
                                    module_entry.modBaseSize)));
    cont = _Module32NextW(snapshot, &module_entry);
  }
  CloseHandle(snapshot);
  symbols_loaded = true;
  return result;
}
References v8::base::OS::GetCurrentProcessId(), v8::base::OS::GetLastError(), v8::base::OS::kStackWalkMaxNameLen, v8::internal::Print(), v8::base::internal::result, and v8::internal::string.
LocalKeyToPthreadKey()
static pthread_key_t v8::base::LocalKeyToPthreadKey (Thread::LocalStorageKey local_key) [static]
Definition at line 1327 of file platform-posix.cc.
                                                                           {
#if V8_OS_CYGWIN
  static_assert(sizeof(Thread::LocalStorageKey) == sizeof(pthread_key_t));
  intptr_t ptr_key = static_cast<intptr_t>(local_key);
  return reinterpret_cast<pthread_key_t>(ptr_key);
#else
  return static_cast<pthread_key_t>(local_key);
#endif
}
Referenced by v8::base::Thread::DeleteThreadLocalKey(), v8::base::Thread::GetThreadLocal(), and v8::base::Thread::SetThreadLocal().
LocalTimeOffset()
double v8::base::LocalTimeOffset (double time_ms, bool is_utc)
Definition at line 86 of file platform-cygwin.cc.
                                                    {
  // On Cygwin, struct tm does not contain a tm_gmtoff field.
  time_t utc = time(nullptr);
  DCHECK_NE(utc, -1);
  struct tm tm;
  struct tm* loc = localtime_r(&utc, &tm);
  DCHECK_NOT_NULL(loc);
  // time - localtime includes any daylight savings offset, so subtract it.
  return static_cast<double>((mktime(loc) - utc) * msPerSecond -
                             (loc->tm_isdst > 0 ? 3600 * msPerSecond : 0));
}
References DCHECK_NE, DCHECK_NOT_NULL, v8::internal::loc, and time().
make_array()
template<std::size_t Size, class Function >
constexpr auto v8::base::make_array (Function f) [constexpr]
Definition at line 38 of file template-utils.h.
                                      {
  return detail::make_array_helper(f, std::make_index_sequence<Size>{});
}
References v8::base::detail::make_array_helper().
make_iterator_range()
template<typename ForwardIterator >
auto v8::base::make_iterator_range (ForwardIterator begin, ForwardIterator end)
Definition at line 65 of file iterator.h.
                                                                     {
  return iterator_range<ForwardIterator>{begin, end};
}
References v8::internal::compiler::begin(), and v8::internal::compiler::end().
Referenced by v8::internal::maglev::Call::args(), v8::internal::maglev::Construct::args(), v8::internal::maglev::CallCPPBuiltin::args(), v8::internal::maglev::CallForwardVarargs::args(), v8::internal::maglev::CallRuntime::args(), v8::internal::maglev::CallSelf::args(), v8::internal::maglev::CallKnownJSFunction::args(), v8::internal::maglev::CallKnownApiFunction::args(), v8::internal::maglev::CallWithSpread::args_no_spread(), v8::internal::maglev::ConstructWithSpread::args_no_spread(), v8::internal::wasm::DebugSideTable::entries(), v8::base::bits::IterateBits(), v8::base::bits::IterateBitsBackwards(), IterateWithoutFirst(), IterateWithoutLast(), v8::internal::maglev::detail::PushAllHelper< Arg1, Arg2, Args... >::Push(), v8::internal::maglev::detail::PushAllHelper< Arg1, Arg2, Args... >::PushReverse(), v8::internal::maglev::RepeatValue(), Reversed(), v8::internal::maglev::CallBuiltin::stack_args(), v8::internal::compiler::UnrollLoop(), and zip().
MakeCheckOpString()
template<typename Lhs , typename Rhs >
V8_NOINLINE std::string* v8::base::MakeCheckOpString (Lhs lhs, Rhs rhs, char const * msg)
Definition at line 301 of file logging.h.
                                                                            {
  std::string lhs_str = PrintCheckOperand<Lhs>(lhs);
  std::string rhs_str = PrintCheckOperand<Rhs>(rhs);
  CheckMessageStream ss;
  ss << msg;
  constexpr size_t kMaxInlineLength = 50;
  if (lhs_str.size() <= kMaxInlineLength &&
      rhs_str.size() <= kMaxInlineLength) {
    ss << " (" << lhs_str << " vs. " << rhs_str << ")";
  } else {
    ss << "\n " << lhs_str << "\n vs.\n " << rhs_str << "\n";
  }
  return new std::string(ss.str());
}
References v8::internal::string.
Malloc()
void* v8::base::Malloc (size_t size) [inline]
Definition at line 36 of file memory.h.
                                 {
#if V8_OS_STARBOARD
  return SbMemoryAllocate(size);
#elif V8_OS_AIX && _LINUX_SOURCE_COMPAT
  // Work around for GCC bug on AIX.
  // See: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=79839
  return __linux_malloc(size);
#else
  return malloc(size);
#endif
}
References size().
Referenced by __sanitizer_cov_trace_pc_guard_init(), v8::internal::StrongRootAllocatorBase::allocate_impl(), v8::base::DefaultAllocationPolicy::AllocateArray(), AllocateAtLeast(), v8::anonymous_namespace{api.cc}::ArrayBufferAllocator::AllocateUninitialized(), heap::base::Worklist< EntryType, MinSegmentSize >::Segment::Create(), v8::internal::FrameDescription::operator new(), and v8::internal::wasm::LiftoffAssembler::set_num_locals().
Memory() [1/2]
template<class T >
T& v8::base::Memory (Address addr) [inline]
Definition at line 18 of file memory.h.
                               {
  DCHECK(IsAligned(addr, alignof(T)));
  return *reinterpret_cast<T*>(addr);
}
References DCHECK, and IsAligned().
Memory() [2/2]
template<class T >
T& v8::base::Memory (uint8_t * addr) [inline]
Definition at line 23 of file memory.h.
                                {
  return Memory<T>(reinterpret_cast<Address>(addr));
}
MulWithWraparound()
template<>
int16_t v8::base::MulWithWraparound (int16_t a, int16_t b) [inline]
Definition at line 41 of file overflowing-math.h.
                                                       {
  uint32_t a_unsigned = static_cast<uint32_t>(a);
  uint32_t b_unsigned = static_cast<uint32_t>(b);
  uint32_t result = a_unsigned * b_unsigned;
  return static_cast<int16_t>(static_cast<uint16_t>(result));
}
References v8::base::internal::result.
Referenced by v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction(), v8::internal::compiler::MachineOperatorReducer::Reduce(), and v8::internal::compiler::MachineOperatorReducer::ReduceInt64Mul().
NegateWithWraparound()
template<typename signed_type >
signed_type v8::base::NegateWithWraparound (signed_type a) [inline]
Definition at line 51 of file overflowing-math.h.
                                                       {
  ASSERT_SIGNED_INTEGER_TYPE(signed_type);
  if (a == std::numeric_limits<signed_type>::min()) return a;
  return -a;
}
References ASSERT_SIGNED_INTEGER_TYPE.
Referenced by v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction(), v8::internal::Smi::LexicographicCompare(), v8::internal::compiler::MachineOperatorReducer::ReduceInt32Sub(), v8::internal::compiler::MachineOperatorReducer::ReduceInt64Sub(), v8::internal::compiler::MachineOperatorReducer::ReduceWordNAnd(), and v8::internal::wasm::AsmJsParser::UnaryExpression().
none_of()
template<typename C , typename P >
bool v8::base::none_of (const C & container, const P & predicate) [inline]
Definition at line 105 of file container-utils.h.
                                                            {
  return std::none_of(std::begin(container), std::end(container), predicate);
}
References v8::internal::compiler::begin(), and v8::internal::compiler::end().
Referenced by v8::internal::wasm::TypeCanonicalizer::AddRecursiveGroup(), v8::internal::wasm::TypeCanonicalizer::AddRecursiveSingletonGroup(), v8::internal::compiler::turboshaft::WasmShuffleAnalyzer::ProcessShuffleOfShuffle(), v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewAccessor(), v8::internal::compiler::turboshaft::FloatType< Bits >::Set(), and v8::internal::compiler::turboshaft::Simd128UseMap::Simd128UseMap().
NormalizedExponent()
static int v8::base::NormalizedExponent (uint64_t significand, int exponent) [static]
Definition at line 16 of file bignum-dtoa.cc.
                                                                  {
  DCHECK_NE(significand, 0);
  while ((significand & Double::kHiddenBit) == 0) {
    significand = significand << 1;
    exponent = exponent - 1;
  }
  return exponent;
}
References DCHECK_NE, and v8::base::Double::kHiddenBit.
Referenced by BignumDtoa().
OneByteVector() [1/2]
Vector<const uint8_t> v8::base::OneByteVector (const char * data) [inline]
Definition at line 340 of file vector.h.
                                                             {
  return OneByteVector(data, strlen(data));
}
References OneByteVector().
OneByteVector() [2/2]
Vector<const uint8_t> v8::base::OneByteVector (const char * data, size_t length) [inline]
Definition at line 336 of file vector.h.
                                                                            {
  return {reinterpret_cast<const uint8_t*>(data), length};
}
References v8::internal::length.
Referenced by v8::internal::Heap::CreateReadOnlyObjects(), v8::internal::Parser::GetNumberAsSymbol(), v8::internal::AstValueFactory::GetOneByteString(), v8::internal::Factory::InternalizeString(), v8::internal::anonymous_namespace{runtime-regexp.cc}::IsContainFlagImpl(), v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), OneByteVector(), StaticOneByteVector(), v8::internal::compiler::CodeAssembler::StringConstant(), v8::internal::JsonStringifier::Stringify(), and v8::internal::StringToDouble().
operator+() [1/2]
Time v8::base::operator+ (const TimeDelta & delta, const Time & time) [inline]
Definition at line 377 of file time.h.
                                                                {
  return time + delta;
}
References time().
operator+() [2/2]
TimeTicks v8::base::operator+ (const TimeDelta & delta, const TimeTicks & ticks) [inline]
Definition at line 419 of file time.h.
                                                                           {
  return ticks + delta;
}
operator<<() [1/4]
V8_BASE_EXPORT std::ostream & v8::base::operator<< (std::ostream & os, const Time & time)
Definition at line 515 of file time.cc.
                                                         {
  return os << time.ToJsTime();
}
References time().
operator<<() [2/4]
template<typename E , typename T >
std::ostream& v8::base::operator<< (std::ostream & os, EnumSet< E, T > set)
Definition at line 104 of file enum-set.h.
                                                          {
  os << "{";
  bool first = true;
  while (!set.empty()) {
    if (!first) os << ", ";
    first = false;
    T bits = set.ToIntegral();
    E element = static_cast<E>(bits::CountTrailingZerosNonZero(bits));
    os << element;
    set.Remove(element);
  }
  os << "}";
  return os;
}
References v8::base::bits::CountTrailingZerosNonZero(), v8::base::EnumSet< E, T >::empty(), v8::base::EnumSet< E, T >::Remove(), and v8::base::EnumSet< E, T >::ToIntegral().
operator<<() [3/4]
std::ostream& v8::base::operator<< (std::ostream & out, AddressRegion region) [inline]
Definition at line 88 of file address-region.h.
                                                                     {
  return out << "[" << reinterpret_cast<void*>(region.begin()) << "+"
             << region.size() << "]";
}
References v8::base::AddressRegion::begin(), and v8::base::AddressRegion::size().
operator<<() [4/4]
std::ostream& v8::base::operator<< (std::ostream & stream, const StrongAlias< TagType, UnderlyingType > & alias)
Definition at line 134 of file strong-alias.h.
                                                                            {
  return stream << alias.value();
}
References v8::base::StrongAlias< TagType, UnderlyingType >::value().
operator==()
template<typename PointerType , typename PayloadType , int NumPayloadBits>
bool v8::base::operator== (PointerWithPayload< PointerType, PayloadType, NumPayloadBits > lhs, PointerWithPayload< PointerType, PayloadType, NumPayloadBits > rhs)
Definition at line 118 of file pointer-with-payload.h.
                                                                      {
  return lhs.raw() == rhs.raw();
}
References v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::raw().
Referenced by EXPORT_TEMPLATE_DECLARE().
OwnedCopyOf() [1/2]
template<typename Container >
auto v8::base::OwnedCopyOf (const Container & c) -> decltype(OwnedCopyOf(std::data(c), std::size(c))) [inline]
Definition at line 390 of file vector.h.
                                                     {
  return OwnedCopyOf(std::data(c), std::size(c));
}
References OwnedCopyOf(), and size().
OwnedCopyOf() [2/2]
template<typename T >
OwnedVector<T> v8::base::OwnedCopyOf (const T * data, size_t size) [inline]
Definition at line 382 of file vector.h.
                                                              {
  return OwnedVector<T>::NewByCopying(data, size);
}
References v8::base::OwnedVector< T >::NewByCopying(), and size().
Referenced by v8::internal::wasm::NativeModule::AddCodeForTesting(), v8::internal::BUILTIN(), v8::WasmModuleObject::Compile(), v8::internal::CreateWasmObject(), v8::internal::wasm::DeserializeNativeModule(), v8::internal::AsmJsCompilationJob::FinalizeJobImpl(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::FinishFunction(), v8::internal::wasm::ProfileGenerator::GetProfileData(), v8::internal::compiler::CodeGenerator::GetProtectedInstructionsData(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GetProtectedInstructionsData(), OwnedCopyOf(), and v8::internal::wasm::WasmFunctionCoverageData::WasmFunctionCoverageData().
PosixInitializeCommon()
void v8::base::PosixInitializeCommon (AbortMode abort_mode, const char *const gc_fake_mmap)
Definition at line 263 of file platform-posix.cc.
                                                           {
  g_abort_mode = abort_mode;
  g_gc_fake_mmap = gc_fake_mmap;
}
References g_abort_mode, and v8::base::anonymous_namespace{platform-posix.cc}::g_gc_fake_mmap.
Referenced by v8::base::OS::Initialize().
PrintCheckOperand()
template<typename T >
std::string v8::base::PrintCheckOperand (T val)
Definition at line 212 of file logging.h.
                                   {
  return "<unprintable>";
}
Referenced by requires().
PRINTF_FORMAT() [1/2]
V8_BASE_EXPORT int v8::base::PRINTF_FORMAT (2 , 0)
PRINTF_FORMAT() [2/2]
V8_BASE_EXPORT int v8::base::PRINTF_FORMAT (2 , 3)
PthreadKeyToLocalKey()
static Thread::LocalStorageKey v8::base::PthreadKeyToLocalKey (pthread_key_t pthread_key) [static]
Definition at line 1313 of file platform-posix.cc.
                                                                             {
#if V8_OS_CYGWIN
  // We need to cast pthread_key_t to Thread::LocalStorageKey in two steps
  // because pthread_key_t is a pointer type on Cygwin. This will probably not
  // work on 64-bit platforms, but Cygwin doesn't support 64-bit anyway.
  static_assert(sizeof(Thread::LocalStorageKey) == sizeof(pthread_key_t));
  intptr_t ptr_key = reinterpret_cast<intptr_t>(pthread_key);
  return static_cast<Thread::LocalStorageKey>(ptr_key);
#else
  return static_cast<Thread::LocalStorageKey>(pthread_key);
#endif
}
Referenced by v8::base::Thread::CreateThreadLocalKey().
RadToDeg()
template<typename T >
requires constexpr std::floating_point<T> T v8::base::RadToDeg (T rad) [constexpr]
Definition at line 24 of file angle_conversions.h.
                            {
  return rad * 180 / std::numbers::pi_v<T>;
}
ReadDiyFp()
static void v8::base::ReadDiyFp (Vector< const char > buffer, DiyFp * result, int * remaining_decimals) [static]
Definition at line 129 of file strtod.cc.
                                               {
  int read_digits;
  uint64_t significand = ReadUint64(buffer, &read_digits);
  if (buffer.length() == read_digits) {
    *result = DiyFp(significand, 0);
    *remaining_decimals = 0;
  } else {
    // Round the significand.
    if (buffer[read_digits] >= '5') {
      significand++;
    }
    // Compute the binary exponent.
    int exponent = 0;
    *result = DiyFp(significand, exponent);
    *remaining_decimals = buffer.length() - read_digits;
  }
}
References v8::base::Vector< T >::length(), ReadUint64(), and v8::base::internal::result.
Referenced by DiyFpStrtod().
ReadLittleEndianValue() [1/2]
template<typename V >
static V v8::base::ReadLittleEndianValue (Address p) [inline], [static]
Definition at line 52 of file memory.h.
                                                 {
#if defined(V8_TARGET_LITTLE_ENDIAN)
  return ReadUnalignedValue<V>(p);
#elif defined(V8_TARGET_BIG_ENDIAN)
  V ret{};
  const uint8_t* src = reinterpret_cast<const uint8_t*>(p);
  uint8_t* dst = reinterpret_cast<uint8_t*>(&ret);
  for (size_t i = 0; i < sizeof(V); i++) {
    dst[i] = src[sizeof(V) - i - 1];
  }
  return ret;
#endif // V8_TARGET_LITTLE_ENDIAN
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, and V.
ReadLittleEndianValue() [2/2]
template<typename V >
static V v8::base::ReadLittleEndianValue (V * p) [inline], [static]
Definition at line 80 of file memory.h.
                                            {
  return ReadLittleEndianValue<V>(reinterpret_cast<Address>(p));
}
References V.
ReadUint64()
static uint64_t v8::base::ReadUint64 (Vector< const char > buffer, int * number_of_read_digits) [static]
Definition at line 112 of file strtod.cc.
                                                       {
  uint64_t result = 0;
  int i = 0;
  while (i < buffer.length() && result <= (kMaxUint64 / 10 - 1)) {
    int digit = buffer[i++] - '0';
    DCHECK(0 <= digit && digit <= 9);
    result = 10 * result + digit;
  }
  *number_of_read_digits = i;
  return result;
}
References DCHECK, v8::internal::anonymous_namespace{json-stringifier.cc}::i, kMaxUint64, v8::base::Vector< T >::length(), and v8::base::internal::result.
Referenced by DoubleStrtod(), and ReadDiyFp().
ReadUInt64()
static uint64_t v8::base::ReadUInt64 (Vector< const char > buffer, int from, int digits_to_read) [static]
Definition at line 63 of file bignum.cc.
                                               {
  uint64_t result = 0;
  int to = from + digits_to_read;
  for (int i = from; i < to; ++i) {
    int digit = buffer[i] - '0';
    DCHECK(0 <= digit && digit <= 9);
    result = result * 10 + digit;
  }
  return result;
}
References DCHECK, v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::base::internal::result.
Referenced by v8::base::Bignum::AssignDecimalString().
ReadUnalignedValue() [1/2]
template<typename V >
static V v8::base::ReadUnalignedValue (Address p) [inline], [static]
Definition at line 28 of file memory.h.
                                              {
  ASSERT_TRIVIALLY_COPYABLE(V);
  V r;
  memcpy(&r, reinterpret_cast<void*>(p), sizeof(V));
  return r;
}
References ASSERT_TRIVIALLY_COPYABLE(), and V.
Referenced by v8::internal::RUNTIME_FUNCTION().
ReadUnalignedValue() [2/2]
template<typename V >
static V v8::base::ReadUnalignedValue (const char p[sizeof(V)]) [inline], [static]
Definition at line 36 of file memory.h.
                                                            {
  return ReadUnalignedValue<V>(reinterpret_cast<Address>(p));
}
References V.
Realloc()
void* v8::base::Realloc (void * memory, size_t size) [inline]
Definition at line 48 of file memory.h.
                                                {
  // The result of realloc with zero size is implementation dependent.
  // Disallow it.
  CHECK_NE(0, size);
#if V8_OS_STARBOARD
  return SbMemoryReallocate(memory, size);
#elif V8_OS_AIX && _LINUX_SOURCE_COMPAT
  // Work around for GCC bug on AIX, see Malloc().
  // See: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=79839
  return __linux_realloc(memory, size);
#else
  return realloc(memory, size);
#endif
}
References CHECK_NE, and size().
Referenced by AllocateAtLeast(), v8::internal::ValueSerializer::ExpandBuffer(), v8::ValueSerializer::Delegate::ReallocateBufferMemory(), and v8::Serializer::ReallocateBufferMemory().
Recip()
float v8::base::Recip (float a) [inline]
Definition at line 78 of file overflowing-math.h.
{ return Divide(1.0f, a); }
References Divide().
RecipSqrt()
float v8::base::RecipSqrt (float a) [inline]
Definition at line 80 of file overflowing-math.h.
                                {
  if (a != 0) return 1.0f / std::sqrt(a);
  if (std::signbit(a) == 0) return std::numeric_limits<float>::infinity();
  return -std::numeric_limits<float>::infinity();
}
RelativePath()
V8_BASE_EXPORT std::unique_ptr< char[]> v8::base::RelativePath (const char * exec_path, const char * name)
Definition at line 15 of file file-utils.cc.
                                                                            {
  DCHECK(exec_path);
  size_t basename_start = strlen(exec_path);
  while (basename_start > 0 &&
         !OS::isDirectorySeparator(exec_path[basename_start - 1])) {
    --basename_start;
  }
  size_t name_length = strlen(name);
  auto buffer = std::make_unique<char[]>(basename_start + name_length + 1);
  if (basename_start > 0) memcpy(buffer.get(), exec_path, basename_start);
  memcpy(buffer.get() + basename_start, name, name_length);
  return buffer;
}
References DCHECK, v8::base::OS::isDirectorySeparator(), and name.
Referenced by v8::internal::InitializeExternalStartupData(), and v8::internal::InitializeICUDefaultLocation().
Relaxed_AtomicExchange()
Atomic32 v8::base::Relaxed_AtomicExchange (volatile Atomic32 * ptr, Atomic32 new_value) [inline]
Definition at line 128 of file atomicops.h.
                                                           {
  return std::atomic_exchange_explicit(helper::to_std_atomic(ptr), new_value,
                                       std::memory_order_relaxed);
}
References v8::base::helper::to_std_atomic().
Relaxed_AtomicIncrement()
Atomic32 v8::base::Relaxed_AtomicIncrement (volatile Atomic32 * ptr, Atomic32 increment) [inline]
Definition at line 140 of file atomicops.h.
                                                            {
  return increment + std::atomic_fetch_add_explicit(helper::to_std_atomic(ptr),
                                                    increment,
                                                    std::memory_order_relaxed);
}
References v8::base::helper::to_std_atomic().
Referenced by cppgc::internal::StatsCollector::InternalScope< trace_category, scope_category >::IncreaseScopeTime(), and v8_inspector::V8ProfilerAgentImpl::nextProfileId().
Relaxed_CompareAndSwap() [1/3]
Atomic16 v8::base::Relaxed_CompareAndSwap (volatile Atomic16 * ptr, Atomic16 old_value, Atomic16 new_value) [inline]
Definition at line 112 of file atomicops.h.
                                                                               {
  std::atomic_compare_exchange_strong_explicit(
      helper::to_std_atomic(ptr), &old_value, new_value,
      std::memory_order_relaxed, std::memory_order_relaxed);
  return old_value;
}
References v8::base::helper::to_std_atomic().
Relaxed_CompareAndSwap() [2/3]
Atomic32 v8::base::Relaxed_CompareAndSwap (volatile Atomic32 * ptr, Atomic32 old_value, Atomic32 new_value) [inline]
Definition at line 120 of file atomicops.h.
                                                                               {
  std::atomic_compare_exchange_strong_explicit(
      helper::to_std_atomic(ptr), &old_value, new_value,
      std::memory_order_relaxed, std::memory_order_relaxed);
  return old_value;
}
References v8::base::helper::to_std_atomic().
Relaxed_CompareAndSwap() [3/3]
Atomic8 v8::base::Relaxed_CompareAndSwap (volatile Atomic8 * ptr, Atomic8 old_value, Atomic8 new_value) [inline]
Definition at line 104 of file atomicops.h.
                                                         {
  std::atomic_compare_exchange_strong_explicit(
      helper::to_std_atomic(ptr), &old_value, new_value,
      std::memory_order_relaxed, std::memory_order_relaxed);
  return old_value;
}
References v8::base::helper::to_std_atomic().
Referenced by v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_CompareAndSwap(), v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Relaxed_CompareAndSwap(), and v8::internal::StackGuard::SetStackLimitForStackSwitching().
Relaxed_Load() [1/3]
Atomic16 v8::base::Relaxed_Load (volatile const Atomic16 * ptr) [inline]
Definition at line 239 of file atomicops.h.
                                                           {
  return std::atomic_load_explicit(helper::to_std_atomic_const(ptr),
                                   std::memory_order_relaxed);
}
References v8::base::helper::to_std_atomic_const().
Relaxed_Load() [2/3]
Atomic32 v8::base::Relaxed_Load (volatile const Atomic32 * ptr) [inline]
Definition at line 244 of file atomicops.h.
                                                           {
  return std::atomic_load_explicit(helper::to_std_atomic_const(ptr),
                                   std::memory_order_relaxed);
}
References v8::base::helper::to_std_atomic_const().
Relaxed_Load() [3/3]
Atomic8 v8::base::Relaxed_Load (volatile const Atomic8 * ptr) [inline]
Definition at line 234 of file atomicops.h.
                                                         {
  return std::atomic_load_explicit(helper::to_std_atomic_const(ptr),
                                   std::memory_order_relaxed);
}
References v8::base::helper::to_std_atomic_const().
Referenced by v8::internal::DEF_RELAXED_GETTER(), v8::internal::ICStats::End(), v8::internal::FUNCTION_REFERENCE(), v8::internal::V8::GetCurrentPlatform(), v8::internal::HandlerTable::GetRangeHandlerBitfield(), v8::internal::StackGuard::ThreadLocal::has_interrupt_requested(), v8::internal::Debug::in_debug_scope(), v8::internal::StackGuard::ThreadLocal::jslimit(), cppgc::internal::StatsCollector::marking_time(), v8::internal::Debug::NotifyDebuggerPausedEventSent(), v8::internal::JSObject::RawFastPropertyAt(), v8::internal::WriteProtectedSlot< SlotT >::Relaxed_Load(), v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Relaxed_Load(), v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_Load(), v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Relaxed_Load_Map_Word(), Relaxed_Memcmp(), Relaxed_Memcpy(), Relaxed_Memmove(), v8::internal::Profiler::Remove(), v8::internal::Profiler::Run(), and v8::internal::tracing::ScopedTracer::~ScopedTracer().
Relaxed_Memcmp()
int v8::base::Relaxed_Memcmp (volatile const Atomic8 * s1, volatile const Atomic8 * s2, size_t len) [inline]
Definition at line 447 of file atomicops.h.
                                                                  {
  constexpr size_t kAtomicWordSize = sizeof(AtomicWord);
  while (len > 0 &&
         !(IsAligned(reinterpret_cast<uintptr_t>(s1), kAtomicWordSize) &&
           IsAligned(reinterpret_cast<uintptr_t>(s2), kAtomicWordSize))) {
    Atomic8 u1 = Relaxed_Load(s1++);
    Atomic8 u2 = Relaxed_Load(s2++);
    if (u1 != u2) return helper::MemcmpNotEqualFundamental(u1, u2);
    --len;
  }
  if (IsAligned(reinterpret_cast<uintptr_t>(s1), kAtomicWordSize) &&
      IsAligned(reinterpret_cast<uintptr_t>(s2), kAtomicWordSize)) {
    while (len >= kAtomicWordSize) {
      AtomicWord u1 =
          Relaxed_Load(reinterpret_cast<const volatile AtomicWord*>(s1));
      AtomicWord u2 =
          Relaxed_Load(reinterpret_cast<const volatile AtomicWord*>(s2));
      if (u1 != u2) return helper::MemcmpNotEqualFundamental(u1, u2);
      s1 += kAtomicWordSize;
      s2 += kAtomicWordSize;
      len -= kAtomicWordSize;
    }
  }
  while (len > 0) {
    Atomic8 u1 = Relaxed_Load(s1++);
    Atomic8 u2 = Relaxed_Load(s2++);
    if (u1 != u2) return helper::MemcmpNotEqualFundamental(u1, u2);
    --len;
  }
  return 0;
}
References IsAligned(), v8::base::helper::MemcmpNotEqualFundamental(), and Relaxed_Load().
Relaxed_Memcpy()
void v8::base::Relaxed_Memcpy (volatile Atomic8 * dst, volatile const Atomic8 * src, size_t bytes) [inline]
Definition at line 363 of file atomicops.h.
                                         {
  constexpr size_t kAtomicWordSize = sizeof(AtomicWord);
  while (bytes > 0 &&
         !IsAligned(reinterpret_cast<uintptr_t>(dst), kAtomicWordSize)) {
    Relaxed_Store(dst++, Relaxed_Load(src++));
    --bytes;
  }
  if (IsAligned(reinterpret_cast<uintptr_t>(src), kAtomicWordSize) &&
      IsAligned(reinterpret_cast<uintptr_t>(dst), kAtomicWordSize)) {
    while (bytes >= kAtomicWordSize) {
      Relaxed_Store(
          reinterpret_cast<volatile AtomicWord*>(dst),
          Relaxed_Load(reinterpret_cast<const volatile AtomicWord*>(src)));
      dst += kAtomicWordSize;
      src += kAtomicWordSize;
      bytes -= kAtomicWordSize;
    }
  }
  while (bytes > 0) {
    Relaxed_Store(dst++, Relaxed_Load(src++));
    --bytes;
  }
}
References IsAligned(), Relaxed_Load(), and Relaxed_Store().
Referenced by v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::CopyElementsFromTypedArray(), v8::anonymous_namespace{wasm-js.cc}::GetAndCopyFirstArgumentAsBytes(), v8::internal::relaxed_memcpy(), Relaxed_Memmove(), v8::internal::RUNTIME_FUNCTION(), v8::internal::SliceHelper(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyValidateImpl().
Relaxed_Memmove()
void v8::base::Relaxed_Memmove (volatile Atomic8 * dst, volatile const Atomic8 * src, size_t bytes) [inline]
Definition at line 388 of file atomicops.h.
                                          {
  // Use Relaxed_Memcpy if copying forwards is safe. This is the case if there
  // is no overlap, or {dst} lies before {src}.
  // This single check checks for both:
  if (reinterpret_cast<uintptr_t>(dst) - reinterpret_cast<uintptr_t>(src) >=
      bytes) {
    Relaxed_Memcpy(dst, src, bytes);
    return;
  }
  // Otherwise copy backwards.
  dst += bytes;
  src += bytes;
  constexpr size_t kAtomicWordSize = sizeof(AtomicWord);
  while (bytes > 0 &&
         !IsAligned(reinterpret_cast<uintptr_t>(dst), kAtomicWordSize)) {
    Relaxed_Store(--dst, Relaxed_Load(--src));
    --bytes;
  }
  if (IsAligned(reinterpret_cast<uintptr_t>(src), kAtomicWordSize) &&
      IsAligned(reinterpret_cast<uintptr_t>(dst), kAtomicWordSize)) {
    while (bytes >= kAtomicWordSize) {
      dst -= kAtomicWordSize;
      src -= kAtomicWordSize;
      bytes -= kAtomicWordSize;
      Relaxed_Store(
          reinterpret_cast<volatile AtomicWord*>(dst),
          Relaxed_Load(reinterpret_cast<const volatile AtomicWord*>(src)));
    }
  }
  while (bytes > 0) {
    Relaxed_Store(--dst, Relaxed_Load(--src));
    --bytes;
  }
}
References IsAligned(), Relaxed_Load(), Relaxed_Memcpy(), and Relaxed_Store().
Referenced by v8::internal::BUILTIN(), and v8::internal::relaxed_memmove().
Relaxed_Store() [1/3]
void v8::base::Relaxed_Store (volatile Atomic16 * ptr, Atomic16 value) [inline]
Definition at line 194 of file atomicops.h.
                                                                  {
  std::atomic_store_explicit(helper::to_std_atomic(ptr), value,
                             std::memory_order_relaxed);
}
References v8::base::helper::to_std_atomic(), and v8::internal::value.
Relaxed_Store() [2/3]
void v8::base::Relaxed_Store (volatile Atomic32 * ptr, Atomic32 value) [inline]
Definition at line 199 of file atomicops.h.
                                                                  {
  std::atomic_store_explicit(helper::to_std_atomic(ptr), value,
                             std::memory_order_relaxed);
}
References v8::base::helper::to_std_atomic(), and v8::internal::value.
Relaxed_Store() [3/3]
void v8::base::Relaxed_Store (volatile Atomic8 * ptr, Atomic8 value) [inline]
Definition at line 189 of file atomicops.h.
                                                                {
  std::atomic_store_explicit(helper::to_std_atomic(ptr), value,
                             std::memory_order_relaxed);
}
References v8::base::helper::to_std_atomic(), and v8::internal::value.
Referenced by v8::internal::ICStats::Begin(), v8::internal::SnapshotByteSource::CopySlots(), v8::internal::DebugScope::DebugScope(), v8::internal::Profiler::Disengage(), v8::internal::ICStats::End(), v8::internal::Profiler::Engage(), v8::internal::FUNCTION_REFERENCE(), v8::internal::ICStats::ICStats(), v8::Locker::Initialize(), v8::internal::Profiler::Insert(), v8::internal::HandlerTable::MarkHandlerUsed(), v8::internal::MarkingBitmap::ClearCellRangeRelaxed< AccessMode::ATOMIC >(), v8::internal::MarkingBitmap::SetCellRangeRelaxed< AccessMode::ATOMIC >(), v8::internal::Profiler::Profiler(), Relaxed_Memcpy(), Relaxed_Memmove(), v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_Store(), v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Relaxed_Store(), v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Relaxed_Store_Map_Word(), v8::internal::Profiler::Remove(), v8::internal::TaggedField< T, kFieldOffset >::SeqCst_Swap(), v8::internal::JSObject::set_elements(), v8::internal::StackGuard::ThreadLocal::set_interrupt_requested(), v8::internal::StackGuard::ThreadLocal::set_jslimit(), v8::internal::V8::SetPlatformForTesting(), v8::internal::Debug::ThreadInit(), v8::platform::tracing::TracingController::UpdateCategoryGroupEnabledFlag(), and v8::internal::DebugScope::~DebugScope().
Release_CompareAndSwap() [1/2]
Atomic32 v8::base::Release_CompareAndSwap (volatile Atomic32 * ptr, Atomic32 old_value, Atomic32 new_value) [inline]
Definition at line 164 of file atomicops.h.
                                                                               {
  atomic_compare_exchange_strong_explicit(
      helper::to_std_atomic(ptr), &old_value, new_value,
      std::memory_order_release, std::memory_order_relaxed);
  return old_value;
}
References v8::base::helper::to_std_atomic().
Release_CompareAndSwap() [2/2]
Atomic8 v8::base::Release_CompareAndSwap (volatile Atomic8 * ptr, Atomic8 old_value, Atomic8 new_value) [inline]
Definition at line 155 of file atomicops.h.
                                                         {
  bool result = atomic_compare_exchange_strong_explicit(
      helper::to_std_atomic(ptr), &old_value, new_value,
      std::memory_order_release, std::memory_order_relaxed);
  USE(result); // Make gcc compiler happy.
  return old_value;
}
References v8::base::internal::result, v8::base::helper::to_std_atomic(), and USE.
Referenced by v8::base::AsAtomicImpl< TAtomicStorageType >::Release_CompareAndSwap(), and v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Release_CompareAndSwap().
Release_Store() [1/3]
void v8::base::Release_Store (volatile Atomic16 * ptr, Atomic16 value) [inline]
Definition at line 209 of file atomicops.h.
                                                                  {
  std::atomic_store_explicit(helper::to_std_atomic(ptr), value,
                             std::memory_order_release);
}
References v8::base::helper::to_std_atomic(), and v8::internal::value.
Release_Store() [2/3]
void v8::base::Release_Store (volatile Atomic32 * ptr, Atomic32 value) [inline]
Definition at line 214 of file atomicops.h.
                                                                  {
  std::atomic_store_explicit(helper::to_std_atomic(ptr), value,
                             std::memory_order_release);
}
References v8::base::helper::to_std_atomic(), and v8::internal::value.
Release_Store() [3/3]
void v8::base::Release_Store (volatile Atomic8 * ptr, Atomic8 value) [inline]
Definition at line 204 of file atomicops.h.
                                                                {
  std::atomic_store_explicit(helper::to_std_atomic(ptr), value,
                             std::memory_order_release);
}
References v8::base::helper::to_std_atomic(), and v8::internal::value.
Referenced by v8::internal::SamplingCircularQueue< v8::internal::TickSampleEventRecord, kTickSampleQueueLength >::FinishEnqueue(), v8::internal::SamplingCircularQueue< T, Length >::FinishEnqueue(), v8::platform::tracing::TracingController::GetCategoryGroupEnabled(), v8::internal::MemoryChunk::InitializationMemoryFence(), v8::base::AsAtomicImpl< TAtomicStorageType >::Release_Store(), v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Release_Store(), v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Release_Store_Map_Word(), v8::internal::Profiler::Remove(), and v8::base::AtomicValue< T >::SetValue().
requires() [1/9]
template<typename T >
v8::base::requires (!has_output_operator< T, CheckMessageStream > &&requires(T t) { { t.begin() } -> std::forward_iterator;})
Definition at line 262 of file logging.h.
                         {
             { t.begin() } -> std::forward_iterator;
           })
std::string PrintCheckOperand(T container) {
  CheckMessageStream oss;
  oss << "{";
  bool first = true;
  for (const auto& val : container) {
    if (!first) {
      oss << ",";
    } else {
      first = false;
    }
    oss << PrintCheckOperand(val);
  }
  oss << "}";
  return oss.str();
}
requires() [2/9]
template<typename T >
v8::base::requires (!std::is_function_v< std::remove_pointer_t< T >> &&!std::is_enum_v< T > &&has_output_operator< T, CheckMessageStream >)
Definition at line 219 of file logging.h.
                                   {
  return detail::PrintToString(std::forward<T>(val));
}
References v8::base::detail::PrintToString().
requires() [3/9]
template<typename T , typename U >
v8::base::requires ((std::is_integral_v< T >||std::is_enum_v< T >) &&(std::is_integral_v< U >||std::is_enum_v< U >)) &&
References DCHECK_LE, and v8::internal::value.
Referenced by EXPORT_TEMPLATE_DECLARE().
requires() [4/9]
template<size_t N, typename Tuple >
v8::base::requires (detail::NIsNotGreaterThanTupleSize< N, Tuple >) const &&
Definition at line 139 of file template-utils.h.
                                       {
  constexpr size_t total_size = std::tuple_size_v<std::decay_t<Tuple>>;
  static_assert(N <= total_size);
  return detail::tuple_slice_impl<N>(
      std::forward<Tuple>(tpl), std::make_index_sequence<total_size - N>());
}
References v8::internal::N.
requires() [5/9]
template<typename Dst = int, typename Src >
v8::base::requires (std::integral< Dst > &&std::floating_point< Src >)
Definition at line 359 of file safe_conversions.h.
                          {
  return saturated_cast<Dst>(std::floor(value));
}
References v8::internal::value.
requires() [6/9]
template<typename T >
v8::base::requires (std::is_enum_v< T >)
Definition at line 238 of file logging.h.
                                   {
  std::string int_str =
      detail::PrintToString(detail::GetUnderlyingEnumTypeForPrinting(val));
  if constexpr (has_output_operator<T, CheckMessageStream>) {
    std::string val_str = detail::PrintToString(val);
    // Printing the original enum might have printed a single non-printable
    // character. Ignore it in that case. Also ignore if it printed the same as
    // the integral representation.
    // TODO(clemensb): Can we somehow statically find out if the output operator
    // is the default one, printing the integral value?
    if ((val_str.length() == 1 && !std::isprint(val_str[0])) ||
        val_str == int_str) {
      return int_str;
    }
    return detail::PrintToString(val_str, " (", int_str, ")");
  } else {
    return int_str;
  }
}
References v8::base::detail::GetUnderlyingEnumTypeForPrinting(), v8::base::detail::PrintToString(), and v8::internal::string.
requires() [7/9]
template<typename T >
v8::base::requires (std::is_function_v< typename std::remove_pointer_t< T >>)
Definition at line 231 of file logging.h.
                                   {
  return PrintCheckOperand(reinterpret_cast<const void*>(val));
}
References PrintCheckOperand().
requires() [8/9]
template<class T >
v8::base::requires (std::is_integral_v< T >) const
Definition at line 29 of file byte_conversions.h.
                                     {
  return internal::SwapBytes(value);
}
References v8::internal::value.
requires() [9/9]
template<typename TagType , typename UnderlyingType >
requires v8::base::requires (std::ostream & stream, const UnderlyingType & value)
Definition at line 131 of file strong-alias.h.
                                                                     {
    stream << value;
  }
References v8::internal::value.
Reversed() [1/2]
template<typename T >
auto v8::base::Reversed (const iterator_range< T > & t)
Definition at line 110 of file iterator.h.
                                          {
  return make_iterator_range(std::rbegin(t), std::rend(t));
}
References make_iterator_range().
Reversed() [2/2]
template<typename T >
auto v8::base::Reversed (T & t)
Definition at line 102 of file iterator.h.
                    {
  return make_iterator_range(std::rbegin(t), std::rend(t));
}
References make_iterator_range().
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::ComputePostDominatingHoles(), v8::internal::compiler::InstructionScheduler::ComputeTotalLatencies(), v8::internal::wasm::LiftoffAssembler::CacheState::DefineSafepoint(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ExceptionHandlerTrampolineBuilder::EmitPopMaterialisedResults(), v8::internal::compiler::InstructionSelector::EmitPrepareArguments(), v8::internal::ExternalEntityTable< Entry, size >::GenericSweep(), v8::internal::compiler::CodeGenerator::GetPushCompatibleMoves(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GetStackValueTypesForDebugging(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::MergePredecessors(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::MoveToNewSnapshot(), v8::internal::MacroAssembler::PopAll(), v8::internal::compiler::turboshaft::StringEscapeAnalyzer::ProcessBlock(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::ProcessBlock(), v8::internal::compiler::turboshaft::anonymous_namespace{decompression-optimization.cc}::DecompressionAnalyzer::ProcessBlock(), v8::internal::compiler::FrameElider::PropagateReversed(), v8::internal::FrameWriter::PushStackJSArguments(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::ResolvePhi(), v8::internal::compiler::ConstraintBuilder::ResolvePhis(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::RevertCurrentSnapshot(), v8::internal::compiler::turboshaft::LoopFinder::Run(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::Run(), v8::internal::compiler::Scheduler::SealFinalSchedule(), v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::SplitRangeByReservationsIfNeeded(), and v8::internal::compiler::InstructionSelector::VisitBlock().
RoundWeed()
static bool v8::base::RoundWeed (char * last_digit, uint64_t distance_too_high_w, uint64_t unsafe_interval, uint64_t rest, uint64_t ten_kappa, uint64_t unit) [static]
Definition at line 41 of file fast-dtoa.cc.
                                                         {
  uint64_t small_distance = distance_too_high_w - unit;
  uint64_t big_distance = distance_too_high_w + unit;
  // Let w_low = too_high - big_distance, and
  // w_high = too_high - small_distance.
  // Note: w_low < w < w_high
  //
  // The real w (* unit) must lie somewhere inside the interval
  // ]w_low; w_high[ (often written as "(w_low; w_high)")
  // Basically the buffer currently contains a number in the unsafe interval
  // ]too_low; too_high[ with too_low < w < too_high
  //
  // too_high - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  // ^v 1 unit ^ ^ ^ ^
  // boundary_high --------------------- . . . .
  // ^v 1 unit . . . .
  // - - - - - - - - - - - - - - - - - - - + - - + - - - - - - . .
  // . . ^ . .
  // . big_distance . . .
  // . . . . rest
  // small_distance . . . .
  // v . . . .
  // w_high - - - - - - - - - - - - - - - - - - . . . .
  // ^v 1 unit . . . .
  // w ---------------------------------------- . . . .
  // ^v 1 unit v . . .
  // w_low - - - - - - - - - - - - - - - - - - - - - . . .
  // . . v
  // buffer --------------------------------------------------+-------+--------
  // . .
  // safe_interval .
  // v .
  // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - .
  // ^v 1 unit .
  // boundary_low ------------------------- unsafe_interval
  // ^v 1 unit v
  // too_low - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  //
  //
  // Note that the value of buffer could lie anywhere inside the range too_low
  // to too_high.
  //
  // boundary_low, boundary_high and w are approximations of the real boundaries
  // and v (the input number). They are guaranteed to be precise up to one unit.
  // In fact the error is guaranteed to be strictly less than one unit.
  //
  // Anything that lies outside the unsafe interval is guaranteed not to round
  // to v when read again.
  // Anything that lies inside the safe interval is guaranteed to round to v
  // when read again.
  // If the number inside the buffer lies inside the unsafe interval but not
  // inside the safe interval then we simply do not know and bail out (returning
  // false).
  //
  // Similarly we have to take into account the imprecision of 'w' when finding
  // the closest representation of 'w'. If we have two potential
  // representations, and one is closer to both w_low and w_high, then we know
  // it is closer to the actual value v.
  //
  // By generating the digits of too_high we got the largest (closest to
  // too_high) buffer that is still in the unsafe interval. In the case where
  // w_high < buffer < too_high we try to decrement the buffer.
  // This way the buffer approaches (rounds towards) w.
  // There are 3 conditions that stop the decrementation process:
  // 1) the buffer is already below w_high
  // 2) decrementing the buffer would make it leave the unsafe interval
  // 3) decrementing the buffer would yield a number below w_high and farther
  // away than the current number. In other words:
  // (buffer{-1} < w_high) && w_high - buffer{-1} > buffer - w_high
  // Instead of using the buffer directly we use its distance to too_high.
  // Conceptually rest ~= too_high - buffer
  // We need to do the following tests in this order to avoid over- and
  // underflows.
  DCHECK(rest <= unsafe_interval);
  while (rest < small_distance && // Negated condition 1
         unsafe_interval - rest >= ten_kappa && // Negated condition 2
         (rest + ten_kappa < small_distance || // buffer{-1} > w_high
          small_distance - rest >= rest + ten_kappa - small_distance)) {
    --*last_digit;
    rest += ten_kappa;
  }
  // We have approached w+ as much as possible. We now test if approaching w-
  // would require changing the buffer. If yes, then we have two possible
  // representations close to w, but we cannot decide which one is closer.
  if (rest < big_distance && unsafe_interval - rest >= ten_kappa &&
      (rest + ten_kappa < big_distance ||
       big_distance - rest > rest + ten_kappa - big_distance)) {
    return false;
  }
  // Weeding test.
  // The safe interval is [too_low + 2 ulp; too_high - 2 ulp]
  // Since too_low = too_high - unsafe_interval this is equivalent to
  // [too_high - unsafe_interval + 4 ulp; too_high - 2 ulp]
  // Conceptually we have: rest ~= too_high - buffer
  return (2 * unit <= rest) && (rest <= unsafe_interval - 4 * unit);
}
References DCHECK.
Referenced by DigitGen().
RoundWeedCounted()
static bool v8::base::RoundWeedCounted (Vector< char > buffer, int length, uint64_t rest, uint64_t ten_kappa, uint64_t unit, int * kappa) [static]
Definition at line 155 of file fast-dtoa.cc.
                                                                            {
  DCHECK(rest < ten_kappa);
  // The following tests are done in a specific order to avoid overflows. They
  // will work correctly with any uint64 values of rest < ten_kappa and unit.
  //
  // If the unit is too big, then we don't know which way to round. For example
  // a unit of 50 means that the real number lies within rest +/- 50. If
  // 10^kappa == 40 then there is no way to tell which way to round.
  if (unit >= ten_kappa) return false;
  // Even if unit is just half the size of 10^kappa we are already completely
  // lost. (And after the previous test we know that the expression will not
  // over/underflow.)
  if (ten_kappa - unit <= unit) return false;
  // If 2 * (rest + unit) <= 10^kappa we can safely round down.
  if ((ten_kappa - rest > rest) && (ten_kappa - 2 * rest >= 2 * unit)) {
    return true;
  }
  // If 2 * (rest - unit) >= 10^kappa, then we can safely round up.
  if ((rest > unit) && (ten_kappa - (rest - unit) <= (rest - unit))) {
    // Increment the last digit recursively until we find a non '9' digit.
    buffer[length - 1]++;
    for (int i = length - 1; i > 0; --i) {
      if (buffer[i] != '0' + 10) break;
      buffer[i] = '0';
      buffer[i - 1]++;
    }
    // If the first digit is now '0'+ 10 we had a buffer with all '9's. With the
    // exception of the first digit all digits are now '0'. Simply switch the
    // first digit to '1' and adjust the kappa. Example: "99" becomes "10" and
    // the power (the kappa) is increased.
    if (buffer[0] == '0' + 10) {
      buffer[0] = '1';
      (*kappa) += 1;
    }
    return true;
  }
  return false;
}
References DCHECK, v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::length.
Referenced by DigitGenCounted().
SeqCst_AtomicExchange()
Atomic32 v8::base::SeqCst_AtomicExchange (volatile Atomic32 * ptr, Atomic32 new_value) [inline]
Definition at line 134 of file atomicops.h.
                                                          {
  return std::atomic_exchange_explicit(helper::to_std_atomic(ptr), new_value,
                                       std::memory_order_seq_cst);
}
References v8::base::helper::to_std_atomic().
Referenced by v8::base::AsAtomicImpl< TAtomicStorageType >::SeqCst_Swap().
SeqCst_CompareAndSwap()
Atomic32 v8::base::SeqCst_CompareAndSwap (volatile Atomic32 * ptr, Atomic32 old_value, Atomic32 new_value) [inline]
Definition at line 181 of file atomicops.h.
                                                                              {
  atomic_compare_exchange_strong_explicit(
      helper::to_std_atomic(ptr), &old_value, new_value,
      std::memory_order_seq_cst, std::memory_order_seq_cst);
  return old_value;
}
References v8::base::helper::to_std_atomic().
Referenced by v8::base::AsAtomicImpl< TAtomicStorageType >::SeqCst_CompareAndSwap(), and v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::SeqCst_CompareAndSwap().
SeqCst_Load() [1/2]
Atomic32 v8::base::SeqCst_Load (volatile const Atomic32 * ptr) [inline]
Definition at line 264 of file atomicops.h.
                                                          {
  return std::atomic_load_explicit(helper::to_std_atomic_const(ptr),
                                   std::memory_order_seq_cst);
}
References v8::base::helper::to_std_atomic_const().
SeqCst_Load() [2/2]
Atomic8 v8::base::SeqCst_Load (volatile const Atomic8 * ptr) [inline]
Definition at line 259 of file atomicops.h.
                                                        {
  return std::atomic_load_explicit(helper::to_std_atomic_const(ptr),
                                   std::memory_order_seq_cst);
}
References v8::base::helper::to_std_atomic_const().
Referenced by v8::internal::JSObject::RawFastPropertyAt(), v8::base::AsAtomicImpl< TAtomicStorageType >::SeqCst_Load(), and v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::SeqCst_Load().
SeqCst_MemoryFence()
void v8::base::SeqCst_MemoryFence () [inline]
Definition at line 91 of file atomicops.h.
                                 {
  std::atomic_thread_fence(std::memory_order_seq_cst);
}
Referenced by v8::internal::MarkingBitmap::Clear(), v8::internal::MarkingBitmap::ClearRange(), v8::internal::MemoryChunk::InitializationMemoryFence(), v8::internal::SamplingCircularQueue< T, Length >::Peek(), v8::internal::SamplingCircularQueue< v8::internal::TickSampleEventRecord, kTickSampleQueueLength >::Remove(), and v8::internal::MarkingBitmap::SetRange().
SeqCst_Store() [1/3]
void v8::base::SeqCst_Store (volatile Atomic16 * ptr, Atomic16 value) [inline]
Definition at line 224 of file atomicops.h.
                                                                 {
  std::atomic_store_explicit(helper::to_std_atomic(ptr), value,
                             std::memory_order_seq_cst);
}
References v8::base::helper::to_std_atomic(), and v8::internal::value.
SeqCst_Store() [2/3]
void v8::base::SeqCst_Store (volatile Atomic32 * ptr, Atomic32 value) [inline]
Definition at line 229 of file atomicops.h.
                                                                 {
  std::atomic_store_explicit(helper::to_std_atomic(ptr), value,
                             std::memory_order_seq_cst);
}
References v8::base::helper::to_std_atomic(), and v8::internal::value.
SeqCst_Store() [3/3]
void v8::base::SeqCst_Store (volatile Atomic8 * ptr, Atomic8 value) [inline]
Definition at line 219 of file atomicops.h.
                                                               {
  std::atomic_store_explicit(helper::to_std_atomic(ptr), value,
                             std::memory_order_seq_cst);
}
References v8::base::helper::to_std_atomic(), and v8::internal::value.
Referenced by v8::internal::FUNCTION_REFERENCE(), v8::base::AsAtomicImpl< TAtomicStorageType >::SeqCst_Store(), and v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::SeqCst_Store().
SetDcheckFunction()
V8_BASE_EXPORT void v8::base::SetDcheckFunction (void(*)(const char *, int, const char *) dcheck_function)
Definition at line 72 of file logging.cc.
                                                                               {
  g_dcheck_function = dcheck_function ? dcheck_function : &DefaultDcheckHandler;
}
References v8::base::anonymous_namespace{logging.cc}::DefaultDcheckHandler(), and v8::base::anonymous_namespace{logging.cc}::g_dcheck_function.
Referenced by v8::V8::SetDcheckErrorHandler().
SetFatalFunction()
V8_BASE_EXPORT void v8::base::SetFatalFunction (void(*)(const char *, int, const char *) fatal_function)
Definition at line 76 of file logging.cc.
                                                                             {
  g_fatal_function = fatal_function;
}
References v8::base::anonymous_namespace{logging.cc}::g_fatal_function.
Referenced by v8::V8::SetFatalErrorHandler().
SetPrintStackTrace()
V8_BASE_EXPORT void v8::base::SetPrintStackTrace (void(*)() print_stack_trace)
Definition at line 68 of file logging.cc.
                                                     {
  g_print_stack_trace = print_stack_trace;
}
References v8::base::anonymous_namespace{logging.cc}::g_print_stack_trace.
Referenced by v8::internal::V8::DisposePlatform(), and v8::internal::V8::InitializePlatform().
SetThreadName() [1/2]
static void v8::base::SetThreadName (const char * name) [static]
Definition at line 1204 of file platform-posix.cc.
                                            {
#if V8_OS_DRAGONFLYBSD || V8_OS_FREEBSD || V8_OS_OPENBSD
  pthread_set_name_np(pthread_self(), name);
#elif V8_OS_NETBSD
  static_assert(Thread::kMaxThreadNameLength <= PTHREAD_MAX_NAMELEN_NP);
  pthread_setname_np(pthread_self(), "%s", name);
#elif V8_OS_DARWIN
  // pthread_setname_np is only available in 10.6 or later, so test
  // for it at runtime.
  int (*dynamic_pthread_setname_np)(const char*);
  *reinterpret_cast<void**>(&dynamic_pthread_setname_np) =
    dlsym(RTLD_DEFAULT, "pthread_setname_np");
  if (dynamic_pthread_setname_np == nullptr) return;
  // Mac OS X does not expose the length limit of the name, so hardcode it.
  static const int kMaxNameLength = 63;
  static_assert(Thread::kMaxThreadNameLength <= kMaxNameLength);
  dynamic_pthread_setname_np(name);
#elif defined(PR_SET_NAME)
  prctl(PR_SET_NAME,
        reinterpret_cast<unsigned long>(name), // NOLINT
        0, 0, 0);
#endif
}
References v8::base::Thread::kMaxThreadNameLength, and name.
Referenced by ThreadEntry().
SetThreadName() [2/2]
static void v8::base::SetThreadName (const char * name) [static]
Definition at line 382 of file platform-starboard.cc.
{ SbThreadSetName(name); }
References v8::base::Thread::name().
ShlWithWraparound()
template<typename signed_type >
signed_type v8::base::ShlWithWraparound (signed_type a, signed_type b) [inline]
Definition at line 58 of file overflowing-math.h.
                                                                   {
  ASSERT_SIGNED_INTEGER_TYPE(signed_type);
  using unsigned_type = std::make_unsigned_t<signed_type>;
  const unsigned_type kMask = (sizeof(a) * 8) - 1;
  return static_cast<signed_type>(static_cast<unsigned_type>(a) << (b & kMask));
}
References ASSERT_SIGNED_INTEGER_TYPE.
Referenced by v8::internal::compiler::MachineOperatorReducer::ReduceWord32Shl(), v8::internal::compiler::MachineOperatorReducer::ReduceWord64Shl(), and v8::internal::Parser::ShortcutLiteralBinaryExpression().
SignedDivisionByConstant() [1/2]
template<typename T >
requires std::unsigned_integral< T > MagicNumbersForDivision< T > v8::base::SignedDivisionByConstant (T d)
Definition at line 19 of file division-by-constant.cc.
                                                         {
  DCHECK(d != static_cast<T>(-1) && d != 0 && d != 1);
  const unsigned bits = static_cast<unsigned>(sizeof(T)) * 8;
  const T min = (static_cast<T>(1) << (bits - 1));
  const bool neg = (min & d) != 0;
  const T ad = neg ? (0 - d) : d;
  const T t = min + (d >> (bits - 1));
  const T anc = t - 1 - t % ad; // Absolute value of nc
  unsigned p = bits - 1; // Init. p.
  T q1 = min / anc; // Init. q1 = 2**p/|nc|.
  T r1 = min - q1 * anc; // Init. r1 = rem(2**p, |nc|).
  T q2 = min / ad; // Init. q2 = 2**p/|d|.
  T r2 = min - q2 * ad; // Init. r2 = rem(2**p, |d|).
  T delta;
  do {
    p = p + 1;
    q1 = 2 * q1; // Update q1 = 2**p/|nc|.
    r1 = 2 * r1; // Update r1 = rem(2**p, |nc|).
    if (r1 >= anc) { // Must be an unsigned comparison here.
      q1 = q1 + 1;
      r1 = r1 - anc;
    }
    q2 = 2 * q2; // Update q2 = 2**p/|d|.
    r2 = 2 * r2; // Update r2 = rem(2**p, |d|).
    if (r2 >= ad) { // Must be an unsigned comparison here.
      q2 = q2 + 1;
      r2 = r2 - ad;
    }
    delta = ad - r2;
  } while (q1 < delta || (q1 == delta && r1 == 0));
  T mul = q2 + 1;
  return MagicNumbersForDivision<T>(neg ? (0 - mul) : mul, p - bits, false);
}
References DCHECK, and T.
Referenced by EXPORT_TEMPLATE_DECLARE(), v8::internal::compiler::MachineOperatorReducer::Int32Div(), v8::internal::compiler::MachineOperatorReducer::Int64Div(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceSignedDiv(), and SignedDivisionByConstant().
SignedDivisionByConstant() [2/2]
template<typename T >
requires std::signed_integral<T> MagicNumbersForDivision<T> v8::base::SignedDivisionByConstant (T d)
Definition at line 47 of file division-by-constant.h.
                                                         {
  using Unsigned = std::make_unsigned_t<T>;
  MagicNumbersForDivision<Unsigned> magic =
      SignedDivisionByConstant(static_cast<Unsigned>(d));
  return {static_cast<T>(magic.multiplier), magic.shift, magic.add};
}
References SignedDivisionByConstant(), and v8::base::bits::Unsigned().
SizeInHexChars()
template<typename S >
static int v8::base::SizeInHexChars (S number) [static]
Definition at line 511 of file bignum.cc.
                                    {
  DCHECK_GT(number, 0);
  int result = 0;
  while (number != 0) {
    number >>= 4;
    result++;
  }
  return result;
}
References DCHECK_GT, and v8::base::internal::result.
Referenced by v8::base::Bignum::ToHexString().
SNPrintF()
int v8::base::SNPrintF (Vector< char > str, const char * format, ...)
Definition at line 20 of file strings.cc.
                                                        {
  va_list args;
  va_start(args, format);
  int result = VSNPrintF(str, format, args);
  va_end(args);
  return result;
}
References args, format, v8::base::internal::result, and VSNPrintF().
Referenced by v8::internal::StringStream::Add(), v8::internal::CodeEventLogger::NameBuffer::AppendHex(), v8::internal::CodeEventLogger::NameBuffer::AppendInt(), v8_inspector::String16Builder::appendNumber(), v8_inspector::String16Builder::appendUnsignedAsHex(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::AssertImpl(), v8::internal::DebugPropertyIterator::attributes(), v8::internal::ExternalizeStringExtension::BuildSource(), v8::internal::CpuTraceMarkExtension::BuildSource(), v8::internal::GCExtension::BuildSource(), v8::internal::VTuneDomainSupportExtension::BuildSource(), v8::internal::FuzzilliExtension::BuildSource(), v8::internal::CodeTracer::CodeTracer(), v8::internal::compiler::CompileWasmImportCallWrapper(), v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::CreateWasmScript(), v8::internal::wasm::WasmCode::DebugName(), v8::internal::Deoptimizer::DoComputeBuiltinContinuation(), v8::internal::wasm::DumpModule(), v8::internal::wasm::DumpProfileToFile(), v8::internal::EmbeddedFileWriter::EmbeddedBlobCodeSymbol(), v8::internal::EmbeddedFileWriter::EmbeddedBlobDataSymbol(), v8::tracing::anonymous_namespace{traced-value.cc}::EscapeAndAppendString(), v8::internal::CodeStubAssembler::FailAssert(), v8_inspector::String16::fromInteger(), v8_inspector::String16::fromInteger64(), v8::internal::wasm::fuzzing::GenerateWasmModuleForInitExpressions(), v8::internal::compiler::GetDebugName(), v8::internal::Version::GetSONAME(), v8::internal::Version::GetString(), v8::internal::compiler::GetVisualizerLogFileName(), v8::base::WindowsTimezoneCache::InitializeIfNeeded(), v8::internal::AsmJs::InstantiateAsmWasm(), v8::internal::Decoder< V >::InstructionDecode(), v8::internal::wasm::LoadProfileFromFile(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::MaybeBailoutForUnsupportedType(), disasm::NameConverter::NameOfAddress(), v8::internal::WasmValueObject::New(), v8::internal::WasmExportedFunction::New(), v8::internal::GCTracer::Print(), v8::internal::HeapEntry::Print(), v8::internal::Decoder< V >::PrintAcquireRelease(), v8::internal::Decoder< V >::PrintBranchOffset(), v8::internal::Decoder< V >::PrintCSRReg(), v8::base::impl::PrintFormattedStringToArray(), v8::internal::Decoder< V >::PrintImm12(), v8::internal::Decoder< V >::PrintImm12X(), v8::internal::Decoder< V >::PrintImm20J(), v8::internal::Decoder< V >::PrintImm20U(), v8::internal::Decoder< V >::PrintMemoryOrder(), v8::internal::Decoder< V >::PrintRoundingMode(), v8::internal::Decoder< V >::PrintRvcImm11CJ(), v8::internal::Decoder< V >::PrintRvcImm5D(), v8::internal::Decoder< V >::PrintRvcImm5W(), v8::internal::Decoder< V >::PrintRvcImm6(), v8::internal::Decoder< V >::PrintRvcImm6Addi16sp(), v8::internal::Decoder< V >::PrintRvcImm6Ldsp(), v8::internal::Decoder< V >::PrintRvcImm6Lwsp(), v8::internal::Decoder< V >::PrintRvcImm6Sdsp(), v8::internal::Decoder< V >::PrintRvcImm6Swsp(), v8::internal::Decoder< V >::PrintRvcImm6U(), v8::internal::Decoder< V >::PrintRvcImm8Addi4spn(), v8::internal::Decoder< V >::PrintRvcImm8B(), v8::internal::Decoder< V >::PrintRvcShamt(), v8::internal::Decoder< V >::PrintRvvLMUL(), v8::internal::Decoder< V >::PrintRvvSEW(), v8::internal::Decoder< V >::PrintRvvSimm5(), v8::internal::Decoder< V >::PrintRvvUimm5(), v8::internal::Decoder< V >::PrintRvvVm(), v8::internal::Decoder< V >::PrintShamt(), v8::internal::Decoder< V >::PrintShamt32(), v8::internal::Decoder< V >::PrintStoreOffset(), v8::internal::Decoder< V >::PrintTarget(), v8::internal::Decoder< V >::PrintUimm(), v8::internal::anonymous_namespace{asm-js.cc}::ReportCompilationSuccess(), v8::internal::anonymous_namespace{asm-js.cc}::ReportInstantiationSuccess(), v8::internal::Map::TransitionToDataProperty(), v8::internal::compiler::anonymous_namespace{pipeline.cc}::ValidateProfileData(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::WasmSimd128ToString(), v8::internal::EmbeddedFileWriter::WriteBuiltin(), v8::internal::EmbeddedFileWriter::WriteFileEpilogue(), and v8::internal::WriteLine().
sort() [1/2]
template<typename C >
void v8::base::sort (C & container) [inline]
Definition at line 111 of file container-utils.h.
                               {
  std::sort(std::begin(container), std::end(container));
}
References v8::internal::compiler::begin(), v8::internal::compiler::end(), and sort().
Referenced by v8::internal::compiler::CodeGenerator::AssembleCode(), v8::internal::anonymous_namespace{liveedit.cc}::CalculateFunctionLiteralChanges(), v8::internal::anonymous_namespace{js-locale.cc}::CalendarsForLocale(), v8::internal::Coverage::Collect(), v8::internal::MarkCompactCollector::CollectEvacuationCandidates(), v8::internal::anonymous_namespace{keys.cc}::CollectKeysFromDictionary(), v8::internal::torque::ClassType::ComputeArraySlotKind(), v8::internal::anonymous_namespace{keys.cc}::CopyEnumKeysTo(), v8::internal::RegExp::CreateCaptureNameMap(), v8::Shell::DumpCounters(), v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::ExternalReferenceList::ExternalReferenceList(), v8::internal::FastIterateArray(), v8::internal::compiler::MoveOptimizer::FinalizeMoves(), v8::internal::FlagMapByName::FlagMapByName(), v8::internal::FlattenRegionsToParts(), v8::internal::compiler::LinearScanAllocator::ForwardStateTo(), v8::internal::wasm::WasmImportWrapperCache::Free(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::FromElements(), v8::internal::GetKeywordValuesFromLocale(), v8::internal::Module::GetModuleNamespace(), v8::internal::TracedHandles::GetNodeBounds(), v8::debug::Script::GetPossibleBreakpoints(), v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::HighestPostDominatingHole(), v8::internal::BuiltinsSorter::InitializeClusters(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PendingDependencies::InstallAllPredictable(), v8::internal::OptimizingCompileOutputQueue::InstallGeneratedBuiltins(), v8::internal::anonymous_namespace{builtins-array.cc}::IterateElements(), v8::internal::compiler::turboshaft::FloatType< Bits >::LeastUpperBound(), v8::internal::compiler::turboshaft::WordType< Bits >::LeastUpperBound(), v8::internal::compiler::turboshaft::TypeParser::ParseSetElements(), v8::internal::compiler::ReferenceMapPopulator::PopulateReferenceMaps(), v8::internal::compiler::CompilationDependencies::PrepareInstallPredictable(), v8::internal::EmbeddedData::PrintStatistics(), v8::internal::MarkingWorklists::PrintWorklist(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::ProductSet(), v8::internal::compiler::turboshaft::WordType< Bits >::Range(), v8::internal::anonymous_namespace{heap.cc}::ReportDuplicates(), v8::internal::anonymous_namespace{intl-objects.cc}::anonymous_namespace{intl-objects.cc}::ResourceAvailableCurrencies::ResourceAvailableCurrencies(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Run(), v8::internal::wasm::ProfileGenerator::SerializeTypeFeedback(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Set(), v8::internal::ZoneList< T >::Sort(), v8::internal::anonymous_namespace{debug-coverage.cc}::SortBlockData(), v8::internal::BuiltinsSorter::SortClusters(), v8::internal::anonymous_namespace{elements.cc}::SortIndices(), v8::internal::wasm::LiftoffStackSlots::SortInPushOrder(), v8::internal::Sweeper::StartMajorSweeping(), v8::internal::Sweeper::StartMinorSweeping(), v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::SweepPage(), v8::internal::wasm::WasmCodePointerTable::SweepSegments(), v8::internal::Intl::ToJSArray(), v8::internal::wasm::NativeModule::TransferNewOwnedCodeLocked(), cppgc::internal::anonymous_namespace{sweeper.cc}::PrepareForSweepVisitor::VisitNormalPageSpace(), v8::internal::ZoneCompactSet< T >::ZoneCompactSet(), and wasm::EngineImpl::~EngineImpl().
sort() [2/2]
template<typename C , typename Comp >
void v8::base::sort (C & container, Comp comp) [inline]
Definition at line 115 of file container-utils.h.
                                          {
  std::sort(std::begin(container), std::end(container), comp);
}
References v8::internal::compiler::begin(), and v8::internal::compiler::end().
Referenced by sort().
STATIC_ASSERT_ENUM() [1/9]
v8::base::STATIC_ASSERT_ENUM (PageAllocator::kNoAccess , base::OS::MemoryPermission::kNoAccess)
STATIC_ASSERT_ENUM() [2/9]
v8::base::STATIC_ASSERT_ENUM (PageAllocator::kNoAccessWillJitLater , base::OS::MemoryPermission::kNoAccessWillJitLater)
STATIC_ASSERT_ENUM() [3/9]
v8::base::STATIC_ASSERT_ENUM (PageAllocator::kReadExecute , base::OS::MemoryPermission::kReadExecute)
STATIC_ASSERT_ENUM() [4/9]
v8::base::STATIC_ASSERT_ENUM (PageAllocator::kReadWrite , base::OS::MemoryPermission::kReadWrite)
STATIC_ASSERT_ENUM() [5/9]
v8::base::STATIC_ASSERT_ENUM (PageAllocator::kReadWriteExecute , base::OS::MemoryPermission::kReadWriteExecute)
STATIC_ASSERT_ENUM() [6/9]
v8::base::STATIC_ASSERT_ENUM (PagePermissions::kNoAccess , OS::MemoryPermission::kNoAccess)
STATIC_ASSERT_ENUM() [7/9]
v8::base::STATIC_ASSERT_ENUM (PagePermissions::kReadExecute , OS::MemoryPermission::kReadExecute)
STATIC_ASSERT_ENUM() [8/9]
v8::base::STATIC_ASSERT_ENUM (PagePermissions::kReadWrite , OS::MemoryPermission::kReadWrite)
STATIC_ASSERT_ENUM() [9/9]
v8::base::STATIC_ASSERT_ENUM (PagePermissions::kReadWriteExecute , OS::MemoryPermission::kReadWriteExecute)
StaticCharVector()
template<size_t N>
constexpr Vector<const char> v8::base::StaticCharVector (const char(&) array[N]) [constexpr]
Definition at line 325 of file vector.h.
                                                                      {
  return {array, N - 1};
}
References v8::internal::N.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::AddImportedStringImports(), v8::internal::MessageFormatter::Format(), v8::internal::anonymous_namespace{isolate.cc}::GetPromiseMethod(), v8::internal::wasm::IdentifyUnknownSectionInternal(), v8::internal::WasmValueObject::New(), v8::internal::anonymous_namespace{runtime-test.cc}::OptimizeFunctionOnNextCall(), and v8::internal::anonymous_namespace{asm-js.cc}::StdlibMathMember().
StaticOneByteVector()
template<size_t N>
Vector<const uint8_t> v8::base::StaticOneByteVector (const char(&) array[N])
Definition at line 345 of file vector.h.
                                                                  {
  return OneByteVector(array, N - 1);
}
References v8::internal::N, and OneByteVector().
Referenced by v8::internal::Factory::NewStringFromStaticChars(), v8::internal::Scanner::TryToParseMagicComment(), v8::internal::anonymous_namespace{uri.cc}::UnescapePrivate(), and v8::internal::wasm::ValidateAndSetBuiltinImports().
StringToLong() [1/2]
static unsigned v8::base::StringToLong (char * buffer) [static]
Definition at line 84 of file platform-aix.cc.
                                           {
  return static_cast<unsigned>(strtol(buffer, nullptr, 16));
}
Referenced by v8::base::OS::GetSharedLibraryAddresses().
StringToLong() [2/2]
static unsigned v8::base::StringToLong (char * buffer) [static]
Definition at line 46 of file platform-freebsd.cc.
                                           {
  return static_cast<unsigned>(strtol(buffer, nullptr, 16));
}
StrNCpy()
V8_BASE_EXPORT int const char V8_BASE_EXPORT void v8::base::StrNCpy (base::Vector< char > dest, const char * src, size_t n)
Definition at line 28 of file strings.cc.
                                                               {
  base::OS::StrNCpy(dest.begin(), dest.length(), src, n);
}
References v8::base::Vector< T >::begin(), v8::base::Vector< T >::length(), and v8::base::OS::StrNCpy().
Referenced by v8::internal::CodeTracer::CodeTracer(), and v8::internal::StringsStorage::GetCopy().
Strtod()
V8_BASE_EXPORT double v8::base::Strtod (Vector< const char > buffer, int exponent)
Definition at line 391 of file strtod.cc.
                                                       {
  Vector<const char> left_trimmed = TrimLeadingZeros(buffer);
  Vector<const char> trimmed = TrimTrailingZeros(left_trimmed);
  exponent += left_trimmed.length() - trimmed.length();
  if (trimmed.empty()) return 0.0;
  if (trimmed.length() > kMaxSignificantDecimalDigits) {
    char significant_buffer[kMaxSignificantDecimalDigits];
    int significant_exponent;
    TrimToMaxSignificantDigits(trimmed, exponent, significant_buffer,
                               &significant_exponent);
    return Strtod(
        Vector<const char>(significant_buffer, kMaxSignificantDecimalDigits),
        significant_exponent);
  }
  if (exponent + trimmed.length() - 1 >= kMaxDecimalPower)
    return std::numeric_limits<double>::infinity();
  if (exponent + trimmed.length() <= kMinDecimalPower) return 0.0;
  double guess;
  if (DoubleStrtod(trimmed, exponent, &guess) ||
      DiyFpStrtod(trimmed, exponent, &guess)) {
    return guess;
  }
  return BignumStrtod(trimmed, exponent, guess);
}
References BignumStrtod(), DiyFpStrtod(), DoubleStrtod(), v8::base::Vector< T >::empty(), kMaxDecimalPower, kMaxSignificantDecimalDigits, kMinDecimalPower, v8::base::Vector< T >::length(), TrimLeadingZeros(), TrimToMaxSignificantDigits(), and TrimTrailingZeros().
Referenced by v8::internal::NumberParseIntHelper::HandleBaseTenCase().
ThreadEntry() [1/3]
static void* v8::base::ThreadEntry (void * arg) [static]
Definition at line 1229 of file platform-posix.cc.
                                    {
  // Reset denormals state to default, in case we picked up a non-default one
  // with the posix clone() call.
  base::FPU::SetFlushDenormals(false);
  Thread* thread = reinterpret_cast<Thread*>(arg);
  // We take the lock here to make sure that pthread_create finished first since
  // we don't know which thread will run first (the original thread or the new
  // one).
  { MutexGuard lock_guard(&thread->data()->thread_creation_mutex_); }
  SetThreadName(thread->name());
#if V8_OS_DARWIN
  switch (thread->priority()) {
    case Thread::Priority::kBestEffort:
      pthread_set_qos_class_self_np(QOS_CLASS_BACKGROUND, 0);
      break;
    case Thread::Priority::kUserVisible:
      pthread_set_qos_class_self_np(QOS_CLASS_USER_INITIATED, -1);
      break;
    case Thread::Priority::kUserBlocking:
      pthread_set_qos_class_self_np(QOS_CLASS_USER_INITIATED, 0);
      break;
    case Thread::Priority::kDefault:
      break;
  }
#elif V8_OS_LINUX || V8_OS_ZOS
  switch (thread->priority()) {
    case Thread::Priority::kBestEffort:
      setpriority(PRIO_PROCESS, 0, 10);
      break;
    case Thread::Priority::kUserVisible:
      setpriority(PRIO_PROCESS, 0, 1);
      break;
    case Thread::Priority::kUserBlocking:
      setpriority(PRIO_PROCESS, 0, 0);
      break;
    case Thread::Priority::kDefault:
      break;
  }
#endif
  DCHECK_NE(thread->data()->thread_, kNoThread);
  thread->NotifyStartedAndRun();
  return nullptr;
}
References v8::base::Thread::data(), DCHECK_NE, v8::base::Thread::kBestEffort, v8::base::Thread::kDefault, kNoThread, v8::base::Thread::kUserBlocking, v8::base::Thread::kUserVisible, v8::base::Thread::name(), v8::base::Thread::NotifyStartedAndRun(), v8::base::Thread::priority(), v8::base::FPU::SetFlushDenormals(), SetThreadName(), v8::base::Thread::PlatformData::thread_, and v8::base::Thread::PlatformData::thread_creation_mutex_.
Referenced by v8::base::Thread::Start().
ThreadEntry() [2/3]
static void* v8::base::ThreadEntry (void * arg) [static]
Definition at line 384 of file platform-starboard.cc.
                                    {
  Thread* thread = reinterpret_cast<Thread*>(arg);
  // We take the lock here to make sure that pthread_create finished first since
  // we don't know which thread will run first (the original thread or the new
  // one).
  { LockGuard<Mutex> lock_guard(&thread->data()->thread_creation_mutex_); }
  SetThreadName(thread->name());
  // DCHECK_NE(thread->data()->thread_, kNoThread);
  thread->NotifyStartedAndRun();
  return nullptr;
}
References v8::base::Thread::data(), v8::base::Thread::name(), v8::base::Thread::NotifyStartedAndRun(), SetThreadName(), and v8::base::Thread::PlatformData::thread_creation_mutex_.
ThreadEntry() [3/3]
static unsigned int __stdcall v8::base::ThreadEntry (void * arg) [static]
Definition at line 1735 of file platform-win32.cc.
                                                     {
  Thread* thread = reinterpret_cast<Thread*>(arg);
  thread->NotifyStartedAndRun();
  return 0;
}
References v8::base::Thread::NotifyStartedAndRun().
TrimLeadingZeros()
static Vector<const char> v8::base::TrimLeadingZeros (Vector< const char > buffer) [static]
Definition at line 73 of file strtod.cc.
                                                                      {
  for (int i = 0; i < buffer.length(); i++) {
    if (buffer[i] != '0') {
      return buffer.SubVector(i, buffer.length());
    }
  }
  return Vector<const char>(buffer.begin(), 0);
}
References v8::base::Vector< T >::begin(), v8::base::Vector< T >::length(), and v8::base::Vector< T >::SubVector().
Referenced by Strtod().
TrimToMaxSignificantDigits()
static void v8::base::TrimToMaxSignificantDigits (Vector< const char > buffer, int exponent, char * significant_buffer, int * significant_exponent) [static]
Definition at line 91 of file strtod.cc.
                                                                  {
  for (int i = 0; i < kMaxSignificantDecimalDigits - 1; ++i) {
    significant_buffer[i] = buffer[i];
  }
  // The input buffer has been trimmed. Therefore the last digit must be
  // different from '0'.
  DCHECK_NE(buffer[buffer.length() - 1], '0');
  // Set the last digit to be non-zero. This is sufficient to guarantee
  // correct rounding.
  significant_buffer[kMaxSignificantDecimalDigits - 1] = '1';
  *significant_exponent =
      exponent + (buffer.length() - kMaxSignificantDecimalDigits);
}
References DCHECK_NE, v8::internal::anonymous_namespace{json-stringifier.cc}::i, kMaxSignificantDecimalDigits, and v8::base::Vector< T >::length().
Referenced by Strtod().
TrimTrailingZeros()
static Vector<const char> v8::base::TrimTrailingZeros (Vector< const char > buffer) [static]
Definition at line 82 of file strtod.cc.
                                                                       {
  for (int i = buffer.length() - 1; i >= 0; --i) {
    if (buffer[i] != '0') {
      return buffer.SubVector(0, i + 1);
    }
  }
  return Vector<const char>(buffer.begin(), 0);
}
References v8::base::Vector< T >::begin(), v8::base::Vector< T >::length(), and v8::base::Vector< T >::SubVector().
Referenced by Strtod().
TrimZeros()
static void v8::base::TrimZeros (Vector< char > buffer, int * length, int * decimal_point) [static]
Definition at line 261 of file fixed-dtoa.cc.
                                                                            {
  while (*length > 0 && buffer[(*length) - 1] == '0') {
    (*length)--;
  }
  int first_non_zero = 0;
  while (first_non_zero < *length && buffer[first_non_zero] == '0') {
    first_non_zero++;
  }
  if (first_non_zero != 0) {
    for (int i = first_non_zero; i < *length; ++i) {
      buffer[i - first_non_zero] = buffer[i];
    }
    *length -= first_non_zero;
    *decimal_point -= first_non_zero;
  }
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::length.
Referenced by FastFixedDtoa().
tuple_fold()
template<typename T , typename Tuple , typename Function >
constexpr auto v8::base::tuple_fold (T && initial, Tuple && tpl, Function && function) [constexpr]
Definition at line 188 of file template-utils.h.
                                                                         {
  return detail::tuple_fold_impl<std::tuple_size_v<std::decay_t<Tuple>> - 1>(
      std::forward<T>(initial), std::forward<Tuple>(tpl), function);
}
Referenced by v8::internal::compiler::turboshaft::Zip< Iterables >::IsEnd().
tuple_for_each()
template<typename Tuple , typename Function >
constexpr void v8::base::tuple_for_each (Tuple && tpl, Function && function) [constexpr]
Definition at line 149 of file template-utils.h.
                                                                {
  detail::tuple_for_each_impl(
      std::forward<Tuple>(tpl), function,
      std::make_index_sequence<std::tuple_size_v<std::decay_t<Tuple>>>());
}
References v8::base::detail::tuple_for_each_impl().
tuple_for_each_with_index()
template<typename Tuple , typename Function >
constexpr void v8::base::tuple_for_each_with_index (Tuple && tpl, Function && function) [constexpr]
Definition at line 159 of file template-utils.h.
                                                                           {
  detail::tuple_for_each_with_index_impl(
      std::forward<Tuple>(tpl), function,
      std::make_index_sequence<std::tuple_size_v<std::decay_t<Tuple>>>());
}
References v8::base::detail::tuple_for_each_with_index_impl().
Referenced by v8::internal::maglev::detail::MoveArgumentsForBuiltin().
tuple_head()
template<size_t N, typename Tuple >
constexpr auto v8::base::tuple_head (Tuple && tpl) [constexpr]
Definition at line 126 of file template-utils.h.
                                       {
  constexpr size_t total_size = std::tuple_size_v<std::decay_t<Tuple>>;
  static_assert(N <= total_size);
  return detail::tuple_slice_impl<0>(std::forward<Tuple>(tpl),
                                     std::make_index_sequence<N>());
}
References v8::internal::N.
tuple_map()
template<typename Tuple , typename Function >
constexpr auto v8::base::tuple_map (Tuple && tpl, Function && function) [constexpr]
Definition at line 168 of file template-utils.h.
                                                           {
  return detail::tuple_map_impl(
      std::forward<Tuple>(tpl), function,
      std::make_index_sequence<std::tuple_size_v<std::decay_t<Tuple>>>());
}
References v8::base::detail::tuple_map_impl().
Referenced by v8::internal::compiler::turboshaft::Zip< Iterables >::Begin().
tuple_map2()
template<typename TupleV , typename TupleU , typename Function >
constexpr auto v8::base::tuple_map2 (TupleV && tplv, TupleU && tplu, Function && function) [constexpr]
Definition at line 177 of file template-utils.h.
                                                                             {
  constexpr size_t S = std::tuple_size_v<std::decay_t<TupleV>>;
  static_assert(S == std::tuple_size_v<std::decay_t<TupleU>>);
  return detail::tuple_map2_impl(std::forward<TupleV>(tplv),
                                 std::forward<TupleU>(tplu), function,
                                 std::make_index_sequence<S>());
}
References v8::internal::S, and v8::base::detail::tuple_map2_impl().
Referenced by v8::internal::compiler::turboshaft::Zip< Iterables >::Advance(), v8::internal::compiler::turboshaft::Zip< Iterables >::Dereference(), and v8::internal::compiler::turboshaft::Zip< Iterables >::IsEnd().
U16FromBigEndian()
constexpr uint16_t v8::base::U16FromBigEndian (std::span< const uint8_t, 2u > bytes) [inline], [constexpr]
Definition at line 302 of file byte_conversions.h.
                                                                             {
  return ByteSwap(internal::FromLittleEndian<uint16_t>(bytes));
}
Referenced by v8::base::numerics::TEST().
U16FromLittleEndian()
constexpr uint16_t v8::base::U16FromLittleEndian (std::span< const uint8_t, 2u > bytes) [inline], [constexpr]
Definition at line 177 of file byte_conversions.h.
                                      {
  return internal::FromLittleEndian<uint16_t>(bytes);
}
Referenced by v8::base::numerics::TEST().
U16FromNativeEndian()
constexpr uint16_t v8::base::U16FromNativeEndian (std::span< const uint8_t, 2u > bytes) [inline], [constexpr]
Definition at line 56 of file byte_conversions.h.
                                      {
  return internal::FromLittleEndian<uint16_t>(bytes);
}
Referenced by v8::base::numerics::TEST().
U16ToBigEndian()
constexpr std::array<uint8_t, 2u> v8::base::U16ToBigEndian (uint16_t val) [inline], [constexpr]
Definition at line 622 of file byte_conversions.h.
                                                                    {
  return internal::ToLittleEndian(ByteSwap(val));
}
Referenced by v8::base::numerics::TEST().
U16ToLittleEndian()
constexpr std::array<uint8_t, 2u> v8::base::U16ToLittleEndian (uint16_t val) [inline], [constexpr]
Definition at line 511 of file byte_conversions.h.
                                                                       {
  return internal::ToLittleEndian(val);
}
Referenced by v8::base::numerics::TEST().
U16ToNativeEndian()
constexpr std::array<uint8_t, 2u> v8::base::U16ToNativeEndian (uint16_t val) [inline], [constexpr]
Definition at line 408 of file byte_conversions.h.
                                                                       {
  return internal::ToLittleEndian(val);
}
Referenced by v8::base::numerics::TEST().
U32FromBigEndian()
constexpr uint32_t v8::base::U32FromBigEndian (std::span< const uint8_t, 4u > bytes) [inline], [constexpr]
Definition at line 312 of file byte_conversions.h.
                                                                             {
  return ByteSwap(internal::FromLittleEndian<uint32_t>(bytes));
}
Referenced by FloatFromBigEndian(), and v8::base::numerics::TEST().
U32FromLittleEndian()
constexpr uint32_t v8::base::U32FromLittleEndian (std::span< const uint8_t, 4u > bytes) [inline], [constexpr]
Definition at line 189 of file byte_conversions.h.
                                      {
  return internal::FromLittleEndian<uint32_t>(bytes);
}
Referenced by FloatFromLittleEndian(), and v8::base::numerics::TEST().
U32FromNativeEndian()
constexpr uint32_t v8::base::U32FromNativeEndian (std::span< const uint8_t, 4u > bytes) [inline], [constexpr]
Definition at line 67 of file byte_conversions.h.
                                      {
  return internal::FromLittleEndian<uint32_t>(bytes);
}
Referenced by FloatFromNativeEndian(), and v8::base::numerics::TEST().
U32ToBigEndian()
constexpr std::array<uint8_t, 4u> v8::base::U32ToBigEndian (uint32_t val) [inline], [constexpr]
Definition at line 633 of file byte_conversions.h.
                                                                    {
  return internal::ToLittleEndian(ByteSwap(val));
}
Referenced by v8::base::numerics::TEST().
U32ToLittleEndian()
constexpr std::array<uint8_t, 4u> v8::base::U32ToLittleEndian (uint32_t val) [inline], [constexpr]
Definition at line 522 of file byte_conversions.h.
                                                                       {
  return internal::ToLittleEndian(val);
}
Referenced by v8::base::numerics::TEST().
U32ToNativeEndian()
constexpr std::array<uint8_t, 4u> v8::base::U32ToNativeEndian (uint32_t val) [inline], [constexpr]
Definition at line 418 of file byte_conversions.h.
                                                                       {
  return internal::ToLittleEndian(val);
}
Referenced by FloatToNativeEndian(), and v8::base::numerics::TEST().
U64FromBigEndian()
constexpr uint64_t v8::base::U64FromBigEndian (std::span< const uint8_t, 8u > bytes) [inline], [constexpr]
Definition at line 322 of file byte_conversions.h.
                                                                             {
  return ByteSwap(internal::FromLittleEndian<uint64_t>(bytes));
}
Referenced by DoubleFromBigEndian(), and v8::base::numerics::TEST().
U64FromLittleEndian()
constexpr uint64_t v8::base::U64FromLittleEndian (std::span< const uint8_t, 8u > bytes) [inline], [constexpr]
Definition at line 201 of file byte_conversions.h.
                                      {
  return internal::FromLittleEndian<uint64_t>(bytes);
}
Referenced by DoubleFromLittleEndian(), and v8::base::numerics::TEST().
U64FromNativeEndian()
constexpr uint64_t v8::base::U64FromNativeEndian (std::span< const uint8_t, 8u > bytes) [inline], [constexpr]
Definition at line 78 of file byte_conversions.h.
                                      {
  return internal::FromLittleEndian<uint64_t>(bytes);
}
Referenced by DoubleFromNativeEndian(), and v8::base::numerics::TEST().
U64ToBigEndian()
constexpr std::array<uint8_t, 8u> v8::base::U64ToBigEndian (uint64_t val) [inline], [constexpr]
Definition at line 644 of file byte_conversions.h.
                                                                    {
  return internal::ToLittleEndian(ByteSwap(val));
}
Referenced by v8::base::numerics::TEST().
U64ToLittleEndian()
constexpr std::array<uint8_t, 8u> v8::base::U64ToLittleEndian (uint64_t val) [inline], [constexpr]
Definition at line 533 of file byte_conversions.h.
                                                                       {
  return internal::ToLittleEndian(val);
}
Referenced by v8::base::numerics::TEST().
U64ToNativeEndian()
constexpr std::array<uint8_t, 8u> v8::base::U64ToNativeEndian (uint64_t val) [inline], [constexpr]
Definition at line 428 of file byte_conversions.h.
                                                                       {
  return internal::ToLittleEndian(val);
}
Referenced by DoubleToNativeEndian(), and v8::base::numerics::TEST().
U8FromBigEndian()
constexpr uint8_t v8::base::U8FromBigEndian (std::span< const uint8_t, 1u > bytes) [inline], [constexpr]
Definition at line 292 of file byte_conversions.h.
                                                                           {
  return bytes[0];
}
Referenced by v8::base::numerics::TEST().
U8FromLittleEndian()
constexpr uint8_t v8::base::U8FromLittleEndian (std::span< const uint8_t, 1u > bytes) [inline], [constexpr]
Definition at line 165 of file byte_conversions.h.
                                      {
  return bytes[0];
}
Referenced by v8::base::numerics::TEST().
U8FromNativeEndian()
constexpr uint8_t v8::base::U8FromNativeEndian (std::span< const uint8_t, 1u > bytes) [inline], [constexpr]
Definition at line 45 of file byte_conversions.h.
                                      {
  return bytes[0];
}
Referenced by v8::base::numerics::TEST().
U8ToBigEndian()
constexpr std::array<uint8_t, 1u> v8::base::U8ToBigEndian (uint8_t val) [inline], [constexpr]
Definition at line 611 of file byte_conversions.h.
                                                                  {
  return {val};
}
Referenced by v8::base::numerics::TEST().
U8ToLittleEndian()
constexpr std::array<uint8_t, 1u> v8::base::U8ToLittleEndian (uint8_t val) [inline], [constexpr]
Definition at line 500 of file byte_conversions.h.
                                                                     {
  return {val};
}
Referenced by v8::base::numerics::TEST().
U8ToNativeEndian()
constexpr std::array<uint8_t, 1u> v8::base::U8ToNativeEndian (uint8_t val) [inline], [constexpr]
Definition at line 398 of file byte_conversions.h.
                                                                     {
  return {val};
}
Referenced by v8::base::numerics::TEST().
uint64_to_double()
constexpr double v8::base::uint64_to_double (uint64_t d64) [inline], [constexpr]
Definition at line 20 of file double.h.
                                                       {
  return std::bit_cast<double>(d64);
}
Referenced by v8::internal::RUNTIME_FUNCTION(), v8::internal::SignedZero(), and v8::base::Double::value().
UnsignedDivisionByConstant()
template<class T >
MagicNumbersForDivision< T > v8::base::UnsignedDivisionByConstant (T d, unsigned leading_zeros)
Definition at line 54 of file division-by-constant.cc.
                                                                              {
  static_assert(std::is_unsigned_v<T>);
  DCHECK_NE(d, 0);
  const unsigned bits = static_cast<unsigned>(sizeof(T)) * 8;
  const T ones = ~static_cast<T>(0) >> leading_zeros;
  const T min = static_cast<T>(1) << (bits - 1);
  const T max = ~static_cast<T>(0) >> 1;
  const T nc = ones - (ones - d) % d;
  bool a = false; // Init. "add" indicator.
  unsigned p = bits - 1; // Init. p.
  T q1 = min / nc; // Init. q1 = 2**p/nc
  T r1 = min - q1 * nc; // Init. r1 = rem(2**p,nc)
  T q2 = max / d; // Init. q2 = (2**p - 1)/d.
  T r2 = max - q2 * d; // Init. r2 = rem(2**p - 1, d).
  T delta;
  do {
    p = p + 1;
    if (r1 >= nc - r1) {
      q1 = 2 * q1 + 1;
      r1 = 2 * r1 - nc;
    } else {
      q1 = 2 * q1;
      r1 = 2 * r1;
    }
    if (r2 + 1 >= d - r2) {
      if (q2 >= max) a = true;
      q2 = 2 * q2 + 1;
      r2 = 2 * r2 + 1 - d;
    } else {
      if (q2 >= min) a = true;
      q2 = 2 * q2;
      r2 = 2 * r2 + 1;
    }
    delta = d - 1 - r2;
  } while (p < bits * 2 && (q1 < delta || (q1 == delta && r1 == 0)));
  return MagicNumbersForDivision<T>(q2 + 1, p - bits, a);
}
References DCHECK_NE, leading_zeros, and T.
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceUnsignedDiv(), v8::internal::compiler::MachineOperatorReducer::Uint32Div(), and v8::internal::compiler::MachineOperatorReducer::Uint64Div().
V8_BASE_HASH_VALUE_SIGNED()
v8::base::V8_BASE_HASH_VALUE_SIGNED (short)
Definition at line 222 of file hashing.h.
                                     {
  // 0 and -0 both hash to zero.
  return v != 0.0f ? hash_value(base::bit_cast<uint32_t>(v)) : 0;
}
References hash_value().
V8_BASE_HASH_VALUE_TRIVIAL()
v8::base::V8_BASE_HASH_VALUE_TRIVIAL (unsigned short)
Definition at line 202 of file hashing.h.
                                            {
  return hash_value_unsigned_impl(v);
}
References hash_value_unsigned_impl().
vector_append()
template<typename V , typename C >
void v8::base::vector_append (V & v, const C & container) [inline]
Definition at line 140 of file container-utils.h.
                                                    {
  v.insert(std::end(v), std::begin(container), std::end(container));
}
References v8::internal::compiler::begin(), and v8::internal::compiler::end().
Referenced by v8::internal::compiler::turboshaft::FloatType< Bits >::LeastUpperBound(), v8::internal::compiler::turboshaft::WordType< Bits >::LeastUpperBound(), and v8::internal::compiler::SimplifiedLoweringVerifier::RecordMachineUsesOfConstant().
VectorOf() [1/3]
template<typename Container >
constexpr auto v8::base::VectorOf (Container && c) -> decltype(VectorOf(std::data(c), std::size(c))) [inline], [constexpr]
Definition at line 366 of file vector.h.
                                                  {
  return VectorOf(std::data(c), std::size(c));
}
References size(), and VectorOf().
VectorOf() [2/3]
template<typename T >
constexpr Vector<const T> v8::base::VectorOf (std::initializer_list< T > list) [inline], [constexpr]
Definition at line 375 of file vector.h.
                                                                       {
  return VectorOf(list.begin(), list.size());
}
References VectorOf().
VectorOf() [3/3]
template<typename T >
constexpr Vector<T> v8::base::VectorOf (T * start, size_t size) [inline], [constexpr]
Definition at line 359 of file vector.h.
                                                           {
  return {start, size};
}
References size().
Referenced by v8::Set::Add(), v8::internal::ApiNatives::AddAccessorProperty(), v8::internal::ApiNatives::AddDataProperty(), v8::internal::compiler::TopLevelLiveRange::AddUsePosition(), v8::internal::compiler::turboshaft::FrameStateData::Builder::AllocateFrameStateData(), v8::internal::JsonStringifier::ApplyReplacerFunction(), v8::internal::JsonStringifier::ApplyToJsonFunction(), v8::internal::compiler::AreUseIntervalsIntersecting(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphCall(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphFrameState(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphSwitch(), v8::internal::compiler::LiveRange::AttachToNext(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::BeginBlock(), v8::internal::compiler::turboshaft::MaybeRedundantStoresTable::BeginBlock(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::BeginBlock(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Bind(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::Bind(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::block(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::br(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::br_if(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::br_on_cast(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::br_on_non_null(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::br_on_null(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTable(), v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::BuildCallAndReturn(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCallAndReturn(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCallWasmFromWrapper(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCapiCallWrapper(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildChangeBigIntToInt64(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildJSToWasmWrapper(), v8::internal::ExternalizeStringExtension::BuildSource(), v8::internal::CpuTraceMarkExtension::BuildSource(), v8::internal::GCExtension::BuildSource(), v8::internal::VTuneDomainSupportExtension::BuildSource(), v8::internal::FuzzilliExtension::BuildSource(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildSuspend(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildWasmCall(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildWasmMaybeReturnCall(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildWasmToJSWrapper(), v8::internal::BUILTIN(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::call(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Call(), v8::internal::wasm::WasmWrapperTSGraphBuilder::CallBuiltin(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin_CallForwardVarargs(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin_CallWithArrayLike(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin_CallWithSpread(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::CallBuiltinForBigIntOp(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallBuiltinThroughJumptable(), v8::internal::wasm::WasmGraphBuilderBase::CallC(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallIndirect(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallRef(), v8::internal::wasm::WasmGraphBuilderBase::CallRuntime(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallRuntimeImpl(), v8::Promise::Catch(), v8::internal::compiler::turboshaft::GenericReducerBase< Next >::CatchBlockBegin(), v8::internal::wasm::DebugSideTable::Entry::changed_values(), v8::internal::JSFinalizationRegistry::Cleanup(), v8::internal::wasm::DebugInfoImpl::ClearStepping(), v8::internal::wasm::WasmFunctionCoverageData::code_ranges(), v8::internal::KeyAccumulator::CollectOwnJSProxyKeys(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitBuilder::Commit(), v8::internal::compiler::CompileCWasmEntry(), v8::internal::wasm::CompileLazy(), v8::internal::compiler::CompileWasmImportCallWrapper(), v8::internal::AsmJsScanner::ConsumeNumber(), v8::internal::wasm::AsmJsParser::CopyCurrentIdentifierString(), v8::internal::wasm::WasmFunctionCoverageData::counters(), v8::internal::Isolate::CountUsage(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CreateFrameState(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::CreateMergeSnapshot(), v8::internal::anonymous_namespace{snapshot.cc}::SnapshotImpl::CreateSnapshotBlob(), v8::internal::wasm::WasmCode::DebugName(), v8::internal::wasm::WasmModule::declared_functions(), v8::internal::JSProxy::DefineOwnProperty(), v8::Map::Delete(), v8::Set::Delete(), v8::internal::JSProxy::DeletePropertyOrElement(), v8::internal::wasm::AsyncStreamingProcessor::Deserialize(), v8::internal::SharedHeapDeserializer::DeserializeStringTable(), v8_inspector::V8DebuggerAgentImpl::disassembleWasmModule(), v8::internal::JSDisposableStackBase::DisposeResources(), v8::internal::wasm::TurboshaftGraphBuildingInterface::DoReturn(), v8::internal::wasm::LiftoffAssembler::DropValues(), v8::internal::wasm::NativeModuleDeserializer::eager_functions(), v8::internal::wasm::liftoff::Emit64BitShiftOperation(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::EmitLoopSinglePredecessorBlock(), v8::internal::compiler::turboshaft::IfElseCascadeToSwitchReducer< Next >::EmitSwitch(), v8::internal::Uri::Encode(), v8::internal::SourceTextModule::ExecuteAsyncModule(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ExecuteCompilationUnits(), v8::internal::wasm::ProfileInformation::executed_functions(), v8::internal::compiler::turboshaft::PhiOp::Explode(), v8::internal::compiler::turboshaft::FrameStateOp::Explode(), v8::internal::compiler::turboshaft::CallOp::Explode(), v8::internal::compiler::turboshaft::TailCallOp::Explode(), v8::internal::compiler::turboshaft::ReturnOp::Explode(), v8::internal::compiler::turboshaft::TupleOp::Explode(), v8::internal::compiler::turboshaft::FastApiCallOp::Explode(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::F64Const(), v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::FastApiCall(), v8::internal::AsmJsCompilationJob::FinalizeJobImpl(), v8::internal::wasm::AsyncStreamingDecoder::Finish(), v8::internal::wasm::SyncStreamingDecoder::Finish(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::FinishFunction(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::finite_loop(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::FixLoopPhi(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::FixLoopPhi(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::FixLoopPhis(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::FlushTerms(), v8::internal::MessageFormatter::Format(), v8::internal::PendingCompilationErrorHandler::FormatErrorMessageForTest(), v8::internal::ErrorUtils::FormatStackTrace(), v8::internal::anonymous_namespace{builtins-console.cc}::Formatter(), v8::internal::wasm::WasmImportWrapperCache::Free(), v8::internal::wasm::WasmEngine::FreeDeadCodeLocked(), v8::WasmModuleObject::FromCompiledModule(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::FromElements(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::Generate(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::GenerateBuiltinCall(), v8::internal::wasm::fuzzing::GenerateRandomWasmModule(), v8::internal::wasm::fuzzing::GenerateWasmModuleForDeopt(), v8::internal::wasm::fuzzing::GenerateWasmModuleForInitExpressions(), v8::internal::wasm::fuzzing::GenerateWasmModuleForRevec(), v8::Map::Get(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GeneratorAlternativesPerOption< kNumMVP, kAdditionalSimd, kAdditionalWasmGC >::GetAlternatives(), v8::debug::GetDateDescription(), v8::anonymous_namespace{wasm-js.cc}::GetFirstArgumentAsBytes(), v8::internal::MessageHandler::GetMessage(), v8::internal::JSProxy::GetOwnPropertyDescriptor(), v8::internal::JSProxy::GetProperty(), v8::internal::compiler::CodeGenerator::GetProtectedInstructionsData(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GetProtectedInstructionsData(), v8::internal::JSProxy::GetPrototype(), v8::internal::wasm::WasmSerializer::GetSerializedNativeModuleSize(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::GetTupleType(), v8::internal::wasm::GetTypeForTable(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::Goto(), v8::Map::Has(), v8::Set::Has(), v8::internal::JSProxy::HasProperty(), v8::internal::wasm::IdentifyUnknownSectionInternal(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::if_(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BlockPhis::incoming_exceptions(), v8::internal::compiler::turboshaft::InitVectorOf(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineWasmCall(), v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::innerCallFunctionOn(), v8::internal::compiler::turboshaft::FrameStateData::Builder::Inputs(), v8::internal::compiler::turboshaft::PhiOp::inputs_rep(), v8::internal::compiler::turboshaft::LoadOp::inputs_rep(), v8::internal::compiler::turboshaft::AtomicWord32PairOp::inputs_rep(), v8::internal::compiler::turboshaft::CallOp::inputs_rep(), v8::internal::compiler::turboshaft::TailCallOp::inputs_rep(), v8::internal::compiler::turboshaft::FastApiCallOp::inputs_rep(), v8::internal::Object::InstanceOf(), v8::internal::wasm::WasmCode::instructions(), v8::internal::JsonParseInternalizer::InternalizeJsonProperty(), v8::internal::JSProxy::IsExtensible(), v8::internal::wasm::NativeModuleDeserializer::lazy_functions(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::local_types(), v8::internal::wasm::WasmCode::LogCode(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::LogEntries(), v8::internal::wasm::WasmEngine::LogOutstandingCodesForIsolate(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::loop(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerCall(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::MakePhiMaybePermuteInputs(), v8::internal::MapsAndHandlers::maps(), v8::internal::compiler::turboshaft::LabelBase< loop, Ts >::MaterializePhisImpl(), v8::internal::compiler::turboshaft::MaybeRepVector(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::MergeFrameState(), v8::internal::wasm::LiftoffAssembler::MergeFullStackWith(), v8::internal::wasm::LiftoffAssembler::MergeIntoNewState(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::MergeOpIndices(), v8::internal::wasm::LiftoffAssembler::MergeStackWith(), v8::internal::Factory::NewError(), v8::internal::anonymous_namespace{runtime-internal.cc}::NewError(), v8::internal::JSAsyncDisposableStack::NextDisposeAsyncIteration(), v8::WasmStreaming::WasmStreamingImpl::OnBytesReceived(), v8::internal::compiler::turboshaft::WordBinopOp::outputs_rep(), v8::internal::compiler::turboshaft::FloatBinopOp::outputs_rep(), v8::internal::compiler::turboshaft::WordBinopDeoptOnOverflowOp::outputs_rep(), v8::internal::compiler::turboshaft::WordUnaryOp::outputs_rep(), v8::internal::compiler::turboshaft::FloatUnaryOp::outputs_rep(), v8::internal::compiler::turboshaft::ShiftOp::outputs_rep(), v8::internal::compiler::turboshaft::ChangeOp::outputs_rep(), v8::internal::compiler::turboshaft::TaggedBitcastOp::outputs_rep(), v8::internal::compiler::turboshaft::SelectOp::outputs_rep(), v8::internal::compiler::turboshaft::PhiOp::outputs_rep(), v8::internal::compiler::turboshaft::PendingLoopPhiOp::outputs_rep(), v8::internal::compiler::turboshaft::ConstantOp::outputs_rep(), v8::internal::compiler::turboshaft::LoadOp::outputs_rep(), v8::internal::compiler::turboshaft::AtomicRMWOp::outputs_rep(), v8::internal::compiler::turboshaft::ProjectionOp::outputs_rep(), v8::internal::compiler::turboshaft::InputsRepFactory::PairOf(), v8::internal::wasm::LiftoffAssembler::ParallelRegisterMove(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Parameter(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Phi(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Phi(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BlockPhis::phi_inputs(), v8::internal::BuiltinsReducer< Next >::PopAndReturn(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PopArgs(), v8::internal::wasm::TurboshaftGraphBuildingInterface::PopControl(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PopSomeArgs(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::PostPhiProcessing(), v8::internal::wasm::NativeModuleCache::PrefixHash(), v8::internal::wasm::LiftoffAssembler::PrepareForBranch(), v8::internal::maglev::MaglevPhiRepresentationSelector::PreparePhiTaggings(), v8::internal::wasm::AsyncCompileJob::PrepareRuntimeObjects(), v8::internal::JSProxy::PreventExtensions(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessBlock(), v8::internal::wasm::InstanceBuilder::ProcessImports(), v8::internal::wasm::NativeModuleDeserializer::Publish(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::PublishCode(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::PublishCompilationResults(), v8::internal::wasm::PublishDetectedFeatures(), v8::internal::ValueDeserializer::ReadJSMap(), v8::internal::ValueDeserializer::ReadJSObjectProperties(), v8::internal::ValueDeserializer::ReadJSSet(), v8::internal::RegExpUtils::RegExpExec(), v8::internal::wasm::ErrorThrower::Reify(), v8::internal::wasm::DebugInfoImpl::RemoveBreakpoint(), v8::internal::wasm::DebugInfoImpl::RemoveIsolate(), v8::internal::Heap::ReportStatisticsAfterGC(), v8::internal::compiler::turboshaft::RepVector(), v8::internal::JSDisposableStackBase::ResolveAPromiseWithValueAndReturnIt(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::ResolvePhi(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Return(), v8::internal::compiler::turboshaft::GrowableStacksReducer< Next >::Return(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Return(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::Run(), v8::internal::compiler::turboshaft::SpecialRPOSchedulingPhase::Run(), v8::internal::RUNTIME_FUNCTION(), v8::internal::compiler::turboshaft::MaybeRedundantStoresTable::Seal(), v8::internal::wasm::WasmSerializer::SerializeNativeModule(), v8::internal::compiler::turboshaft::FloatType< Bits >::Set(), v8::internal::compiler::turboshaft::WordType< Bits >::Set(), v8::Map::Set(), v8::internal::wasm::DebugInfoImpl::SetBreakpoint(), v8::internal::Runtime::SetPrivateMember(), v8::internal::JSProxy::SetProperty(), v8::internal::Object::SetPropertyWithAccessor(), v8::internal::Object::SetPropertyWithDefinedSetter(), v8::internal::JSProxy::SetPrototype(), v8::internal::Factory::ShadowRealmNewTypeErrorCopy(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::SimdExtractLane(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::SimdReplaceLane(), v8::internal::compiler::turboshaft::InputsRepFactory::SingleRep(), v8::internal::SliceHelper(), v8::internal::wasm::NativeModule::SnapshotCodeTable(), v8::internal::wasm::LiftoffAssembler::SpillLocals(), v8::internal::wasm::LiftoffAssembler::SpillLoopArgs(), v8::internal::compiler::LiveRange::SplitAt(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::StartMultiPredecessorExceptionBlock(), v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< Derived, Value, KeyData >::StartNewSnapshot(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::table_op(), v8::internal::interpreter::BytecodeHandlerReducer< Next >::TailCallBytecodeDispatch(), v8::Promise::Then(), v8::internal::ValueSerializer::ThrowDataCloneError(), v8::internal::PendingCompilationErrorHandler::ThrowPendingError(), v8::internal::wasm::ProfileInformation::tiered_up_functions(), v8::internal::FrameTranslationBuilder::ToFrameTranslationWasm(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::ToInternalString(), v8::Date::ToISOString(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::ToRegExp(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::ToRegExp(), v8::Date::ToUTCString(), v8::internal::wasm::anonymous_namespace{wasm-module.cc}::ToValueTypeString(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::try_block_helper(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::try_table_block(), v8::internal::maglev::MaglevGraphBuilder::TryBuildElementAccess(), v8::internal::maglev::MaglevGraphBuilder::TryBuildElementAccessOnJSArrayOrJSObject(), v8::internal::maglev::MaglevGraphBuilder::TryBuildElementAccessOnTypedArray(), v8::internal::maglev::MaglevGraphBuilder::TryBuildElementStoreOnJSArrayOrJSObject(), v8::internal::maglev::MaglevGraphBuilder::TryBuildFastInstanceOf(), v8::internal::maglev::MaglevGraphBuilder::TryBuildNamedAccess(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPolymorphicElementAccess(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPolymorphicPropertyAccess(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyCellStore(), v8::internal::maglev::MaglevGraphBuilder::TryBuildStoreField(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Tuple(), v8::internal::compiler::turboshaft::Graph::TurnLoopIntoMerge(), v8::internal::compiler::turboshaft::Typer::TypeForRepresentation(), v8::internal::wasm::ValidateAndSetBuiltinImports(), v8::internal::compiler::turboshaft::VectorForRep(), VectorOf(), v8::internal::wasm::TurboshaftGraphBuildingInterface::WellKnown_FastApi(), v8::internal::compiler::turboshaft::EmitProjectionReducer< Next >::WrapInTupleIfNeeded(), v8::internal::wasm::NativeModuleSerializer::WriteHeader(), v8::internal::wasm::WasmCodeAllocator::~WasmCodeAllocator(), and v8::internal::wasm::WasmCodeRefScope::~WasmCodeRefScope().
VLQBase64Decode()
V8_BASE_EXPORT int32_t v8::base::VLQBase64Decode (const char * start, size_t sz, size_t * pos)
Definition at line 37 of file vlq-base64.cc.
                                                                   {
  uint32_t res = 0;
  uint64_t shift = 0;
  int32_t digit;
  do {
    if (*pos >= sz) {
      return std::numeric_limits<int32_t>::min();
    }
    digit = static_cast<int>(charToDigitDecode(start[*pos]));
    bool is_last_byte = (shift + kContinueShift >= 32);
    if (digit == -1 || (is_last_byte && (digit >> 2) != 0)) {
      return std::numeric_limits<int32_t>::min();
    }
    res += (digit & kDataMask) << shift;
    shift += kContinueShift;
    (*pos)++;
  } while (digit & kContinueMask);
  return (res & 1) ? -static_cast<int32_t>(res >> 1) : (res >> 1);
}
References v8::base::anonymous_namespace{vlq-base64.cc}::charToDigitDecode(), v8::base::anonymous_namespace{vlq-base64.cc}::kContinueMask, kContinueShift, and kDataMask.
Referenced by v8::internal::wasm::WasmModuleSourceMap::DecodeMapping(), and v8::internal::anonymous_namespace{scanner.cc}::ProcessPerFunctionCompileHints().
VLQConvertToUnsigned()
uint32_t v8::base::VLQConvertToUnsigned (int32_t value) [inline]
Definition at line 47 of file vlq.h.
                                                    {
  // This wouldn't handle kMinInt correctly if it ever encountered it.
  DCHECK_NE(value, std::numeric_limits<int32_t>::min());
  bool is_negative = value < 0;
  // Encode sign in least significant bit.
  uint32_t bits = static_cast<uint32_t>((is_negative ? -value : value) << 1) |
                  static_cast<uint32_t>(is_negative);
  return bits;
}
References DCHECK_NE, and v8::internal::value.
Referenced by VLQEncode().
VLQDecode()
int32_t v8::base::VLQDecode (const uint8_t * data_start, int * index) [inline]
Definition at line 106 of file vlq.h.
                                                                {
  uint32_t bits = VLQDecodeUnsigned(data_start, index);
  bool is_negative = (bits & 1) == 1;
  int32_t result = bits >> 1;
  return is_negative ? -result : result;
}
References v8::internal::index, v8::base::internal::result, and VLQDecodeUnsigned().
Referenced by v8::internal::DeoptTranslationIterator::NextOperand().
VLQDecodeUnsigned()
template<typename GetNextFunction >
uint32_t v8::base::VLQDecodeUnsigned (GetNextFunction && get_next) [inline]
Definition at line 80 of file vlq.h.
{
  uint8_t cur_byte = get_next();
  // Single byte fast path; no need to mask.
  if (cur_byte <= kDataMask) {
    return cur_byte;
  }
  uint32_t bits = cur_byte & kDataMask;
  for (int shift = kContinueShift; shift <= 32; shift += kContinueShift) {
    cur_byte = get_next();
    bits |= (cur_byte & kDataMask) << shift;
    if (cur_byte <= kDataMask) break;
  }
  return bits;
}
// Decodes a variable-length encoded unsigned value stored in contiguous memory
// starting at data_start + index, updating index to where the next encoded
// value starts.
inline uint32_t VLQDecodeUnsigned(const uint8_t* data_start, int* index) {
  return VLQDecodeUnsigned([&] { return data_start[(*index)++]; });
}
References kContinueShift, and kDataMask.
Referenced by v8::internal::RelocIteratorBase< RelocInfoT >::AdvanceReadLongPCJump(), v8::internal::DeoptTranslationIterator::NextOpcode(), v8::internal::DeoptTranslationIterator::NextOperandUnsigned(), v8::internal::DeoptTranslationIterator::NextUnsignedOperandAtPreviousIndex(), v8::internal::baseline::BytecodeOffsetIterator::ReadPosition(), and VLQDecode().
VLQEncode() [1/2]
template<typename Function >
void v8::base::VLQEncode (Function && process_byte, int32_t value) [inline]
Definition at line 60 of file vlq.h.
                                                              {
  uint32_t bits = VLQConvertToUnsigned(value);
  VLQEncodeUnsigned(std::forward<Function>(process_byte), bits);
}
References v8::internal::value, VLQConvertToUnsigned(), and VLQEncodeUnsigned().
Referenced by VLQEncode(), and v8::internal::anonymous_namespace{frame-translation-builder.cc}::SignedOperand::WriteVLQ().
VLQEncode() [2/2]
template<typename A >
void v8::base::VLQEncode (std::vector< uint8_t, A > * data, int32_t value) [inline]
Definition at line 67 of file vlq.h.
                                                                  {
  VLQEncode([data](uint8_t value) { data->push_back(value); }, value);
}
References v8::internal::value, and VLQEncode().
VLQEncodeUnsigned() [1/2]
template<typename Function >
void v8::base::VLQEncodeUnsigned (Function && process_byte, uint32_t value) [inline]
Definition at line 23 of file vlq.h.
                                                                       {
  // Write as many bytes as necessary to encode the value, with 7 bits of data
  // per byte (leaving space for one continuation bit).
  static constexpr uint32_t kDataBitsPerByte = kContinueShift;
  if (value < 1 << (kDataBitsPerByte)) goto write_one_byte;
  if (value < 1 << (2 * kDataBitsPerByte)) goto write_two_bytes;
  if (value < 1 << (3 * kDataBitsPerByte)) goto write_three_bytes;
  if (value < 1 << (4 * kDataBitsPerByte)) goto write_four_bytes;
  process_byte(value | kContinueBit);
  value >>= kContinueShift;
write_four_bytes:
  process_byte(value | kContinueBit);
  value >>= kContinueShift;
write_three_bytes:
  process_byte(value | kContinueBit);
  value >>= kContinueShift;
write_two_bytes:
  process_byte(value | kContinueBit);
  value >>= kContinueShift;
write_one_byte:
  // The last value written doesn't need a continuation bit.
  process_byte(value);
}
References kContinueBit, kContinueShift, and v8::internal::value.
Referenced by v8::internal::baseline::BytecodeOffsetTableBuilder::AddPosition(), VLQEncode(), VLQEncodeUnsigned(), v8::internal::RelocInfoWriter::WriteLongPCJump(), and v8::internal::anonymous_namespace{frame-translation-builder.cc}::UnsignedOperand::WriteVLQ().
VLQEncodeUnsigned() [2/2]
template<typename A >
void v8::base::VLQEncodeUnsigned (std::vector< uint8_t, A > * data, uint32_t value) [inline]
Definition at line 73 of file vlq.h.
                                                                           {
  VLQEncodeUnsigned([data](uint8_t value) { data->push_back(value); }, value);
}
References v8::internal::value, and VLQEncodeUnsigned().
VPrintHelper()
static void v8::base::VPrintHelper (FILE * stream, const char * format, va_list args) [static]
Definition at line 599 of file platform-win32.cc.
                                                                         {
  if ((stream == stdout || stream == stderr) && !HasConsole()) {
    // It is important to use safe print here in order to avoid
    // overflowing the buffer. We might truncate the output, but this
    // does not crash.
    char buffer[4096];
    OS::VSNPrintF(buffer, sizeof(buffer), format, args);
    OutputDebugStringA(buffer);
  } else {
    vfprintf(stream, format, args);
  }
}
References args, format, HasConsole(), and VSNPrintF().
VSNPrintF()
int v8::base::VSNPrintF (Vector< char > str, const char * format, va_list args)
Definition at line 16 of file strings.cc.
                                                                  {
  return OS::VSNPrintF(str.begin(), str.length(), format, args);
}
References args, v8::base::Vector< T >::begin(), format, and v8::base::Vector< T >::length().
Referenced by anonymous_namespace{logging.cc}::FailureMessage::FailureMessage(), v8::internal::StringsStorage::GetVFormatted(), SNPrintF(), v8::internal::wasm::anonymous_namespace{wasm-result.cc}::VPrintFToString(), and VPrintHelper().
WrappingAdd()
template<typename T >
constexpr T v8::base::WrappingAdd (T a, T b) [inline], [constexpr]
Definition at line 18 of file wrapping_math.h.
                                         {
  static_assert(std::is_integral_v<T>);
  // Unsigned arithmetic wraps, so convert to the corresponding unsigned type.
  // Note that, if `T` is smaller than `int`, e.g. `int16_t`, the values are
  // promoted to `int`, which brings us back to undefined overflow. This is fine
  // here because the sum of any two `int16_t`s fits in `int`, but `WrappingMul`
  // will need a more complex implementation.
  using Unsigned = std::make_unsigned_t<T>;
  return static_cast<T>(static_cast<Unsigned>(a) + static_cast<Unsigned>(b));
}
References v8::base::bits::Unsigned().
WrappingSub()
template<typename T >
constexpr T v8::base::WrappingSub (T a, T b) [inline], [constexpr]
Definition at line 32 of file wrapping_math.h.
                                         {
  static_assert(std::is_integral_v<T>);
  // Unsigned arithmetic wraps, so convert to the corresponding unsigned type.
  // Note that, if `T` is smaller than `int`, e.g. `int16_t`, the values are
  // promoted to `int`, which brings us back to undefined overflow. This is fine
  // here because the difference of any two `int16_t`s fits in `int`, but
  // `WrappingMul` will need a more complex implementation.
  using Unsigned = std::make_unsigned_t<T>;
  return static_cast<T>(static_cast<Unsigned>(a) - static_cast<Unsigned>(b));
}
References v8::base::bits::Unsigned().
WriteLittleEndianValue() [1/2]
template<typename V >
static void v8::base::WriteLittleEndianValue (Address p, V value) [inline], [static]
Definition at line 67 of file memory.h.
                                                              {
#if defined(V8_TARGET_LITTLE_ENDIAN)
  WriteUnalignedValue<V>(p, value);
#elif defined(V8_TARGET_BIG_ENDIAN)
  uint8_t* src = reinterpret_cast<uint8_t*>(&value);
  uint8_t* dst = reinterpret_cast<uint8_t*>(p);
  for (size_t i = 0; i < sizeof(V); i++) {
    dst[i] = src[sizeof(V) - i - 1];
  }
#endif // V8_TARGET_LITTLE_ENDIAN
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, V, and v8::internal::value.
Referenced by v8::internal::anonymous_namespace{snapshot.cc}::SnapshotImpl::SetHeaderValue(), and v8::internal::SerializedData::SetHeaderValue().
WriteLittleEndianValue() [2/2]
template<typename V >
static void v8::base::WriteLittleEndianValue (V * p, V value) [inline], [static]
Definition at line 85 of file memory.h.
                                                         {
  static_assert(
      !std::is_array_v<V>,
      "Passing an array decays to pointer, causing unexpected results.");
  WriteLittleEndianValue<V>(reinterpret_cast<Address>(p), value);
}
References v8::internal::value.
WriteUnalignedValue() [1/2]
template<typename V >
static void v8::base::WriteUnalignedValue (Address p, V value) [inline], [static]
Definition at line 41 of file memory.h.
                                                           {
  ASSERT_TRIVIALLY_COPYABLE(V);
  memcpy(reinterpret_cast<void*>(p), &value, sizeof(V));
}
References ASSERT_TRIVIALLY_COPYABLE(), V, and v8::internal::value.
Referenced by v8::internal::wasm::array_fill_wrapper(), v8::internal::Assembler::emit(), v8::internal::Assembler::emit_q(), v8::internal::Assembler::emit_w(), v8::internal::f64_acos_wrapper(), v8::internal::Assembler::long_at_put(), v8::internal::wasm::CWasmArgumentsPacker::Push(), v8::internal::Operand::set_disp32(), v8::internal::Operand::set_dispr(), v8::internal::UnalignedValueMember< T >::set_value(), v8::internal::UnalignedDoubleMember::set_value_as_bits(), v8::internal::RegisterValues::SetDoubleRegister(), v8::internal::WasmGlobalObject::SetF32(), v8::internal::WasmGlobalObject::SetF64(), v8::internal::WasmGlobalObject::SetI32(), v8::internal::WasmGlobalObject::SetI64(), v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::SetImpl(), v8::internal::FrameDescription::SetLiftoffFrameSlot32(), v8::internal::FrameDescription::SetLiftoffFrameSlot64(), v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::SetWasmCalleeTag(), wasm::FuncData::v8_callback(), and v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::Writer::Write().
WriteUnalignedValue() [2/2]
template<typename V >
static void v8::base::WriteUnalignedValue (char p[sizeof(V)], V value) [inline], [static]
Definition at line 47 of file memory.h.
                                                                   {
  return WriteUnalignedValue<V>(reinterpret_cast<Address>(p), value);
}
References v8::internal::value.
zip()
template<class... Containers>
auto v8::base::zip (Containers &... containers)
Definition at line 205 of file iterator.h.
                                    {
  using TupleIt =
      TupleIterator<decltype(std::declval<Containers>().begin())...>;
  return base::make_iterator_range(TupleIt(containers.begin()...),
                                   TupleIt(containers.end()...));
}
References make_iterator_range().
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::CloneSubGraph().
Variable Documentation
args
V8_BASE_EXPORT int const char va_list v8::base::args
Definition at line 23 of file strings.h.
Referenced by v8::internal::compiler::turboshaft::Graph::Add(), v8::internal::StringStream::Add(), v8::Set::Add(), v8::internal::wasm::WasmWrapperTSGraphBuilder::AddArgumentNodes(), v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::AddArguments(), v8::internal::OffHeapHashTableBase< Derived >::AddAt(), v8::internal::anonymous_namespace{runtime-classes.cc}::AddDescriptorsByTemplate(), v8::internal::interpreter::BytecodeGenerator::AddDisposableValue(), v8::internal::maglev::MaglevGraphBuilder::AddInlinedArgumentsToDeoptFrame(), v8::internal::maglev::MaglevGraphBuilder::AddNewCallNode(), v8::internal::maglev::MaglevGraphBuilder::AddNewNode(), v8::internal::maglev::MaglevGraphBuilder::AddNewNodeOrGetEquivalent(), v8::internal::compiler::RawMachineAssembler::AddNode(), v8::internal::maglev::MaglevInliner::AddNodeAtBlockEnd(), v8::internal::maglev::NodeBase::Allocate(), v8::internal::compiler::InstructionSelector::AppendDeoptimizeArguments(), v8::internal::JsonStringifier::ApplyReplacerFunction(), v8::internal::JsonStringifier::ApplyToJsonFunction(), v8::internal::ArrayConstructInitializeElements(), v8::internal::maglev::detail::ArrayWrapper< Size >::ArrayWrapper(), v8::D8Console::Assert(), v8::internal::anonymous_namespace{builtins-async-generator-gen.cc}::AsyncGeneratorBuiltinsAssembler::AsyncGeneratorEnqueue(), v8::internal::wasm::TurboshaftGraphBuildingInterface::AtomicOp(), v8::internal::wasm::WasmInterpreter::BeginExecution(), v8_inspector::anonymous_namespace{custom-preview.cc}::bodyCallback(), v8::internal::compiler::CodeAssembler::Branch(), v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::Build(), v8::internal::CodeStubAssembler::BuildAppendJSArray(), v8::internal::interpreter::BytecodeGenerator::BuildAsyncReturn(), v8::internal::interpreter::BytecodeGenerator::BuildAwait(), v8::internal::compiler::BytecodeGraphBuilder::BuildCall(), v8::internal::baseline::BaselineCompiler::BuildCall(), v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::BuildCallAndReturn(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCallAndReturn(), v8::internal::maglev::MaglevGraphBuilder::BuildCallFromRegisterList(), v8::internal::maglev::MaglevGraphBuilder::BuildCallFromRegisters(), v8::internal::maglev::MaglevGraphBuilder::BuildCallKnownJSFunction(), v8::internal::compiler::WasmGraphBuilder::BuildCallNode(), v8::internal::maglev::MaglevGraphBuilder::BuildCallSelf(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCallWasmFromWrapper(), v8::internal::maglev::MaglevGraphBuilder::BuildCallWithFeedback(), v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::BuildCCall(), v8::internal::interpreter::BytecodeGenerator::BuildClassLiteral(), v8::internal::maglev::MaglevGraphBuilder::BuildConstruct(), v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::BuildCWasmEntry(), v8::internal::interpreter::BytecodeGenerator::BuildDeclareCall(), v8::internal::interpreter::BytecodeGenerator::BuildDisposeScope(), v8::internal::maglev::MaglevGraphBuilder::BuildEagerInlineCall(), v8::internal::interpreter::BytecodeGenerator::BuildFinalizeIteration(), v8::internal::interpreter::BytecodeGenerator::BuildGeneratorObjectVariableInitialization(), v8::internal::maglev::MaglevGraphBuilder::BuildGenericCall(), v8::internal::maglev::MaglevGraphBuilder::BuildGenericConstruct(), v8::internal::interpreter::BytecodeGenerator::BuildInstanceMemberInitialization(), v8::internal::interpreter::BytecodeGenerator::BuildInvalidPropertyAccess(), v8::internal::interpreter::BytecodeGenerator::BuildIteratorClose(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildJSToWasmWrapper(), v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::BuildJSToWasmWrapper(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadTaggedField(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateBrandCheck(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateDebugDynamicGet(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateDebugDynamicSet(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateGetterAccess(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateMethodIn(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateSetterAccess(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildSuspend(), v8::internal::compiler::WasmGraphBuilder::BuildWasmCall(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildWasmCall(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildWasmMaybeReturnCall(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildWasmToJSWrapper(), v8::internal::BUILTIN(), v8::internal::anonymous_namespace{runtime-internal.cc}::BytecodeBudgetInterrupt(), v8::internal::anonymous_namespace{runtime-internal.cc}::BytecodeBudgetInterruptWithStackCheck(), cppgc::MakeGarbageCollectedTrait< T >::Call(), v8::internal::GeneratedCode< Return, Args >::Call(), v8::internal::compiler::GraphAssembler::Call(), v8_inspector::V8Console::call(), v8::internal::Execution::Call(), v8::internal::CodeStubAssembler::Call(), v8::Function::Call(), v8::internal::anonymous_namespace{runtime-test.cc}::call_as_function(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallAndMaybeCatchException(), v8::internal::interpreter::BytecodeArrayBuilder::CallAnyReceiver(), v8::Object::CallAsConstructor(), v8::Object::CallAsFunction(), v8::internal::maglev::MaglevAssembler::CallBuiltin(), v8::internal::baseline::BaselineCompiler::CallBuiltin(), v8::internal::compiler::CodeAssembler::CallBuiltin(), v8::internal::compiler::WasmGraphAssembler::CallBuiltin(), v8::internal::wasm::WasmWrapperTSGraphBuilder::CallBuiltin(), v8::internal::Execution::CallBuiltin(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin_CallForwardVarargs(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::CallBuiltinForBigIntOp(), v8::internal::compiler::WasmGraphAssembler::CallBuiltinImpl(), v8::internal::compiler::CodeAssembler::CallBuiltinPointer(), v8::internal::compiler::WasmGraphAssembler::CallBuiltinThroughJumptable(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallBuiltinThroughJumptable(), v8::internal::compiler::CodeAssembler::CallBuiltinVoid(), v8::internal::compiler::WasmGraphAssembler::CallBuiltinWithFrameState(), v8::internal::wasm::WasmGraphBuilderBase::CallC(), v8::internal::wasm::LiftoffAssembler::CallC(), v8::internal::compiler::anonymous_namespace{raw-machine-assembler.cc}::CallCFunctionImpl(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallCStackSlotToInt32(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallCStackSlotToStackSlot(), v8::internal::wasm::LiftoffAssembler::CallCWithStackBuffer(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallDirect(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallDirect(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallEmitFn(), v8::internal::CodeStubAssembler::CallFunction(), v8::debug::CallFunctionOn(), v8::internal::CallOrConstructBuiltinsAssembler::CallFunctionTemplate(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallIndirect(), v8::internal::compiler::CodeAssembler::CallJS(), v8::internal::interpreter::InterpreterAssembler::CallJSAndDispatch(), v8::internal::compiler::CodeAssembler::CallJSBuiltin(), v8::internal::interpreter::BytecodeArrayBuilder::CallJSRuntime(), v8::internal::compiler::CodeAssembler::CallJSStubImpl(), v8::internal::interpreter::InterpreterAssembler::CallJSWithSpreadAndDispatch(), CallOnce(), v8::internal::anonymous_namespace{builtins-intl.cc}::CallOrConstructConstructor(), v8::internal::interpreter::BytecodeArrayBuilder::CallProperty(), v8::internal::CallOrConstructBuiltinsAssembler::CallReceiver(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallRef(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallRuntime(), v8::internal::baseline::BaselineCompiler::CallRuntime(), v8::internal::compiler::CodeAssembler::CallRuntime(), v8::internal::interpreter::BytecodeArrayBuilder::CallRuntime(), v8::internal::wasm::WasmGraphBuilderBase::CallRuntime(), v8::internal::interpreter::BytecodeArrayBuilder::CallRuntimeForPair(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallRuntimeImpl(), v8::internal::compiler::CodeAssembler::CallRuntimeImpl(), v8::internal::interpreter::InterpreterAssembler::CallRuntimeN(), v8::internal::GeneratedCode< Return, Args >::CallSandboxed(), v8::internal::compiler::CodeAssembler::CallStub(), v8::internal::compiler::CodeAssembler::CallStubR(), v8::internal::compiler::CodeAssembler::CallStubRImpl(), v8::internal::interpreter::BytecodeArrayBuilder::CallUndefinedReceiver(), wasm::anonymous_namespace{c-api.cc}::CallWasmCapiFunction(), v8::internal::interpreter::BytecodeArrayBuilder::CallWithSpread(), v8::internal::wasm::anonymous_namespace{asm-types.cc}::AsmFroundType::CanBeInvokedWith(), v8::internal::wasm::anonymous_namespace{asm-types.cc}::AsmMinMaxType::CanBeInvokedWith(), v8::internal::wasm::AsmFunctionType::CanBeInvokedWith(), v8::internal::wasm::AsmOverloadedFunctionType::CanBeInvokedWith(), v8::Promise::Catch(), v8::base::internal::CheckMathOp(), v8::base::internal::ClampMathOp(), v8::internal::JSFinalizationRegistry::Cleanup(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CodeComment(), v8::internal::KeyAccumulator::CollectOwnJSProxyKeys(), v8::internal::compiler::CodeAssembler::Comment(), v8::internal::ComputeFlagListHash(), v8::internal::torque::TypeVisitor::ComputeType(), v8::internal::ElementsAccessor::Concat(), v8_inspector::String16::concat(), v8::internal::anonymous_namespace{builtins-console.cc}::ConsoleCall(), v8::internal::interpreter::BytecodeArrayBuilder::Construct(), v8::internal::CodeStubAssembler::Construct(), v8::internal::interpreter::InterpreterAssembler::Construct(), v8::internal::compiler::CodeAssembler::ConstructJS(), v8::internal::ThreadIsolation::ConstructNew(), v8::internal::interpreter::BytecodeArrayBuilder::ConstructWithSpread(), v8::internal::interpreter::InterpreterAssembler::ConstructWithSpread(), v8::internal::CodeStubAssembler::ConstructWithTarget(), v8::internal::baseline::detail::CountPushHelper< Arg, Args... >::Count(), v8::internal::maglev::detail::CountPushHelper< Arg, Args... >::Count(), v8::internal::baseline::detail::CountPushHelper< interpreter::RegisterList, Args... >::Count(), v8_inspector::PromiseHandlerTracker::create(), v8::internal::CodeEntryStorage::Create(), v8::internal::anonymous_namespace{builtins-function.cc}::CreateDynamicFunction(), v8::Shell::CreateEvaluationContext(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CreateFrameState(), v8::internal::maglev::MaglevGraphBuilder::CreateNewConstantNode(), v8::internal::maglev::Graph::CreateNewConstantNode(), v8::internal::compiler::turboshaft::CreateOperation(), v8::internal::wasm::TurboshaftGraphBuildingInterface::DataViewGetter(), v8::internal::wasm::TurboshaftGraphBuildingInterface::DataViewSetter(), v8::internal::DateTimeFormatRange(), v8::D8Console::Debug(), v8_inspector::V8Console::debugFunctionCallback(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeAtomicOpcode(), v8::internal::wasm::DecodeError(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeGCOpcode(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeSimdOpcode(), v8::internal::anonymous_namespace{runtime-classes.cc}::DefineClass(), v8::internal::JSProxy::DefineOwnProperty(), v8::internal::anonymous_namespace{js-objects.cc}::DefinePropertyWithInterceptorInternal(), v8::Map::Delete(), v8::Set::Delete(), v8::internal::JSProxy::DeletePropertyOrElement(), v8::internal::JSObject::DeletePropertyWithInterceptor(), v8::internal::anonymous_namespace{builtins-intl.cc}::DisallowCallConstructor(), v8::internal::String::DispatchToSpecificTypeWithoutCast(), v8::internal::JSDisposableStackBase::DisposeResources(), v8::internal::wasm::AsyncCompileJob::DoAsync(), v8::internal::anonymous_namespace{builtins-function.cc}::DoFunctionBind(), v8::internal::wasm::AsyncCompileJob::DoImmediately(), v8::internal::wasm::AsyncCompileJob::DoSync(), v8::internal::maglev::MaglevGraphBuilder::DoTryReduceMathRound(), v8::internal::compiler::turboshaft::TSReducerBase< Next >::Emit(), v8::internal::SharedMacroAssemblerBase::AvxHelper< Dst, Arg, Args >::emit(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::emplace(), v8::internal::ZoneVector< T >::emplace(), v8::LocalVector< T >::emplace_back(), v8::base::SmallVector< T, kSize, Allocator >::emplace_back(), v8::internal::DirectHandleVector< T >::emplace_back(), v8::internal::DirectHandleSmallVector< T, kSize >::emplace_back(), v8::internal::wasm::FastZoneVector< T >::emplace_back(), v8::internal::ZoneVector< T >::emplace_back(), v8::internal::compiler::turboshaft::Opmask::MaskBuilder< Op, Fields >::EncodeValue(), v8::internal::JSObject::EnsureCanContainElements(), v8::EnterV8NoScriptScope< HandleScopeClass >::EnterV8NoScriptScope(), v8::EnterV8Scope< HandleScopeClass >::EnterV8Scope(), v8::internal::torque::Error(), v8::D8Console::Error(), v8::internal::SourceTextModule::ExecuteAsyncModule(), v8::internal::Parser::ExpressionListToExpression(), v8::internal::anonymous_namespace{builtins-array.cc}::Fast_ArrayConcat(), v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::FastApiCall(), v8::internal::KeyAccumulator::FilterForEnumerableProperties(), v8::internal::maglev::MaglevGraphBuilder::FinishBlock(), v8::internal::compiler::turboshaft::FixedArityOperationT< InputCount, Derived >::FixedArityOperationT(), v8::internal::wasm::ErrorThrower::Format(), v8::internal::MessageFormatter::Format(), v8::internal::anonymous_namespace{date.cc}::FormatDate(), v8::internal::wasm::WasmError::FormatError(), v8::internal::PendingCompilationErrorHandler::FormatErrorMessageForTest(), v8::internal::ErrorUtils::FormatStackTrace(), v8::internal::anonymous_namespace{builtins-console.cc}::Formatter(), v8::internal::ArrayIncludesIndexofAssembler::Generate(), v8::internal::anonymous_namespace{builtins-async-iterator-gen.cc}::AsyncFromSyncBuiltinsAssembler::Generate_AsyncFromSyncIteratorMethod(), v8::internal::Builtins::Generate_CallOrConstructVarargs(), v8::internal::ArrayBuiltinsAssembler::GenerateArrayNArgumentsConstructor(), v8::internal::interpreter::BytecodeGenerator::GenerateAsyncFunctionBody(), v8::internal::interpreter::BytecodeGenerator::GenerateAsyncGeneratorFunctionBody(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GenerateCCall(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GenerateCCallWithStackBuffer(), v8::internal::BaseCollectionsAssembler::GenerateConstructor(), v8_inspector::generateCustomPreview(), v8::internal::ArrayBuiltinsAssembler::GenerateDispatchToArrayStub(), v8::internal::interpreter::GenerateInvokeIntrinsic(), v8::internal::GeneratorBuiltinsAssembler::GeneratorPrototypeResume(), v8::internal::anonymous_namespace{builtins-array.cc}::GenericArrayPop(), v8::internal::anonymous_namespace{builtins-array.cc}::GenericArrayPush(), v8::Map::Get(), v8::internal::anonymous_namespace{execution.cc}::InvokeParams::GetAndResetHostDefinedOptions(), v8::internal::maglev::MaglevGraphBuilder::GetArgumentsAsArrayOfValueNodes(), v8::internal::CodeStubAssembler::GetArgumentValue(), v8::internal::maglev::MaglevGraphBuilder::GetConvertReceiver(), v8::internal::maglev::MaglevGraphBuilder::GetDeoptFrameForEagerCall(), v8::internal::anonymous_namespace{runtime-classes.cc}::GetMethodAndSetName(), v8::internal::anonymous_namespace{runtime-classes.cc}::GetMethodWithSharedName(), v8::internal::JSProxy::GetOwnPropertyDescriptor(), v8::internal::anonymous_namespace{builtins-object.cc}::GetOwnPropertyKeys(), v8::internal::JSProxy::GetProperty(), v8::internal::anonymous_namespace{js-objects.cc}::GetPropertyAttributesWithInterceptorInternal(), v8::internal::anonymous_namespace{js-objects.cc}::GetPropertyDescriptorWithInterceptor(), v8::internal::Object::GetPropertyWithAccessor(), v8::internal::anonymous_namespace{js-objects.cc}::GetPropertyWithInterceptorInternal(), v8::internal::JSProxy::GetPrototype(), v8::internal::SharedFunctionInfo::GetSourceCodeHarmony(), v8::anonymous_namespace{d8-console.cc}::GetTimerLabel(), v8::internal::StringsStorage::GetVFormatted(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::GotoIfFalse(), v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::GotoIfTrue(), v8::internal::HandleApiCallAsFunctionOrConstructorDelegate(), v8::internal::wasm::TurboshaftGraphBuildingInterface::HandleWellKnownImport(), v8::Map::Has(), v8::Set::Has(), v8::internal::compiler::turboshaft::OperationT< Derived >::HashWithOptions(), v8::internal::JSProxy::HasProperty(), v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER(), v8::internal::Parser::ImportMetaExpression(), v8::D8Console::Info(), v8::internal::anonymous_namespace{runtime-classes.cc}::InitClassConstructor(), v8::internal::anonymous_namespace{runtime-classes.cc}::InitClassPrototype(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineWasmCall(), v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::innerCallFunctionOn(), v8::internal::GeneratorBuiltinsAssembler::InnerResume(), v8_inspector::V8Console::inspectedObject(), v8_inspector::inspectImpl(), v8::internal::Object::InstanceOf(), v8::internal::JsonParseInternalizer::InternalizeJsonProperty(), cppgc::internal::StatsCollector::InternalScope< trace_category, scope_category >::InternalScope(), v8::internal::interpreter::IntrinsicsGenerator::IntrinsicAsBuiltinCall(), v8::internal::anonymous_namespace{execution.cc}::Invoke(), v8::internal::Builtins::InvokeApiFunction(), v8::internal::JSProxy::IsExtensible(), v8::internal::ETWJITInterface::JoinFields(), v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::InterpreterJSCallAssembler::JSCall(), v8::internal::maglev::MaglevAssembler::JumpToDeferredIf(), v8_inspector::V8Console::keysCallback(), v8_inspector::V8Console::lastEvaluationResultCallback(), v8::base::LeakyObject< T >::LeakyObject(), v8::internal::anonymous_namespace{builtins-intl.cc}::LegacyFormatConstructor(), v8::internal::torque::Lint(), v8::internal::IntlBuiltinsAssembler::ListFormatCommon(), v8::internal::torque::Logger::Log(), v8::D8Console::Log(), v8::internal::anonymous_namespace{builtins-console.cc}::LogTimerEvent(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeCall(), v8::internal::maglev::MaglevAssembler::MakeDeferredCode(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeExternalBuiltin(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeExternalMacro(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeExternalRuntime(), cppgc::MakeGarbageCollected(), v8::internal::ErrorUtils::MakeGenericError(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeIntrinsicCallExpression(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeIntrinsicDeclaration(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeMethodCall(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeMethodDeclaration(), v8::internal::torque::MakeNode(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeTorqueBuiltinDeclaration(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeTorqueMacroDeclaration(), v8::internal::CodeStubAssembler::MakeTypeError(), v8::internal::anonymous_namespace{builtins-array.cc}::MatchArrayElementsKindToArguments(), v8::internal::torque::Message(), v8_inspector::V8Console::monitorFunctionCallback(), v8::internal::baseline::detail::MoveArgumentsForBuiltin(), v8::internal::maglev::detail::MoveArgumentsForBuiltin(), v8::internal::compiler::turboshaft::ZoneWithName< Name >::New(), v8::internal::Zone::New(), v8::internal::compiler::turboshaft::FixedArityOperationT< InputCount, Derived >::New(), v8::internal::compiler::turboshaft::OperationT< Derived >::New(), v8::internal::Execution::New(), v8::internal::maglev::NodeBase::New(), v8::internal::Factory::NewError(), v8::internal::anonymous_namespace{runtime-internal.cc}::NewError(), v8::internal::AstNodeFactory::NewInitializeClassMembersStatement(), v8::internal::AstNodeFactory::NewInitializeClassStaticElementsStatement(), v8::Function::NewInstanceWithSideEffectType(), v8::internal::Parser::NewThrowError(), v8::internal::Parser::NewV8Intrinsic(), v8::internal::Parser::NewV8RuntimeFunctionForFuzzing(), v8::internal::anonymous_namespace{builtins-string.cc}::NextCodePoint(), v8::internal::JSAsyncDisposableStack::NextDisposeAsyncIteration(), v8::internal::wasm::AsyncCompileJob::NextStep(), v8::internal::NumberFormatRange(), v8::internal::CodeDataSource::OnSetup(), v8::internal::anonymous_namespace{runtime-test.cc}::OptimizeFunctionOnNextCall(), v8::internal::OffHeapHashTableBase< Derived >::OverwriteDeletedAt(), v8::internal::ParserBase< Impl >::ParseArguments(), v8::internal::ParserBase< Impl >::ParseLeftHandSideContinuation(), v8::internal::ParserBase< Impl >::ParseMemberWithPresentNewPrefixesExpression(), v8::internal::ParserBase< Impl >::ParseV8Intrinsic(), v8::internal::JSProxy::PreventExtensions(), v8::internal::wasm::anonymous_namespace{wasm-result.cc}::PrintFToString(), v8::internal::torque::CCGenerator::ProcessArgumentsCommon(), v8::internal::torque::CSAGenerator::ProcessArgumentsCommon(), v8::AsyncHooks::PromiseHookDispatch(), v8::internal::baseline::detail::PushAllHelper< Arg, Args... >::Push(), v8::internal::baseline::detail::PushAllHelper< Arg1, Arg2, Args... >::Push(), v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::Push(), v8::internal::maglev::detail::PushAllHelper< Arg, Args... >::Push(), v8::internal::maglev::detail::PushAllHelper< Arg1, Arg2, Args... >::Push(), v8::internal::maglev::detail::PushAllHelper< Input, Args... >::Push(), v8::internal::baseline::detail::PushAll(), v8::internal::maglev::detail::PushAll(), v8::internal::baseline::detail::PushAllReverse(), v8::internal::maglev::detail::PushAllReverse(), wasm::anonymous_namespace{c-api.cc}::PushArgs(), v8::internal::maglev::detail::PushArgumentsForBuiltin(), v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::PushImpl(), v8::internal::maglev::detail::PushIterator(), v8::internal::maglev::detail::PushIteratorReverse(), v8::internal::baseline::detail::PushAllHelper< Arg, Args... >::PushReverse(), v8::internal::baseline::detail::PushAllHelper< Arg1, Arg2, Args... >::PushReverse(), v8::internal::maglev::detail::PushAllHelper< Arg, Args... >::PushReverse(), v8::internal::maglev::detail::PushAllHelper< Arg1, Arg2, Args... >::PushReverse(), v8::internal::maglev::detail::PushAllHelper< Input, Args... >::PushReverse(), v8::internal::ValueDeserializer::ReadJSMap(), v8::internal::ValueDeserializer::ReadJSSet(), v8::internal::maglev::MaglevGraphBuilder::ReduceCall(), v8::internal::maglev::MaglevGraphBuilder::ReduceCallWithArrayLike(), v8::internal::maglev::MaglevGraphBuilder::ReduceCallWithArrayLikeForArgumentsObject(), v8::internal::compiler::JSCallReducer::ReduceJSCall(), v8::internal::compiler::JSCallReducer::ReduceJSConstruct(), v8::internal::compiler::turboshaft::EmitProjectionReducer< Next >::ReduceOperation(), v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::ReduceOperation(), v8::internal::compiler::turboshaft::UniformReducerAdapter< Reducer, Next >::ReduceOperation(), v8::internal::compiler::turboshaft::ExplicitTruncationReducer< Next >::ReduceOperation(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::ReduceOperation(), v8::internal::RegExpUtils::RegExpExec(), v8::internal::compiler::turboshaft::Graph::Replace(), v8::internal::torque::ReportError(), v8::internal::ParserBase< Impl >::ReportMessage(), v8::internal::ParserBase< Impl >::ReportMessageAt(), v8::internal::ResizeHelper(), v8::internal::compiler::turboshaft::detail::ResolveAll(), v8::internal::JSDisposableStackBase::ResolveAPromiseWithValueAndReturnIt(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ReturnCall(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ReturnCall(), v8::internal::ExitPoint::ReturnCallBuiltin(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ReturnCallIndirect(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ReturnCallRef(), v8::internal::ExitPoint::ReturnCallRuntime(), v8::internal::ExitPoint::ReturnCallStub(), v8::internal::ArrayBuiltinsAssembler::ReturnFromBuiltin(), v8::internal::compiler::PipelineImpl::Run(), v8::internal::compiler::turboshaft::Pipeline::Run(), v8::internal::RUNTIME_FUNCTION(), v8::internal::RUNTIME_FUNCTION_RETURN_PAIR(), v8::InspectorFrontend::Send(), v8::internal::baseline::detail::ArgumentSettingHelper< Descriptor, ArgIndex, true, Arg, Args... >::Set(), v8::internal::baseline::detail::ArgumentSettingHelper< Descriptor, ArgIndex, false, Arg, Args... >::Set(), v8::Map::Set(), v8::internal::maglev::ValueLocation::SetAllocated(), v8::internal::maglev::ValueLocation::SetConstant(), v8::internal::Runtime::SetPrivateMember(), v8::internal::JSProxy::SetProperty(), v8::internal::Object::SetPropertyWithAccessor(), v8::internal::Object::SetPropertyWithDefinedSetter(), v8::internal::anonymous_namespace{js-objects.cc}::SetPropertyWithInterceptorInternal(), v8::internal::JSProxy::SetPrototype(), v8::internal::maglev::ValueLocation::SetUnallocated(), v8::internal::anonymous_namespace{execution.cc}::InvokeParams::SetUpForCall(), v8::internal::anonymous_namespace{execution.cc}::InvokeParams::SetUpForNew(), v8::internal::anonymous_namespace{execution.cc}::InvokeParams::SetUpForTryCall(), v8::internal::ErrorUtils::ShadowRealmConstructTypeErrorCopy(), v8::internal::Factory::ShadowRealmNewTypeErrorCopy(), v8::internal::wasm::TurboshaftGraphBuildingInterface::SimdOp(), v8::internal::SliceHelper(), v8::internal::anonymous_namespace{builtins-array.cc}::Slow_ArrayConcat(), SNPrintF(), cppgc::internal::StatsCollector::InternalScope< trace_category, scope_category >::StartTrace(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StructNew(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StructNewDefault(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StructNewImpl(), v8::internal::anonymous_namespace{runtime-classes.cc}::SubstituteValues(), v8::internal::baseline::BaselineCompiler::TailCallBuiltin(), v8::internal::compiler::CodeAssembler::TailCallBuiltin(), v8::internal::compiler::CodeAssembler::TailCallBytecodeDispatch(), v8::internal::interpreter::BytecodeHandlerReducer< Next >::TailCallBytecodeDispatch(), v8::internal::compiler::CodeAssembler::TailCallRuntime(), v8::internal::compiler::CodeAssembler::TailCallRuntimeImpl(), v8::internal::compiler::CodeAssembler::TailCallStub(), v8::internal::compiler::CodeAssembler::TailCallStubImpl(), v8::internal::compiler::CodeAssembler::TailCallStubThenBytecodeDispatchImpl(), v8::internal::TEMPORAL_GET_RUST(), v8::internal::TF_BUILTIN(), v8::Promise::Then(), v8::internal::anonymous_namespace{runtime-internal.cc}::ThrowError(), v8::internal::PendingCompilationErrorHandler::ThrowPendingError(), v8::D8Console::Time(), v8::D8Console::TimeEnd(), v8::D8Console::TimeLog(), v8::D8Console::TimeStamp(), v8_inspector::V8Console::TimeStamp(), v8::internal::torque::ToString(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::try_emplace(), v8::internal::maglev::MaglevGraphBuilder::TryBuildCallKnownApiFunction(), v8::internal::maglev::MaglevGraphBuilder::TryBuildCallKnownJSFunction(), v8::internal::maglev::MaglevGraphBuilder::TryBuildFastInstanceOf(), v8::internal::maglev::MaglevGraphBuilder::TryBuildInlineCall(), v8::internal::maglev::MaglevGraphBuilder::TryBuildLoadDataView(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyGetterCall(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertySetterCall(), v8::internal::compiler::BytecodeGraphBuilder::TryBuildSimplifiedConstruct(), v8::internal::maglev::MaglevGraphBuilder::TryBuildStoreDataView(), v8::internal::Execution::TryCall(), v8::internal::MessageFormatter::TryFormat(), v8::internal::maglev::MaglevGraphBuilder::TryReduceArrayIteratingBuiltin(), v8::internal::maglev::MaglevGraphBuilder::TryReduceBuiltin(), v8::internal::maglev::MaglevGraphBuilder::TryReduceCallForApiFunction(), v8::internal::maglev::MaglevGraphBuilder::TryReduceCallForConstant(), v8::internal::maglev::MaglevGraphBuilder::TryReduceCallForNewClosure(), v8::internal::maglev::MaglevGraphBuilder::TryReduceCallForTarget(), v8::internal::maglev::MaglevGraphBuilder::TryReduceConstruct(), v8::internal::maglev::MaglevGraphBuilder::TryReduceConstructArrayConstructor(), v8::internal::maglev::MaglevGraphBuilder::TryReduceConstructBuiltin(), v8::internal::maglev::MaglevGraphBuilder::TryReduceConstructGeneric(), v8::internal::maglev::MaglevGraphBuilder::TryReduceDatePrototypeGetField(), v8::internal::maglev::MaglevGraphBuilder::TryReduceFunctionPrototypeApplyCallWithReceiver(), v8::internal::maglev::MaglevGraphBuilder::TryReduceGetIterator(), v8_inspector::V8Console::undebugFunctionCallback(), v8_inspector::V8Console::unmonitorFunctionCallback(), v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::Unshift(), v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::UnshiftImpl(), v8_inspector::V8Console::valuesCallback(), v8::internal::torque::ImplementationVisitor::Visit(), v8::internal::interpreter::BytecodeGenerator::VisitArguments(), v8::internal::interpreter::BytecodeGenerator::VisitCallSuper(), v8::internal::compiler::InstructionSelector::VisitDeoptimize(), v8::internal::interpreter::BytecodeGenerator::VisitKeyedSuperPropertyLoad(), v8::internal::interpreter::BytecodeGenerator::VisitNamedSuperPropertyLoad(), v8::internal::wasm::anonymous_namespace{wasm-result.cc}::VPrintFToString(), VPrintHelper(), VSNPrintF(), v8::D8Console::Warn(), wasm_callback(), wasm_callback_with_env(), wasm_func_call(), v8::internal::wasm::WasmInterpreterRuntime::WasmArrayCopy(), v8::internal::wasm::WasmInterpreterRuntime::WasmArrayInitSegment(), v8::internal::wasm::WasmInterpreterRuntime::WasmArrayNewSegment(), v8::internal::wasm::WasmError::WasmError(), v8::internal::wasm::WasmInterpreterRuntime::WasmJSToWasmObject(), v8::internal::wasm::TurboshaftGraphBuildingInterface::WellKnown_FastApi(), v8_inspector::V8ConsoleMessage::wrapArguments(), and v8::anonymous_namespace{d8-console.cc}::WriteToFile().
div
const DivMagic v8::base::div[] [static]
Initial value:
= {
    {0, 0},
    {0x9999999a, 3},
    {0x47ae147b, 6},
    {0x0624dd30, 9},
    {0xa36e2eb2, 13},
    {0x4f8b588f, 16},
    {0x0c6f7a0c, 19},
    {0xad7f29ac, 23},
    {0x5798ee24, 26}
}
Definition at line 210 of file fast-dtoa.cc.
Referenced by DigitGen(), DigitGenCounted(), and v8::internal::compiler::SimplifiedLowering::Uint32Div().
entropy_mutex
LazyMutex v8::base::entropy_mutex = LAZY_MUTEX_INITIALIZER [static]
Definition at line 25 of file random-number-generator.cc.
Referenced by v8::base::RandomNumberGenerator::RandomNumberGenerator(), and v8::base::RandomNumberGenerator::SetEntropySource().
entropy_source
RandomNumberGenerator::EntropySource v8::base::entropy_source = nullptr [static]
Definition at line 26 of file random-number-generator.cc.
Referenced by v8::base::RandomNumberGenerator::RandomNumberGenerator(), v8::base::RandomNumberGenerator::SetEntropySource(), and v8::V8::SetEntropySource().
exact_powers_of_ten
const double v8::base::exact_powers_of_ten[] [static]
Initial value:
= {
  1.0,
  10.0,
  100.0,
  1000.0,
  10000.0,
  100000.0,
  1000000.0,
  10000000.0,
  100000000.0,
  1000000000.0,
  10000000000.0,
  100000000000.0,
  1000000000000.0,
  10000000000000.0,
  100000000000000.0,
  1000000000000000.0,
  10000000000000000.0,
  100000000000000000.0,
  1000000000000000000.0,
  10000000000000000000.0,
  100000000000000000000.0,
  1000000000000000000000.0,
  
  10000000000000000000000.0
}
Definition at line 39 of file strtod.cc.
Referenced by DoubleStrtod().
format
V8_BASE_EXPORT int const char * v8::base::format
Definition at line 23 of file strings.h.
Referenced by anonymous_namespace{logging.cc}::FailureMessage::FailureMessage(), v8::Shell::ReadFile(), v8::CpuProfile::Serialize(), v8::HeapSnapshot::Serialize(), SNPrintF(), V8_Fatal(), VPrintHelper(), and VSNPrintF().
g_abort_mode
V8_BASE_EXPORT AbortMode v8::base::g_abort_mode = AbortMode::kDefault
Definition at line 10 of file abort-mode.cc.
Referenced by v8::base::OS::Abort(), ControlledCrashesAreHarmless(), DcheckFailuresAreIgnored(), and PosixInitializeCommon().
has_output_operator
template<typename T , typename TStream = std::ostream>
concept v8::base::has_output_operator = requires(T t, TStream stream) { stream << t; }
Definition at line 59 of file template-utils.h.
has_type_v
template<typename SearchT , typename... Ts>
constexpr bool v8::base::has_type_v [constexpr]
Initial value:
=
    index_of_type<SearchT, Ts...>::value < sizeof...(Ts)
Definition at line 226 of file template-utils.h.
Hashable
template<typename T >
concept v8::base::Hashable
Initial value:
= requires(const T& t) {
  { hash_value(t) } -> std::convertible_to<size_t>;
}
Definition at line 286 of file hashing.h.
index_of_type_v
template<typename SearchT , typename... Ts>
constexpr size_t v8::base::index_of_type_v = index_of_type<SearchT, Ts...>::value [constexpr]
Definition at line 224 of file template-utils.h.
IntegralConstantLike
template<typename T >
concept v8::base::IntegralConstantLike
Initial value:
=
    std::is_integral_v<decltype(T::value)> &&
    !std::is_same_v<bool, std::remove_const_t<decltype(T::value)>> &&
    std::convertible_to<T, decltype(T::value)> &&
    std::equality_comparable_with<T, decltype(T::value)> &&
    std::bool_constant<T() == T::value>::value &&
    std::bool_constant<static_cast<decltype(T::value)>(T()) == T::value>::value
Definition at line 18 of file integral_constant_like.h.
kBase10MaximalLength
const int v8::base::kBase10MaximalLength = 17
Definition at line 34 of file dtoa.h.
Referenced by v8::internal::DoubleToExponentialStringView(), and v8::internal::DoubleToStringView().
kCachedPowers
const CachedPower v8::base::kCachedPowers[] [static]
Definition at line 25 of file cached-powers.cc.
Referenced by v8::base::PowersOfTenCache::GetCachedPowerForBinaryExponentRange(), and v8::base::PowersOfTenCache::GetCachedPowerForDecimalExponent().
kCachedPowersOffset
const int v8::base::kCachedPowersOffset = 348 [static]
Definition at line 76 of file cached-powers.cc.
Referenced by v8::base::PowersOfTenCache::GetCachedPowerForBinaryExponentRange(), and v8::base::PowersOfTenCache::GetCachedPowerForDecimalExponent().
kContinueBit
constexpr uint32_t v8::base::kContinueBit = 1 << kContinueShift [static], [constexpr]
Definition at line 17 of file vlq.h.
Referenced by VLQEncodeUnsigned().
kContinueShift
constexpr uint32_t v8::base::kContinueShift = 7 [static], [constexpr]
Definition at line 16 of file vlq.h.
Referenced by VLQBase64Decode(), VLQDecodeUnsigned(), and VLQEncodeUnsigned().
kD_1_LOG2_10
const double v8::base::kD_1_LOG2_10 = 0.30102999566398114 [static]
Definition at line 77 of file cached-powers.cc.
Referenced by v8::base::PowersOfTenCache::GetCachedPowerForBinaryExponentRange().
kDataMask
constexpr uint32_t v8::base::kDataMask = kContinueBit - 1 [static], [constexpr]
Definition at line 18 of file vlq.h.
Referenced by v8::internal::anonymous_namespace{frame-translation-builder.cc}::SmallUnsignedOperand::SmallUnsignedOperand(), v8::internal::FrameTranslationBuilder::StoreDoubleRegister(), v8::internal::FrameTranslationBuilder::StoreFloatRegister(), v8::internal::FrameTranslationBuilder::StoreHoleyDoubleRegister(), v8::internal::FrameTranslationBuilder::StoreRegister(), v8::internal::FrameTranslationBuilder::StoreSimd128Register(), VLQBase64Decode(), and VLQDecodeUnsigned().
kDoubleSignificandSize
const int v8::base::kDoubleSignificandSize = 53 [static]
Definition at line 96 of file fixed-dtoa.cc.
Referenced by FastFixedDtoa().
kExactPowersOfTenSize
const int v8::base::kExactPowersOfTenSize = arraysize(exact_powers_of_ten) [static]
Definition at line 66 of file strtod.cc.
Referenced by DoubleStrtod().
kFastDtoaMaximalLength
const int v8::base::kFastDtoaMaximalLength = 17
Definition at line 25 of file fast-dtoa.h.
kMaxDecimalPower
const int v8::base::kMaxDecimalPower = 309 [static]
Definition at line 32 of file strtod.cc.
Referenced by BignumStrtod(), and Strtod().
kMaxExactDoubleIntegerDecimalDigits
const int v8::base::kMaxExactDoubleIntegerDecimalDigits = 15 [static]
Definition at line 22 of file strtod.cc.
Referenced by DoubleStrtod().
kMaximalTargetExponent
const int v8::base::kMaximalTargetExponent = -32 [static]
Definition at line 24 of file fast-dtoa.cc.
Referenced by DigitGen(), DigitGenCounted(), Grisu3(), and Grisu3Counted().
kMaxLoadFactorForRandomization
constexpr double v8::base::kMaxLoadFactorForRandomization = 0.40 [constexpr]
Definition at line 18 of file region-allocator.cc.
kMaxRandomizationAttempts
constexpr int v8::base::kMaxRandomizationAttempts = 3 [constexpr]
Definition at line 21 of file region-allocator.cc.
Referenced by v8::base::RegionAllocator::AllocateRegion().
kMaxSignificantDecimalDigits
const int v8::base::kMaxSignificantDecimalDigits = 780 [static]
Definition at line 71 of file strtod.cc.
Referenced by BignumStrtod(), Strtod(), and TrimToMaxSignificantDigits().
kMaxUint64
const uint64_t v8::base::kMaxUint64 = 0xFFFF'FFFF'FFFF'FFFF [static]
Definition at line 36 of file strtod.cc.
Referenced by ReadUint64().
kMaxUint64DecimalDigits
const int v8::base::kMaxUint64DecimalDigits = 19 [static]
Definition at line 24 of file strtod.cc.
Referenced by v8::base::Bignum::AssignDecimalString(), and DiyFpStrtod().
kMeanGravityDouble
constexpr double v8::base::kMeanGravityDouble = 9.80665 [constexpr]
Definition at line 13 of file math_constants.h.
kMeanGravityFloat
constexpr float v8::base::kMeanGravityFloat = 9.80665f [constexpr]
Definition at line 14 of file math_constants.h.
kMinDecimalPower
const int v8::base::kMinDecimalPower = -324 [static]
Definition at line 33 of file strtod.cc.
Referenced by BignumStrtod(), and Strtod().
kMinimalTargetExponent
const int v8::base::kMinimalTargetExponent = -60 [static]
Definition at line 23 of file fast-dtoa.cc.
Referenced by DigitGen(), DigitGenCounted(), Grisu3(), and Grisu3Counted().
kNoThread [1/2]
const pthread_t v8::base::kNoThread = (pthread_t) 0 [static]
Definition at line 43 of file platform-qnx.cc.
Referenced by v8::base::Thread::Start(), and ThreadEntry().
kNoThread [2/2]
const HANDLE v8::base::kNoThread = INVALID_HANDLE_VALUE [static]
Definition at line 1729 of file platform-win32.cc.
kNullAddress
constexpr Address v8::base::kNullAddress = 0 [constexpr]
Definition at line 19 of file virtual-address-space.h.
Referenced by v8::base::EmulatedVirtualAddressSubspace::AllocatePages(), v8::base::VirtualAddressSubspace::AllocatePages(), v8::base::EmulatedVirtualAddressSubspace::AllocateSharedPages(), v8::base::VirtualAddressSubspace::AllocateSharedPages(), v8::FromCData(), anonymous_namespace{objects-printer.cc}::GetObjectFromRaw(), v8::internal::Deserializer< IsolateT >::ReadAllocateJSDispatchEntry(), v8::internal::Deserializer< IsolateT >::ReadIndirectPointerPrefix(), v8::internal::Deserializer< IsolateT >::ReadInitializeSelfIndirectPointer(), v8::internal::Deserializer< IsolateT >::ReadJSDispatchEntry(), v8::internal::Deserializer< IsolateT >::ReadProtectedPointerPrefix(), v8::internal::Deserializer< IsolateT >::ReadWeakPrefix(), v8::ToCData(), v8::internal::MarkCompactCollector::UpdatePointersInClientHeap(), v8::internal::anonymous_namespace{mark-compact.cc}::RememberedSetUpdatingItem::UpdateUntypedTrustedToTrustedPointers(), and wasm::FuncData::v8_callback().
kTen4
const uint32_t v8::base::kTen4 = 10000 [static]
Definition at line 195 of file fast-dtoa.cc.
Referenced by BiggestPowerTen().
kTen5
const uint32_t v8::base::kTen5 = 100000 [static]
Definition at line 196 of file fast-dtoa.cc.
Referenced by BiggestPowerTen().
kTen6
const uint32_t v8::base::kTen6 = 1000000 [static]
Definition at line 197 of file fast-dtoa.cc.
Referenced by BiggestPowerTen().
kTen7
const uint32_t v8::base::kTen7 = 10000000 [static]
Definition at line 198 of file fast-dtoa.cc.
Referenced by BiggestPowerTen(), FillDigits64(), and FillDigits64FixedLength().
kTen8
const uint32_t v8::base::kTen8 = 100000000 [static]
Definition at line 199 of file fast-dtoa.cc.
Referenced by BiggestPowerTen().
kTen9
const uint32_t v8::base::kTen9 = 1000000000 [static]
Definition at line 200 of file fast-dtoa.cc.
Referenced by BiggestPowerTen().
kUC16Size
constexpr int v8::base::kUC16Size = sizeof(uc16) [constexpr]
Definition at line 20 of file strings.h.
Referenced by v8::internal::LiteralBuffer::AddTwoByteChar(), v8::internal::anonymous_namespace{regexp-interpreter.cc}::BackRefMatchesNoCase(), v8::internal::LiteralBuffer::ConvertToTwoByte(), v8::internal::SeqTwoByteString::GetDataAndPaddingSizes(), and v8::internal::FactoryBase< Impl >::NewTwoByteInternalizedString().
kUnimplementedCodeMessage
constexpr const char* v8::base::kUnimplementedCodeMessage = `unimplemented code` [constexpr]
Definition at line 62 of file logging.h.
kUnreachableCodeMessage
constexpr const char* v8::base::kUnreachableCodeMessage = `unreachable code` [constexpr]
Definition at line 63 of file logging.h.
Referenced by v8::internal::torque::ImplementationVisitor::Visit().
kUnsafeInsertion
constexpr bool v8::base::kUnsafeInsertion = true [static], [constexpr]
Definition at line 370 of file threaded-list.h.
leading_zeros
template unsigned v8::base::leading_zeros
Definition at line 109 of file division-by-constant.cc.
Referenced by v8::internal::MarkingBitmap::FindPreviousValidObject(), v8::bigint::ShiftedDigits::ShiftedDigits(), v8::internal::wasm::uint64_to_float32_wrapper(), and UnsignedDivisionByConstant().
LT
v8::base::LT
Definition at line 405 of file logging.h.
MapViewOfFile3
MapViewOfFile3_t v8::base::MapViewOfFile3 = nullptr
Definition at line 796 of file platform-win32.cc.
output_mode
OutputMode v8::base::output_mode = UNKNOWN [static]
Definition at line 577 of file platform-win32.cc.
Referenced by HasConsole().
UnmapViewOfFile2
UnmapViewOfFile2_t v8::base::UnmapViewOfFile2 = nullptr
Definition at line 799 of file platform-win32.cc.
VirtualAlloc2
VirtualAlloc2_t v8::base::VirtualAlloc2 = nullptr
Definition at line 791 of file platform-win32.cc.
Referenced by v8::base::anonymous_namespace{platform-win32.cc}::VirtualAllocWrapper().