v8::internal::compiler::CsaLoadEliminationHelpers Namespace Reference
Functions
bool Subsumes (MachineRepresentation from, MachineRepresentation to)
bool IsConstantObject (Node *object)
bool IsFreshObject (Node *object)
Function Documentation
IsConstantObject()
bool v8::internal::compiler::CsaLoadEliminationHelpers::IsConstantObject (Node * object)
Definition at line 80 of file csa-load-elimination.cc.
                                    {
  return object->opcode() == IrOpcode::kParameter ||
         object->opcode() == IrOpcode::kLoadImmutable ||
         NodeProperties::IsConstant(object);
}
References v8::internal::compiler::NodeProperties::IsConstant().
Referenced by v8::internal::compiler::CsaLoadElimination::HalfState::AddField(), v8::internal::compiler::CsaLoadElimination::HalfState::KillField(), and v8::internal::compiler::CsaLoadElimination::HalfState::Lookup().
IsFreshObject()
bool v8::internal::compiler::CsaLoadEliminationHelpers::IsFreshObject (Node * object)
Definition at line 86 of file csa-load-elimination.cc.
                                 {
  return object->opcode() == IrOpcode::kAllocate ||
         object->opcode() == IrOpcode::kAllocateRaw;
}
Referenced by v8::internal::compiler::CsaLoadElimination::HalfState::AddField(), v8::internal::compiler::CsaLoadElimination::HalfState::KillField(), and v8::internal::compiler::CsaLoadElimination::HalfState::Lookup().
Subsumes()
bool v8::internal::compiler::CsaLoadEliminationHelpers::Subsumes (MachineRepresentation from, MachineRepresentation to)
Definition at line 71 of file csa-load-elimination.cc.
                                                                    {
  if (from == to) return true;
  if (IsAnyTagged(from)) return IsAnyTagged(to);
  if (IsIntegral(from)) {
    return IsIntegral(to) && ElementSizeInBytes(from) >= ElementSizeInBytes(to);
  }
  return false;
}
References v8::internal::ElementSizeInBytes(), v8::internal::IsAnyTagged(), and v8::internal::IsIntegral().
Referenced by v8::internal::compiler::CsaLoadElimination::ReduceLoadFromObject(), and v8::internal::compiler::CsaLoadElimination::TruncateAndExtend().