v8::internal::wasm::liftoff Namespace Reference
Classes
class CacheStatePreservingTempRegisters
Enumerations
enum class MinOrMax : uint8_t {
kMin
, kMax
, kMin
, kMax
,
kMin
, kMax
 }
enum ShiftDirection { kLeft
, kRight
, kLeft
, kRight
 }
enum class ShiftDirection : bool { kLeft
, kRight
, kLeft
, kRight
 }
enum class ShiftSign : bool { kSigned
, kUnsigned
 }
enum class Binop {
kAdd
, kSub
, kAnd
, kOr
,
kXor
, kExchange
, kAdd
, kAdd
,
kAdd
, kAdd
, kAdd
, kSub
,
kSub
, kSub
, kSub
, kSub
,
kAnd
, kAnd
, kAnd
, kAnd
,
kAnd
, kOr
, kOr
, kOr
,
kOr
, kOr
, kXor
, kXor
,
kXor
, kXor
, kXor
, kExchange
,
kExchange
, kExchange
, kExchange
, kExchange
,
kAdd
, kSub
, kAnd
, kOr
,
kXor
, kExchange
, kAdd
, kSub
,
kAnd
, kOr
, kXor
, kExchange
 }
enum Binop {
kAdd
, kSub
, kAnd
, kOr
,
kXor
, kExchange
, kAdd
, kAdd
,
kAdd
, kAdd
, kAdd
, kSub
,
kSub
, kSub
, kSub
, kSub
,
kAnd
, kAnd
, kAnd
, kAnd
,
kAnd
, kOr
, kOr
, kOr
,
kOr
, kOr
, kXor
, kXor
,
kXor
, kXor
, kXor
, kExchange
,
kExchange
, kExchange
, kExchange
, kExchange
,
kAdd
, kSub
, kAnd
, kOr
,
kXor
, kExchange
, kAdd
, kSub
,
kAnd
, kOr
, kXor
, kExchange
 }
enum class DivOrRem : uint8_t { kDiv
, kRem
, kDiv
, kRem
 }
enum class MinOrMax : uint8_t {
kMin
, kMax
, kMin
, kMax
,
kMin
, kMax
 }
enum class Binop {
kAdd
, kSub
, kAnd
, kOr
,
kXor
, kExchange
, kAdd
, kAdd
,
kAdd
, kAdd
, kAdd
, kSub
,
kSub
, kSub
, kSub
, kSub
,
kAnd
, kAnd
, kAnd
, kAnd
,
kAnd
, kOr
, kOr
, kOr
,
kOr
, kOr
, kXor
, kXor
,
kXor
, kXor
, kXor
, kExchange
,
kExchange
, kExchange
, kExchange
, kExchange
,
kAdd
, kSub
, kAnd
, kOr
,
kXor
, kExchange
, kAdd
, kSub
,
kAnd
, kOr
, kXor
, kExchange
 }
enum class Binop {
kAdd
, kSub
, kAnd
, kOr
,
kXor
, kExchange
, kAdd
, kAdd
,
kAdd
, kAdd
, kAdd
, kSub
,
kSub
, kSub
, kSub
, kSub
,
kAnd
, kAnd
, kAnd
, kAnd
,
kAnd
, kOr
, kOr
, kOr
,
kOr
, kOr
, kXor
, kXor
,
kXor
, kXor
, kXor
, kExchange
,
kExchange
, kExchange
, kExchange
, kExchange
,
kAdd
, kSub
, kAnd
, kOr
,
kXor
, kExchange
, kAdd
, kSub
,
kAnd
, kOr
, kXor
, kExchange
 }
enum class DivOrRem : uint8_t { kDiv
, kRem
, kDiv
, kRem
 }
enum class MinOrMax : uint8_t {
kMin
, kMax
, kMin
, kMax
,
kMin
, kMax
 }
Functions
MemOperand GetStackSlot (int offset)
MemOperand GetHalfStackSlot (int offset, RegPairHalf half)
MemOperand GetInstanceDataOperand ()
MemOperand GetMemOp (LiftoffAssembler *assm, UseScratchRegisterScope *temps, Register addr, Register offset, int32_t offset_imm, unsigned shift_amount=0)
Register CalculateActualAddress (LiftoffAssembler *assm, UseScratchRegisterScope *temps, Register addr_reg, Register offset_reg, uintptr_t offset_imm, Register result_reg=no_reg)
Condition MakeUnsigned (Condition cond)
template<void(Assembler::*)(Register, Register, Register, SBit, Condition) op, void(Assembler::*)(Register, Register, const Operand &, SBit, Condition) op_with_carry>
void I64Binop (LiftoffAssembler *assm, LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
template<void(Assembler::*)(Register, Register, const Operand &, SBit, Condition) op, void(Assembler::*)(Register, Register, const Operand &, SBit, Condition) op_with_carry>
void I64BinopI (LiftoffAssembler *assm, LiftoffRegister dst, LiftoffRegister lhs, int64_t imm)
template<void(MacroAssembler::*)(Register, Register, Register, Register, Register) op, bool is_left_shift>
void I64Shiftop (LiftoffAssembler *assm, LiftoffRegister dst, LiftoffRegister src, Register amount)
FloatRegister GetFloatRegister (DoubleRegister reg)
Simd128Register GetSimd128Register (DoubleRegister reg)
Simd128Register GetSimd128Register (LiftoffRegister reg)
template<typename RegisterType >
void EmitFloatMinOrMax (LiftoffAssembler *assm, RegisterType dst, RegisterType lhs, RegisterType rhs, MinOrMax min_or_max)
Register EnsureNoAlias (Assembler *assm, Register reg, Register must_not_alias, UseScratchRegisterScope *temps)
void S128NarrowOp (LiftoffAssembler *assm, NeonDataType dt, NeonDataType sdt, LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void F64x2Compare (LiftoffAssembler *assm, LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs, Condition cond)
void Store (LiftoffAssembler *assm, LiftoffRegister src, MemOperand dst, ValueKind kind)
void Load (LiftoffAssembler *assm, LiftoffRegister dst, MemOperand src, ValueKind kind)
constexpr int MaskFromNeonDataType (NeonDataType dt)
template<ShiftDirection dir = kLeft, NeonDataType dt, NeonSize sz>
void EmitSimdShift (LiftoffAssembler *assm, LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
template<ShiftDirection dir, NeonDataType dt>
void EmitSimdShiftImmediate (LiftoffAssembler *assm, LiftoffRegister dst, LiftoffRegister lhs, int32_t rhs)
void EmitAnyTrue (LiftoffAssembler *assm, LiftoffRegister dst, LiftoffRegister src)
void LoadInternal (LiftoffAssembler *lasm, LiftoffRegister dst, Register src_addr, Register offset_reg, int32_t offset_imm, LoadType type, uint32_t *protected_load_pc=nullptr, bool needs_shift=false)
void AtomicOp32 (LiftoffAssembler *lasm, Register dst_addr, Register offset_reg, uint32_t offset_imm, LiftoffRegister value, LiftoffRegister result, LiftoffRegList pinned, void(Assembler::*load)(Register, Register, Condition), void(Assembler::*store)(Register, Register, Register, Condition), void(*op)(LiftoffAssembler *, Register, Register, Register))
void Add (LiftoffAssembler *lasm, Register dst, Register lhs, Register rhs)
void Sub (LiftoffAssembler *lasm, Register dst, Register lhs, Register rhs)
void And (LiftoffAssembler *lasm, Register dst, Register lhs, Register rhs)
void Or (LiftoffAssembler *lasm, Register dst, Register lhs, Register rhs)
void Xor (LiftoffAssembler *lasm, Register dst, Register lhs, Register rhs)
void Exchange (LiftoffAssembler *lasm, Register dst, Register lhs, Register rhs)
void AtomicBinop32 (LiftoffAssembler *lasm, Register dst_addr, Register offset_reg, uint32_t offset_imm, LiftoffRegister value, LiftoffRegister result, StoreType type, void(*op)(LiftoffAssembler *, Register, Register, Register))
void AtomicOp64 (LiftoffAssembler *lasm, Register dst_addr, Register offset_reg, uint32_t offset_imm, LiftoffRegister value, std::optional< LiftoffRegister > result, void(*op)(LiftoffAssembler *, LiftoffRegister, LiftoffRegister, LiftoffRegister))
void I64Store (LiftoffAssembler *lasm, LiftoffRegister dst, LiftoffRegister, LiftoffRegister src)
void AtomicI64CompareExchange (LiftoffAssembler *lasm, Register dst_addr_reg, Register offset_reg, uint32_t offset_imm, LiftoffRegister expected, LiftoffRegister new_value, LiftoffRegister result)
void GeneratePopCnt (Assembler *assm, Register dst, Register src, Register scratch1, Register scratch2)
CPURegister GetRegFromType (const LiftoffRegister &reg, ValueKind kind)
CPURegList PadRegList (RegList list)
CPURegList PadVRegList (DoubleRegList list)
CPURegister AcquireByType (UseScratchRegisterScope *temps, ValueKind kind)
template<typename T >
MemOperand GetMemOp (LiftoffAssembler *assm, UseScratchRegisterScope *temps, Register addr, Register offset, T offset_imm, bool i64_offset=false, unsigned shift_amount=0)
Register GetEffectiveAddress (LiftoffAssembler *assm, UseScratchRegisterScope *temps, Register addr, Register offset, uintptr_t offset_imm, bool i64_offset=false)
template<ShiftDirection dir, ShiftSign sign = ShiftSign::kSigned>
void EmitSimdShift (LiftoffAssembler *assm, VRegister dst, VRegister lhs, Register rhs, VectorFormat format)
template<VectorFormat format, ShiftSign sign>
void EmitSimdShiftRightImmediate (LiftoffAssembler *assm, VRegister dst, VRegister lhs, int32_t rhs)
void EmitAllTrue (LiftoffAssembler *assm, LiftoffRegister dst, LiftoffRegister src, VectorFormat format)
CPURegister LoadToRegister (LiftoffAssembler *assm, UseScratchRegisterScope *temps, const LiftoffAssembler::VarState &src)
void StoreToMemory (LiftoffAssembler *assm, MemOperand dst, const LiftoffAssembler::VarState &src)
Register CalculateActualAddress (LiftoffAssembler *lasm, UseScratchRegisterScope &temps, Register addr_reg, Register offset_reg, uintptr_t offset_imm)
void AtomicBinop (LiftoffAssembler *lasm, Register dst_addr, Register offset_reg, uintptr_t offset_imm, LiftoffRegister value, LiftoffRegister result, StoreType type, Binop op)
Operand MemOperand (Register base, Register offset_reg, int offset_imm)
void Load (LiftoffAssembler *assm, LiftoffRegister dst, Register base, int32_t offset, ValueKind kind)
void Store (LiftoffAssembler *assm, Register base, int32_t offset, LiftoffRegister src, ValueKind kind)
void push (LiftoffAssembler *assm, LiftoffRegister reg, ValueKind kind, int padding=0)
void SignExtendI32ToI64 (Assembler *assm, LiftoffRegister reg)
Register GetTmpByteRegister (LiftoffAssembler *assm, Register candidate)
void MoveStackValue (LiftoffAssembler *assm, const Operand &src, const Operand &dst)
void AtomicAddOrSubOrExchange32 (LiftoffAssembler *lasm, Binop binop, Register dst_addr, Register offset_reg, uint32_t offset_imm, LiftoffRegister value, LiftoffRegister result, StoreType type)
void AtomicBinop32 (LiftoffAssembler *lasm, Binop op, Register dst_addr, Register offset_reg, uint32_t offset_imm, LiftoffRegister value, LiftoffRegister result, StoreType type)
void AtomicBinop64 (LiftoffAssembler *lasm, Binop op, Register dst_addr, Register offset_reg, uint32_t offset_imm, LiftoffRegister value, LiftoffRegister result)
template<void(Assembler::*)(Register, Register) op>
void EmitCommutativeBinOp (LiftoffAssembler *assm, Register dst, Register lhs, Register rhs)
template<void(Assembler::*)(Register, int32_t) op>
void EmitCommutativeBinOpImm (LiftoffAssembler *assm, Register dst, Register lhs, int32_t imm)
template<bool is_signed, DivOrRem div_or_rem>
void EmitInt32DivOrRem (LiftoffAssembler *assm, Register dst, Register lhs, Register rhs, Label *trap_div_by_zero, Label *trap_div_unrepresentable)
void EmitShiftOperation (LiftoffAssembler *assm, Register dst, Register src, Register amount, void(Assembler::*emit_shift)(Register))
template<void(Assembler::*)(Register, Register) op, void(Assembler::*)(Register, Register) op_with_carry>
void OpWithCarry (LiftoffAssembler *assm, LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
template<void(Assembler::*)(Register, const Immediate &) op, void(Assembler::*)(Register, int32_t) op_with_carry>
void OpWithCarryI (LiftoffAssembler *assm, LiftoffRegister dst, LiftoffRegister lhs, int64_t imm)
bool PairContains (LiftoffRegister pair, Register reg)
LiftoffRegister ReplaceInPair (LiftoffRegister pair, Register old_reg, Register new_reg)
void Emit64BitShiftOperation (LiftoffAssembler *assm, LiftoffRegister dst, LiftoffRegister src, Register amount, void(MacroAssembler::*emit_shift)(Register, Register))
template<typename type >
void EmitFloatMinOrMax (LiftoffAssembler *assm, DoubleRegister dst, DoubleRegister lhs, DoubleRegister rhs, MinOrMax min_or_max)
template<typename dst_type , typename src_type >
void ConvertFloatToIntAndBack (LiftoffAssembler *assm, Register dst, DoubleRegister src, DoubleRegister converted_back, LiftoffRegList pinned)
template<typename dst_type , typename src_type >
void EmitTruncateFloatToInt (LiftoffAssembler *assm, Register dst, DoubleRegister src, Label *trap)
template<typename dst_type , typename src_type >
void EmitSatTruncateFloatToInt (LiftoffAssembler *assm, Register dst, DoubleRegister src)
void setcc_32_no_spill (LiftoffAssembler *assm, Condition cond, Register dst, Register tmp_byte_reg)
void setcc_32 (LiftoffAssembler *assm, Condition cond, Register dst)
Condition cond_make_unsigned (Condition cond)
template<void(Assembler::*)(DoubleRegister, DoubleRegister) cmp_op>
void EmitFloatSetCond (LiftoffAssembler *assm, Condition cond, Register dst, DoubleRegister lhs, DoubleRegister rhs)
template<void(Assembler::*)(XMMRegister, XMMRegister, XMMRegister) avx_op, void(Assembler::*)(XMMRegister, XMMRegister) sse_op>
void EmitSimdCommutativeBinOp (LiftoffAssembler *assm, LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs, std::optional< CpuFeature > feature=std::nullopt)
template<void(Assembler::*)(XMMRegister, XMMRegister, XMMRegister) avx_op, void(Assembler::*)(XMMRegister, XMMRegister) sse_op>
void EmitSimdNonCommutativeBinOp (LiftoffAssembler *assm, LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs, std::optional< CpuFeature > feature=std::nullopt)
template<void(Assembler::*)(XMMRegister, XMMRegister, XMMRegister) avx_op, void(Assembler::*)(XMMRegister, XMMRegister) sse_op, uint8_t width>
void EmitSimdShiftOp (LiftoffAssembler *assm, LiftoffRegister dst, LiftoffRegister operand, LiftoffRegister count)
template<void(Assembler::*)(XMMRegister, XMMRegister, uint8_t) avx_op, void(Assembler::*)(XMMRegister, uint8_t) sse_op, uint8_t width>
void EmitSimdShiftOpImm (LiftoffAssembler *assm, LiftoffRegister dst, LiftoffRegister operand, int32_t count)
template<void(SharedMacroAssemblerBase::*)(XMMRegister, XMMRegister) pcmp>
void EmitAllTrue (LiftoffAssembler *assm, LiftoffRegister dst, LiftoffRegister src, std::optional< CpuFeature > feature=std::nullopt)
void I32x4ExtMulHelper (LiftoffAssembler *assm, XMMRegister dst, XMMRegister src1, XMMRegister src2, bool low, bool is_signed)
template<typename T >
MemOperand GetMemOp (LiftoffAssembler *assm, Register addr, Register offset, T offset_imm, bool i64_offset=false, unsigned shift_amount=0)
void Store (LiftoffAssembler *assm, MemOperand dst, LiftoffRegister src, ValueKind kind)
void push (LiftoffAssembler *assm, LiftoffRegister reg, ValueKind kind)
FPUCondition ConditionToConditionCmpFPU (Condition condition, bool *predicate)
void EmitAllTrue (LiftoffAssembler *assm, LiftoffRegister dst, LiftoffRegister src, MSABranchDF msa_branch_df)
MemOperand GetMemOp (LiftoffAssembler *assm, Register addr, Register offset, uintptr_t offset_imm, Register scratch, bool i64_offset=false, unsigned shift_amount=0)
MemOperand GetStackSlot (uint32_t offset)
void StoreToMemory (LiftoffAssembler *assm, MemOperand dst, const LiftoffAssembler::VarState &src, Register scratch1, Register scratch2)
MemOperand GetMemOp (LiftoffAssembler *assm, Register addr, Register offset, uintptr_t offset_imm, unsigned shift_amount=0)
Register EnsureNoAlias (Assembler *assm, Register reg, LiftoffRegister must_not_alias, UseScratchRegisterScope *temps)
Register CalculateActualAddress (LiftoffAssembler *lasm, UseScratchRegisterScope &temps, Register addr_reg, Register offset_reg, uintptr_t offset_imm, Register result_reg=no_reg)
void AtomicBinop64 (LiftoffAssembler *lasm, Register dst_addr, Register offset_reg, uintptr_t offset_imm, LiftoffRegister value, LiftoffRegister result, StoreType type, Binop op)
bool IsRegInRegPair (LiftoffRegister pair, Register reg)
void Emit64BitShiftOperation (LiftoffAssembler *assm, LiftoffRegister dst, LiftoffRegister src, Register amount, void(MacroAssembler::*emit_shift)(Register, Register, Register, Register, Register, Register, Register))
MemOperand GetMemOp (LiftoffAssembler *assm, Register addr, Register offset, uintptr_t offset_imm, bool i64_offset=false, unsigned shift_amount=0)
void StoreToMemory (LiftoffAssembler *assm, MemOperand dst, const LiftoffAssembler::VarState &src, Register scratch)
Operand GetMemOp (LiftoffAssembler *assm, Register addr, Register offset_reg, uintptr_t offset_imm, ScaleFactor scale_factor=times_1)
void LoadFromStack (LiftoffAssembler *assm, LiftoffRegister dst, Operand src, ValueKind kind)
void StoreToMemory (LiftoffAssembler *assm, Operand dst, LiftoffRegister src, ValueKind kind)
void StoreToMemory (LiftoffAssembler *assm, Operand dst, const LiftoffAssembler::VarState &src)
void AtomicBinop (LiftoffAssembler *lasm, void(Assembler::*opl)(Register, Register), void(Assembler::*opq)(Register, Register), Register dst_addr, Register offset_reg, uintptr_t offset_imm, LiftoffRegister value, LiftoffRegister result, StoreType type, bool i64_offset)
template<void(Assembler::*)(Register, Register) op, void(Assembler::*)(Register, Register) mov>
void EmitCommutativeBinOp (LiftoffAssembler *assm, Register dst, Register lhs, Register rhs)
template<void(Assembler::*)(Register, Immediate) op, void(Assembler::*)(Register, Register) mov>
void EmitCommutativeBinOpImm (LiftoffAssembler *assm, Register dst, Register lhs, int32_t imm)
template<typename type , DivOrRem div_or_rem>
void EmitIntDivOrRem (LiftoffAssembler *assm, Register dst, Register lhs, Register rhs, Label *trap_div_by_zero, Label *trap_div_unrepresentable)
template<typename dst_type , typename src_type >
void ConvertFloatToIntAndBack (LiftoffAssembler *assm, Register dst, DoubleRegister src, DoubleRegister converted_back)
template<typename src_type >
void EmitSatTruncateFloatToUInt64 (LiftoffAssembler *assm, Register dst, DoubleRegister src)
Variables
constexpr int32_t kPatchInstructionsRequired = 3
constexpr int kHalfStackSlotSize = LiftoffAssembler::kStackSlotSize >> 1
static constexpr LiftoffRegList kByteRegs
constexpr DoubleRegister kScratchDoubleReg = xmm7
constexpr DoubleRegister kScratchDoubleReg2 = xmm0
constexpr int kSubSpSize = 6
constexpr int32_t kLowWordOffset = 0
constexpr int32_t kHighWordOffset = 4
constexpr Register kScratchRegister2 = r11
constexpr Operand kInstanceDataOperand
constexpr Operand kOSRTargetSlot = GetStackSlot(kOSRTargetOffset)
Enumeration Type Documentation
Binop [1/4]
enum v8::internal::wasm::liftoff::Binop [strong]
Enumerator
kAdd
kSub
kAnd
kOr
kXor
kExchange
kAdd
kAdd
kAdd
kAdd
kAdd
kSub
kSub
kSub
kSub
kSub
kAnd
kAnd
kAnd
kAnd
kAnd
kOr
kOr
kOr
kOr
kOr
kXor
kXor
kXor
kXor
kXor
kExchange
kExchange
kExchange
kExchange
kExchange
kAdd
kSub
kAnd
kOr
kXor
kExchange
kAdd
kSub
kAnd
kOr
kXor
kExchange
Definition at line 871 of file liftoff-assembler-arm64-inl.h.
{ kAdd, kSub, kAnd, kOr, kXor, kExchange };
Binop [2/4]
enum v8::internal::wasm::liftoff::Binop
Enumerator
kAdd
kSub
kAnd
kOr
kXor
kExchange
kAdd
kAdd
kAdd
kAdd
kAdd
kSub
kSub
kSub
kSub
kSub
kAnd
kAnd
kAnd
kAnd
kAnd
kOr
kOr
kOr
kOr
kOr
kXor
kXor
kXor
kXor
kXor
kExchange
kExchange
kExchange
kExchange
kExchange
kAdd
kSub
kAnd
kOr
kXor
kExchange
kAdd
kSub
kAnd
kOr
kXor
kExchange
Definition at line 851 of file liftoff-assembler-ia32-inl.h.
{ kAdd, kSub, kAnd, kOr, kXor, kExchange };
Binop [3/4]
enum v8::internal::wasm::liftoff::Binop [strong]
Enumerator
kAdd
kSub
kAnd
kOr
kXor
kExchange
kAdd
kAdd
kAdd
kAdd
kAdd
kSub
kSub
kSub
kSub
kSub
kAnd
kAnd
kAnd
kAnd
kAnd
kOr
kOr
kOr
kOr
kOr
kXor
kXor
kXor
kXor
kXor
kExchange
kExchange
kExchange
kExchange
kExchange
kAdd
kSub
kAnd
kOr
kXor
kExchange
kAdd
kSub
kAnd
kOr
kXor
kExchange
Definition at line 502 of file liftoff-assembler-riscv32-inl.h.
{ kAdd, kSub, kAnd, kOr, kXor, kExchange };
Binop [4/4]
enum v8::internal::wasm::liftoff::Binop [strong]
Enumerator
kAdd
kSub
kAnd
kOr
kXor
kExchange
kAdd
kAdd
kAdd
kAdd
kAdd
kSub
kSub
kSub
kSub
kSub
kAnd
kAnd
kAnd
kAnd
kAnd
kOr
kOr
kOr
kOr
kOr
kXor
kXor
kXor
kXor
kXor
kExchange
kExchange
kExchange
kExchange
kExchange
kAdd
kSub
kAnd
kOr
kXor
kExchange
kAdd
kSub
kAnd
kOr
kXor
kExchange
Definition at line 496 of file liftoff-assembler-riscv64-inl.h.
{ kAdd, kSub, kAnd, kOr, kXor, kExchange };
DivOrRem [1/2]
enum v8::internal::wasm::liftoff::DivOrRem : uint8_t [strong]
Enumerator
kDiv
kRem
kDiv
kRem
Definition at line 1575 of file liftoff-assembler-ia32-inl.h.
: uint8_t { kDiv, kRem };
DivOrRem [2/2]
enum v8::internal::wasm::liftoff::DivOrRem : uint8_t [strong]
Enumerator
kDiv
kRem
kDiv
kRem
Definition at line 1289 of file liftoff-assembler-x64-inl.h.
: uint8_t { kDiv, kRem };
MinOrMax [1/3]
enum v8::internal::wasm::liftoff::MinOrMax : uint8_t [strong]
Enumerator
kMin
kMax
kMin
kMax
kMin
kMax
Definition at line 204 of file liftoff-assembler-arm-inl.h.
: uint8_t { kMin, kMax };
MinOrMax [2/3]
enum v8::internal::wasm::liftoff::MinOrMax : uint8_t [strong]
Enumerator
kMin
kMax
kMin
kMax
kMin
kMax
Definition at line 2155 of file liftoff-assembler-ia32-inl.h.
: uint8_t { kMin, kMax };
MinOrMax [3/3]
enum v8::internal::wasm::liftoff::MinOrMax : uint8_t [strong]
Enumerator
kMin
kMax
kMin
kMax
kMin
kMax
Definition at line 1757 of file liftoff-assembler-x64-inl.h.
: uint8_t { kMin, kMax };
ShiftDirection [1/2]
enum v8::internal::wasm::liftoff::ShiftDirection
Enumerator
kLeft
kRight
kLeft
kRight
Definition at line 377 of file liftoff-assembler-arm-inl.h.
{ kLeft, kRight };
ShiftDirection [2/2]
enum v8::internal::wasm::liftoff::ShiftDirection : bool [strong]
Enumerator
kLeft
kRight
kLeft
kRight
Definition at line 139 of file liftoff-assembler-arm64-inl.h.
: bool { kLeft, kRight };
ShiftSign
enum v8::internal::wasm::liftoff::ShiftSign : bool [strong]
Enumerator
kSigned
kUnsigned
Definition at line 141 of file liftoff-assembler-arm64-inl.h.
: bool { kSigned, kUnsigned };
Function Documentation
AcquireByType()
CPURegister v8::internal::wasm::liftoff::AcquireByType (UseScratchRegisterScope * temps, ValueKind kind) [inline]
Definition at line 84 of file liftoff-assembler-arm64-inl.h.
                                                 {
  switch (kind) {
    case kI32:
      return temps->AcquireW();
    case kI64:
    case kRef:
    case kRefNull:
      return temps->AcquireX();
    case kF32:
      return temps->AcquireS();
    case kF64:
      return temps->AcquireD();
    case kS128:
      return temps->AcquireQ();
    default:
      UNREACHABLE();
  }
}
References v8::internal::UseScratchRegisterScope::AcquireD(), v8::internal::UseScratchRegisterScope::AcquireQ(), v8::internal::UseScratchRegisterScope::AcquireS(), v8::internal::UseScratchRegisterScope::AcquireW(), v8::internal::UseScratchRegisterScope::AcquireX(), v8::internal::kF32, v8::internal::kF64, v8::internal::kI32, v8::internal::kI64, v8::internal::kRef, v8::internal::kRefNull, v8::internal::kS128, and v8::internal::UNREACHABLE().
Referenced by LoadToRegister().
Add()
void v8::internal::wasm::liftoff::Add (LiftoffAssembler * lasm, Register dst, Register lhs, Register rhs) [inline]
Definition at line 1091 of file liftoff-assembler-arm-inl.h.
                              {
  __ add(dst, lhs, rhs);
}
References __.
Referenced by v8::internal::wasm::LiftoffAssembler::AtomicAdd(), and CalculateActualAddress().
And()
void v8::internal::wasm::liftoff::And (LiftoffAssembler * lasm, Register dst, Register lhs, Register rhs) [inline]
Definition at line 1101 of file liftoff-assembler-arm-inl.h.
                              {
  __ and_(dst, lhs, rhs);
}
References __.
Referenced by v8::internal::AdvanceBytecodeOffsetOrReturn(), v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::wasm::LiftoffAssembler::AtomicAnd(), v8::internal::RegExpMacroAssemblerRISCV::CallCheckStackGuardState(), v8::internal::RegExpMacroAssemblerRISCV::CheckBitInTable(), v8::internal::RegExpMacroAssemblerRISCV::CheckCharacterAfterAnd(), v8::internal::RegExpMacroAssemblerRISCV::CheckNotCharacterAfterAnd(), v8::internal::RegExpMacroAssemblerRISCV::CheckNotCharacterAfterMinusAnd(), v8::internal::Builtins::Generate_Call(), v8::internal::Builtins::Generate_CallFunction(), v8::internal::Builtins::Generate_CallOrConstructForwardVarargs(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::anonymous_namespace{builtins-riscv.cc}::ResetFeedbackVectorOsrUrgency(), and v8::internal::MacroAssembler::SmiTst().
AtomicAddOrSubOrExchange32()
void v8::internal::wasm::liftoff::AtomicAddOrSubOrExchange32 (LiftoffAssembler * lasm, Binop binop, Register dst_addr, Register offset_reg, uint32_t offset_imm, LiftoffRegister value, LiftoffRegister result, StoreType type) [inline]
Definition at line 853 of file liftoff-assembler-ia32-inl.h.
                                                                               {
  DCHECK_EQ(value, result);
  DCHECK(!__ cache_state()->is_used(result));
  bool is_64_bit_op = type.value_type() == kWasmI64;
  Register value_reg = is_64_bit_op ? value.low_gp() : value.gp();
  Register result_reg = is_64_bit_op ? result.low_gp() : result.gp();
  bool is_byte_store = type.size() == 1;
  LiftoffRegList pinned{dst_addr, value_reg};
  if (offset_reg != no_reg) pinned.set(offset_reg);
  // Ensure that {value_reg} is a valid register.
  if (is_byte_store && !liftoff::kByteRegs.has(value_reg)) {
    Register safe_value_reg =
        __ GetUnusedRegister(liftoff::kByteRegs.MaskOut(pinned)).gp();
    __ mov(safe_value_reg, value_reg);
    value_reg = safe_value_reg;
  }
  Operand dst_op = liftoff::MemOperand(dst_addr, offset_reg, offset_imm);
  if (binop == kSub) {
    __ neg(value_reg);
  }
  if (binop != kExchange) {
    __ lock();
  }
  switch (type.value()) {
    case StoreType::kI64Store8:
    case StoreType::kI32Store8:
      if (binop == kExchange) {
        __ xchg_b(value_reg, dst_op);
      } else {
        __ xadd_b(dst_op, value_reg);
      }
      __ movzx_b(result_reg, value_reg);
      break;
    case StoreType::kI64Store16:
    case StoreType::kI32Store16:
      if (binop == kExchange) {
        __ xchg_w(value_reg, dst_op);
      } else {
        __ xadd_w(dst_op, value_reg);
      }
      __ movzx_w(result_reg, value_reg);
      break;
    case StoreType::kI64Store32:
    case StoreType::kI32Store:
      if (binop == kExchange) {
        __ xchg(value_reg, dst_op);
      } else {
        __ xadd(dst_op, value_reg);
      }
      if (value_reg != result_reg) {
        __ mov(result_reg, value_reg);
      }
      break;
    default:
      UNREACHABLE();
  }
  if (is_64_bit_op) {
    __ xor_(result.high_gp(), result.high_gp());
  }
}
References __, v8::internal::DCHECK(), DCHECK_EQ, kByteRegs, kExchange, kSub, v8::internal::wasm::kWasmI64, MemOperand(), v8::internal::no_reg, v8::base::internal::result, v8::internal::tracing::type, v8::internal::UNREACHABLE(), and v8::internal::value.
AtomicBinop() [1/2]
void v8::internal::wasm::liftoff::AtomicBinop (LiftoffAssembler * lasm, Register dst_addr, Register offset_reg, uintptr_t offset_imm, LiftoffRegister value, LiftoffRegister result, StoreType type, Binop op) [inline]
Definition at line 873 of file liftoff-assembler-arm64-inl.h.
                                                  {
  LiftoffRegList pinned{dst_addr, value, result};
  if (offset_reg != no_reg) pinned.set(offset_reg);
  Register store_result = pinned.set(__ GetUnusedRegister(kGpReg, pinned)).gp();
  // {LiftoffCompiler::AtomicBinop} ensures that {result} is unique.
  DCHECK(result.gp() != value.gp() && result.gp() != dst_addr &&
         result.gp() != offset_reg);
  UseScratchRegisterScope temps(lasm);
  Register actual_addr = liftoff::CalculateActualAddress(
      lasm, temps, dst_addr, offset_reg, offset_imm);
  if (CpuFeatures::IsSupported(LSE)) {
    CpuFeatureScope scope(lasm, LSE);
    switch (op) {
      case Binop::kAnd:
        switch (type.value()) {
          case StoreType::kI64Store8:
          case StoreType::kI32Store8: {
            UseScratchRegisterScope temps(lasm);
            Register temp = temps.AcquireW();
            __ mvn(temp, value.gp().W());
            __ ldclralb(temp, result.gp().W(), MemOperand(actual_addr));
            break;
          }
          case StoreType::kI64Store16:
          case StoreType::kI32Store16: {
            UseScratchRegisterScope temps(lasm);
            Register temp = temps.AcquireW();
            __ mvn(temp, value.gp().W());
            __ ldclralh(temp, result.gp().W(), MemOperand(actual_addr));
            break;
          }
          case StoreType::kI64Store32:
          case StoreType::kI32Store: {
            UseScratchRegisterScope temps(lasm);
            Register temp = temps.AcquireW();
            __ mvn(temp, value.gp().W());
            __ ldclral(temp, result.gp().W(), MemOperand(actual_addr));
            break;
          }
          case StoreType::kI64Store: {
            UseScratchRegisterScope temps(lasm);
            Register temp = temps.AcquireX();
            __ mvn(temp, value.gp());
            __ ldclral(temp, result.gp(), MemOperand(actual_addr));
            break;
          }
          default:
            UNREACHABLE();
        }
        break;
      case Binop::kSub:
        switch (type.value()) {
          case StoreType::kI64Store8:
          case StoreType::kI32Store8: {
            UseScratchRegisterScope temps(lasm);
            Register temp = temps.AcquireW();
            __ neg(temp, value.gp().W());
            __ ldaddalb(temp, result.gp().W(), MemOperand(actual_addr));
            break;
          }
          case StoreType::kI64Store16:
          case StoreType::kI32Store16: {
            UseScratchRegisterScope temps(lasm);
            Register temp = temps.AcquireW();
            __ neg(temp, value.gp().W());
            __ ldaddalh(temp, result.gp().W(), MemOperand(actual_addr));
            break;
          }
          case StoreType::kI64Store32:
          case StoreType::kI32Store: {
            UseScratchRegisterScope temps(lasm);
            Register temp = temps.AcquireW();
            __ neg(temp, value.gp().W());
            __ ldaddal(temp, result.gp().W(), MemOperand(actual_addr));
            break;
          }
          case StoreType::kI64Store: {
            UseScratchRegisterScope temps(lasm);
            Register temp = temps.AcquireX();
            __ neg(temp, value.gp());
            __ ldaddal(temp, result.gp(), MemOperand(actual_addr));
            break;
          }
          default:
            UNREACHABLE();
        }
        break;
#define ATOMIC_BINOP_CASE(op, instr) \
  case Binop::op: \
    switch (type.value()) { \
      case StoreType::kI64Store8: \
      case StoreType::kI32Store8: \
        __ instr##b(value.gp().W(), result.gp().W(), MemOperand(actual_addr)); \
        break; \
      case StoreType::kI64Store16: \
      case StoreType::kI32Store16: \
        __ instr##h(value.gp().W(), result.gp().W(), MemOperand(actual_addr)); \
        break; \
      case StoreType::kI64Store32: \
      case StoreType::kI32Store: \
        __ instr(value.gp().W(), result.gp().W(), MemOperand(actual_addr)); \
        break; \
      case StoreType::kI64Store: \
        __ instr(value.gp(), result.gp(), MemOperand(actual_addr)); \
        break; \
      default: \
        UNREACHABLE(); \
    } \
    break;
        ATOMIC_BINOP_CASE(kAdd, ldaddal)
        ATOMIC_BINOP_CASE(kOr, ldsetal)
        ATOMIC_BINOP_CASE(kXor, ldeoral)
        ATOMIC_BINOP_CASE(kExchange, swpal)
#undef ATOMIC_BINOP_CASE
    }
  } else {
    // Allocate an additional {temp} register to hold the result that should be
    // stored to memory. Note that {temp} and {store_result} are not allowed to
    // be the same register.
    Register temp = temps.AcquireX();
    Label retry;
    __ Bind(&retry);
    switch (type.value()) {
      case StoreType::kI64Store8:
      case StoreType::kI32Store8:
        __ ldaxrb(result.gp().W(), actual_addr);
        break;
      case StoreType::kI64Store16:
      case StoreType::kI32Store16:
        __ ldaxrh(result.gp().W(), actual_addr);
        break;
      case StoreType::kI64Store32:
      case StoreType::kI32Store:
        __ ldaxr(result.gp().W(), actual_addr);
        break;
      case StoreType::kI64Store:
        __ ldaxr(result.gp().X(), actual_addr);
        break;
      default:
        UNREACHABLE();
    }
    switch (op) {
      case Binop::kAdd:
        __ add(temp, result.gp(), value.gp());
        break;
      case Binop::kSub:
        __ sub(temp, result.gp(), value.gp());
        break;
      case Binop::kAnd:
        __ and_(temp, result.gp(), value.gp());
        break;
      case Binop::kOr:
        __ orr(temp, result.gp(), value.gp());
        break;
      case Binop::kXor:
        __ eor(temp, result.gp(), value.gp());
        break;
      case Binop::kExchange:
        __ mov(temp, value.gp());
        break;
    }
    switch (type.value()) {
      case StoreType::kI64Store8:
      case StoreType::kI32Store8:
        __ stlxrb(store_result.W(), temp.W(), actual_addr);
        break;
      case StoreType::kI64Store16:
      case StoreType::kI32Store16:
        __ stlxrh(store_result.W(), temp.W(), actual_addr);
        break;
      case StoreType::kI64Store32:
      case StoreType::kI32Store:
        __ stlxr(store_result.W(), temp.W(), actual_addr);
        break;
      case StoreType::kI64Store:
        __ stlxr(store_result.W(), temp.X(), actual_addr);
        break;
      default:
        UNREACHABLE();
    }
    __ Cbnz(store_result.W(), &retry);
  }
}
References __, v8::internal::UseScratchRegisterScope::AcquireW(), v8::internal::UseScratchRegisterScope::AcquireX(), ATOMIC_BINOP_CASE, CalculateActualAddress(), v8::internal::DCHECK(), v8::internal::CpuFeatures::IsSupported(), kAdd, kAnd, kExchange, v8::internal::wasm::kGpReg, kOr, kSub, kXor, v8::internal::no_reg, v8::base::internal::result, v8::internal::tracing::type, v8::internal::UNREACHABLE(), v8::internal::value, v8::internal::CPURegister::W(), and v8::internal::CPURegister::X().
AtomicBinop() [2/2]
void v8::internal::wasm::liftoff::AtomicBinop (LiftoffAssembler * lasm, void(Assembler::*)(Register, Register) opl, void(Assembler::*)(Register, Register) opq, Register dst_addr, Register offset_reg, uintptr_t offset_imm, LiftoffRegister value, LiftoffRegister result, StoreType type, bool i64_offset) [inline]
Definition at line 824 of file liftoff-assembler-x64-inl.h.
                                         {
  if (offset_reg != no_reg && !i64_offset) __ AssertZeroExtended(offset_reg);
  DCHECK(!__ cache_state()->is_used(result));
  Register value_reg = value.gp();
  // The cmpxchg instruction uses rax to store the old value of the
  // compare-exchange primitive. Therefore we have to spill the register and
  // move any use to another register.
  LiftoffRegList pinned = LiftoffRegList{dst_addr, value_reg};
  if (offset_reg != no_reg) pinned.set(offset_reg);
  __ ClearRegister(rax, {&dst_addr, &offset_reg, &value_reg}, pinned);
  Operand dst_op = liftoff::GetMemOp(lasm, dst_addr, offset_reg, offset_imm);
  switch (type.value()) {
    case StoreType::kI32Store8:
    case StoreType::kI64Store8: {
      Label binop;
      __ xorq(rax, rax);
      __ movb(rax, dst_op);
      __ bind(&binop);
      __ movl(kScratchRegister, rax);
      (lasm->*opl)(kScratchRegister, value_reg);
      __ lock();
      __ cmpxchgb(dst_op, kScratchRegister);
      __ j(not_equal, &binop);
      break;
    }
    case StoreType::kI32Store16:
    case StoreType::kI64Store16: {
      Label binop;
      __ xorq(rax, rax);
      __ movw(rax, dst_op);
      __ bind(&binop);
      __ movl(kScratchRegister, rax);
      (lasm->*opl)(kScratchRegister, value_reg);
      __ lock();
      __ cmpxchgw(dst_op, kScratchRegister);
      __ j(not_equal, &binop);
      break;
    }
    case StoreType::kI32Store:
    case StoreType::kI64Store32: {
      Label binop;
      __ movl(rax, dst_op);
      __ bind(&binop);
      __ movl(kScratchRegister, rax);
      (lasm->*opl)(kScratchRegister, value_reg);
      __ lock();
      __ cmpxchgl(dst_op, kScratchRegister);
      __ j(not_equal, &binop);
      break;
    }
    case StoreType::kI64Store: {
      Label binop;
      __ movq(rax, dst_op);
      __ bind(&binop);
      __ movq(kScratchRegister, rax);
      (lasm->*opq)(kScratchRegister, value_reg);
      __ lock();
      __ cmpxchgq(dst_op, kScratchRegister);
      __ j(not_equal, &binop);
      break;
    }
    default:
      UNREACHABLE();
  }
  if (result.gp() != rax) {
    __ movq(result.gp(), rax);
  }
}
References __, v8::internal::DCHECK(), GetMemOp(), v8::internal::kScratchRegister, v8::internal::no_reg, v8::internal::not_equal, v8::base::internal::result, v8::internal::wasm::LiftoffRegList::set(), v8::internal::tracing::type, v8::internal::UNREACHABLE(), and v8::internal::value.
AtomicBinop32() [1/2]
void v8::internal::wasm::liftoff::AtomicBinop32 (LiftoffAssembler * lasm, Binop op, Register dst_addr, Register offset_reg, uint32_t offset_imm, LiftoffRegister value, LiftoffRegister result, StoreType type) [inline]
Definition at line 922 of file liftoff-assembler-ia32-inl.h.
                                          {
  DCHECK_EQ(value, result);
  DCHECK(!__ cache_state()->is_used(result));
  bool is_64_bit_op = type.value_type() == kWasmI64;
  Register value_reg = is_64_bit_op ? value.low_gp() : value.gp();
  Register result_reg = is_64_bit_op ? result.low_gp() : result.gp();
  // The cmpxchg instruction uses eax to store the old value of the
  // compare-exchange primitive. Therefore we have to spill the register and
  // move any use to another register.
  {
    LiftoffRegList pinned{dst_addr, value_reg};
    if (offset_reg != no_reg) pinned.set(offset_reg);
    __ ClearRegister(eax, {&dst_addr, &offset_reg, &value_reg}, pinned);
  }
  bool is_byte_store = type.size() == 1;
  Register scratch = no_reg;
  if (is_byte_store) {
    // The scratch register has to be a byte register. As we are already tight
    // on registers, we just use the root register here.
    static_assert(!kLiftoffAssemblerGpCacheRegs.has(kRootRegister),
                  "root register is not Liftoff cache register");
    DCHECK(kRootRegister.is_byte_register());
    __ push(kRootRegister);
    scratch = kRootRegister;
  } else {
    LiftoffRegList pinned{dst_addr, value_reg, eax};
    if (offset_reg != no_reg) pinned.set(offset_reg);
    scratch = __ GetUnusedRegister(kGpReg, pinned).gp();
  }
  Operand dst_op = liftoff::MemOperand(dst_addr, offset_reg, offset_imm);
  switch (type.value()) {
    case StoreType::kI32Store8:
    case StoreType::kI64Store8: {
      __ xor_(eax, eax);
      __ mov_b(eax, dst_op);
      break;
    }
    case StoreType::kI32Store16:
    case StoreType::kI64Store16: {
      __ xor_(eax, eax);
      __ mov_w(eax, dst_op);
      break;
    }
    case StoreType::kI32Store:
    case StoreType::kI64Store32: {
      __ mov(eax, dst_op);
      break;
    }
    default:
      UNREACHABLE();
  }
  Label binop;
  __ bind(&binop);
  __ mov(scratch, eax);
  switch (op) {
    case kAnd: {
      __ and_(scratch, value_reg);
      break;
    }
    case kOr: {
      __ or_(scratch, value_reg);
      break;
    }
    case kXor: {
      __ xor_(scratch, value_reg);
      break;
    }
    default:
      UNREACHABLE();
  }
  __ lock();
  switch (type.value()) {
    case StoreType::kI32Store8:
    case StoreType::kI64Store8: {
      __ cmpxchg_b(dst_op, scratch);
      break;
    }
    case StoreType::kI32Store16:
    case StoreType::kI64Store16: {
      __ cmpxchg_w(dst_op, scratch);
      break;
    }
    case StoreType::kI32Store:
    case StoreType::kI64Store32: {
      __ cmpxchg(dst_op, scratch);
      break;
    }
    default:
      UNREACHABLE();
  }
  __ j(not_equal, &binop);
  if (is_byte_store) {
    __ pop(kRootRegister);
  }
  if (result_reg != eax) {
    __ mov(result_reg, eax);
  }
  if (is_64_bit_op) {
    __ xor_(result.high_gp(), result.high_gp());
  }
}
References __, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::RegListBase< RegisterT >::has(), v8::internal::Register::is_byte_register(), kAnd, v8::internal::wasm::kGpReg, v8::internal::wasm::kLiftoffAssemblerGpCacheRegs, kOr, v8::internal::kRootRegister, v8::internal::wasm::kWasmI64, kXor, MemOperand(), v8::internal::no_reg, v8::internal::not_equal, push(), v8::base::internal::result, v8::internal::tracing::type, v8::internal::UNREACHABLE(), and v8::internal::value.
AtomicBinop32() [2/2]
void v8::internal::wasm::liftoff::AtomicBinop32 (LiftoffAssembler * lasm, Register dst_addr, Register offset_reg, uint32_t offset_imm, LiftoffRegister value, LiftoffRegister result, StoreType type, void(*)(LiftoffAssembler *, Register, Register, Register) op) [inline]
Definition at line 1121 of file liftoff-assembler-arm-inl.h.
                                                {
  LiftoffRegList pinned{dst_addr, value, result};
  if (offset_reg != no_reg) pinned.set(offset_reg);
  switch (type.value()) {
    case StoreType::kI64Store8:
      __ LoadConstant(result.high(), WasmValue(0));
      result = result.low();
      value = value.low();
      [[fallthrough]];
    case StoreType::kI32Store8:
      liftoff::AtomicOp32(lasm, dst_addr, offset_reg, offset_imm, value, result,
                          pinned, &Assembler::ldrexb, &Assembler::strexb, op);
      return;
    case StoreType::kI64Store16:
      __ LoadConstant(result.high(), WasmValue(0));
      result = result.low();
      value = value.low();
      [[fallthrough]];
    case StoreType::kI32Store16:
      liftoff::AtomicOp32(lasm, dst_addr, offset_reg, offset_imm, value, result,
                          pinned, &Assembler::ldrexh, &Assembler::strexh, op);
      return;
    case StoreType::kI64Store32:
      __ LoadConstant(result.high(), WasmValue(0));
      result = result.low();
      value = value.low();
      [[fallthrough]];
    case StoreType::kI32Store:
      liftoff::AtomicOp32(lasm, dst_addr, offset_reg, offset_imm, value, result,
                          pinned, &Assembler::ldrex, &Assembler::strex, op);
      return;
    default:
      UNREACHABLE();
  }
}
References __, AtomicOp32(), v8::internal::Assembler::ldrex(), v8::internal::Assembler::ldrexb(), v8::internal::Assembler::ldrexh(), v8::internal::no_reg, v8::base::internal::result, v8::internal::wasm::LiftoffRegList::set(), v8::internal::Assembler::strex(), v8::internal::Assembler::strexb(), v8::internal::Assembler::strexh(), v8::internal::tracing::type, v8::internal::UNREACHABLE(), and v8::internal::value.
Referenced by v8::internal::wasm::LiftoffAssembler::AtomicAdd(), v8::internal::wasm::LiftoffAssembler::AtomicAnd(), v8::internal::wasm::LiftoffAssembler::AtomicExchange(), v8::internal::wasm::LiftoffAssembler::AtomicOr(), v8::internal::wasm::LiftoffAssembler::AtomicSub(), and v8::internal::wasm::LiftoffAssembler::AtomicXor().
AtomicBinop64() [1/2]
void v8::internal::wasm::liftoff::AtomicBinop64 (LiftoffAssembler * lasm, Binop op, Register dst_addr, Register offset_reg, uint32_t offset_imm, LiftoffRegister value, LiftoffRegister result) [inline]
Definition at line 1037 of file liftoff-assembler-ia32-inl.h.
                                                                         {
  // We need {ebx} here, which is the root register. As the root register it
  // needs special treatment. As we use {ebx} directly in the code below, we
  // have to make sure here that the root register is actually {ebx}.
  static_assert(kRootRegister == ebx,
                "The following code assumes that kRootRegister == ebx");
  __ push(ebx);
  // Store the value on the stack, so that we can use it for retries.
  __ AllocateStackSpace(8);
  Operand value_op_hi = Operand(esp, 0);
  Operand value_op_lo = Operand(esp, 4);
  __ mov(value_op_lo, value.low_gp());
  __ mov(value_op_hi, value.high_gp());
  // We want to use the compare-exchange instruction here. It uses registers
  // as follows: old-value = EDX:EAX; new-value = ECX:EBX.
  Register old_hi = edx;
  Register old_lo = eax;
  Register new_hi = ecx;
  Register new_lo = ebx;
  // Base and offset need separate registers that do not alias with the
  // ones above.
  Register base = esi;
  Register offset = edi;
  // Spill all these registers if they are still holding other values.
  __ SpillRegisters(old_hi, old_lo, new_hi, base, offset);
  if (offset_reg == no_reg) {
    if (dst_addr != base) __ mov(base, dst_addr);
    offset = no_reg;
  } else {
    // Potentially swap base and offset register to avoid unnecessary moves.
    if (dst_addr == offset || offset_reg == base) {
      std::swap(dst_addr, offset_reg);
    }
    __ ParallelRegisterMove(
        {{LiftoffRegister{base}, LiftoffRegister{dst_addr}, kI32},
         {LiftoffRegister{offset}, LiftoffRegister{offset_reg}, kI32}});
  }
  Operand dst_op_lo = liftoff::MemOperand(base, offset, offset_imm);
  Operand dst_op_hi = liftoff::MemOperand(base, offset, offset_imm + 4);
  // Load the old value from memory.
  __ mov(old_lo, dst_op_lo);
  __ mov(old_hi, dst_op_hi);
  Label retry;
  __ bind(&retry);
  __ mov(new_lo, old_lo);
  __ mov(new_hi, old_hi);
  switch (op) {
    case kAdd:
      __ add(new_lo, value_op_lo);
      __ adc(new_hi, value_op_hi);
      break;
    case kSub:
      __ sub(new_lo, value_op_lo);
      __ sbb(new_hi, value_op_hi);
      break;
    case kAnd:
      __ and_(new_lo, value_op_lo);
      __ and_(new_hi, value_op_hi);
      break;
    case kOr:
      __ or_(new_lo, value_op_lo);
      __ or_(new_hi, value_op_hi);
      break;
    case kXor:
      __ xor_(new_lo, value_op_lo);
      __ xor_(new_hi, value_op_hi);
      break;
    case kExchange:
      __ mov(new_lo, value_op_lo);
      __ mov(new_hi, value_op_hi);
      break;
  }
  __ lock();
  __ cmpxchg8b(dst_op_lo);
  __ j(not_equal, &retry);
  // Deallocate the stack space again.
  __ add(esp, Immediate(8));
  // Restore the root register, and we are done.
  __ pop(kRootRegister);
  // Move the result into the correct registers.
  __ ParallelRegisterMove(
      {{result, LiftoffRegister::ForPair(old_lo, old_hi), kI64}});
}
References __, v8::internal::wasm::LiftoffRegister::ForPair(), kAdd, kAnd, kExchange, v8::internal::kI32, v8::internal::kI64, kOr, v8::internal::kRootRegister, kSub, kXor, MemOperand(), v8::internal::no_reg, v8::internal::not_equal, push(), v8::base::internal::result, and v8::internal::value.
AtomicBinop64() [2/2]
void v8::internal::wasm::liftoff::AtomicBinop64 (LiftoffAssembler * lasm, Register dst_addr, Register offset_reg, uintptr_t offset_imm, LiftoffRegister value, LiftoffRegister result, StoreType type, Binop op) [inline]
Definition at line 503 of file liftoff-assembler-riscv32-inl.h.
                                                    {
  ASM_CODE_COMMENT(lasm);
  FrameScope scope(lasm, StackFrame::MANUAL);
  RegList c_params = {kCArgRegs[0], kCArgRegs[1], kCArgRegs[2]};
  RegList result_list = {result.low_gp(), result.high_gp()};
  // Result registers does not need to be pushed.
  __ MultiPush(c_params - result_list);
  UseScratchRegisterScope temps(lasm);
  liftoff::CalculateActualAddress(lasm, temps, dst_addr, offset_reg, offset_imm,
                                  kScratchReg);
  __ Mv(kCArgRegs[1], value.low_gp());
  __ Mv(kCArgRegs[2], value.high_gp());
  __ Mv(kCArgRegs[0], kScratchReg);
  __ MultiPush(kJSCallerSaved - c_params - result_list);
  __ PrepareCallCFunction(3, 0, kScratchReg);
  ExternalReference extern_func_ref;
  switch (op) {
    case Binop::kAdd:
      extern_func_ref = ExternalReference::atomic_pair_add_function();
      break;
    case Binop::kSub:
      extern_func_ref = ExternalReference::atomic_pair_sub_function();
      break;
    case Binop::kAnd:
      extern_func_ref = ExternalReference::atomic_pair_and_function();
      break;
    case Binop::kOr:
      extern_func_ref = ExternalReference::atomic_pair_or_function();
      break;
    case Binop::kXor:
      extern_func_ref = ExternalReference::atomic_pair_xor_function();
      break;
    case Binop::kExchange:
      extern_func_ref = ExternalReference::atomic_pair_exchange_function();
      break;
    default:
      UNREACHABLE();
  }
  __ CallCFunction(extern_func_ref, 3, 0);
  __ MultiPop(kJSCallerSaved - c_params - result_list);
  __ Mv(result.low_gp(), kReturnRegister0);
  __ Mv(result.high_gp(), kReturnRegister1);
  __ MultiPop(c_params - result_list);
  return;
}
References __, ASM_CODE_COMMENT, CalculateActualAddress(), kAdd, kAnd, v8::internal::kCArgRegs, kExchange, v8::internal::kJSCallerSaved, kOr, v8::internal::kReturnRegister0, v8::internal::kReturnRegister1, v8::internal::kScratchReg, kSub, kXor, v8::internal::StackFrame::MANUAL, v8::base::internal::result, v8::internal::UNREACHABLE(), and v8::internal::value.
AtomicI64CompareExchange()
void v8::internal::wasm::liftoff::AtomicI64CompareExchange (LiftoffAssembler * lasm, Register dst_addr_reg, Register offset_reg, uint32_t offset_imm, LiftoffRegister expected, LiftoffRegister new_value, LiftoffRegister result) [inline]
Definition at line 1427 of file liftoff-assembler-arm-inl.h.
                                                             {
  // To implement I64AtomicCompareExchange, we nearly need all registers, with
  // some registers having special constraints, e.g. like for {new_value} and
  // {result} the low-word register has to have an even register code, and the
  // high-word has to be in the next higher register. To avoid complicated
  // register allocation code here, we just assign fixed registers to all
  // values here, and then move all values into the correct register.
  Register dst_addr = r0;
  Register offset = r1;
  Register result_low = r4;
  Register result_high = r5;
  Register new_value_low = r2;
  Register new_value_high = r3;
  Register store_result = r6;
  Register expected_low = r8;
  Register expected_high = r9;
  // We spill all registers, so that we can re-assign them afterwards.
  __ SpillRegisters(dst_addr, offset, result_low, result_high, new_value_low,
                    new_value_high, store_result, expected_low, expected_high);
  __ ParallelRegisterMove(
      {{LiftoffRegister::ForPair(new_value_low, new_value_high), new_value,
        kI64},
       {LiftoffRegister::ForPair(expected_low, expected_high), expected, kI64},
       {dst_addr, dst_addr_reg, kI32},
       {offset, offset_reg != no_reg ? offset_reg : offset, kI32}});
  {
    UseScratchRegisterScope temps(lasm);
    [[maybe_unused]] Register temp = liftoff::CalculateActualAddress(
        lasm, &temps, dst_addr, offset_reg == no_reg ? no_reg : offset,
        offset_imm, dst_addr);
    // Make sure the actual address is stored in the right register.
    DCHECK_EQ(dst_addr, temp);
  }
  Label retry;
  Label done;
  __ dmb(ISH);
  __ bind(&retry);
  __ ldrexd(result_low, result_high, dst_addr);
  __ cmp(result_low, expected_low);
  __ b(ne, &done);
  __ cmp(result_high, expected_high);
  __ b(ne, &done);
  __ strexd(store_result, new_value_low, new_value_high, dst_addr);
  __ cmp(store_result, Operand(0));
  __ b(ne, &retry);
  __ dmb(ISH);
  __ bind(&done);
  __ ParallelRegisterMove(
      {{result, LiftoffRegister::ForPair(result_low, result_high), kI64}});
}
References __, CalculateActualAddress(), DCHECK_EQ, v8::internal::wasm::LiftoffRegister::ForPair(), v8::internal::ISH, v8::internal::kI32, v8::internal::kI64, v8::internal::ne, v8::internal::no_reg, and v8::base::internal::result.
Referenced by v8::internal::wasm::LiftoffAssembler::AtomicCompareExchange().
AtomicOp32()
void v8::internal::wasm::liftoff::AtomicOp32 (LiftoffAssembler * lasm, Register dst_addr, Register offset_reg, uint32_t offset_imm, LiftoffRegister value, LiftoffRegister result, LiftoffRegList pinned, void(Assembler::*)(Register, Register, Condition) load, void(Assembler::*)(Register, Register, Register, Condition) store, void(*)(LiftoffAssembler *, Register, Register, Register) op) [inline]
Definition at line 1058 of file liftoff-assembler-arm-inl.h.
                                                                 {
  Register store_result = pinned.set(__ GetUnusedRegister(kGpReg, pinned)).gp();
  // Allocate an additional {temp} register to hold the result that should be
  // stored to memory. Note that {temp} and {store_result} are not allowed to be
  // the same register.
  Register temp = pinned.set(__ GetUnusedRegister(kGpReg, pinned)).gp();
  // {LiftoffCompiler::AtomicBinop} ensures that {result} is unique.
  DCHECK(result.gp() != value.gp() && result.gp() != dst_addr &&
         result.gp() != offset_reg);
  UseScratchRegisterScope temps(lasm);
  Register actual_addr = liftoff::CalculateActualAddress(
      lasm, &temps, dst_addr, offset_reg, offset_imm);
  __ dmb(ISH);
  Label retry;
  __ bind(&retry);
  (lasm->*load)(result.gp(), actual_addr, al);
  op(lasm, temp, result.gp(), value.gp());
  (lasm->*store)(store_result, temp, actual_addr, al);
  __ cmp(store_result, Operand(0));
  __ b(ne, &retry);
  __ dmb(ISH);
}
References __, v8::internal::al, CalculateActualAddress(), v8::internal::DCHECK(), v8::internal::ISH, v8::internal::wasm::kGpReg, v8::internal::ne, v8::base::internal::result, v8::internal::wasm::LiftoffRegList::set(), store(), and v8::internal::value.
Referenced by AtomicBinop32(), and v8::internal::wasm::LiftoffAssembler::AtomicExchangeTaggedPointer().
AtomicOp64()
void v8::internal::wasm::liftoff::AtomicOp64 (LiftoffAssembler * lasm, Register dst_addr, Register offset_reg, uint32_t offset_imm, LiftoffRegister value, std::optional< LiftoffRegister > result, void(*)(LiftoffAssembler *, LiftoffRegister, LiftoffRegister, LiftoffRegister) op) [inline]
Definition at line 1162 of file liftoff-assembler-arm-inl.h.
                                                                     {
  // strexd loads a 64 bit word into two registers. The first register needs
  // to have an even index, e.g. r8, the second register needs to be the one
  // with the next higher index, e.g. r9 if the first register is r8. In the
  // following code we use the fixed register pair r8/r9 to make the code here
  // simpler, even though other register pairs would also be possible.
  constexpr Register dst_low = r8;
  constexpr Register dst_high = r9;
  // Make sure {dst_low} and {dst_high} are not occupied by any other value.
  Register value_low = value.low_gp();
  Register value_high = value.high_gp();
  LiftoffRegList pinned{dst_low, dst_high};
  auto regs_to_check = {&dst_addr, &offset_reg, &value_low, &value_high};
  auto re_pin = [regs_to_check, &pinned] {
    for (auto* reg : regs_to_check) {
      if (*reg != no_reg) pinned.set(*reg);
    }
  };
  re_pin();
  __ ClearRegister(dst_low, regs_to_check, pinned);
  re_pin();
  __ ClearRegister(dst_high, regs_to_check, pinned);
  re_pin();
  // Make sure that {result}, if it exists, also does not overlap with
  // {dst_low} and {dst_high}. We don't have to transfer the value stored in
  // {result}.
  Register result_low = no_reg;
  Register result_high = no_reg;
  if (result.has_value()) {
    result_low = result.value().low_gp();
    if (pinned.has(result_low)) {
      result_low = __ GetUnusedRegister(kGpReg, pinned).gp();
    }
    pinned.set(result_low);
    result_high = result.value().high_gp();
    if (pinned.has(result_high)) {
      result_high = __ GetUnusedRegister(kGpReg, pinned).gp();
    }
    pinned.set(result_high);
  }
  Register store_result = __ GetUnusedRegister(kGpReg, pinned).gp();
  UseScratchRegisterScope temps(lasm);
  Register actual_addr = liftoff::CalculateActualAddress(
      lasm, &temps, dst_addr, offset_reg, offset_imm);
  __ dmb(ISH);
  Label retry;
  __ bind(&retry);
  // {ldrexd} is needed here so that the {strexd} instruction below can
  // succeed. We don't need the value we are reading. We use {dst_low} and
  // {dst_high} as the destination registers because {ldrexd} has the same
  // restrictions on registers as {strexd}, see the comment above.
  __ ldrexd(dst_low, dst_high, actual_addr);
  if (result.has_value()) {
    __ mov(result_low, dst_low);
    __ mov(result_high, dst_high);
  }
  op(lasm, LiftoffRegister::ForPair(dst_low, dst_high),
     LiftoffRegister::ForPair(dst_low, dst_high),
     LiftoffRegister::ForPair(value_low, value_high));
  __ strexd(store_result, dst_low, dst_high, actual_addr);
  __ cmp(store_result, Operand(0));
  __ b(ne, &retry);
  __ dmb(ISH);
  if (result.has_value()) {
    if (result_low != result.value().low_gp()) {
      __ mov(result.value().low_gp(), result_low);
    }
    if (result_high != result.value().high_gp()) {
      __ mov(result.value().high_gp(), result_high);
    }
  }
}
References __, CalculateActualAddress(), v8::internal::wasm::LiftoffRegister::ForPair(), v8::internal::wasm::LiftoffRegList::has(), v8::internal::ISH, v8::internal::wasm::kGpReg, v8::internal::ne, v8::internal::no_reg, v8::base::internal::result, v8::internal::wasm::LiftoffRegList::set(), and v8::internal::value.
Referenced by v8::internal::wasm::LiftoffAssembler::AtomicAdd(), v8::internal::wasm::LiftoffAssembler::AtomicAnd(), v8::internal::wasm::LiftoffAssembler::AtomicExchange(), v8::internal::wasm::LiftoffAssembler::AtomicOr(), v8::internal::wasm::LiftoffAssembler::AtomicStore(), v8::internal::wasm::LiftoffAssembler::AtomicSub(), and v8::internal::wasm::LiftoffAssembler::AtomicXor().
CalculateActualAddress() [1/3]
Register v8::internal::wasm::liftoff::CalculateActualAddress (LiftoffAssembler * assm, UseScratchRegisterScope * temps, Register addr_reg, Register offset_reg, uintptr_t offset_imm, Register result_reg = no_reg) [inline]
Definition at line 88 of file liftoff-assembler-arm-inl.h.
                                                                     {
  if (offset_reg == no_reg && offset_imm == 0) {
    if (result_reg == addr_reg || result_reg == no_reg) return addr_reg;
    assm->mov(result_reg, addr_reg);
    return result_reg;
  }
  if (result_reg == no_reg) result_reg = temps->Acquire();
  if (offset_reg == no_reg) {
    assm->add(result_reg, addr_reg, Operand(offset_imm));
  } else {
    assm->add(result_reg, addr_reg, Operand(offset_reg));
    if (offset_imm != 0) assm->add(result_reg, result_reg, Operand(offset_imm));
  }
  return result_reg;
}
References v8::internal::UseScratchRegisterScope::Acquire(), v8::internal::Assembler::add(), v8::internal::MacroAssembler::mov(), and v8::internal::no_reg.
Referenced by AtomicBinop(), AtomicBinop64(), v8::internal::wasm::LiftoffAssembler::AtomicCompareExchange(), AtomicI64CompareExchange(), v8::internal::wasm::LiftoffAssembler::AtomicLoad(), AtomicOp32(), AtomicOp64(), v8::internal::wasm::LiftoffStackSlots::Construct(), Load(), LoadInternal(), v8::internal::wasm::LiftoffAssembler::LoadLane(), v8::internal::wasm::LiftoffAssembler::LoadTransform(), Store(), v8::internal::wasm::LiftoffAssembler::Store(), and v8::internal::wasm::LiftoffAssembler::StoreLane().
CalculateActualAddress() [2/3]
Register v8::internal::wasm::liftoff::CalculateActualAddress (LiftoffAssembler * lasm, UseScratchRegisterScope & temps, Register addr_reg, Register offset_reg, uintptr_t offset_imm) [inline]
Definition at line 855 of file liftoff-assembler-arm64-inl.h.
                                                             {
  DCHECK_NE(addr_reg, no_reg);
  if (offset_reg == no_reg && offset_imm == 0) return addr_reg;
  Register result = temps.AcquireX();
  if (offset_reg == no_reg) {
    __ Add(result, addr_reg, Operand(offset_imm));
  } else {
    __ Add(result, addr_reg, Operand(offset_reg));
    if (offset_imm != 0) __ Add(result, result, Operand(offset_imm));
  }
  return result;
}
References __, v8::internal::UseScratchRegisterScope::AcquireX(), Add(), DCHECK_NE, v8::internal::no_reg, and v8::base::internal::result.
CalculateActualAddress() [3/3]
Register v8::internal::wasm::liftoff::CalculateActualAddress (LiftoffAssembler * lasm, UseScratchRegisterScope & temps, Register addr_reg, Register offset_reg, uintptr_t offset_imm, Register result_reg = no_reg) [inline]
Definition at line 481 of file liftoff-assembler-riscv32-inl.h.
                                                                     {
  if (offset_reg == no_reg && offset_imm == 0) {
    if (result_reg == addr_reg || result_reg == no_reg) return addr_reg;
    lasm->mv(result_reg, addr_reg);
    return result_reg;
  }
  if (result_reg == no_reg) result_reg = temps.Acquire();
  if (offset_reg == no_reg) {
    lasm->AddWord(result_reg, addr_reg, Operand(offset_imm));
  } else {
    lasm->AddWord(result_reg, addr_reg, Operand(offset_reg));
    if (offset_imm != 0)
      lasm->AddWord(result_reg, result_reg, Operand(offset_imm));
  }
  return result_reg;
}
References v8::internal::UseScratchRegisterScope::Acquire(), v8::internal::AssemblerRISCVI::mv(), and v8::internal::no_reg.
cond_make_unsigned()
Condition v8::internal::wasm::liftoff::cond_make_unsigned (Condition cond) [inline]
Definition at line 2768 of file liftoff-assembler-ia32-inl.h.
                                                    {
  switch (cond) {
    case kLessThan:
      return kUnsignedLessThan;
    case kLessThanEqual:
      return kUnsignedLessThanEqual;
    case kGreaterThan:
      return kUnsignedGreaterThan;
    case kGreaterThanEqual:
      return kUnsignedGreaterThanEqual;
    default:
      return cond;
  }
}
References v8::internal::kGreaterThan, v8::internal::kGreaterThanEqual, v8::internal::kLessThan, v8::internal::kLessThanEqual, v8::internal::kUnsignedGreaterThan, v8::internal::kUnsignedGreaterThanEqual, v8::internal::kUnsignedLessThan, and v8::internal::kUnsignedLessThanEqual.
ConditionToConditionCmpFPU()
FPUCondition v8::internal::wasm::liftoff::ConditionToConditionCmpFPU (Condition condition, bool * predicate) [inline]
Definition at line 2019 of file liftoff-assembler-loong64-inl.h.
                                                                {
  switch (condition) {
    case kEqual:
      *predicate = true;
      return CEQ;
    case kNotEqual:
      *predicate = false;
      return CEQ;
    case kUnsignedLessThan:
      *predicate = true;
      return CLT;
    case kUnsignedGreaterThanEqual:
      *predicate = false;
      return CLT;
    case kUnsignedLessThanEqual:
      *predicate = true;
      return CLE;
    case kUnsignedGreaterThan:
      *predicate = false;
      return CLE;
    default:
      *predicate = true;
      break;
  }
  UNREACHABLE();
}
References v8::internal::CEQ, v8::internal::CLE, v8::internal::CLT, v8::internal::kEqual, v8::internal::kNotEqual, v8::internal::kUnsignedGreaterThan, v8::internal::kUnsignedGreaterThanEqual, v8::internal::kUnsignedLessThan, v8::internal::kUnsignedLessThanEqual, and v8::internal::UNREACHABLE().
ConvertFloatToIntAndBack() [1/2]
template<typename dst_type , typename src_type >
void v8::internal::wasm::liftoff::ConvertFloatToIntAndBack (LiftoffAssembler * assm, Register dst, DoubleRegister src, DoubleRegister converted_back) [inline]
Definition at line 2025 of file liftoff-assembler-x64-inl.h.
                                                                    {
  if (std::is_same_v<double, src_type>) { // f64
    if (std::is_same_v<int32_t, dst_type>) { // f64 -> i32
      __ Cvttsd2si(dst, src);
      __ Cvtlsi2sd(converted_back, dst);
    } else if (std::is_same_v<uint32_t, dst_type>) { // f64 -> u32
      __ Cvttsd2siq(dst, src);
      __ movl(dst, dst);
      __ Cvtqsi2sd(converted_back, dst);
    } else if (std::is_same_v<int64_t, dst_type>) { // f64 -> i64
      __ Cvttsd2siq(dst, src);
      __ Cvtqsi2sd(converted_back, dst);
    } else {
      UNREACHABLE();
    }
  } else { // f32
    if (std::is_same_v<int32_t, dst_type>) { // f32 -> i32
      __ Cvttss2si(dst, src);
      __ Cvtlsi2ss(converted_back, dst);
    } else if (std::is_same_v<uint32_t, dst_type>) { // f32 -> u32
      __ Cvttss2siq(dst, src);
      __ movl(dst, dst);
      __ Cvtqsi2ss(converted_back, dst);
    } else if (std::is_same_v<int64_t, dst_type>) { // f32 -> i64
      __ Cvttss2siq(dst, src);
      __ Cvtqsi2ss(converted_back, dst);
    } else {
      UNREACHABLE();
    }
  }
}
References __, and v8::internal::UNREACHABLE().
ConvertFloatToIntAndBack() [2/2]
template<typename dst_type , typename src_type >
void v8::internal::wasm::liftoff::ConvertFloatToIntAndBack (LiftoffAssembler * assm, Register dst, DoubleRegister src, DoubleRegister converted_back, LiftoffRegList pinned) [inline]
Definition at line 2434 of file liftoff-assembler-ia32-inl.h.
                                                            {
  if (std::is_same_v<double, src_type>) { // f64
    if (std::is_signed_v<dst_type>) { // f64 -> i32
      __ cvttsd2si(dst, src);
      __ Cvtsi2sd(converted_back, dst);
    } else { // f64 -> u32
      // Use converted_back as a scratch register (we can use it as it is an
      // "output" register of this function.
      __ Cvttsd2ui(dst, src, converted_back);
      __ Cvtui2sd(converted_back, dst,
                  CacheStatePreservingTempRegisters(assm, pinned).Acquire());
    }
  } else { // f32
    if (std::is_signed_v<dst_type>) { // f32 -> i32
      __ cvttss2si(dst, src);
      __ Cvtsi2ss(converted_back, dst);
    } else { // f32 -> u32
      // Use converted_back as a scratch register (we can use it as it is an
      // "output" register of this function.
      __ Cvttss2ui(dst, src, converted_back);
      __ Cvtui2ss(converted_back, dst,
                  CacheStatePreservingTempRegisters(assm, pinned).Acquire());
    }
  }
}
References __.
Emit64BitShiftOperation() [1/2]
void v8::internal::wasm::liftoff::Emit64BitShiftOperation (LiftoffAssembler * assm, LiftoffRegister dst, LiftoffRegister src, Register amount, void(MacroAssembler::*)(Register, Register) emit_shift) [inline]
Definition at line 1921 of file liftoff-assembler-ia32-inl.h.
                                                                           {
  // Temporary registers cannot overlap with {dst}.
  LiftoffRegList pinned{dst};
  constexpr size_t kMaxRegMoves = 3;
  base::SmallVector<LiftoffAssembler::ParallelRegisterMoveTuple, kMaxRegMoves>
      reg_moves;
  // If {dst} contains {ecx}, replace it by an unused register, which is then
  // moved to {ecx} in the end.
  Register ecx_replace = no_reg;
  if (PairContains(dst, ecx)) {
    ecx_replace = assm->GetUnusedRegister(kGpReg, pinned).gp();
    dst = ReplaceInPair(dst, ecx, ecx_replace);
    // If {amount} needs to be moved to {ecx}, but {ecx} is in use (and not part
    // of {dst}, hence overwritten anyway), move {ecx} to a tmp register and
    // restore it at the end.
  } else if (amount != ecx &&
             (assm->cache_state()->is_used(LiftoffRegister(ecx)) ||
              pinned.has(LiftoffRegister(ecx)))) {
    ecx_replace = assm->GetUnusedRegister(kGpReg, pinned).gp();
    reg_moves.emplace_back(ecx_replace, ecx, kI32);
  }
  reg_moves.emplace_back(dst, src, kI64);
  reg_moves.emplace_back(ecx, amount, kI32);
  assm->ParallelRegisterMove(base::VectorOf(reg_moves));
  // Do the actual shift.
  (assm->*emit_shift)(dst.high_gp(), dst.low_gp());
  // Restore {ecx} if needed.
  if (ecx_replace != no_reg) assm->mov(ecx, ecx_replace);
}
References v8::internal::wasm::LiftoffAssembler::cache_state(), v8::base::SmallVector< T, kSize, Allocator >::emplace_back(), v8::internal::wasm::LiftoffAssembler::GetUnusedRegister(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::wasm::LiftoffRegister::high_gp(), v8::internal::wasm::LiftoffAssembler::CacheState::is_used(), v8::internal::wasm::kGpReg, v8::internal::kI32, v8::internal::kI64, v8::internal::wasm::LiftoffRegister::low_gp(), v8::internal::MacroAssembler::mov(), v8::internal::no_reg, PairContains(), v8::internal::wasm::LiftoffAssembler::ParallelRegisterMove(), ReplaceInPair(), and v8::base::VectorOf().
Emit64BitShiftOperation() [2/2]
void v8::internal::wasm::liftoff::Emit64BitShiftOperation (LiftoffAssembler * assm, LiftoffRegister dst, LiftoffRegister src, Register amount, void(MacroAssembler::*)(Register, Register, Register, Register, Register, Register, Register) emit_shift) [inline]
Definition at line 1520 of file liftoff-assembler-riscv32-inl.h.
                                                                      {
  LiftoffRegList pinned{dst, src, amount};
  // If some of destination registers are in use, get another, unused pair.
  // That way we prevent overwriting some input registers while shifting.
  // Do this before any branch so that the cache state will be correct for
  // all conditions.
  Register amount_capped =
      pinned.set(assm->GetUnusedRegister(kGpReg, pinned).gp());
  assm->And(amount_capped, amount, Operand(63));
  if (liftoff::IsRegInRegPair(dst, amount) || dst.overlaps(src)) {
    // Do the actual shift.
    LiftoffRegister tmp = assm->GetUnusedRegister(kGpRegPair, pinned);
    (assm->*emit_shift)(tmp.low_gp(), tmp.high_gp(), src.low_gp(),
                        src.high_gp(), amount_capped, kScratchReg,
                        kScratchReg2);
    // Place result in destination register.
    assm->MacroAssembler::Move(dst.high_gp(), tmp.high_gp());
    assm->MacroAssembler::Move(dst.low_gp(), tmp.low_gp());
  } else {
    (assm->*emit_shift)(dst.low_gp(), dst.high_gp(), src.low_gp(),
                        src.high_gp(), amount_capped, kScratchReg,
                        kScratchReg2);
  }
}
References v8::internal::MacroAssembler::And(), v8::internal::wasm::LiftoffAssembler::GetUnusedRegister(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::wasm::LiftoffRegister::high_gp(), IsRegInRegPair(), v8::internal::wasm::kGpReg, v8::internal::wasm::kGpRegPair, v8::internal::kScratchReg, v8::internal::kScratchReg2, v8::internal::wasm::LiftoffRegister::low_gp(), and v8::internal::wasm::LiftoffRegister::overlaps().
EmitAllTrue() [1/3]
void v8::internal::wasm::liftoff::EmitAllTrue (LiftoffAssembler * assm, LiftoffRegister dst, LiftoffRegister src, MSABranchDF msa_branch_df) [inline]
Definition at line 2088 of file liftoff-assembler-mips64-inl.h.
                                                                        {
  Label all_true;
  assm->BranchMSA(&all_true, msa_branch_df, all_not_zero, src.fp().toW(),
                  USE_DELAY_SLOT);
  assm->li(dst.gp(), 1);
  assm->li(dst.gp(), 0l);
  assm->bind(&all_true);
}
References v8::internal::all_not_zero, v8::internal::Assembler::bind(), v8::internal::MacroAssembler::BranchMSA(), v8::internal::wasm::LiftoffRegister::fp(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::compiler::turboshaft::l, v8::internal::MacroAssembler::li(), and v8::internal::USE_DELAY_SLOT.
EmitAllTrue() [2/3]
template<void(SharedMacroAssemblerBase::*)(XMMRegister, XMMRegister) pcmp>
void v8::internal::wasm::liftoff::EmitAllTrue (LiftoffAssembler * assm, LiftoffRegister dst, LiftoffRegister src, std::optional< CpuFeature > feature = std::nullopt) [inline]
Definition at line 2961 of file liftoff-assembler-ia32-inl.h.
                                                                      {
  std::optional<CpuFeatureScope> sse_scope;
  if (feature.has_value()) sse_scope.emplace(assm, *feature);
  Register tmp = assm->GetUnusedRegister(kGpReg, LiftoffRegList{dst}).gp();
  XMMRegister tmp_simd = liftoff::kScratchDoubleReg;
  assm->mov(tmp, Immediate(1));
  assm->xor_(dst.gp(), dst.gp());
  assm->Pxor(tmp_simd, tmp_simd);
  (assm->*pcmp)(tmp_simd, src.fp());
  assm->Ptest(tmp_simd, tmp_simd);
  assm->cmov(zero, dst.gp(), tmp);
}
References v8::internal::Assembler::cmov(), v8::internal::wasm::LiftoffRegister::fp(), v8::internal::wasm::LiftoffAssembler::GetUnusedRegister(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::wasm::kGpReg, kScratchDoubleReg, v8::internal::MacroAssembler::mov(), v8::internal::Assembler::xor_(), and v8::internal::zero.
EmitAllTrue() [3/3]
void v8::internal::wasm::liftoff::EmitAllTrue (LiftoffAssembler * assm, LiftoffRegister dst, LiftoffRegister src, VectorFormat format) [inline]
Definition at line 199 of file liftoff-assembler-arm64-inl.h.
                                                                  {
  UseScratchRegisterScope scope(assm);
  VRegister temp = scope.AcquireV(ScalarFormatFromFormat(format));
  assm->Uminv(temp, VRegister::Create(src.fp().code(), format));
  assm->Umov(dst.gp().W(), temp, 0);
  assm->Cmp(dst.gp().W(), 0);
  assm->Cset(dst.gp().W(), ne);
}
References v8::internal::UseScratchRegisterScope::AcquireV(), v8::internal::MacroAssembler::Cmp(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::VRegister::Create(), v8::internal::MacroAssembler::Cset(), v8::internal::format, v8::internal::wasm::LiftoffRegister::fp(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::ne, v8::internal::ScalarFormatFromFormat(), v8::internal::MacroAssembler::Umov(), and v8::internal::CPURegister::W().
EmitAnyTrue()
void v8::internal::wasm::liftoff::EmitAnyTrue (LiftoffAssembler * assm, LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 414 of file liftoff-assembler-arm-inl.h.
                                             {
  UseScratchRegisterScope temps(assm);
  DwVfpRegister scratch = temps.AcquireD();
  assm->vpmax(NeonU32, scratch, src.low_fp(), src.high_fp());
  assm->vpmax(NeonU32, scratch, scratch, scratch);
  assm->ExtractLane(dst.gp(), scratch, NeonS32, 0);
  assm->cmp(dst.gp(), Operand(0));
  assm->mov(dst.gp(), Operand(1), LeaveCC, ne);
}
References v8::internal::UseScratchRegisterScope::AcquireD(), v8::internal::Assembler::cmp(), v8::internal::MacroAssembler::ExtractLane(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::wasm::LiftoffRegister::high_fp(), v8::internal::LeaveCC, v8::internal::wasm::LiftoffRegister::low_fp(), v8::internal::MacroAssembler::mov(), v8::internal::ne, v8::internal::NeonS32, v8::internal::NeonU32, and v8::internal::Assembler::vpmax().
Referenced by v8::internal::wasm::LiftoffAssembler::emit_v128_anytrue().
EmitCommutativeBinOp() [1/2]
template<void(Assembler::*)(Register, Register) op>
void v8::internal::wasm::liftoff::EmitCommutativeBinOp (LiftoffAssembler * assm, Register dst, Register lhs, Register rhs)
Definition at line 1544 of file liftoff-assembler-ia32-inl.h.
                                        {
  if (dst == rhs) {
    (assm->*op)(dst, lhs);
  } else {
    if (dst != lhs) assm->mov(dst, lhs);
    (assm->*op)(dst, rhs);
  }
}
References v8::internal::MacroAssembler::mov().
EmitCommutativeBinOp() [2/2]
template<void(Assembler::*)(Register, Register) op, void(Assembler::*)(Register, Register) mov>
void v8::internal::wasm::liftoff::EmitCommutativeBinOp (LiftoffAssembler * assm, Register dst, Register lhs, Register rhs)
Definition at line 1263 of file liftoff-assembler-x64-inl.h.
                                        {
  if (dst == rhs) {
    (assm->*op)(dst, lhs);
  } else {
    if (dst != lhs) (assm->*mov)(dst, lhs);
    (assm->*op)(dst, rhs);
  }
}
EmitCommutativeBinOpImm() [1/2]
template<void(Assembler::*)(Register, int32_t) op>
void v8::internal::wasm::liftoff::EmitCommutativeBinOpImm (LiftoffAssembler * assm, Register dst, Register lhs, int32_t imm)
Definition at line 1555 of file liftoff-assembler-ia32-inl.h.
                                          {
  if (dst != lhs) assm->mov(dst, lhs);
  (assm->*op)(dst, imm);
}
References v8::internal::MacroAssembler::mov().
EmitCommutativeBinOpImm() [2/2]
template<void(Assembler::*)(Register, Immediate) op, void(Assembler::*)(Register, Register) mov>
void v8::internal::wasm::liftoff::EmitCommutativeBinOpImm (LiftoffAssembler * assm, Register dst, Register lhs, int32_t imm)
Definition at line 1275 of file liftoff-assembler-x64-inl.h.
                                          {
  if (dst != lhs) (assm->*mov)(dst, lhs);
  (assm->*op)(dst, Immediate(imm));
}
EmitFloatMinOrMax() [1/2]
template<typename type >
void v8::internal::wasm::liftoff::EmitFloatMinOrMax (LiftoffAssembler * assm, DoubleRegister dst, DoubleRegister lhs, DoubleRegister rhs, MinOrMax min_or_max) [inline]
Definition at line 2157 of file liftoff-assembler-ia32-inl.h.
                                                   {
  Label is_nan;
  Label lhs_below_rhs;
  Label lhs_above_rhs;
  Label done;
  // We need one tmp register to extract the sign bit. Get it right at the
  // beginning, such that the spilling code is not accidentially jumped over.
  Register tmp = assm->GetUnusedRegister(kGpReg, {}).gp();
#define dop(name, ...) \
  do { \
    if (sizeof(type) == 4) { \
      assm->name##s(__VA_ARGS__); \
    } else { \
      assm->name##d(__VA_ARGS__); \
    } \
  } while (false)
  // Check the easy cases first: nan (e.g. unordered), smaller and greater.
  // NaN has to be checked first, because PF=1 implies CF=1.
  dop(ucomis, lhs, rhs);
  assm->j(parity_even, &is_nan, Label::kNear); // PF=1
  assm->j(below, &lhs_below_rhs, Label::kNear); // CF=1
  assm->j(above, &lhs_above_rhs, Label::kNear); // CF=0 && ZF=0
  // If we get here, then either
  // a) {lhs == rhs},
  // b) {lhs == -0.0} and {rhs == 0.0}, or
  // c) {lhs == 0.0} and {rhs == -0.0}.
  // For a), it does not matter whether we return {lhs} or {rhs}. Check the sign
  // bit of {rhs} to differentiate b) and c).
  dop(movmskp, tmp, rhs);
  assm->test(tmp, Immediate(1));
  assm->j(zero, &lhs_below_rhs, Label::kNear);
  assm->jmp(&lhs_above_rhs, Label::kNear);
  assm->bind(&is_nan);
  // Create a NaN output.
  dop(xorp, dst, dst);
  dop(divs, dst, dst);
  assm->jmp(&done, Label::kNear);
  assm->bind(&lhs_below_rhs);
  DoubleRegister lhs_below_rhs_src = min_or_max == MinOrMax::kMin ? lhs : rhs;
  if (dst != lhs_below_rhs_src) dop(movs, dst, lhs_below_rhs_src);
  assm->jmp(&done, Label::kNear);
  assm->bind(&lhs_above_rhs);
  DoubleRegister lhs_above_rhs_src = min_or_max == MinOrMax::kMin ? rhs : lhs;
  if (dst != lhs_above_rhs_src) dop(movs, dst, lhs_above_rhs_src);
  assm->bind(&done);
}
References v8::internal::above, v8::internal::below, v8::internal::Assembler::bind(), dop, v8::internal::wasm::LiftoffAssembler::GetUnusedRegister(), v8::internal::Assembler::j(), v8::internal::MacroAssembler::jmp(), v8::internal::wasm::kGpReg, kMin, v8::internal::Label::kNear, v8::internal::parity_even, v8::internal::Assembler::test(), and v8::internal::zero.
EmitFloatMinOrMax() [2/2]
template<typename RegisterType >
void v8::internal::wasm::liftoff::EmitFloatMinOrMax (LiftoffAssembler * assm, RegisterType dst, RegisterType lhs, RegisterType rhs, MinOrMax min_or_max) [inline]
Definition at line 206 of file liftoff-assembler-arm-inl.h.
                                                   {
  DCHECK(RegisterType::kSizeInBytes == 4 || RegisterType::kSizeInBytes == 8);
  if (lhs == rhs) {
    assm->MacroAssembler::Move(dst, lhs);
    return;
  }
  Label done, is_nan;
  if (min_or_max == MinOrMax::kMin) {
    assm->MacroAssembler::FloatMin(dst, lhs, rhs, &is_nan);
  } else {
    assm->MacroAssembler::FloatMax(dst, lhs, rhs, &is_nan);
  }
  assm->b(&done);
  assm->bind(&is_nan);
  // Create a NaN output.
  assm->vadd(dst, lhs, rhs);
  assm->bind(&done);
}
References v8::internal::Assembler::b(), v8::internal::Assembler::bind(), v8::internal::DCHECK(), kMin, and v8::internal::Assembler::vadd().
Referenced by v8::internal::wasm::LiftoffAssembler::emit_f32_max(), v8::internal::wasm::LiftoffAssembler::emit_f32_min(), v8::internal::wasm::LiftoffAssembler::emit_f64_max(), v8::internal::wasm::LiftoffAssembler::emit_f64_min(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_max(), and v8::internal::wasm::LiftoffAssembler::emit_f64x2_min().
EmitFloatSetCond()
template<void(Assembler::*)(DoubleRegister, DoubleRegister) cmp_op>
void v8::internal::wasm::liftoff::EmitFloatSetCond (LiftoffAssembler * assm, Condition cond, Register dst, DoubleRegister lhs, DoubleRegister rhs)
Definition at line 2816 of file liftoff-assembler-ia32-inl.h.
                                                              {
  Label cont;
  Label not_nan;
  // Get the tmp byte register out here, such that we don't conditionally spill
  // (this cannot be reflected in the cache state).
  Register tmp_byte_reg = GetTmpByteRegister(assm, dst);
  (assm->*cmp_op)(lhs, rhs);
  // If PF is one, one of the operands was Nan. This needs special handling.
  assm->j(parity_odd, &not_nan, Label::kNear);
  // Return 1 for f32.ne, 0 for all other cases.
  if (cond == not_equal) {
    assm->mov(dst, Immediate(1));
  } else {
    assm->xor_(dst, dst);
  }
  assm->jmp(&cont, Label::kNear);
  assm->bind(&not_nan);
  setcc_32_no_spill(assm, cond, dst, tmp_byte_reg);
  assm->bind(&cont);
}
References v8::internal::Assembler::bind(), GetTmpByteRegister(), v8::internal::Assembler::j(), v8::internal::MacroAssembler::jmp(), v8::internal::Label::kNear, v8::internal::MacroAssembler::mov(), v8::internal::not_equal, v8::internal::parity_odd, setcc_32_no_spill(), and v8::internal::Assembler::xor_().
EmitInt32DivOrRem()
template<bool is_signed, DivOrRem div_or_rem>
void v8::internal::wasm::liftoff::EmitInt32DivOrRem (LiftoffAssembler * assm, Register dst, Register lhs, Register rhs, Label * trap_div_by_zero, Label * trap_div_unrepresentable)
Definition at line 1577 of file liftoff-assembler-ia32-inl.h.
                                                        {
  constexpr bool needs_unrepresentable_check =
      is_signed && div_or_rem == DivOrRem::kDiv;
  constexpr bool special_case_minus_1 =
      is_signed && div_or_rem == DivOrRem::kRem;
  DCHECK_EQ(needs_unrepresentable_check, trap_div_unrepresentable != nullptr);
  // For division, the lhs is always taken from {edx:eax}. Thus, make sure that
  // these registers are unused. If {rhs} is stored in one of them, move it to
  // another temporary register.
  // Do all this before any branch, such that the code is executed
  // unconditionally, as the cache state will also be modified unconditionally.
  assm->SpillRegisters(eax, edx);
  if (rhs == eax || rhs == edx) {
    LiftoffRegList unavailable{eax, edx, lhs};
    Register tmp = assm->GetUnusedRegister(kGpReg, unavailable).gp();
    assm->mov(tmp, rhs);
    rhs = tmp;
  }
  // Check for division by zero.
  assm->test(rhs, rhs);
  assm->j(zero, trap_div_by_zero);
  Label done;
  if (needs_unrepresentable_check) {
    // Check for {kMinInt / -1}. This is unrepresentable.
    Label do_div;
    assm->cmp(rhs, -1);
    assm->j(not_equal, &do_div);
    assm->cmp(lhs, kMinInt);
    assm->j(equal, trap_div_unrepresentable);
    assm->bind(&do_div);
  } else if (special_case_minus_1) {
    // {lhs % -1} is always 0 (needs to be special cased because {kMinInt / -1}
    // cannot be computed).
    Label do_rem;
    assm->cmp(rhs, -1);
    assm->j(not_equal, &do_rem);
    assm->xor_(dst, dst);
    assm->jmp(&done);
    assm->bind(&do_rem);
  }
  // Now move {lhs} into {eax}, then zero-extend or sign-extend into {edx}, then
  // do the division.
  if (lhs != eax) assm->mov(eax, lhs);
  if (is_signed) {
    assm->cdq();
    assm->idiv(rhs);
  } else {
    assm->xor_(edx, edx);
    assm->div(rhs);
  }
  // Move back the result (in {eax} or {edx}) into the {dst} register.
  constexpr Register kResultReg = div_or_rem == DivOrRem::kDiv ? eax : edx;
  if (dst != kResultReg) assm->mov(dst, kResultReg);
  if (special_case_minus_1) assm->bind(&done);
}
References v8::internal::Assembler::bind(), v8::internal::Assembler::cdq(), v8::internal::Assembler::cmp(), DCHECK_EQ, v8::internal::Assembler::div(), v8::internal::equal, v8::internal::wasm::LiftoffAssembler::GetUnusedRegister(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::Assembler::idiv(), v8::internal::is_signed(), v8::internal::Assembler::j(), v8::internal::MacroAssembler::jmp(), kDiv, v8::internal::wasm::kGpReg, v8::internal::kMinInt, kRem, v8::internal::MacroAssembler::mov(), v8::internal::not_equal, v8::internal::wasm::LiftoffAssembler::SpillRegisters(), v8::internal::Assembler::test(), v8::internal::Assembler::xor_(), and v8::internal::zero.
EmitIntDivOrRem()
template<typename type , DivOrRem div_or_rem>
void v8::internal::wasm::liftoff::EmitIntDivOrRem (LiftoffAssembler * assm, Register dst, Register lhs, Register rhs, Label * trap_div_by_zero, Label * trap_div_unrepresentable)
Definition at line 1291 of file liftoff-assembler-x64-inl.h.
                                                      {
  constexpr bool needs_unrepresentable_check =
      std::is_signed_v<type> && div_or_rem == DivOrRem::kDiv;
  constexpr bool special_case_minus_1 =
      std::is_signed_v<type> && div_or_rem == DivOrRem::kRem;
  DCHECK_EQ(needs_unrepresentable_check, trap_div_unrepresentable != nullptr);
#define iop(name, ...) \
  do { \
    if (sizeof(type) == 4) { \
      assm->name##l(__VA_ARGS__); \
    } else { \
      assm->name##q(__VA_ARGS__); \
    } \
  } while (false)
  // For division, the lhs is always taken from {edx:eax}. Thus, make sure that
  // these registers are unused. If {rhs} is stored in one of them, move it to
  // another temporary register.
  // Do all this before any branch, such that the code is executed
  // unconditionally, as the cache state will also be modified unconditionally.
  assm->SpillRegisters(rdx, rax);
  if (rhs == rax || rhs == rdx) {
    iop(mov, kScratchRegister, rhs);
    rhs = kScratchRegister;
  }
  // Check for division by zero.
  iop(test, rhs, rhs);
  assm->j(zero, trap_div_by_zero);
  Label done;
  if (needs_unrepresentable_check) {
    // Check for {kMinInt / -1}. This is unrepresentable.
    Label do_div;
    iop(cmp, rhs, Immediate(-1));
    assm->j(not_equal, &do_div);
    // {lhs} is min int if {lhs - 1} overflows.
    iop(cmp, lhs, Immediate(1));
    assm->j(overflow, trap_div_unrepresentable);
    assm->bind(&do_div);
  } else if (special_case_minus_1) {
    // {lhs % -1} is always 0 (needs to be special cased because {kMinInt / -1}
    // cannot be computed).
    Label do_rem;
    iop(cmp, rhs, Immediate(-1));
    assm->j(not_equal, &do_rem);
    // clang-format off
    // (conflicts with presubmit checks because it is confused about "xor")
    iop(xor, dst, dst);
    // clang-format on
    assm->jmp(&done);
    assm->bind(&do_rem);
  }
  // Now move {lhs} into {eax}, then zero-extend or sign-extend into {edx}, then
  // do the division.
  if (lhs != rax) iop(mov, rax, lhs);
  if (std::is_same_v<int32_t, type>) { // i32
    assm->cdq();
    assm->idivl(rhs);
  } else if (std::is_same_v<uint32_t, type>) { // u32
    assm->xorl(rdx, rdx);
    assm->divl(rhs);
  } else if (std::is_same_v<int64_t, type>) { // i64
    assm->cqo();
    assm->idivq(rhs);
  } else { // u64
    assm->xorq(rdx, rdx);
    assm->divq(rhs);
  }
  // Move back the result (in {eax} or {edx}) into the {dst} register.
  constexpr Register kResultReg = div_or_rem == DivOrRem::kDiv ? rax : rdx;
  if (dst != kResultReg) {
    iop(mov, dst, kResultReg);
  }
  if (special_case_minus_1) assm->bind(&done);
}
References v8::internal::Assembler::bind(), v8::internal::Assembler::cdq(), v8::internal::Assembler::cqo(), DCHECK_EQ, iop, v8::internal::Assembler::j(), v8::internal::MacroAssembler::jmp(), v8::internal::kScratchRegister, v8::internal::not_equal, v8::internal::overflow, v8::internal::wasm::LiftoffAssembler::SpillRegisters(), and v8::internal::zero.
EmitSatTruncateFloatToInt()
template<typename dst_type , typename src_type >
void v8::internal::wasm::liftoff::EmitSatTruncateFloatToInt (LiftoffAssembler * assm, Register dst, DoubleRegister src) [inline]
Definition at line 2498 of file liftoff-assembler-ia32-inl.h.
                                                          {
  if (!CpuFeatures::IsSupported(SSE4_1)) {
    __ bailout(kMissingCPUFeature, "no SSE4.1");
    return;
  }
  CpuFeatureScope feature(assm, SSE4_1);
  Label done;
  Label not_nan;
  Label src_positive;
  LiftoffRegList pinned{src, dst};
  DoubleRegister rounded =
      pinned.set(__ GetUnusedRegister(kFpReg, pinned)).fp();
  DoubleRegister converted_back =
      pinned.set(__ GetUnusedRegister(kFpReg, pinned)).fp();
  DoubleRegister zero_reg =
      pinned.set(__ GetUnusedRegister(kFpReg, pinned)).fp();
  if (std::is_same_v<double, src_type>) { // f64
    __ roundsd(rounded, src, kRoundToZero);
  } else { // f32
    __ roundss(rounded, src, kRoundToZero);
  }
  ConvertFloatToIntAndBack<dst_type, src_type>(assm, dst, rounded,
                                               converted_back, pinned);
  if (std::is_same_v<double, src_type>) { // f64
    __ ucomisd(converted_back, rounded);
  } else { // f32
    __ ucomiss(converted_back, rounded);
  }
  // Return 0 if PF is 0 (one of the operands was NaN)
  __ j(parity_odd, &not_nan);
  __ xor_(dst, dst);
  __ jmp(&done);
  __ bind(&not_nan);
  // If rounding is as expected, return result
  __ j(equal, &done);
  __ Xorpd(zero_reg, zero_reg);
  // if out-of-bounds, check if src is positive
  if (std::is_same_v<double, src_type>) { // f64
    __ ucomisd(src, zero_reg);
  } else { // f32
    __ ucomiss(src, zero_reg);
  }
  __ j(above, &src_positive);
  __ mov(dst, Immediate(std::numeric_limits<dst_type>::min()));
  __ jmp(&done);
  __ bind(&src_positive);
  __ mov(dst, Immediate(std::numeric_limits<dst_type>::max()));
  __ bind(&done);
}
References __, v8::internal::above, v8::internal::equal, v8::internal::CpuFeatures::IsSupported(), v8::internal::wasm::kFpReg, v8::internal::wasm::kMissingCPUFeature, v8::internal::kRoundToZero, and v8::internal::parity_odd.
EmitSatTruncateFloatToUInt64()
template<typename src_type >
void v8::internal::wasm::liftoff::EmitSatTruncateFloatToUInt64 (LiftoffAssembler * assm, Register dst, DoubleRegister src) [inline]
Definition at line 2167 of file liftoff-assembler-x64-inl.h.
                                                             {
  if (!CpuFeatures::IsSupported(SSE4_1)) {
    __ bailout(kMissingCPUFeature, "no SSE4.1");
    return;
  }
  CpuFeatureScope feature(assm, SSE4_1);
  Label done;
  Label neg_or_nan;
  Label overflow;
  DoubleRegister zero_reg = kScratchDoubleReg;
  __ xorpd(zero_reg, zero_reg);
  if (std::is_same_v<double, src_type>) { // f64
    __ Ucomisd(src, zero_reg);
  } else { // f32
    __ Ucomiss(src, zero_reg);
  }
  // Check if NaN
  __ j(parity_even, &neg_or_nan);
  __ j(below, &neg_or_nan);
  if (std::is_same_v<double, src_type>) { // f64
    __ Cvttsd2uiq(dst, src, &overflow);
  } else { // f32
    __ Cvttss2uiq(dst, src, &overflow);
  }
  __ jmp(&done);
  __ bind(&neg_or_nan);
  __ movq(dst, zero_reg);
  __ jmp(&done);
  __ bind(&overflow);
  __ movq(dst, Immediate64(std::numeric_limits<uint64_t>::max()));
  __ bind(&done);
}
References __, v8::internal::below, v8::internal::CpuFeatures::IsSupported(), v8::internal::wasm::kMissingCPUFeature, v8::internal::kScratchDoubleReg, v8::internal::overflow, and v8::internal::parity_even.
EmitShiftOperation()
void v8::internal::wasm::liftoff::EmitShiftOperation (LiftoffAssembler * assm, Register dst, Register src, Register amount, void(Assembler::*)(Register) emit_shift) [inline]
Definition at line 1691 of file liftoff-assembler-ia32-inl.h.
                                                                      {
  LiftoffRegList pinned{dst, src, amount};
  // If dst is ecx, compute into a tmp register first, then move to ecx.
  if (dst == ecx) {
    Register tmp = assm->GetUnusedRegister(kGpReg, pinned).gp();
    assm->mov(tmp, src);
    if (amount != ecx) assm->mov(ecx, amount);
    (assm->*emit_shift)(tmp);
    assm->mov(ecx, tmp);
    return;
  }
  // Move amount into ecx. If ecx is in use, move its content to a tmp register
  // first. If src is ecx, src is now the tmp register.
  Register tmp_reg = no_reg;
  if (amount != ecx) {
    if (assm->cache_state()->is_used(LiftoffRegister(ecx)) ||
        pinned.has(LiftoffRegister(ecx))) {
      tmp_reg = assm->GetUnusedRegister(kGpReg, pinned).gp();
      assm->mov(tmp_reg, ecx);
      if (src == ecx) src = tmp_reg;
    }
    assm->mov(ecx, amount);
  }
  // Do the actual shift.
  if (dst != src) assm->mov(dst, src);
  (assm->*emit_shift)(dst);
  // Restore ecx if needed.
  if (tmp_reg.is_valid()) assm->mov(ecx, tmp_reg);
}
References v8::internal::wasm::LiftoffAssembler::cache_state(), v8::internal::wasm::LiftoffAssembler::GetUnusedRegister(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::wasm::LiftoffAssembler::CacheState::is_used(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::is_valid(), v8::internal::wasm::kGpReg, v8::internal::MacroAssembler::mov(), and v8::internal::no_reg.
EmitSimdCommutativeBinOp()
template<void(Assembler::*)(XMMRegister, XMMRegister, XMMRegister) avx_op, void(Assembler::*)(XMMRegister, XMMRegister) sse_op>
void v8::internal::wasm::liftoff::EmitSimdCommutativeBinOp (LiftoffAssembler * assm, LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs, std::optional< CpuFeature > feature = std::nullopt)
Definition at line 2872 of file liftoff-assembler-ia32-inl.h.
                                                                       {
  if (CpuFeatures::IsSupported(AVX)) {
    CpuFeatureScope scope(assm, AVX);
    (assm->*avx_op)(dst.fp(), lhs.fp(), rhs.fp());
    return;
  }
  std::optional<CpuFeatureScope> sse_scope;
  if (feature.has_value()) sse_scope.emplace(assm, *feature);
  if (dst.fp() == rhs.fp()) {
    (assm->*sse_op)(dst.fp(), lhs.fp());
  } else {
    if (dst.fp() != lhs.fp()) (assm->movaps)(dst.fp(), lhs.fp());
    (assm->*sse_op)(dst.fp(), rhs.fp());
  }
}
References v8::internal::wasm::LiftoffRegister::fp(), v8::internal::CpuFeatures::IsSupported(), and v8::internal::Assembler::movaps().
EmitSimdNonCommutativeBinOp()
template<void(Assembler::*)(XMMRegister, XMMRegister, XMMRegister) avx_op, void(Assembler::*)(XMMRegister, XMMRegister) sse_op>
void v8::internal::wasm::liftoff::EmitSimdNonCommutativeBinOp (LiftoffAssembler * assm, LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs, std::optional< CpuFeature > feature = std::nullopt)
Definition at line 2894 of file liftoff-assembler-ia32-inl.h.
                                                                       {
  if (CpuFeatures::IsSupported(AVX)) {
    CpuFeatureScope scope(assm, AVX);
    (assm->*avx_op)(dst.fp(), lhs.fp(), rhs.fp());
    return;
  }
  std::optional<CpuFeatureScope> sse_scope;
  if (feature.has_value()) sse_scope.emplace(assm, *feature);
  if (dst.fp() == rhs.fp()) {
    assm->movaps(kScratchDoubleReg, rhs.fp());
    assm->movaps(dst.fp(), lhs.fp());
    (assm->*sse_op)(dst.fp(), kScratchDoubleReg);
  } else {
    if (dst.fp() != lhs.fp()) assm->movaps(dst.fp(), lhs.fp());
    (assm->*sse_op)(dst.fp(), rhs.fp());
  }
}
References v8::internal::wasm::LiftoffRegister::fp(), v8::internal::CpuFeatures::IsSupported(), kScratchDoubleReg, and v8::internal::Assembler::movaps().
EmitSimdShift() [1/2]
template<ShiftDirection dir = kLeft, NeonDataType dt, NeonSize sz>
void v8::internal::wasm::liftoff::EmitSimdShift (LiftoffAssembler * assm, LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 380 of file liftoff-assembler-arm-inl.h.
                                                                    {
  constexpr int mask = MaskFromNeonDataType(dt);
  UseScratchRegisterScope temps(assm);
  QwNeonRegister tmp = temps.AcquireQ();
  Register shift = temps.Acquire();
  assm->and_(shift, rhs.gp(), Operand(mask));
  assm->vdup(sz, tmp, shift);
  if (dir == kRight) {
    assm->vneg(sz, tmp, tmp);
  }
  assm->vshl(dt, liftoff::GetSimd128Register(dst),
             liftoff::GetSimd128Register(lhs), tmp);
}
References v8::internal::UseScratchRegisterScope::Acquire(), v8::internal::UseScratchRegisterScope::AcquireQ(), v8::internal::Assembler::and_(), GetSimd128Register(), v8::internal::wasm::LiftoffRegister::gp(), kRight, MaskFromNeonDataType(), v8::internal::Assembler::vdup(), v8::internal::Assembler::vneg(), and v8::internal::Assembler::vshl().
EmitSimdShift() [2/2]
template<ShiftDirection dir, ShiftSign sign = ShiftSign::kSigned>
void v8::internal::wasm::liftoff::EmitSimdShift (LiftoffAssembler * assm, VRegister dst, VRegister lhs, Register rhs, VectorFormat format) [inline]
Definition at line 144 of file liftoff-assembler-arm64-inl.h.
                                                             {
  DCHECK_IMPLIES(dir == ShiftDirection::kLeft, sign == ShiftSign::kSigned);
  DCHECK(dst.IsSameFormat(lhs));
  DCHECK_EQ(dst.LaneCount(), LaneCountFromFormat(format));
  UseScratchRegisterScope temps(assm);
  VRegister tmp = temps.AcquireV(format);
  Register shift = dst.Is2D() ? temps.AcquireX() : temps.AcquireW();
  int mask = LaneSizeInBitsFromFormat(format) - 1;
  assm->And(shift, rhs, mask);
  assm->Dup(tmp, shift);
  if (dir == ShiftDirection::kRight) {
    assm->Neg(tmp, tmp);
  }
  if (sign == ShiftSign::kSigned) {
    assm->Sshl(dst, lhs, tmp);
  } else {
    assm->Ushl(dst, lhs, tmp);
  }
}
References v8::internal::UseScratchRegisterScope::AcquireV(), v8::internal::UseScratchRegisterScope::AcquireW(), v8::internal::UseScratchRegisterScope::AcquireX(), v8::internal::MacroAssembler::And(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::MacroAssembler::Dup(), v8::internal::format, v8::internal::VRegister::Is2D(), v8::internal::VRegister::IsSameFormat(), kLeft, kRight, kSigned, v8::internal::VRegister::LaneCount(), v8::internal::LaneCountFromFormat(), v8::internal::LaneSizeInBitsFromFormat(), v8::internal::MacroAssembler::Neg(), and v8::internal::sign.
EmitSimdShiftImmediate()
template<ShiftDirection dir, NeonDataType dt>
void v8::internal::wasm::liftoff::EmitSimdShiftImmediate (LiftoffAssembler * assm, LiftoffRegister dst, LiftoffRegister lhs, int32_t rhs) [inline]
Definition at line 396 of file liftoff-assembler-arm-inl.h.
                                                                     {
  // vshr by 0 is not allowed, so check for it, and only move if dst != lhs.
  int32_t shift = rhs & MaskFromNeonDataType(dt);
  if (shift) {
    if (dir == kLeft) {
      assm->vshl(dt, liftoff::GetSimd128Register(dst),
                 liftoff::GetSimd128Register(lhs), shift);
    } else {
      assm->vshr(dt, liftoff::GetSimd128Register(dst),
                 liftoff::GetSimd128Register(lhs), shift);
    }
  } else if (dst != lhs) {
    assm->vmov(liftoff::GetSimd128Register(dst),
               liftoff::GetSimd128Register(lhs));
  }
}
References GetSimd128Register(), kLeft, MaskFromNeonDataType(), v8::internal::Assembler::vmov(), v8::internal::Assembler::vshl(), and v8::internal::Assembler::vshr().
EmitSimdShiftOp()
template<void(Assembler::*)(XMMRegister, XMMRegister, XMMRegister) avx_op, void(Assembler::*)(XMMRegister, XMMRegister) sse_op, uint8_t width>
void v8::internal::wasm::liftoff::EmitSimdShiftOp (LiftoffAssembler * assm, LiftoffRegister dst, LiftoffRegister operand, LiftoffRegister count)
Definition at line 2918 of file liftoff-assembler-ia32-inl.h.
                                                                     {
  static constexpr RegClass tmp_rc = reg_class_for(kI32);
  LiftoffRegister tmp = assm->GetUnusedRegister(tmp_rc, LiftoffRegList{count});
  constexpr int mask = (1 << width) - 1;
  assm->mov(tmp.gp(), count.gp());
  assm->and_(tmp.gp(), Immediate(mask));
  assm->Movd(kScratchDoubleReg, tmp.gp());
  if (CpuFeatures::IsSupported(AVX)) {
    CpuFeatureScope scope(assm, AVX);
    (assm->*avx_op)(dst.fp(), operand.fp(), kScratchDoubleReg);
  } else {
    if (dst.fp() != operand.fp()) assm->movaps(dst.fp(), operand.fp());
    (assm->*sse_op)(dst.fp(), kScratchDoubleReg);
  }
}
References v8::internal::Assembler::and_(), v8::internal::wasm::LiftoffRegister::fp(), v8::internal::wasm::LiftoffAssembler::GetUnusedRegister(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::CpuFeatures::IsSupported(), v8::internal::kI32, kScratchDoubleReg, v8::internal::MacroAssembler::mov(), v8::internal::Assembler::movaps(), and v8::internal::wasm::reg_class_for().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
EmitSimdShiftOpImm()
template<void(Assembler::*)(XMMRegister, XMMRegister, uint8_t) avx_op, void(Assembler::*)(XMMRegister, uint8_t) sse_op, uint8_t width>
void v8::internal::wasm::liftoff::EmitSimdShiftOpImm (LiftoffAssembler * assm, LiftoffRegister dst, LiftoffRegister operand, int32_t count)
Definition at line 2938 of file liftoff-assembler-ia32-inl.h.
                                                                {
  constexpr int mask = (1 << width) - 1;
  uint8_t shift = static_cast<uint8_t>(count & mask);
  if (CpuFeatures::IsSupported(AVX)) {
    CpuFeatureScope scope(assm, AVX);
    (assm->*avx_op)(dst.fp(), operand.fp(), shift);
  } else {
    if (dst.fp() != operand.fp()) assm->movaps(dst.fp(), operand.fp());
    (assm->*sse_op)(dst.fp(), shift);
  }
}
References v8::internal::wasm::LiftoffRegister::fp(), v8::internal::CpuFeatures::IsSupported(), and v8::internal::Assembler::movaps().
EmitSimdShiftRightImmediate()
template<VectorFormat format, ShiftSign sign>
void v8::internal::wasm::liftoff::EmitSimdShiftRightImmediate (LiftoffAssembler * assm, VRegister dst, VRegister lhs, int32_t rhs) [inline]
Definition at line 169 of file liftoff-assembler-arm64-inl.h.
                                                                    {
  // Sshr and Ushr does not allow shifts to be 0, so check for that here.
  int mask = LaneSizeInBitsFromFormat(format) - 1;
  int32_t shift = rhs & mask;
  if (!shift) {
    if (dst != lhs) {
      assm->Mov(dst, lhs);
    }
    return;
  }
  if (sign == ShiftSign::kSigned) {
    assm->Sshr(dst, lhs, rhs & mask);
  } else {
    assm->Ushr(dst, lhs, rhs & mask);
  }
}
References v8::internal::format, kSigned, v8::internal::LaneSizeInBitsFromFormat(), v8::internal::MacroAssembler::Mov(), and v8::internal::sign.
EmitTruncateFloatToInt()
template<typename dst_type , typename src_type >
void v8::internal::wasm::liftoff::EmitTruncateFloatToInt (LiftoffAssembler * assm, Register dst, DoubleRegister src, Label * trap) [inline]
Definition at line 2464 of file liftoff-assembler-ia32-inl.h.
                                                                    {
  if (!CpuFeatures::IsSupported(SSE4_1)) {
    __ bailout(kMissingCPUFeature, "no SSE4.1");
    return;
  }
  CpuFeatureScope feature(assm, SSE4_1);
  LiftoffRegList pinned{src, dst};
  // Note: This relies on ConvertFloatToIntAndBack not reusing these scratch
  // registers!
  DoubleRegister rounded = kScratchDoubleReg;
  DoubleRegister converted_back = kScratchDoubleReg2;
  if (std::is_same_v<double, src_type>) { // f64
    __ roundsd(rounded, src, kRoundToZero);
  } else { // f32
    __ roundss(rounded, src, kRoundToZero);
  }
  ConvertFloatToIntAndBack<dst_type, src_type>(assm, dst, rounded,
                                               converted_back, pinned);
  if (std::is_same_v<double, src_type>) { // f64
    __ ucomisd(converted_back, rounded);
  } else { // f32
    __ ucomiss(converted_back, rounded);
  }
  // Jump to trap if PF is 0 (one of the operands was NaN) or they are not
  // equal.
  __ j(parity_even, trap);
  __ j(not_equal, trap);
}
References __, v8::internal::CpuFeatures::IsSupported(), v8::internal::wasm::kMissingCPUFeature, v8::internal::kRoundToZero, kScratchDoubleReg, kScratchDoubleReg2, v8::internal::not_equal, and v8::internal::parity_even.
EnsureNoAlias() [1/2]
Register v8::internal::wasm::liftoff::EnsureNoAlias (Assembler * assm, Register reg, LiftoffRegister must_not_alias, UseScratchRegisterScope * temps) [inline]
Definition at line 186 of file liftoff-assembler-riscv32-inl.h.
                                                              {
  if (reg != must_not_alias.low_gp() && reg != must_not_alias.high_gp())
    return reg;
  Register tmp = temps->Acquire();
  DCHECK_NE(must_not_alias.low_gp(), tmp);
  DCHECK_NE(must_not_alias.high_gp(), tmp);
  assm->mv(tmp, reg);
  return tmp;
}
References v8::internal::UseScratchRegisterScope::Acquire(), DCHECK_NE, v8::internal::wasm::LiftoffRegister::high_gp(), v8::internal::wasm::LiftoffRegister::low_gp(), and v8::internal::AssemblerRISCVI::mv().
EnsureNoAlias() [2/2]
Register v8::internal::wasm::liftoff::EnsureNoAlias (Assembler * assm, Register reg, Register must_not_alias, UseScratchRegisterScope * temps) [inline]
Definition at line 227 of file liftoff-assembler-arm-inl.h.
                                                              {
  if (reg != must_not_alias) return reg;
  Register tmp = temps->Acquire();
  DCHECK_NE(reg, tmp);
  assm->mov(tmp, reg);
  return tmp;
}
References v8::internal::UseScratchRegisterScope::Acquire(), DCHECK_NE, and v8::internal::Assembler::mov().
Referenced by v8::internal::wasm::LiftoffAssembler::emit_i64_sari(), v8::internal::wasm::LiftoffAssembler::emit_i64_shli(), and v8::internal::wasm::LiftoffAssembler::emit_i64_shri().
Exchange()
void v8::internal::wasm::liftoff::Exchange (LiftoffAssembler * lasm, Register dst, Register lhs, Register rhs) [inline]
Definition at line 1116 of file liftoff-assembler-arm-inl.h.
                                   {
  __ mov(dst, rhs);
}
References __.
Referenced by v8::internal::wasm::LiftoffAssembler::AtomicExchange(), v8::internal::wasm::LiftoffAssembler::AtomicExchangeTaggedPointer(), and v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
F64x2Compare()
void v8::internal::wasm::liftoff::F64x2Compare (LiftoffAssembler * assm, LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs, Condition cond) [inline]
Definition at line 249 of file liftoff-assembler-arm-inl.h.
                                         {
  DCHECK(cond == eq || cond == ne || cond == lt || cond == le);
  QwNeonRegister dest = liftoff::GetSimd128Register(dst);
  QwNeonRegister left = liftoff::GetSimd128Register(lhs);
  QwNeonRegister right = liftoff::GetSimd128Register(rhs);
  UseScratchRegisterScope temps(assm);
  Register scratch = temps.Acquire();
  assm->mov(scratch, Operand(0));
  assm->VFPCompareAndSetFlags(left.low(), right.low());
  assm->mov(scratch, Operand(-1), LeaveCC, cond);
  if (cond == lt || cond == le) {
    // Check for NaN.
    assm->mov(scratch, Operand(0), LeaveCC, vs);
  }
  assm->vmov(dest.low(), scratch, scratch);
  assm->mov(scratch, Operand(0));
  assm->VFPCompareAndSetFlags(left.high(), right.high());
  assm->mov(scratch, Operand(-1), LeaveCC, cond);
  if (cond == lt || cond == le) {
    // Check for NaN.
    assm->mov(scratch, Operand(0), LeaveCC, vs);
  }
  assm->vmov(dest.high(), scratch, scratch);
}
References v8::internal::UseScratchRegisterScope::Acquire(), v8::internal::DCHECK(), v8::internal::eq, GetSimd128Register(), v8::internal::QwNeonRegister::high(), v8::internal::le, v8::internal::LeaveCC, v8::internal::QwNeonRegister::low(), v8::internal::lt, v8::internal::MacroAssembler::mov(), v8::internal::ne, v8::internal::MacroAssembler::VFPCompareAndSetFlags(), v8::internal::Assembler::vmov(), and v8::internal::vs.
Referenced by v8::internal::wasm::LiftoffAssembler::emit_f64x2_eq(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_le(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_lt(), and v8::internal::wasm::LiftoffAssembler::emit_f64x2_ne().
GeneratePopCnt()
void v8::internal::wasm::liftoff::GeneratePopCnt (Assembler * assm, Register dst, Register src, Register scratch1, Register scratch2) [inline]
Definition at line 1927 of file liftoff-assembler-arm-inl.h.
                                                                 {
  DCHECK(!AreAliased(dst, scratch1, scratch2));
  if (src == scratch1) std::swap(scratch1, scratch2);
  // x = x - ((x & (0x55555555 << 1)) >> 1)
  assm->and_(scratch1, src, Operand(0xaaaaaaaa));
  assm->sub(dst, src, Operand(scratch1, LSR, 1));
  // x = (x & 0x33333333) + ((x & (0x33333333 << 2)) >> 2)
  assm->mov(scratch1, Operand(0x33333333));
  assm->and_(scratch2, dst, Operand(scratch1, LSL, 2));
  assm->and_(scratch1, dst, scratch1);
  assm->add(dst, scratch1, Operand(scratch2, LSR, 2));
  // x = (x + (x >> 4)) & 0x0F0F0F0F
  assm->add(dst, dst, Operand(dst, LSR, 4));
  assm->and_(dst, dst, Operand(0x0f0f0f0f));
  // x = x + (x >> 8)
  assm->add(dst, dst, Operand(dst, LSR, 8));
  // x = x + (x >> 16)
  assm->add(dst, dst, Operand(dst, LSR, 16));
  // x = x & 0x3F
  assm->and_(dst, dst, Operand(0x3f));
}
References v8::internal::Assembler::add(), v8::internal::Assembler::and_(), v8::internal::AreAliased(), v8::internal::DCHECK(), v8::internal::LSL, v8::internal::LSR, v8::internal::Assembler::mov(), and v8::internal::Assembler::sub().
Referenced by v8::internal::wasm::LiftoffAssembler::emit_i32_popcnt(), and v8::internal::wasm::LiftoffAssembler::emit_i64_popcnt().
GetEffectiveAddress()
Register v8::internal::wasm::liftoff::GetEffectiveAddress (LiftoffAssembler * assm, UseScratchRegisterScope * temps, Register addr, Register offset, uintptr_t offset_imm, bool i64_offset = false) [inline]
Definition at line 124 of file liftoff-assembler-arm64-inl.h.
                                                             {
  if (!offset.is_valid() && offset_imm == 0) return addr;
  Register tmp = temps->AcquireX();
  if (offset.is_valid()) {
    assm->Add(tmp, addr, i64_offset ? Operand(offset) : Operand(offset, UXTW));
    addr = tmp;
  }
  if (offset_imm != 0) assm->Add(tmp, addr, offset_imm);
  return tmp;
}
References v8::internal::UseScratchRegisterScope::AcquireX(), v8::internal::MacroAssembler::Add(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::is_valid(), and v8::internal::UXTW.
GetFloatRegister()
FloatRegister v8::internal::wasm::liftoff::GetFloatRegister (DoubleRegister reg) [inline]
Definition at line 191 of file liftoff-assembler-arm-inl.h.
                                                          {
  DCHECK_LT(reg.code(), kDoubleCode_d16);
  return LowDwVfpRegister::from_code(reg.code()).low();
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), DCHECK_LT, v8::internal::RegisterBase< LowDwVfpRegister, kDoubleCode_d16 >::from_code(), and v8::internal::LowDwVfpRegister::low().
Referenced by v8::internal::wasm::LiftoffStackSlots::Construct(), v8::internal::wasm::LiftoffAssembler::emit_f32_abs(), v8::internal::wasm::LiftoffAssembler::emit_f32_add(), v8::internal::wasm::LiftoffAssembler::emit_f32_ceil(), v8::internal::wasm::LiftoffAssembler::emit_f32_div(), v8::internal::wasm::LiftoffAssembler::emit_f32_floor(), v8::internal::wasm::LiftoffAssembler::emit_f32_max(), v8::internal::wasm::LiftoffAssembler::emit_f32_min(), v8::internal::wasm::LiftoffAssembler::emit_f32_mul(), v8::internal::wasm::LiftoffAssembler::emit_f32_nearest_int(), v8::internal::wasm::LiftoffAssembler::emit_f32_neg(), v8::internal::wasm::LiftoffAssembler::emit_f32_set_cond(), v8::internal::wasm::LiftoffAssembler::emit_f32_sqrt(), v8::internal::wasm::LiftoffAssembler::emit_f32_sub(), v8::internal::wasm::LiftoffAssembler::emit_f32_trunc(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_extract_lane(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_replace_lane(), v8::internal::wasm::LiftoffAssembler::emit_store_nonzero_if_nan(), v8::internal::wasm::LiftoffAssembler::emit_type_conversion(), Load(), v8::internal::wasm::LiftoffAssembler::LoadConstant(), LoadInternal(), v8::internal::wasm::LiftoffAssembler::Move(), Store(), and v8::internal::wasm::LiftoffAssembler::Store().
GetHalfStackSlot()
MemOperand v8::internal::wasm::liftoff::GetHalfStackSlot (int offset, RegPairHalf half) [inline]
Definition at line 60 of file liftoff-assembler-arm-inl.h.
                                                                 {
  int32_t half_offset =
      half == kLowWord ? 0 : LiftoffAssembler::kStackSlotSize / 2;
  return MemOperand(offset > 0 ? fp : sp, -offset + half_offset);
}
References v8::internal::wasm::kLowWord, v8::internal::wasm::LiftoffAssembler::kStackSlotSize, and MemOperand().
Referenced by v8::internal::wasm::LiftoffStackSlots::Construct(), v8::internal::wasm::LiftoffAssembler::FillI64Half(), v8::internal::wasm::LiftoffAssembler::FillStackSlotsWithZero(), and v8::internal::wasm::LiftoffAssembler::Spill().
GetInstanceDataOperand()
MemOperand v8::internal::wasm::liftoff::GetInstanceDataOperand () [inline]
Definition at line 66 of file liftoff-assembler-arm-inl.h.
                                           {
  return GetStackSlot(WasmLiftoffFrameConstants::kInstanceDataOffset);
}
References GetStackSlot(), and v8::internal::WasmLiftoffFrameConstants::kInstanceDataOffset.
Referenced by v8::internal::wasm::LiftoffAssembler::LoadInstanceDataFromFrame(), and v8::internal::wasm::LiftoffAssembler::SpillInstanceData().
GetMemOp() [1/7]
template<typename T >
MemOperand v8::internal::wasm::liftoff::GetMemOp (LiftoffAssembler * assm, Register addr, Register offset, T offset_imm, bool i64_offset = false, unsigned shift_amount = 0) [inline]
Definition at line 73 of file liftoff-assembler-loong64-inl.h.
                                                                               {
  if (offset != no_reg) {
    if (!i64_offset) {
      assm->bstrpick_d(kScratchReg, offset, 31, 0);
      offset = kScratchReg;
    }
    if (shift_amount != 0) {
      assm->alsl_d(kScratchReg, offset, addr, shift_amount);
    } else {
      assm->add_d(kScratchReg, offset, addr);
    }
    addr = kScratchReg;
  }
  if (is_int31(offset_imm)) {
    int32_t offset_imm32 = static_cast<int32_t>(offset_imm);
    return MemOperand(addr, offset_imm32);
  } else {
    assm->li(kScratchReg2, Operand(offset_imm));
    assm->add_d(kScratchReg2, addr, kScratchReg2);
    return MemOperand(kScratchReg2, 0);
  }
}
References v8::internal::Assembler::add_d(), v8::internal::Assembler::alsl_d(), v8::internal::Assembler::bstrpick_d(), v8::internal::kScratchReg, v8::internal::kScratchReg2, v8::internal::MacroAssembler::li(), MemOperand(), and v8::internal::no_reg.
GetMemOp() [2/7]
MemOperand v8::internal::wasm::liftoff::GetMemOp (LiftoffAssembler * assm, Register addr, Register offset, uintptr_t offset_imm, bool i64_offset = false, unsigned shift_amount = 0) [inline]
Definition at line 45 of file liftoff-assembler-riscv64-inl.h.
                                                                               {
  if (offset != no_reg) {
    if (!i64_offset) {
      // extract bit[0:31] without sign extend
      assm->ExtractBits(kScratchReg2, offset, 0, 32, false);
      offset = kScratchReg2;
    }
    if (shift_amount != 0) {
      assm->CalcScaledAddress(kScratchReg2, addr, offset, shift_amount);
    } else {
      assm->Add64(kScratchReg2, offset, addr);
    }
    addr = kScratchReg2;
  }
  if (is_int31(offset_imm)) {
    int32_t offset_imm32 = static_cast<int32_t>(offset_imm);
    return MemOperand(addr, offset_imm32);
  } else {
    assm->li(kScratchReg, Operand(offset_imm));
    assm->Add64(kScratchReg2, addr, kScratchReg);
    return MemOperand(kScratchReg2, 0);
  }
}
References v8::internal::MacroAssembler::CalcScaledAddress(), v8::internal::MacroAssembler::ExtractBits(), v8::internal::kScratchReg, v8::internal::kScratchReg2, v8::internal::MacroAssembler::li(), MemOperand(), and v8::internal::no_reg.
GetMemOp() [3/7]
MemOperand v8::internal::wasm::liftoff::GetMemOp (LiftoffAssembler * assm, Register addr, Register offset, uintptr_t offset_imm, Register scratch, bool i64_offset = false, unsigned shift_amount = 0) [inline]
Definition at line 53 of file liftoff-assembler-ppc-inl.h.
                                                      {
  Register kScratchReg2 = scratch;
  DCHECK_NE(addr, kScratchReg2);
  DCHECK_NE(offset, kScratchReg2);
  if (offset != no_reg) {
    if (!i64_offset) {
      // extract least significant 32 bits without sign extend
      assm->ExtractBitRange(kScratchReg2, offset, 31, 0, LeaveRC, false);
      offset = kScratchReg2;
    }
    if (shift_amount != 0) {
      assm->ShiftLeftU64(kScratchReg2, offset, Operand(shift_amount));
    }
    assm->AddS64(kScratchReg2, offset, addr);
    addr = kScratchReg2;
  }
  if (is_int31(offset_imm)) {
    int32_t offset_imm32 = static_cast<int32_t>(offset_imm);
    return MemOperand(addr, offset_imm32);
  } else {
    // Offset immediate does not fit in 31 bits.
    assm->mov(kScratchReg2, Operand(offset_imm));
    assm->AddS64(kScratchReg2, addr, kScratchReg2);
    return MemOperand(kScratchReg2, 0);
  }
}
References v8::internal::MacroAssembler::AddS64(), DCHECK_NE, v8::internal::MacroAssembler::ExtractBitRange(), v8::internal::kScratchReg2, v8::internal::LeaveRC, MemOperand(), v8::internal::MacroAssembler::mov(), v8::internal::no_reg, and v8::internal::MacroAssembler::ShiftLeftU64().
GetMemOp() [4/7]
MemOperand v8::internal::wasm::liftoff::GetMemOp (LiftoffAssembler * assm, Register addr, Register offset, uintptr_t offset_imm, unsigned shift_amount = 0) [inline]
Definition at line 57 of file liftoff-assembler-riscv32-inl.h.
                                                      {
  DCHECK_NE(addr, kScratchReg2);
  DCHECK_NE(offset, kScratchReg2);
  if (is_uint31(offset_imm)) {
    int32_t offset_imm32 = static_cast<int32_t>(offset_imm);
    if (offset == no_reg) return MemOperand(addr, offset_imm32);
    if (shift_amount != 0) {
      assm->CalcScaledAddress(kScratchReg2, addr, offset, shift_amount);
    } else {
      assm->AddWord(kScratchReg2, offset, addr);
    }
    return MemOperand(kScratchReg2, offset_imm32);
  }
  // Offset immediate does not fit in 31 bits.
  assm->li(kScratchReg2, offset_imm);
  assm->AddWord(kScratchReg2, kScratchReg2, addr);
  if (offset != no_reg) {
    if (shift_amount != 0) {
      assm->CalcScaledAddress(kScratchReg2, kScratchReg2, offset, shift_amount);
    } else {
      assm->AddWord(kScratchReg2, kScratchReg2, offset);
    }
  }
  return MemOperand(kScratchReg2, 0);
}
References v8::internal::MacroAssembler::CalcScaledAddress(), DCHECK_NE, v8::internal::kScratchReg2, v8::internal::MacroAssembler::li(), MemOperand(), and v8::internal::no_reg.
GetMemOp() [5/7]
Operand v8::internal::wasm::liftoff::GetMemOp (LiftoffAssembler * assm, Register addr, Register offset_reg, uintptr_t offset_imm, ScaleFactor scale_factor = times_1) [inline]
Definition at line 60 of file liftoff-assembler-x64-inl.h.
                                                            {
  if (is_uint31(offset_imm)) {
    int32_t offset_imm32 = static_cast<int32_t>(offset_imm);
    return offset_reg == no_reg
               ? Operand(addr, offset_imm32)
               : Operand(addr, offset_reg, scale_factor, offset_imm32);
  }
  // Offset immediate does not fit in 31 bits.
  Register scratch = kScratchRegister2;
  assm->MacroAssembler::Move(scratch, offset_imm);
  if (offset_reg != no_reg) assm->addq(scratch, offset_reg);
  return Operand(addr, scratch, scale_factor, 0);
}
References kScratchRegister2, and v8::internal::no_reg.
GetMemOp() [6/7]
MemOperand v8::internal::wasm::liftoff::GetMemOp (LiftoffAssembler * assm, UseScratchRegisterScope * temps, Register addr, Register offset, int32_t offset_imm, unsigned shift_amount = 0) [inline]
Definition at line 70 of file liftoff-assembler-arm-inl.h.
                                                      {
  if (offset != no_reg) {
    if (offset_imm == 0) return MemOperand(addr, offset, LSL, shift_amount);
    Register tmp = temps->Acquire();
    if (shift_amount == 0) {
      assm->add(tmp, offset, Operand(offset_imm));
    } else {
      assm->lsl(tmp, offset, Operand(shift_amount));
      assm->add(tmp, tmp, Operand(offset_imm));
    }
    return MemOperand(addr, tmp);
  }
  return MemOperand(addr, offset_imm);
}
References v8::internal::UseScratchRegisterScope::Acquire(), v8::internal::Assembler::add(), v8::internal::Assembler::lsl(), v8::internal::LSL, MemOperand(), and v8::internal::no_reg.
Referenced by AtomicBinop(), v8::internal::wasm::LiftoffAssembler::LoadFullPointer(), LoadInternal(), and v8::internal::wasm::LiftoffAssembler::Store().
GetMemOp() [7/7]
template<typename T >
MemOperand v8::internal::wasm::liftoff::GetMemOp (LiftoffAssembler * assm, UseScratchRegisterScope * temps, Register addr, Register offset, T offset_imm, bool i64_offset = false, unsigned shift_amount = 0) [inline]
Definition at line 105 of file liftoff-assembler-arm64-inl.h.
                                                                               {
  if (!offset.is_valid()) return MemOperand(addr.X(), offset_imm);
  Register effective_addr = addr.X();
  if (offset_imm) {
    effective_addr = temps->AcquireX();
    assm->Add(effective_addr, addr.X(), offset_imm);
  }
  return i64_offset
             ? MemOperand(effective_addr, offset.X(), LSL, shift_amount)
             : MemOperand(effective_addr, offset.W(), UXTW, shift_amount);
}
References v8::internal::UseScratchRegisterScope::AcquireX(), v8::internal::MacroAssembler::Add(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::is_valid(), v8::internal::LSL, MemOperand(), v8::internal::UXTW, v8::internal::CPURegister::W(), and v8::internal::CPURegister::X().
GetRegFromType()
CPURegister v8::internal::wasm::liftoff::GetRegFromType (const LiftoffRegister & reg, ValueKind kind) [inline]
Definition at line 55 of file liftoff-assembler-arm64-inl.h.
                                                                              {
  switch (kind) {
    case kI32:
      return reg.gp().W();
    case kI64:
    case kRef:
    case kRefNull:
      return reg.gp().X();
    case kF32:
      return reg.fp().S();
    case kF64:
      return reg.fp().D();
    case kS128:
      return reg.fp().Q();
    default:
      UNREACHABLE();
  }
}
References v8::internal::wasm::LiftoffRegister::fp(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::kF32, v8::internal::kF64, v8::internal::kI32, v8::internal::kI64, v8::internal::kRef, v8::internal::kRefNull, v8::internal::kS128, v8::internal::UNREACHABLE(), v8::internal::CPURegister::W(), and v8::internal::CPURegister::X().
Referenced by LoadToRegister().
GetSimd128Register() [1/2]
Simd128Register v8::internal::wasm::liftoff::GetSimd128Register (DoubleRegister reg) [inline]
Definition at line 196 of file liftoff-assembler-arm-inl.h.
                                                              {
  return QwNeonRegister::from_code(reg.code() / 2);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), and v8::internal::RegisterBase< QwNeonRegister, kSimd128AfterLast >::from_code().
Referenced by v8::internal::wasm::LiftoffStackSlots::Construct(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_abs(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_add(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_ceil(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_eq(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_extract_lane(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_floor(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_le(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_lt(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_max(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_min(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_mul(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_ne(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_nearest_int(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_neg(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_pmax(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_pmin(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_qfma(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_qfms(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_relaxed_max(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_relaxed_min(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_replace_lane(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_sconvert_i32x4(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_splat(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_sub(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_trunc(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_uconvert_i32x4(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_convert_low_i32x4_s(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_convert_low_i32x4_u(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_extract_lane(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_max(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_min(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_pmax(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_pmin(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_promote_low_f32x4(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_qfma(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_qfms(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_replace_lane(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_abs(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_add(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_add_sat_s(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_add_sat_u(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_bitmask(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_dot_i8x16_i7x16_s(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_eq(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_extadd_pairwise_i8x16_s(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_extadd_pairwise_i8x16_u(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_extmul_high_i8x16_s(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_extmul_high_i8x16_u(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_extmul_low_i8x16_s(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_extmul_low_i8x16_u(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_extract_lane_s(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_extract_lane_u(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_ge_s(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_ge_u(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_gt_s(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_gt_u(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_max_s(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_max_u(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_min_s(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_min_u(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_mul(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_ne(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_neg(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_q15mulr_sat_s(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_relaxed_q15mulr_s(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_replace_lane(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_rounding_average_u(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_sconvert_i8x16_high(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_sconvert_i8x16_low(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_shli(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_splat(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_sub(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_sub_sat_s(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_sub_sat_u(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_uconvert_i8x16_high(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_uconvert_i8x16_low(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_abs(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_add(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_bitmask(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_dot_i16x8_s(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_dot_i8x16_i7x16_add_s(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_eq(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_extadd_pairwise_i16x8_s(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_extadd_pairwise_i16x8_u(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_extmul_high_i16x8_s(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_extmul_high_i16x8_u(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_extmul_low_i16x8_s(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_extmul_low_i16x8_u(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_extract_lane(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_ge_s(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_ge_u(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_gt_s(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_gt_u(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_max_s(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_max_u(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_min_s(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_min_u(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_mul(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_ne(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_neg(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_relaxed_trunc_f32x4_s(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_relaxed_trunc_f32x4_u(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_replace_lane(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_sconvert_f32x4(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_sconvert_i16x8_high(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_sconvert_i16x8_low(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_shli(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_splat(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_sub(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_uconvert_f32x4(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_uconvert_i16x8_high(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_uconvert_i16x8_low(), v8::internal::wasm::LiftoffAssembler::emit_i64x2_abs(), v8::internal::wasm::LiftoffAssembler::emit_i64x2_add(), v8::internal::wasm::LiftoffAssembler::emit_i64x2_alltrue(), v8::internal::wasm::LiftoffAssembler::emit_i64x2_bitmask(), v8::internal::wasm::LiftoffAssembler::emit_i64x2_eq(), v8::internal::wasm::LiftoffAssembler::emit_i64x2_extmul_high_i32x4_s(), v8::internal::wasm::LiftoffAssembler::emit_i64x2_extmul_high_i32x4_u(), v8::internal::wasm::LiftoffAssembler::emit_i64x2_extmul_low_i32x4_s(), v8::internal::wasm::LiftoffAssembler::emit_i64x2_extmul_low_i32x4_u(), v8::internal::wasm::LiftoffAssembler::emit_i64x2_extract_lane(), v8::internal::wasm::LiftoffAssembler::emit_i64x2_ge_s(), v8::internal::wasm::LiftoffAssembler::emit_i64x2_gt_s(), v8::internal::wasm::LiftoffAssembler::emit_i64x2_mul(), v8::internal::wasm::LiftoffAssembler::emit_i64x2_ne(), v8::internal::wasm::LiftoffAssembler::emit_i64x2_neg(), v8::internal::wasm::LiftoffAssembler::emit_i64x2_replace_lane(), v8::internal::wasm::LiftoffAssembler::emit_i64x2_sconvert_i32x4_high(), v8::internal::wasm::LiftoffAssembler::emit_i64x2_sconvert_i32x4_low(), v8::internal::wasm::LiftoffAssembler::emit_i64x2_shli(), v8::internal::wasm::LiftoffAssembler::emit_i64x2_splat(), v8::internal::wasm::LiftoffAssembler::emit_i64x2_sub(), v8::internal::wasm::LiftoffAssembler::emit_i64x2_uconvert_i32x4_high(), v8::internal::wasm::LiftoffAssembler::emit_i64x2_uconvert_i32x4_low(), v8::internal::wasm::LiftoffAssembler::emit_i8x16_abs(), v8::internal::wasm::LiftoffAssembler::emit_i8x16_add(), v8::internal::wasm::LiftoffAssembler::emit_i8x16_add_sat_s(), v8::internal::wasm::LiftoffAssembler::emit_i8x16_add_sat_u(), v8::internal::wasm::LiftoffAssembler::emit_i8x16_bitmask(), v8::internal::wasm::LiftoffAssembler::emit_i8x16_eq(), v8::internal::wasm::LiftoffAssembler::emit_i8x16_extract_lane_s(), v8::internal::wasm::LiftoffAssembler::emit_i8x16_extract_lane_u(), v8::internal::wasm::LiftoffAssembler::emit_i8x16_ge_s(), v8::internal::wasm::LiftoffAssembler::emit_i8x16_ge_u(), v8::internal::wasm::LiftoffAssembler::emit_i8x16_gt_s(), v8::internal::wasm::LiftoffAssembler::emit_i8x16_gt_u(), v8::internal::wasm::LiftoffAssembler::emit_i8x16_max_s(), v8::internal::wasm::LiftoffAssembler::emit_i8x16_max_u(), v8::internal::wasm::LiftoffAssembler::emit_i8x16_min_s(), v8::internal::wasm::LiftoffAssembler::emit_i8x16_min_u(), v8::internal::wasm::LiftoffAssembler::emit_i8x16_ne(), v8::internal::wasm::LiftoffAssembler::emit_i8x16_neg(), v8::internal::wasm::LiftoffAssembler::emit_i8x16_popcnt(), v8::internal::wasm::LiftoffAssembler::emit_i8x16_replace_lane(), v8::internal::wasm::LiftoffAssembler::emit_i8x16_rounding_average_u(), v8::internal::wasm::LiftoffAssembler::emit_i8x16_shli(), v8::internal::wasm::LiftoffAssembler::emit_i8x16_shuffle(), v8::internal::wasm::LiftoffAssembler::emit_i8x16_splat(), v8::internal::wasm::LiftoffAssembler::emit_i8x16_sub(), v8::internal::wasm::LiftoffAssembler::emit_i8x16_sub_sat_s(), v8::internal::wasm::LiftoffAssembler::emit_i8x16_sub_sat_u(), v8::internal::wasm::LiftoffAssembler::emit_i8x16_swizzle(), v8::internal::wasm::LiftoffAssembler::emit_s128_and(), v8::internal::wasm::LiftoffAssembler::emit_s128_and_not(), v8::internal::wasm::LiftoffAssembler::emit_s128_not(), v8::internal::wasm::LiftoffAssembler::emit_s128_or(), v8::internal::wasm::LiftoffAssembler::emit_s128_select(), v8::internal::wasm::LiftoffAssembler::emit_s128_store_nonzero_if_nan(), v8::internal::wasm::LiftoffAssembler::emit_s128_xor(), EmitSimdShift(), EmitSimdShiftImmediate(), F64x2Compare(), GetSimd128Register(), v8::internal::wasm::LiftoffAssembler::LoadLane(), v8::internal::wasm::LiftoffAssembler::LoadTransform(), v8::internal::wasm::LiftoffAssembler::Move(), and S128NarrowOp().
GetSimd128Register() [2/2]
Simd128Register v8::internal::wasm::liftoff::GetSimd128Register (LiftoffRegister reg) [inline]
Definition at line 200 of file liftoff-assembler-arm-inl.h.
                                                               {
  return liftoff::GetSimd128Register(reg.low_fp());
}
References GetSimd128Register(), and v8::internal::wasm::LiftoffRegister::low_fp().
GetStackSlot() [1/2]
constexpr Operand v8::internal::wasm::liftoff::GetStackSlot (int offset) [inline], [constexpr]
Definition at line 58 of file liftoff-assembler-arm-inl.h.
{ return MemOperand(fp, -offset); }
References MemOperand().
Referenced by v8::internal::wasm::LiftoffAssembler::CallC(), v8::internal::wasm::LiftoffAssembler::CallCWithStackBuffer(), v8::internal::wasm::LiftoffStackSlots::Construct(), v8::internal::wasm::LiftoffAssembler::Fill(), GetInstanceDataOperand(), LoadToRegister(), v8::internal::wasm::LiftoffAssembler::MoveStackValue(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::Process(), v8::internal::wasm::LiftoffAssembler::Spill(), and StoreToMemory().
GetStackSlot() [2/2]
MemOperand v8::internal::wasm::liftoff::GetStackSlot (uint32_t offset) [inline]
Definition at line 83 of file liftoff-assembler-ppc-inl.h.
                                                {
  return MemOperand(fp, -static_cast<int32_t>(offset));
}
References MemOperand().
GetTmpByteRegister()
Register v8::internal::wasm::liftoff::GetTmpByteRegister (LiftoffAssembler * assm, Register candidate) [inline]
Definition at line 161 of file liftoff-assembler-ia32-inl.h.
                                                                               {
  if (candidate.is_byte_register()) return candidate;
  // {GetUnusedRegister()} may insert move instructions to spill registers to
  // the stack. This is OK because {mov} does not change the status flags.
  return assm->GetUnusedRegister(liftoff::kByteRegs).gp();
}
References v8::internal::wasm::LiftoffAssembler::GetUnusedRegister(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::Register::is_byte_register(), and kByteRegs.
Referenced by EmitFloatSetCond(), and setcc_32().
I32x4ExtMulHelper()
void v8::internal::wasm::liftoff::I32x4ExtMulHelper (LiftoffAssembler * assm, XMMRegister dst, XMMRegister src1, XMMRegister src2, bool low, bool is_signed) [inline]
Definition at line 4042 of file liftoff-assembler-ia32-inl.h.
                                              {
  // I32x4ExtMul requires dst == src1 if AVX is not supported.
  if (CpuFeatures::IsSupported(AVX) || dst == src1) {
    assm->I32x4ExtMul(dst, src1, src2, liftoff::kScratchDoubleReg, low,
                      is_signed);
  } else if (dst != src2) {
    // dst != src1 && dst != src2
    assm->movaps(dst, src1);
    assm->I32x4ExtMul(dst, dst, src2, liftoff::kScratchDoubleReg, low,
                      is_signed);
  } else {
    // dst == src2
    // Extended multiplication is commutative,
    assm->movaps(dst, src2);
    assm->I32x4ExtMul(dst, dst, src1, liftoff::kScratchDoubleReg, low,
                      is_signed);
  }
}
References v8::internal::SharedMacroAssemblerBase::I32x4ExtMul(), v8::internal::is_signed(), v8::internal::CpuFeatures::IsSupported(), kScratchDoubleReg, and v8::internal::Assembler::movaps().
I64Binop()
template<void(Assembler::*)(Register, Register, Register, SBit, Condition) op, void(Assembler::*)(Register, Register, const Operand &, SBit, Condition) op_with_carry>
void v8::internal::wasm::liftoff::I64Binop (LiftoffAssembler * assm, LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 133 of file liftoff-assembler-arm-inl.h.
                                                               {
  Register dst_low = dst.low_gp();
  if (dst_low == lhs.high_gp() || dst_low == rhs.high_gp()) {
    dst_low =
        assm->GetUnusedRegister(kGpReg, LiftoffRegList{lhs, rhs, dst.high_gp()})
            .gp();
  }
  (assm->*op)(dst_low, lhs.low_gp(), rhs.low_gp(), SetCC, al);
  (assm->*op_with_carry)(dst.high_gp(), lhs.high_gp(), Operand(rhs.high_gp()),
                         LeaveCC, al);
  if (dst_low != dst.low_gp()) assm->mov(dst.low_gp(), dst_low);
}
References v8::internal::al, v8::internal::wasm::LiftoffAssembler::GetUnusedRegister(), v8::internal::wasm::LiftoffRegister::high_gp(), v8::internal::wasm::kGpReg, v8::internal::LeaveCC, v8::internal::wasm::LiftoffRegister::low_gp(), v8::internal::MacroAssembler::mov(), and v8::internal::SetCC.
I64BinopI()
template<void(Assembler::*)(Register, Register, const Operand &, SBit, Condition) op, void(Assembler::*)(Register, Register, const Operand &, SBit, Condition) op_with_carry>
void v8::internal::wasm::liftoff::I64BinopI (LiftoffAssembler * assm, LiftoffRegister dst, LiftoffRegister lhs, int64_t imm) [inline]
Definition at line 151 of file liftoff-assembler-arm-inl.h.
                                                        {
  // The compiler allocated registers such that either {dst == lhs} or there is
  // no overlap between the two.
  DCHECK_NE(dst.low_gp(), lhs.high_gp());
  int32_t imm_low_word = static_cast<int32_t>(imm);
  int32_t imm_high_word = static_cast<int32_t>(imm >> 32);
  (assm->*op)(dst.low_gp(), lhs.low_gp(), Operand(imm_low_word), SetCC, al);
  (assm->*op_with_carry)(dst.high_gp(), lhs.high_gp(), Operand(imm_high_word),
                         LeaveCC, al);
}
References v8::internal::al, DCHECK_NE, v8::internal::wasm::LiftoffRegister::high_gp(), v8::internal::LeaveCC, v8::internal::wasm::LiftoffRegister::low_gp(), and v8::internal::SetCC.
I64Shiftop()
template<void(MacroAssembler::*)(Register, Register, Register, Register, Register) op, bool is_left_shift>
void v8::internal::wasm::liftoff::I64Shiftop (LiftoffAssembler * assm, LiftoffRegister dst, LiftoffRegister src, Register amount) [inline]
Definition at line 166 of file liftoff-assembler-arm-inl.h.
                                                             {
  Register src_low = src.low_gp();
  Register src_high = src.high_gp();
  Register dst_low = dst.low_gp();
  Register dst_high = dst.high_gp();
  // Left shift writes {dst_high} then {dst_low}, right shifts write {dst_low}
  // then {dst_high}.
  Register clobbered_dst_reg = is_left_shift ? dst_high : dst_low;
  LiftoffRegList pinned{clobbered_dst_reg, src};
  Register amount_capped =
      pinned.set(assm->GetUnusedRegister(kGpReg, pinned)).gp();
  assm->and_(amount_capped, amount, Operand(0x3F));
  // Ensure that writing the first half of {dst} does not overwrite the still
  // needed half of {src}.
  Register* later_src_reg = is_left_shift ? &src_low : &src_high;
  if (*later_src_reg == clobbered_dst_reg) {
    *later_src_reg = assm->GetUnusedRegister(kGpReg, pinned).gp();
    assm->MacroAssembler::Move(*later_src_reg, clobbered_dst_reg);
  }
  (assm->*op)(dst_low, dst_high, src_low, src_high, amount_capped);
}
References v8::internal::Assembler::and_(), v8::internal::wasm::LiftoffAssembler::GetUnusedRegister(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::wasm::LiftoffRegister::high_gp(), v8::internal::wasm::kGpReg, and v8::internal::wasm::LiftoffRegister::low_gp().
I64Store()
void v8::internal::wasm::liftoff::I64Store (LiftoffAssembler * lasm, LiftoffRegister dst, LiftoffRegister , LiftoffRegister src) [inline]
Definition at line 1247 of file liftoff-assembler-arm-inl.h.
                                                           {
  __ mov(dst.low_gp(), src.low_gp());
  __ mov(dst.high_gp(), src.high_gp());
}
References __, v8::internal::wasm::LiftoffRegister::high_gp(), and v8::internal::wasm::LiftoffRegister::low_gp().
Referenced by v8::internal::wasm::LiftoffAssembler::AtomicExchange(), and v8::internal::wasm::LiftoffAssembler::AtomicStore().
IsRegInRegPair()
bool v8::internal::wasm::liftoff::IsRegInRegPair (LiftoffRegister pair, Register reg) [inline]
Definition at line 1515 of file liftoff-assembler-riscv32-inl.h.
                                                               {
  DCHECK(pair.is_gp_pair());
  return pair.low_gp() == reg || pair.high_gp() == reg;
}
References v8::internal::DCHECK(), v8::internal::wasm::LiftoffRegister::high_gp(), v8::internal::wasm::LiftoffRegister::is_gp_pair(), and v8::internal::wasm::LiftoffRegister::low_gp().
Referenced by Emit64BitShiftOperation().
Load() [1/2]
void v8::internal::wasm::liftoff::Load (LiftoffAssembler * assm, LiftoffRegister dst, MemOperand src, ValueKind kind) [inline]
Definition at line 321 of file liftoff-assembler-arm-inl.h.
                                 {
  switch (kind) {
    case kI16:
      assm->ldrh(dst.gp(), src);
      break;
    case kI32:
    case kRefNull:
    case kRef:
      assm->ldr(dst.gp(), src);
      break;
    case kI64:
      assm->ldr(dst.low_gp(), MemOperand(src.rn(), src.offset()));
      assm->ldr(
          dst.high_gp(),
          MemOperand(src.rn(), src.offset() + liftoff::kHalfStackSlotSize));
      break;
    case kF32:
      assm->vldr(liftoff::GetFloatRegister(dst.fp()), src);
      break;
    case kF64:
      assm->vldr(dst.fp(), src);
      break;
    case kS128: {
      // Get memory address of slot to fill from.
      UseScratchRegisterScope temps(assm);
      Register addr = liftoff::CalculateActualAddress(assm, &temps, src.rn(),
                                                      no_reg, src.offset());
      assm->vld1(Neon8, NeonListOperand(dst.low_fp(), 2), NeonMemOperand(addr));
      break;
    }
    default:
      UNREACHABLE();
  }
}
References CalculateActualAddress(), v8::internal::wasm::LiftoffRegister::fp(), GetFloatRegister(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::wasm::LiftoffRegister::high_gp(), v8::internal::kF32, v8::internal::kF64, kHalfStackSlotSize, v8::internal::kI16, v8::internal::kI32, v8::internal::kI64, v8::internal::kRef, v8::internal::kRefNull, v8::internal::kS128, v8::internal::Assembler::ldr(), v8::internal::Assembler::ldrh(), v8::internal::wasm::LiftoffRegister::low_fp(), v8::internal::wasm::LiftoffRegister::low_gp(), v8::internal::Neon8, v8::internal::no_reg, v8::internal::MemOperand::offset(), v8::internal::MemOperand::rn(), v8::internal::UNREACHABLE(), v8::internal::Assembler::vld1(), and v8::internal::Assembler::vldr().
Referenced by v8::internal::wasm::LiftoffAssembler::CallCWithStackBuffer(), v8::internal::wasm::LiftoffAssembler::Fill(), v8::internal::wasm::LiftoffAssembler::LoadCallerFrameSlot(), and v8::internal::wasm::LiftoffAssembler::LoadReturnStackSlot().
Load() [2/2]
void v8::internal::wasm::liftoff::Load (LiftoffAssembler * assm, LiftoffRegister dst, Register base, int32_t offset, ValueKind kind) [inline]
Definition at line 50 of file liftoff-assembler-ia32-inl.h.
                                                 {
  Operand src(base, offset);
  switch (kind) {
    case kI16:
      assm->mov_w(dst.gp(), src);
      break;
    case kI32:
    case kRefNull:
    case kRef:
      assm->mov(dst.gp(), src);
      break;
    case kI64:
      assm->mov(dst.low_gp(), src);
      assm->mov(dst.high_gp(), Operand(base, offset + 4));
      break;
    case kF32:
      assm->movss(dst.fp(), src);
      break;
    case kF64:
      assm->movsd(dst.fp(), src);
      break;
    case kS128:
      assm->movdqu(dst.fp(), src);
      break;
    case kVoid:
    case kTop:
    case kBottom:
    case kI8:
    case kF16:
      UNREACHABLE();
  }
}
References v8::internal::wasm::LiftoffRegister::fp(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::wasm::LiftoffRegister::high_gp(), v8::internal::kF32, v8::internal::kF64, v8::internal::kI16, v8::internal::kI32, v8::internal::kI64, v8::internal::kI8, v8::internal::kRef, v8::internal::kRefNull, v8::internal::kS128, v8::internal::wasm::LiftoffRegister::low_gp(), v8::internal::MacroAssembler::mov(), v8::internal::Assembler::mov_w(), v8::internal::Assembler::movdqu(), v8::internal::Assembler::movsd(), v8::internal::Assembler::movss(), and v8::internal::UNREACHABLE().
LoadFromStack()
void v8::internal::wasm::liftoff::LoadFromStack (LiftoffAssembler * assm, LiftoffRegister dst, Operand src, ValueKind kind) [inline]
Definition at line 76 of file liftoff-assembler-x64-inl.h.
                                                       {
  switch (kind) {
    case kI16:
      assm->movw(dst.gp(), src);
      break;
    case kI32:
      assm->movl(dst.gp(), src);
      break;
    case kI64:
    case kRefNull:
    case kRef:
      // Stack slots are uncompressed even when heap pointers are compressed.
      assm->movq(dst.gp(), src);
      break;
    case kF32:
      assm->Movss(dst.fp(), src);
      break;
    case kF64:
      assm->Movsd(dst.fp(), src);
      break;
    case kS128:
      assm->Movdqu(dst.fp(), src);
      break;
    default:
      UNREACHABLE();
  }
}
References v8::internal::wasm::LiftoffRegister::fp(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::kF32, v8::internal::kF64, v8::internal::kI16, v8::internal::kI32, v8::internal::kI64, v8::internal::kRef, v8::internal::kRefNull, v8::internal::kS128, v8::internal::Assembler::movl(), v8::internal::Assembler::movq(), v8::internal::Assembler::movw(), and v8::internal::UNREACHABLE().
LoadInternal()
void v8::internal::wasm::liftoff::LoadInternal (LiftoffAssembler * lasm, LiftoffRegister dst, Register src_addr, Register offset_reg, int32_t offset_imm, LoadType type, uint32_t * protected_load_pc = nullptr, bool needs_shift = false) [inline]
Definition at line 793 of file liftoff-assembler-arm-inl.h.
                                                   {
  unsigned shift_amount = needs_shift ? type.size_log_2() : 0;
  DCHECK_IMPLIES(type.value_type() == kWasmI64, dst.is_gp_pair());
  UseScratchRegisterScope temps(lasm);
  if (type.value() == LoadType::kF64Load ||
      type.value() == LoadType::kF32Load ||
      type.value() == LoadType::kS128Load) {
    // Remove the DCHECK and implement scaled offsets for these types if needed.
    // For now this path is never used.
    DCHECK(!needs_shift);
    Register actual_src_addr = liftoff::CalculateActualAddress(
        lasm, &temps, src_addr, offset_reg, offset_imm);
    if (type.value() == LoadType::kF64Load) {
      // Armv6 is not supported so Neon can be used to avoid alignment issues.
      CpuFeatureScope scope(lasm, NEON);
      __ vld1(Neon64, NeonListOperand(dst.fp()),
              NeonMemOperand(actual_src_addr));
    } else if (type.value() == LoadType::kF32Load) {
      // TODO(arm): Use vld1 for f32 when implemented in simulator as used for
      // f64. It supports unaligned access.
      Register scratch =
          (actual_src_addr == src_addr) ? temps.Acquire() : actual_src_addr;
      __ ldr(scratch, MemOperand(actual_src_addr));
      __ vmov(liftoff::GetFloatRegister(dst.fp()), scratch);
    } else {
      // Armv6 is not supported so Neon can be used to avoid alignment issues.
      CpuFeatureScope scope(lasm, NEON);
      __ vld1(Neon8, NeonListOperand(dst.low_fp(), 2),
              NeonMemOperand(actual_src_addr));
    }
  } else {
    MemOperand src_op = liftoff::GetMemOp(lasm, &temps, src_addr, offset_reg,
                                          offset_imm, shift_amount);
    if (protected_load_pc) *protected_load_pc = __ pc_offset();
    switch (type.value()) {
      case LoadType::kI32Load8U:
        __ ldrb(dst.gp(), src_op);
        break;
      case LoadType::kI64Load8U:
        __ ldrb(dst.low_gp(), src_op);
        __ mov(dst.high_gp(), Operand(0));
        break;
      case LoadType::kI32Load8S:
        __ ldrsb(dst.gp(), src_op);
        break;
      case LoadType::kI64Load8S:
        __ ldrsb(dst.low_gp(), src_op);
        __ asr(dst.high_gp(), dst.low_gp(), Operand(31));
        break;
      case LoadType::kI32Load16U:
        __ ldrh(dst.gp(), src_op);
        break;
      case LoadType::kI64Load16U:
        __ ldrh(dst.low_gp(), src_op);
        __ mov(dst.high_gp(), Operand(0));
        break;
      case LoadType::kI32Load16S:
        __ ldrsh(dst.gp(), src_op);
        break;
      case LoadType::kI32Load:
        __ ldr(dst.gp(), src_op);
        break;
      case LoadType::kI64Load16S:
        __ ldrsh(dst.low_gp(), src_op);
        __ asr(dst.high_gp(), dst.low_gp(), Operand(31));
        break;
      case LoadType::kI64Load32U:
        __ ldr(dst.low_gp(), src_op);
        __ mov(dst.high_gp(), Operand(0));
        break;
      case LoadType::kI64Load32S:
        __ ldr(dst.low_gp(), src_op);
        __ asr(dst.high_gp(), dst.low_gp(), Operand(31));
        break;
      case LoadType::kI64Load:
        __ ldr(dst.low_gp(), src_op);
        // GetMemOp may use a scratch register as the offset register, in which
        // case, calling GetMemOp again will fail due to the assembler having
        // ran out of scratch registers.
        if (temps.CanAcquire()) {
          src_op = liftoff::GetMemOp(lasm, &temps, src_addr, offset_reg,
                                     offset_imm + kSystemPointerSize);
        } else {
          __ add(src_op.rm(), src_op.rm(), Operand(kSystemPointerSize));
        }
        __ ldr(dst.high_gp(), src_op);
        break;
      default:
        UNREACHABLE();
    }
  }
}
References __, v8::internal::UseScratchRegisterScope::Acquire(), CalculateActualAddress(), v8::internal::UseScratchRegisterScope::CanAcquire(), v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::wasm::LiftoffRegister::fp(), GetFloatRegister(), GetMemOp(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::wasm::LiftoffRegister::high_gp(), v8::internal::wasm::LiftoffRegister::is_gp_pair(), v8::internal::kSystemPointerSize, v8::internal::wasm::kWasmI64, v8::internal::wasm::LiftoffRegister::low_fp(), v8::internal::wasm::LiftoffRegister::low_gp(), MemOperand(), v8::internal::Neon64, v8::internal::Neon8, v8::internal::MemOperand::rm(), v8::internal::tracing::type, and v8::internal::UNREACHABLE().
Referenced by v8::internal::wasm::LiftoffAssembler::Load(), and v8::internal::wasm::LiftoffAssembler::LoadTaggedPointer().
LoadToRegister()
CPURegister v8::internal::wasm::liftoff::LoadToRegister (LiftoffAssembler * assm, UseScratchRegisterScope * temps, const LiftoffAssembler::VarState & src) [inline]
Definition at line 209 of file liftoff-assembler-arm64-inl.h.
                                                                       {
  if (src.is_reg()) {
    return GetRegFromType(src.reg(), src.kind());
  }
  if (src.is_const()) {
    if (src.kind() == kI32) {
      if (src.i32_const() == 0) return wzr;
      Register temp = temps->AcquireW();
      assm->Mov(temp, src.i32_const());
      return temp;
    }
    DCHECK_EQ(kI64, src.kind());
    if (src.i32_const() == 0) return xzr;
    Register temp = temps->AcquireX();
    assm->Mov(temp, static_cast<int64_t>(src.i32_const()));
    return temp;
  }
  DCHECK(src.is_stack());
  CPURegister temp = AcquireByType(temps, src.kind());
  assm->Ldr(temp, GetStackSlot(src.offset()));
  return temp;
}
References AcquireByType(), v8::internal::UseScratchRegisterScope::AcquireW(), v8::internal::UseScratchRegisterScope::AcquireX(), v8::internal::DCHECK(), DCHECK_EQ, GetRegFromType(), GetStackSlot(), v8::internal::wasm::LiftoffVarState::i32_const(), v8::internal::wasm::LiftoffVarState::is_const(), v8::internal::wasm::LiftoffVarState::is_reg(), v8::internal::wasm::LiftoffVarState::is_stack(), v8::internal::kI32, v8::internal::kI64, v8::internal::wasm::LiftoffVarState::kind(), v8::internal::MacroAssembler::Ldr(), v8::internal::MacroAssembler::Mov(), v8::internal::wasm::LiftoffVarState::offset(), and v8::internal::wasm::LiftoffVarState::reg().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayNew(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallIndirectImpl(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::PopIndexToVarState(), StoreToMemory(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringCompare(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringEncodeWtf16(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringEncodeWtf16Array(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringEncodeWtf8(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringEncodeWtf8Array(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringHash(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringNewWtf16Array(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringNewWtf8Array(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringViewIterAdvance(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringViewIterRewind(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringViewIterSlice(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringViewWtf16Encode(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringViewWtf8Advance(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringViewWtf8Encode(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringViewWtf8Slice().
MakeUnsigned()
Condition v8::internal::wasm::liftoff::MakeUnsigned (Condition cond) [inline]
Definition at line 108 of file liftoff-assembler-arm-inl.h.
                                              {
  switch (cond) {
    case kLessThan:
      return kUnsignedLessThan;
    case kLessThanEqual:
      return kUnsignedLessThanEqual;
    case kGreaterThan:
      return kUnsignedGreaterThan;
    case kGreaterThanEqual:
      return kUnsignedGreaterThanEqual;
    case kEqual:
    case kNotEqual:
    case kUnsignedLessThan:
    case kUnsignedLessThanEqual:
    case kUnsignedGreaterThan:
    case kUnsignedGreaterThanEqual:
      return cond;
    default:
      UNREACHABLE();
  }
}
References v8::internal::kEqual, v8::internal::kGreaterThan, v8::internal::kGreaterThanEqual, v8::internal::kLessThan, v8::internal::kLessThanEqual, v8::internal::kNotEqual, v8::internal::kUnsignedGreaterThan, v8::internal::kUnsignedGreaterThanEqual, v8::internal::kUnsignedLessThan, v8::internal::kUnsignedLessThanEqual, and v8::internal::UNREACHABLE().
Referenced by v8::internal::wasm::LiftoffAssembler::emit_i64_set_cond().
MaskFromNeonDataType()
constexpr int v8::internal::wasm::liftoff::MaskFromNeonDataType (NeonDataType dt) [constexpr]
Definition at line 357 of file liftoff-assembler-arm-inl.h.
                                                    {
  switch (dt) {
    case NeonS8:
    case NeonU8:
      return 7;
    case NeonS16:
    case NeonU16:
      return 15;
    case NeonS32:
    case NeonU32:
      return 31;
    case NeonS64:
    case NeonU64:
      return 63;
    default:
      UNREACHABLE();
      return 0;
  }
}
References v8::internal::NeonS16, v8::internal::NeonS32, v8::internal::NeonS64, v8::internal::NeonS8, v8::internal::NeonU16, v8::internal::NeonU32, v8::internal::NeonU64, v8::internal::NeonU8, and v8::internal::UNREACHABLE().
Referenced by EmitSimdShift(), and EmitSimdShiftImmediate().
MemOperand()
Operand v8::internal::wasm::liftoff::MemOperand (Register base, Register offset_reg, int offset_imm) [inline]
Definition at line 42 of file liftoff-assembler-ia32-inl.h.
                                                                              {
  return offset_reg == no_reg ? Operand(base, offset_imm)
                              : Operand(base, offset_reg, times_1, offset_imm);
}
References v8::internal::no_reg, and v8::internal::times_1.
Referenced by AtomicAddOrSubOrExchange32(), AtomicBinop32(), AtomicBinop64(), GetHalfStackSlot(), GetMemOp(), GetStackSlot(), and LoadInternal().
MoveStackValue()
void v8::internal::wasm::liftoff::MoveStackValue (LiftoffAssembler * assm, const Operand & src, const Operand & dst) [inline]
Definition at line 168 of file liftoff-assembler-ia32-inl.h.
                                               {
  if (assm->cache_state()->has_unused_register(kGpReg)) {
    Register tmp = assm->cache_state()->unused_register(kGpReg).gp();
    assm->mov(tmp, src);
    assm->mov(dst, tmp);
  } else {
    // No free register, move via the stack.
    assm->push(src);
    assm->pop(dst);
  }
}
References v8::internal::wasm::LiftoffAssembler::cache_state(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::wasm::LiftoffAssembler::CacheState::has_unused_register(), v8::internal::wasm::kGpReg, v8::internal::MacroAssembler::mov(), v8::internal::MacroAssembler::pop(), v8::internal::MacroAssembler::push(), and v8::internal::wasm::LiftoffAssembler::CacheState::unused_register().
OpWithCarry()
template<void(Assembler::*)(Register, Register) op, void(Assembler::*)(Register, Register) op_with_carry>
void v8::internal::wasm::liftoff::OpWithCarry (LiftoffAssembler * assm, LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 1778 of file liftoff-assembler-ia32-inl.h.
                                                                  {
  // First, compute the low half of the result, potentially into a temporary dst
  // register if {dst.low_gp()} equals {rhs.low_gp()} or any register we need to
  // keep alive for computing the upper half.
  LiftoffRegList keep_alive{lhs.high_gp(), rhs};
  Register dst_low = keep_alive.has(dst.low_gp())
                         ? assm->GetUnusedRegister(kGpReg, keep_alive).gp()
                         : dst.low_gp();
  if (dst_low != lhs.low_gp()) assm->mov(dst_low, lhs.low_gp());
  (assm->*op)(dst_low, rhs.low_gp());
  // Now compute the upper half, while keeping alive the previous result.
  keep_alive = LiftoffRegList{dst_low, rhs.high_gp()};
  Register dst_high = keep_alive.has(dst.high_gp())
                          ? assm->GetUnusedRegister(kGpReg, keep_alive).gp()
                          : dst.high_gp();
  if (dst_high != lhs.high_gp()) assm->mov(dst_high, lhs.high_gp());
  (assm->*op_with_carry)(dst_high, rhs.high_gp());
  // If necessary, move result into the right registers.
  LiftoffRegister tmp_result = LiftoffRegister::ForPair(dst_low, dst_high);
  if (tmp_result != dst) assm->Move(dst, tmp_result, kI64);
}
References v8::internal::wasm::LiftoffRegister::ForPair(), v8::internal::wasm::LiftoffAssembler::GetUnusedRegister(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::wasm::LiftoffRegister::high_gp(), v8::internal::wasm::kGpReg, v8::internal::kI64, v8::internal::wasm::LiftoffRegister::low_gp(), v8::internal::MacroAssembler::mov(), and v8::internal::wasm::LiftoffAssembler::Move().
OpWithCarryI()
template<void(Assembler::*)(Register, const Immediate &) op, void(Assembler::*)(Register, int32_t) op_with_carry>
void v8::internal::wasm::liftoff::OpWithCarryI (LiftoffAssembler * assm, LiftoffRegister dst, LiftoffRegister lhs, int64_t imm) [inline]
Definition at line 1807 of file liftoff-assembler-ia32-inl.h.
                                                           {
  // The compiler allocated registers such that either {dst == lhs} or there is
  // no overlap between the two.
  DCHECK_NE(dst.low_gp(), lhs.high_gp());
  int32_t imm_low_word = static_cast<int32_t>(imm);
  int32_t imm_high_word = static_cast<int32_t>(imm >> 32);
  // First, compute the low half of the result.
  if (dst.low_gp() != lhs.low_gp()) assm->mov(dst.low_gp(), lhs.low_gp());
  (assm->*op)(dst.low_gp(), Immediate(imm_low_word));
  // Now compute the upper half.
  if (dst.high_gp() != lhs.high_gp()) assm->mov(dst.high_gp(), lhs.high_gp());
  (assm->*op_with_carry)(dst.high_gp(), imm_high_word);
}
References DCHECK_NE, v8::internal::wasm::LiftoffRegister::high_gp(), v8::internal::wasm::LiftoffRegister::low_gp(), and v8::internal::MacroAssembler::mov().
Or()
void v8::internal::wasm::liftoff::Or (LiftoffAssembler * lasm, Register dst, Register lhs, Register rhs) [inline]
Definition at line 1106 of file liftoff-assembler-arm-inl.h.
                             {
  __ orr(dst, lhs, rhs);
}
References __.
Referenced by v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::wasm::LiftoffAssembler::AtomicOr(), v8::internal::RegExpMacroAssemblerRISCV::CheckNotBackReferenceIgnoreCase(), and v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
PadRegList()
CPURegList v8::internal::wasm::liftoff::PadRegList (RegList list) [inline]
Definition at line 74 of file liftoff-assembler-arm64-inl.h.
                                           {
  if ((list.Count() & 1) != 0) list.set(padreg);
  return CPURegList(kXRegSizeInBits, list);
}
References v8::internal::RegListBase< RegisterT >::Count(), v8::internal::kXRegSizeInBits, v8::internal::padreg, and v8::internal::RegListBase< RegisterT >::set().
PadVRegList()
CPURegList v8::internal::wasm::liftoff::PadVRegList (DoubleRegList list) [inline]
Definition at line 79 of file liftoff-assembler-arm64-inl.h.
                                                  {
  if ((list.Count() & 1) != 0) list.set(fp_scratch);
  return CPURegList(kQRegSizeInBits, list);
}
References v8::internal::RegListBase< RegisterT >::Count(), v8::internal::kQRegSizeInBits, and v8::internal::RegListBase< RegisterT >::set().
PairContains()
bool v8::internal::wasm::liftoff::PairContains (LiftoffRegister pair, Register reg) [inline]
Definition at line 1906 of file liftoff-assembler-ia32-inl.h.
                                                             {
  return pair.low_gp() == reg || pair.high_gp() == reg;
}
References v8::internal::wasm::LiftoffRegister::high_gp(), and v8::internal::wasm::LiftoffRegister::low_gp().
Referenced by Emit64BitShiftOperation().
push() [1/2]
void v8::internal::wasm::liftoff::push (LiftoffAssembler * assm, LiftoffRegister reg, ValueKind kind) [inline]
Definition at line 157 of file liftoff-assembler-loong64-inl.h.
                                                                              {
  switch (kind) {
    case kI32:
      assm->addi_d(sp, sp, -kSystemPointerSize);
      assm->St_w(reg.gp(), MemOperand(sp, 0));
      break;
    case kI64:
    case kRefNull:
    case kRef:
      assm->Push(reg.gp());
      break;
    case kF32:
      assm->addi_d(sp, sp, -kSystemPointerSize);
      assm->Fst_s(reg.fp(), MemOperand(sp, 0));
      break;
    case kF64:
      assm->addi_d(sp, sp, -kSystemPointerSize);
      assm->Fst_d(reg.fp(), MemOperand(sp, 0));
      break;
    case kS128:
      UNREACHABLE();
      break;
    default:
      UNREACHABLE();
  }
}
References v8::internal::Assembler::addi_d(), v8::internal::wasm::LiftoffRegister::fp(), v8::internal::MacroAssembler::Fst_d(), v8::internal::MacroAssembler::Fst_s(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::kF32, v8::internal::kF64, v8::internal::kI32, v8::internal::kI64, v8::internal::kRef, v8::internal::kRefNull, v8::internal::kS128, v8::internal::kSystemPointerSize, v8::internal::MacroAssembler::Push(), v8::internal::MacroAssembler::St_w(), and v8::internal::UNREACHABLE().
push() [2/2]
void v8::internal::wasm::liftoff::push (LiftoffAssembler * assm, LiftoffRegister reg, ValueKind kind, int padding = 0) [inline]
Definition at line 118 of file liftoff-assembler-ia32-inl.h.
                                  {
  switch (kind) {
    case kI32:
    case kRef:
    case kRefNull:
      assm->AllocateStackSpace(padding);
      assm->push(reg.gp());
      break;
    case kI64:
      assm->AllocateStackSpace(padding);
      assm->push(reg.high_gp());
      assm->push(reg.low_gp());
      break;
    case kF32:
      assm->AllocateStackSpace(sizeof(float) + padding);
      assm->movss(Operand(esp, 0), reg.fp());
      break;
    case kF64:
      assm->AllocateStackSpace(sizeof(double) + padding);
      assm->movsd(Operand(esp, 0), reg.fp());
      break;
    case kS128:
      assm->AllocateStackSpace(sizeof(double) * 2 + padding);
      assm->movdqu(Operand(esp, 0), reg.fp());
      break;
    case kVoid:
    case kTop:
    case kBottom:
    case kI8:
    case kI16:
    case kF16:
      UNREACHABLE();
  }
}
References v8::internal::MacroAssembler::AllocateStackSpace(), v8::internal::wasm::LiftoffRegister::fp(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::wasm::LiftoffRegister::high_gp(), v8::internal::kF32, v8::internal::kF64, v8::internal::kI16, v8::internal::kI32, v8::internal::kI64, v8::internal::kI8, v8::internal::kRef, v8::internal::kRefNull, v8::internal::kS128, v8::internal::wasm::LiftoffRegister::low_gp(), v8::internal::Assembler::movdqu(), v8::internal::Assembler::movsd(), v8::internal::Assembler::movss(), v8::internal::MacroAssembler::push(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), AtomicBinop32(), AtomicBinop64(), v8::internal::Builtins::Generate_CallOrConstructVarargs(), v8::internal::Builtins::Generate_ConstructForwardAllArgsImpl(), v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_DeoptimizationEntry(), v8::internal::Builtins::Generate_InterpreterPushArgsThenConstructImpl(), v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_JSEntryVariant(), v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_PushArguments(), v8::internal::RegExpMacroAssemblerRISCV::GetCode(), v8::internal::compiler::CodeGenerator::Push(), v8::internal::MacroAssembler::Push(), v8::internal::MacroAssembler::PushAll(), v8::internal::MacroAssembler::PushReturnAddressFrom(), and v8::internal::RegExpMacroAssemblerRISCV::SafeCallTarget().
ReplaceInPair()
LiftoffRegister v8::internal::wasm::liftoff::ReplaceInPair (LiftoffRegister pair, Register old_reg, Register new_reg) [inline]
Definition at line 1910 of file liftoff-assembler-ia32-inl.h.
                                                       {
  if (pair.low_gp() == old_reg) {
    return LiftoffRegister::ForPair(new_reg, pair.high_gp());
  }
  if (pair.high_gp() == old_reg) {
    return LiftoffRegister::ForPair(pair.low_gp(), new_reg);
  }
  return pair;
}
References v8::internal::wasm::LiftoffRegister::ForPair(), v8::internal::wasm::LiftoffRegister::high_gp(), and v8::internal::wasm::LiftoffRegister::low_gp().
Referenced by Emit64BitShiftOperation().
S128NarrowOp()
void v8::internal::wasm::liftoff::S128NarrowOp (LiftoffAssembler * assm, NeonDataType dt, NeonDataType sdt, LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 237 of file liftoff-assembler-arm-inl.h.
                                                                   {
  if (dst == lhs) {
    assm->vqmovn(dt, sdt, dst.low_fp(), liftoff::GetSimd128Register(lhs));
    assm->vqmovn(dt, sdt, dst.high_fp(), liftoff::GetSimd128Register(rhs));
  } else {
    assm->vqmovn(dt, sdt, dst.high_fp(), liftoff::GetSimd128Register(rhs));
    assm->vqmovn(dt, sdt, dst.low_fp(), liftoff::GetSimd128Register(lhs));
  }
}
References GetSimd128Register(), v8::internal::wasm::LiftoffRegister::high_fp(), v8::internal::wasm::LiftoffRegister::low_fp(), and v8::internal::Assembler::vqmovn().
Referenced by v8::internal::wasm::LiftoffAssembler::emit_i16x8_sconvert_i32x4(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_uconvert_i32x4(), v8::internal::wasm::LiftoffAssembler::emit_i8x16_sconvert_i16x8(), and v8::internal::wasm::LiftoffAssembler::emit_i8x16_uconvert_i16x8().
setcc_32()
void v8::internal::wasm::liftoff::setcc_32 (LiftoffAssembler * assm, Condition cond, Register dst) [inline]
Definition at line 2737 of file liftoff-assembler-ia32-inl.h.
                                                                           {
  Register tmp_byte_reg = GetTmpByteRegister(assm, dst);
  setcc_32_no_spill(assm, cond, dst, tmp_byte_reg);
}
References GetTmpByteRegister(), and setcc_32_no_spill().
setcc_32_no_spill()
void v8::internal::wasm::liftoff::setcc_32_no_spill (LiftoffAssembler * assm, Condition cond, Register dst, Register tmp_byte_reg) [inline]
Definition at line 2730 of file liftoff-assembler-ia32-inl.h.
                                                                   {
  assm->setcc(cond, tmp_byte_reg);
  assm->movzx_b(dst, tmp_byte_reg);
}
References v8::internal::Assembler::movzx_b(), and v8::internal::Assembler::setcc().
Referenced by EmitFloatSetCond(), and setcc_32().
SignExtendI32ToI64()
void v8::internal::wasm::liftoff::SignExtendI32ToI64 (Assembler * assm, LiftoffRegister reg) [inline]
Definition at line 154 of file liftoff-assembler-ia32-inl.h.
                                                                     {
  assm->mov(reg.high_gp(), reg.low_gp());
  assm->sar(reg.high_gp(), 31);
}
References v8::internal::wasm::LiftoffRegister::high_gp(), v8::internal::wasm::LiftoffRegister::low_gp(), v8::internal::Assembler::mov(), and v8::internal::Assembler::sar().
Store() [1/3]
void v8::internal::wasm::liftoff::Store (LiftoffAssembler * assm, LiftoffRegister src, MemOperand dst, ValueKind kind) [inline]
Definition at line 279 of file liftoff-assembler-arm-inl.h.
                                  {
#ifdef DEBUG
  // The {str} instruction needs a temp register when the immediate in the
  // provided MemOperand does not fit into 12 bits. This happens for large stack
  // frames. This DCHECK checks that the temp register is available when needed.
  DCHECK(UseScratchRegisterScope{assm}.CanAcquire());
#endif
  switch (kind) {
    case kI16:
      assm->strh(src.gp(), dst);
      break;
    case kI32:
    case kRefNull:
    case kRef:
      assm->str(src.gp(), dst);
      break;
    case kI64:
      // Positive offsets should be lowered to kI32.
      assm->str(src.low_gp(), MemOperand(dst.rn(), dst.offset()));
      assm->str(
          src.high_gp(),
          MemOperand(dst.rn(), dst.offset() + liftoff::kHalfStackSlotSize));
      break;
    case kF32:
      assm->vstr(liftoff::GetFloatRegister(src.fp()), dst);
      break;
    case kF64:
      assm->vstr(src.fp(), dst);
      break;
    case kS128: {
      UseScratchRegisterScope temps(assm);
      Register addr = liftoff::CalculateActualAddress(assm, &temps, dst.rn(),
                                                      no_reg, dst.offset());
      assm->vst1(Neon8, NeonListOperand(src.low_fp(), 2), NeonMemOperand(addr));
      break;
    }
    default:
      UNREACHABLE();
  }
}
References CalculateActualAddress(), v8::internal::DCHECK(), v8::internal::wasm::LiftoffRegister::fp(), GetFloatRegister(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::wasm::LiftoffRegister::high_gp(), v8::internal::kF32, v8::internal::kF64, kHalfStackSlotSize, v8::internal::kI16, v8::internal::kI32, v8::internal::kI64, v8::internal::kRef, v8::internal::kRefNull, v8::internal::kS128, v8::internal::wasm::LiftoffRegister::low_fp(), v8::internal::wasm::LiftoffRegister::low_gp(), v8::internal::Neon8, v8::internal::no_reg, v8::internal::MemOperand::offset(), v8::internal::MemOperand::rn(), v8::internal::Assembler::str(), v8::internal::Assembler::strh(), v8::internal::UNREACHABLE(), v8::internal::Assembler::vst1(), and v8::internal::Assembler::vstr().
Referenced by v8::internal::StringBuiltinsReducer< Next >::AllocateSeqOneByteString(), v8::internal::StringBuiltinsReducer< Next >::AllocateSeqTwoByteString(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ArraySet(), v8::internal::wasm::TurboshaftGraphBuildingInterface::AsmjsStoreMem(), v8::internal::wasm::TurboshaftGraphBuildingInterface::AtomicOp(), v8::internal::compiler::fast_api_call::FastApiCallBuilder::Build(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCapiCallWrapper(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildCcallConvertFloatSat(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildCCallForFloatConversion(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildDiv64Call(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildIntToFloatConversionInstruction(), v8::internal::wasm::WasmGraphBuilderBase::BuildModifyThreadInWasmFlagHelper(), v8::internal::compiler::WasmGraphBuilder::BuildSafeStore(), v8::internal::wasm::WasmGraphBuilderBase::BuildSetNewStackLimit(), v8::internal::wasm::WasmGraphBuilderBase::BuildSwitchBackFromCentralStack(), v8::internal::wasm::WasmGraphBuilderBase::BuildSwitchToTheCentralStack(), v8::internal::compiler::turboshaft::WasmInJSInliningReducer< Next >::Call(), v8::internal::wasm::LiftoffAssembler::CallC(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallCStackSlotToInt32(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallCStackSlotToStackSlot(), v8::internal::wasm::LiftoffAssembler::CallCWithStackBuffer(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CheckMaxSteps(), v8::internal::StringBuiltinsReducer< Next >::CopyStringCharacters(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::DataDrop(), v8::internal::wasm::TurboshaftGraphBuildingInterface::DataDrop(), v8::internal::wasm::TurboshaftGraphBuildingInterface::DoReturn(), v8::internal::compiler::turboshaft::TurbolevEarlyLoweringReducer< Next >::GeneratorStore(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GlobalSet(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Initialize(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineMemCopy(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::LowerGlobalSetOrGet(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::MemoryLowering::ReduceAllocateRaw(), v8::internal::compiler::MemoryLowering::ReduceStore(), v8::internal::compiler::MemoryLowering::ReduceStoreElement(), v8::internal::compiler::MemoryLowering::ReduceStoreField(), v8::internal::wasm::WasmWrapperTSGraphBuilder::SafeStore(), v8::internal::wasm::TurboshaftGraphBuildingInterface::SetDataViewOpForErrorMessage(), v8::internal::wasm::LiftoffAssembler::Spill(), v8::internal::compiler::RawMachineAssembler::Store(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Store(), v8::internal::anonymous_namespace{code-stub-assembler.cc}::MetaTableAccessor::Store(), v8::internal::wasm::LiftoffAssembler::StoreCallerFrameSlot(), v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::StoreCounterValue(), v8::internal::compiler::turboshaft::DataViewLoweringReducer< Next >::StoreDataViewElement(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StoreElement(), v8::internal::FeedbackCollectorReducer< Next >::StoreFeedbackVectorSlot(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StoreFieldImpl(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StoreFixedArrayElement(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StoreFixedDoubleArrayElement(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StoreInStackSlot(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StoreMem(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StoreMem(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StoreObjectField(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StoreOffHeap(), v8::internal::compiler::RawMachineAssembler::StoreToPointer(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::StructSet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::TraceMemoryOperation(), v8::internal::wasm::TurboshaftGraphBuildingInterface::TraceMemoryOperation(), v8::internal::compiler::Typer::Visitor::TypeNode(), v8::internal::compiler::RawMachineAssembler::UnalignedStore(), v8::internal::compiler::turboshaft::TurbolevEarlyLoweringReducer< Next >::UpdateJSArrayLength(), v8::internal::compiler::SimplifiedLoweringVerifier::VisitNode(), v8::internal::wasm::TurboshaftGraphBuildingInterface::WellKnown_FastApi(), and v8::internal::compiler::fast_api_call::FastApiCallBuilder::WrapFastCall().
Store() [2/3]
void v8::internal::wasm::liftoff::Store (LiftoffAssembler * assm, MemOperand dst, LiftoffRegister src, ValueKind kind) [inline]
Definition at line 126 of file liftoff-assembler-loong64-inl.h.
                                  {
  switch (kind) {
    case kI16:
      assm->St_h(src.gp(), dst);
      break;
    case kI32:
      assm->St_w(src.gp(), dst);
      break;
    case kI64:
    case kRefNull:
    case kRef:
      assm->St_d(src.gp(), dst);
      break;
    case kF32:
      assm->Fst_s(src.fp(), dst);
      break;
    case kF64:
      assm->Fst_d(src.fp(), dst);
      break;
    default:
      UNREACHABLE();
  }
}
References v8::internal::wasm::LiftoffRegister::fp(), v8::internal::MacroAssembler::Fst_d(), v8::internal::MacroAssembler::Fst_s(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::kF32, v8::internal::kF64, v8::internal::kI16, v8::internal::kI32, v8::internal::kI64, v8::internal::kRef, v8::internal::kRefNull, v8::internal::MacroAssembler::St_d(), v8::internal::MacroAssembler::St_h(), v8::internal::MacroAssembler::St_w(), and v8::internal::UNREACHABLE().
Store() [3/3]
void v8::internal::wasm::liftoff::Store (LiftoffAssembler * assm, Register base, int32_t offset, LiftoffRegister src, ValueKind kind) [inline]
Definition at line 84 of file liftoff-assembler-ia32-inl.h.
                                                       {
  Operand dst(base, offset);
  switch (kind) {
    case kI16:
      assm->mov_w(dst, src.gp());
      break;
    case kI32:
    case kRefNull:
    case kRef:
      assm->mov(dst, src.gp());
      break;
    case kI64:
      assm->mov(dst, src.low_gp());
      assm->mov(Operand(base, offset + 4), src.high_gp());
      break;
    case kF32:
      assm->movss(dst, src.fp());
      break;
    case kF64:
      assm->movsd(dst, src.fp());
      break;
    case kS128:
      assm->movdqu(dst, src.fp());
      break;
    case kVoid:
    case kTop:
    case kBottom:
    case kI8:
    case kF16:
      UNREACHABLE();
  }
}
References v8::internal::wasm::LiftoffRegister::fp(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::wasm::LiftoffRegister::high_gp(), v8::internal::kF32, v8::internal::kF64, v8::internal::kI16, v8::internal::kI32, v8::internal::kI64, v8::internal::kI8, v8::internal::kRef, v8::internal::kRefNull, v8::internal::kS128, v8::internal::wasm::LiftoffRegister::low_gp(), v8::internal::MacroAssembler::mov(), v8::internal::Assembler::mov_w(), v8::internal::Assembler::movdqu(), v8::internal::Assembler::movsd(), v8::internal::Assembler::movss(), and v8::internal::UNREACHABLE().
StoreToMemory() [1/5]
void v8::internal::wasm::liftoff::StoreToMemory (LiftoffAssembler * assm, MemOperand dst, const LiftoffAssembler::VarState & src) [inline]
Definition at line 234 of file liftoff-assembler-arm64-inl.h.
                                                               {
  if (src.kind() == kI16) {
    DCHECK(src.is_reg());
    assm->Strh(src.reg().gp(), dst);
    return;
  }
  UseScratchRegisterScope temps{assm};
  CPURegister src_reg = LoadToRegister(assm, &temps, src);
  assm->Str(src_reg, dst);
}
References v8::internal::DCHECK(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::wasm::LiftoffVarState::is_reg(), v8::internal::kI16, v8::internal::wasm::LiftoffVarState::kind(), LoadToRegister(), and v8::internal::wasm::LiftoffVarState::reg().
Referenced by StoreToMemory().
StoreToMemory() [2/5]
void v8::internal::wasm::liftoff::StoreToMemory (LiftoffAssembler * assm, MemOperand dst, const LiftoffAssembler::VarState & src, Register scratch) [inline]
Definition at line 54 of file liftoff-assembler-s390-inl.h.
                                            {
  if (src.is_reg()) {
    switch (src.kind()) {
      case kI16:
        assm->StoreU16(src.reg().gp(), dst);
        break;
      case kI32:
        assm->StoreU32(src.reg().gp(), dst);
        break;
      case kI64:
        assm->StoreU64(src.reg().gp(), dst);
        break;
      case kF32:
        assm->StoreF32(src.reg().fp(), dst);
        break;
      case kF64:
        assm->StoreF64(src.reg().fp(), dst);
        break;
      case kS128:
        assm->StoreV128(src.reg().fp(), dst, scratch);
        break;
      default:
        UNREACHABLE();
    }
  } else if (src.is_const()) {
    if (src.kind() == kI32) {
      assm->mov(scratch, Operand(src.i32_const()));
      assm->StoreU32(scratch, dst);
    } else {
      assm->mov(scratch, Operand(static_cast<int64_t>(src.i32_const())));
      assm->StoreU64(scratch, dst);
    }
  } else if (value_kind_size(src.kind()) == 4) {
    assm->LoadU32(scratch, liftoff::GetStackSlot(src.offset()), scratch);
    assm->StoreU32(scratch, dst);
  } else {
    DCHECK_EQ(8, value_kind_size(src.kind()));
    assm->LoadU64(scratch, liftoff::GetStackSlot(src.offset()), scratch);
    assm->StoreU64(scratch, dst);
  }
}
References DCHECK_EQ, v8::internal::wasm::LiftoffRegister::fp(), GetStackSlot(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::wasm::LiftoffVarState::i32_const(), v8::internal::wasm::LiftoffVarState::is_const(), v8::internal::wasm::LiftoffVarState::is_reg(), v8::internal::kF32, v8::internal::kF64, v8::internal::kI16, v8::internal::kI32, v8::internal::kI64, v8::internal::wasm::LiftoffVarState::kind(), v8::internal::kS128, v8::internal::MacroAssembler::LoadU32(), v8::internal::MacroAssembler::LoadU64(), v8::internal::MacroAssembler::mov(), v8::internal::wasm::LiftoffVarState::offset(), v8::internal::wasm::LiftoffVarState::reg(), v8::internal::MacroAssembler::StoreF32(), v8::internal::MacroAssembler::StoreF64(), v8::internal::MacroAssembler::StoreU16(), v8::internal::MacroAssembler::StoreU32(), v8::internal::MacroAssembler::StoreU64(), v8::internal::MacroAssembler::StoreV128(), v8::internal::UNREACHABLE(), and v8::internal::wasm::value_kind_size().
StoreToMemory() [3/5]
void v8::internal::wasm::liftoff::StoreToMemory (LiftoffAssembler * assm, MemOperand dst, const LiftoffAssembler::VarState & src, Register scratch1, Register scratch2) [inline]
Definition at line 91 of file liftoff-assembler-ppc-inl.h.
                                                                {
  if (src.is_reg()) {
    switch (src.kind()) {
      case kI16:
        assm->StoreU16(src.reg().gp(), dst, scratch1);
        break;
      case kI32:
        assm->StoreU32(src.reg().gp(), dst, scratch1);
        break;
      case kI64:
        assm->StoreU64(src.reg().gp(), dst, scratch1);
        break;
      case kF32:
        assm->StoreF32(src.reg().fp(), dst, scratch1);
        break;
      case kF64:
        assm->StoreF64(src.reg().fp(), dst, scratch1);
        break;
      case kS128:
        assm->StoreSimd128(src.reg().fp().toSimd(), dst, scratch1);
        break;
      default:
        UNREACHABLE();
    }
  } else if (src.is_const()) {
    if (src.kind() == kI32) {
      assm->mov(scratch2, Operand(src.i32_const()));
      assm->StoreU32(scratch2, dst, scratch1);
    } else {
      assm->mov(scratch2, Operand(static_cast<int64_t>(src.i32_const())));
      assm->StoreU64(scratch2, dst, scratch1);
    }
  } else if (value_kind_size(src.kind()) == 4) {
    assm->LoadU32(scratch2, liftoff::GetStackSlot(src.offset()), scratch1);
    assm->StoreU32(scratch2, dst, scratch1);
  } else {
    DCHECK_EQ(8, value_kind_size(src.kind()));
    assm->LoadU64(scratch2, liftoff::GetStackSlot(src.offset()), scratch1);
    assm->StoreU64(scratch2, dst, scratch1);
  }
}
References DCHECK_EQ, v8::internal::wasm::LiftoffRegister::fp(), GetStackSlot(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::wasm::LiftoffVarState::i32_const(), v8::internal::wasm::LiftoffVarState::is_const(), v8::internal::wasm::LiftoffVarState::is_reg(), v8::internal::kF32, v8::internal::kF64, v8::internal::kI16, v8::internal::kI32, v8::internal::kI64, v8::internal::wasm::LiftoffVarState::kind(), v8::internal::kS128, v8::internal::MacroAssembler::LoadU32(), v8::internal::MacroAssembler::LoadU64(), v8::internal::MacroAssembler::mov(), v8::internal::wasm::LiftoffVarState::offset(), v8::internal::wasm::LiftoffVarState::reg(), v8::internal::MacroAssembler::StoreF32(), v8::internal::MacroAssembler::StoreF64(), v8::internal::MacroAssembler::StoreSimd128(), v8::internal::MacroAssembler::StoreU16(), v8::internal::MacroAssembler::StoreU32(), v8::internal::MacroAssembler::StoreU64(), v8::internal::DoubleRegister::toSimd(), v8::internal::UNREACHABLE(), and v8::internal::wasm::value_kind_size().
StoreToMemory() [4/5]
void v8::internal::wasm::liftoff::StoreToMemory (LiftoffAssembler * assm, Operand dst, const LiftoffAssembler::VarState & src) [inline]
Definition at line 134 of file liftoff-assembler-x64-inl.h.
                                                               {
  if (src.is_reg()) {
    liftoff::StoreToMemory(assm, dst, src.reg(), src.kind());
  } else if (src.is_const()) {
    if (src.kind() == kI32) {
      assm->movl(dst, Immediate(src.i32_const()));
    } else {
      assm->MacroAssembler::Move(dst, static_cast<int64_t>(src.i32_const()));
    }
  } else if (value_kind_size(src.kind()) == 4) {
    DCHECK(src.is_stack());
    assm->movl(kScratchRegister, liftoff::GetStackSlot(src.offset()));
    assm->movl(dst, kScratchRegister);
  } else {
    DCHECK(src.is_stack());
    DCHECK_EQ(8, value_kind_size(src.kind()));
    assm->movq(kScratchRegister, liftoff::GetStackSlot(src.offset()));
    assm->movq(dst, kScratchRegister);
  }
}
References v8::internal::DCHECK(), DCHECK_EQ, GetStackSlot(), v8::internal::wasm::LiftoffVarState::i32_const(), v8::internal::wasm::LiftoffVarState::is_const(), v8::internal::wasm::LiftoffVarState::is_reg(), v8::internal::wasm::LiftoffVarState::is_stack(), v8::internal::kI32, v8::internal::wasm::LiftoffVarState::kind(), v8::internal::kScratchRegister, v8::internal::Assembler::movl(), v8::internal::Assembler::movq(), v8::internal::wasm::LiftoffVarState::offset(), v8::internal::wasm::LiftoffVarState::reg(), StoreToMemory(), and v8::internal::wasm::value_kind_size().
StoreToMemory() [5/5]
void v8::internal::wasm::liftoff::StoreToMemory (LiftoffAssembler * assm, Operand dst, LiftoffRegister src, ValueKind kind) [inline]
Definition at line 105 of file liftoff-assembler-x64-inl.h.
                                                               {
  switch (kind) {
    case kI16:
      assm->movw(dst, src.gp());
      break;
    case kI32:
      assm->movl(dst, src.gp());
      break;
    case kI64:
    case kRefNull:
    case kRef:
      // Stack slots are uncompressed even when heap pointers are compressed.
      assm->movq(dst, src.gp());
      break;
    case kF32:
      assm->Movss(dst, src.fp());
      break;
    case kF64:
      assm->Movsd(dst, src.fp());
      break;
    case kS128:
      assm->Movdqu(dst, src.fp());
      break;
    default:
      UNREACHABLE();
  }
}
References v8::internal::wasm::LiftoffRegister::fp(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::kF32, v8::internal::kF64, v8::internal::kI16, v8::internal::kI32, v8::internal::kI64, v8::internal::kRef, v8::internal::kRefNull, v8::internal::kS128, v8::internal::Assembler::movl(), v8::internal::Assembler::movq(), v8::internal::Assembler::movw(), and v8::internal::UNREACHABLE().
Sub()
void v8::internal::wasm::liftoff::Sub (LiftoffAssembler * lasm, Register dst, Register lhs, Register rhs) [inline]
Definition at line 1096 of file liftoff-assembler-arm-inl.h.
                              {
  __ sub(dst, lhs, rhs);
}
References __.
Referenced by v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::wasm::LiftoffAssembler::AtomicSub(), v8::internal::compiler::turboshaft::anonymous_namespace{loop-unrolling-reducer.cc}::Next(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::anonymous_namespace{runtime-regexp.cc}::RegExpMatchGlobalAtom_OneCharPattern(), v8::internal::wasm::TurboshaftGraphBuildingInterface::SimdOp(), v8::internal::maglev::anonymous_namespace{maglev-assembler-arm64.cc}::SubSizeAndTagObject(), and v8::internal::compiler::turboshaft::Typer::TypeFloatBinop().
Xor()
void v8::internal::wasm::liftoff::Xor (LiftoffAssembler * lasm, Register dst, Register lhs, Register rhs) [inline]
Definition at line 1111 of file liftoff-assembler-arm-inl.h.
                              {
  __ eor(dst, lhs, rhs);
}
References __.
Referenced by v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::wasm::LiftoffAssembler::AtomicXor(), v8::internal::RegExpMacroAssemblerRISCV::CheckSpecialClassRanges(), v8::internal::MacroAssembler::NegateBool(), and v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
Variable Documentation
kByteRegs
constexpr LiftoffRegList v8::internal::wasm::liftoff::kByteRegs [static], [constexpr]
Initial value:
=
    LiftoffRegList::FromBits<RegList{eax, ecx, edx}.bits()>()
Definition at line 47 of file liftoff-assembler-ia32-inl.h.
Referenced by AtomicAddOrSubOrExchange32(), and GetTmpByteRegister().
kHalfStackSlotSize
constexpr int v8::internal::wasm::liftoff::kHalfStackSlotSize = LiftoffAssembler::kStackSlotSize >> 1 [constexpr]
Definition at line 56 of file liftoff-assembler-arm-inl.h.
Referenced by Load(), and Store().
kHighWordOffset
constexpr int32_t v8::internal::wasm::liftoff::kHighWordOffset = 4 [constexpr]
Definition at line 48 of file liftoff-assembler-riscv32-inl.h.
kInstanceDataOperand
constexpr Operand v8::internal::wasm::liftoff::kInstanceDataOperand [constexpr]
Initial value:
=
    GetStackSlot(WasmLiftoffFrameConstants::kInstanceDataOffset)
Definition at line 53 of file liftoff-assembler-x64-inl.h.
kLowWordOffset
constexpr int32_t v8::internal::wasm::liftoff::kLowWordOffset = 0 [constexpr]
Definition at line 47 of file liftoff-assembler-riscv32-inl.h.
kOSRTargetSlot
constexpr Operand v8::internal::wasm::liftoff::kOSRTargetSlot = GetStackSlot(kOSRTargetOffset) [constexpr]
Definition at line 56 of file liftoff-assembler-x64-inl.h.
kPatchInstructionsRequired
constexpr int32_t v8::internal::wasm::liftoff::kPatchInstructionsRequired = 3 [constexpr]
Definition at line 55 of file liftoff-assembler-arm-inl.h.
Referenced by v8::internal::wasm::LiftoffAssembler::PatchPrepareStackFrame(), and v8::internal::wasm::LiftoffAssembler::PrepareStackFrame().
kScratchDoubleReg
constexpr DoubleRegister v8::internal::wasm::liftoff::kScratchDoubleReg = xmm7 [constexpr]
Definition at line 215 of file liftoff-assembler-ia32-inl.h.
Referenced by EmitAllTrue(), EmitSimdNonCommutativeBinOp(), EmitSimdShiftOp(), EmitTruncateFloatToInt(), and I32x4ExtMulHelper().
kScratchDoubleReg2
constexpr DoubleRegister v8::internal::wasm::liftoff::kScratchDoubleReg2 = xmm0 [constexpr]
Definition at line 216 of file liftoff-assembler-ia32-inl.h.
Referenced by EmitTruncateFloatToInt().
kScratchRegister2
constexpr Register v8::internal::wasm::liftoff::kScratchRegister2 = r11 [constexpr]
Definition at line 35 of file liftoff-assembler-x64-inl.h.
Referenced by GetMemOp().
kSubSpSize
constexpr int v8::internal::wasm::liftoff::kSubSpSize = 6 [constexpr]
Definition at line 220 of file liftoff-assembler-ia32-inl.h.