v8::internal::anonymous_namespace{read-only-promotion.cc} Namespace Reference
Classes
class Committee
class ReadOnlyPromotionImpl
Typedefs
using HeapObjectSet = std::unordered_set< Tagged< HeapObject >, Object::Hasher, Object::KeyEqualSafe >
using HeapObjectMap = std::unordered_map< Tagged< HeapObject >, Tagged< HeapObject >, Object::Hasher, Object::KeyEqualSafe >
using HeapObjectList = std::vector< Tagged< HeapObject > >
Enumerations
enum class PromoRecommendation { kReject
, kPromote
, kMatchHost
 }
Functions
bool Contains (const HeapObjectSet &s, Tagged< HeapObject > o)
bool Contains (const HeapObjectMap &s, Tagged< HeapObject > o)
Typedef Documentation
HeapObjectList
using v8::internal::anonymous_namespace{read-only-promotion.cc}::HeapObjectList = typedef std::vector<Tagged<HeapObject> >
Definition at line 30 of file read-only-promotion.cc.
HeapObjectMap
using v8::internal::anonymous_namespace{read-only-promotion.cc}::HeapObjectMap = typedef std::unordered_map<Tagged<HeapObject>, Tagged<HeapObject>, Object::Hasher, Object::KeyEqualSafe>
Definition at line 28 of file read-only-promotion.cc.
HeapObjectSet
using v8::internal::anonymous_namespace{read-only-promotion.cc}::HeapObjectSet = typedef std::unordered_set<Tagged<HeapObject>, Object::Hasher, Object::KeyEqualSafe>
Definition at line 26 of file read-only-promotion.cc.
Enumeration Type Documentation
PromoRecommendation
enum v8::internal::anonymous_namespace{read-only-promotion.cc}::PromoRecommendation [strong]
Enumerator
kReject
kPromote
kMatchHost
Definition at line 39 of file read-only-promotion.cc.
                               {
  // Do not promote this object.
  kReject,
  // Do promote this object.
  kPromote,
  // Promote if it's referenced by an object that must be promoted, otherwise
  // do not promote.
  // This is a rare case when by looking at an object itself it's not clear
  // whether it should be promoted or not. The decision can be made later
  // only taking into account where it's used.
  // One of such examples is ArrayList which shouldn't be promoted unless
  // it's a value of TemplateInfoWithProperties::property_list or
  // TemplateInfoWithProperties::property_accessors of a template that
  // should be promoted to RO space.
  kMatchHost,
};
Function Documentation
Contains() [1/2]
bool v8::internal::anonymous_namespace{read-only-promotion.cc}::Contains (const HeapObjectMap & s, Tagged< HeapObject > o)
Definition at line 35 of file read-only-promotion.cc.
                                                            {
  return s.count(o) != 0;
}
Referenced by v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::DeterminePromotees(), v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::EvaluateSubgraph(), and v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::UpdatePointersVisitor::VisitRootPointers().
Contains() [2/2]
bool v8::internal::anonymous_namespace{read-only-promotion.cc}::Contains (const HeapObjectSet & s, Tagged< HeapObject > o)
Definition at line 32 of file read-only-promotion.cc.
                                                            {
  return s.count(o) != 0;
}
Referenced by v8::internal::anonymous_namespace{objects.cc}::AppendUniqueCallbacks(), v8::base::EmulatedVirtualAddressSubspace::Contains(), v8::internal::compiler::anonymous_namespace{move-optimizer.cc}::OperandSet::ContainsOpOrAlias(), v8::internal::maglev::MaglevAssembler::JumpIfHoleNan(), v8::base::EmulatedVirtualAddressSubspace::MappedRegionContains(), v8::ArrayBuffer::NewBackingStore(), v8::base::EmulatedVirtualAddressSubspace::UnmappedRegionContains(), v8::internal::WasmTableObject::UpdateDispatchTable(), v8::internal::WriteSandboxedPointerField(), and v8::internal::String::WriteToFlat2().