v8::internal::compiler::anonymous_namespace{js-type-hint-lowering.cc} Namespace Reference
Functions
bool BinaryOperationHintToNumberOperationHint (BinaryOperationHint binop_hint, NumberOperationHint *number_hint)
bool BinaryOperationHintToBigIntOperationHint (BinaryOperationHint binop_hint, BigIntOperationHint *bigint_hint)
Function Documentation
BinaryOperationHintToBigIntOperationHint()
bool v8::internal::compiler::anonymous_namespace{js-type-hint-lowering.cc}::BinaryOperationHintToBigIntOperationHint (BinaryOperationHint binop_hint, BigIntOperationHint * bigint_hint)
Definition at line 50 of file js-type-hint-lowering.cc.
                                                                      {
  switch (binop_hint) {
    case BinaryOperationHint::kSignedSmall:
    case BinaryOperationHint::kSignedSmallInputs:
    case BinaryOperationHint::kAdditiveSafeInteger:
    case BinaryOperationHint::kNumber:
    case BinaryOperationHint::kNumberOrOddball:
    case BinaryOperationHint::kAny:
    case BinaryOperationHint::kNone:
    case BinaryOperationHint::kString:
    case BinaryOperationHint::kStringOrStringWrapper:
      return false;
    case BinaryOperationHint::kBigInt64:
      *bigint_hint = BigIntOperationHint::kBigInt64;
      return true;
    case BinaryOperationHint::kBigInt:
      *bigint_hint = BigIntOperationHint::kBigInt;
      return true;
  }
  UNREACHABLE();
}
References v8::internal::kAdditiveSafeInteger, v8::internal::kAny, v8::internal::compiler::kBigInt, v8::internal::kBigInt, v8::internal::compiler::kBigInt64, v8::internal::kBigInt64, v8::internal::kNone, v8::internal::kNumber, v8::internal::kNumberOrOddball, v8::internal::kSignedSmall, v8::internal::kSignedSmallInputs, v8::internal::kString, v8::internal::kStringOrStringWrapper, and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::JSSpeculativeBinopBuilder::GetBinaryBigIntOperationHint().
BinaryOperationHintToNumberOperationHint()
bool v8::internal::compiler::anonymous_namespace{js-type-hint-lowering.cc}::BinaryOperationHintToNumberOperationHint (BinaryOperationHint binop_hint, NumberOperationHint * number_hint)
Definition at line 21 of file js-type-hint-lowering.cc.
                                                                      {
  switch (binop_hint) {
    case BinaryOperationHint::kSignedSmall:
      *number_hint = NumberOperationHint::kSignedSmall;
      return true;
    case BinaryOperationHint::kSignedSmallInputs:
      *number_hint = NumberOperationHint::kSignedSmallInputs;
      return true;
    case BinaryOperationHint::kAdditiveSafeInteger:
      *number_hint = NumberOperationHint::kAdditiveSafeInteger;
      return true;
    case BinaryOperationHint::kNumber:
      *number_hint = NumberOperationHint::kNumber;
      return true;
    case BinaryOperationHint::kNumberOrOddball:
      *number_hint = NumberOperationHint::kNumberOrOddball;
      return true;
    case BinaryOperationHint::kAny:
    case BinaryOperationHint::kNone:
    case BinaryOperationHint::kString:
    case BinaryOperationHint::kStringOrStringWrapper:
    case BinaryOperationHint::kBigInt:
    case BinaryOperationHint::kBigInt64:
      break;
  }
  return false;
}
References v8::internal::compiler::kAdditiveSafeInteger, v8::internal::kAdditiveSafeInteger, v8::internal::kAny, v8::internal::kBigInt, v8::internal::kBigInt64, v8::internal::kNone, v8::internal::compiler::kNumber, v8::internal::kNumber, v8::internal::compiler::kNumberOrOddball, v8::internal::kNumberOrOddball, v8::internal::compiler::kSignedSmall, v8::internal::kSignedSmall, v8::internal::compiler::kSignedSmallInputs, v8::internal::kSignedSmallInputs, v8::internal::kString, and v8::internal::kStringOrStringWrapper.
Referenced by v8::internal::compiler::JSSpeculativeBinopBuilder::GetBinaryNumberOperationHint(), and v8::internal::compiler::JSTypeHintLowering::ReduceToNumberOperation().