v8::internal::wasm::gdb_server Namespace Reference
Classes
class wasm_addr_t
class GdbServerThread
class TaskRunner
class GdbServer
class Packet
class Session
class Target
class SocketBinding
class TransportBase
class Transport
class SocketTransport
class WasmModuleDebug
Functions
void UInt8ToHex (uint8_t byte, char chars[2])
bool HexToUInt8 (const char chars[2], uint8_t *byte)
bool NibbleToUInt8 (char ch, uint8_t *byte)
std::vector< std::string > StringSplit (const string &instr, const char *delim)
std::string Mem2Hex (const uint8_t *mem, size_t count)
std::string Mem2Hex (const std::string &str)
void DisableNagleAlgorithm (SocketHandle socket)
int GetLEB128Size (base::Vector< const uint8_t > module_bytes, int offset)
int ReturnPc (const NativeModule *native_module, int pc)
template<typename T >
bool StoreValue (const T &value, uint8_t *buffer, uint32_t buffer_size, uint32_t *size)
Variables
static const char kHexChars [] = `0123456789abcdef`
static const uint32_t kMaxWasmCallStack = 20
static const int kThreadId = 1
static const int kSigTrace = 5
static const int kSigSegv = 11
Function Documentation
DisableNagleAlgorithm()
void v8::internal::wasm::gdb_server::DisableNagleAlgorithm (SocketHandle socket)
Definition at line 97 of file transport.cc.
                                                {
  int nodelay = 1;
  if (::setsockopt(socket, IPPROTO_TCP, TCP_NODELAY,
                   reinterpret_cast<char*>(&nodelay), sizeof(nodelay))) {
    TRACE_GDB_REMOTE("Failed to set TCP_NODELAY option.\n");
  }
}
References TRACE_GDB_REMOTE.
Referenced by v8::internal::wasm::gdb_server::SocketTransport::AcceptConnection().
GetLEB128Size()
int v8::internal::wasm::gdb_server::GetLEB128Size (base::Vector< const uint8_t > module_bytes, int offset)
Definition at line 57 of file wasm-module-debug.cc.
                                                                      {
  int index = offset;
  while (module_bytes[index] & 0x80) index++;
  return index + 1 - offset;
}
References v8::internal::index.
Referenced by ReturnPc().
HexToUInt8()
bool v8::internal::wasm::gdb_server::HexToUInt8 (const char chars[2], uint8_t * byte)
Definition at line 22 of file gdb-remote-util.cc.
                                                    {
  uint8_t o1, o2;
  if (NibbleToUInt8(chars[0], &o1) && NibbleToUInt8(chars[1], &o2)) {
    *byte = (o1 << 4) + o2;
    return true;
  }
  return false;
}
References NibbleToUInt8().
Referenced by v8::internal::wasm::gdb_server::Session::GetPacket(), and v8::internal::wasm::gdb_server::Packet::GetWord8().
Mem2Hex() [1/2]
std::string v8::internal::wasm::gdb_server::Mem2Hex (const std::string & str)
Definition at line 97 of file gdb-remote-util.cc.
                                        {
  return Mem2Hex(reinterpret_cast<const uint8_t*>(str.data()), str.size());
}
References Mem2Hex().
Mem2Hex() [2/2]
std::string v8::internal::wasm::gdb_server::Mem2Hex (const uint8_t * mem, size_t count)
Definition at line 90 of file gdb-remote-util.cc.
                                                    {
  std::vector<char> result(count * 2 + 1);
  for (size_t i = 0; i < count; i++) UInt8ToHex(*mem++, &result[i * 2]);
  result[count * 2] = '\0';
  return result.data();
}
References v8::base::internal::result, and UInt8ToHex().
Referenced by v8::internal::wasm::gdb_server::Target::InitQueryPropertyMap(), and Mem2Hex().
NibbleToUInt8()
bool v8::internal::wasm::gdb_server::NibbleToUInt8 (char ch, uint8_t * byte)
Definition at line 32 of file gdb-remote-util.cc.
                                           {
  DCHECK(byte);
  // Check for nibble of a-f
  if ((ch >= 'a') && (ch <= 'f')) {
    *byte = (ch - 'a' + 10);
    return true;
  }
  // Check for nibble of A-F
  if ((ch >= 'A') && (ch <= 'F')) {
    *byte = (ch - 'A' + 10);
    return true;
  }
  // Check for nibble of 0-9
  if ((ch >= '0') && (ch <= '9')) {
    *byte = (ch - '0');
    return true;
  }
  // Not a valid nibble representation
  return false;
}
References v8::internal::DCHECK().
Referenced by v8::internal::wasm::gdb_server::Packet::GetHexString(), v8::internal::wasm::gdb_server::Packet::GetNumberSep(), and HexToUInt8().
ReturnPc()
int v8::internal::wasm::gdb_server::ReturnPc (const NativeModule * native_module, int pc)
Definition at line 63 of file wasm-module-debug.cc.
                                                        {
  base::Vector<const uint8_t> wire_bytes = native_module->wire_bytes();
  uint8_t opcode = wire_bytes[pc];
  switch (opcode) {
    case kExprCallFunction: {
      // skip opcode
      pc++;
      // skip function index
      return pc + GetLEB128Size(wire_bytes, pc);
    }
    case kExprCallIndirect: {
      // skip opcode
      pc++;
      // skip signature index
      pc += GetLEB128Size(wire_bytes, pc);
      // skip table index
      return pc + GetLEB128Size(wire_bytes, pc);
    }
    default:
      UNREACHABLE();
  }
}
References GetLEB128Size(), v8::internal::UNREACHABLE(), and v8::internal::wasm::NativeModule::wire_bytes().
Referenced by v8::internal::wasm::gdb_server::WasmModuleDebug::GetCallStack().
StoreValue()
template<typename T >
bool v8::internal::wasm::gdb_server::StoreValue (const T & value, uint8_t * buffer, uint32_t buffer_size, uint32_t * size)
Definition at line 382 of file wasm-module-debug.cc.
                                {
  *size = sizeof(value);
  if (*size > buffer_size) return false;
  memcpy(buffer, &value, *size);
  return true;
}
References size(), and v8::internal::value.
Referenced by v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmValue().
StringSplit()
std::vector< std::string > V8_EXPORT_PRIVATE v8::internal::wasm::gdb_server::StringSplit (const string & instr, const char * delim)
Definition at line 57 of file gdb-remote-util.cc.
                                                                         {
  std::vector<std::string> result;
  const char* in = instr.data();
  if (nullptr == in) return result;
  // Check if we have nothing to do
  if (nullptr == delim) {
    result.push_back(string(in));
    return result;
  }
  while (*in) {
    // Toss all preceeding delimiters
    while (*in && strchr(delim, *in)) in++;
    // If we still have something to process
    if (*in) {
      const char* start = in;
      size_t len = 0;
      // Keep moving forward for all valid chars
      while (*in && (strchr(delim, *in) == nullptr)) {
        len++;
        in++;
      }
      // Build this token and add it to the array.
      result.push_back(string{start, len});
    }
  }
  return result;
}
References v8::base::internal::result.
Referenced by v8::internal::wasm::gdb_server::Target::ProcessQueryPacket().
UInt8ToHex()
void v8::internal::wasm::gdb_server::UInt8ToHex (uint8_t byte, char chars[2])
Definition at line 16 of file gdb-remote-util.cc.
                                             {
  DCHECK(chars);
  chars[0] = kHexChars[byte >> 4];
  chars[1] = kHexChars[byte & 0xF];
}
References v8::internal::DCHECK(), and kHexChars.
Referenced by v8::internal::wasm::gdb_server::Packet::AddNumberSep(), v8::internal::wasm::gdb_server::Packet::AddWord8(), v8::internal::wasm::gdb_server::Session::GetPacket(), v8::internal::wasm::gdb_server::Packet::GetPacketData(), and Mem2Hex().
Variable Documentation
kHexChars
const char v8::internal::wasm::gdb_server::kHexChars[] = `0123456789abcdef` [static]
Definition at line 14 of file gdb-remote-util.cc.
Referenced by UInt8ToHex().
kMaxWasmCallStack
const uint32_t v8::internal::wasm::gdb_server::kMaxWasmCallStack = 20 [static]
Definition at line 20 of file gdb-server.cc.
Referenced by v8::internal::wasm::gdb_server::GdbServer::DebugDelegate::DebugDelegate().
kSigSegv
const int v8::internal::wasm::gdb_server::kSigSegv = 11 [static]
Definition at line 24 of file target.cc.
Referenced by v8::internal::wasm::gdb_server::Target::OnException().
kSigTrace
const int v8::internal::wasm::gdb_server::kSigTrace = 5 [static]
Definition at line 23 of file target.cc.
Referenced by v8::internal::wasm::gdb_server::Target::OnProgramBreak().
kThreadId
const int v8::internal::wasm::gdb_server::kThreadId = 1 [static]
Definition at line 20 of file target.cc.
Referenced by v8::internal::wasm::gdb_server::Target::InitQueryPropertyMap(), v8::internal::wasm::gdb_server::Target::ProcessPacket(), v8::internal::wasm::gdb_server::Target::ProcessQueryPacket(), and v8::internal::wasm::gdb_server::Target::SetStopReply().