v8::internal::anonymous_namespace{templates.cc} Namespace Reference
Functions
DirectHandle< JSObject > CreateSlowJSObjectWithProperties (Isolate *isolate, DirectHandle< FixedArray > property_names, const MemorySpan< MaybeLocal< Value >> &property_values, int num_properties_set)
Function Documentation
CreateSlowJSObjectWithProperties()
DirectHandle<JSObject> v8::internal::anonymous_namespace{templates.cc}::CreateSlowJSObjectWithProperties (Isolate * isolate, DirectHandle< FixedArray > property_names, const MemorySpan< MaybeLocal< Value >> & property_values, int num_properties_set)
Definition at line 221 of file templates.cc.
                            {
  DirectHandle<JSObject> object = isolate->factory()->NewSlowJSObjectFromMap(
      isolate->slow_object_with_object_prototype_map(), num_properties_set,
      AllocationType::kYoung);
  Handle<Object> properties = handle(object->raw_properties_or_hash(), isolate);
  for (int i = 0; i < static_cast<int>(property_values.size()); ++i) {
    Local<Value> property_value;
    if (!property_values[i].ToLocal(&property_value)) {
      continue;
    }
    properties = PropertyDictionary::Add(
        isolate, Cast<PropertyDictionary>(properties),
        Cast<String>(handle(property_names->get(i), isolate)),
        Utils::OpenDirectHandle(*property_value), PropertyDetails::Empty());
  }
  object->set_raw_properties_or_hash(*properties);
  return object;
}
References v8::bigint::Add(), v8::internal::PropertyDetails::Empty(), v8::internal::Isolate::factory(), v8::internal::handle(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::kYoung, v8::internal::Factory::NewSlowJSObjectFromMap(), and v8::Utils::OpenDirectHandle().
Referenced by v8::internal::DictionaryTemplateInfo::NewInstance().