cppgc Namespace Reference
cppgc - A C++ garbage collection library.
Namespaces
 anonymous_namespace{heap.cc}
 internal
Implementation details of cppgc.
 subtle
 testing
Namespace contains testing helpers.
Classes
class AllocationHandle
class MakeGarbageCollectedTraitBase
Base trait that provides utilities for advancers users that have custom allocation needs (e.g., overriding size).
struct AdditionalBytes
Passed to MakeGarbageCollected to specify how many bytes should be appended to the allocated object.
class MakeGarbageCollectedTrait
Default trait class that specifies how to construct an object of type T.
struct PostConstructionCallbackTrait
Allows users to specify a post-construction callback for specific types.
struct CustomSpaceIndex
Index identifying a custom space.
class CustomSpaceBase
Top-level base class for custom spaces.
class CustomSpace
Base class custom spaces should directly inherit from.
struct SpaceTrait
User-overridable trait that allows pinning types to custom spaces.
class DefaultPlatform
Platform provided by cppgc.
class GarbageCollected
Base class for managed objects.
class GarbageCollectedMixin
Base class for managed mixin objects.
class HeapHandle
Opaque handle used for additional heap APIs.
struct HeapStatistics
HeapStatistics contains memory consumption and utilization statistics for a cppgc heap.
class Heap
class LivenessBroker
The broker is passed to weak callbacks to allow (temporarily) querying the liveness state of an object.
class NameProvider
NameProvider allows for providing a human-readable name for garbage-collected objects.
class Platform
Platform interface used by Heap.
class ProcessHeapStatistics
struct TraceDescriptor
Describes how to trace an object, i.e., how to visit all Oilpan-relevant fields of an object.
struct TraceTrait
struct EphemeronPair
An ephemeron pair is used to conditionally retain an object.
class Visitor
Visitor passed to trace methods.
struct TraceTrait< v8::TracedReference< T > >
Typedefs
template<typename T >
using Member = internal::BasicMember< T, internal::StrongMemberTag, internal::DijkstraWriteBarrierPolicy, internal::DefaultMemberCheckingPolicy, internal::DefaultMemberStorage >
Members are used in classes to contain strong pointers to other garbage collected objects.
template<typename T >
using WeakMember = internal::BasicMember< T, internal::WeakMemberTag, internal::DijkstraWriteBarrierPolicy, internal::DefaultMemberCheckingPolicy, internal::DefaultMemberStorage >
WeakMember is similar to Member in that it is used to point to other garbage collected objects.
template<typename T >
using UntracedMember = internal::BasicMember< T, internal::UntracedMemberTag, internal::NoWriteBarrierPolicy, internal::DefaultMemberCheckingPolicy, internal::DefaultMemberStorage >
UntracedMember is a pointer to an on-heap object that is not traced for some reason.
template<typename T >
using Persistent = internal::BasicPersistent< T, internal::StrongPersistentPolicy >
Persistent is a way to create a strong pointer from an off-heap object to another on-heap object.
template<typename T >
using WeakPersistent = internal::BasicPersistent< T, internal::WeakPersistentPolicy >
WeakPersistent is a way to create a weak pointer from an off-heap object to an on-heap object.
using IdleTask = v8::IdleTask
using JobHandle = v8::JobHandle
using JobDelegate = v8::JobDelegate
using JobTask = v8::JobTask
using PageAllocator = v8::PageAllocator
using Task = v8::Task
using TaskPriority = v8::TaskPriority
using TaskRunner = v8::TaskRunner
using TracingController = v8::TracingController
using SourceLocation = v8::SourceLocation
using TraceCallback = void(*)(Visitor *visitor, const void *object)
Callback for invoking tracing on a given object.
using TraceDescriptorCallback = TraceDescriptor(*)(const void *address)
Callback for getting a TraceDescriptor for a given address.
using WeakCallback = void(*)(const LivenessBroker &, const void *)
Enumerations
enum class EmbedderStackState { kMayContainHeapPointers
, kNoHeapPointers
 }
Indicator for the stack state of the embedder.
Functions
bool IsInitialized ()
void InitializeProcess (PageAllocator *page_allocator=nullptr, size_t desired_heap_size=0)
Process-global initialization of the garbage collector.
void ShutdownProcess ()
Must be called after destroying the last used heap.
template<typename T , typename... Args>
T * MakeGarbageCollected (AllocationHandle &handle, Args &&... args)
Constructs a managed object of type T where T transitively inherits from GarbageCollected.
template<typename T , typename... Args>
T * MakeGarbageCollected (AllocationHandle &handle, AdditionalBytes additional_bytes, Args &&... args)
Constructs a managed object of type T where T transitively inherits from GarbageCollected.
Variables
template<typename T >
concept IsStackAllocatedType
constexpr internal::SentinelPointer kSentinelPointer
template<typename T >
constexpr bool IsGarbageCollectedMixinTypeV
Value is true for types that inherit from GarbageCollectedMixin but not GarbageCollected<T> (i.e., they are free mixins), and false otherwise.
template<typename T >
constexpr bool IsGarbageCollectedTypeV
Value is true for types that inherit from GarbageCollected<T>, and false otherwise.
template<typename T >
constexpr bool IsGarbageCollectedOrMixinTypeV
Value is true for types that inherit from either GarbageCollected<T> or GarbageCollectedMixin, and false otherwise.
template<typename T >
constexpr bool IsGarbageCollectedWithMixinTypeV
Value is true for types that inherit from GarbageCollected<T> and GarbageCollectedMixin, and false otherwise.
template<typename T >
constexpr bool IsMemberTypeV = internal::IsMemberType<T>::value
Value is true for types of type Member<T>, and false otherwise.
template<typename T >
constexpr bool IsUntracedMemberTypeV = internal::IsUntracedMemberType<T>::value
Value is true for types of type UntracedMember<T>, and false otherwise.
template<typename T >
constexpr bool IsWeakMemberTypeV = internal::IsWeakMemberType<T>::value
Value is true for types of type WeakMember<T>, and false otherwise.
template<typename T >
constexpr bool IsWeakV = internal::IsWeak<T>::value
Value is true for types that are considered weak references, and false otherwise.
template<typename T >
constexpr bool IsCompleteV = internal::IsComplete<T>::value
Value is true for types that are complete, and false otherwise.
template<typename T >
constexpr bool IsMemberOrWeakMemberTypeV
Value is true for member types Member<T> and WeakMember<T>.
template<typename T >
constexpr bool IsAnyMemberTypeV = internal::IsAnyMemberTypeV<std::decay_t<T>>
Value is true for any member type.
Detailed Description
cppgc - A C++ garbage collection library.
Typedef Documentation
IdleTask
using cppgc::IdleTask = typedef v8::IdleTask
Definition at line 18 of file platform.h.
JobDelegate
using cppgc::JobDelegate = typedef v8::JobDelegate
Definition at line 20 of file platform.h.
JobHandle
using cppgc::JobHandle = typedef v8::JobHandle
Definition at line 19 of file platform.h.
JobTask
using cppgc::JobTask = typedef v8::JobTask
Definition at line 21 of file platform.h.
Member
template<typename T >
using cppgc::Member = typedef internal::BasicMember< T, internal::StrongMemberTag, internal::DijkstraWriteBarrierPolicy, internal::DefaultMemberCheckingPolicy, internal::DefaultMemberStorage>
Members are used in classes to contain strong pointers to other garbage collected objects.
All Member fields of a class must be traced in the class' trace method.
Definition at line 570 of file member.h.
PageAllocator
using cppgc::PageAllocator = typedef v8::PageAllocator
Definition at line 22 of file platform.h.
Persistent
template<typename T >
using cppgc::Persistent = typedef internal::BasicPersistent<T, internal::StrongPersistentPolicy>
Persistent is a way to create a strong pointer from an off-heap object to another on-heap object.
As long as the Persistent handle is alive the GC will keep the object pointed to alive. The Persistent handle is always a GC root from the point of view of the GC. Persistent must be constructed and destructed in the same thread.
Definition at line 362 of file persistent.h.
SourceLocation
using cppgc::SourceLocation = typedef v8::SourceLocation
Definition at line 12 of file source-location.h.
Task
using cppgc::Task = typedef v8::Task
Definition at line 23 of file platform.h.
TaskPriority
using cppgc::TaskPriority = typedef v8::TaskPriority
Definition at line 24 of file platform.h.
TaskRunner
using cppgc::TaskRunner = typedef v8::TaskRunner
Definition at line 25 of file platform.h.
TraceCallback
using cppgc::TraceCallback = typedef void (*)(Visitor* visitor, const void* object)
Callback for invoking tracing on a given object.
Parameters
visitor The visitor to dispatch to.
object The object to invoke tracing on.
Definition at line 37 of file trace-trait.h.
TraceDescriptorCallback
using cppgc::TraceDescriptorCallback = typedef TraceDescriptor (*)(const void* address)
Callback for getting a TraceDescriptor for a given address.
Parameters
address Possibly inner address of an object.
Returns
a TraceDescriptor for the provided address.
Definition at line 61 of file trace-trait.h.
TracingController
using cppgc::TracingController = typedef v8::TracingController
Definition at line 26 of file platform.h.
UntracedMember
template<typename T >
using cppgc::UntracedMember = typedef internal::BasicMember< T, internal::UntracedMemberTag, internal::NoWriteBarrierPolicy, internal::DefaultMemberCheckingPolicy, internal::DefaultMemberStorage>
UntracedMember is a pointer to an on-heap object that is not traced for some reason.
Do not use this unless you know what you are doing. Keeping raw pointers to on-heap objects is prohibited unless used from stack. Pointee must be kept alive through other means.
Definition at line 594 of file member.h.
WeakCallback
using cppgc::WeakCallback = typedef void (*)(const LivenessBroker&, const void*)
Definition at line 37 of file visitor.h.
WeakMember
template<typename T >
using cppgc::WeakMember = typedef internal::BasicMember< T, internal::WeakMemberTag, internal::DijkstraWriteBarrierPolicy, internal::DefaultMemberCheckingPolicy, internal::DefaultMemberStorage>
WeakMember is similar to Member in that it is used to point to other garbage collected objects.
However instead of creating a strong pointer to the object, the WeakMember creates a weak pointer, which does not keep the pointee alive. Hence if all pointers to to a heap allocated object are weak the object will be garbage collected. At the time of GC the weak pointers will automatically be set to null.
Definition at line 583 of file member.h.
WeakPersistent
template<typename T >
using cppgc::WeakPersistent = typedef internal::BasicPersistent<T, internal::WeakPersistentPolicy>
WeakPersistent is a way to create a weak pointer from an off-heap object to an on-heap object.
The pointer is automatically cleared when the pointee gets collected. WeakPersistent must be constructed and destructed in the same thread.
Definition at line 372 of file persistent.h.
Enumeration Type Documentation
EmbedderStackState
enum cppgc::EmbedderStackState [strong]
Indicator for the stack state of the embedder.
Enumerator
kMayContainHeapPointers Stack may contain interesting heap pointers.
kNoHeapPointers Stack does not contain any interesting heap pointers.
Definition at line 15 of file common.h.
                              {
  /**
   * Stack may contain interesting heap pointers.
   */
  kMayContainHeapPointers,
  /**
   * Stack does not contain any interesting heap pointers.
   */
  kNoHeapPointers,
};
Function Documentation
InitializeProcess()
void cppgc::InitializeProcess (PageAllocator * page_allocator = nullptr, size_t desired_heap_size = 0)
Process-global initialization of the garbage collector.
Must be called before creating a Heap.
Can be called multiple times when paired with ShutdownProcess().
Parameters
page_allocator The allocator used for maintaining meta data. Must stay always alive and not change between multiple calls to InitializeProcess. If no allocator is provided, a default internal version will be used.
desired_heap_size Desired amount of virtual address space to reserve for the heap, in bytes. Actual size will be clamped to minimum and maximum values based on compile-time settings and may be rounded up. If this parameter is zero, a default value will be used.
Definition at line 92 of file platform.cc.
                                                 {
#if defined(V8_USE_ADDRESS_SANITIZER) && defined(V8_HOST_ARCH_64_BIT)
  // Retrieve asan's internal shadow memory granularity and check that Oilpan's
  // object alignment/sizes are multiple of this granularity. This is needed to
  // perform poisoness checks.
  size_t shadow_scale;
  __asan_get_shadow_mapping(&shadow_scale, nullptr);
  DCHECK(shadow_scale);
  const size_t poisoning_granularity = 1 << shadow_scale;
  CHECK_EQ(0u, internal::kAllocationGranularity % poisoning_granularity);
#endif
  auto& allocator = internal::CreateAllocatorIfNeeded(page_allocator);
  CHECK(!internal::g_page_allocator);
  internal::GlobalGCInfoTable::Initialize(allocator);
#if defined(CPPGC_CAGED_HEAP)
  internal::CagedHeap::InitializeIfNeeded(allocator, desired_heap_size);
#endif // defined(CPPGC_CAGED_HEAP)
  internal::g_page_allocator = &allocator;
}
References CHECK, CHECK_EQ, cppgc::internal::anonymous_namespace{platform.cc}::CreateAllocatorIfNeeded(), DCHECK, cppgc::internal::anonymous_namespace{platform.cc}::g_page_allocator, cppgc::internal::GlobalGCInfoTable::Initialize(), cppgc::internal::CagedHeap::InitializeIfNeeded(), and cppgc::internal::kAllocationGranularity.
Referenced by v8::V8::Initialize().
IsInitialized()
bool cppgc::IsInitialized ()
Definition at line 90 of file platform.cc.
{ return internal::g_page_allocator != nullptr; }
References cppgc::internal::anonymous_namespace{platform.cc}::g_page_allocator.
Referenced by v8::internal::V8::Initialize(), and v8::V8::Initialize().
MakeGarbageCollected() [1/2]
template<typename T , typename... Args>
T* cppgc::MakeGarbageCollected (AllocationHandle & handle, AdditionalBytes additional_bytes, Args &&... args) [inline]
Constructs a managed object of type T where T transitively inherits from GarbageCollected.
Created objects will have additional bytes appended to it. Allocated memory would suffice for sizeof(T) + additional_bytes.
Parameters
additional_bytes Denotes how many bytes to append to T.
args List of arguments with which an instance of T will be constructed.
Returns
an instance of type T.
Definition at line 294 of file allocation.h.
                                                  {
  T* object = MakeGarbageCollectedTrait<T>::Call(handle, additional_bytes,
                                                 std::forward<Args>(args)...);
  PostConstructionCallbackTrait<T>::Call(object);
  return object;
}
References v8::base::args, cppgc::MakeGarbageCollectedTrait< T >::Call(), cppgc::PostConstructionCallbackTrait< T, typename >::Call(), and v8::internal::handle().
MakeGarbageCollected() [2/2]
template<typename T , typename... Args>
T* cppgc::MakeGarbageCollected (AllocationHandle & handle, Args &&... args) [inline]
Constructs a managed object of type T where T transitively inherits from GarbageCollected.
Parameters
args List of arguments with which an instance of T will be constructed.
Returns
an instance of type T.
Definition at line 276 of file allocation.h.
                                                                            {
  T* object =
      MakeGarbageCollectedTrait<T>::Call(handle, std::forward<Args>(args)...);
  PostConstructionCallbackTrait<T>::Call(object);
  return object;
}
References v8::base::args, cppgc::MakeGarbageCollectedTrait< T >::Call(), cppgc::PostConstructionCallbackTrait< T, typename >::Call(), and v8::internal::handle().
ShutdownProcess()
void cppgc::ShutdownProcess ()
Must be called after destroying the last used heap.
Some process-global metadata may not be returned and reused upon a subsequent InitializeProcess() call.
Definition at line 115 of file platform.cc.
{ internal::g_page_allocator = nullptr; }
References cppgc::internal::anonymous_namespace{platform.cc}::g_page_allocator.
Variable Documentation
IsAnyMemberTypeV
template<typename T >
constexpr bool cppgc::IsAnyMemberTypeV = internal::IsAnyMemberTypeV<std::decay_t<T>> [constexpr]
Value is true for any member type.
Definition at line 268 of file type-traits.h.
IsCompleteV
template<typename T >
constexpr bool cppgc::IsCompleteV = internal::IsComplete<T>::value [constexpr]
Value is true for types that are complete, and false otherwise.
Definition at line 255 of file type-traits.h.
IsGarbageCollectedMixinTypeV
template<typename T >
constexpr bool cppgc::IsGarbageCollectedMixinTypeV [constexpr]
Initial value:
=
    internal::IsGarbageCollectedMixinType<T>::value
Value is true for types that inherit from GarbageCollectedMixin but not GarbageCollected<T> (i.e., they are free mixins), and false otherwise.
Definition at line 199 of file type-traits.h.
IsGarbageCollectedOrMixinTypeV
template<typename T >
constexpr bool cppgc::IsGarbageCollectedOrMixinTypeV [constexpr]
Initial value:
=
    internal::IsGarbageCollectedOrMixinType<T>::value
Value is true for types that inherit from either GarbageCollected<T> or GarbageCollectedMixin, and false otherwise.
Definition at line 215 of file type-traits.h.
IsGarbageCollectedTypeV
template<typename T >
constexpr bool cppgc::IsGarbageCollectedTypeV [constexpr]
Initial value:
=
    internal::IsGarbageCollectedType<T>::value
Value is true for types that inherit from GarbageCollected<T>, and false otherwise.
Definition at line 207 of file type-traits.h.
IsGarbageCollectedWithMixinTypeV
template<typename T >
constexpr bool cppgc::IsGarbageCollectedWithMixinTypeV [constexpr]
Initial value:
=
    internal::IsGarbageCollectedWithMixinType<T>::value
Value is true for types that inherit from GarbageCollected<T> and GarbageCollectedMixin, and false otherwise.
Definition at line 223 of file type-traits.h.
IsMemberOrWeakMemberTypeV
template<typename T >
constexpr bool cppgc::IsMemberOrWeakMemberTypeV [constexpr]
Initial value:
=
    IsMemberTypeV<T> || IsWeakMemberTypeV<T>
Value is true for member types Member<T> and WeakMember<T>.
Definition at line 261 of file type-traits.h.
IsMemberTypeV
template<typename T >
constexpr bool cppgc::IsMemberTypeV = internal::IsMemberType<T>::value [constexpr]
Value is true for types of type Member<T>, and false otherwise.
Definition at line 230 of file type-traits.h.
IsStackAllocatedType
template<typename T >
concept cppgc::IsStackAllocatedType
Initial value:
=
    requires { typename T::IsStackAllocatedTypeMarker; }
Definition at line 51 of file macros.h.
IsUntracedMemberTypeV
template<typename T >
constexpr bool cppgc::IsUntracedMemberTypeV = internal::IsUntracedMemberType<T>::value [constexpr]
Value is true for types of type UntracedMember<T>, and false otherwise.
Definition at line 236 of file type-traits.h.
IsWeakMemberTypeV
template<typename T >
constexpr bool cppgc::IsWeakMemberTypeV = internal::IsWeakMemberType<T>::value [constexpr]
Value is true for types of type WeakMember<T>, and false otherwise.
Definition at line 242 of file type-traits.h.
IsWeakV
template<typename T >
constexpr bool cppgc::IsWeakV = internal::IsWeak<T>::value [constexpr]
Value is true for types that are considered weak references, and false otherwise.
Definition at line 249 of file type-traits.h.
kSentinelPointer
constexpr internal::SentinelPointer cppgc::kSentinelPointer [constexpr]
Definition at line 35 of file sentinel-pointer.h.
Referenced by cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::Assign(), cppgc::internal::SameThreadEnabledCheckingPolicy< kCheckOffHeapAssignments >::CheckPointer(), cppgc::internal::WriteBarrier::DijkstraMarkingBarrierSlowWithSentinelCheck(), cppgc::internal::WriteBarrierTypeForNonCagedHeapPolicy::ValueModeDispatch< WriteBarrier::ValueMode::kValuePresent >::Get(), cppgc::LivenessBroker::IsHeapObjectAlive(), cppgc::internal::RawPointer::IsSentinel(), cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::IsValid(), cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::IsValid(), cppgc::internal::WriteBarrier::SteeleMarkingBarrierSlowWithSentinelCheck(), cppgc::Visitor::Trace(), and cppgc::Visitor::TraceStrongly().