heap::base::anonymous_namespace{stack.cc} Namespace Reference
Functions
void IterateAsanFakeFrameIfNecessary (StackVisitor *visitor, const Stack::Segment &segment, const void *address)
void IteratePointersInUnsafeStackIfNecessary (StackVisitor *visitor, const Stack::Segment &segment)
V8_NOINLINE DISABLE_ASAN DISABLE_HWASAN DISABLE_TSAN void IteratePointersInStack (StackVisitor *visitor, const Stack::Segment &segment)
Function Documentation
IterateAsanFakeFrameIfNecessary()
void heap::base::anonymous_namespace{stack.cc}::IterateAsanFakeFrameIfNecessary (StackVisitor * visitor, const Stack::Segment & segment, const void * address)
Definition at line 86 of file stack.cc.
                                                          {}
Referenced by IteratePointersInStack().
IteratePointersInStack()
V8_NOINLINE DISABLE_ASAN DISABLE_HWASAN DISABLE_TSAN void heap::base::anonymous_namespace{stack.cc}::IteratePointersInStack (StackVisitor * visitor, const Stack::Segment & segment)
Definition at line 127 of file stack.cc.
                                                         {
  CHECK_NOT_NULL(segment.top);
  CHECK_NOT_NULL(segment.start);
  CHECK_GE(segment.start, segment.top);
  // All supported platforms should have their stack aligned to at least
  // sizeof(void*).
  constexpr size_t kMinStackAlignment = sizeof(void*);
  CHECK_EQ(0u,
           reinterpret_cast<uintptr_t>(segment.top) & (kMinStackAlignment - 1));
  CHECK_EQ(0u, reinterpret_cast<uintptr_t>(segment.start) &
                   (kMinStackAlignment - 1));
  for (const void* const* current =
           reinterpret_cast<const void* const*>(segment.top);
       current < segment.start; ++current) {
    // MSAN: Instead of unpoisoning the whole stack, the slot's value is copied
    // into a local which is unpoisoned.
    const void* address = *current;
    MSAN_MEMORY_IS_INITIALIZED(&address, sizeof(address));
    if (address == nullptr) {
      continue;
    }
    visitor->VisitPointer(address);
    IterateAsanFakeFrameIfNecessary(visitor, segment, address);
  }
}
References CHECK_EQ, CHECK_GE, CHECK_NOT_NULL, IterateAsanFakeFrameIfNecessary(), MSAN_MEMORY_IS_INITIALIZED, heap::base::Stack::Segment::start, heap::base::Stack::Segment::top, and heap::base::StackVisitor::VisitPointer().
Referenced by heap::base::Stack::IterateBackgroundStacks(), and heap::base::Stack::IteratePointersInSegment().
IteratePointersInUnsafeStackIfNecessary()
void heap::base::anonymous_namespace{stack.cc}::IteratePointersInUnsafeStackIfNecessary (StackVisitor * visitor, const Stack::Segment & segment)
Definition at line 91 of file stack.cc.
                                                                          {
#ifdef V8_USE_SAFE_STACK
  CHECK_NOT_NULL(segment.unsafe_stack_start);
  CHECK_NOT_NULL(segment.unsafe_stack_top);
  // Source:
  // https://github.com/llvm/llvm-project/blob/main/compiler-rt/lib/safestack/safestack.cpp
  constexpr size_t kSafeStackAlignmentBytes = 16;
  CHECK_GE(segment.unsafe_stack_start, segment.unsafe_stack_top);
  CHECK_EQ(0u, reinterpret_cast<uintptr_t>(segment.unsafe_stack_top) &
                   (kSafeStackAlignmentBytes - 1));
  CHECK_EQ(0u, reinterpret_cast<uintptr_t>(segment.unsafe_stack_start) &
                   (kSafeStackAlignmentBytes - 1));
  for (const void* const* current =
           reinterpret_cast<const void* const*>(segment.unsafe_stack_top);
       current < segment.unsafe_stack_start; ++current) {
    const void* address_curr = *current;
    if (address_curr == nullptr) continue;
    visitor->VisitPointer(address_curr);
  }
#endif // V8_USE_SAFE_STACK
}
References CHECK_EQ, CHECK_GE, CHECK_NOT_NULL, and heap::base::StackVisitor::VisitPointer().
Referenced by heap::base::Stack::IterateBackgroundStacks(), and heap::base::Stack::IteratePointersInSegment().