v8::internal::compiler::anonymous_namespace{machine-operator-reducer.cc} Namespace Reference
Classes
struct BitfieldCheck
struct SimplifiedCondition
Functions
template<class T >
T SilenceNaN (T x)
template<typename T >
bool CanRevertLeftShiftWithRightShift (T value, T shift)
bool CanTruncate (int64_t value)
bool IsFloat64RepresentableAsFloat32 (const Float64Matcher &m)
bool IsZero (Node *node)
std::optional< Node * > TryGetInvertedCondition (Node *cond)
std::optional< SimplifiedCondition > TrySimplifyCompareZero (Node *cond)
Node * TrySimplifyCompareForTestBit (Node *cond)
Function Documentation
CanRevertLeftShiftWithRightShift()
template<typename T >
bool v8::internal::compiler::anonymous_namespace{machine-operator-reducer.cc}::CanRevertLeftShiftWithRightShift (T value, T shift)
Definition at line 1627 of file machine-operator-reducer.cc.
                                                        {
  using unsigned_T = std::make_unsigned_t<T>;
  if (shift < 0 || shift >= std::numeric_limits<T>::digits + 1) {
    // This shift would be UB in C++
    return false;
  }
  if (static_cast<T>(static_cast<unsigned_T>(value) << shift) >> shift !=
      static_cast<T>(value)) {
    return false;
  }
  return true;
}
References v8::internal::value.
CanTruncate()
bool v8::internal::compiler::anonymous_namespace{machine-operator-reducer.cc}::CanTruncate (int64_t value)
Definition at line 1640 of file machine-operator-reducer.cc.
                                {
  return value >= std::numeric_limits<int32_t>::min() &&
         value <= std::numeric_limits<int32_t>::max();
}
References v8::internal::value.
Referenced by v8::internal::compiler::MachineOperatorReducer::ReduceWord64Comparisons().
IsFloat64RepresentableAsFloat32()
bool v8::internal::compiler::anonymous_namespace{machine-operator-reducer.cc}::IsFloat64RepresentableAsFloat32 (const Float64Matcher & m)
Definition at line 2685 of file machine-operator-reducer.cc.
                                                              {
  if (m.HasResolvedValue()) {
    double v = m.ResolvedValue();
    return DoubleToFloat32(v) == v;
  }
  return false;
}
References v8::internal::DoubleToFloat32(), v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), and v8::internal::compiler::ValueMatcher< T, kOpcode >::ResolvedValue().
Referenced by v8::internal::compiler::MachineOperatorReducer::ReduceFloat64Compare().
IsZero()
bool v8::internal::compiler::anonymous_namespace{machine-operator-reducer.cc}::IsZero (Node * node)
Definition at line 2763 of file machine-operator-reducer.cc.
                        {
  switch (node->opcode()) {
#define CASE_IS_ZERO(opcode, matcher) \
  case IrOpcode::opcode: { \
    matcher m(node); \
    return m.Is(0); \
  }
    CASE_IS_ZERO(kInt32Constant, Int32Matcher)
    CASE_IS_ZERO(kInt64Constant, Int64Matcher)
#undef CASE_IS_ZERO
    default:
      break;
  }
  return false;
}
References CASE_IS_ZERO, and v8::internal::compiler::Node::opcode().
SilenceNaN()
template<class T >
T v8::internal::compiler::anonymous_namespace{machine-operator-reducer.cc}::SilenceNaN (T x)
Definition at line 184 of file machine-operator-reducer.cc.
                  {
  DCHECK(std::isnan(x));
  // Do some calculation to make a signalling NaN quiet.
  return x - x;
}
References v8::internal::DCHECK().
Referenced by v8::internal::compiler::MachineOperatorReducer::Reduce().
TryGetInvertedCondition()
std::optional<Node*> v8::internal::compiler::anonymous_namespace{machine-operator-reducer.cc}::TryGetInvertedCondition (Node * cond)
Definition at line 2781 of file machine-operator-reducer.cc.
                                                       {
  if (cond->opcode() == IrOpcode::kWord32Equal) {
    Int32BinopMatcher m(cond);
    if (IsZero(m.right().node())) {
      return m.left().node();
    }
  }
  return std::nullopt;
}
References v8::internal::IsZero(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::left(), v8::internal::compiler::Node::opcode(), and v8::internal::compiler::BinopMatcher< Left, Right, rep >::right().
Referenced by TrySimplifyCompareZero().
TrySimplifyCompareForTestBit()
Node* v8::internal::compiler::anonymous_namespace{machine-operator-reducer.cc}::TrySimplifyCompareForTestBit (Node * cond)
Definition at line 2841 of file machine-operator-reducer.cc.
                                               {
  if (cond->opcode() != IrOpcode::kWord32Equal) {
    return nullptr;
  }
  Node* word_equal_left = cond->InputAt(0);
  Node* word_equal_right = cond->InputAt(1);
  if (word_equal_left->opcode() != IrOpcode::kWord32And ||
      word_equal_right->opcode() != IrOpcode::kInt32Constant) {
    return nullptr;
  }
  Node* word_and_right = word_equal_left->InputAt(1);
  if (word_and_right->opcode() != IrOpcode::kInt32Constant) {
    return nullptr;
  }
  int32_t a = OpParameter<int32_t>(word_and_right->op());
  int32_t b = OpParameter<int32_t>(word_equal_right->op());
  if (a != b || !base::bits::IsPowerOfTwo(a)) {
    return nullptr;
  }
  DCHECK_EQ(word_equal_left->opcode(), IrOpcode::kWord32And);
  return word_equal_left;
}
References DCHECK_EQ, v8::internal::compiler::Node::InputAt(), v8::base::bits::IsPowerOfTwo(), v8::internal::compiler::Node::op(), and v8::internal::compiler::Node::opcode().
Referenced by v8::internal::compiler::MachineOperatorReducer::SimplifyBranch().
TrySimplifyCompareZero()
std::optional<SimplifiedCondition> v8::internal::compiler::anonymous_namespace{machine-operator-reducer.cc}::TrySimplifyCompareZero (Node * cond)
Definition at line 2801 of file machine-operator-reducer.cc.
                                                                    {
  bool is_inverted = false;
  bool changed = false;
  std::optional<Node*> new_cond;
  while ((new_cond = TryGetInvertedCondition(cond)).has_value()) {
    cond = *new_cond;
    is_inverted = !is_inverted;
    changed = true;
  }
  if (changed) {
    return SimplifiedCondition{cond, is_inverted};
  } else {
    return {};
  }
}
References TryGetInvertedCondition().
Referenced by v8::internal::compiler::MachineOperatorReducer::SimplifyBranch().