v8_inspector::anonymous_namespace{v8-stack-trace-impl.cc} Namespace Reference
Functions
std::vector< std::shared_ptr< StackFrame > > toFramesVector (V8Debugger *debugger, v8::Local< v8::StackTrace > v8StackTrace, int maxStackSize)
std::unique_ptr< protocol::Runtime::StackTrace > buildInspectorObjectCommon (V8Debugger *debugger, const std::vector< std::shared_ptr< StackFrame >> &frames, const String16 &description, const std::shared_ptr< AsyncStackTrace > &asyncParent, const V8StackTraceId &externalParent, int maxAsyncDepth)
Variables
static const char kId [] = `id`
static const char kDebuggerId [] = `debuggerId`
static const char kShouldPause [] = `shouldPause`
static const v8::StackTrace::StackTraceOptions stackTraceOptions
Function Documentation
buildInspectorObjectCommon()
std::unique_ptr<protocol::Runtime::StackTrace> v8_inspector::anonymous_namespace{v8-stack-trace-impl.cc}::buildInspectorObjectCommon (V8Debugger * debugger, const std::vector< std::shared_ptr< StackFrame >> & frames, const String16 & description, const std::shared_ptr< AsyncStackTrace > & asyncParent, const V8StackTraceId & externalParent, int maxAsyncDepth)
Definition at line 56 of file v8-stack-trace-impl.cc.
                                                             {
  if (asyncParent && frames.empty() &&
      description == asyncParent->description()) {
    return asyncParent->buildInspectorObject(debugger, maxAsyncDepth);
  }
  auto inspectorFrames =
      std::make_unique<protocol::Array<protocol::Runtime::CallFrame>>();
  for (const std::shared_ptr<StackFrame>& frame : frames) {
    V8InspectorClient* client = nullptr;
    if (debugger && debugger->inspector())
      client = debugger->inspector()->client();
    inspectorFrames->emplace_back(frame->buildInspectorObject(client));
  }
  std::unique_ptr<protocol::Runtime::StackTrace> stackTrace =
      protocol::Runtime::StackTrace::create()
          .setCallFrames(std::move(inspectorFrames))
          .build();
  if (!description.isEmpty()) stackTrace->setDescription(description);
  if (asyncParent) {
    if (maxAsyncDepth > 0) {
      stackTrace->setParent(
          asyncParent->buildInspectorObject(debugger, maxAsyncDepth - 1));
    } else if (debugger) {
      stackTrace->setParentId(
          protocol::Runtime::StackTraceId::create()
              .setId(stackTraceIdToString(
                  AsyncStackTrace::store(debugger, asyncParent)))
              .build());
    }
  }
  if (!externalParent.IsInvalid()) {
    stackTrace->setParentId(
        protocol::Runtime::StackTraceId::create()
            .setId(stackTraceIdToString(externalParent.id))
            .setDebuggerId(
                internal::V8DebuggerId(externalParent.debugger_id).toString())
            .build());
  }
  return stackTrace;
}
References v8_inspector::V8InspectorImpl::client(), v8_inspector::V8StackTraceId::debugger_id, v8_inspector::V8StackTraceId::id, v8_inspector::V8Debugger::inspector(), v8_inspector::String16::isEmpty(), v8_inspector::V8StackTraceId::IsInvalid(), v8_inspector::stackTraceIdToString(), v8_inspector::AsyncStackTrace::store(), and v8_inspector::internal::V8DebuggerId::toString().
Referenced by v8_inspector::AsyncStackTrace::buildInspectorObject(), and v8_inspector::V8StackTraceImpl::buildInspectorObjectImpl().
toFramesVector()
std::vector<std::shared_ptr<StackFrame> > v8_inspector::anonymous_namespace{v8-stack-trace-impl.cc}::toFramesVector (V8Debugger * debugger, v8::Local< v8::StackTrace > v8StackTrace, int maxStackSize)
Definition at line 37 of file v8-stack-trace-impl.cc.
                      {
  DCHECK(debugger->isolate()->InContext());
  int frameCount = std::min(v8StackTrace->GetFrameCount(), maxStackSize);
  TRACE_EVENT1(
      TRACE_DISABLED_BY_DEFAULT("v8.inspector") "," TRACE_DISABLED_BY_DEFAULT(
          "v8.stack_trace"),
      "toFramesVector", "frameCount", frameCount);
  std::vector<std::shared_ptr<StackFrame>> frames(frameCount);
  for (int i = 0; i < frameCount; ++i) {
    frames[i] =
        debugger->symbolize(v8StackTrace->GetFrame(debugger->isolate(), i));
  }
  return frames;
}
References DCHECK, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::Isolate::InContext(), v8_inspector::V8Debugger::isolate(), v8_inspector::V8Debugger::symbolize(), TRACE_DISABLED_BY_DEFAULT, and TRACE_EVENT1.
Referenced by v8_inspector::AsyncStackTrace::capture(), and v8_inspector::V8StackTraceImpl::create().
Variable Documentation
kDebuggerId
const char v8_inspector::anonymous_namespace{v8-stack-trace-impl.cc}::kDebuggerId[] = `debuggerId` [static]
Definition at line 29 of file v8-stack-trace-impl.cc.
Referenced by v8_inspector::V8StackTraceId::ToString(), and v8_inspector::V8StackTraceId::V8StackTraceId().
kId
const char v8_inspector::anonymous_namespace{v8-stack-trace-impl.cc}::kId[] = `id` [static]
Definition at line 28 of file v8-stack-trace-impl.cc.
Referenced by v8::internal::anonymous_namespace{debug-wasm-objects.cc}::IndexedDebugProxy< T, id, Provider >::Create(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::GetOrCreateInstanceProxy(), v8_inspector::V8StackTraceId::ToString(), and v8_inspector::V8StackTraceId::V8StackTraceId().
kShouldPause
const char v8_inspector::anonymous_namespace{v8-stack-trace-impl.cc}::kShouldPause[] = `shouldPause` [static]
Definition at line 30 of file v8-stack-trace-impl.cc.
Referenced by v8_inspector::V8StackTraceId::ToString(), and v8_inspector::V8StackTraceId::V8StackTraceId().
stackTraceOptions
const v8::StackTrace::StackTraceOptions v8_inspector::anonymous_namespace{v8-stack-trace-impl.cc}::stackTraceOptions [static]
Initial value:
=
    static_cast<v8::StackTrace::StackTraceOptions>(
        v8::StackTrace::kDetailed |
        v8::StackTrace::kExposeFramesAcrossSecurityOrigins)
Definition at line 32 of file v8-stack-trace-impl.cc.
Referenced by v8_inspector::AsyncStackTrace::capture(), and v8_inspector::V8StackTraceImpl::capture().