v8::internal::anonymous_namespace{builtins-intl.cc} Namespace Reference
Functions
DirectHandle< JSFunction > CreateBoundFunction (Isolate *isolate, DirectHandle< JSObject > object, Builtin builtin, int len)
template<class T >
Tagged< Object > LegacyFormatConstructor (BuiltinArguments args, Isolate *isolate, v8::Isolate::UseCounterFeature feature, DirectHandle< JSAny > constructor, const char *method_name)
Common code shared between DateTimeFormatConstructor and NumberFormatConstructor.
template<class T >
Tagged< Object > DisallowCallConstructor (BuiltinArguments args, Isolate *isolate, v8::Isolate::UseCounterFeature feature, const char *method_name)
Common code shared by ListFormat, RelativeTimeFormat, PluralRules, and Segmenter.
template<class T >
Tagged< Object > CallOrConstructConstructor (BuiltinArguments args, Isolate *isolate, const char *method_name)
Common code shared by Collator and V8BreakIterator.
Function Documentation
CallOrConstructConstructor()
template<class T >
Tagged<Object> v8::internal::anonymous_namespace{builtins-intl.cc}::CallOrConstructConstructor (BuiltinArguments args, Isolate * isolate, const char * method_name)
Common code shared by Collator and V8BreakIterator.
Definition at line 346 of file builtins-intl.cc.
                                                                   {
  DirectHandle<JSReceiver> new_target;
  if (IsUndefined(*args.new_target(), isolate)) {
    new_target = args.target();
  } else {
    new_target = Cast<JSReceiver>(args.new_target());
  }
  // [[Construct]]
  DirectHandle<JSFunction> target = args.target();
  DirectHandle<Object> locales = args.atOrUndefined(isolate, 1);
  DirectHandle<Object> options = args.atOrUndefined(isolate, 2);
  DirectHandle<Map> map;
  ASSIGN_RETURN_FAILURE_ON_EXCEPTION(
      isolate, map, JSFunction::GetDerivedMap(isolate, target, new_target));
  RETURN_RESULT_OR_FAILURE(isolate,
                           T::New(isolate, map, locales, options, method_name));
}
References v8::base::args, ASSIGN_RETURN_FAILURE_ON_EXCEPTION, v8::internal::JSFunction::GetDerivedMap(), v8::internal::anonymous_namespace{intl-objects.cc}::New(), and RETURN_RESULT_OR_FAILURE.
CreateBoundFunction()
DirectHandle<JSFunction> v8::internal::anonymous_namespace{builtins-intl.cc}::CreateBoundFunction (Isolate * isolate, DirectHandle< JSObject > object, Builtin builtin, int len)
Definition at line 212 of file builtins-intl.cc.
                                                                       {
  DirectHandle<NativeContext> native_context(
      isolate->context()->native_context(), isolate);
  DirectHandle<Context> context = isolate->factory()->NewBuiltinContext(
      native_context,
      static_cast<int>(Intl::BoundFunctionContextSlot::kLength));
  context->SetNoCell(
      static_cast<int>(Intl::BoundFunctionContextSlot::kBoundFunction),
      *object);
  DirectHandle<SharedFunctionInfo> info =
      isolate->factory()->NewSharedFunctionInfoForBuiltin(
          isolate->factory()->empty_string(), builtin, len, kAdapt);
  return Factory::JSFunctionBuilder{isolate, info, context}
      .set_map(isolate->strict_function_without_prototype_map())
      .Build();
}
References v8::internal::Isolate::context(), v8::internal::Isolate::factory(), v8::internal::kAdapt, v8::internal::Intl::kBoundFunction, v8::internal::Intl::kLength, v8::internal::native_context, v8::internal::Factory::NewBuiltinContext(), and v8::internal::Factory::NewSharedFunctionInfoForBuiltin().
Referenced by v8::internal::BUILTIN(), and v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeBind().
DisallowCallConstructor()
template<class T >
Tagged<Object> v8::internal::anonymous_namespace{builtins-intl.cc}::DisallowCallConstructor (BuiltinArguments args, Isolate * isolate, v8::Isolate::UseCounterFeature feature, const char * method_name)
Common code shared by ListFormat, RelativeTimeFormat, PluralRules, and Segmenter.
Definition at line 313 of file builtins-intl.cc.
                                                                {
  isolate->CountUsage(feature);
  // 1. If NewTarget is undefined, throw a TypeError exception.
  if (IsUndefined(*args.new_target(), isolate)) { // [[Call]]
    THROW_NEW_ERROR_RETURN_FAILURE(
        isolate, NewTypeError(MessageTemplate::kConstructorNotFunction,
                              isolate->factory()->NewStringFromAsciiChecked(
                                  method_name)));
  }
  // [[Construct]]
  DirectHandle<JSFunction> target = args.target();
  DirectHandle<JSReceiver> new_target = Cast<JSReceiver>(args.new_target());
  DirectHandle<Map> map;
  // 2. Let result be OrdinaryCreateFromConstructor(NewTarget,
  // "%<T>Prototype%").
  ASSIGN_RETURN_FAILURE_ON_EXCEPTION(
      isolate, map, JSFunction::GetDerivedMap(isolate, target, new_target));
  DirectHandle<Object> locales = args.atOrUndefined(isolate, 1);
  DirectHandle<Object> options = args.atOrUndefined(isolate, 2);
  // 3. Return New<T>(t, locales, options).
  RETURN_RESULT_OR_FAILURE(isolate, T::New(isolate, map, locales, options));
}
References v8::base::args, ASSIGN_RETURN_FAILURE_ON_EXCEPTION, v8::internal::Isolate::CountUsage(), v8::internal::Isolate::factory(), v8::internal::JSFunction::GetDerivedMap(), v8::internal::anonymous_namespace{intl-objects.cc}::New(), v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), RETURN_RESULT_OR_FAILURE, and THROW_NEW_ERROR_RETURN_FAILURE.
LegacyFormatConstructor()
template<class T >
Tagged<Object> v8::internal::anonymous_namespace{builtins-intl.cc}::LegacyFormatConstructor (BuiltinArguments args, Isolate * isolate, v8::Isolate::UseCounterFeature feature, DirectHandle< JSAny > constructor, const char * method_name)
Common code shared between DateTimeFormatConstructor and NumberFormatConstructor.
Definition at line 239 of file builtins-intl.cc.
                                                                {
  isolate->CountUsage(feature);
  DirectHandle<JSReceiver> new_target;
  // 1. If NewTarget is undefined, let newTarget be the active
  // function object, else let newTarget be NewTarget.
  if (IsUndefined(*args.new_target(), isolate)) {
    new_target = args.target();
  } else {
    new_target = Cast<JSReceiver>(args.new_target());
  }
  // [[Construct]]
  DirectHandle<JSFunction> target = args.target();
  DirectHandle<Object> locales = args.atOrUndefined(isolate, 1);
  DirectHandle<Object> options = args.atOrUndefined(isolate, 2);
  // 2. Let format be ? OrdinaryCreateFromConstructor(newTarget,
  // "%<T>Prototype%", ...).
  DirectHandle<Map> map;
  ASSIGN_RETURN_FAILURE_ON_EXCEPTION(
      isolate, map, JSFunction::GetDerivedMap(isolate, target, new_target));
  // 3. Perform ? Initialize<T>(Format, locales, options).
  DirectHandle<T> format;
  ASSIGN_RETURN_FAILURE_ON_EXCEPTION(
      isolate, format, T::New(isolate, map, locales, options, method_name));
  // 4. Let this be the this value.
  if (IsUndefined(*args.new_target(), isolate)) {
    DirectHandle<JSAny> receiver = args.receiver();
    // 5. If NewTarget is undefined and ? OrdinaryHasInstance(%<T>%, this)
    // is true, then Look up the intrinsic value that has been stored on
    // the context.
    DirectHandle<Object> ordinary_has_instance_obj;
    ASSIGN_RETURN_FAILURE_ON_EXCEPTION(
        isolate, ordinary_has_instance_obj,
        Object::OrdinaryHasInstance(isolate, constructor, receiver));
    if (Object::BooleanValue(*ordinary_has_instance_obj, isolate)) {
      if (!IsJSReceiver(*receiver)) {
        THROW_NEW_ERROR_RETURN_FAILURE(
            isolate, NewTypeError(MessageTemplate::kIncompatibleMethodReceiver,
                                  isolate->factory()->NewStringFromAsciiChecked(
                                      method_name),
                                  receiver));
      }
      DirectHandle<JSReceiver> rec = Cast<JSReceiver>(receiver);
      // a. Perform ? DefinePropertyOrThrow(this,
      // %Intl%.[[FallbackSymbol]], PropertyDescriptor{ [[Value]]: format,
      // [[Writable]]: false, [[Enumerable]]: false, [[Configurable]]: false }).
      PropertyDescriptor desc;
      desc.set_value(format);
      desc.set_writable(false);
      desc.set_enumerable(false);
      desc.set_configurable(false);
      Maybe<bool> success = JSReceiver::DefineOwnProperty(
          isolate, rec, isolate->factory()->intl_fallback_symbol(), &desc,
          Just(kThrowOnError));
      MAYBE_RETURN(success, ReadOnlyRoots(isolate).exception());
      CHECK(success.FromJust());
      // b. b. Return this.
      return *receiver;
    }
  }
  // 6. Return format.
  return *format;
}
References v8::base::args, ASSIGN_RETURN_FAILURE_ON_EXCEPTION, v8::internal::Object::BooleanValue(), CHECK, v8::internal::Isolate::CountUsage(), v8::internal::JSReceiver::DefineOwnProperty(), v8::internal::Isolate::factory(), v8::internal::format, v8::Maybe< T >::FromJust(), v8::internal::JSFunction::GetDerivedMap(), v8::Just(), v8::internal::kThrowOnError, MAYBE_RETURN, v8::internal::anonymous_namespace{intl-objects.cc}::New(), v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), v8::internal::Object::OrdinaryHasInstance(), v8::internal::PropertyDescriptor::set_configurable(), v8::internal::PropertyDescriptor::set_enumerable(), v8::internal::PropertyDescriptor::set_value(), v8::internal::PropertyDescriptor::set_writable(), and THROW_NEW_ERROR_RETURN_FAILURE.