cppgc::internal::anonymous_namespace{process-heap.cc} Namespace Reference
Functions
HeapRegistry::Storage & GetHeapRegistryStorage ()
Variables
v8::base::LazyMutex g_heap_registry_mutex = LAZY_MUTEX_INITIALIZER
Function Documentation
GetHeapRegistryStorage()
HeapRegistry::Storage& cppgc::internal::anonymous_namespace{process-heap.cc}::GetHeapRegistryStorage ()
Definition at line 25 of file process-heap.cc.
                                              {
  static v8::base::LazyInstance<HeapRegistry::Storage>::type heap_registry =
      LAZY_INSTANCE_INITIALIZER;
  return *heap_registry.Pointer();
}
References LAZY_INSTANCE_INITIALIZER.
Referenced by cppgc::internal::HeapRegistry::GetRegisteredHeapsForTesting(), cppgc::internal::HeapRegistry::RegisterHeap(), cppgc::internal::HeapRegistry::TryFromManagedPointer(), and cppgc::internal::HeapRegistry::UnregisterHeap().
Variable Documentation
g_heap_registry_mutex
v8::base::LazyMutex cppgc::internal::anonymous_namespace{process-heap.cc}::g_heap_registry_mutex = LAZY_MUTEX_INITIALIZER
Definition at line 23 of file process-heap.cc.
Referenced by cppgc::internal::HeapRegistry::RegisterHeap(), cppgc::internal::HeapRegistry::TryFromManagedPointer(), and cppgc::internal::HeapRegistry::UnregisterHeap().