v8::internal::wasm::anonymous_namespace{wasm-interpreter.cc} Namespace Reference
Functions
void NopFinalizer (const v8::WeakCallbackInfo< void > &data)
IndirectHandle< WasmInstanceObject > MakeWeak (Isolate *isolate, DirectHandle< WasmInstanceObject > instance_object)
std::optional< wasm::ValueType > GetWasmReturnTypeFromSignature (const FunctionSig *wasm_signature)
Function Documentation
GetWasmReturnTypeFromSignature()
std::optional<wasm::ValueType> v8::internal::wasm::anonymous_namespace{wasm-interpreter.cc}::GetWasmReturnTypeFromSignature (const FunctionSig * wasm_signature)
Definition at line 366 of file wasm-interpreter.cc.
                                       {
  if (wasm_signature->return_count() == 0) return {};
  DCHECK_EQ(wasm_signature->return_count(), 1);
  return wasm_signature->GetReturn(0);
}
References DCHECK_EQ, v8::internal::Signature< T >::GetReturn(), and v8::internal::Signature< T >::return_count().
Referenced by v8::internal::wasm::WasmBytecodeGenerator::DecodeInstruction().
MakeWeak()
IndirectHandle<WasmInstanceObject> v8::internal::wasm::anonymous_namespace{wasm-interpreter.cc}::MakeWeak (Isolate * isolate, DirectHandle< WasmInstanceObject > instance_object)
Definition at line 356 of file wasm-interpreter.cc.
                                                                        {
  Handle<WasmInstanceObject> weak_instance =
      isolate->global_handles()->Create<WasmInstanceObject>(*instance_object);
  Address* global_handle_location = weak_instance.location();
  GlobalHandles::MakeWeak(global_handle_location, global_handle_location,
                          &NopFinalizer, v8::WeakCallbackType::kParameter);
  return weak_instance;
}
References v8::internal::GlobalHandles::Create(), v8::internal::Isolate::global_handles(), v8::kParameter, v8::internal::HandleBase::location(), v8::internal::GlobalHandles::MakeWeak(), and NopFinalizer().
NopFinalizer()
void v8::internal::wasm::anonymous_namespace{wasm-interpreter.cc}::NopFinalizer (const v8::WeakCallbackInfo< void > & data)
Definition at line 350 of file wasm-interpreter.cc.
                                                        {
  Address* global_handle_location =
      reinterpret_cast<Address*>(data.GetParameter());
  GlobalHandles::Destroy(global_handle_location);
}
References v8::internal::GlobalHandles::Destroy(), and v8::WeakCallbackInfo< T >::GetParameter().
Referenced by MakeWeak().