v8_inspector::anonymous_namespace{v8-string-conversions.cc} Namespace Reference
Typedefs
using UChar = char16_t
using UChar32 = uint32_t
Enumerations
enum ConversionResult { conversionOK
, sourceExhausted
, targetExhausted
, sourceIllegal
 }
Functions
bool isASCII (UChar c)
int inlineUTF8SequenceLengthNonASCII (char b0)
int inlineUTF8SequenceLength (char b0)
ConversionResult convertUTF16ToUTF8 (const UChar **sourceStart, const UChar *sourceEnd, char **targetStart, char *targetEnd, bool strict)
static bool isLegalUTF8 (const unsigned char *source, int length)
static UChar32 readUTF8Sequence (const char *&sequence, size_t length)
ConversionResult convertUTF8ToUTF16 (const char **sourceStart, const char *sourceEnd, UChar **targetStart, UChar *targetEnd, bool *sourceAllASCII, bool strict)
static void putUTF8Triple (char *&buffer, UChar ch)
Variables
const UChar replacementCharacter = 0xFFFD
static const unsigned char firstByteMark [7]
static const UChar32 offsetsFromUTF8 [6]
Typedef Documentation
UChar
using v8_inspector::anonymous_namespace{v8-string-conversions.cc}::UChar = typedef char16_t
Definition at line 14 of file v8-string-conversions.cc.
UChar32
using v8_inspector::anonymous_namespace{v8-string-conversions.cc}::UChar32 = typedef uint32_t
Definition at line 15 of file v8-string-conversions.cc.
Enumeration Type Documentation
ConversionResult
enum v8_inspector::anonymous_namespace{v8-string-conversions.cc}::ConversionResult
Enumerator
conversionOK
sourceExhausted
targetExhausted
sourceIllegal
Definition at line 41 of file v8-string-conversions.cc.
                      {
  conversionOK, // conversion successful
  sourceExhausted, // partial character in source, but hit end
  targetExhausted, // insuff. room in target for conversion
  sourceIllegal // source sequence is illegal/malformed
};
Function Documentation
convertUTF16ToUTF8()
ConversionResult v8_inspector::anonymous_namespace{v8-string-conversions.cc}::convertUTF16ToUTF8 (const UChar ** sourceStart, const UChar * sourceEnd, char ** targetStart, char * targetEnd, bool strict)
Definition at line 48 of file v8-string-conversions.cc.
                                                                  {
  ConversionResult result = conversionOK;
  const UChar* source = *sourceStart;
  char* target = *targetStart;
  while (source < sourceEnd) {
    UChar32 ch;
    uint32_t bytesToWrite = 0;
    const UChar32 byteMask = 0xBF;
    const UChar32 byteMark = 0x80;
    const UChar* oldSource =
        source; // In case we have to back up because of target overflow.
    ch = static_cast<uint16_t>(*source++);
    // If we have a surrogate pair, convert to UChar32 first.
    if (ch >= 0xD800 && ch <= 0xDBFF) {
      // If the 16 bits following the high surrogate are in the source buffer...
      if (source < sourceEnd) {
        UChar32 ch2 = static_cast<uint16_t>(*source);
        // If it's a low surrogate, convert to UChar32.
        if (ch2 >= 0xDC00 && ch2 <= 0xDFFF) {
          ch = ((ch - 0xD800) << 10) + (ch2 - 0xDC00) + 0x0010000;
          ++source;
        } else if (strict) { // it's an unpaired high surrogate
          --source; // return to the illegal value itself
          result = sourceIllegal;
          break;
        }
      } else { // We don't have the 16 bits following the high surrogate.
        --source; // return to the high surrogate
        result = sourceExhausted;
        break;
      }
    } else if (strict) {
      // UTF-16 surrogate values are illegal in UTF-32
      if (ch >= 0xDC00 && ch <= 0xDFFF) {
        --source; // return to the illegal value itself
        result = sourceIllegal;
        break;
      }
    }
    // Figure out how many bytes the result will require
    if (ch < static_cast<UChar32>(0x80)) {
      bytesToWrite = 1;
    } else if (ch < static_cast<UChar32>(0x800)) {
      bytesToWrite = 2;
    } else if (ch < static_cast<UChar32>(0x10000)) {
      bytesToWrite = 3;
    } else if (ch < static_cast<UChar32>(0x110000)) {
      bytesToWrite = 4;
    } else {
      bytesToWrite = 3;
      ch = replacementCharacter;
    }
    target += bytesToWrite;
    if (target > targetEnd) {
      source = oldSource; // Back up source pointer!
      target -= bytesToWrite;
      result = targetExhausted;
      break;
    }
    switch (bytesToWrite) {
      case 4:
        *--target = static_cast<char>((ch | byteMark) & byteMask);
        ch >>= 6;
        [[fallthrough]];
      case 3:
        *--target = static_cast<char>((ch | byteMark) & byteMask);
        ch >>= 6;
        [[fallthrough]];
      case 2:
        *--target = static_cast<char>((ch | byteMark) & byteMask);
        ch >>= 6;
        [[fallthrough]];
      case 1:
        *--target = static_cast<char>(ch | firstByteMark[bytesToWrite]);
    }
    target += bytesToWrite;
  }
  *sourceStart = source;
  *targetStart = target;
  return result;
}
References conversionOK, firstByteMark, replacementCharacter, v8::base::internal::result, sourceExhausted, sourceIllegal, and targetExhausted.
Referenced by v8_inspector::UTF16ToUTF8().
convertUTF8ToUTF16()
ConversionResult v8_inspector::anonymous_namespace{v8-string-conversions.cc}::convertUTF8ToUTF16 (const char ** sourceStart, const char * sourceEnd, UChar ** targetStart, UChar * targetEnd, bool * sourceAllASCII, bool strict)
Definition at line 262 of file v8-string-conversions.cc.
                                                 {
  ConversionResult result = conversionOK;
  const char* source = *sourceStart;
  UChar* target = *targetStart;
  UChar orAllData = 0;
  while (source < sourceEnd) {
    int utf8SequenceLength = inlineUTF8SequenceLength(*source);
    if (sourceEnd - source < utf8SequenceLength) {
      result = sourceExhausted;
      break;
    }
    // Do this check whether lenient or strict
    if (!isLegalUTF8(reinterpret_cast<const unsigned char*>(source),
                     utf8SequenceLength)) {
      result = sourceIllegal;
      break;
    }
    UChar32 character = readUTF8Sequence(source, utf8SequenceLength);
    if (target >= targetEnd) {
      source -= utf8SequenceLength; // Back up source pointer!
      result = targetExhausted;
      break;
    }
    if (U_IS_BMP(character)) {
      // UTF-16 surrogate values are illegal in UTF-32
      if (U_IS_SURROGATE(character)) {
        if (strict) {
          source -= utf8SequenceLength; // return to the illegal value itself
          result = sourceIllegal;
          break;
        }
        *target++ = replacementCharacter;
        orAllData |= replacementCharacter;
      } else {
        *target++ = static_cast<UChar>(character); // normal case
        orAllData |= character;
      }
    } else if (U_IS_SUPPLEMENTARY(character)) {
      // target is a character in range 0xFFFF - 0x10FFFF
      if (target + 1 >= targetEnd) {
        source -= utf8SequenceLength; // Back up source pointer!
        result = targetExhausted;
        break;
      }
      *target++ = U16_LEAD(character);
      *target++ = U16_TRAIL(character);
      orAllData = 0xFFFF;
    } else {
      if (strict) {
        source -= utf8SequenceLength; // return to the start
        result = sourceIllegal;
        break; // Bail out; shouldn't continue
      } else {
        *target++ = replacementCharacter;
        orAllData |= replacementCharacter;
      }
    }
  }
  *sourceStart = source;
  *targetStart = target;
  if (sourceAllASCII) *sourceAllASCII = !(orAllData & ~0x7F);
  return result;
}
References v8::internal::character, conversionOK, inlineUTF8SequenceLength(), isLegalUTF8(), readUTF8Sequence(), replacementCharacter, v8::base::internal::result, sourceExhausted, sourceIllegal, targetExhausted, U16_LEAD, U16_TRAIL, U_IS_BMP, U_IS_SUPPLEMENTARY, and U_IS_SURROGATE.
Referenced by v8_inspector::UTF8ToUTF16().
inlineUTF8SequenceLength()
int v8_inspector::anonymous_namespace{v8-string-conversions.cc}::inlineUTF8SequenceLength (char b0) [inline]
Definition at line 29 of file v8-string-conversions.cc.
                                             {
  return isASCII(b0) ? 1 : inlineUTF8SequenceLengthNonASCII(b0);
}
References inlineUTF8SequenceLengthNonASCII(), and isASCII().
Referenced by convertUTF8ToUTF16().
inlineUTF8SequenceLengthNonASCII()
int v8_inspector::anonymous_namespace{v8-string-conversions.cc}::inlineUTF8SequenceLengthNonASCII (char b0) [inline]
Definition at line 21 of file v8-string-conversions.cc.
                                                     {
  if ((b0 & 0xC0) != 0xC0) return 0;
  if ((b0 & 0xE0) == 0xC0) return 2;
  if ((b0 & 0xF0) == 0xE0) return 3;
  if ((b0 & 0xF8) == 0xF0) return 4;
  return 0;
}
Referenced by inlineUTF8SequenceLength().
isASCII()
bool v8_inspector::anonymous_namespace{v8-string-conversions.cc}::isASCII (UChar c)
Definition at line 17 of file v8-string-conversions.cc.
{ return !(c & ~0x7F); }
Referenced by inlineUTF8SequenceLength().
isLegalUTF8()
static bool v8_inspector::anonymous_namespace{v8-string-conversions.cc}::isLegalUTF8 (const unsigned char * source, int length) [static]
Definition at line 178 of file v8-string-conversions.cc.
                                                                 {
  unsigned char a;
  const unsigned char* srcptr = source + length;
  switch (length) {
    default:
      return false;
    // Everything else falls through when "true"...
    case 4:
      if ((a = (*--srcptr)) < 0x80 || a > 0xBF) return false;
      [[fallthrough]];
    case 3:
      if ((a = (*--srcptr)) < 0x80 || a > 0xBF) return false;
      [[fallthrough]];
    case 2:
      if ((a = (*--srcptr)) > 0xBF) return false;
      // no fall-through in this inner switch
      switch (*source) {
        case 0xE0:
          if (a < 0xA0) return false;
          break;
        case 0xED:
          if (a > 0x9F) return false;
          break;
        case 0xF0:
          if (a < 0x90) return false;
          break;
        case 0xF4:
          if (a > 0x8F) return false;
          break;
        default:
          if (a < 0x80) return false;
      }
      [[fallthrough]];
    case 1:
      if (*source >= 0x80 && *source < 0xC2) return false;
  }
  if (*source > 0xF4) return false;
  return true;
}
References v8::internal::length.
Referenced by convertUTF8ToUTF16().
putUTF8Triple()
static void v8_inspector::anonymous_namespace{v8-string-conversions.cc}::putUTF8Triple (char *& buffer, UChar ch) [inline], [static]
Definition at line 336 of file v8-string-conversions.cc.
                                                          {
  *buffer++ = static_cast<char>(((ch >> 12) & 0x0F) | 0xE0);
  *buffer++ = static_cast<char>(((ch >> 6) & 0x3F) | 0x80);
  *buffer++ = static_cast<char>((ch & 0x3F) | 0x80);
}
Referenced by v8_inspector::UTF16ToUTF8().
readUTF8Sequence()
static UChar32 v8_inspector::anonymous_namespace{v8-string-conversions.cc}::readUTF8Sequence (const char *& sequence, size_t length) [inline], [static]
Definition at line 230 of file v8-string-conversions.cc.
                                                                             {
  UChar32 character = 0;
  // The cases all fall through.
  switch (length) {
    case 6:
      character += static_cast<unsigned char>(*sequence++);
      character <<= 6;
      [[fallthrough]];
    case 5:
      character += static_cast<unsigned char>(*sequence++);
      character <<= 6;
      [[fallthrough]];
    case 4:
      character += static_cast<unsigned char>(*sequence++);
      character <<= 6;
      [[fallthrough]];
    case 3:
      character += static_cast<unsigned char>(*sequence++);
      character <<= 6;
      [[fallthrough]];
    case 2:
      character += static_cast<unsigned char>(*sequence++);
      character <<= 6;
      [[fallthrough]];
    case 1:
      character += static_cast<unsigned char>(*sequence++);
  }
  return character - offsetsFromUTF8[length - 1];
}
References v8::internal::character, v8::internal::length, and offsetsFromUTF8.
Referenced by convertUTF8ToUTF16().
Variable Documentation
firstByteMark
const unsigned char v8_inspector::anonymous_namespace{v8-string-conversions.cc}::firstByteMark[7] [static]
Initial value:
= {0x00, 0x00, 0xC0, 0xE0,
                                               0xF0, 0xF8, 0xFC}
Definition at line 38 of file v8-string-conversions.cc.
Referenced by convertUTF16ToUTF8().
offsetsFromUTF8
const UChar32 v8_inspector::anonymous_namespace{v8-string-conversions.cc}::offsetsFromUTF8[6] [static]
Initial value:
= {0x00000000UL,
                                           0x00003080UL,
                                           0x000E2080UL,
                                           0x03C82080UL,
                                           static_cast<UChar32>(0xFA082080UL),
                                           static_cast<UChar32>(0x82082080UL)}
Definition at line 223 of file v8-string-conversions.cc.
Referenced by readUTF8Sequence().
replacementCharacter
const UChar v8_inspector::anonymous_namespace{v8-string-conversions.cc}::replacementCharacter = 0xFFFD
Definition at line 19 of file v8-string-conversions.cc.
Referenced by convertUTF16ToUTF8(), convertUTF8ToUTF16(), and v8_inspector::UTF16ToUTF8().