v8::internal::anonymous_namespace{wasm-debug.cc} Namespace Reference
Functions
int FindNextBreakablePosition (wasm::NativeModule *native_module, int func_index, int offset_in_func)
void SetBreakOnEntryFlag (Tagged< Script > script, bool enabled)
int GetBreakpointPos (Isolate *isolate, Tagged< Object > break_point_info_or_undef)
int FindBreakpointInfoInsertPos (Isolate *isolate, DirectHandle< FixedArray > breakpoint_infos, int position)
bool CheckBreakPoint (Isolate *isolate, DirectHandle< BreakPoint > break_point, StackFrameId frame_id)
Function Documentation
CheckBreakPoint()
bool v8::internal::anonymous_namespace{wasm-debug.cc}::CheckBreakPoint (Isolate * isolate, DirectHandle< BreakPoint > break_point, StackFrameId frame_id)
Definition at line 1251 of file wasm-debug.cc.
                                            {
  if (break_point->condition()->length() == 0) return true;
  HandleScope scope(isolate);
  DirectHandle<String> condition(break_point->condition(), isolate);
  DirectHandle<Object> result;
  // The Wasm engine doesn't perform any sort of inlining.
  const int inlined_jsframe_index = 0;
  const bool throw_on_side_effect = false;
  if (!DebugEvaluate::Local(isolate, frame_id, inlined_jsframe_index, condition,
                            throw_on_side_effect)
           .ToHandle(&result)) {
    isolate->clear_exception();
    return false;
  }
  return Object::BooleanValue(*result, isolate);
}
References v8::internal::Object::BooleanValue(), v8::internal::Isolate::clear_exception(), v8::internal::DebugEvaluate::Local(), v8::base::internal::result, and v8::anonymous_namespace{api.cc}::ToHandle().
Referenced by v8::internal::WasmScript::CheckBreakPoints().
FindBreakpointInfoInsertPos()
int v8::internal::anonymous_namespace{wasm-debug.cc}::FindBreakpointInfoInsertPos (Isolate * isolate, DirectHandle< FixedArray > breakpoint_infos, int position)
Definition at line 1015 of file wasm-debug.cc.
                                              {
  // Find insert location via binary search, taking care of undefined values on
  // the right. {position} is either {kOnEntryBreakpointPosition} (which is -1),
  // or positive.
  DCHECK(position == WasmScript::kOnEntryBreakpointPosition || position > 0);
  int left = 0; // inclusive
  int right = breakpoint_infos->length(); // exclusive
  while (right - left > 1) {
    int mid = left + (right - left) / 2;
    Tagged<Object> mid_obj = breakpoint_infos->get(mid);
    if (GetBreakpointPos(isolate, mid_obj) <= position) {
      left = mid;
    } else {
      right = mid;
    }
  }
  int left_pos = GetBreakpointPos(isolate, breakpoint_infos->get(left));
  return left_pos < position ? left + 1 : left;
}
References v8::internal::DCHECK(), GetBreakpointPos(), and v8::internal::WasmScript::kOnEntryBreakpointPosition.
Referenced by v8::internal::WasmScript::AddBreakpointToInfo(), v8::internal::WasmScript::CheckBreakPoints(), and v8::internal::WasmScript::ClearBreakPoint().
FindNextBreakablePosition()
int v8::internal::anonymous_namespace{wasm-debug.cc}::FindNextBreakablePosition (wasm::NativeModule * native_module, int func_index, int offset_in_func)
Definition at line 903 of file wasm-debug.cc.
                                                  {
  Zone zone{wasm::GetWasmEngine()->allocator(), ZONE_NAME};
  wasm::BodyLocalDecls locals;
  const uint8_t* module_start = native_module->wire_bytes().begin();
  const wasm::WasmFunction& func =
      native_module->module()->functions[func_index];
  wasm::BytecodeIterator iterator(module_start + func.code.offset(),
                                  module_start + func.code.end_offset(),
                                  &locals, &zone);
  DCHECK_LT(0, locals.encoded_size);
  if (offset_in_func < 0) return 0;
  for (; iterator.has_next(); iterator.next()) {
    if (iterator.pc_offset() < static_cast<uint32_t>(offset_in_func)) continue;
    if (!wasm::WasmOpcodes::IsBreakable(iterator.current())) continue;
    return static_cast<int>(iterator.pc_offset());
  }
  return 0;
}
References v8::internal::wasm::WasmEngine::allocator(), v8::base::Vector< T >::begin(), v8::internal::wasm::WasmFunction::code, v8::internal::wasm::BytecodeIterator::current(), DCHECK_LT, v8::internal::wasm::BodyLocalDecls::encoded_size, v8::internal::wasm::WireBytesRef::end_offset(), v8::internal::wasm::WasmModule::functions, v8::internal::wasm::GetWasmEngine(), v8::internal::wasm::BytecodeIterator::has_next(), v8::internal::wasm::WasmOpcodes::IsBreakable(), v8::internal::wasm::NativeModule::module(), v8::internal::wasm::BytecodeIterator::next(), v8::internal::wasm::WireBytesRef::offset(), v8::internal::wasm::NativeModule::wire_bytes(), and ZONE_NAME.
Referenced by v8::internal::WasmScript::SetBreakPoint(), and v8::internal::WasmScript::SetBreakPointOnFirstBreakableForFunction().
GetBreakpointPos()
int v8::internal::anonymous_namespace{wasm-debug.cc}::GetBreakpointPos (Isolate * isolate, Tagged< Object > break_point_info_or_undef)
Definition at line 1009 of file wasm-debug.cc.
                                                               {
  if (IsUndefined(break_point_info_or_undef, isolate)) return kMaxInt;
  return Cast<BreakPointInfo>(break_point_info_or_undef)->source_position();
}
References v8::internal::kMaxInt.
Referenced by v8::internal::WasmScript::AddBreakpointToInfo(), and FindBreakpointInfoInsertPos().
SetBreakOnEntryFlag()
void v8::internal::anonymous_namespace{wasm-debug.cc}::SetBreakOnEntryFlag (Tagged< Script > script, bool enabled)
Definition at line 923 of file wasm-debug.cc.
                                                              {
  if (script->break_on_entry() == enabled) return;
  script->set_break_on_entry(enabled);
  // Update the "break_on_entry" flag on all live instances.
  i::Tagged<i::WeakArrayList> weak_instance_list =
      script->wasm_weak_instance_list();
  i::Isolate* isolate = Isolate::Current();
  for (int i = 0; i < weak_instance_list->length(); ++i) {
    if (weak_instance_list->Get(i).IsCleared()) continue;
    i::Tagged<i::WasmInstanceObject> instance = i::Cast<i::WasmInstanceObject>(
        weak_instance_list->Get(i).GetHeapObject());
    instance->trusted_data(isolate)->set_break_on_entry(enabled);
  }
}
References v8::internal::Isolate::Current(), v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObject(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::TaggedImpl< kRefType, StorageType >::IsCleared(), and v8::internal::script.
Referenced by v8::internal::WasmScript::ClearAllBreakpoints(), v8::internal::WasmScript::ClearBreakPoint(), and v8::internal::WasmScript::SetInstrumentationBreakpoint().