v8_inspector::anonymous_namespace{value-mirror.cc} Namespace Reference
Classes
class ValueMirrorBase
class PrimitiveValueMirror
class NumberMirror
class BigIntMirror
class SymbolMirror
class LocationMirror
class FunctionMirror
struct EntryMirror
class PreviewPropertyAccumulator
class ObjectMirror
Enumerations
enum AbbreviateMode { kMiddle
, kEnd
 }
Functions
V8InspectorClient * clientFor (v8::Local< v8::Context > context)
V8InternalValueType v8InternalValueTypeFrom (v8::Local< v8::Context > context, v8::Local< v8::Value > value)
String16 abbreviateString (const String16 &value, AbbreviateMode mode)
String16 descriptionForSymbol (v8::Local< v8::Context > context, v8::Local< v8::Symbol > symbol)
String16 descriptionForBigInt (v8::Local< v8::Context > context, v8::Local< v8::BigInt > value)
String16 descriptionForPrimitiveType (v8::Local< v8::Context > context, v8::Local< v8::Value > value)
String16 descriptionForRegExp (v8::Isolate *isolate, v8::Local< v8::RegExp > value)
v8::Local< v8::Function > deepBoundFunction (v8::Local< v8::Function > function)
v8::MaybeLocal< v8::Value > getErrorProperty (v8::Local< v8::Context > context, v8::Local< v8::Object > object, v8::Local< v8::String > name)
String16 descriptionForError (v8::Local< v8::Context > context, v8::Local< v8::Object > object)
String16 descriptionForObject (v8::Isolate *isolate, v8::Local< v8::Object > object)
String16 descriptionForProxy (v8::Isolate *isolate, v8::Local< v8::Proxy > proxy)
String16 descriptionForDate (v8::Local< v8::Context > context, v8::Local< v8::Date > date)
String16 descriptionForScopeList (v8::Local< v8::Array > list)
String16 descriptionForScope (v8::Local< v8::Context > context, v8::Local< v8::Object > object)
String16 descriptionForCollection (v8::Isolate *isolate, v8::Local< v8::Object > object, size_t length)
String16 descriptionForEntry (v8::Local< v8::Context > context, v8::Local< v8::Object > object)
String16 descriptionForFunction (v8::Local< v8::Function > value)
String16 descriptionForPrivateMethodList (v8::Local< v8::Array > list)
String16 descriptionForPrivateMethod (v8::Local< v8::Context > context, v8::Local< v8::Object > object)
String16 descriptionForNumber (v8::Local< v8::Number > value, bool *unserializable)
bool isArrayLike (v8::Local< v8::Context > context, v8::Local< v8::Object > object, size_t *length)
bool getPropertiesForPreview (v8::Local< v8::Context > context, v8::Local< v8::Object > object, int *nameLimit, int *indexLimit, bool *overflow, std::vector< PropertyMirror > *properties)
void getInternalPropertiesForPreview (v8::Local< v8::Context > context, v8::Local< v8::Object > object, int *nameLimit, bool *overflow, std::vector< InternalPropertyMirror > *properties)
void getPrivatePropertiesForPreview (v8::Local< v8::Context > context, v8::Local< v8::Object > object, int *nameLimit, bool *overflow, protocol::Array< PropertyPreview > *privateProperties)
void nativeGetterCallback (const v8::FunctionCallbackInfo< v8::Value > &info)
std::unique_ptr< ValueMirror > createNativeGetter (v8::Local< v8::Context > context, v8::Local< v8::Value > object, v8::Local< v8::Name > name)
void nativeSetterCallback (const v8::FunctionCallbackInfo< v8::Value > &info)
std::unique_ptr< ValueMirror > createNativeSetter (v8::Local< v8::Context > context, v8::Local< v8::Value > object, v8::Local< v8::Name > name)
bool doesAttributeHaveObservableSideEffectOnGet (v8::Local< v8::Context > context, v8::Local< v8::Object > object, v8::Local< v8::Name > name)
Variables
const size_t kWasmPageSize = 64 * 1024
Enumeration Type Documentation
AbbreviateMode
enum v8_inspector::anonymous_namespace{value-mirror.cc}::AbbreviateMode
Enumerator
kMiddle
kEnd
Definition at line 190 of file value-mirror.cc.
{ kMiddle, kEnd };
Function Documentation
abbreviateString()
String16 v8_inspector::anonymous_namespace{value-mirror.cc}::abbreviateString (const String16 & value, AbbreviateMode mode)
Definition at line 192 of file value-mirror.cc.
                                                                      {
  const size_t maxLength = 100;
  if (value.length() <= maxLength) return value;
  UChar ellipsis = static_cast<UChar>(0x2026);
  if (mode == kMiddle) {
    return String16::concat(
        value.substring(0, maxLength / 2), String16(&ellipsis, 1),
        value.substring(value.length() - maxLength / 2 + 1));
  }
  return String16::concat(value.substring(0, maxLength - 1), ellipsis);
}
References v8_inspector::String16::concat(), kMiddle, mode(), and v8::internal::value.
Referenced by v8_inspector::anonymous_namespace{value-mirror.cc}::BigIntMirror::buildEntryPreview(), v8_inspector::anonymous_namespace{value-mirror.cc}::PrimitiveValueMirror::buildPropertyPreview(), v8_inspector::anonymous_namespace{value-mirror.cc}::ObjectMirror::buildPropertyPreview(), v8_inspector::anonymous_namespace{value-mirror.cc}::BigIntMirror::buildPropertyPreview(), v8_inspector::anonymous_namespace{value-mirror.cc}::SymbolMirror::buildPropertyPreview(), and v8_inspector::anonymous_namespace{value-mirror.cc}::BigIntMirror::buildRemoteObject().
clientFor()
V8InspectorClient* v8_inspector::anonymous_namespace{value-mirror.cc}::clientFor (v8::Local< v8::Context > context)
Definition at line 173 of file value-mirror.cc.
                                                         {
  return static_cast<V8InspectorImpl*>(
             v8::debug::GetInspector(v8::Isolate::GetCurrent()))
      ->client();
}
References v8::Isolate::GetCurrent(), and v8::debug::GetInspector().
Referenced by v8_inspector::anonymous_namespace{value-mirror.cc}::ObjectMirror::buildDeepSerializedValue(), v8_inspector::clientMirror(), v8_inspector::ValueMirror::create(), and getPropertiesForPreview().
createNativeGetter()
std::unique_ptr<ValueMirror> v8_inspector::anonymous_namespace{value-mirror.cc}::createNativeGetter (v8::Local< v8::Context > context, v8::Local< v8::Value > object, v8::Local< v8::Name > name)
Definition at line 1418 of file value-mirror.cc.
                                                                      {
  v8::Isolate* isolate = v8::Isolate::GetCurrent();
  v8::TryCatch tryCatch(isolate);
  v8::Local<v8::Object> data = v8::Object::New(isolate);
  if (data->Set(context, toV8String(isolate, "name"), name).IsNothing()) {
    return nullptr;
  }
  if (data->Set(context, toV8String(isolate, "object"), object).IsNothing()) {
    return nullptr;
  }
  v8::Local<v8::Function> function;
  if (!v8::Function::New(context, nativeGetterCallback, data, 0,
                         v8::ConstructorBehavior::kThrow)
           .ToLocal(&function)) {
    return nullptr;
  }
  return ValueMirror::create(context, function);
}
References v8_inspector::ValueMirror::create(), v8::Isolate::GetCurrent(), v8::kThrow, name, nativeGetterCallback(), v8::Object::New(), v8::Function::New(), v8::Object::Set(), and v8_inspector::toV8String().
Referenced by v8_inspector::ValueMirror::getProperties().
createNativeSetter()
std::unique_ptr<ValueMirror> v8_inspector::anonymous_namespace{value-mirror.cc}::createNativeSetter (v8::Local< v8::Context > context, v8::Local< v8::Value > object, v8::Local< v8::Name > name)
Definition at line 1460 of file value-mirror.cc.
                                                                      {
  v8::Isolate* isolate = v8::Isolate::GetCurrent();
  v8::TryCatch tryCatch(isolate);
  v8::Local<v8::Object> data = v8::Object::New(isolate);
  if (data->Set(context, toV8String(isolate, "name"), name).IsNothing()) {
    return nullptr;
  }
  if (data->Set(context, toV8String(isolate, "object"), object).IsNothing()) {
    return nullptr;
  }
  v8::Local<v8::Function> function;
  if (!v8::Function::New(context, nativeSetterCallback, data, 1,
                         v8::ConstructorBehavior::kThrow)
           .ToLocal(&function)) {
    return nullptr;
  }
  return ValueMirror::create(context, function);
}
References v8_inspector::ValueMirror::create(), v8::Isolate::GetCurrent(), v8::kThrow, name, nativeSetterCallback(), v8::Object::New(), v8::Function::New(), v8::Object::Set(), and v8_inspector::toV8String().
Referenced by v8_inspector::ValueMirror::getProperties().
deepBoundFunction()
v8::Local<v8::Function> v8_inspector::anonymous_namespace{value-mirror.cc}::deepBoundFunction (v8::Local< v8::Function > function)
Definition at line 253 of file value-mirror.cc.
                                                                    {
  while (function->GetBoundFunction()->IsFunction())
    function = function->GetBoundFunction().As<v8::Function>();
  return function;
}
Referenced by getErrorProperty(), and v8_inspector::ValueMirror::getProperties().
descriptionForBigInt()
String16 v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForBigInt (v8::Local< v8::Context > context, v8::Local< v8::BigInt > value)
Definition at line 213 of file value-mirror.cc.
                                                       {
  v8::Isolate* isolate = v8::Isolate::GetCurrent();
  v8::Local<v8::String> description =
      v8::debug::GetBigIntDescription(isolate, value);
  return toProtocolString(isolate, description);
}
References v8::debug::GetBigIntDescription(), v8::Isolate::GetCurrent(), v8_inspector::toProtocolString(), and v8::internal::value.
Referenced by v8_inspector::anonymous_namespace{value-mirror.cc}::BigIntMirror::buildEntryPreview(), v8_inspector::anonymous_namespace{value-mirror.cc}::BigIntMirror::buildPropertyPreview(), and v8_inspector::anonymous_namespace{value-mirror.cc}::BigIntMirror::buildRemoteObject().
descriptionForCollection()
String16 v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForCollection (v8::Isolate * isolate, v8::Local< v8::Object > object, size_t length)
Definition at line 397 of file value-mirror.cc.
                                                                           {
  String16 className = toProtocolString(isolate, object->GetConstructorName());
  return String16::concat(className, '(', String16::fromInteger(length), ')');
}
References v8_inspector::String16::concat(), v8_inspector::String16::fromInteger(), v8::Object::GetConstructorName(), v8::internal::length, and v8_inspector::toProtocolString().
Referenced by v8_inspector::clientMirror(), and v8_inspector::ValueMirror::create().
descriptionForDate()
String16 v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForDate (v8::Local< v8::Context > context, v8::Local< v8::Date > date)
Definition at line 373 of file value-mirror.cc.
                                                  {
  v8::Isolate* isolate = v8::Isolate::GetCurrent();
  v8::Local<v8::String> description = v8::debug::GetDateDescription(date);
  return toProtocolString(isolate, description);
}
References v8::internal::date, v8::Isolate::GetCurrent(), v8::debug::GetDateDescription(), and v8_inspector::toProtocolString().
Referenced by v8_inspector::ValueMirror::create().
descriptionForEntry()
String16 v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForEntry (v8::Local< v8::Context > context, v8::Local< v8::Object > object)
Definition at line 412 of file value-mirror.cc.
                                                       {
  v8::Isolate* isolate = v8::Isolate::GetCurrent();
  String16 key;
  v8::Local<v8::Value> tmp;
  if (object->GetRealNamedProperty(context, toV8String(isolate, "key"))
          .ToLocal(&tmp)) {
    auto wrapper = ValueMirror::create(context, tmp);
    if (wrapper) {
      std::unique_ptr<ObjectPreview> preview;
      int limit = 5;
      wrapper->buildEntryPreview(context, &limit, &limit, &preview);
      if (preview) {
        key = preview->getDescription(String16());
        if (preview->getType() == RemoteObject::TypeEnum::String) {
          key = String16::concat('\"', key, '\"');
        }
      }
    }
  }
  String16 value;
  if (object->GetRealNamedProperty(context, toV8String(isolate, "value"))
          .ToLocal(&tmp)) {
    auto wrapper = ValueMirror::create(context, tmp);
    if (wrapper) {
      std::unique_ptr<ObjectPreview> preview;
      int limit = 5;
      wrapper->buildEntryPreview(context, &limit, &limit, &preview);
      if (preview) {
        value = preview->getDescription(String16());
        if (preview->getType() == RemoteObject::TypeEnum::String) {
          value = String16::concat('\"', value, '\"');
        }
      }
    }
  }
  return key.length() ? ("{" + key + " => " + value + "}") : value;
}
References v8_inspector::String16::concat(), v8_inspector::ValueMirror::create(), v8::Isolate::GetCurrent(), v8::Object::GetRealNamedProperty(), v8::internal::key, v8_inspector::toV8String(), and v8::internal::value.
Referenced by v8_inspector::ValueMirror::create().
descriptionForError()
String16 v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForError (v8::Local< v8::Context > context, v8::Local< v8::Object > object)
Definition at line 303 of file value-mirror.cc.
                                                       {
  v8::Isolate* isolate = v8::Isolate::GetCurrent();
  v8::TryCatch tryCatch(isolate);
  String16 name = toProtocolString(isolate, object->GetConstructorName());
  {
    v8::Local<v8::Value> nameValue;
    if (getErrorProperty(context, object, toV8String(isolate, "name"))
            .ToLocal(&nameValue) &&
        nameValue->IsString()) {
      v8::Local<v8::String> nameString = nameValue.As<v8::String>();
      if (nameString->Length() > 0 &&
          !nameString->StringEquals(toV8String(isolate, "Error"))) {
        name = toProtocolString(isolate, nameString);
      }
    }
  }
  std::optional<String16> stack;
  {
    v8::Local<v8::Value> stackValue;
    if (getErrorProperty(context, object, toV8String(isolate, "stack"))
            .ToLocal(&stackValue) &&
        stackValue->IsString()) {
      String16 stackString =
          toProtocolString(isolate, stackValue.As<v8::String>());
      size_t pos = stackString.find("\n at ");
      if (pos != String16::kNotFound) {
        stack = stackString.substring(pos);
      }
    }
  }
  std::optional<String16> message;
  {
    v8::Local<v8::Value> messageValue;
    if (getErrorProperty(context, object, toV8String(isolate, "message"))
            .ToLocal(&messageValue) &&
        messageValue->IsString()) {
      String16 msg = toProtocolStringWithTypeCheck(isolate, messageValue);
      if (!msg.isEmpty()) message = msg;
    }
  }
  String16 description = name;
  if (message.has_value() && message->length() > 0) {
    description += ": " + *message;
  }
  if (stack.has_value() && stack->length() > 0) {
    description += *stack;
  }
  return description;
}
References v8::Local< T >::As(), v8_inspector::String16::find(), v8::Object::GetConstructorName(), v8::Isolate::GetCurrent(), getErrorProperty(), v8_inspector::String16::isEmpty(), v8::Value::IsString(), v8_inspector::String16::kNotFound, v8::String::Length(), name, v8::internal::stack, v8::String::StringEquals(), v8_inspector::String16::substring(), v8_inspector::toProtocolString(), v8_inspector::toProtocolStringWithTypeCheck(), and v8_inspector::toV8String().
Referenced by v8_inspector::clientMirror(), and v8_inspector::ValueMirror::create().
descriptionForFunction()
String16 v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForFunction (v8::Local< v8::Function > value)
Definition at line 453 of file value-mirror.cc.
                                                           {
  v8::Isolate* isolate = v8::Isolate::GetCurrent();
  v8::Local<v8::String> description = v8::debug::GetFunctionDescription(value);
  return toProtocolString(isolate, description);
}
References v8::Isolate::GetCurrent(), v8::debug::GetFunctionDescription(), v8_inspector::toProtocolString(), and v8::internal::value.
Referenced by v8_inspector::anonymous_namespace{value-mirror.cc}::FunctionMirror::buildEntryPreview(), v8_inspector::anonymous_namespace{value-mirror.cc}::FunctionMirror::buildRemoteObject(), and descriptionForPrivateMethod().
descriptionForNumber()
String16 v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForNumber (v8::Local< v8::Number > value, bool * unserializable)
Definition at line 477 of file value-mirror.cc.
                                                    {
  *unserializable = true;
  double rawValue = value->Value();
  if (std::isnan(rawValue)) return "NaN";
  if (rawValue == 0.0 && std::signbit(rawValue)) return "-0";
  if (std::isinf(rawValue)) {
    return std::signbit(rawValue) ? "-Infinity" : "Infinity";
  }
  *unserializable = false;
  return String16::fromDouble(rawValue);
}
References v8_inspector::String16::fromDouble(), and v8::internal::value.
Referenced by v8_inspector::anonymous_namespace{value-mirror.cc}::NumberMirror::buildDeepSerializedValue(), v8_inspector::anonymous_namespace{value-mirror.cc}::NumberMirror::buildEntryPreview(), v8_inspector::anonymous_namespace{value-mirror.cc}::NumberMirror::buildPropertyPreview(), and v8_inspector::anonymous_namespace{value-mirror.cc}::NumberMirror::buildRemoteObject().
descriptionForObject()
String16 v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForObject (v8::Isolate * isolate, v8::Local< v8::Object > object)
Definition at line 359 of file value-mirror.cc.
                                                        {
  return toProtocolString(isolate, object->GetConstructorName());
}
References v8::Object::GetConstructorName(), and v8_inspector::toProtocolString().
Referenced by v8_inspector::clientMirror(), v8_inspector::ValueMirror::create(), and descriptionForProxy().
descriptionForPrimitiveType()
String16 v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForPrimitiveType (v8::Local< v8::Context > context, v8::Local< v8::Value > value)
Definition at line 221 of file value-mirror.cc.
                                                             {
  if (value->IsUndefined()) return RemoteObject::TypeEnum::Undefined;
  if (value->IsNull()) return RemoteObject::SubtypeEnum::Null;
  if (value->IsBoolean()) {
    return value.As<v8::Boolean>()->Value() ? "true" : "false";
  }
  if (value->IsString()) {
    return toProtocolString(v8::Isolate::GetCurrent(), value.As<v8::String>());
  }
  UNREACHABLE();
}
References v8::Isolate::GetCurrent(), v8::internal::compiler::Null, v8_inspector::toProtocolString(), v8::internal::compiler::Undefined, UNREACHABLE, and v8::internal::value.
Referenced by v8_inspector::anonymous_namespace{value-mirror.cc}::PrimitiveValueMirror::buildEntryPreview(), and v8_inspector::anonymous_namespace{value-mirror.cc}::PrimitiveValueMirror::buildPropertyPreview().
descriptionForPrivateMethod()
String16 v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForPrivateMethod (v8::Local< v8::Context > context, v8::Local< v8::Object > object)
Definition at line 465 of file value-mirror.cc.
                                                               {
  v8::Isolate* isolate = v8::Isolate::GetCurrent();
  v8::Local<v8::Value> value;
  if (!object->GetRealNamedProperty(context, toV8String(isolate, "value"))
           .ToLocal(&value)) {
    return String16();
  }
  DCHECK(value->IsFunction());
  return descriptionForFunction(value.As<v8::Function>());
}
References DCHECK, descriptionForFunction(), v8::Isolate::GetCurrent(), v8::Object::GetRealNamedProperty(), v8_inspector::toV8String(), and v8::internal::value.
Referenced by v8_inspector::ValueMirror::create().
descriptionForPrivateMethodList()
String16 v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForPrivateMethodList (v8::Local< v8::Array > list)
Definition at line 459 of file value-mirror.cc.
                                                                {
  return String16::concat(
      "PrivateMethods[",
      String16::fromInteger(static_cast<size_t>(list->Length())), ']');
}
References v8_inspector::String16::concat(), v8_inspector::String16::fromInteger(), and v8::Array::Length().
Referenced by v8_inspector::ValueMirror::create().
descriptionForProxy()
String16 v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForProxy (v8::Isolate * isolate, v8::Local< v8::Proxy > proxy)
Definition at line 364 of file value-mirror.cc.
                                                                         {
  v8::Local<v8::Value> target = proxy->GetTarget();
  if (target->IsObject()) {
    return String16::concat(
        "Proxy(", descriptionForObject(isolate, target.As<v8::Object>()), ")");
  }
  return String16("Proxy");
}
References v8::Local< T >::As(), v8_inspector::String16::concat(), descriptionForObject(), and v8::Value::IsObject().
Referenced by v8_inspector::ValueMirror::create().
descriptionForRegExp()
String16 v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForRegExp (v8::Isolate * isolate, v8::Local< v8::RegExp > value)
Definition at line 234 of file value-mirror.cc.
                                                       {
  String16Builder description;
  description.append('/');
  description.append(toProtocolString(isolate, value->GetSource()));
  description.append('/');
  v8::RegExp::Flags flags = value->GetFlags();
  if (flags & v8::RegExp::Flags::kHasIndices) description.append('d');
  if (flags & v8::RegExp::Flags::kGlobal) description.append('g');
  if (flags & v8::RegExp::Flags::kIgnoreCase) description.append('i');
  if (flags & v8::RegExp::Flags::kLinear) description.append('l');
  if (flags & v8::RegExp::Flags::kMultiline) description.append('m');
  if (flags & v8::RegExp::Flags::kDotAll) description.append('s');
  if (flags & v8::RegExp::Flags::kUnicode) description.append('u');
  if (flags & v8::RegExp::Flags::kUnicodeSets) description.append('v');
  if (flags & v8::RegExp::Flags::kSticky) description.append('y');
  return description.toString();
}
References v8_inspector::String16Builder::append(), flags(), v8_inspector::toProtocolString(), v8_inspector::String16Builder::toString(), and v8::internal::value.
Referenced by v8_inspector::ValueMirror::create().
descriptionForScope()
String16 v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForScope (v8::Local< v8::Context > context, v8::Local< v8::Object > object)
Definition at line 386 of file value-mirror.cc.
                                                       {
  v8::Isolate* isolate = v8::Isolate::GetCurrent();
  v8::Local<v8::Value> value;
  if (!object->GetRealNamedProperty(context, toV8String(isolate, "description"))
           .ToLocal(&value)) {
    return String16();
  }
  return toProtocolStringWithTypeCheck(isolate, value);
}
References v8::Isolate::GetCurrent(), v8::Object::GetRealNamedProperty(), v8_inspector::toProtocolStringWithTypeCheck(), v8_inspector::toV8String(), and v8::internal::value.
Referenced by v8_inspector::ValueMirror::create().
descriptionForScopeList()
String16 v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForScopeList (v8::Local< v8::Array > list)
Definition at line 380 of file value-mirror.cc.
                                                        {
  return String16::concat(
      "Scopes[", String16::fromInteger(static_cast<size_t>(list->Length())),
      ']');
}
References v8_inspector::String16::concat(), v8_inspector::String16::fromInteger(), and v8::Array::Length().
Referenced by v8_inspector::ValueMirror::create().
descriptionForSymbol()
String16 v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForSymbol (v8::Local< v8::Context > context, v8::Local< v8::Symbol > symbol)
Definition at line 204 of file value-mirror.cc.
                                                        {
  v8::Isolate* isolate = v8::Isolate::GetCurrent();
  return String16::concat(
      "Symbol(",
      toProtocolStringWithTypeCheck(isolate, symbol->Description(isolate)),
      ")");
}
References v8_inspector::String16::concat(), v8::Isolate::GetCurrent(), and v8_inspector::toProtocolStringWithTypeCheck().
Referenced by v8_inspector::anonymous_namespace{value-mirror.cc}::SymbolMirror::buildEntryPreview(), v8_inspector::anonymous_namespace{value-mirror.cc}::SymbolMirror::buildPropertyPreview(), v8_inspector::anonymous_namespace{value-mirror.cc}::SymbolMirror::buildRemoteObject(), and v8_inspector::ValueMirror::getProperties().
doesAttributeHaveObservableSideEffectOnGet()
bool v8_inspector::anonymous_namespace{value-mirror.cc}::doesAttributeHaveObservableSideEffectOnGet (v8::Local< v8::Context > context, v8::Local< v8::Object > object, v8::Local< v8::Name > name)
Definition at line 1483 of file value-mirror.cc.
                                                                      {
  // TODO(dgozman): we should remove this, annotate more embedder properties as
  // side-effect free, and call all getters which do not produce side effects.
  if (!name->IsString()) return false;
  v8::Isolate* isolate = v8::Isolate::GetCurrent();
  if (!name.As<v8::String>()->StringEquals(toV8String(isolate, "body"))) {
    return false;
  }
  v8::TryCatch tryCatch(isolate);
  v8::Local<v8::Value> request;
  if (context->Global()
          ->GetRealNamedProperty(context, toV8String(isolate, "Request"))
          .ToLocal(&request)) {
    if (request->IsObject() &&
        object->InstanceOf(context, request.As<v8::Object>())
            .FromMaybe(false)) {
      return true;
    }
  }
  if (tryCatch.HasCaught()) tryCatch.Reset();
  v8::Local<v8::Value> response;
  if (context->Global()
          ->GetRealNamedProperty(context, toV8String(isolate, "Response"))
          .ToLocal(&response)) {
    if (response->IsObject() &&
        object->InstanceOf(context, response.As<v8::Object>())
            .FromMaybe(false)) {
      return true;
    }
  }
  return false;
}
References v8::Local< T >::As(), v8::Isolate::GetCurrent(), v8::Object::GetRealNamedProperty(), v8::Context::Global(), v8::TryCatch::HasCaught(), v8::Value::InstanceOf(), v8::Value::IsObject(), name, v8::TryCatch::Reset(), v8::String::StringEquals(), and v8_inspector::toV8String().
Referenced by v8_inspector::ValueMirror::getProperties().
getErrorProperty()
v8::MaybeLocal<v8::Value> v8_inspector::anonymous_namespace{value-mirror.cc}::getErrorProperty (v8::Local< v8::Context > context, v8::Local< v8::Object > object, v8::Local< v8::String > name)
Definition at line 259 of file value-mirror.cc.
                                                                   {
  v8::Isolate* isolate = v8::Isolate::GetCurrent();
  v8::TryCatch tryCatch(isolate);
  v8::MicrotasksScope microtasksScope(context,
                                      v8::MicrotasksScope::kDoNotRunMicrotasks);
  v8::Local<v8::Value> descriptor;
  if (!object->GetOwnPropertyDescriptor(context, name).ToLocal(&descriptor)) {
    tryCatch.Reset();
    return object->Get(context, name);
  }
  if (!descriptor->IsObject()) return object->Get(context, name);
  v8::Local<v8::Object> descriptorObject = descriptor.As<v8::Object>();
  v8::Local<v8::Value> getDescriptor;
  if (!descriptorObject->HasOwnProperty(context, toV8String(isolate, "get"))
           .FromJust()) {
    tryCatch.Reset();
    return object->Get(context, name);
  }
  if (!descriptorObject->Get(context, toV8String(isolate, "get"))
           .ToLocal(&getDescriptor)) {
    tryCatch.Reset();
    return object->Get(context, name);
  }
  if (getDescriptor->IsFunction()) {
    v8::Local<v8::Function> function = getDescriptor.As<v8::Function>();
    if (deepBoundFunction(function)->ScriptId() !=
        v8::UnboundScript::kNoScriptId) {
      return v8::MaybeLocal<v8::Value>();
    }
  }
  return object->Get(context, name);
}
References v8::Local< T >::As(), deepBoundFunction(), v8::Object::Get(), v8::Isolate::GetCurrent(), v8::Object::GetOwnPropertyDescriptor(), v8::Object::HasOwnProperty(), v8::Value::IsObject(), v8::MicrotasksScope::kDoNotRunMicrotasks, v8::UnboundScript::kNoScriptId, name, v8::TryCatch::Reset(), v8::MaybeLocal< T >::ToLocal(), and v8_inspector::toV8String().
Referenced by descriptionForError().
getInternalPropertiesForPreview()
void v8_inspector::anonymous_namespace{value-mirror.cc}::getInternalPropertiesForPreview (v8::Local< v8::Context > context, v8::Local< v8::Object > object, int * nameLimit, bool * overflow, std::vector< InternalPropertyMirror > * properties)
Definition at line 1113 of file value-mirror.cc.
                                                   {
  std::vector<InternalPropertyMirror> mirrors;
  ValueMirror::getInternalProperties(context, object, &mirrors);
  std::vector<String16> allowlist;
  if (object->IsBooleanObject() || object->IsNumberObject() ||
      object->IsStringObject() || object->IsSymbolObject() ||
      object->IsBigIntObject()) {
    allowlist.emplace_back("[[PrimitiveValue]]");
  } else if (object->IsPromise()) {
    allowlist.emplace_back("[[PromiseState]]");
    allowlist.emplace_back("[[PromiseResult]]");
  } else if (object->IsGeneratorObject()) {
    allowlist.emplace_back("[[GeneratorState]]");
  } else if (object->IsWeakRef()) {
    allowlist.emplace_back("[[WeakRefTarget]]");
  }
  for (auto& mirror : mirrors) {
    if (std::find(allowlist.begin(), allowlist.end(), mirror.name) ==
        allowlist.end()) {
      continue;
    }
    if (!*nameLimit) {
      *overflow = true;
      return;
    }
    --*nameLimit;
    properties->push_back(std::move(mirror));
  }
}
References v8_inspector::ValueMirror::getInternalProperties(), v8::Value::IsBigIntObject(), v8::Value::IsBooleanObject(), v8::Value::IsGeneratorObject(), v8::Value::IsNumberObject(), v8::Value::IsPromise(), v8::Value::IsStringObject(), v8::Value::IsSymbolObject(), v8::Value::IsWeakRef(), and v8::internal::overflow.
Referenced by v8_inspector::anonymous_namespace{value-mirror.cc}::ObjectMirror::buildObjectPreviewInternal().
getPrivatePropertiesForPreview()
void v8_inspector::anonymous_namespace{value-mirror.cc}::getPrivatePropertiesForPreview (v8::Local< v8::Context > context, v8::Local< v8::Object > object, int * nameLimit, bool * overflow, protocol::Array< PropertyPreview > * privateProperties)
Definition at line 1146 of file value-mirror.cc.
                                                       {
  std::vector<PrivatePropertyMirror> mirrors =
      ValueMirror::getPrivateProperties(context, object,
                                        /* accessPropertiesOnly */ false);
  for (auto& mirror : mirrors) {
    std::unique_ptr<PropertyPreview> propertyPreview;
    if (mirror.value) {
      mirror.value->buildPropertyPreview(context, mirror.name,
                                         &propertyPreview);
    } else {
      propertyPreview = PropertyPreview::create()
                            .setName(mirror.name)
                            .setType(PropertyPreview::TypeEnum::Accessor)
                            .build();
    }
    if (!propertyPreview) continue;
    if (!*nameLimit) {
      *overflow = true;
      return;
    }
    --*nameLimit;
    privateProperties->emplace_back(std::move(propertyPreview));
  }
}
References v8_inspector::ValueMirror::getPrivateProperties(), and v8::internal::overflow.
Referenced by v8_inspector::anonymous_namespace{value-mirror.cc}::ObjectMirror::buildObjectPreviewInternal().
getPropertiesForPreview()
bool v8_inspector::anonymous_namespace{value-mirror.cc}::getPropertiesForPreview (v8::Local< v8::Context > context, v8::Local< v8::Object > object, int * nameLimit, int * indexLimit, bool * overflow, std::vector< PropertyMirror > * properties)
Definition at line 1078 of file value-mirror.cc.
                                                                    {
  std::vector<String16> blocklist;
  size_t length = 0;
  if (isArrayLike(context, object, &length) || object->IsStringObject()) {
    blocklist.push_back("length");
#if V8_ENABLE_WEBASSEMBLY
  } else if (v8::debug::WasmValueObject::IsWasmValueObject(object)) {
    blocklist.push_back("type");
#endif // V8_ENABLE_WEBASSEMBLY
  } else {
    auto clientSubtype = clientFor(context)->valueSubtype(object);
    if (clientSubtype && toString16(clientSubtype->string()) == "array") {
      blocklist.push_back("length");
    }
  }
  if (object->IsArrayBuffer() || object->IsSharedArrayBuffer()) {
    blocklist.push_back("[[Int8Array]]");
    blocklist.push_back("[[Uint8Array]]");
    blocklist.push_back("[[Int16Array]]");
    blocklist.push_back("[[Int32Array]]");
  }
  blocklist.push_back("constructor");
  int skipIndex = object->IsStringObject()
                      ? object.As<v8::StringObject>()->ValueOf()->Length() + 1
                      : -1;
  PreviewPropertyAccumulator accumulator(v8::Isolate::GetCurrent(), blocklist,
                                         skipIndex, nameLimit, indexLimit,
                                         overflow, properties);
  return ValueMirror::getProperties(context, object, false, false, false,
                                    &accumulator);
}
References clientFor(), v8::Isolate::GetCurrent(), v8_inspector::ValueMirror::getProperties(), v8::Value::IsArrayBuffer(), isArrayLike(), v8::Value::IsSharedArrayBuffer(), v8::Value::IsStringObject(), v8::internal::length, v8::internal::overflow, v8_inspector::toString16(), and v8_inspector::V8InspectorClient::valueSubtype().
Referenced by v8_inspector::anonymous_namespace{value-mirror.cc}::ObjectMirror::buildObjectPreviewInternal().
isArrayLike()
bool v8_inspector::anonymous_namespace{value-mirror.cc}::isArrayLike (v8::Local< v8::Context > context, v8::Local< v8::Object > object, size_t * length)
Definition at line 963 of file value-mirror.cc.
                                 {
  if (object->IsArray()) {
    *length = object.As<v8::Array>()->Length();
    return true;
  }
  if (object->IsArgumentsObject()) {
    v8::Isolate* isolate = v8::Isolate::GetCurrent();
    v8::TryCatch tryCatch(isolate);
    v8::MicrotasksScope microtasksScope(
        context, v8::MicrotasksScope::kDoNotRunMicrotasks);
    v8::Local<v8::Value> lengthDescriptor;
    if (!object
             ->GetOwnPropertyDescriptor(context, toV8String(isolate, "length"))
             .ToLocal(&lengthDescriptor)) {
      return false;
    }
    v8::Local<v8::Value> lengthValue;
    if (!lengthDescriptor->IsObject() ||
        !lengthDescriptor.As<v8::Object>()
             ->Get(context, toV8String(isolate, "value"))
             .ToLocal(&lengthValue) ||
        !lengthValue->IsUint32()) {
      return false;
    }
    *length = lengthValue.As<v8::Uint32>()->Value();
    return true;
  }
  return false;
}
References v8::Local< T >::As(), v8::Object::Get(), v8::Isolate::GetCurrent(), v8::Value::IsArgumentsObject(), v8::Value::IsArray(), v8::Value::IsObject(), v8::Value::IsUint32(), v8::MicrotasksScope::kDoNotRunMicrotasks, v8::internal::length, and v8_inspector::toV8String().
Referenced by v8_inspector::ValueMirror::create(), and getPropertiesForPreview().
nativeGetterCallback()
void v8_inspector::anonymous_namespace{value-mirror.cc}::nativeGetterCallback (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 1398 of file value-mirror.cc.
                                                                       {
  v8::Local<v8::Object> data = info.Data().As<v8::Object>();
  v8::Isolate* isolate = info.GetIsolate();
  v8::Local<v8::Context> context = isolate->GetCurrentContext();
  v8::Local<v8::Value> name;
  if (!data->GetRealNamedProperty(context, toV8String(isolate, "name"))
           .ToLocal(&name)) {
    return;
  }
  v8::Local<v8::Value> object;
  if (!data->GetRealNamedProperty(context, toV8String(isolate, "object"))
           .ToLocal(&object) ||
      !object->IsObject()) {
    return;
  }
  v8::Local<v8::Value> value;
  if (!object.As<v8::Object>()->Get(context, name).ToLocal(&value)) return;
  info.GetReturnValue().Set(value);
}
References v8::FunctionCallbackInfo< T >::Data(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::Object::GetRealNamedProperty(), v8::FunctionCallbackInfo< T >::GetReturnValue(), name, v8::MaybeLocal< T >::ToLocal(), v8_inspector::toV8String(), and v8::internal::value.
Referenced by createNativeGetter().
nativeSetterCallback()
void v8_inspector::anonymous_namespace{value-mirror.cc}::nativeSetterCallback (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 1441 of file value-mirror.cc.
                                                                       {
  if (info.Length() < 1) return;
  v8::Local<v8::Object> data = info.Data().As<v8::Object>();
  v8::Isolate* isolate = info.GetIsolate();
  v8::Local<v8::Context> context = isolate->GetCurrentContext();
  v8::Local<v8::Value> name;
  if (!data->GetRealNamedProperty(context, toV8String(isolate, "name"))
           .ToLocal(&name)) {
    return;
  }
  v8::Local<v8::Value> object;
  if (!data->GetRealNamedProperty(context, toV8String(isolate, "object"))
           .ToLocal(&object) ||
      !object->IsObject()) {
    return;
  }
  if (!object.As<v8::Object>()->Set(context, name, info[0]).IsNothing()) return;
}
References v8::FunctionCallbackInfo< T >::Data(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::Object::GetRealNamedProperty(), v8::FunctionCallbackInfo< T >::Length(), name, v8::MaybeLocal< T >::ToLocal(), and v8_inspector::toV8String().
Referenced by createNativeSetter().
v8InternalValueTypeFrom()
V8InternalValueType v8_inspector::anonymous_namespace{value-mirror.cc}::v8InternalValueTypeFrom (v8::Local< v8::Context > context, v8::Local< v8::Value > value)
Definition at line 179 of file value-mirror.cc.
                                                                    {
  if (!value->IsObject()) return V8InternalValueType::kNone;
  V8InspectorImpl* inspector = static_cast<V8InspectorImpl*>(
      v8::debug::GetInspector(v8::Isolate::GetCurrent()));
  int contextId = InspectedContext::contextId(context);
  InspectedContext* inspectedContext = inspector->getContext(contextId);
  if (!inspectedContext) return V8InternalValueType::kNone;
  return inspectedContext->getInternalType(value.As<v8::Object>());
}
References v8_inspector::InspectedContext::contextId(), v8_inspector::V8InspectorImpl::getContext(), v8::Isolate::GetCurrent(), v8::debug::GetInspector(), v8_inspector::InspectedContext::getInternalType(), v8_inspector::kNone, and v8::internal::value.
Referenced by v8_inspector::ValueMirror::create(), and v8_inspector::ValueMirror::getProperties().
Variable Documentation
kWasmPageSize
const size_t v8_inspector::anonymous_namespace{value-mirror.cc}::kWasmPageSize = 64 * 1024
Definition at line 171 of file value-mirror.cc.
Referenced by v8_inspector::ValueMirror::create(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryGrowImpl(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryType().