v8::internal::compiler::anonymous_namespace{heap-refs.cc} Namespace Reference
Functions
bool Is64 ()
ZoneVector< Address > GetCFunctions (Tagged< FixedArray > function_overloads, Isolate *isolate, Zone *zone)
ZoneVector< const CFunctionInfo * > GetCSignatures (Tagged< FixedArray > function_overloads, Isolate *isolate, Zone *zone)
uint64_t RacyReadHeapNumberBits (Tagged< HeapNumber > value)
std::optional< Tagged< Object > > GetOwnFastConstantDataPropertyFromHeap (JSHeapBroker *broker, JSObjectRef holder, Representation representation, FieldIndex field_index)
OptionalObjectRef GetOwnDictionaryPropertyFromHeap (JSHeapBroker *broker, DirectHandle< JSObject > receiver, InternalIndex dict_index)
int InstanceSizeWithMinSlack (JSHeapBroker *broker, MapRef map)
bool IsReadOnlyLengthDescriptor (Isolate *isolate, DirectHandle< Map > jsarray_map)
bool SupportsFastArrayIteration (JSHeapBroker *broker, DirectHandle< Map > map)
bool SupportsFastArrayResize (JSHeapBroker *broker, DirectHandle< Map > map)
constexpr ObjectDataKind ObjectDataKindFor (RefSerializationKind kind)
void RecordConsistentJSFunctionViewDependencyIfNeeded (const JSHeapBroker *broker, JSFunctionRef ref, JSFunctionData *data, JSFunctionData::UsedField used_field)
OddballType GetOddballType (Isolate *isolate, Tagged< Map > map)
Function Documentation
GetCFunctions()
ZoneVector<Address> v8::internal::compiler::anonymous_namespace{heap-refs.cc}::GetCFunctions (Tagged< FixedArray > function_overloads, Isolate * isolate, Zone * zone)
Definition at line 187 of file heap-refs.cc.
                                                                {
  const int len = function_overloads->length() /
                  FunctionTemplateInfo::kFunctionOverloadEntrySize;
  ZoneVector<Address> c_functions = ZoneVector<Address>(len, zone);
  for (int i = 0; i < len; i++) {
    c_functions[i] = v8::ToCData<kCFunctionTag>(
        isolate, function_overloads->get(
                     FunctionTemplateInfo::kFunctionOverloadEntrySize * i));
  }
  return c_functions;
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::FunctionTemplateInfo::kFunctionOverloadEntrySize.
Referenced by v8::internal::compiler::FunctionTemplateInfoRef::c_functions().
GetCSignatures()
ZoneVector<const CFunctionInfo*> v8::internal::compiler::anonymous_namespace{heap-refs.cc}::GetCSignatures (Tagged< FixedArray > function_overloads, Isolate * isolate, Zone * zone)
Definition at line 200 of file heap-refs.cc.
                                                                         {
  const int len = function_overloads->length() /
                  FunctionTemplateInfo::kFunctionOverloadEntrySize;
  ZoneVector<const CFunctionInfo*> c_signatures =
      ZoneVector<const CFunctionInfo*>(len, zone);
  for (int i = 0; i < len; i++) {
    c_signatures[i] = v8::ToCData<const CFunctionInfo*, kCFunctionInfoTag>(
        isolate, function_overloads->get(
                     FunctionTemplateInfo::kFunctionOverloadEntrySize * i + 1));
  }
  return c_signatures;
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::FunctionTemplateInfo::kFunctionOverloadEntrySize.
Referenced by v8::internal::compiler::FunctionTemplateInfoRef::c_signatures().
GetOddballType()
OddballType v8::internal::compiler::anonymous_namespace{heap-refs.cc}::GetOddballType (Isolate * isolate, Tagged< Map > map)
Definition at line 2253 of file heap-refs.cc.
                                                              {
  if (map->instance_type() != ODDBALL_TYPE) {
    return OddballType::kNone;
  }
  ReadOnlyRoots roots(isolate);
  if (map == roots.undefined_map()) {
    return OddballType::kUndefined;
  }
  if (map == roots.null_map()) {
    return OddballType::kNull;
  }
  if (map == roots.boolean_map()) {
    return OddballType::kBoolean;
  }
  UNREACHABLE();
}
References v8::internal::compiler::kBoolean, v8::internal::compiler::kNone, v8::internal::compiler::kNull, v8::internal::compiler::kUndefined, and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::HeapObjectRef::GetHeapObjectType().
GetOwnDictionaryPropertyFromHeap()
OptionalObjectRef v8::internal::compiler::anonymous_namespace{heap-refs.cc}::GetOwnDictionaryPropertyFromHeap (JSHeapBroker * broker, DirectHandle< JSObject > receiver, InternalIndex dict_index)
Definition at line 392 of file heap-refs.cc.
                              {
  Handle<Object> constant;
  {
    DisallowGarbageCollection no_gc;
    // DictionaryPropertyAt will check that we are within the bounds of the
    // object.
    std::optional<Tagged<Object>> maybe_constant =
        JSObject::DictionaryPropertyAt(receiver, dict_index,
                                       broker->isolate()->heap());
    DCHECK_IMPLIES(broker->IsMainThread(), maybe_constant);
    if (!maybe_constant) return {};
    constant = broker->CanonicalPersistentHandle(maybe_constant.value());
  }
  return TryMakeRef(broker, constant);
}
References broker(), DCHECK_IMPLIES, v8::internal::JSObject::DictionaryPropertyAt(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::compiler::TryMakeRef().
Referenced by v8::internal::compiler::JSObjectRef::GetOwnDictionaryProperty().
GetOwnFastConstantDataPropertyFromHeap()
std::optional<Tagged<Object> > v8::internal::compiler::anonymous_namespace{heap-refs.cc}::GetOwnFastConstantDataPropertyFromHeap (JSHeapBroker * broker, JSObjectRef holder, Representation representation, FieldIndex field_index)
Definition at line 308 of file heap-refs.cc.
                            {
  std::optional<Tagged<Object>> constant;
  {
    DisallowGarbageCollection no_gc;
    PtrComprCageBase cage_base = broker->cage_base();
    // This check to ensure the live map is the same as the cached map to
    // to protect us against reads outside the bounds of the heap. This could
    // happen if the Ref was created in a prior GC epoch, and the object
    // shrunk in size. It might end up at the edge of a heap boundary. If
    // we see that the map is the same in this GC epoch, we are safe.
    Tagged<Map> map = holder.object()->map(cage_base, kAcquireLoad);
    if (*holder.map(broker).object() != map) {
      TRACE_BROKER_MISSING(broker, "Map changed for " << holder);
      return {};
    }
    if (field_index.is_inobject()) {
      constant =
          holder.object()->RawInobjectPropertyAt(cage_base, map, field_index);
      if (!constant.has_value()) {
        TRACE_BROKER_MISSING(
            broker, "Constant field in " << holder << " is unsafe to read");
        return {};
      }
    } else {
      Tagged<Object> raw_properties_or_hash =
          holder.object()->raw_properties_or_hash(cage_base, kRelaxedLoad);
      // Ensure that the object is safe to inspect.
      if (broker->ObjectMayBeUninitialized(raw_properties_or_hash)) {
        return {};
      }
      if (!IsPropertyArray(raw_properties_or_hash, cage_base)) {
        TRACE_BROKER_MISSING(
            broker,
            "Expected PropertyArray for backing store in " << holder << ".");
        return {};
      }
      Tagged<PropertyArray> properties =
          Cast<PropertyArray>(raw_properties_or_hash);
      const int array_index = field_index.outobject_array_index();
      if (array_index < properties->length(kAcquireLoad)) {
        constant = properties->get(array_index);
      } else {
        TRACE_BROKER_MISSING(
            broker, "Backing store for " << holder << " not long enough.");
        return {};
      }
    }
    // We might read the uninitialized sentinel, if we race with the main
    // thread adding a new property to the object (having set the map, but not
    // yet initialised the property value). Since this is a tight race, it won't
    // happen very often, so we can just abort the load.
    // TODO(leszeks): We could instead sleep/yield and spin the load, since the
    // timing on this is tight enough that we wouldn't delay the compiler thread
    // by much.
    if (IsUninitialized(constant.value())) {
      TRACE_BROKER_MISSING(broker, "Read uninitialized property.");
      return {};
    }
    // {constant} needs to pass the gc predicate before we can introspect on it.
    if (broker->ObjectMayBeUninitialized(constant.value())) return {};
    // Ensure that {constant} matches the {representation} we expect for the
    // field.
    if (!Object::FitsRepresentation(*constant, representation, false)) {
      const char* repString = IsSmi(*constant) ? "Smi"
                              : IsHeapNumber(*constant) ? "HeapNumber"
                                                        : "HeapObject";
      TRACE_BROKER_MISSING(broker, "Mismatched representation for "
                                       << holder << ". Expected "
                                       << representation << ", but object is a "
                                       << repString);
      return {};
    }
  }
  return constant;
}
References broker(), v8::internal::Object::FitsRepresentation(), v8::internal::FieldIndex::is_inobject(), v8::internal::IsSmi(), v8::kAcquireLoad, v8::kRelaxedLoad, v8::internal::length, v8::internal::compiler::HeapObjectRef::map(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::compiler::JSObjectRef::object(), v8::internal::compiler::MapRef::object(), v8::internal::FieldIndex::outobject_array_index(), v8::internal::raw_properties_or_hash, and TRACE_BROKER_MISSING.
Referenced by v8::internal::compiler::JSObjectRef::GetOwnFastConstantDataProperty(), and v8::internal::compiler::JSObjectRef::GetOwnFastConstantDoubleProperty().
InstanceSizeWithMinSlack()
int v8::internal::compiler::anonymous_namespace{heap-refs.cc}::InstanceSizeWithMinSlack (JSHeapBroker * broker, MapRef map)
Definition at line 596 of file heap-refs.cc.
                                                               {
  // This operation is split into two phases (1. map collection, 2. map
  // processing). This is to avoid having to take two locks
  // (full_transition_array_access and map_updater_access) at once and thus
  // having to deal with related deadlock issues.
  ZoneVector<IndirectHandle<Map>> maps(broker->zone());
  maps.push_back(map.object());
  {
    DisallowGarbageCollection no_gc;
    // Has to be an initial map.
    DCHECK(IsUndefined(map.object()->GetBackPointer(), broker->isolate()));
    static constexpr bool kConcurrentAccess = true;
    TransitionsAccessor(broker->isolate(), *map.object(), kConcurrentAccess)
        .TraverseTransitionTree([&](Tagged<Map> m) {
          maps.push_back(broker->CanonicalPersistentHandle(m));
        });
  }
  // The lock is needed for UnusedPropertyFields and InstanceSizeFromSlack.
  JSHeapBroker::MapUpdaterGuardIfNeeded mumd_scope(broker);
  int slack = std::numeric_limits<int>::max();
  for (DirectHandle<Map> m : maps) {
    slack = std::min(slack, m->UnusedPropertyFields());
  }
  return map.object()->InstanceSizeFromSlack(slack);
}
References broker(), v8::internal::DCHECK(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::compiler::MapRef::object(), v8::internal::ZoneVector< T >::push_back(), and v8::internal::TransitionsAccessor::TraverseTransitionTree().
Referenced by v8::internal::compiler::JSFunctionData::Cache().
Is64()
bool v8::internal::compiler::anonymous_namespace{heap-refs.cc}::Is64 ()
Definition at line 72 of file heap-refs.cc.
{ return kSystemPointerSize == 8; }
References v8::internal::kSystemPointerSize.
Referenced by v8::internal::CodeStubAssembler::BigIntToRawBytes(), v8::internal::CodeStubAssembler::Equal(), v8::internal::CodeStubAssembler::GenerateEqual_Same(), v8::internal::CodeStubAssembler::RelationalComparison(), v8::internal::CodeStubAssembler::StoreElementTypedArrayBigInt(), v8::internal::CodeStubAssembler::StrictEqual(), v8::internal::CodeStubAssembler::TryLookupElement(), and v8::internal::CodeStubAssembler::TryToIntptr().
IsReadOnlyLengthDescriptor()
bool v8::internal::compiler::anonymous_namespace{heap-refs.cc}::IsReadOnlyLengthDescriptor (Isolate * isolate, DirectHandle< Map > jsarray_map)
Definition at line 849 of file heap-refs.cc.
                                                               {
  DCHECK(!jsarray_map->is_dictionary_map());
  Tagged<DescriptorArray> descriptors =
      jsarray_map->instance_descriptors(isolate, kRelaxedLoad);
  static_assert(
      JSArray::kLengthOffset == JSObject::kHeaderSize,
      "The length should be the first property on the descriptor array");
  InternalIndex offset(0);
  return descriptors->GetDetails(offset).IsReadOnly();
}
References v8::internal::DCHECK(), and v8::kRelaxedLoad.
Referenced by SupportsFastArrayResize().
ObjectDataKindFor()
constexpr ObjectDataKind v8::internal::compiler::anonymous_namespace{heap-refs.cc}::ObjectDataKindFor (RefSerializationKind kind) [constexpr]
Definition at line 1033 of file heap-refs.cc.
                                                                      {
  switch (kind) {
    case RefSerializationKind::kBackgroundSerialized:
      return kBackgroundSerializedHeapObject;
    case RefSerializationKind::kNeverSerialized:
      return kNeverSerializedHeapObject;
  }
}
References v8::internal::compiler::kBackgroundSerialized, v8::internal::compiler::kBackgroundSerializedHeapObject, v8::internal::compiler::kNeverSerialized, and v8::internal::compiler::kNeverSerializedHeapObject.
RacyReadHeapNumberBits()
uint64_t v8::internal::compiler::anonymous_namespace{heap-refs.cc}::RacyReadHeapNumberBits (Tagged< HeapNumber > value)
Definition at line 304 of file heap-refs.cc.
                                                          {
  return value->value_as_bits();
}
References v8::internal::value.
Referenced by v8::internal::compiler::JSObjectRef::GetOwnFastConstantDoubleProperty().
RecordConsistentJSFunctionViewDependencyIfNeeded()
void v8::internal::compiler::anonymous_namespace{heap-refs.cc}::RecordConsistentJSFunctionViewDependencyIfNeeded (const JSHeapBroker * broker, JSFunctionRef ref, JSFunctionData * data, JSFunctionData::UsedField used_field)
Definition at line 1267 of file heap-refs.cc.
                                        {
  if (!data->has_any_used_field()) {
    // Deduplicate dependencies.
    broker->dependencies()->DependOnConsistentJSFunctionView(ref);
  }
  data->set_used_field(used_field);
}
References broker(), v8::internal::compiler::JSFunctionData::has_any_used_field(), and v8::internal::compiler::JSFunctionData::set_used_field().
Referenced by v8::internal::compiler::JSFunctionRef::InitialMapInstanceSizeWithMinSlack().
SupportsFastArrayIteration()
bool v8::internal::compiler::anonymous_namespace{heap-refs.cc}::SupportsFastArrayIteration (JSHeapBroker * broker, DirectHandle< Map > map)
Definition at line 865 of file heap-refs.cc.
                                                                             {
  return map->instance_type() == JS_ARRAY_TYPE &&
         IsFastElementsKind(map->elements_kind()) &&
         IsJSArray(map->prototype()) &&
         broker->IsArrayOrObjectPrototype(broker->CanonicalPersistentHandle(
             Cast<JSArray>(map->prototype())));
}
References broker(), and v8::internal::IsFastElementsKind().
Referenced by v8::internal::compiler::MapRef::supports_fast_array_iteration(), and SupportsFastArrayResize().
SupportsFastArrayResize()
bool v8::internal::compiler::anonymous_namespace{heap-refs.cc}::SupportsFastArrayResize (JSHeapBroker * broker, DirectHandle< Map > map)
Definition at line 873 of file heap-refs.cc.
                                                                          {
  return SupportsFastArrayIteration(broker, map) && map->is_extensible() &&
         !map->is_dictionary_map() &&
         !IsReadOnlyLengthDescriptor(broker->isolate(), map);
}
References broker(), IsReadOnlyLengthDescriptor(), and SupportsFastArrayIteration().
Referenced by v8::internal::compiler::MapRef::supports_fast_array_resize().