v8::internal::interpreter::anonymous_namespace{bytecode-generator.cc} Namespace Reference
Classes
struct Accessors
class AccessorTable
struct NullContextScopeHelper
struct NullContextScopeHelper< Isolate >
struct NullContextScopeHelper< LocalIsolate >
struct SwitchInfo
Typedefs
template<typename Isolate >
using NullContextScopeFor = typename NullContextScopeHelper< Isolate >::Type
Functions
bool NeedsContextInitialization (DeclarationScope *scope)
bool IsSmiLiteralSwitchCaseValue (Expression *expr)
int ReduceToSmiSwitchCaseValue (Expression *expr)
bool IsSpreadAcceptable (int spread, int ncases)
bool IsSwitchOptimizable (SwitchStatement *stmt, SwitchInfo *info)
Typedef Documentation
NullContextScopeFor
template<typename Isolate >
using v8::internal::interpreter::anonymous_namespace{bytecode-generator.cc}::NullContextScopeFor = typedef typename NullContextScopeHelper<Isolate>::Type
Definition at line 1474 of file bytecode-generator.cc.
Function Documentation
IsSmiLiteralSwitchCaseValue()
bool v8::internal::interpreter::anonymous_namespace{bytecode-generator.cc}::IsSmiLiteralSwitchCaseValue (Expression * expr)
Definition at line 2370 of file bytecode-generator.cc.
                                                   {
  if (expr->IsSmiLiteral() ||
      (expr->IsLiteral() && expr->AsLiteral()->IsNumber() &&
       expr->AsLiteral()->AsNumber() == 0.0)) {
    return true;
#ifdef DEBUG
  } else if (expr->IsLiteral() && expr->AsLiteral()->IsNumber()) {
    DCHECK(!IsSmiDouble(expr->AsLiteral()->AsNumber()));
#endif
  }
  return false;
}
References v8::internal::DCHECK(), v8::internal::IsSmiDouble(), and v8::internal::Expression::IsSmiLiteral().
Referenced by v8::internal::interpreter::anonymous_namespace{bytecode-generator.cc}::SwitchInfo::CaseExists(), v8::internal::interpreter::anonymous_namespace{bytecode-generator.cc}::SwitchInfo::IsDuplicate(), and IsSwitchOptimizable().
IsSpreadAcceptable()
bool v8::internal::interpreter::anonymous_namespace{bytecode-generator.cc}::IsSpreadAcceptable (int spread, int ncases) [inline]
Definition at line 2396 of file bytecode-generator.cc.
                                                       {
  return spread < v8_flags.switch_table_spread_threshold * ncases;
}
References v8::internal::v8_flags.
Referenced by IsSwitchOptimizable().
IsSwitchOptimizable()
bool v8::internal::interpreter::anonymous_namespace{bytecode-generator.cc}::IsSwitchOptimizable (SwitchStatement * stmt, SwitchInfo * info)
Definition at line 2441 of file bytecode-generator.cc.
                                                                  {
  ZonePtrList<CaseClause>* cases = stmt->cases();
  for (int i = 0; i < cases->length(); ++i) {
    CaseClause* clause = cases->at(i);
    if (clause->is_default()) {
      continue;
    } else if (!(clause->label()->IsLiteral())) {
      // Don't consider Smi cases after a non-literal, because we
      // need to evaluate the non-literal.
      break;
    } else if (IsSmiLiteralSwitchCaseValue(clause->label())) {
      int value = ReduceToSmiSwitchCaseValue(clause->label());
      info->covered_cases.insert({value, clause});
    }
  }
  // GCC also jump-table optimizes switch statements with 6 cases or more.
  if (static_cast<int>(info->covered_cases.size()) >=
      v8_flags.switch_table_min_cases) {
    // Due to case spread will be used as the size of jump-table,
    // we need to check if it doesn't overflow by casting its
    // min and max bounds to int64_t, and calculate if the difference is less
    // than or equal to INT_MAX.
    int64_t min = static_cast<int64_t>(info->MinCase());
    int64_t max = static_cast<int64_t>(info->MaxCase());
    int64_t spread = max - min + 1;
    DCHECK_GT(spread, 0);
    // Check if casted spread is acceptable and doesn't overflow.
    if (spread <= INT_MAX &&
        IsSpreadAcceptable(static_cast<int>(spread), cases->length())) {
      return true;
    }
  }
  // Invariant- covered_cases has all cases and only cases that will go in the
  // jump table.
  info->covered_cases.clear();
  return false;
}
References v8::internal::ZoneList< T >::at(), v8::internal::SwitchStatement::cases(), v8::internal::interpreter::anonymous_namespace{bytecode-generator.cc}::SwitchInfo::covered_cases, DCHECK_GT, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::CaseClause::is_default(), IsSmiLiteralSwitchCaseValue(), IsSpreadAcceptable(), v8::internal::CaseClause::label(), v8::internal::ZoneList< T >::length(), v8::internal::interpreter::anonymous_namespace{bytecode-generator.cc}::SwitchInfo::MaxCase(), v8::internal::interpreter::anonymous_namespace{bytecode-generator.cc}::SwitchInfo::MinCase(), ReduceToSmiSwitchCaseValue(), v8::internal::v8_flags, and v8::internal::value.
NeedsContextInitialization()
bool v8::internal::interpreter::anonymous_namespace{bytecode-generator.cc}::NeedsContextInitialization (DeclarationScope * scope)
Definition at line 1651 of file bytecode-generator.cc.
                                                         {
  return scope->NeedsContext() && !scope->is_script_scope() &&
         !scope->is_module_scope();
}
References v8::internal::Scope::is_module_scope(), v8::internal::Scope::is_script_scope(), and v8::internal::Scope::NeedsContext().
Referenced by v8::internal::interpreter::BytecodeGenerator::GenerateBytecode().
ReduceToSmiSwitchCaseValue()
int v8::internal::interpreter::anonymous_namespace{bytecode-generator.cc}::ReduceToSmiSwitchCaseValue (Expression * expr) [inline]
Definition at line 2384 of file bytecode-generator.cc.
                                                        {
  if (V8_LIKELY(expr->IsSmiLiteral())) {
    return expr->AsLiteral()->AsSmiLiteral().value();
  } else {
    // Only the zero case is possible otherwise.
    DCHECK(expr->IsLiteral() && expr->AsLiteral()->IsNumber() &&
           expr->AsLiteral()->AsNumber() == -0.0);
    return 0;
  }
}
References v8::internal::DCHECK(), v8::internal::Expression::IsSmiLiteral(), and V8_LIKELY.
Referenced by v8::internal::interpreter::anonymous_namespace{bytecode-generator.cc}::SwitchInfo::CaseExists(), v8::internal::interpreter::anonymous_namespace{bytecode-generator.cc}::SwitchInfo::IsDuplicate(), and IsSwitchOptimizable().