v8::internal::compiler::anonymous_namespace{escape-analysis.cc} Namespace Reference
Namespaces
 anonymous_namespace{escape-analysis.cc}
Functions
int OffsetOfFieldAccess (const Operator *op)
Maybe< int > OffsetOfElementAt (ElementAccess const &access, int index)
Maybe< int > OffsetOfElementsAccess (const Operator *op, Node *index_node)
Node * LowerCompareMapsWithoutLoad (Node *checked_map, ZoneRefSet< Map > const &checked_against, JSGraph *jsgraph)
void ReduceNode (const Operator *op, EscapeAnalysisTracker::Scope *current, JSGraph *jsgraph)
Function Documentation
LowerCompareMapsWithoutLoad()
Node* v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::LowerCompareMapsWithoutLoad (Node * checked_map, ZoneRefSet< Map > const & checked_against, JSGraph * jsgraph)
Definition at line 578 of file escape-analysis.cc.
                                                    {
  Node* true_node = jsgraph->TrueConstant();
  Node* false_node = jsgraph->FalseConstant();
  Node* replacement = false_node;
  for (MapRef map : checked_against) {
    // We are using HeapConstantMaybeHole here instead of HeapConstantNoHole
    // as we cannot do the CHECK(object is hole) here as the compile thread is
    // parked during EscapeAnalysis for performance reasons, see pipeline.cc.
    // TODO(cffsmith): do manual checking against hole values here.
    Node* map_node = jsgraph->HeapConstantMaybeHole(map.object());
    // We cannot create a HeapConstant type here as we are off-thread.
    NodeProperties::SetType(map_node, Type::Internal());
    Node* comparison = jsgraph->graph()->NewNode(
        jsgraph->simplified()->ReferenceEqual(), checked_map, map_node);
    NodeProperties::SetType(comparison, Type::Boolean());
    if (replacement == false_node) {
      replacement = comparison;
    } else {
      replacement = jsgraph->graph()->NewNode(
          jsgraph->common()->Select(MachineRepresentation::kTaggedPointer),
          comparison, true_node, replacement);
      NodeProperties::SetType(replacement, Type::Boolean());
    }
  }
  return replacement;
}
References v8::internal::compiler::MachineGraph::common(), v8::internal::compiler::MachineGraph::graph(), v8::internal::compiler::JSGraph::HeapConstantMaybeHole(), v8::internal::kTaggedPointer, v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::SimplifiedOperatorBuilder::ReferenceEqual(), v8::internal::compiler::CommonOperatorBuilder::Select(), v8::internal::compiler::NodeProperties::SetType(), and v8::internal::compiler::JSGraph::simplified().
Referenced by ReduceNode().
OffsetOfElementAt()
Maybe<int> v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::OffsetOfElementAt (ElementAccess const & access, int index)
Definition at line 555 of file escape-analysis.cc.
                                                                     {
  MachineRepresentation representation = access.machine_type.representation();
  // Double elements accesses are not yet supported. See chromium:1237821.
  if (representation == MachineRepresentation::kFloat64) return Nothing<int>();
  DCHECK_GE(index, 0);
  DCHECK_GE(ElementSizeLog2Of(representation), kTaggedSizeLog2);
  return Just(access.header_size +
              (index << ElementSizeLog2Of(representation)));
}
References DCHECK_GE, v8::internal::ElementSizeLog2Of(), v8::internal::compiler::ElementAccess::header_size, v8::internal::index, v8::Just(), v8::internal::kFloat64, v8::internal::kTaggedSizeLog2, v8::internal::compiler::ElementAccess::machine_type, and v8::internal::MachineType::representation().
Referenced by v8::internal::CodeStubAssembler::AllocateNameDictionaryWithCapacity(), v8::internal::CodeStubAssembler::AllocateSimpleNameDictionaryWithCapacity(), v8::internal::EphemeronHashTable::BodyDescriptor::IterateBody(), v8::internal::maglev::StoreContextSlotWithWriteBarrier::offset(), OffsetOfElementsAccess(), ReduceNode(), v8::internal::EmbedderDataArray::slots_start(), and v8::internal::CodeStubAssembler::UnsafeStoreArrayElement().
OffsetOfElementsAccess()
Maybe<int> v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::OffsetOfElementsAccess (const Operator * op, Node * index_node)
Definition at line 566 of file escape-analysis.cc.
                                                                        {
  DCHECK(op->opcode() == IrOpcode::kLoadElement ||
         op->opcode() == IrOpcode::kStoreElement);
  Type index_type = NodeProperties::GetType(index_node);
  if (!index_type.Is(Type::OrderedNumber())) return Nothing<int>();
  double max = index_type.Max();
  double min = index_type.Min();
  int index = static_cast<int>(min);
  if (index < 0 || index != min || index != max) return Nothing<int>();
  return OffsetOfElementAt(ElementAccessOf(op), index);
}
References v8::internal::DCHECK(), v8::internal::compiler::ElementAccessOf(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::index, v8::internal::compiler::Type::Is(), v8::internal::compiler::Type::Max(), v8::internal::compiler::Type::Min(), OffsetOfElementAt(), and v8::internal::compiler::Operator::opcode().
Referenced by ReduceNode().
OffsetOfFieldAccess()
int v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::OffsetOfFieldAccess (const Operator * op)
Definition at line 548 of file escape-analysis.cc.
                                            {
  DCHECK(op->opcode() == IrOpcode::kLoadField ||
         op->opcode() == IrOpcode::kStoreField);
  FieldAccess access = FieldAccessOf(op);
  return access.offset;
}
References v8::internal::DCHECK(), v8::internal::compiler::FieldAccessOf(), v8::internal::compiler::FieldAccess::offset, and v8::internal::compiler::Operator::opcode().
Referenced by ReduceNode().
ReduceNode()
void v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::ReduceNode (const Operator * op, EscapeAnalysisTracker::Scope * current, JSGraph * jsgraph)
Definition at line 633 of file escape-analysis.cc.
                                  {
  switch (op->opcode()) {
    case IrOpcode::kAllocate: {
      NumberMatcher size(current->ValueInput(0));
      if (!size.HasResolvedValue()) break;
      int size_int = static_cast<int>(size.ResolvedValue());
      if (size_int != size.ResolvedValue()) break;
      if (const VirtualObject* vobject = current->InitVirtualObject(size_int)) {
        // Initialize with dead nodes as a sentinel for uninitialized memory.
        for (Variable field : *vobject) {
          current->Set(field, jsgraph->Dead());
        }
      }
      break;
    }
    case IrOpcode::kFinishRegion:
      current->SetVirtualObject(current->ValueInput(0));
      break;
    case IrOpcode::kStoreField: {
      Node* object = current->ValueInput(0);
      Node* value = current->ValueInput(1);
      const VirtualObject* vobject = current->GetVirtualObject(object);
      Variable var;
      if (value->opcode() == IrOpcode::kTrustedHeapConstant) {
        // TODO(dmercadier): enable escaping objects containing
        // TrustedHeapConstants. This is currently disabled because it leads to
        // bugs when Trusted HeapConstant and regular HeapConstant flow into the
        // same Phi, which can then be marked as Compressed, messing up the
        // tagging of the Trusted HeapConstant.
        current->SetEscaped(object);
        current->SetEscaped(value);
        break;
      }
      // BoundedSize fields cannot currently be materialized by the deoptimizer,
      // so we must not dematerialze them.
      if (vobject && !vobject->HasEscaped() &&
          vobject->FieldAt(OffsetOfFieldAccess(op)).To(&var) &&
          !FieldAccessOf(op).is_bounded_size_access) {
        current->Set(var, value);
        current->MarkForDeletion();
      } else {
        current->SetEscaped(object);
        current->SetEscaped(value);
      }
      break;
    }
    case IrOpcode::kStoreElement: {
      Node* object = current->ValueInput(0);
      Node* index = current->ValueInput(1);
      Node* value = current->ValueInput(2);
      const VirtualObject* vobject = current->GetVirtualObject(object);
      int offset;
      Variable var;
      if (vobject && !vobject->HasEscaped() &&
          OffsetOfElementsAccess(op, index).To(&offset) &&
          vobject->FieldAt(offset).To(&var)) {
        current->Set(var, value);
        current->MarkForDeletion();
      } else {
        current->SetEscaped(value);
        current->SetEscaped(object);
      }
      break;
    }
    case IrOpcode::kLoadField: {
      Node* object = current->ValueInput(0);
      const VirtualObject* vobject = current->GetVirtualObject(object);
      Variable var;
      Node* value;
      if (vobject && !vobject->HasEscaped() &&
          vobject->FieldAt(OffsetOfFieldAccess(op)).To(&var) &&
          current->Get(var).To(&value)) {
        current->SetReplacement(value);
      } else {
        current->SetEscaped(object);
      }
      break;
    }
    case IrOpcode::kLoadElement: {
      Node* object = current->ValueInput(0);
      Node* index = current->ValueInput(1);
      const VirtualObject* vobject = current->GetVirtualObject(object);
      int offset;
      Variable var;
      Node* value;
      if (vobject && !vobject->HasEscaped() &&
          OffsetOfElementsAccess(op, index).To(&offset) &&
          vobject->FieldAt(offset).To(&var) && current->Get(var).To(&value)) {
        current->SetReplacement(value);
        break;
      } else if (vobject && !vobject->HasEscaped()) {
        // Compute the known length (aka the number of elements) of {object}
        // based on the virtual object information.
        ElementAccess const& access = ElementAccessOf(op);
        int const length =
            (vobject->size() - access.header_size) >>
            ElementSizeLog2Of(access.machine_type.representation());
        Variable var0, var1;
        Node* value0;
        Node* value1;
        if (length == 1 &&
            vobject->FieldAt(OffsetOfElementAt(access, 0)).To(&var) &&
            current->Get(var).To(&value) &&
            (value == nullptr ||
             NodeProperties::GetType(value).Is(access.type))) {
          // The {object} has no elements, and we know that the LoadElement
          // {index} must be within bounds, thus it must always yield this
          // one element of {object}.
          current->SetReplacement(value);
          break;
        } else if (length == 2 &&
                   vobject->FieldAt(OffsetOfElementAt(access, 0)).To(&var0) &&
                   current->Get(var0).To(&value0) &&
                   (value0 == nullptr ||
                    NodeProperties::GetType(value0).Is(access.type)) &&
                   vobject->FieldAt(OffsetOfElementAt(access, 1)).To(&var1) &&
                   current->Get(var1).To(&value1) &&
                   (value1 == nullptr ||
                    NodeProperties::GetType(value1).Is(access.type))) {
          if (value0 && value1) {
            // The {object} has exactly two elements, so the LoadElement
            // must return one of them (i.e. either the element at index
            // 0 or the one at index 1). So we can turn the LoadElement
            // into a Select operation instead (still allowing the {object}
            // to be scalar replaced). We must however mark the elements
            // of the {object} itself as escaping.
            Node* check =
                jsgraph->graph()->NewNode(jsgraph->simplified()->NumberEqual(),
                                          index, jsgraph->ZeroConstant());
            NodeProperties::SetType(check, Type::Boolean());
            Node* select = jsgraph->graph()->NewNode(
                jsgraph->common()->Select(access.machine_type.representation()),
                check, value0, value1);
            NodeProperties::SetType(select, access.type);
            current->SetReplacement(select);
            current->SetEscaped(value0);
            current->SetEscaped(value1);
            break;
          } else {
            // If the variables have no values, we have
            // not reached the fixed-point yet.
            break;
          }
        }
      }
      current->SetEscaped(object);
      break;
    }
    case IrOpcode::kTypeGuard: {
      current->SetVirtualObject(current->ValueInput(0));
      break;
    }
    case IrOpcode::kReferenceEqual: {
      Node* left = current->ValueInput(0);
      Node* right = current->ValueInput(1);
      const VirtualObject* left_object = current->GetVirtualObject(left);
      const VirtualObject* right_object = current->GetVirtualObject(right);
      Node* replacement = nullptr;
      if (left_object && !left_object->HasEscaped()) {
        if (right_object && !right_object->HasEscaped() &&
            left_object->id() == right_object->id()) {
          replacement = jsgraph->TrueConstant();
        } else {
          replacement = jsgraph->FalseConstant();
        }
      } else if (right_object && !right_object->HasEscaped()) {
        replacement = jsgraph->FalseConstant();
      }
      // TODO(turbofan) This is a workaround for uninhabited types. If we
      // replaced a value of uninhabited type with a constant, we would
      // widen the type of the node. This could produce inconsistent
      // types (which might confuse representation selection). We get
      // around this by refusing to constant-fold and escape-analyze
      // if the type is not inhabited.
      if (replacement && !NodeProperties::GetType(left).IsNone() &&
          !NodeProperties::GetType(right).IsNone()) {
        current->SetReplacement(replacement);
        break;
      }
      current->SetEscaped(left);
      current->SetEscaped(right);
      break;
    }
    case IrOpcode::kCheckMaps: {
      CheckMapsParameters params = CheckMapsParametersOf(op);
      Node* checked = current->ValueInput(0);
      if (CheckMapsHelper(current, checked, params.maps())) {
        break;
      }
      current->SetEscaped(checked);
      break;
    }
    case IrOpcode::kTransitionElementsKindOrCheckMap: {
      ElementsTransitionWithMultipleSources params =
          ElementsTransitionWithMultipleSourcesOf(op);
      Node* checked = current->ValueInput(0);
      if (CheckMapsHelper(current, checked, ZoneRefSet<Map>(params.target()))) {
        break;
      }
      current->SetEscaped(checked);
      break;
    }
    case IrOpcode::kCompareMaps: {
      Node* object = current->ValueInput(0);
      const VirtualObject* vobject = current->GetVirtualObject(object);
      Variable map_field;
      Node* object_map;
      if (vobject && !vobject->HasEscaped() &&
          vobject->FieldAt(HeapObject::kMapOffset).To(&map_field) &&
          current->Get(map_field).To(&object_map)) {
        if (object_map) {
          current->SetReplacement(LowerCompareMapsWithoutLoad(
              object_map, CompareMapsParametersOf(op), jsgraph));
          break;
        } else {
          // If the variable has no value, we have not reached the fixed-point
          // yet.
          break;
        }
      }
      current->SetEscaped(object);
      break;
    }
    case IrOpcode::kCheckHeapObject: {
      Node* checked = current->ValueInput(0);
      switch (checked->opcode()) {
        case IrOpcode::kAllocate:
        case IrOpcode::kFinishRegion:
        case IrOpcode::kHeapConstant:
          current->SetReplacement(checked);
          break;
        default:
          current->SetEscaped(checked);
          break;
      }
      break;
    }
    case IrOpcode::kMapGuard: {
      Node* object = current->ValueInput(0);
      const VirtualObject* vobject = current->GetVirtualObject(object);
      if (vobject && !vobject->HasEscaped()) {
        current->MarkForDeletion();
      }
      break;
    }
    case IrOpcode::kStateValues:
      // We visit StateValue nodes through their correpsonding FrameState node,
      // so we need to make sure we revisit the FrameState.
      current->SetValueChanged();
      break;
    case IrOpcode::kFrameState: {
      // We mark the receiver as escaping due to the non-standard `.getThis`
      // API.
      FrameState frame_state{current->CurrentNode()};
      FrameStateType type = frame_state.frame_state_info().type();
      // This needs to be kept in sync with the frame types supported in
      // `OptimizedJSFrame::Summarize`.
      if (type != FrameStateType::kUnoptimizedFunction &&
          type != FrameStateType::kJavaScriptBuiltinContinuation &&
          type != FrameStateType::kJavaScriptBuiltinContinuationWithCatch) {
        break;
      }
      if (!current->FrameStateMightLazyDeopt(current->CurrentNode())) {
        // Only lazy deopt frame states are used to generate stack traces.
        break;
      }
      StateValuesAccess::iterator it =
          StateValuesAccess(frame_state.parameters()).begin();
      if (!it.done()) {
        if (Node* receiver = it.node()) {
          current->SetEscaped(receiver);
        }
        current->SetEscaped(frame_state.function());
      }
      break;
    }
    default: {
      // For unknown nodes, treat all value inputs as escaping.
      int value_input_count = op->ValueInputCount();
      for (int i = 0; i < value_input_count; ++i) {
        Node* input = current->ValueInput(i);
        current->SetEscaped(input);
      }
      if (OperatorProperties::HasContextInput(op)) {
        current->SetEscaped(current->ContextInput());
      }
      break;
    }
  }
}
References v8::internal::compiler::StateValuesAccess::begin(), v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::anonymous_namespace{escape-analysis.cc}::CheckMapsHelper(), v8::internal::compiler::CheckMapsParametersOf(), v8::internal::compiler::MachineGraph::common(), v8::internal::compiler::CompareMapsParametersOf(), v8::internal::compiler::EscapeAnalysisTracker::Scope::ContextInput(), v8::internal::compiler::EscapeAnalysisTracker::Scope::CurrentNode(), v8::internal::compiler::MachineGraph::Dead(), v8::internal::compiler::StateValuesAccess::iterator::done(), v8::internal::compiler::ElementAccessOf(), v8::internal::ElementSizeLog2Of(), v8::internal::compiler::ElementsTransitionWithMultipleSourcesOf(), v8::internal::compiler::FieldAccessOf(), v8::internal::compiler::VirtualObject::FieldAt(), v8::internal::compiler::EscapeAnalysisTracker::Scope::FrameStateMightLazyDeopt(), v8::internal::compiler::VariableTracker::Scope::Get(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::EscapeAnalysisTracker::Scope::GetVirtualObject(), v8::internal::compiler::MachineGraph::graph(), v8::internal::compiler::OperatorProperties::HasContextInput(), v8::internal::compiler::VirtualObject::HasEscaped(), v8::internal::compiler::ElementAccess::header_size, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::VirtualObject::id(), v8::internal::index, v8::internal::compiler::EscapeAnalysisTracker::Scope::InitVirtualObject(), v8::internal::compiler::Type::Is(), v8::internal::compiler::FieldAccess::is_bounded_size_access, v8::internal::IsNone(), v8::internal::compiler::kJavaScriptBuiltinContinuation, v8::internal::compiler::kJavaScriptBuiltinContinuationWithCatch, v8::internal::HeapObject::kMapOffset, v8::internal::compiler::kUnoptimizedFunction, v8::internal::length, LowerCompareMapsWithoutLoad(), v8::internal::compiler::ElementAccess::machine_type, v8::internal::compiler::CheckMapsParameters::maps(), v8::internal::compiler::EscapeAnalysisTracker::Scope::MarkForDeletion(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::StateValuesAccess::iterator::node(), v8::internal::compiler::SimplifiedOperatorBuilder::NumberEqual(), OffsetOfElementAt(), OffsetOfElementsAccess(), OffsetOfFieldAccess(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::Operator::opcode(), v8::internal::MachineType::representation(), v8::internal::compiler::CommonOperatorBuilder::Select(), v8::internal::compiler::VariableTracker::Scope::Set(), v8::internal::compiler::EscapeAnalysisTracker::Scope::SetEscaped(), v8::internal::compiler::EscapeAnalysisTracker::Scope::SetReplacement(), v8::internal::compiler::NodeProperties::SetType(), v8::internal::compiler::ReduceScope::SetValueChanged(), v8::internal::compiler::EscapeAnalysisTracker::Scope::SetVirtualObject(), v8::internal::compiler::JSGraph::simplified(), v8::internal::compiler::VirtualObject::size(), size(), v8::internal::compiler::ElementsTransitionWithMultipleSources::target(), v8::internal::compiler::ElementAccess::type, v8::internal::tracing::type, v8::internal::value, v8::internal::compiler::EscapeAnalysisTracker::Scope::ValueInput(), and v8::internal::compiler::Operator::ValueInputCount().
Referenced by v8::internal::compiler::EscapeAnalysis::Reduce().