v8::internal::anonymous_namespace{feedback-vector.cc} Namespace Reference
Functions
bool BuiltinHasKeyedAccessStoreMode (Builtin builtin)
KeyedAccessStoreMode KeyedAccessStoreModeForBuiltin (Builtin builtin)
Function Documentation
BuiltinHasKeyedAccessStoreMode()
bool v8::internal::anonymous_namespace{feedback-vector.cc}::BuiltinHasKeyedAccessStoreMode (Builtin builtin)
Definition at line 1274 of file feedback-vector.cc.
                                                     {
  DCHECK(Builtins::IsBuiltinId(builtin));
  switch (builtin) {
    case Builtin::kKeyedStoreIC_SloppyArguments_InBounds:
    case Builtin::kKeyedStoreIC_SloppyArguments_NoTransitionGrowAndHandleCOW:
    case Builtin::kKeyedStoreIC_SloppyArguments_NoTransitionIgnoreTypedArrayOOB:
    case Builtin::kKeyedStoreIC_SloppyArguments_NoTransitionHandleCOW:
    case Builtin::kStoreFastElementIC_InBounds:
    case Builtin::kStoreFastElementIC_NoTransitionGrowAndHandleCOW:
    case Builtin::kStoreFastElementIC_NoTransitionIgnoreTypedArrayOOB:
    case Builtin::kStoreFastElementIC_NoTransitionHandleCOW:
    case Builtin::kElementsTransitionAndStore_InBounds:
    case Builtin::kElementsTransitionAndStore_NoTransitionGrowAndHandleCOW:
    case Builtin::kElementsTransitionAndStore_NoTransitionIgnoreTypedArrayOOB:
    case Builtin::kElementsTransitionAndStore_NoTransitionHandleCOW:
      return true;
    default:
      return false;
  }
  UNREACHABLE();
}
References v8::internal::DCHECK(), v8::internal::Builtins::IsBuiltinId(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::FeedbackNexus::GetKeyedAccessStoreMode(), and KeyedAccessStoreModeForBuiltin().
KeyedAccessStoreModeForBuiltin()
KeyedAccessStoreMode v8::internal::anonymous_namespace{feedback-vector.cc}::KeyedAccessStoreModeForBuiltin (Builtin builtin)
Definition at line 1296 of file feedback-vector.cc.
                                                                     {
  DCHECK(BuiltinHasKeyedAccessStoreMode(builtin));
  switch (builtin) {
    case Builtin::kKeyedStoreIC_SloppyArguments_InBounds:
    case Builtin::kStoreFastElementIC_InBounds:
    case Builtin::kElementsTransitionAndStore_InBounds:
      return KeyedAccessStoreMode::kInBounds;
    case Builtin::kKeyedStoreIC_SloppyArguments_NoTransitionGrowAndHandleCOW:
    case Builtin::kStoreFastElementIC_NoTransitionGrowAndHandleCOW:
    case Builtin::kElementsTransitionAndStore_NoTransitionGrowAndHandleCOW:
      return KeyedAccessStoreMode::kGrowAndHandleCOW;
    case Builtin::kKeyedStoreIC_SloppyArguments_NoTransitionIgnoreTypedArrayOOB:
    case Builtin::kStoreFastElementIC_NoTransitionIgnoreTypedArrayOOB:
    case Builtin::kElementsTransitionAndStore_NoTransitionIgnoreTypedArrayOOB:
      return KeyedAccessStoreMode::kIgnoreTypedArrayOOB;
    case Builtin::kKeyedStoreIC_SloppyArguments_NoTransitionHandleCOW:
    case Builtin::kStoreFastElementIC_NoTransitionHandleCOW:
    case Builtin::kElementsTransitionAndStore_NoTransitionHandleCOW:
      return KeyedAccessStoreMode::kHandleCOW;
    default:
      UNREACHABLE();
  }
}
References BuiltinHasKeyedAccessStoreMode(), v8::internal::DCHECK(), v8::internal::kGrowAndHandleCOW, v8::internal::kHandleCOW, v8::internal::kIgnoreTypedArrayOOB, v8::internal::kInBounds, and v8::internal::UNREACHABLE().
Referenced by v8::internal::FeedbackNexus::GetKeyedAccessStoreMode().