v8::internal::anonymous_namespace{js-display-names.cc} Namespace Reference
Classes
class LocaleDisplayNamesCommon
class LanguageNames
class RegionNames
class ScriptNames
class KeyValueDisplayNames
class CurrencyNames
class CalendarNames
class DateTimeFieldNames
struct CheckCalendar
Enumerations
enum class Type {
kUndefined
, kLanguage
, kRegion
, kScript
,
kCurrency
, kCalendar
, kDateTimeField
 }
Functions
bool IsUnicodeScriptSubtag (const std::string &value)
bool IsUnicodeRegionSubtag (const std::string &value)
UDisplayContext ToUDisplayContext (JSDisplayNames::Style style)
UDateTimePGDisplayWidth StyleToUDateTimePGDisplayWidth (JSDisplayNames::Style style)
UDateTimePatternField StringToUDateTimePatternField (const char *code)
DisplayNamesInternal * CreateInternal (const icu::Locale &locale, JSDisplayNames::Style style, Type type, bool fallback, bool dialect)
Enumeration Type Documentation
Type
enum v8::internal::anonymous_namespace{js-display-names.cc}::Type [strong]
Enumerator
kUndefined
kLanguage
kRegion
kScript
kCurrency
kCalendar
kDateTimeField
Definition at line 40 of file js-display-names.cc.
                {
  kUndefined,
  kLanguage,
  kRegion,
  kScript,
  kCurrency,
  kCalendar,
  kDateTimeField
};
Function Documentation
CreateInternal()
DisplayNamesInternal* v8::internal::anonymous_namespace{js-display-names.cc}::CreateInternal (const icu::Locale & locale, JSDisplayNames::Style style, Type type, bool fallback, bool dialect)
Definition at line 380 of file js-display-names.cc.
                                                                  {
  switch (type) {
    case Type::kLanguage:
      return new LanguageNames(locale, style, fallback, dialect);
    case Type::kRegion:
      return new RegionNames(locale, style, fallback, false);
    case Type::kScript:
      return new ScriptNames(locale, style, fallback, false);
    case Type::kCurrency:
      return new CurrencyNames(locale, style, fallback, false);
    case Type::kCalendar:
      return new CalendarNames(locale, style, fallback, false);
    case Type::kDateTimeField:
      return new DateTimeFieldNames(locale, style, fallback);
    default:
      UNREACHABLE();
  }
}
References v8::internal::tracing::type, and v8::internal::UNREACHABLE().
Referenced by v8::internal::JSDisplayNames::New().
IsUnicodeRegionSubtag()
bool v8::internal::anonymous_namespace{js-display-names.cc}::IsUnicodeRegionSubtag (const std::string & value)
Definition at line 57 of file js-display-names.cc.
                                                   {
  if (value.empty()) return false;
  UErrorCode status = U_ZERO_ERROR;
  icu::LocaleBuilder builder;
  builder.setRegion(value).build(status);
  return U_SUCCESS(status);
}
References v8::internal::status, and v8::internal::value.
Referenced by v8::internal::anonymous_namespace{js-display-names.cc}::RegionNames::of().
IsUnicodeScriptSubtag()
bool v8::internal::anonymous_namespace{js-display-names.cc}::IsUnicodeScriptSubtag (const std::string & value)
Definition at line 50 of file js-display-names.cc.
                                                   {
  UErrorCode status = U_ZERO_ERROR;
  icu::LocaleBuilder builder;
  builder.setScript(value).build(status);
  return U_SUCCESS(status);
}
References v8::internal::status, and v8::internal::value.
Referenced by v8::internal::anonymous_namespace{js-display-names.cc}::ScriptNames::of().
StringToUDateTimePatternField()
UDateTimePatternField v8::internal::anonymous_namespace{js-display-names.cc}::StringToUDateTimePatternField (const char * code)
Definition at line 308 of file js-display-names.cc.
                                                                      {
  switch (code[0]) {
    case 'd':
      if (strcmp(code, "day") == 0) return UDATPG_DAY_FIELD;
      if (strcmp(code, "dayPeriod") == 0) return UDATPG_DAYPERIOD_FIELD;
      break;
    case 'e':
      if (strcmp(code, "era") == 0) return UDATPG_ERA_FIELD;
      break;
    case 'h':
      if (strcmp(code, "hour") == 0) return UDATPG_HOUR_FIELD;
      break;
    case 'm':
      if (strcmp(code, "minute") == 0) return UDATPG_MINUTE_FIELD;
      if (strcmp(code, "month") == 0) return UDATPG_MONTH_FIELD;
      break;
    case 'q':
      if (strcmp(code, "quarter") == 0) return UDATPG_QUARTER_FIELD;
      break;
    case 's':
      if (strcmp(code, "second") == 0) return UDATPG_SECOND_FIELD;
      break;
    case 't':
      if (strcmp(code, "timeZoneName") == 0) return UDATPG_ZONE_FIELD;
      break;
    case 'w':
      if (strcmp(code, "weekOfYear") == 0) return UDATPG_WEEK_OF_YEAR_FIELD;
      if (strcmp(code, "weekday") == 0) return UDATPG_WEEKDAY_FIELD;
      break;
    case 'y':
      if (strcmp(code, "year") == 0) return UDATPG_YEAR_FIELD;
      break;
    default:
      break;
  }
  return UDATPG_FIELD_COUNT;
}
References code.
Referenced by v8::internal::anonymous_namespace{js-display-names.cc}::DateTimeFieldNames::of().
StyleToUDateTimePGDisplayWidth()
UDateTimePGDisplayWidth v8::internal::anonymous_namespace{js-display-names.cc}::StyleToUDateTimePGDisplayWidth (JSDisplayNames::Style style)
Definition at line 296 of file js-display-names.cc.
                               {
  switch (style) {
    case JSDisplayNames::Style::kLong:
      return UDATPG_WIDE;
    case JSDisplayNames::Style::kShort:
      return UDATPG_ABBREVIATED;
    case JSDisplayNames::Style::kNarrow:
      return UDATPG_NARROW;
  }
}
References v8::internal::JSDisplayNames::kLong, v8::internal::JSDisplayNames::kNarrow, and v8::internal::JSDisplayNames::kShort.
ToUDisplayContext()
UDisplayContext v8::internal::anonymous_namespace{js-display-names.cc}::ToUDisplayContext (JSDisplayNames::Style style)
Definition at line 65 of file js-display-names.cc.
                                                             {
  switch (style) {
    case JSDisplayNames::Style::kLong:
      return UDISPCTX_LENGTH_FULL;
    case JSDisplayNames::Style::kShort:
    case JSDisplayNames::Style::kNarrow:
      return UDISPCTX_LENGTH_SHORT;
  }
}
References v8::internal::JSDisplayNames::kLong, v8::internal::JSDisplayNames::kNarrow, and v8::internal::JSDisplayNames::kShort.
Referenced by v8::internal::anonymous_namespace{js-display-names.cc}::LocaleDisplayNamesCommon::LocaleDisplayNamesCommon().