v8::internal::compiler::anonymous_namespace{code-generator-mips64.cc} Namespace Reference
Classes
class OutOfLineRecordWrite
Functions
CREATE_OOL_CLASS (OutOfLineFloat32Max, Float32MaxOutOfLine, FPURegister)
CREATE_OOL_CLASS (OutOfLineFloat32Min, Float32MinOutOfLine, FPURegister)
CREATE_OOL_CLASS (OutOfLineFloat64Max, Float64MaxOutOfLine, FPURegister)
CREATE_OOL_CLASS (OutOfLineFloat64Min, Float64MinOutOfLine, FPURegister)
Condition FlagsConditionToConditionCmp (FlagsCondition condition)
Condition FlagsConditionToConditionTst (FlagsCondition condition)
Condition FlagsConditionToConditionOvf (FlagsCondition condition)
FPUCondition FlagsConditionToConditionCmpFPU (bool *predicate, FlagsCondition condition)
void AdjustStackPointerForTailCall (MacroAssembler *masm, FrameAccessState *state, int new_slot_above_sp, bool allow_shrinkage=true)
bool Is32BitOperand (InstructionOperand *operand)
bool Use32BitMove (InstructionOperand *source, InstructionOperand *destination)
Function Documentation
AdjustStackPointerForTailCall()
void v8::internal::compiler::anonymous_namespace{code-generator-mips64.cc}::AdjustStackPointerForTailCall (MacroAssembler * masm, FrameAccessState * state, int new_slot_above_sp, bool allow_shrinkage = true)
Definition at line 518 of file code-generator-mips64.cc.
                                                                {
  int current_sp_offset = state->GetSPToFPSlotCount() +
                          StandardFrameConstants::kFixedSlotCountAboveFp;
  int stack_slot_delta = new_slot_above_sp - current_sp_offset;
  if (stack_slot_delta > 0) {
    masm->Dsubu(sp, sp, stack_slot_delta * kSystemPointerSize);
    state->IncreaseSPDelta(stack_slot_delta);
  } else if (allow_shrinkage && stack_slot_delta < 0) {
    masm->Daddu(sp, sp, -stack_slot_delta * kSystemPointerSize);
    state->IncreaseSPDelta(stack_slot_delta);
  }
}
References v8::internal::compiler::FrameAccessState::GetSPToFPSlotCount(), v8::internal::compiler::FrameAccessState::IncreaseSPDelta(), v8::internal::CommonFrameConstants::kFixedSlotCountAboveFp, and v8::internal::kSystemPointerSize.
CREATE_OOL_CLASS() [1/4]
v8::internal::compiler::anonymous_namespace{code-generator-mips64.cc}::CREATE_OOL_CLASS (OutOfLineFloat32Max , Float32MaxOutOfLine , FPURegister)
CREATE_OOL_CLASS() [2/4]
v8::internal::compiler::anonymous_namespace{code-generator-mips64.cc}::CREATE_OOL_CLASS (OutOfLineFloat32Min , Float32MinOutOfLine , FPURegister)
CREATE_OOL_CLASS() [3/4]
v8::internal::compiler::anonymous_namespace{code-generator-mips64.cc}::CREATE_OOL_CLASS (OutOfLineFloat64Max , Float64MaxOutOfLine , FPURegister)
CREATE_OOL_CLASS() [4/4]
v8::internal::compiler::anonymous_namespace{code-generator-mips64.cc}::CREATE_OOL_CLASS (OutOfLineFloat64Min , Float64MinOutOfLine , FPURegister)
FlagsConditionToConditionCmp()
Condition v8::internal::compiler::anonymous_namespace{code-generator-mips64.cc}::FlagsConditionToConditionCmp (FlagsCondition condition)
Definition at line 221 of file code-generator-mips64.cc.
                                                                 {
  switch (condition) {
    case kEqual:
      return eq;
    case kNotEqual:
      return ne;
    case kSignedLessThan:
      return lt;
    case kSignedGreaterThanOrEqual:
      return ge;
    case kSignedLessThanOrEqual:
      return le;
    case kSignedGreaterThan:
      return gt;
    case kUnsignedLessThan:
      return lo;
    case kUnsignedGreaterThanOrEqual:
      return hs;
    case kUnsignedLessThanOrEqual:
      return ls;
    case kUnsignedGreaterThan:
      return hi;
    case kUnorderedEqual:
    case kUnorderedNotEqual:
      break;
    default:
      break;
  }
  UNREACHABLE();
}
References v8::internal::eq, v8::internal::ge, v8::internal::gt, v8::internal::hi, v8::internal::hs, v8::internal::compiler::kEqual, v8::internal::compiler::kNotEqual, v8::internal::compiler::kSignedGreaterThan, v8::internal::compiler::kSignedGreaterThanOrEqual, v8::internal::compiler::kSignedLessThan, v8::internal::compiler::kSignedLessThanOrEqual, v8::internal::compiler::kUnorderedEqual, v8::internal::compiler::kUnorderedNotEqual, v8::internal::compiler::kUnsignedGreaterThan, v8::internal::compiler::kUnsignedGreaterThanOrEqual, v8::internal::compiler::kUnsignedLessThan, v8::internal::compiler::kUnsignedLessThanOrEqual, v8::internal::le, v8::internal::lo, v8::internal::ls, v8::internal::lt, v8::internal::ne, and v8::internal::UNREACHABLE().
FlagsConditionToConditionCmpFPU()
FPUCondition v8::internal::compiler::anonymous_namespace{code-generator-mips64.cc}::FlagsConditionToConditionCmpFPU (bool * predicate, FlagsCondition condition)
Definition at line 276 of file code-generator-mips64.cc.
                                                                       {
  switch (condition) {
    case kEqual:
      *predicate = true;
      return EQ;
    case kNotEqual:
      *predicate = false;
      return EQ;
    case kUnsignedLessThan:
    case kFloatLessThan:
      *predicate = true;
      return OLT;
    case kUnsignedGreaterThanOrEqual:
      *predicate = false;
      return OLT;
    case kUnsignedLessThanOrEqual:
    case kFloatLessThanOrEqual:
      *predicate = true;
      return OLE;
    case kUnsignedGreaterThan:
      *predicate = false;
      return OLE;
    case kFloatGreaterThan:
      *predicate = false;
      return ULE;
    case kFloatGreaterThanOrEqual:
      *predicate = false;
      return ULT;
    case kFloatLessThanOrUnordered:
      *predicate = true;
      return ULT;
    case kFloatGreaterThanOrUnordered:
      *predicate = false;
      return OLE;
    case kFloatGreaterThanOrEqualOrUnordered:
      *predicate = false;
      return OLT;
    case kFloatLessThanOrEqualOrUnordered:
      *predicate = true;
      return ULE;
    case kUnorderedEqual:
    case kUnorderedNotEqual:
      *predicate = true;
      break;
    default:
      *predicate = true;
      break;
  }
  UNREACHABLE();
}
References v8::internal::EQ, v8::internal::compiler::kEqual, v8::internal::compiler::kFloatGreaterThan, v8::internal::compiler::kFloatGreaterThanOrEqual, v8::internal::compiler::kFloatGreaterThanOrEqualOrUnordered, v8::internal::compiler::kFloatGreaterThanOrUnordered, v8::internal::compiler::kFloatLessThan, v8::internal::compiler::kFloatLessThanOrEqual, v8::internal::compiler::kFloatLessThanOrEqualOrUnordered, v8::internal::compiler::kFloatLessThanOrUnordered, v8::internal::compiler::kNotEqual, v8::internal::compiler::kUnorderedEqual, v8::internal::compiler::kUnorderedNotEqual, v8::internal::compiler::kUnsignedGreaterThan, v8::internal::compiler::kUnsignedGreaterThanOrEqual, v8::internal::compiler::kUnsignedLessThan, v8::internal::compiler::kUnsignedLessThanOrEqual, v8::internal::OLE, v8::internal::OLT, v8::internal::ULE, v8::internal::ULT, and v8::internal::UNREACHABLE().
FlagsConditionToConditionOvf()
Condition v8::internal::compiler::anonymous_namespace{code-generator-mips64.cc}::FlagsConditionToConditionOvf (FlagsCondition condition)
Definition at line 264 of file code-generator-mips64.cc.
                                                                 {
  switch (condition) {
    case kOverflow:
      return ne;
    case kNotOverflow:
      return eq;
    default:
      break;
  }
  UNREACHABLE();
}
References v8::internal::eq, v8::internal::compiler::kNotOverflow, v8::internal::compiler::kOverflow, v8::internal::ne, and v8::internal::UNREACHABLE().
FlagsConditionToConditionTst()
Condition v8::internal::compiler::anonymous_namespace{code-generator-mips64.cc}::FlagsConditionToConditionTst (FlagsCondition condition)
Definition at line 252 of file code-generator-mips64.cc.
                                                                 {
  switch (condition) {
    case kNotEqual:
      return ne;
    case kEqual:
      return eq;
    default:
      break;
  }
  UNREACHABLE();
}
References v8::internal::eq, v8::internal::compiler::kEqual, v8::internal::compiler::kNotEqual, v8::internal::ne, and v8::internal::UNREACHABLE().
Is32BitOperand()
bool v8::internal::compiler::anonymous_namespace{code-generator-mips64.cc}::Is32BitOperand (InstructionOperand * operand)
Definition at line 4545 of file code-generator-mips64.cc.
                                                 {
  DCHECK(operand->IsStackSlot() || operand->IsRegister());
  MachineRepresentation mr = LocationOperand::cast(operand)->representation();
  return mr == MachineRepresentation::kWord32 ||
         mr == MachineRepresentation::kCompressed ||
         mr == MachineRepresentation::kCompressedPointer;
}
References v8::internal::compiler::LocationOperand::cast(), v8::internal::DCHECK(), v8::internal::compiler::InstructionOperand::IsRegister(), v8::internal::compiler::InstructionOperand::IsStackSlot(), v8::internal::kCompressed, v8::internal::kCompressedPointer, v8::internal::kWord32, and v8::internal::compiler::LocationOperand::representation().
Referenced by Use32BitMove().
Use32BitMove()
bool v8::internal::compiler::anonymous_namespace{code-generator-mips64.cc}::Use32BitMove (InstructionOperand * source, InstructionOperand * destination)
Definition at line 4555 of file code-generator-mips64.cc.
                                                                               {
  return Is32BitOperand(source) && Is32BitOperand(destination);
}
References Is32BitOperand().