v8::internal::anonymous_namespace{string-table.cc} Namespace Reference
Classes
class CharBuffer
Functions
void SetInternalizedReference (Isolate *isolate, Tagged< String > string, Tagged< String > internalized)
Function Documentation
SetInternalizedReference()
void v8::internal::anonymous_namespace{string-table.cc}::SetInternalizedReference (Isolate * isolate, Tagged< String > string, Tagged< String > internalized)
Definition at line 292 of file string-table.cc.
                                                           {
  DCHECK(!IsThinString(string));
  DCHECK(!IsInternalizedString(string));
  DCHECK(IsInternalizedString(internalized));
  DCHECK(!internalized->HasInternalizedForwardingIndex(kAcquireLoad));
  if (string->IsShared() || v8_flags.always_use_string_forwarding_table) {
    uint32_t field = string->raw_hash_field(kAcquireLoad);
    // Don't use the forwarding table for strings that have an integer index.
    // Using the hash field for the integer index is more beneficial than
    // using it to store the forwarding index to the internalized string.
    if (Name::IsIntegerIndex(field)) return;
    // Check one last time if we already have an internalized forwarding index
    // to prevent too many copies of the string in the forwarding table.
    if (Name::IsInternalizedForwardingIndex(field)) return;
    // If we already have an entry for an external resource in the table, update
    // the entry instead of creating a new one. There is no guarantee that we
    // will always update existing records instead of creating new ones, but
    // races should be rare.
    if (Name::IsForwardingIndex(field)) {
      const int forwarding_index =
          Name::ForwardingIndexValueBits::decode(field);
      isolate->string_forwarding_table()->UpdateForwardString(forwarding_index,
                                                              internalized);
      // Update the forwarding index type to include internalized.
      field = Name::IsInternalizedForwardingIndexBit::update(field, true);
      string->set_raw_hash_field(field, kReleaseStore);
    } else {
      const int forwarding_index =
          isolate->string_forwarding_table()->AddForwardString(string,
                                                               internalized);
      string->set_raw_hash_field(
          String::CreateInternalizedForwardingIndex(forwarding_index),
          kReleaseStore);
    }
  } else {
    DCHECK(!string->HasForwardingIndex(kAcquireLoad));
    string->MakeThin(isolate, internalized);
  }
}
References v8::internal::StringForwardingTable::AddForwardString(), v8::internal::Name::CreateInternalizedForwardingIndex(), v8::internal::DCHECK(), v8::base::BitField< T, shift, size, U >::decode(), v8::internal::Name::IsForwardingIndex(), v8::internal::Name::IsIntegerIndex(), v8::internal::Name::IsInternalizedForwardingIndex(), v8::internal::InstanceTypeChecker::IsInternalizedString(), v8::internal::InstanceTypeChecker::IsThinString(), v8::kAcquireLoad, v8::kReleaseStore, v8::internal::string, v8::internal::Isolate::string_forwarding_table(), v8::base::BitField< T, shift, size, U >::update(), v8::internal::StringForwardingTable::UpdateForwardString(), and v8::internal::v8_flags.
Referenced by v8::internal::StringTable::LookupString(), and v8::internal::StringTable::Data::TryStringToIndexOrLookupExisting().