v8::base::anonymous_namespace{platform-darwin.cc} Namespace Reference
Functions
vm_prot_t GetVMProtFromMemoryPermission (OS::MemoryPermission access)
kern_return_t mach_vm_map_wrapper (mach_vm_address_t *address, mach_vm_size_t size, int flags, mach_port_t port, memory_object_offset_t offset, vm_prot_t prot)
Function Documentation
GetVMProtFromMemoryPermission()
vm_prot_t v8::base::anonymous_namespace{platform-darwin.cc}::GetVMProtFromMemoryPermission (OS::MemoryPermission access)
Definition at line 53 of file platform-darwin.cc.
                                                                   {
  switch (access) {
    case OS::MemoryPermission::kNoAccess:
    case OS::MemoryPermission::kNoAccessWillJitLater:
      return VM_PROT_NONE;
    case OS::MemoryPermission::kRead:
      return VM_PROT_READ;
    case OS::MemoryPermission::kReadWrite:
      return VM_PROT_READ | VM_PROT_WRITE;
    case OS::MemoryPermission::kReadWriteExecute:
      return VM_PROT_READ | VM_PROT_WRITE | VM_PROT_EXECUTE;
    case OS::MemoryPermission::kReadExecute:
      return VM_PROT_READ | VM_PROT_EXECUTE;
  }
  UNREACHABLE();
}
References v8::base::OS::kNoAccess, v8::base::OS::kNoAccessWillJitLater, v8::base::OS::kRead, v8::base::OS::kReadExecute, v8::base::OS::kReadWrite, v8::base::OS::kReadWriteExecute, and UNREACHABLE.
Referenced by v8::base::OS::AllocateShared(), v8::base::AddressSpaceReservation::AllocateShared(), and v8::base::OS::RemapPages().
mach_vm_map_wrapper()
kern_return_t v8::base::anonymous_namespace{platform-darwin.cc}::mach_vm_map_wrapper (mach_vm_address_t * address, mach_vm_size_t size, int flags, mach_port_t port, memory_object_offset_t offset, vm_prot_t prot)
Definition at line 70 of file platform-darwin.cc.
                                                  {
  vm_prot_t current_prot = prot;
  vm_prot_t maximum_prot = current_prot;
  return mach_vm_map(mach_task_self(), address, size, 0, flags, port, offset,
                     FALSE, current_prot, maximum_prot, VM_INHERIT_NONE);
}
References flags(), mach_vm_map(), and size().
Referenced by v8::base::OS::AllocateShared(), and v8::base::AddressSpaceReservation::AllocateShared().