v8::internal::maglev::anonymous_namespace{maglev-ir.cc} Namespace Reference
Classes
struct Do_not_use_kScratchRegister_in_arch_independent_code
struct Do_not_use_kScratchDoubleRegister_in_arch_independent_code
class MaybeUnparkForPrint
Functions
bool IsStoreToNonEscapedObject (const NodeBase *node)
void PrintInputs (std::ostream &os, MaglevGraphLabeller *graph_labeller, const NodeBase *node)
void PrintResult (std::ostream &os, MaglevGraphLabeller *graph_labeller, const NodeBase *node)
void PrintResult (std::ostream &os, MaglevGraphLabeller *graph_labeller, const ValueNode *node)
void PrintTargets (std::ostream &os, MaglevGraphLabeller *graph_labeller, const NodeBase *node)
void PrintTargets (std::ostream &os, MaglevGraphLabeller *graph_labeller, const UnconditionalControlNode *node)
void PrintTargets (std::ostream &os, MaglevGraphLabeller *graph_labeller, const BranchControlNode *node)
void PrintTargets (std::ostream &os, MaglevGraphLabeller *graph_labeller, const Switch *node)
template<typename NodeT >
void PrintImpl (std::ostream &os, MaglevGraphLabeller *graph_labeller, const NodeT *node, bool skip_targets)
bool RootToBoolean (RootIndex index)
Variables
struct v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::Do_not_use_kScratchRegister_in_arch_independent_code kScratchRegister
struct v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::Do_not_use_kScratchDoubleRegister_in_arch_independent_code kScratchDoubleRegister
Function Documentation
IsStoreToNonEscapedObject()
bool v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::IsStoreToNonEscapedObject (const NodeBase * node)
Definition at line 176 of file maglev-ir.cc.
                                                     {
  if (CanBeStoreToNonEscapedObject(node->opcode())) {
    DCHECK_GT(node->input_count(), 0);
    if (InlinedAllocation* alloc =
            node->input(0).node()->template TryCast<InlinedAllocation>()) {
      return alloc->HasBeenAnalysed() && alloc->HasBeenElided();
    }
  }
  return false;
}
References v8::internal::maglev::CanBeStoreToNonEscapedObject(), DCHECK_GT, v8::internal::maglev::NodeBase::input(), v8::internal::maglev::NodeBase::input_count(), v8::internal::maglev::Input::node(), and v8::internal::maglev::NodeBase::opcode().
Referenced by PrintImpl().
PrintImpl()
template<typename NodeT >
void v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::PrintImpl (std::ostream & os, MaglevGraphLabeller * graph_labeller, const NodeT * node, bool skip_targets)
Definition at line 274 of file maglev-ir.cc.
                                                     {
  MaybeUnparkForPrint unpark;
  os << node->opcode();
  node->PrintParams(os, graph_labeller);
  PrintInputs(os, graph_labeller, node);
  PrintResult(os, graph_labeller, node);
  if (IsStoreToNonEscapedObject(node)) {
    os << " 🪦";
  }
  if (!skip_targets) {
    PrintTargets(os, graph_labeller, node);
  }
}
References IsStoreToNonEscapedObject(), v8::internal::maglev::NodeTMixin< Base, Derived >::opcode(), PrintInputs(), PrintResult(), and PrintTargets().
PrintInputs()
void v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::PrintInputs (std::ostream & os, MaglevGraphLabeller * graph_labeller, const NodeBase * node)
Definition at line 187 of file maglev-ir.cc.
                                       {
  if (!node->has_inputs()) return;
  os << " [";
  for (int i = 0; i < node->input_count(); i++) {
    if (i != 0) os << ", ";
    graph_labeller->PrintInput(os, node->input(i));
  }
  os << "]";
}
References v8::internal::maglev::NodeBase::has_inputs(), v8::internal::maglev::NodeBase::input(), v8::internal::maglev::NodeBase::input_count(), and v8::internal::maglev::MaglevGraphLabeller::PrintInput().
Referenced by PrintImpl().
PrintResult() [1/2]
void v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::PrintResult (std::ostream & os, MaglevGraphLabeller * graph_labeller, const NodeBase * node)
Definition at line 199 of file maglev-ir.cc.
                                       {}
PrintResult() [2/2]
void v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::PrintResult (std::ostream & os, MaglevGraphLabeller * graph_labeller, const ValueNode * node)
Definition at line 202 of file maglev-ir.cc.
                                        {
  os << " → " << node->result().operand();
  if (node->result().operand().IsAllocated() && node->is_spilled() &&
      node->spill_slot() != node->result().operand()) {
    os << " (spilled: " << node->spill_slot() << ")";
  }
  if (node->has_valid_live_range()) {
    os << ", live range: [" << node->live_range().start << "-"
       << node->live_range().end << "]";
  }
  if (!node->has_id()) {
    os << ", " << node->use_count() << " uses";
    if (const InlinedAllocation* alloc = node->TryCast<InlinedAllocation>()) {
      os << " (" << alloc->non_escaping_use_count() << " non escaping uses)";
      if (alloc->HasBeenAnalysed() && alloc->HasBeenElided()) {
        os << " 🪦";
      }
    } else if (!node->is_used()) {
      if (node->opcode() != Opcode::kAllocationBlock &&
          node->properties().is_required_when_unused()) {
        os << ", but required";
      } else {
        os << " 🪦";
      }
    }
  }
}
References v8::internal::maglev::ValueNode::LiveRange::end, v8::internal::maglev::NodeBase::has_id(), v8::internal::maglev::ValueNode::has_valid_live_range(), v8::internal::maglev::OpProperties::is_required_when_unused(), v8::internal::maglev::ValueNode::is_spilled(), v8::internal::maglev::ValueNode::is_used(), v8::internal::maglev::ValueNode::live_range(), v8::internal::maglev::NodeBase::opcode(), v8::internal::maglev::ValueLocation::operand(), v8::internal::maglev::NodeBase::properties(), v8::internal::maglev::ValueNode::result(), v8::internal::maglev::ValueNode::spill_slot(), v8::internal::maglev::ValueNode::LiveRange::start, v8::internal::maglev::NodeBase::TryCast(), and v8::internal::maglev::ValueNode::use_count().
Referenced by PrintImpl().
PrintTargets() [1/4]
void v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::PrintTargets (std::ostream & os, MaglevGraphLabeller * graph_labeller, const BranchControlNode * node)
Definition at line 239 of file maglev-ir.cc.
                                                 {
  os << " b" << node->if_true()->id() << " b" << node->if_false()->id();
}
References v8::internal::maglev::BasicBlock::id(), v8::internal::maglev::BranchControlNode::if_false(), and v8::internal::maglev::BranchControlNode::if_true().
PrintTargets() [2/4]
void v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::PrintTargets (std::ostream & os, MaglevGraphLabeller * graph_labeller, const NodeBase * node)
Definition at line 231 of file maglev-ir.cc.
                                        {}
PrintTargets() [3/4]
void v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::PrintTargets (std::ostream & os, MaglevGraphLabeller * graph_labeller, const Switch * node)
Definition at line 244 of file maglev-ir.cc.
                                      {
  for (int i = 0; i < node->size(); i++) {
    const BasicBlockRef& target = node->Cast<Switch>()->targets()[i];
    os << " b" << target.block_ptr()->id();
  }
  if (node->Cast<Switch>()->has_fallthrough()) {
    BasicBlock* fallthrough_target = node->Cast<Switch>()->fallthrough();
    os << " b" << fallthrough_target->id();
  }
}
References v8::internal::maglev::BasicBlockRef::block_ptr(), v8::internal::maglev::Switch::has_fallthrough(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::maglev::BasicBlock::id(), and v8::internal::maglev::Switch::size().
Referenced by PrintImpl().
PrintTargets() [4/4]
void v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::PrintTargets (std::ostream & os, MaglevGraphLabeller * graph_labeller, const UnconditionalControlNode * node)
Definition at line 234 of file maglev-ir.cc.
                                                        {
  os << " b" << node->target()->id();
}
References v8::internal::maglev::BasicBlock::id(), and v8::internal::maglev::UnconditionalControlNode::target().
RootToBoolean()
bool v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::RootToBoolean (RootIndex index)
Definition at line 289 of file maglev-ir.cc.
                                    {
  switch (index) {
    case RootIndex::kFalseValue:
    case RootIndex::kNullValue:
    case RootIndex::kUndefinedValue:
    case RootIndex::kNanValue:
    case RootIndex::kUndefinedNanValue:
    case RootIndex::kHoleNanValue:
    case RootIndex::kMinusZeroValue:
    case RootIndex::kempty_string:
#ifdef V8_ENABLE_WEBASSEMBLY
    case RootIndex::kWasmNull:
#endif
      return false;
    default:
      return true;
  }
}
References v8::internal::index.
Referenced by v8::internal::maglev::RootConstant::ToBoolean().
Variable Documentation
kScratchDoubleRegister
struct v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::Do_not_use_kScratchDoubleRegister_in_arch_independent_code v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::kScratchDoubleRegister
kScratchRegister
struct v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::Do_not_use_kScratchRegister_in_arch_independent_code v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::kScratchRegister