v8::internal::Heap::InsertIntoRememberedSetFromCode Namespace Reference
Functions
intptr_t DebugBreakAtEntry (Isolate *isolate, Address raw_sfi)
Address DebugGetCoverageInfo (Isolate *isolate, Address raw_sfi)
Function Documentation
DebugBreakAtEntry()
intptr_t v8::internal::Heap::InsertIntoRememberedSetFromCode::DebugBreakAtEntry (Isolate * isolate, Address raw_sfi)
Definition at line 521 of file external-reference.cc.
                                                              {
  DisallowGarbageCollection no_gc;
  Tagged<SharedFunctionInfo> sfi =
      Cast<SharedFunctionInfo>(Tagged<Object>(raw_sfi));
  return isolate->debug()->BreakAtEntry(sfi) ? 1 : 0;
}
References v8::internal::Debug::BreakAtEntry(), v8::internal::Isolate::debug(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
DebugGetCoverageInfo()
Address v8::internal::Heap::InsertIntoRememberedSetFromCode::DebugGetCoverageInfo (Isolate * isolate, Address raw_sfi)
Definition at line 528 of file external-reference.cc.
                                                                {
  DisallowGarbageCollection no_gc;
  Tagged<SharedFunctionInfo> sfi =
      Cast<SharedFunctionInfo>(Tagged<Object>(raw_sfi));
  std::optional<Tagged<DebugInfo>> debug_info =
      isolate->debug()->TryGetDebugInfo(sfi);
  if (debug_info.has_value() && debug_info.value()->HasCoverageInfo()) {
    return debug_info.value()->coverage_info().ptr();
  }
  return Smi::zero().ptr();
}
References v8::internal::Isolate::debug(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), v8::internal::Debug::TryGetDebugInfo(), and v8::internal::Smi::zero().