v8::internal::anonymous_namespace{frames.cc} Namespace Reference
Functions
Address AddressOf (const StackHandler *handler)
StackFrame::Type GetStateForFastCCallCallerFP (Isolate *isolate, Address fp, Address pc, Address pc_address, StackFrame::State *state)
std::optional< bool > IsInterpreterFramePc (Isolate *isolate, Address pc, StackFrame::State *state)
std::optional< Tagged< GcSafeCode > > GetContainingCode (Isolate *isolate, Address pc)
StackFrame::Type ComputeBuiltinFrameType (Tagged< GcSafeCode > code)
StackFrame::Type SafeStackFrameType (StackFrame::Type candidate)
void PrintIndex (StringStream *accumulator, StackFrame::PrintMode mode, int index)
const char * StringForStackFrameType (StackFrame::Type type)
void VisitSpillSlot (Isolate *isolate, RootVisitor *v, FullObjectSlot spill_slot)
void VisitSpillSlots (Isolate *isolate, RootVisitor *v, FullObjectSlot first_slot_offset, base::Vector< const uint8_t > tagged_slots)
SafepointEntry GetSafepointEntryFromCodeCache (Isolate *isolate, Address inner_pointer, InnerPointerToCodeCache::InnerPointerToCodeCacheEntry *entry)
MaglevSafepointEntry GetMaglevSafepointEntryFromCodeCache (Isolate *isolate, Address inner_pointer, InnerPointerToCodeCache::InnerPointerToCodeCacheEntry *entry)
void PrintFunctionSource (StringStream *accumulator, Tagged< SharedFunctionInfo > shared)
uint32_t PcAddressForHashing (Isolate *isolate, Address address)
constexpr int TopOfStackRegisterPaddingSlots ()
bool BuiltinContinuationModeIsWithCatch (BuiltinContinuationMode mode)
Function Documentation
AddressOf()
Address v8::internal::anonymous_namespace{frames.cc}::AddressOf (const StackHandler * handler)
Definition at line 60 of file frames.cc.
                                               {
  Address raw = handler->address();
#ifdef V8_USE_ADDRESS_SANITIZER
  // ASan puts C++-allocated StackHandler markers onto its fake stack.
  // We work around that by storing the real stack address in the "padding"
  // field. StackHandlers allocated from generated code have 0 as padding.
  Address padding =
      base::Memory<Address>(raw + StackHandlerConstants::kPaddingOffset);
  if (padding != 0) return padding;
#endif
  return raw;
}
References v8::internal::StackHandler::address(), and v8::internal::StackHandlerConstants::kPaddingOffset.
Referenced by v8::internal::StackHandlerIterator::done(), and v8::internal::StackHandlerIterator::StackHandlerIterator().
BuiltinContinuationModeIsWithCatch()
bool v8::internal::anonymous_namespace{frames.cc}::BuiltinContinuationModeIsWithCatch (BuiltinContinuationMode mode)
Definition at line 4184 of file frames.cc.
                                                                      {
  switch (mode) {
    case BuiltinContinuationMode::STUB:
    case BuiltinContinuationMode::JAVASCRIPT:
      return false;
    case BuiltinContinuationMode::JAVASCRIPT_WITH_CATCH:
    case BuiltinContinuationMode::JAVASCRIPT_HANDLE_EXCEPTION:
      return true;
  }
  UNREACHABLE();
}
References v8::internal::JAVASCRIPT, v8::internal::JAVASCRIPT_HANDLE_EXCEPTION, v8::internal::JAVASCRIPT_WITH_CATCH, mode(), v8::internal::STUB, and v8::internal::UNREACHABLE().
Referenced by v8::internal::BuiltinContinuationFrameInfo::BuiltinContinuationFrameInfo().
ComputeBuiltinFrameType()
StackFrame::Type v8::internal::anonymous_namespace{frames.cc}::ComputeBuiltinFrameType (Tagged< GcSafeCode > code)
Definition at line 836 of file frames.cc.
                                                                {
  if (code->is_interpreter_trampoline_builtin() ||
      code->is_baseline_trampoline_builtin()) {
    // Frames for baseline entry trampolines on the stack are still interpreted
    // frames.
    return StackFrame::INTERPRETED;
  } else if (code->is_baseline_leave_frame_builtin()) {
    return StackFrame::BASELINE;
  } else if (code->is_turbofanned()) {
    // TODO(bmeurer): We treat frames for BUILTIN Code objects as
    // OptimizedJSFrame for now (all the builtins with JavaScript linkage are
    // actually generated with TurboFan currently, so this is sound).
    return StackFrame::TURBOFAN_JS;
  }
  return StackFrame::BUILTIN;
}
References BUILTIN, and code.
Referenced by v8::internal::StackFrameIterator::ComputeStackFrameType().
GetContainingCode()
std::optional<Tagged<GcSafeCode> > v8::internal::anonymous_namespace{frames.cc}::GetContainingCode (Isolate * isolate, Address pc)
Definition at line 753 of file frames.cc.
                                                                {
  return isolate->inner_pointer_to_code_cache()->GetCacheEntry(pc)->code;
}
References v8::internal::InnerPointerToCodeCache::InnerPointerToCodeCacheEntry::code, v8::internal::InnerPointerToCodeCache::GetCacheEntry(), and v8::internal::Isolate::inner_pointer_to_code_cache().
Referenced by v8::internal::StackFrameIterator::ComputeStackFrameType(), and v8::internal::StackFrame::GcSafeLookupCodeAndOffset().
GetMaglevSafepointEntryFromCodeCache()
MaglevSafepointEntry v8::internal::anonymous_namespace{frames.cc}::GetMaglevSafepointEntryFromCodeCache (Isolate * isolate, Address inner_pointer, InnerPointerToCodeCache::InnerPointerToCodeCacheEntry * entry)
Definition at line 1639 of file frames.cc.
                                                                {
  if (!entry->maglev_safepoint_entry.is_initialized()) {
    entry->maglev_safepoint_entry = MaglevSafepointTable::FindEntry(
        isolate, entry->code.value(), inner_pointer);
    DCHECK(entry->maglev_safepoint_entry.is_initialized());
  } else {
    DCHECK_EQ(entry->maglev_safepoint_entry,
              MaglevSafepointTable::FindEntry(isolate, entry->code.value(),
                                              inner_pointer));
  }
  return entry->maglev_safepoint_entry;
}
References v8::internal::InnerPointerToCodeCache::InnerPointerToCodeCacheEntry::code, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::MaglevSafepointTable::FindEntry(), v8::internal::SafepointEntryBase::is_initialized(), and v8::internal::InnerPointerToCodeCache::InnerPointerToCodeCacheEntry::maglev_safepoint_entry.
Referenced by v8::internal::MaglevFrame::Iterate().
GetSafepointEntryFromCodeCache()
SafepointEntry v8::internal::anonymous_namespace{frames.cc}::GetSafepointEntryFromCodeCache (Isolate * isolate, Address inner_pointer, InnerPointerToCodeCache::InnerPointerToCodeCacheEntry * entry)
Definition at line 1624 of file frames.cc.
                                                                {
  if (!entry->safepoint_entry.is_initialized()) {
    entry->safepoint_entry =
        SafepointTable::FindEntry(isolate, entry->code.value(), inner_pointer);
    DCHECK(entry->safepoint_entry.is_initialized());
  } else {
    DCHECK_EQ(
        entry->safepoint_entry,
        SafepointTable::FindEntry(isolate, entry->code.value(), inner_pointer));
  }
  return entry->safepoint_entry;
}
References v8::internal::InnerPointerToCodeCache::InnerPointerToCodeCacheEntry::code, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::SafepointTable::FindEntry(), v8::internal::SafepointEntryBase::is_initialized(), and v8::internal::InnerPointerToCodeCache::InnerPointerToCodeCacheEntry::safepoint_entry.
Referenced by v8::internal::TypedFrame::Iterate(), and v8::internal::CommonFrame::IterateTurbofanJSOptimizedFrame().
GetStateForFastCCallCallerFP()
StackFrame::Type v8::internal::anonymous_namespace{frames.cc}::GetStateForFastCCallCallerFP (Isolate * isolate, Address fp, Address pc, Address pc_address, StackFrame::State * state)
Definition at line 240 of file frames.cc.
                                                                      {
  // 'Fast C calls' are a special type of C call where we call directly from
  // JS to C without an exit frame in between. The CEntryStub is responsible
  // for setting Isolate::c_entry_fp, meaning that it won't be set for fast C
  // calls. To keep the stack iterable, we store the FP and PC of the caller
  // of the fast C call on the isolate. This is guaranteed to be the topmost
  // JS frame, because fast C calls cannot call back into JS. We start
  // iterating the stack from this topmost JS frame.
  DCHECK_NE(kNullAddress, pc);
  state->fp = fp;
  state->sp = kNullAddress;
  state->pc_address = reinterpret_cast<Address*>(pc_address);
  state->callee_pc = kNullAddress;
  state->constant_pool_address = nullptr;
#if V8_ENABLE_WEBASSEMBLY
  if (wasm::WasmCode* code =
          wasm::GetWasmCodeManager()->LookupCode(isolate, pc)) {
    if (code->kind() == wasm::WasmCode::kWasmToJsWrapper) {
      return StackFrame::WASM_TO_JS;
    }
    DCHECK_EQ(code->kind(), wasm::WasmCode::kWasmFunction);
    return StackFrame::WASM;
  }
#endif // V8_ENABLE_WEBASSEMBLY
  return StackFrame::TURBOFAN_JS;
}
References v8::internal::StackFrame::State::callee_pc, code, v8::internal::StackFrame::State::constant_pool_address, DCHECK_EQ, DCHECK_NE, v8::internal::StackFrame::State::fp, v8::internal::wasm::GetWasmCodeManager(), v8::internal::kNullAddress, v8::internal::wasm::WasmCode::kWasmFunction, v8::internal::wasm::WasmCode::kWasmToJsWrapper, v8::internal::wasm::WasmCodeManager::LookupCode(), v8::internal::StackFrame::State::pc_address, and v8::internal::StackFrame::State::sp.
Referenced by v8::internal::EntryFrame::GetCallerState(), and v8::internal::StackFrameIterator::Reset().
IsInterpreterFramePc()
std::optional<bool> v8::internal::anonymous_namespace{frames.cc}::IsInterpreterFramePc (Isolate * isolate, Address pc, StackFrame::State * state)
Definition at line 426 of file frames.cc.
                                                                 {
  Builtin builtin = OffHeapInstructionStream::TryLookupCode(isolate, pc);
  if (builtin != Builtin::kNoBuiltinId &&
      (builtin == Builtin::kInterpreterEntryTrampoline ||
       builtin == Builtin::kInterpreterEnterAtBytecode ||
       builtin == Builtin::kInterpreterEnterAtNextBytecode)) {
    return true;
  } else if (isolate->interpreted_frames_native_stack()) {
    intptr_t marker = Memory<intptr_t>(
        state->fp + CommonFrameConstants::kContextOrFrameTypeOffset);
    MSAN_MEMORY_IS_INITIALIZED(
        state->fp + StandardFrameConstants::kFunctionOffset,
        kSystemPointerSize);
    Tagged<Object> maybe_function = Tagged<Object>(
        Memory<Address>(state->fp + StandardFrameConstants::kFunctionOffset));
    // There's no need to run a full ContainsSlow if we know the frame can't be
    // an InterpretedFrame, so we do these fast checks first
    if (StackFrame::IsTypeMarker(marker) || IsSmi(maybe_function)) {
      return false;
    } else if (!isolate->heap()->InSpaceSlow(pc, CODE_SPACE)) {
      return false;
    }
    if (!ThreadIsolation::CanLookupStartOfJitAllocationAt(pc)) {
      return {};
    }
    Tagged<Code> interpreter_entry_trampoline =
        isolate->heap()->FindCodeForInnerPointer(pc);
    return interpreter_entry_trampoline->is_interpreter_trampoline_builtin();
  } else {
    return false;
  }
}
References v8::internal::ThreadIsolation::CanLookupStartOfJitAllocationAt(), v8::internal::CODE_SPACE, v8::internal::Heap::FindCodeForInnerPointer(), v8::internal::StackFrame::State::fp, v8::internal::Isolate::heap(), v8::internal::Heap::InSpaceSlow(), v8::internal::Isolate::interpreted_frames_native_stack(), v8::internal::IsSmi(), v8::internal::StackFrame::IsTypeMarker(), v8::internal::CommonFrameConstants::kContextOrFrameTypeOffset, v8::internal::StandardFrameConstants::kFunctionOffset, v8::internal::kNoBuiltinId, v8::internal::kSystemPointerSize, MSAN_MEMORY_IS_INITIALIZED, v8::internal::Tagged< Object >, and v8::internal::OffHeapInstructionStream::TryLookupCode().
Referenced by v8::internal::StackFrameIteratorForProfiler::ComputeStackFrameType(), and v8::internal::StackFrameIteratorForProfiler::StackFrameIteratorForProfiler().
PcAddressForHashing()
uint32_t v8::internal::anonymous_namespace{frames.cc}::PcAddressForHashing (Isolate * isolate, Address address)
Definition at line 4125 of file frames.cc.
                                                                {
  uint32_t hashable_address;
  if (OffHeapInstructionStream::TryGetAddressForHashing(isolate, address,
                                                        &hashable_address)) {
    return hashable_address;
  }
  return ObjectAddressForHashing(address);
}
References v8::internal::ObjectAddressForHashing(), and v8::internal::OffHeapInstructionStream::TryGetAddressForHashing().
Referenced by v8::internal::InnerPointerToCodeCache::GetCacheEntry().
PrintFunctionSource()
void v8::internal::anonymous_namespace{frames.cc}::PrintFunctionSource (StringStream * accumulator, Tagged< SharedFunctionInfo > shared)
Definition at line 3954 of file frames.cc.
                                                            {
  if (v8_flags.max_stack_trace_source_length != 0) {
    std::ostringstream os;
    os << "--------- s o u r c e c o d e ---------\n"
       << SourceCodeOf(shared, v8_flags.max_stack_trace_source_length)
       << "\n-----------------------------------------\n";
    accumulator->Add(os.str().c_str());
  }
}
References v8::internal::StringStream::Add(), and v8::internal::v8_flags.
Referenced by v8::internal::JavaScriptFrame::Print().
PrintIndex()
void v8::internal::anonymous_namespace{frames.cc}::PrintIndex (StringStream * accumulator, StackFrame::PrintMode mode, int index)
Definition at line 1377 of file frames.cc.
                           {
  accumulator->Add((mode == StackFrame::OVERVIEW) ? "%5d: " : "[%d]: ", index);
}
References v8::internal::StringStream::Add(), v8::internal::index, mode(), and v8::internal::StackFrame::OVERVIEW.
Referenced by v8::internal::StackFrame::Print(), v8::internal::JavaScriptFrame::Print(), v8::internal::BuiltinExitFrame::Print(), v8::internal::ApiCallbackExitFrame::Print(), and v8::internal::ApiAccessorExitFrame::Print().
SafeStackFrameType()
StackFrame::Type v8::internal::anonymous_namespace{frames.cc}::SafeStackFrameType (StackFrame::Type candidate)
Definition at line 853 of file frames.cc.
                                                            {
  DCHECK_LE(static_cast<uintptr_t>(candidate), StackFrame::NUMBER_OF_TYPES);
  switch (candidate) {
    case StackFrame::API_ACCESSOR_EXIT:
    case StackFrame::API_CALLBACK_EXIT:
    case StackFrame::BUILTIN_CONTINUATION:
    case StackFrame::BUILTIN_EXIT:
    case StackFrame::CONSTRUCT:
    case StackFrame::FAST_CONSTRUCT:
    case StackFrame::CONSTRUCT_ENTRY:
    case StackFrame::ENTRY:
    case StackFrame::EXIT:
    case StackFrame::INTERNAL:
    case StackFrame::IRREGEXP:
    case StackFrame::JAVASCRIPT_BUILTIN_CONTINUATION:
    case StackFrame::JAVASCRIPT_BUILTIN_CONTINUATION_WITH_CATCH:
    case StackFrame::STUB:
      return candidate;
#if V8_ENABLE_WEBASSEMBLY
    case StackFrame::JS_TO_WASM:
    case StackFrame::STACK_SWITCH:
    case StackFrame::WASM:
    case StackFrame::WASM_DEBUG_BREAK:
    case StackFrame::WASM_EXIT:
    case StackFrame::WASM_LIFTOFF_SETUP:
    case StackFrame::WASM_TO_JS:
    case StackFrame::WASM_SEGMENT_START:
#if V8_ENABLE_DRUMBRAKE
    case StackFrame::C_WASM_ENTRY:
    case StackFrame::WASM_INTERPRETER_ENTRY:
#endif // V8_ENABLE_DRUMBRAKE
      return candidate;
#endif // V8_ENABLE_WEBASSEMBLY
    // Any other marker value is likely to be a bogus stack frame when being
    // called from the profiler (in particular, JavaScript frames, including
    // interpreted frames, should never have a StackFrame::Type marker).
    // Consider these frames "native".
    // TODO(jgruber): For the StackFrameIterator, I'm not sure this fallback
    // makes sense. Shouldn't we know how to handle all frames we encounter
    // there?
    case StackFrame::BASELINE:
    case StackFrame::BUILTIN:
    case StackFrame::INTERPRETED:
    case StackFrame::MAGLEV:
    case StackFrame::MANUAL:
    case StackFrame::NATIVE:
    case StackFrame::NO_FRAME_TYPE:
    case StackFrame::NUMBER_OF_TYPES:
    case StackFrame::TURBOFAN_JS:
    case StackFrame::TURBOFAN_STUB_WITH_CONTEXT:
#if V8_ENABLE_WEBASSEMBLY && !V8_ENABLE_DRUMBRAKE
    case StackFrame::C_WASM_ENTRY:
#endif // V8_ENABLE_WEBASSEMBLY && !V8_ENABLE_DRUMBRAKE
      return StackFrame::NATIVE;
  }
  UNREACHABLE();
}
References BUILTIN, CONSTRUCT_ENTRY, DCHECK_LE, ENTRY, v8::internal::StackFrame::MANUAL, v8::internal::StackFrame::NO_FRAME_TYPE, and v8::internal::UNREACHABLE().
Referenced by v8::internal::StackFrameIterator::ComputeStackFrameType(), and v8::internal::StackFrameIteratorForProfiler::ComputeStackFrameType().
StringForStackFrameType()
const char* v8::internal::anonymous_namespace{frames.cc}::StringForStackFrameType (StackFrame::Type type)
Definition at line 1382 of file frames.cc.
                                                         {
  switch (type) {
#define CASE(value, name) \
  case StackFrame::value: \
    return #name;
    STACK_FRAME_TYPE_LIST(CASE)
#undef CASE
    case StackFrame::NO_FRAME_TYPE:
      return "NoFrameType";
    default:
      UNREACHABLE();
  }
}
References CASE, v8::internal::StackFrame::NO_FRAME_TYPE, STACK_FRAME_TYPE_LIST, v8::internal::tracing::type, and v8::internal::UNREACHABLE().
Referenced by v8::internal::StackFrame::Print().
TopOfStackRegisterPaddingSlots()
constexpr int v8::internal::anonymous_namespace{frames.cc}::TopOfStackRegisterPaddingSlots () [constexpr]
Definition at line 4180 of file frames.cc.
                                               {
  return ArgumentPaddingSlots(1);
}
References v8::internal::ArgumentPaddingSlots().
Referenced by v8::internal::BuiltinContinuationFrameInfo::BuiltinContinuationFrameInfo(), v8::internal::ConstructStubFrameInfo::ConstructStubFrameInfo(), v8::internal::FastConstructStubFrameInfo::FastConstructStubFrameInfo(), and v8::internal::UnoptimizedFrameInfo::UnoptimizedFrameInfo().
VisitSpillSlot()
void v8::internal::anonymous_namespace{frames.cc}::VisitSpillSlot (Isolate * isolate, RootVisitor * v, FullObjectSlot spill_slot)
Definition at line 1525 of file frames.cc.
                                               {
#ifdef V8_COMPRESS_POINTERS
  PtrComprCageBase cage_base(isolate);
  bool was_compressed = false;
  // Spill slots may contain compressed values in which case the upper
  // 32-bits will contain zeros. In order to simplify handling of such
  // slots in GC we ensure that the slot always contains full value.
  // The spill slot may actually contain weak references so we load/store
  // values using spill_slot.location() in order to avoid dealing with
  // FullMaybeObjectSlots here.
  if (V8_EXTERNAL_CODE_SPACE_BOOL) {
    // When external code space is enabled the spill slot could contain both
    // InstructionStream and non-InstructionStream references, which have
    // different cage bases. So unconditional decompression of the value might
    // corrupt InstructionStream pointers. However, given that 1) the
    // InstructionStream pointers are never compressed by design (because
    // otherwise we wouldn't know which cage base to apply for
    // decompression, see respective DCHECKs in
    // RelocInfo::target_object()),
    // 2) there's no need to update the upper part of the full pointer
    // because if it was there then it'll stay the same,
    // we can avoid updating upper part of the spill slot if it already
    // contains full value.
    // TODO(v8:11880): Remove this special handling by enforcing builtins
    // to use CodeTs instead of InstructionStream objects.
    Address value = *spill_slot.location();
    if (!HAS_SMI_TAG(value) && value <= 0xffffffff) {
      // We don't need to update smi values or full pointers.
      was_compressed = true;
      *spill_slot.location() = V8HeapCompressionScheme::DecompressTagged(
          static_cast<Tagged_t>(value));
      if (DEBUG_BOOL) {
        // Ensure that the spill slot contains correct heap object.
        Tagged<HeapObject> raw =
            Cast<HeapObject>(Tagged<Object>(*spill_slot.location()));
        MapWord map_word = raw->map_word(cage_base, kRelaxedLoad);
        Tagged<HeapObject> forwarded = map_word.IsForwardingAddress()
                                           ? map_word.ToForwardingAddress(raw)
                                           : raw;
        bool is_self_forwarded =
            HeapLayout::IsSelfForwarded(forwarded, cage_base);
        if (is_self_forwarded) {
          // The object might be in a self-forwarding state if it's located
          // in new large object space. GC will fix this at a later stage.
          CHECK(
              MemoryChunk::FromHeapObject(forwarded)->InNewLargeObjectSpace() ||
              MemoryChunk::FromHeapObject(forwarded)->IsQuarantined());
        } else {
          Tagged<HeapObject> forwarded_map = forwarded->map(cage_base);
          // The map might be forwarded as well.
          MapWord fwd_map_map_word =
              forwarded_map->map_word(cage_base, kRelaxedLoad);
          if (fwd_map_map_word.IsForwardingAddress()) {
            forwarded_map = fwd_map_map_word.ToForwardingAddress(forwarded_map);
          }
          CHECK(IsMap(forwarded_map, cage_base));
        }
      }
    }
  } else {
    Address slot_contents = *spill_slot.location();
    Tagged_t compressed_value = static_cast<Tagged_t>(slot_contents);
    if (!HAS_SMI_TAG(compressed_value)) {
      was_compressed = slot_contents <= 0xFFFFFFFF;
      // We don't need to update smi values.
      *spill_slot.location() =
          V8HeapCompressionScheme::DecompressTagged(compressed_value);
    }
  }
#endif
  v->VisitRootPointer(Root::kStackRoots, nullptr, spill_slot);
#if V8_COMPRESS_POINTERS
  if (was_compressed) {
    // Restore compression. Generated code should be able to trust that
    // compressed spill slots remain compressed.
    *spill_slot.location() =
        V8HeapCompressionScheme::CompressObject(*spill_slot.location());
  }
#endif
}
References CHECK, v8::internal::V8HeapCompressionSchemeImpl< Cage >::CompressObject(), DEBUG_BOOL, v8::internal::V8HeapCompressionSchemeImpl< Cage >::DecompressTagged(), v8::internal::MemoryChunk::FromHeapObject(), HAS_SMI_TAG, v8::internal::MapWord::IsForwardingAddress(), v8::internal::HeapLayout::IsSelfForwarded(), v8::kRelaxedLoad, v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::location(), v8::internal::MapWord::ToForwardingAddress(), V8_EXTERNAL_CODE_SPACE_BOOL, v8::internal::value, and v8::internal::RootVisitor::VisitRootPointer().
Referenced by v8::internal::MaglevFrame::Iterate(), and VisitSpillSlots().
VisitSpillSlots()
void v8::internal::anonymous_namespace{frames.cc}::VisitSpillSlots (Isolate * isolate, RootVisitor * v, FullObjectSlot first_slot_offset, base::Vector< const uint8_t > tagged_slots)
Definition at line 1609 of file frames.cc.
                                                             {
  FullObjectSlot slot_offset = first_slot_offset;
  for (uint8_t bits : tagged_slots) {
    while (bits) {
      const int bit = base::bits::CountTrailingZeros(bits);
      bits &= ~(1 << bit);
      FullObjectSlot spill_slot = slot_offset + bit;
      VisitSpillSlot(isolate, v, spill_slot);
    }
    slot_offset += kBitsPerByte;
  }
}
References v8::base::bits::CountTrailingZeros(), v8::internal::kBitsPerByte, and VisitSpillSlot().
Referenced by v8::internal::TypedFrame::Iterate(), and v8::internal::CommonFrame::IterateTurbofanJSOptimizedFrame().