v8::internal::torque::anonymous_namespace{torque-parser.cc} Namespace Reference
Namespaces
 anonymous_namespace{torque-parser.cc}
Classes
class AnnotationSet
struct TorqueGrammar
Functions
bool ProcessIfAnnotation (ParseResultIterator *child_results)
bool ProcessIfAnnotation (const AnnotationSet &annotations)
std::optional< ParseResult > AddGlobalDeclarations (ParseResultIterator *child_results)
void NamingConventionError (const std::string &type, const std::string &name, const std::string &convention, SourcePosition pos=CurrentSourcePosition::Get())
void NamingConventionError (const std::string &type, const Identifier *name, const std::string &convention)
void LintGenericParameters (const GenericParameters &parameters)
std::optional< ParseResult > ConcatList (ParseResultIterator *child_results)
void CheckNotDeferredStatement (Statement *statement)
TypeExpression * AddConstexpr (TypeExpression *type)
Expression * MakeCall (IdentifierExpression *callee, std::optional< Expression * > target, std::vector< Expression * > arguments, const std::vector< Statement * > &otherwise)
Expression * MakeCall (Identifier *callee, const std::vector< TypeExpression * > &generic_arguments, const std::vector< Expression * > &arguments, const std::vector< Statement * > &otherwise)
std::optional< ParseResult > MakeCall (ParseResultIterator *child_results)
std::optional< ParseResult > MakeMethodCall (ParseResultIterator *child_results)
std::optional< ParseResult > MakeNewExpression (ParseResultIterator *child_results)
std::optional< ParseResult > MakeBinaryOperator (ParseResultIterator *child_results)
std::optional< ParseResult > MakeIntrinsicCallExpression (ParseResultIterator *child_results)
std::optional< ParseResult > MakeUnaryOperator (ParseResultIterator *child_results)
std::optional< ParseResult > MakeSpreadExpression (ParseResultIterator *child_results)
std::optional< ParseResult > MakeImplicitParameterList (ParseResultIterator *child_results)
void AddParameter (ParameterList *parameter_list, const NameAndTypeExpression &param)
template<bool has_varargs, bool has_explicit_parameter_names>
std::optional< ParseResult > MakeParameterList (ParseResultIterator *child_results)
std::optional< ParseResult > MakeAssertStatement (ParseResultIterator *child_results)
std::optional< ParseResult > MakeDebugStatement (ParseResultIterator *child_results)
std::optional< ParseResult > DeprecatedMakeVoidType (ParseResultIterator *child_results)
std::optional< ParseResult > MakeExternalMacro (ParseResultIterator *child_results)
std::optional< ParseResult > MakeIntrinsicDeclaration (ParseResultIterator *child_results)
std::optional< ParseResult > MakeTorqueMacroDeclaration (ParseResultIterator *child_results)
std::optional< ParseResult > MakeConstDeclaration (ParseResultIterator *child_results)
std::optional< ParseResult > MakeExternConstDeclaration (ParseResultIterator *child_results)
std::optional< ParseResult > MakeTypeAliasDeclaration (ParseResultIterator *child_results)
std::optional< ParseResult > MakeAbstractTypeDeclaration (ParseResultIterator *child_results)
std::optional< ParseResult > MakeMethodDeclaration (ParseResultIterator *child_results)
std::optional< ParseResult > YieldInt32 (ParseResultIterator *child_results)
std::optional< ParseResult > YieldDouble (ParseResultIterator *child_results)
std::optional< ParseResult > YieldIntegerLiteral (ParseResultIterator *child_results)
std::optional< ParseResult > MakeStringAnnotationParameter (ParseResultIterator *child_results)
std::optional< ParseResult > MakeIntAnnotationParameter (ParseResultIterator *child_results)
int GetAnnotationValue (const AnnotationSet &annotations, const char *name, int default_value)
std::optional< ParseResult > MakeTorqueBuiltinDeclaration (ParseResultIterator *child_results)
InstanceTypeConstraints MakeInstanceTypeConstraints (const AnnotationSet &annotations)
std::optional< ParseResult > MakeClassBody (ParseResultIterator *child_results)
std::optional< ParseResult > MakeClassDeclaration (ParseResultIterator *child_results)
std::optional< ParseResult > MakeNamespaceDeclaration (ParseResultIterator *child_results)
std::optional< ParseResult > MakeSpecializationDeclaration (ParseResultIterator *child_results)
std::optional< ParseResult > MakeStructDeclaration (ParseResultIterator *child_results)
std::optional< ParseResult > MakeBitFieldStructDeclaration (ParseResultIterator *child_results)
std::optional< ParseResult > MakeCppIncludeDeclaration (ParseResultIterator *child_results)
std::optional< ParseResult > ProcessTorqueImportDeclaration (ParseResultIterator *child_results)
std::optional< ParseResult > MakeExternalBuiltin (ParseResultIterator *child_results)
std::optional< ParseResult > MakeExternalRuntime (ParseResultIterator *child_results)
std::optional< ParseResult > StringLiteralUnquoteAction (ParseResultIterator *child_results)
std::optional< ParseResult > MakeBasicTypeExpression (ParseResultIterator *child_results)
std::optional< ParseResult > MakeFunctionTypeExpression (ParseResultIterator *child_results)
std::optional< ParseResult > MakeReferenceTypeExpression (ParseResultIterator *child_results)
std::optional< ParseResult > MakeUnionTypeExpression (ParseResultIterator *child_results)
std::optional< ParseResult > MakeGenericParameter (ParseResultIterator *child_results)
std::optional< ParseResult > MakeExpressionStatement (ParseResultIterator *child_results)
std::optional< ParseResult > MakeIfStatement (ParseResultIterator *child_results)
std::optional< ParseResult > MakeEnumDeclaration (ParseResultIterator *child_results)
std::optional< ParseResult > MakeTypeswitchStatement (ParseResultIterator *child_results)
std::optional< ParseResult > MakeTypeswitchCase (ParseResultIterator *child_results)
std::optional< ParseResult > MakeWhileStatement (ParseResultIterator *child_results)
std::optional< ParseResult > MakeReturnStatement (ParseResultIterator *child_results)
std::optional< ParseResult > MakeTailCallStatement (ParseResultIterator *child_results)
std::optional< ParseResult > MakeVarDeclarationStatement (ParseResultIterator *child_results)
std::optional< ParseResult > MakeBreakStatement (ParseResultIterator *child_results)
std::optional< ParseResult > MakeContinueStatement (ParseResultIterator *child_results)
std::optional< ParseResult > MakeGotoStatement (ParseResultIterator *child_results)
std::optional< ParseResult > MakeBlockStatement (ParseResultIterator *child_results)
std::optional< ParseResult > MakeTryLabelExpression (ParseResultIterator *child_results)
std::optional< ParseResult > MakeForLoopStatement (ParseResultIterator *child_results)
std::optional< ParseResult > MakeLabelBlock (ParseResultIterator *child_results)
std::optional< ParseResult > MakeCatchBlock (ParseResultIterator *child_results)
std::optional< ParseResult > MakeExpressionWithSource (ParseResultIterator *child_results)
std::optional< ParseResult > MakeIdentifier (ParseResultIterator *child_results)
std::optional< ParseResult > MakeIdentifierFromMatchedInput (ParseResultIterator *child_results)
std::optional< ParseResult > MakeRightShiftIdentifier (ParseResultIterator *child_results)
std::optional< ParseResult > MakeNamespaceQualification (ParseResultIterator *child_results)
std::optional< ParseResult > MakeIdentifierExpression (ParseResultIterator *child_results)
std::optional< ParseResult > MakeFieldAccessExpression (ParseResultIterator *child_results)
std::optional< ParseResult > MakeReferenceFieldAccessExpression (ParseResultIterator *child_results)
std::optional< ParseResult > MakeElementAccessExpression (ParseResultIterator *child_results)
std::optional< ParseResult > MakeDereferenceExpression (ParseResultIterator *child_results)
std::optional< ParseResult > MakeStructExpression (ParseResultIterator *child_results)
std::optional< ParseResult > MakeAssignmentExpression (ParseResultIterator *child_results)
std::optional< ParseResult > MakeFloatingPointLiteralExpression (ParseResultIterator *child_results)
std::optional< ParseResult > MakeIntegerLiteralExpression (ParseResultIterator *child_results)
std::optional< ParseResult > MakeStringLiteralExpression (ParseResultIterator *child_results)
std::optional< ParseResult > MakeIncrementDecrementExpressionPostfix (ParseResultIterator *child_results)
std::optional< ParseResult > MakeIncrementDecrementExpressionPrefix (ParseResultIterator *child_results)
std::optional< ParseResult > MakeLogicalOrExpression (ParseResultIterator *child_results)
std::optional< ParseResult > MakeLogicalAndExpression (ParseResultIterator *child_results)
std::optional< ParseResult > MakeConditionalExpression (ParseResultIterator *child_results)
std::optional< ParseResult > MakeLabelAndTypes (ParseResultIterator *child_results)
std::optional< ParseResult > MakeNameAndType (ParseResultIterator *child_results)
std::optional< ParseResult > MakeEnumEntry (ParseResultIterator *child_results)
std::optional< ParseResult > MakeNameAndExpression (ParseResultIterator *child_results)
std::optional< ParseResult > MakeNameAndExpressionFromExpression (ParseResultIterator *child_results)
std::optional< ParseResult > MakeAnnotation (ParseResultIterator *child_results)
std::optional< ParseResult > MakeClassField (ParseResultIterator *child_results)
std::optional< ParseResult > MakeStructField (ParseResultIterator *child_results)
std::optional< ParseResult > MakeBitFieldDeclaration (ParseResultIterator *child_results)
std::optional< ParseResult > ExtractAssignmentOperator (ParseResultIterator *child_results)
Function Documentation
AddConstexpr()
TypeExpression* v8::internal::torque::anonymous_namespace{torque-parser.cc}::AddConstexpr (TypeExpression * type)
Definition at line 363 of file torque-parser.cc.
                                                   {
  BasicTypeExpression* basic = BasicTypeExpression::DynamicCast(type);
  if (!basic) Error("Unsupported extends clause.").Throw();
  return MakeNode<BasicTypeExpression>(
      basic->namespace_qualification,
      MakeNode<Identifier>(CONSTEXPR_TYPE_PREFIX + basic->name->value),
      basic->generic_arguments);
}
References v8::internal::torque::CONSTEXPR_TYPE_PREFIX, v8::internal::torque::Error(), v8::internal::torque::BasicTypeExpression::generic_arguments, v8::internal::torque::BasicTypeExpression::name, v8::internal::torque::BasicTypeExpression::namespace_qualification, v8::internal::torque::MessageBuilder::Throw(), v8::internal::tracing::type, and v8::internal::torque::Identifier::value.
Referenced by MakeAbstractTypeDeclaration(), and MakeEnumDeclaration().
AddGlobalDeclarations()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::AddGlobalDeclarations (ParseResultIterator * child_results)
Definition at line 311 of file torque-parser.cc.
                                        {
  auto declarations = child_results->NextAs<std::vector<Declaration*>>();
  for (Declaration* declaration : declarations) {
    CurrentAst::Get().declarations().push_back(declaration);
  }
  return std::nullopt;
}
References v8::internal::compiler::turboshaft::Get(), and v8::internal::torque::ParseResultIterator::NextAs().
AddParameter()
void v8::internal::torque::anonymous_namespace{torque-parser.cc}::AddParameter (ParameterList * parameter_list, const NameAndTypeExpression & param)
Definition at line 502 of file torque-parser.cc.
                                                      {
  if (!IsLowerCamelCase(param.name->value)) {
    NamingConventionError("Parameter", param.name, "lowerCamelCase");
  }
  parameter_list->names.push_back(param.name);
  parameter_list->types.push_back(param.type);
}
References v8::internal::torque::IsLowerCamelCase(), v8::internal::torque::NameAndTypeExpression::name, v8::internal::torque::ParameterList::names, NamingConventionError(), v8::internal::torque::NameAndTypeExpression::type, v8::internal::torque::ParameterList::types, and v8::internal::torque::Identifier::value.
Referenced by MakeParameterList().
CheckNotDeferredStatement()
void v8::internal::torque::anonymous_namespace{torque-parser.cc}::CheckNotDeferredStatement (Statement * statement)
Definition at line 352 of file torque-parser.cc.
                                                     {
  CurrentSourcePosition::Scope source_position(statement->pos);
  if (BlockStatement* block = BlockStatement::DynamicCast(statement)) {
    if (block->deferred) {
      Lint(
          "cannot use deferred with a statement block here, it will have no "
          "effect");
    }
  }
}
References v8::internal::torque::Lint(), and v8::internal::torque::AstNode::pos.
Referenced by MakeBlockStatement(), MakeForLoopStatement(), MakeIfStatement(), MakeSpecializationDeclaration(), MakeTryLabelExpression(), and MakeWhileStatement().
ConcatList()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::ConcatList (ParseResultIterator * child_results)
Definition at line 342 of file torque-parser.cc.
                                                                        {
  auto list_of_lists =
      child_results->NextAs<std::vector<std::vector<Declaration*>>>();
  std::vector<Declaration*> result;
  for (auto& list : list_of_lists) {
    result.insert(result.end(), list.begin(), list.end());
  }
  return ParseResult{std::move(result)};
}
References v8::internal::torque::ParseResultIterator::NextAs(), and v8::base::internal::result.
DeprecatedMakeVoidType()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::DeprecatedMakeVoidType (ParseResultIterator * child_results)
Definition at line 588 of file torque-parser.cc.
                                        {
  Error("Default void return types are deprecated. Add `: void`.");
  TypeExpression* result = MakeNode<BasicTypeExpression>(
      std::vector<std::string>{}, MakeNode<Identifier>("void"),
      std::vector<TypeExpression*>{});
  return ParseResult{result};
}
References v8::internal::torque::Error(), and v8::base::internal::result.
ExtractAssignmentOperator()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::ExtractAssignmentOperator (ParseResultIterator * child_results)
Definition at line 2256 of file torque-parser.cc.
                                        {
  auto op = child_results->NextAs<Identifier*>();
  std::optional<std::string> result =
      std::string(op->value.begin(), op->value.end() - 1);
  return ParseResult(std::move(result));
}
References v8::internal::torque::ParseResultIterator::NextAs(), v8::base::internal::result, and v8::internal::string.
GetAnnotationValue()
int v8::internal::torque::anonymous_namespace{torque-parser.cc}::GetAnnotationValue (const AnnotationSet & annotations, const char * name, int default_value)
Definition at line 969 of file torque-parser.cc.
                                          {
  auto opt_value = annotations.GetIntParam(name);
  return opt_value.has_value() ? *opt_value : default_value;
}
References v8::internal::torque::anonymous_namespace{torque-parser.cc}::AnnotationSet::GetIntParam(), and v8::internal::name.
Referenced by MakeInstanceTypeConstraints().
LintGenericParameters()
void v8::internal::torque::anonymous_namespace{torque-parser.cc}::LintGenericParameters (const GenericParameters & parameters)
Definition at line 333 of file torque-parser.cc.
                                                                {
  for (auto parameter : parameters) {
    if (!IsUpperCamelCase(parameter.name->value)) {
      NamingConventionError("Generic parameter", parameter.name,
                            "UpperCamelCase");
    }
  }
}
References v8::internal::torque::IsUpperCamelCase(), and NamingConventionError().
Referenced by MakeExternalBuiltin(), MakeExternalMacro(), MakeIntrinsicDeclaration(), MakeStructDeclaration(), MakeTorqueBuiltinDeclaration(), and MakeTorqueMacroDeclaration().
MakeAbstractTypeDeclaration()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeAbstractTypeDeclaration (ParseResultIterator * child_results)
Definition at line 812 of file torque-parser.cc.
                                        {
  bool use_parent_type_checker = HasAnnotation(
      child_results, ANNOTATION_USE_PARENT_TYPE_CHECKER, "abstract type");
  auto transient = child_results->NextAs<bool>();
  auto name = child_results->NextAs<Identifier*>();
  if (!IsValidTypeName(name->value)) {
    NamingConventionError("Type", name, "UpperCamelCase");
  }
  auto generic_parameters = child_results->NextAs<GenericParameters>();
  auto extends = child_results->NextAs<std::optional<TypeExpression*>>();
  auto generates = child_results->NextAs<std::optional<std::string>>();
  AbstractTypeFlags flags(AbstractTypeFlag::kNone);
  if (transient) flags |= AbstractTypeFlag::kTransient;
  if (use_parent_type_checker) flags |= AbstractTypeFlag::kUseParentTypeChecker;
  TypeDeclaration* type_decl = MakeNode<AbstractTypeDeclaration>(
      name, flags, extends, std::move(generates));
  Declaration* decl = type_decl;
  if (!generic_parameters.empty()) {
    decl = MakeNode<GenericTypeDeclaration>(generic_parameters, type_decl);
  }
  auto constexpr_generates =
      child_results->NextAs<std::optional<std::string>>();
  std::vector<Declaration*> result{decl};
  if (constexpr_generates) {
    // Create a AbstractTypeDeclaration for the associated constexpr type.
    Identifier* constexpr_name =
        MakeNode<Identifier>(CONSTEXPR_TYPE_PREFIX + name->value);
    constexpr_name->pos = name->pos;
    std::optional<TypeExpression*> constexpr_extends;
    if (extends) {
      constexpr_extends = AddConstexpr(*extends);
    }
    TypeDeclaration* constexpr_decl = MakeNode<AbstractTypeDeclaration>(
        constexpr_name, flags | AbstractTypeFlag::kConstexpr, constexpr_extends,
        constexpr_generates);
    constexpr_decl->pos = name->pos;
    decl = constexpr_decl;
    if (!generic_parameters.empty()) {
      decl = MakeNode<GenericTypeDeclaration>(std::move(generic_parameters),
                                              constexpr_decl);
    }
    result.push_back(decl);
  }
  return ParseResult{std::move(result)};
}
References AddConstexpr(), v8::internal::torque::ANNOTATION_USE_PARENT_TYPE_CHECKER, v8::internal::torque::CONSTEXPR_TYPE_PREFIX, v8::internal::flags, v8::internal::torque::anonymous_namespace{torque-parser.cc}::anonymous_namespace{torque-parser.cc}::HasAnnotation(), v8::internal::torque::IsValidTypeName(), v8::internal::torque::kConstexpr, v8::internal::torque::kNone, v8::internal::torque::kTransient, v8::internal::torque::kUseParentTypeChecker, v8::internal::name, NamingConventionError(), v8::internal::torque::ParseResultIterator::NextAs(), v8::internal::torque::AstNode::pos, and v8::base::internal::result.
MakeAnnotation()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeAnnotation (ParseResultIterator * child_results)
Definition at line 2149 of file torque-parser.cc.
                                                                            {
  return ParseResult{
      Annotation{child_results->NextAs<Identifier*>(),
                 child_results->NextAs<std::optional<AnnotationParameter>>()}};
}
References v8::internal::torque::ParseResultIterator::NextAs().
MakeAssertStatement()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeAssertStatement (ParseResultIterator * child_results)
Definition at line 553 of file torque-parser.cc.
                                        {
  auto kind_string = child_results->NextAs<Identifier*>()->value;
  auto expr_with_source = child_results->NextAs<ExpressionWithSource>();
  AssertStatement::AssertKind kind;
  if (kind_string == "dcheck") {
    kind = AssertStatement::AssertKind::kDcheck;
  } else if (kind_string == "check") {
    kind = AssertStatement::AssertKind::kCheck;
  } else if (kind_string == "sbxcheck") {
#ifdef V8_ENABLE_SANDBOX
    kind = AssertStatement::AssertKind::kSbxCheck;
#else
    kind = AssertStatement::AssertKind::kDcheck;
#endif // V8_ENABLE_SANDBOX
  } else if (kind_string == "static_assert") {
    kind = AssertStatement::AssertKind::kStaticAssert;
  } else {
    UNREACHABLE();
  }
  Statement* result = MakeNode<AssertStatement>(
      kind, expr_with_source.expression, expr_with_source.source);
  return ParseResult{result};
}
References v8::internal::torque::AssertStatement::kCheck, v8::internal::torque::AssertStatement::kDcheck, v8::internal::torque::AssertStatement::kSbxCheck, v8::internal::torque::AssertStatement::kStaticAssert, v8::internal::torque::ParseResultIterator::NextAs(), v8::base::internal::result, v8::internal::UNREACHABLE(), and v8::internal::value.
MakeAssignmentExpression()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeAssignmentExpression (ParseResultIterator * child_results)
Definition at line 2027 of file torque-parser.cc.
                                        {
  auto location = child_results->NextAs<Expression*>();
  auto op = child_results->NextAs<std::optional<std::string>>();
  auto value = child_results->NextAs<Expression*>();
  Expression* result =
      MakeNode<AssignmentExpression>(location, std::move(op), value);
  return ParseResult{result};
}
References v8::internal::torque::ParseResultIterator::NextAs(), v8::base::internal::result, and v8::internal::value.
MakeBasicTypeExpression()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeBasicTypeExpression (ParseResultIterator * child_results)
Definition at line 1359 of file torque-parser.cc.
                                        {
  auto namespace_qualification =
      child_results->NextAs<std::vector<std::string>>();
  auto is_constexpr = child_results->NextAs<bool>();
  auto name = child_results->NextAs<std::string>();
  auto generic_arguments =
      child_results->NextAs<std::vector<TypeExpression*>>();
  TypeExpression* result = MakeNode<BasicTypeExpression>(
      std::move(namespace_qualification),
      MakeNode<Identifier>(is_constexpr ? GetConstexprName(name)
                                        : std::move(name)),
      std::move(generic_arguments));
  return ParseResult{result};
}
References v8::internal::torque::GetConstexprName(), name, v8::internal::torque::ParseResultIterator::NextAs(), v8::base::internal::result, and v8::internal::string.
MakeBinaryOperator()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeBinaryOperator (ParseResultIterator * child_results)
Definition at line 459 of file torque-parser.cc.
                                        {
  auto left = child_results->NextAs<Expression*>();
  auto op = child_results->NextAs<Identifier*>();
  auto right = child_results->NextAs<Expression*>();
  return ParseResult{MakeCall(op, TypeList{},
                              std::vector<Expression*>{left, right},
                              std::vector<Statement*>{})};
}
References MakeCall(), and v8::internal::torque::ParseResultIterator::NextAs().
Referenced by v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::BinaryOperator().
MakeBitFieldDeclaration()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeBitFieldDeclaration (ParseResultIterator * child_results)
Definition at line 2248 of file torque-parser.cc.
                                        {
  auto name = child_results->NextAs<Identifier*>();
  auto type = child_results->NextAs<TypeExpression*>();
  auto num_bits = child_results->NextAs<int32_t>();
  return ParseResult{BitFieldDeclaration{{name, type}, num_bits}};
}
References name, v8::internal::torque::ParseResultIterator::NextAs(), and v8::internal::tracing::type.
MakeBitFieldStructDeclaration()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeBitFieldStructDeclaration (ParseResultIterator * child_results)
Definition at line 1284 of file torque-parser.cc.
                                        {
  auto name = child_results->NextAs<Identifier*>();
  if (!IsValidTypeName(name->value)) {
    NamingConventionError("Bitfield struct", name, "UpperCamelCase");
  }
  auto extends = child_results->NextAs<TypeExpression*>();
  auto fields = child_results->NextAs<std::vector<BitFieldDeclaration>>();
  Declaration* decl =
      MakeNode<BitFieldStructDeclaration>(name, extends, std::move(fields));
  return ParseResult{decl};
}
References v8::internal::torque::IsValidTypeName(), name, NamingConventionError(), and v8::internal::torque::ParseResultIterator::NextAs().
MakeBlockStatement()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeBlockStatement (ParseResultIterator * child_results)
Definition at line 1837 of file torque-parser.cc.
                                        {
  auto deferred = child_results->NextAs<bool>();
  auto statements = child_results->NextAs<std::vector<Statement*>>();
  for (Statement* statement : statements) {
    CheckNotDeferredStatement(statement);
  }
  Statement* result = MakeNode<BlockStatement>(deferred, std::move(statements));
  return ParseResult{result};
}
References CheckNotDeferredStatement(), v8::internal::torque::ParseResultIterator::NextAs(), and v8::base::internal::result.
MakeBreakStatement()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeBreakStatement (ParseResultIterator * child_results)
Definition at line 1817 of file torque-parser.cc.
                                        {
  Statement* result = MakeNode<BreakStatement>();
  return ParseResult{result};
}
References v8::base::internal::result.
MakeCall() [1/3]
Expression* v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeCall (Identifier * callee, const std::vector< TypeExpression * > & generic_arguments, const std::vector< Expression * > & arguments, const std::vector< Statement * > & otherwise)
Definition at line 420 of file torque-parser.cc.
                                                             {
  return MakeCall(MakeNode<IdentifierExpression>(callee, generic_arguments),
                  std::nullopt, arguments, otherwise);
}
References MakeCall().
MakeCall() [2/3]
Expression* v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeCall (IdentifierExpression * callee, std::optional< Expression * > target, std::vector< Expression * > arguments, const std::vector< Statement * > & otherwise)
Definition at line 372 of file torque-parser.cc.
                                                             {
  std::vector<Identifier*> labels;
  // All IdentifierExpressions are treated as label names and can be directly
  // used as labels identifiers. All other statements in a call's otherwise
  // must create intermediate Labels for the otherwise's statement code.
  size_t label_id_count = 0;
  std::vector<TryHandler*> temp_labels;
  for (auto* statement : otherwise) {
    if (auto* e = ExpressionStatement::DynamicCast(statement)) {
      if (auto* id = IdentifierExpression::DynamicCast(e->expression)) {
        if (!id->generic_arguments.empty()) {
          ReportError("An otherwise label cannot have generic parameters");
        }
        labels.push_back(id->name);
        continue;
      }
    }
    auto label_name = std::string("__label") + std::to_string(label_id_count++);
    auto label_id = MakeNode<Identifier>(label_name);
    label_id->pos = SourcePosition::Invalid();
    labels.push_back(label_id);
    auto* handler =
        MakeNode<TryHandler>(TryHandler::HandlerKind::kLabel, label_id,
                             ParameterList::Empty(), statement);
    temp_labels.push_back(handler);
  }
  // Create nested try-label expression for all of the temporary Labels that
  // were created.
  Expression* result = nullptr;
  if (target) {
    result = MakeNode<CallMethodExpression>(
        *target, callee, std::move(arguments), std::move(labels));
  } else {
    result = MakeNode<CallExpression>(callee, std::move(arguments),
                                      std::move(labels));
  }
  for (auto* label : temp_labels) {
    result = MakeNode<TryLabelExpression>(result, label);
  }
  return result;
}
References v8::internal::torque::ParameterList::Empty(), v8::internal::torque::SourcePosition::Invalid(), v8::internal::torque::TryHandler::kLabel, v8::internal::torque::ReportError(), v8::base::internal::result, and v8::internal::string.
MakeCall() [3/3]
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeCall (ParseResultIterator * child_results)
Definition at line 428 of file torque-parser.cc.
                                                                      {
  auto callee = child_results->NextAs<Expression*>();
  auto args = child_results->NextAs<std::vector<Expression*>>();
  auto otherwise = child_results->NextAs<std::vector<Statement*>>();
  IdentifierExpression* target = IdentifierExpression::cast(callee);
  return ParseResult{
      MakeCall(target, std::nullopt, std::move(args), otherwise)};
}
References v8::base::args, and v8::internal::torque::ParseResultIterator::NextAs().
Referenced by MakeBinaryOperator(), MakeCall(), MakeClassField(), MakeEnumDeclaration(), MakeMethodCall(), MakeTypeswitchStatement(), and MakeUnaryOperator().
MakeCatchBlock()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeCatchBlock (ParseResultIterator * child_results)
Definition at line 1898 of file torque-parser.cc.
                                                                            {
  auto parameter_names = child_results->NextAs<std::vector<std::string>>();
  auto body = child_results->NextAs<Statement*>();
  for (const std::string& variable : parameter_names) {
    if (!IsLowerCamelCase(variable)) {
      NamingConventionError("Exception", variable, "lowerCamelCase");
    }
  }
  if (parameter_names.size() != 2) {
    ReportError(
        "A catch clause needs to have exactly two parameters: The exception "
        "and the message. How about: \"catch (exception, message) { ...\".");
  }
  ParameterList parameters;
  parameters.names.push_back(MakeNode<Identifier>(parameter_names[0]));
  parameters.types.push_back(MakeNode<BasicTypeExpression>(
      std::vector<std::string>{}, MakeNode<Identifier>("JSAny"),
      std::vector<TypeExpression*>{}));
  parameters.names.push_back(MakeNode<Identifier>(parameter_names[1]));
  parameters.types.push_back(MakeNode<UnionTypeExpression>(
      MakeNode<BasicTypeExpression>(std::vector<std::string>{},
                                    MakeNode<Identifier>("JSMessageObject"),
                                    std::vector<TypeExpression*>{}),
      MakeNode<BasicTypeExpression>(std::vector<std::string>{},
                                    MakeNode<Identifier>("TheHole"),
                                    std::vector<TypeExpression*>{})));
  parameters.has_varargs = false;
  TryHandler* result = MakeNode<TryHandler>(
      TryHandler::HandlerKind::kCatch, MakeNode<Identifier>(kCatchLabelName),
      std::move(parameters), body);
  return ParseResult{result};
}
References v8::internal::torque::ParameterList::has_varargs, v8::internal::torque::IsLowerCamelCase(), v8::internal::anonymous_namespace{isolate.cc}::kCatch, v8::internal::torque::kCatchLabelName, v8::internal::torque::ParameterList::names, NamingConventionError(), v8::internal::torque::ParseResultIterator::NextAs(), v8::internal::torque::ReportError(), v8::base::internal::result, v8::internal::string, and v8::internal::torque::ParameterList::types.
MakeClassBody()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeClassBody (ParseResultIterator * child_results)
Definition at line 1031 of file torque-parser.cc.
                                                                           {
  auto methods = child_results->NextAs<std::vector<Declaration*>>();
  auto fields = child_results->NextAs<std::vector<ClassFieldExpression>>();
  std::optional<ClassBody*> result =
      MakeNode<ClassBody>(std::move(methods), std::move(fields));
  return ParseResult(result);
}
References v8::internal::torque::ParseResultIterator::NextAs(), and v8::base::internal::result.
MakeClassDeclaration()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeClassDeclaration (ParseResultIterator * child_results)
Definition at line 1039 of file torque-parser.cc.
                                        {
  AnnotationSet annotations(
      child_results,
      {ANNOTATION_ABSTRACT, ANNOTATION_HAS_SAME_INSTANCE_TYPE_AS_PARENT,
       ANNOTATION_DO_NOT_GENERATE_CPP_CLASS, ANNOTATION_CUSTOM_CPP_CLASS,
       ANNOTATION_CUSTOM_MAP, ANNOTATION_GENERATE_BODY_DESCRIPTOR,
       ANNOTATION_EXPORT, ANNOTATION_DO_NOT_GENERATE_CAST,
       ANNOTATION_GENERATE_UNIQUE_MAP, ANNOTATION_GENERATE_FACTORY_FUNCTION,
       ANNOTATION_HIGHEST_INSTANCE_TYPE_WITHIN_PARENT,
       ANNOTATION_LOWEST_INSTANCE_TYPE_WITHIN_PARENT,
       ANNOTATION_CPP_OBJECT_DEFINITION,
       ANNOTATION_CPP_OBJECT_LAYOUT_DEFINITION},
      {ANNOTATION_RESERVE_BITS_IN_INSTANCE_TYPE,
       ANNOTATION_INSTANCE_TYPE_VALUE});
  ClassFlags flags = ClassFlag::kNone;
  if (annotations.Contains(ANNOTATION_ABSTRACT)) {
    flags |= ClassFlag::kAbstract;
  }
  if (annotations.Contains(ANNOTATION_HAS_SAME_INSTANCE_TYPE_AS_PARENT)) {
    flags |= ClassFlag::kHasSameInstanceTypeAsParent;
  }
  bool do_not_generate_cpp_class =
      annotations.Contains(ANNOTATION_DO_NOT_GENERATE_CPP_CLASS);
  if (annotations.Contains(ANNOTATION_CUSTOM_CPP_CLASS)) {
    Error(
        "@customCppClass is deprecated. Use 'extern' instead. "
        "@generateBodyDescriptor, @generateUniqueMap, and "
        "@generateFactoryFunction accomplish most of what '@export "
        "@customCppClass' used to.");
  }
  if (annotations.Contains(ANNOTATION_CUSTOM_MAP)) {
    Error(
        "@customMap is deprecated. Generating a unique map is opt-in now using "
        "@generateUniqueMap.");
  }
  if (annotations.Contains(ANNOTATION_DO_NOT_GENERATE_CAST)) {
    flags |= ClassFlag::kDoNotGenerateCast;
  }
  if (annotations.Contains(ANNOTATION_GENERATE_BODY_DESCRIPTOR)) {
    flags |= ClassFlag::kGenerateBodyDescriptor;
  }
  if (annotations.Contains(ANNOTATION_GENERATE_UNIQUE_MAP)) {
    flags |= ClassFlag::kGenerateUniqueMap;
  }
  if (annotations.Contains(ANNOTATION_GENERATE_FACTORY_FUNCTION)) {
    flags |= ClassFlag::kGenerateFactoryFunction;
  }
  if (annotations.Contains(ANNOTATION_EXPORT)) {
    flags |= ClassFlag::kExport;
  }
  if (annotations.Contains(ANNOTATION_HIGHEST_INSTANCE_TYPE_WITHIN_PARENT)) {
    flags |= ClassFlag::kHighestInstanceTypeWithinParent;
  }
  if (annotations.Contains(ANNOTATION_LOWEST_INSTANCE_TYPE_WITHIN_PARENT)) {
    flags |= ClassFlag::kLowestInstanceTypeWithinParent;
  }
  if (annotations.Contains(ANNOTATION_CPP_OBJECT_DEFINITION)) {
    flags |= ClassFlag::kCppObjectDefinition;
  }
  if (annotations.Contains(ANNOTATION_CPP_OBJECT_LAYOUT_DEFINITION)) {
    flags |= ClassFlag::kCppObjectLayoutDefinition;
  }
  auto is_extern = child_results->NextAs<bool>();
  if (is_extern) flags |= ClassFlag::kExtern;
  auto transient = child_results->NextAs<bool>();
  if (transient) flags |= ClassFlag::kTransient;
  std::string kind = child_results->NextAs<Identifier*>()->value;
  if (kind == "shape") {
    flags |= ClassFlag::kIsShape;
    flags |= ClassFlag::kTransient;
    flags |= ClassFlag::kHasSameInstanceTypeAsParent;
    flags |= ClassFlag::kDoNotGenerateCast;
  } else {
    DCHECK_EQ(kind, "class");
  }
  auto name = child_results->NextAs<Identifier*>();
  if (!IsValidTypeName(name->value)) {
    NamingConventionError("Type", name, "UpperCamelCase");
  }
  auto extends = child_results->NextAs<TypeExpression*>();
  if (!BasicTypeExpression::DynamicCast(extends)) {
    ReportError("Expected type name in extends clause.");
  }
  auto generates = child_results->NextAs<std::optional<std::string>>();
  auto body = child_results->NextAs<std::optional<ClassBody*>>();
  std::vector<Declaration*> methods;
  std::vector<ClassFieldExpression> fields_raw;
  if (body.has_value()) {
    methods = (*body)->methods;
    fields_raw = (*body)->fields;
  } else {
    flags |= ClassFlag::kUndefinedLayout;
  }
  if (is_extern && body.has_value()) {
    if (!do_not_generate_cpp_class) {
      flags |= ClassFlag::kGenerateCppClassDefinitions;
    }
  } else if (do_not_generate_cpp_class) {
    Lint("Annotation @doNotGenerateCppClass has no effect");
  }
  // Filter to only include fields that should be present based on decoration.
  std::vector<ClassFieldExpression> fields;
  std::copy_if(
      fields_raw.begin(), fields_raw.end(), std::back_inserter(fields),
      [](const ClassFieldExpression& exp) {
        for (const ConditionalAnnotation& condition : exp.conditions) {
          if (condition.type == ConditionalAnnotationType::kPositive
                  ? !BuildFlags::GetFlag(condition.condition, ANNOTATION_IF)
                  : BuildFlags::GetFlag(condition.condition,
                                        ANNOTATION_IFNOT)) {
            return false;
          }
        }
        return true;
      });
  std::vector<Declaration*> result;
  result.push_back(MakeNode<ClassDeclaration>(
      name, flags, extends, generates, std::move(methods), std::move(fields),
      MakeInstanceTypeConstraints(annotations)));
  Identifier* constexpr_name =
      MakeNode<Identifier>(CONSTEXPR_TYPE_PREFIX + name->value);
  constexpr_name->pos = name->pos;
  TypeExpression* constexpr_extends = AddConstexpr(extends);
  AbstractTypeFlags abstract_type_flags(AbstractTypeFlag::kConstexpr);
  if (transient) abstract_type_flags |= AbstractTypeFlag::kTransient;
  TypeDeclaration* constexpr_decl = MakeNode<AbstractTypeDeclaration>(
      constexpr_name, abstract_type_flags, constexpr_extends,
      generates ? UnwrapTNodeTypeName(*generates) : name->value);
  constexpr_decl->pos = name->pos;
  result.push_back(constexpr_decl);
  if ((flags & ClassFlag::kDoNotGenerateCast) == 0 &&
      (flags & ClassFlag::kIsShape) == 0) {
    ParameterList parameters;
    parameters.names.push_back(MakeNode<Identifier>("obj"));
    parameters.types.push_back(MakeNode<BasicTypeExpression>(
        std::vector<std::string>{}, MakeNode<Identifier>("HeapObject"),
        std::vector<TypeExpression*>{}));
    LabelAndTypesVector labels;
    labels.push_back(LabelAndTypes{MakeNode<Identifier>("CastError"),
                                   std::vector<TypeExpression*>{}});
    TypeExpression* class_type = MakeNode<BasicTypeExpression>(
        std::vector<std::string>{}, name, std::vector<TypeExpression*>{});
    std::vector<std::string> namespace_qualification{
        TORQUE_INTERNAL_NAMESPACE_STRING};
    IdentifierExpression* internal_downcast_target =
        MakeNode<IdentifierExpression>(
            std::move(namespace_qualification),
            MakeNode<Identifier>("DownCastForTorqueClass"),
            std::vector<TypeExpression*>{class_type});
    IdentifierExpression* internal_downcast_otherwise =
        MakeNode<IdentifierExpression>(std::vector<std::string>{},
                                       MakeNode<Identifier>("CastError"));
    Expression* argument = MakeNode<IdentifierExpression>(
        std::vector<std::string>{}, MakeNode<Identifier>("obj"));
    auto value = MakeCall(internal_downcast_target, std::nullopt,
                          std::vector<Expression*>{argument},
                          std::vector<Statement*>{MakeNode<ExpressionStatement>(
                              internal_downcast_otherwise)});
    auto cast_body = MakeNode<ReturnStatement>(value);
    std::vector<TypeExpression*> generic_parameters;
    generic_parameters.push_back(MakeNode<BasicTypeExpression>(
        std::vector<std::string>{}, name, std::vector<TypeExpression*>{}));
    Declaration* specialization = MakeNode<SpecializationDeclaration>(
        false, MakeNode<Identifier>("Cast"), std::move(generic_parameters),
        std::move(parameters), class_type, std::move(labels), cast_body);
    result.push_back(specialization);
  }
  return ParseResult{std::move(result)};
}
References v8::internal::torque::ANNOTATION_ABSTRACT, v8::internal::torque::ANNOTATION_CPP_OBJECT_DEFINITION, v8::internal::torque::ANNOTATION_CPP_OBJECT_LAYOUT_DEFINITION, v8::internal::torque::ANNOTATION_CUSTOM_CPP_CLASS, v8::internal::torque::ANNOTATION_CUSTOM_MAP, v8::internal::torque::ANNOTATION_DO_NOT_GENERATE_CAST, v8::internal::torque::ANNOTATION_DO_NOT_GENERATE_CPP_CLASS, v8::internal::torque::ANNOTATION_EXPORT, v8::internal::torque::ANNOTATION_GENERATE_BODY_DESCRIPTOR, v8::internal::torque::ANNOTATION_GENERATE_FACTORY_FUNCTION, v8::internal::torque::ANNOTATION_GENERATE_UNIQUE_MAP, v8::internal::torque::ANNOTATION_HAS_SAME_INSTANCE_TYPE_AS_PARENT, v8::internal::torque::ANNOTATION_HIGHEST_INSTANCE_TYPE_WITHIN_PARENT, v8::internal::torque::ANNOTATION_INSTANCE_TYPE_VALUE, v8::internal::torque::ANNOTATION_LOWEST_INSTANCE_TYPE_WITHIN_PARENT, v8::internal::torque::ANNOTATION_RESERVE_BITS_IN_INSTANCE_TYPE, v8::internal::torque::anonymous_namespace{torque-parser.cc}::AnnotationSet::Contains(), DCHECK_EQ, v8::internal::torque::Error(), v8::base::ieee754::exp(), v8::internal::flags, v8::internal::torque::IsValidTypeName(), v8::internal::torque::kAbstract, v8::internal::torque::kCppObjectDefinition, v8::internal::torque::kCppObjectLayoutDefinition, v8::internal::torque::kDoNotGenerateCast, v8::internal::torque::kExport, v8::internal::torque::kExtern, v8::internal::torque::kGenerateBodyDescriptor, v8::internal::torque::kGenerateCppClassDefinitions, v8::internal::torque::kGenerateFactoryFunction, v8::internal::torque::kGenerateUniqueMap, v8::internal::torque::kHasSameInstanceTypeAsParent, v8::internal::torque::kHighestInstanceTypeWithinParent, v8::internal::torque::kIsShape, v8::internal::torque::kLowestInstanceTypeWithinParent, v8::internal::torque::kNone, v8::internal::torque::kTransient, v8::internal::torque::kUndefinedLayout, v8::internal::torque::Lint(), v8::internal::name, NamingConventionError(), v8::internal::torque::ParseResultIterator::NextAs(), v8::internal::torque::ReportError(), v8::internal::string, and v8::internal::value.
MakeClassField()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeClassField (ParseResultIterator * child_results)
Definition at line 2155 of file torque-parser.cc.
                                                                            {
  AnnotationSet annotations(
      child_results,
      {ANNOTATION_CPP_RELAXED_STORE, ANNOTATION_CPP_RELAXED_LOAD,
       ANNOTATION_CPP_RELEASE_STORE, ANNOTATION_CPP_ACQUIRE_LOAD,
       ANNOTATION_CUSTOM_WEAK_MARKING},
      {ANNOTATION_IF, ANNOTATION_IFNOT});
  FieldSynchronization synchronization = FieldSynchronization::kNone;
  if (annotations.Contains(ANNOTATION_CPP_RELEASE_STORE)) {
    synchronization = FieldSynchronization::kAcquireRelease;
  } else if (annotations.Contains(ANNOTATION_CPP_RELAXED_STORE)) {
    synchronization = FieldSynchronization::kRelaxed;
  }
  {
    FieldSynchronization read_synchronization = FieldSynchronization::kNone;
    if (annotations.Contains(ANNOTATION_CPP_ACQUIRE_LOAD)) {
      read_synchronization = FieldSynchronization::kAcquireRelease;
    } else if (annotations.Contains(ANNOTATION_CPP_RELAXED_LOAD)) {
      read_synchronization = FieldSynchronization::kRelaxed;
    }
    if (read_synchronization != synchronization) {
      Error("Incompatible read/write synchronization annotations for a field.");
    }
  }
  std::vector<ConditionalAnnotation> conditions;
  std::optional<std::string> if_condition =
      annotations.GetStringParam(ANNOTATION_IF);
  std::optional<std::string> ifnot_condition =
      annotations.GetStringParam(ANNOTATION_IFNOT);
  if (if_condition.has_value()) {
    conditions.push_back({*if_condition, ConditionalAnnotationType::kPositive});
  }
  if (ifnot_condition.has_value()) {
    conditions.push_back(
        {*ifnot_condition, ConditionalAnnotationType::kNegative});
  }
  bool custom_weak_marking =
      annotations.Contains(ANNOTATION_CUSTOM_WEAK_MARKING);
  auto deprecated_weak = child_results->NextAs<bool>();
  if (deprecated_weak) {
    Error(
        "The keyword 'weak' is deprecated. For a field that can contain a "
        "normal weak pointer, use type Weak<T>. For a field that should be "
        "marked in some custom way, use @customWeakMarking.");
    custom_weak_marking = true;
  }
  auto const_qualified = child_results->NextAs<bool>();
  auto name = child_results->NextAs<Identifier*>();
  auto optional = child_results->NextAs<bool>();
  auto index = child_results->NextAs<std::optional<Expression*>>();
  if (optional && !index) {
    Error(
        "Fields using optional specifier must also provide an expression "
        "indicating the condition for whether the field is present");
  }
  std::optional<ClassFieldIndexInfo> index_info;
  if (index) {
    if (optional) {
      // Internally, an optional field is just an indexed field where the count
      // is zero or one.
      index = MakeNode<ConditionalExpression>(
          *index,
          MakeCall(
              MakeNode<Identifier>("FromConstexpr"),
              {MakeNode<BasicTypeExpression>(std::vector<std::string>{},
                                             MakeNode<Identifier>("intptr"),
                                             std::vector<TypeExpression*>{})},
              {MakeNode<IntegerLiteralExpression>(IntegerLiteral(1))}, {}),
          MakeCall(
              MakeNode<Identifier>("FromConstexpr"),
              {MakeNode<BasicTypeExpression>(std::vector<std::string>{},
                                             MakeNode<Identifier>("intptr"),
                                             std::vector<TypeExpression*>{})},
              {MakeNode<IntegerLiteralExpression>(IntegerLiteral(0))}, {}));
    }
    index_info = ClassFieldIndexInfo{*index, optional};
  }
  auto type = child_results->NextAs<TypeExpression*>();
  return ParseResult{ClassFieldExpression{{name, type},
                                          index_info,
                                          std::move(conditions),
                                          custom_weak_marking,
                                          const_qualified,
                                          synchronization}};
}
References v8::internal::torque::ANNOTATION_CPP_ACQUIRE_LOAD, v8::internal::torque::ANNOTATION_CPP_RELAXED_LOAD, v8::internal::torque::ANNOTATION_CPP_RELAXED_STORE, v8::internal::torque::ANNOTATION_CPP_RELEASE_STORE, v8::internal::torque::ANNOTATION_CUSTOM_WEAK_MARKING, v8::internal::torque::ANNOTATION_IF, v8::internal::torque::ANNOTATION_IFNOT, v8::internal::torque::anonymous_namespace{torque-parser.cc}::AnnotationSet::Contains(), v8::internal::torque::Error(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::AnnotationSet::GetStringParam(), v8::internal::index, v8::internal::compiler::kNegative, MakeCall(), name, v8::internal::torque::ParseResultIterator::NextAs(), and v8::internal::tracing::type.
MakeConditionalExpression()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeConditionalExpression (ParseResultIterator * child_results)
Definition at line 2092 of file torque-parser.cc.
                                        {
  auto condition = child_results->NextAs<Expression*>();
  auto if_true = child_results->NextAs<Expression*>();
  auto if_false = child_results->NextAs<Expression*>();
  Expression* result =
      MakeNode<ConditionalExpression>(condition, if_true, if_false);
  return ParseResult{result};
}
References v8::internal::torque::ParseResultIterator::NextAs(), and v8::base::internal::result.
MakeConstDeclaration()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeConstDeclaration (ParseResultIterator * child_results)
Definition at line 777 of file torque-parser.cc.
                                        {
  bool enabled = ProcessIfAnnotation(child_results);
  auto name = child_results->NextAs<Identifier*>();
  if (!IsValidNamespaceConstName(name->value)) {
    NamingConventionError("Constant", name, "kUpperCamelCase");
  }
  auto type = child_results->NextAs<TypeExpression*>();
  auto expression = child_results->NextAs<Expression*>();
  std::vector<Declaration*> result = {};
  if (enabled) result = {MakeNode<ConstDeclaration>(name, type, expression)};
  return ParseResult{std::move(result)};
}
References v8::internal::torque::IsValidNamespaceConstName(), v8::internal::name, NamingConventionError(), v8::internal::torque::ParseResultIterator::NextAs(), ProcessIfAnnotation(), v8::base::internal::result, and v8::internal::tracing::type.
MakeContinueStatement()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeContinueStatement (ParseResultIterator * child_results)
Definition at line 1823 of file torque-parser.cc.
                                        {
  Statement* result = MakeNode<ContinueStatement>();
  return ParseResult{result};
}
References v8::base::internal::result.
MakeCppIncludeDeclaration()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeCppIncludeDeclaration (ParseResultIterator * child_results)
Definition at line 1297 of file torque-parser.cc.
                                        {
  auto include_path = child_results->NextAs<std::string>();
  Declaration* result =
      MakeNode<CppIncludeDeclaration>(std::move(include_path));
  return ParseResult{result};
}
References v8::internal::torque::ParseResultIterator::NextAs(), v8::base::internal::result, and v8::internal::string.
MakeDebugStatement()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeDebugStatement (ParseResultIterator * child_results)
Definition at line 578 of file torque-parser.cc.
                                        {
  auto kind = child_results->NextAs<Identifier*>()->value;
  DCHECK(kind == "unreachable" || kind == "debug");
  Statement* result = MakeNode<DebugStatement>(
      kind == "unreachable" ? DebugStatement::Kind::kUnreachable
                            : DebugStatement::Kind::kDebug);
  return ParseResult{result};
}
References v8::internal::DCHECK(), v8::internal::torque::DebugStatement::kDebug, v8::internal::torque::DebugStatement::kUnreachable, v8::internal::torque::ParseResultIterator::NextAs(), v8::base::internal::result, and v8::internal::value.
MakeDereferenceExpression()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeDereferenceExpression (ParseResultIterator * child_results)
Definition at line 2011 of file torque-parser.cc.
                                        {
  auto reference = child_results->NextAs<Expression*>();
  Expression* result = MakeNode<DereferenceExpression>(reference);
  return ParseResult{result};
}
References v8::internal::torque::ParseResultIterator::NextAs(), and v8::base::internal::result.
MakeElementAccessExpression()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeElementAccessExpression (ParseResultIterator * child_results)
Definition at line 2003 of file torque-parser.cc.
                                        {
  auto object = child_results->NextAs<Expression*>();
  auto field = child_results->NextAs<Expression*>();
  Expression* result = MakeNode<ElementAccessExpression>(object, field);
  return ParseResult{result};
}
References v8::internal::torque::ParseResultIterator::NextAs(), and v8::base::internal::result.
MakeEnumDeclaration()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeEnumDeclaration (ParseResultIterator * child_results)
Definition at line 1443 of file torque-parser.cc.
                                        {
  const bool is_extern = child_results->NextAs<bool>();
  auto name_identifier = child_results->NextAs<Identifier*>();
  auto name = name_identifier->value;
  auto base_type_expression =
      child_results->NextAs<std::optional<TypeExpression*>>();
  auto constexpr_generates_opt =
      child_results->NextAs<std::optional<std::string>>();
  auto entries = child_results->NextAs<std::vector<EnumEntry>>();
  const bool is_open = child_results->NextAs<bool>();
  CurrentSourcePosition::Scope current_source_position(
      child_results->matched_input().pos);
  if (!is_extern) {
    ReportError("non-extern enums are not supported yet");
  }
  if (!IsValidTypeName(name)) {
    NamingConventionError("Type", name, "UpperCamelCase");
  }
  if (constexpr_generates_opt && *constexpr_generates_opt == name) {
    Lint("Unnecessary 'constexpr' clause for enum ", name);
  }
  auto constexpr_generates =
      constexpr_generates_opt ? *constexpr_generates_opt : name;
  const bool generate_nonconstexpr = base_type_expression.has_value();
  std::vector<Declaration*> result;
  // Build non-constexpr types.
  if (generate_nonconstexpr) {
    DCHECK(base_type_expression.has_value());
    if (is_open) {
      // For open enumerations, we define an abstract type and inherit all
      // entries' types from that:
      // type Enum extends Base;
      // namespace Enum {
      // type kEntry0 extends Enum;
      // ...
      // type kEntryN extends Enum;
      // }
      auto type_decl = MakeNode<AbstractTypeDeclaration>(
          name_identifier, AbstractTypeFlag::kNone, base_type_expression,
          std::nullopt);
      TypeExpression* name_type_expression =
          MakeNode<BasicTypeExpression>(name_identifier);
      name_type_expression->pos = name_identifier->pos;
      std::vector<Declaration*> entry_decls;
      entry_decls.reserve(entries.size());
      for (const auto& entry : entries) {
        entry_decls.push_back(MakeNode<AbstractTypeDeclaration>(
            entry.name, AbstractTypeFlag::kNone,
            entry.type.value_or(name_type_expression), std::nullopt));
      }
      result.push_back(type_decl);
      result.push_back(
          MakeNode<NamespaceDeclaration>(name, std::move(entry_decls)));
    } else {
      // For closed enumerations, we define abstract types for all entries and
      // define the enumeration as a union of those:
      // namespace Enum {
      // type kEntry0 extends Base;
      // ...
      // type kEntryN extends Base;
      // }
      // type Enum = Enum::kEntry0 | ... | Enum::kEntryN;
      TypeExpression* union_type = nullptr;
      std::vector<Declaration*> entry_decls;
      for (const auto& entry : entries) {
        entry_decls.push_back(MakeNode<AbstractTypeDeclaration>(
            entry.name, AbstractTypeFlag::kNone,
            entry.type.value_or(*base_type_expression), std::nullopt));
        auto entry_type = MakeNode<BasicTypeExpression>(
            std::vector<std::string>{name}, entry.name,
            std::vector<TypeExpression*>{});
        if (union_type) {
          union_type = MakeNode<UnionTypeExpression>(union_type, entry_type);
        } else {
          union_type = entry_type;
        }
      }
      result.push_back(
          MakeNode<NamespaceDeclaration>(name, std::move(entry_decls)));
      result.push_back(
          MakeNode<TypeAliasDeclaration>(name_identifier, union_type));
    }
  }
  // Build constexpr types.
  {
    // The constexpr entries inherit from an abstract enumeration type:
    // type constexpr Enum extends constexpr Base;
    // namespace Enum {
    // type constexpr kEntry0 extends constexpr Enum;
    // ...
    // type constexpr kEntry1 extends constexpr Enum;
    // }
    Identifier* constexpr_type_identifier =
        MakeNode<Identifier>(std::string(CONSTEXPR_TYPE_PREFIX) + name);
    TypeExpression* constexpr_type_expression = MakeNode<BasicTypeExpression>(
        MakeNode<Identifier>(std::string(CONSTEXPR_TYPE_PREFIX) + name));
    std::optional<TypeExpression*> base_constexpr_type_expression =
        std::nullopt;
    if (base_type_expression) {
      base_constexpr_type_expression = AddConstexpr(*base_type_expression);
    }
    result.push_back(MakeNode<AbstractTypeDeclaration>(
        constexpr_type_identifier, AbstractTypeFlag::kConstexpr,
        base_constexpr_type_expression, constexpr_generates));
    TypeExpression* type_expr = nullptr;
    Identifier* fromconstexpr_identifier = nullptr;
    Identifier* fromconstexpr_parameter_identifier = nullptr;
    Statement* fromconstexpr_body = nullptr;
    if (generate_nonconstexpr) {
      DCHECK(base_type_expression.has_value());
      type_expr = MakeNode<BasicTypeExpression>(std::vector<std::string>{},
                                                MakeNode<Identifier>(name),
                                                std::vector<TypeExpression*>{});
      // return %RawDownCast<Enum>(%FromConstexpr<Base>(o)))
      fromconstexpr_identifier = MakeNode<Identifier>("FromConstexpr");
      fromconstexpr_parameter_identifier = MakeNode<Identifier>("o");
      fromconstexpr_body =
          MakeNode<ReturnStatement>(MakeNode<IntrinsicCallExpression>(
              MakeNode<Identifier>("%RawDownCast"),
              std::vector<TypeExpression*>{type_expr},
              std::vector<Expression*>{MakeNode<IntrinsicCallExpression>(
                  MakeNode<Identifier>("%FromConstexpr"),
                  std::vector<TypeExpression*>{*base_type_expression},
                  std::vector<Expression*>{MakeNode<IdentifierExpression>(
                      std::vector<std::string>{},
                      fromconstexpr_parameter_identifier)})}));
    }
    EnumDescription enum_description{CurrentSourcePosition::Get(), name,
                                     constexpr_generates, is_open};
    std::vector<Declaration*> entry_decls;
    for (const auto& entry : entries) {
      const std::string entry_name = entry.name->value;
      const std::string entry_constexpr_type =
          CONSTEXPR_TYPE_PREFIX + entry_name;
      std::string alias_entry;
      if (entry.alias_entry) {
        alias_entry = constexpr_generates + "::" + *entry.alias_entry;
      }
      enum_description.entries.emplace_back(
          constexpr_generates + "::" + entry_name, alias_entry);
      entry_decls.push_back(MakeNode<AbstractTypeDeclaration>(
          MakeNode<Identifier>(entry_constexpr_type),
          AbstractTypeFlag::kConstexpr, constexpr_type_expression,
          constexpr_generates));
      bool generate_typed_constant = entry.type.has_value();
      if (generate_typed_constant) {
        // namespace Enum {
        // const constexpr_constant_kEntry0: constexpr kEntry0 constexpr
        // 'Enum::kEntry0'; const kEntry0 = %RawDownCast<T,
        // Base>(FromConstexpr<Enum>(constexpr_constant_kEntry0));
        // }
        if (!generate_nonconstexpr) {
          Error(
              "Enum constants with custom types require an enum with an "
              "extends clause.")
              .Position((*entry.type)->pos);
        }
        Identifier* constexpr_constant_name =
            MakeNode<Identifier>("constexpr constant " + entry_name);
        entry_decls.push_back(MakeNode<ExternConstDeclaration>(
            constexpr_constant_name,
            MakeNode<BasicTypeExpression>(
                std::vector<std::string>{},
                MakeNode<Identifier>(entry_constexpr_type),
                std::vector<TypeExpression*>{}),
            constexpr_generates + "::" + entry_name));
        entry_decls.push_back(MakeNode<ConstDeclaration>(
            entry.name, *entry.type,
            MakeNode<IntrinsicCallExpression>(
                MakeNode<Identifier>("%RawDownCast"),
                std::vector<TypeExpression*>{*entry.type,
                                             *base_type_expression},
                std::vector<Expression*>{MakeCall(
                    MakeNode<Identifier>("FromConstexpr"), {type_expr},
                    {MakeNode<IdentifierExpression>(std::vector<std::string>{},
                                                    constexpr_constant_name)},
                    {})})));
      } else {
        // namespace Enum {
        // const kEntry0: constexpr kEntry0 constexpr 'Enum::kEntry0';
        // }
        entry_decls.push_back(MakeNode<ExternConstDeclaration>(
            entry.name,
            MakeNode<BasicTypeExpression>(
                std::vector<std::string>{},
                MakeNode<Identifier>(entry_constexpr_type),
                std::vector<TypeExpression*>{}),
            constexpr_generates + "::" + entry_name));
      }
      // FromConstexpr<Enum, Enum::constexpr kEntry0>(
      // : Enum::constexpr kEntry0): Enum
      if (generate_nonconstexpr) {
        TypeExpression* entry_constexpr_type_expr =
            MakeNode<BasicTypeExpression>(
                std::vector<std::string>{name},
                MakeNode<Identifier>(entry_constexpr_type),
                std::vector<TypeExpression*>{});
        ParameterList parameters;
        parameters.names.push_back(fromconstexpr_parameter_identifier);
        parameters.types.push_back(entry_constexpr_type_expr);
        result.push_back(MakeNode<SpecializationDeclaration>(
            false, fromconstexpr_identifier,
            std::vector<TypeExpression*>{type_expr, entry_constexpr_type_expr},
            std::move(parameters), type_expr, LabelAndTypesVector{},
            fromconstexpr_body));
      }
    }
    result.push_back(
        MakeNode<NamespaceDeclaration>(name, std::move(entry_decls)));
    CurrentAst::Get().AddEnumDescription(std::move(enum_description));
  }
  return ParseResult{std::move(result)};
}
References AddConstexpr(), v8::internal::torque::CONSTEXPR_TYPE_PREFIX, DCHECK, v8::internal::torque::Error(), v8::internal::compiler::turboshaft::Get(), v8::internal::torque::IsValidTypeName(), v8::internal::torque::Lint(), MakeCall(), v8::internal::torque::ParseResultIterator::matched_input(), name, v8::internal::torque::ParameterList::names, NamingConventionError(), v8::internal::torque::ParseResultIterator::NextAs(), v8::internal::torque::AstNode::pos, v8::internal::torque::MatchedInput::pos, v8::internal::torque::MessageBuilder::Position(), v8::internal::torque::ReportError(), v8::base::internal::result, and v8::internal::string.
MakeEnumEntry()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeEnumEntry (ParseResultIterator * child_results)
Definition at line 2118 of file torque-parser.cc.
                                                                           {
  AnnotationSet annotations(child_results, {}, {ANNOTATION_SAME_ENUM_VALUE_AS});
  std::vector<ConditionalAnnotation> conditions;
  std::optional<std::string> alias_entry =
      annotations.GetStringParam(ANNOTATION_SAME_ENUM_VALUE_AS);
  auto name = child_results->NextAs<Identifier*>();
  auto type = child_results->NextAs<std::optional<TypeExpression*>>();
  return ParseResult{EnumEntry{name, type, alias_entry}};
}
References v8::internal::torque::ANNOTATION_SAME_ENUM_VALUE_AS, v8::internal::torque::anonymous_namespace{torque-parser.cc}::AnnotationSet::GetStringParam(), name, v8::internal::torque::ParseResultIterator::NextAs(), and v8::internal::tracing::type.
MakeExpressionStatement()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeExpressionStatement (ParseResultIterator * child_results)
Definition at line 1414 of file torque-parser.cc.
                                        {
  auto expression = child_results->NextAs<Expression*>();
  Statement* result = MakeNode<ExpressionStatement>(expression);
  return ParseResult{result};
}
References v8::internal::torque::ParseResultIterator::NextAs(), and v8::base::internal::result.
MakeExpressionWithSource()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeExpressionWithSource (ParseResultIterator * child_results)
Definition at line 1932 of file torque-parser.cc.
                                        {
  auto e = child_results->NextAs<Expression*>();
  return ParseResult{
      ExpressionWithSource{e, child_results->matched_input().ToString()}};
}
References v8::internal::torque::ParseResultIterator::matched_input(), v8::internal::torque::ParseResultIterator::NextAs(), and v8::internal::torque::MatchedInput::ToString().
MakeExternalBuiltin()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeExternalBuiltin (ParseResultIterator * child_results)
Definition at line 1324 of file torque-parser.cc.
                                        {
  auto transitioning = child_results->NextAs<bool>();
  auto js_linkage = child_results->NextAs<bool>();
  auto name = child_results->NextAs<Identifier*>();
  auto generic_parameters = child_results->NextAs<GenericParameters>();
  LintGenericParameters(generic_parameters);
  auto args = child_results->NextAs<ParameterList>();
  auto return_type = child_results->NextAs<TypeExpression*>();
  Declaration* result = MakeNode<ExternalBuiltinDeclaration>(
      transitioning, js_linkage, name, args, return_type);
  if (!generic_parameters.empty()) {
    Error("External builtins cannot be generic.");
  }
  return ParseResult{result};
}
References v8::base::args, v8::internal::torque::Error(), LintGenericParameters(), name, v8::internal::torque::ParseResultIterator::NextAs(), and v8::base::internal::result.
MakeExternalMacro()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeExternalMacro (ParseResultIterator * child_results)
Definition at line 597 of file torque-parser.cc.
                                        {
  bool enabled = ProcessIfAnnotation(child_results);
  auto transitioning = child_results->NextAs<bool>();
  auto operator_name = child_results->NextAs<std::optional<std::string>>();
  auto external_assembler_name =
      child_results->NextAs<std::optional<std::string>>();
  auto name = child_results->NextAs<Identifier*>();
  auto generic_parameters = child_results->NextAs<GenericParameters>();
  LintGenericParameters(generic_parameters);
  auto args = child_results->NextAs<ParameterList>();
  auto return_type = child_results->NextAs<TypeExpression*>();
  auto labels = child_results->NextAs<LabelAndTypesVector>();
  std::vector<Declaration*> result = {};
  if (enabled) {
    result = {MakeNode<ExternalMacroDeclaration>(
        transitioning,
        external_assembler_name ? *external_assembler_name
                                : "CodeStubAssembler",
        name, operator_name, args, return_type, std::move(labels))};
  }
  if (!generic_parameters.empty()) {
    Error("External builtins cannot be generic.");
  }
  return ParseResult{std::move(result)};
}
References v8::base::args, v8::internal::torque::Error(), LintGenericParameters(), v8::internal::name, v8::internal::torque::ParseResultIterator::NextAs(), ProcessIfAnnotation(), and v8::base::internal::result.
MakeExternalRuntime()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeExternalRuntime (ParseResultIterator * child_results)
Definition at line 1342 of file torque-parser.cc.
                                        {
  auto transitioning = child_results->NextAs<bool>();
  auto name = child_results->NextAs<Identifier*>();
  auto args = child_results->NextAs<ParameterList>();
  auto return_type = child_results->NextAs<TypeExpression*>();
  Declaration* result = MakeNode<ExternalRuntimeDeclaration>(
      transitioning, name, args, return_type);
  return ParseResult{result};
}
References v8::base::args, name, v8::internal::torque::ParseResultIterator::NextAs(), and v8::base::internal::result.
MakeExternConstDeclaration()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeExternConstDeclaration (ParseResultIterator * child_results)
Definition at line 792 of file torque-parser.cc.
                                        {
  auto name = child_results->NextAs<Identifier*>();
  auto type = child_results->NextAs<TypeExpression*>();
  auto literal = child_results->NextAs<std::string>();
  Declaration* result =
      MakeNode<ExternConstDeclaration>(name, type, std::move(literal));
  return ParseResult{result};
}
References v8::internal::name, v8::internal::torque::ParseResultIterator::NextAs(), v8::base::internal::result, v8::internal::string, and v8::internal::tracing::type.
MakeFieldAccessExpression()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeFieldAccessExpression (ParseResultIterator * child_results)
Definition at line 1985 of file torque-parser.cc.
                                        {
  auto object = child_results->NextAs<Expression*>();
  auto field = child_results->NextAs<Identifier*>();
  Expression* result = MakeNode<FieldAccessExpression>(object, field);
  return ParseResult{result};
}
References v8::internal::torque::ParseResultIterator::NextAs(), and v8::base::internal::result.
MakeFloatingPointLiteralExpression()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeFloatingPointLiteralExpression (ParseResultIterator * child_results)
Definition at line 2037 of file torque-parser.cc.
                                        {
  auto value = child_results->NextAs<double>();
  Expression* result = MakeNode<FloatingPointLiteralExpression>(value);
  return ParseResult{result};
}
References v8::internal::torque::ParseResultIterator::NextAs(), v8::base::internal::result, and v8::internal::value.
MakeForLoopStatement()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeForLoopStatement (ParseResultIterator * child_results)
Definition at line 1872 of file torque-parser.cc.
                                        {
  auto var_decl = child_results->NextAs<std::optional<Statement*>>();
  auto test = child_results->NextAs<std::optional<Expression*>>();
  auto action = child_results->NextAs<std::optional<Expression*>>();
  std::optional<Statement*> action_stmt;
  if (action) action_stmt = MakeNode<ExpressionStatement>(*action);
  auto body = child_results->NextAs<Statement*>();
  CheckNotDeferredStatement(body);
  Statement* result =
      MakeNode<ForLoopStatement>(var_decl, test, action_stmt, body);
  return ParseResult{result};
}
References CheckNotDeferredStatement(), v8::internal::torque::ParseResultIterator::NextAs(), and v8::base::internal::result.
MakeFunctionTypeExpression()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeFunctionTypeExpression (ParseResultIterator * child_results)
Definition at line 1375 of file torque-parser.cc.
                                        {
  auto parameters = child_results->NextAs<std::vector<TypeExpression*>>();
  auto return_type = child_results->NextAs<TypeExpression*>();
  TypeExpression* result =
      MakeNode<FunctionTypeExpression>(std::move(parameters), return_type);
  return ParseResult{result};
}
References v8::internal::torque::ParseResultIterator::NextAs(), and v8::base::internal::result.
MakeGenericParameter()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeGenericParameter (ParseResultIterator * child_results)
Definition at line 1407 of file torque-parser.cc.
                                        {
  auto name = child_results->NextAs<Identifier*>();
  auto constraint = child_results->NextAs<std::optional<TypeExpression*>>();
  return ParseResult{GenericParameter{name, constraint}};
}
References name, and v8::internal::torque::ParseResultIterator::NextAs().
MakeGotoStatement()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeGotoStatement (ParseResultIterator * child_results)
Definition at line 1829 of file torque-parser.cc.
                                        {
  auto label = child_results->NextAs<Identifier*>();
  auto arguments = child_results->NextAs<std::vector<Expression*>>();
  Statement* result = MakeNode<GotoStatement>(label, std::move(arguments));
  return ParseResult{result};
}
References v8::internal::torque::ParseResultIterator::NextAs(), and v8::base::internal::result.
MakeIdentifier()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeIdentifier (ParseResultIterator * child_results)
Definition at line 1939 of file torque-parser.cc.
                                                                            {
  auto name = child_results->NextAs<std::string>();
  Identifier* result = MakeNode<Identifier>(std::move(name));
  return ParseResult{result};
}
References name, v8::internal::torque::ParseResultIterator::NextAs(), v8::base::internal::result, and v8::internal::string.
MakeIdentifierExpression()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeIdentifierExpression (ParseResultIterator * child_results)
Definition at line 1973 of file torque-parser.cc.
                                        {
  auto namespace_qualification =
      child_results->NextAs<std::vector<std::string>>();
  auto name = child_results->NextAs<Identifier*>();
  auto generic_arguments =
      child_results->NextAs<std::vector<TypeExpression*>>();
  Expression* result = MakeNode<IdentifierExpression>(
      std::move(namespace_qualification), name, std::move(generic_arguments));
  return ParseResult{result};
}
References name, v8::internal::torque::ParseResultIterator::NextAs(), and v8::base::internal::result.
MakeIdentifierFromMatchedInput()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeIdentifierFromMatchedInput (ParseResultIterator * child_results)
Definition at line 1945 of file torque-parser.cc.
                                        {
  return ParseResult{
      MakeNode<Identifier>(child_results->matched_input().ToString())};
}
References v8::internal::torque::ParseResultIterator::matched_input(), and v8::internal::torque::MatchedInput::ToString().
Referenced by v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::OneOf().
MakeIfStatement()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeIfStatement (ParseResultIterator * child_results)
Definition at line 1421 of file torque-parser.cc.
                                                                             {
  auto is_constexpr = child_results->NextAs<bool>();
  auto condition = child_results->NextAs<Expression*>();
  auto if_true = child_results->NextAs<Statement*>();
  auto if_false = child_results->NextAs<std::optional<Statement*>>();
  if (if_false && !(BlockStatement::DynamicCast(if_true) &&
                    (BlockStatement::DynamicCast(*if_false) ||
                     IfStatement::DynamicCast(*if_false)))) {
    ReportError("if-else statements require curly braces");
  }
  if (is_constexpr) {
    CheckNotDeferredStatement(if_true);
    if (if_false) CheckNotDeferredStatement(*if_false);
  }
  Statement* result =
      MakeNode<IfStatement>(is_constexpr, condition, if_true, if_false);
  return ParseResult{result};
}
References CheckNotDeferredStatement(), v8::internal::torque::ParseResultIterator::NextAs(), v8::internal::torque::ReportError(), and v8::base::internal::result.
MakeImplicitParameterList()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeImplicitParameterList (ParseResultIterator * child_results)
Definition at line 495 of file torque-parser.cc.
                                        {
  auto kind = child_results->NextAs<Identifier*>();
  auto parameters = child_results->NextAs<std::vector<NameAndTypeExpression>>();
  return ParseResult{ImplicitParameters{kind, std::move(parameters)}};
}
References v8::internal::torque::ParseResultIterator::NextAs().
MakeIncrementDecrementExpressionPostfix()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeIncrementDecrementExpressionPostfix (ParseResultIterator * child_results)
Definition at line 2058 of file torque-parser.cc.
                                        {
  auto location = child_results->NextAs<Expression*>();
  auto op = child_results->NextAs<IncrementDecrementOperator>();
  Expression* result =
      MakeNode<IncrementDecrementExpression>(location, op, true);
  return ParseResult{result};
}
References v8::internal::torque::ParseResultIterator::NextAs(), and v8::base::internal::result.
MakeIncrementDecrementExpressionPrefix()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeIncrementDecrementExpressionPrefix (ParseResultIterator * child_results)
Definition at line 2067 of file torque-parser.cc.
                                        {
  auto op = child_results->NextAs<IncrementDecrementOperator>();
  auto location = child_results->NextAs<Expression*>();
  Expression* result =
      MakeNode<IncrementDecrementExpression>(location, op, false);
  return ParseResult{result};
}
References v8::internal::torque::ParseResultIterator::NextAs(), and v8::base::internal::result.
MakeInstanceTypeConstraints()
InstanceTypeConstraints v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeInstanceTypeConstraints (const AnnotationSet & annotations)
Definition at line 1021 of file torque-parser.cc.
                                      {
  InstanceTypeConstraints result;
  result.value =
      GetAnnotationValue(annotations, ANNOTATION_INSTANCE_TYPE_VALUE, -1);
  result.num_flags_bits = GetAnnotationValue(
      annotations, ANNOTATION_RESERVE_BITS_IN_INSTANCE_TYPE, -1);
  return result;
}
References v8::internal::torque::ANNOTATION_INSTANCE_TYPE_VALUE, v8::internal::torque::ANNOTATION_RESERVE_BITS_IN_INSTANCE_TYPE, GetAnnotationValue(), and v8::base::internal::result.
MakeIntAnnotationParameter()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeIntAnnotationParameter (ParseResultIterator * child_results)
Definition at line 962 of file torque-parser.cc.
                                        {
  int32_t value = child_results->NextAs<int32_t>();
  AnnotationParameter result{"", value, true};
  return ParseResult{result};
}
References v8::internal::torque::ParseResultIterator::NextAs(), v8::base::internal::result, and v8::internal::value.
MakeIntegerLiteralExpression()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeIntegerLiteralExpression (ParseResultIterator * child_results)
Definition at line 2044 of file torque-parser.cc.
                                        {
  auto value = child_results->NextAs<IntegerLiteral>();
  Expression* result = MakeNode<IntegerLiteralExpression>(std::move(value));
  return ParseResult{result};
}
References v8::internal::torque::ParseResultIterator::NextAs(), v8::base::internal::result, and v8::internal::value.
MakeIntrinsicCallExpression()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeIntrinsicCallExpression (ParseResultIterator * child_results)
Definition at line 469 of file torque-parser.cc.
                                        {
  auto callee = child_results->NextAs<Identifier*>();
  auto generic_arguments =
      child_results->NextAs<std::vector<TypeExpression*>>();
  auto args = child_results->NextAs<std::vector<Expression*>>();
  Expression* result = MakeNode<IntrinsicCallExpression>(
      callee, std::move(generic_arguments), std::move(args));
  return ParseResult{result};
}
References v8::base::args, v8::internal::torque::ParseResultIterator::NextAs(), and v8::base::internal::result.
MakeIntrinsicDeclaration()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeIntrinsicDeclaration (ParseResultIterator * child_results)
Definition at line 626 of file torque-parser.cc.
                                        {
  auto name = child_results->NextAs<Identifier*>();
  auto generic_parameters = child_results->NextAs<GenericParameters>();
  LintGenericParameters(generic_parameters);
  auto args = child_results->NextAs<ParameterList>();
  auto return_type = child_results->NextAs<TypeExpression*>();
  auto body = child_results->NextAs<std::optional<Statement*>>();
  CallableDeclaration* declaration;
  if (body) {
    declaration = MakeNode<TorqueMacroDeclaration>(
        false, name, std::optional<std::string>{}, args, return_type,
        LabelAndTypesVector{}, false, body);
  } else {
    declaration = MakeNode<IntrinsicDeclaration>(name, args, return_type);
  }
  Declaration* result = declaration;
  if (!generic_parameters.empty()) {
    result = MakeNode<GenericCallableDeclaration>(std::move(generic_parameters),
                                                  declaration);
  }
  return ParseResult{result};
}
References v8::base::args, LintGenericParameters(), v8::internal::name, v8::internal::torque::ParseResultIterator::NextAs(), and v8::base::internal::result.
MakeLabelAndTypes()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeLabelAndTypes (ParseResultIterator * child_results)
Definition at line 2102 of file torque-parser.cc.
                                        {
  auto name = child_results->NextAs<Identifier*>();
  if (!IsUpperCamelCase(name->value)) {
    NamingConventionError("Label", name, "UpperCamelCase");
  }
  auto types = child_results->NextAs<std::vector<TypeExpression*>>();
  return ParseResult{LabelAndTypes{name, std::move(types)}};
}
References v8::internal::torque::IsUpperCamelCase(), name, NamingConventionError(), and v8::internal::torque::ParseResultIterator::NextAs().
MakeLabelBlock()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeLabelBlock (ParseResultIterator * child_results)
Definition at line 1886 of file torque-parser.cc.
                                                                            {
  auto label = child_results->NextAs<Identifier*>();
  if (!IsUpperCamelCase(label->value)) {
    NamingConventionError("Label", label, "UpperCamelCase");
  }
  auto parameters = child_results->NextAs<ParameterList>();
  auto body = child_results->NextAs<Statement*>();
  TryHandler* result = MakeNode<TryHandler>(TryHandler::HandlerKind::kLabel,
                                            label, std::move(parameters), body);
  return ParseResult{result};
}
References v8::internal::torque::IsUpperCamelCase(), NamingConventionError(), v8::internal::torque::ParseResultIterator::NextAs(), and v8::base::internal::result.
MakeLogicalAndExpression()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeLogicalAndExpression (ParseResultIterator * child_results)
Definition at line 2084 of file torque-parser.cc.
                                        {
  auto left = child_results->NextAs<Expression*>();
  auto right = child_results->NextAs<Expression*>();
  Expression* result = MakeNode<LogicalAndExpression>(left, right);
  return ParseResult{result};
}
References v8::internal::torque::ParseResultIterator::NextAs(), and v8::base::internal::result.
MakeLogicalOrExpression()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeLogicalOrExpression (ParseResultIterator * child_results)
Definition at line 2076 of file torque-parser.cc.
                                        {
  auto left = child_results->NextAs<Expression*>();
  auto right = child_results->NextAs<Expression*>();
  Expression* result = MakeNode<LogicalOrExpression>(left, right);
  return ParseResult{result};
}
References v8::internal::torque::ParseResultIterator::NextAs(), and v8::base::internal::result.
MakeMethodCall()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeMethodCall (ParseResultIterator * child_results)
Definition at line 437 of file torque-parser.cc.
                                                                            {
  auto this_arg = child_results->NextAs<Expression*>();
  auto callee = child_results->NextAs<Identifier*>();
  auto args = child_results->NextAs<std::vector<Expression*>>();
  auto otherwise = child_results->NextAs<std::vector<Statement*>>();
  return ParseResult{MakeCall(MakeNode<IdentifierExpression>(callee), this_arg,
                              std::move(args), otherwise)};
}
References v8::base::args, MakeCall(), and v8::internal::torque::ParseResultIterator::NextAs().
MakeMethodDeclaration()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeMethodDeclaration (ParseResultIterator * child_results)
Definition at line 863 of file torque-parser.cc.
                                        {
  auto transitioning = child_results->NextAs<bool>();
  auto operator_name = child_results->NextAs<std::optional<std::string>>();
  auto name = child_results->NextAs<Identifier*>();
  if (!IsUpperCamelCase(name->value)) {
    NamingConventionError("Method", name, "UpperCamelCase");
  }
  auto args = child_results->NextAs<ParameterList>();
  auto return_type = child_results->NextAs<TypeExpression*>();
  auto labels = child_results->NextAs<LabelAndTypesVector>();
  auto body = child_results->NextAs<Statement*>();
  Declaration* result = MakeNode<TorqueMacroDeclaration>(
      transitioning, name, operator_name, args, return_type, std::move(labels),
      false, body);
  return ParseResult{result};
}
References v8::base::args, v8::internal::torque::IsUpperCamelCase(), v8::internal::name, NamingConventionError(), v8::internal::torque::ParseResultIterator::NextAs(), and v8::base::internal::result.
MakeNameAndExpression()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeNameAndExpression (ParseResultIterator * child_results)
Definition at line 2129 of file torque-parser.cc.
                                        {
  auto name = child_results->NextAs<Identifier*>();
  auto expression = child_results->NextAs<Expression*>();
  return ParseResult{NameAndExpression{name, expression}};
}
References name, and v8::internal::torque::ParseResultIterator::NextAs().
MakeNameAndExpressionFromExpression()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeNameAndExpressionFromExpression (ParseResultIterator * child_results)
Definition at line 2136 of file torque-parser.cc.
                                        {
  auto expression = child_results->NextAs<Expression*>();
  if (auto* id = IdentifierExpression::DynamicCast(expression)) {
    if (!id->generic_arguments.empty() ||
        !id->namespace_qualification.empty()) {
      ReportError("expected a plain identifier without qualification");
    }
    return ParseResult{NameAndExpression{id->name, id}};
  }
  ReportError("Constructor parameters need to be named.");
}
References v8::internal::torque::NameAndExpression::name, v8::internal::torque::ParseResultIterator::NextAs(), and v8::internal::torque::ReportError().
MakeNameAndType()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeNameAndType (ParseResultIterator * child_results)
Definition at line 2112 of file torque-parser.cc.
                                                                             {
  auto name = child_results->NextAs<Identifier*>();
  auto type = child_results->NextAs<TypeExpression*>();
  return ParseResult{NameAndTypeExpression{name, type}};
}
References name, v8::internal::torque::ParseResultIterator::NextAs(), and v8::internal::tracing::type.
MakeNamespaceDeclaration()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeNamespaceDeclaration (ParseResultIterator * child_results)
Definition at line 1226 of file torque-parser.cc.
                                        {
  auto name = child_results->NextAs<std::string>();
  if (!IsSnakeCase(name)) {
    NamingConventionError("Namespace", name, "snake_case");
  }
  auto declarations = child_results->NextAs<std::vector<Declaration*>>();
  Declaration* result =
      MakeNode<NamespaceDeclaration>(std::move(name), std::move(declarations));
  return ParseResult{result};
}
References v8::internal::torque::IsSnakeCase(), name, NamingConventionError(), v8::internal::torque::ParseResultIterator::NextAs(), v8::base::internal::result, and v8::internal::string.
MakeNamespaceQualification()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeNamespaceQualification (ParseResultIterator * child_results)
Definition at line 1962 of file torque-parser.cc.
                                        {
  bool global_namespace = child_results->NextAs<bool>();
  auto namespace_qualification =
      child_results->NextAs<std::vector<std::string>>();
  if (global_namespace) {
    namespace_qualification.insert(namespace_qualification.begin(), "");
  }
  return ParseResult(std::move(namespace_qualification));
}
References v8::internal::torque::ParseResultIterator::NextAs().
MakeNewExpression()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeNewExpression (ParseResultIterator * child_results)
Definition at line 446 of file torque-parser.cc.
                                        {
  bool pretenured = child_results->NextAs<bool>();
  bool clear_padding = child_results->NextAs<bool>();
  auto type = child_results->NextAs<TypeExpression*>();
  auto initializers = child_results->NextAs<std::vector<NameAndExpression>>();
  Expression* result = MakeNode<NewExpression>(type, std::move(initializers),
                                               pretenured, clear_padding);
  return ParseResult{result};
}
References v8::internal::torque::ParseResultIterator::NextAs(), v8::base::internal::result, and v8::internal::tracing::type.
MakeParameterList()
template<bool has_varargs, bool has_explicit_parameter_names>
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeParameterList (ParseResultIterator * child_results)
Definition at line 512 of file torque-parser.cc.
                                        {
  auto implicit_params =
      child_results->NextAs<std::optional<ImplicitParameters>>();
  ParameterList result;
  result.has_varargs = has_varargs;
  result.implicit_count = 0;
  result.implicit_kind = ImplicitKind::kNoImplicit;
  if (implicit_params) {
    result.implicit_count = implicit_params->parameters.size();
    if (implicit_params->kind->value == "implicit") {
      result.implicit_kind = ImplicitKind::kImplicit;
    } else {
      DCHECK_EQ(implicit_params->kind->value, "js-implicit");
      result.implicit_kind = ImplicitKind::kJSImplicit;
    }
    result.implicit_kind_pos = implicit_params->kind->pos;
    for (NameAndTypeExpression& implicit_param : implicit_params->parameters) {
      AddParameter(&result, implicit_param);
    }
  }
  if (has_explicit_parameter_names) {
    auto explicit_params =
        child_results->NextAs<std::vector<NameAndTypeExpression>>();
    std::string arguments_variable = "";
    if (has_varargs) {
      arguments_variable = child_results->NextAs<std::string>();
    }
    for (NameAndTypeExpression& param : explicit_params) {
      AddParameter(&result, param);
    }
    result.arguments_variable = arguments_variable;
  } else {
    auto explicit_types = child_results->NextAs<TypeList>();
    for (auto* explicit_type : explicit_types) {
      result.types.push_back(explicit_type);
    }
  }
  return ParseResult{std::move(result)};
}
References AddParameter(), DCHECK_EQ, v8::internal::torque::kImplicit, v8::internal::torque::kJSImplicit, v8::internal::torque::kNoImplicit, v8::internal::torque::ParseResultIterator::NextAs(), v8::base::internal::result, and v8::internal::string.
MakeReferenceFieldAccessExpression()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeReferenceFieldAccessExpression (ParseResultIterator * child_results)
Definition at line 1993 of file torque-parser.cc.
                                        {
  auto object = child_results->NextAs<Expression*>();
  auto field = child_results->NextAs<Identifier*>();
  // `a->b` is equivalent to `(*a).b`.
  Expression* deref = MakeNode<DereferenceExpression>(object);
  Expression* result = MakeNode<FieldAccessExpression>(deref, field);
  return ParseResult{result};
}
References v8::internal::torque::ParseResultIterator::NextAs(), and v8::base::internal::result.
MakeReferenceTypeExpression()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeReferenceTypeExpression (ParseResultIterator * child_results)
Definition at line 1384 of file torque-parser.cc.
                                        {
  auto is_const = child_results->NextAs<bool>();
  auto referenced_type = child_results->NextAs<TypeExpression*>();
  std::vector<std::string> namespace_qualification{
      TORQUE_INTERNAL_NAMESPACE_STRING};
  std::vector<TypeExpression*> generic_arguments{referenced_type};
  TypeExpression* result = MakeNode<BasicTypeExpression>(
      std::move(namespace_qualification),
      MakeNode<Identifier>(is_const ? CONST_REFERENCE_TYPE_STRING
                                    : MUTABLE_REFERENCE_TYPE_STRING),
      std::move(generic_arguments));
  return ParseResult{result};
}
References v8::internal::torque::CONST_REFERENCE_TYPE_STRING, v8::internal::torque::MUTABLE_REFERENCE_TYPE_STRING, v8::internal::torque::ParseResultIterator::NextAs(), v8::base::internal::result, and v8::internal::torque::TORQUE_INTERNAL_NAMESPACE_STRING.
MakeReturnStatement()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeReturnStatement (ParseResultIterator * child_results)
Definition at line 1781 of file torque-parser.cc.
                                        {
  auto value = child_results->NextAs<std::optional<Expression*>>();
  Statement* result = MakeNode<ReturnStatement>(value);
  return ParseResult{result};
}
References v8::internal::torque::ParseResultIterator::NextAs(), v8::base::internal::result, and v8::internal::value.
MakeRightShiftIdentifier()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeRightShiftIdentifier (ParseResultIterator * child_results)
Definition at line 1951 of file torque-parser.cc.
                                        {
  std::string str = child_results->matched_input().ToString();
  for (auto character : str) {
    if (character != '>') {
      ReportError("right-shift operators may not contain any whitespace");
    }
  }
  return ParseResult{MakeNode<Identifier>(str)};
}
References v8::internal::character, v8::internal::torque::ParseResultIterator::matched_input(), v8::internal::torque::ReportError(), v8::internal::string, and v8::internal::torque::MatchedInput::ToString().
MakeSpecializationDeclaration()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeSpecializationDeclaration (ParseResultIterator * child_results)
Definition at line 1238 of file torque-parser.cc.
                                        {
  bool enabled = ProcessIfAnnotation(child_results);
  auto transitioning = child_results->NextAs<bool>();
  auto name = child_results->NextAs<Identifier*>();
  auto generic_parameters =
      child_results->NextAs<std::vector<TypeExpression*>>();
  auto parameters = child_results->NextAs<ParameterList>();
  auto return_type = child_results->NextAs<TypeExpression*>();
  auto labels = child_results->NextAs<LabelAndTypesVector>();
  auto body = child_results->NextAs<Statement*>();
  CheckNotDeferredStatement(body);
  std::vector<Declaration*> result = {};
  if (enabled) {
    result = {MakeNode<SpecializationDeclaration>(
        transitioning, std::move(name), std::move(generic_parameters),
        std::move(parameters), return_type, std::move(labels), body)};
  }
  return ParseResult{std::move(result)};
}
References CheckNotDeferredStatement(), name, v8::internal::torque::ParseResultIterator::NextAs(), ProcessIfAnnotation(), and v8::base::internal::result.
MakeSpreadExpression()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeSpreadExpression (ParseResultIterator * child_results)
Definition at line 488 of file torque-parser.cc.
                                        {
  auto spreadee = child_results->NextAs<Expression*>();
  Expression* result = MakeNode<SpreadExpression>(spreadee);
  return ParseResult{result};
}
References v8::internal::torque::ParseResultIterator::NextAs(), and v8::base::internal::result.
MakeStringAnnotationParameter()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeStringAnnotationParameter (ParseResultIterator * child_results)
Definition at line 955 of file torque-parser.cc.
                                        {
  std::string value = child_results->NextAs<std::string>();
  AnnotationParameter result{value, 0, false};
  return ParseResult{result};
}
References v8::internal::torque::ParseResultIterator::NextAs(), v8::base::internal::result, v8::internal::string, and v8::internal::value.
MakeStringLiteralExpression()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeStringLiteralExpression (ParseResultIterator * child_results)
Definition at line 2051 of file torque-parser.cc.
                                        {
  auto literal = child_results->NextAs<std::string>();
  Expression* result = MakeNode<StringLiteralExpression>(std::move(literal));
  return ParseResult{result};
}
References v8::internal::torque::ParseResultIterator::NextAs(), v8::base::internal::result, and v8::internal::string.
MakeStructDeclaration()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeStructDeclaration (ParseResultIterator * child_results)
Definition at line 1259 of file torque-parser.cc.
                                        {
  bool is_export = HasExportAnnotation(child_results, "Struct");
  StructFlags flags = StructFlag::kNone;
  if (is_export) flags |= StructFlag::kExport;
  auto name = child_results->NextAs<Identifier*>();
  if (!IsValidTypeName(name->value)) {
    NamingConventionError("Struct", name, "UpperCamelCase");
  }
  auto generic_parameters = child_results->NextAs<GenericParameters>();
  LintGenericParameters(generic_parameters);
  auto methods = child_results->NextAs<std::vector<Declaration*>>();
  auto fields = child_results->NextAs<std::vector<StructFieldExpression>>();
  TypeDeclaration* struct_decl = MakeNode<StructDeclaration>(
      flags, name, std::move(methods), std::move(fields));
  Declaration* result = struct_decl;
  if (!generic_parameters.empty()) {
    result = MakeNode<GenericTypeDeclaration>(std::move(generic_parameters),
                                              struct_decl);
  }
  return ParseResult{result};
}
References flags(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::anonymous_namespace{torque-parser.cc}::HasExportAnnotation(), v8::internal::torque::IsValidTypeName(), LintGenericParameters(), name, NamingConventionError(), v8::internal::torque::ParseResultIterator::NextAs(), and v8::base::internal::result.
MakeStructExpression()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeStructExpression (ParseResultIterator * child_results)
Definition at line 2018 of file torque-parser.cc.
                                        {
  auto type = child_results->NextAs<TypeExpression*>();
  auto initializers = child_results->NextAs<std::vector<NameAndExpression>>();
  Expression* result =
      MakeNode<StructExpression>(type, std::move(initializers));
  return ParseResult{result};
}
References v8::internal::torque::ParseResultIterator::NextAs(), v8::base::internal::result, and v8::internal::tracing::type.
MakeStructField()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeStructField (ParseResultIterator * child_results)
Definition at line 2241 of file torque-parser.cc.
                                                                             {
  auto const_qualified = child_results->NextAs<bool>();
  auto name = child_results->NextAs<Identifier*>();
  auto type = child_results->NextAs<TypeExpression*>();
  return ParseResult{StructFieldExpression{{name, type}, const_qualified}};
}
References name, v8::internal::torque::ParseResultIterator::NextAs(), and v8::internal::tracing::type.
MakeTailCallStatement()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeTailCallStatement (ParseResultIterator * child_results)
Definition at line 1788 of file torque-parser.cc.
                                        {
  auto value = child_results->NextAs<Expression*>();
  Statement* result = MakeNode<TailCallStatement>(CallExpression::cast(value));
  return ParseResult{result};
}
References v8::internal::torque::ParseResultIterator::NextAs(), v8::base::internal::result, and v8::internal::value.
MakeTorqueBuiltinDeclaration()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeTorqueBuiltinDeclaration (ParseResultIterator * child_results)
Definition at line 975 of file torque-parser.cc.
                                        {
  AnnotationSet annotations(child_results,
                            {ANNOTATION_CUSTOM_INTERFACE_DESCRIPTOR},
                            {ANNOTATION_IF, ANNOTATION_INCREMENT_USE_COUNTER});
  const bool has_custom_interface_descriptor =
      annotations.Contains(ANNOTATION_CUSTOM_INTERFACE_DESCRIPTOR);
  std::optional<std::string> use_counter_name =
      annotations.GetStringParam(ANNOTATION_INCREMENT_USE_COUNTER);
  auto transitioning = child_results->NextAs<bool>();
  auto javascript_linkage = child_results->NextAs<bool>();
  auto name = child_results->NextAs<Identifier*>();
  if (!IsUpperCamelCase(name->value)) {
    NamingConventionError("Builtin", name, "UpperCamelCase");
  }
  auto generic_parameters = child_results->NextAs<GenericParameters>();
  LintGenericParameters(generic_parameters);
  auto args = child_results->NextAs<ParameterList>();
  auto return_type = child_results->NextAs<TypeExpression*>();
  auto body = child_results->NextAs<std::optional<Statement*>>();
  CallableDeclaration* declaration = MakeNode<TorqueBuiltinDeclaration>(
      transitioning, javascript_linkage, name, args, return_type,
      has_custom_interface_descriptor, use_counter_name, body);
  Declaration* result = declaration;
  if (generic_parameters.empty()) {
    if (!body) ReportError("A non-generic declaration needs a body.");
  } else {
    result = MakeNode<GenericCallableDeclaration>(std::move(generic_parameters),
                                                  declaration);
  }
  if (use_counter_name && !body) {
    ReportError("@incrementUseCounter needs a body.");
  }
  std::vector<Declaration*> results;
  if (std::optional<std::string> condition =
          annotations.GetStringParam(ANNOTATION_IF)) {
    if (!BuildFlags::GetFlag(*condition, ANNOTATION_IF)) {
      return ParseResult{std::move(results)};
    }
  }
  results.push_back(result);
  return ParseResult{std::move(results)};
}
References v8::internal::torque::ANNOTATION_CUSTOM_INTERFACE_DESCRIPTOR, v8::internal::torque::ANNOTATION_IF, v8::internal::torque::ANNOTATION_INCREMENT_USE_COUNTER, v8::base::args, v8::internal::torque::anonymous_namespace{torque-parser.cc}::AnnotationSet::Contains(), v8::internal::torque::BuildFlags::GetFlag(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::AnnotationSet::GetStringParam(), v8::internal::torque::IsUpperCamelCase(), LintGenericParameters(), v8::internal::name, NamingConventionError(), v8::internal::torque::ParseResultIterator::NextAs(), v8::internal::torque::ReportError(), and v8::base::internal::result.
MakeTorqueMacroDeclaration()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeTorqueMacroDeclaration (ParseResultIterator * child_results)
Definition at line 740 of file torque-parser.cc.
                                        {
  AnnotationSet annotations(child_results, {ANNOTATION_EXPORT},
                            {ANNOTATION_IF, ANNOTATION_IFNOT});
  bool enabled = ProcessIfAnnotation(annotations);
  bool export_to_csa = annotations.Contains(ANNOTATION_EXPORT);
  auto transitioning = child_results->NextAs<bool>();
  auto operator_name = child_results->NextAs<std::optional<std::string>>();
  auto name = child_results->NextAs<Identifier*>();
  if (!IsUpperCamelCase(name->value)) {
    NamingConventionError("Macro", name, "UpperCamelCase");
  }
  auto generic_parameters = child_results->NextAs<GenericParameters>();
  LintGenericParameters(generic_parameters);
  auto args = child_results->NextAs<ParameterList>();
  auto return_type = child_results->NextAs<TypeExpression*>();
  auto labels = child_results->NextAs<LabelAndTypesVector>();
  auto body = child_results->NextAs<std::optional<Statement*>>();
  std::vector<Declaration*> result = {};
  if (enabled) {
    CallableDeclaration* declaration = MakeNode<TorqueMacroDeclaration>(
        transitioning, name, operator_name, args, return_type,
        std::move(labels), export_to_csa, body);
    result = {declaration};
    if (generic_parameters.empty()) {
      if (!body) ReportError("A non-generic declaration needs a body.");
    } else {
      if (export_to_csa) ReportError("Cannot export generics to CSA.");
      result = {MakeNode<GenericCallableDeclaration>(
          std::move(generic_parameters), declaration)};
    }
  }
  return ParseResult{std::move(result)};
}
References v8::internal::torque::ANNOTATION_EXPORT, v8::internal::torque::ANNOTATION_IF, v8::internal::torque::ANNOTATION_IFNOT, v8::base::args, v8::internal::torque::anonymous_namespace{torque-parser.cc}::AnnotationSet::Contains(), v8::internal::torque::IsUpperCamelCase(), LintGenericParameters(), v8::internal::name, NamingConventionError(), v8::internal::torque::ParseResultIterator::NextAs(), ProcessIfAnnotation(), v8::internal::torque::ReportError(), and v8::base::internal::result.
MakeTryLabelExpression()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeTryLabelExpression (ParseResultIterator * child_results)
Definition at line 1848 of file torque-parser.cc.
                                        {
  auto try_block = child_results->NextAs<Statement*>();
  CheckNotDeferredStatement(try_block);
  Statement* result = try_block;
  auto handlers = child_results->NextAs<std::vector<TryHandler*>>();
  if (handlers.empty()) {
    Error("Try blocks without catch or label don't make sense.");
  }
  for (size_t i = 0; i < handlers.size(); ++i) {
    if (i != 0 &&
        handlers[i]->handler_kind == TryHandler::HandlerKind::kCatch) {
      Error(
          "A catch handler always has to be first, before any label handler, "
          "to avoid ambiguity about whether it catches exceptions from "
          "preceding handlers or not.")
          .Position(handlers[i]->pos);
    }
    result = MakeNode<ExpressionStatement>(MakeNode<TryLabelExpression>(
        MakeNode<StatementExpression>(result), handlers[i]));
  }
  return ParseResult{result};
}
References CheckNotDeferredStatement(), v8::internal::torque::Error(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::anonymous_namespace{isolate.cc}::kCatch, v8::internal::torque::ParseResultIterator::NextAs(), v8::internal::torque::MessageBuilder::Position(), and v8::base::internal::result.
MakeTypeAliasDeclaration()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeTypeAliasDeclaration (ParseResultIterator * child_results)
Definition at line 802 of file torque-parser.cc.
                                        {
  bool enabled = ProcessIfAnnotation(child_results);
  auto name = child_results->NextAs<Identifier*>();
  auto type = child_results->NextAs<TypeExpression*>();
  std::vector<Declaration*> result = {};
  if (enabled) result = {MakeNode<TypeAliasDeclaration>(name, type)};
  return ParseResult{std::move(result)};
}
References v8::internal::name, v8::internal::torque::ParseResultIterator::NextAs(), ProcessIfAnnotation(), v8::base::internal::result, and v8::internal::tracing::type.
MakeTypeswitchCase()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeTypeswitchCase (ParseResultIterator * child_results)
Definition at line 1763 of file torque-parser.cc.
                                        {
  auto name = child_results->NextAs<std::optional<Identifier*>>();
  auto type = child_results->NextAs<TypeExpression*>();
  auto block = child_results->NextAs<Statement*>();
  return ParseResult{
      TypeswitchCase{child_results->matched_input().pos, name, type, block}};
}
References v8::internal::torque::ParseResultIterator::matched_input(), name, v8::internal::torque::ParseResultIterator::NextAs(), v8::internal::torque::MatchedInput::pos, and v8::internal::tracing::type.
MakeTypeswitchStatement()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeTypeswitchStatement (ParseResultIterator * child_results)
Definition at line 1678 of file torque-parser.cc.
                                        {
  auto expression = child_results->NextAs<Expression*>();
  auto cases = child_results->NextAs<std::vector<TypeswitchCase>>();
  CurrentSourcePosition::Scope matched_input_current_source_position(
      child_results->matched_input().pos);
  // typeswitch (expression) case (x1 : T1) {
  // ...b1
  // } case (x2 : T2) {
  // ...b2
  // } case (x3 : T3) {
  // ...b3
  // }
  //
  // desugars to
  //
  // {
  // const _value = expression;
  // try {
  // const x1 : T1 = cast<T1>(_value) otherwise _NextCase;
  // ...b1
  // } label _NextCase {
  // try {
  // const x2 : T2 = cast<T2>(%assume_impossible<T1>(_value));
  // ...b2
  // } label _NextCase {
  // const x3 : T3 = %assume_impossible<T1|T2>(_value);
  // ...b3
  // }
  // }
  // }
  BlockStatement* current_block = MakeNode<BlockStatement>();
  Statement* result = current_block;
  {
    CurrentSourcePosition::Scope current_source_position(expression->pos);
    current_block->statements.push_back(MakeNode<VarDeclarationStatement>(
        true, MakeNode<Identifier>("__value"), std::nullopt, expression));
  }
  TypeExpression* accumulated_types;
  for (size_t i = 0; i < cases.size(); ++i) {
    CurrentSourcePosition::Scope current_source_position(cases[i].pos);
    Expression* value =
        MakeNode<IdentifierExpression>(MakeNode<Identifier>("__value"));
    if (i >= 1) {
      value =
          MakeNode<AssumeTypeImpossibleExpression>(accumulated_types, value);
    }
    BlockStatement* case_block;
    if (i < cases.size() - 1) {
      value = MakeCall(MakeNode<Identifier>("Cast"),
                       std::vector<TypeExpression*>{cases[i].type},
                       std::vector<Expression*>{value},
                       std::vector<Statement*>{MakeNode<ExpressionStatement>(
                           MakeNode<IdentifierExpression>(
                               MakeNode<Identifier>(kNextCaseLabelName)))});
      case_block = MakeNode<BlockStatement>();
    } else {
      case_block = current_block;
    }
    Identifier* name =
        cases[i].name ? *cases[i].name : MakeNode<Identifier>("__case_value");
    if (cases[i].name) name = *cases[i].name;
    case_block->statements.push_back(
        MakeNode<VarDeclarationStatement>(true, name, cases[i].type, value));
    case_block->statements.push_back(cases[i].block);
    if (i < cases.size() - 1) {
      BlockStatement* next_block = MakeNode<BlockStatement>();
      current_block->statements.push_back(
          MakeNode<ExpressionStatement>(MakeNode<TryLabelExpression>(
              MakeNode<StatementExpression>(case_block),
              MakeNode<TryHandler>(TryHandler::HandlerKind::kLabel,
                                   MakeNode<Identifier>(kNextCaseLabelName),
                                   ParameterList::Empty(), next_block))));
      current_block = next_block;
    }
    accumulated_types =
        i > 0 ? MakeNode<UnionTypeExpression>(accumulated_types, cases[i].type)
              : cases[i].type;
  }
  return ParseResult{result};
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::torque::kNextCaseLabelName, MakeCall(), v8::internal::torque::ParseResultIterator::matched_input(), name, v8::internal::torque::ParseResultIterator::NextAs(), v8::internal::torque::MatchedInput::pos, v8::base::internal::result, v8::internal::torque::BlockStatement::statements, v8::internal::tracing::type, and v8::internal::value.
MakeUnaryOperator()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeUnaryOperator (ParseResultIterator * child_results)
Definition at line 480 of file torque-parser.cc.
                                        {
  auto op = child_results->NextAs<Identifier*>();
  auto e = child_results->NextAs<Expression*>();
  return ParseResult{MakeCall(op, TypeList{}, std::vector<Expression*>{e},
                              std::vector<Statement*>{})};
}
References MakeCall(), and v8::internal::torque::ParseResultIterator::NextAs().
MakeUnionTypeExpression()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeUnionTypeExpression (ParseResultIterator * child_results)
Definition at line 1399 of file torque-parser.cc.
                                        {
  auto a = child_results->NextAs<TypeExpression*>();
  auto b = child_results->NextAs<TypeExpression*>();
  TypeExpression* result = MakeNode<UnionTypeExpression>(a, b);
  return ParseResult{result};
}
References v8::internal::torque::ParseResultIterator::NextAs(), and v8::base::internal::result.
MakeVarDeclarationStatement()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeVarDeclarationStatement (ParseResultIterator * child_results)
Definition at line 1795 of file torque-parser.cc.
                                        {
  auto kind = child_results->NextAs<Identifier*>();
  bool const_qualified = kind->value == "const";
  if (!const_qualified) DCHECK_EQ("let", kind->value);
  auto name = child_results->NextAs<Identifier*>();
  if (!IsLowerCamelCase(name->value)) {
    NamingConventionError("Variable", name, "lowerCamelCase");
  }
  auto type = child_results->NextAs<std::optional<TypeExpression*>>();
  std::optional<Expression*> initializer;
  if (child_results->HasNext())
    initializer = child_results->NextAs<Expression*>();
  if (!initializer && !type) {
    ReportError("Declaration is missing a type.");
  }
  Statement* result = MakeNode<VarDeclarationStatement>(const_qualified, name,
                                                        type, initializer);
  return ParseResult{result};
}
References DCHECK_EQ, v8::internal::torque::ParseResultIterator::HasNext(), v8::internal::torque::IsLowerCamelCase(), name, NamingConventionError(), v8::internal::torque::ParseResultIterator::NextAs(), v8::internal::torque::ReportError(), v8::base::internal::result, v8::internal::tracing::type, and v8::internal::torque::Identifier::value.
MakeWhileStatement()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeWhileStatement (ParseResultIterator * child_results)
Definition at line 1772 of file torque-parser.cc.
                                        {
  auto condition = child_results->NextAs<Expression*>();
  auto body = child_results->NextAs<Statement*>();
  Statement* result = MakeNode<WhileStatement>(condition, body);
  CheckNotDeferredStatement(result);
  return ParseResult{result};
}
References CheckNotDeferredStatement(), v8::internal::torque::ParseResultIterator::NextAs(), and v8::base::internal::result.
NamingConventionError() [1/2]
void v8::internal::torque::anonymous_namespace{torque-parser.cc}::NamingConventionError (const std::string & type, const Identifier * name, const std::string & convention)
Definition at line 328 of file torque-parser.cc.
                                                        {
  NamingConventionError(type, name->value, convention, name->pos);
}
References v8::internal::name, and v8::internal::tracing::type.
Referenced by AddParameter(), LintGenericParameters(), MakeAbstractTypeDeclaration(), MakeBitFieldStructDeclaration(), MakeCatchBlock(), MakeClassDeclaration(), MakeConstDeclaration(), MakeEnumDeclaration(), MakeLabelAndTypes(), MakeLabelBlock(), MakeMethodDeclaration(), MakeNamespaceDeclaration(), MakeStructDeclaration(), MakeTorqueBuiltinDeclaration(), MakeTorqueMacroDeclaration(), and MakeVarDeclarationStatement().
NamingConventionError() [2/2]
void v8::internal::torque::anonymous_namespace{torque-parser.cc}::NamingConventionError (const std::string & type, const std::string & name, const std::string & convention, SourcePosition pos = CurrentSourcePosition::Get())
Definition at line 320 of file torque-parser.cc.
                                                                            {
  Lint(type, " \"", name, "\" does not follow \"", convention,
       "\" naming convention.")
      .Position(pos);
}
References v8::internal::torque::Lint(), v8::internal::name, v8::internal::torque::MessageBuilder::Position(), and v8::internal::tracing::type.
ProcessIfAnnotation() [1/2]
bool v8::internal::torque::anonymous_namespace{torque-parser.cc}::ProcessIfAnnotation (const AnnotationSet & annotations)
Definition at line 882 of file torque-parser.cc.
                                                           {
  if (std::optional<std::string> condition =
          annotations.GetStringParam(ANNOTATION_IF)) {
    if (!BuildFlags::GetFlag(*condition, ANNOTATION_IF)) return false;
  }
  if (std::optional<std::string> condition =
          annotations.GetStringParam(ANNOTATION_IFNOT)) {
    if (BuildFlags::GetFlag(*condition, ANNOTATION_IFNOT)) return false;
  }
  return true;
}
References v8::internal::torque::ANNOTATION_IF, v8::internal::torque::ANNOTATION_IFNOT, v8::internal::torque::BuildFlags::GetFlag(), and v8::internal::torque::anonymous_namespace{torque-parser.cc}::AnnotationSet::GetStringParam().
Referenced by MakeConstDeclaration(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::MakeExtendedVectorIfAnnotation(), MakeExternalMacro(), MakeSpecializationDeclaration(), MakeTorqueMacroDeclaration(), MakeTypeAliasDeclaration(), and ProcessIfAnnotation().
ProcessIfAnnotation() [2/2]
bool v8::internal::torque::anonymous_namespace{torque-parser.cc}::ProcessIfAnnotation (ParseResultIterator * child_results)
Definition at line 894 of file torque-parser.cc.
                                                             {
  AnnotationSet annotations(child_results, {},
                            {ANNOTATION_IF, ANNOTATION_IFNOT});
  return ProcessIfAnnotation(annotations);
}
References v8::internal::torque::ANNOTATION_IF, v8::internal::torque::ANNOTATION_IFNOT, and ProcessIfAnnotation().
ProcessTorqueImportDeclaration()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::ProcessTorqueImportDeclaration (ParseResultIterator * child_results)
Definition at line 1305 of file torque-parser.cc.
                                        {
  auto import_path = child_results->NextAs<std::string>();
  if (!SourceFileMap::FileRelativeToV8RootExists(import_path)) {
    Error("File '", import_path, "' not found.");
  }
  auto import_id = SourceFileMap::GetSourceId(import_path);
  if (!import_id.IsValid()) {
    // TODO(szuend): Instead of reporting and error. Queue the file up
    // for compilation.
    Error("File '", import_path, "'is not part of the source set.").Throw();
  }
  CurrentAst::Get().DeclareImportForCurrentFile(import_id);
  return std::nullopt;
}
References v8::internal::torque::Error(), v8::internal::compiler::turboshaft::Get(), v8::internal::torque::ParseResultIterator::NextAs(), v8::internal::string, and v8::internal::torque::MessageBuilder::Throw().
StringLiteralUnquoteAction()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::StringLiteralUnquoteAction (ParseResultIterator * child_results)
Definition at line 1353 of file torque-parser.cc.
                                        {
  return ParseResult{
      StringLiteralUnquote(child_results->NextAs<std::string>())};
}
References v8::internal::torque::ParseResultIterator::NextAs(), v8::internal::string, and v8::internal::torque::StringLiteralUnquote().
YieldDouble()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::YieldDouble (ParseResultIterator * child_results)
Definition at line 918 of file torque-parser.cc.
                                                                         {
  std::string value = child_results->matched_input().ToString();
  size_t num_chars_converted = 0;
  double result = 0;
  try {
    result = std::stod(value, &num_chars_converted);
  } catch (const std::out_of_range&) {
    Error("double literal out-of-range");
    return ParseResult{result};
  }
  // Tokenizer shouldn't have included extra trailing characters.
  DCHECK_EQ(num_chars_converted, value.size());
  return ParseResult{result};
}
References DCHECK_EQ, v8::internal::torque::Error(), v8::internal::torque::ParseResultIterator::matched_input(), v8::base::internal::result, v8::internal::string, v8::internal::torque::MatchedInput::ToString(), and v8::internal::value.
YieldInt32()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::YieldInt32 (ParseResultIterator * child_results)
Definition at line 900 of file torque-parser.cc.
                                                                        {
  std::string value = child_results->matched_input().ToString();
  size_t num_chars_converted = 0;
  int result = 0;
  try {
    result = std::stoi(value, &num_chars_converted, 0);
  } catch (const std::invalid_argument&) {
    Error("Expected an integer");
    return ParseResult{result};
  } catch (const std::out_of_range&) {
    Error("Integer out of 32-bit range");
    return ParseResult{result};
  }
  // Tokenizer shouldn't have included extra trailing characters.
  DCHECK_EQ(num_chars_converted, value.size());
  return ParseResult{result};
}
References DCHECK_EQ, v8::internal::torque::Error(), v8::internal::torque::ParseResultIterator::matched_input(), v8::base::internal::result, v8::internal::string, v8::internal::torque::MatchedInput::ToString(), and v8::internal::value.
YieldIntegerLiteral()
std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::YieldIntegerLiteral (ParseResultIterator * child_results)
Definition at line 933 of file torque-parser.cc.
                                        {
  std::string value = child_results->matched_input().ToString();
  // Consume a leading minus.
  bool negative = false;
  if (!value.empty() && value[0] == '-') {
    negative = true;
    value = value.substr(1);
  }
  uint64_t absolute_value;
  try {
    size_t parsed = 0;
    absolute_value = std::stoull(value, &parsed, 0);
    DCHECK_EQ(parsed, value.size());
  } catch (const std::invalid_argument&) {
    Error("integer literal could not be parsed").Throw();
  } catch (const std::out_of_range&) {
    Error("integer literal value out of range").Throw();
  }
  return ParseResult(IntegerLiteral(negative, absolute_value));
}
References DCHECK_EQ, v8::internal::torque::Error(), v8::internal::torque::ParseResultIterator::matched_input(), v8::internal::negative, v8::internal::string, v8::internal::torque::MessageBuilder::Throw(), v8::internal::torque::MatchedInput::ToString(), and v8::internal::value.