v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc} Namespace Reference
Functions
bool S390OpcodeOnlySupport12BitDisp (ArchOpcode opcode)
bool S390OpcodeOnlySupport12BitDisp (InstructionCode op)
ArchOpcode SelectLoadOpcode (MemoryRepresentation loaded_rep, RegisterRepresentation result_rep)
ArchOpcode SelectLoadOpcode (LoadRepresentation load_rep)
bool ProduceWord32Result (InstructionSelector *selector, OpIndex node)
static bool DoZeroExtForResult (InstructionSelector *selector, OpIndex node)
void VisitTryTruncateDouble (InstructionSelector *selector, ArchOpcode opcode, OpIndex node)
template<class CanCombineWithLoad >
void GenerateRightOperands (InstructionSelector *selector, OpIndex node, OpIndex right, InstructionCode *opcode, OperandModes *operand_mode, InstructionOperand *inputs, size_t *input_count, CanCombineWithLoad canCombineWithLoad)
template<class CanCombineWithLoad >
void GenerateBinOpOperands (InstructionSelector *selector, OpIndex node, OpIndex left, OpIndex right, InstructionCode *opcode, OperandModes *operand_mode, InstructionOperand *inputs, size_t *input_count, CanCombineWithLoad canCombineWithLoad)
template<class CanCombineWithLoad >
void VisitUnaryOp (InstructionSelector *selector, OpIndex node, InstructionCode opcode, OperandModes operand_mode, FlagsContinuation *cont, CanCombineWithLoad canCombineWithLoad)
template<class CanCombineWithLoad >
void VisitBinOp (InstructionSelector *selector, OpIndex node, InstructionCode opcode, OperandModes operand_mode, FlagsContinuation *cont, CanCombineWithLoad canCombineWithLoad)
void VisitCompare (InstructionSelector *selector, InstructionCode opcode, InstructionOperand left, InstructionOperand right, FlagsContinuation *cont)
void VisitLoadAndTest (InstructionSelector *selector, InstructionCode opcode, OpIndex node, OpIndex value, FlagsContinuation *cont, bool discard_output=false)
void VisitWordCompare (InstructionSelector *selector, OpIndex node, InstructionCode opcode, FlagsContinuation *cont, OperandModes immediate_mode)
void VisitWord32Compare (InstructionSelector *selector, OpIndex node, FlagsContinuation *cont)
void VisitWord64Compare (InstructionSelector *selector, OpIndex node, FlagsContinuation *cont)
void VisitFloat32Compare (InstructionSelector *selector, OpIndex node, FlagsContinuation *cont)
void VisitFloat64Compare (InstructionSelector *selector, OpIndex node, FlagsContinuation *cont)
void VisitTestUnderMask (InstructionSelector *selector, OpIndex node, FlagsContinuation *cont)
Function Documentation
DoZeroExtForResult()
static bool v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::DoZeroExtForResult (InstructionSelector * selector, OpIndex node) [inline], [static]
Definition at line 615 of file instruction-selector-s390.cc.
                                                    {
  return ProduceWord32Result(selector, node);
}
References ProduceWord32Result().
Referenced by v8::internal::compiler::TryMatchNegFromSub(), v8::internal::compiler::TryMatchShiftFromMul(), VisitBinOp(), and VisitUnaryOp().
GenerateBinOpOperands()
template<class CanCombineWithLoad >
void v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::GenerateBinOpOperands (InstructionSelector * selector, OpIndex node, OpIndex left, OpIndex right, InstructionCode * opcode, OperandModes * operand_mode, InstructionOperand * inputs, size_t * input_count, CanCombineWithLoad canCombineWithLoad)
Definition at line 689 of file instruction-selector-s390.cc.
                                                                  {
  S390OperandGenerator g(selector);
  // left is always register
  InstructionOperand const left_input = g.UseRegister(left);
  inputs[(*input_count)++] = left_input;
  if (left == right) {
    inputs[(*input_count)++] = left_input;
    // Can only be RR or RRR
    *operand_mode &= OperandMode::kAllowRRR;
  } else {
    GenerateRightOperands(selector, node, right, opcode, operand_mode, inputs,
                          input_count, canCombineWithLoad);
  }
}
References GenerateRightOperands(), v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::kAllowRRR, and v8::internal::compiler::OperandGenerator::UseRegister().
Referenced by VisitBinOp().
GenerateRightOperands()
template<class CanCombineWithLoad >
void v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::GenerateRightOperands (InstructionSelector * selector, OpIndex node, OpIndex right, InstructionCode * opcode, OperandModes * operand_mode, InstructionOperand * inputs, size_t * input_count, CanCombineWithLoad canCombineWithLoad)
Definition at line 643 of file instruction-selector-s390.cc.
                                                                  {
  S390OperandGenerator g(selector);
  if ((*operand_mode & OperandMode::kAllowImmediate) &&
      g.CanBeImmediate(right, *operand_mode)) {
    inputs[(*input_count)++] = g.UseImmediate(right);
    // Can only be RI or RRI
    *operand_mode &= OperandMode::kAllowImmediate;
  } else if (*operand_mode & OperandMode::kAllowMemoryOperand) {
    const Operation& right_op = selector->Get(right);
    if (right_op.Is<LoadOp>() && selector->CanCover(node, right) &&
        canCombineWithLoad(
            SelectLoadOpcode(selector->load_view(right).ts_loaded_rep(),
                             selector->load_view(right).ts_result_rep()))) {
      AddressingMode mode =
          g.GetEffectiveAddressMemoryOperand(right, inputs, input_count);
      *opcode |= AddressingModeField::encode(mode);
      *operand_mode &= ~OperandMode::kAllowImmediate;
      if (*operand_mode & OperandMode::kAllowRM)
        *operand_mode &= ~OperandMode::kAllowDistinctOps;
    } else if (*operand_mode & OperandMode::kAllowRM) {
      DCHECK(!(*operand_mode & OperandMode::kAllowRRM));
      inputs[(*input_count)++] = g.UseAnyExceptImmediate(right);
      // Can not be Immediate
      *operand_mode &=
          ~OperandMode::kAllowImmediate & ~OperandMode::kAllowDistinctOps;
    } else if (*operand_mode & OperandMode::kAllowRRM) {
      DCHECK(!(*operand_mode & OperandMode::kAllowRM));
      inputs[(*input_count)++] = g.UseAnyExceptImmediate(right);
      // Can not be Immediate
      *operand_mode &= ~OperandMode::kAllowImmediate;
    } else {
      UNREACHABLE();
    }
  } else {
    inputs[(*input_count)++] = g.UseRegister(right);
    // Can only be RR or RRR
    *operand_mode &= OperandMode::kAllowRRR;
  }
}
References v8::internal::compiler::S390OperandGenerator::CanBeImmediate(), v8::internal::compiler::InstructionSelector::CanCover(), v8::internal::DCHECK(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::S390OperandGenerator::GetEffectiveAddressMemoryOperand(), v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::compiler::kAllowImmediate, v8::internal::compiler::kAllowMemoryOperand, v8::internal::compiler::kAllowRM, v8::internal::compiler::kAllowRRM, v8::internal::compiler::kAllowRRR, v8::internal::compiler::InstructionSelector::load_view(), mode(), v8::internal::compiler::SelectLoadOpcode(), v8::internal::compiler::InstructionSelector::LoadView::ts_loaded_rep(), v8::internal::compiler::InstructionSelector::LoadView::ts_result_rep(), v8::internal::UNREACHABLE(), v8::internal::compiler::S390OperandGenerator::UseAnyExceptImmediate(), v8::internal::compiler::OperandGenerator::UseImmediate(), and v8::internal::compiler::OperandGenerator::UseRegister().
Referenced by GenerateBinOpOperands(), and VisitUnaryOp().
ProduceWord32Result()
bool v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::ProduceWord32Result (InstructionSelector * selector, OpIndex node)
Definition at line 517 of file instruction-selector-s390.cc.
                                                                      {
  const Operation& op = selector->Get(node);
  switch (op.opcode) {
    case Opcode::kWordBinop: {
      const auto& binop = op.Cast<WordBinopOp>();
      if (binop.rep != WordRepresentation::Word32()) return false;
      return binop.kind == WordBinopOp::Kind::kAdd ||
             binop.kind == WordBinopOp::Kind::kSub ||
             binop.kind == WordBinopOp::Kind::kMul ||
             binop.kind == WordBinopOp::Kind::kSignedDiv ||
             binop.kind == WordBinopOp::Kind::kUnsignedDiv ||
             binop.kind == WordBinopOp::Kind::kSignedMod ||
             binop.kind == WordBinopOp::Kind::kUnsignedMod ||
             binop.kind == WordBinopOp::Kind::kBitwiseAnd ||
             binop.kind == WordBinopOp::Kind::kBitwiseOr ||
             binop.kind == WordBinopOp::Kind::kBitwiseXor ||
             binop.kind == WordBinopOp::Kind::kSignedMulOverflownBits ||
             binop.kind == WordBinopOp::Kind::kUnsignedMulOverflownBits;
    }
    case Opcode::kWordUnary: {
      const auto& unop = op.Cast<WordUnaryOp>();
      if (unop.rep != WordRepresentation::Word32()) return false;
      return unop.kind == WordUnaryOp::Kind::kCountLeadingZeros ||
             unop.kind == WordUnaryOp::Kind::kPopCount ||
             unop.kind == WordUnaryOp::Kind::kSignExtend8 ||
             unop.kind == WordUnaryOp::Kind::kSignExtend16;
    }
    case Opcode::kChange: {
      const auto& changeop = op.Cast<ChangeOp>();
      switch (changeop.kind) {
        // Float64ExtractLowWord32
        // Float64ExtractHighWord32
        case ChangeOp::Kind::kExtractLowHalf:
        case ChangeOp::Kind::kExtractHighHalf:
          CHECK_EQ(changeop.from, FloatRepresentation::Float64());
          CHECK_EQ(changeop.to, WordRepresentation::Word32());
          return true;
        // BitcastFloat32ToInt32
        case ChangeOp::Kind::kBitcast:
          return changeop.from == FloatRepresentation::Float32() &&
                 changeop.to == WordRepresentation::Word32();
        case ChangeOp::Kind::kSignedFloatTruncateOverflowToMin:
        case ChangeOp::Kind::kUnsignedFloatTruncateOverflowToMin:
          // RoundFloat64ToInt32
          // ChangeFloat64ToInt32
          // TruncateFloat64ToUint32
          // ChangeFloat64ToUint32
          if (changeop.from == FloatRepresentation::Float64() &&
              changeop.to == WordRepresentation::Word32()) {
            return true;
          }
          // TruncateFloat32ToInt32
          // TruncateFloat32ToUint32
          if (changeop.from == FloatRepresentation::Float32() &&
              changeop.to == WordRepresentation::Word32()) {
            return true;
          }
          return false;
        default:
          return false;
      }
    }
    case Opcode::kShift: {
      const auto& shift = op.Cast<ShiftOp>();
      if (shift.rep != WordRepresentation::Word32()) return false;
      return shift.kind == ShiftOp::Kind::kShiftRightArithmetic ||
             shift.kind == ShiftOp::Kind::kShiftRightLogical ||
             shift.kind == ShiftOp::Kind::kShiftRightArithmeticShiftOutZeros ||
             shift.kind == ShiftOp::Kind::kShiftLeft ||
             shift.kind == ShiftOp::Kind::kRotateRight;
    }
    case Opcode::kOverflowCheckedBinop: {
      const auto& ovfbinop = op.Cast<OverflowCheckedBinopOp>();
      if (ovfbinop.rep != WordRepresentation::Word32()) return false;
      return ovfbinop.kind == OverflowCheckedBinopOp::Kind::kSignedAdd ||
             ovfbinop.kind == OverflowCheckedBinopOp::Kind::kSignedSub ||
             ovfbinop.kind == OverflowCheckedBinopOp::Kind::kSignedMul;
    }
    case Opcode::kLoad: {
      LoadRepresentation load_rep = selector->load_view(node).loaded_rep();
      MachineRepresentation rep = load_rep.representation();
      switch (rep) {
        case MachineRepresentation::kWord32:
          return true;
        case MachineRepresentation::kWord8:
          if (load_rep.IsSigned())
            return false;
          else
            return true;
        default:
          return false;
      }
    }
    default:
      return false;
  }
}
References v8::internal::compiler::turboshaft::Operation::Cast(), CHECK_EQ, v8::internal::compiler::turboshaft::FloatRepresentation::Float32(), v8::internal::compiler::turboshaft::FloatRepresentation::Float64(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::MachineType::IsSigned(), v8::internal::compiler::turboshaft::WordBinopOp::kAdd, v8::internal::compiler::turboshaft::ChangeOp::kBitcast, v8::internal::compiler::turboshaft::WordBinopOp::kBitwiseAnd, v8::internal::compiler::turboshaft::WordBinopOp::kBitwiseOr, v8::internal::compiler::turboshaft::WordBinopOp::kBitwiseXor, v8::internal::compiler::turboshaft::WordUnaryOp::kCountLeadingZeros, v8::internal::compiler::turboshaft::ChangeOp::kExtractHighHalf, v8::internal::compiler::turboshaft::ChangeOp::kExtractLowHalf, v8::internal::compiler::turboshaft::WordBinopOp::kind, v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::kind, v8::internal::compiler::turboshaft::WordUnaryOp::kind, v8::internal::compiler::turboshaft::ShiftOp::kind, v8::internal::compiler::turboshaft::WordBinopOp::kMul, v8::internal::compiler::turboshaft::WordUnaryOp::kPopCount, v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::kSignedAdd, v8::internal::compiler::turboshaft::WordBinopOp::kSignedDiv, v8::internal::compiler::turboshaft::ChangeOp::kSignedFloatTruncateOverflowToMin, v8::internal::compiler::turboshaft::WordBinopOp::kSignedMod, v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::kSignedMul, v8::internal::compiler::turboshaft::WordBinopOp::kSignedMulOverflownBits, v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::kSignedSub, v8::internal::compiler::turboshaft::WordUnaryOp::kSignExtend16, v8::internal::compiler::turboshaft::WordUnaryOp::kSignExtend8, v8::internal::compiler::turboshaft::WordBinopOp::kSub, v8::internal::compiler::turboshaft::WordBinopOp::kUnsignedDiv, v8::internal::compiler::turboshaft::ChangeOp::kUnsignedFloatTruncateOverflowToMin, v8::internal::compiler::turboshaft::WordBinopOp::kUnsignedMod, v8::internal::compiler::turboshaft::WordBinopOp::kUnsignedMulOverflownBits, v8::internal::kWord32, v8::internal::kWord8, v8::internal::compiler::InstructionSelector::load_view(), v8::internal::compiler::InstructionSelector::LoadView::loaded_rep(), v8::internal::compiler::turboshaft::Operation::opcode, v8::internal::MachineType::representation(), and v8::internal::compiler::turboshaft::WordRepresentation::Word32().
Referenced by DoZeroExtForResult(), v8::internal::compiler::TryMatchNegFromSub(), v8::internal::compiler::TryMatchShiftFromMul(), v8::internal::compiler::TryMatchSignExtInt16OrInt8FromWord32Sar(), VisitBinOp(), and VisitUnaryOp().
S390OpcodeOnlySupport12BitDisp() [1/2]
bool v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::S390OpcodeOnlySupport12BitDisp (ArchOpcode opcode)
Definition at line 323 of file instruction-selector-s390.cc.
                                                       {
  switch (opcode) {
    case kS390_AddFloat:
    case kS390_AddDouble:
    case kS390_CmpFloat:
    case kS390_CmpDouble:
    case kS390_Float32ToDouble:
      return true;
    default:
      return false;
  }
}
S390OpcodeOnlySupport12BitDisp() [2/2]
bool v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::S390OpcodeOnlySupport12BitDisp (InstructionCode op)
Definition at line 336 of file instruction-selector-s390.cc.
                                                        {
  ArchOpcode opcode = ArchOpcodeField::decode(op);
  return S390OpcodeOnlySupport12BitDisp(opcode);
}
References v8::base::BitField< T, shift, size, U >::decode().
SelectLoadOpcode() [1/2]
ArchOpcode v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::SelectLoadOpcode (LoadRepresentation load_rep)
Definition at line 416 of file instruction-selector-s390.cc.
                                                         {
  ArchOpcode opcode;
  switch (load_rep.representation()) {
    case MachineRepresentation::kFloat32:
      opcode = kS390_LoadFloat32;
      break;
    case MachineRepresentation::kFloat64:
      opcode = kS390_LoadDouble;
      break;
    case MachineRepresentation::kBit: // Fall through.
    case MachineRepresentation::kWord8:
      opcode = load_rep.IsSigned() ? kS390_LoadWordS8 : kS390_LoadWordU8;
      break;
    case MachineRepresentation::kWord16:
      opcode = load_rep.IsSigned() ? kS390_LoadWordS16 : kS390_LoadWordU16;
      break;
    case MachineRepresentation::kWord32:
      opcode = kS390_LoadWordU32;
      break;
    case MachineRepresentation::kCompressedPointer: // Fall through.
    case MachineRepresentation::kCompressed:
    case MachineRepresentation::kIndirectPointer: // Fall through.
    case MachineRepresentation::kSandboxedPointer: // Fall through.
#ifdef V8_COMPRESS_POINTERS
      opcode = kS390_LoadWordS32;
      break;
#else
      UNREACHABLE();
#endif
#ifdef V8_COMPRESS_POINTERS
    case MachineRepresentation::kTaggedSigned:
      opcode = kS390_LoadDecompressTaggedSigned;
      break;
    case MachineRepresentation::kTaggedPointer:
      opcode = kS390_LoadDecompressTagged;
      break;
    case MachineRepresentation::kTagged:
      opcode = kS390_LoadDecompressTagged;
      break;
#else
    case MachineRepresentation::kTaggedSigned: // Fall through.
    case MachineRepresentation::kTaggedPointer: // Fall through.
    case MachineRepresentation::kTagged: // Fall through.
#endif
    case MachineRepresentation::kWord64:
      opcode = kS390_LoadWord64;
      break;
    case MachineRepresentation::kSimd128:
      opcode = kS390_LoadSimd128;
      break;
    case MachineRepresentation::kFloat16:
      UNIMPLEMENTED();
    case MachineRepresentation::kProtectedPointer: // Fall through.
    case MachineRepresentation::kSimd256: // Fall through.
    case MachineRepresentation::kMapWord: // Fall through.
    case MachineRepresentation::kFloat16RawBits: // Fall through.
    case MachineRepresentation::kNone:
    default:
      UNREACHABLE();
  }
  return opcode;
}
References v8::internal::MachineType::IsSigned(), v8::internal::kBit, v8::internal::kCompressed, v8::internal::kCompressedPointer, v8::internal::kFloat16, v8::internal::kFloat16RawBits, v8::internal::kFloat32, v8::internal::kFloat64, v8::internal::kIndirectPointer, v8::internal::kMapWord, v8::internal::kNone, v8::internal::kProtectedPointer, v8::internal::kSandboxedPointer, v8::internal::kSimd128, v8::internal::kSimd256, v8::internal::kTagged, v8::internal::kTaggedPointer, v8::internal::kTaggedSigned, v8::internal::kWord16, v8::internal::kWord32, v8::internal::kWord64, v8::internal::kWord8, v8::internal::MachineType::representation(), v8::internal::compiler::UNIMPLEMENTED(), and v8::internal::UNREACHABLE().
SelectLoadOpcode() [2/2]
ArchOpcode v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::SelectLoadOpcode (MemoryRepresentation loaded_rep, RegisterRepresentation result_rep)
Definition at line 345 of file instruction-selector-s390.cc.
                                                               {
  // NOTE: The meaning of `loaded_rep` = `MemoryRepresentation::AnyTagged()` is
  // we are loading a compressed tagged field, while `result_rep` =
  // `RegisterRepresentation::Tagged()` refers to an uncompressed tagged value.
  switch (loaded_rep) {
    case MemoryRepresentation::Int8():
      DCHECK_EQ(result_rep, RegisterRepresentation::Word32());
      return kS390_LoadWordS8;
    case MemoryRepresentation::Uint8():
      DCHECK_EQ(result_rep, RegisterRepresentation::Word32());
      return kS390_LoadWordU8;
    case MemoryRepresentation::Int16():
      DCHECK_EQ(result_rep, RegisterRepresentation::Word32());
      return kS390_LoadWordS16;
    case MemoryRepresentation::Uint16():
      DCHECK_EQ(result_rep, RegisterRepresentation::Word32());
      return kS390_LoadWordU16;
    case MemoryRepresentation::Int32():
    case MemoryRepresentation::Uint32():
      DCHECK_EQ(result_rep, RegisterRepresentation::Word32());
      return kS390_LoadWordU32;
    case MemoryRepresentation::Int64():
    case MemoryRepresentation::Uint64():
      DCHECK_EQ(result_rep, RegisterRepresentation::Word64());
      return kS390_LoadWord64;
    case MemoryRepresentation::Float16():
      UNIMPLEMENTED();
    case MemoryRepresentation::Float32():
      DCHECK_EQ(result_rep, RegisterRepresentation::Float32());
      return kS390_LoadFloat32;
    case MemoryRepresentation::Float64():
      DCHECK_EQ(result_rep, RegisterRepresentation::Float64());
      return kS390_LoadDouble;
#ifdef V8_COMPRESS_POINTERS
    case MemoryRepresentation::AnyTagged():
    case MemoryRepresentation::TaggedPointer():
      if (result_rep == RegisterRepresentation::Compressed()) {
        return kS390_LoadWordS32;
      }
      DCHECK_EQ(result_rep, RegisterRepresentation::Tagged());
      return kS390_LoadDecompressTagged;
    case MemoryRepresentation::TaggedSigned():
      if (result_rep == RegisterRepresentation::Compressed()) {
        return kS390_LoadWordS32;
      }
      DCHECK_EQ(result_rep, RegisterRepresentation::Tagged());
      return kS390_LoadDecompressTaggedSigned;
#else
    case MemoryRepresentation::AnyTagged():
    case MemoryRepresentation::TaggedPointer():
    case MemoryRepresentation::TaggedSigned():
      DCHECK_EQ(result_rep, RegisterRepresentation::Tagged());
      return kS390_LoadWord64;
#endif
    case MemoryRepresentation::AnyUncompressedTagged():
    case MemoryRepresentation::UncompressedTaggedPointer():
    case MemoryRepresentation::UncompressedTaggedSigned():
      DCHECK_EQ(result_rep, RegisterRepresentation::Tagged());
      return kS390_LoadWord64;
    case MemoryRepresentation::Simd128():
      DCHECK_EQ(result_rep, RegisterRepresentation::Simd128());
      return kS390_LoadSimd128;
    case MemoryRepresentation::ProtectedPointer():
    case MemoryRepresentation::IndirectPointer():
    case MemoryRepresentation::SandboxedPointer():
    case MemoryRepresentation::Simd256():
      UNREACHABLE();
  }
}
References v8::internal::compiler::turboshaft::MemoryRepresentation::AnyTagged(), v8::internal::compiler::turboshaft::MemoryRepresentation::AnyUncompressedTagged(), v8::internal::compiler::turboshaft::RegisterRepresentation::Compressed(), DCHECK_EQ, v8::internal::compiler::turboshaft::MemoryRepresentation::Float16(), v8::internal::compiler::turboshaft::RegisterRepresentation::Float32(), v8::internal::compiler::turboshaft::MemoryRepresentation::Float32(), v8::internal::compiler::turboshaft::RegisterRepresentation::Float64(), v8::internal::compiler::turboshaft::MemoryRepresentation::Float64(), v8::internal::compiler::turboshaft::MemoryRepresentation::IndirectPointer(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int16(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int32(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int64(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int8(), v8::internal::compiler::turboshaft::MemoryRepresentation::ProtectedPointer(), v8::internal::compiler::turboshaft::MemoryRepresentation::SandboxedPointer(), v8::internal::compiler::turboshaft::RegisterRepresentation::Simd128(), v8::internal::compiler::turboshaft::MemoryRepresentation::Simd128(), v8::internal::compiler::turboshaft::MemoryRepresentation::Simd256(), v8::internal::compiler::turboshaft::RegisterRepresentation::Tagged(), v8::internal::compiler::turboshaft::MemoryRepresentation::TaggedPointer(), v8::internal::compiler::turboshaft::MemoryRepresentation::TaggedSigned(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint16(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint32(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint64(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint8(), v8::internal::compiler::turboshaft::MemoryRepresentation::UncompressedTaggedPointer(), v8::internal::compiler::turboshaft::MemoryRepresentation::UncompressedTaggedSigned(), v8::internal::compiler::UNIMPLEMENTED(), v8::internal::UNREACHABLE(), v8::internal::compiler::turboshaft::RegisterRepresentation::Word32(), and v8::internal::compiler::turboshaft::RegisterRepresentation::Word64().
VisitBinOp()
template<class CanCombineWithLoad >
void v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitBinOp (InstructionSelector * selector, OpIndex node, InstructionCode opcode, OperandModes operand_mode, FlagsContinuation * cont, CanCombineWithLoad canCombineWithLoad)
Definition at line 814 of file instruction-selector-s390.cc.
                                                       {
  S390OperandGenerator g(selector);
  const Operation& op = selector->Get(node);
  OpIndex left = op.input(0);
  OpIndex right = op.input(1);
  InstructionOperand inputs[8];
  size_t input_count = 0;
  InstructionOperand outputs[2];
  size_t output_count = 0;
    if (op.TryCast<WordBinopOp>() &&
        WordBinopOp::IsCommutative(
            selector->Get(node).template Cast<WordBinopOp>().kind) &&
        !g.CanBeImmediate(right, operand_mode) &&
        (g.CanBeBetterLeftOperand(right))) {
      std::swap(left, right);
    }
  GenerateBinOpOperands(selector, node, left, right, &opcode, &operand_mode,
                        inputs, &input_count, canCombineWithLoad);
  bool left_is_word32 = ProduceWord32Result(selector, left);
  bool doZeroExt = DoZeroExtForResult(selector, node);
  bool canEliminateZeroExt = left_is_word32;
  if (doZeroExt) {
    // Add zero-ext indication
    inputs[input_count++] = g.TempImmediate(!canEliminateZeroExt);
  }
  if ((operand_mode & OperandMode::kAllowDistinctOps) &&
      // If we can deoptimize as a result of the binop, we need to make sure
      // that the deopt inputs are not overwritten by the binop result. One way
      // to achieve that is to declare the output register as same-as-first.
      !cont->IsDeoptimize()) {
    if (doZeroExt && canEliminateZeroExt) {
      // we have to make sure result and left use the same register
      outputs[output_count++] = g.DefineSameAsFirst(node);
    } else {
      outputs[output_count++] = g.DefineAsRegister(node);
    }
  } else {
    outputs[output_count++] = g.DefineSameAsFirst(node);
  }
  DCHECK_NE(0u, input_count);
  DCHECK_NE(0u, output_count);
  DCHECK_GE(arraysize(inputs), input_count);
  DCHECK_GE(arraysize(outputs), output_count);
  selector->EmitWithContinuation(opcode, output_count, outputs, input_count,
                                 inputs, cont);
}
References arraysize, v8::internal::compiler::S390OperandGenerator::CanBeBetterLeftOperand(), v8::internal::compiler::S390OperandGenerator::CanBeImmediate(), DCHECK_GE, DCHECK_NE, v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::OperandGenerator::DefineSameAsFirst(), DoZeroExtForResult(), v8::internal::compiler::InstructionSelector::EmitWithContinuation(), GenerateBinOpOperands(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::turboshaft::WordBinopOp::IsCommutative(), v8::internal::compiler::FlagsContinuation::IsDeoptimize(), v8::internal::compiler::kAllowDistinctOps, ProduceWord32Result(), v8::internal::compiler::OperandGenerator::TempImmediate(), and v8::internal::compiler::turboshaft::Operation::TryCast().
VisitCompare()
void v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitCompare (InstructionSelector * selector, InstructionCode opcode, InstructionOperand left, InstructionOperand right, FlagsContinuation * cont)
Definition at line 1859 of file instruction-selector-s390.cc.
                                           {
  selector->EmitWithContinuation(opcode, left, right, cont);
}
References v8::internal::compiler::InstructionSelector::EmitWithContinuation().
VisitFloat32Compare()
void v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitFloat32Compare (InstructionSelector * selector, OpIndex node, FlagsContinuation * cont)
Definition at line 1939 of file instruction-selector-s390.cc.
                                                  {
  VisitWordCompare(selector, node, kS390_CmpFloat, cont, OperandMode::kNone);
}
References v8::internal::compiler::kNone, and v8::internal::compiler::VisitWordCompare().
VisitFloat64Compare()
void v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitFloat64Compare (InstructionSelector * selector, OpIndex node, FlagsContinuation * cont)
Definition at line 1945 of file instruction-selector-s390.cc.
                                                  {
  VisitWordCompare(selector, node, kS390_CmpDouble, cont, OperandMode::kNone);
}
References v8::internal::compiler::kNone, and v8::internal::compiler::VisitWordCompare().
VisitLoadAndTest()
void v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitLoadAndTest (InstructionSelector * selector, InstructionCode opcode, OpIndex node, OpIndex value, FlagsContinuation * cont, bool discard_output = false)
Definition at line 1975 of file instruction-selector-s390.cc.
                                           {
  static_assert(kS390_LoadAndTestFloat64 - kS390_LoadAndTestWord32 == 3,
                "LoadAndTest Opcode shouldn't contain other opcodes.");
  // TODO(john.yan): Add support for Float32/Float64.
  DCHECK(opcode >= kS390_LoadAndTestWord32 ||
         opcode <= kS390_LoadAndTestWord64);
  S390OperandGenerator g(selector);
  InstructionOperand inputs[8];
  InstructionOperand outputs[2];
  size_t input_count = 0;
  size_t output_count = 0;
  bool use_value = false;
  int effect_level = selector->GetEffectLevel(node, cont);
  if (g.CanBeMemoryOperand(opcode, node, value, effect_level)) {
    // generate memory operand
    AddressingMode addressing_mode =
        g.GetEffectiveAddressMemoryOperand(value, inputs, &input_count);
    opcode |= AddressingModeField::encode(addressing_mode);
  } else {
    inputs[input_count++] = g.UseAnyExceptImmediate(value);
    use_value = true;
  }
  if (!discard_output && !use_value) {
    outputs[output_count++] = g.DefineAsRegister(value);
  }
  DCHECK(input_count <= 8 && output_count <= 2);
  selector->EmitWithContinuation(opcode, output_count, outputs, input_count,
                                 inputs, cont);
}
References v8::internal::compiler::S390OperandGenerator::CanBeMemoryOperand(), v8::internal::DCHECK(), v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::InstructionSelector::EmitWithContinuation(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::S390OperandGenerator::GetEffectiveAddressMemoryOperand(), v8::internal::compiler::InstructionSelector::GetEffectLevel(), v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::S390OperandGenerator::UseAnyExceptImmediate(), and v8::internal::value.
Referenced by VisitWordCompare().
VisitTestUnderMask()
void v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitTestUnderMask (InstructionSelector * selector, OpIndex node, FlagsContinuation * cont)
Definition at line 1950 of file instruction-selector-s390.cc.
                                                 {
  const Operation& op = selector->Get(node);
  DCHECK(op.Is<Opmask::kWord32BitwiseAnd>() ||
         op.Is<Opmask::kWord64BitwiseAnd>());
  USE(op);
  ArchOpcode opcode;
  if (selector->Get(node).template TryCast<Opmask::kWord32BitwiseAnd>()) {
    opcode = kS390_Tst32;
  } else {
    opcode = kS390_Tst64;
  }
  S390OperandGenerator g(selector);
  OpIndex lhs = op.input(0);
  OpIndex rhs = op.input(1);
  if (!g.CanBeImmediate(rhs, OperandMode::kUint32Imm) &&
      g.CanBeImmediate(lhs, OperandMode::kUint32Imm)) {
    std::swap(lhs, rhs);
  }
  VisitCompare(selector, opcode, g.UseRegister(lhs),
               g.UseOperand(rhs, OperandMode::kUint32Imm), cont);
}
References v8::internal::compiler::S390OperandGenerator::CanBeImmediate(), v8::internal::DCHECK(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::compiler::kUint32Imm, USE, v8::internal::compiler::S390OperandGenerator::UseOperand(), v8::internal::compiler::OperandGenerator::UseRegister(), and v8::internal::compiler::VisitCompare().
VisitTryTruncateDouble()
void v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitTryTruncateDouble (InstructionSelector * selector, ArchOpcode opcode, OpIndex node)
Definition at line 625 of file instruction-selector-s390.cc.
                                          {
  S390OperandGenerator g(selector);
  const Operation& op = selector->Get(node);
  InstructionOperand inputs[] = {g.UseRegister(op.input(0))};
  InstructionOperand outputs[2];
  size_t output_count = 0;
  outputs[output_count++] = g.DefineAsRegister(node);
  OptionalOpIndex success_output = selector->FindProjection(node, 1);
  if (success_output.valid()) {
    outputs[output_count++] = g.DefineAsRegister(success_output.value());
  }
  selector->Emit(opcode, output_count, outputs, 1, inputs);
}
References v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::InstructionSelector::Emit(), v8::internal::compiler::InstructionSelector::FindProjection(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::OperandGenerator::UseRegister(), v8::internal::compiler::turboshaft::OptionalOpIndex::valid(), and v8::internal::compiler::turboshaft::OptionalOpIndex::value().
VisitUnaryOp()
template<class CanCombineWithLoad >
void v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitUnaryOp (InstructionSelector * selector, OpIndex node, InstructionCode opcode, OperandModes operand_mode, FlagsContinuation * cont, CanCombineWithLoad canCombineWithLoad)
Definition at line 765 of file instruction-selector-s390.cc.
                                                         {
  S390OperandGenerator g(selector);
  InstructionOperand inputs[8];
  const Operation& op = selector->Get(node);
  size_t input_count = 0;
  InstructionOperand outputs[2];
  size_t output_count = 0;
  OpIndex input = op.input(0);
  GenerateRightOperands(selector, node, input, &opcode, &operand_mode, inputs,
                        &input_count, canCombineWithLoad);
  bool input_is_word32 = ProduceWord32Result(selector, input);
  bool doZeroExt = DoZeroExtForResult(selector, node);
  bool canEliminateZeroExt = input_is_word32;
  if (doZeroExt) {
    // Add zero-ext indication
    inputs[input_count++] = g.TempImmediate(!canEliminateZeroExt);
  }
  if (!cont->IsDeoptimize()) {
    // If we can deoptimize as a result of the binop, we need to make sure
    // that the deopt inputs are not overwritten by the binop result. One way
    // to achieve that is to declare the output register as same-as-first.
    if (doZeroExt && canEliminateZeroExt) {
      // we have to make sure result and left use the same register
      outputs[output_count++] = g.DefineSameAsFirst(node);
    } else {
      outputs[output_count++] = g.DefineAsRegister(node);
    }
  } else {
    outputs[output_count++] = g.DefineSameAsFirst(node);
  }
  DCHECK_NE(0u, input_count);
  DCHECK_NE(0u, output_count);
  DCHECK_GE(arraysize(inputs), input_count);
  DCHECK_GE(arraysize(outputs), output_count);
  selector->EmitWithContinuation(opcode, output_count, outputs, input_count,
                                 inputs, cont);
}
References arraysize, DCHECK_GE, DCHECK_NE, v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::OperandGenerator::DefineSameAsFirst(), DoZeroExtForResult(), v8::internal::compiler::InstructionSelector::EmitWithContinuation(), GenerateRightOperands(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::FlagsContinuation::IsDeoptimize(), ProduceWord32Result(), and v8::internal::compiler::OperandGenerator::TempImmediate().
VisitWord32Compare()
void v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitWord32Compare (InstructionSelector * selector, OpIndex node, FlagsContinuation * cont)
Definition at line 1924 of file instruction-selector-s390.cc.
                                                 {
  OperandModes mode =
      (CompareLogical(cont) ? OperandMode::kUint32Imm : OperandMode::kInt32Imm);
  VisitWordCompare(selector, node, kS390_Cmp32, cont, mode);
}
References v8::internal::compiler::CompareLogical(), v8::internal::compiler::kInt32Imm, v8::internal::compiler::kUint32Imm, mode(), and v8::internal::compiler::VisitWordCompare().
VisitWord64Compare()
void v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitWord64Compare (InstructionSelector * selector, OpIndex node, FlagsContinuation * cont)
Definition at line 1931 of file instruction-selector-s390.cc.
                                                 {
  OperandModes mode =
      (CompareLogical(cont) ? OperandMode::kUint32Imm : OperandMode::kInt32Imm);
  VisitWordCompare(selector, node, kS390_Cmp64, cont, mode);
}
References v8::internal::compiler::CompareLogical(), v8::internal::compiler::kInt32Imm, v8::internal::compiler::kUint32Imm, mode(), and v8::internal::compiler::VisitWordCompare().
VisitWordCompare()
void v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitWordCompare (InstructionSelector * selector, OpIndex node, InstructionCode opcode, FlagsContinuation * cont, OperandModes immediate_mode)
Definition at line 1870 of file instruction-selector-s390.cc.
                                                   {
  S390OperandGenerator g(selector);
  const Operation& op = selector->Get(node);
  OpIndex lhs = op.input(0);
  OpIndex rhs = op.input(1);
  DCHECK(op.Is<ComparisonOp>() || op.Is<Opmask::kWord32Sub>() ||
         op.Is<Opmask::kWord64Sub>());
  InstructionOperand inputs[8];
  InstructionOperand outputs[1];
  size_t input_count = 0;
  size_t output_count = 0;
  // If one of the two inputs is an immediate, make sure it's on the right, or
  // if one of the two inputs is a memory operand, make sure it's on the left.
  int effect_level = selector->GetEffectLevel(node, cont);
  if ((!g.CanBeImmediate(rhs, immediate_mode) &&
       g.CanBeImmediate(lhs, immediate_mode)) ||
      (!g.CanBeMemoryOperand(opcode, node, rhs, effect_level) &&
       g.CanBeMemoryOperand(opcode, node, lhs, effect_level))) {
    if (!selector->IsCommutative(node)) cont->Commute();
    std::swap(lhs, rhs);
  }
  // check if compare with 0
  if (g.CanBeImmediate(rhs, immediate_mode) && g.GetImmediate(rhs) == 0) {
    DCHECK(opcode == kS390_Cmp32 || opcode == kS390_Cmp64);
    ArchOpcode load_and_test = (opcode == kS390_Cmp32)
                                   ? kS390_LoadAndTestWord32
                                   : kS390_LoadAndTestWord64;
    return VisitLoadAndTest(selector, load_and_test, node, lhs, cont, true);
  }
  inputs[input_count++] = g.UseRegister(lhs);
  if (g.CanBeMemoryOperand(opcode, node, rhs, effect_level)) {
    // generate memory operand
    AddressingMode addressing_mode = g.GetEffectiveAddressMemoryOperand(
        rhs, inputs, &input_count, OpcodeImmMode(opcode));
    opcode |= AddressingModeField::encode(addressing_mode);
  } else if (g.CanBeImmediate(rhs, immediate_mode)) {
    inputs[input_count++] = g.UseImmediate(rhs);
  } else {
    inputs[input_count++] = g.UseAnyExceptImmediate(rhs);
  }
  DCHECK(input_count <= 8 && output_count <= 1);
  selector->EmitWithContinuation(opcode, output_count, outputs, input_count,
                                 inputs, cont);
}
References v8::internal::compiler::S390OperandGenerator::CanBeImmediate(), v8::internal::compiler::S390OperandGenerator::CanBeMemoryOperand(), v8::internal::compiler::FlagsContinuation::Commute(), v8::internal::DCHECK(), v8::internal::compiler::InstructionSelector::EmitWithContinuation(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::S390OperandGenerator::GetEffectiveAddressMemoryOperand(), v8::internal::compiler::InstructionSelector::GetEffectLevel(), v8::internal::compiler::S390OperandGenerator::GetImmediate(), v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::compiler::InstructionSelector::IsCommutative(), OpcodeImmMode, v8::internal::compiler::S390OperandGenerator::UseAnyExceptImmediate(), v8::internal::compiler::OperandGenerator::UseImmediate(), v8::internal::compiler::OperandGenerator::UseRegister(), and VisitLoadAndTest().