v8::internal::wasm::anonymous_namespace{module-compiler.cc} Namespace Reference
Classes
class BackgroundCompileScope
class CompilationUnitQueues
class CompilationStateImpl
struct ExecutionTierPair
class CompilationUnitBuilder
class CompileLazyTimingScope
class CompilationTimeCallback
class BackgroundCompileJob
class TriggerCodeCachingAfterTimeoutTask
Enumerations
enum class CompileStrategy : uint8_t { kLazy
, kEager
, kLazyBaselineEagerTopTier
, kDefault = kEager
 }
enum CompilationTier { kBaseline = 0
, kTopTier = 1
, kNumTiers = kTopTier + 1
 }
enum OnlyLazyFunctions : bool { kAllFunctions = false
, kOnlyLazyFunctions = true
 }
enum CompilationExecutionResult : int8_t { kNoMoreUnits
, kYield
 }
Functions
CompilationStateImpl * Impl (CompilationState *compilation_state)
const CompilationStateImpl * Impl (const CompilationState *compilation_state)
ExecutionTier ApplyHintToExecutionTier (WasmCompilationHintTier hint, ExecutionTier default_tier)
const WasmCompilationHint * GetCompilationHint (const WasmModule *module, uint32_t func_index)
CompileStrategy GetCompileStrategy (const WasmModule *module, WasmEnabledFeatures enabled_features, uint32_t func_index, bool lazy_module)
ExecutionTierPair GetDefaultTiersPerModule (NativeModule *native_module, DebugState is_in_debug_state, bool lazy_module)
ExecutionTierPair GetLazyCompilationTiers (NativeModule *native_module, uint32_t func_index, DebugState is_in_debug_state)
DecodeResult ValidateSingleFunction (Zone *zone, const WasmModule *module, int func_index, base::Vector< const uint8_t > code, WasmEnabledFeatures enabled_features, WasmDetectedFeatures *detected_features)
bool IsLazyModule (const WasmModule *module)
bool IsI16Array (wasm::ValueType type, const WasmModule *module)
bool IsI8Array (wasm::ValueType type, const WasmModule *module, bool allow_nullable)
uint32_t ImportStartOffset (base::Vector< const uint8_t > wire_bytes, uint32_t module_name_start)
const char * GetCompilationEventName (const WasmCompilationUnit &unit, const CompilationEnv &env)
CompilationExecutionResult ExecuteCompilationUnits (std::weak_ptr< NativeModule > native_module, Counters *counters, JobDelegate *delegate, CompilationTier tier)
std::unique_ptr< CompilationUnitBuilder > InitializeCompilation (Isolate *isolate, NativeModule *native_module, ProfileInformation *pgo_info)
bool MayCompriseLazyFunctions (const WasmModule *module, WasmEnabledFeatures enabled_features)
WasmError ValidateFunctions (const WasmModule *module, base::Vector< const uint8_t > wire_bytes, WasmEnabledFeatures enabled_features, OnlyLazyFunctions only_lazy_functions, WasmDetectedFeatures *detected_features)
WasmError ValidateFunctions (const NativeModule &native_module, OnlyLazyFunctions only_lazy_functions)
void CompileNativeModule (Isolate *isolate, v8::metrics::Recorder::ContextId context_id, ErrorThrower *thrower, std::shared_ptr< NativeModule > native_module, ProfileInformation *pgo_info)
std::shared_ptr< NativeModule > GetOrCompileNewNativeModule (Isolate *isolate, WasmEnabledFeatures enabled_features, WasmDetectedFeatures detected_features, CompileTimeImports compile_imports, ErrorThrower *thrower, std::shared_ptr< const WasmModule > module, base::OwnedVector< const uint8_t > wire_bytes, int compilation_id, v8::metrics::Recorder::ContextId context_id, ProfileInformation *pgo_info)
Variables
constexpr uint8_t kMainTaskId = 0
Enumeration Type Documentation
CompilationExecutionResult
enum v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationExecutionResult : int8_t
Enumerator
kNoMoreUnits
kYield
Definition at line 2022 of file module-compiler.cc.
: int8_t { kNoMoreUnits, kYield };
CompilationTier
enum v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationTier
Enumerator
kBaseline
kTopTier
kNumTiers
Definition at line 103 of file module-compiler.cc.
{ kBaseline = 0, kTopTier = 1, kNumTiers = kTopTier + 1 };
CompileStrategy
enum v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompileStrategy : uint8_t [strong]
Enumerator
kLazy
kEager
kLazyBaselineEagerTopTier
kDefault
Definition at line 62 of file module-compiler.cc.
                           : uint8_t {
  // Compiles functions on first use. In this case, execution will block until
  // the function's baseline is reached and top tier compilation starts in
  // background (if applicable).
  // Lazy compilation can help to reduce startup time and code size at the risk
  // of blocking execution.
  kLazy,
  // Compiles baseline ahead of execution and starts top tier compilation in
  // background (if applicable).
  kEager,
  // Triggers baseline compilation on first use (just like {kLazy}) with the
  // difference that top tier compilation is started eagerly.
  // This strategy can help to reduce startup time at the risk of blocking
  // execution, but only in its early phase (until top tier compilation
  // finishes).
  kLazyBaselineEagerTopTier,
  // Marker for default strategy.
  kDefault = kEager,
};
OnlyLazyFunctions
enum v8::internal::wasm::anonymous_namespace{module-compiler.cc}::OnlyLazyFunctions : bool
Enumerator
kAllFunctions
kOnlyLazyFunctions
Definition at line 1152 of file module-compiler.cc.
                       : bool {
  kAllFunctions = false,
  kOnlyLazyFunctions = true,
};
Function Documentation
ApplyHintToExecutionTier()
ExecutionTier v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ApplyHintToExecutionTier (WasmCompilationHintTier hint, ExecutionTier default_tier)
Definition at line 981 of file module-compiler.cc.
                                                                   {
  switch (hint) {
    case WasmCompilationHintTier::kDefault:
      return default_tier;
    case WasmCompilationHintTier::kBaseline:
      return ExecutionTier::kLiftoff;
    case WasmCompilationHintTier::kOptimized:
      return ExecutionTier::kTurbofan;
  }
  UNREACHABLE();
}
References v8::internal::wasm::kBaseline, v8::internal::wasm::kDefault, v8::internal::wasm::kLiftoff, v8::internal::wasm::kOptimized, v8::internal::wasm::kTurbofan, and v8::internal::UNREACHABLE().
Referenced by v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::ApplyCompilationHintToInitialProgress(), and GetLazyCompilationTiers().
CompileNativeModule()
void v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompileNativeModule (Isolate * isolate, v8::metrics::Recorder::ContextId context_id, ErrorThrower * thrower, std::shared_ptr< NativeModule > native_module, ProfileInformation * pgo_info)
Definition at line 2295 of file module-compiler.cc.
                                                       {
  CHECK(!v8_flags.jitless || v8_flags.wasm_jitless);
  const WasmModule* module = native_module->module();
  // The callback captures a shared ptr to the semaphore.
  auto* compilation_state = Impl(native_module->compilation_state());
  if (base::TimeTicks::IsHighResolution()) {
    compilation_state->AddCallback(std::make_unique<CompilationTimeCallback>(
        isolate->async_counters(), isolate->metrics_recorder(), context_id,
        native_module, CompilationTimeCallback::kSynchronous));
  }
  // Initialize the compilation units and kick off background compile tasks.
  std::unique_ptr<CompilationUnitBuilder> builder =
      InitializeCompilation(isolate, native_module.get(), pgo_info);
  compilation_state->InitializeCompilationUnits(std::move(builder));
  // Validate wasm modules for lazy compilation if requested. Never validate
  // asm.js modules as these are valid by construction (additionally a CHECK
  // will catch this during lazy compilation).
  if (!v8_flags.wasm_lazy_validation && module->origin == kWasmOrigin) {
    DCHECK(!thrower->error());
    if (WasmError validation_error =
            ValidateFunctions(*native_module, kOnlyLazyFunctions)) {
      thrower->CompileFailed(std::move(validation_error));
      return;
    }
  }
  if (!compilation_state->failed()) {
    compilation_state->WaitForCompilationEvent(
        CompilationEvent::kFinishedBaselineCompilation);
  }
  if (compilation_state->failed()) {
    DCHECK_IMPLIES(IsLazyModule(module), !v8_flags.wasm_lazy_validation);
    WasmError validation_error =
        ValidateFunctions(*native_module, kAllFunctions);
    CHECK(validation_error.has_error());
    thrower->CompileFailed(std::move(validation_error));
  }
}
References v8::internal::Isolate::async_counters(), CHECK, v8::internal::wasm::ErrorThrower::CompileFailed(), v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::wasm::ErrorThrower::error(), v8::internal::wasm::WasmError::has_error(), Impl(), InitializeCompilation(), v8::base::TimeTicks::IsHighResolution(), IsLazyModule(), kAllFunctions, v8::internal::wasm::kFinishedBaselineCompilation, kOnlyLazyFunctions, v8::internal::wasm::kWasmOrigin, v8::internal::Isolate::metrics_recorder(), v8::internal::wasm::WasmModule::origin, v8::internal::v8_flags, and v8::internal::wasm::ValidateFunctions().
Referenced by GetOrCompileNewNativeModule().
ExecuteCompilationUnits()
CompilationExecutionResult v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ExecuteCompilationUnits (std::weak_ptr< NativeModule > native_module, Counters * counters, JobDelegate * delegate, CompilationTier tier)
Definition at line 2043 of file module-compiler.cc.
                                                 {
  TRACE_EVENT0("v8.wasm", "wasm.ExecuteCompilationUnits");
  // Compilation must be disabled in jitless mode.
  CHECK(!v8_flags.wasm_jitless);
  // These fields are initialized in a {BackgroundCompileScope} before
  // starting compilation.
  std::optional<CompilationEnv> env;
  std::optional<base::FlushDenormalsScope> disable_denormals;
  std::shared_ptr<WireBytesStorage> wire_bytes;
  std::shared_ptr<const WasmModule> module;
  // Task 0 is any main thread (there might be multiple from multiple isolates),
  // worker threads start at 1 (thus the "+ 1").
  static_assert(kMainTaskId == 0);
  int task_id = delegate ? (int{delegate->GetTaskId()} + 1) : kMainTaskId;
  DCHECK_LE(0, task_id);
  CompilationUnitQueues::Queue* queue;
  std::optional<WasmCompilationUnit> unit;
  WasmDetectedFeatures global_detected_features;
  // Preparation (synchronized): Initialize the fields above and get the first
  // compilation unit.
  {
    BackgroundCompileScope compile_scope(native_module);
    if (compile_scope.cancelled()) return kYield;
    env.emplace(CompilationEnv::ForModule(compile_scope.native_module()));
    // We only really need this for optimized compilation, but for simplicity
    // set it just once for everything.
    disable_denormals.emplace(
        compile_scope.native_module()->compile_imports().contains(
            CompileTimeImport::kDisableDenormalFloats));
    wire_bytes = compile_scope.compilation_state()->GetWireBytesStorage();
    module = compile_scope.native_module()->shared_module();
    queue = compile_scope.compilation_state()->GetQueueForCompileTask(task_id);
    unit =
        compile_scope.compilation_state()->GetNextCompilationUnit(queue, tier);
    if (!unit) return kNoMoreUnits;
  }
  TRACE_COMPILE("ExecuteCompilationUnits (task id %d)\n", task_id);
  std::vector<WasmCompilationResult> results_to_publish;
  while (true) {
    ExecutionTier current_tier = unit->tier();
    const char* event_name = GetCompilationEventName(unit.value(), env.value());
    TRACE_EVENT0("v8.wasm", event_name);
    while (unit->tier() == current_tier) {
      // Track detected features on a per-function basis before collecting them
      // into {global_detected_features}.
      WasmDetectedFeatures per_function_detected_features;
      // (asynchronous): Execute the compilation.
      WasmCompilationResult result =
          unit->ExecuteCompilation(&env.value(), wire_bytes.get(), counters,
                                   &per_function_detected_features);
      global_detected_features.Add(per_function_detected_features);
      bool compilation_succeeded = result.succeeded();
      ExecutionTier result_tier = result.result_tier;
      // We don't eagerly compile import wrappers any more.
      DCHECK_GE(unit->func_index(), env->module->num_imported_functions);
      results_to_publish.emplace_back(std::move(result));
      bool yield = delegate && delegate->ShouldYield();
      // (synchronized): Publish the compilation result and get the next unit.
      BackgroundCompileScope compile_scope(native_module);
      if (compile_scope.cancelled()) return kYield;
      if (!compilation_succeeded) {
        compile_scope.compilation_state()->SetError();
        return kNoMoreUnits;
      }
      if (!unit->for_debugging() && result_tier != current_tier) {
        compile_scope.native_module()->AddLiftoffBailout();
      }
      // Yield or get next unit.
      if (yield ||
          !(unit = compile_scope.compilation_state()->GetNextCompilationUnit(
                queue, tier))) {
        std::vector<UnpublishedWasmCode> unpublished_code =
            compile_scope.native_module()->AddCompiledCode(
                base::VectorOf(results_to_publish));
        results_to_publish.clear();
        compile_scope.compilation_state()->SchedulePublishCompilationResults(
            std::move(unpublished_code), tier);
        compile_scope.compilation_state()->OnCompilationStopped(
            global_detected_features);
        return yield ? kYield : kNoMoreUnits;
      }
      // Publish after finishing a certain amount of units, to avoid
      // contention when all threads publish at the end.
      bool batch_full =
          queue->ShouldPublish(static_cast<int>(results_to_publish.size()));
      // Also publish each time the compilation tier changes from Liftoff to
      // TurboFan, such that we immediately publish the baseline compilation
      // results to start execution, and do not wait for a batch to fill up.
      bool liftoff_finished = unit->tier() != current_tier &&
                              unit->tier() == ExecutionTier::kTurbofan;
      if (batch_full || liftoff_finished) {
        std::vector<UnpublishedWasmCode> unpublished_code =
            compile_scope.native_module()->AddCompiledCode(
                base::VectorOf(results_to_publish));
        results_to_publish.clear();
        compile_scope.compilation_state()->SchedulePublishCompilationResults(
            std::move(unpublished_code), tier);
      }
    }
  }
  UNREACHABLE();
}
References v8::base::EnumSet< E, T >::Add(), v8::internal::wasm::NativeModule::AddCompiledCode(), v8::internal::wasm::NativeModule::AddLiftoffBailout(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::BackgroundCompileScope::cancelled(), CHECK, v8::internal::wasm::anonymous_namespace{module-compiler.cc}::BackgroundCompileScope::compilation_state(), v8::internal::wasm::NativeModule::compile_imports(), v8::internal::wasm::CompileTimeImports::contains(), DCHECK_GE, DCHECK_LE, v8::internal::wasm::CompilationEnv::ForModule(), GetCompilationEventName(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::GetNextCompilationUnit(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::GetQueueForCompileTask(), v8::JobDelegate::GetTaskId(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::GetWireBytesStorage(), v8::internal::wasm::kDisableDenormalFloats, kMainTaskId, kNoMoreUnits, v8::internal::wasm::kTurbofan, kYield, v8::internal::wasm::anonymous_namespace{module-compiler.cc}::BackgroundCompileScope::native_module(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::OnCompilationStopped(), v8::base::internal::result, v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::SchedulePublishCompilationResults(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::SetError(), v8::internal::wasm::NativeModule::shared_module(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::Queue::ShouldPublish(), v8::JobDelegate::ShouldYield(), TRACE_COMPILE, TRACE_EVENT0, v8::internal::UNREACHABLE(), v8::internal::v8_flags, and v8::base::VectorOf().
Referenced by v8::internal::wasm::anonymous_namespace{module-compiler.cc}::BackgroundCompileJob::Run(), and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::TierUpAllFunctions().
GetCompilationEventName()
const char* v8::internal::wasm::anonymous_namespace{module-compiler.cc}::GetCompilationEventName (const WasmCompilationUnit & unit, const CompilationEnv & env)
Definition at line 2024 of file module-compiler.cc.
                                                               {
  ExecutionTier tier = unit.tier();
  if (tier == ExecutionTier::kLiftoff) {
    return "wasm.BaselineCompilation";
  }
  if (tier == ExecutionTier::kTurbofan) {
    return "wasm.TopTierCompilation";
  }
  if (unit.func_index() <
      static_cast<int>(env.module->num_imported_functions)) {
    return "wasm.WasmToJSWrapperCompilation";
  }
  return "wasm.OtherCompilation";
}
References v8::internal::wasm::WasmCompilationUnit::func_index(), v8::internal::wasm::kLiftoff, v8::internal::wasm::kTurbofan, v8::internal::wasm::CompilationEnv::module, v8::internal::wasm::WasmModule::num_imported_functions, and v8::internal::wasm::WasmCompilationUnit::tier().
Referenced by ExecuteCompilationUnits().
GetCompilationHint()
const WasmCompilationHint* v8::internal::wasm::anonymous_namespace{module-compiler.cc}::GetCompilationHint (const WasmModule * module, uint32_t func_index)
Definition at line 994 of file module-compiler.cc.
                                                                   {
  DCHECK_LE(module->num_imported_functions, func_index);
  uint32_t hint_index = declared_function_index(module, func_index);
  const std::vector<WasmCompilationHint>& compilation_hints =
      module->compilation_hints;
  if (hint_index < compilation_hints.size()) {
    return &compilation_hints[hint_index];
  }
  return nullptr;
}
References v8::internal::wasm::WasmModule::compilation_hints, DCHECK_LE, v8::internal::wasm::declared_function_index(), and v8::internal::wasm::WasmModule::num_imported_functions.
Referenced by GetCompileStrategy(), and GetLazyCompilationTiers().
GetCompileStrategy()
CompileStrategy v8::internal::wasm::anonymous_namespace{module-compiler.cc}::GetCompileStrategy (const WasmModule * module, WasmEnabledFeatures enabled_features, uint32_t func_index, bool lazy_module)
Definition at line 1006 of file module-compiler.cc.
                                                                          {
  if (lazy_module) return CompileStrategy::kLazy;
  if (!enabled_features.has_compilation_hints()) {
    return CompileStrategy::kDefault;
  }
  auto* hint = GetCompilationHint(module, func_index);
  if (hint == nullptr) return CompileStrategy::kDefault;
  switch (hint->strategy) {
    case WasmCompilationHintStrategy::kLazy:
      return CompileStrategy::kLazy;
    case WasmCompilationHintStrategy::kEager:
      return CompileStrategy::kEager;
    case WasmCompilationHintStrategy::kLazyBaselineEagerTopTier:
      return CompileStrategy::kLazyBaselineEagerTopTier;
    case WasmCompilationHintStrategy::kDefault:
      return CompileStrategy::kDefault;
  }
}
References GetCompilationHint(), v8::internal::wasm::kDefault, v8::internal::wasm::kEager, v8::internal::wasm::kLazy, and v8::internal::wasm::kLazyBaselineEagerTopTier.
Referenced by v8::internal::wasm::CompileLazy(), MayCompriseLazyFunctions(), v8::internal::wasm::AsyncStreamingProcessor::ProcessFunctionBody(), and ValidateFunctions().
GetDefaultTiersPerModule()
ExecutionTierPair v8::internal::wasm::anonymous_namespace{module-compiler.cc}::GetDefaultTiersPerModule (NativeModule * native_module, DebugState is_in_debug_state, bool lazy_module)
Definition at line 1036 of file module-compiler.cc.
                                                             {
  const WasmModule* module = native_module->module();
  if (lazy_module) {
    return {ExecutionTier::kNone, ExecutionTier::kNone};
  }
  if (is_asmjs_module(module)) {
    DCHECK(!is_in_debug_state);
    return {ExecutionTier::kTurbofan, ExecutionTier::kTurbofan};
  }
  if (is_in_debug_state) {
    return {ExecutionTier::kLiftoff, ExecutionTier::kLiftoff};
  }
  ExecutionTier baseline_tier =
      v8_flags.liftoff ? ExecutionTier::kLiftoff : ExecutionTier::kTurbofan;
  bool eager_tier_up = !v8_flags.wasm_dynamic_tiering && v8_flags.wasm_tier_up;
  ExecutionTier top_tier =
      eager_tier_up ? ExecutionTier::kTurbofan : baseline_tier;
  return {baseline_tier, top_tier};
}
References v8::internal::DCHECK(), v8::internal::wasm::is_asmjs_module(), v8::internal::wasm::kLiftoff, v8::internal::wasm::kNone, v8::internal::wasm::kTurbofan, v8::internal::wasm::NativeModule::module(), and v8::internal::v8_flags.
Referenced by GetLazyCompilationTiers(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::InitializeCompilationProgress(), and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::InitializeCompilationProgressAfterDeserialization().
GetLazyCompilationTiers()
ExecutionTierPair v8::internal::wasm::anonymous_namespace{module-compiler.cc}::GetLazyCompilationTiers (NativeModule * native_module, uint32_t func_index, DebugState is_in_debug_state)
Definition at line 1058 of file module-compiler.cc.
                                                                        {
  // For lazy compilation, get the tiers we would use if lazy compilation is
  // disabled.
  constexpr bool kNotLazy = false;
  ExecutionTierPair tiers =
      GetDefaultTiersPerModule(native_module, is_in_debug_state, kNotLazy);
  // If we are in debug mode, we ignore compilation hints.
  if (is_in_debug_state) return tiers;
  // Check if compilation hints override default tiering behaviour.
  if (native_module->enabled_features().has_compilation_hints()) {
    if (auto* hint = GetCompilationHint(native_module->module(), func_index)) {
      tiers.baseline_tier =
          ApplyHintToExecutionTier(hint->baseline_tier, tiers.baseline_tier);
      tiers.top_tier = ApplyHintToExecutionTier(hint->top_tier, tiers.top_tier);
    }
  }
  if (V8_UNLIKELY(v8_flags.wasm_tier_up_filter >= 0 &&
                  func_index !=
                      static_cast<uint32_t>(v8_flags.wasm_tier_up_filter))) {
    tiers.top_tier = tiers.baseline_tier;
  }
  // Correct top tier if necessary.
  static_assert(ExecutionTier::kLiftoff < ExecutionTier::kTurbofan,
                "Assume an order on execution tiers");
  if (tiers.baseline_tier > tiers.top_tier) {
    tiers.top_tier = tiers.baseline_tier;
  }
  return tiers;
}
References ApplyHintToExecutionTier(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ExecutionTierPair::baseline_tier, v8::internal::wasm::NativeModule::enabled_features(), GetCompilationHint(), GetDefaultTiersPerModule(), v8::internal::wasm::kLiftoff, v8::internal::wasm::kTurbofan, v8::internal::wasm::NativeModule::module(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ExecutionTierPair::top_tier, v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by v8::internal::wasm::CompileLazy().
GetOrCompileNewNativeModule()
std::shared_ptr<NativeModule> v8::internal::wasm::anonymous_namespace{module-compiler.cc}::GetOrCompileNewNativeModule (Isolate * isolate, WasmEnabledFeatures enabled_features, WasmDetectedFeatures detected_features, CompileTimeImports compile_imports, ErrorThrower * thrower, std::shared_ptr< const WasmModule > module, base::OwnedVector< const uint8_t > wire_bytes, int compilation_id, v8::metrics::Recorder::ContextId context_id, ProfileInformation * pgo_info)
Definition at line 2378 of file module-compiler.cc.
                                                                         {
  std::shared_ptr<NativeModule> native_module =
      GetWasmEngine()->MaybeGetNativeModule(
          module->origin, wire_bytes.as_vector(), compile_imports, isolate);
  if (native_module) return native_module;
  // Otherwise compile a new NativeModule.
  std::optional<TimedHistogramScope> wasm_compile_module_time_scope;
  if (base::TimeTicks::IsHighResolution()) {
    wasm_compile_module_time_scope.emplace(SELECT_WASM_COUNTER(
        isolate->counters(), module->origin, wasm_compile, module_time));
  }
  size_t code_size_estimate =
      wasm::WasmCodeManager::EstimateNativeModuleCodeSize(module.get());
  native_module = GetWasmEngine()->NewNativeModule(
      isolate, enabled_features, detected_features, std::move(compile_imports),
      module, code_size_estimate);
  native_module->SetWireBytes(std::move(wire_bytes));
  native_module->compilation_state()->set_compilation_id(compilation_id);
  if (!v8_flags.wasm_jitless) {
    // Compile / validate the new module.
    CompileNativeModule(isolate, context_id, thrower, native_module, pgo_info);
  }
  if (thrower->error()) {
    GetWasmEngine()->UpdateNativeModuleCache(true, std::move(native_module),
                                             isolate);
    return {};
  }
  // Finally, put the new module in the cache; this can return the passed
  // NativeModule pointer, or another one (for a previously cached module).
  return GetWasmEngine()->UpdateNativeModuleCache(false, native_module,
                                                  isolate);
}
References v8::base::OwnedVector< T >::as_vector(), CompileNativeModule(), v8::internal::Isolate::counters(), v8::internal::wasm::ErrorThrower::error(), v8::internal::wasm::WasmCodeManager::EstimateNativeModuleCodeSize(), v8::internal::wasm::GetWasmEngine(), v8::base::TimeTicks::IsHighResolution(), v8::internal::wasm::WasmEngine::MaybeGetNativeModule(), v8::internal::wasm::WasmEngine::NewNativeModule(), SELECT_WASM_COUNTER, v8::internal::wasm::WasmEngine::UpdateNativeModuleCache(), and v8::internal::v8_flags.
Referenced by v8::internal::wasm::CompileToNativeModule().
Impl() [1/2]
CompilationStateImpl* v8::internal::wasm::anonymous_namespace{module-compiler.cc}::Impl (CompilationState * compilation_state)
Definition at line 834 of file module-compiler.cc.
                                                                {
  return reinterpret_cast<CompilationStateImpl*>(compilation_state);
}
Referenced by v8::PersistentValueMapBase< K, V, Traits >::Clear(), v8::internal::SharedMacroAssembler< Impl >::impl(), v8::internal::FactoryBase< Impl >::impl(), v8::internal::ParserBase< Impl >::impl(), v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::Invalidate(), and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::TriggerCodeCachingAfterTimeoutTask::Run().
Impl() [2/2]
const CompilationStateImpl* v8::internal::wasm::anonymous_namespace{module-compiler.cc}::Impl (const CompilationState * compilation_state)
Definition at line 837 of file module-compiler.cc.
                                                                            {
  return reinterpret_cast<const CompilationStateImpl*>(compilation_state);
}
Referenced by v8::internal::wasm::CompilationState::AddCallback(), v8::internal::wasm::CompilationState::AllowAnotherTopTierJob(), v8::internal::wasm::CompilationState::AllowAnotherTopTierJobForAllFunctions(), v8::internal::wasm::CompilationState::baseline_compilation_finished(), v8::internal::wasm::CompilationState::CancelCompilation(), v8::internal::wasm::CompilationState::CancelInitialCompilation(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::BackgroundCompileScope::cancelled(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::BackgroundCompileScope::compilation_state(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitBuilder::compilation_state(), v8::internal::wasm::CompileLazy(), CompileNativeModule(), v8::internal::wasm::CompilationState::detected_features(), v8::internal::wasm::CompilationState::EstimateCurrentMemoryConsumption(), v8::internal::wasm::CompilationState::failed(), v8::internal::wasm::AsyncCompileJob::FinishCompile(), v8::internal::wasm::CompilationState::GetWireBytesStorage(), v8::internal::wasm::CompilationState::InitCompileJob(), v8::internal::wasm::CompilationState::InitializeAfterDeserialization(), InitializeCompilation(), v8::internal::wasm::InitializeCompilationForTesting(), v8::internal::wasm::AsyncStreamingProcessor::ProcessCodeSectionHeader(), v8::internal::wasm::AsyncStreamingProcessor::ProcessFunctionBody(), v8::internal::wasm::CompilationState::PublishCode(), v8::internal::wasm::AsyncCompileJob::PrepareAndStartCompile::RunInForeground(), v8::internal::wasm::CompilationState::set_compilation_id(), v8::internal::wasm::CompilationState::SetError(), v8::internal::wasm::CompilationState::SetWireBytesStorage(), v8::internal::wasm::ThrowLazyCompilationError(), v8::internal::wasm::CompilationState::TierUpAllFunctions(), v8::internal::wasm::TriggerTierUp(), v8::internal::wasm::CompilationState::UpdateDetectedFeatures(), v8::internal::wasm::AsyncCompileJob::~AsyncCompileJob(), and v8::internal::wasm::CompilationState::~CompilationState().
ImportStartOffset()
uint32_t v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ImportStartOffset (base::Vector< const uint8_t > wire_bytes, uint32_t module_name_start)
Definition at line 1827 of file module-compiler.cc.
                                                       {
  DCHECK_LT(0, module_name_start);
  uint32_t offset = module_name_start - 1; // Last byte of the string length.
  DCHECK_EQ(wire_bytes[offset] & 0x80, 0);
  while (offset > 0 && (wire_bytes[offset - 1] & 0x80) != 0) {
    offset--;
  }
  return offset;
}
References DCHECK_EQ, and DCHECK_LT.
Referenced by v8::internal::wasm::ValidateAndSetBuiltinImports().
InitializeCompilation()
std::unique_ptr<CompilationUnitBuilder> v8::internal::wasm::anonymous_namespace{module-compiler.cc}::InitializeCompilation (Isolate * isolate, NativeModule * native_module, ProfileInformation * pgo_info)
Definition at line 2159 of file module-compiler.cc.
                                  {
  CompilationStateImpl* compilation_state =
      Impl(native_module->compilation_state());
  auto builder = std::make_unique<CompilationUnitBuilder>(native_module);
  compilation_state->InitializeCompilationProgress(pgo_info);
  return builder;
}
References v8::internal::wasm::NativeModule::compilation_state(), Impl(), and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::InitializeCompilationProgress().
Referenced by CompileNativeModule(), v8::internal::wasm::AsyncStreamingProcessor::ProcessCodeSectionHeader(), and v8::internal::wasm::AsyncCompileJob::PrepareAndStartCompile::RunInForeground().
IsI16Array()
bool v8::internal::wasm::anonymous_namespace{module-compiler.cc}::IsI16Array (wasm::ValueType type, const WasmModule * module)
Definition at line 1804 of file module-compiler.cc.
                                                              {
  if (!type.is_object_reference() || !type.has_index()) return false;
  ModuleTypeIndex reftype = type.ref_index();
  if (!module->has_array(reftype)) return false;
  return module->canonical_type_id(reftype) ==
         TypeCanonicalizer::kPredefinedArrayI16Index;
}
References v8::internal::wasm::WasmModule::canonical_type_id(), v8::internal::wasm::WasmModule::has_array(), v8::internal::wasm::TypeCanonicalizer::kPredefinedArrayI16Index, and v8::internal::tracing::type.
Referenced by v8::internal::wasm::ValidateAndSetBuiltinImports().
IsI8Array()
bool v8::internal::wasm::anonymous_namespace{module-compiler.cc}::IsI8Array (wasm::ValueType type, const WasmModule * module, bool allow_nullable)
Definition at line 1812 of file module-compiler.cc.
                                    {
  if (!type.is_object_reference() || !type.has_index()) return false;
  if (!allow_nullable && type.is_nullable()) return false;
  ModuleTypeIndex reftype = type.ref_index();
  if (!module->has_array(reftype)) return false;
  return module->canonical_type_id(reftype) ==
         TypeCanonicalizer::kPredefinedArrayI8Index;
}
References v8::internal::wasm::WasmModule::canonical_type_id(), v8::internal::wasm::WasmModule::has_array(), v8::internal::wasm::TypeCanonicalizer::kPredefinedArrayI8Index, and v8::internal::tracing::type.
Referenced by v8::internal::wasm::ValidateAndSetBuiltinImports().
IsLazyModule()
bool v8::internal::wasm::anonymous_namespace{module-compiler.cc}::IsLazyModule (const WasmModule * module)
Definition at line 1157 of file module-compiler.cc.
                                            {
  return v8_flags.wasm_lazy_compilation ||
         (v8_flags.asm_wasm_lazy_compilation && is_asmjs_module(module));
}
References v8::internal::wasm::is_asmjs_module(), and v8::internal::v8_flags.
Referenced by v8::internal::wasm::CompileLazy(), CompileNativeModule(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::InitializeCompilationProgress(), MayCompriseLazyFunctions(), and ValidateFunctions().
MayCompriseLazyFunctions()
bool v8::internal::wasm::anonymous_namespace{module-compiler.cc}::MayCompriseLazyFunctions (const WasmModule * module, WasmEnabledFeatures enabled_features)
Definition at line 2169 of file module-compiler.cc.
                                                                    {
  if (IsLazyModule(module)) return true;
  if (enabled_features.has_compilation_hints()) return true;
#ifdef ENABLE_SLOW_DCHECKS
  int start = module->num_imported_functions;
  int end = start + module->num_declared_functions;
  for (int func_index = start; func_index < end; func_index++) {
    SLOW_DCHECK(GetCompileStrategy(module, enabled_features, func_index,
                                   false) != CompileStrategy::kLazy);
  }
#endif
  return false;
}
References v8::internal::compiler::end(), GetCompileStrategy(), IsLazyModule(), v8::internal::wasm::WasmModule::num_declared_functions, v8::internal::wasm::WasmModule::num_imported_functions, and SLOW_DCHECK.
Referenced by ValidateFunctions().
ValidateFunctions() [1/2]
WasmError v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ValidateFunctions (const NativeModule & native_module, OnlyLazyFunctions only_lazy_functions)
Definition at line 2278 of file module-compiler.cc.
                                                                   {
  WasmDetectedFeatures detected_features;
  WasmError result =
      ValidateFunctions(native_module.module(), native_module.wire_bytes(),
                        native_module.enabled_features(), only_lazy_functions,
                        &detected_features);
  if (!result.has_error()) {
    // This function is called before the NativeModule is finished; all detected
    // features will be published afterwards anyway, so ignore the return value
    // here.
    USE(native_module.compilation_state()->UpdateDetectedFeatures(
        detected_features));
  }
  return result;
}
References v8::internal::wasm::NativeModule::compilation_state(), v8::internal::wasm::NativeModule::enabled_features(), v8::internal::wasm::NativeModule::module(), v8::base::internal::result, v8::internal::wasm::CompilationState::UpdateDetectedFeatures(), USE, v8::internal::wasm::ValidateFunctions(), and v8::internal::wasm::NativeModule::wire_bytes().
ValidateFunctions() [2/2]
WasmError v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ValidateFunctions (const WasmModule * module, base::Vector< const uint8_t > wire_bytes, WasmEnabledFeatures enabled_features, OnlyLazyFunctions only_lazy_functions, WasmDetectedFeatures * detected_features)
Definition at line 2252 of file module-compiler.cc.
                                                                     {
  DCHECK_EQ(module->origin, kWasmOrigin);
  if (only_lazy_functions &&
      !MayCompriseLazyFunctions(module, enabled_features)) {
    return {};
  }
  std::function<bool(int)> filter; // Initially empty for "all functions".
  if (only_lazy_functions) {
    const bool is_lazy_module = IsLazyModule(module);
    filter = [module, enabled_features, is_lazy_module](int func_index) {
      CompileStrategy strategy = GetCompileStrategy(module, enabled_features,
                                                    func_index, is_lazy_module);
      return strategy == CompileStrategy::kLazy ||
             strategy == CompileStrategy::kLazyBaselineEagerTopTier;
    };
  }
  // Call {ValidateFunctions} in the module decoder.
  return ValidateFunctions(module, enabled_features, wire_bytes, filter,
                           detected_features);
}
References v8::internal::bool, DCHECK_EQ, GetCompileStrategy(), IsLazyModule(), v8::internal::wasm::kWasmOrigin, MayCompriseLazyFunctions(), v8::internal::wasm::WasmModule::origin, and v8::internal::wasm::ValidateFunctions().
ValidateSingleFunction()
DecodeResult v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ValidateSingleFunction (Zone * zone, const WasmModule * module, int func_index, base::Vector< const uint8_t > code, WasmEnabledFeatures enabled_features, WasmDetectedFeatures * detected_features)
Definition at line 1133 of file module-compiler.cc.
                                                                             {
  // Sometimes functions get validated unpredictably in the background, for
  // debugging or when inlining one function into another. We check here if that
  // is the case, and exit early if so.
  if (module->function_was_validated(func_index)) return {};
  const WasmFunction* func = &module->functions[func_index];
  bool is_shared = module->type(func->sig_index).is_shared;
  FunctionBody body{func->sig, func->code.offset(), code.begin(), code.end(),
                    is_shared};
  DecodeResult result = ValidateFunctionBody(zone, enabled_features, module,
                                             detected_features, body);
  if (result.ok()) module->set_function_validated(func_index);
  return result;
}
References code, v8::internal::wasm::WasmFunction::code, v8::internal::wasm::WasmModule::function_was_validated(), v8::internal::wasm::WasmModule::functions, v8::internal::is_shared, v8::internal::wasm::TypeDefinition::is_shared, v8::internal::wasm::WireBytesRef::offset(), v8::base::internal::result, v8::internal::wasm::WasmModule::set_function_validated(), v8::internal::wasm::WasmFunction::sig, v8::internal::wasm::WasmFunction::sig_index, v8::internal::wasm::WasmModule::type(), and v8::internal::wasm::ValidateFunctionBody().
Referenced by v8::internal::wasm::ValidateFunctionsStreamingJob::Run(), and v8::internal::wasm::ThrowLazyCompilationError().
Variable Documentation
kMainTaskId
constexpr uint8_t v8::internal::wasm::anonymous_namespace{module-compiler.cc}::kMainTaskId = 0 [constexpr]
Definition at line 2040 of file module-compiler.cc.
Referenced by ExecuteCompilationUnits(), and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::TierUpAllFunctions().