v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc} Namespace Reference
Classes
struct StringImports
class DataRange
class GeneratorAlternativesPerOption
class BodyGen
class ModuleGen
Typedefs
using GenerateFn = void(BodyGen::*)(DataRange *)
using GenerateFnWithHeap = bool(BodyGen::*)(HeapType, DataRange *, Nullability)
Enumerations
enum IncludeNumericTypes { kIncludeNumericTypes = true
, kExcludeNumericTypes = false
 }
enum IncludePackedTypes { kIncludePackedTypes = true
, kExcludePackedTypes = false
 }
enum IncludeAllGenerics { kIncludeAllGenerics = true
, kExcludeSomeGenerics = false
 }
enum IncludeS128 { kIncludeS128 = true
, kExcludeS128 = false
 }
Functions
int MaxTableSize ()
int MaxNumOfFunctions ()
template<typename... T>
constexpr auto CreateArray (T... elements)
template<typename T , size_t... N>
constexpr auto ConcatArrays (std::array< T, N >... array)
ValueType GetValueTypeHelper (WasmModuleGenerationOptions options, DataRange *data, uint32_t num_nullable_types, uint32_t num_non_nullable_types, IncludeNumericTypes include_numeric_types, IncludePackedTypes include_packed_types, IncludeAllGenerics include_all_generics, IncludeS128 include_s128=kIncludeS128)
ValueType GetValueType (WasmModuleGenerationOptions options, DataRange *data, uint32_t num_types)
void GeneratePassiveDataSegment (DataRange *range, WasmModuleBuilder *builder)
uint32_t GenerateRefTypeElementSegment (DataRange *range, WasmModuleBuilder *builder, ValueType element_type)
std::vector< ValueType > GenerateTypes (WasmModuleGenerationOptions options, DataRange *data, uint32_t num_ref_types)
FunctionSig * CreateSignature (Zone *zone, base::Vector< const ValueType > param_types, base::Vector< const ValueType > return_types)
template<size_t kNumMVP, size_t kAdditionalSimd, size_t kAdditionalWasmGC>
GeneratorAlternativesPerOption (std::array< GenerateFn, kNumMVP >, std::array< GenerateFn, kAdditionalSimd >, std::array< GenerateFn, kAdditionalWasmGC >) -> GeneratorAlternativesPerOption< kNumMVP, kAdditionalSimd, kAdditionalWasmGC >
WasmInitExpr GenerateInitExpr (Zone *zone, DataRange &range, WasmModuleBuilder *builder, ValueType type, const std::vector< ModuleTypeIndex > &structs, const std::vector< ModuleTypeIndex > &arrays, uint32_t recursion_depth)
WasmInitExpr GenerateStructNewInitExpr (Zone *zone, DataRange &range, WasmModuleBuilder *builder, ModuleTypeIndex index, const std::vector< ModuleTypeIndex > &structs, const std::vector< ModuleTypeIndex > &arrays, uint32_t recursion_depth)
WasmInitExpr GenerateArrayInitExpr (Zone *zone, DataRange &range, WasmModuleBuilder *builder, ModuleTypeIndex index, const std::vector< ModuleTypeIndex > &structs, const std::vector< ModuleTypeIndex > &arrays, uint32_t recursion_depth)
bool HasSameReturns (const FunctionSig *a, const FunctionSig *b)
void EmitDeoptAndReturnValues (BodyGen gen_body, WasmFunctionBuilder *f, const FunctionSig *target_sig, ModuleTypeIndex target_sig_index, uint32_t global_index, uint32_t table_index, bool use_table64, DataRange *data)
void EmitCallAndReturnValues (BodyGen gen_body, WasmFunctionBuilder *f, WasmFunctionBuilder *callee, uint32_t table_index, bool use_table64, DataRange *data)
Variables
constexpr int kMaxArrays = 3
constexpr int kMaxStructs = 4
constexpr int kMaxStructFields = 4
constexpr int kMaxGlobals = 64
constexpr uint32_t kMaxLocals = 32
constexpr int kMaxParameters = 15
constexpr int kMaxReturns = 15
constexpr int kMaxExceptions = 4
constexpr int kMaxTables = 4
constexpr int kMaxMemories = 4
constexpr int kMaxArraySize = 20
constexpr int kMaxPassiveDataSegments = 2
constexpr uint32_t kMaxRecursionDepth = 64
constexpr int kMaxCatchCases = 6
Typedef Documentation
GenerateFn
using v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateFn = typedef void (BodyGen::*)(DataRange*)
Definition at line 361 of file random-module-generation.cc.
GenerateFnWithHeap
using v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateFnWithHeap = typedef bool (BodyGen::*)(HeapType, DataRange*, Nullability)
Definition at line 362 of file random-module-generation.cc.
Enumeration Type Documentation
IncludeAllGenerics
enum v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::IncludeAllGenerics
Enumerator
kIncludeAllGenerics
kExcludeSomeGenerics
Definition at line 216 of file random-module-generation.cc.
                        {
  kIncludeAllGenerics = true,
  kExcludeSomeGenerics = false
};
IncludeNumericTypes
enum v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::IncludeNumericTypes
Enumerator
kIncludeNumericTypes
kExcludeNumericTypes
Definition at line 208 of file random-module-generation.cc.
                         {
  kIncludeNumericTypes = true,
  kExcludeNumericTypes = false
};
IncludePackedTypes
enum v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::IncludePackedTypes
Enumerator
kIncludePackedTypes
kExcludePackedTypes
Definition at line 212 of file random-module-generation.cc.
                        {
  kIncludePackedTypes = true,
  kExcludePackedTypes = false
};
IncludeS128
enum v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::IncludeS128
Enumerator
kIncludeS128
kExcludeS128
Definition at line 220 of file random-module-generation.cc.
{ kIncludeS128 = true, kExcludeS128 = false };
Function Documentation
ConcatArrays()
template<typename T , size_t... N>
constexpr auto v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ConcatArrays (std::array< T, N >... array) [constexpr]
Definition at line 88 of file random-module-generation.cc.
                                                     {
  constexpr size_t kNumArrays = sizeof...(array);
  std::array<T*, kNumArrays> kArrays = {&array[0]...};
  constexpr size_t kLengths[kNumArrays] = {array.size()...};
  constexpr size_t kSumOfLengths = (... + array.size());
  std::array<T, kSumOfLengths> result = {0};
  size_t result_index = 0;
  for (size_t arr = 0; arr < kNumArrays; arr++) {
    for (size_t pos = 0; pos < kLengths[arr]; pos++) {
      result[result_index++] = kArrays[arr][pos];
    }
  }
  return result;
}
References v8::base::internal::result.
CreateArray()
template<typename... T>
constexpr auto v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::CreateArray (T... elements) [constexpr]
Definition at line 81 of file random-module-generation.cc.
                                          {
  std::array result = {elements...};
  return result;
}
References v8::base::internal::result.
Referenced by v8::internal::compiler::JSCallReducerAssembler::CreateArrayNoThrow(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GenerateF32(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GenerateF64(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GenerateI32(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GenerateI64(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GenerateRef(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GenerateS128(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GenerateVoid(), v8::internal::compiler::JSCallReducer::ReduceArrayConstructor(), and v8::internal::compiler::JSCallReducer::ReduceJSConstruct().
CreateSignature()
FunctionSig* v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::CreateSignature (Zone * zone, base::Vector< const ValueType > param_types, base::Vector< const ValueType > return_types)
Definition at line 347 of file random-module-generation.cc.
                                                                       {
  FunctionSig::Builder builder(zone, return_types.size(), param_types.size());
  for (auto& type : param_types) {
    builder.AddParam(type);
  }
  for (auto& type : return_types) {
    builder.AddReturn(type);
  }
  return builder.Get();
}
References v8::internal::SignatureBuilder< SigT, T >::AddParam(), v8::internal::SignatureBuilder< SigT, T >::AddReturn(), v8::internal::SignatureBuilder< SigT, T >::Get(), v8::base::Vector< T >::size(), and v8::internal::tracing::type.
Referenced by v8::internal::wasm::fuzzing::GenerateWasmModuleForDeopt(), v8::internal::wasm::fuzzing::GenerateWasmModuleForRevec(), and v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::try_table_rec().
EmitCallAndReturnValues()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::EmitCallAndReturnValues (BodyGen gen_body, WasmFunctionBuilder * f, WasmFunctionBuilder * callee, uint32_t table_index, bool use_table64, DataRange * data)
Definition at line 4723 of file random-module-generation.cc.
                                                                {
  const FunctionSig* callee_sig = callee->signature();
  uint32_t callee_index =
      callee->func_index() + gen_body.NumImportedFunctions();
  base::Vector<const ValueType> return_types = f->signature()->returns();
  // Split the return types randomly and generate some values before the
  // deopting call and some afterwards to create more interesting test cases.
  uint32_t returns_split = data->get<uint8_t>() % (return_types.size() + 1);
  if (returns_split) {
    gen_body.Generate(return_types.SubVector(0, returns_split), data);
  }
  gen_body.Generate(callee_sig->parameters(), data);
  // Tail calls can only be emitted if the return types match.
  bool same_returns = HasSameReturns(callee_sig, f->signature());
  size_t option_count = (same_returns + 1) * 3;
  switch (data->get<uint8_t>() % option_count) {
    case 0:
      f->EmitWithU32V(kExprCallFunction, callee_index);
      break;
    case 1:
      f->EmitWithU32V(kExprRefFunc, callee_index);
      f->EmitWithU32V(kExprCallRef, callee->sig_index());
      break;
    case 2:
      // Note that this assumes that the declared function index is the same as
      // the index of the function in the table.
      use_table64 ? f->EmitI64Const(callee->func_index())
                  : f->EmitI32Const(callee->func_index());
      f->EmitWithU32V(kExprCallIndirect, callee->sig_index());
      f->EmitByte(table_index);
      break;
    case 3:
      f->EmitWithU32V(kExprReturnCall, callee_index);
      break;
    case 4:
      f->EmitWithU32V(kExprRefFunc, callee_index);
      f->EmitWithU32V(kExprReturnCallRef, callee->sig_index());
      break;
    case 5:
      // Note that this assumes that the declared function index is the same as
      // the index of the function in the table.
      use_table64 ? f->EmitI64Const(callee->func_index())
                  : f->EmitI32Const(callee->func_index());
      f->EmitWithU32V(kExprReturnCallIndirect, callee->sig_index());
      f->EmitByte(table_index);
      break;
    default:
      UNREACHABLE();
  }
  gen_body.ConsumeAndGenerate(callee_sig->returns(),
                              return_types.SubVectorFrom(returns_split), data);
}
References v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::ConsumeAndGenerate(), v8::internal::wasm::WasmFunctionBuilder::EmitByte(), v8::internal::wasm::WasmFunctionBuilder::EmitI32Const(), v8::internal::wasm::WasmFunctionBuilder::EmitI64Const(), v8::internal::wasm::WasmFunctionBuilder::EmitWithU32V(), v8::internal::wasm::WasmFunctionBuilder::func_index(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::Generate(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), HasSameReturns(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::NumImportedFunctions(), v8::internal::Signature< T >::parameters(), v8::internal::Signature< T >::returns(), v8::internal::wasm::WasmFunctionBuilder::sig_index(), v8::internal::wasm::WasmFunctionBuilder::signature(), v8::base::Vector< T >::size(), v8::base::Vector< T >::SubVector(), v8::base::Vector< T >::SubVectorFrom(), and v8::internal::UNREACHABLE().
EmitDeoptAndReturnValues()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::EmitDeoptAndReturnValues (BodyGen gen_body, WasmFunctionBuilder * f, const FunctionSig * target_sig, ModuleTypeIndex target_sig_index, uint32_t global_index, uint32_t table_index, bool use_table64, DataRange * data)
Definition at line 4667 of file random-module-generation.cc.
                                                                 {
  base::Vector<const ValueType> return_types = f->signature()->returns();
  // Split the return types randomly and generate some values before the
  // deopting call and some afterwards. (This makes sure that we have deopts
  // where there are values on the wasm value stack which are not used by the
  // deopting call itself.)
  uint32_t returns_split = data->get<uint8_t>() % (return_types.size() + 1);
  if (returns_split) {
    gen_body.Generate(return_types.SubVector(0, returns_split), data);
  }
  gen_body.Generate(target_sig->parameters(), data);
  f->EmitWithU32V(kExprGlobalGet, global_index);
  if (use_table64) {
    f->Emit(kExprI64UConvertI32);
  }
  // Tail calls can only be emitted if the return types match.
  bool same_returns = HasSameReturns(target_sig, f->signature());
  size_t option_count = (same_returns + 1) * 2;
  switch (data->get<uint8_t>() % option_count) {
    case 0:
      // Emit call_ref.
      f->Emit(kExprTableGet);
      f->EmitU32V(table_index);
      f->EmitWithPrefix(kExprRefCast);
      f->EmitI32V(target_sig_index);
      f->EmitWithU32V(kExprCallRef, target_sig_index);
      break;
    case 1:
      // Emit call_indirect.
      f->EmitWithU32V(kExprCallIndirect, target_sig_index);
      f->EmitByte(table_index);
      break;
    case 2:
      // Emit return_call_ref.
      f->Emit(kExprTableGet);
      f->EmitU32V(table_index);
      f->EmitWithPrefix(kExprRefCast);
      f->EmitI32V(target_sig_index);
      f->EmitWithU32V(kExprReturnCallRef, target_sig_index);
      break;
    case 3:
      // Emit return_call_indirect.
      f->EmitWithU32V(kExprReturnCallIndirect, target_sig_index);
      f->EmitByte(table_index);
      break;
    default:
      UNREACHABLE();
  }
  gen_body.ConsumeAndGenerate(target_sig->returns(),
                              return_types.SubVectorFrom(returns_split), data);
}
References v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::ConsumeAndGenerate(), v8::internal::wasm::WasmFunctionBuilder::Emit(), v8::internal::wasm::WasmFunctionBuilder::EmitByte(), v8::internal::wasm::WasmFunctionBuilder::EmitI32V(), v8::internal::wasm::WasmFunctionBuilder::EmitU32V(), v8::internal::wasm::WasmFunctionBuilder::EmitWithPrefix(), v8::internal::wasm::WasmFunctionBuilder::EmitWithU32V(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::Generate(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), HasSameReturns(), v8::internal::Signature< T >::parameters(), v8::internal::Signature< T >::returns(), v8::internal::wasm::WasmFunctionBuilder::signature(), v8::base::Vector< T >::size(), v8::base::Vector< T >::SubVector(), v8::base::Vector< T >::SubVectorFrom(), and v8::internal::UNREACHABLE().
GenerateArrayInitExpr()
WasmInitExpr v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateArrayInitExpr (Zone * zone, DataRange & range, WasmModuleBuilder * builder, ModuleTypeIndex index, const std::vector< ModuleTypeIndex > & structs, const std::vector< ModuleTypeIndex > & arrays, uint32_t recursion_depth)
Definition at line 4122 of file random-module-generation.cc.
                                                             {
  constexpr int kMaxArrayLength = 20;
  uint8_t choice = range.get<uint8_t>() % 3;
  ValueType element_type = builder->GetArrayType(index)->element_type();
  if (choice == 0) {
    size_t element_count = range.get<uint8_t>() % kMaxArrayLength;
    if (!element_type.is_defaultable()) {
      // If the element type is not defaultable, limit the size to 0 or 1
      // to prevent having to create too many such elements on the value
      // stack. (With multiple non-nullable references, this can explode
      // in size very quickly.)
      element_count %= 2;
    }
    ZoneVector<WasmInitExpr>* elements =
        zone->New<ZoneVector<WasmInitExpr>>(zone);
    for (size_t i = 0; i < element_count; i++) {
      elements->push_back(GenerateInitExpr(zone, range, builder, element_type,
                                           structs, arrays,
                                           recursion_depth + 1));
    }
    return WasmInitExpr::ArrayNewFixed(index, elements);
  } else if (choice == 1 || !element_type.is_defaultable()) {
    // TODO(14034): Add other int expressions to length (same below).
    WasmInitExpr length = WasmInitExpr(range.get<uint8_t>() % kMaxArrayLength);
    WasmInitExpr init = GenerateInitExpr(zone, range, builder, element_type,
                                         structs, arrays, recursion_depth + 1);
    return WasmInitExpr::ArrayNew(zone, index, init, length);
  } else {
    WasmInitExpr length = WasmInitExpr(range.get<uint8_t>() % kMaxArrayLength);
    return WasmInitExpr::ArrayNewDefault(zone, index, length);
  }
}
References v8::internal::wasm::WasmInitExpr::ArrayNew(), v8::internal::wasm::WasmInitExpr::ArrayNewDefault(), v8::internal::wasm::WasmInitExpr::ArrayNewFixed(), v8::internal::wasm::ArrayType::element_type(), GenerateInitExpr(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), v8::internal::wasm::WasmModuleBuilder::GetArrayType(), v8::internal::index, v8::internal::length, v8::internal::Zone::New(), and v8::internal::ZoneVector< T >::push_back().
Referenced by GenerateInitExpr().
GenerateInitExpr()
WasmInitExpr v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateInitExpr (Zone * zone, DataRange & range, WasmModuleBuilder * builder, ValueType type, const std::vector< ModuleTypeIndex > & structs, const std::vector< ModuleTypeIndex > & arrays, uint32_t recursion_depth)
Definition at line 4160 of file random-module-generation.cc.
                                                        {
  switch (type.kind()) {
    case kI8:
    case kI16:
    case kI32: {
      if (range.size() == 0 || recursion_depth >= kMaxRecursionDepth) {
        return WasmInitExpr(int32_t{0});
      }
      // 50% to generate a constant, 50% to generate a binary operator.
      uint8_t choice = range.get<uint8_t>() % 6;
      switch (choice) {
        case 0:
        case 1:
        case 2:
          if (choice % 2 == 0 && builder->NumGlobals()) {
            // Search for a matching global to emit a global.get.
            int num_globals = builder->NumGlobals();
            int start_index = range.get<uint8_t>() % num_globals;
            for (int i = 0; i < num_globals; ++i) {
              int index = (start_index + i) % num_globals;
              if (builder->GetGlobalType(index) == type &&
                  !builder->IsMutableGlobal(index)) {
                return WasmInitExpr::GlobalGet(index);
              }
            }
            // Fall back to constant if no matching global was found.
          }
          return WasmInitExpr(range.getPseudoRandom<int32_t>());
        default:
          WasmInitExpr::Operator op = choice == 3 ? WasmInitExpr::kI32Add
                                      : choice == 4 ? WasmInitExpr::kI32Sub
                                                    : WasmInitExpr::kI32Mul;
          return WasmInitExpr::Binop(
              zone, op,
              GenerateInitExpr(zone, range, builder, kWasmI32, structs, arrays,
                               recursion_depth + 1),
              GenerateInitExpr(zone, range, builder, kWasmI32, structs, arrays,
                               recursion_depth + 1));
      }
    }
    case kI64: {
      if (range.size() == 0 || recursion_depth >= kMaxRecursionDepth) {
        return WasmInitExpr(int64_t{0});
      }
      // 50% to generate a constant, 50% to generate a binary operator.
      uint8_t choice = range.get<uint8_t>() % 6;
      switch (choice) {
        case 0:
        case 1:
        case 2:
          return WasmInitExpr(range.get<int64_t>());
        default:
          WasmInitExpr::Operator op = choice == 3 ? WasmInitExpr::kI64Add
                                      : choice == 4 ? WasmInitExpr::kI64Sub
                                                    : WasmInitExpr::kI64Mul;
          return WasmInitExpr::Binop(
              zone, op,
              GenerateInitExpr(zone, range, builder, kWasmI64, structs, arrays,
                               recursion_depth + 1),
              GenerateInitExpr(zone, range, builder, kWasmI64, structs, arrays,
                               recursion_depth + 1));
      }
    }
    case kF16:
    case kF32:
      return WasmInitExpr(0.0f);
    case kF64:
      return WasmInitExpr(0.0);
    case kS128: {
      uint8_t s128_const[kSimd128Size] = {0};
      return WasmInitExpr(s128_const);
    }
    case kRefNull: {
      bool null_only = false;
      switch (type.heap_representation()) {
        case HeapType::kNone:
        case HeapType::kNoFunc:
        case HeapType::kNoExtern:
          null_only = true;
          break;
        default:
          break;
      }
      if (range.size() == 0 || recursion_depth >= kMaxRecursionDepth ||
          null_only || (range.get<uint8_t>() % 4 == 0)) {
        return WasmInitExpr::RefNullConst(type.heap_type());
      }
      [[fallthrough]];
    }
    case kRef: {
      switch (type.heap_representation()) {
        case HeapType::kStruct: {
          ModuleTypeIndex index =
              structs[range.get<uint8_t>() % structs.size()];
          return GenerateStructNewInitExpr(zone, range, builder, index, structs,
                                           arrays, recursion_depth);
        }
        case HeapType::kAny: {
          // Do not use 0 as the determining value here, otherwise an exhausted
          // {range} will generate an infinite recursion with the {kExtern}
          // case.
          if (recursion_depth < kMaxRecursionDepth && range.size() > 0 &&
              range.get<uint8_t>() % 4 == 3) {
            return WasmInitExpr::AnyConvertExtern(
                zone, GenerateInitExpr(zone, range, builder,
                                       ValueType::RefMaybeNull(
                                           kWasmExternRef, type.nullability()),
                                       structs, arrays, recursion_depth + 1));
          }
          [[fallthrough]];
        }
        case HeapType::kEq: {
          uint8_t choice = range.get<uint8_t>() % 3;
          HeapType subtype = choice == 0 ? kWasmI31Ref
                             : choice == 1 ? kWasmArrayRef
                                           : kWasmStructRef;
          return GenerateInitExpr(
              zone, range, builder,
              ValueType::RefMaybeNull(subtype, type.nullability()), structs,
              arrays, recursion_depth);
        }
        case HeapType::kFunc: {
          uint32_t index =
              range.get<uint32_t>() % (builder->NumDeclaredFunctions() +
                                       builder->NumImportedFunctions());
          return WasmInitExpr::RefFuncConst(index);
        }
        case HeapType::kExtern:
          return WasmInitExpr::ExternConvertAny(
              zone, GenerateInitExpr(zone, range, builder,
                                     ValueType::RefMaybeNull(
                                         kWasmAnyRef, type.nullability()),
                                     structs, arrays, recursion_depth + 1));
        case HeapType::kI31:
          return WasmInitExpr::RefI31(
              zone, GenerateInitExpr(zone, range, builder, kWasmI32, structs,
                                     arrays, recursion_depth + 1));
        case HeapType::kArray: {
          ModuleTypeIndex index = arrays[range.get<uint8_t>() % arrays.size()];
          return GenerateArrayInitExpr(zone, range, builder, index, structs,
                                       arrays, recursion_depth);
        }
        case HeapType::kNone:
        case HeapType::kNoFunc:
        case HeapType::kNoExtern:
          UNREACHABLE();
        default: {
          ModuleTypeIndex index = type.ref_index();
          if (builder->IsStructType(index)) {
            return GenerateStructNewInitExpr(zone, range, builder, index,
                                             structs, arrays, recursion_depth);
          } else if (builder->IsArrayType(index)) {
            return GenerateArrayInitExpr(zone, range, builder, index, structs,
                                         arrays, recursion_depth);
          } else {
            DCHECK(builder->IsSignature(index));
            for (int i = 0; i < builder->NumDeclaredFunctions(); ++i) {
              if (builder->GetFunction(i)->sig_index() == index) {
                return WasmInitExpr::RefFuncConst(
                    builder->NumImportedFunctions() + i);
              }
            }
            // There has to be at least one function per signature, otherwise
            // the init expression is unable to generate a non-nullable
            // reference with the correct type.
            UNREACHABLE();
          }
          UNREACHABLE();
        }
      }
    }
    case kVoid:
    case kTop:
    case kBottom:
      UNREACHABLE();
  }
}
References v8::internal::wasm::WasmInitExpr::AnyConvertExtern(), v8::internal::wasm::WasmInitExpr::Binop(), v8::internal::DCHECK(), v8::internal::wasm::WasmInitExpr::ExternConvertAny(), GenerateArrayInitExpr(), GenerateStructNewInitExpr(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), v8::internal::wasm::WasmModuleBuilder::GetFunction(), v8::internal::wasm::WasmModuleBuilder::GetGlobalType(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::getPseudoRandom(), v8::internal::wasm::WasmInitExpr::GlobalGet(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::wasm::WasmModuleBuilder::IsArrayType(), v8::internal::wasm::WasmModuleBuilder::IsMutableGlobal(), v8::internal::wasm::WasmModuleBuilder::IsSignature(), v8::internal::wasm::WasmModuleBuilder::IsStructType(), v8::internal::wasm::HeapType::kAny, v8::internal::wasm::HeapType::kArray, v8::internal::wasm::HeapType::kEq, v8::internal::wasm::HeapType::kExtern, v8::internal::kF32, v8::internal::kF64, v8::internal::wasm::HeapType::kFunc, v8::internal::kI16, v8::internal::wasm::HeapType::kI31, v8::internal::kI32, v8::internal::wasm::WasmInitExpr::kI32Add, v8::internal::wasm::WasmInitExpr::kI32Mul, v8::internal::wasm::WasmInitExpr::kI32Sub, v8::internal::kI64, v8::internal::wasm::WasmInitExpr::kI64Add, v8::internal::wasm::WasmInitExpr::kI64Mul, v8::internal::wasm::WasmInitExpr::kI64Sub, v8::internal::kI8, kMaxRecursionDepth, v8::internal::wasm::HeapType::kNoExtern, v8::internal::wasm::HeapType::kNoFunc, v8::internal::wasm::HeapType::kNone, v8::internal::kRef, v8::internal::kRefNull, v8::internal::kS128, v8::internal::kSimd128Size, v8::internal::wasm::HeapType::kStruct, v8::internal::wasm::kWasmAnyRef, v8::internal::wasm::kWasmArrayRef, v8::internal::wasm::kWasmExternRef, v8::internal::wasm::kWasmI31Ref, v8::internal::wasm::kWasmI32, v8::internal::wasm::kWasmI64, v8::internal::wasm::kWasmStructRef, v8::internal::wasm::WasmModuleBuilder::NumDeclaredFunctions(), v8::internal::wasm::WasmModuleBuilder::NumGlobals(), v8::internal::wasm::WasmModuleBuilder::NumImportedFunctions(), v8::internal::wasm::WasmInitExpr::RefFuncConst(), v8::internal::wasm::WasmInitExpr::RefI31(), v8::internal::wasm::ValueType::RefMaybeNull(), v8::internal::wasm::WasmInitExpr::RefNullConst(), v8::internal::wasm::WasmFunctionBuilder::sig_index(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::size(), v8::internal::tracing::type, and v8::internal::UNREACHABLE().
Referenced by GenerateArrayInitExpr(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::GenerateRandomGlobals(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::GenerateRandomTables(), GenerateStructNewInitExpr(), and v8::internal::wasm::fuzzing::GenerateWasmModuleForInitExpressions().
GeneratePassiveDataSegment()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GeneratePassiveDataSegment (DataRange * range, WasmModuleBuilder * builder)
Definition at line 309 of file random-module-generation.cc.
                                                                              {
  int length = range->get<uint8_t>() % 65;
  ZoneVector<uint8_t> data(length, builder->zone());
  for (int i = 0; i < length; ++i) {
    data[i] = range->getPseudoRandom<uint8_t>();
  }
  builder->AddPassiveDataSegment(data.data(),
                                 static_cast<uint32_t>(data.size()));
}
References v8::internal::wasm::WasmModuleBuilder::AddPassiveDataSegment(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::getPseudoRandom(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::length, and v8::internal::wasm::WasmModuleBuilder::zone().
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_init_data(), v8::internal::wasm::fuzzing::GenerateRandomWasmModule(), v8::internal::wasm::fuzzing::GenerateWasmModuleForRevec(), and v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::new_object().
GenerateRefTypeElementSegment()
uint32_t v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateRefTypeElementSegment (DataRange * range, WasmModuleBuilder * builder, ValueType element_type)
Definition at line 319 of file random-module-generation.cc.
                                                               {
  DCHECK(element_type.is_object_reference());
  DCHECK(element_type.has_index());
  WasmModuleBuilder::WasmElemSegment segment(
      builder->zone(), element_type, false,
      WasmInitExpr::RefNullConst(element_type.heap_type()));
  size_t element_count = range->get<uint8_t>() % 11;
  for (size_t i = 0; i < element_count; ++i) {
    segment.entries.emplace_back(
        WasmModuleBuilder::WasmElemSegment::Entry::kRefNullEntry,
        element_type.ref_index().index);
  }
  return builder->AddElementSegment(std::move(segment));
}
References v8::internal::wasm::WasmModuleBuilder::AddElementSegment(), v8::internal::DCHECK(), v8::internal::wasm::WasmModuleBuilder::WasmElemSegment::entries, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), v8::internal::wasm::ValueTypeBase::has_index(), v8::internal::wasm::ValueType::heap_type(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::TypeIndex::index, v8::internal::wasm::ValueTypeBase::is_object_reference(), v8::internal::wasm::WasmModuleBuilder::WasmElemSegment::Entry::kRefNullEntry, v8::internal::wasm::ValueType::ref_index(), v8::internal::wasm::WasmInitExpr::RefNullConst(), and v8::internal::wasm::WasmModuleBuilder::zone().
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_init_elem(), and v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::new_object().
GenerateStructNewInitExpr()
WasmInitExpr v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateStructNewInitExpr (Zone * zone, DataRange & range, WasmModuleBuilder * builder, ModuleTypeIndex index, const std::vector< ModuleTypeIndex > & structs, const std::vector< ModuleTypeIndex > & arrays, uint32_t recursion_depth)
Definition at line 4097 of file random-module-generation.cc.
                                                                        {
  const StructType* struct_type = builder->GetStructType(index);
  bool use_new_default =
      std::all_of(struct_type->fields().begin(), struct_type->fields().end(),
                  [](ValueType type) { return type.is_defaultable(); }) &&
      range.get<bool>();
  if (use_new_default) {
    return WasmInitExpr::StructNewDefault(index);
  } else {
    ZoneVector<WasmInitExpr>* elements =
        zone->New<ZoneVector<WasmInitExpr>>(zone);
    int field_count = struct_type->field_count();
    for (int field_index = 0; field_index < field_count; field_index++) {
      elements->push_back(GenerateInitExpr(
          zone, range, builder, struct_type->field(field_index), structs,
          arrays, recursion_depth + 1));
    }
    return WasmInitExpr::StructNew(index, elements);
  }
}
References v8::base::all_of(), v8::internal::wasm::StructType::field(), v8::internal::wasm::StructTypeBase::field_count(), v8::internal::wasm::StructType::fields(), GenerateInitExpr(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), v8::internal::wasm::WasmModuleBuilder::GetStructType(), v8::internal::index, v8::internal::Zone::New(), v8::internal::ZoneVector< T >::push_back(), v8::internal::wasm::WasmInitExpr::StructNew(), v8::internal::wasm::WasmInitExpr::StructNewDefault(), and v8::internal::tracing::type.
Referenced by GenerateInitExpr().
GenerateTypes()
std::vector<ValueType> v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateTypes (WasmModuleGenerationOptions options, DataRange * data, uint32_t num_ref_types)
Definition at line 336 of file random-module-generation.cc.
                                                                              {
  std::vector<ValueType> types;
  int num_params = int{data->get<uint8_t>()} % (kMaxParameters + 1);
  types.reserve(num_params);
  for (int i = 0; i < num_params; ++i) {
    types.push_back(GetValueType(options, data, num_ref_types));
  }
  return types;
}
References v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), GetValueType(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, and kMaxParameters.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::Generate(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GenerateTypes(), v8::internal::wasm::fuzzing::GenerateWasmModuleForDeopt(), and v8::internal::wasm::fuzzing::GenerateWasmModuleForRevec().
GeneratorAlternativesPerOption()
template<size_t kNumMVP, size_t kAdditionalSimd, size_t kAdditionalWasmGC>
v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GeneratorAlternativesPerOption (std::array< GenerateFn, kNumMVP > , std::array< GenerateFn, kAdditionalSimd > , std::array< GenerateFn, kAdditionalWasmGC >) -> GeneratorAlternativesPerOption< kNumMVP, kAdditionalSimd, kAdditionalWasmGC >
GetValueType()
ValueType v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GetValueType (WasmModuleGenerationOptions options, DataRange * data, uint32_t num_types)
Definition at line 302 of file random-module-generation.cc.
                                           {
  return GetValueTypeHelper(options, data, num_types, num_types,
                            kIncludeNumericTypes, kExcludePackedTypes,
                            kIncludeAllGenerics);
}
References GetValueTypeHelper(), kExcludePackedTypes, kIncludeAllGenerics, and kIncludeNumericTypes.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::BodyGen(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::drop(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::GenerateRandomGlobals(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::GenerateSig(), GenerateTypes(), and v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::DebugFieldType::GetTypeString().
GetValueTypeHelper()
ValueType v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GetValueTypeHelper (WasmModuleGenerationOptions options, DataRange * data, uint32_t num_nullable_types, uint32_t num_non_nullable_types, IncludeNumericTypes include_numeric_types, IncludePackedTypes include_packed_types, IncludeAllGenerics include_all_generics, IncludeS128 include_s128 = kIncludeS128)
Definition at line 224 of file random-module-generation.cc.
                                                                      {
  // Create and fill a vector of potential types to choose from.
  base::SmallVector<ValueType, 32> types;
  // Numeric non-wasmGC types.
  if (include_numeric_types) {
    // Many "general-purpose" instructions return i32, so give that a higher
    // probability (such as 3x).
    types.insert(types.end(),
                 {kWasmI32, kWasmI32, kWasmI32, kWasmI64, kWasmF32, kWasmF64});
    // SIMD type.
    if (options.generate_simd() && include_s128) {
      types.push_back(kWasmS128);
    }
  }
  // The MVP types: apart from numeric types, contains only the non-nullable
  // funcRef. We don't add externRef, because for externRef globals we generate
  // initialiser expressions where we need wasmGC types. Also, externRef is not
  // really useful for the MVP fuzzer, as there is nothing that we could
  // generate.
  types.push_back(kWasmFuncRef);
  // WasmGC types (including user-defined types).
  // Decide if the return type will be nullable or not.
  const bool nullable = options.generate_wasm_gc() ? data->get<bool>() : false;
  if (options.generate_wasm_gc()) {
    types.push_back(kWasmI31Ref);
    if (include_numeric_types && include_packed_types) {
      types.insert(types.end(), {kWasmI8, kWasmI16});
    }
    if (nullable) {
      types.insert(types.end(),
                   {kWasmNullRef, kWasmNullExternRef, kWasmNullFuncRef});
    }
    if (nullable || include_all_generics) {
      types.insert(types.end(), {kWasmStructRef, kWasmArrayRef, kWasmAnyRef,
                                 kWasmEqRef, kWasmExternRef});
    }
  }
  // The last index of user-defined types allowed is different based on the
  // nullability of the output. User-defined types are function signatures or
  // structs and arrays (in case of wasmGC).
  const uint32_t num_user_defined_types =
      nullable ? num_nullable_types : num_non_nullable_types;
  // Conceptually, user-defined types are added to the end of the list. Pick a
  // random one among them.
  uint32_t chosen_id =
      data->get<uint8_t>() % (types.size() + num_user_defined_types);
  Nullability nullability = nullable ? kNullable : kNonNullable;
  if (chosen_id >= types.size()) {
    // Return user-defined type.
    return ValueType::RefMaybeNull(
        ModuleTypeIndex{chosen_id - static_cast<uint32_t>(types.size())},
        nullability, kNotShared, RefTypeKind::kOther /* unknown */);
  }
  // If returning a reference type, fix its nullability according to {nullable}.
  if (types[chosen_id].is_reference()) {
    return ValueType::RefMaybeNull(types[chosen_id].heap_type(), nullability);
  }
  // Otherwise, just return the picked type.
  return types[chosen_id];
}
References v8::base::SmallVector< T, kSize, Allocator >::end(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), v8::base::SmallVector< T, kSize, Allocator >::insert(), v8::internal::wasm::is_reference(), v8::internal::wasm::kNonNullable, v8::internal::kNotShared, v8::internal::wasm::kNullable, v8::internal::wasm::kOther, v8::internal::wasm::kWasmAnyRef, v8::internal::wasm::kWasmArrayRef, v8::internal::wasm::kWasmEqRef, v8::internal::wasm::kWasmExternRef, v8::internal::wasm::kWasmFuncRef, v8::internal::wasm::kWasmI16, v8::internal::wasm::kWasmI31Ref, v8::internal::wasm::kWasmI8, v8::internal::wasm::kWasmNullExternRef, v8::internal::wasm::kWasmNullFuncRef, v8::internal::wasm::kWasmNullRef, v8::internal::wasm::kWasmS128, v8::internal::wasm::kWasmStructRef, v8::base::SmallVector< T, kSize, Allocator >::push_back(), v8::internal::wasm::ValueType::RefMaybeNull(), and v8::base::SmallVector< T, kSize, Allocator >::size().
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::GenerateRandomArrays(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::GenerateRandomStructs(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::GenerateRandomTables(), v8::internal::wasm::fuzzing::GenerateWasmModuleForInitExpressions(), and GetValueType().
HasSameReturns()
bool v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::HasSameReturns (const FunctionSig * a, const FunctionSig * b)
Definition at line 4659 of file random-module-generation.cc.
                                                                {
  if (a->return_count() != b->return_count()) return false;
  for (size_t i = 0; i < a->return_count(); ++i) {
    if (a->GetReturn(i) != b->GetReturn(i)) return false;
  }
  return true;
}
References v8::internal::Signature< T >::GetReturn(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::Signature< T >::return_count().
Referenced by EmitCallAndReturnValues(), and EmitDeoptAndReturnValues().
MaxNumOfFunctions()
int v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::MaxNumOfFunctions ()
Definition at line 50 of file random-module-generation.cc.
                        {
  return std::min(static_cast<int>(v8_flags.max_wasm_functions.value()), 4);
}
References v8::internal::v8_flags.
Referenced by v8::internal::wasm::fuzzing::GenerateRandomWasmModule(), and v8::internal::wasm::fuzzing::GenerateWasmModuleForRevec().
MaxTableSize()
int v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::MaxTableSize ()
Definition at line 46 of file random-module-generation.cc.
                   {
  return std::min(static_cast<int>(v8_flags.wasm_max_table_size.value()), 32);
}
References v8::internal::v8_flags.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::GenerateRandomTables().
Variable Documentation
kMaxArrays
constexpr int v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kMaxArrays = 3 [constexpr]
Definition at line 31 of file random-module-generation.cc.
Referenced by v8::internal::wasm::fuzzing::GenerateRandomWasmModule(), v8::internal::wasm::fuzzing::GenerateWasmModuleForDeopt(), and v8::internal::wasm::fuzzing::GenerateWasmModuleForInitExpressions().
kMaxArraySize
constexpr int v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kMaxArraySize = 20 [constexpr]
Definition at line 41 of file random-module-generation.cc.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::new_object().
kMaxCatchCases
constexpr int v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kMaxCatchCases = 6 [constexpr]
Definition at line 44 of file random-module-generation.cc.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::try_table_block_helper().
kMaxExceptions
constexpr int v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kMaxExceptions = 4 [constexpr]
Definition at line 38 of file random-module-generation.cc.
Referenced by v8::internal::wasm::fuzzing::GenerateRandomWasmModule(), and v8::internal::wasm::fuzzing::GenerateWasmModuleForRevec().
kMaxGlobals
constexpr int v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kMaxGlobals = 64 [constexpr]
Definition at line 34 of file random-module-generation.cc.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::GenerateRandomGlobals(), and v8::internal::wasm::fuzzing::GenerateWasmModuleForInitExpressions().
kMaxLocals
constexpr uint32_t v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kMaxLocals = 32 [constexpr]
Definition at line 35 of file random-module-generation.cc.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::BodyGen().
kMaxMemories
constexpr int v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kMaxMemories = 4 [constexpr]
Definition at line 40 of file random-module-generation.cc.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::GenerateRandomMemories().
kMaxParameters
constexpr int v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kMaxParameters = 15 [constexpr]
Definition at line 36 of file random-module-generation.cc.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::GenerateSig(), and GenerateTypes().
kMaxPassiveDataSegments
constexpr int v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kMaxPassiveDataSegments = 2 [constexpr]
Definition at line 42 of file random-module-generation.cc.
Referenced by v8::internal::wasm::fuzzing::GenerateRandomWasmModule(), and v8::internal::wasm::fuzzing::GenerateWasmModuleForRevec().
kMaxRecursionDepth
constexpr uint32_t v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kMaxRecursionDepth = 64 [constexpr]
Definition at line 43 of file random-module-generation.cc.
Referenced by v8::internal::Serializer::RecursionScope::ExceedsMaximum(), v8::internal::Serializer::RecursionScope::ExceedsMaximumBy(), GenerateInitExpr(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GeneratorRecursionScope::GeneratorRecursionScope(), and v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::recursion_limit_reached().
kMaxReturns
constexpr int v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kMaxReturns = 15 [constexpr]
Definition at line 37 of file random-module-generation.cc.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::GenerateSig().
kMaxStructFields
constexpr int v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kMaxStructFields = 4 [constexpr]
Definition at line 33 of file random-module-generation.cc.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::GenerateRandomStructs(), and v8::internal::wasm::fuzzing::GenerateWasmModuleForInitExpressions().
kMaxStructs
constexpr int v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kMaxStructs = 4 [constexpr]
Definition at line 32 of file random-module-generation.cc.
Referenced by v8::internal::wasm::fuzzing::GenerateRandomWasmModule(), v8::internal::wasm::fuzzing::GenerateWasmModuleForDeopt(), and v8::internal::wasm::fuzzing::GenerateWasmModuleForInitExpressions().
kMaxTables
constexpr int v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kMaxTables = 4 [constexpr]
Definition at line 39 of file random-module-generation.cc.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::GenerateRandomTables().