v8::internal::compiler::anonymous_namespace{register-allocator-verifier.cc} Namespace Reference
Functions
size_t OperandCount (const Instruction *instr)
void VerifyEmptyGaps (const Instruction *instr)
void VerifyAllocatedGaps (const Instruction *instr, const char *caller_info)
int GetValue (const ImmediateOperand *imm)
Function Documentation
GetValue()
int v8::internal::compiler::anonymous_namespace{register-allocator-verifier.cc}::GetValue (const ImmediateOperand * imm)
Definition at line 49 of file register-allocator-verifier.cc.
                                          {
  switch (imm->type()) {
    case ImmediateOperand::INLINE_INT32:
      return imm->inline_int32_value();
    case ImmediateOperand::INLINE_INT64:
      return static_cast<int>(imm->inline_int64_value());
    case ImmediateOperand::INDEXED_RPO:
    case ImmediateOperand::INDEXED_IMM:
      return imm->indexed_value();
  }
}
References v8::internal::compiler::ImmediateOperand::INDEXED_IMM, v8::internal::compiler::ImmediateOperand::INDEXED_RPO, v8::internal::compiler::ImmediateOperand::indexed_value(), v8::internal::compiler::ImmediateOperand::INLINE_INT32, v8::internal::compiler::ImmediateOperand::inline_int32_value(), v8::internal::compiler::ImmediateOperand::INLINE_INT64, v8::internal::compiler::ImmediateOperand::inline_int64_value(), and v8::internal::compiler::ImmediateOperand::type().
Referenced by v8::internal::compiler::RegisterAllocatorVerifier::BuildConstraint(), v8::internal::compiler::RegisterAllocatorVerifier::CheckConstraint(), v8::internal::wasm::DebugInfoImpl::GetLocalValue(), v8::internal::wasm::DebugInfoImpl::GetStackValue(), v8::internal::compiler::DescriptorArrayRef::GetStrongValue(), and v8::internal::DateParser::DateStringTokenizer< Char >::Scan().
OperandCount()
size_t v8::internal::compiler::anonymous_namespace{register-allocator-verifier.cc}::OperandCount (const Instruction * instr)
Definition at line 19 of file register-allocator-verifier.cc.
                                              {
  return instr->InputCount() + instr->OutputCount() + instr->TempCount();
}
References v8::internal::compiler::Instruction::InputCount(), v8::internal::compiler::Instruction::OutputCount(), and v8::internal::compiler::Instruction::TempCount().
Referenced by v8::internal::compiler::RegisterAllocatorVerifier::RegisterAllocatorVerifier(), and v8::internal::compiler::RegisterAllocatorVerifier::VerifyAssignment().
VerifyAllocatedGaps()
void v8::internal::compiler::anonymous_namespace{register-allocator-verifier.cc}::VerifyAllocatedGaps (const Instruction * instr, const char * caller_info)
Definition at line 32 of file register-allocator-verifier.cc.
                                                                            {
  for (int i = Instruction::FIRST_GAP_POSITION;
       i <= Instruction::LAST_GAP_POSITION; i++) {
    Instruction::GapPosition inner_pos =
        static_cast<Instruction::GapPosition>(i);
    const ParallelMove* moves = instr->GetParallelMove(inner_pos);
    if (moves == nullptr) continue;
    for (const MoveOperands* move : *moves) {
      if (move->IsRedundant()) continue;
      CHECK_WITH_MSG(
          move->source().IsAllocated() || move->source().IsConstant(),
          caller_info);
      CHECK_WITH_MSG(move->destination().IsAllocated(), caller_info);
    }
  }
}
References CHECK_WITH_MSG, v8::internal::compiler::Instruction::FIRST_GAP_POSITION, v8::internal::compiler::Instruction::GetParallelMove(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::compiler::Instruction::LAST_GAP_POSITION.
Referenced by v8::internal::compiler::RegisterAllocatorVerifier::VerifyAssignment().
VerifyEmptyGaps()
void v8::internal::compiler::anonymous_namespace{register-allocator-verifier.cc}::VerifyEmptyGaps (const Instruction * instr)
Definition at line 23 of file register-allocator-verifier.cc.
                                               {
  for (int i = Instruction::FIRST_GAP_POSITION;
       i <= Instruction::LAST_GAP_POSITION; i++) {
    Instruction::GapPosition inner_pos =
        static_cast<Instruction::GapPosition>(i);
    CHECK_NULL(instr->GetParallelMove(inner_pos));
  }
}
References CHECK_NULL, v8::internal::compiler::Instruction::FIRST_GAP_POSITION, v8::internal::compiler::Instruction::GetParallelMove(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::compiler::Instruction::LAST_GAP_POSITION.
Referenced by v8::internal::compiler::RegisterAllocatorVerifier::RegisterAllocatorVerifier().