v8::bigint::anonymous_namespace{div-helpers.cc} Namespace Reference
Functions
void Copy (RWDigits Z, Digits X)
Function Documentation
Copy()
void v8::bigint::anonymous_namespace{div-helpers.cc}::Copy (RWDigits Z, Digits X)
Definition at line 14 of file div-helpers.cc.
                                {
  if (Z == X) return;
  int i = 0;
  for (; i < X.len(); i++) Z[i] = X[i];
  for (; i < Z.len(); i++) Z[i] = 0;
}
References v8::bigint::Digits::len(), and X().
Referenced by v8::Persistent< T, M >::Copy(), v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::CopyBetweenBackingStores(), v8::internal::WasmJs::InstallTypeReflection(), v8::bigint::LeftShift(), and v8::bigint::RightShift().