v8::bigint::anonymous_namespace{bitwise.cc} Namespace Reference
Functions
void TruncateToNBits (RWDigits Z, Digits X, int n)
void TruncateAndSubFromPowerOfTwo (RWDigits Z, Digits X, int n)
Function Documentation
TruncateAndSubFromPowerOfTwo()
void v8::bigint::anonymous_namespace{bitwise.cc}::TruncateAndSubFromPowerOfTwo (RWDigits Z, Digits X, int n)
Definition at line 242 of file bitwise.cc.
                                                               {
  int digits = DIV_CEIL(n, kDigitBits);
  int bits = n % kDigitBits;
  // Process all digits except the MSD. Take X's digits, then simulate leading
  // zeroes.
  int last = digits - 1;
  int have_x = std::min(last, X.len());
  digit_t borrow = 0;
  int i = 0;
  for (; i < have_x; i++) Z[i] = digit_sub2(0, X[i], borrow, &borrow);
  for (; i < last; i++) Z[i] = digit_sub(0, borrow, &borrow);
  // The MSD might contain extra bits that we don't want.
  digit_t msd = last < X.len() ? X[last] : 0;
  if (bits == 0) {
    Z[last] = digit_sub2(0, msd, borrow, &borrow);
  } else {
    int drop = kDigitBits - bits;
    msd = (msd << drop) >> drop;
    digit_t minuend_msd = static_cast<digit_t>(1) << bits;
    digit_t result_msd = digit_sub2(minuend_msd, msd, borrow, &borrow);
    DCHECK(borrow == 0); // result < 2^n.
    // If all subtracted bits were zero, we have to get rid of the
    // materialized minuend_msd again.
    Z[last] = result_msd & (minuend_msd - 1);
  }
}
References DCHECK, v8::bigint::digit_sub(), v8::bigint::digit_sub2(), DIV_CEIL, v8::bigint::kDigitBits, and X().
Referenced by v8::bigint::AsIntN(), and v8::bigint::AsUintN_Neg().
TruncateToNBits()
void v8::bigint::anonymous_namespace{bitwise.cc}::TruncateToNBits (RWDigits Z, Digits X, int n)
Definition at line 224 of file bitwise.cc.
                                                  {
  int digits = DIV_CEIL(n, kDigitBits);
  int bits = n % kDigitBits;
  // Copy all digits except the MSD.
  int last = digits - 1;
  for (int i = 0; i < last; i++) {
    Z[i] = X[i];
  }
  // The MSD might contain extra bits that we don't want.
  digit_t msd = X[last];
  if (bits != 0) {
    int drop = kDigitBits - bits;
    msd = (msd << drop) >> drop;
  }
  Z[last] = msd;
}
References DIV_CEIL, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::bigint::kDigitBits, and X().
Referenced by v8::bigint::AsIntN(), and v8::bigint::AsUintN_Pos().