v8::internal::wasm::anonymous_namespace{turboshaft-graph-interface.cc} Namespace Reference
Classes
class BranchHintingStresser
Enumerations
enum class BranchHintingMode { kNone
, kModuleProvided
, kStress
 }
Functions
ExternalArrayType GetExternalArrayType (DataViewOp op_type)
size_t GetTypeSize (DataViewOp op_type)
bool ReverseBytesSupported (size_t size_in_bytes)
Enumeration Type Documentation
BranchHintingMode
enum v8::internal::wasm::anonymous_namespace{turboshaft-graph-interface.cc}::BranchHintingMode [strong]
Enumerator
kNone
kModuleProvided
kStress
Definition at line 123 of file turboshaft-graph-interface.cc.
                             {
  kNone,
  kModuleProvided,
  kStress,
};
Function Documentation
GetExternalArrayType()
ExternalArrayType v8::internal::wasm::anonymous_namespace{turboshaft-graph-interface.cc}::GetExternalArrayType (DataViewOp op_type)
Definition at line 86 of file turboshaft-graph-interface.cc.
                                                           {
  switch (op_type) {
#define V(Name) \
  case DataViewOp::kGet##Name: \
  case DataViewOp::kSet##Name: \
    return kExternal##Name##Array;
    DATAVIEW_OP_LIST(V)
#undef V
    case DataViewOp::kByteLength:
      UNREACHABLE();
  }
}
References DATAVIEW_OP_LIST, kByteLength, and v8::internal::UNREACHABLE().
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::DataViewGetter(), v8::internal::wasm::TurboshaftGraphBuildingInterface::DataViewSetter(), and GetTypeSize().
GetTypeSize()
size_t v8::internal::wasm::anonymous_namespace{turboshaft-graph-interface.cc}::GetTypeSize (DataViewOp op_type)
Definition at line 99 of file turboshaft-graph-interface.cc.
                                       {
  ExternalArrayType array_type = GetExternalArrayType(op_type);
  switch (array_type) {
#define ELEMENTS_KIND_TO_ELEMENT_SIZE(Type, type, TYPE, ctype) \
  case kExternal##Type##Array: \
    return sizeof(ctype);
    TYPED_ARRAYS(ELEMENTS_KIND_TO_ELEMENT_SIZE)
#undef ELEMENTS_KIND_TO_ELEMENT_SIZE
  }
}
References ELEMENTS_KIND_TO_ELEMENT_SIZE, GetExternalArrayType(), and TYPED_ARRAYS.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::GetDataViewDataPtr().
ReverseBytesSupported()
bool v8::internal::wasm::anonymous_namespace{turboshaft-graph-interface.cc}::ReverseBytesSupported (size_t size_in_bytes)
Definition at line 111 of file turboshaft-graph-interface.cc.
                                                 {
  switch (size_in_bytes) {
    case 4:
    case 16:
      return true;
    case 8:
      return Is64();
    default:
      return false;
  }
}
References v8::internal::Is64().
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildChangeEndiannessLoad(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildChangeEndiannessStore().