v8_inspector Namespace Reference
Namespaces
 anonymous_namespace{custom-preview.cc}
 anonymous_namespace{injected-script.cc}
 anonymous_namespace{remote-object-id.cc}
 anonymous_namespace{search-util.cc}
 anonymous_namespace{string-16.cc}
 anonymous_namespace{string-util.cc}
 anonymous_namespace{v8-console-message.cc}
 anonymous_namespace{v8-console.cc}
 anonymous_namespace{v8-debugger-agent-impl.cc}
 anonymous_namespace{v8-debugger-script.cc}
 anonymous_namespace{v8-debugger.cc}
 anonymous_namespace{v8-deep-serializer.cc}
 anonymous_namespace{v8-heap-profiler-agent-impl.cc}
 anonymous_namespace{v8-inspector-session-impl.cc}
 anonymous_namespace{v8-profiler-agent-impl.cc}
 anonymous_namespace{v8-runtime-agent-impl.cc}
 anonymous_namespace{v8-stack-trace-impl.cc}
 anonymous_namespace{v8-string-conversions.cc}
 anonymous_namespace{value-mirror.cc}
 ConsoleAgentState
 DebuggerAgentState
 internal
 ProfilerAgentState
 protocol
 V8RuntimeAgentImplState
Classes
class EvaluateCallback
class InjectedScript
class PromiseHandlerTracker
class InspectedContext
class RemoteObjectIdBase
class RemoteObjectId
class RemoteCallFrameId
class String16
class String16Builder
class V8ConsoleAgentImpl
class V8ConsoleMessage
class V8ConsoleMessageStorage
class V8Console
class TaskInfo
Each JS task object created via console.createTask has a corresponding TaskInfo object on the C++ side (in a 1:1 relationship).
struct DisassemblyChunk
class DisassemblyCollectorImpl
class V8DebuggerAgentImpl
class V8DebuggerBarrier
class V8DebuggerScript
struct WrapSerializationOptions
struct WrapOptions
class V8Debugger
class V8DeepSerializer
class V8HeapProfilerAgentImpl
class V8InspectorImpl
class V8InspectorSessionImpl
class V8ProfilerAgentImpl
class V8Regex
class V8RuntimeAgentImpl
class V8SchemaAgentImpl
class V8SerializationDuplicateTracker
class StackFrame
class V8StackTraceImpl
class AsyncStackTrace
struct PrivatePropertyMirror
struct InternalPropertyMirror
struct PropertyMirror
class ValueMirror
class StringView
class StringBuffer
class V8ContextInfo
class V8DebuggerId
struct V8StackFrame
class V8StackTrace
class V8InspectorSession
struct DeepSerializedValue
struct DeepSerializationResult
class V8InspectorClient
struct V8StackTraceId
class V8Inspector
Typedefs
using UChar = char16_t
using TerminateExecutionCallback = protocol::Runtime::Backend::TerminateExecutionCallback
Enumerations
enum class V8InternalValueType {
kNone
, kEntry
, kScope
, kScopeList
,
kPrivateMethodList
, kPrivateMethod
 }
enum class V8MessageOrigin { kConsole
, kException
, kRevokedException
 }
enum class ConsoleAPIType {
kLog
, kDebug
, kInfo
, kError
,
kWarning
, kDir
, kDirXML
, kTable
,
kTrace
, kStartGroup
, kStartGroupCollapsed
, kEndGroup
,
kClear
, kAssert
, kTimeEnd
, kCount
 }
enum class WrapMode { kJson
, kIdOnly
, kPreview
, kDeep
 }
enum MultilineMode { MultilineDisabled
, MultilineEnabled
 }
Functions
int32_t computeCrc32 (const String16 &text)
void generateCustomPreview (v8::Isolate *isolate, int sessionId, const String16 &groupName, v8::Local< v8::Object > object, v8::MaybeLocal< v8::Value > maybeConfig, int maxDepth, std::unique_ptr< CustomPreview > *preview)
void generateCustomPreview (v8::Isolate *isolate, int sessionId, const String16 &groupName, v8::Local< v8::Object > object, v8::MaybeLocal< v8::Value > config, int maxDepth, std::unique_ptr< protocol::Runtime::CustomPreview > *preview)
std::vector< std::unique_ptr< protocol::Debugger::SearchMatch > > searchInTextByLinesImpl (V8InspectorSession *session, const String16 &text, const String16 &query, const bool caseSensitive, const bool isRegex)
String16 findSourceURL (const String16 &content, bool multiline)
String16 findSourceMapURL (const String16 &content, bool multiline)
String16 findDebugId (const String16 &content, bool multiline)
String16 operator+ (const char *a, const String16 &b)
v8::Local< v8::String > toV8String (v8::Isolate *isolate, const String16 &string)
v8::Local< v8::String > toV8StringInternalized (v8::Isolate *isolate, const String16 &string)
v8::Local< v8::String > toV8StringInternalized (v8::Isolate *isolate, const char *str)
v8::Local< v8::String > toV8String (v8::Isolate *isolate, const StringView &string)
String16 toProtocolString (v8::Isolate *isolate, v8::Local< v8::String > value)
String16 toProtocolStringWithTypeCheck (v8::Isolate *isolate, v8::Local< v8::Value > value)
String16 toString16 (const StringView &string)
StringView toStringView (const String16 &string)
bool stringViewStartsWith (const StringView &string, const char *prefix)
std::unique_ptr< StringBuffer > StringBufferFrom (String16 str)
std::unique_ptr< StringBuffer > StringBufferFrom (std::vector< uint8_t > str)
String16 stackTraceIdToString (uintptr_t id)
template<size_t N>
StringView toStringView (const char *str[N])
void SetMaxAsyncTaskStacksForTest (V8Inspector *inspector, int limit)
void DumpAsyncTaskStacksStateForTest (V8Inspector *inspector)
static void setFunctionBreakpoint (ConsoleHelper &helper, int sessionId, v8::Local< v8::Function > function, V8DebuggerAgentImpl::BreakpointSource source, v8::Local< v8::String > condition, bool enable)
static void inspectImpl (const v8::FunctionCallbackInfo< v8::Value > &info, v8::Local< v8::Value > value, int sessionId, InspectRequest request, V8InspectorImpl *inspector)
static bool isCommandLineAPIGetter (const String16 &name)
static String16 getScriptLanguage (const V8DebuggerScript &script)
std::string UTF16ToUTF8 (const UChar *stringStart, size_t length)
std::basic_string< UChar > UTF8ToUTF16 (const char *stringStart, size_t length)
v8::Maybe< bool > createDataProperty (v8::Local< v8::Context > context, v8::Local< v8::Object > object, v8::Local< v8::Name > key, v8::Local< v8::Value > value)
v8::Maybe< bool > createDataProperty (v8::Local< v8::Context > context, v8::Local< v8::Array > array, int index, v8::Local< v8::Value > value)
Response toProtocolValue (v8::Local< v8::Context > context, v8::Local< v8::Value > value, int maxDepth, std::unique_ptr< protocol::Value > *result)
Response arrayToProtocolValue (v8::Local< v8::Context > context, v8::Local< v8::Array > array, int maxDepth, std::unique_ptr< protocol::ListValue > *result)
Response objectToProtocolValue (v8::Local< v8::Context > context, v8::Local< v8::Object > object, int maxDepth, std::unique_ptr< protocol::DictionaryValue > *result)
std::unique_ptr< protocol::FundamentalValue > toProtocolValue (double doubleValue)
Response toProtocolValue (v8::Local< v8::Context > context, v8::Local< v8::Value > value, std::unique_ptr< protocol::Value > *result)
std::unique_ptr< ValueMirror > clientMirror (v8::Local< v8::Context > context, v8::Local< v8::Object > value, const String16 &subtype)
Variables
static uint32_t kCrcTable [256]
const int kMaxCustomPreviewDepth = 20
static const char kBacktraceObjectGroup [] = `backtrace`
static const char kDebuggerNotEnabled [] = `Debugger agent is not enabled`
static const char kDebuggerNotPaused []
static const size_t kBreakpointHintMaxLength = 128
static const intptr_t kBreakpointHintMaxSearchOffset = 80 * 10
static const size_t kMaxNumBreakpoints = 1000
static constexpr v8::base::TimeDelta kDefaultTimerDelay
static const int kMaxProtocolDepth = 1000
Typedef Documentation
TerminateExecutionCallback
using v8_inspector::TerminateExecutionCallback = typedef protocol::Runtime::Backend::TerminateExecutionCallback
Definition at line 48 of file v8-debugger.h.
UChar
using v8_inspector::UChar = typedef char16_t
Definition at line 22 of file string-16.h.
Enumeration Type Documentation
ConsoleAPIType
enum v8_inspector::ConsoleAPIType [strong]
Enumerator
kLog
kDebug
kInfo
kError
kWarning
kDir
kDirXML
kTable
kTrace
kStartGroup
kStartGroupCollapsed
kEndGroup
kClear
kAssert
kTimeEnd
kCount
Definition at line 29 of file v8-console-message.h.
                          {
  kLog,
  kDebug,
  kInfo,
  kError,
  kWarning,
  kDir,
  kDirXML,
  kTable,
  kTrace,
  kStartGroup,
  kStartGroupCollapsed,
  kEndGroup,
  kClear,
  kAssert,
  kTimeEnd,
  kCount
};
MultilineMode
enum v8_inspector::MultilineMode
Enumerator
MultilineDisabled
MultilineEnabled
Definition at line 20 of file v8-regex.h.
{ MultilineDisabled, MultilineEnabled };
V8InternalValueType
enum v8_inspector::V8InternalValueType [strong]
Enumerator
kNone
kEntry
kScope
kScopeList
kPrivateMethodList
kPrivateMethod
Definition at line 31 of file inspected-context.h.
                               {
  kNone,
  kEntry,
  kScope,
  kScopeList,
  kPrivateMethodList,
  kPrivateMethod
};
V8MessageOrigin
enum v8_inspector::V8MessageOrigin [strong]
Enumerator
kConsole
kException
kRevokedException
Definition at line 27 of file v8-console-message.h.
{ kConsole, kException, kRevokedException };
WrapMode
enum v8_inspector::WrapMode [strong]
Enumerator
kJson
kIdOnly
kPreview
kDeep
Definition at line 35 of file v8-debugger.h.
{ kJson, kIdOnly, kPreview, kDeep };
Function Documentation
arrayToProtocolValue()
protocol::Response v8_inspector::arrayToProtocolValue (v8::Local< v8::Context > context, v8::Local< v8::Array > array, int maxDepth, std::unique_ptr< protocol::ListValue > * result)
Definition at line 45 of file value-mirror.cc.
                                                                        {
  std::unique_ptr<protocol::ListValue> inspectorArray =
      protocol::ListValue::create();
  uint32_t length = array->Length();
  for (uint32_t i = 0; i < length; i++) {
    v8::Local<v8::Value> value;
    if (!array->Get(context, i).ToLocal(&value))
      return Response::InternalError();
    std::unique_ptr<protocol::Value> element;
    Response response = toProtocolValue(context, value, maxDepth - 1, &element);
    if (!response.IsSuccess()) return response;
    inspectorArray->pushValue(std::move(element));
  }
  *result = std::move(inspectorArray);
  return Response::Success();
}
References v8::Object::Get(), v8::Array::Length(), v8::internal::length, v8::base::internal::result, v8::MaybeLocal< T >::ToLocal(), toProtocolValue(), and v8::internal::value.
Referenced by toProtocolValue().
clientMirror()
std::unique_ptr<ValueMirror> v8_inspector::clientMirror (v8::Local< v8::Context > context, v8::Local< v8::Object > value, const String16 & subtype)
Definition at line 1785 of file value-mirror.cc.
                                                                   {
  auto descriptionForValueSubtype =
      clientFor(context)->descriptionForValueSubtype(context, value);
  if (descriptionForValueSubtype) {
    return std::make_unique<ObjectMirror>(
        value, subtype, toString16(descriptionForValueSubtype->string()));
  }
  if (subtype == "error") {
    return std::make_unique<ObjectMirror>(value,
                                          RemoteObject::SubtypeEnum::Error,
                                          descriptionForError(context, value));
  }
  if (subtype == "array" && value->IsObject()) {
    v8::Isolate* isolate = v8::Isolate::GetCurrent();
    v8::TryCatch tryCatch(isolate);
    v8::Local<v8::Value> lengthValue;
    if (value->Get(context, toV8String(isolate, "length"))
            .ToLocal(&lengthValue)) {
      if (lengthValue->IsInt32()) {
        return std::make_unique<ObjectMirror>(
            value, RemoteObject::SubtypeEnum::Array,
            descriptionForCollection(isolate, value,
                                     lengthValue.As<v8::Int32>()->Value()));
      }
    }
  }
  return std::make_unique<ObjectMirror>(
      value, descriptionForObject(v8::Isolate::GetCurrent(), value));
}
References v8::Local< T >::As(), v8_inspector::anonymous_namespace{value-mirror.cc}::clientFor(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForCollection(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForError(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForObject(), v8_inspector::V8InspectorClient::descriptionForValueSubtype(), v8::internal::torque::Error(), v8::Isolate::GetCurrent(), v8::Value::IsInt32(), toString16(), toV8String(), v8::Int32::Value(), and v8::internal::value.
Referenced by v8_inspector::ValueMirror::create().
computeCrc32()
int32_t v8_inspector::computeCrc32 (const String16 & text)
Definition at line 72 of file crc32.cc.
                                           {
  const uint8_t* bytes = reinterpret_cast<const uint8_t*>(text.characters16());
  size_t byteLength = sizeof(UChar) * text.length();
  uint32_t checksum = 0;
  for (size_t i = 0; i < byteLength; ++i) {
    uint32_t index = (checksum ^ bytes[i]) & 0xff;
    checksum = (checksum >> 8) ^ kCrcTable[index];
  }
  return v8::base::bit_cast<int32_t>(checksum);
}
References v8_inspector::String16::characters16(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, kCrcTable, and v8_inspector::String16::length().
Referenced by v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::adjustBreakpointLocation(), and v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::breakpointHint().
createDataProperty() [1/2]
v8::Maybe< bool > v8_inspector::createDataProperty (v8::Local< v8::Context > context, v8::Local< v8::Array > array, int index, v8::Local< v8::Value > value)
Definition at line 24 of file v8-value-utils.cc.
                                                           {
  v8::Isolate* isolate = v8::Isolate::GetCurrent();
  v8::TryCatch tryCatch(isolate);
  v8::Isolate::DisallowJavascriptExecutionScope throwJs(
      isolate, v8::Isolate::DisallowJavascriptExecutionScope::THROW_ON_FAILURE);
  return array->CreateDataProperty(context, index, value);
}
References v8::Object::CreateDataProperty(), v8::Isolate::GetCurrent(), v8::internal::index, v8::Isolate::DisallowJavascriptExecutionScope::THROW_ON_FAILURE, and v8::internal::value.
createDataProperty() [2/2]
v8::Maybe< bool > v8_inspector::createDataProperty (v8::Local< v8::Context > context, v8::Local< v8::Object > object, v8::Local< v8::Name > key, v8::Local< v8::Value > value)
Definition at line 13 of file v8-value-utils.cc.
                                                           {
  v8::Isolate* isolate = v8::Isolate::GetCurrent();
  v8::TryCatch tryCatch(isolate);
  v8::Isolate::DisallowJavascriptExecutionScope throwJs(
      isolate, v8::Isolate::DisallowJavascriptExecutionScope::THROW_ON_FAILURE);
  return object->CreateDataProperty(context, key, value);
}
References v8::Isolate::GetCurrent(), v8::internal::key, v8::Isolate::DisallowJavascriptExecutionScope::THROW_ON_FAILURE, and v8::internal::value.
Referenced by v8_inspector::V8Debugger::collectionsEntries(), v8_inspector::anonymous_namespace{v8-console.cc}::createBoundFunctionProperty(), v8_inspector::V8Debugger::getTargetScopes(), v8_inspector::V8Debugger::internalProperties(), v8_inspector::V8Debugger::privateMethods(), v8_inspector::V8Debugger::queryObjects(), and v8_inspector::V8Console::valuesCallback().
DumpAsyncTaskStacksStateForTest()
void v8_inspector::DumpAsyncTaskStacksStateForTest (V8Inspector * inspector)
Definition at line 18 of file test-interface.cc.
                                                             {
  static_cast<V8InspectorImpl*>(inspector)
      ->debugger()
      ->dumpAsyncTaskStacksStateForTest();
}
findDebugId()
String16 v8_inspector::findDebugId (const String16 & content, bool multiline)
Definition at line 168 of file search-util.cc.
                                                              {
  return findMagicComment(content, "debugId", multiline);
}
References v8_inspector::anonymous_namespace{search-util.cc}::findMagicComment().
Referenced by v8_inspector::V8DebuggerAgentImpl::didParseSource().
findSourceMapURL()
String16 v8_inspector::findSourceMapURL (const String16 & content, bool multiline)
Definition at line 164 of file search-util.cc.
                                                                   {
  return findMagicComment(content, "sourceMappingURL", multiline);
}
References v8_inspector::anonymous_namespace{search-util.cc}::findMagicComment().
Referenced by v8_inspector::V8DebuggerAgentImpl::didParseSource().
findSourceURL()
String16 v8_inspector::findSourceURL (const String16 & content, bool multiline)
Definition at line 160 of file search-util.cc.
                                                                {
  return findMagicComment(content, "sourceURL", multiline);
}
References v8_inspector::anonymous_namespace{search-util.cc}::findMagicComment().
Referenced by v8_inspector::V8DebuggerAgentImpl::didParseSource().
generateCustomPreview() [1/2]
void v8_inspector::generateCustomPreview (v8::Isolate * isolate, int sessionId, const String16 & groupName, v8::Local< v8::Object > object, v8::MaybeLocal< v8::Value > config, int maxDepth, std::unique_ptr< protocol::Runtime::CustomPreview > * preview)
generateCustomPreview() [2/2]
void v8_inspector::generateCustomPreview (v8::Isolate * isolate, int sessionId, const String16 & groupName, v8::Local< v8::Object > object, v8::MaybeLocal< v8::Value > maybeConfig, int maxDepth, std::unique_ptr< CustomPreview > * preview)
Definition at line 259 of file custom-preview.cc.
                                                                  {
  v8::Local<v8::Context> context;
  if (!object->GetCreationContext(isolate).ToLocal(&context)) {
    return;
  }
  v8::MicrotasksScope microtasksScope(context,
                                      v8::MicrotasksScope::kDoNotRunMicrotasks);
  v8::TryCatch tryCatch(isolate);
  v8::Local<v8::Value> configValue;
  if (!maybeConfig.ToLocal(&configValue)) configValue = v8::Undefined(isolate);
  v8::Local<v8::Object> global = context->Global();
  v8::Local<v8::Value> formattersValue;
  if (!global->Get(context, toV8String(isolate, "devtoolsFormatters"))
           .ToLocal(&formattersValue)) {
    reportError(context, tryCatch);
    return;
  }
  if (!formattersValue->IsArray()) return;
  v8::Local<v8::Array> formatters = formattersValue.As<v8::Array>();
  v8::Local<v8::String> headerLiteral = toV8String(isolate, "header");
  v8::Local<v8::String> hasBodyLiteral = toV8String(isolate, "hasBody");
  for (uint32_t i = 0; i < formatters->Length(); ++i) {
    v8::Local<v8::Value> formatterValue;
    if (!formatters->Get(context, i).ToLocal(&formatterValue)) {
      reportError(context, tryCatch);
      return;
    }
    if (!formatterValue->IsObject()) {
      reportError(context, tryCatch, "formatter should be an Object");
      return;
    }
    v8::Local<v8::Object> formatter = formatterValue.As<v8::Object>();
    v8::Local<v8::Value> headerValue;
    if (!formatter->Get(context, headerLiteral).ToLocal(&headerValue)) {
      reportError(context, tryCatch);
      return;
    }
    if (!headerValue->IsFunction()) {
      reportError(context, tryCatch, "header should be a Function");
      return;
    }
    v8::Local<v8::Function> headerFunction = headerValue.As<v8::Function>();
    v8::Local<v8::Value> formattedValue;
    v8::Local<v8::Value> args[] = {object, configValue};
    if (!headerFunction->Call(context, formatter, 2, args)
             .ToLocal(&formattedValue)) {
      reportError(context, tryCatch);
      return;
    }
    if (!formattedValue->IsArray()) continue;
    v8::Local<v8::Array> jsonML = formattedValue.As<v8::Array>();
    v8::Local<v8::Value> hasBodyFunctionValue;
    if (!formatter->Get(context, hasBodyLiteral)
             .ToLocal(&hasBodyFunctionValue)) {
      reportError(context, tryCatch);
      return;
    }
    if (!hasBodyFunctionValue->IsFunction()) continue;
    v8::Local<v8::Function> hasBodyFunction =
        hasBodyFunctionValue.As<v8::Function>();
    v8::Local<v8::Value> hasBodyValue;
    if (!hasBodyFunction->Call(context, formatter, 2, args)
             .ToLocal(&hasBodyValue)) {
      reportError(context, tryCatch);
      return;
    }
    bool hasBody = hasBodyValue->ToBoolean(isolate)->Value();
    if (jsonML->Length() && !substituteObjectTags(sessionId, groupName, context,
                                                  jsonML, maxDepth)) {
      return;
    }
    v8::Local<v8::String> header;
    if (!v8::JSON::Stringify(context, jsonML).ToLocal(&header)) {
      reportError(context, tryCatch);
      return;
    }
    v8::Local<v8::Function> bodyFunction;
    if (hasBody) {
      v8::Local<v8::Object> bodyConfig = v8::Object::New(isolate);
      if (bodyConfig
              ->CreateDataProperty(context, toV8String(isolate, "sessionId"),
                                   v8::Integer::New(isolate, sessionId))
              .IsNothing()) {
        reportError(context, tryCatch);
        return;
      }
      if (bodyConfig
              ->CreateDataProperty(context, toV8String(isolate, "formatter"),
                                   formatter)
              .IsNothing()) {
        reportError(context, tryCatch);
        return;
      }
      if (bodyConfig
              ->CreateDataProperty(context, toV8String(isolate, "groupName"),
                                   toV8String(isolate, groupName))
              .IsNothing()) {
        reportError(context, tryCatch);
        return;
      }
      if (bodyConfig
              ->CreateDataProperty(context, toV8String(isolate, "config"),
                                   configValue)
              .IsNothing()) {
        reportError(context, tryCatch);
        return;
      }
      if (bodyConfig
              ->CreateDataProperty(context, toV8String(isolate, "object"),
                                   object)
              .IsNothing()) {
        reportError(context, tryCatch);
        return;
      }
      if (!v8::Function::New(context, bodyCallback, bodyConfig)
               .ToLocal(&bodyFunction)) {
        reportError(context, tryCatch);
        return;
      }
    }
    *preview = CustomPreview::create()
                   .setHeader(toProtocolString(isolate, header))
                   .build();
    if (!bodyFunction.IsEmpty()) {
      InjectedScript* injectedScript = getInjectedScript(context, sessionId);
      if (!injectedScript) {
        reportError(context, tryCatch, "cannot find context with specified id");
        return;
      }
      (*preview)->setBodyGetterId(
          injectedScript->bindObject(bodyFunction, groupName));
    }
    return;
  }
}
References v8::base::args, v8::Local< T >::As(), v8_inspector::InjectedScript::bindObject(), v8_inspector::anonymous_namespace{custom-preview.cc}::bodyCallback(), v8::internal::anonymous_namespace{property-descriptor.cc}::CreateDataProperty(), v8::Object::Get(), v8::Object::GetCreationContext(), v8_inspector::anonymous_namespace{custom-preview.cc}::getInjectedScript(), v8::Context::Global(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::Value::IsArray(), v8::api_internal::IndirectHandleBase::IsEmpty(), v8::Value::IsObject(), v8::MicrotasksScope::kDoNotRunMicrotasks, v8::Array::Length(), v8::Object::New(), v8::Integer::New(), v8::Function::New(), v8_inspector::anonymous_namespace{custom-preview.cc}::reportError(), v8::JSON::Stringify(), v8_inspector::anonymous_namespace{custom-preview.cc}::substituteObjectTags(), v8::MaybeLocal< T >::ToLocal(), toProtocolString(), toV8String(), and v8::Undefined().
Referenced by v8_inspector::InjectedScript::wrapObjectMirror().
getScriptLanguage()
static String16 v8_inspector::getScriptLanguage (const V8DebuggerScript & script) [static]
Definition at line 1883 of file v8-debugger-agent-impl.cc.
                                                                  {
  switch (script.getLanguage()) {
    case V8DebuggerScript::Language::WebAssembly:
      return protocol::Debugger::ScriptLanguageEnum::WebAssembly;
    case V8DebuggerScript::Language::JavaScript:
      return protocol::Debugger::ScriptLanguageEnum::JavaScript;
  }
}
References v8_inspector::V8DebuggerScript::JavaScript, v8::internal::script, and v8_inspector::V8DebuggerScript::WebAssembly.
Referenced by v8_inspector::V8DebuggerAgentImpl::didParseSource().
inspectImpl()
static void v8_inspector::inspectImpl (const v8::FunctionCallbackInfo< v8::Value > & info, v8::Local< v8::Value > value, int sessionId, InspectRequest request, V8InspectorImpl * inspector) [static]
Definition at line 743 of file v8-console.cc.
                                                                            {
  if (request == kRegular) info.GetReturnValue().Set(value);
  v8::debug::ConsoleCallArguments args(info);
  ConsoleHelper helper(args, v8::debug::ConsoleContext(), inspector);
  InjectedScript* injectedScript = helper.injectedScript(sessionId);
  if (!injectedScript) return;
  std::unique_ptr<protocol::Runtime::RemoteObject> wrappedObject;
  protocol::Response response = injectedScript->wrapObject(
      value, "", WrapOptions({WrapMode::kIdOnly}), &wrappedObject);
  if (!response.IsSuccess()) return;
  std::unique_ptr<protocol::DictionaryValue> hints =
      protocol::DictionaryValue::create();
  if (request == kCopyToClipboard) {
    hints->setBoolean("copyToClipboard", true);
  } else if (request == kQueryObjects) {
    hints->setBoolean("queryObjects", true);
  }
  if (V8InspectorSessionImpl* session = helper.session(sessionId)) {
    session->runtimeAgent()->inspect(std::move(wrappedObject), std::move(hints),
                                     helper.contextId());
  }
}
References v8::base::args, v8::FunctionCallbackInfo< T >::GetReturnValue(), v8_inspector::anonymous_namespace{v8-console.cc}::kCopyToClipboard, kIdOnly, v8_inspector::anonymous_namespace{v8-console.cc}::kQueryObjects, v8::internal::value, and v8_inspector::InjectedScript::wrapObject().
Referenced by v8_inspector::V8Console::copyCallback(), v8_inspector::V8Console::inspectCallback(), and v8_inspector::V8Console::queryObjectsCallback().
isCommandLineAPIGetter()
static bool v8_inspector::isCommandLineAPIGetter (const String16 & name) [static]
Definition at line 928 of file v8-console.cc.
                                                         {
  if (name.length() != 2) return false;
  // $0 ... $4, $_
  return name[0] == '$' &&
         ((name[1] >= '0' && name[1] <= '4') || name[1] == '_');
}
References name.
Referenced by v8_inspector::V8Console::CommandLineAPIScope::accessorGetterCallback().
objectToProtocolValue()
protocol::Response v8_inspector::objectToProtocolValue (v8::Local< v8::Context > context, v8::Local< v8::Object > object, int maxDepth, std::unique_ptr< protocol::DictionaryValue > * result)
Definition at line 64 of file value-mirror.cc.
                                                    {
  std::unique_ptr<protocol::DictionaryValue> jsonObject =
      protocol::DictionaryValue::create();
  v8::Local<v8::Array> propertyNames;
  if (!object->GetOwnPropertyNames(context).ToLocal(&propertyNames))
    return Response::InternalError();
  uint32_t length = propertyNames->Length();
  for (uint32_t i = 0; i < length; i++) {
    v8::Local<v8::Value> name;
    if (!propertyNames->Get(context, i).ToLocal(&name))
      return Response::InternalError();
    if (name->IsString()) {
      v8::Maybe<bool> hasRealNamedProperty =
          object->HasRealNamedProperty(context, name.As<v8::String>());
      // Don't access properties with interceptors.
      if (hasRealNamedProperty.IsNothing() || !hasRealNamedProperty.FromJust())
        continue;
    }
    v8::Local<v8::String> propertyName;
    if (!name->ToString(context).ToLocal(&propertyName)) continue;
    v8::Local<v8::Value> property;
    if (!object->Get(context, name).ToLocal(&property))
      return Response::InternalError();
    if (property->IsUndefined()) continue;
    std::unique_ptr<protocol::Value> propertyValue;
    Response response =
        toProtocolValue(context, property, maxDepth - 1, &propertyValue);
    if (!response.IsSuccess()) return response;
    jsonObject->setValue(
        toProtocolString(v8::Isolate::GetCurrent(), propertyName),
        std::move(propertyValue));
  }
  *result = std::move(jsonObject);
  return Response::Success();
}
References v8::Maybe< T >::FromJust(), v8::Object::Get(), v8::Isolate::GetCurrent(), v8::Object::GetOwnPropertyNames(), v8::Maybe< T >::IsNothing(), v8::Value::IsUndefined(), v8::Array::Length(), v8::internal::length, name, v8::base::internal::result, v8::MaybeLocal< T >::ToLocal(), toProtocolString(), and toProtocolValue().
Referenced by v8_inspector::V8InspectorImpl::getAssociatedExceptionDataForProtocol(), and toProtocolValue().
operator+()
String16 v8_inspector::operator+ (const char * a, const String16 & b) [inline]
Definition at line 126 of file string-16.h.
                                                            {
  return String16(a) + b;
}
searchInTextByLinesImpl()
std::vector< std::unique_ptr< protocol::Debugger::SearchMatch > > v8_inspector::searchInTextByLinesImpl (V8InspectorSession * session, const String16 & text, const String16 & query, const bool caseSensitive, const bool isRegex)
Definition at line 144 of file search-util.cc.
                                            {
  std::unique_ptr<V8Regex> regex = createSearchRegex(
      static_cast<V8InspectorSessionImpl*>(session)->inspector(), query,
      caseSensitive, isRegex);
  std::vector<std::pair<int, String16>> matches =
      scriptRegexpMatchesByLines(*regex, text);
  std::vector<std::unique_ptr<protocol::Debugger::SearchMatch>> result;
  result.reserve(matches.size());
  for (const auto& match : matches)
    result.push_back(buildObjectForSearchMatch(match.first, match.second));
  return result;
}
References v8_inspector::anonymous_namespace{search-util.cc}::buildObjectForSearchMatch(), v8_inspector::anonymous_namespace{search-util.cc}::createSearchRegex(), v8::base::internal::result, and v8_inspector::anonymous_namespace{search-util.cc}::scriptRegexpMatchesByLines().
Referenced by v8_inspector::V8DebuggerAgentImpl::searchInContent(), and v8_inspector::V8InspectorSessionImpl::searchInTextByLines().
setFunctionBreakpoint()
static void v8_inspector::setFunctionBreakpoint (ConsoleHelper & helper, int sessionId, v8::Local< v8::Function > function, V8DebuggerAgentImpl::BreakpointSource source, v8::Local< v8::String > condition, bool enable) [static]
Definition at line 655 of file v8-console.cc.
                                               {
  V8InspectorSessionImpl* session = helper.session(sessionId);
  if (session == nullptr) return;
  if (!session->debuggerAgent()->enabled()) return;
  if (enable) {
    session->debuggerAgent()->setBreakpointFor(function, condition, source);
  } else {
    session->debuggerAgent()->removeBreakpointFor(function, source);
  }
}
References v8_inspector::V8InspectorSessionImpl::debuggerAgent(), v8_inspector::V8DebuggerAgentImpl::enabled(), v8_inspector::V8DebuggerAgentImpl::removeBreakpointFor(), and v8_inspector::V8DebuggerAgentImpl::setBreakpointFor().
Referenced by v8_inspector::V8Console::debugFunctionCallback(), v8_inspector::V8Console::monitorFunctionCallback(), v8_inspector::V8Console::undebugFunctionCallback(), and v8_inspector::V8Console::unmonitorFunctionCallback().
SetMaxAsyncTaskStacksForTest()
void v8_inspector::SetMaxAsyncTaskStacksForTest (V8Inspector * inspector, int limit)
Definition at line 12 of file test-interface.cc.
                                                                     {
  static_cast<V8InspectorImpl*>(inspector)
      ->debugger()
      ->setMaxAsyncTaskStacksForTest(limit);
}
stackTraceIdToString()
String16 v8_inspector::stackTraceIdToString (uintptr_t id)
Definition at line 240 of file string-util.cc.
                                            {
  String16Builder builder;
  builder.appendNumber(static_cast<size_t>(id));
  return builder.toString();
}
References v8_inspector::String16Builder::appendNumber(), and v8_inspector::String16Builder::toString().
Referenced by v8_inspector::anonymous_namespace{v8-stack-trace-impl.cc}::buildInspectorObjectCommon(), and v8_inspector::V8DebuggerAgentImpl::currentExternalStackTrace().
StringBufferFrom() [1/2]
std::unique_ptr< StringBuffer > v8_inspector::StringBufferFrom (std::vector< uint8_t > str)
Definition at line 235 of file string-util.cc.
                                                                     {
  if (str.empty()) return std::make_unique<EmptyStringBuffer>();
  return std::make_unique<StringBuffer8>(std::move(str));
}
StringBufferFrom() [2/2]
std::unique_ptr< StringBuffer > v8_inspector::StringBufferFrom (String16 str)
Definition at line 230 of file string-util.cc.
                                                           {
  if (str.isEmpty()) return std::make_unique<EmptyStringBuffer>();
  return std::make_unique<StringBuffer16>(std::move(str));
}
References v8_inspector::String16::isEmpty().
Referenced by v8_inspector::V8InspectorSessionImpl::serializeForFrontend(), v8_inspector::V8StackTraceId::ToString(), v8_inspector::V8DebuggerId::toString(), v8_inspector::V8StackTraceImpl::toString(), and v8_inspector::V8InspectorSessionImpl::unwrapObject().
stringViewStartsWith()
bool v8_inspector::stringViewStartsWith (const StringView & string, const char * prefix)
Definition at line 170 of file string-util.cc.
                                                                        {
  if (!string.length()) return !(*prefix);
  if (string.is8Bit()) {
    for (size_t i = 0, j = 0; prefix[j] && i < string.length(); ++i, ++j) {
      if (string.characters8()[i] != prefix[j]) return false;
    }
  } else {
    for (size_t i = 0, j = 0; prefix[j] && i < string.length(); ++i, ++j) {
      if (string.characters16()[i] != prefix[j]) return false;
    }
  }
  return true;
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::length.
Referenced by v8_inspector::V8InspectorSession::canDispatchMethod().
toProtocolString()
String16 v8_inspector::toProtocolString (v8::Isolate * isolate, v8::Local< v8::String > value)
Definition at line 143 of file string-util.cc.
                                                                       {
  if (value.IsEmpty() || value->IsNullOrUndefined()) return String16();
  uint32_t length = value->Length();
  std::unique_ptr<UChar[]> buffer(new UChar[length]);
  value->WriteV2(isolate, 0, length, reinterpret_cast<uint16_t*>(buffer.get()));
  return String16(buffer.get(), length);
}
References v8::internal::length, and v8::internal::value.
Referenced by v8_inspector::anonymous_namespace{v8-console-message.cc}::V8ValueStringBuilder::append(), v8_inspector::V8RuntimeAgentImpl::bindingCallback(), v8_inspector::anonymous_namespace{custom-preview.cc}::bodyCallback(), v8_inspector::V8Debugger::BreakpointConditionEvaluated(), v8_inspector::anonymous_namespace{value-mirror.cc}::PrimitiveValueMirror::buildDeepSerializedValue(), v8_inspector::anonymous_namespace{value-mirror.cc}::BigIntMirror::buildDeepSerializedValue(), v8_inspector::V8DebuggerScript::buildId(), v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::buildInspectorObjectFor(), v8_inspector::anonymous_namespace{value-mirror.cc}::ObjectMirror::buildRemoteObject(), v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc}::buildSampingHeapProfileNode(), v8_inspector::InjectedScript::ProtocolPromiseHandler::catchCallback(), v8_inspector::anonymous_namespace{v8-console.cc}::consoleContextToString(), v8_inspector::V8Console::Count(), v8_inspector::V8Console::CountReset(), v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::coverageToProtocol(), v8_inspector::InjectedScript::createExceptionDetails(), v8_inspector::V8Console::createTask(), v8_inspector::V8DebuggerAgentImpl::currentCallFrames(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForBigInt(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForCollection(), v8_inspector::anonymous_namespace{v8-deep-serializer.cc}::DescriptionForDate(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForDate(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForError(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForFunction(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForObject(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForPrimitiveType(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForRegExp(), generateCustomPreview(), v8_inspector::V8RuntimeAgentImpl::getExceptionDetails(), v8_inspector::ValueMirror::getProperties(), v8_inspector::V8DebuggerScript::GetScriptName(), v8_inspector::V8DebuggerScript::GetScriptURL(), v8_inspector::V8RuntimeAgentImpl::globalLexicalScopeNames(), v8_inspector::V8DebuggerScript::Initialize(), objectToProtocolValue(), v8_inspector::V8Console::Profile(), v8_inspector::V8Console::ProfileEnd(), v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::resourceNameToUrl(), v8_inspector::anonymous_namespace{v8-deep-serializer.cc}::SerializeMap(), v8_inspector::anonymous_namespace{v8-deep-serializer.cc}::SerializeObjectValue(), v8_inspector::anonymous_namespace{v8-deep-serializer.cc}::SerializeRegexp(), v8_inspector::V8DebuggerAgentImpl::setScriptSource(), v8_inspector::V8Debugger::symbolize(), v8_inspector::V8Console::Time(), v8_inspector::V8Console::TimeEnd(), v8_inspector::V8Console::TimeLog(), toProtocolStringWithTypeCheck(), toProtocolValue(), v8_inspector::V8Regex::V8Regex(), and v8_inspector::InjectedScript::wrapTable().
toProtocolStringWithTypeCheck()
String16 v8_inspector::toProtocolStringWithTypeCheck (v8::Isolate * isolate, v8::Local< v8::Value > value)
Definition at line 151 of file string-util.cc.
                                                               {
  if (value.IsEmpty() || !value->IsString()) return String16();
  return toProtocolString(isolate, value.As<v8::String>());
}
References toProtocolString(), and v8::internal::value.
Referenced by v8_inspector::V8Console::CommandLineAPIScope::accessorGetterCallback(), v8_inspector::anonymous_namespace{value-mirror.cc}::FunctionMirror::buildRemoteObject(), v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::buildScopes(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForError(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForScope(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForSymbol(), v8_inspector::ValueMirror::getInternalProperties(), v8_inspector::ValueMirror::getPrivateProperties(), v8_inspector::V8Debugger::getTargetScopes(), and v8_inspector::V8Console::monitorFunctionCallback().
toProtocolValue() [1/3]
std::unique_ptr<protocol::FundamentalValue> v8_inspector::toProtocolValue (double doubleValue)
Definition at line 102 of file value-mirror.cc.
                        {
  if (doubleValue >= std::numeric_limits<int>::min() &&
      doubleValue <= std::numeric_limits<int>::max() &&
      v8::base::bit_cast<int64_t>(doubleValue) !=
          v8::base::bit_cast<int64_t>(-0.0)) {
    int intValue = static_cast<int>(doubleValue);
    if (intValue == doubleValue) {
      return protocol::FundamentalValue::create(intValue);
    }
  }
  return protocol::FundamentalValue::create(doubleValue);
}
toProtocolValue() [2/3]
protocol::Response v8_inspector::toProtocolValue (v8::Local< v8::Context > context, v8::Local< v8::Value > value, int maxDepth, std::unique_ptr< protocol::Value > * result)
Definition at line 116 of file value-mirror.cc.
                                                               {
  if (maxDepth <= 0)
    return Response::ServerError("Object reference chain is too long");
  if (value->IsNull() || value->IsUndefined()) {
    *result = protocol::Value::null();
    return Response::Success();
  }
  if (value->IsBoolean()) {
    *result =
        protocol::FundamentalValue::create(value.As<v8::Boolean>()->Value());
    return Response::Success();
  }
  if (value->IsNumber()) {
    double doubleValue = value.As<v8::Number>()->Value();
    *result = toProtocolValue(doubleValue);
    return Response::Success();
  }
  if (value->IsString()) {
    *result = protocol::StringValue::create(
        toProtocolString(v8::Isolate::GetCurrent(), value.As<v8::String>()));
    return Response::Success();
  }
  if (value->IsArray()) {
    v8::Local<v8::Array> array = value.As<v8::Array>();
    std::unique_ptr<protocol::ListValue> list_result;
    auto response =
        arrayToProtocolValue(context, array, maxDepth, &list_result);
    *result = std::move(list_result);
    return response;
  }
  if (value->IsObject()) {
    v8::Local<v8::Object> object = value.As<v8::Object>();
    std::unique_ptr<protocol::DictionaryValue> dict_result;
    auto response =
        objectToProtocolValue(context, object, maxDepth, &dict_result);
    *result = std::move(dict_result);
    return response;
  }
  return Response::ServerError("Object couldn't be returned by value");
}
References arrayToProtocolValue(), v8::Isolate::GetCurrent(), null, objectToProtocolValue(), v8::base::internal::result, toProtocolString(), v8::Boolean::Value(), and v8::internal::value.
Referenced by arrayToProtocolValue(), v8_inspector::anonymous_namespace{value-mirror.cc}::NumberMirror::buildDeepSerializedValue(), v8_inspector::anonymous_namespace{value-mirror.cc}::ObjectMirror::buildDeepSerializedValue(), v8_inspector::anonymous_namespace{value-mirror.cc}::PrimitiveValueMirror::buildRemoteObject(), v8_inspector::anonymous_namespace{value-mirror.cc}::FunctionMirror::buildRemoteObject(), v8_inspector::anonymous_namespace{value-mirror.cc}::ObjectMirror::buildRemoteObject(), objectToProtocolValue(), and toProtocolValue().
toProtocolValue() [3/3]
Response v8_inspector::toProtocolValue (v8::Local< v8::Context > context, v8::Local< v8::Value > value, std::unique_ptr< protocol::Value > * result)
Definition at line 161 of file value-mirror.cc.
                                                               {
  if (value->IsUndefined()) return Response::Success();
  return toProtocolValue(context, value, kMaxProtocolDepth, result);
}
References kMaxProtocolDepth, v8::base::internal::result, toProtocolValue(), and v8::internal::value.
toString16()
V8_EXPORT_PRIVATE String16 v8_inspector::toString16 (const StringView & string)
Definition at line 157 of file string-util.cc.
                                              {
  if (!string.length()) return String16();
  if (string.is8Bit())
    return String16(reinterpret_cast<const char*>(string.characters8()),
                    string.length());
  return String16(string.characters16(), string.length());
}
References v8::internal::length.
Referenced by v8_inspector::V8Debugger::asyncTaskScheduledForStack(), v8_inspector::V8InspectorSessionImpl::breakProgram(), v8_inspector::anonymous_namespace{value-mirror.cc}::ObjectMirror::buildDeepSerializedValue(), v8_inspector::StackFrame::buildInspectorObject(), clientMirror(), v8_inspector::ValueMirror::create(), v8_inspector::V8ConsoleMessage::createForConsoleAPI(), v8_inspector::V8InspectorImpl::exceptionRevoked(), v8_inspector::V8InspectorImpl::exceptionThrown(), v8_inspector::anonymous_namespace{value-mirror.cc}::getPropertiesForPreview(), v8_inspector::V8DebuggerScript::GetScriptName(), v8_inspector::V8InspectorSessionImpl::releaseObjectGroup(), v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::resourceNameToUrl(), v8_inspector::V8InspectorSessionImpl::schedulePauseOnNextStatement(), v8_inspector::V8InspectorSessionImpl::searchInTextByLines(), v8_inspector::V8Debugger::storeCurrentStackTrace(), v8_inspector::internal::V8DebuggerId::toString(), v8_inspector::V8InspectorSessionImpl::triggerPreciseCoverageDeltaUpdate(), v8_inspector::V8InspectorSessionImpl::unwrapObject(), and v8_inspector::V8InspectorSessionImpl::wrapObject().
toStringView() [1/2]
template<size_t N>
StringView v8_inspector::toStringView (const char * str[N])
Definition at line 81 of file string-util.h.
                                            {
  return StringView(reinterpret_cast<const uint8_t*>(str), N);
}
References v8::internal::N.
toStringView() [2/2]
V8_EXPORT_PRIVATE StringView v8_inspector::toStringView (const String16 & string)
Definition at line 165 of file string-util.cc.
                                                {
  if (string.isEmpty()) return StringView();
  return StringView(string.characters16(), string.length());
}
References v8::internal::length.
Referenced by v8_inspector::V8Debugger::AsyncEventOccurred(), v8_inspector::V8Debugger::BreakpointConditionEvaluated(), v8_inspector::StackFrame::buildInspectorObject(), v8_inspector::V8ConsoleMessage::createForConsoleAPI(), v8_inspector::V8StackTraceImpl::firstNonEmptySourceURL(), v8_inspector::V8StackTraceImpl::frames(), v8_inspector::V8DebuggerScript::GetScriptName(), v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::resourceNameToUrl(), v8_inspector::V8StackTraceImpl::topFunctionName(), and v8_inspector::V8StackTraceImpl::topSourceURL().
toV8String() [1/2]
v8::Local< v8::String > v8_inspector::toV8String (v8::Isolate * isolate, const String16 & string)
Definition at line 102 of file string-util.cc.
                                                                         {
  if (string.isEmpty()) return v8::String::Empty(isolate);
  DCHECK_GT(v8::String::kMaxLength, string.length());
  return v8::String::NewFromTwoByte(
             isolate, reinterpret_cast<const uint16_t*>(string.characters16()),
             v8::NewStringType::kNormal, static_cast<int>(string.length()))
      .ToLocalChecked();
}
References DCHECK_GT, v8::String::Empty(), v8::String::kMaxLength, v8::kNormal, v8::internal::length, and v8::String::NewFromTwoByte().
Referenced by v8_inspector::V8RuntimeAgentImpl::addBinding(), v8_inspector::V8Console::Assert(), v8_inspector::anonymous_namespace{custom-preview.cc}::bodyCallback(), clientMirror(), v8_inspector::V8InspectorImpl::compileScript(), v8_inspector::anonymous_namespace{value-mirror.cc}::createNativeGetter(), v8_inspector::anonymous_namespace{value-mirror.cc}::createNativeSetter(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForEntry(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForError(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForPrivateMethod(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForScope(), v8_inspector::anonymous_namespace{value-mirror.cc}::doesAttributeHaveObservableSideEffectOnGet(), v8_inspector::V8RuntimeAgentImpl::evaluate(), v8_inspector::V8InspectorSessionImpl::evaluate(), v8_inspector::V8DebuggerAgentImpl::evaluateOnCallFrame(), generateCustomPreview(), v8_inspector::anonymous_namespace{value-mirror.cc}::getErrorProperty(), v8_inspector::ValueMirror::getProperties(), v8_inspector::V8Debugger::getTargetScopes(), v8_inspector::InspectedContext::InspectedContext(), v8_inspector::anonymous_namespace{value-mirror.cc}::isArrayLike(), v8_inspector::V8Regex::match(), v8_inspector::V8Console::monitorFunctionCallback(), v8_inspector::anonymous_namespace{value-mirror.cc}::nativeGetterCallback(), v8_inspector::anonymous_namespace{value-mirror.cc}::nativeSetterCallback(), v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::parseAdditionalSerializationParameters(), v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::reportCallAndReplaceFirstArgument(), v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::reportCallWithArgument(), v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::reportCallWithDefaultArgument(), v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::reportDeprecatedCall(), v8_inspector::anonymous_namespace{custom-preview.cc}::reportError(), v8_inspector::InjectedScript::resolveCallArgument(), v8_inspector::V8DebuggerScript::setBreakpoint(), v8_inspector::V8DebuggerAgentImpl::setBreakpointOnFunctionCall(), v8_inspector::V8DebuggerScript::setSource(), v8_inspector::V8DebuggerAgentImpl::setVariableValue(), v8_inspector::V8ProfilerAgentImpl::startProfiling(), v8_inspector::V8ProfilerAgentImpl::stopProfiling(), v8_inspector::anonymous_namespace{custom-preview.cc}::substituteObjectTags(), and v8_inspector::V8Regex::V8Regex().
toV8String() [2/2]
v8::Local< v8::String > v8_inspector::toV8String (v8::Isolate * isolate, const StringView & string)
Definition at line 128 of file string-util.cc.
                                                           {
  if (!string.length()) return v8::String::Empty(isolate);
  DCHECK_GT(v8::String::kMaxLength, string.length());
  if (string.is8Bit())
    return v8::String::NewFromOneByte(
               isolate, reinterpret_cast<const uint8_t*>(string.characters8()),
               v8::NewStringType::kNormal, static_cast<int>(string.length()))
        .ToLocalChecked();
  return v8::String::NewFromTwoByte(
             isolate, reinterpret_cast<const uint16_t*>(string.characters16()),
             v8::NewStringType::kNormal, static_cast<int>(string.length()))
      .ToLocalChecked();
}
References DCHECK_GT, v8::String::Empty(), v8::String::kMaxLength, v8::kNormal, v8::internal::length, v8::String::NewFromOneByte(), and v8::String::NewFromTwoByte().
toV8StringInternalized() [1/2]
v8::Local< v8::String > v8_inspector::toV8StringInternalized (v8::Isolate * isolate, const char * str)
Definition at line 122 of file string-util.cc.
                                                              {
  return v8::String::NewFromUtf8(isolate, str, v8::NewStringType::kInternalized)
      .ToLocalChecked();
}
References v8::kInternalized, and v8::String::NewFromUtf8().
toV8StringInternalized() [2/2]
v8::Local< v8::String > v8_inspector::toV8StringInternalized (v8::Isolate * isolate, const String16 & string)
Definition at line 111 of file string-util.cc.
                                                                     {
  if (string.isEmpty()) return v8::String::Empty(isolate);
  DCHECK_GT(v8::String::kMaxLength, string.length());
  return v8::String::NewFromTwoByte(
             isolate, reinterpret_cast<const uint16_t*>(string.characters16()),
             v8::NewStringType::kInternalized,
             static_cast<int>(string.length()))
      .ToLocalChecked();
}
References DCHECK_GT, v8::String::Empty(), v8::kInternalized, v8::String::kMaxLength, v8::internal::length, and v8::String::NewFromTwoByte().
Referenced by v8_inspector::V8Debugger::collectionsEntries(), v8_inspector::anonymous_namespace{v8-console.cc}::createBoundFunctionProperty(), v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::firstArgToString(), v8_inspector::V8Debugger::getTargetScopes(), v8_inspector::V8Console::installMemoryGetter(), v8_inspector::V8Debugger::internalProperties(), v8_inspector::V8Regex::match(), v8_inspector::V8Debugger::privateMethods(), and v8_inspector::V8Console::queryObjectsCallback().
UTF16ToUTF8()
std::string v8_inspector::UTF16ToUTF8 (const UChar * stringStart, size_t length)
Definition at line 343 of file v8-string-conversions.cc.
                                                               {
  if (!stringStart || !length) return std::string();
  // Allocate a buffer big enough to hold all the characters
  // (an individual UTF-16 UChar can only expand to 3 UTF-8 bytes).
  // Optimization ideas, if we find this function is hot:
  // * We could speculatively create a CStringBuffer to contain 'length'
  // characters, and resize if necessary (i.e. if the buffer contains
  // non-ascii characters). (Alternatively, scan the buffer first for
  // ascii characters, so we know this will be sufficient).
  // * We could allocate a CStringBuffer with an appropriate size to
  // have a good chance of being able to write the string into the
  // buffer without reallocing (say, 1.5 x length).
  if (length > std::numeric_limits<unsigned>::max() / 3) return std::string();
  std::string output(length * 3, '\0');
  const UChar* characters = stringStart;
  const UChar* characters_end = characters + length;
  char* buffer = &*output.begin();
  char* buffer_end = &*output.end();
  while (characters < characters_end) {
    // Use strict conversion to detect unpaired surrogates.
    ConversionResult result = convertUTF16ToUTF8(
        &characters, characters_end, &buffer, buffer_end, /* strict= */ true);
    DCHECK_NE(result, targetExhausted);
    // Conversion fails when there is an unpaired surrogate. Put
    // replacement character (U+FFFD) instead of the unpaired
    // surrogate.
    if (result != conversionOK) {
      DCHECK_LE(0xD800, *characters);
      DCHECK_LE(*characters, 0xDFFF);
      // There should be room left, since one UChar hasn't been
      // converted.
      DCHECK_LE(buffer + 3, buffer_end);
      putUTF8Triple(buffer, replacementCharacter);
      ++characters;
    }
  }
  output.resize(buffer - output.data());
  return output;
}
References v8_inspector::anonymous_namespace{v8-string-conversions.cc}::conversionOK, v8_inspector::anonymous_namespace{v8-string-conversions.cc}::convertUTF16ToUTF8(), DCHECK_LE, DCHECK_NE, v8::internal::length, v8_inspector::anonymous_namespace{v8-string-conversions.cc}::putUTF8Triple(), v8_inspector::anonymous_namespace{v8-string-conversions.cc}::replacementCharacter, v8::base::internal::result, v8::internal::string, and v8_inspector::anonymous_namespace{v8-string-conversions.cc}::targetExhausted.
Referenced by v8_inspector::String16::utf8().
UTF8ToUTF16()
std::basic_string< char16_t > v8_inspector::UTF8ToUTF16 (const char * stringStart, size_t length)
Definition at line 386 of file v8-string-conversions.cc.
                                                                           {
  if (!stringStart || !length) return std::basic_string<UChar>();
  std::vector<UChar> buffer(length);
  UChar* bufferStart = buffer.data();
  UChar* bufferCurrent = bufferStart;
  const char* stringCurrent = reinterpret_cast<const char*>(stringStart);
  if (convertUTF8ToUTF16(&stringCurrent,
                         reinterpret_cast<const char*>(stringStart + length),
                         &bufferCurrent, bufferCurrent + buffer.size(), nullptr,
                         true) != conversionOK)
    return std::basic_string<UChar>();
  size_t utf16Length = bufferCurrent - bufferStart;
  return std::basic_string<UChar>(bufferStart, bufferStart + utf16Length);
}
References v8_inspector::anonymous_namespace{v8-string-conversions.cc}::conversionOK, v8_inspector::anonymous_namespace{v8-string-conversions.cc}::convertUTF8ToUTF16(), and v8::internal::length.
Referenced by v8_inspector::String16::fromUTF8().
Variable Documentation
kBacktraceObjectGroup
const char v8_inspector::kBacktraceObjectGroup[] = `backtrace` [static]
Definition at line 68 of file v8-debugger-agent-impl.cc.
Referenced by v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::buildScopes(), v8_inspector::V8DebuggerAgentImpl::currentCallFrames(), v8_inspector::V8DebuggerAgentImpl::didPause(), v8_inspector::V8DebuggerAgentImpl::restartFrame(), v8_inspector::V8DebuggerAgentImpl::resume(), v8_inspector::V8DebuggerAgentImpl::setScriptSource(), v8_inspector::V8DebuggerAgentImpl::stepInto(), v8_inspector::V8DebuggerAgentImpl::stepOut(), and v8_inspector::V8DebuggerAgentImpl::stepOver().
kBreakpointHintMaxLength
const size_t v8_inspector::kBreakpointHintMaxLength = 128 [static]
Definition at line 73 of file v8-debugger-agent-impl.cc.
Referenced by v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::breakpointHint().
kBreakpointHintMaxSearchOffset
const intptr_t v8_inspector::kBreakpointHintMaxSearchOffset = 80 * 10 [static]
Definition at line 74 of file v8-debugger-agent-impl.cc.
Referenced by v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::adjustBreakpointLocation().
kCrcTable
uint32_t v8_inspector::kCrcTable[256] [static]
Definition at line 18 of file crc32.cc.
Referenced by computeCrc32().
kDebuggerNotEnabled
const char v8_inspector::kDebuggerNotEnabled[] = `Debugger agent is not enabled` [static]
Definition at line 69 of file v8-debugger-agent-impl.cc.
Referenced by v8_inspector::V8DebuggerAgentImpl::continueToLocation(), v8_inspector::V8DebuggerAgentImpl::disassembleWasmModule(), v8_inspector::V8DebuggerAgentImpl::getScriptSource(), v8_inspector::V8DebuggerAgentImpl::getWasmBytecode(), v8_inspector::V8DebuggerAgentImpl::nextWasmDisassemblyChunk(), v8_inspector::V8DebuggerAgentImpl::pause(), v8_inspector::V8DebuggerAgentImpl::removeBreakpoint(), v8_inspector::V8DebuggerAgentImpl::setAsyncCallStackDepth(), v8_inspector::V8DebuggerAgentImpl::setBreakpoint(), v8_inspector::V8DebuggerAgentImpl::setBreakpointByUrl(), v8_inspector::V8DebuggerAgentImpl::setBreakpointOnFunctionCall(), v8_inspector::V8DebuggerAgentImpl::setInstrumentationBreakpoint(), v8_inspector::V8DebuggerAgentImpl::setPauseOnExceptions(), v8_inspector::V8DebuggerAgentImpl::setReturnValue(), v8_inspector::V8DebuggerAgentImpl::setScriptSource(), and v8_inspector::V8DebuggerAgentImpl::setVariableValue().
kDebuggerNotPaused
const char v8_inspector::kDebuggerNotPaused[] [static]
Initial value:
=
    "Can only perform operation while paused."
Definition at line 70 of file v8-debugger-agent-impl.cc.
Referenced by v8_inspector::V8DebuggerAgentImpl::continueToLocation(), v8_inspector::V8DebuggerAgentImpl::evaluateOnCallFrame(), v8_inspector::V8DebuggerAgentImpl::restartFrame(), v8_inspector::V8DebuggerAgentImpl::resume(), v8_inspector::V8DebuggerAgentImpl::setReturnValue(), v8_inspector::V8DebuggerAgentImpl::setVariableValue(), v8_inspector::V8DebuggerAgentImpl::stepInto(), v8_inspector::V8DebuggerAgentImpl::stepOut(), and v8_inspector::V8DebuggerAgentImpl::stepOver().
kDefaultTimerDelay
constexpr v8::base::TimeDelta v8_inspector::kDefaultTimerDelay [static], [constexpr]
Initial value:
=
    v8::base::TimeDelta::FromMilliseconds(50)
Definition at line 495 of file v8-heap-profiler-agent-impl.cc.
Referenced by v8_inspector::V8HeapProfilerAgentImpl::onTimerImpl(), and v8_inspector::V8HeapProfilerAgentImpl::startTrackingHeapObjectsInternal().
kMaxCustomPreviewDepth
const int v8_inspector::kMaxCustomPreviewDepth = 20
Definition at line 15 of file custom-preview.h.
Referenced by v8_inspector::anonymous_namespace{custom-preview.cc}::bodyCallback(), v8_inspector::InjectedScript::getProperties(), and v8_inspector::InjectedScript::wrapObject().
kMaxNumBreakpoints
const size_t v8_inspector::kMaxNumBreakpoints = 1000 [static]
Definition at line 77 of file v8-debugger-agent-impl.cc.
Referenced by v8_inspector::V8DebuggerAgentImpl::getPossibleBreakpoints().
kMaxProtocolDepth
const int v8_inspector::kMaxProtocolDepth = 1000 [static]
Definition at line 38 of file value-mirror.cc.
Referenced by v8_inspector::anonymous_namespace{value-mirror.cc}::ObjectMirror::buildDeepSerializedValue(), and toProtocolValue().