v8::internal::anonymous_namespace{embedded-file-writer.cc} Namespace Reference
Functions
int WriteDirectiveOrSeparator (PlatformEmbeddedFileWriterBase *w, int current_line_length, DataDirective directive)
int WriteLineEndIfNeeded (PlatformEmbeddedFileWriterBase *w, int current_line_length, int write_size)
Function Documentation
WriteDirectiveOrSeparator()
int v8::internal::anonymous_namespace{embedded-file-writer.cc}::WriteDirectiveOrSeparator (PlatformEmbeddedFileWriterBase * w, int current_line_length, DataDirective directive)
Definition at line 20 of file embedded-file-writer.cc.
                                                       {
  int printed_chars;
  if (current_line_length == 0) {
    printed_chars = w->IndentedDataDirective(directive);
    DCHECK_LT(0, printed_chars);
  } else {
    printed_chars = fprintf(w->fp(), ",");
    DCHECK_EQ(1, printed_chars);
  }
  return current_line_length + printed_chars;
}
References DCHECK_EQ, DCHECK_LT, v8::internal::PlatformEmbeddedFileWriterBase::fp(), and v8::internal::PlatformEmbeddedFileWriterBase::IndentedDataDirective().
Referenced by v8::internal::EmbeddedFileWriter::WriteBinaryContentsAsInlineAssembly(), and v8::internal::EmbeddedFileWriter::WriteCodeSection().
WriteLineEndIfNeeded()
int v8::internal::anonymous_namespace{embedded-file-writer.cc}::WriteLineEndIfNeeded (PlatformEmbeddedFileWriterBase * w, int current_line_length, int write_size)
Definition at line 34 of file embedded-file-writer.cc.
                                                                  {
  static const int kTextWidth = 100;
  // Check if adding ',0xFF...FF\n"' would force a line wrap. This doesn't use
  // the actual size of the string to be written to determine this so it's
  // more conservative than strictly needed.
  if (current_line_length + strlen(",0x") + write_size * 2 > kTextWidth) {
    fprintf(w->fp(), "\n");
    return 0;
  } else {
    return current_line_length;
  }
}
References v8::internal::PlatformEmbeddedFileWriterBase::fp().
Referenced by v8::internal::EmbeddedFileWriter::WriteBinaryContentsAsInlineAssembly().