v8::internal::anonymous_namespace{externalize-string-extension.cc} Namespace Reference
Functions
bool HasExternalForwardingIndex (DirectHandle< String > string)
MaybeDirectHandle< String > CopyConsStringToOld (Isolate *isolate, DirectHandle< ConsString > string, v8::String::Encoding encoding)
MaybeDirectHandle< String > CreateExternalizableString (v8::Isolate *isolate, DirectHandle< String > string, v8::String::Encoding encoding)
Function Documentation
CopyConsStringToOld()
MaybeDirectHandle<String> v8::internal::anonymous_namespace{externalize-string-extension.cc}::CopyConsStringToOld (Isolate * isolate, DirectHandle< ConsString > string, v8::String::Encoding encoding)
Definition at line 153 of file externalize-string-extension.cc.
                                                                         {
  DirectHandle<String> first = handle(string->first(), isolate);
  DirectHandle<String> second = handle(string->second(), isolate);
  if (encoding == v8::String::Encoding::TWO_BYTE_ENCODING &&
      first->IsOneByteRepresentation() && second->IsOneByteRepresentation()) {
    isolate->Throw(*isolate->factory()->NewStringFromAsciiChecked(
        "Cannot create externalizable two-byte string from one-byte "
        "ConsString. Create at least one part of the ConsString with "
        "createExternalizableTwoByteString()"));
    return kNullMaybeHandle;
  }
  return isolate->factory()->NewConsString(first, second, AllocationType::kOld);
}
References v8::internal::Isolate::factory(), v8::internal::handle(), v8::internal::kNullMaybeHandle, v8::internal::kOld, v8::internal::FactoryBase< Impl >::NewConsString(), v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), v8::internal::string, and v8::internal::Isolate::Throw().
Referenced by CreateExternalizableString().
CreateExternalizableString()
MaybeDirectHandle<String> v8::internal::anonymous_namespace{externalize-string-extension.cc}::CreateExternalizableString (v8::Isolate * isolate, DirectHandle< String > string, v8::String::Encoding encoding)
Definition at line 169 of file externalize-string-extension.cc.
                               {
  Isolate* i_isolate = reinterpret_cast<Isolate*>(isolate);
  DCHECK_IMPLIES(encoding == v8::String::Encoding::ONE_BYTE_ENCODING,
                 string->IsOneByteRepresentation());
  if (string->SupportsExternalization(encoding)) {
    return string;
  }
  // Return the string if it is already externalized.
  if (StringShape(*string).IsExternal()) {
    return string;
  }
  // Read-only strings are never externalizable. Don't try to copy them as
  // some parts of the code might rely on some strings being in RO space (i.e.
  // empty string).
  if (HeapLayout::InReadOnlySpace(*string)) {
    isolate->ThrowError("Read-only strings cannot be externalized.");
    return kNullMaybeHandle;
  }
#ifdef V8_COMPRESS_POINTERS
  // Small strings may not be in-place externalizable.
  if (string->Size() < static_cast<int>(sizeof(UncachedExternalString))) {
    isolate->ThrowError("String is too short to be externalized.");
    return kNullMaybeHandle;
  }
#endif
  // Special handling for ConsStrings, as the ConsString -> ExternalString
  // migration is special for GC (Tagged pointers to Untagged pointers).
  // Skip if the ConsString is flat, as we won't be guaranteed a string in old
  // space in that case. Note that this is also true for non-canonicalized
  // ConsStrings that TurboFan might create (the first part is empty), so we
  // explicitly check for that case as well.
  if (IsConsString(*string, i_isolate) && !string->IsFlat() &&
      Cast<ConsString>(string)->first()->length() != 0) {
    DirectHandle<String> result;
    if (CopyConsStringToOld(i_isolate, Cast<ConsString>(string), encoding)
            .ToHandle(&result)) {
      DCHECK(result->SupportsExternalization(encoding));
      return result;
    } else {
      return kNullMaybeHandle;
    }
  }
  // All other strings can be implicitly flattened.
  if (encoding == v8::String::ONE_BYTE_ENCODING) {
    MaybeDirectHandle<SeqOneByteString> maybe_result =
        i_isolate->factory()->NewRawOneByteString(string->length(),
                                                  AllocationType::kOld);
    DirectHandle<SeqOneByteString> result;
    if (maybe_result.ToHandle(&result)) {
      DisallowGarbageCollection no_gc;
      String::WriteToFlat(*string, result->GetChars(no_gc), 0,
                          string->length());
      DCHECK(result->SupportsExternalization(encoding));
      return result;
    }
  } else {
    MaybeDirectHandle<SeqTwoByteString> maybe_result =
        i_isolate->factory()->NewRawTwoByteString(string->length(),
                                                  AllocationType::kOld);
    DirectHandle<SeqTwoByteString> result;
    if (maybe_result.ToHandle(&result)) {
      DisallowGarbageCollection no_gc;
      String::WriteToFlat(*string, result->GetChars(no_gc), 0,
                          string->length());
      DCHECK(result->SupportsExternalization(encoding));
      return result;
    }
  }
  isolate->ThrowError("Unable to create string");
  return kNullMaybeHandle;
}
References CopyConsStringToOld(), v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::Isolate::factory(), v8::internal::HeapLayout::InReadOnlySpace(), v8::internal::InstanceTypeChecker::IsConsString(), v8::internal::StringShape::IsExternal(), v8::internal::kNullMaybeHandle, v8::internal::kOld, v8::internal::FactoryBase< Impl >::NewRawOneByteString(), v8::internal::FactoryBase< Impl >::NewRawTwoByteString(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::String::ONE_BYTE_ENCODING, v8::base::internal::result, v8::internal::string, v8::Isolate::ThrowError(), v8::internal::MaybeDirectHandle< T >::ToHandle(), v8::anonymous_namespace{api.cc}::ToHandle(), and v8::internal::String::WriteToFlat().
Referenced by v8::internal::ExternalizeStringExtension::CreateExternalizableString(), and v8::internal::ExternalizeStringExtension::CreateExternalizableTwoByteString().
HasExternalForwardingIndex()
bool v8::internal::anonymous_namespace{externalize-string-extension.cc}::HasExternalForwardingIndex (DirectHandle< String > string)
Definition at line 91 of file externalize-string-extension.cc.
                                                             {
  if (!string->IsShared()) return false;
  uint32_t raw_hash = string->raw_hash_field(kAcquireLoad);
  return Name::IsExternalForwardingIndex(raw_hash);
}
References v8::internal::Name::IsExternalForwardingIndex(), v8::kAcquireLoad, and v8::internal::string.
Referenced by v8::internal::ExternalizeStringExtension::Externalize().