v8::internal::anonymous_namespace{modules.cc} Namespace Reference
Functions
template<typename IsolateT >
Handle< UnionOf< String, Undefined > > ToStringOrUndefined (IsolateT *isolate, const AstRawString *s)
const SourceTextModuleDescriptor::Entry * BetterDuplicate (const SourceTextModuleDescriptor::Entry *candidate, ZoneMap< const AstRawString *, const SourceTextModuleDescriptor::Entry * > &export_names, const SourceTextModuleDescriptor::Entry *current_duplicate)
Function Documentation
BetterDuplicate()
const SourceTextModuleDescriptor::Entry* v8::internal::anonymous_namespace{modules.cc}::BetterDuplicate (const SourceTextModuleDescriptor::Entry * candidate, ZoneMap< const AstRawString *, const SourceTextModuleDescriptor::Entry * > & export_names, const SourceTextModuleDescriptor::Entry * current_duplicate)
Definition at line 317 of file modules.cc.
                                                              {
  DCHECK_NOT_NULL(candidate->export_name);
  DCHECK(candidate->location.IsValid());
  auto insert_result =
      export_names.insert(std::make_pair(candidate->export_name, candidate));
  if (insert_result.second) return current_duplicate;
  if (current_duplicate == nullptr) {
    current_duplicate = insert_result.first->second;
  }
  return (candidate->location.beg_pos > current_duplicate->location.beg_pos)
             ? candidate
             : current_duplicate;
}
References v8::internal::Scanner::Location::beg_pos, v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::SourceTextModuleDescriptor::Entry::export_name, v8::internal::Scanner::Location::IsValid(), and v8::internal::SourceTextModuleDescriptor::Entry::location.
Referenced by v8::internal::SourceTextModuleDescriptor::FindDuplicateExport().
ToStringOrUndefined()
template<typename IsolateT >
Handle<UnionOf<String, Undefined> > v8::internal::anonymous_namespace{modules.cc}::ToStringOrUndefined (IsolateT * isolate, const AstRawString * s)
Definition at line 128 of file modules.cc.
                                                                              {
  if (s == nullptr) return isolate->factory()->undefined_value();
  return s->string();
}
References v8::internal::AstRawString::string().
Referenced by v8::internal::SourceTextModuleDescriptor::Entry::Serialize().