v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc} Namespace Reference
Classes
struct GraphBuilder
Functions
bool IsValidSmi (intptr_t c)
Function Documentation
IsValidSmi()
bool v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::IsValidSmi (intptr_t c)
Definition at line 55 of file graph-builder.cc.
                            {
  Tagged<Object> as_obj = Tagged<Object>(c);
  if (!IsSmi(as_obj)) return false;
  return Smi::FromInt(Smi::ToInt(as_obj)).ptr() == static_cast<uintptr_t>(c);
}
References v8::internal::Smi::FromInt(), v8::internal::IsSmi(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), v8::internal::Tagged< Object >, and v8::internal::Smi::ToInt().
Referenced by v8::internal::Internals::IsValidSmi(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::ReturnValue< T >::Set(), and v8::internal::Internals::TryIntegralToSmi().