v8::internal::anonymous_namespace{heap-snapshot-generator.cc} Namespace Reference
Classes
class ExternalDataEntryAllocator
class ExternalStringRecorder
class NullContextForSnapshotScope
Functions
const v8::String::ExternalStringResourceBase * GetExternalStringResource (Tagged< ExternalString > object, PtrComprCageBase cage_base)
int ExternalStringSizeForSnapshot (Tagged< ExternalString > object, PtrComprCageBase cage_base)
int SizeForSnapshot (Tagged< HeapObject > object, PtrComprCageBase cage_base)
const char * EmbedderGraphNodeName (StringsStorage *names, EmbedderGraphImpl::Node *node)
HeapEntry::Type EmbedderGraphNodeType (EmbedderGraphImpl::Node *node)
const char * MergeNames (StringsStorage *names, const char *embedder_name, const char *wrapper_name)
Function Documentation
EmbedderGraphNodeName()
const char* v8::internal::anonymous_namespace{heap-snapshot-generator.cc}::EmbedderGraphNodeName (StringsStorage * names, EmbedderGraphImpl::Node * node)
Definition at line 3083 of file heap-snapshot-generator.cc.
                                                               {
  const char* prefix = node->NamePrefix();
  return prefix ? names->GetFormatted("%s %s", prefix, node->Name())
                : names->GetCopy(node->Name());
}
References v8::internal::StringsStorage::GetCopy(), v8::EmbedderGraph::Node::Name(), and v8::EmbedderGraph::Node::NamePrefix().
Referenced by v8::internal::EmbedderGraphEntriesAllocator::AllocateEntry(), and v8::internal::NativeObjectsExplorer::MergeNodeIntoEntry().
EmbedderGraphNodeType()
HeapEntry::Type v8::internal::anonymous_namespace{heap-snapshot-generator.cc}::EmbedderGraphNodeType (EmbedderGraphImpl::Node * node)
Definition at line 3090 of file heap-snapshot-generator.cc.
                                                                 {
  return node->IsRootNode() ? HeapEntry::kSynthetic : HeapEntry::kNative;
}
References v8::EmbedderGraph::Node::IsRootNode(), v8::internal::HeapEntry::kNative, and v8::internal::HeapEntry::kSynthetic.
Referenced by v8::internal::EmbedderGraphEntriesAllocator::AllocateEntry(), and v8::internal::NativeObjectsExplorer::MergeNodeIntoEntry().
ExternalStringSizeForSnapshot()
int v8::internal::anonymous_namespace{heap-snapshot-generator.cc}::ExternalStringSizeForSnapshot (Tagged< ExternalString > object, PtrComprCageBase cage_base)
Definition at line 550 of file heap-snapshot-generator.cc.
                                                              {
  const v8::String::ExternalStringResourceBase* resource =
      GetExternalStringResource(object, cage_base);
  size_t external_string_size = resource ? resource->EstimateMemoryUsage() : 0;
  if (external_string_size ==
      v8::String::ExternalStringResourceBase::kDefaultMemoryEstimate) {
    return object->ExternalPayloadSize();
  }
  DCHECK_LE(external_string_size, std::numeric_limits<int>::max());
  return base::saturated_cast<int>(external_string_size);
}
References DCHECK_LE, v8::String::ExternalStringResourceBase::EstimateMemoryUsage(), GetExternalStringResource(), and v8::String::ExternalStringResourceBase::kDefaultMemoryEstimate.
Referenced by SizeForSnapshot().
GetExternalStringResource()
const v8::String::ExternalStringResourceBase* v8::internal::anonymous_namespace{heap-snapshot-generator.cc}::GetExternalStringResource (Tagged< ExternalString > object, PtrComprCageBase cage_base)
Definition at line 542 of file heap-snapshot-generator.cc.
                                                               {
  if (IsExternalOneByteString(object, cage_base)) {
    return Cast<ExternalOneByteString>(object)->resource();
  }
  return Cast<ExternalTwoByteString>(object)->resource();
}
Referenced by ExternalStringSizeForSnapshot(), and v8::internal::V8HeapExplorer::ExtractStringReferences().
MergeNames()
const char* v8::internal::anonymous_namespace{heap-snapshot-generator.cc}::MergeNames (StringsStorage * names, const char * embedder_name, const char * wrapper_name)
Definition at line 3098 of file heap-snapshot-generator.cc.
                                                 {
  const char* suffix = strchr(wrapper_name, '/');
  return suffix ? names->GetFormatted("%s %s", embedder_name, suffix)
                : embedder_name;
}
Referenced by v8::internal::NativeObjectsExplorer::MergeNodeIntoEntry().
SizeForSnapshot()
int v8::internal::anonymous_namespace{heap-snapshot-generator.cc}::SizeForSnapshot (Tagged< HeapObject > object, PtrComprCageBase cage_base)
Definition at line 563 of file heap-snapshot-generator.cc.
                                                                           {
  // Since read-only space can be shared among Isolates, and JS developers have
  // no control over the size of read-only space, we represent read-only objects
  // as having zero size.
  if (HeapLayout::InReadOnlySpace(object)) return 0;
  int size = object->Size(cage_base);
  if (IsExternalString(object, cage_base)) {
    size +=
        ExternalStringSizeForSnapshot(Cast<ExternalString>(object), cage_base);
  }
  return size;
}
References ExternalStringSizeForSnapshot(), v8::internal::HeapLayout::InReadOnlySpace(), v8::internal::InstanceTypeChecker::IsExternalString(), and size().
Referenced by v8::internal::V8HeapExplorer::AddEntry(), and v8::internal::HeapObjectsMap::UpdateHeapObjectsMap().