anonymous_namespace{mksnapshot.cc} Namespace Reference
Classes
class SnapshotFileWriter
Typedefs
using CounterMap = std::map< std::string, int >
Functions
std::unique_ptr< char[]> GetExtraCode (char *filename, const char *description)
v8::StartupData CreateSnapshotDataBlob (v8::SnapshotCreator &snapshot_creator, const char *embedded_source)
v8::StartupData WarmUpSnapshotDataBlob (v8::StartupData cold_snapshot_blob, const char *warmup_source)
void WriteEmbeddedFile (i::EmbeddedFileWriter *writer)
void MaybeSetCounterFunction (v8::Isolate *isolate)
Variables
CounterMap * counter_map_ = nullptr
Typedef Documentation
CounterMap
using anonymous_namespace{mksnapshot.cc}::CounterMap = typedef std::map<std::string, int>
Definition at line 199 of file mksnapshot.cc.
Function Documentation
CreateSnapshotDataBlob()
v8::StartupData anonymous_namespace{mksnapshot.cc}::CreateSnapshotDataBlob (v8::SnapshotCreator & snapshot_creator, const char * embedded_source)
Definition at line 159 of file mksnapshot.cc.
                                                                    {
  v8::base::ElapsedTimer timer;
  timer.Start();
  v8::StartupData result = i::CreateSnapshotDataBlobInternal(
      v8::SnapshotCreator::FunctionCodeHandling::kClear, embedded_source,
      snapshot_creator);
  if (i::v8_flags.profile_deserialization) {
    i::PrintF("[Creating snapshot took %0.3f ms]\n",
              timer.Elapsed().InMillisecondsF());
  }
  timer.Stop();
  return result;
}
References v8::internal::CreateSnapshotDataBlobInternal(), v8::base::ElapsedTimer::Elapsed(), v8::base::TimeDelta::InMillisecondsF(), v8::SnapshotCreator::kClear, v8::internal::PrintF(), v8::base::internal::result, v8::base::ElapsedTimer::Start(), v8::base::ElapsedTimer::Stop(), and v8::internal::v8_flags.
Referenced by main().
GetExtraCode()
std::unique_ptr<char[]> anonymous_namespace{mksnapshot.cc}::GetExtraCode (char * filename, const char * description)
Definition at line 134 of file mksnapshot.cc.
                                                                            {
  if (filename == nullptr || strlen(filename) == 0) return nullptr;
  ::printf("Loading script for %s: %s\n", description, filename);
  FILE* file = v8::base::OS::FOpen(filename, "rb");
  if (file == nullptr) {
    fprintf(stderr, "Failed to open '%s': errno %d\n", filename, errno);
    exit(1);
  }
  fseek(file, 0, SEEK_END);
  size_t size = ftell(file);
  rewind(file);
  char* chars = new char[size + 1];
  chars[size] = '\0';
  for (size_t i = 0; i < size;) {
    size_t read = fread(&chars[i], 1, size - i, file);
    if (ferror(file)) {
      fprintf(stderr, "Failed to read '%s': errno %d\n", filename, errno);
      exit(1);
    }
    i += read;
  }
  v8::base::Fclose(file);
  return std::unique_ptr<char[]>(chars);
}
References v8::base::Fclose(), file(), v8::base::OS::FOpen(), and size().
Referenced by main().
MaybeSetCounterFunction()
void anonymous_namespace{mksnapshot.cc}::MaybeSetCounterFunction (v8::Isolate * isolate)
Definition at line 202 of file mksnapshot.cc.
                                                 {
  // If --native-code-counters is on then we enable all counters to make
  // sure we generate code to increment them from the snapshot.
  //
  // Note: For the sake of the mksnapshot, the counter function must only
  // return distinct addresses for each counter s.t. the serializer can properly
  // distinguish between them. In theory it should be okay to just return an
  // incremented int value each time this function is called, but we play it
  // safe and return a real distinct memory location tied to every counter name.
  if (i::v8_flags.native_code_counters) {
    counter_map_ = new CounterMap();
    isolate->SetCounterFunction([](const char* name) -> int* {
      auto map_entry = counter_map_->find(name);
      if (map_entry == counter_map_->end()) {
        counter_map_->emplace(name, 0);
      }
      return &counter_map_->at(name);
    });
  }
}
References counter_map_, name, v8::Isolate::SetCounterFunction(), and v8::internal::v8_flags.
Referenced by main().
WarmUpSnapshotDataBlob()
v8::StartupData anonymous_namespace{mksnapshot.cc}::WarmUpSnapshotDataBlob (v8::StartupData cold_snapshot_blob, const char * warmup_source)
Definition at line 177 of file mksnapshot.cc.
                                                                  {
  v8::base::ElapsedTimer timer;
  timer.Start();
  v8::StartupData result =
      i::WarmUpSnapshotDataBlobInternal(cold_snapshot_blob, warmup_source);
  if (i::v8_flags.profile_deserialization) {
    i::PrintF("Warming up snapshot took %0.3f ms\n",
              timer.Elapsed().InMillisecondsF());
  }
  timer.Stop();
  return result;
}
References v8::base::ElapsedTimer::Elapsed(), v8::base::TimeDelta::InMillisecondsF(), v8::internal::PrintF(), v8::base::internal::result, v8::base::ElapsedTimer::Start(), v8::base::ElapsedTimer::Stop(), v8::internal::v8_flags, and v8::internal::WarmUpSnapshotDataBlobInternal().
Referenced by main().
WriteEmbeddedFile()
void anonymous_namespace{mksnapshot.cc}::WriteEmbeddedFile (i::EmbeddedFileWriter * writer)
Definition at line 194 of file mksnapshot.cc.
                                                    {
  i::EmbeddedData embedded_blob = i::EmbeddedData::FromBlob();
  writer->WriteEmbedded(&embedded_blob);
}
References v8::internal::EmbeddedData::FromBlob(), and v8::internal::EmbeddedFileWriter::WriteEmbedded().
Referenced by main().
Variable Documentation
counter_map_
CounterMap* anonymous_namespace{mksnapshot.cc}::counter_map_ = nullptr
Definition at line 200 of file mksnapshot.cc.
Referenced by v8::Shell::DumpCounters(), wasm::EngineImpl::EngineImpl(), v8::Shell::GetCounter(), main(), MaybeSetCounterFunction(), v8::Shell::OnExit(), and wasm::EngineImpl::~EngineImpl().