v8::internal::compiler::anonymous_namespace{frame-states.cc} Namespace Reference
Functions
uint8_t DeoptimizerParameterCountFor (ContinuationFrameStateMode mode)
FrameState CreateBuiltinContinuationFrameStateCommon (JSGraph *jsgraph, FrameStateType frame_type, Builtin name, Node *closure, Node *context, Node **parameters, int parameter_count, Node *outer_frame_state, Handle< SharedFunctionInfo > shared=Handle< SharedFunctionInfo >(), const wasm::CanonicalSig *signature=nullptr)
Function Documentation
CreateBuiltinContinuationFrameStateCommon()
FrameState v8::internal::compiler::anonymous_namespace{frame-states.cc}::CreateBuiltinContinuationFrameStateCommon (JSGraph * jsgraph, FrameStateType frame_type, Builtin name, Node * closure, Node * context, Node ** parameters, int parameter_count, Node * outer_frame_state, Handle< SharedFunctionInfo > shared = Handle<SharedFunctionInfo>(), const wasm::CanonicalSig * signature = nullptr)
Definition at line 153 of file frame-states.cc.
                                                 {
  TFGraph* const graph = jsgraph->graph();
  CommonOperatorBuilder* const common = jsgraph->common();
  const Operator* op_param =
      common->StateValues(parameter_count, SparseInputMask::Dense());
  Node* params_node = graph->NewNode(op_param, parameter_count, parameters);
  BytecodeOffset bailout_id = Builtins::GetContinuationBytecodeOffset(name);
#if V8_ENABLE_WEBASSEMBLY
  const FrameStateFunctionInfo* state_info =
      signature ? common->CreateJSToWasmFrameStateFunctionInfo(
                      frame_type, parameter_count, 0, shared, signature)
                : common->CreateFrameStateFunctionInfo(
                      frame_type, parameter_count, 0, 0, shared, {});
#else
  DCHECK_NULL(signature);
  const FrameStateFunctionInfo* state_info =
      common->CreateFrameStateFunctionInfo(frame_type, parameter_count, 0, 0,
                                           shared, {});
#endif // V8_ENABLE_WEBASSEMBLY
  const Operator* op = common->FrameState(
      bailout_id, OutputFrameStateCombine::Ignore(), state_info);
  return FrameState(graph->NewNode(op, params_node, jsgraph->EmptyStateValues(),
                                   jsgraph->EmptyStateValues(), context,
                                   closure, outer_frame_state));
}
References v8::internal::compiler::MachineGraph::common(), v8::internal::compiler::CommonOperatorBuilder::CreateFrameStateFunctionInfo(), DCHECK_NULL, v8::internal::compiler::SparseInputMask::Dense(), v8::internal::compiler::CommonOperatorBuilder::FrameState(), v8::internal::Builtins::GetContinuationBytecodeOffset(), v8::internal::compiler::MachineGraph::graph(), graph(), v8::internal::compiler::OutputFrameStateCombine::Ignore(), v8::internal::name, and v8::internal::compiler::CommonOperatorBuilder::StateValues().
Referenced by v8::internal::compiler::CreateJavaScriptBuiltinContinuationFrameState(), and v8::internal::compiler::CreateStubBuiltinContinuationFrameState().
DeoptimizerParameterCountFor()
uint8_t v8::internal::compiler::anonymous_namespace{frame-states.cc}::DeoptimizerParameterCountFor (ContinuationFrameStateMode mode)
Definition at line 141 of file frame-states.cc.
                                                                      {
  switch (mode) {
    case ContinuationFrameStateMode::EAGER:
      return 0;
    case ContinuationFrameStateMode::LAZY:
      return 1;
    case ContinuationFrameStateMode::LAZY_WITH_CATCH:
      return 2;
  }
  UNREACHABLE();
}
References v8::internal::compiler::EAGER, v8::internal::compiler::LAZY, v8::internal::compiler::LAZY_WITH_CATCH, mode(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::CreateJavaScriptBuiltinContinuationFrameState(), and v8::internal::compiler::CreateStubBuiltinContinuationFrameState().