v8::internal::wasm::anonymous_namespace{constant-expression-interface.cc} Namespace Reference
Functions
WasmValue DefaultValueForType (ValueType type, Isolate *isolate, const WasmModule *module)
Function Documentation
DefaultValueForType()
WasmValue v8::internal::wasm::anonymous_namespace{constant-expression-interface.cc}::DefaultValueForType (ValueType type, Isolate * isolate, const WasmModule * module)
Definition at line 252 of file constant-expression-interface.cc.
                                                        {
  switch (type.kind()) {
    case kI32:
    case kI8:
    case kI16:
      return WasmValue(0);
    case kI64:
      return WasmValue(int64_t{0});
    case kF16:
    case kF32:
      return WasmValue(0.0f);
    case kF64:
      return WasmValue(0.0);
    case kS128:
      return WasmValue(Simd128());
    case kRefNull:
      return WasmValue(type.use_wasm_null()
                           ? Cast<Object>(isolate->factory()->wasm_null())
                           : Cast<Object>(isolate->factory()->null_value()),
                       module->canonical_type(type));
    case kVoid:
    case kRef:
    case kTop:
    case kBottom:
      UNREACHABLE();
  }
}
References v8::internal::wasm::WasmModule::canonical_type(), v8::internal::Isolate::factory(), v8::internal::kF32, v8::internal::kF64, v8::internal::kI16, v8::internal::kI32, v8::internal::kI64, v8::internal::kI8, v8::internal::kRef, v8::internal::kRefNull, v8::internal::kS128, v8::internal::tracing::type, and v8::internal::UNREACHABLE().