v8::internal::anonymous_namespace{regexp-parser.cc}::anonymous_namespace{regexp-parser.cc} Namespace Reference
Functions
void push_code_unit (ZoneVector< base::uc16 > *v, uint32_t code_unit)
void AddClassString (ZoneList< base::uc32 > *normalized_string, RegExpTree *regexp_string, ZoneList< CharacterRange > *ranges, CharacterClassStrings *strings, Zone *zone)
bool MayContainStrings (ClassSetOperandType type, RegExpTree *operand)
Function Documentation
AddClassString()
void v8::internal::anonymous_namespace{regexp-parser.cc}::anonymous_namespace{regexp-parser.cc}::AddClassString (ZoneList< base::uc32 > * normalized_string, RegExpTree * regexp_string, ZoneList< CharacterRange > * ranges, CharacterClassStrings * strings, Zone * zone)
Definition at line 2609 of file regexp-parser.cc.
                                                                {
  if (normalized_string->length() == 1) {
    ranges->Add(CharacterRange::Singleton(normalized_string->at(0)), zone);
  } else {
    strings->emplace(normalized_string->ToVector(), regexp_string);
  }
}
References v8::internal::ZoneList< T >::Add(), v8::internal::ZoneList< T >::at(), v8::internal::ZoneList< T >::length(), v8::internal::CharacterRange::Singleton(), and v8::internal::ZoneList< T >::ToVector().
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseClassStringDisjunction().
MayContainStrings()
bool v8::internal::anonymous_namespace{regexp-parser.cc}::anonymous_namespace{regexp-parser.cc}::MayContainStrings (ClassSetOperandType type, RegExpTree * operand)
Definition at line 2788 of file regexp-parser.cc.
                                                                      {
  switch (type) {
    case ClassSetOperandType::kClassSetCharacter:
    case ClassSetOperandType::kClassSetRange:
      return false;
    case ClassSetOperandType::kCharacterClassEscape:
    case ClassSetOperandType::kClassStringDisjunction:
      return operand->AsClassSetOperand()->has_strings();
    case ClassSetOperandType::kNestedClass:
      if (operand->IsClassRanges()) return false;
      return operand->AsClassSetExpression()->may_contain_strings();
  }
}
References v8::internal::anonymous_namespace{regexp-parser.cc}::kCharacterClassEscape, v8::internal::anonymous_namespace{regexp-parser.cc}::kClassSetCharacter, v8::internal::anonymous_namespace{regexp-parser.cc}::kClassSetRange, v8::internal::anonymous_namespace{regexp-parser.cc}::kClassStringDisjunction, v8::internal::anonymous_namespace{regexp-parser.cc}::kNestedClass, and v8::internal::tracing::type.
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseClassIntersection(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseClassSubtraction(), and v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseClassUnion().
push_code_unit()
void v8::internal::anonymous_namespace{regexp-parser.cc}::anonymous_namespace{regexp-parser.cc}::push_code_unit (ZoneVector< base::uc16 > * v, uint32_t code_unit)
Definition at line 1539 of file regexp-parser.cc.
                                                                 {
  if (code_unit <= unibrow::Utf16::kMaxNonSurrogateCharCode) {
    v->push_back(code_unit);
  } else {
    v->push_back(unibrow::Utf16::LeadSurrogate(code_unit));
    v->push_back(unibrow::Utf16::TrailSurrogate(code_unit));
  }
}
References unibrow::Utf16::kMaxNonSurrogateCharCode, unibrow::Utf16::LeadSurrogate(), v8::internal::ZoneVector< T >::push_back(), and unibrow::Utf16::TrailSurrogate().
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseCaptureGroupName().