cppgc::internal::anonymous_namespace{caged-heap.cc} Namespace Reference
Functions
VirtualMemory ReserveCagedHeap (PageAllocator &platform_allocator)
Function Documentation
ReserveCagedHeap()
VirtualMemory cppgc::internal::anonymous_namespace{caged-heap.cc}::ReserveCagedHeap (PageAllocator & platform_allocator)
Definition at line 40 of file caged-heap.cc.
                                                                  {
  DCHECK_EQ(0u, api_constants::kCagedHeapMaxReservationSize %
                    platform_allocator.AllocatePageSize());
  static constexpr size_t kAllocationTries = 4;
  for (size_t i = 0; i < kAllocationTries; ++i) {
#if defined(CPPGC_POINTER_COMPRESSION)
    // We want compressed pointers to have the most significant bit set to 1.
    // That way, on decompression the bit will be sign-extended. This saves us a
    // branch and 'or' operation during compression.
    //
    // We achieve this by over-reserving the cage and selecting a sub-region
    // from the upper half of the reservation that has the bit pattern we need.
    // Examples:
    // - For a 4GB cage with 1 bit of pointer compression shift, reserve 8GB and
    // use the upper 4GB.
    // - For an 8GB cage with 3 bits of pointer compression shift, reserve 32GB
    // and use the first 8GB of the upper 16 GB.
    //
    // TODO(chromium:1325007): Provide API in PageAllocator to left trim
    // allocations and return unused portions of the reservation back to the OS.
    static constexpr size_t kTryReserveSize =
        2 * api_constants::kCagedHeapMaxReservationSize;
    static constexpr size_t kTryReserveAlignment =
        2 * api_constants::kCagedHeapReservationAlignment;
#else // !defined(CPPGC_POINTER_COMPRESSION)
    static constexpr size_t kTryReserveSize =
        api_constants::kCagedHeapMaxReservationSize;
    static constexpr size_t kTryReserveAlignment =
        api_constants::kCagedHeapReservationAlignment;
#endif // !defined(CPPGC_POINTER_COMPRESSION)
    void* hint = reinterpret_cast<void*>(RoundDown(
        reinterpret_cast<uintptr_t>(platform_allocator.GetRandomMmapAddr()),
        kTryReserveAlignment));
    VirtualMemory memory(&platform_allocator, kTryReserveSize,
                         kTryReserveAlignment, hint);
    if (memory.IsReserved()) return memory;
  }
  GetGlobalOOMHandler()("Oilpan: CagedHeap reservation.");
}
References v8::PageAllocator::AllocatePageSize(), DCHECK_EQ, cppgc::internal::GetGlobalOOMHandler(), v8::PageAllocator::GetRandomMmapAddr(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, cppgc::internal::VirtualMemory::IsReserved(), and RoundDown().