v8::internal::anonymous_namespace{runtime-scopes.cc} Namespace Reference
Classes
class HandleArguments
class ParameterArguments
Enumerations
enum class RedeclarationType { kSyntaxError = 0
, kTypeError = 1
 }
Functions
Tagged< Object > ThrowRedeclarationError (Isolate *isolate, Handle< String > name, RedeclarationType redeclaration_type)
Tagged< Object > DeclareGlobal (Isolate *isolate, DirectHandle< JSGlobalObject > global, Handle< String > name, Handle< Object > value, PropertyAttributes attr, bool is_var, RedeclarationType redeclaration_type)
Maybe< bool > AddToDisposableStack (Isolate *isolate, DirectHandle< JSDisposableStackBase > stack, DirectHandle< JSAny > value, DisposeMethodCallType type, DisposeMethodHint hint)
Tagged< Object > DeclareEvalHelper (Isolate *isolate, Handle< String > name, Handle< Object > value)
DirectHandleVector< Object > GetCallerArguments (Isolate *isolate)
template<typename T >
DirectHandle< JSObject > NewSloppyArguments (Isolate *isolate, DirectHandle< JSFunction > callee, T parameters, int argument_count)
MaybeDirectHandle< Object > LoadLookupSlot (Isolate *isolate, Handle< String > name, ShouldThrow should_throw, Handle< Object > *receiver_return=nullptr)
MaybeDirectHandle< Object > StoreLookupSlot (Isolate *isolate, Handle< Context > context, Handle< String > name, DirectHandle< Object > value, LanguageMode language_mode, ContextLookupFlags context_lookup_flags=FOLLOW_CHAINS)
Enumeration Type Documentation
RedeclarationType
enum v8::internal::anonymous_namespace{runtime-scopes.cc}::RedeclarationType [strong]
Enumerator
kSyntaxError
kTypeError
Definition at line 45 of file runtime-scopes.cc.
{ kSyntaxError = 0, kTypeError = 1 };
Function Documentation
AddToDisposableStack()
Maybe<bool> v8::internal::anonymous_namespace{runtime-scopes.cc}::AddToDisposableStack (Isolate * isolate, DirectHandle< JSDisposableStackBase > stack, DirectHandle< JSAny > value, DisposeMethodCallType type, DisposeMethodHint hint)
Definition at line 248 of file runtime-scopes.cc.
                                                         {
  DirectHandle<Object> method;
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, method,
      JSDisposableStackBase::CheckValueAndGetDisposeMethod(isolate, value,
                                                           hint),
      Nothing<bool>());
  // Return the DisposableResource Record { [[ResourceValue]]: V, [[Hint]]:
  // hint, [[DisposeMethod]]: method }.
  JSDisposableStackBase::Add(isolate, stack, value, method, type, hint);
  return Just(true);
}
References v8::internal::JSDisposableStackBase::Add(), ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::JSDisposableStackBase::CheckValueAndGetDisposeMethod(), v8::Just(), v8::internal::stack, v8::internal::tracing::type, and v8::internal::value.
Referenced by v8::internal::RUNTIME_FUNCTION().
DeclareEvalHelper()
Tagged<Object> v8::internal::anonymous_namespace{runtime-scopes.cc}::DeclareEvalHelper (Isolate * isolate, Handle< String > name, Handle< Object > value)
Definition at line 366 of file runtime-scopes.cc.
                                                       {
  // Declarations are always made in a function, native, eval, or script
  // context, or a declaration block scope. Since this is called from eval, the
  // context passed is the context of the caller, which may be some nested
  // context and not the declaration context.
  Handle<Context> context(isolate->context()->declaration_context(), isolate);
  // For debug-evaluate we always use sloppy eval, in which case context could
  // also be a module context. As module contexts reuse the extension slot
  // we need to check for this.
  const bool is_debug_evaluate_in_module =
      isolate->context()->IsDebugEvaluateContext() &&
      context->IsModuleContext();
  DCHECK(context->IsFunctionContext() || IsNativeContext(*context) ||
         context->IsScriptContext() || context->IsEvalContext() ||
         (context->IsBlockContext() &&
          context->scope_info()->is_declaration_scope()) ||
         is_debug_evaluate_in_module);
  bool is_var = IsUndefined(*value, isolate);
  DCHECK_IMPLIES(!is_var, IsJSFunction(*value));
  int index;
  PropertyAttributes attributes;
  InitializationFlag init_flag;
  VariableMode mode;
  DirectHandle<Object> holder =
      Context::Lookup(context, name, DONT_FOLLOW_CHAINS, &index, &attributes,
                      &init_flag, &mode);
  DCHECK(holder.is_null() || !IsSourceTextModule(*holder));
  DCHECK(!isolate->has_exception());
  DirectHandle<JSObject> object;
  if (attributes != ABSENT && IsJSGlobalObject(*holder)) {
    // ES#sec-evaldeclarationinstantiation 8.a.iv.1.b:
    // If fnDefinable is false, throw a TypeError exception.
    return DeclareGlobal(isolate, Cast<JSGlobalObject>(holder), name, value,
                         NONE, is_var, RedeclarationType::kTypeError);
  }
  if (context->has_extension() && IsJSGlobalObject(context->extension())) {
    DirectHandle<JSGlobalObject> global(
        Cast<JSGlobalObject>(context->extension()), isolate);
    return DeclareGlobal(isolate, global, name, value, NONE, is_var,
                         RedeclarationType::kTypeError);
  } else if (context->IsScriptContext()) {
    DCHECK(IsJSGlobalObject(context->global_object()));
    DirectHandle<JSGlobalObject> global(
        Cast<JSGlobalObject>(context->global_object()), isolate);
    return DeclareGlobal(isolate, global, name, value, NONE, is_var,
                         RedeclarationType::kTypeError);
  }
  if (attributes != ABSENT) {
    DCHECK_EQ(NONE, attributes);
    // Skip var re-declarations.
    if (is_var) return ReadOnlyRoots(isolate).undefined_value();
    if (index != Context::kNotFound) {
      DCHECK(holder.is_identical_to(context));
      Context::Set(context, index, value, isolate);
      return ReadOnlyRoots(isolate).undefined_value();
    }
    object = Cast<JSObject>(holder);
  } else if (context->has_extension() && !is_debug_evaluate_in_module) {
    object = direct_handle(context->extension_object(), isolate);
    DCHECK(IsJSContextExtensionObject(*object));
  } else if (context->scope_info()->HasContextExtensionSlot() &&
             !is_debug_evaluate_in_module) {
    // Sloppy varblock and function contexts might not have an extension object
    // yet. Sloppy eval will never have an extension object, as vars are hoisted
    // out, and lets are known statically.
    DCHECK((context->IsBlockContext() &&
            context->scope_info()->is_declaration_scope()) ||
           context->IsFunctionContext());
    DCHECK(context->scope_info()->SloppyEvalCanExtendVars());
    object =
        isolate->factory()->NewJSObject(isolate->context_extension_function());
    context->set_extension(*object);
    {
      Tagged<ScopeInfo> scope_info = context->scope_info();
      if (!scope_info->SomeContextHasExtension()) {
        scope_info->mark_some_context_has_extension();
        DependentCode::DeoptimizeDependencyGroups(
            isolate, scope_info, DependentCode::kEmptyContextExtensionGroup);
      }
    }
  } else {
    THROW_NEW_ERROR_RETURN_FAILURE(
        isolate,
        NewEvalError(MessageTemplate::kVarNotAllowedInEvalScope, name));
  }
  RETURN_FAILURE_ON_EXCEPTION(isolate, JSObject::SetOwnPropertyIgnoreAttributes(
                                           object, name, value, NONE));
  return ReadOnlyRoots(isolate).undefined_value();
}
References v8::internal::ABSENT, v8::internal::Isolate::context(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, DeclareGlobal(), v8::internal::DependentCode::DeoptimizeDependencyGroups(), v8::internal::direct_handle(), v8::internal::DONT_FOLLOW_CHAINS, v8::internal::Isolate::factory(), v8::internal::Isolate::has_exception(), v8::internal::index, v8::internal::DirectHandle< T >::is_identical_to(), v8::internal::DirectHandle< T >::is_null(), v8::internal::DependentCode::kEmptyContextExtensionGroup, v8::internal::Context::kNotFound, v8::internal::Context::Lookup(), mode(), v8::internal::name, v8::internal::Factory::NewJSObject(), v8::internal::NONE, RETURN_FAILURE_ON_EXCEPTION, v8::internal::Context::Set(), v8::internal::JSObject::SetOwnPropertyIgnoreAttributes(), THROW_NEW_ERROR_RETURN_FAILURE, and v8::internal::value.
Referenced by v8::internal::RUNTIME_FUNCTION().
DeclareGlobal()
Tagged<Object> v8::internal::anonymous_namespace{runtime-scopes.cc}::DeclareGlobal (Isolate * isolate, DirectHandle< JSGlobalObject > global, Handle< String > name, Handle< Object > value, PropertyAttributes attr, bool is_var, RedeclarationType redeclaration_type)
Definition at line 60 of file runtime-scopes.cc.
                                                                   {
  DirectHandle<ScriptContextTable> script_contexts(
      global->native_context()->script_context_table(), isolate);
  VariableLookupResult lookup;
  if (script_contexts->Lookup(name, &lookup) &&
      IsLexicalVariableMode(lookup.mode)) {
    // ES#sec-globaldeclarationinstantiation 6.a:
    // If envRec.HasLexicalDeclaration(name) is true, throw a SyntaxError
    // exception.
    return ThrowRedeclarationError(isolate, name,
                                   RedeclarationType::kSyntaxError);
  }
  // Do the lookup own properties only, see ES5 erratum.
  LookupIterator::Configuration lookup_config(
      LookupIterator::Configuration::OWN_SKIP_INTERCEPTOR);
  if (!is_var) {
    // For function declarations, use the interceptor on the declaration. For
    // non-functions, use it only on initialization.
    lookup_config = LookupIterator::Configuration::OWN;
  }
  LookupIterator it(isolate, global, name, global, lookup_config);
  Maybe<PropertyAttributes> maybe = JSReceiver::GetPropertyAttributes(&it);
  if (maybe.IsNothing()) return ReadOnlyRoots(isolate).exception();
  if (it.IsFound()) {
    PropertyAttributes old_attributes = maybe.FromJust();
    // The name was declared before; check for conflicting re-declarations.
    // Skip var re-declarations.
    if (is_var) return ReadOnlyRoots(isolate).undefined_value();
    if ((old_attributes & DONT_DELETE) != 0) {
      // Only allow reconfiguring globals to functions in user code (no
      // natives, which are marked as read-only).
      DCHECK_EQ(attr & READ_ONLY, 0);
      // Check whether we can reconfigure the existing property into a
      // function.
      if (old_attributes & READ_ONLY || old_attributes & DONT_ENUM ||
          (it.state() == LookupIterator::ACCESSOR)) {
        // ECMA-262 section 15.1.11 GlobalDeclarationInstantiation 5.d:
        // If hasRestrictedGlobal is true, throw a SyntaxError exception.
        // ECMA-262 section 18.2.1.3 EvalDeclarationInstantiation 8.a.iv.1.b:
        // If fnDefinable is false, throw a TypeError exception.
        return ThrowRedeclarationError(isolate, name, redeclaration_type);
      }
      // If the existing property is not configurable, keep its attributes. Do
      attr = old_attributes;
    }
    // If the current state is ACCESSOR, this could mean it's an AccessorInfo
    // type property. We are not allowed to call into such setters during global
    // function declaration since this would break e.g., onload. Meaning
    // 'function onload() {}' would invalidly register that function as the
    // onload callback. To avoid this situation, we first delete the property
    // before readding it as a regular data property below.
    if (it.state() == LookupIterator::ACCESSOR) it.Delete();
  }
  if (!is_var) it.Restart();
  // Define or redefine own property.
  RETURN_FAILURE_ON_EXCEPTION(
      isolate, JSObject::DefineOwnPropertyIgnoreAttributes(&it, value, attr));
  return ReadOnlyRoots(isolate).undefined_value();
}
References v8::internal::LookupIterator::ACCESSOR, DCHECK_EQ, v8::internal::JSObject::DefineOwnPropertyIgnoreAttributes(), v8::internal::LookupIterator::Delete(), v8::internal::DONT_DELETE, v8::internal::DONT_ENUM, v8::Maybe< T >::FromJust(), v8::internal::JSReceiver::GetPropertyAttributes(), v8::internal::LookupIterator::IsFound(), v8::internal::IsLexicalVariableMode(), v8::Maybe< T >::IsNothing(), v8::internal::VariableLookupResult::mode, v8::internal::name, v8::internal::READ_ONLY, v8::internal::LookupIterator::Restart(), RETURN_FAILURE_ON_EXCEPTION, v8::internal::LookupIterator::state(), ThrowRedeclarationError(), and v8::internal::value.
Referenced by DeclareEvalHelper(), and v8::internal::RUNTIME_FUNCTION().
GetCallerArguments()
DirectHandleVector<Object> v8::internal::anonymous_namespace{runtime-scopes.cc}::GetCallerArguments (Isolate * isolate)
Definition at line 493 of file runtime-scopes.cc.
                                                                {
  // Find frame containing arguments passed to the caller.
  JavaScriptStackFrameIterator it(isolate);
  JavaScriptFrame* frame = it.frame();
  std::vector<Tagged<SharedFunctionInfo>> functions;
  frame->GetFunctions(&functions);
  if (functions.size() > 1) {
    int inlined_jsframe_index = static_cast<int>(functions.size()) - 1;
    TranslatedState translated_values(frame);
    translated_values.Prepare(frame->fp());
    int argument_count = 0;
    TranslatedFrame* translated_frame =
        translated_values.GetArgumentsInfoFromJSFrameIndex(
            inlined_jsframe_index, &argument_count);
    TranslatedFrame::iterator iter = translated_frame->begin();
    // Skip the function.
    iter++;
    // Skip the receiver.
    iter++;
    argument_count--;
    DirectHandleVector<Object> param_data(isolate, argument_count);
    bool should_deoptimize = false;
    for (int i = 0; i < argument_count; i++) {
      // If we materialize any object, we should deoptimize the frame because we
      // might alias an object that was eliminated by escape analysis.
      should_deoptimize = should_deoptimize || iter->IsMaterializedObject();
      DirectHandle<Object> value = iter->GetValue();
      param_data[i] = value;
      iter++;
    }
    if (should_deoptimize) {
      translated_values.StoreMaterializedValuesAndDeopt(frame);
    }
    return param_data;
  } else {
    int args_count = frame->GetActualArgumentCount();
    DirectHandleVector<Object> param_data(isolate, args_count);
    for (int i = 0; i < args_count; i++) {
      DirectHandle<Object> val =
          DirectHandle<Object>(frame->GetParameter(i), isolate);
      param_data[i] = val;
    }
    return param_data;
  }
}
References v8::internal::TranslatedFrame::begin(), v8::internal::StackFrame::fp(), v8::internal::JavaScriptStackFrameIterator::frame(), v8::internal::JavaScriptFrame::GetActualArgumentCount(), v8::internal::TranslatedState::GetArgumentsInfoFromJSFrameIndex(), v8::internal::JavaScriptFrame::GetFunctions(), v8::internal::CommonFrameWithJSLinkage::GetParameter(), v8::internal::TranslatedValue::GetValue(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::TranslatedValue::IsMaterializedObject(), v8::internal::TranslatedState::Prepare(), v8::internal::TranslatedState::StoreMaterializedValuesAndDeopt(), and v8::internal::value.
Referenced by v8::internal::RUNTIME_FUNCTION().
LoadLookupSlot()
MaybeDirectHandle<Object> v8::internal::anonymous_namespace{runtime-scopes.cc}::LoadLookupSlot (Isolate * isolate, Handle< String > name, ShouldThrow should_throw, Handle< Object > * receiver_return = nullptr)
Definition at line 811 of file runtime-scopes.cc.
                                               {
  int index;
  PropertyAttributes attributes;
  InitializationFlag flag;
  VariableMode mode;
  Handle<Context> context(isolate->context(), isolate);
  Handle<Object> holder = Context::Lookup(context, name, FOLLOW_CHAINS, &index,
                                          &attributes, &flag, &mode);
  if (isolate->has_exception()) return MaybeDirectHandle<Object>();
  if (!holder.is_null() && IsSourceTextModule(*holder)) {
    Handle<Object> receiver = isolate->factory()->undefined_value();
    if (receiver_return) *receiver_return = receiver;
    return SourceTextModule::LoadVariable(
        isolate, Cast<SourceTextModule>(holder), index);
  }
  if (index != Context::kNotFound) {
    DCHECK(IsContext(*holder));
    DirectHandle<Context> holder_context = Cast<Context>(holder);
    // If the "property" we were looking for is a local variable, the
    // receiver is the global object; see ECMA-262, 3rd., 10.1.6 and 10.2.3.
    Handle<Object> receiver = isolate->factory()->undefined_value();
    // Check for uninitialized bindings.
    if (flag == kNeedsInitialization &&
        holder_context->IsElementTheHole(index)) {
      THROW_NEW_ERROR(isolate,
                      NewReferenceError(MessageTemplate::kNotDefined, name));
    }
    if (receiver_return) *receiver_return = receiver;
    DirectHandle<Object> value = Context::Get(holder_context, index, isolate);
    DCHECK(!IsTheHole(*value, isolate));
    return value;
  }
  // Otherwise, if the slot was found the holder is a context extension
  // object, subject of a with, or a global object. We read the named
  // property from it.
  if (!holder.is_null()) {
    // No need to unhole the value here. This is taken care of by the
    // GetProperty function.
    DirectHandle<Object> value;
    ASSIGN_RETURN_ON_EXCEPTION(
        isolate, value,
        Object::GetProperty(isolate, Cast<JSAny>(holder), name));
    if (receiver_return) {
      *receiver_return =
          (IsJSGlobalObject(*holder) || IsJSContextExtensionObject(*holder))
              ? Cast<Object>(isolate->factory()->undefined_value())
              : holder;
    }
    return value;
  }
  if (should_throw == kThrowOnError) {
    // The property doesn't exist - throw exception.
    THROW_NEW_ERROR(isolate,
                    NewReferenceError(MessageTemplate::kNotDefined, name));
  }
  // The property doesn't exist - return undefined.
  if (receiver_return) *receiver_return = isolate->factory()->undefined_value();
  return isolate->factory()->undefined_value();
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::Isolate::context(), v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::internal::FOLLOW_CHAINS, v8::internal::Context::Get(), v8::internal::Object::GetProperty(), v8::internal::Isolate::has_exception(), v8::internal::index, v8::internal::HandleBase::is_null(), v8::internal::kNeedsInitialization, v8::internal::Context::kNotFound, v8::internal::kThrowOnError, v8::internal::SourceTextModule::LoadVariable(), v8::internal::Context::Lookup(), mode(), v8::internal::name, THROW_NEW_ERROR, and v8::internal::value.
Referenced by v8::internal::RUNTIME_FUNCTION(), and v8::internal::RUNTIME_FUNCTION_RETURN_PAIR().
NewSloppyArguments()
template<typename T >
DirectHandle<JSObject> v8::internal::anonymous_namespace{runtime-scopes.cc}::NewSloppyArguments (Isolate * isolate, DirectHandle< JSFunction > callee, T parameters, int argument_count)
Definition at line 546 of file runtime-scopes.cc.
                                                                            {
  CHECK(!IsDerivedConstructor(callee->shared()->kind()));
  DCHECK(callee->shared()->has_simple_parameters());
  DirectHandle<JSObject> result =
      isolate->factory()->NewArgumentsObject(callee, argument_count);
  // Allocate the elements if needed.
  int parameter_count =
      callee->shared()->internal_formal_parameter_count_without_receiver();
  if (argument_count > 0) {
    if (parameter_count > 0) {
      int mapped_count = std::min(argument_count, parameter_count);
      // Store the context and the arguments array at the beginning of the
      // parameter map.
      DirectHandle<Context> context(isolate->context(), isolate);
      DirectHandle<FixedArray> arguments = isolate->factory()->NewFixedArray(
          argument_count, AllocationType::kYoung);
      DirectHandle<SloppyArgumentsElements> parameter_map =
          isolate->factory()->NewSloppyArgumentsElements(
              mapped_count, context, arguments, AllocationType::kYoung);
      result->set_map(isolate,
                      isolate->native_context()->fast_aliased_arguments_map());
      result->set_elements(*parameter_map);
      // Loop over the actual parameters backwards.
      int index = argument_count - 1;
      while (index >= mapped_count) {
        // These go directly in the arguments array and have no
        // corresponding slot in the parameter map.
        arguments->set(index, parameters[index]);
        --index;
      }
      DirectHandle<ScopeInfo> scope_info(callee->shared()->scope_info(),
                                         isolate);
      // First mark all mappable slots as unmapped and copy the values into the
      // arguments object.
      for (int i = 0; i < mapped_count; i++) {
        arguments->set(i, parameters[i]);
        parameter_map->set_mapped_entries(
            i, *isolate->factory()->the_hole_value());
      }
      // Walk all context slots to find context allocated parameters. Mark each
      // found parameter as mapped.
      ReadOnlyRoots roots{isolate};
      for (int i = 0; i < scope_info->ContextLocalCount(); i++) {
        if (!scope_info->ContextLocalIsParameter(i)) continue;
        int parameter = scope_info->ContextLocalParameterNumber(i);
        if (parameter >= mapped_count) continue;
        arguments->set_the_hole(roots, parameter);
        Tagged<Smi> slot = Smi::FromInt(scope_info->ContextHeaderLength() + i);
        parameter_map->set_mapped_entries(parameter, slot);
      }
    } else {
      // If there is no aliasing, the arguments object elements are not
      // special in any way.
      DirectHandle<FixedArray> elements = isolate->factory()->NewFixedArray(
          argument_count, AllocationType::kYoung);
      result->set_elements(*elements);
      for (int i = 0; i < argument_count; ++i) {
        elements->set(i, parameters[i]);
      }
    }
  }
  return result;
}
References CHECK, v8::internal::Isolate::context(), v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::internal::Smi::FromInt(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::IsDerivedConstructor(), v8::internal::kYoung, v8::internal::Isolate::native_context(), v8::internal::Factory::NewArgumentsObject(), v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::FactoryBase< Impl >::NewSloppyArgumentsElements(), and v8::base::internal::result.
Referenced by v8::internal::RUNTIME_FUNCTION().
StoreLookupSlot()
MaybeDirectHandle<Object> v8::internal::anonymous_namespace{runtime-scopes.cc}::StoreLookupSlot (Isolate * isolate, Handle< Context > context, Handle< String > name, DirectHandle< Object > value, LanguageMode language_mode, ContextLookupFlags context_lookup_flags = FOLLOW_CHAINS)
Definition at line 929 of file runtime-scopes.cc.
                                                             {
  int index;
  PropertyAttributes attributes;
  InitializationFlag flag;
  VariableMode mode;
  bool is_sloppy_function_name;
  Handle<Object> holder =
      Context::Lookup(context, name, context_lookup_flags, &index, &attributes,
                      &flag, &mode, &is_sloppy_function_name);
  if (holder.is_null()) {
    // In case of JSProxy, an exception might have been thrown.
    if (isolate->has_exception()) return MaybeDirectHandle<Object>();
  } else if (IsSourceTextModule(*holder)) {
    if ((attributes & READ_ONLY) == 0) {
      SourceTextModule::StoreVariable(Cast<SourceTextModule>(holder), index,
                                      value);
    } else {
      THROW_NEW_ERROR(isolate,
                      NewTypeError(MessageTemplate::kConstAssign, name));
    }
    return value;
  }
  // The property was found in a context slot.
  if (index != Context::kNotFound) {
    auto holder_context = Cast<Context>(holder);
    if (flag == kNeedsInitialization &&
        holder_context->IsElementTheHole(index)) {
      THROW_NEW_ERROR(isolate,
                      NewReferenceError(MessageTemplate::kNotDefined, name));
    }
    if ((attributes & READ_ONLY) == 0) {
      Context::Set(holder_context, index, value, isolate);
    } else if (!is_sloppy_function_name || is_strict(language_mode)) {
      THROW_NEW_ERROR(isolate,
                      NewTypeError(MessageTemplate::kConstAssign, name));
    }
    return value;
  }
  // Slow case: The property is not in a context slot. It is either in a
  // context extension object, a property of the subject of a with, or a
  // property of the global object.
  DirectHandle<JSReceiver> object;
  if (attributes != ABSENT) {
    // The property exists on the holder.
    object = Cast<JSReceiver>(holder);
  } else if (is_strict(language_mode)) {
    // If absent in strict mode: throw.
    THROW_NEW_ERROR(isolate,
                    NewReferenceError(MessageTemplate::kNotDefined, name));
  } else {
    // If absent in sloppy mode: add the property to the global object.
    object = direct_handle(context->global_object(), isolate);
  }
  ASSIGN_RETURN_ON_EXCEPTION(isolate, value,
                             Object::SetProperty(isolate, object, name, value));
  return value;
}
References v8::internal::ABSENT, ASSIGN_RETURN_ON_EXCEPTION, v8::internal::direct_handle(), v8::internal::Isolate::has_exception(), v8::internal::index, v8::internal::HandleBase::is_null(), v8::internal::is_strict(), v8::internal::kNeedsInitialization, v8::internal::Context::kNotFound, v8::internal::Context::Lookup(), mode(), v8::internal::name, v8::internal::READ_ONLY, v8::internal::Context::Set(), v8::internal::Object::SetProperty(), v8::internal::SourceTextModule::StoreVariable(), THROW_NEW_ERROR, and v8::internal::value.
Referenced by v8::internal::RUNTIME_FUNCTION().
ThrowRedeclarationError()
Tagged<Object> v8::internal::anonymous_namespace{runtime-scopes.cc}::ThrowRedeclarationError (Isolate * isolate, Handle< String > name, RedeclarationType redeclaration_type)
Definition at line 47 of file runtime-scopes.cc.
                                                                             {
  HandleScope scope(isolate);
  if (redeclaration_type == RedeclarationType::kSyntaxError) {
    THROW_NEW_ERROR_RETURN_FAILURE(
        isolate, NewSyntaxError(MessageTemplate::kVarRedeclaration, name));
  } else {
    THROW_NEW_ERROR_RETURN_FAILURE(
        isolate, NewTypeError(MessageTemplate::kVarRedeclaration, name));
  }
}
References v8::internal::name, and THROW_NEW_ERROR_RETURN_FAILURE.
Referenced by DeclareGlobal().