v8::internal::anonymous_namespace{elements.cc} Namespace Reference
Namespaces
 anonymous_namespace{elements.cc}
Classes
class ElementsKindTraits
class InternalElementsAccessor
class ElementsAccessorBase
class DictionaryElementsAccessor
class FastElementsAccessor
class FastSmiOrObjectElementsAccessor
class FastPackedSmiElementsAccessor
class FastHoleySmiElementsAccessor
class FastPackedObjectElementsAccessor
class FastNonextensibleObjectElementsAccessor
class FastPackedNonextensibleObjectElementsAccessor
class FastHoleyNonextensibleObjectElementsAccessor
class FastSealedObjectElementsAccessor
class FastPackedSealedObjectElementsAccessor
class SharedArrayElementsAccessor
class FastHoleySealedObjectElementsAccessor
class FastFrozenObjectElementsAccessor
class FastPackedFrozenObjectElementsAccessor
class FastHoleyFrozenObjectElementsAccessor
class FastHoleyObjectElementsAccessor
struct CopyBetweenBackingStoresImpl
class FastDoubleElementsAccessor
class FastPackedDoubleElementsAccessor
class FastHoleyDoubleElementsAccessor
class TypedElementsAccessor
struct CopyBetweenBackingStoresImpl< Kind, ElementType, FLOAT16_ELEMENTS, uint16_t >
struct CopyBetweenBackingStoresImpl< Kind, ElementType, RAB_GSAB_FLOAT16_ELEMENTS, uint16_t >
class SloppyArgumentsElementsAccessor
class SlowSloppyArgumentsElementsAccessor
class FastSloppyArgumentsElementsAccessor
class StringWrapperElementsAccessor
class FastStringWrapperElementsAccessor
class SlowStringWrapperElementsAccessor
Enumerations
enum Where { AT_START
, AT_END
 }
enum IsSharedBuffer : bool { kShared = true
, kUnshared = false
 }
Functions
V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > ThrowArrayLengthRangeError (Isolate *isolate)
WriteBarrierMode GetWriteBarrierMode (Tagged< FixedArrayBase > elements, ElementsKind kind, const DisallowGarbageCollection &promise)
void CopyObjectToObjectElements (Isolate *isolate, Tagged< FixedArrayBase > from_base, ElementsKind from_kind, uint32_t from_start, Tagged< FixedArrayBase > to_base, ElementsKind to_kind, uint32_t to_start, int raw_copy_size)
void CopyDictionaryToObjectElements (Isolate *isolate, Tagged< FixedArrayBase > from_base, uint32_t from_start, Tagged< FixedArrayBase > to_base, ElementsKind to_kind, uint32_t to_start, int raw_copy_size)
void CopyDoubleToObjectElements (Isolate *isolate, Tagged< FixedArrayBase > from_base, uint32_t from_start, Tagged< FixedArrayBase > to_base, uint32_t to_start, int raw_copy_size)
void CopyDoubleToDoubleElements (Tagged< FixedArrayBase > from_base, uint32_t from_start, Tagged< FixedArrayBase > to_base, uint32_t to_start, int raw_copy_size)
void CopySmiToDoubleElements (Tagged< FixedArrayBase > from_base, uint32_t from_start, Tagged< FixedArrayBase > to_base, uint32_t to_start, int raw_copy_size)
void CopyPackedSmiToDoubleElements (Tagged< FixedArrayBase > from_base, uint32_t from_start, Tagged< FixedArrayBase > to_base, uint32_t to_start, int packed_size, int raw_copy_size)
void CopyObjectToDoubleElements (Tagged< FixedArrayBase > from_base, uint32_t from_start, Tagged< FixedArrayBase > to_base, uint32_t to_start, int raw_copy_size)
void CopyDictionaryToDoubleElements (Isolate *isolate, Tagged< FixedArrayBase > from_base, uint32_t from_start, Tagged< FixedArrayBase > to_base, uint32_t to_start, int raw_copy_size)
void SortIndices (Isolate *isolate, DirectHandle< FixedArray > indices, uint32_t sort_size)
Maybe< bool > IncludesValueSlowPath (Isolate *isolate, DirectHandle< JSObject > receiver, DirectHandle< Object > value, size_t start_from, size_t length)
Maybe< int64_t > IndexOfValueSlowPath (Isolate *isolate, DirectHandle< JSObject > receiver, DirectHandle< Object > value, size_t start_from, size_t length)
constexpr bool IsFloat16RawBitsZero (uint16_t x)
Variables
static const int kPackedSizeNotKnown = -1
constexpr int kCopyToEndAndInitializeToHole = -1
Enumeration Type Documentation
IsSharedBuffer
enum v8::internal::anonymous_namespace{elements.cc}::IsSharedBuffer : bool
Enumerator
kShared
kUnshared
Definition at line 3364 of file elements.cc.
: bool { kShared = true, kUnshared = false };
Where
enum v8::internal::anonymous_namespace{elements.cc}::Where
Enumerator
AT_START
AT_END
Definition at line 105 of file elements.cc.
{ AT_START, AT_END };
Function Documentation
CopyDictionaryToDoubleElements()
void v8::internal::anonymous_namespace{elements.cc}::CopyDictionaryToDoubleElements (Isolate * isolate, Tagged< FixedArrayBase > from_base, uint32_t from_start, Tagged< FixedArrayBase > to_base, uint32_t to_start, int raw_copy_size)
Definition at line 459 of file elements.cc.
                                                                          {
  DisallowGarbageCollection no_gc;
  Tagged<NumberDictionary> from = Cast<NumberDictionary>(from_base);
  int copy_size = raw_copy_size;
  if (copy_size < 0) {
    DCHECK_EQ(kCopyToEndAndInitializeToHole, copy_size);
    copy_size = from->max_number_key() + 1 - from_start;
    for (int i = to_start + copy_size; i < to_base->length(); ++i) {
      Cast<FixedDoubleArray>(to_base)->set_the_hole(i);
    }
  }
  if (copy_size == 0) return;
  Tagged<FixedDoubleArray> to = Cast<FixedDoubleArray>(to_base);
  uint32_t to_length = to->length();
  if (to_start + copy_size > to_length) {
    copy_size = to_length - to_start;
  }
  for (int i = 0; i < copy_size; i++) {
    InternalIndex entry = from->FindEntry(isolate, i + from_start);
    if (entry.is_found()) {
      to->set(i + to_start,
              Object::NumberValue(Cast<Number>(from->ValueAt(entry))));
    } else {
      to->set_the_hole(i + to_start);
    }
  }
}
References v8::internal::Cast< NumberDictionary >(), DCHECK_EQ, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::InternalIndex::is_found(), kCopyToEndAndInitializeToHole, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::Object::NumberValue().
Referenced by v8::internal::anonymous_namespace{elements.cc}::FastDoubleElementsAccessor< Subclass, KindTraits >::CopyElementsImpl().
CopyDictionaryToObjectElements()
void v8::internal::anonymous_namespace{elements.cc}::CopyDictionaryToObjectElements (Isolate * isolate, Tagged< FixedArrayBase > from_base, uint32_t from_start, Tagged< FixedArrayBase > to_base, ElementsKind to_kind, uint32_t to_start, int raw_copy_size)
Definition at line 239 of file elements.cc.
                                                       {
  DisallowGarbageCollection no_gc;
  Tagged<NumberDictionary> from = Cast<NumberDictionary>(from_base);
  int copy_size = raw_copy_size;
  if (raw_copy_size < 0) {
    DCHECK_EQ(kCopyToEndAndInitializeToHole, raw_copy_size);
    copy_size = from->max_number_key() + 1 - from_start;
    int start = to_start + copy_size;
    int length = to_base->length() - start;
    if (length > 0) {
      MemsetTagged(Cast<FixedArray>(to_base)->RawFieldOfElementAt(start),
                   ReadOnlyRoots(isolate).the_hole_value(), length);
    }
  }
  DCHECK(to_base != from_base);
  DCHECK(IsSmiOrObjectElementsKind(to_kind));
  if (copy_size == 0) return;
  Tagged<FixedArray> to = Cast<FixedArray>(to_base);
  uint32_t to_length = to->length();
  if (to_start + copy_size > to_length) {
    copy_size = to_length - to_start;
  }
  WriteBarrierMode write_barrier_mode = GetWriteBarrierMode(to, to_kind, no_gc);
  for (int i = 0; i < copy_size; i++) {
    InternalIndex entry = from->FindEntry(isolate, i + from_start);
    if (entry.is_found()) {
      Tagged<Object> value = from->ValueAt(entry);
      DCHECK(!IsTheHole(value, isolate));
      to->set(i + to_start, value, write_barrier_mode);
    } else {
      to->set_the_hole(isolate, i + to_start);
    }
  }
}
References v8::internal::Cast< NumberDictionary >(), v8::internal::DCHECK(), DCHECK_EQ, GetWriteBarrierMode(), v8::internal::InternalIndex::is_found(), v8::internal::IsSmiOrObjectElementsKind(), kCopyToEndAndInitializeToHole, v8::internal::length, v8::internal::MemsetTagged(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::value.
Referenced by v8::internal::anonymous_namespace{elements.cc}::FastSmiOrObjectElementsAccessor< Subclass, KindTraits >::CopyElementsImpl(), v8::internal::anonymous_namespace{elements.cc}::FastSloppyArgumentsElementsAccessor::CopyElementsImpl(), and v8::internal::anonymous_namespace{elements.cc}::StringWrapperElementsAccessor< Subclass, BackingStoreAccessor, KindTraits >::CopyElementsImpl().
CopyDoubleToDoubleElements()
void v8::internal::anonymous_namespace{elements.cc}::CopyDoubleToDoubleElements (Tagged< FixedArrayBase > from_base, uint32_t from_start, Tagged< FixedArrayBase > to_base, uint32_t to_start, int raw_copy_size)
Definition at line 329 of file elements.cc.
                                                                      {
  DisallowGarbageCollection no_gc;
  int copy_size = raw_copy_size;
  if (raw_copy_size < 0) {
    DCHECK_EQ(kCopyToEndAndInitializeToHole, raw_copy_size);
    copy_size = std::min(from_base->length() - from_start,
                         to_base->length() - to_start);
    for (int i = to_start + copy_size; i < to_base->length(); ++i) {
      Cast<FixedDoubleArray>(to_base)->set_the_hole(i);
    }
  }
  DCHECK((copy_size + static_cast<int>(to_start)) <= to_base->length() &&
         (copy_size + static_cast<int>(from_start)) <= from_base->length());
  if (copy_size == 0) return;
  Tagged<FixedDoubleArray> from = Cast<FixedDoubleArray>(from_base);
  Tagged<FixedDoubleArray> to = Cast<FixedDoubleArray>(to_base);
  Address to_address = reinterpret_cast<Address>(to->begin());
  Address from_address = reinterpret_cast<Address>(from->begin());
  to_address += kDoubleSize * to_start;
  from_address += kDoubleSize * from_start;
#ifdef V8_COMPRESS_POINTERS
  // TODO(ishell, v8:8875): we use CopyTagged() in order to avoid unaligned
  // access to double values in the arrays. This will no longed be necessary
  // once the allocations alignment issue is fixed.
  int words_per_double = (kDoubleSize / kTaggedSize);
  CopyTagged(to_address, from_address,
             static_cast<size_t>(words_per_double * copy_size));
#else
  int words_per_double = (kDoubleSize / kSystemPointerSize);
  CopyWords(to_address, from_address,
            static_cast<size_t>(words_per_double * copy_size));
#endif
}
References v8::internal::CopyTagged(), v8::internal::CopyWords(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::anonymous_namespace{json-stringifier.cc}::i, kCopyToEndAndInitializeToHole, v8::internal::kDoubleSize, v8::internal::kSystemPointerSize, v8::internal::kTaggedSize, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::internal::anonymous_namespace{elements.cc}::FastDoubleElementsAccessor< Subclass, KindTraits >::CopyElementsImpl().
CopyDoubleToObjectElements()
void v8::internal::anonymous_namespace{elements.cc}::CopyDoubleToObjectElements (Isolate * isolate, Tagged< FixedArrayBase > from_base, uint32_t from_start, Tagged< FixedArrayBase > to_base, uint32_t to_start, int raw_copy_size)
Definition at line 282 of file elements.cc.
                                                                      {
  int copy_size = raw_copy_size;
  if (raw_copy_size < 0) {
    DisallowGarbageCollection no_gc;
    DCHECK_EQ(kCopyToEndAndInitializeToHole, raw_copy_size);
    copy_size = std::min(from_base->length() - from_start,
                         to_base->length() - to_start);
    // Also initialize the area that will be copied over since HeapNumber
    // allocation below can cause an incremental marking step, requiring all
    // existing heap objects to be properly initialized.
    int start = to_start;
    int length = to_base->length() - start;
    if (length > 0) {
      MemsetTagged(Cast<FixedArray>(to_base)->RawFieldOfElementAt(start),
                   ReadOnlyRoots(isolate).the_hole_value(), length);
    }
  }
  DCHECK((copy_size + static_cast<int>(to_start)) <= to_base->length() &&
         (copy_size + static_cast<int>(from_start)) <= from_base->length());
  if (copy_size == 0) return;
  // From here on, the code below could actually allocate. Therefore the raw
  // values are wrapped into handles.
  DirectHandle<FixedDoubleArray> from(Cast<FixedDoubleArray>(from_base),
                                      isolate);
  DirectHandle<FixedArray> to(Cast<FixedArray>(to_base), isolate);
  // Use an outer loop to not waste too much time on creating HandleScopes.
  // On the other hand we might overflow a single handle scope depending on
  // the copy_size.
  int offset = 0;
  while (offset < copy_size) {
    HandleScope scope(isolate);
    offset += 100;
    for (int i = offset - 100; i < offset && i < copy_size; ++i) {
      DirectHandle<Object> value =
          FixedDoubleArray::get(*from, i + from_start, isolate);
      to->set(i + to_start, *value, UPDATE_WRITE_BARRIER);
    }
  }
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::FixedDoubleArray::get(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, kCopyToEndAndInitializeToHole, v8::internal::length, v8::internal::MemsetTagged(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::UPDATE_WRITE_BARRIER, and v8::internal::value.
Referenced by v8::internal::anonymous_namespace{elements.cc}::FastSmiOrObjectElementsAccessor< Subclass, KindTraits >::CopyElementsImpl().
CopyObjectToDoubleElements()
void v8::internal::anonymous_namespace{elements.cc}::CopyObjectToDoubleElements (Tagged< FixedArrayBase > from_base, uint32_t from_start, Tagged< FixedArrayBase > to_base, uint32_t to_start, int raw_copy_size)
Definition at line 429 of file elements.cc.
                                                                      {
  DisallowGarbageCollection no_gc;
  int copy_size = raw_copy_size;
  if (raw_copy_size < 0) {
    DCHECK_EQ(kCopyToEndAndInitializeToHole, raw_copy_size);
    copy_size = from_base->length() - from_start;
    for (int i = to_start + copy_size; i < to_base->length(); ++i) {
      Cast<FixedDoubleArray>(to_base)->set_the_hole(i);
    }
  }
  DCHECK((copy_size + static_cast<int>(to_start)) <= to_base->length() &&
         (copy_size + static_cast<int>(from_start)) <= from_base->length());
  if (copy_size == 0) return;
  Tagged<FixedArray> from = Cast<FixedArray>(from_base);
  Tagged<FixedDoubleArray> to = Cast<FixedDoubleArray>(to_base);
  Tagged<Hole> the_hole = GetReadOnlyRoots().the_hole_value();
  for (uint32_t from_end = from_start + copy_size; from_start < from_end;
       from_start++, to_start++) {
    Tagged<Object> hole_or_object = from->get(from_start);
    if (hole_or_object == the_hole) {
      to->set_the_hole(to_start);
    } else {
      to->set(to_start, Object::NumberValue(Cast<Number>(hole_or_object)));
    }
  }
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::GetReadOnlyRoots(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, kCopyToEndAndInitializeToHole, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::Object::NumberValue().
Referenced by v8::internal::anonymous_namespace{elements.cc}::FastDoubleElementsAccessor< Subclass, KindTraits >::CopyElementsImpl().
CopyObjectToObjectElements()
void v8::internal::anonymous_namespace{elements.cc}::CopyObjectToObjectElements (Isolate * isolate, Tagged< FixedArrayBase > from_base, ElementsKind from_kind, uint32_t from_start, Tagged< FixedArrayBase > to_base, ElementsKind to_kind, uint32_t to_start, int raw_copy_size)
Definition at line 202 of file elements.cc.
                                                   {
  ReadOnlyRoots roots(isolate);
  DCHECK(to_base->map() != roots.fixed_cow_array_map());
  DisallowGarbageCollection no_gc;
  int copy_size = raw_copy_size;
  if (raw_copy_size < 0) {
    DCHECK_EQ(kCopyToEndAndInitializeToHole, raw_copy_size);
    copy_size = std::min(from_base->length() - from_start,
                         to_base->length() - to_start);
    int start = to_start + copy_size;
    int length = to_base->length() - start;
    if (length > 0) {
      MemsetTagged(Cast<FixedArray>(to_base)->RawFieldOfElementAt(start),
                   roots.the_hole_value(), length);
    }
  }
  DCHECK((copy_size + static_cast<int>(to_start)) <= to_base->length() &&
         (copy_size + static_cast<int>(from_start)) <= from_base->length());
  if (copy_size == 0) return;
  Tagged<FixedArray> from = Cast<FixedArray>(from_base);
  Tagged<FixedArray> to = Cast<FixedArray>(to_base);
  DCHECK(IsSmiOrObjectElementsKind(from_kind));
  DCHECK(IsSmiOrObjectElementsKind(to_kind));
  WriteBarrierMode write_barrier_mode =
      (IsObjectElementsKind(from_kind) && IsObjectElementsKind(to_kind))
          ? UPDATE_WRITE_BARRIER
          : SKIP_WRITE_BARRIER;
  to->CopyElements(isolate, to_start, from, from_start, copy_size,
                   write_barrier_mode);
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::IsObjectElementsKind(), v8::internal::IsSmiOrObjectElementsKind(), kCopyToEndAndInitializeToHole, v8::internal::length, v8::internal::MemsetTagged(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::SKIP_WRITE_BARRIER, and v8::internal::UPDATE_WRITE_BARRIER.
Referenced by v8::internal::anonymous_namespace{elements.cc}::FastSmiOrObjectElementsAccessor< Subclass, KindTraits >::CopyElementsImpl(), v8::internal::anonymous_namespace{elements.cc}::FastSloppyArgumentsElementsAccessor::CopyElementsImpl(), v8::internal::anonymous_namespace{elements.cc}::StringWrapperElementsAccessor< Subclass, BackingStoreAccessor, KindTraits >::CopyElementsImpl(), and v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::PrependElementIndicesImpl().
CopyPackedSmiToDoubleElements()
void v8::internal::anonymous_namespace{elements.cc}::CopyPackedSmiToDoubleElements (Tagged< FixedArrayBase > from_base, uint32_t from_start, Tagged< FixedArrayBase > to_base, uint32_t to_start, int packed_size, int raw_copy_size)
Definition at line 396 of file elements.cc.
                                                      {
  DisallowGarbageCollection no_gc;
  int copy_size = raw_copy_size;
  uint32_t to_end;
  if (raw_copy_size < 0) {
    DCHECK_EQ(kCopyToEndAndInitializeToHole, raw_copy_size);
    copy_size = packed_size - from_start;
    to_end = to_base->length();
    for (uint32_t i = to_start + copy_size; i < to_end; ++i) {
      Cast<FixedDoubleArray>(to_base)->set_the_hole(i);
    }
  } else {
    to_end = to_start + static_cast<uint32_t>(copy_size);
  }
  DCHECK(static_cast<int>(to_end) <= to_base->length());
  DCHECK(packed_size >= 0 && packed_size <= copy_size);
  DCHECK((copy_size + static_cast<int>(to_start)) <= to_base->length() &&
         (copy_size + static_cast<int>(from_start)) <= from_base->length());
  if (copy_size == 0) return;
  Tagged<FixedArray> from = Cast<FixedArray>(from_base);
  Tagged<FixedDoubleArray> to = Cast<FixedDoubleArray>(to_base);
  for (uint32_t from_end = from_start + static_cast<uint32_t>(packed_size);
       from_start < from_end; from_start++, to_start++) {
    Tagged<Object> smi = from->get(from_start);
    DCHECK(!IsTheHole(smi));
    to->set(to_start, Smi::ToInt(smi));
  }
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::anonymous_namespace{json-stringifier.cc}::i, kCopyToEndAndInitializeToHole, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::Smi::ToInt().
Referenced by v8::internal::anonymous_namespace{elements.cc}::FastDoubleElementsAccessor< Subclass, KindTraits >::CopyElementsImpl().
CopySmiToDoubleElements()
void v8::internal::anonymous_namespace{elements.cc}::CopySmiToDoubleElements (Tagged< FixedArrayBase > from_base, uint32_t from_start, Tagged< FixedArrayBase > to_base, uint32_t to_start, int raw_copy_size)
Definition at line 366 of file elements.cc.
                                                {
  DisallowGarbageCollection no_gc;
  int copy_size = raw_copy_size;
  if (raw_copy_size < 0) {
    DCHECK_EQ(kCopyToEndAndInitializeToHole, raw_copy_size);
    copy_size = from_base->length() - from_start;
    for (int i = to_start + copy_size; i < to_base->length(); ++i) {
      Cast<FixedDoubleArray>(to_base)->set_the_hole(i);
    }
  }
  DCHECK((copy_size + static_cast<int>(to_start)) <= to_base->length() &&
         (copy_size + static_cast<int>(from_start)) <= from_base->length());
  if (copy_size == 0) return;
  Tagged<FixedArray> from = Cast<FixedArray>(from_base);
  Tagged<FixedDoubleArray> to = Cast<FixedDoubleArray>(to_base);
  Tagged<Object> the_hole = GetReadOnlyRoots().the_hole_value();
  for (uint32_t from_end = from_start + static_cast<uint32_t>(copy_size);
       from_start < from_end; from_start++, to_start++) {
    Tagged<Object> hole_or_smi = from->get(from_start);
    if (hole_or_smi == the_hole) {
      to->set_the_hole(to_start);
    } else {
      to->set(to_start, Smi::ToInt(hole_or_smi));
    }
  }
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::GetReadOnlyRoots(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, kCopyToEndAndInitializeToHole, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::Smi::ToInt().
Referenced by v8::internal::anonymous_namespace{elements.cc}::FastDoubleElementsAccessor< Subclass, KindTraits >::CopyElementsImpl().
GetWriteBarrierMode()
WriteBarrierMode v8::internal::anonymous_namespace{elements.cc}::GetWriteBarrierMode (Tagged< FixedArrayBase > elements, ElementsKind kind, const DisallowGarbageCollection & promise)
Definition at line 188 of file elements.cc.
                                                                               {
  if (IsSmiElementsKind(kind)) return SKIP_WRITE_BARRIER;
  if (IsDoubleElementsKind(kind)) return SKIP_WRITE_BARRIER;
  return elements->GetWriteBarrierMode(promise);
}
References v8::internal::IsDoubleElementsKind(), v8::internal::IsSmiElementsKind(), and v8::internal::SKIP_WRITE_BARRIER.
Referenced by CopyDictionaryToObjectElements().
IncludesValueSlowPath()
Maybe<bool> v8::internal::anonymous_namespace{elements.cc}::IncludesValueSlowPath (Isolate * isolate, DirectHandle< JSObject > receiver, DirectHandle< Object > value, size_t start_from, size_t length)
Definition at line 520 of file elements.cc.
                                                 {
  bool search_for_hole = IsUndefined(*value, isolate);
  for (size_t k = start_from; k < length; ++k) {
    LookupIterator it(isolate, receiver, k);
    if (!it.IsFound()) {
      if (search_for_hole) return Just(true);
      continue;
    }
    DirectHandle<Object> element_k;
    ASSIGN_RETURN_ON_EXCEPTION_VALUE(isolate, element_k,
                                     Object::GetProperty(&it), Nothing<bool>());
    if (Object::SameValueZero(*value, *element_k)) return Just(true);
  }
  return Just(false);
}
References ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::Object::GetProperty(), v8::internal::LookupIterator::IsFound(), v8::Just(), v8::internal::length, v8::internal::Object::SameValueZero(), and v8::internal::value.
Referenced by v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::IncludesValueImpl(), v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::IncludesValueImpl(), and v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::IncludesValueImpl().
IndexOfValueSlowPath()
Maybe<int64_t> v8::internal::anonymous_namespace{elements.cc}::IndexOfValueSlowPath (Isolate * isolate, DirectHandle< JSObject > receiver, DirectHandle< Object > value, size_t start_from, size_t length)
Definition at line 541 of file elements.cc.
                                                                      {
  for (size_t k = start_from; k < length; ++k) {
    LookupIterator it(isolate, receiver, k);
    if (!it.IsFound()) {
      continue;
    }
    DirectHandle<Object> element_k;
    ASSIGN_RETURN_ON_EXCEPTION_VALUE(
        isolate, element_k, Object::GetProperty(&it), Nothing<int64_t>());
    if (Object::StrictEquals(*value, *element_k)) return Just<int64_t>(k);
  }
  return Just<int64_t>(-1);
}
References ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::Object::GetProperty(), v8::internal::LookupIterator::IsFound(), v8::internal::length, v8::internal::Object::StrictEquals(), and v8::internal::value.
Referenced by v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::IndexOfValueImpl(), v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::IndexOfValueImpl(), and v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::IndexOfValueImpl().
IsFloat16RawBitsZero()
constexpr bool v8::internal::anonymous_namespace{elements.cc}::IsFloat16RawBitsZero (uint16_t x) [constexpr]
Definition at line 3366 of file elements.cc.
                                                {
  // IEEE754 comparison returns true for 0 == -0, even though they are two
  // different bit patterns.
  return (x & ~0x8000) == 0;
}
Referenced by v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::IncludesValueImpl(), v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::IndexOfValueImpl(), and v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::LastIndexOfValueImpl().
SortIndices()
void v8::internal::anonymous_namespace{elements.cc}::SortIndices (Isolate * isolate, DirectHandle< FixedArray > indices, uint32_t sort_size)
Definition at line 491 of file elements.cc.
                                     {
  if (sort_size == 0) return;
  // Use AtomicSlot wrapper to ensure that std::sort uses atomic load and
  // store operations that are safe for concurrent marking.
  AtomicSlot start(indices->RawFieldOfFirstElement());
  AtomicSlot end(start + sort_size);
  std::sort(start, end, [isolate](Tagged_t elementA, Tagged_t elementB) {
#ifdef V8_COMPRESS_POINTERS
    Tagged<Object> a(V8HeapCompressionScheme::DecompressTagged(elementA));
    Tagged<Object> b(V8HeapCompressionScheme::DecompressTagged(elementB));
#else
    Tagged<Object> a(elementA);
    Tagged<Object> b(elementB);
#endif
    if (IsSmi(a) || !IsUndefined(a, isolate)) {
      if (!IsSmi(b) && IsUndefined(b, isolate)) {
        return true;
      }
      return Object::NumberValue(Cast<Number>(a)) <
             Object::NumberValue(Cast<Number>(b));
    }
    return !IsSmi(b) && IsUndefined(b, isolate);
  });
  WriteBarrier::ForRange(isolate->heap(), *indices, ObjectSlot(start),
                         ObjectSlot(end));
}
References v8::internal::V8HeapCompressionSchemeImpl< Cage >::DecompressTagged(), v8::internal::compiler::end(), v8::internal::WriteBarrier::ForRange(), v8::internal::Isolate::heap(), v8::internal::IsSmi(), v8::internal::Object::NumberValue(), and v8::base::sort().
Referenced by v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::CollectElementIndicesImpl(), v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::CollectElementIndicesImpl(), and v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::PrependElementIndicesImpl().
ThrowArrayLengthRangeError()
V8_WARN_UNUSED_RESULT MaybeDirectHandle<Object> v8::internal::anonymous_namespace{elements.cc}::ThrowArrayLengthRangeError (Isolate * isolate)
Definition at line 184 of file elements.cc.
                                                                       {
  THROW_NEW_ERROR(isolate, NewRangeError(MessageTemplate::kInvalidArrayLength));
}
References THROW_NEW_ERROR.
Referenced by v8::internal::ArrayConstructInitializeElements().
Variable Documentation
kCopyToEndAndInitializeToHole
constexpr int v8::internal::anonymous_namespace{elements.cc}::kCopyToEndAndInitializeToHole = -1 [constexpr]
Definition at line 200 of file elements.cc.
Referenced by v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::ConvertElementsWithCapacity(), CopyDictionaryToDoubleElements(), CopyDictionaryToObjectElements(), CopyDoubleToDoubleElements(), CopyDoubleToObjectElements(), CopyObjectToDoubleElements(), CopyObjectToObjectElements(), CopyPackedSmiToDoubleElements(), and CopySmiToDoubleElements().
kPackedSizeNotKnown
const int v8::internal::anonymous_namespace{elements.cc}::kPackedSizeNotKnown = -1 [static]
Definition at line 103 of file elements.cc.
Referenced by v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::ConvertElementsWithCapacity(), and v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::CopyElements().