v8::internal::compiler::anonymous_namespace{wasm-typer.cc} Namespace Reference
Functions
bool AllInputsTyped (Node *node)
Function Documentation
AllInputsTyped()
bool v8::internal::compiler::anonymous_namespace{wasm-typer.cc}::AllInputsTyped (Node * node)
Definition at line 33 of file wasm-typer.cc.
                                {
  for (int i = 0; i < node->op()->ValueInputCount(); i++) {
    if (!NodeProperties::IsTyped(NodeProperties::GetValueInput(node, i))) {
      return false;
    }
  }
  return true;
}
References v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::NodeProperties::IsTyped(), and v8::internal::compiler::Node::op().
Referenced by v8::internal::compiler::WasmTyper::Reduce().