v8::internal::anonymous_namespace{setup-builtins-internal.cc} Namespace Reference
Typedefs
using BuiltinCompilationScheduler = compiler::CodeAssembler::BuiltinCompilationScheduler
using MacroAssemblerGenerator = void(*)(MacroAssembler *)
using TurboshaftAssemblerGenerator = void(*)(compiler::turboshaft::PipelineData *, Isolate *, compiler::turboshaft::Graph &, Zone *)
using CodeAssemblerGenerator = compiler::Pipeline::CodeAssemblerGenerator
using CodeAssemblerInstaller = compiler::Pipeline::CodeAssemblerInstaller
Functions
AssemblerOptions BuiltinAssemblerOptions (Isolate *isolate, Builtin builtin)
DirectHandle< Code > BuildPlaceholder (Isolate *isolate, Builtin builtin)
V8_NOINLINE Tagged< Code > BuildWithMacroAssembler (Isolate *isolate, Builtin builtin, MacroAssemblerGenerator generator, const char *s_name)
Tagged< Code > BuildAdaptor (Isolate *isolate, Builtin builtin, Address builtin_address, const char *name)
V8_NOINLINE Tagged< Code > BuildWithTurboshaftAssemblerJS (Isolate *isolate, Builtin builtin, compiler::turboshaft::TurboshaftAssemblerGenerator generator, int argc, const char *name)
void CompileJSLinkageCodeStubBuiltin (Isolate *isolate, Builtin builtin, CodeAssemblerGenerator generator, CodeAssemblerInstaller installer, int argc, const char *name, int finalize_order, BuiltinCompilationScheduler &scheduler)
V8_NOINLINE Tagged< Code > BuildWithTurboshaftAssemblerCS (Isolate *isolate, Builtin builtin, compiler::turboshaft::TurboshaftAssemblerGenerator generator, CallDescriptors::Key interface_descriptor, const char *name)
void CompileCSLinkageCodeStubBuiltin (Isolate *isolate, Builtin builtin, CodeAssemblerGenerator generator, CodeAssemblerInstaller installer, CallDescriptors::Key interface_descriptor, const char *name, int finalize_order, BuiltinCompilationScheduler &scheduler)
void CompileBytecodeHandler (Isolate *isolate, Builtin builtin, interpreter::OperandScale operand_scale, interpreter::Bytecode bytecode, compiler::Pipeline::CodeAssemblerInstaller installer, int finalize_order, BuiltinCompilationScheduler &scheduler)
Variables
const int kBufferSize = 128 * KB
Typedef Documentation
BuiltinCompilationScheduler
using v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuiltinCompilationScheduler = typedef compiler::CodeAssembler::BuiltinCompilationScheduler
Definition at line 79 of file setup-builtins-internal.cc.
CodeAssemblerGenerator
using v8::internal::anonymous_namespace{setup-builtins-internal.cc}::CodeAssemblerGenerator = typedef compiler::Pipeline::CodeAssemblerGenerator
Definition at line 136 of file setup-builtins-internal.cc.
CodeAssemblerInstaller
using v8::internal::anonymous_namespace{setup-builtins-internal.cc}::CodeAssemblerInstaller = typedef compiler::Pipeline::CodeAssemblerInstaller
Definition at line 137 of file setup-builtins-internal.cc.
MacroAssemblerGenerator
using v8::internal::anonymous_namespace{setup-builtins-internal.cc}::MacroAssemblerGenerator = typedef void (*)(MacroAssembler*)
Definition at line 132 of file setup-builtins-internal.cc.
TurboshaftAssemblerGenerator
using v8::internal::anonymous_namespace{setup-builtins-internal.cc}::TurboshaftAssemblerGenerator = typedef void (*)(compiler::turboshaft::PipelineData*, Isolate*, compiler::turboshaft::Graph&, Zone*)
Definition at line 133 of file setup-builtins-internal.cc.
Function Documentation
BuildAdaptor()
Tagged<Code> v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuildAdaptor (Isolate * isolate, Builtin builtin, Address builtin_address, const char * name)
Definition at line 219 of file setup-builtins-internal.cc.
                                                                     {
  HandleScope scope(isolate);
  uint8_t buffer[kBufferSize];
  MacroAssembler masm(isolate, BuiltinAssemblerOptions(isolate, builtin),
                      CodeObjectRequired::kYes,
                      ExternalAssemblerBuffer(buffer, kBufferSize));
  masm.set_builtin(builtin);
  DCHECK(!masm.has_frame());
  int formal_parameter_count = Builtins::GetFormalParameterCount(builtin);
  Builtins::Generate_Adaptor(&masm, formal_parameter_count, builtin_address);
  CodeDesc desc;
  masm.GetCode(isolate, &desc);
  DirectHandle<Code> code =
      Factory::CodeBuilder(isolate, desc, CodeKind::BUILTIN)
          .set_self_reference(masm.CodeObject())
          .set_builtin(builtin)
          .set_parameter_count(formal_parameter_count)
          .Build();
  return *code;
}
References v8::internal::Factory::CodeBuilder::Build(), BUILTIN, BuiltinAssemblerOptions(), code, v8::internal::MacroAssemblerBase::CodeObject(), v8::internal::DCHECK(), v8::internal::ExternalAssemblerBuffer(), v8::internal::Builtins::Generate_Adaptor(), v8::internal::Assembler::GetCode(), v8::internal::Builtins::GetFormalParameterCount(), v8::internal::MacroAssemblerBase::has_frame(), kBufferSize, v8::internal::kYes, v8::internal::MacroAssemblerBase::set_builtin(), v8::internal::Factory::CodeBuilder::set_builtin(), v8::internal::Factory::CodeBuilder::set_parameter_count(), and v8::internal::Factory::CodeBuilder::set_self_reference().
BuildPlaceholder()
DirectHandle<Code> v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuildPlaceholder (Isolate * isolate, Builtin builtin)
Definition at line 139 of file setup-builtins-internal.cc.
                                                                       {
  HandleScope scope(isolate);
  uint8_t buffer[kBufferSize];
  MacroAssembler masm(isolate, CodeObjectRequired::kYes,
                      ExternalAssemblerBuffer(buffer, kBufferSize));
  DCHECK(!masm.has_frame());
  {
    FrameScope frame_scope(&masm, StackFrame::NO_FRAME_TYPE);
    // The contents of placeholder don't matter, as long as they don't create
    // embedded constants or external references.
    masm.Move(kJavaScriptCallCodeStartRegister, Smi::zero());
    masm.Call(kJavaScriptCallCodeStartRegister);
  }
  CodeDesc desc;
  masm.GetCode(isolate, &desc);
  Handle<Code> code = Factory::CodeBuilder(isolate, desc, CodeKind::BUILTIN)
                          .set_self_reference(masm.CodeObject())
                          .set_builtin(builtin)
                          .Build();
  return scope.CloseAndEscape(code);
}
References v8::internal::Factory::CodeBuilder::Build(), BUILTIN, v8::internal::MacroAssembler::Call(), code, v8::internal::MacroAssemblerBase::CodeObject(), v8::internal::DCHECK(), v8::internal::ExternalAssemblerBuffer(), v8::internal::Assembler::GetCode(), v8::internal::MacroAssemblerBase::has_frame(), kBufferSize, v8::internal::kJavaScriptCallCodeStartRegister, v8::internal::kYes, v8::internal::MacroAssembler::Move(), v8::internal::StackFrame::NO_FRAME_TYPE, v8::internal::Factory::CodeBuilder::set_builtin(), v8::internal::Factory::CodeBuilder::set_self_reference(), and v8::internal::Smi::zero().
Referenced by v8::internal::SetupIsolateDelegate::PopulateWithPlaceholders().
BuildWithMacroAssembler()
V8_NOINLINE Tagged<Code> v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuildWithMacroAssembler (Isolate * isolate, Builtin builtin, MacroAssemblerGenerator generator, const char * s_name)
Definition at line 161 of file setup-builtins-internal.cc.
                        {
  HandleScope scope(isolate);
  uint8_t buffer[kBufferSize];
  MacroAssembler masm(isolate, BuiltinAssemblerOptions(isolate, builtin),
                      CodeObjectRequired::kYes,
                      ExternalAssemblerBuffer(buffer, kBufferSize));
  masm.set_builtin(builtin);
  DCHECK(!masm.has_frame());
  masm.CodeEntry();
  generator(&masm);
  int handler_table_offset = 0;
  // JSEntry builtins are a special case and need to generate a handler table.
  DCHECK_EQ(Builtins::KindOf(Builtin::kJSEntry), Builtins::ASM);
  DCHECK_EQ(Builtins::KindOf(Builtin::kJSConstructEntry), Builtins::ASM);
  DCHECK_EQ(Builtins::KindOf(Builtin::kJSRunMicrotasksEntry), Builtins::ASM);
  if (Builtins::IsJSEntryVariant(builtin)) {
    handler_table_offset = HandlerTable::EmitReturnTableStart(&masm);
    HandlerTable::EmitReturnEntry(
        &masm, 0, isolate->builtins()->js_entry_handler_offset());
#if V8_ENABLE_DRUMBRAKE
  } else if (builtin == Builtin::kWasmInterpreterCWasmEntry) {
    handler_table_offset = HandlerTable::EmitReturnTableStart(&masm);
    HandlerTable::EmitReturnEntry(
        &masm, 0,
        isolate->builtins()->cwasm_interpreter_entry_handler_offset());
#endif // V8_ENABLE_DRUMBRAKE
  }
#if V8_ENABLE_WEBASSEMBLY && \
    (V8_TARGET_ARCH_X64 || V8_TARGET_ARCH_ARM64 || V8_TARGET_ARCH_IA32 || \
     V8_TARGET_ARCH_ARM || V8_TARGET_ARCH_RISCV64 || V8_TARGET_ARCH_LOONG64 || \
     V8_TARGET_ARCH_PPC64 || V8_TARGET_ARCH_S390X || V8_TARGET_ARCH_RISCV32)
  if (builtin == Builtin::kWasmReturnPromiseOnSuspendAsm) {
    handler_table_offset = HandlerTable::EmitReturnTableStart(&masm);
    HandlerTable::EmitReturnEntry(
        &masm, 0, isolate->builtins()->jspi_prompt_handler_offset());
  }
#endif
  CodeDesc desc;
  masm.GetCode(isolate->main_thread_local_isolate(), &desc,
               MacroAssembler::kNoSafepointTable, handler_table_offset);
  DirectHandle<Code> code =
      Factory::CodeBuilder(isolate, desc, CodeKind::BUILTIN)
          .set_self_reference(masm.CodeObject())
          .set_builtin(builtin)
          .Build();
#if defined(V8_OS_WIN64)
  isolate->SetBuiltinUnwindData(builtin, masm.GetUnwindInfo());
#endif // V8_OS_WIN64
  return *code;
}
References v8::internal::Builtins::ASM, v8::internal::Factory::CodeBuilder::Build(), BUILTIN, BuiltinAssemblerOptions(), v8::internal::Isolate::builtins(), code, v8::internal::MacroAssembler::CodeEntry(), v8::internal::MacroAssemblerBase::CodeObject(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::HandlerTable::EmitReturnEntry(), v8::internal::HandlerTable::EmitReturnTableStart(), v8::internal::ExternalAssemblerBuffer(), v8::internal::Assembler::GetCode(), v8::internal::MacroAssemblerBase::has_frame(), v8::internal::Builtins::IsJSEntryVariant(), v8::internal::Builtins::js_entry_handler_offset(), v8::internal::Builtins::jspi_prompt_handler_offset(), kBufferSize, v8::internal::Builtins::KindOf(), v8::internal::Assembler::kNoSafepointTable, v8::internal::kYes, v8::internal::Isolate::main_thread_local_isolate(), v8::internal::MacroAssemblerBase::set_builtin(), v8::internal::Factory::CodeBuilder::set_builtin(), and v8::internal::Factory::CodeBuilder::set_self_reference().
BuildWithTurboshaftAssemblerCS()
V8_NOINLINE Tagged<Code> v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuildWithTurboshaftAssemblerCS (Isolate * isolate, Builtin builtin, compiler::turboshaft::TurboshaftAssemblerGenerator generator, CallDescriptors::Key interface_descriptor, const char * name)
Definition at line 275 of file setup-builtins-internal.cc.
                                                               {
  HandleScope scope(isolate);
  DirectHandle<Code> code =
      compiler::turboshaft::BuildWithTurboshaftAssemblerImpl(
          isolate, builtin, generator,
          [interface_descriptor](Zone* zone) {
            CallInterfaceDescriptor descriptor(interface_descriptor);
            DCHECK_LE(0, descriptor.GetRegisterParameterCount());
            return compiler::Linkage::GetStubCallDescriptor(
                zone, descriptor, descriptor.GetStackParameterCount(),
                compiler::CallDescriptor::kNoFlags,
                compiler::Operator::kNoProperties);
          },
          name, BuiltinAssemblerOptions(isolate, builtin));
  return *code;
}
References v8::internal::compiler::turboshaft::BuildWithTurboshaftAssemblerImpl(), BuiltinAssemblerOptions(), code, DCHECK_LE, v8::internal::CallInterfaceDescriptor::GetRegisterParameterCount(), v8::internal::CallInterfaceDescriptor::GetStackParameterCount(), v8::internal::compiler::Linkage::GetStubCallDescriptor(), v8::internal::compiler::CallDescriptor::kNoFlags, v8::internal::compiler::Operator::kNoProperties, and v8::internal::name.
Referenced by CompileCSLinkageCodeStubBuiltin().
BuildWithTurboshaftAssemblerJS()
V8_NOINLINE Tagged<Code> v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuildWithTurboshaftAssemblerJS (Isolate * isolate, Builtin builtin, compiler::turboshaft::TurboshaftAssemblerGenerator generator, int argc, const char * name)
Definition at line 242 of file setup-builtins-internal.cc.
                      {
  HandleScope scope(isolate);
  DirectHandle<Code> code =
      compiler::turboshaft::BuildWithTurboshaftAssemblerImpl(
          isolate, builtin, generator,
          [argc](Zone* zone) {
            return compiler::Linkage::GetJSCallDescriptor(
                zone, false, argc, compiler::CallDescriptor::kCanUseRoots);
          },
          name, BuiltinAssemblerOptions(isolate, builtin));
  return *code;
}
References v8::internal::compiler::turboshaft::BuildWithTurboshaftAssemblerImpl(), BuiltinAssemblerOptions(), code, v8::internal::compiler::Linkage::GetJSCallDescriptor(), v8::internal::compiler::CallDescriptor::kCanUseRoots, and v8::internal::name.
Referenced by CompileJSLinkageCodeStubBuiltin().
BuiltinAssemblerOptions()
AssemblerOptions v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuiltinAssemblerOptions (Isolate * isolate, Builtin builtin)
Definition at line 84 of file setup-builtins-internal.cc.
                                                                            {
  AssemblerOptions options = AssemblerOptions::Default(isolate);
  CHECK(!options.isolate_independent_code);
  CHECK(!options.collect_win64_unwind_info);
#if V8_ENABLE_WEBASSEMBLY
  if (wasm::BuiltinLookup::IsWasmBuiltinId(builtin) ||
      builtin == Builtin::kJSToWasmWrapper ||
      builtin == Builtin::kJSToWasmHandleReturns ||
      builtin == Builtin::kWasmToJsWrapperCSA) {
    options.is_wasm = true;
  }
#endif
  if (!isolate->IsGeneratingEmbeddedBuiltins()) {
    return options;
  }
  const base::AddressRegion& code_region = isolate->heap()->code_region();
  bool pc_relative_calls_fit_in_code_range =
      !code_region.is_empty() &&
      std::ceil(static_cast<float>(code_region.size() / MB)) <=
          kMaxPCRelativeCodeRangeInMB;
  // Mksnapshot ensures that the code range is small enough to guarantee that
  // PC-relative call/jump instructions can be used for builtin to builtin
  // calls/tail calls. The embedded builtins blob generator also ensures that.
  // However, there are serializer tests, where we force isolate creation at
  // runtime and at this point, Code space isn't restricted to a
  // size s.t. PC-relative calls may be used. So, we fall back to an indirect
  // mode.
  options.use_pc_relative_calls_and_jumps_for_mksnapshot =
      pc_relative_calls_fit_in_code_range;
  options.builtin_call_jump_mode = BuiltinCallJumpMode::kForMksnapshot;
  options.isolate_independent_code = true;
  options.collect_win64_unwind_info = true;
  if (builtin == Builtin::kInterpreterEntryTrampolineForProfiling) {
    // InterpreterEntryTrampolineForProfiling must be generated in a position
    // independent way because it might be necessary to create a copy of the
    // builtin in the code space if the v8_flags.interpreted_frames_native_stack
    // is enabled.
    options.builtin_call_jump_mode = BuiltinCallJumpMode::kIndirect;
  }
  return options;
}
References v8::internal::AssemblerOptions::builtin_call_jump_mode, CHECK, v8::internal::Heap::code_region(), v8::internal::AssemblerOptions::collect_win64_unwind_info, v8::internal::AssemblerOptions::Default(), v8::internal::Isolate::heap(), v8::base::AddressRegion::is_empty(), v8::internal::AssemblerOptions::is_wasm, v8::internal::Isolate::IsGeneratingEmbeddedBuiltins(), v8::internal::AssemblerOptions::isolate_independent_code, v8::internal::wasm::BuiltinLookup::IsWasmBuiltinId(), v8::internal::kForMksnapshot, v8::internal::kIndirect, v8::internal::kMaxPCRelativeCodeRangeInMB, v8::internal::MB, v8::base::AddressRegion::size(), and v8::internal::AssemblerOptions::use_pc_relative_calls_and_jumps_for_mksnapshot.
Referenced by BuildAdaptor(), BuildWithMacroAssembler(), BuildWithTurboshaftAssemblerCS(), BuildWithTurboshaftAssemblerJS(), CompileBytecodeHandler(), CompileCSLinkageCodeStubBuiltin(), and CompileJSLinkageCodeStubBuiltin().
CompileBytecodeHandler()
void v8::internal::anonymous_namespace{setup-builtins-internal.cc}::CompileBytecodeHandler (Isolate * isolate, Builtin builtin, interpreter::OperandScale operand_scale, interpreter::Bytecode bytecode, compiler::Pipeline::CodeAssemblerInstaller installer, int finalize_order, BuiltinCompilationScheduler & scheduler)
Definition at line 319 of file setup-builtins-internal.cc.
                                            {
  DCHECK(interpreter::Bytecodes::BytecodeHasHandler(bytecode, operand_scale));
  const char* name = Builtins::name(builtin);
  auto generator = [bytecode,
                    operand_scale](compiler::CodeAssemblerState* state) {
    interpreter::GenerateBytecodeHandler(state, bytecode, operand_scale);
  };
  std::unique_ptr<TurbofanCompilationJob> job(
      compiler::Pipeline::NewBytecodeHandlerCompilationJob(
          isolate, builtin, generator, installer,
          BuiltinAssemblerOptions(isolate, builtin), name,
          ProfileDataFromFile::TryRead(name), finalize_order));
  scheduler.CompileCode(isolate, std::move(job));
}
References BuiltinAssemblerOptions(), v8::internal::interpreter::Bytecodes::BytecodeHasHandler(), v8::internal::compiler::CodeAssembler::BuiltinCompilationScheduler::CompileCode(), v8::internal::DCHECK(), v8::internal::interpreter::GenerateBytecodeHandler(), v8::internal::Builtins::name(), v8::internal::name, v8::internal::compiler::Pipeline::NewBytecodeHandlerCompilationJob(), and v8::internal::ProfileDataFromFile::TryRead().
CompileCSLinkageCodeStubBuiltin()
void v8::internal::anonymous_namespace{setup-builtins-internal.cc}::CompileCSLinkageCodeStubBuiltin (Isolate * isolate, Builtin builtin, CodeAssemblerGenerator generator, CodeAssemblerInstaller installer, CallDescriptors::Key interface_descriptor, const char * name, int finalize_order, BuiltinCompilationScheduler & scheduler)
Definition at line 296 of file setup-builtins-internal.cc.
                                                                             {
  // TODO(nicohartmann): Remove this once `BuildWithTurboshaftAssemblerCS` has
  // an actual use.
#if V8_ENABLE_GEARBOX
  std::optional<InstructionSetExtensionScope> isx_scope;
  if (Builtins::IsISXVariant(builtin)) {
    isx_scope.emplace();
  }
#endif // V8_ENABLE_GEARBOX
  USE(&BuildWithTurboshaftAssemblerCS);
  std::unique_ptr<TurbofanCompilationJob> job(
      compiler::Pipeline::NewCSLinkageCodeStubBuiltinCompilationJob(
          isolate, builtin, generator, installer,
          BuiltinAssemblerOptions(isolate, builtin), interface_descriptor, name,
          ProfileDataFromFile::TryRead(name), finalize_order));
  scheduler.CompileCode(isolate, std::move(job));
}
References BuildWithTurboshaftAssemblerCS(), BuiltinAssemblerOptions(), v8::internal::compiler::CodeAssembler::BuiltinCompilationScheduler::CompileCode(), v8::internal::name, v8::internal::compiler::Pipeline::NewCSLinkageCodeStubBuiltinCompilationJob(), v8::internal::ProfileDataFromFile::TryRead(), and USE.
CompileJSLinkageCodeStubBuiltin()
void v8::internal::anonymous_namespace{setup-builtins-internal.cc}::CompileJSLinkageCodeStubBuiltin (Isolate * isolate, Builtin builtin, CodeAssemblerGenerator generator, CodeAssemblerInstaller installer, int argc, const char * name, int finalize_order, BuiltinCompilationScheduler & scheduler)
Definition at line 258 of file setup-builtins-internal.cc.
                                                                             {
  // TODO(nicohartmann): Remove this once `BuildWithTurboshaftAssemblerJS` has
  // an actual use.
  USE(&BuildWithTurboshaftAssemblerJS);
  std::unique_ptr<TurbofanCompilationJob> job(
      compiler::Pipeline::NewJSLinkageCodeStubBuiltinCompilationJob(
          isolate, builtin, generator, installer,
          BuiltinAssemblerOptions(isolate, builtin), argc, name,
          ProfileDataFromFile::TryRead(name), finalize_order));
  scheduler.CompileCode(isolate, std::move(job));
}
References BuildWithTurboshaftAssemblerJS(), BuiltinAssemblerOptions(), v8::internal::compiler::CodeAssembler::BuiltinCompilationScheduler::CompileCode(), v8::internal::name, v8::internal::compiler::Pipeline::NewJSLinkageCodeStubBuiltinCompilationJob(), v8::internal::ProfileDataFromFile::TryRead(), and USE.
Variable Documentation
kBufferSize
const int v8::internal::anonymous_namespace{setup-builtins-internal.cc}::kBufferSize = 128 * KB
Definition at line 82 of file setup-builtins-internal.cc.
Referenced by v8_inspector::String16Builder::appendNumber(), v8::internal::CircularStructureMessageBuilder::AppendSmi(), v8_inspector::String16Builder::appendUnsignedAsHex(), v8::internal::CodeStubAssembler::BranchIfMaybeSpecialIndex(), BuildAdaptor(), BuildPlaceholder(), BuildWithMacroAssembler(), v8_inspector::String16::fromInteger(), v8::internal::NumberParseIntHelper::HandleBaseTenCase(), v8::internal::IsSpecialIndex(), v8::internal::wasm::operator<<(), v8::internal::wasm::FunctionBodyDisassembler::PrintHexNumber(), v8::Shell::ReadFromStdin(), v8::internal::JsonStringifier::SerializeDouble(), v8::internal::FastJsonStringifier< Char >::SerializeDouble(), v8::internal::JsonStringifier::SerializeSmi(), v8::internal::FastJsonStringifier< Char >::SerializeSmi(), and v8::internal::WriteLine().