v8::internal::anonymous_namespace{global-handles.cc} Namespace Reference
Functions
void ExtractInternalFields (Tagged< JSObject > jsobject, void **embedder_fields, int len)
template<typename NodeType >
bool NeedsTrackingInYoungNodes (Tagged< Object > value, NodeType *node)
template<typename T >
void UpdateListOfYoungNodesImpl (Isolate *isolate, std::vector< T * > *node_list)
template<typename T >
void ClearListOfYoungNodesImpl (Isolate *isolate, std::vector< T * > *node_list)
Variables
constexpr size_t kBlockSize = 256
Function Documentation
ClearListOfYoungNodesImpl()
template<typename T >
void v8::internal::anonymous_namespace{global-handles.cc}::ClearListOfYoungNodesImpl (Isolate * isolate, std::vector< T * > * node_list)
Definition at line 802 of file global-handles.cc.
                                                                           {
  for (T* node : *node_list) {
    DCHECK(node->is_in_young_list());
    node->set_in_young_list(false);
    DCHECK_IMPLIES(node->IsInUse() && node->state() != T::NEAR_DEATH,
                   !HeapLayout::InYoungGeneration(node->object()));
  }
  isolate->heap()->IncrementNodesDiedInNewSpace(
      static_cast<int>(node_list->size()));
  node_list->clear();
  node_list->shrink_to_fit();
}
References v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::Isolate::heap(), v8::internal::Heap::IncrementNodesDiedInNewSpace(), and v8::internal::HeapLayout::InYoungGeneration().
Referenced by v8::internal::GlobalHandles::ClearListOfYoungNodes().
ExtractInternalFields()
void v8::internal::anonymous_namespace{global-handles.cc}::ExtractInternalFields (Tagged< JSObject > jsobject, void ** embedder_fields, int len)
Definition at line 410 of file global-handles.cc.
                                    {
  int field_count = jsobject->GetEmbedderFieldCount();
  IsolateForSandbox isolate = GetCurrentIsolateForSandbox();
  for (int i = 0; i < len; ++i) {
    if (field_count == i) break;
    void* pointer;
    if (EmbedderDataSlot(jsobject, i).ToAlignedPointer(isolate, &pointer)) {
      embedder_fields[i] = pointer;
    }
  }
}
References v8::internal::GetCurrentIsolateForSandbox(), and v8::internal::anonymous_namespace{json-stringifier.cc}::i.
Referenced by v8::internal::GlobalHandles::Node::CollectPhantomCallbackData().
NeedsTrackingInYoungNodes()
template<typename NodeType >
bool v8::internal::anonymous_namespace{global-handles.cc}::NeedsTrackingInYoungNodes (Tagged< Object > value, NodeType * node)
Definition at line 618 of file global-handles.cc.
                                                                     {
  return HeapLayout::InYoungGeneration(value) && !node->is_in_young_list();
}
References v8::internal::HeapLayout::InYoungGeneration(), and v8::internal::value.
Referenced by v8::internal::GlobalHandles::Create().
UpdateListOfYoungNodesImpl()
template<typename T >
void v8::internal::anonymous_namespace{global-handles.cc}::UpdateListOfYoungNodesImpl (Isolate * isolate, std::vector< T * > * node_list)
Definition at line 779 of file global-handles.cc.
                                                                            {
  size_t last = 0;
  for (T* node : *node_list) {
    DCHECK(node->is_in_young_list());
    if (node->IsInUse() && node->state() != T::NEAR_DEATH) {
      if (HeapLayout::InYoungGeneration(node->object())) {
        (*node_list)[last++] = node;
        isolate->heap()->IncrementNodesCopiedInNewSpace();
      } else {
        node->set_in_young_list(false);
        isolate->heap()->IncrementNodesPromoted();
      }
    } else {
      node->set_in_young_list(false);
      isolate->heap()->IncrementNodesDiedInNewSpace(1);
    }
  }
  DCHECK_LE(last, node_list->size());
  node_list->resize(last);
  node_list->shrink_to_fit();
}
References v8::internal::DCHECK(), DCHECK_LE, v8::internal::Isolate::heap(), v8::internal::Heap::IncrementNodesCopiedInNewSpace(), v8::internal::Heap::IncrementNodesDiedInNewSpace(), v8::internal::Heap::IncrementNodesPromoted(), and v8::internal::HeapLayout::InYoungGeneration().
Referenced by v8::internal::GlobalHandles::UpdateListOfYoungNodes().
Variable Documentation
kBlockSize
constexpr size_t v8::internal::anonymous_namespace{global-handles.cc}::kBlockSize = 256 [constexpr]
Definition at line 41 of file global-handles.cc.
Referenced by v8::internal::GlobalHandles::NodeBlock< _NodeType >::end_address(), v8::internal::GlobalHandles::NodeBlock< _NodeType >::IncreaseUsage(), v8::internal::GlobalHandles::NodeIterator< BlockType >::operator++(), v8::internal::GlobalHandles::NodeSpace< NodeType >::PutNodesOnFreeList(), and v8::internal::GlobalHandles::NodeSpace< NodeType >::TotalSize().