v8::internal::ETWJITInterface Namespace Reference
Classes
class EtwIsolateCaptureStateMonitor
class IsolateLoadScriptData
class EtwIsolateOperations
struct str_bytes
struct str_bytes< 0 >
Typedefs
using IsolateMapType = std::unordered_map< v8::internal::Isolate *, IsolateLoadScriptData >
using FilterDataType = std::string
Functions
void SetMetaDescriptors (EVENT_DATA_DESCRIPTOR *data_descriptor, UINT16 const UNALIGNED *traits, const void *metadata, size_t size)
template<size_t count, typename idx = std::make_index_sequence<count>>
constexpr auto MakeStrBytes (char const (&s)[count])
template<std::size_t size1, std::size_t size2>
constexpr auto JoinBytes (const str_bytes< size1 > &str1, const str_bytes< size2 > &str2)
template<size_t count>
constexpr auto Field (char const (&s)[count], uint8_t type)
constexpr auto Header (size_t size)
constexpr auto JoinFields ()
template<typename T1 >
constexpr auto JoinFields (T1 field)
template<typename T1 , typename T2 , typename... Ts>
constexpr auto JoinFields (T1 field1, T2 field2, Ts... args)
template<std::size_t count, typename... Ts>
constexpr auto EventFields (char const (&name)[count], Ts... field_args)
constexpr auto EventMetadata (uint16_t id, uint64_t keywords)
void SetFieldDescriptors (EVENT_DATA_DESCRIPTOR *data_descriptors)
template<typename... Ts>
void SetFieldDescriptors (EVENT_DATA_DESCRIPTOR *data_descriptors, const std::wstring &value, const Ts &... rest)
template<typename... Ts>
void SetFieldDescriptors (EVENT_DATA_DESCRIPTOR *data_descriptors, const std::string &value, const Ts &... rest)
template<typename... Ts>
void SetFieldDescriptors (EVENT_DATA_DESCRIPTOR *data_descriptors, const char *value, const Ts &... rest)
template<typename T , typename... Ts>
void SetFieldDescriptors (EVENT_DATA_DESCRIPTOR *data_descriptors, const T &value, const Ts &... rest)
ULONG LogEvent (uint64_t regHandle, const EVENT_DESCRIPTOR *event_descriptor, EVENT_DATA_DESCRIPTOR *data_descriptor, ULONG desc_count)
template<typename T , typename... Fs>
void LogEventData (const TraceLoggingHProvider provider, const EVENT_DESCRIPTOR *event_descriptor, T *meta, const Fs &... fields)
V8_DECLARE_TRACELOGGING_PROVIDER (g_v8Provider)
V8_DEFINE_TRACELOGGING_PROVIDER (g_v8Provider)
void MaybeSetHandlerNow (Isolate *isolate)
Tagged< SharedFunctionInfo > GetSharedFunctionInfo (const JitCodeEvent *event)
std::wstring GetScriptMethodNameFromEvent (const JitCodeEvent *event)
std::wstring GetScriptMethodNameFromSharedFunctionInfo (Tagged< SharedFunctionInfo > sfi)
std::wstring GetScriptMethodName (const JitCodeEvent *event)
void UpdateETWEnabled (bool enabled, uint32_t options)
void WINAPI V8_EXPORT_PRIVATE ETWEnableCallback (LPCGUID, ULONG is_enabled, UCHAR level, ULONGLONG match_any_keyword, ULONGLONG match_all_keyword, PEVENT_FILTER_DESCRIPTOR filter_data, PVOID)
void Register ()
void Unregister ()
void AddIsolate (Isolate *isolate)
void RemoveIsolate (Isolate *isolate)
void EventHandler (const JitCodeEvent *event)
Variables
constexpr auto kCaptureStateTimeout = base::TimeDelta::FromSeconds(10)
base::LazyMutex isolates_mutex = LAZY_MUTEX_INITIALIZER
base::LazyInstance< IsolateMapType >::type isolate_map
base::LazyInstance< FilterDataType >::type etw_filter_payload_glob
const uint8_t kManifestFreeChannel = 11
const uint8_t kMetaDescriptorsCount = 2
constexpr uint32_t kEtwControlDisable = 0
constexpr uint32_t kEtwControlEnable = 1
constexpr uint32_t kEtwControlCaptureState = 2
constexpr uint64_t kJScriptRuntimeKeyword = 1
constexpr uint16_t kSourceLoadEventID = 41
constexpr uint16_t kMethodLoadEventID = 9
constexpr uint16_t kSourceDCStartEventID = 39
constexpr uint16_t kMethodDCStartEventID = 5
constexpr unsigned char kTraceLevel = TRACE_LEVEL_INFORMATION
std::atomic< bool > has_active_etw_tracing_session_or_custom_filter = false
constexpr uint32_t kEtwRundown = 0xf0000000
Typedef Documentation
FilterDataType
using v8::internal::ETWJITInterface::FilterDataType = typedef std::string
Definition at line 91 of file etw-isolate-load-script-data-win.h.
IsolateMapType
using v8::internal::ETWJITInterface::IsolateMapType = typedef std::unordered_map<v8::internal::Isolate*, IsolateLoadScriptData>
Definition at line 87 of file etw-isolate-load-script-data-win.h.
Function Documentation
AddIsolate()
void v8::internal::ETWJITInterface::AddIsolate (Isolate * isolate)
Definition at line 199 of file etw-jit-win.cc.
                                  {
  IsolateLoadScriptData::AddIsolate(isolate);
}
References v8::internal::ETWJITInterface::IsolateLoadScriptData::AddIsolate().
Referenced by v8::internal::Isolate::Init().
ETWEnableCallback()
void WINAPI V8_EXPORT_PRIVATE v8::internal::ETWJITInterface::ETWEnableCallback (LPCGUID , ULONG is_enabled, UCHAR level, ULONGLONG match_any_keyword, ULONGLONG match_all_keyword, PEVENT_FILTER_DESCRIPTOR filter_data, PVOID)
Definition at line 112 of file etw-jit-win.cc.
                                                   {
  ETWTRACEDBG << "ETWEnableCallback called with is_enabled==" << is_enabled
              << std::endl;
  bool is_etw_enabled_now =
      is_enabled && level >= kTraceLevel &&
      (match_any_keyword & kJScriptRuntimeKeyword) &&
      ((match_all_keyword & kJScriptRuntimeKeyword) == match_all_keyword);
  uint32_t options = kJitCodeEventDefault;
  if (is_enabled == kEtwControlCaptureState) {
    options |= (kEtwRundown | kJitCodeEventEnumExisting);
  }
  FilterDataType* etw_filter = etw_filter_payload_glob.Pointer();
  if (!is_etw_enabled_now) {
    // Disable the current tracing session.
    ETWTRACEDBG << "Disabling" << std::endl;
    etw_filter->clear();
    UpdateETWEnabled(false, options);
    return;
  }
  DCHECK(is_etw_enabled_now);
  // Ignore the callback if ETW tracing is not fully enabled and we are not
  // passing a custom filter.
  if (!v8_flags.enable_etw_stack_walking &&
      (!filter_data || filter_data->Type != EVENT_FILTER_TYPE_SCHEMATIZED)) {
    return;
  }
  if (v8_flags.enable_etw_stack_walking &&
      (!filter_data || filter_data->Type != EVENT_FILTER_TYPE_SCHEMATIZED)) {
    etw_filter->clear();
    ETWTRACEDBG << "Enabling without filter" << std::endl;
    UpdateETWEnabled(is_etw_enabled_now, options);
    return;
  }
  // Ignore the callback if the --enable-etw-by-custom-filter-only flag is not
  // enabled.
  if (!v8_flags.enable_etw_by_custom_filter_only) return;
  // Validate custom filter data configured in a WPR profile and passed to the
  // callback.
  if (filter_data->Size <= sizeof(EVENT_FILTER_DESCRIPTOR)) {
    return; // Invalid data
  }
  EVENT_FILTER_HEADER* filter_event_header =
      reinterpret_cast<EVENT_FILTER_HEADER*>(filter_data->Ptr);
  if (filter_event_header->Size < sizeof(EVENT_FILTER_HEADER)) {
    return; // Invalid data
  }
  const uint8_t* payload_start =
      reinterpret_cast<uint8_t*>(filter_event_header) +
      sizeof(EVENT_FILTER_HEADER);
  const size_t payload_size =
      filter_event_header->Size - sizeof(EVENT_FILTER_HEADER);
  etw_filter->assign(payload_start, payload_start + payload_size);
  has_active_etw_tracing_session_or_custom_filter = true;
  ETWTRACEDBG << "Enabling with filter data" << std::endl;
  IsolateLoadScriptData::EnableLogWithFilterDataOnAllIsolates(
      reinterpret_cast<const uint8_t*>(etw_filter->data()), etw_filter->size(),
      options);
}
References v8::internal::DCHECK(), v8::internal::ETWJITInterface::IsolateLoadScriptData::EnableLogWithFilterDataOnAllIsolates(), etw_filter_payload_glob, ETWTRACEDBG, has_active_etw_tracing_session_or_custom_filter, kEtwControlCaptureState, kEtwRundown, v8::kJitCodeEventDefault, v8::kJitCodeEventEnumExisting, kJScriptRuntimeKeyword, kTraceLevel, UpdateETWEnabled(), and v8::internal::v8_flags.
Referenced by Register().
EventFields()
template<std::size_t count, typename... Ts>
constexpr auto v8::internal::ETWJITInterface::EventFields (char const (&) name[count], Ts... field_args) [constexpr]
Definition at line 133 of file etw-jit-metadata-win.h.
                                                                        {
  auto name_bytes = MakeStrBytes(name);
  auto fields = JoinFields(field_args...);
  auto data = JoinBytes(name_bytes, fields);
  auto header = Header(data.size);
  return JoinBytes(header, data);
}
References Header(), JoinBytes(), JoinFields(), MakeStrBytes(), and v8::internal::name.
Referenced by EventHandler().
EventHandler()
void v8::internal::ETWJITInterface::EventHandler (const JitCodeEvent * event)
Definition at line 207 of file etw-jit-win.cc.
                                             {
  v8::Isolate* script_context = event->isolate;
  Isolate* isolate = reinterpret_cast<Isolate*>(script_context);
  if (!isolate->IsETWTracingEnabled()) return;
  if (event->code_type != v8::JitCodeEvent::CodeType::JIT_CODE) return;
  if (event->type != v8::JitCodeEvent::EventType::CODE_ADDED) return;
  std::wstring method_name = GetScriptMethodName(event);
  // No heap allocations after this point.
  DisallowGarbageCollection no_gc;
  int script_id = 0;
  uint32_t script_line = -1;
  uint32_t script_column = -1;
  Tagged<SharedFunctionInfo> sfi = GetSharedFunctionInfo(event);
  if (!sfi.is_null() && IsScript(sfi->script())) {
    Tagged<Script> script = Cast<Script>(sfi->script());
    // if the first time seeing this source file, log the SourceLoad event
    script_id = script->id();
    if (IsolateLoadScriptData::MaybeAddLoadedScript(isolate, script_id)) {
      std::wstring wstr_name(0, L'\0');
      Tagged<Object> script_name = script->GetNameOrSourceURL();
      if (IsString(script_name)) {
        Tagged<String> v8str_name = Cast<String>(script_name);
        wstr_name.resize(v8str_name->length());
        // On Windows wchar_t == uint16_t. const_Cast needed for C++14.
        uint16_t* wstr_data = const_cast<uint16_t*>(
            reinterpret_cast<const uint16_t*>(wstr_name.data()));
        String::WriteToFlat(v8str_name, wstr_data, 0, v8str_name->length());
      }
      if (isolate->ETWIsInRundown()) {
        constexpr static auto source_dcstart_event_meta =
            EventMetadata(kSourceDCStartEventID, kJScriptRuntimeKeyword);
        constexpr static auto source_dcstart_event_fields =
            EventFields("SourceDCStart", Field("SourceID", TlgInUINT64),
                        Field("ScriptContextID", TlgInPOINTER),
                        Field("SourceFlags", TlgInUINT32),
                        Field("Url", TlgInUNICODESTRING));
        LogEventData(g_v8Provider, &source_dcstart_event_meta,
                     &source_dcstart_event_fields, (uint64_t)script_id,
                     script_context,
                     (uint32_t)0, // SourceFlags
                     wstr_name);
      } else {
        constexpr static auto source_load_event_meta =
            EventMetadata(kSourceLoadEventID, kJScriptRuntimeKeyword);
        constexpr static auto source_load_event_fields =
            EventFields("SourceLoad", Field("SourceID", TlgInUINT64),
                        Field("ScriptContextID", TlgInPOINTER),
                        Field("SourceFlags", TlgInUINT32),
                        Field("Url", TlgInUNICODESTRING));
        LogEventData(g_v8Provider, &source_load_event_meta,
                     &source_load_event_fields, (uint64_t)script_id,
                     script_context,
                     (uint32_t)0, // SourceFlags
                     wstr_name);
      }
    }
    Script::PositionInfo info;
    script->GetPositionInfo(sfi->StartPosition(), &info);
    script_line = info.line + 1;
    script_column = info.column + 1;
  }
  auto code =
      EtwIsolateOperations::Instance()->HeapGcSafeTryFindCodeForInnerPointer(
          isolate, Address(event->code_start));
  if (code && code.value()->is_builtin()) {
    bool skip_emitting_builtin = true;
    // Skip logging functions with code kind BUILTIN as they are already present
    // in the PDB.
    // We should still emit builtin addresses if they are an interpreter
    // trampoline.
    if (code.value()->has_instruction_stream()) {
      skip_emitting_builtin = false;
      // The only builtin that might have instruction stream is the
      // InterpreterEntryTrampoline builtin and only when the
      // v8_flags.interpreted_frames_native_stack flag is enabled.
      DCHECK_IMPLIES(
          code.value()->is_builtin(),
          code.value()->builtin_id() == Builtin::kInterpreterEntryTrampoline &&
              isolate->interpreted_frames_native_stack());
    } else {
      DCHECK(code.value()->is_builtin());
    }
    // If the builtin has been relocated, we still need to emit the address
    if (skip_emitting_builtin && V8_SHORT_BUILTIN_CALLS_BOOL &&
        v8_flags.short_builtin_calls) {
      CodeRange* code_range = isolate->isolate_group()->GetCodeRange();
      if (code_range && code_range->embedded_blob_code_copy() != nullptr) {
        skip_emitting_builtin = false;
      }
    }
    if (skip_emitting_builtin) {
      return;
    }
  }
  if (isolate->ETWIsInRundown()) {
    constexpr static auto method_dcstart_event_meta =
        EventMetadata(kMethodDCStartEventID, kJScriptRuntimeKeyword);
    constexpr static auto method_dcstart_event_fields = EventFields(
        "MethodDCStart", Field("ScriptContextID", TlgInPOINTER),
        Field("MethodStartAddress", TlgInPOINTER),
        Field("MethodSize", TlgInUINT64), Field("MethodID", TlgInUINT32),
        Field("MethodFlags", TlgInUINT16),
        Field("MethodAddressRangeID", TlgInUINT16),
        Field("SourceID", TlgInUINT64), Field("Line", TlgInUINT32),
        Field("Column", TlgInUINT32), Field("MethodName", TlgInUNICODESTRING));
    LogEventData(g_v8Provider, &method_dcstart_event_meta,
                 &method_dcstart_event_fields, script_context,
                 event->code_start, (uint64_t)event->code_len,
                 (uint32_t)0, // MethodId
                 (uint16_t)0, // MethodFlags
                 (uint16_t)0, // MethodAddressRangeId
                 (uint64_t)script_id, script_line, script_column, method_name);
  } else {
    constexpr static auto method_load_event_meta =
        EventMetadata(kMethodLoadEventID, kJScriptRuntimeKeyword);
    constexpr static auto method_load_event_fields = EventFields(
        "MethodLoad", Field("ScriptContextID", TlgInPOINTER),
        Field("MethodStartAddress", TlgInPOINTER),
        Field("MethodSize", TlgInUINT64), Field("MethodID", TlgInUINT32),
        Field("MethodFlags", TlgInUINT16),
        Field("MethodAddressRangeID", TlgInUINT16),
        Field("SourceID", TlgInUINT64), Field("Line", TlgInUINT32),
        Field("Column", TlgInUINT32), Field("MethodName", TlgInUNICODESTRING));
    LogEventData(g_v8Provider, &method_load_event_meta,
                 &method_load_event_fields, script_context, event->code_start,
                 (uint64_t)event->code_len,
                 (uint32_t)0, // MethodId
                 (uint16_t)0, // MethodFlags
                 (uint16_t)0, // MethodAddressRangeId
                 (uint64_t)script_id, script_line, script_column, method_name);
  }
}
References code, v8::JitCodeEvent::code_len, v8::JitCodeEvent::code_start, v8::JitCodeEvent::code_type, v8::internal::Script::PositionInfo::column, v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::CodeRange::embedded_blob_code_copy(), EventFields(), EventMetadata(), Field(), v8::internal::IsolateGroup::GetCodeRange(), GetScriptMethodName(), GetSharedFunctionInfo(), v8::internal::ETWJITInterface::EtwIsolateOperations::HeapGcSafeTryFindCodeForInnerPointer(), v8::internal::ETWJITInterface::EtwIsolateOperations::Instance(), v8::internal::Isolate::interpreted_frames_native_stack(), v8::internal::Tagged< HeapObject >::is_null(), v8::internal::Isolate::isolate_group(), kJScriptRuntimeKeyword, kMethodDCStartEventID, kMethodLoadEventID, kSourceDCStartEventID, kSourceLoadEventID, v8::internal::L, v8::internal::Script::PositionInfo::line, LogEventData(), v8::internal::ETWJITInterface::IsolateLoadScriptData::MaybeAddLoadedScript(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::script, v8::JitCodeEvent::type, v8::internal::v8_flags, V8_SHORT_BUILTIN_CALLS_BOOL, and v8::internal::String::WriteToFlat().
Referenced by v8::internal::V8FileLogger::SetUp().
EventMetadata()
constexpr auto v8::internal::ETWJITInterface::EventMetadata (uint16_t id, uint64_t keywords) [constexpr]
Definition at line 142 of file etw-jit-metadata-win.h.
                                                             {
  return EVENT_DESCRIPTOR{id,
                          0, // Version
                          kManifestFreeChannel,
                          kTraceLevel, // Level
                          EVENT_TRACE_TYPE_START, // Opcode
                          0, // Task
                          keywords};
}
References kManifestFreeChannel, and kTraceLevel.
Referenced by EventHandler().
Field()
template<size_t count>
constexpr auto v8::internal::ETWJITInterface::Field (char const (&) s[count], uint8_t type) [constexpr]
Definition at line 88 of file etw-jit-metadata-win.h.
                                                           {
  auto field_name = MakeStrBytes(s);
  const char type_arr[1] = {static_cast<char>(type)};
  return JoinBytes(field_name, MakeStrBytes(type_arr));
}
References JoinBytes(), MakeStrBytes(), and v8::internal::tracing::type.
Referenced by EventHandler().
GetScriptMethodName()
std::wstring v8::internal::ETWJITInterface::GetScriptMethodName (const JitCodeEvent * event)
Definition at line 95 of file etw-jit-win.cc.
                                                          {
  auto sfi = GetSharedFunctionInfo(event);
  return sfi.is_null() ? GetScriptMethodNameFromEvent(event)
                       : GetScriptMethodNameFromSharedFunctionInfo(sfi);
}
References GetScriptMethodNameFromEvent(), GetScriptMethodNameFromSharedFunctionInfo(), and GetSharedFunctionInfo().
Referenced by EventHandler().
GetScriptMethodNameFromEvent()
std::wstring v8::internal::ETWJITInterface::GetScriptMethodNameFromEvent (const JitCodeEvent * event)
Definition at line 72 of file etw-jit-win.cc.
                                                                   {
  int name_len = static_cast<int>(event->name.len);
  // Note: event->name.str is not null terminated.
  std::wstring method_name(name_len + 1, '\0');
  MultiByteToWideChar(
      CP_UTF8, 0, event->name.str, name_len,
      // Const cast needed as building with C++14 (not const in >= C++17)
      const_cast<LPWSTR>(method_name.data()),
      static_cast<int>(method_name.size()));
  return method_name;
}
References v8::JitCodeEvent::name, and v8::JitCodeEvent::name_t::str.
Referenced by GetScriptMethodName().
GetScriptMethodNameFromSharedFunctionInfo()
std::wstring v8::internal::ETWJITInterface::GetScriptMethodNameFromSharedFunctionInfo (Tagged< SharedFunctionInfo > sfi)
Definition at line 84 of file etw-jit-win.cc.
                                    {
  auto sfi_name = sfi->DebugNameCStr();
  int method_name_length = static_cast<int>(strlen(sfi_name.get()));
  std::wstring method_name(method_name_length, L'\0');
  MultiByteToWideChar(CP_UTF8, 0, sfi_name.get(), method_name_length,
                      const_cast<LPWSTR>(method_name.data()),
                      static_cast<int>(method_name.length()));
  return method_name;
}
References v8::internal::L.
Referenced by GetScriptMethodName().
GetSharedFunctionInfo()
Tagged<SharedFunctionInfo> v8::internal::ETWJITInterface::GetSharedFunctionInfo (const JitCodeEvent * event)
Definition at line 67 of file etw-jit-win.cc.
                                                                            {
  return event->script.IsEmpty() ? Tagged<SharedFunctionInfo>()
                                 : *Utils::OpenDirectHandle(*event->script);
}
References v8::Utils::OpenDirectHandle(), and v8::JitCodeEvent::script.
Referenced by EventHandler(), GetScriptMethodName(), and v8::Module::GetUnboundModuleScript().
Header()
constexpr auto v8::internal::ETWJITInterface::Header (size_t size) [constexpr]
Definition at line 96 of file etw-jit-metadata-win.h.
                                   {
  size_t total_size = size + 3; // total_size includes the 2 byte size + tag
  const char header_bytes[3] = {static_cast<char>(total_size & 0xFF),
                                static_cast<char>(total_size >> 8 & 0xFF),
                                '\0'};
  return MakeStrBytes(header_bytes);
}
References MakeStrBytes(), and size().
Referenced by v8::internal::PrimitiveArrayBase< Derived, ShapeT, Super >::DataSize(), EventFields(), and v8::internal::FixedIntegerArrayBase< T, Base >::OffsetOfElementAt().
JoinBytes()
template<std::size_t size1, std::size_t size2>
constexpr auto v8::internal::ETWJITInterface::JoinBytes (const str_bytes< size1 > & str1, const str_bytes< size2 > & str2) [constexpr]
Definition at line 79 of file etw-jit-metadata-win.h.
                                                       {
  auto idx1 = std::make_index_sequence<size1>();
  auto idx2 = std::make_index_sequence<size2>();
  return str_bytes<size1 + size2>{str1, idx1, str2, idx2};
}
Referenced by EventFields(), Field(), and JoinFields().
JoinFields() [1/3]
constexpr auto v8::internal::ETWJITInterface::JoinFields () [constexpr]
Definition at line 108 of file etw-jit-metadata-win.h.
{ return str_bytes<0>{}; }
Referenced by EventFields(), and JoinFields().
JoinFields() [2/3]
template<typename T1 >
constexpr auto v8::internal::ETWJITInterface::JoinFields (T1 field) [constexpr]
Definition at line 112 of file etw-jit-metadata-win.h.
                                    {
  return field;
}
JoinFields() [3/3]
template<typename T1 , typename T2 , typename... Ts>
constexpr auto v8::internal::ETWJITInterface::JoinFields (T1 field1, T2 field2, Ts... args) [constexpr]
Definition at line 118 of file etw-jit-metadata-win.h.
                                                            {
  auto bytes = JoinBytes(field1, field2);
  return JoinFields(bytes, args...);
}
References v8::base::args, JoinBytes(), and JoinFields().
LogEvent()
ULONG v8::internal::ETWJITInterface::LogEvent (uint64_t regHandle, const EVENT_DESCRIPTOR * event_descriptor, EVENT_DATA_DESCRIPTOR * data_descriptor, ULONG desc_count) [inline]
Definition at line 206 of file etw-jit-metadata-win.h.
                                        {
  if (regHandle == 0) return ERROR_SUCCESS;
  return EventWriteTransfer(regHandle, event_descriptor, NULL /* ActivityId */,
                            NULL /* RelatedActivityId */, desc_count,
                            data_descriptor);
}
Referenced by LogEventData().
LogEventData()
template<typename T , typename... Fs>
void v8::internal::ETWJITInterface::LogEventData (const TraceLoggingHProvider provider, const EVENT_DESCRIPTOR * event_descriptor, T * meta, const Fs &... fields)
Definition at line 218 of file etw-jit-metadata-win.h.
                                       {
  const size_t descriptor_count = sizeof...(fields) + kMetaDescriptorsCount;
  EVENT_DATA_DESCRIPTOR descriptors[sizeof...(fields) + kMetaDescriptorsCount];
  SetMetaDescriptors(descriptors, provider->ProviderMetadataPtr, meta->bytes,
                     meta->size);
  EVENT_DATA_DESCRIPTOR* data_descriptors = descriptors + kMetaDescriptorsCount;
  SetFieldDescriptors(data_descriptors, fields...);
  LogEvent(provider->RegHandle, event_descriptor, descriptors,
           descriptor_count);
}
References kMetaDescriptorsCount, LogEvent(), SetFieldDescriptors(), and SetMetaDescriptors().
Referenced by EventHandler().
MakeStrBytes()
template<size_t count, typename idx = std::make_index_sequence<count>>
constexpr auto v8::internal::ETWJITInterface::MakeStrBytes (char const (&) s[count]) [constexpr]
Definition at line 73 of file etw-jit-metadata-win.h.
                                                    {
  return str_bytes<count>{s, idx{}};
}
Referenced by EventFields(), Field(), and Header().
MaybeSetHandlerNow()
void v8::internal::ETWJITInterface::MaybeSetHandlerNow (Isolate * isolate)
Definition at line 46 of file etw-jit-win.cc.
                                          {
  DCHECK(v8_flags.enable_etw_stack_walking ||
         v8_flags.enable_etw_by_custom_filter_only);
  ETWTRACEDBG << "MaybeSetHandlerNow called" << std::endl;
  // Iterating read-only heap before sealed might not be safe.
  if (has_active_etw_tracing_session_or_custom_filter &&
      !EtwIsolateOperations::Instance()->HeapReadOnlySpaceWritable(isolate)) {
    if (etw_filter_payload_glob.Pointer()->empty()) {
      DCHECK(v8_flags.enable_etw_stack_walking);
      IsolateLoadScriptData::EnableLog(
          isolate, 0, std::weak_ptr<EtwIsolateCaptureStateMonitor>(),
          kJitCodeEventDefault);
    } else {
      IsolateLoadScriptData::EnableLogWithFilterData(
          isolate, 0, *etw_filter_payload_glob.Pointer(),
          std::weak_ptr<EtwIsolateCaptureStateMonitor>(), kJitCodeEventDefault);
    }
  }
}
References v8::internal::DCHECK(), v8::internal::ETWJITInterface::IsolateLoadScriptData::EnableLog(), v8::internal::ETWJITInterface::IsolateLoadScriptData::EnableLogWithFilterData(), etw_filter_payload_glob, ETWTRACEDBG, has_active_etw_tracing_session_or_custom_filter, v8::internal::ETWJITInterface::EtwIsolateOperations::Instance(), v8::kJitCodeEventDefault, and v8::internal::v8_flags.
Referenced by v8::internal::Isolate::Init(), and v8::Script::Run().
Register()
void v8::internal::ETWJITInterface::Register ()
Definition at line 187 of file etw-jit-win.cc.
                {
  DCHECK(!TraceLoggingProviderEnabled(g_v8Provider, 0, 0));
  TraceLoggingRegisterEx(g_v8Provider, ETWEnableCallback, nullptr);
}
References v8::internal::DCHECK(), and ETWEnableCallback().
Referenced by v8::internal::interpreter::Register::argument_count(), v8::internal::wasm::LiftoffAssembler::AtomicCompareExchange(), v8::internal::maglev::MaglevGraphBuilder::BuildRegisterFrameInitialization(), v8::internal::interpreter::Register::bytecode_array(), v8::internal::interpreter::Register::bytecode_offset(), v8::internal::maglev::RegisterFrameArray< T >::CopyFrom(), v8::internal::interpreter::Register::current_context(), v8::internal::maglev::RegisterFrameArray< T >::DataSize(), v8::internal::interpreter::InterpreterAssembler::ExportParametersAndRegisterFile(), v8::internal::interpreter::Register::feedback_vector(), v8::internal::interpreter::RegisterList::first_register(), v8::internal::maglev::CompactInterpreterFrameState::ForEachLocal(), v8::internal::interpreter::Register::FromOperand(), v8::internal::interpreter::Register::FromParameterIndex(), v8::internal::interpreter::Register::FromShortStar(), v8::internal::interpreter::Register::function_closure(), v8::internal::interpreter::InterpreterAssembler::ImportRegisterFile(), v8::internal::V8::Initialize(), v8::internal::V8::InitializePlatform(), v8::internal::interpreter::Register::invalid_value(), v8::internal::maglev::LazyDeoptInfo::IsResultRegister(), v8::internal::interpreter::BytecodeGenerator::AssignmentLhsData::KeyedSuperProperty(), v8::internal::interpreter::RegisterList::last_register(), v8::internal::interpreter::BytecodeArrayBuilder::Local(), v8::internal::interpreter::BytecodeGenerator::AssignmentLhsData::NamedProperty(), v8::internal::interpreter::BytecodeGenerator::AssignmentLhsData::NamedSuperProperty(), v8::internal::interpreter::BytecodeGenerator::AssignmentLhsData::NonProperty(), v8::internal::interpreter::RegisterList::operator[](), v8::internal::interpreter::BytecodeGenerator::AssignmentLhsData::PrivateDebugEvaluate(), v8::internal::compiler::BytecodeGraphBuilder::ProcessCallVarArgs(), v8::internal::CodeDataSource::Register(), v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterFromRegisterInfoTableIndex(), v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterListAllocateEvent(), v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterListFreeEvent(), v8::internal::interpreter::BytecodeArrayBuilder::RegisterListIsValid(), v8::internal::interpreter::InterpreterAssembler::StoreRegisterForShortStar(), v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateInLivenessForInOperand(), v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateInLivenessForOutOperand(), and v8::internal::interpreter::Register::virtual_accumulator().
RemoveIsolate()
void v8::internal::ETWJITInterface::RemoveIsolate (Isolate * isolate)
Definition at line 203 of file etw-jit-win.cc.
                                     {
  IsolateLoadScriptData::RemoveIsolate(isolate);
}
References v8::internal::ETWJITInterface::IsolateLoadScriptData::RemoveIsolate().
Referenced by v8::internal::Isolate::Deinit().
SetFieldDescriptors() [1/5]
void v8::internal::ETWJITInterface::SetFieldDescriptors (EVENT_DATA_DESCRIPTOR * data_descriptors) [inline]
Definition at line 157 of file etw-jit-metadata-win.h.
{}
Referenced by LogEventData(), and SetFieldDescriptors().
SetFieldDescriptors() [2/5]
template<typename... Ts>
void v8::internal::ETWJITInterface::SetFieldDescriptors (EVENT_DATA_DESCRIPTOR * data_descriptors, const char * value, const Ts &... rest)
Definition at line 198 of file etw-jit-metadata-win.h.
                                                               {
  ULONG size = static_cast<ULONG>(strlen(value) + 1);
  EventDataDescCreate(data_descriptors, value, size);
  SetFieldDescriptors(++data_descriptors, rest...);
}
References SetFieldDescriptors(), size(), and v8::internal::value.
SetFieldDescriptors() [3/5]
template<typename... Ts>
void v8::internal::ETWJITInterface::SetFieldDescriptors (EVENT_DATA_DESCRIPTOR * data_descriptors, const std::string & value, const Ts &... rest)
Definition at line 190 of file etw-jit-metadata-win.h.
                                                                    {
  EventDataDescCreate(data_descriptors, value.data(),
                      static_cast<ULONG>(value.size() + 1));
  SetFieldDescriptors(++data_descriptors, rest...);
}
References SetFieldDescriptors(), and v8::internal::value.
SetFieldDescriptors() [4/5]
template<typename... Ts>
void v8::internal::ETWJITInterface::SetFieldDescriptors (EVENT_DATA_DESCRIPTOR * data_descriptors, const std::wstring & value, const Ts &... rest)
Definition at line 182 of file etw-jit-metadata-win.h.
                                                                     {
  EventDataDescCreate(data_descriptors, value.data(),
                      static_cast<ULONG>(value.size() * 2 + 2));
  SetFieldDescriptors(++data_descriptors, rest...);
}
References SetFieldDescriptors(), and v8::internal::value.
SetFieldDescriptors() [5/5]
template<typename T , typename... Ts>
void v8::internal::ETWJITInterface::SetFieldDescriptors (EVENT_DATA_DESCRIPTOR * data_descriptors, const T & value, const Ts &... rest)
Definition at line 174 of file etw-jit-metadata-win.h.
                                                            {
  EventDataDescCreate(data_descriptors, &value, sizeof(value));
  SetFieldDescriptors(++data_descriptors, rest...);
}
References SetFieldDescriptors(), and v8::internal::value.
SetMetaDescriptors()
void v8::internal::ETWJITInterface::SetMetaDescriptors (EVENT_DATA_DESCRIPTOR * data_descriptor, UINT16 const UNALIGNED * traits, const void * metadata, size_t size)
Definition at line 11 of file etw-jit-metadata-win.cc.
                                     {
  // The first descriptor is the provider traits (just the name currently)
  uint16_t traits_size = *reinterpret_cast<const uint16_t*>(traits);
  EventDataDescCreate(data_descriptor, traits, traits_size);
  data_descriptor->Type = EVENT_DATA_DESCRIPTOR_TYPE_PROVIDER_METADATA;
  ++data_descriptor;
  // The second descriptor contains the data to describe the field layout
  EventDataDescCreate(data_descriptor, metadata, static_cast<ULONG>(size));
  data_descriptor->Type = EVENT_DATA_DESCRIPTOR_TYPE_EVENT_METADATA;
}
References size().
Referenced by LogEventData().
Unregister()
void v8::internal::ETWJITInterface::Unregister ()
Definition at line 192 of file etw-jit-win.cc.
                  {
  if (g_v8Provider) {
    TraceLoggingUnregister(g_v8Provider);
  }
  UpdateETWEnabled(false, kJitCodeEventDefault);
}
References v8::kJitCodeEventDefault, and UpdateETWEnabled().
Referenced by v8::internal::V8::DisposePlatform().
UpdateETWEnabled()
void v8::internal::ETWJITInterface::UpdateETWEnabled (bool enabled, uint32_t options)
Definition at line 101 of file etw-jit-win.cc.
                                                      {
  DCHECK(v8_flags.enable_etw_stack_walking ||
         v8_flags.enable_etw_by_custom_filter_only);
  has_active_etw_tracing_session_or_custom_filter = enabled;
  IsolateLoadScriptData::UpdateAllIsolates(enabled, options);
}
References v8::internal::DCHECK(), has_active_etw_tracing_session_or_custom_filter, v8::internal::ETWJITInterface::IsolateLoadScriptData::UpdateAllIsolates(), and v8::internal::v8_flags.
Referenced by ETWEnableCallback(), and Unregister().
V8_DECLARE_TRACELOGGING_PROVIDER()
v8::internal::ETWJITInterface::V8_DECLARE_TRACELOGGING_PROVIDER (g_v8Provider)
V8_DEFINE_TRACELOGGING_PROVIDER()
v8::internal::ETWJITInterface::V8_DEFINE_TRACELOGGING_PROVIDER (g_v8Provider)
Variable Documentation
etw_filter_payload_glob
base::LazyInstance< FilterDataType >::type v8::internal::ETWJITInterface::etw_filter_payload_glob
Initial value:
=
    LAZY_INSTANCE_INITIALIZER
Definition at line 313 of file etw-isolate-load-script-data-win.cc.
Referenced by ETWEnableCallback(), and MaybeSetHandlerNow().
has_active_etw_tracing_session_or_custom_filter
V8_EXPORT_PRIVATE std::atomic< bool > v8::internal::ETWJITInterface::has_active_etw_tracing_session_or_custom_filter = false
Definition at line 44 of file etw-jit-win.cc.
Referenced by ETWEnableCallback(), MaybeSetHandlerNow(), and UpdateETWEnabled().
isolate_map
base::LazyInstance< IsolateMapType >::type v8::internal::ETWJITInterface::isolate_map
Initial value:
=
    LAZY_INSTANCE_INITIALIZER
Definition at line 311 of file etw-isolate-load-script-data-win.cc.
Referenced by v8::internal::ETWJITInterface::IsolateLoadScriptData::AddIsolate(), v8::internal::ETWJITInterface::IsolateLoadScriptData::EnableLogWithFilterDataOnAllIsolates(), v8::internal::ETWJITInterface::IsolateLoadScriptData::GetData(), v8::internal::FutexEmulation::IsolateDeinit(), v8::internal::FutexEmulation::NotifyAsyncWaiter(), v8::internal::FutexEmulation::NumUnresolvedAsyncPromisesForTesting(), v8::internal::ETWJITInterface::IsolateLoadScriptData::RemoveIsolate(), v8::internal::FutexEmulation::ResolveAsyncWaiterPromises(), and v8::internal::ETWJITInterface::IsolateLoadScriptData::UpdateAllIsolates().
isolates_mutex
base::LazyMutex v8::internal::ETWJITInterface::isolates_mutex = LAZY_MUTEX_INITIALIZER
Definition at line 310 of file etw-isolate-load-script-data-win.cc.
Referenced by v8::internal::ETWJITInterface::IsolateLoadScriptData::AddIsolate(), v8::internal::ETWJITInterface::IsolateLoadScriptData::DisableLog(), v8::internal::ETWJITInterface::IsolateLoadScriptData::EnableLog(), v8::internal::ETWJITInterface::IsolateLoadScriptData::EnableLogWithFilterData(), v8::internal::ETWJITInterface::IsolateLoadScriptData::EnableLogWithFilterDataOnAllIsolates(), v8::internal::ETWJITInterface::IsolateLoadScriptData::MaybeAddLoadedScript(), v8::internal::ETWJITInterface::IsolateLoadScriptData::RemoveIsolate(), and v8::internal::ETWJITInterface::IsolateLoadScriptData::UpdateAllIsolates().
kCaptureStateTimeout
constexpr auto v8::internal::ETWJITInterface::kCaptureStateTimeout = base::TimeDelta::FromSeconds(10) [constexpr]
Definition at line 39 of file etw-isolate-load-script-data-win.cc.
Referenced by v8::internal::ETWJITInterface::IsolateLoadScriptData::EnableLogWithFilterDataOnAllIsolates().
kEtwControlCaptureState
constexpr uint32_t v8::internal::ETWJITInterface::kEtwControlCaptureState = 2 [constexpr]
Definition at line 33 of file etw-jit-metadata-win.h.
Referenced by ETWEnableCallback().
kEtwControlDisable
constexpr uint32_t v8::internal::ETWJITInterface::kEtwControlDisable = 0 [constexpr]
Definition at line 31 of file etw-jit-metadata-win.h.
kEtwControlEnable
constexpr uint32_t v8::internal::ETWJITInterface::kEtwControlEnable = 1 [constexpr]
Definition at line 32 of file etw-jit-metadata-win.h.
kEtwRundown
constexpr uint32_t v8::internal::ETWJITInterface::kEtwRundown = 0xf0000000 [constexpr]
Definition at line 27 of file etw-jit-win.h.
Referenced by ETWEnableCallback().
kJScriptRuntimeKeyword
constexpr uint64_t v8::internal::ETWJITInterface::kJScriptRuntimeKeyword = 1 [constexpr]
Definition at line 36 of file etw-jit-metadata-win.h.
Referenced by ETWEnableCallback(), and EventHandler().
kManifestFreeChannel
const uint8_t v8::internal::ETWJITInterface::kManifestFreeChannel = 11
Definition at line 23 of file etw-jit-metadata-win.h.
Referenced by EventMetadata().
kMetaDescriptorsCount
const uint8_t v8::internal::ETWJITInterface::kMetaDescriptorsCount = 2
Definition at line 27 of file etw-jit-metadata-win.h.
Referenced by LogEventData().
kMethodDCStartEventID
constexpr uint16_t v8::internal::ETWJITInterface::kMethodDCStartEventID = 5 [constexpr]
Definition at line 41 of file etw-jit-metadata-win.h.
Referenced by EventHandler().
kMethodLoadEventID
constexpr uint16_t v8::internal::ETWJITInterface::kMethodLoadEventID = 9 [constexpr]
Definition at line 39 of file etw-jit-metadata-win.h.
Referenced by EventHandler().
kSourceDCStartEventID
constexpr uint16_t v8::internal::ETWJITInterface::kSourceDCStartEventID = 39 [constexpr]
Definition at line 40 of file etw-jit-metadata-win.h.
Referenced by EventHandler().
kSourceLoadEventID
constexpr uint16_t v8::internal::ETWJITInterface::kSourceLoadEventID = 41 [constexpr]
Definition at line 38 of file etw-jit-metadata-win.h.
Referenced by EventHandler().
kTraceLevel
constexpr unsigned char v8::internal::ETWJITInterface::kTraceLevel = TRACE_LEVEL_INFORMATION [constexpr]
Definition at line 43 of file etw-jit-metadata-win.h.
Referenced by ETWEnableCallback(), and EventMetadata().