cppgc::internal::anonymous_namespace{compactor.cc} Namespace Reference
Classes
class MovableReferences
class CompactionState
Functions
void CompactPage (NormalPage *page, CompactionState &compaction_state, StickyBits sticky_bits)
void CompactSpace (NormalPageSpace *space, MovableReferences &movable_references, StickyBits sticky_bits)
size_t UpdateHeapResidency (const std::vector< NormalPageSpace * > &spaces)
Variables
static constexpr size_t kFreeListSizeThreshold = 512 * kKB
Function Documentation
CompactPage()
void cppgc::internal::anonymous_namespace{compactor.cc}::CompactPage (NormalPage * page, CompactionState & compaction_state, StickyBits sticky_bits)
Definition at line 335 of file compactor.cc.
                                         {
  compaction_state.AddPage(page);
  page->object_start_bitmap().Clear();
  for (Address header_address = page->PayloadStart();
       header_address < page->PayloadEnd();) {
    HeapObjectHeader* header =
        reinterpret_cast<HeapObjectHeader*>(header_address);
    size_t size = header->AllocatedSize();
    DCHECK_GT(size, 0u);
    DCHECK_LT(size, kPageSize);
    if (header->IsFree()) {
      // Unpoison the freelist entry so that we can compact into it as wanted.
      ASAN_UNPOISON_MEMORY_REGION(header_address, size);
      header_address += size;
      continue;
    }
    if (!header->IsMarked()) {
      // Compaction is currently launched only from AtomicPhaseEpilogue, so it's
      // guaranteed to be on the mutator thread - no need to postpone
      // finalization.
      header->Finalize();
      // As compaction is under way, leave the freed memory accessible
      // while compacting the rest of the page. We just zap the payload
      // to catch out other finalizers trying to access it.
#if DEBUG || defined(V8_USE_MEMORY_SANITIZER) || \
    defined(V8_USE_ADDRESS_SANITIZER)
      ZapMemory(header, size);
#endif
      header_address += size;
      continue;
    }
    // Object is marked.
#if defined(CPPGC_YOUNG_GENERATION)
    if (sticky_bits == StickyBits::kDisabled) header->Unmark();
#else // !defined(CPPGC_YOUNG_GENERATION)
    header->Unmark();
#endif // !defined(CPPGC_YOUNG_GENERATION)
    // Potentially unpoison the live object as well as it is the source of
    // the copy.
    ASAN_UNPOISON_MEMORY_REGION(header->ObjectStart(), header->ObjectSize());
    compaction_state.RelocateObject(page, header_address, size);
    header_address += size;
  }
  compaction_state.FinishCompactingPage(page);
}
References cppgc::internal::anonymous_namespace{compactor.cc}::CompactionState::AddPage(), cppgc::internal::HeapObjectHeader::AllocatedSize(), ASAN_UNPOISON_MEMORY_REGION, cppgc::internal::ObjectStartBitmap::Clear(), DCHECK_GT, DCHECK_LT, cppgc::internal::HeapObjectHeader::Finalize(), cppgc::internal::anonymous_namespace{compactor.cc}::CompactionState::FinishCompactingPage(), cppgc::internal::HeapObjectHeader::IsFree(), cppgc::internal::HeapObjectHeader::IsMarked(), cppgc::internal::kDisabled, cppgc::internal::kPageSize, cppgc::internal::NormalPage::object_start_bitmap(), cppgc::internal::HeapObjectHeader::ObjectSize(), cppgc::internal::HeapObjectHeader::ObjectStart(), cppgc::internal::NormalPage::PayloadStart(), cppgc::internal::anonymous_namespace{compactor.cc}::CompactionState::RelocateObject(), size(), cppgc::internal::HeapObjectHeader::Unmark(), and cppgc::internal::ZapMemory().
Referenced by CompactSpace().
CompactSpace()
void cppgc::internal::anonymous_namespace{compactor.cc}::CompactSpace (NormalPageSpace * space, MovableReferences & movable_references, StickyBits sticky_bits)
Definition at line 390 of file compactor.cc.
                                          {
  using Pages = NormalPageSpace::Pages;
#ifdef V8_USE_ADDRESS_SANITIZER
  UnmarkedObjectsPoisoner().Traverse(*space);
#endif // V8_USE_ADDRESS_SANITIZER
  DCHECK(space->is_compactable());
  space->free_list().Clear();
  // Compaction generally follows Jonker's algorithm for fast garbage
  // compaction. Compaction is performed in-place, sliding objects down over
  // unused holes for a smaller heap page footprint and improved locality. A
  // "compaction pointer" is consequently kept, pointing to the next available
  // address to move objects down to. It will belong to one of the already
  // compacted pages for this space, but as compaction proceeds, it will not
  // belong to the same page as the one being currently compacted.
  //
  // The compaction pointer is represented by the
  // |(current_page_, used_bytes_in_current_page_)| pair, with
  // |used_bytes_in_current_page_| being the offset into |current_page_|, making
  // up the next available location. When the compaction of an arena page causes
  // the compaction pointer to exhaust the current page it is compacting into,
  // page compaction will advance the current page of the compaction
  // pointer, as well as the allocation point.
  //
  // By construction, the page compaction can be performed without having
  // to allocate any new pages. So to arrange for the page compaction's
  // supply of freed, available pages, we chain them together after each
  // has been "compacted from". The page compaction will then reuse those
  // as needed, and once finished, the chained, available pages can be
  // released back to the OS.
  //
  // To ease the passing of the compaction state when iterating over an
  // arena's pages, package it up into a |CompactionState|.
  Pages pages = space->RemoveAllPages();
  if (pages.empty()) return;
  CompactionState compaction_state(space, movable_references);
  for (BasePage* page : pages) {
    page->ResetMarkedBytes();
    // Large objects do not belong to this arena.
    CompactPage(NormalPage::From(page), compaction_state, sticky_bits);
  }
  compaction_state.FinishCompactingSpace();
  // Sweeping will verify object start bitmap of compacted space.
}
References CompactPage(), DCHECK, cppgc::internal::anonymous_namespace{compactor.cc}::CompactionState::FinishCompactingSpace(), cppgc::internal::NormalPage::From(), and space.
Referenced by cppgc::internal::Compactor::CompactSpacesIfEnabled().
UpdateHeapResidency()
size_t cppgc::internal::anonymous_namespace{compactor.cc}::UpdateHeapResidency (const std::vector< NormalPageSpace * > & spaces)
Definition at line 442 of file compactor.cc.
                                                                      {
  return std::accumulate(spaces.cbegin(), spaces.cend(), 0u,
                         [](size_t acc, const NormalPageSpace* space) {
                           DCHECK(space->is_compactable());
                           if (!space->size()) return acc;
                           return acc + space->free_list().Size();
                         });
}
References space.
Referenced by cppgc::internal::Compactor::ShouldCompact().
Variable Documentation
kFreeListSizeThreshold
constexpr size_t cppgc::internal::anonymous_namespace{compactor.cc}::kFreeListSizeThreshold = 512 * kKB [static], [constexpr]
Definition at line 29 of file compactor.cc.
Referenced by cppgc::internal::Compactor::ShouldCompact().