v8::internal::anonymous_namespace{mark-compact.cc} Namespace Reference
Classes
class ParallelClearingJob
class ClearStringTableJobItem
class SharedStructTypeRegistryCleaner
class ClearSharedStructTypeRegistryJobItem
class RememberedSetUpdatingItem
Enumerations
enum class MemoryReductionMode { kNone
, kShouldReduceMemory
 }
Functions
int NumberOfAvailableCores ()
int NumberOfParallelCompactionTasks (Heap *heap)
base::EnumSet< CodeFlushMode > GetCodeFlushMode (Isolate *isolate)
void ShrinkPagesToObjectSizes (Heap *heap, OldLargeObjectSpace *space)
bool ShouldRetainMap (Heap *heap, MarkingState *marking_state, Tagged< Map > map, int age)
template<typename TSlot , HeapObjectReferenceType reference_type>
TSlot::TObject MakeSlotValue (Tagged< HeapObject > heap_object)
template<> Tagged< Object > MakeSlotValue< ObjectSlot, HeapObjectReferenceType::STRONG > (Tagged< HeapObject > heap_object)
template<> Tagged< MaybeObject > MakeSlotValue< MaybeObjectSlot, HeapObjectReferenceType::STRONG > (Tagged< HeapObject > heap_object)
template<> Tagged< MaybeObject > MakeSlotValue< MaybeObjectSlot, HeapObjectReferenceType::WEAK > (Tagged< HeapObject > heap_object)
template<> Tagged< Object > MakeSlotValue< OffHeapObjectSlot, HeapObjectReferenceType::STRONG > (Tagged< HeapObject > heap_object)
template<HeapObjectReferenceType reference_type, typename TSlot >
static void UpdateSlot (PtrComprCageBase cage_base, TSlot slot, Tagged< HeapObject > heap_obj)
template<typename TSlot >
static void UpdateSlot (PtrComprCageBase cage_base, TSlot slot)
template<typename TSlot >
static SlotCallbackResult UpdateOldToSharedSlot (PtrComprCageBase cage_base, TSlot slot)
template<typename TSlot >
static void UpdateStrongSlot (PtrComprCageBase cage_base, TSlot slot)
static SlotCallbackResult UpdateStrongOldToSharedSlot (PtrComprCageBase cage_base, FullMaybeObjectSlot slot)
static void UpdateStrongCodeSlot (IsolateForSandbox isolate, PtrComprCageBase cage_base, PtrComprCageBase code_cage_base, InstructionStreamSlot slot)
size_t CreateAndExecuteEvacuationTasks (Heap *heap, MarkCompactCollector *collector, std::vector< std::pair< ParallelWorkItem, MutablePageMetadata * >> evacuation_items)
intptr_t NewSpacePageEvacuationThreshold ()
bool ShouldMovePage (PageMetadata *p, intptr_t live_bytes, MemoryReductionMode memory_reduction_mode)
void TraceEvacuation (Isolate *isolate, size_t pages_count, size_t wanted_num_tasks, size_t live_bytes, size_t aborted_pages)
template<typename IterateableSpace >
void CollectRememberedSetUpdatingItems (std::vector< std::unique_ptr< UpdatingItem >> *items, IterateableSpace *space)
void ReRecordPage (Heap *heap, Address failed_start, PageMetadata *page)
bool ShouldPostponeFreeingEmptyPages (LargeObjectSpace *space)
Variables
constexpr size_t kDeadlineCheckInterval = 128u
Enumeration Type Documentation
MemoryReductionMode
enum v8::internal::anonymous_namespace{mark-compact.cc}::MemoryReductionMode [strong]
Enumerator
kNone
kShouldReduceMemory
Definition at line 4802 of file mark-compact.cc.
{ kNone, kShouldReduceMemory };
Function Documentation
CollectRememberedSetUpdatingItems()
template<typename IterateableSpace >
void v8::internal::anonymous_namespace{mark-compact.cc}::CollectRememberedSetUpdatingItems (std::vector< std::unique_ptr< UpdatingItem >> * items, IterateableSpace * space)
Definition at line 5553 of file mark-compact.cc.
                             {
  for (MutablePageMetadata* page : *space) {
    // No need to update pointers on evacuation candidates. Evacuated pages will
    // be released after this phase.
    if (page->Chunk()->IsEvacuationCandidate()) continue;
    if (page->ContainsAnySlots()) {
      items->emplace_back(
          std::make_unique<RememberedSetUpdatingItem>(space->heap(), page));
    }
  }
}
References space.
Referenced by v8::internal::MarkCompactCollector::UpdatePointersAfterEvacuation().
CreateAndExecuteEvacuationTasks()
size_t v8::internal::anonymous_namespace{mark-compact.cc}::CreateAndExecuteEvacuationTasks (Heap * heap, MarkCompactCollector * collector, std::vector< std::pair< ParallelWorkItem, MutablePageMetadata * >> evacuation_items)
Definition at line 4770 of file mark-compact.cc.
                          {
  std::optional<ProfilingMigrationObserver> profiling_observer;
  if (heap->isolate()->log_object_relocation()) {
    profiling_observer.emplace(heap);
  }
  std::vector<std::unique_ptr<v8::internal::Evacuator>> evacuators;
  const int wanted_num_tasks = NumberOfParallelCompactionTasks(heap);
  for (int i = 0; i < wanted_num_tasks; i++) {
    auto evacuator = std::make_unique<Evacuator>(heap);
    if (profiling_observer) {
      evacuator->AddObserver(&profiling_observer.value());
    }
    evacuators.push_back(std::move(evacuator));
  }
  auto page_evacuation_job = std::make_unique<PageEvacuationJob>(
      heap->isolate(), collector, &evacuators, std::move(evacuation_items));
  TRACE_GC_NOTE_WITH_FLOW("PageEvacuationJob started",
                          page_evacuation_job->trace_id(),
                          TRACE_EVENT_FLAG_FLOW_OUT);
  V8::GetCurrentPlatform()
      ->CreateJob(v8::TaskPriority::kUserBlocking,
                  std::move(page_evacuation_job))
      ->Join();
  for (auto& evacuator : evacuators) {
    evacuator->Finalize();
  }
  return wanted_num_tasks;
}
References v8::Platform::CreateJob(), v8::debug::GetCurrentPlatform(), v8::kUserBlocking, NumberOfParallelCompactionTasks(), TRACE_EVENT_FLAG_FLOW_OUT, and TRACE_GC_NOTE_WITH_FLOW.
Referenced by v8::internal::MarkCompactCollector::EvacuatePagesInParallel().
GetCodeFlushMode()
base::EnumSet<CodeFlushMode> v8::internal::anonymous_namespace{mark-compact.cc}::GetCodeFlushMode (Isolate * isolate)
Definition at line 372 of file mark-compact.cc.
                                                              {
  if (isolate->disable_bytecode_flushing()) {
    return base::EnumSet<CodeFlushMode>();
  }
  base::EnumSet<CodeFlushMode> code_flush_mode;
  if (v8_flags.flush_bytecode) {
    code_flush_mode.Add(CodeFlushMode::kFlushBytecode);
  }
  if (v8_flags.flush_baseline_code) {
    code_flush_mode.Add(CodeFlushMode::kFlushBaselineCode);
  }
  if (v8_flags.stress_flush_code) {
    // This is to check tests accidentally don't miss out on adding either flush
    // bytecode or flush code along with stress flush code. stress_flush_code
    // doesn't do anything if either one of them isn't enabled.
    DCHECK(v8_flags.fuzzing || v8_flags.flush_baseline_code ||
           v8_flags.flush_bytecode);
    code_flush_mode.Add(CodeFlushMode::kForceFlush);
  }
  if (isolate->heap()->IsLastResortGC() &&
      (v8_flags.flush_code_based_on_time ||
       v8_flags.flush_code_based_on_tab_visibility)) {
    code_flush_mode.Add(CodeFlushMode::kForceFlush);
  }
  return code_flush_mode;
}
References v8::base::EnumSet< E, T >::Add(), v8::internal::DCHECK(), v8::internal::Isolate::heap(), v8::internal::Heap::IsLastResortGC(), v8::internal::kFlushBaselineCode, v8::internal::kFlushBytecode, v8::internal::kForceFlush, and v8::internal::v8_flags.
Referenced by v8::internal::MarkCompactCollector::StartMarking().
MakeSlotValue()
template<typename TSlot , HeapObjectReferenceType reference_type>
TSlot::TObject v8::internal::anonymous_namespace{mark-compact.cc}::MakeSlotValue (Tagged< HeapObject > heap_object)
MakeSlotValue< MaybeObjectSlot, HeapObjectReferenceType::STRONG >()
template<>
Tagged<MaybeObject> v8::internal::anonymous_namespace{mark-compact.cc}::MakeSlotValue< MaybeObjectSlot, HeapObjectReferenceType::STRONG > (Tagged< HeapObject > heap_object)
Definition at line 4086 of file mark-compact.cc.
                                    {
  return heap_object;
}
MakeSlotValue< MaybeObjectSlot, HeapObjectReferenceType::WEAK >()
template<>
Tagged<MaybeObject> v8::internal::anonymous_namespace{mark-compact.cc}::MakeSlotValue< MaybeObjectSlot, HeapObjectReferenceType::WEAK > (Tagged< HeapObject > heap_object)
Definition at line 4086 of file mark-compact.cc.
                                    {
  return MakeWeak(heap_object);
}
MakeSlotValue< ObjectSlot, HeapObjectReferenceType::STRONG >()
template<>
Tagged<Object> v8::internal::anonymous_namespace{mark-compact.cc}::MakeSlotValue< ObjectSlot, HeapObjectReferenceType::STRONG > (Tagged< HeapObject > heap_object)
Definition at line 4086 of file mark-compact.cc.
                                    {
  return heap_object;
}
MakeSlotValue< OffHeapObjectSlot, HeapObjectReferenceType::STRONG >()
template<>
Tagged<Object> v8::internal::anonymous_namespace{mark-compact.cc}::MakeSlotValue< OffHeapObjectSlot, HeapObjectReferenceType::STRONG > (Tagged< HeapObject > heap_object)
Definition at line 4086 of file mark-compact.cc.
                                    {
  return heap_object;
}
NewSpacePageEvacuationThreshold()
intptr_t v8::internal::anonymous_namespace{mark-compact.cc}::NewSpacePageEvacuationThreshold ()
Definition at line 4806 of file mark-compact.cc.
                                           {
  return v8_flags.page_promotion_threshold *
         MemoryChunkLayout::AllocatableMemoryInDataPage() / 100;
}
References v8::internal::v8_flags.
Referenced by ShouldMovePage().
NumberOfAvailableCores()
int v8::internal::anonymous_namespace{mark-compact.cc}::NumberOfAvailableCores ()
Definition at line 229 of file mark-compact.cc.
                             {
  static int num_cores = V8::GetCurrentPlatform()->NumberOfWorkerThreads() + 1;
  // This number of cores should be greater than zero and never change.
  DCHECK_GE(num_cores, 1);
  DCHECK_EQ(num_cores, V8::GetCurrentPlatform()->NumberOfWorkerThreads() + 1);
  return num_cores;
}
References DCHECK_EQ, DCHECK_GE, v8::internal::V8::GetCurrentPlatform(), and v8::Platform::NumberOfWorkerThreads().
Referenced by NumberOfParallelCompactionTasks().
NumberOfParallelCompactionTasks()
int v8::internal::anonymous_namespace{mark-compact.cc}::NumberOfParallelCompactionTasks (Heap * heap)
Definition at line 237 of file mark-compact.cc.
                                                {
  int tasks = v8_flags.parallel_compaction ? NumberOfAvailableCores() : 1;
  if (!heap->CanPromoteYoungAndExpandOldGeneration(
          static_cast<size_t>(tasks * PageMetadata::kPageSize))) {
    // Optimize for memory usage near the heap limit.
    tasks = 1;
  }
  return tasks;
}
References v8::internal::MutablePageMetadata::kPageSize, NumberOfAvailableCores(), and v8::internal::v8_flags.
Referenced by CreateAndExecuteEvacuationTasks().
ReRecordPage()
void v8::internal::anonymous_namespace{mark-compact.cc}::ReRecordPage (Heap * heap, Address failed_start, PageMetadata * page)
Definition at line 5891 of file mark-compact.cc.
                                                                        {
  DCHECK(page->Chunk()->IsFlagSet(MemoryChunk::COMPACTION_WAS_ABORTED));
  // Aborted compaction page. We have to record slots here, since we
  // might not have recorded them in first place.
  // Remove mark bits in evacuated area.
  page->marking_bitmap()->ClearRange<AccessMode::NON_ATOMIC>(
      MarkingBitmap::AddressToIndex(page->area_start()),
      MarkingBitmap::LimitAddressToIndex(failed_start));
  // Remove outdated slots.
  RememberedSet<OLD_TO_NEW>::RemoveRange(page, page->area_start(), failed_start,
                                         SlotSet::FREE_EMPTY_BUCKETS);
  RememberedSet<OLD_TO_NEW>::RemoveRangeTyped(page, page->area_start(),
                                              failed_start);
  RememberedSet<OLD_TO_NEW_BACKGROUND>::RemoveRange(
      page, page->area_start(), failed_start, SlotSet::FREE_EMPTY_BUCKETS);
  DCHECK_NULL(page->typed_slot_set<OLD_TO_NEW_BACKGROUND>());
  RememberedSet<OLD_TO_SHARED>::RemoveRange(
      page, page->area_start(), failed_start, SlotSet::FREE_EMPTY_BUCKETS);
  RememberedSet<OLD_TO_SHARED>::RemoveRangeTyped(page, page->area_start(),
                                                 failed_start);
  // Re-record slots and recompute live bytes.
  EvacuateRecordOnlyVisitor visitor(heap);
  LiveObjectVisitor::VisitMarkedObjectsNoFail(page, &visitor);
  page->SetLiveBytes(visitor.live_object_size());
  // Array buffers will be processed during pointer updating.
}
References v8::internal::MemoryChunkMetadata::area_start(), v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::MarkingBitmap::ClearRange(), DCHECK, DCHECK_NULL, v8::internal::MemoryChunk::IsFlagSet(), v8::internal::EvacuateRecordOnlyVisitor::live_object_size(), v8::internal::MutablePageMetadata::marking_bitmap(), v8::internal::OLD_TO_NEW_BACKGROUND, v8::internal::MutablePageMetadata::SetLiveBytes(), and v8::internal::MutablePageMetadata::typed_slot_set().
Referenced by v8::internal::MarkCompactCollector::PostProcessAbortedEvacuationCandidates().
ShouldMovePage()
bool v8::internal::anonymous_namespace{mark-compact.cc}::ShouldMovePage (PageMetadata * p, intptr_t live_bytes, MemoryReductionMode memory_reduction_mode)
Definition at line 4811 of file mark-compact.cc.
                                                               {
  Heap* heap = p->heap();
  DCHECK(!p->Chunk()->NeverEvacuate());
  const bool should_move_page =
      v8_flags.page_promotion &&
      (memory_reduction_mode == MemoryReductionMode::kNone) &&
      (live_bytes > NewSpacePageEvacuationThreshold()) &&
      heap->CanExpandOldGeneration(live_bytes);
  if (v8_flags.trace_page_promotions) {
    PrintIsolate(heap->isolate(),
                 "[Page Promotion] %p: collector=mc, should move: %d"
                 ", live bytes = %zu, promotion threshold = %zu"
                 ", allocated labs size = %zu\n",
                 p, should_move_page, live_bytes,
                 NewSpacePageEvacuationThreshold(), p->AllocatedLabSize());
  }
  return should_move_page;
}
References v8::internal::MutablePageMetadata::AllocatedLabSize(), v8::internal::MemoryChunkMetadata::Chunk(), DCHECK, v8::internal::MemoryChunkMetadata::heap(), v8::internal::MemoryChunk::NeverEvacuate(), NewSpacePageEvacuationThreshold(), v8::internal::PrintIsolate(), and v8::internal::v8_flags.
Referenced by v8::internal::MarkCompactCollector::EvacuatePagesInParallel().
ShouldPostponeFreeingEmptyPages()
bool v8::internal::anonymous_namespace{mark-compact.cc}::ShouldPostponeFreeingEmptyPages (LargeObjectSpace * space)
Definition at line 6107 of file mark-compact.cc.
                                                              {
  // Delay releasing dead old large object pages until after pointer updating is
  // done because dead old space objects may have old-to-new slots (which
  // were possibly later overriden with old-to-old references) that are
  // pointing to these pages and will need to be updated.
  if (space->identity() == LO_SPACE) return true;
  // Old-to-new slots may also point to shared spaces. Delay releasing so that
  // updating slots in dead old objects can access the dead shared objects.
  if (space->identity() == SHARED_LO_SPACE) return true;
  return false;
}
References v8::internal::LO_SPACE, v8::internal::SHARED_LO_SPACE, and space.
Referenced by v8::internal::MarkCompactCollector::SweepLargeSpace().
ShouldRetainMap()
bool v8::internal::anonymous_namespace{mark-compact.cc}::ShouldRetainMap (Heap * heap, MarkingState * marking_state, Tagged< Map > map, int age)
Definition at line 2409 of file mark-compact.cc.
                              {
  if (age == 0) {
    // The map has aged. Do not retain this map.
    return false;
  }
  Tagged<Object> constructor = map->GetConstructor();
  if (!IsHeapObject(constructor) ||
      MarkingHelper::IsUnmarkedAndNotAlwaysLive(
          heap, marking_state, Cast<HeapObject>(constructor))) {
    // The constructor is dead, no new objects with this map can
    // be created. Do not retain this map.
    return false;
  }
  return true;
}
References v8::internal::InstanceTypeChecker::IsHeapObject().
Referenced by v8::internal::MarkCompactCollector::RetainMaps().
ShrinkPagesToObjectSizes()
void v8::internal::anonymous_namespace{mark-compact.cc}::ShrinkPagesToObjectSizes (Heap * heap, OldLargeObjectSpace * space)
Definition at line 834 of file mark-compact.cc.
                                                                      {
  size_t surviving_object_size = 0;
  PtrComprCageBase cage_base(heap->isolate());
  for (auto it = space->begin(); it != space->end();) {
    LargePageMetadata* current = *(it++);
    Tagged<HeapObject> object = current->GetObject();
    const size_t object_size = static_cast<size_t>(object->Size(cage_base));
    space->ShrinkPageToObjectSize(current, object, object_size);
    surviving_object_size += object_size;
  }
  space->set_objects_size(surviving_object_size);
}
References v8::internal::LargePageMetadata::GetObject(), and space.
Referenced by v8::internal::MarkCompactCollector::Finish().
TraceEvacuation()
void v8::internal::anonymous_namespace{mark-compact.cc}::TraceEvacuation (Isolate * isolate, size_t pages_count, size_t wanted_num_tasks, size_t live_bytes, size_t aborted_pages)
Definition at line 4831 of file mark-compact.cc.
                                           {
  DCHECK(v8_flags.trace_evacuation);
  PrintIsolate(isolate,
               "%8.0f ms: evacuation-summary: parallel=%s pages=%zu "
               "wanted_tasks=%zu cores=%d live_bytes=%" V8PRIdPTR
               " compaction_speed=%.f aborted=%zu\n",
               isolate->time_millis_since_init(),
               v8_flags.parallel_compaction ? "yes" : "no", pages_count,
               wanted_num_tasks,
               V8::GetCurrentPlatform()->NumberOfWorkerThreads() + 1,
               live_bytes,
               isolate->heap()
                   ->tracer()
                   ->CompactionSpeedInBytesPerMillisecond()
                   .value_or(0),
               aborted_pages);
}
References v8::internal::GCTracer::CompactionSpeedInBytesPerMillisecond(), DCHECK, v8::debug::GetCurrentPlatform(), v8::internal::Isolate::heap(), v8::Platform::NumberOfWorkerThreads(), v8::internal::PrintIsolate(), v8::internal::Isolate::time_millis_since_init(), v8::internal::Heap::tracer(), v8::internal::v8_flags, and V8PRIdPTR.
Referenced by v8::internal::MarkCompactCollector::EvacuatePagesInParallel().
UpdateOldToSharedSlot()
template<typename TSlot >
static SlotCallbackResult v8::internal::anonymous_namespace{mark-compact.cc}::UpdateOldToSharedSlot (PtrComprCageBase cage_base, TSlot slot) [inline], [static]
Definition at line 4238 of file mark-compact.cc.
                                            {
  typename TSlot::TObject obj = slot.Relaxed_Load(cage_base);
  Tagged<HeapObject> heap_obj;
  if constexpr (TSlot::kCanBeWeak) {
    if (obj.GetHeapObjectIfWeak(&heap_obj)) {
      UpdateSlot<HeapObjectReferenceType::WEAK>(cage_base, slot, heap_obj);
      return HeapLayout::InWritableSharedSpace(heap_obj) ? KEEP_SLOT
                                                         : REMOVE_SLOT;
    }
  }
  if (obj.GetHeapObjectIfStrong(&heap_obj)) {
    UpdateSlot<HeapObjectReferenceType::STRONG>(cage_base, slot, heap_obj);
    return HeapLayout::InWritableSharedSpace(heap_obj) ? KEEP_SLOT
                                                       : REMOVE_SLOT;
  }
  return REMOVE_SLOT;
}
References heap::base::KEEP_SLOT, and heap::base::REMOVE_SLOT.
Referenced by v8::internal::MarkCompactCollector::UpdatePointersInClientHeap().
UpdateSlot() [1/2]
template<typename TSlot >
static void v8::internal::anonymous_namespace{mark-compact.cc}::UpdateSlot (PtrComprCageBase cage_base, TSlot slot) [inline], [static]
Definition at line 4223 of file mark-compact.cc.
                                                                      {
  typename TSlot::TObject obj = slot.Relaxed_Load(cage_base);
  Tagged<HeapObject> heap_obj;
  if constexpr (TSlot::kCanBeWeak) {
    if (obj.GetHeapObjectIfWeak(&heap_obj)) {
      return UpdateSlot<HeapObjectReferenceType::WEAK>(cage_base, slot,
                                                       heap_obj);
    }
  }
  if (obj.GetHeapObjectIfStrong(&heap_obj)) {
    UpdateSlot<HeapObjectReferenceType::STRONG>(cage_base, slot, heap_obj);
  }
}
Referenced by v8::internal::anonymous_namespace{mark-compact.cc}::RememberedSetUpdatingItem::CheckAndUpdateOldToNewSlot(), v8::internal::PointersUpdatingVisitor::UpdateSlotInternal(), v8::internal::anonymous_namespace{mark-compact.cc}::RememberedSetUpdatingItem::UpdateUntypedOldToOldPointers(), and v8::internal::anonymous_namespace{mark-compact.cc}::RememberedSetUpdatingItem::UpdateUntypedTrustedToTrustedPointers().
UpdateSlot() [2/2]
template<HeapObjectReferenceType reference_type, typename TSlot >
static void v8::internal::anonymous_namespace{mark-compact.cc}::UpdateSlot (PtrComprCageBase cage_base, TSlot slot, Tagged< HeapObject > heap_obj) [inline], [static]
Definition at line 4190 of file mark-compact.cc.
                                                           {
  static_assert(
      std::is_same_v<TSlot, FullObjectSlot> ||
          std::is_same_v<TSlot, ObjectSlot> ||
          std::is_same_v<TSlot, FullMaybeObjectSlot> ||
          std::is_same_v<TSlot, MaybeObjectSlot> ||
          std::is_same_v<TSlot, OffHeapObjectSlot> ||
          std::is_same_v<TSlot, InstructionStreamSlot> ||
          std::is_same_v<TSlot, ProtectedPointerSlot> ||
          std::is_same_v<TSlot, ProtectedMaybeObjectSlot> ||
          std::is_same_v<TSlot, WriteProtectedSlot<ObjectSlot>> ||
          std::is_same_v<TSlot, WriteProtectedSlot<ProtectedPointerSlot>>,
      "Only [Full|OffHeap]ObjectSlot, [Full]MaybeObjectSlot, "
      "InstructionStreamSlot, Protected[Pointer|MaybeObject]Slot, "
      "or WriteProtectedSlot are expected here");
  MapWord map_word = heap_obj->map_word(cage_base, kRelaxedLoad);
  if (!map_word.IsForwardingAddress()) return;
  DCHECK_IMPLIES((!v8_flags.minor_ms && !Heap::InFromPage(heap_obj)),
                 MarkCompactCollector::IsOnEvacuationCandidate(heap_obj) ||
                     MemoryChunk::FromHeapObject(heap_obj)->IsFlagSet(
                         MemoryChunk::COMPACTION_WAS_ABORTED));
  typename TSlot::TObject target = MakeSlotValue<TSlot, reference_type>(
      map_word.ToForwardingAddress(heap_obj));
  // Needs to be atomic for map space compaction: This slot could be a map
  // word which we update while loading the map word for updating the slot
  // on another page.
  slot.Relaxed_Store(target);
  DCHECK_IMPLIES(!v8_flags.sticky_mark_bits, !Heap::InFromPage(target));
  DCHECK(!MarkCompactCollector::IsOnEvacuationCandidate(target));
}
References DCHECK, DCHECK_IMPLIES, v8::internal::MapWord::IsForwardingAddress(), v8::kRelaxedLoad, v8::internal::MapWord::ToForwardingAddress(), and v8::internal::v8_flags.
UpdateStrongCodeSlot()
static void v8::internal::anonymous_namespace{mark-compact.cc}::UpdateStrongCodeSlot (IsolateForSandbox isolate, PtrComprCageBase cage_base, PtrComprCageBase code_cage_base, InstructionStreamSlot slot) [inline], [static]
Definition at line 4290 of file mark-compact.cc.
                                                                    {
  Tagged<Object> obj = slot.Relaxed_Load(code_cage_base);
  DCHECK(!HAS_WEAK_HEAP_OBJECT_TAG(obj.ptr()));
  Tagged<HeapObject> heap_obj;
  if (obj.GetHeapObject(&heap_obj)) {
    UpdateSlot<HeapObjectReferenceType::STRONG>(cage_base, slot, heap_obj);
    Tagged<Code> code = Cast<Code>(HeapObject::FromAddress(
        slot.address() - Code::kInstructionStreamOffset));
    Tagged<InstructionStream> instruction_stream =
        code->instruction_stream(code_cage_base);
    code->UpdateInstructionStart(isolate, instruction_stream);
  }
}
References v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::address(), code, DCHECK, v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObject(), HAS_WEAK_HEAP_OBJECT_TAG, v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), and v8::internal::OffHeapFullObjectSlot::Relaxed_Load().
Referenced by v8::internal::anonymous_namespace{mark-compact.cc}::RememberedSetUpdatingItem::UpdateUntypedTrustedToCodePointers(), and v8::internal::PointersUpdatingVisitor::VisitInstructionStreamPointer().
UpdateStrongOldToSharedSlot()
static SlotCallbackResult v8::internal::anonymous_namespace{mark-compact.cc}::UpdateStrongOldToSharedSlot (PtrComprCageBase cage_base, FullMaybeObjectSlot slot) [inline], [static]
Definition at line 4273 of file mark-compact.cc.
                                                          {
  Tagged<MaybeObject> obj = slot.Relaxed_Load(cage_base);
#ifdef V8_ENABLE_DIRECT_HANDLE
  if (obj.ptr() == kTaggedNullAddress) return REMOVE_SLOT;
#endif
  DCHECK(!HAS_WEAK_HEAP_OBJECT_TAG(obj.ptr()));
  Tagged<HeapObject> heap_obj;
  if (obj.GetHeapObject(&heap_obj)) {
    UpdateSlot<HeapObjectReferenceType::STRONG>(cage_base, slot, heap_obj);
    return HeapLayout::InWritableSharedSpace(heap_obj) ? KEEP_SLOT
                                                       : REMOVE_SLOT;
  }
  return REMOVE_SLOT;
}
References DCHECK, v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObject(), HAS_WEAK_HEAP_OBJECT_TAG, heap::base::KEEP_SLOT, v8::internal::kTaggedNullAddress, v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), v8::internal::FullMaybeObjectSlot::Relaxed_Load(), and heap::base::REMOVE_SLOT.
Referenced by v8::internal::MarkCompactCollector::UpdatePointersInClientHeap().
UpdateStrongSlot()
template<typename TSlot >
static void v8::internal::anonymous_namespace{mark-compact.cc}::UpdateStrongSlot (PtrComprCageBase cage_base, TSlot slot) [inline], [static]
Definition at line 4261 of file mark-compact.cc.
                                                                            {
  typename TSlot::TObject obj = slot.Relaxed_Load(cage_base);
#ifdef V8_ENABLE_DIRECT_HANDLE
  if (obj.ptr() == kTaggedNullAddress) return;
#endif
  DCHECK(!HAS_WEAK_HEAP_OBJECT_TAG(obj.ptr()));
  Tagged<HeapObject> heap_obj;
  if (obj.GetHeapObject(&heap_obj)) {
    UpdateSlot<HeapObjectReferenceType::STRONG>(cage_base, slot, heap_obj);
  }
}
References DCHECK, HAS_WEAK_HEAP_OBJECT_TAG, and v8::internal::kTaggedNullAddress.
Referenced by v8::internal::PointersUpdatingVisitor::UpdateRootSlotInternal(), v8::internal::PointersUpdatingVisitor::UpdateStrongMaybeObjectSlotInternal(), v8::internal::PointersUpdatingVisitor::UpdateStrongSlotInternal(), v8::internal::anonymous_namespace{mark-compact.cc}::RememberedSetUpdatingItem::UpdateTypedOldToOldPointers(), and v8::internal::anonymous_namespace{mark-compact.cc}::RememberedSetUpdatingItem::UpdateUntypedTrustedToTrustedPointers().
Variable Documentation
kDeadlineCheckInterval
constexpr size_t v8::internal::anonymous_namespace{mark-compact.cc}::kDeadlineCheckInterval = 128u [constexpr]
Definition at line 2195 of file mark-compact.cc.
Referenced by cppgc::internal::DrainWorklistWithPredicate(), and v8::internal::MarkCompactCollector::ProcessMarkingWorklist().