v8::debug Namespace Reference
Namespaces
 anonymous_namespace{debug-interface.cc}
Classes
struct LiveEditResult
class ScriptSource
An internal representation of the source for a given v8::debug::Script, which can be a v8::String, in which case it represents JavaScript source, or it can be a managed pointer to a native Wasm module, or it can be undefined to indicate that source is unavailable.
class Script
Native wrapper around v8::internal::Script object.
class DisassemblyCollector
class DebugDelegate
class AsyncEventDelegate
class GeneratorObject
Native wrapper around v8::internal::JSGeneratorObject object.
class Coverage
class ScopeIterator
class StackTraceIterator
class PostponeInterruptsScope
class DisableBreakScope
class EphemeronTable
class AccessorPair
Pairs of accessors.
struct PropertyDescriptor
class PropertyIterator
class Location
Defines location inside script.
class BreakLocation
class ConsoleCallArguments
class ConsoleContext
class ConsoleDelegate
Typedefs
typedef base::EnumSet< BreakReason > BreakReasons
using BreakpointId = int
using OutOfMemoryCallback = void(*)(void *data)
Enumerations
enum class PrivateMemberFilter { kPrivateMethods = 1
, kPrivateFields = 1 << 1
, kPrivateAccessors = 1 << 2
 }
enum ExceptionBreakState { NoBreakOnException = 0
, BreakOnCaughtException = 1
, BreakOnUncaughtException = 2
, BreakOnAnyException = 3
 }
enum StepAction { StepOut = 0
, StepOver = 1
, StepInto = 2
 }
enum class BreakReason : uint8_t {
kAlreadyPaused
, kStep
, kAsyncStep
, kException
,
kAssert
, kDebuggerStatement
, kOOM
, kScheduled
,
kAgent
 }
enum ExceptionType { kException
, kException
, kPromiseRejection
 }
enum Builtin { kStringToLowerCase
 }
enum class NativeAccessorType { None = 0
, HasGetter = 1 << 0
, HasSetter = 1 << 1
, IsValueUnavailable = 1 << 2
 }
enum class EvaluateGlobalMode { kDefault
, kDisableBreaks
, kDisableBreaksAndThrowOnSideEffect
 }
enum DebugAsyncActionType {
kDebugAwait
, kDebugPromiseThen
, kDebugPromiseCatch
, kDebugPromiseFinally
,
kDebugWillHandle
, kDebugDidHandle
, kDebugStackTraceCaptured
 }
enum BreakLocationType { kCallBreakLocation
, kReturnBreakLocation
, kDebuggerStatementBreakLocation
, kCommonBreakLocation
 }
enum class CoverageMode {
kBestEffort
, kPreciseCount
, kPreciseBinary
, kBlockCount
,
kBlockBinary
 }
Functions
void SetContextId (Local< Context > context, int id)
int GetContextId (Local< Context > context)
void SetInspector (Isolate *isolate, v8_inspector::V8Inspector *inspector)
v8_inspector::V8Inspector * GetInspector (Isolate *isolate)
Local< String > GetBigIntStringValue (Isolate *isolate, Local< BigInt > bigint)
Local< String > GetBigIntDescription (Isolate *isolate, Local< BigInt > bigint)
Local< String > GetDateDescription (Local< Date > date)
Local< String > GetFunctionDescription (Local< Function > function)
void SetBreakOnNextFunctionCall (Isolate *isolate)
void ClearBreakOnNextFunctionCall (Isolate *isolate)
MaybeLocal< Array > GetInternalProperties (Isolate *isolate, Local< Value > value)
Returns array of internal properties specific to the value type.
bool GetPrivateMembers (Local< Context > context, Local< Object > value, int filter, LocalVector< Value > *names_out, LocalVector< Value > *values_out)
Retrieve both instance and static private members on an object.
MaybeLocal< Context > GetCreationContext (Local< Object > value)
Forwards to v8::Object::CreationContext, but with special handling for JSGlobalProxy objects.
void ChangeBreakOnException (Isolate *isolate, ExceptionBreakState state)
Defines if VM will pause on exceptions or not.
void SetBreakPointsActive (Isolate *v8_isolate, bool is_active)
void PrepareStep (Isolate *v8_isolate, StepAction action)
bool PrepareRestartFrame (Isolate *v8_isolate, int callFrameOrdinal)
void ClearStepping (Isolate *v8_isolate)
void BreakRightNow (Isolate *v8_isolate, base::EnumSet< debug::BreakReason > break_reasons)
void SetTerminateOnResume (Isolate *v8_isolate)
bool CanBreakProgram (Isolate *v8_isolate)
void RemoveBreakpoint (Isolate *v8_isolate, BreakpointId id)
Platform * GetCurrentPlatform ()
void ForceGarbageCollection (Isolate *isolate, StackState embedder_stack_state)
void GetLoadedScripts (Isolate *v8_isolate, std::vector< v8::Global< Script >> &scripts)
std::optional< v8::ScriptOrigin > GetScriptOrigin (Isolate *v8_isolate, int script_id)
MaybeLocal< UnboundScript > CompileInspectorScript (Isolate *v8_isolate, Local< String > source)
void SetDebugDelegate (Isolate *v8_isolate, DebugDelegate *delegate)
void SetAsyncEventDelegate (Isolate *v8_isolate, AsyncEventDelegate *delegate)
void ResetBlackboxedStateCache (Isolate *v8_isolate, Local< Script > script)
int EstimatedValueSize (Isolate *v8_isolate, Local< Value > value)
Local< Function > GetBuiltin (Isolate *v8_isolate, Builtin requested_builtin)
void SetConsoleDelegate (Isolate *v8_isolate, ConsoleDelegate *delegate)
v8::Local< v8::Message > CreateMessageFromException (Isolate *v8_isolate, v8::Local< v8::Value > v8_error)
MaybeLocal< Value > CallFunctionOn (Local< Context > context, Local< Function > function, Local< Value > recv, base::Vector< Local< Value >> args, bool throw_on_side_effect)
MaybeLocal< v8::Value > EvaluateGlobal (v8::Isolate *isolate, v8::Local< v8::String > source, EvaluateGlobalMode mode, bool repl)
void GlobalLexicalScopeNames (v8::Local< v8::Context > v8_context, std::vector< v8::Global< v8::String >> *names)
void SetReturnValue (v8::Isolate *v8_isolate, v8::Local< v8::Value > value)
int64_t GetNextRandomInt64 (v8::Isolate *v8_isolate)
int GetDebuggingId (v8::Local< v8::Function > function)
bool SetFunctionBreakpoint (v8::Local< v8::Function > function, v8::Local< v8::String > condition, BreakpointId *id)
MaybeLocal< Message > GetMessageFromPromise (Local< Promise > p)
void RecordAsyncStackTaggingCreateTaskCall (v8::Isolate *v8_isolate)
void NotifyDebuggerPausedEventSent (v8::Isolate *v8_isolate)
uint64_t GetIsolateId (v8::Isolate *v8_isolate)
void SetIsolateId (v8::Isolate *v8_isolate, uint64_t id)
Typedef Documentation
BreakpointId
using v8::debug::BreakpointId = typedef int
Definition at line 184 of file interface-types.h.
BreakReasons
typedef base::EnumSet<BreakReason> v8::debug::BreakReasons
Definition at line 143 of file debug-interface.h.
OutOfMemoryCallback
using v8::debug::OutOfMemoryCallback = typedef void (*)(void* data)
Definition at line 70 of file heap.h.
Enumeration Type Documentation
BreakLocationType
enum v8::debug::BreakLocationType
Enumerator
kCallBreakLocation
kReturnBreakLocation
kDebuggerStatementBreakLocation
kCommonBreakLocation
Definition at line 58 of file interface-types.h.
                       {
  kCallBreakLocation,
  kReturnBreakLocation,
  kDebuggerStatementBreakLocation,
  kCommonBreakLocation
};
BreakReason
enum v8::debug::BreakReason : uint8_t [strong]
Enumerator
kAlreadyPaused
kStep
kAsyncStep
kException
kAssert
kDebuggerStatement
kOOM
kScheduled
kAgent
Definition at line 132 of file debug-interface.h.
                       : uint8_t {
  kAlreadyPaused,
  kStep,
  kAsyncStep,
  kException,
  kAssert,
  kDebuggerStatement,
  kOOM,
  kScheduled,
  kAgent
};
Builtin
enum v8::debug::Builtin
Enumerator
kStringToLowerCase
Definition at line 367 of file debug-interface.h.
{ kStringToLowerCase };
CoverageMode
enum v8::debug::CoverageMode [strong]
Enumerator
kBestEffort
kPreciseCount
kPreciseBinary
kBlockCount
kBlockBinary
Definition at line 65 of file interface-types.h.
                        {
  // Make use of existing information in feedback vectors on the heap.
  // Only return a yes/no result. Optimization and GC are not affected.
  // Collecting best effort coverage does not reset counters.
  kBestEffort,
  // Disable optimization and prevent feedback vectors from being garbage
  // collected in order to preserve precise invocation counts. Collecting
  // precise count coverage resets counters to get incremental updates.
  kPreciseCount,
  // We are only interested in a yes/no result for the function. Optimization
  // and GC can be allowed once a function has been invoked. Collecting
  // precise binary coverage resets counters for incremental updates.
  kPreciseBinary,
  // Similar to the precise coverage modes but provides coverage at a
  // lower granularity. Design doc:
  // https://docs.google.com/document/d/1wCydi2HEZRF0skDeLb6CH0abZnTyVo5Vz5u-jhwi7es
  kBlockCount,
  kBlockBinary,
};
DebugAsyncActionType
enum v8::debug::DebugAsyncActionType
Enumerator
kDebugAwait
kDebugPromiseThen
kDebugPromiseCatch
kDebugPromiseFinally
kDebugWillHandle
kDebugDidHandle
kDebugStackTraceCaptured
Definition at line 48 of file interface-types.h.
                          {
  kDebugAwait,
  kDebugPromiseThen,
  kDebugPromiseCatch,
  kDebugPromiseFinally,
  kDebugWillHandle,
  kDebugDidHandle,
  kDebugStackTraceCaptured
};
EvaluateGlobalMode
enum v8::debug::EvaluateGlobalMode [strong]
Enumerator
kDefault
kDisableBreaks
kDisableBreaksAndThrowOnSideEffect
Definition at line 564 of file debug-interface.h.
                              {
  kDefault,
  kDisableBreaks,
  kDisableBreaksAndThrowOnSideEffect
};
ExceptionBreakState
enum v8::debug::ExceptionBreakState
Enumerator
NoBreakOnException
BreakOnCaughtException
BreakOnUncaughtException
BreakOnAnyException
Definition at line 106 of file debug-interface.h.
                         {
  NoBreakOnException = 0,
  BreakOnCaughtException = 1,
  BreakOnUncaughtException = 2,
  BreakOnAnyException = 3,
};
ExceptionType
enum v8::debug::ExceptionType
Enumerator
kException
kException
kPromiseRejection
Definition at line 299 of file debug-interface.h.
{ kException, kPromiseRejection };
NativeAccessorType
enum v8::debug::NativeAccessorType [strong]
Enumerator
None
HasGetter
HasSetter
IsValueUnavailable
Definition at line 550 of file debug-interface.h.
                              {
  None = 0,
  HasGetter = 1 << 0,
  HasSetter = 1 << 1,
  IsValueUnavailable = 1 << 2
};
PrivateMemberFilter
enum v8::debug::PrivateMemberFilter [strong]
Enumerator
kPrivateMethods
kPrivateFields
kPrivateAccessors
Definition at line 78 of file debug-interface.h.
                               {
  kPrivateMethods = 1,
  kPrivateFields = 1 << 1,
  kPrivateAccessors = 1 << 2,
};
StepAction
enum v8::debug::StepAction
Enumerator
StepOut
StepOver
StepInto
Definition at line 124 of file debug-interface.h.
                {
  StepOut = 0, // Step out of the current function.
  StepOver = 1, // Step to the next statement in the current function.
  StepInto = 2 // Step into new functions invoked or the next statement
                 // in the current function.
};
Function Documentation
BreakRightNow()
V8_EXPORT_PRIVATE void v8::debug::BreakRightNow (Isolate * v8_isolate, base::EnumSet< debug::BreakReason > break_reasons)
Definition at line 421 of file debug-interface.cc.
                                                                {
  i::Isolate* isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  EnterV8BasicScope api_scope(isolate);
  isolate->debug()->HandleDebugBreak(i::kIgnoreIfAllFramesBlackboxed,
                                     break_reasons);
}
References v8::internal::Isolate::debug(), v8::internal::Debug::HandleDebugBreak(), and v8::internal::kIgnoreIfAllFramesBlackboxed.
Referenced by v8_inspector::V8Debugger::breakProgram(), v8_inspector::V8Debugger::breakProgramOnAssert(), v8_inspector::V8Debugger::interruptAndBreak(), v8_inspector::V8Debugger::nearHeapLimitCallback(), v8::internal::RUNTIME_FUNCTION(), and v8::internal::wasm::gdb_server::GdbServer::Suspend().
CallFunctionOn()
MaybeLocal< Value > v8::debug::CallFunctionOn (Local< Context > context, Local< Function > function, Local< Value > recv, base::Vector< Local< Value >> args, bool throw_on_side_effect)
Definition at line 1229 of file debug-interface.cc.
                                                            {
  auto isolate = i::Isolate::Current();
  PrepareForDebugInterfaceExecutionScope api_scope(isolate, context);
  auto self = Utils::OpenHandle(*function);
  auto recv_obj = Utils::OpenHandle(*recv);
  static_assert(sizeof(v8::Global<v8::Value>) == sizeof(i::Handle<i::Object>));
  auto arguments = reinterpret_cast<i::DirectHandle<i::Object>*>(args.data());
  // Disable breaks in side-effect free mode.
  i::DisableBreak disable_break_scope(isolate->debug(), throw_on_side_effect);
  if (throw_on_side_effect) {
    isolate->debug()->StartSideEffectCheckMode();
  }
  MaybeLocal<Value> result = Utils::ToMaybeLocal(
      i::Execution::Call(isolate, self, recv_obj, {arguments, args.size()}));
  if (throw_on_side_effect) {
    isolate->debug()->StopSideEffectCheckMode();
  }
  return api_scope.EscapeMaybe(result);
}
References v8::base::args, v8::internal::Execution::Call(), v8::internal::Isolate::Current(), v8::internal::Isolate::debug(), v8::PrepareForDebugInterfaceExecutionScope::EscapeMaybe(), v8::Utils::OpenHandle(), v8::base::internal::result, v8::internal::Debug::StartSideEffectCheckMode(), v8::internal::Debug::StopSideEffectCheckMode(), and v8::Utils::ToMaybeLocal().
Referenced by v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::innerCallFunctionOn().
CanBreakProgram()
bool v8::debug::CanBreakProgram (Isolate * v8_isolate)
Definition at line 435 of file debug-interface.cc.
                                          {
  i::Isolate* isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  EnterV8BasicScope api_scope(isolate);
  return !isolate->debug()->AllFramesOnStackAreBlackboxed();
}
References v8::internal::Debug::AllFramesOnStackAreBlackboxed(), and v8::internal::Isolate::debug().
Referenced by v8_inspector::V8Debugger::canBreakProgram().
ChangeBreakOnException()
void v8::debug::ChangeBreakOnException (Isolate * isolate, ExceptionBreakState state)
Defines if VM will pause on exceptions or not.
If BreakOnAnyExceptions is set then VM will pause on caught and uncaught exception, if BreakOnUncaughtException is set then VM will pause only on uncaught exception, otherwise VM won't stop on any exception.
Definition at line 372 of file debug-interface.cc.
                                                                        {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(isolate);
  i::DisallowJavascriptExecutionDebugOnly no_execution(i_isolate);
  i::DisallowExceptionsDebugOnly no_exceptions(i_isolate);
  i_isolate->debug()->ChangeBreakOnException(
      i::BreakCaughtException,
      type == BreakOnCaughtException || type == BreakOnAnyException);
  i_isolate->debug()->ChangeBreakOnException(
      i::BreakUncaughtException,
      type == BreakOnUncaughtException || type == BreakOnAnyException);
}
References v8::internal::BreakCaughtException, BreakOnAnyException, BreakOnCaughtException, BreakOnUncaughtException, v8::internal::BreakUncaughtException, v8::internal::Debug::ChangeBreakOnException(), v8::internal::Isolate::debug(), and v8::internal::tracing::type.
Referenced by v8::internal::wasm::gdb_server::GdbServer::DebugDelegate::DebugDelegate(), v8_inspector::V8Debugger::enable(), and v8_inspector::V8Debugger::setPauseOnExceptionsState().
ClearBreakOnNextFunctionCall()
V8_EXPORT_PRIVATE void v8::debug::ClearBreakOnNextFunctionCall (Isolate * isolate)
Definition at line 180 of file debug-interface.cc.
                                                    {
  auto i_isolate = reinterpret_cast<i::Isolate*>(isolate);
  i::DisallowJavascriptExecutionDebugOnly no_execution(i_isolate);
  i::DisallowExceptionsDebugOnly no_exceptions(i_isolate);
  i_isolate->debug()->ClearBreakOnNextFunctionCall();
}
Referenced by v8_inspector::V8Debugger::asyncTaskFinishedForStepping(), v8_inspector::V8Debugger::externalAsyncTaskFinished(), and v8_inspector::V8Debugger::setPauseOnNextCall().
ClearStepping()
void v8::debug::ClearStepping (Isolate * v8_isolate)
Definition at line 414 of file debug-interface.cc.
                                        {
  i::Isolate* isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  EnterV8NoScriptNoExceptionScope api_scope(isolate);
  // Clear all current stepping setup.
  isolate->debug()->ClearStepping();
}
References v8::internal::Debug::ClearStepping(), and v8::internal::Isolate::debug().
Referenced by v8_inspector::V8Debugger::asyncTaskCandidateForStepping(), and v8_inspector::V8Debugger::storeCurrentStackTrace().
CompileInspectorScript()
MaybeLocal< UnboundScript > v8::debug::CompileInspectorScript (Isolate * v8_isolate, Local< String > source)
Definition at line 1042 of file debug-interface.cc.
                                                                       {
  i::Isolate* isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  v8::Local<v8::Context> context = Utils::ToLocal(isolate->native_context());
  PrepareForDebugInterfaceExecutionScope api_scope(isolate, context);
  i::Handle<i::String> str = Utils::OpenHandle(*source);
  i::DirectHandle<i::SharedFunctionInfo> result;
  {
    i::AlignedCachedData* cached_data = nullptr;
    ScriptCompiler::CompilationDetails compilation_details;
    i::MaybeDirectHandle<i::SharedFunctionInfo> maybe_function_info =
        i::Compiler::GetSharedFunctionInfoForScriptWithCachedData(
            isolate, str, i::ScriptDetails(), cached_data,
            ScriptCompiler::kNoCompileOptions,
            ScriptCompiler::kNoCacheBecauseInspector,
            i::v8_flags.expose_inspector_scripts ? i::NOT_NATIVES_CODE
                                                 : i::INSPECTOR_CODE,
            &compilation_details);
    bool has_exception = !maybe_function_info.ToHandle(&result);
    if (has_exception) return {};
  }
  return api_scope.Escape(ToApiHandle<UnboundScript>(result));
}
References v8::PrepareForDebugInterfaceExecutionScope::Escape(), v8::internal::Compiler::GetSharedFunctionInfoForScriptWithCachedData(), v8::internal::INSPECTOR_CODE, v8::ScriptCompiler::kNoCacheBecauseInspector, v8::ScriptCompiler::kNoCompileOptions, v8::internal::Isolate::native_context(), v8::internal::NOT_NATIVES_CODE, v8::Utils::OpenHandle(), v8::base::internal::result, v8::internal::MaybeDirectHandle< T >::ToHandle(), and v8::internal::v8_flags.
Referenced by v8_inspector::V8InspectorImpl::compileAndRunInternalScript().
CreateMessageFromException()
V8_EXPORT_PRIVATE v8::Local< v8::Message > v8::debug::CreateMessageFromException (Isolate * v8_isolate, v8::Local< v8::Value > v8_error)
Definition at line 1182 of file debug-interface.cc.
                                                    {
  i::DirectHandle<i::Object> obj = Utils::OpenDirectHandle(*v8_error);
  i::Isolate* isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  EnterV8NoScriptNoExceptionScope api_scope(isolate);
  i::HandleScope scope(isolate);
  return Utils::MessageToLocal(
      scope.CloseAndEscape(isolate->CreateMessageFromException(obj)));
}
References v8::internal::Isolate::CreateMessageFromException(), and v8::Utils::OpenDirectHandle().
Referenced by v8_inspector::V8Debugger::BreakpointConditionEvaluated(), and v8_inspector::V8RuntimeAgentImpl::getExceptionDetails().
EstimatedValueSize()
int v8::debug::EstimatedValueSize (Isolate * v8_isolate, Local< Value > value)
Definition at line 1101 of file debug-interface.cc.
                                                                {
  i::Isolate* isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  EnterV8NoScriptNoExceptionScope api_scope(isolate);
  auto object = Utils::OpenDirectHandle(*value);
  if (IsSmi(*object)) return i::kTaggedSize;
  CHECK(IsHeapObject(*object));
  return i::Cast<i::HeapObject>(object)->Size();
}
References CHECK, v8::internal::InstanceTypeChecker::IsHeapObject(), v8::internal::IsSmi(), v8::internal::kTaggedSize, v8::Utils::OpenDirectHandle(), and v8::internal::value.
Referenced by v8_inspector::V8ConsoleMessage::createForConsoleAPI(), and v8_inspector::V8ConsoleMessage::createForException().
EvaluateGlobal()
V8_EXPORT_PRIVATE v8::MaybeLocal< v8::Value > v8::debug::EvaluateGlobal (v8::Isolate * isolate, v8::Local< v8::String > source, EvaluateGlobalMode mode, bool repl)
Definition at line 1252 of file debug-interface.cc.
                                                                         {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(isolate);
  v8::Local<v8::Context> context = Utils::ToLocal(i_isolate->native_context());
  PrepareForDebugInterfaceExecutionScope api_scope(i_isolate, context);
  i::REPLMode repl_mode = repl ? i::REPLMode::kYes : i::REPLMode::kNo;
  MaybeLocal<Value> result = Utils::ToMaybeLocal(i::DebugEvaluate::Global(
      i_isolate, Utils::OpenHandle(*source), mode, repl_mode));
  return api_scope.EscapeMaybe(result);
}
References v8::PrepareForDebugInterfaceExecutionScope::EscapeMaybe(), v8::internal::DebugEvaluate::Global(), v8::internal::kNo, v8::internal::kYes, mode(), v8::internal::Isolate::native_context(), v8::Utils::OpenHandle(), v8::base::internal::result, and v8::Utils::ToMaybeLocal().
Referenced by v8_inspector::V8RuntimeAgentImpl::evaluate(), and v8_inspector::V8InspectorSessionImpl::evaluate().
ForceGarbageCollection()
void v8::debug::ForceGarbageCollection (Isolate * isolate, StackState embedder_stack_state)
Definition at line 802 of file debug-interface.cc.
                                                                               {
  i::EmbedderStackStateScope stack_scope(
      reinterpret_cast<i::Isolate*>(isolate)->heap(),
      i::EmbedderStackStateOrigin::kImplicitThroughTask, embedder_stack_state);
  isolate->LowMemoryNotification();
}
References heap(), and v8::Isolate::LowMemoryNotification().
Referenced by v8_inspector::V8HeapProfilerAgentImpl::GCTask::Run().
GetBigIntDescription()
Local< String > v8::debug::GetBigIntDescription (Isolate * isolate, Local< BigInt > bigint)
Definition at line 111 of file debug-interface.cc.
                                                                           {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(isolate);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::DirectHandle<i::BigInt> i_bigint = Utils::OpenDirectHandle(*bigint);
  i::Handle<i::String> string_value =
      GetBigIntStringPresentationHandle(i_isolate, i_bigint);
  i::DirectHandle<i::String> description =
      i_isolate->factory()
          ->NewConsString(string_value, i_isolate->factory()->n_string())
          .ToHandleChecked();
  return Utils::ToLocal(description);
}
References v8::internal::Isolate::factory(), v8::debug::anonymous_namespace{debug-interface.cc}::GetBigIntStringPresentationHandle(), v8::internal::FactoryBase< Impl >::NewConsString(), and v8::Utils::OpenDirectHandle().
Referenced by v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForBigInt().
GetBigIntStringValue()
Local< String > v8::debug::GetBigIntStringValue (Isolate * isolate, Local< BigInt > bigint)
Definition at line 101 of file debug-interface.cc.
                                                                           {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(isolate);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::DirectHandle<i::BigInt> i_bigint = Utils::OpenDirectHandle(*bigint);
  i::DirectHandle<i::String> string_value =
      GetBigIntStringPresentationHandle(i_isolate, i_bigint);
  return Utils::ToLocal(string_value);
}
References v8::debug::anonymous_namespace{debug-interface.cc}::GetBigIntStringPresentationHandle(), and v8::Utils::OpenDirectHandle().
Referenced by v8_inspector::anonymous_namespace{value-mirror.cc}::BigIntMirror::buildDeepSerializedValue().
GetBuiltin()
Local< Function > v8::debug::GetBuiltin (Isolate * v8_isolate, Builtin requested_builtin)
Definition at line 1137 of file debug-interface.cc.
                                                                           {
  i::Isolate* isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  EnterV8NoScriptNoExceptionScope api_scope(isolate);
  i::HandleScope handle_scope(isolate);
  CHECK_EQ(requested_builtin, kStringToLowerCase);
  i::Builtin builtin = i::Builtin::kStringPrototypeToLocaleLowerCase;
  i::Factory* factory = isolate->factory();
  i::DirectHandle<i::String> name = isolate->factory()->empty_string();
  i::DirectHandle<i::NativeContext> context(isolate->native_context());
  i::DirectHandle<i::SharedFunctionInfo> info =
      factory->NewSharedFunctionInfoForBuiltin(name, builtin, 0, i::kAdapt);
  info->set_language_mode(i::LanguageMode::kStrict);
  i::Handle<i::JSFunction> fun =
      i::Factory::JSFunctionBuilder{isolate, info, context}
          .set_map(isolate->strict_function_without_prototype_map())
          .Build();
  return Utils::ToLocal(handle_scope.CloseAndEscape(fun));
}
References CHECK_EQ, v8::internal::Isolate::factory(), v8::internal::kStrict, kStringToLowerCase, name, v8::internal::Isolate::native_context(), and v8::internal::Factory::NewSharedFunctionInfoForBuiltin().
GetContextId()
int v8::debug::GetContextId (Local< Context > context)
Definition at line 41 of file debug-interface.cc.
                                         {
  auto v8_context = Utils::OpenDirectHandle(*context);
  auto* i_isolate = i::Isolate::Current();
  i::DisallowJavascriptExecutionDebugOnly no_execution(i_isolate);
  i::DisallowExceptionsDebugOnly no_exceptions(i_isolate);
  i::Tagged<i::Object> value = v8_context->debug_context_id();
  return (IsSmi(value)) ? i::Smi::ToInt(value) : 0;
}
References v8::internal::Isolate::Current(), v8::internal::IsSmi(), v8::Utils::OpenDirectHandle(), v8::internal::Smi::ToInt(), and v8::internal::value.
Referenced by v8::internal::CppHeap::MetricRecorderAdapter::AddMainThreadEvent(), v8_inspector::InspectedContext::contextId(), and v8::internal::CppHeap::MetricRecorderAdapter::FlushBatchedIncrementalEvents().
GetCreationContext()
MaybeLocal< Context > v8::debug::GetCreationContext (Local< Object > value)
Forwards to v8::Object::CreationContext, but with special handling for JSGlobalProxy objects.
Definition at line 363 of file debug-interface.cc.
                                                            {
  if (IsJSGlobalProxy(*Utils::OpenDirectHandle(*value))) {
    return MaybeLocal<Context>();
  }
  START_ALLOW_USE_DEPRECATED();
  return value->GetCreationContext();
  END_ALLOW_USE_DEPRECATED();
}
References END_ALLOW_USE_DEPRECATED, v8::Utils::OpenDirectHandle(), START_ALLOW_USE_DEPRECATED, and v8::internal::value.
Referenced by v8::internal::CodeStubAssembler::CallGetterIfAccessor(), v8_inspector::anonymous_namespace{v8-debugger.cc}::MatchPrototypePredicate::Filter(), v8::internal::JSReceiver::GetCreationContext(), v8::internal::JSGlobalProxy::IsDetached(), and v8::internal::JSGlobalObject::native_context().
GetCurrentPlatform()
v8::Platform * v8::debug::GetCurrentPlatform ()
Definition at line 800 of file debug-interface.cc.
{ return i::V8::GetCurrentPlatform(); }
References v8::internal::V8::GetCurrentPlatform().
Referenced by v8::internal::MarkCompactCollector::ClearNonLiveReferences(), v8_inspector::V8HeapProfilerAgentImpl::collectGarbage(), v8::internal::anonymous_namespace{mark-compact.cc}::CreateAndExecuteEvacuationTasks(), v8_inspector::InspectedContext::WeakCallbackData::resetContext(), v8_inspector::V8InspectorImpl::EvaluateScope::setTimeout(), v8_inspector::V8HeapProfilerAgentImpl::takeHeapSnapshot(), v8::internal::anonymous_namespace{mark-compact.cc}::TraceEvacuation(), and v8::internal::MarkCompactCollector::UpdatePointersAfterEvacuation().
GetDateDescription()
Local< String > v8::debug::GetDateDescription (Local< Date > date)
Definition at line 126 of file debug-interface.cc.
                                                   {
  auto receiver = Utils::OpenDirectHandle(*date);
  auto jsdate = i::Cast<i::JSDate>(receiver);
  i::Isolate* i_isolate = i::Isolate::Current();
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  auto buffer = i::ToDateString(jsdate->value(), i_isolate->date_cache(),
                                i::ToDateStringMode::kLocalDateAndTime);
  return Utils::ToLocal(i_isolate->factory()
                            ->NewStringFromUtf8(base::VectorOf(buffer))
                            .ToHandleChecked());
}
References v8::internal::Isolate::Current(), v8::internal::date, v8::internal::Isolate::date_cache(), v8::internal::Isolate::factory(), v8::internal::Factory::NewStringFromUtf8(), v8::Utils::OpenDirectHandle(), v8::internal::ToDateString(), and v8::base::VectorOf().
Referenced by v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForDate().
GetDebuggingId()
int v8::debug::GetDebuggingId (v8::Local< v8::Function > function)
Definition at line 1294 of file debug-interface.cc.
                                                 {
  auto callable = v8::Utils::OpenDirectHandle(*function);
  if (!IsJSFunction(*callable)) return i::DebugInfo::kNoDebuggingId;
  auto func = i::Cast<i::JSFunction>(callable);
  int id = i::Isolate::Current()->debug()->GetFunctionDebuggingId(func);
  DCHECK_NE(i::DebugInfo::kNoDebuggingId, id);
  return id;
}
References v8::internal::Isolate::Current(), DCHECK_NE, v8::internal::Isolate::debug(), v8::internal::Debug::GetFunctionDebuggingId(), v8::internal::DebugInfo::kNoDebuggingId, and v8::Utils::OpenDirectHandle().
Referenced by v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::generateBreakpointId().
GetFunctionDescription()
Local< String > v8::debug::GetFunctionDescription (Local< Function > function)
Definition at line 138 of file debug-interface.cc.
                                                               {
  auto receiver = Utils::OpenHandle(*function);
  auto i_isolate = i::Isolate::Current();
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  if (IsJSBoundFunction(*receiver)) {
    return Utils::ToLocal(i::JSBoundFunction::ToString(
        i_isolate, i::Cast<i::JSBoundFunction>(receiver)));
  }
  if (IsJSFunction(*receiver)) {
    auto js_function = i::Cast<i::JSFunction>(receiver);
#if V8_ENABLE_WEBASSEMBLY
    if (js_function->shared()->HasWasmExportedFunctionData(i_isolate)) {
      i::DirectHandle<i::WasmExportedFunctionData> function_data(
          js_function->shared()->wasm_exported_function_data(), i_isolate);
      int func_index = function_data->function_index();
      i::DirectHandle<i::WasmTrustedInstanceData> instance_data(
          function_data->instance_data(), i_isolate);
      if (instance_data->module()->origin == i::wasm::kWasmOrigin) {
        // For asm.js functions, we can still print the source
        // code (hopefully), so don't bother with them here.
        auto debug_name =
            i::GetWasmFunctionDebugName(i_isolate, instance_data, func_index);
        i::IncrementalStringBuilder builder(i_isolate);
        builder.AppendCStringLiteral("function ");
        builder.AppendString(debug_name);
        builder.AppendCStringLiteral("() { [native code] }");
        return Utils::ToLocal(builder.Finish().ToHandleChecked());
      }
    }
#endif // V8_ENABLE_WEBASSEMBLY
    return Utils::ToLocal(i::JSFunction::ToString(i_isolate, js_function));
  }
  return Utils::ToLocal(i_isolate->factory()->function_native_code_string());
}
References v8::internal::IncrementalStringBuilder::AppendCStringLiteral(), v8::internal::IncrementalStringBuilder::AppendString(), v8::internal::Isolate::Current(), v8::internal::IncrementalStringBuilder::Finish(), v8::internal::GetWasmFunctionDebugName(), v8::internal::instance_data, v8::internal::wasm::kWasmOrigin, v8::Utils::OpenHandle(), v8::internal::JSBoundFunction::ToString(), and v8::internal::JSFunction::ToString().
Referenced by v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForFunction().
GetInspector()
v8_inspector::V8Inspector * v8::debug::GetInspector (Isolate * isolate)
Definition at line 61 of file debug-interface.cc.
                                                        {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(isolate);
  i::DisallowJavascriptExecutionDebugOnly no_execution(i_isolate);
  i::DisallowExceptionsDebugOnly no_exceptions(i_isolate);
  return i_isolate->inspector();
}
Referenced by v8_inspector::V8RuntimeAgentImpl::bindingCallback(), v8_inspector::InjectedScript::bindRemoteObjectIfNeeded(), v8_inspector::InjectedScript::ProtocolPromiseHandler::catchCallback(), v8_inspector::InjectedScript::ProtocolPromiseHandler::cleanup(), v8_inspector::anonymous_namespace{value-mirror.cc}::clientFor(), v8_inspector::anonymous_namespace{custom-preview.cc}::getInjectedScript(), v8_inspector::ValueMirror::getInternalProperties(), v8_inspector::anonymous_namespace{custom-preview.cc}::reportError(), v8_inspector::V8Debugger::terminateExecutionCompletedCallback(), v8_inspector::InjectedScript::ProtocolPromiseHandler::thenCallback(), and v8_inspector::anonymous_namespace{value-mirror.cc}::v8InternalValueTypeFrom().
GetInternalProperties()
MaybeLocal< Array > v8::debug::GetInternalProperties (Isolate * isolate, Local< Value > value)
Returns array of internal properties specific to the value type.
Result has the following format: [<name>,
,...,<name>,
]. Result array will be allocated in the current context.
Definition at line 187 of file debug-interface.cc.
                                                            {
  i::Isolate* isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  EnterV8NoScriptNoExceptionScope api_scope(isolate);
  i::DirectHandle<i::Object> val = Utils::OpenDirectHandle(*value);
  i::DirectHandle<i::JSArray> result;
  if (!i::Runtime::GetInternalProperties(isolate, val).ToHandle(&result))
    return MaybeLocal<Array>();
  return Utils::ToLocal(result);
}
References v8::internal::Runtime::GetInternalProperties(), v8::Utils::OpenDirectHandle(), v8::base::internal::result, v8::anonymous_namespace{api.cc}::ToHandle(), and v8::internal::value.
Referenced by v8_inspector::V8Debugger::internalProperties().
GetIsolateId()
uint64_t v8::debug::GetIsolateId (v8::Isolate * v8_isolate)
Definition at line 1477 of file debug-interface.cc.
                                             {
  i::Isolate* isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  return isolate->debug()->IsolateId();
}
References v8::internal::Isolate::debug(), and v8::internal::Debug::IsolateId().
Referenced by v8_inspector::V8InspectorImpl::isolateId().
GetLoadedScripts()
V8_EXPORT_PRIVATE void v8::debug::GetLoadedScripts (Isolate * v8_isolate, std::vector< v8::Global< Script >> & scripts)
Definition at line 983 of file debug-interface.cc.
                                                            {
  i::Isolate* isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  EnterV8NoScriptNoExceptionScope api_scope(isolate);
  {
    i::DisallowGarbageCollection no_gc;
    i::Script::Iterator iterator(isolate);
    for (i::Tagged<i::Script> script = iterator.Next(); !script.is_null();
         script = iterator.Next()) {
#if V8_ENABLE_WEBASSEMBLY
      if (script->type() != i::Script::Type::kNormal &&
          script->type() != i::Script::Type::kWasm) {
        continue;
      }
#else
      if (script->type() != i::Script::Type::kNormal) continue;
#endif // V8_ENABLE_WEBASSEMBLY
      if (!script->HasValidSource()) continue;
      i::HandleScope handle_scope(isolate);
      i::DirectHandle<i::Script> script_handle(script, isolate);
      scripts.emplace_back(v8_isolate, ToApiHandle<Script>(script_handle));
    }
  }
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::script.
Referenced by v8_inspector::V8Debugger::getCompiledScripts().
GetMessageFromPromise()
MaybeLocal< Message > v8::debug::GetMessageFromPromise (Local< Promise > p)
Definition at line 1454 of file debug-interface.cc.
                                                            {
  i::DirectHandle<i::JSPromise> promise = Utils::OpenDirectHandle(*p);
  i::Isolate* isolate = i::Isolate::Current();
  i::DirectHandle<i::Symbol> key =
      isolate->factory()->promise_debug_message_symbol();
  i::DirectHandle<i::Object> maybeMessage =
      i::JSReceiver::GetDataProperty(isolate, promise, key);
  if (!IsJSMessageObject(*maybeMessage, isolate)) return MaybeLocal<Message>();
  return ToApiHandle<Message>(i::Cast<i::JSMessageObject>(maybeMessage));
}
References v8::internal::Isolate::Current(), v8::internal::Isolate::factory(), v8::internal::JSReceiver::GetDataProperty(), v8::internal::key, and v8::Utils::OpenDirectHandle().
Referenced by v8_inspector::InjectedScript::ProtocolPromiseHandler::catchCallback().
GetNextRandomInt64()
int64_t v8::debug::GetNextRandomInt64 (v8::Isolate * v8_isolate)
Definition at line 1288 of file debug-interface.cc.
                                                  {
  return reinterpret_cast<i::Isolate*>(v8_isolate)
      ->random_number_generator()
      ->NextInt64();
}
Referenced by v8_inspector::V8InspectorImpl::generateUniqueId().
GetPrivateMembers()
V8_EXPORT_PRIVATE bool v8::debug::GetPrivateMembers (Local< Context > context, Local< Object > value, int filter, LocalVector< Value > * names_out, LocalVector< Value > * values_out)
Retrieve both instance and static private members on an object.
filter should be a combination of PrivateMemberFilter. Returns through the out parameters names_out a vector of names in v8::String and through values_out the corresponding values. Private fields and methods are returned directly while accessors are returned as v8::debug::AccessorPair. Missing components in the accessor pairs are null. If an exception occurs, false is returned. Otherwise true is returned. Results will be allocated in the current context and handle scope.
Definition at line 231 of file debug-interface.cc.
                                                       {
  i::Isolate* isolate = i::Isolate::Current();
  ApiRuntimeCallStatsScope rcs_scope(
      isolate, i::RuntimeCallCounterId::kAPI_debug_GetPrivateMembers);
  EnterV8NoScriptNoExceptionScope api_scope(isolate);
  bool include_methods =
      filter & static_cast<int>(PrivateMemberFilter::kPrivateMethods);
  bool include_fields =
      filter & static_cast<int>(PrivateMemberFilter::kPrivateFields);
  bool include_accessors =
      filter & static_cast<int>(PrivateMemberFilter::kPrivateAccessors);
  bool include_methods_or_accessors = include_methods || include_accessors;
  auto var_mode_filter =
      include_methods
          ? (include_accessors ? i::IsPrivateMethodOrAccessorVariableMode
                               : i::IsPrivateMethodVariableMode)
          : i::IsPrivateAccessorVariableMode;
  auto constexpr instance_filter = [](i::IsStaticFlag flag) {
    return flag == i::IsStaticFlag::kNotStatic;
  };
  auto constexpr static_filter = [](i::IsStaticFlag flag) {
    return flag == i::IsStaticFlag::kStatic;
  };
  i::DirectHandle<i::JSReceiver> receiver = Utils::OpenDirectHandle(*object);
  i::PropertyFilter key_filter =
      static_cast<i::PropertyFilter>(i::PropertyFilter::PRIVATE_NAMES_ONLY);
  i::DirectHandle<i::FixedArray> keys;
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, keys,
      i::KeyAccumulator::GetKeys(isolate, receiver,
                                 i::KeyCollectionMode::kOwnOnly, key_filter,
                                 i::GetKeysConversion::kConvertToString),
      false);
  // Estimate number of private fields and private instance methods/accessors.
  int private_entries_count = 0;
  auto count_private_entry =
      [&](i::VariableMode mode, i::DirectHandle<i::String>,
          i::DirectHandle<i::Object>) { private_entries_count++; };
  for (int i = 0; i < keys->length(); ++i) {
    // Exclude the private brand symbols.
    i::DirectHandle<i::Symbol> key(i::Cast<i::Symbol>(keys->get(i)), isolate);
    if (key->is_private_brand()) {
      if (include_methods_or_accessors) {
        i::DirectHandle<i::Object> value;
        ASSIGN_RETURN_ON_EXCEPTION_VALUE(
            isolate, value, i::Object::GetProperty(isolate, receiver, key),
            false);
        i::DirectHandle<i::Context> value_context(i::Cast<i::Context>(*value),
                                                  isolate);
        ForEachContextLocal(isolate, value_context, var_mode_filter,
                            instance_filter, count_private_entry);
      }
    } else if (include_fields) {
      private_entries_count++;
    }
  }
  // Estimate number of static private methods/accessors for classes.
  bool has_static_private_methods_or_accessors = false;
  if (include_methods_or_accessors) {
    if (IsJSFunction(*receiver)) {
      i::DirectHandle<i::JSFunction> func(i::Cast<i::JSFunction>(*receiver),
                                          isolate);
      i::DirectHandle<i::SharedFunctionInfo> shared(func->shared(), isolate);
      if (shared->is_class_constructor() &&
          shared->has_static_private_methods_or_accessors()) {
        has_static_private_methods_or_accessors = true;
        i::DirectHandle<i::Context> func_context(func->context(), isolate);
        ForEachContextLocal(isolate, func_context, var_mode_filter,
                            static_filter, count_private_entry);
      }
    }
  }
  DCHECK(names_out->empty());
  names_out->reserve(private_entries_count);
  DCHECK(values_out->empty());
  values_out->reserve(private_entries_count);
  auto add_private_entry = [&](i::VariableMode mode,
                               i::DirectHandle<i::String> name,
                               i::DirectHandle<i::Object> value) {
    DCHECK_IMPLIES(mode == i::VariableMode::kPrivateMethod,
                   IsJSFunction(*value));
    DCHECK_IMPLIES(mode != i::VariableMode::kPrivateMethod,
                   IsAccessorPair(*value));
    names_out->push_back(Utils::ToLocal(name));
    values_out->push_back(Utils::ToLocal(value));
  };
  if (has_static_private_methods_or_accessors) {
    i::DirectHandle<i::Context> receiver_context(
        i::Cast<i::JSFunction>(*receiver)->context(), isolate);
    ForEachContextLocal(isolate, receiver_context, var_mode_filter,
                        static_filter, add_private_entry);
  }
  for (int i = 0; i < keys->length(); ++i) {
    i::DirectHandle<i::Object> obj_key(keys->get(i), isolate);
    i::DirectHandle<i::Symbol> key(i::Cast<i::Symbol>(*obj_key), isolate);
    CHECK(key->is_private_name());
    i::DirectHandle<i::Object> value;
    ASSIGN_RETURN_ON_EXCEPTION_VALUE(
        isolate, value, i::Object::GetProperty(isolate, receiver, key), false);
    if (key->is_private_brand()) {
      if (include_methods_or_accessors) {
        DCHECK(IsContext(*value));
        i::DirectHandle<i::Context> value_context(i::Cast<i::Context>(*value),
                                                  isolate);
        ForEachContextLocal(isolate, value_context, var_mode_filter,
                            instance_filter, add_private_entry);
      }
    } else if (include_fields) { // Private fields
      i::DirectHandle<i::String> name(
          i::Cast<i::String>(i::Cast<i::Symbol>(*key)->description()), isolate);
      names_out->push_back(Utils::ToLocal(name));
      values_out->push_back(Utils::ToLocal(value));
    }
  }
  DCHECK_EQ(names_out->size(), values_out->size());
  DCHECK_LE(names_out->size(), private_entries_count);
  return true;
}
References ASSIGN_RETURN_ON_EXCEPTION_VALUE, CHECK, v8::internal::Isolate::Current(), DCHECK, DCHECK_EQ, DCHECK_IMPLIES, DCHECK_LE, v8::LocalVector< T >::empty(), v8::debug::anonymous_namespace{debug-interface.cc}::ForEachContextLocal(), v8::internal::KeyAccumulator::GetKeys(), v8::internal::Object::GetProperty(), v8::internal::has_static_private_methods_or_accessors, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::IsPrivateAccessorVariableMode(), v8::internal::IsPrivateMethodOrAccessorVariableMode(), v8::internal::IsPrivateMethodVariableMode(), v8::internal::key, kPrivateAccessors, kPrivateFields, kPrivateMethods, mode(), name, v8::Utils::OpenDirectHandle(), v8::internal::PRIVATE_NAMES_ONLY, v8::LocalVector< T >::push_back(), v8::LocalVector< T >::reserve(), v8::LocalVector< T >::size(), and v8::internal::value.
Referenced by v8_inspector::ValueMirror::getPrivateProperties(), and v8_inspector::V8Debugger::privateMethods().
GetScriptOrigin()
V8_EXPORT_PRIVATE std::optional< v8::ScriptOrigin > v8::debug::GetScriptOrigin (Isolate * v8_isolate, int script_id)
Definition at line 1008 of file debug-interface.cc.
                                                               {
  i::Isolate* isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  EnterV8NoScriptNoExceptionScope api_scope(isolate);
  {
    i::DisallowGarbageCollection no_gc;
    i::Script::Iterator iterator(isolate);
    for (i::Tagged<i::Script> script = iterator.Next(); !script.is_null();
         script = iterator.Next()) {
      if (script->id() == script_id) {
        i::DirectHandle<i::Object> scriptName(script->GetNameOrSourceURL(),
                                              isolate);
        i::DirectHandle<i::Object> source_map_url(script->source_mapping_url(),
                                                  isolate);
        i::DirectHandle<i::Object> host_defined_options(
            script->host_defined_options(), isolate);
        ScriptOriginOptions options(script->origin_options());
        bool is_wasm = false;
#if V8_ENABLE_WEBASSEMBLY
        is_wasm = script->type() == i::Script::Type::kWasm;
#endif // V8_ENABLE_WEBASSEMBLY
        v8::ScriptOrigin origin(
            Utils::ToLocal(scriptName), script->line_offset(),
            script->column_offset(), options.IsSharedCrossOrigin(),
            script->id(), Utils::ToLocal(source_map_url), options.IsOpaque(),
            is_wasm, options.IsModule(), Utils::ToLocal(host_defined_options));
        return origin;
      }
    }
  }
  return std::nullopt;
}
References v8::ScriptOriginOptions::IsModule(), v8::ScriptOriginOptions::IsOpaque(), v8::ScriptOriginOptions::IsSharedCrossOrigin(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::script.
Referenced by v8_inspector::V8ConsoleMessage::reportToFrontend().
GlobalLexicalScopeNames()
void v8::debug::GlobalLexicalScopeNames (v8::Local< v8::Context > v8_context, std::vector< v8::Global< v8::String >> * names)
Definition at line 1264 of file debug-interface.cc.
                                                                   {
  auto context = Utils::OpenDirectHandle(*v8_context);
  i::Isolate* isolate = i::Isolate::Current();
  i::DirectHandle<i::ScriptContextTable> table(
      context->native_context()->script_context_table(), isolate);
  for (int i = 0; i < table->length(kAcquireLoad); i++) {
    i::DirectHandle<i::Context> script_context(table->get(i), isolate);
    DCHECK(script_context->IsScriptContext());
    i::DirectHandle<i::ScopeInfo> scope_info(script_context->scope_info(),
                                             isolate);
    for (auto it : i::ScopeInfo::IterateLocalNames(scope_info)) {
      if (i::ScopeInfo::VariableIsSynthetic(it->name())) continue;
      names->emplace_back(reinterpret_cast<Isolate*>(isolate),
                          Utils::ToLocal(direct_handle(it->name(), isolate)));
    }
  }
}
References v8::internal::Isolate::Current(), DCHECK, v8::internal::direct_handle(), v8::internal::ScopeInfo::IterateLocalNames(), v8::kAcquireLoad, v8::Utils::OpenDirectHandle(), and v8::internal::ScopeInfo::VariableIsSynthetic().
Referenced by v8_inspector::V8RuntimeAgentImpl::globalLexicalScopeNames().
NotifyDebuggerPausedEventSent()
void v8::debug::NotifyDebuggerPausedEventSent (v8::Isolate * v8_isolate)
Definition at line 1472 of file debug-interface.cc.
                                                          {
  i::Isolate* isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  isolate->debug()->NotifyDebuggerPausedEventSent();
}
References v8::internal::Isolate::debug(), and v8::internal::Debug::NotifyDebuggerPausedEventSent().
Referenced by v8_inspector::V8DebuggerAgentImpl::didPause().
PrepareRestartFrame()
bool v8::debug::PrepareRestartFrame (Isolate * v8_isolate, int callFrameOrdinal)
Definition at line 400 of file debug-interface.cc.
                                                                    {
  i::Isolate* isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  EnterV8BasicScope api_scope(isolate);
  CHECK(isolate->debug()->CheckExecutionState());
  i::DebugStackTraceIterator it(isolate, callFrameOrdinal);
  if (it.Done() || !it.CanBeRestarted()) return false;
  // Clear all current stepping setup.
  isolate->debug()->ClearStepping();
  it.PrepareRestart();
  return true;
}
References v8::internal::DebugStackTraceIterator::CanBeRestarted(), CHECK, v8::internal::Debug::CheckExecutionState(), v8::internal::Debug::ClearStepping(), v8::internal::Isolate::debug(), v8::internal::DebugStackTraceIterator::Done(), and v8::internal::DebugStackTraceIterator::PrepareRestart().
Referenced by v8_inspector::V8Debugger::restartFrame().
PrepareStep()
void v8::debug::PrepareStep (Isolate * v8_isolate, StepAction action)
Definition at line 390 of file debug-interface.cc.
                                                         {
  i::Isolate* isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  EnterV8BasicScope api_scope(isolate);
  CHECK(isolate->debug()->CheckExecutionState());
  // Clear all current stepping setup.
  isolate->debug()->ClearStepping();
  // Prepare step.
  isolate->debug()->PrepareStep(static_cast<i::StepAction>(action));
}
References CHECK, v8::internal::Debug::CheckExecutionState(), v8::internal::Debug::ClearStepping(), v8::internal::Isolate::debug(), and v8::internal::Debug::PrepareStep().
Referenced by v8_inspector::V8Debugger::handleProgramBreak(), v8::internal::wasm::gdb_server::WasmModuleDebug::PrepareStep(), v8_inspector::V8Debugger::stepIntoStatement(), v8_inspector::V8Debugger::stepOutOfFunction(), and v8_inspector::V8Debugger::stepOverStatement().
RecordAsyncStackTaggingCreateTaskCall()
void v8::debug::RecordAsyncStackTaggingCreateTaskCall (v8::Isolate * v8_isolate)
Definition at line 1467 of file debug-interface.cc.
                                                                  {
  i::Isolate* isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  isolate->CountUsage(v8::Isolate::kAsyncStackTaggingCreateTaskCall);
}
References v8::internal::Isolate::CountUsage(), and v8::Isolate::kAsyncStackTaggingCreateTaskCall.
Referenced by v8_inspector::V8Console::createTask().
RemoveBreakpoint()
void v8::debug::RemoveBreakpoint (Isolate * v8_isolate, BreakpointId id)
Definition at line 794 of file debug-interface.cc.
                                                            {
  i::Isolate* isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  i::HandleScope handle_scope(isolate);
  isolate->debug()->RemoveBreakpoint(id);
}
References v8::internal::Isolate::debug(), and v8::internal::Debug::RemoveBreakpoint().
Referenced by v8_inspector::V8Debugger::clearContinueToLocation(), and v8_inspector::V8Debugger::removeBreakpoint().
ResetBlackboxedStateCache()
void v8::debug::ResetBlackboxedStateCache (Isolate * v8_isolate, Local< Script > script)
Definition at line 1087 of file debug-interface.cc.
                                                                          {
  i::Isolate* isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  EnterV8NoScriptNoExceptionScope api_scope(isolate);
  i::DisallowGarbageCollection no_gc;
  i::SharedFunctionInfo::ScriptIterator iter(isolate,
                                             *Utils::OpenDirectHandle(*script));
  for (i::Tagged<i::SharedFunctionInfo> info = iter.Next(); !info.is_null();
       info = iter.Next()) {
    if (auto debug_info = isolate->debug()->TryGetDebugInfo(info)) {
      debug_info.value()->set_computed_debug_is_blackboxed(false);
    }
  }
}
References v8::internal::Isolate::debug(), v8::internal::Tagged< HeapObject >::is_null(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::Utils::OpenDirectHandle(), v8::internal::script, and v8::internal::Debug::TryGetDebugInfo().
Referenced by v8_inspector::V8DebuggerScript::resetBlackboxedStateCache().
SetAsyncEventDelegate()
V8_EXPORT_PRIVATE void v8::debug::SetAsyncEventDelegate (Isolate * v8_isolate, AsyncEventDelegate * delegate)
Definition at line 1083 of file debug-interface.cc.
                                                                              {
  reinterpret_cast<i::Isolate*>(v8_isolate)->set_async_event_delegate(delegate);
}
Referenced by v8_inspector::V8Debugger::setAsyncCallStackDepth().
SetBreakOnNextFunctionCall()
V8_EXPORT_PRIVATE void v8::debug::SetBreakOnNextFunctionCall (Isolate * isolate)
Definition at line 173 of file debug-interface.cc.
                                                  {
  auto i_isolate = reinterpret_cast<i::Isolate*>(isolate);
  i::DisallowJavascriptExecutionDebugOnly no_execution(i_isolate);
  i::DisallowExceptionsDebugOnly no_exceptions(i_isolate);
  i_isolate->debug()->SetBreakOnNextFunctionCall();
}
Referenced by v8_inspector::V8Debugger::asyncTaskStartedForStepping(), v8_inspector::V8Debugger::externalAsyncTaskStarted(), v8_inspector::V8Debugger::setPauseOnNextCall(), and v8::internal::wasm::gdb_server::GdbServer::Suspend().
SetBreakPointsActive()
void v8::debug::SetBreakPointsActive (Isolate * v8_isolate, bool is_active)
Definition at line 384 of file debug-interface.cc.
                                                               {
  i::Isolate* isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  EnterV8NoScriptNoExceptionScope api_scope(isolate);
  isolate->debug()->set_break_points_active(is_active);
}
References v8::internal::Isolate::debug(), and v8::internal::Debug::set_break_points_active().
Referenced by v8_inspector::V8Debugger::setBreakpointsActive().
SetConsoleDelegate()
V8_EXPORT_PRIVATE void v8::debug::SetConsoleDelegate (Isolate * v8_isolate, ConsoleDelegate * delegate)
Definition at line 1159 of file debug-interface.cc.
                                                                        {
  i::Isolate* isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  i::DisallowJavascriptExecutionDebugOnly no_execution(isolate);
  i::DisallowExceptionsDebugOnly no_exceptions(isolate);
  if (delegate == nullptr) {
    isolate->set_console_delegate(nullptr);
  } else {
    isolate->set_console_delegate(delegate);
  }
}
References v8::internal::Isolate::set_console_delegate().
Referenced by v8::Shell::Initialize(), v8_inspector::V8InspectorImpl::V8InspectorImpl(), and v8_inspector::V8InspectorImpl::~V8InspectorImpl().
SetContextId()
void v8::debug::SetContextId (Local< Context > context, int id)
Definition at line 33 of file debug-interface.cc.
                                                  {
  auto v8_context = Utils::OpenDirectHandle(*context);
  auto* i_isolate = i::Isolate::Current();
  i::DisallowJavascriptExecutionDebugOnly no_execution(i_isolate);
  i::DisallowExceptionsDebugOnly no_exceptions(i_isolate);
  v8_context->set_debug_context_id(i::Smi::FromInt(id));
}
References v8::internal::Isolate::Current(), v8::internal::Smi::FromInt(), and v8::Utils::OpenDirectHandle().
Referenced by v8_inspector::InspectedContext::InspectedContext().
SetDebugDelegate()
V8_EXPORT_PRIVATE void v8::debug::SetDebugDelegate (Isolate * v8_isolate, DebugDelegate * delegate)
Definition at line 1078 of file debug-interface.cc.
                                                                    {
  i::Isolate* isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  isolate->debug()->SetDebugDelegate(delegate);
}
References v8::internal::Isolate::debug(), and v8::internal::Debug::SetDebugDelegate().
Referenced by v8_inspector::V8Debugger::disable(), v8::Shell::DisableDebugger(), v8_inspector::V8Debugger::enable(), and v8::Shell::EnableDebugger().
SetFunctionBreakpoint()
V8_EXPORT_PRIVATE bool v8::debug::SetFunctionBreakpoint (v8::Local< v8::Function > function, v8::Local< v8::String > condition, BreakpointId * id)
Definition at line 1303 of file debug-interface.cc.
                                                                          {
  auto callable = Utils::OpenDirectHandle(*function);
  if (!IsJSFunction(*callable)) return false;
  auto jsfunction = i::Cast<i::JSFunction>(callable);
  i::Isolate* isolate = i::Isolate::Current();
  i::DirectHandle<i::String> condition_string =
      condition.IsEmpty()
          ? i::DirectHandle<i::String>(isolate->factory()->empty_string())
          : Utils::OpenDirectHandle(*condition);
  return isolate->debug()->SetBreakpointForFunction(
      handle(jsfunction->shared(), isolate), condition_string, id);
}
References v8::internal::Isolate::Current(), v8::internal::Isolate::debug(), v8::internal::Isolate::factory(), v8::internal::handle(), v8::api_internal::IndirectHandleBase::IsEmpty(), v8::Utils::OpenDirectHandle(), and v8::internal::Debug::SetBreakpointForFunction().
Referenced by v8_inspector::V8DebuggerAgentImpl::setBreakpointImpl().
SetInspector()
void v8::debug::SetInspector (Isolate * isolate, v8_inspector::V8Inspector * inspector)
Definition at line 50 of file debug-interface.cc.
                                                                        {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(isolate);
  i::DisallowJavascriptExecutionDebugOnly no_execution(i_isolate);
  i::DisallowExceptionsDebugOnly no_exceptions(i_isolate);
  if (inspector == nullptr) {
    i_isolate->set_inspector(nullptr);
  } else {
    i_isolate->set_inspector(inspector);
  }
}
Referenced by v8_inspector::V8InspectorImpl::V8InspectorImpl(), and v8_inspector::V8InspectorImpl::~V8InspectorImpl().
SetIsolateId()
void v8::debug::SetIsolateId (v8::Isolate * v8_isolate, uint64_t id)
Definition at line 1482 of file debug-interface.cc.
                                                      {
  i::Isolate* isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  isolate->debug()->SetIsolateId(id);
}
References v8::internal::Isolate::debug(), and v8::internal::Debug::SetIsolateId().
Referenced by v8_inspector::V8InspectorImpl::V8InspectorImpl().
SetReturnValue()
void v8::debug::SetReturnValue (v8::Isolate * v8_isolate, v8::Local< v8::Value > value)
Definition at line 1283 of file debug-interface.cc.
                                                                   {
  i::Isolate* isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  isolate->debug()->set_return_value(*Utils::OpenDirectHandle(*value));
}
References v8::internal::Isolate::debug(), v8::Utils::OpenDirectHandle(), v8::internal::Debug::set_return_value(), and v8::internal::value.
Referenced by v8::internal::torque::ImplementationVisitor::InlineMacro(), v8_inspector::V8DebuggerAgentImpl::setReturnValue(), and v8::internal::torque::ImplementationVisitor::Visit().
SetTerminateOnResume()
V8_EXPORT_PRIVATE void v8::debug::SetTerminateOnResume (Isolate * v8_isolate)
Definition at line 429 of file debug-interface.cc.
                                               {
  i::Isolate* isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  EnterV8NoScriptNoExceptionScope api_scope(isolate);
  isolate->debug()->SetTerminateOnResume();
}
References v8::internal::Isolate::debug(), and v8::internal::Debug::SetTerminateOnResume().
Referenced by v8_inspector::V8Debugger::continueProgram().