v8::internal::anonymous_namespace{call-site-info.cc} Namespace Reference
Functions
MaybeHandle< String > FormatEvalOrigin (Isolate *isolate, DirectHandle< Script > script)
Tagged< PrimitiveHeapObject > InferMethodNameFromFastObject (Isolate *isolate, Tagged< JSObject > receiver, Tagged< JSFunction > fun, Tagged< PrimitiveHeapObject > name)
template<typename Dictionary >
Tagged< PrimitiveHeapObject > InferMethodNameFromDictionary (Isolate *isolate, Tagged< Dictionary > dictionary, Tagged< JSFunction > fun, Tagged< PrimitiveHeapObject > name)
Tagged< PrimitiveHeapObject > InferMethodName (Isolate *isolate, Tagged< JSReceiver > receiver, Tagged< JSFunction > fun)
bool IsNonEmptyString (DirectHandle< Object > object)
void AppendFileLocation (Isolate *isolate, DirectHandle< CallSiteInfo > frame, IncrementalStringBuilder *builder)
bool StringEndsWithMethodName (Isolate *isolate, DirectHandle< String > subject, DirectHandle< String > pattern)
void AppendMethodCall (Isolate *isolate, DirectHandle< CallSiteInfo > frame, IncrementalStringBuilder *builder)
void SerializeJSStackFrame (Isolate *isolate, DirectHandle< CallSiteInfo > frame, IncrementalStringBuilder *builder)
Function Documentation
AppendFileLocation()
void v8::internal::anonymous_namespace{call-site-info.cc}::AppendFileLocation (Isolate * isolate, DirectHandle< CallSiteInfo > frame, IncrementalStringBuilder * builder)
Definition at line 693 of file call-site-info.cc.
                                                           {
  DirectHandle<Object> script_name_or_source_url(
      frame->GetScriptNameOrSourceURL(), isolate);
  if (!IsString(*script_name_or_source_url) && frame->IsEval()) {
    builder->AppendString(Cast<String>(CallSiteInfo::GetEvalOrigin(frame)));
    // Expecting source position to follow.
    builder->AppendCStringLiteral(", ");
  }
  if (IsNonEmptyString(script_name_or_source_url)) {
    builder->AppendString(Cast<String>(script_name_or_source_url));
  } else {
    // Source code does not originate from a file and is not native, but we
    // can still get the source position inside the source string, e.g. in
    // an eval string.
    builder->AppendCStringLiteral("<anonymous>");
  }
  int line_number = CallSiteInfo::GetLineNumber(frame);
  if (line_number != Message::kNoLineNumberInfo) {
    builder->AppendCharacter(':');
    builder->AppendInt(line_number);
    int column_number = CallSiteInfo::GetColumnNumber(frame);
    if (column_number != Message::kNoColumnInfo) {
      builder->AppendCharacter(':');
      builder->AppendInt(column_number);
    }
  }
}
References v8::internal::IncrementalStringBuilder::AppendCharacter(), v8::internal::IncrementalStringBuilder::AppendCStringLiteral(), v8::internal::IncrementalStringBuilder::AppendInt(), v8::internal::IncrementalStringBuilder::AppendString(), v8::internal::CallSiteInfo::GetColumnNumber(), v8::internal::CallSiteInfo::GetEvalOrigin(), v8::internal::CallSiteInfo::GetLineNumber(), IsNonEmptyString(), v8::Message::kNoColumnInfo, and v8::Message::kNoLineNumberInfo.
Referenced by SerializeJSStackFrame().
AppendMethodCall()
void v8::internal::anonymous_namespace{call-site-info.cc}::AppendMethodCall (Isolate * isolate, DirectHandle< CallSiteInfo > frame, IncrementalStringBuilder * builder)
Definition at line 757 of file call-site-info.cc.
                                                         {
  DirectHandle<Object> type_name = CallSiteInfo::GetTypeName(frame);
  DirectHandle<Object> method_name = CallSiteInfo::GetMethodName(frame);
  DirectHandle<Object> function_name = CallSiteInfo::GetFunctionName(frame);
  if (IsNonEmptyString(function_name)) {
    DirectHandle<String> function_string = Cast<String>(function_name);
    if (IsNonEmptyString(type_name)) {
      DirectHandle<String> type_string = Cast<String>(type_name);
      if (String::IsIdentifier(isolate, function_string) &&
          !String::Equals(isolate, function_string, type_string)) {
        builder->AppendString(type_string);
        builder->AppendCharacter('.');
      }
    }
    builder->AppendString(function_string);
    if (IsNonEmptyString(method_name)) {
      DirectHandle<String> method_string = Cast<String>(method_name);
      if (!StringEndsWithMethodName(isolate, function_string, method_string)) {
        builder->AppendCStringLiteral(" [as ");
        builder->AppendString(method_string);
        builder->AppendCharacter(']');
      }
    }
  } else {
    if (IsNonEmptyString(type_name)) {
      builder->AppendString(Cast<String>(type_name));
      builder->AppendCharacter('.');
    }
    if (IsNonEmptyString(method_name)) {
      builder->AppendString(Cast<String>(method_name));
    } else {
      builder->AppendCStringLiteral("<anonymous>");
    }
  }
}
References v8::internal::IncrementalStringBuilder::AppendCharacter(), v8::internal::IncrementalStringBuilder::AppendCStringLiteral(), v8::internal::IncrementalStringBuilder::AppendString(), v8::internal::String::Equals(), v8::internal::CallSiteInfo::GetFunctionName(), v8::internal::CallSiteInfo::GetMethodName(), v8::internal::CallSiteInfo::GetTypeName(), v8::internal::String::IsIdentifier(), IsNonEmptyString(), and StringEndsWithMethodName().
Referenced by SerializeJSStackFrame().
FormatEvalOrigin()
MaybeHandle<String> v8::internal::anonymous_namespace{call-site-info.cc}::FormatEvalOrigin (Isolate * isolate, DirectHandle< Script > script)
Definition at line 224 of file call-site-info.cc.
                                                                  {
  Handle<Object> sourceURL(script->GetNameOrSourceURL(), isolate);
  if (IsString(*sourceURL)) return Cast<String>(sourceURL);
  IncrementalStringBuilder builder(isolate);
  builder.AppendCStringLiteral("eval at ");
  if (script->has_eval_from_shared()) {
    DirectHandle<SharedFunctionInfo> eval_shared(script->eval_from_shared(),
                                                 isolate);
    auto eval_name = SharedFunctionInfo::DebugName(isolate, eval_shared);
    if (eval_name->length() != 0) {
      builder.AppendString(eval_name);
    } else {
      builder.AppendCStringLiteral("<anonymous>");
    }
    if (IsScript(eval_shared->script())) {
      DirectHandle<Script> eval_script(Cast<Script>(eval_shared->script()),
                                       isolate);
      builder.AppendCStringLiteral(" (");
      if (eval_script->compilation_type() == Script::CompilationType::kEval) {
        // Eval script originated from another eval.
        DirectHandle<String> str;
        ASSIGN_RETURN_ON_EXCEPTION(isolate, str,
                                   FormatEvalOrigin(isolate, eval_script));
        builder.AppendString(str);
      } else {
        // eval script originated from "real" source.
        DirectHandle<Object> eval_script_name(eval_script->name(), isolate);
        if (IsString(*eval_script_name)) {
          builder.AppendString(Cast<String>(eval_script_name));
          Script::PositionInfo info;
          if (Script::GetPositionInfo(eval_script,
                                      Script::GetEvalPosition(isolate, script),
                                      &info, Script::OffsetFlag::kNoOffset)) {
            builder.AppendCharacter(':');
            builder.AppendInt(info.line + 1);
            builder.AppendCharacter(':');
            builder.AppendInt(info.column + 1);
          }
        } else {
          builder.AppendCStringLiteral("unknown source");
        }
      }
      builder.AppendCharacter(')');
    }
  } else {
    builder.AppendCStringLiteral("<anonymous>");
  }
  return indirect_handle(builder.Finish().ToHandleChecked(), isolate);
}
References v8::internal::IncrementalStringBuilder::AppendCharacter(), v8::internal::IncrementalStringBuilder::AppendCStringLiteral(), v8::internal::IncrementalStringBuilder::AppendInt(), v8::internal::IncrementalStringBuilder::AppendString(), ASSIGN_RETURN_ON_EXCEPTION, v8::internal::Script::PositionInfo::column, v8::internal::SharedFunctionInfo::DebugName(), v8::internal::IncrementalStringBuilder::Finish(), v8::internal::Script::GetEvalPosition(), v8::internal::Script::GetPositionInfo(), v8::internal::indirect_handle(), v8::internal::Script::kEval, v8::internal::Script::kNoOffset, v8::internal::Script::PositionInfo::line, and v8::internal::script.
Referenced by v8::internal::CallSiteInfo::GetEvalOrigin().
InferMethodName()
Tagged<PrimitiveHeapObject> v8::internal::anonymous_namespace{call-site-info.cc}::InferMethodName (Isolate * isolate, Tagged< JSReceiver > receiver, Tagged< JSFunction > fun)
Definition at line 418 of file call-site-info.cc.
                                                                    {
  DisallowGarbageCollection no_gc;
  ReadOnlyRoots roots(isolate);
  Tagged<PrimitiveHeapObject> name = roots.undefined_value();
  for (PrototypeIterator it(isolate, receiver, kStartAtReceiver); !it.IsAtEnd();
       it.Advance()) {
    auto current = it.GetCurrent();
    if (!IsJSObject(current)) break;
    auto object = Cast<JSObject>(current);
    if (IsAccessCheckNeeded(object)) break;
    if (object->HasFastProperties()) {
      name = InferMethodNameFromFastObject(isolate, object, fun, name);
    } else if (IsJSGlobalObject(object)) {
      name = InferMethodNameFromDictionary(
          isolate,
          Cast<JSGlobalObject>(object)->global_dictionary(kAcquireLoad), fun,
          name);
    } else if (V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
      name = InferMethodNameFromDictionary(
          isolate, object->property_dictionary_swiss(), fun, name);
    } else {
      name = InferMethodNameFromDictionary(
          isolate, object->property_dictionary(), fun, name);
    }
  }
  if (IsUndefined(name, isolate)) return roots.null_value();
  return name;
}
References InferMethodNameFromDictionary(), InferMethodNameFromFastObject(), v8::internal::PrototypeIterator::IsAtEnd(), v8::kAcquireLoad, v8::internal::kStartAtReceiver, v8::internal::name, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL.
Referenced by v8::internal::CallSiteInfo::GetMethodName().
InferMethodNameFromDictionary()
template<typename Dictionary >
Tagged<PrimitiveHeapObject> v8::internal::anonymous_namespace{call-site-info.cc}::InferMethodNameFromDictionary (Isolate * isolate, Tagged< Dictionary > dictionary, Tagged< JSFunction > fun, Tagged< PrimitiveHeapObject > name)
Definition at line 393 of file call-site-info.cc.
                                      {
  ReadOnlyRoots roots(isolate);
  for (auto i : dictionary->IterateEntries()) {
    Tagged<Object> key;
    if (!dictionary->ToKey(roots, i, &key)) continue;
    if (IsSymbol(key)) continue;
    auto details = dictionary->DetailsAt(i);
    if (details.IsDontEnum()) continue;
    auto value = dictionary->ValueAt(i);
    if (value != fun) {
      if (!IsAccessorPair(value)) continue;
      auto pair = Cast<AccessorPair>(value);
      if (pair->getter() != fun && pair->setter() != fun) continue;
    }
    if (name != key) {
      name = IsUndefined(name, isolate)
                 ? Cast<PrimitiveHeapObject>(key)
                 : Tagged<PrimitiveHeapObject>(roots.null_value());
    }
  }
  return name;
}
References v8::internal::key, v8::internal::name, and v8::internal::value.
Referenced by InferMethodName().
InferMethodNameFromFastObject()
Tagged<PrimitiveHeapObject> v8::internal::anonymous_namespace{call-site-info.cc}::InferMethodNameFromFastObject (Isolate * isolate, Tagged< JSObject > receiver, Tagged< JSFunction > fun, Tagged< PrimitiveHeapObject > name)
Definition at line 358 of file call-site-info.cc.
                                      {
  ReadOnlyRoots roots(isolate);
  Tagged<Map> map = receiver->map();
  Tagged<DescriptorArray> descriptors = map->instance_descriptors(isolate);
  for (auto i : map->IterateOwnDescriptors()) {
    Tagged<PrimitiveHeapObject> key = descriptors->GetKey(i);
    if (IsSymbol(key)) continue;
    auto details = descriptors->GetDetails(i);
    if (details.IsDontEnum()) continue;
    Tagged<Object> value;
    if (details.location() == PropertyLocation::kField) {
      auto field_index = FieldIndex::ForPropertyIndex(
          map, details.field_index(), details.representation());
      if (field_index.is_double()) continue;
      value = receiver->RawFastPropertyAt(isolate, field_index);
    } else {
      value = descriptors->GetStrongValue(i);
    }
    if (value != fun) {
      if (!IsAccessorPair(value)) continue;
      auto pair = Cast<AccessorPair>(value);
      if (pair->getter() != fun && pair->setter() != fun) continue;
    }
    if (name != key) {
      name = IsUndefined(name, isolate)
                 ? key
                 : Tagged<PrimitiveHeapObject>(roots.null_value());
    }
  }
  return name;
}
References v8::internal::FieldIndex::ForPropertyIndex(), v8::internal::key, v8::internal::kField, v8::internal::name, and v8::internal::value.
Referenced by InferMethodName().
IsNonEmptyString()
bool v8::internal::anonymous_namespace{call-site-info.cc}::IsNonEmptyString (DirectHandle< Object > object)
Definition at line 689 of file call-site-info.cc.
                                                   {
  return (IsString(*object) && Cast<String>(*object)->length() > 0);
}
Referenced by AppendFileLocation(), AppendMethodCall(), and SerializeJSStackFrame().
SerializeJSStackFrame()
void v8::internal::anonymous_namespace{call-site-info.cc}::SerializeJSStackFrame (Isolate * isolate, DirectHandle< CallSiteInfo > frame, IncrementalStringBuilder * builder)
Definition at line 796 of file call-site-info.cc.
                                                              {
  DirectHandle<Object> function_name = CallSiteInfo::GetFunctionName(frame);
  if (frame->IsAsync()) {
    builder->AppendCStringLiteral("async ");
    if (frame->IsPromiseAll() || frame->IsPromiseAny() ||
        frame->IsPromiseAllSettled()) {
      builder->AppendCStringLiteral("Promise.");
      builder->AppendString(Cast<String>(function_name));
      builder->AppendCStringLiteral(" (index ");
      builder->AppendInt(CallSiteInfo::GetSourcePosition(frame));
      builder->AppendCharacter(')');
      return;
    }
  }
  if (frame->IsMethodCall()) {
    AppendMethodCall(isolate, frame, builder);
  } else if (frame->IsConstructor()) {
    builder->AppendCStringLiteral("new ");
    if (IsNonEmptyString(function_name)) {
      builder->AppendString(Cast<String>(function_name));
    } else {
      builder->AppendCStringLiteral("<anonymous>");
    }
  } else if (IsNonEmptyString(function_name)) {
    builder->AppendString(Cast<String>(function_name));
  } else {
    AppendFileLocation(isolate, frame, builder);
    return;
  }
  builder->AppendCStringLiteral(" (");
  AppendFileLocation(isolate, frame, builder);
  builder->AppendCharacter(')');
}
References v8::internal::IncrementalStringBuilder::AppendCharacter(), v8::internal::IncrementalStringBuilder::AppendCStringLiteral(), AppendFileLocation(), v8::internal::IncrementalStringBuilder::AppendInt(), AppendMethodCall(), v8::internal::IncrementalStringBuilder::AppendString(), v8::internal::CallSiteInfo::GetFunctionName(), v8::internal::CallSiteInfo::GetSourcePosition(), and IsNonEmptyString().
Referenced by v8::internal::SerializeCallSiteInfo().
StringEndsWithMethodName()
bool v8::internal::anonymous_namespace{call-site-info.cc}::StringEndsWithMethodName (Isolate * isolate, DirectHandle< String > subject, DirectHandle< String > pattern)
Definition at line 728 of file call-site-info.cc.
                                                            {
  if (String::Equals(isolate, subject, pattern)) return true;
  FlatStringReader subject_reader(isolate, String::Flatten(isolate, subject));
  FlatStringReader pattern_reader(isolate, String::Flatten(isolate, pattern));
  int pattern_index = pattern_reader.length() - 1;
  int subject_index = subject_reader.length() - 1;
  // Iterate over len + 1.
  for (uint32_t i = 0; i <= pattern_reader.length(); i++) {
    if (subject_index < 0) {
      return false;
    }
    const base::uc32 subject_char = subject_reader.Get(subject_index);
    if (i == pattern_reader.length()) {
      if (subject_char != '.' && subject_char != ' ') return false;
    } else if (subject_char != pattern_reader.Get(pattern_index)) {
      return false;
    }
    pattern_index--;
    subject_index--;
  }
  return true;
}
References v8::internal::String::Equals(), v8::internal::FlatStringReader::Get(), and v8::internal::FlatStringReader::length().
Referenced by AppendMethodCall().