v8::internal::compiler::anonymous_namespace{code-generator-x64.cc} Namespace Reference
Classes
class OutOfLineLoadFloat32NaN
class OutOfLineLoadFloat64NaN
class OutOfLineTruncateDoubleToI
class OutOfLineRecordWrite
Functions
bool HasAddressingMode (Instruction *instr)
bool HasImmediateInput (Instruction *instr, size_t index)
bool HasRegisterInput (Instruction *instr, size_t index)
template<std::memory_order order>
int EmitStore (MacroAssembler *masm, Operand operand, Register value, MachineRepresentation rep)
template<std::memory_order order>
int EmitStore (MacroAssembler *masm, Operand operand, Immediate value, MachineRepresentation rep)
template<> int EmitStore< std::memory_order_relaxed > (MacroAssembler *masm, Operand operand, Immediate value, MachineRepresentation rep)
void RecordTrapInfoIfNeeded (Zone *zone, CodeGenerator *codegen, InstructionCode opcode, Instruction *instr, int pc)
template<std::memory_order order, typename ValueT >
void EmitTSANAwareStore (Zone *zone, CodeGenerator *codegen, MacroAssembler *masm, Operand operand, ValueT value, X64OperandConverter &i, StubCallMode stub_call_mode, MachineRepresentation rep, Instruction *instr)
void EmitTSANRelaxedLoadOOLIfNeeded (Zone *zone, CodeGenerator *codegen, MacroAssembler *masm, Operand operand, X64OperandConverter &i, StubCallMode mode, int size)
void AdjustStackPointerForTailCall (Instruction *instr, MacroAssembler *assembler, Linkage *linkage, OptimizedCompilationInfo *info, FrameAccessState *state, int new_slot_above_sp, bool allow_shrinkage=true)
void SetupSimdImmediateInRegister (MacroAssembler *assembler, uint32_t *imms, XMMRegister reg)
void SetupSimd256ImmediateInRegister (MacroAssembler *assembler, uint32_t *imms, YMMRegister reg, XMMRegister scratch)
constexpr Condition FlagsConditionToCondition (FlagsCondition condition)
bool Is32BitOperand (InstructionOperand *operand)
bool Use32BitMove (InstructionOperand *source, InstructionOperand *destination)
Variables
static const int kQuadWordSize = 16
Function Documentation
AdjustStackPointerForTailCall()
void v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::AdjustStackPointerForTailCall (Instruction * instr, MacroAssembler * assembler, Linkage * linkage, OptimizedCompilationInfo * info, FrameAccessState * state, int new_slot_above_sp, bool allow_shrinkage = true)
Definition at line 1309 of file code-generator-x64.cc.
                                                                {
  int stack_slot_delta;
  if (instr->HasCallDescriptorFlag(CallDescriptor::kIsTailCallForTierUp)) {
    // For this special tail-call mode, the callee has the same arguments and
    // linkage as the caller, and arguments adapter frames must be preserved.
    // Thus we simply have reset the stack pointer register to its original
    // value before frame construction.
    // See also: AssembleConstructFrame.
    DCHECK(!info->is_osr());
    DCHECK(linkage->GetIncomingDescriptor()->CalleeSavedRegisters().is_empty());
    DCHECK(
        linkage->GetIncomingDescriptor()->CalleeSavedFPRegisters().is_empty());
    DCHECK_EQ(state->frame()->GetReturnSlotCount(), 0);
    stack_slot_delta = (state->frame()->GetTotalFrameSlotCount() -
                        kReturnAddressStackSlotCount) *
                       -1;
    DCHECK_LE(stack_slot_delta, 0);
  } else {
    int current_sp_offset = state->GetSPToFPSlotCount() +
                            StandardFrameConstants::kFixedSlotCountAboveFp;
    stack_slot_delta = new_slot_above_sp - current_sp_offset;
  }
  if (stack_slot_delta > 0) {
    assembler->AllocateStackSpace(stack_slot_delta * kSystemPointerSize);
    state->IncreaseSPDelta(stack_slot_delta);
  } else if (allow_shrinkage && stack_slot_delta < 0) {
    assembler->addq(rsp, Immediate(-stack_slot_delta * kSystemPointerSize));
    state->IncreaseSPDelta(stack_slot_delta);
  }
}
References v8::internal::MacroAssembler::AllocateStackSpace(), v8::internal::compiler::CallDescriptor::CalleeSavedFPRegisters(), v8::internal::compiler::CallDescriptor::CalleeSavedRegisters(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LE, v8::internal::compiler::FrameAccessState::frame(), v8::internal::compiler::Linkage::GetIncomingDescriptor(), v8::internal::compiler::Frame::GetReturnSlotCount(), v8::internal::compiler::FrameAccessState::GetSPToFPSlotCount(), v8::internal::compiler::Frame::GetTotalFrameSlotCount(), v8::internal::compiler::Instruction::HasCallDescriptorFlag(), v8::internal::compiler::FrameAccessState::IncreaseSPDelta(), v8::internal::RegListBase< RegisterT >::is_empty(), v8::internal::OptimizedCompilationInfo::is_osr(), v8::internal::CommonFrameConstants::kFixedSlotCountAboveFp, v8::internal::compiler::CallDescriptor::kIsTailCallForTierUp, kReturnAddressStackSlotCount, and v8::internal::kSystemPointerSize.
EmitStore() [1/2]
template<std::memory_order order>
int v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::EmitStore (MacroAssembler * masm, Operand operand, Immediate value, MachineRepresentation rep)
EmitStore() [2/2]
template<std::memory_order order>
int v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::EmitStore (MacroAssembler * masm, Operand operand, Register value, MachineRepresentation rep)
Definition at line 475 of file code-generator-x64.cc.
                                         {
  int store_instr_offset;
  if (order == std::memory_order_relaxed) {
    store_instr_offset = masm->pc_offset();
    switch (rep) {
      case MachineRepresentation::kWord8:
        masm->movb(operand, value);
        break;
      case MachineRepresentation::kWord16:
        masm->movw(operand, value);
        break;
      case MachineRepresentation::kWord32:
        masm->movl(operand, value);
        break;
      case MachineRepresentation::kWord64:
        masm->movq(operand, value);
        break;
      case MachineRepresentation::kTagged:
        masm->StoreTaggedField(operand, value);
        break;
      case MachineRepresentation::kSandboxedPointer:
        masm->StoreSandboxedPointerField(operand, value);
        break;
      case MachineRepresentation::kIndirectPointer:
        masm->StoreIndirectPointerField(operand, value);
        break;
      default:
        UNREACHABLE();
    }
    return store_instr_offset;
  }
  DCHECK_EQ(order, std::memory_order_seq_cst);
  switch (rep) {
    case MachineRepresentation::kWord8:
      masm->movq(kScratchRegister, value);
      store_instr_offset = masm->pc_offset();
      masm->xchgb(kScratchRegister, operand);
      break;
    case MachineRepresentation::kWord16:
      masm->movq(kScratchRegister, value);
      store_instr_offset = masm->pc_offset();
      masm->xchgw(kScratchRegister, operand);
      break;
    case MachineRepresentation::kWord32:
      masm->movq(kScratchRegister, value);
      store_instr_offset = masm->pc_offset();
      masm->xchgl(kScratchRegister, operand);
      break;
    case MachineRepresentation::kWord64:
      masm->movq(kScratchRegister, value);
      store_instr_offset = masm->pc_offset();
      masm->xchgq(kScratchRegister, operand);
      break;
    case MachineRepresentation::kTagged:
      if (COMPRESS_POINTERS_BOOL) {
        masm->movl(kScratchRegister, value);
        store_instr_offset = masm->pc_offset();
        masm->xchgl(kScratchRegister, operand);
      } else {
        masm->movq(kScratchRegister, value);
        store_instr_offset = masm->pc_offset();
        masm->xchgq(kScratchRegister, operand);
      }
      break;
    default:
      UNREACHABLE();
  }
  return store_instr_offset;
}
References COMPRESS_POINTERS_BOOL, DCHECK_EQ, v8::internal::kIndirectPointer, v8::internal::kSandboxedPointer, v8::internal::kScratchRegister, v8::internal::kTagged, v8::internal::kWord16, v8::internal::kWord32, v8::internal::kWord64, v8::internal::kWord8, v8::internal::Assembler::movb(), v8::internal::Assembler::movl(), v8::internal::Assembler::movq(), v8::internal::Assembler::movw(), v8::internal::AssemblerBase::pc_offset(), v8::internal::MacroAssembler::StoreIndirectPointerField(), v8::internal::MacroAssembler::StoreSandboxedPointerField(), v8::internal::MacroAssembler::StoreTaggedField(), v8::internal::UNREACHABLE(), v8::internal::value, v8::internal::Assembler::xchgb(), and v8::internal::Assembler::xchgw().
EmitStore< std::memory_order_relaxed >()
template<>
int v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::EmitStore< std::memory_order_relaxed > (MacroAssembler * masm, Operand operand, Immediate value, MachineRepresentation rep)
Definition at line 552 of file code-generator-x64.cc.
                                                                    {
  int store_instr_offset = masm->pc_offset();
  switch (rep) {
    case MachineRepresentation::kWord8:
      masm->movb(operand, value);
      break;
    case MachineRepresentation::kWord16:
      masm->movw(operand, value);
      break;
    case MachineRepresentation::kWord32:
      masm->movl(operand, value);
      break;
    case MachineRepresentation::kWord64:
      masm->movq(operand, value);
      break;
    case MachineRepresentation::kTagged:
      masm->StoreTaggedField(operand, value);
      break;
    default:
      UNREACHABLE();
  }
  return store_instr_offset;
}
References v8::internal::kTagged, v8::internal::kWord16, v8::internal::kWord32, v8::internal::kWord64, v8::internal::kWord8, v8::internal::Assembler::movb(), v8::internal::Assembler::movl(), v8::internal::Assembler::movq(), v8::internal::Assembler::movw(), v8::internal::AssemblerBase::pc_offset(), v8::internal::MacroAssembler::StoreTaggedField(), v8::internal::UNREACHABLE(), and v8::internal::value.
EmitTSANAwareStore()
template<std::memory_order order, typename ValueT >
void v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::EmitTSANAwareStore (Zone * zone, CodeGenerator * codegen, MacroAssembler * masm, Operand operand, ValueT value, X64OperandConverter & i, StubCallMode stub_call_mode, MachineRepresentation rep, Instruction * instr)
Definition at line 874 of file code-generator-x64.cc.
                                                                       {
  DCHECK(order == std::memory_order_relaxed ||
         order == std::memory_order_seq_cst);
  int store_instr_off = EmitStore<order>(masm, operand, value, rep);
  if (instr->HasMemoryAccessMode()) {
    RecordTrapInfoIfNeeded(zone, codegen, instr->opcode(), instr,
                           store_instr_off);
  }
}
References v8::internal::DCHECK(), v8::internal::compiler::Instruction::HasMemoryAccessMode(), v8::internal::compiler::Instruction::opcode(), RecordTrapInfoIfNeeded(), and v8::internal::value.
EmitTSANRelaxedLoadOOLIfNeeded()
void v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::EmitTSANRelaxedLoadOOLIfNeeded (Zone * zone, CodeGenerator * codegen, MacroAssembler * masm, Operand operand, X64OperandConverter & i, StubCallMode mode, int size)
Definition at line 887 of file code-generator-x64.cc.
                                              {}
FlagsConditionToCondition()
constexpr Condition v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::FlagsConditionToCondition (FlagsCondition condition) [constexpr]
Definition at line 7369 of file code-generator-x64.cc.
                                                                        {
  switch (condition) {
    case kUnorderedEqual:
    case kEqual:
      return equal;
    case kUnorderedNotEqual:
    case kNotEqual:
      return not_equal;
    case kSignedLessThan:
      return less;
    case kSignedGreaterThanOrEqual:
      return greater_equal;
    case kSignedLessThanOrEqual:
      return less_equal;
    case kSignedGreaterThan:
      return greater;
    case kUnsignedLessThan:
      return below;
    case kUnsignedGreaterThanOrEqual:
      return above_equal;
    case kUnsignedLessThanOrEqual:
      return below_equal;
    case kUnsignedGreaterThan:
      return above;
    case kOverflow:
      return overflow;
    case kNotOverflow:
      return no_overflow;
    case kIsNaN:
      return parity_even;
    case kIsNotNaN:
      return parity_odd;
    default:
      break;
  }
  UNREACHABLE();
}
References v8::internal::above, v8::internal::above_equal, v8::internal::below, v8::internal::below_equal, v8::internal::equal, v8::internal::greater, v8::internal::greater_equal, v8::internal::compiler::kEqual, v8::internal::compiler::kIsNaN, v8::internal::compiler::kIsNotNaN, v8::internal::compiler::kNotEqual, v8::internal::compiler::kNotOverflow, v8::internal::compiler::kOverflow, v8::internal::compiler::kSignedGreaterThan, v8::internal::compiler::kSignedGreaterThanOrEqual, v8::internal::compiler::kSignedLessThan, v8::internal::compiler::kSignedLessThanOrEqual, v8::internal::compiler::kUnorderedEqual, v8::internal::compiler::kUnorderedNotEqual, v8::internal::compiler::kUnsignedGreaterThan, v8::internal::compiler::kUnsignedGreaterThanOrEqual, v8::internal::compiler::kUnsignedLessThan, v8::internal::compiler::kUnsignedLessThanOrEqual, v8::internal::less, v8::internal::less_equal, v8::internal::no_overflow, v8::internal::not_equal, v8::internal::overflow, v8::internal::parity_even, v8::internal::parity_odd, and v8::internal::UNREACHABLE().
HasAddressingMode()
bool v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::HasAddressingMode (Instruction * instr)
Definition at line 276 of file code-generator-x64.cc.
                                           {
  return instr->addressing_mode() != kMode_None;
}
References v8::internal::compiler::Instruction::addressing_mode().
HasImmediateInput()
bool v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::HasImmediateInput (Instruction * instr, size_t index)
Definition at line 280 of file code-generator-x64.cc.
                                                         {
  return instr->InputAt(index)->IsImmediate();
}
References v8::internal::index, and v8::internal::compiler::Instruction::InputAt().
HasRegisterInput()
bool v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::HasRegisterInput (Instruction * instr, size_t index)
Definition at line 284 of file code-generator-x64.cc.
                                                        {
  return instr->InputAt(index)->IsRegister();
}
References v8::internal::index, v8::internal::compiler::Instruction::InputAt(), and v8::internal::compiler::InstructionOperand::IsRegister().
Is32BitOperand()
bool v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::Is32BitOperand (InstructionOperand * operand)
Definition at line 8173 of file code-generator-x64.cc.
                                                 {
  DCHECK(operand->IsStackSlot() || operand->IsRegister());
  MachineRepresentation mr = LocationOperand::cast(operand)->representation();
  return mr == MachineRepresentation::kWord32 ||
         mr == MachineRepresentation::kCompressed ||
         mr == MachineRepresentation::kCompressedPointer;
}
References v8::internal::compiler::LocationOperand::cast(), v8::internal::DCHECK(), v8::internal::compiler::InstructionOperand::IsRegister(), v8::internal::compiler::InstructionOperand::IsStackSlot(), v8::internal::kCompressed, v8::internal::kCompressedPointer, v8::internal::kWord32, and v8::internal::compiler::LocationOperand::representation().
Referenced by Use32BitMove().
RecordTrapInfoIfNeeded()
void v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::RecordTrapInfoIfNeeded (Zone * zone, CodeGenerator * codegen, InstructionCode opcode, Instruction * instr, int pc)
Definition at line 623 of file code-generator-x64.cc.
                                    {
  DCHECK_EQ(kMemoryAccessDirect, instr->memory_access_mode());
}
References DCHECK_EQ, v8::internal::compiler::kMemoryAccessDirect, and v8::internal::compiler::Instruction::memory_access_mode().
Referenced by EmitTSANAwareStore().
SetupSimd256ImmediateInRegister()
void v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::SetupSimd256ImmediateInRegister (MacroAssembler * assembler, uint32_t * imms, YMMRegister reg, XMMRegister scratch)
Definition at line 1352 of file code-generator-x64.cc.
                                                                           {
  bool is_splat =
      std::all_of(imms, imms + 8, [imms](uint32_t v) { return v == imms[0]; });
  if (is_splat) {
    assembler->Move(scratch, imms[0]);
    CpuFeatureScope avx_scope(assembler, AVX2);
    assembler->vpbroadcastd(reg, scratch);
  } else {
    assembler->Move(reg, make_uint64(imms[3], imms[2]),
                    make_uint64(imms[1], imms[0]));
    assembler->Move(scratch, make_uint64(imms[7], imms[6]),
                    make_uint64(imms[5], imms[4]));
    CpuFeatureScope avx_scope(assembler, AVX2);
    assembler->vinserti128(reg, reg, scratch, uint8_t{1});
  }
}
References v8::base::all_of(), make_uint64(), v8::internal::MacroAssembler::Move(), and v8::internal::Assembler::vinserti128().
SetupSimdImmediateInRegister()
void v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::SetupSimdImmediateInRegister (MacroAssembler * assembler, uint32_t * imms, XMMRegister reg)
Definition at line 1346 of file code-generator-x64.cc.
                                                   {
  assembler->Move(reg, make_uint64(imms[3], imms[2]),
                  make_uint64(imms[1], imms[0]));
}
References make_uint64(), and v8::internal::MacroAssembler::Move().
Use32BitMove()
bool v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::Use32BitMove (InstructionOperand * source, InstructionOperand * destination)
Definition at line 8189 of file code-generator-x64.cc.
                                                                               {
  return Is32BitOperand(source) && Is32BitOperand(destination);
}
References Is32BitOperand().
Variable Documentation
kQuadWordSize
const int v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::kQuadWordSize = 16 [static]
Definition at line 7707 of file code-generator-x64.cc.