v8::internal::torque::anonymous_namespace{torque-compiler.cc} Namespace Reference
Functions
std::optional< std::string > ReadFile (const std::string &path)
void ReadAndParseTorqueFile (const std::string &path)
void CompileCurrentAst (TorqueCompilerOptions options)
Function Documentation
CompileCurrentAst()
void v8::internal::torque::anonymous_namespace{torque-compiler.cc}::CompileCurrentAst (TorqueCompilerOptions options)
Definition at line 48 of file torque-compiler.cc.
                                                      {
  GlobalContext::Scope global_context(std::move(CurrentAst::Get()));
  if (options.collect_language_server_data) {
    GlobalContext::SetCollectLanguageServerData();
  }
  if (options.collect_kythe_data) {
    GlobalContext::SetCollectKytheData();
  }
  if (options.force_assert_statements) {
    GlobalContext::SetForceAssertStatements();
  }
  if (options.annotate_ir) {
    GlobalContext::SetAnnotateIR();
  }
  TypeOracle::Scope type_oracle;
  CurrentScope::Scope current_namespace(GlobalContext::GetDefaultNamespace());
  // Two-step process of predeclaration + resolution allows to resolve type
  // declarations independent of the order they are given.
  PredeclarationVisitor::Predeclare(GlobalContext::ast());
  PredeclarationVisitor::ResolvePredeclarations();
  // Process other declarations.
  DeclarationVisitor::Visit(GlobalContext::ast());
  // A class types' fields are resolved here, which allows two class fields to
  // mutually refer to each others.
  TypeOracle::FinalizeAggregateTypes();
  std::string output_directory = options.output_directory;
  ImplementationVisitor implementation_visitor;
  implementation_visitor.SetDryRun(output_directory.empty());
  implementation_visitor.GenerateInstanceTypes(output_directory);
  implementation_visitor.BeginGeneratedFiles();
  implementation_visitor.BeginDebugMacrosFile();
  implementation_visitor.VisitAllDeclarables();
  ReportAllUnusedMacros();
  implementation_visitor.GenerateBuiltinDefinitionsAndInterfaceDescriptors(
      output_directory);
  implementation_visitor.GenerateVisitorLists(output_directory);
  implementation_visitor.GenerateBitFields(output_directory);
  implementation_visitor.GeneratePrintDefinitions(output_directory);
  implementation_visitor.GenerateClassDefinitions(output_directory);
  implementation_visitor.GenerateClassVerifiers(output_directory);
  implementation_visitor.GenerateClassDebugReaders(output_directory);
  implementation_visitor.GenerateEnumVerifiers(output_directory);
  implementation_visitor.GenerateBodyDescriptors(output_directory);
  implementation_visitor.GenerateExportedMacrosAssembler(output_directory);
  implementation_visitor.GenerateCSATypes(output_directory);
  implementation_visitor.EndGeneratedFiles();
  implementation_visitor.EndDebugMacrosFile();
  implementation_visitor.GenerateImplementation(output_directory);
  if (GlobalContext::collect_language_server_data()) {
    LanguageServerData::SetGlobalContext(std::move(GlobalContext::Get()));
    LanguageServerData::SetTypeOracle(std::move(TypeOracle::Get()));
  }
}
References v8::internal::torque::TorqueCompilerOptions::annotate_ir, v8::internal::torque::GlobalContext::ast(), v8::internal::torque::ImplementationVisitor::BeginDebugMacrosFile(), v8::internal::torque::ImplementationVisitor::BeginGeneratedFiles(), v8::internal::torque::TorqueCompilerOptions::collect_kythe_data, v8::internal::torque::GlobalContext::collect_language_server_data(), v8::internal::torque::TorqueCompilerOptions::collect_language_server_data, v8::internal::torque::ImplementationVisitor::EndDebugMacrosFile(), v8::internal::torque::ImplementationVisitor::EndGeneratedFiles(), v8::internal::torque::TypeOracle::FinalizeAggregateTypes(), v8::internal::torque::TorqueCompilerOptions::force_assert_statements, v8::internal::torque::ImplementationVisitor::GenerateBitFields(), v8::internal::torque::ImplementationVisitor::GenerateBodyDescriptors(), v8::internal::torque::ImplementationVisitor::GenerateBuiltinDefinitionsAndInterfaceDescriptors(), v8::internal::torque::ImplementationVisitor::GenerateClassDebugReaders(), v8::internal::torque::ImplementationVisitor::GenerateClassDefinitions(), v8::internal::torque::ImplementationVisitor::GenerateClassVerifiers(), v8::internal::torque::ImplementationVisitor::GenerateCSATypes(), v8::internal::torque::ImplementationVisitor::GenerateEnumVerifiers(), v8::internal::torque::ImplementationVisitor::GenerateExportedMacrosAssembler(), v8::internal::torque::ImplementationVisitor::GenerateImplementation(), v8::internal::torque::ImplementationVisitor::GenerateInstanceTypes(), v8::internal::torque::ImplementationVisitor::GeneratePrintDefinitions(), v8::internal::torque::ImplementationVisitor::GenerateVisitorLists(), v8::base::ContextualVariable< Derived, VarType >::Get(), v8::internal::compiler::turboshaft::Get(), v8::internal::torque::GlobalContext::GetDefaultNamespace(), v8::internal::torque::TorqueCompilerOptions::output_directory, v8::internal::torque::PredeclarationVisitor::Predeclare(), v8::internal::torque::ReportAllUnusedMacros(), v8::internal::torque::PredeclarationVisitor::ResolvePredeclarations(), v8::internal::torque::GlobalContext::SetAnnotateIR(), v8::internal::torque::GlobalContext::SetCollectKytheData(), v8::internal::torque::GlobalContext::SetCollectLanguageServerData(), v8::internal::torque::ImplementationVisitor::SetDryRun(), v8::internal::torque::GlobalContext::SetForceAssertStatements(), v8::internal::torque::LanguageServerData::SetGlobalContext(), v8::internal::torque::LanguageServerData::SetTypeOracle(), v8::internal::string, v8::internal::torque::DeclarationVisitor::Visit(), and v8::internal::torque::ImplementationVisitor::VisitAllDeclarables().
Referenced by v8::internal::torque::CompileTorque(), and v8::internal::torque::CompileTorqueForKythe().
ReadAndParseTorqueFile()
void v8::internal::torque::anonymous_namespace{torque-compiler.cc}::ReadAndParseTorqueFile (const std::string & path)
Definition at line 29 of file torque-compiler.cc.
                                                   {
  SourceId source_id = SourceFileMap::AddSource(path);
  CurrentSourceFile::Scope source_id_scope(source_id);
  // path might be either a normal file path or an encoded URI.
  auto maybe_content = ReadFile(SourceFileMap::AbsolutePath(source_id));
  if (!maybe_content) {
    if (auto maybe_path = FileUriDecode(path)) {
      maybe_content = ReadFile(*maybe_path);
    }
  }
  if (!maybe_content) {
    Error("Cannot open file path/uri: ", path).Throw();
  }
  ParseTorque(*maybe_content);
}
References v8::internal::torque::SourceFileMap::AbsolutePath(), v8::internal::torque::SourceFileMap::AddSource(), v8::internal::torque::Error(), v8::internal::torque::FileUriDecode(), v8::internal::torque::ParseTorque(), v8::internal::ReadFile(), and v8::internal::torque::MessageBuilder::Throw().
Referenced by v8::internal::torque::CompileTorque().
ReadFile()
std::optional<std::string> v8::internal::torque::anonymous_namespace{torque-compiler.cc}::ReadFile (const std::string & path)
Definition at line 21 of file torque-compiler.cc.
                                                       {
  std::ifstream file_stream(path);
  if (!file_stream.good()) return std::nullopt;
  return std::string{std::istreambuf_iterator<char>(file_stream),
                     std::istreambuf_iterator<char>()};
}
References v8::internal::string.
Referenced by v8::Shell::CreateGlobalTemplate(), v8::Shell::ExecuteFile(), v8::Shell::LogGetAndStop(), and v8::Shell::ReadFile().