v8::internal::anonymous_namespace{js-struct.cc} Namespace Reference
Functions
void PrepareMapCommon (Tagged< Map > map)
InternalIndex GetSpecialSlotIndex (Tagged< Map > instance_map, Tagged< Symbol > special_slot_name)
template<typename T >
MaybeHandle< T > GetSpecialSlotValue (Isolate *isolate, Tagged< Map > instance_map, Tagged< Symbol > special_slot_name)
Variables
constexpr int kSpecialSlots = 2
Function Documentation
GetSpecialSlotIndex()
InternalIndex v8::internal::anonymous_namespace{js-struct.cc}::GetSpecialSlotIndex (Tagged< Map > instance_map, Tagged< Symbol > special_slot_name)
Definition at line 124 of file js-struct.cc.
                                                                    {
  DCHECK(IsJSSharedStructMap(instance_map));
  DCHECK(IsPrivateSymbol(special_slot_name));
  Tagged<DescriptorArray> descriptors = instance_map->instance_descriptors();
  // Special slots are optional and start at descriptor number 0.
  int end = std::min(static_cast<int>(descriptors->number_of_all_descriptors()),
                     kSpecialSlots);
  for (int i = 0; i < end; ++i) {
    InternalIndex idx(i);
    if (descriptors->GetKey(idx) == special_slot_name) {
      DCHECK_EQ(PropertyLocation::kDescriptor,
                descriptors->GetDetails(idx).location());
      return idx;
    }
  }
  return InternalIndex::NotFound();
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::end(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::IsPrivateSymbol(), v8::internal::kDescriptor, kSpecialSlots, and v8::internal::InternalIndex::NotFound().
Referenced by GetSpecialSlotValue().
GetSpecialSlotValue()
template<typename T >
MaybeHandle<T> v8::internal::anonymous_namespace{js-struct.cc}::GetSpecialSlotValue (Isolate * isolate, Tagged< Map > instance_map, Tagged< Symbol > special_slot_name)
Definition at line 144 of file js-struct.cc.
                                                                     {
  DisallowGarbageCollection no_gc;
  MaybeHandle<T> result;
  InternalIndex entry = GetSpecialSlotIndex(instance_map, special_slot_name);
  if (entry.is_found()) {
    DCHECK_IMPLIES(
        special_slot_name ==
            ReadOnlyRoots(isolate).shared_struct_map_registry_key_symbol(),
        entry.as_int() == 0);
    result =
        handle(Cast<T>(instance_map->instance_descriptors()->GetStrongValue(
                   isolate, entry)),
               isolate);
  }
  return result;
}
References v8::internal::InternalIndex::as_int(), DCHECK_IMPLIES, GetSpecialSlotIndex(), v8::internal::handle(), v8::internal::InternalIndex::is_found(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::base::internal::result.
PrepareMapCommon()
void v8::internal::anonymous_namespace{js-struct.cc}::PrepareMapCommon (Tagged< Map > map)
Definition at line 18 of file js-struct.cc.
                                       {
  DCHECK(IsAlwaysSharedSpaceJSObjectMap(map));
  DisallowGarbageCollection no_gc;
  // Shared objects have fixed layout ahead of time, so there's no slack.
  map->SetInObjectUnusedPropertyFields(0);
  // Shared objects are not extensible and have a null prototype.
  map->set_is_extensible(false);
  // Shared space objects are not optimizable as prototypes because it is
  // not threadsafe.
  map->set_prototype_validity_cell(Map::kPrototypeChainValidSmi, kRelaxedStore,
                                   SKIP_WRITE_BARRIER);
}
References v8::internal::DCHECK(), v8::internal::Map::kPrototypeChainValidSmi, v8::kRelaxedStore, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::SKIP_WRITE_BARRIER.
Referenced by v8::internal::AlwaysSharedSpaceJSObject::PrepareMapNoEnumerableProperties(), and v8::internal::AlwaysSharedSpaceJSObject::PrepareMapWithEnumerableProperties().
Variable Documentation
kSpecialSlots
constexpr int v8::internal::anonymous_namespace{js-struct.cc}::kSpecialSlots = 2 [constexpr]
Definition at line 122 of file js-struct.cc.
Referenced by v8::internal::JSSharedStruct::CreateInstanceMap(), and GetSpecialSlotIndex().