v8::internal::anonymous_namespace{module.cc} Namespace Reference
Functions
void SetStatusInternal (Tagged< Module > module, Module::Status new_status)
Function Documentation
SetStatusInternal()
void v8::internal::anonymous_namespace{module.cc}::SetStatusInternal (Tagged< Module > module, Module::Status new_status)
Definition at line 60 of file module.cc.
                                                                       {
  DisallowGarbageCollection no_gc;
#ifdef DEBUG
  Module::Status old_status = static_cast<Module::Status>(module->status());
  module->set_status(new_status);
  PrintStatusTransition(module, old_status);
#else
  module->set_status(new_status);
#endif // DEBUG
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::internal::Module::RecordError(), v8::internal::Module::Reset(), and v8::internal::Module::SetStatus().