v8::internal::anonymous_namespace{dependent-code.cc} Namespace Reference
Functions
void PrintDependencyGroups (DependentCode::DependencyGroups groups)
Function Documentation
PrintDependencyGroups()
void v8::internal::anonymous_namespace{dependent-code.cc}::PrintDependencyGroups (DependentCode::DependencyGroups groups)
Definition at line 52 of file dependent-code.cc.
                                                                 {
  while (groups != 0) {
    auto group = static_cast<DependentCode::DependencyGroup>(
        1 << base::bits::CountTrailingZeros(static_cast<uint32_t>(groups)));
    StdoutStream{} << DependentCode::DependencyGroupName(group);
    groups &= ~group;
    if (groups != 0) StdoutStream{} << ",";
  }
}
References v8::base::bits::CountTrailingZeros(), and v8::internal::DependentCode::DependencyGroupName().
Referenced by v8::internal::DependentCode::InstallDependency().