v8::internal::compiler::anonymous_namespace{node.cc} Namespace Reference
Functions
void PrintNode (const Node *node, std::ostream &os, int depth, int indentation=0)
Function Documentation
PrintNode()
void v8::internal::compiler::anonymous_namespace{node.cc}::PrintNode (const Node * node, std::ostream & os, int depth, int indentation = 0)
Definition at line 353 of file node.cc.
                                    {
  for (int i = 0; i < indentation; ++i) {
    os << " ";
  }
  if (node) {
    os << *node << std::endl;
  } else {
    os << "(NULL)" << std::endl;
    return;
  }
  if (depth <= 0) return;
  for (Node* input : node->inputs()) {
    PrintNode(input, os, depth - 1, indentation + 1);
  }
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::compiler::Node::inputs().
Referenced by v8::internal::maglev::MaglevGraphBuilder::AddInitializedNodeToGraph(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadElements(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadStringLength(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadTaggedField(), v8::internal::maglev::MaglevGraphBuilder::CreateNewConstantNode(), v8::internal::maglev::Graph::CreateNewConstantNode(), v8::internal::maglev::MaglevGraphBuilder::FinishBlock(), v8::internal::maglev::MaglevGraphBuilder::LoadAndCacheContextSlot(), v8::internal::compiler::Node::Print(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::PrintAfterMerge(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::Process(), v8::internal::maglev::MaglevGraphBuilder::ProcessMergePointAtExceptionHandlerStart(), v8::internal::maglev::MaglevGraphBuilder::RecordKnownProperty(), v8::internal::maglev::MaglevGraphBuilder::RegisterPhisWithGraphLabeller(), v8::internal::maglev::MaglevGraphBuilder::StoreAndCacheContextSlot(), v8::internal::maglev::MaglevGraphBuilder::TryBuildStoreTaggedFieldToAllocation(), and v8::internal::maglev::MaglevGraphBuilder::TryReuseKnownPropertyLoad().