v8::internal::anonymous_namespace{binary-op-assembler.cc} Namespace Reference
Functions
bool IsBigInt64OpSupported (BinaryOpAssembler *assembler, Operation op)
Function Documentation
IsBigInt64OpSupported()
bool v8::internal::anonymous_namespace{binary-op-assembler.cc}::IsBigInt64OpSupported (BinaryOpAssembler * assembler, Operation op) [inline]
Definition at line 19 of file binary-op-assembler.cc.
                                                                              {
  return assembler->Is64() && op != Operation::kExponentiate &&
         op != Operation::kShiftLeft && op != Operation::kShiftRight &&
         op != Operation::kShiftRightLogical;
}
References v8::internal::compiler::CodeAssembler::Is64().
Referenced by v8::internal::BinaryOpAssembler::Generate_BinaryOperationWithFeedback(), and v8::internal::BinaryOpAssembler::Generate_BitwiseBinaryOpWithOptionalFeedback().