v8::internal::anonymous_namespace{source-range-ast-visitor.cc} Namespace Reference
Functions
Statement * FindLastNonSyntheticStatement (ZonePtrList< Statement > *statements)
Function Documentation
FindLastNonSyntheticStatement()
Statement* v8::internal::anonymous_namespace{source-range-ast-visitor.cc}::FindLastNonSyntheticStatement (ZonePtrList< Statement > * statements)
Definition at line 102 of file source-range-ast-visitor.cc.
                                                                             {
  for (int i = statements->length() - 1; i >= 0; --i) {
    Statement* stmt = statements->at(i);
    if (stmt->IsReturnStatement() &&
        stmt->AsReturnStatement()->is_synthetic_async_return()) {
      continue;
    }
    return stmt;
  }
  return nullptr;
}
References v8::internal::ZoneList< T >::at(), and v8::internal::ZoneList< T >::length().
Referenced by v8::internal::SourceRangeAstVisitor::MaybeRemoveContinuationRangeOfAsyncReturn().