v8_inspector::anonymous_namespace{v8-debugger-script.cc} Namespace Reference
Functions
String16 calculateHash (v8::Isolate *isolate, v8::Local< v8::String > source)
Variables
const char kGlobalDebuggerScriptHandleLabel [] = `DevTools debugger`
Function Documentation
calculateHash()
String16 v8_inspector::anonymous_namespace{v8-debugger-script.cc}::calculateHash (v8::Isolate * isolate, v8::Local< v8::String > source)
Definition at line 21 of file v8-debugger-script.cc.
                                                                     {
  uint32_t length = source->Length();
  std::unique_ptr<UChar[]> buffer(new UChar[length]);
  source->WriteV2(isolate, 0, length,
                  reinterpret_cast<uint16_t*>(buffer.get()));
  const uint8_t* data = nullptr;
  size_t sizeInBytes = sizeof(UChar) * length;
  data = reinterpret_cast<const uint8_t*>(buffer.get());
  uint8_t hash[kSizeOfSha256Digest];
  v8::internal::SHA256_hash(data, sizeInBytes, hash);
  String16Builder formatted_hash;
  for (size_t i = 0; i < kSizeOfSha256Digest; i++)
    formatted_hash.appendUnsignedAsHex(static_cast<uint8_t>(hash[i]));
  return formatted_hash.toString();
}
References v8_inspector::String16Builder::appendUnsignedAsHex(), kSizeOfSha256Digest, v8::String::Length(), v8::internal::length, v8::internal::SHA256_hash(), v8_inspector::String16Builder::toString(), and v8::String::WriteV2().
Referenced by v8_inspector::V8DebuggerScript::hash().
Variable Documentation
kGlobalDebuggerScriptHandleLabel
const char v8_inspector::anonymous_namespace{v8-debugger-script.cc}::kGlobalDebuggerScriptHandleLabel[] = `DevTools debugger`
Definition at line 19 of file v8-debugger-script.cc.
Referenced by v8_inspector::V8DebuggerScript::Initialize().