v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc} Namespace Reference
Classes
struct LoadStoreView
Functions
bool IsCompressed (InstructionSelector *selector, OpIndex node)
ArchOpcode GetLoadOpcode (MemoryRepresentation loaded_rep, RegisterRepresentation result_rep)
ArchOpcode GetLoadOpcode (LoadRepresentation load_rep)
ArchOpcode GetStoreOpcode (MemoryRepresentation stored_rep)
ArchOpcode GetSeqCstStoreOpcode (StoreRepresentation store_rep)
template<VectorLength vec_len>
void VisitMinOrMax (InstructionSelector *selector, OpIndex node, ArchOpcode opcode, bool flip_inputs)
void VisitAtomicExchange (InstructionSelector *selector, OpIndex node, ArchOpcode opcode, AtomicWidth width, MemoryAccessKind access_kind)
void VisitStoreCommon (InstructionSelector *selector, const InstructionSelector::StoreView &store)
void VisitWord32Shift (InstructionSelector *selector, OpIndex node, ArchOpcode opcode)
void VisitWord64Shift (InstructionSelector *selector, OpIndex node, ArchOpcode opcode)
bool TryVisitWordShift (InstructionSelector *selector, OpIndex node, int bits, ArchOpcode opcode, FlagsContinuation *cont)
void EmitLea (InstructionSelector *selector, InstructionCode opcode, OpIndex result, OpIndex index, int scale, OpIndex base, int64_t displacement, DisplacementMode displacement_mode)
AddressingMode AddDisplacementToAddressingMode (AddressingMode mode)
bool TryEmitLoadForLoadWord64AndShiftRight (InstructionSelector *selector, OpIndex node, InstructionCode opcode)
void VisitMul (InstructionSelector *selector, OpIndex node, ArchOpcode opcode)
void VisitMulHigh (InstructionSelector *selector, OpIndex node, ArchOpcode opcode)
void VisitDiv (InstructionSelector *selector, OpIndex node, ArchOpcode opcode)
void VisitMod (InstructionSelector *selector, OpIndex node, ArchOpcode opcode)
void VisitRO (InstructionSelector *selector, OpIndex node, InstructionCode opcode)
void VisitRR (InstructionSelector *selector, OpIndex node, InstructionCode opcode)
void VisitRRO (InstructionSelector *selector, OpIndex node, InstructionCode opcode)
void VisitFloatBinop (InstructionSelector *selector, OpIndex node, InstructionCode avx_opcode, InstructionCode sse_opcode)
void VisitFloatUnop (InstructionSelector *selector, OpIndex node, OpIndex input, InstructionCode opcode)
void VisitCompareWithMemoryOperand (InstructionSelector *selector, InstructionCode opcode, OpIndex left, InstructionOperand right, FlagsContinuation *cont)
void VisitCompare (InstructionSelector *selector, InstructionCode opcode, InstructionOperand left, InstructionOperand right, FlagsContinuation *cont)
void VisitCompare (InstructionSelector *selector, InstructionCode opcode, OpIndex left, OpIndex right, FlagsContinuation *cont, bool commutative)
MachineType MachineTypeForNarrow (InstructionSelector *selector, OpIndex node, OpIndex hint_node)
bool IsIntConstant (InstructionSelector *selector, OpIndex node)
bool IsWordAnd (InstructionSelector *selector, OpIndex node)
MachineType MachineTypeForNarrowWordAnd (InstructionSelector *selector, OpIndex and_node, OpIndex constant_node)
InstructionCode TryNarrowOpcodeSize (InstructionSelector *selector, InstructionCode opcode, OpIndex left, OpIndex right, FlagsContinuation *cont)
OpIndex RemoveUnnecessaryWordAnd (InstructionSelector *selector, InstructionCode opcode, OpIndex and_node)
void VisitWordCompare (InstructionSelector *selector, OpIndex node, InstructionCode opcode, FlagsContinuation *cont)
void VisitWord64EqualImpl (InstructionSelector *selector, OpIndex node, FlagsContinuation *cont)
bool MatchHeapObjectEqual (InstructionSelector *selector, OpIndex node, OpIndex *left, Handle< HeapObject > *right)
void VisitWord32EqualImpl (InstructionSelector *selector, OpIndex node, FlagsContinuation *cont)
void VisitCompareZero (InstructionSelector *selector, OpIndex user, OpIndex node, InstructionCode opcode, FlagsContinuation *cont)
void VisitFloat32Compare (InstructionSelector *selector, OpIndex node, FlagsContinuation *cont)
void VisitFloat64Compare (InstructionSelector *selector, OpIndex node, FlagsContinuation *cont)
void VisitAtomicBinop (InstructionSelector *selector, OpIndex node, ArchOpcode opcode, AtomicWidth width, MemoryAccessKind access_kind)
void VisitAtomicCompareExchange (InstructionSelector *selector, OpIndex node, ArchOpcode opcode, AtomicWidth width, MemoryAccessKind access_kind)
Function Documentation
AddDisplacementToAddressingMode()
AddressingMode v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::AddDisplacementToAddressingMode (AddressingMode mode) [inline]
Definition at line 1972 of file instruction-selector-x64.cc.
                                                                           {
  switch (mode) {
    case kMode_MR:
      return kMode_MRI;
    case kMode_MR1:
      return kMode_MR1I;
    case kMode_MR2:
      return kMode_MR2I;
    case kMode_MR4:
      return kMode_MR4I;
    case kMode_MR8:
      return kMode_MR8I;
    case kMode_M1:
      return kMode_M1I;
    case kMode_M2:
      return kMode_M2I;
    case kMode_M4:
      return kMode_M4I;
    case kMode_M8:
      return kMode_M8I;
    case kMode_None:
    case kMode_MRI:
    case kMode_MR1I:
    case kMode_MR2I:
    case kMode_MR4I:
    case kMode_MR8I:
    case kMode_M1I:
    case kMode_M2I:
    case kMode_M4I:
    case kMode_M8I:
    case kMode_Root:
    case kMode_MCR:
    case kMode_MCRI:
      UNREACHABLE();
  }
  UNREACHABLE();
}
References mode(), and v8::internal::UNREACHABLE().
Referenced by TryEmitLoadForLoadWord64AndShiftRight().
EmitLea()
void v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::EmitLea (InstructionSelector * selector, InstructionCode opcode, OpIndex result, OpIndex index, int scale, OpIndex base, int64_t displacement, DisplacementMode displacement_mode)
Definition at line 1908 of file instruction-selector-x64.cc.
                                                                       {
  X64OperandGenerator g(selector);
  InstructionOperand inputs[4];
  size_t input_count = 0;
  AddressingMode mode =
      g.GenerateMemoryOperandInputs(index, scale, base, displacement,
                                    displacement_mode, inputs, &input_count);
  DCHECK_NE(0u, input_count);
  DCHECK_GE(arraysize(inputs), input_count);
  InstructionOperand outputs[1];
  outputs[0] = g.DefineAsRegister(result);
  opcode = AddressingModeField::encode(mode) | opcode;
  selector->Emit(opcode, 1, outputs, input_count, inputs);
}
References arraysize, DCHECK_GE, DCHECK_NE, v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::InstructionSelector::Emit(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::X64OperandGenerator::GenerateMemoryOperandInputs(), v8::internal::index, v8::internal::compiler::turboshaft::detail::input_count(), mode(), and v8::base::internal::result.
GetLoadOpcode() [1/2]
ArchOpcode v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetLoadOpcode (LoadRepresentation load_rep)
Definition at line 907 of file instruction-selector-x64.cc.
                                                      {
  ArchOpcode opcode;
  switch (load_rep.representation()) {
    case MachineRepresentation::kFloat16:
      opcode = kX64Movsh;
      break;
    case MachineRepresentation::kFloat32:
      opcode = kX64Movss;
      break;
    case MachineRepresentation::kFloat64:
      opcode = kX64Movsd;
      break;
    case MachineRepresentation::kBit: // Fall through.
    case MachineRepresentation::kWord8:
      opcode = load_rep.IsSigned() ? kX64Movsxbl : kX64Movzxbl;
      break;
    case MachineRepresentation::kWord16:
      opcode = load_rep.IsSigned() ? kX64Movsxwl : kX64Movzxwl;
      break;
    case MachineRepresentation::kWord32:
      opcode = kX64Movl;
      break;
    case MachineRepresentation::kCompressedPointer: // Fall through.
    case MachineRepresentation::kCompressed:
#ifdef V8_COMPRESS_POINTERS
      opcode = kX64Movl;
      break;
#else
      UNREACHABLE();
#endif
#ifdef V8_COMPRESS_POINTERS
    case MachineRepresentation::kTaggedSigned:
      opcode = kX64MovqDecompressTaggedSigned;
      break;
    case MachineRepresentation::kTaggedPointer:
    case MachineRepresentation::kTagged:
      opcode = kX64MovqDecompressTagged;
      break;
#else
    case MachineRepresentation::kTaggedSigned: // Fall through.
    case MachineRepresentation::kTaggedPointer: // Fall through.
    case MachineRepresentation::kTagged: // Fall through.
#endif
    case MachineRepresentation::kWord64:
      opcode = kX64Movq;
      break;
    case MachineRepresentation::kProtectedPointer:
      CHECK(V8_ENABLE_SANDBOX_BOOL);
      opcode = kX64MovqDecompressProtected;
      break;
    case MachineRepresentation::kSandboxedPointer:
      opcode = kX64MovqDecodeSandboxedPointer;
      break;
    case MachineRepresentation::kSimd128:
      opcode = kX64Movdqu;
      break;
    case MachineRepresentation::kSimd256: // Fall through.
      opcode = kX64Movdqu256;
      break;
    case MachineRepresentation::kNone: // Fall through.
    case MachineRepresentation::kMapWord: // Fall through.
    case MachineRepresentation::kIndirectPointer: // Fall through.
    case MachineRepresentation::kFloat16RawBits:
      UNREACHABLE();
  }
  return opcode;
}
References CHECK, v8::internal::MachineType::IsSigned(), v8::internal::kBit, v8::internal::kCompressed, v8::internal::kCompressedPointer, v8::internal::kFloat16, v8::internal::kFloat16RawBits, v8::internal::kFloat32, v8::internal::kFloat64, v8::internal::kIndirectPointer, v8::internal::kMapWord, v8::internal::kNone, v8::internal::kProtectedPointer, v8::internal::kSandboxedPointer, v8::internal::kSimd128, v8::internal::kSimd256, v8::internal::kTagged, v8::internal::kTaggedPointer, v8::internal::kTaggedSigned, v8::internal::kWord16, v8::internal::kWord32, v8::internal::kWord64, v8::internal::kWord8, v8::internal::MachineType::representation(), v8::internal::UNREACHABLE(), and V8_ENABLE_SANDBOX_BOOL.
GetLoadOpcode() [2/2]
ArchOpcode v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetLoadOpcode (MemoryRepresentation loaded_rep, RegisterRepresentation result_rep)
Definition at line 830 of file instruction-selector-x64.cc.
                                                            {
  // NOTE: The meaning of `loaded_rep` = `MemoryRepresentation::AnyTagged()` is
  // we are loading a compressed tagged field, while `result_rep` =
  // `RegisterRepresentation::Tagged()` refers to an uncompressed tagged value.
  switch (loaded_rep) {
    case MemoryRepresentation::Int8():
      DCHECK_EQ(result_rep, RegisterRepresentation::Word32());
      return kX64Movsxbl;
    case MemoryRepresentation::Uint8():
      DCHECK_EQ(result_rep, RegisterRepresentation::Word32());
      return kX64Movzxbl;
    case MemoryRepresentation::Int16():
      DCHECK_EQ(result_rep, RegisterRepresentation::Word32());
      return kX64Movsxwl;
    case MemoryRepresentation::Uint16():
      DCHECK_EQ(result_rep, RegisterRepresentation::Word32());
      return kX64Movzxwl;
    case MemoryRepresentation::Int32():
    case MemoryRepresentation::Uint32():
      DCHECK_EQ(result_rep, RegisterRepresentation::Word32());
      return kX64Movl;
    case MemoryRepresentation::Int64():
    case MemoryRepresentation::Uint64():
      DCHECK_EQ(result_rep, RegisterRepresentation::Word64());
      return kX64Movq;
    case MemoryRepresentation::Float16():
      DCHECK_EQ(result_rep, RegisterRepresentation::Float32());
      return kX64Movsh;
    case MemoryRepresentation::Float32():
      DCHECK_EQ(result_rep, RegisterRepresentation::Float32());
      return kX64Movss;
    case MemoryRepresentation::Float64():
      DCHECK_EQ(result_rep, RegisterRepresentation::Float64());
      return kX64Movsd;
#ifdef V8_COMPRESS_POINTERS
    case MemoryRepresentation::AnyTagged():
    case MemoryRepresentation::TaggedPointer():
      if (result_rep == RegisterRepresentation::Compressed()) {
        return kX64Movl;
      }
      DCHECK_EQ(result_rep, RegisterRepresentation::Tagged());
      return kX64MovqDecompressTagged;
    case MemoryRepresentation::TaggedSigned():
      if (result_rep == RegisterRepresentation::Compressed()) {
        return kX64Movl;
      }
      DCHECK_EQ(result_rep, RegisterRepresentation::Tagged());
      return kX64MovqDecompressTaggedSigned;
#else
    case MemoryRepresentation::AnyTagged():
    case MemoryRepresentation::TaggedPointer():
    case MemoryRepresentation::TaggedSigned():
      DCHECK_EQ(result_rep, RegisterRepresentation::Tagged());
      return kX64Movq;
#endif
    case MemoryRepresentation::AnyUncompressedTagged():
    case MemoryRepresentation::UncompressedTaggedPointer():
    case MemoryRepresentation::UncompressedTaggedSigned():
      DCHECK_EQ(result_rep, RegisterRepresentation::Tagged());
      return kX64Movq;
    case MemoryRepresentation::ProtectedPointer():
      CHECK(V8_ENABLE_SANDBOX_BOOL);
      return kX64MovqDecompressProtected;
    case MemoryRepresentation::IndirectPointer():
      UNREACHABLE();
    case MemoryRepresentation::SandboxedPointer():
      return kX64MovqDecodeSandboxedPointer;
    case MemoryRepresentation::Simd128():
      DCHECK_EQ(result_rep, RegisterRepresentation::Simd128());
      return kX64Movdqu;
    case MemoryRepresentation::Simd256():
      DCHECK_EQ(result_rep, RegisterRepresentation::Simd256());
      return kX64Movdqu256;
  }
}
References v8::internal::compiler::turboshaft::MemoryRepresentation::AnyTagged(), v8::internal::compiler::turboshaft::MemoryRepresentation::AnyUncompressedTagged(), CHECK, v8::internal::compiler::turboshaft::RegisterRepresentation::Compressed(), DCHECK_EQ, v8::internal::compiler::turboshaft::MemoryRepresentation::Float16(), v8::internal::compiler::turboshaft::RegisterRepresentation::Float32(), v8::internal::compiler::turboshaft::MemoryRepresentation::Float32(), v8::internal::compiler::turboshaft::RegisterRepresentation::Float64(), v8::internal::compiler::turboshaft::MemoryRepresentation::Float64(), v8::internal::compiler::turboshaft::MemoryRepresentation::IndirectPointer(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int16(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int32(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int64(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int8(), v8::internal::compiler::turboshaft::MemoryRepresentation::ProtectedPointer(), v8::internal::compiler::turboshaft::MemoryRepresentation::SandboxedPointer(), v8::internal::compiler::turboshaft::RegisterRepresentation::Simd128(), v8::internal::compiler::turboshaft::MemoryRepresentation::Simd128(), v8::internal::compiler::turboshaft::RegisterRepresentation::Simd256(), v8::internal::compiler::turboshaft::MemoryRepresentation::Simd256(), v8::internal::compiler::turboshaft::RegisterRepresentation::Tagged(), v8::internal::compiler::turboshaft::MemoryRepresentation::TaggedPointer(), v8::internal::compiler::turboshaft::MemoryRepresentation::TaggedSigned(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint16(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint32(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint64(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint8(), v8::internal::compiler::turboshaft::MemoryRepresentation::UncompressedTaggedPointer(), v8::internal::compiler::turboshaft::MemoryRepresentation::UncompressedTaggedSigned(), v8::internal::UNREACHABLE(), V8_ENABLE_SANDBOX_BOOL, v8::internal::compiler::turboshaft::RegisterRepresentation::Word32(), and v8::internal::compiler::turboshaft::RegisterRepresentation::Word64().
GetSeqCstStoreOpcode()
ArchOpcode v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetSeqCstStoreOpcode (StoreRepresentation store_rep)
Definition at line 1017 of file instruction-selector-x64.cc.
                                                               {
  switch (store_rep.representation()) {
    case MachineRepresentation::kWord8:
      return kAtomicStoreWord8;
    case MachineRepresentation::kWord16:
      return kAtomicStoreWord16;
    case MachineRepresentation::kWord32:
      return kAtomicStoreWord32;
    case MachineRepresentation::kWord64:
      return kX64Word64AtomicStoreWord64;
    case MachineRepresentation::kTaggedSigned: // Fall through.
    case MachineRepresentation::kTaggedPointer: // Fall through.
    case MachineRepresentation::kTagged:
      if (COMPRESS_POINTERS_BOOL) return kAtomicStoreWord32;
      return kX64Word64AtomicStoreWord64;
    case MachineRepresentation::kCompressedPointer: // Fall through.
    case MachineRepresentation::kCompressed:
      CHECK(COMPRESS_POINTERS_BOOL);
      return kAtomicStoreWord32;
    default:
      UNREACHABLE();
  }
}
References CHECK, COMPRESS_POINTERS_BOOL, v8::internal::kCompressed, v8::internal::kCompressedPointer, v8::internal::kTagged, v8::internal::kTaggedPointer, v8::internal::kTaggedSigned, v8::internal::kWord16, v8::internal::kWord32, v8::internal::kWord64, v8::internal::kWord8, v8::internal::compiler::StoreRepresentation::representation(), and v8::internal::UNREACHABLE().
Referenced by VisitStoreCommon().
GetStoreOpcode()
ArchOpcode v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetStoreOpcode (MemoryRepresentation stored_rep)
Definition at line 975 of file instruction-selector-x64.cc.
                                                           {
  switch (stored_rep) {
    case MemoryRepresentation::Int8():
    case MemoryRepresentation::Uint8():
      return kX64Movb;
    case MemoryRepresentation::Int16():
    case MemoryRepresentation::Uint16():
      return kX64Movw;
    case MemoryRepresentation::Int32():
    case MemoryRepresentation::Uint32():
      return kX64Movl;
    case MemoryRepresentation::Int64():
    case MemoryRepresentation::Uint64():
      return kX64Movq;
    case MemoryRepresentation::Float16():
      return kX64Movsh;
    case MemoryRepresentation::Float32():
      return kX64Movss;
    case MemoryRepresentation::Float64():
      return kX64Movsd;
    case MemoryRepresentation::AnyTagged():
    case MemoryRepresentation::TaggedPointer():
    case MemoryRepresentation::TaggedSigned():
      return kX64MovqCompressTagged;
    case MemoryRepresentation::AnyUncompressedTagged():
    case MemoryRepresentation::UncompressedTaggedPointer():
    case MemoryRepresentation::UncompressedTaggedSigned():
      return kX64Movq;
    case MemoryRepresentation::ProtectedPointer():
      // We never store directly to protected pointers from generated code.
      UNREACHABLE();
    case MemoryRepresentation::IndirectPointer():
      return kX64MovqStoreIndirectPointer;
    case MemoryRepresentation::SandboxedPointer():
      return kX64MovqEncodeSandboxedPointer;
    case MemoryRepresentation::Simd128():
      return kX64Movdqu;
    case MemoryRepresentation::Simd256():
      return kX64Movdqu256;
  }
}
References v8::internal::compiler::turboshaft::MemoryRepresentation::AnyTagged(), v8::internal::compiler::turboshaft::MemoryRepresentation::AnyUncompressedTagged(), v8::internal::compiler::turboshaft::MemoryRepresentation::Float16(), v8::internal::compiler::turboshaft::MemoryRepresentation::Float32(), v8::internal::compiler::turboshaft::MemoryRepresentation::Float64(), v8::internal::compiler::turboshaft::MemoryRepresentation::IndirectPointer(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int16(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int32(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int64(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int8(), v8::internal::compiler::turboshaft::MemoryRepresentation::ProtectedPointer(), v8::internal::compiler::turboshaft::MemoryRepresentation::SandboxedPointer(), v8::internal::compiler::turboshaft::MemoryRepresentation::Simd128(), v8::internal::compiler::turboshaft::MemoryRepresentation::Simd256(), v8::internal::compiler::turboshaft::MemoryRepresentation::TaggedPointer(), v8::internal::compiler::turboshaft::MemoryRepresentation::TaggedSigned(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint16(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint32(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint64(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint8(), v8::internal::compiler::turboshaft::MemoryRepresentation::UncompressedTaggedPointer(), v8::internal::compiler::turboshaft::MemoryRepresentation::UncompressedTaggedSigned(), and v8::internal::UNREACHABLE().
Referenced by VisitStoreCommon().
IsCompressed()
bool v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::IsCompressed (InstructionSelector * selector, OpIndex node)
Definition at line 45 of file instruction-selector-x64.cc.
                                                               {
  if (!node.valid()) return false;
  if (selector->is_load(node)) {
    auto load = selector->load_view(node);
    return load.loaded_rep().IsCompressed();
  } else if (const PhiOp* phi = selector->TryCast<PhiOp>(node)) {
    MachineRepresentation phi_rep = phi->rep.machine_representation();
    return phi_rep == MachineRepresentation::kCompressed ||
           phi_rep == MachineRepresentation::kCompressedPointer;
  }
  return false;
}
References v8::internal::compiler::InstructionSelector::is_load(), v8::internal::MachineType::IsCompressed(), v8::internal::kCompressed, v8::internal::kCompressedPointer, v8::internal::compiler::InstructionSelector::load_view(), v8::internal::compiler::InstructionSelector::LoadView::loaded_rep(), v8::internal::compiler::turboshaft::OperationMatcher::TryCast(), and v8::internal::compiler::turboshaft::OpIndex::valid().
Referenced by v8::internal::compiler::X64OperandGenerator::GetEffectiveAddressMemoryOperand().
IsIntConstant()
bool v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::IsIntConstant (InstructionSelector * selector, OpIndex node)
Definition at line 3238 of file instruction-selector-x64.cc.
                                                                {
  if (auto constant = selector->Get(node).TryCast<ConstantOp>()) {
    return constant->kind == ConstantOp::Kind::kWord32 ||
           constant->kind == ConstantOp::Kind::kWord64;
  }
  return false;
}
References v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::ConstantOp::kWord32, v8::internal::compiler::turboshaft::ConstantOp::kWord64, and v8::internal::compiler::turboshaft::Operation::TryCast().
Referenced by MachineTypeForNarrowWordAnd(), RemoveUnnecessaryWordAnd(), and TryNarrowOpcodeSize().
IsWordAnd()
bool v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::IsWordAnd (InstructionSelector * selector, OpIndex node)
Definition at line 3245 of file instruction-selector-x64.cc.
                                                            {
  if (auto binop = selector->Get(node).TryCast<WordBinopOp>()) {
    return binop->kind == WordBinopOp::Kind::kBitwiseAnd;
  }
  return false;
}
References v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::WordBinopOp::kBitwiseAnd, and v8::internal::compiler::turboshaft::Operation::TryCast().
Referenced by TryNarrowOpcodeSize(), and VisitWordCompare().
MachineTypeForNarrow()
MachineType v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::MachineTypeForNarrow (InstructionSelector * selector, OpIndex node, OpIndex hint_node)
Definition at line 3194 of file instruction-selector-x64.cc.
                                                    {
  if (selector->IsLoadOrLoadImmutable(hint_node)) {
    MachineType hint = selector->load_view(hint_node).loaded_rep();
    int64_t constant;
    if (selector->MatchSignedIntegralConstant(node, &constant)) {
      if (hint == MachineType::Int8()) {
        if (constant >= std::numeric_limits<int8_t>::min() &&
            constant <= std::numeric_limits<int8_t>::max()) {
          return hint;
        }
      } else if (hint == MachineType::Uint8()) {
        if (constant >= std::numeric_limits<uint8_t>::min() &&
            constant <= std::numeric_limits<uint8_t>::max()) {
          return hint;
        }
      } else if (hint == MachineType::Int16()) {
        if (constant >= std::numeric_limits<int16_t>::min() &&
            constant <= std::numeric_limits<int16_t>::max()) {
          return hint;
        }
      } else if (hint == MachineType::Uint16()) {
        if (constant >= std::numeric_limits<uint16_t>::min() &&
            constant <= std::numeric_limits<uint16_t>::max()) {
          return hint;
        }
      } else if (hint == MachineType::Int32()) {
        if (constant >= std::numeric_limits<int32_t>::min() &&
            constant <= std::numeric_limits<int32_t>::max()) {
          return hint;
        }
      } else if (hint == MachineType::Uint32()) {
        if (constant >= std::numeric_limits<uint32_t>::min() &&
            constant <= std::numeric_limits<uint32_t>::max())
          return hint;
      }
    }
  }
  if (selector->IsLoadOrLoadImmutable(node)) {
    return selector->load_view(node).loaded_rep();
  }
  return MachineType::None();
}
References v8::internal::MachineType::Int16(), v8::internal::MachineType::Int32(), v8::internal::MachineType::Int8(), v8::internal::compiler::InstructionSelector::IsLoadOrLoadImmutable(), v8::internal::compiler::InstructionSelector::load_view(), v8::internal::compiler::InstructionSelector::LoadView::loaded_rep(), v8::internal::compiler::turboshaft::OperationMatcher::MatchSignedIntegralConstant(), v8::internal::MachineType::None(), v8::internal::MachineType::Uint16(), v8::internal::MachineType::Uint32(), and v8::internal::MachineType::Uint8().
Referenced by TryNarrowOpcodeSize().
MachineTypeForNarrowWordAnd()
MachineType v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::MachineTypeForNarrowWordAnd (InstructionSelector * selector, OpIndex and_node, OpIndex constant_node)
Definition at line 3255 of file instruction-selector-x64.cc.
                                                               {
  const WordBinopOp& op = selector->Cast<WordBinopOp>(and_node);
  DCHECK_EQ(op.input_count, 2);
  auto and_left = op.left();
  auto and_right = op.right();
  auto and_constant_node = IsIntConstant(selector, and_right) ? and_right
                           : IsIntConstant(selector, and_left) ? and_left
                                                               : OpIndex{};
  if (and_constant_node.valid()) {
    int64_t and_constant, cmp_constant;
    selector->MatchSignedIntegralConstant(and_constant_node, &and_constant);
    selector->MatchSignedIntegralConstant(constant_node, &cmp_constant);
    if (and_constant >= 0 && cmp_constant >= 0) {
      int64_t constant =
          and_constant > cmp_constant ? and_constant : cmp_constant;
      if (constant <= std::numeric_limits<int8_t>::max()) {
        return MachineType::Int8();
      } else if (constant <= std::numeric_limits<uint8_t>::max()) {
        return MachineType::Uint8();
      } else if (constant <= std::numeric_limits<int16_t>::max()) {
        return MachineType::Int16();
      } else if (constant <= std::numeric_limits<uint16_t>::max()) {
        return MachineType::Uint16();
      } else if (constant <= std::numeric_limits<int32_t>::max()) {
        return MachineType::Int32();
      } else if (constant <= std::numeric_limits<uint32_t>::max()) {
        return MachineType::Uint32();
      }
    }
  }
  return MachineType::None();
}
References v8::internal::compiler::turboshaft::OperationMatcher::Cast(), DCHECK_EQ, v8::internal::compiler::turboshaft::FixedArityOperationT< InputCount, Derived >::input_count, v8::internal::MachineType::Int16(), v8::internal::MachineType::Int32(), v8::internal::MachineType::Int8(), IsIntConstant(), v8::internal::compiler::turboshaft::WordBinopOp::left(), v8::internal::compiler::turboshaft::OperationMatcher::MatchSignedIntegralConstant(), v8::internal::MachineType::None(), v8::internal::compiler::turboshaft::WordBinopOp::right(), v8::internal::MachineType::Uint16(), v8::internal::MachineType::Uint32(), and v8::internal::MachineType::Uint8().
Referenced by TryNarrowOpcodeSize().
MatchHeapObjectEqual()
bool v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::MatchHeapObjectEqual (InstructionSelector * selector, OpIndex node, OpIndex * left, Handle< HeapObject > * right)
Definition at line 3494 of file instruction-selector-x64.cc.
                                                                    {
  const ComparisonOp& equal = selector->Cast<ComparisonOp>(node);
  DCHECK_EQ(equal.kind, ComparisonOp::Kind::kEqual);
  if (selector->MatchHeapConstant(equal.right(), right)) {
    *left = equal.left();
    return true;
  }
  return false;
}
References v8::internal::compiler::turboshaft::OperationMatcher::Cast(), DCHECK_EQ, v8::internal::equal, v8::internal::compiler::turboshaft::ComparisonOp::kEqual, and v8::internal::compiler::turboshaft::OperationMatcher::MatchHeapConstant().
Referenced by VisitWord32EqualImpl().
RemoveUnnecessaryWordAnd()
OpIndex v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::RemoveUnnecessaryWordAnd (InstructionSelector * selector, InstructionCode opcode, OpIndex and_node)
Definition at line 3373 of file instruction-selector-x64.cc.
                                                                           {
  int64_t mask = 0;
  if (opcode == kX64Cmp32 || opcode == kX64Test32) {
    mask = std::numeric_limits<uint32_t>::max();
  } else if (opcode == kX64Cmp16 || opcode == kX64Test16) {
    mask = std::numeric_limits<uint16_t>::max();
  } else if (opcode == kX64Cmp8 || opcode == kX64Test8) {
    mask = std::numeric_limits<uint8_t>::max();
  } else {
    return and_node;
  }
  const WordBinopOp& op = selector->Cast<WordBinopOp>(and_node);
  DCHECK_EQ(op.input_count, 2);
  auto and_left = op.left();
  auto and_right = op.right();
  auto and_constant_node = OpIndex{};
  auto and_other_node = OpIndex{};
  if (IsIntConstant(selector, and_left)) {
    and_constant_node = and_left;
    and_other_node = and_right;
  } else if (IsIntConstant(selector, and_right)) {
    and_constant_node = and_right;
    and_other_node = and_left;
  }
  if (and_constant_node.valid()) {
    int64_t and_constant;
    selector->MatchSignedIntegralConstant(and_constant_node, &and_constant);
    if (and_constant == mask) return and_other_node;
  }
  return and_node;
}
References v8::internal::compiler::turboshaft::OperationMatcher::Cast(), DCHECK_EQ, v8::internal::compiler::turboshaft::FixedArityOperationT< InputCount, Derived >::input_count, IsIntConstant(), v8::internal::compiler::turboshaft::WordBinopOp::left(), v8::internal::compiler::turboshaft::OperationMatcher::MatchSignedIntegralConstant(), and v8::internal::compiler::turboshaft::WordBinopOp::right().
Referenced by VisitWordCompare().
TryEmitLoadForLoadWord64AndShiftRight()
bool v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::TryEmitLoadForLoadWord64AndShiftRight (InstructionSelector * selector, OpIndex node, InstructionCode opcode)
Definition at line 2014 of file instruction-selector-x64.cc.
                                                                   {
  DCHECK(selector->Get(node).template Cast<ShiftOp>().IsRightShift());
  const ShiftOp& shift = selector->Get(node).template Cast<ShiftOp>();
  X64OperandGenerator g(selector);
  if (selector->CanCover(node, shift.left()) &&
      selector->Get(shift.left()).Is<LoadOp>() &&
      selector->MatchIntegralWord32Constant(shift.right(), 32)) {
    DCHECK_EQ(selector->GetEffectLevel(node),
              selector->GetEffectLevel(shift.left()));
    // Just load and sign-extend the interesting 4 bytes instead. This happens,
    // for example, when we're loading and untagging SMIs.
    auto m =
        TryMatchBaseWithScaledIndexAndDisplacement64(selector, shift.left());
    if (m.has_value() &&
        (m->displacement == 0 || ValueFitsIntoImmediate(m->displacement))) {
#ifdef V8_IS_TSAN
      // On TSAN builds we require one scratch register. Because of this we also
      // have to modify the inputs to take into account possible aliasing and
      // use UseUniqueRegister which is not required for non-TSAN builds.
      InstructionOperand temps[] = {g.TempRegister()};
      size_t temp_count = arraysize(temps);
      auto reg_kind = OperandGenerator::RegisterUseKind::kUseUniqueRegister;
#else
      InstructionOperand* temps = nullptr;
      size_t temp_count = 0;
      auto reg_kind = OperandGenerator::RegisterUseKind::kUseRegister;
#endif // V8_IS_TSAN
      size_t input_count = 0;
      InstructionOperand inputs[3];
      AddressingMode mode = g.GetEffectiveAddressMemoryOperand(
          shift.left(), inputs, &input_count, reg_kind);
      if (m->displacement == 0) {
        // Make sure that the addressing mode indicates the presence of an
        // immediate displacement. It seems that we never use M1 and M2, but we
        // handle them here anyways.
        mode = AddDisplacementToAddressingMode(mode);
        inputs[input_count++] =
            ImmediateOperand(ImmediateOperand::INLINE_INT32, 4);
      } else {
        // In the case that the base address was zero, the displacement will be
        // in a register and replacing it with an immediate is not allowed. This
        // usually only happens in dead code anyway.
        if (!inputs[input_count - 1].IsImmediate()) return false;
        inputs[input_count - 1] =
            ImmediateOperand(ImmediateOperand::INLINE_INT32,
                             static_cast<int32_t>(m->displacement) + 4);
      }
      InstructionOperand outputs[] = {g.DefineAsRegister(node)};
      InstructionCode code = opcode | AddressingModeField::encode(mode);
      selector->Emit(code, 1, outputs, input_count, inputs, temp_count, temps);
      return true;
    }
  }
  return false;
}
References AddDisplacementToAddressingMode(), arraysize, v8::internal::compiler::InstructionSelector::CanCover(), code, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::InstructionSelector::Emit(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::X64OperandGenerator::GetEffectiveAddressMemoryOperand(), v8::internal::compiler::InstructionSelector::GetEffectLevel(), v8::internal::compiler::ImmediateOperand::INLINE_INT32, v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::compiler::OperandGenerator::kUseRegister, v8::internal::compiler::OperandGenerator::kUseUniqueRegister, v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralWord32Constant(), mode(), v8::internal::compiler::turboshaft::ShiftOp::right(), v8::internal::compiler::OperandGenerator::TempRegister(), v8::internal::compiler::TryMatchBaseWithScaledIndexAndDisplacement64(), and v8::internal::compiler::ValueFitsIntoImmediate().
TryNarrowOpcodeSize()
InstructionCode v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::TryNarrowOpcodeSize (InstructionSelector * selector, InstructionCode opcode, OpIndex left, OpIndex right, FlagsContinuation * cont)
Definition at line 3294 of file instruction-selector-x64.cc.
                                                                            {
  MachineType left_type = MachineType::None();
  MachineType right_type = MachineType::None();
  if (IsWordAnd(selector, left) && IsIntConstant(selector, right)) {
    left_type = MachineTypeForNarrowWordAnd(selector, left, right);
    right_type = left_type;
  } else if (IsWordAnd(selector, right) && IsIntConstant(selector, left)) {
    right_type = MachineTypeForNarrowWordAnd(selector, right, left);
    left_type = right_type;
  } else {
    // TODO(epertoso): we can probably get some size information out phi nodes.
    // If the load representations don't match, both operands will be
    // zero/sign-extended to 32bit.
    left_type = MachineTypeForNarrow(selector, left, right);
    right_type = MachineTypeForNarrow(selector, right, left);
  }
  if (left_type == right_type) {
    switch (left_type.representation()) {
      case MachineRepresentation::kBit:
      case MachineRepresentation::kWord8: {
        if (opcode == kX64Test || opcode == kX64Test32) return kX64Test8;
        if (opcode == kX64Cmp || opcode == kX64Cmp32) {
          if (left_type.semantic() == MachineSemantic::kUint32) {
            cont->OverwriteUnsignedIfSigned();
          } else {
            CHECK_EQ(MachineSemantic::kInt32, left_type.semantic());
          }
          return kX64Cmp8;
        }
        break;
      }
      // Cmp16/Test16 may introduce LCP(Length-Changing-Prefixes) stall, use
      // Cmp32/Test32 instead.
      case MachineRepresentation::kWord16: // Fall through.
      case MachineRepresentation::kWord32:
        if (opcode == kX64Test) return kX64Test32;
        if (opcode == kX64Cmp) {
          if (left_type.semantic() == MachineSemantic::kUint32) {
            cont->OverwriteUnsignedIfSigned();
          } else {
            CHECK_EQ(MachineSemantic::kInt32, left_type.semantic());
          }
          return kX64Cmp32;
        }
        break;
#ifdef V8_COMPRESS_POINTERS
      case MachineRepresentation::kTaggedSigned:
      case MachineRepresentation::kTaggedPointer:
      case MachineRepresentation::kTagged:
        // When pointer compression is enabled the lower 32-bits uniquely
        // identify tagged value.
        if (opcode == kX64Cmp) return kX64Cmp32;
        break;
#endif
      default:
        break;
    }
  }
  return opcode;
}
References CHECK_EQ, IsIntConstant(), IsWordAnd(), v8::internal::kBit, v8::internal::kInt32, v8::internal::kTagged, v8::internal::kTaggedPointer, v8::internal::kTaggedSigned, v8::internal::kUint32, v8::internal::kWord16, v8::internal::kWord32, v8::internal::kWord8, MachineTypeForNarrow(), MachineTypeForNarrowWordAnd(), v8::internal::MachineType::None(), v8::internal::compiler::FlagsContinuation::OverwriteUnsignedIfSigned(), v8::internal::MachineType::representation(), and v8::internal::MachineType::semantic().
Referenced by VisitWordCompare().
TryVisitWordShift()
bool v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::TryVisitWordShift (InstructionSelector * selector, OpIndex node, int bits, ArchOpcode opcode, FlagsContinuation * cont)
Definition at line 1886 of file instruction-selector-x64.cc.
                                                                   {
  DCHECK(bits == 32 || bits == 64);
  X64OperandGenerator g(selector);
  const ShiftOp& op = selector->Cast<ShiftOp>(node);
  DCHECK_EQ(op.input_count, 2);
  auto left = op.left();
  auto right = op.right();
  // If the shift count is 0, the flags are not affected.
  if (!g.CanBeImmediate(right) ||
      (g.GetImmediateIntegerValue(right) & (bits - 1)) == 0) {
    return false;
  }
  InstructionOperand output = g.DefineSameAsFirst(node);
  InstructionOperand inputs[2];
  inputs[0] = g.UseRegister(left);
  inputs[1] = g.UseImmediate(right);
  selector->EmitWithContinuation(opcode, 1, &output, 2, inputs, cont);
  return true;
}
References v8::internal::compiler::X64OperandGenerator::CanBeImmediate(), v8::internal::compiler::turboshaft::OperationMatcher::Cast(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::OperandGenerator::DefineSameAsFirst(), v8::internal::compiler::InstructionSelector::EmitWithContinuation(), v8::internal::compiler::X64OperandGenerator::GetImmediateIntegerValue(), v8::internal::compiler::turboshaft::FixedArityOperationT< InputCount, Derived >::input_count, v8::internal::compiler::turboshaft::ShiftOp::right(), v8::internal::compiler::OperandGenerator::UseImmediate(), and v8::internal::compiler::OperandGenerator::UseRegister().
Referenced by VisitCompareZero().
VisitAtomicBinop()
void v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitAtomicBinop (InstructionSelector * selector, OpIndex node, ArchOpcode opcode, AtomicWidth width, MemoryAccessKind access_kind)
Definition at line 3633 of file instruction-selector-x64.cc.
                                                    {
  const AtomicRMWOp& atomic_op = selector->Cast<AtomicRMWOp>(node);
  X64OperandGenerator g(selector);
  AddressingMode addressing_mode;
  InstructionOperand inputs[] = {
      g.UseUniqueRegister(atomic_op.value()),
      g.UseUniqueRegister(atomic_op.base()),
      g.GetEffectiveIndexOperand(atomic_op.index(), &addressing_mode)};
  InstructionOperand outputs[] = {g.DefineAsFixed(node, rax)};
  InstructionOperand temps[] = {g.TempRegister()};
  InstructionCode code = opcode | AddressingModeField::encode(addressing_mode) |
                         AtomicWidthField::encode(width);
  if (access_kind == MemoryAccessKind::kProtectedByTrapHandler) {
    code |= AccessModeField::encode(kMemoryAccessProtectedMemOutOfBounds);
  }
  selector->Emit(code, arraysize(outputs), outputs, arraysize(inputs), inputs,
                 arraysize(temps), temps);
}
References arraysize, v8::internal::compiler::turboshaft::AtomicRMWOp::base(), v8::internal::compiler::turboshaft::OperationMatcher::Cast(), code, v8::internal::compiler::InstructionSelector::Emit(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::turboshaft::AtomicRMWOp::index(), v8::internal::compiler::kMemoryAccessProtectedMemOutOfBounds, v8::internal::compiler::kProtectedByTrapHandler, and v8::internal::compiler::turboshaft::AtomicRMWOp::value().
VisitAtomicCompareExchange()
void v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitAtomicCompareExchange (InstructionSelector * selector, OpIndex node, ArchOpcode opcode, AtomicWidth width, MemoryAccessKind access_kind)
Definition at line 3655 of file instruction-selector-x64.cc.
                                                              {
  const AtomicRMWOp& atomic_op = selector->Cast<AtomicRMWOp>(node);
  X64OperandGenerator g(selector);
  AddressingMode addressing_mode;
  InstructionOperand inputs[] = {
      g.UseFixed(atomic_op.expected().value(), rax),
      g.UseUniqueRegister(atomic_op.value()),
      g.UseUniqueRegister(atomic_op.base()),
      g.GetEffectiveIndexOperand(atomic_op.index(), &addressing_mode)};
  InstructionOperand outputs[] = {g.DefineAsFixed(node, rax)};
  InstructionCode code = opcode | AddressingModeField::encode(addressing_mode) |
                         AtomicWidthField::encode(width);
  if (access_kind == MemoryAccessKind::kProtectedByTrapHandler) {
    code |= AccessModeField::encode(kMemoryAccessProtectedMemOutOfBounds);
  }
  selector->Emit(code, arraysize(outputs), outputs, arraysize(inputs), inputs);
}
References arraysize, v8::internal::compiler::turboshaft::AtomicRMWOp::base(), v8::internal::compiler::turboshaft::OperationMatcher::Cast(), code, v8::internal::compiler::InstructionSelector::Emit(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::turboshaft::AtomicRMWOp::expected(), v8::internal::compiler::turboshaft::AtomicRMWOp::index(), v8::internal::compiler::kMemoryAccessProtectedMemOutOfBounds, v8::internal::compiler::kProtectedByTrapHandler, v8::internal::compiler::turboshaft::OptionalOpIndex::value(), and v8::internal::compiler::turboshaft::AtomicRMWOp::value().
VisitAtomicExchange()
void v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitAtomicExchange (InstructionSelector * selector, OpIndex node, ArchOpcode opcode, AtomicWidth width, MemoryAccessKind access_kind)
Definition at line 1392 of file instruction-selector-x64.cc.
                                                       {
  const AtomicRMWOp& atomic_op = selector->Cast<AtomicRMWOp>(node);
  X64OperandGenerator g(selector);
  AddressingMode addressing_mode;
  InstructionOperand inputs[] = {
      g.UseUniqueRegister(atomic_op.value()),
      g.UseUniqueRegister(atomic_op.base()),
      g.GetEffectiveIndexOperand(atomic_op.index(), &addressing_mode)};
  base::SmallVector<InstructionOperand, 3> temps;
  if (opcode == kAtomicExchangeWithWriteBarrier) {
    temps.push_back(g.TempRegister());
    temps.push_back(g.TempRegister());
    temps.push_back(g.TempRegister());
  }
  InstructionOperand outputs[] = {g.DefineSameAsFirst(node)};
  InstructionCode code = opcode | AddressingModeField::encode(addressing_mode) |
                         AtomicWidthField::encode(width);
  if (access_kind == MemoryAccessKind::kProtectedByTrapHandler) {
    code |= AccessModeField::encode(kMemoryAccessProtectedMemOutOfBounds);
  }
  selector->Emit(code, arraysize(outputs), outputs, arraysize(inputs), inputs,
                 temps.size(), temps.data());
}
References arraysize, v8::internal::compiler::turboshaft::AtomicRMWOp::base(), v8::internal::compiler::turboshaft::OperationMatcher::Cast(), code, v8::base::SmallVector< T, kSize, Allocator >::data(), v8::internal::compiler::InstructionSelector::Emit(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::turboshaft::AtomicRMWOp::index(), v8::internal::compiler::kMemoryAccessProtectedMemOutOfBounds, v8::internal::compiler::kProtectedByTrapHandler, v8::base::SmallVector< T, kSize, Allocator >::push_back(), v8::base::SmallVector< T, kSize, Allocator >::size(), and v8::internal::compiler::turboshaft::AtomicRMWOp::value().
VisitCompare() [1/2]
void v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitCompare (InstructionSelector * selector, InstructionCode opcode, InstructionOperand left, InstructionOperand right, FlagsContinuation * cont)
Definition at line 3163 of file instruction-selector-x64.cc.
                                           {
  if (cont->IsSelect()) {
    X64OperandGenerator g(selector);
    InstructionOperand inputs[4] = {left, right};
    if (cont->condition() == kUnorderedEqual) {
      cont->Negate();
      inputs[2] = g.UseRegister(cont->true_value());
      inputs[3] = g.Use(cont->false_value());
    } else {
      inputs[2] = g.UseRegister(cont->false_value());
      inputs[3] = g.Use(cont->true_value());
    }
    selector->EmitWithContinuation(opcode, 0, nullptr, 4, inputs, cont);
    return;
  }
  selector->EmitWithContinuation(opcode, left, right, cont);
}
References v8::internal::compiler::FlagsContinuation::condition(), v8::internal::compiler::InstructionSelector::EmitWithContinuation(), v8::internal::compiler::FlagsContinuation::false_value(), v8::internal::compiler::FlagsContinuation::IsSelect(), v8::internal::compiler::kUnorderedEqual, v8::internal::compiler::FlagsContinuation::Negate(), v8::internal::compiler::FlagsContinuation::true_value(), v8::internal::compiler::OperandGenerator::Use(), and v8::internal::compiler::OperandGenerator::UseRegister().
VisitCompare() [2/2]
void v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitCompare (InstructionSelector * selector, InstructionCode opcode, OpIndex left, OpIndex right, FlagsContinuation * cont, bool commutative)
Definition at line 3184 of file instruction-selector-x64.cc.
                                    {
  X64OperandGenerator g(selector);
  if (commutative && g.CanBeBetterLeftOperand(right)) {
    std::swap(left, right);
  }
  VisitCompare(selector, opcode, g.UseRegister(left), g.Use(right), cont);
}
References v8::internal::compiler::X64OperandGenerator::CanBeBetterLeftOperand(), v8::internal::compiler::OperandGenerator::Use(), v8::internal::compiler::OperandGenerator::UseRegister(), and v8::internal::compiler::VisitCompare().
VisitCompareWithMemoryOperand()
void v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitCompareWithMemoryOperand (InstructionSelector * selector, InstructionCode opcode, OpIndex left, InstructionOperand right, FlagsContinuation * cont)
Definition at line 3136 of file instruction-selector-x64.cc.
                                                            {
  DCHECK(selector->IsLoadOrLoadImmutable(left));
  X64OperandGenerator g(selector);
  size_t input_count = 0;
  InstructionOperand inputs[6];
  AddressingMode addressing_mode =
      g.GetEffectiveAddressMemoryOperand(left, inputs, &input_count);
  opcode |= AddressingModeField::encode(addressing_mode);
  inputs[input_count++] = right;
  if (cont->IsSelect()) {
    if (opcode == kUnorderedEqual) {
      cont->Negate();
      inputs[input_count++] = g.UseRegister(cont->true_value());
      inputs[input_count++] = g.Use(cont->false_value());
    } else {
      inputs[input_count++] = g.UseRegister(cont->false_value());
      inputs[input_count++] = g.Use(cont->true_value());
    }
  }
  selector->EmitWithContinuation(opcode, 0, nullptr, input_count, inputs, cont);
}
References v8::internal::DCHECK(), v8::internal::compiler::InstructionSelector::EmitWithContinuation(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::FlagsContinuation::false_value(), v8::internal::compiler::X64OperandGenerator::GetEffectiveAddressMemoryOperand(), v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::InstructionSelector::IsLoadOrLoadImmutable(), v8::internal::compiler::FlagsContinuation::IsSelect(), v8::internal::compiler::kUnorderedEqual, v8::internal::compiler::FlagsContinuation::Negate(), v8::internal::compiler::FlagsContinuation::true_value(), v8::internal::compiler::OperandGenerator::Use(), and v8::internal::compiler::OperandGenerator::UseRegister().
Referenced by VisitCompareZero(), and VisitWordCompare().
VisitCompareZero()
void v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitCompareZero (InstructionSelector * selector, OpIndex user, OpIndex node, InstructionCode opcode, FlagsContinuation * cont)
Definition at line 3543 of file instruction-selector-x64.cc.
                                                                       {
  X64OperandGenerator g(selector);
  const Operation& op = selector->turboshaft_graph()->Get(node);
  if (cont->IsBranch() &&
      (cont->condition() == kNotEqual || cont->condition() == kEqual)) {
    if (const WordBinopOp* binop = op.TryCast<WordBinopOp>()) {
      if (selector->IsOnlyUserOfNodeInSameBlock(user, node)) {
        const bool is64 = binop->rep == WordRepresentation::Word64();
        switch (binop->kind) {
          case WordBinopOp::Kind::kAdd:
            return VisitBinop(selector, node, is64 ? kX64Add : kX64Add32, cont);
          case WordBinopOp::Kind::kSub:
            return VisitBinop(selector, node, is64 ? kX64Sub : kX64Sub32, cont);
          case WordBinopOp::Kind::kBitwiseAnd:
            return VisitBinop(selector, node, is64 ? kX64And : kX64And32, cont);
          case WordBinopOp::Kind::kBitwiseOr:
            return VisitBinop(selector, node, is64 ? kX64Or : kX64Or32, cont);
          default:
            break;
        }
      }
    } else if (const ShiftOp* shift = op.TryCast<ShiftOp>()) {
      if (selector->IsOnlyUserOfNodeInSameBlock(user, node)) {
        const bool is64 = shift->rep == WordRepresentation::Word64();
        switch (shift->kind) {
          case ShiftOp::Kind::kShiftLeft:
            if (TryVisitWordShift(selector, node, is64 ? 64 : 32,
                                  is64 ? kX64Shl : kX64Shl32, cont)) {
              return;
            }
            break;
          case ShiftOp::Kind::kShiftRightLogical:
            if (TryVisitWordShift(selector, node, is64 ? 64 : 32,
                                  is64 ? kX64Shr : kX64Shr32, cont)) {
              return;
            }
            break;
          default:
            break;
        }
      }
    }
  }
  int effect_level = selector->GetEffectLevel(node, cont);
  if (const auto load = op.TryCast<LoadOp>()) {
    if (load->loaded_rep == MemoryRepresentation::Int8() ||
        load->loaded_rep == MemoryRepresentation::Uint8()) {
      if (opcode == kX64Cmp32) {
        opcode = kX64Cmp8;
      } else if (opcode == kX64Test32) {
        opcode = kX64Test8;
      }
    } else if (load->loaded_rep == MemoryRepresentation::Int16() ||
               load->loaded_rep == MemoryRepresentation::Uint16()) {
      if (opcode == kX64Cmp32) {
        opcode = kX64Cmp16;
      } else if (opcode == kX64Test32) {
        opcode = kX64Test16;
      }
    }
  }
  if (g.CanBeMemoryOperand(opcode, user, node, effect_level)) {
    VisitCompareWithMemoryOperand(selector, opcode, node, g.TempImmediate(0),
                                  cont);
  } else {
    VisitCompare(selector, opcode, g.Use(node), g.TempImmediate(0), cont);
  }
}
References v8::internal::compiler::X64OperandGenerator::CanBeMemoryOperand(), v8::internal::compiler::FlagsContinuation::condition(), v8::internal::compiler::turboshaft::Graph::Get(), v8::internal::compiler::InstructionSelector::GetEffectLevel(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int16(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int8(), v8::internal::compiler::FlagsContinuation::IsBranch(), v8::internal::compiler::InstructionSelector::IsOnlyUserOfNodeInSameBlock(), v8::internal::compiler::turboshaft::WordBinopOp::kAdd, v8::internal::compiler::turboshaft::WordBinopOp::kBitwiseAnd, v8::internal::compiler::turboshaft::WordBinopOp::kBitwiseOr, v8::internal::kEqual, v8::internal::compiler::kNotEqual, v8::internal::compiler::turboshaft::WordBinopOp::kSub, v8::internal::compiler::OperandGenerator::TempImmediate(), v8::internal::compiler::turboshaft::Operation::TryCast(), TryVisitWordShift(), v8::internal::compiler::InstructionSelector::turboshaft_graph(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint16(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint8(), v8::internal::compiler::OperandGenerator::Use(), v8::internal::compiler::VisitBinop(), v8::internal::compiler::VisitCompare(), VisitCompareWithMemoryOperand(), and v8::internal::compiler::turboshaft::WordRepresentation::Word64().
VisitDiv()
void v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitDiv (InstructionSelector * selector, OpIndex node, ArchOpcode opcode)
Definition at line 2300 of file instruction-selector-x64.cc.
                                                                              {
  X64OperandGenerator g(selector);
  auto [left, right] = selector->Inputs<WordBinopOp>(node);
  InstructionOperand temps[] = {g.TempRegister(rdx)};
  selector->Emit(opcode, g.DefineAsFixed(node, rax), g.UseFixed(left, rax),
                 g.UseUniqueRegister(right), arraysize(temps), temps);
}
References arraysize, v8::internal::compiler::OperandGenerator::DefineAsFixed(), v8::internal::compiler::InstructionSelector::Emit(), v8::internal::compiler::InstructionSelector::Inputs(), v8::internal::compiler::OperandGenerator::TempRegister(), v8::internal::compiler::OperandGenerator::UseFixed(), and v8::internal::compiler::OperandGenerator::UseUniqueRegister().
VisitFloat32Compare()
void v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitFloat32Compare (InstructionSelector * selector, OpIndex node, FlagsContinuation * cont)
Definition at line 3615 of file instruction-selector-x64.cc.
                                                  {
  const ComparisonOp& op = selector->Cast<ComparisonOp>(node);
  InstructionCode const opcode =
      selector->IsSupported(AVX) ? kAVXFloat32Cmp : kSSEFloat32Cmp;
  VisitCompare(selector, opcode, op.right(), op.left(), cont, false);
}
References v8::internal::compiler::turboshaft::OperationMatcher::Cast(), v8::internal::compiler::InstructionSelector::IsSupported(), v8::internal::compiler::turboshaft::ComparisonOp::left(), v8::internal::compiler::turboshaft::ComparisonOp::right(), and v8::internal::compiler::VisitCompare().
VisitFloat64Compare()
void v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitFloat64Compare (InstructionSelector * selector, OpIndex node, FlagsContinuation * cont)
Definition at line 3624 of file instruction-selector-x64.cc.
                                                  {
  const ComparisonOp& op = selector->Cast<ComparisonOp>(node);
  InstructionCode const opcode =
      selector->IsSupported(AVX) ? kAVXFloat64Cmp : kSSEFloat64Cmp;
  VisitCompare(selector, opcode, op.right(), op.left(), cont, false);
}
References v8::internal::compiler::turboshaft::OperationMatcher::Cast(), v8::internal::compiler::InstructionSelector::IsSupported(), v8::internal::compiler::turboshaft::ComparisonOp::left(), v8::internal::compiler::turboshaft::ComparisonOp::right(), and v8::internal::compiler::VisitCompare().
VisitFloatBinop()
void v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitFloatBinop (InstructionSelector * selector, OpIndex node, InstructionCode avx_opcode, InstructionCode sse_opcode)
Definition at line 2707 of file instruction-selector-x64.cc.
                                                                             {
  X64OperandGenerator g(selector);
  const FloatBinopOp& op = selector->Cast<FloatBinopOp>(node);
  DCHECK_EQ(op.input_count, 2);
  auto left = op.left();
  auto right = op.right();
  InstructionOperand inputs[8];
  size_t input_count = 0;
  InstructionOperand outputs[1];
  size_t output_count = 0;
  OpIndex trapping_load = {};
  if (left == right) {
    // If both inputs refer to the same operand, enforce allocating a register
    // for both of them to ensure that we don't end up generating code like
    // this:
    //
    // movss rax, [rbp-0x10]
    // addss rax, [rbp-0x10]
    // jo label
    InstructionOperand const input = g.UseRegister(left);
    inputs[input_count++] = input;
    inputs[input_count++] = input;
  } else {
    int effect_level = selector->GetEffectLevel(node);
    if (selector->IsCommutative(node) &&
        (g.CanBeBetterLeftOperand(right) ||
         g.CanBeMemoryOperand(avx_opcode, node, left, effect_level)) &&
        (!g.CanBeBetterLeftOperand(left) ||
         !g.CanBeMemoryOperand(avx_opcode, node, right, effect_level))) {
      std::swap(left, right);
    }
    if (g.CanBeMemoryOperand(avx_opcode, node, right, effect_level)) {
      inputs[input_count++] = g.UseRegister(left);
      AddressingMode addressing_mode =
          g.GetEffectiveAddressMemoryOperand(right, inputs, &input_count);
      avx_opcode |= AddressingModeField::encode(addressing_mode);
      sse_opcode |= AddressingModeField::encode(addressing_mode);
      if (selector->IsProtectedLoad(right) &&
          selector->CanCoverProtectedLoad(node, right)) {
        // In {CanBeMemoryOperand} we have already checked that
        // CanCover(node, right) succeeds, which means that there is no
        // instruction with Effects required_when_unused or
        // produces.control_flow between right and node, and that the node has
        // no other uses. Therefore, we can record the fact that 'right' was
        // embedded in 'node' and we can later delete the Load instruction.
        selector->MarkAsProtected(node);
        avx_opcode |=
            AccessModeField::encode(kMemoryAccessProtectedMemOutOfBounds);
        sse_opcode |=
            AccessModeField::encode(kMemoryAccessProtectedMemOutOfBounds);
        selector->SetProtectedLoadToRemove(right);
        trapping_load = right;
      }
    } else {
      inputs[input_count++] = g.UseRegister(left);
      inputs[input_count++] = g.Use(right);
    }
  }
  DCHECK_NE(0u, input_count);
  DCHECK_GE(arraysize(inputs), input_count);
  InstructionCode code = selector->IsSupported(AVX) ? avx_opcode : sse_opcode;
  outputs[output_count++] = selector->IsSupported(AVX)
                                ? g.DefineAsRegister(node)
                                : g.DefineSameAsFirst(node);
  DCHECK_EQ(1u, output_count);
  DCHECK_GE(arraysize(outputs), output_count);
  Instruction* instr =
      selector->Emit(code, output_count, outputs, input_count, inputs);
  if (trapping_load.valid()) {
    selector->UpdateSourcePosition(instr, trapping_load);
  }
}
References arraysize, v8::internal::compiler::X64OperandGenerator::CanBeBetterLeftOperand(), v8::internal::compiler::X64OperandGenerator::CanBeMemoryOperand(), v8::internal::compiler::InstructionSelector::CanCoverProtectedLoad(), v8::internal::compiler::turboshaft::OperationMatcher::Cast(), code, DCHECK_EQ, DCHECK_GE, DCHECK_NE, v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::OperandGenerator::DefineSameAsFirst(), v8::internal::compiler::InstructionSelector::Emit(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::X64OperandGenerator::GetEffectiveAddressMemoryOperand(), v8::internal::compiler::InstructionSelector::GetEffectLevel(), v8::internal::compiler::turboshaft::FixedArityOperationT< InputCount, Derived >::input_count, v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::InstructionSelector::IsCommutative(), v8::internal::compiler::InstructionSelector::IsProtectedLoad(), v8::internal::compiler::InstructionSelector::IsSupported(), v8::internal::compiler::kMemoryAccessProtectedMemOutOfBounds, v8::internal::compiler::turboshaft::FloatBinopOp::left(), v8::internal::compiler::InstructionSelector::MarkAsProtected(), v8::internal::compiler::turboshaft::FloatBinopOp::right(), v8::internal::compiler::InstructionSelector::SetProtectedLoadToRemove(), v8::internal::compiler::InstructionSelector::UpdateSourcePosition(), v8::internal::compiler::OperandGenerator::Use(), v8::internal::compiler::OperandGenerator::UseRegister(), and v8::internal::compiler::turboshaft::OpIndex::valid().
VisitFloatUnop()
void v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitFloatUnop (InstructionSelector * selector, OpIndex node, OpIndex input, InstructionCode opcode)
Definition at line 2783 of file instruction-selector-x64.cc.
                                            {
  X64OperandGenerator g(selector);
  if (selector->IsSupported(AVX)) {
    selector->Emit(opcode, g.DefineAsRegister(node), g.UseRegister(input));
  } else {
    selector->Emit(opcode, g.DefineSameAsFirst(node), g.UseRegister(input));
  }
}
References v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::OperandGenerator::DefineSameAsFirst(), v8::internal::compiler::InstructionSelector::Emit(), v8::internal::compiler::InstructionSelector::IsSupported(), and v8::internal::compiler::OperandGenerator::UseRegister().
VisitMinOrMax()
template<VectorLength vec_len>
void v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitMinOrMax (InstructionSelector * selector, OpIndex node, ArchOpcode opcode, bool flip_inputs)
Definition at line 1043 of file instruction-selector-x64.cc.
                                                        {
  X64OperandGenerator g(selector);
  const Operation& op = selector->Get(node);
  DCHECK_EQ(op.input_count, 2);
  InstructionOperand dst = selector->IsSupported(AVX)
                               ? g.DefineAsRegister(node)
                               : g.DefineSameAsFirst(node);
  InstructionCode instr_code = opcode | VectorLengthField::encode(vec_len);
  if (flip_inputs) {
    // Due to the way minps/minpd work, we want the dst to be same as the second
    // input: b = pmin(a, b) directly maps to minps b a.
    selector->Emit(instr_code, dst, g.UseRegister(op.input(1)),
                   g.UseRegister(op.input(0)));
  } else {
    selector->Emit(instr_code, dst, g.UseRegister(op.input(0)),
                   g.UseRegister(op.input(1)));
  }
}
References DCHECK_EQ, v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::OperandGenerator::DefineSameAsFirst(), v8::internal::compiler::InstructionSelector::Emit(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::turboshaft::Operation::input_count, v8::internal::compiler::InstructionSelector::IsSupported(), and v8::internal::compiler::OperandGenerator::UseRegister().
VisitMod()
void v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitMod (InstructionSelector * selector, OpIndex node, ArchOpcode opcode)
Definition at line 2308 of file instruction-selector-x64.cc.
                                                                              {
  X64OperandGenerator g(selector);
  auto [left, right] = selector->Inputs<WordBinopOp>(node);
  InstructionOperand temps[] = {g.TempRegister(rax)};
  selector->Emit(opcode, g.DefineAsFixed(node, rdx), g.UseFixed(left, rax),
                 g.UseUniqueRegister(right), arraysize(temps), temps);
}
References arraysize, v8::internal::compiler::OperandGenerator::DefineAsFixed(), v8::internal::compiler::InstructionSelector::Emit(), v8::internal::compiler::InstructionSelector::Inputs(), v8::internal::compiler::OperandGenerator::TempRegister(), v8::internal::compiler::OperandGenerator::UseFixed(), and v8::internal::compiler::OperandGenerator::UseUniqueRegister().
VisitMul()
void v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitMul (InstructionSelector * selector, OpIndex node, ArchOpcode opcode)
Definition at line 2271 of file instruction-selector-x64.cc.
                                                                              {
  X64OperandGenerator g(selector);
  auto [left, right] = selector->Inputs<WordBinopOp>(node);
  if (g.CanBeImmediate(right)) {
    selector->Emit(opcode, g.DefineAsRegister(node), g.Use(left),
                   g.UseImmediate(right));
  } else {
    if (g.CanBeBetterLeftOperand(right)) {
      std::swap(left, right);
    }
    selector->Emit(opcode, g.DefineSameAsFirst(node), g.UseRegister(left),
                   g.Use(right));
  }
}
References v8::internal::compiler::X64OperandGenerator::CanBeBetterLeftOperand(), v8::internal::compiler::X64OperandGenerator::CanBeImmediate(), v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::OperandGenerator::DefineSameAsFirst(), v8::internal::compiler::InstructionSelector::Emit(), v8::internal::compiler::InstructionSelector::Inputs(), v8::internal::compiler::OperandGenerator::Use(), v8::internal::compiler::OperandGenerator::UseImmediate(), and v8::internal::compiler::OperandGenerator::UseRegister().
VisitMulHigh()
void v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitMulHigh (InstructionSelector * selector, OpIndex node, ArchOpcode opcode)
Definition at line 2286 of file instruction-selector-x64.cc.
                                     {
  X64OperandGenerator g(selector);
  auto [left, right] = selector->Inputs<WordBinopOp>(node);
  if (selector->IsLive(left) && !selector->IsLive(right)) {
    std::swap(left, right);
  }
  InstructionOperand temps[] = {g.TempRegister(rax)};
  // TODO(turbofan): We use UseUniqueRegister here to improve register
  // allocation.
  selector->Emit(opcode, g.DefineAsFixed(node, rdx), g.UseFixed(left, rax),
                 g.UseUniqueRegister(right), arraysize(temps), temps);
}
References arraysize, v8::internal::compiler::OperandGenerator::DefineAsFixed(), v8::internal::compiler::InstructionSelector::Emit(), v8::internal::compiler::InstructionSelector::Inputs(), v8::internal::compiler::InstructionSelector::IsLive(), v8::internal::compiler::OperandGenerator::TempRegister(), v8::internal::compiler::OperandGenerator::UseFixed(), and v8::internal::compiler::OperandGenerator::UseUniqueRegister().
VisitRO()
void v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitRO (InstructionSelector * selector, OpIndex node, InstructionCode opcode)
Definition at line 2682 of file instruction-selector-x64.cc.
                                     {
  X64OperandGenerator g(selector);
  const Operation& op = selector->Get(node);
  DCHECK_EQ(op.input_count, 1);
  selector->Emit(opcode, g.DefineAsRegister(node), g.Use(op.input(0)));
}
References DCHECK_EQ, v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::InstructionSelector::Emit(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::turboshaft::Operation::input_count, and v8::internal::compiler::OperandGenerator::Use().
VisitRR()
void v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitRR (InstructionSelector * selector, OpIndex node, InstructionCode opcode)
Definition at line 2690 of file instruction-selector-x64.cc.
                                     {
  X64OperandGenerator g(selector);
  const Operation& op = selector->Get(node);
  DCHECK_EQ(op.input_count, 1);
  selector->Emit(opcode, g.DefineAsRegister(node), g.UseRegister(op.input(0)));
}
References DCHECK_EQ, v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::InstructionSelector::Emit(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::turboshaft::Operation::input_count, and v8::internal::compiler::OperandGenerator::UseRegister().
VisitRRO()
void v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitRRO (InstructionSelector * selector, OpIndex node, InstructionCode opcode)
Definition at line 2698 of file instruction-selector-x64.cc.
                                      {
  X64OperandGenerator g(selector);
  const Operation& op = selector->Get(node);
  DCHECK_EQ(op.input_count, 2);
  selector->Emit(opcode, g.DefineSameAsFirst(node), g.UseRegister(op.input(0)),
                 g.Use(op.input(1)));
}
References DCHECK_EQ, v8::internal::compiler::OperandGenerator::DefineSameAsFirst(), v8::internal::compiler::InstructionSelector::Emit(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::turboshaft::Operation::input_count, v8::internal::compiler::OperandGenerator::Use(), and v8::internal::compiler::OperandGenerator::UseRegister().
VisitStoreCommon()
void v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitStoreCommon (InstructionSelector * selector, const InstructionSelector::StoreView & store)
Definition at line 1418 of file instruction-selector-x64.cc.
                                                                 {
  X64OperandGenerator g(selector);
  OpIndex base = store.base();
  OptionalOpIndex index = store.index();
  OpIndex value = store.value();
  int32_t displacement = store.displacement();
  uint8_t element_size_log2 = store.element_size_log2();
  std::optional<AtomicMemoryOrder> atomic_order = store.memory_order();
  MemoryAccessKind acs_kind = store.access_kind();
  const StoreRepresentation store_rep = store.stored_rep();
  DCHECK_NE(store_rep.representation(), MachineRepresentation::kMapWord);
  WriteBarrierKind write_barrier_kind = store_rep.write_barrier_kind();
  const bool is_seqcst =
      atomic_order && *atomic_order == AtomicMemoryOrder::kSeqCst;
  if (v8_flags.enable_unconditional_write_barriers &&
      CanBeTaggedOrCompressedPointer(store_rep.representation())) {
    write_barrier_kind = kFullWriteBarrier;
  }
  const auto access_mode =
      acs_kind == MemoryAccessKind::kProtectedByTrapHandler
          ? (store.is_store_trap_on_null()
                 ? kMemoryAccessProtectedNullDereference
                 : MemoryAccessMode::kMemoryAccessProtectedMemOutOfBounds)
          : MemoryAccessMode::kMemoryAccessDirect;
  if (write_barrier_kind != kNoWriteBarrier &&
      !v8_flags.disable_write_barriers) {
    DCHECK(
        CanBeTaggedOrCompressedOrIndirectPointer(store_rep.representation()));
    // Uncompressed stores should not happen if we need a write barrier.
    CHECK((store.ts_stored_rep() !=
           MemoryRepresentation::AnyUncompressedTagged()) &&
          (store.ts_stored_rep() !=
           MemoryRepresentation::UncompressedTaggedPointer()) &&
          (store.ts_stored_rep() !=
           MemoryRepresentation::UncompressedTaggedPointer()));
    AddressingMode addressing_mode;
    InstructionOperand inputs[5];
    size_t input_count = 0;
    addressing_mode = g.GenerateMemoryOperandInputs(
        index, element_size_log2, base, displacement,
        DisplacementMode::kPositiveDisplacement, inputs, &input_count,
        X64OperandGenerator::RegisterUseKind::kUseUniqueRegister);
    DCHECK_LT(input_count, 4);
    inputs[input_count++] = g.UseUniqueRegister(value);
    RecordWriteMode record_write_mode =
        WriteBarrierKindToRecordWriteMode(write_barrier_kind);
    InstructionOperand temps[] = {g.TempRegister(), g.TempRegister()};
    InstructionCode code;
    if (store_rep.representation() == MachineRepresentation::kIndirectPointer) {
      DCHECK_EQ(write_barrier_kind, kIndirectPointerWriteBarrier);
      // In this case we need to add the IndirectPointerTag as additional input.
      code = kArchStoreIndirectWithWriteBarrier;
      IndirectPointerTag tag = store.indirect_pointer_tag();
      inputs[input_count++] = g.UseImmediate64(static_cast<int64_t>(tag));
    } else {
      code = is_seqcst ? kArchAtomicStoreWithWriteBarrier
                       : kArchStoreWithWriteBarrier;
    }
    code |= AddressingModeField::encode(addressing_mode);
    code |= RecordWriteModeField::encode(record_write_mode);
    code |= AccessModeField::encode(access_mode);
    selector->Emit(code, 0, nullptr, input_count, inputs, arraysize(temps),
                   temps);
  } else {
#ifdef V8_IS_TSAN
    // On TSAN builds we require two scratch registers. Because of this we also
    // have to modify the inputs to take into account possible aliasing and use
    // UseUniqueRegister which is not required for non-TSAN builds.
    InstructionOperand temps[] = {g.TempRegister(), g.TempRegister()};
    size_t temp_count = arraysize(temps);
    auto reg_kind = OperandGenerator::RegisterUseKind::kUseUniqueRegister;
#else
    InstructionOperand* temps = nullptr;
    size_t temp_count = 0;
    auto reg_kind = OperandGenerator::RegisterUseKind::kUseRegister;
#endif // V8_IS_TSAN
    // Release and non-atomic stores emit MOV and sequentially consistent stores
    // emit XCHG.
    // https://www.cl.cam.ac.uk/~pes20/cpp/cpp0xmappings.html
    ArchOpcode opcode;
    AddressingMode addressing_mode;
    InstructionOperand inputs[4];
    size_t input_count = 0;
    if (is_seqcst) {
      // SeqCst stores emit XCHG instead of MOV, so encode the inputs as we
      // would for XCHG. XCHG can't encode the value as an immediate and has
      // fewer addressing modes available.
      inputs[input_count++] = g.UseUniqueRegister(value);
      inputs[input_count++] = g.UseUniqueRegister(base);
      DCHECK_EQ(element_size_log2, 0);
      if (index.valid()) {
        DCHECK_EQ(displacement, 0);
        inputs[input_count++] =
            g.GetEffectiveIndexOperand(index.value(), &addressing_mode);
      } else if (displacement != 0) {
        DCHECK(ValueFitsIntoImmediate(displacement));
        inputs[input_count++] = g.UseImmediate(displacement);
        addressing_mode = kMode_MRI;
      } else {
        addressing_mode = kMode_MR;
      }
      opcode = GetSeqCstStoreOpcode(store_rep);
    } else {
      if (ElementSizeLog2Of(store_rep.representation()) <
          kSystemPointerSizeLog2) {
        if (V<Word64> value64;
            selector->MatchTruncateWord64ToWord32(value, &value64)) {
          value = value64;
        }
      }
      addressing_mode = g.GetEffectiveAddressMemoryOperand(
          store, inputs, &input_count, reg_kind);
      InstructionOperand value_operand = g.CanBeImmediate(value)
                                             ? g.UseImmediate(value)
                                             : g.UseRegister(value, reg_kind);
      inputs[input_count++] = value_operand;
        opcode = GetStoreOpcode(store.ts_stored_rep());
    }
    InstructionCode code = opcode
      | AddressingModeField::encode(addressing_mode)
      | AccessModeField::encode(access_mode);
    selector->Emit(code, 0, static_cast<InstructionOperand*>(nullptr),
                   input_count, inputs, temp_count, temps);
  }
}
References v8::internal::compiler::turboshaft::MemoryRepresentation::AnyUncompressedTagged(), arraysize, v8::internal::compiler::X64OperandGenerator::CanBeImmediate(), v8::internal::CanBeTaggedOrCompressedOrIndirectPointer(), v8::internal::CanBeTaggedOrCompressedPointer(), CHECK, code, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LT, DCHECK_NE, v8::internal::ElementSizeLog2Of(), v8::internal::compiler::InstructionSelector::Emit(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::X64OperandGenerator::GenerateMemoryOperandInputs(), v8::internal::compiler::X64OperandGenerator::GetEffectiveAddressMemoryOperand(), v8::internal::compiler::X64OperandGenerator::GetEffectiveIndexOperand(), GetSeqCstStoreOpcode(), GetStoreOpcode(), v8::internal::index, v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::kFullWriteBarrier, v8::internal::kIndirectPointer, v8::internal::compiler::kIndirectPointerWriteBarrier, v8::internal::kMapWord, v8::internal::compiler::kMemoryAccessDirect, v8::internal::compiler::kMemoryAccessProtectedMemOutOfBounds, v8::internal::compiler::kMemoryAccessProtectedNullDereference, v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kPositiveDisplacement, v8::internal::compiler::kProtectedByTrapHandler, v8::internal::kSeqCst, v8::internal::kSystemPointerSizeLog2, v8::internal::compiler::OperandGenerator::kUseRegister, v8::internal::compiler::OperandGenerator::kUseUniqueRegister, v8::internal::compiler::turboshaft::OperationMatcher::MatchTruncateWord64ToWord32(), v8::internal::compiler::StoreRepresentation::representation(), store(), v8::internal::compiler::OperandGenerator::TempRegister(), v8::internal::compiler::turboshaft::MemoryRepresentation::UncompressedTaggedPointer(), v8::internal::compiler::OperandGenerator::UseImmediate(), v8::internal::compiler::OperandGenerator::UseImmediate64(), v8::internal::compiler::OperandGenerator::UseRegister(), v8::internal::compiler::OperandGenerator::UseUniqueRegister(), v8::internal::v8_flags, v8::internal::value, v8::internal::compiler::ValueFitsIntoImmediate(), v8::internal::compiler::StoreRepresentation::write_barrier_kind(), and v8::internal::compiler::WriteBarrierKindToRecordWriteMode().
VisitWord32EqualImpl()
void v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWord32EqualImpl (InstructionSelector * selector, OpIndex node, FlagsContinuation * cont)
Definition at line 3505 of file instruction-selector-x64.cc.
                                                   {
  if (COMPRESS_POINTERS_BOOL && selector->isolate()) {
    X64OperandGenerator g(selector);
    const RootsTable& roots_table = selector->isolate()->roots_table();
    RootIndex root_index;
    OpIndex left;
    Handle<HeapObject> right;
    // HeapConstants and CompressedHeapConstants can be treated the same when
    // using them as an input to a 32-bit comparison. Check whether either is
    // present.
    if (MatchHeapObjectEqual(selector, node, &left, &right)) {
      if (roots_table.IsRootHandle(right, &root_index)) {
        DCHECK(left.valid());
        if (RootsTable::IsReadOnly(root_index) &&
            (V8_STATIC_ROOTS_BOOL || !selector->isolate()->bootstrapper())) {
          return VisitCompare(
              selector, kX64Cmp32, g.UseRegister(left),
              g.TempImmediate(MacroAssemblerBase::ReadOnlyRootPtr(
                  root_index, selector->isolate())),
              cont);
        }
        if (selector->CanUseRootsRegister()) {
          InstructionCode opcode =
              kX64Cmp32 | AddressingModeField::encode(kMode_Root);
          return VisitCompare(
              selector, opcode,
              g.TempImmediate(
                  MacroAssemblerBase::RootRegisterOffsetForRootIndex(
                      root_index)),
              g.UseRegister(left), cont);
        }
      }
    }
  }
  VisitWordCompare(selector, node, kX64Cmp32, cont);
}
References v8::internal::Isolate::bootstrapper(), v8::internal::compiler::InstructionSelector::CanUseRootsRegister(), COMPRESS_POINTERS_BOOL, v8::internal::DCHECK(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::InstructionSelector::isolate(), v8::internal::RootsTable::IsReadOnly(), v8::internal::RootsTable::IsRootHandle(), MatchHeapObjectEqual(), v8::internal::MacroAssemblerBase::ReadOnlyRootPtr(), v8::internal::MacroAssemblerBase::RootRegisterOffsetForRootIndex(), v8::internal::Isolate::roots_table(), v8::internal::compiler::OperandGenerator::TempImmediate(), v8::internal::compiler::OperandGenerator::UseRegister(), V8_STATIC_ROOTS_BOOL, v8::internal::compiler::turboshaft::OpIndex::valid(), v8::internal::compiler::VisitCompare(), and v8::internal::compiler::VisitWordCompare().
VisitWord32Shift()
void v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWord32Shift (InstructionSelector * selector, OpIndex node, ArchOpcode opcode)
Definition at line 1825 of file instruction-selector-x64.cc.
                                         {
  X64OperandGenerator g(selector);
  const ShiftOp& op = selector->Cast<ShiftOp>(node);
  DCHECK_EQ(op.input_count, 2);
  auto left = op.left();
  auto right = op.right();
  if (V<Word64> left64; selector->MatchTruncateWord64ToWord32(left, &left64)) {
    left = left64;
  }
  if (g.CanBeImmediate(right)) {
    selector->Emit(opcode, g.DefineSameAsFirst(node), g.UseRegister(left),
                   g.UseImmediate(right));
  } else {
    selector->Emit(opcode, g.DefineSameAsFirst(node), g.UseRegister(left),
                   g.UseFixed(right, rcx));
  }
}
References v8::internal::compiler::X64OperandGenerator::CanBeImmediate(), v8::internal::compiler::turboshaft::OperationMatcher::Cast(), DCHECK_EQ, v8::internal::compiler::OperandGenerator::DefineSameAsFirst(), v8::internal::compiler::InstructionSelector::Emit(), v8::internal::compiler::turboshaft::FixedArityOperationT< InputCount, Derived >::input_count, v8::internal::compiler::turboshaft::OperationMatcher::MatchTruncateWord64ToWord32(), v8::internal::compiler::turboshaft::ShiftOp::right(), v8::internal::compiler::OperandGenerator::UseFixed(), v8::internal::compiler::OperandGenerator::UseImmediate(), and v8::internal::compiler::OperandGenerator::UseRegister().
VisitWord64EqualImpl()
void v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWord64EqualImpl (InstructionSelector * selector, OpIndex node, FlagsContinuation * cont)
Definition at line 3468 of file instruction-selector-x64.cc.
                                                   {
  if (selector->CanUseRootsRegister()) {
    X64OperandGenerator g(selector);
    const RootsTable& roots_table = selector->isolate()->roots_table();
    RootIndex root_index;
    const ComparisonOp& equal =
        selector->Get(node).template Cast<ComparisonOp>();
    DCHECK_EQ(equal.kind, ComparisonOp::Kind::kEqual);
    Handle<HeapObject> object;
    if (equal.rep == RegisterRepresentation::Tagged() &&
        selector->MatchHeapConstant(equal.right(), &object)) {
      if (roots_table.IsRootHandle(object, &root_index)) {
        InstructionCode opcode =
            kX64Cmp | AddressingModeField::encode(kMode_Root);
        return VisitCompare(
            selector, opcode,
            g.TempImmediate(
                MacroAssemblerBase::RootRegisterOffsetForRootIndex(root_index)),
            g.UseRegister(equal.left()), cont);
      }
    }
  }
  VisitWordCompare(selector, node, kX64Cmp, cont);
}
References v8::internal::compiler::InstructionSelector::CanUseRootsRegister(), DCHECK_EQ, v8::base::BitField< T, shift, size, U >::encode(), v8::internal::equal, v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::InstructionSelector::isolate(), v8::internal::RootsTable::IsRootHandle(), v8::internal::compiler::turboshaft::ComparisonOp::kEqual, v8::internal::compiler::turboshaft::OperationMatcher::MatchHeapConstant(), v8::internal::MacroAssemblerBase::RootRegisterOffsetForRootIndex(), v8::internal::Isolate::roots_table(), v8::internal::compiler::turboshaft::RegisterRepresentation::Tagged(), v8::internal::compiler::OperandGenerator::TempImmediate(), v8::internal::compiler::OperandGenerator::UseRegister(), v8::internal::compiler::VisitCompare(), and v8::internal::compiler::VisitWordCompare().
VisitWord64Shift()
void v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWord64Shift (InstructionSelector * selector, OpIndex node, ArchOpcode opcode)
Definition at line 1848 of file instruction-selector-x64.cc.
                                         {
  X64OperandGenerator g(selector);
  const ShiftOp& op = selector->Cast<ShiftOp>(node);
  DCHECK_EQ(op.input_count, 2);
  auto left = op.left();
  auto right = op.right();
  if (g.CanBeImmediate(right)) {
      // TODO(nicohartmann@): Implement this for Turboshaft.
#if 0
      Int64BinopMatcher m(node);
      if (opcode == kX64Shr && m.left().IsChangeUint32ToUint64() &&
          m.right().HasResolvedValue() && m.right().ResolvedValue() < 32 &&
          m.right().ResolvedValue() >= 0) {
        opcode = kX64Shr32;
        left = left->InputAt(0);
      }
#endif
      selector->Emit(opcode, g.DefineSameAsFirst(node), g.UseRegister(left),
                     g.UseImmediate(right));
  } else {
    // TODO(nicohartmann@): Implement this for Turboshaft.
#if 0
      Int64BinopMatcher m(node);
      if (m.right().IsWord64And()) {
        Int64BinopMatcher mright(right);
        if (mright.right().Is(0x3F)) {
          right = mright.left().node();
        }
      }
#endif
    selector->Emit(opcode, g.DefineSameAsFirst(node), g.UseRegister(left),
                   g.UseFixed(right, rcx));
  }
}
References v8::internal::compiler::X64OperandGenerator::CanBeImmediate(), v8::internal::compiler::turboshaft::OperationMatcher::Cast(), DCHECK_EQ, v8::internal::compiler::OperandGenerator::DefineSameAsFirst(), v8::internal::compiler::InstructionSelector::Emit(), v8::internal::compiler::turboshaft::FixedArityOperationT< InputCount, Derived >::input_count, v8::internal::compiler::BinopMatcher< Left, Right, rep >::left(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::right(), v8::internal::compiler::turboshaft::ShiftOp::right(), v8::internal::compiler::OperandGenerator::UseFixed(), v8::internal::compiler::OperandGenerator::UseImmediate(), and v8::internal::compiler::OperandGenerator::UseRegister().
VisitWordCompare()
void v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWordCompare (InstructionSelector * selector, OpIndex node, InstructionCode opcode, FlagsContinuation * cont)
Definition at line 3410 of file instruction-selector-x64.cc.
                                                                       {
  X64OperandGenerator g(selector);
  const Operation& op = selector->Get(node);
  DCHECK_EQ(op.input_count, 2);
  auto left = op.input(0);
  auto right = op.input(1);
  // The 32-bit comparisons automatically truncate Word64
  // values to Word32 range, no need to do that explicitly.
  if (opcode == kX64Cmp32 || opcode == kX64Test32) {
    if (V<Word64> left64;
        selector->MatchTruncateWord64ToWord32(left, &left64)) {
      left = left64;
    }
    if (V<Word64> right64;
        selector->MatchTruncateWord64ToWord32(right, &right64)) {
      right = right64;
    }
  }
  opcode = TryNarrowOpcodeSize(selector, opcode, left, right, cont);
  // If one of the two inputs is an immediate, make sure it's on the right, or
  // if one of the two inputs is a memory operand, make sure it's on the left.
  int effect_level = selector->GetEffectLevel(node, cont);
  if ((!g.CanBeImmediate(right) && g.CanBeImmediate(left)) ||
      (g.CanBeMemoryOperand(opcode, node, right, effect_level) &&
       !g.CanBeMemoryOperand(opcode, node, left, effect_level))) {
    if (!selector->IsCommutative(node)) cont->Commute();
    std::swap(left, right);
  }
  if (IsWordAnd(selector, left)) {
    left = RemoveUnnecessaryWordAnd(selector, opcode, left);
  }
  // Match immediates on right side of comparison.
  if (g.CanBeImmediate(right)) {
    if (g.CanBeMemoryOperand(opcode, node, left, effect_level)) {
      return VisitCompareWithMemoryOperand(selector, opcode, left,
                                           g.UseImmediate(right), cont);
    }
    return VisitCompare(selector, opcode, g.Use(left), g.UseImmediate(right),
                        cont);
  }
  // Match memory operands on left side of comparison.
  if (g.CanBeMemoryOperand(opcode, node, left, effect_level)) {
    return VisitCompareWithMemoryOperand(selector, opcode, left,
                                         g.UseRegister(right), cont);
  }
  return VisitCompare(selector, opcode, left, right, cont,
                      selector->IsCommutative(node));
}
References v8::internal::compiler::X64OperandGenerator::CanBeImmediate(), v8::internal::compiler::X64OperandGenerator::CanBeMemoryOperand(), v8::internal::compiler::FlagsContinuation::Commute(), DCHECK_EQ, v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::InstructionSelector::GetEffectLevel(), v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::turboshaft::Operation::input_count, v8::internal::compiler::InstructionSelector::IsCommutative(), IsWordAnd(), v8::internal::compiler::turboshaft::OperationMatcher::MatchTruncateWord64ToWord32(), RemoveUnnecessaryWordAnd(), TryNarrowOpcodeSize(), v8::internal::compiler::OperandGenerator::Use(), v8::internal::compiler::OperandGenerator::UseImmediate(), v8::internal::compiler::OperandGenerator::UseRegister(), v8::internal::compiler::VisitCompare(), and VisitCompareWithMemoryOperand().