v8::internal::anonymous_namespace{js-function.cc} Namespace Reference
Functions
V8_WARN_UNUSED_RESULT bool HighestTierOf (CodeKinds kinds, CodeKind *highest_tier)
constexpr TieringState TieringStateFor (CodeKind target_kind, ConcurrencyMode mode)
void SetInstancePrototype (Isolate *isolate, DirectHandle< JSFunction > function, DirectHandle< JSReceiver > value)
bool FastInitializeDerivedMap (Isolate *isolate, DirectHandle< JSFunction > new_target, DirectHandle< JSFunction > constructor, DirectHandle< Map > constructor_initial_map)
int TypedArrayElementsKindToConstructorIndex (ElementsKind elements_kind)
int TypedArrayElementsKindToRabGsabCtorIndex (ElementsKind elements_kind)
bool UseFastFunctionNameLookup (Isolate *isolate, Tagged< Map > map)
DirectHandle< String > NativeCodeFunctionSourceString (Isolate *isolate, DirectHandle< SharedFunctionInfo > shared_info)
Function Documentation
FastInitializeDerivedMap()
bool v8::internal::anonymous_namespace{js-function.cc}::FastInitializeDerivedMap (Isolate * isolate, DirectHandle< JSFunction > new_target, DirectHandle< JSFunction > constructor, DirectHandle< Map > constructor_initial_map)
Definition at line 1128 of file js-function.cc.
                                                                         {
  // Use the default intrinsic prototype instead.
  if (!new_target->has_prototype_slot()) return false;
  // Check that |function|'s initial map still in sync with the |constructor|,
  // otherwise we must create a new initial map for |function|.
  if (new_target->has_initial_map() &&
      new_target->initial_map()->GetConstructor() == *constructor) {
    DCHECK(IsJSReceiver(new_target->instance_prototype()));
    return true;
  }
  InstanceType instance_type = constructor_initial_map->instance_type();
  DCHECK(CanSubclassHaveInobjectProperties(instance_type));
  // Create a new map with the size and number of in-object properties
  // suggested by |function|.
  // Link initial map and constructor function if the new.target is actually a
  // subclass constructor.
  if (!IsDerivedConstructor(new_target->shared()->kind())) return false;
  int instance_size;
  int in_object_properties;
  int embedder_fields =
      JSObject::GetEmbedderFieldCount(*constructor_initial_map);
  // Constructor expects certain number of in-object properties to be in the
  // object. However, CalculateExpectedNofProperties() may return smaller value
  // if 1) the constructor is not in the prototype chain of new_target, or
  // 2) the prototype chain is modified during iteration, or 3) compilation
  // failure occur during prototype chain iteration.
  // So we take the maximum of two values.
  int expected_nof_properties = std::max(
      static_cast<int>(constructor->shared()->expected_nof_properties()),
      JSFunction::CalculateExpectedNofProperties(isolate, new_target));
  JSFunction::CalculateInstanceSizeHelper(
      instance_type, constructor_initial_map->has_prototype_slot(),
      embedder_fields, expected_nof_properties, &instance_size,
      &in_object_properties);
  int pre_allocated = constructor_initial_map->GetInObjectProperties() -
                      constructor_initial_map->UnusedPropertyFields();
  CHECK_LE(constructor_initial_map->UsedInstanceSize(), instance_size);
  int unused_property_fields = in_object_properties - pre_allocated;
  DirectHandle<Map> map =
      Map::CopyInitialMap(isolate, constructor_initial_map, instance_size,
                          in_object_properties, unused_property_fields);
  map->set_new_target_is_base(false);
  DirectHandle<JSPrototype> prototype(new_target->instance_prototype(),
                                      isolate);
  JSFunction::SetInitialMap(isolate, new_target, map, prototype, constructor);
  DCHECK(IsJSReceiver(new_target->instance_prototype()));
  map->set_construction_counter(Map::kNoSlackTracking);
  map->StartInobjectSlackTracking();
  return true;
}
References v8::internal::JSFunction::CalculateExpectedNofProperties(), v8::internal::JSFunction::CalculateInstanceSizeHelper(), CHECK_LE, v8::internal::Map::CopyInitialMap(), v8::internal::DCHECK(), v8::internal::JSObject::GetEmbedderFieldCount(), v8::internal::IsDerivedConstructor(), v8::internal::Map::kNoSlackTracking, v8::internal::prototype, and v8::internal::JSFunction::SetInitialMap().
Referenced by v8::internal::JSFunction::GetDerivedMap().
HighestTierOf()
V8_WARN_UNUSED_RESULT bool v8::internal::anonymous_namespace{js-function.cc}::HighestTierOf (CodeKinds kinds, CodeKind * highest_tier)
Definition at line 167 of file js-function.cc.
                                                                 {
  DCHECK_EQ((kinds & ~kJSFunctionCodeKindsMask), 0);
  // Higher tiers > lower tiers.
  static_assert(CodeKind::TURBOFAN_JS > CodeKind::INTERPRETED_FUNCTION);
  if (kinds == 0) return false;
  const int highest_tier_log2 =
      31 - base::bits::CountLeadingZeros(static_cast<uint32_t>(kinds));
  DCHECK(CodeKindIsJSFunction(static_cast<CodeKind>(highest_tier_log2)));
  *highest_tier = static_cast<CodeKind>(highest_tier_log2);
  return true;
}
References v8::internal::CodeKindIsJSFunction(), v8::base::bits::CountLeadingZeros(), v8::internal::DCHECK(), DCHECK_EQ, and v8::internal::kJSFunctionCodeKindsMask.
Referenced by v8::internal::JSFunction::GetActiveTier().
NativeCodeFunctionSourceString()
DirectHandle<String> v8::internal::anonymous_namespace{js-function.cc}::NativeCodeFunctionSourceString (Isolate * isolate, DirectHandle< SharedFunctionInfo > shared_info)
Definition at line 1426 of file js-function.cc.
                                                                    {
  IncrementalStringBuilder builder(isolate);
  builder.AppendCStringLiteral("function ");
  builder.AppendString(direct_handle(shared_info->Name(), isolate));
  builder.AppendCStringLiteral("() { [native code] }");
  return builder.Finish().ToHandleChecked();
}
References v8::internal::IncrementalStringBuilder::AppendCStringLiteral(), v8::internal::IncrementalStringBuilder::AppendString(), v8::internal::direct_handle(), and v8::internal::IncrementalStringBuilder::Finish().
Referenced by v8::internal::JSFunction::ToString().
SetInstancePrototype()
void v8::internal::anonymous_namespace{js-function.cc}::SetInstancePrototype (Isolate * isolate, DirectHandle< JSFunction > function, DirectHandle< JSReceiver > value)
Definition at line 811 of file js-function.cc.
                                                          {
  // Now some logic for the maps of the objects that are created by using this
  // function as a constructor.
  if (function->has_initial_map()) {
    // If the function has allocated the initial map replace it with a
    // copy containing the new prototype. Also complete any in-object
    // slack tracking that is in progress at this point because it is
    // still tracking the old copy.
    function->CompleteInobjectSlackTrackingIfActive(isolate);
    DirectHandle<Map> initial_map(function->initial_map(), isolate);
    if (!isolate->bootstrapper()->IsActive() &&
        initial_map->instance_type() == JS_OBJECT_TYPE) {
      // Put the value in the initial map field until an initial map is needed.
      // At that point, a new initial map is created and the prototype is put
      // into the initial map where it belongs.
      function->set_prototype_or_initial_map(*value, kReleaseStore);
      if (IsJSObjectThatCanBeTrackedAsPrototype(*value)) {
        // Optimize as prototype to detach it from its transition tree.
        JSObject::OptimizeAsPrototype(Cast<JSObject>(value));
      }
    } else {
      DirectHandle<Map> new_map =
          Map::Copy(isolate, initial_map, "SetInstancePrototype");
      JSFunction::SetInitialMap(isolate, function, new_map, value);
      DCHECK_IMPLIES(!isolate->bootstrapper()->IsActive(),
                     *function != function->native_context()->array_function());
    }
    // Deoptimize all code that embeds the previous initial map.
    DependentCode::DeoptimizeDependencyGroups(
        isolate, *initial_map, DependentCode::kInitialMapChangedGroup);
  } else {
    // Put the value in the initial map field until an initial map is
    // needed. At that point, a new initial map is created and the
    // prototype is put into the initial map where it belongs.
    function->set_prototype_or_initial_map(*value, kReleaseStore);
    if (IsJSObjectThatCanBeTrackedAsPrototype(*value)) {
      // Optimize as prototype to detach it from its transition tree.
      JSObject::OptimizeAsPrototype(Cast<JSObject>(value));
    }
  }
}
References v8::internal::Isolate::bootstrapper(), v8::internal::Map::Copy(), DCHECK_IMPLIES, v8::internal::DependentCode::DeoptimizeDependencyGroups(), v8::internal::compiler::initial_map, v8::internal::Bootstrapper::IsActive(), v8::internal::IsJSObjectThatCanBeTrackedAsPrototype(), v8::internal::DependentCode::kInitialMapChangedGroup, v8::kReleaseStore, v8::internal::JSObject::OptimizeAsPrototype(), v8::internal::JSFunction::SetInitialMap(), and v8::internal::value.
Referenced by v8::internal::JSFunction::SetPrototype().
TieringStateFor()
constexpr TieringState v8::internal::anonymous_namespace{js-function.cc}::TieringStateFor (CodeKind target_kind, ConcurrencyMode mode) [constexpr]
Definition at line 249 of file js-function.cc.
                                                             {
  DCHECK(target_kind == CodeKind::MAGLEV ||
         target_kind == CodeKind::TURBOFAN_JS);
  return target_kind == CodeKind::MAGLEV
             ? (IsConcurrent(mode) ? TieringState::kRequestMaglev_Concurrent
                                   : TieringState::kRequestMaglev_Synchronous)
             : (IsConcurrent(mode)
                    ? TieringState::kRequestTurbofan_Concurrent
                    : TieringState::kRequestTurbofan_Synchronous);
}
References v8::internal::DCHECK(), v8::internal::IsConcurrent(), and mode().
Referenced by v8::internal::JSFunction::RequestOptimization().
TypedArrayElementsKindToConstructorIndex()
int v8::internal::anonymous_namespace{js-function.cc}::TypedArrayElementsKindToConstructorIndex (ElementsKind elements_kind)
Definition at line 1277 of file js-function.cc.
                                                                         {
  return Context::FIRST_FIXED_TYPED_ARRAY_FUN_INDEX + elements_kind -
         ElementsKind::FIRST_FIXED_TYPED_ARRAY_ELEMENTS_KIND;
}
References v8::internal::FIRST_FIXED_TYPED_ARRAY_ELEMENTS_KIND, and v8::internal::Context::FIRST_FIXED_TYPED_ARRAY_FUN_INDEX.
Referenced by v8::internal::JSFunction::GetDerivedRabGsabTypedArrayMap().
TypedArrayElementsKindToRabGsabCtorIndex()
int v8::internal::anonymous_namespace{js-function.cc}::TypedArrayElementsKindToRabGsabCtorIndex (ElementsKind elements_kind)
Definition at line 1282 of file js-function.cc.
                                                                         {
  return Context::FIRST_RAB_GSAB_TYPED_ARRAY_MAP_INDEX + elements_kind -
         ElementsKind::FIRST_FIXED_TYPED_ARRAY_ELEMENTS_KIND;
}
References v8::internal::FIRST_FIXED_TYPED_ARRAY_ELEMENTS_KIND, and v8::internal::Context::FIRST_RAB_GSAB_TYPED_ARRAY_MAP_INDEX.
Referenced by v8::internal::JSFunction::GetDerivedRabGsabTypedArrayMap().
UseFastFunctionNameLookup()
bool v8::internal::anonymous_namespace{js-function.cc}::UseFastFunctionNameLookup (Isolate * isolate, Tagged< Map > map)
Definition at line 1357 of file js-function.cc.
                                                                  {
  DCHECK(IsJSFunctionMap(map));
  if (map->NumberOfOwnDescriptors() <
      JSFunction::kMinDescriptorsForFastBindAndWrap) {
    return false;
  }
  DCHECK(!map->is_dictionary_map());
  Tagged<HeapObject> value;
  ReadOnlyRoots roots(isolate);
  auto descriptors = map->instance_descriptors(isolate);
  InternalIndex kNameIndex{JSFunction::kNameDescriptorIndex};
  if (descriptors->GetKey(kNameIndex) != roots.name_string() ||
      !descriptors->GetValue(kNameIndex)
           .GetHeapObjectIfStrong(isolate, &value)) {
    return false;
  }
  return IsAccessorInfo(value);
}
References v8::internal::DCHECK(), v8::internal::JSFunction::kMinDescriptorsForFastBindAndWrap, and v8::internal::value.
Referenced by v8::internal::JSFunction::GetDebugName().