v8::internal::anonymous_namespace{deserializer.cc} Namespace Reference
Functions
template<typename IsolateT >
uint32_t ComputeRawHashField (IsolateT *isolate, Tagged< String > string)
void NoExternalReferencesCallback ()
void PostProcessExternalString (Tagged< ExternalString > string, Isolate *isolate)
AllocationType SpaceToAllocation (SnapshotSpace space)
template<int byte_code_count, int expected>
constexpr uint8_t VerifyBytecodeCount (uint8_t bytecode)
const char * SnapshotSpaceName (SnapshotSpace space)
Function Documentation
ComputeRawHashField()
template<typename IsolateT >
uint32_t v8::internal::anonymous_namespace{deserializer.cc}::ComputeRawHashField (IsolateT * isolate, Tagged< String > string)
Definition at line 445 of file deserializer.cc.
                                                                       {
  // Make sure raw_hash_field() is computed.
  string->EnsureHash(SharedStringAccessGuardIfNeeded(isolate));
  return string->raw_hash_field();
}
NoExternalReferencesCallback()
void v8::internal::anonymous_namespace{deserializer.cc}::NoExternalReferencesCallback ()
Definition at line 487 of file deserializer.cc.
                                    {
  // The following check will trigger if a function or object template
  // with references to native functions have been deserialized from
  // snapshot, but no actual external references were provided when the
  // isolate was created.
  FATAL("No external references provided via API");
}
References FATAL.
Referenced by v8::internal::Deserializer< IsolateT >::ReadApiReference().
PostProcessExternalString()
void v8::internal::anonymous_namespace{deserializer.cc}::PostProcessExternalString (Tagged< ExternalString > string, Isolate * isolate)
Definition at line 495 of file deserializer.cc.
                                                 {
  DisallowGarbageCollection no_gc;
  uint32_t index = string->GetResourceRefForDeserialization();
  Address address =
      static_cast<Address>(isolate->api_external_references()[index]);
  string->InitExternalPointerFields(isolate);
  string->set_address_as_resource(isolate, address);
  isolate->heap()->UpdateExternalString(string, 0,
                                        string->ExternalPayloadSize());
  isolate->heap()->RegisterExternalString(string);
}
References v8::internal::Isolate::heap(), v8::internal::index, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Heap::RegisterExternalString(), v8::internal::string, and v8::internal::Heap::UpdateExternalString().
Referenced by v8::internal::Deserializer< IsolateT >::PostProcessNewObject().
SnapshotSpaceName()
const char* v8::internal::anonymous_namespace{deserializer.cc}::SnapshotSpaceName (SnapshotSpace space)
Definition at line 1079 of file deserializer.cc.
                                                   {
  switch (space) {
    case SnapshotSpace::kReadOnlyHeap:
      return "ReadOnlyHeap";
    case SnapshotSpace::kOld:
      return "Old";
    case SnapshotSpace::kCode:
      return "Code";
    case SnapshotSpace::kTrusted:
      return "Trusted";
  }
  return "(!unknown space!)";
}
References space.
Referenced by v8::internal::Deserializer< IsolateT >::ReadNewMetaMap(), and v8::internal::Deserializer< IsolateT >::ReadNewObject().
SpaceToAllocation()
AllocationType v8::internal::anonymous_namespace{deserializer.cc}::SpaceToAllocation (SnapshotSpace space)
Definition at line 744 of file deserializer.cc.
                                                      {
  switch (space) {
    case SnapshotSpace::kCode:
      return AllocationType::kCode;
    case SnapshotSpace::kOld:
      return AllocationType::kOld;
    case SnapshotSpace::kReadOnlyHeap:
      return AllocationType::kReadOnly;
    case SnapshotSpace::kTrusted:
      return AllocationType::kTrusted;
  }
}
References space.
Referenced by v8::internal::Deserializer< IsolateT >::ReadMetaMap(), and v8::internal::Deserializer< IsolateT >::ReadObject().
VerifyBytecodeCount()
template<int byte_code_count, int expected>
constexpr uint8_t v8::internal::anonymous_namespace{deserializer.cc}::VerifyBytecodeCount (uint8_t bytecode) [constexpr]
Definition at line 937 of file deserializer.cc.
                                                        {
  static_assert(byte_code_count == expected);
  return bytecode;
}