v8::internal::temporal::anonymous_namespace{js-temporal-helpers.cc} Namespace Reference
Functions
bool IsIntegralNumber (Isolate *isolate, DirectHandle< Object > argument)
Maybe< double > ToIntegerWithoutRounding (Isolate *isolate, DirectHandle< Object > argument)
Maybe< bool > IterateDurationRecordFieldsTable (Isolate *isolate, DirectHandle< JSReceiver > temporal_duration_like, Maybe< bool >(*RowFunction)(Isolate *, DirectHandle< JSReceiver > temporal_duration_like, DirectHandle< String >, double *), DurationRecord *record)
Function Documentation
IsIntegralNumber()
bool v8::internal::temporal::anonymous_namespace{js-temporal-helpers.cc}::IsIntegralNumber (Isolate * isolate, DirectHandle< Object > argument)
Definition at line 14 of file js-temporal-helpers.cc.
                                                                       {
  // 1. If Type(argument) is not Number, return false.
  if (!IsNumber(*argument)) return false;
  // 2. If argument is NaN, +∞𝔽, or -∞𝔽, return false.
  double number = Object::NumberValue(Cast<Number>(*argument));
  if (!std::isfinite(number)) return false;
  // 3. If floor(abs(ℝ(argument))) ≠ abs(ℝ(argument)), return false.
  if (std::floor(std::abs(number)) != std::abs(number)) return false;
  // 4. Return true.
  return true;
}
References v8::internal::IsNumber(), and v8::internal::Object::NumberValue().
Referenced by ToIntegerWithoutRounding().
IterateDurationRecordFieldsTable()
Maybe<bool> v8::internal::temporal::anonymous_namespace{js-temporal-helpers.cc}::IterateDurationRecordFieldsTable (Isolate * isolate, DirectHandle< JSReceiver > temporal_duration_like, Maybe< bool >(*)(Isolate *, DirectHandle< JSReceiver > temporal_duration_like, DirectHandle< String >, double *) RowFunction, DurationRecord * record)
Definition at line 51 of file js-temporal-helpers.cc.
                            {
  Factory* factory = isolate->factory();
  std::array<std::pair<DirectHandle<String>, double*>, 10> table8 = {
      {{factory->days_string(), &record->time_duration.days},
       {factory->hours_string(), &record->time_duration.hours},
       {factory->microseconds_string(), &record->time_duration.microseconds},
       {factory->milliseconds_string(), &record->time_duration.milliseconds},
       {factory->minutes_string(), &record->time_duration.minutes},
       {factory->months_string(), &record->months},
       {factory->nanoseconds_string(), &record->time_duration.nanoseconds},
       {factory->seconds_string(), &record->time_duration.seconds},
       {factory->weeks_string(), &record->weeks},
       {factory->years_string(), &record->years}}};
  // x. Let any be false.
  bool any = false;
  // x+1. For each row of Table 8, except the header row, in table order, do
  for (const auto& row : table8) {
    bool result;
    // row.first is prop: the Property Name value of the current row
    // row.second is the address of result's field whose name is the Field Name
    // value of the current row
    MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
        isolate, result,
        RowFunction(isolate, temporal_duration_like, row.first, row.second),
        Nothing<bool>());
    any |= result;
  }
  return Just(any);
}
References v8::internal::temporal::TimeDurationRecord::days, v8::internal::Isolate::factory(), v8::internal::temporal::TimeDurationRecord::hours, v8::Just(), MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::temporal::TimeDurationRecord::microseconds, v8::internal::temporal::TimeDurationRecord::milliseconds, v8::internal::temporal::TimeDurationRecord::minutes, v8::internal::temporal::DurationRecord::months, v8::internal::temporal::TimeDurationRecord::nanoseconds, v8::base::internal::result, v8::internal::temporal::TimeDurationRecord::seconds, v8::internal::temporal::DurationRecord::time_duration, v8::internal::temporal::DurationRecord::weeks, and v8::internal::temporal::DurationRecord::years.
Referenced by v8::internal::temporal::ToPartialDuration().
ToIntegerWithoutRounding()
Maybe<double> v8::internal::temporal::anonymous_namespace{js-temporal-helpers.cc}::ToIntegerWithoutRounding (Isolate * isolate, DirectHandle< Object > argument)
Definition at line 27 of file js-temporal-helpers.cc.
                                                                      {
  // 1. Let number be ? ToNumber(argument).
  DirectHandle<Number> number;
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, number, Object::ToNumber(isolate, argument), Nothing<double>());
  // 2. If number is NaN, +0𝔽, or −0𝔽 return 0.
  if (IsNaN(*number) || Object::NumberValue(*number) == 0) {
    return Just(static_cast<double>(0));
  }
  // 3. If IsIntegralNumber(number) is false, throw a RangeError exception.
  if (!IsIntegralNumber(isolate, number)) {
    THROW_NEW_ERROR_RETURN_VALUE(
        isolate, NEW_TEMPORAL_INVALID_ARG_RANGE_ERROR(), Nothing<double>());
  }
  // 4. Return ℝ(number).
  return Just(Object::NumberValue(*number));
}
References ASSIGN_RETURN_ON_EXCEPTION_VALUE, IsIntegralNumber(), v8::internal::IsNaN(), v8::Just(), NEW_TEMPORAL_INVALID_ARG_RANGE_ERROR, v8::internal::Object::NumberValue(), THROW_NEW_ERROR_RETURN_VALUE, and v8::Value::ToNumber().
Referenced by v8::internal::temporal::ToPartialDuration().