v8::internal::compiler::anonymous_namespace{load-elimination.cc} Namespace Reference
Functions
bool IsRename (Node *node)
Node * ResolveRenames (Node *node)
bool MayAlias (Node *a, Node *b)
bool MustAlias (Node *a, Node *b)
bool IsCompatible (MachineRepresentation r1, MachineRepresentation r2)
bool MayAlias (MaybeHandle< Name > x, MaybeHandle< Name > y)
Function Documentation
IsCompatible()
bool v8::internal::compiler::anonymous_namespace{load-elimination.cc}::IsCompatible (MachineRepresentation r1, MachineRepresentation r2)
Definition at line 145 of file load-elimination.cc.
                                                                      {
  if (r1 == r2) return true;
  return IsAnyTagged(r1) && IsAnyTagged(r2);
}
References v8::internal::IsAnyTagged().
Referenced by v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationChecker::CheckCallInputs(), v8::internal::compiler::CodeGenerator::MoveType::InferMove(), v8::internal::compiler::CodeGenerator::MoveType::InferSwap(), v8::internal::compiler::LoadElimination::AbstractElements::Lookup(), v8::internal::compiler::LoadElimination::ReduceLoadField(), and v8::internal::compiler::LoadElimination::ReduceStoreField().
IsRename()
bool v8::internal::compiler::anonymous_namespace{load-elimination.cc}::IsRename (Node * node)
Definition at line 23 of file load-elimination.cc.
                          {
  switch (node->opcode()) {
    case IrOpcode::kCheckHeapObject:
    case IrOpcode::kFinishRegion:
    case IrOpcode::kTypeGuard:
      return !node->IsDead();
    default:
      return false;
  }
}
References v8::internal::compiler::Node::IsDead(), and v8::internal::compiler::Node::opcode().
Referenced by MayAlias(), and ResolveRenames().
MayAlias() [1/2]
bool v8::internal::compiler::anonymous_namespace{load-elimination.cc}::MayAlias (MaybeHandle< Name > x, MaybeHandle< Name > y)
Definition at line 267 of file load-elimination.cc.
                                                        {
  if (!x.address()) return true;
  if (!y.address()) return true;
  if (x.address() != y.address()) return false;
  return true;
}
References v8::internal::MaybeHandle< T >::address(), and v8::internal::y.
Referenced by v8::internal::compiler::LoadElimination::AbstractField::Kill(), v8::internal::compiler::LoadElimination::AbstractElements::Kill(), MayAlias(), and v8::internal::compiler::LoadElimination::AliasStateInfo::MayAlias().
MayAlias() [2/2]
bool v8::internal::compiler::anonymous_namespace{load-elimination.cc}::MayAlias (Node * a, Node * b)
Definition at line 41 of file load-elimination.cc.
                                {
  if (a != b) {
    if (!NodeProperties::GetType(a).Maybe(NodeProperties::GetType(b))) {
      return false;
    } else if (IsRename(b)) {
      return MayAlias(a, b->InputAt(0));
    } else if (IsRename(a)) {
      return MayAlias(a->InputAt(0), b);
    } else if (b->opcode() == IrOpcode::kAllocate) {
      switch (a->opcode()) {
        case IrOpcode::kAllocate:
        case IrOpcode::kHeapConstant:
        case IrOpcode::kParameter:
          return false;
        default:
          break;
      }
    } else if (a->opcode() == IrOpcode::kAllocate) {
      switch (b->opcode()) {
        case IrOpcode::kHeapConstant:
        case IrOpcode::kParameter:
          return false;
        default:
          break;
      }
    }
  }
  return true;
}
References v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::Node::InputAt(), IsRename(), MayAlias(), and v8::internal::compiler::Node::opcode().
MustAlias()
bool v8::internal::compiler::anonymous_namespace{load-elimination.cc}::MustAlias (Node * a, Node * b)
Definition at line 71 of file load-elimination.cc.
                                 {
  return ResolveRenames(a) == ResolveRenames(b);
}
References ResolveRenames().
Referenced by v8::internal::compiler::LoadElimination::AbstractField::KillConst(), v8::internal::compiler::LoadElimination::AbstractField::Lookup(), and v8::internal::compiler::LoadElimination::AbstractElements::Lookup().
ResolveRenames()
Node* v8::internal::compiler::anonymous_namespace{load-elimination.cc}::ResolveRenames (Node * node)
Definition at line 34 of file load-elimination.cc.
                                 {
  while (IsRename(node)) {
    node = node->InputAt(0);
  }
  return node;
}
References v8::internal::compiler::Node::InputAt(), and IsRename().
Referenced by v8::internal::compiler::LoadElimination::AbstractMaps::AbstractMaps(), v8::internal::compiler::LoadElimination::AbstractMaps::Extend(), v8::internal::compiler::LoadElimination::AbstractMaps::Lookup(), and MustAlias().