v8::anonymous_namespace{wasm-js.cc} Namespace Reference
Namespaces
 anonymous_namespace{wasm-js.cc}
Functions
i::DirectHandle< i::String > v8_str (i::Isolate *isolate, const char *str)
Local< String > v8_str (Isolate *isolate, const char *str)
base::Vector< const uint8_t > GetFirstArgumentAsBytes (const v8::FunctionCallbackInfo< v8::Value > &info, size_t max_length, ErrorThrower *thrower, bool *is_shared)
base::OwnedVector< const uint8_t > GetAndCopyFirstArgumentAsBytes (const v8::FunctionCallbackInfo< v8::Value > &info, size_t max_length, ErrorThrower *thrower)
void WebAssemblyCompileImpl (const v8::FunctionCallbackInfo< v8::Value > &info)
void WasmStreamingCallbackForTesting (const v8::FunctionCallbackInfo< v8::Value > &info)
void WasmStreamingPromiseFailedCallback (const v8::FunctionCallbackInfo< v8::Value > &info)
void StartAsyncCompilationWithResolver (WasmJSApiScope &js_api_scope, Local< Value > response_or_promise, Local< Value > options_arg_value, std::shared_ptr< i::wasm::CompilationResultResolver > resolver)
void WebAssemblyCompileStreaming (const v8::FunctionCallbackInfo< v8::Value > &info)
void WebAssemblyValidateImpl (const v8::FunctionCallbackInfo< v8::Value > &info)
void WebAssemblyModuleImpl (const v8::FunctionCallbackInfo< v8::Value > &info)
void WebAssemblyModuleImportsImpl (const v8::FunctionCallbackInfo< v8::Value > &info)
void WebAssemblyModuleExportsImpl (const v8::FunctionCallbackInfo< v8::Value > &info)
void WebAssemblyModuleCustomSectionsImpl (const v8::FunctionCallbackInfo< v8::Value > &info)
void WebAssemblyInstanceImpl (const v8::FunctionCallbackInfo< v8::Value > &info)
void WebAssemblyInstantiateStreaming (const v8::FunctionCallbackInfo< v8::Value > &info)
void WebAssemblyInstantiateImpl (const v8::FunctionCallbackInfo< v8::Value > &info)
void WebAssemblyTableImpl (const v8::FunctionCallbackInfo< v8::Value > &info)
void WebAssemblyMemoryImpl (const v8::FunctionCallbackInfo< v8::Value > &info)
void WebAssemblyMemoryMapDescriptorImpl (const v8::FunctionCallbackInfo< v8::Value > &info)
std::optional< i::wasm::ValueType > GetValueType (Isolate *isolate, MaybeLocal< Value > maybe, Local< Context > context, WasmEnabledFeatures enabled_features)
void WebAssemblyGlobalImpl (const v8::FunctionCallbackInfo< v8::Value > &info)
void WebAssemblyTagImpl (const v8::FunctionCallbackInfo< v8::Value > &info)
void WebAssemblyExceptionImpl (const v8::FunctionCallbackInfo< v8::Value > &info)
i::DirectHandle< i::JSFunction > NewPromisingWasmExportedFunction (i::Isolate *i_isolate, i::DirectHandle< i::WasmExportedFunctionData > data, ErrorThrower &thrower)
void WebAssemblyFunction (const v8::FunctionCallbackInfo< v8::Value > &info)
void WebAssemblyPromising (const v8::FunctionCallbackInfo< v8::Value > &info)
void WebAssemblySuspendingImpl (const v8::FunctionCallbackInfo< v8::Value > &info)
void WebAssemblyDescriptorOptionsImpl (const FunctionCallbackInfo< v8::Value > &info)
void WebAssemblyFunctionType (const v8::FunctionCallbackInfo< v8::Value > &info)
void WebAssemblyInstanceGetExportsImpl (const v8::FunctionCallbackInfo< v8::Value > &info)
void WebAssemblyTableGetLengthImpl (const v8::FunctionCallbackInfo< v8::Value > &info)
void WebAssemblyTableGrowImpl (const v8::FunctionCallbackInfo< v8::Value > &info)
void WebAssemblyTableGetImpl (const v8::FunctionCallbackInfo< v8::Value > &info)
void WebAssemblyTableSetImpl (const v8::FunctionCallbackInfo< v8::Value > &info)
void WebAssemblyTableType (const v8::FunctionCallbackInfo< v8::Value > &info)
void WebAssemblyMemoryMapDescriptorMapImpl (const v8::FunctionCallbackInfo< v8::Value > &info)
void WebAssemblyMemoryMapDescriptorUnmapImpl (const v8::FunctionCallbackInfo< v8::Value > &info)
void WebAssemblyMemoryGrowImpl (const v8::FunctionCallbackInfo< v8::Value > &info)
void WebAssemblyMemoryGetBufferImpl (const v8::FunctionCallbackInfo< v8::Value > &info)
void WebAssemblyMemoryToFixedLengthBufferImpl (const v8::FunctionCallbackInfo< v8::Value > &info)
void WebAssemblyMemoryToResizableBufferImpl (const v8::FunctionCallbackInfo< v8::Value > &info)
void WebAssemblyMemoryType (const v8::FunctionCallbackInfo< v8::Value > &info)
void WebAssemblyTagType (const v8::FunctionCallbackInfo< v8::Value > &info)
void WebAssemblyExceptionGetArgImpl (const v8::FunctionCallbackInfo< v8::Value > &info)
void WebAssemblyExceptionIsImpl (const v8::FunctionCallbackInfo< v8::Value > &info)
void WebAssemblyGlobalGetValueCommon (WasmJSApiScope &js_api_scope)
void WebAssemblyGlobalValueOfImpl (const v8::FunctionCallbackInfo< v8::Value > &info)
void WebAssemblyGlobalGetValueImpl (const v8::FunctionCallbackInfo< v8::Value > &info)
void WebAssemblyGlobalSetValueImpl (const v8::FunctionCallbackInfo< v8::Value > &info)
void WebAssemblyGlobalType (const v8::FunctionCallbackInfo< v8::Value > &info)
Variables
constexpr const char * kName_WasmGlobalObject = `WebAssembly.Global`
constexpr const char * kName_WasmMemoryObject = `WebAssembly.Memory`
constexpr const char * kName_WasmMemoryMapDescriptor
constexpr const char * kName_WasmInstanceObject = `WebAssembly.Instance`
constexpr const char * kName_WasmTableObject = `WebAssembly.Table`
constexpr const char * kName_WasmTagObject = `WebAssembly.Tag`
constexpr const char * kName_WasmExceptionPackage = `WebAssembly.Exception`
Function Documentation
GetAndCopyFirstArgumentAsBytes()
base::OwnedVector<const uint8_t> v8::anonymous_namespace{wasm-js.cc}::GetAndCopyFirstArgumentAsBytes (const v8::FunctionCallbackInfo< v8::Value > & info, size_t max_length, ErrorThrower * thrower)
Definition at line 243 of file wasm-js.cc.
                           {
  bool is_shared = false;
  base::Vector<const uint8_t> bytes =
      GetFirstArgumentAsBytes(info, max_length, thrower, &is_shared);
  if (bytes.empty()) {
    return {};
  }
  // Use relaxed reads (and writes, which is unnecessary here) to avoid TSan
  // reports in case the buffer is shared and is being modified concurrently.
  auto result = base::OwnedVector<uint8_t>::NewForOverwrite(bytes.size());
  base::Relaxed_Memcpy(reinterpret_cast<base::Atomic8*>(result.begin()),
                       reinterpret_cast<const base::Atomic8*>(bytes.data()),
                       bytes.size());
  return result;
}
References v8::base::Vector< T >::data(), v8::base::Vector< T >::empty(), GetFirstArgumentAsBytes(), v8::internal::is_shared, v8::base::OwnedVector< T >::NewForOverwrite(), v8::base::Relaxed_Memcpy(), v8::base::internal::result, and v8::base::Vector< T >::size().
Referenced by WasmStreamingCallbackForTesting(), WebAssemblyCompileImpl(), WebAssemblyInstantiateImpl(), and WebAssemblyModuleImpl().
GetFirstArgumentAsBytes()
base::Vector<const uint8_t> v8::anonymous_namespace{wasm-js.cc}::GetFirstArgumentAsBytes (const v8::FunctionCallbackInfo< v8::Value > & info, size_t max_length, ErrorThrower * thrower, bool * is_shared)
Definition at line 198 of file wasm-js.cc.
                                            {
  const uint8_t* start = nullptr;
  size_t length = 0;
  v8::Local<v8::Value> source = info[0];
  if (source->IsArrayBuffer()) {
    // A raw array buffer was passed.
    Local<ArrayBuffer> buffer = Local<ArrayBuffer>::Cast(source);
    auto backing_store = buffer->GetBackingStore();
    start = reinterpret_cast<const uint8_t*>(backing_store->Data());
    length = backing_store->ByteLength();
    *is_shared = buffer->IsSharedArrayBuffer();
  } else if (source->IsTypedArray()) {
    // A TypedArray was passed.
    Local<TypedArray> array = Local<TypedArray>::Cast(source);
    Local<ArrayBuffer> buffer = array->Buffer();
    auto backing_store = buffer->GetBackingStore();
    start = reinterpret_cast<const uint8_t*>(backing_store->Data()) +
            array->ByteOffset();
    length = array->ByteLength();
    *is_shared = buffer->IsSharedArrayBuffer();
  } else {
    thrower->TypeError("Argument 0 must be a buffer source");
    return {};
  }
  DCHECK_IMPLIES(length, start != nullptr);
  if (length == 0) {
    thrower->CompileError("BufferSource argument is empty");
    return {};
  }
  if (length > max_length) {
    // The spec requires a CompileError for implementation-defined limits, see
    // https://webassembly.github.io/spec/js-api/index.html#limits.
    thrower->CompileError("buffer source exceeds maximum size of %zu (is %zu)",
                          max_length, length);
    return {};
  }
  return base::VectorOf(start, length);
}
References v8::Local< T >::Cast(), DCHECK_IMPLIES, v8::internal::is_shared, v8::Value::IsArrayBuffer(), v8::Value::IsTypedArray(), v8::internal::length, and v8::base::VectorOf().
Referenced by GetAndCopyFirstArgumentAsBytes(), and WebAssemblyValidateImpl().
GetValueType()
std::optional<i::wasm::ValueType> v8::anonymous_namespace{wasm-js.cc}::GetValueType (Isolate * isolate, MaybeLocal< Value > maybe, Local< Context > context, WasmEnabledFeatures enabled_features)
Definition at line 1713 of file wasm-js.cc.
                                          {
  v8::Local<v8::Value> value;
  if (!maybe.ToLocal(&value)) return std::nullopt;
  i::DirectHandle<i::String> string;
  if (!i::Object::ToString(reinterpret_cast<i::Isolate*>(isolate),
                           Utils::OpenDirectHandle(*value))
           .ToHandle(&string)) {
    return std::nullopt;
  }
  if (string->IsEqualTo(base::CStrVector("i32"))) {
    return i::wasm::kWasmI32;
  } else if (string->IsEqualTo(base::CStrVector("f32"))) {
    return i::wasm::kWasmF32;
  } else if (string->IsEqualTo(base::CStrVector("i64"))) {
    return i::wasm::kWasmI64;
  } else if (string->IsEqualTo(base::CStrVector("f64"))) {
    return i::wasm::kWasmF64;
  } else if (string->IsEqualTo(base::CStrVector("v128"))) {
    return i::wasm::kWasmS128;
  } else if (string->IsEqualTo(base::CStrVector("externref"))) {
    return i::wasm::kWasmExternRef;
  } else if (enabled_features.has_type_reflection() &&
             string->IsEqualTo(base::CStrVector("funcref"))) {
    // The type reflection proposal renames "anyfunc" to "funcref", and makes
    // "anyfunc" an alias of "funcref".
    return i::wasm::kWasmFuncRef;
  } else if (string->IsEqualTo(base::CStrVector("anyfunc"))) {
    // The JS api spec uses 'anyfunc' instead of 'funcref'.
    return i::wasm::kWasmFuncRef;
  } else if (string->IsEqualTo(base::CStrVector("eqref"))) {
    return i::wasm::kWasmEqRef;
  } else if (enabled_features.has_stringref() &&
             string->IsEqualTo(base::CStrVector("stringref"))) {
    return i::wasm::kWasmStringRef;
  } else if (string->IsEqualTo(base::CStrVector("anyref"))) {
    return i::wasm::kWasmAnyRef;
  } else if (string->IsEqualTo(base::CStrVector("structref"))) {
    return i::wasm::kWasmStructRef;
  } else if (string->IsEqualTo(base::CStrVector("arrayref"))) {
    return i::wasm::kWasmArrayRef;
  } else if (string->IsEqualTo(base::CStrVector("i31ref"))) {
    return i::wasm::kWasmI31Ref;
  } else if (enabled_features.has_exnref() &&
             string->IsEqualTo(base::CStrVector("exnref"))) {
    return i::wasm::kWasmExnRef;
  }
  // Unrecognized type.
  return i::wasm::kWasmVoid;
}
References v8::base::CStrVector(), v8::internal::wasm::kWasmAnyRef, v8::internal::wasm::kWasmArrayRef, v8::internal::wasm::kWasmEqRef, v8::internal::wasm::kWasmExnRef, v8::internal::wasm::kWasmExternRef, v8::internal::wasm::kWasmF32, v8::internal::wasm::kWasmF64, v8::internal::wasm::kWasmFuncRef, v8::internal::wasm::kWasmI31Ref, v8::internal::wasm::kWasmI32, v8::internal::wasm::kWasmI64, v8::internal::wasm::kWasmS128, v8::internal::wasm::kWasmStringRef, v8::internal::wasm::kWasmStructRef, v8::internal::wasm::kWasmVoid, v8::Utils::OpenDirectHandle(), v8::internal::string, v8::anonymous_namespace{api.cc}::ToHandle(), v8::MaybeLocal< T >::ToLocal(), ToString(), and v8::internal::value.
Referenced by WebAssemblyFunction(), WebAssemblyGlobalImpl(), and WebAssemblyTagImpl().
NewPromisingWasmExportedFunction()
i::DirectHandle<i::JSFunction> v8::anonymous_namespace{wasm-js.cc}::NewPromisingWasmExportedFunction (i::Isolate * i_isolate, i::DirectHandle< i::WasmExportedFunctionData > data, ErrorThrower & thrower)
Definition at line 2230 of file wasm-js.cc.
                           {
  i::DirectHandle<i::WasmTrustedInstanceData> trusted_instance_data{
      data->instance_data(), i_isolate};
  int func_index = data->function_index();
  const i::wasm::WasmModule* module = trusted_instance_data->module();
  i::wasm::ModuleTypeIndex sig_index = module->functions[func_index].sig_index;
  const i::wasm::CanonicalSig* sig =
      i::wasm::GetTypeCanonicalizer()->LookupFunctionSignature(
          module->canonical_sig_id(sig_index));
  i::DirectHandle<i::Code> wrapper;
  if (!internal::wasm::IsJSCompatibleSignature(sig)) {
    // If the signature is incompatible with JS, the original export will have
    // compiled an incompatible signature wrapper, so just reuse that.
    wrapper =
        i::DirectHandle<i::Code>(data->wrapper_code(i_isolate), i_isolate);
  } else {
    wrapper = BUILTIN_CODE(i_isolate, WasmPromising);
  }
  // TODO(14034): Create funcref RTTs lazily?
  i::DirectHandle<i::Map> rtt{
      i::Cast<i::Map>(
          trusted_instance_data->managed_object_maps()->get(sig_index.index)),
      i_isolate};
  int num_imported_functions = module->num_imported_functions;
  i::DirectHandle<i::TrustedObject> implicit_arg;
  constexpr bool kShared = false;
  if (func_index >= num_imported_functions) {
    implicit_arg = trusted_instance_data;
  } else {
    implicit_arg = i_isolate->factory()->NewWasmImportData(
        direct_handle(i::Cast<i::WasmImportData>(
                          trusted_instance_data->dispatch_table_for_imports()
                              ->implicit_arg(func_index)),
                      i_isolate),
        kShared);
  }
  i::DirectHandle<i::WasmInternalFunction> internal =
      i_isolate->factory()->NewWasmInternalFunction(
          implicit_arg, func_index, kShared,
          trusted_instance_data->GetCallTarget(func_index));
  i::DirectHandle<i::WasmFuncRef> func_ref =
      i_isolate->factory()->NewWasmFuncRef(internal, rtt, kShared);
  if (func_index < num_imported_functions) {
    i::Cast<i::WasmImportData>(implicit_arg)->set_call_origin(*internal);
  }
  i::DirectHandle<i::JSFunction> result = i::WasmExportedFunction::New(
      i_isolate, trusted_instance_data, func_ref, internal,
      static_cast<int>(data->sig()->parameter_count()), wrapper);
  return result;
}
References BUILTIN_CODE, v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::wasm::WasmModule::functions, v8::internal::wasm::GetTypeCanonicalizer(), v8::internal::wasm::IsJSCompatibleSignature(), v8::internal::wasm::TypeCanonicalizer::LookupFunctionSignature(), v8::internal::WasmExportedFunction::New(), v8::base::internal::result, and v8::internal::sig.
Referenced by WebAssemblyPromising().
StartAsyncCompilationWithResolver()
void v8::anonymous_namespace{wasm-js.cc}::StartAsyncCompilationWithResolver (WasmJSApiScope & js_api_scope, Local< Value > response_or_promise, Local< Value > options_arg_value, std::shared_ptr< i::wasm::CompilationResultResolver > resolver)
Definition at line 786 of file wasm-js.cc.
                                                            {
  auto [isolate, i_isolate, thrower] = js_api_scope.isolates_and_thrower();
  Local<Context> context = isolate->GetCurrentContext();
  i::DirectHandle<i::NativeContext> native_context =
      Utils::OpenHandle(*context);
  if (!i::wasm::IsWasmCodegenAllowed(i_isolate, native_context)) {
    i::DirectHandle<i::String> error =
        i::wasm::ErrorStringForCodegen(i_isolate, native_context);
    thrower.CompileError("%s", error->ToCString().get());
    resolver->OnCompilationFailed(thrower.Reify());
    return;
  }
  auto enabled_features = WasmEnabledFeatures::FromIsolate(i_isolate);
  CompileTimeImports compile_imports =
      ArgumentToCompileOptions(options_arg_value, i_isolate, enabled_features);
  if (i_isolate->has_exception()) {
    if (i_isolate->is_execution_terminating()) return;
    i::DirectHandle<i::JSAny> exception(Cast<i::JSAny>(i_isolate->exception()),
                                        i_isolate);
    i_isolate->clear_exception();
    resolver->OnCompilationFailed(exception);
    return;
  }
  // Allocate the streaming decoder in a Managed so we can pass it to the
  // embedder.
  std::shared_ptr<WasmStreaming> streaming = std::make_shared<WasmStreaming>(
      std::make_unique<WasmStreaming::WasmStreamingImpl>(
          i_isolate, js_api_scope.api_name(), std::move(compile_imports),
          resolver));
  i::DirectHandle<i::Managed<WasmStreaming>> data =
      i::Managed<WasmStreaming>::From(i_isolate, 0, streaming);
  DCHECK_NOT_NULL(i_isolate->wasm_streaming_callback());
  Local<v8::Function> compile_callback, reject_callback;
  if (!v8::Function::New(context, i_isolate->wasm_streaming_callback(),
                         Utils::ToLocal(i::Cast<i::Object>(data)), 1)
           .ToLocal(&compile_callback) ||
      !v8::Function::New(context, WasmStreamingPromiseFailedCallback,
                         Utils::ToLocal(i::Cast<i::Object>(data)), 1)
           .ToLocal(&reject_callback)) {
    return js_api_scope.AssertException();
  }
  // The parameter may be of type {Response} or of type {Promise<Response>}.
  // Treat either case of parameter as Promise.resolve(parameter)
  // as per https://www.w3.org/2001/tag/doc/promises-guide#resolve-arguments
  // Ending with:
  // return Promise.resolve(parameter).then(compile_callback);
  Local<Promise::Resolver> input_resolver;
  if (!Promise::Resolver::New(context).ToLocal(&input_resolver) ||
      input_resolver->Resolve(context, response_or_promise).IsNothing()) {
    return js_api_scope.AssertException();
  }
  // Calling `then` on the promise can fail if the user monkey-patched stuff,
  // see https://crbug.com/374820218 / https://crbug.com/396461004.
  // If this does not fail, then the {compile_callback} will start streaming
  // compilation, which will eventually resolve the promise we set as result
  // value.
  if (input_resolver->GetPromise()
          ->Then(context, compile_callback, reject_callback)
          .IsEmpty()) {
    streaming->Abort(MaybeLocal<Value>{});
    return js_api_scope.AssertException();
  }
}
References v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::ArgumentToCompileOptions(), DCHECK_NOT_NULL, v8::internal::wasm::ErrorStringForCodegen(), v8::internal::Managed< CppType >::From(), v8::internal::wasm::IsWasmCodegenAllowed(), v8::internal::native_context, v8::Promise::Resolver::New(), v8::Function::New(), v8::Utils::OpenHandle(), and WasmStreamingPromiseFailedCallback().
Referenced by WebAssemblyCompileStreaming(), and WebAssemblyInstantiateStreaming().
v8_str() [1/2]
i::DirectHandle<i::String> v8::anonymous_namespace{wasm-js.cc}::v8_str (i::Isolate * isolate, const char * str)
Definition at line 174 of file wasm-js.cc.
                                                                  {
  return isolate->factory()->NewStringFromAsciiChecked(str);
}
References v8::internal::Isolate::factory(), and v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked().
Referenced by v8::anonymous_namespace{d8.cc}::ToSTLString(), and v8::anonymous_namespace{d8.cc}::TryGetValue().
v8_str() [2/2]
Local<String> v8::anonymous_namespace{wasm-js.cc}::v8_str (Isolate * isolate, const char * str)
Definition at line 177 of file wasm-js.cc.
                                                        {
  return Utils::ToLocal(v8_str(reinterpret_cast<i::Isolate*>(isolate), str));
}
Referenced by v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::GetAddressType(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::GetInitialOrMinimumProperty(), v8::internal::WasmJs::Install(), v8::internal::WasmJs::InstallCustomDescriptors(), v8::internal::anonymous_namespace{wasm-js.cc}::InstallFunc(), v8::internal::anonymous_namespace{wasm-js.cc}::InstallGetter(), v8::internal::anonymous_namespace{wasm-js.cc}::InstallGetterSetter(), v8::internal::WasmJs::InstallJSPromiseIntegration(), v8::internal::WasmJs::InstallModule(), v8::internal::WasmJs::InstallTypeReflection(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::InstantiateBytesResultResolver::OnInstantiationSucceeded(), v8::internal::WasmJs::PrepareForSnapshot(), v8::internal::anonymous_namespace{wasm-js.cc}::SetupConstructor(), WebAssemblyExceptionImpl(), WebAssemblyFunction(), WebAssemblyGlobalImpl(), WebAssemblyMemoryImpl(), WebAssemblyTableImpl(), and WebAssemblyTagImpl().
WasmStreamingCallbackForTesting()
void v8::anonymous_namespace{wasm-js.cc}::WasmStreamingCallbackForTesting (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 756 of file wasm-js.cc.
                                                 {
  WasmJSApiScope js_api_scope{info, "WebAssembly.compile()"};
  auto [isolate, i_isolate, thrower] = js_api_scope.isolates_and_thrower();
  std::shared_ptr<v8::WasmStreaming> streaming =
      v8::WasmStreaming::Unpack(info.GetIsolate(), info.Data());
  // We don't check the buffer length up front, to allow d8 to test that the
  // streaming decoder implementation handles overly large inputs correctly.
  size_t unlimited = std::numeric_limits<size_t>::max();
  base::OwnedVector<const uint8_t> bytes =
      GetAndCopyFirstArgumentAsBytes(info, unlimited, &thrower);
  if (bytes.empty()) {
    streaming->Abort(Utils::ToLocal(thrower.Reify()));
    return;
  }
  streaming->OnBytesReceived(bytes.begin(), bytes.size());
  streaming->Finish();
  CHECK(!thrower.error());
}
References v8::base::OwnedVector< T >::begin(), CHECK, v8::FunctionCallbackInfo< T >::Data(), v8::base::OwnedVector< T >::empty(), GetAndCopyFirstArgumentAsBytes(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::base::OwnedVector< T >::size(), and v8::WasmStreaming::Unpack().
Referenced by v8::internal::WasmJs::Install().
WasmStreamingPromiseFailedCallback()
void v8::anonymous_namespace{wasm-js.cc}::WasmStreamingPromiseFailedCallback (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 778 of file wasm-js.cc.
                                                 {
  DCHECK(i::ValidateCallbackInfo(info));
  std::shared_ptr<v8::WasmStreaming> streaming =
      v8::WasmStreaming::Unpack(info.GetIsolate(), info.Data());
  streaming->Abort(info[0]);
}
References v8::FunctionCallbackInfo< T >::Data(), DCHECK, v8::FunctionCallbackInfo< T >::GetIsolate(), v8::WasmStreaming::Unpack(), and v8::internal::ValidateCallbackInfo().
Referenced by StartAsyncCompilationWithResolver().
WebAssemblyCompileImpl()
void v8::anonymous_namespace{wasm-js.cc}::WebAssemblyCompileImpl (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 708 of file wasm-js.cc.
                                                                         {
  WasmJSApiScope js_api_scope{info, "WebAssembly.compile()"};
  auto [isolate, i_isolate, thrower] = js_api_scope.isolates_and_thrower();
  RecordCompilationMethod(i_isolate, kAsyncCompilation);
  Local<Context> context = isolate->GetCurrentContext();
  Local<Promise::Resolver> promise_resolver;
  if (!Promise::Resolver::New(context).ToLocal(&promise_resolver)) {
    return js_api_scope.AssertException();
  }
  Local<Promise> promise = promise_resolver->GetPromise();
  info.GetReturnValue().Set(promise);
  std::shared_ptr<i::wasm::CompilationResultResolver> resolver(
      new AsyncCompilationResolver(isolate, context, promise_resolver));
  i::DirectHandle<i::NativeContext> native_context =
      i_isolate->native_context();
  if (!i::wasm::IsWasmCodegenAllowed(i_isolate, native_context)) {
    i::DirectHandle<i::String> error =
        i::wasm::ErrorStringForCodegen(i_isolate, native_context);
    thrower.CompileError("%s", error->ToCString().get());
    resolver->OnCompilationFailed(thrower.Reify());
    return;
  }
  base::OwnedVector<const uint8_t> bytes = GetAndCopyFirstArgumentAsBytes(
      info, i::wasm::max_module_size(), &thrower);
  if (bytes.empty()) {
    resolver->OnCompilationFailed(thrower.Reify());
    return;
  }
  auto enabled_features = WasmEnabledFeatures::FromIsolate(i_isolate);
  CompileTimeImports compile_imports =
      ArgumentToCompileOptions(info[1], i_isolate, enabled_features);
  if (i_isolate->has_exception()) {
    if (i_isolate->is_execution_terminating()) return;
    i::DirectHandle<i::JSAny> exception(Cast<i::JSAny>(i_isolate->exception()),
                                        i_isolate);
    i_isolate->clear_exception();
    resolver->OnCompilationFailed(exception);
    return;
  }
  i::wasm::GetWasmEngine()->AsyncCompile(
      i_isolate, enabled_features, std::move(compile_imports),
      std::move(resolver), std::move(bytes), js_api_scope.api_name());
}
References v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::ArgumentToCompileOptions(), v8::internal::wasm::WasmEngine::AsyncCompile(), v8::base::OwnedVector< T >::empty(), v8::internal::wasm::ErrorStringForCodegen(), GetAndCopyFirstArgumentAsBytes(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::internal::wasm::GetWasmEngine(), v8::internal::wasm::IsWasmCodegenAllowed(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::kAsyncCompilation, v8::internal::wasm::max_module_size(), v8::internal::native_context, v8::Promise::Resolver::New(), and v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::RecordCompilationMethod().
WebAssemblyCompileStreaming()
void v8::anonymous_namespace{wasm-js.cc}::WebAssemblyCompileStreaming (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 863 of file wasm-js.cc.
                                                 {
  WasmJSApiScope js_api_scope{info, "WebAssembly.compileStreaming()"};
  auto [isolate, i_isolate, thrower] = js_api_scope.isolates_and_thrower();
  RecordCompilationMethod(i_isolate, kStreamingCompilation);
  Local<Context> context = isolate->GetCurrentContext();
  // Create and assign the return value of this function.
  Local<Promise::Resolver> promise_resolver;
  if (!Promise::Resolver::New(context).ToLocal(&promise_resolver)) {
    return js_api_scope.AssertException();
  }
  Local<Promise> promise = promise_resolver->GetPromise();
  info.GetReturnValue().Set(promise);
  // Prepare the CompilationResultResolver for the compilation.
  auto resolver = std::make_shared<AsyncCompilationResolver>(isolate, context,
                                                             promise_resolver);
  StartAsyncCompilationWithResolver(js_api_scope, info[0], info[1], resolver);
}
References v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::kStreamingCompilation, v8::Promise::Resolver::New(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::RecordCompilationMethod(), and StartAsyncCompilationWithResolver().
Referenced by v8::internal::WasmJs::Install().
WebAssemblyDescriptorOptionsImpl()
void v8::anonymous_namespace{wasm-js.cc}::WebAssemblyDescriptorOptionsImpl (const FunctionCallbackInfo< v8::Value > & info)
Definition at line 2461 of file wasm-js.cc.
                                               {
  WasmJSApiScope js_api_scope{info, "WebAssembly.DescriptorOptions()"};
  auto [isolate, i_isolate, thrower] = js_api_scope.isolates_and_thrower();
  if (!info.IsConstructCall()) {
    thrower.TypeError(
        "WebAssembly.DescriptorOptions must be invoked with 'new'");
    return;
  }
  if (!info[0]->IsObject()) {
    thrower.TypeError("Argument 0 must be an object");
    return;
  }
  i::DirectHandle<i::JSReceiver> options =
      Utils::OpenDirectHandle(*Local<v8::Object>::Cast(info[0]));
  i::DirectHandle<i::Object> prototype;
  if (!i::JSReceiver::GetProperty(i_isolate, options, "prototype")
           .ToHandle(&prototype)) {
    return js_api_scope.AssertException();
  }
  if (!i::IsJSReceiver(*prototype)) {
    thrower.TypeError("Prototype must be an object");
    return;
  }
  i::DirectHandle<i::WasmDescriptorOptions> result =
      i::WasmDescriptorOptions::New(i_isolate, prototype);
  info.GetReturnValue().Set(Utils::ToLocal(i::Cast<i::JSObject>(result)));
}
References v8::internal::JSReceiver::GetProperty(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::FunctionCallbackInfo< T >::IsConstructCall(), v8::internal::IsObject(), v8::internal::WasmDescriptorOptions::New(), v8::Utils::OpenDirectHandle(), v8::internal::prototype, v8::base::internal::result, and v8::anonymous_namespace{api.cc}::ToHandle().
Referenced by v8::internal::WasmJs::InstallCustomDescriptors().
WebAssemblyExceptionGetArgImpl()
void v8::anonymous_namespace{wasm-js.cc}::WebAssemblyExceptionGetArgImpl (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 2959 of file wasm-js.cc.
                                                 {
  WasmJSApiScope js_api_scope{info, "WebAssembly.Exception.getArg()"};
  auto [isolate, i_isolate, thrower] = js_api_scope.isolates_and_thrower();
  EXTRACT_THIS(exception, WasmExceptionPackage);
  i::DirectHandle<i::WasmTagObject> tag_object;
  if (!GetFirstArgumentAsTag(info, &thrower).ToHandle(&tag_object)) {
    return js_api_scope.AssertException();
  }
  Local<Context> context = isolate->GetCurrentContext();
  std::optional<uint32_t> maybe_index =
      EnforceUint32("Index", info[1], context, &thrower);
  if (!maybe_index) return js_api_scope.AssertException();
  uint32_t index = *maybe_index;
  auto maybe_values =
      i::WasmExceptionPackage::GetExceptionValues(i_isolate, exception);
  auto this_tag =
      i::WasmExceptionPackage::GetExceptionTag(i_isolate, exception);
  DCHECK(IsWasmExceptionTag(*this_tag));
  if (tag_object->tag() != *this_tag) {
    thrower.TypeError("First argument does not match the exception tag");
    return;
  }
  DCHECK(!IsUndefined(*maybe_values));
  auto values = i::Cast<i::FixedArray>(maybe_values);
  auto signature = tag_object->serialized_signature();
  if (index >= static_cast<uint32_t>(signature->length())) {
    thrower.RangeError("Index out of range");
    return;
  }
  // First, find the index in the values array.
  uint32_t decode_index = 0;
  // Since the bounds check above passed, the cast to int is safe.
  for (int i = 0; i < static_cast<int>(index); ++i) {
    switch (signature->get(i).kind()) {
      case i::wasm::kI32:
      case i::wasm::kF32:
        decode_index += 2;
        break;
      case i::wasm::kI64:
      case i::wasm::kF64:
        decode_index += 4;
        break;
      case i::wasm::kRef:
      case i::wasm::kRefNull:
        decode_index++;
        break;
      case i::wasm::kS128:
        decode_index += 8;
        break;
      case i::wasm::kI8:
      case i::wasm::kI16:
      case i::wasm::kF16:
      case i::wasm::kVoid:
      case i::wasm::kTop:
      case i::wasm::kBottom:
        UNREACHABLE();
    }
  }
  // Decode the value at {decode_index}.
  Local<Value> result;
  switch (signature->get(index).kind()) {
    case i::wasm::kI32: {
      uint32_t u32_bits = 0;
      i::DecodeI32ExceptionValue(values, &decode_index, &u32_bits);
      int32_t i32 = static_cast<int32_t>(u32_bits);
      result = v8::Integer::New(isolate, i32);
      break;
    }
    case i::wasm::kI64: {
      uint64_t u64_bits = 0;
      i::DecodeI64ExceptionValue(values, &decode_index, &u64_bits);
      int64_t i64 = static_cast<int64_t>(u64_bits);
      result = v8::BigInt::New(isolate, i64);
      break;
    }
    case i::wasm::kF32: {
      uint32_t f32_bits = 0;
      DecodeI32ExceptionValue(values, &decode_index, &f32_bits);
      float f32 = base::bit_cast<float>(f32_bits);
      result = v8::Number::New(isolate, f32);
      break;
    }
    case i::wasm::kF64: {
      uint64_t f64_bits = 0;
      DecodeI64ExceptionValue(values, &decode_index, &f64_bits);
      double f64 = base::bit_cast<double>(f64_bits);
      result = v8::Number::New(isolate, f64);
      break;
    }
    case i::wasm::kRef:
    case i::wasm::kRefNull: {
      i::DirectHandle<i::Object> obj(values->get(decode_index), i_isolate);
      ReturnValue<Value> return_value = info.GetReturnValue();
      if (!WasmObjectToJSReturnValue(return_value, obj, signature->get(index),
                                     i_isolate, &thrower)) {
        return js_api_scope.AssertException();
      }
      return;
    }
    case i::wasm::kS128:
      thrower.TypeError("Invalid type v128");
      return;
    case i::wasm::kI8:
    case i::wasm::kI16:
    case i::wasm::kF16:
    case i::wasm::kVoid:
    case i::wasm::kTop:
    case i::wasm::kBottom:
      UNREACHABLE();
  }
  info.GetReturnValue().Set(result);
}
References DCHECK, v8::internal::DecodeI32ExceptionValue(), v8::internal::DecodeI64ExceptionValue(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::EnforceUint32(), EXTRACT_THIS, v8::internal::WasmExceptionPackage::GetExceptionTag(), v8::internal::WasmExceptionPackage::GetExceptionValues(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::Number::New(), v8::Integer::New(), v8::BigInt::New(), v8::base::internal::result, v8::anonymous_namespace{api.cc}::ToHandle(), UNREACHABLE, and v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::WasmObjectToJSReturnValue().
WebAssemblyExceptionImpl()
void v8::anonymous_namespace{wasm-js.cc}::WebAssemblyExceptionImpl (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 2149 of file wasm-js.cc.
                                                                           {
  WasmJSApiScope js_api_scope{info, "WebAssembly.Exception()"};
  auto [isolate, i_isolate, thrower] = js_api_scope.isolates_and_thrower();
  if (!info.IsConstructCall()) {
    thrower.TypeError("WebAssembly.Exception must be invoked with 'new'");
    return;
  }
  if (!info[0]->IsObject()) {
    thrower.TypeError("Argument 0 must be a WebAssembly tag");
    return;
  }
  i::DirectHandle<i::Object> arg0 = Utils::OpenDirectHandle(*info[0]);
  if (!IsWasmTagObject(i::Cast<i::HeapObject>(*arg0))) {
    thrower.TypeError("Argument 0 must be a WebAssembly tag");
    return;
  }
  auto tag_object = i::Cast<i::WasmTagObject>(arg0);
  i::DirectHandle<i::WasmExceptionTag> tag(
      i::Cast<i::WasmExceptionTag>(tag_object->tag()), i_isolate);
  auto js_tag = i::Cast<i::WasmTagObject>(i_isolate->context()->wasm_js_tag());
  if (*tag == js_tag->tag()) {
    thrower.TypeError("Argument 0 cannot be WebAssembly.JSTag");
    return;
  }
  const i::wasm::CanonicalSig* sig =
      i::wasm::GetTypeCanonicalizer()->LookupFunctionSignature(
          i::wasm::CanonicalTypeIndex{
              static_cast<uint32_t>(tag_object->canonical_type_index())});
  if (sig->return_count() != 0) {
    thrower.TypeError(
        "Invalid WebAssembly tag (return values not permitted in Exception "
        "tag)");
    return;
  }
  uint32_t size = GetEncodedSize(tag_object);
  i::DirectHandle<i::WasmExceptionPackage> runtime_exception =
      i::WasmExceptionPackage::New(i_isolate, tag, size);
  // The constructor above should guarantee that the cast below succeeds.
  i::DirectHandle<i::FixedArray> values =
      i::Cast<i::FixedArray>(i::WasmExceptionPackage::GetExceptionValues(
          i_isolate, runtime_exception));
  i::DirectHandle<i::PodArray<i::wasm::ValueType>> signature(
      tag_object->serialized_signature(), i_isolate);
  if (!EncodeExceptionValues(isolate, signature, tag_object, info[1], &thrower,
                             values)) {
    return js_api_scope.AssertException();
  }
  // Third argument: optional ExceptionOption ({traceStack: <bool>}).
  if (!info[2]->IsNullOrUndefined() && !info[2]->IsObject()) {
    thrower.TypeError("Argument 2 is not an object");
    return;
  }
  if (info[2]->IsObject()) {
    Local<Context> context = isolate->GetCurrentContext();
    Local<Object> trace_stack_obj = Local<Object>::Cast(info[2]);
    Local<String> trace_stack_key = v8_str(isolate, "traceStack");
    v8::Local<Value> trace_stack_value;
    if (!trace_stack_obj->Get(context, trace_stack_key)
             .ToLocal(&trace_stack_value)) {
      return js_api_scope.AssertException();
    }
    if (trace_stack_value->BooleanValue(isolate)) {
      i::Handle<i::Object> caller = Utils::OpenHandle(*info.NewTarget());
      i::DirectHandle<i::Object> capture_result;
      if (!i::ErrorUtils::CaptureStackTrace(i_isolate, runtime_exception,
                                            i::SKIP_NONE, caller)
               .ToHandle(&capture_result)) {
        return js_api_scope.AssertException();
      }
    }
  }
  info.GetReturnValue().Set(
      Utils::ToLocal(i::Cast<i::Object>(runtime_exception)));
}
References v8::internal::ErrorUtils::CaptureStackTrace(), v8::Local< T >::Cast(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::EncodeExceptionValues(), v8::Object::Get(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::GetEncodedSize(), v8::internal::WasmExceptionPackage::GetExceptionValues(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::internal::wasm::GetTypeCanonicalizer(), v8::FunctionCallbackInfo< T >::IsConstructCall(), v8::internal::IsNullOrUndefined(), v8::internal::IsObject(), v8::internal::wasm::TypeCanonicalizer::LookupFunctionSignature(), v8::internal::WasmExceptionPackage::New(), v8::FunctionCallbackInfo< T >::NewTarget(), v8::Utils::OpenDirectHandle(), v8::Utils::OpenHandle(), v8::internal::sig, size(), v8::internal::SKIP_NONE, v8::anonymous_namespace{api.cc}::ToHandle(), v8::MaybeLocal< T >::ToLocal(), and v8_str().
WebAssemblyExceptionIsImpl()
void v8::anonymous_namespace{wasm-js.cc}::WebAssemblyExceptionIsImpl (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 3076 of file wasm-js.cc.
                                                 {
  WasmJSApiScope js_api_scope{info, "WebAssembly.Exception.is()"};
  auto [isolate, i_isolate, thrower] = js_api_scope.isolates_and_thrower();
  EXTRACT_THIS(exception, WasmExceptionPackage);
  auto tag = i::WasmExceptionPackage::GetExceptionTag(i_isolate, exception);
  DCHECK(IsWasmExceptionTag(*tag));
  i::DirectHandle<i::WasmTagObject> tag_object;
  if (!GetFirstArgumentAsTag(info, &thrower).ToHandle(&tag_object)) {
    return js_api_scope.AssertException();
  }
  info.GetReturnValue().Set(tag_object->tag() == *tag);
}
References DCHECK, EXTRACT_THIS, v8::internal::WasmExceptionPackage::GetExceptionTag(), v8::FunctionCallbackInfo< T >::GetReturnValue(), and v8::anonymous_namespace{api.cc}::ToHandle().
WebAssemblyFunction()
void v8::anonymous_namespace{wasm-js.cc}::WebAssemblyFunction (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 2288 of file wasm-js.cc.
                                                                      {
  WasmJSApiScope js_api_scope{info, "WebAssembly.Function()"};
  auto [isolate, i_isolate, thrower] = js_api_scope.isolates_and_thrower();
  if (!info.IsConstructCall()) {
    thrower.TypeError("WebAssembly.Function must be invoked with 'new'");
    return;
  }
  if (!info[0]->IsObject()) {
    thrower.TypeError("Argument 0 must be a function type");
    return;
  }
  Local<Object> function_type = Local<Object>::Cast(info[0]);
  Local<Context> context = isolate->GetCurrentContext();
  auto enabled_features = WasmEnabledFeatures::FromIsolate(i_isolate);
  // Load the 'parameters' property of the function type.
  Local<String> parameters_key = v8_str(isolate, "parameters");
  v8::MaybeLocal<v8::Value> parameters_maybe =
      function_type->Get(context, parameters_key);
  v8::Local<v8::Value> parameters_value;
  if (!parameters_maybe.ToLocal(&parameters_value) ||
      !parameters_value->IsObject()) {
    thrower.TypeError("Argument 0 must be a function type with 'parameters'");
    return;
  }
  Local<Object> parameters = parameters_value.As<Object>();
  uint32_t parameters_len = GetIterableLength(i_isolate, context, parameters);
  if (parameters_len == i::kMaxUInt32) {
    thrower.TypeError("Argument 0 contains parameters without 'length'");
    return;
  }
  if (parameters_len > i::wasm::kV8MaxWasmFunctionParams) {
    thrower.TypeError("Argument 0 contains too many parameters");
    return;
  }
  // Load the 'results' property of the function type.
  v8::Local<v8::Value> results_value;
  if (!function_type->Get(context, v8_str(isolate, "results"))
           .ToLocal(&results_value)) {
    return js_api_scope.AssertException();
  }
  if (!results_value->IsObject()) {
    thrower.TypeError("Argument 0 must be a function type with 'results'");
    return;
  }
  Local<Object> results = results_value.As<Object>();
  uint32_t results_len = GetIterableLength(i_isolate, context, results);
  if (results_len == i::kMaxUInt32) {
    thrower.TypeError("Argument 0 contains results without 'length'");
    return;
  }
  if (results_len > i::wasm::kV8MaxWasmFunctionReturns) {
    thrower.TypeError("Argument 0 contains too many results");
    return;
  }
  // Decode the function type and construct a signature.
  i::Zone zone(i_isolate->allocator(), ZONE_NAME);
  i::wasm::FunctionSig::Builder builder(&zone, results_len, parameters_len);
  for (uint32_t i = 0; i < parameters_len; ++i) {
    MaybeLocal<Value> maybe = parameters->Get(context, i);
    std::optional<i::wasm::ValueType> maybe_type =
        GetValueType(isolate, maybe, context, enabled_features);
    if (!maybe_type) return;
    i::wasm::ValueType type = *maybe_type;
    if (type == i::wasm::kWasmVoid) {
      thrower.TypeError(
          "Argument 0 parameter type at index #%u must be a value type", i);
      return;
    }
    builder.AddParam(type);
  }
  for (uint32_t i = 0; i < results_len; ++i) {
    MaybeLocal<Value> maybe = results->Get(context, i);
    std::optional<i::wasm::ValueType> maybe_type =
        GetValueType(isolate, maybe, context, enabled_features);
    if (!maybe_type) return js_api_scope.AssertException();
    i::wasm::ValueType type = *maybe_type;
    if (type == i::wasm::kWasmVoid) {
      thrower.TypeError(
          "Argument 0 result type at index #%u must be a value type", i);
      return;
    }
    builder.AddReturn(type);
  }
  if (!info[1]->IsObject()) {
    thrower.TypeError("Argument 1 must be a function");
    return;
  }
  const i::wasm::FunctionSig* sig = builder.Get();
  i::wasm::Suspend suspend = i::wasm::kNoSuspend;
  i::DirectHandle<i::JSReceiver> callable =
      Utils::OpenDirectHandle(*info[1].As<Object>());
  if (i::IsWasmSuspendingObject(*callable)) {
    suspend = i::wasm::kSuspend;
    callable = direct_handle(
        i::Cast<i::WasmSuspendingObject>(*callable)->callable(), i_isolate);
    DCHECK(i::IsCallable(*callable));
  } else if (!i::IsCallable(*callable)) {
    thrower.TypeError("Argument 1 must be a function");
    return;
  }
  i::DirectHandle<i::JSFunction> result =
      i::WasmJSFunction::New(i_isolate, sig, callable, suspend);
  info.GetReturnValue().Set(Utils::ToLocal(result));
}
References v8::Local< T >::As(), v8::Local< T >::Cast(), DCHECK, v8::internal::direct_handle(), v8::Object::Get(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::GetIterableLength(), v8::FunctionCallbackInfo< T >::GetReturnValue(), GetValueType(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::FunctionCallbackInfo< T >::IsConstructCall(), v8::Value::IsObject(), v8::internal::IsObject(), v8::internal::kMaxUInt32, v8::internal::wasm::kNoSuspend, v8::internal::wasm::kSuspend, v8::internal::wasm::kV8MaxWasmFunctionParams, v8::internal::wasm::kV8MaxWasmFunctionReturns, v8::internal::wasm::kWasmVoid, v8::internal::WasmJSFunction::New(), v8::Utils::OpenDirectHandle(), v8::base::internal::result, v8::internal::sig, v8::MaybeLocal< T >::ToLocal(), v8::internal::tracing::type, v8_str(), and ZONE_NAME.
Referenced by v8::internal::WasmJs::InstallTypeReflection().
WebAssemblyFunctionType()
void v8::anonymous_namespace{wasm-js.cc}::WebAssemblyFunctionType (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 2493 of file wasm-js.cc.
                                                                          {
  WasmJSApiScope js_api_scope{info, "WebAssembly.Function.type()"};
  auto [isolate, i_isolate, thrower] = js_api_scope.isolates_and_thrower();
  i::DirectHandle<i::JSObject> type;
  i::DirectHandle<i::Object> fun = Utils::OpenDirectHandle(*info.This());
  if (i::WasmExportedFunction::IsWasmExportedFunction(*fun)) {
    auto wasm_exported_function = i::Cast<i::WasmExportedFunction>(fun);
    i::Tagged<i::WasmExportedFunctionData> data =
        wasm_exported_function->shared()->wasm_exported_function_data();
    // Note: while {zone} is only referenced directly in the if-block below,
    // its lifetime must exceed that of {sig}.
    // TODO(42210967): Creating a Zone just to create a modified copy of a
    // single signature is rather expensive. It would be good to find a more
    // efficient approach, if this function is ever considered performance
    // relevant.
    i::Zone zone(i_isolate->allocator(), ZONE_NAME);
    const i::wasm::FunctionSig* sig =
        data->instance_data()->module()->functions[data->function_index()].sig;
    i::wasm::Promise promise_flags =
        i::WasmFunctionData::PromiseField::decode(data->js_promise_flags());
    if (promise_flags == i::wasm::kPromise) {
      // The wrapper function returns a promise as an externref instead of the
      // original return type.
      size_t param_count = sig->parameter_count();
      i::wasm::FunctionSig::Builder builder(&zone, 1, param_count);
      for (size_t i = 0; i < param_count; ++i) {
        builder.AddParam(sig->GetParam(i));
      }
      builder.AddReturn(i::wasm::kWasmExternRef);
      sig = builder.Get();
    }
    type = i::wasm::GetTypeForFunction(i_isolate, sig);
  } else if (i::WasmJSFunction::IsWasmJSFunction(*fun)) {
    const i::wasm::CanonicalSig* sig = i::Cast<i::WasmJSFunction>(fun)
                                           ->shared()
                                           ->wasm_js_function_data()
                                           ->GetSignature();
    // As long as WasmJSFunctions cannot use indexed types, their canonical
    // signatures are bit-compatible with module-specific signatures.
#if DEBUG
    for (i::wasm::CanonicalValueType t : sig->all()) {
      DCHECK(!t.has_index());
    }
#endif
    static_assert(sizeof(i::wasm::ValueType) ==
                  sizeof(i::wasm::CanonicalValueType));
    type = i::wasm::GetTypeForFunction(
        i_isolate, reinterpret_cast<const i::wasm::FunctionSig*>(sig));
  } else {
    thrower.TypeError("Receiver must be a WebAssembly.Function");
    return;
  }
  info.GetReturnValue().Set(Utils::ToLocal(type));
}
References DCHECK, v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::internal::wasm::GetTypeForFunction(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::WasmExportedFunction::IsWasmExportedFunction(), v8::internal::WasmJSFunction::IsWasmJSFunction(), v8::internal::wasm::kPromise, v8::internal::wasm::kWasmExternRef, v8::Utils::OpenDirectHandle(), v8::internal::sig, v8::FunctionCallbackInfo< T >::This(), v8::internal::tracing::type, and ZONE_NAME.
Referenced by v8::internal::WasmJs::InstallTypeReflection().
WebAssemblyGlobalGetValueCommon()
void v8::anonymous_namespace{wasm-js.cc}::WebAssemblyGlobalGetValueCommon (WasmJSApiScope & js_api_scope)
Definition at line 3092 of file wasm-js.cc.
                                                                   {
  auto [isolate, i_isolate, thrower] = js_api_scope.isolates_and_thrower();
  auto& info = js_api_scope.callback_info(); // Needed by EXTRACT_THIS.
  EXTRACT_THIS(receiver, WasmGlobalObject);
  v8::ReturnValue<v8::Value> return_value = info.GetReturnValue();
  switch (receiver->type().kind()) {
    case i::wasm::kI32:
      return_value.Set(receiver->GetI32());
      break;
    case i::wasm::kI64: {
      Local<BigInt> value = BigInt::New(isolate, receiver->GetI64());
      return_value.Set(value);
      break;
    }
    case i::wasm::kF32:
      return_value.Set(receiver->GetF32());
      break;
    case i::wasm::kF64:
      return_value.Set(receiver->GetF64());
      break;
    case i::wasm::kS128:
      thrower.TypeError("Can't get the value of s128 WebAssembly.Global");
      break;
    case i::wasm::kRef:
    case i::wasm::kRefNull:
      if (!WasmObjectToJSReturnValue(return_value, receiver->GetRef(),
                                     receiver->type(), i_isolate, &thrower)) {
        return js_api_scope.AssertException();
      }
      break;
    case i::wasm::kI8:
    case i::wasm::kI16:
    case i::wasm::kF16:
    case i::wasm::kTop:
    case i::wasm::kBottom:
    case i::wasm::kVoid:
      UNREACHABLE();
  }
}
References EXTRACT_THIS, v8::BigInt::New(), v8::ReturnValue< T >::Set(), UNREACHABLE, v8::internal::value, and v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::WasmObjectToJSReturnValue().
Referenced by WebAssemblyGlobalGetValueImpl(), and WebAssemblyGlobalValueOfImpl().
WebAssemblyGlobalGetValueImpl()
void v8::anonymous_namespace{wasm-js.cc}::WebAssemblyGlobalGetValueImpl (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 3142 of file wasm-js.cc.
                                                 {
  WasmJSApiScope js_api_scope{info, "get WebAssembly.Global.value)"};
  return WebAssemblyGlobalGetValueCommon(js_api_scope);
}
References WebAssemblyGlobalGetValueCommon().
WebAssemblyGlobalImpl()
void v8::anonymous_namespace{wasm-js.cc}::WebAssemblyGlobalImpl (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 1807 of file wasm-js.cc.
                                                                        {
  WasmJSApiScope js_api_scope{info, "WebAssembly.Global()"};
  auto [isolate, i_isolate, thrower] = js_api_scope.isolates_and_thrower();
  if (!info.IsConstructCall()) {
    thrower.TypeError("WebAssembly.Global must be invoked with 'new'");
    return;
  }
  if (!info[0]->IsObject()) {
    thrower.TypeError("Argument 0 must be a global descriptor");
    return;
  }
  Local<Context> context = isolate->GetCurrentContext();
  Local<v8::Object> descriptor = Local<Object>::Cast(info[0]);
  auto enabled_features = WasmEnabledFeatures::FromIsolate(i_isolate);
  // The descriptor's 'mutable'.
  bool is_mutable;
  {
    v8::Local<v8::Value> value;
    if (!descriptor->Get(context, v8_str(isolate, "mutable")).ToLocal(&value)) {
      return js_api_scope.AssertException();
    }
    is_mutable = value->BooleanValue(isolate);
  }
  // The descriptor's type, called 'value'. It is called 'value' because this
  // descriptor is planned to be reused as the global's type for reflection,
  // so calling it 'type' is redundant.
  i::wasm::ValueType type;
  {
    v8::MaybeLocal<v8::Value> maybe =
        descriptor->Get(context, v8_str(isolate, "value"));
    std::optional<i::wasm::ValueType> maybe_type =
        GetValueType(isolate, maybe, context, enabled_features);
    if (!maybe_type) return js_api_scope.AssertException();
    type = *maybe_type;
    if (type == i::wasm::kWasmVoid) {
      thrower.TypeError(
          "Descriptor property 'value' must be a WebAssembly type");
      return;
    }
  }
  const uint32_t offset = 0;
  i::MaybeDirectHandle<i::WasmGlobalObject> maybe_global_obj =
      i::WasmGlobalObject::New(
          i_isolate, i::DirectHandle<i::WasmTrustedInstanceData>(),
          i::MaybeDirectHandle<i::JSArrayBuffer>(),
          i::MaybeDirectHandle<i::FixedArray>(), type, offset, is_mutable);
  i::DirectHandle<i::WasmGlobalObject> global_obj;
  if (!maybe_global_obj.ToHandle(&global_obj)) {
    return js_api_scope.AssertException();
  }
  // The infrastructure for `new Foo` calls allocates an object, which is
  // available here as {info.This()}. We're going to discard this object
  // and use {global_obj} instead, but it does have the correct prototype,
  // which we must harvest from it. This makes a difference when the JS
  // constructor function wasn't {WebAssembly.Global} directly, but some
  // subclass: {global_obj} has {WebAssembly.Global}'s prototype at this
  // point, so we must overwrite that with the correct prototype for {Foo}.
  if (!TransferPrototype(i_isolate, global_obj,
                         Utils::OpenDirectHandle(*info.This()))) {
    return js_api_scope.AssertException();
  }
  // Convert value to a WebAssembly value, the default value is 0.
  Local<v8::Value> value = Local<Value>::Cast(info[1]);
  switch (type.kind()) {
    case i::wasm::kI32: {
      int32_t i32_value = 0;
      if (!ToI32(value, context, &i32_value)) {
        return js_api_scope.AssertException();
      }
      global_obj->SetI32(i32_value);
      break;
    }
    case i::wasm::kI64: {
      int64_t i64_value = 0;
      if (!ToI64(value, context, &i64_value)) {
        return js_api_scope.AssertException();
      }
      global_obj->SetI64(i64_value);
      break;
    }
    case i::wasm::kF32: {
      float f32_value = 0;
      if (!ToF32(value, context, &f32_value)) {
        return js_api_scope.AssertException();
      }
      global_obj->SetF32(f32_value);
      break;
    }
    case i::wasm::kF64: {
      double f64_value = 0;
      if (!ToF64(value, context, &f64_value)) {
        return js_api_scope.AssertException();
      }
      global_obj->SetF64(f64_value);
      break;
    }
    case i::wasm::kRef:
      if (info.Length() < 2) {
        thrower.TypeError("Non-defaultable global needs initial value");
        return;
      }
      [[fallthrough]];
    case i::wasm::kRefNull: {
      // We need the wasm default value {null} over {undefined}.
      i::DirectHandle<i::Object> value_handle;
      if (info.Length() < 2) {
        value_handle = DefaultReferenceValue(i_isolate, type);
      } else {
        value_handle = Utils::OpenDirectHandle(*value);
        const char* error_message;
        // While the JS API generally allows indexed types, it currently has
        // no way to specify such types in `new WebAssembly.Global(...)`.
        // TODO(14034): Fix this if that changes.
        DCHECK(!type.has_index());
        i::wasm::CanonicalValueType canonical_type{type};
        if (!i::wasm::JSToWasmObject(i_isolate, value_handle, canonical_type,
                                     &error_message)
                 .ToHandle(&value_handle)) {
          thrower.TypeError("%s", error_message);
          return;
        }
      }
      global_obj->SetRef(value_handle);
      break;
    }
    case i::wasm::kS128: {
      thrower.TypeError(
          "A global of type 'v128' cannot be created in JavaScript");
      return;
    }
    case i::wasm::kI8:
    case i::wasm::kI16:
    case i::wasm::kF16:
    case i::wasm::kVoid:
    case i::wasm::kTop:
    case i::wasm::kBottom:
      UNREACHABLE();
  }
  i::DirectHandle<i::JSObject> global_js_object(global_obj);
  info.GetReturnValue().Set(Utils::ToLocal(global_js_object));
}
References v8::Local< T >::Cast(), DCHECK, v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::DefaultReferenceValue(), v8::Object::Get(), v8::FunctionCallbackInfo< T >::GetReturnValue(), GetValueType(), v8::FunctionCallbackInfo< T >::IsConstructCall(), v8::internal::IsObject(), v8::internal::wasm::JSToWasmObject(), v8::internal::wasm::kWasmVoid, v8::FunctionCallbackInfo< T >::Length(), v8::internal::WasmGlobalObject::New(), v8::Utils::OpenDirectHandle(), v8::FunctionCallbackInfo< T >::This(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::ToF32(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::ToF64(), v8::internal::MaybeDirectHandle< T >::ToHandle(), v8::anonymous_namespace{api.cc}::ToHandle(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::ToI32(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::ToI64(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::TransferPrototype(), v8::internal::tracing::type, UNREACHABLE, v8_str(), and v8::internal::value.
WebAssemblyGlobalSetValueImpl()
void v8::anonymous_namespace{wasm-js.cc}::WebAssemblyGlobalSetValueImpl (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 3149 of file wasm-js.cc.
                                                 {
  WasmJSApiScope js_api_scope{info, "set WebAssembly.Global.value)"};
  auto [isolate, i_isolate, thrower] = js_api_scope.isolates_and_thrower();
  EXTRACT_THIS(receiver, WasmGlobalObject);
  if (!receiver->is_mutable()) {
    thrower.TypeError("Can't set the value of an immutable global.");
    return;
  }
  if (info.Length() == 0) {
    thrower.TypeError("Argument 0 is required");
    return;
  }
  Local<Context> context = isolate->GetCurrentContext();
  switch (receiver->type().kind()) {
    case i::wasm::kI32: {
      int32_t i32_value = 0;
      if (!info[0]->Int32Value(context).To(&i32_value)) {
        return js_api_scope.AssertException();
      }
      receiver->SetI32(i32_value);
      break;
    }
    case i::wasm::kI64: {
      v8::Local<v8::BigInt> bigint_value;
      if (!info[0]->ToBigInt(context).ToLocal(&bigint_value)) {
        return js_api_scope.AssertException();
      }
      receiver->SetI64(bigint_value->Int64Value());
      break;
    }
    case i::wasm::kF32: {
      double f64_value = 0;
      if (!info[0]->NumberValue(context).To(&f64_value)) {
        return js_api_scope.AssertException();
      }
      receiver->SetF32(i::DoubleToFloat32(f64_value));
      break;
    }
    case i::wasm::kF64: {
      double f64_value = 0;
      if (!info[0]->NumberValue(context).To(&f64_value)) {
        return js_api_scope.AssertException();
      }
      receiver->SetF64(f64_value);
      break;
    }
    case i::wasm::kS128:
      thrower.TypeError("Can't set the value of s128 WebAssembly.Global");
      break;
    case i::wasm::kRef:
    case i::wasm::kRefNull: {
      const i::wasm::WasmModule* module =
          receiver->has_trusted_data()
              ? receiver->trusted_data(i_isolate)->module()
              : nullptr;
      i::DirectHandle<i::Object> value = Utils::OpenDirectHandle(*info[0]);
      const char* error_message;
      if (!i::wasm::JSToWasmObject(i_isolate, module, value, receiver->type(),
                                   &error_message)
               .ToHandle(&value)) {
        thrower.TypeError("%s", error_message);
        return;
      }
      receiver->SetRef(value);
      return;
    }
    case i::wasm::kI8:
    case i::wasm::kI16:
    case i::wasm::kF16:
    case i::wasm::kTop:
    case i::wasm::kBottom:
    case i::wasm::kVoid:
      UNREACHABLE();
  }
}
References v8::internal::DoubleToFloat32(), EXTRACT_THIS, v8::internal::wasm::JSToWasmObject(), v8::FunctionCallbackInfo< T >::Length(), v8::Utils::OpenDirectHandle(), UNREACHABLE, and v8::internal::value.
WebAssemblyGlobalType()
void v8::anonymous_namespace{wasm-js.cc}::WebAssemblyGlobalType (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 3229 of file wasm-js.cc.
                                                                        {
  WasmJSApiScope js_api_scope{info, "WebAssembly.Global.type())"};
  auto [isolate, i_isolate, thrower] = js_api_scope.isolates_and_thrower();
  EXTRACT_THIS(global, WasmGlobalObject);
  auto type = i::wasm::GetTypeForGlobal(i_isolate, global->is_mutable(),
                                        global->type());
  info.GetReturnValue().Set(Utils::ToLocal(type));
}
References EXTRACT_THIS, v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::internal::wasm::GetTypeForGlobal(), and v8::internal::tracing::type.
Referenced by v8::internal::WasmJs::InstallTypeReflection().
WebAssemblyGlobalValueOfImpl()
void v8::anonymous_namespace{wasm-js.cc}::WebAssemblyGlobalValueOfImpl (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 3135 of file wasm-js.cc.
                                                 {
  WasmJSApiScope js_api_scope{info, "WebAssembly.Global.valueOf()"};
  return WebAssemblyGlobalGetValueCommon(js_api_scope);
}
References WebAssemblyGlobalGetValueCommon().
WebAssemblyInstanceGetExportsImpl()
void v8::anonymous_namespace{wasm-js.cc}::WebAssemblyInstanceGetExportsImpl (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 2572 of file wasm-js.cc.
                                                 {
  WasmJSApiScope js_api_scope{info, "WebAssembly.Instance.exports()"};
  auto [isolate, i_isolate, thrower] = js_api_scope.isolates_and_thrower();
  EXTRACT_THIS(receiver, WasmInstanceObject);
  i::DirectHandle<i::JSObject> exports_object(receiver->exports_object(),
                                              i_isolate);
  info.GetReturnValue().Set(Utils::ToLocal(exports_object));
}
References EXTRACT_THIS, and v8::FunctionCallbackInfo< T >::GetReturnValue().
WebAssemblyInstanceImpl()
void v8::anonymous_namespace{wasm-js.cc}::WebAssemblyInstanceImpl (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 1068 of file wasm-js.cc.
                                                                          {
  WasmJSApiScope js_api_scope{info, "WebAssembly.Instance()"};
  auto [isolate, i_isolate, thrower] = js_api_scope.isolates_and_thrower();
  RecordCompilationMethod(i_isolate, kAsyncInstantiation);
  i_isolate->CountUsage(
      v8::Isolate::UseCounterFeature::kWebAssemblyInstantiation);
  if (i_isolate->wasm_instance_callback()(info)) return;
  i::DirectHandle<i::JSObject> instance_obj;
  {
    if (!info.IsConstructCall()) {
      thrower.TypeError("WebAssembly.Instance must be invoked with 'new'");
      return;
    }
    i::DirectHandle<i::WasmModuleObject> module_object;
    if (!GetFirstArgumentAsModule(info, &thrower).ToHandle(&module_object)) {
      return js_api_scope.AssertException();
    }
    Local<Value> ffi = info[1];
    if (!ffi->IsUndefined() && !ffi->IsObject()) {
      thrower.TypeError("Argument 1 must be an object");
      return;
    }
    if (!i::wasm::GetWasmEngine()
             ->SyncInstantiate(i_isolate, &thrower, module_object,
                               ImportsAsMaybeReceiver(ffi),
                               i::MaybeDirectHandle<i::JSArrayBuffer>())
             .ToHandle(&instance_obj)) {
      return js_api_scope.AssertException();
    }
  }
  // The infrastructure for `new Foo` calls allocates an object, which is
  // available here as {info.This()}. We're going to discard this object
  // and use {instance_obj} instead, but it does have the correct prototype,
  // which we must harvest from it. This makes a difference when the JS
  // constructor function wasn't {WebAssembly.Instance} directly, but some
  // subclass: {instance_obj} has {WebAssembly.Instance}'s prototype at this
  // point, so we must overwrite that with the correct prototype for {Foo}.
  if (!TransferPrototype(i_isolate, instance_obj,
                         Utils::OpenDirectHandle(*info.This()))) {
    return js_api_scope.AssertException();
  }
  info.GetReturnValue().Set(Utils::ToLocal(instance_obj));
}
References v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::internal::wasm::GetWasmEngine(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::ImportsAsMaybeReceiver(), v8::FunctionCallbackInfo< T >::IsConstructCall(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::kAsyncInstantiation, v8::Utils::OpenDirectHandle(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::RecordCompilationMethod(), v8::FunctionCallbackInfo< T >::This(), v8::anonymous_namespace{api.cc}::ToHandle(), and v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::TransferPrototype().
WebAssemblyInstantiateImpl()
void v8::anonymous_namespace{wasm-js.cc}::WebAssemblyInstantiateImpl (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 1162 of file wasm-js.cc.
                                                 {
  WasmJSApiScope js_api_scope{info, "WebAssembly.instantiate()"};
  auto [isolate, i_isolate, thrower] = js_api_scope.isolates_and_thrower();
  i_isolate->CountUsage(
      v8::Isolate::UseCounterFeature::kWebAssemblyInstantiation);
  Local<Context> context = isolate->GetCurrentContext();
  Local<Promise::Resolver> promise_resolver;
  if (!Promise::Resolver::New(context).ToLocal(&promise_resolver)) {
    return js_api_scope.AssertException();
  }
  Local<Promise> promise = promise_resolver->GetPromise();
  info.GetReturnValue().Set(promise);
  std::unique_ptr<i::wasm::InstantiationResultResolver> resolver(
      new InstantiateModuleResultResolver(isolate, context, promise_resolver));
  Local<Value> first_arg_value = info[0];
  i::DirectHandle<i::Object> first_arg =
      Utils::OpenDirectHandle(*first_arg_value);
  if (!IsJSObject(*first_arg)) {
    thrower.TypeError(
        "Argument 0 must be a buffer source or a WebAssembly.Module object");
    resolver->OnInstantiationFailed(thrower.Reify());
    return;
  }
  // If info.Length < 2, this will be undefined - see FunctionCallbackInfo.
  Local<Value> ffi = info[1];
  if (!ffi->IsUndefined() && !ffi->IsObject()) {
    thrower.TypeError("Argument 1 must be an object");
    resolver->OnInstantiationFailed(thrower.Reify());
    return;
  }
  if (IsWasmModuleObject(*first_arg)) {
    i::DirectHandle<i::WasmModuleObject> module_obj =
        i::Cast<i::WasmModuleObject>(first_arg);
    i::wasm::GetWasmEngine()->AsyncInstantiate(i_isolate, std::move(resolver),
                                               module_obj,
                                               ImportsAsMaybeReceiver(ffi));
    return;
  }
  base::OwnedVector<const uint8_t> bytes = GetAndCopyFirstArgumentAsBytes(
      info, i::wasm::max_module_size(), &thrower);
  if (bytes.empty()) {
    resolver->OnInstantiationFailed(thrower.Reify());
    return;
  }
  // We start compilation now, we have no use for the
  // {InstantiationResultResolver}.
  resolver.reset();
  std::shared_ptr<i::wasm::CompilationResultResolver> compilation_resolver(
      new AsyncInstantiateCompileResultResolver(isolate, context,
                                                promise_resolver, ffi));
  // The first parameter is a buffer source, we have to check if we are allowed
  // to compile it.
  i::DirectHandle<i::NativeContext> native_context =
      i_isolate->native_context();
  if (!i::wasm::IsWasmCodegenAllowed(i_isolate, native_context)) {
    i::DirectHandle<i::String> error =
        i::wasm::ErrorStringForCodegen(i_isolate, native_context);
    thrower.CompileError("%s", error->ToCString().get());
    compilation_resolver->OnCompilationFailed(thrower.Reify());
    return;
  }
  auto enabled_features = WasmEnabledFeatures::FromIsolate(i_isolate);
  CompileTimeImports compile_imports =
      ArgumentToCompileOptions(info[2], i_isolate, enabled_features);
  if (i_isolate->has_exception()) {
    if (i_isolate->is_execution_terminating()) return;
    i::DirectHandle<i::JSAny> exception(Cast<i::JSAny>(i_isolate->exception()),
                                        i_isolate);
    i_isolate->clear_exception();
    compilation_resolver->OnCompilationFailed(exception);
    return;
  }
  i::wasm::GetWasmEngine()->AsyncCompile(
      i_isolate, enabled_features, std::move(compile_imports),
      std::move(compilation_resolver), std::move(bytes),
      js_api_scope.api_name());
}
References v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::ArgumentToCompileOptions(), v8::internal::wasm::WasmEngine::AsyncCompile(), v8::internal::wasm::WasmEngine::AsyncInstantiate(), v8::base::OwnedVector< T >::empty(), v8::internal::wasm::ErrorStringForCodegen(), GetAndCopyFirstArgumentAsBytes(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::internal::wasm::GetWasmEngine(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::ImportsAsMaybeReceiver(), v8::internal::wasm::IsWasmCodegenAllowed(), v8::internal::wasm::max_module_size(), v8::internal::native_context, v8::Promise::Resolver::New(), and v8::Utils::OpenDirectHandle().
WebAssemblyInstantiateStreaming()
void v8::anonymous_namespace{wasm-js.cc}::WebAssemblyInstantiateStreaming (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 1124 of file wasm-js.cc.
                                                 {
  WasmJSApiScope js_api_scope{info, "WebAssembly.instantiateStreaming()"};
  auto [isolate, i_isolate, thrower] = js_api_scope.isolates_and_thrower();
  RecordCompilationMethod(i_isolate, kStreamingInstantiation);
  i_isolate->CountUsage(
      v8::Isolate::UseCounterFeature::kWebAssemblyInstantiation);
  Local<Context> context = isolate->GetCurrentContext();
  // Create and assign the return value of this function.
  Local<Promise::Resolver> result_resolver;
  if (!Promise::Resolver::New(context).ToLocal(&result_resolver)) {
    return js_api_scope.AssertException();
  }
  Local<Promise> promise = result_resolver->GetPromise();
  info.GetReturnValue().Set(promise);
  // If info.Length < 2, this will be undefined - see FunctionCallbackInfo.
  Local<Value> ffi = info[1];
  if (!ffi->IsUndefined() && !ffi->IsObject()) {
    thrower.TypeError("Argument 1 must be an object");
    InstantiateModuleResultResolver resolver(isolate, context, result_resolver);
    resolver.OnInstantiationFailed(thrower.Reify());
    return;
  }
  auto compilation_resolver =
      std::make_shared<AsyncInstantiateCompileResultResolver>(
          isolate, context, result_resolver, ffi);
  StartAsyncCompilationWithResolver(js_api_scope, info[0], info[2],
                                    std::move(compilation_resolver));
}
References v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::kStreamingInstantiation, v8::Promise::Resolver::New(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::RecordCompilationMethod(), and StartAsyncCompilationWithResolver().
Referenced by v8::internal::WasmJs::Install().
WebAssemblyMemoryGetBufferImpl()
void v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryGetBufferImpl (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 2837 of file wasm-js.cc.
                                                 {
  WasmJSApiScope js_api_scope{info, "WebAssembly.Memory.buffer"};
  auto [isolate, i_isolate, thrower] = js_api_scope.isolates_and_thrower();
  EXTRACT_THIS(receiver, WasmMemoryObject);
  i::DirectHandle<i::Object> buffer_obj(receiver->array_buffer(), i_isolate);
  DCHECK(IsJSArrayBuffer(*buffer_obj));
  i::DirectHandle<i::JSArrayBuffer> buffer(
      i::Cast<i::JSArrayBuffer>(*buffer_obj), i_isolate);
  if (buffer->is_shared()) {
    // TODO(gdeepti): More needed here for when cached buffer, and current
    // buffer are out of sync, handle that here when bounds checks, and Grow
    // are handled correctly.
    Maybe<bool> result =
        buffer->SetIntegrityLevel(i_isolate, buffer, i::FROZEN, i::kDontThrow);
    if (!result.FromJust()) {
      thrower.TypeError(
          "Status of setting SetIntegrityLevel of buffer is false.");
      return;
    }
  }
  info.GetReturnValue().Set(Utils::ToLocal(buffer));
}
References DCHECK, EXTRACT_THIS, v8::internal::FROZEN, v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::internal::kDontThrow, and v8::base::internal::result.
WebAssemblyMemoryGrowImpl()
void v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryGrowImpl (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 2802 of file wasm-js.cc.
                                                 {
  WasmJSApiScope js_api_scope{info, "WebAssembly.Memory.grow()"};
  auto [isolate, i_isolate, thrower] = js_api_scope.isolates_and_thrower();
  Local<Context> context = isolate->GetCurrentContext();
  EXTRACT_THIS(receiver, WasmMemoryObject);
  std::optional<uint64_t> maybe_delta_pages = AddressValueToU64(
      &thrower, context, info[0], "Argument 0", receiver->address_type());
  if (!maybe_delta_pages) return js_api_scope.AssertException();
  uint64_t delta_pages = *maybe_delta_pages;
  i::DirectHandle<i::JSArrayBuffer> old_buffer(receiver->array_buffer(),
                                               i_isolate);
  uint64_t old_pages = old_buffer->GetByteLength() / i::wasm::kWasmPageSize;
  uint64_t max_pages = receiver->maximum_pages();
  if (delta_pages > max_pages - old_pages) {
    thrower.RangeError("Maximum memory size exceeded");
    return;
  }
  static_assert(i::wasm::kV8MaxWasmMemory64Pages <= i::kMaxUInt32);
  int32_t ret = i::WasmMemoryObject::Grow(i_isolate, receiver,
                                          static_cast<uint32_t>(delta_pages));
  if (ret == -1) {
    thrower.RangeError("Unable to grow instance memory");
    return;
  }
  info.GetReturnValue().Set(
      AddressValueFromUnsigned(isolate, receiver->address_type(), ret));
}
References v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::AddressValueFromUnsigned(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::AddressValueToU64(), EXTRACT_THIS, v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::internal::WasmMemoryObject::Grow(), v8::internal::kMaxUInt32, v8::internal::wasm::kV8MaxWasmMemory64Pages, and v8_inspector::anonymous_namespace{value-mirror.cc}::kWasmPageSize.
WebAssemblyMemoryImpl()
void v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryImpl (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 1570 of file wasm-js.cc.
                                                                        {
  WasmJSApiScope js_api_scope{info, "WebAssembly.Memory()"};
  auto [isolate, i_isolate, thrower] = js_api_scope.isolates_and_thrower();
  if (!info.IsConstructCall()) {
    thrower.TypeError("WebAssembly.Memory must be invoked with 'new'");
    return;
  }
  if (!info[0]->IsObject()) {
    thrower.TypeError("Argument 0 must be a memory descriptor");
    return;
  }
  Local<Context> context = isolate->GetCurrentContext();
  Local<v8::Object> descriptor = Local<Object>::Cast(info[0]);
  // Parse the 'address' property of the `descriptor`.
  std::optional<AddressType> maybe_address_type =
      GetAddressType(isolate, context, descriptor, &thrower);
  if (!maybe_address_type) return js_api_scope.AssertException();
  AddressType address_type = *maybe_address_type;
  uint64_t max_supported_pages = address_type == AddressType::kI64
                                     ? i::wasm::kSpecMaxMemory64Pages
                                     : i::wasm::kSpecMaxMemory32Pages;
  // {max_supported_pages} will actually be in integer range. That's the type
  // {WasmMemoryObject::New} uses.
  static_assert(i::wasm::kSpecMaxMemory32Pages < i::kMaxInt);
  static_assert(i::wasm::kSpecMaxMemory64Pages < i::kMaxInt);
  // Parse the 'initial' or 'minimum' property of the `descriptor`.
  std::optional<uint64_t> maybe_initial =
      GetInitialOrMinimumProperty(isolate, &thrower, context, descriptor,
                                  address_type, max_supported_pages);
  if (!maybe_initial) {
    return js_api_scope.AssertException();
  }
  uint64_t initial = *maybe_initial;
  // Parse the 'maximum' property of the `descriptor`.
  auto maybe_maybe_maximum = GetOptionalAddressValue(
      &thrower, context, descriptor, v8_str(isolate, "maximum"), address_type,
      initial, max_supported_pages);
  if (!maybe_maybe_maximum) {
    return js_api_scope.AssertException();
  }
  std::optional<uint64_t> maybe_maximum = *maybe_maybe_maximum;
  // Parse the 'shared' property of the `descriptor`.
  v8::Local<v8::Value> value;
  if (!descriptor->Get(context, v8_str(isolate, "shared")).ToLocal(&value)) {
    return js_api_scope.AssertException();
  }
  auto shared = value->BooleanValue(isolate) ? i::SharedFlag::kShared
                                             : i::SharedFlag::kNotShared;
  // Throw TypeError if shared is true, and the descriptor has no "maximum".
  if (shared == i::SharedFlag::kShared && !maybe_maximum.has_value()) {
    thrower.TypeError("If shared is true, maximum property should be defined.");
    return;
  }
  i::DirectHandle<i::JSObject> memory_obj;
  if (!i::WasmMemoryObject::New(i_isolate, static_cast<int>(initial),
                                maybe_maximum ? static_cast<int>(*maybe_maximum)
                                              : i::WasmMemoryObject::kNoMaximum,
                                shared, address_type)
           .ToHandle(&memory_obj)) {
    thrower.RangeError("could not allocate memory");
    return;
  }
  // The infrastructure for `new Foo` calls allocates an object, which is
  // available here as {info.This()}. We're going to discard this object
  // and use {memory_obj} instead, but it does have the correct prototype,
  // which we must harvest from it. This makes a difference when the JS
  // constructor function wasn't {WebAssembly.Memory} directly, but some
  // subclass: {memory_obj} has {WebAssembly.Memory}'s prototype at this
  // point, so we must overwrite that with the correct prototype for {Foo}.
  if (!TransferPrototype(i_isolate, memory_obj,
                         Utils::OpenDirectHandle(*info.This()))) {
    return js_api_scope.AssertException();
  }
  if (shared == i::SharedFlag::kShared) {
    i::DirectHandle<i::JSArrayBuffer> buffer(
        i::Cast<i::WasmMemoryObject>(memory_obj)->array_buffer(), i_isolate);
    Maybe<bool> result =
        buffer->SetIntegrityLevel(i_isolate, buffer, i::FROZEN, i::kDontThrow);
    if (!result.FromJust()) {
      thrower.TypeError(
          "Status of setting SetIntegrityLevel of buffer is false.");
      return;
    }
  }
  info.GetReturnValue().Set(Utils::ToLocal(memory_obj));
}
References v8::Local< T >::Cast(), v8::internal::FROZEN, v8::Object::Get(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::GetAddressType(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::GetInitialOrMinimumProperty(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::GetOptionalAddressValue(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::FunctionCallbackInfo< T >::IsConstructCall(), v8::internal::IsObject(), v8::internal::kDontThrow, v8::internal::kMaxInt, v8::internal::WasmMemoryObject::kNoMaximum, v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::kNotShared, v8::internal::kShared, v8::internal::wasm::kSpecMaxMemory32Pages, v8::internal::wasm::kSpecMaxMemory64Pages, v8::internal::WasmMemoryObject::New(), v8::Utils::OpenDirectHandle(), v8::base::internal::result, v8::FunctionCallbackInfo< T >::This(), v8::anonymous_namespace{api.cc}::ToHandle(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::TransferPrototype(), v8_str(), and v8::internal::value.
WebAssemblyMemoryMapDescriptorImpl()
void v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryMapDescriptorImpl (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 1668 of file wasm-js.cc.
                                                 {
  CHECK(i::v8_flags.experimental_wasm_memory_control);
  WasmJSApiScope js_api_scope{info, "WebAssembly.MemoryMapDescriptor()"};
  auto [isolate, i_isolate, thrower] = js_api_scope.isolates_and_thrower();
  if (!info.IsConstructCall()) {
    thrower.TypeError(
        "WebAssembly.MemoryMapDescriptor must be invoked with 'new'");
    return js_api_scope.AssertException();
  }
  std::optional<uint32_t> size =
      EnforceUint32("size", info[0], isolate->GetCurrentContext(), &thrower);
  if (!size.has_value()) {
    return js_api_scope.AssertException();
  }
  i::DirectHandle<i::JSObject> descriptor_obj;
  if (!i::WasmMemoryMapDescriptor::NewFromAnonymous(i_isolate, size.value())
           .ToHandle(&descriptor_obj)) {
    thrower.RuntimeError("Failed to create a MemoryMapDescriptor");
    return js_api_scope.AssertException();
  }
  // The infrastructure for `new Foo` calls allocates an object, which is
  // available here as {info.This()}. We're going to discard this object
  // and use {memory_obj} instead, but it does have the correct prototype,
  // which we must harvest from it. This makes a difference when the JS
  // constructor function wasn't {WebAssembly.Memory} directly, but some
  // subclass: {memory_obj} has {WebAssembly.Memory}'s prototype at this
  // point, so we must overwrite that with the correct prototype for {Foo}.
  if (!TransferPrototype(i_isolate, descriptor_obj,
                         Utils::OpenDirectHandle(*info.This()))) {
    DCHECK(i_isolate->has_exception());
    return js_api_scope.AssertException();
  }
  info.GetReturnValue().Set(Utils::ToLocal(descriptor_obj));
}
References CHECK, DCHECK, v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::EnforceUint32(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::FunctionCallbackInfo< T >::IsConstructCall(), v8::internal::WasmMemoryMapDescriptor::NewFromAnonymous(), v8::Utils::OpenDirectHandle(), size(), v8::FunctionCallbackInfo< T >::This(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::TransferPrototype(), and v8::internal::v8_flags.
WebAssemblyMemoryMapDescriptorMapImpl()
void v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryMapDescriptorMapImpl (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 2752 of file wasm-js.cc.
                                                 {
  CHECK(i::v8_flags.experimental_wasm_memory_control);
  WasmJSApiScope js_api_scope{info, "WebAssembly.MemoryMapDescriptor.map()"};
  auto [isolate, i_isolate, thrower] = js_api_scope.isolates_and_thrower();
  EXTRACT_THIS(receiver, WasmMemoryMapDescriptor);
  i::DirectHandle<i::WasmMemoryObject> memory;
  {
    i::DirectHandle<i::Object> memory_param = Utils::OpenDirectHandle(*info[0]);
    if (!i::IsWasmMemoryObject(*memory_param)) {
      thrower.TypeError("Parameter is not a WebAssembly.Memory");
      return js_api_scope.AssertException();
    }
    memory = i::Cast<i::WasmMemoryObject>(memory_param);
  }
  Local<Context> context = isolate->GetCurrentContext();
  std::optional<uint32_t> offset =
      EnforceUint32("Argument 1", info[1], context, &thrower);
  if (!offset.has_value()) {
    return js_api_scope.AssertException();
  }
  size_t mapped_size = receiver->MapDescriptor(memory, offset.value());
  if (!mapped_size) {
    thrower.RuntimeError(
        "Failed to map the MemoryMapDescriptor to WebAssembly memory.");
    return js_api_scope.AssertException();
  }
  receiver->set_memory(MakeWeak(*memory));
  receiver->set_offset(offset.value());
  receiver->set_size(static_cast<uint32_t>(mapped_size));
  info.GetReturnValue().Set(static_cast<int64_t>(mapped_size));
}
References CHECK, v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::EnforceUint32(), EXTRACT_THIS, v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::api_internal::MakeWeak(), v8::Utils::OpenDirectHandle(), and v8::internal::v8_flags.
WebAssemblyMemoryMapDescriptorUnmapImpl()
void v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryMapDescriptorUnmapImpl (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 2788 of file wasm-js.cc.
                                                 {
  CHECK(i::v8_flags.experimental_wasm_memory_control);
  WasmJSApiScope js_api_scope{info, "WebAssembly.MemoryMapDescriptor.unmap()"};
  auto [isolate, i_isolate, thrower] = js_api_scope.isolates_and_thrower();
  EXTRACT_THIS(receiver, WasmMemoryMapDescriptor);
  if (!receiver->UnmapDescriptor()) {
    thrower.RangeError("Failed to unmap the MemoryMapDescriptor.");
    return;
  }
}
References CHECK, EXTRACT_THIS, and v8::internal::v8_flags.
WebAssemblyMemoryToFixedLengthBufferImpl()
void v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryToFixedLengthBufferImpl (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 2863 of file wasm-js.cc.
                                                 {
  WasmJSApiScope js_api_scope{info, "WebAssembly.Memory.toFixedLengthBuffer()"};
  auto [isolate, i_isolate, thrower] = js_api_scope.isolates_and_thrower();
  EXTRACT_THIS(receiver, WasmMemoryObject);
  i::DirectHandle<i::Object> buffer_obj(receiver->array_buffer(), i_isolate);
  DCHECK(IsJSArrayBuffer(*buffer_obj));
  i::DirectHandle<i::JSArrayBuffer> buffer(
      i::Cast<i::JSArrayBuffer>(*buffer_obj), i_isolate);
  if (buffer->is_resizable_by_js()) {
    buffer = i::WasmMemoryObject::ToFixedLengthBuffer(i_isolate, receiver);
  }
  if (buffer->is_shared()) {
    Maybe<bool> result =
        buffer->SetIntegrityLevel(i_isolate, buffer, i::FROZEN, i::kDontThrow);
    if (!result.FromJust()) {
      thrower.TypeError(
          "Status of setting SetIntegrityLevel of buffer is false.");
      return;
    }
  }
  v8::ReturnValue<v8::Value> return_value = info.GetReturnValue();
  return_value.Set(Utils::ToLocal(buffer));
}
References DCHECK, EXTRACT_THIS, v8::internal::FROZEN, v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::internal::kDontThrow, v8::base::internal::result, v8::ReturnValue< T >::Set(), and v8::internal::WasmMemoryObject::ToFixedLengthBuffer().
WebAssemblyMemoryToResizableBufferImpl()
void v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryToResizableBufferImpl (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 2890 of file wasm-js.cc.
                                                 {
  WasmJSApiScope js_api_scope{info, "WebAssembly.Memory.toResizableBuffer()"};
  auto [isolate, i_isolate, thrower] = js_api_scope.isolates_and_thrower();
  EXTRACT_THIS(receiver, WasmMemoryObject);
  i::DirectHandle<i::Object> buffer_obj(receiver->array_buffer(), i_isolate);
  DCHECK(IsJSArrayBuffer(*buffer_obj));
  i::DirectHandle<i::JSArrayBuffer> buffer(
      i::Cast<i::JSArrayBuffer>(*buffer_obj), i_isolate);
  if (!buffer->is_resizable_by_js()) {
    if (!receiver->has_maximum_pages()) {
      thrower.TypeError("Memory must have a maximum");
      return;
    }
    buffer = i::WasmMemoryObject::ToResizableBuffer(i_isolate, receiver);
  }
  if (buffer->is_shared()) {
    Maybe<bool> result =
        buffer->SetIntegrityLevel(i_isolate, buffer, i::FROZEN, i::kDontThrow);
    if (!result.FromJust()) {
      thrower.TypeError(
          "Status of setting SetIntegrityLevel of buffer is false.");
      return;
    }
  }
  v8::ReturnValue<v8::Value> return_value = info.GetReturnValue();
  return_value.Set(Utils::ToLocal(buffer));
}
References DCHECK, EXTRACT_THIS, v8::internal::FROZEN, v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::internal::kDontThrow, v8::base::internal::result, v8::ReturnValue< T >::Set(), and v8::internal::WasmMemoryObject::ToResizableBuffer().
WebAssemblyMemoryType()
void v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryType (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 2921 of file wasm-js.cc.
                                                                        {
  WasmJSApiScope js_api_scope{info, "WebAssembly.Memory.type()"};
  auto [isolate, i_isolate, thrower] = js_api_scope.isolates_and_thrower();
  EXTRACT_THIS(memory, WasmMemoryObject);
  i::DirectHandle<i::JSArrayBuffer> buffer(memory->array_buffer(), i_isolate);
  size_t curr_size = buffer->GetByteLength() / i::wasm::kWasmPageSize;
  DCHECK_LE(curr_size, std::numeric_limits<uint32_t>::max());
  uint32_t min_size = static_cast<uint32_t>(curr_size);
  std::optional<uint32_t> max_size;
  if (memory->has_maximum_pages()) {
    uint64_t max_size64 = memory->maximum_pages();
    DCHECK_LE(max_size64, std::numeric_limits<uint32_t>::max());
    max_size.emplace(static_cast<uint32_t>(max_size64));
  }
  bool shared = buffer->is_shared();
  auto type = i::wasm::GetTypeForMemory(i_isolate, min_size, max_size, shared,
                                        memory->address_type());
  info.GetReturnValue().Set(Utils::ToLocal(type));
}
References DCHECK_LE, EXTRACT_THIS, v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::internal::wasm::GetTypeForMemory(), v8_inspector::anonymous_namespace{value-mirror.cc}::kWasmPageSize, and v8::internal::tracing::type.
Referenced by v8::internal::WasmJs::InstallTypeReflection().
WebAssemblyModuleCustomSectionsImpl()
void v8::anonymous_namespace{wasm-js.cc}::WebAssemblyModuleCustomSectionsImpl (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 1041 of file wasm-js.cc.
                                                 {
  WasmJSApiScope js_api_scope{info, "WebAssembly.Module.customSections()"};
  auto [isolate, i_isolate, thrower] = js_api_scope.isolates_and_thrower();
  i::DirectHandle<i::WasmModuleObject> module_object;
  if (!GetFirstArgumentAsModule(info, &thrower).ToHandle(&module_object)) {
    return js_api_scope.AssertException();
  }
  if (info[1]->IsUndefined()) {
    thrower.TypeError("Argument 1 is required");
    return;
  }
  i::DirectHandle<i::Object> name;
  if (!i::Object::ToString(i_isolate, Utils::OpenDirectHandle(*info[1]))
           .ToHandle(&name)) {
    return js_api_scope.AssertException();
  }
  auto custom_sections = i::wasm::GetCustomSections(
      i_isolate, module_object, i::Cast<i::String>(name), &thrower);
  if (thrower.error()) return;
  info.GetReturnValue().Set(Utils::ToLocal(custom_sections));
}
References v8::internal::wasm::GetCustomSections(), v8::FunctionCallbackInfo< T >::GetReturnValue(), name, v8::Utils::OpenDirectHandle(), v8::anonymous_namespace{api.cc}::ToHandle(), and ToString().
WebAssemblyModuleExportsImpl()
void v8::anonymous_namespace{wasm-js.cc}::WebAssemblyModuleExportsImpl (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 1027 of file wasm-js.cc.
                                                 {
  WasmJSApiScope js_api_scope{info, "WebAssembly.Module.exports()"};
  auto [isolate, i_isolate, thrower] = js_api_scope.isolates_and_thrower();
  i::DirectHandle<i::WasmModuleObject> module_object;
  if (!GetFirstArgumentAsModule(info, &thrower).ToHandle(&module_object)) {
    return js_api_scope.AssertException();
  }
  auto exports = i::wasm::GetExports(i_isolate, module_object);
  info.GetReturnValue().Set(Utils::ToLocal(exports));
}
References v8::internal::wasm::GetExports(), v8::FunctionCallbackInfo< T >::GetReturnValue(), and v8::anonymous_namespace{api.cc}::ToHandle().
WebAssemblyModuleImpl()
void v8::anonymous_namespace{wasm-js.cc}::WebAssemblyModuleImpl (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 956 of file wasm-js.cc.
                                                                        {
  WasmJSApiScope js_api_scope{info, "WebAssembly.Module()"};
  auto [isolate, i_isolate, thrower] = js_api_scope.isolates_and_thrower();
  if (i_isolate->wasm_module_callback()(info)) return;
  RecordCompilationMethod(i_isolate, kSyncCompilation);
  if (!info.IsConstructCall()) {
    thrower.TypeError("WebAssembly.Module must be invoked with 'new'");
    return;
  }
  i::DirectHandle<i::NativeContext> native_context =
      i_isolate->native_context();
  if (!i::wasm::IsWasmCodegenAllowed(i_isolate, native_context)) {
    i::DirectHandle<i::String> error =
        i::wasm::ErrorStringForCodegen(i_isolate, native_context);
    thrower.CompileError("%s", error->ToCString().get());
    return;
  }
  base::OwnedVector<const uint8_t> bytes = GetAndCopyFirstArgumentAsBytes(
      info, i::wasm::max_module_size(), &thrower);
  if (bytes.empty()) return js_api_scope.AssertException();
  auto enabled_features = WasmEnabledFeatures::FromIsolate(i_isolate);
  CompileTimeImports compile_imports =
      ArgumentToCompileOptions(info[1], i_isolate, enabled_features);
  if (i_isolate->has_exception()) {
    // TODO(14179): Does this need different error message handling?
    return;
  }
  i::MaybeDirectHandle<i::WasmModuleObject> maybe_module_obj;
  maybe_module_obj = i::wasm::GetWasmEngine()->SyncCompile(
      i_isolate, enabled_features, std::move(compile_imports), &thrower,
      std::move(bytes));
  i::DirectHandle<i::WasmModuleObject> module_obj;
  if (!maybe_module_obj.ToHandle(&module_obj)) return;
  // The infrastructure for `new Foo` calls allocates an object, which is
  // available here as {info.This()}. We're going to discard this object
  // and use {module_obj} instead, but it does have the correct prototype,
  // which we must harvest from it. This makes a difference when the JS
  // constructor function wasn't {WebAssembly.Module} directly, but some
  // subclass: {module_obj} has {WebAssembly.Module}'s prototype at this
  // point, so we must overwrite that with the correct prototype for {Foo}.
  if (!TransferPrototype(i_isolate, module_obj,
                         Utils::OpenDirectHandle(*info.This()))) {
    return;
  }
  v8::ReturnValue<v8::Value> return_value = info.GetReturnValue();
  return_value.Set(Utils::ToLocal(module_obj));
}
References v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::ArgumentToCompileOptions(), v8::base::OwnedVector< T >::empty(), v8::internal::wasm::ErrorStringForCodegen(), GetAndCopyFirstArgumentAsBytes(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::internal::wasm::GetWasmEngine(), v8::FunctionCallbackInfo< T >::IsConstructCall(), v8::internal::wasm::IsWasmCodegenAllowed(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::kSyncCompilation, v8::internal::wasm::max_module_size(), v8::internal::native_context, v8::Utils::OpenDirectHandle(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::RecordCompilationMethod(), v8::ReturnValue< T >::Set(), v8::internal::wasm::WasmEngine::SyncCompile(), v8::FunctionCallbackInfo< T >::This(), v8::internal::MaybeDirectHandle< T >::ToHandle(), and v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::TransferPrototype().
WebAssemblyModuleImportsImpl()
void v8::anonymous_namespace{wasm-js.cc}::WebAssemblyModuleImportsImpl (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 1013 of file wasm-js.cc.
                                                 {
  WasmJSApiScope js_api_scope{info, "WebAssembly.Module.imports()"};
  auto [isolate, i_isolate, thrower] = js_api_scope.isolates_and_thrower();
  i::DirectHandle<i::WasmModuleObject> module_object;
  if (!GetFirstArgumentAsModule(info, &thrower).ToHandle(&module_object)) {
    return js_api_scope.AssertException();
  }
  auto imports = i::wasm::GetImports(i_isolate, module_object);
  info.GetReturnValue().Set(Utils::ToLocal(imports));
}
References v8::internal::wasm::GetImports(), v8::FunctionCallbackInfo< T >::GetReturnValue(), and v8::anonymous_namespace{api.cc}::ToHandle().
WebAssemblyPromising()
void v8::anonymous_namespace{wasm-js.cc}::WebAssemblyPromising (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 2401 of file wasm-js.cc.
                                                                       {
  WasmJSApiScope js_api_scope{info, "WebAssembly.promising()"};
  auto [isolate, i_isolate, thrower] = js_api_scope.isolates_and_thrower();
  i_isolate->CountUsage(v8::Isolate::kWasmJavaScriptPromiseIntegration);
  if (!info[0]->IsFunction()) {
    thrower.TypeError("Argument 0 must be a function");
    return;
  }
  i::DirectHandle<i::JSReceiver> callable =
      Utils::OpenDirectHandle(*info[0].As<Function>());
  if (!i::WasmExportedFunction::IsWasmExportedFunction(*callable)) {
    thrower.TypeError("Argument 0 must be a WebAssembly exported function");
    return;
  }
  auto wasm_exported_function = i::Cast<i::WasmExportedFunction>(*callable);
  i::DirectHandle<i::WasmExportedFunctionData> data(
      wasm_exported_function->shared()->wasm_exported_function_data(),
      i_isolate);
  if (data->instance_data()->module_object()->is_asm_js()) {
    thrower.TypeError("Argument 0 must be a WebAssembly exported function");
    return;
  }
  i::DirectHandle<i::JSFunction> result =
      NewPromisingWasmExportedFunction(i_isolate, data, thrower);
  info.GetReturnValue().Set(Utils::ToLocal(i::Cast<i::JSObject>(result)));
}
References v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::internal::WasmExportedFunction::IsWasmExportedFunction(), v8::Isolate::kWasmJavaScriptPromiseIntegration, NewPromisingWasmExportedFunction(), v8::Utils::OpenDirectHandle(), and v8::base::internal::result.
Referenced by v8::internal::WasmJs::InstallJSPromiseIntegration().
WebAssemblySuspendingImpl()
void v8::anonymous_namespace{wasm-js.cc}::WebAssemblySuspendingImpl (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 2431 of file wasm-js.cc.
                                                 {
  WasmJSApiScope js_api_scope{info, "WebAssembly.Suspending()"};
  auto [isolate, i_isolate, thrower] = js_api_scope.isolates_and_thrower();
  i_isolate->CountUsage(v8::Isolate::kWasmJavaScriptPromiseIntegration);
  if (!info.IsConstructCall()) {
    thrower.TypeError("WebAssembly.Suspending must be invoked with 'new'");
    return;
  }
  if (!info[0]->IsFunction()) {
    thrower.TypeError("Argument 0 must be a function");
    return;
  }
  i::DirectHandle<i::JSReceiver> callable =
      Utils::OpenDirectHandle(*info[0].As<Function>());
  if (i::WasmExportedFunction::IsWasmExportedFunction(*callable) ||
      i::WasmJSFunction::IsWasmJSFunction(*callable)) {
    thrower.TypeError("Argument 0 must not be a WebAssembly function");
    return;
  }
  i::DirectHandle<i::WasmSuspendingObject> result =
      i::WasmSuspendingObject::New(i_isolate, callable);
  info.GetReturnValue().Set(Utils::ToLocal(i::Cast<i::JSObject>(result)));
}
References v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::FunctionCallbackInfo< T >::IsConstructCall(), v8::internal::WasmExportedFunction::IsWasmExportedFunction(), v8::internal::WasmJSFunction::IsWasmJSFunction(), v8::Isolate::kWasmJavaScriptPromiseIntegration, v8::internal::WasmSuspendingObject::New(), v8::Utils::OpenDirectHandle(), and v8::base::internal::result.
Referenced by v8::internal::WasmJs::InstallJSPromiseIntegration().
WebAssemblyTableGetImpl()
void v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableGetImpl (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 2668 of file wasm-js.cc.
                                                                          {
  WasmJSApiScope js_api_scope{info, "WebAssembly.Table.get()"};
  auto [isolate, i_isolate, thrower] = js_api_scope.isolates_and_thrower();
  Local<Context> context = isolate->GetCurrentContext();
  EXTRACT_THIS(receiver, WasmTableObject);
  std::optional<uint64_t> maybe_address = AddressValueToU64(
      &thrower, context, info[0], "Argument 0", receiver->address_type());
  if (!maybe_address) return;
  uint64_t address = *maybe_address;
  if (address > i::kMaxUInt32 ||
      !receiver->is_in_bounds(static_cast<uint32_t>(address))) {
    thrower.RangeError("invalid address %" PRIu64 " in %s table of size %d",
                       address, receiver->unsafe_type().name().c_str(),
                       receiver->current_length());
    return;
  }
  i::DirectHandle<i::Object> result = i::WasmTableObject::Get(
      i_isolate, receiver, static_cast<uint32_t>(address));
  v8::ReturnValue<v8::Value> return_value = info.GetReturnValue();
  if (!WasmObjectToJSReturnValue(return_value, result, receiver->unsafe_type(),
                                 i_isolate, &thrower)) {
    return js_api_scope.AssertException();
  }
}
References v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::AddressValueToU64(), EXTRACT_THIS, v8::internal::WasmTableObject::Get(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::internal::kMaxUInt32, v8::base::internal::result, and v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::WasmObjectToJSReturnValue().
WebAssemblyTableGetLengthImpl()
void v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableGetLengthImpl (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 2583 of file wasm-js.cc.
                                                 {
  WasmJSApiScope js_api_scope{info, "WebAssembly.Table.length()"};
  auto [isolate, i_isolate, thrower] = js_api_scope.isolates_and_thrower();
  EXTRACT_THIS(receiver, WasmTableObject);
  int length = receiver->current_length();
  DCHECK_LE(0, length);
  info.GetReturnValue().Set(
      AddressValueFromUnsigned(isolate, receiver->address_type(), length));
}
References v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::AddressValueFromUnsigned(), DCHECK_LE, EXTRACT_THIS, v8::FunctionCallbackInfo< T >::GetReturnValue(), and v8::internal::length.
WebAssemblyTableGrowImpl()
void v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableGrowImpl (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 2596 of file wasm-js.cc.
                                                                           {
  WasmJSApiScope js_api_scope{info, "WebAssembly.Table.grow()"};
  auto [isolate, i_isolate, thrower] = js_api_scope.isolates_and_thrower();
  Local<Context> context = isolate->GetCurrentContext();
  EXTRACT_THIS(receiver, WasmTableObject);
  std::optional<uint64_t> maybe_grow_by = AddressValueToU64(
      &thrower, context, info[0], "Argument 0", receiver->address_type());
  if (!maybe_grow_by) return js_api_scope.AssertException();
  uint64_t grow_by = *maybe_grow_by;
  i::DirectHandle<i::Object> init_value;
  if (info.Length() >= 2) {
    init_value = Utils::OpenDirectHandle(*info[1]);
    const char* error_message;
    if (!i::WasmTableObject::JSToWasmElement(i_isolate, receiver, init_value,
                                             &error_message)
             .ToHandle(&init_value)) {
      thrower.TypeError("Argument 1 is invalid: %s", error_message);
      return;
    }
  } else if (receiver->unsafe_type().is_non_nullable()) {
    thrower.TypeError(
        "Argument 1 must be specified for non-nullable element type");
    return;
  } else {
    init_value = DefaultReferenceValue(i_isolate, receiver->unsafe_type());
  }
  static_assert(i::wasm::kV8MaxWasmTableSize <= i::kMaxUInt32);
  int old_size = grow_by > i::wasm::max_table_size()
                     ? -1
                     : i::WasmTableObject::Grow(i_isolate, receiver,
                                                static_cast<uint32_t>(grow_by),
                                                init_value);
  if (old_size < 0) {
    thrower.RangeError("failed to grow table by %" PRIu64, grow_by);
    return;
  }
  info.GetReturnValue().Set(
      AddressValueFromUnsigned(isolate, receiver->address_type(), old_size));
}
References v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::AddressValueFromUnsigned(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::AddressValueToU64(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::DefaultReferenceValue(), EXTRACT_THIS, v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::internal::WasmTableObject::Grow(), v8::internal::WasmTableObject::JSToWasmElement(), v8::internal::kMaxUInt32, v8::internal::wasm::kV8MaxWasmTableSize, v8::FunctionCallbackInfo< T >::Length(), v8::internal::wasm::max_table_size(), v8::Utils::OpenDirectHandle(), and v8::anonymous_namespace{api.cc}::ToHandle().
WebAssemblyTableImpl()
void v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableImpl (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 1426 of file wasm-js.cc.
                                                                       {
  WasmJSApiScope js_api_scope{info, "WebAssembly.Table()"};
  auto [isolate, i_isolate, thrower] = js_api_scope.isolates_and_thrower();
  if (!info.IsConstructCall()) {
    thrower.TypeError("WebAssembly.Table must be invoked with 'new'");
    return;
  }
  if (!info[0]->IsObject()) {
    thrower.TypeError("Argument 0 must be a table descriptor");
    return;
  }
  Local<Context> context = isolate->GetCurrentContext();
  Local<v8::Object> descriptor = Local<Object>::Cast(info[0]);
  i::wasm::ValueType type;
  // Parse the 'element' property of the `descriptor`.
  {
    v8::Local<v8::Value> value;
    if (!descriptor->Get(context, v8_str(isolate, "element")).ToLocal(&value)) {
      return js_api_scope.AssertException();
    }
    i::DirectHandle<i::String> string;
    if (!i::Object::ToString(reinterpret_cast<i::Isolate*>(isolate),
                             Utils::OpenDirectHandle(*value))
             .ToHandle(&string)) {
      return js_api_scope.AssertException();
    }
    auto enabled_features = WasmEnabledFeatures::FromIsolate(i_isolate);
    // The JS api uses 'anyfunc' instead of 'funcref'.
    if (string->IsEqualTo(base::CStrVector("anyfunc"))) {
      type = i::wasm::kWasmFuncRef;
    } else if (enabled_features.has_type_reflection() &&
               string->IsEqualTo(base::CStrVector("funcref"))) {
      // With the type reflection proposal, "funcref" replaces "anyfunc",
      // and anyfunc just becomes an alias for "funcref".
      type = i::wasm::kWasmFuncRef;
    } else if (string->IsEqualTo(base::CStrVector("externref"))) {
      type = i::wasm::kWasmExternRef;
    } else if (enabled_features.has_stringref() &&
               string->IsEqualTo(base::CStrVector("stringref"))) {
      type = i::wasm::kWasmStringRef;
    } else if (string->IsEqualTo(base::CStrVector("anyref"))) {
      type = i::wasm::kWasmAnyRef;
    } else if (string->IsEqualTo(base::CStrVector("eqref"))) {
      type = i::wasm::kWasmEqRef;
    } else if (string->IsEqualTo(base::CStrVector("structref"))) {
      type = i::wasm::kWasmStructRef;
    } else if (string->IsEqualTo(base::CStrVector("arrayref"))) {
      type = i::wasm::kWasmArrayRef;
    } else if (string->IsEqualTo(base::CStrVector("i31ref"))) {
      type = i::wasm::kWasmI31Ref;
    } else {
      thrower.TypeError(
          "Descriptor property 'element' must be a WebAssembly reference type");
      return;
    }
    // TODO(14616): Support shared types.
  }
  // Parse the 'address' property of the `descriptor`.
  std::optional<AddressType> maybe_address_type =
      GetAddressType(isolate, context, descriptor, &thrower);
  if (!maybe_address_type) {
    DCHECK(i_isolate->has_exception() || thrower.error());
    return;
  }
  AddressType address_type = *maybe_address_type;
  // Parse the 'initial' or 'minimum' property of the `descriptor`.
  std::optional<uint64_t> maybe_initial = GetInitialOrMinimumProperty(
      isolate, &thrower, context, descriptor, address_type,
      i::wasm::max_table_init_entries());
  if (!maybe_initial) return js_api_scope.AssertException();
  static_assert(i::wasm::kV8MaxWasmTableInitEntries <= i::kMaxUInt32);
  uint32_t initial = static_cast<uint32_t>(*maybe_initial);
  // Parse the 'maximum' property of the `descriptor`.
  uint64_t kNoMaximum = i::kMaxUInt64;
  auto maybe_maybe_maximum = GetOptionalAddressValue(
      &thrower, context, descriptor, v8_str(isolate, "maximum"), address_type,
      initial, kNoMaximum);
  if (!maybe_maybe_maximum) return js_api_scope.AssertException();
  std::optional<uint64_t> maybe_maximum = *maybe_maybe_maximum;
  DCHECK(!type.has_index()); // The JS API can't express type indices.
  i::wasm::CanonicalValueType canonical_type{type};
  i::DirectHandle<i::WasmTableObject> table_obj = i::WasmTableObject::New(
      i_isolate, i::DirectHandle<i::WasmTrustedInstanceData>(), type,
      canonical_type, initial, maybe_maximum.has_value(),
      maybe_maximum.value_or(0) /* note: unused if previous param is false */,
      DefaultReferenceValue(i_isolate, type), address_type);
  // The infrastructure for `new Foo` calls allocates an object, which is
  // available here as {info.This()}. We're going to discard this object
  // and use {table_obj} instead, but it does have the correct prototype,
  // which we must harvest from it. This makes a difference when the JS
  // constructor function wasn't {WebAssembly.Table} directly, but some
  // subclass: {table_obj} has {WebAssembly.Table}'s prototype at this
  // point, so we must overwrite that with the correct prototype for {Foo}.
  if (!TransferPrototype(i_isolate, table_obj,
                         Utils::OpenDirectHandle(*info.This()))) {
    return js_api_scope.AssertException();
  }
  if (initial > 0 && info.Length() >= 2 && !info[1]->IsUndefined()) {
    i::DirectHandle<i::Object> element = Utils::OpenDirectHandle(*info[1]);
    const char* error_message;
    if (!i::WasmTableObject::JSToWasmElement(i_isolate, table_obj, element,
                                             &error_message)
             .ToHandle(&element)) {
      thrower.TypeError(
          "Argument 2 must be undefined or a value of type compatible "
          "with the type of the new table: %s.",
          error_message);
      return;
    }
    for (uint32_t index = 0; index < static_cast<uint32_t>(initial); ++index) {
      i::WasmTableObject::Set(i_isolate, table_obj, index, element);
    }
  } else if (initial > 0) {
    DCHECK_EQ(type, table_obj->unsafe_type());
    switch (type.heap_representation()) {
      case i::wasm::HeapType::kString:
        thrower.TypeError(
            "Missing initial value when creating stringref table");
        return;
      case i::wasm::HeapType::kStringViewWtf8:
        thrower.TypeError("stringview_wtf8 has no JS representation");
        return;
      case i::wasm::HeapType::kStringViewWtf16:
        thrower.TypeError("stringview_wtf16 has no JS representation");
        return;
      case i::wasm::HeapType::kStringViewIter:
        thrower.TypeError("stringview_iter has no JS representation");
        return;
      default:
        break;
    }
  }
  v8::ReturnValue<v8::Value> return_value = info.GetReturnValue();
  return_value.Set(Utils::ToLocal(i::Cast<i::JSObject>(table_obj)));
}
References v8::Local< T >::Cast(), v8::base::CStrVector(), DCHECK, DCHECK_EQ, v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::DefaultReferenceValue(), v8::Object::Get(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::GetAddressType(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::GetInitialOrMinimumProperty(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::GetOptionalAddressValue(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::internal::index, v8::FunctionCallbackInfo< T >::IsConstructCall(), v8::internal::IsObject(), v8::internal::WasmTableObject::JSToWasmElement(), v8::internal::kMaxUInt32, v8::internal::kMaxUInt64, v8::internal::wasm::kNoMaximum, v8::internal::wasm::kV8MaxWasmTableInitEntries, v8::internal::wasm::kWasmAnyRef, v8::internal::wasm::kWasmArrayRef, v8::internal::wasm::kWasmEqRef, v8::internal::wasm::kWasmExternRef, v8::internal::wasm::kWasmFuncRef, v8::internal::wasm::kWasmI31Ref, v8::internal::wasm::kWasmStringRef, v8::internal::wasm::kWasmStructRef, v8::FunctionCallbackInfo< T >::Length(), v8::internal::wasm::max_table_init_entries(), v8::internal::WasmTableObject::New(), v8::Utils::OpenDirectHandle(), v8::ReturnValue< T >::Set(), v8::internal::WasmTableObject::Set(), v8::internal::string, v8::FunctionCallbackInfo< T >::This(), v8::anonymous_namespace{api.cc}::ToHandle(), ToString(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::TransferPrototype(), v8::internal::tracing::type, v8_str(), and v8::internal::value.
WebAssemblyTableSetImpl()
void v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableSetImpl (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 2698 of file wasm-js.cc.
                                                                          {
  WasmJSApiScope js_api_scope{info, "WebAssembly.Table.set()"};
  auto [isolate, i_isolate, thrower] = js_api_scope.isolates_and_thrower();
  Local<Context> context = isolate->GetCurrentContext();
  EXTRACT_THIS(table_object, WasmTableObject);
  std::optional<uint64_t> maybe_address = AddressValueToU64(
      &thrower, context, info[0], "Argument 0", table_object->address_type());
  if (!maybe_address) return js_api_scope.AssertException();
  uint64_t address = *maybe_address;
  if (address > i::kMaxUInt32 ||
      !table_object->is_in_bounds(static_cast<uint32_t>(address))) {
    thrower.RangeError("invalid address %" PRIu64 " in %s table of size %d",
                       address, table_object->unsafe_type().name().c_str(),
                       table_object->current_length());
    return;
  }
  i::DirectHandle<i::Object> element;
  if (info.Length() >= 2) {
    element = Utils::OpenDirectHandle(*info[1]);
    const char* error_message;
    if (!i::WasmTableObject::JSToWasmElement(i_isolate, table_object, element,
                                             &error_message)
             .ToHandle(&element)) {
      thrower.TypeError("Argument 1 is invalid for table: %s", error_message);
      return;
    }
  } else if (table_object->unsafe_type().is_defaultable()) {
    element = DefaultReferenceValue(i_isolate, table_object->unsafe_type());
  } else {
    thrower.TypeError("Table of non-defaultable type %s needs explicit element",
                      table_object->unsafe_type().name().c_str());
    return;
  }
  i::WasmTableObject::Set(i_isolate, table_object,
                          static_cast<uint32_t>(address), element);
}
References v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::AddressValueToU64(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::DefaultReferenceValue(), EXTRACT_THIS, v8::internal::WasmTableObject::JSToWasmElement(), v8::internal::kMaxUInt32, v8::FunctionCallbackInfo< T >::Length(), v8::Utils::OpenDirectHandle(), v8::internal::WasmTableObject::Set(), and v8::anonymous_namespace{api.cc}::ToHandle().
WebAssemblyTableType()
void v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableType (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 2740 of file wasm-js.cc.
                                                                       {
  WasmJSApiScope js_api_scope{info, "WebAssembly.Table.type()"};
  auto [isolate, i_isolate, thrower] = js_api_scope.isolates_and_thrower();
  EXTRACT_THIS(table, WasmTableObject);
  std::optional<uint64_t> max_size = table->maximum_length_u64();
  auto type = i::wasm::GetTypeForTable(i_isolate, table->unsafe_type(),
                                       table->current_length(), max_size,
                                       table->address_type());
  info.GetReturnValue().Set(Utils::ToLocal(type));
}
References EXTRACT_THIS, v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::internal::wasm::GetTypeForTable(), and v8::internal::tracing::type.
Referenced by v8::internal::WasmJs::InstallTypeReflection().
WebAssemblyTagImpl()
void v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTagImpl (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 1973 of file wasm-js.cc.
                                                                     {
  WasmJSApiScope js_api_scope{info, "WebAssembly.Tag()"};
  auto [isolate, i_isolate, thrower] = js_api_scope.isolates_and_thrower();
  if (!info.IsConstructCall()) {
    thrower.TypeError("WebAssembly.Tag must be invoked with 'new'");
    return;
  }
  if (!info[0]->IsObject()) {
    thrower.TypeError("Argument 0 must be a tag type");
    return;
  }
  Local<Object> event_type = Local<Object>::Cast(info[0]);
  Local<Context> context = isolate->GetCurrentContext();
  auto enabled_features = WasmEnabledFeatures::FromIsolate(i_isolate);
  // Load the 'parameters' property of the event type.
  Local<String> parameters_key = v8_str(isolate, "parameters");
  v8::MaybeLocal<v8::Value> parameters_maybe =
      event_type->Get(context, parameters_key);
  v8::Local<v8::Value> parameters_value;
  if (!parameters_maybe.ToLocal(&parameters_value) ||
      !parameters_value->IsObject()) {
    thrower.TypeError("Argument 0 must be a tag type with 'parameters'");
    return;
  }
  Local<Object> parameters = parameters_value.As<Object>();
  uint32_t parameters_len = GetIterableLength(i_isolate, context, parameters);
  if (parameters_len == i::kMaxUInt32) {
    thrower.TypeError("Argument 0 contains parameters without 'length'");
    return;
  }
  if (parameters_len > i::wasm::kV8MaxWasmFunctionParams) {
    thrower.TypeError("Argument 0 contains too many parameters");
    return;
  }
  // Decode the tag type and construct a signature.
  std::vector<i::wasm::ValueType> param_types(parameters_len,
                                              i::wasm::kWasmVoid);
  for (uint32_t i = 0; i < parameters_len; ++i) {
    i::wasm::ValueType& type = param_types[i];
    MaybeLocal<Value> maybe = parameters->Get(context, i);
    std::optional<i::wasm::ValueType> maybe_type =
        GetValueType(isolate, maybe, context, enabled_features);
    if (!maybe_type) return;
    type = *maybe_type;
    if (type == i::wasm::kWasmVoid) {
      thrower.TypeError(
          "Argument 0 parameter type at index #%u must be a value type", i);
      return;
    }
  }
  const i::wasm::FunctionSig sig{0, parameters_len, param_types.data()};
  // Set the tag index to 0. It is only used for debugging purposes, and has no
  // meaningful value when declared outside of a wasm module.
  auto tag = i::WasmExceptionTag::New(i_isolate, 0);
  i::wasm::CanonicalTypeIndex type_index =
      i::wasm::GetWasmEngine()->type_canonicalizer()->AddRecursiveGroup(&sig);
  i::DirectHandle<i::JSObject> tag_object =
      i::WasmTagObject::New(i_isolate, &sig, type_index, tag,
                            i::DirectHandle<i::WasmTrustedInstanceData>());
  info.GetReturnValue().Set(Utils::ToLocal(tag_object));
}
References v8::internal::wasm::TypeCanonicalizer::AddRecursiveGroup(), v8::Local< T >::As(), v8::Local< T >::Cast(), v8::Object::Get(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::GetIterableLength(), v8::FunctionCallbackInfo< T >::GetReturnValue(), GetValueType(), v8::internal::wasm::GetWasmEngine(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::FunctionCallbackInfo< T >::IsConstructCall(), v8::Value::IsObject(), v8::internal::IsObject(), v8::internal::kMaxUInt32, v8::internal::wasm::kV8MaxWasmFunctionParams, v8::internal::wasm::kWasmVoid, v8::internal::WasmTagObject::New(), v8::internal::WasmExceptionTag::New(), v8::internal::sig, v8::MaybeLocal< T >::ToLocal(), v8::internal::tracing::type, v8::internal::wasm::WasmEngine::type_canonicalizer(), and v8_str().
WebAssemblyTagType()
void v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTagType (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 2943 of file wasm-js.cc.
                                                                     {
  WasmJSApiScope js_api_scope{info, "WebAssembly.Tag.type()"};
  auto [isolate, i_isolate, thrower] = js_api_scope.isolates_and_thrower();
  EXTRACT_THIS(tag, WasmTagObject);
  int n = tag->serialized_signature()->length();
  std::vector<i::wasm::ValueType> data(n);
  if (n > 0) {
    tag->serialized_signature()->copy_out(0, data.data(), n);
  }
  const i::wasm::FunctionSig sig{0, data.size(), data.data()};
  constexpr bool kForException = true;
  auto type = i::wasm::GetTypeForFunction(i_isolate, &sig, kForException);
  info.GetReturnValue().Set(Utils::ToLocal(type));
}
References EXTRACT_THIS, v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::internal::wasm::GetTypeForFunction(), v8::internal::sig, and v8::internal::tracing::type.
Referenced by v8::internal::WasmJs::InstallTypeReflection().
WebAssemblyValidateImpl()
void v8::anonymous_namespace{wasm-js.cc}::WebAssemblyValidateImpl (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 886 of file wasm-js.cc.
                                                                          {
  WasmJSApiScope js_api_scope{info, "WebAssembly.validate()"};
  auto [isolate, i_isolate, thrower] = js_api_scope.isolates_and_thrower();
  v8::ReturnValue<v8::Value> return_value = info.GetReturnValue();
  bool bytes_are_shared = false;
  base::Vector<const uint8_t> bytes = GetFirstArgumentAsBytes(
      info, i::wasm::max_module_size(), &thrower, &bytes_are_shared);
  if (bytes.empty()) {
    js_api_scope.AssertException();
    // Propagate anything except wasm exceptions.
    if (!thrower.wasm_error()) return;
    // Clear wasm exceptions; return false instead.
    thrower.Reset();
    return_value.Set(v8::False(isolate));
    return;
  }
  auto enabled_features = WasmEnabledFeatures::FromIsolate(i_isolate);
  CompileTimeImports compile_imports =
      ArgumentToCompileOptions(info[1], i_isolate, enabled_features);
  if (i_isolate->has_exception()) {
    if (i_isolate->is_execution_terminating()) return;
    i_isolate->clear_exception();
    return_value.Set(v8::False(isolate));
    return;
  }
  bool validated = false;
  if (bytes_are_shared) {
    // Make a copy of the wire bytes to avoid concurrent modification.
    // Use relaxed reads (and writes, which is unnecessary here) to avoid TSan
    // reports in case the buffer is shared and is being modified concurrently.
    auto bytes_copy = base::OwnedVector<uint8_t>::NewForOverwrite(bytes.size());
    base::Relaxed_Memcpy(reinterpret_cast<base::Atomic8*>(bytes_copy.begin()),
                         reinterpret_cast<const base::Atomic8*>(bytes.data()),
                         bytes.size());
    validated = i::wasm::GetWasmEngine()->SyncValidate(
        i_isolate, enabled_features, std::move(compile_imports),
        bytes_copy.as_vector());
  } else {
    // The wire bytes are not shared, OK to use them directly.
    validated = i::wasm::GetWasmEngine()->SyncValidate(
        i_isolate, enabled_features, std::move(compile_imports), bytes);
  }
  return_value.Set(validated);
}
References v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::ArgumentToCompileOptions(), v8::base::Vector< T >::data(), v8::base::Vector< T >::empty(), v8::False(), GetFirstArgumentAsBytes(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::internal::wasm::GetWasmEngine(), v8::internal::wasm::max_module_size(), v8::base::OwnedVector< T >::NewForOverwrite(), v8::base::Relaxed_Memcpy(), v8::ReturnValue< T >::Set(), v8::base::Vector< T >::size(), and v8::internal::wasm::WasmEngine::SyncValidate().
Variable Documentation
kName_WasmExceptionPackage
constexpr const char* v8::anonymous_namespace{wasm-js.cc}::kName_WasmExceptionPackage = `WebAssembly.Exception` [constexpr]
Definition at line 2558 of file wasm-js.cc.
kName_WasmGlobalObject
constexpr const char* v8::anonymous_namespace{wasm-js.cc}::kName_WasmGlobalObject = `WebAssembly.Global` [constexpr]
Definition at line 2551 of file wasm-js.cc.
kName_WasmInstanceObject
constexpr const char* v8::anonymous_namespace{wasm-js.cc}::kName_WasmInstanceObject = `WebAssembly.Instance` [constexpr]
Definition at line 2555 of file wasm-js.cc.
kName_WasmMemoryMapDescriptor
constexpr const char* v8::anonymous_namespace{wasm-js.cc}::kName_WasmMemoryMapDescriptor [constexpr]
Initial value:
=
    "WebAssembly.MemoryMapDescriptor"
Definition at line 2553 of file wasm-js.cc.
kName_WasmMemoryObject
constexpr const char* v8::anonymous_namespace{wasm-js.cc}::kName_WasmMemoryObject = `WebAssembly.Memory` [constexpr]
Definition at line 2552 of file wasm-js.cc.
kName_WasmTableObject
constexpr const char* v8::anonymous_namespace{wasm-js.cc}::kName_WasmTableObject = `WebAssembly.Table` [constexpr]
Definition at line 2556 of file wasm-js.cc.
kName_WasmTagObject
constexpr const char* v8::anonymous_namespace{wasm-js.cc}::kName_WasmTagObject = `WebAssembly.Tag` [constexpr]
Definition at line 2557 of file wasm-js.cc.