v8::internal::anonymous_namespace{parser.cc} Namespace Reference
Functions
void MaybeProcessSourceRanges (ParseInfo *parse_info, Expression *root, uintptr_t stack_limit_)
Function Documentation
MaybeProcessSourceRanges()
void v8::internal::anonymous_namespace{parser.cc}::MaybeProcessSourceRanges (ParseInfo * parse_info, Expression * root, uintptr_t stack_limit_)
Definition at line 683 of file parser.cc.
                                                      {
  if (parse_info->source_range_map() != nullptr) {
    SourceRangeAstVisitor visitor(stack_limit_, root,
                                  parse_info->source_range_map());
    visitor.Run();
  }
}
References v8::internal::AstTraversalVisitor< Subclass >::Run(), and v8::internal::ParseInfo::source_range_map().
Referenced by v8::internal::Parser::ParseFunction(), v8::internal::Parser::ParseOnBackground(), and v8::internal::Parser::ParseProgram().