v8::internal::compiler::anonymous_namespace{late-escape-analysis.cc} Namespace Reference
Functions
bool IsStore (Edge edge)
bool IsEscapingAllocationWitness (Edge edge)
std::optional< Node * > TryGetStoredValue (Node *node)
Function Documentation
IsEscapingAllocationWitness()
bool v8::internal::compiler::anonymous_namespace{late-escape-analysis.cc}::IsEscapingAllocationWitness (Edge edge)
Definition at line 43 of file late-escape-analysis.cc.
                                            {
  if (edge.to()->opcode() != IrOpcode::kAllocateRaw) return false;
  if (!NodeProperties::IsValueEdge(edge)) return false;
  return !IsStore(edge);
}
References IsStore(), v8::internal::compiler::NodeProperties::IsValueEdge(), v8::internal::compiler::Node::opcode(), and v8::internal::compiler::Edge::to().
Referenced by v8::internal::compiler::LateEscapeAnalysis::Reduce().
IsStore()
bool v8::internal::compiler::anonymous_namespace{late-escape-analysis.cc}::IsStore (Edge edge)
Definition at line 27 of file late-escape-analysis.cc.
                        {
  DCHECK_EQ(edge.to()->opcode(), IrOpcode::kAllocateRaw);
  DCHECK(NodeProperties::IsValueEdge(edge));
  switch (edge.from()->opcode()) {
    case IrOpcode::kInitializeImmutableInObject:
    case IrOpcode::kStore:
    case IrOpcode::kStoreElement:
    case IrOpcode::kStoreField:
    case IrOpcode::kStoreToObject:
      return edge.index() == 0;
    default:
      return false;
  }
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::Edge::from(), v8::internal::compiler::Edge::index(), v8::internal::compiler::NodeProperties::IsValueEdge(), v8::internal::compiler::Node::opcode(), and v8::internal::compiler::Edge::to().
Referenced by IsEscapingAllocationWitness().
TryGetStoredValue()
std::optional<Node*> v8::internal::compiler::anonymous_namespace{late-escape-analysis.cc}::TryGetStoredValue (Node * node)
Definition at line 83 of file late-escape-analysis.cc.
                                                 {
  int value_index;
  switch (node->opcode()) {
    case IrOpcode::kInitializeImmutableInObject:
    case IrOpcode::kStore:
    case IrOpcode::kStoreElement:
    case IrOpcode::kStoreToObject:
      value_index = 2;
      break;
    case IrOpcode::kStoreField:
      value_index = 1;
      break;
    default:
      return {};
  }
  return NodeProperties::GetValueInput(node, value_index);
}
References v8::internal::compiler::NodeProperties::GetValueInput(), and v8::internal::compiler::Node::opcode().
Referenced by v8::internal::compiler::LateEscapeAnalysis::RemoveAllocation().