v8::internal::anonymous_namespace{js-list-format.cc} Namespace Reference
Classes
struct CheckListPattern
Functions
UListFormatterWidth GetIcuWidth (JSListFormat::Style style)
UListFormatterType GetIcuType (JSListFormat::Type type)
Maybe< std::vector< icu::UnicodeString > > ToUnicodeStringArray (Isolate *isolate, DirectHandle< FixedArray > array)
template<typename T >
MaybeDirectHandle< T > FormatListCommon (Isolate *isolate, DirectHandle< JSListFormat > format, DirectHandle< FixedArray > list, const std::function< MaybeDirectHandle< T >(Isolate *, const icu::FormattedValue &)> &formatToResult)
DirectHandle< String > IcuFieldIdToType (Isolate *isolate, int32_t field_id)
MaybeDirectHandle< JSArray > FormattedListToJSArray (Isolate *isolate, const icu::FormattedValue &formatted)
Function Documentation
FormatListCommon()
template<typename T >
MaybeDirectHandle<T> v8::internal::anonymous_namespace{js-list-format.cc}::FormatListCommon (Isolate * isolate, DirectHandle< JSListFormat > format, DirectHandle< FixedArray > list, const std::function< MaybeDirectHandle< T >(Isolate *, const icu::FormattedValue &)> & formatToResult)
Definition at line 218 of file js-list-format.cc.
                                                              {
  DCHECK(!IsUndefined(*list));
  Maybe<std::vector<icu::UnicodeString>> maybe_array =
      ToUnicodeStringArray(isolate, list);
  MAYBE_RETURN(maybe_array, DirectHandle<T>());
  std::vector<icu::UnicodeString> array = maybe_array.FromJust();
  icu::ListFormatter* formatter = format->icu_formatter()->raw();
  DCHECK_NOT_NULL(formatter);
  UErrorCode status = U_ZERO_ERROR;
  icu::FormattedList formatted = formatter->formatStringsToValue(
      array.data(), static_cast<int32_t>(array.size()), status);
  if (U_FAILURE(status)) {
    THROW_NEW_ERROR(isolate, NewTypeError(MessageTemplate::kIcuError));
  }
  return formatToResult(isolate, formatted);
}
References v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::format, v8::Maybe< T >::FromJust(), MAYBE_RETURN, v8::internal::status, THROW_NEW_ERROR, and ToUnicodeStringArray().
FormattedListToJSArray()
MaybeDirectHandle<JSArray> v8::internal::anonymous_namespace{js-list-format.cc}::FormattedListToJSArray (Isolate * isolate, const icu::FormattedValue & formatted)
Definition at line 254 of file js-list-format.cc.
                                                          {
  DirectHandle<JSArray> array = isolate->factory()->NewJSArray(0);
  icu::ConstrainedFieldPosition cfpos;
  cfpos.constrainCategory(UFIELD_CATEGORY_LIST);
  int index = 0;
  UErrorCode status = U_ZERO_ERROR;
  icu::UnicodeString string = formatted.toString(status);
  DirectHandle<String> substring;
  while (formatted.nextPosition(cfpos, status) && U_SUCCESS(status)) {
    ASSIGN_RETURN_ON_EXCEPTION(
        isolate, substring,
        Intl::ToString(isolate, string, cfpos.getStart(), cfpos.getLimit()));
    Intl::AddElement(isolate, array, index++,
                     IcuFieldIdToType(isolate, cfpos.getField()), substring);
  }
  if (U_FAILURE(status)) {
    THROW_NEW_ERROR(isolate, NewTypeError(MessageTemplate::kIcuError));
  }
  JSObject::ValidateElements(isolate, *array);
  return array;
}
References v8::internal::Intl::AddElement(), ASSIGN_RETURN_ON_EXCEPTION, v8::internal::Isolate::factory(), IcuFieldIdToType(), v8::internal::index, v8::internal::Factory::NewJSArray(), v8::internal::status, THROW_NEW_ERROR, v8::internal::Intl::ToString(), and v8::internal::JSObject::ValidateElements().
GetIcuType()
UListFormatterType v8::internal::anonymous_namespace{js-list-format.cc}::GetIcuType (JSListFormat::Type type)
Definition at line 46 of file js-list-format.cc.
                                                     {
  switch (type) {
    case JSListFormat::Type::CONJUNCTION:
      return ULISTFMT_TYPE_AND;
    case JSListFormat::Type::DISJUNCTION:
      return ULISTFMT_TYPE_OR;
    case JSListFormat::Type::UNIT:
      return ULISTFMT_TYPE_UNITS;
  }
  UNREACHABLE();
}
References v8::internal::JSListFormat::CONJUNCTION, v8::internal::JSListFormat::DISJUNCTION, v8::internal::tracing::type, v8::internal::JSListFormat::UNIT, and v8::internal::UNREACHABLE().
Referenced by v8::internal::JSListFormat::New().
GetIcuWidth()
UListFormatterWidth v8::internal::anonymous_namespace{js-list-format.cc}::GetIcuWidth (JSListFormat::Style style)
Definition at line 34 of file js-list-format.cc.
                                                         {
  switch (style) {
    case JSListFormat::Style::LONG:
      return ULISTFMT_WIDTH_WIDE;
    case JSListFormat::Style::SHORT:
      return ULISTFMT_WIDTH_SHORT;
    case JSListFormat::Style::NARROW:
      return ULISTFMT_WIDTH_NARROW;
  }
  UNREACHABLE();
}
References v8::internal::JSListFormat::LONG, v8::internal::JSListFormat::NARROW, v8::internal::JSListFormat::SHORT, and v8::internal::UNREACHABLE().
Referenced by v8::internal::JSListFormat::New().
IcuFieldIdToType()
DirectHandle<String> v8::internal::anonymous_namespace{js-list-format.cc}::IcuFieldIdToType (Isolate * isolate, int32_t field_id)
Definition at line 241 of file js-list-format.cc.
                                                                          {
  switch (field_id) {
    case ULISTFMT_LITERAL_FIELD:
      return isolate->factory()->literal_string();
    case ULISTFMT_ELEMENT_FIELD:
      return isolate->factory()->element_string();
    default:
      UNREACHABLE();
  }
}
References v8::internal::Isolate::factory(), and v8::internal::UNREACHABLE().
Referenced by FormattedListToJSArray().
ToUnicodeStringArray()
Maybe<std::vector<icu::UnicodeString> > v8::internal::anonymous_namespace{js-list-format.cc}::ToUnicodeStringArray (Isolate * isolate, DirectHandle< FixedArray > array)
Definition at line 203 of file js-list-format.cc.
                                                      {
  int length = array->length();
  std::vector<icu::UnicodeString> result;
  for (int i = 0; i < length; i++) {
    Handle<Object> item(array->get(i), isolate);
    DCHECK(IsString(*item));
    Handle<String> item_str = Cast<String>(item);
    if (!item_str->IsFlat()) item_str = String::Flatten(isolate, item_str);
    result.push_back(Intl::ToICUUnicodeString(isolate, item_str));
  }
  return Just(result);
}
References v8::internal::DCHECK(), v8::Just(), v8::internal::length, v8::base::internal::result, and v8::internal::Intl::ToICUUnicodeString().
Referenced by FormatListCommon().