v8::internal::torque::anonymous_namespace{implementation-visitor.cc} Namespace Reference
Namespaces
 anonymous_namespace{implementation-visitor.cc}
Classes
class FieldOffsetsGenerator
class ClassFieldOffsetGenerator
class CppClassGenerator
Typedefs
using FieldSections = base::Flags< FieldSectionType >
Enumerations
enum class FieldSectionType : uint32_t { kNoSection = 0
, kWeakSection = 1 << 0
, kStrongSection = 2 << 0
, kScalarSection = 3 << 0
 }
Functions
std::string AddParameter (size_t i, Builtin *builtin, Stack< std::string > *parameters, Stack< const Type * > *parameter_types, BlockBindings< LocalValue > *parameter_bindings, bool mark_as_used)
std::string FormatAssertSource (const std::string &str)
void FailCallableLookup (const std::string &reason, const QualifiedName &name, const TypeVector &parameter_types, const std::vector< Binding< LocalLabel > * > &labels, const std::vector< Signature > &candidates, const std::vector< std::pair< GenericCallable *, std::string >> inapplicable_generics)
Callable * GetOrCreateSpecialization (const SpecializationKey< GenericCallable > &key)
std::pair< std::string, std::string > GetClassInstanceTypeRange (const ClassType *class_type)
bool IsPointerSection (FieldSectionType type)
std::string ToString (FieldSectionType type)
void GenerateClassExport (const ClassType *type, std::ostream &header, std::ostream &inl_header)
std::optional< std::vector< Field > > GetOrderedUniqueIndexFields (const ClassType &type)
void GenerateStructLayoutDescription (std::ostream &header, const StructType *type)
void GeneratePrintDefinitionsForClass (std::ostream &impl, const ClassType *type, const std::string &gen_name, const std::string &gen_name_T, const std::string template_params)
void GenerateFieldValueVerifier (const std::string &class_name, bool indexed, std::string offset, const Field &leaf_field, std::string indexed_field_size, std::ostream &cc_contents, bool is_map)
void GenerateClassFieldVerifier (const std::string &class_name, const ClassType &class_type, const Field &f, std::ostream &h_contents, std::ostream &cc_contents)
void CollectAllFields (const std::string &path, const Field &field, std::vector< std::string > &result)
Variables
const char * BuiltinIncludesMarker = `// __BUILTIN_INCLUDES_MARKER__\n`
Typedef Documentation
FieldSections
using v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::FieldSections = typedef base::Flags<FieldSectionType>
Definition at line 3767 of file implementation-visitor.cc.
Enumeration Type Documentation
FieldSectionType
enum v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::FieldSectionType : uint32_t [strong]
Enumerator
kNoSection
kWeakSection
kStrongSection
kScalarSection
Definition at line 3755 of file implementation-visitor.cc.
                            : uint32_t {
  kNoSection = 0,
  kWeakSection = 1 << 0,
  kStrongSection = 2 << 0,
  kScalarSection = 3 << 0
};
Function Documentation
AddParameter()
std::string v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::AddParameter (size_t i, Builtin * builtin, Stack< std::string > * parameters, Stack< const Type * > * parameter_types, BlockBindings< LocalValue > * parameter_bindings, bool mark_as_used)
Definition at line 570 of file implementation-visitor.cc.
                                            {
  const Identifier* name = builtin->signature().parameter_names[i];
  const Type* type = builtin->signature().types()[i];
  std::string external_name = "parameter" + std::to_string(i);
  parameters->Push(external_name);
  StackRange range = parameter_types->PushMany(LowerType(type));
  Binding<LocalValue>* binding = parameter_bindings->Add(
      name,
      LocalValue{LocationReference::Temporary(VisitResult(type, range),
                                              "parameter " + name->value)},
      mark_as_used);
  if (GlobalContext::collect_kythe_data()) {
    KytheData::AddBindingDefinition(binding);
  }
  return external_name;
}
References v8::internal::torque::BlockBindings< T >::Add(), v8::internal::torque::KytheData::AddBindingDefinition(), v8::internal::torque::GlobalContext::collect_kythe_data(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::torque::LowerType(), v8::internal::name, v8::internal::torque::Signature::parameter_names, v8::internal::torque::Stack< T >::Push(), v8::internal::torque::Stack< T >::PushMany(), v8::internal::torque::Callable::signature(), v8::internal::string, v8::internal::torque::LocationReference::Temporary(), v8::internal::tracing::type, and v8::internal::torque::Signature::types().
Referenced by v8::internal::torque::ImplementationVisitor::Visit().
CollectAllFields()
void v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CollectAllFields (const std::string & path, const Field & field, std::vector< std::string > & result)
Definition at line 5554 of file implementation-visitor.cc.
                                                    {
  if (field.name_and_type.type->StructSupertype()) {
    std::string next_path = path + field.name_and_type.name + ".";
    const StructType* struct_type =
        StructType::DynamicCast(field.name_and_type.type);
    for (const auto& inner_field : struct_type->fields()) {
      CollectAllFields(next_path, inner_field, result);
    }
  } else {
    result.push_back(path + field.name_and_type.name);
  }
}
References v8::internal::torque::AggregateType::fields(), v8::internal::torque::NameAndType::name, v8::internal::torque::Field::name_and_type, v8::base::internal::result, v8::internal::string, and v8::internal::torque::NameAndType::type.
Referenced by v8::internal::torque::ImplementationVisitor::GenerateCSATypes().
FailCallableLookup()
void v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::FailCallableLookup (const std::string & reason, const QualifiedName & name, const TypeVector & parameter_types, const std::vector< Binding< LocalLabel > * > & labels, const std::vector< Signature > & candidates, const std::vector< std::pair< GenericCallable *, std::string >> inapplicable_generics)
Definition at line 1982 of file implementation-visitor.cc.
                               {
  std::stringstream stream;
  stream << "\n" << reason << ": \n " << name << "(" << parameter_types << ")";
  if (!labels.empty()) {
    stream << " labels ";
    for (size_t i = 0; i < labels.size(); ++i) {
      stream << labels[i]->name() << "(" << labels[i]->parameter_types << ")";
    }
  }
  stream << "\ncandidates are:";
  for (const Signature& signature : candidates) {
    stream << "\n " << name;
    PrintSignature(stream, signature, false);
  }
  if (!inapplicable_generics.empty()) {
    stream << "\nfailed to instantiate all of these generic declarations:";
    for (auto& failure : inapplicable_generics) {
      GenericCallable* generic = failure.first;
      const std::string& fail_reason = failure.second;
      stream << "\n " << generic->name() << " defined at "
             << PositionAsString(generic->Position()) << ":\n "
             << fail_reason << "\n";
    }
  }
  ReportError(stream.str());
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::name, v8::internal::torque::PositionAsString(), v8::internal::torque::PrintSignature(), v8::internal::torque::ReportError(), and v8::internal::string.
Referenced by v8::internal::torque::ImplementationVisitor::LookupCallable().
FormatAssertSource()
std::string v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::FormatAssertSource (const std::string & str)
Definition at line 1248 of file implementation-visitor.cc.
                                                   {
  // Replace all whitespace characters with a space character.
  std::string str_no_newlines = str;
  std::replace_if(
      str_no_newlines.begin(), str_no_newlines.end(),
      [](unsigned char c) { return isspace(c); }, ' ');
  // str might include indentation, squash multiple space characters into one.
  std::string result;
  std::unique_copy(str_no_newlines.begin(), str_no_newlines.end(),
                   std::back_inserter(result),
                   [](char a, char b) { return a == ' ' && b == ' '; });
  return result;
}
References v8::base::internal::result, and v8::internal::string.
Referenced by v8::internal::torque::ImplementationVisitor::Visit().
GenerateClassExport()
void v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::GenerateClassExport (const ClassType * type, std::ostream & header, std::ostream & inl_header)
Definition at line 3917 of file implementation-visitor.cc.
                                                 {
  const ClassType* super = type->GetSuperClass();
  std::string parent = "TorqueGenerated" + type->name() + "<" + type->name() +
                       ", " + super->name() + ">";
  header << "class " << type->name() << " : public " << parent << " {\n";
  header << " public:\n";
  if (type->ShouldGenerateBodyDescriptor()) {
    header << " class BodyDescriptor;\n";
  }
  header << " TQ_OBJECT_CONSTRUCTORS(" << type->name() << ")\n";
  header << "};\n\n";
  inl_header << "TQ_OBJECT_CONSTRUCTORS_IMPL(" << type->name() << ")\n";
}
References v8::internal::torque::AggregateType::name(), v8::internal::string, and v8::internal::tracing::type.
GenerateClassFieldVerifier()
void v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::GenerateClassFieldVerifier (const std::string & class_name, const ClassType & class_type, const Field & f, std::ostream & h_contents, std::ostream & cc_contents)
Definition at line 5305 of file implementation-visitor.cc.
                                                         {
  const Type* field_type = f.name_and_type.type;
  // We only verify tagged types, not raw numbers or pointers. Structs
  // consisting of tagged types are also included.
  if (!field_type->IsSubtypeOf(TypeOracle::GetTaggedType()) &&
      !field_type->StructSupertype())
    return;
  // Protected pointer fields cannot be read or verified from torque yet.
  if (field_type->IsSubtypeOf(TypeOracle::GetProtectedPointerType())) return;
  if (field_type == TypeOracle::GetFloat64OrUndefinedOrHoleType()) return;
  std::string field_start_offset;
  if (f.index) {
    field_start_offset = f.name_and_type.name + "__offset";
    std::string length = f.name_and_type.name + "__length";
    cc_contents << " intptr_t " << field_start_offset << ", " << length
                << ";\n";
    cc_contents << " std::tie(std::ignore, " << field_start_offset << ", "
                << length << ") = "
                << Callable::PrefixNameForCCOutput(
                       class_type.GetSliceMacroName(f))
                << "(o);\n";
    // Slices use intptr, but TaggedField<T>.load() uses int, so verify that
    // such a cast is valid.
    cc_contents << " CHECK_EQ(" << field_start_offset << ", static_cast<int>("
                << field_start_offset << "));\n";
    cc_contents << " CHECK_EQ(" << length << ", static_cast<int>(" << length
                << "));\n";
    field_start_offset = "static_cast<int>(" + field_start_offset + ")";
    length = "static_cast<int>(" + length + ")";
    cc_contents << " for (int i = 0; i < " << length << "; ++i) {\n";
  } else {
    // Non-indexed fields have known offsets.
    field_start_offset = std::to_string(*f.offset);
    cc_contents << " {\n";
  }
  if (auto struct_type = field_type->StructSupertype()) {
    for (const Field& struct_field : (*struct_type)->fields()) {
      if (struct_field.name_and_type.type->IsSubtypeOf(
              TypeOracle::GetTaggedType())) {
        GenerateFieldValueVerifier(
            class_name, f.index.has_value(),
            field_start_offset + " + " + std::to_string(*struct_field.offset),
            struct_field, std::to_string((*struct_type)->PackedSize()),
            cc_contents, f.name_and_type.name == "map");
      }
    }
  } else {
    GenerateFieldValueVerifier(class_name, f.index.has_value(),
                               field_start_offset, f, "kTaggedSize",
                               cc_contents, f.name_and_type.name == "map");
  }
  cc_contents << " }\n";
}
References GenerateFieldValueVerifier(), v8::internal::torque::ClassType::GetSliceMacroName(), v8::internal::torque::Field::index, v8::internal::torque::Type::IsSubtypeOf(), v8::internal::length, v8::internal::torque::NameAndType::name, v8::internal::torque::Field::name_and_type, v8::internal::torque::Field::offset, v8::internal::string, v8::internal::torque::Type::StructSupertype(), and v8::internal::torque::NameAndType::type.
Referenced by v8::internal::torque::ImplementationVisitor::GenerateClassVerifiers().
GenerateFieldValueVerifier()
void v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::GenerateFieldValueVerifier (const std::string & class_name, bool indexed, std::string offset, const Field & leaf_field, std::string indexed_field_size, std::ostream & cc_contents, bool is_map)
Definition at line 5264 of file implementation-visitor.cc.
                                                                      {
  const Type* field_type = leaf_field.name_and_type.type;
  bool maybe_object =
      !field_type->IsSubtypeOf(TypeOracle::GetStrongTaggedType());
  const char* object_type = maybe_object ? "MaybeObject" : "Object";
  const char* tagged_object_type =
      maybe_object ? "Tagged<MaybeObject>" : "Tagged<Object>";
  const char* verify_fn =
      maybe_object ? "VerifyMaybeObjectPointer" : "VerifyPointer";
  if (indexed) {
    offset += " + i * " + indexed_field_size;
  }
  // Name the local var based on the field name for nicer CHECK output.
  const std::string value = leaf_field.name_and_type.name + "__value";
  // Read the field.
  if (is_map) {
    cc_contents << " " << tagged_object_type << " " << value
                << " = o->map();\n";
  } else {
    cc_contents << " " << tagged_object_type << " " << value
                << " = TaggedField<" << object_type << ">::load(o, " << offset
                << ");\n";
  }
  // Call VerifyPointer or VerifyMaybeObjectPointer on it.
  cc_contents << " Object::" << verify_fn << "(isolate, " << value << ");\n";
  // Check that the value is of an appropriate type. We can skip this part for
  // the Object type because it would not check anything beyond what we already
  // checked with VerifyPointer.
  if (field_type != TypeOracle::GetObjectType()) {
    cc_contents << " CHECK(" << GenerateRuntimeTypeCheck(field_type, value)
                << ");\n";
  }
}
References v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::anonymous_namespace{implementation-visitor.cc}::GenerateRuntimeTypeCheck(), v8::internal::torque::Type::IsSubtypeOf(), v8::internal::torque::NameAndType::name, v8::internal::torque::Field::name_and_type, v8::internal::string, v8::internal::torque::NameAndType::type, and v8::internal::value.
Referenced by GenerateClassFieldVerifier().
GeneratePrintDefinitionsForClass()
void v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::GeneratePrintDefinitionsForClass (std::ostream & impl, const ClassType * type, const std::string & gen_name, const std::string & gen_name_T, const std::string template_params)
Definition at line 5014 of file implementation-visitor.cc.
                                                                       {
  impl << template_params << "\n";
  impl << "void " << gen_name_T << "::" << type->name()
       << "Print(std::ostream& os) {\n";
  impl << " this->PrintHeader(os, \"" << type->name() << "\");\n";
  auto hierarchy = type->GetHierarchy();
  std::map<std::string, const AggregateType*> field_names;
  for (const AggregateType* aggregate_type : hierarchy) {
    for (const Field& f : aggregate_type->fields()) {
      if (f.name_and_type.name == "map" || f.index.has_value() ||
          !CanGenerateFieldAccessors(f.name_and_type.type)) {
        continue;
      }
      std::string getter = f.name_and_type.name;
      if (aggregate_type != type) {
        // We must call getters directly on the class that provided them,
        // because a subclass could have hidden them.
        getter = aggregate_type->name() + "::TorqueGeneratedClass::" + getter;
      }
      if (f.name_and_type.type->IsSubtypeOf(TypeOracle::GetSmiType()) ||
          !f.name_and_type.type->IsSubtypeOf(TypeOracle::GetTaggedType())) {
        impl << " os << \"\\n - " << f.name_and_type.name << ": \" << ";
        if (f.name_and_type.type->StructSupertype()) {
          // TODO(turbofan): Print struct fields too.
          impl << "\" <struct field printing still unimplemented>\";\n";
        } else {
          impl << "this->" << getter;
          switch (f.synchronization) {
            case FieldSynchronization::kNone:
              impl << "();\n";
              break;
            case FieldSynchronization::kRelaxed:
              impl << "(kRelaxedLoad);\n";
              break;
            case FieldSynchronization::kAcquireRelease:
              impl << "(kAcquireLoad);\n";
              break;
          }
        }
      } else {
        impl << " os << \"\\n - " << f.name_and_type.name << ": \" << "
             << "Brief(this->" << getter;
        switch (f.synchronization) {
          case FieldSynchronization::kNone:
            impl << "());\n";
            break;
          case FieldSynchronization::kRelaxed:
            impl << "(kRelaxedLoad));\n";
            break;
          case FieldSynchronization::kAcquireRelease:
            impl << "(kAcquireLoad));\n";
            break;
        }
      }
    }
  }
  impl << " os << '\\n';\n";
  impl << "}\n\n";
}
References v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::anonymous_namespace{implementation-visitor.cc}::CanGenerateFieldAccessors(), wasm::impl(), v8::internal::string, and v8::internal::tracing::type.
Referenced by v8::internal::torque::ImplementationVisitor::GeneratePrintDefinitions().
GenerateStructLayoutDescription()
void v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::GenerateStructLayoutDescription (std::ostream & header, const StructType * type)
Definition at line 4822 of file implementation-visitor.cc.
                                                             {
  header << "struct TorqueGenerated" << CamelifyString(type->name())
         << "Offsets {\n";
  for (const Field& field : type->fields()) {
    header << " static constexpr int k"
           << CamelifyString(field.name_and_type.name)
           << "Offset = " << *field.offset << ";\n";
  }
  header << " static constexpr int kSize = " << type->PackedSize() << ";\n";
  header << "};\n\n";
}
References v8::internal::torque::CamelifyString(), and v8::internal::tracing::type.
Referenced by v8::internal::torque::ImplementationVisitor::GenerateClassDefinitions().
GetClassInstanceTypeRange()
std::pair<std::string, std::string> v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::GetClassInstanceTypeRange (const ClassType * class_type)
Definition at line 2762 of file implementation-visitor.cc.
                                 {
  std::pair<std::string, std::string> result;
  if (class_type->InstanceTypeRange()) {
    auto instance_type_range = *class_type->InstanceTypeRange();
    std::string instance_type_string_first =
        "static_cast<InstanceType>(" +
        std::to_string(instance_type_range.first) + ")";
    std::string instance_type_string_second =
        "static_cast<InstanceType>(" +
        std::to_string(instance_type_range.second) + ")";
    result =
        std::make_pair(instance_type_string_first, instance_type_string_second);
  } else {
    ReportError(
        "%Min/MaxInstanceType must take a class type that is either a string "
        "or has a generated instance type range");
  }
  return result;
}
References v8::internal::torque::ClassType::InstanceTypeRange(), v8::internal::torque::ReportError(), v8::base::internal::result, and v8::internal::string.
Referenced by v8::internal::torque::ImplementationVisitor::GenerateCall().
GetOrCreateSpecialization()
Callable* v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::GetOrCreateSpecialization (const SpecializationKey< GenericCallable > & key)
Definition at line 2015 of file implementation-visitor.cc.
                                                   {
  if (std::optional<Callable*> specialization =
          key.generic->GetSpecialization(key.specialized_types)) {
    return *specialization;
  }
  return DeclarationVisitor::SpecializeImplicit(key);
}
References v8::internal::key, and v8::internal::torque::DeclarationVisitor::SpecializeImplicit().
Referenced by v8::internal::torque::ImplementationVisitor::GetLocationReference(), and v8::internal::torque::ImplementationVisitor::LookupCallable().
GetOrderedUniqueIndexFields()
std::optional<std::vector<Field> > v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::GetOrderedUniqueIndexFields (const ClassType & type)
Definition at line 4155 of file implementation-visitor.cc.
                           {
  std::vector<Field> result;
  std::set<std::string> index_names;
  for (const Field& field : type.ComputeAllFields()) {
    if (field.index) {
      auto name_and_type = ExtractSimpleFieldArraySize(type, field.index->expr);
      if (!name_and_type) {
        return std::nullopt;
      }
      index_names.insert(name_and_type->name);
    }
  }
  for (const Field& field : type.ComputeAllFields()) {
    if (index_names.count(field.name_and_type.name) != 0) {
      result.push_back(field);
    }
  }
  return result;
}
References v8::internal::torque::ExtractSimpleFieldArraySize(), v8::base::internal::result, and v8::internal::tracing::type.
Referenced by v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::GenerateClass(), and v8::internal::torque::ImplementationVisitor::GenerateClassDefinitions().
IsPointerSection()
bool v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::IsPointerSection (FieldSectionType type)
Definition at line 3762 of file implementation-visitor.cc.
                                             {
  return type == FieldSectionType::kWeakSection ||
         type == FieldSectionType::kStrongSection;
}
References v8::internal::tracing::type.
Referenced by v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::FieldOffsetsGenerator::Begin(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::FieldOffsetsGenerator::End(), and v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::FieldOffsetsGenerator::UpdateSection().
ToString()
std::string v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::ToString (FieldSectionType type)
Definition at line 3769 of file implementation-visitor.cc.
                                          {
  switch (type) {
    case FieldSectionType::kNoSection:
      return "NoSection";
    case FieldSectionType::kWeakSection:
      return "WeakFields";
    case FieldSectionType::kStrongSection:
      return "StrongFields";
    case FieldSectionType::kScalarSection:
      return "ScalarFields";
  }
  UNREACHABLE();
}
References v8::internal::tracing::type, and v8::internal::UNREACHABLE().
Variable Documentation
BuiltinIncludesMarker
const char* v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::BuiltinIncludesMarker = `// __BUILTIN_INCLUDES_MARKER__\n`
Definition at line 41 of file implementation-visitor.cc.
Referenced by v8::internal::torque::ImplementationVisitor::BeginGeneratedFiles(), and v8::internal::torque::ImplementationVisitor::GenerateImplementation().