v8_inspector::anonymous_namespace{v8-console.cc} Namespace Reference
Classes
class ConsoleHelper
Enumerations
enum InspectRequest { kRegular
, kCopyToClipboard
, kQueryObjects
 }
Functions
String16 consoleContextToString (v8::Isolate *isolate, const v8::debug::ConsoleContext &consoleContext)
void createBoundFunctionProperty (v8::Local< v8::Context > context, v8::Local< v8::Object > console, v8::Local< v8::Value > data, const char *name, v8::FunctionCallback callback, v8::SideEffectType side_effect_type=v8::SideEffectType::kHasSideEffect)
void cleanupTaskInfo (const v8::WeakCallbackInfo< TaskInfo > &info)
DEFINE_LAZY_LEAKY_OBJECT_GETTER (std::set< std::string_view >, UnsafeCommandLineAPIFns, std::initializer_list< std::string_view >{ `debug`, `undebug`, `monitor`, `unmonitor`, `inspect`, `copy`, `queryObjects`}) bool IsUnsafeCommandLineAPIFn(v8
Enumeration Type Documentation
InspectRequest
enum v8_inspector::anonymous_namespace{v8-console.cc}::InspectRequest
Enumerator
kRegular
kCopyToClipboard
kQueryObjects
Definition at line 218 of file v8-console.cc.
{ kRegular, kCopyToClipboard, kQueryObjects };
Function Documentation
cleanupTaskInfo()
void v8_inspector::anonymous_namespace{v8-console.cc}::cleanupTaskInfo (const v8::WeakCallbackInfo< TaskInfo > & info)
Definition at line 600 of file v8-console.cc.
                                                               {
  TaskInfo* task = info.GetParameter();
  CHECK(task);
  task->Cancel();
}
References v8_inspector::TaskInfo::Cancel(), CHECK, and v8::WeakCallbackInfo< T >::GetParameter().
Referenced by v8_inspector::TaskInfo::TaskInfo().
consoleContextToString()
String16 v8_inspector::anonymous_namespace{v8-console.cc}::consoleContextToString (v8::Isolate * isolate, const v8::debug::ConsoleContext & consoleContext)
Definition at line 35 of file v8-console.cc.
                                                                     {
  if (consoleContext.id() == 0) return String16();
  return toProtocolString(isolate, consoleContext.name()) + "#" +
         String16::fromInteger(consoleContext.id());
}
References v8_inspector::String16::fromInteger(), v8::debug::ConsoleContext::id(), v8::debug::ConsoleContext::name(), and v8_inspector::toProtocolString().
Referenced by v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::reportCall().
createBoundFunctionProperty()
void v8_inspector::anonymous_namespace{v8-console.cc}::createBoundFunctionProperty (v8::Local< v8::Context > context, v8::Local< v8::Object > console, v8::Local< v8::Value > data, const char * name, v8::FunctionCallback callback, v8::SideEffectType side_effect_type = v8::SideEffectType::kHasSideEffect)
Definition at line 203 of file v8-console.cc.
                                                                        {
  v8::Local<v8::String> funcName =
      toV8StringInternalized(v8::Isolate::GetCurrent(), name);
  v8::Local<v8::Function> func;
  if (!v8::Function::New(context, callback, data, 0,
                         v8::ConstructorBehavior::kThrow, side_effect_type)
           .ToLocal(&func))
    return;
  func->SetName(funcName);
  createDataProperty(context, console, funcName, func);
}
References v8_inspector::createDataProperty(), v8::Isolate::GetCurrent(), v8::kThrow, name, v8::Function::New(), and v8_inspector::toV8StringInternalized().
Referenced by v8_inspector::V8Console::createCommandLineAPI(), and v8_inspector::V8Console::installAsyncStackTaggingAPI().
DEFINE_LAZY_LEAKY_OBJECT_GETTER()
v8_inspector::anonymous_namespace{v8-console.cc}::DEFINE_LAZY_LEAKY_OBJECT_GETTER (std::set< std::string_view > , UnsafeCommandLineAPIFns , std::initializer_list< std::string_view >{ `debug`, `undebug`, `monitor`, `unmonitor`, `inspect`, `copy`, `queryObjects`})
Definition at line 989 of file v8-console.cc.
                                                                   {
                                    "debug", "undebug", "monitor", "unmonitor",
                                    "inspect", "copy", "queryObjects"})
bool IsUnsafeCommandLineAPIFn(v8::Local<v8::Value> name, v8::Isolate* isolate) {
  std::string nameStr = toProtocolStringWithTypeCheck(isolate, name).utf8();
  return UnsafeCommandLineAPIFns()->count(nameStr) > 0;
}