v8_inspector::anonymous_namespace{remote-object-id.cc} Namespace Reference
Functions
String16 serializeId (uint64_t isolateId, int injectedScriptId, int id)
Function Documentation
serializeId()
String16 v8_inspector::anonymous_namespace{remote-object-id.cc}::serializeId (uint64_t isolateId, int injectedScriptId, int id)
Definition at line 15 of file remote-object-id.cc.
                                                                       {
  return String16::concat(
      String16::fromInteger64(static_cast<int64_t>(isolateId)), ".",
      String16::fromInteger(injectedScriptId), ".", String16::fromInteger(id));
}
References v8_inspector::String16::concat(), v8_inspector::String16::fromInteger(), and v8_inspector::String16::fromInteger64().
Referenced by v8_inspector::RemoteCallFrameId::serialize(), and v8_inspector::RemoteObjectId::serialize().