v8::internal::anonymous_namespace{runtime-strings.cc} Namespace Reference
Typedefs
using ASVariant = AddStringConstantAndInternalizeVariant
Functions
Tagged< Object > StringAdd_StringConstant_Internalize (Isolate *isolate, DirectHandle< Object > lhs, DirectHandle< Object > rhs, Handle< HeapObject > maybe_feedback_vector, int slot_index, ASVariant as_variant)
Typedef Documentation
ASVariant
using v8::internal::anonymous_namespace{runtime-strings.cc}::ASVariant = typedef AddStringConstantAndInternalizeVariant
Definition at line 169 of file runtime-strings.cc.
Function Documentation
StringAdd_StringConstant_Internalize()
Tagged<Object> v8::internal::anonymous_namespace{runtime-strings.cc}::StringAdd_StringConstant_Internalize (Isolate * isolate, DirectHandle< Object > lhs, DirectHandle< Object > rhs, Handle< HeapObject > maybe_feedback_vector, int slot_index, ASVariant as_variant)
Definition at line 171 of file runtime-strings.cc.
                          {
  const bool lhs_is_string_constant =
      as_variant == ASVariant::kLhsIsStringConstant;
  DirectHandle<Object> const_str_operand = lhs_is_string_constant ? lhs : rhs;
  DirectHandle<Object> other_operand = lhs_is_string_constant ? rhs : lhs;
  DCHECK(IsInternalizedString(*const_str_operand));
  DirectHandle<String> other_operand_string;
  if (IsString(*other_operand)) {
    other_operand_string = Cast<String>(other_operand);
  } else {
    // According to spec we first have to do ToPrimitive and only then
    // ToString.
    // https://tc39.es/ecma262/#sec-applystringornumericbinaryoperator
    ASSIGN_RETURN_FAILURE_ON_EXCEPTION(
        isolate, other_operand, Object::ToPrimitive(isolate, other_operand));
    ASSIGN_RETURN_FAILURE_ON_EXCEPTION(
        isolate, other_operand_string,
        Object::ToString(isolate, other_operand));
  }
  auto f = isolate->factory();
  auto other_operand_internalize =
      IsInternalizedString(*other_operand_string)
          ? Cast<InternalizedString>(other_operand_string)
          : f->InternalizeString(other_operand_string);
  auto lhs_internalize = lhs_is_string_constant
                             ? Cast<String>(const_str_operand)
                             : Cast<String>(other_operand_internalize);
  auto rhs_internalize = lhs_is_string_constant
                             ? Cast<String>(other_operand_internalize)
                             : Cast<String>(const_str_operand);
  if (IsUndefined(*maybe_feedback_vector)) {
    DirectHandle<String> cons;
    ASSIGN_RETURN_FAILURE_ON_EXCEPTION(
        isolate, cons, f->NewConsString(lhs_internalize, rhs_internalize));
    return *f->InternalizeString(cons);
  }
  auto feedback_vector = Cast<FeedbackVector>(maybe_feedback_vector);
  FeedbackSlot cache_slot(FeedbackVector::ToSlot(
      slot_index + kAdd_StringConstant_Internalize_CacheSlotOffset));
  DCHECK_LT(cache_slot.ToInt(), feedback_vector->length());
  Handle<Object> cache_obj(Cast<Object>(feedback_vector->Get(cache_slot)),
                           isolate);
  Handle<SimpleNameDictionary> cache;
  if (*cache_obj == ReadOnlyRoots{isolate}.uninitialized_symbol()) {
    cache = SimpleNameDictionary::New(isolate, 1);
    feedback_vector->SynchronizedSet(cache_slot, *cache);
  } else {
    cache = Cast<SimpleNameDictionary>(cache_obj);
  }
  InternalIndex entry = cache->FindEntry(isolate, other_operand_internalize);
  if (entry.is_found()) {
    auto result = cache->ValueAt(entry);
    DCHECK(IsInternalizedString(result));
    return result;
  }
  DirectHandle<String> cons;
  ASSIGN_RETURN_FAILURE_ON_EXCEPTION(
      isolate, cons, f->NewConsString(lhs_internalize, rhs_internalize));
  auto internalized = f->InternalizeString(cons);
  auto new_cache = SimpleNameDictionary::Set(
      isolate, cache, other_operand_internalize, internalized);
  if (*new_cache != *cache) {
    feedback_vector->SynchronizedSet(cache_slot, *new_cache);
  }
  return *internalized;
}
References ASSIGN_RETURN_FAILURE_ON_EXCEPTION, v8::internal::DCHECK(), DCHECK_LT, v8::internal::Isolate::factory(), v8::internal::InternalIndex::is_found(), v8::internal::InstanceTypeChecker::IsInternalizedString(), v8::kAdd_StringConstant_Internalize_CacheSlotOffset, v8::internal::anonymous_namespace{intl-objects.cc}::New(), v8::base::internal::result, v8::internal::SimpleNameDictionary::Set(), v8::internal::FeedbackSlot::ToInt(), v8::Value::ToPrimitive(), v8::internal::FeedbackVector::ToSlot(), and v8::Value::ToString().
Referenced by v8::internal::RUNTIME_FUNCTION().