v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc} Namespace Reference
Functions
template<Bytecode bytecode, OperandType operand_type, size_t i>
void UpdateInLivenessForOutOperand (BytecodeLivenessState *in_liveness, const interpreter::BytecodeArrayIterator &iterator)
template<Bytecode bytecode, OperandType operand_type, size_t i>
void UpdateInLivenessForInOperand (BytecodeLivenessState *in_liveness, const interpreter::BytecodeArrayIterator &iterator)
template<Bytecode bytecode, ImplicitRegisterUse implicit_register_use, OperandType... operand_types, size_t... operand_index>
void UpdateInLiveness (BytecodeLivenessState *in_liveness, const interpreter::BytecodeArrayIterator &iterator, std::index_sequence< operand_index... >)
template<Bytecode bytecode, ImplicitRegisterUse implicit_register_use, OperandType... operand_types>
void UpdateInLiveness (BytecodeLivenessState *in_liveness, const interpreter::BytecodeArrayIterator &iterator)
template<bool IsFirstUpdate = false>
void EnsureOutLivenessIsNotAlias (BytecodeLiveness &liveness, BytecodeLivenessState *next_bytecode_in_liveness, Zone *zone)
template<bool IsFirstUpdate, Bytecode bytecode>
void UpdateOutLiveness (BytecodeLiveness &liveness, BytecodeLivenessState *next_bytecode_in_liveness, const interpreter::BytecodeArrayIterator &iterator, DirectHandle< BytecodeArray > bytecode_array, const BytecodeLivenessMap &liveness_map, Zone *zone)
template<bool IsFirstUpdate = false>
void UpdateOutLiveness (Bytecode bytecode, BytecodeLiveness &liveness, BytecodeLivenessState *next_bytecode_in_liveness, const interpreter::BytecodeArrayIterator &iterator, DirectHandle< BytecodeArray > bytecode_array, const BytecodeLivenessMap &liveness_map, Zone *zone)
template<bool IsFirstUpdate, Bytecode bytecode, ImplicitRegisterUse implicit_register_use, OperandType... operand_types>
void UpdateLiveness (BytecodeLiveness &liveness, BytecodeLivenessState **next_bytecode_in_liveness, const interpreter::BytecodeArrayIterator &iterator, DirectHandle< BytecodeArray > bytecode_array, const BytecodeLivenessMap &liveness_map, Zone *zone)
template<bool IsFirstUpdate = false>
void UpdateLiveness (Bytecode bytecode, BytecodeLiveness &liveness, BytecodeLivenessState **next_bytecode_in_liveness, const interpreter::BytecodeArrayIterator &iterator, DirectHandle< BytecodeArray > bytecode_array, const BytecodeLivenessMap &liveness_map, Zone *zone)
void UpdateAssignments (Bytecode bytecode, BytecodeLoopAssignments *assignments, const interpreter::BytecodeArrayIterator &iterator)
Function Documentation
EnsureOutLivenessIsNotAlias()
template<bool IsFirstUpdate = false>
void v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::EnsureOutLivenessIsNotAlias (BytecodeLiveness & liveness, BytecodeLivenessState * next_bytecode_in_liveness, Zone * zone)
Definition at line 227 of file bytecode-analysis.cc.
                                                                  {
  if (!IsFirstUpdate) {
    // We should have copied the next bytecode's in liveness already in the
    // first pass, so on subsequent passes this should already not be an alias.
    DCHECK_NE(liveness.out, next_bytecode_in_liveness);
    return;
  }
  if (liveness.out == next_bytecode_in_liveness) {
    // If the out-liveness is aliasing the next bytecode's in-liveness,
    // reallocate it and copy the data to the newly allocated state.
    liveness.out =
        zone->New<BytecodeLivenessState>(*next_bytecode_in_liveness, zone);
  }
}
References DCHECK_NE, v8::internal::Zone::New(), and v8::internal::compiler::BytecodeLiveness::out.
UpdateAssignments()
void v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateAssignments (Bytecode bytecode, BytecodeLoopAssignments * assignments, const interpreter::BytecodeArrayIterator & iterator)
Definition at line 418 of file bytecode-analysis.cc.
                                                                         {
  int num_operands = Bytecodes::NumberOfOperands(bytecode);
  const OperandType* operand_types = Bytecodes::GetOperandTypes(bytecode);
  for (int i = 0; i < num_operands; ++i) {
    switch (operand_types[i]) {
      case OperandType::kRegInOut:
      case OperandType::kRegOut: {
        assignments->Add(iterator.GetRegisterOperand(i));
        break;
      }
      case OperandType::kRegOutList: {
        interpreter::Register r = iterator.GetRegisterOperand(i++);
        uint32_t reg_count = iterator.GetRegisterCountOperand(i);
        assignments->AddList(r, reg_count);
        break;
      }
      case OperandType::kRegOutPair: {
        assignments->AddList(iterator.GetRegisterOperand(i), 2);
        break;
      }
      case OperandType::kRegOutTriple: {
        assignments->AddList(iterator.GetRegisterOperand(i), 3);
        break;
      }
      default:
        DCHECK(!Bytecodes::IsRegisterOutputOperandType(operand_types[i]));
        break;
    }
  }
  if (Bytecodes::WritesImplicitRegister(bytecode)) {
    assignments->Add(interpreter::Register::FromShortStar(bytecode));
  }
}
References v8::internal::compiler::BytecodeLoopAssignments::Add(), v8::internal::compiler::BytecodeLoopAssignments::AddList(), v8::internal::DCHECK(), v8::internal::interpreter::Register::FromShortStar(), v8::internal::interpreter::Bytecodes::GetOperandTypes(), v8::internal::interpreter::BytecodeArrayIterator::GetRegisterCountOperand(), v8::internal::interpreter::BytecodeArrayIterator::GetRegisterOperand(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::interpreter::Bytecodes::IsRegisterOutputOperandType(), v8::internal::interpreter::Bytecodes::NumberOfOperands(), and v8::internal::interpreter::Bytecodes::WritesImplicitRegister().
Referenced by v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::Analyze().
UpdateInLiveness() [1/2]
template<Bytecode bytecode, ImplicitRegisterUse implicit_register_use, OperandType... operand_types>
void v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateInLiveness (BytecodeLivenessState * in_liveness, const interpreter::BytecodeArrayIterator & iterator)
Definition at line 205 of file bytecode-analysis.cc.
                                                                        {
  UpdateInLiveness<bytecode, implicit_register_use, operand_types...>(
      in_liveness, iterator,
      std::make_index_sequence<sizeof...(operand_types)>());
}
Referenced by UpdateLiveness().
UpdateInLiveness() [2/2]
template<Bytecode bytecode, ImplicitRegisterUse implicit_register_use, OperandType... operand_types, size_t... operand_index>
void v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateInLiveness (BytecodeLivenessState * in_liveness, const interpreter::BytecodeArrayIterator & iterator, std::index_sequence< operand_index... >)
Definition at line 163 of file bytecode-analysis.cc.
                                                           {
  // Special case Suspend and Resume to just pass through liveness.
  if constexpr (bytecode == Bytecode::kSuspendGenerator) {
    // The generator object has to be live.
    in_liveness->MarkRegisterLive(iterator.GetRegisterOperand(0).index());
    // Suspend additionally reads and returns the accumulator
    DCHECK(Bytecodes::ReadsAccumulator(bytecode));
    in_liveness->MarkAccumulatorLive();
    return;
  } else if constexpr (bytecode == Bytecode::kResumeGenerator) {
    // The generator object has to be live.
    in_liveness->MarkRegisterLive(iterator.GetRegisterOperand(0).index());
    return;
  }
  // Otherwise, walk all accumulator and register writes and reads.
  if constexpr (BytecodeOperands::WritesAccumulator(implicit_register_use)) {
    in_liveness->MarkAccumulatorDead();
  }
  DCHECK_IMPLIES(BytecodeOperands::ClobbersAccumulator(implicit_register_use),
                 !in_liveness->AccumulatorIsLive());
  (UpdateInLivenessForOutOperand<bytecode, operand_types, operand_index>(
       in_liveness, iterator),
   ...);
  if constexpr (BytecodeOperands::WritesImplicitRegister(
                    implicit_register_use)) {
    in_liveness->MarkRegisterDead(Register::FromShortStar(bytecode).index());
  }
  if constexpr (BytecodeOperands::ReadsAccumulator(implicit_register_use)) {
    in_liveness->MarkAccumulatorLive();
  }
  (UpdateInLivenessForInOperand<bytecode, operand_types, operand_index>(
       in_liveness, iterator),
   ...);
}
References v8::internal::compiler::BytecodeLivenessState::AccumulatorIsLive(), v8::internal::interpreter::BytecodeOperands::ClobbersAccumulator(), v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::interpreter::Register::FromShortStar(), v8::internal::interpreter::BytecodeArrayIterator::GetRegisterOperand(), v8::internal::interpreter::Register::index(), v8::internal::index, v8::internal::compiler::BytecodeLivenessState::MarkAccumulatorDead(), v8::internal::compiler::BytecodeLivenessState::MarkAccumulatorLive(), v8::internal::compiler::BytecodeLivenessState::MarkRegisterDead(), v8::internal::compiler::BytecodeLivenessState::MarkRegisterLive(), v8::internal::interpreter::Bytecodes::ReadsAccumulator(), v8::internal::interpreter::BytecodeOperands::ReadsAccumulator(), v8::internal::interpreter::BytecodeOperands::WritesAccumulator(), and v8::internal::interpreter::BytecodeOperands::WritesImplicitRegister().
UpdateInLivenessForInOperand()
template<Bytecode bytecode, OperandType operand_type, size_t i>
void v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateInLivenessForInOperand (BytecodeLivenessState * in_liveness, const interpreter::BytecodeArrayIterator & iterator)
Definition at line 131 of file bytecode-analysis.cc.
                                                      {
  if constexpr (operand_type == OperandType::kReg ||
                operand_type == OperandType::kRegInOut) {
    Register r = iterator.GetRegisterOperand(i);
    if (!r.is_parameter()) {
      in_liveness->MarkRegisterLive(r.index());
    }
  } else if constexpr (operand_type == OperandType::kRegPair) {
    Register r = iterator.GetRegisterOperand(i);
    if (!r.is_parameter()) {
      DCHECK(!Register(r.index() + 1).is_parameter());
      in_liveness->MarkRegisterLive(r.index());
      in_liveness->MarkRegisterLive(r.index() + 1);
    }
  } else if constexpr (operand_type == OperandType::kRegList) {
    Register r = iterator.GetRegisterOperand(i);
    uint32_t reg_count = iterator.GetRegisterCountOperand(i + 1);
    if (!r.is_parameter()) {
      for (uint32_t j = 0; j < reg_count; ++j) {
        DCHECK(!interpreter::Register(r.index() + j).is_parameter());
        in_liveness->MarkRegisterLive(r.index() + j);
      }
    }
  } else {
    DCHECK(!Bytecodes::IsRegisterInputOperandType(operand_type));
  }
}
References v8::internal::DCHECK(), v8::internal::interpreter::BytecodeArrayIterator::GetRegisterCountOperand(), v8::internal::interpreter::BytecodeArrayIterator::GetRegisterOperand(), v8::internal::interpreter::Register::index(), v8::internal::interpreter::Register::is_parameter(), v8::internal::interpreter::Bytecodes::IsRegisterInputOperandType(), v8::internal::compiler::BytecodeLivenessState::MarkRegisterLive(), and v8::internal::ETWJITInterface::Register().
UpdateInLivenessForOutOperand()
template<Bytecode bytecode, OperandType operand_type, size_t i>
void v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateInLivenessForOutOperand (BytecodeLivenessState * in_liveness, const interpreter::BytecodeArrayIterator & iterator)
Definition at line 91 of file bytecode-analysis.cc.
                                                      {
  if constexpr (operand_type == OperandType::kRegOut ||
                operand_type == OperandType::kRegInOut) {
    Register r = iterator.GetRegisterOperand(i);
    if (!r.is_parameter()) {
      in_liveness->MarkRegisterDead(r.index());
    }
  } else if constexpr (operand_type == OperandType::kRegOutList) {
    Register r = iterator.GetRegisterOperand(i);
    uint32_t reg_count = iterator.GetRegisterCountOperand(i + 1);
    if (!r.is_parameter()) {
      for (uint32_t j = 0; j < reg_count; ++j) {
        DCHECK(!Register(r.index() + j).is_parameter());
        in_liveness->MarkRegisterDead(r.index() + j);
      }
    }
  } else if constexpr (operand_type == OperandType::kRegOutPair) {
    Register r = iterator.GetRegisterOperand(i);
    if (!r.is_parameter()) {
      DCHECK(!Register(r.index() + 1).is_parameter());
      in_liveness->MarkRegisterDead(r.index());
      in_liveness->MarkRegisterDead(r.index() + 1);
    }
  } else if constexpr (operand_type == OperandType::kRegOutTriple) {
    Register r = iterator.GetRegisterOperand(i);
    if (!r.is_parameter()) {
      DCHECK(!Register(r.index() + 1).is_parameter());
      DCHECK(!Register(r.index() + 2).is_parameter());
      in_liveness->MarkRegisterDead(r.index());
      in_liveness->MarkRegisterDead(r.index() + 1);
      in_liveness->MarkRegisterDead(r.index() + 2);
    }
  } else {
    DCHECK(!Bytecodes::IsRegisterOutputOperandType(operand_type));
  }
}
References v8::internal::DCHECK(), v8::internal::interpreter::BytecodeArrayIterator::GetRegisterCountOperand(), v8::internal::interpreter::BytecodeArrayIterator::GetRegisterOperand(), v8::internal::interpreter::Register::index(), v8::internal::interpreter::Register::is_parameter(), v8::internal::interpreter::Bytecodes::IsRegisterOutputOperandType(), v8::internal::compiler::BytecodeLivenessState::MarkRegisterDead(), and v8::internal::ETWJITInterface::Register().
UpdateLiveness() [1/2]
template<bool IsFirstUpdate = false>
void v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateLiveness (Bytecode bytecode, BytecodeLiveness & liveness, BytecodeLivenessState ** next_bytecode_in_liveness, const interpreter::BytecodeArrayIterator & iterator, DirectHandle< BytecodeArray > bytecode_array, const BytecodeLivenessMap & liveness_map, Zone * zone)
Definition at line 402 of file bytecode-analysis.cc.
                                                                         {
  switch (bytecode) {
#define BYTECODE_UPDATE_LIVENESS(Name, ...) \
  case Bytecode::k##Name: \
    return UpdateLiveness<IsFirstUpdate, Bytecode::k##Name, __VA_ARGS__>(\
        liveness, next_bytecode_in_liveness, iterator, bytecode_array, \
        liveness_map, zone);
    BYTECODE_LIST(BYTECODE_UPDATE_LIVENESS, BYTECODE_UPDATE_LIVENESS)
#undef BYTECODE_UPDATE_LIVENESS
  }
}
References BYTECODE_LIST, and BYTECODE_UPDATE_LIVENESS.
Referenced by v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::Analyze().
UpdateLiveness() [2/2]
template<bool IsFirstUpdate, Bytecode bytecode, ImplicitRegisterUse implicit_register_use, OperandType... operand_types>
void v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateLiveness (BytecodeLiveness & liveness, BytecodeLivenessState ** next_bytecode_in_liveness, const interpreter::BytecodeArrayIterator & iterator, DirectHandle< BytecodeArray > bytecode_array, const BytecodeLivenessMap & liveness_map, Zone * zone)
Definition at line 376 of file bytecode-analysis.cc.
                                                                         {
  UpdateOutLiveness<IsFirstUpdate, bytecode>(
      liveness, *next_bytecode_in_liveness, iterator, bytecode_array,
      liveness_map, zone);
  if (IsFirstUpdate) {
    // On the first update, allocate the in-liveness as a copy of the
    // out-liveness.
    DCHECK_NULL(liveness.in);
    liveness.in = zone->New<BytecodeLivenessState>(*liveness.out, zone);
  } else {
    // On subsequent updates, copy liveness from the out vector.
    // TODO(leszeks): If this copy doesn't change liveness, we could
    // opportunistically terminate early.
    liveness.in->CopyFrom(*liveness.out);
  }
  UpdateInLiveness<bytecode, implicit_register_use, operand_types...>(
      liveness.in, iterator);
  *next_bytecode_in_liveness = liveness.in;
}
References v8::internal::compiler::BytecodeLivenessState::CopyFrom(), DCHECK_NULL, v8::internal::compiler::BytecodeLiveness::in, v8::internal::Zone::New(), v8::internal::compiler::BytecodeLiveness::out, and UpdateInLiveness().
UpdateOutLiveness() [1/2]
template<bool IsFirstUpdate = false>
void v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateOutLiveness (Bytecode bytecode, BytecodeLiveness & liveness, BytecodeLivenessState * next_bytecode_in_liveness, const interpreter::BytecodeArrayIterator & iterator, DirectHandle< BytecodeArray > bytecode_array, const BytecodeLivenessMap & liveness_map, Zone * zone)
Definition at line 357 of file bytecode-analysis.cc.
                                                                            {
  switch (bytecode) {
#define BYTECODE_UPDATE_OUT_LIVENESS(Name, ...) \
  case Bytecode::k##Name: \
    return UpdateOutLiveness<IsFirstUpdate, Bytecode::k##Name>(\
        liveness, next_bytecode_in_liveness, iterator, bytecode_array, \
        liveness_map, zone);
    BYTECODE_LIST(BYTECODE_UPDATE_OUT_LIVENESS, BYTECODE_UPDATE_OUT_LIVENESS)
#undef BYTECODE_UPDATE_OUT_LIVENESS
  }
}
References BYTECODE_LIST, and BYTECODE_UPDATE_OUT_LIVENESS.
Referenced by v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::Analyze().
UpdateOutLiveness() [2/2]
template<bool IsFirstUpdate, Bytecode bytecode>
void v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateOutLiveness (BytecodeLiveness & liveness, BytecodeLivenessState * next_bytecode_in_liveness, const interpreter::BytecodeArrayIterator & iterator, DirectHandle< BytecodeArray > bytecode_array, const BytecodeLivenessMap & liveness_map, Zone * zone)
Definition at line 245 of file bytecode-analysis.cc.
                                                                            {
  // On subsequent updates, only update out-liveness manually if it isn't
  // already aliasing the next bytecode's in-liveness.
  if (!IsFirstUpdate && liveness.out == next_bytecode_in_liveness) return;
  // Special case Suspend and Resume to just pass through liveness.
  if (bytecode == Bytecode::kSuspendGenerator ||
      bytecode == Bytecode::kResumeGenerator) {
    DCHECK_NOT_NULL(next_bytecode_in_liveness);
    if (IsFirstUpdate) {
      liveness.out = next_bytecode_in_liveness;
    } else {
      liveness.out->Union(*next_bytecode_in_liveness);
    }
    return;
  }
  // Special case SwitchOnGeneratorState to ignore resume liveness, since that's
  // a pass through. Instead, just consider the fallthrough live, plus the
  // generator register itself for the resumes.
  if (bytecode == Bytecode::kSwitchOnGeneratorState) {
    DCHECK_NOT_NULL(next_bytecode_in_liveness);
    if (IsFirstUpdate) {
      // The generator register won't be live in the fallthrough, so copy the
      // liveness and make it live here.
      int generator_reg_index = iterator.GetRegisterOperand(0).index();
      DCHECK(!next_bytecode_in_liveness->RegisterIsLive(generator_reg_index));
      liveness.out =
          zone->New<BytecodeLivenessState>(*next_bytecode_in_liveness, zone);
      liveness.out->MarkRegisterLive(generator_reg_index);
    } else {
      liveness.out->Union(*next_bytecode_in_liveness);
    }
    return;
  }
  // Update from next bytecode (unless there isn't one or this is an
  // unconditional jump).
  if (next_bytecode_in_liveness != nullptr &&
      !Bytecodes::IsUnconditionalJump(bytecode) &&
      !Bytecodes::Returns(bytecode) &&
      !Bytecodes::UnconditionallyThrows(bytecode)) {
    if (IsFirstUpdate) {
      // On first update, we can assume that this out-liveness is the same as
      // the next liveness, and can directly alias it -- we'll allocate a new
      // one using EnsureOutLivenessIsNotAlias if it needs to be mutated.
      DCHECK_NULL(liveness.out);
      liveness.out = next_bytecode_in_liveness;
    } else {
      liveness.out->Union(*next_bytecode_in_liveness);
    }
  } else if (IsFirstUpdate) {
    // Otherwise, on the first allocation we need to make sure that there is an
    // allocated out liveness.
    DCHECK_NULL(liveness.out);
    liveness.out = zone->New<BytecodeLivenessState>(
        bytecode_array->register_count(), zone);
  }
  DCHECK_NOT_NULL(liveness.out);
  // Update from jump target (if any). Skip loops, we update these manually in
  // the liveness iterations.
  if (Bytecodes::IsForwardJump(bytecode)) {
    int target_offset = iterator.GetJumpTargetOffset();
    EnsureOutLivenessIsNotAlias<IsFirstUpdate>(liveness,
                                               next_bytecode_in_liveness, zone);
    liveness.out->Union(*liveness_map.GetInLiveness(target_offset));
  } else if (Bytecodes::IsSwitch(bytecode)) {
    EnsureOutLivenessIsNotAlias<IsFirstUpdate>(liveness,
                                               next_bytecode_in_liveness, zone);
    for (interpreter::JumpTableTargetOffset entry :
         iterator.GetJumpTableTargetOffsets()) {
      liveness.out->Union(*liveness_map.GetInLiveness(entry.target_offset));
    }
  }
  // Update from exception handler (if any).
  if (!interpreter::Bytecodes::IsWithoutExternalSideEffects(bytecode)) {
    // TODO(leszeks): We should look up this range only once per entry.
    HandlerTable table(*bytecode_array);
    int handler_index =
        table.LookupHandlerIndexForRange(iterator.current_offset());
    if (handler_index != HandlerTable::kNoHandlerFound) {
      EnsureOutLivenessIsNotAlias<IsFirstUpdate>(
          liveness, next_bytecode_in_liveness, zone);
      bool was_accumulator_live = liveness.out->AccumulatorIsLive();
      liveness.out->Union(
          *liveness_map.GetInLiveness(table.GetRangeHandler(handler_index)));
      liveness.out->MarkRegisterLive(table.GetRangeData(handler_index));
      if (!was_accumulator_live) {
        // The accumulator is reset to the exception on entry into a handler,
        // and so shouldn't be considered live coming out of this bytecode just
        // because it's live coming into the handler. So, kill the accumulator
        // if the handler is the only thing that made it live.
        liveness.out->MarkAccumulatorDead();
        // TODO(leszeks): Ideally the accumulator wouldn't be considered live at
        // the start of the handler, but looking up if the current bytecode is
        // the start of a handler is not free, so we should only do it if we
        // decide it's necessary.
      }
    }
  }
}
References v8::internal::compiler::BytecodeLivenessState::AccumulatorIsLive(), v8::internal::interpreter::BytecodeArrayIterator::current_offset(), v8::internal::DCHECK(), DCHECK_NOT_NULL, DCHECK_NULL, v8::internal::compiler::BytecodeLivenessMap::GetInLiveness(), v8::internal::interpreter::BytecodeArrayIterator::GetJumpTableTargetOffsets(), v8::internal::interpreter::BytecodeArrayIterator::GetJumpTargetOffset(), v8::internal::HandlerTable::GetRangeData(), v8::internal::HandlerTable::GetRangeHandler(), v8::internal::interpreter::BytecodeArrayIterator::GetRegisterOperand(), v8::internal::interpreter::Register::index(), v8::internal::interpreter::Bytecodes::IsForwardJump(), v8::internal::interpreter::Bytecodes::IsSwitch(), v8::internal::interpreter::Bytecodes::IsUnconditionalJump(), v8::internal::interpreter::Bytecodes::IsWithoutExternalSideEffects(), v8::internal::HandlerTable::kNoHandlerFound, v8::internal::HandlerTable::LookupHandlerIndexForRange(), v8::internal::compiler::BytecodeLivenessState::MarkAccumulatorDead(), v8::internal::compiler::BytecodeLivenessState::MarkRegisterLive(), v8::internal::Zone::New(), v8::internal::compiler::BytecodeLiveness::out, v8::internal::compiler::BytecodeLivenessState::RegisterIsLive(), v8::internal::interpreter::Bytecodes::Returns(), v8::internal::interpreter::Bytecodes::UnconditionallyThrows(), and v8::internal::compiler::BytecodeLivenessState::Union().