v8::internal::anonymous_namespace{execution.cc} Namespace Reference
Classes
struct InvokeParams
Functions
DirectHandle< Object > NormalizeReceiver (Isolate *isolate, DirectHandle< Object > receiver)
DirectHandle< Code > JSEntry (Isolate *isolate, Execution::Target execution_target, bool is_construct)
MaybeDirectHandle< Context > NewScriptContext (Isolate *isolate, DirectHandle< JSFunction > function, DirectHandle< FixedArray > host_defined_options)
V8_WARN_UNUSED_RESULT MaybeHandle< Object > Invoke (Isolate *isolate, const InvokeParams &params)
MaybeDirectHandle< Object > InvokeWithTryCatch (Isolate *isolate, const InvokeParams &params)
Function Documentation
Invoke()
V8_WARN_UNUSED_RESULT MaybeHandle<Object> v8::internal::anonymous_namespace{execution.cc}::Invoke (Isolate * isolate, const InvokeParams & params)
Definition at line 272 of file execution.cc.
                                                                             {
  RCS_SCOPE(isolate, RuntimeCallCounterId::kInvoke);
  DCHECK(!IsJSGlobalObject(*params.receiver));
  DCHECK_LE(params.args.size(), FixedArray::kMaxLength);
  DCHECK(!isolate->has_exception());
  // Runtime code must be able to get the "current" isolate from TLS, and this
  // must equal the isolate we execute in.
  DCHECK_EQ(isolate, Isolate::TryGetCurrent());
#if V8_ENABLE_WEBASSEMBLY
  // If we have PKU support for Wasm, ensure that code is currently write
  // protected for this thread.
  DCHECK_IMPLIES(wasm::GetWasmCodeManager()->HasMemoryProtectionKeySupport(),
                 !wasm::GetWasmCodeManager()->MemoryProtectionKeyWritable());
#endif // V8_ENABLE_WEBASSEMBLY
#ifdef USE_SIMULATOR
  // Simulators use separate stacks for C++ and JS. JS stack overflow checks
  // are performed whenever a JS function is called. However, it can be the case
  // that the C++ stack grows faster than the JS stack, resulting in an overflow
  // there. Add a check here to make that less likely.
  StackLimitCheck check(isolate);
  if (check.HasOverflowed()) {
    isolate->StackOverflow();
    isolate->ReportPendingMessages(params.message_handling ==
                                   Execution::MessageHandling::kReport);
    return MaybeHandle<Object>();
  }
#endif
  // api callbacks can be called directly, unless we want to take the detour
  // through JS to set up a frame for break-at-entry.
  if (IsJSFunction(*params.target)) {
    auto function = Cast<JSFunction>(params.target);
    if ((!params.is_construct || IsConstructor(*function)) &&
        function->shared()->IsApiFunction() &&
        !function->shared()->BreakAtEntry(isolate)) {
      SaveAndSwitchContext save(isolate, function->context());
      DCHECK(IsJSGlobalObject(function->context()->global_object()));
      DirectHandle<Object> receiver = params.is_construct
                                          ? isolate->factory()->the_hole_value()
                                          : params.receiver;
      DirectHandle<FunctionTemplateInfo> fun_data(
          function->shared()->api_func_data(), isolate);
      auto value = Builtins::InvokeApiFunction(
          isolate, params.is_construct, fun_data, receiver, params.args,
          Cast<HeapObject>(params.new_target));
      bool has_exception = value.is_null();
      DCHECK_EQ(has_exception, isolate->has_exception());
      if (has_exception) {
        isolate->ReportPendingMessages(params.message_handling ==
                                       Execution::MessageHandling::kReport);
        return MaybeHandle<Object>();
      } else {
        isolate->clear_pending_message();
      }
      return value;
    }
#ifdef DEBUG
    if (function->shared()->is_script()) {
      DCHECK(params.IsScript());
      DCHECK(IsJSGlobalProxy(*params.receiver));
      DCHECK_EQ(params.args.size(), 1);
      DCHECK(IsFixedArray(*params.args[0]));
    } else {
      DCHECK(!params.IsScript());
    }
#endif
    // Set up a ScriptContext when running scripts that need it.
    if (function->shared()->needs_script_context()) {
      DirectHandle<Context> context;
      DirectHandle<FixedArray> host_defined_options =
          const_cast<InvokeParams&>(params).GetAndResetHostDefinedOptions();
      if (!NewScriptContext(isolate, function, host_defined_options)
               .ToHandle(&context)) {
        isolate->ReportPendingMessages(params.message_handling ==
                                       Execution::MessageHandling::kReport);
        return MaybeHandle<Object>();
      }
      // We mutate the context if we allocate a script context. This is
      // guaranteed to only happen once in a native context since scripts will
      // always produce name clashes with themselves.
      function->set_context(*context);
    }
  }
  // Entering JavaScript.
  VMState<JS> state(isolate);
  if (!AllowJavascriptExecution::IsAllowed(isolate)) {
    GRACEFUL_FATAL("Invoke in DisallowJavascriptExecutionScope");
  }
  if (!ThrowOnJavascriptExecution::IsAllowed(isolate)) {
    isolate->ThrowIllegalOperation();
    isolate->ReportPendingMessages(params.message_handling ==
                                   Execution::MessageHandling::kReport);
    return MaybeHandle<Object>();
  }
  if (!DumpOnJavascriptExecution::IsAllowed(isolate)) {
    V8::GetCurrentPlatform()->DumpWithoutCrashing();
    return isolate->factory()->undefined_value();
  }
  isolate->IncrementJavascriptExecutionCounter();
  if (params.execution_target == Execution::Target::kCallable) {
    DirectHandle<NativeContext> context = isolate->native_context();
    if (!IsUndefined(context->script_execution_callback(), isolate)) {
      v8::Context::AbortScriptExecutionCallback callback =
          v8::ToCData<v8::Context::AbortScriptExecutionCallback,
                      kApiAbortScriptExecutionCallbackTag>(
              isolate, context->script_execution_callback());
      v8::Isolate* api_isolate = reinterpret_cast<v8::Isolate*>(isolate);
      v8::Local<v8::Context> api_context = v8::Utils::ToLocal(context);
      callback(api_isolate, api_context);
      DCHECK(!isolate->has_exception());
      // Always throw an exception to abort execution, if callback exists.
      isolate->ThrowIllegalOperation();
      return MaybeHandle<Object>();
    }
  }
  // Placeholder for return value.
  Tagged<Object> value;
  DirectHandle<Code> code =
      JSEntry(isolate, params.execution_target, params.is_construct);
  {
    // Save and restore context around invocation.
    SaveContext save(isolate);
    if (v8_flags.clear_exceptions_on_js_entry) isolate->clear_exception();
    if (params.execution_target == Execution::Target::kCallable) {
      // clang-format off
      // {new_target}, {target}, {receiver}, return value: tagged pointers
      // {argv}: pointer to array of tagged pointers
      using JSEntryFunction = GeneratedCode<Address(
          Address root_register_value, Address new_target, Address target,
          Address receiver, intptr_t argc, Address** argv)>;
      // clang-format on
      JSEntryFunction stub_entry =
          JSEntryFunction::FromAddress(isolate, code->instruction_start());
      Address orig_func = (*params.new_target).ptr();
      Address func = (*params.target).ptr();
      Address recv = (*params.receiver).ptr();
      int argc = static_cast<int>(params.args.size());
#ifdef V8_ENABLE_DIRECT_HANDLE
      // TODO(42203211): Store the arguments to indirect handles because
      // generated code still expects them in indirect handles. A fresh handle
      // scope is introduced for these handles, which is then sealed. When this
      // is eventually removed, sealing can go back together with saving the
      // context for both branches.
      HandleScope scope_for_conversion(isolate);
      std::vector<IndirectHandle<Object>> args(argc);
      for (int i = 0; i < argc; ++i)
        args[i] = indirect_handle(params.args[i], isolate);
      Address** argv = reinterpret_cast<Address**>(args.data());
#else
      Address** argv = const_cast<Address**>(
          reinterpret_cast<Address* const*>(params.args.data()));
#endif
      // Block the allocation of handles without explicit handle scopes.
      SealHandleScope shs(isolate);
      RCS_SCOPE(isolate, RuntimeCallCounterId::kJS_Execution);
      value = Tagged<Object>(
          stub_entry.Call(isolate->isolate_data()->isolate_root(), orig_func,
                          func, recv, JSParameterCount(argc), argv));
    } else {
      DCHECK_EQ(Execution::Target::kRunMicrotasks, params.execution_target);
      // clang-format off
      // return value: tagged pointers
      // {microtask_queue}: pointer to a C++ object
      using JSEntryFunction = GeneratedCode<Address(
          Address root_register_value, MicrotaskQueue* microtask_queue)>;
      // clang-format on
      JSEntryFunction stub_entry =
          JSEntryFunction::FromAddress(isolate, code->instruction_start());
      // Block the allocation of handles without explicit handle scopes.
      SealHandleScope shs(isolate);
      RCS_SCOPE(isolate, RuntimeCallCounterId::kJS_Execution);
      value = Tagged<Object>(stub_entry.Call(
          isolate->isolate_data()->isolate_root(), params.microtask_queue));
    }
  }
#ifdef VERIFY_HEAP
  if (v8_flags.verify_heap) {
    Object::ObjectVerify(value, isolate);
  }
#endif
  // Update the pending exception flag and return the value.
  bool has_exception = IsException(value, isolate);
  DCHECK_EQ(has_exception, isolate->has_exception());
  if (has_exception) {
    isolate->ReportPendingMessages(params.message_handling ==
                                   Execution::MessageHandling::kReport);
    return MaybeHandle<Object>();
  } else {
    isolate->clear_pending_message();
  }
  return Handle<Object>(value, isolate);
}
References v8::base::args, v8::internal::anonymous_namespace{execution.cc}::InvokeParams::args, v8::internal::Isolate::clear_exception(), v8::internal::Isolate::clear_pending_message(), code, v8::internal::Isolate::context(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, DCHECK_LE, v8::Platform::DumpWithoutCrashing(), v8::internal::anonymous_namespace{execution.cc}::InvokeParams::execution_target, v8::internal::Isolate::factory(), v8::internal::V8::GetCurrentPlatform(), v8::internal::wasm::GetWasmCodeManager(), GRACEFUL_FATAL, v8::internal::Isolate::has_exception(), v8::internal::StackLimitCheck::HasOverflowed(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::Isolate::IncrementJavascriptExecutionCounter(), v8::internal::indirect_handle(), v8::internal::Builtins::InvokeApiFunction(), v8::internal::anonymous_namespace{execution.cc}::InvokeParams::is_construct, v8::internal::Isolate::isolate_data(), v8::internal::IsolateData::isolate_root(), v8::internal::anonymous_namespace{execution.cc}::InvokeParams::IsScript(), JSEntry(), v8::internal::JSParameterCount(), v8::internal::kApiAbortScriptExecutionCallbackTag, v8::internal::Execution::kCallable, v8::internal::FixedArray::kMaxLength, v8::internal::Execution::kReport, v8::internal::Execution::kRunMicrotasks, v8::internal::anonymous_namespace{execution.cc}::InvokeParams::message_handling, v8::internal::anonymous_namespace{execution.cc}::InvokeParams::microtask_queue, v8::internal::Isolate::native_context(), v8::internal::anonymous_namespace{execution.cc}::InvokeParams::new_target, NewScriptContext(), RCS_SCOPE, v8::internal::anonymous_namespace{execution.cc}::InvokeParams::receiver, v8::internal::Isolate::ReportPendingMessages(), v8::internal::Isolate::StackOverflow(), v8::internal::Tagged< Object >, v8::internal::anonymous_namespace{execution.cc}::InvokeParams::target, v8::internal::Isolate::ThrowIllegalOperation(), v8::ToCData(), v8::Isolate::TryGetCurrent(), v8::internal::v8_flags, and v8::internal::value.
Referenced by cppgc::MakeGarbageCollectedTraitBase< T >::Allocate(), v8::internal::Execution::Call(), v8::internal::Execution::CallBuiltin(), v8::internal::Execution::CallScript(), InvokeWithTryCatch(), and v8::internal::Execution::New().
InvokeWithTryCatch()
MaybeDirectHandle<Object> v8::internal::anonymous_namespace{execution.cc}::InvokeWithTryCatch (Isolate * isolate, const InvokeParams & params)
Definition at line 485 of file execution.cc.
                                                                         {
  DCHECK_IMPLIES(v8_flags.strict_termination_checks,
                 !isolate->is_execution_terminating());
  MaybeDirectHandle<Object> maybe_result;
  if (params.exception_out != nullptr) {
    *params.exception_out = {};
  }
  // Enter a try-block while executing the JavaScript code. To avoid
  // duplicate error printing it must be non-verbose. Also, to avoid
  // creating message objects during stack overflow we shouldn't
  // capture messages.
  v8::TryCatch catcher(reinterpret_cast<v8::Isolate*>(isolate));
  catcher.SetVerbose(false);
  catcher.SetCaptureMessage(false);
  maybe_result = Invoke(isolate, params);
  if (V8_LIKELY(!maybe_result.is_null())) {
    DCHECK(!isolate->has_exception());
    return maybe_result;
  }
  DCHECK(isolate->has_exception());
  if (isolate->is_execution_terminating()) {
    return maybe_result;
  }
  if (params.exception_out != nullptr) {
    DCHECK(catcher.HasCaught());
    *params.exception_out = v8::Utils::OpenDirectHandle(*catcher.Exception());
  }
  return maybe_result;
}
References v8::internal::DCHECK(), DCHECK_IMPLIES, v8::TryCatch::Exception(), v8::internal::anonymous_namespace{execution.cc}::InvokeParams::exception_out, v8::internal::Isolate::has_exception(), v8::TryCatch::HasCaught(), Invoke(), v8::internal::Isolate::is_execution_terminating(), v8::internal::MaybeDirectHandle< T >::is_null(), v8::Utils::OpenDirectHandle(), v8::TryCatch::SetCaptureMessage(), v8::TryCatch::SetVerbose(), v8::internal::v8_flags, and V8_LIKELY.
Referenced by v8::internal::Execution::TryCall(), v8::internal::Execution::TryCallScript(), and v8::internal::Execution::TryRunMicrotasks().
JSEntry()
DirectHandle<Code> v8::internal::anonymous_namespace{execution.cc}::JSEntry (Isolate * isolate, Execution::Target execution_target, bool is_construct)
Definition at line 166 of file execution.cc.
                                              {
  if (is_construct) {
    DCHECK_EQ(Execution::Target::kCallable, execution_target);
    return BUILTIN_CODE(isolate, JSConstructEntry);
  } else if (execution_target == Execution::Target::kCallable) {
    DCHECK(!is_construct);
    return BUILTIN_CODE(isolate, JSEntry);
  } else if (execution_target == Execution::Target::kRunMicrotasks) {
    DCHECK(!is_construct);
    return BUILTIN_CODE(isolate, JSRunMicrotasksEntry);
  }
  UNREACHABLE();
}
References BUILTIN_CODE, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Execution::kCallable, v8::internal::Execution::kRunMicrotasks, and v8::internal::UNREACHABLE().
Referenced by Invoke().
NewScriptContext()
MaybeDirectHandle<Context> v8::internal::anonymous_namespace{execution.cc}::NewScriptContext (Isolate * isolate, DirectHandle< JSFunction > function, DirectHandle< FixedArray > host_defined_options)
Definition at line 181 of file execution.cc.
                                                   {
  // TODO(cbruni, 1244145): Use passed in host_defined_options.
  // Creating a script context is a side effect, so abort if that's not
  // allowed.
  if (isolate->should_check_side_effects()) {
    isolate->Throw(*isolate->factory()->NewEvalError(
        MessageTemplate::kNoSideEffectDebugEvaluate));
    return MaybeDirectHandle<Context>();
  }
  SaveAndSwitchContext save(isolate, function->context());
  Tagged<SharedFunctionInfo> sfi = function->shared();
  Handle<Script> script(Cast<Script>(sfi->script()), isolate);
  DirectHandle<ScopeInfo> scope_info(sfi->scope_info(), isolate);
  // Make sure this is the first time we're running this function.
  CHECK(IsNativeContext(function->context()));
  DirectHandle<NativeContext> native_context(
      Cast<NativeContext>(function->context()), isolate);
  DirectHandle<JSGlobalObject> global_object(native_context->global_object(),
                                             isolate);
  Handle<ScriptContextTable> script_context(
      native_context->script_context_table(), isolate);
  // Find name clashes.
  for (auto name_it : ScopeInfo::IterateLocalNames(scope_info)) {
    Handle<String> name(name_it->name(), isolate);
    VariableMode mode = scope_info->ContextLocalMode(name_it->index());
    VariableLookupResult lookup;
    if (script_context->Lookup(name, &lookup)) {
      if (IsLexicalVariableMode(mode) || IsLexicalVariableMode(lookup.mode)) {
        DirectHandle<Context> context(script_context->get(lookup.context_index),
                                      isolate);
        // If we are trying to redeclare a REPL-mode let as a let, REPL-mode
        // const as a const, REPL-mode using as a using and REPL-mode await
        // using as an await using allow it.
        if (!((mode == lookup.mode && IsLexicalVariableMode(mode)) &&
              scope_info->IsReplModeScope() &&
              context->scope_info()->IsReplModeScope())) {
          // ES#sec-globaldeclarationinstantiation 5.b:
          // If envRec.HasLexicalDeclaration(name) is true, throw a SyntaxError
          // exception.
          MessageLocation location(script, 0, 1);
          isolate->ThrowAt(isolate->factory()->NewSyntaxError(
                               MessageTemplate::kVarRedeclaration, name),
                           &location);
          return MaybeDirectHandle<Context>();
        }
      }
    }
    if (IsLexicalVariableMode(mode)) {
      LookupIterator lookup_it(isolate, global_object, name, global_object,
                               LookupIterator::OWN_SKIP_INTERCEPTOR);
      Maybe<PropertyAttributes> maybe =
          JSReceiver::GetPropertyAttributes(&lookup_it);
      // Can't fail since the we looking up own properties on the global object
      // skipping interceptors.
      CHECK(!maybe.IsNothing());
      if ((maybe.FromJust() & DONT_DELETE) != 0) {
        // ES#sec-globaldeclarationinstantiation 5.a:
        // If envRec.HasVarDeclaration(name) is true, throw a SyntaxError
        // exception.
        // ES#sec-globaldeclarationinstantiation 5.d:
        // If hasRestrictedGlobal is true, throw a SyntaxError exception.
        MessageLocation location(script, 0, 1);
        isolate->ThrowAt(isolate->factory()->NewSyntaxError(
                             MessageTemplate::kVarRedeclaration, name),
                         &location);
        return MaybeDirectHandle<Context>();
      }
      JSGlobalObject::InvalidatePropertyCell(global_object, name);
    }
  }
  DirectHandle<Context> result =
      isolate->factory()->NewScriptContext(native_context, scope_info);
  result->Initialize(isolate);
  // In REPL mode, we are allowed to add/modify let/const/using/await using
  // variables. We use the previous defined script context for those.
  const bool ignore_duplicates = scope_info->IsReplModeScope();
  DirectHandle<ScriptContextTable> new_script_context_table =
      ScriptContextTable::Add(isolate, script_context, result,
                              ignore_duplicates);
  native_context->synchronized_set_script_context_table(
      *new_script_context_table);
  return result;
}
References v8::internal::ScriptContextTable::Add(), CHECK, v8::internal::Isolate::context(), v8::internal::VariableLookupResult::context_index, v8::internal::DONT_DELETE, v8::internal::Isolate::factory(), v8::Maybe< T >::FromJust(), v8::internal::JSReceiver::GetPropertyAttributes(), v8::internal::JSGlobalObject::InvalidatePropertyCell(), v8::internal::IsLexicalVariableMode(), v8::Maybe< T >::IsNothing(), v8::internal::ScopeInfo::IterateLocalNames(), mode(), v8::internal::VariableLookupResult::mode, v8::internal::name, v8::internal::native_context, v8::internal::Factory::NewScriptContext(), v8::internal::LookupIterator::OWN_SKIP_INTERCEPTOR, v8::base::internal::result, v8::internal::script, v8::internal::Isolate::should_check_side_effects(), v8::internal::Isolate::Throw(), and v8::internal::Isolate::ThrowAt().
Referenced by Invoke().
NormalizeReceiver()
DirectHandle<Object> v8::internal::anonymous_namespace{execution.cc}::NormalizeReceiver (Isolate * isolate, DirectHandle< Object > receiver)
Definition at line 25 of file execution.cc.
                                                                      {
  // Convert calls on global objects to be calls on the global
  // receiver instead to avoid having a 'this' pointer which refers
  // directly to a global object.
  if (IsJSGlobalObject(*receiver)) {
    return direct_handle(Cast<JSGlobalObject>(receiver)->global_proxy(),
                         isolate);
  }
  return receiver;
}
References v8::internal::direct_handle().
Referenced by v8::internal::anonymous_namespace{execution.cc}::InvokeParams::SetUpForCall(), and v8::internal::anonymous_namespace{execution.cc}::InvokeParams::SetUpForTryCall().