v8::internal::maglev::anonymous_namespace{maglev-ir-s390.cc} Namespace Reference
Enumerations
enum class ReduceInterruptBudgetType { kLoop
, kReturn
 }
Functions
void HandleInterruptsAndTiering (MaglevAssembler *masm, ZoneLabelRef done, Node *node, ReduceInterruptBudgetType type, Register scratch0)
void GenerateReduceInterruptBudget (MaglevAssembler *masm, Node *node, Register feedback_cell, ReduceInterruptBudgetType type, int amount)
Enumeration Type Documentation
ReduceInterruptBudgetType
enum v8::internal::maglev::anonymous_namespace{maglev-ir-s390.cc}::ReduceInterruptBudgetType [strong]
Enumerator
kLoop
kReturn
Definition at line 742 of file maglev-ir-s390.cc.
{ kLoop, kReturn };
Function Documentation
GenerateReduceInterruptBudget()
void v8::internal::maglev::anonymous_namespace{maglev-ir-s390.cc}::GenerateReduceInterruptBudget (MaglevAssembler * masm, Node * node, Register feedback_cell, ReduceInterruptBudgetType type, int amount)
Definition at line 798 of file maglev-ir-s390.cc.
                                                                               {
  MaglevAssembler::TemporaryRegisterScope temps(masm);
  Register budget = temps.AcquireScratch();
  __ LoadU32(budget, FieldMemOperand(feedback_cell,
                                     FeedbackCell::kInterruptBudgetOffset));
  __ SubS32(budget, Operand(amount));
  __ StoreU32(budget, FieldMemOperand(feedback_cell,
                                      FeedbackCell::kInterruptBudgetOffset));
  ZoneLabelRef done(masm);
  __ JumpToDeferredIf(lt, HandleInterruptsAndTiering, done, node, type, budget);
  __ bind(*done);
}
References __, v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), v8::internal::FieldMemOperand(), HandleInterruptsAndTiering(), v8::internal::lt, and v8::internal::tracing::type.
HandleInterruptsAndTiering()
void v8::internal::maglev::anonymous_namespace{maglev-ir-s390.cc}::HandleInterruptsAndTiering (MaglevAssembler * masm, ZoneLabelRef done, Node * node, ReduceInterruptBudgetType type, Register scratch0)
Definition at line 744 of file maglev-ir-s390.cc.
                                                   {
  // For loops, first check for interrupts. Don't do this for returns, as we
  // can't lazy deopt to the end of a return.
  if (type == ReduceInterruptBudgetType::kLoop) {
    Label next;
    // Here, we only care about interrupts since we've already guarded against
    // real stack overflows on function entry.
    {
      Register stack_limit = scratch0;
      __ LoadStackLimit(stack_limit, StackLimitKind::kInterruptStackLimit);
      __ CmpU64(sp, stack_limit);
      __ bgt(&next);
    }
    // An interrupt has been requested and we must call into runtime to handle
    // it; since we already pay the call cost, combine with the TieringManager
    // call.
    {
      SaveRegisterStateForCall save_register_state(masm,
                                                   node->register_snapshot());
      Register function = scratch0;
      __ LoadU64(function,
                 MemOperand(fp, StandardFrameConstants::kFunctionOffset));
      __ Push(function);
      // Move into kContextRegister after the load into scratch0, just in case
      // scratch0 happens to be kContextRegister.
      __ Move(kContextRegister, masm->native_context().object());
      __ CallRuntime(Runtime::kBytecodeBudgetInterruptWithStackCheck_Maglev, 1);
      save_register_state.DefineSafepointWithLazyDeopt(node->lazy_deopt_info());
    }
    __ b(*done); // All done, continue.
    __ bind(&next);
  }
  // No pending interrupts. Call into the TieringManager if needed.
  {
    SaveRegisterStateForCall save_register_state(masm,
                                                 node->register_snapshot());
    Register function = scratch0;
    __ LoadU64(function,
               MemOperand(fp, StandardFrameConstants::kFunctionOffset));
    __ Push(function);
    // Move into kContextRegister after the load into scratch0, just in case
    // scratch0 happens to be kContextRegister.
    __ Move(kContextRegister, masm->native_context().object());
    // Note: must not cause a lazy deopt!
    __ CallRuntime(Runtime::kBytecodeBudgetInterrupt_Maglev, 1);
    save_register_state.DefineSafepoint();
  }
  __ b(*done);
}
References __, v8::internal::maglev::SaveRegisterStateForCall::DefineSafepoint(), v8::internal::maglev::SaveRegisterStateForCall::DefineSafepointWithLazyDeopt(), v8::internal::kContextRegister, v8::internal::StandardFrameConstants::kFunctionOffset, v8::internal::kInterruptStackLimit, v8::internal::maglev::NodeBase::lazy_deopt_info(), v8::internal::maglev::MaglevAssembler::native_context(), v8::internal::compiler::NativeContextRef::object(), v8::internal::maglev::NodeBase::register_snapshot(), and v8::internal::tracing::type.
Referenced by GenerateReduceInterruptBudget().