v8::bigint::anonymous_namespace{mul-fft.cc} Namespace Reference
Classes
struct Parameters
class FFTContainer
Functions
void ModFn_Helper (digit_t *x, int len, signed_digit_t high)
void ModFn (digit_t *x, int len)
void ModFnDoubleWidth (digit_t *dest, const digit_t *src, int len)
void SumDiff (digit_t *sum, digit_t *diff, const digit_t *a, const digit_t *b, int len)
void ShiftModFn_Large (digit_t *result, const digit_t *input, int digit_shift, int bits_shift, int K)
void ShiftModFn (digit_t *result, const digit_t *input, int power_of_two, int K, int zero_above=0x7FFFFFFF)
void ComputeParameters (int N, int m, Parameters *params)
void ComputeParameters_Inner (int N, Parameters *params)
int PredictInnerK (int N)
bool ShouldDecrementM (const Parameters &current, const Parameters &next, const Parameters &after_next)
int GetParameters (int N, Parameters *params)
void CopyAndZeroExtend (digit_t *dst, const digit_t *src, int digits_to_copy, size_t total_bytes)
bool ShouldBeNegative (const digit_t *x, int xlen, digit_t threshold, int s)
void MultiplyFFT_Inner (RWDigits Z, Digits X, Digits Y, const Parameters &params, ProcessorImpl *processor)
Function Documentation
ComputeParameters()
void v8::bigint::anonymous_namespace{mul-fft.cc}::ComputeParameters (int N, int m, Parameters * params)
Definition at line 303 of file mul-fft.cc.
                                                         {
  N *= kDigitBits;
  int n = 1 << m; // 2^m
  int nhalf = n >> 1;
  int s = (N + n - 1) >> m; // ceil(N/n)
  s = RoundUp(s, kDigitBits);
  int K = m + 2 * s + 1; // K must be at least this big...
  K = RoundUp(K, nhalf); // ...and a multiple of n/2.
  int r = K >> (m - 1); // Which multiple?
  // We want recursive calls to make progress, so force K to be a multiple
  // of 8 if it's above the recursion threshold. Otherwise, K must be a
  // multiple of kDigitBits.
  const int threshold = (K + 1 >= kFftInnerThreshold * kDigitBits)
                            ? 3 + kLog2DigitBits
                            : kLog2DigitBits;
  int K_tz = CountTrailingZeros(K);
  while (K_tz < threshold) {
    K += (1 << K_tz);
    r = K >> (m - 1);
    K_tz = CountTrailingZeros(K);
  }
  DCHECK(K % kDigitBits == 0);
  DCHECK(s % kDigitBits == 0);
  params->K = K / kDigitBits;
  params->s = s / kDigitBits;
  params->n = n;
  params->r = r;
}
References v8::bigint::CountTrailingZeros(), DCHECK, v8::bigint::anonymous_namespace{mul-fft.cc}::Parameters::K, v8::internal::K, v8::bigint::kDigitBits, v8::bigint::kFftInnerThreshold, v8::bigint::anonymous_namespace{mul-fft.cc}::Parameters::n, v8::internal::N, v8::bigint::anonymous_namespace{mul-fft.cc}::Parameters::r, v8::bigint::RoundUp(), and v8::bigint::anonymous_namespace{mul-fft.cc}::Parameters::s.
Referenced by GetParameters().
ComputeParameters_Inner()
void v8::bigint::anonymous_namespace{mul-fft.cc}::ComputeParameters_Inner (int N, Parameters * params)
Definition at line 335 of file mul-fft.cc.
                                                        {
  int max_m = CountTrailingZeros(N);
  int N_bits = BitLength(N);
  int m = N_bits - 4; // Don't let s get too small.
  m = std::min(max_m, m);
  N *= kDigitBits;
  int n = 1 << m; // 2^m
  // We can't round up s in the inner layer, because N = n*s is fixed.
  int s = N >> m;
  DCHECK(N == s * n);
  int K = m + 2 * s + 1; // K must be at least this big...
  K = RoundUp(K, n); // ...and a multiple of n and kDigitBits.
  K = RoundUp(K, kDigitBits);
  params->r = K >> m; // Which multiple?
  DCHECK(K % kDigitBits == 0);
  DCHECK(s % kDigitBits == 0);
  params->K = K / kDigitBits;
  params->s = s / kDigitBits;
  params->n = n;
  params->m = m;
}
References v8::bigint::BitLength(), v8::bigint::CountTrailingZeros(), DCHECK, v8::bigint::anonymous_namespace{mul-fft.cc}::Parameters::K, v8::internal::K, v8::bigint::kDigitBits, v8::bigint::anonymous_namespace{mul-fft.cc}::Parameters::m, v8::bigint::anonymous_namespace{mul-fft.cc}::Parameters::n, v8::internal::N, v8::bigint::anonymous_namespace{mul-fft.cc}::Parameters::r, v8::bigint::RoundUp(), and v8::bigint::anonymous_namespace{mul-fft.cc}::Parameters::s.
Referenced by v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::DoPointwiseMultiplication(), and PredictInnerK().
CopyAndZeroExtend()
void v8::bigint::anonymous_namespace{mul-fft.cc}::CopyAndZeroExtend (digit_t * dst, const digit_t * src, int digits_to_copy, size_t total_bytes) [inline]
Definition at line 480 of file mul-fft.cc.
                                                                      {
  size_t bytes_to_copy = digits_to_copy * sizeof(digit_t);
  memcpy(dst, static_cast<const void*>(src), bytes_to_copy);
  memset(dst + digits_to_copy, 0, total_bytes - bytes_to_copy);
}
Referenced by v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::Start(), and v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::Start_Default().
GetParameters()
int v8::bigint::anonymous_namespace{mul-fft.cc}::GetParameters (int N, Parameters * params)
Definition at line 400 of file mul-fft.cc.
                                             {
  int N_bits = BitLength(N);
  int max_m = N_bits - 3; // Larger m make s too small.
  max_m = std::max(kLog2DigitBits, max_m); // Smaller m break the logic below.
  int m = max_m;
  Parameters current;
  ComputeParameters(N, m, &current);
  Parameters next;
  ComputeParameters(N, m - 1, &next);
  while (m > 2) {
    Parameters after_next;
    ComputeParameters(N, m - 2, &after_next);
    if (ShouldDecrementM(current, next, after_next)) {
      m--;
      current = next;
      next = after_next;
    } else {
      break;
    }
  }
  *params = current;
  return m;
}
References v8::bigint::BitLength(), ComputeParameters(), v8::internal::N, and ShouldDecrementM().
Referenced by v8::internal::OptimizedJSFrame::Summarize(), and v8::internal::UnoptimizedJSFrame::Summarize().
ModFn()
void v8::bigint::anonymous_namespace{mul-fft.cc}::ModFn (digit_t * x, int len)
Definition at line 46 of file mul-fft.cc.
                                {
  int K = len - 1;
  signed_digit_t high = x[K];
  if (high == 0) return;
  ModFn_Helper(x, len, high);
  high = x[K];
  if (high == 0) return;
  DCHECK(high == 1 || high == -1);
  ModFn_Helper(x, len, high);
  high = x[K];
  if (high == -1) ModFn_Helper(x, len, high);
}
References DCHECK, v8::internal::K, and ModFn_Helper().
Referenced by ModFnDoubleWidth(), and SumDiff().
ModFn_Helper()
void v8::bigint::anonymous_namespace{mul-fft.cc}::ModFn_Helper (digit_t * x, int len, signed_digit_t high)
Definition at line 26 of file mul-fft.cc.
                                                            {
  if (high > 0) {
    digit_t borrow = high;
    x[len - 1] = 0;
    for (int i = 0; i < len; i++) {
      x[i] = digit_sub(x[i], borrow, &borrow);
      if (borrow == 0) break;
    }
  } else {
    digit_t carry = -high;
    x[len - 1] = 0;
    for (int i = 0; i < len; i++) {
      x[i] = digit_add2(x[i], carry, &carry);
      if (carry == 0) break;
    }
  }
}
References v8::internal::carry, v8::bigint::digit_add2(), v8::bigint::digit_sub(), and v8::internal::anonymous_namespace{json-stringifier.cc}::i.
Referenced by ModFn().
ModFnDoubleWidth()
void v8::bigint::anonymous_namespace{mul-fft.cc}::ModFnDoubleWidth (digit_t * dest, const digit_t * src, int len)
Definition at line 63 of file mul-fft.cc.
                                                                  {
  int K = len - 1;
  digit_t borrow = 0;
  for (int i = 0; i < K; i++) {
    dest[i] = digit_sub2(src[i], src[i + K], borrow, &borrow);
  }
  dest[K] = digit_sub2(0, src[2 * K], borrow, &borrow);
  // {borrow} may be non-zero here, that's OK as {ModFn} will take care of it.
  ModFn(dest, len);
}
References v8::bigint::digit_sub2(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::K, and ModFn().
Referenced by v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::DoPointwiseMultiplication().
MultiplyFFT_Inner()
void v8::bigint::anonymous_namespace{mul-fft.cc}::MultiplyFFT_Inner (RWDigits Z, Digits X, Digits Y, const Parameters & params, ProcessorImpl * processor)
Definition at line 703 of file mul-fft.cc.
                                                 {
  int omega = 2 * params.r; // really: 2^(2r)
  int theta = params.r; // really: 2^r
  FFTContainer a(params.n, params.K, processor);
  a.Start_Default(X, params.s, theta, omega);
  FFTContainer b(params.n, params.K, processor);
  b.Start_Default(Y, params.s, theta, omega);
  a.PointwiseMultiply(b);
  if (processor->should_terminate()) return;
  FFTContainer& c = a;
  c.BackwardFFT(0, params.n, omega);
  c.CounterWeightAndRecombine(theta, params.m, Z, params.s);
}
References v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::BackwardFFT(), v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::CounterWeightAndRecombine(), v8::bigint::anonymous_namespace{mul-fft.cc}::Parameters::K, v8::bigint::anonymous_namespace{mul-fft.cc}::Parameters::m, v8::bigint::anonymous_namespace{mul-fft.cc}::Parameters::n, v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::PointwiseMultiply(), v8::bigint::anonymous_namespace{mul-fft.cc}::Parameters::r, v8::bigint::anonymous_namespace{mul-fft.cc}::Parameters::s, v8::bigint::ProcessorImpl::should_terminate(), v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::Start_Default(), and X().
Referenced by v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::DoPointwiseMultiplication().
PredictInnerK()
int v8::bigint::anonymous_namespace{mul-fft.cc}::PredictInnerK (int N)
Definition at line 357 of file mul-fft.cc.
                         {
  Parameters params;
  ComputeParameters_Inner(N, &params);
  return params.K;
}
References ComputeParameters_Inner(), v8::bigint::anonymous_namespace{mul-fft.cc}::Parameters::K, and v8::internal::N.
Referenced by ShouldDecrementM().
ShiftModFn()
void v8::bigint::anonymous_namespace{mul-fft.cc}::ShiftModFn (digit_t * result, const digit_t * input, int power_of_two, int K, int zero_above = 0x7FFFFFFF)
Definition at line 180 of file mul-fft.cc.
                                             {
  // The modulo-reduction amounts to a subtraction, which we combine
  // with the shift as follows:
  // input = [ iK ][iK-1] .... .... [ i1 ][ i0 ]
  // result = [iX-1] .... [ i0 ] <---------- shift by {power_of_two}
  // - [ iK ] .... [ iX ]
  // where "X" is the index "K - digit_shift".
  int digit_shift = power_of_two / kDigitBits;
  int bits_shift = power_of_two % kDigitBits;
  // By an analogous construction to the "digit_shift >= K" case,
  // it turns out that:
  // x * 2^{2K+m} == x * 2^m mod 2^K + 1.
  while (digit_shift >= 2 * K) digit_shift -= 2 * K; // Faster than '%'!
  if (digit_shift >= K) {
    return ShiftModFn_Large(result, input, digit_shift, bits_shift, K);
  }
  digit_t borrow = 0;
  if (bits_shift == 0) {
    // We do a single pass over {input}, starting by copying digits [i1] to
    // [iX-1] to result indices digit_shift+1 to K-1.
    int i = 1;
    // Read input digits unless we know they are zero.
    int cap = std::min(K - digit_shift, zero_above);
    for (; i < cap; i++) {
      result[i + digit_shift] = input[i];
    }
    // Any remaining work can hard-code the knowledge that input[i] == 0.
    for (; i < K - digit_shift; i++) {
      DCHECK(input[i] == 0);
      result[i + digit_shift] = 0;
    }
    // Second phase: subtract input digits [iX] to [iK] from (virtually) zero-
    // initialized result indices 0 to digit_shift-1.
    cap = std::min(K, zero_above);
    for (; i < cap; i++) {
      digit_t d = input[i];
      result[i - K + digit_shift] = digit_sub2(0, d, borrow, &borrow);
    }
    // Any remaining work can hard-code the knowledge that input[i] == 0.
    for (; i < K; i++) {
      DCHECK(input[i] == 0);
      result[i - K + digit_shift] = digit_sub(0, borrow, &borrow);
    }
    // Last step: subtract [iK] from [i0] and store at result index digit_shift.
    result[digit_shift] = digit_sub2(input[0], input[K], borrow, &borrow);
  } else {
    // Same flow as before, but taking bits_shift != 0 into account.
    // First phase: result indices digit_shift+1 to K.
    digit_t carry = 0;
    int i = 0;
    // Read input digits unless we know they are zero.
    int cap = std::min(K - digit_shift, zero_above);
    for (; i < cap; i++) {
      digit_t d = input[i];
      result[i + digit_shift] = (d << bits_shift) | carry;
      carry = d >> (kDigitBits - bits_shift);
    }
    // Any remaining work can hard-code the knowledge that input[i] == 0.
    for (; i < K - digit_shift; i++) {
      DCHECK(input[i] == 0);
      result[i + digit_shift] = carry;
      carry = 0;
    }
    // Second phase: result indices 0 to digit_shift - 1.
    cap = std::min(K, zero_above);
    for (; i < cap; i++) {
      digit_t d = input[i];
      result[i - K + digit_shift] =
          digit_sub2(0, (d << bits_shift) | carry, borrow, &borrow);
      carry = d >> (kDigitBits - bits_shift);
    }
    // Any remaining work can hard-code the knowledge that input[i] == 0.
    if (i < K) {
      DCHECK(input[i] == 0);
      result[i - K + digit_shift] = digit_sub2(0, carry, borrow, &borrow);
      carry = 0;
      i++;
    }
    for (; i < K; i++) {
      DCHECK(input[i] == 0);
      result[i - K + digit_shift] = digit_sub(0, borrow, &borrow);
    }
    // Last step: compute result[digit_shift].
    digit_t d = input[K];
    result[digit_shift] = digit_sub2(
        result[digit_shift], (d << bits_shift) | carry, borrow, &borrow);
    // No carry left.
    DCHECK((d >> (kDigitBits - bits_shift)) == 0);
  }
  result[K] = 0;
  for (int i = digit_shift + 1; i <= K && borrow > 0; i++) {
    result[i] = digit_sub(result[i], borrow, &borrow);
  }
  if (borrow > 0) {
    // Underflow means we subtracted too much. Add 2^K + 1.
    digit_t carry = 1;
    for (int i = 0; i <= K; i++) {
      result[i] = digit_add2(result[i], carry, &carry);
      if (carry == 0) break;
    }
    result[K] = digit_add2(result[K], 1, &carry);
  }
}
References v8::internal::carry, DCHECK, v8::bigint::digit_add2(), v8::bigint::digit_sub(), v8::bigint::digit_sub2(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::K, v8::bigint::kDigitBits, v8::base::internal::result, and ShiftModFn_Large().
Referenced by v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::BackwardFFT_Threadsafe(), v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::CounterWeightAndRecombine(), v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::FFT_ReturnShuffledThreadsafe(), v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::NormalizeAndRecombine(), v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::Start(), and v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::Start_Default().
ShiftModFn_Large()
void v8::bigint::anonymous_namespace{mul-fft.cc}::ShiftModFn_Large (digit_t * result, const digit_t * input, int digit_shift, int bits_shift, int K)
Definition at line 93 of file mul-fft.cc.
                                             {
  // If {digit_shift} is greater than K, we use the following transformation
  // (where, since everything is mod 2^K + 1, we are allowed to add or
  // subtract any multiple of 2^K + 1 at any time):
  // x * 2^{K+m} mod 2^K + 1
  // == x * 2^K * 2^m - (2^K + 1)*(x * 2^m) mod 2^K + 1
  // == x * 2^K * 2^m - x * 2^K * 2^m - x * 2^m mod 2^K + 1
  // == -x * 2^m mod 2^K + 1
  // So the flow is the same as for m < K, but we invert the subtraction's
  // operands. In order to avoid underflow, we virtually initialize the
  // result to 2^K + 1:
  // input = [ iK ][iK-1] .... .... [ i1 ][ i0 ]
  // result = [ 1][0000] .... .... [0000][0001]
  // + [ iK ] .... [ iX ]
  // - [iX-1] .... [ i0 ]
  DCHECK(digit_shift >= K);
  digit_shift -= K;
  digit_t borrow = 0;
  if (bits_shift == 0) {
    digit_t carry = 1;
    for (int i = 0; i < digit_shift; i++) {
      result[i] = digit_add2(input[i + K - digit_shift], carry, &carry);
    }
    result[digit_shift] = digit_sub(input[K] + carry, input[0], &borrow);
    for (int i = digit_shift + 1; i < K; i++) {
      digit_t d = input[i - digit_shift];
      result[i] = digit_sub2(0, d, borrow, &borrow);
    }
  } else {
    digit_t add_carry = 1;
    digit_t input_carry =
        input[K - digit_shift - 1] >> (kDigitBits - bits_shift);
    for (int i = 0; i < digit_shift; i++) {
      digit_t d = input[i + K - digit_shift];
      digit_t summand = (d << bits_shift) | input_carry;
      result[i] = digit_add2(summand, add_carry, &add_carry);
      input_carry = d >> (kDigitBits - bits_shift);
    }
    {
      // result[digit_shift] = (add_carry + iK_part) - i0_part
      digit_t d = input[K];
      digit_t iK_part = (d << bits_shift) | input_carry;
      digit_t iK_carry = d >> (kDigitBits - bits_shift);
      digit_t sum = digit_add2(add_carry, iK_part, &add_carry);
      // {iK_carry} is less than a full digit, so we can merge {add_carry}
      // into it without overflow.
      iK_carry += add_carry;
      d = input[0];
      digit_t i0_part = d << bits_shift;
      result[digit_shift] = digit_sub(sum, i0_part, &borrow);
      input_carry = d >> (kDigitBits - bits_shift);
      if (digit_shift + 1 < K) {
        d = input[1];
        digit_t subtrahend = (d << bits_shift) | input_carry;
        result[digit_shift + 1] =
            digit_sub2(iK_carry, subtrahend, borrow, &borrow);
        input_carry = d >> (kDigitBits - bits_shift);
      }
    }
    for (int i = digit_shift + 2; i < K; i++) {
      digit_t d = input[i - digit_shift];
      digit_t subtrahend = (d << bits_shift) | input_carry;
      result[i] = digit_sub2(0, subtrahend, borrow, &borrow);
      input_carry = d >> (kDigitBits - bits_shift);
    }
  }
  // The virtual 1 in result[K] should be eliminated by {borrow}. If there
  // is no borrow, then the virtual initialization was too much. Subtract
  // 2^K + 1.
  result[K] = 0;
  if (borrow != 1) {
    borrow = 1;
    for (int i = 0; i < K; i++) {
      result[i] = digit_sub(result[i], borrow, &borrow);
      if (borrow == 0) break;
    }
    if (borrow != 0) {
      // The result must be 2^K.
      for (int i = 0; i < K; i++) result[i] = 0;
      result[K] = 1;
    }
  }
}
References v8::internal::carry, DCHECK, v8::bigint::digit_add2(), v8::bigint::digit_sub(), v8::bigint::digit_sub2(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::K, v8::bigint::kDigitBits, and v8::base::internal::result.
Referenced by ShiftModFn().
ShouldBeNegative()
bool v8::bigint::anonymous_namespace{mul-fft.cc}::ShouldBeNegative (const digit_t * x, int xlen, digit_t threshold, int s)
Definition at line 638 of file mul-fft.cc.
                                                                            {
  if (x[2 * s] >= threshold) return true;
  for (int i = 2 * s + 1; i < xlen; i++) {
    if (x[i] > 0) return true;
  }
  return false;
}
References xlen.
Referenced by v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::CounterWeightAndRecombine().
ShouldDecrementM()
bool v8::bigint::anonymous_namespace{mul-fft.cc}::ShouldDecrementM (const Parameters & current, const Parameters & next, const Parameters & after_next)
Definition at line 365 of file mul-fft.cc.
                                                    {
  // K == 64 seems to work particularly well.
  if (current.K == 64 && next.K >= 112) return false;
  // Small values for s are never efficient.
  if (current.s < 6) return true;
  // The time is roughly determined by K * n. When we decrement m, then
  // n always halves, and K usually gets bigger, by up to 2x.
  // For not-quite-so-small s, look at how much bigger K would get: if
  // the K increase is small enough, making n smaller is worth it.
  // Empirically, it's most meaningful to look at the K *after* next.
  // The specific threshold values have been chosen by running many
  // benchmarks on inputs of many sizes, and manually selecting thresholds
  // that seemed to produce good results.
  double factor = static_cast<double>(after_next.K) / current.K;
  if ((current.s == 6 && factor < 3.85) || // --
      (current.s == 7 && factor < 3.73) || // --
      (current.s == 8 && factor < 3.55) || // --
      (current.s == 9 && factor < 3.50) || // --
      factor < 3.4) {
    return true;
  }
  // If K is just below the recursion threshold, make sure we do recurse,
  // unless doing so would be particularly inefficient (large inner_K).
  // If K is just above the recursion threshold, doubling it often makes
  // the inner call more efficient.
  if (current.K >= 160 && current.K < 250 && PredictInnerK(next.K) < 28) {
    return true;
  }
  // If we found no reason to decrement, keep m as large as possible.
  return false;
}
References v8::base::internal::if(), v8::bigint::anonymous_namespace{mul-fft.cc}::Parameters::K, PredictInnerK(), and v8::bigint::anonymous_namespace{mul-fft.cc}::Parameters::s.
Referenced by GetParameters().
SumDiff()
void v8::bigint::anonymous_namespace{mul-fft.cc}::SumDiff (digit_t * sum, digit_t * diff, const digit_t * a, const digit_t * b, int len)
Definition at line 77 of file mul-fft.cc.
                      {
  digit_t carry = 0;
  digit_t borrow = 0;
  for (int i = 0; i < len; i++) {
    // Read both values first, because inputs and outputs can overlap.
    digit_t ai = a[i];
    digit_t bi = b[i];
    sum[i] = digit_add3(ai, bi, carry, &carry);
    diff[i] = digit_sub2(ai, bi, borrow, &borrow);
  }
  ModFn(sum, len);
  ModFn(diff, len);
}
References v8::internal::carry, v8::bigint::digit_add3(), v8::bigint::digit_sub2(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, and ModFn().
Referenced by v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::BackwardFFT_Threadsafe(), v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::DoPointwiseMultiplication(), and v8::bigint::anonymous_namespace{mul-fft.cc}::FFTContainer::FFT_ReturnShuffledThreadsafe().