v8::internal::anonymous_namespace{regexp.cc} Namespace Reference
Classes
struct RegExpCaptureIndexLess
Functions
bool HasFewDifferentCharacters (DirectHandle< String > pattern)
template<typename SChar , typename PChar >
int AtomExecRawImpl (Isolate *isolate, base::Vector< const SChar > subject, base::Vector< const PChar > pattern, int index, RegExpFlags flags, int32_t *output, int output_size, const DisallowGarbageCollection &no_gc)
bool TooMuchRegExpCode (Isolate *isolate, DirectHandle< String > pattern)
Function Documentation
AtomExecRawImpl()
template<typename SChar , typename PChar >
int v8::internal::anonymous_namespace{regexp.cc}::AtomExecRawImpl (Isolate * isolate, base::Vector< const SChar > subject, base::Vector< const PChar > pattern, int index, RegExpFlags flags, int32_t * output, int output_size, const DisallowGarbageCollection & no_gc)
Definition at line 396 of file regexp.cc.
                                                            {
  const int subject_length = subject.length();
  const int pattern_length = pattern.length();
  DCHECK_GT(pattern_length, 0);
  const int max_index = subject_length - pattern_length;
  StringSearch<PChar, SChar> search(isolate, pattern);
  for (int i = 0; i < output_size; i += JSRegExp::kAtomRegisterCount) {
    if constexpr (std::is_same_v<SChar, uint16_t>) {
      if (index > 0 && index < subject_length &&
          ShouldOptionallyStepBackToLeadSurrogate(flags)) {
        // See https://github.com/tc39/ecma262/issues/128 and
        // https://codereview.chromium.org/1608693003.
        if (unibrow::Utf16::IsTrailSurrogate(subject[index]) &&
            unibrow::Utf16::IsLeadSurrogate(subject[index - 1])) {
          index--;
        }
      }
    }
    if (index > max_index) {
      static_assert(RegExp::RE_FAILURE == 0);
      return i / JSRegExp::kAtomRegisterCount; // Return number of matches.
    }
    index = search.Search(subject, index);
    if (index == -1) {
      static_assert(RegExp::RE_FAILURE == 0);
      return i / JSRegExp::kAtomRegisterCount; // Return number of matches.
    } else {
      output[i] = index; // match start
      index += pattern_length;
      output[i + 1] = index; // match end
    }
  }
  return output_size / JSRegExp::kAtomRegisterCount;
}
References DCHECK_GT, v8::internal::flags, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, unibrow::Utf16::IsLeadSurrogate(), unibrow::Utf16::IsTrailSurrogate(), v8::internal::JSRegExp::kAtomRegisterCount, v8::base::Vector< T >::length(), v8::internal::RegExp::RE_FAILURE, v8::internal::anonymous_namespace{simd.cc}::search(), and v8::internal::ShouldOptionallyStepBackToLeadSurrogate().
Referenced by v8::internal::RegExpImpl::AtomExecRaw().
HasFewDifferentCharacters()
bool v8::internal::anonymous_namespace{regexp.cc}::HasFewDifferentCharacters (DirectHandle< String > pattern)
Definition at line 175 of file regexp.cc.
                                                             {
  uint32_t length = std::min(kMaxLookaheadForBoyerMoore, pattern->length());
  if (length <= kPatternTooShortForBoyerMoore) return false;
  const int kMod = 128;
  bool character_found[kMod];
  uint32_t different = 0;
  memset(&character_found[0], 0, sizeof(character_found));
  for (uint32_t i = 0; i < length; i++) {
    int ch = (pattern->Get(i) & (kMod - 1));
    if (!character_found[ch]) {
      character_found[ch] = true;
      different++;
      // We declare a regexp low-alphabet if it has at least 3 times as many
      // characters as it has different characters.
      if (different * 3 > length) return false;
    }
  }
  return true;
}
References v8::internal::regexp_compiler_constants::kMaxLookaheadForBoyerMoore, v8::internal::regexp_compiler_constants::kPatternTooShortForBoyerMoore, and v8::internal::length.
Referenced by v8::internal::RegExp::Compile().
TooMuchRegExpCode()
bool v8::internal::anonymous_namespace{regexp.cc}::TooMuchRegExpCode (Isolate * isolate, DirectHandle< String > pattern)
Definition at line 934 of file regexp.cc.
                                                                       {
  // Limit the space regexps take up on the heap. In order to limit this we
  // would like to keep track of the amount of regexp code on the heap. This
  // is not tracked, however. As a conservative approximation we track the
  // total regexp code compiled including code that has subsequently been freed
  // and the total executable memory at any point.
  static constexpr size_t kRegExpExecutableMemoryLimit = 16 * MB;
  static constexpr size_t kRegExpCompiledLimit = 1 * MB;
  Heap* heap = isolate->heap();
  if (pattern->length() > RegExp::kRegExpTooLargeToOptimize) return true;
  return (isolate->total_regexp_code_generated() > kRegExpCompiledLimit &&
          heap->CommittedMemoryExecutable() > kRegExpExecutableMemoryLimit);
}
References v8::internal::Isolate::heap(), v8::internal::RegExp::kRegExpTooLargeToOptimize, v8::internal::MB, and v8::internal::Isolate::total_regexp_code_generated().
Referenced by v8::internal::RegExpImpl::Compile().