v8::internal::compiler::turboshaft::anonymous_namespace{turbolev-graph-builder.cc} Namespace Reference
Functions
MachineType MachineTypeFor (maglev::ValueRepresentation repr)
Function Documentation
MachineTypeFor()
MachineType v8::internal::compiler::turboshaft::anonymous_namespace{turbolev-graph-builder.cc}::MachineTypeFor (maglev::ValueRepresentation repr)
Definition at line 70 of file turbolev-graph-builder.cc.
                                                           {
  switch (repr) {
    case maglev::ValueRepresentation::kTagged:
      return MachineType::AnyTagged();
    case maglev::ValueRepresentation::kInt32:
      return MachineType::Int32();
    case maglev::ValueRepresentation::kUint32:
      return MachineType::Uint32();
    case maglev::ValueRepresentation::kIntPtr:
      return MachineType::IntPtr();
    case maglev::ValueRepresentation::kFloat64:
      return MachineType::Float64();
    case maglev::ValueRepresentation::kHoleyFloat64:
      return MachineType::HoleyFloat64();
  }
}
References v8::internal::MachineType::AnyTagged(), v8::internal::MachineType::Float64(), v8::internal::MachineType::HoleyFloat64(), v8::internal::MachineType::Int32(), v8::internal::MachineType::IntPtr(), v8::internal::maglev::kFloat64, v8::internal::maglev::kHoleyFloat64, v8::internal::maglev::kInt32, v8::internal::maglev::kIntPtr, v8::internal::maglev::kTagged, v8::internal::maglev::kUint32, and v8::internal::MachineType::Uint32().