v8::internal::anonymous_namespace{keys.cc} Namespace Reference
Classes
class NameComparator
Functions
static bool ContainsOnlyValidKeys (DirectHandle< FixedArray > array)
static int AddKey (Tagged< Object > key, DirectHandle< FixedArray > combined_keys, DirectHandle< DescriptorArray > descs, int nof_descriptors, int target)
static Handle< FixedArray > CombineKeys (Isolate *isolate, Handle< FixedArray > own_keys, Handle< FixedArray > prototype_chain_keys, DirectHandle< JSReceiver > receiver, bool may_have_elements)
void TrySettingEmptyEnumCache (Tagged< JSReceiver > object)
bool CheckAndInitializeEmptyEnumCache (Tagged< JSReceiver > object)
Handle< FixedArray > ReduceFixedArrayTo (Isolate *isolate, Handle< FixedArray > array, int length)
Handle< FixedArray > GetFastEnumPropertyKeys (Isolate *isolate, DirectHandle< JSObject > object)
template<bool fast_properties>
MaybeHandle< FixedArray > GetOwnKeysWithElements (Isolate *isolate, DirectHandle< JSObject > object, GetKeysConversion convert, bool skip_indices)
template<bool skip_symbols>
std::optional< int > CollectOwnPropertyNamesInternal (DirectHandle< JSObject > object, KeyAccumulator *keys, DirectHandle< DescriptorArray > descs, int start_index, int limit)
template<typename Dictionary >
void CommonCopyEnumKeysTo (Isolate *isolate, DirectHandle< Dictionary > dictionary, DirectHandle< FixedArray > storage, KeyCollectionMode mode, KeyAccumulator *accumulator)
template<typename Dictionary >
void CopyEnumKeysTo (Isolate *isolate, DirectHandle< Dictionary > dictionary, DirectHandle< FixedArray > storage, KeyCollectionMode mode, KeyAccumulator *accumulator)
template<> void CopyEnumKeysTo (Isolate *isolate, DirectHandle< SwissNameDictionary > dictionary, DirectHandle< FixedArray > storage, KeyCollectionMode mode, KeyAccumulator *accumulator)
template<class T >
Handle< FixedArray > GetOwnEnumPropertyDictionaryKeys (Isolate *isolate, KeyCollectionMode mode, KeyAccumulator *accumulator, DirectHandle< JSObject > object, Tagged< T > raw_dictionary)
template<typename Dictionary >
ExceptionStatus CollectKeysFromDictionary (DirectHandle< Dictionary > dictionary, KeyAccumulator *keys)
Function Documentation
AddKey()
static int v8::internal::anonymous_namespace{keys.cc}::AddKey (Tagged< Object > key, DirectHandle< FixedArray > combined_keys, DirectHandle< DescriptorArray > descs, int nof_descriptors, int target) [static]
Definition at line 54 of file keys.cc.
                              {
  for (InternalIndex i : InternalIndex::Range(nof_descriptors)) {
    if (descs->GetKey(i) == key) return 0;
  }
  combined_keys->set(target, key);
  return 1;
}
References v8::internal::key.
Referenced by CombineKeys().
CheckAndInitializeEmptyEnumCache()
bool v8::internal::anonymous_namespace{keys.cc}::CheckAndInitializeEmptyEnumCache (Tagged< JSReceiver > object)
Definition at line 333 of file keys.cc.
                                                                 {
  if (object->map()->EnumLength() == kInvalidEnumCacheSentinel) {
    TrySettingEmptyEnumCache(object);
  }
  if (object->map()->EnumLength() != 0) return false;
  DCHECK(IsJSObject(object));
  return !Cast<JSObject>(object)->HasEnumerableElements();
}
References v8::internal::DCHECK(), v8::internal::kInvalidEnumCacheSentinel, and TrySettingEmptyEnumCache().
Referenced by v8::internal::FastKeyAccumulator::Prepare().
CollectKeysFromDictionary()
template<typename Dictionary >
ExceptionStatus v8::internal::anonymous_namespace{keys.cc}::CollectKeysFromDictionary (DirectHandle< Dictionary > dictionary, KeyAccumulator * keys)
Definition at line 945 of file keys.cc.
                                                                {
  Isolate* isolate = keys->isolate();
  ReadOnlyRoots roots(isolate);
  // TODO(jkummerow): Consider using a std::unique_ptr<InternalIndex[]> instead.
  DirectHandle<FixedArray> array =
      isolate->factory()->NewFixedArray(dictionary->NumberOfElements());
  int array_size = 0;
  PropertyFilter filter = keys->filter();
  // Handle enumerable strings in CopyEnumKeysTo.
  DCHECK_NE(keys->filter(), ENUMERABLE_STRINGS);
  {
    DisallowGarbageCollection no_gc;
    for (InternalIndex i : dictionary->IterateEntries()) {
      Tagged<Object> key;
      Tagged<Dictionary> raw_dictionary = *dictionary;
      if (!raw_dictionary->ToKey(roots, i, &key)) continue;
      if (Object::FilterKey(key, filter)) continue;
      PropertyDetails details = raw_dictionary->DetailsAt(i);
      if ((int{details.attributes()} & filter) != 0) {
        AllowGarbageCollection gc;
        // This might allocate, but {key} is not used afterwards.
        keys->AddShadowingKey(key, &gc);
        continue;
      }
      // TODO(emrich): consider storing keys instead of indices into the array
      // in case of ordered dictionary type.
      array->set(array_size++, Smi::FromInt(i.as_int()));
    }
    if (!Dictionary::kIsOrderedDictionaryType) {
      // Sorting only needed if it's an unordered dictionary,
      // otherwise we traversed elements in insertion order
      EnumIndexComparator<Dictionary> cmp(*dictionary);
      // Use AtomicSlot wrapper to ensure that std::sort uses atomic load and
      // store operations that are safe for concurrent marking.
      AtomicSlot start(array->RawFieldOfFirstElement());
      std::sort(start, start + array_size, cmp);
    }
  }
  bool has_seen_symbol = false;
  for (int i = 0; i < array_size; i++) {
    InternalIndex index(Smi::ToInt(array->get(i)));
    Tagged<Object> key = dictionary->NameAt(index);
    if (IsSymbol(key)) {
      has_seen_symbol = true;
      continue;
    }
    ExceptionStatus status = keys->AddKey(key, DO_NOT_CONVERT);
    if (!status) return status;
  }
  if (has_seen_symbol) {
    for (int i = 0; i < array_size; i++) {
      InternalIndex index(Smi::ToInt(array->get(i)));
      Tagged<Object> key = dictionary->NameAt(index);
      if (!IsSymbol(key)) continue;
      ExceptionStatus status = keys->AddKey(key, DO_NOT_CONVERT);
      if (!status) return status;
    }
  }
  return ExceptionStatus::kSuccess;
}
References v8::internal::KeyAccumulator::AddKey(), v8::internal::KeyAccumulator::AddShadowingKey(), v8::internal::PropertyDetails::attributes(), DCHECK_NE, v8::internal::DO_NOT_CONVERT, v8::internal::ENUMERABLE_STRINGS, v8::internal::Isolate::factory(), v8::internal::KeyAccumulator::filter(), v8::internal::Object::FilterKey(), v8::internal::Smi::FromInt(), v8::internal::index, v8::internal::KeyAccumulator::isolate(), v8::internal::key, v8::internal::kSuccess, v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::sort(), v8::internal::status, and v8::internal::Smi::ToInt().
Referenced by v8::internal::KeyAccumulator::CollectOwnJSProxyKeys(), v8::internal::KeyAccumulator::CollectOwnPropertyNames(), and v8::internal::KeyAccumulator::CollectPrivateNames().
CollectOwnPropertyNamesInternal()
template<bool skip_symbols>
std::optional<int> v8::internal::anonymous_namespace{keys.cc}::CollectOwnPropertyNamesInternal (DirectHandle< JSObject > object, KeyAccumulator * keys, DirectHandle< DescriptorArray > descs, int start_index, int limit)
Definition at line 801 of file keys.cc.
                                                                     {
  AllowGarbageCollection allow_gc;
  int first_skipped = -1;
  PropertyFilter filter = keys->filter();
  KeyCollectionMode mode = keys->mode();
  for (InternalIndex i : InternalIndex::Range(start_index, limit)) {
    bool is_shadowing_key = false;
    PropertyDetails details = descs->GetDetails(i);
    if ((int{details.attributes()} & filter) != 0) {
      if (mode == KeyCollectionMode::kIncludePrototypes) {
        is_shadowing_key = true;
      } else {
        continue;
      }
    }
    Tagged<Name> key = descs->GetKey(i);
    if (skip_symbols == IsSymbol(key)) {
      if (first_skipped == -1) first_skipped = i.as_int();
      continue;
    }
    if (Object::FilterKey(key, keys->filter())) continue;
    if (is_shadowing_key) {
      // This might allocate, but {key} is not used afterwards.
      keys->AddShadowingKey(key, &allow_gc);
      continue;
    } else {
      if (keys->AddKey(key, DO_NOT_CONVERT) != ExceptionStatus::kSuccess) {
        return std::optional<int>();
      }
    }
  }
  return first_skipped;
}
References v8::internal::KeyAccumulator::AddKey(), v8::internal::KeyAccumulator::AddShadowingKey(), v8::internal::PropertyDetails::attributes(), v8::internal::DO_NOT_CONVERT, v8::internal::KeyAccumulator::filter(), v8::internal::Object::FilterKey(), v8::internal::key, v8::internal::kIncludePrototypes, v8::internal::kSuccess, v8::internal::KeyAccumulator::mode(), and mode().
CombineKeys()
static Handle<FixedArray> v8::internal::anonymous_namespace{keys.cc}::CombineKeys (Isolate * isolate, Handle< FixedArray > own_keys, Handle< FixedArray > prototype_chain_keys, DirectHandle< JSReceiver > receiver, bool may_have_elements) [static]
Definition at line 64 of file keys.cc.
                                                              {
  int prototype_chain_keys_length = prototype_chain_keys->length();
  if (prototype_chain_keys_length == 0) return own_keys;
  Tagged<Map> map = receiver->map();
  int nof_descriptors = map->NumberOfOwnDescriptors();
  if (nof_descriptors == 0 && !may_have_elements) return prototype_chain_keys;
  DirectHandle<DescriptorArray> descs(map->instance_descriptors(isolate),
                                      isolate);
  int own_keys_length = own_keys.is_null() ? 0 : own_keys->length();
  Handle<FixedArray> combined_keys = isolate->factory()->NewFixedArray(
      own_keys_length + prototype_chain_keys_length);
  if (own_keys_length != 0) {
    FixedArray::CopyElements(isolate, *combined_keys, 0, *own_keys, 0,
                             own_keys_length);
  }
  int target_keys_length = own_keys_length;
  for (int i = 0; i < prototype_chain_keys_length; i++) {
    target_keys_length += AddKey(prototype_chain_keys->get(i), combined_keys,
                                 descs, nof_descriptors, target_keys_length);
  }
  return FixedArray::RightTrimOrEmpty(isolate, combined_keys,
                                      target_keys_length);
}
References AddKey(), v8::internal::FixedArray::CopyElements(), v8::internal::Isolate::factory(), v8::internal::HandleBase::is_null(), and v8::internal::FactoryBase< Impl >::NewFixedArray().
Referenced by v8::internal::FastKeyAccumulator::GetKeysWithPrototypeInfoCache().
CommonCopyEnumKeysTo()
template<typename Dictionary >
void v8::internal::anonymous_namespace{keys.cc}::CommonCopyEnumKeysTo (Isolate * isolate, DirectHandle< Dictionary > dictionary, DirectHandle< FixedArray > storage, KeyCollectionMode mode, KeyAccumulator * accumulator)
Definition at line 842 of file keys.cc.
                                                                               {
  DCHECK_IMPLIES(mode != KeyCollectionMode::kOwnOnly, accumulator != nullptr);
  int length = storage->length();
  int properties = 0;
  ReadOnlyRoots roots(isolate);
  AllowGarbageCollection allow_gc;
  for (InternalIndex i : dictionary->IterateEntries()) {
    Tagged<Object> key;
    if (!dictionary->ToKey(roots, i, &key)) continue;
    bool is_shadowing_key = false;
    if (IsSymbol(key)) continue;
    PropertyDetails details = dictionary->DetailsAt(i);
    if (details.IsDontEnum()) {
      if (mode == KeyCollectionMode::kIncludePrototypes) {
        is_shadowing_key = true;
      } else {
        continue;
      }
    }
    if (is_shadowing_key) {
      // This might allocate, but {key} is not used afterwards.
      accumulator->AddShadowingKey(key, &allow_gc);
      continue;
    } else {
      if (Dictionary::kIsOrderedDictionaryType) {
        storage->set(properties, Cast<Name>(key));
      } else {
        // If the dictionary does not store elements in enumeration order,
        // we need to sort it afterwards in CopyEnumKeysTo. To enable this we
        // need to store indices at this point, rather than the values at the
        // given indices.
        storage->set(properties, Smi::FromInt(i.as_int()));
      }
    }
    properties++;
    if (mode == KeyCollectionMode::kOwnOnly && properties == length) break;
  }
  CHECK_EQ(length, properties);
}
References v8::internal::KeyAccumulator::AddShadowingKey(), CHECK_EQ, DCHECK_IMPLIES, v8::internal::Smi::FromInt(), v8::internal::PropertyDetails::IsDontEnum(), v8::internal::key, v8::internal::kIncludePrototypes, v8::internal::kOwnOnly, v8::internal::length, and mode().
ContainsOnlyValidKeys()
static bool v8::internal::anonymous_namespace{keys.cc}::ContainsOnlyValidKeys (DirectHandle< FixedArray > array) [static]
Definition at line 45 of file keys.cc.
                                                                  {
  int len = array->length();
  for (int i = 0; i < len; i++) {
    Tagged<Object> e = array->get(i);
    if (!(IsName(e) || IsNumber(e))) return false;
  }
  return true;
}
References v8::internal::IsNumber().
Referenced by v8::internal::KeyAccumulator::GetKeys().
CopyEnumKeysTo() [1/2]
template<typename Dictionary >
void v8::internal::anonymous_namespace{keys.cc}::CopyEnumKeysTo (Isolate * isolate, DirectHandle< Dictionary > dictionary, DirectHandle< FixedArray > storage, KeyCollectionMode mode, KeyAccumulator * accumulator)
Definition at line 890 of file keys.cc.
                                                 {
  static_assert(!Dictionary::kIsOrderedDictionaryType);
  CommonCopyEnumKeysTo<Dictionary>(isolate, dictionary, storage, mode,
                                   accumulator);
  int length = storage->length();
  DisallowGarbageCollection no_gc;
  Tagged<Dictionary> raw_dictionary = *dictionary;
  Tagged<FixedArray> raw_storage = *storage;
  EnumIndexComparator<Dictionary> cmp(raw_dictionary);
  // Use AtomicSlot wrapper to ensure that std::sort uses atomic load and
  // store operations that are safe for concurrent marking.
  AtomicSlot start(storage->RawFieldOfFirstElement());
  std::sort(start, start + length, cmp);
  for (int i = 0; i < length; i++) {
    InternalIndex index(Smi::ToInt(raw_storage->get(i)));
    raw_storage->set(i, raw_dictionary->NameAt(index));
  }
}
References v8::internal::index, v8::internal::length, mode(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::sort(), and v8::internal::Smi::ToInt().
CopyEnumKeysTo() [2/2]
template<>
void v8::internal::anonymous_namespace{keys.cc}::CopyEnumKeysTo (Isolate * isolate, DirectHandle< SwissNameDictionary > dictionary, DirectHandle< FixedArray > storage, KeyCollectionMode mode, KeyAccumulator * accumulator)
Definition at line 915 of file keys.cc.
                                                 {
  CommonCopyEnumKeysTo<SwissNameDictionary>(isolate, dictionary, storage, mode,
                                            accumulator);
  // No need to sort, as CommonCopyEnumKeysTo on OrderedNameDictionary
  // adds entries to |storage| in the dict's insertion order
  // Further, the template argument true above means that |storage|
  // now contains the actual values from |dictionary|, rather than indices.
}
References mode().
Referenced by GetOwnEnumPropertyDictionaryKeys().
GetFastEnumPropertyKeys()
Handle<FixedArray> v8::internal::anonymous_namespace{keys.cc}::GetFastEnumPropertyKeys (Isolate * isolate, DirectHandle< JSObject > object)
Definition at line 391 of file keys.cc.
                                                                          {
  DirectHandle<Map> map(object->map(), isolate);
  Handle<FixedArray> keys(
      map->instance_descriptors(isolate)->enum_cache()->keys(), isolate);
  // Check if the {map} has a valid enum length, which implies that it
  // must have a valid enum cache as well.
  int enum_length = map->EnumLength();
  if (enum_length != kInvalidEnumCacheSentinel) {
    DCHECK(map->OnlyHasSimpleProperties());
    DCHECK_LE(enum_length, keys->length());
    DCHECK_EQ(enum_length, map->NumberOfEnumerableProperties());
    isolate->counters()->enum_cache_hits()->Increment();
    return ReduceFixedArrayTo(isolate, keys, enum_length);
  }
  // Determine the actual number of enumerable properties of the {map}.
  enum_length = map->NumberOfEnumerableProperties();
  // Check if there's already a shared enum cache on the {map}s
  // DescriptorArray with sufficient number of entries.
  if (enum_length <= keys->length()) {
    if (map->OnlyHasSimpleProperties()) map->SetEnumLength(enum_length);
    isolate->counters()->enum_cache_hits()->Increment();
    return ReduceFixedArrayTo(isolate, keys, enum_length);
  }
  return FastKeyAccumulator::InitializeFastPropertyEnumCache(isolate, map,
                                                             enum_length);
}
References v8::internal::Isolate::counters(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LE, v8::internal::FastKeyAccumulator::InitializeFastPropertyEnumCache(), v8::internal::kInvalidEnumCacheSentinel, v8::internal::length, and ReduceFixedArrayTo().
Referenced by v8::internal::KeyAccumulator::GetOwnEnumPropertyKeys(), GetOwnKeysWithElements(), and v8::internal::FastKeyAccumulator::GetOwnKeysWithUninitializedEnumLength().
GetOwnEnumPropertyDictionaryKeys()
template<class T >
Handle<FixedArray> v8::internal::anonymous_namespace{keys.cc}::GetOwnEnumPropertyDictionaryKeys (Isolate * isolate, KeyCollectionMode mode, KeyAccumulator * accumulator, DirectHandle< JSObject > object, Tagged< T > raw_dictionary)
Definition at line 929 of file keys.cc.
                                                             {
  DirectHandle<T> dictionary(raw_dictionary, isolate);
  if (dictionary->NumberOfElements() == 0) {
    return isolate->factory()->empty_fixed_array();
  }
  int length = dictionary->NumberOfEnumerableProperties();
  Handle<FixedArray> storage = isolate->factory()->NewFixedArray(length);
  CopyEnumKeysTo(isolate, dictionary, storage, mode, accumulator);
  return storage;
}
References CopyEnumKeysTo(), v8::internal::Isolate::factory(), v8::internal::length, mode(), and v8::internal::FactoryBase< Impl >::NewFixedArray().
Referenced by v8::internal::KeyAccumulator::CollectOwnPropertyNames(), and v8::internal::KeyAccumulator::GetOwnEnumPropertyKeys().
GetOwnKeysWithElements()
template<bool fast_properties>
MaybeHandle<FixedArray> v8::internal::anonymous_namespace{keys.cc}::GetOwnKeysWithElements (Isolate * isolate, DirectHandle< JSObject > object, GetKeysConversion convert, bool skip_indices)
Definition at line 424 of file keys.cc.
                                                                  {
  Handle<FixedArray> keys;
  if (fast_properties) {
    keys = GetFastEnumPropertyKeys(isolate, object);
  } else {
    // TODO(cbruni): preallocate big enough array to also hold elements.
    keys = KeyAccumulator::GetOwnEnumPropertyKeys(isolate, object);
  }
  MaybeHandle<FixedArray> result;
  if (skip_indices) {
    result = keys;
  } else {
    ElementsAccessor* accessor = object->GetElementsAccessor(isolate);
    result = accessor->PrependElementIndices(isolate, object, keys, convert,
                                             ONLY_ENUMERABLE);
  }
  if (v8_flags.trace_for_in_enumerate) {
    PrintF("| strings=%d symbols=0 elements=%u || prototypes>=1 ||\n",
           keys->length(), result.ToHandleChecked()->length() - keys->length());
  }
  return result;
}
References GetFastEnumPropertyKeys(), v8::internal::KeyAccumulator::GetOwnEnumPropertyKeys(), v8::internal::ONLY_ENUMERABLE, v8::internal::ElementsAccessor::PrependElementIndices(), v8::internal::PrintF(), v8::base::internal::result, and v8::internal::v8_flags.
ReduceFixedArrayTo()
Handle<FixedArray> v8::internal::anonymous_namespace{keys.cc}::ReduceFixedArrayTo (Isolate * isolate, Handle< FixedArray > array, int length)
Definition at line 382 of file keys.cc.
                                                                            {
  DCHECK_LE(length, array->length());
  if (array->length() == length) return array;
  return isolate->factory()->CopyFixedArrayUpTo(array, length);
}
References v8::internal::Factory::CopyFixedArrayUpTo(), DCHECK_LE, v8::internal::Isolate::factory(), and v8::internal::length.
Referenced by GetFastEnumPropertyKeys().
TrySettingEmptyEnumCache()
void v8::internal::anonymous_namespace{keys.cc}::TrySettingEmptyEnumCache (Tagged< JSReceiver > object)
Definition at line 324 of file keys.cc.
                                                         {
  Tagged<Map> map = object->map();
  DCHECK_EQ(kInvalidEnumCacheSentinel, map->EnumLength());
  if (!map->OnlyHasSimpleProperties()) return;
  DCHECK(IsJSObjectMap(map)); // Implied by {OnlyHasSimpleProperties}.
  if (map->NumberOfEnumerableProperties() > 0) return;
  map->SetEnumLength(0);
}
References v8::internal::DCHECK(), DCHECK_EQ, and v8::internal::kInvalidEnumCacheSentinel.
Referenced by CheckAndInitializeEmptyEnumCache().