v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc} Namespace Reference
Classes
struct ExtendingLoadMatcher
struct CbzOrTbzMatchTrait
struct CbzOrTbzMatchTrait< 32 >
struct CbzOrTbzMatchTrait< 64 >
struct TestAndBranchMatcherTurboshaft
Typedefs
using CanCommuteField = base::BitField8< bool, 1, 1 >
using MustCommuteCondField = base::BitField8< bool, 2, 1 >
using IsComparisonField = base::BitField8< bool, 3, 1 >
using IsAddSubField = base::BitField8< bool, 4, 1 >
Functions
void VisitRR (InstructionSelector *selector, ArchOpcode opcode, OpIndex node)
void VisitRRR (InstructionSelector *selector, InstructionCode opcode, OpIndex node)
void VisitRRO (InstructionSelector *selector, ArchOpcode opcode, OpIndex node, ImmediateMode operand_mode)
bool TryMatchExtendingLoad (InstructionSelector *selector, OpIndex node)
bool TryEmitExtendingLoad (InstructionSelector *selector, OpIndex node)
bool TryMatchAnyShift (InstructionSelector *selector, OpIndex node, OpIndex input_node, InstructionCode *opcode, bool try_ror, RegisterRepresentation rep)
bool TryMatchBitwiseAndSmallMask (OperationMatcher &matcher, OpIndex op, OpIndex *left, int32_t *mask)
bool TryMatchSignExtendShift (InstructionSelector *selector, OpIndex op, OpIndex *left, int32_t *shift_by)
bool TryMatchAnyExtend (Arm64OperandGenerator *g, InstructionSelector *selector, OpIndex node, OpIndex left_node, OpIndex right_node, InstructionOperand *left_op, InstructionOperand *right_op, InstructionCode *opcode)
bool TryMatchLoadStoreShift (Arm64OperandGenerator *g, InstructionSelector *selector, MemoryRepresentation rep, OpIndex node, OpIndex index, InstructionOperand *index_op, InstructionOperand *shift_immediate_op)
uint8_t GetBinopProperties (InstructionCode opcode)
template<typename Matcher >
void VisitBinop (InstructionSelector *selector, OpIndex node, ArchOpcode opcode, ImmediateMode operand_mode)
void VisitBinopImpl (InstructionSelector *selector, OpIndex binop_idx, OpIndex left_node, OpIndex right_node, RegisterRepresentation rep, InstructionCode opcode, ImmediateMode operand_mode, FlagsContinuation *cont)
void VisitBinop (InstructionSelector *selector, OpIndex binop_idx, RegisterRepresentation rep, InstructionCode opcode, ImmediateMode operand_mode, FlagsContinuation *cont)
void VisitBinop (InstructionSelector *selector, OpIndex node, RegisterRepresentation rep, ArchOpcode opcode, ImmediateMode operand_mode)
std::tuple< OpIndex, OpIndex > GetBinopLeftRightCstOnTheRight (InstructionSelector *selector, const WordBinopOp &binop)
void VisitAddSub (InstructionSelector *selector, OpIndex node, ArchOpcode opcode, ArchOpcode negate_opcode)
template<typename Matcher >
int32_t LeftShiftForReducedMultiply (Matcher *m)
int32_t LeftShiftForReducedMultiply (InstructionSelector *selector, OpIndex rhs)
template<typename MultiplyOpmaskT >
bool TryEmitMultiplyAdd (InstructionSelector *selector, OpIndex add, OpIndex lhs, OpIndex rhs, InstructionCode madd_opcode)
bool TryEmitMultiplyAddInt32 (InstructionSelector *selector, OpIndex add, OpIndex lhs, OpIndex rhs)
bool TryEmitMultiplyAddInt64 (InstructionSelector *selector, OpIndex add, OpIndex lhs, OpIndex rhs)
template<typename SubtractOpmaskT >
bool TryEmitMultiplyNegate (InstructionSelector *selector, OpIndex mul, OpIndex lhs, OpIndex rhs, InstructionCode mneg_opcode)
bool TryEmitMultiplyNegateInt32 (InstructionSelector *selector, OpIndex mul, OpIndex lhs, OpIndex rhs)
bool TryEmitMultiplyNegateInt64 (InstructionSelector *selector, OpIndex mul, OpIndex lhs, OpIndex rhs)
template<typename MultiplyOpmaskT >
bool TryEmitMultiplySub (InstructionSelector *selector, OpIndex node, InstructionCode msub_opbocde)
std::tuple< InstructionCode, ImmediateMode > GetStoreOpcodeAndImmediate (MemoryRepresentation stored_rep, bool paired)
bool TryEmitBitfieldExtract32 (InstructionSelector *selector, OpIndex node)
void EmitInt32MulWithOverflow (InstructionSelector *selector, OpIndex node, FlagsContinuation *cont)
void EmitInt64MulWithOverflow (InstructionSelector *selector, OpIndex node, FlagsContinuation *cont)
void VisitCompare (InstructionSelector *selector, InstructionCode opcode, InstructionOperand left, InstructionOperand right, FlagsContinuation *cont)
bool CanUseFlagSettingBinop (FlagsCondition cond)
FlagsCondition MapForFlagSettingBinop (FlagsCondition cond)
void MaybeReplaceCmpZeroWithFlagSettingBinop (InstructionSelector *selector, OpIndex *node, OpIndex binop, ArchOpcode *opcode, FlagsCondition cond, FlagsContinuation *cont, ImmediateMode *immediate_mode)
FlagsCondition MapForTbz (FlagsCondition cond)
FlagsCondition MapForCbz (FlagsCondition cond)
void EmitBranchOrDeoptimize (InstructionSelector *selector, InstructionCode opcode, InstructionOperand value, FlagsContinuation *cont)
template<int N>
bool TryEmitCbzOrTbz (InstructionSelector *selector, OpIndex node, typename CbzOrTbzMatchTrait< N >::IntegralType value, OpIndex user, FlagsCondition cond, FlagsContinuation *cont)
void VisitWordCompare (InstructionSelector *selector, OpIndex node, InstructionCode opcode, FlagsContinuation *cont, ImmediateMode immediate_mode)
void VisitWord32Compare (InstructionSelector *selector, OpIndex node, FlagsContinuation *cont)
void VisitWordTest (InstructionSelector *selector, OpIndex node, InstructionCode opcode, FlagsContinuation *cont)
void VisitWord32Test (InstructionSelector *selector, OpIndex node, FlagsContinuation *cont)
void VisitWord64Test (InstructionSelector *selector, OpIndex node, FlagsContinuation *cont)
void VisitFloat32Compare (InstructionSelector *selector, OpIndex node, FlagsContinuation *cont)
void VisitFloat64Compare (InstructionSelector *selector, OpIndex node, FlagsContinuation *cont)
void VisitAtomicExchange (InstructionSelector *selector, OpIndex node, ArchOpcode opcode, AtomicWidth width, MemoryAccessKind access_kind)
void VisitAtomicCompareExchange (InstructionSelector *selector, OpIndex node, ArchOpcode opcode, AtomicWidth width, MemoryAccessKind access_kind)
void VisitAtomicLoad (InstructionSelector *selector, OpIndex node, AtomicWidth width)
AtomicStoreParameters AtomicStoreParametersOf (InstructionSelector *selector, OpIndex node)
void VisitAtomicStore (InstructionSelector *selector, OpIndex node, AtomicWidth width)
void VisitAtomicBinop (InstructionSelector *selector, OpIndex node, ArchOpcode opcode, AtomicWidth width, MemoryAccessKind access_kind)
Typedef Documentation
CanCommuteField
using v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::CanCommuteField = typedef base::BitField8<bool, 1, 1>
Definition at line 497 of file instruction-selector-arm64.cc.
IsAddSubField
using v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::IsAddSubField = typedef base::BitField8<bool, 4, 1>
Definition at line 505 of file instruction-selector-arm64.cc.
IsComparisonField
using v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::IsComparisonField = typedef base::BitField8<bool, 3, 1>
Definition at line 503 of file instruction-selector-arm64.cc.
MustCommuteCondField
using v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::MustCommuteCondField = typedef base::BitField8<bool, 2, 1>
Definition at line 500 of file instruction-selector-arm64.cc.
Function Documentation
AtomicStoreParametersOf()
AtomicStoreParameters v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::AtomicStoreParametersOf (InstructionSelector * selector, OpIndex node)
Definition at line 3684 of file instruction-selector-arm64.cc.
                                                            {
  auto store = selector->store_view(node);
  return AtomicStoreParameters(store.stored_rep().representation(),
                               store.stored_rep().write_barrier_kind(),
                               store.memory_order().value(),
                               store.access_kind());
}
References store(), and v8::internal::compiler::InstructionSelector::store_view().
CanUseFlagSettingBinop()
bool v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::CanUseFlagSettingBinop (FlagsCondition cond)
Definition at line 3130 of file instruction-selector-arm64.cc.
                                                 {
  switch (cond) {
    case kEqual:
    case kNotEqual:
    case kSignedLessThan:
    case kSignedGreaterThanOrEqual:
    case kUnsignedLessThanOrEqual: // x <= 0 -> x == 0
    case kUnsignedGreaterThan: // x > 0 -> x != 0
      return true;
    default:
      return false;
  }
}
References v8::internal::kEqual, v8::internal::compiler::kNotEqual, v8::internal::compiler::kSignedGreaterThanOrEqual, v8::internal::compiler::kSignedLessThan, v8::internal::compiler::kUnsignedGreaterThan, and v8::internal::compiler::kUnsignedLessThanOrEqual.
Referenced by MapForFlagSettingBinop(), and VisitWord32Compare().
EmitBranchOrDeoptimize()
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::EmitBranchOrDeoptimize (InstructionSelector * selector, InstructionCode opcode, InstructionOperand value, FlagsContinuation * cont)
Definition at line 3244 of file instruction-selector-arm64.cc.
                                                     {
  DCHECK(cont->IsBranch() || cont->IsDeoptimize());
  if ((cont->IsBranch() && cont->hint() != BranchHint::kNone) ||
      cont->IsDeoptimize()) {
    opcode |= BranchHintField::encode(true);
  }
  selector->EmitWithContinuation(opcode, value, cont);
}
References v8::internal::DCHECK(), v8::internal::compiler::InstructionSelector::EmitWithContinuation(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::FlagsContinuation::hint(), v8::internal::compiler::FlagsContinuation::IsBranch(), v8::internal::compiler::FlagsContinuation::IsDeoptimize(), v8::internal::kNone, and v8::internal::value.
Referenced by TryEmitCbzOrTbz().
EmitInt32MulWithOverflow()
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::EmitInt32MulWithOverflow (InstructionSelector * selector, OpIndex node, FlagsContinuation * cont)
Definition at line 2536 of file instruction-selector-arm64.cc.
                                                       {
  Arm64OperandGenerator g(selector);
  const OverflowCheckedBinopOp& mul =
      selector->Get(node).Cast<OverflowCheckedBinopOp>();
  InstructionOperand result = g.DefineAsRegister(node);
  InstructionOperand left = g.UseRegister(mul.left());
  int32_t constant_rhs;
  if (selector->MatchIntegralWord32Constant(mul.right(), &constant_rhs) &&
      base::bits::IsPowerOfTwo(constant_rhs)) {
    // Sign extend the bottom 32 bits and shift left.
    int32_t shift = base::bits::WhichPowerOfTwo(constant_rhs);
    selector->Emit(kArm64Sbfiz, result, left, g.TempImmediate(shift),
                   g.TempImmediate(32));
  } else {
    InstructionOperand right = g.UseRegister(mul.right());
    selector->Emit(kArm64Smull, result, left, right);
  }
  InstructionCode opcode =
      kArm64Cmp | AddressingModeField::encode(kMode_Operand2_R_SXTW);
  selector->EmitWithContinuation(opcode, result, result, cont);
}
References v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::InstructionSelector::Emit(), v8::internal::compiler::InstructionSelector::EmitWithContinuation(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::base::bits::IsPowerOfTwo(), v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::left(), v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralWord32Constant(), v8::base::internal::result, v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::right(), v8::internal::compiler::OperandGenerator::TempImmediate(), v8::internal::compiler::OperandGenerator::UseRegister(), and v8::base::bits::WhichPowerOfTwo().
EmitInt64MulWithOverflow()
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::EmitInt64MulWithOverflow (InstructionSelector * selector, OpIndex node, FlagsContinuation * cont)
Definition at line 2561 of file instruction-selector-arm64.cc.
                                                       {
  Arm64OperandGenerator g(selector);
  const OverflowCheckedBinopOp& op =
      selector->Cast<OverflowCheckedBinopOp>(node);
  InstructionOperand result = g.DefineAsRegister(node);
  InstructionOperand left = g.UseRegister(op.left());
  InstructionOperand high = g.TempRegister();
  InstructionOperand right = g.UseRegister(op.right());
  selector->Emit(kArm64Mul, result, left, right);
  selector->Emit(kArm64Smulh, high, left, right);
  // Test whether {high} is a sign-extension of {result}.
  InstructionCode opcode =
      kArm64Cmp | AddressingModeField::encode(kMode_Operand2_R_ASR_I);
  selector->EmitWithContinuation(opcode, high, result, g.TempImmediate(63),
                                 cont);
}
References v8::internal::compiler::turboshaft::OperationMatcher::Cast(), v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::InstructionSelector::Emit(), v8::internal::compiler::InstructionSelector::EmitWithContinuation(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::left(), v8::base::internal::result, v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::right(), v8::internal::compiler::OperandGenerator::TempImmediate(), v8::internal::compiler::OperandGenerator::TempRegister(), and v8::internal::compiler::OperandGenerator::UseRegister().
GetBinopLeftRightCstOnTheRight()
std::tuple<OpIndex, OpIndex> v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::GetBinopLeftRightCstOnTheRight (InstructionSelector * selector, const WordBinopOp & binop)
Definition at line 666 of file instruction-selector-arm64.cc.
                                                             {
  OpIndex left = binop.left();
  OpIndex right = binop.right();
  if (!selector->Is<ConstantOp>(right) &&
      WordBinopOp::IsCommutative(binop.kind) &&
      selector->Is<ConstantOp>(left)) {
    std::swap(left, right);
  }
  return {left, right};
}
References v8::internal::compiler::turboshaft::OperationMatcher::Is(), v8::internal::compiler::turboshaft::WordBinopOp::IsCommutative(), v8::internal::compiler::turboshaft::WordBinopOp::kind, v8::internal::compiler::turboshaft::WordBinopOp::left(), and v8::internal::compiler::turboshaft::WordBinopOp::right().
Referenced by VisitAddSub().
GetBinopProperties()
uint8_t v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::GetBinopProperties (InstructionCode opcode)
Definition at line 508 of file instruction-selector-arm64.cc.
                                                   {
  uint8_t result = 0;
  switch (opcode) {
    case kArm64Cmp32:
    case kArm64Cmp:
      // We can commute CMP by switching the inputs and commuting
      // the flags continuation.
      result = CanCommuteField::update(result, true);
      result = MustCommuteCondField::update(result, true);
      result = IsComparisonField::update(result, true);
      // The CMP and CMN instructions are encoded as SUB or ADD
      // with zero output register, and therefore support the same
      // operand modes.
      result = IsAddSubField::update(result, true);
      break;
    case kArm64Cmn32:
    case kArm64Cmn:
      result = CanCommuteField::update(result, true);
      result = IsComparisonField::update(result, true);
      result = IsAddSubField::update(result, true);
      break;
    case kArm64Add32:
    case kArm64Add:
      result = CanCommuteField::update(result, true);
      result = IsAddSubField::update(result, true);
      break;
    case kArm64Sub32:
    case kArm64Sub:
      result = IsAddSubField::update(result, true);
      break;
    case kArm64Tst32:
    case kArm64Tst:
      result = CanCommuteField::update(result, true);
      result = IsComparisonField::update(result, true);
      break;
    case kArm64And32:
    case kArm64And:
    case kArm64Or32:
    case kArm64Or:
    case kArm64Eor32:
    case kArm64Eor:
      result = CanCommuteField::update(result, true);
      break;
    default:
      UNREACHABLE();
  }
  DCHECK_IMPLIES(MustCommuteCondField::decode(result),
                 CanCommuteField::decode(result));
  return result;
}
References DCHECK_IMPLIES, v8::base::internal::result, and v8::internal::UNREACHABLE().
Referenced by VisitBinopImpl().
GetStoreOpcodeAndImmediate()
std::tuple<InstructionCode, ImmediateMode> v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::GetStoreOpcodeAndImmediate (MemoryRepresentation stored_rep, bool paired)
Definition at line 811 of file instruction-selector-arm64.cc.
                                                  {
  switch (stored_rep) {
    case MemoryRepresentation::Int8():
    case MemoryRepresentation::Uint8():
      CHECK(!paired);
      return {kArm64Strb, kLoadStoreImm8};
    case MemoryRepresentation::Int16():
    case MemoryRepresentation::Uint16():
      CHECK(!paired);
      return {kArm64Strh, kLoadStoreImm16};
    case MemoryRepresentation::Int32():
    case MemoryRepresentation::Uint32():
      return {paired ? kArm64StrWPair : kArm64StrW, kLoadStoreImm32};
    case MemoryRepresentation::Int64():
    case MemoryRepresentation::Uint64():
      return {paired ? kArm64StrPair : kArm64Str, kLoadStoreImm64};
    case MemoryRepresentation::Float16():
      CHECK(!paired);
      return {kArm64StrH, kLoadStoreImm16};
    case MemoryRepresentation::Float32():
      CHECK(!paired);
      return {kArm64StrS, kLoadStoreImm32};
    case MemoryRepresentation::Float64():
      CHECK(!paired);
      return {kArm64StrD, kLoadStoreImm64};
    case MemoryRepresentation::AnyTagged():
    case MemoryRepresentation::TaggedPointer():
    case MemoryRepresentation::TaggedSigned():
      if (paired) {
        // There is an inconsistency here on how we treat stores vs. paired
        // stores. In the normal store case we have special opcodes for
        // compressed fields and the backend decides whether to write 32 or 64
        // bits. However, for pairs this does not make sense, since the
        // paired values could have different representations (e.g.,
        // compressed paired with word32). Therefore, we decide on the actual
        // machine representation already in instruction selection.
#ifdef V8_COMPRESS_POINTERS
        static_assert(ElementSizeLog2Of(MachineRepresentation::kTagged) == 2);
        return {kArm64StrWPair, kLoadStoreImm32};
#else
        static_assert(ElementSizeLog2Of(MachineRepresentation::kTagged) == 3);
        return {kArm64StrPair, kLoadStoreImm64};
#endif
      }
      return {kArm64StrCompressTagged,
              COMPRESS_POINTERS_BOOL ? kLoadStoreImm32 : kLoadStoreImm64};
    case MemoryRepresentation::AnyUncompressedTagged():
    case MemoryRepresentation::UncompressedTaggedPointer():
    case MemoryRepresentation::UncompressedTaggedSigned():
      CHECK(!paired);
      return {kArm64Str, kLoadStoreImm64};
    case MemoryRepresentation::ProtectedPointer():
      // We never store directly to protected pointers from generated code.
      UNREACHABLE();
    case MemoryRepresentation::IndirectPointer():
      return {kArm64StrIndirectPointer, kLoadStoreImm32};
    case MemoryRepresentation::SandboxedPointer():
      CHECK(!paired);
      return {kArm64StrEncodeSandboxedPointer, kLoadStoreImm64};
    case MemoryRepresentation::Simd128():
      CHECK(!paired);
      return {kArm64StrQ, kLoadStoreImm128};
    case MemoryRepresentation::Simd256():
      UNREACHABLE();
  }
}
References v8::internal::compiler::turboshaft::MemoryRepresentation::AnyTagged(), v8::internal::compiler::turboshaft::MemoryRepresentation::AnyUncompressedTagged(), CHECK, COMPRESS_POINTERS_BOOL, v8::internal::ElementSizeLog2Of(), v8::internal::compiler::turboshaft::MemoryRepresentation::Float16(), v8::internal::compiler::turboshaft::MemoryRepresentation::Float32(), v8::internal::compiler::turboshaft::MemoryRepresentation::Float64(), v8::internal::compiler::turboshaft::MemoryRepresentation::IndirectPointer(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int16(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int32(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int64(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int8(), v8::internal::compiler::kLoadStoreImm128, v8::internal::compiler::kLoadStoreImm16, v8::internal::compiler::kLoadStoreImm32, v8::internal::compiler::kLoadStoreImm64, v8::internal::compiler::kLoadStoreImm8, v8::internal::kTagged, v8::internal::compiler::turboshaft::MemoryRepresentation::ProtectedPointer(), v8::internal::compiler::turboshaft::MemoryRepresentation::SandboxedPointer(), v8::internal::compiler::turboshaft::MemoryRepresentation::Simd128(), v8::internal::compiler::turboshaft::MemoryRepresentation::Simd256(), v8::internal::compiler::turboshaft::MemoryRepresentation::TaggedPointer(), v8::internal::compiler::turboshaft::MemoryRepresentation::TaggedSigned(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint16(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint32(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint64(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint8(), v8::internal::compiler::turboshaft::MemoryRepresentation::UncompressedTaggedPointer(), v8::internal::compiler::turboshaft::MemoryRepresentation::UncompressedTaggedSigned(), and v8::internal::UNREACHABLE().
LeftShiftForReducedMultiply() [1/2]
int32_t v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::LeftShiftForReducedMultiply (InstructionSelector * selector, OpIndex rhs)
Definition at line 715 of file instruction-selector-arm64.cc.
                                                 {
  Arm64OperandGenerator g(selector);
  if (auto constant = g.GetOptionalIntegerConstant(rhs)) {
    int64_t value_minus_one = constant.value() - 1;
    if (base::bits::IsPowerOfTwo(value_minus_one)) {
      return base::bits::WhichPowerOfTwo(value_minus_one);
    }
  }
  return 0;
}
References v8::internal::compiler::Arm64OperandGenerator::GetOptionalIntegerConstant(), v8::base::bits::IsPowerOfTwo(), and v8::base::bits::WhichPowerOfTwo().
Referenced by TryEmitMultiplyAdd(), and TryEmitMultiplySub().
LeftShiftForReducedMultiply() [2/2]
template<typename Matcher >
int32_t v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::LeftShiftForReducedMultiply (Matcher * m)
Definition at line 701 of file instruction-selector-arm64.cc.
                                                {
  DCHECK(m->IsInt32Mul() || m->IsInt64Mul());
  if (m->right().HasResolvedValue() && m->right().ResolvedValue() >= 3) {
    uint64_t value_minus_one = m->right().ResolvedValue() - 1;
    if (base::bits::IsPowerOfTwo(value_minus_one)) {
      return base::bits::WhichPowerOfTwo(value_minus_one);
    }
  }
  return 0;
}
References v8::internal::DCHECK(), v8::base::bits::IsPowerOfTwo(), and v8::base::bits::WhichPowerOfTwo().
MapForCbz()
FlagsCondition v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::MapForCbz (FlagsCondition cond)
Definition at line 3230 of file instruction-selector-arm64.cc.
                                              {
  switch (cond) {
    case kEqual: // generate CBZ
    case kNotEqual: // generate CBNZ
      return cond;
    case kUnsignedLessThanOrEqual: // generate CBZ
      return kEqual;
    case kUnsignedGreaterThan: // generate CBNZ
      return kNotEqual;
    default:
      UNREACHABLE();
  }
}
References v8::internal::kEqual, v8::internal::compiler::kNotEqual, v8::internal::compiler::kUnsignedGreaterThan, v8::internal::compiler::kUnsignedLessThanOrEqual, and v8::internal::UNREACHABLE().
Referenced by TryEmitCbzOrTbz().
MapForFlagSettingBinop()
FlagsCondition v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::MapForFlagSettingBinop (FlagsCondition cond)
Definition at line 3149 of file instruction-selector-arm64.cc.
                                                           {
  DCHECK(CanUseFlagSettingBinop(cond));
  switch (cond) {
    case kEqual:
    case kNotEqual:
      return cond;
    case kSignedLessThan:
      return kNegative;
    case kSignedGreaterThanOrEqual:
      return kPositiveOrZero;
    case kUnsignedLessThanOrEqual: // x <= 0 -> x == 0
      return kEqual;
    case kUnsignedGreaterThan: // x > 0 -> x != 0
      return kNotEqual;
    default:
      UNREACHABLE();
  }
}
References CanUseFlagSettingBinop(), v8::internal::DCHECK(), v8::internal::kEqual, v8::internal::compiler::kNegative, v8::internal::compiler::kNotEqual, v8::internal::compiler::kPositiveOrZero, v8::internal::compiler::kSignedGreaterThanOrEqual, v8::internal::compiler::kSignedLessThan, v8::internal::compiler::kUnsignedGreaterThan, v8::internal::compiler::kUnsignedLessThanOrEqual, and v8::internal::UNREACHABLE().
Referenced by MaybeReplaceCmpZeroWithFlagSettingBinop().
MapForTbz()
FlagsCondition v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::MapForTbz (FlagsCondition cond)
Definition at line 3216 of file instruction-selector-arm64.cc.
                                              {
  switch (cond) {
    case kSignedLessThan: // generate TBNZ
      return kNotEqual;
    case kSignedGreaterThanOrEqual: // generate TBZ
      return kEqual;
    default:
      UNREACHABLE();
  }
}
References v8::internal::kEqual, v8::internal::compiler::kNotEqual, v8::internal::compiler::kSignedGreaterThanOrEqual, v8::internal::compiler::kSignedLessThan, and v8::internal::UNREACHABLE().
Referenced by TryEmitCbzOrTbz().
MaybeReplaceCmpZeroWithFlagSettingBinop()
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::MaybeReplaceCmpZeroWithFlagSettingBinop (InstructionSelector * selector, OpIndex * node, OpIndex binop, ArchOpcode * opcode, FlagsCondition cond, FlagsContinuation * cont, ImmediateMode * immediate_mode)
Definition at line 3174 of file instruction-selector-arm64.cc.
                                                                            {
  ArchOpcode binop_opcode;
  ArchOpcode no_output_opcode;
  ImmediateMode binop_immediate_mode;
  const Operation& op = selector->Get(binop);
  if (op.Is<Opmask::kWord32Add>()) {
    binop_opcode = kArm64Add32;
    no_output_opcode = kArm64Cmn32;
    binop_immediate_mode = kArithmeticImm;
  } else if (op.Is<Opmask::kWord32BitwiseAnd>()) {
    binop_opcode = kArm64And32;
    no_output_opcode = kArm64Tst32;
    binop_immediate_mode = kLogical32Imm;
  } else {
    UNREACHABLE();
  }
  if (selector->CanCover(*node, binop)) {
    // The comparison is the only user of the add or and, so we can generate
    // a cmn or tst instead.
    cont->Overwrite(MapForFlagSettingBinop(cond));
    *opcode = no_output_opcode;
    *node = binop;
    *immediate_mode = binop_immediate_mode;
  } else if (selector->IsOnlyUserOfNodeInSameBlock(*node, binop)) {
    // We can also handle the case where the add and the compare are in the
    // same basic block, and the compare is the only use of add in this basic
    // block (the add has users in other basic blocks).
    cont->Overwrite(MapForFlagSettingBinop(cond));
    *opcode = binop_opcode;
    *node = binop;
    *immediate_mode = binop_immediate_mode;
  }
}
References v8::internal::compiler::InstructionSelector::CanCover(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::compiler::InstructionSelector::IsOnlyUserOfNodeInSameBlock(), v8::internal::compiler::kArithmeticImm, v8::internal::compiler::kLogical32Imm, MapForFlagSettingBinop(), v8::internal::compiler::FlagsContinuation::Overwrite(), and v8::internal::UNREACHABLE().
Referenced by VisitWord32Compare().
TryEmitBitfieldExtract32()
bool v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitBitfieldExtract32 (InstructionSelector * selector, OpIndex node)
Definition at line 2169 of file instruction-selector-arm64.cc.
                                                                           {
  Arm64OperandGenerator g(selector);
  const ShiftOp& shift = selector->Get(node).Cast<ShiftOp>();
  const Operation& lhs = selector->Get(shift.left());
  if (selector->CanCover(node, shift.left()) &&
      lhs.Is<Opmask::kWord32ShiftLeft>()) {
    // Select Ubfx or Sbfx for (x << (K & 0x1F)) OP (K & 0x1F), where
    // OP is >>> or >> and (K & 0x1F) != 0.
    const ShiftOp& lhs_shift = lhs.Cast<ShiftOp>();
    int64_t lhs_shift_by_constant, shift_by_constant;
    if (selector->MatchSignedIntegralConstant(lhs_shift.right(),
                                              &lhs_shift_by_constant) &&
        selector->MatchSignedIntegralConstant(shift.right(),
                                              &shift_by_constant) &&
        (lhs_shift_by_constant & 0x1F) != 0 &&
        (lhs_shift_by_constant & 0x1F) == (shift_by_constant & 0x1F)) {
      DCHECK(shift.Is<Opmask::kWord32ShiftRightArithmetic>() ||
             shift.Is<Opmask::kWord32ShiftRightArithmeticShiftOutZeros>() ||
             shift.Is<Opmask::kWord32ShiftRightLogical>());
      ArchOpcode opcode = shift.kind == ShiftOp::Kind::kShiftRightLogical
                              ? kArm64Ubfx32
                              : kArm64Sbfx32;
      int right_val = shift_by_constant & 0x1F;
      DCHECK_NE(right_val, 0);
      selector->Emit(opcode, g.DefineAsRegister(node),
                     g.UseRegister(lhs_shift.left()), g.TempImmediate(0),
                     g.TempImmediate(32 - right_val));
      return true;
    }
  }
  return false;
}
References v8::internal::compiler::InstructionSelector::CanCover(), v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::DCHECK(), DCHECK_NE, v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::InstructionSelector::Emit(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::compiler::turboshaft::ShiftOp::kind, v8::internal::compiler::turboshaft::OperationMatcher::MatchSignedIntegralConstant(), v8::internal::compiler::turboshaft::ShiftOp::right(), v8::internal::compiler::OperandGenerator::TempImmediate(), and v8::internal::compiler::OperandGenerator::UseRegister().
TryEmitCbzOrTbz()
template<int N>
bool v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitCbzOrTbz (InstructionSelector * selector, OpIndex node, typename CbzOrTbzMatchTrait< N >::IntegralType value, OpIndex user, FlagsCondition cond, FlagsContinuation * cont)
Definition at line 3280 of file instruction-selector-arm64.cc.
                                              {
  // Only handle branches and deoptimisations.
  if (!cont->IsBranch() && !cont->IsDeoptimize()) return false;
  switch (cond) {
    case kSignedLessThan:
    case kSignedGreaterThanOrEqual: {
      // Here we handle sign tests, aka. comparisons with zero.
      if (value != 0) return false;
      // We don't generate TBZ/TBNZ for deoptimisations, as they have a
      // shorter range than conditional branches and generating them for
      // deoptimisations results in more veneers.
      if (cont->IsDeoptimize()) return false;
      Arm64OperandGenerator g(selector);
      cont->Overwrite(MapForTbz(cond));
      if (N == 32) {
        const Operation& op = selector->Get(node);
        if (op.Is<Opmask::kFloat64ExtractHighWord32>() &&
            selector->CanCover(user, node)) {
          // SignedLessThan(Float64ExtractHighWord32(x), 0) and
          // SignedGreaterThanOrEqual(Float64ExtractHighWord32(x), 0)
          // essentially check the sign bit of a 64-bit floating point value.
          InstructionOperand temp = g.TempRegister();
          selector->Emit(kArm64U64MoveFloat64, temp,
                         g.UseRegister(op.input(0)));
          selector->EmitWithContinuation(kArm64TestAndBranch, temp,
                                         g.TempImmediate(kDSignBit), cont);
          return true;
        }
      }
      selector->EmitWithContinuation(
          CbzOrTbzMatchTrait<N>::kTestAndBranchOpcode, g.UseRegister(node),
          g.TempImmediate(CbzOrTbzMatchTrait<N>::kSignBit), cont);
      return true;
    }
    case kEqual:
    case kNotEqual: {
      const Operation& op = selector->Get(node);
      if (const WordBinopOp* bitwise_and = op.TryCast<Opmask::kBitwiseAnd>()) {
        // Emit a tbz/tbnz if we are comparing with a single-bit mask:
        // Branch(WordEqual(WordAnd(x, 1 << N), 1 << N), true, false)
        uint64_t actual_value;
        if (cont->IsBranch() && base::bits::IsPowerOfTwo(value) &&
            selector->MatchUnsignedIntegralConstant(bitwise_and->right(),
                                                    &actual_value) &&
            actual_value == value && selector->CanCover(user, node)) {
          Arm64OperandGenerator g(selector);
          // In the code generator, Equal refers to a bit being cleared. We
          // want the opposite here so negate the condition.
          cont->Negate();
          selector->EmitWithContinuation(
              CbzOrTbzMatchTrait<N>::kTestAndBranchOpcode,
              g.UseRegister(bitwise_and->left()),
              g.TempImmediate(base::bits::CountTrailingZeros(value)), cont);
          return true;
        }
      }
      [[fallthrough]];
    }
    case kUnsignedLessThanOrEqual:
    case kUnsignedGreaterThan: {
      if (value != 0) return false;
      Arm64OperandGenerator g(selector);
      cont->Overwrite(MapForCbz(cond));
      EmitBranchOrDeoptimize(selector,
                             CbzOrTbzMatchTrait<N>::kCompareAndBranchOpcode,
                             g.UseRegister(node), cont);
      return true;
    }
    default:
      return false;
  }
}
References v8::internal::compiler::InstructionSelector::CanCover(), v8::base::bits::CountTrailingZeros(), v8::internal::compiler::InstructionSelector::Emit(), EmitBranchOrDeoptimize(), v8::internal::compiler::InstructionSelector::EmitWithContinuation(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::compiler::FlagsContinuation::IsBranch(), v8::internal::compiler::FlagsContinuation::IsDeoptimize(), v8::base::bits::IsPowerOfTwo(), v8::internal::kDSignBit, v8::internal::kEqual, v8::internal::compiler::kNotEqual, v8::internal::compiler::kSignedGreaterThanOrEqual, v8::internal::compiler::kSignedLessThan, v8::internal::compiler::kUnsignedGreaterThan, v8::internal::compiler::kUnsignedLessThanOrEqual, MapForCbz(), MapForTbz(), v8::internal::compiler::turboshaft::OperationMatcher::MatchUnsignedIntegralConstant(), v8::internal::N, v8::internal::compiler::FlagsContinuation::Negate(), v8::internal::compiler::FlagsContinuation::Overwrite(), v8::internal::compiler::OperandGenerator::TempImmediate(), v8::internal::compiler::OperandGenerator::TempRegister(), v8::internal::compiler::turboshaft::Operation::TryCast(), v8::internal::compiler::OperandGenerator::UseRegister(), and v8::internal::value.
TryEmitExtendingLoad()
bool v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitExtendingLoad (InstructionSelector * selector, OpIndex node)
Definition at line 328 of file instruction-selector-arm64.cc.
                                                                       {
  ExtendingLoadMatcher m(node, selector);
  Arm64OperandGenerator g(selector);
  if (m.Matches()) {
    InstructionOperand inputs[2];
    inputs[0] = g.UseRegister(m.base());
    InstructionCode opcode =
        m.opcode() | AddressingModeField::encode(kMode_MRI);
    DCHECK(is_int32(m.immediate()));
    inputs[1] = g.TempImmediate(static_cast<int32_t>(m.immediate()));
    InstructionOperand outputs[] = {g.DefineAsRegister(node)};
    selector->Emit(opcode, arraysize(outputs), outputs, arraysize(inputs),
                   inputs);
    return true;
  }
  return false;
}
References arraysize, v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::ExtendingLoadMatcher::base(), v8::internal::DCHECK(), v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::InstructionSelector::Emit(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::ExtendingLoadMatcher::immediate(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::ExtendingLoadMatcher::Matches(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::ExtendingLoadMatcher::opcode(), v8::internal::compiler::OperandGenerator::TempImmediate(), and v8::internal::compiler::OperandGenerator::UseRegister().
TryEmitMultiplyAdd()
template<typename MultiplyOpmaskT >
bool v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitMultiplyAdd (InstructionSelector * selector, OpIndex add, OpIndex lhs, OpIndex rhs, InstructionCode madd_opcode)
Definition at line 729 of file instruction-selector-arm64.cc.
                                                                  {
  const Operation& add_lhs = selector->Get(lhs);
  if (!add_lhs.Is<MultiplyOpmaskT>() || !selector->CanCover(add, lhs)) {
    return false;
  }
  // Check that multiply can't be reduced to an addition with shift later on.
  const WordBinopOp& mul = add_lhs.Cast<WordBinopOp>();
  if (LeftShiftForReducedMultiply(selector, mul.right()) != 0) return false;
  Arm64OperandGenerator g(selector);
  selector->Emit(madd_opcode, g.DefineAsRegister(add),
                 g.UseRegister(mul.left()), g.UseRegister(mul.right()),
                 g.UseRegister(rhs));
  return true;
}
References v8::internal::compiler::InstructionSelector::CanCover(), v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::InstructionSelector::Emit(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::compiler::turboshaft::WordBinopOp::left(), LeftShiftForReducedMultiply(), v8::internal::compiler::turboshaft::WordBinopOp::right(), and v8::internal::compiler::OperandGenerator::UseRegister().
TryEmitMultiplyAddInt32()
bool v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitMultiplyAddInt32 (InstructionSelector * selector, OpIndex add, OpIndex lhs, OpIndex rhs)
Definition at line 746 of file instruction-selector-arm64.cc.
                                                       {
  return TryEmitMultiplyAdd<Opmask::kWord32Mul>(selector, add, lhs, rhs,
                                                kArm64Madd32);
}
TryEmitMultiplyAddInt64()
bool v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitMultiplyAddInt64 (InstructionSelector * selector, OpIndex add, OpIndex lhs, OpIndex rhs)
Definition at line 752 of file instruction-selector-arm64.cc.
                                                       {
  return TryEmitMultiplyAdd<Opmask::kWord64Mul>(selector, add, lhs, rhs,
                                                kArm64Madd);
}
TryEmitMultiplyNegate()
template<typename SubtractOpmaskT >
bool v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitMultiplyNegate (InstructionSelector * selector, OpIndex mul, OpIndex lhs, OpIndex rhs, InstructionCode mneg_opcode)
Definition at line 760 of file instruction-selector-arm64.cc.
                                                        {
  const Operation& mul_lhs = selector->Get(lhs);
  if (!mul_lhs.Is<SubtractOpmaskT>() || !selector->CanCover(mul, lhs)) {
    return false;
  }
  const WordBinopOp& sub = mul_lhs.Cast<WordBinopOp>();
  Arm64OperandGenerator g(selector);
  std::optional<int64_t> sub_lhs_constant =
      g.GetOptionalIntegerConstant(sub.left());
  if (!sub_lhs_constant.has_value() || sub_lhs_constant != 0) return false;
  selector->Emit(mneg_opcode, g.DefineAsRegister(mul),
                 g.UseRegister(sub.right()), g.UseRegister(rhs));
  return true;
}
References v8::internal::compiler::InstructionSelector::CanCover(), v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::compiler::InstructionSelector::Emit(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::compiler::turboshaft::WordBinopOp::left(), and v8::internal::compiler::turboshaft::WordBinopOp::right().
TryEmitMultiplyNegateInt32()
bool v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitMultiplyNegateInt32 (InstructionSelector * selector, OpIndex mul, OpIndex lhs, OpIndex rhs)
Definition at line 777 of file instruction-selector-arm64.cc.
                                                          {
  return TryEmitMultiplyNegate<Opmask::kWord32Sub>(selector, mul, lhs, rhs,
                                                   kArm64Mneg32);
}
TryEmitMultiplyNegateInt64()
bool v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitMultiplyNegateInt64 (InstructionSelector * selector, OpIndex mul, OpIndex lhs, OpIndex rhs)
Definition at line 783 of file instruction-selector-arm64.cc.
                                                          {
  return TryEmitMultiplyNegate<Opmask::kWord64Sub>(selector, mul, lhs, rhs,
                                                   kArm64Mneg);
}
TryEmitMultiplySub()
template<typename MultiplyOpmaskT >
bool v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitMultiplySub (InstructionSelector * selector, OpIndex node, InstructionCode msub_opbocde)
Definition at line 791 of file instruction-selector-arm64.cc.
                                                      {
  const WordBinopOp& sub = selector->Get(node).Cast<WordBinopOp>();
  DCHECK_EQ(sub.kind, WordBinopOp::Kind::kSub);
  // Select Msub(x, y, a) for Sub(a, Mul(x, y)).
  const Operation& sub_rhs = selector->Get(sub.right());
  if (sub_rhs.Is<MultiplyOpmaskT>() && selector->CanCover(node, sub.right())) {
    const WordBinopOp& mul = sub_rhs.Cast<WordBinopOp>();
    if (LeftShiftForReducedMultiply(selector, mul.right()) == 0) {
      Arm64OperandGenerator g(selector);
      selector->Emit(msub_opbocde, g.DefineAsRegister(node),
                     g.UseRegister(mul.left()), g.UseRegister(mul.right()),
                     g.UseRegister(sub.left()));
      return true;
    }
  }
  return false;
}
References v8::internal::compiler::InstructionSelector::CanCover(), v8::internal::compiler::turboshaft::Operation::Cast(), DCHECK_EQ, v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::InstructionSelector::Emit(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::compiler::turboshaft::WordBinopOp::kind, v8::internal::compiler::turboshaft::WordBinopOp::kSub, v8::internal::compiler::turboshaft::WordBinopOp::left(), LeftShiftForReducedMultiply(), v8::internal::compiler::turboshaft::WordBinopOp::right(), and v8::internal::compiler::OperandGenerator::UseRegister().
TryMatchAnyExtend()
bool v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryMatchAnyExtend (Arm64OperandGenerator * g, InstructionSelector * selector, OpIndex node, OpIndex left_node, OpIndex right_node, InstructionOperand * left_op, InstructionOperand * right_op, InstructionCode * opcode)
Definition at line 435 of file instruction-selector-arm64.cc.
                                                                              {
  if (!selector->CanCover(node, right_node)) return false;
  const Operation& right = selector->Get(right_node);
  OpIndex bitwise_and_left;
  int32_t mask;
  if (TryMatchBitwiseAndSmallMask(*selector, right_node, &bitwise_and_left,
                                  &mask)) {
    *left_op = g->UseRegister(left_node);
    *right_op = g->UseRegister(bitwise_and_left);
    *opcode |= AddressingModeField::encode(
        (mask == 0xFF) ? kMode_Operand2_R_UXTB : kMode_Operand2_R_UXTH);
    return true;
  }
  OpIndex shift_input_left;
  int32_t shift_by;
  if (TryMatchSignExtendShift(selector, right_node, &shift_input_left,
                              &shift_by)) {
    *left_op = g->UseRegister(left_node);
    *right_op = g->UseRegister(shift_input_left);
    *opcode |= AddressingModeField::encode(
        (shift_by == 24) ? kMode_Operand2_R_SXTB : kMode_Operand2_R_SXTH);
    return true;
  }
  if (const ChangeOp* change_op =
          right.TryCast<Opmask::kChangeInt32ToInt64>()) {
    // Use extended register form.
    *opcode |= AddressingModeField::encode(kMode_Operand2_R_SXTW);
    *left_op = g->UseRegister(left_node);
    *right_op = g->UseRegister(change_op->input());
    return true;
  }
  return false;
}
References v8::internal::compiler::InstructionSelector::CanCover(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::TryCast(), TryMatchBitwiseAndSmallMask(), TryMatchSignExtendShift(), and v8::internal::compiler::OperandGenerator::UseRegister().
Referenced by VisitBinopImpl().
TryMatchAnyShift()
bool v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryMatchAnyShift (InstructionSelector * selector, OpIndex node, OpIndex input_node, InstructionCode * opcode, bool try_ror, RegisterRepresentation rep)
Definition at line 346 of file instruction-selector-arm64.cc.
                                                  {
  Arm64OperandGenerator g(selector);
  if (!selector->CanCover(node, input_node)) return false;
  if (const ShiftOp* shift = selector->Get(input_node).TryCast<ShiftOp>()) {
    // Differently to Turbofan, the representation should always match.
    DCHECK_EQ(shift->rep, rep);
    if (shift->rep != rep) return false;
    if (!g.IsIntegerConstant(shift->right())) return false;
    switch (shift->kind) {
      case ShiftOp::Kind::kShiftLeft:
        *opcode |= AddressingModeField::encode(kMode_Operand2_R_LSL_I);
        return true;
      case ShiftOp::Kind::kShiftRightLogical:
        *opcode |= AddressingModeField::encode(kMode_Operand2_R_LSR_I);
        return true;
      case ShiftOp::Kind::kShiftRightArithmetic:
      case ShiftOp::Kind::kShiftRightArithmeticShiftOutZeros:
        if (rep == WordRepresentation::Word64() &&
            TryMatchExtendingLoad(selector, input_node)) {
          return false;
        }
        *opcode |= AddressingModeField::encode(kMode_Operand2_R_ASR_I);
        return true;
      case ShiftOp::Kind::kRotateRight:
        if (try_ror) {
          *opcode |= AddressingModeField::encode(kMode_Operand2_R_ROR_I);
          return true;
        }
        return false;
      case ShiftOp::Kind::kRotateLeft:
        return false;
    }
  }
  return false;
}
References v8::internal::compiler::InstructionSelector::CanCover(), DCHECK_EQ, v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::Arm64OperandGenerator::IsIntegerConstant(), v8::internal::compiler::turboshaft::Operation::TryCast(), TryMatchExtendingLoad(), and v8::internal::compiler::turboshaft::WordRepresentation::Word64().
Referenced by VisitBinopImpl().
TryMatchBitwiseAndSmallMask()
bool v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryMatchBitwiseAndSmallMask (OperationMatcher & matcher, OpIndex op, OpIndex * left, int32_t * mask)
Definition at line 386 of file instruction-selector-arm64.cc.
                                                               {
  if (const ChangeOp* change_op =
          matcher.TryCast<Opmask::kChangeInt32ToInt64>(op)) {
    return TryMatchBitwiseAndSmallMask(matcher, change_op->input(), left, mask);
  }
  if (const WordBinopOp* bitwise_and =
          matcher.TryCast<Opmask::kWord32BitwiseAnd>(op)) {
    if (matcher.MatchIntegralWord32Constant(bitwise_and->right(), mask) &&
        (*mask == 0xFF || *mask == 0xFFFF)) {
      *left = bitwise_and->left();
      return true;
    }
    if (matcher.MatchIntegralWord32Constant(bitwise_and->left(), mask) &&
        (*mask == 0xFF || *mask == 0xFFFF)) {
      *left = bitwise_and->right();
      return true;
    }
  }
  return false;
}
References v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralWord32Constant(), and v8::internal::compiler::turboshaft::OperationMatcher::TryCast().
Referenced by TryMatchAnyExtend().
TryMatchExtendingLoad()
bool v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryMatchExtendingLoad (InstructionSelector * selector, OpIndex node)
Definition at line 323 of file instruction-selector-arm64.cc.
                                                                        {
  ExtendingLoadMatcher m(node, selector);
  return m.Matches();
}
References v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::ExtendingLoadMatcher::Matches().
Referenced by TryMatchAnyShift().
TryMatchLoadStoreShift()
bool v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryMatchLoadStoreShift (Arm64OperandGenerator * g, InstructionSelector * selector, MemoryRepresentation rep, OpIndex node, OpIndex index, InstructionOperand * index_op, InstructionOperand * shift_immediate_op)
Definition at line 475 of file instruction-selector-arm64.cc.
                                                                    {
  if (!selector->CanCover(node, index)) return false;
  if (const ChangeOp* change =
          selector->Get(index).TryCast<Opmask::kChangeUint32ToUint64>();
      change && selector->CanCover(index, change->input())) {
    index = change->input();
  }
  const ShiftOp* shift = selector->Get(index).TryCast<Opmask::kShiftLeft>();
  if (shift == nullptr) return false;
  if (!g->CanBeLoadStoreShiftImmediate(shift->right(), rep)) return false;
  *index_op = g->UseRegister(shift->left());
  *shift_immediate_op = g->UseImmediate(shift->right());
  return true;
}
References v8::internal::compiler::Arm64OperandGenerator::CanBeLoadStoreShiftImmediate(), v8::internal::compiler::InstructionSelector::CanCover(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::index, v8::internal::compiler::turboshaft::ShiftOp::right(), v8::internal::compiler::turboshaft::Operation::TryCast(), v8::internal::compiler::OperandGenerator::UseImmediate(), and v8::internal::compiler::OperandGenerator::UseRegister().
TryMatchSignExtendShift()
bool v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryMatchSignExtendShift (InstructionSelector * selector, OpIndex op, OpIndex * left, int32_t * shift_by)
Definition at line 408 of file instruction-selector-arm64.cc.
                                                               {
  if (const ChangeOp* change_op =
          selector->TryCast<Opmask::kChangeInt32ToInt64>(op)) {
    return TryMatchSignExtendShift(selector, change_op->input(), left,
                                   shift_by);
  }
  if (const ShiftOp* sar =
          selector->TryCast<Opmask::kWord32ShiftRightArithmetic>(op)) {
    const Operation& sar_lhs = selector->Get(sar->left());
    if (sar_lhs.Is<Opmask::kWord32ShiftLeft>() &&
        selector->CanCover(op, sar->left())) {
      const ShiftOp& shl = sar_lhs.Cast<ShiftOp>();
      int32_t sar_by, shl_by;
      if (selector->MatchIntegralWord32Constant(sar->right(), &sar_by) &&
          selector->MatchIntegralWord32Constant(shl.right(), &shl_by) &&
          sar_by == shl_by && (sar_by == 16 || sar_by == 24)) {
        *left = shl.left();
        *shift_by = sar_by;
        return true;
      }
    }
  }
  return false;
}
References v8::internal::compiler::InstructionSelector::CanCover(), v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralWord32Constant(), v8::internal::compiler::turboshaft::ShiftOp::right(), and v8::internal::compiler::turboshaft::OperationMatcher::TryCast().
Referenced by TryMatchAnyExtend().
VisitAddSub()
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAddSub (InstructionSelector * selector, OpIndex node, ArchOpcode opcode, ArchOpcode negate_opcode)
Definition at line 678 of file instruction-selector-arm64.cc.
                                           {
  Arm64OperandGenerator g(selector);
  const WordBinopOp& add_sub = selector->Get(node).Cast<WordBinopOp>();
  auto [left, right] = GetBinopLeftRightCstOnTheRight(selector, add_sub);
  if (std::optional<int64_t> constant_rhs =
          g.GetOptionalIntegerConstant(right)) {
    if (constant_rhs < 0 && constant_rhs > std::numeric_limits<int>::min() &&
        g.CanBeImmediate(-*constant_rhs, kArithmeticImm)) {
      selector->Emit(negate_opcode, g.DefineAsRegister(node),
                     g.UseRegister(left),
                     g.TempImmediate(static_cast<int32_t>(-*constant_rhs)));
      return;
    }
  }
  VisitBinop(selector, node, add_sub.rep, opcode, kArithmeticImm);
}
References v8::internal::compiler::Arm64OperandGenerator::CanBeImmediate(), v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::InstructionSelector::Emit(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), GetBinopLeftRightCstOnTheRight(), v8::internal::compiler::Arm64OperandGenerator::GetOptionalIntegerConstant(), v8::internal::compiler::kArithmeticImm, v8::internal::compiler::turboshaft::WordBinopOp::rep, v8::internal::compiler::OperandGenerator::TempImmediate(), v8::internal::compiler::OperandGenerator::UseRegister(), and v8::internal::compiler::VisitBinop().
VisitAtomicBinop()
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicBinop (InstructionSelector * selector, OpIndex node, ArchOpcode opcode, AtomicWidth width, MemoryAccessKind access_kind)
Definition at line 3774 of file instruction-selector-arm64.cc.
                                                    {
  using OpIndex = OpIndex;
  Arm64OperandGenerator g(selector);
  const AtomicRMWOp& atomic_op = selector->Cast<AtomicRMWOp>(node);
  OpIndex base = atomic_op.base();
  OpIndex index = atomic_op.index();
  OpIndex value = atomic_op.value();
  AddressingMode addressing_mode = kMode_MRR;
  InstructionOperand inputs[] = {g.UseRegister(base), g.UseRegister(index),
                                 g.UseUniqueRegister(value)};
  InstructionOperand outputs[] = {g.DefineAsRegister(node)};
  InstructionCode code = opcode | AddressingModeField::encode(addressing_mode) |
                         AtomicWidthField::encode(width);
  if (access_kind == MemoryAccessKind::kProtectedByTrapHandler) {
    code |= AccessModeField::encode(kMemoryAccessProtectedMemOutOfBounds);
  }
  if (CpuFeatures::IsSupported(LSE)) {
    InstructionOperand temps[] = {g.TempRegister()};
    selector->Emit(code, arraysize(outputs), outputs, arraysize(inputs), inputs,
                   arraysize(temps), temps);
  } else {
    InstructionOperand temps[] = {g.TempRegister(), g.TempRegister(),
                                  g.TempRegister()};
    selector->Emit(code, arraysize(outputs), outputs, arraysize(inputs), inputs,
                   arraysize(temps), temps);
  }
}
References arraysize, v8::internal::compiler::turboshaft::AtomicRMWOp::base(), v8::internal::compiler::turboshaft::OperationMatcher::Cast(), code, v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::InstructionSelector::Emit(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::turboshaft::AtomicRMWOp::index(), v8::internal::index, v8::internal::CpuFeatures::IsSupported(), v8::internal::compiler::kMemoryAccessProtectedMemOutOfBounds, v8::internal::compiler::kProtectedByTrapHandler, v8::internal::compiler::turboshaft::OpIndex, v8::internal::compiler::OperandGenerator::TempRegister(), v8::internal::compiler::OperandGenerator::UseRegister(), v8::internal::compiler::OperandGenerator::UseUniqueRegister(), v8::internal::compiler::turboshaft::AtomicRMWOp::value(), and v8::internal::value.
VisitAtomicCompareExchange()
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicCompareExchange (InstructionSelector * selector, OpIndex node, ArchOpcode opcode, AtomicWidth width, MemoryAccessKind access_kind)
Definition at line 3578 of file instruction-selector-arm64.cc.
                                                              {
  using OpIndex = OpIndex;
  Arm64OperandGenerator g(selector);
  const AtomicRMWOp& atomic_op = selector->Cast<AtomicRMWOp>(node);
  OpIndex base = atomic_op.base();
  OpIndex index = atomic_op.index();
  OpIndex old_value = atomic_op.expected().value();
  OpIndex new_value = atomic_op.value();
  InstructionOperand inputs[] = {g.UseRegister(base), g.UseRegister(index),
                                 g.UseUniqueRegister(old_value),
                                 g.UseUniqueRegister(new_value)};
  InstructionOperand outputs[1];
  InstructionCode code = opcode | AddressingModeField::encode(kMode_MRR) |
                         AtomicWidthField::encode(width);
  if (access_kind == MemoryAccessKind::kProtectedByTrapHandler) {
    code |= AccessModeField::encode(kMemoryAccessProtectedMemOutOfBounds);
  }
  if (CpuFeatures::IsSupported(LSE)) {
    InstructionOperand temps[] = {g.TempRegister()};
    outputs[0] = g.DefineSameAsInput(node, 2);
    selector->Emit(code, arraysize(outputs), outputs, arraysize(inputs), inputs,
                   arraysize(temps), temps);
  } else {
    InstructionOperand temps[] = {g.TempRegister(), g.TempRegister()};
    outputs[0] = g.DefineAsRegister(node);
    selector->Emit(code, arraysize(outputs), outputs, arraysize(inputs), inputs,
                   arraysize(temps), temps);
  }
}
References arraysize, v8::internal::compiler::turboshaft::AtomicRMWOp::base(), v8::internal::compiler::turboshaft::OperationMatcher::Cast(), code, v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::OperandGenerator::DefineSameAsInput(), v8::internal::compiler::InstructionSelector::Emit(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::turboshaft::AtomicRMWOp::expected(), v8::internal::compiler::turboshaft::AtomicRMWOp::index(), v8::internal::index, v8::internal::CpuFeatures::IsSupported(), v8::internal::compiler::kMemoryAccessProtectedMemOutOfBounds, v8::internal::compiler::kProtectedByTrapHandler, v8::internal::compiler::turboshaft::OpIndex, v8::internal::compiler::OperandGenerator::TempRegister(), v8::internal::compiler::OperandGenerator::UseRegister(), v8::internal::compiler::OperandGenerator::UseUniqueRegister(), v8::internal::compiler::turboshaft::OptionalOpIndex::value(), and v8::internal::compiler::turboshaft::AtomicRMWOp::value().
VisitAtomicExchange()
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicExchange (InstructionSelector * selector, OpIndex node, ArchOpcode opcode, AtomicWidth width, MemoryAccessKind access_kind)
Definition at line 3540 of file instruction-selector-arm64.cc.
                                                       {
  using OpIndex = OpIndex;
  const AtomicRMWOp& atomic_op = selector->Cast<AtomicRMWOp>(node);
  Arm64OperandGenerator g(selector);
  OpIndex base = atomic_op.base();
  OpIndex index = atomic_op.index();
  OpIndex value = atomic_op.value();
  InstructionOperand inputs[3];
  if (opcode == kAtomicExchangeWithWriteBarrier) {
    // All inputs registers need to be non-aliasing with the temp registers as
    // the original inputs are still needed when emitting the write barrier.
    inputs[0] = g.UseUniqueRegister(base);
    inputs[1] = g.UseUniqueRegister(index);
    inputs[2] = g.UseUniqueRegister(value);
  } else {
    inputs[0] = g.UseRegister(base);
    inputs[1] = g.UseRegister(index);
    inputs[2] = g.UseUniqueRegister(value);
  }
  InstructionOperand outputs[] = {g.DefineAsRegister(node)};
  InstructionCode code = opcode | AddressingModeField::encode(kMode_MRR) |
                         AtomicWidthField::encode(width);
  if (access_kind == MemoryAccessKind::kProtectedByTrapHandler) {
    code |= AccessModeField::encode(kMemoryAccessProtectedMemOutOfBounds);
  }
  if (CpuFeatures::IsSupported(LSE)) {
    InstructionOperand temps[] = {g.TempRegister()};
    selector->Emit(code, arraysize(outputs), outputs, arraysize(inputs), inputs,
                   arraysize(temps), temps);
  } else {
    InstructionOperand temps[] = {g.TempRegister(), g.TempRegister()};
    selector->Emit(code, arraysize(outputs), outputs, arraysize(inputs), inputs,
                   arraysize(temps), temps);
  }
}
References arraysize, v8::internal::compiler::turboshaft::AtomicRMWOp::base(), v8::internal::compiler::turboshaft::OperationMatcher::Cast(), code, v8::internal::compiler::InstructionSelector::Emit(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::turboshaft::AtomicRMWOp::index(), v8::internal::index, v8::internal::CpuFeatures::IsSupported(), v8::internal::compiler::kMemoryAccessProtectedMemOutOfBounds, v8::internal::compiler::kProtectedByTrapHandler, v8::internal::compiler::turboshaft::OpIndex, v8::internal::compiler::turboshaft::AtomicRMWOp::value(), and v8::internal::value.
VisitAtomicLoad()
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicLoad (InstructionSelector * selector, OpIndex node, AtomicWidth width)
Definition at line 3610 of file instruction-selector-arm64.cc.
                                        {
  using OpIndex = OpIndex;
  Arm64OperandGenerator g(selector);
  auto load = selector->load_view(node);
  OpIndex base = load.base();
  OpIndex index = load.index();
  InstructionOperand inputs[] = {g.UseRegister(base), g.UseRegister(index)};
  InstructionOperand outputs[] = {g.DefineAsRegister(node)};
  InstructionOperand temps[] = {g.TempRegister()};
  // The memory order is ignored as both acquire and sequentially consistent
  // loads can emit LDAR.
  // https://www.cl.cam.ac.uk/~pes20/cpp/cpp0xmappings.html
  LoadRepresentation load_rep = load.loaded_rep();
  InstructionCode code;
  switch (load_rep.representation()) {
    case MachineRepresentation::kWord8:
      DCHECK_IMPLIES(load_rep.IsSigned(), width == AtomicWidth::kWord32);
      code = load_rep.IsSigned() ? kAtomicLoadInt8 : kAtomicLoadUint8;
      break;
    case MachineRepresentation::kWord16:
      DCHECK_IMPLIES(load_rep.IsSigned(), width == AtomicWidth::kWord32);
      code = load_rep.IsSigned() ? kAtomicLoadInt16 : kAtomicLoadUint16;
      break;
    case MachineRepresentation::kWord32:
      code = kAtomicLoadWord32;
      break;
    case MachineRepresentation::kWord64:
      code = kArm64Word64AtomicLoadUint64;
      break;
#ifdef V8_COMPRESS_POINTERS
    case MachineRepresentation::kTaggedSigned:
      code = kArm64LdarDecompressTaggedSigned;
      break;
    case MachineRepresentation::kTaggedPointer:
      code = kArm64LdarDecompressTagged;
      break;
    case MachineRepresentation::kTagged:
      code = kArm64LdarDecompressTagged;
      break;
#else
    case MachineRepresentation::kTaggedSigned: // Fall through.
    case MachineRepresentation::kTaggedPointer: // Fall through.
    case MachineRepresentation::kTagged:
      if (kTaggedSize == 8) {
        code = kArm64Word64AtomicLoadUint64;
      } else {
        code = kAtomicLoadWord32;
      }
      break;
#endif
    case MachineRepresentation::kCompressedPointer: // Fall through.
    case MachineRepresentation::kCompressed:
      DCHECK(COMPRESS_POINTERS_BOOL);
      code = kAtomicLoadWord32;
      break;
    default:
      UNREACHABLE();
  }
  bool traps_on_null;
  if (load.is_protected(&traps_on_null)) {
    code |= AccessModeField::encode(traps_on_null
                                        ? kMemoryAccessProtectedNullDereference
                                        : kMemoryAccessProtectedMemOutOfBounds);
  }
  code |=
      AddressingModeField::encode(kMode_MRR) | AtomicWidthField::encode(width);
  selector->Emit(code, arraysize(outputs), outputs, arraysize(inputs), inputs,
                 arraysize(temps), temps);
}
References arraysize, code, COMPRESS_POINTERS_BOOL, v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::InstructionSelector::Emit(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::index, v8::internal::MachineType::IsSigned(), v8::internal::kCompressed, v8::internal::kCompressedPointer, v8::internal::compiler::kMemoryAccessProtectedMemOutOfBounds, v8::internal::compiler::kMemoryAccessProtectedNullDereference, v8::internal::kTagged, v8::internal::kTaggedPointer, v8::internal::kTaggedSigned, v8::internal::kTaggedSize, v8::internal::kWord16, v8::internal::kWord32, v8::internal::compiler::kWord32, v8::internal::kWord64, v8::internal::kWord8, v8::internal::compiler::InstructionSelector::load_view(), v8::internal::compiler::turboshaft::OpIndex, v8::internal::MachineType::representation(), v8::internal::compiler::OperandGenerator::TempRegister(), v8::internal::UNREACHABLE(), and v8::internal::compiler::OperandGenerator::UseRegister().
VisitAtomicStore()
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicStore (InstructionSelector * selector, OpIndex node, AtomicWidth width)
Definition at line 3693 of file instruction-selector-arm64.cc.
                                         {
  using OpIndex = OpIndex;
  Arm64OperandGenerator g(selector);
  auto store = selector->store_view(node);
  OpIndex base = store.base();
  OpIndex index = store.index().value();
  OpIndex value = store.value();
  DCHECK_EQ(store.displacement(), 0);
  // The memory order is ignored as both release and sequentially consistent
  // stores can emit STLR.
  // https://www.cl.cam.ac.uk/~pes20/cpp/cpp0xmappings.html
  AtomicStoreParameters store_params = AtomicStoreParametersOf(selector, node);
  WriteBarrierKind write_barrier_kind = store_params.write_barrier_kind();
  MachineRepresentation rep = store_params.representation();
  if (v8_flags.enable_unconditional_write_barriers &&
      CanBeTaggedOrCompressedPointer(rep)) {
    write_barrier_kind = kFullWriteBarrier;
  }
  InstructionOperand inputs[] = {g.UseUniqueRegister(base),
                                 g.UseUniqueRegister(index),
                                 g.UseUniqueRegister(value)};
  InstructionOperand temps[] = {g.TempRegister()};
  InstructionCode code;
  if (write_barrier_kind != kNoWriteBarrier &&
      !v8_flags.disable_write_barriers) {
    DCHECK(CanBeTaggedOrCompressedPointer(rep));
    DCHECK_EQ(AtomicWidthSize(width), kTaggedSize);
    RecordWriteMode record_write_mode =
        WriteBarrierKindToRecordWriteMode(write_barrier_kind);
    code = kArchAtomicStoreWithWriteBarrier;
    code |= RecordWriteModeField::encode(record_write_mode);
  } else {
    switch (rep) {
      case MachineRepresentation::kWord8:
        code = kAtomicStoreWord8;
        break;
      case MachineRepresentation::kWord16:
        code = kAtomicStoreWord16;
        break;
      case MachineRepresentation::kWord32:
        code = kAtomicStoreWord32;
        break;
      case MachineRepresentation::kWord64:
        DCHECK_EQ(width, AtomicWidth::kWord64);
        code = kArm64Word64AtomicStoreWord64;
        break;
      case MachineRepresentation::kTaggedSigned: // Fall through.
      case MachineRepresentation::kTaggedPointer: // Fall through.
      case MachineRepresentation::kTagged:
        DCHECK_EQ(AtomicWidthSize(width), kTaggedSize);
        code = kArm64StlrCompressTagged;
        break;
      case MachineRepresentation::kCompressedPointer: // Fall through.
      case MachineRepresentation::kCompressed:
        CHECK(COMPRESS_POINTERS_BOOL);
        DCHECK_EQ(width, AtomicWidth::kWord32);
        code = kArm64StlrCompressTagged;
        break;
      default:
        UNREACHABLE();
    }
    code |= AtomicWidthField::encode(width);
  }
  if (store.is_store_trap_on_null()) {
    code |= AccessModeField::encode(kMemoryAccessProtectedNullDereference);
  } else if (store_params.kind() == MemoryAccessKind::kProtectedByTrapHandler) {
    code |= AccessModeField::encode(kMemoryAccessProtectedMemOutOfBounds);
  }
  code |= AddressingModeField::encode(kMode_MRR);
  selector->Emit(code, 0, nullptr, arraysize(inputs), inputs, arraysize(temps),
                 temps);
}
References arraysize, v8::internal::compiler::AtomicStoreParametersOf(), v8::internal::compiler::AtomicWidthSize(), v8::internal::CanBeTaggedOrCompressedPointer(), CHECK, code, COMPRESS_POINTERS_BOOL, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::InstructionSelector::Emit(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::index, v8::internal::kCompressed, v8::internal::kCompressedPointer, v8::internal::compiler::kFullWriteBarrier, v8::internal::compiler::AtomicStoreParameters::kind(), v8::internal::compiler::kMemoryAccessProtectedMemOutOfBounds, v8::internal::compiler::kMemoryAccessProtectedNullDereference, v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kProtectedByTrapHandler, v8::internal::kTagged, v8::internal::kTaggedPointer, v8::internal::kTaggedSigned, v8::internal::kTaggedSize, v8::internal::kWord16, v8::internal::kWord32, v8::internal::compiler::kWord32, v8::internal::kWord64, v8::internal::compiler::kWord64, v8::internal::kWord8, v8::internal::compiler::turboshaft::OpIndex, v8::internal::compiler::AtomicStoreParameters::representation(), store(), v8::internal::compiler::InstructionSelector::store_view(), v8::internal::compiler::OperandGenerator::TempRegister(), v8::internal::UNREACHABLE(), v8::internal::compiler::OperandGenerator::UseUniqueRegister(), v8::internal::v8_flags, v8::internal::value, v8::internal::compiler::AtomicStoreParameters::write_barrier_kind(), and v8::internal::compiler::WriteBarrierKindToRecordWriteMode().
VisitBinop() [1/3]
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitBinop (InstructionSelector * selector, OpIndex binop_idx, RegisterRepresentation rep, InstructionCode opcode, ImmediateMode operand_mode, FlagsContinuation * cont)
Definition at line 649 of file instruction-selector-arm64.cc.
                                                                     {
  const Operation& binop = selector->Get(binop_idx);
  OpIndex left_node = binop.input(0);
  OpIndex right_node = binop.input(1);
  return VisitBinopImpl(selector, binop_idx, left_node, right_node, rep, opcode,
                        operand_mode, cont);
}
References v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::input(), and VisitBinopImpl().
VisitBinop() [2/3]
template<typename Matcher >
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitBinop (InstructionSelector * selector, OpIndex node, ArchOpcode opcode, ImmediateMode operand_mode)
Definition at line 561 of file instruction-selector-arm64.cc.
                                            {
  FlagsContinuation cont;
  VisitBinop<Matcher>(selector, node, opcode, operand_mode, &cont);
}
VisitBinop() [3/3]
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitBinop (InstructionSelector * selector, OpIndex node, RegisterRepresentation rep, ArchOpcode opcode, ImmediateMode operand_mode)
Definition at line 659 of file instruction-selector-arm64.cc.
                                            {
  FlagsContinuation cont;
  VisitBinop(selector, node, rep, opcode, operand_mode, &cont);
}
References v8::internal::compiler::VisitBinop().
VisitBinopImpl()
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitBinopImpl (InstructionSelector * selector, OpIndex binop_idx, OpIndex left_node, OpIndex right_node, RegisterRepresentation rep, InstructionCode opcode, ImmediateMode operand_mode, FlagsContinuation * cont)
Definition at line 567 of file instruction-selector-arm64.cc.
                                                                         {
  DCHECK(!cont->IsConditionalSet() && !cont->IsConditionalBranch());
  Arm64OperandGenerator g(selector);
  constexpr uint32_t kMaxFlagSetInputs = 3;
  constexpr uint32_t kMaxSelectInputs = 2;
  constexpr uint32_t kMaxInputs = kMaxFlagSetInputs + kMaxSelectInputs;
  InstructionOperand inputs[kMaxInputs];
  size_t input_count = 0;
  InstructionOperand outputs[1];
  size_t output_count = 0;
  uint8_t properties = GetBinopProperties(opcode);
  bool can_commute = CanCommuteField::decode(properties);
  bool must_commute_cond = MustCommuteCondField::decode(properties);
  bool is_add_sub = IsAddSubField::decode(properties);
  if (g.CanBeImmediate(right_node, operand_mode)) {
    inputs[input_count++] = g.UseRegister(left_node);
    inputs[input_count++] = g.UseImmediate(right_node);
  } else if (can_commute && g.CanBeImmediate(left_node, operand_mode)) {
    if (must_commute_cond) cont->Commute();
    inputs[input_count++] = g.UseRegister(right_node);
    inputs[input_count++] = g.UseImmediate(left_node);
  } else if (is_add_sub &&
             TryMatchAnyExtend(&g, selector, binop_idx, left_node, right_node,
                               &inputs[0], &inputs[1], &opcode)) {
    input_count += 2;
  } else if (is_add_sub && can_commute &&
             TryMatchAnyExtend(&g, selector, binop_idx, right_node, left_node,
                               &inputs[0], &inputs[1], &opcode)) {
    if (must_commute_cond) cont->Commute();
    input_count += 2;
  } else if (TryMatchAnyShift(selector, binop_idx, right_node, &opcode,
                              !is_add_sub, rep)) {
    const ShiftOp& shift = selector->Get(right_node).Cast<ShiftOp>();
    inputs[input_count++] = g.UseRegisterOrImmediateZero(left_node);
    inputs[input_count++] = g.UseRegister(shift.left());
    // We only need at most the last 6 bits of the shift.
    int64_t constant;
    selector->MatchSignedIntegralConstant(shift.right(), &constant);
    inputs[input_count++] = g.UseImmediate(static_cast<int>(constant & 0x3F));
  } else if (can_commute && TryMatchAnyShift(selector, binop_idx, left_node,
                                             &opcode, !is_add_sub, rep)) {
    if (must_commute_cond) cont->Commute();
    const ShiftOp& shift = selector->Get(left_node).Cast<ShiftOp>();
    inputs[input_count++] = g.UseRegisterOrImmediateZero(right_node);
    inputs[input_count++] = g.UseRegister(shift.left());
    // We only need at most the last 6 bits of the shift.
    int64_t constant;
    selector->MatchSignedIntegralConstant(shift.right(), &constant);
    inputs[input_count++] = g.UseImmediate(static_cast<int>(constant & 0x3F));
  } else {
    inputs[input_count++] = g.UseRegisterOrImmediateZero(left_node);
    inputs[input_count++] = g.UseRegister(right_node);
  }
  if (!IsComparisonField::decode(properties)) {
    outputs[output_count++] = g.DefineAsRegister(binop_idx);
  }
  if (cont->IsSelect()) {
    // Keep the values live until the end so that we can use operations that
    // write registers to generate the condition, without accidently
    // overwriting the inputs.
    inputs[input_count++] = g.UseRegisterAtEnd(cont->true_value());
    inputs[input_count++] = g.UseRegisterAtEnd(cont->false_value());
  } else if (cont->IsBranch() && cont->hint() != BranchHint::kNone) {
    opcode |= BranchHintField::encode(true);
  }
  DCHECK_NE(0u, input_count);
  DCHECK((output_count != 0) || IsComparisonField::decode(properties));
  DCHECK_GE(arraysize(inputs), input_count);
  DCHECK_GE(arraysize(outputs), output_count);
  selector->EmitWithContinuation(opcode, output_count, outputs, input_count,
                                 inputs, cont);
}
References arraysize, v8::internal::compiler::Arm64OperandGenerator::CanBeImmediate(), v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::compiler::FlagsContinuation::Commute(), v8::internal::DCHECK(), DCHECK_GE, DCHECK_NE, v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::InstructionSelector::EmitWithContinuation(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::FlagsContinuation::false_value(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), GetBinopProperties(), v8::internal::compiler::FlagsContinuation::hint(), v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::FlagsContinuation::IsBranch(), v8::internal::compiler::FlagsContinuation::IsConditionalBranch(), v8::internal::compiler::FlagsContinuation::IsConditionalSet(), v8::internal::compiler::FlagsContinuation::IsSelect(), v8::internal::kNone, v8::internal::compiler::turboshaft::OperationMatcher::MatchSignedIntegralConstant(), v8::internal::compiler::turboshaft::ShiftOp::right(), v8::internal::compiler::FlagsContinuation::true_value(), TryMatchAnyExtend(), TryMatchAnyShift(), v8::internal::compiler::OperandGenerator::UseImmediate(), v8::internal::compiler::OperandGenerator::UseRegister(), v8::internal::compiler::OperandGenerator::UseRegisterAtEnd(), and v8::internal::compiler::Arm64OperandGenerator::UseRegisterOrImmediateZero().
Referenced by VisitBinop(), and VisitWord32Compare().
VisitCompare()
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitCompare (InstructionSelector * selector, InstructionCode opcode, InstructionOperand left, InstructionOperand right, FlagsContinuation * cont)
Definition at line 3108 of file instruction-selector-arm64.cc.
                                           {
  if (cont->IsSelect()) {
    Arm64OperandGenerator g(selector);
    InstructionOperand inputs[] = {
        left, right, g.UseRegisterOrImmediateZero(cont->true_value()),
        g.UseRegisterOrImmediateZero(cont->false_value())};
    selector->EmitWithContinuation(opcode, 0, nullptr, 4, inputs, cont);
  } else {
    selector->EmitWithContinuation(opcode, left, right, cont);
  }
}
References v8::internal::compiler::InstructionSelector::EmitWithContinuation(), v8::internal::compiler::FlagsContinuation::false_value(), v8::internal::compiler::FlagsContinuation::IsSelect(), v8::internal::compiler::FlagsContinuation::true_value(), and v8::internal::compiler::Arm64OperandGenerator::UseRegisterOrImmediateZero().
VisitFloat32Compare()
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitFloat32Compare (InstructionSelector * selector, OpIndex node, FlagsContinuation * cont)
Definition at line 3500 of file instruction-selector-arm64.cc.
                                                  {
  Arm64OperandGenerator g(selector);
  const ComparisonOp& op = selector->Get(node).template Cast<ComparisonOp>();
  OpIndex left = op.left();
  OpIndex right = op.right();
  if (selector->MatchZero(right)) {
    VisitCompare(selector, kArm64Float32Cmp, g.UseRegister(left),
                 g.UseImmediate(right), cont);
  } else if (selector->MatchZero(left)) {
    cont->Commute();
    VisitCompare(selector, kArm64Float32Cmp, g.UseRegister(right),
                 g.UseImmediate(left), cont);
  } else {
    VisitCompare(selector, kArm64Float32Cmp, g.UseRegister(left),
                 g.UseRegister(right), cont);
  }
}
References v8::internal::compiler::FlagsContinuation::Commute(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::ComparisonOp::left(), v8::internal::compiler::turboshaft::OperationMatcher::MatchZero(), v8::internal::compiler::turboshaft::ComparisonOp::right(), v8::internal::compiler::OperandGenerator::UseImmediate(), v8::internal::compiler::OperandGenerator::UseRegister(), and v8::internal::compiler::VisitCompare().
VisitFloat64Compare()
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitFloat64Compare (InstructionSelector * selector, OpIndex node, FlagsContinuation * cont)
Definition at line 3520 of file instruction-selector-arm64.cc.
                                                  {
  Arm64OperandGenerator g(selector);
  const Operation& compare = selector->Get(node);
  DCHECK(compare.Is<ComparisonOp>());
  OpIndex lhs = compare.input(0);
  OpIndex rhs = compare.input(1);
  if (selector->MatchZero(rhs)) {
    VisitCompare(selector, kArm64Float64Cmp, g.UseRegister(lhs),
                 g.UseImmediate(rhs), cont);
  } else if (selector->MatchZero(lhs)) {
    cont->Commute();
    VisitCompare(selector, kArm64Float64Cmp, g.UseRegister(rhs),
                 g.UseImmediate(lhs), cont);
  } else {
    VisitCompare(selector, kArm64Float64Cmp, g.UseRegister(lhs),
                 g.UseRegister(rhs), cont);
  }
}
References v8::internal::compiler::FlagsContinuation::Commute(), v8::internal::DCHECK(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::compiler::turboshaft::OperationMatcher::MatchZero(), v8::internal::compiler::OperandGenerator::UseImmediate(), v8::internal::compiler::OperandGenerator::UseRegister(), and v8::internal::compiler::VisitCompare().
VisitRR()
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitRR (InstructionSelector * selector, ArchOpcode opcode, OpIndex node)
Definition at line 191 of file instruction-selector-arm64.cc.
                                                                             {
  Arm64OperandGenerator g(selector);
  const Operation& op = selector->Get(node);
  DCHECK_EQ(op.input_count, 1);
  selector->Emit(opcode, g.DefineAsRegister(node), g.UseRegister(op.input(0)));
}
References DCHECK_EQ, v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::InstructionSelector::Emit(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::turboshaft::Operation::input_count, and v8::internal::compiler::OperandGenerator::UseRegister().
VisitRRO()
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitRRO (InstructionSelector * selector, ArchOpcode opcode, OpIndex node, ImmediateMode operand_mode)
Definition at line 253 of file instruction-selector-arm64.cc.
                                          {
  Arm64OperandGenerator g(selector);
  const Operation& op = selector->Get(node);
  DCHECK_EQ(op.input_count, 2);
  selector->Emit(opcode, g.DefineAsRegister(node), g.UseRegister(op.input(0)),
                 g.UseOperand(op.input(1), operand_mode));
}
References DCHECK_EQ, v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::InstructionSelector::Emit(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::turboshaft::Operation::input_count, v8::internal::compiler::Arm64OperandGenerator::UseOperand(), and v8::internal::compiler::OperandGenerator::UseRegister().
VisitRRR()
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitRRR (InstructionSelector * selector, InstructionCode opcode, OpIndex node)
Definition at line 198 of file instruction-selector-arm64.cc.
                            {
  Arm64OperandGenerator g(selector);
  const Operation& op = selector->Get(node);
  DCHECK_EQ(op.input_count, 2);
  selector->Emit(opcode, g.DefineAsRegister(node), g.UseRegister(op.input(0)),
                 g.UseRegister(op.input(1)));
}
References DCHECK_EQ, v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::InstructionSelector::Emit(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::turboshaft::Operation::input_count, and v8::internal::compiler::OperandGenerator::UseRegister().
VisitWord32Compare()
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitWord32Compare (InstructionSelector * selector, OpIndex node, FlagsContinuation * cont)
Definition at line 3389 of file instruction-selector-arm64.cc.
                                                 {
  const Operation& compare = selector->Get(node);
  DCHECK_GE(compare.input_count, 2);
  OpIndex lhs = compare.input(0);
  OpIndex rhs = compare.input(1);
  FlagsCondition cond = cont->condition();
  if (uint64_t constant;
      selector->MatchUnsignedIntegralConstant(rhs, &constant) &&
      TryEmitCbzOrTbz<32>(selector, lhs, static_cast<uint32_t>(constant), node,
                          cond, cont)) {
    return;
  }
  if (uint64_t constant;
      selector->MatchUnsignedIntegralConstant(lhs, &constant) &&
      TryEmitCbzOrTbz<32>(selector, rhs, static_cast<uint32_t>(constant), node,
                          CommuteFlagsCondition(cond), cont)) {
    return;
  }
  const Operation& left = selector->Get(lhs);
  const Operation& right = selector->Get(rhs);
  ArchOpcode opcode = kArm64Cmp32;
  ImmediateMode immediate_mode = kArithmeticImm;
  if (selector->MatchIntegralZero(rhs) &&
      (left.Is<Opmask::kWord32Add>() || left.Is<Opmask::kWord32BitwiseAnd>())) {
    // Emit flag setting add/and instructions for comparisons against zero.
    if (CanUseFlagSettingBinop(cond)) {
      MaybeReplaceCmpZeroWithFlagSettingBinop(selector, &node, lhs, &opcode,
                                              cond, cont, &immediate_mode);
    }
  } else if (selector->MatchIntegralZero(lhs) &&
             (right.Is<Opmask::kWord32Add>() ||
              right.Is<Opmask::kWord32BitwiseAnd>())) {
    // Same as above, but we need to commute the condition before we
    // continue with the rest of the checks.
    FlagsCondition commuted_cond = CommuteFlagsCondition(cond);
    if (CanUseFlagSettingBinop(commuted_cond)) {
      MaybeReplaceCmpZeroWithFlagSettingBinop(
          selector, &node, rhs, &opcode, commuted_cond, cont, &immediate_mode);
    }
  } else if (right.Is<Opmask::kWord32Sub>() &&
             (cond == kEqual || cond == kNotEqual)) {
    const WordBinopOp& sub = right.Cast<WordBinopOp>();
    if (selector->MatchIntegralZero(sub.left())) {
      // For a given compare(x, 0 - y) where compare is kEqual or kNotEqual,
      // it can be expressed as cmn(x, y).
      opcode = kArm64Cmn32;
      VisitBinopImpl(selector, node, lhs, sub.right(),
                     RegisterRepresentation::Word32(), opcode, immediate_mode,
                     cont);
      return;
    }
  }
  VisitBinop(selector, node, RegisterRepresentation::Word32(), opcode,
             immediate_mode, cont);
}
References CanUseFlagSettingBinop(), v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::compiler::CommuteFlagsCondition(), v8::internal::compiler::FlagsContinuation::condition(), DCHECK_GE, v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::turboshaft::Operation::input_count, v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::compiler::kArithmeticImm, v8::internal::kEqual, v8::internal::compiler::kNotEqual, v8::internal::compiler::turboshaft::WordBinopOp::left(), v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralZero(), v8::internal::compiler::turboshaft::OperationMatcher::MatchUnsignedIntegralConstant(), MaybeReplaceCmpZeroWithFlagSettingBinop(), v8::internal::compiler::turboshaft::WordBinopOp::right(), v8::internal::compiler::VisitBinop(), VisitBinopImpl(), and v8::internal::compiler::turboshaft::RegisterRepresentation::Word32().
VisitWord32Test()
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitWord32Test (InstructionSelector * selector, OpIndex node, FlagsContinuation * cont)
Definition at line 3456 of file instruction-selector-arm64.cc.
                                              {
  VisitWordTest(selector, node, kArm64Tst32, cont);
}
References VisitWordTest().
VisitWord64Test()
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitWord64Test (InstructionSelector * selector, OpIndex node, FlagsContinuation * cont)
Definition at line 3461 of file instruction-selector-arm64.cc.
                                              {
  VisitWordTest(selector, node, kArm64Tst, cont);
}
References VisitWordTest().
VisitWordCompare()
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitWordCompare (InstructionSelector * selector, OpIndex node, InstructionCode opcode, FlagsContinuation * cont, ImmediateMode immediate_mode)
Definition at line 3360 of file instruction-selector-arm64.cc.
                                                    {
  Arm64OperandGenerator g(selector);
  const Operation& op = selector->Get(node);
  DCHECK_EQ(op.input_count, 2);
  auto left = op.input(0);
  auto right = op.input(1);
  // If one of the two inputs is an immediate, make sure it's on the right.
  if (!g.CanBeImmediate(right, immediate_mode) &&
      g.CanBeImmediate(left, immediate_mode)) {
    cont->Commute();
    std::swap(left, right);
  }
  int64_t constant;
  if (opcode == kArm64Cmp &&
      selector->MatchSignedIntegralConstant(right, &constant)) {
    if (TryEmitCbzOrTbz<64>(selector, left, constant, node, cont->condition(),
                            cont)) {
      return;
    }
  }
  VisitCompare(selector, opcode, g.UseRegister(left),
               g.UseOperand(right, immediate_mode), cont);
}
References v8::internal::compiler::Arm64OperandGenerator::CanBeImmediate(), v8::internal::compiler::FlagsContinuation::Commute(), v8::internal::compiler::FlagsContinuation::condition(), DCHECK_EQ, v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::turboshaft::Operation::input_count, v8::internal::compiler::turboshaft::OperationMatcher::MatchSignedIntegralConstant(), v8::internal::compiler::Arm64OperandGenerator::UseOperand(), v8::internal::compiler::OperandGenerator::UseRegister(), and v8::internal::compiler::VisitCompare().
VisitWordTest()
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitWordTest (InstructionSelector * selector, OpIndex node, InstructionCode opcode, FlagsContinuation * cont)
Definition at line 3449 of file instruction-selector-arm64.cc.
                                                                    {
  Arm64OperandGenerator g(selector);
  VisitCompare(selector, opcode, g.UseRegister(node), g.UseRegister(node),
               cont);
}
References v8::internal::compiler::OperandGenerator::UseRegister(), and v8::internal::compiler::VisitCompare().
Referenced by VisitWord32Test(), and VisitWord64Test().