v8::internal::compiler::anonymous_namespace{redundancy-elimination.cc} Namespace Reference
Classes
struct Subsumption
Functions
Subsumption CheckSubsumes (Node const *a, Node const *b, MachineOperatorBuilder *machine)
bool TypeSubsumes (Node *node, Node *replacement)
Function Documentation
CheckSubsumes()
Subsumption v8::internal::compiler::anonymous_namespace{redundancy-elimination.cc}::CheckSubsumes (Node const * a, Node const * b, MachineOperatorBuilder * machine)
Definition at line 181 of file redundancy-elimination.cc.
                                                           {
  Subsumption subsumption = Subsumption::Implicit();
  if (a->op() != b->op()) {
    if (a->opcode() == IrOpcode::kCheckInternalizedString &&
        b->opcode() == IrOpcode::kCheckString) {
      // CheckInternalizedString(node) implies CheckString(node)
    } else if (a->opcode() == IrOpcode::kCheckString &&
               b->opcode() == IrOpcode::kCheckStringOrStringWrapper) {
      // CheckString(node) implies CheckStringOrStringWrapper(node)
    } else if (a->opcode() == IrOpcode::kCheckInternalizedString &&
               b->opcode() == IrOpcode::kCheckStringOrStringWrapper) {
      // CheckInteralizedString(node) implies CheckStringOrStringWrapper(node)
    } else if (a->opcode() == IrOpcode::kCheckSmi &&
               b->opcode() == IrOpcode::kCheckNumber) {
      // CheckSmi(node) implies CheckNumber(node)
    } else if (a->opcode() == IrOpcode::kCheckSmi &&
               b->opcode() == IrOpcode::kCheckNumberFitsInt32) {
      // CheckSmi(node) implies CheckNumberFitsInt32(node)
    } else if (a->opcode() == IrOpcode::kCheckNumberFitsInt32 &&
               b->opcode() == IrOpcode::kCheckNumber) {
      // CheckNumberFitsInt32(node) implies CheckNumber(node)
    } else if (a->opcode() == IrOpcode::kCheckedTaggedSignedToInt32 &&
               b->opcode() == IrOpcode::kCheckedTaggedToInt32) {
      // CheckedTaggedSignedToInt32(node) implies CheckedTaggedToInt32(node)
    } else if (a->opcode() == IrOpcode::kCheckedTaggedSignedToInt32 &&
               b->opcode() == IrOpcode::kCheckedTaggedToArrayIndex) {
      // CheckedTaggedSignedToInt32(node) implies
      // CheckedTaggedToArrayIndex(node)
      if (machine->Is64()) {
        // On 64 bit architectures, ArrayIndex is 64 bit.
        subsumption =
            Subsumption::WithConversion(machine->ChangeInt32ToInt64());
      }
    } else if (a->opcode() == IrOpcode::kCheckedTaggedToInt32 &&
               b->opcode() == IrOpcode::kCheckedTaggedToArrayIndex) {
      // CheckedTaggedToInt32(node) implies CheckedTaggedToArrayIndex(node)
      if (machine->Is64()) {
        // On 64 bit architectures, ArrayIndex is 64 bit.
        subsumption =
            Subsumption::WithConversion(machine->ChangeInt32ToInt64());
      }
    } else if (a->opcode() == IrOpcode::kCheckReceiver &&
               b->opcode() == IrOpcode::kCheckReceiverOrNullOrUndefined) {
      // CheckReceiver(node) implies CheckReceiverOrNullOrUndefined(node)
    } else if (a->opcode() != b->opcode()) {
      return Subsumption::None();
    } else {
      switch (a->opcode()) {
        case IrOpcode::kCheckBounds:
        case IrOpcode::kCheckSmi:
        case IrOpcode::kCheckString:
        case IrOpcode::kCheckStringOrStringWrapper:
        case IrOpcode::kCheckNumber:
        case IrOpcode::kCheckNumberFitsInt32:
        case IrOpcode::kCheckBigInt:
        case IrOpcode::kCheckedBigIntToBigInt64:
          break;
        case IrOpcode::kTypeGuard: {
          Type at = TypeGuardTypeOf(a->op());
          Type bt = TypeGuardTypeOf(b->op());
          // {a}.type has to be narrower than (or equal to) {b}.type for
          // {b}.type to be a redundant check.
          if (!at.Is(bt)) {
            return Subsumption::None();
          }
          break;
        }
        case IrOpcode::kCheckedInt32ToTaggedSigned:
        case IrOpcode::kCheckedInt64ToInt32:
        case IrOpcode::kCheckedInt64ToAdditiveSafeInteger:
        case IrOpcode::kCheckedInt64ToTaggedSigned:
        case IrOpcode::kCheckedTaggedSignedToInt32:
        case IrOpcode::kCheckedTaggedToTaggedPointer:
        case IrOpcode::kCheckedTaggedToTaggedSigned:
        case IrOpcode::kCheckedTaggedToArrayIndex:
        case IrOpcode::kCheckedUint32Bounds:
        case IrOpcode::kCheckedUint32ToInt32:
        case IrOpcode::kCheckedUint32ToTaggedSigned:
        case IrOpcode::kCheckedUint64Bounds:
        case IrOpcode::kCheckedUint64ToInt32:
        case IrOpcode::kCheckedUint64ToTaggedSigned:
          break;
        case IrOpcode::kCheckedFloat64ToInt32:
        case IrOpcode::kCheckedFloat64ToAdditiveSafeInteger:
        case IrOpcode::kCheckedFloat64ToInt64:
        case IrOpcode::kCheckedTaggedToInt32:
        case IrOpcode::kCheckedTaggedToAdditiveSafeInteger:
        case IrOpcode::kCheckedTaggedToInt64: {
          const CheckMinusZeroParameters& ap =
              CheckMinusZeroParametersOf(a->op());
          const CheckMinusZeroParameters& bp =
              CheckMinusZeroParametersOf(b->op());
          if (ap.mode() != bp.mode()) {
            return Subsumption::None();
          }
          break;
        }
        case IrOpcode::kCheckedTaggedToFloat64:
        case IrOpcode::kCheckedTruncateTaggedToWord32: {
          CheckTaggedInputParameters const& ap =
              CheckTaggedInputParametersOf(a->op());
          CheckTaggedInputParameters const& bp =
              CheckTaggedInputParametersOf(b->op());
          // {a} subsumes {b} if the modes are either the same, or {a} checks
          // for Number, in which case {b} will be subsumed no matter what.
          if (ap.mode() != bp.mode() &&
              ap.mode() != CheckTaggedInputMode::kNumber) {
            return Subsumption::None();
          }
          break;
        }
        default:
          DCHECK(!IsCheckedWithFeedback(a->op()));
          return Subsumption::None();
      }
    }
  }
  for (int i = a->op()->ValueInputCount(); --i >= 0;) {
    if (a->InputAt(i) != b->InputAt(i)) return Subsumption::None();
  }
  return subsumption;
}
References v8::internal::compiler::MachineOperatorBuilder::ChangeInt32ToInt64(), v8::internal::compiler::CheckMinusZeroParametersOf(), v8::internal::compiler::CheckTaggedInputParametersOf(), v8::internal::DCHECK(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Type::Is(), v8::internal::compiler::MachineOperatorBuilder::Is64(), v8::internal::compiler::IsCheckedWithFeedback(), v8::internal::compiler::kNumber, v8::internal::compiler::CheckTaggedInputParameters::mode(), v8::internal::compiler::CheckMinusZeroParameters::mode(), v8::None, v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::TypeGuardTypeOf(), and v8::internal::compiler::Operator::ValueInputCount().
Referenced by v8::internal::compiler::RedundancyElimination::EffectPathChecks::LookupCheck().
TypeSubsumes()
bool v8::internal::compiler::anonymous_namespace{redundancy-elimination.cc}::TypeSubsumes (Node * node, Node * replacement)
Definition at line 305 of file redundancy-elimination.cc.
                                                 {
  if (!NodeProperties::IsTyped(node) || !NodeProperties::IsTyped(replacement)) {
    // If either node is untyped, we are running during an untyped optimization
    // phase, and replacement is OK.
    return true;
  }
  Type node_type = NodeProperties::GetType(node);
  Type replacement_type = NodeProperties::GetType(replacement);
  return replacement_type.Is(node_type);
}
References v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::Type::Is(), and v8::internal::compiler::NodeProperties::IsTyped().
Referenced by v8::internal::compiler::RedundancyElimination::EffectPathChecks::LookupBoundsCheckFor(), and v8::internal::compiler::RedundancyElimination::EffectPathChecks::LookupCheck().