v8::internal::torque::ls::anonymous_namespace{message-handler.cc} Namespace Reference
Classes
class DiagnosticCollector
Functions
void ResetCompilationErrorDiagnostics (MessageWriter writer)
void SendCompilationDiagnostics (const TorqueCompilerResult &result, MessageWriter writer)
void RecompileTorque (MessageWriter writer)
void RecompileTorqueWithDiagnostics (MessageWriter writer)
void HandleInitializeRequest (InitializeRequest request, MessageWriter writer)
void HandleInitializedNotification (MessageWriter writer)
void HandleTorqueFileListNotification (TorqueFileListNotification notification, MessageWriter writer)
void HandleGotoDefinitionRequest (GotoDefinitionRequest request, MessageWriter writer)
void HandleChangeWatchedFilesNotification (DidChangeWatchedFilesNotification notification, MessageWriter writer)
void HandleDocumentSymbolRequest (DocumentSymbolRequest request, MessageWriter writer)
Function Documentation
HandleChangeWatchedFilesNotification()
void v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::HandleChangeWatchedFilesNotification (DidChangeWatchedFilesNotification notification, MessageWriter writer)
Definition at line 294 of file message-handler.cc.
                                                                          {
  // TODO(szuend): Implement updates to the TorqueFile list when create/delete
  // notifications are received. Currently we simply re-compile.
  RecompileTorqueWithDiagnostics(writer);
}
References RecompileTorqueWithDiagnostics().
Referenced by v8::internal::torque::ls::HandleMessage().
HandleDocumentSymbolRequest()
void v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::HandleDocumentSymbolRequest (DocumentSymbolRequest request, MessageWriter writer)
Definition at line 301 of file message-handler.cc.
                                                       {
  DocumentSymbolResponse response;
  response.set_id(request.id());
  SourceId id =
      SourceFileMap::GetSourceId(request.params().textDocument().uri());
  for (const auto& symbol : LanguageServerData::SymbolsForSourceId(id)) {
    DCHECK(symbol->IsUserDefined());
    if (symbol->IsMacro()) {
      Macro* macro = Macro::cast(symbol);
      SymbolInformation info = response.add_result();
      info.set_name(macro->ReadableName());
      info.set_kind(SymbolKind::kFunction);
      info.location().SetTo(macro->Position());
    } else if (symbol->IsBuiltin()) {
      Builtin* builtin = Builtin::cast(symbol);
      SymbolInformation info = response.add_result();
      info.set_name(builtin->ReadableName());
      info.set_kind(SymbolKind::kFunction);
      info.location().SetTo(builtin->Position());
    } else if (symbol->IsGenericCallable()) {
      GenericCallable* generic = GenericCallable::cast(symbol);
      SymbolInformation info = response.add_result();
      info.set_name(generic->name());
      info.set_kind(SymbolKind::kFunction);
      info.location().SetTo(generic->Position());
    } else if (symbol->IsTypeAlias()) {
      const Type* type = TypeAlias::cast(symbol)->type();
      SymbolKind kind =
          type->IsClassType() ? SymbolKind::kClass : SymbolKind::kStruct;
      SymbolInformation sym = response.add_result();
      sym.set_name(type->ToString());
      sym.set_kind(kind);
      sym.location().SetTo(symbol->Position());
    }
  }
  // Trigger empty array creation in case no symbols were found.
  USE(response.result_size());
  writer(std::move(response.GetJsonValue()));
}
References v8::internal::DCHECK(), v8::internal::torque::ls::Message::GetJsonValue(), v8::internal::torque::SourceFileMap::GetSourceId(), v8::internal::torque::ls::kClass, v8::internal::torque::ls::kFunction, v8::internal::torque::ls::kStruct, v8::internal::torque::Declarable::Position(), v8::internal::torque::Callable::ReadableName(), v8::internal::torque::LanguageServerData::SymbolsForSourceId(), v8::internal::tracing::type, and USE.
Referenced by v8::internal::torque::ls::HandleMessage().
HandleGotoDefinitionRequest()
void v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::HandleGotoDefinitionRequest (GotoDefinitionRequest request, MessageWriter writer)
Definition at line 264 of file message-handler.cc.
                                                       {
  GotoDefinitionResponse response;
  response.set_id(request.id());
  SourceId id =
      SourceFileMap::GetSourceId(request.params().textDocument().uri());
  // Unknown source files cause an empty response which corresponds with
  // the definition not beeing found.
  if (!id.IsValid()) {
    response.SetNull("result");
    writer(std::move(response.GetJsonValue()));
    return;
  }
  auto pos =
      LineAndColumn::WithUnknownOffset(request.params().position().line(),
                                       request.params().position().character());
  if (auto maybe_definition = LanguageServerData::FindDefinition(id, pos)) {
    SourcePosition definition = *maybe_definition;
    response.result().SetTo(definition);
  } else {
    response.SetNull("result");
  }
  writer(std::move(response.GetJsonValue()));
}
References v8::internal::torque::LanguageServerData::FindDefinition(), v8::internal::torque::ls::Message::GetJsonValue(), v8::internal::torque::SourceFileMap::GetSourceId(), v8::internal::torque::ls::BaseJsonAccessor::SetNull(), and v8::internal::torque::LineAndColumn::WithUnknownOffset().
Referenced by v8::internal::torque::ls::HandleMessage().
HandleInitializedNotification()
void v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::HandleInitializedNotification (MessageWriter writer)
Definition at line 226 of file message-handler.cc.
                                                         {
  RegistrationRequest request;
  // TODO(szuend): The language server needs a "global" request id counter.
  request.set_id(2000);
  request.set_method("client/registerCapability");
  Registration reg = request.params().add_registrations();
  auto options =
      reg.registerOptions<DidChangeWatchedFilesRegistrationOptions>();
  FileSystemWatcher watcher = options.add_watchers();
  watcher.set_globPattern("**/*.tq");
  watcher.set_kind(FileSystemWatcher::WatchKind::kAll);
  reg.set_id("did-change-id");
  reg.set_method("workspace/didChangeWatchedFiles");
  writer(std::move(request.GetJsonValue()));
}
References v8::internal::torque::ls::Message::GetJsonValue().
Referenced by v8::internal::torque::ls::HandleMessage().
HandleInitializeRequest()
void v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::HandleInitializeRequest (InitializeRequest request, MessageWriter writer)
Definition at line 209 of file message-handler.cc.
                                                                              {
  InitializeResponse response;
  response.set_id(request.id());
  response.result().capabilities().textDocumentSync();
  response.result().capabilities().set_definitionProvider(true);
  response.result().capabilities().set_documentSymbolProvider(true);
  // TODO(szuend): Register for document synchronisation here,
  // so we work with the content that the client
  // provides, not directly read from files.
  // TODO(szuend): Check that the client actually supports dynamic
  // "workspace/didChangeWatchedFiles" capability.
  // TODO(szuend): Check if client supports "LocationLink". This will
  // influence the result of "goto definition".
  writer(std::move(response.GetJsonValue()));
}
References v8::internal::torque::ls::Message::GetJsonValue().
Referenced by v8::internal::torque::ls::HandleMessage().
HandleTorqueFileListNotification()
void v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::HandleTorqueFileListNotification (TorqueFileListNotification notification, MessageWriter writer)
Definition at line 245 of file message-handler.cc.
                                                            {
  CHECK_EQ(notification.params().object()["files"].tag, JsonValue::ARRAY);
  std::vector<std::string>& files = TorqueFileList::Get();
  Logger::Log("[info] Initial file list:\n");
  for (const auto& file_json :
       notification.params().object()["files"].ToArray()) {
    CHECK(file_json.IsString());
    // We only consider file URIs (there shouldn't be anything else).
    // Internally we store the URI instead of the path, eliminating the need
    // to encode it again.
    files.push_back(file_json.ToString());
    Logger::Log(" ", file_json.ToString(), "\n");
  }
  RecompileTorqueWithDiagnostics(writer);
}
References v8::internal::torque::ls::JsonValue::ARRAY, CHECK, CHECK_EQ, v8::internal::compiler::turboshaft::Get(), v8::internal::torque::Logger::Log(), v8::internal::torque::ls::Message::object(), and RecompileTorqueWithDiagnostics().
Referenced by v8::internal::torque::ls::HandleMessage().
RecompileTorque()
void v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::RecompileTorque (MessageWriter writer)
Definition at line 189 of file message-handler.cc.
                                           {
  Logger::Log("[info] Start compilation run ...\n");
  TorqueCompilerOptions options;
  options.output_directory = "";
  options.collect_language_server_data = true;
  options.force_assert_statements = true;
  TorqueCompilerResult result = CompileTorque(TorqueFileList::Get(), options);
  Logger::Log("[info] Finished compilation run ...\n");
  CompilationFinished(std::move(result), writer);
}
References v8::internal::torque::TorqueCompilerOptions::collect_language_server_data, v8::internal::torque::ls::CompilationFinished(), v8::internal::torque::CompileTorque(), v8::internal::torque::TorqueCompilerOptions::force_assert_statements, v8::internal::compiler::turboshaft::Get(), v8::internal::torque::Logger::Log(), v8::internal::torque::TorqueCompilerOptions::output_directory, and v8::base::internal::result.
Referenced by RecompileTorqueWithDiagnostics().
RecompileTorqueWithDiagnostics()
void v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::RecompileTorqueWithDiagnostics (MessageWriter writer)
Definition at line 204 of file message-handler.cc.
                                                          {
  ResetCompilationErrorDiagnostics(writer);
  RecompileTorque(writer);
}
References RecompileTorque(), and ResetCompilationErrorDiagnostics().
Referenced by HandleChangeWatchedFilesNotification(), and HandleTorqueFileListNotification().
ResetCompilationErrorDiagnostics()
void v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::ResetCompilationErrorDiagnostics (MessageWriter writer)
Definition at line 65 of file message-handler.cc.
                                                            {
  for (const SourceId& source : DiagnosticsFiles::Get()) {
    PublishDiagnosticsNotification notification;
    notification.set_method("textDocument/publishDiagnostics");
    std::string error_file = SourceFileMap::AbsolutePath(source);
    notification.params().set_uri(error_file);
    // Trigger empty array creation.
    USE(notification.params().diagnostics_size());
    writer(std::move(notification.GetJsonValue()));
  }
  DiagnosticsFiles::Get() = {};
}
References v8::internal::torque::SourceFileMap::AbsolutePath(), v8::internal::compiler::turboshaft::Get(), v8::internal::torque::ls::Message::GetJsonValue(), v8::internal::string, and USE.
Referenced by RecompileTorqueWithDiagnostics().
SendCompilationDiagnostics()
void v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::SendCompilationDiagnostics (const TorqueCompilerResult & result, MessageWriter writer)
Definition at line 158 of file message-handler.cc.
                                                      {
  DiagnosticCollector collector;
  // TODO(szuend): Split up messages by SourceId and sort them by line number.
  for (const TorqueMessage& message : result.messages) {
    collector.AddTorqueMessage(message);
  }
  for (auto& pair : collector.notifications()) {
    PublishDiagnosticsNotification& notification = pair.second;
    writer(std::move(notification.GetJsonValue()));
    // Record all source files for which notifications are sent, so they
    // can be reset before the next compiler run.
    const SourceId& source = pair.first;
    if (source.IsValid()) DiagnosticsFiles::Get().push_back(source);
  }
}
References v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::DiagnosticCollector::AddTorqueMessage(), v8::internal::compiler::turboshaft::Get(), v8::internal::torque::ls::Message::GetJsonValue(), v8::internal::torque::SourceId::IsValid(), v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::DiagnosticCollector::notifications(), and v8::base::internal::result.
Referenced by v8::internal::torque::ls::CompilationFinished().