v8::internal::compiler::anonymous_namespace{move-optimizer.cc} Namespace Reference
Classes
struct MoveKey
class OperandSet
Functions
int FindFirstNonEmptySlot (const Instruction *instr)
bool IsSlot (const InstructionOperand &op)
bool Is64BitsWide (const InstructionOperand &op)
bool LoadCompare (const MoveOperands *a, const MoveOperands *b)
Function Documentation
FindFirstNonEmptySlot()
int v8::internal::compiler::anonymous_namespace{move-optimizer.cc}::FindFirstNonEmptySlot (const Instruction * instr)
Definition at line 111 of file move-optimizer.cc.
                                                    {
  int i = Instruction::FIRST_GAP_POSITION;
  for (; i <= Instruction::LAST_GAP_POSITION; i++) {
    ParallelMove* moves = instr->parallel_moves()[i];
    if (moves == nullptr) continue;
    for (MoveOperands* move : *moves) {
      if (!move->IsRedundant()) return i;
      move->Eliminate();
    }
    moves->clear(); // Clear this redundant move.
  }
  return i;
}
References v8::internal::compiler::Instruction::FIRST_GAP_POSITION, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::Instruction::LAST_GAP_POSITION, and v8::internal::compiler::Instruction::parallel_moves().
Referenced by v8::internal::compiler::MoveOptimizer::CompressGaps().
Is64BitsWide()
bool v8::internal::compiler::anonymous_namespace{move-optimizer.cc}::Is64BitsWide (const InstructionOperand & op)
Definition at line 512 of file move-optimizer.cc.
                                                {
  MachineRepresentation rep = LocationOperand::cast(&op)->representation();
#if V8_COMPRESS_POINTERS
  // We can't use {ElementSizeInBytes} because it's made for on-heap object
  // slots and assumes that kTagged == kCompressed, whereas for the purpose
  // here we specifically need to distinguish those cases.
  return (rep == MachineRepresentation::kTagged ||
          rep == MachineRepresentation::kTaggedPointer ||
          rep == MachineRepresentation::kWord64);
#else
  return rep == MachineRepresentation::kWord64;
#endif
}
References v8::internal::compiler::LocationOperand::cast(), v8::internal::kTagged, v8::internal::kTaggedPointer, v8::internal::kWord64, and v8::internal::compiler::LocationOperand::representation().
Referenced by LoadCompare().
IsSlot()
bool v8::internal::compiler::anonymous_namespace{move-optimizer.cc}::IsSlot (const InstructionOperand & op)
Definition at line 508 of file move-optimizer.cc.
                                          {
  return op.IsStackSlot() || op.IsFPStackSlot();
}
References v8::internal::compiler::InstructionOperand::IsFPStackSlot(), and v8::internal::compiler::InstructionOperand::IsStackSlot().
Referenced by v8::internal::compiler::MoveOptimizer::FinalizeMoves(), and LoadCompare().
LoadCompare()
bool v8::internal::compiler::anonymous_namespace{move-optimizer.cc}::LoadCompare (const MoveOperands * a, const MoveOperands * b)
Definition at line 526 of file move-optimizer.cc.
                                                               {
  if (!a->source().EqualsCanonicalized(b->source())) {
    return a->source().CompareCanonicalized(b->source());
  }
  // The replacements below are only safe if wider values are preferred.
  // In particular, replacing an uncompressed pointer with a compressed
  // pointer is disallowed.
  if (a->destination().IsLocationOperand() &&
      b->destination().IsLocationOperand()) {
    if (Is64BitsWide(a->destination()) && !Is64BitsWide(b->destination())) {
      return true;
    }
    if (!Is64BitsWide(a->destination()) && Is64BitsWide(b->destination())) {
      return false;
    }
  }
  if (IsSlot(a->destination()) && !IsSlot(b->destination())) return false;
  if (!IsSlot(a->destination()) && IsSlot(b->destination())) return true;
  return a->destination().CompareCanonicalized(b->destination());
}
References v8::internal::compiler::InstructionOperand::CompareCanonicalized(), v8::internal::compiler::MoveOperands::destination(), v8::internal::compiler::InstructionOperand::EqualsCanonicalized(), Is64BitsWide(), v8::internal::compiler::InstructionOperand::IsLocationOperand(), IsSlot(), and v8::internal::compiler::MoveOperands::source().
Referenced by v8::internal::compiler::MoveOptimizer::FinalizeMoves().