v8::internal::wasm::anonymous_namespace{wasm-serialization.cc} Namespace Reference
Classes
class Writer
class Reader
class ExternalReferenceList
Functions
void WriteHeader (Writer *writer, WasmEnabledFeatures enabled_features)
void SetWasmCalleeTag (WritableRelocInfo *rinfo, uint32_t tag)
uint32_t GetWasmCalleeTag (RelocInfo *rinfo)
Variables
constexpr uint8_t kLazyFunction = 2
constexpr uint8_t kEagerFunction = 3
constexpr uint8_t kTurboFanFunction = 4
constexpr size_t kCodeHeaderSize
Function Documentation
GetWasmCalleeTag()
uint32_t v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::GetWasmCalleeTag (RelocInfo * rinfo)
Definition at line 183 of file wasm-serialization.cc.
                                            {
#if V8_TARGET_ARCH_X64 || V8_TARGET_ARCH_IA32
  DCHECK(!RelocInfo::IsCompressedEmbeddedObject(rinfo->rmode()));
  return ReadUnalignedValue<uint32_t>(rinfo->target_address_address());
#elif V8_TARGET_ARCH_ARM64
  Instruction* instr = reinterpret_cast<Instruction*>(rinfo->pc());
  if (instr->IsLdrLiteralX()) {
    return ReadUnalignedValue<uint32_t>(rinfo->constant_pool_entry_address());
  } else {
    DCHECK(instr->IsBranchAndLink() || instr->IsUnconditionalBranch());
    return static_cast<uint32_t>(instr->ImmPCOffset() / kInstrSize);
  }
#elif V8_TARGET_ARCH_RISCV64 || V8_TARGET_ARCH_RISCV32
  Instruction* instr = reinterpret_cast<Instruction*>(rinfo->pc());
  if (instr->IsAUIPC()) {
    Instr auipc = instr->InstructionBits();
    Instr jalr = reinterpret_cast<Instruction*>(rinfo->pc() + 1 * kInstrSize)
                     ->InstructionBits();
    return Assembler::BrachlongOffset(auipc, jalr);
  } else {
    return static_cast<uint32_t>(rinfo->target_address());
  }
#else
  Address addr;
  if (rinfo->rmode() == RelocInfo::EXTERNAL_REFERENCE) {
    addr = rinfo->target_external_reference();
  } else if (rinfo->rmode() == RelocInfo::WASM_STUB_CALL) {
    addr = rinfo->wasm_stub_call_address();
  } else {
    addr = rinfo->target_address();
  }
  return static_cast<uint32_t>(addr);
#endif
}
References v8::internal::Assembler::BrachlongOffset(), v8::internal::RelocInfo::constant_pool_entry_address(), v8::internal::DCHECK(), v8::internal::RelocInfo::EXTERNAL_REFERENCE, v8::internal::Instruction::ImmPCOffset(), v8::internal::Instruction::InstructionBits(), v8::internal::InstructionGetters< T >::IsAUIPC(), v8::internal::Instruction::IsBranchAndLink(), v8::internal::RelocInfo::IsCompressedEmbeddedObject(), v8::internal::Instruction::IsLdrLiteralX(), v8::internal::Instruction::IsUnconditionalBranch(), v8::internal::kInstrSize, v8::internal::RelocInfo::pc(), v8::internal::RelocInfo::rmode(), v8::internal::RelocInfo::target_address(), v8::internal::RelocInfo::target_address_address(), v8::internal::RelocInfo::target_external_reference(), v8::internal::RelocInfo::WASM_STUB_CALL, and v8::internal::RelocInfo::wasm_stub_call_address().
Referenced by v8::internal::wasm::NativeModuleDeserializer::CopyAndRelocate().
SetWasmCalleeTag()
void v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::SetWasmCalleeTag (WritableRelocInfo * rinfo, uint32_t tag)
Definition at line 142 of file wasm-serialization.cc.
                                                              {
#if V8_TARGET_ARCH_X64 || V8_TARGET_ARCH_IA32
  DCHECK(rinfo->HasTargetAddressAddress());
  DCHECK(!RelocInfo::IsCompressedEmbeddedObject(rinfo->rmode()));
  WriteUnalignedValue(rinfo->target_address_address(), tag);
#elif V8_TARGET_ARCH_ARM64
  Instruction* instr = reinterpret_cast<Instruction*>(rinfo->pc());
  if (instr->IsLdrLiteralX()) {
    WriteUnalignedValue(rinfo->constant_pool_entry_address(),
                        static_cast<Address>(tag));
  } else {
    DCHECK(instr->IsBranchAndLink() || instr->IsUnconditionalBranch());
    instr->SetBranchImmTarget<UncondBranchType>(
        reinterpret_cast<Instruction*>(rinfo->pc() + tag * kInstrSize));
  }
#elif V8_TARGET_ARCH_RISCV64 || V8_TARGET_ARCH_RISCV32
  Instruction* instr = reinterpret_cast<Instruction*>(rinfo->pc());
  if (instr->IsAUIPC()) {
    Instr auipc = instr->InstructionBits();
    Instr jalr = reinterpret_cast<Instruction*>(rinfo->pc() + 1 * kInstrSize)
                     ->InstructionBits();
    DCHECK(is_int32(tag + 0x800));
    Assembler::PatchBranchlongOffset(rinfo->pc(), auipc, jalr, (int32_t)tag,
                                     nullptr);
  } else {
    Assembler::set_target_address_at(rinfo->pc(), rinfo->constant_pool(),
                                     static_cast<Address>(tag), nullptr,
                                     SKIP_ICACHE_FLUSH);
  }
#else
  Address addr = static_cast<Address>(tag);
  if (rinfo->rmode() == RelocInfo::EXTERNAL_REFERENCE) {
    rinfo->set_target_external_reference(addr, SKIP_ICACHE_FLUSH);
  } else if (rinfo->rmode() == RelocInfo::WASM_STUB_CALL) {
    rinfo->set_wasm_stub_call_address(addr);
  } else {
    rinfo->set_target_address(addr, SKIP_ICACHE_FLUSH);
  }
#endif
}
References v8::internal::RelocInfo::constant_pool(), v8::internal::RelocInfo::constant_pool_entry_address(), v8::internal::DCHECK(), v8::internal::RelocInfo::EXTERNAL_REFERENCE, v8::internal::RelocInfo::HasTargetAddressAddress(), v8::internal::Instruction::InstructionBits(), v8::internal::InstructionGetters< T >::IsAUIPC(), v8::internal::Instruction::IsBranchAndLink(), v8::internal::RelocInfo::IsCompressedEmbeddedObject(), v8::internal::Instruction::IsLdrLiteralX(), v8::internal::Instruction::IsUnconditionalBranch(), v8::internal::kInstrSize, v8::internal::Assembler::PatchBranchlongOffset(), v8::internal::RelocInfo::pc(), v8::internal::RelocInfo::rmode(), v8::internal::WritableRelocInfo::set_target_address(), v8::internal::Assembler::set_target_address_at(), v8::internal::WritableRelocInfo::set_target_external_reference(), v8::internal::WritableRelocInfo::set_wasm_stub_call_address(), v8::internal::Instruction::SetBranchImmTarget(), v8::internal::SKIP_ICACHE_FLUSH, v8::internal::RelocInfo::target_address_address(), v8::internal::UncondBranchType, v8::internal::RelocInfo::WASM_STUB_CALL, and v8::base::WriteUnalignedValue().
Referenced by v8::internal::wasm::NativeModuleSerializer::WriteCode().
WriteHeader()
void v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::WriteHeader (Writer * writer, WasmEnabledFeatures enabled_features)
Definition at line 127 of file wasm-serialization.cc.
                                                                       {
  DCHECK_EQ(0, writer->bytes_written());
  writer->Write(SerializedData::kMagicNumber);
  writer->Write(Version::Hash());
  writer->Write(static_cast<uint32_t>(CpuFeatures::SupportedFeatures()));
  writer->Write(FlagList::Hash());
  writer->Write(enabled_features.ToIntegral());
  DCHECK_EQ(WasmSerializer::kHeaderSize, writer->bytes_written());
}
References v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::Writer::bytes_written(), DCHECK_EQ, v8::internal::FlagList::Hash(), v8::internal::Version::Hash(), v8::internal::wasm::WasmSerializer::kHeaderSize, v8::internal::SerializedData::kMagicNumber, v8::internal::CpuFeatures::SupportedFeatures(), v8::base::EnumSet< E, T >::ToIntegral(), and v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::Writer::Write().
Variable Documentation
kCodeHeaderSize
constexpr size_t v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::kCodeHeaderSize [constexpr]
Initial value:
= sizeof(uint8_t) +
                                   sizeof(int) +
                                   sizeof(int) +
                                   sizeof(int) +
                                   sizeof(int) +
                                   sizeof(int) +
                                   sizeof(int) +
                                   sizeof(int) +
                                   sizeof(int) +
                                   sizeof(int) +
                                   sizeof(int) +
                                   sizeof(int) +
                                   sizeof(int) +
                                   sizeof(int) +
                                   sizeof(int) +
                                   sizeof(int) +
                                   sizeof(WasmCode::Kind) +
                                   sizeof(ExecutionTier)
Definition at line 218 of file wasm-serialization.cc.
Referenced by v8::internal::wasm::NativeModuleSerializer::MeasureCode().
kEagerFunction
constexpr uint8_t v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::kEagerFunction = 3 [constexpr]
Definition at line 30 of file wasm-serialization.cc.
Referenced by v8::internal::wasm::NativeModuleDeserializer::ReadCode(), and v8::internal::wasm::NativeModuleSerializer::WriteCode().
kLazyFunction
constexpr uint8_t v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::kLazyFunction = 2 [constexpr]
Definition at line 29 of file wasm-serialization.cc.
Referenced by v8::internal::wasm::NativeModuleDeserializer::ReadCode(), and v8::internal::wasm::NativeModuleSerializer::WriteCode().
kTurboFanFunction
constexpr uint8_t v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::kTurboFanFunction = 4 [constexpr]
Definition at line 31 of file wasm-serialization.cc.
Referenced by v8::internal::wasm::NativeModuleSerializer::WriteCode().