v8::internal::interpreter::anonymous_namespace{bytecode-operands.cc} Namespace Reference
Functions
const char * ImplicitRegisterUseToString (ImplicitRegisterUse implicit_register_use)
const char * OperandTypeToString (OperandType operand_type)
const char * OperandScaleToString (OperandScale operand_scale)
const char * OperandSizeToString (OperandSize operand_size)
Function Documentation
ImplicitRegisterUseToString()
const char* v8::internal::interpreter::anonymous_namespace{bytecode-operands.cc}::ImplicitRegisterUseToString (ImplicitRegisterUse implicit_register_use)
Definition at line 15 of file bytecode-operands.cc.
                                               {
  switch (implicit_register_use) {
    case ImplicitRegisterUse::kNone:
      return "None";
    case ImplicitRegisterUse::kReadAccumulator:
      return "ReadAccumulator";
    case ImplicitRegisterUse::kWriteAccumulator:
      return "WriteAccumulator";
    case ImplicitRegisterUse::kClobberAccumulator:
      return "ClobberAccumulator";
    case ImplicitRegisterUse::kWriteShortStar:
      return "WriteShortStar";
    case ImplicitRegisterUse::kReadAndClobberAccumulator:
      return "ReadAndClobberAccumulator";
    case ImplicitRegisterUse::kReadWriteAccumulator:
      return "ReadWriteAccumulator";
    case ImplicitRegisterUse::kReadAccumulatorWriteShortStar:
      return "ReadAccumulatorWriteShortStar";
  }
  UNREACHABLE();
}
References v8::internal::interpreter::kClobberAccumulator, v8::internal::interpreter::kNone, v8::internal::interpreter::kReadAccumulator, v8::internal::interpreter::kReadAccumulatorWriteShortStar, v8::internal::interpreter::kReadAndClobberAccumulator, v8::internal::interpreter::kReadWriteAccumulator, v8::internal::interpreter::kWriteAccumulator, v8::internal::interpreter::kWriteShortStar, and v8::internal::UNREACHABLE().
Referenced by v8::internal::interpreter::operator<<().
OperandScaleToString()
const char* v8::internal::interpreter::anonymous_namespace{bytecode-operands.cc}::OperandScaleToString (OperandScale operand_scale)
Definition at line 49 of file bytecode-operands.cc.
                                                             {
  switch (operand_scale) {
#define CASE(Name, _) \
  case OperandScale::k##Name: \
    return #Name;
    OPERAND_SCALE_LIST(CASE)
#undef CASE
  }
  UNREACHABLE();
}
References CASE, OPERAND_SCALE_LIST, and v8::internal::UNREACHABLE().
Referenced by v8::internal::interpreter::operator<<().
OperandSizeToString()
const char* v8::internal::interpreter::anonymous_namespace{bytecode-operands.cc}::OperandSizeToString (OperandSize operand_size)
Definition at line 60 of file bytecode-operands.cc.
                                                          {
  switch (operand_size) {
    case OperandSize::kNone:
      return "None";
    case OperandSize::kByte:
      return "Byte";
    case OperandSize::kShort:
      return "Short";
    case OperandSize::kQuad:
      return "Quad";
  }
  UNREACHABLE();
}
References v8::internal::interpreter::kByte, v8::internal::interpreter::kNone, v8::internal::interpreter::kQuad, v8::internal::interpreter::kShort, and v8::internal::UNREACHABLE().
Referenced by v8::internal::interpreter::operator<<().
OperandTypeToString()
const char* v8::internal::interpreter::anonymous_namespace{bytecode-operands.cc}::OperandTypeToString (OperandType operand_type)
Definition at line 38 of file bytecode-operands.cc.
                                                          {
  switch (operand_type) {
#define CASE(Name, _) \
  case OperandType::k##Name: \
    return #Name;
    OPERAND_TYPE_LIST(CASE)
#undef CASE
  }
  UNREACHABLE();
}
References CASE, OPERAND_TYPE_LIST, and v8::internal::UNREACHABLE().
Referenced by v8::internal::interpreter::operator<<().