wasm::anonymous_namespace{c-api.cc} Namespace Reference
Classes
struct FrameImpl
class SignatureHelper
Typedefs
using PtrComprCageAccessScope = i::PtrComprCageAccessScope
Functions
auto ReadLebU64 (const byte_t **pos) -> uint64_t
template<typename T >
ValKind V8ValueTypeToWasm (T v8_valtype) requires(std
i::wasm::ValueType WasmValKindToV8 (ValKind kind)
Name GetNameFromWireBytes (const i::wasm::WireBytesRef &ref, v8::base::Vector< const uint8_t > wire_bytes)
own< FuncType > FunctionSigToFuncType (const i::wasm::FunctionSig *sig)
own< ExternType > GetImportExportType (const i::wasm::WasmModule *module, const i::wasm::ImportExportKindCode kind, const uint32_t index)
own< Instance > GetInstance (StoreImpl *store, i::DirectHandle< i::WasmInstanceObject > instance)
own< Frame > CreateFrameFromInternal (i::DirectHandle< i::FixedArray > frames, int index, i::Isolate *isolate, StoreImpl *store)
auto make_func (Store *store_abs, std::shared_ptr< FuncData > data) -> own< Func >
own< Ref > V8RefValueToWasm (StoreImpl *store, i::DirectHandle< i::Object > value)
i::DirectHandle< i::Object > WasmRefToV8 (i::Isolate *isolate, const Ref *ref)
void PrepareFunctionData (i::Isolate *isolate, i::DirectHandle< i::WasmExportedFunctionData > function_data, const i::wasm::CanonicalSig *sig)
void PushArgs (const i::wasm::CanonicalSig *sig, const vec< Val > &args, i::wasm::CWasmArgumentsPacker *packer, StoreImpl *store)
void PopArgs (const i::wasm::CanonicalSig *sig, vec< Val > &results, i::wasm::CWasmArgumentsPacker *packer, StoreImpl *store)
own< Trap > CallWasmCapiFunction (i::Tagged< i::WasmCapiFunctionData > data, const vec< Val > &args, vec< Val > &results)
i::DirectHandle< i::JSReceiver > GetProperException (i::Isolate *isolate, i::DirectHandle< i::Object > maybe_exception)
Typedef Documentation
PtrComprCageAccessScope
using wasm::anonymous_namespace{c-api.cc}::PtrComprCageAccessScope = typedef i::PtrComprCageAccessScope
Definition at line 100 of file c-api.cc.
Function Documentation
CallWasmCapiFunction()
own<Trap> wasm::anonymous_namespace{c-api.cc}::CallWasmCapiFunction (i::Tagged< i::WasmCapiFunctionData > data, const vec< Val > & args, vec< Val > & results)
Definition at line 1769 of file c-api.cc.
                                                                        {
  FuncData* func_data =
      i::Cast<i::Managed<FuncData>>(data->embedder_data())->raw();
  if (func_data->kind == FuncData::kCallback) {
    return (func_data->callback)(args, results);
  }
  DCHECK(func_data->kind == FuncData::kCallbackWithEnv);
  return (func_data->callback_with_env)(func_data->env, args, results);
}
References v8::base::args, wasm::FuncData::callback, wasm::FuncData::callback_with_env, DCHECK, wasm::FuncData::env, wasm::FuncData::kCallback, wasm::FuncData::kCallbackWithEnv, and wasm::FuncData::kind.
CreateFrameFromInternal()
own<Frame> wasm::anonymous_namespace{c-api.cc}::CreateFrameFromInternal (i::DirectHandle< i::FixedArray > frames, int index, i::Isolate * isolate, StoreImpl * store)
Definition at line 1129 of file c-api.cc.
                                                     {
  PtrComprCageAccessScope ptr_compr_cage_access_scope(isolate);
  i::DirectHandle<i::CallSiteInfo> frame(
      i::Cast<i::CallSiteInfo>(frames->get(index)), isolate);
  i::DirectHandle<i::WasmInstanceObject> instance(frame->GetWasmInstance(),
                                                  isolate);
  uint32_t func_index = frame->GetWasmFunctionIndex();
  size_t module_offset = i::CallSiteInfo::GetSourcePosition(frame);
  size_t func_offset = module_offset - i::wasm::GetWasmFunctionOffset(
                                           instance->module(), func_index);
  return own<Frame>(seal<Frame>(new (std::nothrow) FrameImpl(
      GetInstance(store, instance), func_index, func_offset, module_offset)));
}
References GetInstance(), v8::internal::CallSiteInfo::GetSourcePosition(), v8::internal::wasm::GetWasmFunctionOffset(), v8::internal::index, and store().
FunctionSigToFuncType()
own<FuncType> wasm::anonymous_namespace{c-api.cc}::FunctionSigToFuncType (const i::wasm::FunctionSig * sig)
Definition at line 174 of file c-api.cc.
                                                                 {
  size_t param_count = sig->parameter_count();
  ownvec<ValType> params = ownvec<ValType>::make_uninitialized(param_count);
  for (size_t i = 0; i < param_count; i++) {
    params[i] = ValType::make(V8ValueTypeToWasm(sig->GetParam(i)));
  }
  size_t return_count = sig->return_count();
  ownvec<ValType> results = ownvec<ValType>::make_uninitialized(return_count);
  for (size_t i = 0; i < return_count; i++) {
    results[i] = ValType::make(V8ValueTypeToWasm(sig->GetReturn(i)));
  }
  return FuncType::make(std::move(params), std::move(results));
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::sig, and V8ValueTypeToWasm().
Referenced by GetImportExportType().
GetImportExportType()
own<ExternType> wasm::anonymous_namespace{c-api.cc}::GetImportExportType (const i::wasm::WasmModule * module, const i::wasm::ImportExportKindCode kind, const uint32_t index)
Definition at line 188 of file c-api.cc.
                                                          {
  switch (kind) {
    case i::wasm::kExternalFunction: {
      return FunctionSigToFuncType(module->functions[index].sig);
    }
    case i::wasm::kExternalTable: {
      const i::wasm::WasmTable& table = module->tables[index];
      own<ValType> elem = ValType::make(V8ValueTypeToWasm(table.type));
      Limits limits(table.initial_size,
                    table.has_maximum_size
                        ? v8::base::checked_cast<int32_t>(table.maximum_size)
                        : -1);
      return TableType::make(std::move(elem), limits);
    }
    case i::wasm::kExternalMemory: {
      const i::wasm::WasmMemory& memory = module->memories[index];
      Limits limits(memory.initial_pages,
                    memory.has_maximum_pages
                        ? v8::base::checked_cast<int32_t>(memory.maximum_pages)
                        : -1);
      return MemoryType::make(limits);
    }
    case i::wasm::kExternalGlobal: {
      const i::wasm::WasmGlobal& global = module->globals[index];
      own<ValType> content = ValType::make(V8ValueTypeToWasm(global.type));
      Mutability mutability =
          global.mutability ? Mutability::VAR : Mutability::CONST;
      return GlobalType::make(std::move(content), mutability);
    }
    case i::wasm::kExternalTag:
      UNREACHABLE();
  }
}
References FunctionSigToFuncType(), v8::internal::index, v8::internal::wasm::kExternalFunction, v8::internal::wasm::kExternalGlobal, v8::internal::wasm::kExternalMemory, v8::internal::wasm::kExternalTable, v8::internal::wasm::kExternalTag, UNREACHABLE, and V8ValueTypeToWasm().
Referenced by wasm::ExportsImpl().
GetInstance()
own< Instance > wasm::anonymous_namespace{c-api.cc}::GetInstance (StoreImpl * store, i::DirectHandle< i::WasmInstanceObject > instance)
Definition at line 2414 of file c-api.cc.
                                                                       {
  return implement<Instance>::type::make(store, instance);
}
References store().
Referenced by CreateFrameFromInternal(), v8::internal::PerfettoLogger::OnCodeDataSourceStart(), v8::internal::PerfettoLogger::OnCodeDataSourceStop(), v8::internal::PerfettoLogger::RegisterIsolate(), and v8::internal::PerfettoLogger::UnregisterIsolate().
GetNameFromWireBytes()
Name wasm::anonymous_namespace{c-api.cc}::GetNameFromWireBytes (const i::wasm::WireBytesRef & ref, v8::base::Vector< const uint8_t > wire_bytes)
Definition at line 164 of file c-api.cc.
                                                                  {
  DCHECK_LE(ref.offset(), wire_bytes.length());
  DCHECK_LE(ref.end_offset(), wire_bytes.length());
  if (ref.length() == 0) return Name::make();
  Name name = Name::make_uninitialized(ref.length());
  std::memcpy(name.get(), wire_bytes.begin() + ref.offset(), ref.length());
  return name;
}
References v8::base::Vector< T >::begin(), DCHECK_LE, v8::base::Vector< T >::length(), and name.
Referenced by wasm::ExportsImpl().
GetProperException()
i::DirectHandle<i::JSReceiver> wasm::anonymous_namespace{c-api.cc}::GetProperException (i::Isolate * isolate, i::DirectHandle< i::Object > maybe_exception)
Definition at line 1780 of file c-api.cc.
                                                               {
  if (IsJSReceiver(*maybe_exception)) {
    return i::Cast<i::JSReceiver>(maybe_exception);
  }
  if (v8::internal::IsTerminationException(*maybe_exception)) {
    i::DirectHandle<i::String> string =
        isolate->factory()->NewStringFromAsciiChecked("TerminationException");
    return isolate->factory()->NewError(isolate->error_function(), string);
  }
  i::MaybeDirectHandle<i::String> maybe_string =
      i::Object::ToString(isolate, maybe_exception);
  i::DirectHandle<i::String> string = isolate->factory()->empty_string();
  if (!maybe_string.ToHandle(&string)) {
    // If converting the {maybe_exception} to string threw another exception,
    // just give up and leave {string} as the empty string.
    isolate->clear_exception();
  }
  // {NewError} cannot fail when its input is a plain String, so we always
  // get an Error object here.
  return i::Cast<i::JSReceiver>(
      isolate->factory()->NewError(isolate->error_function(), string));
}
References v8::internal::Isolate::clear_exception(), v8::internal::Isolate::factory(), v8::internal::Factory::NewError(), v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), v8::internal::MaybeDirectHandle< T >::ToHandle(), and ToString().
make_func()
auto wasm::anonymous_namespace{c-api.cc}::make_func (Store * store_abs, std::shared_ptr< FuncData > data) -> own<Func>
Definition at line 1570 of file c-api.cc.
                                                                            {
  auto store = impl(store_abs);
  i::Isolate* isolate = store->i_isolate();
  v8::Isolate::Scope isolate_scope(store->isolate());
  i::HandleScope handle_scope(isolate);
  CheckAndHandleInterrupts(isolate);
  i::DirectHandle<i::Managed<FuncData>> embedder_data =
      i::Managed<FuncData>::From(isolate, sizeof(FuncData), data);
  i::wasm::CanonicalTypeIndex sig_index =
      SignatureHelper::Canonicalize(data->type.get());
  const i::wasm::CanonicalSig* sig =
      i::wasm::GetTypeCanonicalizer()->LookupFunctionSignature(sig_index);
  i::DirectHandle<i::WasmCapiFunction> function = i::WasmCapiFunction::New(
      isolate, reinterpret_cast<i::Address>(&FuncData::v8_callback),
      embedder_data, sig_index, sig);
  i::Cast<i::WasmImportData>(
      function->shared()->wasm_capi_function_data()->internal()->implicit_arg())
      ->set_callable(*function);
  auto func = implement<Func>::type::make(store, function);
  return func;
}
References wasm::CheckAndHandleInterrupts(), v8::internal::Managed< CppType >::From(), v8::internal::wasm::GetTypeCanonicalizer(), wasm::impl(), v8::internal::wasm::TypeCanonicalizer::LookupFunctionSignature(), v8::internal::WasmCapiFunction::New(), v8::internal::sig, store(), and wasm::FuncData::v8_callback().
PopArgs()
void wasm::anonymous_namespace{c-api.cc}::PopArgs (const i::wasm::CanonicalSig * sig, vec< Val > & results, i::wasm::CWasmArgumentsPacker * packer, StoreImpl * store)
Definition at line 1728 of file c-api.cc.
                                                                  {
  packer->Reset();
  for (size_t i = 0; i < sig->return_count(); i++) {
    i::wasm::CanonicalValueType type = sig->GetReturn(i);
    switch (type.kind()) {
      case i::wasm::kI32:
        results[i] = Val(packer->Pop<int32_t>());
        break;
      case i::wasm::kI64:
        results[i] = Val(packer->Pop<int64_t>());
        break;
      case i::wasm::kF32:
        results[i] = Val(packer->Pop<float>());
        break;
      case i::wasm::kF64:
        results[i] = Val(packer->Pop<double>());
        break;
      case i::wasm::kRef:
      case i::wasm::kRefNull: {
        // TODO(14034): Make sure this works for all heap types.
        i::Address raw = packer->Pop<i::Address>();
        i::DirectHandle<i::Object> obj(i::Tagged<i::Object>(raw),
                                       store->i_isolate());
        results[i] = Val(V8RefValueToWasm(store, obj));
        break;
      }
      case i::wasm::kS128:
        // TODO(14034): Implement.
        UNIMPLEMENTED();
      case i::wasm::kI8:
      case i::wasm::kI16:
      case i::wasm::kF16:
      case i::wasm::kVoid:
      case i::wasm::kTop:
      case i::wasm::kBottom:
        UNREACHABLE();
    }
  }
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::sig, store(), v8::internal::tracing::type, UNIMPLEMENTED, UNREACHABLE, and V8RefValueToWasm().
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeAtomicOpcode(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeGCOpcode(), and v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeSimdOpcode().
PrepareFunctionData()
void wasm::anonymous_namespace{c-api.cc}::PrepareFunctionData (i::Isolate * isolate, i::DirectHandle< i::WasmExportedFunctionData > function_data, const i::wasm::CanonicalSig * sig)
Definition at line 1671 of file c-api.cc.
                                  {
  // If the data is already populated, return immediately.
  // TODO(saelo): We need to use full pointer comparison here while not all Code
  // objects have migrated into trusted space.
  static_assert(!i::kAllCodeObjectsLiveInTrustedSpace);
  if (!function_data->c_wrapper_code(isolate).SafeEquals(
          *BUILTIN_CODE(isolate, Illegal))) {
    return;
  }
  // Compile wrapper code.
  i::DirectHandle<i::Code> wrapper_code =
      i::compiler::CompileCWasmEntry(isolate, sig);
  function_data->set_c_wrapper_code(*wrapper_code);
  // Compute packed args size.
  function_data->set_packed_args_size(
      i::wasm::CWasmArgumentsPacker::TotalSize(sig));
}
References BUILTIN_CODE, v8::internal::compiler::CompileCWasmEntry(), v8::internal::kAllCodeObjectsLiveInTrustedSpace, and v8::internal::sig.
PushArgs()
void wasm::anonymous_namespace{c-api.cc}::PushArgs (const i::wasm::CanonicalSig * sig, const vec< Val > & args, i::wasm::CWasmArgumentsPacker * packer, StoreImpl * store)
Definition at line 1692 of file c-api.cc.
                                                                   {
  for (size_t i = 0; i < sig->parameter_count(); i++) {
    i::wasm::CanonicalValueType type = sig->GetParam(i);
    switch (type.kind()) {
      case i::wasm::kI32:
        packer->Push(args[i].i32());
        break;
      case i::wasm::kI64:
        packer->Push(args[i].i64());
        break;
      case i::wasm::kF32:
        packer->Push(args[i].f32());
        break;
      case i::wasm::kF64:
        packer->Push(args[i].f64());
        break;
      case i::wasm::kRef:
      case i::wasm::kRefNull:
        // TODO(14034): Make sure this works for all heap types.
        packer->Push((*WasmRefToV8(store->i_isolate(), args[i].ref())).ptr());
        break;
      case i::wasm::kS128:
        // TODO(14034): Implement.
        UNIMPLEMENTED();
      case i::wasm::kI8:
      case i::wasm::kI16:
      case i::wasm::kF16:
      case i::wasm::kVoid:
      case i::wasm::kTop:
      case i::wasm::kBottom:
        UNREACHABLE();
    }
  }
}
References v8::base::args, v8::internal::sig, store(), v8::internal::tracing::type, UNIMPLEMENTED, UNREACHABLE, and WasmRefToV8().
ReadLebU64()
auto wasm::anonymous_namespace{c-api.cc}::ReadLebU64 (const byte_t ** pos) -> uint64_t
Definition at line 102 of file c-api.cc.
                                                {
  uint64_t n = 0;
  uint64_t shift = 0;
  byte_t b;
  do {
    b = **pos;
    (*pos)++;
    n += (b & 0x7f) << shift;
    shift += 7;
  } while ((b & 0x80) != 0);
  return n;
}
V8RefValueToWasm()
own<Ref> wasm::anonymous_namespace{c-api.cc}::V8RefValueToWasm (StoreImpl * store, i::DirectHandle< i::Object > value)
Definition at line 1661 of file c-api.cc.
                                                                          {
  if (IsNull(*value, store->i_isolate())) return nullptr;
  return implement<Ref>::type::make(store, i::Cast<i::JSReceiver>(value));
}
References v8::internal::IsNull(), store(), and v8::internal::value.
Referenced by PopArgs(), and wasm::FuncData::v8_callback().
V8ValueTypeToWasm()
template<typename T >
ValKind wasm::anonymous_namespace{c-api.cc}::V8ValueTypeToWasm (T v8_valtype)
Definition at line 116 of file c-api.cc.
{
  switch (v8_valtype.kind()) {
    case i::wasm::kI32:
      return ValKind::I32;
    case i::wasm::kI64:
      return ValKind::I64;
    case i::wasm::kF32:
      return ValKind::F32;
    case i::wasm::kF64:
      return ValKind::F64;
    case i::wasm::kRef:
    case i::wasm::kRefNull:
      switch (v8_valtype.heap_representation()) {
        case i::wasm::HeapType::kFunc:
          return ValKind::FUNCREF;
        case i::wasm::HeapType::kExtern:
          return ValKind::EXTERNREF;
        default:
          UNREACHABLE();
      }
    default:
      UNREACHABLE();
  }
}
References UNREACHABLE.
Referenced by wasm::anonymous_namespace{c-api.cc}::SignatureHelper::FromV8Sig(), FunctionSigToFuncType(), and GetImportExportType().
WasmRefToV8()
i::DirectHandle<i::Object> wasm::anonymous_namespace{c-api.cc}::WasmRefToV8 (i::Isolate * isolate, const Ref * ref)
Definition at line 1666 of file c-api.cc.
                                                                      {
  if (ref == nullptr) return isolate->factory()->null_value();
  return impl(ref)->v8_object();
}
References v8::internal::Isolate::factory(), and wasm::impl().
Referenced by PushArgs(), and wasm::FuncData::v8_callback().
WasmValKindToV8()
i::wasm::ValueType wasm::anonymous_namespace{c-api.cc}::WasmValKindToV8 (ValKind kind)
Definition at line 144 of file c-api.cc.
                                             {
  switch (kind) {
    case ValKind::I32:
      return i::wasm::kWasmI32;
    case ValKind::I64:
      return i::wasm::kWasmI64;
    case ValKind::F32:
      return i::wasm::kWasmF32;
    case ValKind::F64:
      return i::wasm::kWasmF64;
    case ValKind::FUNCREF:
      return i::wasm::kWasmFuncRef;
    case ValKind::EXTERNREF:
      return i::wasm::kWasmExternRef;
    default:
      // TODO(wasm+): support new value types
      UNREACHABLE();
  }
}
References v8::internal::wasm::kWasmExternRef, v8::internal::wasm::kWasmF32, v8::internal::wasm::kWasmF64, v8::internal::wasm::kWasmFuncRef, v8::internal::wasm::kWasmI32, v8::internal::wasm::kWasmI64, and UNREACHABLE.
Referenced by wasm::anonymous_namespace{c-api.cc}::SignatureHelper::Canonicalize().