v8::internal::anonymous_namespace{preparser.cc} Namespace Reference
Functions
PreParserIdentifier GetIdentifierHelper (Scanner *scanner, const AstRawString *string, AstValueFactory *avf)
Function Documentation
GetIdentifierHelper()
PreParserIdentifier v8::internal::anonymous_namespace{preparser.cc}::GetIdentifierHelper (Scanner * scanner, const AstRawString * string, AstValueFactory * avf)
Definition at line 26 of file preparser.cc.
                                                              {
  // These symbols require slightly different treatement:
  // - regular keywords (async, etc.; treated in 1st switch.)
  // - 'contextual' keywords (and may contain escaped; treated in 2nd switch.)
  // - 'contextual' keywords, but may not be escaped (3rd switch).
  switch (scanner->current_token()) {
    case Token::kAsync:
      return PreParserIdentifier::Async();
    case Token::kPrivateName:
      return PreParserIdentifier::PrivateName();
    default:
      break;
  }
  if (string == avf->constructor_string()) {
    return PreParserIdentifier::Constructor();
  }
  if (scanner->literal_contains_escapes()) {
    return PreParserIdentifier::Default();
  }
  if (string == avf->eval_string()) {
    return PreParserIdentifier::Eval();
  }
  if (string == avf->arguments_string()) {
    return PreParserIdentifier::Arguments();
  }
  return PreParserIdentifier::Default();
}
References v8::internal::PreParserIdentifier::Arguments(), v8::internal::PreParserIdentifier::Async(), v8::internal::PreParserIdentifier::Constructor(), v8::internal::Scanner::current_token(), v8::internal::PreParserIdentifier::Default(), v8::internal::PreParserIdentifier::Eval(), v8::internal::Scanner::literal_contains_escapes(), and v8::internal::PreParserIdentifier::PrivateName().
Referenced by v8::internal::PreParser::GetIdentifier().