v8::platform::anonymous_namespace{default-platform.cc} Namespace Reference
Functions
void PrintStackTrace ()
int GetActualThreadPoolSize (int thread_pool_size)
double DefaultTimeFunction ()
Variables
constexpr int kMaxThreadPoolSize = 16
Function Documentation
DefaultTimeFunction()
double v8::platform::anonymous_namespace{default-platform.cc}::DefaultTimeFunction ()
Definition at line 130 of file default-platform.cc.
                             {
  return base::TimeTicks::Now().ToInternalValue() /
         static_cast<double>(base::Time::kMicrosecondsPerSecond);
}
References v8::base::TimeConstants::kMicrosecondsPerSecond, v8::base::TimeTicks::Now(), and v8::base::time_internal::TimeBase< TimeClass >::ToInternalValue().
Referenced by v8::platform::DefaultPlatform::EnsureBackgroundTaskRunnerInitialized(), v8::platform::DefaultPlatform::GetForegroundTaskRunner(), and v8::platform::DefaultPlatform::MonotonicallyIncreasingTime().
GetActualThreadPoolSize()
int v8::platform::anonymous_namespace{default-platform.cc}::GetActualThreadPoolSize (int thread_pool_size)
Definition at line 35 of file default-platform.cc.
                                                  {
  DCHECK_GE(thread_pool_size, 0);
  if (thread_pool_size < 1) {
    thread_pool_size = base::SysInfo::NumberOfProcessors() - 1;
  }
  return std::max(std::min(thread_pool_size, kMaxThreadPoolSize), 1);
}
References DCHECK_GE, kMaxThreadPoolSize, and v8::base::SysInfo::NumberOfProcessors().
Referenced by v8::platform::NewDefaultPlatform().
PrintStackTrace()
void v8::platform::anonymous_namespace{default-platform.cc}::PrintStackTrace ()
Definition at line 26 of file default-platform.cc.
                       {
  v8::base::debug::StackTrace trace;
  trace.Print();
  // Avoid dumping duplicate stack trace on abort signal.
  v8::base::debug::DisableSignalStackDump();
}
References v8::base::debug::DisableSignalStackDump(), and v8::base::debug::StackTrace::Print().
Referenced by v8::platform::DefaultPlatform::GetStackTracePrinter().
Variable Documentation
kMaxThreadPoolSize
constexpr int v8::platform::anonymous_namespace{default-platform.cc}::kMaxThreadPoolSize = 16 [constexpr]
Definition at line 33 of file default-platform.cc.
Referenced by GetActualThreadPoolSize().