v8::internal::anonymous_namespace{simd.cc} Namespace Reference
Enumerations
enum class SimdKinds { kSSE
, kNeon
, kAVX2
, kNone
 }
enum class ArrayIndexOfIncludesKind { DOUBLE
, OBJECTORSMI
 }
Functions
SimdKinds get_vectorization_kind ()
template<typename T >
uintptr_t slow_search (T *array, uintptr_t array_len, uintptr_t index, T search_element)
template<typename T >
uintptr_t fast_search_noavx (T *array, uintptr_t array_len, uintptr_t index, T search_element)
template<typename T >
uintptr_t fast_search_avx (T *array, uintptr_t array_len, uintptr_t index, T search_element)
template<typename T >
uintptr_t search (T *array, uintptr_t array_len, uintptr_t index, T search_element)
template<ArrayIndexOfIncludesKind kind>
Address ArrayIndexOfIncludes (Address array_start, uintptr_t array_len, uintptr_t from_index, Address search_element)
char NibbleToHex (uint8_t nibble)
void PerformNibbleToHexAndWriteIntoStringOutPut (uint8_t byte, int index, DirectHandle< SeqOneByteString > string_output)
void Uint8ArrayToHexSlow (const char *bytes, size_t length, DirectHandle< SeqOneByteString > string_output)
void AtomicUint8ArrayToHexSlow (const char *bytes, size_t length, DirectHandle< SeqOneByteString > string_output)
uint16_t ByteToHex (uint8_t byte)
V8_ALLOW_UNUSED void HandleRemainingNibbles (const char *bytes, uint8_t *output, size_t length, size_t i)
Maybe< uint8_t > HexToUint8 (base::uc16 hex)
template<typename T >
std::optional< uint8_t > HandleRemainingHexValues (const base::Vector< T > &input_vector, size_t i)
Enumeration Type Documentation
ArrayIndexOfIncludesKind
enum v8::internal::anonymous_namespace{simd.cc}::ArrayIndexOfIncludesKind [strong]
Enumerator
DOUBLE
OBJECTORSMI
Definition at line 358 of file simd.cc.
{ DOUBLE, OBJECTORSMI };
SimdKinds
enum v8::internal::anonymous_namespace{simd.cc}::SimdKinds [strong]
Enumerator
kSSE
kNeon
kAVX2
kNone
Definition at line 40 of file simd.cc.
{ kSSE, kNeon, kAVX2, kNone };
Function Documentation
ArrayIndexOfIncludes()
template<ArrayIndexOfIncludesKind kind>
Address v8::internal::anonymous_namespace{simd.cc}::ArrayIndexOfIncludes (Address array_start, uintptr_t array_len, uintptr_t from_index, Address search_element)
Definition at line 372 of file simd.cc.
                                                                           {
  if (array_len == 0) {
    return Smi::FromInt(-1).ptr();
  }
  if constexpr (kind == ArrayIndexOfIncludesKind::DOUBLE) {
    Tagged<FixedDoubleArray> fixed_array =
        Cast<FixedDoubleArray>(Tagged<Object>(array_start));
    UnalignedDoubleMember* unaligned_array = fixed_array->begin();
    // TODO(leszeks): This reinterpret cast is a bit sketchy because the values
    // are unaligned doubles. Ideally we'd fix the search method to support
    // UnalignedDoubleMember.
    static_assert(sizeof(UnalignedDoubleMember) == sizeof(double));
    double* array = reinterpret_cast<double*>(unaligned_array);
    double search_num;
    if (IsSmi(Tagged<Object>(search_element))) {
      search_num = Tagged<Object>(search_element).ToSmi().value();
    } else {
      DCHECK(IsHeapNumber(Tagged<Object>(search_element)));
      search_num = Cast<HeapNumber>(Tagged<Object>(search_element))->value();
    }
    DCHECK(!std::isnan(search_num));
    if (reinterpret_cast<uintptr_t>(array) % sizeof(double) != 0) {
      // Slow scalar search for unaligned double array.
      for (; from_index < array_len; from_index++) {
        if (fixed_array->is_the_hole(static_cast<int>(from_index))) {
          // |search_num| cannot be NaN, so there is no need to check against
          // holes.
          continue;
        }
        if (fixed_array->get_scalar(static_cast<int>(from_index)) ==
            search_num) {
          return from_index;
        }
      }
      return Smi::FromInt(-1).ptr();
    }
    return search<double>(array, array_len, from_index, search_num);
  }
  if constexpr (kind == ArrayIndexOfIncludesKind::OBJECTORSMI) {
    Tagged<FixedArray> fixed_array =
        Cast<FixedArray>(Tagged<Object>(array_start));
    Tagged_t* array = static_cast<Tagged_t*>(
        fixed_array->RawFieldOfFirstElement().ToVoidPtr());
    DCHECK(!IsHeapNumber(Tagged<Object>(search_element)));
    DCHECK(!IsBigInt(Tagged<Object>(search_element)));
    DCHECK(!IsString(Tagged<Object>(search_element)));
    return search<Tagged_t>(array, array_len, from_index,
                            static_cast<Tagged_t>(search_element));
  }
}
References v8::internal::DCHECK(), v8::internal::Smi::FromInt(), v8::internal::IsSmi(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), and v8::internal::Tagged< Object >.
AtomicUint8ArrayToHexSlow()
void v8::internal::anonymous_namespace{simd.cc}::AtomicUint8ArrayToHexSlow (const char * bytes, size_t length, DirectHandle< SeqOneByteString > string_output)
Definition at line 480 of file simd.cc.
                                                                             {
  int index = 0;
  // std::atomic_ref<T> must not have a const T, see
  // https://cplusplus.github.io/LWG/issue3508
  // we instead provide a mutable input, which is ok since we are only reading
  // from it.
  char* mutable_bytes = const_cast<char*>(bytes);
  for (size_t i = 0; i < length; i++) {
    uint8_t byte =
        std::atomic_ref<char>(mutable_bytes[i]).load(std::memory_order_relaxed);
    PerformNibbleToHexAndWriteIntoStringOutPut(byte, index, string_output);
    index += 2;
  }
}
References v8::internal::index, v8::internal::length, and PerformNibbleToHexAndWriteIntoStringOutPut().
Referenced by v8::internal::Uint8ArrayToHex().
ByteToHex()
uint16_t v8::internal::anonymous_namespace{simd.cc}::ByteToHex (uint8_t byte) [inline]
Definition at line 496 of file simd.cc.
                                        {
  const uint16_t correction = (('a' - '0' - 10) << 8) + ('a' - '0' - 10);
#if V8_TARGET_BIG_ENDIAN
  const uint16_t nibbles = (byte << 4) + (byte & 0xF);
#else
  const uint16_t nibbles = ((byte & 0xF) << 8) + (byte >> 4);
#endif
  const uint16_t chars = nibbles + 0x3030;
  const uint16_t temp = 0x8080 - 0x0A0A + nibbles;
  const uint16_t msb = temp & 0x8080;
  const uint16_t mask = msb - (msb >> 7);
  return chars + (mask & correction);
}
Referenced by HandleRemainingNibbles().
fast_search_avx()
template<typename T >
uintptr_t v8::internal::anonymous_namespace{simd.cc}::fast_search_avx (T * array, uintptr_t array_len, uintptr_t index, T search_element)
Definition at line 338 of file simd.cc.
                                            {
  UNREACHABLE();
}
References v8::internal::UNREACHABLE().
Referenced by search().
fast_search_noavx()
template<typename T >
uintptr_t v8::internal::anonymous_namespace{simd.cc}::fast_search_noavx (T * array, uintptr_t array_len, uintptr_t index, T search_element) [inline]
Definition at line 174 of file simd.cc.
                                                                      {
  static constexpr bool is_uint32 =
      sizeof(T) == sizeof(uint32_t) && std::is_integral_v<T>;
  static constexpr bool is_uint64 =
      sizeof(T) == sizeof(uint64_t) && std::is_integral_v<T>;
  static constexpr bool is_double =
      sizeof(T) == sizeof(double) && std::is_floating_point_v<T>;
  static_assert(is_uint32 || is_uint64 || is_double);
#if !(defined(__SSE3__) || defined(NEON64))
  // No SIMD available.
  return slow_search(array, array_len, index, search_element);
#endif
#ifdef __SSE3__
  const int target_align = 16;
#elif defined(NEON64)
  const int target_align = 16;
#else
  const int target_align = 4;
  UNREACHABLE();
#endif
  // Scalar loop to reach desired alignment
  for (;
       index < array_len &&
       (reinterpret_cast<std::uintptr_t>(&(array[index])) % target_align) != 0;
       index++) {
    if (array[index] == search_element) {
      return index;
    }
  }
  // Inserting one of the vectorized loop
#ifdef __SSE3__
  if constexpr (is_uint32) {
#define MOVEMASK(x) _mm_movemask_ps(_mm_castsi128_ps(x))
#define EXTRACT(x) base::bits::CountTrailingZeros32(x)
    VECTORIZED_LOOP_x86(__m128i, __m128i, _mm_set1_epi32, _mm_cmpeq_epi32,
                        MOVEMASK, EXTRACT)
#undef MOVEMASK
#undef EXTRACT
  } else if constexpr (is_uint64) {
#define MOVEMASK(x) _mm_movemask_ps(_mm_castsi128_ps(x))
// _mm_cmpeq_epi64_nosse4_2() might produce only the following non-zero
// patterns:
// 0b0011 -> 0 (the first value matches),
// 0b1100 -> 1 (the second value matches),
// 0b1111 -> 0 (both first and second value match).
// Thus it's enough to check only the least significant bit.
#define EXTRACT(x) (((x) & 1) ? 0 : 1)
    VECTORIZED_LOOP_x86(__m128i, __m128i, _mm_set1_epi64x,
                        _mm_cmpeq_epi64_nosse4_2, MOVEMASK, EXTRACT)
#undef MOVEMASK
#undef EXTRACT
  } else if constexpr (is_double) {
#define EXTRACT(x) base::bits::CountTrailingZeros32(x)
    VECTORIZED_LOOP_x86(__m128d, __m128d, _mm_set1_pd, _mm_cmpeq_pd,
                        _mm_movemask_pd, EXTRACT)
#undef EXTRACT
  }
#elif defined(NEON64)
  if constexpr (is_uint32) {
    VECTORIZED_LOOP_Neon(uint32x4_t, uint32x4_t, vdupq_n_u32, vceqq_u32,
                         vmaxvq_u32)
  } else if constexpr (is_uint64) {
    VECTORIZED_LOOP_Neon(uint64x2_t, uint64x2_t, vdupq_n_u64, vceqq_u64,
                         reinterpret_vmaxvq_u64)
  } else if constexpr (is_double) {
    VECTORIZED_LOOP_Neon(float64x2_t, uint64x2_t, vdupq_n_f64, vceqq_f64,
                         reinterpret_vmaxvq_u64)
  }
#else
  UNREACHABLE();
#endif
  // The vectorized loop stops when there are not enough items left in the array
  // to fill a vector register. The slow_search function will take care of
  // iterating through the few remaining items.
  return slow_search(array, array_len, index, search_element);
}
References v8::internal::index, slow_search(), T, v8::internal::UNREACHABLE(), VECTORIZED_LOOP_Neon, and VECTORIZED_LOOP_x86.
Referenced by search().
get_vectorization_kind()
SimdKinds v8::internal::anonymous_namespace{simd.cc}::get_vectorization_kind () [inline]
Definition at line 42 of file simd.cc.
                                          {
#ifdef __SSE3__
#if defined(V8_TARGET_ARCH_IA32) || defined(V8_TARGET_ARCH_X64)
  bool has_avx2 = CpuFeatures::IsSupported(AVX2);
#else
  bool has_avx2 = false;
#endif
  if (has_avx2) {
    return SimdKinds::kAVX2;
  } else {
    // No need for a runtime check since we do not support x86/x64 CPUs without
    // SSE3.
    return SimdKinds::kSSE;
  }
#elif defined(NEON64)
  // No need for a runtime check since all Arm64 CPUs have Neon.
  return SimdKinds::kNeon;
#else
  return SimdKinds::kNone;
#endif
}
References v8::internal::CpuFeatures::IsSupported().
Referenced by v8::internal::ArrayBufferFromHex(), search(), and v8::internal::Uint8ArrayToHex().
HandleRemainingHexValues()
template<typename T >
std::optional<uint8_t> v8::internal::anonymous_namespace{simd.cc}::HandleRemainingHexValues (const base::Vector< T > & input_vector, size_t i)
Definition at line 671 of file simd.cc.
                                                 {
  T higher = input_vector[i];
  T lower = input_vector[i + 1];
  uint8_t result_high = 0;
  Maybe<uint8_t> maybe_result_high = HexToUint8(higher);
  if (!maybe_result_high.To(&result_high)) {
    return {};
  }
  uint8_t result_low = 0;
  Maybe<uint8_t> maybe_result_low = HexToUint8(lower);
  if (!maybe_result_low.To(&result_low)) {
    return {};
  }
  result_high <<= 4;
  uint8_t result = result_high + result_low;
  return result;
}
References HexToUint8(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::base::internal::result, and v8::Maybe< T >::To().
Referenced by v8::internal::ArrayBufferFromHex().
HandleRemainingNibbles()
V8_ALLOW_UNUSED void v8::internal::anonymous_namespace{simd.cc}::HandleRemainingNibbles (const char * bytes, uint8_t * output, size_t length, size_t i)
Definition at line 510 of file simd.cc.
                                                                     {
  uint16_t* output_pairs = reinterpret_cast<uint16_t*>(output) + i;
  bytes += i;
  size_t rest = length & 0x7;
  for (i = 0; i < rest; i++) {
    *(output_pairs++) = ByteToHex(*bytes++);
  }
}
References ByteToHex(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::length.
HexToUint8()
Maybe<uint8_t> v8::internal::anonymous_namespace{simd.cc}::HexToUint8 (base::uc16 hex)
Definition at line 658 of file simd.cc.
                                        {
  if (hex >= '0' && hex <= '9') {
    return Just<uint8_t>(hex - '0');
  } else if (hex >= 'a' && hex <= 'f') {
    return Just<uint8_t>(hex - 'a' + 10);
  } else if (hex >= 'A' && hex <= 'F') {
    return Just<uint8_t>(hex - 'A' + 10);
  }
  return Nothing<uint8_t>();
}
Referenced by HandleRemainingHexValues().
NibbleToHex()
char v8::internal::anonymous_namespace{simd.cc}::NibbleToHex (uint8_t nibble)
Definition at line 452 of file simd.cc.
                                 {
  const char correction = 'a' - '0' - 10;
  const char c = nibble + '0';
  uint8_t temp = 128 - 10 + nibble;
  uint8_t msb = temp & 0x80;
  uint8_t mask = msb - (msb >> 7);
  return c + (mask & correction);
}
Referenced by PerformNibbleToHexAndWriteIntoStringOutPut().
PerformNibbleToHexAndWriteIntoStringOutPut()
void v8::internal::anonymous_namespace{simd.cc}::PerformNibbleToHexAndWriteIntoStringOutPut (uint8_t byte, int index, DirectHandle< SeqOneByteString > string_output)
Definition at line 461 of file simd.cc.
                                                                           {
  uint8_t high = byte >> 4;
  uint8_t low = byte & 0x0F;
  string_output->SeqOneByteStringSet(index++, NibbleToHex(high));
  string_output->SeqOneByteStringSet(index, NibbleToHex(low));
}
References v8::internal::index, and NibbleToHex().
Referenced by AtomicUint8ArrayToHexSlow(), and Uint8ArrayToHexSlow().
search()
template<typename T >
uintptr_t v8::internal::anonymous_namespace{simd.cc}::search (T * array, uintptr_t array_len, uintptr_t index, T search_element) [inline]
Definition at line 349 of file simd.cc.
                                          {
  if (get_vectorization_kind() == SimdKinds::kAVX2) {
    return fast_search_avx(array, array_len, index, search_element);
  } else {
    return fast_search_noavx(array, array_len, index, search_element);
  }
}
References fast_search_avx(), fast_search_noavx(), get_vectorization_kind(), and v8::internal::index.
Referenced by v8::internal::anonymous_namespace{regexp.cc}::AtomExecRawImpl(), v8::internal::StringSearch< PatternChar, SubjectChar >::BoyerMooreHorspoolSearch(), v8::internal::StringSearch< PatternChar, SubjectChar >::BoyerMooreSearch(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin_StringIndexOf(), v8::internal::compiler::anonymous_namespace{jump-threading.cc}::GapJumpRecord::CanForwardGapJump(), v8::internal::FindStringIndices(), v8::internal::wasm::TurboshaftGraphBuildingInterface::GetStringIndexOf(), v8::internal::wasm::TurboshaftGraphBuildingInterface::HandleWellKnownImport(), v8::internal::String::IndexOf(), v8::internal::StringSearch< PatternChar, SubjectChar >::InitialSearch(), v8::internal::anonymous_namespace{runtime-regexp.cc}::IsContainFlagImpl(), v8::internal::String::LastIndexOf(), v8::internal::StringSearch< PatternChar, SubjectChar >::LinearSearch(), v8::internal::JSNumberFormat::MinimumIntegerDigitsFromSkeleton(), v8::internal::compiler::JSCallReducer::ReduceRegExpPrototypeTest(), v8::internal::anonymous_namespace{runtime-regexp.cc}::RegExpMatchGlobalAtom_Generic(), v8::internal::RUNTIME_FUNCTION(), v8::internal::SearchString(), v8::internal::StringSearch< PatternChar, SubjectChar >::SingleCharSearch(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StringIndexOf(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::StringIndexOf(), v8::internal::StringReplaceOneCharWithString(), v8::internal::TF_BUILTIN(), v8::internal::anonymous_namespace{uri.cc}::UnescapePrivate(), and v8::internal::anonymous_namespace{js-number-format.cc}::UnitFromSkeleton().
slow_search()
template<typename T >
uintptr_t v8::internal::anonymous_namespace{simd.cc}::slow_search (T * array, uintptr_t array_len, uintptr_t index, T search_element) [inline]
Definition at line 68 of file simd.cc.
                                               {
  for (; index < array_len; index++) {
    if (array[index] == search_element) {
      return index;
    }
  }
  return -1;
}
References v8::internal::index.
Referenced by fast_search_noavx().
Uint8ArrayToHexSlow()
void v8::internal::anonymous_namespace{simd.cc}::Uint8ArrayToHexSlow (const char * bytes, size_t length, DirectHandle< SeqOneByteString > string_output)
Definition at line 470 of file simd.cc.
                                                                       {
  int index = 0;
  for (size_t i = 0; i < length; i++) {
    uint8_t byte = bytes[i];
    PerformNibbleToHexAndWriteIntoStringOutPut(byte, index, string_output);
    index += 2;
  }
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::length, and PerformNibbleToHexAndWriteIntoStringOutPut().
Referenced by v8::internal::Uint8ArrayToHex().