v8::internal::torque::ls Namespace Reference
Namespaces
 anonymous_namespace{json.cc}
 anonymous_namespace{message-handler.cc}
Classes
class JsonGrammar
struct JsonParserResult
struct JsonValue
class BaseJsonAccessor
class Message
class NestedJsonAccessor
class ResponseError
class InitializeParams
class FileListParams
class FileSystemWatcher
class DidChangeWatchedFilesRegistrationOptions
class FileEvent
class DidChangeWatchedFilesParams
class SaveOptions
class TextDocumentSyncOptions
class ServerCapabilities
class InitializeResult
class Registration
class RegistrationParams
class JsonPosition
class Range
class Location
class TextDocumentIdentifier
class TextDocumentPositionParams
class Diagnostic
class PublishDiagnosticsParams
class DocumentSymbolParams
class SymbolInformation
class Request
class Response
class ResponseArrayResult
Typedefs
using JsonMember = std::pair< std::string, JsonValue >
using JsonObject = std::map< std::string, JsonValue >
using JsonArray = std::vector< JsonValue >
using MessageWriter = std::function< void(JsonValue)>
using InitializeRequest = Request< InitializeParams >
using RegistrationRequest = Request< RegistrationParams >
using TorqueFileListNotification = Request< FileListParams >
using GotoDefinitionRequest = Request< TextDocumentPositionParams >
using DidChangeWatchedFilesNotification = Request< DidChangeWatchedFilesParams >
using PublishDiagnosticsNotification = Request< PublishDiagnosticsParams >
using DocumentSymbolRequest = Request< DocumentSymbolParams >
using InitializeResponse = Response< InitializeResult >
using GotoDefinitionResponse = Response< Location >
using DocumentSymbolResponse = ResponseArrayResult< SymbolInformation >
Enumerations
enum SymbolKind {
kFile = 1
, kNamespace = 3
, kClass = 5
, kMethod = 6
,
kProperty = 7
, kField = 8
, kConstructor = 9
, kFunction = 12
,
kVariable = 13
, kConstant = 14
, kStruct = 23
 }
Functions
template<bool value>
std::optional< ParseResult > MakeBoolLiteral (ParseResultIterator *child_results)
std::optional< ParseResult > MakeNullLiteral (ParseResultIterator *child_results)
std::optional< ParseResult > MakeNumberLiteral (ParseResultIterator *child_results)
std::optional< ParseResult > MakeStringLiteral (ParseResultIterator *child_results)
std::optional< ParseResult > MakeArray (ParseResultIterator *child_results)
std::optional< ParseResult > MakeMember (ParseResultIterator *child_results)
std::optional< ParseResult > MakeObject (ParseResultIterator *child_results)
JsonParserResult ParseJson (const std::string &input)
std::string SerializeToString (const JsonValue &value)
JsonValue ReadMessage ()
void WriteMessage (JsonValue message)
void CompilationFinished (TorqueCompilerResult result, MessageWriter writer)
void HandleMessage (JsonValue raw_message, MessageWriter writer)
int WrappedMain (int argc, const char **argv)
Variables
static const char kContentLength [] = `Content-Length: `
static const size_t kContentLengthSize = sizeof(kContentLength) - 1
constexpr const char * kProtocolLineEnding = `\r\n\r\n`
Typedef Documentation
DidChangeWatchedFilesNotification
using v8::internal::torque::ls::DidChangeWatchedFilesNotification = typedef Request<DidChangeWatchedFilesParams>
Definition at line 337 of file message.h.
DocumentSymbolRequest
using v8::internal::torque::ls::DocumentSymbolRequest = typedef Request<DocumentSymbolParams>
Definition at line 339 of file message.h.
DocumentSymbolResponse
using v8::internal::torque::ls::DocumentSymbolResponse = typedef ResponseArrayResult<SymbolInformation>
Definition at line 365 of file message.h.
GotoDefinitionRequest
using v8::internal::torque::ls::GotoDefinitionRequest = typedef Request<TextDocumentPositionParams>
Definition at line 336 of file message.h.
GotoDefinitionResponse
using v8::internal::torque::ls::GotoDefinitionResponse = typedef Response<Location>
Definition at line 352 of file message.h.
InitializeRequest
using v8::internal::torque::ls::InitializeRequest = typedef Request<InitializeParams>
Definition at line 333 of file message.h.
InitializeResponse
using v8::internal::torque::ls::InitializeResponse = typedef Response<InitializeResult>
Definition at line 351 of file message.h.
JsonArray
using v8::internal::torque::ls::JsonArray = typedef std::vector<JsonValue>
Definition at line 23 of file json.h.
JsonMember
using v8::internal::torque::ls::JsonMember = typedef std::pair<std::string, JsonValue>
Definition at line 35 of file json-parser.cc.
JsonObject
using v8::internal::torque::ls::JsonObject = typedef std::map<std::string, JsonValue>
Definition at line 22 of file json.h.
MessageWriter
using v8::internal::torque::ls::MessageWriter = typedef std::function<void(JsonValue)>
Definition at line 27 of file message-handler.h.
PublishDiagnosticsNotification
using v8::internal::torque::ls::PublishDiagnosticsNotification = typedef Request<PublishDiagnosticsParams>
Definition at line 338 of file message.h.
RegistrationRequest
using v8::internal::torque::ls::RegistrationRequest = typedef Request<RegistrationParams>
Definition at line 334 of file message.h.
TorqueFileListNotification
using v8::internal::torque::ls::TorqueFileListNotification = typedef Request<FileListParams>
Definition at line 335 of file message.h.
Enumeration Type Documentation
SymbolKind
enum v8::internal::torque::ls::SymbolKind
Enumerator
kFile
kNamespace
kClass
kMethod
kProperty
kField
kConstructor
kFunction
kVariable
kConstant
kStruct
Definition at line 292 of file message.h.
                {
  kFile = 1,
  kNamespace = 3,
  kClass = 5,
  kMethod = 6,
  kProperty = 7,
  kField = 8,
  kConstructor = 9,
  kFunction = 12,
  kVariable = 13,
  kConstant = 14,
  kStruct = 23,
};
Function Documentation
CompilationFinished()
V8_EXPORT_PRIVATE void v8::internal::torque::ls::CompilationFinished (TorqueCompilerResult result, MessageWriter writer)
Definition at line 180 of file message-handler.cc.
                                                                            {
  LanguageServerData::Get() = std::move(result.language_server_data);
  SourceFileMap::Get() = *result.source_file_map;
  SendCompilationDiagnostics(result, writer);
}
References v8::base::ContextualVariable< Derived, VarType >::Get(), v8::base::internal::result, and v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::SendCompilationDiagnostics().
Referenced by v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::RecompileTorque().
HandleMessage()
V8_EXPORT_PRIVATE void v8::internal::torque::ls::HandleMessage (JsonValue raw_message, MessageWriter writer)
Definition at line 349 of file message-handler.cc.
                                                                {
  Request<bool> request(std::move(raw_message));
  // We ignore responses for now. They are matched to requests
  // by id and don't have a method set.
  // TODO(szuend): Implement proper response handling for requests
  // that originate from the server.
  if (!request.has_method()) {
    Logger::Log("[info] Unhandled response with id ", request.id(), "\n\n");
    return;
  }
  const std::string method = request.method();
  if (method == "initialize") {
    HandleInitializeRequest(
        InitializeRequest(std::move(request.GetJsonValue())), writer);
  } else if (method == "initialized") {
    HandleInitializedNotification(writer);
  } else if (method == "torque/fileList") {
    HandleTorqueFileListNotification(
        TorqueFileListNotification(std::move(request.GetJsonValue())), writer);
  } else if (method == "textDocument/definition") {
    HandleGotoDefinitionRequest(
        GotoDefinitionRequest(std::move(request.GetJsonValue())), writer);
  } else if (method == "workspace/didChangeWatchedFiles") {
    HandleChangeWatchedFilesNotification(
        DidChangeWatchedFilesNotification(std::move(request.GetJsonValue())),
        writer);
  } else if (method == "textDocument/documentSymbol") {
    HandleDocumentSymbolRequest(
        DocumentSymbolRequest(std::move(request.GetJsonValue())), writer);
  } else {
    Logger::Log("[error] Message of type ", method, " is not handled!\n\n");
  }
}
References v8::internal::torque::ls::Message::GetJsonValue(), v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::HandleChangeWatchedFilesNotification(), v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::HandleDocumentSymbolRequest(), v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::HandleGotoDefinitionRequest(), v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::HandleInitializedNotification(), v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::HandleInitializeRequest(), v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::HandleTorqueFileListNotification(), v8::internal::torque::Logger::Log(), and v8::internal::string.
Referenced by WrappedMain().
MakeArray()
std::optional<ParseResult> v8::internal::torque::ls::MakeArray (ParseResultIterator * child_results)
Definition at line 61 of file json-parser.cc.
                                                                       {
  JsonArray array = child_results->NextAs<JsonArray>();
  return ParseResult{JsonValue::From(std::move(array))};
}
References v8::internal::torque::ls::JsonValue::From(), and v8::internal::torque::ParseResultIterator::NextAs().
MakeBoolLiteral()
template<bool value>
std::optional<ParseResult> v8::internal::torque::ls::MakeBoolLiteral (ParseResultIterator * child_results)
Definition at line 38 of file json-parser.cc.
                                                                             {
  return ParseResult{JsonValue::From(value)};
}
References v8::internal::torque::ls::JsonValue::From(), and v8::internal::value.
MakeMember()
std::optional<ParseResult> v8::internal::torque::ls::MakeMember (ParseResultIterator * child_results)
Definition at line 66 of file json-parser.cc.
                                                                        {
  JsonMember result;
  std::string key = child_results->NextAs<std::string>();
  result.first = StringLiteralUnquote(key);
  result.second = child_results->NextAs<JsonValue>();
  return ParseResult{std::move(result)};
}
References v8::internal::key, v8::internal::torque::ParseResultIterator::NextAs(), v8::base::internal::result, v8::internal::string, and v8::internal::torque::StringLiteralUnquote().
MakeNullLiteral()
std::optional<ParseResult> v8::internal::torque::ls::MakeNullLiteral (ParseResultIterator * child_results)
Definition at line 42 of file json-parser.cc.
                                                                             {
  JsonValue result;
  result.tag = JsonValue::IS_NULL;
  return ParseResult{std::move(result)};
}
References v8::internal::torque::ls::JsonValue::IS_NULL, and v8::base::internal::result.
MakeNumberLiteral()
std::optional<ParseResult> v8::internal::torque::ls::MakeNumberLiteral (ParseResultIterator * child_results)
Definition at line 48 of file json-parser.cc.
                                        {
  auto number = child_results->NextAs<std::string>();
  double d = std::stod(number);
  return ParseResult{JsonValue::From(d)};
}
References v8::internal::torque::ls::JsonValue::From(), v8::internal::torque::ParseResultIterator::NextAs(), and v8::internal::string.
MakeObject()
std::optional<ParseResult> v8::internal::torque::ls::MakeObject (ParseResultIterator * child_results)
Definition at line 74 of file json-parser.cc.
                                                                        {
  using MemberList = std::vector<JsonMember>;
  MemberList members = child_results->NextAs<MemberList>();
  JsonObject object;
  for (auto& member : members) object.insert(std::move(member));
  return ParseResult{JsonValue::From(std::move(object))};
}
References v8::internal::torque::ls::JsonValue::From(), and v8::internal::torque::ParseResultIterator::NextAs().
MakeStringLiteral()
std::optional<ParseResult> v8::internal::torque::ls::MakeStringLiteral (ParseResultIterator * child_results)
Definition at line 55 of file json-parser.cc.
                                        {
  std::string literal = child_results->NextAs<std::string>();
  return ParseResult{JsonValue::From(StringLiteralUnquote(literal))};
}
References v8::internal::torque::ls::JsonValue::From(), v8::internal::torque::ParseResultIterator::NextAs(), v8::internal::string, and v8::internal::torque::StringLiteralUnquote().
ParseJson()
V8_EXPORT_PRIVATE JsonParserResult v8::internal::torque::ls::ParseJson (const std::string & input)
Definition at line 181 of file json-parser.cc.
                                                   {
  // Torque needs a CurrentSourceFile scope during parsing.
  // As JSON lives in memory only, an unknown file scope is created.
  SourceFileMap::Scope source_map_scope("");
  TorqueMessages::Scope messages_scope;
  CurrentSourceFile::Scope unkown_file(SourceFileMap::AddSource("<json>"));
  JsonParserResult result;
  try {
    result.value = (*JsonGrammar().Parse(input)).Cast<JsonValue>();
  } catch (TorqueAbortCompilation&) {
    CHECK(!TorqueMessages::Get().empty());
    result.error = TorqueMessages::Get().front();
  }
  return result;
}
References v8::internal::torque::SourceFileMap::AddSource(), CHECK, v8::internal::compiler::turboshaft::Get(), v8::internal::torque::Grammar::Parse(), and v8::base::internal::result.
Referenced by ReadMessage().
ReadMessage()
JsonValue v8::internal::torque::ls::ReadMessage ()
Definition at line 34 of file message-handler.cc.
                        {
  std::string line;
  std::getline(std::cin, line);
  if (line.rfind(kContentLength) != 0) {
    // Invalid message, we just crash.
    Logger::Log("[fatal] Did not find Content-Length ...\n");
    v8::base::OS::Abort();
  }
  const int content_length = std::atoi(line.substr(kContentLengthSize).c_str());
  std::getline(std::cin, line);
  std::string content(content_length, ' ');
  std::cin.read(&content[0], content_length);
  Logger::Log("[incoming] ", content, "\n\n");
  return ParseJson(content).value;
}
References v8::base::OS::Abort(), kContentLength, kContentLengthSize, v8::internal::torque::Logger::Log(), ParseJson(), v8::internal::string, and v8::internal::torque::ls::JsonParserResult::value.
Referenced by WrappedMain().
SerializeToString()
std::string v8::internal::torque::ls::SerializeToString (const JsonValue & value)
Definition at line 60 of file json.cc.
                                                    {
  std::stringstream result;
  SerializeToString(result, value);
  return result.str();
}
References v8::base::internal::result, and v8::internal::value.
Referenced by v8::internal::torque::ls::anonymous_namespace{json.cc}::SerializeToString(), and WriteMessage().
WrappedMain()
int v8::internal::torque::ls::WrappedMain (int argc, const char ** argv)
Definition at line 20 of file torque-language-server.cc.
                                             {
  Logger::Scope log_scope;
  TorqueFileList::Scope files_scope;
  LanguageServerData::Scope server_data_scope;
  SourceFileMap::Scope source_file_map_scope("");
  DiagnosticsFiles::Scope diagnostics_files_scope;
  for (int i = 1; i < argc; ++i) {
    if (!strcmp("-l", argv[i])) {
      Logger::Enable(argv[++i]);
      break;
    }
  }
  while (true) {
    JsonValue message = ReadMessage();
    // TODO(szuend): We should probably offload the actual message handling
    // (even the parsing) to a background thread, so we can
    // keep receiving messages. We might also receive
    // $/cancelRequests or contet updates, that require restarts.
    HandleMessage(std::move(message), &WriteMessage);
  }
}
References v8::internal::torque::Logger::Enable(), HandleMessage(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, ReadMessage(), and WriteMessage().
Referenced by main().
WriteMessage()
void v8::internal::torque::ls::WriteMessage (JsonValue message)
Definition at line 54 of file message-handler.cc.
                                     {
  std::string content = SerializeToString(message);
  Logger::Log("[outgoing] ", content, "\n\n");
  std::cout << kContentLength << content.size() << kProtocolLineEnding;
  std::cout << content << std::flush;
}
References kContentLength, kProtocolLineEnding, v8::internal::torque::Logger::Log(), SerializeToString(), and v8::internal::string.
Referenced by WrappedMain().
Variable Documentation
kContentLength
const char v8::internal::torque::ls::kContentLength[] = `Content-Length: ` [static]
Definition at line 24 of file message-handler.cc.
Referenced by ReadMessage(), and WriteMessage().
kContentLengthSize
const size_t v8::internal::torque::ls::kContentLengthSize = sizeof(kContentLength) - 1 [static]
Definition at line 25 of file message-handler.cc.
Referenced by ReadMessage().
kProtocolLineEnding
constexpr const char* v8::internal::torque::ls::kProtocolLineEnding = `\r\n\r\n` [constexpr]
Definition at line 31 of file message-handler.cc.
Referenced by WriteMessage().