v8::internal::anonymous_namespace{runtime-debug.cc} Namespace Reference
Functions
template<class IteratorType >
static DirectHandle< ArrayList > AddIteratorInternalProperties (Isolate *isolate, DirectHandle< ArrayList > result, DirectHandle< IteratorType > iterator)
int ScriptLinePosition (Isolate *isolate, DirectHandle< Script > script, int line)
int ScriptLinePositionWithOffset (Isolate *isolate, DirectHandle< Script > script, int line, int offset)
DirectHandle< Object > GetJSPositionInfo (DirectHandle< Script > script, int position, Script::OffsetFlag offset_flag, Isolate *isolate)
DirectHandle< Object > ScriptLocationFromLine (Isolate *isolate, DirectHandle< Script > script, DirectHandle< Object > opt_line, DirectHandle< Object > opt_column, int32_t offset)
bool GetScriptById (Isolate *isolate, int needle, DirectHandle< Script > *result)
DirectHandle< JSObject > MakeRangeObject (Isolate *isolate, const CoverageBlock &range)
Function Documentation
AddIteratorInternalProperties()
template<class IteratorType >
static DirectHandle<ArrayList> v8::internal::anonymous_namespace{runtime-debug.cc}::AddIteratorInternalProperties (Isolate * isolate, DirectHandle< ArrayList > result, DirectHandle< IteratorType > iterator) [static]
Definition at line 164 of file runtime-debug.cc.
                                         {
  const char* kind = nullptr;
  switch (iterator->map()->instance_type()) {
    case JS_MAP_KEY_ITERATOR_TYPE:
      kind = "keys";
      break;
    case JS_MAP_KEY_VALUE_ITERATOR_TYPE:
    case JS_SET_KEY_VALUE_ITERATOR_TYPE:
      kind = "entries";
      break;
    case JS_MAP_VALUE_ITERATOR_TYPE:
    case JS_SET_VALUE_ITERATOR_TYPE:
      kind = "values";
      break;
    default:
      UNREACHABLE();
  }
  result = ArrayList::Add(
      isolate, result,
      isolate->factory()->NewStringFromAsciiChecked("[[IteratorHasMore]]"),
      isolate->factory()->ToBoolean(iterator->HasMore()));
  result = ArrayList::Add(
      isolate, result,
      isolate->factory()->NewStringFromAsciiChecked("[[IteratorIndex]]"),
      direct_handle(iterator->index(), isolate));
  result = ArrayList::Add(
      isolate, result,
      isolate->factory()->NewStringFromAsciiChecked("[[IteratorKind]]"),
      isolate->factory()->NewStringFromAsciiChecked(kind));
  return result;
}
References v8::internal::ArrayList::Add(), v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), v8::base::internal::result, v8::internal::FactoryBase< Impl >::ToBoolean(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::Runtime::GetInternalProperties().
GetJSPositionInfo()
DirectHandle<Object> v8::internal::anonymous_namespace{runtime-debug.cc}::GetJSPositionInfo (DirectHandle< Script > script, int position, Script::OffsetFlag offset_flag, Isolate * isolate)
Definition at line 594 of file runtime-debug.cc.
                                                         {
  Script::PositionInfo info;
  if (!Script::GetPositionInfo(script, position, &info, offset_flag)) {
    return isolate->factory()->null_value();
  }
#if V8_ENABLE_WEBASSEMBLY
  const bool is_wasm_script = script->type() == Script::Type::kWasm;
#else
  const bool is_wasm_script = false;
#endif // V8_ENABLE_WEBASSEMBLY
  DirectHandle<String> sourceText =
      is_wasm_script ? isolate->factory()->empty_string()
                     : isolate->factory()->NewSubString(
                           handle(Cast<String>(script->source()), isolate),
                           info.line_start, info.line_end);
  DirectHandle<JSObject> jsinfo =
      isolate->factory()->NewJSObject(isolate->object_function());
  JSObject::AddProperty(isolate, jsinfo, isolate->factory()->script_string(),
                        script, NONE);
  JSObject::AddProperty(isolate, jsinfo, isolate->factory()->position_string(),
                        direct_handle(Smi::FromInt(position), isolate), NONE);
  JSObject::AddProperty(isolate, jsinfo, isolate->factory()->line_string(),
                        direct_handle(Smi::FromInt(info.line), isolate), NONE);
  JSObject::AddProperty(isolate, jsinfo, isolate->factory()->column_string(),
                        direct_handle(Smi::FromInt(info.column), isolate),
                        NONE);
  JSObject::AddProperty(isolate, jsinfo,
                        isolate->factory()->sourceText_string(), sourceText,
                        NONE);
  return jsinfo;
}
References v8::internal::JSObject::AddProperty(), v8::internal::Script::PositionInfo::column, v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::Smi::FromInt(), v8::internal::Script::GetPositionInfo(), v8::internal::handle(), v8::internal::Script::PositionInfo::line, v8::internal::Script::PositionInfo::line_end, v8::internal::Script::PositionInfo::line_start, v8::internal::Factory::NewJSObject(), v8::internal::NONE, and v8::internal::script.
Referenced by ScriptLocationFromLine().
GetScriptById()
bool v8::internal::anonymous_namespace{runtime-debug.cc}::GetScriptById (Isolate * isolate, int needle, DirectHandle< Script > * result)
Definition at line 663 of file runtime-debug.cc.
                                                                               {
  Script::Iterator iterator(isolate);
  for (Tagged<Script> script = iterator.Next(); !script.is_null();
       script = iterator.Next()) {
    if (script->id() == needle) {
      *result = direct_handle(script, isolate);
      return true;
    }
  }
  return false;
}
References v8::internal::direct_handle(), v8::internal::Script::Iterator::Next(), v8::base::internal::result, and v8::internal::script.
Referenced by v8::internal::RUNTIME_FUNCTION().
MakeRangeObject()
DirectHandle<JSObject> v8::internal::anonymous_namespace{runtime-debug.cc}::MakeRangeObject (Isolate * isolate, const CoverageBlock & range)
Definition at line 726 of file runtime-debug.cc.
                                                                   {
  Factory* factory = isolate->factory();
  DirectHandle<String> start_string = factory->InternalizeUtf8String("start");
  DirectHandle<String> end_string = factory->InternalizeUtf8String("end");
  DirectHandle<String> count_string = factory->InternalizeUtf8String("count");
  DirectHandle<JSObject> range_obj = factory->NewJSObjectWithNullProto();
  JSObject::AddProperty(isolate, range_obj, start_string,
                        factory->NewNumberFromInt(range.start), NONE);
  JSObject::AddProperty(isolate, range_obj, end_string,
                        factory->NewNumberFromInt(range.end), NONE);
  JSObject::AddProperty(isolate, range_obj, count_string,
                        factory->NewNumberFromUint(range.count), NONE);
  return range_obj;
}
References v8::internal::JSObject::AddProperty(), v8::internal::CoverageBlock::count, v8::internal::CoverageBlock::end, v8::internal::Isolate::factory(), v8::internal::Factory::InternalizeUtf8String(), v8::internal::Factory::NewJSObjectWithNullProto(), v8::internal::FactoryBase< Impl >::NewNumberFromInt(), v8::internal::FactoryBase< Impl >::NewNumberFromUint(), v8::internal::NONE, and v8::internal::CoverageBlock::start.
Referenced by v8::internal::RUNTIME_FUNCTION().
ScriptLinePosition()
int v8::internal::anonymous_namespace{runtime-debug.cc}::ScriptLinePosition (Isolate * isolate, DirectHandle< Script > script, int line)
Definition at line 554 of file runtime-debug.cc.
                                 {
  if (line < 0) return -1;
#if V8_ENABLE_WEBASSEMBLY
  if (script->type() == Script::Type::kWasm) {
    // Wasm positions are relative to the start of the module.
    return 0;
  }
#endif // V8_ENABLE_WEBASSEMBLY
  Script::InitLineEnds(isolate, script);
  Tagged<FixedArray> line_ends_array = Cast<FixedArray>(script->line_ends());
  const int line_count = line_ends_array->length();
  DCHECK_LT(0, line_count);
  if (line == 0) return 0;
  // If line == line_count, we return the first position beyond the last line.
  if (line > line_count) return -1;
  return Smi::ToInt(line_ends_array->get(line - 1)) + 1;
}
References DCHECK_LT, v8::internal::Script::InitLineEnds(), v8::internal::script, and v8::internal::Smi::ToInt().
Referenced by ScriptLinePositionWithOffset().
ScriptLinePositionWithOffset()
int v8::internal::anonymous_namespace{runtime-debug.cc}::ScriptLinePositionWithOffset (Isolate * isolate, DirectHandle< Script > script, int line, int offset)
Definition at line 577 of file runtime-debug.cc.
                                                       {
  if (line < 0 || offset < 0) return -1;
  if (line == 0 || offset == 0)
    return ScriptLinePosition(isolate, script, line) + offset;
  Script::PositionInfo info;
  if (!Script::GetPositionInfo(script, offset, &info,
                               Script::OffsetFlag::kNoOffset)) {
    return -1;
  }
  const int total_line = info.line + line;
  return ScriptLinePosition(isolate, script, total_line);
}
References v8::internal::Script::GetPositionInfo(), v8::internal::Script::kNoOffset, v8::internal::Script::PositionInfo::line, v8::internal::script, and ScriptLinePosition().
Referenced by ScriptLocationFromLine().
ScriptLocationFromLine()
DirectHandle<Object> v8::internal::anonymous_namespace{runtime-debug.cc}::ScriptLocationFromLine (Isolate * isolate, DirectHandle< Script > script, DirectHandle< Object > opt_line, DirectHandle< Object > opt_column, int32_t offset)
Definition at line 633 of file runtime-debug.cc.
                                                            {
  // Line and column are possibly undefined and we need to handle these cases,
  // additionally subtracting corresponding offsets.
  int32_t line = 0;
  if (!IsNullOrUndefined(*opt_line, isolate)) {
    CHECK(IsNumber(*opt_line));
    line = NumberToInt32(*opt_line) - script->line_offset();
  }
  int32_t column = 0;
  if (!IsNullOrUndefined(*opt_column, isolate)) {
    CHECK(IsNumber(*opt_column));
    column = NumberToInt32(*opt_column);
    if (line == 0) column -= script->column_offset();
  }
  int line_position =
      ScriptLinePositionWithOffset(isolate, script, line, offset);
  if (line_position < 0 || column < 0) return isolate->factory()->null_value();
  return GetJSPositionInfo(script, line_position + column,
                           Script::OffsetFlag::kNoOffset, isolate);
}
References CHECK, v8::internal::Isolate::factory(), GetJSPositionInfo(), v8::internal::IsNullOrUndefined(), v8::internal::IsNumber(), v8::internal::Script::kNoOffset, v8::internal::NumberToInt32(), v8::internal::script, and ScriptLinePositionWithOffset().
Referenced by v8::internal::RUNTIME_FUNCTION().