v8::internal::compiler::anonymous_namespace{wasm-load-elimination.cc} Namespace Reference
Functions
bool TypesUnrelated (wasm::ValueType type1, wasm::ValueType type2, const wasm::WasmModule *module)
bool TypesUnrelated (Node *lhs, Node *rhs)
bool IsFresh (Node *node)
bool IsConstant (Node *node)
bool MayAlias (Node *lhs, Node *rhs)
Node * ResolveAliases (Node *node)
Variables
constexpr int kArrayLengthFieldIndex = -1
constexpr int kStringPrepareForGetCodeunitIndex = -2
constexpr int kStringAsWtf16Index = -3
constexpr int kAnyConvertExternIndex = -4
Function Documentation
IsConstant()
bool v8::internal::compiler::anonymous_namespace{wasm-load-elimination.cc}::IsConstant (Node * node)
Definition at line 39 of file wasm-load-elimination.cc.
                            {
  return node->opcode() == IrOpcode::kParameter ||
         node->opcode() == IrOpcode::kHeapConstant;
}
References v8::internal::compiler::Node::opcode().
Referenced by MayAlias(), and v8::internal::compiler::WasmAddressReassociation::ReplaceInputs().
IsFresh()
bool v8::internal::compiler::anonymous_namespace{wasm-load-elimination.cc}::IsFresh (Node * node)
Definition at line 34 of file wasm-load-elimination.cc.
                         {
  return node->opcode() == IrOpcode::kAllocate ||
         node->opcode() == IrOpcode::kAllocateRaw;
}
References v8::internal::compiler::Node::opcode().
Referenced by MayAlias().
MayAlias()
bool v8::internal::compiler::anonymous_namespace{wasm-load-elimination.cc}::MayAlias (Node * lhs, Node * rhs)
Definition at line 44 of file wasm-load-elimination.cc.
                                    {
  if (lhs == rhs) return true;
  if (TypesUnrelated(lhs, rhs) || (IsFresh(lhs) && IsFresh(rhs)) ||
      (IsFresh(lhs) && IsConstant(rhs)) || (IsConstant(lhs) && IsFresh(rhs))) {
    return false;
  }
  return true;
}
References IsConstant(), IsFresh(), and TypesUnrelated().
Referenced by v8::internal::compiler::WasmLoadElimination::HalfState::KillField().
ResolveAliases()
Node* v8::internal::compiler::anonymous_namespace{wasm-load-elimination.cc}::ResolveAliases (Node * node)
Definition at line 53 of file wasm-load-elimination.cc.
                                 {
  while (node->opcode() == IrOpcode::kWasmTypeCast ||
         node->opcode() == IrOpcode::kWasmTypeCastAbstract ||
         node->opcode() == IrOpcode::kAssertNotNull ||
         node->opcode() == IrOpcode::kTypeGuard) {
    node = NodeProperties::GetValueInput(node, 0);
  }
  return node;
}
References v8::internal::compiler::NodeProperties::GetValueInput(), and v8::internal::compiler::Node::opcode().
Referenced by v8::internal::compiler::WasmLoadElimination::ReduceLoadLikeFromImmutable(), v8::internal::compiler::WasmLoadElimination::ReduceStringPrepareForGetCodeunit(), v8::internal::compiler::WasmLoadElimination::ReduceWasmArrayInitializeLength(), v8::internal::compiler::WasmLoadElimination::ReduceWasmStructGet(), and v8::internal::compiler::WasmLoadElimination::ReduceWasmStructSet().
TypesUnrelated() [1/2]
bool v8::internal::compiler::anonymous_namespace{wasm-load-elimination.cc}::TypesUnrelated (Node * lhs, Node * rhs)
Definition at line 27 of file wasm-load-elimination.cc.
                                          {
  wasm::TypeInModule type1 = NodeProperties::GetType(lhs).AsWasm();
  wasm::TypeInModule type2 = NodeProperties::GetType(rhs).AsWasm();
  DCHECK_EQ(type1.module, type2.module);
  return TypesUnrelated(type1.type, type2.type, type1.module);
}
References DCHECK_EQ, v8::internal::compiler::NodeProperties::GetType(), v8::internal::wasm::TypeInModule::module, and v8::internal::wasm::TypeInModule::type.
Referenced by MayAlias(), and v8::internal::compiler::WasmLoadElimination::TruncateAndExtendOrType().
TypesUnrelated() [2/2]
bool v8::internal::compiler::anonymous_namespace{wasm-load-elimination.cc}::TypesUnrelated (wasm::ValueType type1, wasm::ValueType type2, const wasm::WasmModule * module)
Definition at line 21 of file wasm-load-elimination.cc.
                                                  {
  return !wasm::IsSubtypeOf(type1, type2, module) &&
         !wasm::IsSubtypeOf(type2, type1, module);
}
References v8::internal::wasm::IsSubtypeOf().
Variable Documentation
kAnyConvertExternIndex
constexpr int v8::internal::compiler::anonymous_namespace{wasm-load-elimination.cc}::kAnyConvertExternIndex = -4 [constexpr]
Definition at line 68 of file wasm-load-elimination.cc.
Referenced by v8::internal::compiler::WasmLoadElimination::ReduceAnyConvertExtern().
kArrayLengthFieldIndex
constexpr int v8::internal::compiler::anonymous_namespace{wasm-load-elimination.cc}::kArrayLengthFieldIndex = -1 [constexpr]
Definition at line 65 of file wasm-load-elimination.cc.
Referenced by v8::internal::compiler::WasmLoadElimination::ReduceWasmArrayInitializeLength(), and v8::internal::compiler::WasmLoadElimination::ReduceWasmArrayLength().
kStringAsWtf16Index
constexpr int v8::internal::compiler::anonymous_namespace{wasm-load-elimination.cc}::kStringAsWtf16Index = -3 [constexpr]
Definition at line 67 of file wasm-load-elimination.cc.
Referenced by v8::internal::compiler::WasmLoadElimination::ReduceStringAsWtf16().
kStringPrepareForGetCodeunitIndex
constexpr int v8::internal::compiler::anonymous_namespace{wasm-load-elimination.cc}::kStringPrepareForGetCodeunitIndex = -2 [constexpr]
Definition at line 66 of file wasm-load-elimination.cc.
Referenced by v8::internal::compiler::WasmLoadElimination::ReduceStringPrepareForGetCodeunit().