v8::internal::torque::anonymous_namespace{cc-generator.cc} Namespace Reference
Functions
std::string GetBitFieldSpecialization (const Type *container, const BitField &field)
void CollectAllFields (const VisitResult &result, const Stack< std::string > &values, std::vector< std::string > &all_fields)
Function Documentation
CollectAllFields()
void v8::internal::torque::anonymous_namespace{cc-generator.cc}::CollectAllFields (const VisitResult & result, const Stack< std::string > & values, std::vector< std::string > & all_fields)
Definition at line 495 of file cc-generator.cc.
                                                        {
  if (!result.IsOnStack()) {
    all_fields.push_back(result.constexpr_value());
  } else if (auto struct_type = result.type()->StructSupertype()) {
    for (const Field& field : (*struct_type)->fields()) {
      CollectAllFields(ProjectStructField(result, field.name_and_type.name),
                       values, all_fields);
    }
  } else {
    DCHECK_EQ(1, result.stack_range().Size());
    all_fields.push_back(values.Peek(result.stack_range().begin()));
  }
}
References DCHECK_EQ, v8::internal::torque::Stack< T >::Peek(), v8::internal::torque::ProjectStructField(), and v8::base::internal::result.
Referenced by v8::internal::torque::CCGenerator::EmitCCValue().
GetBitFieldSpecialization()
std::string v8::internal::torque::anonymous_namespace{cc-generator.cc}::GetBitFieldSpecialization (const Type * container, const BitField & field)
Definition at line 447 of file cc-generator.cc.
                                                             {
  std::stringstream stream;
  stream << "base::BitField<"
         << field.name_and_type.type->GetConstexprGeneratedTypeName() << ", "
         << field.offset << ", " << field.num_bits << ", "
         << container->GetConstexprGeneratedTypeName() << ">";
  return stream.str();
}
References v8::internal::torque::Type::GetConstexprGeneratedTypeName(), v8::internal::torque::BitField::name_and_type, v8::internal::torque::BitField::num_bits, v8::internal::torque::BitField::offset, and v8::internal::torque::NameAndType::type.