v8::internal::wasm::value_type_reader Namespace Reference
Functions
template<typename ValidationTag >
std::pair< HeapType, uint32_t > read_heap_type (Decoder *decoder, const uint8_t *pc, WasmEnabledFeatures enabled, WasmDetectedFeatures *detected)
template<typename ValidationTag >
std::pair< ValueType, uint32_t > read_value_type (Decoder *decoder, const uint8_t *pc, WasmEnabledFeatures enabled, WasmDetectedFeatures *detected)
template<typename ValidationTag >
bool ValidateHeapType (Decoder *decoder, const uint8_t *pc, const WasmModule *module, HeapType type)
template<typename ValidationTag >
bool ValidateValueType (Decoder *decoder, const uint8_t *pc, const WasmModule *module, ValueType type)
static void Populate (HeapType *unfinished_type, const WasmModule *module)
static void Populate (ValueType *unfinished_type, const WasmModule *module)
Function Documentation
Populate() [1/2]
static void v8::internal::wasm::value_type_reader::Populate (HeapType * unfinished_type, const WasmModule * module) [static]
Definition at line 511 of file function-body-decoder-impl.h.
                                                                          {
  if (!unfinished_type->has_index()) return;
  DCHECK(module->has_type(unfinished_type->ref_index()));
  const TypeDefinition& type_def = module->type(unfinished_type->ref_index());
  unfinished_type->Populate(type_def.is_shared,
                            static_cast<RefTypeKind>(type_def.kind));
}
References v8::internal::DCHECK(), v8::internal::wasm::ValueTypeBase::has_index(), v8::internal::wasm::WasmModule::has_type(), v8::internal::wasm::TypeDefinition::is_shared, v8::internal::wasm::TypeDefinition::kind, v8::internal::wasm::ValueTypeBase::Populate(), v8::internal::wasm::HeapType::ref_index(), and v8::internal::wasm::WasmModule::type().
Referenced by v8::internal::wasm::ModuleDecoderImpl::consume_init_expr(), v8::internal::wasm::ModuleDecoderImpl::consume_value_type(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::ConsumeElementSegmentEntry(), v8::internal::wasm::WasmBytecodeGenerator::DecodeGCOp(), v8::internal::wasm::WasmBytecodeGenerator::DecodeInstruction(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeLocals(), v8::internal::wasm::ModuleDecoderImpl::FinalizeRecgroup(), and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate().
Populate() [2/2]
static void v8::internal::wasm::value_type_reader::Populate (ValueType * unfinished_type, const WasmModule * module) [static]
Definition at line 520 of file function-body-decoder-impl.h.
                                                                           {
  if (!unfinished_type->has_index()) return;
  DCHECK(module->has_type(unfinished_type->ref_index()));
  const TypeDefinition& type_def = module->type(unfinished_type->ref_index());
  unfinished_type->Populate(type_def.is_shared,
                            static_cast<RefTypeKind>(type_def.kind));
}
References v8::internal::DCHECK(), v8::internal::wasm::ValueTypeBase::has_index(), v8::internal::wasm::WasmModule::has_type(), v8::internal::wasm::TypeDefinition::is_shared, v8::internal::wasm::TypeDefinition::kind, v8::internal::wasm::ValueTypeBase::Populate(), v8::internal::wasm::ValueType::ref_index(), and v8::internal::wasm::WasmModule::type().
read_heap_type()
template<typename ValidationTag >
std::pair<HeapType, uint32_t> v8::internal::wasm::value_type_reader::read_heap_type (Decoder * decoder, const uint8_t * pc, WasmEnabledFeatures enabled, WasmDetectedFeatures * detected)
Definition at line 215 of file function-body-decoder-impl.h.
                                                                             {
  auto [heap_index, length] =
      decoder->read_i33v<ValidationTag>(pc, "heap type");
  Exactness exactness = Exactness::kAnySubtype;
  uint32_t type_index;
  if (heap_index < 0) {
    int64_t min_1_byte_leb128 = -64;
    if (!VALIDATE(heap_index >= min_1_byte_leb128)) {
      DecodeError<ValidationTag>(decoder, pc, "Unknown heap type %" PRId64,
                                 heap_index);
      return {kWasmBottom, length};
    }
    uint8_t uint_7_mask = 0x7F;
    uint8_t code = static_cast<ValueTypeCode>(heap_index) & uint_7_mask;
    bool is_shared = false;
    if (code == kSharedFlagCode) {
      if (!VALIDATE(enabled.has_shared())) {
        DecodeError<ValidationTag>(
            decoder, pc,
            "invalid heap type 0x%hhx, enable with --experimental-wasm-shared",
            kSharedFlagCode);
        return {kWasmBottom, length};
      }
      code = decoder->read_u8<ValidationTag>(pc + length, "heap type");
      length++;
      is_shared = true;
    }
    switch (code) {
      case kNoFuncCode:
      case kFuncRefCode:
        if (!VALIDATE(!is_shared)) {
          DecodeError<ValidationTag>(
              decoder, pc,
              "invalid heap type '%s', shared function references are not "
              "supported",
              HeapType::from_code(code, is_shared).name().c_str());
          return {kWasmBottom, 0};
        }
        [[fallthrough]];
      case kEqRefCode:
      case kI31RefCode:
      case kStructRefCode:
      case kArrayRefCode:
      case kAnyRefCode:
      case kNoneCode:
      case kNoExternCode:
      case kExternRefCode:
        return {HeapType::from_code(code, is_shared), length};
      case kNoExnCode:
      case kExnRefCode:
        if (!VALIDATE(enabled.has_exnref())) {
          DecodeError<ValidationTag>(
              decoder, pc,
              "invalid heap type '%s', enable with --experimental-wasm-exnref",
              HeapType::from_code(code, is_shared).name().c_str());
          return {kWasmBottom, 0};
        }
        if (!VALIDATE(!detected->has_legacy_eh() ||
                      v8_flags.wasm_allow_mixed_eh_for_testing)) {
          DecodeError<ValidationTag>(
              decoder, pc,
              "module uses a mix of legacy and new exception handling "
              "instructions");
          return {kWasmBottom, 0};
        }
        if (!VALIDATE(!is_shared)) {
          DecodeError<ValidationTag>(
              decoder, pc,
              "invalid heap type '%s', shared exception references are not "
              "supported",
              HeapType::from_code(code, is_shared).name().c_str());
          return {kWasmBottom, 0};
        }
        detected->add_exnref();
        return {HeapType::from_code(code, is_shared), length};
      case kStringRefCode:
      case kStringViewWtf8Code:
      case kStringViewWtf16Code:
      case kStringViewIterCode:
        if (!VALIDATE(enabled.has_stringref())) {
          DecodeError<ValidationTag>(
              decoder, pc,
              "invalid heap type '%s', enable with "
              "--experimental-wasm-stringref",
              HeapType::from_code(code, is_shared).name().c_str());
          return {kWasmBottom, 0};
        }
        return {HeapType::from_code(code, is_shared), length};
      case kNoContCode:
      case kContRefCode:
        if (!VALIDATE(enabled.has_wasmfx())) {
          DecodeError<ValidationTag>(
              decoder, pc,
              "invalid heap type '%s', enable with "
              "--experimental-wasm-wasmfx",
              HeapType::from_code(code, is_shared).name().c_str());
          return {kWasmBottom, 0};
        }
        if (!VALIDATE(!is_shared)) {
          DecodeError<ValidationTag>(
              decoder, pc,
              "invalid heap type '%s', shared continuation references are not "
              "supported",
              HeapType::from_code(code, is_shared).name().c_str());
          return {kWasmBottom, 0};
        }
        return {HeapType::from_code(code, is_shared), length};
      case kExactCode: {
        if (!VALIDATE(enabled.has_custom_descriptors())) {
          DecodeError<ValidationTag>(decoder, pc,
                                     "invalid heap type 'exact', enable with "
                                     "--experimental-wasm-custom-descriptors");
          return {kWasmBottom, 0};
        }
        auto [nested_index, index_length] =
            decoder->read_u32v<ValidationTag>(pc + 1, "type index");
        type_index = nested_index;
        exactness = Exactness::kExact;
        length += index_length;
        break;
      }
      default:
        DecodeError<ValidationTag>(decoder, pc, "Unknown heap type %" PRId64,
                                   heap_index);
        return {kWasmBottom, length};
    }
  } else {
    type_index = static_cast<uint32_t>(heap_index);
  }
  if (!VALIDATE(type_index < kV8MaxWasmTypes)) {
    DecodeError<ValidationTag>(
        decoder, pc,
        "Type index %u is greater than the maximum number %zu "
        "of type definitions supported by V8",
        type_index, kV8MaxWasmTypes);
    return {kWasmBottom, length};
  }
  // We don't have a module yet, so we can only fill in default values:
  bool kDefaultShared = false;
  RefTypeKind kDefaultKind = RefTypeKind::kOther;
  return {HeapType::Index(ModuleTypeIndex{type_index}, kDefaultShared,
                          kDefaultKind, exactness),
          length};
}
References code, v8::internal::wasm::HeapType::from_code(), v8::internal::wasm::HeapType::Index(), v8::internal::is_shared, v8::internal::wasm::kAnyRefCode, v8::internal::wasm::kAnySubtype, v8::internal::wasm::kArrayRefCode, v8::internal::wasm::kContRefCode, v8::internal::wasm::kEqRefCode, v8::internal::wasm::kExact, v8::internal::wasm::kExactCode, v8::internal::wasm::kExnRefCode, v8::internal::wasm::kExternRefCode, v8::internal::wasm::kFuncRefCode, v8::internal::wasm::kI31RefCode, v8::internal::wasm::kNoContCode, v8::internal::wasm::kNoExnCode, v8::internal::wasm::kNoExternCode, v8::internal::wasm::kNoFuncCode, v8::internal::wasm::kNoneCode, v8::internal::wasm::kOther, v8::internal::wasm::kSharedFlagCode, v8::internal::wasm::kStringRefCode, v8::internal::wasm::kStringViewIterCode, v8::internal::wasm::kStringViewWtf16Code, v8::internal::wasm::kStringViewWtf8Code, v8::internal::wasm::kStructRefCode, v8::internal::wasm::kV8MaxWasmTypes, v8::internal::wasm::kWasmBottom, v8::internal::length, v8::internal::wasm::name(), v8::internal::wasm::Decoder::read_i33v(), v8::internal::wasm::Decoder::read_u32v(), v8::internal::wasm::Decoder::read_u8(), v8::internal::v8_flags, and VALIDATE.
read_value_type()
template<typename ValidationTag >
std::pair<ValueType, uint32_t> v8::internal::wasm::value_type_reader::read_value_type (Decoder * decoder, const uint8_t * pc, WasmEnabledFeatures enabled, WasmDetectedFeatures * detected)
Definition at line 367 of file function-body-decoder-impl.h.
                                                                               {
  uint8_t val = decoder->read_u8<ValidationTag>(pc, "value type opcode");
  if (!VALIDATE(decoder->ok())) {
    return {kWasmBottom, 0};
  }
  ValueTypeCode code = static_cast<ValueTypeCode>(val);
  switch (code) {
    case kEqRefCode:
    case kI31RefCode:
    case kStructRefCode:
    case kArrayRefCode:
    case kAnyRefCode:
    case kNoneCode:
    case kNoExternCode:
    case kNoFuncCode:
    case kExternRefCode:
    case kFuncRefCode:
      return {ValueType::RefNull(HeapType::from_code(code, false)), 1};
    case kNoExnCode:
    case kExnRefCode:
      if (!VALIDATE(enabled.has_exnref())) {
        DecodeError<ValidationTag>(
            decoder, pc,
            "invalid value type '%s', enable with --experimental-wasm-exnref",
            HeapType::from_code(code, false).name().c_str());
        return {kWasmBottom, 0};
      }
      if (!VALIDATE(!detected->has_legacy_eh() ||
                    v8_flags.wasm_allow_mixed_eh_for_testing)) {
        DecodeError<ValidationTag>(
            decoder, pc,
            "module uses a mix of legacy and new exception handling "
            "instructions");
        return {kWasmBottom, 0};
      }
      detected->add_exnref();
      return {code == kExnRefCode ? kWasmExnRef : kWasmNullExnRef, 1};
    case kStringRefCode:
    case kStringViewWtf8Code:
    case kStringViewWtf16Code:
    case kStringViewIterCode: {
      if (!VALIDATE(enabled.has_stringref())) {
        DecodeError<ValidationTag>(
            decoder, pc,
            "invalid value type '%sref', enable with "
            "--experimental-wasm-stringref",
            HeapType::from_code(code, false).name().c_str());
        return {kWasmBottom, 0};
      }
      // String views are not nullable, so interpret the shorthand accordingly.
      ValueType type = code == kStringRefCode
                           ? kWasmStringRef
                           : ValueType::Ref(HeapType::from_code(code, false));
      return {type, 1};
    }
    case kContRefCode:
    case kNoContCode:
      if (!VALIDATE(enabled.has_wasmfx())) {
        DecodeError<ValidationTag>(
            decoder, pc,
            "invalid value type '%s', enable with --experimental-wasm-wasmfx",
            HeapType::from_code(code, false).name().c_str());
        return {kWasmBottom, 0};
      }
      return {code == kContRefCode ? kWasmContRef : kWasmNullContRef, 1};
    case kI32Code:
      return {kWasmI32, 1};
    case kI64Code:
      return {kWasmI64, 1};
    case kF32Code:
      return {kWasmF32, 1};
    case kF64Code:
      return {kWasmF64, 1};
    case kRefCode:
    case kRefNullCode: {
      Nullability nullability = code == kRefNullCode ? kNullable : kNonNullable;
      auto [heap_type, length] =
          read_heap_type<ValidationTag>(decoder, pc + 1, enabled, detected);
      if (!VALIDATE(!heap_type.is_string_view() ||
                    nullability == kNonNullable)) {
        DecodeError<ValidationTag>(decoder, pc,
                                   "nullable string views don't exist");
        return {kWasmBottom, 0};
      }
      ValueType type = heap_type.is_bottom()
                           ? kWasmBottom
                           : ValueType::RefMaybeNull(heap_type, nullability);
      return {type, length + 1};
    }
    case kS128Code: {
      if (!VALIDATE(CheckHardwareSupportsSimd())) {
        if (v8_flags.correctness_fuzzer_suppressions) {
          FATAL("Aborting on missing Wasm SIMD support");
        }
        DecodeError<ValidationTag>(decoder, pc, "Wasm SIMD unsupported");
        return {kWasmBottom, 0};
      }
      return {kWasmS128, 1};
    }
    // Although these codes are included in ValueTypeCode, they technically
    // do not correspond to value types and are only used in specific
    // contexts. The caller of this function is responsible for handling them.
    case kVoidCode:
    case kI8Code:
    case kI16Code:
    case kF16Code:
    case kExactCode:
      // Fall through to the error reporting below.
      break;
  }
  // Anything that doesn't match an enumeration value is an invalid type code.
  if constexpr (!ValidationTag::validate) UNREACHABLE();
  DecodeError<ValidationTag>(decoder, pc, "invalid value type 0x%hhx", code);
  return {kWasmBottom, 0};
}
References v8::internal::wasm::CheckHardwareSupportsSimd(), code, FATAL, v8::internal::wasm::HeapType::from_code(), v8::internal::wasm::kAnyRefCode, v8::internal::wasm::kArrayRefCode, v8::internal::wasm::kContRefCode, v8::internal::wasm::kEqRefCode, v8::internal::wasm::kExactCode, v8::internal::wasm::kExnRefCode, v8::internal::wasm::kExternRefCode, v8::internal::wasm::kF16Code, v8::internal::wasm::kF32Code, v8::internal::wasm::kF64Code, v8::internal::wasm::kFuncRefCode, v8::internal::wasm::kI16Code, v8::internal::wasm::kI31RefCode, v8::internal::wasm::kI32Code, v8::internal::wasm::kI64Code, v8::internal::wasm::kI8Code, v8::internal::wasm::kNoContCode, v8::internal::wasm::kNoExnCode, v8::internal::wasm::kNoExternCode, v8::internal::wasm::kNoFuncCode, v8::internal::wasm::kNoneCode, v8::internal::wasm::kNonNullable, v8::internal::wasm::kNullable, v8::internal::wasm::kRefCode, v8::internal::wasm::kRefNullCode, v8::internal::wasm::kS128Code, v8::internal::wasm::kStringRefCode, v8::internal::wasm::kStringViewIterCode, v8::internal::wasm::kStringViewWtf16Code, v8::internal::wasm::kStringViewWtf8Code, v8::internal::wasm::kStructRefCode, v8::internal::wasm::kVoidCode, v8::internal::wasm::kWasmBottom, v8::internal::wasm::kWasmContRef, v8::internal::wasm::kWasmExnRef, v8::internal::wasm::kWasmF32, v8::internal::wasm::kWasmF64, v8::internal::wasm::kWasmI32, v8::internal::wasm::kWasmI64, v8::internal::wasm::kWasmNullContRef, v8::internal::wasm::kWasmNullExnRef, v8::internal::wasm::kWasmS128, v8::internal::wasm::kWasmStringRef, v8::internal::length, v8::internal::wasm::name(), v8::internal::wasm::Decoder::ok(), v8::internal::wasm::Decoder::read_u8(), v8::internal::wasm::ValueType::Ref(), v8::internal::wasm::ValueType::RefMaybeNull(), v8::internal::wasm::ValueType::RefNull(), v8::internal::tracing::type, v8::internal::UNREACHABLE(), v8::internal::v8_flags, and VALIDATE.
ValidateHeapType()
template<typename ValidationTag >
bool v8::internal::wasm::value_type_reader::ValidateHeapType (Decoder * decoder, const uint8_t * pc, const WasmModule * module, HeapType type)
Definition at line 487 of file function-body-decoder-impl.h.
                                                               {
  if (!VALIDATE(!type.is_bottom())) return false;
  if (!type.is_index()) return true;
  // A {nullptr} module is accepted if we are not validating anyway (e.g. for
  // opcode length computation).
  if (!ValidationTag::validate && module == nullptr) return true;
  if (!VALIDATE(type.ref_index().index < module->types.size())) {
    DecodeError<ValidationTag>(decoder, pc, "Type index %u is out of bounds",
                               type.ref_index().index);
    return false;
  }
  return true;
}
References v8::internal::tracing::type, v8::internal::wasm::WasmModule::types, and VALIDATE.
ValidateValueType()
template<typename ValidationTag >
bool v8::internal::wasm::value_type_reader::ValidateValueType (Decoder * decoder, const uint8_t * pc, const WasmModule * module, ValueType type)
Definition at line 503 of file function-body-decoder-impl.h.
                                                                 {
  if (!VALIDATE(!type.is_bottom())) return false;
  if (V8_LIKELY(!type.is_object_reference())) return true;
  return ValidateHeapType<ValidationTag>(decoder, pc, module, type.heap_type());
}
References v8::internal::tracing::type, V8_LIKELY, and VALIDATE.