v8::internal::compiler::anonymous_namespace{bitcast-elider.cc} Namespace Reference
Functions
bool IsBitcast (Node *node)
bool OwnedByWord32Op (Node *node)
void Replace (Node *node, Node *replacement)
Function Documentation
IsBitcast()
bool v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::IsBitcast (Node * node)
Definition at line 15 of file bitcast-elider.cc.
                           {
  // We can only elide kBitcastTaggedToWordForTagAndSmiBits and
  // kBitcastWordToTaggedSigned because others might affect GC / safepoint
  // tables.
  return node->opcode() == IrOpcode::kBitcastTaggedToWordForTagAndSmiBits ||
         node->opcode() == IrOpcode::kBitcastWordToTaggedSigned;
}
References v8::internal::compiler::Node::opcode().
Referenced by v8::internal::compiler::BitcastElider::VisitNode().
OwnedByWord32Op()
bool v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::OwnedByWord32Op (Node * node)
Definition at line 23 of file bitcast-elider.cc.
                                 {
#if V8_TARGET_ARCH_LOONG64 || V8_TARGET_ARCH_MIPS64 || V8_TARGET_ARCH_RISCV64
  return false;
#else
  for (Node* const use : node->uses()) {
    switch (use->opcode()) {
      case IrOpcode::kWord32Equal:
      case IrOpcode::kInt32LessThan:
      case IrOpcode::kInt32LessThanOrEqual:
      case IrOpcode::kUint32LessThan:
      case IrOpcode::kUint32LessThanOrEqual:
      case IrOpcode::kChangeInt32ToInt64:
#define Word32Op(Name) case IrOpcode::k##Name:
        MACHINE_BINOP_32_LIST(Word32Op)
#undef Word32Op
        break;
      default:
        return false;
    }
  }
  return true;
#endif
}
References MACHINE_BINOP_32_LIST, use(), v8::internal::compiler::Node::uses(), and Word32Op.
Referenced by v8::internal::compiler::BitcastElider::VisitNode().
Replace()
void v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace (Node * node, Node * replacement)
Definition at line 47 of file bitcast-elider.cc.
                                            {
  for (Edge edge : node->use_edges()) {
    edge.UpdateTo(replacement);
  }
  node->Kill();
}
References v8::internal::compiler::Node::Kill(), and v8::internal::compiler::Node::use_edges().
Referenced by v8::internal::compiler::CsaLoadElimination::AssertUnreachable(), v8::internal::compiler::JSTypedLowering::GenerateStringAddition(), v8::internal::compiler::DeadCodeElimination::PropagateDeadControl(), v8::internal::compiler::ConstantFoldingReducer::Reduce(), v8::internal::compiler::SimplifiedOperatorReducer::Reduce(), v8::internal::compiler::MachineOperatorReducer::Reduce(), v8::internal::compiler::PairLoadStoreReducer::Reduce(), v8::internal::compiler::BranchElimination::ReduceBranch(), v8::internal::compiler::CommonOperatorReducer::ReduceBranch(), v8::internal::compiler::DeadCodeElimination::ReduceBranchOrSwitch(), v8::internal::compiler::TypedOptimization::ReduceCheckEqualsInternalizedString(), v8::internal::compiler::TypedOptimization::ReduceCheckEqualsSymbol(), v8::internal::compiler::TypedOptimization::ReduceCheckHeapObject(), v8::internal::compiler::LoadElimination::ReduceCheckMaps(), v8::internal::compiler::TypedOptimization::ReduceCheckMaps(), v8::internal::compiler::TypedOptimization::ReduceCheckNotTaggedHole(), v8::internal::compiler::TypedOptimization::ReduceCheckNumber(), v8::internal::compiler::TypedOptimization::ReduceCheckNumberFitsInt32(), v8::internal::compiler::CheckpointElimination::ReduceCheckpoint(), v8::internal::compiler::TypedOptimization::ReduceCheckString(), v8::internal::compiler::TypedOptimization::ReduceCheckStringOrStringWrapper(), v8::internal::compiler::LoadElimination::ReduceCompareMaps(), v8::internal::compiler::TypedOptimization::ReduceConvertReceiver(), v8::internal::compiler::BranchElimination::ReduceDeoptimizeConditional(), v8::internal::compiler::CommonOperatorReducer::ReduceDeoptimizeConditional(), v8::internal::compiler::DeadCodeElimination::ReduceEffectNode(), v8::internal::compiler::CommonOperatorReducer::ReduceEffectPhi(), v8::internal::compiler::DeadCodeElimination::ReduceEnd(), v8::internal::compiler::LoadElimination::ReduceEnsureWritableFastElements(), v8::internal::compiler::MachineOperatorReducer::ReduceInt32Add(), v8::internal::compiler::MachineOperatorReducer::ReduceInt32Div(), v8::internal::compiler::MachineOperatorReducer::ReduceInt32Mod(), v8::internal::compiler::MachineOperatorReducer::ReduceInt32Sub(), v8::internal::compiler::MachineOperatorReducer::ReduceInt64Add(), v8::internal::compiler::MachineOperatorReducer::ReduceInt64Div(), v8::internal::compiler::MachineOperatorReducer::ReduceInt64Mod(), v8::internal::compiler::MachineOperatorReducer::ReduceInt64Mul(), v8::internal::compiler::MachineOperatorReducer::ReduceInt64Sub(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateLiteralArrayOrObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateLiteralRegExp(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateObject(), v8::internal::compiler::JSTypedLowering::ReduceJSEqual(), v8::internal::compiler::JSTypedLowering::ReduceJSForInPrepare(), v8::internal::compiler::JSCreateLowering::ReduceJSGetTemplateObject(), v8::internal::compiler::JSTypedLowering::ReduceJSHasInPrototypeChain(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadNamed(), v8::internal::compiler::JSTypedLowering::ReduceJSOrdinaryHasInstance(), v8::internal::compiler::JSTypedLowering::ReduceJSParseInt(), v8::internal::compiler::JSTypedLowering::ReduceJSStrictEqual(), v8::internal::compiler::JSTypedLowering::ReduceJSToLength(), v8::internal::compiler::JSTypedLowering::ReduceJSToName(), v8::internal::compiler::JSTypedLowering::ReduceJSToNumberInput(), v8::internal::compiler::TypedOptimization::ReduceJSToNumberInput(), v8::internal::compiler::JSTypedLowering::ReduceJSToObject(), v8::internal::compiler::JSTypedLowering::ReduceJSToStringInput(), v8::internal::compiler::LoadElimination::ReduceLoadElement(), v8::internal::compiler::TypedOptimization::ReduceLoadField(), v8::internal::compiler::LoadElimination::ReduceLoadField(), v8::internal::compiler::CsaLoadElimination::ReduceLoadFromObject(), v8::internal::compiler::WasmLoadElimination::ReduceLoadLikeFromImmutable(), v8::internal::compiler::DeadCodeElimination::ReduceLoopOrMerge(), v8::internal::compiler::LoadElimination::ReduceMapGuard(), v8::internal::compiler::TypedOptimization::ReduceMaybeGrowFastElements(), v8::internal::compiler::CommonOperatorReducer::ReduceMerge(), v8::internal::compiler::TypedOptimization::ReduceNumberFloor(), v8::internal::compiler::TypedOptimization::ReduceNumberRoundop(), v8::internal::compiler::TypedOptimization::ReduceNumberSilenceNaN(), v8::internal::compiler::TypedOptimization::ReduceNumberToUint8Clamped(), v8::internal::compiler::JSTypedLowering::ReduceObjectIsArray(), v8::internal::compiler::CommonOperatorReducer::ReducePhi(), v8::internal::compiler::DeadCodeElimination::ReducePhi(), v8::internal::compiler::MachineOperatorReducer::ReduceProjection(), v8::internal::compiler::DeadCodeElimination::ReducePureNode(), v8::internal::compiler::TypedOptimization::ReduceReferenceEqual(), v8::internal::compiler::CommonOperatorReducer::ReduceReturn(), v8::internal::compiler::TypedOptimization::ReduceSameValue(), v8::internal::compiler::CommonOperatorReducer::ReduceSelect(), v8::internal::compiler::TypedOptimization::ReduceSelect(), v8::internal::compiler::TypedOptimization::ReduceSpeculativeNumberAdd(), v8::internal::compiler::TypedOptimization::ReduceSpeculativeNumberBinop(), v8::internal::compiler::TypedOptimization::ReduceSpeculativeNumberComparison(), v8::internal::compiler::TypedOptimization::ReduceSpeculativeToNumber(), v8::internal::compiler::LoadElimination::ReduceStoreElement(), v8::internal::compiler::LoadElimination::ReduceStoreField(), v8::internal::compiler::TypedOptimization::ReduceStringComparison(), v8::internal::compiler::TypedOptimization::ReduceStringLength(), v8::internal::compiler::WasmLoadElimination::ReduceStringPrepareForGetCodeunit(), v8::internal::compiler::CommonOperatorReducer::ReduceSwitch(), v8::internal::compiler::TypedOptimization::ReduceToBoolean(), v8::internal::compiler::JSIntrinsicLowering::ReduceToString(), v8::internal::compiler::LoadElimination::ReduceTransitionElementsKind(), v8::internal::compiler::LoadElimination::ReduceTransitionElementsKindOrCheckMap(), v8::internal::compiler::TypedOptimization::ReduceTransitionElementsKindOrCheckMap(), v8::internal::compiler::BranchElimination::ReduceTrapConditional(), v8::internal::compiler::CommonOperatorReducer::ReduceTrapConditional(), v8::internal::compiler::MachineOperatorReducer::ReduceTruncateInt64ToInt32(), v8::internal::compiler::TypedOptimization::ReduceTypedArrayLength(), v8::internal::compiler::TypedOptimization::ReduceTypeOf(), v8::internal::compiler::MachineOperatorReducer::ReduceUint32Div(), v8::internal::compiler::MachineOperatorReducer::ReduceUint32Mod(), v8::internal::compiler::MachineOperatorReducer::ReduceUint64Div(), v8::internal::compiler::MachineOperatorReducer::ReduceUint64Mod(), v8::internal::compiler::DeadCodeElimination::ReduceUnreachableOrIfException(), v8::internal::compiler::WasmLoadElimination::ReduceWasmStructGet(), v8::internal::compiler::WasmLoadElimination::ReduceWasmStructSet(), v8::internal::compiler::MachineOperatorReducer::ReduceWord32Sar(), v8::internal::compiler::MachineOperatorReducer::ReduceWord32Shl(), v8::internal::compiler::MachineOperatorReducer::ReduceWord32Shr(), v8::internal::compiler::MachineOperatorReducer::ReduceWord32Xor(), v8::internal::compiler::MachineOperatorReducer::ReduceWord64Sar(), v8::internal::compiler::MachineOperatorReducer::ReduceWord64Shl(), v8::internal::compiler::MachineOperatorReducer::ReduceWord64Shr(), v8::internal::compiler::MachineOperatorReducer::ReduceWordNAnd(), v8::internal::compiler::MachineOperatorReducer::ReduceWordNOr(), v8::internal::compiler::MachineOperatorReducer::ReduceWordNXor(), v8::internal::compiler::DeadCodeElimination::RemoveLoopExit(), v8::internal::compiler::SimplifiedOperatorReducer::ReplaceBoolean(), v8::internal::compiler::MachineOperatorReducer::ReplaceFloat32(), v8::internal::compiler::MachineOperatorReducer::ReplaceFloat64(), v8::internal::compiler::SimplifiedOperatorReducer::ReplaceFloat64(), v8::internal::compiler::ValueNumberingReducer::ReplaceIfTypesMatch(), v8::internal::compiler::MachineOperatorReducer::ReplaceInt32(), v8::internal::compiler::SimplifiedOperatorReducer::ReplaceInt32(), v8::internal::compiler::MachineOperatorReducer::ReplaceInt64(), v8::internal::compiler::EscapeAnalysisReducer::ReplaceNode(), v8::internal::compiler::SimplifiedOperatorReducer::ReplaceNumber(), v8::internal::compiler::MachineOperatorReducer::ReplaceUint32(), v8::internal::compiler::MachineOperatorReducer::ReplaceUint64(), v8::internal::compiler::TypedOptimization::TryReduceStringComparisonOfStringFromSingleCharCode(), v8::internal::compiler::TypedOptimization::TryReduceStringComparisonOfStringFromSingleCharCodeToConstant(), and v8::internal::compiler::BitcastElider::VisitNode().