v8::anonymous_namespace{code-generator-riscv.cc} Namespace Reference
Functions
bool Is32BitOperand (InstructionOperand *operand)
bool Use32BitMove (InstructionOperand *source, InstructionOperand *destination)
Function Documentation
Is32BitOperand()
bool v8::anonymous_namespace{code-generator-riscv.cc}::Is32BitOperand (InstructionOperand * operand)
Definition at line 4785 of file code-generator-riscv.cc.
                                                 {
  DCHECK(operand->IsStackSlot() || operand->IsRegister());
  MachineRepresentation mr = LocationOperand::cast(operand)->representation();
  return mr == MachineRepresentation::kWord32 ||
         mr == MachineRepresentation::kCompressed ||
         mr == MachineRepresentation::kCompressedPointer;
}
References v8::internal::compiler::LocationOperand::cast(), v8::internal::DCHECK(), v8::internal::kCompressed, v8::internal::kCompressedPointer, v8::internal::kWord32, and v8::internal::compiler::LocationOperand::representation().
Referenced by Use32BitMove().
Use32BitMove()
bool v8::anonymous_namespace{code-generator-riscv.cc}::Use32BitMove (InstructionOperand * source, InstructionOperand * destination)
Definition at line 4795 of file code-generator-riscv.cc.
                                                                               {
  return Is32BitOperand(source) && Is32BitOperand(destination);
}
References Is32BitOperand().