v8::internal::anonymous_namespace{liveedit.cc} Namespace Reference
Classes
class SubrangableInput
class SubrangableOutput
class TokensCompareInput
class TokensCompareOutput
class LineEndsWrapper
class LineArrayCompareInput
class TokenizingLineArrayCompareOutput
struct SourcePositionEvent
struct FunctionLiteralChange
class CollectFunctionLiterals
struct FunctionData
class FunctionDataMap
Typedefs
using FunctionLiteralChanges = std::unordered_map< FunctionLiteral *, FunctionLiteralChange >
using LiteralMap = std::unordered_map< FunctionLiteral *, FunctionLiteral * >
Enumerations
enum ChangeState { UNCHANGED
, CHANGED
, DAMAGED
 }
Functions
bool CompareSubstrings (DirectHandle< String > s1, int pos1, DirectHandle< String > s2, int pos2, int len)
void NarrowDownInput (SubrangableInput *input, SubrangableOutput *output)
void CalculateFunctionLiteralChanges (const std::vector< FunctionLiteral * > &literals, const std::vector< SourceChangeRange > &diffs, FunctionLiteralChanges *result)
bool HasChangedScope (FunctionLiteral *a, FunctionLiteral *b)
void MapLiterals (const FunctionLiteralChanges &changes, const std::vector< FunctionLiteral * > &new_literals, LiteralMap *unchanged, LiteralMap *changed)
bool ParseScript (Isolate *isolate, Handle< Script > script, ParseInfo *parse_info, MaybeDirectHandle< ScopeInfo > outer_scope_info, bool compile_as_well, std::vector< FunctionLiteral * > *literals, std::map< uint32_t, std::vector< uint32_t >> *eval_calls, debug::LiveEditResult *result)
bool CanPatchScript (const LiteralMap &changed, DirectHandle< Script > script, DirectHandle< Script > new_script, FunctionDataMap &function_data_map, bool allow_top_frame_live_editing, debug::LiveEditResult *result)
void TranslateSourcePositionTable (Isolate *isolate, DirectHandle< BytecodeArray > code, const std::vector< SourceChangeRange > &diffs)
void UpdatePositions (Isolate *isolate, DirectHandle< SharedFunctionInfo > sfi, FunctionLiteral *new_function, const std::vector< SourceChangeRange > &diffs)
MaybeDirectHandle< ScopeInfo > DetermineOuterScopeInfo (Isolate *isolate, DirectHandle< Script > script)
Typedef Documentation
FunctionLiteralChanges
using v8::internal::anonymous_namespace{liveedit.cc}::FunctionLiteralChanges = typedef std::unordered_map<FunctionLiteral*, FunctionLiteralChange>
Definition at line 354 of file liveedit.cc.
LiteralMap
using v8::internal::anonymous_namespace{liveedit.cc}::LiteralMap = typedef std::unordered_map<FunctionLiteral*, FunctionLiteral*>
Definition at line 442 of file liveedit.cc.
Enumeration Type Documentation
ChangeState
enum v8::internal::anonymous_namespace{liveedit.cc}::ChangeState
Enumerator
UNCHANGED
CHANGED
DAMAGED
Definition at line 440 of file liveedit.cc.
{ UNCHANGED, CHANGED, DAMAGED };
Function Documentation
CalculateFunctionLiteralChanges()
void v8::internal::anonymous_namespace{liveedit.cc}::CalculateFunctionLiteralChanges (const std::vector< FunctionLiteral * > & literals, const std::vector< SourceChangeRange > & diffs, FunctionLiteralChanges * result)
Definition at line 356 of file liveedit.cc.
                                    {
  std::vector<SourcePositionEvent> events;
  events.reserve(literals.size() * 2 + diffs.size() * 2);
  for (FunctionLiteral* literal : literals) {
    events.emplace_back(literal, true);
    events.emplace_back(literal, false);
  }
  for (const SourceChangeRange& diff : diffs) {
    events.emplace_back(diff, true);
    events.emplace_back(diff, false);
  }
  std::sort(events.begin(), events.end(), SourcePositionEvent::LessThan);
  bool inside_diff = false;
  int delta = 0;
  std::stack<std::pair<FunctionLiteral*, FunctionLiteralChange>> literal_stack;
  for (const SourcePositionEvent& event : events) {
    switch (event.type) {
      case SourcePositionEvent::DIFF_ENDS:
        DCHECK(inside_diff);
        inside_diff = false;
        delta += event.pos_diff;
        break;
      case SourcePositionEvent::LITERAL_ENDS: {
        DCHECK_EQ(literal_stack.top().first, event.literal);
        FunctionLiteralChange& change = literal_stack.top().second;
        change.new_end_position = inside_diff
                                      ? kNoSourcePosition
                                      : event.literal->end_position() + delta;
        result->insert(literal_stack.top());
        literal_stack.pop();
        break;
      }
      case SourcePositionEvent::LITERAL_STARTS:
        literal_stack.push(std::make_pair(
            event.literal,
            FunctionLiteralChange(
                inside_diff ? kNoSourcePosition
                            : event.literal->start_position() + delta,
                literal_stack.empty() ? nullptr : literal_stack.top().first)));
        break;
      case SourcePositionEvent::DIFF_STARTS:
        DCHECK(!inside_diff);
        inside_diff = true;
        if (!literal_stack.empty()) {
          // Note that outer literal has not necessarily changed, unless the
          // diff goes past the end of this literal. In this case, we'll mark
          // this function as damaged and parent as changed later in
          // MapLiterals.
          literal_stack.top().second.has_changes = true;
        }
        break;
    }
  }
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::kNoSourcePosition, v8::internal::anonymous_namespace{liveedit.cc}::FunctionLiteralChange::new_end_position, v8::base::internal::result, and v8::base::sort().
Referenced by v8::internal::LiveEdit::PatchScript().
CanPatchScript()
bool v8::internal::anonymous_namespace{liveedit.cc}::CanPatchScript (const LiteralMap & changed, DirectHandle< Script > script, DirectHandle< Script > new_script, FunctionDataMap & function_data_map, bool allow_top_frame_live_editing, debug::LiveEditResult * result)
Definition at line 712 of file liveedit.cc.
                                                 {
  for (const auto& mapping : changed) {
    FunctionData* data = nullptr;
    function_data_map.Lookup(script, mapping.first, &data);
    FunctionData* new_data = nullptr;
    function_data_map.Lookup(new_script, mapping.second, &new_data);
    Handle<SharedFunctionInfo> sfi;
    if (!data->shared.ToHandle(&sfi)) {
      continue;
    } else if (IsModule(sfi->kind())) {
      DCHECK(script->origin_options().IsModule() && sfi->is_toplevel());
      result->status =
          debug::LiveEditResult::BLOCKED_BY_TOP_LEVEL_ES_MODULE_CHANGE;
      return false;
    } else if (data->stack_position == FunctionData::ON_STACK) {
      result->status = debug::LiveEditResult::BLOCKED_BY_ACTIVE_FUNCTION;
      return false;
    } else if (!data->running_generators.empty()) {
      result->status = debug::LiveEditResult::BLOCKED_BY_RUNNING_GENERATOR;
      return false;
    } else if (data->stack_position == FunctionData::ON_TOP_ONLY) {
      if (!allow_top_frame_live_editing) {
        result->status = debug::LiveEditResult::BLOCKED_BY_ACTIVE_FUNCTION;
        return false;
      }
      result->restart_top_frame_required = true;
    }
  }
  return true;
}
References v8::debug::LiveEditResult::BLOCKED_BY_ACTIVE_FUNCTION, v8::debug::LiveEditResult::BLOCKED_BY_RUNNING_GENERATOR, v8::debug::LiveEditResult::BLOCKED_BY_TOP_LEVEL_ES_MODULE_CHANGE, v8::internal::DCHECK(), v8::internal::IsModule(), v8::internal::anonymous_namespace{liveedit.cc}::FunctionDataMap::Lookup(), v8::base::internal::result, v8::internal::anonymous_namespace{liveedit.cc}::FunctionData::running_generators, v8::internal::script, v8::internal::anonymous_namespace{liveedit.cc}::FunctionData::shared, and v8::internal::anonymous_namespace{liveedit.cc}::FunctionData::stack_position.
Referenced by v8::internal::LiveEdit::PatchScript().
CompareSubstrings()
bool v8::internal::anonymous_namespace{liveedit.cc}::CompareSubstrings (DirectHandle< String > s1, int pos1, DirectHandle< String > s2, int pos2, int len)
Definition at line 34 of file liveedit.cc.
                                                                   {
  for (int i = 0; i < len; i++) {
    if (s1->Get(i + pos1) != s2->Get(i + pos2)) return false;
  }
  return true;
}
Referenced by v8::internal::anonymous_namespace{liveedit.cc}::LineArrayCompareInput::Equals().
DetermineOuterScopeInfo()
MaybeDirectHandle<ScopeInfo> v8::internal::anonymous_namespace{liveedit.cc}::DetermineOuterScopeInfo (Isolate * isolate, DirectHandle< Script > script)
Definition at line 825 of file liveedit.cc.
                                                   {
  if (!script->has_eval_from_shared()) return kNullMaybeHandle;
  DCHECK_EQ(script->compilation_type(), Script::CompilationType::kEval);
  Tagged<ScopeInfo> scope_info = script->eval_from_shared()->scope_info();
  // Sloppy eval compiles use the ScopeInfo of the context. Let's find it.
  while (!scope_info->IsEmpty()) {
    if (scope_info->HasContext()) {
#ifdef DEBUG
      Tagged<ScopeInfo> other_scope_info =
          FindOuterScopeInfoFromScriptSfi(isolate, script);
      DCHECK_IMPLIES(!other_scope_info.is_null(),
                     scope_info == other_scope_info);
#endif
      return direct_handle(scope_info, isolate);
    } else if (!scope_info->HasOuterScopeInfo()) {
      break;
    }
    scope_info = scope_info->OuterScopeInfo();
  }
  return kNullMaybeHandle;
}
References DCHECK_EQ, DCHECK_IMPLIES, v8::internal::direct_handle(), v8::internal::Tagged< HeapObject >::is_null(), v8::internal::Script::kEval, v8::internal::kNullMaybeHandle, and v8::internal::script.
Referenced by v8::internal::LiveEdit::PatchScript().
HasChangedScope()
bool v8::internal::anonymous_namespace{liveedit.cc}::HasChangedScope (FunctionLiteral * a, FunctionLiteral * b)
Definition at line 419 of file liveedit.cc.
                                                             {
  Scope* scope_a = a->scope()->outer_scope();
  Scope* scope_b = b->scope()->outer_scope();
  while (scope_a && scope_b) {
    std::unordered_map<int, Handle<String>> vars;
    for (Variable* var : *scope_a->locals()) {
      if (!var->IsContextSlot()) continue;
      vars[var->index()] = var->name();
    }
    for (Variable* var : *scope_b->locals()) {
      if (!var->IsContextSlot()) continue;
      auto it = vars.find(var->index());
      if (it == vars.end()) return true;
      if (*it->second != *var->name()) return true;
    }
    scope_a = scope_a->outer_scope();
    scope_b = scope_b->outer_scope();
  }
  return scope_a != scope_b;
}
References v8::internal::Scope::locals(), v8::internal::Scope::outer_scope(), and v8::internal::FunctionLiteral::scope().
Referenced by MapLiterals().
MapLiterals()
void v8::internal::anonymous_namespace{liveedit.cc}::MapLiterals (const FunctionLiteralChanges & changes, const std::vector< FunctionLiteral * > & new_literals, LiteralMap * unchanged, LiteralMap * changed)
Definition at line 443 of file liveedit.cc.
                                                             {
  // Track the top-level script function separately as it can overlap fully with
  // another function, e.g. the script "()=>42".
  const std::pair<int, int> kTopLevelMarker = std::make_pair(-1, -1);
  std::map<std::pair<int, int>, FunctionLiteral*> position_to_new_literal;
  for (FunctionLiteral* literal : new_literals) {
    DCHECK(literal->start_position() != kNoSourcePosition);
    DCHECK(literal->end_position() != kNoSourcePosition);
    std::pair<int, int> key =
        literal->function_literal_id() == kFunctionLiteralIdTopLevel
            ? kTopLevelMarker
            : std::make_pair(literal->start_position(),
                             literal->end_position());
    // Make sure there are no duplicate keys.
    DCHECK_EQ(position_to_new_literal.find(key), position_to_new_literal.end());
    position_to_new_literal[key] = literal;
  }
  LiteralMap mappings;
  std::unordered_map<FunctionLiteral*, ChangeState> change_state;
  for (const auto& change_pair : changes) {
    FunctionLiteral* literal = change_pair.first;
    const FunctionLiteralChange& change = change_pair.second;
    std::pair<int, int> key =
        literal->function_literal_id() == kFunctionLiteralIdTopLevel
            ? kTopLevelMarker
            : std::make_pair(change.new_start_position,
                             change.new_end_position);
    auto it = position_to_new_literal.find(key);
    if (it == position_to_new_literal.end() ||
        HasChangedScope(literal, it->second)) {
      change_state[literal] = ChangeState::DAMAGED;
      if (!change.outer_literal) continue;
      if (change_state[change.outer_literal] != ChangeState::DAMAGED) {
        change_state[change.outer_literal] = ChangeState::CHANGED;
      }
    } else {
      mappings[literal] = it->second;
      if (change_state.find(literal) == change_state.end()) {
        change_state[literal] =
            change.has_changes ? ChangeState::CHANGED : ChangeState::UNCHANGED;
      }
    }
  }
  for (const auto& mapping : mappings) {
    if (change_state[mapping.first] == ChangeState::UNCHANGED) {
      (*unchanged)[mapping.first] = mapping.second;
    } else if (change_state[mapping.first] == ChangeState::CHANGED) {
      (*changed)[mapping.first] = mapping.second;
    }
  }
}
References CHANGED, DAMAGED, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::FunctionLiteral::function_literal_id(), v8::internal::anonymous_namespace{liveedit.cc}::FunctionLiteralChange::has_changes, HasChangedScope(), v8::internal::key, v8::internal::kFunctionLiteralIdTopLevel, v8::internal::kNoSourcePosition, v8::internal::anonymous_namespace{liveedit.cc}::FunctionLiteralChange::new_end_position, v8::internal::anonymous_namespace{liveedit.cc}::FunctionLiteralChange::new_start_position, v8::internal::anonymous_namespace{liveedit.cc}::FunctionLiteralChange::outer_literal, and UNCHANGED.
Referenced by v8::internal::LiveEdit::PatchScript().
NarrowDownInput()
void v8::internal::anonymous_namespace{liveedit.cc}::NarrowDownInput (SubrangableInput * input, SubrangableOutput * output)
Definition at line 61 of file liveedit.cc.
                                                                         {
  const int len1 = input->GetLength1();
  const int len2 = input->GetLength2();
  int common_prefix_len;
  int common_suffix_len;
  {
    common_prefix_len = 0;
    int prefix_limit = std::min(len1, len2);
    while (common_prefix_len < prefix_limit &&
        input->Equals(common_prefix_len, common_prefix_len)) {
      common_prefix_len++;
    }
    common_suffix_len = 0;
    int suffix_limit =
        std::min(len1 - common_prefix_len, len2 - common_prefix_len);
    while (common_suffix_len < suffix_limit &&
        input->Equals(len1 - common_suffix_len - 1,
        len2 - common_suffix_len - 1)) {
      common_suffix_len++;
    }
  }
  if (common_prefix_len > 0 || common_suffix_len > 0) {
    int new_len1 = len1 - common_suffix_len - common_prefix_len;
    int new_len2 = len2 - common_suffix_len - common_prefix_len;
    input->SetSubrange1(common_prefix_len, new_len1);
    input->SetSubrange2(common_prefix_len, new_len2);
    output->SetSubrange1(common_prefix_len, new_len1);
    output->SetSubrange2(common_prefix_len, new_len2);
  }
}
References v8::internal::Comparator::Input::Equals(), v8::internal::Comparator::Input::GetLength1(), v8::internal::Comparator::Input::GetLength2(), v8::internal::anonymous_namespace{liveedit.cc}::SubrangableInput::SetSubrange1(), v8::internal::anonymous_namespace{liveedit.cc}::SubrangableOutput::SetSubrange1(), v8::internal::anonymous_namespace{liveedit.cc}::SubrangableInput::SetSubrange2(), and v8::internal::anonymous_namespace{liveedit.cc}::SubrangableOutput::SetSubrange2().
Referenced by v8::internal::LiveEdit::CompareStrings().
ParseScript()
bool v8::internal::anonymous_namespace{liveedit.cc}::ParseScript (Isolate * isolate, Handle< Script > script, ParseInfo * parse_info, MaybeDirectHandle< ScopeInfo > outer_scope_info, bool compile_as_well, std::vector< FunctionLiteral * > * literals, std::map< uint32_t, std::vector< uint32_t >> * eval_calls, debug::LiveEditResult * result)
Definition at line 531 of file liveedit.cc.
                                              {
  v8::TryCatch try_catch(reinterpret_cast<v8::Isolate*>(isolate));
  DirectHandle<SharedFunctionInfo> shared;
  bool success = false;
  if (compile_as_well) {
    success = Compiler::CompileForLiveEdit(parse_info, script, outer_scope_info,
                                           isolate)
                  .ToHandle(&shared);
  } else {
    success =
        parsing::ParseProgram(parse_info, script, outer_scope_info, isolate,
                              parsing::ReportStatisticsMode::kYes);
    if (!success) {
      // Throw the parser error.
      parse_info->pending_error_handler()->PrepareErrors(
          isolate, parse_info->ast_value_factory());
      parse_info->pending_error_handler()->ReportErrors(isolate, script);
    }
  }
  if (!success) {
    DCHECK(try_catch.HasCaught());
    result->message = try_catch.Message()->Get();
    i::DirectHandle<i::JSMessageObject> msg =
        Utils::OpenDirectHandle(*try_catch.Message());
    i::JSMessageObject::EnsureSourcePositionsAvailable(isolate, msg);
    result->line_number = msg->GetLineNumber();
    result->column_number = msg->GetColumnNumber();
    result->status = debug::LiveEditResult::COMPILE_ERROR;
    return false;
  }
  CollectFunctionLiterals(isolate, parse_info->literal())
      .Run(literals, eval_calls);
  return true;
}
References v8::internal::ParseInfo::ast_value_factory(), v8::debug::LiveEditResult::COMPILE_ERROR, v8::internal::Compiler::CompileForLiveEdit(), v8::internal::DCHECK(), v8::internal::JSMessageObject::EnsureSourcePositionsAvailable(), v8::TryCatch::HasCaught(), v8::internal::parsing::kYes, v8::internal::ParseInfo::literal(), v8::TryCatch::Message(), v8::Utils::OpenDirectHandle(), v8::internal::parsing::ParseProgram(), v8::internal::ParseInfo::pending_error_handler(), v8::internal::PendingCompilationErrorHandler::PrepareErrors(), v8::internal::PendingCompilationErrorHandler::ReportErrors(), v8::base::internal::result, v8::internal::anonymous_namespace{liveedit.cc}::CollectFunctionLiterals::Run(), and v8::internal::script.
Referenced by v8::internal::LiveEdit::PatchScript().
TranslateSourcePositionTable()
void v8::internal::anonymous_namespace{liveedit.cc}::TranslateSourcePositionTable (Isolate * isolate, DirectHandle< BytecodeArray > code, const std::vector< SourceChangeRange > & diffs)
Definition at line 747 of file liveedit.cc.
                                                                             {
  Zone zone(isolate->allocator(), ZONE_NAME);
  SourcePositionTableBuilder builder(&zone);
  DirectHandle<TrustedByteArray> source_position_table(
      code->SourcePositionTable(), isolate);
  for (SourcePositionTableIterator iterator(*source_position_table);
       !iterator.done(); iterator.Advance()) {
    SourcePosition position = iterator.source_position();
    position.SetScriptOffset(
        LiveEdit::TranslatePosition(diffs, position.ScriptOffset()));
    builder.AddPosition(iterator.code_offset(), position,
                        iterator.is_statement());
  }
  DirectHandle<TrustedByteArray> new_source_position_table(
      builder.ToSourcePositionTable(isolate));
  code->set_source_position_table(*new_source_position_table, kReleaseStore);
  LOG_CODE_EVENT(isolate,
                 CodeLinePosInfoRecordEvent(code->GetFirstBytecodeAddress(),
                                            *new_source_position_table,
                                            JitCodeEvent::BYTE_CODE));
}
References v8::internal::SourcePositionTableBuilder::AddPosition(), v8::internal::Isolate::allocator(), v8::JitCodeEvent::BYTE_CODE, code, v8::internal::SourcePositionTableIterator::done(), v8::kReleaseStore, LOG_CODE_EVENT, v8::internal::SourcePosition::ScriptOffset(), v8::internal::SourcePosition::SetScriptOffset(), v8::internal::SourcePositionTableBuilder::ToSourcePositionTable(), v8::internal::LiveEdit::TranslatePosition(), and ZONE_NAME.
Referenced by UpdatePositions().
UpdatePositions()
void v8::internal::anonymous_namespace{liveedit.cc}::UpdatePositions (Isolate * isolate, DirectHandle< SharedFunctionInfo > sfi, FunctionLiteral * new_function, const std::vector< SourceChangeRange > & diffs)
Definition at line 773 of file liveedit.cc.
                                                                {
  sfi->UpdateFromFunctionLiteralForLiveEdit(isolate, new_function);
  if (sfi->HasBytecodeArray()) {
    TranslateSourcePositionTable(
        isolate, direct_handle(sfi->GetBytecodeArray(isolate), isolate), diffs);
  }
}
References v8::internal::direct_handle(), and TranslateSourcePositionTable().
Referenced by v8::internal::LiveEdit::PatchScript().