v8::internal::compiler::anonymous_namespace{code-generator-arm64.cc} Namespace Reference
Classes
class OutOfLineRecordWrite
Functions
Condition FlagsConditionToCondition (FlagsCondition condition)
void RecordTrapInfoIfNeeded (Zone *zone, CodeGenerator *codegen, InstructionCode opcode, Instruction *instr, int pc)
template<typename Fn >
void EmitFpOrNeonUnop (MacroAssembler *masm, Fn fn, Instruction *instr, Arm64OperandConverter i, VectorFormat scalar, VectorFormat vector)
void AdjustStackPointerForTailCall (MacroAssembler *masm, FrameAccessState *state, int new_slot_above_sp, bool allow_shrinkage=true)
Function Documentation
AdjustStackPointerForTailCall()
void v8::internal::compiler::anonymous_namespace{code-generator-arm64.cc}::AdjustStackPointerForTailCall (MacroAssembler * masm, FrameAccessState * state, int new_slot_above_sp, bool allow_shrinkage = true)
Definition at line 706 of file code-generator-arm64.cc.
                                                                {
  int current_sp_offset = state->GetSPToFPSlotCount() +
                          StandardFrameConstants::kFixedSlotCountAboveFp;
  int stack_slot_delta = new_slot_above_sp - current_sp_offset;
  DCHECK_EQ(stack_slot_delta % 2, 0);
  if (stack_slot_delta > 0) {
    masm->Claim(stack_slot_delta);
    state->IncreaseSPDelta(stack_slot_delta);
  } else if (allow_shrinkage && stack_slot_delta < 0) {
    masm->Drop(-stack_slot_delta);
    state->IncreaseSPDelta(stack_slot_delta);
  }
}
References v8::internal::MacroAssembler::Claim(), DCHECK_EQ, v8::internal::MacroAssembler::Drop(), v8::internal::compiler::FrameAccessState::GetSPToFPSlotCount(), v8::internal::compiler::FrameAccessState::IncreaseSPDelta(), and v8::internal::CommonFrameConstants::kFixedSlotCountAboveFp.
EmitFpOrNeonUnop()
template<typename Fn >
void v8::internal::compiler::anonymous_namespace{code-generator-arm64.cc}::EmitFpOrNeonUnop (MacroAssembler * masm, Fn fn, Instruction * instr, Arm64OperandConverter i, VectorFormat scalar, VectorFormat vector)
Definition at line 489 of file code-generator-arm64.cc.
                                           {
  VectorFormat f = instr->InputAt(0)->IsSimd128Register() ? vector : scalar;
  VRegister output = VRegister::Create(i.OutputDoubleRegister().code(), f);
  VRegister input = VRegister::Create(i.InputDoubleRegister(0).code(), f);
  (masm->*fn)(output, input);
}
References v8::internal::VRegister::Create(), v8::internal::compiler::Instruction::InputAt(), and v8::internal::compiler::InstructionOperand::IsSimd128Register().
FlagsConditionToCondition()
Condition v8::internal::compiler::anonymous_namespace{code-generator-arm64.cc}::FlagsConditionToCondition (FlagsCondition condition)
Definition at line 386 of file code-generator-arm64.cc.
                                                              {
  switch (condition) {
    case kEqual:
      return eq;
    case kNotEqual:
      return ne;
    case kSignedLessThan:
      return lt;
    case kSignedGreaterThanOrEqual:
      return ge;
    case kSignedLessThanOrEqual:
      return le;
    case kSignedGreaterThan:
      return gt;
    case kUnsignedLessThan:
      return lo;
    case kUnsignedGreaterThanOrEqual:
      return hs;
    case kUnsignedLessThanOrEqual:
      return ls;
    case kUnsignedGreaterThan:
      return hi;
    case kFloatLessThanOrUnordered:
      return lt;
    case kFloatGreaterThanOrEqual:
      return ge;
    case kFloatLessThanOrEqual:
      return ls;
    case kFloatGreaterThanOrUnordered:
      return hi;
    case kFloatLessThan:
      return lo;
    case kFloatGreaterThanOrEqualOrUnordered:
      return hs;
    case kFloatLessThanOrEqualOrUnordered:
      return le;
    case kFloatGreaterThan:
      return gt;
    case kOverflow:
      return vs;
    case kNotOverflow:
      return vc;
    case kUnorderedEqual:
    case kUnorderedNotEqual:
    case kIsNaN:
    case kIsNotNaN:
      break;
    case kPositiveOrZero:
      return pl;
    case kNegative:
      return mi;
  }
  UNREACHABLE();
}
References v8::internal::eq, v8::internal::ge, v8::internal::gt, v8::internal::hi, v8::internal::hs, v8::internal::compiler::kEqual, v8::internal::compiler::kFloatGreaterThan, v8::internal::compiler::kFloatGreaterThanOrEqual, v8::internal::compiler::kFloatGreaterThanOrEqualOrUnordered, v8::internal::compiler::kFloatGreaterThanOrUnordered, v8::internal::compiler::kFloatLessThan, v8::internal::compiler::kFloatLessThanOrEqual, v8::internal::compiler::kFloatLessThanOrEqualOrUnordered, v8::internal::compiler::kFloatLessThanOrUnordered, v8::internal::compiler::kIsNaN, v8::internal::compiler::kIsNotNaN, v8::internal::compiler::kNegative, v8::internal::compiler::kNotEqual, v8::internal::compiler::kNotOverflow, v8::internal::compiler::kOverflow, v8::internal::compiler::kPositiveOrZero, v8::internal::compiler::kSignedGreaterThan, v8::internal::compiler::kSignedGreaterThanOrEqual, v8::internal::compiler::kSignedLessThan, v8::internal::compiler::kSignedLessThanOrEqual, v8::internal::compiler::kUnorderedEqual, v8::internal::compiler::kUnorderedNotEqual, v8::internal::compiler::kUnsignedGreaterThan, v8::internal::compiler::kUnsignedGreaterThanOrEqual, v8::internal::compiler::kUnsignedLessThan, v8::internal::compiler::kUnsignedLessThanOrEqual, v8::internal::le, v8::internal::lo, v8::internal::ls, v8::internal::lt, v8::internal::mi, v8::internal::ne, v8::internal::pl, v8::internal::UNREACHABLE(), v8::internal::vc, and v8::internal::vs.
RecordTrapInfoIfNeeded()
void v8::internal::compiler::anonymous_namespace{code-generator-arm64.cc}::RecordTrapInfoIfNeeded (Zone * zone, CodeGenerator * codegen, InstructionCode opcode, Instruction * instr, int pc)
Definition at line 480 of file code-generator-arm64.cc.
                                    {
  DCHECK_EQ(kMemoryAccessDirect, AccessModeField::decode(opcode));
}
References DCHECK_EQ, v8::base::BitField< T, shift, size, U >::decode(), and v8::internal::compiler::kMemoryAccessDirect.