v8::internal::anonymous_namespace{constants-table-builder.cc} Namespace Reference
Functions
void CheckPreconditionsForPatching (Isolate *isolate, Handle< Object > replacement_object)
Function Documentation
CheckPreconditionsForPatching()
void v8::internal::anonymous_namespace{constants-table-builder.cc}::CheckPreconditionsForPatching (Isolate * isolate, Handle< Object > replacement_object)
Definition at line 70 of file constants-table-builder.cc.
                                                                      {
  // Roots must not be inserted into the constants table as they are already
  // accessible from the root list.
  RootIndex root_list_index;
  DCHECK(!isolate->roots_table().IsRootHandle(replacement_object,
                                              &root_list_index));
  USE(root_list_index);
  // Not yet finalized.
  DCHECK_EQ(ReadOnlyRoots(isolate).empty_fixed_array(),
            isolate->heap()->builtins_constants_table());
  DCHECK(isolate->IsGeneratingEmbeddedBuiltins());
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Isolate::heap(), v8::internal::Isolate::IsGeneratingEmbeddedBuiltins(), v8::internal::RootsTable::IsRootHandle(), v8::internal::Isolate::roots_table(), and USE.
Referenced by v8::internal::BuiltinsConstantsTableBuilder::PatchBasicBlockCountersReference(), and v8::internal::BuiltinsConstantsTableBuilder::PatchSelfReference().