v8::internal::anonymous_namespace{v8.cc} Namespace Reference
Enumerations
enum class V8StartupState {
kIdle
, kPlatformInitializing
, kPlatformInitialized
, kV8Initializing
,
kV8Initialized
, kV8Disposing
, kV8Disposed
, kPlatformDisposing
,
kPlatformDisposed
 }
Functions
std::atomic< V8StartupState > v8_startup_state_ (V8StartupState::kIdle)
void AdvanceStartupState (V8StartupState expected_next_state)
Enumeration Type Documentation
V8StartupState
enum v8::internal::anonymous_namespace{v8.cc}::V8StartupState [strong]
Enumerator
kIdle
kPlatformInitializing
kPlatformInitialized
kV8Initializing
kV8Initialized
kV8Disposing
kV8Disposed
kPlatformDisposing
kPlatformDisposed
Definition at line 55 of file v8.cc.
                          {
  kIdle,
  kPlatformInitializing,
  kPlatformInitialized,
  kV8Initializing,
  kV8Initialized,
  kV8Disposing,
  kV8Disposed,
  kPlatformDisposing,
  kPlatformDisposed
};
Function Documentation
AdvanceStartupState()
void v8::internal::anonymous_namespace{v8.cc}::AdvanceStartupState (V8StartupState expected_next_state)
Definition at line 69 of file v8.cc.
                                                             {
  V8StartupState current_state = v8_startup_state_;
  CHECK_NE(current_state, V8StartupState::kPlatformDisposed);
  V8StartupState next_state =
      static_cast<V8StartupState>(static_cast<int>(current_state) + 1);
  if (next_state != expected_next_state) {
    // Ensure the following order:
    // v8::V8::InitializePlatform(platform);
    // v8::V8::Initialize();
    // v8::Isolate* isolate = v8::Isolate::New(...);
    // ...
    // isolate->Dispose();
    // v8::V8::Dispose();
    // v8::V8::DisposePlatform();
    FATAL("Wrong initialization order: from %d to %d, expected to %d!",
          static_cast<int>(current_state), static_cast<int>(next_state),
          static_cast<int>(expected_next_state));
  }
  if (!v8_startup_state_.compare_exchange_strong(current_state, next_state)) {
    FATAL(
        "Multiple threads are initializating V8 in the wrong order: expected "
        "%d got %d!",
        static_cast<int>(current_state),
        static_cast<int>(v8_startup_state_.load()));
  }
}
References CHECK_NE, FATAL, and v8_startup_state_().
Referenced by v8::internal::V8::Dispose(), v8::internal::V8::DisposePlatform(), v8::internal::V8::Initialize(), and v8::internal::V8::InitializePlatform().
v8_startup_state_()
std::atomic<V8StartupState> v8::internal::anonymous_namespace{v8.cc}::v8_startup_state_ (V8StartupState::kIdle)
Referenced by AdvanceStartupState(), and v8::internal::V8::InitializePlatformForTesting().