v8::internal::anonymous_namespace{debug-wasm-objects.cc} Namespace Reference
Classes
struct IndexedDebugProxy
struct NamedDebugProxy
struct FunctionsProxy
struct GlobalsProxy
struct MemoriesProxy
struct TablesProxy
struct LocalsProxy
struct StackProxy
class ContextProxyPrototype
class ContextProxy
class DebugWasmScopeIterator
Typedefs
using StringBuilder = wasm::StringBuilder
Enumerations
enum DebugProxyId {
kFunctionsProxy
, kGlobalsProxy
, kMemoriesProxy
, kTablesProxy
,
kLastInstanceProxyId = kTablesProxy
, kContextProxy
, kLocalsProxy
, kStackProxy
,
kStructProxy
, kArrayProxy
, kLastProxyId = kArrayProxy
, kNumProxies = kLastProxyId + 1
,
kNumInstanceProxies = kLastInstanceProxyId + 1
 }
Functions
DirectHandle< String > ToInternalString (StringBuilder &sb, Isolate *isolate)
DirectHandle< FixedArray > GetOrCreateDebugMaps (Isolate *isolate)
DirectHandle< Map > GetOrCreateDebugProxyMap (Isolate *isolate, DebugProxyId id, v8::Local< v8::FunctionTemplate >(*create_template_fn)(v8::Isolate *), bool make_non_extensible=true)
DirectHandle< FixedArray > GetOrCreateInstanceProxyCache (Isolate *isolate, DirectHandle< WasmInstanceObject > instance)
template<typename Proxy >
DirectHandle< JSObject > GetOrCreateInstanceProxy (Isolate *isolate, DirectHandle< WasmInstanceObject > instance)
DirectHandle< String > WasmSimd128ToString (Isolate *isolate, Simd128 s128)
DirectHandle< String > GetRefTypeName (Isolate *isolate, wasm::CanonicalValueType type)
Variables
constexpr int kWasmValueMapIndex = kNumProxies
constexpr int kNumDebugMaps = kWasmValueMapIndex + 1
Typedef Documentation
StringBuilder
using v8::internal::anonymous_namespace{debug-wasm-objects.cc}::StringBuilder = typedef wasm::StringBuilder
Definition at line 30 of file debug-wasm-objects.cc.
Enumeration Type Documentation
DebugProxyId
enum v8::internal::anonymous_namespace{debug-wasm-objects.cc}::DebugProxyId
Enumerator
kFunctionsProxy
kGlobalsProxy
kMemoriesProxy
kTablesProxy
kLastInstanceProxyId
kContextProxy
kLocalsProxy
kStackProxy
kStructProxy
kArrayProxy
kLastProxyId
kNumProxies
kNumInstanceProxies
Definition at line 36 of file debug-wasm-objects.cc.
                  {
  kFunctionsProxy,
  kGlobalsProxy,
  kMemoriesProxy,
  kTablesProxy,
  kLastInstanceProxyId = kTablesProxy,
  kContextProxy,
  kLocalsProxy,
  kStackProxy,
  kStructProxy,
  kArrayProxy,
  kLastProxyId = kArrayProxy,
  kNumProxies = kLastProxyId + 1,
  kNumInstanceProxies = kLastInstanceProxyId + 1
};
Function Documentation
GetOrCreateDebugMaps()
DirectHandle<FixedArray> v8::internal::anonymous_namespace{debug-wasm-objects.cc}::GetOrCreateDebugMaps (Isolate * isolate)
Definition at line 57 of file debug-wasm-objects.cc.
                                                                {
  DirectHandle<FixedArray> maps = isolate->wasm_debug_maps();
  if (maps->length() == 0) {
    maps = isolate->factory()->NewFixedArrayWithHoles(kNumDebugMaps);
    isolate->native_context()->set_wasm_debug_maps(*maps);
  }
  return maps;
}
References v8::internal::Isolate::factory(), kNumDebugMaps, v8::internal::Isolate::native_context(), and v8::internal::FactoryBase< Impl >::NewFixedArrayWithHoles().
Referenced by GetOrCreateDebugProxyMap(), and v8::internal::WasmValueObject::New().
GetOrCreateDebugProxyMap()
DirectHandle<Map> v8::internal::anonymous_namespace{debug-wasm-objects.cc}::GetOrCreateDebugProxyMap (Isolate * isolate, DebugProxyId id, v8::Local< v8::FunctionTemplate >(*)(v8::Isolate *) create_template_fn, bool make_non_extensible = true)
Definition at line 72 of file debug-wasm-objects.cc.
                                     {
  auto maps = GetOrCreateDebugMaps(isolate);
  CHECK_LE(kNumProxies, maps->length());
  if (!maps->is_the_hole(isolate, id)) {
    return direct_handle(Cast<Map>(maps->get(id)), isolate);
  }
  auto tmp = (*create_template_fn)(reinterpret_cast<v8::Isolate*>(isolate));
  auto fun =
      ApiNatives::InstantiateFunction(isolate, Utils::OpenDirectHandle(*tmp))
          .ToHandleChecked();
  auto map = JSFunction::GetDerivedMap(isolate, fun, fun).ToHandleChecked();
  Map::SetPrototype(isolate, map, isolate->factory()->null_value());
  if (make_non_extensible) {
    map->set_is_extensible(false);
  }
  maps->set(id, *map);
  return map;
}
References CHECK_LE, v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::JSFunction::GetDerivedMap(), GetOrCreateDebugMaps(), v8::internal::ApiNatives::InstantiateFunction(), kNumProxies, v8::Utils::OpenDirectHandle(), and v8::internal::Map::SetPrototype().
Referenced by v8::internal::anonymous_namespace{debug-wasm-objects.cc}::ContextProxyPrototype::Create(), and v8::internal::anonymous_namespace{debug-wasm-objects.cc}::IndexedDebugProxy< T, id, Provider >::Create().
GetOrCreateInstanceProxy()
template<typename Proxy >
DirectHandle<JSObject> v8::internal::anonymous_namespace{debug-wasm-objects.cc}::GetOrCreateInstanceProxy (Isolate * isolate, DirectHandle< WasmInstanceObject > instance)
Definition at line 505 of file debug-wasm-objects.cc.
                                                                 {
  static_assert(Proxy::kId < kNumInstanceProxies);
  DirectHandle<FixedArray> proxies =
      GetOrCreateInstanceProxyCache(isolate, instance);
  if (!proxies->is_the_hole(isolate, Proxy::kId)) {
    return direct_handle(Cast<JSObject>(proxies->get(Proxy::kId)), isolate);
  }
  DirectHandle<JSObject> proxy = Proxy::Create(isolate, instance);
  proxies->set(Proxy::kId, *proxy);
  return proxy;
}
References v8::internal::direct_handle(), GetOrCreateInstanceProxyCache(), v8_inspector::anonymous_namespace{v8-stack-trace-impl.cc}::kId, and kNumInstanceProxies.
GetOrCreateInstanceProxyCache()
DirectHandle<FixedArray> v8::internal::anonymous_namespace{debug-wasm-objects.cc}::GetOrCreateInstanceProxyCache (Isolate * isolate, DirectHandle< WasmInstanceObject > instance)
Definition at line 489 of file debug-wasm-objects.cc.
                                                                 {
  DirectHandle<Object> cache;
  DirectHandle<Symbol> symbol =
      isolate->factory()->wasm_debug_proxy_cache_symbol();
  if (!Object::GetProperty(isolate, instance, symbol).ToHandle(&cache) ||
      IsUndefined(*cache, isolate)) {
    cache = isolate->factory()->NewFixedArrayWithHoles(kNumInstanceProxies);
    Object::SetProperty(isolate, instance, symbol, cache).Check();
  }
  return Cast<FixedArray>(cache);
}
References v8::internal::Isolate::factory(), v8::internal::Object::GetProperty(), kNumInstanceProxies, v8::internal::FactoryBase< Impl >::NewFixedArrayWithHoles(), v8::internal::Object::SetProperty(), and v8::anonymous_namespace{api.cc}::ToHandle().
Referenced by GetOrCreateInstanceProxy().
GetRefTypeName()
DirectHandle<String> v8::internal::anonymous_namespace{debug-wasm-objects.cc}::GetRefTypeName (Isolate * isolate, wasm::CanonicalValueType type)
Definition at line 857 of file debug-wasm-objects.cc.
                                                                 {
  StringBuilder name;
  wasm::GetCanonicalTypeNamesProvider()->PrintValueType(name, type);
  return ToInternalString(name, isolate);
}
References v8::internal::wasm::GetCanonicalTypeNamesProvider(), v8::internal::name, v8::internal::wasm::CanonicalTypeNamesProvider::PrintValueType(), ToInternalString(), and v8::internal::tracing::type.
Referenced by v8::internal::WasmValueObject::New().
ToInternalString()
DirectHandle<String> v8::internal::anonymous_namespace{debug-wasm-objects.cc}::ToInternalString (StringBuilder & sb, Isolate * isolate)
Definition at line 31 of file debug-wasm-objects.cc.
                                                                           {
  return isolate->factory()->InternalizeString(
      base::VectorOf(sb.start(), sb.length()));
}
References v8::internal::Isolate::factory(), v8::internal::Factory::InternalizeString(), v8::internal::wasm::StringBuilder::length(), v8::internal::wasm::StringBuilder::start(), and v8::base::VectorOf().
Referenced by v8::internal::anonymous_namespace{debug-wasm-objects.cc}::LocalsProxy::GetName(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::GlobalsProxy::GetName(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::MemoriesProxy::GetName(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::TablesProxy::GetName(), v8::internal::StructProxy::GetName(), GetRefTypeName(), and v8::internal::GetWasmFunctionDebugName().
WasmSimd128ToString()
DirectHandle<String> v8::internal::anonymous_namespace{debug-wasm-objects.cc}::WasmSimd128ToString (Isolate * isolate, Simd128 s128)
Definition at line 847 of file debug-wasm-objects.cc.
                                                                         {
  // We use the canonical format as described in:
  // https://github.com/WebAssembly/simd/blob/master/proposals/simd/TextSIMD.md
  base::EmbeddedVector<char, 50> buffer;
  auto i32x4 = s128.to_i32x4();
  SNPrintF(buffer, "i32x4 0x%08X 0x%08X 0x%08X 0x%08X", i32x4.val[0],
           i32x4.val[1], i32x4.val[2], i32x4.val[3]);
  return isolate->factory()->NewStringFromAsciiChecked(buffer.data());
}
References v8::base::Vector< T >::data(), v8::internal::Isolate::factory(), v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), and v8::base::SNPrintF().
Referenced by v8::internal::WasmValueObject::New().
Variable Documentation
kNumDebugMaps
constexpr int v8::internal::anonymous_namespace{debug-wasm-objects.cc}::kNumDebugMaps = kWasmValueMapIndex + 1 [constexpr]
Definition at line 55 of file debug-wasm-objects.cc.
Referenced by GetOrCreateDebugMaps().
kWasmValueMapIndex
constexpr int v8::internal::anonymous_namespace{debug-wasm-objects.cc}::kWasmValueMapIndex = kNumProxies [constexpr]
Definition at line 54 of file debug-wasm-objects.cc.
Referenced by v8::internal::WasmValueObject::New().