v8::internal::libvtune Namespace Reference
Functions
int startTask (const std::vector< std::string > &vparams)
int endTask (const std::vector< std::string > &vparams)
void split (const std::string &str, char delimiter, std::vector< std::string > *vparams)
int invoke (const char *params)
Variables
const auto & function_map
Function Documentation
endTask()
int v8::internal::libvtune::endTask (const std::vector< std::string > & vparams)
Definition at line 64 of file vtunedomain-support-extension.cc.
                                                 {
  int errcode = 0;
  if (const char* domain_name = vparams[1].c_str()) {
    if (std::shared_ptr<VTuneDomain> domainptr =
            VTuneDomain::createDomain(domain_name)) {
      domainptr->endTask();
    } else {
      errcode += CREATE_DOMAIN_FAILED;
    }
  } else {
    errcode = NO_DOMAIN_NAME;
  }
  return errcode;
}
References CREATE_DOMAIN_FAILED, and NO_DOMAIN_NAME.
invoke()
int v8::internal::libvtune::invoke (const char * params)
Definition at line 81 of file vtunedomain-support-extension.cc.
                               {
  int errcode = 0;
  std::vector<std::string> vparams;
  split(*(new std::string(params)), ' ', &vparams);
  auto it = function_map.find(vparams[0]);
  if (it != function_map.end()) {
    (it->second)(vparams);
  } else {
    errcode += UNKNOWN_PARAMS;
  }
  return errcode;
}
References function_map, split(), v8::internal::string, and UNKNOWN_PARAMS.
Referenced by v8::CreateEnvironment(), v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_JSEntryVariant(), and v8::internal::VTuneDomainSupportExtension::Mark().
split()
void v8::internal::libvtune::split (const std::string & str, char delimiter, std::vector< std::string > * vparams)
Definition at line 25 of file vtunedomain-support-extension.cc.
                                          {
  std::string::size_type baseindex = 0;
  std::string::size_type offindex = str.find(delimiter);
  while (offindex != std::string::npos) {
    (*vparams).push_back(str.substr(baseindex, offindex - baseindex));
    baseindex = ++offindex;
    offindex = str.find(delimiter, offindex);
    if (offindex == std::string::npos)
      (*vparams).push_back(str.substr(baseindex, str.length()));
  }
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GenerateBrTable(), invoke(), v8::internal::anonymous_namespace{map-updater.cc}::PrintGeneralization(), v8::internal::compiler::LinearScanAllocator::ReloadLiveRanges(), v8::internal::compiler::LinearScanAllocator::SpillNotLiveRanges(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::split(), v8::internal::maglev::BasicBlock::Split(), v8_inspector::protocol::anonymous_namespace{string-util.cc}::SplitByte(), v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::SplitRangeByReservationsIfNeeded(), and v8_inspector::protocol::Binary::toBase64().
startTask()
int v8::internal::libvtune::startTask (const std::vector< std::string > & vparams)
Definition at line 40 of file vtunedomain-support-extension.cc.
                                                   {
  int errcode = 0;
  if (const char* domain_name = vparams[1].c_str()) {
    if (const char* task_name = vparams[2].c_str()) {
      if (std::shared_ptr<VTuneDomain> domainptr =
              VTuneDomain::createDomain(domain_name)) {
        if (!domainptr->beginTask(task_name)) {
          errcode += TASK_BEGIN_FAILED;
        }
      } else {
        errcode += CREATE_DOMAIN_FAILED;
      }
    } else {
      errcode += NO_TASK_NAME;
    }
  } else {
    errcode = NO_DOMAIN_NAME;
  }
  return errcode;
}
References CREATE_DOMAIN_FAILED, NO_DOMAIN_NAME, NO_TASK_NAME, and TASK_BEGIN_FAILED.
Variable Documentation
function_map
const auto& v8::internal::libvtune::function_map
Initial value:
=
    *new std::map<std::string, int (*)(const std::vector<std::string>&)>{
        {"start", startTask}, {"end", endTask}}
Definition at line 21 of file vtunedomain-support-extension.cc.
Referenced by v8::internal::Map::AsLanguageMode(), v8::internal::WasmJs::InstallTypeReflection(), invoke(), v8::internal::WasmExportedFunction::New(), v8::internal::WasmJs::PrepareForSnapshot(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateClosure(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSFindNonDefaultConstructorOrConstruct(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSGetSuperConstructor(), v8::internal::RUNTIME_FUNCTION(), v8::internal::TF_BUILTIN(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildFindNonDefaultConstructorOrConstruct().