v8::internal::torque::anonymous_namespace{instructions.cc} Namespace Reference
Functions
void ExpectType (const Type *expected, const Type *actual)
void ExpectSubtype (const Type *subtype, const Type *supertype)
Function Documentation
ExpectSubtype()
void v8::internal::torque::anonymous_namespace{instructions.cc}::ExpectSubtype (const Type * subtype, const Type * supertype)
Definition at line 31 of file instructions.cc.
                                                               {
  if (!subtype->IsSubtypeOf(supertype)) {
    ReportError("type ", *subtype, " is not a subtype of ", *supertype);
  }
}
References v8::internal::torque::Type::IsSubtypeOf(), and v8::internal::torque::ReportError().
ExpectType()
void v8::internal::torque::anonymous_namespace{instructions.cc}::ExpectType (const Type * expected, const Type * actual)
Definition at line 26 of file instructions.cc.
                                                          {
  if (expected != actual) {
    ReportError("expected type ", *expected, " but found ", *actual);
  }
}
References v8::internal::torque::ReportError().