v8::internal::anonymous_namespace{property-descriptor.cc} Namespace Reference
Functions
bool GetPropertyIfPresent (Isolate *isolate, DirectHandle< JSReceiver > receiver, DirectHandle< String > name, Handle< JSAny > *value)
bool ToPropertyDescriptorFastPath (Isolate *isolate, DirectHandle< JSReceiver > obj, PropertyDescriptor *desc)
void CreateDataProperty (Isolate *isolate, DirectHandle< JSObject > object, Handle< String > name, DirectHandle< Object > value)
Function Documentation
CreateDataProperty()
void v8::internal::anonymous_namespace{property-descriptor.cc}::CreateDataProperty (Isolate * isolate, DirectHandle< JSObject > object, Handle< String > name, DirectHandle< Object > value)
Definition at line 123 of file property-descriptor.cc.
                                                                         {
  Maybe<bool> result = JSObject::CreateDataProperty(
      isolate, object, PropertyKey(isolate, Cast<Name>(name)), value);
  CHECK(result.IsJust() && result.FromJust());
}
References CHECK, v8::internal::JSObject::CreateDataProperty(), v8::internal::name, v8::base::internal::result, and v8::internal::value.
Referenced by v8_inspector::generateCustomPreview(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::InstantiateBytesResultResolver::OnInstantiationSucceeded(), and v8::internal::PropertyDescriptor::ToObject().
GetPropertyIfPresent()
bool v8::internal::anonymous_namespace{property-descriptor.cc}::GetPropertyIfPresent (Isolate * isolate, DirectHandle< JSReceiver > receiver, DirectHandle< String > name, Handle< JSAny > * value)
Definition at line 24 of file property-descriptor.cc.
                                                                           {
  LookupIterator it(isolate, receiver, name, receiver);
  // 4. Let hasEnumerable be HasProperty(Obj, "enumerable").
  Maybe<bool> has_property = JSReceiver::HasProperty(&it);
  // 5. ReturnIfAbrupt(hasEnumerable).
  if (has_property.IsNothing()) return false;
  // 6. If hasEnumerable is true, then
  if (has_property.FromJust() == true) {
    // 6a. Let enum be ToBoolean(Get(Obj, "enumerable")).
    // 6b. ReturnIfAbrupt(enum).
    if (!Cast<JSAny>(Object::GetProperty(&it)).ToHandle(value)) return false;
  }
  return true;
}
References v8::Maybe< T >::FromJust(), v8::internal::Object::GetProperty(), v8::internal::JSReceiver::HasProperty(), v8::Maybe< T >::IsNothing(), v8::internal::name, v8::anonymous_namespace{api.cc}::ToHandle(), and v8::internal::value.
Referenced by v8::internal::PropertyDescriptor::ToPropertyDescriptor().
ToPropertyDescriptorFastPath()
bool v8::internal::anonymous_namespace{property-descriptor.cc}::ToPropertyDescriptorFastPath (Isolate * isolate, DirectHandle< JSReceiver > obj, PropertyDescriptor * desc)
Definition at line 44 of file property-descriptor.cc.
                                                            {
  {
    DisallowGarbageCollection no_gc;
    Tagged<JSReceiver> raw_obj = *obj;
    if (!IsJSObject(*raw_obj)) return false;
    Tagged<Map> raw_map = raw_obj->map(isolate);
    if (raw_map->instance_type() != JS_OBJECT_TYPE) return false;
    if (raw_map->is_access_check_needed()) return false;
    if (raw_map->prototype() != *isolate->initial_object_prototype())
      return false;
    // During bootstrapping, the object_function_prototype_map hasn't been
    // set up yet.
    if (isolate->bootstrapper()->IsActive()) return false;
    if (Cast<JSObject>(raw_map->prototype())->map() !=
        isolate->raw_native_context()->object_function_prototype_map()) {
      return false;
    }
    // TODO(jkummerow): support dictionary properties?
    if (raw_map->is_dictionary_map()) return false;
  }
  DirectHandle<Map> map(obj->map(isolate), isolate);
  DirectHandle<DescriptorArray> descs(map->instance_descriptors(isolate),
                                      isolate);
  ReadOnlyRoots roots(isolate);
  for (InternalIndex i : map->IterateOwnDescriptors()) {
    PropertyDetails details = descs->GetDetails(i);
    DirectHandle<Object> value;
    if (details.location() == PropertyLocation::kField) {
      if (details.kind() == PropertyKind::kData) {
        value = JSObject::FastPropertyAt(isolate, Cast<JSObject>(obj),
                                         details.representation(),
                                         FieldIndex::ForDetails(*map, details));
      } else {
        DCHECK_EQ(PropertyKind::kAccessor, details.kind());
        // Bail out to slow path.
        return false;
      }
    } else {
      DCHECK_EQ(PropertyLocation::kDescriptor, details.location());
      if (details.kind() == PropertyKind::kData) {
        value = direct_handle(descs->GetStrongValue(i), isolate);
      } else {
        DCHECK_EQ(PropertyKind::kAccessor, details.kind());
        // Bail out to slow path.
        return false;
      }
    }
    Tagged<Name> key = descs->GetKey(i);
    if (key == roots.enumerable_string()) {
      desc->set_enumerable(Object::BooleanValue(*value, isolate));
    } else if (key == roots.configurable_string()) {
      desc->set_configurable(Object::BooleanValue(*value, isolate));
    } else if (key == roots.value_string()) {
      desc->set_value(Cast<JSAny>(value));
    } else if (key == roots.writable_string()) {
      desc->set_writable(Object::BooleanValue(*value, isolate));
    } else if (key == roots.get_string()) {
      // Bail out to slow path to throw an exception if necessary.
      if (!IsCallable(*value)) return false;
      desc->set_get(Cast<JSAny>(value));
    } else if (key == roots.set_string()) {
      // Bail out to slow path to throw an exception if necessary.
      if (!IsCallable(*value)) return false;
      desc->set_set(Cast<JSAny>(value));
    }
  }
  if ((desc->has_get() || desc->has_set()) &&
      (desc->has_value() || desc->has_writable())) {
    // Bail out to slow path to throw an exception.
    return false;
  }
  return true;
}
References v8::internal::Object::BooleanValue(), v8::internal::Isolate::bootstrapper(), DCHECK_EQ, v8::internal::direct_handle(), v8::internal::JSObject::FastPropertyAt(), v8::internal::FieldIndex::ForDetails(), v8::internal::PropertyDescriptor::has_get(), v8::internal::PropertyDescriptor::has_set(), v8::internal::PropertyDescriptor::has_value(), v8::internal::PropertyDescriptor::has_writable(), v8::internal::Bootstrapper::IsActive(), v8::internal::kAccessor, v8::internal::kData, v8::internal::kDescriptor, v8::internal::key, v8::internal::kField, v8::internal::PropertyDetails::kind(), v8::internal::PropertyDetails::location(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Isolate::raw_native_context(), v8::internal::PropertyDetails::representation(), v8::internal::PropertyDescriptor::set_configurable(), v8::internal::PropertyDescriptor::set_enumerable(), v8::internal::PropertyDescriptor::set_get(), v8::internal::PropertyDescriptor::set_set(), v8::internal::PropertyDescriptor::set_value(), v8::internal::PropertyDescriptor::set_writable(), and v8::internal::value.
Referenced by v8::internal::PropertyDescriptor::ToPropertyDescriptor().