v8::internal::compiler::anonymous_namespace{js-generic-lowering.cc} Namespace Reference
Functions
CallDescriptor::Flags FrameStateFlagForCall (Node *node)
bool ShouldUseMegamorphicAccessBuiltin (FeedbackSource const &source, OptionalNameRef name, AccessMode mode, JSHeapBroker *broker)
Function Documentation
FrameStateFlagForCall()
CallDescriptor::Flags v8::internal::compiler::anonymous_namespace{js-generic-lowering.cc}::FrameStateFlagForCall (Node * node)
Definition at line 29 of file js-generic-lowering.cc.
                                                      {
  return OperatorProperties::HasFrameStateInput(node->op())
             ? CallDescriptor::kNeedsFrameState
             : CallDescriptor::kNoFlags;
}
References v8::internal::compiler::OperatorProperties::HasFrameStateInput(), v8::internal::compiler::CallDescriptor::kNeedsFrameState, v8::internal::compiler::CallDescriptor::kNoFlags, and v8::internal::compiler::Node::op().
Referenced by v8::internal::compiler::JSGenericLowering::ReplaceWithBuiltinCall().
ShouldUseMegamorphicAccessBuiltin()
bool v8::internal::compiler::anonymous_namespace{js-generic-lowering.cc}::ShouldUseMegamorphicAccessBuiltin (FeedbackSource const & source, OptionalNameRef name, AccessMode mode, JSHeapBroker * broker)
Definition at line 198 of file js-generic-lowering.cc.
                                                             {
  ProcessedFeedback const& feedback =
      broker->GetFeedbackForPropertyAccess(source, mode, name);
  if (feedback.kind() == ProcessedFeedback::kElementAccess) {
    return feedback.AsElementAccess().transition_groups().empty();
  } else if (feedback.kind() == ProcessedFeedback::kNamedAccess) {
    return feedback.AsNamedAccess().maps().empty();
  } else if (feedback.kind() == ProcessedFeedback::kInsufficient) {
    return false;
  }
References v8::internal::compiler::ProcessedFeedback::AsElementAccess(), v8::internal::compiler::ProcessedFeedback::AsNamedAccess(), broker(), v8::internal::compiler::ProcessedFeedback::kElementAccess, v8::internal::compiler::ProcessedFeedback::kind(), v8::internal::compiler::ProcessedFeedback::kInsufficient, v8::internal::compiler::ProcessedFeedback::kNamedAccess, v8::internal::compiler::NamedAccessFeedback::maps(), mode(), v8::internal::name, v8::internal::compiler::ElementAccessFeedback::transition_groups(), and v8::internal::UNREACHABLE().