v8::internal::anonymous_namespace{perfetto-logger.cc} Namespace Reference
Classes
class IsolateRegistry
Functions
CodeDataSource::TraceContext::TracePacketHandle NewTracePacket (CodeDataSource::TraceContext &context)
CodeTraceContext NewCodeTraceContext (CodeDataSource::TraceContext &ctx)
void WriteJsCode (Isolate *isolate, const CodeTraceContext &ctx, Tagged< AbstractCode > abstract_code, V8JsCode &code_proto)
Function Documentation
NewCodeTraceContext()
CodeTraceContext v8::internal::anonymous_namespace{perfetto-logger.cc}::NewCodeTraceContext (CodeDataSource::TraceContext & ctx)
Definition at line 72 of file perfetto-logger.cc.
                                                                      {
  return CodeTraceContext(NewTracePacket(ctx), ctx.GetIncrementalState());
}
References NewTracePacket().
Referenced by v8::internal::PerfettoLogger::BytecodeMoveEvent(), v8::internal::PerfettoLogger::CodeCreateEvent(), v8::internal::PerfettoLogger::CodeMoveEvent(), and v8::internal::PerfettoLogger::RegExpCodeCreateEvent().
NewTracePacket()
CodeDataSource::TraceContext::TracePacketHandle v8::internal::anonymous_namespace{perfetto-logger.cc}::NewTracePacket (CodeDataSource::TraceContext & context)
Definition at line 48 of file perfetto-logger.cc.
                                         {
  CodeDataSourceIncrementalState* inc_state = context.GetIncrementalState();
  auto packet = context.NewTracePacket();
  packet->set_timestamp(base::TimeTicks::Now().since_origin().InNanoseconds());
  if (inc_state->is_initialized()) {
    packet->set_sequence_flags(TracePacket::SEQ_NEEDS_INCREMENTAL_STATE);
    return packet;
  }
  inc_state->Init(context);
  packet->set_sequence_flags(TracePacket::SEQ_INCREMENTAL_STATE_CLEARED);
  auto* defaults = packet->set_trace_packet_defaults();
  defaults->set_timestamp_clock_id(BuiltinClock::BUILTIN_CLOCK_MONOTONIC);
  auto* v8_defaults = defaults->set_v8_code_defaults();
  v8_defaults->set_tid(base::OS::GetCurrentThreadId());
  return packet;
}
References v8::base::OS::GetCurrentThreadId(), v8::internal::CodeDataSourceIncrementalState::Init(), v8::internal::CodeDataSourceIncrementalState::is_initialized(), and v8::base::TimeTicks::Now().
Referenced by NewCodeTraceContext().
WriteJsCode()
void v8::internal::anonymous_namespace{perfetto-logger.cc}::WriteJsCode (Isolate * isolate, const CodeTraceContext & ctx, Tagged< AbstractCode > abstract_code, V8JsCode & code_proto)
Definition at line 149 of file perfetto-logger.cc.
                                                                           {
  if (IsBytecodeArray(abstract_code)) {
    Tagged<BytecodeArray> bytecode = abstract_code->GetBytecodeArray();
    code_proto.set_tier(V8JsCode::TIER_IGNITION);
    code_proto.set_instruction_start(bytecode->GetFirstBytecodeAddress());
    code_proto.set_instruction_size_bytes(bytecode->length());
    if (ctx.log_instructions()) {
      code_proto.set_bytecode(
          reinterpret_cast<const uint8_t*>(bytecode->GetFirstBytecodeAddress()),
          bytecode->length());
    }
    return;
  }
  DCHECK(IsCode(abstract_code));
  Tagged<Code> code = abstract_code->GetCode();
  V8JsCode::Tier tier = V8JsCode::TIER_UNKNOWN;
  switch (code->kind()) {
    case CodeKind::BUILTIN:
      if (code->builtin_id() == Builtin::kInterpreterEntryTrampoline) {
        DCHECK(isolate->interpreted_frames_native_stack());
        DCHECK(code->has_instruction_stream());
        tier = V8JsCode::TIER_IGNITION;
        break;
      }
      // kEmptyFunction is used as a placeholder sometimes.
      DCHECK_EQ(code->builtin_id(), Builtin::kEmptyFunction);
      DCHECK(!code->has_instruction_stream());
      return;
    case CodeKind::INTERPRETED_FUNCTION:
      // Handled above.
      UNREACHABLE();
    case CodeKind::BASELINE:
      tier = V8JsCode::TIER_SPARKPLUG;
      break;
    case CodeKind::MAGLEV:
      tier = V8JsCode::TIER_MAGLEV;
      break;
    case CodeKind::TURBOFAN_JS:
      tier = V8JsCode::TIER_TURBOFAN;
      break;
    case CodeKind::BYTECODE_HANDLER:
    case CodeKind::FOR_TESTING:
    case CodeKind::REGEXP:
    case CodeKind::WASM_FUNCTION:
    case CodeKind::WASM_TO_CAPI_FUNCTION:
    case CodeKind::WASM_TO_JS_FUNCTION:
    case CodeKind::JS_TO_WASM_FUNCTION:
    case CodeKind::C_WASM_ENTRY:
      UNREACHABLE();
  }
  code_proto.set_tier(tier);
  code_proto.set_instruction_start(code->instruction_start());
  code_proto.set_instruction_size_bytes(code->instruction_size());
  if (ctx.log_instructions()) {
    code_proto.set_machine_code(
        reinterpret_cast<const uint8_t*>(code->instruction_start()),
        code->instruction_size());
  }
}
References BUILTIN, code, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Isolate::interpreted_frames_native_stack(), v8::internal::CodeTraceContext::log_instructions(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::PerfettoLogger::CodeCreateEvent().