v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::anonymous_namespace{escape-analysis.cc} Namespace Reference
Functions
bool CheckMapsHelper (EscapeAnalysisTracker::Scope *current, Node *checked, ZoneRefSet< Map > target)
Function Documentation
CheckMapsHelper()
bool v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::anonymous_namespace{escape-analysis.cc}::CheckMapsHelper (EscapeAnalysisTracker::Scope * current, Node * checked, ZoneRefSet< Map > target)
Definition at line 608 of file escape-analysis.cc.
                                             {
  const VirtualObject* vobject = current->GetVirtualObject(checked);
  Variable map_field;
  Node* map;
  if (vobject && !vobject->HasEscaped() &&
      vobject->FieldAt(HeapObject::kMapOffset).To(&map_field) &&
      current->Get(map_field).To(&map)) {
    if (map) {
      Type const map_type = NodeProperties::GetType(map);
      if (map_type.IsHeapConstant() &&
          target.contains(map_type.AsHeapConstant()->Ref().AsMap())) {
        current->MarkForDeletion();
        return true;
      }
    } else {
      // If the variable has no value, we have not reached the fixed-point
      // yet.
      return true;
    }
  }
  return false;
}
References v8::internal::compiler::Type::AsHeapConstant(), v8::internal::ZoneCompactSet< T >::contains(), v8::internal::compiler::VirtualObject::FieldAt(), v8::internal::compiler::VariableTracker::Scope::Get(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::EscapeAnalysisTracker::Scope::GetVirtualObject(), v8::internal::compiler::VirtualObject::HasEscaped(), v8::internal::compiler::Type::IsHeapConstant(), v8::internal::HeapObject::kMapOffset, v8::internal::compiler::EscapeAnalysisTracker::Scope::MarkForDeletion(), and v8::internal::compiler::HeapConstantType::Ref().
Referenced by v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::ReduceNode().