v8::internal::anonymous_namespace{js-number-format.cc} Namespace Reference
Classes
class UnitFactory
struct CheckNumberElements
Enumerations
enum class Style { DECIMAL
, PERCENT
, CURRENCY
, UNIT
 }
enum class CurrencyDisplay { CODE
, SYMBOL
, NAME
, NARROW_SYMBOL
 }
enum class CurrencySign { STANDARD
, ACCOUNTING
 }
enum class UnitDisplay { SHORT
, NARROW
, LONG
 }
enum class Notation { STANDARD
, SCIENTIFIC
, ENGINEERING
, COMPACT
 }
enum class CompactDisplay { SHORT
, LONG
 }
enum class SignDisplay {
AUTO
, ALWAYS
, NEVER
, EXCEPT_ZERO
,
NEGATIVE
 }
enum class UseGrouping { OFF
, MIN2
, AUTO
, ALWAYS
 }
Functions
UNumberUnitWidth ToUNumberUnitWidth (CurrencyDisplay currency_display)
UNumberUnitWidth ToUNumberUnitWidth (UnitDisplay unit_display)
UNumberSignDisplay ToUNumberSignDisplay (SignDisplay sign_display, CurrencySign currency_sign)
icu::number::Notation ToICUNotation (Notation notation, CompactDisplay compact_display)
UNumberFormatRoundingMode ToUNumberFormatRoundingMode (Intl::RoundingMode rounding_mode)
UNumberGroupingStrategy ToUNumberGroupingStrategy (UseGrouping use_grouping)
std::map< const std::string, icu::MeasureUnit, std::less<> > CreateUnitMap ()
icu::MeasureUnit IsSanctionedUnitIdentifier (const std::string_view unit)
Maybe< std::pair< icu::MeasureUnit, icu::MeasureUnit > > IsWellFormedUnitIdentifier (Isolate *isolate, const std::string_view unit)
int CurrencyDigits (const icu::UnicodeString &currency)
bool IsAToZ (char ch)
bool IsWellFormedCurrencyCode (const std::string &currency)
DirectHandle< String > StyleAsString (Isolate *isolate, Style style)
DirectHandle< String > CurrencyDisplayString (Isolate *isolate, const icu::UnicodeString &skeleton)
DirectHandle< Object > UseGroupingFromSkeleton (Isolate *isolate, const icu::UnicodeString &skeleton)
const icu::UnicodeString CurrencyFromSkeleton (const icu::UnicodeString &skeleton)
DirectHandle< String > CurrencySignString (Isolate *isolate, const icu::UnicodeString &skeleton)
DirectHandle< String > UnitDisplayString (Isolate *isolate, const icu::UnicodeString &skeleton)
Notation NotationFromSkeleton (const icu::UnicodeString &skeleton)
DirectHandle< String > NotationAsString (Isolate *isolate, Notation notation)
DirectHandle< String > CompactDisplayString (Isolate *isolate, const icu::UnicodeString &skeleton)
DirectHandle< String > SignDisplayString (Isolate *isolate, const icu::UnicodeString &skeleton)
std::string UnitFromSkeleton (const icu::UnicodeString &skeleton)
Style StyleFromSkeleton (const icu::UnicodeString &skeleton)
template<typename StringHandle >
int32_t SignedStringLength (StringHandle string)
icu::number::FormattedNumber FormatDecimalString (Isolate *isolate, const icu::number::LocalizedNumberFormatter &number_format, Handle< String > string, UErrorCode &status)
Maybe< icu::number::FormattedNumber > IcuFormatNumber (Isolate *isolate, const icu::number::LocalizedNumberFormatter &number_format, Handle< Object > numeric_obj)
template<typename Char >
std::pair< int, int > FindLeadingAndTrailingWhiteSpaceOrLineTerminator (base::Vector< const Char > src)
Handle< String > TrimWhiteSpaceOrLineTerminator (Isolate *isolate, Handle< String > string)
bool cmp_NumberFormatSpan (const NumberFormatSpan &a, const NumberFormatSpan &b)
Maybe< int > ConstructParts (Isolate *isolate, const icu::FormattedValue &formatted, DirectHandle< JSArray > result, int start_index, bool style_is_unit, bool is_nan, bool output_source, bool output_unit, DirectHandle< String > unit)
template<typename T , MaybeDirectHandle< T >(*)(Isolate *, const icu::FormattedValue &, const icu::number::LocalizedNumberFormatter &, bool) F>
MaybeDirectHandle< T > PartitionNumberRangePattern (Isolate *isolate, DirectHandle< JSNumberFormat > number_format, Handle< Object > start, Handle< Object > end, const char *func_name)
MaybeDirectHandle< String > FormatToString (Isolate *isolate, const icu::FormattedValue &formatted, const icu::number::LocalizedNumberFormatter &, bool)
MaybeDirectHandle< JSArray > FormatToJSArray (Isolate *isolate, const icu::FormattedValue &formatted, const icu::number::LocalizedNumberFormatter &nfmt, bool is_nan, bool output_source)
MaybeDirectHandle< JSArray > FormatRangeToJSArray (Isolate *isolate, const icu::FormattedValue &formatted, const icu::number::LocalizedNumberFormatter &nfmt, bool is_nan)
Enumeration Type Documentation
CompactDisplay
enum v8::internal::anonymous_namespace{js-number-format.cc}::CompactDisplay [strong]
Enumerator
SHORT
LONG
Definition at line 95 of file js-number-format.cc.
                          {
  SHORT,
  LONG,
};
CurrencyDisplay
enum v8::internal::anonymous_namespace{js-number-format.cc}::CurrencyDisplay [strong]
Enumerator
CODE
SYMBOL
NAME
NARROW_SYMBOL
Definition at line 50 of file js-number-format.cc.
                           {
  CODE,
  SYMBOL,
  NAME,
  NARROW_SYMBOL,
};
CurrencySign
enum v8::internal::anonymous_namespace{js-number-format.cc}::CurrencySign [strong]
Enumerator
STANDARD
ACCOUNTING
Definition at line 61 of file js-number-format.cc.
                        {
  STANDARD,
  ACCOUNTING,
};
Notation
enum v8::internal::anonymous_namespace{js-number-format.cc}::Notation [strong]
Enumerator
STANDARD
SCIENTIFIC
ENGINEERING
COMPACT
Definition at line 84 of file js-number-format.cc.
                    {
  STANDARD,
  SCIENTIFIC,
  ENGINEERING,
  COMPACT,
};
SignDisplay
enum v8::internal::anonymous_namespace{js-number-format.cc}::SignDisplay [strong]
Enumerator
AUTO
ALWAYS
NEVER
EXCEPT_ZERO
NEGATIVE
Definition at line 104 of file js-number-format.cc.
                       {
  AUTO,
  ALWAYS,
  NEVER,
  EXCEPT_ZERO,
  NEGATIVE,
};
Style
enum v8::internal::anonymous_namespace{js-number-format.cc}::Style [strong]
Enumerator
DECIMAL
PERCENT
CURRENCY
UNIT
Definition at line 46 of file js-number-format.cc.
{ DECIMAL, PERCENT, CURRENCY, UNIT };
UnitDisplay
enum v8::internal::anonymous_namespace{js-number-format.cc}::UnitDisplay [strong]
Enumerator
SHORT
NARROW
LONG
Definition at line 70 of file js-number-format.cc.
                       {
  SHORT,
  NARROW,
  LONG,
};
UseGrouping
enum v8::internal::anonymous_namespace{js-number-format.cc}::UseGrouping [strong]
Enumerator
OFF
MIN2
AUTO
ALWAYS
Definition at line 113 of file js-number-format.cc.
                       {
  OFF,
  MIN2,
  AUTO,
  ALWAYS,
};
Function Documentation
cmp_NumberFormatSpan()
bool v8::internal::anonymous_namespace{js-number-format.cc}::cmp_NumberFormatSpan (const NumberFormatSpan & a, const NumberFormatSpan & b)
Definition at line 1819 of file js-number-format.cc.
                                                     {
  // Regions that start earlier should be encountered earlier.
  if (a.begin_pos < b.begin_pos) return true;
  if (a.begin_pos > b.begin_pos) return false;
  // For regions that start in the same place, regions that last longer should
  // be encountered earlier.
  if (a.end_pos < b.end_pos) return false;
  if (a.end_pos > b.end_pos) return true;
  // For regions that are exactly the same, one of them must be the "literal"
  // backdrop we added, which has a field_id of -1, so consider higher field_ids
  // to be later.
  return a.field_id < b.field_id;
}
References v8::internal::NumberFormatSpan::begin_pos, v8::internal::NumberFormatSpan::end_pos, and v8::internal::NumberFormatSpan::field_id.
Referenced by v8::internal::FlattenRegionsToParts().
CompactDisplayString()
DirectHandle<String> v8::internal::anonymous_namespace{js-number-format.cc}::CompactDisplayString (Isolate * isolate, const icu::UnicodeString & skeleton)
Definition at line 519 of file js-number-format.cc.
                                                                            {
  // Ex: skeleton as
  // "compact-long .### rounding-mode-half-up"
  if (skeleton.indexOf("compact-long") >= 0) {
    return isolate->factory()->long_string();
  }
  // Ex: skeleton as
  // "compact-short .### rounding-mode-half-up"
  DCHECK_GE(skeleton.indexOf("compact-short"), 0);
  return isolate->factory()->short_string();
}
References DCHECK_GE, and v8::internal::Isolate::factory().
Referenced by v8::internal::JSNumberFormat::ResolvedOptions().
ConstructParts()
Maybe<int> v8::internal::anonymous_namespace{js-number-format.cc}::ConstructParts (Isolate * isolate, const icu::FormattedValue & formatted, DirectHandle< JSArray > result, int start_index, bool style_is_unit, bool is_nan, bool output_source, bool output_unit, DirectHandle< String > unit)
Definition at line 1927 of file js-number-format.cc.
                                                                       {
  UErrorCode status = U_ZERO_ERROR;
  icu::UnicodeString formatted_text = formatted.toString(status);
  if (U_FAILURE(status)) {
    THROW_NEW_ERROR_RETURN_VALUE(
        isolate, NewTypeError(MessageTemplate::kIcuError), Nothing<int>());
  }
  int32_t length = formatted_text.length();
  int index = start_index;
  if (length == 0) return Just(index);
  std::vector<NumberFormatSpan> regions;
  // Add a "literal" backdrop for the entire string. This will be used if no
  // other region covers some part of the formatted string. It's possible
  // there's another field with exactly the same begin and end as this backdrop,
  // in which case the backdrop's field_id of -1 will give it lower priority.
  regions.push_back(NumberFormatSpan(-1, 0, formatted_text.length()));
  Intl::FormatRangeSourceTracker tracker;
  {
    icu::ConstrainedFieldPosition cfpos;
    while (formatted.nextPosition(cfpos, status)) {
      int32_t category = cfpos.getCategory();
      int32_t field = cfpos.getField();
      int32_t start = cfpos.getStart();
      int32_t limit = cfpos.getLimit();
      if (category == UFIELD_CATEGORY_NUMBER_RANGE_SPAN) {
        DCHECK_LE(field, 2);
        tracker.Add(field, start, limit);
      } else {
        regions.push_back(NumberFormatSpan(field, start, limit));
      }
    }
  }
  std::vector<NumberFormatSpan> parts = FlattenRegionsToParts(&regions);
  for (auto it = parts.begin(); it < parts.end(); it++) {
    NumberFormatSpan part = *it;
    DirectHandle<String> field_type_string =
        isolate->factory()->literal_string();
    if (part.field_id != -1) {
      if (style_is_unit && static_cast<UNumberFormatFields>(part.field_id) ==
                               UNUM_PERCENT_FIELD) {
        // Special case when style is unit.
        field_type_string = isolate->factory()->unit_string();
      } else {
        field_type_string =
            Intl::NumberFieldToType(isolate, part, formatted_text, is_nan);
      }
    }
    DirectHandle<String> substring;
    ASSIGN_RETURN_ON_EXCEPTION_VALUE(
        isolate, substring,
        Intl::ToString(isolate, formatted_text, part.begin_pos, part.end_pos),
        Nothing<int>());
    if (output_source) {
      Intl::AddElement(
          isolate, result, index, field_type_string, substring,
          isolate->factory()->source_string(),
          Intl::SourceString(isolate,
                             tracker.GetSource(part.begin_pos, part.end_pos)));
    } else {
      if (output_unit) {
        Intl::AddElement(isolate, result, index, field_type_string, substring,
                         isolate->factory()->unit_string(), unit);
      } else {
        Intl::AddElement(isolate, result, index, field_type_string, substring);
      }
    }
    ++index;
  }
  JSObject::ValidateElements(isolate, *result);
  return Just(index);
}
References v8::internal::Intl::FormatRangeSourceTracker::Add(), v8::internal::Intl::AddElement(), ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::NumberFormatSpan::begin_pos, DCHECK_LE, v8::internal::NumberFormatSpan::end_pos, v8::internal::Isolate::factory(), v8::internal::NumberFormatSpan::field_id, v8::internal::FlattenRegionsToParts(), v8::internal::Intl::FormatRangeSourceTracker::GetSource(), v8::internal::index, v8::Just(), v8::internal::length, v8::internal::Intl::NumberFieldToType(), v8::base::internal::result, v8::internal::Intl::SourceString(), v8::internal::status, THROW_NEW_ERROR_RETURN_VALUE, v8::internal::Intl::ToString(), and v8::internal::JSObject::ValidateElements().
Referenced by v8::internal::Intl::AddNumberElements(), and FormatToJSArray().
CreateUnitMap()
std::map<const std::string, icu::MeasureUnit, std::less<> > v8::internal::anonymous_namespace{js-number-format.cc}::CreateUnitMap ()
Definition at line 233 of file js-number-format.cc.
                                                                   {
  UErrorCode status = U_ZERO_ERROR;
  int32_t total = icu::MeasureUnit::getAvailable(nullptr, 0, status);
  DCHECK(U_FAILURE(status));
  status = U_ZERO_ERROR;
  std::vector<icu::MeasureUnit> units(total);
  total = icu::MeasureUnit::getAvailable(units.data(), total, status);
  DCHECK(U_SUCCESS(status));
  std::map<const std::string, icu::MeasureUnit, std::less<>> map;
  std::set<std::string> sanctioned(Intl::SanctionedSimpleUnits());
  for (auto it = units.begin(); it != units.end(); ++it) {
    // Need to skip none/percent
    if (sanctioned.count(it->getSubtype()) > 0 &&
        strcmp("none", it->getType()) != 0) {
      map[it->getSubtype()] = *it;
    }
  }
  return map;
}
References v8::internal::DCHECK(), v8::internal::Intl::SanctionedSimpleUnits(), and v8::internal::status.
CurrencyDigits()
int v8::internal::anonymous_namespace{js-number-format.cc}::CurrencyDigits (const icu::UnicodeString & currency)
Definition at line 329 of file js-number-format.cc.
                                                     {
  UErrorCode status = U_ZERO_ERROR;
  uint32_t fraction_digits = ucurr_getDefaultFractionDigits(
      reinterpret_cast<const UChar*>(currency.getBuffer()), &status);
  // For missing currency codes, default to the most common, 2
  return U_SUCCESS(status) ? fraction_digits : 2;
}
References v8::internal::status.
Referenced by v8::internal::JSNumberFormat::New().
CurrencyDisplayString()
DirectHandle<String> v8::internal::anonymous_namespace{js-number-format.cc}::CurrencyDisplayString (Isolate * isolate, const icu::UnicodeString & skeleton)
Definition at line 375 of file js-number-format.cc.
                                                                             {
  // Ex: skeleton as
  // "currency/TWD .00 rounding-mode-half-up unit-width-iso-code"
  if (skeleton.indexOf("unit-width-iso-code") >= 0) {
    return isolate->factory()->code_string();
  }
  // Ex: skeleton as
  // "currency/TWD .00 rounding-mode-half-up unit-width-full-name;"
  if (skeleton.indexOf("unit-width-full-name") >= 0) {
    return isolate->factory()->name_string();
  }
  // Ex: skeleton as
  // "currency/TWD .00 rounding-mode-half-up unit-width-narrow;
  if (skeleton.indexOf("unit-width-narrow") >= 0) {
    return isolate->factory()->narrowSymbol_string();
  }
  // Ex: skeleton as "currency/TWD .00 rounding-mode-half-up"
  return isolate->factory()->symbol_string();
}
References v8::internal::Isolate::factory().
Referenced by v8::internal::JSNumberFormat::ResolvedOptions().
CurrencyFromSkeleton()
const icu::UnicodeString v8::internal::anonymous_namespace{js-number-format.cc}::CurrencyFromSkeleton (const icu::UnicodeString & skeleton)
Definition at line 427 of file js-number-format.cc.
                                      {
  const char currency[] = "currency/";
  int32_t index = skeleton.indexOf(currency);
  if (index < 0) return "";
  index += static_cast<int32_t>(std::strlen(currency));
  return skeleton.tempSubString(index, 3);
}
References v8::internal::index.
Referenced by v8::internal::JSNumberFormat::ResolvedOptions().
CurrencySignString()
DirectHandle<String> v8::internal::anonymous_namespace{js-number-format.cc}::CurrencySignString (Isolate * isolate, const icu::UnicodeString & skeleton)
Definition at line 452 of file js-number-format.cc.
                                                                          {
  // Ex: skeleton as
  // "currency/TWD .00 rounding-mode-half-up sign-accounting-always" OR
  // "currency/TWD .00 rounding-mode-half-up sign-accounting-except-zero"
  if (skeleton.indexOf("sign-accounting") >= 0) {
    return isolate->factory()->accounting_string();
  }
  return isolate->factory()->standard_string();
}
References v8::internal::Isolate::factory().
Referenced by v8::internal::JSNumberFormat::ResolvedOptions().
FindLeadingAndTrailingWhiteSpaceOrLineTerminator()
template<typename Char >
std::pair<int, int> v8::internal::anonymous_namespace{js-number-format.cc}::FindLeadingAndTrailingWhiteSpaceOrLineTerminator (base::Vector< const Char > src)
Definition at line 1649 of file js-number-format.cc.
                                {
  size_t leading_end = 0;
  // Find the length of leading StrWhiteSpaceChar.
  while (leading_end < src.size() &&
         IsWhiteSpaceOrLineTerminator(
             static_cast<uint16_t>(src.at(leading_end)))) {
    leading_end++;
  }
  size_t trailing_start = src.size();
  // Find the start of the trailing StrWhiteSpaceChar
  while (trailing_start > leading_end &&
         IsWhiteSpaceOrLineTerminator(
             static_cast<uint16_t>(src.at(trailing_start - 1)))) {
    trailing_start--;
  }
  return std::make_pair(leading_end, trailing_start);
}
References v8::base::Vector< T >::at(), v8::internal::IsWhiteSpaceOrLineTerminator(), and v8::base::Vector< T >::size().
Referenced by TrimWhiteSpaceOrLineTerminator().
FormatDecimalString()
icu::number::FormattedNumber v8::internal::anonymous_namespace{js-number-format.cc}::FormatDecimalString (Isolate * isolate, const icu::number::LocalizedNumberFormatter & number_format, Handle< String > string, UErrorCode & status)
Definition at line 1500 of file js-number-format.cc.
                                               {
  string = String::Flatten(isolate, string);
  DisallowGarbageCollection no_gc;
  const String::FlatContent& flat = string->GetFlatContent(no_gc);
  int32_t length = SignedStringLength(string);
  if (flat.IsOneByte()) {
    const char* char_buffer =
        reinterpret_cast<const char*>(flat.ToOneByteVector().begin());
    return number_format.formatDecimal({char_buffer, length}, status);
  }
  auto converted = string->ToStdString();
  return number_format.formatDecimal(converted, status);
}
References v8::base::Vector< T >::begin(), v8::internal::String::FlatContent::IsOneByte(), v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, SignedStringLength(), v8::internal::status, and v8::internal::String::FlatContent::ToOneByteVector().
Referenced by v8::internal::IntlMathematicalValue::FormatNumeric().
FormatRangeToJSArray()
MaybeDirectHandle<JSArray> v8::internal::anonymous_namespace{js-number-format.cc}::FormatRangeToJSArray (Isolate * isolate, const icu::FormattedValue & formatted, const icu::number::LocalizedNumberFormatter & nfmt, bool is_nan)
Definition at line 2106 of file js-number-format.cc.
                                                                {
  return FormatToJSArray(isolate, formatted, nfmt, is_nan, true);
}
References FormatToJSArray().
FormatToJSArray()
MaybeDirectHandle<JSArray> v8::internal::anonymous_namespace{js-number-format.cc}::FormatToJSArray (Isolate * isolate, const icu::FormattedValue & formatted, const icu::number::LocalizedNumberFormatter & nfmt, bool is_nan, bool output_source)
Definition at line 2084 of file js-number-format.cc.
                        {
  UErrorCode status = U_ZERO_ERROR;
  bool is_unit = Style::UNIT == StyleFromSkeleton(nfmt.toSkeleton(status));
  CHECK(U_SUCCESS(status));
  Factory* factory = isolate->factory();
  DirectHandle<JSArray> result = factory->NewJSArray(0);
  int format_to_parts;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, format_to_parts,
      ConstructParts(isolate, formatted, result, 0, is_unit, is_nan,
                     output_source, false, DirectHandle<String>()),
      DirectHandle<JSArray>());
  USE(format_to_parts);
  return result;
}
References CHECK, ConstructParts(), v8::internal::Isolate::factory(), MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::Factory::NewJSArray(), v8::base::internal::result, v8::internal::status, StyleFromSkeleton(), and USE.
Referenced by FormatRangeToJSArray(), and v8::internal::JSNumberFormat::FormatToParts().
FormatToString()
MaybeDirectHandle<String> v8::internal::anonymous_namespace{js-number-format.cc}::FormatToString (Isolate * isolate, const icu::FormattedValue & formatted, const icu::number::LocalizedNumberFormatter & , bool)
Definition at line 2073 of file js-number-format.cc.
                                                    {
  UErrorCode status = U_ZERO_ERROR;
  icu::UnicodeString result = formatted.toString(status);
  if (U_FAILURE(status)) {
    THROW_NEW_ERROR(isolate, NewTypeError(MessageTemplate::kIcuError));
  }
  return Intl::ToString(isolate, result);
}
References v8::base::internal::result, v8::internal::status, THROW_NEW_ERROR, and v8::internal::Intl::ToString().
Referenced by v8::internal::JSNumberFormat::FormatNumeric(), and v8::internal::JSNumberFormat::NumberFormatFunction().
IcuFormatNumber()
Maybe<icu::number::FormattedNumber> v8::internal::anonymous_namespace{js-number-format.cc}::IcuFormatNumber (Isolate * isolate, const icu::number::LocalizedNumberFormatter & number_format, Handle< Object > numeric_obj)
Definition at line 1534 of file js-number-format.cc.
                                {
  icu::number::FormattedNumber formatted;
  // If it is BigInt, handle it differently.
  UErrorCode status = U_ZERO_ERROR;
  if (IsBigInt(*numeric_obj)) {
    auto big_int = Cast<BigInt>(numeric_obj);
    Handle<String> big_int_string;
    ASSIGN_RETURN_ON_EXCEPTION_VALUE(isolate, big_int_string,
                                     BigInt::ToString(isolate, big_int),
                                     Nothing<icu::number::FormattedNumber>());
    big_int_string = String::Flatten(isolate, big_int_string);
    DisallowGarbageCollection no_gc;
    const String::FlatContent& flat = big_int_string->GetFlatContent(no_gc);
    int32_t length = SignedStringLength(big_int_string);
    DCHECK(flat.IsOneByte());
    const char* char_buffer =
        reinterpret_cast<const char*>(flat.ToOneByteVector().begin());
    formatted = number_format.formatDecimal({char_buffer, length}, status);
  } else {
    if (IsString(*numeric_obj)) {
      // TODO(ftang) Correct the handling of string after the resolution of
      // https://github.com/tc39/proposal-intl-numberformat-v3/pull/82
      DirectHandle<String> string =
          String::Flatten(isolate, Cast<String>(numeric_obj));
      DisallowGarbageCollection no_gc;
      const String::FlatContent& flat = string->GetFlatContent(no_gc);
      int32_t length = SignedStringLength(string);
      if (flat.IsOneByte()) {
        const char* char_buffer =
            reinterpret_cast<const char*>(flat.ToOneByteVector().begin());
        formatted = number_format.formatDecimal({char_buffer, length}, status);
      } else {
        // We may have two bytes string such as " 123456789".substring(2)
        // The value will be "123456789" only in ASCII range, but encoded
        // in two bytes string.
        // ICU accepts UTF8 string, so if the source is two-byte encoded,
        // copy into a UTF8 string via ToStdString.
        auto std_string = string->ToStdString();
        formatted = number_format.formatDecimal(std_string, status);
      }
    } else {
      double number = IsNaN(*numeric_obj)
                          ? std::numeric_limits<double>::quiet_NaN()
                          : Object::NumberValue(*numeric_obj);
      formatted = number_format.formatDouble(number, status);
    }
  }
  if (U_FAILURE(status)) {
    // This happen because of icu data trimming trim out "unit".
    // See https://bugs.chromium.org/p/v8/issues/detail?id=8641
    THROW_NEW_ERROR_RETURN_VALUE(isolate,
                                 NewTypeError(MessageTemplate::kIcuError),
                                 Nothing<icu::number::FormattedNumber>());
  }
  return Just(std::move(formatted));
}
References ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::base::Vector< T >::begin(), v8::internal::DCHECK(), v8::internal::IsNaN(), v8::internal::String::FlatContent::IsOneByte(), v8::Just(), v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Object::NumberValue(), SignedStringLength(), v8::internal::status, THROW_NEW_ERROR_RETURN_VALUE, v8::internal::String::FlatContent::ToOneByteVector(), and v8::internal::BigInt::ToString().
Referenced by v8::internal::IntlMathematicalValue::FormatNumeric(), and v8::internal::JSNumberFormat::FormatNumeric().
IsAToZ()
bool v8::internal::anonymous_namespace{js-number-format.cc}::IsAToZ (char ch)
Definition at line 337 of file js-number-format.cc.
                     {
  return base::IsInRange(AsciiAlphaToLower(ch), 'a', 'z');
}
References v8::internal::AsciiAlphaToLower().
Referenced by IsWellFormedCurrencyCode().
IsSanctionedUnitIdentifier()
icu::MeasureUnit v8::internal::anonymous_namespace{js-number-format.cc}::IsSanctionedUnitIdentifier (const std::string_view unit)
Definition at line 276 of file js-number-format.cc.
                                                                     {
  static base::LazyInstance<UnitFactory>::type factory =
      LAZY_INSTANCE_INITIALIZER;
  return factory.Pointer()->create(unit);
}
References LAZY_INSTANCE_INITIALIZER.
Referenced by IsWellFormedUnitIdentifier().
IsWellFormedCurrencyCode()
bool v8::internal::anonymous_namespace{js-number-format.cc}::IsWellFormedCurrencyCode (const std::string & currency)
Definition at line 342 of file js-number-format.cc.
                                                         {
  // Verifies that the input is a well-formed ISO 4217 currency code.
  // ecma402/#sec-currency-codes
  // 2. If the number of elements in normalized is not 3, return false.
  if (currency.length() != 3) return false;
  // 1. Let normalized be the result of mapping currency to upper case as
  // described in 6.1.
  //
  // 3. If normalized contains any character that is not in
  // the range "A" to "Z" (U+0041 to U+005A), return false.
  //
  // 4. Return true.
  // Don't uppercase to test. It could convert invalid code into a valid one.
  // For example \u00DFP (Eszett+P) becomes SSP.
  return (IsAToZ(currency[0]) && IsAToZ(currency[1]) && IsAToZ(currency[2]));
}
References IsAToZ().
Referenced by v8::internal::JSNumberFormat::New().
IsWellFormedUnitIdentifier()
Maybe<std::pair<icu::MeasureUnit, icu::MeasureUnit> > v8::internal::anonymous_namespace{js-number-format.cc}::IsWellFormedUnitIdentifier (Isolate * isolate, const std::string_view unit)
Definition at line 283 of file js-number-format.cc.
                                                 {
  icu::MeasureUnit result = IsSanctionedUnitIdentifier(unit);
  icu::MeasureUnit none = icu::MeasureUnit();
  // 1. If the result of IsSanctionedUnitIdentifier(unitIdentifier) is true,
  // then
  if (result != AVOID_AMBIGUOUS_OP_WARNING(none)) {
    // a. Return true.
    std::pair<icu::MeasureUnit, icu::MeasureUnit> pair(result, none);
    return Just(pair);
  }
  // 2. If the substring "-per-" does not occur exactly once in unitIdentifier,
  // then
  size_t first_per = unit.find("-per-");
  if (first_per == std::string::npos ||
      unit.find("-per-", first_per + 5) != std::string::npos) {
    // a. Return false.
    return Nothing<std::pair<icu::MeasureUnit, icu::MeasureUnit>>();
  }
  // 3. Let numerator be the substring of unitIdentifier from the beginning to
  // just before "-per-".
  std::string_view numerator = unit.substr(0, first_per);
  // 4. If the result of IsSanctionedUnitIdentifier(numerator) is false, then
  result = IsSanctionedUnitIdentifier(numerator);
  if (result == AVOID_AMBIGUOUS_OP_WARNING(none)) {
    // a. Return false.
    return Nothing<std::pair<icu::MeasureUnit, icu::MeasureUnit>>();
  }
  // 5. Let denominator be the substring of unitIdentifier from just after
  // "-per-" to the end.
  std::string_view denominator = unit.substr(first_per + 5);
  // 6. If the result of IsSanctionedUnitIdentifier(denominator) is false, then
  icu::MeasureUnit den_result = IsSanctionedUnitIdentifier(denominator);
  if (den_result == AVOID_AMBIGUOUS_OP_WARNING(none)) {
    // a. Return false.
    return Nothing<std::pair<icu::MeasureUnit, icu::MeasureUnit>>();
  }
  // 7. Return true.
  std::pair<icu::MeasureUnit, icu::MeasureUnit> pair(result, den_result);
  return Just(pair);
}
References AVOID_AMBIGUOUS_OP_WARNING, IsSanctionedUnitIdentifier(), v8::Just(), none, and v8::base::internal::result.
Referenced by v8::internal::JSNumberFormat::New().
NotationAsString()
DirectHandle<String> v8::internal::anonymous_namespace{js-number-format.cc}::NotationAsString (Isolate * isolate, Notation notation)
Definition at line 504 of file js-number-format.cc.
                                                                           {
  switch (notation) {
    case Notation::SCIENTIFIC:
      return isolate->factory()->scientific_string();
    case Notation::ENGINEERING:
      return isolate->factory()->engineering_string();
    case Notation::COMPACT:
      return isolate->factory()->compact_string();
    case Notation::STANDARD:
      return isolate->factory()->standard_string();
  }
  UNREACHABLE();
}
References v8::internal::Isolate::factory(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::JSNumberFormat::ResolvedOptions().
NotationFromSkeleton()
Notation v8::internal::anonymous_namespace{js-number-format.cc}::NotationFromSkeleton (const icu::UnicodeString & skeleton)
Definition at line 482 of file js-number-format.cc.
                                                                {
  // Ex: skeleton as
  // "scientific .### rounding-mode-half-up"
  if (skeleton.indexOf("scientific") >= 0) {
    return Notation::SCIENTIFIC;
  }
  // Ex: skeleton as
  // "engineering .### rounding-mode-half-up"
  if (skeleton.indexOf("engineering") >= 0) {
    return Notation::ENGINEERING;
  }
  // Ex: skeleton as
  // "compact-short .### rounding-mode-half-up" or
  // "compact-long .### rounding-mode-half-up
  if (skeleton.indexOf("compact-") >= 0) {
    return Notation::COMPACT;
  }
  // Ex: skeleton as
  // "unit/length-foot .### rounding-mode-half-up"
  return Notation::STANDARD;
}
Referenced by v8::internal::JSNumberFormat::ResolvedOptions().
PartitionNumberRangePattern()
template<typename T , MaybeDirectHandle< T >(*)(Isolate *, const icu::FormattedValue &, const icu::number::LocalizedNumberFormatter &, bool) F>
MaybeDirectHandle<T> v8::internal::anonymous_namespace{js-number-format.cc}::PartitionNumberRangePattern (Isolate * isolate, DirectHandle< JSNumberFormat > number_format, Handle< Object > start, Handle< Object > end, const char * func_name)
Definition at line 2023 of file js-number-format.cc.
                                                                     {
  Factory* factory = isolate->factory();
  // 4. Let x be ? ToIntlMathematicalValue(start).
  IntlMathematicalValue x;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, x, IntlMathematicalValue::From(isolate, start),
      DirectHandle<T>());
  // 5. Let y be ? ToIntlMathematicalValue(end).
  IntlMathematicalValue y;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, y, IntlMathematicalValue::From(isolate, end), DirectHandle<T>());
  // 1. If x is not-a-number or y is not-a-number, throw a RangeError exception.
  if (x.IsNaN()) {
    THROW_NEW_ERROR_RETURN_VALUE(
        isolate,
        NewRangeError(MessageTemplate::kInvalid,
                      factory->NewStringFromStaticChars("start"), start),
        MaybeDirectHandle<T>());
  }
  if (y.IsNaN()) {
    THROW_NEW_ERROR_RETURN_VALUE(
        isolate,
        NewRangeError(MessageTemplate::kInvalid,
                      factory->NewStringFromStaticChars("end"), end),
        MaybeDirectHandle<T>());
  }
  Maybe<icu::number::LocalizedNumberRangeFormatter> maybe_range_formatter =
      JSNumberFormat::GetRangeFormatter(
          isolate, number_format->locale(),
          *number_format->icu_number_formatter()->raw());
  MAYBE_RETURN(maybe_range_formatter, MaybeDirectHandle<T>());
  icu::number::LocalizedNumberRangeFormatter nrfmt =
      maybe_range_formatter.FromJust();
  Maybe<icu::number::FormattedNumberRange> maybe_formatted =
      IntlMathematicalValue::FormatRange(isolate, nrfmt, x, y);
  MAYBE_RETURN(maybe_formatted, DirectHandle<T>());
  icu::number::FormattedNumberRange formatted =
      std::move(maybe_formatted).FromJust();
  return F(isolate, formatted, *(number_format->icu_number_formatter()->raw()),
           false /* is_nan */);
}
References v8::internal::compiler::end(), v8::internal::F, v8::internal::Isolate::factory(), v8::internal::IntlMathematicalValue::FormatRange(), v8::internal::IntlMathematicalValue::From(), v8::Maybe< T >::FromJust(), v8::internal::JSNumberFormat::GetRangeFormatter(), v8::internal::IntlMathematicalValue::IsNaN(), v8::internal::anonymous_namespace{isolate.cc}::kInvalid, MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE, MAYBE_RETURN, v8::internal::Factory::NewStringFromStaticChars(), THROW_NEW_ERROR_RETURN_VALUE, and v8::internal::y.
SignDisplayString()
DirectHandle<String> v8::internal::anonymous_namespace{js-number-format.cc}::SignDisplayString (Isolate * isolate, const icu::UnicodeString & skeleton)
Definition at line 533 of file js-number-format.cc.
                                                                         {
  // Ex: skeleton as
  // "currency/TWD .00 rounding-mode-half-up sign-never"
  if (skeleton.indexOf("sign-never") >= 0) {
    return isolate->factory()->never_string();
  }
  // Ex: skeleton as
  // ".### rounding-mode-half-up sign-always" or
  // "currency/TWD .00 rounding-mode-half-up sign-accounting-always"
  if (skeleton.indexOf("sign-always") >= 0 ||
      skeleton.indexOf("sign-accounting-always") >= 0) {
    return isolate->factory()->always_string();
  }
  // Ex: skeleton as
  // "currency/TWD .00 rounding-mode-half-up sign-accounting-except-zero" or
  // "currency/TWD .00 rounding-mode-half-up sign-except-zero"
  if (skeleton.indexOf("sign-accounting-except-zero") >= 0 ||
      skeleton.indexOf("sign-except-zero") >= 0) {
    return isolate->factory()->exceptZero_string();
  }
  // Ex: skeleton as
  // ".### rounding-mode-half-up sign-negative" or
  // "currency/TWD .00 rounding-mode-half-up sign-accounting-negative"
  if (skeleton.indexOf("sign-accounting-negative") >= 0 ||
      skeleton.indexOf("sign-negative") >= 0) {
    return isolate->factory()->negative_string();
  }
  return isolate->factory()->auto_string();
}
References v8::internal::Isolate::factory().
Referenced by v8::internal::JSNumberFormat::ResolvedOptions().
SignedStringLength()
template<typename StringHandle >
int32_t v8::internal::anonymous_namespace{js-number-format.cc}::SignedStringLength (StringHandle string)
Definition at line 1493 of file js-number-format.cc.
                                                {
  uint32_t unsigned_length = string->length();
  static_assert(String::kMaxLength < std::numeric_limits<int32_t>::max());
  SBXCHECK_LE(unsigned_length, String::kMaxLength);
  return static_cast<int32_t>(unsigned_length);
}
References v8::internal::String::kMaxLength, and SBXCHECK_LE.
Referenced by FormatDecimalString(), IcuFormatNumber(), and v8::internal::IntlMathematicalValue::ToFormattable().
StyleAsString()
DirectHandle<String> v8::internal::anonymous_namespace{js-number-format.cc}::StyleAsString (Isolate * isolate, Style style)
Definition at line 360 of file js-number-format.cc.
                                                                  {
  switch (style) {
    case Style::PERCENT:
      return isolate->factory()->percent_string();
    case Style::CURRENCY:
      return isolate->factory()->currency_string();
    case Style::UNIT:
      return isolate->factory()->unit_string();
    case Style::DECIMAL:
      return isolate->factory()->decimal_string();
  }
  UNREACHABLE();
}
References v8::internal::Isolate::factory(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::JSNumberFormat::ResolvedOptions().
StyleFromSkeleton()
Style v8::internal::anonymous_namespace{js-number-format.cc}::StyleFromSkeleton (const icu::UnicodeString & skeleton)
Definition at line 807 of file js-number-format.cc.
                                                          {
  if (skeleton.indexOf("currency/") >= 0) {
    return Style::CURRENCY;
  }
  if (skeleton.indexOf("percent") >= 0) {
    // percent precision-integer rounding-mode-half-up scale/100
    if (skeleton.indexOf("scale/100") >= 0) {
      return Style::PERCENT;
    } else {
      return Style::UNIT;
    }
  }
  // Before ICU68: "measure-unit/", since ICU68 "unit/"
  if (skeleton.indexOf("unit/") >= 0) {
    return Style::UNIT;
  }
  return Style::DECIMAL;
}
Referenced by FormatToJSArray(), and v8::internal::JSNumberFormat::ResolvedOptions().
ToICUNotation()
icu::number::Notation v8::internal::anonymous_namespace{js-number-format.cc}::ToICUNotation (Notation notation, CompactDisplay compact_display)
Definition at line 176 of file js-number-format.cc.
                                                                    {
  switch (notation) {
    case Notation::STANDARD:
      return icu::number::Notation::simple();
    case Notation::SCIENTIFIC:
      return icu::number::Notation::scientific();
    case Notation::ENGINEERING:
      return icu::number::Notation::engineering();
    // 29. If notation is "compact", then
    case Notation::COMPACT:
      // 29. a. Set numberFormat.[[CompactDisplay]] to compactDisplay.
      if (compact_display == CompactDisplay::SHORT) {
        return icu::number::Notation::compactShort();
      }
      DCHECK(compact_display == CompactDisplay::LONG);
      return icu::number::Notation::compactLong();
  }
}
References v8::internal::DCHECK().
Referenced by v8::internal::JSNumberFormat::New().
ToUNumberFormatRoundingMode()
UNumberFormatRoundingMode v8::internal::anonymous_namespace{js-number-format.cc}::ToUNumberFormatRoundingMode (Intl::RoundingMode rounding_mode)
Definition at line 196 of file js-number-format.cc.
                                    {
  switch (rounding_mode) {
    case Intl::RoundingMode::kCeil:
      return UNumberFormatRoundingMode::UNUM_ROUND_CEILING;
    case Intl::RoundingMode::kFloor:
      return UNumberFormatRoundingMode::UNUM_ROUND_FLOOR;
    case Intl::RoundingMode::kExpand:
      return UNumberFormatRoundingMode::UNUM_ROUND_UP;
    case Intl::RoundingMode::kTrunc:
      return UNumberFormatRoundingMode::UNUM_ROUND_DOWN;
    case Intl::RoundingMode::kHalfCeil:
      return UNumberFormatRoundingMode::UNUM_ROUND_HALF_CEILING;
    case Intl::RoundingMode::kHalfFloor:
      return UNumberFormatRoundingMode::UNUM_ROUND_HALF_FLOOR;
    case Intl::RoundingMode::kHalfExpand:
      return UNumberFormatRoundingMode::UNUM_ROUND_HALFUP;
    case Intl::RoundingMode::kHalfTrunc:
      return UNumberFormatRoundingMode::UNUM_ROUND_HALFDOWN;
    case Intl::RoundingMode::kHalfEven:
      return UNumberFormatRoundingMode::UNUM_ROUND_HALFEVEN;
  }
}
References v8::internal::Intl::kCeil, v8::internal::Intl::kExpand, v8::internal::Intl::kFloor, v8::internal::Intl::kHalfCeil, v8::internal::Intl::kHalfEven, v8::internal::Intl::kHalfExpand, v8::internal::Intl::kHalfFloor, v8::internal::Intl::kHalfTrunc, and v8::internal::Intl::kTrunc.
Referenced by v8::internal::JSNumberFormat::SetDigitOptionsToFormatter().
ToUNumberGroupingStrategy()
UNumberGroupingStrategy v8::internal::anonymous_namespace{js-number-format.cc}::ToUNumberGroupingStrategy (UseGrouping use_grouping)
Definition at line 220 of file js-number-format.cc.
                                                                            {
  switch (use_grouping) {
    case UseGrouping::OFF:
      return UNumberGroupingStrategy::UNUM_GROUPING_OFF;
    case UseGrouping::MIN2:
      return UNumberGroupingStrategy::UNUM_GROUPING_MIN2;
    case UseGrouping::AUTO:
      return UNumberGroupingStrategy::UNUM_GROUPING_AUTO;
    case UseGrouping::ALWAYS:
      return UNumberGroupingStrategy::UNUM_GROUPING_ON_ALIGNED;
  }
}
Referenced by v8::internal::JSNumberFormat::New().
ToUNumberSignDisplay()
UNumberSignDisplay v8::internal::anonymous_namespace{js-number-format.cc}::ToUNumberSignDisplay (SignDisplay sign_display, CurrencySign currency_sign)
Definition at line 144 of file js-number-format.cc.
                                                                    {
  switch (sign_display) {
    case SignDisplay::AUTO:
      if (currency_sign == CurrencySign::ACCOUNTING) {
        return UNumberSignDisplay::UNUM_SIGN_ACCOUNTING;
      }
      DCHECK(currency_sign == CurrencySign::STANDARD);
      return UNumberSignDisplay::UNUM_SIGN_AUTO;
    case SignDisplay::NEVER:
      return UNumberSignDisplay::UNUM_SIGN_NEVER;
    case SignDisplay::ALWAYS:
      if (currency_sign == CurrencySign::ACCOUNTING) {
        return UNumberSignDisplay::UNUM_SIGN_ACCOUNTING_ALWAYS;
      }
      DCHECK(currency_sign == CurrencySign::STANDARD);
      return UNumberSignDisplay::UNUM_SIGN_ALWAYS;
    case SignDisplay::EXCEPT_ZERO:
      if (currency_sign == CurrencySign::ACCOUNTING) {
        return UNumberSignDisplay::UNUM_SIGN_ACCOUNTING_EXCEPT_ZERO;
      }
      DCHECK(currency_sign == CurrencySign::STANDARD);
      return UNumberSignDisplay::UNUM_SIGN_EXCEPT_ZERO;
    case SignDisplay::NEGATIVE:
      if (currency_sign == CurrencySign::ACCOUNTING) {
        return UNumberSignDisplay::UNUM_SIGN_ACCOUNTING_NEGATIVE;
      }
      DCHECK(currency_sign == CurrencySign::STANDARD);
      return UNumberSignDisplay::UNUM_SIGN_NEGATIVE;
  }
}
References v8::internal::DCHECK().
Referenced by v8::internal::JSNumberFormat::New().
ToUNumberUnitWidth() [1/2]
UNumberUnitWidth v8::internal::anonymous_namespace{js-number-format.cc}::ToUNumberUnitWidth (CurrencyDisplay currency_display)
Definition at line 120 of file js-number-format.cc.
                                                                      {
  switch (currency_display) {
    case CurrencyDisplay::SYMBOL:
      return UNumberUnitWidth::UNUM_UNIT_WIDTH_SHORT;
    case CurrencyDisplay::CODE:
      return UNumberUnitWidth::UNUM_UNIT_WIDTH_ISO_CODE;
    case CurrencyDisplay::NAME:
      return UNumberUnitWidth::UNUM_UNIT_WIDTH_FULL_NAME;
    case CurrencyDisplay::NARROW_SYMBOL:
      return UNumberUnitWidth::UNUM_UNIT_WIDTH_NARROW;
  }
}
References NAME.
ToUNumberUnitWidth() [2/2]
UNumberUnitWidth v8::internal::anonymous_namespace{js-number-format.cc}::ToUNumberUnitWidth (UnitDisplay unit_display)
Definition at line 133 of file js-number-format.cc.
                                                              {
  switch (unit_display) {
    case UnitDisplay::SHORT:
      return UNumberUnitWidth::UNUM_UNIT_WIDTH_SHORT;
    case UnitDisplay::LONG:
      return UNumberUnitWidth::UNUM_UNIT_WIDTH_FULL_NAME;
    case UnitDisplay::NARROW:
      return UNumberUnitWidth::UNUM_UNIT_WIDTH_NARROW;
  }
}
Referenced by v8::internal::JSNumberFormat::New().
TrimWhiteSpaceOrLineTerminator()
Handle<String> v8::internal::anonymous_namespace{js-number-format.cc}::TrimWhiteSpaceOrLineTerminator (Isolate * isolate, Handle< String > string)
Definition at line 1669 of file js-number-format.cc.
                                                                     {
  string = String::Flatten(isolate, string);
  std::pair<int, uint32_t> whitespace_offsets;
  {
    DisallowGarbageCollection no_gc;
    String::FlatContent flat = string->GetFlatContent(no_gc);
    if (flat.IsOneByte()) {
      whitespace_offsets = FindLeadingAndTrailingWhiteSpaceOrLineTerminator(
          flat.ToOneByteVector());
    } else {
      whitespace_offsets =
          FindLeadingAndTrailingWhiteSpaceOrLineTerminator(flat.ToUC16Vector());
    }
  }
  if (whitespace_offsets.first == 0 &&
      string->length() == whitespace_offsets.second) {
    return string;
  }
  return isolate->factory()->NewSubString(string, whitespace_offsets.first,
                                          whitespace_offsets.second);
}
References v8::internal::Isolate::factory(), FindLeadingAndTrailingWhiteSpaceOrLineTerminator(), v8::internal::String::FlatContent::IsOneByte(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::string, v8::internal::String::FlatContent::ToOneByteVector(), and v8::internal::String::FlatContent::ToUC16Vector().
Referenced by v8::internal::IntlMathematicalValue::From().
UnitDisplayString()
DirectHandle<String> v8::internal::anonymous_namespace{js-number-format.cc}::UnitDisplayString (Isolate * isolate, const icu::UnicodeString & skeleton)
Definition at line 464 of file js-number-format.cc.
                                                                         {
  // Ex: skeleton as
  // "unit/length-meter .### rounding-mode-half-up unit-width-full-name"
  if (skeleton.indexOf("unit-width-full-name") >= 0) {
    return isolate->factory()->long_string();
  }
  // Ex: skeleton as
  // "unit/length-meter .### rounding-mode-half-up unit-width-narrow".
  if (skeleton.indexOf("unit-width-narrow") >= 0) {
    return isolate->factory()->narrow_string();
  }
  // Ex: skeleton as
  // "unit/length-foot .### rounding-mode-half-up"
  return isolate->factory()->short_string();
}
References v8::internal::Isolate::factory().
Referenced by v8::internal::JSNumberFormat::ResolvedOptions().
UnitFromSkeleton()
std::string v8::internal::anonymous_namespace{js-number-format.cc}::UnitFromSkeleton (const icu::UnicodeString & skeleton)
Definition at line 771 of file js-number-format.cc.
                                                             {
  std::string str;
  str = skeleton.toUTF8String<std::string>(str);
  std::string search("unit/");
  size_t begin = str.find(search);
  if (begin == str.npos) {
    // Special case for "percent".
    if (str.find("percent") != str.npos) {
      return "percent";
    }
    return "";
  }
  // Ex:
  // "unit/acre .### rounding-mode-half-up"
  // b
  // Ex:
  // "unit/milliliter-per-acre .### rounding-mode-half-up"
  // b
  begin += search.size();
  if (begin == str.npos) {
    return "";
  }
  // Find the end of the subtype.
  size_t end = str.find(' ', begin);
  // Ex:
  // "unit/acre .### rounding-mode-half-up"
  // b e
  // Ex:
  // "unit/milliliter-per-acre .### rounding-mode-half-up"
  // b e
  if (end == str.npos) {
    end = str.size();
  }
  return str.substr(begin, end - begin);
}
References v8::internal::compiler::begin(), v8::internal::compiler::end(), v8::internal::anonymous_namespace{simd.cc}::search(), and v8::internal::string.
Referenced by v8::internal::JSNumberFormat::ResolvedOptions().
UseGroupingFromSkeleton()
DirectHandle<Object> v8::internal::anonymous_namespace{js-number-format.cc}::UseGroupingFromSkeleton (Isolate * isolate, const icu::UnicodeString & skeleton)
Definition at line 396 of file js-number-format.cc.
                                                        {
  Factory* factory = isolate->factory();
  static const char* group = "group-";
  int32_t start = skeleton.indexOf(group);
  if (start >= 0) {
    DCHECK_EQ(6, strlen(group));
    icu::UnicodeString check = skeleton.tempSubString(start + 6);
    // Ex: skeleton as
    // .### rounding-mode-half-up group-off
    if (check.startsWith("off")) {
      return factory->false_value();
    }
    // Ex: skeleton as
    // .### rounding-mode-half-up group-min2
    if (check.startsWith("min2")) {
      return isolate->factory()->min2_string();
    }
    // Ex: skeleton as
    // .### rounding-mode-half-up group-on-aligned
    if (check.startsWith("on-aligned")) {
      return isolate->factory()->always_string();
    }
  }
  // Ex: skeleton as
  // .###
  return isolate->factory()->auto_string();
}
References DCHECK_EQ, and v8::internal::Isolate::factory().
Referenced by v8::internal::JSNumberFormat::ResolvedOptions().