v8::internal::anonymous_namespace{template-objects.cc} Namespace Reference
Functions
bool CachedTemplateMatches (Isolate *isolate, Tagged< NativeContext > native_context, Tagged< JSArray > entry, int function_literal_id, int slot_id, DisallowGarbageCollection &no_gc)
Function Documentation
CachedTemplateMatches()
bool v8::internal::anonymous_namespace{template-objects.cc}::CachedTemplateMatches (Isolate * isolate, Tagged< NativeContext > native_context, Tagged< JSArray > entry, int function_literal_id, int slot_id, DisallowGarbageCollection & no_gc)
Definition at line 19 of file template-objects.cc.
                                                                          {
  if (native_context->is_js_array_template_literal_object_map(
          entry->map(isolate))) {
    Tagged<TemplateLiteralObject> template_object =
        Cast<TemplateLiteralObject>(entry);
    return template_object->function_literal_id() == function_literal_id &&
           template_object->slot_id() == slot_id;
  }
  DirectHandle<JSArray> entry_handle(entry, isolate);
  Tagged<Smi> cached_function_literal_id =
      Cast<Smi>(*JSReceiver::GetDataProperty(
          isolate, entry_handle,
          isolate->factory()->template_literal_function_literal_id_symbol()));
  if (cached_function_literal_id.value() != function_literal_id) return false;
  Tagged<Smi> cached_slot_id = Cast<Smi>(*JSReceiver::GetDataProperty(
      isolate, entry_handle,
      isolate->factory()->template_literal_slot_id_symbol()));
  if (cached_slot_id.value() != slot_id) return false;
  return true;
}
References v8::internal::Isolate::factory(), v8::internal::function_literal_id, v8::internal::JSReceiver::GetDataProperty(), v8::internal::native_context, and v8::internal::Tagged< Smi >::value().
Referenced by v8::internal::TemplateObjectDescription::GetTemplateObject().