v8::internal::maglev::anonymous_namespace{maglev-ir-x64.cc} Namespace Reference
Enumerations
enum class ReduceInterruptBudgetType { kLoop
, kReturn
 }
Functions
void HandleInterruptsAndTiering (MaglevAssembler *masm, ZoneLabelRef done, Node *node, ReduceInterruptBudgetType type)
void GenerateReduceInterruptBudget (MaglevAssembler *masm, Node *node, Register feedback_cell, ReduceInterruptBudgetType type, int amount)
Enumeration Type Documentation
ReduceInterruptBudgetType
enum v8::internal::maglev::anonymous_namespace{maglev-ir-x64.cc}::ReduceInterruptBudgetType [strong]
Enumerator
kLoop
kReturn
Definition at line 807 of file maglev-ir-x64.cc.
{ kLoop, kReturn };
Function Documentation
GenerateReduceInterruptBudget()
void v8::internal::maglev::anonymous_namespace{maglev-ir-x64.cc}::GenerateReduceInterruptBudget (MaglevAssembler * masm, Node * node, Register feedback_cell, ReduceInterruptBudgetType type, int amount)
Definition at line 850 of file maglev-ir-x64.cc.
                                                                               {
  MaglevAssembler::TemporaryRegisterScope temps(masm);
  __ subl(FieldOperand(feedback_cell, FeedbackCell::kInterruptBudgetOffset),
          Immediate(amount));
  ZoneLabelRef done(masm);
  __ JumpToDeferredIf(less, HandleInterruptsAndTiering, done, node, type);
  __ bind(*done);
}
References __, v8::internal::FieldOperand(), HandleInterruptsAndTiering(), v8::internal::less, and v8::internal::tracing::type.
HandleInterruptsAndTiering()
void v8::internal::maglev::anonymous_namespace{maglev-ir-x64.cc}::HandleInterruptsAndTiering (MaglevAssembler * masm, ZoneLabelRef done, Node * node, ReduceInterruptBudgetType type)
Definition at line 809 of file maglev-ir-x64.cc.
                                                                            {
  // For loops, first check for interrupts. Don't do this for returns, as we
  // can't lazy deopt to the end of a return.
  if (type == ReduceInterruptBudgetType::kLoop) {
    Label next;
    // Here, we only care about interrupts since we've already guarded against
    // real stack overflows on function entry.
    __ cmpq(rsp, __ StackLimitAsOperand(StackLimitKind::kInterruptStackLimit));
    __ j(above, &next);
    // An interrupt has been requested and we must call into runtime to handle
    // it; since we already pay the call cost, combine with the TieringManager
    // call.
    {
      SaveRegisterStateForCall save_register_state(masm,
                                                   node->register_snapshot());
      __ Move(kContextRegister, masm->native_context().object());
      __ Push(MemOperand(rbp, StandardFrameConstants::kFunctionOffset));
      __ CallRuntime(Runtime::kBytecodeBudgetInterruptWithStackCheck_Maglev, 1);
      save_register_state.DefineSafepointWithLazyDeopt(node->lazy_deopt_info());
    }
    __ jmp(*done); // All done, continue.
    __ bind(&next);
  }
  // No pending interrupts. Call into the TieringManager if needed.
  {
    SaveRegisterStateForCall save_register_state(masm,
                                                 node->register_snapshot());
    __ Move(kContextRegister, masm->native_context().object());
    __ Push(MemOperand(rbp, StandardFrameConstants::kFunctionOffset));
    // Note: must not cause a lazy deopt!
    __ CallRuntime(Runtime::kBytecodeBudgetInterrupt_Maglev, 1);
    save_register_state.DefineSafepoint();
  }
  __ jmp(*done);
}
References __, v8::internal::above, v8::internal::maglev::SaveRegisterStateForCall::DefineSafepoint(), v8::internal::maglev::SaveRegisterStateForCall::DefineSafepointWithLazyDeopt(), v8::internal::kContextRegister, v8::internal::StandardFrameConstants::kFunctionOffset, v8::internal::kInterruptStackLimit, v8::internal::maglev::NodeBase::lazy_deopt_info(), v8::internal::maglev::MaglevAssembler::native_context(), v8::internal::compiler::NativeContextRef::object(), v8::internal::maglev::NodeBase::register_snapshot(), and v8::internal::tracing::type.
Referenced by GenerateReduceInterruptBudget().