v8::internal::anonymous_namespace{profile-generator.cc} Namespace Reference
Functions
void BuildNodeValue (const ProfileNode *node, TracedValue *value)
void FlattenNodesTree (const v8::CpuProfileNode *node, std::vector< const v8::CpuProfileNode * > *nodes)
int64_t GreatestCommonDivisor (int64_t a, int64_t b)
Function Documentation
BuildNodeValue()
void v8::internal::anonymous_namespace{profile-generator.cc}::BuildNodeValue (const ProfileNode * node, TracedValue * value)
Definition at line 663 of file profile-generator.cc.
                                                                 {
  const CodeEntry* entry = node->entry();
  value->BeginDictionary("callFrame");
  value->SetString("functionName", entry->name());
  if (*entry->resource_name()) {
    value->SetString("url", entry->resource_name());
  }
  value->SetInteger("scriptId", entry->script_id());
  if (entry->line_and_column().line) {
    value->SetInteger("lineNumber", entry->line_and_column().line - 1);
  }
  if (entry->line_and_column().line) {
    value->SetInteger("columnNumber", entry->line_and_column().column - 1);
  }
  value->SetString("codeType", entry->code_type_string());
  value->EndDictionary();
  value->SetInteger("id", node->id());
  if (node->parent()) {
    value->SetInteger("parent", node->parent()->id());
  }
  const char* deopt_reason = entry->bailout_reason();
  if (deopt_reason && deopt_reason[0] && strcmp(deopt_reason, "no reason")) {
    value->SetString("deoptReason", deopt_reason);
  }
}
References v8::internal::CodeEntry::bailout_reason(), v8::internal::CodeEntry::code_type_string(), v8::internal::LineAndColumn::column, v8::internal::ProfileNode::entry(), v8::internal::ProfileNode::id(), v8::internal::LineAndColumn::line, v8::internal::CodeEntry::line_and_column(), v8::internal::CodeEntry::name(), v8::internal::ProfileNode::parent(), v8::internal::CodeEntry::resource_name(), v8::internal::CodeEntry::script_id(), and v8::internal::value.
Referenced by v8::internal::CpuProfile::StreamPendingTraceEvents().
FlattenNodesTree()
void v8::internal::anonymous_namespace{profile-generator.cc}::FlattenNodesTree (const v8::CpuProfileNode * node, std::vector< const v8::CpuProfileNode * > * nodes)
Definition at line 790 of file profile-generator.cc.
                                                                 {
  nodes->emplace_back(node);
  const int childrenCount = node->GetChildrenCount();
  for (int i = 0; i < childrenCount; i++)
    FlattenNodesTree(node->GetChild(i), nodes);
}
References v8::CpuProfileNode::GetChild(), and v8::CpuProfileNode::GetChildrenCount().
Referenced by v8::internal::CpuProfileJSONSerializer::SerializeNodes().
GreatestCommonDivisor()
int64_t v8::internal::anonymous_namespace{profile-generator.cc}::GreatestCommonDivisor (int64_t a, int64_t b)
Definition at line 1174 of file profile-generator.cc.
                                                    {
  return b ? GreatestCommonDivisor(b, a % b) : a;
}
Referenced by v8::internal::CpuProfilesCollection::GetCommonSamplingInterval().