v8::internal::anonymous_namespace{runtime-atomics.cc} Namespace Reference
Functions
template<typename WriteOperation >
Tagged< Object > AtomicFieldWrite (Isolate *isolate, DirectHandle< JSObject > object, Handle< Name > field_name, DirectHandle< Object > value, WriteOperation write_operation)
Function Documentation
AtomicFieldWrite()
template<typename WriteOperation >
Tagged<Object> v8::internal::anonymous_namespace{runtime-atomics.cc}::AtomicFieldWrite (Isolate * isolate, DirectHandle< JSObject > object, Handle< Name > field_name, DirectHandle< Object > value, WriteOperation write_operation)
Definition at line 649 of file runtime-atomics.cc.
                                                                {
  LookupIterator it(isolate, object, PropertyKey(isolate, field_name),
                    LookupIterator::OWN);
  Maybe<bool> result = Nothing<bool>();
  if (it.IsFound()) {
    if (!it.IsReadOnly()) {
      return write_operation(it);
    }
    // Shared structs and arrays are non-extensible and have non-configurable,
    // writable, enumerable properties. The only exception is SharedArrays'
    // "length" property, which is non-writable.
    result = Object::WriteToReadOnlyProperty(&it, value, Just(kThrowOnError));
  } else {
    // Shared structs are non-extensible. Instead of duplicating logic, call
    // Object::AddDataProperty to handle the error case.
    result = Object::AddDataProperty(&it, value, NONE, Just(kThrowOnError),
                                     StoreOrigin::kMaybeKeyed);
  }
  // Treat as strict code and always throw an error.
  DCHECK(result.IsNothing());
  USE(result);
  return ReadOnlyRoots(isolate).exception();
}
References v8::internal::Object::AddDataProperty(), v8::internal::DCHECK(), v8::internal::LookupIterator::IsFound(), v8::internal::LookupIterator::IsReadOnly(), v8::Just(), v8::internal::kMaybeKeyed, v8::internal::kThrowOnError, v8::internal::NONE, v8::internal::LookupIterator::OWN, v8::base::internal::result, USE, v8::internal::value, and v8::internal::Object::WriteToReadOnlyProperty().
Referenced by v8::internal::RUNTIME_FUNCTION().