v8::internal::anonymous_namespace{symbolizer.cc} Namespace Reference
Functions
CodeEntry * EntryForVMState (StateTag tag)
Function Documentation
EntryForVMState()
CodeEntry* v8::internal::anonymous_namespace{symbolizer.cc}::EntryForVMState (StateTag tag)
Definition at line 25 of file symbolizer.cc.
                                         {
  switch (tag) {
    case GC:
      return CodeEntry::gc_entry();
    case JS:
    case PARSER:
    case COMPILER:
    case BYTECODE_COMPILER:
    case ATOMICS_WAIT:
    // DOM events handlers are reported as OTHER / EXTERNAL entries.
    // To avoid confusing people, let's put all these entries into
    // one bucket.
    case OTHER:
    case EXTERNAL:
    case LOGGING:
      return CodeEntry::program_entry();
    case IDLE:
      return CodeEntry::idle_entry();
  }
}
References v8::ATOMICS_WAIT, v8::BYTECODE_COMPILER, v8::COMPILER, v8::EXTERNAL, v8::GC, v8::internal::CodeEntry::gc_entry(), v8::IDLE, v8::internal::CodeEntry::idle_entry(), v8::JS, v8::LOGGING, v8::OTHER, v8::PARSER, and v8::internal::CodeEntry::program_entry().
Referenced by v8::internal::Symbolizer::SymbolizeTickSample().