v8::internal::anonymous_namespace{string.cc} Namespace Reference
Classes
class WriteToFlat_RepeatOptimizer
Typedefs
using wtf_stack_t = base::SmallVector< Tagged< String >, 32 >
using wtf_stack_top_t = Tagged< String >
Enumerations
enum WriteToFlatImplVariant { kWTFSeqOneByte
, kWTFGeneric
 }
Functions
template<class StringClass >
void MigrateExternalStringResource (Isolate *isolate, Tagged< ExternalString > from, Tagged< StringClass > to)
void MigrateExternalString (Isolate *isolate, Tagged< String > string, Tagged< String > internalized)
template<bool is_one_byte>
Tagged< Map > ComputeExternalStringMap (Isolate *isolate, Tagged< String > string, int size)
template<typename SinkCharT >
SinkCharT * WriteNonConsToFlat2 (Tagged< String > src, StringShape shape, SinkCharT *dst, uint32_t src_index, uint32_t length, const SharedStringAccessGuardIfNeeded &aguard, const DisallowGarbageCollection &no_gc)
void wtf_push (wtf_stack_top_t &top, wtf_stack_t &stack, Tagged< String > value)
bool wtf_try_pop (wtf_stack_top_t &top, wtf_stack_t &stack, Tagged< String > *value)
template<WriteToFlatImplVariant kVariant, typename SinkCharT >
void WriteToFlat2Impl (SinkCharT *&rdst, wtf_stack_top_t &top, wtf_stack_t &stack, WriteToFlat_RepeatOptimizer< SinkCharT > &ropt, const SharedStringAccessGuardIfNeeded &aguard, const DisallowGarbageCollection &no_gc)
uint32_t ToValidIndex (Tagged< String > str, Tagged< Object > number)
template<typename T >
int SearchString (Isolate *isolate, String::FlatContent receiver_content, base::Vector< T > pat_vector, int start_index)
template<typename schar , typename pchar >
int StringMatchBackwards (base::Vector< const schar > subject, base::Vector< const pchar > pattern, int idx)
template<typename Char >
bool IsIdentifierVector (base::Vector< Char > vec)
template<typename Char >
uint32_t HashString (Tagged< String > string, size_t start, uint32_t length, uint64_t seed, const SharedStringAccessGuardIfNeeded &access_guard)
Typedef Documentation
wtf_stack_t
using v8::internal::anonymous_namespace{string.cc}::wtf_stack_t = typedef base::SmallVector<Tagged<String>, 32>
Definition at line 930 of file string.cc.
wtf_stack_top_t
using v8::internal::anonymous_namespace{string.cc}::wtf_stack_top_t = typedef Tagged<String>
Definition at line 931 of file string.cc.
Enumeration Type Documentation
WriteToFlatImplVariant
enum v8::internal::anonymous_namespace{string.cc}::WriteToFlatImplVariant
Enumerator
kWTFSeqOneByte
kWTFGeneric
Definition at line 921 of file string.cc.
                            {
  kWTFSeqOneByte,
  kWTFGeneric,
};
Function Documentation
ComputeExternalStringMap()
template<bool is_one_byte>
Tagged<Map> v8::internal::anonymous_namespace{string.cc}::ComputeExternalStringMap (Isolate * isolate, Tagged< String > string, int size)
Definition at line 246 of file string.cc.
                                               {
  ReadOnlyRoots roots(isolate);
  StringShape shape(string);
  const bool is_internalized = shape.IsInternalized();
  const bool is_shared = shape.IsShared();
  if constexpr (is_one_byte) {
    if (size < static_cast<int>(sizeof(ExternalString))) {
      if (is_internalized) {
        return roots.uncached_external_internalized_one_byte_string_map();
      } else {
        return is_shared ? roots.shared_uncached_external_one_byte_string_map()
                         : roots.uncached_external_one_byte_string_map();
      }
    } else {
      if (is_internalized) {
        return roots.external_internalized_one_byte_string_map();
      } else {
        return is_shared ? roots.shared_external_one_byte_string_map()
                         : roots.external_one_byte_string_map();
      }
    }
  } else {
    if (size < static_cast<int>(sizeof(ExternalString))) {
      if (is_internalized) {
        return roots.uncached_external_internalized_two_byte_string_map();
      } else {
        return is_shared ? roots.shared_uncached_external_two_byte_string_map()
                         : roots.uncached_external_two_byte_string_map();
      }
    } else {
      if (is_internalized) {
        return roots.external_internalized_two_byte_string_map();
      } else {
        return is_shared ? roots.shared_external_two_byte_string_map()
                         : roots.external_two_byte_string_map();
      }
    }
  }
}
References v8::internal::is_shared, v8::internal::StringShape::IsInternalized(), v8::internal::StringShape::IsShared(), and size().
HashString()
template<typename Char >
uint32_t v8::internal::anonymous_namespace{string.cc}::HashString (Tagged< String > string, size_t start, uint32_t length, uint64_t seed, const SharedStringAccessGuardIfNeeded & access_guard)
Definition at line 1795 of file string.cc.
                                                                         {
  DisallowGarbageCollection no_gc;
  if (length > String::kMaxHashCalcLength) {
    return StringHasher::GetTrivialHash(length);
  }
  std::unique_ptr<Char[]> buffer;
  const Char* chars;
  if (IsConsString(string)) {
    DCHECK_EQ(0, start);
    DCHECK(!string->IsFlat());
    buffer.reset(new Char[length]);
    String::WriteToFlat(string, buffer.get(), 0, length, access_guard);
    chars = buffer.get();
  } else {
    chars = string->GetDirectStringChars<Char>(no_gc, access_guard) + start;
  }
  return StringHasher::HashSequentialString<Char>(chars, length, seed);
}
References DCHECK, DCHECK_EQ, v8::internal::InstanceTypeChecker::IsConsString(), v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::string.
IsIdentifierVector()
template<typename Char >
bool v8::internal::anonymous_namespace{string.cc}::IsIdentifierVector (base::Vector< Char > vec)
Definition at line 1766 of file string.cc.
                                              {
  if (vec.empty()) {
    return false;
  }
  if (!IsIdentifierStart(vec[0])) {
    return false;
  }
  for (size_t i = 1; i < vec.size(); ++i) {
    if (!IsIdentifierPart(vec[i])) {
      return false;
    }
  }
  return true;
}
References v8::base::Vector< T >::empty(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::IsIdentifierPart(), v8::internal::IsIdentifierStart(), and v8::base::Vector< T >::size().
Referenced by v8::internal::String::IsIdentifier().
MigrateExternalString()
void v8::internal::anonymous_namespace{string.cc}::MigrateExternalString (Isolate * isolate, Tagged< String > string, Tagged< String > internalized)
Definition at line 106 of file string.cc.
                                                        {
  if (IsExternalOneByteString(internalized)) {
    MigrateExternalStringResource(isolate, Cast<ExternalString>(string),
                                  Cast<ExternalOneByteString>(internalized));
  } else if (IsExternalTwoByteString(internalized)) {
    MigrateExternalStringResource(isolate, Cast<ExternalString>(string),
                                  Cast<ExternalTwoByteString>(internalized));
  } else {
    // If the external string is duped into an existing non-external
    // internalized string, free its resource (it's about to be rewritten
    // into a ThinString below).
    isolate->heap()->FinalizeExternalString(string);
  }
}
References v8::internal::Heap::FinalizeExternalString(), v8::internal::Isolate::heap(), and MigrateExternalStringResource().
Referenced by v8::internal::String::MakeThin().
MigrateExternalStringResource()
template<class StringClass >
void v8::internal::anonymous_namespace{string.cc}::MigrateExternalStringResource (Isolate * isolate, Tagged< ExternalString > from, Tagged< StringClass > to)
Definition at line 87 of file string.cc.
                                                           {
  Address to_resource_address = to->resource_as_address();
  if (to_resource_address == kNullAddress) {
    Tagged<StringClass> cast_from = Cast<StringClass>(from);
    // |to| is a just-created internalized copy of |from|. Migrate the resource.
    to->SetResource(isolate, cast_from->resource());
    // Zap |from|'s resource pointer to reflect the fact that |from| has
    // relinquished ownership of its resource.
    isolate->heap()->UpdateExternalString(
        from, Cast<ExternalString>(from)->ExternalPayloadSize(), 0);
    cast_from->SetResource(isolate, nullptr);
  } else if (to_resource_address != from->resource_as_address()) {
    // |to| already existed and has its own resource. Finalize |from|.
    isolate->heap()->FinalizeExternalString(from);
  }
}
References v8::internal::Heap::FinalizeExternalString(), v8::internal::Isolate::heap(), v8::internal::kNullAddress, and v8::internal::Heap::UpdateExternalString().
Referenced by MigrateExternalString().
SearchString()
template<typename T >
int v8::internal::anonymous_namespace{string.cc}::SearchString (Isolate * isolate, String::FlatContent receiver_content, base::Vector< T > pat_vector, int start_index)
Definition at line 1449 of file string.cc.
                                                            {
  if (receiver_content.IsOneByte()) {
    return SearchString(isolate, receiver_content.ToOneByteVector(), pat_vector,
                        start_index);
  }
  return SearchString(isolate, receiver_content.ToUC16Vector(), pat_vector,
                      start_index);
}
References v8::internal::String::FlatContent::IsOneByte(), v8::internal::String::FlatContent::ToOneByteVector(), and v8::internal::String::FlatContent::ToUC16Vector().
StringMatchBackwards()
template<typename schar , typename pchar >
int v8::internal::anonymous_namespace{string.cc}::StringMatchBackwards (base::Vector< const schar > subject, base::Vector< const pchar > pattern, int idx)
Definition at line 1650 of file string.cc.
                                                                   {
  int pattern_length = pattern.length();
  DCHECK_GE(pattern_length, 1);
  DCHECK(idx + pattern_length <= subject.length());
  if (sizeof(schar) == 1 && sizeof(pchar) > 1) {
    for (int i = 0; i < pattern_length; i++) {
      base::uc16 c = pattern[i];
      if (c > String::kMaxOneByteCharCode) {
        return -1;
      }
    }
  }
  pchar pattern_first_char = pattern[0];
  for (int i = idx; i >= 0; i--) {
    if (subject[i] != pattern_first_char) continue;
    int j = 1;
    while (j < pattern_length) {
      if (pattern[j] != subject[i + j]) {
        break;
      }
      j++;
    }
    if (j == pattern_length) {
      return i;
    }
  }
  return -1;
}
References DCHECK, DCHECK_GE, v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::base::Vector< T >::length().
Referenced by v8::internal::String::LastIndexOf().
ToValidIndex()
uint32_t v8::internal::anonymous_namespace{string.cc}::ToValidIndex (Tagged< String > str, Tagged< Object > number)
Definition at line 1412 of file string.cc.
                                                                 {
  uint32_t index = PositiveNumberToUint32(number);
  uint32_t length = str->length();
  if (index > length) return length;
  return index;
}
References v8::internal::index, v8::internal::length, and v8::internal::PositiveNumberToUint32().
Referenced by v8::internal::String::IndexOf(), and v8::internal::String::LastIndexOf().
WriteNonConsToFlat2()
template<typename SinkCharT >
SinkCharT* v8::internal::anonymous_namespace{string.cc}::WriteNonConsToFlat2 (Tagged< String > src, StringShape shape, SinkCharT * dst, uint32_t src_index, uint32_t length, const SharedStringAccessGuardIfNeeded & aguard, const DisallowGarbageCollection & no_gc)
Definition at line 882 of file string.cc.
                                                                       {
  DCHECK(!shape.IsCons());
  DCHECK_LE(src_index + length, src->length());
  return shape.DispatchToSpecificType(
      src, absl::Overload{
               [&](Tagged<SeqOneByteString> s) {
                 CopyChars(dst, s->GetChars(no_gc, aguard) + src_index, length);
                 return dst + length;
               },
               [&](Tagged<SeqTwoByteString> s) {
                 CopyChars(dst, s->GetChars(no_gc, aguard) + src_index, length);
                 return dst + length;
               },
               [&](Tagged<ExternalOneByteString> s) {
                 CopyChars(dst, s->GetChars() + src_index, length);
                 return dst + length;
               },
               [&](Tagged<ExternalTwoByteString> s) {
                 CopyChars(dst, s->GetChars() + src_index, length);
                 return dst + length;
               },
               [&](Tagged<SlicedString> s) {
                 Tagged<String> parent = s->parent();
                 return WriteNonConsToFlat2(parent, StringShape{parent}, dst,
                                            src_index + s->offset(), length,
                                            aguard, no_gc);
               },
               [&](Tagged<ThinString> s) {
                 Tagged<String> actual = Cast<ThinString>(src)->actual();
                 return WriteNonConsToFlat2(actual, StringShape{actual}, dst,
                                            src_index, length, aguard, no_gc);
               },
               [&](Tagged<ConsString>) -> SinkCharT* { UNREACHABLE(); }});
}
References v8::internal::CopyChars(), DCHECK, DCHECK_LE, v8::internal::StringShape::DispatchToSpecificType(), v8::internal::StringShape::IsCons(), v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and UNREACHABLE.
Referenced by WriteToFlat2Impl().
WriteToFlat2Impl()
template<WriteToFlatImplVariant kVariant, typename SinkCharT >
void v8::internal::anonymous_namespace{string.cc}::WriteToFlat2Impl (SinkCharT *& rdst, wtf_stack_top_t & top, wtf_stack_t & stack, WriteToFlat_RepeatOptimizer< SinkCharT > & ropt, const SharedStringAccessGuardIfNeeded & aguard, const DisallowGarbageCollection & no_gc) [inline]
Definition at line 997 of file string.cc.
                                                                        {
  Tagged<String> s;
  while (V8_LIKELY(wtf_try_pop(top, stack, &s))) {
    StringShape shape{s};
    if constexpr (kVariant == kWTFGeneric) {
      if (V8_UNLIKELY(ropt.TryApply(s, &rdst))) continue;
    }
    // Descend into the rightmost leaf and push left branches onto the stack.
    //
    // Alternatively, we could always flatten the shorter side first, where
    // substring length is used as a heuristic for substring tree depth, in
    // order to minimize stack size. That approach has different trade-offs,
    // for example: the stack would have to store both the string and the
    // current `rdst` value, and the write sequence may be less cache-friendly.
    while (shape.IsCons()) {
      auto cons = Cast<ConsString>(s);
      auto first = cons->first();
      wtf_push(top, stack, first);
      s = cons->second();
      if (V8_UNLIKELY(s == first)) {
        ropt.RecordFirstOccurrence(s, rdst);
      }
      shape = StringShape{s};
    }
    if constexpr (kVariant == kWTFSeqOneByte) {
      if (!shape.IsSequentialOneByte() || V8_UNLIKELY(ropt.enabled())) {
        // Exit the specialized variant. Note the caller MUST follow up with
        // the kGeneric variant.
        wtf_push(top, stack, s);
        return;
      }
      uint8_t* chars = Cast<SeqOneByteString>(s)->GetChars(no_gc, aguard);
      uint32_t length = s->length();
      rdst -= length;
      CopyChars(rdst, chars, length);
    } else {
      static_assert(kVariant == kWTFGeneric);
      uint32_t length = s->length();
      rdst -= length;
      WriteNonConsToFlat2(s, shape, rdst, 0, length, aguard, no_gc);
    }
  }
}
References v8::internal::CopyChars(), v8::internal::anonymous_namespace{string.cc}::WriteToFlat_RepeatOptimizer< SinkCharT >::enabled(), kWTFGeneric, kWTFSeqOneByte, v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::anonymous_namespace{string.cc}::WriteToFlat_RepeatOptimizer< SinkCharT >::RecordFirstOccurrence(), v8::internal::stack, v8::internal::anonymous_namespace{string.cc}::WriteToFlat_RepeatOptimizer< SinkCharT >::TryApply(), V8_LIKELY, V8_UNLIKELY, WriteNonConsToFlat2(), wtf_push(), and wtf_try_pop().
wtf_push()
void v8::internal::anonymous_namespace{string.cc}::wtf_push (wtf_stack_top_t & top, wtf_stack_t & stack, Tagged< String > value) [inline]
Definition at line 933 of file string.cc.
                                              {
  if (!top.is_null()) stack.push_back(top);
  top = value;
}
References v8::internal::Tagged< HeapObject >::is_null(), v8::internal::stack, and v8::internal::value.
Referenced by WriteToFlat2Impl().
wtf_try_pop()
bool v8::internal::anonymous_namespace{string.cc}::wtf_try_pop (wtf_stack_top_t & top, wtf_stack_t & stack, Tagged< String > * value) [inline]
Definition at line 939 of file string.cc.
                                                  {
  if (V8_LIKELY(!top.is_null())) {
    *value = top;
    top = {};
    return true;
  }
  if (V8_LIKELY(!stack.empty())) {
    *value = stack.back();
    stack.pop_back();
    return true;
  }
  return false;
}
References v8::internal::Tagged< HeapObject >::is_null(), v8::internal::stack, V8_LIKELY, and v8::internal::value.
Referenced by WriteToFlat2Impl().