v8::internal::compiler::anonymous_namespace{dead-code-elimination.cc} Namespace Reference
Functions
bool NoReturn (Node *node)
Node * FindDeadInput (Node *node)
Function Documentation
FindDeadInput()
Node* v8::internal::compiler::anonymous_namespace{dead-code-elimination.cc}::FindDeadInput (Node * node)
Definition at line 38 of file dead-code-elimination.cc.
                                {
  for (Node* input : node->inputs()) {
    if (NoReturn(input)) return input;
  }
  return nullptr;
}
References v8::internal::compiler::Node::inputs(), and NoReturn().
Referenced by v8::internal::compiler::DeadCodeElimination::ReduceDeoptimizeOrReturnOrTerminateOrTailCall(), v8::internal::compiler::DeadCodeElimination::ReduceEffectNode(), and v8::internal::compiler::DeadCodeElimination::ReducePureNode().
NoReturn()
bool v8::internal::compiler::anonymous_namespace{dead-code-elimination.cc}::NoReturn (Node * node)
Definition at line 31 of file dead-code-elimination.cc.
                          {
  return node->opcode() == IrOpcode::kDead ||
         node->opcode() == IrOpcode::kUnreachable ||
         node->opcode() == IrOpcode::kDeadValue ||
         NodeProperties::GetTypeOrAny(node).IsNone();
}
References v8::internal::compiler::NodeProperties::GetTypeOrAny(), v8::internal::compiler::Type::IsNone(), v8::internal::wasm::kUnreachable, and v8::internal::compiler::Node::opcode().
Referenced by FindDeadInput().