v8::internal::compiler::js_node_wrapper_utils Namespace Reference
Functions
TNode< Oddball > UndefinedConstant (JSGraph *jsgraph)
Function Documentation
UndefinedConstant()
TNode< Oddball > v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant (JSGraph * jsgraph)
Definition at line 46 of file js-operator.cc.
                                                   {
  return TNode<Oddball>::UncheckedCast(jsgraph->UndefinedConstant());
}
References v8::internal::TNode< T >::UncheckedCast().
Referenced by v8::internal::BaseCollectionsAssembler::AddConstructorEntries(), v8::internal::CodeStubAssembler::AllocateArrayList(), v8::internal::anonymous_namespace{builtins-async-generator-gen.cc}::AsyncGeneratorBuiltinsAssembler::AllocateAsyncGeneratorRequest(), v8::internal::compiler::JSCallReducerAssembler::AllocateEmptyJSArray(), v8::internal::TypedArrayBuiltinsAssembler::AllocateEmptyOnHeapBuffer(), v8::internal::CodeStubAssembler::AllocateNameDictionaryWithCapacity(), v8::internal::CodeStubAssembler::AllocateOrderedHashTableWithCapacity(), v8::internal::CodeStubAssembler::AllocateSimpleNameDictionaryWithCapacity(), v8::internal::compiler::JSCallOrConstructNode::ArgumentOrUndefined(), v8::internal::compiler::JSCallReducerAssembler::ArgumentOrUndefined(), v8::internal::CodeStubAssembler::ArrayCreate(), v8::internal::anonymous_namespace{builtins-async-generator-gen.cc}::AsyncGeneratorBuiltinsAssembler::AsyncGeneratorAwait(), v8::internal::AsyncBuiltinsAssembler::Await(), v8::internal::compiler::JSNativeContextSpecialization::BuildExtendPropertiesBackingStore(), v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyStore(), v8::internal::CodeStubAssembler::CallGetterIfAccessor(), v8::internal::interpreter::InterpreterAssembler::CallJSAndDispatch(), v8::internal::compiler::PromiseBuiltinReducerAssembler::CallPromiseExecutor(), v8::internal::compiler::PromiseBuiltinReducerAssembler::CallPromiseReject(), v8::internal::compiler::BytecodeGraphBuilder::CheckContextExtensionAtDepth(), v8::internal::compiler::JSGraph::Constant(), v8::internal::interpreter::InterpreterAssembler::Construct(), v8::internal::RegExpBuiltinsAssembler::ConstructNewResultFromMatchInfo(), v8::internal::interpreter::InterpreterAssembler::ConstructWithSpread(), v8::internal::ArrayBuiltinsAssembler::CreateArrayDispatchNoArgument(), v8::internal::ArrayBuiltinsAssembler::CreateArrayDispatchSingleArgument(), v8::internal::compiler::JSInliner::CreateArtificialFrameState(), v8::internal::ObjectEntriesValuesBuiltinsAssembler::FastGetOwnValuesOrEntries(), v8::internal::ConstructorBuiltinsAssembler::FastNewFunctionContext(), v8::internal::CodeStubAssembler::FillPropertyArrayWithUndefined(), v8::internal::ObjectBuiltinsAssembler::FromPropertyDescriptor(), v8::internal::anonymous_namespace{builtins-async-iterator-gen.cc}::AsyncFromSyncBuiltinsAssembler::Generate_AsyncFromSyncIteratorMethod(), v8::internal::AccessorAssembler::GenerateLoadIC_NoFeedback(), v8::internal::AccessorAssembler::GenericElementLoad(), v8::internal::AccessorAssembler::GenericPropertyLoad(), v8::internal::ObjectBuiltinsAssembler::GetAccessorOrUndefined(), v8::internal::CodeStubAssembler::GetInterestingProperty(), v8::internal::CodeStubAssembler::GotoIfHasContextExtensionUpToDepth(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerCase(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerLoadNamedCase(), v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER(), v8::internal::CodeStubAssembler::InitializePropertyDescriptorObject(), v8::internal::compiler::JSInliner::InlineCall(), v8::internal::GeneratorBuiltinsAssembler::InnerResume(), v8::internal::CodeStubAssembler::InsertEntry(), v8::internal::CodeStubAssembler::InstanceOf(), v8::internal::interpreter::IntrinsicsGenerator::InvokeIntrinsic(), v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::InterpreterJSCallAssembler::JSCall(), v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::InterpreterJSCallAssembler::JSCallN(), v8::internal::KeyedStoreGenericAssembler::KeyedStoreGeneric(), v8::internal::BaseCollectionsAssembler::LoadAndNormalizeFixedArrayElement(), v8::internal::BaseCollectionsAssembler::LoadAndNormalizeFixedDoubleArrayElement(), v8::internal::CodeStubAssembler::LoadElementAndPrepareForStore(), v8::internal::CodeStubAssembler::LoadFeedbackVector(), v8::internal::FeedbackCollectorReducer< Next >::LoadFeedbackVectorOrUndefinedIfJitless(), v8::internal::interpreter::InterpreterAssembler::LoadFeedbackVectorOrUndefinedIfJitless(), v8::internal::CodeStubAssembler::LoadFixedArrayBaseElementAsTagged(), v8::internal::CodeStubAssembler::LoadMapBackPointer(), v8::internal::CodeStubAssembler::NameDictionaryLookup(), v8::internal::CodeStubAssembler::NumberDictionaryLookup(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeAt(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFind(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeForEach(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeReduce(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeShift(), v8::internal::compiler::JSCallReducer::ReduceCollectionIteratorPrototypeNext(), v8::internal::compiler::FastApiCallReducerAssembler::ReduceFastApiCall(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeApply(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeCall(), v8::internal::compiler::JSTypedLowering::ReduceJSCall(), v8::internal::compiler::JSTypedLowering::ReduceJSConstruct(), v8::internal::compiler::JSTypedLowering::ReduceJSConstructForwardVarargs(), v8::internal::compiler::JSCreateLowering::ReduceJSCreate(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateAsyncFunctionObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateBlockContext(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateClosure(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateEmptyLiteralObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateFunctionContext(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateGeneratorObject(), v8::internal::compiler::JSTypedLowering::ReduceJSEqual(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSGetIterator(), v8::internal::compiler::JSCreateLowering::ReduceNewArray(), v8::internal::compiler::JSCallReducer::ReduceObjectCreate(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeCatch(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeThen(), v8::internal::compiler::JSCallReducer::ReduceReflectApply(), v8::internal::compiler::JSCallReducer::ReduceReflectConstruct(), v8::internal::compiler::JSCallReducer::ReduceReflectHas(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeSubstr(), v8::internal::compiler::JSCallReducer::ReduceTypedArrayPrototypeToStringTag(), v8::internal::RegExpBuiltinsAssembler::RegExpPrototypeSplitBody(), v8::internal::CodeStubAssembler::RelationalComparison(), v8::internal::MicrotaskQueueBuiltinsAssembler::RunSingleMicrotask(), v8::internal::KeyedStoreGenericAssembler::StoreIC_NoFeedback(), v8::internal::KeyedStoreGenericAssembler::StoreProperty(), v8::internal::TF_BUILTIN(), and v8::internal::ArrayBuiltinsAssembler::VisitAllTypedArrayElements().