v8::internal::torque::anonymous_namespace{kythe-data.cc} Namespace Reference
Functions
KythePosition MakeKythePosition (const SourcePosition &pos)
Function Documentation
MakeKythePosition()
KythePosition v8::internal::torque::anonymous_namespace{kythe-data.cc}::MakeKythePosition (const SourcePosition & pos)
Definition at line 13 of file kythe-data.cc.
                                                           {
  KythePosition p;
  if (pos.source.IsValid()) {
    p.file_path = SourceFileMap::PathFromV8Root(pos.source);
  } else {
    p.file_path = "UNKNOWN";
  }
  p.start_offset = pos.start.offset;
  p.end_offset = pos.end.offset;
  return p;
}
References v8::internal::torque::SourcePosition::end, v8::internal::torque::KythePosition::end_offset, v8::internal::torque::KythePosition::file_path, v8::internal::torque::SourceId::IsValid(), v8::internal::torque::LineAndColumn::offset, v8::internal::torque::SourceFileMap::PathFromV8Root(), v8::internal::torque::SourcePosition::source, v8::internal::torque::SourcePosition::start, and v8::internal::torque::KythePosition::start_offset.
Referenced by v8::internal::torque::KytheData::AddBindingDefinitionImpl(), v8::internal::torque::KytheData::AddBindingUse(), v8::internal::torque::KytheData::AddCall(), v8::internal::torque::KytheData::AddClassFieldDefinition(), v8::internal::torque::KytheData::AddClassFieldUse(), v8::internal::torque::KytheData::AddConstantDefinition(), v8::internal::torque::KytheData::AddConstantUse(), v8::internal::torque::KytheData::AddFunctionDefinition(), v8::internal::torque::KytheData::AddTypeDefinition(), and v8::internal::torque::KytheData::AddTypeUse().