v8::internal::anonymous_namespace{intl-objects.cc} Namespace Reference
Namespaces
 anonymous_namespace{intl-objects.cc}
Classes
struct FastCompareStringsData
struct ParsedLocale
class Iterator
struct CheckCalendar
Enumerations
enum class Direction { kPast
, kFuture
 }
Functions
constexpr uint8_t AsOneByte (uint16_t ch)
constexpr uint8_t ToLatin1Lower (uint8_t ch)
constexpr uint8_t ToLatin1Lower (uint16_t ch)=delete
constexpr uint8_t ToLatin1Upper (uint8_t ch)
constexpr uint8_t ToLatin1Upper (uint16_t ch)=delete
bool ToUpperFastASCII (base::Vector< const uint16_t > src, DirectHandle< SeqOneByteString > result)
template<typename Char >
bool ToUpperOneByte (base::Vector< const Char > src, uint8_t *dest, int *sharp_s_count)
template<typename Char >
void ToUpperWithSharpS (base::Vector< const Char > src, DirectHandle< SeqOneByteString > result)
int FindFirstUpperOrNonAscii (Tagged< String > s, int length)
const UChar * GetUCharBufferFromFlat (const String::FlatContent &flat, std::unique_ptr< base::uc16[]> *dest, int32_t length)
template<typename T >
MaybeDirectHandle< T > New (Isolate *isolate, DirectHandle< JSFunction > constructor, DirectHandle< Object > locales, DirectHandle< Object > options, const char *method_name)
icu::StringPiece ToICUStringPiece (Isolate *isolate, DirectHandle< String > string, int offset=0)
MaybeHandle< String > LocaleConvertCase (Isolate *isolate, DirectHandle< String > s, bool is_to_upper, const char *lang)
Maybe< icu::Locale > CreateICULocale (const std::string &bcp47_locale)
Handle< JSObject > InnerAddElement (Isolate *isolate, DirectHandle< JSArray > array, int index, DirectHandle< String > field_type_string, DirectHandle< String > value)
bool RemoveLocaleScriptTag (const std::string &icu_locale, std::string *locale_less_script)
bool ValidateResource (const icu::Locale locale, const char *path, const char *key)
bool IsTwoLetterLanguage (std::string_view locale)
bool IsDeprecatedOrLegacyLanguage (std::string_view locale)
bool IsStructurallyValidLanguageTag (std::string_view tag)
Maybe< std::string > CanonicalizeLanguageTag (Isolate *isolate, DirectHandle< Object > locale_in)
constexpr UCollationResult ToUCollationResult (int delta)
template<class CharT >
constexpr bool CanFastCompare (CharT c)
template<class Char1T , class Char2T >
bool FastCompareFlatString (const Char1T *lhs, const Char2T *rhs, int length, FastCompareStringsData *d)
bool FastCompareStringFlatContent (const String::FlatContent &lhs, const String::FlatContent &rhs, int length, FastCompareStringsData *d)
bool CharIsAsciiOrOutOfBounds (const String::FlatContent &string, int string_length, int index)
bool CharCanFastCompareOrOutOfBounds (const String::FlatContent &string, int string_length, int index)
std::optional< UCollationResult > TryFastCompareStrings (Isolate *isolate, const icu::Collator &icu_collator, DirectHandle< String > string1, DirectHandle< String > string2, int *processed_until_out)
bool IsValidRoundingIncrement (int value)
std::string BestAvailableLocale (const std::set< std::string > &available_locales, const std::string &locale)
ParsedLocale ParseBCP47Locale (const std::string &locale)
std::vector< std::string > LookupSupportedLocales (const std::set< std::string > &available_locales, const std::vector< std::string > &requested_locales)
icu::LocaleMatcher BuildLocaleMatcher (Isolate *isolate, const std::set< std::string > &available_locales, UErrorCode *status)
std::string BestFitMatcher (Isolate *isolate, const std::set< std::string > &available_locales, const std::vector< std::string > &requested_locales)
std::vector< std::string > BestFitSupportedLocales (Isolate *isolate, const std::set< std::string > &available_locales, const std::vector< std::string > &requested_locales)
MaybeDirectHandle< JSArray > CreateArrayFromList (Isolate *isolate, std::vector< std::string > elements, PropertyAttributes attr)
MaybeDirectHandle< JSObject > SupportedLocales (Isolate *isolate, const char *method_name, const std::set< std::string > &available_locales, const std::vector< std::string > &requested_locales, DirectHandle< Object > options)
MaybeDirectHandle< JSArray > AvailableCollations (Isolate *isolate)
MaybeDirectHandle< JSArray > VectorToJSArray (Isolate *isolate, const std::vector< std::string > &array)
MaybeDirectHandle< JSArray > AvailableCurrencies (Isolate *isolate)
MaybeDirectHandle< JSArray > AvailableNumberingSystems (Isolate *isolate)
MaybeDirectHandle< JSArray > AvailableTimeZones (Isolate *isolate)
MaybeDirectHandle< JSArray > AvailableUnits (Isolate *isolate)
template<typename T >
bool IsValidExtension (const icu::Locale &locale, const char *key, const std::string &value)
bool IsWellFormedNumberingSystem (const std::string &value)
std::map< std::string, std::string > LookupAndValidateUnicodeExtensions (icu::Locale *icu_locale, const std::set< std::string > &relevant_keys)
std::string LookupMatcher (Isolate *isolate, const std::set< std::string > &available_locales, const std::vector< std::string > &requested_locales)
bool IsUnicodeStringValidTimeZoneName (const icu::UnicodeString &id)
const icu::BasicTimeZone * CreateBasicTimeZoneFromIndex (int32_t time_zone_index)
int64_t ApproximateMillisecondEpoch (Isolate *isolate, DirectHandle< BigInt > nanosecond_epoch, Direction direction=Direction::kPast)
DirectHandle< BigInt > MillisecondToNanosecond (Isolate *isolate, int64_t ms)
Variables
constexpr uint8_t kToLower [256]
const uint16_t sharp_s = 0xDF
constexpr uint8_t kCollationWeightsL1 [256]
constexpr uint8_t kCollationWeightsL3 [256]
constexpr int kCollationWeightsLength = arraysize(kCollationWeightsL1)
Enumeration Type Documentation
Direction
enum v8::internal::anonymous_namespace{intl-objects.cc}::Direction [strong]
Enumerator
kPast
kFuture
Definition at line 3086 of file intl-objects.cc.
{ kPast, kFuture };
Function Documentation
ApproximateMillisecondEpoch()
int64_t v8::internal::anonymous_namespace{intl-objects.cc}::ApproximateMillisecondEpoch (Isolate * isolate, DirectHandle< BigInt > nanosecond_epoch, Direction direction = Direction::kPast)
Definition at line 3087 of file intl-objects.cc.
                                                                          {
  DirectHandle<BigInt> one_million = BigInt::FromUint64(isolate, 1000000);
  int64_t ms = BigInt::Divide(isolate, nanosecond_epoch, one_million)
                   .ToHandleChecked()
                   ->AsInt64();
  DirectHandle<BigInt> remainder =
      BigInt::Remainder(isolate, nanosecond_epoch, one_million)
          .ToHandleChecked();
  // If the nanosecond_epoch is not on the exact millisecond
  if (remainder->ToBoolean()) {
    if (direction == Direction::kPast) {
      if (remainder->IsNegative()) {
        // If the remaninder is negative, we know we have an negative epoch
        // We need to decrease one millisecond.
        // Move to the previous millisecond
        ms -= 1;
      }
    } else {
      if (!remainder->IsNegative()) {
        // Move to the future millisecond
        ms += 1;
      }
    }
  }
  return ms;
}
References v8::internal::BigInt::Divide(), v8::internal::BigInt::FromUint64(), and v8::internal::BigInt::Remainder().
Referenced by v8::internal::Intl::GetTimeZoneOffsetNanoseconds(), v8::internal::Intl::GetTimeZoneOffsetTransitionNanoseconds(), and v8::internal::Intl::GetTimeZonePossibleOffsetNanoseconds().
AsOneByte()
constexpr uint8_t v8::internal::anonymous_namespace{intl-objects.cc}::AsOneByte (uint16_t ch) [inline], [constexpr]
Definition at line 76 of file intl-objects.cc.
                                                {
  DCHECK_LE(ch, kMaxUInt8);
  return static_cast<uint8_t>(ch);
}
References DCHECK_LE, and v8::internal::kMaxUInt8.
Referenced by v8::internal::Intl::ConvertOneByteToLower(), ToUpperOneByte(), and ToUpperWithSharpS().
AvailableCollations()
MaybeDirectHandle<JSArray> v8::internal::anonymous_namespace{intl-objects.cc}::AvailableCollations (Isolate * isolate)
Definition at line 2176 of file intl-objects.cc.
                                                                 {
  UErrorCode status = U_ZERO_ERROR;
  std::unique_ptr<icu::StringEnumeration> enumeration(
      icu::Collator::getKeywordValues("collation", status));
  if (U_FAILURE(status)) {
    THROW_NEW_ERROR(isolate, NewRangeError(MessageTemplate::kIcuError));
  }
  return Intl::ToJSArray(isolate, "co", enumeration.get(),
                         Intl::RemoveCollation, true);
}
References v8::internal::Intl::RemoveCollation(), v8::internal::status, THROW_NEW_ERROR, and v8::internal::Intl::ToJSArray().
Referenced by v8::internal::Intl::SupportedValuesOf().
AvailableCurrencies()
MaybeDirectHandle<JSArray> v8::internal::anonymous_namespace{intl-objects.cc}::AvailableCurrencies (Isolate * isolate)
Definition at line 2253 of file intl-objects.cc.
                                                                 {
  return VectorToJSArray(isolate, GetAvailableCurrencies());
}
References v8::internal::anonymous_namespace{intl-objects.cc}::anonymous_namespace{intl-objects.cc}::GetAvailableCurrencies(), and VectorToJSArray().
Referenced by v8::internal::Intl::SupportedValuesOf().
AvailableNumberingSystems()
MaybeDirectHandle<JSArray> v8::internal::anonymous_namespace{intl-objects.cc}::AvailableNumberingSystems (Isolate * isolate)
Definition at line 2257 of file intl-objects.cc.
                                                                       {
  UErrorCode status = U_ZERO_ERROR;
  std::unique_ptr<icu::StringEnumeration> enumeration(
      icu::NumberingSystem::getAvailableNames(status));
  if (U_FAILURE(status)) {
    THROW_NEW_ERROR(isolate, NewRangeError(MessageTemplate::kIcuError));
  }
  // Need to filter out isAlgorithmic
  return Intl::ToJSArray(
      isolate, "nu", enumeration.get(),
      [](const char* value) {
        UErrorCode status = U_ZERO_ERROR;
        std::unique_ptr<icu::NumberingSystem> numbering_system(
            icu::NumberingSystem::createInstanceByName(value, status));
        // Skip algorithmic one since chrome filter out the resource.
        return U_FAILURE(status) || numbering_system->isAlgorithmic();
      },
      true);
}
References v8::internal::status, THROW_NEW_ERROR, v8::internal::Intl::ToJSArray(), and v8::internal::value.
Referenced by v8::internal::Intl::SupportedValuesOf().
AvailableTimeZones()
MaybeDirectHandle<JSArray> v8::internal::anonymous_namespace{intl-objects.cc}::AvailableTimeZones (Isolate * isolate)
Definition at line 2277 of file intl-objects.cc.
                                                                {
  UErrorCode status = U_ZERO_ERROR;
  std::unique_ptr<icu::StringEnumeration> enumeration(
      icu::TimeZone::createTimeZoneIDEnumeration(
          UCAL_ZONE_TYPE_CANONICAL_LOCATION, nullptr, nullptr, status));
  if (U_FAILURE(status)) {
    THROW_NEW_ERROR(isolate, NewRangeError(MessageTemplate::kIcuError));
  }
  return Intl::ToJSArray(isolate, nullptr, enumeration.get(), nullptr, true);
}
References v8::internal::status, THROW_NEW_ERROR, and v8::internal::Intl::ToJSArray().
Referenced by v8::internal::Intl::SupportedValuesOf().
AvailableUnits()
MaybeDirectHandle<JSArray> v8::internal::anonymous_namespace{intl-objects.cc}::AvailableUnits (Isolate * isolate)
Definition at line 2288 of file intl-objects.cc.
                                                            {
  Factory* factory = isolate->factory();
  std::set<std::string> sanctioned(Intl::SanctionedSimpleUnits());
  DirectHandle<FixedArray> fixed_array =
      factory->NewFixedArray(static_cast<int32_t>(sanctioned.size()));
  int32_t index = 0;
  for (const std::string& item : sanctioned) {
    DirectHandle<String> str = factory->NewStringFromAsciiChecked(item.c_str());
    fixed_array->set(index++, *str);
  }
  return factory->NewJSArrayWithElements(fixed_array);
}
References v8::internal::Isolate::factory(), v8::internal::index, v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::Factory::NewJSArrayWithElements(), v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), v8::internal::Intl::SanctionedSimpleUnits(), and v8::internal::string.
Referenced by v8::internal::Intl::SupportedValuesOf().
BestAvailableLocale()
std::string v8::internal::anonymous_namespace{intl-objects.cc}::BestAvailableLocale (const std::set< std::string > & available_locales, const std::string & locale)
Definition at line 1860 of file intl-objects.cc.
                                                         {
  // 1. Let candidate be locale.
  std::string candidate = locale;
  // 2. Repeat,
  while (true) {
    // 2.a. If availableLocales contains an element equal to candidate, return
    // candidate.
    if (available_locales.find(candidate) != available_locales.end()) {
      return candidate;
    }
    // 2.b. Let pos be the character index of the last occurrence of "-"
    // (U+002D) within candidate. If that character does not occur, return
    // undefined.
    size_t pos = candidate.rfind('-');
    if (pos == std::string::npos) {
      return std::string();
    }
    // 2.c. If pos 2 and the character "-" occurs at index pos-2 of candidate,
    // decrease pos by 2.
    if (pos >= 2 && candidate[pos - 2] == '-') {
      pos -= 2;
    }
    // 2.d. Let candidate be the substring of candidate from position 0,
    // inclusive, to position pos, exclusive.
    candidate = candidate.substr(0, pos);
  }
}
References v8::internal::string.
Referenced by LookupMatcher(), and LookupSupportedLocales().
BestFitMatcher()
std::string v8::internal::anonymous_namespace{intl-objects.cc}::BestFitMatcher (Isolate * isolate, const std::set< std::string > & available_locales, const std::vector< std::string > & requested_locales)
Definition at line 2049 of file intl-objects.cc.
                                                                          {
  UErrorCode status = U_ZERO_ERROR;
  Iterator iter(requested_locales.cbegin(), requested_locales.cend());
  std::string bestfit = BuildLocaleMatcher(isolate, available_locales, &status)
                            .getBestMatchResult(iter, status)
                            .makeResolvedLocale(status)
                            .toLanguageTag<std::string>(status);
  DCHECK(U_SUCCESS(status));
  return bestfit;
}
References BuildLocaleMatcher(), v8::internal::DCHECK(), v8::internal::status, and v8::internal::string.
Referenced by v8::internal::Intl::ResolveLocale().
BestFitSupportedLocales()
std::vector<std::string> v8::internal::anonymous_namespace{intl-objects.cc}::BestFitSupportedLocales (Isolate * isolate, const std::set< std::string > & available_locales, const std::vector< std::string > & requested_locales)
Definition at line 2064 of file intl-objects.cc.
                                                   {
  UErrorCode status = U_ZERO_ERROR;
  icu::LocaleMatcher matcher =
      BuildLocaleMatcher(isolate, available_locales, &status);
  std::vector<std::string> result;
  if (U_SUCCESS(status)) {
    for (auto it = requested_locales.cbegin(); it != requested_locales.cend();
         it++) {
      status = U_ZERO_ERROR;
      icu::Locale desired = icu::Locale::forLanguageTag(it->c_str(), status);
      icu::LocaleMatcher::Result matched =
          matcher.getBestMatchResult(desired, status);
      if (U_FAILURE(status)) continue;
      if (matched.getSupportedIndex() < 0) continue;
      // The BestFitSupportedLocales abstract operation returns the *SUBSET* of
      // the provided BCP 47 language priority list requestedLocales for which
      // availableLocales has a matching locale when using the Best Fit Matcher
      // algorithm. Locales appear in the same order in the returned list as in
      // requestedLocales. The steps taken are implementation dependent.
      std::string bestfit = desired.toLanguageTag<std::string>(status);
      if (U_FAILURE(status)) continue;
      result.push_back(bestfit);
    }
  }
  return result;
}
References BuildLocaleMatcher(), v8::base::internal::result, v8::internal::status, and v8::internal::string.
Referenced by SupportedLocales().
BuildLocaleMatcher()
icu::LocaleMatcher v8::internal::anonymous_namespace{intl-objects.cc}::BuildLocaleMatcher (Isolate * isolate, const std::set< std::string > & available_locales, UErrorCode * status)
Definition at line 1988 of file intl-objects.cc.
                        {
  icu::Locale default_locale =
      icu::Locale::forLanguageTag(isolate->DefaultLocale(), *status);
  icu::LocaleMatcher::Builder builder;
  if (U_FAILURE(*status)) {
    return builder.build(*status);
  }
  builder.setDefaultLocale(&default_locale);
  for (auto it = available_locales.begin(); it != available_locales.end();
       ++it) {
    *status = U_ZERO_ERROR;
    icu::Locale l = icu::Locale::forLanguageTag(it->c_str(), *status);
    // skip invalid locale such as no-NO-NY
    if (U_SUCCESS(*status)) {
      builder.addSupportedLocale(l);
    }
  }
  return builder.build(*status);
}
References v8::internal::compiler::turboshaft::l, and v8::internal::status.
Referenced by BestFitMatcher(), and BestFitSupportedLocales().
CanFastCompare()
template<class CharT >
constexpr bool v8::internal::anonymous_namespace{intl-objects.cc}::CanFastCompare (CharT c) [constexpr]
Definition at line 1146 of file intl-objects.cc.
                                       {
  return c < kCollationWeightsLength && kCollationWeightsL1[c] != 0;
}
References kCollationWeightsL1, and kCollationWeightsLength.
Referenced by CharCanFastCompareOrOutOfBounds(), and FastCompareFlatString().
CanonicalizeLanguageTag()
Maybe<std::string> v8::internal::anonymous_namespace{intl-objects.cc}::CanonicalizeLanguageTag (Isolate * isolate, DirectHandle< Object > locale_in)
Definition at line 707 of file intl-objects.cc.
                                                                           {
  DirectHandle<String> locale_str;
  // This does part of the validity checking spec'ed in CanonicalizeLocaleList:
  // 7c ii. If Type(kValue) is not String or Object, throw a TypeError
  // exception.
  // 7c iii. Let tag be ? ToString(kValue).
  // 7c iv. If IsStructurallyValidLanguageTag(tag) is false, throw a
  // RangeError exception.
  if (IsString(*locale_in)) {
    locale_str = Cast<String>(locale_in);
  } else if (IsJSReceiver(*locale_in)) {
    ASSIGN_RETURN_ON_EXCEPTION_VALUE(isolate, locale_str,
                                     Object::ToString(isolate, locale_in),
                                     Nothing<std::string>());
  } else {
    THROW_NEW_ERROR_RETURN_VALUE(isolate,
                                 NewTypeError(MessageTemplate::kLanguageID),
                                 Nothing<std::string>());
  }
  std::string locale = locale_str->ToStdString();
  return Intl::ValidateAndCanonicalizeUnicodeLocaleId(isolate, locale);
}
References ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::string, THROW_NEW_ERROR_RETURN_VALUE, v8::Value::ToString(), and v8::internal::Intl::ValidateAndCanonicalizeUnicodeLocaleId().
Referenced by v8::internal::Intl::CanonicalizeLocaleList().
CharCanFastCompareOrOutOfBounds()
bool v8::internal::anonymous_namespace{intl-objects.cc}::CharCanFastCompareOrOutOfBounds (const String::FlatContent & string, int string_length, int index)
Definition at line 1217 of file intl-objects.cc.
                                                                   {
  DCHECK_EQ(string.length(), string_length);
  return index >= string_length || CanFastCompare(string.Get(index));
}
References CanFastCompare(), DCHECK_EQ, v8::internal::compiler::turboshaft::Get(), v8::internal::index, and v8::internal::length.
Referenced by TryFastCompareStrings().
CharIsAsciiOrOutOfBounds()
bool v8::internal::anonymous_namespace{intl-objects.cc}::CharIsAsciiOrOutOfBounds (const String::FlatContent & string, int string_length, int index)
Definition at line 1211 of file intl-objects.cc.
                                                            {
  DCHECK_EQ(string.length(), string_length);
  return index >= string_length || isascii(string.Get(index));
}
References DCHECK_EQ, v8::internal::compiler::turboshaft::Get(), v8::internal::index, and v8::internal::length.
Referenced by TryFastCompareStrings().
CreateArrayFromList()
MaybeDirectHandle<JSArray> v8::internal::anonymous_namespace{intl-objects.cc}::CreateArrayFromList (Isolate * isolate, std::vector< std::string > elements, PropertyAttributes attr)
Definition at line 2095 of file intl-objects.cc.
                             {
  Factory* factory = isolate->factory();
  // Let array be ! ArrayCreate(0).
  DirectHandle<JSArray> array = factory->NewJSArray(0);
  uint32_t length = static_cast<uint32_t>(elements.size());
  // 3. Let n be 0.
  // 4. For each element e of elements, do
  for (uint32_t i = 0; i < length; i++) {
    // a. Let status be CreateDataProperty(array, ! ToString(n), e).
    const std::string& part = elements[i];
    DirectHandle<String> value =
        factory->NewStringFromUtf8(base::CStrVector(part.c_str()))
            .ToHandleChecked();
    MAYBE_RETURN(JSObject::AddDataElement(isolate, array, i, value, attr), {});
  }
  // 5. Return array.
  return array;
}
References v8::internal::JSObject::AddDataElement(), v8::base::CStrVector(), v8::internal::Isolate::factory(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::length, MAYBE_RETURN, v8::internal::Factory::NewJSArray(), v8::internal::Factory::NewStringFromUtf8(), v8::internal::string, and v8::internal::value.
Referenced by v8::internal::Intl::GetCanonicalLocales(), and SupportedLocales().
CreateBasicTimeZoneFromIndex()
const icu::BasicTimeZone* v8::internal::anonymous_namespace{intl-objects.cc}::CreateBasicTimeZoneFromIndex (int32_t time_zone_index)
Definition at line 3072 of file intl-objects.cc.
                             {
  DCHECK_NE(time_zone_index, 0);
  return static_cast<const icu::BasicTimeZone*>(
      icu::TimeZone::createTimeZone(icu::UnicodeString(
          Intl::TimeZoneIdFromIndex(time_zone_index).c_str(), -1, US_INV)));
}
References DCHECK_NE, and v8::internal::Intl::TimeZoneIdFromIndex().
Referenced by v8::internal::Intl::GetTimeZoneOffsetNanoseconds(), v8::internal::Intl::GetTimeZoneOffsetTransitionNanoseconds(), and v8::internal::Intl::GetTimeZonePossibleOffsetNanoseconds().
CreateICULocale()
Maybe<icu::Locale> v8::internal::anonymous_namespace{intl-objects.cc}::CreateICULocale (const std::string & bcp47_locale)
Definition at line 487 of file intl-objects.cc.
                                                                {
  DisallowGarbageCollection no_gc;
  // Convert BCP47 into ICU locale format.
  UErrorCode status = U_ZERO_ERROR;
  icu::Locale icu_locale = icu::Locale::forLanguageTag(bcp47_locale, status);
  if (U_FAILURE(status) || icu_locale.isBogus()) {
    return Nothing<icu::Locale>();
  }
  return Just(icu_locale);
}
References v8::Just(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::status.
Referenced by v8::internal::Intl::ResolveLocale().
FastCompareFlatString()
template<class Char1T , class Char2T >
bool v8::internal::anonymous_namespace{intl-objects.cc}::FastCompareFlatString (const Char1T * lhs, const Char2T * rhs, int length, FastCompareStringsData * d)
Definition at line 1151 of file intl-objects.cc.
                                                      {
  for (int i = 0; i < length; i++) {
    const Char1T l = lhs[i];
    const Char2T r = rhs[i];
    if (!CanFastCompare(l) || !CanFastCompare(r)) {
      d->processed_until = i;
      return false;
    }
    UCollationResult l1_result =
        ToUCollationResult(kCollationWeightsL1[l] - kCollationWeightsL1[r]);
    if (l1_result != UCollationResult::UCOL_EQUAL) {
      d->has_diff = true;
      d->first_diff_at = i;
      d->processed_until = i;
      d->l1_result = l1_result;
      return true;
    }
    if (l != r && d->l3_result == UCollationResult::UCOL_EQUAL) {
      // Collapse the two-pass algorithm into one: if we find a difference in
      // L1 weights, that is our result. If not, use the first L3 weight
      // difference.
      UCollationResult l3_result =
          ToUCollationResult(kCollationWeightsL3[l] - kCollationWeightsL3[r]);
      d->l3_result = l3_result;
      if (!d->has_diff) {
        d->has_diff = true;
        d->first_diff_at = i;
      }
    }
  }
  d->processed_until = length;
  return true;
}
References CanFastCompare(), v8::internal::anonymous_namespace{intl-objects.cc}::FastCompareStringsData::first_diff_at, v8::internal::anonymous_namespace{intl-objects.cc}::FastCompareStringsData::has_diff, v8::internal::anonymous_namespace{json-stringifier.cc}::i, kCollationWeightsL1, kCollationWeightsL3, v8::internal::compiler::turboshaft::l, v8::internal::anonymous_namespace{intl-objects.cc}::FastCompareStringsData::l1_result, v8::internal::anonymous_namespace{intl-objects.cc}::FastCompareStringsData::l3_result, v8::internal::length, v8::internal::anonymous_namespace{intl-objects.cc}::FastCompareStringsData::processed_until, and ToUCollationResult().
Referenced by FastCompareStringFlatContent().
FastCompareStringFlatContent()
bool v8::internal::anonymous_namespace{intl-objects.cc}::FastCompareStringFlatContent (const String::FlatContent & lhs, const String::FlatContent & rhs, int length, FastCompareStringsData * d)
Definition at line 1186 of file intl-objects.cc.
                                                             {
  if (lhs.IsOneByte()) {
    base::Vector<const uint8_t> l = lhs.ToOneByteVector();
    if (rhs.IsOneByte()) {
      base::Vector<const uint8_t> r = rhs.ToOneByteVector();
      return FastCompareFlatString(l.data(), r.data(), length, d);
    } else {
      base::Vector<const uint16_t> r = rhs.ToUC16Vector();
      return FastCompareFlatString(l.data(), r.data(), length, d);
    }
  } else {
    base::Vector<const uint16_t> l = lhs.ToUC16Vector();
    if (rhs.IsOneByte()) {
      base::Vector<const uint8_t> r = rhs.ToOneByteVector();
      return FastCompareFlatString(l.data(), r.data(), length, d);
    } else {
      base::Vector<const uint16_t> r = rhs.ToUC16Vector();
      return FastCompareFlatString(l.data(), r.data(), length, d);
    }
  }
  UNREACHABLE();
}
References v8::base::Vector< T >::data(), FastCompareFlatString(), v8::internal::String::FlatContent::IsOneByte(), v8::internal::compiler::turboshaft::l, v8::internal::length, v8::internal::String::FlatContent::ToOneByteVector(), v8::internal::String::FlatContent::ToUC16Vector(), and v8::internal::UNREACHABLE().
Referenced by TryFastCompareStrings().
FindFirstUpperOrNonAscii()
int v8::internal::anonymous_namespace{intl-objects.cc}::FindFirstUpperOrNonAscii (Tagged< String > s, int length) [inline]
Definition at line 179 of file intl-objects.cc.
                                                                  {
  for (int index = 0; index < length; ++index) {
    uint16_t ch = s->Get(index);
    if (V8_UNLIKELY(IsAsciiUpper(ch) || ch & ~0x7F)) {
      return index;
    }
  }
  return length;
}
References v8::internal::index, v8::internal::IsAsciiUpper(), v8::internal::length, and V8_UNLIKELY.
Referenced by v8::internal::Intl::ConvertOneByteToLower(), and v8::internal::Intl::ConvertToLower().
GetUCharBufferFromFlat()
const UChar* v8::internal::anonymous_namespace{intl-objects.cc}::GetUCharBufferFromFlat (const String::FlatContent & flat, std::unique_ptr< base::uc16[]> * dest, int32_t length)
Definition at line 189 of file intl-objects.cc.
                                                    {
  DCHECK(flat.IsFlat());
  if (flat.IsOneByte()) {
    if (!*dest) {
      dest->reset(NewArray<base::uc16>(length));
      CopyChars(dest->get(), flat.ToOneByteVector().begin(), length);
    }
    return reinterpret_cast<const UChar*>(dest->get());
  } else {
    return reinterpret_cast<const UChar*>(flat.ToUC16Vector().begin());
  }
}
References v8::base::Vector< T >::begin(), v8::internal::CopyChars(), v8::internal::DCHECK(), v8::internal::String::FlatContent::IsFlat(), v8::internal::String::FlatContent::IsOneByte(), v8::internal::length, v8::internal::String::FlatContent::ToOneByteVector(), and v8::internal::String::FlatContent::ToUC16Vector().
Referenced by LocaleConvertCase(), and v8::internal::Intl::ToICUUnicodeString().
InnerAddElement()
Handle<JSObject> v8::internal::anonymous_namespace{intl-objects.cc}::InnerAddElement (Isolate * isolate, DirectHandle< JSArray > array, int index, DirectHandle< String > field_type_string, DirectHandle< String > value)
Definition at line 519 of file intl-objects.cc.
                                                             {
  // let element = $array[$index] = {
  // type: $field_type_string,
  // value: $value
  // }
  // return element;
  Factory* factory = isolate->factory();
  Handle<JSObject> element = factory->NewJSObject(isolate->object_function());
  JSObject::AddProperty(isolate, element, factory->type_string(),
                        field_type_string, NONE);
  JSObject::AddProperty(isolate, element, factory->value_string(), value, NONE);
  // TODO(victorgomes): Temporarily forcing a fatal error here in case of
  // overflow, until Intl::AddElement can handle exceptions.
  if (JSObject::AddDataElement(isolate, array, index, element, NONE)
          .IsNothing()) {
    FATAL("Fatal JavaScript invalid size error when adding element");
    UNREACHABLE();
  }
  return element;
}
References v8::internal::JSObject::AddDataElement(), v8::internal::JSObject::AddProperty(), v8::internal::Isolate::factory(), FATAL, v8::internal::index, v8::internal::Factory::NewJSObject(), v8::internal::NONE, v8::internal::UNREACHABLE(), and v8::internal::value.
Referenced by v8::internal::Intl::AddElement().
IsDeprecatedOrLegacyLanguage()
bool v8::internal::anonymous_namespace{intl-objects.cc}::IsDeprecatedOrLegacyLanguage (std::string_view locale)
Definition at line 695 of file intl-objects.cc.
                                                         {
  // Check if locale is one of the deprecated language tags:
  return locale == "in" || locale == "iw" || locale == "ji" || locale == "jw" ||
         locale == "mo" ||
         // Check if locale is one of the legacy language tags:
         locale == "sh" || locale == "tl" || locale == "no";
}
Referenced by v8::internal::Intl::ValidateAndCanonicalizeUnicodeLocaleId().
IsStructurallyValidLanguageTag()
bool v8::internal::anonymous_namespace{intl-objects.cc}::IsStructurallyValidLanguageTag (std::string_view tag)
Definition at line 703 of file intl-objects.cc.
                                                        {
  return JSLocale::StartsWithUnicodeLanguageId(tag);
}
References v8::internal::JSLocale::StartsWithUnicodeLanguageId().
Referenced by v8::internal::Intl::ValidateAndCanonicalizeUnicodeLocaleId().
IsTwoLetterLanguage()
bool v8::internal::anonymous_namespace{intl-objects.cc}::IsTwoLetterLanguage (std::string_view locale)
Definition at line 689 of file intl-objects.cc.
                                                {
  // Two letters, both in range 'a'-'z'...
  return locale.length() == 2 && IsAsciiLower(locale[0]) &&
         IsAsciiLower(locale[1]);
}
References v8::internal::IsAsciiLower().
Referenced by v8::internal::Intl::ValidateAndCanonicalizeUnicodeLocaleId().
IsUnicodeStringValidTimeZoneName()
bool v8::internal::anonymous_namespace{intl-objects.cc}::IsUnicodeStringValidTimeZoneName (const icu::UnicodeString & id)
Definition at line 2944 of file intl-objects.cc.
                                                                  {
  UErrorCode status = U_ZERO_ERROR;
  icu::UnicodeString canonical;
  icu::TimeZone::getCanonicalID(id, canonical, status);
  return U_SUCCESS(status) &&
         canonical != icu::UnicodeString("Etc/Unknown", -1, US_INV);
}
References v8::internal::status.
Referenced by v8::internal::Intl::IsValidTimeZoneName().
IsValidExtension()
template<typename T >
bool v8::internal::anonymous_namespace{intl-objects.cc}::IsValidExtension (const icu::Locale & locale, const char * key, const std::string & value)
Definition at line 2371 of file intl-objects.cc.
                                              {
  const char* legacy_type = uloc_toLegacyType(key, value.c_str());
  if (legacy_type == nullptr) {
    return false;
  }
  UErrorCode status = U_ZERO_ERROR;
  std::unique_ptr<icu::StringEnumeration> enumeration(
      T::getKeywordValuesForLocale(key, icu::Locale(locale.getBaseName()),
                                   false, status));
  if (U_FAILURE(status)) {
    return false;
  }
  int32_t length;
  for (const char* item = enumeration->next(&length, status);
       U_SUCCESS(status) && item != nullptr;
       item = enumeration->next(&length, status)) {
    if (strcmp(legacy_type, item) == 0) {
      return true;
    }
  }
  return false;
}
References v8::internal::key, v8::internal::length, v8::internal::status, and v8::internal::value.
IsValidRoundingIncrement()
bool v8::internal::anonymous_namespace{intl-objects.cc}::IsValidRoundingIncrement (int value)
Definition at line 1555 of file intl-objects.cc.
                                         {
  switch (value) {
    case 1:
    case 2:
    case 5:
    case 10:
    case 20:
    case 25:
    case 50:
    case 100:
    case 200:
    case 250:
    case 500:
    case 1000:
    case 2000:
    case 2500:
    case 5000:
      return true;
    default:
      return false;
  }
}
References v8::internal::value.
Referenced by v8::internal::Intl::SetNumberFormatDigitOptions().
IsWellFormedNumberingSystem()
bool v8::internal::anonymous_namespace{intl-objects.cc}::IsWellFormedNumberingSystem (const std::string & value)
Definition at line 2430 of file intl-objects.cc.
                                                         {
  return JSLocale::Is38AlphaNumList(value);
}
References v8::internal::JSLocale::Is38AlphaNumList(), and v8::internal::value.
Referenced by v8::internal::Intl::GetNumberingSystem().
LocaleConvertCase()
MaybeHandle<String> v8::internal::anonymous_namespace{intl-objects.cc}::LocaleConvertCase (Isolate * isolate, DirectHandle< String > s, bool is_to_upper, const char * lang)
Definition at line 271 of file intl-objects.cc.
                                                                          {
  auto case_converter = is_to_upper ? u_strToUpper : u_strToLower;
  uint32_t src_length = s->length();
  uint32_t dest_length = src_length;
  UErrorCode status;
  Handle<SeqTwoByteString> result;
  std::unique_ptr<base::uc16[]> sap;
  if (dest_length == 0) return isolate->factory()->empty_string();
  // This is not a real loop. It'll be executed only once (no overflow) or
  // twice (overflow).
  for (int i = 0; i < 2; ++i) {
    // Case conversion can increase the string length (e.g. sharp-S => SS) so
    // that we have to handle RangeError exceptions here.
    ASSIGN_RETURN_ON_EXCEPTION(
        isolate, result, isolate->factory()->NewRawTwoByteString(dest_length));
    DisallowGarbageCollection no_gc;
    DCHECK(s->IsFlat());
    String::FlatContent flat = s->GetFlatContent(no_gc);
    const UChar* src = GetUCharBufferFromFlat(flat, &sap, src_length);
    status = U_ZERO_ERROR;
    dest_length =
        case_converter(reinterpret_cast<UChar*>(result->GetChars(no_gc)),
                       dest_length, src, src_length, lang, &status);
    if (status != U_BUFFER_OVERFLOW_ERROR) break;
  }
  // In most cases, the output will fill the destination buffer completely
  // leading to an unterminated string (U_STRING_NOT_TERMINATED_WARNING).
  // Only in rare cases, it'll be shorter than the destination buffer and
  // |result| has to be truncated.
  DCHECK(U_SUCCESS(status));
  if (V8_LIKELY(status == U_STRING_NOT_TERMINATED_WARNING)) {
    DCHECK(dest_length == result->length());
    return result;
  }
  DCHECK(dest_length < result->length());
  return SeqString::Truncate(isolate, result, dest_length);
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::DCHECK(), v8::internal::Isolate::factory(), GetUCharBufferFromFlat(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::length, v8::internal::FactoryBase< Impl >::NewRawTwoByteString(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, v8::internal::status, v8::internal::SeqString::Truncate(), and V8_LIKELY.
Referenced by v8::internal::Intl::ConvertToLower(), v8::internal::Intl::ConvertToUpper(), and v8::internal::Intl::StringLocaleConvertCase().
LookupAndValidateUnicodeExtensions()
std::map<std::string, std::string> v8::internal::anonymous_namespace{intl-objects.cc}::LookupAndValidateUnicodeExtensions (icu::Locale * icu_locale, const std::set< std::string > & relevant_keys)
Definition at line 2434 of file intl-objects.cc.
                                                                   {
  std::map<std::string, std::string> extensions;
  UErrorCode status = U_ZERO_ERROR;
  icu::LocaleBuilder builder;
  builder.setLocale(*icu_locale).clearExtensions();
  std::unique_ptr<icu::StringEnumeration> keywords(
      icu_locale->createKeywords(status));
  if (U_FAILURE(status)) return extensions;
  if (!keywords) return extensions;
  char value[ULOC_FULLNAME_CAPACITY];
  int32_t length;
  status = U_ZERO_ERROR;
  for (const char* keyword = keywords->next(&length, status);
       keyword != nullptr; keyword = keywords->next(&length, status)) {
    // Ignore failures in ICU and skip to the next keyword.
    //
    // This is fine.
    if (U_FAILURE(status)) {
      status = U_ZERO_ERROR;
      continue;
    }
    icu_locale->getKeywordValue(keyword, value, ULOC_FULLNAME_CAPACITY, status);
    // Ignore failures in ICU and skip to the next keyword.
    //
    // This is fine.
    if (U_FAILURE(status)) {
      status = U_ZERO_ERROR;
      continue;
    }
    const char* bcp47_key = uloc_toUnicodeLocaleKey(keyword);
    if (bcp47_key && (relevant_keys.find(bcp47_key) != relevant_keys.end())) {
      const char* bcp47_value = uloc_toUnicodeLocaleType(bcp47_key, value);
      bool is_valid_value = false;
      // 8.h.ii.1.a If keyLocaleData contains requestedValue, then
      if (strcmp("ca", bcp47_key) == 0) {
        is_valid_value = Intl::IsValidCalendar(*icu_locale, bcp47_value);
      } else if (strcmp("co", bcp47_key) == 0) {
        is_valid_value = Intl::IsValidCollation(*icu_locale, bcp47_value);
      } else if (strcmp("hc", bcp47_key) == 0) {
        // https://www.unicode.org/repos/cldr/tags/latest/common/bcp47/calendar.xml
        std::set<std::string> valid_values = {"h11", "h12", "h23", "h24"};
        is_valid_value = valid_values.find(bcp47_value) != valid_values.end();
      } else if (strcmp("lb", bcp47_key) == 0) {
        // https://www.unicode.org/repos/cldr/tags/latest/common/bcp47/segmentation.xml
        std::set<std::string> valid_values = {"strict", "normal", "loose"};
        is_valid_value = valid_values.find(bcp47_value) != valid_values.end();
      } else if (strcmp("kn", bcp47_key) == 0) {
        // https://www.unicode.org/repos/cldr/tags/latest/common/bcp47/collation.xml
        std::set<std::string> valid_values = {"true", "false"};
        is_valid_value = valid_values.find(bcp47_value) != valid_values.end();
      } else if (strcmp("kf", bcp47_key) == 0) {
        // https://www.unicode.org/repos/cldr/tags/latest/common/bcp47/collation.xml
        std::set<std::string> valid_values = {"upper", "lower", "false"};
        is_valid_value = valid_values.find(bcp47_value) != valid_values.end();
      } else if (strcmp("nu", bcp47_key) == 0) {
        is_valid_value = Intl::IsValidNumberingSystem(bcp47_value);
      }
      if (is_valid_value) {
        extensions.insert(
            std::pair<std::string, std::string>(bcp47_key, bcp47_value));
        builder.setUnicodeLocaleKeyword(bcp47_key, bcp47_value);
      }
    }
  }
  status = U_ZERO_ERROR;
  *icu_locale = builder.build(status);
  return extensions;
}
References v8::internal::Intl::IsValidCalendar(), v8::internal::Intl::IsValidCollation(), v8::internal::Intl::IsValidNumberingSystem(), v8::internal::length, v8::internal::status, and v8::internal::value.
Referenced by v8::internal::Intl::ResolveLocale().
LookupMatcher()
std::string v8::internal::anonymous_namespace{intl-objects.cc}::LookupMatcher (Isolate * isolate, const std::set< std::string > & available_locales, const std::vector< std::string > & requested_locales)
Definition at line 2514 of file intl-objects.cc.
                                                                         {
  // 1. Let result be a new Record.
  std::string result;
  // 2. For each element locale of requestedLocales in List order, do
  for (const std::string& locale : requested_locales) {
    // 2. a. Let noExtensionsLocale be the String value that is locale
    // with all Unicode locale extension sequences removed.
    ParsedLocale parsed_locale = ParseBCP47Locale(locale);
    std::string no_extensions_locale = parsed_locale.no_extensions_locale;
    // 2. b. Let availableLocale be
    // BestAvailableLocale(availableLocales, noExtensionsLocale).
    std::string available_locale =
        BestAvailableLocale(available_locales, no_extensions_locale);
    // 2. c. If availableLocale is not undefined, append locale to the
    // end of subset.
    if (!available_locale.empty()) {
      // Note: The following steps are not performed here because we
      // can use ICU to parse the unicode locale extension sequence
      // as part of Intl::ResolveLocale.
      //
      // There's no need to separate the unicode locale extensions
      // right here. Instead just return the available locale with the
      // extensions.
      //
      // 2. c. i. Set result.[[locale]] to availableLocale.
      // 2. c. ii. If locale and noExtensionsLocale are not the same
      // String value, then
      // 2. c. ii. 1. Let extension be the String value consisting of
      // the first substring of locale that is a Unicode locale
      // extension sequence.
      // 2. c. ii. 2. Set result.[[extension]] to extension.
      // 2. c. iii. Return result.
      return available_locale + parsed_locale.extension;
    }
  }
  // 3. Let defLocale be DefaultLocale();
  // 4. Set result.[[locale]] to defLocale.
  // 5. Return result.
  return isolate->DefaultLocale();
}
References BestAvailableLocale(), v8::internal::anonymous_namespace{intl-objects.cc}::ParsedLocale::extension, v8::internal::anonymous_namespace{intl-objects.cc}::ParsedLocale::no_extensions_locale, ParseBCP47Locale(), v8::base::internal::result, and v8::internal::string.
Referenced by v8::internal::Intl::ResolveLocale().
LookupSupportedLocales()
std::vector<std::string> v8::internal::anonymous_namespace{intl-objects.cc}::LookupSupportedLocales (const std::set< std::string > & available_locales, const std::vector< std::string > & requested_locales)
Definition at line 1959 of file intl-objects.cc.
                                                   {
  // 1. Let subset be a new empty List.
  std::vector<std::string> subset;
  // 2. For each element locale of requestedLocales in List order, do
  for (const std::string& locale : requested_locales) {
    // 2. a. Let noExtensionsLocale be the String value that is locale
    // with all Unicode locale extension sequences removed.
    std::string no_extension_locale =
        ParseBCP47Locale(locale).no_extensions_locale;
    // 2. b. Let availableLocale be
    // BestAvailableLocale(availableLocales, noExtensionsLocale).
    std::string available_locale =
        BestAvailableLocale(available_locales, no_extension_locale);
    // 2. c. If availableLocale is not undefined, append locale to the
    // end of subset.
    if (!available_locale.empty()) {
      subset.push_back(locale);
    }
  }
  // 3. Return subset.
  return subset;
}
References BestAvailableLocale(), v8::internal::anonymous_namespace{intl-objects.cc}::ParsedLocale::no_extensions_locale, ParseBCP47Locale(), and v8::internal::string.
Referenced by SupportedLocales().
MillisecondToNanosecond()
DirectHandle<BigInt> v8::internal::anonymous_namespace{intl-objects.cc}::MillisecondToNanosecond (Isolate * isolate, int64_t ms)
Definition at line 3118 of file intl-objects.cc.
                                                                           {
  return BigInt::Multiply(isolate, BigInt::FromInt64(isolate, ms),
                          BigInt::FromUint64(isolate, 1000000))
      .ToHandleChecked();
}
References v8::internal::BigInt::FromInt64(), v8::internal::BigInt::FromUint64(), and v8::internal::BigInt::Multiply().
Referenced by v8::internal::Intl::GetTimeZoneOffsetTransitionNanoseconds(), and v8::internal::Intl::GetTimeZonePossibleOffsetNanoseconds().
New()
template<typename T >
MaybeDirectHandle<T> v8::internal::anonymous_namespace{intl-objects.cc}::New (Isolate * isolate, DirectHandle< JSFunction > constructor, DirectHandle< Object > locales, DirectHandle< Object > options, const char * method_name)
Definition at line 205 of file intl-objects.cc.
                                                  {
  DirectHandle<Map> map;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, map,
      JSFunction::GetDerivedMap(isolate, constructor, constructor));
  return T::New(isolate, map, locales, options, method_name);
}
References ASSIGN_RETURN_ON_EXCEPTION, and v8::internal::JSFunction::GetDerivedMap().
Referenced by v8::internal::compiler::turboshaft::Graph::Add(), v8::anonymous_namespace{api.cc}::AddPropertiesAndElementsToObject(), v8::internal::KeyAccumulator::AddShadowingKey(), v8::internal::BIT_FIELD_ACCESSORS(), v8::internal::JsonParser< Char >::BuildJsonObject(), v8::internal::anonymous_namespace{builtins-intl.cc}::CallOrConstructConstructor(), v8::internal::anonymous_namespace{compiler.cc}::CompileMaglev(), v8::internal::BasicBlockProfilerData::CopyToJSHeap(), v8::internal::ScopeInfo::Create(), v8::internal::JSSharedStruct::CreateInstanceMap(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::CreateNamedCaptureAtIndex(), v8::internal::Heap::CreateReadOnlyObjects(), v8::internal::ObjectDescriptor< IsolateT >::CreateTemplates(), v8::internal::anonymous_namespace{builtins-intl.cc}::DisallowCallConstructor(), v8::internal::CompilationCacheEvalOrScript::GetTable(), v8::internal::CompilationCacheRegExp::GetTable(), v8::internal::TemplateObjectDescription::GetTemplateObject(), v8::internal::JSWeakCollection::Initialize(), v8::internal::Genesis::InstallABunchOfRandomThings(), v8::internal::anonymous_namespace{builtins-intl.cc}::LegacyFormatConstructor(), v8::internal::Isolate::LocalsBlockListCacheSet(), v8::internal::ManualOptimizationTable::MarkFunctionForManualOptimization(), v8::internal::maglev::MaglevGraphBuilder::MergeIntoFrameState(), v8::internal::maglev::MaglevGraphBuilder::MergeIntoInlinedReturnFrameState(), v8::internal::IsolateGroup::New(), v8::internal::compiler::turboshaft::LoadOp::New(), v8::internal::compiler::turboshaft::StoreOp::New(), v8::internal::compiler::turboshaft::AtomicRMWOp::New(), v8::internal::compiler::turboshaft::TailCallOp::New(), v8::internal::compiler::turboshaft::OperationT< Derived >::New(), v8::internal::compiler::turboshaft::CallOp::New(), v8::internal::compiler::turboshaft::JSStackCheckOp::New(), v8::internal::compiler::turboshaft::FastApiCallOp::New(), v8::internal::compiler::turboshaft::CompareMapsOp::New(), v8::internal::compiler::turboshaft::CheckMapsOp::New(), v8::internal::compiler::turboshaft::ReturnOp::New(), v8::internal::compiler::turboshaft::AtomicWord32PairOp::New(), v8::internal::StringSet::New(), v8::internal::ScriptContextTable::New(), v8::internal::FixedAddressArrayBase< Base >::New(), v8::internal::FixedIntegerArrayBase< T, Base >::New(), v8::Local< T >::New(), v8::internal::NameDictionary::New(), v8::debug::EphemeronTable::New(), v8::internal::Factory::NewForTest(), v8::internal::Factory::NewJSGlobalObject(), v8::internal::Factory::NewSourceTextModule(), v8::internal::Factory::NewSyntheticModule(), v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::NormalizeImpl(), v8::internal::JsonParser< Char >::ParseJsonValue(), v8::internal::WasmJs::PrepareForSnapshot(), v8::internal::compiler::turboshaft::Graph::Replace(), v8::internal::requires(), v8::PersistentBase< T >::Reset(), v8::internal::Module::Reset(), v8::internal::anonymous_namespace{builtins-array.cc}::ArrayConcatVisitor::SetDictionaryMode(), v8::internal::anonymous_namespace{builtins-array.cc}::Slow_ArrayConcat(), v8::internal::anonymous_namespace{runtime-strings.cc}::StringAdd_StringConstant_Internalize(), v8::internal::ValueDeserializer::TransferArrayBuffer(), and v8::internal::wasm::WasmModuleCoverageData::WasmModuleCoverageData().
ParseBCP47Locale()
ParsedLocale v8::internal::anonymous_namespace{intl-objects.cc}::ParseBCP47Locale (const std::string & locale)
Definition at line 1903 of file intl-objects.cc.
                                                       {
  size_t length = locale.length();
  ParsedLocale parsed_locale;
  // Privateuse or grandfathered locales have no extension sequences.
  if ((length > 1) && (locale[1] == '-')) {
    // Check to make sure that this really is a grandfathered or
    // privateuse extension. ICU can sometimes mess up the
    // canonicalization.
    DCHECK(locale[0] == 'x' || locale[0] == 'i');
    parsed_locale.no_extensions_locale = locale;
    return parsed_locale;
  }
  size_t unicode_extension_start = locale.find("-u-");
  // No unicode extensions found.
  if (unicode_extension_start == std::string::npos) {
    parsed_locale.no_extensions_locale = locale;
    return parsed_locale;
  }
  size_t private_extension_start = locale.find("-x-");
  // Unicode extensions found within privateuse subtags don't count.
  if (private_extension_start != std::string::npos &&
      private_extension_start < unicode_extension_start) {
    parsed_locale.no_extensions_locale = locale;
    return parsed_locale;
  }
  const std::string beginning = locale.substr(0, unicode_extension_start);
  size_t unicode_extension_end = length;
  DCHECK_GT(length, 2);
  // Find the end of the extension production as per the bcp47 grammar
  // by looking for '-' followed by 2 chars and then another '-'.
  for (size_t i = unicode_extension_start + 1; i < length - 2; i++) {
    if (locale[i] != '-') continue;
    if (locale[i + 2] == '-') {
      unicode_extension_end = i;
      break;
    }
    i += 2;
  }
  const std::string end = locale.substr(unicode_extension_end);
  parsed_locale.no_extensions_locale = beginning + end;
  parsed_locale.extension = locale.substr(
      unicode_extension_start, unicode_extension_end - unicode_extension_start);
  return parsed_locale;
}
References v8::internal::DCHECK(), DCHECK_GT, v8::internal::compiler::end(), v8::internal::anonymous_namespace{intl-objects.cc}::ParsedLocale::extension, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::length, v8::internal::anonymous_namespace{intl-objects.cc}::ParsedLocale::no_extensions_locale, and v8::internal::string.
Referenced by LookupMatcher(), and LookupSupportedLocales().
RemoveLocaleScriptTag()
bool v8::internal::anonymous_namespace{intl-objects.cc}::RemoveLocaleScriptTag (const std::string & icu_locale, std::string * locale_less_script)
Definition at line 574 of file intl-objects.cc.
                                                          {
  icu::Locale new_locale = icu::Locale::createCanonical(icu_locale.c_str());
  const char* icu_script = new_locale.getScript();
  if (icu_script == nullptr || strlen(icu_script) == 0) {
    *locale_less_script = std::string();
    return false;
  }
  const char* icu_language = new_locale.getLanguage();
  const char* icu_country = new_locale.getCountry();
  icu::Locale short_locale = icu::Locale(icu_language, icu_country);
  *locale_less_script = short_locale.getName();
  return true;
}
References v8::internal::string.
Referenced by v8::internal::Intl::BuildLocaleSet().
SupportedLocales()
MaybeDirectHandle<JSObject> v8::internal::anonymous_namespace{intl-objects.cc}::SupportedLocales (Isolate * isolate, const char * method_name, const std::set< std::string > & available_locales, const std::vector< std::string > & requested_locales, DirectHandle< Object > options)
Definition at line 2119 of file intl-objects.cc.
                                  {
  std::vector<std::string> supported_locales;
  // 1. Set options to ? CoerceOptionsToObject(options).
  DirectHandle<JSReceiver> options_obj;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, options_obj,
      CoerceOptionsToObject(isolate, options, method_name));
  // 2. Let matcher be ? GetOption(options, "localeMatcher", "string",
  // "lookup", "best fit" , "best fit").
  Maybe<Intl::MatcherOption> maybe_locale_matcher =
      Intl::GetLocaleMatcher(isolate, options_obj, method_name);
  MAYBE_RETURN(maybe_locale_matcher, {});
  Intl::MatcherOption matcher = maybe_locale_matcher.FromJust();
  // 3. If matcher is "best fit", then
  // a. Let supportedLocales be BestFitSupportedLocales(availableLocales,
  // requestedLocales).
  if (matcher == Intl::MatcherOption::kBestFit &&
      v8_flags.harmony_intl_best_fit_matcher) {
    supported_locales =
        BestFitSupportedLocales(isolate, available_locales, requested_locales);
  } else {
    // 4. Else,
    // a. Let supportedLocales be LookupSupportedLocales(availableLocales,
    // requestedLocales).
    supported_locales =
        LookupSupportedLocales(available_locales, requested_locales);
  }
  // 5. Return CreateArrayFromList(supportedLocales).
  return CreateArrayFromList(isolate, supported_locales,
                             PropertyAttributes::NONE);
}
References ASSIGN_RETURN_ON_EXCEPTION, BestFitSupportedLocales(), v8::internal::CoerceOptionsToObject(), CreateArrayFromList(), v8::Maybe< T >::FromJust(), v8::internal::Intl::GetLocaleMatcher(), v8::internal::Intl::kBestFit, LookupSupportedLocales(), MAYBE_RETURN, v8::internal::NONE, and v8::internal::v8_flags.
Referenced by v8::internal::Intl::SupportedLocalesOf().
ToICUStringPiece()
icu::StringPiece v8::internal::anonymous_namespace{intl-objects.cc}::ToICUStringPiece (Isolate * isolate, DirectHandle< String > string, int offset = 0)
Definition at line 253 of file intl-objects.cc.
                                                  {
  DCHECK(string->IsFlat());
  DisallowGarbageCollection no_gc;
  const String::FlatContent& flat = string->GetFlatContent(no_gc);
  if (!flat.IsOneByte()) return icu::StringPiece();
  int32_t length = string->length();
  const char* char_buffer =
      reinterpret_cast<const char*>(flat.ToOneByteVector().begin());
  if (!String::IsAscii(char_buffer, length)) {
    return icu::StringPiece();
  }
  return icu::StringPiece(char_buffer + offset, length - offset);
}
References v8::base::Vector< T >::begin(), v8::internal::DCHECK(), v8::internal::String::IsAscii(), v8::internal::String::FlatContent::IsOneByte(), v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::string, and v8::internal::String::FlatContent::ToOneByteVector().
Referenced by v8::internal::Intl::CompareStrings().
ToLatin1Lower() [1/2]
constexpr uint8_t v8::internal::anonymous_namespace{intl-objects.cc}::ToLatin1Lower (uint16_t ch) [inline], [constexpr], [delete]
Referenced by v8::internal::Intl::ConvertOneByteToLower().
ToLatin1Lower() [2/2]
constexpr uint8_t v8::internal::anonymous_namespace{intl-objects.cc}::ToLatin1Lower (uint8_t ch) [inline], [constexpr]
Definition at line 106 of file intl-objects.cc.
                                                   {
  static_assert(std::numeric_limits<decltype(ch)>::max() < arraysize(kToLower));
  return kToLower[ch];
}
References arraysize, and kToLower.
ToLatin1Upper() [1/2]
constexpr uint8_t v8::internal::anonymous_namespace{intl-objects.cc}::ToLatin1Upper (uint16_t ch) [inline], [constexpr], [delete]
Referenced by ToUpperOneByte(), and ToUpperWithSharpS().
ToLatin1Upper() [2/2]
constexpr uint8_t v8::internal::anonymous_namespace{intl-objects.cc}::ToLatin1Upper (uint8_t ch) [inline], [constexpr]
Definition at line 115 of file intl-objects.cc.
                                                   {
  DCHECK(ch != 0xDF && ch != 0xB5 && ch != 0xFF);
  return ch &
         ~((IsAsciiLower(ch) || (((ch & 0xE0) == 0xE0) && ch != 0xF7)) << 5);
}
References v8::internal::DCHECK(), and v8::internal::IsAsciiLower().
ToUCollationResult()
constexpr UCollationResult v8::internal::anonymous_namespace{intl-objects.cc}::ToUCollationResult (int delta) [constexpr]
Definition at line 1116 of file intl-objects.cc.
                                                         {
  return delta < 0 ? UCollationResult::UCOL_LESS
                   : (delta > 0 ? UCollationResult::UCOL_GREATER
                                : UCollationResult::UCOL_EQUAL);
}
Referenced by FastCompareFlatString(), and TryFastCompareStrings().
ToUpperFastASCII()
bool v8::internal::anonymous_namespace{intl-objects.cc}::ToUpperFastASCII (base::Vector< const uint16_t > src, DirectHandle< SeqOneByteString > result)
Definition at line 123 of file intl-objects.cc.
                                                             {
  // Do a faster loop for the case where all the characters are ASCII.
  uint16_t ored = 0;
  int32_t index = 0;
  for (const uint16_t* it = src.begin(); it != src.end(); ++it) {
    uint16_t ch = *it;
    ored |= ch;
    result->SeqOneByteStringSet(index++, ToAsciiUpper(ch));
  }
  return !(ored & ~0x7F);
}
References v8::base::Vector< T >::begin(), v8::base::Vector< T >::end(), v8::internal::index, v8::base::internal::result, and v8::internal::ToAsciiUpper().
Referenced by v8::internal::Intl::ConvertToUpper().
ToUpperOneByte()
template<typename Char >
bool v8::internal::anonymous_namespace{intl-objects.cc}::ToUpperOneByte (base::Vector< const Char > src, uint8_t * dest, int * sharp_s_count)
Definition at line 139 of file intl-objects.cc.
                                        {
  // Still pretty-fast path for the input with non-ASCII Latin-1 characters.
  // There are two special cases.
  // 1. U+00B5 and U+00FF are mapped to a character beyond U+00FF.
  // 2. Lower case sharp-S converts to "SS" (two characters)
  *sharp_s_count = 0;
  for (auto it = src.begin(); it != src.end(); ++it) {
    uint8_t ch = AsOneByte(*it);
    if (V8_UNLIKELY(ch == sharp_s)) {
      ++(*sharp_s_count);
      continue;
    }
    if (V8_UNLIKELY(ch == 0xB5 || ch == 0xFF)) {
      // Since this upper-cased character does not fit in an 8-bit string, we
      // need to take the 16-bit path.
      return false;
    }
    *dest++ = ToLatin1Upper(ch);
  }
  return true;
}
References AsOneByte(), v8::base::Vector< T >::begin(), v8::base::Vector< T >::end(), sharp_s, ToLatin1Upper(), and V8_UNLIKELY.
Referenced by v8::internal::Intl::ConvertToUpper().
ToUpperWithSharpS()
template<typename Char >
void v8::internal::anonymous_namespace{intl-objects.cc}::ToUpperWithSharpS (base::Vector< const Char > src, DirectHandle< SeqOneByteString > result)
Definition at line 165 of file intl-objects.cc.
                                                              {
  int32_t dest_index = 0;
  for (auto it = src.begin(); it != src.end(); ++it) {
    uint8_t ch = AsOneByte(*it);
    if (ch == sharp_s) {
      result->SeqOneByteStringSet(dest_index++, 'S');
      result->SeqOneByteStringSet(dest_index++, 'S');
    } else {
      result->SeqOneByteStringSet(dest_index++, ToLatin1Upper(ch));
    }
  }
}
References AsOneByte(), v8::base::Vector< T >::begin(), v8::base::Vector< T >::end(), v8::base::internal::result, sharp_s, and ToLatin1Upper().
Referenced by v8::internal::Intl::ConvertToUpper().
TryFastCompareStrings()
std::optional<UCollationResult> v8::internal::anonymous_namespace{intl-objects.cc}::TryFastCompareStrings (Isolate * isolate, const icu::Collator & icu_collator, DirectHandle< String > string1, DirectHandle< String > string2, int * processed_until_out)
Definition at line 1371 of file intl-objects.cc.
                              {
  // TODO(jgruber): We could avoid the flattening (done by the caller) as well
  // by implementing comparison through string iteration. This has visible
  // performance benefits (e.g. 7% on CDJS) but complicates the code. Consider
  // doing this in the future.
  DCHECK(string1->IsFlat());
  DCHECK(string2->IsFlat());
  *processed_until_out = 0;
#ifdef DEBUG
  // Checked by the caller, see CompareStringsOptionsFor.
  SLOW_DCHECK(CollatorAllowsFastComparison(icu_collator));
  USE(CollatorAllowsFastComparison);
#endif // DEBUG
  DCHECK(!SharedStringAccessGuardIfNeeded::IsNeeded(*string1));
  DCHECK(!SharedStringAccessGuardIfNeeded::IsNeeded(*string2));
  const int length1 = string1->length();
  const int length2 = string2->length();
  int common_length = std::min(length1, length2);
  FastCompareStringsData d;
  DisallowGarbageCollection no_gc;
  const String::FlatContent& flat1 = string1->GetFlatContent(no_gc);
  const String::FlatContent& flat2 = string2->GetFlatContent(no_gc);
  if (!FastCompareStringFlatContent(flat1, flat2, common_length, &d)) {
    DCHECK_EQ(d.l1_result, UCollationResult::UCOL_EQUAL);
    return d.FastCompareFailed(processed_until_out);
  }
  // The result is only valid if the last processed character is not followed
  // by a unicode combining character (we are overly strict and restrict to
  // ASCII).
  if (!CharIsAsciiOrOutOfBounds(flat1, length1, d.processed_until + 1) ||
      !CharIsAsciiOrOutOfBounds(flat2, length2, d.processed_until + 1)) {
    return d.FastCompareFailed(processed_until_out);
  }
  if (d.l1_result != UCollationResult::UCOL_EQUAL) {
    return d.l1_result;
  }
  // Strings are L1-equal up to their common length, length differences win.
  UCollationResult length_result = ToUCollationResult(length1 - length2);
  if (length_result != UCollationResult::UCOL_EQUAL) {
    // Strings of different lengths may still compare as equal if the longer
    // string has a fully ignored suffix, e.g. "a" vs. "a\u{1}".
    if (!CharCanFastCompareOrOutOfBounds(flat1, length1, common_length) ||
        !CharCanFastCompareOrOutOfBounds(flat2, length2, common_length)) {
      return d.FastCompareFailed(processed_until_out);
    }
    return length_result;
  }
  // L1-equal and same length, the L3 result wins.
  return d.l3_result;
}
References CharCanFastCompareOrOutOfBounds(), CharIsAsciiOrOutOfBounds(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::anonymous_namespace{intl-objects.cc}::FastCompareStringsData::FastCompareFailed(), FastCompareStringFlatContent(), v8::internal::SharedStringAccessGuardIfNeeded::IsNeeded(), v8::internal::anonymous_namespace{intl-objects.cc}::FastCompareStringsData::l1_result, v8::internal::anonymous_namespace{intl-objects.cc}::FastCompareStringsData::l3_result, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::anonymous_namespace{intl-objects.cc}::FastCompareStringsData::processed_until, SLOW_DCHECK, ToUCollationResult(), and USE.
Referenced by v8::internal::Intl::CompareStrings().
ValidateResource()
bool v8::internal::anonymous_namespace{intl-objects.cc}::ValidateResource (const icu::Locale locale, const char * path, const char * key)
Definition at line 590 of file intl-objects.cc.
                                       {
  bool result = false;
  UErrorCode status = U_ZERO_ERROR;
  UResourceBundle* bundle = ures_open(path, locale.getName(), &status);
  if (bundle != nullptr && status == U_ZERO_ERROR) {
    if (key == nullptr) {
      result = true;
    } else {
      UResourceBundle* key_bundle =
          ures_getByKey(bundle, key, nullptr, &status);
      result = key_bundle != nullptr && (status == U_ZERO_ERROR);
      ures_close(key_bundle);
    }
  }
  ures_close(bundle);
  if (!result) {
    if ((locale.getCountry()[0] != '\0') && (locale.getScript()[0] != '\0')) {
      // Fallback to try without country.
      std::string without_country(locale.getLanguage());
      without_country = without_country.append("-").append(locale.getScript());
      return ValidateResource(without_country.c_str(), path, key);
    } else if ((locale.getCountry()[0] != '\0') ||
               (locale.getScript()[0] != '\0')) {
      // Fallback to try with only language.
      std::string language(locale.getLanguage());
      return ValidateResource(language.c_str(), path, key);
    }
  }
  return result;
}
References v8::internal::key, v8::base::internal::result, v8::internal::status, and v8::internal::string.
Referenced by v8::internal::Intl::BuildLocaleSet().
VectorToJSArray()
MaybeDirectHandle<JSArray> v8::internal::anonymous_namespace{intl-objects.cc}::VectorToJSArray (Isolate * isolate, const std::vector< std::string > & array)
Definition at line 2187 of file intl-objects.cc.
                                                         {
  Factory* factory = isolate->factory();
  DirectHandle<FixedArray> fixed_array =
      factory->NewFixedArray(static_cast<int32_t>(array.size()));
  int32_t index = 0;
  for (const std::string& item : array) {
    DirectHandle<String> str = factory->NewStringFromAsciiChecked(item.c_str());
    fixed_array->set(index++, *str);
  }
  return factory->NewJSArrayWithElements(fixed_array);
}
References v8::internal::Isolate::factory(), v8::internal::index, v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::Factory::NewJSArrayWithElements(), v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), and v8::internal::string.
Referenced by AvailableCurrencies(), and v8::internal::Intl::ToJSArray().
Variable Documentation
kCollationWeightsL1
constexpr uint8_t v8::internal::anonymous_namespace{intl-objects.cc}::kCollationWeightsL1[256] [constexpr]
Initial value:
= {
    0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    6, 12, 16, 28, 38, 29, 27, 15, 17, 18, 24, 32, 9, 8, 14, 25,
   39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 11, 10, 33, 34, 35, 13,
   23, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
   64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 19, 26, 20, 31, 7,
   30, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
   64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 21, 36, 22, 37, 0,
}
Definition at line 1090 of file intl-objects.cc.
Referenced by v8::internal::Intl::AsciiCollationWeightsL1(), CanFastCompare(), and FastCompareFlatString().
kCollationWeightsL3
constexpr uint8_t v8::internal::anonymous_namespace{intl-objects.cc}::kCollationWeightsL3[256] [constexpr]
Initial value:
= {
    0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
}
Definition at line 1100 of file intl-objects.cc.
Referenced by v8::internal::Intl::AsciiCollationWeightsL3(), and FastCompareFlatString().
kCollationWeightsLength
constexpr int v8::internal::anonymous_namespace{intl-objects.cc}::kCollationWeightsLength = arraysize(kCollationWeightsL1) [constexpr]
Definition at line 1110 of file intl-objects.cc.
Referenced by CanFastCompare().
kToLower
constexpr uint8_t v8::internal::anonymous_namespace{intl-objects.cc}::kToLower[256] [constexpr]
Initial value:
= {
    0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B,
    0x0C, 0x0D, 0x0E, 0x0F, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17,
    0x18, 0x19, 0x1A, 0x1B, 0x1C, 0x1D, 0x1E, 0x1F, 0x20, 0x21, 0x22, 0x23,
    0x24, 0x25, 0x26, 0x27, 0x28, 0x29, 0x2A, 0x2B, 0x2C, 0x2D, 0x2E, 0x2F,
    0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x3A, 0x3B,
    0x3C, 0x3D, 0x3E, 0x3F, 0x40, 0x61, 0x62, 0x63, 0x64, 0x65, 0x66, 0x67,
    0x68, 0x69, 0x6A, 0x6B, 0x6C, 0x6D, 0x6E, 0x6F, 0x70, 0x71, 0x72, 0x73,
    0x74, 0x75, 0x76, 0x77, 0x78, 0x79, 0x7A, 0x5B, 0x5C, 0x5D, 0x5E, 0x5F,
    0x60, 0x61, 0x62, 0x63, 0x64, 0x65, 0x66, 0x67, 0x68, 0x69, 0x6A, 0x6B,
    0x6C, 0x6D, 0x6E, 0x6F, 0x70, 0x71, 0x72, 0x73, 0x74, 0x75, 0x76, 0x77,
    0x78, 0x79, 0x7A, 0x7B, 0x7C, 0x7D, 0x7E, 0x7F, 0x80, 0x81, 0x82, 0x83,
    0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8A, 0x8B, 0x8C, 0x8D, 0x8E, 0x8F,
    0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9A, 0x9B,
    0x9C, 0x9D, 0x9E, 0x9F, 0xA0, 0xA1, 0xA2, 0xA3, 0xA4, 0xA5, 0xA6, 0xA7,
    0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3,
    0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF,
    0xE0, 0xE1, 0xE2, 0xE3, 0xE4, 0xE5, 0xE6, 0xE7, 0xE8, 0xE9, 0xEA, 0xEB,
    0xEC, 0xED, 0xEE, 0xEF, 0xF0, 0xF1, 0xF2, 0xF3, 0xF4, 0xF5, 0xF6, 0xD7,
    0xF8, 0xF9, 0xFA, 0xFB, 0xFC, 0xFD, 0xFE, 0xDF, 0xE0, 0xE1, 0xE2, 0xE3,
    0xE4, 0xE5, 0xE6, 0xE7, 0xE8, 0xE9, 0xEA, 0xEB, 0xEC, 0xED, 0xEE, 0xEF,
    0xF0, 0xF1, 0xF2, 0xF3, 0xF4, 0xF5, 0xF6, 0xF7, 0xF8, 0xF9, 0xFA, 0xFB,
    0xFC, 0xFD, 0xFE, 0xFF,
}
Definition at line 81 of file intl-objects.cc.
Referenced by ToLatin1Lower(), and v8::internal::Intl::ToLatin1LowerTable().
sharp_s
const uint16_t v8::internal::anonymous_namespace{intl-objects.cc}::sharp_s = 0xDF
Definition at line 136 of file intl-objects.cc.
Referenced by ToUpperOneByte(), and ToUpperWithSharpS().