v8::internal::wasm Namespace Reference
Namespaces
 anonymous_namespace{asm-types.cc}
 anonymous_namespace{constant-expression-interface.cc}
 anonymous_namespace{liftoff-assembler.cc}
 anonymous_namespace{liftoff-compiler.cc}
 anonymous_namespace{module-compiler.cc}
 anonymous_namespace{module-decoder.cc}
 anonymous_namespace{module-instantiate.cc}
 anonymous_namespace{names-provider.cc}
 anonymous_namespace{simd-shuffle.cc}
 anonymous_namespace{streaming-decoder.cc}
 anonymous_namespace{turboshaft-graph-interface.cc}
 anonymous_namespace{value-type.cc}
 anonymous_namespace{wasm-code-manager.cc}
 anonymous_namespace{wasm-debug.cc}
 anonymous_namespace{wasm-engine.cc}
 anonymous_namespace{wasm-external-refs.cc}
 anonymous_namespace{wasm-interpreter-runtime.cc}
 anonymous_namespace{wasm-interpreter.cc}
 anonymous_namespace{wasm-module-builder.cc}
 anonymous_namespace{wasm-module.cc}
 anonymous_namespace{wasm-objects.cc}
 anonymous_namespace{wasm-result.cc}
 anonymous_namespace{wasm-serialization.cc}
 anonymous_namespace{wasm-subtyping.cc}
 anonymous_namespace{wrappers.cc}
 baseline
 detail
 fuzzing
 gdb_server
 impl
 liftoff
 value_type_impl
 value_type_reader
Classes
class AsmJsParser
class AsmValueType
class AsmCallableType
class AsmFunctionType
class AsmOverloadedFunctionType
class AsmType
class GetProtectedInstruction
class FreezeCacheState
class LiftoffAssembler
class LiftoffStackSlots
struct LiftoffOptions
class LiftoffRegister
class LiftoffRegList
class LiftoffVarState
class ParallelMove
class BasicBlockCalculator
class BranchHintMap
class TypeCanonicalizer
class CodeSpaceWriteScope
struct CompilationEnv
class WireBytesStorage
class CompilationEventCallback
class CompilationState
class ConstantExpressionInterface
class ConstantExpression
class ITracer
class Decoder
struct ImmI32Immediate
struct ImmI64Immediate
struct ImmF32Immediate
struct ImmF64Immediate
struct BrOnCastFlags
struct BrOnCastImmediate
struct IndexImmediate
struct MemoryIndexImmediate
struct TableIndexImmediate
struct TagIndexImmediate
struct GlobalIndexImmediate
struct TypeIndexImmediate
struct SigIndexImmediate
struct ContIndexImmediate
struct StructIndexImmediate
struct ArrayIndexImmediate
struct CallFunctionImmediate
struct SelectTypeImmediate
struct BlockTypeImmediate
struct BranchDepthImmediate
struct FieldImmediate
struct MemoryOrderImmediate
struct CallIndirectImmediate
struct BranchTableImmediate
class BranchTableIterator
struct CatchCase
class TryTableIterator
struct HandlerCase
class EffectHandlerTableIterator
struct MemoryAccessImmediate
struct SimdLaneImmediate
struct Simd128Immediate
struct MemoryInitImmediate
struct MemoryCopyImmediate
struct TableInitImmediate
struct TableCopyImmediate
struct HeapTypeImmediate
struct StringConstImmediate
struct PcForErrors
struct PcForErrors< true >
struct ValueBase
struct Merge
struct ControlBase
class FastZoneVector
class WasmDecoder
class NoVector
class WasmFullDecoder
class EmptyInterface
struct FunctionBody
struct BodyLocalDecls
class BytecodeIterator
class AssumptionsJournal
struct WasmCompilationResult
class WasmCompilationUnit
class JSToWasmWrapperCompilationUnit
class InliningTree
struct TreeNodeOrdering
class ValueTypes
class IndirectFunctionTableEntry
struct StackHandlerMarker
class WasmInterpreterRuntime
class InterpreterHandle
class HandlersBase
class Handlers
struct InterpreterCode
struct FrameState
class WasmExecutionTimer
class WasmInterpreterThreadMap
class WasmInterpreterThread
class WasmInterpreter
struct handler_traits
struct handler_traits< true >
struct handler_traits< false >
struct RegModeTransform
struct BranchOnCastData
struct WasmInstruction
struct Slot
class WasmEHData
class WasmEHDataGenerator
class WasmBytecode
class WasmBytecodeGenerator
class ClearThreadInWasmScope
class JumpTableAssembler
class LEBHelper
struct LocalDeclEncoderBuffer
class LocalDeclEncoder
struct MemoryTracingInfo
class TransitiveTypeFeedbackProcessor
class FeedbackMaker
struct ValidateFunctionsStreamingJobData
class ValidateFunctionsStreamingJob
class AsyncStreamingProcessor
class AsyncCompileJob
class WasmSectionIterator
class ModuleDecoderImpl
class DescriptorsSectionIterator
struct AsmJsOffsetEntry
struct AsmJsOffsetFunctionEntries
struct AsmJsOffsets
class DecodedNameSection
struct CustomSectionOffset
class ModuleDecoder
class JSPrototypesSetup
class InstanceBuilder
class ResolvedWasmImport
struct WrapperCompilationInfo
class NamesProvider
class CanonicalTypeNamesProvider
class ObjectAccess
class ProfileGenerator
class ProfileInformation
class SignatureHasher
class SimdShuffle
class SimdSwizzle
struct JumpBuffer
class StackMemory
class StackPool
class AsyncStreamingDecoder
class StreamingProcessor
class StreamingDecoder
struct LabelInfo
class MultiLineStringBuilder
class StringBuilder
class StructTypeBase
class StructType
class CanonicalStructType
class ArrayTypeBase
class ArrayType
class CanonicalArrayType
class ContType
class CanonicalContType
class SyncStreamingDecoder
class TurboshaftGraphBuildingInterface
class WasmGraphBuilderBase
struct TypeIndex
struct ModuleTypeIndex
struct CanonicalTypeIndex
class ValueTypeBase
class HeapType
class ValueType
class CanonicalValueType
class IndependentValueType
class IndependentHeapType
class CanonicalSig
class LoadType
class StoreType
class CWasmArgumentsPacker
class BuiltinLookup
struct WasmCodeRange
class WasmFunctionCoverageData
class WasmModuleCoverageData
class DisjointAllocationPool
class WasmCode
struct UnpublishedWasmCode
class WasmCodeAllocator
class NativeModule
class WasmCodeManager
class WasmCodeRefScope
class WasmCodeLookupCache
struct WasmCodePointerTableEntry
class WasmCodePointerTable
class DebugInfoImpl
class DebugSideTable
class DebugInfo
struct WasmDeoptData
struct WasmDeoptEntry
class WasmDeoptView
class WasmDeoptDataProcessor
struct LiftoffFrameDescriptionForDeopt
class ImmediatesPrinter
class Indentation
class OffsetsProvider
class FunctionBodyDisassembler
class ModuleDisassembler
class WasmOrphanedGlobalHandle
class CompilationResultResolver
class InstantiationResultResolver
class NativeModuleCache
class WasmEngine
class WasmExportWrapperCache
class WasmEnabledFeatures
class WasmDetectedFeatures
class CompileTimeImports
class WasmImportWrapperCache
class WasmImportWrapperHandle
class WasmInitExpr
class LinkageAllocator
class LinkageLocationAllocator
class ZoneBuffer
class WasmFunctionBuilder
class WasmModuleBuilder
class WasmModuleSourceMap
class WireBytesRef
struct WasmFunction
struct WasmGlobal
struct WasmTag
struct WasmMemory
struct WasmStringRefLiteral
struct WasmDataSegment
struct WasmElemSegment
struct WasmImport
struct WasmExport
struct WasmCompilationHint
class AdaptiveMap
class LazilyGeneratedNames
class AsmJsOffsetInformation
struct TypeDefinition
struct WasmDebugSymbols
class CallSiteFeedback
struct FunctionTypeFeedback
struct TypeFeedbackStorage
struct WasmTable
struct WasmModule
struct ModuleWireBytes
struct WasmFunctionName
class TruncatedUserString
class WasmOpcodes
class WasmError
class Result
class ErrorThrower
class NativeModuleSerializer
struct DeserializationUnit
class DeserializationQueue
class NativeModuleDeserializer
class DeserializeCodeTask
class WasmSerializer
struct TypeInModule
class WasmValue
class WellKnownImportsList
class WasmWrapperTSGraphBuilder
Typedefs
using WasmName = base::Vector< const char >
using VarState = LiftoffAssembler::VarState
using ValueKindSig = LiftoffAssembler::ValueKindSig
using BranchHintInfo = std::unordered_map< uint32_t, BranchHintMap >
using ValueOrError = std::variant< WasmValue, MessageTemplate >
using DecodeResult = VoidResult
using TryTableImmediate = BranchTableImmediate
using EffectHandlerTableImmediate = BranchTableImmediate
using TypeChecker = bool(*)(const WasmRef obj)
using pc_t = size_t
using CodeOffset = size_t
using WasmRef = DirectHandle< Object >
typedef uint32_t * sp
typedef uint32_t WasmInterpreterRuntime * wasm_runtime
typedef uint32_t WasmInterpreterRuntime int64_t r0
typedef uint32_t WasmInterpreterRuntime int64_t double fp0
using ModuleResult = Result< std::shared_ptr< WasmModule > >
using FunctionResult = Result< std::unique_ptr< WasmFunction > >
using FunctionOffsets = std::vector< std::pair< int, int > >
using FunctionOffsetsResult = Result< FunctionOffsets >
using AsmJsOffsetsResult = Result< AsmJsOffsets >
using TSBlock = compiler::turboshaft::Block
using FunctionSig = Signature< ValueType >
using WasmCodePosition = int
using IndexAsComment = NamesProvider::IndexAsComment
using Address = uintptr_t
using CompileTimeImportFlags = base::EnumSet< CompileTimeImport, int >
using WasmTagSig = FunctionSig
using NameMap = AdaptiveMap< WireBytesRef >
using IndirectNameMap = AdaptiveMap< AdaptiveMap< WireBytesRef > >
using VoidResult = Result< std::nullptr_t >
Enumerations
enum class CallOrigin { kCalledFromWasm
, kCalledFromJS
 }
enum class LoadOrStore : bool { kLoad
, kStore
 }
enum LiftoffBailoutReason : int8_t {
kSuccess = 0
, kDecodeError = 1
, kUnsupportedArchitecture = 2
, kMissingCPUFeature = 3
,
kComplexOperation = 4
, kSimd = 5
, kRefTypes = 6
, kExceptionHandling = 7
,
kMultiValue = 8
, kTailCall = 9
, kAtomics = 10
, kBulkMemory = 11
,
kNonTrappingFloatToInt = 12
, kGC = 13
, kRelaxedSimd = 14
, kOtherReason = 20
,
kNumBailoutReasons
 }
enum class LocationKindForDeopt : uint8_t { kNone
, kEagerDeopt
, kInlinedCall
 }
enum RegClass : uint8_t {
kGpReg
, kFpReg
, kGpRegPair = kFpReg + 1 + (kNeedS128RegPair && !kNeedI64RegPair)
, kFpRegPair = kFpReg + 1 + kNeedI64RegPair
,
kNoReg = kFpRegPair + kNeedS128RegPair
 }
enum RegPairHalf : uint8_t { kLowWord = 0
, kHighWord = 1
 }
enum class CompilationEvent : uint8_t { kFinishedBaselineCompilation
, kFinishedCompilationChunk
, kFailedCompilation
 }
enum DecodingMode { kFunctionBody
, kConstantExpression
 }
enum ControlKind : uint8_t {
kControlIf
, kControlIfElse
, kControlBlock
, kControlLoop
,
kControlTry
, kControlTryTable
, kControlTryCatch
, kControlTryCatchAll
 }
enum Reachability : uint8_t { kReachable
, kSpecOnlyReachable
, kUnreachable
 }
enum class LoadTransformationKind : uint8_t { kSplat
, kExtend
, kZeroExtend
 }
enum BoundsCheckedHandlersCounter { kTotalItems
 }
enum OperatorMode { kR2R = 0
, kR2S
, kS2R
, kS2S
 }
enum class RegMode {
kNoReg
, kI32Reg
, kI64Reg
, kF32Reg
,
kF64Reg
, kAnyReg
 }
enum ExternalCallResult { EXTERNAL_RETURNED
, EXTERNAL_EXCEPTION
 }
enum InstructionHandler : uint16_t { kInstructionCount
 }
enum InstrHandlerSize { Large = 0
, Small = 1
 }
enum class DecodingMethod {
kSync
, kAsync
, kSyncStream
, kAsyncStream
,
kDeserialize
 }
enum Suspend : int { kSuspend
, kNoSuspend
 }
enum Promise : int { kPromise
, kNoPromise
, kStressSwitch
 }
enum class ImportCallKind : uint8_t {
kLinkError
, kRuntimeTypeError
, kWasmToCapi
, kWasmToJSFastApi
,
kWasmToWasm
, kJSFunction
, kUseCallBuiltin
 }
enum Nullability : bool { kNonNullable = false
, kNullable = true
 }
enum Exactness : bool { kAnySubtype
, kExact
 }
enum ValueKind : uint8_t
enum class TypeKind : uint8_t { kNumeric = 0b00
, kSentinel = SENTINEL
, kAbstractRef = REF
, kIndexedRef = REF | SENTINEL
 }
enum class RefTypeKind : uint8_t {
kOther = 0
, kFunction = 1
, kStruct = 2
, kArray = 3
,
kCont = 4
, kLastValue = kCont
 }
enum class StandardType : uint8_t { DEF_ENUM
, FOREACH_GENERIC_TYPE =(DEF_ENUM) FOREACH_NUMERIC_VALUE_TYPE(DEF_ENUM)
 }
enum class GenericKind : uint32_t { DEF_ENUM
 }
enum class NumericKind : uint32_t { DEF_ENUM
 }
enum ValueTypeCode : uint8_t {
kVoidCode = 0x40
, kI32Code = 0x7f
, kI64Code = 0x7e
, kF32Code = 0x7d
,
kF64Code = 0x7c
, kS128Code = 0x7b
, kI8Code = 0x78
, kI16Code = 0x77
,
kF16Code = 0x76
, kNoExnCode = 0x74
, kNoFuncCode = 0x73
, kNoExternCode = 0x72
,
kNoneCode = 0x71
, kFuncRefCode = 0x70
, kExternRefCode = 0x6f
, kAnyRefCode = 0x6e
,
kEqRefCode = 0x6d
, kI31RefCode = 0x6c
, kStructRefCode = 0x6b
, kArrayRefCode = 0x6a
,
kRefCode = 0x64
, kRefNullCode = 0x63
, kExactCode = 0x62
, kExnRefCode = 0x69
,
kContRefCode = 0x68
, kNoContCode = 0x75
, kStringRefCode = 0x67
, kStringViewWtf8Code = 0x66
,
kStringViewWtf16Code = 0x60
, kStringViewIterCode = 0x61
, kFirstHeapTypeCode = kStringViewWtf16Code
, kLastHeapTypeCode = kNoContCode
 }
enum ImportExportKindCode : uint8_t {
kExternalFunction = 0
, kExternalTable = 1
, kExternalMemory = 2
, kExternalGlobal = 3
,
kExternalTag = 4
 }
enum LimitsFlags : uint8_t {
kNoMaximum = 0x00
, kWithMaximum = 0x01
, kSharedNoMaximum = 0x02
, kSharedWithMaximum = 0x03
,
kMemory64NoMaximum = 0x04
, kMemory64WithMaximum = 0x05
, kMemory64SharedNoMaximum = 0x06
, kMemory64SharedWithMaximum = 0x07
 }
enum SegmentFlags : uint8_t { kActiveNoIndex = 0
, kPassive = 1
, kActiveWithIndex = 2
 }
enum SectionCode : int8_t {
kUnknownSectionCode = 0
, kTypeSectionCode = 1
, kImportSectionCode = 2
, kFunctionSectionCode = 3
,
kTableSectionCode = 4
, kMemorySectionCode = 5
, kGlobalSectionCode = 6
, kExportSectionCode = 7
,
kStartSectionCode = 8
, kElementSectionCode = 9
, kCodeSectionCode = 10
, kDataSectionCode = 11
,
kDataCountSectionCode = 12
, kTagSectionCode = 13
, kStringRefSectionCode = 14
, kNameSectionCode
,
kSourceMappingURLSectionCode
, kDebugInfoSectionCode
, kExternalDebugInfoSectionCode
, kBuildIdSectionCode
,
kInstTraceSectionCode
, kCompilationHintsSectionCode
, kBranchHintsSectionCode
, kDescriptorsSectionCode
,
kFirstSectionInModule = kTypeSectionCode
, kLastKnownModuleSection = kStringRefSectionCode
, kFirstUnorderedSection = kDataCountSectionCode
 }
enum NameSectionKindCode : uint8_t {
kModuleCode = 0
, kFunctionCode = 1
, kLocalCode = 2
, kLabelCode = 3
,
kTypeCode = 4
, kTableCode = 5
, kMemoryCode = 6
, kGlobalCode = 7
,
kElementSegmentCode = 8
, kDataSegmentCode = 9
, kFieldCode = 10
, kTagCode = 11
 }
enum CatchKind : uint8_t {
kCatch = 0x0
, kCatchRef = 0x1
, kCatchAll = 0x2
, kCatchAllRef = 0x3
,
kLastCatchKind = kCatchAllRef
 }
enum SwitchKind : uint8_t { kOnSuspend = 0x0
, kSwitch = 0x1
, kLastSwitchKind = kSwitch
 }
enum class WasmEnabledFeature { DECL_FEATURE_ENUM
 }
enum class WasmDetectedFeature { DECL_FEATURE_ENUM
 }
enum class CompileTimeImport {
kJsString
, kStringConstants
, kTextEncoder
, kTextDecoder
,
kDisableDenormalFloats
 }
enum class AddressType : uint8_t { kI32
, kI64
 }
enum ModuleOrigin : uint8_t { kWasmOrigin
, kAsmJsSloppyOrigin
, kAsmJsStrictOrigin
 }
enum BoundsCheckStrategy : int8_t { kTrapHandler
, kExplicitBoundsChecks
, kNoBoundsChecks
 }
enum class WasmCompilationHintStrategy : uint8_t { kDefault = 0
, kLazy = 1
, kEager = 2
, kLazyBaselineEagerTopTier = 3
 }
enum class WasmCompilationHintTier : uint8_t { kDefault = 0
, kBaseline = 1
, kOptimized = 2
 }
enum class OnResume : int { kContinue
, kThrow
 }
enum WasmOpcode
enum TrapReason { kTrapCount
 }
enum class ExecutionTier : int8_t { kNone
, kLiftoff
, kTurbofan
 }
enum ForDebugging : int8_t { kNotForDebugging = 0
, kForDebugging
, kWithBreakpoints
, kForStepping
 }
enum DebugState : bool { kNotDebugging = false
, kDebugging = true
 }
enum class WellKnownImport : uint8_t {
kUninstantiated
, kGeneric
, kLinkError
, kFirstCompileTimeImport
,
kStringCast = kFirstCompileTimeImport
, kStringCharCodeAt
, kStringCodePointAt
, kStringCompare
,
kStringConcat
, kStringEquals
, kStringFromCharCode
, kStringFromCodePoint
,
kStringFromUtf8Array
, kStringFromWtf16Array
, kStringIntoUtf8Array
, kStringLength
,
kStringMeasureUtf8
, kStringSubstring
, kStringTest
, kStringToUtf8Array
,
kStringToWtf16Array
, kLastCompileTimeImport = kStringToWtf16Array
, kDataViewGetBigInt64
, kDataViewGetBigUint64
,
kDataViewGetFloat32
, kDataViewGetFloat64
, kDataViewGetInt8
, kDataViewGetInt16
,
kDataViewGetInt32
, kDataViewGetUint8
, kDataViewGetUint16
, kDataViewGetUint32
,
kDataViewSetBigInt64
, kDataViewSetBigUint64
, kDataViewSetFloat32
, kDataViewSetFloat64
,
kDataViewSetInt8
, kDataViewSetInt16
, kDataViewSetInt32
, kDataViewSetUint8
,
kDataViewSetUint16
, kDataViewSetUint32
, kDataViewByteLength
, kMathF64Acos
,
kMathF64Asin
, kMathF64Atan
, kMathF64Atan2
, kMathF64Cos
,
kMathF64Sin
, kMathF64Tan
, kMathF64Exp
, kMathF64Log
,
kMathF64Pow
, kMathF64Sqrt
, kDoubleToString
, kIntToString
,
kParseFloat
, kStringIndexOf
, kStringIndexOfImported
, kStringToLocaleLowerCaseStringref
,
kStringToLowerCaseStringref
, kStringToLowerCaseImported
, kFastAPICall
 }
Functions
std::ostream & operator<< (std::ostream &os, LiftoffVarState slot)
constexpr Condition Negate (Condition cond)
constexpr Condition Flip (Condition cond)
WasmCompilationResult ExecuteLiftoffCompilation (CompilationEnv *env, const FunctionBody &func_body, const LiftoffOptions &compiler_options)
std::unique_ptr< DebugSideTable > GenerateLiftoffDebugSideTable (const WasmCode *code)
static constexpr bool needs_gp_reg_pair (ValueKind kind)
static constexpr bool needs_fp_reg_pair (ValueKind kind)
static constexpr RegClass reg_class_for (ValueKind kind)
ASSERT_TRIVIALLY_COPYABLE (LiftoffRegister)
std::ostream & operator<< (std::ostream &os, LiftoffRegister reg)
ASSERT_TRIVIALLY_COPYABLE (LiftoffRegList)
static constexpr LiftoffRegList GetCacheRegList (RegClass rc)
std::ostream & operator<< (std::ostream &os, LiftoffRegList reglist)
ASSERT_TRIVIALLY_COPYABLE (LiftoffVarState)
static FPUCondition ConditionToConditionCmpFPU (Condition condition)
template<void(Assembler::*)(YMMRegister, YMMRegister, YMMRegister) avx_op>
bool F16x8CmpOpViaF32 (LiftoffAssembler *assm, LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
template<void(Assembler::*)(YMMRegister, YMMRegister, YMMRegister) avx_op>
bool F16x8BinOpViaF32 (LiftoffAssembler *assm, LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
TypeCanonicalizer * GetTypeCanonicalizer ()
ValueOrError EvaluateConstantExpression (Zone *zone, ConstantExpression expr, ValueType expected, const WasmModule *module, Isolate *isolate, DirectHandle< WasmTrustedInstanceData > trusted_instance_data, DirectHandle< WasmTrustedInstanceData > shared_trusted_instance_data)
bool is_error (ValueOrError result)
MessageTemplate to_error (ValueOrError result)
WasmValue to_value (ValueOrError result)
static constexpr LoadType GetLoadType (WasmOpcode opcode)
static constexpr StoreType GetStoreType (WasmOpcode opcode)
template<typename ValidationTag , typename... Args>
void DecodeError (Decoder *decoder, const uint8_t *pc, const char *str, Args &&... args)
template<typename ValidationTag , typename... Args>
void DecodeError (Decoder *decoder, const char *str, Args &&... args)
template<typename ValidationTag >
bool DecodeLocalDecls (WasmEnabledFeatures enabled, BodyLocalDecls *decls, const WasmModule *module, bool is_shared, const uint8_t *start, const uint8_t *end, Zone *zone)
void DecodeLocalDecls (WasmEnabledFeatures enabled, BodyLocalDecls *decls, const uint8_t *start, const uint8_t *end, Zone *zone)
bool ValidateAndDecodeLocalDeclsForTesting (WasmEnabledFeatures enabled, BodyLocalDecls *decls, const WasmModule *module, bool is_shared, const uint8_t *start, const uint8_t *end, Zone *zone)
DecodeResult ValidateFunctionBody (Zone *zone, WasmEnabledFeatures enabled, const WasmModule *module, WasmDetectedFeatures *detected, const FunctionBody &body)
unsigned OpcodeLength (const uint8_t *pc, const uint8_t *end)
bool CheckHardwareSupportsSimd ()
BitVector * AnalyzeLoopAssignmentForTesting (Zone *zone, uint32_t num_locals, const uint8_t *start, const uint8_t *end, bool *loop_is_innermost)
ASSERT_TRIVIALLY_COPYABLE (WasmCompilationUnit)
bool CanUseGenericJsToWasmWrapper (const WasmModule *module, const CanonicalSig *sig)
uint32_t GetValueSizeInSlots (ValueKind kind)
V8_EXPORT_PRIVATE InterpreterHandle * GetInterpreterHandle (Isolate *isolate, DirectHandle< Tuple2 > interpreter_object)
V8_EXPORT_PRIVATE InterpreterHandle * GetOrCreateInterpreterHandle (Isolate *isolate, DirectHandle< Tuple2 > interpreter_object)
DISABLE_CFI_ICALL void CallThroughDispatchTable (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
template<TypeChecker type_checker>
bool AbstractTypeCast (Isolate *isolate, const WasmRef obj, const ValueType obj_type, bool null_succeeds)
static bool EqCheck (const WasmRef obj)
static bool I31Check (const WasmRef obj)
static bool StructCheck (const WasmRef obj)
static bool ArrayCheck (const WasmRef obj)
static bool StringCheck (const WasmRef obj)
V8_DECLARE_ONCE (init_instruction_table_once)
V8_DECLARE_ONCE (init_trap_handlers_once)
INSTRUCTION_HANDLER_FUNC TrapMemOutOfBounds (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
void InitTrapHandlersOnce (Isolate *isolate)
void InitInstructionTableOnce (Isolate *isolate)
static int StructFieldOffset (const StructType *struct_type, int field_index)
const char * GetRegModeString (RegMode reg_mode)
const char * GetOperatorModeString (OperatorMode mode)
typedef void (VECTORCALL PWasmOp)(const uint8_t *code
RegMode GetRegMode (ValueKind kind)
template<typename T >
INSTRUCTION_HANDLER_FUNC trace_PushSlot (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
template<typename T >
static ValueType value_type ()
template<> ValueType value_type< int32_t > ()
template<> ValueType value_type< uint32_t > ()
template<> ValueType value_type< int64_t > ()
template<> ValueType value_type< uint64_t > ()
template<> ValueType value_type< float > ()
template<> ValueType value_type< double > ()
template<> ValueType value_type< Simd128 > ()
template<> ValueType value_type< WasmRef > ()
InstructionHandler ReadFnId (const uint8_t *&code)
bool CompileLazy (Isolate *isolate, Tagged< WasmTrustedInstanceData > trusted_instance_data, int func_index)
void ThrowLazyCompilationError (Isolate *isolate, const NativeModule *native_module, int func_index)
bool IsCrossInstanceCall (Tagged< Object > obj, Isolate *const isolate)
void TriggerTierUp (Isolate *isolate, Tagged< WasmTrustedInstanceData > trusted_instance_data, int func_index)
void TierUpNowForTesting (Isolate *isolate, Tagged< WasmTrustedInstanceData > trusted_instance_data, int func_index)
void TierUpAllForTesting (Isolate *isolate, Tagged< WasmTrustedInstanceData > trusted_instance_data)
void InitializeCompilationForTesting (NativeModule *native_module)
void PublishDetectedFeatures (WasmDetectedFeatures detected_features, Isolate *isolate, bool is_initial_compilation)
WasmError ValidateAndSetBuiltinImports (const WasmModule *module, base::Vector< const uint8_t > wire_bytes, const CompileTimeImports &imports, WasmDetectedFeatures *detected)
std::shared_ptr< NativeModule > CompileToNativeModule (Isolate *isolate, WasmEnabledFeatures enabled_features, WasmDetectedFeatures detected_features, CompileTimeImports compile_imports, ErrorThrower *thrower, std::shared_ptr< const WasmModule > module, base::OwnedVector< const uint8_t > wire_bytes, int compilation_id, v8::metrics::Recorder::ContextId context_id, ProfileInformation *pgo_info)
std::shared_ptr< wasm::WasmImportWrapperHandle > CompileImportWrapperForTest (Isolate *isolate, ImportCallKind kind, const CanonicalSig *sig, CanonicalTypeIndex type_index, int expected_arity, Suspend suspend)
const char * ExternalKindName (ImportExportKindCode kind)
bool validate_utf8 (Decoder *decoder, WireBytesRef string)
WireBytesRef consume_string (Decoder *decoder, unibrow::Utf8Variant grammar, const char *name, ITracer *tracer)
WireBytesRef consume_string (Decoder *decoder, unibrow::Utf8Variant grammar, const char *name)
WireBytesRef consume_utf8_string (Decoder *decoder, const char *name, ITracer *tracer)
SectionCode IdentifyUnknownSectionInternal (Decoder *decoder, ITracer *tracer)
void DumpModule (const base::Vector< const uint8_t > module_bytes, bool ok)
const char * SectionName (SectionCode code)
ModuleResult DecodeWasmModule (WasmEnabledFeatures enabled_features, base::Vector< const uint8_t > wire_bytes, bool validate_functions, ModuleOrigin origin, Counters *counters, std::shared_ptr< metrics::Recorder > metrics_recorder, v8::metrics::Recorder::ContextId context_id, DecodingMethod decoding_method, WasmDetectedFeatures *detected_features)
ModuleResult DecodeWasmModule (WasmEnabledFeatures enabled_features, base::Vector< const uint8_t > wire_bytes, bool validate_functions, ModuleOrigin origin, WasmDetectedFeatures *detected_features)
ModuleResult DecodeWasmModuleForDisassembler (base::Vector< const uint8_t > wire_bytes, ITracer *tracer)
Result< const FunctionSig * > DecodeWasmSignatureForTesting (WasmEnabledFeatures enabled_features, Zone *zone, base::Vector< const uint8_t > bytes)
ConstantExpression DecodeWasmInitExprForTesting (WasmEnabledFeatures enabled_features, base::Vector< const uint8_t > bytes, ValueType expected)
FunctionResult DecodeWasmFunctionForTesting (WasmEnabledFeatures enabled_features, Zone *zone, ModuleWireBytes wire_bytes, const WasmModule *module, base::Vector< const uint8_t > function_bytes)
AsmJsOffsetsResult DecodeAsmJsOffsets (base::Vector< const uint8_t > encoded_offsets)
std::vector< CustomSectionOffset > DecodeCustomSections (base::Vector< const uint8_t > bytes)
void DecodeFunctionNames (base::Vector< const uint8_t > wire_bytes, NameMap &names)
void DecodeCanonicalTypeNames (base::Vector< const uint8_t > wire_bytes, const WasmModule *module, std::vector< base::OwnedVector< char >> &typenames, std::map< uint32_t, std::vector< base::OwnedVector< char >>> &fieldnames, size_t *total_allocated_size)
WasmError ValidateFunctions (const WasmModule *module, WasmEnabledFeatures enabled_features, base::Vector< const uint8_t > wire_bytes, std::function< bool(int)> filter, WasmDetectedFeatures *detected_features_out)
WasmError GetWasmErrorWithName (base::Vector< const uint8_t > wire_bytes, int func_index, const WasmModule *module, WasmError error)
bool IsValidSectionCode (uint8_t byte)
void CreateMapForType (Isolate *isolate, const WasmModule *module, ModuleTypeIndex type_index, DirectHandle< FixedArray > maybe_shared_maps)
MaybeDirectHandle< WasmInstanceObject > InstantiateToInstanceObject (Isolate *isolate, ErrorThrower *thrower, DirectHandle< WasmModuleObject > module_object, MaybeDirectHandle< JSReceiver > imports, MaybeDirectHandle< JSArrayBuffer > memory_buffer)
std::tuple< const char *, Builtin, int > NameBuiltinLength (WellKnownImport wki)
DirectHandle< JSFunction > CreateFunctionForCompileTimeImport (Isolate *isolate, WellKnownImport wki)
std::optional< MessageTemplate > InitializeElementSegment (Zone *zone, Isolate *isolate, DirectHandle< WasmTrustedInstanceData > trusted_instance_data, DirectHandle< WasmTrustedInstanceData > shared_trusted_instance_data, uint32_t segment_index)
WireBytesRef Get (const NameMap &map, uint32_t index)
WireBytesRef Get (const IndirectNameMap &map, uint32_t outer_index, uint32_t inner_index)
void DeserializeTypeFeedback (Decoder &decoder, const WasmModule *module)
std::unique_ptr< ProfileInformation > DeserializeTieringInformation (Decoder &decoder, const WasmModule *module)
std::unique_ptr< ProfileInformation > RestoreProfileData (const WasmModule *module, base::Vector< uint8_t > profile_data)
void DumpProfileToFile (const WasmModule *module, base::Vector< const uint8_t > wire_bytes, std::atomic< uint32_t > *tiering_budget_array)
std::unique_ptr< ProfileInformation > LoadProfileFromFile (const WasmModule *module, base::Vector< const uint8_t > wire_bytes)
MachineRepresentation GetMachineRepresentation (ValueTypeBase type)
MachineRepresentation GetMachineRepresentation (MachineType type)
template<class ResultCollector , class SigType >
void IterateSignatureImpl (const SigType *sig, bool extra_callable_param, ResultCollector &locations, int *untagged_parameter_slots, int *total_parameter_slots, int *untagged_return_slots, int *total_return_slots)
template<size_t N>
constexpr const SimdShuffle::ShuffleArray expand (const std::array< uint8_t, N > in)
template<int kLanes, int kLaneBytes>
bool MatchHelper (const uint8_t *input, uint8_t *output)
template<typename T >
size_t ContentSize (const std::vector< T > &vector)
template<typename T >
size_t ContentSize (const base::OwnedVector< T > &vector)
template<typename Key , typename T >
size_t ContentSize (const std::map< Key, T > &map)
template<typename Key , typename T , typename Hash >
size_t ContentSize (const std::unordered_map< Key, T, Hash > &map)
template<typename T , typename Hash >
size_t ContentSize (const std::unordered_set< T, Hash > &set)
int GetNumDigits (uint32_t value)
StringBuilder & operator<< (StringBuilder &sb, const char *str)
StringBuilder & operator<< (StringBuilder &sb, char c)
StringBuilder & operator<< (StringBuilder &sb, const std::string &s)
StringBuilder & operator<< (StringBuilder &sb, std::string_view s)
StringBuilder & operator<< (StringBuilder &sb, uint32_t n)
StringBuilder & operator<< (StringBuilder &sb, int value)
std::ostream & operator<< (std::ostream &out, StructTypeBase type)
V8_EXPORT_PRIVATE void BuildTSGraph (compiler::turboshaft::PipelineData *data, AccountingAllocator *allocator, CompilationEnv *env, WasmDetectedFeatures *detected, Graph &graph, const FunctionBody &func_body, const WireBytesStorage *wire_bytes, std::unique_ptr< AssumptionsJournal > *assumptions, ZoneVector< WasmInliningPosition > *inlining_positions, int func_index)
void BuildWasmWrapper (compiler::turboshaft::PipelineData *data, AccountingAllocator *allocator, compiler::turboshaft::Graph &graph, const wasm::CanonicalSig *sig, WrapperCompilationInfo)
std::optional< wasm::ValueKind > WasmReturnTypeFromSignature (const CanonicalSig *wasm_signature)
bool EquivalentNumericSig (const CanonicalSig *a, const FunctionSig *b)
const wasm::FunctionSig * GetI32Sig (Zone *zone, const wasm::FunctionSig *sig)
ASSERT_TRIVIALLY_COPYABLE (ModuleTypeIndex)
ASSERT_TRIVIALLY_COPYABLE (CanonicalTypeIndex)
std::ostream & operator<< (std::ostream &oss, TypeIndex index)
constexpr bool IsNullKind (GenericKind kind)
ASSERT_TRIVIALLY_COPYABLE (ValueTypeBase)
ASSERT_TRIVIALLY_COPYABLE (ValueType)
ASSERT_TRIVIALLY_COPYABLE (CanonicalValueType)
constexpr bool is_reference (ValueKind kind)
constexpr bool is_object_reference (ValueKind kind)
constexpr int value_kind_size_log2 (ValueKind kind)
constexpr int value_kind_size (ValueKind kind)
constexpr int value_kind_full_size (ValueKind kind)
constexpr const char * name (ValueKind kind)
std::ostream & operator<< (std::ostream &oss, ValueKind kind)
constexpr MachineType machine_type (ValueKind kind)
constexpr bool is_packed (ValueKind kind)
constexpr ValueKind unpacked (ValueKind kind)
std::ostream & operator<< (std::ostream &oss, ValueType type)
const char * GetWasmCodeKindAsString (WasmCode::Kind kind)
WasmCode::Kind GetCodeKind (const WasmCompilationResult &result)
DEFINE_LAZY_LEAKY_OBJECT_GETTER (WasmCodePointerTable, GetProcessWideWasmCodePointerTable) std
V8_EXPORT_PRIVATE WasmCodePointerTable * GetProcessWideWasmCodePointerTable ()
StringBuilder & operator<< (StringBuilder &sb, Indentation indentation)
StringBuilder & operator<< (StringBuilder &sb, uint64_t n)
StringBuilder & operator<< (StringBuilder &sb, ModuleTypeIndex index)
V8_EXPORT_PRIVATE void PrintSignatureOneLine (StringBuilder &out, const FunctionSig *sig, uint32_t func_index, NamesProvider *names, bool param_names, IndexAsComment indices_as_comments=NamesProvider::kDontPrintIndex)
V8_EXPORT_PRIVATE void PrintStringAsJSON (StringBuilder &out, const uint8_t *start, WireBytesRef ref)
std::unique_ptr< OffsetsProvider > AllocateOffsetsProvider ()
void Disassemble (const WasmModule *module, ModuleWireBytes wire_bytes, NamesProvider *names, v8::debug::DisassemblyCollector *collector, std::vector< int > *function_body_offsets)
void Disassemble (base::Vector< const uint8_t > wire_bytes, v8::debug::DisassemblyCollector *collector, std::vector< int > *function_body_offsets)
void DisassembleFunctionImpl (const WasmModule *module, int func_index, base::Vector< const uint8_t > function_body, ModuleWireBytes module_bytes, NamesProvider *names, std::ostream &os, std::vector< uint32_t > *offsets)
void DisassembleFunction (const WasmModule *module, int func_index, base::Vector< const uint8_t > wire_bytes, NamesProvider *names, std::ostream &os)
void DisassembleFunction (const WasmModule *module, int func_index, base::Vector< const uint8_t > function_body, base::Vector< const uint8_t > maybe_wire_bytes, uint32_t function_body_offset, std::ostream &os, std::vector< uint32_t > *offsets)
uint32_t GetDefaultAlignment (WasmOpcode opcode)
void PrintStringRaw (StringBuilder &out, const uint8_t *start, const uint8_t *end)
WasmEngine * GetWasmEngine ()
WasmCodeManager * GetWasmCodeManager ()
WasmImportWrapperCache * GetWasmImportWrapperCache ()
CanonicalTypeNamesProvider * GetCanonicalTypeNamesProvider ()
uint32_t max_mem32_pages ()
uint32_t max_mem64_pages ()
uint32_t max_table_size ()
uint32_t max_table_init_entries ()
size_t max_module_size ()
void f32_trunc_wrapper (Address data)
void f32_floor_wrapper (Address data)
void f32_ceil_wrapper (Address data)
void f32_nearest_int_wrapper (Address data)
void f64_trunc_wrapper (Address data)
void f64_floor_wrapper (Address data)
void f64_ceil_wrapper (Address data)
void f64_nearest_int_wrapper (Address data)
void int64_to_float32_wrapper (Address data)
void uint64_to_float32_wrapper (Address data)
void int64_to_float64_wrapper (Address data)
void uint64_to_float64_wrapper (Address data)
int32_t float32_to_int64_wrapper (Address data)
int32_t float32_to_uint64_wrapper (Address data)
int32_t float64_to_int64_wrapper (Address data)
int32_t float64_to_uint64_wrapper (Address data)
void float32_to_int64_sat_wrapper (Address data)
void float32_to_uint64_sat_wrapper (Address data)
void float64_to_int64_sat_wrapper (Address data)
void float64_to_uint64_sat_wrapper (Address data)
void float16_to_float32_wrapper (Address data)
void float32_to_float16_wrapper (Address data)
int32_t int64_div_wrapper (Address data)
int32_t int64_mod_wrapper (Address data)
int32_t uint64_div_wrapper (Address data)
int32_t uint64_mod_wrapper (Address data)
uint32_t word32_rol_wrapper (uint32_t input, uint32_t shift)
uint32_t word32_ror_wrapper (uint32_t input, uint32_t shift)
uint64_t word64_rol_wrapper (uint64_t input, uint32_t shift)
uint64_t word64_ror_wrapper (uint64_t input, uint32_t shift)
void float64_pow_wrapper (Address data)
template<typename T , T(*)(T) float_round_op>
void simd_float_round_wrapper (Address data)
void f64x2_ceil_wrapper (Address data)
void f64x2_floor_wrapper (Address data)
void f64x2_trunc_wrapper (Address data)
void f64x2_nearest_int_wrapper (Address data)
void f32x4_ceil_wrapper (Address data)
void f32x4_floor_wrapper (Address data)
void f32x4_trunc_wrapper (Address data)
void f32x4_nearest_int_wrapper (Address data)
Float16 f16_abs (Float16 a)
void f16x8_abs_wrapper (Address data)
Float16 f16_neg (Float16 a)
void f16x8_neg_wrapper (Address data)
Float16 f16_sqrt (Float16 a)
void f16x8_sqrt_wrapper (Address data)
Float16 f16_ceil (Float16 a)
void f16x8_ceil_wrapper (Address data)
Float16 f16_floor (Float16 a)
void f16x8_floor_wrapper (Address data)
Float16 f16_trunc (Float16 a)
void f16x8_trunc_wrapper (Address data)
Float16 f16_nearest_int (Float16 a)
void f16x8_nearest_int_wrapper (Address data)
template<typename R , R(*)(Float16, Float16) float_bin_op>
void simd_float16_bin_wrapper (Address data)
int16_t f16_eq (Float16 a, Float16 b)
void f16x8_eq_wrapper (Address data)
int16_t f16_ne (Float16 a, Float16 b)
void f16x8_ne_wrapper (Address data)
int16_t f16_lt (Float16 a, Float16 b)
void f16x8_lt_wrapper (Address data)
int16_t f16_le (Float16 a, Float16 b)
void f16x8_le_wrapper (Address data)
Float16 f16_add (Float16 a, Float16 b)
void f16x8_add_wrapper (Address data)
Float16 f16_sub (Float16 a, Float16 b)
void f16x8_sub_wrapper (Address data)
Float16 f16_mul (Float16 a, Float16 b)
void f16x8_mul_wrapper (Address data)
Float16 f16_div (Float16 a, Float16 b)
void f16x8_div_wrapper (Address data)
Float16 f16_min (Float16 a, Float16 b)
void f16x8_min_wrapper (Address data)
Float16 f16_max (Float16 a, Float16 b)
void f16x8_max_wrapper (Address data)
Float16 f16_pmin (Float16 a, Float16 b)
void f16x8_pmin_wrapper (Address data)
Float16 f16_pmax (Float16 a, Float16 b)
void f16x8_pmax_wrapper (Address data)
template<typename T , typename R , R(*)(T) float_un_op>
void simd_float_un_wrapper (Address data)
int16_t ConvertToIntS (Float16 val)
uint16_t ConvertToIntU (Float16 val)
void i16x8_sconvert_f16x8_wrapper (Address data)
void i16x8_uconvert_f16x8_wrapper (Address data)
Float16 ConvertToF16S (int16_t val)
void f16x8_sconvert_i16x8_wrapper (Address data)
Float16 ConvertToF16U (uint16_t val)
void f16x8_uconvert_i16x8_wrapper (Address data)
void f32x4_promote_low_f16x8_wrapper (Address data)
void f16x8_demote_f32x4_zero_wrapper (Address data)
void f16x8_demote_f64x2_zero_wrapper (Address data)
template<float(*)(float, float, float) float_fma_op>
void simd_float16_fma_wrapper (Address data)
float Qfma (float a, float b, float c)
void f16x8_qfma_wrapper (Address data)
float Qfms (float a, float b, float c)
void f16x8_qfms_wrapper (Address data)
int32_t memory_init_wrapper (Address trusted_data_addr, uint32_t mem_index, uintptr_t dst, uint32_t src, uint32_t seg_index, uint32_t size)
int32_t memory_copy_wrapper (Address trusted_data_addr, uint32_t dst_mem_index, uint32_t src_mem_index, uintptr_t dst, uintptr_t src, uintptr_t size)
int32_t memory_fill_wrapper (Address trusted_data_addr, uint32_t mem_index, uintptr_t dst, uint8_t value, uintptr_t size)
void array_copy_wrapper (Address raw_dst_array, uint32_t dst_index, Address raw_src_array, uint32_t src_index, uint32_t length)
void array_fill_wrapper (Address raw_array, uint32_t index, uint32_t length, uint32_t emit_write_barrier, uint32_t raw_type, Address initial_value_addr)
double flat_string_to_f64 (Address string_address)
void switch_stacks (Isolate *isolate, wasm::StackMemory *from)
void return_switch (Isolate *isolate, wasm::StackMemory *from)
intptr_t switch_to_the_central_stack (Isolate *isolate, uintptr_t current_sp)
void switch_from_the_central_stack (Isolate *isolate)
intptr_t switch_to_the_central_stack_for_js (Isolate *isolate, Address fp)
void switch_from_the_central_stack_for_js (Isolate *isolate)
Address grow_stack (Isolate *isolate, void *current_sp, size_t frame_size, size_t gap, Address current_fp)
Address shrink_stack (Isolate *isolate)
Address load_old_fp (Isolate *isolate)
constexpr const char * name (WasmEnabledFeature feature)
std::ostream & operator<< (std::ostream &os, WasmEnabledFeature feature)
constexpr const char * name (WasmDetectedFeature feature)
std::ostream & operator<< (std::ostream &os, WasmDetectedFeature feature)
std::ostream & operator<< (std::ostream &os, CompileTimeImport imp)
ASSERT_TRIVIALLY_COPYABLE (WasmInitExpr)
std::unique_ptr< WasmStreaming > StartStreamingForTesting (Isolate *isolate, std::shared_ptr< wasm::CompilationResultResolver > resolver)
uint64_t max_mem32_bytes ()
uint64_t max_mem64_bytes ()
void UpdateComputedInformation (WasmMemory *memory, ModuleOrigin origin)
int GetWasmFunctionOffset (const WasmModule *module, uint32_t func_index)
int GetNearestWasmFunction (const WasmModule *module, uint32_t byte_offset)
int GetContainingWasmFunction (const WasmModule *module, uint32_t byte_offset)
int GetSubtypingDepth (const WasmModule *module, ModuleTypeIndex type_index)
std::ostream & operator<< (std::ostream &os, const WasmFunctionName &name)
bool IsWasmCodegenAllowed (Isolate *isolate, DirectHandle< NativeContext > context)
DirectHandle< String > ErrorStringForCodegen (Isolate *isolate, DirectHandle< Context > context)
DirectHandle< JSObject > GetTypeForFunction (Isolate *isolate, const FunctionSig *sig, bool for_exception)
DirectHandle< JSObject > GetTypeForGlobal (Isolate *isolate, bool is_mutable, ValueType type)
DirectHandle< JSObject > GetTypeForMemory (Isolate *isolate, uint32_t min_size, std::optional< uint64_t > max_size, bool shared, AddressType address_type)
DirectHandle< JSObject > GetTypeForTable (Isolate *isolate, ValueType type, uint32_t min_size, std::optional< uint64_t > max_size, AddressType address_type)
DirectHandle< JSArray > GetImports (Isolate *isolate, DirectHandle< WasmModuleObject > module_object)
DirectHandle< JSArray > GetExports (Isolate *isolate, DirectHandle< WasmModuleObject > module_object)
DirectHandle< JSArray > GetCustomSections (Isolate *isolate, DirectHandle< WasmModuleObject > module_object, DirectHandle< String > name, ErrorThrower *thrower)
int GetSourcePosition (const WasmModule *module, uint32_t func_index, uint32_t byte_offset, bool is_at_number_conversion)
size_t PrintSignature (base::Vector< char > buffer, const CanonicalSig *sig, char delimiter)
int JumpTableOffset (const WasmModule *module, int func_index)
size_t GetWireBytesHash (base::Vector< const uint8_t > wire_bytes)
int NumFeedbackSlots (const WasmModule *module, int func_index)
constexpr const char * AddressTypeToStr (AddressType address_type)
std::ostream & operator<< (std::ostream &os, AddressType address_type)
bool is_asmjs_module (const WasmModule *module)
ASSERT_TRIVIALLY_COPYABLE (ModuleWireBytes)
int declared_function_index (const WasmModule *module, int func_index)
MaybeDirectHandle< Object > JSToWasmObject (Isolate *isolate, DirectHandle< Object > value, CanonicalValueType expected, const char **error_message)
MaybeDirectHandle< Object > JSToWasmObject (Isolate *isolate, const WasmModule *module, DirectHandle< Object > value, ValueType expected, const char **error_message)
DirectHandle< Object > WasmToJSObject (Isolate *isolate, DirectHandle< Object > value)
std::ostream & operator<< (std::ostream &os, const FunctionSig &sig)
bool IsJSCompatibleSignature (const CanonicalSig *sig)
bool IsSupportedVersion (base::Vector< const uint8_t > header, WasmEnabledFeatures enabled_features)
MaybeDirectHandle< WasmModuleObject > DeserializeNativeModule (Isolate *isolate, base::Vector< const uint8_t > data, base::Vector< const uint8_t > wire_bytes_vec, const CompileTimeImports &compile_imports, base::Vector< const char > source_url)
bool ValidSubtypeDefinition (ModuleTypeIndex subtype_index, ModuleTypeIndex supertype_index, const WasmModule *module)
V8_NOINLINE V8_EXPORT_PRIVATE bool IsSubtypeOfImpl (HeapType subtype, HeapType supertype, const WasmModule *sub_module, const WasmModule *super_module)
V8_NOINLINE V8_EXPORT_PRIVATE bool IsSubtypeOfImpl (ValueType subtype, ValueType supertype, const WasmModule *sub_module, const WasmModule *super_module)
V8_NOINLINE V8_EXPORT_PRIVATE bool IsSubtypeOfImpl (CanonicalValueType subtype, CanonicalValueType supertype)
V8_NOINLINE bool EquivalentTypes (ValueType type1, ValueType type2, const WasmModule *module)
V8_NOINLINE bool EquivalentTypes (ValueType type1, ValueType type2, const WasmModule *module1, const WasmModule *module2)
V8_EXPORT_PRIVATE TypeInModule Union (ValueType type1, ValueType type2, const WasmModule *module)
TypeInModule Intersection (ValueType type1, ValueType type2, const WasmModule *module)
ValueType ToNullSentinel (TypeInModule type)
bool IsSameTypeHierarchy (HeapType type1, HeapType type2, const WasmModule *module)
bool IsSubtypeOf (ValueType subtype, ValueType supertype, const WasmModule *sub_module, const WasmModule *super_module)
bool IsSubtypeOf (ValueType subtype, ValueType supertype, const WasmModule *module)
bool IsSubtypeOf (CanonicalValueType subtype, CanonicalValueType supertype)
bool IsHeapSubtypeOf (HeapType subtype, HeapType supertype, const WasmModule *module)
bool HeapTypesUnrelated (HeapType heap1, HeapType heap2, const WasmModule *module)
std::ostream & operator<< (std::ostream &oss, TypeInModule type)
const char * ExecutionTierToString (ExecutionTier tier)
ASSERT_TRIVIALLY_COPYABLE (DirectHandle< Object >)
const char * WellKnownImportName (WellKnownImport wki)
bool IsCompileTimeImport (WellKnownImport wki)
Variables
constexpr RegList kLiftoffAssemblerGpCacheRegs = RegList::FromBits(0xff)
constexpr DoubleRegList kLiftoffAssemblerFpCacheRegs
constexpr auto kRegister = VarState::kRegister
constexpr auto kIntConst = VarState::kIntConst
constexpr auto kStack = VarState::kStack
static constexpr bool kNeedI64RegPair = kSystemPointerSize == 4
static constexpr bool kNeedS128RegPair = kFPAliasing == AliasingKind::kCombine
static constexpr int kMaxGpRegCode = kLiftoffAssemblerGpCacheRegs.last().code()
static constexpr int kMaxFpRegCode = kLiftoffAssemblerFpCacheRegs.last().code()
static constexpr int kAfterMaxLiftoffGpRegCode = kMaxGpRegCode + 1
static constexpr int kAfterMaxLiftoffFpRegCode
static constexpr int kAfterMaxLiftoffRegCode = kAfterMaxLiftoffFpRegCode
static constexpr int kBitsPerLiftoffRegCode
static constexpr int kBitsPerGpRegCode
static constexpr int kBitsPerFpRegCode
static constexpr int kBitsPerRegPair
static constexpr LiftoffRegList kGpCacheRegList
static constexpr LiftoffRegList kFpCacheRegList
constexpr bool is_be = false
constexpr int stack_bias = 0
static constexpr size_t kMaxCanonicalTypes = kV8MaxWasmTypes
constexpr bool kPartialOOBWritesAreNoops = true
const std::pair< uint32_t, uint32_t > invalid_instruction_trace = {0, 0}
constexpr Decoder::NoValidationTag kNoValidate
constexpr uint32_t kFloat32SignBitMask = uint32_t{1} << 31
constexpr uint64_t kFloat64SignBitMask = uint64_t{1} << 63
InstructionHandler s_unwind_code = InstructionHandler::k_s2s_Unwind
PWasmOp * kInstructionTable [kInstructionTableSize]
static const size_t kOperatorModeCount = 4
static const RegModeTransform kRegModes [256]
static const size_t kSlotSize = sizeof(int32_t)
static const ptrdiff_t kCodeOffsetSize = sizeof(int32_t)
constexpr uint32_t kBranchOnCastDataTargetTypeBitSize = 30
static constexpr uint32_t kInstructionTableSize = 4096
static constexpr uint32_t kInstructionTableMask = kInstructionTableSize - 1
constexpr size_t kPaddedVarInt32Size = 5
constexpr size_t kMaxVarInt32Size = 5
constexpr size_t kMaxVarInt64Size = 10
constexpr char kNameString [] = `name`
constexpr char kSourceMappingURLString [] = `sourceMappingURL`
constexpr char kInstTraceString [] = `metadata.code.trace_inst`
constexpr char kCompilationHintsString [] = `compilationHints`
constexpr char kBranchHintsString [] = `metadata.code.branch_hint`
constexpr char kDebugInfoString [] = `.debug_info`
constexpr char kExternalDebugInfoString [] = `external_debug_info`
constexpr char kBuildIdString [] = `build_id`
constexpr char kDescriptorsString [] = `experimental-descriptors`
constexpr ImportCallKind kDefaultImportCallKind = ImportCallKind::kJSFunction
constexpr uint8_t kFunctionExecutedBit = 1 << 0
constexpr uint8_t kFunctionTieredUpBit = 1 << 1
constexpr int kStackSpOffset
constexpr int kStackFpOffset
constexpr int kStackPcOffset
constexpr int kStackLimitOffset
constexpr int kStackParentOffset
constexpr int kStackStateOffset
constexpr int kMaxValueTypeSize = 16
constexpr ModuleTypeIndex kNoSuperType = ModuleTypeIndex::Invalid()
constexpr ModuleTypeIndex kNoType = ModuleTypeIndex::Invalid()
static constexpr bool kNotShared = false
constexpr IndependentValueType kWasmI32 {NumericKind::kI32}
constexpr IndependentValueType kWasmI64 {NumericKind::kI64}
constexpr IndependentValueType kWasmF32 {NumericKind::kF32}
constexpr IndependentValueType kWasmF64 {NumericKind::kF64}
constexpr IndependentValueType kWasmS128 {NumericKind::kS128}
constexpr IndependentValueType kWasmI8 {NumericKind::kI8}
constexpr IndependentValueType kWasmI16 {NumericKind::kI16}
constexpr IndependentValueType kWasmF16 {NumericKind::kF16}
constexpr IndependentHeapType kWasmVoid {GenericKind::kVoid, kNonNullable}
constexpr IndependentHeapType kWasmTop {GenericKind::kTop}
constexpr IndependentHeapType kWasmBottom {GenericKind::kBottom, kNonNullable}
constexpr IndependentHeapType kWasmFuncRef {GenericKind::kFunc}
constexpr IndependentHeapType kWasmAnyRef {GenericKind::kAny}
constexpr IndependentHeapType kWasmSharedAnyRef
constexpr IndependentHeapType kWasmExternRef {GenericKind::kExtern}
constexpr IndependentHeapType kWasmRefExtern
constexpr IndependentHeapType kWasmExnRef {GenericKind::kExn}
constexpr IndependentHeapType kWasmEqRef {GenericKind::kEq}
constexpr IndependentHeapType kWasmI31Ref {GenericKind::kI31}
constexpr IndependentHeapType kWasmRefI31 {GenericKind::kI31, kNonNullable}
constexpr IndependentHeapType kWasmStructRef {GenericKind::kStruct}
constexpr IndependentHeapType kWasmArrayRef {GenericKind::kArray}
constexpr IndependentHeapType kWasmStringRef {GenericKind::kString}
constexpr IndependentHeapType kWasmRefString
constexpr IndependentHeapType kWasmRefNullExternString
constexpr IndependentHeapType kWasmRefExternString
constexpr IndependentHeapType kWasmStringViewWtf8
constexpr IndependentHeapType kWasmStringViewWtf16
constexpr IndependentHeapType kWasmStringViewIter
constexpr IndependentHeapType kWasmNullRef {GenericKind::kNone}
constexpr IndependentHeapType kWasmNullExternRef {GenericKind::kNoExtern}
constexpr IndependentHeapType kWasmNullExnRef {GenericKind::kNoExn}
constexpr IndependentHeapType kWasmNullFuncRef {GenericKind::kNoFunc}
constexpr IndependentHeapType kWasmContRef {GenericKind::kCont}
constexpr IndependentHeapType kWasmNullContRef {GenericKind::kNoCont}
constexpr WasmCodePointer kInvalidWasmCodePointer
constexpr uint32_t kWasmMagic = 0x6d736100
constexpr uint32_t kWasmVersion = 0x01
constexpr uint8_t kSharedFlagCode = 0x65
constexpr uint8_t kWasmFunctionTypeCode = 0x60
constexpr uint8_t kWasmStructTypeCode = 0x5f
constexpr uint8_t kWasmArrayTypeCode = 0x5e
constexpr uint8_t kWasmContTypeCode = 0x5d
constexpr uint8_t kWasmSubtypeCode = 0x50
constexpr uint8_t kWasmSubtypeFinalCode = 0x4f
constexpr uint8_t kWasmRecursiveTypeGroupCode = 0x4e
constexpr uint8_t kWasmDescriptorCode = 0x4d
constexpr uint8_t kWasmDescribesCode = 0x4c
constexpr uint8_t kDefaultCompilationHint = 0x0
constexpr uint8_t kNoCompilationHint = kMaxUInt8
constexpr size_t kWasmPageSize = 0x10000
constexpr uint32_t kWasmPageSizeLog2 = 16
constexpr WasmCodePosition kNoCodePosition = -1
constexpr uint32_t kExceptionAttribute = 0
constexpr int kAnonymousFuncIndex = -1
constexpr uint32_t kInvalidCanonicalIndex = static_cast<uint32_t>(-1)
constexpr uint32_t kGenericWrapperBudget = 1000
constexpr uint32_t kMinimumSupertypeArraySize = 3
constexpr int kMaxPolymorphism = 4
constexpr int kMaxStructFieldIndexForImplicitNullCheck = 4000
constexpr bool kSkipFunctionTypesInTypeSection = true
constexpr IndexAsComment kIndicesAsComments = NamesProvider::kIndexAsComment
constexpr bool kSkipDataSegmentNames = true
static constexpr char kHexChars [] = `0123456789abcdef`
static constexpr char kUpperHexChars [] = `0123456789ABCDEF`
constexpr size_t kSpecMaxMemory32Pages = 65'536
constexpr size_t kSpecMaxMemory64Pages = 262'144
constexpr size_t kV8MaxWasmTypes = 1'000'000
constexpr size_t kV8MaxWasmDefinedFunctions = 1'000'000
constexpr size_t kV8MaxWasmImports = 1'000'000
constexpr size_t kV8MaxWasmExports = 1'000'000
constexpr size_t kV8MaxWasmGlobals = 1'000'000
constexpr size_t kV8MaxWasmTags = 1'000'000
constexpr size_t kV8MaxWasmExceptionTypes = 1'000'000
constexpr size_t kV8MaxWasmDataSegments = 100'000
constexpr size_t kV8MaxWasmMemory32Pages
constexpr size_t kV8MaxWasmMemory64Pages
constexpr size_t kV8MaxWasmStringSize = 100'000
constexpr size_t kV8MaxWasmModuleSize = 1024 * 1024 * 1024
constexpr size_t kV8MaxWasmFunctionSize = 7'654'321
constexpr size_t kV8MaxWasmFunctionLocals = 50'000
constexpr size_t kV8MaxWasmFunctionParams = 1'000
constexpr size_t kV8MaxWasmFunctionReturns = 1'000
constexpr size_t kV8MaxWasmFunctionBrTableSize = 65'520
constexpr size_t kV8MaxWasmTableSize = 10'000'000
constexpr size_t kV8MaxWasmTableInitEntries = 10'000'000
constexpr size_t kV8MaxWasmTables = 100'000
constexpr size_t kV8MaxWasmMemories = 100'000
constexpr size_t kV8MaxWasmStructFields = 10'000
constexpr uint32_t kV8MaxRttSubtypingDepth = 63
constexpr size_t kV8MaxWasmArrayNewFixedLength = 10'000
constexpr size_t kV8MaxWasmStringLiterals = 1'000'000
constexpr uint64_t kWasmMaxHeapOffset
constexpr size_t kV8MaxWasmTotalFunctions
constexpr size_t kMaxMemory64Size
constexpr Register kGpParamRegisters [] = {}
constexpr Register kGpReturnRegisters [] = {}
constexpr DoubleRegister kFpParamRegisters [] = {}
constexpr DoubleRegister kFpReturnRegisters [] = {}
constexpr bool kIsFpAlwaysDouble = false
constexpr bool kIsBigEndian = false
constexpr bool kIsBigEndianOnSim = false
constexpr int kWasmInstanceDataParameterIndex = 0
static constexpr int kConstructorFunctionContextSlot
static constexpr int kConstructorFunctionContextLength
Typedef Documentation
Address
using v8::internal::wasm::Address = typedef uintptr_t
Definition at line 25 of file wasm-external-refs.h.
AsmJsOffsetsResult
using v8::internal::wasm::AsmJsOffsetsResult = typedef Result<AsmJsOffsets>
Definition at line 57 of file module-decoder.h.
BranchHintInfo
using v8::internal::wasm::BranchHintInfo = typedef std::unordered_map<uint32_t, BranchHintMap>
Definition at line 36 of file branch-hint-map.h.
CodeOffset
using v8::internal::wasm::CodeOffset = typedef size_t
Definition at line 74 of file wasm-interpreter.h.
CompileTimeImportFlags
using v8::internal::wasm::CompileTimeImportFlags = typedef base::EnumSet<CompileTimeImport, int>
Definition at line 148 of file wasm-features.h.
DecodeResult
using v8::internal::wasm::DecodeResult = typedef VoidResult
Definition at line 39 of file decoder.h.
EffectHandlerTableImmediate
using v8::internal::wasm::EffectHandlerTableImmediate = typedef BranchTableImmediate
Definition at line 999 of file function-body-decoder-impl.h.
fp0
typedef uint32_t WasmInterpreterRuntime int64_t double v8::internal::wasm::fp0
Definition at line 675 of file wasm-interpreter.h.
FunctionOffsets
using v8::internal::wasm::FunctionOffsets = typedef std::vector<std::pair<int, int> >
Definition at line 41 of file module-decoder.h.
FunctionOffsetsResult
using v8::internal::wasm::FunctionOffsetsResult = typedef Result<FunctionOffsets>
Definition at line 42 of file module-decoder.h.
FunctionResult
using v8::internal::wasm::FunctionResult = typedef Result<std::unique_ptr<WasmFunction> >
Definition at line 40 of file module-decoder.h.
FunctionSig
using v8::internal::wasm::FunctionSig = typedef Signature<ValueType>
Definition at line 1296 of file value-type.h.
IndexAsComment
using v8::internal::wasm::IndexAsComment = typedef NamesProvider::IndexAsComment
Definition at line 25 of file wasm-disassembler-impl.h.
IndirectNameMap
using v8::internal::wasm::IndirectNameMap = typedef AdaptiveMap<AdaptiveMap<WireBytesRef> >
Definition at line 375 of file wasm-module.h.
ModuleResult
using v8::internal::wasm::ModuleResult = typedef Result<std::shared_ptr<WasmModule> >
Definition at line 39 of file module-decoder.h.
NameMap
using v8::internal::wasm::NameMap = typedef AdaptiveMap<WireBytesRef>
Definition at line 374 of file wasm-module.h.
pc_t
using v8::internal::wasm::pc_t = typedef size_t
Definition at line 73 of file wasm-interpreter.h.
r0
typedef uint32_t WasmInterpreterRuntime int64_t v8::internal::wasm::r0
Definition at line 675 of file wasm-interpreter.h.
sp
typedef uint32_t* v8::internal::wasm::sp
Definition at line 673 of file wasm-interpreter.h.
TryTableImmediate
using v8::internal::wasm::TryTableImmediate = typedef BranchTableImmediate
Definition at line 902 of file function-body-decoder-impl.h.
TSBlock
typedef compiler::turboshaft::Block v8::internal::wasm::TSBlock
Definition at line 44 of file turboshaft-graph-interface.cc.
TypeChecker
using v8::internal::wasm::TypeChecker = typedef bool (*)(const WasmRef obj)
Definition at line 2654 of file wasm-interpreter-runtime.cc.
ValueKindSig
using v8::internal::wasm::ValueKindSig = typedef LiftoffAssembler::ValueKindSig
Definition at line 26 of file liftoff-assembler.cc.
ValueOrError
using v8::internal::wasm::ValueOrError = typedef std::variant<WasmValue, MessageTemplate>
Definition at line 118 of file constant-expression.h.
VarState
typedef LiftoffAssembler::VarState v8::internal::wasm::VarState
Definition at line 25 of file liftoff-assembler.cc.
VoidResult
using v8::internal::wasm::VoidResult = typedef Result<std::nullptr_t>
Definition at line 187 of file wasm-result.h.
wasm_runtime
typedef uint32_t WasmInterpreterRuntime* v8::internal::wasm::wasm_runtime
Definition at line 674 of file wasm-interpreter.h.
WasmCodePosition
using v8::internal::wasm::WasmCodePosition = typedef int
Definition at line 184 of file wasm-constants.h.
WasmName
typedef base::Vector< const char > v8::internal::wasm::WasmName
Definition at line 30 of file code-events.h.
WasmRef
using v8::internal::wasm::WasmRef = typedef DirectHandle<Object>
Definition at line 75 of file wasm-interpreter.h.
WasmTagSig
typedef FunctionSig v8::internal::wasm::WasmTagSig
Definition at line 112 of file wasm-module.h.
Enumeration Type Documentation
AddressType
enum v8::internal::wasm::AddressType : uint8_t [strong]
Enumerator
kI32
kI64
Definition at line 49 of file wasm-module.h.
: uint8_t { kI32, kI64 };
BoundsCheckedHandlersCounter
enum v8::internal::wasm::BoundsCheckedHandlersCounter
Enumerator
kTotalItems
Definition at line 539 of file wasm-interpreter.cc.
                                  {
#define ITEM_ENUM_DEFINE(name) name##counter,
  FOREACH_LOAD_STORE_INSTR_HANDLER(ITEM_ENUM_DEFINE)
#undef ITEM_ENUM_DEFINE
      kTotalItems
};
BoundsCheckStrategy
enum v8::internal::wasm::BoundsCheckStrategy : int8_t
Enumerator
kTrapHandler
kExplicitBoundsChecks
kNoBoundsChecks
Definition at line 130 of file wasm-module.h.
                         : int8_t {
  // Emit protected instructions, use the trap handler for OOB detection.
  kTrapHandler,
  // Emit explicit bounds checks.
  kExplicitBoundsChecks,
  // Emit no bounds checks at all (for testing only).
  kNoBoundsChecks
};
CallOrigin
enum v8::internal::wasm::CallOrigin [strong]
Enumerator
kCalledFromWasm
kCalledFromJS
Definition at line 65 of file wasm-compiler.h.
{ kCalledFromWasm, kCalledFromJS };
CatchKind
enum v8::internal::wasm::CatchKind : uint8_t
Enumerator
kCatch
kCatchRef
kCatchAll
kCatchAllRef
kLastCatchKind
Definition at line 165 of file wasm-constants.h.
               : uint8_t {
  kCatch = 0x0,
  kCatchRef = 0x1,
  kCatchAll = 0x2,
  kCatchAllRef = 0x3,
  kLastCatchKind = kCatchAllRef,
};
CompilationEvent
enum v8::internal::wasm::CompilationEvent : uint8_t [strong]
Enumerator
kFinishedBaselineCompilation
kFinishedCompilationChunk
kFailedCompilation
Definition at line 97 of file compilation-environment.h.
                            : uint8_t {
  kFinishedBaselineCompilation,
  kFinishedCompilationChunk,
  kFailedCompilation,
};
CompileTimeImport
enum v8::internal::wasm::CompileTimeImport [strong]
Enumerator
kJsString
kStringConstants
kTextEncoder
kTextDecoder
kDisableDenormalFloats
Definition at line 135 of file wasm-features.h.
                             {
  kJsString,
  kStringConstants,
  kTextEncoder,
  kTextDecoder,
  // Not really an import, but needs the same handling as compile-time imports.
  kDisableDenormalFloats,
};
ControlKind
enum v8::internal::wasm::ControlKind : uint8_t
Enumerator
kControlIf
kControlIfElse
kControlBlock
kControlLoop
kControlTry
kControlTryTable
kControlTryCatch
kControlTryCatchAll
Definition at line 1261 of file function-body-decoder-impl.h.
                 : uint8_t {
  kControlIf,
  kControlIfElse,
  kControlBlock,
  kControlLoop,
  kControlTry,
  kControlTryTable,
  kControlTryCatch,
  kControlTryCatchAll,
};
DebugState
enum v8::internal::wasm::DebugState : bool
Enumerator
kNotDebugging
kDebugging
Definition at line 53 of file wasm-tier.h.
: bool { kNotDebugging = false, kDebugging = true };
DecodingMethod
enum v8::internal::wasm::DecodingMethod [strong]
Enumerator
kSync
kAsync
kSyncStream
kAsyncStream
kDeserialize
Definition at line 79 of file module-decoder.h.
                          {
  kSync,
  kAsync,
  kSyncStream,
  kAsyncStream,
  kDeserialize
};
DecodingMode
enum v8::internal::wasm::DecodingMode
Enumerator
kFunctionBody
kConstantExpression
Definition at line 530 of file function-body-decoder-impl.h.
{ kFunctionBody, kConstantExpression };
Exactness
enum v8::internal::wasm::Exactness : bool
Enumerator
kAnySubtype
kExact
Definition at line 104 of file value-type.h.
: bool { kAnySubtype, kExact };
ExecutionTier
enum v8::internal::wasm::ExecutionTier : int8_t [strong]
Enumerator
kNone
kLiftoff
kTurbofan
Definition at line 19 of file wasm-tier.h.
                         : int8_t {
  kNone,
#if V8_ENABLE_DRUMBRAKE
  kInterpreter,
#endif // V8_ENABLE_DRUMBRAKE
  kLiftoff,
  kTurbofan,
};
ExternalCallResult
enum v8::internal::wasm::ExternalCallResult
Enumerator
EXTERNAL_RETURNED
EXTERNAL_EXCEPTION
Definition at line 1055 of file wasm-interpreter.h.
                        {
  // The function was executed and returned normally.
  EXTERNAL_RETURNED,
  // The function was executed, threw an exception.
  EXTERNAL_EXCEPTION
};
ForDebugging
enum v8::internal::wasm::ForDebugging : int8_t
Enumerator
kNotForDebugging
kForDebugging
kWithBreakpoints
kForStepping
Definition at line 46 of file wasm-tier.h.
                  : int8_t {
  kNotForDebugging = 0,
  kForDebugging,
  kWithBreakpoints,
  kForStepping
};
GenericKind
enum v8::internal::wasm::GenericKind : uint32_t [strong]
Enumerator
DEF_ENUM
Definition at line 277 of file value-type.h.
                       : uint32_t {
#define DEF_ENUM(kind, code, extra_bits, ...) \
  k##kind = value_type_impl::PayloadField::encode(\
                static_cast<uint8_t>(StandardType::k##kind)) + \
            (extra_bits),
  FOREACH_GENERIC_TYPE(DEF_ENUM)
#undef DEF_ENUM
};
ImportCallKind
enum v8::internal::wasm::ImportCallKind : uint8_t [strong]
Enumerator
kLinkError
kRuntimeTypeError
kWasmToCapi
kWasmToJSFastApi
kWasmToWasm
kJSFunction
kUseCallBuiltin
Definition at line 43 of file module-instantiate.h.
                          : uint8_t {
  kLinkError, // static Wasm->Wasm type error
  kRuntimeTypeError, // runtime Wasm->JS type error
  kWasmToCapi, // fast Wasm->C-API call
  kWasmToJSFastApi, // fast Wasm->JS Fast API C call
  kWasmToWasm, // fast Wasm->Wasm call
  kJSFunction, // fast Wasm->JS call
  // For everything else, there's the call builtin.
  kUseCallBuiltin
};
ImportExportKindCode
enum v8::internal::wasm::ImportExportKindCode : uint8_t
Enumerator
kExternalFunction
kExternalTable
kExternalMemory
kExternalGlobal
kExternalTag
Definition at line 78 of file wasm-constants.h.
                          : uint8_t {
  kExternalFunction = 0,
  kExternalTable = 1,
  kExternalMemory = 2,
  kExternalGlobal = 3,
  kExternalTag = 4
};
InstrHandlerSize
enum v8::internal::wasm::InstrHandlerSize
Enumerator
Large
Small
Definition at line 1449 of file wasm-interpreter.h.
                      {
  Large = 0, // false
  Small = 1 // true
};
InstructionHandler
enum v8::internal::wasm::InstructionHandler : uint16_t
Enumerator
kInstructionCount
Definition at line 1220 of file wasm-interpreter.h.
                        : uint16_t {
  FOREACH_INSTR_HANDLER(DEFINE_INSTR_HANDLER)
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
      FOREACH_TRACE_INSTR_HANDLER(DEFINE_INSTR_HANDLER)
#endif // V8_ENABLE_DRUMBRAKE_TRACING
          kInstructionCount
};
LiftoffBailoutReason
enum v8::internal::wasm::LiftoffBailoutReason : int8_t
Enumerator
kSuccess
kDecodeError
kUnsupportedArchitecture
kMissingCPUFeature
kComplexOperation
kSimd
kRefTypes
kExceptionHandling
kMultiValue
kTailCall
kAtomics
kBulkMemory
kNonTrappingFloatToInt
kGC
kRelaxedSimd
kOtherReason
kNumBailoutReasons
Definition at line 28 of file liftoff-compiler.h.
                          : int8_t {
  // Nothing actually failed.
  kSuccess = 0,
  // Compilation failed, but not because of Liftoff.
  kDecodeError = 1,
  // Liftoff is not implemented on that architecture.
  kUnsupportedArchitecture = 2,
  // More complex code would be needed because a CPU feature is not present.
  kMissingCPUFeature = 3,
  // Liftoff does not implement a complex (and rare) instruction.
  kComplexOperation = 4,
  // Unimplemented proposals:
  kSimd = 5,
  kRefTypes = 6,
  kExceptionHandling = 7,
  kMultiValue = 8,
  kTailCall = 9,
  kAtomics = 10,
  kBulkMemory = 11,
  kNonTrappingFloatToInt = 12,
  kGC = 13,
  kRelaxedSimd = 14,
  // A little gap, for forward compatibility.
  // Any other reason (use rarely; introduce new reasons if this spikes).
  kOtherReason = 20,
  // Marker:
  kNumBailoutReasons
};
LimitsFlags
enum v8::internal::wasm::LimitsFlags : uint8_t
Enumerator
kNoMaximum
kWithMaximum
kSharedNoMaximum
kSharedWithMaximum
kMemory64NoMaximum
kMemory64WithMaximum
kMemory64SharedNoMaximum
kMemory64SharedWithMaximum
Definition at line 87 of file wasm-constants.h.
                 : uint8_t {
  kNoMaximum = 0x00,
  kWithMaximum = 0x01,
  kSharedNoMaximum = 0x02,
  kSharedWithMaximum = 0x03,
  kMemory64NoMaximum = 0x04,
  kMemory64WithMaximum = 0x05,
  kMemory64SharedNoMaximum = 0x06,
  kMemory64SharedWithMaximum = 0x07
};
LoadOrStore
enum v8::internal::wasm::LoadOrStore : bool [strong]
Enumerator
kLoad
kStore
Definition at line 610 of file liftoff-assembler-arm64-inl.h.
: bool { kLoad, kStore };
LoadTransformationKind
enum v8::internal::wasm::LoadTransformationKind : uint8_t [strong]
Enumerator
kSplat
kExtend
kZeroExtend
Definition at line 48 of file function-body-decoder.h.
: uint8_t { kSplat, kExtend, kZeroExtend };
LocationKindForDeopt
enum v8::internal::wasm::LocationKindForDeopt : uint8_t [strong]
Enumerator
kNone
kEagerDeopt
kInlinedCall
Definition at line 61 of file liftoff-compiler.h.
                                : uint8_t {
  kNone,
  kEagerDeopt, // The location is the point of an eager deopt.
  kInlinedCall, // The loation is an inlined call, not a deopt.
};
ModuleOrigin
enum v8::internal::wasm::ModuleOrigin : uint8_t
Enumerator
kWasmOrigin
kAsmJsSloppyOrigin
kAsmJsStrictOrigin
Definition at line 124 of file wasm-module.h.
                  : uint8_t {
  kWasmOrigin,
  kAsmJsSloppyOrigin,
  kAsmJsStrictOrigin
};
NameSectionKindCode
enum v8::internal::wasm::NameSectionKindCode : uint8_t
Enumerator
kModuleCode
kFunctionCode
kLocalCode
kLabelCode
kTypeCode
kTableCode
kMemoryCode
kGlobalCode
kElementSegmentCode
kDataSegmentCode
kFieldCode
kTagCode
Definition at line 147 of file wasm-constants.h.
                         : uint8_t {
  kModuleCode = 0,
  kFunctionCode = 1,
  kLocalCode = 2,
  // https://github.com/WebAssembly/extended-name-section/
  kLabelCode = 3,
  kTypeCode = 4,
  kTableCode = 5,
  kMemoryCode = 6,
  kGlobalCode = 7,
  kElementSegmentCode = 8,
  kDataSegmentCode = 9,
  // https://github.com/WebAssembly/gc/issues/193
  kFieldCode = 10,
  // https://github.com/WebAssembly/exception-handling/pull/213
  kTagCode = 11,
};
Nullability
enum v8::internal::wasm::Nullability : bool
Enumerator
kNonNullable
kNullable
Definition at line 102 of file value-type.h.
: bool { kNonNullable = false, kNullable = true };
NumericKind
enum v8::internal::wasm::NumericKind : uint32_t [strong]
Enumerator
DEF_ENUM
Definition at line 286 of file value-type.h.
                       : uint32_t {
#define DEF_ENUM(kind, ...) \
  k##kind = value_type_impl::PayloadField::encode(\
                static_cast<uint8_t>(StandardType::k##kind)) + \
            value_type_impl::kNumericExtraBits,
  FOREACH_NUMERIC_VALUE_TYPE(DEF_ENUM)
#undef DEF_ENUM
};
OnResume
enum v8::internal::wasm::OnResume : int [strong]
Enumerator
kContinue
kThrow
Definition at line 102 of file wasm-objects.h.
: int { kContinue, kThrow };
OperatorMode
enum v8::internal::wasm::OperatorMode
Enumerator
kR2R
kR2S
kS2R
kS2S
Definition at line 726 of file wasm-interpreter.h.
{ kR2R = 0, kR2S, kS2R, kS2S };
Promise
enum v8::internal::wasm::Promise : int
Enumerator
kPromise
kNoPromise
kStressSwitch
Definition at line 37 of file module-instantiate.h.
: int { kPromise, kNoPromise, kStressSwitch };
Reachability
enum v8::internal::wasm::Reachability : uint8_t
Enumerator
kReachable
kSpecOnlyReachable
kUnreachable
Definition at line 1272 of file function-body-decoder-impl.h.
                  : uint8_t {
  // reachable code.
  kReachable,
  // reachable code in unreachable block (implies normal validation).
  kSpecOnlyReachable,
  // code unreachable in its own block (implies polymorphic validation).
  kUnreachable
};
RefTypeKind
enum v8::internal::wasm::RefTypeKind : uint8_t [strong]
Enumerator
kOther
kFunction
kStruct
kArray
kCont
kLastValue
Definition at line 214 of file value-type.h.
                       : uint8_t {
  kOther = 0,
  kFunction = 1,
  kStruct = 2,
  kArray = 3,
  kCont = 4,
  kLastValue = kCont,
};
RegClass
enum v8::internal::wasm::RegClass : uint8_t
Enumerator
kGpReg
kFpReg
kGpRegPair
kFpRegPair
kNoReg
Definition at line 22 of file liftoff-register.h.
              : uint8_t {
  kGpReg,
  kFpReg,
  kGpRegPair = kFpReg + 1 + (kNeedS128RegPair && !kNeedI64RegPair),
  kFpRegPair = kFpReg + 1 + kNeedI64RegPair,
  kNoReg = kFpRegPair + kNeedS128RegPair,
  // +------------------+-------------------------------+
  // | | kNeedI64RegPair |
  // +------------------+---------------+---------------+
  // | kNeedS128RegPair | true | false |
  // +------------------+---------------+---------------+
  // | true | 0,1,2,3,4 (a) | 0,1,3,2,3 |
  // | false | 0,1,2,3,3 (b) | 0,1,2,2,2 (c) |
  // +------------------+---------------+---------------+
  // (a) arm
  // (b) ia32
  // (c) x64, arm64
};
RegMode
enum v8::internal::wasm::RegMode [strong]
Enumerator
kNoReg
kI32Reg
kI64Reg
kF32Reg
kF64Reg
kAnyReg
Definition at line 742 of file wasm-interpreter.h.
                   {
  kNoReg, // The instruction handler only gets inputs from stack slots or
           // provide the result into a stack slot.
  kI32Reg, // The instruction handler can be optimized to work with the integer
  kI64Reg, // register 'r0'.
  kF32Reg, // The instruction handler can be optimized to work with the
  kF64Reg, // floating point register 'fp0'.
  kAnyReg, // The instruction handler can be optimized to work either with the
            // integer or fp register; the specific register depends on the
            // type of the type of the value at the top of the stack. This is
            // used for instructions like 'drop', 'select' and 'local.set.
};
RegPairHalf
enum v8::internal::wasm::RegPairHalf : uint8_t
Enumerator
kLowWord
kHighWord
Definition at line 46 of file liftoff-register.h.
: uint8_t { kLowWord = 0, kHighWord = 1 };
SectionCode
enum v8::internal::wasm::SectionCode : int8_t
Enumerator
kUnknownSectionCode
kTypeSectionCode
kImportSectionCode
kFunctionSectionCode
kTableSectionCode
kMemorySectionCode
kGlobalSectionCode
kExportSectionCode
kStartSectionCode
kElementSectionCode
kCodeSectionCode
kDataSectionCode
kDataCountSectionCode
kTagSectionCode
kStringRefSectionCode
kNameSectionCode
kSourceMappingURLSectionCode
kDebugInfoSectionCode
kExternalDebugInfoSectionCode
kBuildIdSectionCode
kInstTraceSectionCode
kCompilationHintsSectionCode
kBranchHintsSectionCode
kDescriptorsSectionCode
kFirstSectionInModule
kLastKnownModuleSection
kFirstUnorderedSection
Definition at line 106 of file wasm-constants.h.
                 : int8_t {
  kUnknownSectionCode = 0, // code for unknown sections
  kTypeSectionCode = 1, // Function signature declarations
  kImportSectionCode = 2, // Import declarations
  kFunctionSectionCode = 3, // Function declarations
  kTableSectionCode = 4, // Indirect function table and others
  kMemorySectionCode = 5, // Memory attributes
  kGlobalSectionCode = 6, // Global declarations
  kExportSectionCode = 7, // Exports
  kStartSectionCode = 8, // Start function declaration
  kElementSectionCode = 9, // Elements section
  kCodeSectionCode = 10, // Function code
  kDataSectionCode = 11, // Data segments
  kDataCountSectionCode = 12, // Number of data segments
  kTagSectionCode = 13, // Tag section
  kStringRefSectionCode = 14, // Stringref literal section
  // The following sections are custom sections, and are identified using a
  // string rather than an integer. Their enumeration values are not guaranteed
  // to be consistent.
  kNameSectionCode, // Name section (encoded as a string)
  kSourceMappingURLSectionCode, // Source Map URL section
  kDebugInfoSectionCode, // DWARF section .debug_info
  kExternalDebugInfoSectionCode, // Section encoding the external symbol path
  kBuildIdSectionCode, // Unique build id to match the symbol file
  kInstTraceSectionCode, // Instruction trace section
  kCompilationHintsSectionCode, // Compilation hints section
  kBranchHintsSectionCode, // Branch hints section
  kDescriptorsSectionCode, // Descriptors section
  // Helper values
  kFirstSectionInModule = kTypeSectionCode,
  kLastKnownModuleSection = kStringRefSectionCode,
  kFirstUnorderedSection = kDataCountSectionCode,
};
SegmentFlags
enum v8::internal::wasm::SegmentFlags : uint8_t
Enumerator
kActiveNoIndex
kPassive
kActiveWithIndex
Definition at line 99 of file wasm-constants.h.
                  : uint8_t {
  kActiveNoIndex = 0, // Active segment with a memory/table index of zero.
  kPassive = 1, // Passive segment.
  kActiveWithIndex = 2, // Active segment with a given memory/table index.
};
StandardType
enum v8::internal::wasm::StandardType : uint8_t [strong]
Enumerator
DEF_ENUM
FOREACH_GENERIC_TYPE
Definition at line 267 of file value-type.h.
                        : uint8_t {
#define DEF_ENUM(kind, ...) k##kind,
  FOREACH_GENERIC_TYPE(DEF_ENUM) FOREACH_NUMERIC_VALUE_TYPE(DEF_ENUM)
#undef DEF_ENUM
};
Suspend
enum v8::internal::wasm::Suspend : int
Enumerator
kSuspend
kNoSuspend
Definition at line 34 of file module-instantiate.h.
: int { kSuspend, kNoSuspend };
SwitchKind
enum v8::internal::wasm::SwitchKind : uint8_t
Enumerator
kOnSuspend
kSwitch
kLastSwitchKind
Definition at line 173 of file wasm-constants.h.
                : uint8_t {
  kOnSuspend = 0x0,
  kSwitch = 0x1,
  kLastSwitchKind = kSwitch,
};
TrapReason
enum v8::internal::wasm::TrapReason
Enumerator
kTrapCount
Definition at line 965 of file wasm-opcodes.h.
                {
#define DECLARE_ENUM(name) k##name,
  FOREACH_WASM_TRAPREASON(DECLARE_ENUM)
  kTrapCount
#undef DECLARE_ENUM
};
TypeKind
enum v8::internal::wasm::TypeKind : uint8_t [strong]
Enumerator
kNumeric
kSentinel
kAbstractRef
kIndexedRef
Definition at line 208 of file value-type.h.
                    : uint8_t {
  kNumeric = 0b00, // i32, etc. FOREACH_NUMERIC_VALUE_TYPE above.
  kSentinel = SENTINEL, // top, bottom, void. Have "SENTINEL" above.
  kAbstractRef = REF, // anyref, eqref, funcref, etc. Have "REF" above.
  kIndexedRef = REF | SENTINEL,
};
ValueKind
enum v8::internal::wasm::ValueKind : uint8_t
Definition at line 108 of file value-type.h.
               : uint8_t {
#define DEF_ENUM(kind, ...) k##kind,
  FOREACH_VALUE_TYPE(DEF_ENUM)
#undef DEF_ENUM
};
ValueTypeCode
enum v8::internal::wasm::ValueTypeCode : uint8_t
Enumerator
kVoidCode
kI32Code
kI64Code
kF32Code
kF64Code
kS128Code
kI8Code
kI16Code
kF16Code
kNoExnCode
kNoFuncCode
kNoExternCode
kNoneCode
kFuncRefCode
kExternRefCode
kAnyRefCode
kEqRefCode
kI31RefCode
kStructRefCode
kArrayRefCode
kRefCode
kRefNullCode
kExactCode
kExnRefCode
kContRefCode
kNoContCode
kStringRefCode
kStringViewWtf8Code
kStringViewWtf16Code
kStringViewIterCode
kFirstHeapTypeCode
kLastHeapTypeCode
Definition at line 26 of file wasm-constants.h.
                   : uint8_t {
  // Current value types
  kVoidCode = 0x40,
  kI32Code = 0x7f, // -0x01
  kI64Code = 0x7e, // -0x02
  kF32Code = 0x7d, // -0x03
  kF64Code = 0x7c, // -0x04
  kS128Code = 0x7b, // -0x05
  kI8Code = 0x78, // -0x08, packed type
  kI16Code = 0x77, // -0x09, packed type
  kF16Code = 0x76, // -0x0a, packed type
  kNoExnCode = 0x74, // -0x0c
  kNoFuncCode = 0x73, // -0x0d
  kNoExternCode = 0x72, // -0x0e
  kNoneCode = 0x71, // -0x0f
  kFuncRefCode = 0x70, // -0x10
  kExternRefCode = 0x6f, // -0x11
  kAnyRefCode = 0x6e, // -0x12
  kEqRefCode = 0x6d, // -0x13
  kI31RefCode = 0x6c, // -0x14
  kStructRefCode = 0x6b, // -0x15
  kArrayRefCode = 0x6a, // -0x16
  kRefCode = 0x64, // -0x1c
  kRefNullCode = 0x63, // -0x1d
                                // Non-finalized proposals below.
  kExactCode = 0x62, // -0x1e
  kExnRefCode = 0x69, // -0x17
  kContRefCode = 0x68, // -0x18
  kNoContCode = 0x75, // -0x0b
  kStringRefCode = 0x67, // -0x19
  kStringViewWtf8Code = 0x66, // -0x1a
  kStringViewWtf16Code = 0x60, // -0x20
  kStringViewIterCode = 0x61, // -0x1f
  // For decoding, we build an array for all heap types with these bounds:
  kFirstHeapTypeCode = kStringViewWtf16Code, // Lowest assigned code.
  kLastHeapTypeCode = kNoContCode, // Highest assigned code.
};
WasmCompilationHintStrategy
enum v8::internal::wasm::WasmCompilationHintStrategy : uint8_t [strong]
Enumerator
kDefault
kLazy
kEager
kLazyBaselineEagerTopTier
Definition at line 275 of file wasm-module.h.
                                       : uint8_t {
  kDefault = 0,
  kLazy = 1,
  kEager = 2,
  kLazyBaselineEagerTopTier = 3,
};
WasmCompilationHintTier
enum v8::internal::wasm::WasmCompilationHintTier : uint8_t [strong]
Enumerator
kDefault
kBaseline
kOptimized
Definition at line 282 of file wasm-module.h.
                                   : uint8_t {
  kDefault = 0,
  kBaseline = 1,
  kOptimized = 2,
};
WasmDetectedFeature
enum v8::internal::wasm::WasmDetectedFeature [strong]
Enumerator
DECL_FEATURE_ENUM
Definition at line 48 of file wasm-features.h.
                               {
#define DECL_FEATURE_ENUM(feat, ...) feat,
  FOREACH_WASM_FEATURE(DECL_FEATURE_ENUM)
#undef DECL_FEATURE_ENUM
};
WasmEnabledFeature
enum v8::internal::wasm::WasmEnabledFeature [strong]
Enumerator
DECL_FEATURE_ENUM
Definition at line 42 of file wasm-features.h.
                              {
#define DECL_FEATURE_ENUM(feat, ...) feat,
  FOREACH_WASM_FEATURE_FLAG(DECL_FEATURE_ENUM)
#undef DECL_FEATURE_ENUM
};
WasmOpcode
enum v8::internal::wasm::WasmOpcode
Definition at line 955 of file wasm-opcodes.h.
                {
// Declare expression opcodes.
#define DECLARE_NAMED_ENUM(name, opcode, ...) kExpr##name = opcode,
  FOREACH_OPCODE(DECLARE_NAMED_ENUM)
#undef DECLARE_NAMED_ENUM
#define DECLARE_PREFIX(name, opcode) k##name##Prefix = opcode,
      FOREACH_PREFIX(DECLARE_PREFIX)
#undef DECLARE_PREFIX
};
WellKnownImport
enum v8::internal::wasm::WellKnownImport : uint8_t [strong]
Enumerator
kUninstantiated
kGeneric
kLinkError
kFirstCompileTimeImport
kStringCast
kStringCharCodeAt
kStringCodePointAt
kStringCompare
kStringConcat
kStringEquals
kStringFromCharCode
kStringFromCodePoint
kStringFromUtf8Array
kStringFromWtf16Array
kStringIntoUtf8Array
kStringLength
kStringMeasureUtf8
kStringSubstring
kStringTest
kStringToUtf8Array
kStringToWtf16Array
kLastCompileTimeImport
kDataViewGetBigInt64
kDataViewGetBigUint64
kDataViewGetFloat32
kDataViewGetFloat64
kDataViewGetInt8
kDataViewGetInt16
kDataViewGetInt32
kDataViewGetUint8
kDataViewGetUint16
kDataViewGetUint32
kDataViewSetBigInt64
kDataViewSetBigUint64
kDataViewSetFloat32
kDataViewSetFloat64
kDataViewSetInt8
kDataViewSetInt16
kDataViewSetInt32
kDataViewSetUint8
kDataViewSetUint16
kDataViewSetUint32
kDataViewByteLength
kMathF64Acos
kMathF64Asin
kMathF64Atan
kMathF64Atan2
kMathF64Cos
kMathF64Sin
kMathF64Tan
kMathF64Exp
kMathF64Log
kMathF64Pow
kMathF64Sqrt
kDoubleToString
kIntToString
kParseFloat
kStringIndexOf
kStringIndexOfImported
kStringToLocaleLowerCaseStringref
kStringToLowerCaseStringref
kStringToLowerCaseImported
kFastAPICall
Definition at line 19 of file well-known-imports.h.
                           : uint8_t {
  // Generic:
  kUninstantiated,
  kGeneric,
  kLinkError,
  ////////////////////////////////////////////////////////
  // Compile-time "builtin" imports:
  ////////////////////////////////////////////////////////
  kFirstCompileTimeImport,
  // JS String Builtins
  // https://github.com/WebAssembly/js-string-builtins
  // TODO(14179): Rename some of these to reflect the new import names.
  kStringCast = kFirstCompileTimeImport,
  kStringCharCodeAt,
  kStringCodePointAt,
  kStringCompare,
  kStringConcat,
  kStringEquals,
  kStringFromCharCode,
  kStringFromCodePoint,
  kStringFromUtf8Array,
  kStringFromWtf16Array,
  kStringIntoUtf8Array,
  kStringLength,
  kStringMeasureUtf8,
  kStringSubstring,
  kStringTest,
  kStringToUtf8Array,
  kStringToWtf16Array,
  kLastCompileTimeImport = kStringToWtf16Array,
  ////////////////////////////////////////////////////////
  // End of compile-time "builtin" imports.
  ////////////////////////////////////////////////////////
  // DataView methods:
  kDataViewGetBigInt64,
  kDataViewGetBigUint64,
  kDataViewGetFloat32,
  kDataViewGetFloat64,
  kDataViewGetInt8,
  kDataViewGetInt16,
  kDataViewGetInt32,
  kDataViewGetUint8,
  kDataViewGetUint16,
  kDataViewGetUint32,
  kDataViewSetBigInt64,
  kDataViewSetBigUint64,
  kDataViewSetFloat32,
  kDataViewSetFloat64,
  kDataViewSetInt8,
  kDataViewSetInt16,
  kDataViewSetInt32,
  kDataViewSetUint8,
  kDataViewSetUint16,
  kDataViewSetUint32,
  kDataViewByteLength,
  // Math functions.
  kMathF64Acos,
  kMathF64Asin,
  kMathF64Atan,
  kMathF64Atan2,
  kMathF64Cos,
  kMathF64Sin,
  kMathF64Tan,
  kMathF64Exp,
  kMathF64Log,
  kMathF64Pow,
  kMathF64Sqrt, // Used by dart2wasm. f64.sqrt is equivalent.
  // String-related functions:
  kDoubleToString,
  kIntToString,
  kParseFloat,
  kStringIndexOf,
  kStringIndexOfImported,
  kStringToLocaleLowerCaseStringref,
  kStringToLowerCaseStringref,
  kStringToLowerCaseImported,
  // Fast API calls:
  kFastAPICall,
};
Function Documentation
AbstractTypeCast()
template<TypeChecker type_checker>
bool v8::internal::wasm::AbstractTypeCast (Isolate * isolate, const WasmRef obj, const ValueType obj_type, bool null_succeeds)
Definition at line 2657 of file wasm-interpreter-runtime.cc.
                                                                    {
  if (null_succeeds && obj_type.is_nullable() &&
      WasmInterpreterRuntime::IsNull(isolate, obj, obj_type)) {
    return true;
  }
  return type_checker(obj);
}
References v8::internal::wasm::ValueTypeBase::is_nullable(), and v8::internal::wasm::WasmInterpreterRuntime::IsNull().
AddressTypeToStr()
constexpr const char* v8::internal::wasm::AddressTypeToStr (AddressType address_type) [inline], [constexpr]
Definition at line 51 of file wasm-module.h.
                                                                        {
  return address_type == AddressType::kI32 ? "i32" : "i64";
}
References kI32.
Referenced by GetTypeForTable(), operator<<(), v8::internal::wasm::InstanceBuilder::ProcessImportedMemories(), and v8::internal::wasm::InstanceBuilder::ProcessImportedTable().
AllocateOffsetsProvider()
std::unique_ptr<OffsetsProvider> v8::internal::wasm::AllocateOffsetsProvider () [inline]
Definition at line 229 of file wasm-disassembler-impl.h.
                                                                {
  return std::make_unique<OffsetsProvider>();
}
Referenced by Disassemble().
AnalyzeLoopAssignmentForTesting()
V8_EXPORT_PRIVATE BitVector * v8::internal::wasm::AnalyzeLoopAssignmentForTesting (Zone * zone, uint32_t num_locals, const uint8_t * start, const uint8_t * end, bool * loop_is_innermost)
Definition at line 98 of file function-body-decoder.cc.
                                                                    {
  WasmEnabledFeatures no_features = WasmEnabledFeatures::None();
  WasmDetectedFeatures unused_detected_features;
  constexpr bool kIsShared = false; // TODO(14616): Extend this.
  WasmDecoder<Decoder::FullValidationTag> decoder(
      zone, nullptr, no_features, &unused_detected_features, nullptr, kIsShared,
      start, end, 0);
  return WasmDecoder<Decoder::FullValidationTag>::AnalyzeLoopAssignment(
      &decoder, start, num_locals, zone, loop_is_innermost);
}
References v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::AnalyzeLoopAssignment(), v8::internal::compiler::end(), and v8::internal::wasm::WasmEnabledFeatures::None().
array_copy_wrapper()
void v8::internal::wasm::array_copy_wrapper (Address raw_dst_array, uint32_t dst_index, Address raw_src_array, uint32_t src_index, uint32_t length)
Definition at line 825 of file wasm-external-refs.cc.
                                         {
  DCHECK_GT(length, 0);
  ThreadNotInWasmScope thread_not_in_wasm_scope;
  DisallowGarbageCollection no_gc;
  Tagged<WasmArray> dst_array = Cast<WasmArray>(Tagged<Object>(raw_dst_array));
  Tagged<WasmArray> src_array = Cast<WasmArray>(Tagged<Object>(raw_src_array));
  bool overlapping_ranges =
      dst_array.ptr() == src_array.ptr() &&
      (dst_index < src_index ? dst_index + length > src_index
                             : src_index + length > dst_index);
  wasm::CanonicalValueType element_type =
      src_array->map()->wasm_type_info()->element_type();
  if (element_type.is_reference()) {
    ObjectSlot dst_slot = dst_array->ElementSlot(dst_index);
    ObjectSlot src_slot = src_array->ElementSlot(src_index);
    Heap* heap = Isolate::Current()->heap();
    if (overlapping_ranges) {
      heap->MoveRange(dst_array, dst_slot, src_slot, length,
                      UPDATE_WRITE_BARRIER);
    } else {
      heap->CopyRange(dst_array, dst_slot, src_slot, length,
                      UPDATE_WRITE_BARRIER);
    }
  } else {
    int element_size_bytes = element_type.value_kind_size();
    void* dst = ArrayElementAddress(dst_array, dst_index, element_size_bytes);
    void* src = ArrayElementAddress(src_array, src_index, element_size_bytes);
    size_t copy_size = length * element_size_bytes;
    if (overlapping_ranges) {
      MemMove(dst, src, copy_size);
    } else {
      MemCopy(dst, src, copy_size);
    }
  }
}
References v8::internal::wasm::anonymous_namespace{wasm-external-refs.cc}::ArrayElementAddress(), v8::internal::Isolate::Current(), DCHECK_GT, v8::internal::Isolate::heap(), v8::internal::wasm::ValueTypeBase::is_reference(), v8::internal::length, v8::internal::MemCopy(), v8::internal::MemMove(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), v8::internal::UPDATE_WRITE_BARRIER, and v8::internal::wasm::ValueTypeBase::value_kind_size().
array_fill_wrapper()
void v8::internal::wasm::array_fill_wrapper (Address raw_array, uint32_t index, uint32_t length, uint32_t emit_write_barrier, uint32_t raw_type, Address initial_value_addr)
Definition at line 864 of file wasm-external-refs.cc.
                                                    {
  ThreadNotInWasmScope thread_not_in_wasm_scope;
  DisallowGarbageCollection no_gc;
  ValueType type = ValueType::FromRawBitField(raw_type);
  int8_t* initial_element_address = reinterpret_cast<int8_t*>(
      ArrayElementAddress(raw_array, index, type.value_kind_size()));
  const int bytes_to_set = length * type.value_kind_size();
  // We implement the general case by setting the first 8 bytes manually, then
  // filling the rest by exponentially growing {memcpy}s.
  CHECK_GE(static_cast<size_t>(bytes_to_set), sizeof(int64_t));
  switch (type.kind()) {
    case kI64:
    case kF64: {
      // Stack pointers are only aligned to 4 bytes.
      int64_t initial_value =
          base::ReadUnalignedValue<int64_t>(initial_value_addr);
      if (initial_value == 0) {
        std::memset(initial_element_address, 0, bytes_to_set);
        return;
      }
      // Array elements are only aligned to 4 bytes, therefore
      // `initial_element_address` may be misaligned as a 64-bit pointer.
      base::WriteUnalignedValue<int64_t>(
          reinterpret_cast<Address>(initial_element_address), initial_value);
      break;
    }
    case kI32:
    case kF32: {
      int32_t initial_value = *reinterpret_cast<int32_t*>(initial_value_addr);
      if (initial_value == 0) {
        std::memset(initial_element_address, 0, bytes_to_set);
        return;
      }
      int32_t* base = reinterpret_cast<int32_t*>(initial_element_address);
      base[0] = base[1] = initial_value;
      break;
    }
    case kF16:
    case kI16: {
      // The array.fill input is an i32!
      int16_t initial_value = *reinterpret_cast<int32_t*>(initial_value_addr);
      if (initial_value == 0) {
        std::memset(initial_element_address, 0, bytes_to_set);
        return;
      }
      int16_t* base = reinterpret_cast<int16_t*>(initial_element_address);
      base[0] = base[1] = base[2] = base[3] = initial_value;
      break;
    }
    case kI8: {
      // The array.fill input is an i32!
      int8_t initial_value = *reinterpret_cast<int32_t*>(initial_value_addr);
      if (initial_value == 0) {
        std::memset(initial_element_address, 0, bytes_to_set);
        return;
      }
      int8_t* base = reinterpret_cast<int8_t*>(initial_element_address);
      for (size_t i = 0; i < sizeof(int64_t); i++) {
        base[i] = initial_value;
      }
      break;
    }
    case kRefNull:
    case kRef: {
      intptr_t uncompressed_pointer =
          base::ReadUnalignedValue<intptr_t>(initial_value_addr);
      if constexpr (kTaggedSize == 4) {
        int32_t* base = reinterpret_cast<int32_t*>(initial_element_address);
        base[0] = base[1] = static_cast<int32_t>(uncompressed_pointer);
      } else {
        base::WriteUnalignedValue(
            reinterpret_cast<Address>(initial_element_address),
            uncompressed_pointer);
      }
      break;
    }
    case kS128:
      // S128 can only be filled with zeros.
      DCHECK_EQ(base::ReadUnalignedValue<int64_t>(initial_value_addr), 0);
      std::memset(initial_element_address, 0, bytes_to_set);
      return;
    case kVoid:
    case kTop:
    case kBottom:
      UNREACHABLE();
  }
  int bytes_already_set = sizeof(int64_t);
  while (bytes_already_set * 2 <= bytes_to_set) {
    std::memcpy(initial_element_address + bytes_already_set,
                initial_element_address, bytes_already_set);
    bytes_already_set *= 2;
  }
  if (bytes_already_set < bytes_to_set) {
    std::memcpy(initial_element_address + bytes_already_set,
                initial_element_address, bytes_to_set - bytes_already_set);
  }
  if (emit_write_barrier) {
    DCHECK(type.is_reference());
    Tagged<WasmArray> array = Cast<WasmArray>(Tagged<Object>(raw_array));
    Isolate* isolate = Isolate::Current();
    ObjectSlot start(reinterpret_cast<Address>(initial_element_address));
    ObjectSlot end(
        reinterpret_cast<Address>(initial_element_address + bytes_to_set));
    WriteBarrier::ForRange(isolate->heap(), array, start, end);
  }
}
References v8::internal::wasm::anonymous_namespace{wasm-external-refs.cc}::ArrayElementAddress(), CHECK_GE, v8::internal::Isolate::Current(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::end(), v8::internal::WriteBarrier::ForRange(), v8::internal::wasm::ValueType::FromRawBitField(), v8::internal::Isolate::heap(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::kF32, v8::internal::kF64, v8::internal::kI16, v8::internal::kI32, v8::internal::kI64, v8::internal::kI8, v8::internal::kRef, v8::internal::kRefNull, v8::internal::kS128, v8::internal::kTaggedSize, v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::tracing::type, v8::internal::UNREACHABLE(), and v8::base::WriteUnalignedValue().
ArrayCheck()
static bool v8::internal::wasm::ArrayCheck (const WasmRef obj) [static]
Definition at line 2702 of file wasm-interpreter-runtime.cc.
                                          {
  if (IsSmi(*obj)) {
    return false;
  }
  if (!IsHeapObject(*obj)) return false;
  InstanceType instance_type = Cast<HeapObject>(obj)->map()->instance_type();
  return instance_type == WASM_ARRAY_TYPE;
}
References v8::internal::IsHeapObject(), and v8::internal::IsSmi().
ASSERT_TRIVIALLY_COPYABLE() [1/12]
v8::internal::wasm::ASSERT_TRIVIALLY_COPYABLE (CanonicalTypeIndex)
ASSERT_TRIVIALLY_COPYABLE() [2/12]
v8::internal::wasm::ASSERT_TRIVIALLY_COPYABLE (CanonicalValueType)
ASSERT_TRIVIALLY_COPYABLE() [3/12]
v8::internal::wasm::ASSERT_TRIVIALLY_COPYABLE (DirectHandle< Object >)
ASSERT_TRIVIALLY_COPYABLE() [4/12]
v8::internal::wasm::ASSERT_TRIVIALLY_COPYABLE (LiftoffRegister)
ASSERT_TRIVIALLY_COPYABLE() [5/12]
v8::internal::wasm::ASSERT_TRIVIALLY_COPYABLE (LiftoffRegList)
ASSERT_TRIVIALLY_COPYABLE() [6/12]
v8::internal::wasm::ASSERT_TRIVIALLY_COPYABLE (LiftoffVarState)
ASSERT_TRIVIALLY_COPYABLE() [7/12]
v8::internal::wasm::ASSERT_TRIVIALLY_COPYABLE (ModuleTypeIndex)
ASSERT_TRIVIALLY_COPYABLE() [8/12]
v8::internal::wasm::ASSERT_TRIVIALLY_COPYABLE (ModuleWireBytes)
ASSERT_TRIVIALLY_COPYABLE() [9/12]
v8::internal::wasm::ASSERT_TRIVIALLY_COPYABLE (ValueType)
ASSERT_TRIVIALLY_COPYABLE() [10/12]
v8::internal::wasm::ASSERT_TRIVIALLY_COPYABLE (ValueTypeBase)
ASSERT_TRIVIALLY_COPYABLE() [11/12]
v8::internal::wasm::ASSERT_TRIVIALLY_COPYABLE (WasmCompilationUnit)
ASSERT_TRIVIALLY_COPYABLE() [12/12]
v8::internal::wasm::ASSERT_TRIVIALLY_COPYABLE (WasmInitExpr)
BuildTSGraph()
V8_EXPORT_PRIVATE void v8::internal::wasm::BuildTSGraph (compiler::turboshaft::PipelineData * data, AccountingAllocator * allocator, CompilationEnv * env, WasmDetectedFeatures * detected, Graph & graph, const FunctionBody & func_body, const WireBytesStorage * wire_bytes, std::unique_ptr< AssumptionsJournal > * assumptions, ZoneVector< WasmInliningPosition > * inlining_positions, int func_index)
Definition at line 9231 of file turboshaft-graph-interface.cc.
                                                                          {
  DCHECK(env->module->function_was_validated(func_index));
  Zone zone(allocator, ZONE_NAME);
  WasmGraphBuilderBase::Assembler assembler(data, graph, graph, &zone);
  WasmFullDecoder<TurboshaftGraphBuildingInterface::ValidationTag,
                  TurboshaftGraphBuildingInterface>
      decoder(&zone, env->module, env->enabled_features, detected, func_body,
              &zone, env, assembler, assumptions, inlining_positions,
              func_index, func_body.is_shared, wire_bytes);
  decoder.Decode();
  // The function was already validated, so graph building must always succeed.
  DCHECK(decoder.ok());
}
References v8::internal::DCHECK(), v8::internal::wasm::CompilationEnv::enabled_features, v8::internal::wasm::WasmModule::function_was_validated(), graph(), v8::internal::wasm::FunctionBody::is_shared, v8::internal::wasm::CompilationEnv::module, and ZONE_NAME.
BuildWasmWrapper()
void v8::internal::wasm::BuildWasmWrapper (compiler::turboshaft::PipelineData * data, AccountingAllocator * allocator, compiler::turboshaft::Graph & graph, const wasm::CanonicalSig * sig, WrapperCompilationInfo wrapper_info)
Definition at line 1307 of file wrappers.cc.
                                                           {
  Zone zone(allocator, ZONE_NAME);
  WasmGraphBuilderBase::Assembler assembler(data, graph, graph, &zone);
  WasmWrapperTSGraphBuilder builder(&zone, assembler, sig);
  if (wrapper_info.code_kind == CodeKind::JS_TO_WASM_FUNCTION) {
    builder.BuildJSToWasmWrapper(wrapper_info.receiver_is_first_param);
  } else if (wrapper_info.code_kind == CodeKind::WASM_TO_JS_FUNCTION) {
    builder.BuildWasmToJSWrapper(wrapper_info.import_kind,
                                 wrapper_info.expected_arity,
                                 wrapper_info.suspend);
  } else if (wrapper_info.code_kind == CodeKind::WASM_TO_CAPI_FUNCTION) {
    builder.BuildCapiCallWrapper();
  } else {
    // TODO(thibaudm): Port remaining wrappers.
    UNREACHABLE();
  }
}
References v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCapiCallWrapper(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildJSToWasmWrapper(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildWasmToJSWrapper(), v8::internal::wasm::WrapperCompilationInfo::code_kind, v8::internal::wasm::WrapperCompilationInfo::expected_arity, graph(), v8::internal::wasm::WrapperCompilationInfo::import_kind, v8::internal::wasm::WrapperCompilationInfo::receiver_is_first_param, v8::internal::sig, v8::internal::wasm::WrapperCompilationInfo::suspend, v8::internal::UNREACHABLE(), and ZONE_NAME.
CallThroughDispatchTable()
DISABLE_CFI_ICALL void v8::internal::wasm::CallThroughDispatchTable (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 1408 of file wasm-interpreter-runtime.cc.
                            {
  kInstructionTable[ReadFnId(code) & kInstructionTableMask](
      code, sp, wasm_runtime, r0, fp0);
}
References code, kInstructionTable, kInstructionTableMask, and ReadFnId().
Referenced by v8::internal::wasm::WasmInterpreterRuntime::ExecuteFunction().
CanUseGenericJsToWasmWrapper()
bool v8::internal::wasm::CanUseGenericJsToWasmWrapper (const WasmModule * module, const CanonicalSig * sig) [inline]
Definition at line 165 of file function-compiler.h.
                                                                  {
#if (V8_TARGET_ARCH_X64 || V8_TARGET_ARCH_ARM64 || V8_TARGET_ARCH_IA32 || \
     V8_TARGET_ARCH_ARM || V8_TARGET_ARCH_S390X || V8_TARGET_ARCH_PPC64 || \
     V8_TARGET_ARCH_LOONG64)
  // We don't use the generic wrapper for asm.js, because it creates invalid
  // stack traces.
  return !is_asmjs_module(module) && v8_flags.wasm_generic_wrapper &&
         IsJSCompatibleSignature(sig);
#else
  return false;
#endif
}
References is_asmjs_module(), IsJSCompatibleSignature(), v8::internal::sig, and v8::internal::v8_flags.
Referenced by v8::internal::WasmExportedFunction::GetWrapper().
CheckHardwareSupportsSimd()
V8_EXPORT_PRIVATE bool v8::internal::wasm::CheckHardwareSupportsSimd ()
Definition at line 96 of file function-body-decoder.cc.
{ return CpuFeatures::SupportsWasmSimd128(); }
References v8::internal::CpuFeatures::SupportsWasmSimd128().
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE(), and v8::internal::wasm::value_type_reader::read_value_type().
CompileImportWrapperForTest()
V8_EXPORT_PRIVATE std::shared_ptr< wasm::WasmImportWrapperHandle > v8::internal::wasm::CompileImportWrapperForTest (Isolate * isolate, ImportCallKind kind, const CanonicalSig * sig, CanonicalTypeIndex type_index, int expected_arity, Suspend suspend)
Definition at line 4394 of file module-compiler.cc.
                                                                        {
  if (v8_flags.wasm_jitless) {
    return nullptr;
  }
  return GetWasmImportWrapperCache()->GetCompiled(isolate, kind, type_index,
                                                  expected_arity, suspend, sig);
}
References v8::internal::wasm::WasmImportWrapperCache::GetCompiled(), GetWasmImportWrapperCache(), v8::internal::sig, and v8::internal::v8_flags.
CompileLazy()
bool v8::internal::wasm::CompileLazy (Isolate * isolate, Tagged< WasmTrustedInstanceData > trusted_instance_data, int func_index)
Definition at line 1183 of file module-compiler.cc.
                                 {
  DisallowGarbageCollection no_gc;
  NativeModule* native_module = trusted_instance_data->native_module();
  Counters* counters = isolate->counters();
  // Put the timer scope around everything, including the {CodeSpaceWriteScope}
  // and its destruction, to measure complete overhead (apart from the runtime
  // function itself, which has constant overhead).
  std::optional<CompileLazyTimingScope> lazy_compile_time_scope;
  if (base::TimeTicks::IsHighResolution()) {
    lazy_compile_time_scope.emplace(counters, native_module);
  }
  DCHECK(!native_module->lazy_compile_frozen());
  TRACE_LAZY("Compiling wasm-function#%d.\n", func_index);
  CompilationStateImpl* compilation_state =
      Impl(native_module->compilation_state());
  DebugState is_in_debug_state = native_module->IsInDebugState();
  ExecutionTierPair tiers =
      GetLazyCompilationTiers(native_module, func_index, is_in_debug_state);
  DCHECK_LE(native_module->num_imported_functions(), func_index);
  DCHECK_LT(func_index, native_module->num_functions());
  WasmCompilationUnit baseline_unit{
      func_index, tiers.baseline_tier,
      is_in_debug_state ? kForDebugging : kNotForDebugging};
  CompilationEnv env = CompilationEnv::ForModule(native_module);
  WasmDetectedFeatures detected_features;
  WasmCompilationResult result = baseline_unit.ExecuteCompilation(
      &env, compilation_state->GetWireBytesStorage().get(), counters,
      &detected_features);
  compilation_state->OnCompilationStopped(detected_features);
  // During lazy compilation, we can only get compilation errors when
  // {--wasm-lazy-validation} is enabled. Otherwise, the module was fully
  // verified before starting its execution.
  CHECK_IMPLIES(result.failed(), v8_flags.wasm_lazy_validation);
  if (result.failed()) {
    return false;
  }
  WasmCodeRefScope code_ref_scope;
  WasmCode* code =
      native_module->PublishCode(native_module->AddCompiledCode(result));
  DCHECK_EQ(func_index, code->index());
  if (V8_UNLIKELY(native_module->log_code())) {
    GetWasmEngine()->LogCode(base::VectorOf(&code, 1));
    // Log the code immediately in the current isolate.
    GetWasmEngine()->LogOutstandingCodesForIsolate(isolate);
  }
  counters->wasm_lazily_compiled_functions()->Increment();
  const WasmModule* module = native_module->module();
  const bool lazy_module = IsLazyModule(module);
  if (GetCompileStrategy(module, native_module->enabled_features(), func_index,
                         lazy_module) == CompileStrategy::kLazy &&
      tiers.baseline_tier < tiers.top_tier) {
    WasmCompilationUnit tiering_unit{func_index, tiers.top_tier,
                                     kNotForDebugging};
    compilation_state->CommitTopTierCompilationUnit(tiering_unit);
  }
  return true;
}
References v8::internal::wasm::NativeModule::AddCompiledCode(), CHECK_IMPLIES, code, v8::internal::wasm::NativeModule::compilation_state(), v8::internal::Isolate::counters(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LE, DCHECK_LT, v8::internal::wasm::NativeModule::enabled_features(), v8::internal::wasm::CompilationEnv::ForModule(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::GetCompileStrategy(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::GetLazyCompilationTiers(), GetWasmEngine(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::Impl(), v8::base::TimeTicks::IsHighResolution(), v8::internal::wasm::NativeModule::IsInDebugState(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::IsLazyModule(), kForDebugging, kNotForDebugging, v8::internal::wasm::NativeModule::lazy_compile_frozen(), v8::internal::wasm::NativeModule::log_code(), v8::internal::wasm::WasmEngine::LogCode(), v8::internal::wasm::WasmEngine::LogOutstandingCodesForIsolate(), v8::internal::wasm::NativeModule::module(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::wasm::NativeModule::num_functions(), v8::internal::wasm::NativeModule::num_imported_functions(), v8::internal::wasm::NativeModule::PublishCode(), v8::base::internal::result, TRACE_LAZY, v8::internal::v8_flags, V8_UNLIKELY, and v8::base::VectorOf().
Referenced by v8::internal::Snapshot::ClearReconstructableDataForSerialization(), v8::internal::Compiler::GetFunctionFromEval(), v8::internal::CodeStubAssembler::GetSharedFunctionInfoCode(), v8::internal::ExistingCodeLogger::LogCompiledFunctions(), v8::internal::Compiler::LogFunctionCompilation(), v8::internal::ClosureFeedbackCellArray::New(), v8::internal::JSFunction::ResetIfCodeFlushed(), v8::internal::RUNTIME_FUNCTION(), v8::internal::Code::SetMarkedForDeoptimization(), and v8::internal::TF_BUILTIN().
CompileToNativeModule()
V8_EXPORT_PRIVATE std::shared_ptr< NativeModule > v8::internal::wasm::CompileToNativeModule (Isolate * isolate, WasmEnabledFeatures enabled_features, WasmDetectedFeatures detected_features, CompileTimeImports compile_imports, ErrorThrower * thrower, std::shared_ptr< const WasmModule > module, base::OwnedVector< const uint8_t > wire_bytes, int compilation_id, v8::metrics::Recorder::ContextId context_id, ProfileInformation * pgo_info)
Definition at line 2423 of file module-compiler.cc.
                                                                         {
  std::shared_ptr<NativeModule> native_module = GetOrCompileNewNativeModule(
      isolate, enabled_features, detected_features, std::move(compile_imports),
      thrower, module, std::move(wire_bytes), compilation_id, context_id,
      pgo_info);
  if (!native_module) return {};
  // Ensure that the code objects are logged before returning.
  GetWasmEngine()->LogOutstandingCodesForIsolate(isolate);
  // Now publish all detected features of this module in the current isolate.
  PublishDetectedFeatures(
      native_module->compilation_state()->detected_features(), isolate, true);
  return native_module;
}
References v8::internal::wasm::anonymous_namespace{module-compiler.cc}::GetOrCompileNewNativeModule(), GetWasmEngine(), v8::internal::wasm::WasmEngine::LogOutstandingCodesForIsolate(), and PublishDetectedFeatures().
Referenced by v8::internal::wasm::WasmEngine::SyncCompile(), and v8::internal::wasm::WasmEngine::SyncCompileTranslatedAsmJs().
ConditionToConditionCmpFPU()
static FPUCondition v8::internal::wasm::ConditionToConditionCmpFPU (Condition condition) [static]
Definition at line 402 of file liftoff-assembler-riscv-inl.h.
                                                                    {
  switch (condition) {
    case kEqual:
      return EQ;
    case kNotEqual:
      return NE;
    case kUnsignedLessThan:
      return LT;
    case kUnsignedGreaterThanEqual:
      return GE;
    case kUnsignedLessThanEqual:
      return LE;
    case kUnsignedGreaterThan:
      return GT;
    default:
      break;
  }
  UNREACHABLE();
}
References v8::internal::EQ, v8::internal::GE, v8::internal::GT, v8::internal::kEqual, v8::internal::kNotEqual, v8::internal::kUnsignedGreaterThan, v8::internal::kUnsignedGreaterThanEqual, v8::internal::kUnsignedLessThan, v8::internal::kUnsignedLessThanEqual, v8::internal::LE, v8::internal::LT, v8::internal::NE, and v8::internal::UNREACHABLE().
consume_string() [1/2]
WireBytesRef v8::internal::wasm::consume_string (Decoder * decoder, unibrow::Utf8Variant grammar, const char * name) [inline]
Definition at line 113 of file module-decoder-impl.h.
                                                     {
  return consume_string(decoder, grammar, name, ITracer::NoTrace);
}
References consume_string(), name(), and v8::internal::wasm::ITracer::NoTrace.
consume_string() [2/2]
WireBytesRef v8::internal::wasm::consume_string (Decoder * decoder, unibrow::Utf8Variant grammar, const char * name, ITracer * tracer) [inline]
Definition at line 66 of file module-decoder-impl.h.
                                                                      {
  if (tracer) {
    tracer->Description(name);
    tracer->Description(" ");
  }
  uint32_t length = decoder->consume_u32v("length", tracer);
  if (tracer) {
    tracer->Description(": ");
    tracer->Description(length);
    tracer->NextLine();
  }
  uint32_t offset = decoder->pc_offset();
  const uint8_t* string_start = decoder->pc();
  // Consume bytes before validation to guarantee that the string is not oob.
  if (length > 0) {
    if (tracer) {
      tracer->Bytes(decoder->pc(), length);
      tracer->Description(name);
      tracer->Description(": ");
      tracer->Description(reinterpret_cast<const char*>(decoder->pc()), length);
      tracer->NextLine();
    }
    decoder->consume_bytes(length, name);
    if (decoder->ok()) {
      switch (grammar) {
        case unibrow::Utf8Variant::kLossyUtf8:
          break;
        case unibrow::Utf8Variant::kUtf8:
          if (!unibrow::Utf8::ValidateEncoding(string_start, length)) {
            decoder->errorf(string_start, "%s: no valid UTF-8 string", name);
          }
          break;
        case unibrow::Utf8Variant::kWtf8:
          if (!unibrow::Wtf8::ValidateEncoding(string_start, length)) {
            decoder->errorf(string_start, "%s: no valid WTF-8 string", name);
          }
          break;
        case unibrow::Utf8Variant::kUtf8NoTrap:
          UNREACHABLE();
      }
    }
  }
  return {offset, decoder->failed() ? 0 : length};
}
References v8::internal::wasm::ITracer::Bytes(), v8::internal::wasm::Decoder::consume_bytes(), v8::internal::wasm::Decoder::consume_u32v(), v8::internal::wasm::ITracer::Description(), v8::internal::wasm::Decoder::errorf(), v8::internal::wasm::Decoder::failed(), unibrow::kLossyUtf8, v8::internal::length, name(), v8::internal::wasm::ITracer::NextLine(), v8::internal::wasm::Decoder::ok(), v8::internal::wasm::Decoder::pc(), v8::internal::wasm::Decoder::pc_offset(), v8::internal::UNREACHABLE(), and unibrow::Utf8::ValidateEncoding().
Referenced by v8::internal::wasm::DescriptorsSectionIterator::consume_string(), consume_string(), consume_utf8_string(), v8::internal::wasm::ModuleDecoderImpl::DecodeBuildIdSection(), DecodeCanonicalTypeNames(), v8::internal::wasm::anonymous_namespace{module-decoder.cc}::DecodeNameMapInternal(), v8::internal::wasm::ModuleDecoderImpl::DecodeNameSection(), and v8::internal::wasm::ModuleDecoderImpl::DecodeStringRefSection().
consume_utf8_string()
WireBytesRef v8::internal::wasm::consume_utf8_string (Decoder * decoder, const char * name, ITracer * tracer) [inline]
Definition at line 119 of file module-decoder-impl.h.
                                                         {
  return consume_string(decoder, unibrow::Utf8Variant::kUtf8, name, tracer);
}
References consume_string(), and name().
Referenced by v8::internal::wasm::ModuleDecoderImpl::DecodeExportSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeExternalDebugInfoSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeImportSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeSourceMappingURLSection(), and IdentifyUnknownSectionInternal().
ContentSize() [1/5]
template<typename T >
size_t v8::internal::wasm::ContentSize (const base::OwnedVector< T > & vector) [inline]
Definition at line 35 of file std-object-sizes.h.
                                                            {
  return vector.size() * sizeof(T);
}
References v8::base::OwnedVector< T >::size(), and T.
ContentSize() [2/5]
template<typename Key , typename T >
size_t v8::internal::wasm::ContentSize (const std::map< Key, T > & map) [inline]
Definition at line 40 of file std-object-sizes.h.
                                                     {
  // Very rough lower bound approximation: two internal pointers per entry.
  return map.size() * (sizeof(Key) + sizeof(T) + 2 * sizeof(void*));
}
ContentSize() [3/5]
template<typename Key , typename T , typename Hash >
size_t v8::internal::wasm::ContentSize (const std::unordered_map< Key, T, Hash > & map) [inline]
Definition at line 46 of file std-object-sizes.h.
                                                                     {
  // Very rough lower bound approximation: two internal pointers per entry.
  size_t raw = map.size() * (sizeof(Key) + sizeof(T) + 2 * sizeof(void*));
  // In the spirit of computing lower bounds of definitely-used memory,
  // we assume a 75% fill ratio.
  return raw * 4 / 3;
}
ContentSize() [4/5]
template<typename T , typename Hash >
size_t v8::internal::wasm::ContentSize (const std::unordered_set< T, Hash > & set) [inline]
Definition at line 55 of file std-object-sizes.h.
                                                                {
  // Very rough lower bound approximation: two internal pointers per entry.
  size_t raw = set.size() * (sizeof(T) + 2 * sizeof(void*));
  // In the spirit of computing lower bounds of definitely-used memory,
  // we assume a 75% fill ratio.
  return raw * 4 / 3;
}
References T.
ContentSize() [5/5]
template<typename T >
size_t v8::internal::wasm::ContentSize (const std::vector< T > & vector) [inline]
Definition at line 28 of file std-object-sizes.h.
                                                      {
  // We use {capacity()} rather than {size()} because we want to compute
  // actual memory consumption.
  return vector.capacity() * sizeof(T);
}
References T.
Referenced by v8::internal::wasm::TypeCanonicalizer::EstimateCurrentMemoryConsumption(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::EstimateCurrentMemoryConsumption(), v8::internal::wasm::CanonicalTypeNamesProvider::EstimateCurrentMemoryConsumption(), v8::internal::wasm::NativeModule::EstimateCurrentMemoryConsumption(), v8::internal::wasm::DebugInfoImpl::EstimateCurrentMemoryConsumption(), v8::internal::wasm::DebugSideTable::Entry::EstimateCurrentMemoryConsumption(), v8::internal::wasm::DebugSideTable::EstimateCurrentMemoryConsumption(), v8::internal::wasm::WasmEngine::EstimateCurrentMemoryConsumption(), v8::internal::wasm::WasmImportWrapperCache::EstimateCurrentMemoryConsumption(), v8::internal::wasm::WasmModuleSourceMap::EstimateCurrentMemoryConsumption(), v8::internal::wasm::TypeFeedbackStorage::EstimateCurrentMemoryConsumption(), v8::internal::wasm::WasmModule::EstimateStoredSize(), and v8::internal::wasm::anonymous_namespace{names-provider.cc}::StringMapSize().
ConvertToF16S()
Float16 v8::internal::wasm::ConvertToF16S (int16_t val)
Definition at line 608 of file wasm-external-refs.cc.
{ return Float16::FromFloat32(val); }
References v8::internal::Float16::FromFloat32().
ConvertToF16U()
Float16 v8::internal::wasm::ConvertToF16U (uint16_t val)
Definition at line 614 of file wasm-external-refs.cc.
{ return Float16::FromFloat32(val); }
References v8::internal::Float16::FromFloat32().
ConvertToIntS()
int16_t v8::internal::wasm::ConvertToIntS (Float16 val)
Definition at line 584 of file wasm-external-refs.cc.
                                   {
  float f32 = val.ToFloat32();
  if (std::isnan(f32)) return 0;
  if (f32 > float{kMaxInt16}) return kMaxInt16;
  if (f32 < float{kMinInt16}) return kMinInt16;
  return static_cast<int16_t>(f32);
}
References v8::internal::kMaxInt16, v8::internal::kMinInt16, and v8::internal::Float16::ToFloat32().
ConvertToIntU()
uint16_t v8::internal::wasm::ConvertToIntU (Float16 val)
Definition at line 592 of file wasm-external-refs.cc.
                                    {
  float f32 = val.ToFloat32();
  if (std::isnan(f32)) return 0;
  if (f32 > float{kMaxUInt16}) return kMaxUInt16;
  if (f32 < float{0}) return 0;
  return static_cast<uint16_t>(f32);
}
References v8::internal::kMaxUInt16, and v8::internal::Float16::ToFloat32().
CreateFunctionForCompileTimeImport()
DirectHandle<JSFunction> v8::internal::wasm::CreateFunctionForCompileTimeImport (Isolate * isolate, WellKnownImport wki)
Definition at line 2186 of file module-instantiate.cc.
                                           {
  auto [name, builtin, length] = NameBuiltinLength(wki);
  Factory* factory = isolate->factory();
  DirectHandle<NativeContext> context(isolate->native_context());
  DirectHandle<Map> map = isolate->strict_function_without_prototype_map();
  DirectHandle<String> name_str = factory->InternalizeUtf8String(name);
  DirectHandle<SharedFunctionInfo> info =
      factory->NewSharedFunctionInfoForBuiltin(name_str, builtin, length,
                                               kAdapt);
  info->set_native(true);
  info->set_language_mode(LanguageMode::kStrict);
  DirectHandle<JSFunction> fun =
      Factory::JSFunctionBuilder{isolate, info, context}.set_map(map).Build();
  return fun;
}
References v8::internal::Isolate::factory(), v8::internal::Factory::InternalizeUtf8String(), v8::internal::kAdapt, v8::internal::kStrict, v8::internal::length, name(), NameBuiltinLength(), v8::internal::Isolate::native_context(), and v8::internal::Factory::NewSharedFunctionInfoForBuiltin().
Referenced by v8::internal::wasm::InstanceBuilder::SanitizeImports().
CreateMapForType()
V8_EXPORT_PRIVATE void v8::internal::wasm::CreateMapForType (Isolate * isolate, const WasmModule * module, ModuleTypeIndex type_index, DirectHandle< FixedArray > maybe_shared_maps)
Definition at line 57 of file module-instantiate.cc.
                                                                  {
  // Recursive calls for supertypes may already have created this map.
  if (IsMap(maybe_shared_maps->get(type_index.index))) return;
  CanonicalTypeIndex canonical_type_index =
      module->canonical_type_id(type_index);
  // Try to find the canonical map for this type in the isolate store.
  DirectHandle<WeakFixedArray> canonical_rtts =
      direct_handle(isolate->heap()->wasm_canonical_rtts(), isolate);
  DCHECK_GT(static_cast<uint32_t>(canonical_rtts->length()),
            canonical_type_index.index);
  Tagged<MaybeObject> maybe_canonical_map =
      canonical_rtts->get(canonical_type_index.index);
  if (!maybe_canonical_map.IsCleared()) {
    maybe_shared_maps->set(type_index.index,
                           maybe_canonical_map.GetHeapObjectAssumeWeak());
    return;
  }
  DirectHandle<Map> rtt_parent;
  // If the type with {type_index} has an explicit supertype, make sure the
  // map for that supertype is created first, so that the supertypes list
  // that's cached on every RTT can be set up correctly.
  ModuleTypeIndex supertype = module->supertype(type_index);
  if (supertype.valid()) {
    // This recursion is safe, because kV8MaxRttSubtypingDepth limits the
    // number of recursive steps, so we won't overflow the stack.
    CreateMapForType(isolate, module, supertype, maybe_shared_maps);
    // We look up the supertype in {maybe_shared_maps} as a shared type can only
    // inherit from a shared type and vice verca.
    rtt_parent = direct_handle(
        Cast<Map>(maybe_shared_maps->get(supertype.index)), isolate);
  }
  DirectHandle<Map> map;
  switch (module->type(type_index).kind) {
    case TypeDefinition::kStruct: {
      DirectHandle<NativeContext> context_independent;
      map = CreateStructMap(isolate, canonical_type_index, rtt_parent,
                            context_independent);
      break;
    }
    case TypeDefinition::kArray:
      map = CreateArrayMap(isolate, canonical_type_index, rtt_parent);
      break;
    case TypeDefinition::kFunction:
      map = CreateFuncRefMap(isolate, canonical_type_index, rtt_parent,
                             module->type(type_index).is_shared);
      break;
    case TypeDefinition::kCont:
      UNIMPLEMENTED();
  }
  canonical_rtts->set(canonical_type_index.index, MakeWeak(*map));
  maybe_shared_maps->set(type_index.index, *map);
}
References v8::internal::wasm::WasmModule::canonical_type_id(), v8::internal::CreateArrayMap(), v8::internal::CreateFuncRefMap(), v8::internal::CreateStructMap(), DCHECK_GT, v8::internal::direct_handle(), v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectAssumeWeak(), v8::internal::Isolate::heap(), v8::internal::wasm::TypeIndex::index, v8::internal::wasm::TypeDefinition::is_shared, v8::internal::TaggedImpl< kRefType, StorageType >::IsCleared(), v8::internal::wasm::TypeDefinition::kArray, v8::internal::wasm::TypeDefinition::kCont, v8::internal::wasm::TypeDefinition::kFunction, v8::internal::wasm::TypeDefinition::kind, v8::internal::wasm::TypeDefinition::kStruct, v8::internal::MakeWeak(), v8::internal::wasm::WasmModule::supertype(), v8::internal::wasm::WasmModule::type(), v8::internal::UNIMPLEMENTED(), and v8::internal::wasm::TypeIndex::valid().
Referenced by v8::internal::wasm::InstanceBuilder::Build_Phase1().
declared_function_index()
int v8::internal::wasm::declared_function_index (const WasmModule * module, int func_index) [inline]
Definition at line 1076 of file wasm-module.h.
                                                                             {
  DCHECK_LE(module->num_imported_functions, func_index);
  int declared_idx = func_index - module->num_imported_functions;
  DCHECK_GT(module->num_declared_functions, declared_idx);
  return declared_idx;
}
References DCHECK_GT, DCHECK_LE, v8::internal::wasm::WasmModule::num_declared_functions, and v8::internal::wasm::WasmModule::num_imported_functions.
Referenced by v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::AllowAnotherTopTierJob(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::ApplyPgoInfoLate(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::ApplyPgoInfoToInitialProgress(), v8::internal::wasm::LiftoffAssembler::CallFrameSetupStub(), v8::internal::wasm::WasmCompilationUnit::ExecuteCompilation(), ExecuteLiftoffCompilation(), v8::internal::wasm::NativeModule::GetCode(), v8::internal::wasm::NativeModule::GetCodePointerHandle(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::GetCompilationHint(), GetSourcePosition(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::GetTopTierPriorityUnit(), v8::internal::wasm::NativeModule::HasCode(), v8::internal::wasm::NativeModule::HasCodeWithTier(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::InitializeCompilationProgressAfterDeserialization(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::InitializeCompilationUnitForSingleFunction(), v8::internal::wasm::WasmModuleCoverageData::InstallCoverageData(), JumpTableOffset(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::OnFinishedUnits(), v8::internal::wasm::TransitiveTypeFeedbackProcessor::ProcessFunction(), v8::internal::wasm::NativeModule::PublishCodeLocked(), v8::internal::wasm::NativeModule::ReinstallDebugCode(), v8::internal::RUNTIME_FUNCTION(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::StealTopTierPriorityUnit(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::TierupCheck(), v8::internal::JSFunction::ToString(), TriggerTierUp(), v8::internal::wasm::NativeModule::UseLazyStubLocked(), and v8::internal::wasm::NativeModuleSerializer::WriteCode().
DecodeAsmJsOffsets()
AsmJsOffsetsResult v8::internal::wasm::DecodeAsmJsOffsets (base::Vector< const uint8_t > encoded_offsets)
Definition at line 227 of file module-decoder.cc.
                                               {
  std::vector<AsmJsOffsetFunctionEntries> functions;
  Decoder decoder(encoded_offsets);
  uint32_t functions_count = decoder.consume_u32v("functions count");
  // Consistency check.
  DCHECK_GE(encoded_offsets.size(), functions_count);
  functions.reserve(functions_count);
  for (uint32_t i = 0; i < functions_count; ++i) {
    uint32_t size = decoder.consume_u32v("table size");
    if (size == 0) {
      functions.emplace_back();
      continue;
    }
    DCHECK(decoder.checkAvailable(size));
    const uint8_t* table_end = decoder.pc() + size;
    uint32_t locals_size = decoder.consume_u32v("locals size");
    int function_start_position = decoder.consume_u32v("function start pos");
    int function_end_position = function_start_position;
    int last_byte_offset = locals_size;
    int last_asm_position = function_start_position;
    std::vector<AsmJsOffsetEntry> func_asm_offsets;
    func_asm_offsets.reserve(size / 4); // conservative estimation
    // Add an entry for the stack check, associated with position 0.
    func_asm_offsets.push_back(
        {0, function_start_position, function_start_position});
    while (decoder.pc() < table_end) {
      DCHECK(decoder.ok());
      last_byte_offset += decoder.consume_u32v("byte offset delta");
      int call_position =
          last_asm_position + decoder.consume_i32v("call position delta");
      int to_number_position =
          call_position + decoder.consume_i32v("to_number position delta");
      last_asm_position = to_number_position;
      if (decoder.pc() == table_end) {
        // The last entry is the function end marker.
        DCHECK_EQ(call_position, to_number_position);
        function_end_position = call_position;
      } else {
        func_asm_offsets.push_back(
            {last_byte_offset, call_position, to_number_position});
      }
    }
    DCHECK_EQ(decoder.pc(), table_end);
    functions.emplace_back(AsmJsOffsetFunctionEntries{
        function_start_position, function_end_position,
        std::move(func_asm_offsets)});
  }
  DCHECK(decoder.ok());
  DCHECK(!decoder.more());
  return decoder.toResult(AsmJsOffsets{std::move(functions)});
}
References v8::internal::wasm::Decoder::checkAvailable(), v8::internal::wasm::Decoder::consume_i32v(), v8::internal::wasm::Decoder::consume_u32v(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GE, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::Decoder::more(), v8::internal::wasm::Decoder::ok(), v8::internal::wasm::Decoder::pc(), v8::base::Vector< T >::size(), size(), and v8::internal::wasm::Decoder::toResult().
Referenced by v8::internal::wasm::AsmJsOffsetInformation::EnsureDecodedOffsets().
DecodeCanonicalTypeNames()
void v8::internal::wasm::DecodeCanonicalTypeNames (base::Vector< const uint8_t > wire_bytes, const WasmModule * module, std::vector< base::OwnedVector< char >> & typenames, std::map< uint32_t, std::vector< base::OwnedVector< char >>> & fieldnames, size_t * total_allocated_size)
Definition at line 421 of file module-decoder.cc.
                                  {
  bool types_done = false;
  bool fields_done = false;
  Decoder decoder(wire_bytes);
  if (!FindNameSection(&decoder)) return;
  const char* base = reinterpret_cast<const char*>(wire_bytes.begin());
  while (decoder.ok() && decoder.more()) {
    uint8_t name_type = decoder.consume_u8("name type");
    if (name_type & 0x80) break; // no varuint7
    uint32_t name_payload_len = decoder.consume_u32v("name payload length");
    if (!decoder.checkAvailable(name_payload_len)) break;
    if (name_type == NameSectionKindCode::kTypeCode) {
      if (types_done) {
        decoder.consume_bytes(name_payload_len, "name subsection payload");
        continue; // The spec allows only one occurrence.
      }
      types_done = true;
      uint32_t count = decoder.consume_u32v("names count");
      for (uint32_t i = 0; i < count; i++) {
        ModuleTypeIndex module_index{decoder.consume_u32v("index")};
        WireBytesRef name =
            consume_string(&decoder, unibrow::Utf8Variant::kLossyUtf8, "name");
        if (!decoder.ok()) break;
        if (!module->has_type(module_index)) continue;
        if (name.is_empty()) continue;
        CanonicalTypeIndex canonical_index =
            module->canonical_type_id(module_index);
        uint32_t index = canonical_index.index;
        // Callers should have pre-sized the target vector appropriately.
        DCHECK_LT(index, typenames.size());
        // TODO(jkummerow): Consider implementing a more refined strategy
        // for conflict resolution than "first definition wins", if we
        // encounter that situation in practice. Note that we'll also have
        // to deal with multiple field names then (in the loop below).
        if (!typenames[index].empty()) continue; // We already have a name.
        if (!validate_utf8(&decoder, name)) continue;
        uint32_t length = name.length();
        typenames[index] =
            base::OwnedVector<char>::NewByCopying(base + name.offset(), length);
        *total_allocated_size += length;
      }
    } else if (name_type == NameSectionKindCode::kFieldCode) {
      if (fields_done) {
        decoder.consume_bytes(name_payload_len, "name subsection payload");
        continue; // The spec allows only one occurrence.
      }
      fields_done = true;
      uint32_t types_count = decoder.consume_u32v("types count");
      for (uint32_t i = 0; i < types_count; ++i) {
        ModuleTypeIndex module_index{decoder.consume_u32v("type index")};
        // TODO(jkummerow): Should we try to skip only the invalid entry?
        if (!module->has_struct(module_index)) return;
        CanonicalTypeIndex canonical_index =
            module->canonical_type_id(module_index);
        uint32_t struct_index = canonical_index.index;
        if (struct_index >= typenames.size()) return;
        // Due to {module->has_struct()}, this is guaranteed to succeed.
        const CanonicalStructType* struct_type =
            GetTypeCanonicalizer()->LookupStruct(canonical_index);
        auto const& entry = fieldnames.try_emplace(
            struct_index, size_t{struct_type->field_count()});
        std::vector<base::OwnedVector<char>>& field_names = entry.first->second;
        uint32_t fields_count = decoder.consume_u32v("fields count");
        for (uint32_t j = 0; j < fields_count; j++) {
          uint32_t field_index = decoder.consume_u32v("field index");
          WireBytesRef name = consume_string(
              &decoder, unibrow::Utf8Variant::kLossyUtf8, "field name");
          if (!decoder.ok()) break;
          if (field_index >= field_names.size()) continue;
          if (!field_names[field_index].empty()) continue;
          if (!validate_utf8(&decoder, name)) continue;
          uint32_t length = name.length();
          field_names[field_index] = base::OwnedVector<char>::NewByCopying(
              base + name.offset(), length);
          *total_allocated_size += length;
        }
        if (!decoder.ok()) break;
      }
    } else {
      // We don't care about this subsection here.
      decoder.consume_bytes(name_payload_len, "name subsection payload");
    }
  }
}
References v8::base::Vector< T >::begin(), v8::internal::wasm::WasmModule::canonical_type_id(), v8::internal::wasm::Decoder::checkAvailable(), v8::internal::wasm::Decoder::consume_bytes(), consume_string(), v8::internal::wasm::Decoder::consume_u32v(), v8::internal::wasm::Decoder::consume_u8(), DCHECK_LT, v8::internal::wasm::StructTypeBase::field_count(), v8::internal::wasm::anonymous_namespace{module-decoder.cc}::FindNameSection(), GetTypeCanonicalizer(), v8::internal::wasm::WasmModule::has_struct(), v8::internal::wasm::WasmModule::has_type(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::wasm::TypeIndex::index, kFieldCode, unibrow::kLossyUtf8, kTypeCode, v8::internal::length, v8::internal::wasm::TypeCanonicalizer::LookupStruct(), v8::internal::wasm::Decoder::more(), name(), v8::base::OwnedVector< T >::NewByCopying(), v8::internal::wasm::Decoder::ok(), and validate_utf8().
Referenced by v8::internal::wasm::CanonicalTypeNamesProvider::DecodeNames().
DecodeCustomSections()
V8_EXPORT_PRIVATE std::vector< CustomSectionOffset > v8::internal::wasm::DecodeCustomSections (base::Vector< const uint8_t > bytes)
Definition at line 283 of file module-decoder.cc.
                                     {
  Decoder decoder(bytes);
  decoder.consume_bytes(4, "wasm magic");
  decoder.consume_bytes(4, "wasm version");
  std::vector<CustomSectionOffset> result;
  while (decoder.more()) {
    uint8_t section_code = decoder.consume_u8("section code");
    uint32_t section_length = decoder.consume_u32v("section length");
    uint32_t section_start = decoder.pc_offset();
    if (section_code != 0) {
      // Skip known sections.
      decoder.consume_bytes(section_length, "section bytes");
      continue;
    }
    uint32_t name_length = decoder.consume_u32v("name length");
    uint32_t name_offset = decoder.pc_offset();
    decoder.consume_bytes(name_length, "section name");
    uint32_t payload_offset = decoder.pc_offset();
    if (section_length < (payload_offset - section_start)) {
      decoder.error("invalid section length");
      break;
    }
    uint32_t payload_length = section_length - (payload_offset - section_start);
    decoder.consume_bytes(payload_length);
    if (decoder.failed()) break;
    result.push_back({{section_start, section_length},
                      {name_offset, name_length},
                      {payload_offset, payload_length}});
  }
  return result;
}
References v8::internal::wasm::Decoder::consume_bytes(), v8::internal::wasm::Decoder::consume_u32v(), v8::internal::wasm::Decoder::consume_u8(), v8::internal::wasm::Decoder::error(), v8::internal::wasm::Decoder::failed(), v8::internal::wasm::Decoder::more(), v8::internal::wasm::Decoder::pc_offset(), and v8::base::internal::result.
Referenced by GetCustomSections().
DecodeError() [1/2]
template<typename ValidationTag , typename... Args>
void v8::internal::wasm::DecodeError (Decoder * decoder, const char * str, Args &&... args) [inline]
Definition at line 200 of file function-body-decoder-impl.h.
                                                                              {
  // Decode errors can only happen if we are validating; the compiler should
  // know this e.g. from the VALIDATE macro, but this assumption tells it again
  // that this path is impossible.
  V8_ASSUME(ValidationTag::validate);
  if constexpr (sizeof...(Args) == 0) {
    decoder->error(str);
  } else {
    decoder->errorf(str, std::forward<Args>(args)...);
  }
}
References v8::base::args, v8::internal::wasm::Decoder::error(), v8::internal::wasm::Decoder::errorf(), and V8_ASSUME.
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeAsmJsOpcode(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeAtomicOpcode(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeGCOpcode(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeNumericOpcode(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeSimdOpcode(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeStringRefOpcode(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::NotEnoughArgumentsError(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::ParseBrOnCast(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PopTypeError(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Push(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::TypeCheckOneArmedIf(), and v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::TypeCheckStackAgainstMerge_Slow().
DecodeError() [2/2]
template<typename ValidationTag , typename... Args>
void v8::internal::wasm::DecodeError (Decoder * decoder, const uint8_t * pc, const char * str, Args &&... args) [inline]
Definition at line 183 of file function-body-decoder-impl.h.
                                           {
  // Decode errors can only happen if we are validating; the compiler should
  // know this e.g. from the VALIDATE macro, but this assumption tells it again
  // that this path is impossible.
  V8_ASSUME(ValidationTag::validate);
  if constexpr (sizeof...(Args) == 0) {
    decoder->error(pc, str);
  } else {
    decoder->errorf(pc, str, std::forward<Args>(args)...);
  }
}
References v8::base::args, v8::internal::wasm::Decoder::error(), v8::internal::wasm::Decoder::errorf(), and V8_ASSUME.
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE(), and v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeEffectHandlerTable().
DecodeFunctionNames()
void v8::internal::wasm::DecodeFunctionNames (base::Vector< const uint8_t > wire_bytes, NameMap & names)
Definition at line 387 of file module-decoder.cc.
                                         {
  Decoder decoder(wire_bytes);
  if (!FindNameSection(&decoder)) return;
  while (decoder.ok() && decoder.more()) {
    uint8_t name_type = decoder.consume_u8("name type");
    if (name_type & 0x80) break; // no varuint7
    uint32_t name_payload_len = decoder.consume_u32v("name payload length");
    if (!decoder.checkAvailable(name_payload_len)) break;
    if (name_type != NameSectionKindCode::kFunctionCode) {
      decoder.consume_bytes(name_payload_len, "name subsection payload");
      continue;
    }
    // We need to allow empty function names for spec-conformant stack traces.
    DecodeNameMapInternal(names, decoder, EmptyNames::kAllow);
    // The spec allows only one occurrence of each subsection. We could be
    // more permissive and allow repeated subsections; in that case we'd
    // have to delay calling {target.FinishInitialization()} on the function
    // names map until we've seen them all.
    // For now, we stop decoding after finding the first function names
    // subsection.
    return;
  }
}
References v8::internal::wasm::Decoder::checkAvailable(), v8::internal::wasm::Decoder::consume_bytes(), v8::internal::wasm::Decoder::consume_u32v(), v8::internal::wasm::Decoder::consume_u8(), v8::internal::wasm::anonymous_namespace{module-decoder.cc}::DecodeNameMapInternal(), v8::internal::wasm::anonymous_namespace{module-decoder.cc}::FindNameSection(), kFunctionCode, v8::internal::wasm::Decoder::more(), and v8::internal::wasm::Decoder::ok().
Referenced by v8::internal::wasm::LazilyGeneratedNames::LookupFunctionName().
DecodeLocalDecls() [1/2]
V8_EXPORT_PRIVATE void v8::internal::wasm::DecodeLocalDecls (WasmEnabledFeatures enabled, BodyLocalDecls * decls, const uint8_t * start, const uint8_t * end, Zone * zone)
Definition at line 43 of file function-body-decoder.cc.
                                                                            {
  constexpr WasmModule* kNoModule = nullptr;
  DecodeLocalDecls<Decoder::NoValidationTag>(enabled, decls, kNoModule, false,
                                             start, end, zone);
}
References v8::internal::compiler::end().
DecodeLocalDecls() [2/2]
template<typename ValidationTag >
bool v8::internal::wasm::DecodeLocalDecls (WasmEnabledFeatures enabled, BodyLocalDecls * decls, const WasmModule * module, bool is_shared, const uint8_t * start, const uint8_t * end, Zone * zone)
Definition at line 21 of file function-body-decoder.cc.
                                                                            {
  if constexpr (ValidationTag::validate) DCHECK_NOT_NULL(module);
  WasmDetectedFeatures unused_detected_features;
  constexpr FixedSizeSignature<ValueType, 0, 0> kNoSig;
  WasmDecoder<ValidationTag> decoder(zone, module, enabled,
                                     &unused_detected_features, &kNoSig,
                                     is_shared, start, end);
  decls->encoded_size = decoder.DecodeLocals(decoder.pc());
  if (ValidationTag::validate && decoder.failed()) {
    DCHECK_EQ(0, decls->encoded_size);
    return false;
  }
  DCHECK(decoder.ok());
  // Copy the decoded locals types into {decls->local_types}.
  DCHECK_NULL(decls->local_types);
  decls->num_locals = decoder.num_locals_;
  decls->local_types = decoder.local_types_;
  return true;
}
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NOT_NULL, DCHECK_NULL, v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeLocals(), v8::internal::wasm::BodyLocalDecls::encoded_size, v8::internal::compiler::end(), v8::internal::wasm::Decoder::failed(), v8::internal::is_shared, v8::internal::wasm::BodyLocalDecls::local_types, v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::local_types_, v8::internal::wasm::BodyLocalDecls::num_locals, v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::num_locals_, v8::internal::wasm::Decoder::ok(), and v8::internal::wasm::Decoder::pc().
Referenced by v8::internal::wasm::BytecodeIterator::BytecodeIterator().
DecodeWasmFunctionForTesting()
V8_EXPORT_PRIVATE FunctionResult v8::internal::wasm::DecodeWasmFunctionForTesting (WasmEnabledFeatures enabled_features, Zone * zone, ModuleWireBytes wire_bytes, const WasmModule * module, base::Vector< const uint8_t > function_bytes)
Definition at line 212 of file module-decoder.cc.
                                              {
  if (function_bytes.size() > kV8MaxWasmFunctionSize) {
    return FunctionResult{
        WasmError{0, "size > maximum function size (%zu): %zu",
                  kV8MaxWasmFunctionSize, function_bytes.size()}};
  }
  WasmDetectedFeatures unused_detected_features;
  ModuleDecoderImpl decoder{enabled_features, function_bytes, kWasmOrigin,
                            &unused_detected_features};
  return decoder.DecodeSingleFunctionForTesting(zone, wire_bytes, module);
}
References kV8MaxWasmFunctionSize, kWasmOrigin, and v8::base::Vector< T >::size().
DecodeWasmInitExprForTesting()
V8_EXPORT_PRIVATE ConstantExpression v8::internal::wasm::DecodeWasmInitExprForTesting (WasmEnabledFeatures enabled_features, base::Vector< const uint8_t > bytes, ValueType expected)
Definition at line 203 of file module-decoder.cc.
                        {
  WasmDetectedFeatures unused_detected_features;
  ModuleDecoderImpl decoder{enabled_features, bytes, kWasmOrigin,
                            &unused_detected_features};
  return decoder.DecodeInitExprForTesting(expected);
}
References kWasmOrigin.
DecodeWasmModule() [1/2]
V8_EXPORT_PRIVATE ModuleResult v8::internal::wasm::DecodeWasmModule (WasmEnabledFeatures enabled_features, base::Vector< const uint8_t > wire_bytes, bool validate_functions, ModuleOrigin origin, Counters * counters, std::shared_ptr< metrics::Recorder > metrics_recorder, v8::metrics::Recorder::ContextId context_id, DecodingMethod decoding_method, WasmDetectedFeatures * detected_features)
Definition at line 77 of file module-decoder.cc.
                                             {
  if (counters) {
    auto size_counter =
        SELECT_WASM_COUNTER(counters, origin, wasm, module_size_bytes);
    static_assert(kV8MaxWasmModuleSize < kMaxInt);
    size_counter->AddSample(static_cast<int>(wire_bytes.size()));
  }
  v8::metrics::WasmModuleDecoded metrics_event;
  base::ElapsedTimer timer;
  timer.Start();
  ModuleResult result =
      DecodeWasmModule(enabled_features, wire_bytes, validate_functions, origin,
                       detected_features);
  if (counters && result.ok()) {
    auto counter =
        SELECT_WASM_COUNTER(counters, origin, wasm_functions_per, module);
    counter->AddSample(
        static_cast<int>(result.value()->num_declared_functions));
  }
  // Record event metrics.
  metrics_event.wall_clock_duration_in_us = timer.Elapsed().InMicroseconds();
  timer.Stop();
  metrics_event.success = result.ok();
  metrics_event.async = decoding_method == DecodingMethod::kAsync ||
                        decoding_method == DecodingMethod::kAsyncStream;
  metrics_event.streamed = decoding_method == DecodingMethod::kSyncStream ||
                           decoding_method == DecodingMethod::kAsyncStream;
  if (result.ok()) {
    metrics_event.function_count = result.value()->num_declared_functions;
  }
  metrics_event.module_size_in_bytes = wire_bytes.size();
  metrics_recorder->DelayMainThreadEvent(metrics_event, context_id);
  return result;
}
References v8::metrics::WasmModuleDecoded::async, v8::base::ElapsedTimer::Elapsed(), v8::metrics::WasmModuleDecoded::function_count, v8::base::TimeDelta::InMicroseconds(), kAsync, kAsyncStream, v8::internal::kMaxInt, kSyncStream, kV8MaxWasmModuleSize, v8::metrics::WasmModuleDecoded::module_size_in_bytes, v8::base::internal::result, SELECT_WASM_COUNTER, v8::base::Vector< T >::size(), v8::base::ElapsedTimer::Start(), v8::base::ElapsedTimer::Stop(), v8::metrics::WasmModuleDecoded::streamed, v8::metrics::WasmModuleDecoded::success, and v8::metrics::WasmModuleDecoded::wall_clock_duration_in_us.
Referenced by DeserializeNativeModule(), v8::internal::wasm::AsyncCompileJob::Failed(), v8::internal::wasm::AsyncStreamingProcessor::OnFinishedStream(), v8::internal::wasm::AsyncCompileJob::DecodeModule::RunInBackground(), v8::internal::wasm::WasmEngine::SyncCompile(), v8::internal::wasm::WasmEngine::SyncCompileTranslatedAsmJs(), and v8::internal::wasm::WasmEngine::SyncValidate().
DecodeWasmModule() [2/2]
V8_EXPORT_PRIVATE ModuleResult v8::internal::wasm::DecodeWasmModule (WasmEnabledFeatures enabled_features, base::Vector< const uint8_t > wire_bytes, bool validate_functions, ModuleOrigin origin, WasmDetectedFeatures * detected_features)
Definition at line 121 of file module-decoder.cc.
                                                                       {
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.wasm.detailed"),
               "wasm.DecodeWasmModule");
  ModuleDecoderImpl decoder{enabled_features, wire_bytes, origin,
                            detected_features};
  ModuleResult result = decoder.DecodeModule(validate_functions);
  return result;
}
References v8::base::internal::result, TRACE_DISABLED_BY_DEFAULT, and TRACE_EVENT0.
DecodeWasmModuleForDisassembler()
V8_EXPORT_PRIVATE ModuleResult v8::internal::wasm::DecodeWasmModuleForDisassembler (base::Vector< const uint8_t > wire_bytes, ITracer * tracer)
Definition at line 133 of file module-decoder.cc.
                                                           {
  constexpr bool kNoValidateFunctions = false;
  WasmDetectedFeatures unused_detected_features;
  ModuleDecoderImpl decoder{WasmEnabledFeatures::All(), wire_bytes, kWasmOrigin,
                            &unused_detected_features, tracer};
  return decoder.DecodeModule(kNoValidateFunctions);
}
References v8::internal::wasm::WasmEnabledFeatures::All(), and kWasmOrigin.
Referenced by Disassemble().
DecodeWasmSignatureForTesting()
V8_EXPORT_PRIVATE Result< const FunctionSig * > v8::internal::wasm::DecodeWasmSignatureForTesting (WasmEnabledFeatures enabled_features, Zone * zone, base::Vector< const uint8_t > bytes)
Definition at line 193 of file module-decoder.cc.
                                     {
  WasmDetectedFeatures unused_detected_features;
  ModuleDecoderImpl decoder{enabled_features, bytes, kWasmOrigin,
                            &unused_detected_features};
  return decoder.toResult(
      decoder.DecodeFunctionSignatureForTesting(zone, bytes.begin()));
}
References v8::base::Vector< T >::begin(), and kWasmOrigin.
DEFINE_LAZY_LEAKY_OBJECT_GETTER()
v8::internal::wasm::DEFINE_LAZY_LEAKY_OBJECT_GETTER (WasmCodePointerTable , GetProcessWideWasmCodePointerTable)
Definition at line 21 of file wasm-code-pointer-table.cc.
                                               {
  DCHECK(!freelist.is_empty());
  std::vector<uint32_t> entries(freelist.length());
  uint32_t entry = freelist.next();
  for (uint32_t i = 0; i < freelist.length(); i++) {
    entries[i] = entry;
    entry = at(entry).GetNextFreelistEntryIndex();
  }
  return entries;
}
References v8::internal::SegmentedTable< WasmCodePointerTableEntry, kCodePointerTableReservationSize >::at(), v8::internal::DCHECK(), and v8::internal::anonymous_namespace{json-stringifier.cc}::i.
DeserializeNativeModule()
V8_EXPORT_PRIVATE MaybeDirectHandle< WasmModuleObject > v8::internal::wasm::DeserializeNativeModule (Isolate * isolate, base::Vector< const uint8_t > data, base::Vector< const uint8_t > wire_bytes_vec, const CompileTimeImports & compile_imports, base::Vector< const char > source_url)
Definition at line 1091 of file wasm-serialization.cc.
                                       {
  WasmEnabledFeatures enabled_features =
      WasmEnabledFeatures::FromIsolate(isolate);
  if (!IsWasmCodegenAllowed(isolate, isolate->native_context())) return {};
  if (!IsSupportedVersion(data, enabled_features)) return {};
  // Make the copy of the wire bytes early, so we use the same memory for
  // decoding, lookup in the native module cache, and insertion into the cache.
  base::OwnedVector<const uint8_t> owned_wire_bytes =
      base::OwnedCopyOf(wire_bytes_vec);
  WasmDetectedFeatures detected_features;
  ModuleResult decode_result = DecodeWasmModule(
      enabled_features, owned_wire_bytes.as_vector(), false,
      i::wasm::kWasmOrigin, isolate->counters(), isolate->metrics_recorder(),
      isolate->GetOrRegisterRecorderContextId(isolate->native_context()),
      DecodingMethod::kDeserialize, &detected_features);
  if (decode_result.failed()) return {};
  std::shared_ptr<WasmModule> module = std::move(decode_result).value();
  CHECK_NOT_NULL(module);
  WasmEngine* wasm_engine = GetWasmEngine();
  auto shared_native_module = wasm_engine->MaybeGetNativeModule(
      module->origin, owned_wire_bytes.as_vector(), compile_imports, isolate);
  if (shared_native_module == nullptr) {
    size_t code_size_estimate =
        wasm::WasmCodeManager::EstimateNativeModuleCodeSize(module.get());
    shared_native_module = wasm_engine->NewNativeModule(
        isolate, enabled_features, detected_features, compile_imports,
        std::move(module), code_size_estimate);
    // We have to assign a compilation ID here, as it is required for a
    // potential re-compilation, e.g. triggered by
    // {EnterDebuggingForIsolate}. The value is -2 so that it is different
    // than the compilation ID of actual compilations, and also different than
    // the sentinel value of the CompilationState.
    shared_native_module->compilation_state()->set_compilation_id(-2);
    shared_native_module->SetWireBytes(std::move(owned_wire_bytes));
    NativeModuleDeserializer deserializer(shared_native_module.get());
    Reader reader(data + WasmSerializer::kHeaderSize);
    bool error = !deserializer.Read(&reader);
    if (error) {
      wasm_engine->UpdateNativeModuleCache(
          error, std::move(shared_native_module), isolate);
      return {};
    }
    shared_native_module->compilation_state()->InitializeAfterDeserialization(
        deserializer.lazy_functions(), deserializer.eager_functions());
    wasm_engine->UpdateNativeModuleCache(error, shared_native_module, isolate);
    // Now publish the full set of detected features (read during
    // deserialization, so potentially more than from DecodeWasmModule above).
    detected_features =
        shared_native_module->compilation_state()->detected_features();
    PublishDetectedFeatures(detected_features, isolate, true);
  }
  DirectHandle<Script> script =
      wasm_engine->GetOrCreateScript(isolate, shared_native_module, source_url);
  DirectHandle<WasmModuleObject> module_object =
      WasmModuleObject::New(isolate, shared_native_module, script);
  // Finish the Wasm script now and make it public to the debugger.
  isolate->debug()->OnAfterCompile(script);
  // Log the code within the generated module for profiling.
  shared_native_module->LogWasmCodes(isolate, *script);
  return module_object;
}
References v8::base::OwnedVector< T >::as_vector(), CHECK_NOT_NULL, v8::internal::Isolate::counters(), v8::internal::Isolate::debug(), DecodeWasmModule(), v8::internal::wasm::NativeModuleDeserializer::eager_functions(), v8::internal::wasm::WasmCodeManager::EstimateNativeModuleCodeSize(), v8::internal::wasm::Result< T >::failed(), v8::internal::wasm::WasmEnabledFeatures::FromIsolate(), v8::internal::wasm::WasmEngine::GetOrCreateScript(), v8::internal::Isolate::GetOrRegisterRecorderContextId(), GetWasmEngine(), IsSupportedVersion(), IsWasmCodegenAllowed(), kDeserialize, v8::internal::wasm::WasmSerializer::kHeaderSize, kWasmOrigin, v8::internal::wasm::NativeModuleDeserializer::lazy_functions(), v8::internal::wasm::WasmEngine::MaybeGetNativeModule(), v8::internal::Isolate::metrics_recorder(), v8::internal::Isolate::native_context(), v8::internal::WasmModuleObject::New(), v8::internal::wasm::WasmEngine::NewNativeModule(), v8::internal::Debug::OnAfterCompile(), v8::base::OwnedCopyOf(), PublishDetectedFeatures(), v8::internal::wasm::NativeModuleDeserializer::Read(), v8::internal::script, and v8::internal::wasm::WasmEngine::UpdateNativeModuleCache().
Referenced by v8::internal::wasm::AsyncStreamingProcessor::Deserialize(), v8::internal::wasm::SyncStreamingDecoder::Finish(), and v8::internal::RUNTIME_FUNCTION().
DeserializeTieringInformation()
std::unique_ptr<ProfileInformation> v8::internal::wasm::DeserializeTieringInformation (Decoder & decoder, const WasmModule * module)
Definition at line 163 of file pgo.cc.
                                                {
  std::vector<uint32_t> executed_functions;
  std::vector<uint32_t> tiered_up_functions;
  uint32_t start = module->num_imported_functions;
  uint32_t end = start + module->num_declared_functions;
  for (uint32_t func_index = start; func_index < end; ++func_index) {
    uint8_t tiering_info = decoder.consume_u8("tiering info");
    CHECK_EQ(0, tiering_info & ~3);
    bool was_executed = tiering_info & kFunctionExecutedBit;
    bool was_tiered_up = tiering_info & kFunctionTieredUpBit;
    if (was_tiered_up) tiered_up_functions.push_back(func_index);
    if (was_executed) executed_functions.push_back(func_index);
  }
  return std::make_unique<ProfileInformation>(std::move(executed_functions),
                                              std::move(tiered_up_functions));
}
References CHECK_EQ, v8::internal::wasm::Decoder::consume_u8(), v8::internal::compiler::end(), kFunctionExecutedBit, kFunctionTieredUpBit, v8::internal::wasm::WasmModule::num_declared_functions, and v8::internal::wasm::WasmModule::num_imported_functions.
Referenced by RestoreProfileData().
DeserializeTypeFeedback()
void v8::internal::wasm::DeserializeTypeFeedback (Decoder & decoder, const WasmModule * module)
Definition at line 105 of file pgo.cc.
                                                                         {
  base::MutexGuard mutex_guard{&module->type_feedback.mutex};
  std::unordered_map<uint32_t, FunctionTypeFeedback>& feedback_for_function =
      module->type_feedback.feedback_for_function;
  uint32_t num_entries = decoder.consume_u32v("num function entries");
  CHECK_LE(num_entries, module->num_declared_functions);
  for (uint32_t missing_entries = num_entries; missing_entries > 0;
       --missing_entries) {
    FunctionTypeFeedback function_feedback;
    uint32_t function_index = decoder.consume_u32v("function index");
    // Deserialize {feedback_vector}.
    uint32_t feedback_vector_size =
        decoder.consume_u32v("feedback vector size");
    function_feedback.feedback_vector =
        base::OwnedVector<CallSiteFeedback>::NewForOverwrite(
            feedback_vector_size);
    for (CallSiteFeedback& feedback : function_feedback.feedback_vector) {
      int num_cases = decoder.consume_i32v("num cases");
      if (num_cases == 0) continue; // no feedback
      if (num_cases == 1) { // monomorphic
        int called_function_index = decoder.consume_i32v("function index");
        int call_count = decoder.consume_i32v("call count");
        feedback = CallSiteFeedback{called_function_index, call_count};
      } else { // polymorphic
        auto* polymorphic = new CallSiteFeedback::PolymorphicCase[num_cases];
        for (int i = 0; i < num_cases; ++i) {
          polymorphic[i].function_index =
              decoder.consume_i32v("function index");
          polymorphic[i].absolute_call_frequency =
              decoder.consume_i32v("call count");
        }
        feedback = CallSiteFeedback{polymorphic, num_cases};
      }
    }
    // Deserialize {call_targets}.
    uint32_t num_call_targets = decoder.consume_u32v("num call targets");
    function_feedback.call_targets =
        base::OwnedVector<uint32_t>::NewForOverwrite(num_call_targets);
    for (uint32_t& call_target : function_feedback.call_targets) {
      call_target = decoder.consume_u32v("call target");
    }
    // Finally, insert the new feedback into the map. Overwrite existing
    // feedback, but check for consistency.
    auto [feedback_it, is_new] = feedback_for_function.emplace(
        function_index, std::move(function_feedback));
    if (!is_new) {
      FunctionTypeFeedback& old_feedback = feedback_it->second;
      CHECK(old_feedback.feedback_vector.empty() ||
            old_feedback.feedback_vector.size() == feedback_vector_size);
      CHECK_EQ(old_feedback.call_targets.as_vector(),
               function_feedback.call_targets.as_vector());
      std::swap(old_feedback.feedback_vector,
                function_feedback.feedback_vector);
    }
  }
}
References v8::base::OwnedVector< T >::as_vector(), v8::internal::wasm::FunctionTypeFeedback::call_targets, CHECK, CHECK_EQ, CHECK_LE, v8::internal::wasm::Decoder::consume_i32v(), v8::internal::wasm::Decoder::consume_u32v(), v8::internal::wasm::TypeFeedbackStorage::feedback_for_function, v8::internal::wasm::FunctionTypeFeedback::feedback_vector, v8::internal::wasm::CallSiteFeedback::PolymorphicCase::function_index, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::TypeFeedbackStorage::mutex, v8::base::OwnedVector< T >::NewForOverwrite(), v8::internal::wasm::WasmModule::num_declared_functions, and v8::internal::wasm::WasmModule::type_feedback.
Referenced by RestoreProfileData().
Disassemble() [1/2]
void v8::internal::wasm::Disassemble (base::Vector< const uint8_t > wire_bytes, v8::debug::DisassemblyCollector * collector, std::vector< int > * function_body_offsets)
Definition at line 35 of file wasm-disassembler.cc.
                                                        {
  std::unique_ptr<OffsetsProvider> offsets = AllocateOffsetsProvider();
  ModuleResult result =
      DecodeWasmModuleForDisassembler(wire_bytes, offsets.get());
  MultiLineStringBuilder out;
  AccountingAllocator allocator;
  if (result.failed()) {
    WasmError error = result.error();
    out << "Decoding error: " << error.message() << " at offset "
        << error.offset();
    out.ToDisassemblyCollector(collector);
    return;
  }
  const WasmModule* module = result.value().get();
  NamesProvider names(module, wire_bytes);
  ModuleWireBytes module_bytes(wire_bytes);
  ModuleDisassembler md(out, module, &names, module_bytes, &allocator,
                        std::move(offsets), function_body_offsets);
  md.PrintModule({0, 2}, v8_flags.wasm_disassembly_max_mb);
  out.ToDisassemblyCollector(collector);
}
References AllocateOffsetsProvider(), DecodeWasmModuleForDisassembler(), v8::internal::wasm::WasmError::message(), v8::internal::wasm::WasmError::offset(), v8::internal::wasm::ModuleDisassembler::PrintModule(), v8::base::internal::result, v8::internal::wasm::MultiLineStringBuilder::ToDisassemblyCollector(), and v8::internal::v8_flags.
Disassemble() [2/2]
void v8::internal::wasm::Disassemble (const WasmModule * module, ModuleWireBytes wire_bytes, NamesProvider * names, v8::debug::DisassemblyCollector * collector, std::vector< int > * function_body_offsets)
Definition at line 23 of file wasm-disassembler.cc.
                                                        {
  MultiLineStringBuilder out;
  AccountingAllocator allocator;
  ModuleDisassembler md(out, module, names, wire_bytes, &allocator,
                        /* no offsets yet */ {}, function_body_offsets);
  md.PrintModule({0, 2}, v8_flags.wasm_disassembly_max_mb);
  out.ToDisassemblyCollector(collector);
}
References v8::internal::wasm::ModuleDisassembler::PrintModule(), v8::internal::wasm::MultiLineStringBuilder::ToDisassemblyCollector(), and v8::internal::v8_flags.
Referenced by v8::internal::wasm::NativeModule::DisassembleForLcov(), and v8_inspector::V8DebuggerAgentImpl::disassembleWasmModule().
DisassembleFunction() [1/2]
void v8::internal::wasm::DisassembleFunction (const WasmModule * module, int func_index, base::Vector< const uint8_t > function_body, base::Vector< const uint8_t > maybe_wire_bytes, uint32_t function_body_offset, std::ostream & os, std::vector< uint32_t > * offsets)
Definition at line 101 of file wasm-disassembler.cc.
                                                       {
  DCHECK(func_index < static_cast<int>(module->functions.size()) &&
         func_index >= static_cast<int>(module->num_imported_functions));
  NamesProvider fake_names(module, maybe_wire_bytes);
  DisassembleFunctionImpl(module, func_index, function_body,
                          ModuleWireBytes{nullptr, 0}, &fake_names, os,
                          offsets);
}
References v8::internal::DCHECK(), DisassembleFunctionImpl(), v8::internal::wasm::WasmModule::functions, and v8::internal::wasm::WasmModule::num_imported_functions.
DisassembleFunction() [2/2]
void v8::internal::wasm::DisassembleFunction (const WasmModule * module, int func_index, base::Vector< const uint8_t > wire_bytes, NamesProvider * names, std::ostream & os)
Definition at line 88 of file wasm-disassembler.cc.
                                                               {
  DCHECK(func_index < static_cast<int>(module->functions.size()) &&
         func_index >= static_cast<int>(module->num_imported_functions));
  ModuleWireBytes module_bytes(wire_bytes);
  base::Vector<const uint8_t> code =
      module_bytes.GetFunctionBytes(&module->functions[func_index]);
  std::vector<uint32_t>* collect_offsets = nullptr;
  DisassembleFunctionImpl(module, func_index, code, module_bytes, names, os,
                          collect_offsets);
}
References code, v8::internal::DCHECK(), DisassembleFunctionImpl(), v8::internal::wasm::WasmModule::functions, v8::internal::wasm::ModuleWireBytes::GetFunctionBytes(), and v8::internal::wasm::WasmModule::num_imported_functions.
Referenced by v8::internal::compiler::JsonPrintFunctionSource().
DisassembleFunctionImpl()
void v8::internal::wasm::DisassembleFunctionImpl (const WasmModule * module, int func_index, base::Vector< const uint8_t > function_body, ModuleWireBytes module_bytes, NamesProvider * names, std::ostream & os, std::vector< uint32_t > * offsets)
Definition at line 69 of file wasm-disassembler.cc.
                                                                           {
  MultiLineStringBuilder sb;
  const wasm::WasmFunction& func = module->functions[func_index];
  AccountingAllocator allocator;
  Zone zone(&allocator, "Wasm disassembler");
  bool shared = module->type(func.sig_index).is_shared;
  WasmDetectedFeatures detected;
  FunctionBodyDisassembler d(&zone, module, func_index, shared, &detected,
                             func.sig, function_body.begin(),
                             function_body.end(), func.code.offset(),
                             module_bytes, names);
  d.DecodeAsWat(sb, {0, 2}, FunctionBodyDisassembler::kPrintHeader);
  const bool print_offsets = false;
  sb.WriteTo(os, print_offsets, offsets);
}
References v8::base::Vector< T >::begin(), v8::internal::wasm::WasmFunction::code, v8::internal::wasm::FunctionBodyDisassembler::DecodeAsWat(), v8::base::Vector< T >::end(), v8::internal::wasm::WasmModule::functions, v8::internal::wasm::TypeDefinition::is_shared, v8::internal::wasm::FunctionBodyDisassembler::kPrintHeader, v8::internal::wasm::WireBytesRef::offset(), v8::internal::wasm::WasmFunction::sig, v8::internal::wasm::WasmFunction::sig_index, v8::internal::wasm::WasmModule::type(), and v8::internal::wasm::MultiLineStringBuilder::WriteTo().
Referenced by DisassembleFunction().
DumpModule()
void v8::internal::wasm::DumpModule (const base::Vector< const uint8_t > module_bytes, bool ok) [inline]
Definition at line 284 of file module-decoder-impl.h.
                                {
  std::string path;
  if (v8_flags.dump_wasm_module_path) {
    path = v8_flags.dump_wasm_module_path;
    if (path.size() && !base::OS::isDirectorySeparator(path[path.size() - 1])) {
      path += base::OS::DirectorySeparator();
    }
  }
  // File are named `<hash>.{ok,failed}.wasm`.
  // Limit the hash to 8 characters (32 bits).
  uint32_t hash = static_cast<uint32_t>(GetWireBytesHash(module_bytes));
  base::EmbeddedVector<char, 32> buf;
  SNPrintF(buf, "%08x.%s.wasm", hash, ok ? "ok" : "failed");
  path += buf.begin();
  size_t rv = 0;
  if (FILE* file = base::OS::FOpen(path.c_str(), "wb")) {
    rv = fwrite(module_bytes.begin(), module_bytes.length(), 1, file);
    base::Fclose(file);
  }
  if (rv != 1) {
    OFStream os(stderr);
    os << "Error while dumping wasm file to " << path << std::endl;
  }
}
References v8::base::Vector< T >::begin(), v8::base::OS::DirectorySeparator(), v8::base::Fclose(), file(), v8::base::OS::FOpen(), GetWireBytesHash(), v8::base::OS::isDirectorySeparator(), v8::base::Vector< T >::length(), v8::base::SNPrintF(), v8::internal::string, and v8::internal::v8_flags.
Referenced by v8::internal::wasm::ModuleDecoderImpl::DecodeModule().
DumpProfileToFile()
void v8::internal::wasm::DumpProfileToFile (const WasmModule * module, base::Vector< const uint8_t > wire_bytes, std::atomic< uint32_t > * tiering_budget_array)
Definition at line 196 of file pgo.cc.
                                                                  {
  CHECK(!wire_bytes.empty());
  // File are named `profile-wasm-<hash>`.
  // We use the same hash as for reported scripts, to make it easier to
  // correlate files to wasm modules (see {CreateWasmScript}).
  uint32_t hash = static_cast<uint32_t>(GetWireBytesHash(wire_bytes));
  base::EmbeddedVector<char, 32> filename;
  SNPrintF(filename, "profile-wasm-%08x", hash);
  ProfileGenerator profile_generator{module, tiering_budget_array};
  base::OwnedVector<uint8_t> profile_data = profile_generator.GetProfileData();
  PrintF(
      "Dumping Wasm PGO data to file '%s' (module size %zu, %u declared "
      "functions, %zu bytes PGO data)\n",
      filename.begin(), wire_bytes.size(), module->num_declared_functions,
      profile_data.size());
  if (FILE* file = base::OS::FOpen(filename.begin(), "wb")) {
    size_t written = fwrite(profile_data.begin(), 1, profile_data.size(), file);
    CHECK_EQ(profile_data.size(), written);
    base::Fclose(file);
  }
}
References v8::base::Vector< T >::begin(), v8::base::OwnedVector< T >::begin(), CHECK, CHECK_EQ, v8::base::Vector< T >::empty(), v8::base::Fclose(), file(), v8::base::OS::FOpen(), GetWireBytesHash(), v8::internal::wasm::WasmModule::num_declared_functions, v8::internal::PrintF(), v8::base::Vector< T >::size(), v8::base::OwnedVector< T >::size(), v8::base::SNPrintF(), and v8::internal::tiering_budget_array.
Referenced by v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::WriteOutPGOTask::Run(), and v8::internal::wasm::NativeModule::~NativeModule().
EqCheck()
static bool v8::internal::wasm::EqCheck (const WasmRef obj) [static]
Definition at line 2666 of file wasm-interpreter-runtime.cc.
                                       {
  if (IsSmi(*obj)) {
    return true;
  }
  if (!IsHeapObject(*obj)) return false;
  InstanceType instance_type = Cast<HeapObject>(obj)->map()->instance_type();
  return instance_type >= FIRST_WASM_OBJECT_TYPE &&
         instance_type <= LAST_WASM_OBJECT_TYPE;
}
References v8::internal::IsHeapObject(), and v8::internal::IsSmi().
EquivalentNumericSig()
V8_EXPORT_PRIVATE bool v8::internal::wasm::EquivalentNumericSig (const CanonicalSig * a, const FunctionSig * b)
Definition at line 172 of file value-type.cc.
                                                                       {
  if (a->parameter_count() != b->parameter_count()) return false;
  if (a->return_count() != b->return_count()) return false;
  base::Vector<const CanonicalValueType> a_types = a->all();
  base::Vector<const ValueType> b_types = b->all();
  for (size_t i = 0; i < a_types.size(); i++) {
    if (!a_types[i].is_numeric()) return false;
    if (a_types[i].kind() != b_types[i].kind()) return false;
  }
  return true;
}
References v8::internal::Signature< T >::all(), v8::internal::Signature< T >::parameter_count(), v8::internal::Signature< T >::return_count(), and v8::base::Vector< T >::size().
EquivalentTypes() [1/2]
V8_NOINLINE V8_EXPORT_PRIVATE bool v8::internal::wasm::EquivalentTypes (ValueType type1, ValueType type2, const WasmModule * module)
Definition at line 481 of file wasm-subtyping.cc.
                                                           {
  if (type1 == type2) return true;
  if (!type1.has_index() || !type2.has_index()) return type1 == type2;
  if (type1.nullability() != type2.nullability()) return false;
  if (type1.is_exact() != type2.is_exact()) return false;
  DCHECK(type1.has_index() && module->has_type(type1.ref_index()) &&
         type2.has_index() && module->has_type(type2.ref_index()));
  return EquivalentIndices(type1.ref_index(), type2.ref_index(), module);
}
References v8::internal::DCHECK(), v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::EquivalentIndices(), v8::internal::wasm::ValueTypeBase::has_index(), v8::internal::wasm::WasmModule::has_type(), v8::internal::wasm::ValueTypeBase::is_exact(), v8::internal::wasm::ValueTypeBase::nullability(), and v8::internal::wasm::ValueType::ref_index().
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildIndirectCallTargetAndImplicitArg(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallIndirectImpl(), v8::internal::wasm::WasmInterpreterRuntime::CheckIndirectCallSignature(), v8::internal::wasm::DebugSideTable::Entry::Value::operator==(), v8::internal::wasm::InstanceBuilder::ProcessImportedTable(), v8::internal::wasm::InstanceBuilder::ProcessImportedWasmGlobalObject(), v8::internal::compiler::WasmTyper::Reduce(), v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::ValidArraySubtypeDefinition(), and v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::ValidStructSubtypeDefinition().
EquivalentTypes() [2/2]
V8_NOINLINE V8_EXPORT_PRIVATE bool v8::internal::wasm::EquivalentTypes (ValueType type1, ValueType type2, const WasmModule * module1, const WasmModule * module2)
Definition at line 494 of file wasm-subtyping.cc.
                                                            {
  if (type1 == type2 && module1 == module2) return true;
  if (!type1.has_index() || !type2.has_index()) return type1 == type2;
  if (type1.nullability() != type2.nullability()) return false;
  if (type1.is_exact() != type2.is_exact()) return false;
  DCHECK(type1.has_index() && module1->has_type(type1.ref_index()) &&
         type2.has_index() && module2->has_type(type2.ref_index()));
  return module1->canonical_type_id(type1.ref_index()) ==
         module2->canonical_type_id(type2.ref_index());
}
References v8::internal::wasm::WasmModule::canonical_type_id(), v8::internal::DCHECK(), v8::internal::wasm::ValueTypeBase::has_index(), v8::internal::wasm::WasmModule::has_type(), v8::internal::wasm::ValueTypeBase::is_exact(), v8::internal::wasm::ValueTypeBase::nullability(), and v8::internal::wasm::ValueType::ref_index().
ErrorStringForCodegen()
V8_EXPORT_PRIVATE DirectHandle< String > v8::internal::wasm::ErrorStringForCodegen (Isolate * isolate, DirectHandle< Context > context)
Definition at line 274 of file wasm-module.cc.
                                                                          {
  DirectHandle<Object> error = context->ErrorMessageForWasmCodeGeneration();
  DCHECK(!error.is_null());
  return Object::NoSideEffectsToString(isolate, error);
}
References v8::internal::DCHECK(), v8::internal::DirectHandle< T >::is_null(), and v8::internal::Object::NoSideEffectsToString().
Referenced by v8::anonymous_namespace{wasm-js.cc}::StartAsyncCompilationWithResolver(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyCompileImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyInstantiateImpl(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyModuleImpl().
EvaluateConstantExpression()
ValueOrError v8::internal::wasm::EvaluateConstantExpression (Zone * zone, ConstantExpression expr, ValueType expected, const WasmModule * module, Isolate * isolate, DirectHandle< WasmTrustedInstanceData > trusted_instance_data, DirectHandle< WasmTrustedInstanceData > shared_trusted_instance_data)
Definition at line 29 of file constant-expression.cc.
                                                                        {
  switch (expr.kind()) {
    case ConstantExpression::Kind::kEmpty:
      UNREACHABLE();
    case ConstantExpression::Kind::kI32Const:
      return WasmValue(expr.i32_value());
    case ConstantExpression::Kind::kRefNull:
      return WasmValue(expected.use_wasm_null()
                           ? Cast<Object>(isolate->factory()->wasm_null())
                           : Cast<Object>(isolate->factory()->null_value()),
                       module->canonical_type(ValueType::RefNull(expr.type())));
    case ConstantExpression::Kind::kRefFunc: {
      uint32_t index = expr.index();
      bool function_is_shared =
          module->type(module->functions[index].sig_index).is_shared;
      DirectHandle<WasmFuncRef> value =
          WasmTrustedInstanceData::GetOrCreateFuncRef(
              isolate,
              function_is_shared ? shared_trusted_instance_data
                                 : trusted_instance_data,
              index);
      return WasmValue(value, module->canonical_type(expected));
    }
    case ConstantExpression::Kind::kWireBytesRef: {
      WireBytesRef ref = expr.wire_bytes_ref();
      base::Vector<const uint8_t> module_bytes =
          trusted_instance_data->native_module()->wire_bytes();
      const uint8_t* start = module_bytes.begin() + ref.offset();
      const uint8_t* end = module_bytes.begin() + ref.end_offset();
      auto sig = FixedSizeSignature<ValueType>::Returns(expected);
      // We have already validated the expression, so we might as well
      // revalidate it as non-shared, which is strictly more permissive.
      // TODO(14616): Rethink this.
      constexpr bool kIsShared = false;
      FunctionBody body(&sig, ref.offset(), start, end, kIsShared);
      WasmDetectedFeatures detected;
      ValueOrError result;
      {
        // We need a scope for the decoder because its destructor resets some
        // Zone elements, which has to be done before we reset the Zone
        // afterwards.
        // We use FullValidationTag so we do not have to create another template
        // instance of WasmFullDecoder, which would cost us >50Kb binary code
        // size.
        WasmFullDecoder<Decoder::FullValidationTag, ConstantExpressionInterface,
                        kConstantExpression>
            decoder(zone, module, WasmEnabledFeatures::All(), &detected, body,
                    module, isolate, trusted_instance_data,
                    shared_trusted_instance_data);
        decoder.DecodeFunctionBody();
        result = decoder.interface().has_error()
                     ? ValueOrError(decoder.interface().error())
                     : ValueOrError(decoder.interface().computed_value());
      }
      zone->Reset();
      return result;
    }
  }
}
References v8::internal::wasm::WasmEnabledFeatures::All(), v8::base::Vector< T >::begin(), v8::internal::wasm::WasmModule::canonical_type(), v8::internal::compiler::end(), v8::internal::wasm::WireBytesRef::end_offset(), v8::internal::Isolate::factory(), v8::internal::wasm::WasmModule::functions, v8::internal::WasmTrustedInstanceData::GetOrCreateFuncRef(), v8::internal::wasm::ConstantExpression::i32_value(), v8::internal::index, v8::internal::wasm::ConstantExpression::index(), v8::internal::wasm::TypeDefinition::is_shared, kConstantExpression, v8::internal::wasm::ConstantExpression::kEmpty, v8::internal::wasm::ConstantExpression::kI32Const, v8::internal::wasm::ConstantExpression::kind(), v8::internal::wasm::ConstantExpression::kRefFunc, v8::internal::wasm::ConstantExpression::kRefNull, v8::internal::wasm::ConstantExpression::kWireBytesRef, v8::internal::wasm::WireBytesRef::offset(), v8::internal::wasm::ValueType::RefNull(), v8::internal::Zone::Reset(), v8::base::internal::result, v8::internal::FixedSizeSignature< T, kNumReturns, kNumParams >::Returns(), v8::internal::sig, v8::internal::wasm::ConstantExpression::type(), v8::internal::wasm::WasmModule::type(), v8::internal::UNREACHABLE(), v8::internal::wasm::ValueTypeBase::use_wasm_null(), v8::internal::value, and v8::internal::wasm::ConstantExpression::wire_bytes_ref().
Referenced by v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::ConsumeElementSegmentEntry(), v8::internal::wasm::InstanceBuilder::InitGlobals(), v8::internal::wasm::InstanceBuilder::LoadDataSegments(), v8::internal::wasm::InstanceBuilder::LoadTableSegments(), and v8::internal::wasm::InstanceBuilder::SetTableInitialValues().
ExecuteLiftoffCompilation()
V8_EXPORT_PRIVATE WasmCompilationResult v8::internal::wasm::ExecuteLiftoffCompilation (CompilationEnv * env, const FunctionBody & func_body, const LiftoffOptions & compiler_options)
Definition at line 10533 of file liftoff-compiler.cc.
                                            {
  DCHECK(compiler_options.is_initialized());
  // Liftoff does not validate the code, so that should have run before.
  DCHECK(env->module->function_was_validated(compiler_options.func_index));
  base::TimeTicks start_time;
  if (V8_UNLIKELY(v8_flags.trace_wasm_compilation_times)) {
    start_time = base::TimeTicks::Now();
  }
  int func_body_size = static_cast<int>(func_body.end - func_body.start);
  TRACE_EVENT2(TRACE_DISABLED_BY_DEFAULT("v8.wasm.detailed"),
               "wasm.CompileBaseline", "funcIndex", compiler_options.func_index,
               "bodySize", func_body_size);
  Zone zone(GetWasmEngine()->allocator(), "LiftoffCompilationZone");
  auto call_descriptor = compiler::GetWasmCallDescriptor(&zone, func_body.sig);
  std::unique_ptr<DebugSideTableBuilder> debug_sidetable_builder;
  if (compiler_options.debug_sidetable) {
    debug_sidetable_builder = std::make_unique<DebugSideTableBuilder>();
  }
  DCHECK_IMPLIES(compiler_options.max_steps,
                 compiler_options.for_debugging == kForDebugging);
  WasmDetectedFeatures unused_detected_features;
  WasmFunctionCoverageData* function_coverage_data = nullptr;
  if (V8_UNLIKELY(v8_flags.wasm_code_coverage)) {
    DCHECK_NOT_NULL(env->module_coverage_data);
    int declared_function_index =
        compiler_options.func_index - env->module->num_imported_functions;
    function_coverage_data = env->module_coverage_data->GetFunctionCoverageData(
        declared_function_index);
    if (!function_coverage_data) {
      // There can be a race here, if another thread finds that
      // GetFunctionCoverageData() returns nullptr, but in that case we would
      // just waste some time calling ComputeBasicBlocks().
      BasicBlockCalculator basic_block_calculator(
          &zone, {func_body.start, static_cast<size_t>(func_body_size)});
      basic_block_calculator.ComputeBasicBlocks();
      function_coverage_data = env->module_coverage_data->InstallCoverageData(
          declared_function_index, basic_block_calculator.GetCodeRanges());
    }
  }
  WasmFullDecoder<Decoder::NoValidationTag, LiftoffCompiler> decoder(
      &zone, env->module, env->enabled_features,
      compiler_options.detected_features ? compiler_options.detected_features
                                         : &unused_detected_features,
      func_body, call_descriptor, env, &zone,
      NewLiftoffAssemblerBuffer(func_body_size), debug_sidetable_builder.get(),
      compiler_options, function_coverage_data);
  decoder.Decode();
  LiftoffCompiler* compiler = &decoder.interface();
  if (decoder.failed()) compiler->OnFirstError(&decoder);
  if (auto* counters = compiler_options.counters) {
    // Check that the histogram for the bailout reasons has the correct size.
    DCHECK_EQ(0, counters->liftoff_bailout_reasons()->min());
    DCHECK_EQ(kNumBailoutReasons - 1,
              counters->liftoff_bailout_reasons()->max());
    DCHECK_EQ(kNumBailoutReasons,
              counters->liftoff_bailout_reasons()->num_buckets());
    // Register the bailout reason (can also be {kSuccess}).
    counters->liftoff_bailout_reasons()->AddSample(
        static_cast<int>(compiler->bailout_reason()));
  }
  if (compiler->did_bailout()) return WasmCompilationResult{};
  WasmCompilationResult result;
  compiler->GetCode(&result.code_desc);
  result.instr_buffer = compiler->ReleaseBuffer();
  result.source_positions = compiler->GetSourcePositionTable();
  result.protected_instructions_data = compiler->GetProtectedInstructionsData();
  result.frame_slot_count = compiler->GetTotalFrameSlotCountForGC();
  result.ool_spill_count = compiler->OolSpillCount();
  auto* lowered_call_desc = GetLoweredCallDescriptor(&zone, call_descriptor);
  result.tagged_parameter_slots = lowered_call_desc->GetTaggedParameterSlots();
  result.func_index = compiler_options.func_index;
  result.result_tier = ExecutionTier::kLiftoff;
  result.for_debugging = compiler_options.for_debugging;
  result.frame_has_feedback_slot = v8_flags.wasm_inlining;
  result.liftoff_frame_descriptions = compiler->ReleaseFrameDescriptions();
  if (auto* debug_sidetable = compiler_options.debug_sidetable) {
    *debug_sidetable = debug_sidetable_builder->GenerateDebugSideTable();
  }
  if (V8_UNLIKELY(v8_flags.trace_wasm_compilation_times)) {
    base::TimeDelta time = base::TimeTicks::Now() - start_time;
    int codesize = result.code_desc.body_size();
    StdoutStream{} << "Compiled function "
                   << reinterpret_cast<const void*>(env->module) << "#"
                   << compiler_options.func_index << " using Liftoff, took "
                   << time.InMilliseconds() << " ms and "
                   << zone.allocation_size() << " bytes; bodysize "
                   << func_body_size << " codesize " << codesize << std::endl;
  }
  DCHECK(result.succeeded());
  return result;
}
References v8::internal::Zone::allocation_size(), v8::internal::wasm::BasicBlockCalculator::ComputeBasicBlocks(), v8::internal::wasm::LiftoffOptions::counters, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, DCHECK_NOT_NULL, v8::internal::wasm::LiftoffOptions::debug_sidetable, declared_function_index(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Decode(), v8::internal::wasm::LiftoffOptions::detected_features, v8::internal::wasm::CompilationEnv::enabled_features, v8::internal::wasm::FunctionBody::end, v8::internal::wasm::Decoder::failed(), v8::internal::wasm::LiftoffOptions::for_debugging, v8::internal::wasm::LiftoffOptions::func_index, v8::internal::wasm::WasmModule::function_was_validated(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::GetLoweredCallDescriptor(), v8::internal::compiler::GetWasmCallDescriptor(), GetWasmEngine(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::interface(), v8::internal::wasm::LiftoffOptions::is_initialized(), kForDebugging, kLiftoff, kNumBailoutReasons, v8::internal::wasm::LiftoffOptions::max_steps, v8::internal::wasm::CompilationEnv::module, v8::internal::wasm::CompilationEnv::module_coverage_data, v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::NewLiftoffAssemblerBuffer(), v8::base::TimeTicks::Now(), v8::internal::wasm::WasmModule::num_imported_functions, v8::base::internal::result, v8::internal::wasm::FunctionBody::sig, v8::internal::wasm::FunctionBody::start, v8::internal::time, TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT2, v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by v8::internal::wasm::WasmCompilationUnit::ExecuteCompilation(), and v8::internal::wasm::DebugInfoImpl::RecompileLiftoffWithBreakpoints().
ExecutionTierToString()
const char* v8::internal::wasm::ExecutionTierToString (ExecutionTier tier) [inline]
Definition at line 28 of file wasm-tier.h.
                                                             {
  switch (tier) {
    case ExecutionTier::kTurbofan:
      return "turbofan";
    case ExecutionTier::kLiftoff:
      return "liftoff";
#if V8_ENABLE_DRUMBRAKE
    case ExecutionTier::kInterpreter:
      return "interpreter";
#endif // V8_ENABLE_DRUMBRAKE
    case ExecutionTier::kNone:
      return "none";
  }
}
References kLiftoff, kNone, and kTurbofan.
Referenced by v8::internal::wasm::WasmCompilationUnit::ExecuteCompilation(), and v8::internal::RUNTIME_FUNCTION().
expand()
template<size_t N>
constexpr const SimdShuffle::ShuffleArray v8::internal::wasm::expand (const std::array< uint8_t, N > in) [constexpr]
Definition at line 17 of file simd-shuffle.cc.
                                   {
  SimdShuffle::ShuffleArray res{};
  constexpr size_t lane_bytes = 16 / N;
  for (unsigned i = 0; i < N; ++i) {
    for (unsigned j = 0; j < lane_bytes; ++j) {
      res[i * lane_bytes + j] = lane_bytes * in[i] + j;
    }
  }
  return res;
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::N.
ExternalKindName()
const char* v8::internal::wasm::ExternalKindName (ImportExportKindCode kind) [inline]
Definition at line 42 of file module-decoder-impl.h.
                                                               {
  switch (kind) {
    case kExternalFunction:
      return "function";
    case kExternalTable:
      return "table";
    case kExternalMemory:
      return "memory";
    case kExternalGlobal:
      return "global";
    case kExternalTag:
      return "tag";
  }
  return "unknown";
}
References kExternalFunction, kExternalGlobal, kExternalMemory, kExternalTable, and kExternalTag.
Referenced by v8::internal::wasm::ModuleDecoderImpl::DecodeExportSection(), and v8::internal::wasm::ModuleDecoderImpl::DecodeImportSection().
f16_abs()
Float16 v8::internal::wasm::f16_abs (Float16 a)
Definition at line 413 of file wasm-external-refs.cc.
                           {
  return Float16::FromFloat32(std::abs(a.ToFloat32()));
}
References v8::internal::Float16::FromFloat32(), and v8::internal::Float16::ToFloat32().
f16_add()
Float16 v8::internal::wasm::f16_add (Float16 a, Float16 b)
Definition at line 510 of file wasm-external-refs.cc.
                                      {
  return Float16::FromFloat32(a.ToFloat32() + b.ToFloat32());
}
References v8::internal::Float16::FromFloat32(), and v8::internal::Float16::ToFloat32().
f16_ceil()
Float16 v8::internal::wasm::f16_ceil (Float16 a)
Definition at line 435 of file wasm-external-refs.cc.
                            {
  return Float16::FromFloat32(ceilf(a.ToFloat32()));
}
References v8::internal::Float16::FromFloat32(), and v8::internal::Float16::ToFloat32().
f16_div()
Float16 v8::internal::wasm::f16_div (Float16 a, Float16 b)
Definition at line 534 of file wasm-external-refs.cc.
                                      {
  return Float16::FromFloat32(base::Divide(a.ToFloat32(), b.ToFloat32()));
}
References v8::base::Divide(), v8::internal::Float16::FromFloat32(), and v8::internal::Float16::ToFloat32().
f16_eq()
int16_t v8::internal::wasm::f16_eq (Float16 a, Float16 b)
Definition at line 478 of file wasm-external-refs.cc.
                                     {
  return a.ToFloat32() == b.ToFloat32() ? -1 : 0;
}
References v8::internal::Float16::ToFloat32().
f16_floor()
Float16 v8::internal::wasm::f16_floor (Float16 a)
Definition at line 443 of file wasm-external-refs.cc.
                             {
  return Float16::FromFloat32(floorf(a.ToFloat32()));
}
References v8::internal::Float16::FromFloat32(), and v8::internal::Float16::ToFloat32().
f16_le()
int16_t v8::internal::wasm::f16_le (Float16 a, Float16 b)
Definition at line 502 of file wasm-external-refs.cc.
                                     {
  return a.ToFloat32() <= b.ToFloat32() ? -1 : 0;
}
References v8::internal::Float16::ToFloat32().
f16_lt()
int16_t v8::internal::wasm::f16_lt (Float16 a, Float16 b)
Definition at line 494 of file wasm-external-refs.cc.
                                     {
  return a.ToFloat32() < b.ToFloat32() ? -1 : 0;
}
References v8::internal::Float16::ToFloat32().
f16_max()
Float16 v8::internal::wasm::f16_max (Float16 a, Float16 b)
Definition at line 550 of file wasm-external-refs.cc.
                                      {
  return Float16::FromFloat32(JSMax(a.ToFloat32(), b.ToFloat32()));
}
References v8::internal::Float16::FromFloat32(), v8::internal::JSMax(), and v8::internal::Float16::ToFloat32().
f16_min()
Float16 v8::internal::wasm::f16_min (Float16 a, Float16 b)
Definition at line 542 of file wasm-external-refs.cc.
                                      {
  return Float16::FromFloat32(JSMin(a.ToFloat32(), b.ToFloat32()));
}
References v8::internal::Float16::FromFloat32(), v8::internal::JSMin(), and v8::internal::Float16::ToFloat32().
f16_mul()
Float16 v8::internal::wasm::f16_mul (Float16 a, Float16 b)
Definition at line 526 of file wasm-external-refs.cc.
                                      {
  return Float16::FromFloat32(a.ToFloat32() * b.ToFloat32());
}
References v8::internal::Float16::FromFloat32(), and v8::internal::Float16::ToFloat32().
f16_ne()
int16_t v8::internal::wasm::f16_ne (Float16 a, Float16 b)
Definition at line 486 of file wasm-external-refs.cc.
                                     {
  return a.ToFloat32() != b.ToFloat32() ? -1 : 0;
}
References v8::internal::Float16::ToFloat32().
f16_nearest_int()
Float16 v8::internal::wasm::f16_nearest_int (Float16 a)
Definition at line 459 of file wasm-external-refs.cc.
                                   {
  return Float16::FromFloat32(nearbyintf(a.ToFloat32()));
}
References v8::internal::Float16::FromFloat32(), and v8::internal::Float16::ToFloat32().
f16_neg()
Float16 v8::internal::wasm::f16_neg (Float16 a)
Definition at line 421 of file wasm-external-refs.cc.
{ return Float16::FromFloat32(-(a.ToFloat32())); }
References v8::internal::Float16::FromFloat32(), and v8::internal::Float16::ToFloat32().
f16_pmax()
Float16 v8::internal::wasm::f16_pmax (Float16 a, Float16 b)
Definition at line 566 of file wasm-external-refs.cc.
                                       {
  return Float16::FromFloat32(std::max(a.ToFloat32(), b.ToFloat32()));
}
References v8::internal::Float16::FromFloat32(), and v8::internal::Float16::ToFloat32().
f16_pmin()
Float16 v8::internal::wasm::f16_pmin (Float16 a, Float16 b)
Definition at line 558 of file wasm-external-refs.cc.
                                       {
  return Float16::FromFloat32(std::min(a.ToFloat32(), b.ToFloat32()));
}
References v8::internal::Float16::FromFloat32(), and v8::internal::Float16::ToFloat32().
f16_sqrt()
Float16 v8::internal::wasm::f16_sqrt (Float16 a)
Definition at line 427 of file wasm-external-refs.cc.
                            {
  return Float16::FromFloat32(std::sqrt(a.ToFloat32()));
}
References v8::internal::Float16::FromFloat32(), and v8::internal::Float16::ToFloat32().
f16_sub()
Float16 v8::internal::wasm::f16_sub (Float16 a, Float16 b)
Definition at line 518 of file wasm-external-refs.cc.
                                      {
  return Float16::FromFloat32(a.ToFloat32() - b.ToFloat32());
}
References v8::internal::Float16::FromFloat32(), and v8::internal::Float16::ToFloat32().
f16_trunc()
Float16 v8::internal::wasm::f16_trunc (Float16 a)
Definition at line 451 of file wasm-external-refs.cc.
                             {
  return Float16::FromFloat32(truncf(a.ToFloat32()));
}
References v8::internal::Float16::FromFloat32(), and v8::internal::Float16::ToFloat32().
f16x8_abs_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::f16x8_abs_wrapper (Address data)
Definition at line 417 of file wasm-external-refs.cc.
                                     {
  simd_float_round_wrapper<Float16, &f16_abs>(data);
}
f16x8_add_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::f16x8_add_wrapper (Address data)
Definition at line 514 of file wasm-external-refs.cc.
                                     {
  simd_float16_bin_wrapper<Float16, &f16_add>(data);
}
f16x8_ceil_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::f16x8_ceil_wrapper (Address data)
Definition at line 439 of file wasm-external-refs.cc.
                                      {
  simd_float_round_wrapper<Float16, &f16_ceil>(data);
}
f16x8_demote_f32x4_zero_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::f16x8_demote_f32x4_zero_wrapper (Address data)
Definition at line 634 of file wasm-external-refs.cc.
                                                   {
#if V8_TARGET_BIG_ENDIAN
  for (int i = 3, j = 7; i >= 0; i--, j--) {
    float input = ReadUnalignedValue<float>(data + (i * sizeof(float)));
    Float16::FromFloat32(input).Write(data + (j * sizeof(Float16)));
  }
  for (int i = 0; i < 4; i++) {
    WriteUnalignedValue<Float16>(data + (i * sizeof(Float16)),
                                 Float16::FromFloat32(0));
  }
#else
  for (int i = 0; i < 4; i++) {
    float input = ReadUnalignedValue<float>(data + (i * sizeof(float)));
    Float16::FromFloat32(input).Write(data + (i * sizeof(Float16)));
  }
  for (int i = 4; i < 8; i++) {
    WriteUnalignedValue<Float16>(data + (i * sizeof(Float16)),
                                 Float16::FromFloat32(0));
  }
#endif
}
References v8::internal::Float16::FromFloat32(), and v8::internal::Float16::Write().
f16x8_demote_f64x2_zero_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::f16x8_demote_f64x2_zero_wrapper (Address data)
Definition at line 656 of file wasm-external-refs.cc.
                                                   {
#if V8_TARGET_BIG_ENDIAN
  for (int i = 1, j = 7; i >= 0; i--, j--) {
    double input = ReadUnalignedValue<double>(data + (i * sizeof(double)));
    WriteUnalignedValue<uint16_t>(data + (j * sizeof(uint16_t)),
                                  DoubleToFloat16(input));
  }
  for (int i = 0; i < 6; i++) {
    WriteUnalignedValue<Float16>(data + (i * sizeof(Float16)),
                                 Float16::FromFloat32(0));
  }
#else
  for (int i = 0; i < 2; i++) {
    double input = ReadUnalignedValue<double>(data + (i * sizeof(double)));
    WriteUnalignedValue<uint16_t>(data + (i * sizeof(uint16_t)),
                                  DoubleToFloat16(input));
  }
  for (int i = 2; i < 8; i++) {
    WriteUnalignedValue<Float16>(data + (i * sizeof(Float16)),
                                 Float16::FromFloat32(0));
  }
#endif
}
References v8::internal::DoubleToFloat16(), and v8::internal::Float16::FromFloat32().
f16x8_div_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::f16x8_div_wrapper (Address data)
Definition at line 538 of file wasm-external-refs.cc.
                                     {
  simd_float16_bin_wrapper<Float16, &f16_div>(data);
}
f16x8_eq_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::f16x8_eq_wrapper (Address data)
Definition at line 482 of file wasm-external-refs.cc.
                                    {
  simd_float16_bin_wrapper<int16_t, &f16_eq>(data);
}
f16x8_floor_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::f16x8_floor_wrapper (Address data)
Definition at line 447 of file wasm-external-refs.cc.
                                       {
  simd_float_round_wrapper<Float16, &f16_floor>(data);
}
f16x8_le_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::f16x8_le_wrapper (Address data)
Definition at line 506 of file wasm-external-refs.cc.
                                    {
  simd_float16_bin_wrapper<int16_t, &f16_le>(data);
}
f16x8_lt_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::f16x8_lt_wrapper (Address data)
Definition at line 498 of file wasm-external-refs.cc.
                                    {
  simd_float16_bin_wrapper<int16_t, &f16_lt>(data);
}
f16x8_max_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::f16x8_max_wrapper (Address data)
Definition at line 554 of file wasm-external-refs.cc.
                                     {
  simd_float16_bin_wrapper<Float16, &f16_max>(data);
}
f16x8_min_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::f16x8_min_wrapper (Address data)
Definition at line 546 of file wasm-external-refs.cc.
                                     {
  simd_float16_bin_wrapper<Float16, &f16_min>(data);
}
f16x8_mul_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::f16x8_mul_wrapper (Address data)
Definition at line 530 of file wasm-external-refs.cc.
                                     {
  simd_float16_bin_wrapper<Float16, &f16_mul>(data);
}
f16x8_ne_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::f16x8_ne_wrapper (Address data)
Definition at line 490 of file wasm-external-refs.cc.
                                    {
  simd_float16_bin_wrapper<int16_t, &f16_ne>(data);
}
f16x8_nearest_int_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::f16x8_nearest_int_wrapper (Address data)
Definition at line 463 of file wasm-external-refs.cc.
                                             {
  simd_float_round_wrapper<Float16, &f16_nearest_int>(data);
}
f16x8_neg_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::f16x8_neg_wrapper (Address data)
Definition at line 423 of file wasm-external-refs.cc.
                                     {
  simd_float_round_wrapper<Float16, &f16_neg>(data);
}
f16x8_pmax_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::f16x8_pmax_wrapper (Address data)
Definition at line 570 of file wasm-external-refs.cc.
                                      {
  simd_float16_bin_wrapper<Float16, &f16_pmax>(data);
}
f16x8_pmin_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::f16x8_pmin_wrapper (Address data)
Definition at line 562 of file wasm-external-refs.cc.
                                      {
  simd_float16_bin_wrapper<Float16, &f16_pmin>(data);
}
f16x8_qfma_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::f16x8_qfma_wrapper (Address data)
Definition at line 695 of file wasm-external-refs.cc.
                                      {
  return simd_float16_fma_wrapper<&Qfma>(data);
}
f16x8_qfms_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::f16x8_qfms_wrapper (Address data)
Definition at line 701 of file wasm-external-refs.cc.
                                      {
  return simd_float16_fma_wrapper<&Qfms>(data);
}
f16x8_sconvert_i16x8_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::f16x8_sconvert_i16x8_wrapper (Address data)
Definition at line 610 of file wasm-external-refs.cc.
                                                {
  simd_float_un_wrapper<int16_t, Float16, &ConvertToF16S>(data);
}
f16x8_sqrt_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::f16x8_sqrt_wrapper (Address data)
Definition at line 431 of file wasm-external-refs.cc.
                                      {
  simd_float_round_wrapper<Float16, &f16_sqrt>(data);
}
f16x8_sub_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::f16x8_sub_wrapper (Address data)
Definition at line 522 of file wasm-external-refs.cc.
                                     {
  simd_float16_bin_wrapper<Float16, &f16_sub>(data);
}
f16x8_trunc_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::f16x8_trunc_wrapper (Address data)
Definition at line 455 of file wasm-external-refs.cc.
                                       {
  simd_float_round_wrapper<Float16, &f16_trunc>(data);
}
f16x8_uconvert_i16x8_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::f16x8_uconvert_i16x8_wrapper (Address data)
Definition at line 616 of file wasm-external-refs.cc.
                                                {
  simd_float_un_wrapper<uint16_t, Float16, &ConvertToF16U>(data);
}
F16x8BinOpViaF32()
template<void(Assembler::*)(YMMRegister, YMMRegister, YMMRegister) avx_op>
bool v8::internal::wasm::F16x8BinOpViaF32 (LiftoffAssembler * assm, LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
Definition at line 4521 of file liftoff-assembler-x64-inl.h.
                                                                {
  if (!CpuFeatures::IsSupported(F16C) || !CpuFeatures::IsSupported(AVX)) {
    return false;
  }
  CpuFeatureScope f16c_scope(assm, F16C);
  CpuFeatureScope avx_scope(assm, AVX);
  static constexpr RegClass res_rc = reg_class_for(kS128);
  LiftoffRegister tmp =
      assm->GetUnusedRegister(res_rc, LiftoffRegList{dst, lhs, rhs});
  YMMRegister ytmp = YMMRegister::from_code(tmp.fp().code());
  YMMRegister ydst = YMMRegister::from_code(dst.fp().code());
  // dst can overlap with rhs or lhs, so cannot be used as temporary reg.
  assm->vcvtph2ps(ytmp, lhs.fp());
  assm->vcvtph2ps(kScratchSimd256Reg, rhs.fp());
  (assm->*avx_op)(ydst, ytmp, kScratchSimd256Reg);
  assm->vcvtps2ph(dst.fp(), ydst, 0);
  return true;
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::wasm::LiftoffRegister::fp(), v8::internal::YMMRegister::from_code(), v8::internal::wasm::LiftoffAssembler::GetUnusedRegister(), v8::internal::CpuFeatures::IsSupported(), v8::internal::kS128, v8::internal::kScratchSimd256Reg, reg_class_for(), v8::internal::Assembler::vcvtph2ps(), and v8::internal::Assembler::vcvtps2ph().
F16x8CmpOpViaF32()
template<void(Assembler::*)(YMMRegister, YMMRegister, YMMRegister) avx_op>
bool v8::internal::wasm::F16x8CmpOpViaF32 (LiftoffAssembler * assm, LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
Definition at line 4483 of file liftoff-assembler-x64-inl.h.
                                                                {
  if (!CpuFeatures::IsSupported(F16C) || !CpuFeatures::IsSupported(AVX) ||
      !CpuFeatures::IsSupported(AVX2)) {
    return false;
  }
  CpuFeatureScope f16c_scope(assm, F16C);
  CpuFeatureScope avx_scope(assm, AVX);
  CpuFeatureScope avx2_scope(assm, AVX2);
  YMMRegister ydst = YMMRegister::from_code(dst.fp().code());
  assm->vcvtph2ps(ydst, lhs.fp());
  assm->vcvtph2ps(kScratchSimd256Reg, rhs.fp());
  (assm->*avx_op)(ydst, ydst, kScratchSimd256Reg);
  assm->vpackssdw(ydst, ydst, ydst);
  return true;
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::wasm::LiftoffRegister::fp(), v8::internal::YMMRegister::from_code(), v8::internal::CpuFeatures::IsSupported(), v8::internal::kScratchSimd256Reg, and v8::internal::Assembler::vcvtph2ps().
f32_ceil_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::f32_ceil_wrapper (Address data)
Definition at line 58 of file wasm-external-refs.cc.
                                    {
  WriteUnalignedValue<float>(data, ceilf(ReadUnalignedValue<float>(data)));
}
f32_floor_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::f32_floor_wrapper (Address data)
Definition at line 54 of file wasm-external-refs.cc.
                                     {
  WriteUnalignedValue<float>(data, floorf(ReadUnalignedValue<float>(data)));
}
f32_nearest_int_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::f32_nearest_int_wrapper (Address data)
Definition at line 62 of file wasm-external-refs.cc.
                                           {
  float input = ReadUnalignedValue<float>(data);
  float value = nearbyintf(input);
#if V8_OS_AIX
  value = FpOpWorkaround<float>(input, value);
#endif
  WriteUnalignedValue<float>(data, value);
}
References v8::internal::value.
f32_trunc_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::f32_trunc_wrapper (Address data)
Definition at line 50 of file wasm-external-refs.cc.
                                     {
  WriteUnalignedValue<float>(data, truncf(ReadUnalignedValue<float>(data)));
}
f32x4_ceil_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::f32x4_ceil_wrapper (Address data)
Definition at line 397 of file wasm-external-refs.cc.
                                      {
  simd_float_round_wrapper<float, &ceilf>(data);
}
f32x4_floor_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::f32x4_floor_wrapper (Address data)
Definition at line 401 of file wasm-external-refs.cc.
                                       {
  simd_float_round_wrapper<float, &floorf>(data);
}
f32x4_nearest_int_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::f32x4_nearest_int_wrapper (Address data)
Definition at line 409 of file wasm-external-refs.cc.
                                             {
  simd_float_round_wrapper<float, &nearbyintf>(data);
}
f32x4_promote_low_f16x8_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::f32x4_promote_low_f16x8_wrapper (Address data)
Definition at line 620 of file wasm-external-refs.cc.
                                                   {
  // Result is stored in the same buffer, so read all values to local
  // stack variables first.
  Float16 a = Float16::Read(data);
  Float16 b = Float16::Read(data + sizeof(Float16));
  Float16 c = Float16::Read(data + 2 * sizeof(Float16));
  Float16 d = Float16::Read(data + 3 * sizeof(Float16));
  WriteUnalignedValue<float>(data, a.ToFloat32());
  WriteUnalignedValue<float>(data + sizeof(float), b.ToFloat32());
  WriteUnalignedValue<float>(data + (2 * sizeof(float)), c.ToFloat32());
  WriteUnalignedValue<float>(data + (3 * sizeof(float)), d.ToFloat32());
}
References v8::internal::Float16::Read(), and v8::internal::Float16::ToFloat32().
f32x4_trunc_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::f32x4_trunc_wrapper (Address data)
Definition at line 405 of file wasm-external-refs.cc.
                                       {
  simd_float_round_wrapper<float, &truncf>(data);
}
f64_ceil_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::f64_ceil_wrapper (Address data)
Definition at line 79 of file wasm-external-refs.cc.
                                    {
  WriteUnalignedValue<double>(data, ceil(ReadUnalignedValue<double>(data)));
}
f64_floor_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::f64_floor_wrapper (Address data)
Definition at line 75 of file wasm-external-refs.cc.
                                     {
  WriteUnalignedValue<double>(data, floor(ReadUnalignedValue<double>(data)));
}
f64_nearest_int_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::f64_nearest_int_wrapper (Address data)
Definition at line 83 of file wasm-external-refs.cc.
                                           {
  double input = ReadUnalignedValue<double>(data);
  double value = nearbyint(input);
#if V8_OS_AIX
  value = FpOpWorkaround<double>(input, value);
#endif
  WriteUnalignedValue<double>(data, value);
}
References v8::internal::value.
f64_trunc_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::f64_trunc_wrapper (Address data)
Definition at line 71 of file wasm-external-refs.cc.
                                     {
  WriteUnalignedValue<double>(data, trunc(ReadUnalignedValue<double>(data)));
}
f64x2_ceil_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::f64x2_ceil_wrapper (Address data)
Definition at line 381 of file wasm-external-refs.cc.
                                      {
  simd_float_round_wrapper<double, &ceil>(data);
}
f64x2_floor_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::f64x2_floor_wrapper (Address data)
Definition at line 385 of file wasm-external-refs.cc.
                                       {
  simd_float_round_wrapper<double, &floor>(data);
}
f64x2_nearest_int_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::f64x2_nearest_int_wrapper (Address data)
Definition at line 393 of file wasm-external-refs.cc.
                                             {
  simd_float_round_wrapper<double, &nearbyint>(data);
}
f64x2_trunc_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::f64x2_trunc_wrapper (Address data)
Definition at line 389 of file wasm-external-refs.cc.
                                       {
  simd_float_round_wrapper<double, &trunc>(data);
}
flat_string_to_f64()
double v8::internal::wasm::flat_string_to_f64 (Address string_address)
Definition at line 980 of file wasm-external-refs.cc.
                                                  {
  Tagged<String> s = Cast<String>(Tagged<Object>(string_address));
  return FlatStringToDouble(s, ALLOW_TRAILING_JUNK,
                            std::numeric_limits<double>::quiet_NaN());
}
References v8::internal::ALLOW_TRAILING_JUNK, and v8::internal::FlatStringToDouble().
Flip()
constexpr Condition v8::internal::wasm::Flip (Condition cond) [inline], [constexpr]
Definition at line 57 of file liftoff-assembler.h.
                                                {
  switch (cond) {
    case kEqual:
      return kEqual;
    case kNotEqual:
      return kNotEqual;
    case kLessThan:
      return kGreaterThan;
    case kLessThanEqual:
      return kGreaterThanEqual;
    case kGreaterThanEqual:
      return kLessThanEqual;
    case kGreaterThan:
      return kLessThan;
    case kUnsignedLessThan:
      return kUnsignedGreaterThan;
    case kUnsignedLessThanEqual:
      return kUnsignedGreaterThanEqual;
    case kUnsignedGreaterThanEqual:
      return kUnsignedLessThanEqual;
    case kUnsignedGreaterThan:
      return kUnsignedLessThan;
    default:
      UNREACHABLE();
  }
}
References v8::internal::kEqual, v8::internal::kGreaterThan, v8::internal::kGreaterThanEqual, v8::internal::kLessThan, v8::internal::kLessThanEqual, v8::internal::kNotEqual, v8::internal::kUnsignedGreaterThan, v8::internal::kUnsignedGreaterThanEqual, v8::internal::kUnsignedLessThan, v8::internal::kUnsignedLessThanEqual, and v8::internal::UNREACHABLE().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::JumpIfFalse().
float16_to_float32_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::float16_to_float32_wrapper (Address data)
Definition at line 291 of file wasm-external-refs.cc.
                                              {
  WriteUnalignedValue<float>(data, Float16::Read(data).ToFloat32());
}
References v8::internal::Float16::Read().
float32_to_float16_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::float32_to_float16_wrapper (Address data)
Definition at line 295 of file wasm-external-refs.cc.
                                              {
  Float16::FromFloat32(ReadUnalignedValue<float>(data)).Write(data);
}
References v8::internal::Float16::FromFloat32(), and v8::internal::Float16::Write().
float32_to_int64_sat_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::float32_to_int64_sat_wrapper (Address data)
Definition at line 231 of file wasm-external-refs.cc.
                                                {
  float input = ReadUnalignedValue<float>(data);
  if (base::IsValueInRangeForNumericType<int64_t>(input)) {
    WriteUnalignedValue<int64_t>(data, static_cast<int64_t>(input));
    return;
  }
  if (std::isnan(input)) {
    WriteUnalignedValue<int64_t>(data, 0);
    return;
  }
  if (input < 0.0) {
    WriteUnalignedValue<int64_t>(data, std::numeric_limits<int64_t>::min());
    return;
  }
  WriteUnalignedValue<int64_t>(data, std::numeric_limits<int64_t>::max());
}
float32_to_int64_wrapper()
V8_EXPORT_PRIVATE int32_t v8::internal::wasm::float32_to_int64_wrapper (Address data)
Definition at line 195 of file wasm-external-refs.cc.
                                               {
  float input = ReadUnalignedValue<float>(data);
  if (base::IsValueInRangeForNumericType<int64_t>(input)) {
    WriteUnalignedValue<int64_t>(data, static_cast<int64_t>(input));
    return 1;
  }
  return 0;
}
float32_to_uint64_sat_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::float32_to_uint64_sat_wrapper (Address data)
Definition at line 248 of file wasm-external-refs.cc.
                                                 {
  float input = ReadUnalignedValue<float>(data);
  if (base::IsValueInRangeForNumericType<uint64_t>(input)) {
    WriteUnalignedValue<uint64_t>(data, static_cast<uint64_t>(input));
    return;
  }
  if (input >= static_cast<float>(std::numeric_limits<uint64_t>::max())) {
    WriteUnalignedValue<uint64_t>(data, std::numeric_limits<uint64_t>::max());
    return;
  }
  WriteUnalignedValue<uint64_t>(data, 0);
}
float32_to_uint64_wrapper()
V8_EXPORT_PRIVATE int32_t v8::internal::wasm::float32_to_uint64_wrapper (Address data)
Definition at line 204 of file wasm-external-refs.cc.
                                                {
  float input = ReadUnalignedValue<float>(data);
  if (base::IsValueInRangeForNumericType<uint64_t>(input)) {
    WriteUnalignedValue<uint64_t>(data, static_cast<uint64_t>(input));
    return 1;
  }
  return 0;
}
float64_pow_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::float64_pow_wrapper (Address data)
Definition at line 362 of file wasm-external-refs.cc.
                                       {
  double x = ReadUnalignedValue<double>(data);
  double y = ReadUnalignedValue<double>(data + sizeof(x));
  WriteUnalignedValue<double>(data, math::pow(x, y));
}
References v8::internal::math::pow(), and v8::internal::y.
float64_to_int64_sat_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::float64_to_int64_sat_wrapper (Address data)
Definition at line 261 of file wasm-external-refs.cc.
                                                {
  double input = ReadUnalignedValue<double>(data);
  if (base::IsValueInRangeForNumericType<int64_t>(input)) {
    WriteUnalignedValue<int64_t>(data, static_cast<int64_t>(input));
    return;
  }
  if (std::isnan(input)) {
    WriteUnalignedValue<int64_t>(data, 0);
    return;
  }
  if (input < 0.0) {
    WriteUnalignedValue<int64_t>(data, std::numeric_limits<int64_t>::min());
    return;
  }
  WriteUnalignedValue<int64_t>(data, std::numeric_limits<int64_t>::max());
}
float64_to_int64_wrapper()
V8_EXPORT_PRIVATE int32_t v8::internal::wasm::float64_to_int64_wrapper (Address data)
Definition at line 213 of file wasm-external-refs.cc.
                                               {
  double input = ReadUnalignedValue<double>(data);
  if (base::IsValueInRangeForNumericType<int64_t>(input)) {
    WriteUnalignedValue<int64_t>(data, static_cast<int64_t>(input));
    return 1;
  }
  return 0;
}
float64_to_uint64_sat_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::float64_to_uint64_sat_wrapper (Address data)
Definition at line 278 of file wasm-external-refs.cc.
                                                 {
  double input = ReadUnalignedValue<double>(data);
  if (base::IsValueInRangeForNumericType<uint64_t>(input)) {
    WriteUnalignedValue<uint64_t>(data, static_cast<uint64_t>(input));
    return;
  }
  if (input >= static_cast<double>(std::numeric_limits<uint64_t>::max())) {
    WriteUnalignedValue<uint64_t>(data, std::numeric_limits<uint64_t>::max());
    return;
  }
  WriteUnalignedValue<uint64_t>(data, 0);
}
float64_to_uint64_wrapper()
V8_EXPORT_PRIVATE int32_t v8::internal::wasm::float64_to_uint64_wrapper (Address data)
Definition at line 222 of file wasm-external-refs.cc.
                                                {
  double input = ReadUnalignedValue<double>(data);
  if (base::IsValueInRangeForNumericType<uint64_t>(input)) {
    WriteUnalignedValue<uint64_t>(data, static_cast<uint64_t>(input));
    return 1;
  }
  return 0;
}
GenerateLiftoffDebugSideTable()
V8_EXPORT_PRIVATE std::unique_ptr< DebugSideTable > v8::internal::wasm::GenerateLiftoffDebugSideTable (const WasmCode * code)
Definition at line 10637 of file liftoff-compiler.cc.
                          {
  auto* native_module = code->native_module();
  auto* function = &native_module->module()->functions[code->index()];
  ModuleWireBytes wire_bytes{native_module->wire_bytes()};
  base::Vector<const uint8_t> function_bytes =
      wire_bytes.GetFunctionBytes(function);
  CompilationEnv env = CompilationEnv::ForModule(native_module);
  bool is_shared = native_module->module()->type(function->sig_index).is_shared;
  FunctionBody func_body{function->sig, 0, function_bytes.begin(),
                         function_bytes.end(), is_shared};
  Zone zone(GetWasmEngine()->allocator(), "LiftoffDebugSideTableZone");
  auto call_descriptor = compiler::GetWasmCallDescriptor(&zone, function->sig);
  DebugSideTableBuilder debug_sidetable_builder;
  WasmDetectedFeatures detected;
  constexpr int kSteppingBreakpoints[] = {0};
  DCHECK(code->for_debugging() == kForDebugging ||
         code->for_debugging() == kForStepping);
  base::Vector<const int> breakpoints =
      code->for_debugging() == kForStepping
          ? base::ArrayVector(kSteppingBreakpoints)
          : base::Vector<const int>{};
  WasmFullDecoder<Decoder::NoValidationTag, LiftoffCompiler> decoder(
      &zone, native_module->module(), env.enabled_features, &detected,
      func_body, call_descriptor, &env, &zone,
      NewAssemblerBuffer(AssemblerBase::kDefaultBufferSize),
      &debug_sidetable_builder,
      LiftoffOptions{}
          .set_func_index(code->index())
          .set_for_debugging(code->for_debugging())
          .set_breakpoints(breakpoints),
      nullptr);
  decoder.Decode();
  DCHECK(decoder.ok());
  DCHECK(!decoder.interface().did_bailout());
  return debug_sidetable_builder.GenerateDebugSideTable();
}
References v8::base::ArrayVector(), v8::base::Vector< T >::begin(), code, v8::internal::DCHECK(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Decode(), v8::internal::wasm::CompilationEnv::enabled_features, v8::base::Vector< T >::end(), v8::internal::wasm::CompilationEnv::ForModule(), v8::internal::compiler::GetWasmCallDescriptor(), GetWasmEngine(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::interface(), v8::internal::is_shared, v8::internal::AssemblerBase::kDefaultBufferSize, kForDebugging, kForStepping, v8::internal::NewAssemblerBuffer(), v8::internal::wasm::Decoder::ok(), and v8::internal::wasm::FunctionBody::sig.
Referenced by v8::internal::wasm::DebugInfoImpl::GetDebugSideTable().
Get() [1/2]
WireBytesRef v8::internal::wasm::Get (const IndirectNameMap & map, uint32_t outer_index, uint32_t inner_index)
Definition at line 226 of file names-provider.cc.
                                       {
  const NameMap* inner = map.Get(outer_index);
  if (!inner) return {};
  return Get(*inner, inner_index);
}
References Get(), and v8::internal::wasm::AdaptiveMap< Value >::Get().
Get() [2/2]
WireBytesRef v8::internal::wasm::Get (const NameMap & map, uint32_t index)
Definition at line 220 of file names-provider.cc.
                                                     {
  const WireBytesRef* result = map.Get(index);
  if (!result) return {};
  return *result;
}
References v8::internal::wasm::AdaptiveMap< Value >::Get(), v8::internal::index, and v8::base::internal::result.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::AtomicOp(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BoundsCheckMem(), Get(), v8::internal::wasm::TurboshaftGraphBuildingInterface::IsArrayNewSegment(), v8::internal::wasm::NamesProvider::PrintDataSegmentName(), v8::internal::wasm::NamesProvider::PrintElementSegmentName(), v8::internal::wasm::NamesProvider::PrintFieldName(), v8::internal::wasm::NamesProvider::PrintGlobalName(), v8::internal::wasm::NamesProvider::PrintLabelName(), v8::internal::wasm::NamesProvider::PrintLocalName(), v8::internal::wasm::NamesProvider::PrintMemoryName(), v8::internal::wasm::NamesProvider::PrintTableName(), v8::internal::wasm::NamesProvider::PrintTagName(), v8::internal::wasm::NamesProvider::PrintTypeName(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StoreInStackSlot(), and v8::internal::wasm::WasmModuleSourceMap::WasmModuleSourceMap().
GetCacheRegList()
static constexpr LiftoffRegList v8::internal::wasm::GetCacheRegList (RegClass rc) [static], [constexpr]
Definition at line 548 of file liftoff-register.h.
                                                             {
  V8_ASSUME(rc == kFpReg || rc == kGpReg);
  static_assert(kGpReg == 0 && kFpReg == 1);
  constexpr LiftoffRegList kRegLists[2]{kGpCacheRegList, kFpCacheRegList};
  return kRegLists[rc];
}
References kFpCacheRegList, kFpReg, kGpCacheRegList, kGpReg, and V8_ASSUME.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::TempRegisterScope::Acquire(), and v8::internal::wasm::LiftoffAssembler::GetUnusedRegister().
GetCanonicalTypeNamesProvider()
V8_EXPORT_PRIVATE CanonicalTypeNamesProvider * v8::internal::wasm::GetCanonicalTypeNamesProvider ()
Definition at line 2140 of file wasm-engine.cc.
                                                            {
  DCHECK_NOT_NULL(global_wasm_state);
  return &global_wasm_state->type_names_provider;
}
References DCHECK_NOT_NULL, v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::global_wasm_state, and v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::GlobalWasmState::type_names_provider.
Referenced by v8::internal::V8HeapExplorer::AddEntry(), v8::internal::wasm::WasmEngine::EstimateCurrentMemoryConsumption(), v8::internal::StructProxy::GetName(), and v8::internal::anonymous_namespace{debug-wasm-objects.cc}::GetRefTypeName().
GetCodeKind()
WasmCode::Kind v8::internal::wasm::GetCodeKind (const WasmCompilationResult & result)
Definition at line 1470 of file wasm-code-manager.cc.
                                                              {
  switch (result.kind) {
    case WasmCompilationResult::kWasmToJsWrapper:
      return WasmCode::Kind::kWasmToJsWrapper;
#if V8_ENABLE_DRUMBRAKE
    case WasmCompilationResult::kInterpreterEntry:
      return WasmCode::Kind::kInterpreterEntry;
#endif // V8_ENABLE_DRUMBRAKE
    case WasmCompilationResult::kFunction:
      return WasmCode::Kind::kWasmFunction;
    default:
      UNREACHABLE();
  }
}
References v8::internal::wasm::WasmCompilationResult::kFunction, v8::internal::compiler::kWasmFunction, v8::internal::wasm::WasmCompilationResult::kWasmToJsWrapper, v8::base::internal::result, and v8::internal::UNREACHABLE().
Referenced by v8::internal::wasm::NativeModule::AddCompiledCode().
GetContainingWasmFunction()
int v8::internal::wasm::GetContainingWasmFunction (const WasmModule * module, uint32_t byte_offset)
Definition at line 132 of file wasm-module.cc.
                                                                              {
  int func_index = GetNearestWasmFunction(module, byte_offset);
  if (func_index >= 0) {
    // If the found function does not contain the given position, return -1.
    const WasmFunction& func = module->functions[func_index];
    if (byte_offset < func.code.offset() ||
        byte_offset >= func.code.end_offset()) {
      return -1;
    }
  }
  return func_index;
}
References v8::internal::wasm::WasmFunction::code, v8::internal::wasm::WireBytesRef::end_offset(), v8::internal::wasm::WasmModule::functions, GetNearestWasmFunction(), and v8::internal::wasm::WireBytesRef::offset().
Referenced by v8::internal::WasmScript::ClearBreakPoint(), and v8::internal::WasmScript::SetBreakPoint().
GetCustomSections()
DirectHandle< JSArray > v8::internal::wasm::GetCustomSections (Isolate * isolate, DirectHandle< WasmModuleObject > module_object, DirectHandle< String > name, ErrorThrower * thrower)
Definition at line 651 of file wasm-module.cc.
                                                      {
  Factory* factory = isolate->factory();
  base::Vector<const uint8_t> wire_bytes =
      module_object->native_module()->wire_bytes();
  std::vector<CustomSectionOffset> custom_sections =
      DecodeCustomSections(wire_bytes);
  DirectHandleVector<Object> matching_sections(isolate);
  // Gather matching sections.
  for (auto& section : custom_sections) {
    DirectHandle<String> section_name =
        WasmModuleObject::ExtractUtf8StringFromModuleBytes(
            isolate, module_object, section.name, kNoInternalize);
    if (!name->Equals(*section_name)) continue;
    // Make a copy of the payload data in the section.
    size_t size = section.payload.length();
    MaybeDirectHandle<JSArrayBuffer> result =
        isolate->factory()->NewJSArrayBufferAndBackingStore(
            size, InitializedFlag::kUninitialized);
    DirectHandle<JSArrayBuffer> array_buffer;
    if (!result.ToHandle(&array_buffer)) {
      thrower->RangeError("out of memory allocating custom section data");
      return DirectHandle<JSArray>();
    }
    memcpy(array_buffer->backing_store(),
           wire_bytes.begin() + section.payload.offset(),
           section.payload.length());
    matching_sections.push_back(array_buffer);
  }
  int num_custom_sections = static_cast<int>(matching_sections.size());
  DirectHandle<JSArray> array_object =
      factory->NewJSArray(PACKED_ELEMENTS, 0, 0);
  DirectHandle<FixedArray> storage =
      factory->NewFixedArray(num_custom_sections);
  JSArray::SetContent(isolate, array_object, storage);
  DCHECK_EQ(array_object->length(), Smi::FromInt(num_custom_sections));
  for (int i = 0; i < num_custom_sections; i++) {
    storage->set(i, *matching_sections[i]);
  }
  JSObject::ValidateElements(isolate, *array_object);
  return array_object;
}
References v8::base::Vector< T >::begin(), DCHECK_EQ, DecodeCustomSections(), v8::internal::WasmModuleObject::ExtractUtf8StringFromModuleBytes(), v8::internal::Isolate::factory(), v8::internal::Smi::FromInt(), v8::internal::kNoInternalize, v8::internal::kUninitialized, name(), v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::Factory::NewJSArray(), v8::internal::Factory::NewJSArrayBufferAndBackingStore(), v8::internal::PACKED_ELEMENTS, v8::internal::DirectHandleVector< T >::push_back(), v8::base::internal::result, v8::internal::JSArray::SetContent(), v8::internal::DirectHandleVector< T >::size(), size(), and v8::internal::JSObject::ValidateElements().
Referenced by v8::anonymous_namespace{wasm-js.cc}::WebAssemblyModuleCustomSectionsImpl().
GetDefaultAlignment()
uint32_t v8::internal::wasm::GetDefaultAlignment (WasmOpcode opcode)
Definition at line 122 of file wasm-disassembler.cc.
                                                {
  switch (opcode) {
    case kExprS128LoadMem:
    case kExprS128StoreMem:
      return 4;
    case kExprS128Load8x8S:
    case kExprS128Load8x8U:
    case kExprS128Load16x4S:
    case kExprS128Load16x4U:
    case kExprS128Load32x2S:
    case kExprS128Load32x2U:
    case kExprS128Load64Splat:
    case kExprS128Load64Zero:
    case kExprS128Load64Lane:
    case kExprS128Store64Lane:
      return 3;
    case kExprS128Load32Splat:
    case kExprS128Load32Zero:
    case kExprS128Load32Lane:
    case kExprS128Store32Lane:
      return 2;
    case kExprS128Load16Splat:
    case kExprS128Load16Lane:
    case kExprS128Store16Lane:
      return 1;
    case kExprS128Load8Splat:
    case kExprS128Load8Lane:
    case kExprS128Store8Lane:
      return 0;
#define CASE(Opcode, ...) \
  case kExpr##Opcode: \
    return GetLoadType(kExpr##Opcode).size_log_2();
      FOREACH_LOAD_MEM_OPCODE(CASE)
#undef CASE
#define CASE(Opcode, ...) \
  case kExpr##Opcode: \
    return GetStoreType(kExpr##Opcode).size_log_2();
      FOREACH_STORE_MEM_OPCODE(CASE)
#undef CASE
#define CASE(Opcode, Type) \
  case kExpr##Opcode: \
    return ElementSizeLog2Of(MachineType::Type().representation());
      ATOMIC_OP_LIST(CASE)
      ATOMIC_STORE_OP_LIST(CASE)
#undef CASE
    default:
      UNREACHABLE();
  }
}
References ATOMIC_OP_LIST, ATOMIC_STORE_OP_LIST, CASE, FOREACH_LOAD_MEM_OPCODE, FOREACH_STORE_MEM_OPCODE, and v8::internal::UNREACHABLE().
Referenced by v8::internal::wasm::ImmediatesPrinter< ValidationTag >::MemoryAccess().
GetExports()
DirectHandle< JSArray > v8::internal::wasm::GetExports (Isolate * isolate, DirectHandle< WasmModuleObject > module_object)
Definition at line 553 of file wasm-module.cc.
                                                                               {
  auto enabled_features = i::wasm::WasmEnabledFeatures::FromIsolate(isolate);
  Factory* factory = isolate->factory();
  DirectHandle<String> name_string = factory->name_string();
  DirectHandle<String> kind_string = factory->InternalizeUtf8String("kind");
  DirectHandle<String> type_string = factory->InternalizeUtf8String("type");
  DirectHandle<String> function_string = factory->function_string();
  DirectHandle<String> table_string = factory->InternalizeUtf8String("table");
  DirectHandle<String> memory_string = factory->InternalizeUtf8String("memory");
  DirectHandle<String> global_string = factory->global_string();
  DirectHandle<String> tag_string = factory->InternalizeUtf8String("tag");
  // Create the result array.
  const WasmModule* module = module_object->module();
  int num_exports = static_cast<int>(module->export_table.size());
  DirectHandle<JSArray> array_object =
      factory->NewJSArray(PACKED_ELEMENTS, 0, 0);
  DirectHandle<FixedArray> storage = factory->NewFixedArray(num_exports);
  JSArray::SetContent(isolate, array_object, storage);
  DCHECK_EQ(array_object->length(), Smi::FromInt(num_exports));
  DirectHandle<JSFunction> object_function = DirectHandle<JSFunction>(
      isolate->native_context()->object_function(), isolate);
  // Populate the result array.
  for (int index = 0; index < num_exports; ++index) {
    const WasmExport& exp = module->export_table[index];
    DirectHandle<String> export_kind;
    DirectHandle<JSObject> type_value;
    switch (exp.kind) {
      case kExternalFunction:
        if (enabled_features.has_type_reflection()) {
          auto& func = module->functions[exp.index];
          type_value = GetTypeForFunction(isolate, func.sig);
        }
        export_kind = function_string;
        break;
      case kExternalTable:
        if (enabled_features.has_type_reflection()) {
          auto& table = module->tables[exp.index];
          std::optional<uint32_t> maximum_size;
          if (table.has_maximum_size) maximum_size.emplace(table.maximum_size);
          type_value = GetTypeForTable(isolate, table.type, table.initial_size,
                                       maximum_size, table.address_type);
        }
        export_kind = table_string;
        break;
      case kExternalMemory:
        if (enabled_features.has_type_reflection()) {
          auto& memory = module->memories[exp.index];
          std::optional<uint32_t> maximum_size;
          if (memory.has_maximum_pages) {
            maximum_size.emplace(memory.maximum_pages);
          }
          type_value =
              GetTypeForMemory(isolate, memory.initial_pages, maximum_size,
                               memory.is_shared, memory.address_type);
        }
        export_kind = memory_string;
        break;
      case kExternalGlobal:
        if (enabled_features.has_type_reflection()) {
          auto& global = module->globals[exp.index];
          type_value =
              GetTypeForGlobal(isolate, global.mutability, global.type);
        }
        export_kind = global_string;
        break;
      case kExternalTag:
        export_kind = tag_string;
        break;
      default:
        UNREACHABLE();
    }
    DirectHandle<JSObject> entry = factory->NewJSObject(object_function);
    DirectHandle<String> export_name =
        WasmModuleObject::ExtractUtf8StringFromModuleBytes(
            isolate, module_object, exp.name, kNoInternalize);
    JSObject::AddProperty(isolate, entry, name_string, export_name, NONE);
    JSObject::AddProperty(isolate, entry, kind_string, export_kind, NONE);
    if (!type_value.is_null()) {
      JSObject::AddProperty(isolate, entry, type_string, type_value, NONE);
    }
    storage->set(index, *entry);
  }
  JSObject::ValidateElements(isolate, *array_object);
  return array_object;
}
References v8::internal::JSObject::AddProperty(), DCHECK_EQ, v8::base::ieee754::exp(), v8::internal::wasm::WasmModule::export_table, v8::internal::WasmModuleObject::ExtractUtf8StringFromModuleBytes(), v8::internal::Isolate::factory(), v8::internal::Smi::FromInt(), v8::internal::wasm::WasmModule::functions, GetTypeForFunction(), GetTypeForGlobal(), GetTypeForMemory(), GetTypeForTable(), v8::internal::wasm::WasmModule::globals, v8::internal::index, v8::internal::Factory::InternalizeUtf8String(), v8::internal::DirectHandle< T >::is_null(), kExternalFunction, kExternalGlobal, kExternalMemory, kExternalTable, kExternalTag, v8::internal::kNoInternalize, v8::internal::wasm::WasmModule::memories, v8::internal::Isolate::native_context(), v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::Factory::NewJSArray(), v8::internal::Factory::NewJSObject(), v8::internal::NONE, v8::internal::PACKED_ELEMENTS, v8::internal::JSArray::SetContent(), v8::internal::wasm::WasmModule::tables, v8::internal::UNREACHABLE(), and v8::internal::JSObject::ValidateElements().
Referenced by v8::internal::AddWasmModuleObjectInternalProperties(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyModuleExportsImpl().
GetI32Sig()
V8_EXPORT_PRIVATE const wasm::FunctionSig * v8::internal::wasm::GetI32Sig (Zone * zone, const wasm::FunctionSig * sig)
Definition at line 235 of file value-type.cc.
                                                                         {
  return ReplaceTypeInSig(zone, sig, wasm::kWasmI64, wasm::kWasmI32, 2);
}
References kWasmI32, kWasmI64, v8::internal::wasm::anonymous_namespace{value-type.cc}::ReplaceTypeInSig(), and v8::internal::sig.
GetImports()
DirectHandle< JSArray > v8::internal::wasm::GetImports (Isolate * isolate, DirectHandle< WasmModuleObject > module_object)
Definition at line 425 of file wasm-module.cc.
                                                                               {
  auto enabled_features = i::wasm::WasmEnabledFeatures::FromIsolate(isolate);
  Factory* factory = isolate->factory();
  DirectHandle<String> module_string = factory->InternalizeUtf8String("module");
  DirectHandle<String> name_string = factory->name_string();
  DirectHandle<String> kind_string = factory->InternalizeUtf8String("kind");
  DirectHandle<String> type_string = factory->InternalizeUtf8String("type");
  DirectHandle<String> function_string = factory->function_string();
  DirectHandle<String> table_string = factory->InternalizeUtf8String("table");
  DirectHandle<String> memory_string = factory->InternalizeUtf8String("memory");
  DirectHandle<String> global_string = factory->global_string();
  DirectHandle<String> tag_string = factory->InternalizeUtf8String("tag");
  // Create the result array.
  NativeModule* native_module = module_object->native_module();
  const WasmModule* module = native_module->module();
  int num_imports = static_cast<int>(module->import_table.size());
  DirectHandle<JSArray> array_object =
      factory->NewJSArray(PACKED_ELEMENTS, 0, 0);
  DirectHandle<FixedArray> storage = factory->NewFixedArray(num_imports);
  JSArray::SetContent(isolate, array_object, storage);
  DirectHandle<JSFunction> object_function = DirectHandle<JSFunction>(
      isolate->native_context()->object_function(), isolate);
  // Populate the result array.
  const WellKnownImportsList& well_known_imports =
      module->type_feedback.well_known_imports;
  const std::string& magic_string_constants =
      native_module->compile_imports().constants_module();
  const bool has_magic_string_constants =
      native_module->compile_imports().contains(
          CompileTimeImport::kStringConstants);
  int cursor = 0;
  for (int index = 0; index < num_imports; ++index) {
    const WasmImport& import = module->import_table[index];
    DirectHandle<JSObject> entry = factory->NewJSObject(object_function);
    DirectHandle<String> import_kind;
    DirectHandle<JSObject> type_value;
    switch (import.kind) {
      case kExternalFunction:
        if (IsCompileTimeImport(well_known_imports.get(import.index))) {
          continue;
        }
        if (enabled_features.has_type_reflection()) {
          auto& func = module->functions[import.index];
          type_value = GetTypeForFunction(isolate, func.sig);
        }
        import_kind = function_string;
        break;
      case kExternalTable:
        if (enabled_features.has_type_reflection()) {
          auto& table = module->tables[import.index];
          std::optional<uint32_t> maximum_size;
          if (table.has_maximum_size) maximum_size.emplace(table.maximum_size);
          type_value = GetTypeForTable(isolate, table.type, table.initial_size,
                                       maximum_size, table.address_type);
        }
        import_kind = table_string;
        break;
      case kExternalMemory:
        if (enabled_features.has_type_reflection()) {
          auto& memory = module->memories[import.index];
          std::optional<uint32_t> maximum_size;
          if (memory.has_maximum_pages) {
            maximum_size.emplace(memory.maximum_pages);
          }
          type_value =
              GetTypeForMemory(isolate, memory.initial_pages, maximum_size,
                               memory.is_shared, memory.address_type);
        }
        import_kind = memory_string;
        break;
      case kExternalGlobal:
        if (has_magic_string_constants &&
            import.module_name.length() == magic_string_constants.size() &&
            std::equal(magic_string_constants.begin(),
                       magic_string_constants.end(),
                       module_object->native_module()->wire_bytes().begin() +
                           import.module_name.offset())) {
          continue;
        }
        if (enabled_features.has_type_reflection()) {
          auto& global = module->globals[import.index];
          type_value =
              GetTypeForGlobal(isolate, global.mutability, global.type);
        }
        import_kind = global_string;
        break;
      case kExternalTag:
        import_kind = tag_string;
        break;
    }
    DCHECK(!import_kind.is_null());
    DirectHandle<String> import_module =
        WasmModuleObject::ExtractUtf8StringFromModuleBytes(
            isolate, module_object, import.module_name, kInternalize);
    DirectHandle<String> import_name =
        WasmModuleObject::ExtractUtf8StringFromModuleBytes(
            isolate, module_object, import.field_name, kInternalize);
    JSObject::AddProperty(isolate, entry, module_string, import_module, NONE);
    JSObject::AddProperty(isolate, entry, name_string, import_name, NONE);
    JSObject::AddProperty(isolate, entry, kind_string, import_kind, NONE);
    if (!type_value.is_null()) {
      JSObject::AddProperty(isolate, entry, type_string, type_value, NONE);
    }
    storage->set(cursor++, *entry);
  }
  array_object->set_length(Smi::FromInt(cursor));
  // Make sure that values after the cursor are holes.
  for (int index = cursor; index < num_imports; ++index) {
    storage->set_the_hole(isolate, cursor++);
  }
  JSObject::ValidateElements(isolate, *array_object);
  return array_object;
}
References v8::internal::JSObject::AddProperty(), v8::internal::wasm::NativeModule::compile_imports(), v8::internal::wasm::CompileTimeImports::constants_module(), v8::internal::wasm::CompileTimeImports::contains(), v8::internal::DCHECK(), v8::internal::equal, v8::internal::WasmModuleObject::ExtractUtf8StringFromModuleBytes(), v8::internal::Isolate::factory(), v8::internal::Smi::FromInt(), v8::internal::wasm::WasmModule::functions, v8::internal::wasm::WellKnownImportsList::get(), GetTypeForFunction(), GetTypeForGlobal(), GetTypeForMemory(), GetTypeForTable(), v8::internal::wasm::WasmModule::globals, v8::internal::wasm::WasmModule::import_table, v8::internal::index, v8::internal::Factory::InternalizeUtf8String(), v8::internal::DirectHandle< T >::is_null(), IsCompileTimeImport(), kExternalFunction, kExternalGlobal, kExternalMemory, kExternalTable, kExternalTag, v8::internal::kInternalize, kStringConstants, v8::internal::wasm::WasmModule::memories, v8::internal::wasm::NativeModule::module(), v8::internal::Isolate::native_context(), v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::Factory::NewJSArray(), v8::internal::Factory::NewJSObject(), v8::internal::NONE, v8::internal::PACKED_ELEMENTS, v8::internal::JSArray::SetContent(), v8::internal::string, v8::internal::wasm::WasmModule::tables, v8::internal::wasm::WasmModule::type_feedback, v8::internal::JSObject::ValidateElements(), and v8::internal::wasm::TypeFeedbackStorage::well_known_imports.
Referenced by v8::internal::AddWasmModuleObjectInternalProperties(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyModuleImportsImpl().
GetInterpreterHandle()
V8_EXPORT_PRIVATE InterpreterHandle * v8::internal::wasm::GetInterpreterHandle (Isolate * isolate, DirectHandle< Tuple2 > interpreter_object)
Definition at line 233 of file wasm-interpreter-runtime.cc.
                                                               {
  DirectHandle<Object> handle(
      WasmInterpreterObject::get_interpreter_handle(*interpreter_object),
      isolate);
  CHECK(!IsUndefined(*handle, isolate));
  return Cast<Managed<InterpreterHandle>>(handle)->raw();
}
References CHECK, v8::internal::WasmInterpreterObject::get_interpreter_handle(), and v8::internal::handle().
Referenced by v8::internal::WasmInterpreterObject::RunInterpreter().
GetLoadType()
static constexpr LoadType v8::internal::wasm::GetLoadType (WasmOpcode opcode) [static], [constexpr]
Definition at line 75 of file function-body-decoder-impl.h.
                                                         {
  // Hard-code the list of load types. The opcodes are highly unlikely to
  // ever change, and we have some checks here to guard against that.
  static_assert(sizeof(LoadType) == sizeof(uint8_t), "LoadType is compact");
  constexpr uint8_t kMinOpcode = kExprI32LoadMem;
  constexpr uint8_t kMaxOpcode = kExprI64LoadMem32U;
  constexpr LoadType kLoadTypes[] = {
      LoadType::kI32Load, LoadType::kI64Load, LoadType::kF32Load,
      LoadType::kF64Load, LoadType::kI32Load8S, LoadType::kI32Load8U,
      LoadType::kI32Load16S, LoadType::kI32Load16U, LoadType::kI64Load8S,
      LoadType::kI64Load8U, LoadType::kI64Load16S, LoadType::kI64Load16U,
      LoadType::kI64Load32S, LoadType::kI64Load32U};
  static_assert(arraysize(kLoadTypes) == kMaxOpcode - kMinOpcode + 1);
  DCHECK_LE(kMinOpcode, opcode);
  DCHECK_GE(kMaxOpcode, opcode);
  return kLoadTypes[opcode - kMinOpcode];
}
References arraysize, DCHECK_GE, and DCHECK_LE.
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE().
GetMachineRepresentation() [1/2]
MachineRepresentation v8::internal::wasm::GetMachineRepresentation (MachineType type) [inline]
Definition at line 24 of file signature-hashing.h.
                                                                        {
  return type.representation();
}
References v8::internal::tracing::type.
GetMachineRepresentation() [2/2]
MachineRepresentation v8::internal::wasm::GetMachineRepresentation (ValueTypeBase type) [inline]
Definition at line 20 of file signature-hashing.h.
                                                                          {
  return type.machine_representation();
}
References v8::internal::tracing::type.
Referenced by IterateSignatureImpl().
GetNearestWasmFunction()
int v8::internal::wasm::GetNearestWasmFunction (const WasmModule * module, uint32_t byte_offset)
Definition at line 112 of file wasm-module.cc.
                                                                           {
  const std::vector<WasmFunction>& functions = module->functions;
  // Binary search for a function containing the given position.
  int left = 0; // inclusive
  int right = static_cast<int>(functions.size()); // exclusive
  if (right == 0) return -1;
  while (right - left > 1) {
    int mid = left + (right - left) / 2;
    if (functions[mid].code.offset() <= byte_offset) {
      left = mid;
    } else {
      right = mid;
    }
  }
  return left;
}
References code, and v8::internal::wasm::WasmModule::functions.
Referenced by GetContainingWasmFunction(), and v8::internal::WasmScript::GetPossibleBreakpoints().
GetNumDigits()
int v8::internal::wasm::GetNumDigits (uint32_t value) [inline]
Definition at line 29 of file string-builder-multiline.h.
                                        {
  int digits = 1;
  for (uint32_t compare = 10; value >= compare; compare *= 10) digits++;
  return digits;
}
References v8::internal::value.
Referenced by v8::internal::wasm::MultiLineStringBuilder::WriteTo().
GetOperatorModeString()
const char* v8::internal::wasm::GetOperatorModeString (OperatorMode mode)
Definition at line 8644 of file wasm-interpreter.cc.
                                                     {
  switch (mode) {
    case kR2R:
      return "R2R";
    case kR2S:
      return "R2S";
    case kS2R:
      return "S2R";
    case kS2S:
      return "S2S";
    default:
      UNREACHABLE();
  }
}
References kR2R, kR2S, kS2R, kS2S, mode(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction().
GetOrCreateInterpreterHandle()
V8_EXPORT_PRIVATE InterpreterHandle * v8::internal::wasm::GetOrCreateInterpreterHandle (Isolate * isolate, DirectHandle< Tuple2 > interpreter_object)
Definition at line 242 of file wasm-interpreter-runtime.cc.
                                                               {
  DirectHandle<Object> handle(
      WasmInterpreterObject::get_interpreter_handle(*interpreter_object),
      isolate);
  if (IsUndefined(*handle, isolate)) {
    // Use the maximum stack size to estimate the maximum size of the
    // interpreter. The interpreter keeps its own stack internally, and the size
    // of the stack should dominate the overall size of the interpreter. We
    // multiply by '2' to account for the growing strategy for the backing store
    // of the stack.
    size_t interpreter_size = v8_flags.stack_size * KB * 2;
    handle = Managed<InterpreterHandle>::From(
        isolate, interpreter_size,
        std::make_shared<InterpreterHandle>(isolate, interpreter_object));
    WasmInterpreterObject::set_interpreter_handle(*interpreter_object, *handle);
  }
  return Cast<Managed<InterpreterHandle>>(handle)->raw();
}
References v8::internal::Managed< CppType >::From(), v8::internal::WasmInterpreterObject::get_interpreter_handle(), v8::internal::handle(), v8::internal::KB, v8::internal::WasmInterpreterObject::set_interpreter_handle(), and v8::internal::v8_flags.
Referenced by v8::internal::wasm::WasmInterpreterRuntime::CallImportedFunction(), v8::internal::wasm::WasmInterpreterRuntime::ClearIndirectCallCacheEntry(), v8::internal::wasm::WasmInterpreterRuntime::ExecuteIndirectCall(), v8::internal::WasmInterpreterObject::RunInterpreter(), v8::internal::RUNTIME_FUNCTION(), v8::internal::wasm::WasmInterpreterRuntime::UpdateIndirectCallTable(), and v8::internal::wasm::WasmInterpreterRuntime::UpdateMemoryAddress().
GetProcessWideWasmCodePointerTable()
V8_EXPORT_PRIVATE WasmCodePointerTable* v8::internal::wasm::GetProcessWideWasmCodePointerTable ()
Referenced by v8::internal::wasm::FeedbackMaker::AddCallIndirectCandidate(), v8::internal::wasm::NativeModule::FreeCodePointerTableHandles(), v8::internal::FUNCTION_REFERENCE(), v8::internal::wasm::WasmEngine::GlobalTearDown(), v8::internal::wasm::NativeModule::InitializeCodePointerTableHandles(), v8::internal::wasm::NativeModule::InitializeJumpTableForLazyCompilation(), v8::internal::wasm::WasmEngine::InitializeOncePerProcess(), v8::internal::wasm::NativeModule::PatchJumpTablesLocked(), v8::internal::RUNTIME_FUNCTION(), v8::internal::ImportedFunctionEntry::SetWasmToWasm(), v8::internal::WasmTableObject::UpdateDispatchTable(), and v8::internal::wasm::WasmImportWrapperHandle::~WasmImportWrapperHandle().
GetRegMode()
RegMode v8::internal::wasm::GetRegMode (ValueKind kind) [inline]
Definition at line 758 of file wasm-interpreter.h.
                                          {
  switch (kind) {
    case kI32:
      return RegMode::kI32Reg;
    case kI64:
      return RegMode::kI64Reg;
    case kF32:
      return RegMode::kF32Reg;
    case kF64:
      return RegMode::kF64Reg;
    default:
      UNREACHABLE();
  }
}
References v8::internal::kF32, kF32Reg, v8::internal::kF64, kF64Reg, v8::internal::kI32, kI32Reg, v8::internal::kI64, kI64Reg, and v8::internal::UNREACHABLE().
Referenced by v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction().
GetRegModeString()
const char* v8::internal::wasm::GetRegModeString (RegMode reg_mode)
Definition at line 8625 of file wasm-interpreter.cc.
                                               {
  switch (reg_mode) {
    case RegMode::kNoReg:
      return "NoReg";
    case RegMode::kAnyReg:
      return "AnyReg";
    case RegMode::kI32Reg:
      return "I32Reg";
    case RegMode::kI64Reg:
      return "I64Reg";
    case RegMode::kF32Reg:
      return "F32Reg";
    case RegMode::kF64Reg:
      return "F64Reg";
    default:
      UNREACHABLE();
  }
}
References kAnyReg, kF32Reg, kF64Reg, kI32Reg, kI64Reg, kNoReg, and v8::internal::UNREACHABLE().
Referenced by v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction().
GetSourcePosition()
int v8::internal::wasm::GetSourcePosition (const WasmModule * module, uint32_t func_index, uint32_t byte_offset, bool is_at_number_conversion)
Definition at line 706 of file wasm-module.cc.
                                                                          {
  DCHECK_EQ(is_asmjs_module(module),
            module->asm_js_offset_information != nullptr);
  if (!is_asmjs_module(module)) {
    // For non-asm.js modules, we just add the function's start offset
    // to make a module-relative position.
    return byte_offset + GetWasmFunctionOffset(module, func_index);
  }
  // asm.js modules have an additional offset table that must be searched.
  return module->asm_js_offset_information->GetSourcePosition(
      declared_function_index(module, func_index), byte_offset,
      is_at_number_conversion);
}
References v8::internal::wasm::WasmModule::asm_js_offset_information, DCHECK_EQ, declared_function_index(), GetWasmFunctionOffset(), and is_asmjs_module().
Referenced by v8::internal::compiler::CodeGenerator::AssembleSourcePosition(), v8::internal::CallSiteInfo::ComputeSourcePosition(), v8::internal::CallSiteInfo::GetEnclosingColumnNumber(), and v8::internal::CallSiteInfo::GetEnclosingLineNumber().
GetStoreType()
static constexpr StoreType v8::internal::wasm::GetStoreType (WasmOpcode opcode) [static], [constexpr]
Definition at line 93 of file function-body-decoder-impl.h.
                                                           {
  // Hard-code the list of store types. The opcodes are highly unlikely to
  // ever change, and we have some checks here to guard against that.
  static_assert(sizeof(StoreType) == sizeof(uint8_t), "StoreType is compact");
  constexpr uint8_t kMinOpcode = kExprI32StoreMem;
  constexpr uint8_t kMaxOpcode = kExprI64StoreMem32;
  constexpr StoreType kStoreTypes[] = {
      StoreType::kI32Store, StoreType::kI64Store, StoreType::kF32Store,
      StoreType::kF64Store, StoreType::kI32Store8, StoreType::kI32Store16,
      StoreType::kI64Store8, StoreType::kI64Store16, StoreType::kI64Store32};
  static_assert(arraysize(kStoreTypes) == kMaxOpcode - kMinOpcode + 1);
  DCHECK_LE(kMinOpcode, opcode);
  DCHECK_GE(kMaxOpcode, opcode);
  return kStoreTypes[opcode - kMinOpcode];
}
References arraysize, DCHECK_GE, and DCHECK_LE.
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE().
GetSubtypingDepth()
V8_EXPORT_PRIVATE int v8::internal::wasm::GetSubtypingDepth (const WasmModule * module, ModuleTypeIndex type_index)
Definition at line 146 of file wasm-module.cc.
                                                                            {
  DCHECK_LT(type_index.index, module->types.size());
  int depth = module->type(type_index).subtyping_depth;
  DCHECK_LE(depth, kV8MaxRttSubtypingDepth);
  return depth;
}
References DCHECK_LE, DCHECK_LT, v8::internal::wasm::TypeIndex::index, kV8MaxRttSubtypingDepth, v8::internal::wasm::TypeDefinition::subtyping_depth, v8::internal::wasm::WasmModule::type(), and v8::internal::wasm::WasmModule::types.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildIndirectCallTargetAndImplicitArg(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallIndirectImpl(), v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::CommonAncestor(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCast(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ReduceWasmTypeCastRtt(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheck(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ReduceWasmTypeCheckRtt(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SubtypeCheck(), and v8::internal::wasm::WasmInterpreterRuntime::SubtypeCheck().
GetTypeCanonicalizer()
V8_EXPORT_PRIVATE TypeCanonicalizer * v8::internal::wasm::GetTypeCanonicalizer ()
Definition at line 20 of file canonical-types.cc.
                                          {
  return GetWasmEngine()->type_canonicalizer();
}
References GetWasmEngine(), and v8::internal::wasm::WasmEngine::type_canonicalizer().
Referenced by v8::internal::wasm::NativeModule::AddCodeWithCodeSpace(), v8::internal::wasm::NativeModule::AddDeserializedCode(), wasm::anonymous_namespace{c-api.cc}::SignatureHelper::Canonicalize(), v8::internal::wasm::WasmInterpreterRuntime::ContinueExecution(), v8::internal::StructProxy::Count(), v8::internal::CreateArrayMap(), v8::internal::CreateStructMap(), DecodeCanonicalTypeNames(), v8::internal::wasm::CanonicalTypeNamesProvider::DecodeNameSections(), v8::internal::wasm::ModuleDecoderImpl::DecodeTypeSection(), v8::internal::WasmStruct::GcSafeType(), v8::internal::wasm::WasmBytecodeGenerator::GenerateBytecode(), v8::internal::WasmStruct::GetFieldValue(), v8::internal::WasmInternalFunction::GetOrCreateExternal(), v8::internal::wasm::NativeModule::InitializeJumpTableForLazyCompilation(), IsSubtypeOfImpl(), wasm::anonymous_namespace{c-api.cc}::make_func(), v8::internal::WasmExportedFunctionData::MatchesSignature(), v8::internal::WasmJSFunction::New(), v8::internal::WasmExportedFunction::New(), v8::anonymous_namespace{wasm-js.cc}::NewPromisingWasmExportedFunction(), v8::internal::wasm::InstanceBuilder::ProcessImportedFunction(), v8::internal::wasm::ResolvedWasmImport::ResolvedWasmImport(), v8::internal::RUNTIME_FUNCTION(), v8::internal::wasm::WasmWrapperTSGraphBuilder::ToJS(), v8::internal::WasmTableObject::UpdateDispatchTable(), v8::internal::wasm::NativeModule::UseLazyStubLocked(), v8::internal::wasm::WasmCode::Validate(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyExceptionImpl().
GetTypeForFunction()
DirectHandle< JSObject > v8::internal::wasm::GetTypeForFunction (Isolate * isolate, const FunctionSig * sig, bool for_exception)
Definition at line 290 of file wasm-module.cc.
                                                              {
  Factory* factory = isolate->factory();
  // Extract values for the {ValueType[]} arrays.
  int param_index = 0;
  int param_count = static_cast<int>(sig->parameter_count());
  DirectHandle<FixedArray> param_values = factory->NewFixedArray(param_count);
  for (ValueType type : sig->parameters()) {
    DirectHandle<String> type_value = ToValueTypeString(isolate, type);
    param_values->set(param_index++, *type_value);
  }
  // Create the resulting {FunctionType} object.
  DirectHandle<JSFunction> object_function = isolate->object_function();
  DirectHandle<JSObject> object = factory->NewJSObject(object_function);
  DirectHandle<JSArray> params = factory->NewJSArrayWithElements(param_values);
  DirectHandle<String> params_string =
      factory->InternalizeUtf8String("parameters");
  DirectHandle<String> results_string =
      factory->InternalizeUtf8String("results");
  JSObject::AddProperty(isolate, object, params_string, params, NONE);
  // Now add the result types if needed.
  if (for_exception) {
    DCHECK_EQ(sig->returns().size(), 0);
  } else {
    int result_index = 0;
    int result_count = static_cast<int>(sig->return_count());
    DirectHandle<FixedArray> result_values =
        factory->NewFixedArray(result_count);
    for (ValueType type : sig->returns()) {
      DirectHandle<String> type_value = ToValueTypeString(isolate, type);
      result_values->set(result_index++, *type_value);
    }
    DirectHandle<JSArray> results =
        factory->NewJSArrayWithElements(result_values);
    JSObject::AddProperty(isolate, object, results_string, results, NONE);
  }
  return object;
}
References v8::internal::JSObject::AddProperty(), DCHECK_EQ, v8::internal::Isolate::factory(), v8::internal::Factory::InternalizeUtf8String(), v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::Factory::NewJSArrayWithElements(), v8::internal::Factory::NewJSObject(), v8::internal::NONE, v8::internal::sig, v8::internal::wasm::anonymous_namespace{wasm-module.cc}::ToValueTypeString(), and v8::internal::tracing::type.
Referenced by GetExports(), GetImports(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyFunctionType(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTagType().
GetTypeForGlobal()
DirectHandle< JSObject > v8::internal::wasm::GetTypeForGlobal (Isolate * isolate, bool is_mutable, ValueType type)
Definition at line 334 of file wasm-module.cc.
                                                        {
  Factory* factory = isolate->factory();
  DirectHandle<JSFunction> object_function = isolate->object_function();
  DirectHandle<JSObject> object = factory->NewJSObject(object_function);
  DirectHandle<String> mutable_string =
      factory->InternalizeUtf8String("mutable");
  DirectHandle<String> value_string = factory->value_string();
  JSObject::AddProperty(isolate, object, mutable_string,
                        factory->ToBoolean(is_mutable), NONE);
  JSObject::AddProperty(isolate, object, value_string,
                        ToValueTypeString(isolate, type), NONE);
  return object;
}
References v8::internal::JSObject::AddProperty(), v8::internal::Isolate::factory(), v8::internal::Factory::InternalizeUtf8String(), v8::internal::Factory::NewJSObject(), v8::internal::NONE, v8::internal::FactoryBase< Impl >::ToBoolean(), v8::internal::wasm::anonymous_namespace{wasm-module.cc}::ToValueTypeString(), and v8::internal::tracing::type.
Referenced by GetExports(), GetImports(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyGlobalType().
GetTypeForMemory()
DirectHandle< JSObject > v8::internal::wasm::GetTypeForMemory (Isolate * isolate, uint32_t min_size, std::optional< uint64_t > max_size, bool shared, AddressType address_type)
Definition at line 351 of file wasm-module.cc.
                                                                               {
  Factory* factory = isolate->factory();
  DirectHandle<JSFunction> object_function = isolate->object_function();
  DirectHandle<JSObject> object = factory->NewJSObject(object_function);
  DirectHandle<String> minimum_string =
      factory->InternalizeUtf8String("minimum");
  DirectHandle<String> maximum_string =
      factory->InternalizeUtf8String("maximum");
  DirectHandle<String> shared_string = factory->InternalizeUtf8String("shared");
  DirectHandle<String> address_string =
      factory->InternalizeUtf8String("address");
  JSObject::AddProperty(isolate, object, minimum_string,
                        factory->NewNumberFromUint(min_size), NONE);
  if (max_size.has_value()) {
    DirectHandle<UnionOf<Smi, HeapNumber, BigInt>> max;
    if (address_type == AddressType::kI32) {
      DCHECK_GE(kMaxUInt32, *max_size);
      max = factory->NewNumberFromUint(static_cast<uint32_t>(*max_size));
    } else {
      max = BigInt::FromUint64(isolate, *max_size);
    }
    JSObject::AddProperty(isolate, object, maximum_string, max, NONE);
  }
  JSObject::AddProperty(isolate, object, shared_string,
                        factory->ToBoolean(shared), NONE);
  JSObject::AddProperty(
      isolate, object, address_string,
      factory->InternalizeUtf8String(AddressTypeToStr(address_type)), NONE);
  return object;
}
References v8::internal::Isolate::factory(), v8::internal::Factory::InternalizeUtf8String(), and v8::internal::Factory::NewJSObject().
Referenced by GetExports(), GetImports(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryType().
GetTypeForTable()
DirectHandle< JSObject > v8::internal::wasm::GetTypeForTable (Isolate * isolate, ValueType type, uint32_t min_size, std::optional< uint64_t > max_size, AddressType address_type)
Definition at line 387 of file wasm-module.cc.
                                                                 {
  Factory* factory = isolate->factory();
  DirectHandle<String> element =
      factory->InternalizeUtf8String(base::VectorOf(type.name()));
  DirectHandle<JSFunction> object_function = isolate->object_function();
  DirectHandle<JSObject> object = factory->NewJSObject(object_function);
  DirectHandle<String> element_string = factory->element_string();
  DirectHandle<String> minimum_string =
      factory->InternalizeUtf8String("minimum");
  DirectHandle<String> maximum_string =
      factory->InternalizeUtf8String("maximum");
  DirectHandle<String> address_string =
      factory->InternalizeUtf8String("address");
  JSObject::AddProperty(isolate, object, element_string, element, NONE);
  JSObject::AddProperty(isolate, object, minimum_string,
                        factory->NewNumberFromUint(min_size), NONE);
  if (max_size.has_value()) {
    DirectHandle<UnionOf<Smi, HeapNumber, BigInt>> max;
    if (address_type == AddressType::kI32) {
      DCHECK_GE(kMaxUInt32, *max_size);
      max = factory->NewNumberFromUint(static_cast<uint32_t>(*max_size));
    } else {
      max = BigInt::FromUint64(isolate, *max_size);
    }
    JSObject::AddProperty(isolate, object, maximum_string, max, NONE);
  }
  JSObject::AddProperty(
      isolate, object, address_string,
      factory->InternalizeUtf8String(AddressTypeToStr(address_type)), NONE);
  return object;
}
References v8::internal::JSObject::AddProperty(), AddressTypeToStr(), DCHECK_GE, v8::internal::Isolate::factory(), v8::internal::BigInt::FromUint64(), v8::internal::Factory::InternalizeUtf8String(), kI32, v8::internal::kMaxUInt32, v8::internal::Factory::NewJSObject(), v8::internal::FactoryBase< Impl >::NewNumberFromUint(), v8::internal::NONE, v8::internal::tracing::type, and v8::base::VectorOf().
Referenced by GetExports(), GetImports(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableType().
GetValueSizeInSlots()
uint32_t v8::internal::wasm::GetValueSizeInSlots (ValueKind kind) [inline]
Definition at line 136 of file wasm-interpreter-inl.h.
                                                    {
  switch (kind) {
    case kI32:
      return sizeof(int32_t) / kSlotSize;
    case kI64:
      return sizeof(int64_t) / kSlotSize;
    case kF32:
      return sizeof(float) / kSlotSize;
    case kF64:
      return sizeof(double) / kSlotSize;
    case kS128:
      return sizeof(Simd128) / kSlotSize;
    case kRef:
    case kRefNull:
      return sizeof(WasmRef) / kSlotSize;
    default:
      UNREACHABLE();
  }
}
References v8::internal::kF32, v8::internal::kF64, v8::internal::kI32, v8::internal::kI64, v8::internal::kRef, v8::internal::kRefNull, v8::internal::kS128, kSlotSize, and v8::internal::UNREACHABLE().
Referenced by v8::internal::wasm::WasmBytecode::ArgsSizeInSlots(), v8::internal::wasm::WasmBytecode::LocalsSizeInSlots(), and v8::internal::wasm::WasmBytecode::RetsSizeInSlots().
GetWasmCodeKindAsString()
const char * v8::internal::wasm::GetWasmCodeKindAsString (WasmCode::Kind kind)
Definition at line 547 of file wasm-code-manager.cc.
                                                       {
  switch (kind) {
    case WasmCode::kWasmFunction:
      return "wasm function";
    case WasmCode::kWasmToCapiWrapper:
      return "wasm-to-capi";
    case WasmCode::kWasmToJsWrapper:
      return "wasm-to-js";
#if V8_ENABLE_DRUMBRAKE
    case WasmCode::kInterpreterEntry:
      return "interpreter entry";
#endif // V8_ENABLE_DRUMBRAKE
    case WasmCode::kJumpTable:
      return "jump table";
  }
  return "unknown kind";
}
References v8::internal::wasm::WasmCode::kJumpTable, v8::internal::wasm::WasmCode::kWasmFunction, v8::internal::wasm::WasmCode::kWasmToCapiWrapper, and v8::internal::wasm::WasmCode::kWasmToJsWrapper.
Referenced by v8::internal::wasm::WasmCode::Disassemble().
GetWasmCodeManager()
V8_EXPORT_PRIVATE WasmCodeManager * v8::internal::wasm::GetWasmCodeManager ()
Definition at line 2130 of file wasm-engine.cc.
                                      {
  DCHECK_NOT_NULL(global_wasm_state);
  return &global_wasm_state->code_manager;
}
References v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::GlobalWasmState::code_manager, DCHECK_NOT_NULL, and v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::global_wasm_state.
Referenced by _v8_internal_Print_Code(), _v8_internal_Print_OnlyCode(), v8::internal::wasm::FeedbackMaker::AddCallIndirectCandidate(), v8::internal::wasm::WasmEngine::AddPotentiallyDeadCode(), v8::internal::wasm::WasmCodeAllocator::AllocateForCodeInRegion(), v8::internal::StackFrameIterator::ComputeStackFrameType(), v8::internal::Deoptimizer::Deoptimizer(), v8::internal::Deoptimizer::EnsureValidReturnAddress(), v8::internal::MemoryMeasurement::FinishProcessing(), v8::internal::wasm::WasmCodeAllocator::FreeCode(), v8::internal::wasm::WasmEngine::FreeNativeModule(), v8::internal::wasm::WasmCodeLookupCache::GetCacheEntry(), v8::internal::anonymous_namespace{frames.cc}::GetStateForFastCCallCallerFP(), v8::internal::CommonFrame::HasTaggedOutgoingParams(), v8::internal::anonymous_namespace{execution.cc}::Invoke(), v8::internal::wasm::WasmImportWrapperCache::LazyInitialize(), v8::internal::wasm::WasmEngine::NewNativeModule(), v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::ReportLiveCodeFromFrameForGC(), v8::internal::wasm::WasmEngine::ReportLiveCodeFromStackForGC(), v8::internal::Isolate::UnwindAndFindHandler(), and v8::internal::wasm::WasmCodeAllocator::~WasmCodeAllocator().
GetWasmEngine()
V8_EXPORT_PRIVATE WasmEngine * v8::internal::wasm::GetWasmEngine ()
Definition at line 2125 of file wasm-engine.cc.
                            {
  DCHECK_NOT_NULL(global_wasm_state);
  return &global_wasm_state->engine;
}
References DCHECK_NOT_NULL, v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::GlobalWasmState::engine, and v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::global_wasm_state.
Referenced by v8::internal::wasm::AsyncCompileJob::Abort(), v8::internal::wasm::WasmEngine::AddIsolate(), v8::internal::compiler::turboshaft::PipelineData::allocator(), v8::internal::wasm::AsyncCompileJob::CompilationStateCallback::call(), v8::WasmModuleObject::Compile(), CompileLazy(), CompileToNativeModule(), v8::internal::compiler::CompileWasmJSFastCallWrapper(), v8::internal::wasm::WasmImportWrapperCache::CompileWasmJsFastCallWrapper(), v8::internal::wasm::WasmImportWrapperCache::CompileWrapper(), v8::Isolate::ContextDisposedNotification(), v8::internal::wasm::AsyncCompileJob::CreateNativeModule(), v8::internal::CreateWasmObject(), v8::internal::wasm::CanonicalTypeNamesProvider::DecodeNameSections(), v8::internal::wasm::WasmCode::DecRefOnPotentiallyDeadCode(), v8::internal::wasm::WasmCode::DecrementRefCount(), v8::internal::Isolate::Deinit(), DeserializeNativeModule(), v8::internal::Isolate::DumpAndResetStats(), v8::internal::Heap::EagerlyFreeExternalMemoryAndWasmCode(), v8::internal::wasm::TypeCanonicalizer::EmptyStorageForTesting(), v8::internal::wasm::WasmCompilationUnit::ExecuteCompilation(), ExecuteLiftoffCompilation(), v8::internal::wasm::AsyncCompileJob::Failed(), v8::internal::AsmJsCompilationJob::FinalizeJobImpl(), v8::internal::anonymous_namespace{wasm-debug.cc}::FindNextBreakablePosition(), v8::internal::wasm::SyncStreamingDecoder::Finish(), v8::internal::MemoryMeasurement::FinishProcessing(), v8::internal::wasm::AsyncCompileJob::FinishSuccessfully(), v8::WasmModuleObject::FromCompiledModule(), GenerateLiftoffDebugSideTable(), v8::internal::wasm::WasmWrapperTSGraphBuilder::GetBigIntToI64CallDescriptor(), v8::internal::compiler::TFPipelineData::GetCodeTracer(), v8::internal::compiler::turboshaft::PipelineData::GetCodeTracer(), v8::Isolate::GetHeapStatistics(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::GetOrCompileNewNativeModule(), v8::internal::wasm::AsyncCompileJob::GetOrCreateNativeModule(), v8::internal::WasmScript::GetPossibleBreakpoints(), v8::internal::WasmJSFunctionData::GetSignature(), GetTypeCanonicalizer(), v8::internal::StackGuard::HandleInterrupts(), v8::Isolate::HasPendingBackgroundTasks(), v8::internal::Isolate::Init(), v8::internal::WasmJs::Install(), v8::internal::AsmJs::InstantiateAsmWasm(), JSToWasmObject(), v8::internal::V8FileLogger::LateSetup(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerCall(), v8::internal::wasm::WasmCodeManager::NewNativeModule(), v8::internal::wasm::AsyncStreamingProcessor::OnAbort(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::AsyncInstantiateCompileResultResolver::OnCompilationSucceeded(), v8::internal::wasm::AsyncStreamingProcessor::OnFinishedStream(), v8::internal::wasm::AsyncCompileJob::PrepareRuntimeObjects(), v8::internal::wasm::AsyncStreamingProcessor::ProcessCodeSectionHeader(), v8::internal::ProfilingScope::ProfilingScope(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::PublishCode(), v8::internal::wasm::DebugInfoImpl::RecompileLiftoffWithBreakpoints(), v8::internal::wasm::ValidateFunctionsStreamingJob::Run(), v8::internal::wasm::anonymous_namespace{module-decoder.cc}::ValidateFunctionsTask::Run(), v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::WasmGCForegroundTask::RunInternal(), v8::internal::wasm::WasmEngine::LogCodesTask::RunInternal(), v8::internal::RUNTIME_FUNCTION(), v8::internal::V8FileLogger::SetCodeEventHandler(), ThrowLazyCompilationError(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::TierUpAllFunctions(), TierUpNowForTesting(), v8::internal::WasmTableObject::UpdateDispatchTable(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyCompileImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyInstanceImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyInstantiateImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyModuleImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTagImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyValidateImpl(), v8::internal::wasm::NativeModule::~NativeModule(), and v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::WeakScriptHandle::~WeakScriptHandle().
GetWasmErrorWithName()
WasmError v8::internal::wasm::GetWasmErrorWithName (base::Vector< const uint8_t > wire_bytes, int func_index, const WasmModule * module, WasmError error)
Definition at line 664 of file module-decoder.cc.
                                                {
  WasmName name = ModuleWireBytes{wire_bytes}.GetNameOrNull(func_index, module);
  if (name.begin() == nullptr) {
    return WasmError(error.offset(), "Compiling function #%d failed: %s",
                     func_index, error.message().c_str());
  } else {
    TruncatedUserString<> truncated_name(name);
    return WasmError(error.offset(),
                     "Compiling function #%d:\"%.*s\" failed: %s", func_index,
                     truncated_name.length(), truncated_name.start(),
                     error.message().c_str());
  }
}
References v8::internal::wasm::TruncatedUserString< kMaxLen >::length(), v8::internal::wasm::WasmError::message(), name(), v8::internal::wasm::WasmError::offset(), and v8::internal::wasm::TruncatedUserString< kMaxLen >::start().
Referenced by v8::internal::wasm::anonymous_namespace{module-decoder.cc}::ValidateFunctionsTask::SetError(), and ThrowLazyCompilationError().
GetWasmFunctionOffset()
int v8::internal::wasm::GetWasmFunctionOffset (const WasmModule * module, uint32_t func_index)
Definition at line 104 of file wasm-module.cc.
                                                                         {
  const std::vector<WasmFunction>& functions = module->functions;
  if (static_cast<uint32_t>(func_index) >= functions.size()) return -1;
  DCHECK_GE(kMaxInt, functions[func_index].code.offset());
  return static_cast<int>(functions[func_index].code.offset());
}
References code, DCHECK_GE, v8::internal::wasm::WasmModule::functions, and v8::internal::kMaxInt.
Referenced by wasm::anonymous_namespace{c-api.cc}::CreateFrameFromInternal(), v8::internal::wasm::gdb_server::WasmModuleDebug::GetCallStack(), v8::internal::CallSiteInfo::GetEnclosingColumnNumber(), and GetSourcePosition().
GetWasmImportWrapperCache()
V8_EXPORT_PRIVATE WasmImportWrapperCache * v8::internal::wasm::GetWasmImportWrapperCache ()
Definition at line 2135 of file wasm-engine.cc.
                                                    {
  DCHECK_NOT_NULL(global_wasm_state);
  return &global_wasm_state->import_wrapper_cache;
}
References DCHECK_NOT_NULL, v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::global_wasm_state, and v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::GlobalWasmState::import_wrapper_cache.
Referenced by v8::internal::wasm::WasmEngine::AddIsolate(), CompileImportWrapperForTest(), v8::internal::MemoryMeasurement::FinishProcessing(), v8::internal::wasm::WasmEngine::FreeDeadCodeLocked(), v8::internal::WasmDispatchTable::Grow(), v8::internal::ExistingCodeLogger::LogCompiledFunctions(), v8::internal::wasm::WasmCodeManager::LookupCode(), v8::internal::WasmJSFunction::New(), v8::internal::wasm::WasmEngine::NewNativeModule(), v8::internal::wasm::InstanceBuilder::ProcessImportedFunction(), v8::internal::RUNTIME_FUNCTION(), v8::internal::wasm::WasmImportWrapperHandle::set_code(), and v8::internal::WasmTableObject::UpdateDispatchTable().
GetWireBytesHash()
V8_EXPORT_PRIVATE size_t v8::internal::wasm::GetWireBytesHash (base::Vector< const uint8_t > wire_bytes)
Definition at line 848 of file wasm-module.cc.
                                                              {
  return StringHasher::HashSequentialString(
      reinterpret_cast<const char*>(wire_bytes.begin()), wire_bytes.length(),
      kZeroHashSeed);
}
References v8::base::Vector< T >::begin(), v8::internal::kZeroHashSeed, and v8::base::Vector< T >::length().
Referenced by v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::CreateWasmScript(), DumpModule(), DumpProfileToFile(), and LoadProfileFromFile().
grow_stack()
Address v8::internal::wasm::grow_stack (Isolate * isolate, void * current_sp, size_t frame_size, size_t gap, Address current_fp)
Definition at line 1052 of file wasm-external-refs.cc.
                                                   {
  // Check if this is a real stack overflow.
  StackLimitCheck check(isolate);
  if (check.WasmHasOverflowed(gap)) {
    wasm::StackMemory* active_stack = isolate->isolate_data()->active_stack();
    if (isolate->IsOnCentralStack()) {
      // Should not grow the central stack.
      return 0;
    }
    DCHECK(active_stack->IsActive());
    // Grow by at least the new frame size plus the stack limit margin.
    if (!active_stack->Grow(
            current_fp,
            gap + frame_size + StackMemory::JSStackLimitMarginKB() * KB)) {
      return 0;
    }
    Address new_sp = active_stack->base() - frame_size;
    // Here we assume stack values don't refer other moved stack slots.
    // A stack grow event happens right in the beginning of the function
    // call so moved slots contain only incoming params and frame header.
    // So, it is reasonable to assume no self references.
    std::memcpy(reinterpret_cast<void*>(new_sp), current_sp, frame_size);
#if V8_TARGET_ARCH_ARM64
    Address new_fp =
        new_sp + (current_fp - reinterpret_cast<Address>(current_sp));
    Address old_pc_address = current_fp + CommonFrameConstants::kCallerPCOffset;
    Address new_pc_address = new_fp + CommonFrameConstants::kCallerPCOffset;
    Address old_signed_pc = base::Memory<Address>(old_pc_address);
    Address new_signed_pc = PointerAuthentication::MoveSignedPC(
        isolate, old_signed_pc, new_pc_address + kSystemPointerSize,
        old_pc_address + kSystemPointerSize);
    WriteUnalignedValue<Address>(new_pc_address, new_signed_pc);
#endif
    isolate->stack_guard()->SetStackLimitForStackSwitching(
        reinterpret_cast<uintptr_t>(active_stack->jslimit()));
    return new_sp;
  }
  return 0;
}
References v8::internal::IsolateData::active_stack(), v8::internal::wasm::StackMemory::base(), v8::internal::DCHECK(), v8::internal::wasm::StackMemory::Grow(), v8::internal::wasm::StackMemory::IsActive(), v8::internal::Isolate::isolate_data(), v8::internal::Isolate::IsOnCentralStack(), v8::internal::wasm::StackMemory::jslimit(), v8::internal::wasm::StackMemory::JSStackLimitMarginKB(), v8::internal::KB, v8::internal::CommonFrameConstants::kCallerPCOffset, v8::internal::kSystemPointerSize, v8::internal::PointerAuthentication::MoveSignedPC(), v8::internal::StackGuard::SetStackLimitForStackSwitching(), v8::internal::Isolate::stack_guard(), and v8::internal::StackLimitCheck::WasmHasOverflowed().
Referenced by v8::internal::RegExpMacroAssemblerRISCV::GetCode().
HeapTypesUnrelated()
bool v8::internal::wasm::HeapTypesUnrelated (HeapType heap1, HeapType heap2, const WasmModule * module) [inline]
Definition at line 98 of file wasm-subtyping.h.
                                                            {
  return !IsHeapSubtypeOf(heap1, heap2, module) &&
         !IsHeapSubtypeOf(heap2, heap1, module);
}
References IsHeapSubtypeOf().
Referenced by v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCastAbstract(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCheck(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCheckAbstract(), v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::TypesUnrelated(), v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::WasmTypeCast(), and v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::WasmTypeCheck().
i16x8_sconvert_f16x8_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::i16x8_sconvert_f16x8_wrapper (Address data)
Definition at line 600 of file wasm-external-refs.cc.
                                                {
  simd_float_un_wrapper<Float16, int16_t, &ConvertToIntS>(data);
}
i16x8_uconvert_f16x8_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::i16x8_uconvert_f16x8_wrapper (Address data)
Definition at line 604 of file wasm-external-refs.cc.
                                                {
  simd_float_un_wrapper<Float16, uint16_t, &ConvertToIntU>(data);
}
I31Check()
static bool v8::internal::wasm::I31Check (const WasmRef obj) [static]
Definition at line 2681 of file wasm-interpreter-runtime.cc.
{ return IsSmi(*obj); }
References v8::internal::IsSmi().
IdentifyUnknownSectionInternal()
SectionCode v8::internal::wasm::IdentifyUnknownSectionInternal (Decoder * decoder, ITracer * tracer) [inline]
Definition at line 124 of file module-decoder-impl.h.
                                                                   {
  WireBytesRef string = consume_utf8_string(decoder, "section name", tracer);
  if (decoder->failed()) {
    return kUnknownSectionCode;
  }
  const uint8_t* section_name_start =
      decoder->start() + decoder->GetBufferRelativeOffset(string.offset());
  TRACE(" +%d section name : \"%.*s\"\n",
        static_cast<int>(section_name_start - decoder->start()),
        string.length() < 20 ? string.length() : 20, section_name_start);
  using SpecialSectionPair = std::pair<base::Vector<const char>, SectionCode>;
  static constexpr SpecialSectionPair kSpecialSections[]{
      {base::StaticCharVector(kNameString), kNameSectionCode},
      {base::StaticCharVector(kSourceMappingURLString),
       kSourceMappingURLSectionCode},
      {base::StaticCharVector(kInstTraceString), kInstTraceSectionCode},
      {base::StaticCharVector(kCompilationHintsString),
       kCompilationHintsSectionCode},
      {base::StaticCharVector(kBranchHintsString), kBranchHintsSectionCode},
      {base::StaticCharVector(kDebugInfoString), kDebugInfoSectionCode},
      {base::StaticCharVector(kExternalDebugInfoString),
       kExternalDebugInfoSectionCode},
      {base::StaticCharVector(kBuildIdString), kBuildIdSectionCode},
      {base::StaticCharVector(kDescriptorsString), kDescriptorsSectionCode}};
  auto name_vec = base::Vector<const char>::cast(
      base::VectorOf(section_name_start, string.length()));
  for (auto& special_section : kSpecialSections) {
    if (name_vec == special_section.first) return special_section.second;
  }
  return kUnknownSectionCode;
}
References consume_utf8_string(), v8::internal::wasm::Decoder::failed(), v8::internal::wasm::Decoder::GetBufferRelativeOffset(), kBranchHintsSectionCode, kBranchHintsString, kBuildIdSectionCode, kBuildIdString, kCompilationHintsSectionCode, kCompilationHintsString, kDebugInfoSectionCode, kDebugInfoString, kDescriptorsSectionCode, kDescriptorsString, kExternalDebugInfoSectionCode, kExternalDebugInfoString, kInstTraceSectionCode, kInstTraceString, kNameSectionCode, kNameString, kSourceMappingURLSectionCode, kSourceMappingURLString, kUnknownSectionCode, v8::internal::length, v8::internal::wasm::Decoder::start(), v8::base::StaticCharVector(), v8::internal::TRACE(), and v8::base::VectorOf().
Referenced by v8::internal::wasm::ModuleDecoder::IdentifyUnknownSection(), and v8::internal::wasm::WasmSectionIterator::next().
InitializeCompilationForTesting()
V8_EXPORT_PRIVATE void v8::internal::wasm::InitializeCompilationForTesting (NativeModule * native_module)
Definition at line 1723 of file module-compiler.cc.
                                                                  {
  Impl(native_module->compilation_state())
      ->InitializeCompilationProgress(nullptr);
}
References v8::internal::wasm::NativeModule::compilation_state(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::Impl(), and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::InitializeCompilationProgress().
InitializeElementSegment()
std::optional< MessageTemplate > v8::internal::wasm::InitializeElementSegment (Zone * zone, Isolate * isolate, DirectHandle< WasmTrustedInstanceData > trusted_instance_data, DirectHandle< WasmTrustedInstanceData > shared_trusted_instance_data, uint32_t segment_index)
Definition at line 3254 of file module-instantiate.cc.
                            {
  bool shared =
      trusted_instance_data->module()->elem_segments[segment_index].shared;
  DirectHandle<WasmTrustedInstanceData> data =
      shared ? shared_trusted_instance_data : trusted_instance_data;
  if (!IsUndefined(data->element_segments()->get(segment_index))) return {};
  const NativeModule* native_module = data->native_module();
  const WasmModule* module = native_module->module();
  const WasmElemSegment& elem_segment = module->elem_segments[segment_index];
  base::Vector<const uint8_t> module_bytes = native_module->wire_bytes();
  Decoder decoder(module_bytes);
  decoder.consume_bytes(elem_segment.elements_wire_bytes_offset);
  DirectHandle<FixedArray> result =
      isolate->factory()->NewFixedArray(elem_segment.element_count);
  for (size_t i = 0; i < elem_segment.element_count; ++i) {
    ValueOrError value = ConsumeElementSegmentEntry(
        zone, isolate, trusted_instance_data, shared_trusted_instance_data,
        elem_segment, decoder, kStrictFunctionsAndNull);
    if (is_error(value)) return {to_error(value)};
    result->set(static_cast<int>(i), *to_value(value).to_ref());
  }
  data->element_segments()->set(segment_index, *result);
  return {};
}
References v8::internal::wasm::Decoder::consume_bytes(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::ConsumeElementSegmentEntry(), v8::internal::wasm::WasmModule::elem_segments, v8::internal::wasm::WasmElemSegment::element_count, v8::internal::wasm::WasmElemSegment::elements_wire_bytes_offset, v8::internal::Isolate::factory(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, is_error(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::kStrictFunctionsAndNull, v8::internal::wasm::NativeModule::module(), v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::base::internal::result, to_error(), to_value(), v8::internal::value, and v8::internal::wasm::NativeModule::wire_bytes().
Referenced by v8::internal::WasmTrustedInstanceData::InitTableEntries(), and v8::internal::RUNTIME_FUNCTION().
InitInstructionTableOnce()
void v8::internal::wasm::InitInstructionTableOnce (Isolate * isolate)
Definition at line 602 of file wasm-interpreter.cc.
                                                {
  size_t index = 0;
#define V(name) \
  if (v8_flags.drumbrake_compact_bytecode) { \
    kInstructionTable[index] = reinterpret_cast<PWasmOp*>(\
        isolate->builtins()->code(Builtin::k##name##_s)->instruction_start()); \
  } \
  kInstructionTable[kInstructionCount + index++] = reinterpret_cast<PWasmOp*>(\
      isolate->builtins()->code(Builtin::k##name##_l)->instruction_start());
#ifdef __clang__
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wcast-calling-convention"
#endif // __clang__
  FOREACH_LOAD_STORE_INSTR_HANDLER(V)
#ifdef __clang__
#pragma clang diagnostic pop
#endif // __clang__
#undef V
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
  if (v8_flags.trace_drumbrake_compact_bytecode) {
    index = 0;
#define DEFINE_INSTR_HANDLER(name) kInstructionHandlerNames[index++] = #name;
    FOREACH_INSTR_HANDLER(DEFINE_INSTR_HANDLER)
    FOREACH_TRACE_INSTR_HANDLER(DEFINE_INSTR_HANDLER)
#undef DEFINE_INSTR_HANDLER
  }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
}
References DEFINE_INSTR_HANDLER, FOREACH_INSTR_HANDLER, FOREACH_LOAD_STORE_INSTR_HANDLER, v8::internal::index, and v8::internal::v8_flags.
Referenced by v8::internal::wasm::WasmInterpreter::WasmInterpreter().
InitTrapHandlersOnce()
void v8::internal::wasm::InitTrapHandlersOnce (Isolate * isolate)
Definition at line 578 of file wasm-interpreter.cc.
                                            {
  CHECK_LE(kInstructionCount, kInstructionTableSize);
  ClearThreadInWasmScope wasm_flag(isolate);
  // Overwrites the instruction handlers that access memory and can cause an
  // out-of-bounds trap with builtin versions that don't have explicit bounds
  // check but rely on a trap handler to intercept the access violation and
  // transform it into a trap.
  EmbeddedData embedded_data = EmbeddedData::FromBlob();
#define V(name) \
  if (v8_flags.drumbrake_compact_bytecode) { \
    trap_handler::RegisterHandlerData(\
        reinterpret_cast<Address>(kInstructionTable[k_##name]), \
        embedded_data.InstructionSizeOf(Builtin::k##name##_s), 0, nullptr); \
  } \
  trap_handler::RegisterHandlerData(\
      reinterpret_cast<Address>(\
          kInstructionTable[k_##name + kInstructionCount]), \
      embedded_data.InstructionSizeOf(Builtin::k##name##_l), 0, nullptr);
  FOREACH_LOAD_STORE_INSTR_HANDLER(V)
#undef V
}
References CHECK_LE, FOREACH_LOAD_STORE_INSTR_HANDLER, v8::internal::EmbeddedData::FromBlob(), kInstructionCount, and kInstructionTableSize.
Referenced by v8::internal::wasm::WasmInterpreter::WasmInterpreter().
InstantiateToInstanceObject()
MaybeDirectHandle< WasmInstanceObject > v8::internal::wasm::InstantiateToInstanceObject (Isolate * isolate, ErrorThrower * thrower, DirectHandle< WasmModuleObject > module_object, MaybeDirectHandle< JSReceiver > imports, MaybeDirectHandle< JSArrayBuffer > memory_buffer)
Definition at line 1403 of file module-instantiate.cc.
                                                    {
  v8::metrics::Recorder::ContextId context_id =
      isolate->GetOrRegisterRecorderContextId(isolate->native_context());
  InstanceBuilder builder(isolate, context_id, thrower, module_object, imports,
                          memory_buffer);
  MaybeDirectHandle<WasmInstanceObject> instance_object = builder.Build();
  if (!instance_object.is_null()) {
    const std::shared_ptr<NativeModule>& native_module =
        module_object->shared_native_module();
    if (v8_flags.experimental_wasm_pgo_to_file &&
        native_module->ShouldPgoDataBeWritten() &&
        native_module->module()->num_declared_functions > 0) {
      WriteOutPGOTask::Schedule(native_module);
    }
    if (builder.ExecuteStartFunction() &&
        builder.ConfigurePrototypes_Modular()) {
      builder.FinalizeExportsObject(instance_object);
      return instance_object;
    }
  }
  DCHECK(isolate->has_exception() || thrower->error());
  return {};
}
References v8::internal::wasm::InstanceBuilder::Build(), v8::internal::wasm::InstanceBuilder::ConfigurePrototypes_Modular(), v8::internal::DCHECK(), v8::internal::wasm::ErrorThrower::error(), v8::internal::wasm::InstanceBuilder::ExecuteStartFunction(), v8::internal::wasm::InstanceBuilder::FinalizeExportsObject(), v8::internal::Isolate::GetOrRegisterRecorderContextId(), v8::internal::Isolate::has_exception(), v8::internal::instance_object, v8::internal::Isolate::native_context(), and v8::internal::v8_flags.
Referenced by v8::internal::wasm::WasmEngine::SyncInstantiate().
int64_div_wrapper()
V8_EXPORT_PRIVATE int32_t v8::internal::wasm::int64_div_wrapper (Address data)
Definition at line 299 of file wasm-external-refs.cc.
                                        {
  int64_t dividend = ReadUnalignedValue<int64_t>(data);
  int64_t divisor = ReadUnalignedValue<int64_t>(data + sizeof(dividend));
  if (divisor == 0) {
    return 0;
  }
  if (divisor == -1 && dividend == std::numeric_limits<int64_t>::min()) {
    return -1;
  }
  WriteUnalignedValue<int64_t>(data, dividend / divisor);
  return 1;
}
int64_mod_wrapper()
V8_EXPORT_PRIVATE int32_t v8::internal::wasm::int64_mod_wrapper (Address data)
Definition at line 312 of file wasm-external-refs.cc.
                                        {
  int64_t dividend = ReadUnalignedValue<int64_t>(data);
  int64_t divisor = ReadUnalignedValue<int64_t>(data + sizeof(dividend));
  if (divisor == 0) {
    return 0;
  }
  if (divisor == -1 && dividend == std::numeric_limits<int64_t>::min()) {
    WriteUnalignedValue<int64_t>(data, 0);
    return 1;
  }
  WriteUnalignedValue<int64_t>(data, dividend % divisor);
  return 1;
}
int64_to_float32_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::int64_to_float32_wrapper (Address data)
Definition at line 92 of file wasm-external-refs.cc.
                                            {
  int64_t input = ReadUnalignedValue<int64_t>(data);
  WriteUnalignedValue<float>(data, static_cast<float>(input));
}
int64_to_float64_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::int64_to_float64_wrapper (Address data)
Definition at line 168 of file wasm-external-refs.cc.
                                            {
  int64_t input = ReadUnalignedValue<int64_t>(data);
  WriteUnalignedValue<double>(data, static_cast<double>(input));
}
Intersection()
V8_EXPORT_PRIVATE TypeInModule v8::internal::wasm::Intersection (ValueType type1, ValueType type2, const WasmModule * module)
Definition at line 626 of file wasm-subtyping.cc.
                                                    {
  if (type1 == kWasmTop) return {type2, module};
  if (type2 == kWasmTop) return {type1, module};
  if (!type1.is_ref() || !type2.is_ref()) {
    return {type1 == type2 ? type1 : kWasmBottom, module};
  }
  Nullability nullability =
      type1.is_nullable() && type2.is_nullable() ? kNullable : kNonNullable;
  // non-nullable null type is not a valid type.
  if (nullability == kNonNullable &&
      (IsNullSentinel(type1) || IsNullSentinel(type2))) {
    return {kWasmBottom, module};
  }
  if (IsHeapSubtypeOf(type1.heap_type(), type2.heap_type(), module)) {
    return TypeInModule{type1.AsNullable(nullability), module};
  }
  if (IsHeapSubtypeOf(type2.heap_type(), type1.heap_type(), module)) {
    return TypeInModule{type2.AsNullable(nullability), module};
  }
  if (nullability == kNonNullable) {
    return {kWasmBottom, module};
  }
  // Check for common null representation.
  ValueType null_type1 = ToNullSentinel({type1, module});
  if (null_type1 == ToNullSentinel({type2, module})) {
    return {null_type1, module};
  }
  return {kWasmBottom, module};
}
References v8::internal::wasm::ValueType::AsNullable(), v8::internal::wasm::ValueType::heap_type(), v8::internal::wasm::ValueTypeBase::is_nullable(), v8::internal::wasm::ValueTypeBase::is_ref(), IsHeapSubtypeOf(), v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::IsNullSentinel(), kNonNullable, kNullable, kWasmBottom, kWasmTop, and ToNullSentinel().
Referenced by v8::internal::compiler::anonymous_namespace{wasm-gc-operator-reducer.cc}::Intersection(), v8::internal::compiler::WasmTyper::Reduce(), v8::internal::compiler::WasmGCOperatorReducer::ReduceIf(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCastAbstract(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::RefineTypeKnowledge(), v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::WasmTypeCast(), and v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::WasmTypeCheck().
is_asmjs_module()
bool v8::internal::wasm::is_asmjs_module (const WasmModule * module) [inline]
Definition at line 961 of file wasm-module.h.
                                                      {
  return module->origin != kWasmOrigin;
}
References kWasmOrigin, and v8::internal::wasm::WasmModule::origin.
Referenced by v8::internal::wasm::InstanceBuilder::Build_Phase1(), CanUseGenericJsToWasmWrapper(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeAsmJsOpcode(), v8::internal::wasm::ModuleDecoderImpl::DecodeFunctionSection(), v8::internal::wasm::InliningTree::FullyExpand(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::GetDefaultTiersPerModule(), GetSourcePosition(), v8::internal::GetWasmFunctionDebugName(), v8::internal::WasmModuleObject::is_asm_js(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::IsLazyModule(), v8::internal::WasmExportedFunction::New(), v8::internal::wasm::InstanceBuilder::ProcessExports(), v8::internal::wasm::InstanceBuilder::ProcessImportedGlobal(), v8::internal::wasm::InstanceBuilder::SanitizeImports(), v8::internal::wasm::TurboshaftGraphBuildingInterface::should_inline(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StartFunction(), v8::internal::JSFunction::ToString(), and v8::internal::compiler::turboshaft::WasmInJSInliningReducer< Next >::TryInlineWasmCall().
is_error()
bool v8::internal::wasm::is_error (ValueOrError result) [inline]
Definition at line 120 of file constant-expression.h.
                                             {
  return std::holds_alternative<MessageTemplate>(result);
}
References v8::base::internal::result.
Referenced by InitializeElementSegment(), and v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::MaybeMarkError().
is_object_reference()
constexpr bool v8::internal::wasm::is_object_reference (ValueKind kind) [constexpr]
Definition at line 1158 of file value-type.h.
                                                   {
  return kind == kRef || kind == kRefNull;
}
References v8::internal::kRef, and v8::internal::kRefNull.
Referenced by v8::internal::wasm::ParallelMove::MoveRegister(), and v8::internal::WasmGlobalObject::SetRef().
is_packed()
constexpr bool v8::internal::wasm::is_packed (ValueKind kind) [constexpr]
Definition at line 1224 of file value-type.h.
                                         {
  return kind == kI8 || kind == kI16 || kind == kF16;
}
References v8::internal::kI16, and v8::internal::kI8.
Referenced by v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::CopyElements(), v8::internal::Map::FindElementsKindTransitionedMap(), and unpacked().
is_reference()
constexpr bool v8::internal::wasm::is_reference (ValueKind kind) [constexpr]
Definition at line 1154 of file value-type.h.
                                            {
  return kind == kRef || kind == kRefNull;
}
References v8::internal::kRef, and v8::internal::kRefNull.
Referenced by v8::internal::WasmGlobalObject::address(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayAtomicCompareExchange(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayAtomicRMW(), v8::internal::wasm::LiftoffAssembler::CacheState::DefineSafepoint(), v8::internal::wasm::LiftoffAssembler::CacheState::DefineSafepointWithCalleeSavedRegisters(), v8::internal::WasmArray::ElementSlot(), v8::internal::wasm::LiftoffAssembler::emit_cond_jump(), v8::internal::WasmGlobalObject::GetRef(), v8::internal::wasm::LiftoffAssembler::CacheState::GetTaggedSlotsForOOLCode(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GetValueTypeHelper(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GlobalGet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GlobalSet(), v8::internal::wasm::WasmBytecode::HasRefOrSimdArgs(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::LoadAtomicObjectField(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::LoadObjectField(), v8::internal::wasm::LiftoffAssembler::Move(), v8::internal::wasm::LiftoffAssembler::NeedsAlignment(), v8::internal::wasm::WasmBytecode::RefArgsCount(), v8::internal::wasm::WasmBytecode::RefLocalsCount(), v8::internal::wasm::WasmBytecodeGenerator::RefPop(), v8::internal::wasm::WasmBytecode::RefRetsCount(), v8::internal::WasmArray::SetTaggedElement(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StartFunctionBody(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StoreAtomicObjectField(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StoreObjectField(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructAtomicCompareExchange(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StructAtomicRMW(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructAtomicRMW(), v8::internal::wasm::WasmBytecodeGenerator::ToRegisterIsAllowed(), and value_kind_full_size().
IsCompileTimeImport()
bool v8::internal::wasm::IsCompileTimeImport (WellKnownImport wki) [inline]
Definition at line 111 of file well-known-imports.h.
                                                     {
  using T = std::underlying_type_t<WellKnownImport>;
  T num = static_cast<T>(wki);
  constexpr T kFirst = static_cast<T>(WellKnownImport::kFirstCompileTimeImport);
  constexpr T kLast = static_cast<T>(WellKnownImport::kLastCompileTimeImport);
  return kFirst <= num && num <= kLast;
}
References kFirstCompileTimeImport, v8::internal::kLast, and kLastCompileTimeImport.
Referenced by v8::internal::wasm::ResolvedWasmImport::ComputeKind(), GetImports(), and v8::internal::wasm::InstanceBuilder::SanitizeImports().
IsCrossInstanceCall()
bool v8::internal::wasm::IsCrossInstanceCall (Tagged< Object > obj, Isolate *const isolate)
Definition at line 1351 of file module-compiler.cc.
                                                                     {
  return obj == ReadOnlyRoots{isolate}.wasm_cross_instance_call_symbol();
}
Referenced by v8::internal::wasm::FeedbackMaker::AddCallIndirectCandidate(), and v8::internal::wasm::TransitiveTypeFeedbackProcessor::ProcessFunction().
IsHeapSubtypeOf()
bool v8::internal::wasm::IsHeapSubtypeOf (HeapType subtype, HeapType supertype, const WasmModule * module) [inline]
Definition at line 91 of file wasm-subtyping.h.
                                                         {
  // If the types are trivially identical, exit early.
  if (V8_LIKELY(subtype == supertype)) return true;
  return IsSubtypeOfImpl(subtype, supertype, module, module);
}
References IsSubtypeOfImpl(), and V8_LIKELY.
Referenced by HeapTypesUnrelated(), Intersection(), v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::ParseArrayLen(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCastAbstract(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCheck(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCheckAbstract(), ToNullSentinel(), v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::ValidContinuationSubtypeDefinition(), v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::ValidStructSubtypeDefinition(), v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::WasmTypeCast(), and v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::WasmTypeCheck().
IsJSCompatibleSignature()
V8_EXPORT_PRIVATE bool v8::internal::wasm::IsJSCompatibleSignature (const CanonicalSig * sig)
Definition at line 31 of file wasm-opcodes.cc.
                                                      {
  for (auto type : sig->all()) {
    if (type == kWasmS128) return false;
    if (type.is_ref() && !type.has_index()) {
      switch (type.generic_kind()) {
        case GenericKind::kStringViewWtf8:
        case GenericKind::kStringViewWtf16:
        case GenericKind::kStringViewIter:
        case GenericKind::kExn:
        case GenericKind::kNoExn:
        case GenericKind::kCont:
        case GenericKind::kNoCont:
          return false;
        default:
          break;
      }
    }
  }
  return true;
}
References kWasmS128, v8::internal::sig, and v8::internal::tracing::type.
Referenced by v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildJSToWasmWrapper(), v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::BuildJSToWasmWrapper(), v8::internal::wasm::WasmImportWrapperCache::BuiltinForWrapper(), v8::internal::wasm::WasmInterpreterRuntime::CallExternalJSFunction(), CanUseGenericJsToWasmWrapper(), v8::internal::wasm::ResolvedWasmImport::ComputeKind(), v8::internal::WasmJSFunction::New(), v8::anonymous_namespace{wasm-js.cc}::NewPromisingWasmExportedFunction(), and v8::internal::UseGenericWasmToJSWrapper().
IsNullKind()
constexpr bool v8::internal::wasm::IsNullKind (GenericKind kind) [constexpr]
Definition at line 321 of file value-type.h.
                                            {
  switch (kind) {
#define NULLTYPE(name, ...) \
  case GenericKind::k##name: \
    return true;
    FOREACH_NONE_TYPE(NULLTYPE)
#undef NULLTYPE
    default:
      break;
  }
  return false;
}
References FOREACH_NONE_TYPE, and NULLTYPE.
Referenced by v8::internal::wasm::ValueTypeBase::is_uninhabited(), v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::IsGenericSubtypeOfIndexedTypes(), and v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::IsNullSentinel().
IsSameTypeHierarchy()
bool v8::internal::wasm::IsSameTypeHierarchy (HeapType type1, HeapType type2, const WasmModule * module)
Definition at line 663 of file wasm-subtyping.cc.
                                                   {
  return NullSentinelImpl(type1) == NullSentinelImpl(type2);
}
References v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::NullSentinelImpl().
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeGCOpcode(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::ParseBrOnCast(), v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::WasmTypeCast(), and v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::WasmTypeCheck().
IsSubtypeOf() [1/3]
bool v8::internal::wasm::IsSubtypeOf (CanonicalValueType subtype, CanonicalValueType supertype) [inline]
Definition at line 84 of file wasm-subtyping.h.
                                                         {
  if (subtype == supertype) return true;
  return IsSubtypeOfImpl(subtype, supertype);
}
References IsSubtypeOfImpl().
IsSubtypeOf() [2/3]
bool v8::internal::wasm::IsSubtypeOf (ValueType subtype, ValueType supertype, const WasmModule * module) [inline]
Definition at line 77 of file wasm-subtyping.h.
                                                     {
  // If the types are trivially identical, exit early.
  if (V8_LIKELY(subtype == supertype)) return true;
  return IsSubtypeOfImpl(subtype, supertype, module, module);
}
References IsSubtypeOfImpl(), and V8_LIKELY.
IsSubtypeOf() [3/3]
bool v8::internal::wasm::IsSubtypeOf (ValueType subtype, ValueType supertype, const WasmModule * sub_module, const WasmModule * super_module) [inline]
Definition at line 68 of file wasm-subtyping.h.
                                                           {
  if (subtype == supertype && sub_module == super_module) return true;
  return IsSubtypeOfImpl(subtype, supertype, sub_module, super_module);
}
References IsSubtypeOfImpl().
Referenced by v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::AssertNotNull(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::CanReturnCall(), v8::internal::wasm::ModuleDecoderImpl::consume_element_func_index(), v8::internal::wasm::ModuleDecoderImpl::consume_element_segment_header(), v8::internal::torque::DeclarationVisitor::CreateBuiltin(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeAtomicOpcode(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeGCOpcode(), v8::internal::WasmTableObject::GetFunctionTableEntry(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineTargetIsTypeCompatible(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::IsSubtypeVec(), v8::internal::wasm::InstanceBuilder::LoadTableSegments(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::ParseBrOnCast(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessBranchOnTarget(), v8::internal::wasm::InstanceBuilder::ProcessImportedTable(), v8::internal::wasm::InstanceBuilder::ProcessImportedWasmGlobalObject(), v8::internal::wasm::WasmInterpreterRuntime::PurgeIndirectCallCache(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PushControl(), v8::internal::compiler::WasmTyper::Reduce(), v8::internal::compiler::WasmGCLowering::ReduceAssertNotNull(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCastAbstract(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ReduceWasmTypeCastAbstract(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ReduceWasmTypeCastRtt(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheck(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheckAbstract(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ReduceWasmTypeCheckAbstract(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ReduceWasmTypeCheckRtt(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::RefAsNonNull(), v8::internal::wasm::InstanceBuilder::SetTableInitialValues(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SubtypeCheck(), v8::internal::wasm::WasmInterpreterRuntime::SubtypeCheck(), v8::internal::wasm::WasmInterpreterRuntime::TableCopy(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::TableGet(), v8::internal::wasm::WasmInterpreterRuntime::TableInit(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::TableSet(), v8::internal::compiler::WasmLoadElimination::TruncateAndExtendOrType(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::TypeCheckAlwaysFails(), v8::internal::wasm::WasmBytecodeGenerator::TypeCheckAlwaysFails(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::TypeCheckAlwaysSucceeds(), v8::internal::wasm::WasmBytecodeGenerator::TypeCheckAlwaysSucceeds(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::TypeCheckOneArmedIf(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::TypeCheckStackAgainstMerge_Slow(), v8::internal::compiler::anonymous_namespace{wasm-load-elimination.cc}::TypesUnrelated(), v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::ValidArraySubtypeDefinition(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::ValidateStackValue(), v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::ValidFunctionSubtypeDefinition(), v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::ValidStructSubtypeDefinition(), and v8::internal::wasm::InstanceBuilder::WriteGlobalValue().
IsSubtypeOfImpl() [1/3]
V8_NOINLINE V8_EXPORT_PRIVATE bool v8::internal::wasm::IsSubtypeOfImpl (CanonicalValueType subtype, CanonicalValueType supertype)
Definition at line 462 of file wasm-subtyping.cc.
                                                              {
  DCHECK_NE(subtype, supertype); // Caller has checked.
  if (supertype.is_top()) return true;
  if (subtype.is_numeric()) return false;
  if (supertype.is_numeric()) return subtype.is_bottom();
  if (subtype.is_nullable() && !supertype.is_nullable()) return false;
  std::optional<bool> result = IsSubtypeOf_CommonImpl(subtype, supertype);
  if (result.has_value()) return result.value();
  DCHECK(subtype.has_index() && supertype.has_index());
  CanonicalTypeIndex sub_index = subtype.ref_index();
  CanonicalTypeIndex super_index = supertype.ref_index();
  // Can happen despite subtype != supertype, e.g. when nullability differs.
  if (sub_index == super_index) return true;
  if (supertype.is_exact()) return false;
  return GetTypeCanonicalizer()->IsHeapSubtype(sub_index, super_index);
}
References v8::internal::DCHECK(), DCHECK_NE, GetTypeCanonicalizer(), v8::internal::wasm::ValueTypeBase::has_index(), v8::internal::wasm::ValueTypeBase::is_bottom(), v8::internal::wasm::ValueTypeBase::is_exact(), v8::internal::wasm::ValueTypeBase::is_nullable(), v8::internal::wasm::ValueTypeBase::is_numeric(), v8::internal::wasm::ValueTypeBase::is_top(), v8::internal::wasm::TypeCanonicalizer::IsHeapSubtype(), v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::IsSubtypeOf_CommonImpl(), v8::internal::wasm::CanonicalValueType::ref_index(), and v8::base::internal::result.
IsSubtypeOfImpl() [2/3]
V8_NOINLINE V8_EXPORT_PRIVATE bool v8::internal::wasm::IsSubtypeOfImpl (HeapType subtype, HeapType supertype, const WasmModule * sub_module, const WasmModule * super_module)
Definition at line 421 of file wasm-subtyping.cc.
                                    {
  DCHECK(subtype != supertype || sub_module != super_module);
  std::optional<bool> result = IsSubtypeOf_CommonImpl(subtype, supertype);
  if (result.has_value()) return result.value();
  DCHECK(subtype.has_index() && supertype.has_index());
  ModuleTypeIndex sub_index = subtype.ref_index();
  CanonicalTypeIndex super_canon =
      super_module->canonical_type_id(supertype.ref_index());
  // Comparing canonicalized type indices handles both different modules
  // and different recgroups in the same module.
  if (supertype.is_exact()) {
    return sub_module->canonical_type_id(sub_index) == super_canon;
  }
  do {
    if (sub_module->canonical_type_id(sub_index) == super_canon) return true;
    sub_index = sub_module->supertype(sub_index);
  } while (sub_index.valid());
  return false;
}
References v8::internal::wasm::WasmModule::canonical_type_id(), v8::internal::DCHECK(), v8::internal::wasm::ValueTypeBase::has_index(), v8::internal::wasm::ValueTypeBase::is_exact(), v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::IsSubtypeOf_CommonImpl(), v8::internal::wasm::HeapType::ref_index(), v8::base::internal::result, v8::internal::wasm::WasmModule::supertype(), and v8::internal::wasm::TypeIndex::valid().
Referenced by IsHeapSubtypeOf(), IsSubtypeOf(), and IsSubtypeOfImpl().
IsSubtypeOfImpl() [3/3]
V8_NOINLINE V8_EXPORT_PRIVATE bool v8::internal::wasm::IsSubtypeOfImpl (ValueType subtype, ValueType supertype, const WasmModule * sub_module, const WasmModule * super_module)
Definition at line 444 of file wasm-subtyping.cc.
                                    {
  // Note: it seems tempting to handle <top> and the numeric types
  // with the lookup-based mechanism we'll ultimately call. But that would
  // require guarding the checks for nullability and sharedness behind
  // checks for being reftypes, so it would end up being more complicated,
  // not less.
  if (supertype.is_top()) return true;
  if (subtype.is_numeric()) return subtype == supertype;
  if (supertype.is_numeric()) return subtype.is_bottom();
  if (subtype.is_nullable() && !supertype.is_nullable()) return false;
  HeapType sub_heap = subtype.heap_type();
  HeapType super_heap = supertype.heap_type();
  if (sub_heap == super_heap && sub_module == super_module) return true;
  return IsSubtypeOfImpl(sub_heap, super_heap, sub_module, super_module);
}
References v8::internal::wasm::ValueType::heap_type(), v8::internal::wasm::ValueTypeBase::is_bottom(), v8::internal::wasm::ValueTypeBase::is_nullable(), v8::internal::wasm::ValueTypeBase::is_numeric(), v8::internal::wasm::ValueTypeBase::is_top(), and IsSubtypeOfImpl().
IsSupportedVersion()
bool v8::internal::wasm::IsSupportedVersion (base::Vector< const uint8_t > header, WasmEnabledFeatures enabled_features)
Definition at line 1081 of file wasm-serialization.cc.
                                                              {
  if (header.size() < WasmSerializer::kHeaderSize) return false;
  uint8_t current_version[WasmSerializer::kHeaderSize];
  Writer writer({current_version, WasmSerializer::kHeaderSize});
  WriteHeader(&writer, enabled_features);
  return memcmp(header.begin(), current_version, WasmSerializer::kHeaderSize) ==
         0;
}
References v8::base::Vector< T >::begin(), v8::internal::wasm::WasmSerializer::kHeaderSize, v8::base::Vector< T >::size(), and v8::internal::WriteHeader().
Referenced by DeserializeNativeModule(), and v8::WasmStreaming::WasmStreamingImpl::SetCompiledModuleBytes().
IsValidSectionCode()
bool v8::internal::wasm::IsValidSectionCode (uint8_t byte) [inline]
Definition at line 31 of file module-decoder.h.
                                             {
  // Allow everything within [kUnknownSectionCode, kLastKnownModuleSection].
  static_assert(kUnknownSectionCode == 0);
  return byte <= kLastKnownModuleSection;
}
References kLastKnownModuleSection, and kUnknownSectionCode.
Referenced by v8::internal::wasm::WasmSectionIterator::next(), and v8::internal::wasm::AsyncStreamingDecoder::DecodeSectionID::Next().
IsWasmCodegenAllowed()
V8_EXPORT_PRIVATE bool v8::internal::wasm::IsWasmCodegenAllowed (Isolate * isolate, DirectHandle< NativeContext > context)
Definition at line 260 of file wasm-module.cc.
                                                               {
  // TODO(wasm): Once wasm has its own CSP policy, we should introduce a
  // separate callback that includes information about the module about to be
  // compiled. For the time being, pass an empty string as placeholder for the
  // sources.
  if (auto wasm_codegen_callback = isolate->allow_wasm_code_gen_callback()) {
    return wasm_codegen_callback(
        v8::Utils::ToLocal(context),
        v8::Utils::ToLocal(isolate->factory()->empty_string()));
  }
  return true;
}
References v8::internal::Isolate::factory().
Referenced by DeserializeNativeModule(), v8::anonymous_namespace{wasm-js.cc}::StartAsyncCompilationWithResolver(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyCompileImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyInstantiateImpl(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyModuleImpl().
IterateSignatureImpl()
template<class ResultCollector , class SigType >
void v8::internal::wasm::IterateSignatureImpl (const SigType * sig, bool extra_callable_param, ResultCollector & locations, int * untagged_parameter_slots, int * total_parameter_slots, int * untagged_return_slots, int * total_return_slots)
Definition at line 42 of file signature-hashing.h.
                                                                               {
  constexpr int kParamsSlotOffset = 0;
  LinkageLocationAllocator params(kGpParamRegisters, kFpParamRegisters,
                                  kParamsSlotOffset);
  // The instance object.
  locations.AddParamAt(0, params.Next(MachineRepresentation::kTaggedPointer));
  const size_t param_offset = 1; // Actual params start here.
  // Parameters are separated into two groups (first all untagged, then all
  // tagged parameters). This allows for easy iteration of tagged parameters
  // during frame iteration. It also allows for easy signature verification
  // based on counts.
  const size_t parameter_count = sig->parameter_count();
  bool has_tagged_param = false;
  for (size_t i = 0; i < parameter_count; i++) {
    MachineRepresentation param = GetMachineRepresentation(sig->GetParam(i));
    // Skip tagged parameters (e.g. any-ref).
    if (IsAnyTagged(param)) {
      has_tagged_param = true;
      continue;
    }
    locations.AddParamAt(i + param_offset, params.Next(param));
  }
  params.EndSlotArea(); // End the untagged area. Tagged slots come after.
  *untagged_parameter_slots = params.NumStackSlots();
  if (has_tagged_param) {
    for (size_t i = 0; i < parameter_count; i++) {
      MachineRepresentation param = GetMachineRepresentation(sig->GetParam(i));
      if (!IsAnyTagged(param)) continue; // Skip untagged parameters.
      locations.AddParamAt(i + param_offset, params.Next(param));
    }
  }
  // Import call wrappers have an additional (implicit) parameter, the callable.
  // For consistency with JS, we use the JSFunction register.
  if (extra_callable_param) {
    locations.AddParamAt(
        parameter_count + param_offset,
        LinkageLocation::ForRegister(kJSFunctionRegister.code(),
                                     MachineType::TaggedPointer()));
  }
  int params_stack_height = AddArgumentPaddingSlots(params.NumStackSlots());
  *total_parameter_slots = params_stack_height;
  // Add return location(s).
  // For efficient signature verification, order results by taggedness, such
  // that all untagged results appear first in registers and on the stack,
  // followed by tagged results. That way, we can simply check the size of
  // each section, rather than needing a bit map.
  LinkageLocationAllocator rets(kGpReturnRegisters, kFpReturnRegisters,
                                params_stack_height);
  const size_t return_count = sig->return_count();
  bool has_tagged_result = false;
  for (size_t i = 0; i < return_count; i++) {
    MachineRepresentation ret = GetMachineRepresentation(sig->GetReturn(i));
    if (IsAnyTagged(ret)) {
      has_tagged_result = true;
      continue;
    }
    locations.AddReturnAt(i, rets.Next(ret));
  }
  rets.EndSlotArea(); // End the untagged area.
  *untagged_return_slots = rets.NumStackSlots();
  if (has_tagged_result) {
    for (size_t i = 0; i < return_count; i++) {
      MachineRepresentation ret = GetMachineRepresentation(sig->GetReturn(i));
      if (!IsAnyTagged(ret)) continue;
      locations.AddReturnAt(i, rets.Next(ret));
    }
  }
  *total_return_slots = rets.NumStackSlots();
}
References v8::internal::AddArgumentPaddingSlots(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::wasm::LinkageLocationAllocator::EndSlotArea(), v8::internal::LinkageLocation::ForRegister(), GetMachineRepresentation(), v8::internal::IsAnyTagged(), kFpParamRegisters, kFpReturnRegisters, kGpParamRegisters, kGpReturnRegisters, v8::internal::kJSFunctionRegister, v8::internal::kTaggedPointer, v8::internal::wasm::LinkageLocationAllocator::Next(), v8::internal::wasm::LinkageLocationAllocator::NumStackSlots(), v8::internal::sig, and v8::internal::MachineType::TaggedPointer().
Referenced by v8::internal::compiler::BuildLocations().
JSToWasmObject() [1/2]
MaybeDirectHandle< Object > v8::internal::wasm::JSToWasmObject (Isolate * isolate, const WasmModule * module, DirectHandle< Object > value, ValueType expected, const char ** error_message)
Definition at line 3625 of file wasm-objects.cc.
                                                                     {
  CanonicalValueType canonical;
  if (expected.has_index()) {
    canonical = module->canonical_type(expected);
  } else {
    canonical = CanonicalValueType{expected};
  }
  return JSToWasmObject(isolate, value, canonical, error_message);
}
References v8::internal::wasm::WasmModule::canonical_type(), v8::internal::wasm::ValueTypeBase::has_index(), JSToWasmObject(), and v8::internal::value.
JSToWasmObject() [2/2]
MaybeDirectHandle< Object > v8::internal::wasm::JSToWasmObject (Isolate * isolate, DirectHandle< Object > value, CanonicalValueType expected, const char ** error_message)
Definition at line 3408 of file wasm-objects.cc.
                                                                     {
  DCHECK(expected.is_object_reference());
  if (expected.kind() == kRefNull && IsNull(*value, isolate)) {
    switch (expected.heap_representation()) {
      case HeapType::kStringViewWtf8:
        *error_message = "stringview_wtf8 has no JS representation";
        return {};
      case HeapType::kStringViewWtf16:
        *error_message = "stringview_wtf16 has no JS representation";
        return {};
      case HeapType::kStringViewIter:
        *error_message = "stringview_iter has no JS representation";
        return {};
      case HeapType::kExn:
        *error_message = "invalid type (ref null exn)";
        return {};
      case HeapType::kNoExn:
        *error_message = "invalid type (ref null noexn)";
        return {};
      case HeapType::kNoCont:
        *error_message = "invalid type (ref null nocont)";
        return {};
      case HeapType::kCont:
        *error_message = "invalid type (ref null cont)";
        return {};
      default:
        return expected.use_wasm_null() ? isolate->factory()->wasm_null()
                                        : value;
    }
  }
  switch (expected.heap_representation_non_shared()) {
    case HeapType::kFunc: {
      if (!(WasmExternalFunction::IsWasmExternalFunction(*value) ||
            WasmCapiFunction::IsWasmCapiFunction(*value))) {
        *error_message =
            "function-typed object must be null (if nullable) or a Wasm "
            "function object";
        return {};
      }
      return direct_handle(
          Cast<JSFunction>(*value)->shared()->wasm_function_data()->func_ref(),
          isolate);
    }
    case HeapType::kExtern: {
      if (!ConvertToSharedIfExpected(isolate, &value, expected,
                                     error_message)) {
        return {};
      }
      if (!IsNull(*value, isolate)) return value;
      *error_message = "null is not allowed for (ref extern)";
      return {};
    }
    case HeapType::kAny: {
      // TODO(mliedtke): We need to construct heap numbers with correct
      // sharedness.
      if (IsSmi(*value)) {
        return CanonicalizeSmi(value, isolate, expected.is_shared());
      }
      if (IsHeapNumber(*value)) {
        return CanonicalizeHeapNumber(value, isolate, expected.is_shared());
      }
      if (!ConvertToSharedIfExpected(isolate, &value, expected,
                                     error_message)) {
        return {};
      }
      if (!IsNull(*value, isolate)) return value;
      *error_message = "null is not allowed for (ref any)";
      return {};
    }
    case HeapType::kExn:
      *error_message = "invalid type (ref exn)";
      return {};
    case HeapType::kCont:
      *error_message = "invalid type (ref cont)";
      return {};
    case HeapType::kStruct: {
      if (!CheckExpectedSharedness(isolate, value, expected, error_message)) {
        return {};
      }
      if (IsWasmStruct(*value)) {
        return value;
      }
      *error_message =
          "structref object must be null (if nullable) or a wasm struct";
      return {};
    }
    case HeapType::kArray: {
      if (!CheckExpectedSharedness(isolate, value, expected, error_message)) {
        return {};
      }
      if (IsWasmArray(*value)) {
        return value;
      }
      *error_message =
          "arrayref object must be null (if nullable) or a wasm array";
      return {};
    }
    case HeapType::kEq: {
      if (IsSmi(*value)) {
        DirectHandle<Object> truncated =
            CanonicalizeSmi(value, isolate, expected.is_shared());
        if (IsSmi(*truncated)) return truncated;
      } else if (IsHeapNumber(*value)) {
        DirectHandle<Object> truncated =
            CanonicalizeHeapNumber(value, isolate, expected.is_shared());
        if (IsSmi(*truncated)) return truncated;
      } else if (IsWasmStruct(*value) || IsWasmArray(*value)) {
        if (!CheckExpectedSharedness(isolate, value, expected, error_message)) {
          return {};
        }
        return value;
      }
      *error_message =
          "eqref object must be null (if nullable), or a wasm "
          "struct/array, or a Number that fits in i31ref range";
      return {};
    }
    case HeapType::kI31: {
      if (IsSmi(*value)) {
        DirectHandle<Object> truncated =
            CanonicalizeSmi(value, isolate, expected.is_shared());
        if (IsSmi(*truncated)) return truncated;
      } else if (IsHeapNumber(*value)) {
        DirectHandle<Object> truncated =
            CanonicalizeHeapNumber(value, isolate, expected.is_shared());
        if (IsSmi(*truncated)) return truncated;
      }
      *error_message =
          "i31ref object must be null (if nullable) or a Number that fits "
          "in i31ref range";
      return {};
    }
    case HeapType::kString:
      if (IsString(*value)) return value;
      *error_message = "wrong type (expected a string)";
      return {};
    case HeapType::kStringViewWtf8:
      *error_message = "stringview_wtf8 has no JS representation";
      return {};
    case HeapType::kStringViewWtf16:
      *error_message = "stringview_wtf16 has no JS representation";
      return {};
    case HeapType::kStringViewIter:
      *error_message = "stringview_iter has no JS representation";
      return {};
    case HeapType::kNoFunc:
    case HeapType::kNoExtern:
    case HeapType::kNoExn:
    case HeapType::kNoCont:
    case HeapType::kNone: {
      *error_message = "only null allowed for null types";
      return {};
    }
    default: {
      DCHECK(expected.has_index());
      CanonicalTypeIndex canonical_index = expected.ref_index();
      auto type_canonicalizer = GetWasmEngine()->type_canonicalizer();
      if (WasmExportedFunction::IsWasmExportedFunction(*value)) {
        Tagged<WasmExportedFunction> function =
            Cast<WasmExportedFunction>(*value);
        CanonicalTypeIndex real_type_index =
            function->shared()->wasm_exported_function_data()->sig_index();
        if (!type_canonicalizer->IsCanonicalSubtype(real_type_index,
                                                    canonical_index)) {
          *error_message =
              "assigned exported function has to be a subtype of the "
              "expected type";
          return {};
        }
        return direct_handle(Cast<WasmExternalFunction>(*value)->func_ref(),
                             isolate);
      } else if (WasmJSFunction::IsWasmJSFunction(*value)) {
        if (!Cast<WasmJSFunction>(*value)
                 ->shared()
                 ->wasm_js_function_data()
                 ->MatchesSignature(canonical_index)) {
          *error_message =
              "assigned WebAssembly.Function has to be a subtype of the "
              "expected type";
          return {};
        }
        return direct_handle(Cast<WasmExternalFunction>(*value)->func_ref(),
                             isolate);
      } else if (WasmCapiFunction::IsWasmCapiFunction(*value)) {
        if (!Cast<WasmCapiFunction>(*value)->MatchesSignature(
                canonical_index)) {
          *error_message =
              "assigned C API function has to be a subtype of the expected "
              "type";
          return {};
        }
        return direct_handle(Cast<WasmExternalFunction>(*value)->func_ref(),
                             isolate);
      } else if (IsWasmStruct(*value) || IsWasmArray(*value)) {
        DirectHandle<WasmObject> wasm_obj = Cast<WasmObject>(value);
        Tagged<WasmTypeInfo> type_info = wasm_obj->map()->wasm_type_info();
        CanonicalTypeIndex actual_type = type_info->type_index();
        if (!type_canonicalizer->IsCanonicalSubtype(actual_type,
                                                    canonical_index)) {
          *error_message = "object is not a subtype of expected type";
          return {};
        }
        return value;
      } else {
        *error_message = "JS object does not match expected wasm type";
        return {};
      }
    }
  }
}
References v8::internal::anonymous_namespace{wasm-objects.cc}::CanonicalizeHeapNumber(), v8::internal::anonymous_namespace{wasm-objects.cc}::CanonicalizeSmi(), v8::internal::wasm::anonymous_namespace{wasm-objects.cc}::CheckExpectedSharedness(), v8::internal::wasm::anonymous_namespace{wasm-objects.cc}::ConvertToSharedIfExpected(), v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::Isolate::factory(), GetWasmEngine(), v8::internal::wasm::ValueTypeBase::has_index(), v8::internal::wasm::CanonicalValueType::heap_representation(), v8::internal::wasm::CanonicalValueType::heap_representation_non_shared(), v8::internal::wasm::ValueTypeBase::is_object_reference(), v8::internal::wasm::ValueTypeBase::is_shared(), v8::internal::IsNull(), v8::internal::IsSmi(), v8::internal::WasmCapiFunction::IsWasmCapiFunction(), v8::internal::WasmExportedFunction::IsWasmExportedFunction(), v8::internal::WasmExternalFunction::IsWasmExternalFunction(), v8::internal::WasmJSFunction::IsWasmJSFunction(), v8::internal::wasm::HeapType::kAny, v8::internal::wasm::HeapType::kArray, v8::internal::wasm::HeapType::kCont, v8::internal::wasm::HeapType::kEq, v8::internal::wasm::HeapType::kExn, v8::internal::wasm::HeapType::kExtern, v8::internal::wasm::HeapType::kFunc, v8::internal::wasm::HeapType::kI31, v8::internal::wasm::ValueTypeBase::kind(), v8::internal::wasm::HeapType::kNoCont, v8::internal::wasm::HeapType::kNoExn, v8::internal::wasm::HeapType::kNoExtern, v8::internal::wasm::HeapType::kNoFunc, v8::internal::wasm::HeapType::kNone, v8::internal::kRefNull, v8::internal::wasm::HeapType::kString, v8::internal::wasm::HeapType::kStringViewIter, v8::internal::wasm::HeapType::kStringViewWtf16, v8::internal::wasm::HeapType::kStringViewWtf8, v8::internal::wasm::HeapType::kStruct, v8::internal::wasm::CanonicalValueType::ref_index(), v8::internal::wasm::WasmEngine::type_canonicalizer(), v8::internal::wasm::ValueTypeBase::use_wasm_null(), and v8::internal::value.
Referenced by v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::EncodeExceptionValues(), v8::internal::WasmTableObject::JSToWasmElement(), JSToWasmObject(), v8::internal::wasm::WasmInterpreterRuntime::JSToWasmObject(), v8::internal::wasm::InstanceBuilder::ProcessImportedGlobal(), v8::internal::RUNTIME_FUNCTION(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyGlobalImpl(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyGlobalSetValueImpl().
JumpTableOffset()
int v8::internal::wasm::JumpTableOffset (const WasmModule * module, int func_index)
Definition at line 843 of file wasm-module.cc.
                                                              {
  return JumpTableAssembler::JumpSlotIndexToOffset(
      declared_function_index(module, func_index));
}
References declared_function_index().
Referenced by v8::internal::wasm::NativeModule::GetNearCallTargetForFunction(), and v8::internal::RUNTIME_FUNCTION().
load_old_fp()
Address v8::internal::wasm::load_old_fp (Isolate * isolate)
Definition at line 1111 of file wasm-external-refs.cc.
                                      {
  // If there is no parent, then the current stack is the main isolate stack.
  wasm::StackMemory* active_stack = isolate->isolate_data()->active_stack();
  if (active_stack->jmpbuf()->parent == nullptr) {
    return 0;
  }
  DCHECK_EQ(active_stack->jmpbuf()->state, wasm::JumpBuffer::Active);
  return active_stack->old_fp();
}
References v8::internal::wasm::JumpBuffer::Active, v8::internal::IsolateData::active_stack(), DCHECK_EQ, v8::internal::Isolate::isolate_data(), v8::internal::wasm::StackMemory::jmpbuf(), v8::internal::wasm::StackMemory::old_fp(), v8::internal::wasm::JumpBuffer::parent, and v8::internal::wasm::JumpBuffer::state.
LoadProfileFromFile()
V8_WARN_UNUSED_RESULT std::unique_ptr< ProfileInformation > v8::internal::wasm::LoadProfileFromFile (const WasmModule * module, base::Vector< const uint8_t > wire_bytes)
Definition at line 222 of file pgo.cc.
                                                                    {
  CHECK(!wire_bytes.empty());
  // File are named `profile-wasm-<hash>`.
  // We use the same hash as for reported scripts, to make it easier to
  // correlate files to wasm modules (see {CreateWasmScript}).
  uint32_t hash = static_cast<uint32_t>(GetWireBytesHash(wire_bytes));
  base::EmbeddedVector<char, 32> filename;
  SNPrintF(filename, "profile-wasm-%08x", hash);
  FILE* file = base::OS::FOpen(filename.begin(), "rb");
  if (!file) {
    PrintF("No Wasm PGO data found: Cannot open file '%s'\n", filename.begin());
    return {};
  }
  fseek(file, 0, SEEK_END);
  size_t size = ftell(file);
  rewind(file);
  PrintF("Loading Wasm PGO data from file '%s' (%zu bytes)\n", filename.begin(),
         size);
  base::OwnedVector<uint8_t> profile_data =
      base::OwnedVector<uint8_t>::NewForOverwrite(size);
  for (size_t read = 0; read < size;) {
    read += fread(profile_data.begin() + read, 1, size - read, file);
    CHECK(!ferror(file));
  }
  base::Fclose(file);
  return RestoreProfileData(module, profile_data.as_vector());
}
References v8::base::OwnedVector< T >::as_vector(), v8::base::Vector< T >::begin(), v8::base::OwnedVector< T >::begin(), CHECK, v8::base::Vector< T >::empty(), v8::base::Fclose(), file(), v8::base::OS::FOpen(), GetWireBytesHash(), v8::base::OwnedVector< T >::NewForOverwrite(), v8::internal::PrintF(), RestoreProfileData(), size(), and v8::base::SNPrintF().
Referenced by v8::internal::wasm::AsyncCompileJob::FinishCompile(), and v8::internal::wasm::WasmEngine::SyncCompile().
machine_type()
constexpr MachineType v8::internal::wasm::machine_type (ValueKind kind) [constexpr]
Definition at line 1211 of file value-type.h.
                                                   {
  DCHECK_NE(kBottom, kind);
  constexpr MachineType kMachineType[] = {
#define MACH_TYPE(kind, log2Size, code, machineType, ...) \
  MachineType::machineType(),
      FOREACH_VALUE_TYPE(MACH_TYPE)
#undef MACH_TYPE
  };
  return kMachineType[kind];
}
References DCHECK_NE, FOREACH_VALUE_TYPE, and MACH_TYPE.
Referenced by v8::internal::compiler::fast_api_call::FastApiCallBuilder::Build(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandReadUnaligned(), v8::internal::compiler::turboshaft::FrameStateData::Iterator::ConsumeInput(), v8::internal::compiler::RepresentationSelector::DeoptMachineTypeOf(), v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::FastApiCall(), v8::internal::compiler::FieldAccess::FieldAccess(), v8::internal::compiler::AccessBuilder::ForJSObjectInObjectProperty(), v8::internal::LinkageLocation::LinkageLocation(), v8::internal::CodeStubAssembler::LoadArrayElement(), v8::internal::compiler::turboshaft::DataViewLoweringReducer< Next >::LoadDataViewElement(), v8::internal::CodeStubAssembler::LoadDoubleWithUndefinedAndHoleCheck(), v8::internal::CodeStubAssembler::LoadFixedDoubleArrayElement(), v8::internal::CodeStubAssembler::LoadObjectField(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::MemoryGrow(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::MemoryLowering::ReduceLoadFromObject(), v8::internal::compiler::MemoryLowering::ReduceStoreField(), v8::internal::compiler::turboshaft::DataViewLoweringReducer< Next >::StoreDataViewElement(), and v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StoreFieldImpl().
MatchHelper()
template<int kLanes, int kLaneBytes>
bool v8::internal::wasm::MatchHelper (const uint8_t * input, uint8_t * output)
Definition at line 183 of file simd-shuffle.cc.
                                                        {
  for (int i = 0; i < kLanes; ++i) {
    if (input[i * kLaneBytes] % kLaneBytes != 0) return false;
    for (int j = 1; j < kLaneBytes; ++j) {
      if (input[i * kLaneBytes + j] - input[i * kLaneBytes + j - 1] != 1)
        return false;
    }
    output[i] = input[i * kLaneBytes] / kLaneBytes;
  }
  return true;
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i.
max_mem32_bytes()
uint64_t v8::internal::wasm::max_mem32_bytes () [inline]
Definition at line 102 of file wasm-limits.h.
                                  {
  return uint64_t{max_mem32_pages()} * kWasmPageSize;
}
References kWasmPageSize, and max_mem32_pages().
Referenced by v8::internal::anonymous_namespace{asm-js.cc}::IsValidAsmjsMemorySize(), and v8::internal::WasmTrustedInstanceData::SetRawMemory().
max_mem32_pages()
V8_EXPORT_PRIVATE uint32_t v8::internal::wasm::max_mem32_pages ()
Definition at line 2146 of file wasm-engine.cc.
                           {
  static_assert(
      kV8MaxWasmMemory32Pages * kWasmPageSize <= JSArrayBuffer::kMaxByteLength,
      "Wasm memories must not be bigger than JSArrayBuffers");
  static_assert(kV8MaxWasmMemory32Pages <= kMaxUInt32);
  return std::min(uint32_t{kV8MaxWasmMemory32Pages},
                  v8_flags.wasm_max_mem_pages.value());
}
References v8::internal::JSArrayBuffer::kMaxByteLength, v8::internal::kMaxUInt32, kV8MaxWasmMemory32Pages, kWasmPageSize, and v8::internal::v8_flags.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::GenerateRandomMemories(), v8::internal::WasmMemoryObject::Grow(), max_mem32_bytes(), v8::internal::WasmMemoryObject::New(), and UpdateComputedInformation().
max_mem64_bytes()
uint64_t v8::internal::wasm::max_mem64_bytes () [inline]
Definition at line 106 of file wasm-limits.h.
                                  {
  return uint64_t{max_mem64_pages()} * kWasmPageSize;
}
References kWasmPageSize, and max_mem64_pages().
Referenced by v8::internal::WasmTrustedInstanceData::SetRawMemory().
max_mem64_pages()
V8_EXPORT_PRIVATE uint32_t v8::internal::wasm::max_mem64_pages ()
Definition at line 2155 of file wasm-engine.cc.
                           {
  static_assert(
      kV8MaxWasmMemory64Pages * kWasmPageSize <= JSArrayBuffer::kMaxByteLength,
      "Wasm memories must not be bigger than JSArrayBuffers");
  static_assert(kV8MaxWasmMemory64Pages <= kMaxUInt32);
  return std::min(uint32_t{kV8MaxWasmMemory64Pages},
                  v8_flags.wasm_max_mem_pages.value());
}
References v8::internal::JSArrayBuffer::kMaxByteLength, v8::internal::kMaxUInt32, kV8MaxWasmMemory64Pages, kWasmPageSize, and v8::internal::v8_flags.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::GenerateRandomMemories(), v8::internal::WasmMemoryObject::Grow(), max_mem64_bytes(), v8::internal::WasmMemoryObject::New(), and UpdateComputedInformation().
max_module_size()
V8_EXPORT_PRIVATE size_t v8::internal::wasm::max_module_size ()
Definition at line 2177 of file wasm-engine.cc.
                         {
  // Clamp the value of --wasm-max-module-size between 16 and the maximum
  // that the implementation supports.
  constexpr size_t kMin = 16;
  constexpr size_t kMax = kV8MaxWasmModuleSize;
  static_assert(kMin <= kV8MaxWasmModuleSize);
  return std::clamp(v8_flags.wasm_max_module_size.value(), kMin, kMax);
}
References v8::internal::kMax, v8::internal::kMin, kV8MaxWasmModuleSize, and v8::internal::v8_flags.
Referenced by v8::internal::wasm::ModuleDecoderImpl::DecodeModule(), v8::internal::wasm::AsyncStreamingDecoder::Finish(), v8::internal::wasm::AsyncStreamingDecoder::DecodeSectionLength::NextWithValue(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyCompileImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyInstantiateImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyModuleImpl(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyValidateImpl().
max_table_init_entries()
V8_EXPORT_PRIVATE uint32_t v8::internal::wasm::max_table_init_entries ()
Definition at line 2171 of file wasm-engine.cc.
                                  {
  return std::min(uint32_t{kV8MaxWasmTableInitEntries},
                  v8_flags.wasm_max_table_size.value());
}
References kV8MaxWasmTableInitEntries, and v8::internal::v8_flags.
Referenced by v8::internal::wasm::ModuleDecoderImpl::consume_element_segment_header(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableImpl().
max_table_size()
V8_EXPORT_PRIVATE uint32_t v8::internal::wasm::max_table_size ()
Definition at line 2165 of file wasm-engine.cc.
                          {
  return std::min(uint32_t{kV8MaxWasmTableSize},
                  v8_flags.wasm_max_table_size.value());
}
References kV8MaxWasmTableSize, and v8::internal::v8_flags.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallIndirectImpl(), v8::internal::wasm::ModuleDecoderImpl::DecodeElementSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeImportSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeTableSection(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::GenerateRandomTables(), v8::internal::WasmDispatchTable::Grow(), v8::internal::WasmTableObject::Grow(), v8::internal::wasm::WasmModuleBuilder::IncreaseTableMinSize(), v8::internal::wasm::InstanceBuilder::LoadTableSegments(), v8::internal::WasmTableObject::New(), v8::internal::wasm::TurboshaftGraphBuildingInterface::TableGet(), v8::internal::wasm::TurboshaftGraphBuildingInterface::TableGrow(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableGrowImpl().
memory_copy_wrapper()
int32_t v8::internal::wasm::memory_copy_wrapper (Address trusted_data_addr, uint32_t dst_mem_index, uint32_t src_mem_index, uintptr_t dst, uintptr_t src, uintptr_t size)
Definition at line 778 of file wasm-external-refs.cc.
                                                           {
  ThreadNotInWasmScope thread_not_in_wasm_scope;
  DisallowGarbageCollection no_gc;
  Tagged<WasmTrustedInstanceData> trusted_data =
      Cast<WasmTrustedInstanceData>(Tagged<Object>{trusted_data_addr});
  size_t dst_mem_size = trusted_data->memory_size(dst_mem_index);
  size_t src_mem_size = trusted_data->memory_size(src_mem_index);
  static_assert(std::is_same_v<size_t, uintptr_t>);
  if (!base::IsInBounds<size_t>(dst, size, dst_mem_size)) return kOutOfBounds;
  if (!base::IsInBounds<size_t>(src, size, src_mem_size)) return kOutOfBounds;
  // Use std::memmove, because the ranges can overlap.
  std::memmove(EffectiveAddress(trusted_data, dst_mem_index, dst),
               EffectiveAddress(trusted_data, src_mem_index, src), size);
  return kSuccess;
}
References v8::internal::wasm::anonymous_namespace{wasm-external-refs.cc}::EffectiveAddress(), v8::internal::wasm::anonymous_namespace{wasm-external-refs.cc}::kOutOfBounds, kSuccess, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and size().
memory_fill_wrapper()
int32_t v8::internal::wasm::memory_fill_wrapper (Address trusted_data_addr, uint32_t mem_index, uintptr_t dst, uint8_t value, uintptr_t size)
Definition at line 798 of file wasm-external-refs.cc.
                                                                          {
  ThreadNotInWasmScope thread_not_in_wasm_scope;
  DisallowGarbageCollection no_gc;
  Tagged<WasmTrustedInstanceData> trusted_data =
      Cast<WasmTrustedInstanceData>(Tagged<Object>{trusted_data_addr});
  uint64_t mem_size = trusted_data->memory_size(mem_index);
  if (!base::IsInBounds<uint64_t>(dst, size, mem_size)) return kOutOfBounds;
  std::memset(EffectiveAddress(trusted_data, mem_index, dst), value, size);
  return kSuccess;
}
References v8::internal::wasm::anonymous_namespace{wasm-external-refs.cc}::EffectiveAddress(), v8::internal::wasm::anonymous_namespace{wasm-external-refs.cc}::kOutOfBounds, kSuccess, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, size(), and v8::internal::value.
memory_init_wrapper()
int32_t v8::internal::wasm::memory_init_wrapper (Address trusted_data_addr, uint32_t mem_index, uintptr_t dst, uint32_t src, uint32_t seg_index, uint32_t size)
Definition at line 757 of file wasm-external-refs.cc.
                                           {
  ThreadNotInWasmScope thread_not_in_wasm_scope;
  DisallowGarbageCollection no_gc;
  Tagged<WasmTrustedInstanceData> trusted_data =
      Cast<WasmTrustedInstanceData>(Tagged<Object>{trusted_data_addr});
  uint64_t mem_size = trusted_data->memory_size(mem_index);
  if (!base::IsInBounds<uint64_t>(dst, size, mem_size)) return kOutOfBounds;
  uint32_t seg_size = trusted_data->data_segment_sizes()->get(seg_index);
  if (!base::IsInBounds<uint32_t>(src, size, seg_size)) return kOutOfBounds;
  uint8_t* seg_start = reinterpret_cast<uint8_t*>(
      trusted_data->data_segment_starts()->get(seg_index));
  std::memcpy(EffectiveAddress(trusted_data, mem_index, dst), seg_start + src,
              size);
  return kSuccess;
}
References v8::internal::wasm::anonymous_namespace{wasm-external-refs.cc}::EffectiveAddress(), v8::internal::wasm::anonymous_namespace{wasm-external-refs.cc}::kOutOfBounds, kSuccess, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and size().
name() [1/3]
constexpr const char* v8::internal::wasm::name (ValueKind kind) [constexpr]
Definition at line 1195 of file value-type.h.
                                           {
  constexpr const char* kKindName[] = {
#define KIND_NAME(kind, log2Size, code, machineType, shortName, kindName, ...) \
  kindName,
      FOREACH_VALUE_TYPE(KIND_NAME)
#undef TYPE_NAME
  };
  return kKindName[kind];
}
References FOREACH_VALUE_TYPE, and KIND_NAME.
Referenced by v8::internal::wasm::WasmModuleBuilder::AddExport(), v8::internal::wasm::WasmModuleBuilder::AddExportedGlobal(), v8::internal::wasm::LazilyGeneratedNames::AddForTesting(), v8::internal::wasm::AsmJsParser::AddGlobalImport(), v8::internal::wasm::WasmModuleBuilder::AddGlobalImport(), v8::internal::wasm::WasmModuleBuilder::AddImport(), v8::internal::wasm::WasmWrapperTSGraphBuilder::CallBuiltin(), v8::internal::wasm::DescriptorsSectionIterator::Entry::Constructor(), v8::internal::wasm::Decoder::consume_bytes(), v8::internal::wasm::ModuleDecoderImpl::consume_count(), v8::internal::wasm::Decoder::consume_i32v(), v8::internal::wasm::Decoder::consume_i64v(), v8::internal::wasm::ModuleDecoderImpl::consume_index(), v8::internal::wasm::Decoder::consume_little_endian(), v8::internal::wasm::ModuleDecoderImpl::consume_resizable_limits(), consume_string(), v8::internal::wasm::Decoder::consume_u16(), v8::internal::wasm::Decoder::consume_u32(), v8::internal::wasm::Decoder::consume_u32v(), v8::internal::wasm::Decoder::consume_u64v(), v8::internal::wasm::Decoder::consume_u8(), consume_utf8_string(), CreateFunctionForCompileTimeImport(), v8::internal::wasm::WasmCode::DebugName(), DecodeCanonicalTypeNames(), v8::internal::wasm::ModuleDecoderImpl::DecodeExportSection(), v8::internal::wasm::anonymous_namespace{module-decoder.cc}::DecodeNameMapInternal(), v8::internal::wasm::ModuleDecoderImpl::DecodeNameSection(), v8::internal::wasm::WasmCode::Disassemble(), v8::internal::wasm::ModuleDecoderImpl::expect_u8(), v8::internal::wasm::WasmModuleBuilder::ExportImportedFunction(), v8::internal::wasm::JSToWasmWrapperCompilationUnit::Finalize(), v8::internal::wasm::anonymous_namespace{wrappers.cc}::GetBuiltinCallDescriptor(), GetCustomSections(), v8::internal::wasm::JSPrototypesSetup::GetImportedObject(), v8::internal::wasm::gdb_server::WasmModuleDebug::GetModuleName(), GetWasmErrorWithName(), v8::internal::wasm::CompileTimeImports::has_string_constants(), v8::internal::wasm::JSPrototypesSetup::InstallExport(), v8::internal::wasm::WasmCode::LogCode(), v8::internal::wasm::JSPrototypesSetup::MakeConstructor(), v8::internal::wasm::JSPrototypesSetup::MaterializeDescriptorOptionsImpl(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::MaybeBailoutForUnsupportedType(), v8::internal::wasm::WasmCode::MaybePrint(), v8::internal::wasm::DescriptorsSectionIterator::Entry::NextMethodImpl(), operator<<(), v8::internal::wasm::WasmCode::Print(), v8::internal::wasm::CanonicalTypeNamesProvider::PrintFieldName(), v8::internal::wasm::CanonicalTypeNamesProvider::PrintTypeName(), v8::internal::wasm::CanonicalTypeNamesProvider::PrintValueType(), v8::internal::wasm::InstanceBuilder::ProcessExports(), v8::internal::wasm::value_type_reader::read_heap_type(), v8::internal::wasm::Decoder::read_i32v(), v8::internal::wasm::Decoder::read_i33v(), v8::internal::wasm::Decoder::read_i64v(), v8::internal::wasm::Decoder::read_leb(), v8::internal::wasm::Decoder::read_leb_slowpath(), v8::internal::wasm::Decoder::read_leb_tail(), v8::internal::wasm::Decoder::read_u32v(), v8::internal::wasm::Decoder::read_u64v(), v8::internal::wasm::value_type_reader::read_value_type(), v8::internal::wasm::WasmFunctionBuilder::SetName(), ValidateAndSetBuiltinImports(), v8::internal::wasm::AsmJsParser::ValidateExport(), v8::internal::wasm::AsmJsParser::ValidateModuleVarImport(), v8::internal::wasm::ZoneBuffer::write_string(), and v8::internal::wasm::WasmModuleBuilder::WriteTo().
name() [2/3]
constexpr const char* v8::internal::wasm::name (WasmDetectedFeature feature) [inline], [constexpr]
Definition at line 121 of file wasm-features.h.
                                                               {
  switch (feature) {
#define NAME(feat, ...) \
  case WasmDetectedFeature::feat: \
    return #feat;
    FOREACH_WASM_FEATURE(NAME)
  }
#undef NAME
}
References FOREACH_WASM_FEATURE, and NAME.
name() [3/3]
constexpr const char* v8::internal::wasm::name (WasmEnabledFeature feature) [inline], [constexpr]
Definition at line 107 of file wasm-features.h.
                                                              {
  switch (feature) {
#define NAME(feat, ...) \
  case WasmEnabledFeature::feat: \
    return #feat;
    FOREACH_WASM_FEATURE_FLAG(NAME)
  }
#undef NAME
}
References FOREACH_WASM_FEATURE_FLAG, and NAME.
NameBuiltinLength()
std::tuple<const char*, Builtin, int> v8::internal::wasm::NameBuiltinLength (WellKnownImport wki)
Definition at line 2158 of file module-instantiate.cc.
                                                                           {
#define CASE(CamelName, name, length) \
  case WellKnownImport::kString##CamelName: \
    return std::make_tuple(name, Builtin::kWebAssemblyString##CamelName, length)
  switch (wki) {
    CASE(Cast, "cast", 1);
    CASE(CharCodeAt, "charCodeAt", 2);
    CASE(CodePointAt, "codePointAt", 2);
    CASE(Compare, "compare", 2);
    CASE(Concat, "concat", 2);
    CASE(Equals, "equals", 2);
    CASE(FromCharCode, "fromCharCode", 1);
    CASE(FromCodePoint, "fromCodePoint", 1);
    CASE(FromUtf8Array, "decodeStringFromUTF8Array", 3);
    CASE(FromWtf16Array, "fromCharCodeArray", 3);
    CASE(IntoUtf8Array, "encodeStringIntoUTF8Array", 3);
    CASE(Length, "length", 1);
    CASE(MeasureUtf8, "measureStringAsUTF8", 1);
    CASE(Substring, "substring", 3);
    CASE(Test, "test", 1);
    CASE(ToUtf8Array, "encodeStringToUTF8Array", 1);
    CASE(ToWtf16Array, "intoCharCodeArray", 3);
    default:
      UNREACHABLE(); // Only call this for compile-time imports.
  }
#undef CASE
}
References CASE, v8::internal::Cast(), v8::bigint::Compare(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::Equals(), and v8::internal::UNREACHABLE().
Referenced by CreateFunctionForCompileTimeImport().
needs_fp_reg_pair()
static constexpr bool v8::internal::wasm::needs_fp_reg_pair (ValueKind kind) [inline], [static], [constexpr]
Definition at line 52 of file liftoff-register.h.
                                                               {
  return kNeedS128RegPair && kind == kS128;
}
References kNeedS128RegPair, and v8::internal::kS128.
Referenced by v8::internal::wasm::LiftoffAssembler::MoveToReturnLocations().
needs_gp_reg_pair()
static constexpr bool v8::internal::wasm::needs_gp_reg_pair (ValueKind kind) [inline], [static], [constexpr]
Definition at line 48 of file liftoff-register.h.
                                                               {
  return kNeedI64RegPair && kind == kI64;
}
References v8::internal::kI64, and kNeedI64RegPair.
Referenced by v8::internal::wasm::LiftoffAssembler::CallC(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitBitRotationCCall(), v8::internal::wasm::LiftoffAssembler::FinishCall(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GenerateCCall(), v8::internal::wasm::LiftoffAssembler::MoveToReturnLocations(), v8::internal::wasm::LiftoffAssembler::MoveToReturnLocationsMultiReturn(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ParameterProcessor::NextParam().
Negate()
constexpr Condition v8::internal::wasm::Negate (Condition cond) [inline], [constexpr]
Definition at line 30 of file liftoff-assembler.h.
                                                  {
  switch (cond) {
    case kEqual:
      return kNotEqual;
    case kNotEqual:
      return kEqual;
    case kLessThan:
      return kGreaterThanEqual;
    case kLessThanEqual:
      return kGreaterThan;
    case kGreaterThanEqual:
      return kLessThan;
    case kGreaterThan:
      return kLessThanEqual;
    case kUnsignedLessThan:
      return kUnsignedGreaterThanEqual;
    case kUnsignedLessThanEqual:
      return kUnsignedGreaterThan;
    case kUnsignedGreaterThanEqual:
      return kUnsignedLessThan;
    case kUnsignedGreaterThan:
      return kUnsignedLessThanEqual;
    default:
      UNREACHABLE();
  }
}
References v8::internal::kEqual, v8::internal::kGreaterThan, v8::internal::kGreaterThanEqual, v8::internal::kLessThan, v8::internal::kLessThanEqual, v8::internal::kNotEqual, v8::internal::kUnsignedGreaterThan, v8::internal::kUnsignedGreaterThanEqual, v8::internal::kUnsignedLessThan, v8::internal::kUnsignedLessThanEqual, and v8::internal::UNREACHABLE().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::JumpIfFalse().
NumFeedbackSlots()
int v8::internal::wasm::NumFeedbackSlots (const WasmModule * module, int func_index)
Definition at line 854 of file wasm-module.cc.
                                                               {
  base::MutexGuard mutex_guard{&module->type_feedback.mutex};
  auto it = module->type_feedback.feedback_for_function.find(func_index);
  if (it == module->type_feedback.feedback_for_function.end()) return 0;
  // The number of call instructions is capped by max function size.
  static_assert(kV8MaxWasmFunctionSize < std::numeric_limits<int>::max() / 2);
  return static_cast<int>(2 * it->second.call_targets.size());
}
References v8::internal::wasm::TypeFeedbackStorage::feedback_for_function, kV8MaxWasmFunctionSize, v8::internal::wasm::TypeFeedbackStorage::mutex, and v8::internal::wasm::WasmModule::type_feedback.
Referenced by v8::internal::anonymous_namespace{runtime-wasm.cc}::AllocateFeedbackVector().
OpcodeLength()
V8_EXPORT_PRIVATE unsigned v8::internal::wasm::OpcodeLength (const uint8_t * pc, const uint8_t * end)
Definition at line 84 of file function-body-decoder.cc.
                                                             {
  WasmDetectedFeatures unused_detected_features;
  Zone* no_zone = nullptr;
  WasmModule* no_module = nullptr;
  FunctionSig* no_sig = nullptr;
  constexpr bool kIsShared = false;
  WasmDecoder<Decoder::NoValidationTag> decoder(
      no_zone, no_module, WasmEnabledFeatures::All(), &unused_detected_features,
      no_sig, kIsShared, pc, end, 0);
  return WasmDecoder<Decoder::NoValidationTag>::OpcodeLength(&decoder, pc);
}
References v8::internal::wasm::WasmEnabledFeatures::All(), v8::internal::compiler::end(), and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::OpcodeLength().
Referenced by v8::internal::wasm::BasicBlockCalculator::EndCurrentBlock(), v8::internal::wasm::BytecodeIterator::next(), and v8::internal::wasm::BytecodeIterator::iterator_base::operator++().
operator<<() [1/23]
std::ostream& v8::internal::wasm::operator<< (std::ostream & os, AddressType address_type) [inline]
Definition at line 55 of file wasm-module.h.
                                                                        {
  return os << AddressTypeToStr(address_type);
}
References AddressTypeToStr().
operator<<() [2/23]
std::ostream& v8::internal::wasm::operator<< (std::ostream & os, CompileTimeImport imp) [inline]
Definition at line 144 of file wasm-features.h.
                                                                     {
  return os << static_cast<int>(imp);
}
operator<<() [3/23]
V8_EXPORT_PRIVATE std::ostream & v8::internal::wasm::operator<< (std::ostream & os, const FunctionSig & sig)
Definition at line 18 of file wasm-opcodes.cc.
                                                               {
  if (sig.return_count() == 0) os << "v";
  for (auto ret : sig.returns()) {
    os << ret.short_name();
  }
  os << "_";
  if (sig.parameter_count() == 0) os << "v";
  for (auto param : sig.parameters()) {
    os << param.short_name();
  }
  return os;
}
References v8::internal::sig.
operator<<() [4/23]
V8_EXPORT_PRIVATE std::ostream & v8::internal::wasm::operator<< (std::ostream & os, const WasmFunctionName & name)
Definition at line 231 of file wasm-module.cc.
                                                                     {
  os << "#" << name.func_index_;
  if (!name.name_.empty()) {
    if (name.name_.begin()) {
      os << ":";
      os.write(name.name_.begin(), name.name_.length());
    }
  } else {
    os << "?";
  }
  return os;
}
References name().
operator<<() [5/23]
std::ostream& v8::internal::wasm::operator<< (std::ostream & os, LiftoffRegister reg) [inline]
Definition at line 332 of file liftoff-register.h.
                                                                   {
  if (reg.is_gp_pair()) {
    return os << "<" << reg.low_gp() << "+" << reg.high_gp() << ">";
  } else if (reg.is_fp_pair()) {
    return os << "<" << reg.low_fp() << "+" << reg.high_fp() << ">";
  } else if (reg.is_gp()) {
    return os << reg.gp();
  } else {
    return os << reg.fp();
  }
}
References v8::internal::wasm::LiftoffRegister::fp(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::wasm::LiftoffRegister::high_fp(), v8::internal::wasm::LiftoffRegister::high_gp(), v8::internal::wasm::LiftoffRegister::is_fp_pair(), v8::internal::wasm::LiftoffRegister::is_gp(), v8::internal::wasm::LiftoffRegister::is_gp_pair(), v8::internal::wasm::LiftoffRegister::low_fp(), and v8::internal::wasm::LiftoffRegister::low_gp().
operator<<() [6/23]
std::ostream& v8::internal::wasm::operator<< (std::ostream & os, LiftoffRegList reglist) [inline]
Definition at line 555 of file liftoff-register.h.
                                                                      {
  os << "{";
  for (bool first = true; !reglist.is_empty(); first = false) {
    LiftoffRegister reg = reglist.GetFirstRegSet();
    reglist.clear(reg);
    os << (first ? "" : ", ") << reg;
  }
  return os << "}";
}
References v8::internal::wasm::LiftoffRegList::clear(), v8::internal::wasm::LiftoffRegList::GetFirstRegSet(), and v8::internal::wasm::LiftoffRegList::is_empty().
operator<<() [7/23]
std::ostream & v8::internal::wasm::operator<< (std::ostream & os, LiftoffVarState slot)
Definition at line 1203 of file liftoff-assembler.cc.
                                                             {
  os << name(slot.kind()) << ":";
  switch (slot.loc()) {
    case LiftoffVarState::kStack:
      return os << "s0x" << std::hex << slot.offset() << std::dec;
    case LiftoffVarState::kRegister:
      return os << slot.reg();
    case LiftoffVarState::kIntConst:
      return os << "c" << slot.i32_const();
  }
  UNREACHABLE();
}
References v8::internal::wasm::LiftoffVarState::i32_const(), v8::internal::wasm::LiftoffVarState::kind(), v8::internal::wasm::LiftoffVarState::kIntConst, v8::internal::wasm::LiftoffVarState::kRegister, v8::internal::wasm::LiftoffVarState::kStack, v8::internal::wasm::LiftoffVarState::loc(), name(), v8::internal::wasm::LiftoffVarState::offset(), v8::internal::wasm::LiftoffVarState::reg(), and v8::internal::UNREACHABLE().
operator<<() [8/23]
std::ostream& v8::internal::wasm::operator<< (std::ostream & os, WasmDetectedFeature feature) [inline]
Definition at line 131 of file wasm-features.h.
                                                                           {
  return os << name(feature);
}
References name().
operator<<() [9/23]
std::ostream& v8::internal::wasm::operator<< (std::ostream & os, WasmEnabledFeature feature) [inline]
Definition at line 117 of file wasm-features.h.
                                                                          {
  return os << name(feature);
}
References name().
operator<<() [10/23]
std::ostream& v8::internal::wasm::operator<< (std::ostream & oss, TypeIndex index) [inline]
Definition at line 98 of file value-type.h.
                                                                {
  return oss << index.index;
}
References v8::internal::index.
operator<<() [11/23]
std::ostream& v8::internal::wasm::operator<< (std::ostream & oss, TypeInModule type) [inline]
Definition at line 133 of file wasm-subtyping.h.
                                                                  {
  return oss << type.type.name() << "@"
             << reinterpret_cast<intptr_t>(type.module);
}
References v8::internal::tracing::type.
operator<<() [12/23]
std::ostream& v8::internal::wasm::operator<< (std::ostream & oss, ValueKind kind) [inline]
Definition at line 1207 of file value-type.h.
                                                               {
  return oss << name(kind);
}
References name().
operator<<() [13/23]
std::ostream& v8::internal::wasm::operator<< (std::ostream & oss, ValueType type) [inline]
Definition at line 1237 of file value-type.h.
                                                               {
  return oss << type.name() << " (raw=0x" << std::hex << type.raw_bit_field()
             << ")" << std::dec;
}
References v8::internal::tracing::type.
operator<<() [14/23]
std::ostream& v8::internal::wasm::operator<< (std::ostream & out, StructTypeBase type) [inline]
Definition at line 305 of file struct-types.h.
                                                                    {
  out << "[";
  for (ValueTypeBase field : type.fields()) {
    out << field.name() << ", ";
  }
  out << "]";
  return out;
}
References v8::internal::tracing::type.
operator<<() [15/23]
StringBuilder& v8::internal::wasm::operator<< (StringBuilder & sb, char c) [inline]
Definition at line 132 of file string-builder.h.
                                                            {
  *sb.allocate(1) = c;
  return sb;
}
References v8::internal::wasm::StringBuilder::allocate().
operator<<() [16/23]
StringBuilder& v8::internal::wasm::operator<< (StringBuilder & sb, const char * str) [inline]
Definition at line 125 of file string-builder.h.
                                                                     {
  size_t len = strlen(str);
  char* ptr = sb.allocate(len);
  memcpy(ptr, str, len);
  return sb;
}
References v8::internal::wasm::StringBuilder::allocate().
operator<<() [17/23]
StringBuilder& v8::internal::wasm::operator<< (StringBuilder & sb, const std::string & s) [inline]
Definition at line 137 of file string-builder.h.
                                                                        {
  sb.write(s.data(), s.length());
  return sb;
}
References v8::internal::wasm::StringBuilder::write().
operator<<() [18/23]
StringBuilder& v8::internal::wasm::operator<< (StringBuilder & sb, Indentation indentation) [inline]
Definition at line 58 of file wasm-disassembler-impl.h.
                                                                             {
  char* ptr = sb.allocate(indentation.current());
  memset(ptr, ' ', indentation.current());
  return sb;
}
References v8::internal::wasm::StringBuilder::allocate(), and v8::internal::wasm::Indentation::current().
operator<<() [19/23]
StringBuilder& v8::internal::wasm::operator<< (StringBuilder & sb, int value) [inline]
Definition at line 164 of file string-builder.h.
                                                               {
  if (value >= 0) {
    sb << static_cast<uint32_t>(value);
  } else {
    sb << "-" << ((~static_cast<uint32_t>(value)) + 1);
  }
  return sb;
}
References v8::internal::value.
operator<<() [20/23]
StringBuilder& v8::internal::wasm::operator<< (StringBuilder & sb, ModuleTypeIndex index) [inline]
Definition at line 81 of file wasm-disassembler-impl.h.
                                                                           {
  return sb << index.index;
}
References v8::internal::index.
operator<<() [21/23]
StringBuilder& v8::internal::wasm::operator<< (StringBuilder & sb, std::string_view s) [inline]
Definition at line 142 of file string-builder.h.
                                                                      {
  sb.write(s.data(), s.length());
  return sb;
}
References v8::internal::wasm::StringBuilder::write().
operator<<() [22/23]
StringBuilder& v8::internal::wasm::operator<< (StringBuilder & sb, uint32_t n) [inline]
Definition at line 147 of file string-builder.h.
                                                                {
  if (n == 0) {
    *sb.allocate(1) = '0';
    return sb;
  }
  static constexpr size_t kBufferSize = 10; // Just enough for a uint32.
  char buffer[kBufferSize];
  char* end = buffer + kBufferSize;
  char* out = end;
  while (n != 0) {
    *(--out) = '0' + (n % 10);
    n /= 10;
  }
  sb.write(out, static_cast<size_t>(end - out));
  return sb;
}
References v8::internal::wasm::StringBuilder::allocate(), v8::internal::compiler::end(), v8::internal::anonymous_namespace{setup-builtins-internal.cc}::kBufferSize, and v8::internal::wasm::StringBuilder::write().
operator<<() [23/23]
StringBuilder& v8::internal::wasm::operator<< (StringBuilder & sb, uint64_t n) [inline]
Definition at line 64 of file wasm-disassembler-impl.h.
                                                                {
  if (n == 0) {
    *sb.allocate(1) = '0';
    return sb;
  }
  static constexpr size_t kBufferSize = 20; // Just enough for a uint64.
  char buffer[kBufferSize];
  char* end = buffer + kBufferSize;
  char* out = end;
  while (n != 0) {
    *(--out) = '0' + (n % 10);
    n /= 10;
  }
  sb.write(out, static_cast<size_t>(end - out));
  return sb;
}
References v8::internal::wasm::StringBuilder::allocate(), v8::internal::compiler::end(), v8::internal::anonymous_namespace{setup-builtins-internal.cc}::kBufferSize, and v8::internal::wasm::StringBuilder::write().
PrintSignature()
size_t v8::internal::wasm::PrintSignature (base::Vector< char > buffer, const CanonicalSig * sig, char delimiter)
Definition at line 823 of file wasm-module.cc.
                                      {
  if (buffer.empty()) return 0;
  size_t old_size = buffer.size();
  auto append_char = [&buffer](char c) {
    if (buffer.size() == 1) return; // Keep last character for '\0'.
    buffer[0] = c;
    buffer += 1;
  };
  for (CanonicalValueType t : sig->parameters()) {
    append_char(t.short_name());
  }
  append_char(delimiter);
  for (CanonicalValueType t : sig->returns()) {
    append_char(t.short_name());
  }
  buffer[0] = '\0';
  return old_size - buffer.size();
}
References v8::base::Vector< T >::empty(), v8::internal::sig, and v8::base::Vector< T >::size().
PrintSignatureOneLine()
void v8::internal::wasm::PrintSignatureOneLine (StringBuilder & out, const FunctionSig * sig, uint32_t func_index, NamesProvider * names, bool param_names, IndexAsComment indices_as_comments = NamesProvider::kDontPrintIndex)
Definition at line 175 of file wasm-disassembler.cc.
                                                               {
  if (param_names) {
    for (uint32_t i = 0; i < sig->parameter_count(); i++) {
      out << " (param ";
      names->PrintLocalName(out, func_index, i, indices_as_comments);
      out << ' ';
      names->PrintValueType(out, sig->GetParam(i));
      out << ")";
    }
  } else if (sig->parameter_count() > 0) {
    out << " (param";
    for (uint32_t i = 0; i < sig->parameter_count(); i++) {
      out << " ";
      names->PrintValueType(out, sig->GetParam(i));
    }
    out << ")";
  }
  for (size_t i = 0; i < sig->return_count(); i++) {
    out << " (result ";
    names->PrintValueType(out, sig->GetReturn(i));
    out << ")";
  }
}
References v8::internal::wasm::NamesProvider::PrintLocalName(), v8::internal::wasm::NamesProvider::PrintValueType(), and v8::internal::sig.
Referenced by v8::internal::wasm::ImmediatesPrinter< ValidationTag >::BlockType(), v8::internal::wasm::FunctionBodyDisassembler::DecodeAsWat(), v8::internal::wasm::ModuleDisassembler::PrintModule(), and v8::internal::wasm::ImmediatesPrinter< ValidationTag >::PrintSignature().
PrintStringAsJSON()
void v8::internal::wasm::PrintStringAsJSON (StringBuilder & out, const uint8_t * start, WireBytesRef ref)
Definition at line 1237 of file wasm-disassembler.cc.
                                         {
  for (const uint8_t* ptr = start + ref.offset();
       ptr < start + ref.end_offset(); ptr++) {
    uint8_t b = *ptr;
    if (b <= 34) {
      switch (b) {
        // clang-format off
        case '\b': out << "\\b"; break;
        case '\t': out << "\\t"; break;
        case '\n': out << "\\n"; break;
        case '\f': out << "\\f"; break;
        case '\r': out << "\\r"; break;
        case ' ': out << ' '; break;
        case '!': out << '!'; break;
        case '"': out << "\\\""; break;
        // clang-format on
        default:
          out << "\\u00" << kHexChars[b >> 4] << kHexChars[b & 0xF];
          break;
      }
    } else if (b != 127 && b != '\\') {
      out << static_cast<char>(b);
    } else if (b == '\\') {
      out << "\\\\";
    } else {
      out << "\\x7F";
    }
  }
}
References v8::internal::wasm::WireBytesRef::end_offset(), kHexChars, and v8::internal::wasm::WireBytesRef::offset().
Referenced by v8::internal::wasm::ModuleDisassembler::PrintStringAsJSON().
PrintStringRaw()
void v8::internal::wasm::PrintStringRaw (StringBuilder & out, const uint8_t * start, const uint8_t * end)
Definition at line 202 of file wasm-disassembler.cc.
                                        {
  for (const uint8_t* ptr = start; ptr < end; ptr++) {
    uint8_t b = *ptr;
    if (b < 32 || b >= 127 || b == '"' || b == '\\') {
      out << '\\' << kHexChars[b >> 4] << kHexChars[b & 0xF];
    } else {
      out << static_cast<char>(b);
    }
  }
}
References v8::internal::compiler::end(), and kHexChars.
Referenced by v8::internal::wasm::ModuleDisassembler::PrintString(), and v8::internal::wasm::ImmediatesPrinter< ValidationTag >::StringConst().
PublishDetectedFeatures()
void v8::internal::wasm::PublishDetectedFeatures (WasmDetectedFeatures detected_features, Isolate * isolate, bool is_initial_compilation)
Definition at line 1728 of file module-compiler.cc.
                                                                            {
  using Feature = v8::Isolate::UseCounterFeature;
  static constexpr std::pair<WasmDetectedFeature, Feature> kUseCounters[] = {
      {WasmDetectedFeature::shared_memory, Feature::kWasmSharedMemory},
      {WasmDetectedFeature::reftypes, Feature::kWasmRefTypes},
      {WasmDetectedFeature::simd, Feature::kWasmSimdOpcodes},
      {WasmDetectedFeature::threads, Feature::kWasmThreadOpcodes},
      {WasmDetectedFeature::legacy_eh, Feature::kWasmExceptionHandling},
      {WasmDetectedFeature::memory64, Feature::kWasmMemory64},
      {WasmDetectedFeature::multi_memory, Feature::kWasmMultiMemory},
      {WasmDetectedFeature::gc, Feature::kWasmGC},
      {WasmDetectedFeature::imported_strings, Feature::kWasmImportedStrings},
      {WasmDetectedFeature::imported_strings_utf8,
       Feature::kWasmImportedStringsUtf8},
      {WasmDetectedFeature::return_call, Feature::kWasmReturnCall},
      {WasmDetectedFeature::extended_const, Feature::kWasmExtendedConst},
      {WasmDetectedFeature::relaxed_simd, Feature::kWasmRelaxedSimd},
      {WasmDetectedFeature::type_reflection, Feature::kWasmTypeReflection},
      {WasmDetectedFeature::exnref, Feature::kWasmExnRef},
      {WasmDetectedFeature::typed_funcref, Feature::kWasmTypedFuncRef},
      {WasmDetectedFeature::jspi, Feature::kWasmJavaScriptPromiseIntegration},
      {WasmDetectedFeature::branch_hinting, Feature::kWasmBranchHinting},
      {WasmDetectedFeature::multi_value, Feature::kWasmMultiValue},
  };
  // Check that every staging or shipping feature has a use counter as that is
  // the main point of tracking used features.
  auto check_use_counter = [](WasmDetectedFeature feat) constexpr -> bool {
    // Some features intentionally do not have a use counter.
    constexpr WasmDetectedFeature kIntentionallyNoUseCounter[] = {
        WasmDetectedFeature::stringref, // Deprecated / unlikely to ship.
    };
    for (auto no_use_counter_feature : kIntentionallyNoUseCounter) {
      if (feat == no_use_counter_feature) return true;
    }
    for (auto [feature, use_counter] : kUseCounters) {
      if (feat == feature) return true;
    }
    return false;
  };
#define CHECK_USE_COUNTER(feat, ...) \
  static_assert(check_use_counter(WasmDetectedFeature::feat));
  FOREACH_WASM_STAGING_FEATURE_FLAG(CHECK_USE_COUNTER)
  FOREACH_WASM_SHIPPED_FEATURE_FLAG(CHECK_USE_COUNTER)
  FOREACH_WASM_NON_FLAG_FEATURE(CHECK_USE_COUNTER)
#undef CHECK_USE_COUNTER
  static constexpr size_t kMaxFeatures = arraysize(kUseCounters) + 1;
  base::SmallVector<Feature, kMaxFeatures> use_counter_features;
  if (is_initial_compilation) {
    // Always set the WasmModuleCompilation feature as a baseline for the other
    // features. Note that we also track instantiation, but the number of
    // compilations and instantiations are pretty unrelated.
    use_counter_features.push_back(Feature::kWasmModuleCompilation);
  }
  for (auto [wasm_feature, feature] : kUseCounters) {
    if (!detected_features.contains(wasm_feature)) continue;
    use_counter_features.push_back(feature);
  }
  if (use_counter_features.empty()) return;
  isolate->CountUsage(base::VectorOf(use_counter_features));
  // Help differential fuzzers avoid detecting known/intentional platform-
  // specific differences.
  if (v8_flags.correctness_fuzzer_suppressions) {
    if (detected_features.has_relaxed_simd()) {
      PrintF("Warning: This run cannot be compared across architectures.\n");
    }
  }
}
References arraysize, CHECK_USE_COUNTER, v8::base::EnumSet< E, T >::contains(), v8::internal::Isolate::CountUsage(), v8::base::SmallVector< T, kSize, Allocator >::empty(), FOREACH_WASM_NON_FLAG_FEATURE, FOREACH_WASM_SHIPPED_FEATURE_FLAG, FOREACH_WASM_STAGING_FEATURE_FLAG, kWasmExnRef, v8::internal::PrintF(), v8::base::SmallVector< T, kSize, Allocator >::push_back(), v8::internal::v8_flags, and v8::base::VectorOf().
Referenced by CompileToNativeModule(), DeserializeNativeModule(), and v8::internal::wasm::AsyncCompileJob::FinishCompile().
Qfma()
float v8::internal::wasm::Qfma (float a, float b, float c)
Definition at line 693 of file wasm-external-refs.cc.
{ return a * b + c; }
Qfms()
float v8::internal::wasm::Qfms (float a, float b, float c)
Definition at line 699 of file wasm-external-refs.cc.
{ return -(a * b) + c; }
ReadFnId()
InstructionHandler v8::internal::wasm::ReadFnId (const uint8_t *& code) [inline]
Definition at line 1229 of file wasm-interpreter.h.
                                                         {
  InstructionHandler result = base::ReadUnalignedValue<InstructionHandler>(
      reinterpret_cast<Address>(code));
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
  if (v8_flags.trace_drumbrake_compact_bytecode) {
    printf("* ReadFnId %04x %s%s\n", result,
           kInstructionHandlerNames[result % kInstructionCount],
           result >= kInstructionCount ? " (large)" : "");
  }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
  code += sizeof(InstructionHandler);
  return result;
}
References code, kInstructionCount, v8::base::internal::result, and v8::internal::v8_flags.
Referenced by CallThroughDispatchTable().
reg_class_for()
static constexpr RegClass v8::internal::wasm::reg_class_for (ValueKind kind) [inline], [static], [constexpr]
Definition at line 56 of file liftoff-register.h.
                                                               {
  // Statically generate an array that we use for lookup at runtime.
  constexpr size_t kNumValueKinds = static_cast<size_t>(kTop);
  constexpr auto kRegClasses =
      base::make_array<kNumValueKinds>([](std::size_t kind) {
        switch (kind) {
          case kF16:
          case kF32:
          case kF64:
            return kFpReg;
          case kI8:
          case kI16:
          case kI32:
            return kGpReg;
          case kI64:
            return kNeedI64RegPair ? kGpRegPair : kGpReg;
          case kS128:
            return kNeedS128RegPair ? kFpRegPair : kFpReg;
          case kRef:
          case kRefNull:
            return kGpReg;
          case kVoid:
            return kNoReg; // unsupported kind
        }
        CONSTEXPR_UNREACHABLE();
      });
  V8_ASSUME(kind < kNumValueKinds);
  RegClass rc = kRegClasses[kind];
  V8_ASSUME(rc != kNoReg);
  return rc;
}
References CONSTEXPR_UNREACHABLE, v8::internal::kF32, v8::internal::kF64, kFpReg, kFpRegPair, kGpReg, kGpRegPair, v8::internal::kI16, v8::internal::kI32, v8::internal::kI64, v8::internal::kI8, kNeedI64RegPair, kNeedS128RegPair, kNoReg, v8::internal::kRef, v8::internal::kRefNull, v8::internal::kS128, v8::internal::size_t, and V8_ASSUME.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayAtomicCompareExchange(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayAtomicGet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayAtomicRMW(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayAtomicSet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayGet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayNew(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArraySet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::AtomicCompareExchange(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::AtomicLoadMem(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CatchCase(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CheckS128Nan(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitBinOp(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitBinOpImm(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitI8x16Swizzle(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitRelaxedLaneSelect(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitSimdExtractLaneOp(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitSimdFloatBinOpWithCFallback(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitSimdFloatRoundingOpWithCFallback(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitSimdFmaOp(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitSimdFmaOpWithCFallback(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitSimdReplaceLaneOp(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitSimdShiftOp(), v8::internal::wasm::liftoff::EmitSimdShiftOp(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitTerOp(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitTypeConversion(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitUnOp(), F16x8BinOpViaF32(), v8::internal::wasm::LiftoffAssembler::FinishCall(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GlobalGet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::I64Const(), v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::InitMergeRegion(), v8::internal::wasm::LiftoffVarState::LiftoffVarState(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::LoadExceptionValue(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::LoadLane(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::LoadMem(), v8::internal::wasm::LiftoffAssembler::LoadToRegister_Slow(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::LoadTransform(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::LocalGet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::LocalSetFromStackSlot(), v8::internal::wasm::ParallelMove::MoveRegister(), v8::internal::wasm::LiftoffAssembler::MoveToReturnLocations(), v8::internal::wasm::LiftoffAssembler::MoveToReturnLocationsMultiReturn(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ParameterProcessor::NextParam(), v8::internal::wasm::LiftoffAssembler::PrepareForBranch(), v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::PrepareStackTransfers(), v8::internal::wasm::LiftoffAssembler::PushRegister(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::S128Const(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::Simd8x16ShuffleOp(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StoreExceptionValue(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructAtomicCompareExchange(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructAtomicGet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructAtomicRMW(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructGet(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructNew().
RestoreProfileData()
std::unique_ptr<ProfileInformation> v8::internal::wasm::RestoreProfileData (const WasmModule * module, base::Vector< uint8_t > profile_data)
Definition at line 182 of file pgo.cc.
                                                                {
  Decoder decoder{profile_data.begin(), profile_data.end()};
  DeserializeTypeFeedback(decoder, module);
  std::unique_ptr<ProfileInformation> pgo_info =
      DeserializeTieringInformation(decoder, module);
  CHECK(decoder.ok());
  CHECK_EQ(decoder.pc(), decoder.end());
  return pgo_info;
}
References v8::base::Vector< T >::begin(), CHECK, CHECK_EQ, DeserializeTieringInformation(), DeserializeTypeFeedback(), and v8::base::Vector< T >::end().
Referenced by LoadProfileFromFile().
return_switch()
void v8::internal::wasm::return_switch (Isolate * isolate, wasm::StackMemory * from)
Definition at line 990 of file wasm-external-refs.cc.
                                                            {
  isolate->SwitchStacks(from, isolate->isolate_data()->active_stack());
  isolate->RetireWasmStack(from);
}
References v8::internal::IsolateData::active_stack(), and v8::internal::Isolate::isolate_data().
Referenced by v8::internal::anonymous_namespace{builtins-riscv.cc}::SwitchStacks().
SectionName()
V8_EXPORT_PRIVATE const char * v8::internal::wasm::SectionName (SectionCode code)
Definition at line 22 of file module-decoder.cc.
                                          {
  switch (code) {
    case kUnknownSectionCode:
      return "Unknown";
    case kTypeSectionCode:
      return "Type";
    case kImportSectionCode:
      return "Import";
    case kFunctionSectionCode:
      return "Function";
    case kTableSectionCode:
      return "Table";
    case kMemorySectionCode:
      return "Memory";
    case kGlobalSectionCode:
      return "Global";
    case kExportSectionCode:
      return "Export";
    case kStartSectionCode:
      return "Start";
    case kCodeSectionCode:
      return "Code";
    case kElementSectionCode:
      return "Element";
    case kDataSectionCode:
      return "Data";
    case kTagSectionCode:
      return "Tag";
    case kStringRefSectionCode:
      return "StringRef";
    case kDataCountSectionCode:
      return "DataCount";
    case kNameSectionCode:
      return kNameString;
    case kSourceMappingURLSectionCode:
      return kSourceMappingURLString;
    case kDebugInfoSectionCode:
      return kDebugInfoString;
    case kExternalDebugInfoSectionCode:
      return kExternalDebugInfoString;
    case kBuildIdSectionCode:
      return kBuildIdString;
    case kInstTraceSectionCode:
      return kInstTraceString;
    case kCompilationHintsSectionCode:
      return kCompilationHintsString;
    case kBranchHintsSectionCode:
      return kBranchHintsString;
    case kDescriptorsSectionCode:
      return kDescriptorsString;
    default:
      return "<unknown>";
  }
}
References code, kBranchHintsSectionCode, kBranchHintsString, kBuildIdSectionCode, kBuildIdString, kCodeSectionCode, kCompilationHintsSectionCode, kCompilationHintsString, kDataCountSectionCode, kDataSectionCode, kDebugInfoSectionCode, kDebugInfoString, kDescriptorsSectionCode, kDescriptorsString, kElementSectionCode, kExportSectionCode, kExternalDebugInfoSectionCode, kExternalDebugInfoString, kFunctionSectionCode, kGlobalSectionCode, kImportSectionCode, kInstTraceSectionCode, kInstTraceString, kMemorySectionCode, kNameSectionCode, kNameString, kSourceMappingURLSectionCode, kSourceMappingURLString, kStartSectionCode, kStringRefSectionCode, kTableSectionCode, kTagSectionCode, kTypeSectionCode, and kUnknownSectionCode.
Referenced by v8::internal::wasm::ModuleDecoderImpl::CheckSectionOrder(), v8::internal::wasm::ModuleDecoderImpl::DecodeSection(), v8::internal::wasm::WasmSectionIterator::next(), and v8::internal::wasm::AsyncStreamingDecoder::DecodeSectionID::Next().
shrink_stack()
Address v8::internal::wasm::shrink_stack (Isolate * isolate)
Definition at line 1097 of file wasm-external-refs.cc.
                                       {
  // If there is no parent, then the current stack is the main isolate stack.
  wasm::StackMemory* active_stack = isolate->isolate_data()->active_stack();
  if (active_stack->jmpbuf()->parent == nullptr) {
    return 0;
  }
  DCHECK(active_stack->IsActive());
  Address old_fp = active_stack->Shrink();
  isolate->stack_guard()->SetStackLimitForStackSwitching(
      reinterpret_cast<uintptr_t>(active_stack->jslimit()));
  return old_fp;
}
References v8::internal::IsolateData::active_stack(), v8::internal::DCHECK(), v8::internal::wasm::StackMemory::IsActive(), v8::internal::Isolate::isolate_data(), v8::internal::wasm::StackMemory::jmpbuf(), v8::internal::wasm::StackMemory::jslimit(), v8::internal::wasm::JumpBuffer::parent, v8::internal::StackGuard::SetStackLimitForStackSwitching(), v8::internal::wasm::StackMemory::Shrink(), and v8::internal::Isolate::stack_guard().
simd_float16_bin_wrapper()
template<typename R , R(*)(Float16, Float16) float_bin_op>
void v8::internal::wasm::simd_float16_bin_wrapper (Address data)
Definition at line 468 of file wasm-external-refs.cc.
                                            {
  constexpr int n = kSimd128Size / sizeof(Float16);
  for (int i = 0; i < n; i++) {
    Float16 lhs = Float16::Read(data + (i * sizeof(Float16)));
    Float16 rhs = Float16::Read(data + kSimd128Size + (i * sizeof(Float16)));
    R value = float_bin_op(lhs, rhs);
    WriteUnalignedValue<R>(data + (i * sizeof(R)), value);
  }
}
References v8::internal::kSimd128Size, v8::internal::Float16::Read(), and v8::internal::value.
simd_float16_fma_wrapper()
template<float(*)(float, float, float) float_fma_op>
void v8::internal::wasm::simd_float16_fma_wrapper (Address data)
Definition at line 681 of file wasm-external-refs.cc.
                                            {
  constexpr int n = kSimd128Size / sizeof(Float16);
  for (int i = 0; i < n; i++) {
    Address offset = data + i * sizeof(Float16);
    Float16 a = Float16::Read(offset);
    Float16 b = Float16::Read(offset + kSimd128Size);
    Float16 c = Float16::Read(offset + 2 * kSimd128Size);
    float value = float_fma_op(a.ToFloat32(), b.ToFloat32(), c.ToFloat32());
    Float16::FromFloat32(value).Write(offset);
  }
}
References v8::internal::Float16::FromFloat32(), v8::internal::kSimd128Size, v8::internal::Float16::Read(), v8::internal::Float16::ToFloat32(), v8::internal::value, and v8::internal::Float16::Write().
simd_float_round_wrapper()
template<typename T , T(*)(T) float_round_op>
void v8::internal::wasm::simd_float_round_wrapper (Address data)
Definition at line 369 of file wasm-external-refs.cc.
                                            {
  constexpr int n = kSimd128Size / sizeof(T);
  for (int i = 0; i < n; i++) {
    T input = ReadUnalignedValue<T>(data + (i * sizeof(T)));
    T value = float_round_op(input);
#if V8_OS_AIX
    value = FpOpWorkaround<T>(input, value);
#endif
    WriteUnalignedValue<T>(data + (i * sizeof(T)), value);
  }
}
References v8::internal::kSimd128Size, T, and v8::internal::value.
simd_float_un_wrapper()
template<typename T , typename R , R(*)(T) float_un_op>
void v8::internal::wasm::simd_float_un_wrapper (Address data)
Definition at line 575 of file wasm-external-refs.cc.
                                         {
  constexpr int n = kSimd128Size / sizeof(T);
  for (int i = 0; i < n; i++) {
    T input = ReadUnalignedValue<T>(data + (i * sizeof(T)));
    R value = float_un_op(input);
    WriteUnalignedValue<R>(data + (i * sizeof(T)), value);
  }
}
References v8::internal::kSimd128Size, T, and v8::internal::value.
StartStreamingForTesting()
V8_EXPORT_PRIVATE std::unique_ptr< WasmStreaming > v8::internal::wasm::StartStreamingForTesting (Isolate * isolate, std::shared_ptr< wasm::CompilationResultResolver > resolver)
Definition at line 3950 of file wasm-js.cc.
                                                           {
  return std::make_unique<WasmStreaming>(
      std::make_unique<WasmStreaming::WasmStreamingImpl>(
          isolate, "StartStreamingForTesting", CompileTimeImports{}, resolver));
}
StringCheck()
static bool v8::internal::wasm::StringCheck (const WasmRef obj) [static]
Definition at line 2716 of file wasm-interpreter-runtime.cc.
                                           {
  if (IsSmi(*obj)) {
    return false;
  }
  if (!IsHeapObject(*obj)) return false;
  InstanceType instance_type = Cast<HeapObject>(obj)->map()->instance_type();
  return instance_type < FIRST_NONSTRING_TYPE;
}
References v8::internal::FIRST_NONSTRING_TYPE, v8::internal::IsHeapObject(), and v8::internal::IsSmi().
StructCheck()
static bool v8::internal::wasm::StructCheck (const WasmRef obj) [static]
Definition at line 2688 of file wasm-interpreter-runtime.cc.
                                           {
  if (IsSmi(*obj)) {
    return false;
  }
  if (!IsHeapObject(*obj)) return false;
  InstanceType instance_type = Cast<HeapObject>(obj)->map()->instance_type();
  return instance_type == WASM_STRUCT_TYPE;
}
References v8::internal::IsHeapObject(), and v8::internal::IsSmi().
StructFieldOffset()
static int v8::internal::wasm::StructFieldOffset (const StructType * struct_type, int field_index) [static]
Definition at line 746 of file wasm-interpreter.cc.
                                                                             {
  return wasm::ObjectAccess::ToTagged(WasmStruct::kHeaderSize +
                                      struct_type->field_offset(field_index));
}
References v8::internal::wasm::StructTypeBase::field_offset(), and v8::internal::wasm::ObjectAccess::ToTagged().
Referenced by v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction(), v8::internal::wasm::Handlers< Compressed >::s2s_StructNew(), v8::internal::wasm::Handlers< Compressed >::s2s_StructNewDefault(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructAtomicCompareExchange(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructAtomicGet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructAtomicRMW(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructAtomicSet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructGet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructNew(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructSet().
switch_from_the_central_stack()
void v8::internal::wasm::switch_from_the_central_stack (Isolate * isolate)
Definition at line 1014 of file wasm-external-refs.cc.
                                                     {
  ThreadLocalTop* thread_local_top = isolate->thread_local_top();
  CHECK_NE(thread_local_top->secondary_stack_sp_, 0);
  CHECK_NE(thread_local_top->secondary_stack_limit_, 0);
  auto secondary_stack_limit = thread_local_top->secondary_stack_limit_;
  thread_local_top->secondary_stack_limit_ = 0;
  thread_local_top->secondary_stack_sp_ = 0;
  thread_local_top->is_on_central_stack_flag_ = false;
  StackGuard* stack_guard = isolate->stack_guard();
  stack_guard->SetStackLimitForStackSwitching(secondary_stack_limit);
}
References CHECK_NE, v8::internal::ThreadLocalTop::is_on_central_stack_flag_, v8::internal::ThreadLocalTop::secondary_stack_limit_, v8::internal::ThreadLocalTop::secondary_stack_sp_, v8::internal::StackGuard::SetStackLimitForStackSwitching(), v8::internal::Isolate::stack_guard(), and v8::internal::Isolate::thread_local_top().
switch_from_the_central_stack_for_js()
void v8::internal::wasm::switch_from_the_central_stack_for_js (Isolate * isolate)
Definition at line 1040 of file wasm-external-refs.cc.
                                                            {
  // The stack only contains wasm frames after this JS call.
  wasm::StackMemory* stack = isolate->isolate_data()->active_stack();
  stack->clear_stack_switch_info();
  ThreadLocalTop* thread_local_top = isolate->thread_local_top();
  thread_local_top->is_on_central_stack_flag_ = false;
  StackGuard* stack_guard = isolate->stack_guard();
  stack_guard->SetStackLimitForStackSwitching(
      reinterpret_cast<uintptr_t>(stack->jslimit()));
}
References v8::internal::IsolateData::active_stack(), v8::internal::ThreadLocalTop::is_on_central_stack_flag_, v8::internal::Isolate::isolate_data(), v8::internal::StackGuard::SetStackLimitForStackSwitching(), v8::internal::stack, v8::internal::Isolate::stack_guard(), and v8::internal::Isolate::thread_local_top().
switch_stacks()
void v8::internal::wasm::switch_stacks (Isolate * isolate, wasm::StackMemory * from)
Definition at line 986 of file wasm-external-refs.cc.
                                                            {
  isolate->SwitchStacks(from, isolate->isolate_data()->active_stack());
}
References v8::internal::IsolateData::active_stack(), and v8::internal::Isolate::isolate_data().
switch_to_the_central_stack()
intptr_t v8::internal::wasm::switch_to_the_central_stack (Isolate * isolate, uintptr_t current_sp)
Definition at line 995 of file wasm-external-refs.cc.
                                                                             {
  ThreadLocalTop* thread_local_top = isolate->thread_local_top();
  StackGuard* stack_guard = isolate->stack_guard();
  auto secondary_stack_limit = stack_guard->real_jslimit();
  stack_guard->SetStackLimitForStackSwitching(
      thread_local_top->central_stack_limit_);
  thread_local_top->secondary_stack_limit_ = secondary_stack_limit;
  thread_local_top->secondary_stack_sp_ = current_sp;
  thread_local_top->is_on_central_stack_flag_ = true;
  auto counter = isolate->wasm_switch_to_the_central_stack_counter();
  isolate->set_wasm_switch_to_the_central_stack_counter(counter + 1);
  return thread_local_top->central_stack_sp_;
}
References v8::internal::ThreadLocalTop::central_stack_limit_, v8::internal::ThreadLocalTop::central_stack_sp_, v8::internal::ThreadLocalTop::is_on_central_stack_flag_, v8::internal::StackGuard::real_jslimit(), v8::internal::ThreadLocalTop::secondary_stack_limit_, v8::internal::ThreadLocalTop::secondary_stack_sp_, v8::internal::StackGuard::SetStackLimitForStackSwitching(), v8::internal::Isolate::stack_guard(), and v8::internal::Isolate::thread_local_top().
Referenced by v8::internal::compiler::CodeAssembler::CallRuntimeImpl(), and v8::internal::compiler::CodeAssembler::TailCallRuntimeImpl().
switch_to_the_central_stack_for_js()
intptr_t v8::internal::wasm::switch_to_the_central_stack_for_js (Isolate * isolate, Address fp)
Definition at line 1028 of file wasm-external-refs.cc.
                                                                          {
  ThreadLocalTop* thread_local_top = isolate->thread_local_top();
  StackGuard* stack_guard = isolate->stack_guard();
  wasm::StackMemory* stack = isolate->isolate_data()->active_stack();
  Address central_stack_sp = thread_local_top->central_stack_sp_;
  stack->set_stack_switch_info(fp, central_stack_sp);
  stack_guard->SetStackLimitForStackSwitching(
      thread_local_top->central_stack_limit_);
  thread_local_top->is_on_central_stack_flag_ = true;
  return central_stack_sp;
}
References v8::internal::IsolateData::active_stack(), v8::internal::ThreadLocalTop::central_stack_limit_, v8::internal::ThreadLocalTop::central_stack_sp_, v8::internal::ThreadLocalTop::is_on_central_stack_flag_, v8::internal::Isolate::isolate_data(), v8::internal::StackGuard::SetStackLimitForStackSwitching(), v8::internal::stack, v8::internal::Isolate::stack_guard(), and v8::internal::Isolate::thread_local_top().
ThrowLazyCompilationError()
void v8::internal::wasm::ThrowLazyCompilationError (Isolate * isolate, const NativeModule * native_module, int func_index)
Definition at line 1253 of file module-compiler.cc.
                                               {
  const WasmModule* module = native_module->module();
  CompilationStateImpl* compilation_state =
      Impl(native_module->compilation_state());
  const WasmFunction* func = &module->functions[func_index];
  base::Vector<const uint8_t> code =
      compilation_state->GetWireBytesStorage()->GetCode(func->code);
  auto enabled_features = native_module->enabled_features();
  // This path is unlikely, so the overhead for creating an extra Zone is
  // not important.
  Zone validation_zone{GetWasmEngine()->allocator(), ZONE_NAME};
  WasmDetectedFeatures unused_detected_features;
  DecodeResult decode_result =
      ValidateSingleFunction(&validation_zone, module, func_index, code,
                             enabled_features, &unused_detected_features);
  CHECK(decode_result.failed());
  wasm::ErrorThrower thrower(isolate, nullptr);
  thrower.CompileFailed(GetWasmErrorWithName(native_module->wire_bytes(),
                                             func_index, module,
                                             std::move(decode_result).error()));
}
References v8::internal::wasm::WasmEngine::allocator(), CHECK, code, v8::internal::wasm::WasmFunction::code, v8::internal::wasm::NativeModule::compilation_state(), v8::internal::wasm::ErrorThrower::CompileFailed(), v8::internal::wasm::NativeModule::enabled_features(), v8::internal::wasm::Result< T >::failed(), v8::internal::wasm::WasmModule::functions, GetWasmEngine(), GetWasmErrorWithName(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::Impl(), v8::internal::wasm::NativeModule::module(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ValidateSingleFunction(), v8::internal::wasm::NativeModule::wire_bytes(), and ZONE_NAME.
Referenced by v8::internal::RUNTIME_FUNCTION().
TierUpAllForTesting()
V8_EXPORT_PRIVATE void v8::internal::wasm::TierUpAllForTesting (Isolate * isolate, Tagged< WasmTrustedInstanceData > trusted_instance_data)
Definition at line 1708 of file module-compiler.cc.
                                                                             {
  NativeModule* native_module = trusted_instance_data->native_module();
  const WasmModule* mod = native_module->module();
  WasmCodeRefScope code_ref_scope;
  uint32_t start = mod->num_imported_functions;
  uint32_t end = start + mod->num_declared_functions;
  for (uint32_t func_index = start; func_index < end; func_index++) {
    if (!native_module->HasCodeWithTier(func_index, ExecutionTier::kTurbofan)) {
      TierUpNowForTesting(isolate, trusted_instance_data, func_index);
    }
  }
}
References v8::internal::compiler::end(), v8::internal::wasm::NativeModule::HasCodeWithTier(), kTurbofan, v8::internal::wasm::NativeModule::module(), v8::internal::wasm::WasmModule::num_declared_functions, v8::internal::wasm::WasmModule::num_imported_functions, and TierUpNowForTesting().
TierUpNowForTesting()
V8_EXPORT_PRIVATE void v8::internal::wasm::TierUpNowForTesting (Isolate * isolate, Tagged< WasmTrustedInstanceData > trusted_instance_data, int func_index)
Definition at line 1694 of file module-compiler.cc.
                                         {
  NativeModule* native_module = trusted_instance_data->native_module();
  if (v8_flags.wasm_inlining) {
    TransitiveTypeFeedbackProcessor::Process(isolate, trusted_instance_data,
                                             func_index);
  }
  wasm::GetWasmEngine()->CompileFunction(isolate->counters(), native_module,
                                         func_index,
                                         wasm::ExecutionTier::kTurbofan);
  CHECK(!native_module->compilation_state()->failed());
}
References CHECK, v8::internal::wasm::NativeModule::compilation_state(), v8::internal::wasm::WasmEngine::CompileFunction(), v8::internal::Isolate::counters(), v8::internal::wasm::CompilationState::failed(), GetWasmEngine(), kTurbofan, v8::internal::wasm::TransitiveTypeFeedbackProcessor::Process(), and v8::internal::v8_flags.
Referenced by v8::internal::RUNTIME_FUNCTION(), and TierUpAllForTesting().
to_error()
MessageTemplate v8::internal::wasm::to_error (ValueOrError result) [inline]
Definition at line 123 of file constant-expression.h.
                                                        {
  return std::get<MessageTemplate>(result);
}
References v8::base::internal::result.
Referenced by InitializeElementSegment(), and v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::MaybeMarkError().
to_value()
WasmValue v8::internal::wasm::to_value (ValueOrError result) [inline]
Definition at line 126 of file constant-expression.h.
                                                  {
  return std::get<WasmValue>(result);
}
References v8::base::internal::result.
Referenced by v8::internal::wasm::InstanceBuilder::InitGlobals(), InitializeElementSegment(), v8::internal::wasm::InstanceBuilder::LoadDataSegments(), v8::internal::wasm::InstanceBuilder::LoadTableSegments(), v8::internal::HeapObjectsMap::MoveObject(), and v8::internal::wasm::InstanceBuilder::SetTableInitialValues().
ToNullSentinel()
ValueType v8::internal::wasm::ToNullSentinel (TypeInModule type)
Definition at line 657 of file wasm-subtyping.cc.
                                            {
  HeapType null_heap = NullSentinelImpl(type.type.heap_type());
  DCHECK(IsHeapSubtypeOf(null_heap, type.type.heap_type(), type.module));
  return ValueType::RefNull(null_heap);
}
References v8::internal::DCHECK(), IsHeapSubtypeOf(), v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::NullSentinelImpl(), v8::internal::wasm::ValueType::RefNull(), and v8::internal::tracing::type.
Referenced by Intersection(), v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::IsNull(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessBranchOnTarget(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessNull(), v8::internal::compiler::WasmTyper::Reduce(), v8::internal::compiler::WasmGCOperatorReducer::ReduceIf(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCast(), and v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCastAbstract().
trace_PushSlot()
template<typename T >
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::trace_PushSlot (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0)
TrapMemOutOfBounds()
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::TrapMemOutOfBounds (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0)
Definition at line 8661 of file wasm-interpreter.cc.
                               {
  TRAP(TrapReason::kTrapMemOutOfBounds)
}
References TRAP.
Referenced by v8::internal::wasm::WasmInterpreter::WasmInterpreter().
TriggerTierUp()
V8_EXPORT_PRIVATE void v8::internal::wasm::TriggerTierUp (Isolate * isolate, Tagged< WasmTrustedInstanceData > trusted_instance_data, int func_index)
Definition at line 1654 of file module-compiler.cc.
                                   {
  NativeModule* native_module = trusted_instance_data->native_module();
  CompilationStateImpl* compilation_state =
      Impl(native_module->compilation_state());
  WasmCompilationUnit tiering_unit{func_index, ExecutionTier::kTurbofan,
                                   kNotForDebugging};
  const WasmModule* module = native_module->module();
  int priority;
  {
    base::MutexGuard mutex_guard(&module->type_feedback.mutex);
    int array_index = wasm::declared_function_index(module, func_index);
    trusted_instance_data->tiering_budget_array()[array_index].store(
        v8_flags.wasm_tiering_budget, std::memory_order_relaxed);
    int& stored_priority =
        module->type_feedback.feedback_for_function[func_index].tierup_priority;
    if (stored_priority < kMaxInt) ++stored_priority;
    priority = stored_priority;
  }
  // Only create a compilation unit if this is the first time we detect this
  // function as hot (priority == 1), or if the priority increased
  // significantly. The latter is assumed to be the case if the priority
  // increased at least to four, and is a power of two.
  if (priority == 2 || !base::bits::IsPowerOfTwo(priority)) return;
  // Before adding the tier-up unit or increasing priority, process type
  // feedback for best code generation.
  if (v8_flags.wasm_inlining) {
    // TODO(jkummerow): we could have collisions here if different instances
    // of the same module have collected different feedback. If that ever
    // becomes a problem, figure out a solution.
    TransitiveTypeFeedbackProcessor::Process(isolate, trusted_instance_data,
                                             func_index);
  }
  compilation_state->AddTopTierPriorityCompilationUnit(tiering_unit, priority);
}
References v8::internal::wasm::NativeModule::compilation_state(), declared_function_index(), v8::internal::wasm::TypeFeedbackStorage::feedback_for_function, v8::internal::wasm::anonymous_namespace{module-compiler.cc}::Impl(), v8::base::bits::IsPowerOfTwo(), v8::internal::kMaxInt, kNotForDebugging, kTurbofan, v8::internal::wasm::NativeModule::module(), v8::internal::wasm::TypeFeedbackStorage::mutex, v8::internal::wasm::TransitiveTypeFeedbackProcessor::Process(), v8::internal::wasm::WasmModule::type_feedback, and v8::internal::v8_flags.
Referenced by v8::internal::RUNTIME_FUNCTION().
uint64_div_wrapper()
V8_EXPORT_PRIVATE int32_t v8::internal::wasm::uint64_div_wrapper (Address data)
Definition at line 326 of file wasm-external-refs.cc.
                                         {
  uint64_t dividend = ReadUnalignedValue<uint64_t>(data);
  uint64_t divisor = ReadUnalignedValue<uint64_t>(data + sizeof(dividend));
  if (divisor == 0) {
    return 0;
  }
  WriteUnalignedValue<uint64_t>(data, dividend / divisor);
  return 1;
}
uint64_mod_wrapper()
V8_EXPORT_PRIVATE int32_t v8::internal::wasm::uint64_mod_wrapper (Address data)
Definition at line 336 of file wasm-external-refs.cc.
                                         {
  uint64_t dividend = ReadUnalignedValue<uint64_t>(data);
  uint64_t divisor = ReadUnalignedValue<uint64_t>(data + sizeof(dividend));
  if (divisor == 0) {
    return 0;
  }
  WriteUnalignedValue<uint64_t>(data, dividend % divisor);
  return 1;
}
uint64_to_float32_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::uint64_to_float32_wrapper (Address data)
Definition at line 97 of file wasm-external-refs.cc.
                                             {
  uint64_t input = ReadUnalignedValue<uint64_t>(data);
#if defined(V8_OS_WIN)
  // On Windows, the FP stack registers calculate with less precision, which
  // leads to a uint64_t to float32 conversion which does not satisfy the
  // WebAssembly specification. Therefore we do a different approach here:
  //
  // / leading 0 \/ 24 float data bits \/ for rounding \/ trailing 0 \
  // 00000000000001XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX100000000000000
  //
  // Float32 can only represent 24 data bit (1 implicit 1 bit + 23 mantissa
  // bits). Starting from the most significant 1 bit, we can therefore extract
  // 24 bits and do the conversion only on them. The other bits can affect the
  // result only through rounding. Rounding works as follows:
  // * If the most significant rounding bit is not set, then round down.
  // * If the most significant rounding bit is set, and at least one of the
  // other rounding bits is set, then round up.
  // * If the most significant rounding bit is set, but all other rounding bits
  // are not set, then round to even.
  // We can aggregate 'all other rounding bits' in the second-most significant
  // rounding bit.
  // The resulting algorithm is therefore as follows:
  // * Check if the distance between the most significant bit (MSB) and the
  // least significant bit (LSB) is greater than 25 bits. If the distance is
  // less or equal to 25 bits, the uint64 to float32 conversion is anyways
  // exact, and we just use the C++ conversion.
  // * Find the most significant bit (MSB).
  // * Starting from the MSB, extract 25 bits (24 data bits + the first rounding
  // bit).
  // * The remaining rounding bits are guaranteed to contain at least one 1 bit,
  // due to the check we did above.
  // * Store the 25 bits + 1 aggregated bit in an uint32_t.
  // * Convert this uint32_t to float. The conversion does the correct rounding
  // now.
  // * Shift the result back to the original magnitude.
  uint32_t leading_zeros = base::bits::CountLeadingZeros(input);
  uint32_t trailing_zeros = base::bits::CountTrailingZeros(input);
  constexpr uint32_t num_extracted_bits = 25;
  // Check if there are any rounding bits we have to aggregate.
  if (leading_zeros + trailing_zeros + num_extracted_bits < 64) {
    // Shift to extract the data bits.
    uint32_t num_aggregation_bits = 64 - num_extracted_bits - leading_zeros;
    // We extract the bits we want to convert. Note that we convert one bit more
    // than necessary. This bit is a placeholder where we will store the
    // aggregation bit.
    int32_t extracted_bits =
        static_cast<int32_t>(input >> (num_aggregation_bits - 1));
    // Set the aggregation bit. We don't have to clear the slot first, because
    // the bit there is also part of the aggregation.
    extracted_bits |= 1;
    float result = static_cast<float>(extracted_bits);
    // We have to shift the result back. The shift amount is
    // (num_aggregation_bits - 1), which is the shift amount we did originally,
    // and (-2), which is for the two additional bits we kept originally for
    // rounding.
    int32_t shift_back = static_cast<int32_t>(num_aggregation_bits) - 1 - 2;
    // Calculate the multiplier to shift the extracted bits back to the original
    // magnitude. This multiplier is a power of two, so in the float32 bit
    // representation we just have to construct the correct exponent and put it
    // at the correct bit offset. The exponent consists of 8 bits, starting at
    // the second MSB (a.k.a '<< 23'). The encoded exponent itself is
    // ('actual exponent' - 127).
    int32_t multiplier_bits = ((shift_back - 127) & 0xff) << 23;
    result *= base::bit_cast<float>(multiplier_bits);
    WriteUnalignedValue<float>(data, result);
    return;
  }
#endif // defined(V8_OS_WIN)
  WriteUnalignedValue<float>(data, static_cast<float>(input));
}
References v8::base::bits::CountLeadingZeros(), v8::base::bits::CountTrailingZeros(), v8::base::leading_zeros, and v8::base::internal::result.
uint64_to_float64_wrapper()
V8_EXPORT_PRIVATE void v8::internal::wasm::uint64_to_float64_wrapper (Address data)
Definition at line 173 of file wasm-external-refs.cc.
                                             {
  uint64_t input = ReadUnalignedValue<uint64_t>(data);
  double result = static_cast<double>(input);
#if V8_CC_MSVC
  // With MSVC we use static_cast<double>(uint32_t) instead of
  // static_cast<double>(uint64_t) to achieve round-to-nearest-ties-even
  // semantics. The idea is to calculate
  // static_cast<double>(high_word) * 2^32 + static_cast<double>(low_word).
  uint32_t low_word = static_cast<uint32_t>(input & 0xFFFFFFFF);
  uint32_t high_word = static_cast<uint32_t>(input >> 32);
  double shift = static_cast<double>(1ull << 32);
  result = static_cast<double>(high_word);
  result *= shift;
  result += static_cast<double>(low_word);
#endif
  WriteUnalignedValue<double>(data, result);
}
References v8::base::internal::result.
Union()
V8_EXPORT_PRIVATE TypeInModule v8::internal::wasm::Union (ValueType type1, ValueType type2, const WasmModule * module)
Definition at line 594 of file wasm-subtyping.cc.
                                                               {
  if (type1 == kWasmTop || type2 == kWasmTop) return {kWasmTop, module};
  if (type1 == kWasmBottom) return {type2, module};
  if (type2 == kWasmBottom) return {type1, module};
  if (!type1.is_ref() || !type2.is_ref()) {
    return {type1 == type2 ? type1 : kWasmTop, module};
  }
  Nullability nullability =
      type1.is_nullable() || type2.is_nullable() ? kNullable : kNonNullable;
  Exactness exactness = UnionExactness(type1, type2, module);
  HeapType heap1 = type1.heap_type();
  HeapType heap2 = type2.heap_type();
  if (heap1 == heap2) {
    return {type1.AsNullable(nullability).AsExactIfIndexed(exactness), module};
  }
  HeapType result_type = kWasmBottom;
  if (heap1.is_abstract_ref()) {
    result_type = CommonAncestorWithAbstract(heap1, heap2);
  } else if (heap2.is_abstract_ref()) {
    result_type = CommonAncestorWithAbstract(heap2, heap1);
  } else {
    result_type = CommonAncestor(heap1, heap2, module);
  }
  // The type could only be kBottom if the input was kBottom but any kBottom
  // HeapType should be "normalized" to kWasmBottom ValueType.
  DCHECK_NE(result_type, kWasmBottom);
  if (result_type.is_top()) return {kWasmTop, module};
  return {ValueType::RefMaybeNull(result_type, nullability).AsExact(exactness),
          module};
}
References v8::internal::wasm::ValueType::AsExact(), v8::internal::wasm::ValueType::AsExactIfIndexed(), v8::internal::wasm::ValueType::AsNullable(), v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::CommonAncestor(), v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::CommonAncestorWithAbstract(), DCHECK_NE, v8::internal::wasm::ValueType::heap_type(), v8::internal::wasm::ValueTypeBase::is_abstract_ref(), v8::internal::wasm::ValueTypeBase::is_nullable(), v8::internal::wasm::ValueTypeBase::is_ref(), v8::internal::wasm::ValueTypeBase::is_top(), kNonNullable, kNullable, kWasmBottom, kWasmTop, v8::internal::wasm::ValueType::RefMaybeNull(), and v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::UnionExactness().
Referenced by v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::CreateMergeSnapshot(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessPhi(), and v8::internal::compiler::WasmTyper::Reduce().
unpacked()
constexpr ValueKind v8::internal::wasm::unpacked (ValueKind kind) [constexpr]
Definition at line 1227 of file value-type.h.
                                             {
  return is_packed(kind) ? (kind == kF16 ? kF32 : kI32) : kind;
}
References is_packed(), v8::internal::kF32, and v8::internal::kI32.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayAtomicGet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayGet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructAtomicGet(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructGet().
UpdateComputedInformation()
void v8::internal::wasm::UpdateComputedInformation (WasmMemory * memory, ModuleOrigin origin)
Definition at line 28 of file wasm-module.cc.
                                                                        {
  const uintptr_t platform_max_pages =
      memory->is_memory64() ? wasm::max_mem64_pages() : wasm::max_mem32_pages();
  memory->min_memory_size = static_cast<uintptr_t>(std::min<uint64_t>(
                                platform_max_pages, memory->initial_pages)) *
                            kWasmPageSize;
  memory->max_memory_size = static_cast<uintptr_t>(std::min<uint64_t>(
                                platform_max_pages, memory->maximum_pages)) *
                            kWasmPageSize;
  if (!v8_flags.wasm_bounds_checks) {
    memory->bounds_checks = kNoBoundsChecks;
  } else if (v8_flags.wasm_enforce_bounds_checks) {
    // Explicit bounds checks requested via flag (for testing).
    memory->bounds_checks = kExplicitBoundsChecks;
  } else if (origin != kWasmOrigin) {
    // Asm.js modules can't use trap handling.
    memory->bounds_checks = kExplicitBoundsChecks;
  } else if (memory->is_memory64() && !v8_flags.wasm_memory64_trap_handling) {
    memory->bounds_checks = kExplicitBoundsChecks;
  } else if (trap_handler::IsTrapHandlerEnabled()) {
    if constexpr (kSystemPointerSize == 4) UNREACHABLE();
    memory->bounds_checks = kTrapHandler;
  } else {
    // If the trap handler is not enabled, fall back to explicit bounds checks.
    memory->bounds_checks = kExplicitBoundsChecks;
  }
}
References v8::internal::wasm::WasmMemory::bounds_checks, v8::internal::wasm::WasmMemory::initial_pages, v8::internal::wasm::WasmMemory::is_memory64(), v8::internal::trap_handler::IsTrapHandlerEnabled(), kExplicitBoundsChecks, kNoBoundsChecks, v8::internal::kSystemPointerSize, kTrapHandler, kWasmOrigin, kWasmPageSize, max_mem32_pages(), max_mem64_pages(), v8::internal::wasm::WasmMemory::max_memory_size, v8::internal::wasm::WasmMemory::maximum_pages, v8::internal::wasm::WasmMemory::min_memory_size, v8::internal::UNREACHABLE(), and v8::internal::v8_flags.
Referenced by v8::internal::wasm::ModuleDecoderImpl::UpdateComputedMemoryInformation().
V8_DECLARE_ONCE() [1/2]
v8::internal::wasm::V8_DECLARE_ONCE (init_instruction_table_once)
V8_DECLARE_ONCE() [2/2]
v8::internal::wasm::V8_DECLARE_ONCE (init_trap_handlers_once)
validate_utf8()
bool v8::internal::wasm::validate_utf8 (Decoder * decoder, WireBytesRef string) [inline]
Definition at line 58 of file module-decoder-impl.h.
                                                                 {
  return unibrow::Utf8::ValidateEncoding(
      decoder->start() + decoder->GetBufferRelativeOffset(string.offset()),
      string.length());
}
References v8::internal::wasm::Decoder::GetBufferRelativeOffset(), v8::internal::wasm::Decoder::start(), and unibrow::Utf8::ValidateEncoding().
Referenced by DecodeCanonicalTypeNames(), v8::internal::wasm::anonymous_namespace{module-decoder.cc}::DecodeNameMapInternal(), v8::internal::wasm::ModuleDecoderImpl::DecodeNameSection(), and unibrow::Utf8::ValidateEncoding().
ValidateAndDecodeLocalDeclsForTesting()
V8_EXPORT_PRIVATE bool v8::internal::wasm::ValidateAndDecodeLocalDeclsForTesting (WasmEnabledFeatures enabled, BodyLocalDecls * decls, const WasmModule * module, bool is_shared, const uint8_t * start, const uint8_t * end, Zone * zone)
Definition at line 50 of file function-body-decoder.cc.
                                                                           {
  return DecodeLocalDecls<Decoder::FullValidationTag>(
      enabled, decls, module, is_shared, start, end, zone);
}
References v8::internal::compiler::end(), and v8::internal::is_shared.
ValidateAndSetBuiltinImports()
V8_EXPORT_PRIVATE WasmError v8::internal::wasm::ValidateAndSetBuiltinImports (const WasmModule * module, base::Vector< const uint8_t > wire_bytes, const CompileTimeImports & imports, WasmDetectedFeatures * detected)
Definition at line 1842 of file module-compiler.cc.
                                                                       {
  DCHECK_EQ(module->origin, kWasmOrigin);
  if (imports.empty()) return {};
  static constexpr ValueType kRefExtern = kWasmRefExtern;
  static constexpr ValueType kExternRef = kWasmExternRef;
  static constexpr ValueType kI32 = kWasmI32;
  // Shorthands: "r" = nullable "externref", "e" = non-nullable "ref extern".
  static constexpr ValueType kReps_e_i[] = {kRefExtern, kI32};
  static constexpr ValueType kReps_e_rr[] = {kRefExtern, kExternRef,
                                             kExternRef};
  static constexpr ValueType kReps_e_rii[] = {kRefExtern, kExternRef, kI32,
                                              kI32};
  static constexpr ValueType kReps_i_ri[] = {kI32, kExternRef, kI32};
  static constexpr ValueType kReps_i_rr[] = {kI32, kExternRef, kExternRef};
  static constexpr FunctionSig kSig_e_i(1, 1, kReps_e_i);
  static constexpr FunctionSig kSig_e_r(1, 1, kReps_e_rr);
  static constexpr FunctionSig kSig_e_rr(1, 2, kReps_e_rr);
  static constexpr FunctionSig kSig_e_rii(1, 3, kReps_e_rii);
  static constexpr FunctionSig kSig_i_r(1, 1, kReps_i_ri);
  static constexpr FunctionSig kSig_i_ri(1, 2, kReps_i_ri);
  static constexpr FunctionSig kSig_i_rr(1, 2, kReps_i_rr);
  std::vector<WellKnownImport> statuses;
  statuses.reserve(module->num_imported_functions);
  for (size_t i = 0; i < module->import_table.size(); i++) {
    const WasmImport& import = module->import_table[i];
    // When magic string imports are requested, check that imports with the
    // string constant module name are globals of the right type.
    if (imports.has_string_constants(wire_bytes.SubVector(
            import.module_name.offset(), import.module_name.end_offset()))) {
      if (import.kind != kExternalGlobal ||
          !module->globals[import.index].type.is_reference_to(
              HeapType::kExtern) ||
          module->globals[import.index].mutability != false) {
        TruncatedUserString<> name(
            wire_bytes.data() + import.field_name.offset(),
            import.field_name.length());
        return WasmError(
            ImportStartOffset(wire_bytes, import.module_name.offset()),
            "String constant import #%zu \"%.*s\" must be an immutable global "
            "subtyping externref",
            i, name.length(), name.start());
      }
    }
    // Check compile-time imported functions.
    if (import.kind != kExternalFunction) continue;
    base::Vector<const uint8_t> module_name = wire_bytes.SubVector(
        import.module_name.offset(), import.module_name.end_offset());
    constexpr size_t kMinInterestingLength = 10;
    if (module_name.size() < kMinInterestingLength ||
        module_name.SubVector(0, 5) != base::StaticOneByteVector("wasm:")) {
      statuses.push_back(WellKnownImport::kUninstantiated);
      continue;
    }
    base::Vector<const uint8_t> collection = module_name.SubVectorFrom(5);
    WellKnownImport status = WellKnownImport::kUninstantiated;
    const WasmFunction& func = module->functions[import.index];
    const FunctionSig* sig = func.sig;
    WireBytesRef field_name = import.field_name;
    base::Vector<const uint8_t> name =
        wire_bytes.SubVector(field_name.offset(), field_name.end_offset());
    if (collection == base::StaticOneByteVector("js-string") &&
        imports.contains(CompileTimeImport::kJsString)) {
#define RETURN_ERROR(module_name_string, import_name) \
  uint32_t error_offset = \
      ImportStartOffset(wire_bytes, import.module_name.offset()); \
  return WasmError(error_offset, \
                   "Imported builtin function \"wasm:" module_name_string \
                   "\" \"" import_name "\" has incorrect signature")
#define CHECK_SIG(import_name, kSigName, kEnumName) \
  if (name == base::StaticOneByteVector(#import_name)) { \
    if (*sig != kSigName) { \
      RETURN_ERROR("js-string", #import_name); \
    } \
    status = WellKnownImport::kEnumName; \
    detected->add_imported_strings(); \
  } else // NOLINT(readability/braces)
      CHECK_SIG(cast, kSig_e_r, kStringCast)
      CHECK_SIG(test, kSig_i_r, kStringTest)
      CHECK_SIG(fromCharCode, kSig_e_i, kStringFromCharCode)
      CHECK_SIG(fromCodePoint, kSig_e_i, kStringFromCodePoint)
      CHECK_SIG(charCodeAt, kSig_i_ri, kStringCharCodeAt)
      CHECK_SIG(codePointAt, kSig_i_ri, kStringCodePointAt)
      CHECK_SIG(length, kSig_i_r, kStringLength)
      CHECK_SIG(concat, kSig_e_rr, kStringConcat)
      CHECK_SIG(substring, kSig_e_rii, kStringSubstring)
      CHECK_SIG(equals, kSig_i_rr, kStringEquals)
      CHECK_SIG(compare, kSig_i_rr, kStringCompare)
      if (name == base::StaticOneByteVector("fromCharCodeArray")) {
        if (sig->parameter_count() != 3 || sig->return_count() != 1 ||
            !IsI16Array(sig->GetParam(0), module) || // --
            sig->GetParam(1) != kI32 || // --
            sig->GetParam(2) != kI32 || // --
            sig->GetReturn() != kRefExtern) {
          RETURN_ERROR("js-string", "fromCharCodeArray");
        }
        detected->add_imported_strings();
        status = WellKnownImport::kStringFromWtf16Array;
      } else if (name == base::StaticOneByteVector("intoCharCodeArray")) {
        if (sig->parameter_count() != 3 || sig->return_count() != 1 ||
            sig->GetParam(0) != kExternRef ||
            !IsI16Array(sig->GetParam(1), module) || // --
            sig->GetParam(2) != kI32 || // --
            sig->GetReturn() != kI32) {
          RETURN_ERROR("js-string", "intoCharCodeArray");
        }
        status = WellKnownImport::kStringToWtf16Array;
        detected->add_imported_strings();
      }
#undef CHECK_SIG
    } else if (collection == base::StaticOneByteVector("text-encoder") &&
               imports.contains(CompileTimeImport::kTextEncoder)) {
      if (name == base::StaticOneByteVector("measureStringAsUTF8")) {
        if (*sig != kSig_i_r) {
          RETURN_ERROR("text-encoder", "measureStringAsUTF8");
        }
        status = WellKnownImport::kStringMeasureUtf8;
        detected->add_imported_strings_utf8();
      } else if (name ==
                 base::StaticOneByteVector("encodeStringIntoUTF8Array")) {
        if (sig->parameter_count() != 3 || sig->return_count() != 1 ||
            sig->GetParam(0) != kExternRef || // --
            !IsI8Array(sig->GetParam(1), module, true) || // --
            sig->GetParam(2) != kI32 || // --
            sig->GetReturn() != kI32) {
          RETURN_ERROR("text-encoder", "encodeStringIntoUTF8Array");
        }
        status = WellKnownImport::kStringIntoUtf8Array;
        detected->add_imported_strings_utf8();
      } else if (name == base::StaticOneByteVector("encodeStringToUTF8Array")) {
        if (sig->parameter_count() != 1 || sig->return_count() != 1 ||
            sig->GetParam(0) != kExternRef ||
            !IsI8Array(sig->GetReturn(), module, false)) {
          RETURN_ERROR("text-encoder", "encodeStringToUTF8Array");
        }
        status = WellKnownImport::kStringToUtf8Array;
        detected->add_imported_strings_utf8();
      }
    } else if (collection == base::StaticOneByteVector("text-decoder") &&
               imports.contains(CompileTimeImport::kTextDecoder)) {
      if (name == base::StaticOneByteVector("decodeStringFromUTF8Array")) {
        if (sig->parameter_count() != 3 || sig->return_count() != 1 ||
            !IsI8Array(sig->GetParam(0), module, true) || // --
            sig->GetParam(1) != kI32 || // --
            sig->GetParam(2) != kI32 || // --
            sig->GetReturn() != kRefExtern) {
          RETURN_ERROR("text-decoder", "decodeStringFromUTF8Array");
        }
        status = WellKnownImport::kStringFromUtf8Array;
        detected->add_imported_strings_utf8();
      }
    }
#undef RETURN_ERROR
    statuses.push_back(status);
  }
  // We're operating on a fresh WasmModule instance here, so we don't need to
  // check for incompatibilities with previously seen imports.
  DCHECK_EQ(module->num_imported_functions, statuses.size());
  // The "Initialize" call is currently only safe when the decoder has allocated
  // storage, which it allocates when there is an imports section.
  if (module->num_imported_functions != 0) {
    module->type_feedback.well_known_imports.Initialize(
        base::VectorOf(statuses));
  }
  return {};
}
References CHECK_SIG, v8::internal::wasm::CompileTimeImports::contains(), v8::base::Vector< T >::data(), DCHECK_EQ, v8::internal::wasm::CompileTimeImports::empty(), v8::internal::wasm::WireBytesRef::end_offset(), v8::internal::wasm::WasmModule::functions, v8::internal::wasm::WasmModule::globals, v8::internal::wasm::CompileTimeImports::has_string_constants(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::WasmModule::import_table, v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ImportStartOffset(), v8::internal::wasm::WellKnownImportsList::Initialize(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::IsI16Array(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::IsI8Array(), v8::internal::wasm::HeapType::kExtern, kExternalFunction, kExternalGlobal, v8::internal::kI32, kJsString, kStringCast, kStringCharCodeAt, kStringCodePointAt, kStringCompare, kStringEquals, kStringFromCharCode, kStringFromCodePoint, kStringFromUtf8Array, kStringFromWtf16Array, kStringIntoUtf8Array, kStringLength, kStringMeasureUtf8, kStringSubstring, kStringTest, kStringToUtf8Array, kStringToWtf16Array, kTextDecoder, kTextEncoder, kUninstantiated, kWasmExternRef, kWasmI32, kWasmOrigin, kWasmRefExtern, v8::internal::length, name(), v8::internal::wasm::WasmModule::num_imported_functions, v8::internal::wasm::WireBytesRef::offset(), v8::internal::wasm::WasmModule::origin, RETURN_ERROR, v8::internal::wasm::WasmFunction::sig, v8::internal::sig, v8::base::Vector< T >::size(), v8::base::StaticOneByteVector(), v8::internal::status, v8::base::Vector< T >::SubVector(), v8::base::Vector< T >::SubVectorFrom(), v8::internal::wasm::WasmModule::type_feedback, v8::base::VectorOf(), and v8::internal::wasm::TypeFeedbackStorage::well_known_imports.
Referenced by v8::internal::wasm::AsyncCompileJob::Failed(), v8::internal::wasm::AsyncStreamingProcessor::OnFinishedStream(), v8::internal::wasm::AsyncCompileJob::DecodeModule::RunInBackground(), v8::internal::wasm::WasmEngine::SyncCompile(), and v8::internal::wasm::WasmEngine::SyncValidate().
ValidateFunctionBody()
V8_EXPORT_PRIVATE DecodeResult v8::internal::wasm::ValidateFunctionBody (Zone * zone, WasmEnabledFeatures enabled, const WasmModule * module, WasmDetectedFeatures * detected, const FunctionBody & body)
Definition at line 72 of file function-body-decoder.cc.
                                                            {
  // Asm.js functions should never be validated; they are valid by design.
  DCHECK_EQ(kWasmOrigin, module->origin);
  WasmFullDecoder<Decoder::FullValidationTag, EmptyInterface> decoder(
      zone, module, enabled, detected, body);
  decoder.Decode();
  return decoder.toResult(nullptr);
}
References DCHECK_EQ, v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Decode(), kWasmOrigin, v8::internal::wasm::WasmModule::origin, and v8::internal::wasm::Decoder::toResult().
Referenced by v8::internal::wasm::ModuleDecoderImpl::DecodeSingleFunctionForTesting(), v8::internal::wasm::WasmCompilationUnit::ExecuteCompilation(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineWasmCall(), v8::internal::wasm::DebugInfoImpl::RecompileLiftoffWithBreakpoints(), v8::internal::compiler::WasmGraphBuilder::TryWasmInlining(), v8::internal::wasm::anonymous_namespace{module-decoder.cc}::ValidateFunctionsTask::ValidateFunction(), v8::internal::anonymous_namespace{runtime-test-wasm.cc}::ValidateFunctionNowIfNeeded(), and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ValidateSingleFunction().
ValidateFunctions()
V8_EXPORT_PRIVATE WasmError v8::internal::wasm::ValidateFunctions (const WasmModule * module, WasmEnabledFeatures enabled_features, base::Vector< const uint8_t > wire_bytes, std::function< bool(int)> filter, WasmDetectedFeatures * detected_features_out)
Definition at line 621 of file module-decoder.cc.
                                                                         {
  TRACE_EVENT2(TRACE_DISABLED_BY_DEFAULT("v8.wasm.detailed"),
               "wasm.ValidateFunctions", "num_declared_functions",
               module->num_declared_functions, "has_filter", filter != nullptr);
  DCHECK_EQ(kWasmOrigin, module->origin);
  class NeverYieldDelegate final : public JobDelegate {
   public:
    bool ShouldYield() override { return false; }
    bool IsJoiningThread() const override { UNIMPLEMENTED(); }
    void NotifyConcurrencyIncrease() override { UNIMPLEMENTED(); }
    uint8_t GetTaskId() override { UNIMPLEMENTED(); }
  };
  // Create a {ValidateFunctionsTask} to validate all functions. The earliest
  // error found will be set on this decoder.
  WasmError validation_error;
  std::atomic<WasmDetectedFeatures> detected_features;
  std::unique_ptr<JobTask> validate_job =
      std::make_unique<ValidateFunctionsTask>(
          wire_bytes, module, enabled_features, std::move(filter),
          &validation_error, &detected_features);
  if (v8_flags.single_threaded) {
    // In single-threaded mode, run the {ValidateFunctionsTask} synchronously.
    NeverYieldDelegate delegate;
    validate_job->Run(&delegate);
  } else {
    // Spawn the task and join it.
    std::unique_ptr<JobHandle> job_handle = V8::GetCurrentPlatform()->CreateJob(
        TaskPriority::kUserVisible, std::move(validate_job));
    job_handle->Join();
  }
  *detected_features_out |= detected_features.load(std::memory_order_relaxed);
  return validation_error;
}
References v8::Platform::CreateJob(), DCHECK_EQ, v8::internal::V8::GetCurrentPlatform(), v8::kUserVisible, kWasmOrigin, v8::internal::wasm::WasmModule::num_declared_functions, v8::internal::wasm::WasmModule::origin, TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT2, v8::internal::UNIMPLEMENTED(), and v8::internal::v8_flags.
Referenced by v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompileNativeModule(), v8::internal::wasm::ModuleDecoderImpl::DecodeModule(), v8::internal::wasm::AsyncCompileJob::DecodeModule::RunInBackground(), v8::internal::wasm::AsyncCompileJob::PrepareAndStartCompile::RunInForeground(), and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ValidateFunctions().
ValidSubtypeDefinition()
V8_EXPORT_PRIVATE bool v8::internal::wasm::ValidSubtypeDefinition (ModuleTypeIndex subtype_index, ModuleTypeIndex supertype_index, const WasmModule * module)
Definition at line 372 of file wasm-subtyping.cc.
                                                      {
  const TypeDefinition& subtype = module->type(subtype_index);
  const TypeDefinition& supertype = module->type(supertype_index);
  if (subtype.kind != supertype.kind) return false;
  if (supertype.is_final) return false;
  if (subtype.is_shared != supertype.is_shared) return false;
  switch (subtype.kind) {
    case TypeDefinition::kFunction:
      return ValidFunctionSubtypeDefinition(subtype_index, supertype_index,
                                            module);
    case TypeDefinition::kStruct:
      return ValidStructSubtypeDefinition(subtype_index, supertype_index,
                                          module);
    case TypeDefinition::kArray:
      return ValidArraySubtypeDefinition(subtype_index, supertype_index,
                                         module);
    case TypeDefinition::kCont:
      return ValidContinuationSubtypeDefinition(subtype_index, supertype_index,
                                                module);
  }
}
References v8::internal::wasm::TypeDefinition::is_final, v8::internal::wasm::TypeDefinition::is_shared, v8::internal::wasm::TypeDefinition::kArray, v8::internal::wasm::TypeDefinition::kCont, v8::internal::wasm::TypeDefinition::kFunction, v8::internal::wasm::TypeDefinition::kind, v8::internal::wasm::TypeDefinition::kStruct, v8::internal::wasm::WasmModule::type(), v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::ValidArraySubtypeDefinition(), v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::ValidContinuationSubtypeDefinition(), v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::ValidFunctionSubtypeDefinition(), and v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::ValidStructSubtypeDefinition().
Referenced by v8::internal::wasm::ModuleDecoderImpl::FinalizeRecgroup().
value_kind_full_size()
constexpr int v8::internal::wasm::value_kind_full_size (ValueKind kind) [constexpr]
Definition at line 1187 of file value-type.h.
                                                   {
  if (is_reference(kind)) {
    // Uncompressed pointer size.
    return kSystemPointerSize;
  }
  return value_kind_size(kind);
}
References is_reference(), v8::internal::kSystemPointerSize, and value_kind_size().
value_kind_size()
constexpr int v8::internal::wasm::value_kind_size (ValueKind kind) [constexpr]
Definition at line 1174 of file value-type.h.
                                              {
  constexpr int8_t kElementSize[] = {
#define ELEM_SIZE_LOG2(kind, log2Size, ...) \
  log2Size == -1 ? -1 : (1 << std::max(0, log2Size)),
      FOREACH_VALUE_TYPE(ELEM_SIZE_LOG2)
#undef ELEM_SIZE_LOG2
  };
  int size = kElementSize[kind];
  DCHECK_LT(0, size);
  return size;
}
References DCHECK_LT, ELEM_SIZE_LOG2, FOREACH_VALUE_TYPE, and size().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayFillImpl(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayNew(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayNewFixed(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::AtomicWait(), v8::internal::wasm::LiftoffAssembler::CallCWithStackBuffer(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GenerateCCallWithStackBuffer(), v8::internal::wasm::Handlers< Compressed >::s2s_ArrayNew(), v8::internal::wasm::Handlers< Compressed >::s2s_ArrayNewDefault(), v8::internal::wasm::Handlers< Compressed >::s2s_ArrayNewFixed(), v8::internal::wasm::Handlers< Compressed >::s2s_RefArrayNew(), v8::internal::wasm::LiftoffAssembler::SlotSizeForType(), v8::internal::wasm::liftoff::StoreToMemory(), v8::internal::wasm::ParallelMove::TransferToStack(), and value_kind_full_size().
value_kind_size_log2()
constexpr int v8::internal::wasm::value_kind_size_log2 (ValueKind kind) [constexpr]
Definition at line 1162 of file value-type.h.
                                                   {
  constexpr int8_t kValueKindSizeLog2[] = {
#define VALUE_KIND_SIZE_LOG2(kind, log2Size, ...) log2Size,
      FOREACH_VALUE_TYPE(VALUE_KIND_SIZE_LOG2)
#undef VALUE_KIND_SIZE_LOG2
  };
  int size_log_2 = kValueKindSizeLog2[kind];
  DCHECK_LE(0, size_log_2);
  return size_log_2;
}
References DCHECK_LE, FOREACH_VALUE_TYPE, and VALUE_KIND_SIZE_LOG2.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayAtomicCompareExchange(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayAtomicGet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayAtomicRMW(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayAtomicSet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayFillImpl(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayGet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayNewFixed(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArraySet().
value_type()
template<typename T >
static ValueType v8::internal::wasm::value_type () [inline], [static]
Definition at line 1180 of file wasm-interpreter.h.
                                     {
  UNREACHABLE();
}
References v8::internal::UNREACHABLE().
Referenced by v8::internal::wasm::WasmBytecodeGenerator::_PushSlot(), v8::internal::wasm::TypeCanonicalizer::CanonicalHashing::Add(), v8::internal::AddressToTraceMap::AddRange(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_get_helper(), v8::internal::maglev::MaglevGraphBuilder::BuildToBoolean(), v8::internal::maglev::MaglevAssembler::CheckAndEmitDeferredWriteBarrier(), v8::internal::compiler::turboshaft::GenericAssemblerOpInterface< Assembler >::ControlFlowHelper_Foreach(), v8::internal::wasm::WasmBytecodeGenerator::CopyToSlot(), v8::internal::wasm::WasmBytecodeGenerator::CopyToSlotAndPop(), v8::internal::wasm::WasmBytecodeGenerator::CreateSlot(), v8::internal::wasm::WasmBytecodeGenerator::CreateWasmRefSlot(), v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction(), v8::internal::wasm::WasmBytecodeGenerator::EmitCopySlot(), v8::internal::CodeEntry::EstimatedSize(), v8::internal::torque::FileUriDecode(), v8::internal::wasm::WasmBytecodeGenerator::FindSharedSlot(), v8::internal::wasm::WasmBytecodeGenerator::InitSlotsForFunctionArgs(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::IsDataViewSetterSig(), v8::internal::HandlerTable::LookupReturn(), v8::internal::wasm::WasmBytecodeGenerator::PreserveArgsAndLocals(), v8::internal::ValueDeserializer::ReadJSObjectProperties(), v8::internal::compiler::TypedOptimization::ReduceConvertReceiver(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateArray(), v8::internal::compiler::JSTypedLowering::ReduceJSHasInPrototypeChain(), v8::internal::compiler::JSTypedLowering::ReduceJSParseInt(), v8::internal::compiler::JSTypedLowering::ReduceObjectIsArray(), v8::internal::wasm::WasmBytecodeGenerator::RefPop(), v8::internal::AddressToTraceMap::RemoveRange(), v8::internal::wasm::WasmBytecodeGenerator::ReserveBlockSlots(), v8::internal::RUNTIME_FUNCTION(), v8::internal::wasm::Handlers< Compressed >::s2s_StructNewDefault(), v8::internal::SourcePositionTable::Size(), v8::internal::wasm::StackPool::Size(), v8::internal::wasm::WasmBytecodeGenerator::StoreBlockParamsIntoSlots(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::struct_get_helper(), v8::internal::compiler::SimplifiedOperatorBuilder::TransitionAndStoreNonNumberElement(), v8::internal::compiler::WasmLoadElimination::TruncateAndExtendOrType(), v8::internal::JSDataObjectBuilder::TryGeneralizeFieldToValue(), v8::internal::wasm::WasmBytecodeGenerator::UpdateStack(), v8::internal::compiler::RepresentationSelector::VisitNode(), v8::internal::wasm::WasmInterpreterRuntime::WasmJSToWasmObject(), and v8::internal::compiler::RepresentationSelector::WriteBarrierKindFor().
value_type< double >()
template<>
ValueType v8::internal::wasm::value_type< double > () [inline]
Definition at line 1204 of file wasm-interpreter.h.
                                      {
  return kWasmF64;
}
References kWasmF64.
value_type< float >()
template<>
ValueType v8::internal::wasm::value_type< float > () [inline]
Definition at line 1200 of file wasm-interpreter.h.
                                     {
  return kWasmF32;
}
References kWasmF32.
value_type< int32_t >()
template<>
ValueType v8::internal::wasm::value_type< int32_t > () [inline]
Definition at line 1184 of file wasm-interpreter.h.
                                       {
  return kWasmI32;
}
References kWasmI32.
value_type< int64_t >()
template<>
ValueType v8::internal::wasm::value_type< int64_t > () [inline]
Definition at line 1192 of file wasm-interpreter.h.
                                       {
  return kWasmI64;
}
References kWasmI64.
value_type< Simd128 >()
template<>
ValueType v8::internal::wasm::value_type< Simd128 > () [inline]
Definition at line 1208 of file wasm-interpreter.h.
                                       {
  return kWasmS128;
}
References kWasmS128.
value_type< uint32_t >()
template<>
ValueType v8::internal::wasm::value_type< uint32_t > () [inline]
Definition at line 1188 of file wasm-interpreter.h.
                                        {
  return kWasmI32;
}
References kWasmI32.
value_type< uint64_t >()
template<>
ValueType v8::internal::wasm::value_type< uint64_t > () [inline]
Definition at line 1196 of file wasm-interpreter.h.
                                        {
  return kWasmI64;
}
References kWasmI64.
value_type< WasmRef >()
template<>
ValueType v8::internal::wasm::value_type< WasmRef > () [inline]
Definition at line 1212 of file wasm-interpreter.h.
                                       {
  return kWasmAnyRef; // TODO(paolosev@microsoft.com)
}
References kWasmAnyRef.
void()
typedef v8::internal::wasm::void (VECTORCALL PWasmOp) const
Referenced by v8::internal::wasm::LiftoffAssembler::AtomicCompareExchange(), v8::FuzzerMonitor::ControlFlowViolation(), v8::bigint::anonymous_namespace{div-burnikel.cc}::BZ::D3n2n(), cppgc::internal::EnsureGCInfoIndex(), v8::base::internal::CheckOnFailure::HandleFailure(), v8::internal::TracedHandles::ProcessWeakYoungObjects(), v8::internal::tracing::TraceID::TraceID(), v8::internal::compiler::LinearScanAllocator::UpdateDeferredFixedRanges(), and v8::internal::WritableJitAllocation::WritableJitAllocation().
WasmReturnTypeFromSignature()
std::optional< wasm::ValueKind > v8::internal::wasm::WasmReturnTypeFromSignature (const CanonicalSig * wasm_signature)
Definition at line 163 of file value-type.cc.
                                        {
  if (wasm_signature->return_count() == 0) return {};
  DCHECK_EQ(wasm_signature->return_count(), 1);
  CanonicalValueType return_type = wasm_signature->GetReturn(0);
  return {return_type.kind()};
}
References DCHECK_EQ, v8::internal::Signature< T >::GetReturn(), v8::internal::wasm::ValueTypeBase::kind(), and v8::internal::Signature< T >::return_count().
WasmToJSObject()
DirectHandle< Object > v8::internal::wasm::WasmToJSObject (Isolate * isolate, DirectHandle< Object > value)
Definition at line 3639 of file wasm-objects.cc.
                                                                {
  if (IsWasmNull(*value)) {
    return isolate->factory()->null_value();
  } else if (IsWasmFuncRef(*value)) {
    return i::WasmInternalFunction::GetOrCreateExternal(i::direct_handle(
        i::Cast<i::WasmFuncRef>(*value)->internal(isolate), isolate));
  } else {
    return value;
  }
}
References v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::WasmInternalFunction::GetOrCreateExternal(), and v8::internal::value.
Referenced by v8::internal::RUNTIME_FUNCTION(), and v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::WasmObjectToJSReturnValue().
WellKnownImportName()
const char * v8::internal::wasm::WellKnownImportName (WellKnownImport wki)
Definition at line 9 of file well-known-imports.cc.
                                                     {
  switch (wki) {
    // Generic:
    case WellKnownImport::kUninstantiated:
      return "uninstantiated";
    case WellKnownImport::kGeneric:
      return "generic";
    case WellKnownImport::kLinkError:
      return "LinkError";
    // DataView methods:
    case WellKnownImport::kDataViewGetBigInt64:
      return "DataView.getBigInt64";
    case WellKnownImport::kDataViewGetBigUint64:
      return "DataView.getBigUint64";
    case WellKnownImport::kDataViewGetFloat32:
      return "DataView.getFloat32";
    case WellKnownImport::kDataViewGetFloat64:
      return "DataView.getFloat64";
    case WellKnownImport::kDataViewGetInt8:
      return "DataView.getInt8";
    case WellKnownImport::kDataViewGetInt16:
      return "DataView.getInt16";
    case WellKnownImport::kDataViewGetInt32:
      return "DataView.getInt32";
    case WellKnownImport::kDataViewGetUint8:
      return "DataView.getUint8";
    case WellKnownImport::kDataViewGetUint16:
      return "DataView.getUint16";
    case WellKnownImport::kDataViewGetUint32:
      return "DataView.getUint32";
    case WellKnownImport::kDataViewSetBigInt64:
      return "DataView.setBigInt64";
    case WellKnownImport::kDataViewSetBigUint64:
      return "DataView.setBigUint64";
    case WellKnownImport::kDataViewSetFloat32:
      return "DataView.setFloat32";
    case WellKnownImport::kDataViewSetFloat64:
      return "DataView.setFloat64";
    case WellKnownImport::kDataViewSetInt8:
      return "DataView.setInt8";
    case WellKnownImport::kDataViewSetInt16:
      return "DataView.setInt16";
    case WellKnownImport::kDataViewSetInt32:
      return "DataView.setInt32";
    case WellKnownImport::kDataViewSetUint8:
      return "DataView.setUint8";
    case WellKnownImport::kDataViewSetUint16:
      return "DataView.setUint16";
    case WellKnownImport::kDataViewSetUint32:
      return "DataView.setUint32";
    case WellKnownImport::kDataViewByteLength:
      return "DataView.byteLength";
      // Math functions.
    case WellKnownImport::kMathF64Acos:
      return "Math.acos";
    case WellKnownImport::kMathF64Asin:
      return "Math.asin";
    case WellKnownImport::kMathF64Atan:
      return "Math.atan";
    case WellKnownImport::kMathF64Atan2:
      return "Math.atan2";
    case WellKnownImport::kMathF64Cos:
      return "Math.cos";
    case WellKnownImport::kMathF64Sin:
      return "Math.sin";
    case WellKnownImport::kMathF64Tan:
      return "Math.tan";
    case WellKnownImport::kMathF64Exp:
      return "Math.exp";
    case WellKnownImport::kMathF64Log:
      return "Math.log";
    case WellKnownImport::kMathF64Pow:
      return "Math.pow";
    case WellKnownImport::kMathF64Sqrt:
      return "Math.sqrt";
      // String-related functions:
    case WellKnownImport::kDoubleToString:
      return "DoubleToString";
    case WellKnownImport::kIntToString:
      return "IntToString";
    case WellKnownImport::kParseFloat:
      return "ParseFloat";
    case WellKnownImport::kStringIndexOf:
    case WellKnownImport::kStringIndexOfImported:
      return "String.indexOf";
    case WellKnownImport::kStringToLocaleLowerCaseStringref:
      return "String.toLocaleLowerCase";
    case WellKnownImport::kStringToLowerCaseStringref:
    case WellKnownImport::kStringToLowerCaseImported:
      return "String.toLowerCase";
      // JS String Builtins:
    case WellKnownImport::kStringCast:
      return "js-string:cast";
    case WellKnownImport::kStringCharCodeAt:
      return "js-string:charCodeAt";
    case WellKnownImport::kStringCodePointAt:
      return "js-string:codePointAt";
    case WellKnownImport::kStringCompare:
      return "js-string:compare";
    case WellKnownImport::kStringConcat:
      return "js-string:concat";
    case WellKnownImport::kStringEquals:
      return "js-string:equals";
    case WellKnownImport::kStringFromCharCode:
      return "js-string:fromCharCode";
    case WellKnownImport::kStringFromCodePoint:
      return "js-string:fromCodePoint";
    case WellKnownImport::kStringFromUtf8Array:
      return "text-decoder:decodeStringFromUTF8Array";
    case WellKnownImport::kStringFromWtf16Array:
      return "js-string:fromCharCodeArray";
    case WellKnownImport::kStringIntoUtf8Array:
      return "text-encoder:encodeStringIntoUTF8Array";
    case WellKnownImport::kStringToUtf8Array:
      return "text-encoder:encodeStringToUTF8Array";
    case WellKnownImport::kStringLength:
      return "js-string:length";
    case WellKnownImport::kStringMeasureUtf8:
      return "text-encoder:measureStringAsUTF8";
    case WellKnownImport::kStringSubstring:
      return "js-string:substring";
    case WellKnownImport::kStringTest:
      return "js-string:test";
    case WellKnownImport::kStringToWtf16Array:
      return "js-string:intoCharCodeArray";
      // Fast API Call:
    case WellKnownImport::kFastAPICall:
      return "fast API call";
  }
}
References kDataViewByteLength, kDataViewGetBigInt64, kDataViewGetBigUint64, kDataViewGetFloat32, kDataViewGetFloat64, kDataViewGetInt16, kDataViewGetInt32, kDataViewGetInt8, kDataViewGetUint16, kDataViewGetUint32, kDataViewGetUint8, kDataViewSetBigInt64, kDataViewSetBigUint64, kDataViewSetFloat32, kDataViewSetFloat64, kDataViewSetInt16, kDataViewSetInt32, kDataViewSetInt8, kDataViewSetUint16, kDataViewSetUint32, kDataViewSetUint8, kDoubleToString, kFastAPICall, kGeneric, kIntToString, kLinkError, kMathF64Acos, kMathF64Asin, kMathF64Atan, kMathF64Atan2, kMathF64Cos, kMathF64Exp, kMathF64Log, kMathF64Pow, kMathF64Sin, kMathF64Sqrt, kMathF64Tan, kParseFloat, kStringCast, kStringCharCodeAt, kStringCodePointAt, kStringCompare, kStringConcat, kStringEquals, kStringFromCharCode, kStringFromCodePoint, kStringFromUtf8Array, kStringFromWtf16Array, kStringIndexOf, kStringIndexOfImported, kStringIntoUtf8Array, kStringLength, kStringMeasureUtf8, kStringSubstring, kStringTest, kStringToLocaleLowerCaseStringref, kStringToLowerCaseImported, kStringToLowerCaseStringref, kStringToUtf8Array, kStringToWtf16Array, and kUninstantiated.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::HandleWellKnownImport(), and v8::internal::wasm::InstanceBuilder::ProcessImportedFunction().
word32_rol_wrapper()
V8_EXPORT_PRIVATE uint32_t v8::internal::wasm::word32_rol_wrapper (uint32_t input, uint32_t shift)
Definition at line 346 of file wasm-external-refs.cc.
                                                            {
  return (input << (shift & 31)) | (input >> ((32 - shift) & 31));
}
word32_ror_wrapper()
V8_EXPORT_PRIVATE uint32_t v8::internal::wasm::word32_ror_wrapper (uint32_t input, uint32_t shift)
Definition at line 350 of file wasm-external-refs.cc.
                                                            {
  return (input >> (shift & 31)) | (input << ((32 - shift) & 31));
}
word64_rol_wrapper()
V8_EXPORT_PRIVATE uint64_t v8::internal::wasm::word64_rol_wrapper (uint64_t input, uint32_t shift)
Definition at line 354 of file wasm-external-refs.cc.
                                                            {
  return (input << (shift & 63)) | (input >> ((64 - shift) & 63));
}
word64_ror_wrapper()
V8_EXPORT_PRIVATE uint64_t v8::internal::wasm::word64_ror_wrapper (uint64_t input, uint32_t shift)
Definition at line 358 of file wasm-external-refs.cc.
                                                            {
  return (input >> (shift & 63)) | (input << ((64 - shift) & 63));
}
Variable Documentation
invalid_instruction_trace
const std::pair<uint32_t, uint32_t> v8::internal::wasm::invalid_instruction_trace = {0, 0}
Definition at line 1617 of file function-body-decoder-impl.h.
Referenced by v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::WasmDecoder().
is_be
constexpr bool v8::internal::wasm::is_be = false [constexpr]
Definition at line 774 of file liftoff-assembler-ppc-inl.h.
kAfterMaxLiftoffFpRegCode
constexpr int v8::internal::wasm::kAfterMaxLiftoffFpRegCode [static], [constexpr]
Initial value:
=
    kAfterMaxLiftoffGpRegCode + kMaxFpRegCode + 1
Definition at line 127 of file liftoff-register.h.
Referenced by v8::internal::wasm::LiftoffRegister::is_fp().
kAfterMaxLiftoffGpRegCode
constexpr int v8::internal::wasm::kAfterMaxLiftoffGpRegCode = kMaxGpRegCode + 1 [static], [constexpr]
Definition at line 126 of file liftoff-register.h.
Referenced by v8::internal::wasm::LiftoffRegister::fp(), v8::internal::wasm::LiftoffRegList::GetFpList(), v8::internal::wasm::LiftoffRegister::is_fp(), and v8::internal::wasm::LiftoffRegister::is_gp().
kAfterMaxLiftoffRegCode
constexpr int v8::internal::wasm::kAfterMaxLiftoffRegCode = kAfterMaxLiftoffFpRegCode [static], [constexpr]
Definition at line 129 of file liftoff-register.h.
kAnonymousFuncIndex
constexpr int v8::internal::wasm::kAnonymousFuncIndex = -1 [constexpr]
Definition at line 189 of file wasm-constants.h.
Referenced by v8::internal::wasm::NativeModule::AddCodeForTesting(), v8::internal::wasm::WasmImportWrapperCache::ModificationScope::AddWrapper(), v8::internal::wasm::NativeModule::CreateEmptyJumpTableInRegionLocked(), v8::internal::wasm::NativeModule::GetCodePointerHandle(), v8::internal::WasmModuleObject::GetRawFunctionName(), and v8::internal::wasm::WasmCode::IsAnonymous().
kBitsPerFpRegCode
constexpr int v8::internal::wasm::kBitsPerFpRegCode [static], [constexpr]
Initial value:
=
    32 - base::bits::CountLeadingZeros<uint32_t>(kMaxFpRegCode)
Definition at line 134 of file liftoff-register.h.
Referenced by v8::internal::wasm::LiftoffRegister::high_fp(), and v8::internal::wasm::LiftoffRegister::low_fp().
kBitsPerGpRegCode
constexpr int v8::internal::wasm::kBitsPerGpRegCode [static], [constexpr]
Initial value:
=
    32 - base::bits::CountLeadingZeros<uint32_t>(kMaxGpRegCode)
Definition at line 132 of file liftoff-register.h.
Referenced by v8::internal::wasm::LiftoffRegister::ForFpPair(), v8::internal::wasm::LiftoffRegister::ForPair(), v8::internal::wasm::LiftoffRegister::high_gp(), v8::internal::wasm::LiftoffRegister::is_fp_pair(), v8::internal::wasm::LiftoffRegister::is_gp_pair(), v8::internal::wasm::LiftoffRegister::is_pair(), and v8::internal::wasm::LiftoffRegister::low_gp().
kBitsPerLiftoffRegCode
constexpr int v8::internal::wasm::kBitsPerLiftoffRegCode [static], [constexpr]
Initial value:
=
    32 - base::bits::CountLeadingZeros<uint32_t>(kAfterMaxLiftoffRegCode - 1)
Definition at line 130 of file liftoff-register.h.
kBitsPerRegPair
constexpr int v8::internal::wasm::kBitsPerRegPair [static], [constexpr]
Initial value:
=
    (kNeedS128RegPair ? 2 : 1) + 2 * kBitsPerGpRegCode
Definition at line 137 of file liftoff-register.h.
kBranchHintsString
constexpr char v8::internal::wasm::kBranchHintsString[] = `metadata.code.branch_hint` [constexpr]
Definition at line 35 of file module-decoder-impl.h.
Referenced by IdentifyUnknownSectionInternal(), and SectionName().
kBranchOnCastDataTargetTypeBitSize
constexpr uint32_t v8::internal::wasm::kBranchOnCastDataTargetTypeBitSize = 30 [constexpr]
Definition at line 1062 of file wasm-interpreter.h.
Referenced by v8::internal::wasm::WasmBytecodeGenerator::DecodeGCOp().
kBuildIdString
constexpr char v8::internal::wasm::kBuildIdString[] = `build_id` [constexpr]
Definition at line 38 of file module-decoder-impl.h.
Referenced by IdentifyUnknownSectionInternal(), and SectionName().
kCodeOffsetSize
const ptrdiff_t v8::internal::wasm::kCodeOffsetSize = sizeof(int32_t) [static]
Definition at line 1053 of file wasm-interpreter.h.
Referenced by v8::internal::wasm::Handlers< Compressed >::r2s_BranchIf(), v8::internal::wasm::Handlers< Compressed >::r2s_BranchIfWithParams(), v8::internal::wasm::Handlers< Compressed >::r2s_BrTable(), v8::internal::wasm::Handlers< Compressed >::r2s_If(), v8::internal::wasm::Handlers< Compressed >::s2s_Branch(), v8::internal::wasm::Handlers< Compressed >::s2s_BranchIf(), v8::internal::wasm::Handlers< Compressed >::s2s_BranchIfWithParams(), v8::internal::wasm::Handlers< Compressed >::s2s_BranchOnCast(), v8::internal::wasm::Handlers< Compressed >::s2s_BranchOnCastFail(), v8::internal::wasm::Handlers< Compressed >::s2s_BranchOnNonNull(), v8::internal::wasm::Handlers< Compressed >::s2s_BranchOnNonNullWithParams(), v8::internal::wasm::Handlers< Compressed >::s2s_BranchOnNull(), v8::internal::wasm::Handlers< Compressed >::s2s_BranchOnNullWithParams(), v8::internal::wasm::Handlers< Compressed >::s2s_BrTable(), v8::internal::wasm::Handlers< Compressed >::s2s_Catch(), v8::internal::wasm::Handlers< Compressed >::s2s_Else(), and v8::internal::wasm::Handlers< Compressed >::s2s_If().
kCompilationHintsString
constexpr char v8::internal::wasm::kCompilationHintsString[] = `compilationHints` [constexpr]
Definition at line 34 of file module-decoder-impl.h.
Referenced by IdentifyUnknownSectionInternal(), and SectionName().
kConstructorFunctionContextLength
constexpr int v8::internal::wasm::kConstructorFunctionContextLength [static], [constexpr]
Initial value:
=
    kConstructorFunctionContextSlot + 1
Definition at line 109 of file wasm-objects.h.
Referenced by v8::internal::wasm::JSPrototypesSetup::MakeConstructor().
kConstructorFunctionContextSlot
constexpr int v8::internal::wasm::kConstructorFunctionContextSlot [static], [constexpr]
Initial value:
=
    Context::MIN_CONTEXT_SLOTS
Definition at line 107 of file wasm-objects.h.
Referenced by v8::internal::wasm::JSPrototypesSetup::MakeConstructor(), and v8::internal::TF_BUILTIN().
kDebugInfoString
constexpr char v8::internal::wasm::kDebugInfoString[] = `.debug_info` [constexpr]
Definition at line 36 of file module-decoder-impl.h.
Referenced by IdentifyUnknownSectionInternal(), and SectionName().
kDefaultCompilationHint
constexpr uint8_t v8::internal::wasm::kDefaultCompilationHint = 0x0 [constexpr]
Definition at line 143 of file wasm-constants.h.
Referenced by v8::internal::wasm::WasmModuleBuilder::WriteTo().
kDefaultImportCallKind
constexpr ImportCallKind v8::internal::wasm::kDefaultImportCallKind = ImportCallKind::kJSFunction [constexpr]
Definition at line 54 of file module-instantiate.h.
kDescriptorsString
constexpr char v8::internal::wasm::kDescriptorsString[] = `experimental-descriptors` [constexpr]
Definition at line 40 of file module-decoder-impl.h.
Referenced by IdentifyUnknownSectionInternal(), and SectionName().
kExceptionAttribute
constexpr uint32_t v8::internal::wasm::kExceptionAttribute = 0 [constexpr]
Definition at line 187 of file wasm-constants.h.
Referenced by v8::internal::wasm::ModuleDecoderImpl::consume_exception_attribute(), and v8::internal::wasm::WasmModuleBuilder::WriteTo().
kExternalDebugInfoString
constexpr char v8::internal::wasm::kExternalDebugInfoString[] = `external_debug_info` [constexpr]
Definition at line 37 of file module-decoder-impl.h.
Referenced by IdentifyUnknownSectionInternal(), and SectionName().
kFloat32SignBitMask
constexpr uint32_t v8::internal::wasm::kFloat32SignBitMask = uint32_t{1} << 31 [constexpr]
Definition at line 674 of file wasm-interpreter.cc.
kFloat64SignBitMask
constexpr uint64_t v8::internal::wasm::kFloat64SignBitMask = uint64_t{1} << 63 [constexpr]
Definition at line 675 of file wasm-interpreter.cc.
kFpCacheRegList
constexpr LiftoffRegList v8::internal::wasm::kFpCacheRegList [static], [constexpr]
Initial value:
=
    LiftoffRegList::FromBits<LiftoffRegList::kFpMask>()
Definition at line 522 of file liftoff-register.h.
Referenced by GetCacheRegList(), v8::internal::wasm::LiftoffAssembler::PopRegisters(), v8::internal::wasm::LiftoffAssembler::PushRegisters(), v8::internal::wasm::LiftoffAssembler::RecordSpillsInSafepoint(), and v8::internal::wasm::LiftoffAssembler::SpillAdjacentFpRegisters().
kFpParamRegisters
constexpr DoubleRegister v8::internal::wasm::kFpParamRegisters[] = {} [constexpr]
Definition at line 119 of file wasm-linkage.h.
Referenced by v8::internal::compiler::CodeGenerator::AssembleConstructFrame(), v8::internal::compiler::CodeGenerator::AssembleReturn(), IterateSignatureImpl(), v8::internal::anonymous_namespace{builtins-riscv.cc}::JSToWasmWrapperHelper(), and v8::internal::wasm::LiftoffAssembler::PatchPrepareStackFrame().
kFpReturnRegisters
constexpr DoubleRegister v8::internal::wasm::kFpReturnRegisters[] = {} [constexpr]
Definition at line 120 of file wasm-linkage.h.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::AllReturnRegs(), v8::internal::wasm::LiftoffAssembler::CheckStackShrink(), IterateSignatureImpl(), v8::internal::anonymous_namespace{builtins-riscv.cc}::JSToWasmWrapperHelper(), v8::internal::wasm::LiftoffAssembler::MoveToReturnLocations(), and v8::internal::WasmToJSWrapperDescriptor::return_double_registers().
kFunctionExecutedBit
constexpr uint8_t v8::internal::wasm::kFunctionExecutedBit = 1 << 0 [constexpr]
Definition at line 12 of file pgo.cc.
Referenced by DeserializeTieringInformation(), and v8::internal::wasm::ProfileGenerator::SerializeTieringInfo().
kFunctionTieredUpBit
constexpr uint8_t v8::internal::wasm::kFunctionTieredUpBit = 1 << 1 [constexpr]
Definition at line 13 of file pgo.cc.
Referenced by DeserializeTieringInformation(), and v8::internal::wasm::ProfileGenerator::SerializeTieringInfo().
kGenericWrapperBudget
constexpr uint32_t v8::internal::wasm::kGenericWrapperBudget = 1000 [constexpr]
Definition at line 211 of file wasm-constants.h.
kGpCacheRegList
constexpr LiftoffRegList v8::internal::wasm::kGpCacheRegList [static], [constexpr]
Initial value:
=
    LiftoffRegList::FromBits<LiftoffRegList::kGpMask>()
Definition at line 520 of file liftoff-register.h.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallIndirectImpl(), v8::internal::wasm::LiftoffAssembler::FinishCall(), GetCacheRegList(), v8::internal::wasm::LiftoffAssembler::GetUnusedRegister(), v8::internal::wasm::LiftoffAssembler::PrepareCall(), v8::internal::wasm::LiftoffAssembler::RecordSpillsInSafepoint(), and v8::internal::wasm::LiftoffAssembler::CacheState::TrySetCachedInstanceRegister().
kGpParamRegisters
constexpr Register v8::internal::wasm::kGpParamRegisters[] = {} [constexpr]
Definition at line 117 of file wasm-linkage.h.
Referenced by v8::internal::compiler::CodeGenerator::AssembleConstructFrame(), v8::internal::wasm::LiftoffAssembler::CallFrameSetupStub(), IterateSignatureImpl(), v8::internal::anonymous_namespace{builtins-riscv.cc}::JSToWasmWrapperHelper(), v8::internal::wasm::LiftoffAssembler::PatchPrepareStackFrame(), v8::internal::wasm::LiftoffAssembler::PrepareCall(), and v8::internal::WasmToJSWrapperDescriptor::registers().
kGpReturnRegisters
constexpr Register v8::internal::wasm::kGpReturnRegisters[] = {} [constexpr]
Definition at line 118 of file wasm-linkage.h.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::AllReturnRegs(), v8::internal::compiler::CodeGenerator::AssembleReturn(), v8::internal::wasm::LiftoffAssembler::CheckStackShrink(), IterateSignatureImpl(), v8::internal::anonymous_namespace{builtins-riscv.cc}::JSToWasmWrapperHelper(), v8::internal::wasm::LiftoffAssembler::MoveToReturnLocations(), and v8::internal::WasmToJSWrapperDescriptor::return_registers().
kHexChars
constexpr char v8::internal::wasm::kHexChars[] = `0123456789abcdef` [static], [constexpr]
Definition at line 117 of file wasm-disassembler.cc.
Referenced by v8::internal::wasm::FunctionBodyDisassembler::PrintHexNumber(), PrintStringAsJSON(), and PrintStringRaw().
kIndicesAsComments
constexpr IndexAsComment v8::internal::wasm::kIndicesAsComments = NamesProvider::kIndexAsComment [constexpr]
Definition at line 31 of file wasm-disassembler-impl.h.
Referenced by v8::internal::wasm::FunctionBodyDisassembler::DecodeAsWat(), v8::internal::wasm::ModuleDisassembler::PrintModule(), and v8::internal::wasm::ImmediatesPrinter< ValidationTag >::StringConst().
kInstructionTable
PWasmOp * v8::internal::wasm::kInstructionTable
Definition at line 7139 of file wasm-interpreter.cc.
Referenced by CallThroughDispatchTable().
kInstructionTableMask
constexpr uint32_t v8::internal::wasm::kInstructionTableMask = kInstructionTableSize - 1 [static], [constexpr]
Definition at line 1217 of file wasm-interpreter.h.
Referenced by CallThroughDispatchTable().
kInstructionTableSize
constexpr uint32_t v8::internal::wasm::kInstructionTableSize = 4096 [static], [constexpr]
Definition at line 1216 of file wasm-interpreter.h.
Referenced by InitTrapHandlersOnce().
kInstTraceString
constexpr char v8::internal::wasm::kInstTraceString[] = `metadata.code.trace_inst` [constexpr]
Definition at line 33 of file module-decoder-impl.h.
Referenced by IdentifyUnknownSectionInternal(), and SectionName().
kIntConst
constexpr auto v8::internal::wasm::kIntConst = VarState::kIntConst [constexpr]
Definition at line 47 of file liftoff-compiler.cc.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GetCurrentDebugSideTableEntries(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::LocalSet().
kInvalidCanonicalIndex
constexpr uint32_t v8::internal::wasm::kInvalidCanonicalIndex = static_cast<uint32_t>(-1) [constexpr]
Definition at line 193 of file wasm-constants.h.
kInvalidWasmCodePointer
constexpr WasmCodePointer v8::internal::wasm::kInvalidWasmCodePointer [constexpr]
Initial value:
=
    WasmCodePointer{WasmCodePointerTable::kInvalidHandle}
Definition at line 88 of file wasm-code-manager.h.
Referenced by v8::internal::WasmDispatchTable::Clear(), v8::internal::WasmTrustedInstanceData::GetCallTarget(), v8::internal::wasm::NativeModule::GetCodePointerHandle(), v8::internal::RUNTIME_FUNCTION(), v8::internal::WasmDispatchTable::SetForNonWrapper(), and v8::internal::WasmDispatchTable::target().
kIsBigEndian
constexpr bool v8::internal::wasm::kIsBigEndian = false [constexpr]
Definition at line 134 of file wasm-linkage.h.
kIsBigEndianOnSim
constexpr bool v8::internal::wasm::kIsBigEndianOnSim = false [constexpr]
Definition at line 139 of file wasm-linkage.h.
kIsFpAlwaysDouble
constexpr bool v8::internal::wasm::kIsFpAlwaysDouble = false [constexpr]
Definition at line 129 of file wasm-linkage.h.
kLiftoffAssemblerFpCacheRegs
constexpr DoubleRegList v8::internal::wasm::kLiftoffAssemblerFpCacheRegs [constexpr]
Initial value:
=
    DoubleRegList::FromBits(0xff)
Definition at line 142 of file liftoff-assembler-defs.h.
Referenced by v8::internal::wasm::LiftoffAssembler::emit_i8x16_shuffle(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitDeoptPoint(), and v8::internal::wasm::LiftoffRegister::LiftoffRegister().
kLiftoffAssemblerGpCacheRegs
constexpr RegList v8::internal::wasm::kLiftoffAssemblerGpCacheRegs = RegList::FromBits(0xff) [constexpr]
Definition at line 140 of file liftoff-assembler-defs.h.
Referenced by v8::internal::wasm::liftoff::CacheStatePreservingTempRegisters::Acquire(), v8::internal::wasm::liftoff::AtomicBinop32(), v8::internal::wasm::LiftoffRegister::LiftoffRegister(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SpillLocalsInitially().
kMaxCanonicalTypes
constexpr size_t v8::internal::wasm::kMaxCanonicalTypes = kV8MaxWasmTypes [static], [constexpr]
Definition at line 30 of file canonical-types.h.
Referenced by v8::internal::wasm::TypeCanonicalizer::CanonicalHashing::Add(), v8::internal::wasm::TypeCanonicalizer::AddPredefinedArrayTypes(), v8::internal::wasm::TypeCanonicalizer::CanonicalizeTypeDef(), v8::internal::wasm::TypeCanonicalizer::CheckMaxCanonicalIndex(), v8::internal::wasm::TypeCanonicalizer::FindCanonicalGroup(), v8::internal::wasm::WasmExportWrapperCache::Hash(), v8::internal::WasmJSFunction::New(), and v8::internal::wasm::TypeCanonicalizer::CanonicalTypeVector::reserve().
kMaxFpRegCode
constexpr int v8::internal::wasm::kMaxFpRegCode = kLiftoffAssemblerFpCacheRegs.last().code() [static], [constexpr]
Definition at line 125 of file liftoff-register.h.
kMaxGpRegCode
constexpr int v8::internal::wasm::kMaxGpRegCode = kLiftoffAssemblerGpCacheRegs.last().code() [static], [constexpr]
Definition at line 123 of file liftoff-register.h.
kMaxMemory64Size
constexpr size_t v8::internal::wasm::kMaxMemory64Size [constexpr]
Initial value:
=
    size_t{kV8MaxWasmMemory64Pages} * kWasmPageSize
Definition at line 111 of file wasm-limits.h.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::BoundsCheckMem(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BoundsCheckMem(), and v8::internal::anonymous_namespace{backing-store.cc}::GetReservationSize().
kMaxPolymorphism
constexpr int v8::internal::wasm::kMaxPolymorphism = 4 [constexpr]
Definition at line 218 of file wasm-constants.h.
Referenced by v8::internal::wasm::FeedbackMaker::FinalizeCall(), and v8::internal::wasm::TransitiveTypeFeedbackProcessor::ProcessFunction().
kMaxStructFieldIndexForImplicitNullCheck
constexpr int v8::internal::wasm::kMaxStructFieldIndexForImplicitNullCheck = 4000 [constexpr]
Definition at line 222 of file wasm-constants.h.
Referenced by v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::null_checks_for_struct_op(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::null_checks_for_struct_op(), v8::internal::compiler::WasmGCLowering::ReduceWasmStructGet(), and v8::internal::compiler::WasmGCLowering::ReduceWasmStructSet().
kMaxValueTypeSize
constexpr int v8::internal::wasm::kMaxValueTypeSize = 16 [constexpr]
Definition at line 50 of file value-type.h.
Referenced by v8::internal::WasmStruct::EncodeInstanceSizeInMap(), and v8::internal::wasm::StackMemory::JSStackLimitMarginKB().
kMaxVarInt32Size
constexpr size_t v8::internal::wasm::kMaxVarInt32Size = 5 [constexpr]
Definition at line 20 of file leb-helper.h.
Referenced by v8::internal::wasm::WasmFunctionBuilder::EmitDirectCallIndex(), v8::internal::wasm::ZoneBuffer::reserve_u32v(), v8::internal::wasm::ZoneBuffer::write_i32v(), v8::internal::wasm::ZoneBuffer::write_size(), and v8::internal::wasm::ZoneBuffer::write_u32v().
kMaxVarInt64Size
constexpr size_t v8::internal::wasm::kMaxVarInt64Size = 10 [constexpr]
Definition at line 21 of file leb-helper.h.
Referenced by v8::internal::wasm::ZoneBuffer::write_i64v(), and v8::internal::wasm::ZoneBuffer::write_u64v().
kMinimumSupertypeArraySize
constexpr uint32_t v8::internal::wasm::kMinimumSupertypeArraySize = 3 [constexpr]
Definition at line 215 of file wasm-constants.h.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildIndirectCallTargetAndImplicitArg(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallIndirectImpl(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCast(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ReduceWasmTypeCastRtt(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheck(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ReduceWasmTypeCheckRtt(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SubtypeCheck(), and v8::internal::wasm::WasmInterpreterRuntime::SubtypeCheck().
kNameString
constexpr char v8::internal::wasm::kNameString[] = `name` [constexpr]
Definition at line 31 of file module-decoder-impl.h.
Referenced by IdentifyUnknownSectionInternal(), and SectionName().
kNeedI64RegPair
constexpr bool v8::internal::wasm::kNeedI64RegPair = kSystemPointerSize == 4 [static], [constexpr]
Definition at line 19 of file liftoff-register.h.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::AtomicWait(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BoundsCheckMem(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CurrentMemoryPages(), v8::internal::wasm::LiftoffRegister::ForPair(), v8::internal::wasm::LiftoffAssembler::GetUnusedRegister(), v8::internal::wasm::LiftoffRegister::is_gp_pair(), v8::internal::wasm::LiftoffRegister::is_pair(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::Load64BitExceptionValue(), v8::internal::wasm::ParallelMove::LoadI64HalfIntoRegister(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::MemoryGrow(), v8::internal::wasm::LiftoffAssembler::Move(), needs_gp_reg_pair(), v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::PrepareStackTransfers(), reg_class_for(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::Store64BitExceptionValue(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::TableGrow(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::TableSize(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::TraceMemoryOperation().
kNeedS128RegPair
constexpr bool v8::internal::wasm::kNeedS128RegPair = kFPAliasing == AliasingKind::kCombine [static], [constexpr]
Definition at line 20 of file liftoff-register.h.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitSimdReplaceLaneOp(), v8::internal::wasm::ParallelMove::ExecuteLoads(), v8::internal::wasm::LiftoffRegister::ForFpPair(), v8::internal::wasm::LiftoffRegister::from_external_code(), v8::internal::wasm::LiftoffAssembler::GetUnusedRegister(), v8::internal::wasm::LiftoffRegister::high(), v8::internal::wasm::LiftoffRegister::is_fp_pair(), v8::internal::wasm::LiftoffRegister::is_pair(), v8::internal::wasm::LiftoffRegister::low(), v8::internal::wasm::LiftoffAssembler::Move(), needs_fp_reg_pair(), reg_class_for(), and v8::internal::wasm::LiftoffAssembler::SpillAdjacentFpRegisters().
kNoCodePosition
constexpr WasmCodePosition v8::internal::wasm::kNoCodePosition = -1 [constexpr]
Definition at line 185 of file wasm-constants.h.
Referenced by v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::BuildCallAndReturn(), v8::internal::compiler::WasmGraphBuilder::BuildCallNode(), and v8::internal::compiler::WasmGraphBuilder::SetSourcePosition().
kNoCompilationHint
constexpr uint8_t v8::internal::wasm::kNoCompilationHint = kMaxUInt8 [constexpr]
Definition at line 144 of file wasm-constants.h.
Referenced by v8::internal::wasm::WasmFunctionBuilder::SetCompilationHint(), and v8::internal::wasm::WasmModuleBuilder::WriteTo().
kNoSuperType
constexpr ModuleTypeIndex v8::internal::wasm::kNoSuperType = ModuleTypeIndex::Invalid() [constexpr]
Definition at line 79 of file value-type.h.
Referenced by v8::internal::wasm::TypeCanonicalizer::AddPredefinedArrayTypes(), v8::internal::wasm::TypeCanonicalizer::AddRecursiveGroup(), v8::internal::wasm::WasmModule::AddTypeForTesting(), v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::CommonAncestor(), v8::internal::wasm::ModuleDecoderImpl::consume_base_type_definition(), v8::internal::wasm::ModuleDecoderImpl::consume_subtype_definition(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::GenerateRandomArrays(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::GenerateRandomStructs(), v8::internal::wasm::fuzzing::GenerateRandomWasmModule(), v8::internal::wasm::fuzzing::GenerateWasmModuleForDeopt(), v8::internal::wasm::fuzzing::GenerateWasmModuleForInitExpressions(), and v8::internal::wasm::ModuleDisassembler::PrintTypeDefinition().
kNotShared
constexpr bool v8::internal::wasm::kNotShared = false [static], [constexpr]
Definition at line 106 of file value-type.h.
Referenced by v8::internal::wasm::TypeCanonicalizer::AddRecursiveGroup(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallIndirect(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallRef(), v8::internal::wasm::ValueType::For(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ReturnCallIndirect(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::ReturnCallRef().
kNoType
constexpr ModuleTypeIndex v8::internal::wasm::kNoType = ModuleTypeIndex::Invalid() [constexpr]
Definition at line 80 of file value-type.h.
kNoValidate
constexpr Decoder::NoValidationTag v8::internal::wasm::kNoValidate [constexpr]
Definition at line 15 of file wasm-interpreter-simd.cc.
Referenced by v8::internal::wasm::WasmBytecodeGenerator::DecodeSimdOp().
kOperatorModeCount
const size_t v8::internal::wasm::kOperatorModeCount = 4 [static]
Definition at line 727 of file wasm-interpreter.h.
kPaddedVarInt32Size
constexpr size_t v8::internal::wasm::kPaddedVarInt32Size = 5 [constexpr]
Definition at line 19 of file leb-helper.h.
Referenced by v8::internal::wasm::anonymous_namespace{wasm-module-builder.cc}::FixupSection(), and v8::internal::wasm::ZoneBuffer::patch_u32v().
kPartialOOBWritesAreNoops
constexpr bool v8::internal::wasm::kPartialOOBWritesAreNoops = true [constexpr]
Definition at line 47 of file compilation-environment.h.
Referenced by v8::internal::RUNTIME_FUNCTION(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StoreLane(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StoreLane(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StoreMem(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StoreMem().
kRegister
constexpr auto v8::internal::wasm::kRegister = VarState::kRegister [constexpr]
Definition at line 46 of file liftoff-compiler.cc.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GetCurrentDebugSideTableEntries(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::LocalSet().
kRegModes
const RegModeTransform v8::internal::wasm::kRegModes[256] [static]
Definition at line 778 of file wasm-interpreter.h.
Referenced by v8::internal::wasm::WasmInstruction::InputRegMode(), and v8::internal::wasm::WasmInstruction::SupportsToRegister().
kSharedFlagCode
constexpr uint8_t v8::internal::wasm::kSharedFlagCode = 0x65 [constexpr]
Definition at line 66 of file wasm-constants.h.
Referenced by v8::internal::wasm::ModuleDecoderImpl::consume_shared_type(), v8::internal::wasm::LocalDeclEncoder::Emit(), v8::internal::wasm::value_type_reader::read_heap_type(), and v8::internal::wasm::anonymous_namespace{wasm-module-builder.cc}::WriteValueType().
kSkipDataSegmentNames
constexpr bool v8::internal::wasm::kSkipDataSegmentNames = true [constexpr]
Definition at line 32 of file wasm-disassembler-impl.h.
Referenced by v8::internal::wasm::ImmediatesPrinter< ValidationTag >::DataSegmentIndex(), and v8::internal::wasm::ModuleDisassembler::PrintModule().
kSkipFunctionTypesInTypeSection
constexpr bool v8::internal::wasm::kSkipFunctionTypesInTypeSection = true [constexpr]
Definition at line 30 of file wasm-disassembler-impl.h.
Referenced by v8::internal::wasm::ModuleDisassembler::PrintModule().
kSlotSize
const size_t v8::internal::wasm::kSlotSize = sizeof(int32_t) [static]
Definition at line 1052 of file wasm-interpreter.h.
Referenced by v8::internal::wasm::WasmInterpreterRuntime::BeginExecution(), v8::internal::wasm::WasmInterpreterRuntime::CallExternalJSFunction(), v8::internal::wasm::WasmInterpreterRuntime::ContinueExecution(), v8::internal::wasm::WasmBytecodeGenerator::CreateConstSlot(), v8::internal::wasm::WasmBytecodeGenerator::CreateSlot(), v8::internal::wasm::WasmBytecodeGenerator::CreateWasmRefSlot(), v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction(), v8::internal::wasm::WasmInterpreterRuntime::ExecuteCallRef(), v8::internal::wasm::WasmInterpreterRuntime::ExecuteFunction(), v8::internal::wasm::WasmInterpreterRuntime::ExecuteIndirectCall(), v8::internal::wasm::WasmBytecodeGenerator::FindSharedSlot(), v8::internal::wasm::WasmBytecodeGenerator::GenerateBytecode(), GetValueSizeInSlots(), v8::internal::wasm::WasmBytecode::InitializeSlots(), v8::internal::wasm::WasmInterpreterRuntime::PrepareTailCall(), v8::internal::wasm::Handlers< Compressed >::push(), v8::internal::wasm::WasmBytecodeGenerator::RestoreIfElseParams(), v8::internal::wasm::WasmBytecodeGenerator::ScanConstInstructions(), v8::internal::wasm::WasmBytecodeGenerator::StoreBlockParamsAndResultsIntoSlots(), v8::internal::wasm::WasmBytecodeGenerator::StoreBlockParamsIntoSlots(), v8::internal::wasm::WasmInterpreterRuntime::StoreRefArgsIntoStackSlots(), and v8::internal::wasm::WasmInterpreterRuntime::UnpackException().
kSourceMappingURLString
constexpr char v8::internal::wasm::kSourceMappingURLString[] = `sourceMappingURL` [constexpr]
Definition at line 32 of file module-decoder-impl.h.
Referenced by IdentifyUnknownSectionInternal(), and SectionName().
kSpecMaxMemory32Pages
constexpr size_t v8::internal::wasm::kSpecMaxMemory32Pages = 65'536 [constexpr]
Definition at line 25 of file wasm-limits.h.
Referenced by v8::internal::wasm::ModuleDecoderImpl::DecodeImportSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeMemorySection(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryImpl().
kSpecMaxMemory64Pages
constexpr size_t v8::internal::wasm::kSpecMaxMemory64Pages = 262'144 [constexpr]
Definition at line 26 of file wasm-limits.h.
Referenced by v8::internal::wasm::ModuleDecoderImpl::DecodeImportSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeMemorySection(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryImpl().
kStack
constexpr auto v8::internal::wasm::kStack = VarState::kStack [constexpr]
Definition at line 48 of file liftoff-compiler.cc.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GetCurrentDebugSideTableEntries(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::LocalSet().
kStackFpOffset
constexpr int v8::internal::wasm::kStackFpOffset [constexpr]
Initial value:
=
    wasm::StackMemory::jmpbuf_offset() + offsetof(JumpBuffer, fp)
Definition at line 222 of file stacks.h.
Referenced by v8::internal::anonymous_namespace{builtins-riscv.cc}::FillJumpBuffer(), and v8::internal::anonymous_namespace{builtins-riscv.cc}::LoadJumpBuffer().
kStackLimitOffset
constexpr int v8::internal::wasm::kStackLimitOffset [constexpr]
Initial value:
=
    wasm::StackMemory::jmpbuf_offset() + offsetof(JumpBuffer, stack_limit)
Definition at line 226 of file stacks.h.
Referenced by v8::internal::anonymous_namespace{builtins-riscv.cc}::FillJumpBuffer(), and v8::internal::anonymous_namespace{builtins-riscv.cc}::SwitchStackPointerAndSimulatorStackLimit().
kStackParentOffset
constexpr int v8::internal::wasm::kStackParentOffset [constexpr]
Initial value:
=
    wasm::StackMemory::jmpbuf_offset() + offsetof(JumpBuffer, parent)
Definition at line 228 of file stacks.h.
Referenced by v8::internal::anonymous_namespace{builtins-riscv.cc}::ReloadParentStack(), and v8::internal::anonymous_namespace{builtins-riscv.cc}::SwitchToAllocatedStack().
kStackPcOffset
constexpr int v8::internal::wasm::kStackPcOffset [constexpr]
Initial value:
=
    wasm::StackMemory::jmpbuf_offset() + offsetof(JumpBuffer, pc)
Definition at line 224 of file stacks.h.
Referenced by v8::internal::anonymous_namespace{builtins-riscv.cc}::FillJumpBuffer(), and v8::internal::anonymous_namespace{builtins-riscv.cc}::LoadJumpBuffer().
kStackSpOffset
constexpr int v8::internal::wasm::kStackSpOffset [constexpr]
Initial value:
=
    wasm::StackMemory::jmpbuf_offset() + offsetof(JumpBuffer, sp)
Definition at line 220 of file stacks.h.
Referenced by v8::internal::anonymous_namespace{builtins-riscv.cc}::FillJumpBuffer(), v8::internal::anonymous_namespace{builtins-riscv.cc}::ReloadParentStack(), and v8::internal::anonymous_namespace{builtins-riscv.cc}::SwitchStackPointerAndSimulatorStackLimit().
kStackStateOffset
constexpr int v8::internal::wasm::kStackStateOffset [constexpr]
Initial value:
=
    wasm::StackMemory::jmpbuf_offset() + offsetof(JumpBuffer, state)
Definition at line 230 of file stacks.h.
Referenced by v8::internal::anonymous_namespace{builtins-riscv.cc}::SwitchStackState().
kUpperHexChars
constexpr char v8::internal::wasm::kUpperHexChars[] = `0123456789ABCDEF` [static], [constexpr]
Definition at line 118 of file wasm-disassembler.cc.
Referenced by v8::internal::wasm::ImmediatesPrinter< ValidationTag >::S128Const().
kV8MaxRttSubtypingDepth
constexpr uint32_t v8::internal::wasm::kV8MaxRttSubtypingDepth = 63 [constexpr]
Definition at line 65 of file wasm-limits.h.
Referenced by v8::internal::wasm::ModuleDecoderImpl::FinalizeRecgroup(), and GetSubtypingDepth().
kV8MaxWasmArrayNewFixedLength
constexpr size_t v8::internal::wasm::kV8MaxWasmArrayNewFixedLength = 10'000 [constexpr]
Definition at line 66 of file wasm-limits.h.
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeGCOpcode().
kV8MaxWasmDataSegments
constexpr size_t v8::internal::wasm::kV8MaxWasmDataSegments = 100'000 [constexpr]
Definition at line 37 of file wasm-limits.h.
Referenced by v8::internal::wasm::ModuleDecoderImpl::DecodeDataCountSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeDataSection(), and v8::internal::wasm::DecodedNameSection::DecodedNameSection().
kV8MaxWasmDefinedFunctions
constexpr size_t v8::internal::wasm::kV8MaxWasmDefinedFunctions = 1'000'000 [constexpr]
Definition at line 31 of file wasm-limits.h.
kV8MaxWasmExceptionTypes
constexpr size_t v8::internal::wasm::kV8MaxWasmExceptionTypes = 1'000'000 [constexpr]
Definition at line 36 of file wasm-limits.h.
kV8MaxWasmExports
constexpr size_t v8::internal::wasm::kV8MaxWasmExports = 1'000'000 [constexpr]
Definition at line 33 of file wasm-limits.h.
Referenced by v8::internal::wasm::ModuleDecoderImpl::DecodeExportSection().
kV8MaxWasmFunctionBrTableSize
constexpr size_t v8::internal::wasm::kV8MaxWasmFunctionBrTableSize = 65'520 [constexpr]
Definition at line 55 of file wasm-limits.h.
Referenced by v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate().
kV8MaxWasmFunctionLocals
constexpr size_t v8::internal::wasm::kV8MaxWasmFunctionLocals = 50'000 [constexpr]
Definition at line 52 of file wasm-limits.h.
Referenced by v8::internal::wasm::DecodedNameSection::DecodedNameSection(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeLocals(), and v8::internal::wasm::AsmJsParser::ValidateFunction().
kV8MaxWasmFunctionParams
constexpr size_t v8::internal::wasm::kV8MaxWasmFunctionParams = 1'000 [constexpr]
Definition at line 53 of file wasm-limits.h.
Referenced by v8::internal::wasm::ModuleDecoderImpl::consume_sig(), v8::internal::wasm::StackMemory::JSStackLimitMarginKB(), v8::internal::wasm::WasmCode::Validate(), v8::internal::wasm::AsmJsParser::ValidateCall(), v8::internal::wasm::AsmJsParser::ValidateFunction(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyFunction(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTagImpl().
kV8MaxWasmFunctionReturns
constexpr size_t v8::internal::wasm::kV8MaxWasmFunctionReturns = 1'000 [constexpr]
Definition at line 54 of file wasm-limits.h.
Referenced by v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCallAllocateJSArray(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCapiCallWrapper(), v8::internal::wasm::ModuleDecoderImpl::consume_sig(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyFunction().
kV8MaxWasmFunctionSize
constexpr size_t v8::internal::wasm::kV8MaxWasmFunctionSize = 7'654'321 [constexpr]
Definition at line 51 of file wasm-limits.h.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallIndirectImpl(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallRefImpl(), v8::internal::wasm::ModuleDecoderImpl::DecodeCodeSection(), v8::internal::wasm::DecodedNameSection::DecodedNameSection(), DecodeWasmFunctionForTesting(), NumFeedbackSlots(), and v8::internal::wasm::AsmJsParser::ValidateFunction().
kV8MaxWasmGlobals
constexpr size_t v8::internal::wasm::kV8MaxWasmGlobals = 1'000'000 [constexpr]
Definition at line 34 of file wasm-limits.h.
Referenced by v8::internal::wasm::DecodedNameSection::DecodedNameSection(), and v8::internal::wasm::ModuleDecoderImpl::DecodeGlobalSection().
kV8MaxWasmImports
constexpr size_t v8::internal::wasm::kV8MaxWasmImports = 1'000'000 [constexpr]
Definition at line 32 of file wasm-limits.h.
Referenced by v8::internal::wasm::ModuleDecoderImpl::DecodeImportSection().
kV8MaxWasmMemories
constexpr size_t v8::internal::wasm::kV8MaxWasmMemories = 100'000 [constexpr]
Definition at line 61 of file wasm-limits.h.
Referenced by v8::internal::wasm::InstanceBuilder::Build_Phase1(), v8::internal::wasm::DecodedNameSection::DecodedNameSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeImportSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeMemorySection(), and v8::internal::WasmTrustedInstanceData::New().
kV8MaxWasmMemory32Pages
constexpr size_t v8::internal::wasm::kV8MaxWasmMemory32Pages [constexpr]
Initial value:
= kSystemPointerSize == 4
                                               ? 32'767
                                               : 65'536
Definition at line 43 of file wasm-limits.h.
Referenced by max_mem32_pages().
kV8MaxWasmMemory64Pages
constexpr size_t v8::internal::wasm::kV8MaxWasmMemory64Pages [constexpr]
Initial value:
= kSystemPointerSize == 4
                                               ? 32'767
                                               : 262'144
Definition at line 46 of file wasm-limits.h.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::GenerateRandomMemories(), max_mem64_pages(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryGrowImpl().
kV8MaxWasmModuleSize
constexpr size_t v8::internal::wasm::kV8MaxWasmModuleSize = 1024 * 1024 * 1024 [constexpr]
Definition at line 50 of file wasm-limits.h.
Referenced by v8::internal::wasm::WasmEngine::AsyncCompile(), DecodeWasmModule(), and max_module_size().
kV8MaxWasmStringLiterals
constexpr size_t v8::internal::wasm::kV8MaxWasmStringLiterals = 1'000'000 [constexpr]
Definition at line 69 of file wasm-limits.h.
Referenced by v8::internal::wasm::ModuleDecoderImpl::DecodeStringRefSection(), and v8::internal::RUNTIME_FUNCTION().
kV8MaxWasmStringSize
constexpr size_t v8::internal::wasm::kV8MaxWasmStringSize = 100'000 [constexpr]
Definition at line 49 of file wasm-limits.h.
kV8MaxWasmStructFields
constexpr size_t v8::internal::wasm::kV8MaxWasmStructFields = 10'000 [constexpr]
Definition at line 64 of file wasm-limits.h.
Referenced by v8::internal::wasm::ModuleDecoderImpl::consume_struct(), v8::internal::wasm::DecodedNameSection::DecodedNameSection(), v8::internal::WasmStruct::EncodeInstanceSizeInMap(), and v8::internal::wasm::StructTypeBase::StructTypeBase().
kV8MaxWasmTableInitEntries
constexpr size_t v8::internal::wasm::kV8MaxWasmTableInitEntries = 10'000'000 [constexpr]
Definition at line 59 of file wasm-limits.h.
Referenced by v8::internal::wasm::DecodedNameSection::DecodedNameSection(), max_table_init_entries(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableImpl().
kV8MaxWasmTables
constexpr size_t v8::internal::wasm::kV8MaxWasmTables = 100'000 [constexpr]
Definition at line 60 of file wasm-limits.h.
Referenced by v8::internal::wasm::DecodedNameSection::DecodedNameSection(), and v8::internal::wasm::ModuleDecoderImpl::DecodeTableSection().
kV8MaxWasmTableSize
constexpr size_t v8::internal::wasm::kV8MaxWasmTableSize = 10'000'000 [constexpr]
Definition at line 58 of file wasm-limits.h.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildIndirectCallTargetAndImplicitArg(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallIndirectImpl(), v8::internal::WasmTableObject::Grow(), max_table_size(), v8::internal::RUNTIME_FUNCTION(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableGrowImpl().
kV8MaxWasmTags
constexpr size_t v8::internal::wasm::kV8MaxWasmTags = 1'000'000 [constexpr]
Definition at line 35 of file wasm-limits.h.
Referenced by v8::internal::wasm::DecodedNameSection::DecodedNameSection(), and v8::internal::wasm::ModuleDecoderImpl::DecodeTagSection().
kV8MaxWasmTotalFunctions
constexpr size_t v8::internal::wasm::kV8MaxWasmTotalFunctions [constexpr]
Initial value:
=
    kV8MaxWasmDefinedFunctions + kV8MaxWasmImports
Definition at line 88 of file wasm-limits.h.
Referenced by v8::internal::wasm::DecodedNameSection::DecodedNameSection(), and v8::internal::wasm::anonymous_namespace{module-decoder.cc}::ValidateFunctionsTask::Run().
kV8MaxWasmTypes
constexpr size_t v8::internal::wasm::kV8MaxWasmTypes = 1'000'000 [constexpr]
Definition at line 30 of file wasm-limits.h.
Referenced by v8::internal::wasm::DecodedNameSection::DecodedNameSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeTypeSection(), and v8::internal::wasm::value_type_reader::read_heap_type().
kWasmAnyRef
constexpr IndependentHeapType v8::internal::wasm::kWasmAnyRef {GenericKind::kAny} [constexpr]
Definition at line 1257 of file value-type.h.
Referenced by v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::AnyConvertExtern(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ArrayLength(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BrOnCastFailImpl(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BrOnCastImpl(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeAtomicOpcode(), v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ExternConvertAny(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateInitExpr(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GenerateRef(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GetCurrentDebugSideTableEntries(), v8::internal::wasm::TurboshaftGraphBuildingInterface::GetRttFromDescriptor(), v8::anonymous_namespace{wasm-js.cc}::GetValueType(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GetValueTypeHelper(), v8::internal::compiler::WasmGCLowering::ReduceWasmArrayLength(), v8::internal::compiler::WasmGCLowering::ReduceWasmExternConvertAny(), v8::internal::compiler::WasmGCLowering::ReduceWasmStructGet(), v8::internal::compiler::WasmGCLowering::ReduceWasmStructSet(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCast(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ReduceWasmTypeCastRtt(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheck(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheckAbstract(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCheckAbstract(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ReduceWasmTypeCheckAbstract(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ReduceWasmTypeCheckRtt(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::ref_is_null(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::ref_test(), v8::internal::RUNTIME_FUNCTION(), v8::internal::wasm::Handlers< Compressed >::s2s_AnyConvertExtern(), v8::internal::wasm::Handlers< Compressed >::s2s_ExternConvertAny(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StartFunctionBody(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::StructAtomicRMW(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::StructGet(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::StructSet(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::top_type(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::UnOp(), value_type< WasmRef >(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableImpl().
kWasmArrayRef
constexpr IndependentHeapType v8::internal::wasm::kWasmArrayRef {GenericKind::kArray} [constexpr]
Definition at line 1268 of file value-type.h.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_len(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateInitExpr(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GenerateRef(), v8::anonymous_namespace{wasm-js.cc}::GetValueType(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GetValueTypeHelper(), v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::ParseArrayLen(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableImpl().
kWasmArrayTypeCode
constexpr uint8_t v8::internal::wasm::kWasmArrayTypeCode = 0x5e [constexpr]
Definition at line 69 of file wasm-constants.h.
Referenced by v8::internal::wasm::ModuleDecoderImpl::consume_base_type_definition(), v8::internal::wasm::ModuleDecoderImpl::TypeKindName(), and v8::internal::wasm::WasmModuleBuilder::WriteTo().
kWasmBottom
constexpr IndependentHeapType v8::internal::wasm::kWasmBottom {GenericKind::kBottom, kNonNullable} [constexpr]
Definition at line 1254 of file value-type.h.
Referenced by v8::internal::wasm::ModuleDecoderImpl::consume_element_segment_header(), v8::internal::CreateFuncRefMap(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::CreateMergeSnapshot(), v8::internal::CreateStructMap(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE(), v8::internal::wasm::ModuleDecoderImpl::DecodeElementSection(), v8::internal::wasm::WasmBytecodeGenerator::DecodeInstruction(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::EncodeExceptionValues(), v8::internal::wasm::WasmBytecodeGenerator::GenerateBytecode(), Intersection(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PushControl(), v8::internal::wasm::value_type_reader::read_heap_type(), v8::internal::wasm::value_type_reader::read_value_type(), v8::internal::compiler::WasmTyper::Reduce(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::RefineTypeKnowledge(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::RefineTypeKnowledgeNotNull(), v8::internal::wasm::WasmBytecodeGenerator::ReserveBlockSlots(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::TypeCheckStackAgainstMerge_Slow(), Union(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::UnreachableValue(), and v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::ValidateStackValue().
kWasmContRef
constexpr IndependentHeapType v8::internal::wasm::kWasmContRef {GenericKind::kCont} [constexpr]
Definition at line 1286 of file value-type.h.
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE(), and v8::internal::wasm::value_type_reader::read_value_type().
kWasmContTypeCode
constexpr uint8_t v8::internal::wasm::kWasmContTypeCode = 0x5d [constexpr]
Definition at line 70 of file wasm-constants.h.
Referenced by v8::internal::wasm::ModuleDecoderImpl::consume_base_type_definition(), v8::internal::wasm::ModuleDecoderImpl::TypeKindName(), and v8::internal::wasm::WasmModuleBuilder::WriteTo().
kWasmDescribesCode
constexpr uint8_t v8::internal::wasm::kWasmDescribesCode = 0x4c [constexpr]
Definition at line 75 of file wasm-constants.h.
Referenced by v8::internal::wasm::ModuleDecoderImpl::consume_describing_type().
kWasmDescriptorCode
constexpr uint8_t v8::internal::wasm::kWasmDescriptorCode = 0x4d [constexpr]
Definition at line 74 of file wasm-constants.h.
Referenced by v8::internal::wasm::ModuleDecoderImpl::consume_described_type().
kWasmEqRef
constexpr IndependentHeapType v8::internal::wasm::kWasmEqRef {GenericKind::kEq} [constexpr]
Definition at line 1264 of file value-type.h.
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeAtomicOpcode(), v8::anonymous_namespace{wasm-js.cc}::GetValueType(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GetValueTypeHelper(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::ref_eq(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableImpl().
kWasmExnRef
constexpr IndependentHeapType v8::internal::wasm::kWasmExnRef {GenericKind::kExn} [constexpr]
Definition at line 1263 of file value-type.h.
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE(), v8::anonymous_namespace{wasm-js.cc}::GetValueType(), PublishDetectedFeatures(), v8::internal::wasm::value_type_reader::read_value_type(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::top_type(), and v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::try_table_rec().
kWasmExternRef
constexpr IndependentHeapType v8::internal::wasm::kWasmExternRef {GenericKind::kExtern} [constexpr]
Definition at line 1260 of file value-type.h.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::AddImportedStringImports(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::any_convert_extern(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::AnyConvertExtern(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BindBlockAndGeneratePhis(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CatchCase(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CatchCase(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CatchException(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::CheckForWellKnownImport(), v8::internal::compiler::AccessInfoFactory::ComputeElementAccessInfo(), v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ExternConvertAny(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateInitExpr(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GenerateRef(), v8::internal::wasm::WasmInterpreterRuntime::GetNullValue(), v8::anonymous_namespace{wasm-js.cc}::GetValueType(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GetValueTypeHelper(), v8::internal::wasm::TurboshaftGraphBuildingInterface::HandleWellKnownImport(), v8::internal::wasm::WasmInterpreterRuntime::InitializeRefLocalsRefs(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineWasmCall(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::IsDataViewGetterSig(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::IsDataViewSetterSig(), v8::internal::wasm::WasmInterpreterRuntime::IsNull(), v8::internal::compiler::WasmGCLowering::ReduceWasmAnyConvertExtern(), v8::internal::compiler::WasmGCLowering::ReduceWasmExternConvertAny(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCheckAbstract(), v8::internal::RUNTIME_FUNCTION(), v8::internal::wasm::Handlers< Compressed >::s2s_ExternConvertAny(), v8::internal::compiler::WasmGraphBuilder::SetType(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StartFunctionBody(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::string_cast(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::string_charcodeat(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::string_codepointat(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::string_compare(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::string_concat(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::string_equals(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::string_intocharcodearray(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::string_intoutf8array(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::string_length(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::string_measureutf8(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::string_substring(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::string_test(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::string_toutf8array(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StringNewWtf8ArrayImpl(), v8::internal::wasm::WasmInterpreterRuntime::SubtypeCheck(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::table_copy(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::top_type(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::UnOp(), ValidateAndSetBuiltinImports(), wasm::anonymous_namespace{c-api.cc}::WasmValKindToV8(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyFunctionType(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableImpl().
kWasmF16
constexpr IndependentValueType v8::internal::wasm::kWasmF16 {NumericKind::kF16} [constexpr]
Definition at line 1250 of file value-type.h.
kWasmF32
constexpr IndependentValueType v8::internal::wasm::kWasmF32 {NumericKind::kF32} [constexpr]
Definition at line 1245 of file value-type.h.
Referenced by v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::CheckForWellKnownImport(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::CompareWithNormalizedCType(), v8::internal::wasm::AsmJsParser::ConvertSignature(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeSimdOpcode(), v8::internal::wasm::WasmBytecodeGenerator::DoEncodeSuperInstruction(), v8::internal::wasm::WasmBytecodeGenerator::F32Push(), v8::internal::wasm::DebugInfoImpl::GetValue(), v8::anonymous_namespace{wasm-js.cc}::GetValueType(), v8::internal::wasm::InstanceBuilder::ProcessImportedGlobal(), v8::internal::wasm::value_type_reader::read_value_type(), v8::internal::RUNTIME_FUNCTION(), v8::internal::wasm::TurboshaftGraphBuildingInterface::UnOpImpl(), v8::internal::wasm::AsmJsParser::ValidateFunctionLocals(), v8::internal::wasm::AsmJsParser::ValidateModuleVar(), v8::internal::wasm::AsmJsParser::ValidateModuleVarFromGlobal(), value_type< float >(), wasm::anonymous_namespace{c-api.cc}::WasmValKindToV8(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::WellKnown_FastApi().
kWasmF64
constexpr IndependentValueType v8::internal::wasm::kWasmF64 {NumericKind::kF64} [constexpr]
Definition at line 1246 of file value-type.h.
Referenced by v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::CheckForWellKnownImport(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::CompareWithNormalizedCType(), v8::internal::wasm::AsmJsParser::ConvertSignature(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeSimdOpcode(), v8::internal::wasm::WasmBytecodeGenerator::DoEncodeSuperInstruction(), v8::internal::wasm::WasmBytecodeGenerator::F64Push(), v8::internal::wasm::DebugInfoImpl::GetValue(), v8::anonymous_namespace{wasm-js.cc}::GetValueType(), v8::internal::wasm::value_type_reader::read_value_type(), v8::internal::RUNTIME_FUNCTION(), v8::internal::wasm::TurboshaftGraphBuildingInterface::UnOpImpl(), v8::internal::wasm::AsmJsParser::ValidateFunctionLocals(), v8::internal::wasm::AsmJsParser::ValidateModuleVar(), v8::internal::wasm::AsmJsParser::ValidateModuleVarImport(), v8::internal::wasm::AsmJsParser::ValidateModuleVarStdlib(), value_type< double >(), wasm::anonymous_namespace{c-api.cc}::WasmValKindToV8(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::WellKnown_FastApi().
kWasmFuncRef
constexpr IndependentHeapType v8::internal::wasm::kWasmFuncRef {GenericKind::kFunc} [constexpr]
Definition at line 1256 of file value-type.h.
Referenced by v8::internal::wasm::ModuleDecoderImpl::consume_element_func_index(), v8::internal::wasm::ModuleDecoderImpl::consume_element_segment_header(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::GenerateRandomTables(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GenerateRef(), v8::internal::WasmTableObject::GetFunctionTableEntry(), v8::anonymous_namespace{wasm-js.cc}::GetValueType(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GetValueTypeHelper(), v8::internal::wasm::InstanceBuilder::LoadTableSegments(), v8::internal::WasmTrustedInstanceData::New(), v8::internal::wasm::InstanceBuilder::ProcessImportedTable(), v8::internal::wasm::WasmInterpreterRuntime::PurgeIndirectCallCache(), v8::internal::wasm::WasmModuleBuilder::SetIndirectFunction(), v8::internal::wasm::InstanceBuilder::SetTableInitialValues(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::table_copy(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::table_fill(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::table_grow(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::table_op(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::table_set(), v8::internal::wasm::WasmInterpreterRuntime::TableCopy(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::TableGet(), v8::internal::wasm::WasmInterpreterRuntime::TableInit(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::TableSet(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::top_type(), v8::internal::wasm::AsmJsParser::ValidateCall(), wasm::anonymous_namespace{c-api.cc}::WasmValKindToV8(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableImpl().
kWasmFunctionTypeCode
constexpr uint8_t v8::internal::wasm::kWasmFunctionTypeCode = 0x60 [constexpr]
Definition at line 67 of file wasm-constants.h.
Referenced by v8::internal::wasm::ModuleDecoderImpl::consume_base_type_definition(), v8::internal::wasm::ModuleDecoderImpl::DecodeFunctionSignatureForTesting(), v8::internal::wasm::ModuleDecoderImpl::DecodeSingleFunctionForTesting(), v8::internal::wasm::ModuleDecoderImpl::TypeKindName(), and v8::internal::wasm::WasmModuleBuilder::WriteTo().
kWasmI16
constexpr IndependentValueType v8::internal::wasm::kWasmI16 {NumericKind::kI16} [constexpr]
Definition at line 1249 of file value-type.h.
Referenced by v8::internal::wasm::TypeCanonicalizer::AddPredefinedArrayTypes(), v8::internal::wasm::ModuleDecoderImpl::consume_storage_type(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeAtomicOpcode(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeStringRefOpcode(), v8::internal::wasm::fuzzing::GenerateRandomWasmModule(), v8::internal::wasm::fuzzing::GenerateWasmModuleForDeopt(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GetValueTypeHelper(), v8::internal::wasm::WasmValue::Packed(), and v8::internal::compiler::WasmLoadElimination::TruncateAndExtendOrType().
kWasmI31Ref
constexpr IndependentHeapType v8::internal::wasm::kWasmI31Ref {GenericKind::kI31} [constexpr]
Definition at line 1265 of file value-type.h.
Referenced by v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::AssertNotNull(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeGCOpcode(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateInitExpr(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GenerateRef(), v8::anonymous_namespace{wasm-js.cc}::GetValueType(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GetValueTypeHelper(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::i31_get(), v8::internal::compiler::WasmGCLowering::ReduceAssertNotNull(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCastAbstract(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ReduceWasmTypeCastAbstract(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ReduceWasmTypeCastRtt(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheck(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheckAbstract(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ReduceWasmTypeCheckAbstract(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ReduceWasmTypeCheckRtt(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableImpl().
kWasmI32
constexpr IndependentValueType v8::internal::wasm::kWasmI32 {NumericKind::kI32} [constexpr]
Definition at line 1243 of file value-type.h.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::AddImportedStringImports(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_copy(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_fill(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_get_helper(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_init_data(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_init_elem(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_set(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayAtomicRMW(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ArrayLength(), v8::internal::wasm::TurboshaftGraphBuildingInterface::AtomicOp(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::br_if(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::br_table(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildChangeEndiannessStore(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::CheckForWellKnownImport(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::CompareWithNormalizedCType(), v8::internal::compiler::AccessInfoFactory::ComputeElementAccessInfo(), v8::internal::wasm::ModuleDecoderImpl::consume_data_segment_header(), v8::internal::wasm::ModuleDecoderImpl::consume_element_segment_header(), v8::internal::wasm::ModuleDecoderImpl::consume_init_expr(), v8::internal::wasm::AsmJsParser::ConvertSignature(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeAtomicOpcode(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeGCOpcode(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeNumericOpcode(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeSimdOpcode(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeStringEncodeWtf8(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeStringEncodeWtf8Array(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeStringMeasureWtf8(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeStringNewWtf8(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeStringNewWtf8Array(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeStringRefOpcode(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeStringViewWtf8Encode(), v8::internal::wasm::WasmBytecodeGenerator::DoEncodeSuperInstruction(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::finite_loop(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateInitExpr(), v8::internal::wasm::fuzzing::GenerateRandomWasmModule(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GenerateRef(), v8::internal::wasm::fuzzing::GenerateWasmModuleForRevec(), GetI32Sig(), v8::internal::wasm::DebugInfoImpl::GetValue(), v8::anonymous_namespace{wasm-js.cc}::GetValueType(), v8::internal::wasm::WasmBytecodeGenerator::I32Push(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::if_(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::IsDataViewGetterSig(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::IsDataViewSetterSig(), v8::internal::wasm::InstanceBuilder::LoadDataSegments(), v8::internal::wasm::InstanceBuilder::LoadTableSegments(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::MemoryAddressType(), v8::internal::wasm::TurboshaftGraphBuildingInterface::MemoryInit(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::new_object(), v8::internal::wasm::WasmValue::Packed(), v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::ParseArrayLen(), v8::internal::wasm::ModuleDisassembler::PrintModule(), v8::internal::wasm::InstanceBuilder::ProcessImportedGlobal(), v8::internal::wasm::value_type_reader::read_value_type(), v8::internal::compiler::WasmGCOperatorReducer::ReduceCheckNull(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCastAbstract(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCheck(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCheckAbstract(), v8::internal::RUNTIME_FUNCTION(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::string_charcodeat(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::string_codepointat(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::string_fromcharcode(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::string_fromcharcodearray(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::string_fromcodepoint(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::string_fromutf8array(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::string_intocharcodearray(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::string_intoutf8array(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::string_substring(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::table_address_type(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::table_copy(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::TableAddressType(), ValidateAndSetBuiltinImports(), v8::internal::wasm::AsmJsParser::ValidateFunction(), v8::internal::wasm::AsmJsParser::ValidateFunctionLocals(), v8::internal::wasm::AsmJsParser::ValidateModuleVar(), v8::internal::wasm::AsmJsParser::ValidateModuleVarImport(), value_type< int32_t >(), value_type< uint32_t >(), wasm::anonymous_namespace{c-api.cc}::WasmValKindToV8(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::WellKnown_FastApi().
kWasmI64
constexpr IndependentValueType v8::internal::wasm::kWasmI64 {NumericKind::kI64} [constexpr]
Definition at line 1244 of file value-type.h.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayAtomicCompareExchange(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayAtomicRMW(), v8::internal::wasm::liftoff::AtomicAddOrSubOrExchange32(), v8::internal::wasm::liftoff::AtomicBinop32(), v8::internal::wasm::TurboshaftGraphBuildingInterface::AtomicOp(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildChangeEndiannessStore(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::CheckForWellKnownImport(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::CompareWithNormalizedCType(), v8::internal::wasm::ModuleDecoderImpl::consume_data_segment_header(), v8::internal::wasm::ModuleDecoderImpl::consume_element_segment_header(), v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::ContainsInt64(), v8::internal::CreateWasmObject(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeAtomicOpcode(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeSimdOpcode(), v8::internal::wasm::WasmBytecodeGenerator::DoEncodeSuperInstruction(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateInitExpr(), v8::internal::wasm::fuzzing::GenerateWasmModuleForRevec(), GetI32Sig(), v8::internal::wasm::DebugInfoImpl::GetValue(), v8::anonymous_namespace{wasm-js.cc}::GetValueType(), v8::internal::wasm::WasmBytecodeGenerator::I64Push(), v8::internal::wasm::InstanceBuilder::LoadDataSegments(), v8::internal::wasm::liftoff::LoadInternal(), v8::internal::wasm::TurboshaftGraphBuildingInterface::LoadMem(), v8::internal::wasm::InstanceBuilder::LoadTableSegments(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::MemoryAddressType(), v8::internal::wasm::ModuleDisassembler::PrintModule(), v8::internal::wasm::InstanceBuilder::ProcessImportedGlobal(), v8::internal::wasm::value_type_reader::read_value_type(), v8::internal::RUNTIME_FUNCTION(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StoreInStackSlot(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StoreMem(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::StructAtomicRMW(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::StructGet(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::StructSet(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::table_address_type(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::TableAddressType(), value_type< int64_t >(), value_type< uint64_t >(), wasm::anonymous_namespace{c-api.cc}::WasmValKindToV8(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::WellKnown_FastApi().
kWasmI8
constexpr IndependentValueType v8::internal::wasm::kWasmI8 {NumericKind::kI8} [constexpr]
Definition at line 1248 of file value-type.h.
Referenced by v8::internal::wasm::TypeCanonicalizer::AddPredefinedArrayTypes(), v8::internal::wasm::ModuleDecoderImpl::consume_storage_type(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeAtomicOpcode(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeStringEncodeWtf8Array(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeStringNewWtf8Array(), v8::internal::wasm::fuzzing::GenerateRandomWasmModule(), v8::internal::wasm::fuzzing::GenerateWasmModuleForDeopt(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GetValueTypeHelper(), v8::internal::wasm::WasmValue::Packed(), v8::internal::RUNTIME_FUNCTION(), and v8::internal::compiler::WasmLoadElimination::TruncateAndExtendOrType().
kWasmInstanceDataParameterIndex
constexpr int v8::internal::wasm::kWasmInstanceDataParameterIndex = 0 [constexpr]
Definition at line 144 of file wasm-linkage.h.
Referenced by v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::Param(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessParameter(), v8::internal::compiler::WasmGraphBuilder::Start(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StartFunction(), v8::internal::compiler::turboshaft::WasmInJSInliningReducer< Next >::TryInlineWasmCall(), and v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::WasmIntoJSInlinerImpl().
kWasmMagic
constexpr uint32_t v8::internal::wasm::kWasmMagic = 0x6d736100 [constexpr]
Definition at line 22 of file wasm-constants.h.
Referenced by v8::internal::wasm::ModuleDecoderImpl::DecodeModuleHeader(), and v8::internal::wasm::WasmModuleBuilder::WriteTo().
kWasmMaxHeapOffset
constexpr uint64_t v8::internal::wasm::kWasmMaxHeapOffset [constexpr]
Initial value:
=
    static_cast<uint64_t>(
        std::numeric_limits<uint32_t>::max())
    + std::numeric_limits<uint32_t>::max()
Definition at line 81 of file wasm-limits.h.
kWasmNullContRef
constexpr IndependentHeapType v8::internal::wasm::kWasmNullContRef {GenericKind::kNoCont} [constexpr]
Definition at line 1287 of file value-type.h.
Referenced by v8::internal::wasm::value_type_reader::read_value_type().
kWasmNullExnRef
constexpr IndependentHeapType v8::internal::wasm::kWasmNullExnRef {GenericKind::kNoExn} [constexpr]
Definition at line 1284 of file value-type.h.
Referenced by v8::internal::wasm::value_type_reader::read_value_type().
kWasmNullExternRef
constexpr IndependentHeapType v8::internal::wasm::kWasmNullExternRef {GenericKind::kNoExtern} [constexpr]
Definition at line 1283 of file value-type.h.
Referenced by v8::internal::wasm::WasmInterpreterRuntime::GetNullValue(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GetValueTypeHelper(), v8::internal::wasm::WasmInterpreterRuntime::InitializeRefLocalsRefs(), v8::internal::wasm::WasmInterpreterRuntime::IsNull(), v8::internal::RUNTIME_FUNCTION(), and v8::internal::wasm::WasmInterpreterRuntime::SubtypeCheck().
kWasmNullFuncRef
constexpr IndependentHeapType v8::internal::wasm::kWasmNullFuncRef {GenericKind::kNoFunc} [constexpr]
Definition at line 1285 of file value-type.h.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GetValueTypeHelper().
kWasmNullRef
constexpr IndependentHeapType v8::internal::wasm::kWasmNullRef {GenericKind::kNone} [constexpr]
Definition at line 1282 of file value-type.h.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GetValueTypeHelper(), v8::internal::compiler::WasmTyper::Reduce(), v8::internal::compiler::WasmGCLowering::ReduceWasmAnyConvertExtern(), v8::internal::compiler::WasmLoadElimination::ReduceWasmStructGet(), and v8::internal::compiler::WasmLoadElimination::ReduceWasmStructSet().
kWasmPageSize
constexpr size_t v8::internal::wasm::kWasmPageSize = 0x10000 [constexpr]
Definition at line 179 of file wasm-constants.h.
Referenced by v8::internal::wasm::InstanceBuilder::Build_Phase1(), v8::internal::WasmMemoryObject::FixUpResizableArrayBuffer(), v8::internal::WasmMemoryObject::Grow(), max_mem32_bytes(), max_mem32_pages(), max_mem64_bytes(), max_mem64_pages(), v8::internal::wasm::WasmInterpreterRuntime::MemorySize(), v8::internal::WasmMemoryObject::New(), v8::internal::wasm::InstanceBuilder::ProcessImportedMemories(), v8::internal::ResizeHelper(), and UpdateComputedInformation().
kWasmPageSizeLog2
constexpr uint32_t v8::internal::wasm::kWasmPageSizeLog2 = 16 [constexpr]
Definition at line 180 of file wasm-constants.h.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CurrentMemoryPages(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::CurrentMemoryPages().
kWasmRecursiveTypeGroupCode
constexpr uint8_t v8::internal::wasm::kWasmRecursiveTypeGroupCode = 0x4e [constexpr]
Definition at line 73 of file wasm-constants.h.
Referenced by v8::internal::wasm::ModuleDecoderImpl::DecodeTypeSection(), and v8::internal::wasm::WasmModuleBuilder::WriteTo().
kWasmRefExtern
constexpr IndependentHeapType v8::internal::wasm::kWasmRefExtern [constexpr]
Initial value:
{GenericKind::kExtern,
                                             kNonNullable}
Definition at line 1261 of file value-type.h.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::AddImportedStringImports(), and ValidateAndSetBuiltinImports().
kWasmRefExternString
constexpr IndependentHeapType v8::internal::wasm::kWasmRefExternString [constexpr]
Initial value:
{GenericKind::kExternString,
                                                   kNonNullable}
Definition at line 1274 of file value-type.h.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::AnnotateAsString(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ExternRefToString(), v8::internal::wasm::TurboshaftGraphBuildingInterface::HandleWellKnownImport(), v8::internal::wasm::TurboshaftGraphBuildingInterface::IsExplicitStringCast(), v8::internal::wasm::TurboshaftGraphBuildingInterface::IsExternRefString(), and v8::internal::compiler::WasmGraphBuilder::SetType().
kWasmRefI31
constexpr IndependentHeapType v8::internal::wasm::kWasmRefI31 {GenericKind::kI31, kNonNullable} [constexpr]
Definition at line 1266 of file value-type.h.
Referenced by v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::RefAsNonNull(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SubtypeCheck(), and v8::internal::wasm::WasmInterpreterRuntime::SubtypeCheck().
kWasmRefNullExternString
constexpr IndependentHeapType v8::internal::wasm::kWasmRefNullExternString [constexpr]
Initial value:
{
    GenericKind::kExternString}
Definition at line 1272 of file value-type.h.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::ExternRefToString().
kWasmRefString
constexpr IndependentHeapType v8::internal::wasm::kWasmRefString [constexpr]
Initial value:
{GenericKind::kString,
                                             kNonNullable}
Definition at line 1270 of file value-type.h.
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeStringRefOpcode(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::HandleWellKnownImport().
kWasmS128
constexpr IndependentValueType v8::internal::wasm::kWasmS128 {NumericKind::kS128} [constexpr]
Definition at line 1247 of file value-type.h.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayFillImpl(), v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::ContainsSimd(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeLoadLane(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeLoadTransformMem(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeStoreLane(), v8::internal::wasm::fuzzing::GenerateWasmModuleForRevec(), v8::internal::wasm::DebugInfoImpl::GetValue(), v8::anonymous_namespace{wasm-js.cc}::GetValueType(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GetValueTypeHelper(), IsJSCompatibleSignature(), v8::internal::wasm::InstanceBuilder::ProcessImportedGlobal(), v8::internal::wasm::InstanceBuilder::ProcessImportedWasmGlobalObject(), v8::internal::wasm::value_type_reader::read_value_type(), v8::internal::RUNTIME_FUNCTION(), v8::internal::wasm::WasmBytecodeGenerator::S128Push(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Simd8x16ShuffleOp(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::SimdConstOp(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::SimdExtractLane(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::SimdReplaceLane(), and value_type< Simd128 >().
kWasmSharedAnyRef
constexpr IndependentHeapType v8::internal::wasm::kWasmSharedAnyRef [constexpr]
Initial value:
{GenericKind::kAny, kNullable,
                                                true}
Definition at line 1258 of file value-type.h.
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeAtomicOpcode().
kWasmStringRef
constexpr IndependentHeapType v8::internal::wasm::kWasmStringRef {GenericKind::kString} [constexpr]
Definition at line 1269 of file value-type.h.
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeStringEncodeWtf8(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeStringEncodeWtf8Array(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeStringMeasureWtf8(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeStringNewWtf8(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeStringNewWtf8Array(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeStringRefOpcode(), v8::anonymous_namespace{wasm-js.cc}::GetValueType(), v8::internal::wasm::value_type_reader::read_value_type(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringEq(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableImpl().
kWasmStringViewIter
constexpr IndependentHeapType v8::internal::wasm::kWasmStringViewIter [constexpr]
Initial value:
{GenericKind::kStringViewIter,
                                                  kNonNullable}
Definition at line 1280 of file value-type.h.
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeStringRefOpcode().
kWasmStringViewWtf16
constexpr IndependentHeapType v8::internal::wasm::kWasmStringViewWtf16 [constexpr]
Initial value:
{
    GenericKind::kStringViewWtf16, kNonNullable}
Definition at line 1278 of file value-type.h.
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeStringRefOpcode().
kWasmStringViewWtf8
constexpr IndependentHeapType v8::internal::wasm::kWasmStringViewWtf8 [constexpr]
Initial value:
{GenericKind::kStringViewWtf8,
                                                  kNonNullable}
Definition at line 1276 of file value-type.h.
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeStringRefOpcode(), and v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeStringViewWtf8Encode().
kWasmStructRef
constexpr IndependentHeapType v8::internal::wasm::kWasmStructRef {GenericKind::kStruct} [constexpr]
Definition at line 1267 of file value-type.h.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateInitExpr(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GenerateRef(), v8::anonymous_namespace{wasm-js.cc}::GetValueType(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GetValueTypeHelper(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessAllocateStruct(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableImpl().
kWasmStructTypeCode
constexpr uint8_t v8::internal::wasm::kWasmStructTypeCode = 0x5f [constexpr]
Definition at line 68 of file wasm-constants.h.
Referenced by v8::internal::wasm::ModuleDecoderImpl::consume_base_type_definition(), v8::internal::wasm::ModuleDecoderImpl::TypeKindName(), and v8::internal::wasm::WasmModuleBuilder::WriteTo().
kWasmSubtypeCode
constexpr uint8_t v8::internal::wasm::kWasmSubtypeCode = 0x50 [constexpr]
Definition at line 71 of file wasm-constants.h.
Referenced by v8::internal::wasm::ModuleDecoderImpl::consume_subtype_definition(), and v8::internal::wasm::WasmModuleBuilder::WriteTo().
kWasmSubtypeFinalCode
constexpr uint8_t v8::internal::wasm::kWasmSubtypeFinalCode = 0x4f [constexpr]
Definition at line 72 of file wasm-constants.h.
Referenced by v8::internal::wasm::ModuleDecoderImpl::consume_subtype_definition(), and v8::internal::wasm::WasmModuleBuilder::WriteTo().
kWasmTop
constexpr IndependentHeapType v8::internal::wasm::kWasmTop {GenericKind::kTop} [constexpr]
Definition at line 1253 of file value-type.h.
Referenced by v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::CommonAncestor(), v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::CommonAncestorWithAbstract(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GetRandomLocal(), Intersection(), and Union().
kWasmVersion
constexpr uint32_t v8::internal::wasm::kWasmVersion = 0x01 [constexpr]
Definition at line 23 of file wasm-constants.h.
Referenced by v8::internal::wasm::ModuleDecoderImpl::DecodeModuleHeader(), and v8::internal::wasm::WasmModuleBuilder::WriteTo().
kWasmVoid
constexpr IndependentHeapType v8::internal::wasm::kWasmVoid {GenericKind::kVoid, kNonNullable} [constexpr]
Definition at line 1251 of file value-type.h.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::BlockScope::BlockScope(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::br_table(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::BuildSimpleOperator(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::call(), v8::internal::wasm::ConstantExpressionInterface::computed_value(), v8::internal::wasm::WasmBytecodeGenerator::DecodeInstruction(), v8::internal::wasm::ConstantExpressionInterface::error(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::finite_loop(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::Generate(), v8::internal::wasm::WasmBytecodeGenerator::GetReturnType(), v8::anonymous_namespace{wasm-js.cc}::GetValueType(), v8::internal::wasm::WasmBytecodeGenerator::HasVoidSignature(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::Var::is_valid(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::ParseBrOnCast(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PopDescriptor(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Push(), v8::internal::wasm::WasmBytecodeGenerator::ReserveBlockSlots(), v8::internal::wasm::WasmBytecodeGenerator::ReturnsCount(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::shift_locals(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyFunction(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyGlobalImpl(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTagImpl().
s_unwind_code
InstructionHandler v8::internal::wasm::s_unwind_code = InstructionHandler::k_s2s_Unwind
Definition at line 751 of file wasm-interpreter.cc.
Referenced by v8::internal::wasm::anonymous_namespace{wasm-interpreter-runtime.cc}::RedirectCodeToUnwindHandler().
stack_bias
constexpr int v8::internal::wasm::stack_bias = 0 [constexpr]
Definition at line 1226 of file liftoff-assembler-ppc-inl.h.