v8::internal::anonymous_namespace{builtins-typed-array.cc} Namespace Reference
Functions
int64_t CapRelativeIndex (double relative, int64_t minimum, int64_t maximum)
std::vector< std::tuple< const char *, size_t, simdutf::base64_options > > SimdutfBase64OptionsVector ()
std::vector< std::tuple< const char *, size_t, simdutf::last_chunk_handling_options > > SimdutfLastChunkHandlingOptionsVector ()
template<typename T >
Maybe< T > MapOptionToEnum (Isolate *isolate, DirectHandle< String > option_string, const std::vector< std::tuple< const char *, size_t, T >> &allowed_options)
Maybe< std::pair< simdutf::base64_options, simdutf::last_chunk_handling_options > > HandleOptionsBag (Isolate *isolate, DirectHandle< Object > options)
MessageTemplate ToMessageTemplate (simdutf::error_code error)
template<typename T >
std::unique_ptr< char[]> ArrayBufferFromBase64 (T input_vector, size_t input_length, simdutf::base64_options alphabet, simdutf::last_chunk_handling_options last_chunk_handling, simdutf::result &simd_result, size_t &output_length)
template<typename T >
simdutf::result ArrayBufferSetFromBase64 (T input_vector, size_t input_length, size_t array_length, simdutf::base64_options alphabet, simdutf::last_chunk_handling_options last_chunk_handling, DirectHandle< JSTypedArray > typed_array, size_t &output_length)
Function Documentation
ArrayBufferFromBase64()
template<typename T >
std::unique_ptr<char[]> v8::internal::anonymous_namespace{builtins-typed-array.cc}::ArrayBufferFromBase64 (T input_vector, size_t input_length, simdutf::base64_options alphabet, simdutf::last_chunk_handling_options last_chunk_handling, simdutf::result & simd_result, size_t & output_length)
Definition at line 484 of file builtins-typed-array.cc.
                                                       {
  output_length = simdutf::maximal_binary_length_from_base64(
      reinterpret_cast<const T>(input_vector), input_length);
  std::unique_ptr<char[]> output = std::make_unique<char[]>(output_length);
  simd_result = simdutf::base64_to_binary_safe(
      reinterpret_cast<const T>(input_vector), input_length, output.get(),
      output_length, alphabet, last_chunk_handling,
      /*decode_up_to_bad_char*/ true);
  return output;
}
Referenced by v8::internal::BUILTIN().
ArrayBufferSetFromBase64()
template<typename T >
simdutf::result v8::internal::anonymous_namespace{builtins-typed-array.cc}::ArrayBufferSetFromBase64 (T input_vector, size_t input_length, size_t array_length, simdutf::base64_options alphabet, simdutf::last_chunk_handling_options last_chunk_handling, DirectHandle< JSTypedArray > typed_array, size_t & output_length)
Definition at line 500 of file builtins-typed-array.cc.
                                                                   {
  output_length = array_length;
  simdutf::result simd_result;
  if (typed_array->buffer()->is_shared()) {
    simd_result = simdutf::atomic_base64_to_binary_safe(
        reinterpret_cast<const T>(input_vector), input_length,
        reinterpret_cast<char*>(typed_array->DataPtr()), output_length,
        alphabet, last_chunk_handling, /*decode_up_to_bad_char*/ true);
  } else {
    simd_result = simdutf::base64_to_binary_safe(
        reinterpret_cast<const T>(input_vector), input_length,
        reinterpret_cast<char*>(typed_array->DataPtr()), output_length,
        alphabet, last_chunk_handling, /*decode_up_to_bad_char*/ true);
  }
  return simd_result;
}
References v8::base::internal::result.
Referenced by v8::internal::BUILTIN().
CapRelativeIndex()
int64_t v8::internal::anonymous_namespace{builtins-typed-array.cc}::CapRelativeIndex (double relative, int64_t minimum, int64_t maximum)
Definition at line 33 of file builtins-typed-array.cc.
                                                                            {
  DCHECK(!std::isnan(relative));
  return static_cast<int64_t>(
      relative < 0 ? std::max<double>(relative + maximum, minimum)
                   : std::min<double>(relative, maximum));
}
References v8::internal::DCHECK().
Referenced by v8::internal::BUILTIN().
HandleOptionsBag()
Maybe<std::pair<simdutf::base64_options, simdutf::last_chunk_handling_options> > v8::internal::anonymous_namespace{builtins-typed-array.cc}::HandleOptionsBag (Isolate * isolate, DirectHandle< Object > options)
Definition at line 405 of file builtins-typed-array.cc.
                                                                 {
  simdutf::base64_options alphabet;
  simdutf::last_chunk_handling_options last_chunk_handling;
  // 1. Let alphabet be ? Get(opts, "alphabet").
  DirectHandle<Object> opt_alphabet;
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, opt_alphabet,
      JSObject::ReadFromOptionsBag(
          options, isolate->factory()->alphabet_string(), isolate),
      (Nothing<std::pair<simdutf::base64_options,
                         simdutf::last_chunk_handling_options>>()));
  // 2. If alphabet is undefined, set alphabet to "base64".
  if (IsUndefined(*opt_alphabet)) {
    alphabet = simdutf::base64_default;
  } else if (!IsString(*opt_alphabet)) {
    isolate->Throw(*isolate->factory()->NewTypeError(
        MessageTemplate::kInvalidOption, opt_alphabet));
    return Nothing<std::pair<simdutf::base64_options,
                             simdutf::last_chunk_handling_options>>();
  } else {
    // 3. If alphabet is neither "base64" nor "base64url", throw a TypeError
    // exception.
    DirectHandle<String> alphabet_string = Cast<String>(opt_alphabet);
    MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
        isolate, alphabet,
        MapOptionToEnum(isolate, alphabet_string, SimdutfBase64OptionsVector()),
        (Nothing<std::pair<simdutf::base64_options,
                           simdutf::last_chunk_handling_options>>()));
  }
  // 4. Let lastChunkHandling be ? Get(opts, "lastChunkHandling").
  DirectHandle<Object> opt_last_chunk_handling;
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, opt_last_chunk_handling,
      JSObject::ReadFromOptionsBag(
          options, isolate->factory()->last_chunk_handling_string(), isolate),
      (Nothing<std::pair<simdutf::base64_options,
                         simdutf::last_chunk_handling_options>>()));
  // 5. If lastChunkHandling is undefined, set lastChunkHandling to "loose".
  if (IsUndefined(*opt_last_chunk_handling)) {
    last_chunk_handling = simdutf::last_chunk_handling_options::loose;
  } else if (!IsString(*opt_last_chunk_handling)) {
    isolate->Throw(*isolate->factory()->NewTypeError(
        MessageTemplate::kInvalidOption, opt_last_chunk_handling));
    return Nothing<std::pair<simdutf::base64_options,
                             simdutf::last_chunk_handling_options>>();
  } else {
    // 6. If lastChunkHandling is not one of "loose", "strict", or
    // "stop-before-partial", throw a TypeError exception.
    DirectHandle<String> last_chunk_handling_string =
        Cast<String>(opt_last_chunk_handling);
    MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
        isolate, last_chunk_handling,
        MapOptionToEnum(isolate, last_chunk_handling_string,
                        SimdutfLastChunkHandlingOptionsVector()),
        (Nothing<std::pair<simdutf::base64_options,
                           simdutf::last_chunk_handling_options>>()));
  }
  return Just(std::make_pair(alphabet, last_chunk_handling));
}
References ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::Isolate::factory(), v8::Just(), MapOptionToEnum(), MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::Nothing(), v8::internal::JSObject::ReadFromOptionsBag(), SimdutfBase64OptionsVector(), SimdutfLastChunkHandlingOptionsVector(), and v8::internal::Isolate::Throw().
Referenced by v8::internal::BUILTIN().
MapOptionToEnum()
template<typename T >
Maybe<T> v8::internal::anonymous_namespace{builtins-typed-array.cc}::MapOptionToEnum (Isolate * isolate, DirectHandle< String > option_string, const std::vector< std::tuple< const char *, size_t, T >> & allowed_options)
Definition at line 365 of file builtins-typed-array.cc.
                                                                        {
  option_string = String::Flatten(isolate, option_string);
  {
    DisallowGarbageCollection no_gc;
    String::FlatContent option_content = option_string->GetFlatContent(no_gc);
    if (option_content.IsOneByte()) {
      const unsigned char* option_string_to_compare =
          option_content.ToOneByteVector().data();
      size_t length = option_content.ToOneByteVector().size();
      for (auto& [str_val, str_size, enum_val] : allowed_options) {
        if (str_size == length &&
            CompareCharsEqual(option_string_to_compare, str_val, str_size)) {
          return Just<T>(enum_val);
        }
      }
    } else {
      const base::uc16* option_string_to_compare =
          option_content.ToUC16Vector().data();
      size_t length = option_content.ToUC16Vector().size();
      for (auto& [str_val, str_size, enum_val] : allowed_options) {
        if (str_size == length &&
            CompareCharsEqual(option_string_to_compare, str_val, str_size)) {
          return Just<T>(enum_val);
        }
      }
    }
  }
  isolate->Throw(*isolate->factory()->NewTypeError(
      MessageTemplate::kInvalidOption, option_string));
  return Nothing<T>();
}
References v8::internal::CompareCharsEqual(), v8::base::Vector< T >::data(), v8::internal::Isolate::factory(), v8::internal::String::FlatContent::IsOneByte(), v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::Vector< T >::size(), v8::internal::Isolate::Throw(), v8::internal::String::FlatContent::ToOneByteVector(), and v8::internal::String::FlatContent::ToUC16Vector().
Referenced by v8::internal::BUILTIN(), and HandleOptionsBag().
SimdutfBase64OptionsVector()
std::vector<std::tuple<const char*, size_t, simdutf::base64_options> > v8::internal::anonymous_namespace{builtins-typed-array.cc}::SimdutfBase64OptionsVector ()
Definition at line 350 of file builtins-typed-array.cc.
                             {
  return {{"base64", 6, simdutf::base64_options::base64_default},
          {"base64url", 9, simdutf::base64_options::base64_url}};
}
Referenced by v8::internal::BUILTIN(), and HandleOptionsBag().
SimdutfLastChunkHandlingOptionsVector()
std::vector< std::tuple<const char*, size_t, simdutf::last_chunk_handling_options> > v8::internal::anonymous_namespace{builtins-typed-array.cc}::SimdutfLastChunkHandlingOptionsVector ()
Definition at line 357 of file builtins-typed-array.cc.
                                        {
  return {{"loose", 5, simdutf::last_chunk_handling_options::loose},
          {"strict", 6, simdutf::last_chunk_handling_options::strict},
          {"stop-before-partial", 19,
           simdutf::last_chunk_handling_options::stop_before_partial}};
}
Referenced by HandleOptionsBag().
ToMessageTemplate()
MessageTemplate v8::internal::anonymous_namespace{builtins-typed-array.cc}::ToMessageTemplate (simdutf::error_code error)
Definition at line 470 of file builtins-typed-array.cc.
                                                           {
  switch (error) {
    case simdutf::error_code::INVALID_BASE64_CHARACTER:
      return MessageTemplate::kInvalidBase64Character;
    case simdutf::error_code::BASE64_INPUT_REMAINDER:
      return MessageTemplate::kBase64InputRemainder;
    case simdutf::error_code::BASE64_EXTRA_BITS:
      return MessageTemplate::kBase64ExtraBits;
    default:
      UNREACHABLE();
  }
}
References v8::internal::UNREACHABLE().
Referenced by v8::internal::BUILTIN().