v8::internal::anonymous_namespace{heap-write-barrier.cc} Namespace Reference
Enumerations
enum RangeWriteBarrierMode { kDoGenerationalOrShared = 1 << 0
, kDoMarking = 1 << 1
, kDoEvacuationSlotRecording = 1 << 2
 }
Functions
template<int kModeMask, typename TSlot >
void ForRangeImpl (Heap *heap, MemoryChunk *source_chunk, Tagged< HeapObject > object, TSlot start_slot, TSlot end_slot)
Variables
thread_local MarkingBarrier * current_marking_barrier = nullptr
Enumeration Type Documentation
RangeWriteBarrierMode
enum v8::internal::anonymous_namespace{heap-write-barrier.cc}::RangeWriteBarrierMode
Enumerator
kDoGenerationalOrShared
kDoMarking
kDoEvacuationSlotRecording
Definition at line 397 of file heap-write-barrier.cc.
                           {
  kDoGenerationalOrShared = 1 << 0,
  kDoMarking = 1 << 1,
  kDoEvacuationSlotRecording = 1 << 2,
};
Function Documentation
ForRangeImpl()
template<int kModeMask, typename TSlot >
void v8::internal::anonymous_namespace{heap-write-barrier.cc}::ForRangeImpl (Heap * heap, MemoryChunk * source_chunk, Tagged< HeapObject > object, TSlot start_slot, TSlot end_slot)
Definition at line 404 of file heap-write-barrier.cc.
                                                                               {
  // At least one of generational or marking write barrier should be requested.
  static_assert(kModeMask & (kDoGenerationalOrShared | kDoMarking));
  // kDoEvacuationSlotRecording implies kDoMarking.
  static_assert(!(kModeMask & kDoEvacuationSlotRecording) ||
                (kModeMask & kDoMarking));
  MarkingBarrier* marking_barrier = nullptr;
  static constexpr Tagged_t kPageMask =
      ~static_cast<Tagged_t>(PageMetadata::kPageSize - 1);
  Tagged_t cached_uninteresting_page =
      static_cast<Tagged_t>(heap->read_only_space()->FirstPageAddress()) &
      kPageMask;
  if (kModeMask & kDoMarking) {
    marking_barrier = WriteBarrier::CurrentMarkingBarrier(object);
  }
  MarkCompactCollector* collector = heap->mark_compact_collector();
  MutablePageMetadata* source_page_metadata =
      MutablePageMetadata::cast(source_chunk->Metadata());
  for (TSlot slot = start_slot; slot < end_slot; ++slot) {
    // If we *only* need the generational or shared WB, we can skip objects
    // residing on uninteresting pages.
    Tagged_t compressed_page;
    if (kModeMask == kDoGenerationalOrShared) {
      Tagged_t tagged_value = *slot.location();
      if (HAS_SMI_TAG(tagged_value)) continue;
      compressed_page = tagged_value & kPageMask;
      if (compressed_page == cached_uninteresting_page) {
#if DEBUG
        typename TSlot::TObject value = *slot;
        Tagged<HeapObject> value_heap_object;
        if (value.GetHeapObject(&value_heap_object)) {
          CHECK(!HeapLayout::InYoungGeneration(value_heap_object));
          CHECK(!HeapLayout::InWritableSharedSpace(value_heap_object));
        }
#endif // DEBUG
        continue;
      }
      // Fall through to decompressing the pointer and fetching its actual
      // page header flags.
    }
    typename TSlot::TObject value = *slot;
    Tagged<HeapObject> value_heap_object;
    if (!value.GetHeapObject(&value_heap_object)) continue;
    if (kModeMask & kDoGenerationalOrShared) {
      if (HeapLayout::InYoungGeneration(value_heap_object)) {
        RememberedSet<OLD_TO_NEW>::Insert<AccessMode::NON_ATOMIC>(
            source_page_metadata, source_chunk->Offset(slot.address()));
      } else if (HeapLayout::InWritableSharedSpace(value_heap_object)) {
        RememberedSet<OLD_TO_SHARED>::Insert<AccessMode::ATOMIC>(
            source_page_metadata, source_chunk->Offset(slot.address()));
      } else if (kModeMask == kDoGenerationalOrShared) {
        cached_uninteresting_page = compressed_page;
      }
    }
    if (kModeMask & kDoMarking) {
      marking_barrier->MarkValue(object, value_heap_object);
      if (kModeMask & kDoEvacuationSlotRecording) {
        collector->RecordSlot(source_chunk, HeapObjectSlot(slot),
                              value_heap_object);
      }
    }
  }
}
References v8::internal::MutablePageMetadata::cast(), CHECK, v8::internal::WriteBarrier::CurrentMarkingBarrier(), HAS_SMI_TAG, v8::internal::HeapLayout::InWritableSharedSpace(), v8::internal::HeapLayout::InYoungGeneration(), kDoEvacuationSlotRecording, kDoGenerationalOrShared, kDoMarking, v8::internal::MutablePageMetadata::kPageSize, v8::internal::MarkingBarrier::MarkValue(), v8::internal::MemoryChunk::Metadata(), v8::internal::MemoryChunk::Offset(), v8::internal::MarkCompactCollector::RecordSlot(), and v8::internal::value.
Referenced by v8::internal::WriteBarrier::ForRange().
Variable Documentation
current_marking_barrier
thread_local MarkingBarrier* v8::internal::anonymous_namespace{heap-write-barrier.cc}::current_marking_barrier = nullptr
Definition at line 23 of file heap-write-barrier.cc.
Referenced by v8::internal::WriteBarrier::CurrentMarkingBarrier(), and v8::internal::WriteBarrier::SetForThread().