v8::internal::compiler::anonymous_namespace{revectorizer.cc} Namespace Reference
Classes
class EffectChainIterator
Functions
bool IsSupportedLoad (const Node *node)
int64_t GetConstantValue (const Node *node)
int64_t GetMemoryOffsetValue (const Node *node)
Node * GetNodeAddress (const Node *node)
bool IsContinuousAccess (const ZoneVector< Node * > &node_group)
bool AllConstant (const ZoneVector< Node * > &node_group)
bool AllSameAddress (const ZoneVector< Node * > &nodes)
template<typename T >
bool IsSplat (const T &node_group)
static bool OperatorCanBePacked (const Operator *lhs, const Operator *rhs)
bool AllPackableOperator (const ZoneVector< Node * > &node_group)
bool ShiftBySameScalar (const ZoneVector< Node * > &node_group)
bool IsSignExtensionOperation (IrOpcode::Value op)
bool MaybePackSignExtensionOp (const ZoneVector< Node * > &node_group)
void InsertAfter (EffectChainIterator &dest, EffectChainIterator &src)
Function Documentation
AllConstant()
bool v8::internal::compiler::anonymous_namespace{revectorizer.cc}::AllConstant (const ZoneVector< Node * > & node_group)
Definition at line 243 of file revectorizer.cc.
                                                      {
  for (Node* node : node_group) {
    if (!NodeProperties::IsConstant(node)) {
      return false;
    }
  }
  return true;
}
References v8::internal::compiler::NodeProperties::IsConstant().
Referenced by v8::internal::compiler::SLPTree::BuildTreeRec(), and v8::internal::compiler::SLPTree::CanBePacked().
AllPackableOperator()
bool v8::internal::compiler::anonymous_namespace{revectorizer.cc}::AllPackableOperator (const ZoneVector< Node * > & node_group)
Definition at line 287 of file revectorizer.cc.
                                                              {
  auto op = node_group[0]->op();
  for (ZoneVector<Node*>::size_type i = 1; i < node_group.size(); i++) {
    if (!OperatorCanBePacked(node_group[i]->op(), op)) {
      return false;
    }
  }
  return true;
}
References OperatorCanBePacked(), and v8::internal::ZoneVector< T >::size().
Referenced by v8::internal::compiler::SLPTree::BuildTreeRec(), and v8::internal::compiler::SLPTree::CanBePacked().
AllSameAddress()
bool v8::internal::compiler::anonymous_namespace{revectorizer.cc}::AllSameAddress (const ZoneVector< Node * > & nodes)
Definition at line 253 of file revectorizer.cc.
                                                    {
  Node* address = GetNodeAddress(nodes[0]);
  for (size_t i = 1; i < nodes.size(); i++) {
    if (GetNodeAddress(nodes[i]) != address) {
      TRACE("Diff address #%d,#%d!\n", address->id(),
            GetNodeAddress(nodes[i])->id());
      return false;
    }
  }
  return true;
}
References GetNodeAddress(), v8::internal::compiler::Node::id(), v8::internal::ZoneVector< T >::size(), and v8::internal::TRACE().
Referenced by v8::internal::compiler::SLPTree::BuildTreeRec().
GetConstantValue()
int64_t v8::internal::compiler::anonymous_namespace{revectorizer.cc}::GetConstantValue (const Node * node)
Definition at line 176 of file revectorizer.cc.
                                           {
  int64_t value = -1;
  if (node->opcode() == IrOpcode::kInt64Constant) {
    value = OpParameter<int64_t>(node->op());
  }
  return value;
}
References v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), and v8::internal::value.
Referenced by GetMemoryOffsetValue().
GetMemoryOffsetValue()
int64_t v8::internal::compiler::anonymous_namespace{revectorizer.cc}::GetMemoryOffsetValue (const Node * node)
Definition at line 184 of file revectorizer.cc.
                                               {
  DCHECK(IsSupportedLoad(node) || node->opcode() == IrOpcode::kStore ||
         node->opcode() == IrOpcode::kProtectedStore);
  Node* offset = node->InputAt(0);
  if (offset->opcode() == IrOpcode::kLoadFromObject ||
      offset->opcode() == IrOpcode::kLoad) {
    return 0;
  }
  int64_t offset_value = -1;
  if (offset->opcode() == IrOpcode::kInt64Add) {
    if (NodeProperties::IsConstant(offset->InputAt(0))) {
      offset_value = GetConstantValue(offset->InputAt(0));
    } else if (NodeProperties::IsConstant(offset->InputAt(1))) {
      offset_value = GetConstantValue(offset->InputAt(1));
    }
  }
  return offset_value;
}
References v8::internal::DCHECK(), GetConstantValue(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::NodeProperties::IsConstant(), IsSupportedLoad(), and v8::internal::compiler::Node::opcode().
Referenced by v8::internal::compiler::Revectorizer::CollectSeeds(), IsContinuousAccess(), and v8::internal::compiler::MemoryOffsetComparer::operator()().
GetNodeAddress()
Node* v8::internal::compiler::anonymous_namespace{revectorizer.cc}::GetNodeAddress (const Node * node)
Definition at line 209 of file revectorizer.cc.
                                       {
  Node* address = node->InputAt(1);
  // The index is changed to Uint64 for memory32
  if (address->opcode() == IrOpcode::kChangeUint32ToUint64) {
    address = address->InputAt(0);
  }
  return address;
}
References v8::internal::compiler::Node::InputAt(), and v8::internal::compiler::Node::opcode().
Referenced by AllSameAddress(), and v8::internal::compiler::Revectorizer::CollectSeeds().
InsertAfter()
void v8::internal::compiler::anonymous_namespace{revectorizer.cc}::InsertAfter (EffectChainIterator & dest, EffectChainIterator & src)
Definition at line 376 of file revectorizer.cc.
                                                                      {
  Node* dest_next = dest.Next();
  NodeProperties::ReplaceEffectInput(src.Prev(), src.Next());
  NodeProperties::ReplaceEffectInput(*dest, *src);
  NodeProperties::ReplaceEffectInput(*src, dest_next);
}
References v8::internal::compiler::anonymous_namespace{revectorizer.cc}::EffectChainIterator::Next(), v8::internal::compiler::anonymous_namespace{revectorizer.cc}::EffectChainIterator::Prev(), and v8::internal::compiler::NodeProperties::ReplaceEffectInput().
Referenced by v8::internal::compiler::SLPTree::TryReduceLoadChain().
IsContinuousAccess()
bool v8::internal::compiler::anonymous_namespace{revectorizer.cc}::IsContinuousAccess (const ZoneVector< Node * > & node_group)
Definition at line 218 of file revectorizer.cc.
                                                             {
  DCHECK_GT(node_group.size(), 0);
  int64_t previous_offset = GetMemoryOffsetValue(node_group[0]);
  for (size_t i = 1; i < node_group.size(); ++i) {
    int64_t current_offset = GetMemoryOffsetValue(node_group[i]);
    int64_t diff = current_offset - previous_offset;
    if (diff == 8 && node_group[0]->opcode() == IrOpcode::kLoadTransform) {
      LoadTransformParameters params =
          LoadTransformParametersOf(node_group[0]->op());
      if (params.transformation < LoadTransformation::kFirst128Extend ||
          params.transformation > LoadTransformation::kLast128Extend) {
        TRACE("Non-continuous access!\n");
        return false;
      }
      TRACE("Continuous access with load extend offset!\n");
    } else if (diff != kSimd128Size) {
      TRACE("Non-continuous access!\n");
      return false;
    }
    previous_offset = current_offset;
  }
  return true;
}
References DCHECK_GT, GetMemoryOffsetValue(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::kFirst128Extend, v8::internal::compiler::kLast128Extend, v8::internal::kSimd128Size, v8::internal::compiler::LoadTransformParametersOf(), v8::internal::ZoneVector< T >::size(), v8::internal::TRACE(), and v8::internal::compiler::LoadTransformParameters::transformation.
Referenced by v8::internal::compiler::SLPTree::BuildTreeRec(), and v8::internal::compiler::Revectorizer::ReduceStoreChain().
IsSignExtensionOperation()
bool v8::internal::compiler::anonymous_namespace{revectorizer.cc}::IsSignExtensionOperation (IrOpcode::Value op)
Definition at line 309 of file revectorizer.cc.
                                                {
#define CASE(op_low, op_high, not_used) \
  case IrOpcode::k##op_low: \
  case IrOpcode::k##op_high:
  switch (op) {
    SIMD_SIGN_EXTENSION_CONVERT_OP(CASE)
    return true;
    default:
      return false;
  }
#undef CASE
  UNREACHABLE();
}
References CASE, SIMD_SIGN_EXTENSION_CONVERT_OP, and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::SLPTree::CanBePacked().
IsSplat()
template<typename T >
bool v8::internal::compiler::anonymous_namespace{revectorizer.cc}::IsSplat (const T & node_group)
Definition at line 268 of file revectorizer.cc.
                                  {
  for (typename T::size_type i = 1; i < node_group.size(); ++i) {
    if (node_group[i] != node_group[0]) {
      return false;
    }
  }
  return true;
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i.
Referenced by v8::internal::compiler::SLPTree::BuildTreeRec(), v8::internal::compiler::Revectorizer::DecideVectorize(), and v8::internal::compiler::Revectorizer::VectorizeTree().
IsSupportedLoad()
bool v8::internal::compiler::anonymous_namespace{revectorizer.cc}::IsSupportedLoad (const Node * node)
Definition at line 158 of file revectorizer.cc.
                                       {
  if (node->opcode() == IrOpcode::kProtectedLoad ||
      node->opcode() == IrOpcode::kLoad ||
      node->opcode() == IrOpcode::kLoadTransform) {
    return true;
  }
  return false;
}
References v8::internal::compiler::Node::opcode().
Referenced by v8::internal::compiler::SLPTree::BuildTreeRec(), v8::internal::compiler::anonymous_namespace{revectorizer.cc}::EffectChainIterator::EffectInputOf(), GetMemoryOffsetValue(), v8::internal::compiler::SLPTree::IsSideEffectFreeLoad(), and v8::internal::compiler::SLPTree::TryReduceLoadChain().
MaybePackSignExtensionOp()
bool v8::internal::compiler::anonymous_namespace{revectorizer.cc}::MaybePackSignExtensionOp (const ZoneVector< Node * > & node_group)
Definition at line 323 of file revectorizer.cc.
                                                                   {
#define CHECK_SIGN_EXTENSION_CASE(op_low, op_high, not_used) \
  case IrOpcode::k##op_low: { \
    if (node_group[1]->opcode() == IrOpcode::k##op_high && \
        node_group[0]->InputAt(0) == node_group[1]->InputAt(0)) { \
      return true; \
    } \
    return false; \
  }
  switch (node_group[0]->opcode()) {
    SIMD_SIGN_EXTENSION_CONVERT_OP(CHECK_SIGN_EXTENSION_CASE)
    default: {
      return false;
    }
  }
#undef CHECK_SIGN_EXTENSION_CASE
  UNREACHABLE();
}
References CHECK_SIGN_EXTENSION_CASE, SIMD_SIGN_EXTENSION_CONVERT_OP, and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::SLPTree::BuildTreeRec(), and v8::internal::compiler::SLPTree::CanBePacked().
OperatorCanBePacked()
static bool v8::internal::compiler::anonymous_namespace{revectorizer.cc}::OperatorCanBePacked (const Operator * lhs, const Operator * rhs) [inline], [static]
Definition at line 280 of file revectorizer.cc.
                                                               {
  return lhs->opcode() == rhs->opcode() &&
         lhs->properties() == rhs->properties();
}
References v8::internal::compiler::Operator::opcode(), and v8::internal::compiler::Operator::properties().
Referenced by AllPackableOperator().
ShiftBySameScalar()
bool v8::internal::compiler::anonymous_namespace{revectorizer.cc}::ShiftBySameScalar (const ZoneVector< Node * > & node_group)
Definition at line 297 of file revectorizer.cc.
                                                            {
  auto node0 = node_group[0];
  for (ZoneVector<Node*>::size_type i = 1; i < node_group.size(); i++) {
    DCHECK_EQ(node_group[i]->op(), node0->op());
    DCHECK_EQ(node0->InputCount(), 2);
    if (node_group[i]->InputAt(1) != node0->InputAt(1)) {
      return false;
    }
  }
  return true;
}
References DCHECK_EQ, and v8::internal::ZoneVector< T >::size().
Referenced by v8::internal::compiler::SLPTree::BuildTreeRec().