v8::internal::compiler::anonymous_namespace{code-generator-ppc.cc} Namespace Reference
Classes
class OutOfLineRecordWrite
Functions
Condition FlagsConditionToCondition (FlagsCondition condition, ArchOpcode op)
void FlushPendingPushRegisters (MacroAssembler *masm, FrameAccessState *frame_access_state, ZoneVector< Register > *pending_pushes)
void AdjustStackPointerForTailCall (MacroAssembler *masm, FrameAccessState *state, int new_slot_above_sp, ZoneVector< Register > *pending_pushes=nullptr, bool allow_shrinkage=true)
Function Documentation
AdjustStackPointerForTailCall()
void v8::internal::compiler::anonymous_namespace{code-generator-ppc.cc}::AdjustStackPointerForTailCall (MacroAssembler * masm, FrameAccessState * state, int new_slot_above_sp, ZoneVector< Register > * pending_pushes = nullptr, bool allow_shrinkage = true)
Definition at line 722 of file code-generator-ppc.cc.
                                 {
  int current_sp_offset = state->GetSPToFPSlotCount() +
                          StandardFrameConstants::kFixedSlotCountAboveFp;
  int stack_slot_delta = new_slot_above_sp - current_sp_offset;
  if (stack_slot_delta > 0) {
    if (pending_pushes != nullptr) {
      FlushPendingPushRegisters(masm, state, pending_pushes);
    }
    masm->AddS64(sp, sp, Operand(-stack_slot_delta * kSystemPointerSize), r0);
    state->IncreaseSPDelta(stack_slot_delta);
  } else if (allow_shrinkage && stack_slot_delta < 0) {
    if (pending_pushes != nullptr) {
      FlushPendingPushRegisters(masm, state, pending_pushes);
    }
    masm->AddS64(sp, sp, Operand(-stack_slot_delta * kSystemPointerSize), r0);
    state->IncreaseSPDelta(stack_slot_delta);
  }
}
References v8::internal::MacroAssembler::AddS64(), FlushPendingPushRegisters(), v8::internal::compiler::FrameAccessState::GetSPToFPSlotCount(), v8::internal::compiler::FrameAccessState::IncreaseSPDelta(), v8::internal::CommonFrameConstants::kFixedSlotCountAboveFp, and v8::internal::kSystemPointerSize.
FlagsConditionToCondition()
Condition v8::internal::compiler::anonymous_namespace{code-generator-ppc.cc}::FlagsConditionToCondition (FlagsCondition condition, ArchOpcode op)
Definition at line 256 of file code-generator-ppc.cc.
                                                                             {
  switch (condition) {
    case kEqual:
      return eq;
    case kNotEqual:
      return ne;
    case kSignedLessThan:
    case kUnsignedLessThan:
      return lt;
    case kSignedGreaterThanOrEqual:
    case kUnsignedGreaterThanOrEqual:
      return ge;
    case kSignedLessThanOrEqual:
    case kUnsignedLessThanOrEqual:
      return le;
    case kSignedGreaterThan:
    case kUnsignedGreaterThan:
      return gt;
    case kOverflow:
      // Overflow checked for add/sub only.
      switch (op) {
        case kPPC_Add32:
        case kPPC_Add64:
        case kPPC_Sub:
        case kPPC_AddWithOverflow32:
        case kPPC_SubWithOverflow32:
          return lt;
        default:
          break;
      }
      break;
    case kNotOverflow:
      switch (op) {
        case kPPC_Add32:
        case kPPC_Add64:
        case kPPC_Sub:
        case kPPC_AddWithOverflow32:
        case kPPC_SubWithOverflow32:
          return ge;
        default:
          break;
      }
      break;
    default:
      break;
  }
  UNREACHABLE();
}
References v8::internal::eq, v8::internal::ge, v8::internal::gt, v8::internal::compiler::kEqual, v8::internal::compiler::kNotEqual, v8::internal::compiler::kNotOverflow, v8::internal::compiler::kOverflow, v8::internal::compiler::kSignedGreaterThan, v8::internal::compiler::kSignedGreaterThanOrEqual, v8::internal::compiler::kSignedLessThan, v8::internal::compiler::kSignedLessThanOrEqual, v8::internal::compiler::kUnsignedGreaterThan, v8::internal::compiler::kUnsignedGreaterThanOrEqual, v8::internal::compiler::kUnsignedLessThan, v8::internal::compiler::kUnsignedLessThanOrEqual, v8::internal::le, v8::internal::lt, v8::internal::ne, and v8::internal::UNREACHABLE().
FlushPendingPushRegisters()
void v8::internal::compiler::anonymous_namespace{code-generator-ppc.cc}::FlushPendingPushRegisters (MacroAssembler * masm, FrameAccessState * frame_access_state, ZoneVector< Register > * pending_pushes)
Definition at line 699 of file code-generator-ppc.cc.
                                                                     {
  switch (pending_pushes->size()) {
    case 0:
      break;
    case 1:
      masm->Push((*pending_pushes)[0]);
      break;
    case 2:
      masm->Push((*pending_pushes)[0], (*pending_pushes)[1]);
      break;
    case 3:
      masm->Push((*pending_pushes)[0], (*pending_pushes)[1],
                 (*pending_pushes)[2]);
      break;
    default:
      UNREACHABLE();
  }
  frame_access_state->IncreaseSPDelta(pending_pushes->size());
  pending_pushes->clear();
}
References v8::internal::ZoneVector< T >::clear(), v8::internal::compiler::FrameAccessState::IncreaseSPDelta(), v8::internal::MacroAssembler::Push(), v8::internal::ZoneVector< T >::size(), and v8::internal::UNREACHABLE().
Referenced by AdjustStackPointerForTailCall().