v8::internal::wasm::anonymous_namespace{value-type.cc} Namespace Reference
Functions
void PrintGenericHeaptypeName (std::ostringstream &buf, ValueTypeBase type)
const wasm::FunctionSig * ReplaceTypeInSig (Zone *zone, const wasm::FunctionSig *sig, wasm::ValueType from, wasm::ValueType to, size_t num_replacements)
Function Documentation
PrintGenericHeaptypeName()
void v8::internal::wasm::anonymous_namespace{value-type.cc}::PrintGenericHeaptypeName (std::ostringstream & buf, ValueTypeBase type)
Definition at line 88 of file value-type.cc.
                                                                         {
  DCHECK(type.is_generic());
  if (type.is_nullable()) {
    GenericKind kind = type.generic_kind();
    if (kind == GenericKind::kNone) {
      // The code below would produce "noneref", and we need to keep it
      // that way for "(ref none)", so we need this special case.
      buf << (type.is_shared() ? "(shared nullref)" : "nullref");
      return;
    } else if (kind == GenericKind::kNoExn) {
      buf << (type.is_shared() ? "(shared nullexnref)" : "nullexnref");
      return;
    } else if (kind == GenericKind::kNoExtern) {
      buf << (type.is_shared() ? "(shared nullexternref)" : "nullexternref");
      return;
    } else if (kind == GenericKind::kNoFunc) {
      buf << (type.is_shared() ? "(shared nullfuncref)" : "nullfuncref");
      return;
    } else if (kind == GenericKind::kNoCont) {
      buf << (type.is_shared() ? "(shared nullcontref)" : "nullcontref");
      return;
    }
  }
  buf << type.generic_heaptype_name();
}
References v8::internal::DCHECK(), and v8::internal::tracing::type.
Referenced by v8::internal::wasm::ValueTypeBase::name().
ReplaceTypeInSig()
const wasm::FunctionSig* v8::internal::wasm::anonymous_namespace{value-type.cc}::ReplaceTypeInSig (Zone * zone, const wasm::FunctionSig * sig, wasm::ValueType from, wasm::ValueType to, size_t num_replacements)
Definition at line 200 of file value-type.cc.
                                                                   {
  size_t param_occurences =
      std::count(sig->parameters().begin(), sig->parameters().end(), from);
  size_t return_occurences =
      std::count(sig->returns().begin(), sig->returns().end(), from);
  if (param_occurences == 0 && return_occurences == 0) return sig;
  wasm::FunctionSig::Builder builder(
      zone, sig->return_count() + return_occurences * (num_replacements - 1),
      sig->parameter_count() + param_occurences * (num_replacements - 1));
  for (wasm::ValueType ret : sig->returns()) {
    if (ret == from) {
      for (size_t i = 0; i < num_replacements; i++) builder.AddReturn(to);
    } else {
      builder.AddReturn(ret);
    }
  }
  for (wasm::ValueType param : sig->parameters()) {
    if (param == from) {
      for (size_t i = 0; i < num_replacements; i++) builder.AddParam(to);
    } else {
      builder.AddParam(param);
    }
  }
  return builder.Get();
}
References v8::internal::SignatureBuilder< SigT, T >::AddParam(), v8::internal::SignatureBuilder< SigT, T >::AddReturn(), v8::internal::SignatureBuilder< SigT, T >::Get(), and v8::internal::sig.
Referenced by v8::internal::wasm::GetI32Sig().