v8::internal::compiler::anonymous_namespace{memory-optimizer.cc} Namespace Reference
Functions
bool CanAllocate (const Node *node)
Node * SearchAllocatingNode (Node *start, Node *limit, Zone *temp_zone)
bool CanLoopAllocate (Node *loop_effect_phi, Zone *temp_zone)
Node * EffectPhiForPhi (Node *phi)
void WriteBarrierAssertFailed (Node *node, Node *object, const char *name, Zone *temp_zone)
Function Documentation
CanAllocate()
bool v8::internal::compiler::anonymous_namespace{memory-optimizer.cc}::CanAllocate (const Node * node)
Definition at line 22 of file memory-optimizer.cc.
                                   {
  switch (node->opcode()) {
    case IrOpcode::kAbortCSADcheck:
    case IrOpcode::kBitcastTaggedToWord:
    case IrOpcode::kBitcastWordToTagged:
    case IrOpcode::kCheckTurboshaftTypeOf:
    case IrOpcode::kComment:
    case IrOpcode::kDebugBreak:
    case IrOpcode::kDeoptimizeIf:
    case IrOpcode::kDeoptimizeUnless:
    case IrOpcode::kEffectPhi:
    case IrOpcode::kIfException:
    case IrOpcode::kLoad:
    case IrOpcode::kLoadImmutable:
    case IrOpcode::kLoadElement:
    case IrOpcode::kLoadField:
    case IrOpcode::kLoadFromObject:
    case IrOpcode::kLoadImmutableFromObject:
    case IrOpcode::kMemoryBarrier:
    case IrOpcode::kProtectedLoad:
    case IrOpcode::kLoadTrapOnNull:
    case IrOpcode::kProtectedStore:
    case IrOpcode::kStoreTrapOnNull:
    case IrOpcode::kRetain:
    case IrOpcode::kStackPointerGreaterThan:
#if V8_ENABLE_WEBASSEMBLY
    case IrOpcode::kLoadLane:
    case IrOpcode::kLoadTransform:
    case IrOpcode::kStoreLane:
    case IrOpcode::kLoadStackPointer:
    case IrOpcode::kSetStackPointer:
#endif // V8_ENABLE_WEBASSEMBLY
    case IrOpcode::kStaticAssert:
    // TODO(turbofan): Store nodes might do a bump-pointer allocation.
    // We should introduce a special bump-pointer store node to
    // differentiate that.
    case IrOpcode::kStore:
    case IrOpcode::kStoreElement:
    case IrOpcode::kStoreField:
    case IrOpcode::kStoreToObject:
    case IrOpcode::kTraceInstruction:
    case IrOpcode::kInitializeImmutableInObject:
    case IrOpcode::kTrapIf:
    case IrOpcode::kTrapUnless:
    case IrOpcode::kUnalignedLoad:
    case IrOpcode::kUnalignedStore:
    case IrOpcode::kUnreachable:
    case IrOpcode::kWord32AtomicAdd:
    case IrOpcode::kWord32AtomicAnd:
    case IrOpcode::kWord32AtomicCompareExchange:
    case IrOpcode::kWord32AtomicExchange:
    case IrOpcode::kWord32AtomicLoad:
    case IrOpcode::kWord32AtomicOr:
    case IrOpcode::kWord32AtomicPairAdd:
    case IrOpcode::kWord32AtomicPairAnd:
    case IrOpcode::kWord32AtomicPairCompareExchange:
    case IrOpcode::kWord32AtomicPairExchange:
    case IrOpcode::kWord32AtomicPairLoad:
    case IrOpcode::kWord32AtomicPairOr:
    case IrOpcode::kWord32AtomicPairStore:
    case IrOpcode::kWord32AtomicPairSub:
    case IrOpcode::kWord32AtomicPairXor:
    case IrOpcode::kWord32AtomicStore:
    case IrOpcode::kWord32AtomicSub:
    case IrOpcode::kWord32AtomicXor:
    case IrOpcode::kWord64AtomicAdd:
    case IrOpcode::kWord64AtomicAnd:
    case IrOpcode::kWord64AtomicCompareExchange:
    case IrOpcode::kWord64AtomicExchange:
    case IrOpcode::kWord64AtomicLoad:
    case IrOpcode::kWord64AtomicOr:
    case IrOpcode::kWord64AtomicStore:
    case IrOpcode::kWord64AtomicSub:
    case IrOpcode::kWord64AtomicXor:
      return false;
    case IrOpcode::kCall:
      return !(CallDescriptorOf(node->op())->flags() &
               CallDescriptor::kNoAllocate);
    default:
      break;
  }
  return true;
}
References v8::internal::compiler::CallDescriptorOf(), v8::internal::compiler::CallDescriptor::flags(), v8::internal::compiler::CallDescriptor::kNoAllocate, v8::internal::wasm::kUnreachable, v8::internal::compiler::Node::op(), and v8::internal::compiler::Node::opcode().
Referenced by v8::internal::FreeListCategory::PickNodeFromList(), SearchAllocatingNode(), v8::internal::FreeListCategory::SearchForNodeInList(), and v8::internal::compiler::MemoryOptimizer::VisitNode().
CanLoopAllocate()
bool v8::internal::compiler::anonymous_namespace{memory-optimizer.cc}::CanLoopAllocate (Node * loop_effect_phi, Zone * temp_zone)
Definition at line 131 of file memory-optimizer.cc.
                                                             {
  Node* const control = NodeProperties::GetControlInput(loop_effect_phi);
  // Start the effect chain walk from the loop back edges.
  for (int i = 1; i < control->InputCount(); ++i) {
    if (SearchAllocatingNode(loop_effect_phi->InputAt(i), loop_effect_phi,
                             temp_zone) != nullptr) {
      return true;
    }
  }
  return false;
}
References v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::InputCount(), and SearchAllocatingNode().
Referenced by v8::internal::compiler::MemoryOptimizer::EnqueueMerge().
EffectPhiForPhi()
Node* v8::internal::compiler::anonymous_namespace{memory-optimizer.cc}::EffectPhiForPhi (Node * phi)
Definition at line 143 of file memory-optimizer.cc.
                                 {
  Node* control = NodeProperties::GetControlInput(phi);
  for (Node* use : control->uses()) {
    if (use->opcode() == IrOpcode::kEffectPhi) {
      return use;
    }
  }
  return nullptr;
}
References v8::internal::compiler::NodeProperties::GetControlInput(), use(), and v8::internal::compiler::Node::uses().
Referenced by WriteBarrierAssertFailed().
SearchAllocatingNode()
Node* v8::internal::compiler::anonymous_namespace{memory-optimizer.cc}::SearchAllocatingNode (Node * start, Node * limit, Zone * temp_zone)
Definition at line 107 of file memory-optimizer.cc.
                                                                      {
  ZoneQueue<Node*> queue(temp_zone);
  ZoneSet<Node*> visited(temp_zone);
  visited.insert(limit);
  queue.push(start);
  while (!queue.empty()) {
    Node* const current = queue.front();
    queue.pop();
    if (visited.find(current) == visited.end()) {
      visited.insert(current);
      if (CanAllocate(current)) {
        return current;
      }
      for (int i = 0; i < current->op()->EffectInputCount(); ++i) {
        queue.push(NodeProperties::GetEffectInput(current, i));
      }
    }
  }
  return nullptr;
}
References CanAllocate(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::compiler::Node::op().
Referenced by CanLoopAllocate(), and WriteBarrierAssertFailed().
WriteBarrierAssertFailed()
void v8::internal::compiler::anonymous_namespace{memory-optimizer.cc}::WriteBarrierAssertFailed (Node * node, Node * object, const char * name, Zone * temp_zone)
Definition at line 153 of file memory-optimizer.cc.
                                               {
  std::stringstream str;
  str << "MemoryOptimizer could not remove write barrier for node #"
      << node->id() << "\n";
  str << " Run mksnapshot with --csa-trap-on-node=" << name << ","
      << node->id() << " to break in CSA code.\n";
  Node* object_position = object;
  if (object_position->opcode() == IrOpcode::kPhi) {
    object_position = EffectPhiForPhi(object_position);
  }
  Node* allocating_node = nullptr;
  if (object_position && object_position->op()->EffectOutputCount() > 0) {
    allocating_node = SearchAllocatingNode(node, object_position, temp_zone);
  }
  if (allocating_node) {
    str << "\n There is a potentially allocating node in between:\n";
    str << " " << *allocating_node << "\n";
    str << " Run mksnapshot with --csa-trap-on-node=" << name << ","
        << allocating_node->id() << " to break there.\n";
    if (allocating_node->opcode() == IrOpcode::kCall) {
      str << " If this is a never-allocating runtime call, you can add an "
             "exception to Runtime::MayAllocate.\n";
    }
  } else {
    str << "\n It seems the store happened to something different than a "
           "direct "
           "allocation:\n";
    str << " " << *object << "\n";
    str << " Run mksnapshot with --csa-trap-on-node=" << name << ","
        << object->id() << " to break there.\n";
  }
  FATAL("%s", str.str().c_str());
}
References v8::internal::compiler::Operator::EffectOutputCount(), EffectPhiForPhi(), FATAL, v8::internal::compiler::Node::id(), v8::internal::name, v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), and SearchAllocatingNode().