v8::internal::InstanceTypeChecker Namespace Reference
Namespaces
 InstanceTypeTraits
Classes
struct InstanceRangeChecker
struct InstanceRangeChecker< FIRST_TYPE, upper_limit >
struct InstanceRangeChecker< lower_limit, LAST_TYPE >
Typedefs
using InstanceTypeRange = std::pair< InstanceType, InstanceType >
using TaggedAddressRange = std::pair< Tagged_t, Tagged_t >
Functions
template<class type >
consteval std::optional< RootIndex > UniqueMapOfInstanceTypeCheck ()
constexpr std::optional< RootIndex > UniqueMapOfInstanceType (InstanceType type)
bool MayHaveMapCheckFastCase (InstanceType type)
constexpr bool IsHeapObject (InstanceType instance_type)
constexpr bool IsInternalizedString (InstanceType instance_type)
bool IsInternalizedString (Tagged< Map > map_object)
constexpr bool IsSeqString (InstanceType instance_type)
bool IsSeqString (Tagged< Map > map_object)
constexpr bool IsExternalString (InstanceType instance_type)
bool IsExternalString (Tagged< Map > map_object)
constexpr bool IsUncachedExternalString (InstanceType instance_type)
bool IsUncachedExternalString (Tagged< Map > map_object)
constexpr bool IsConsString (InstanceType instance_type)
bool IsConsString (Tagged< Map > map_object)
constexpr bool IsSlicedString (InstanceType instance_type)
bool IsSlicedString (Tagged< Map > map_object)
constexpr bool IsThinString (InstanceType instance_type)
bool IsThinString (Tagged< Map > map_object)
constexpr bool IsOneByteString (InstanceType instance_type)
bool IsOneByteString (Tagged< Map > map_object)
constexpr bool IsTwoByteString (InstanceType instance_type)
bool IsTwoByteString (Tagged< Map > map_object)
bool IsSharedString (InstanceType instance_type)
bool IsSharedString (Tagged< Map > map_object)
constexpr bool IsIndirectString (InstanceType instance_type)
bool IsIndirectString (Tagged< Map > map_object)
constexpr bool IsDirectString (InstanceType instance_type)
bool IsDirectString (Tagged< Map > map_object)
constexpr bool IsReferenceComparable (InstanceType instance_type)
constexpr bool IsGcSafeCode (InstanceType instance_type)
bool IsGcSafeCode (Tagged< Map > map_object)
constexpr bool IsAbstractCode (InstanceType instance_type)
bool IsAbstractCode (Tagged< Map > map_object)
constexpr bool IsFreeSpaceOrFiller (InstanceType instance_type)
bool IsFreeSpaceOrFiller (Tagged< Map > map)
constexpr bool IsMaybeReadOnlyJSObject (InstanceType instance_type)
bool IsMaybeReadOnlyJSObject (Tagged< Map > map_object)
constexpr bool IsPropertyDictionary (InstanceType instance_type)
bool IsPropertyDictionary (Tagged< Map > map_object)
constexpr bool IsNativeContextSpecific (InstanceType instance_type)
bool IsNativeContextSpecificMap (Tagged< Map > map_object)
constexpr bool IsJSApiWrapperObject (InstanceType instance_type)
bool IsJSApiWrapperObject (Tagged< Map > map_object)
constexpr bool IsCppHeapPointerWrapperObject (InstanceType instance_type)
bool IsCppHeapPointerWrapperObject (Tagged< Map > map_object)
Variables
constexpr Tagged_t kNonJsReceiverMapLimit = 0x0
Typedef Documentation
InstanceTypeRange
using v8::internal::InstanceTypeChecker::InstanceTypeRange = typedef std::pair<InstanceType, InstanceType>
Definition at line 75 of file instance-type-inl.h.
TaggedAddressRange
using v8::internal::InstanceTypeChecker::TaggedAddressRange = typedef std::pair<Tagged_t, Tagged_t>
Definition at line 76 of file instance-type-inl.h.
Function Documentation
IsAbstractCode() [1/2]
constexpr bool v8::internal::InstanceTypeChecker::IsAbstractCode (InstanceType instance_type) [inline], [constexpr]
Definition at line 512 of file instance-type-inl.h.
                                                                    {
  return IsBytecodeArray(instance_type) || IsCode(instance_type);
}
Referenced by IsAbstractCode(), and v8::internal::CodeStatistics::RecordCodeAndMetadataStatistics().
IsAbstractCode() [2/2]
bool v8::internal::InstanceTypeChecker::IsAbstractCode (Tagged< Map > map_object) [inline]
Definition at line 516 of file instance-type-inl.h.
                                                      {
  return IsAbstractCode(map_object->instance_type());
}
References IsAbstractCode().
IsConsString() [1/2]
constexpr bool v8::internal::InstanceTypeChecker::IsConsString (InstanceType instance_type) [inline], [constexpr]
Definition at line 375 of file instance-type-inl.h.
                                                                  {
  return (instance_type & (kIsNotStringMask | kStringRepresentationMask)) ==
         kConsStringTag;
}
References v8::internal::kConsStringTag, v8::internal::kIsNotStringMask, and v8::internal::kStringRepresentationMask.
Referenced by v8::internal::V8HeapExplorer::AddEntry(), v8::internal::anonymous_namespace{externalize-string-extension.cc}::CreateExternalizableString(), v8::internal::V8HeapExplorer::ExtractStringReferences(), v8::internal::anonymous_namespace{string.cc}::HashString(), v8::internal::StringShape::IsCons(), IsConsString(), v8::internal::ConsString::PrintTree(), v8::internal::requires(), v8::internal::RUNTIME_FUNCTION(), v8::internal::StringReplaceOneCharWithString(), v8::internal::StringTable::TryStringToIndexOrLookupExisting(), v8::internal::StringTable::Data::TryStringToIndexOrLookupExisting(), and v8::internal::Isolate::VerifyStaticRoots().
IsConsString() [2/2]
bool v8::internal::InstanceTypeChecker::IsConsString (Tagged< Map > map_object) [inline]
Definition at line 380 of file instance-type-inl.h.
                                                    {
#if V8_STATIC_ROOTS_BOOL
  return CheckInstanceMapRange(kUniqueMapRangeOfStringType::kConsString,
                               map_object);
#else
  return IsConsString(map_object->instance_type());
#endif
}
References IsConsString().
IsCppHeapPointerWrapperObject() [1/2]
constexpr bool v8::internal::InstanceTypeChecker::IsCppHeapPointerWrapperObject (InstanceType instance_type) [inline], [constexpr]
Definition at line 603 of file instance-type-inl.h.
                                {
  return IsJSApiWrapperObject(instance_type) ||
         IsCppHeapExternalObject(instance_type);
}
References IsJSApiWrapperObject().
Referenced by v8::internal::CppHeapObjectWrapper::CppHeapObjectWrapper(), v8::internal::CppHeapObjectWrapper::From(), IsCppHeapPointerWrapperObject(), and v8::internal::anonymous_namespace{minor-mark-sweep.cc}::VisitObjectWithCppHeapPointerField().
IsCppHeapPointerWrapperObject() [2/2]
bool v8::internal::InstanceTypeChecker::IsCppHeapPointerWrapperObject (Tagged< Map > map_object) [inline]
Definition at line 609 of file instance-type-inl.h.
                                                                     {
  return IsCppHeapPointerWrapperObject(map_object->instance_type());
}
References IsCppHeapPointerWrapperObject().
IsDirectString() [1/2]
constexpr bool v8::internal::InstanceTypeChecker::IsDirectString (InstanceType instance_type) [inline], [constexpr]
Definition at line 486 of file instance-type-inl.h.
                                                                    {
  return !IsIndirectString(instance_type);
}
References IsIndirectString().
Referenced by v8::internal::StringShape::IsDirect(), and IsDirectString().
IsDirectString() [2/2]
bool v8::internal::InstanceTypeChecker::IsDirectString (Tagged< Map > map_object) [inline]
Definition at line 490 of file instance-type-inl.h.
                                                      {
#if V8_STATIC_ROOTS_BOOL
  return CheckInstanceMapRange(kUniqueMapRangeOfStringType::kDirectString,
                               map_object);
#else
  return IsDirectString(map_object->instance_type());
#endif
}
References IsDirectString().
IsExternalString() [1/2]
constexpr bool v8::internal::InstanceTypeChecker::IsExternalString (InstanceType instance_type) [inline], [constexpr]
Definition at line 346 of file instance-type-inl.h.
                                                                      {
  return (instance_type & (kIsNotStringMask | kStringRepresentationMask)) ==
         kExternalStringTag;
}
References v8::internal::kExternalStringTag, v8::internal::kIsNotStringMask, and v8::internal::kStringRepresentationMask.
Referenced by v8::internal::Heap::ExternalStringTable::AddString(), v8::internal::Heap::ExternalStringTable::CleanUpAll(), v8::internal::Heap::ExternalStringTable::CleanUpYoung(), v8::internal::ObjectStatsCollectorImpl::CollectStatistics(), v8::internal::StringForwardingTable::Record::DisposeUnusedExternalResource(), v8::internal::V8HeapExplorer::ExtractStringReferences(), v8::internal::Heap::FinalizeExternalString(), v8::internal::NativeContextStats::HasExternalBytes(), v8::internal::NativeContextStats::IncrementExternalSize(), v8::internal::StringShape::IsExternal(), v8::internal::StringShape::IsExternalOneByte(), v8::internal::compiler::StringRef::IsExternalString(), IsExternalString(), v8::internal::StringShape::IsExternalTwoByte(), v8::internal::String::IsInPlaceInternalizableExcludingExternal(), v8::internal::NativeRegExpMacroAssembler::Match(), v8::internal::Heap::MustBeInSharedOldSpace(), v8::internal::Factory::NewProperSubString(), v8::internal::Deserializer< IsolateT >::PostProcessNewObject(), v8::internal::CodeStatistics::RecordCodeAndMetadataStatistics(), v8::internal::ObjectStatsCollectorImpl::RecordVirtualScriptDetails(), v8::internal::Heap::RegisterExternalString(), v8::internal::Serializer::ObjectSerializer::Serialize(), v8::internal::Serializer::ObjectSerializer::SerializeExternalStringAsSequentialString(), v8::internal::SlicedString::set_parent(), v8::internal::anonymous_namespace{heap-snapshot-generator.cc}::SizeForSnapshot(), v8::internal::FullStringForwardingTableCleaner::TryExternalize(), v8::internal::FastJsonStringifier< Char >::TrySerializeSimpleObject(), v8::internal::Heap::UpdateExternalString(), v8::internal::UpdateReferenceInExternalStringTableEntry(), v8::internal::Heap::UpdateYoungReferenceInExternalStringTableEntry(), v8::internal::Heap::ExternalStringTable::UpdateYoungReferences(), v8::internal::Heap::ExternalStringTable::Verify(), v8::internal::Isolate::VerifyStaticRoots(), v8::internal::Heap::ExternalStringTable::VerifyYoung(), v8::internal::Serializer::ObjectSerializer::VisitExternalPointer(), and v8::internal::ExternalStringTableCleanerVisitor< mode >::VisitRootPointers().
IsExternalString() [2/2]
bool v8::internal::InstanceTypeChecker::IsExternalString (Tagged< Map > map_object) [inline]
Definition at line 351 of file instance-type-inl.h.
                                                        {
#if V8_STATIC_ROOTS_BOOL
  return CheckInstanceMapRange(kUniqueMapRangeOfStringType::kExternalString,
                               map_object);
#else
  return IsExternalString(map_object->instance_type());
#endif
}
References IsExternalString().
IsFreeSpaceOrFiller() [1/2]
constexpr bool v8::internal::InstanceTypeChecker::IsFreeSpaceOrFiller (InstanceType instance_type) [inline], [constexpr]
Definition at line 520 of file instance-type-inl.h.
                                                                         {
  return instance_type == FREE_SPACE_TYPE || instance_type == FILLER_TYPE;
}
Referenced by v8::internal::HeapObjectRange::iterator::AdvanceToNextObject(), v8::internal::LiveObjectRange::iterator::AdvanceToNextValidObject(), v8::internal::MinorMarkSweepCollector::DrainMarkingWorklist(), v8::internal::ConservativeStackVisitorBase< ConcreteVisitor >::FindBasePtr(), IsFreeSpaceOrFiller(), v8::internal::ClearStaleLeftTrimmedPointerVisitor::IsLeftTrimmed(), v8::internal::ReadOnlyPageObjectIterator::Next(), v8::internal::SemiSpaceObjectIterator::Next(), v8::internal::LargeObjectSpaceObjectIterator::Next(), v8::internal::anonymous_namespace{read-only-spaces.cc}::ReadOnlySpaceObjectIterator::Next(), v8::internal::MarkCompactCollector::ProcessMarkingWorklist(), v8::internal::MarkingVisitorBase< ConcreteVisitor >::ProcessStrongHeapObject(), v8::internal::Serializer::ObjectSerializer::Serialize(), v8::internal::ReadOnlyPageMetadata::ShrinkToHighWaterMark(), v8::internal::UnreachableObjectsFilter::SkipObject(), and v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::ValidateImpl().
IsFreeSpaceOrFiller() [2/2]
bool v8::internal::InstanceTypeChecker::IsFreeSpaceOrFiller (Tagged< Map > map) [inline]
Definition at line 524 of file instance-type-inl.h.
                                                    {
#if V8_STATIC_ROOTS_BOOL
  static_assert(StaticReadOnlyRoot::kFreeSpaceMap + Map::kSize ==
                StaticReadOnlyRoot::kOnePointerFillerMap);
  static_assert(StaticReadOnlyRoot::kOnePointerFillerMap + Map::kSize ==
                StaticReadOnlyRoot::kTwoPointerFillerMap);
  // Make sure that we can use fast immediate constants on arm64.
  static_assert(StaticReadOnlyRoot::kTwoPointerFillerMap <=
                kMaxFastImmediateConstantArm64);
  return CheckInstanceMapRange(
      TaggedAddressRange(StaticReadOnlyRoot::kFreeSpaceMap,
                         StaticReadOnlyRoot::kTwoPointerFillerMap),
      map);
#else // !V8_STATIC_ROOTS_BOOL
  return IsFreeSpaceOrFiller(map->instance_type());
#endif // !V8_STATIC_ROOTS_BOOL
}
References IsFreeSpaceOrFiller().
IsGcSafeCode() [1/2]
constexpr bool v8::internal::InstanceTypeChecker::IsGcSafeCode (InstanceType instance_type) [inline], [constexpr]
Definition at line 504 of file instance-type-inl.h.
                                                                  {
  return IsCode(instance_type);
}
IsGcSafeCode() [2/2]
bool v8::internal::InstanceTypeChecker::IsGcSafeCode (Tagged< Map > map_object) [inline]
Definition at line 508 of file instance-type-inl.h.
                                                    {
  return IsCode(map_object);
}
IsHeapObject()
constexpr bool v8::internal::InstanceTypeChecker::IsHeapObject (InstanceType instance_type) [inline], [constexpr]
Definition at line 313 of file instance-type-inl.h.
                                                                  {
  return true;
}
Referenced by v8::internal::MarkCompactCollector::ClearJSWeakRefs(), v8::internal::MarkCompactCollector::ClearWeakCollections(), v8::debug::EstimatedValueSize(), v8::internal::PrecisePagePinningVisitor::HandlePointer(), v8::internal::HeapObject::IsHeapObject(), v8::internal::FullStringForwardingTableCleaner::MarkForwardObject(), v8::internal::compiler::ObjectData::ObjectData(), v8::internal::MarkCompactCollector::ProcessMarkingWorklist(), v8::internal::MarkCompactCollector::ProcessOldCodeCandidates(), v8::internal::EvacuationWeakObjectRetainer::RetainAs(), v8::internal::MarkCompactCollector::RetainMaps(), v8::internal::anonymous_namespace{mark-compact.cc}::ShouldRetainMap(), v8::Shell::TestVerifySourcePositions(), v8::internal::FullStringForwardingTableCleaner::TransitionStrings(), v8::internal::FullStringForwardingTableCleaner::TryInternalize(), and v8::internal::ExternalStringTableCleanerVisitor< mode >::VisitRootPointers().
IsIndirectString() [1/2]
constexpr bool v8::internal::InstanceTypeChecker::IsIndirectString (InstanceType instance_type) [inline], [constexpr]
Definition at line 472 of file instance-type-inl.h.
                                                                      {
  return (instance_type & (kIsNotStringMask | kIsIndirectStringMask)) ==
         kIsIndirectStringTag;
}
References v8::internal::kIsIndirectStringMask, v8::internal::kIsIndirectStringTag, and v8::internal::kIsNotStringMask.
Referenced by IsDirectString(), v8::internal::StringShape::IsIndirect(), and IsIndirectString().
IsIndirectString() [2/2]
bool v8::internal::InstanceTypeChecker::IsIndirectString (Tagged< Map > map_object) [inline]
Definition at line 477 of file instance-type-inl.h.
                                                        {
#if V8_STATIC_ROOTS_BOOL
  return CheckInstanceMapRange(kUniqueMapRangeOfStringType::kIndirectString,
                               map_object);
#else
  return IsIndirectString(map_object->instance_type());
#endif
}
References IsIndirectString().
IsInternalizedString() [1/2]
constexpr bool v8::internal::InstanceTypeChecker::IsInternalizedString (InstanceType instance_type) [inline], [constexpr]
Definition at line 317 of file instance-type-inl.h.
                                                                          {
  static_assert(kNotInternalizedTag != 0);
  return (instance_type & (kIsNotStringMask | kIsNotInternalizedMask)) ==
         (kStringTag | kInternalizedTag);
}
References v8::internal::kInternalizedTag, v8::internal::kIsNotInternalizedMask, v8::internal::kIsNotStringMask, v8::internal::kNotInternalizedTag, and v8::internal::kStringTag.
Referenced by v8::internal::SerializerDeserializer::CanBeDeferred(), v8::internal::SharedHeapSerializer::CanBeInSharedOldSpace(), v8::internal::LoadIC::ComputeHandler(), v8::internal::Factory::ComputeInternalizationStrategyForString(), v8::internal::ScopeInfo::ContextSlotIndex(), v8::internal::DEF_HEAP_OBJECT_PREDICATE(), v8::internal::RegExpResultsCache::Enter(), v8::internal::Name::Equals(), v8::internal::String::Equals(), v8::internal::TransitionsAccessor::FindTransitionToField(), v8::internal::ScopeInfo::FunctionContextSlotIndex(), v8::internal::InternalizedStringKey::GetHandleForInsertion(), v8::internal::InternalizedStringKey::InternalizedStringKey(), v8::internal::StringShape::IsInternalized(), IsInternalizedString(), v8::internal::IsPropertyNameFeedback(), IsSharedString(), v8::internal::compiler::NameRef::IsUniqueName(), v8::internal::SharedStructTypeRegistry::Data::KeyIsMatch(), v8::internal::RegExpResultsCache::Lookup(), v8::internal::LookupIterator::LookupIterator(), v8::internal::StringTable::LookupString(), v8::internal::String::MakeExternal(), v8::internal::String::MakeThin(), v8::internal::ScopeInfo::ModuleIndex(), v8::internal::Heap::MustBeInSharedOldSpace(), v8::internal::ClassBoilerplate::New(), v8::internal::Deserializer< IsolateT >::PostProcessNewObject(), v8::internal::Deserializer< IsolateT >::ReadObject(), v8::internal::FactoryBase< Impl >::RefineAllocationTypeForInPlaceInternalizableString(), v8::internal::requires(), v8::internal::FastJsonStringifier< Char >::ResumeJSObject(), v8::internal::RUNTIME_FUNCTION(), v8::internal::Serializer::ObjectSerializer::SerializeExternalStringAsSequentialString(), v8::internal::ContextSerializer::SerializeObjectImpl(), v8::internal::SharedHeapSerializer::SerializeStringTable(), v8::internal::ScopeInfo::SetFunctionName(), v8::internal::anonymous_namespace{string-table.cc}::SetInternalizedReference(), v8::internal::SharedHeapSerializer::ShouldBeInSharedHeapObjectCache(), v8::internal::ContextSerializer::ShouldBeInTheSharedObjectCache(), v8::internal::anonymous_namespace{runtime-strings.cc}::StringAdd_StringConstant_Internalize(), v8::internal::StringTableInsertionKey::StringTableInsertionKey(), v8::internal::compiler::StringRef::SupportedStringKind(), v8::internal::ConcurrentLookupIterator::TryGetOwnChar(), v8::internal::FullStringForwardingTableCleaner::TryInternalize(), v8::internal::StringTable::TryStringToIndexOrLookupExisting(), v8::internal::StringTable::Data::TryStringToIndexOrLookupExisting(), v8::internal::LookupIterator::UpdateProtector(), and v8::internal::Isolate::VerifyStaticRoots().
IsInternalizedString() [2/2]
bool v8::internal::InstanceTypeChecker::IsInternalizedString (Tagged< Map > map_object) [inline]
Definition at line 323 of file instance-type-inl.h.
                                                            {
#if V8_STATIC_ROOTS_BOOL
  return CheckInstanceMapRange(kUniqueMapRangeOfStringType::kInternalizedString,
                               map_object);
#else
  return IsInternalizedString(map_object->instance_type());
#endif
}
References IsInternalizedString().
IsJSApiWrapperObject() [1/2]
constexpr bool v8::internal::InstanceTypeChecker::IsJSApiWrapperObject (InstanceType instance_type) [inline], [constexpr]
Definition at line 594 of file instance-type-inl.h.
                                                                          {
  return IsJSAPIObjectWithEmbedderSlots(instance_type) ||
         IsJSSpecialObject(instance_type);
}
Referenced by v8::internal::CppHeapObjectWrapper::CppHeapObjectWrapper(), v8::internal::ExtractEmbedderDataBackref(), v8::internal::HeapProfiler::GetDetachedJSWrapperObjects(), v8::Object::IsApiWrapper(), IsCppHeapPointerWrapperObject(), IsJSApiWrapperObject(), v8::internal::ContextSerializer::SerializeApiWrapperFields(), and v8::internal::ContextSerializer::SerializeObjectImpl().
IsJSApiWrapperObject() [2/2]
bool v8::internal::InstanceTypeChecker::IsJSApiWrapperObject (Tagged< Map > map_object) [inline]
Definition at line 599 of file instance-type-inl.h.
                                                            {
  return IsJSApiWrapperObject(map_object->instance_type());
}
References IsJSApiWrapperObject().
IsMaybeReadOnlyJSObject() [1/2]
constexpr bool v8::internal::InstanceTypeChecker::IsMaybeReadOnlyJSObject (InstanceType instance_type) [inline], [constexpr]
Definition at line 546 of file instance-type-inl.h.
                                                                             {
  return IsJSExternalObject(instance_type) || IsJSMessageObject(instance_type);
}
Referenced by v8::internal::Map::CanTransition(), v8::internal::Factory::InitializeMap(), IsMaybeReadOnlyJSObject(), and IsNativeContextSpecific().
IsMaybeReadOnlyJSObject() [2/2]
bool v8::internal::InstanceTypeChecker::IsMaybeReadOnlyJSObject (Tagged< Map > map_object) [inline]
Definition at line 550 of file instance-type-inl.h.
                                                               {
  return IsMaybeReadOnlyJSObject(map_object->instance_type());
}
References IsMaybeReadOnlyJSObject().
IsNativeContextSpecific()
constexpr bool v8::internal::InstanceTypeChecker::IsNativeContextSpecific (InstanceType instance_type) [inline], [constexpr]
Definition at line 564 of file instance-type-inl.h.
                                                                             {
  // All context map are tied to some native context.
  if (IsContext(instance_type)) return true;
  // All non-JSReceivers are never tied to any native context.
  if (!IsJSReceiver(instance_type)) return false;
  // Most of the JSReceivers are tied to some native context modulo the
  // following exceptions.
  if (IsMaybeReadOnlyJSObject(instance_type)) {
    // These JSObject types are wrappers around a set of primitive values
    // and exist only for the purpose of passing the data across V8 Api.
    // Thus they are not tied to any native context.
    return false;
  } else if (InstanceTypeChecker::IsAlwaysSharedSpaceJSObject(instance_type)) {
    // JSObjects allocated in shared space are never tied to a native context.
    return false;
#if V8_ENABLE_WEBASSEMBLY
  } else if (InstanceTypeChecker::IsWasmObject(instance_type)) {
    // Wasm structs/arrays are not tied to a native context.
    return false;
#endif
  }
  return true;
}
References IsMaybeReadOnlyJSObject(), and v8::internal::IsWasmObject().
Referenced by IsNativeContextSpecificMap(), v8::internal::Factory::NewContextfulMap(), v8::internal::Factory::NewContextfulMapForCurrentContext(), and v8::internal::Factory::NewContextlessMap().
IsNativeContextSpecificMap()
bool v8::internal::InstanceTypeChecker::IsNativeContextSpecificMap (Tagged< Map > map_object) [inline]
Definition at line 590 of file instance-type-inl.h.
                                                                  {
  return IsNativeContextSpecific(map_object->instance_type());
}
References IsNativeContextSpecific().
IsOneByteString() [1/2]
constexpr bool v8::internal::InstanceTypeChecker::IsOneByteString (InstanceType instance_type) [inline], [constexpr]
Definition at line 417 of file instance-type-inl.h.
                                                                     {
  DCHECK(IsString(instance_type));
  return (instance_type & kStringEncodingMask) == kOneByteStringTag;
}
References v8::internal::DCHECK(), v8::internal::kOneByteStringTag, and v8::internal::kStringEncodingMask.
Referenced by v8::internal::anonymous_namespace{json-parser.cc}::GetFastKeyChars(), v8::internal::StringShape::IsExternalOneByte(), v8::internal::StringShape::IsOneByte(), v8::internal::String::IsOneByteRepresentation(), IsOneByteString(), v8::internal::compiler::MapRef::IsOneByteStringMap(), v8::internal::StringShape::IsSequentialOneByte(), and v8::internal::Isolate::VerifyStaticRoots().
IsOneByteString() [2/2]
bool v8::internal::InstanceTypeChecker::IsOneByteString (Tagged< Map > map_object) [inline]
Definition at line 422 of file instance-type-inl.h.
                                                       {
#if V8_STATIC_ROOTS_BOOL
  DCHECK(IsStringMap(map_object));
  Tagged_t ptr = V8HeapCompressionScheme::CompressObject(map_object.ptr());
  return (ptr & kStringMapEncodingMask) == kOneByteStringMapBit;
#else
  return IsOneByteString(map_object->instance_type());
#endif
}
References v8::internal::V8HeapCompressionSchemeImpl< Cage >::CompressObject(), v8::internal::DCHECK(), IsOneByteString(), and v8::internal::TaggedImpl< kRefType, StorageType >::ptr().
IsPropertyDictionary() [1/2]
constexpr bool v8::internal::InstanceTypeChecker::IsPropertyDictionary (InstanceType instance_type) [inline], [constexpr]
Definition at line 554 of file instance-type-inl.h.
                                                                          {
  return instance_type == PROPERTY_DICTIONARY_TYPE;
}
References v8::internal::PROPERTY_DICTIONARY_TYPE.
Referenced by v8::internal::DEF_GETTER(), v8::internal::JSObject::DictionaryPropertyAt(), v8::internal::anonymous_namespace{js-objects.cc}::GetIdentityHashHelper(), v8::internal::CodeStubAssembler::GetInterestingProperty(), IsPropertyDictionary(), v8::internal::Factory::NewSlowJSObjectWithPropertiesAndElements(), and v8::internal::anonymous_namespace{js-objects.cc}::SetHashAndUpdateProperties().
IsPropertyDictionary() [2/2]
bool v8::internal::InstanceTypeChecker::IsPropertyDictionary (Tagged< Map > map_object) [inline]
Definition at line 558 of file instance-type-inl.h.
                                                            {
  return IsPropertyDictionary(map_object->instance_type());
}
References IsPropertyDictionary().
IsReferenceComparable()
constexpr bool v8::internal::InstanceTypeChecker::IsReferenceComparable (InstanceType instance_type) [inline], [constexpr]
Definition at line 499 of file instance-type-inl.h.
                                                                           {
  return !IsString(instance_type) && !IsBigInt(instance_type) &&
         instance_type != HEAP_NUMBER_TYPE;
}
Referenced by v8::internal::maglev::MaglevGraphBuilder::TryReduceCompareEqualAgainstConstant().
IsSeqString() [1/2]
constexpr bool v8::internal::InstanceTypeChecker::IsSeqString (InstanceType instance_type) [inline], [constexpr]
Definition at line 332 of file instance-type-inl.h.
                                                                 {
  return (instance_type & (kIsNotStringMask | kStringRepresentationMask)) ==
         kSeqStringTag;
}
References v8::internal::kIsNotStringMask, v8::internal::kSeqStringTag, and v8::internal::kStringRepresentationMask.
Referenced by v8::internal::TranslatedValue::GetRawValue(), v8::internal::compiler::StringRef::IsSeqString(), IsSeqString(), v8::internal::compiler::MapRef::IsSeqStringMap(), v8::internal::StringShape::IsSequential(), v8::internal::StringShape::IsSequentialOneByte(), v8::internal::StringShape::IsSequentialTwoByte(), v8::internal::NativeRegExpMacroAssembler::Match(), v8::internal::Factory::NewProperSubString(), v8::internal::Serializer::ObjectSerializer::OutputRawData(), v8::internal::FieldStatsCollector::RecordStats(), v8::internal::SlicedString::set_parent(), and v8::internal::Isolate::VerifyStaticRoots().
IsSeqString() [2/2]
bool v8::internal::InstanceTypeChecker::IsSeqString (Tagged< Map > map_object) [inline]
Definition at line 337 of file instance-type-inl.h.
                                                   {
#if V8_STATIC_ROOTS_BOOL
  return CheckInstanceMapRange(kUniqueMapRangeOfStringType::kSeqString,
                               map_object);
#else
  return IsSeqString(map_object->instance_type());
#endif
}
References IsSeqString().
IsSharedString() [1/2]
bool v8::internal::InstanceTypeChecker::IsSharedString (InstanceType instance_type) [inline]
Definition at line 448 of file instance-type-inl.h.
                                                          {
  DCHECK(IsString(instance_type));
  // TODO(v8:12007): Set is_shared to true on internalized string when
  // v8_flags.shared_string_table is removed.
  return (instance_type & kSharedStringMask) == kSharedStringTag ||
         (v8_flags.shared_string_table && IsInternalizedString(instance_type));
}
References v8::internal::DCHECK(), IsInternalizedString(), v8::internal::kSharedStringMask, v8::internal::kSharedStringTag, and v8::internal::v8_flags.
Referenced by v8::internal::Factory::ComputeSharingStrategyForString(), v8::internal::StringShape::IsShared(), IsSharedString(), and v8::internal::Isolate::VerifyStaticRoots().
IsSharedString() [2/2]
bool v8::internal::InstanceTypeChecker::IsSharedString (Tagged< Map > map_object) [inline]
Definition at line 456 of file instance-type-inl.h.
                                                      {
#if V8_STATIC_ROOTS_BOOL
  DCHECK(IsStringMap(map_object));
  // TODO(v8:12007): Set is_shared to true on internalized string when
  // v8_flags.shared_string_table is removed.
  return (CheckInstanceMapRange(kUniqueMapRangeOfStringType::kSharedSeqString,
                                map_object) ||
          CheckInstanceMapRange(
              kUniqueMapRangeOfStringType::kSharedExternalString,
              map_object)) ||
         (v8_flags.shared_string_table && IsInternalizedString(map_object));
#else
  return IsSharedString(map_object->instance_type());
#endif
}
References v8::internal::DCHECK(), IsInternalizedString(), IsSharedString(), and v8::internal::v8_flags.
IsSlicedString() [1/2]
constexpr bool v8::internal::InstanceTypeChecker::IsSlicedString (InstanceType instance_type) [inline], [constexpr]
Definition at line 389 of file instance-type-inl.h.
                                                                    {
  return (instance_type & (kIsNotStringMask | kStringRepresentationMask)) ==
         kSlicedStringTag;
}
References v8::internal::kIsNotStringMask, v8::internal::kSlicedStringTag, and v8::internal::kStringRepresentationMask.
Referenced by v8::internal::V8HeapExplorer::AddEntry(), v8::internal::JsonParser< Char >::CalculateFileLocation(), v8::internal::V8HeapExplorer::ExtractStringReferences(), v8::internal::ScannerStream::For(), v8::internal::TranslatedValue::GetRawValue(), v8::internal::StringShape::IsSliced(), IsSlicedString(), v8::internal::JsonParser< Char >::IsSpecialString(), v8::internal::JsonParser< Char >::JsonParser(), v8::internal::Factory::NewProperSubString(), v8::internal::JsonParser< Char >::ReportUnexpectedToken(), v8::internal::RUNTIME_FUNCTION(), v8::internal::RegExpResultsCache_MatchGlobalAtom::TryGet(), v8::internal::RegExpResultsCache_MatchGlobalAtom::TryInsert(), v8::internal::StringTable::TryStringToIndexOrLookupExisting(), and v8::internal::Isolate::VerifyStaticRoots().
IsSlicedString() [2/2]
bool v8::internal::InstanceTypeChecker::IsSlicedString (Tagged< Map > map_object) [inline]
Definition at line 394 of file instance-type-inl.h.
                                                      {
#if V8_STATIC_ROOTS_BOOL
  return CheckInstanceMapRange(kUniqueMapRangeOfStringType::kSlicedString,
                               map_object);
#else
  return IsSlicedString(map_object->instance_type());
#endif
}
References IsSlicedString().
IsThinString() [1/2]
constexpr bool v8::internal::InstanceTypeChecker::IsThinString (InstanceType instance_type) [inline], [constexpr]
Definition at line 403 of file instance-type-inl.h.
                                                                  {
  return (instance_type & (kIsNotStringMask | kStringRepresentationMask)) ==
         kThinStringTag;
}
References v8::internal::kIsNotStringMask, v8::internal::kStringRepresentationMask, and v8::internal::kThinStringTag.
Referenced by v8::internal::Heap::ExternalStringTable::CleanUpAll(), v8::internal::Heap::ExternalStringTable::CleanUpYoung(), v8::internal::LoadIC::ComputeHandler(), v8::internal::compiler::JSGraph::ConstantNoHole(), v8::internal::StringForwardingTable::Record::DisposeUnusedExternalResource(), v8::internal::V8HeapExplorer::ExtractStringReferences(), v8::internal::ScannerStream::For(), v8::internal::Deserializer< IsolateT >::GetBackReferencedObject(), v8::internal::maglev::Graph::GetConstant(), v8::String::GetExternalOneByteStringResource(), v8::String::GetExternalStringResourceBaseSlow(), v8::String::GetExternalStringResourceSlow(), v8::internal::StringShape::IsThin(), IsThinString(), v8::internal::compiler::MapRef::IsThinStringMap(), v8::internal::JsonParser< Char >::JsonParser(), v8::internal::StringTable::LookupString(), v8::String::MakeExternal(), v8::internal::FactoryBase< Impl >::NewConsString(), v8::internal::Factory::NewProperSubString(), v8::internal::Heap::RegisterExternalString(), v8::internal::requires(), v8::internal::RUNTIME_FUNCTION(), v8::internal::Serializer::SerializeObject(), v8::internal::anonymous_namespace{string-table.cc}::SetInternalizedReference(), v8::internal::String::SlowEquals(), v8::internal::compiler::StringRef::SupportedStringKind(), v8::internal::String::SupportsExternalization(), v8::internal::Heap::ExternalStringTable::TearDown(), v8::internal::FullStringForwardingTableCleaner::TransitionStrings(), v8::internal::ConcurrentLookupIterator::TryGetOwnChar(), v8::internal::StringTable::TryStringToIndexOrLookupExisting(), v8::internal::Heap::UpdateYoungReferenceInExternalStringTableEntry(), v8::String::VerifyExternalStringResource(), v8::String::VerifyExternalStringResourceBase(), v8::internal::Isolate::VerifyStaticRoots(), and v8::internal::ExternalStringTableCleanerVisitor< mode >::VisitRootPointers().
IsThinString() [2/2]
bool v8::internal::InstanceTypeChecker::IsThinString (Tagged< Map > map_object) [inline]
Definition at line 408 of file instance-type-inl.h.
                                                    {
#if V8_STATIC_ROOTS_BOOL
  return CheckInstanceMapRange(kUniqueMapRangeOfStringType::kThinString,
                               map_object);
#else
  return IsThinString(map_object->instance_type());
#endif
}
References IsThinString().
IsTwoByteString() [1/2]
constexpr bool v8::internal::InstanceTypeChecker::IsTwoByteString (InstanceType instance_type) [inline], [constexpr]
Definition at line 433 of file instance-type-inl.h.
                                                                     {
  DCHECK(IsString(instance_type));
  return (instance_type & kStringEncodingMask) == kTwoByteStringTag;
}
References v8::internal::DCHECK(), v8::internal::kStringEncodingMask, and v8::internal::kTwoByteStringTag.
Referenced by v8::internal::StringShape::IsExternalTwoByte(), v8::internal::StringShape::IsSequentialTwoByte(), v8::internal::StringShape::IsTwoByte(), v8::internal::String::IsTwoByteRepresentation(), IsTwoByteString(), v8::internal::compiler::MapRef::IsTwoByteStringMap(), v8::internal::JsonParser< Char >::ParseJsonObjectProperties(), v8::internal::FastJsonStringifier< Char >::SerializeObjectKey(), and v8::internal::Isolate::VerifyStaticRoots().
IsTwoByteString() [2/2]
bool v8::internal::InstanceTypeChecker::IsTwoByteString (Tagged< Map > map_object) [inline]
Definition at line 438 of file instance-type-inl.h.
                                                       {
#if V8_STATIC_ROOTS_BOOL
  DCHECK(IsStringMap(map_object));
  Tagged_t ptr = V8HeapCompressionScheme::CompressObject(map_object.ptr());
  return (ptr & kStringMapEncodingMask) == kTwoByteStringMapBit;
#else
  return IsTwoByteString(map_object->instance_type());
#endif
}
References v8::internal::V8HeapCompressionSchemeImpl< Cage >::CompressObject(), v8::internal::DCHECK(), IsTwoByteString(), and v8::internal::TaggedImpl< kRefType, StorageType >::ptr().
IsUncachedExternalString() [1/2]
constexpr bool v8::internal::InstanceTypeChecker::IsUncachedExternalString (InstanceType instance_type) [inline], [constexpr]
Definition at line 360 of file instance-type-inl.h.
                                                                              {
  return (instance_type & (kIsNotStringMask | kUncachedExternalStringMask |
                           kStringRepresentationMask)) ==
         (kExternalStringTag | kUncachedExternalStringTag);
}
References v8::internal::kExternalStringTag, v8::internal::kIsNotStringMask, v8::internal::kStringRepresentationMask, v8::internal::kUncachedExternalStringMask, and v8::internal::kUncachedExternalStringTag.
Referenced by v8::internal::StringShape::IsUncachedExternal(), IsUncachedExternalString(), and v8::internal::Isolate::VerifyStaticRoots().
IsUncachedExternalString() [2/2]
bool v8::internal::InstanceTypeChecker::IsUncachedExternalString (Tagged< Map > map_object) [inline]
Definition at line 366 of file instance-type-inl.h.
                                                                {
#if V8_STATIC_ROOTS_BOOL
  return CheckInstanceMapRange(
      kUniqueMapRangeOfStringType::kUncachedExternalString, map_object);
#else
  return IsUncachedExternalString(map_object->instance_type());
#endif
}
References IsUncachedExternalString().
MayHaveMapCheckFastCase()
bool v8::internal::InstanceTypeChecker::MayHaveMapCheckFastCase (InstanceType type) [inline]
Definition at line 203 of file instance-type-inl.h.
{ return false; }
Referenced by v8::internal::Factory::NewMapImpl().
UniqueMapOfInstanceType()
constexpr std::optional<RootIndex> v8::internal::InstanceTypeChecker::UniqueMapOfInstanceType (InstanceType type) [inline], [constexpr]
Definition at line 58 of file instance-type-inl.h.
                       {
#define INSTANCE_TYPE_CHECK(it, forinstancetype) \
  if (type == forinstancetype) { \
    return InstanceTypeChecker::UniqueMapOfInstanceTypeCheck< \
        InstanceTypeChecker::InstanceTypeTraits::it>(); \
  }
  INSTANCE_TYPE_CHECKERS_SINGLE(INSTANCE_TYPE_CHECK);
#undef INSTANCE_TYPE_CHECK
  return Map::TryGetMapRootIdxFor(type);
}
References INSTANCE_TYPE_CHECK, INSTANCE_TYPE_CHECKERS_SINGLE, v8::internal::Map::TryGetMapRootIdxFor(), and v8::internal::tracing::type.
Referenced by v8::internal::compiler::turboshaft::TurbolevEarlyLoweringReducer< Next >::CheckInstanceType(), v8::internal::CodeStubAssembler::DoesntHaveInstanceType(), v8::internal::CodeStubAssembler::HasInstanceType(), and v8::internal::MacroAssembler::JumpIfObjectType().
UniqueMapOfInstanceTypeCheck()
template<class type >
consteval std::optional<RootIndex> v8::internal::InstanceTypeChecker::UniqueMapOfInstanceTypeCheck () [inline]
Definition at line 45 of file instance-type-inl.h.
                                                                          {
  return {};
}
Variable Documentation
kNonJsReceiverMapLimit
constexpr Tagged_t v8::internal::InstanceTypeChecker::kNonJsReceiverMapLimit = 0x0 [constexpr]
Definition at line 97 of file instance-type-checker.h.
Referenced by v8::internal::compiler::turboshaft::TurbolevEarlyLoweringReducer< Next >::JSAnyIsNotPrimitive(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::JSAnyIsNotPrimitiveHeapObject(), v8::internal::CodeStubAssembler::JSAnyIsNotPrimitiveMap(), v8::internal::MacroAssembler::JumpIfJSAnyIsNotPrimitive(), v8::internal::Factory::NewMapImpl(), and v8::internal::Isolate::VerifyStaticRoots().