v8::internal::anonymous_namespace{embedded-data.cc} Namespace Reference
Functions
void FinalizeEmbeddedCodeTargets (Isolate *isolate, EmbeddedData *blob)
void EnsureRelocatable (Tagged< Code > code)
Function Documentation
EnsureRelocatable()
void v8::internal::anonymous_namespace{embedded-data.cc}::EnsureRelocatable (Tagged< Code > code)
Definition at line 224 of file embedded-data.cc.
                                          {
  if (code->relocation_size() == 0) return;
  // On some architectures (arm) the builtin might have a non-empty reloc
  // info containing a CONST_POOL entry. These entries don't have to be
  // updated when InstructionStream object is relocated, so it's safe to drop
  // the reloc info alltogether. If it wasn't the case then we'd have to store
  // it in the metadata.
  for (RelocIterator it(code); !it.done(); it.next()) {
    CHECK_EQ(it.rinfo()->rmode(), RelocInfo::CONST_POOL);
  }
}
References CHECK_EQ, code, v8::internal::RelocInfo::CONST_POOL, and v8::internal::RelocIteratorBase< RelocInfoT >::done().
Referenced by v8::internal::EmbeddedData::NewFromIsolate().
FinalizeEmbeddedCodeTargets()
void v8::internal::anonymous_namespace{embedded-data.cc}::FinalizeEmbeddedCodeTargets (Isolate * isolate, EmbeddedData * blob)
Definition at line 177 of file embedded-data.cc.
                                                                       {
  static const int kRelocMask =
      RelocInfo::ModeMask(RelocInfo::CODE_TARGET) |
      RelocInfo::ModeMask(RelocInfo::RELATIVE_CODE_TARGET);
  static_assert(Builtins::kAllBuiltinsAreIsolateIndependent);
  for (Builtin builtin = Builtins::kFirst; builtin <= Builtins::kLast;
       ++builtin) {
    Tagged<Code> code = isolate->builtins()->code(builtin);
    RelocIterator on_heap_it(code, kRelocMask);
    RelocIterator off_heap_it(blob, code, kRelocMask);
#if defined(V8_TARGET_ARCH_X64) || defined(V8_TARGET_ARCH_ARM64) || \
    defined(V8_TARGET_ARCH_ARM) || defined(V8_TARGET_ARCH_IA32) || \
    defined(V8_TARGET_ARCH_S390X) || defined(V8_TARGET_ARCH_RISCV64) || \
    defined(V8_TARGET_ARCH_LOONG64) || defined(V8_TARGET_ARCH_RISCV32)
    // On these platforms we emit relative builtin-to-builtin
    // jumps for isolate independent builtins in the snapshot. This fixes up the
    // relative jumps to the right offsets in the snapshot.
    // See also: InstructionStream::IsIsolateIndependent.
    while (!on_heap_it.done()) {
      DCHECK(!off_heap_it.done());
      RelocInfo* rinfo = on_heap_it.rinfo();
      DCHECK_EQ(rinfo->rmode(), off_heap_it.rinfo()->rmode());
      Tagged<Code> target_code =
          Code::FromTargetAddress(rinfo->target_address());
      CHECK(Builtins::IsIsolateIndependentBuiltin(target_code));
      // Do not emit write-barrier for off-heap writes.
      off_heap_it.rinfo()->set_off_heap_target_address(
          blob->InstructionStartOf(target_code->builtin_id()));
      on_heap_it.next();
      off_heap_it.next();
    }
    DCHECK(off_heap_it.done());
#else
    // Architectures other than x64 and arm/arm64 do not use pc-relative calls
    // and thus must not contain embedded code targets. Instead, we use an
    // indirection through the root register.
    CHECK(on_heap_it.done());
    CHECK(off_heap_it.done());
#endif
  }
}
References v8::internal::Isolate::builtins(), CHECK, v8::internal::Builtins::code(), code, v8::internal::RelocInfo::CODE_TARGET, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::RelocIteratorBase< RelocInfoT >::done(), v8::internal::Code::FromTargetAddress(), v8::internal::EmbeddedData::InstructionStartOf(), v8::internal::Builtins::IsIsolateIndependentBuiltin(), v8::internal::Builtins::kAllBuiltinsAreIsolateIndependent, v8::internal::Builtins::kFirst, v8::internal::Builtins::kLast, v8::internal::RelocInfo::ModeMask(), v8::internal::RelocIteratorBase< RelocInfoT >::next(), v8::internal::RelocInfo::RELATIVE_CODE_TARGET, v8::internal::RelocIteratorBase< RelocInfoT >::rinfo(), v8::internal::RelocInfo::rmode(), v8::internal::RelocInfo::set_off_heap_target_address(), and v8::internal::RelocInfo::target_address().
Referenced by v8::internal::EmbeddedData::NewFromIsolate().