v8::internal::compiler::turboshaft::detail Namespace Reference
Classes
struct IndexTypeFor
struct IndexTypeFor< std::tuple< T > >
struct LoopLabelForHelper
struct LoopLabelForHelper< V< T > >
struct LoopLabelForHelper< std::tuple< V< Ts >... > >
struct RepresentationForUnionBase
struct RepresentationForUnionBase< T, true >
struct RepresentationForUnion
struct RepresentationForUnion< UntaggedUnion< T, Ts... > >
struct ConstOrVTypeHelper
struct ConstOrVTypeHelper< T, std::void_t< ConstOrV< T > > >
struct BitfieldCheck
struct ValueMatch
struct ValueMatch< T, false >
struct OptionMatch
struct operation_to_opcode_map
struct produces_printable_graph_impl
struct produces_printable_graph_impl< P, std::void_t< decltype(P::kOutputIsTraceableGraph)> >
struct ComponentWithZone
struct BuiltinComponent
struct GraphComponent
struct CodegenComponent
struct InstructionComponent
struct RegisterComponent
class GrowingSidetable
class FixedSidetable
struct TypeForBits
struct TypeForBits< 32 >
struct TypeForBits< 64 >
struct Payload_Empty
struct Payload_Range
struct Payload_InlineSet
struct Payload_OutlineSet
Typedefs
template<typename T >
using index_type_for_t = typename IndexTypeFor< T >::type
Functions
template<typename A , typename ConstOrValues >
auto ResolveAll (A &assembler, const ConstOrValues &const_or_values)
bool SuppressUnusedWarning (bool b)
template<typename T >
auto unwrap_unary_tuple (std::tuple< T > &&tpl)
template<typename T1 , typename T2 , typename... Rest>
auto unwrap_unary_tuple (std::tuple< T1, T2, Rest... > &&tpl)
template<typename T >
T && MakeShadowy (T &&value)
ShadowyOpIndex MakeShadowy (OpIndex value)
template<typename T >
ShadowyOpIndex MakeShadowy (V< T > value)
ShadowyOpIndexVectorWrapper MakeShadowy (base::Vector< const OpIndex > value)
template<typename T >
ShadowyOpIndexVectorWrapper MakeShadowy (base::Vector< const V< T >> value)
template<typename LoopLabel , typename Iterable , typename Iterator , typename ValueTuple , size_t... Indices>
auto BuildResultTupleImpl (bool bound, Iterable &&iterable, LoopLabel &&loop_header, Label<> loop_exit, Iterator current_iterator, ValueTuple current_values, std::index_sequence< Indices... >)
template<typename LoopLabel , typename Iterable , typename Iterator , typename Value >
auto BuildResultTuple (bool bound, Iterable &&iterable, LoopLabel &&loop_header, Label<> loop_exit, Iterator current_iterator, Value current_value)
template<typename LoopLabel , typename Iterable , typename Iterator , typename... Values>
auto BuildResultTuple (bool bound, Iterable &&iterable, LoopLabel &&loop_header, Label<> loop_exit, Iterator current_iterator, std::tuple< Values... > current_values)
Handle< HeapObject > CreateCountersArray (Isolate *isolate)
template<typename T >
bool CanFoldFloatConstants (bool ensure_deterministic_nan, T k1, T k2)
constexpr size_t input_count ()
template<typename T >
constexpr size_t input_count (T) requires(std
template<template< typename > typename HandleType, typename T >
constexpr size_t input_count (const HandleType< T >) requires(std
template<typename T >
constexpr size_t input_count (const base::Flags< T >)
constexpr size_t input_count (const Block *)
constexpr size_t input_count (const TSCallDescriptor *)
constexpr size_t input_count (const char *)
constexpr size_t input_count (const DeoptimizeParameters *)
constexpr size_t input_count (const FastApiCallParameters *)
constexpr size_t input_count (const FrameStateData *)
constexpr size_t input_count (const base::Vector< SwitchOp::Case >)
constexpr size_t input_count (LoadOp::Kind)
constexpr size_t input_count (RegisterRepresentation)
constexpr size_t input_count (MemoryRepresentation)
constexpr size_t input_count (OpEffects)
constexpr size_t input_count (ExternalPointerTagRange)
size_t input_count (const ElementsTransition)
size_t input_count (const ElementsTransitionWithMultipleSources)
size_t input_count (const FeedbackSource)
size_t input_count (const ZoneRefSet< Map >)
size_t input_count (ConstantOp::Storage)
size_t input_count (Type)
size_t input_count (base::Vector< const RegisterRepresentation >)
constexpr size_t input_count (OpIndex)
constexpr size_t input_count (OptionalOpIndex)
constexpr size_t input_count (base::Vector< const OpIndex > inputs)
template<typename T >
constexpr size_t input_count (base::Vector< const V< T >> inputs)
template<typename T >
bool is_unique_and_sorted (const T &container)
template<typename T >
bool is_minus_zero (T value)
template<typename T >
bool is_float_special_value (T value)
template<typename T >
constexpr uint64_t multi_encode (const T &value)
template<typename Head , typename Next , typename... Rest>
constexpr uint64_t multi_encode (const Head &head, const Next &next, const Rest &... rest)
Typedef Documentation
index_type_for_t
template<typename T >
using v8::internal::compiler::turboshaft::detail::index_type_for_t = typedef typename IndexTypeFor<T>::type
Definition at line 372 of file assembler.h.
Function Documentation
BuildResultTuple() [1/2]
template<typename LoopLabel , typename Iterable , typename Iterator , typename... Values>
auto v8::internal::compiler::turboshaft::detail::BuildResultTuple (bool bound, Iterable && iterable, LoopLabel && loop_header, Label<> loop_exit, Iterator current_iterator, std::tuple< Values... > current_values)
Definition at line 1332 of file assembler.h.
                                                          {
  static_assert(std::tuple_size_v<Iterator> == sizeof...(Values));
  return BuildResultTupleImpl(bound, std::forward<Iterable>(iterable),
                              std::forward<LoopLabel>(loop_header),
                              std::move(loop_exit), std::move(current_iterator),
                              std::move(current_values),
                              std::make_index_sequence<sizeof...(Values)>{});
}
References BuildResultTupleImpl().
Referenced by v8::internal::compiler::turboshaft::GenericAssemblerOpInterface< Assembler >::ControlFlowHelper_Foreach().
BuildResultTuple() [2/2]
template<typename LoopLabel , typename Iterable , typename Iterator , typename Value >
auto v8::internal::compiler::turboshaft::detail::BuildResultTuple (bool bound, Iterable && iterable, LoopLabel && loop_header, Label<> loop_exit, Iterator current_iterator, Value current_value)
Definition at line 1322 of file assembler.h.
                                           {
  return std::make_tuple(bound, std::forward<Iterable>(iterable),
                         std::forward<LoopLabel>(loop_header),
                         std::move(loop_exit), current_iterator, current_value);
}
BuildResultTupleImpl()
template<typename LoopLabel , typename Iterable , typename Iterator , typename ValueTuple , size_t... Indices>
auto v8::internal::compiler::turboshaft::detail::BuildResultTupleImpl (bool bound, Iterable && iterable, LoopLabel && loop_header, Label<> loop_exit, Iterator current_iterator, ValueTuple current_values, std::index_sequence< Indices... >)
Definition at line 1310 of file assembler.h.
                                                         {
  return std::make_tuple(bound, std::forward<Iterable>(iterable),
                         std::forward<LoopLabel>(loop_header),
                         std::move(loop_exit), current_iterator,
                         std::get<Indices>(current_values)...);
}
Referenced by BuildResultTuple().
CanFoldFloatConstants()
template<typename T >
bool v8::internal::compiler::turboshaft::detail::CanFoldFloatConstants (bool ensure_deterministic_nan, T k1, T k2)
Definition at line 179 of file machine-optimization-reducer.h.
                                                                      {
  if (!ensure_deterministic_nan) return true;
  // Operations involving NaN values have platform specific results.
  return (!std::isnan(k1) && !std::isnan(k2)) &&
         // Operations involving +Inf and -Inf values have platform specific
         // results.
         (!(std::isinf(k1) && std::isinf(k2) && k1 != k2));
}
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::FloatBinop().
CreateCountersArray()
Handle< HeapObject > v8::internal::compiler::turboshaft::detail::CreateCountersArray (Isolate * isolate)
Definition at line 14 of file block-instrumentation-reducer.cc.
                                                         {
  return Handle<HeapObject>::New(
      ReadOnlyRoots(isolate).basic_block_counters_marker(), isolate);
}
References v8::internal::Handle< T >::New().
Referenced by v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::BlockInstrumentationReducer().
input_count() [1/27]
constexpr size_t v8::internal::compiler::turboshaft::detail::input_count () [constexpr]
Definition at line 9513 of file operations.h.
{ return 0; }
Referenced by v8::internal::maglev::MaglevGraphBuilder::AddNewCallNode(), v8::internal::maglev::MaglevGraphBuilder::AddNewNode(), v8::internal::compiler::RawMachineAssembler::AddNode(), v8::internal::compiler::turboshaft::UseMap::AddUse(), v8::internal::compiler::NodeProperties::AllValueInputsAreTyped(), v8::internal::compiler::Node::AppendInput(), v8::internal::maglev::Phi::backedge_input(), v8::internal::maglev::MaglevGraphBuilder::BuildCallCPPBuiltin(), v8::internal::maglev::MaglevGraphBuilder::BuildCallKnownJSFunction(), v8::internal::maglev::MaglevGraphBuilder::BuildCallSelf(), v8::internal::maglev::MaglevGraphBuilder::BuildGenericConstruct(), v8::internal::maglev::CallBuiltin::CallBuiltin(), v8::internal::compiler::CodeAssembler::CallCFunctionN(), v8::internal::compiler::RawMachineAssembler::CallN(), v8::internal::compiler::RawMachineAssembler::CallNWithFrameState(), v8::internal::compiler::CodeAssembler::CallStubN(), v8::internal::compiler::Verifier::Visitor::Check(), v8::internal::compiler::Node::Clone(), v8::internal::compiler::ScheduleLateNodeVisitor::CloneNode(), v8::internal::compiler::NodeHashCache::Constructor::Constructor(), v8::internal::maglev::CallBuiltin::context_input(), v8::internal::compiler::BytecodeGraphBuilder::CreateGraph(), v8::internal::compiler::JSInliningHeuristic::CreateOrReuseDispatch(), v8::internal::compiler::InstructionSelector::Emit(), v8::internal::compiler::InstructionSelector::EmitBinarySearchSwitch(), v8::internal::compiler::EmitInt64MulWithOverflow(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::EmitLea(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::EmitLea(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitLoad(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::EmitLoopSinglePredecessorBlock(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitStore(), v8::internal::compiler::InstructionSelector::EmitTableSwitch(), v8::internal::compiler::InstructionSelector::EmitWithContinuation(), v8::internal::compiler::MemoryOptimizer::EnqueueMerge(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::GenerateBinOpOperands(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::GenerateRightOperands(), v8::internal::compiler::IA32OperandGenerator::GetEffectiveAddressMemoryOperand(), v8::internal::compiler::S390OperandGenerator::GetEffectiveAddressMemoryOperand(), v8::internal::compiler::X64OperandGenerator::GetEffectiveAddressMemoryOperand(), v8::internal::compiler::anonymous_namespace{js-inlining-heuristic.cc}::HasHeapNumberInputOrOutput(), v8::internal::compiler::CommonOperatorBuilder::InductionVariablePhi(), v8::internal::compiler::InstructionSelector::InitializeCallBuffer(), v8::internal::compiler::JSNativeContextSpecialization::InlineApiCall(), v8::internal::compiler::JSInliner::InlineCall(), v8::internal::compiler::JSInliningHeuristic::InlineCandidate(), v8::internal::maglev::CallBuiltin::InputCountWithoutContext(), v8::internal::compiler::Instruction::Instruction(), v8::internal::maglev::Phi::is_backedge_offset(), v8::internal::maglev::Phi::is_exception_phi(), v8::internal::compiler::RawMachineAssembler::MakeNode(), v8::internal::compiler::Instruction::New(), v8::internal::compiler::Node::New(), v8::internal::maglev::NodeTMixin< Base, Derived >::New(), v8::internal::compiler::Node::NewImpl(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::TFGraph::NewNodeUnchecked(), v8::internal::maglev::Call::num_args(), v8::internal::maglev::Construct::num_args(), v8::internal::maglev::CallCPPBuiltin::num_args(), v8::internal::maglev::CallForwardVarargs::num_args(), v8::internal::maglev::CallRuntime::num_args(), v8::internal::maglev::CallWithSpread::num_args(), v8::internal::maglev::CallSelf::num_args(), v8::internal::maglev::CallKnownJSFunction::num_args(), v8::internal::maglev::CallKnownApiFunction::num_args(), v8::internal::maglev::ConstructWithSpread::num_args(), v8::internal::maglev::GeneratorStore::num_parameters_and_registers(), v8::internal::compiler::RawMachineAssembler::Phi(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::maglev::Phi::RecordUseReprHint(), v8::internal::compiler::JSIntrinsicLowering::ReduceCopyDataPropertiesWithExcludedPropertiesOnStack(), v8::internal::compiler::CsaLoadElimination::ReduceEffectPhi(), v8::internal::compiler::DeadCodeElimination::ReduceEffectPhi(), v8::internal::compiler::LoadElimination::ReduceEffectPhi(), v8::internal::compiler::RedundancyElimination::ReduceEffectPhi(), v8::internal::compiler::WasmLoadElimination::ReduceEffectPhi(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeBind(), v8::internal::compiler::DeadCodeElimination::ReducePhi(), v8::internal::compiler::turboshaft::StringEscapeAnalyzer::ReprocessStringConcats(), v8::internal::maglev::Phi::SetUseRequires31BitValue(), v8::internal::compiler::BranchElimination::SimplifyBranchCondition(), v8::internal::maglev::CallWithSpread::spread(), v8::internal::maglev::ConstructWithSpread::spread(), v8::internal::compiler::RawMachineAssembler::TailCallN(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::TryEmitLoadForLoadWord64AndShiftRight(), v8::internal::maglev::MaglevGraphBuilder::TryReduceCallForApiFunction(), v8::internal::compiler::JSInliningHeuristic::TryReuseDispatch(), v8::internal::compiler::Revectorizer::VectorizeTree(), v8::internal::maglev::GeneratorStore::VerifyInputs(), v8::internal::maglev::Call::VerifyInputs(), v8::internal::maglev::Construct::VerifyInputs(), v8::internal::maglev::CallBuiltin::VerifyInputs(), v8::internal::maglev::CallCPPBuiltin::VerifyInputs(), v8::internal::maglev::CallForwardVarargs::VerifyInputs(), v8::internal::maglev::CallRuntime::VerifyInputs(), v8::internal::maglev::CallWithSpread::VerifyInputs(), v8::internal::maglev::CallSelf::VerifyInputs(), v8::internal::maglev::CallKnownJSFunction::VerifyInputs(), v8::internal::maglev::CallKnownApiFunction::VerifyInputs(), v8::internal::maglev::ConstructWithSpread::VerifyInputs(), v8::internal::compiler::VisitAtomicBinaryOperation(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicBinop(), v8::internal::compiler::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitAtomicBinop(), v8::internal::compiler::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicCompareExchange(), v8::internal::compiler::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitBinOp(), v8::internal::compiler::VisitBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitBinopImpl(), v8::internal::compiler::turboshaft::VisitCompareChain(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitCompareWithMemoryOperand(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitCompareWithMemoryOperand(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitFloatBinop(), v8::internal::compiler::VisitGeneralStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitLoadAndTest(), v8::internal::compiler::InstructionSelector::VisitReturn(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitShift(), v8::internal::compiler::InstructionSelector::VisitStackPointerGreaterThan(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitStoreCommon(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitStoreCommon(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitStoreCommon(), v8::internal::compiler::VisitStoreCommon(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitUnaryOp(), v8::internal::compiler::InstructionSelector::VisitWord32AtomicBinaryOperation(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitWordCompare(), and v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitWordCompare().
input_count() [2/27]
constexpr size_t v8::internal::compiler::turboshaft::detail::input_count (base::Vector< const OpIndex > inputs) [constexpr]
Definition at line 9576 of file operations.h.
                                                               {
  return inputs.size();
}
References v8::base::Vector< T >::size().
input_count() [3/27]
size_t v8::internal::compiler::turboshaft::detail::input_count (base::Vector< const RegisterRepresentation >) [inline]
Definition at line 9559 of file operations.h.
                                                                    {
  return 0;
}
input_count() [4/27]
template<typename T >
constexpr size_t v8::internal::compiler::turboshaft::detail::input_count (base::Vector< const V< T >> inputs) [constexpr]
Definition at line 9580 of file operations.h.
                                                            {
  return inputs.size();
}
Referenced by v8::internal::compiler::turboshaft::CallOp::arguments(), v8::internal::compiler::turboshaft::TailCallOp::arguments(), v8::internal::compiler::turboshaft::CreateOperation(), v8::internal::compiler::turboshaft::AtomicRMWOp::expected(), v8::internal::compiler::turboshaft::JSStackCheckOp::frame_state(), v8::internal::compiler::turboshaft::AtomicWord32PairOp::HasIndex(), v8::internal::compiler::turboshaft::LoadOp::index(), v8::internal::compiler::turboshaft::StoreOp::index(), v8::internal::compiler::turboshaft::PhiOp::inputs_rep(), v8::internal::compiler::turboshaft::AtomicWord32PairOp::inputs_rep(), v8::internal::compiler::turboshaft::CallOp::inputs_rep(), v8::internal::compiler::turboshaft::TailCallOp::inputs_rep(), v8::internal::compiler::turboshaft::CompareMapsOp::map(), v8::internal::compiler::turboshaft::CheckMapsOp::map(), v8::internal::compiler::turboshaft::OperationT< Derived >::New(), v8::internal::compiler::turboshaft::Operation::Operation(), v8::internal::compiler::turboshaft::ReturnOp::return_values(), v8::internal::compiler::turboshaft::FrameStateOp::state_values_count(), v8::internal::compiler::turboshaft::Operation::StorageSlotCount(), v8::internal::compiler::turboshaft::OperationT< Derived >::StorageSlotCount(), and v8::internal::compiler::turboshaft::PhiOp::Validate().
input_count() [5/27]
template<typename T >
constexpr size_t v8::internal::compiler::turboshaft::detail::input_count (const base::Flags< T >) [constexpr]
Definition at line 9536 of file operations.h.
                                                 {
  return 0;
}
input_count() [6/27]
constexpr size_t v8::internal::compiler::turboshaft::detail::input_count (const base::Vector< SwitchOp::Case >) [constexpr]
Definition at line 9545 of file operations.h.
{ return 0; }
input_count() [7/27]
constexpr size_t v8::internal::compiler::turboshaft::detail::input_count (const Block *) [constexpr]
Definition at line 9539 of file operations.h.
{ return 0; }
input_count() [8/27]
constexpr size_t v8::internal::compiler::turboshaft::detail::input_count (const char *) [constexpr]
Definition at line 9541 of file operations.h.
{ return 0; }
input_count() [9/27]
constexpr size_t v8::internal::compiler::turboshaft::detail::input_count (const DeoptimizeParameters *) [constexpr]
Definition at line 9542 of file operations.h.
{ return 0; }
input_count() [10/27]
size_t v8::internal::compiler::turboshaft::detail::input_count (const ElementsTransition) [inline]
Definition at line 9551 of file operations.h.
{ return 0; }
input_count() [11/27]
size_t v8::internal::compiler::turboshaft::detail::input_count (const ElementsTransitionWithMultipleSources) [inline]
Definition at line 9552 of file operations.h.
                                                                       {
  return 0;
}
input_count() [12/27]
constexpr size_t v8::internal::compiler::turboshaft::detail::input_count (const FastApiCallParameters *) [constexpr]
Definition at line 9543 of file operations.h.
{ return 0; }
input_count() [13/27]
size_t v8::internal::compiler::turboshaft::detail::input_count (const FeedbackSource) [inline]
Definition at line 9555 of file operations.h.
{ return 0; }
input_count() [14/27]
constexpr size_t v8::internal::compiler::turboshaft::detail::input_count (const FrameStateData *) [constexpr]
Definition at line 9544 of file operations.h.
{ return 0; }
input_count() [15/27]
template<template< typename > typename HandleType, typename T >
constexpr size_t v8::internal::compiler::turboshaft::detail::input_count (const HandleType< T >) [constexpr]
Definition at line 9528 of file operations.h.
{
  return 0;
}
input_count() [16/27]
constexpr size_t v8::internal::compiler::turboshaft::detail::input_count (const TSCallDescriptor *) [constexpr]
Definition at line 9540 of file operations.h.
{ return 0; }
input_count() [17/27]
size_t v8::internal::compiler::turboshaft::detail::input_count (const ZoneRefSet< Map >) [inline]
Definition at line 9556 of file operations.h.
{ return 0; }
input_count() [18/27]
size_t v8::internal::compiler::turboshaft::detail::input_count (ConstantOp::Storage) [inline]
Definition at line 9557 of file operations.h.
{ return 0; }
input_count() [19/27]
constexpr size_t v8::internal::compiler::turboshaft::detail::input_count (ExternalPointerTagRange) [constexpr]
Definition at line 9550 of file operations.h.
{ return 0; }
input_count() [20/27]
constexpr size_t v8::internal::compiler::turboshaft::detail::input_count (LoadOp::Kind) [constexpr]
Definition at line 9546 of file operations.h.
{ return 0; }
input_count() [21/27]
constexpr size_t v8::internal::compiler::turboshaft::detail::input_count (MemoryRepresentation) [constexpr]
Definition at line 9548 of file operations.h.
{ return 0; }
input_count() [22/27]
constexpr size_t v8::internal::compiler::turboshaft::detail::input_count (OpEffects) [constexpr]
Definition at line 9549 of file operations.h.
{ return 0; }
input_count() [23/27]
constexpr size_t v8::internal::compiler::turboshaft::detail::input_count (OpIndex) [constexpr]
Definition at line 9574 of file operations.h.
{ return 1; }
input_count() [24/27]
constexpr size_t v8::internal::compiler::turboshaft::detail::input_count (OptionalOpIndex) [constexpr]
Definition at line 9575 of file operations.h.
{ return 1; }
input_count() [25/27]
constexpr size_t v8::internal::compiler::turboshaft::detail::input_count (RegisterRepresentation) [constexpr]
Definition at line 9547 of file operations.h.
{ return 0; }
input_count() [26/27]
template<typename T >
constexpr size_t v8::internal::compiler::turboshaft::detail::input_count (T) [constexpr]
Definition at line 9518 of file operations.h.
{
  return 0;
}
input_count() [27/27]
size_t v8::internal::compiler::turboshaft::detail::input_count (Type) [inline]
Definition at line 9558 of file operations.h.
{ return 0; }
is_float_special_value()
template<typename T >
bool v8::internal::compiler::turboshaft::detail::is_float_special_value (T value) [inline]
Definition at line 71 of file types.h.
                                            {
  return std::isnan(value) || is_minus_zero(value);
}
References is_minus_zero(), and v8::internal::value.
Referenced by v8::internal::compiler::turboshaft::FloatType< Bits >::Range().
is_minus_zero()
template<typename T >
bool v8::internal::compiler::turboshaft::detail::is_minus_zero (T value) [inline]
Definition at line 66 of file types.h.
                                   {
  return IsMinusZero(value);
}
References v8::internal::IsMinusZero(), and v8::internal::value.
Referenced by v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::AnyConvertExtern(), v8::internal::anonymous_namespace{js-array-buffer.cc}::CanonicalNumericIndexString(), v8::internal::JSTypedArray::DefineOwnProperty(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Divide(), v8::internal::compiler::turboshaft::FloatType< Bits >::IdentifyMinusZero(), is_float_special_value(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Range(), and v8::internal::compiler::WasmGCLowering::ReduceWasmAnyConvertExtern().
is_unique_and_sorted()
template<typename T >
bool v8::internal::compiler::turboshaft::detail::is_unique_and_sorted (const T & container) [inline]
Definition at line 55 of file types.h.
                                                     {
  if (std::size(container) <= 1) return true;
  auto cur = std::begin(container);
  auto next = cur;
  for (++next; next != std::end(container); ++cur, ++next) {
    if (!(*cur < *next)) return false;
  }
  return true;
}
References v8::internal::compiler::begin(), v8::internal::compiler::end(), and size().
Referenced by v8::internal::compiler::turboshaft::WordType< Bits >::Intersect(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::MakeRange(), v8::internal::compiler::turboshaft::FloatType< Bits >::Set(), and v8::internal::compiler::turboshaft::WordType< Bits >::Set().
MakeShadowy() [1/5]
ShadowyOpIndexVectorWrapper v8::internal::compiler::turboshaft::detail::MakeShadowy (base::Vector< const OpIndex > value) [inline]
Definition at line 1051 of file assembler.h.
                                     {
  return ShadowyOpIndexVectorWrapper{value};
}
References v8::internal::value.
MakeShadowy() [2/5]
template<typename T >
ShadowyOpIndexVectorWrapper v8::internal::compiler::turboshaft::detail::MakeShadowy (base::Vector< const V< T >> value) [inline]
Definition at line 1056 of file assembler.h.
                                                                             {
  return ShadowyOpIndexVectorWrapper{value};
}
References v8::internal::value.
MakeShadowy() [3/5]
ShadowyOpIndex v8::internal::compiler::turboshaft::detail::MakeShadowy (OpIndex value) [inline]
Definition at line 1044 of file assembler.h.
                                                 {
  return ShadowyOpIndex{value};
}
References v8::internal::value.
MakeShadowy() [4/5]
template<typename T >
T&& v8::internal::compiler::turboshaft::detail::MakeShadowy (T && value) [inline]
Definition at line 1040 of file assembler.h.
                                  {
  static_assert(!std::is_same_v<std::remove_reference_t<T>, OpIndex>);
  return std::forward<T>(value);
}
References v8::internal::value.
MakeShadowy() [5/5]
template<typename T >
ShadowyOpIndex v8::internal::compiler::turboshaft::detail::MakeShadowy (V< T > value) [inline]
Definition at line 1048 of file assembler.h.
                                              {
  return ShadowyOpIndex{value};
}
References v8::internal::value.
multi_encode() [1/2]
template<typename Head , typename Next , typename... Rest>
constexpr uint64_t v8::internal::compiler::turboshaft::detail::multi_encode (const Head & head, const Next & next, const Rest &... rest) [constexpr]
Definition at line 167 of file utils.h.
                                                     {
  uint64_t v = multi_encode(next, rest...);
  DCHECK_LT(
      v, std::numeric_limits<uint64_t>::max() / MultiSwitch<Head>::max_value);
  return (v * MultiSwitch<Head>::max_value) + MultiSwitch<Head>::encode(head);
}
References DCHECK_LT, and multi_encode().
multi_encode() [2/2]
template<typename T >
constexpr uint64_t v8::internal::compiler::turboshaft::detail::multi_encode (const T & value) [constexpr]
Definition at line 162 of file utils.h.
                                                {
  return MultiSwitch<T>::encode(value);
}
References v8::internal::value.
Referenced by v8::internal::compiler::turboshaft::multi(), and multi_encode().
ResolveAll()
template<typename A , typename ConstOrValues >
auto v8::internal::compiler::turboshaft::detail::ResolveAll (A & assembler, const ConstOrValues & const_or_values)
Definition at line 356 of file assembler.h.
                                                                    {
  return std::apply(
      [&](auto&... args) { return std::tuple{assembler.resolve(args)...}; },
      const_or_values);
}
References v8::base::args.
Referenced by v8::internal::compiler::turboshaft::GenericAssemblerOpInterface< Assembler >::ControlFlowHelper_Goto(), v8::internal::compiler::turboshaft::GenericAssemblerOpInterface< Assembler >::ControlFlowHelper_GotoIf(), and v8::internal::compiler::turboshaft::GenericAssemblerOpInterface< Assembler >::ControlFlowHelper_GotoIfNot().
SuppressUnusedWarning()
bool v8::internal::compiler::turboshaft::detail::SuppressUnusedWarning (bool b) [inline]
Definition at line 374 of file assembler.h.
{ return b; }
unwrap_unary_tuple() [1/2]
template<typename T >
auto v8::internal::compiler::turboshaft::detail::unwrap_unary_tuple (std::tuple< T > && tpl)
Definition at line 376 of file assembler.h.
                                           {
  return std::get<0>(std::forward<std::tuple<T>>(tpl));
}
unwrap_unary_tuple() [2/2]
template<typename T1 , typename T2 , typename... Rest>
auto v8::internal::compiler::turboshaft::detail::unwrap_unary_tuple (std::tuple< T1, T2, Rest... > && tpl)
Definition at line 380 of file assembler.h.
                                                         {
  return tpl;
}
Referenced by v8::internal::compiler::turboshaft::GenericAssemblerOpInterface< Assembler >::ControlFlowHelper_Foreach().