v8::internal::anonymous_namespace{minor-mark-sweep.cc} Namespace Reference
Classes
class YoungStringForwardingTableCleaner
class MinorMSConservativeStackVisitor
Functions
int EstimateMaxNumberOfRemeberedSets (Heap *heap)
bool IsUnmarkedObjectInYoungGeneration (Heap *heap, FullObjectSlot p)
void VisitObjectWithCppHeapPointerField (Isolate *isolate, Tagged< CppHeapPointerWrapperObjectT > object, MarkingWorklists::Local &worklist)
intptr_t NewSpacePageEvacuationThreshold ()
bool ShouldMovePage (PageMetadata *p, intptr_t live_bytes, intptr_t wasted_bytes)
Function Documentation
EstimateMaxNumberOfRemeberedSets()
int v8::internal::anonymous_namespace{minor-mark-sweep.cc}::EstimateMaxNumberOfRemeberedSets (Heap * heap)
Definition at line 165 of file minor-mark-sweep.cc.
                                                 {
  // old space, lo space, trusted space and trusted lo space can have a maximum
  // of two remembered sets (OLD_TO_NEW and OLD_TO_NEW_BACKGROUND).
  // Code space and code lo space can have typed OLD_TO_NEW in addition.
  return 2 * (heap->old_space()->CountTotalPages() +
              heap->lo_space()->PageCount() +
              heap->trusted_space()->CountTotalPages() +
              heap->trusted_lo_space()->PageCount()) +
         3 * (heap->code_space()->CountTotalPages() +
              heap->code_lo_space()->PageCount());
}
Referenced by v8::internal::YoungGenerationRememberedSetsMarkingWorklist::CollectItems().
IsUnmarkedObjectInYoungGeneration()
bool v8::internal::anonymous_namespace{minor-mark-sweep.cc}::IsUnmarkedObjectInYoungGeneration (Heap * heap, FullObjectSlot p)
Definition at line 495 of file minor-mark-sweep.cc.
                                                                     {
  if (v8_flags.sticky_mark_bits) {
    return HeapLayout::InYoungGeneration(*p);
  }
  DCHECK_IMPLIES(HeapLayout::InYoungGeneration(*p), Heap::InToPage(*p));
  return HeapLayout::InYoungGeneration(*p) &&
         !heap->non_atomic_marking_state()->IsMarked(Cast<HeapObject>(*p));
}
References DCHECK_IMPLIES, v8::internal::Heap::InToPage(), v8::internal::HeapLayout::InYoungGeneration(), and v8::internal::v8_flags.
Referenced by v8::internal::MinorMarkSweepCollector::ClearNonLiveReferences().
NewSpacePageEvacuationThreshold()
intptr_t v8::internal::anonymous_namespace{minor-mark-sweep.cc}::NewSpacePageEvacuationThreshold ()
Definition at line 868 of file minor-mark-sweep.cc.
                                           {
  return v8_flags.minor_ms_page_promotion_threshold *
         MemoryChunkLayout::AllocatableMemoryInDataPage() / 100;
}
References v8::internal::MemoryChunkLayout::AllocatableMemoryInDataPage(), and v8::internal::v8_flags.
Referenced by ShouldMovePage().
ShouldMovePage()
bool v8::internal::anonymous_namespace{minor-mark-sweep.cc}::ShouldMovePage (PageMetadata * p, intptr_t live_bytes, intptr_t wasted_bytes)
Definition at line 873 of file minor-mark-sweep.cc.
                                           {
  DCHECK(v8_flags.page_promotion);
  DCHECK(!v8_flags.sticky_mark_bits);
  Heap* heap = p->heap();
  DCHECK(!p->Chunk()->NeverEvacuate());
  const bool should_move_page =
      ((live_bytes + wasted_bytes) > NewSpacePageEvacuationThreshold() ||
       (p->AllocatedLabSize() == 0)) &&
      (heap->new_space()->IsPromotionCandidate(p)) &&
      heap->CanExpandOldGeneration(live_bytes);
  if (v8_flags.trace_page_promotions) {
    PrintIsolate(
        heap->isolate(),
        "[Page Promotion] %p: collector=mms, should move: %d"
        ", live bytes = %zu, wasted bytes = %zu, promotion threshold = %zu"
        ", allocated labs size = %zu\n",
        p, should_move_page, live_bytes, wasted_bytes,
        NewSpacePageEvacuationThreshold(), p->AllocatedLabSize());
  }
  if (!should_move_page &&
      (p->AgeInNewSpace() == v8_flags.minor_ms_max_page_age)) {
    // Don't allocate on old pages so that recently allocated objects on the
    // page get a chance to die young. The page will be force promoted on the
    // next GC because `AllocatedLabSize` will be 0.
    p->Chunk()->SetFlagNonExecutable(MemoryChunk::NEVER_ALLOCATE_ON_PAGE);
  }
  return should_move_page;
}
References v8::internal::MutablePageMetadata::AgeInNewSpace(), v8::internal::MutablePageMetadata::AllocatedLabSize(), v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::DCHECK(), v8::internal::MemoryChunkMetadata::heap(), v8::internal::MemoryChunk::NEVER_ALLOCATE_ON_PAGE, v8::internal::MemoryChunk::NeverEvacuate(), NewSpacePageEvacuationThreshold(), v8::internal::PrintIsolate(), v8::internal::MemoryChunk::SetFlagNonExecutable(), and v8::internal::v8_flags.
Referenced by v8::internal::MinorMarkSweepCollector::StartSweepNewSpace().
VisitObjectWithCppHeapPointerField()
void v8::internal::anonymous_namespace{minor-mark-sweep.cc}::VisitObjectWithCppHeapPointerField (Isolate * isolate, Tagged< CppHeapPointerWrapperObjectT > object, MarkingWorklists::Local & worklist)
Definition at line 607 of file minor-mark-sweep.cc.
                                     {
  DCHECK(IsCppHeapPointerWrapperObject(object));
  DCHECK(!HeapLayout::InYoungGeneration(object));
  // Wrapper using cpp_heap_wrappable field.
  void* wrappable = CppHeapObjectWrapper::From(object).GetCppHeapWrappable(
      isolate, kAnyCppHeapPointer);
  if (wrappable) {
    worklist.cpp_marking_state()->MarkAndPush(wrappable);
  }
}
References v8::internal::DCHECK(), v8::internal::CppHeapObjectWrapper::From(), v8::internal::CppHeapObjectWrapper::GetCppHeapWrappable(), v8::internal::HeapLayout::InYoungGeneration(), v8::internal::InstanceTypeChecker::IsCppHeapPointerWrapperObject(), and v8::kAnyCppHeapPointer().
Referenced by v8::internal::MinorMarkSweepCollector::MarkRootsFromTracedHandles().