v8::internal::maglev Namespace Reference
Namespaces
 anonymous_namespace{maglev-assembler-arm.cc}
 anonymous_namespace{maglev-assembler-arm64.cc}
 anonymous_namespace{maglev-assembler-s390.cc}
 anonymous_namespace{maglev-assembler-x64.cc}
 anonymous_namespace{maglev-code-generator.cc}
 anonymous_namespace{maglev-compilation-info.cc}
 anonymous_namespace{maglev-concurrent-dispatcher.cc}
 anonymous_namespace{maglev-graph-builder.cc}
 anonymous_namespace{maglev-interpreter-frame-state.cc}
 anonymous_namespace{maglev-ir-arm.cc}
 anonymous_namespace{maglev-ir-arm64.cc}
 anonymous_namespace{maglev-ir-riscv.cc}
 anonymous_namespace{maglev-ir-s390.cc}
 anonymous_namespace{maglev-ir-x64.cc}
 anonymous_namespace{maglev-ir.cc}
 anonymous_namespace{maglev-phi-representation-selector.cc}
 anonymous_namespace{maglev-regalloc.cc}
 detail
Classes
class ZoneLabelRef
struct StackSlot
class MapCompare
class MaglevAssembler
class SaveRegisterStateForCall
class RepeatIterator
class BasicBlock
class DeferredCodeInfo
class MaglevCodeGenState
class MaglevCodeGenerator
class MaglevCompilationInfo
class MaglevCompilationUnit
class MaglevCompiler
class DeoptInfoVisitor
class CallArguments
class MaybeReduceResult
class ReduceResult
struct CatchBlockDetails
struct MaglevCallerDetails
struct MaglevCallSiteInfo
class MaglevGraphBuilder
class MaglevGraphLabeller
class PrintNode
class PrintNodeLabel
class MaglevPrintingVisitor
class GraphProcessor
class ProcessingState
class NodeMultiProcessor
class NodeMultiProcessor<>
class NodeMultiProcessor< Processor, Processors... >
class MaglevGraphVerifier
class Graph
class MaglevInliner
class NodeInfo
struct KnownNodeAspects
class InterpreterFrameState
class CompactInterpreterFrameState
class MergePointRegisterState
class MergePointInterpreterFrameState
struct LoopEffects
class BasicBlockRef
class OpProperties
class ValueLocation
class InputLocation
class Input
class DeoptFrame
class InterpretedDeoptFrame
class InlinedArgumentsDeoptFrame
class ConstructInvokeStubDeoptFrame
class BuiltinContinuationDeoptFrame
class DeoptInfo
struct RegisterSnapshot
class EagerDeoptInfo
class LazyDeoptInfo
class ExceptionHandlerInfo
struct NodeWithInlineInputs
class NodeBase
class Node
class ValueNode
class NodeTMixin
class FixedInputNodeTMixin
struct IsFixedInputNode
struct IsFixedInputNode< T, std::void_t< decltype(T::kInputCount)> >
class Identity
class UnaryWithFeedbackNode
class BinaryWithFeedbackNode
class Int32BinaryWithOverflowNode
class Int32BinaryNode
class Int32BitwiseNot
class Int32UnaryWithOverflowNode
class Int32ShiftRightLogical
class Int32Compare
class Int32ToBoolean
class IntPtrToBoolean
class CheckedSmiIncrement
class CheckedSmiDecrement
class Float64BinaryNode
class Float64BinaryNodeWithCall
class Float64Compare
class Float64ToBoolean
class Float64Negate
class Float64Ieee754Unary
class CheckInt32IsSmi
class CheckUint32IsSmi
class CheckIntPtrIsSmi
class CheckHoleyFloat64IsSmi
class CheckedSmiTagInt32
class CheckedSmiSizedInt32
class CheckedSmiTagUint32
class CheckedSmiTagIntPtr
class UnsafeSmiTagInt32
class UnsafeSmiTagUint32
class UnsafeSmiTagIntPtr
class CheckedSmiUntag
class UnsafeSmiUntag
class Int32Constant
class Uint32Constant
class IntPtrConstant
class Float64Constant
class Int32ToUint8Clamped
class Uint32ToUint8Clamped
class Float64ToUint8Clamped
class CheckedNumberToUint8Clamped
class Int32ToNumber
class Uint32ToNumber
class IntPtrToNumber
class Float64ToTagged
class Float64ToHeapNumberForField
class HoleyFloat64ToTagged
class CheckedSmiTagFloat64
class CheckedInt32ToUint32
class CheckedIntPtrToUint32
class UnsafeInt32ToUint32
class CheckedUint32ToInt32
class CheckedIntPtrToInt32
class ChangeInt32ToFloat64
class ChangeUint32ToFloat64
class ChangeIntPtrToFloat64
class CheckedTruncateFloat64ToInt32
class Int32AbsWithOverflow
class Float64Abs
class Int32CountLeadingZeros
class SmiCountLeadingZeros
class Float64CountLeadingZeros
class Float64Round
class CheckedTruncateFloat64ToUint32
class CheckedNumberOrOddballToFloat64
class CheckedNumberOrOddballToHoleyFloat64
class CheckedNumberToInt32
class UncheckedNumberOrOddballToFloat64
class CheckedHoleyFloat64ToFloat64
class HoleyFloat64ToMaybeNanFloat64
class HoleyFloat64IsHole
class TruncateNumberOrOddballToInt32
class CheckedTruncateNumberOrOddballToInt32
class LogicalNot
class SetPendingMessage
class ToBoolean
class ToBooleanLogicalNot
class StringEqual
class TaggedEqual
class TaggedNotEqual
class TestInstanceOf
class TestUndetectable
class TestTypeOf
class ToName
class ToNumberOrNumeric
class DeleteProperty
class GeneratorStore
class TryOnStackReplacement
class ForInPrepare
class ForInNext
class GetIterator
class GetSecondReturnedValue
class ToObject
class ToString
class NumberToString
class GeneratorRestoreRegister
class InitialValue
class RegisterInput
class SmiConstant
class TaggedIndexConstant
class Constant
class RootConstant
class TrustedConstant
class CreateArrayLiteral
class CreateShallowArrayLiteral
class CreateObjectLiteral
class CreateShallowObjectLiteral
class VirtualObject
class VirtualObjectList
class InlinedAllocation
class AllocationBlock
class ArgumentsLength
class RestLength
class ArgumentsElements
class AllocateElementsArray
class CreateFunctionContext
class FastCreateClosure
class CreateRegExpLiteral
class CreateClosure
class AssertInt32
class CheckMaps
class CheckMapsWithMigrationAndDeopt
class CheckMapsWithAlreadyLoadedMap
class CheckValue
class CheckValueEqualsInt32
class CheckFloat64SameValue
class CheckValueEqualsString
class CheckDynamicValue
class CheckSmi
class CheckNumber
class CheckHeapObject
class CheckSymbol
class CheckInstanceType
class CheckString
class CheckSeqOneByteString
class CheckStringOrStringWrapper
class CheckStringOrOddball
class CheckDetectableCallable
class CheckMapsWithMigration
class MigrateMapIfNeeded
class CheckCacheIndicesNotCleared
class CheckJSDataViewBounds
class LoadTypedArrayLength
class CheckTypedArrayNotDetached
class CheckTypedArrayBounds
class CheckInt32Condition
class DebugBreak
class Dead
class FunctionEntryStackCheck
class CheckedInternalizedString
class CheckedObjectToIndex
class GetTemplateObject
class HasInPrototypeChain
class BuiltinStringFromCharCode
class BuiltinStringPrototypeCharCodeOrCodePointAt
class BuiltinSeqOneByteStringCharCodeAt
class MapPrototypeGet
class MapPrototypeGetInt32Key
class SetPrototypeHas
class CreateFastArrayElements
class TransitionAndStoreArrayElement
class PolymorphicAccessInfo
class AbstractLoadTaggedField
class LoadTaggedField
class LoadTaggedFieldForProperty
class LoadTaggedFieldForContextSlotNoCells
class LoadTaggedFieldForContextSlot
class LoadDoubleField
class LoadFloat64
class LoadInt32
class LoadTaggedFieldByFieldIndex
class LoadFixedArrayElement
class EnsureWritableFastElements
class ExtendPropertiesBackingStore
class MaybeGrowFastElements
class StoreFixedArrayElementWithWriteBarrier
class StoreFixedArrayElementNoWriteBarrier
class LoadFixedDoubleArrayElement
class LoadHoleyFixedDoubleArrayElement
class LoadHoleyFixedDoubleArrayElementCheckedNotHole
class StoreFixedDoubleArrayElement
class LoadSignedIntDataViewElement
class LoadDoubleDataViewElement
class StoreSignedIntDataViewElement
class StoreDoubleDataViewElement
class StoreDoubleField
class StoreInt32
class StoreFloat64
class StoreTaggedFieldNoWriteBarrier
class StoreMap
class StoreTaggedFieldWithWriteBarrier
class StoreContextSlotWithWriteBarrier
class StoreTrustedPointerFieldWithWriteBarrier
class LoadGlobal
class StoreGlobal
class UpdateJSArrayLength
class LoadNamedGeneric
class LoadNamedFromSuperGeneric
class SetNamedGeneric
class LoadEnumCacheLength
class StringAt
class SeqOneByteStringAt
class StringLength
class StringConcat
class ConsStringMap
class UnwrapStringWrapper
class DefineNamedOwnGeneric
class StoreInArrayLiteralGeneric
class GetKeyedGeneric
class SetKeyedGeneric
class DefineKeyedOwnGeneric
class GapMove
class ConstantGapMove
class Phi
class Call
class Construct
class CallBuiltin
class CallCPPBuiltin
class CallForwardVarargs
class CallRuntime
class CallWithSpread
class CallWithArrayLike
class CallSelf
class CallKnownJSFunction
class CallKnownApiFunction
class ConstructWithSpread
class ConvertReceiver
class CheckConstructResult
class CheckDerivedConstructResult
class CheckJSReceiverOrNullOrUndefined
class CheckNotHole
class CheckHoleyFloat64NotHole
class ConvertHoleToUndefined
class HandleNoHeapWritesInterrupt
class ReduceInterruptBudgetForLoop
class ReduceInterruptBudgetForReturn
class ThrowReferenceErrorIfHole
class ThrowSuperNotCalledIfHole
class ThrowSuperAlreadyCalledIfNotHole
class ThrowIfNotCallable
class ThrowIfNotSuperConstructor
class TransitionElementsKind
class TransitionElementsKindOrCheckMap
class GetContinuationPreservedEmbedderData
class SetContinuationPreservedEmbedderData
class ControlNode
class UnconditionalControlNode
class UnconditionalControlNodeT
class ConditionalControlNode
class BranchControlNode
class TerminalControlNode
class TerminalControlNodeT
class BranchControlNodeT
class Jump
class CheckpointedJump
class JumpLoop
class Abort
class Return
class Deopt
class Switch
class BranchIfSmi
class BranchIfRootConstant
class BranchIfUndefinedOrNull
class BranchIfUndetectable
class BranchIfJSReceiver
class BranchIfToBooleanTrue
class BranchIfInt32ToBooleanTrue
class BranchIfIntPtrToBooleanTrue
class BranchIfFloat64ToBooleanTrue
class BranchIfFloat64IsHole
class BranchIfInt32Compare
class BranchIfUint32Compare
class BranchIfFloat64Compare
class BranchIfReferenceEqual
class BranchIfTypeOf
class MaglevPhiRepresentationSelector
class SweepIdentityNodes
class LoopOptimizationProcessor
class AnyUseMarkingProcessor
class DeadNodeSweepingProcessor
class ValueLocationConstraintProcessor
class DecompressedUseMarkingProcessor
class MaxCallDepthProcessor
class LiveRangeAndNextUseProcessor
struct AllocatableRegisters
struct AllocatableRegisters< Register >
struct AllocatableRegisters< DoubleRegister >
struct RegisterStateFlags
struct RegisterMerge
struct RegallocInfo
class RegisterFrameState
class StraightForwardRegisterAllocator
class RegisterFrameArray
Typedefs
using NodeIterator = ZoneVector< Node * >::iterator
using NodeConstIterator = ZoneVector< Node * >::const_iterator
template<typename... Processors>
using GraphMultiProcessor = GraphProcessor< NodeMultiProcessor< Processors... > >
using BlockConstIterator = ZoneVector< BasicBlock * >::const_iterator
using BlockConstReverseIterator = ZoneVector< BasicBlock * >::const_reverse_iterator
using PossibleMaps = compiler::ZoneRefSet< Map >
using NodeTypeInt = std::underlying_type_t< NodeType >
using NodeIdT = uint32_t
template<class Derived >
using NodeT = NodeTMixin< Node, Derived >
template<class Derived >
using ValueNodeT = NodeTMixin< ValueNode, Derived >
template<size_t InputCount, class Derived >
using FixedInputNodeT = FixedInputNodeTMixin< InputCount, NodeT< Derived >, Derived >
template<size_t InputCount, class Derived >
using FixedInputValueNodeT = FixedInputNodeTMixin< InputCount, ValueNodeT< Derived >, Derived >
typedef base::EnumSet< ValueRepresentation, int8_t > ValueRepresentationSet
typedef base::EnumSet< UseRepresentation, int8_t > UseRepresentationSet
typedef base::PointerWithPayload< void, RegisterStateFlags, 2 > RegisterState
Enumerations
enum class UseReprHintRecording { kRecord
, kDoNotRecord
 }
enum class BlockProcessResult { kContinue
, kSkip
 }
enum class ProcessResult {
kContinue
, kRemove
, kHoist
, kAbort
,
kSkipBlock
 }
enum class Opcode : uint16_t { NODE_BASE_LIST =(DEF_OPCODES)
 }
enum class ValueRepresentation : uint8_t {
kTagged
, kInt32
, kUint32
, kFloat64
,
kHoleyFloat64
, kIntPtr
 }
enum class NodeType : uint32_t { DEFINE_NODE_TYPE
 }
enum class TaggedToFloat64ConversionType : uint8_t { kOnlyNumber
, kNumberOrBoolean
, kNumberOrOddball
 }
enum class CheckType { kCheckHeapObject
, kOmitHeapObjectCheck
 }
enum class StringEqualInputs { kOnlyStrings
, kStringsOrOddballs
 }
enum class EscapeAnalysisResult { kUnknown
, kElided
, kEscaped
 }
enum class AssertCondition { D
 }
enum class StoreTaggedMode : uint8_t { kDefault
, kInitializing
, kTransitioning
 }
enum class UseRepresentation : uint8_t {
kTagged
, kInt32
, kTruncatedInt32
, kUint32
,
kFloat64
, kHoleyFloat64
 }
Functions
static bool IsMaglevEnabled ()
static bool IsMaglevOsrEnabled ()
constexpr Condition ConditionForFloat64 (Operation operation)
constexpr Condition ConditionForNaN ()
int ShiftFromScale (int n)
template<typename T >
void AllocateSlow (MaglevAssembler *masm, RegisterSnapshot register_snapshot, Register object, Builtin builtin, T size_in_bytes, ZoneLabelRef done)
ExternalReference SpaceAllocationTopAddress (Isolate *isolate, AllocationType alloc_type)
ExternalReference SpaceAllocationLimitAddress (Isolate *isolate, AllocationType alloc_type)
Builtin AllocateBuiltin (AllocationType alloc_type)
template<typename T >
auto RepeatValue (T val, int count)
Condition ToCondition (AssertCondition cond)
constexpr Condition ConditionFor (Operation operation)
constexpr Condition UnsignedConditionFor (Operation operation)
int GetSafepointIndexForStackSlot (int i)
Register ToRegister (const compiler::InstructionOperand &operand)
DoubleRegister ToDoubleRegister (const compiler::InstructionOperand &operand)
template<typename RegisterT >
auto ToRegisterT (const compiler::InstructionOperand &operand)
Register ToRegister (const ValueLocation &location)
DoubleRegister ToDoubleRegister (const ValueLocation &location)
template<Operation kOperation>
static constexpr std::optional< int > Int32Identity ()
template<Operation kOperation, typename type >
bool OperationValue (type left, type right)
std::ostream & operator<< (std::ostream &os, const PrintNode &printer)
std::ostream & operator<< (std::ostream &os, const PrintNodeLabel &printer)
void PrintGraph (std::ostream &os, Graph *const graph)
template<typename Key , typename Value , typename MergeFunc = std::equal_to<Value>>
void DestructivelyIntersect (ZoneMap< Key, Value > &lhs_map, const ZoneMap< Key, Value > &rhs_map, MergeFunc &&func=MergeFunc())
void DefineAsRegister (Node *node)
void DefineAsConstant (Node *node)
void DefineAsFixed (Node *node, Register reg)
void DefineSameAsFirst (Node *node)
void UseRegister (Input &input)
void UseAndClobberRegister (Input &input)
void UseAny (Input &input)
void UseFixed (Input &input, Register reg)
void UseFixed (Input &input, DoubleRegister reg)
const char * OpcodeToString (Opcode opcode)
bool FromConstantToBool (LocalIsolate *local_isolate, ValueNode *node)
ValueRepresentation ToValueRepresentation (MachineType type)
void CheckValueInputIs (const NodeBase *node, int i, ValueRepresentation expected, MaglevGraphLabeller *graph_labeller)
void CheckValueInputIs (const NodeBase *node, int i, Opcode expected, MaglevGraphLabeller *graph_labeller)
template<typename Derived , ValueRepresentation FloatType>
requires (FloatType==ValueRepresentation::kFloat64||FloatType==ValueRepresentation::kHoleyFloat64) void CheckedNumberOrOddballToFloat64OrHoleyFloat64< Derived
std::ostream & operator<< (std::ostream &os, StoreMap::Kind kind)
std::ostream & operator<< (std::ostream &os, Opcode opcode)
constexpr bool IsValueNode (Opcode opcode)
constexpr bool IsConstantNode (Opcode opcode)
constexpr bool IsCommutativeNode (Opcode opcode)
constexpr bool IsZeroCostNode (Opcode opcode)
constexpr bool IsGapMoveNode (Opcode opcode)
constexpr bool IsControlNode (Opcode opcode)
constexpr bool IsBranchControlNode (Opcode opcode)
constexpr bool IsConditionalControlNode (Opcode opcode)
constexpr bool IsUnconditionalControlNode (Opcode opcode)
constexpr bool IsTerminalControlNode (Opcode opcode)
constexpr bool IsSimpleFieldStore (Opcode opcode)
constexpr bool IsElementsArrayWrite (Opcode opcode)
constexpr bool IsTypedArrayStore (Opcode opcode)
constexpr bool CanBeStoreToNonEscapedObject (Opcode opcode)
constexpr bool IsDoubleRepresentation (ValueRepresentation repr)
constexpr bool IsZeroExtendedRepresentation (ValueRepresentation repr)
constexpr bool NodeTypeIsNeverStandalone (NodeType type)
constexpr NodeType EmptyNodeType ()
constexpr NodeType IntersectType (NodeType left, NodeType right)
constexpr NodeType UnionType (NodeType left, NodeType right)
constexpr bool NodeTypeIs (NodeType type, NodeType to_check)
constexpr bool NodeTypeCanBe (NodeType type, NodeType to_check)
constexpr bool NodeTypeIsUnstable (NodeType type)
constexpr NodeType MakeTypeStable (NodeType type)
NodeType StaticTypeForMap (compiler::MapRef map, compiler::JSHeapBroker *broker)
constexpr bool IsEmptyNodeType (NodeType type)
NodeType StaticTypeForConstant (compiler::JSHeapBroker *broker, compiler::ObjectRef ref)
bool IsInstanceOfLeafNodeType (compiler::MapRef map, NodeType type, compiler::JSHeapBroker *broker)
bool IsInstanceOfNodeType (compiler::MapRef map, NodeType type, compiler::JSHeapBroker *broker)
std::ostream & operator<< (std::ostream &out, const NodeType &type)
bool NodeTypeMayBeNullOrUndefined (NodeType type)
bool FromConstantToBool (MaglevAssembler *masm, ValueNode *node)
std::ostream & operator<< (std::ostream &os, const ValueRepresentation &repr)
std::ostream & operator<< (std::ostream &os, const TaggedToFloat64ConversionType &conversion_type)
bool HasOnlyJSTypedArrayMaps (base::Vector< const compiler::MapRef > maps)
bool HasOnlyJSArrayMaps (base::Vector< const compiler::MapRef > maps)
bool HasOnlyJSObjectMaps (base::Vector< const compiler::MapRef > maps)
bool HasOnlyStringMaps (base::Vector< const compiler::MapRef > maps)
bool HasOnlyNumberMaps (base::Vector< const compiler::MapRef > maps)
bool HasNumberMap (base::Vector< const compiler::MapRef > maps)
constexpr OpProperties StaticPropertiesForOpcode (Opcode opcode)
DEFINE_TRUNCATE_NODE (TruncateFloat64ToInt32, HoleyFloat64, OpProperties::Int32()) DEFINE_TRUNCATE_NODE(UnsafeTruncateFloat64ToInt32
std::ostream & operator<< (std::ostream &os, const AssertCondition cond)
LOAD_TYPED_ARRAY (LoadSignedIntTypedArrayElement, OpProperties::Int32(), INT8_ELEMENTS, INT16_ELEMENTS, INT32_ELEMENTS) LOAD_TYPED_ARRAY(LoadUnsignedIntTypedArrayElement
UINT32_ELEMENTS LOAD_TYPED_ARRAY (LoadDoubleTypedArrayElement, OpProperties::Float64(), FLOAT32_ELEMENTS, FLOAT64_ELEMENTS) LOAD_CONSTANT_TYPED_ARRAY(LoadSignedIntConstantTypedArrayElement
UINT32_ELEMENTS INT32_ELEMENTS LOAD_CONSTANT_TYPED_ARRAY (LoadUnsignedIntConstantTypedArrayElement, OpProperties::Uint32(), UINT8_ELEMENTS, UINT8_CLAMPED_ELEMENTS, UINT16_ELEMENTS, UINT16_ELEMENTS, UINT32_ELEMENTS) LOAD_CONSTANT_TYPED_ARRAY(LoadDoubleConstantTypedArrayElement
STORE_TYPED_ARRAY (StoreIntTypedArrayElement, OpProperties::CanWrite(), ValueRepresentation::kInt32, INT8_ELEMENTS, INT16_ELEMENTS, INT32_ELEMENTS, UINT8_ELEMENTS, UINT8_CLAMPED_ELEMENTS, UINT16_ELEMENTS, UINT16_ELEMENTS, UINT32_ELEMENTS) STORE_TYPED_ARRAY(StoreDoubleTypedArrayElement
STORE_CONSTANT_TYPED_ARRAY (StoreIntConstantTypedArrayElement, OpProperties::CanWrite(), ValueRepresentation::kInt32, INT8_ELEMENTS, INT16_ELEMENTS, INT32_ELEMENTS, UINT8_ELEMENTS, UINT8_CLAMPED_ELEMENTS, UINT16_ELEMENTS, UINT16_ELEMENTS, UINT32_ELEMENTS) STORE_CONSTANT_TYPED_ARRAY(StoreDoubleConstantTypedArrayElement
bool IsInitializingOrTransitioning (StoreTaggedMode mode)
std::ostream & operator<< (std::ostream &os, const UseRepresentation &repr)
template<typename NodeT >
constexpr bool CanBeStoreToNonEscapedObject ()
constexpr bool operator== (const RegisterStateFlags &left, const RegisterStateFlags &right)
bool LoadMergeState (RegisterState state, RegisterMerge **merge)
bool LoadMergeState (RegisterState state, ValueNode **node, RegisterMerge **merge)
FPUCondition ConditionToConditionCmpFPU (Condition condition)
void SubSizeAndTagObject (MaglevAssembler *masm, Register object, Register size_in_bytes)
void SubSizeAndTagObject (MaglevAssembler *masm, Register object, int size_in_bytes)
template<typename T >
void AllocateRaw (MaglevAssembler *masm, Isolate *isolate, RegisterSnapshot register_snapshot, Register object, T size_in_bytes, AllocationType alloc_type, AllocationAlignment alignment)
ScaleFactor ScaleFactorFromInt (int n)
Variables
static constexpr int kNoVreg = -1
static constexpr int kOpcodeCount = NODE_BASE_LIST(PLUS_ONE)
static constexpr Opcode kFirstOpcode = static_cast<Opcode>(0)
static constexpr Opcode kLastOpcode = static_cast<Opcode>(kOpcodeCount - 1)
static constexpr Opcode kFirstValueNodeOpcode
static constexpr Opcode kLastValueNodeOpcode
static constexpr Opcode kFirstConstantNodeOpcode
static constexpr Opcode kLastConstantNodeOpcode
static constexpr Opcode kFirstGapMoveNodeOpcode
static constexpr Opcode kLastGapMoveNodeOpcode
static constexpr Opcode kFirstNodeOpcode = std::min({NODE_LIST(V) kLastOpcode})
static constexpr Opcode kLastNodeOpcode = std::max({NODE_LIST(V) kFirstOpcode})
static constexpr Opcode kFirstBranchControlNodeOpcode
static constexpr Opcode kLastBranchControlNodeOpcode
static constexpr Opcode kFirstConditionalControlNodeOpcode
static constexpr Opcode kLastConditionalControlNodeOpcode
static constexpr Opcode kLastUnconditionalControlNodeOpcode
static constexpr Opcode kFirstUnconditionalControlNodeOpcode
static constexpr Opcode kLastTerminalControlNodeOpcode
static constexpr Opcode kFirstTerminalControlNodeOpcode
static constexpr Opcode kFirstControlNodeOpcode
static constexpr Opcode kLastControlNodeOpcode
static constexpr int kNumberOfLeafNodeTypes = 0 LEAF_NODE_TYPE_LIST(COUNT)
static constexpr NodeIdT kInvalidNodeId = 0
static constexpr NodeIdT kFirstValidNodeId = 1
HoleyFloat64
static constexpr int kNumAssertConditions
UINT8_ELEMENTS
UINT8_CLAMPED_ELEMENTS
UINT16_ELEMENTS
UINT32_ELEMENTS INT8_ELEMENTS
UINT32_ELEMENTS INT16_ELEMENTS
UINT32_ELEMENTS INT32_ELEMENTS FLOAT32_ELEMENTS
static constexpr int kAllocatableGeneralRegisterCount
static constexpr int kAllocatableDoubleRegisterCount
Typedef Documentation
BlockConstIterator
using v8::internal::maglev::BlockConstIterator = typedef ZoneVector<BasicBlock*>::const_iterator
Definition at line 22 of file maglev-graph.h.
BlockConstReverseIterator
using v8::internal::maglev::BlockConstReverseIterator = typedef ZoneVector<BasicBlock*>::const_reverse_iterator
Definition at line 23 of file maglev-graph.h.
FixedInputNodeT
template<size_t InputCount, class Derived >
using v8::internal::maglev::FixedInputNodeT = typedef FixedInputNodeTMixin<InputCount, NodeT<Derived>, Derived>
Definition at line 3049 of file maglev-ir.h.
FixedInputValueNodeT
template<size_t InputCount, class Derived >
using v8::internal::maglev::FixedInputValueNodeT = typedef FixedInputNodeTMixin<InputCount, ValueNodeT<Derived>, Derived>
Definition at line 3053 of file maglev-ir.h.
GraphMultiProcessor
template<typename... Processors>
using v8::internal::maglev::GraphMultiProcessor = typedef GraphProcessor<NodeMultiProcessor<Processors...> >
Definition at line 334 of file maglev-graph-processor.h.
NodeConstIterator
using v8::internal::maglev::NodeConstIterator = typedef ZoneVector<Node*>::const_iterator
Definition at line 23 of file maglev-basic-block.h.
NodeIdT
using v8::internal::maglev::NodeIdT = typedef uint32_t
Definition at line 1095 of file maglev-ir.h.
NodeIterator
using v8::internal::maglev::NodeIterator = typedef ZoneVector<Node*>::iterator
Definition at line 22 of file maglev-basic-block.h.
NodeT
template<class Derived >
using v8::internal::maglev::NodeT = typedef NodeTMixin<Node, Derived>
Definition at line 3043 of file maglev-ir.h.
NodeTypeInt
using v8::internal::maglev::NodeTypeInt = typedef std::underlying_type_t<NodeType>
Definition at line 710 of file maglev-ir.h.
PossibleMaps
using v8::internal::maglev::PossibleMaps = typedef compiler::ZoneRefSet<Map>
Definition at line 71 of file maglev-interpreter-frame-state.h.
RegisterState
typedef base::PointerWithPayload<void, RegisterStateFlags, 2> v8::internal::maglev::RegisterState
Definition at line 63 of file maglev-regalloc-data.h.
UseRepresentationSet
typedef base::EnumSet<UseRepresentation, int8_t> v8::internal::maglev::UseRepresentationSet
Definition at line 9835 of file maglev-ir.h.
ValueNodeT
template<class Derived >
using v8::internal::maglev::ValueNodeT = typedef NodeTMixin<ValueNode, Derived>
Definition at line 3046 of file maglev-ir.h.
ValueRepresentationSet
typedef base::EnumSet<ValueRepresentation, int8_t> v8::internal::maglev::ValueRepresentationSet
Definition at line 9834 of file maglev-ir.h.
Enumeration Type Documentation
AssertCondition
enum v8::internal::maglev::AssertCondition [strong]
Enumerator
D
Definition at line 6740 of file maglev-ir.h.
                           {
#define D(Name) k##Name,
  ASSERT_CONDITION(D)
#undef D
};
BlockProcessResult
enum v8::internal::maglev::BlockProcessResult [strong]
Enumerator
kContinue
kSkip
Definition at line 47 of file maglev-graph-processor.h.
                              {
  kContinue, // Process exited normally.
  kSkip, // Skip processing this block (no MultiProcessor support).
};
CheckType
enum v8::internal::maglev::CheckType [strong]
Enumerator
kCheckHeapObject
kOmitHeapObjectCheck
Definition at line 4915 of file maglev-ir.h.
{ kCheckHeapObject, kOmitHeapObjectCheck };
EscapeAnalysisResult
enum v8::internal::maglev::EscapeAnalysisResult [strong]
Enumerator
kUnknown
kElided
kEscaped
Definition at line 6258 of file maglev-ir.h.
                                {
  kUnknown,
  kElided,
  kEscaped,
};
NodeType
enum v8::internal::maglev::NodeType : uint32_t [strong]
Enumerator
DEFINE_NODE_TYPE
Definition at line 705 of file maglev-ir.h.
                    : uint32_t {
#define DEFINE_NODE_TYPE(Name, Value) k##Name = Value,
  NODE_TYPE_LIST(DEFINE_NODE_TYPE)
#undef DEFINE_NODE_TYPE
};
Opcode
enum v8::internal::maglev::Opcode : uint16_t [strong]
Enumerator
NODE_BASE_LIST
Definition at line 451 of file maglev-ir.h.
: uint16_t { NODE_BASE_LIST(DEF_OPCODES) };
ProcessResult
enum v8::internal::maglev::ProcessResult [strong]
Enumerator
kContinue
kRemove
kHoist
kAbort
kSkipBlock
Definition at line 52 of file maglev-graph-processor.h.
                         {
  kContinue, // Process exited normally, and the following processors will be
               // called on the node.
  kRemove, // Remove the current node from the graph (and do not call the
               // following processors).
  kHoist, // Hoist the current instruction to the parent basic block
               // and reset the current instruction to the beginning of the
               // block. Parent block must be dominating.
  kAbort, // Stop processing now, do not process subsequent nodes/blocks.
               // Should not be used when processing Constants.
  kSkipBlock, // Stop processing this block and skip the remaining nodes (no
               // MultiProcessor support).
};
StoreTaggedMode
enum v8::internal::maglev::StoreTaggedMode : uint8_t [strong]
Enumerator
kDefault
kInitializing
kTransitioning
Definition at line 9001 of file maglev-ir.h.
                           : uint8_t {
  kDefault,
  kInitializing,
  kTransitioning
};
StringEqualInputs
enum v8::internal::maglev::StringEqualInputs [strong]
Enumerator
kOnlyStrings
kStringsOrOddballs
Definition at line 4966 of file maglev-ir.h.
{ kOnlyStrings, kStringsOrOddballs };
TaggedToFloat64ConversionType
enum v8::internal::maglev::TaggedToFloat64ConversionType : uint8_t [strong]
Enumerator
kOnlyNumber
kNumberOrBoolean
kNumberOrOddball
Definition at line 1007 of file maglev-ir.h.
                                         : uint8_t {
  kOnlyNumber,
  kNumberOrBoolean,
  kNumberOrOddball,
};
UseRepresentation
enum v8::internal::maglev::UseRepresentation : uint8_t [strong]
Enumerator
kTagged
kInt32
kTruncatedInt32
kUint32
kFloat64
kHoleyFloat64
Definition at line 9807 of file maglev-ir.h.
                             : uint8_t {
  kTagged,
  kInt32,
  kTruncatedInt32,
  kUint32,
  kFloat64,
  kHoleyFloat64,
};
UseReprHintRecording
enum v8::internal::maglev::UseReprHintRecording [strong]
Enumerator
kRecord
kDoNotRecord
Definition at line 173 of file maglev-graph-builder.h.
{ kRecord, kDoNotRecord };
ValueRepresentation
enum v8::internal::maglev::ValueRepresentation : uint8_t [strong]
Enumerator
kTagged
kInt32
kUint32
kFloat64
kHoleyFloat64
kIntPtr
Definition at line 610 of file maglev-ir.h.
                               : uint8_t {
  kTagged,
  kInt32,
  kUint32,
  kFloat64,
  kHoleyFloat64,
  kIntPtr
};
Function Documentation
AllocateBuiltin()
Builtin v8::internal::maglev::AllocateBuiltin (AllocationType alloc_type) [inline]
Definition at line 41 of file maglev-assembler.h.
                                                          {
  if (alloc_type == AllocationType::kYoung) {
    return Builtin::kAllocateInYoungGeneration;
  }
  DCHECK_EQ(alloc_type, AllocationType::kOld);
  return Builtin::kAllocateInOldGeneration;
}
References DCHECK_EQ, v8::internal::kOld, and v8::internal::kYoung.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-assembler-arm.cc}::AllocateRaw(), v8::internal::maglev::anonymous_namespace{maglev-assembler-arm64.cc}::AllocateRaw(), AllocateRaw(), v8::internal::maglev::anonymous_namespace{maglev-assembler-s390.cc}::AllocateRaw(), and v8::internal::maglev::anonymous_namespace{maglev-assembler-x64.cc}::AllocateRaw().
AllocateRaw()
template<typename T >
void v8::internal::maglev::AllocateRaw (MaglevAssembler * masm, Isolate * isolate, RegisterSnapshot register_snapshot, Register object, T size_in_bytes, AllocationType alloc_type, AllocationAlignment alignment)
Definition at line 27 of file maglev-assembler-riscv.cc.
                                                {
  DCHECK(masm->allow_allocate());
  // TODO(victorgomes): Call the runtime for large object allocation.
  // TODO(victorgomes): Support double alignment.
  DCHECK_EQ(alignment, kTaggedAligned);
  if (v8_flags.single_generation) {
    alloc_type = AllocationType::kOld;
  }
  ExternalReference top = SpaceAllocationTopAddress(isolate, alloc_type);
  ExternalReference limit = SpaceAllocationLimitAddress(isolate, alloc_type);
  ZoneLabelRef done(masm);
  MaglevAssembler::TemporaryRegisterScope temps(masm);
  Register scratch = temps.AcquireScratch();
  // We are a bit short on registers, so we use the same register for {object}
  // and {new_top}. Once we have defined {new_top}, we don't use {object} until
  // {new_top} is used for the last time. And there (at the end of this
  // function), we recover the original {object} from {new_top} by subtracting
  // {size_in_bytes}.
  Register new_top = object;
  // Check if there is enough space.
  __ LoadWord(object, __ ExternalReferenceAsOperand(top, scratch));
  __ AddWord(new_top, object, Operand(size_in_bytes));
  __ LoadWord(scratch, __ ExternalReferenceAsOperand(limit, scratch));
  // Call runtime if new_top >= limit.
  __ MacroAssembler::Branch(
      __ MakeDeferredCode(
          [](MaglevAssembler* masm, RegisterSnapshot register_snapshot,
             Register object, AllocationType alloc_type, T size_in_bytes,
             ZoneLabelRef done) {
            AllocateSlow(masm, register_snapshot, object,
                         AllocateBuiltin(alloc_type), size_in_bytes, done);
          },
          register_snapshot, object, alloc_type, size_in_bytes, done),
      ge, new_top, Operand(scratch));
  // Store new top and tag object.
  __ Move(__ ExternalReferenceAsOperand(top, scratch), new_top);
  SubSizeAndTagObject(masm, object, size_in_bytes);
  __ bind(*done);
}
References __, v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), AllocateBuiltin(), AllocateSlow(), v8::internal::MacroAssembler::Branch(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::ge, v8::internal::kOld, v8::internal::kTaggedAligned, SpaceAllocationLimitAddress(), SpaceAllocationTopAddress(), SubSizeAndTagObject(), and v8::internal::v8_flags.
Referenced by v8::internal::maglev::MaglevAssembler::Allocate().
AllocateSlow()
template<typename T >
void v8::internal::maglev::AllocateSlow (MaglevAssembler * masm, RegisterSnapshot register_snapshot, Register object, Builtin builtin, T size_in_bytes, ZoneLabelRef done) [inline]
Definition at line 265 of file maglev-assembler-inl.h.
                                                                              {
  // Remove {object} from snapshot, since it is the returned allocated
  // HeapObject.
  register_snapshot.live_registers.clear(object);
  register_snapshot.live_tagged_registers.clear(object);
  {
    SaveRegisterStateForCall save_register_state(masm, register_snapshot);
    using D = AllocateDescriptor;
    masm->Move(D::GetRegisterParameter(D::kRequestedSize), size_in_bytes);
    masm->CallBuiltin(builtin);
    save_register_state.DefineSafepoint();
    masm->Move(object, kReturnRegister0);
  }
  masm->Jump(*done);
}
References v8::internal::maglev::MaglevAssembler::CallBuiltin(), v8::internal::RegListBase< RegisterT >::clear(), D, v8::internal::maglev::SaveRegisterStateForCall::DefineSafepoint(), v8::internal::maglev::MaglevAssembler::Jump(), v8::internal::kReturnRegister0, v8::internal::maglev::RegisterSnapshot::live_registers, v8::internal::maglev::RegisterSnapshot::live_tagged_registers, and v8::internal::maglev::MaglevAssembler::Move().
Referenced by AllocateRaw().
CanBeStoreToNonEscapedObject() [1/2]
template<typename NodeT >
constexpr bool v8::internal::maglev::CanBeStoreToNonEscapedObject () [constexpr]
Definition at line 199 of file maglev-post-hoc-optimizations-processors.h.
                                              {
  return CanBeStoreToNonEscapedObject(NodeBase::opcode_of<NodeT>);
}
References CanBeStoreToNonEscapedObject().
CanBeStoreToNonEscapedObject() [2/2]
constexpr bool v8::internal::maglev::CanBeStoreToNonEscapedObject (Opcode opcode) [constexpr]
Definition at line 586 of file maglev-ir.h.
                                                           {
  switch (opcode) {
    case Opcode::kStoreMap:
    case Opcode::kStoreInt32:
    case Opcode::kStoreTrustedPointerFieldWithWriteBarrier:
    case Opcode::kStoreTaggedFieldWithWriteBarrier:
    case Opcode::kStoreTaggedFieldNoWriteBarrier:
    case Opcode::kStoreContextSlotWithWriteBarrier:
    case Opcode::kStoreFloat64:
      return true;
    default:
      return false;
  }
}
Referenced by CanBeStoreToNonEscapedObject(), and v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::IsStoreToNonEscapedObject().
CheckValueInputIs() [1/2]
void v8::internal::maglev::CheckValueInputIs (const NodeBase * node, int i, Opcode expected, MaglevGraphLabeller * graph_labeller)
Definition at line 878 of file maglev-ir.cc.
                                                            {
  ValueNode* input = node->input(i).node();
  Opcode got = input->opcode();
  if (got != expected) {
    std::ostringstream str;
    str << "Opcode error: node ";
    if (graph_labeller) {
      str << "#" << graph_labeller->NodeId(node) << " : ";
    }
    str << node->opcode() << " (input @" << i << " = " << input->opcode()
        << ") opcode " << got << " is not " << expected;
    FATAL("%s", str.str().c_str());
  }
}
References FATAL, v8::internal::maglev::NodeBase::input(), v8::internal::maglev::Input::node(), v8::internal::maglev::MaglevGraphLabeller::NodeId(), and v8::internal::maglev::NodeBase::opcode().
CheckValueInputIs() [2/2]
void v8::internal::maglev::CheckValueInputIs (const NodeBase * node, int i, ValueRepresentation expected, MaglevGraphLabeller * graph_labeller)
Definition at line 856 of file maglev-ir.cc.
                                                            {
  ValueNode* input = node->input(i).node();
  DCHECK(!input->Is<Identity>());
  ValueRepresentation got = input->properties().value_representation();
  // Allow Float64 values to be inputs when HoleyFloat64 is expected.
  bool valid =
      (got == expected) || (got == ValueRepresentation::kFloat64 &&
                            expected == ValueRepresentation::kHoleyFloat64);
  if (!valid) {
    std::ostringstream str;
    str << "Type representation error: node ";
    if (graph_labeller) {
      str << "#" << graph_labeller->NodeId(node) << " : ";
    }
    str << node->opcode() << " (input @" << i << " = " << input->opcode()
        << ") type " << got << " is not " << expected;
    FATAL("%s", str.str().c_str());
  }
}
References v8::internal::DCHECK(), FATAL, v8::internal::maglev::NodeBase::input(), v8::internal::maglev::NodeBase::Is(), kFloat64, kHoleyFloat64, v8::internal::maglev::Input::node(), v8::internal::maglev::MaglevGraphLabeller::NodeId(), v8::internal::maglev::NodeBase::opcode(), v8::internal::maglev::NodeBase::properties(), and v8::internal::maglev::OpProperties::value_representation().
Referenced by v8::internal::compiler::Verifier::Visitor::Check(), v8::internal::maglev::FixedInputNodeTMixin< InputCount, Base, Derived >::VerifyInputs(), v8::internal::maglev::GeneratorStore::VerifyInputs(), v8::internal::maglev::InlinedAllocation::VerifyInputs(), v8::internal::maglev::Call::VerifyInputs(), v8::internal::maglev::Construct::VerifyInputs(), v8::internal::maglev::CallBuiltin::VerifyInputs(), v8::internal::maglev::CallCPPBuiltin::VerifyInputs(), v8::internal::maglev::CallForwardVarargs::VerifyInputs(), v8::internal::maglev::CallRuntime::VerifyInputs(), v8::internal::maglev::CallWithSpread::VerifyInputs(), v8::internal::maglev::CallWithArrayLike::VerifyInputs(), v8::internal::maglev::CallSelf::VerifyInputs(), v8::internal::maglev::CallKnownJSFunction::VerifyInputs(), v8::internal::maglev::CallKnownApiFunction::VerifyInputs(), and v8::internal::maglev::ConstructWithSpread::VerifyInputs().
ConditionFor()
constexpr Condition v8::internal::maglev::ConditionFor (Operation operation) [constexpr]
Definition at line 1117 of file maglev-assembler.h.
                                                      {
  switch (operation) {
    case Operation::kEqual:
    case Operation::kStrictEqual:
      return kEqual;
    case Operation::kLessThan:
      return kLessThan;
    case Operation::kLessThanOrEqual:
      return kLessThanEqual;
    case Operation::kGreaterThan:
      return kGreaterThan;
    case Operation::kGreaterThanOrEqual:
      return kGreaterThanEqual;
    default:
      UNREACHABLE();
  }
}
References v8::internal::kEqual, v8::internal::kGreaterThan, v8::internal::kGreaterThanEqual, v8::internal::kLessThan, v8::internal::kLessThanEqual, and v8::internal::UNREACHABLE().
Referenced by ConditionForFloat64().
ConditionForFloat64()
constexpr Condition v8::internal::maglev::ConditionForFloat64 (Operation operation) [constexpr]
Definition at line 21 of file maglev-assembler-arm-inl.h.
                                                             {
  return ConditionFor(operation);
}
References ConditionFor().
ConditionForNaN()
constexpr Condition v8::internal::maglev::ConditionForNaN () [constexpr]
Definition at line 25 of file maglev-assembler-arm-inl.h.
{ return vs; }
References v8::internal::vs.
Referenced by v8::internal::maglev::MaglevAssembler::CompareFloat64AndBranch(), v8::internal::maglev::MaglevAssembler::CompareFloat64AndJumpIf(), v8::internal::maglev::MaglevAssembler::JumpIfHoleNan(), v8::internal::maglev::MaglevAssembler::JumpIfNan(), and v8::internal::maglev::MaglevAssembler::JumpIfNotNan().
ConditionToConditionCmpFPU()
FPUCondition v8::internal::maglev::ConditionToConditionCmpFPU (Condition condition) [inline]
Definition at line 41 of file maglev-assembler-riscv-inl.h.
                                                                    {
  switch (condition) {
    case kEqual:
      return EQ;
    case kNotEqual:
      return NE;
    case kUnsignedLessThan:
    case kLessThan:
      return LT;
    case kUnsignedGreaterThanEqual:
    case kGreaterThanEqual:
      return GE;
    case kUnsignedLessThanEqual:
    case kLessThanEqual:
      return LE;
    case kUnsignedGreaterThan:
    case kGreaterThan:
      return GT;
    default:
      break;
  }
  UNREACHABLE();
}
References v8::internal::EQ, v8::internal::GE, v8::internal::GT, v8::internal::kEqual, v8::internal::kGreaterThan, v8::internal::kGreaterThanEqual, v8::internal::kLessThan, v8::internal::kLessThanEqual, v8::internal::kNotEqual, v8::internal::kUnsignedGreaterThan, v8::internal::kUnsignedGreaterThanEqual, v8::internal::kUnsignedLessThan, v8::internal::kUnsignedLessThanEqual, v8::internal::LE, v8::internal::LT, v8::internal::NE, and v8::internal::UNREACHABLE().
DEFINE_TRUNCATE_NODE()
v8::internal::maglev::DEFINE_TRUNCATE_NODE (TruncateFloat64ToInt32 , HoleyFloat64 , OpProperties::Int32())
DefineAsConstant()
void v8::internal::maglev::DefineAsConstant (Node * node) [inline]
Definition at line 48 of file maglev-ir-inl.h.
                                         {
  node->result().SetUnallocated(compiler::UnallocatedOperand::NONE, kNoVreg);
}
References kNoVreg, v8::internal::compiler::UnallocatedOperand::NONE, v8::internal::maglev::Node::result(), and v8::internal::maglev::ValueLocation::SetUnallocated().
DefineAsFixed()
void v8::internal::maglev::DefineAsFixed (Node * node, Register reg) [inline]
Definition at line 52 of file maglev-ir-inl.h.
                                                    {
  node->result().SetUnallocated(compiler::UnallocatedOperand::FIXED_REGISTER,
                                reg.code(), kNoVreg);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::compiler::UnallocatedOperand::FIXED_REGISTER, kNoVreg, v8::internal::maglev::Node::result(), and v8::internal::maglev::ValueLocation::SetUnallocated().
DefineAsRegister()
void v8::internal::maglev::DefineAsRegister (Node * node) [inline]
Definition at line 44 of file maglev-ir-inl.h.
                                         {
  node->result().SetUnallocated(
      compiler::UnallocatedOperand::MUST_HAVE_REGISTER, kNoVreg);
}
References kNoVreg, v8::internal::compiler::UnallocatedOperand::MUST_HAVE_REGISTER, v8::internal::maglev::Node::result(), and v8::internal::maglev::ValueLocation::SetUnallocated().
Referenced by v8::internal::maglev::Int32BitwiseNot::SetValueLocationConstraints(), v8::internal::maglev::InlinedAllocation::SetValueLocationConstraints(), v8::internal::maglev::ArgumentsLength::SetValueLocationConstraints(), v8::internal::maglev::RestLength::SetValueLocationConstraints(), and v8::internal::maglev::BuiltinStringFromCharCode::SetValueLocationConstraints().
DefineSameAsFirst()
void v8::internal::maglev::DefineSameAsFirst (Node * node) [inline]
Definition at line 58 of file maglev-ir-inl.h.
                                          {
  node->result().SetUnallocated(kNoVreg, 0);
}
References kNoVreg, v8::internal::maglev::Node::result(), and v8::internal::maglev::ValueLocation::SetUnallocated().
Referenced by v8::internal::maglev::CheckedIntPtrToInt32::SetValueLocationConstraints(), and v8::internal::maglev::InlinedAllocation::SetValueLocationConstraints().
DestructivelyIntersect()
template<typename Key , typename Value , typename MergeFunc = std::equal_to<Value>>
void v8::internal::maglev::DestructivelyIntersect (ZoneMap< Key, Value > & lhs_map, const ZoneMap< Key, Value > & rhs_map, MergeFunc && func = MergeFunc())
Definition at line 38 of file maglev-interpreter-frame-state.h.
                                                            {
  // Walk the two maps in lock step. This relies on the fact that ZoneMaps are
  // sorted.
  typename ZoneMap<Key, Value>::iterator lhs_it = lhs_map.begin();
  typename ZoneMap<Key, Value>::const_iterator rhs_it = rhs_map.begin();
  while (lhs_it != lhs_map.end() && rhs_it != rhs_map.end()) {
    if (lhs_it->first < rhs_it->first) {
      // Remove from LHS elements that are not in RHS.
      lhs_it = lhs_map.erase(lhs_it);
    } else if (rhs_it->first < lhs_it->first) {
      // Skip over elements that are only in RHS.
      ++rhs_it;
    } else {
      // Apply the merge function to the values of the two iterators. If the
      // function returns false, remove the value.
      bool keep_value = func(lhs_it->second, rhs_it->second);
      if (keep_value) {
        ++lhs_it;
      } else {
        lhs_it = lhs_map.erase(lhs_it);
      }
      ++rhs_it;
    }
  }
  // If we haven't reached the end of LHS by now, then we have reached the end
  // of RHS, and the remaining items are therefore not in RHS. Remove them.
  if (lhs_it != lhs_map.end()) {
    lhs_map.erase(lhs_it, lhs_map.end());
  }
}
Referenced by v8::internal::maglev::KnownNodeAspects::Merge().
EmptyNodeType()
constexpr NodeType v8::internal::maglev::EmptyNodeType () [inline], [constexpr]
Definition at line 729 of file maglev-ir.h.
{ return static_cast<NodeType>(0); }
Referenced by v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::KnownMapsMerger::IntersectWithKnownNodeAspects().
FromConstantToBool() [1/2]
bool v8::internal::maglev::FromConstantToBool (LocalIsolate * local_isolate, ValueNode * node)
Definition at line 365 of file maglev-ir.cc.
                                                                      {
  DCHECK(IsConstantNode(node->opcode()));
  switch (node->opcode()) {
#define CASE(Name) \
  case Opcode::k##Name: { \
    return node->Cast<Name>()->ToBoolean(local_isolate); \
  }
    CONSTANT_VALUE_NODE_LIST(CASE)
#undef CASE
    default:
      UNREACHABLE();
  }
}
References CASE, CONSTANT_VALUE_NODE_LIST, v8::internal::DCHECK(), IsConstantNode(), v8::internal::maglev::NodeBase::opcode(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfToBooleanTrue(), and v8::internal::maglev::MaglevGraphBuilder::BuildToBoolean().
FromConstantToBool() [2/2]
bool v8::internal::maglev::FromConstantToBool (MaglevAssembler * masm, ValueNode * node)
GetSafepointIndexForStackSlot()
int v8::internal::maglev::GetSafepointIndexForStackSlot (int i) [inline]
Definition at line 146 of file maglev-code-gen-state.h.
                                                {
  // Safepoint tables also contain slots for all fixed frame slots (both
  // above and below the fp).
  return StandardFrameConstants::kFixedSlotCount + i;
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::StandardFrameConstants::kFixedSlotCount.
HasNumberMap()
bool v8::internal::maglev::HasNumberMap (base::Vector< const compiler::MapRef > maps) [inline]
Definition at line 1084 of file maglev-ir.h.
                                                                {
  for (compiler::MapRef map : maps) {
    if (map.instance_type() == HEAP_NUMBER_TYPE) return true;
  }
  return false;
}
HasOnlyJSArrayMaps()
bool v8::internal::maglev::HasOnlyJSArrayMaps (base::Vector< const compiler::MapRef > maps) [inline]
Definition at line 1056 of file maglev-ir.h.
                                                                      {
  for (compiler::MapRef map : maps) {
    if (!map.IsJSArrayMap()) return false;
  }
  return true;
}
HasOnlyJSObjectMaps()
bool v8::internal::maglev::HasOnlyJSObjectMaps (base::Vector< const compiler::MapRef > maps) [inline]
Definition at line 1063 of file maglev-ir.h.
                                                                       {
  for (compiler::MapRef map : maps) {
    if (!map.IsJSObjectMap()) return false;
  }
  return true;
}
Referenced by v8::internal::maglev::MaglevGraphBuilder::TryBuildElementLoadOnJSArrayOrJSObject(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildElementStoreOnJSArrayOrJSObject().
HasOnlyJSTypedArrayMaps()
bool v8::internal::maglev::HasOnlyJSTypedArrayMaps (base::Vector< const compiler::MapRef > maps) [inline]
Definition at line 1049 of file maglev-ir.h.
                                                                           {
  for (compiler::MapRef map : maps) {
    if (!map.IsJSTypedArrayMap()) return false;
  }
  return true;
}
Referenced by v8::internal::maglev::MaglevGraphBuilder::TryBuildElementAccessOnTypedArray().
HasOnlyNumberMaps()
bool v8::internal::maglev::HasOnlyNumberMaps (base::Vector< const compiler::MapRef > maps) [inline]
Definition at line 1077 of file maglev-ir.h.
                                                                     {
  for (compiler::MapRef map : maps) {
    if (map.instance_type() != HEAP_NUMBER_TYPE) return false;
  }
  return true;
}
Referenced by v8::internal::maglev::MaglevGraphBuilder::TryBuildNamedAccess().
HasOnlyStringMaps()
bool v8::internal::maglev::HasOnlyStringMaps (base::Vector< const compiler::MapRef > maps) [inline]
Definition at line 1070 of file maglev-ir.h.
                                                                     {
  for (compiler::MapRef map : maps) {
    if (!map.IsStringMap()) return false;
  }
  return true;
}
Referenced by v8::internal::maglev::MaglevGraphBuilder::TryBuildNamedAccess().
Int32Identity()
template<Operation kOperation>
static constexpr std::optional<int> v8::internal::maglev::Int32Identity () [static], [constexpr]
Definition at line 2234 of file maglev-graph-builder.cc.
                                                  {
  switch (kOperation) {
#define CASE(op, _, identity) \
  case Operation::k##op: \
    return identity;
    MAP_BINARY_OPERATION_TO_INT32_NODE(CASE)
#undef CASE
    default:
      UNREACHABLE();
  }
}
References CASE, v8::kOperation, MAP_BINARY_OPERATION_TO_INT32_NODE, and v8::internal::UNREACHABLE().
IntersectType()
constexpr NodeType v8::internal::maglev::IntersectType (NodeType left, NodeType right) [inline], [constexpr]
Definition at line 731 of file maglev-ir.h.
                                                                       {
  DCHECK(!NodeTypeIsNeverStandalone(left));
  DCHECK(!NodeTypeIsNeverStandalone(right));
  return static_cast<NodeType>(static_cast<NodeTypeInt>(left) &
                               static_cast<NodeTypeInt>(right));
}
References v8::internal::DCHECK(), and NodeTypeIsNeverStandalone().
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildCheckHeapObject(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckJSFunction(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckJSReceiver(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckJSReceiverOrNullOrUndefined(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckMaps(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckNumber(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckSeqOneByteString(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckSmi(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckString(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckStringOrOddball(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckStringOrStringWrapper(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckSymbol(), v8::internal::maglev::MaglevGraphBuilder::GetFloat64ForToNumber(), v8::internal::maglev::KnownNodeAspects::GetType(), v8::internal::maglev::KnownNodeAspects::HasDisjointType(), v8::internal::maglev::NodeInfo::IntersectType(), MakeTypeStable(), v8::internal::maglev::MergePointInterpreterFrameState::MergeValue(), NodeTypeIsUnstable(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildPolymorphicPropertyAccess().
IsBranchControlNode()
constexpr bool v8::internal::maglev::IsBranchControlNode (Opcode opcode) [constexpr]
Definition at line 548 of file maglev-ir.h.
                                                  {
  return kFirstBranchControlNodeOpcode <= opcode &&
         opcode <= kLastBranchControlNodeOpcode;
}
References kFirstBranchControlNodeOpcode, and kLastBranchControlNodeOpcode.
Referenced by v8::internal::maglev::NodeBase::Is(), and v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::PatchJumps().
IsCommutativeNode()
constexpr bool v8::internal::maglev::IsCommutativeNode (Opcode opcode) [constexpr]
Definition at line 514 of file maglev-ir.h.
                                                {
  switch (opcode) {
    case Opcode::kFloat64Add:
    case Opcode::kFloat64Multiply:
    case Opcode::kGenericStrictEqual:
    case Opcode::kInt32AddWithOverflow:
    case Opcode::kInt32BitwiseAnd:
    case Opcode::kInt32BitwiseOr:
    case Opcode::kInt32BitwiseXor:
    case Opcode::kInt32MultiplyWithOverflow:
    case Opcode::kStringEqual:
    case Opcode::kTaggedEqual:
    case Opcode::kTaggedNotEqual:
      return true;
    default:
      return false;
  }
}
Referenced by v8::internal::maglev::MaglevGraphBuilder::AddNewNodeOrGetEquivalent().
IsConditionalControlNode()
constexpr bool v8::internal::maglev::IsConditionalControlNode (Opcode opcode) [constexpr]
Definition at line 552 of file maglev-ir.h.
                                                       {
  return kFirstConditionalControlNodeOpcode <= opcode &&
         opcode <= kLastConditionalControlNodeOpcode;
}
References kFirstConditionalControlNodeOpcode, and kLastConditionalControlNodeOpcode.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::Build(), v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::GotoIfFalse(), v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::GotoIfTrue(), and v8::internal::maglev::NodeBase::Is().
IsConstantNode()
constexpr bool v8::internal::maglev::IsConstantNode (Opcode opcode) [constexpr]
Definition at line 510 of file maglev-ir.h.
                                             {
  return kFirstConstantNodeOpcode <= opcode &&
         opcode <= kLastConstantNodeOpcode;
}
References kFirstConstantNodeOpcode, and kLastConstantNodeOpcode.
Referenced by v8::internal::maglev::MaglevGraphBuilder::AddDeoptUse(), v8::internal::maglev::StraightForwardRegisterAllocator::AddMoveBeforeCurrentNode(), v8::internal::maglev::MaglevGraphBuilder::AddNewNodeOrGetEquivalent(), v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNodeResult(), v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfToBooleanTrue(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckInternalizedStringValueOrByReference(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckNumericalValue(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildNestedValue(), v8::internal::maglev::MaglevGraphBuilder::BuildNewConsStringMap(), v8::internal::maglev::MaglevGraphBuilder::BuildTaggedEqual(), v8::internal::maglev::MaglevGraphBuilder::BuildToBoolean(), v8::internal::maglev::LoopOptimizationProcessor::CanHoist(), v8::internal::maglev::MaglevGraphBuilder::CreateNewConstantNode(), v8::internal::maglev::Graph::CreateNewConstantNode(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ExceptionHandlerTrampolineBuilder::EmitMaterialisationsAndPushResults(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ExceptionHandlerTrampolineBuilder::EmitPopMaterialisedResults(), v8::internal::maglev::VirtualObject::ForEachNestedRuntimeInput(), FromConstantToBool(), v8::internal::maglev::LoadSignedIntDataViewElement::is_little_endian_constant(), v8::internal::maglev::LoadDoubleDataViewElement::is_little_endian_constant(), v8::internal::maglev::StoreSignedIntDataViewElement::is_little_endian_constant(), v8::internal::maglev::StoreDoubleDataViewElement::is_little_endian_constant(), v8::internal::maglev::Node::participate_in_cse(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::RecordMoveToRegister(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::RecordMoveToStackSlot(), v8::internal::maglev::ValueNode::SetConstantLocation(), v8::internal::maglev::ValueNode::SetNoSpill(), v8::internal::maglev::ValueNode::Spill(), v8::internal::maglev::MaglevGraphBuilder::TryGetConstantAlternative(), and v8::internal::maglev::AllocationBlock::TryPretenure().
IsControlNode()
constexpr bool v8::internal::maglev::IsControlNode (Opcode opcode) [constexpr]
Definition at line 545 of file maglev-ir.h.
                                            {
  return kFirstControlNodeOpcode <= opcode && opcode <= kLastControlNodeOpcode;
}
References kFirstControlNodeOpcode, and kLastControlNodeOpcode.
Referenced by v8::internal::maglev::NodeBase::Is(), and v8::internal::maglev::Node::participate_in_cse().
IsDoubleRepresentation()
constexpr bool v8::internal::maglev::IsDoubleRepresentation (ValueRepresentation repr) [inline], [constexpr]
Definition at line 619 of file maglev-ir.h.
                                                                       {
  return repr == ValueRepresentation::kFloat64 ||
         repr == ValueRepresentation::kHoleyFloat64;
}
References kFloat64, and kHoleyFloat64.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNodeResult(), v8::internal::maglev::StraightForwardRegisterAllocator::AllocateSpillSlot(), v8::internal::maglev::StraightForwardRegisterAllocator::UpdateUse(), and v8::internal::maglev::ValueNode::use_double_register().
IsElementsArrayWrite()
constexpr bool v8::internal::maglev::IsElementsArrayWrite (Opcode opcode) [constexpr]
Definition at line 577 of file maglev-ir.h.
                                                   {
  return opcode == Opcode::kMaybeGrowFastElements ||
         opcode == Opcode::kEnsureWritableFastElements;
}
Referenced by v8::internal::maglev::NodeBase::ClearElementsProperties(), v8::internal::maglev::NodeBase::ClearUnstableNodeAspects(), and v8::internal::maglev::MaglevGraphBuilder::MarkPossibleSideEffect().
IsEmptyNodeType()
constexpr bool v8::internal::maglev::IsEmptyNodeType (NodeType type) [inline], [constexpr]
Definition at line 874 of file maglev-ir.h.
                                                     {
  // No bits are set.
  return static_cast<int>(type) == 0;
}
References v8::internal::tracing::type.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildCheckHeapObject(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckJSFunction(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckJSReceiver(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckJSReceiverOrNullOrUndefined(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckMaps(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckNumber(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckSeqOneByteString(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckSmi(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckString(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckStringOrOddball(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckStringOrStringWrapper(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckSymbol(), v8::internal::maglev::MaglevGraphBuilder::BuildSmiUntag(), v8::internal::maglev::MaglevGraphBuilder::CanElideWriteBarrier(), v8::internal::maglev::MaglevGraphBuilder::GetFloat64ForToNumber(), v8::internal::maglev::MaglevGraphBuilder::GetInt32(), v8::internal::maglev::MaglevGraphBuilder::GetTaggedValue(), v8::internal::maglev::KnownNodeAspects::HasDisjointType(), v8::internal::maglev::MergePointInterpreterFrameState::MergeValue(), operator<<(), StaticTypeForConstant(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPolymorphicPropertyAccess(), v8::internal::maglev::MaglevGraphBuilder::TryBuildStoreField(), and v8::internal::maglev::MaglevGraphBuilder::TrySpecializeStoreContextSlot().
IsGapMoveNode()
constexpr bool v8::internal::maglev::IsGapMoveNode (Opcode opcode) [constexpr]
Definition at line 542 of file maglev-ir.h.
                                            {
  return kFirstGapMoveNodeOpcode <= opcode && opcode <= kLastGapMoveNodeOpcode;
}
References kFirstGapMoveNodeOpcode, and kLastGapMoveNodeOpcode.
Referenced by v8::internal::maglev::BasicBlock::FirstNonGapMoveId().
IsInitializingOrTransitioning()
bool v8::internal::maglev::IsInitializingOrTransitioning (StoreTaggedMode mode) [inline]
Definition at line 9006 of file maglev-ir.h.
                                                                {
  return mode == StoreTaggedMode::kInitializing ||
         mode == StoreTaggedMode::kTransitioning;
}
References mode().
IsInstanceOfLeafNodeType()
bool v8::internal::maglev::IsInstanceOfLeafNodeType (compiler::MapRef map, NodeType type, compiler::JSHeapBroker * broker) [inline]
Definition at line 893 of file maglev-ir.h.
                                                                   {
  switch (type) {
    case NodeType::kSmi:
      return false;
    case NodeType::kHeapNumber:
      return map.IsHeapNumberMap();
    case NodeType::kNull:
      return map.IsNullMap(broker);
    case NodeType::kUndefined:
      return map.IsUndefinedMap(broker);
    case NodeType::kBoolean:
      return map.IsBooleanMap(broker);
    case NodeType::kSymbol:
      return map.IsSymbolMap();
    case NodeType::kOtherString:
      // This doesn't exclude other string leaf types, which means one should
      // never test for this node type alone.
      return map.IsStringMap();
    case NodeType::kOtherSeqOneByteString:
      return map.IsSeqStringMap() && map.IsOneByteStringMap();
    // We can't prove with a map alone that an object is in RO-space, but
    // these maps will be potential candidates.
    case NodeType::kROSeqInternalizedOneByteString:
    case NodeType::kOtherSeqInternalizedOneByteString:
      return map.IsInternalizedStringMap() && map.IsSeqStringMap() &&
             map.IsOneByteStringMap();
    case NodeType::kOtherInternalizedString:
      return map.IsInternalizedStringMap();
    case NodeType::kStringWrapper:
      return map.IsStringWrapperMap();
    case NodeType::kContext:
      return map.IsContextMap();
    case NodeType::kJSArray:
      return map.IsJSArrayMap();
    case NodeType::kJSFunction:
      return map.IsJSFunctionMap();
    case NodeType::kCallable:
      return map.is_callable();
    case NodeType::kOtherCallable:
      return map.is_callable() && !map.IsJSFunctionMap();
    case NodeType::kOtherJSReceiver:
      return map.IsJSReceiverMap() && !map.IsJSArrayMap() &&
             !map.is_callable() && !map.IsStringWrapperMap();
    case NodeType::kOtherHeapObject:
      return !map.IsHeapNumberMap() && !map.IsOddballMap() &&
             !map.IsContextMap() && !map.IsSymbolMap() && !map.IsStringMap() &&
             !map.IsJSReceiverMap();
    default:
      UNREACHABLE();
  }
}
References broker(), v8::internal::compiler::MapRef::is_callable(), v8::internal::compiler::MapRef::IsBooleanMap(), v8::internal::compiler::MapRef::IsNullMap(), v8::internal::compiler::MapRef::IsOneByteStringMap(), v8::internal::compiler::MapRef::IsSeqStringMap(), v8::internal::compiler::MapRef::IsStringWrapperMap(), v8::internal::compiler::MapRef::IsUndefinedMap(), v8::internal::compiler::kSmi, v8::internal::tracing::type, and v8::internal::UNREACHABLE().
Referenced by IsInstanceOfNodeType().
IsInstanceOfNodeType()
bool v8::internal::maglev::IsInstanceOfNodeType (compiler::MapRef map, NodeType type, compiler::JSHeapBroker * broker) [inline]
Definition at line 946 of file maglev-ir.h.
                                                               {
  DCHECK(!NodeTypeIsNeverStandalone(type));
  // Early return for any heap object.
  if (NodeTypeIs(NodeType::kAnyHeapObject, type)) {
    // Unknown types will be handled here too.
    static_assert(NodeTypeIs(NodeType::kAnyHeapObject, NodeType::kUnknown));
    return true;
  }
  // Iterate over each leaf type bit in the type bitmask, and check if the map
  // matches it.
  NodeTypeInt type_bits = static_cast<NodeTypeInt>(type);
  while (type_bits != 0) {
    NodeTypeInt current_bit =
        1 << base::bits::CountTrailingZerosNonZero(type_bits);
    NodeType leaf_type = static_cast<NodeType>(current_bit);
    if (IsInstanceOfLeafNodeType(map, leaf_type, broker)) return true;
    type_bits = base::bits::ClearLsb(type_bits);
  }
  return false;
}
References broker(), v8::base::bits::ClearLsb, v8::base::bits::CountTrailingZerosNonZero(), v8::internal::DCHECK(), IsInstanceOfLeafNodeType(), NodeTypeIs(), NodeTypeIsNeverStandalone(), and v8::internal::tracing::type.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildCheckInternalizedStringValueOrByReference(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckValueByReference(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::KnownMapsMerger::IntersectWithKnownNodeAspects(), and v8::internal::maglev::MaglevGraphBuilder::SetKnownValue().
IsMaglevEnabled()
static bool v8::internal::maglev::IsMaglevEnabled () [inline], [static]
Definition at line 57 of file compiler.h.
{ return v8_flags.maglev; }
References v8::internal::v8_flags.
Referenced by v8::internal::anonymous_namespace{runtime-test.cc}::CanOptimizeFunction(), v8::internal::anonymous_namespace{compiler.cc}::CompileMaglev(), IsMaglevOsrEnabled(), v8::internal::maglev::MaglevCodeGenerator::MaglevCodeGenerator(), v8::internal::TieringManager::NotifyICChanged(), v8::internal::RUNTIME_FUNCTION(), v8::internal::anonymous_namespace{compiler.cc}::ShouldOptimize(), and v8::internal::anonymous_namespace{tiering-manager.cc}::TiersUpToMaglev().
IsMaglevOsrEnabled()
static bool v8::internal::maglev::IsMaglevOsrEnabled () [inline], [static]
Definition at line 59 of file compiler.h.
                                        {
  return IsMaglevEnabled() && v8_flags.maglev_osr;
}
References IsMaglevEnabled(), and v8::internal::v8_flags.
Referenced by v8::internal::anonymous_namespace{runtime-compiler.cc}::CompileOptimizedOSR(), v8::internal::anonymous_namespace{tiering-manager.cc}::InterruptBudgetFor(), v8::internal::maglev::MaglevCodeGenerator::MaglevCodeGenerator(), v8::internal::TieringManager::MaybeOptimizeFrame(), and v8::internal::RUNTIME_FUNCTION().
IsSimpleFieldStore()
constexpr bool v8::internal::maglev::IsSimpleFieldStore (Opcode opcode) [constexpr]
Definition at line 566 of file maglev-ir.h.
                                                 {
  return opcode == Opcode::kStoreTaggedFieldWithWriteBarrier ||
         opcode == Opcode::kStoreTaggedFieldNoWriteBarrier ||
         opcode == Opcode::kStoreDoubleField ||
         opcode == Opcode::kStoreFloat64 || opcode == Opcode::kStoreInt32 ||
         opcode == Opcode::kUpdateJSArrayLength ||
         opcode == Opcode::kStoreFixedArrayElementWithWriteBarrier ||
         opcode == Opcode::kStoreFixedArrayElementNoWriteBarrier ||
         opcode == Opcode::kStoreFixedDoubleArrayElement ||
         opcode == Opcode::kStoreTrustedPointerFieldWithWriteBarrier;
}
Referenced by v8::internal::maglev::NodeBase::ClearUnstableNodeAspects(), and v8::internal::maglev::MaglevGraphBuilder::MarkPossibleSideEffect().
IsTerminalControlNode()
constexpr bool v8::internal::maglev::IsTerminalControlNode (Opcode opcode) [constexpr]
Definition at line 560 of file maglev-ir.h.
                                                    {
  return kFirstTerminalControlNodeOpcode <= opcode &&
         opcode <= kLastTerminalControlNodeOpcode;
}
References kFirstTerminalControlNodeOpcode, and kLastTerminalControlNodeOpcode.
Referenced by v8::internal::maglev::NodeBase::Is().
IsTypedArrayStore()
constexpr bool v8::internal::maglev::IsTypedArrayStore (Opcode opcode) [constexpr]
Definition at line 581 of file maglev-ir.h.
                                                {
  return opcode == Opcode::kStoreIntTypedArrayElement ||
         opcode == Opcode::kStoreDoubleTypedArrayElement;
}
Referenced by v8::internal::maglev::MaglevGraphBuilder::MarkPossibleSideEffect().
IsUnconditionalControlNode()
constexpr bool v8::internal::maglev::IsUnconditionalControlNode (Opcode opcode) [constexpr]
Definition at line 556 of file maglev-ir.h.
                                                         {
  return kFirstUnconditionalControlNodeOpcode <= opcode &&
         opcode <= kLastUnconditionalControlNodeOpcode;
}
References kFirstUnconditionalControlNodeOpcode, and kLastUnconditionalControlNodeOpcode.
Referenced by v8::internal::maglev::NodeBase::Is(), and v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::PatchJumps().
IsValueNode()
constexpr bool v8::internal::maglev::IsValueNode (Opcode opcode) [constexpr]
Definition at line 507 of file maglev-ir.h.
                                          {
  return kFirstValueNodeOpcode <= opcode && opcode <= kLastValueNodeOpcode;
}
References kFirstValueNodeOpcode, and kLastValueNodeOpcode.
Referenced by v8::internal::maglev::NodeBase::Is(), v8::internal::maglev::AnyUseMarkingProcessor::Process(), and v8::internal::maglev::DeadNodeSweepingProcessor::Process().
IsZeroCostNode()
constexpr bool v8::internal::maglev::IsZeroCostNode (Opcode opcode) [constexpr]
Definition at line 532 of file maglev-ir.h.
                                             {
  switch (opcode) {
    case Opcode::kTruncateUint32ToInt32:
    case Opcode::kUnsafeTruncateUint32ToInt32:
    case Opcode::kIdentity:
      return true;
    default:
      return false;
  }
}
Referenced by v8::internal::maglev::Node::participate_in_cse().
IsZeroExtendedRepresentation()
constexpr bool v8::internal::maglev::IsZeroExtendedRepresentation (ValueRepresentation repr) [inline], [constexpr]
Definition at line 624 of file maglev-ir.h.
                                                                             {
#if defined(V8_TARGET_ARCH_RISCV64)
  // on RISC-V int32 are always sign-extended
  return false;
#else
  return (repr == ValueRepresentation::kUint32 ||
          repr == ValueRepresentation::kInt32);
#endif
}
References kInt32, and kUint32.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::Process().
LOAD_CONSTANT_TYPED_ARRAY()
UINT32_ELEMENTS INT32_ELEMENTS v8::internal::maglev::LOAD_CONSTANT_TYPED_ARRAY (LoadUnsignedIntConstantTypedArrayElement , OpProperties::Uint32() , UINT8_ELEMENTS , UINT8_CLAMPED_ELEMENTS , UINT16_ELEMENTS , UINT16_ELEMENTS , UINT32_ELEMENTS)
LOAD_TYPED_ARRAY() [1/2]
UINT32_ELEMENTS v8::internal::maglev::LOAD_TYPED_ARRAY (LoadDoubleTypedArrayElement , OpProperties::Float64() , FLOAT32_ELEMENTS , FLOAT64_ELEMENTS)
LOAD_TYPED_ARRAY() [2/2]
v8::internal::maglev::LOAD_TYPED_ARRAY (LoadSignedIntTypedArrayElement , OpProperties::Int32() , INT8_ELEMENTS , INT16_ELEMENTS , INT32_ELEMENTS)
LoadMergeState() [1/2]
bool v8::internal::maglev::LoadMergeState (RegisterState state, RegisterMerge ** merge) [inline]
Definition at line 74 of file maglev-regalloc-data.h.
                                                                       {
  DCHECK(state.GetPayload().is_initialized);
  if (state.GetPayload().is_merge) {
    *merge = static_cast<RegisterMerge*>(state.GetPointer());
    return true;
  }
  *merge = nullptr;
  return false;
}
References v8::internal::DCHECK(), v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::GetPayload(), and v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::GetPointer().
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::EmitBlockEndGapMoves(), v8::internal::maglev::BasicBlock::HasPhisOrRegisterMerges(), v8::internal::maglev::StraightForwardRegisterAllocator::InitializeRegisterValues(), LoadMergeState(), and v8::internal::maglev::StraightForwardRegisterAllocator::MergeRegisterValues().
LoadMergeState() [2/2]
bool v8::internal::maglev::LoadMergeState (RegisterState state, ValueNode ** node, RegisterMerge ** merge) [inline]
Definition at line 84 of file maglev-regalloc-data.h.
                                                  {
  DCHECK(state.GetPayload().is_initialized);
  if (LoadMergeState(state, merge)) {
    *node = (*merge)->node;
    return true;
  }
  *node = static_cast<ValueNode*>(state.GetPointer());
  return false;
}
References v8::internal::DCHECK(), v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::GetPayload(), v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::GetPointer(), and LoadMergeState().
MakeTypeStable()
constexpr NodeType v8::internal::maglev::MakeTypeStable (NodeType type) [inline], [constexpr]
Definition at line 797 of file maglev-ir.h.
                                                        {
  DCHECK(!NodeTypeIsNeverStandalone(type));
  if (!NodeTypeIsUnstable(type)) return type;
  // Strings can be in-place internalized, turned into thin strings, and
  // in-place externalized, and byteness can change from one->two byte (because
  // of internalized external strings with two-byte encoding of one-byte data)
  // or two->one byte (because of internalizing a two-byte slice with one-byte
  // data). The only invariant that we can preserve is that internalized strings
  // stay internalized.
  DCHECK(NodeTypeCanBe(type, NodeType::kString));
  // Extract out the string part of the node type.
  NodeType string_type = IntersectType(type, NodeType::kString);
  if (NodeTypeIs(string_type, NodeType::kInternalizedString)) {
    // Strings that can't be anything but internalized become generic
    // internalized.
    type = UnionType(type, NodeType::kInternalizedString);
  } else {
    // All other strings become fully generic.
    type = UnionType(type, NodeType::kString);
  }
  DCHECK(!NodeTypeIsUnstable(type));
  return type;
}
References v8::internal::DCHECK(), IntersectType(), NodeTypeCanBe(), NodeTypeIs(), NodeTypeIsNeverStandalone(), NodeTypeIsUnstable(), v8::internal::tracing::type, and UnionType().
Referenced by v8::internal::maglev::NodeInfo::ClearUnstableMaps().
NodeTypeCanBe()
constexpr bool v8::internal::maglev::NodeTypeCanBe (NodeType type, NodeType to_check) [inline], [constexpr]
Definition at line 749 of file maglev-ir.h.
                                                                      {
  DCHECK(!NodeTypeIsNeverStandalone(type));
  DCHECK(!NodeTypeIsNeverStandalone(to_check));
  NodeTypeInt right = static_cast<NodeTypeInt>(to_check);
  return (static_cast<NodeTypeInt>(type) & (right)) != 0;
}
References v8::internal::DCHECK(), NodeTypeIsNeverStandalone(), and v8::internal::tracing::type.
Referenced by MakeTypeStable(), and NodeTypeIsUnstable().
NodeTypeIs()
constexpr bool v8::internal::maglev::NodeTypeIs (NodeType type, NodeType to_check) [inline], [constexpr]
Definition at line 743 of file maglev-ir.h.
                                                                   {
  DCHECK(!NodeTypeIsNeverStandalone(type));
  DCHECK(!NodeTypeIsNeverStandalone(to_check));
  NodeTypeInt right = static_cast<NodeTypeInt>(to_check);
  return (static_cast<NodeTypeInt>(type) & (~right)) == 0;
}
References v8::internal::DCHECK(), NodeTypeIsNeverStandalone(), and v8::internal::tracing::type.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfToBooleanTrue(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckMaps(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckNumericalValue(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadJSFunctionContext(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadJSFunctionFeedbackCell(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadStringLength(), v8::internal::maglev::MaglevGraphBuilder::BuildUnwrapStringWrapper(), v8::internal::maglev::KnownNodeAspects::CheckType(), v8::internal::maglev::KnownNodeAspects::CheckTypes(), v8::internal::maglev::MaglevPhiRepresentationSelector::ConvertTaggedPhiTo(), v8::internal::maglev::KnownNodeAspects::EnsureType(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::GetCheckType(), v8::internal::maglev::MaglevGraphBuilder::GetFloat64ForToNumber(), v8::internal::maglev::MaglevGraphBuilder::GetInternalizedString(), v8::internal::maglev::MaglevGraphBuilder::GetTruncatedInt32ForToNumber(), v8::internal::maglev::KnownNodeAspects::GetType(), IsInstanceOfNodeType(), MakeTypeStable(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::NodeInfoIncludes(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::NodeInfoTypeIs(), v8::internal::maglev::MaglevPhiRepresentationSelector::ProcessPhi(), v8::internal::maglev::Phi::promote_post_loop_type(), v8::internal::maglev::MaglevGraphBuilder::SetKnownValue(), v8::internal::maglev::NodeInfo::SetPossibleMaps(), v8::internal::maglev::ValueNode::StaticTypeIs(), v8::internal::maglev::MaglevGraphBuilder::TryBuildNewConsString(), v8::internal::maglev::MergePointInterpreterFrameState::TryMergeLoop(), and v8::internal::maglev::KnownNodeAspects::UpdateMayHaveAliasingContexts().
NodeTypeIsNeverStandalone()
constexpr bool v8::internal::maglev::NodeTypeIsNeverStandalone (NodeType type) [inline], [constexpr]
Definition at line 714 of file maglev-ir.h.
                                                               {
  switch (type) {
    // "Other" string types should be considered internal and never appear as
    // standalone leaf types.
    case NodeType::kOtherCallable:
    case NodeType::kOtherInternalizedString:
    case NodeType::kOtherSeqInternalizedOneByteString:
    case NodeType::kOtherSeqOneByteString:
    case NodeType::kOtherString:
      return true;
    default:
      return false;
  }
}
References v8::internal::tracing::type.
Referenced by IntersectType(), IsInstanceOfNodeType(), MakeTypeStable(), NodeTypeCanBe(), NodeTypeIs(), NodeTypeIsUnstable(), and UnionType().
NodeTypeIsUnstable()
constexpr bool v8::internal::maglev::NodeTypeIsUnstable (NodeType type) [inline], [constexpr]
Definition at line 756 of file maglev-ir.h.
                                                        {
  DCHECK(!NodeTypeIsNeverStandalone(type));
  // Any type that can be a string might be unstable, if the string part of the
  // type is unstable.
  if (NodeTypeCanBe(type, NodeType::kString)) {
    // Extract out the string part of the node type.
    NodeType string_type = IntersectType(type, NodeType::kString);
    // RO-space strings are ok, since they can't change.
    if (string_type == NodeType::kROSeqInternalizedOneByteString) return false;
    // The generic internalized string type is ok, since it doesn't consider
    // seqness and internalized strings stay internalized.
    if (string_type == NodeType::kInternalizedString) return false;
    // The generic string type is ok, since it defines all strings.
    if (string_type == NodeType::kString) return false;
    // Otherwise, a string can get in-place externalized, or in-place converted
    // to thin if not already internalized, both of which lose seq-ness.
    // TODO(leszeks): We could probably consider byteness of internalized
    // strings to be stable, since we can't change byteness with in-place
    // externalization.
    return true;
  }
  // All other node types are stable.
  return false;
}
References v8::internal::DCHECK(), IntersectType(), NodeTypeCanBe(), NodeTypeIsNeverStandalone(), and v8::internal::tracing::type.
Referenced by v8::internal::maglev::KnownNodeAspects::EnsureType(), and MakeTypeStable().
NodeTypeMayBeNullOrUndefined()
bool v8::internal::maglev::NodeTypeMayBeNullOrUndefined (NodeType type) [inline]
Definition at line 1002 of file maglev-ir.h.
                                                        {
  return (static_cast<int>(type) &
          static_cast<int>(NodeType::kNullOrUndefined)) != 0;
}
References v8::internal::tracing::type.
Referenced by v8::internal::maglev::KnownNodeAspects::MayBeNullOrUndefined().
OpcodeToString()
const char * v8::internal::maglev::OpcodeToString (Opcode opcode)
Definition at line 52 of file maglev-ir.cc.
                                          {
#define DEF_NAME(Name) #Name,
  static constexpr const char* const names[] = {NODE_BASE_LIST(DEF_NAME)};
#undef DEF_NAME
  return names[static_cast<int>(opcode)];
}
References DEF_NAME, and NODE_BASE_LIST.
Referenced by v8::internal::maglev::MaglevPhiRepresentationSelector::GetReplacementForPhiInputConversion(), and operator<<().
OperationValue()
template<Operation kOperation, typename type >
bool v8::internal::maglev::OperationValue (type left, type right)
Definition at line 3044 of file maglev-graph-builder.cc.
                                           {
  switch (kOperation) {
    case Operation::kEqual:
    case Operation::kStrictEqual:
      return left == right;
    case Operation::kLessThan:
      return left < right;
    case Operation::kLessThanOrEqual:
      return left <= right;
    case Operation::kGreaterThan:
      return left > right;
    case Operation::kGreaterThanOrEqual:
      return left >= right;
  }
}
References v8::internal::kEqual, v8::internal::kGreaterThan, v8::internal::kLessThan, and v8::kOperation.
operator<<() [1/9]
std::ostream& v8::internal::maglev::operator<< (std::ostream & os, const AssertCondition cond) [inline]
Definition at line 6750 of file maglev-ir.h.
                                                                          {
  switch (cond) {
#define CASE(Name) \
  case AssertCondition::k##Name: \
    os << #Name; \
    break;
    ASSERT_CONDITION(CASE)
#undef CASE
  }
  return os;
}
References ASSERT_CONDITION, and CASE.
operator<<() [2/9]
std::ostream& v8::internal::maglev::operator<< (std::ostream & os, const PrintNode & printer) [inline]
Definition at line 130 of file maglev-graph-labeller.h.
                                                                        {
  printer.Print(os);
  return os;
}
References v8::internal::maglev::PrintNode::Print().
operator<<() [3/9]
std::ostream& v8::internal::maglev::operator<< (std::ostream & os, const PrintNodeLabel & printer) [inline]
Definition at line 135 of file maglev-graph-labeller.h.
                                                               {
  printer.Print(os);
  return os;
}
operator<<() [4/9]
std::ostream& v8::internal::maglev::operator<< (std::ostream & os, const TaggedToFloat64ConversionType & conversion_type) [inline]
Definition at line 1037 of file maglev-ir.h.
                                                                          {
  switch (conversion_type) {
    case TaggedToFloat64ConversionType::kOnlyNumber:
      return os << "Number";
    case TaggedToFloat64ConversionType::kNumberOrBoolean:
      return os << "NumberOrBoolean";
    case TaggedToFloat64ConversionType::kNumberOrOddball:
      return os << "NumberOrOddball";
  }
}
References kNumberOrBoolean, kNumberOrOddball, and kOnlyNumber.
operator<<() [5/9]
std::ostream& v8::internal::maglev::operator<< (std::ostream & os, const UseRepresentation & repr) [inline]
Definition at line 9816 of file maglev-ir.h.
                                                               {
  switch (repr) {
    case UseRepresentation::kTagged:
      return os << "Tagged";
    case UseRepresentation::kInt32:
      return os << "Int32";
    case UseRepresentation::kTruncatedInt32:
      return os << "TruncatedInt32";
    case UseRepresentation::kUint32:
      return os << "Uint32";
    case UseRepresentation::kFloat64:
      return os << "Float64";
    case UseRepresentation::kHoleyFloat64:
      return os << "HoleyFloat64";
  }
}
operator<<() [6/9]
std::ostream& v8::internal::maglev::operator<< (std::ostream & os, const ValueRepresentation & repr) [inline]
Definition at line 1019 of file maglev-ir.h.
                                                                 {
  switch (repr) {
    case ValueRepresentation::kTagged:
      return os << "Tagged";
    case ValueRepresentation::kInt32:
      return os << "Int32";
    case ValueRepresentation::kUint32:
      return os << "Uint32";
    case ValueRepresentation::kFloat64:
      return os << "Float64";
    case ValueRepresentation::kHoleyFloat64:
      return os << "HoleyFloat64";
    case ValueRepresentation::kIntPtr:
      return os << "Word64";
  }
}
References kFloat64, kHoleyFloat64, kInt32, kIntPtr, kTagged, and kUint32.
operator<<() [7/9]
std::ostream& v8::internal::maglev::operator<< (std::ostream & os, Opcode opcode) [inline]
Definition at line 460 of file maglev-ir.h.
                                                             {
  return os << OpcodeToString(opcode);
}
References OpcodeToString().
operator<<() [8/9]
std::ostream & v8::internal::maglev::operator<< (std::ostream & os, StoreMap::Kind kind)
Definition at line 8239 of file maglev-ir.cc.
                                                          {
  switch (kind) {
    case StoreMap::Kind::kInitializing:
      os << "Initializing";
      break;
    case StoreMap::Kind::kInlinedAllocation:
      os << "InlinedAllocation";
      break;
    case StoreMap::Kind::kTransitioning:
      os << "Transitioning";
      break;
  }
  return os;
}
References v8::internal::maglev::StoreMap::kInitializing, v8::internal::maglev::StoreMap::kInlinedAllocation, and v8::internal::maglev::StoreMap::kTransitioning.
operator<<() [9/9]
std::ostream& v8::internal::maglev::operator<< (std::ostream & out, const NodeType & type) [inline]
Definition at line 970 of file maglev-ir.h.
                                                                     {
  if (IsEmptyNodeType(type)) {
    out << "Empty";
    return out;
  }
  switch (type) {
#define CASE(Name, _) \
  case NodeType::k##Name: \
    out << #Name; \
    break;
    NODE_TYPE_LIST(CASE)
#undef CASE
    default:
#define CASE(Name, _) \
  if (NodeTypeIs(NodeType::k##Name, type)) { \
    if constexpr (NodeType::k##Name != NodeType::kUnknown) { \
      out << #Name "|"; \
    } \
  }
      LEAF_NODE_TYPE_LIST(CASE)
#undef CASE
  }
  return out;
}
References CASE, IsEmptyNodeType(), LEAF_NODE_TYPE_LIST, NODE_TYPE_LIST, and v8::internal::tracing::type.
operator==()
constexpr bool v8::internal::maglev::operator== (const RegisterStateFlags & left, const RegisterStateFlags & right) [constexpr]
Definition at line 57 of file maglev-regalloc-data.h.
                                                           {
  return left.is_initialized == right.is_initialized &&
         left.is_merge == right.is_merge;
}
References v8::internal::maglev::RegisterStateFlags::is_initialized, and v8::internal::maglev::RegisterStateFlags::is_merge.
PrintGraph()
void v8::internal::maglev::PrintGraph (std::ostream & os, Graph *const graph) [inline]
Definition at line 94 of file maglev-graph-printer.h.
                                           {}
Referenced by v8::internal::maglev::MaglevCompiler::Compile(), v8::internal::compiler::turboshaft::Pipeline::Run(), and v8::internal::maglev::MaglevInliner::Run().
RepeatValue()
template<typename T >
auto v8::internal::maglev::RepeatValue (T val, int count)
Definition at line 1091 of file maglev-assembler.h.
                                   {
  return base::make_iterator_range(RepeatIterator<T>(val, 0),
                                   RepeatIterator<T>(val, count));
}
References v8::base::make_iterator_range().
requires()
template<typename Derived , ValueRepresentation FloatType>
v8::internal::maglev::requires (FloatType = = ValueRepresentation::kFloat64 || FloatType == ValueRepresentation::kHoleyFloat64)
ScaleFactorFromInt()
ScaleFactor v8::internal::maglev::ScaleFactorFromInt (int n) [inline]
Definition at line 45 of file maglev-assembler-x64-inl.h.
                                             {
  switch (n) {
    case 1:
      return times_1;
    case 2:
      return times_2;
    case 4:
      return times_4;
    case 8:
      return times_8;
    default:
      UNREACHABLE();
  }
}
References v8::internal::times_1, v8::internal::times_2, v8::internal::times_4, v8::internal::times_8, and v8::internal::UNREACHABLE().
ShiftFromScale()
int v8::internal::maglev::ShiftFromScale (int n) [inline]
Definition at line 27 of file maglev-assembler-arm-inl.h.
                                 {
  switch (n) {
    case 1:
      return 0;
    case 2:
      return 1;
    case 4:
      return 2;
    case 8:
      return 3;
    default:
      UNREACHABLE();
  }
}
References v8::internal::UNREACHABLE().
Referenced by v8::internal::maglev::MaglevAssembler::LoadTaggedFieldByIndex(), and v8::internal::maglev::MaglevAssembler::TypedArrayElementOperand().
SpaceAllocationLimitAddress()
ExternalReference v8::internal::maglev::SpaceAllocationLimitAddress (Isolate * isolate, AllocationType alloc_type) [inline]
Definition at line 32 of file maglev-assembler.h.
                                                 {
  if (alloc_type == AllocationType::kYoung) {
    return ExternalReference::new_space_allocation_limit_address(isolate);
  }
  DCHECK_EQ(alloc_type, AllocationType::kOld);
  return ExternalReference::old_space_allocation_limit_address(isolate);
}
References DCHECK_EQ, v8::internal::kOld, and v8::internal::kYoung.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-assembler-arm.cc}::AllocateRaw(), v8::internal::maglev::anonymous_namespace{maglev-assembler-arm64.cc}::AllocateRaw(), AllocateRaw(), v8::internal::maglev::anonymous_namespace{maglev-assembler-s390.cc}::AllocateRaw(), and v8::internal::maglev::anonymous_namespace{maglev-assembler-x64.cc}::AllocateRaw().
SpaceAllocationTopAddress()
ExternalReference v8::internal::maglev::SpaceAllocationTopAddress (Isolate * isolate, AllocationType alloc_type) [inline]
Definition at line 23 of file maglev-assembler.h.
                                                                              {
  if (alloc_type == AllocationType::kYoung) {
    return ExternalReference::new_space_allocation_top_address(isolate);
  }
  DCHECK_EQ(alloc_type, AllocationType::kOld);
  return ExternalReference::old_space_allocation_top_address(isolate);
}
References DCHECK_EQ, v8::internal::kOld, and v8::internal::kYoung.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-assembler-arm.cc}::AllocateRaw(), v8::internal::maglev::anonymous_namespace{maglev-assembler-arm64.cc}::AllocateRaw(), AllocateRaw(), v8::internal::maglev::anonymous_namespace{maglev-assembler-s390.cc}::AllocateRaw(), and v8::internal::maglev::anonymous_namespace{maglev-assembler-x64.cc}::AllocateRaw().
StaticPropertiesForOpcode()
constexpr OpProperties v8::internal::maglev::StaticPropertiesForOpcode (Opcode opcode) [inline], [constexpr]
Definition at line 11851 of file maglev-ir.h.
                                                                       {
  switch (opcode) {
#define CASE(op) \
  case Opcode::k##op: \
    return op::kProperties;
    NODE_BASE_LIST(CASE)
#undef CASE
  }
}
References CASE, and NODE_BASE_LIST.
Referenced by v8::internal::maglev::MaglevGraphBuilder::AddNewNodeOrGetEquivalent(), v8::internal::maglev::Node::needs_epoch_check(), v8::internal::maglev::NodeBase::OverwriteWith(), and v8::internal::maglev::Node::participate_in_cse().
StaticTypeForConstant()
NodeType v8::internal::maglev::StaticTypeForConstant (compiler::JSHeapBroker * broker, compiler::ObjectRef ref) [inline]
Definition at line 879 of file maglev-ir.h.
                                                             {
  if (ref.IsSmi()) return NodeType::kSmi;
  NodeType type = StaticTypeForMap(ref.AsHeapObject().map(broker), broker);
  DCHECK(!IsEmptyNodeType(type));
  if (type == NodeType::kInternalizedString && ref.is_read_only()) {
    if (ref.AsString().IsSeqString() &&
        ref.AsString().IsOneByteRepresentation()) {
      type = NodeType::kROSeqInternalizedOneByteString;
    }
  }
  return type;
}
References broker(), v8::internal::DCHECK(), IsEmptyNodeType(), v8::internal::compiler::kSmi, StaticTypeForMap(), and v8::internal::tracing::type.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildCheckValueByReference(), v8::internal::maglev::ValueNode::GetStaticType(), and v8::internal::maglev::MaglevGraphBuilder::SetKnownValue().
StaticTypeForMap()
NodeType v8::internal::maglev::StaticTypeForMap (compiler::MapRef map, compiler::JSHeapBroker * broker) [inline]
Definition at line 842 of file maglev-ir.h.
                                                               {
  if (map.IsHeapNumberMap()) return NodeType::kHeapNumber;
  if (map.IsStringMap()) {
    if (map.IsInternalizedStringMap()) {
      return NodeType::kInternalizedString;
    }
    if (map.IsSeqStringMap() && map.IsOneByteStringMap()) {
      return NodeType::kSeqOneByteString;
    }
    return NodeType::kString;
  }
  if (map.IsStringWrapperMap()) return NodeType::kStringWrapper;
  if (map.IsSymbolMap()) return NodeType::kSymbol;
  if (map.IsBooleanMap(broker)) return NodeType::kBoolean;
  if (map.IsOddballMap()) {
    // Oddball but not a Boolean.
    return NodeType::kNullOrUndefined;
  }
  if (map.IsContextMap()) return NodeType::kContext;
  if (map.IsJSArrayMap()) return NodeType::kJSArray;
  if (map.IsJSFunctionMap()) return NodeType::kJSFunction;
  if (map.is_callable()) {
    return NodeType::kCallable;
  }
  if (map.IsJSReceiverMap()) {
    // JSReceiver but not any of the above.
    return NodeType::kOtherJSReceiver;
  }
  return NodeType::kOtherHeapObject;
}
References broker(), v8::internal::compiler::MapRef::is_callable(), v8::internal::compiler::MapRef::IsBooleanMap(), v8::internal::compiler::MapRef::IsOneByteStringMap(), v8::internal::compiler::MapRef::IsSeqStringMap(), and v8::internal::compiler::MapRef::IsStringWrapperMap().
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildLoadField(), v8::internal::maglev::MaglevGraphBuilder::BuildStoreMap(), v8::internal::maglev::MaglevGraphBuilder::BuildTransitionElementsKindAndCompareMaps(), v8::internal::maglev::MaglevGraphBuilder::BuildTransitionElementsKindOrCheckMap(), v8::internal::maglev::ValueNode::GetStaticType(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::KnownMapsMerger::InsertMap(), v8::internal::maglev::NodeInfo::SetPossibleMaps(), and StaticTypeForConstant().
STORE_CONSTANT_TYPED_ARRAY()
v8::internal::maglev::STORE_CONSTANT_TYPED_ARRAY (StoreIntConstantTypedArrayElement , OpProperties::CanWrite() , ValueRepresentation::kInt32 , INT8_ELEMENTS , INT16_ELEMENTS , INT32_ELEMENTS , UINT8_ELEMENTS , UINT8_CLAMPED_ELEMENTS , UINT16_ELEMENTS , UINT16_ELEMENTS , UINT32_ELEMENTS)
STORE_TYPED_ARRAY()
v8::internal::maglev::STORE_TYPED_ARRAY (StoreIntTypedArrayElement , OpProperties::CanWrite() , ValueRepresentation::kInt32 , INT8_ELEMENTS , INT16_ELEMENTS , INT32_ELEMENTS , UINT8_ELEMENTS , UINT8_CLAMPED_ELEMENTS , UINT16_ELEMENTS , UINT16_ELEMENTS , UINT32_ELEMENTS)
SubSizeAndTagObject() [1/2]
void v8::internal::maglev::SubSizeAndTagObject (MaglevAssembler * masm, Register object, int size_in_bytes)
Definition at line 21 of file maglev-assembler-riscv.cc.
                                            {
  __ AddWord(object, object, Operand(kHeapObjectTag - size_in_bytes));
}
References __, and v8::internal::kHeapObjectTag.
SubSizeAndTagObject() [2/2]
void v8::internal::maglev::SubSizeAndTagObject (MaglevAssembler * masm, Register object, Register size_in_bytes)
Definition at line 15 of file maglev-assembler-riscv.cc.
                                                 {
  __ SubWord(object, object, Operand(size_in_bytes));
  __ AddWord(object, object, Operand(kHeapObjectTag));
}
References __, and v8::internal::kHeapObjectTag.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-assembler-arm.cc}::AllocateRaw(), v8::internal::maglev::anonymous_namespace{maglev-assembler-arm64.cc}::AllocateRaw(), AllocateRaw(), and v8::internal::maglev::anonymous_namespace{maglev-assembler-s390.cc}::AllocateRaw().
ToCondition()
Condition v8::internal::maglev::ToCondition (AssertCondition cond) [inline]
Definition at line 1107 of file maglev-assembler.h.
                                                   {
  switch (cond) {
#define CASE(Name) \
  case AssertCondition::k##Name: \
    return k##Name;
    ASSERT_CONDITION(CASE)
#undef CASE
  }
}
References ASSERT_CONDITION, and CASE.
ToDoubleRegister() [1/2]
DoubleRegister v8::internal::maglev::ToDoubleRegister (const compiler::InstructionOperand & operand) [inline]
Definition at line 156 of file maglev-code-gen-state.h.
                                               {
  return compiler::AllocatedOperand::cast(operand).GetDoubleRegister();
}
References v8::internal::compiler::LocationOperand::cast(), and v8::internal::compiler::LocationOperand::GetDoubleRegister().
Referenced by v8::internal::maglev::CheckFloat64SameValue::GenerateCode(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::Process(), v8::internal::maglev::StraightForwardRegisterAllocator::SaveRegisterSnapshot(), ToDoubleRegister(), and ToRegisterT().
ToDoubleRegister() [2/2]
DoubleRegister v8::internal::maglev::ToDoubleRegister (const ValueLocation & location) [inline]
Definition at line 174 of file maglev-code-gen-state.h.
                                                                      {
  return ToDoubleRegister(location.operand());
}
References v8::internal::maglev::ValueLocation::operand(), and ToDoubleRegister().
ToRegister() [1/2]
Register v8::internal::maglev::ToRegister (const compiler::InstructionOperand & operand) [inline]
Definition at line 152 of file maglev-code-gen-state.h.
                                                                      {
  return compiler::AllocatedOperand::cast(operand).GetRegister();
}
References v8::internal::compiler::LocationOperand::cast(), and v8::internal::compiler::LocationOperand::GetRegister().
Referenced by v8::internal::maglev::MaglevAssembler::FromAnyToRegister(), v8::internal::maglev::Int32AbsWithOverflow::GenerateCode(), v8::internal::maglev::InlinedAllocation::GenerateCode(), v8::internal::maglev::ArgumentsLength::GenerateCode(), v8::internal::maglev::RestLength::GenerateCode(), v8::internal::maglev::BuiltinStringFromCharCode::GenerateCode(), v8::internal::maglev::MaglevAssembler::IsRootConstant(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::Process(), v8::internal::maglev::detail::PushAligned(), v8::internal::maglev::StraightForwardRegisterAllocator::SaveRegisterSnapshot(), ToRegister(), v8::internal::maglev::detail::ToRegister(), and ToRegisterT().
ToRegister() [2/2]
Register v8::internal::maglev::ToRegister (const ValueLocation & location) [inline]
Definition at line 170 of file maglev-code-gen-state.h.
                                                          {
  return ToRegister(location.operand());
}
References v8::internal::maglev::ValueLocation::operand(), and ToRegister().
ToRegisterT()
template<typename RegisterT >
auto v8::internal::maglev::ToRegisterT (const compiler::InstructionOperand & operand) [inline]
Definition at line 162 of file maglev-code-gen-state.h.
                                                                   {
  if constexpr (std::is_same_v<RegisterT, Register>) {
    return ToRegister(operand);
  } else {
    return ToDoubleRegister(operand);
  }
}
References ToDoubleRegister(), and ToRegister().
ToValueRepresentation()
ValueRepresentation v8::internal::maglev::ToValueRepresentation (MachineType type)
Definition at line 840 of file maglev-ir.cc.
                                                            {
  switch (type.representation()) {
    case MachineRepresentation::kTagged:
    case MachineRepresentation::kTaggedSigned:
    case MachineRepresentation::kTaggedPointer:
      return ValueRepresentation::kTagged;
    case MachineRepresentation::kFloat64:
      return ValueRepresentation::kFloat64;
    case MachineRepresentation::kWord64:
      DCHECK_EQ(kSystemPointerSize, 8);
      return ValueRepresentation::kIntPtr;
    default:
      return ValueRepresentation::kInt32;
  }
}
References DCHECK_EQ, v8::internal::kFloat64, kFloat64, kInt32, kIntPtr, v8::internal::kSystemPointerSize, v8::internal::kTagged, kTagged, v8::internal::kTaggedPointer, v8::internal::kTaggedSigned, v8::internal::kWord64, and v8::internal::tracing::type.
Referenced by v8::internal::maglev::CallBuiltin::VerifyInputs().
UnionType()
constexpr NodeType v8::internal::maglev::UnionType (NodeType left, NodeType right) [inline], [constexpr]
Definition at line 737 of file maglev-ir.h.
                                                                   {
  DCHECK(!NodeTypeIsNeverStandalone(left));
  DCHECK(!NodeTypeIsNeverStandalone(right));
  return static_cast<NodeType>(static_cast<NodeTypeInt>(left) |
                               static_cast<NodeTypeInt>(right));
}
References v8::internal::DCHECK(), and NodeTypeIsNeverStandalone().
Referenced by v8::internal::torque::UnionType::FromType(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::KnownMapsMerger::InsertMap(), MakeTypeStable(), v8::internal::maglev::Phi::merge_post_loop_type(), v8::internal::maglev::Phi::merge_type(), v8::internal::maglev::MergePointInterpreterFrameState::MergeValue(), v8::internal::maglev::MergePointInterpreterFrameState::MergeVirtualObjectValue(), v8::internal::maglev::NodeInfo::SetPossibleMaps(), and v8::internal::maglev::NodeInfo::UnionType().
UnsignedConditionFor()
constexpr Condition v8::internal::maglev::UnsignedConditionFor (Operation operation) [constexpr]
Definition at line 1135 of file maglev-assembler.h.
                                                              {
  switch (operation) {
    case Operation::kEqual:
    case Operation::kStrictEqual:
      return kEqual;
    case Operation::kLessThan:
      return kUnsignedLessThan;
    case Operation::kLessThanOrEqual:
      return kUnsignedLessThanEqual;
    case Operation::kGreaterThan:
      return kUnsignedGreaterThan;
    case Operation::kGreaterThanOrEqual:
      return kUnsignedGreaterThanEqual;
    default:
      UNREACHABLE();
  }
}
References v8::internal::kEqual, v8::internal::kGreaterThan, v8::internal::kLessThan, v8::internal::kUnsignedGreaterThan, v8::internal::kUnsignedGreaterThanEqual, v8::internal::kUnsignedLessThan, v8::internal::kUnsignedLessThanEqual, and v8::internal::UNREACHABLE().
UseAndClobberRegister()
void v8::internal::maglev::UseAndClobberRegister (Input & input) [inline]
Definition at line 66 of file maglev-ir-inl.h.
                                                {
  input.SetUnallocated(compiler::UnallocatedOperand::MUST_HAVE_REGISTER,
                       compiler::UnallocatedOperand::USED_AT_START, kNoVreg);
}
References kNoVreg, v8::internal::compiler::UnallocatedOperand::MUST_HAVE_REGISTER, v8::internal::maglev::ValueLocation::SetUnallocated(), and v8::internal::compiler::UnallocatedOperand::USED_AT_START.
Referenced by v8::internal::maglev::BuiltinStringFromCharCode::SetValueLocationConstraints().
UseAny()
void v8::internal::maglev::UseAny (Input & input) [inline]
Definition at line 70 of file maglev-ir-inl.h.
                                 {
  input.SetUnallocated(
      compiler::UnallocatedOperand::REGISTER_OR_SLOT_OR_CONSTANT,
      compiler::UnallocatedOperand::USED_AT_END, kNoVreg);
}
References kNoVreg, v8::internal::compiler::UnallocatedOperand::REGISTER_OR_SLOT_OR_CONSTANT, v8::internal::maglev::ValueLocation::SetUnallocated(), and v8::internal::compiler::UnallocatedOperand::USED_AT_END.
Referenced by v8::internal::maglev::BuiltinStringFromCharCode::SetValueLocationConstraints().
UseFixed() [1/2]
void v8::internal::maglev::UseFixed (Input & input, DoubleRegister reg) [inline]
Definition at line 80 of file maglev-ir-inl.h.
                                                       {
  input.SetUnallocated(compiler::UnallocatedOperand::FIXED_FP_REGISTER,
                       reg.code(), kNoVreg);
  input.node()->SetHint(input.operand());
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::compiler::UnallocatedOperand::FIXED_FP_REGISTER, kNoVreg, v8::internal::maglev::Input::node(), v8::internal::maglev::ValueLocation::operand(), v8::internal::maglev::ValueNode::SetHint(), and v8::internal::maglev::ValueLocation::SetUnallocated().
UseFixed() [2/2]
void v8::internal::maglev::UseFixed (Input & input, Register reg) [inline]
Definition at line 75 of file maglev-ir-inl.h.
                                                 {
  input.SetUnallocated(compiler::UnallocatedOperand::FIXED_REGISTER, reg.code(),
                       kNoVreg);
  input.node()->SetHint(input.operand());
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::compiler::UnallocatedOperand::FIXED_REGISTER, kNoVreg, v8::internal::maglev::Input::node(), v8::internal::maglev::ValueLocation::operand(), v8::internal::maglev::ValueNode::SetHint(), and v8::internal::maglev::ValueLocation::SetUnallocated().
Referenced by v8::internal::compiler::IA32OperandGenerator::UseByteRegister().
UseRegister()
void v8::internal::maglev::UseRegister (Input & input) [inline]
Definition at line 62 of file maglev-ir-inl.h.
                                      {
  input.SetUnallocated(compiler::UnallocatedOperand::MUST_HAVE_REGISTER,
                       compiler::UnallocatedOperand::USED_AT_END, kNoVreg);
}
References kNoVreg, v8::internal::compiler::UnallocatedOperand::MUST_HAVE_REGISTER, v8::internal::maglev::ValueLocation::SetUnallocated(), and v8::internal::compiler::UnallocatedOperand::USED_AT_END.
Referenced by v8::internal::compiler::X64OperandGenerator::GenerateMemoryOperandInputs(), v8::internal::compiler::S390OperandGenerator::GenerateMemoryOperandInputs(), v8::internal::compiler::S390OperandGenerator::GetEffectiveAddressMemoryOperand(), v8::internal::compiler::X64OperandGenerator::GetEffectiveAddressMemoryOperand(), v8::internal::maglev::Int32BitwiseNot::SetValueLocationConstraints(), v8::internal::maglev::CheckedIntPtrToInt32::SetValueLocationConstraints(), v8::internal::maglev::InlinedAllocation::SetValueLocationConstraints(), v8::internal::maglev::CheckFloat64SameValue::SetValueLocationConstraints(), v8::internal::compiler::S390OperandGenerator::UseAnyExceptImmediate(), v8::internal::compiler::Arm64OperandGenerator::UseOperand(), v8::internal::compiler::PPCOperandGenerator::UseOperand(), v8::internal::compiler::Loong64OperandGenerator::UseOperand(), v8::internal::compiler::Mips64OperandGenerator::UseOperand(), v8::internal::compiler::RiscvOperandGenerator::UseOperand(), v8::internal::compiler::S390OperandGenerator::UseOperand(), v8::internal::compiler::Arm64OperandGenerator::UseRegisterOrImmediateZero(), v8::internal::compiler::Loong64OperandGenerator::UseRegisterOrImmediateZero(), v8::internal::compiler::Mips64OperandGenerator::UseRegisterOrImmediateZero(), and v8::internal::compiler::RiscvOperandGenerator::UseRegisterOrImmediateZero().
Variable Documentation
FLOAT32_ELEMENTS
v8::internal::maglev::FLOAT32_ELEMENTS
Definition at line 8756 of file maglev-ir.h.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildLoadConstantTypedArrayElement(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadTypedArrayElement(), v8::internal::maglev::MaglevGraphBuilder::BuildStoreConstantTypedArrayElement(), v8::internal::maglev::MaglevGraphBuilder::BuildStoreTypedArrayElement(), v8::internal::anonymous_namespace{code-stub-assembler.cc}::ElementsKindToMachineRepresentation(), v8::internal::ElementsKindToShiftSize(), v8::internal::AccessorAssembler::EmitElementLoad(), v8::internal::CodeStubAssembler::EmitElementStore(), v8::internal::compiler::fast_api_call::GetTypedArrayElementsKind(), v8::internal::IsFloatTypedArrayElementsKind(), v8::internal::CodeStubAssembler::LoadFixedTypedArrayElementAsTagged(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::TypedArrayBuiltinsAssembler::StoreJSTypedArrayElementFromNumeric(), v8::internal::TypedArrayBuiltinsAssembler::StoreJSTypedArrayElementFromTagged(), v8::internal::CodeStubAssembler::TryLookupElement(), and v8::internal::SharedArrayBufferBuiltinsAssembler::ValidateIntegerTypedArray().
HoleyFloat64
v8::internal::maglev::HoleyFloat64
Definition at line 4584 of file maglev-ir.h.
Referenced by v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), and v8::internal::maglev::Phi::VerifyInputs().
INT16_ELEMENTS
UINT32_ELEMENTS v8::internal::maglev::INT16_ELEMENTS
Definition at line 8747 of file maglev-ir.h.
Referenced by v8::internal::SharedArrayBufferBuiltinsAssembler::AtomicBinopBuiltinCommon(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadConstantTypedArrayElement(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadTypedArrayElement(), v8::internal::maglev::MaglevGraphBuilder::BuildStoreConstantTypedArrayElement(), v8::internal::maglev::MaglevGraphBuilder::BuildStoreTypedArrayElement(), v8::internal::anonymous_namespace{code-stub-assembler.cc}::ElementsKindToMachineRepresentation(), v8::internal::ElementsKindToShiftSize(), v8::internal::AccessorAssembler::EmitElementLoad(), v8::internal::CodeStubAssembler::EmitElementStore(), v8::internal::CodeStubAssembler::EmitElementStoreTypedArrayUpdateValue(), v8::internal::IsSignedIntTypedArrayElementsKind(), v8::internal::CodeStubAssembler::LoadFixedTypedArrayElementAsTagged(), v8::internal::TypedArrayBuiltinsAssembler::StoreJSTypedArrayElementFromNumeric(), v8::internal::TypedArrayBuiltinsAssembler::StoreJSTypedArrayElementFromTagged(), v8::internal::TF_BUILTIN(), v8::internal::CodeStubAssembler::TryLookupElement(), and v8::internal::SharedArrayBufferBuiltinsAssembler::ValidateIntegerTypedArray().
INT8_ELEMENTS
UINT32_ELEMENTS v8::internal::maglev::INT8_ELEMENTS
Definition at line 8747 of file maglev-ir.h.
Referenced by v8::internal::SharedArrayBufferBuiltinsAssembler::AtomicBinopBuiltinCommon(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadConstantTypedArrayElement(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadTypedArrayElement(), v8::internal::maglev::MaglevGraphBuilder::BuildStoreConstantTypedArrayElement(), v8::internal::maglev::MaglevGraphBuilder::BuildStoreTypedArrayElement(), v8::internal::anonymous_namespace{code-stub-assembler.cc}::ElementsKindToMachineRepresentation(), v8::internal::ElementsKindToShiftSize(), v8::internal::AccessorAssembler::EmitElementLoad(), v8::internal::CodeStubAssembler::EmitElementStore(), v8::internal::CodeStubAssembler::EmitElementStoreTypedArrayUpdateValue(), v8::internal::IsSignedIntTypedArrayElementsKind(), v8::internal::CodeStubAssembler::LoadFixedTypedArrayElementAsTagged(), v8::internal::TypedArrayBuiltinsAssembler::StoreJSTypedArrayElementFromNumeric(), v8::internal::TypedArrayBuiltinsAssembler::StoreJSTypedArrayElementFromTagged(), v8::internal::TF_BUILTIN(), v8::internal::CodeStubAssembler::TryLookupElement(), and v8::internal::SharedArrayBufferBuiltinsAssembler::ValidateIntegerTypedArray().
kAllocatableDoubleRegisterCount
constexpr int v8::internal::maglev::kAllocatableDoubleRegisterCount [static], [constexpr]
Initial value:
=
    MaglevAssembler::GetAllocatableDoubleRegisters().Count()
Definition at line 21 of file maglev-regalloc-data.h.
Referenced by v8::internal::maglev::MaxCallDepthProcessor::Process().
kAllocatableGeneralRegisterCount
constexpr int v8::internal::maglev::kAllocatableGeneralRegisterCount [static], [constexpr]
Initial value:
=
    MaglevAssembler::GetAllocatableRegisters().Count()
Definition at line 19 of file maglev-regalloc-data.h.
Referenced by v8::internal::maglev::MaxCallDepthProcessor::Process().
kFirstBranchControlNodeOpcode
constexpr Opcode v8::internal::maglev::kFirstBranchControlNodeOpcode [static], [constexpr]
Initial value:
=
    std::min({BRANCH_CONTROL_NODE_LIST(V) kLastOpcode})
Definition at line 481 of file maglev-ir.h.
Referenced by IsBranchControlNode().
kFirstConditionalControlNodeOpcode
constexpr Opcode v8::internal::maglev::kFirstConditionalControlNodeOpcode [static], [constexpr]
Initial value:
=
    std::min({CONDITIONAL_CONTROL_NODE_LIST(V) kLastOpcode})
Definition at line 486 of file maglev-ir.h.
Referenced by IsConditionalControlNode().
kFirstConstantNodeOpcode
constexpr Opcode v8::internal::maglev::kFirstConstantNodeOpcode [static], [constexpr]
Initial value:
=
    std::min({CONSTANT_VALUE_NODE_LIST(V) kLastOpcode})
Definition at line 469 of file maglev-ir.h.
Referenced by IsConstantNode().
kFirstControlNodeOpcode
constexpr Opcode v8::internal::maglev::kFirstControlNodeOpcode [static], [constexpr]
Initial value:
=
    std::min({CONTROL_NODE_LIST(V) kLastOpcode})
Definition at line 501 of file maglev-ir.h.
Referenced by IsControlNode().
kFirstGapMoveNodeOpcode
constexpr Opcode v8::internal::maglev::kFirstGapMoveNodeOpcode [static], [constexpr]
Initial value:
=
    std::min({GAP_MOVE_NODE_LIST(V) kLastOpcode})
Definition at line 473 of file maglev-ir.h.
Referenced by IsGapMoveNode().
kFirstNodeOpcode
constexpr Opcode v8::internal::maglev::kFirstNodeOpcode = std::min({NODE_LIST(V) kLastOpcode}) [static], [constexpr]
Definition at line 478 of file maglev-ir.h.
kFirstOpcode
constexpr Opcode v8::internal::maglev::kFirstOpcode = static_cast<Opcode>(0) [static], [constexpr]
Definition at line 455 of file maglev-ir.h.
Referenced by v8::internal::maglev::MaglevGraphVerifier::Process().
kFirstTerminalControlNodeOpcode
constexpr Opcode v8::internal::maglev::kFirstTerminalControlNodeOpcode [static], [constexpr]
Initial value:
=
    std::min({TERMINAL_CONTROL_NODE_LIST(V) kLastOpcode})
Definition at line 498 of file maglev-ir.h.
Referenced by IsTerminalControlNode().
kFirstUnconditionalControlNodeOpcode
constexpr Opcode v8::internal::maglev::kFirstUnconditionalControlNodeOpcode [static], [constexpr]
Initial value:
=
    std::min({UNCONDITIONAL_CONTROL_NODE_LIST(V) kLastOpcode})
Definition at line 493 of file maglev-ir.h.
Referenced by IsUnconditionalControlNode().
kFirstValidNodeId
constexpr NodeIdT v8::internal::maglev::kFirstValidNodeId = 1 [static], [constexpr]
Definition at line 1097 of file maglev-ir.h.
kFirstValueNodeOpcode
constexpr Opcode v8::internal::maglev::kFirstValueNodeOpcode [static], [constexpr]
Initial value:
=
    std::min({VALUE_NODE_LIST(V) kLastOpcode})
Definition at line 465 of file maglev-ir.h.
Referenced by IsValueNode().
kInvalidNodeId
constexpr NodeIdT v8::internal::maglev::kInvalidNodeId = 0 [static], [constexpr]
Definition at line 1096 of file maglev-ir.h.
Referenced by v8::internal::maglev::NodeBase::has_id(), v8::internal::maglev::ValueNode::has_no_more_uses(), v8::internal::maglev::NodeBase::id(), v8::internal::maglev::LiveRangeAndNextUseProcessor::MarkInputUses(), v8::internal::maglev::LiveRangeAndNextUseProcessor::MarkUse(), v8::internal::maglev::LiveRangeAndNextUseProcessor::PreProcessBasicBlock(), v8::internal::maglev::LiveRangeAndNextUseProcessor::Process(), v8::internal::maglev::ValueNode::record_next_use(), and v8::internal::maglev::NodeBase::set_id().
kLastBranchControlNodeOpcode
constexpr Opcode v8::internal::maglev::kLastBranchControlNodeOpcode [static], [constexpr]
Initial value:
=
    std::max({BRANCH_CONTROL_NODE_LIST(V) kFirstOpcode})
Definition at line 483 of file maglev-ir.h.
Referenced by IsBranchControlNode().
kLastConditionalControlNodeOpcode
constexpr Opcode v8::internal::maglev::kLastConditionalControlNodeOpcode [static], [constexpr]
Initial value:
=
    std::max({CONDITIONAL_CONTROL_NODE_LIST(V) kFirstOpcode})
Definition at line 488 of file maglev-ir.h.
Referenced by IsConditionalControlNode().
kLastConstantNodeOpcode
constexpr Opcode v8::internal::maglev::kLastConstantNodeOpcode [static], [constexpr]
Initial value:
=
    std::max({CONSTANT_VALUE_NODE_LIST(V) kFirstOpcode})
Definition at line 471 of file maglev-ir.h.
Referenced by IsConstantNode().
kLastControlNodeOpcode
constexpr Opcode v8::internal::maglev::kLastControlNodeOpcode [static], [constexpr]
Initial value:
=
    std::max({CONTROL_NODE_LIST(V) kFirstOpcode})
Definition at line 503 of file maglev-ir.h.
Referenced by IsControlNode().
kLastGapMoveNodeOpcode
constexpr Opcode v8::internal::maglev::kLastGapMoveNodeOpcode [static], [constexpr]
Initial value:
=
    std::max({GAP_MOVE_NODE_LIST(V) kFirstOpcode})
Definition at line 475 of file maglev-ir.h.
Referenced by IsGapMoveNode().
kLastNodeOpcode
constexpr Opcode v8::internal::maglev::kLastNodeOpcode = std::max({NODE_LIST(V) kFirstOpcode}) [static], [constexpr]
Definition at line 479 of file maglev-ir.h.
kLastOpcode
constexpr Opcode v8::internal::maglev::kLastOpcode = static_cast<Opcode>(kOpcodeCount - 1) [static], [constexpr]
Definition at line 456 of file maglev-ir.h.
Referenced by v8::internal::maglev::MaglevGraphVerifier::Process().
kLastTerminalControlNodeOpcode
constexpr Opcode v8::internal::maglev::kLastTerminalControlNodeOpcode [static], [constexpr]
Initial value:
=
    std::max({TERMINAL_CONTROL_NODE_LIST(V) kFirstOpcode})
Definition at line 496 of file maglev-ir.h.
Referenced by IsTerminalControlNode().
kLastUnconditionalControlNodeOpcode
constexpr Opcode v8::internal::maglev::kLastUnconditionalControlNodeOpcode [static], [constexpr]
Initial value:
=
    std::max({UNCONDITIONAL_CONTROL_NODE_LIST(V) kFirstOpcode})
Definition at line 491 of file maglev-ir.h.
Referenced by IsUnconditionalControlNode().
kLastValueNodeOpcode
constexpr Opcode v8::internal::maglev::kLastValueNodeOpcode [static], [constexpr]
Initial value:
=
    std::max({VALUE_NODE_LIST(V) kFirstOpcode})
Definition at line 467 of file maglev-ir.h.
Referenced by IsValueNode().
kNoVreg
constexpr int v8::internal::maglev::kNoVreg = -1 [static], [constexpr]
Definition at line 42 of file maglev-ir-inl.h.
Referenced by DefineAsConstant(), DefineAsFixed(), DefineAsRegister(), DefineSameAsFirst(), v8::internal::maglev::StraightForwardRegisterAllocator::SetLoopPhiRegisterHint(), UseAndClobberRegister(), UseAny(), UseFixed(), and UseRegister().
kNumAssertConditions
constexpr int v8::internal::maglev::kNumAssertConditions [static], [constexpr]
Initial value:
=
#define D(Name)
    0 ASSERT_CONDITION(D)
Definition at line 6745 of file maglev-ir.h.
kNumberOfLeafNodeTypes
constexpr int v8::internal::maglev::kNumberOfLeafNodeTypes = 0 LEAF_NODE_TYPE_LIST(COUNT) [static], [constexpr]
Definition at line 675 of file maglev-ir.h.
kOpcodeCount
constexpr int v8::internal::maglev::kOpcodeCount = NODE_BASE_LIST(PLUS_ONE) [static], [constexpr]
Definition at line 454 of file maglev-ir.h.
UINT16_ELEMENTS
v8::internal::maglev::UINT16_ELEMENTS
Definition at line 8702 of file maglev-ir.h.
Referenced by v8::internal::StringBuiltinsAssembler::AllocAndCopyStringCharacters(), v8::internal::SharedArrayBufferBuiltinsAssembler::AtomicBinopBuiltinCommon(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadConstantTypedArrayElement(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadTypedArrayElement(), v8::internal::maglev::MaglevGraphBuilder::BuildStoreConstantTypedArrayElement(), v8::internal::maglev::MaglevGraphBuilder::BuildStoreTypedArrayElement(), v8::internal::StringBuiltinsAssembler::CopyStringCharacters(), v8::internal::anonymous_namespace{code-stub-assembler.cc}::ElementsKindToMachineRepresentation(), v8::internal::ElementsKindToShiftSize(), v8::internal::AccessorAssembler::EmitElementLoad(), v8::internal::CodeStubAssembler::EmitElementStore(), v8::internal::CodeStubAssembler::EmitElementStoreTypedArrayUpdateValue(), v8::internal::RegExpBuiltinsAssembler::GetStringPointers(), v8::internal::IsUnsignedIntTypedArrayElementsKind(), v8::internal::CodeStubAssembler::LoadFixedTypedArrayElementAsTagged(), v8::internal::TypedArrayBuiltinsAssembler::StoreJSTypedArrayElementFromNumeric(), v8::internal::TypedArrayBuiltinsAssembler::StoreJSTypedArrayElementFromTagged(), v8::internal::TF_BUILTIN(), v8::internal::CodeStubAssembler::TryLookupElement(), and v8::internal::SharedArrayBufferBuiltinsAssembler::ValidateIntegerTypedArray().
UINT8_CLAMPED_ELEMENTS
v8::internal::maglev::UINT8_CLAMPED_ELEMENTS
Definition at line 8702 of file maglev-ir.h.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildLoadConstantTypedArrayElement(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadTypedArrayElement(), v8::internal::maglev::MaglevGraphBuilder::BuildStoreConstantTypedArrayElement(), v8::internal::maglev::MaglevGraphBuilder::BuildStoreTypedArrayElement(), v8::internal::anonymous_namespace{code-stub-assembler.cc}::ElementsKindToMachineRepresentation(), v8::internal::ElementsKindToShiftSize(), v8::internal::AccessorAssembler::EmitElementLoad(), v8::internal::CodeStubAssembler::EmitElementStore(), v8::internal::CodeStubAssembler::EmitElementStoreTypedArrayUpdateValue(), v8::internal::TypedArrayBuiltinsAssembler::IsUint8ElementsKind(), v8::internal::IsUnsignedIntTypedArrayElementsKind(), v8::internal::CodeStubAssembler::LoadFixedTypedArrayElementAsTagged(), v8::internal::CodeStubAssembler::StoreElementTypedArrayWord32(), v8::internal::TypedArrayBuiltinsAssembler::StoreJSTypedArrayElementFromNumeric(), v8::internal::TypedArrayBuiltinsAssembler::StoreJSTypedArrayElementFromTagged(), v8::internal::maglev::MaglevGraphBuilder::TryBuildElementAccessOnTypedArray(), v8::internal::CodeStubAssembler::TryLookupElement(), and v8::internal::SharedArrayBufferBuiltinsAssembler::ValidateIntegerTypedArray().
UINT8_ELEMENTS
v8::internal::maglev::UINT8_ELEMENTS
Definition at line 8702 of file maglev-ir.h.
Referenced by v8::internal::CodeStubAssembler::AllocateByteArray(), v8::internal::CodeStubAssembler::AllocateNonEmptyByteArray(), v8::internal::SharedArrayBufferBuiltinsAssembler::AtomicBinopBuiltinCommon(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadConstantTypedArrayElement(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadTypedArrayElement(), v8::internal::maglev::MaglevGraphBuilder::BuildStoreConstantTypedArrayElement(), v8::internal::maglev::MaglevGraphBuilder::BuildStoreTypedArrayElement(), v8::internal::BUILTIN(), v8::internal::StringBuiltinsAssembler::CopyStringCharacters(), v8::internal::anonymous_namespace{code-stub-assembler.cc}::ElementsKindToMachineRepresentation(), v8::internal::ElementsKindToShiftSize(), v8::internal::AccessorAssembler::EmitElementLoad(), v8::internal::CodeStubAssembler::EmitElementStore(), v8::internal::CodeStubAssembler::EmitElementStoreTypedArrayUpdateValue(), v8::internal::CodeStubAssembler::GetNonRabGsabElementsKind(), v8::internal::RegExpBuiltinsAssembler::GetStringPointers(), v8::internal::compiler::fast_api_call::GetTypedArrayElementsKind(), v8::internal::TypedArrayBuiltinsAssembler::IsUint8ElementsKind(), v8::internal::IsUnsignedIntTypedArrayElementsKind(), v8::internal::CodeStubAssembler::LoadFixedTypedArrayElementAsTagged(), v8::internal::TypedArrayBuiltinsAssembler::StoreJSTypedArrayElementFromNumeric(), v8::internal::TypedArrayBuiltinsAssembler::StoreJSTypedArrayElementFromTagged(), v8::internal::TF_BUILTIN(), v8::internal::CodeStubAssembler::TryLookupElement(), and v8::internal::SharedArrayBufferBuiltinsAssembler::ValidateIntegerTypedArray().