v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc} Namespace Reference
Functions
static Instruction * VisitCompare (InstructionSelector *selector, InstructionCode opcode, InstructionOperand left, InstructionOperand right, FlagsContinuation *cont)
void VisitFloat32Compare (InstructionSelector *selector, OpIndex node, FlagsContinuation *cont)
void VisitFloat64Compare (InstructionSelector *selector, OpIndex node, FlagsContinuation *cont)
Instruction * VisitWordCompare (InstructionSelector *selector, OpIndex node, InstructionCode opcode, FlagsContinuation *cont, bool commutative)
void VisitFullWord32Compare (InstructionSelector *selector, OpIndex node, InstructionCode opcode, FlagsContinuation *cont)
void VisitWord32Compare (InstructionSelector *selector, OpIndex node, FlagsContinuation *cont)
void VisitWord64Compare (InstructionSelector *selector, OpIndex node, FlagsContinuation *cont)
void EmitWordCompareZero (InstructionSelector *selector, OpIndex value, FlagsContinuation *cont)
void VisitAtomicLoad (InstructionSelector *selector, OpIndex node, AtomicWidth width)
AtomicStoreParameters AtomicStoreParametersOf (InstructionSelector *selector, OpIndex node)
void VisitAtomicStore (InstructionSelector *selector, OpIndex node, AtomicWidth width)
void VisitAtomicExchange (InstructionSelector *selector, OpIndex node, ArchOpcode opcode, AtomicWidth width)
void VisitAtomicCompareExchange (InstructionSelector *selector, OpIndex node, ArchOpcode opcode, AtomicWidth width)
void VisitAtomicBinop (InstructionSelector *selector, OpIndex node, ArchOpcode opcode, AtomicWidth width)
Function Documentation
AtomicStoreParametersOf()
AtomicStoreParameters v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::AtomicStoreParametersOf (InstructionSelector * selector, OpIndex node)
Definition at line 1698 of file instruction-selector-mips64.cc.
                                                            {
  auto store = selector->store_view(node);
  return AtomicStoreParameters(store.stored_rep().representation(),
                               store.stored_rep().write_barrier_kind(),
                               store.memory_order().value(),
                               store.access_kind());
}
References store(), and v8::internal::compiler::InstructionSelector::store_view().
EmitWordCompareZero()
void v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::EmitWordCompareZero (InstructionSelector * selector, OpIndex value, FlagsContinuation * cont)
Definition at line 1639 of file instruction-selector-mips64.cc.
                                                  {
  Mips64OperandGenerator g(selector);
  selector->EmitWithContinuation(kMips64Cmp, g.UseRegister(value),
                                 g.TempImmediate(0), cont);
}
References v8::internal::compiler::InstructionSelector::EmitWithContinuation(), v8::internal::compiler::OperandGenerator::TempImmediate(), v8::internal::compiler::OperandGenerator::UseRegister(), and v8::internal::value.
VisitAtomicBinop()
void v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicBinop (InstructionSelector * selector, OpIndex node, ArchOpcode opcode, AtomicWidth width)
Definition at line 1852 of file instruction-selector-mips64.cc.
                                                            {
  using OpIndex = OpIndex;
  Mips64OperandGenerator g(selector);
  const AtomicRMWOp& atomic_op = selector->Cast<AtomicRMWOp>(node);
  OpIndex base = atomic_op.base();
  OpIndex index = atomic_op.index();
  OpIndex value = atomic_op.value();
  AddressingMode addressing_mode = kMode_MRI;
  InstructionOperand inputs[3];
  size_t input_count = 0;
  inputs[input_count++] = g.UseUniqueRegister(base);
  inputs[input_count++] = g.UseUniqueRegister(index);
  inputs[input_count++] = g.UseUniqueRegister(value);
  InstructionOperand outputs[1];
  outputs[0] = g.UseUniqueRegister(node);
  InstructionOperand temps[4];
  temps[0] = g.TempRegister();
  temps[1] = g.TempRegister();
  temps[2] = g.TempRegister();
  temps[3] = g.TempRegister();
  InstructionCode code = opcode | AddressingModeField::encode(addressing_mode) |
                         AtomicWidthField::encode(width);
  selector->Emit(code, 1, outputs, input_count, inputs, 4, temps);
}
References v8::internal::compiler::turboshaft::AtomicRMWOp::base(), v8::internal::compiler::turboshaft::OperationMatcher::Cast(), code, v8::internal::compiler::InstructionSelector::Emit(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::turboshaft::AtomicRMWOp::index(), v8::internal::index, v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::turboshaft::OpIndex, v8::internal::compiler::OperandGenerator::TempRegister(), v8::internal::compiler::OperandGenerator::UseUniqueRegister(), v8::internal::compiler::turboshaft::AtomicRMWOp::value(), and v8::internal::value.
VisitAtomicCompareExchange()
void v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicCompareExchange (InstructionSelector * selector, OpIndex node, ArchOpcode opcode, AtomicWidth width)
Definition at line 1824 of file instruction-selector-mips64.cc.
                                                                      {
  using OpIndex = OpIndex;
  Mips64OperandGenerator g(selector);
  const AtomicRMWOp& atomic_op = selector->Cast<AtomicRMWOp>(node);
  OpIndex base = atomic_op.base();
  OpIndex index = atomic_op.index();
  OpIndex old_value = atomic_op.expected().value();
  OpIndex new_value = atomic_op.value();
  AddressingMode addressing_mode = kMode_MRI;
  InstructionOperand inputs[4];
  size_t input_count = 0;
  inputs[input_count++] = g.UseUniqueRegister(base);
  inputs[input_count++] = g.UseUniqueRegister(index);
  inputs[input_count++] = g.UseUniqueRegister(old_value);
  inputs[input_count++] = g.UseUniqueRegister(new_value);
  InstructionOperand outputs[1];
  outputs[0] = g.UseUniqueRegister(node);
  InstructionOperand temp[3];
  temp[0] = g.TempRegister();
  temp[1] = g.TempRegister();
  temp[2] = g.TempRegister();
  InstructionCode code = opcode | AddressingModeField::encode(addressing_mode) |
                         AtomicWidthField::encode(width);
  selector->Emit(code, 1, outputs, input_count, inputs, 3, temp);
}
References v8::internal::compiler::turboshaft::AtomicRMWOp::base(), v8::internal::compiler::turboshaft::OperationMatcher::Cast(), code, v8::internal::compiler::InstructionSelector::Emit(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::turboshaft::AtomicRMWOp::expected(), v8::internal::compiler::turboshaft::AtomicRMWOp::index(), v8::internal::index, v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::turboshaft::OpIndex, v8::internal::compiler::OperandGenerator::TempRegister(), v8::internal::compiler::OperandGenerator::UseUniqueRegister(), v8::internal::compiler::turboshaft::OptionalOpIndex::value(), and v8::internal::compiler::turboshaft::AtomicRMWOp::value().
VisitAtomicExchange()
void v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicExchange (InstructionSelector * selector, OpIndex node, ArchOpcode opcode, AtomicWidth width)
Definition at line 1790 of file instruction-selector-mips64.cc.
                                                               {
  using OpIndex = OpIndex;
  Mips64OperandGenerator g(selector);
  const AtomicRMWOp& atomic_op = selector->Cast<AtomicRMWOp>(node);
  OpIndex base = atomic_op.base();
  OpIndex index = atomic_op.index();
  OpIndex value = atomic_op.value();
  AddressingMode addressing_mode = kMode_MRI;
  InstructionOperand inputs[3];
  if (opcode == kAtomicExchangeWithWriteBarrier) {
    // All inputs registers need to be non-aliasing with the temp registers as
    // the original inputs are still needed when emitting the write barrier.
    inputs[0] = g.UseUniqueRegister(base);
    inputs[1] = g.UseUniqueRegister(index);
    inputs[2] = g.UseUniqueRegister(value);
  } else {
    inputs[0] = g.UseRegister(base);
    inputs[1] = g.UseRegister(index);
    inputs[2] = g.UseUniqueRegister(value);
  }
  InstructionOperand outputs[1];
  outputs[0] = g.UseUniqueRegister(node);
  InstructionOperand temps[3];
  temps[0] = g.TempRegister();
  temps[1] = g.TempRegister();
  temps[2] = g.TempRegister();
  InstructionCode code = opcode | AddressingModeField::encode(addressing_mode) |
                         AtomicWidthField::encode(width);
  selector->Emit(code, arraysize(outputs), outputs, arraysize(inputs), inputs,
                 arraysize(temps), temps);
}
References arraysize, v8::internal::compiler::turboshaft::AtomicRMWOp::base(), v8::internal::compiler::turboshaft::OperationMatcher::Cast(), code, v8::internal::compiler::InstructionSelector::Emit(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::turboshaft::AtomicRMWOp::index(), v8::internal::index, v8::internal::compiler::turboshaft::OpIndex, v8::internal::compiler::OperandGenerator::TempRegister(), v8::internal::compiler::OperandGenerator::UseRegister(), v8::internal::compiler::OperandGenerator::UseUniqueRegister(), v8::internal::compiler::turboshaft::AtomicRMWOp::value(), and v8::internal::value.
VisitAtomicLoad()
void v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicLoad (InstructionSelector * selector, OpIndex node, AtomicWidth width)
Definition at line 1646 of file instruction-selector-mips64.cc.
                                        {
  using OpIndex = OpIndex;
  Mips64OperandGenerator g(selector);
  auto load = selector->load_view(node);
  OpIndex base = load.base();
  OpIndex index = load.index();
  // The memory order is ignored.
  LoadRepresentation load_rep = load.loaded_rep();
  InstructionCode code;
  switch (load_rep.representation()) {
    case MachineRepresentation::kWord8:
      DCHECK_IMPLIES(load_rep.IsSigned(), width == AtomicWidth::kWord32);
      code = load_rep.IsSigned() ? kAtomicLoadInt8 : kAtomicLoadUint8;
      break;
    case MachineRepresentation::kWord16:
      DCHECK_IMPLIES(load_rep.IsSigned(), width == AtomicWidth::kWord32);
      code = load_rep.IsSigned() ? kAtomicLoadInt16 : kAtomicLoadUint16;
      break;
    case MachineRepresentation::kWord32:
      code = kAtomicLoadWord32;
      break;
    case MachineRepresentation::kWord64:
      code = kMips64Word64AtomicLoadUint64;
      break;
    case MachineRepresentation::kTaggedSigned: // Fall through.
    case MachineRepresentation::kTaggedPointer: // Fall through.
    case MachineRepresentation::kTagged:
      DCHECK_EQ(kTaggedSize, 8);
      code = kMips64Word64AtomicLoadUint64;
      break;
    default:
      UNREACHABLE();
  }
  if (g.CanBeImmediate(index, code)) {
    selector->Emit(code | AddressingModeField::encode(kMode_MRI) |
                       AtomicWidthField::encode(width),
                   g.DefineAsRegister(node), g.UseRegister(base),
                   g.UseImmediate(index));
  } else {
    InstructionOperand addr_reg = g.TempRegister();
    selector->Emit(kMips64Dadd | AddressingModeField::encode(kMode_None),
                   addr_reg, g.UseRegister(index), g.UseRegister(base));
    // Emit desired load opcode, using temp addr_reg.
    selector->Emit(code | AddressingModeField::encode(kMode_MRI) |
                       AtomicWidthField::encode(width),
                   g.DefineAsRegister(node), addr_reg, g.TempImmediate(0));
  }
}
References v8::internal::compiler::Mips64OperandGenerator::CanBeImmediate(), code, DCHECK_EQ, DCHECK_IMPLIES, v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::InstructionSelector::Emit(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::index, v8::internal::MachineType::IsSigned(), v8::internal::kTagged, v8::internal::kTaggedPointer, v8::internal::kTaggedSigned, v8::internal::kTaggedSize, v8::internal::kWord16, v8::internal::kWord32, v8::internal::compiler::kWord32, v8::internal::kWord64, v8::internal::kWord8, v8::internal::compiler::InstructionSelector::load_view(), v8::internal::compiler::turboshaft::OpIndex, v8::internal::MachineType::representation(), v8::internal::compiler::OperandGenerator::TempImmediate(), v8::internal::compiler::OperandGenerator::TempRegister(), v8::internal::UNREACHABLE(), v8::internal::compiler::OperandGenerator::UseImmediate(), and v8::internal::compiler::OperandGenerator::UseRegister().
VisitAtomicStore()
void v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicStore (InstructionSelector * selector, OpIndex node, AtomicWidth width)
Definition at line 1707 of file instruction-selector-mips64.cc.
                                         {
  using OpIndex = OpIndex;
  Mips64OperandGenerator g(selector);
  auto store = selector->store_view(node);
  OpIndex base = store.base();
  OpIndex index = store.index().value();
  OpIndex value = store.value();
  DCHECK_EQ(store.displacement(), 0);
  // The memory order is ignored.
  AtomicStoreParameters store_params = AtomicStoreParametersOf(selector, node);
  WriteBarrierKind write_barrier_kind = store_params.write_barrier_kind();
  MachineRepresentation rep = store_params.representation();
  if (v8_flags.enable_unconditional_write_barriers &&
      CanBeTaggedOrCompressedPointer(rep)) {
    write_barrier_kind = kFullWriteBarrier;
  }
  InstructionCode code;
  if (write_barrier_kind != kNoWriteBarrier &&
      !v8_flags.disable_write_barriers) {
    DCHECK(CanBeTaggedPointer(rep));
    DCHECK_EQ(AtomicWidthSize(width), kTaggedSize);
    InstructionOperand inputs[3];
    size_t input_count = 0;
    inputs[input_count++] = g.UseUniqueRegister(base);
    inputs[input_count++] = g.UseUniqueRegister(index);
    inputs[input_count++] = g.UseUniqueRegister(value);
    RecordWriteMode record_write_mode =
        WriteBarrierKindToRecordWriteMode(write_barrier_kind);
    InstructionOperand temps[] = {g.TempRegister(), g.TempRegister()};
    size_t const temp_count = arraysize(temps);
    code = kArchAtomicStoreWithWriteBarrier;
    code |= RecordWriteModeField::encode(record_write_mode);
    selector->Emit(code, 0, nullptr, input_count, inputs, temp_count, temps);
  } else {
    switch (rep) {
      case MachineRepresentation::kWord8:
        code = kAtomicStoreWord8;
        break;
      case MachineRepresentation::kWord16:
        code = kAtomicStoreWord16;
        break;
      case MachineRepresentation::kWord32:
        code = kAtomicStoreWord32;
        break;
      case MachineRepresentation::kWord64:
        DCHECK_EQ(width, AtomicWidth::kWord64);
        code = kMips64Word64AtomicStoreWord64;
        break;
      case MachineRepresentation::kTaggedSigned: // Fall through.
      case MachineRepresentation::kTaggedPointer: // Fall through.
      case MachineRepresentation::kTagged:
        DCHECK_EQ(AtomicWidthSize(width), kTaggedSize);
        code = kMips64StoreCompressTagged;
        break;
      default:
        UNREACHABLE();
    }
    code |= AtomicWidthField::encode(width);
    if (g.CanBeImmediate(index, code)) {
      selector->Emit(code | AddressingModeField::encode(kMode_MRI) |
                         AtomicWidthField::encode(width),
                     g.NoOutput(), g.UseRegister(base), g.UseImmediate(index),
                     g.UseRegisterOrImmediateZero(value));
    } else {
      InstructionOperand addr_reg = g.TempRegister();
      selector->Emit(kMips64Dadd | AddressingModeField::encode(kMode_None),
                     addr_reg, g.UseRegister(index), g.UseRegister(base));
      // Emit desired store opcode, using temp addr_reg.
      selector->Emit(code | AddressingModeField::encode(kMode_MRI) |
                         AtomicWidthField::encode(width),
                     g.NoOutput(), addr_reg, g.TempImmediate(0),
                     g.UseRegisterOrImmediateZero(value));
    }
  }
}
References arraysize, v8::internal::compiler::AtomicStoreParametersOf(), v8::internal::compiler::AtomicWidthSize(), v8::internal::compiler::Mips64OperandGenerator::CanBeImmediate(), v8::internal::CanBeTaggedOrCompressedPointer(), v8::internal::CanBeTaggedPointer(), code, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::InstructionSelector::Emit(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::index, v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::kFullWriteBarrier, v8::internal::compiler::kNoWriteBarrier, v8::internal::kTagged, v8::internal::kTaggedPointer, v8::internal::kTaggedSigned, v8::internal::kTaggedSize, v8::internal::kWord16, v8::internal::kWord32, v8::internal::kWord64, v8::internal::compiler::kWord64, v8::internal::kWord8, v8::internal::compiler::OperandGenerator::NoOutput(), v8::internal::compiler::turboshaft::OpIndex, v8::internal::compiler::AtomicStoreParameters::representation(), store(), v8::internal::compiler::InstructionSelector::store_view(), v8::internal::compiler::OperandGenerator::TempImmediate(), v8::internal::compiler::OperandGenerator::TempRegister(), v8::internal::UNREACHABLE(), v8::internal::compiler::OperandGenerator::UseImmediate(), v8::internal::compiler::OperandGenerator::UseRegister(), v8::internal::compiler::Mips64OperandGenerator::UseRegisterOrImmediateZero(), v8::internal::compiler::OperandGenerator::UseUniqueRegister(), v8::internal::v8_flags, v8::internal::value, v8::internal::compiler::AtomicStoreParameters::write_barrier_kind(), and v8::internal::compiler::WriteBarrierKindToRecordWriteMode().
VisitCompare()
static Instruction* v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitCompare (InstructionSelector * selector, InstructionCode opcode, InstructionOperand left, InstructionOperand right, FlagsContinuation * cont) [static]
Definition at line 1498 of file instruction-selector-mips64.cc.
                                                          {
  return selector->EmitWithContinuation(opcode, left, right, cont);
}
References v8::internal::compiler::InstructionSelector::EmitWithContinuation().
VisitFloat32Compare()
void v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitFloat32Compare (InstructionSelector * selector, OpIndex node, FlagsContinuation * cont)
Definition at line 1507 of file instruction-selector-mips64.cc.
                                                  {
  Mips64OperandGenerator g(selector);
  const ComparisonOp& op = selector->Get(node).template Cast<ComparisonOp>();
  OpIndex left = op.left();
  OpIndex right = op.right();
  InstructionOperand lhs, rhs;
  lhs = selector->MatchZero(left) ? g.UseImmediate(left) : g.UseRegister(left);
  rhs =
      selector->MatchZero(right) ? g.UseImmediate(right) : g.UseRegister(right);
  VisitCompare(selector, kMips64CmpS, lhs, rhs, cont);
}
References v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::ComparisonOp::left(), v8::internal::compiler::turboshaft::OperationMatcher::MatchZero(), v8::internal::compiler::turboshaft::ComparisonOp::right(), v8::internal::compiler::OperandGenerator::UseImmediate(), v8::internal::compiler::OperandGenerator::UseRegister(), and v8::internal::compiler::VisitCompare().
VisitFloat64Compare()
void v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitFloat64Compare (InstructionSelector * selector, OpIndex node, FlagsContinuation * cont)
Definition at line 1522 of file instruction-selector-mips64.cc.
                                                  {
  Mips64OperandGenerator g(selector);
  const Operation& compare = selector->Get(node);
  DCHECK(compare.Is<ComparisonOp>());
  OpIndex lhs = compare.input(0);
  OpIndex rhs = compare.input(1);
  if (selector->MatchZero(rhs)) {
    VisitCompare(selector, kMips64CmpD, g.UseRegister(lhs), g.UseImmediate(rhs),
                 cont);
  } else if (selector->MatchZero(lhs)) {
    VisitCompare(selector, kMips64CmpD, g.UseImmediate(lhs), g.UseRegister(rhs),
                 cont);
  } else {
    VisitCompare(selector, kMips64CmpD, g.UseRegister(lhs), g.UseRegister(rhs),
                 cont);
  }
}
References v8::internal::DCHECK(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::compiler::turboshaft::OperationMatcher::MatchZero(), v8::internal::compiler::OperandGenerator::UseImmediate(), v8::internal::compiler::OperandGenerator::UseRegister(), and v8::internal::compiler::VisitCompare().
VisitFullWord32Compare()
void v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitFullWord32Compare (InstructionSelector * selector, OpIndex node, InstructionCode opcode, FlagsContinuation * cont)
Definition at line 1612 of file instruction-selector-mips64.cc.
                                                                             {
  Mips64OperandGenerator g(selector);
  const Operation& op = selector->Get(node);
  DCHECK_EQ(op.input_count, 2);
  InstructionOperand leftOp = g.TempRegister();
  InstructionOperand rightOp = g.TempRegister();
  selector->Emit(kMips64Dshl, leftOp, g.UseRegister(op.input(0)),
                 g.TempImmediate(32));
  selector->Emit(kMips64Dshl, rightOp, g.UseRegister(op.input(1)),
                 g.TempImmediate(32));
  Instruction* instr = VisitCompare(selector, opcode, leftOp, rightOp, cont);
  selector->UpdateSourcePosition(instr, node);
}
References DCHECK_EQ, v8::internal::compiler::InstructionSelector::Emit(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::turboshaft::Operation::input_count, v8::internal::compiler::OperandGenerator::TempImmediate(), v8::internal::compiler::OperandGenerator::TempRegister(), v8::internal::compiler::InstructionSelector::UpdateSourcePosition(), v8::internal::compiler::OperandGenerator::UseRegister(), and v8::internal::compiler::VisitCompare().
Referenced by VisitWord32Compare().
VisitWord32Compare()
void v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitWord32Compare (InstructionSelector * selector, OpIndex node, FlagsContinuation * cont)
Definition at line 1629 of file instruction-selector-mips64.cc.
                                                 {
  VisitFullWord32Compare(selector, node, kMips64Cmp, cont);
}
References VisitFullWord32Compare().
VisitWord64Compare()
void v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitWord64Compare (InstructionSelector * selector, OpIndex node, FlagsContinuation * cont)
Definition at line 1634 of file instruction-selector-mips64.cc.
                                                 {
  VisitWordCompare(selector, node, kMips64Cmp, cont, false);
}
References v8::internal::compiler::VisitWordCompare().
VisitWordCompare()
Instruction* v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitWordCompare (InstructionSelector * selector, OpIndex node, InstructionCode opcode, FlagsContinuation * cont, bool commutative)
Definition at line 1542 of file instruction-selector-mips64.cc.
                                                {
  Mips64OperandGenerator g(selector);
  const Operation& op = selector->Get(node);
  DCHECK_EQ(op.input_count, 2);
  auto left = op.input(0);
  auto right = op.input(1);
  // Match immediates on left or right side of comparison.
  if (g.CanBeImmediate(right, opcode)) {
    if (opcode == kMips64Tst) {
      return VisitCompare(selector, opcode, g.UseRegister(left),
                          g.UseImmediate(right), cont);
    } else {
      switch (cont->condition()) {
        case kEqual:
        case kNotEqual:
          if (cont->IsSet()) {
            return VisitCompare(selector, opcode, g.UseRegister(left),
                                g.UseImmediate(right), cont);
          } else {
            return VisitCompare(selector, opcode, g.UseRegister(left),
                                g.UseRegister(right), cont);
          }
        case kSignedLessThan:
        case kSignedGreaterThanOrEqual:
        case kUnsignedLessThan:
        case kUnsignedGreaterThanOrEqual:
          return VisitCompare(selector, opcode, g.UseRegister(left),
                              g.UseImmediate(right), cont);
        default:
          return VisitCompare(selector, opcode, g.UseRegister(left),
                              g.UseRegister(right), cont);
      }
    }
  } else if (g.CanBeImmediate(left, opcode)) {
    if (!commutative) cont->Commute();
    if (opcode == kMips64Tst) {
      return VisitCompare(selector, opcode, g.UseRegister(right),
                          g.UseImmediate(left), cont);
    } else {
      switch (cont->condition()) {
        case kEqual:
        case kNotEqual:
          if (cont->IsSet()) {
            return VisitCompare(selector, opcode, g.UseRegister(right),
                                g.UseImmediate(left), cont);
          } else {
            return VisitCompare(selector, opcode, g.UseRegister(right),
                                g.UseRegister(left), cont);
          }
        case kSignedLessThan:
        case kSignedGreaterThanOrEqual:
        case kUnsignedLessThan:
        case kUnsignedGreaterThanOrEqual:
          return VisitCompare(selector, opcode, g.UseRegister(right),
                              g.UseImmediate(left), cont);
        default:
          return VisitCompare(selector, opcode, g.UseRegister(right),
                              g.UseRegister(left), cont);
      }
    }
  } else {
    return VisitCompare(selector, opcode, g.UseRegister(left),
                        g.UseRegister(right), cont);
  }
}
References v8::internal::compiler::Mips64OperandGenerator::CanBeImmediate(), v8::internal::compiler::FlagsContinuation::Commute(), v8::internal::compiler::FlagsContinuation::condition(), DCHECK_EQ, v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::turboshaft::Operation::input_count, v8::internal::compiler::FlagsContinuation::IsSet(), v8::internal::kEqual, v8::internal::compiler::kNotEqual, v8::internal::compiler::kSignedGreaterThanOrEqual, v8::internal::compiler::kSignedLessThan, v8::internal::compiler::kUnsignedGreaterThanOrEqual, v8::internal::compiler::kUnsignedLessThan, v8::internal::compiler::OperandGenerator::UseImmediate(), v8::internal::compiler::OperandGenerator::UseRegister(), and v8::internal::compiler::VisitCompare().