v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::anonymous_namespace{maglev-code-generator.cc} Namespace Reference
Functions
DeoptimizationFrameTranslation::FrameCount GetFrameCount (const DeoptFrame *deopt_frame)
Function Documentation
GetFrameCount()
DeoptimizationFrameTranslation::FrameCount v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::anonymous_namespace{maglev-code-generator.cc}::GetFrameCount (const DeoptFrame * deopt_frame)
Definition at line 1136 of file maglev-code-generator.cc.
                                   {
  int total = 0;
  int js_frame = 0;
  do {
    if (deopt_frame->IsJsFrame()) {
      js_frame++;
    }
    total++;
    deopt_frame = deopt_frame->parent();
  } while (deopt_frame);
  return {total, js_frame};
}
References v8::internal::maglev::DeoptFrame::IsJsFrame(), and v8::internal::maglev::DeoptFrame::parent().
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildBeginDeopt().