v8::internal::anonymous_namespace{debug.cc} Namespace Reference
Classes
class DiscardBaselineCodeVisitor
Functions
bool ToHandle (Isolate *isolate, std::optional< Tagged< DebugInfo >> debug_info, Handle< DebugInfo > *out)
bool IsJSFunctionAndNeedsTrampoline (Isolate *isolate, Tagged< Object > maybe_function)
void FindBreakablePositions (Handle< DebugInfo > debug_info, int start_position, int end_position, std::vector< BreakLocation > *locations)
bool CompileTopLevel (Isolate *isolate, Handle< Script > script, MaybeHandle< SharedFunctionInfo > *result=nullptr)
Tagged< SharedFunctionInfo > FindSharedFunctionInfoCandidate (int position, DirectHandle< Script > script, Isolate *isolate)
debug::Location GetDebugLocation (DirectHandle< Script > script, int source_position)
Function Documentation
CompileTopLevel()
bool v8::internal::anonymous_namespace{debug.cc}::CompileTopLevel (Isolate * isolate, Handle< Script > script, MaybeHandle< SharedFunctionInfo > * result = nullptr)
Definition at line 1973 of file debug.cc.
                                                                        {
  if (script->compilation_type() == Script::CompilationType::kEval ||
      script->is_wrapped()) {
    return false;
  }
  UnoptimizedCompileState compile_state;
  ReusableUnoptimizedCompileState reusable_state(isolate);
  UnoptimizedCompileFlags flags =
      UnoptimizedCompileFlags::ForScriptCompile(isolate, *script);
  flags.set_is_reparse(true);
  ParseInfo parse_info(isolate, flags, &compile_state, &reusable_state);
  IsCompiledScope is_compiled_scope;
  const MaybeHandle<SharedFunctionInfo> maybe_result =
      Compiler::CompileToplevel(&parse_info, script, isolate,
                                &is_compiled_scope);
  if (maybe_result.is_null()) {
    if (isolate->has_exception()) {
      isolate->clear_exception();
    }
    return false;
  }
  if (result) *result = maybe_result;
  return true;
}
References v8::internal::Isolate::clear_exception(), v8::internal::Compiler::CompileToplevel(), v8::internal::flags, v8::internal::UnoptimizedCompileFlags::ForScriptCompile(), v8::internal::Isolate::has_exception(), v8::internal::MaybeHandle< T >::is_null(), v8::internal::Script::kEval, v8::base::internal::result, and v8::internal::script.
Referenced by v8::internal::Debug::FindInnermostContainingFunctionInfo(), and v8::internal::Debug::GetTopLevelWithRecompile().
FindBreakablePositions()
void v8::internal::anonymous_namespace{debug.cc}::FindBreakablePositions (Handle< DebugInfo > debug_info, int start_position, int end_position, std::vector< BreakLocation > * locations)
Definition at line 1959 of file debug.cc.
                                                                 {
  DCHECK(debug_info->HasInstrumentedBytecodeArray());
  BreakIterator it(debug_info);
  while (!it.Done()) {
    if (it.GetDebugBreakType() != DEBUG_BREAK_SLOT_AT_SUSPEND &&
        it.position() >= start_position && it.position() < end_position) {
      locations->push_back(it.GetBreakLocation());
    }
    it.Next();
  }
}
References v8::internal::DCHECK(), v8::internal::DEBUG_BREAK_SLOT_AT_SUSPEND, v8::internal::BreakIterator::Done(), v8::internal::BreakIterator::GetBreakLocation(), v8::internal::BreakIterator::GetDebugBreakType(), v8::internal::BreakIterator::Next(), and v8::internal::BreakIterator::position().
Referenced by v8::internal::Debug::GetPossibleBreakpoints().
FindSharedFunctionInfoCandidate()
Tagged<SharedFunctionInfo> v8::internal::anonymous_namespace{debug.cc}::FindSharedFunctionInfoCandidate (int position, DirectHandle< Script > script, Isolate * isolate)
Definition at line 2092 of file debug.cc.
                                                                 {
  SharedFunctionInfoFinder finder(position);
  SharedFunctionInfo::ScriptIterator iterator(isolate, *script);
  for (Tagged<SharedFunctionInfo> info = iterator.Next(); !info.is_null();
       info = iterator.Next()) {
    finder.NewCandidate(info);
  }
  return finder.Result();
}
References v8::internal::SharedFunctionInfoFinder::NewCandidate(), v8::internal::SharedFunctionInfo::ScriptIterator::Next(), v8::internal::SharedFunctionInfoFinder::Result(), and v8::internal::script.
Referenced by v8::internal::Debug::FindInnermostContainingFunctionInfo().
GetDebugLocation()
debug::Location v8::internal::anonymous_namespace{debug.cc}::GetDebugLocation (DirectHandle< Script > script, int source_position)
Definition at line 2647 of file debug.cc.
                                                      {
  Script::PositionInfo info;
  Script::GetPositionInfo(script, source_position, &info);
  // V8 provides ScriptCompiler::CompileFunction method which takes
  // expression and compile it as anonymous function like (function() ..
  // expression ..). To produce correct locations for stmts inside of this
  // expression V8 compile this function with negative offset. Instead of stmt
  // position blackboxing use function start position which is negative in
  // described case.
  return debug::Location(std::max(info.line, 0), std::max(info.column, 0));
}
References v8::internal::Script::PositionInfo::column, v8::internal::Script::GetPositionInfo(), v8::internal::Script::PositionInfo::line, and v8::internal::script.
Referenced by v8::internal::Debug::IsFunctionBlackboxed().
IsJSFunctionAndNeedsTrampoline()
bool v8::internal::anonymous_namespace{debug.cc}::IsJSFunctionAndNeedsTrampoline (Isolate * isolate, Tagged< Object > maybe_function)
Definition at line 1844 of file debug.cc.
                                                                   {
  if (!IsJSFunction(maybe_function)) return false;
  std::optional<Tagged<DebugInfo>> debug_info =
      isolate->debug()->TryGetDebugInfo(
          Cast<JSFunction>(maybe_function)->shared());
  return debug_info.has_value() && debug_info.value()->CanBreakAtEntry();
}
References v8::internal::Isolate::debug(), and v8::internal::Debug::TryGetDebugInfo().
Referenced by v8::internal::Debug::InstallDebugBreakTrampoline().
ToHandle()
bool v8::internal::anonymous_namespace{debug.cc}::ToHandle (Isolate * isolate, std::optional< Tagged< DebugInfo >> debug_info, Handle< DebugInfo > * out)
Definition at line 914 of file debug.cc.
                                      {
  if (!debug_info.has_value()) return false;
  *out = handle(debug_info.value(), isolate);
  return true;
}
References v8::internal::handle().
Referenced by v8::internal::Debug::HandleDebugBreak(), v8::internal::Debug::IsBreakAtReturn(), and v8::internal::Debug::OnException().