v8_inspector::anonymous_namespace{string-16.cc} Namespace Reference
Functions
bool isASCII (UChar c)
bool isSpaceOrNewLine (UChar c)
int64_t charactersToInteger (const uint16_t *characters, size_t length, bool *ok=nullptr)
Function Documentation
charactersToInteger()
int64_t v8_inspector::anonymous_namespace{string-16.cc}::charactersToInteger (const uint16_t * characters, size_t length, bool * ok = nullptr)
Definition at line 30 of file string-16.cc.
                                                {
  std::vector<char> buffer;
  buffer.reserve(length + 1);
  for (size_t i = 0; i < length; ++i) {
    if (!isASCII(characters[i])) {
      if (ok) *ok = false;
      return 0;
    }
    buffer.push_back(static_cast<char>(characters[i]));
  }
  buffer.push_back('\0');
  char* endptr;
  int64_t result =
      static_cast<int64_t>(std::strtoll(buffer.data(), &endptr, 10));
  if (ok) *ok = !(*endptr);
  return result;
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, isASCII(), v8::internal::length, and v8::base::internal::result.
Referenced by v8_inspector::String16::toInteger64().
isASCII()
bool v8_inspector::anonymous_namespace{string-16.cc}::isASCII (UChar c)
Definition at line 24 of file string-16.cc.
{ return !(c & ~0x7F); }
Referenced by charactersToInteger(), and isSpaceOrNewLine().
isSpaceOrNewLine()
bool v8_inspector::anonymous_namespace{string-16.cc}::isSpaceOrNewLine (UChar c)
Definition at line 26 of file string-16.cc.
                               {
  return isASCII(c) && c <= ' ' && (c == ' ' || (c <= 0xD && c >= 0x9));
}
References isASCII().
Referenced by v8_inspector::String16::getTrimmedOffsetAndLength().