v8::internal::parsing Namespace Reference
Namespaces
 anonymous_namespace{parsing.cc}
Enumerations
enum class ReportStatisticsMode { kYes
, kNo
 }
Functions
bool ParseProgram (ParseInfo *info, DirectHandle< Script > script, MaybeDirectHandle< ScopeInfo > maybe_outer_scope_info, Isolate *isolate, ReportStatisticsMode mode)
bool ParseProgram (ParseInfo *info, DirectHandle< Script > script, Isolate *isolate, ReportStatisticsMode mode)
bool ParseFunction (ParseInfo *info, DirectHandle< SharedFunctionInfo > shared_info, Isolate *isolate, ReportStatisticsMode mode)
bool ParseAny (ParseInfo *info, DirectHandle< SharedFunctionInfo > shared_info, Isolate *isolate, ReportStatisticsMode mode)
Enumeration Type Documentation
ReportStatisticsMode
enum v8::internal::parsing::ReportStatisticsMode [strong]
Enumerator
kYes
kNo
Definition at line 18 of file parsing.h.
{ kYes, kNo };
Function Documentation
ParseAny()
V8_EXPORT_PRIVATE bool v8::internal::parsing::ParseAny (ParseInfo * info, DirectHandle< SharedFunctionInfo > shared_info, Isolate * isolate, ReportStatisticsMode mode)
Definition at line 98 of file parsing.cc.
                                                           {
  DCHECK(!shared_info.is_null());
  if (info->flags().is_toplevel()) {
    MaybeDirectHandle<ScopeInfo> maybe_outer_scope_info;
    if (shared_info->HasOuterScopeInfo()) {
      maybe_outer_scope_info =
          direct_handle(shared_info->GetOuterScopeInfo(), isolate);
    }
    return ParseProgram(
        info, direct_handle(Cast<Script>(shared_info->script()), isolate),
        maybe_outer_scope_info, isolate, mode);
  }
  return ParseFunction(info, shared_info, isolate, mode);
}
References v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::ParseInfo::flags(), v8::internal::DirectHandle< T >::is_null(), mode(), ParseFunction(), and ParseProgram().
Referenced by v8::internal::Compiler::CollectSourcePositions(), v8::internal::Compiler::Compile(), v8::internal::anonymous_namespace{messages.cc}::RenderCallSite(), v8::internal::ErrorUtils::ThrowLoadFromNullOrUndefined(), and v8::internal::ErrorUtils::ThrowSpreadArgError().
ParseFunction()
V8_EXPORT_PRIVATE bool v8::internal::parsing::ParseFunction (ParseInfo * info, DirectHandle< SharedFunctionInfo > shared_info, Isolate * isolate, ReportStatisticsMode mode)
Definition at line 67 of file parsing.cc.
                                                                {
  DCHECK(!info->flags().is_toplevel());
  DCHECK(!shared_info.is_null());
  DCHECK_NULL(info->literal());
  VMState<PARSER> state(isolate);
  // Create a character stream for the parser.
  DirectHandle<Script> script(Cast<Script>(shared_info->script()), isolate);
  Handle<String> source(Cast<String>(script->source()), isolate);
  uint32_t start_pos = shared_info->StartPosition();
  uint32_t end_pos = shared_info->EndPosition();
  if (end_pos > source->length()) {
    isolate->PushStackTraceAndDie(reinterpret_cast<void*>(script->ptr()),
                                  reinterpret_cast<void*>(source->ptr()));
  }
  std::unique_ptr<Utf16CharacterStream> stream(
      ScannerStream::For(isolate, source, start_pos, end_pos));
  info->set_character_stream(std::move(stream));
  Parser parser(isolate->main_thread_local_isolate(), info);
  // Ok to use Isolate here; this function is only called in the main thread.
  DCHECK(parser.parsing_on_main_thread_);
  parser.ParseFunction(isolate, info, shared_info);
  MaybeReportStatistics(info, script, isolate, &parser, mode);
  return info->literal() != nullptr;
}
References v8::internal::DCHECK(), DCHECK_NULL, v8::internal::ParseInfo::flags(), v8::internal::ScannerStream::For(), v8::internal::DirectHandle< T >::is_null(), v8::internal::ParseInfo::literal(), v8::internal::Isolate::main_thread_local_isolate(), v8::internal::parsing::anonymous_namespace{parsing.cc}::MaybeReportStatistics(), mode(), v8::internal::Parser::ParseFunction(), v8::internal::Isolate::PushStackTraceAndDie(), v8::internal::script, and v8::internal::ParseInfo::set_character_stream().
Referenced by ParseAny(), and v8::internal::ScopeIterator::TryParseAndRetrieveScopes().
ParseProgram() [1/2]
V8_EXPORT_PRIVATE bool v8::internal::parsing::ParseProgram (ParseInfo * info, DirectHandle< Script > script, Isolate * isolate, ReportStatisticsMode mode)
Definition at line 62 of file parsing.cc.
                                                               {
  return ParseProgram(info, script, kNullMaybeHandle, isolate, mode);
}
References v8::internal::kNullMaybeHandle, mode(), ParseProgram(), and v8::internal::script.
ParseProgram() [2/2]
V8_EXPORT_PRIVATE bool v8::internal::parsing::ParseProgram (ParseInfo * info, DirectHandle< Script > script, MaybeDirectHandle< ScopeInfo > maybe_outer_scope_info, Isolate * isolate, ReportStatisticsMode mode)
Definition at line 39 of file parsing.cc.
                                                               {
  DCHECK(info->flags().is_toplevel());
  DCHECK_NULL(info->literal());
  VMState<PARSER> state(isolate);
  // Create a character stream for the parser.
  Handle<String> source(Cast<String>(script->source()), isolate);
  std::unique_ptr<Utf16CharacterStream> stream(
      ScannerStream::For(isolate, source));
  info->set_character_stream(std::move(stream));
  Parser parser(isolate->main_thread_local_isolate(), info);
  // Ok to use Isolate here; this function is only called in the main thread.
  DCHECK(parser.parsing_on_main_thread_);
  parser.ParseProgram(isolate, script, info, maybe_outer_scope_info);
  MaybeReportStatistics(info, script, isolate, &parser, mode);
  return info->literal() != nullptr;
}
References v8::internal::DCHECK(), DCHECK_NULL, v8::internal::ParseInfo::flags(), v8::internal::ScannerStream::For(), v8::internal::ParseInfo::literal(), v8::internal::Isolate::main_thread_local_isolate(), v8::internal::parsing::anonymous_namespace{parsing.cc}::MaybeReportStatistics(), mode(), v8::internal::Parser::ParseProgram(), v8::internal::script, and v8::internal::ParseInfo::set_character_stream().
Referenced by v8::internal::anonymous_namespace{compiler.cc}::CompileToplevel(), v8::Shell::ExecuteString(), ParseAny(), ParseProgram(), v8::internal::anonymous_namespace{liveedit.cc}::ParseScript(), and v8::internal::ScopeIterator::TryParseAndRetrieveScopes().