v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc} Namespace Reference
Functions
template<typename Key >
bool NextInIgnoreList (typename ZoneSet< Key >::const_iterator &ignore, typename ZoneSet< Key >::const_iterator &ignore_end, const Key &cur)
template<typename As , typename Bs , typename CompareFunction , typename IsEmptyFunction = std::nullptr_t>
bool AspectIncludes (const As &as, const Bs &bs, const CompareFunction &Compare, const IsEmptyFunction IsEmpty=nullptr)
template<typename As , typename Bs , typename Function >
bool MaybeEmptyAspectIncludes (const As &as, const Bs &bs, const Function &Compare)
template<typename As , typename Bs , typename Function >
bool MaybeNullAspectIncludes (const As &as, const Bs &bs, const Function &Compare)
bool NodeInfoIncludes (const NodeInfo &before, const NodeInfo &after)
bool NodeInfoIsEmpty (const NodeInfo &info)
bool NodeInfoTypeIs (const NodeInfo &before, const NodeInfo &after)
bool SameValue (ValueNode *before, ValueNode *after)
void PrintBeforeMerge (MaglevGraphLabeller *labeller, ValueNode *current_value, ValueNode *unmerged_value, interpreter::Register reg, KnownNodeAspects *kna)
void PrintAfterMerge (MaglevGraphLabeller *labeller, ValueNode *merged_value, KnownNodeAspects *kna)
ValueNode * FromInt32ToTagged (const MaglevGraphBuilder *builder, NodeType node_type, ValueNode *value, BasicBlock *predecessor)
ValueNode * FromUint32ToTagged (const MaglevGraphBuilder *builder, NodeType node_type, ValueNode *value, BasicBlock *predecessor)
ValueNode * FromIntPtrToTagged (const MaglevGraphBuilder *builder, NodeType node_type, ValueNode *value, BasicBlock *predecessor)
ValueNode * FromFloat64ToTagged (const MaglevGraphBuilder *builder, NodeType node_type, ValueNode *value, BasicBlock *predecessor)
ValueNode * FromHoleyFloat64ToTagged (const MaglevGraphBuilder *builder, NodeType node_type, ValueNode *value, BasicBlock *predecessor)
ValueNode * NonTaggedToTagged (const MaglevGraphBuilder *builder, NodeType node_type, ValueNode *value, BasicBlock *predecessor)
ValueNode * EnsureTagged (const MaglevGraphBuilder *builder, const KnownNodeAspects &known_node_aspects, ValueNode *value, BasicBlock *predecessor)
Function Documentation
AspectIncludes()
template<typename As , typename Bs , typename CompareFunction , typename IsEmptyFunction = std::nullptr_t>
bool v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::AspectIncludes (const As & as, const Bs & bs, const CompareFunction & Compare, const IsEmptyFunction IsEmpty = nullptr)
Definition at line 300 of file maglev-interpreter-frame-state.cc.
                                                             {
  typename As::const_iterator a = as.begin();
  typename Bs::const_iterator b = bs.begin();
  while (a != as.end()) {
    if constexpr (!std::is_same_v<IsEmptyFunction, std::nullptr_t>) {
      if (IsEmpty(a->second)) {
        ++a;
        continue;
      }
    }
    if (b == bs.end()) return false;
    while (b->first < a->first) {
      ++b;
      if (b == bs.end()) return false;
    }
    if (!(a->first == b->first)) return false;
    if (!Compare(a->second, b->second)) {
      return false;
    }
    ++a;
    ++b;
  }
  return true;
}
References v8::bigint::Compare().
Referenced by v8::internal::maglev::KnownNodeAspects::IsCompatibleWithLoopHeader().
EnsureTagged()
ValueNode* v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::EnsureTagged (const MaglevGraphBuilder * builder, const KnownNodeAspects & known_node_aspects, ValueNode * value, BasicBlock * predecessor)
Definition at line 1114 of file maglev-interpreter-frame-state.cc.
                                                                   {
  if (value->properties().value_representation() ==
      ValueRepresentation::kTagged) {
    return value;
  }
  auto info_it = known_node_aspects.FindInfo(value);
  const NodeInfo* info =
      known_node_aspects.IsValid(info_it) ? &info_it->second : nullptr;
  if (info) {
    if (auto alt = info->alternative().tagged()) {
      return alt;
    }
  }
  return NonTaggedToTagged(builder, info ? info->type() : NodeType::kUnknown,
                           value, predecessor);
}
References v8::internal::maglev::NodeInfo::alternative(), v8::internal::maglev::KnownNodeAspects::FindInfo(), v8::internal::maglev::KnownNodeAspects::IsValid(), v8::internal::maglev::kTagged, NonTaggedToTagged(), v8::internal::maglev::NodeInfo::type(), and v8::internal::value.
Referenced by v8::internal::maglev::MaglevInliner::BuildInlineFunction(), v8::internal::maglev::MergePointInterpreterFrameState::MergeLoopValue(), v8::internal::maglev::MergePointInterpreterFrameState::MergeValue(), and v8::internal::maglev::MergePointInterpreterFrameState::MergeVirtualObjectValue().
FromFloat64ToTagged()
ValueNode* v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::FromFloat64ToTagged (const MaglevGraphBuilder * builder, NodeType node_type, ValueNode * value, BasicBlock * predecessor)
Definition at line 1062 of file maglev-interpreter-frame-state.cc.
                                                        {
  DCHECK_EQ(value->properties().value_representation(),
            ValueRepresentation::kFloat64);
  DCHECK(!value->properties().is_conversion());
  // Create a tagged version, and insert it at the end of the predecessor.
  ValueNode* tagged = Node::New<Float64ToTagged>(
      builder->zone(), {value},
      Float64ToTagged::ConversionMode::kCanonicalizeSmi);
  predecessor->nodes().push_back(tagged);
  builder->compilation_unit()->RegisterNodeInGraphLabeller(tagged);
  return tagged;
}
References v8::internal::maglev::MaglevGraphBuilder::compilation_unit(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::maglev::Float64ToTagged::kCanonicalizeSmi, v8::internal::maglev::kFloat64, v8::internal::maglev::BasicBlock::nodes(), v8::internal::ZoneVector< T >::push_back(), v8::internal::maglev::MaglevCompilationUnit::RegisterNodeInGraphLabeller(), v8::internal::value, and v8::internal::maglev::MaglevGraphBuilder::zone().
Referenced by NonTaggedToTagged().
FromHoleyFloat64ToTagged()
ValueNode* v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::FromHoleyFloat64ToTagged (const MaglevGraphBuilder * builder, NodeType node_type, ValueNode * value, BasicBlock * predecessor)
Definition at line 1079 of file maglev-interpreter-frame-state.cc.
                                                             {
  DCHECK_EQ(value->properties().value_representation(),
            ValueRepresentation::kHoleyFloat64);
  DCHECK(!value->properties().is_conversion());
  // Create a tagged version, and insert it at the end of the predecessor.
  ValueNode* tagged = Node::New<HoleyFloat64ToTagged>(
      builder->zone(), {value},
      HoleyFloat64ToTagged::ConversionMode::kCanonicalizeSmi);
  predecessor->nodes().push_back(tagged);
  builder->compilation_unit()->RegisterNodeInGraphLabeller(tagged);
  return tagged;
}
References v8::internal::maglev::MaglevGraphBuilder::compilation_unit(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::maglev::HoleyFloat64ToTagged::kCanonicalizeSmi, v8::internal::maglev::kHoleyFloat64, v8::internal::maglev::BasicBlock::nodes(), v8::internal::ZoneVector< T >::push_back(), v8::internal::maglev::MaglevCompilationUnit::RegisterNodeInGraphLabeller(), v8::internal::value, and v8::internal::maglev::MaglevGraphBuilder::zone().
Referenced by NonTaggedToTagged().
FromInt32ToTagged()
ValueNode* v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::FromInt32ToTagged (const MaglevGraphBuilder * builder, NodeType node_type, ValueNode * value, BasicBlock * predecessor)
Definition at line 997 of file maglev-interpreter-frame-state.cc.
                                                      {
  DCHECK_EQ(value->properties().value_representation(),
            ValueRepresentation::kInt32);
  DCHECK(!value->properties().is_conversion());
  ValueNode* tagged;
  if (value->Is<Int32Constant>()) {
    int32_t constant = value->Cast<Int32Constant>()->value();
    if (Smi::IsValid(constant)) {
      return builder->graph()->GetSmiConstant(constant);
    }
  }
  if (value->Is<StringLength>() ||
      value->Is<BuiltinStringPrototypeCharCodeOrCodePointAt>()) {
    static_assert(String::kMaxLength <= kSmiMaxValue,
                  "String length must fit into a Smi");
    tagged = Node::New<UnsafeSmiTagInt32>(builder->zone(), {value});
  } else if (NodeTypeIsSmi(node_type)) {
    // For known Smis, we can tag without a check.
    tagged = Node::New<UnsafeSmiTagInt32>(builder->zone(), {value});
  } else {
    tagged = Node::New<Int32ToNumber>(builder->zone(), {value});
  }
  predecessor->nodes().push_back(tagged);
  builder->compilation_unit()->RegisterNodeInGraphLabeller(tagged);
  return tagged;
}
References v8::internal::maglev::MaglevGraphBuilder::compilation_unit(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::maglev::Graph::GetSmiConstant(), v8::internal::maglev::MaglevGraphBuilder::graph(), v8::internal::Smi::IsValid(), v8::internal::maglev::kInt32, v8::internal::String::kMaxLength, v8::internal::kSmiMaxValue, v8::internal::maglev::BasicBlock::nodes(), v8::internal::ZoneVector< T >::push_back(), v8::internal::maglev::MaglevCompilationUnit::RegisterNodeInGraphLabeller(), v8::internal::value, and v8::internal::maglev::MaglevGraphBuilder::zone().
Referenced by NonTaggedToTagged().
FromIntPtrToTagged()
ValueNode* v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::FromIntPtrToTagged (const MaglevGraphBuilder * builder, NodeType node_type, ValueNode * value, BasicBlock * predecessor)
Definition at line 1048 of file maglev-interpreter-frame-state.cc.
                                                       {
  DCHECK_EQ(value->properties().value_representation(),
            ValueRepresentation::kIntPtr);
  DCHECK(!value->properties().is_conversion());
  ValueNode* tagged = Node::New<IntPtrToNumber>(builder->zone(), {value});
  predecessor->nodes().push_back(tagged);
  builder->compilation_unit()->RegisterNodeInGraphLabeller(tagged);
  return tagged;
}
References v8::internal::maglev::MaglevGraphBuilder::compilation_unit(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::maglev::kIntPtr, v8::internal::maglev::BasicBlock::nodes(), v8::internal::ZoneVector< T >::push_back(), v8::internal::maglev::MaglevCompilationUnit::RegisterNodeInGraphLabeller(), v8::internal::value, and v8::internal::maglev::MaglevGraphBuilder::zone().
Referenced by NonTaggedToTagged().
FromUint32ToTagged()
ValueNode* v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::FromUint32ToTagged (const MaglevGraphBuilder * builder, NodeType node_type, ValueNode * value, BasicBlock * predecessor)
Definition at line 1029 of file maglev-interpreter-frame-state.cc.
                                                       {
  DCHECK_EQ(value->properties().value_representation(),
            ValueRepresentation::kUint32);
  DCHECK(!value->properties().is_conversion());
  ValueNode* tagged;
  if (NodeTypeIsSmi(node_type)) {
    tagged = Node::New<UnsafeSmiTagUint32>(builder->zone(), {value});
  } else {
    tagged = Node::New<Uint32ToNumber>(builder->zone(), {value});
  }
  predecessor->nodes().push_back(tagged);
  builder->compilation_unit()->RegisterNodeInGraphLabeller(tagged);
  return tagged;
}
References v8::internal::maglev::MaglevGraphBuilder::compilation_unit(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::maglev::kUint32, v8::internal::maglev::BasicBlock::nodes(), v8::internal::ZoneVector< T >::push_back(), v8::internal::maglev::MaglevCompilationUnit::RegisterNodeInGraphLabeller(), v8::internal::value, and v8::internal::maglev::MaglevGraphBuilder::zone().
Referenced by NonTaggedToTagged().
MaybeEmptyAspectIncludes()
template<typename As , typename Bs , typename Function >
bool v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::MaybeEmptyAspectIncludes (const As & as, const Bs & bs, const Function & Compare)
Definition at line 329 of file maglev-interpreter-frame-state.cc.
                                                       {
  return AspectIncludes<As, Bs, Function>(as, bs, Compare,
                                          [](auto x) { return x.empty(); });
}
References v8::bigint::Compare().
Referenced by v8::internal::maglev::KnownNodeAspects::IsCompatibleWithLoopHeader().
MaybeNullAspectIncludes()
template<typename As , typename Bs , typename Function >
bool v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::MaybeNullAspectIncludes (const As & as, const Bs & bs, const Function & Compare)
Definition at line 336 of file maglev-interpreter-frame-state.cc.
                                                      {
  return AspectIncludes<As, Bs, Function>(as, bs, Compare,
                                          [](auto x) { return x == nullptr; });
}
References v8::bigint::Compare().
Referenced by v8::internal::maglev::KnownNodeAspects::IsCompatibleWithLoopHeader().
NextInIgnoreList()
template<typename Key >
bool v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::NextInIgnoreList (typename ZoneSet< Key >::const_iterator & ignore, typename ZoneSet< Key >::const_iterator & ignore_end, const Key & cur)
Definition at line 74 of file maglev-interpreter-frame-state.cc.
                                      {
  while (ignore != ignore_end && *ignore < cur) {
    ++ignore;
  }
  return ignore != ignore_end && *ignore == cur;
}
References wasm::ignore().
Referenced by v8::internal::maglev::KnownNodeAspects::KnownNodeAspects().
NodeInfoIncludes()
bool v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::NodeInfoIncludes (const NodeInfo & before, const NodeInfo & after)
Definition at line 342 of file maglev-interpreter-frame-state.cc.
                                                                     {
  if (!NodeTypeIs(after.type(), before.type())) {
    return false;
  }
  if (before.possible_maps_are_known() && before.any_map_is_unstable()) {
    if (!after.possible_maps_are_known()) {
      return false;
    }
    if (!before.possible_maps().contains(after.possible_maps())) {
      return false;
    }
  }
  return true;
}
References v8::internal::maglev::NodeInfo::any_map_is_unstable(), v8::internal::ZoneCompactSet< T >::contains(), v8::internal::maglev::NodeTypeIs(), v8::internal::maglev::NodeInfo::possible_maps(), v8::internal::maglev::NodeInfo::possible_maps_are_known(), and v8::internal::maglev::NodeInfo::type().
Referenced by v8::internal::maglev::KnownNodeAspects::IsCompatibleWithLoopHeader().
NodeInfoIsEmpty()
bool v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::NodeInfoIsEmpty (const NodeInfo & info)
Definition at line 357 of file maglev-interpreter-frame-state.cc.
                                           {
  return info.type() == NodeType::kUnknown && !info.possible_maps_are_known();
}
References v8::internal::maglev::NodeInfo::possible_maps_are_known(), and v8::internal::maglev::NodeInfo::type().
Referenced by v8::internal::maglev::KnownNodeAspects::IsCompatibleWithLoopHeader().
NodeInfoTypeIs()
bool v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::NodeInfoTypeIs (const NodeInfo & before, const NodeInfo & after)
Definition at line 361 of file maglev-interpreter-frame-state.cc.
                                                                   {
  return NodeTypeIs(after.type(), before.type());
}
References v8::internal::maglev::NodeTypeIs(), and v8::internal::maglev::NodeInfo::type().
Referenced by v8::internal::maglev::KnownNodeAspects::IsCompatibleWithLoopHeader().
NonTaggedToTagged()
ValueNode* v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::NonTaggedToTagged (const MaglevGraphBuilder * builder, NodeType node_type, ValueNode * value, BasicBlock * predecessor)
Definition at line 1096 of file maglev-interpreter-frame-state.cc.
                                                      {
  switch (value->properties().value_representation()) {
    case ValueRepresentation::kTagged:
      UNREACHABLE();
    case ValueRepresentation::kInt32:
      return FromInt32ToTagged(builder, node_type, value, predecessor);
    case ValueRepresentation::kUint32:
      return FromUint32ToTagged(builder, node_type, value, predecessor);
    case ValueRepresentation::kIntPtr:
      return FromIntPtrToTagged(builder, node_type, value, predecessor);
    case ValueRepresentation::kFloat64:
      return FromFloat64ToTagged(builder, node_type, value, predecessor);
    case ValueRepresentation::kHoleyFloat64:
      return FromHoleyFloat64ToTagged(builder, node_type, value, predecessor);
  }
}
References FromFloat64ToTagged(), FromHoleyFloat64ToTagged(), FromInt32ToTagged(), FromIntPtrToTagged(), FromUint32ToTagged(), v8::internal::maglev::kFloat64, v8::internal::maglev::kHoleyFloat64, v8::internal::maglev::kInt32, v8::internal::maglev::kIntPtr, v8::internal::maglev::kTagged, v8::internal::maglev::kUint32, v8::internal::UNREACHABLE(), and v8::internal::value.
Referenced by EnsureTagged(), and v8::internal::maglev::MergePointInterpreterFrameState::MergeValue().
PrintAfterMerge()
void v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::PrintAfterMerge (MaglevGraphLabeller * labeller, ValueNode * merged_value, KnownNodeAspects * kna)
Definition at line 596 of file maglev-interpreter-frame-state.cc.
                                            {
  if (!v8_flags.trace_maglev_graph_building) return;
  std::cout << " => " << PrintNodeLabel(labeller, merged_value) << ": "
            << PrintNode(labeller, merged_value) << "<";
  if (kna) {
    if (auto out_info = kna->TryGetInfoFor(merged_value)) {
      std::cout << out_info->type();
      if (out_info->possible_maps_are_known()) {
        std::cout << " " << out_info->possible_maps().size();
      }
    }
  }
  std::cout << ">" << std::endl;
}
References v8::internal::compiler::anonymous_namespace{node.cc}::PrintNode(), v8::internal::maglev::KnownNodeAspects::TryGetInfoFor(), and v8::internal::v8_flags.
Referenced by v8::internal::maglev::MergePointInterpreterFrameState::MergeLoop(), v8::internal::maglev::MergePointInterpreterFrameState::MergePhis(), v8::internal::maglev::MergePointInterpreterFrameState::MergeThrow(), and v8::internal::maglev::MergePointInterpreterFrameState::TryMergeLoop().
PrintBeforeMerge()
void v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::PrintBeforeMerge (MaglevGraphLabeller * labeller, ValueNode * current_value, ValueNode * unmerged_value, interpreter::Register reg, KnownNodeAspects * kna)
Definition at line 571 of file maglev-interpreter-frame-state.cc.
                                             {
  if (!v8_flags.trace_maglev_graph_building) return;
  std::cout << " " << reg.ToString() << ": "
            << PrintNodeLabel(labeller, current_value) << "<";
  if (kna) {
    if (auto cur_info = kna->TryGetInfoFor(current_value)) {
      std::cout << cur_info->type();
      if (cur_info->possible_maps_are_known()) {
        std::cout << " " << cur_info->possible_maps().size();
      }
    }
  }
  std::cout << "> <- " << PrintNodeLabel(labeller, unmerged_value) << "<";
  if (kna) {
    if (auto in_info = kna->TryGetInfoFor(unmerged_value)) {
      std::cout << in_info->type();
      if (in_info->possible_maps_are_known()) {
        std::cout << " " << in_info->possible_maps().size();
      }
    }
  }
  std::cout << ">";
}
References v8::internal::interpreter::Register::ToString(), v8::internal::maglev::KnownNodeAspects::TryGetInfoFor(), and v8::internal::v8_flags.
Referenced by v8::internal::maglev::MergePointInterpreterFrameState::MergeLoop(), v8::internal::maglev::MergePointInterpreterFrameState::MergePhis(), v8::internal::maglev::MergePointInterpreterFrameState::MergeThrow(), and v8::internal::maglev::MergePointInterpreterFrameState::TryMergeLoop().
SameValue()
bool v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::SameValue (ValueNode * before, ValueNode * after)
Definition at line 365 of file maglev-interpreter-frame-state.cc.
{ return before == after; }
Referenced by v8::internal::maglev::KnownNodeAspects::IsCompatibleWithLoopHeader(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::TypeNarrowingReducer::Reduce(), v8::internal::compiler::JSCallReducer::ReduceObjectIs(), and v8::internal::compiler::RepresentationSelector::UpdateFeedbackType().