cppgc::internal::anonymous_namespace{object-allocator.cc} Namespace Reference
Functions
void MarkRangeAsYoung (BasePage &page, Address begin, Address end)
void AddToFreeList (NormalPageSpace &space, Address start, size_t size)
void ReplaceLinearAllocationBuffer (NormalPageSpace &space, StatsCollector &stats_collector, Address new_buffer, size_t new_size)
LargePage * TryAllocateLargeObjectImpl (PageBackend &page_backend, LargePageSpace &space, size_t size)
void * TryAllocateLargeObject (PageBackend &page_backend, LargePageSpace &space, StatsCollector &stats_collector, size_t size, GCInfoIndex gcinfo)
Variables
constexpr GCConfig kOnAllocationFailureGCConfig
Function Documentation
AddToFreeList()
void cppgc::internal::anonymous_namespace{object-allocator.cc}::AddToFreeList (NormalPageSpace & space, Address start, size_t size)
Definition at line 51 of file object-allocator.cc.
                                                                       {
  // No need for SetMemoryInaccessible() as LAB memory is retrieved as free
  // inaccessible memory.
  space.free_list().Add({start, size});
  // Concurrent marking may be running while the LAB is set up next to a live
  // object sharing the same cell in the bitmap.
  NormalPage::From(BasePage::FromPayload(start))
      ->object_start_bitmap()
      .SetBit<AccessMode::kAtomic>(start);
}
References cppgc::internal::NormalPage::From(), cppgc::internal::BasePage::FromPayload(), cppgc::internal::kAtomic, cppgc::internal::NormalPage::object_start_bitmap(), cppgc::internal::PlatformAwareObjectStartBitmap::SetBit(), size(), and space.
Referenced by ReplaceLinearAllocationBuffer().
MarkRangeAsYoung()
void cppgc::internal::anonymous_namespace{object-allocator.cc}::MarkRangeAsYoung (BasePage & page, Address begin, Address end)
Definition at line 30 of file object-allocator.cc.
                                                                  {
#if defined(CPPGC_YOUNG_GENERATION)
  DCHECK_LT(begin, end);
  if (!page.heap().generational_gc_supported()) return;
  // Then, if the page is newly allocated, force the first and last cards to be
  // marked as young.
  const bool new_page =
      (begin == page.PayloadStart()) && (end == page.PayloadEnd());
  auto& age_table = CagedHeapLocalData::Get().age_table;
  age_table.SetAgeForRange(CagedHeap::OffsetFromAddress(begin),
                           CagedHeap::OffsetFromAddress(end),
                           AgeTable::Age::kYoung,
                           new_page ? AgeTable::AdjacentCardsPolicy::kIgnore
                                    : AgeTable::AdjacentCardsPolicy::kConsider);
  page.set_as_containing_young_objects(true);
#endif // defined(CPPGC_YOUNG_GENERATION)
}
References v8::internal::compiler::begin(), DCHECK_LT, v8::internal::compiler::end(), cppgc::internal::HeapBase::generational_gc_supported(), v8::internal::compiler::turboshaft::Get(), cppgc::internal::BasePage::heap(), cppgc::internal::CagedHeap::OffsetFromAddress(), cppgc::internal::BasePage::PayloadEnd(), cppgc::internal::BasePage::PayloadStart(), and cppgc::internal::BasePage::set_as_containing_young_objects().
Referenced by cppgc::internal::ObjectAllocator::MarkAllPagesAsYoung(), ReplaceLinearAllocationBuffer(), and TryAllocateLargeObject().
ReplaceLinearAllocationBuffer()
void cppgc::internal::anonymous_namespace{object-allocator.cc}::ReplaceLinearAllocationBuffer (NormalPageSpace & space, StatsCollector & stats_collector, Address new_buffer, size_t new_size)
Definition at line 62 of file object-allocator.cc.
                                                                        {
  auto& lab = space.linear_allocation_buffer();
  if (lab.size()) {
    AddToFreeList(space, lab.start(), lab.size());
    stats_collector.NotifyExplicitFree(lab.size());
  }
  lab.Set(new_buffer, new_size);
  if (new_size) {
    DCHECK_NOT_NULL(new_buffer);
    stats_collector.NotifyAllocation(new_size);
    auto* page = NormalPage::From(BasePage::FromPayload(new_buffer));
    // Concurrent marking may be running while the LAB is set up next to a live
    // object sharing the same cell in the bitmap.
    page->object_start_bitmap().ClearBit<AccessMode::kAtomic>(new_buffer);
    MarkRangeAsYoung(*page, new_buffer, new_buffer + new_size);
  }
}
References AddToFreeList(), DCHECK_NOT_NULL, cppgc::internal::NormalPage::From(), cppgc::internal::BasePage::FromPayload(), cppgc::internal::kAtomic, MarkRangeAsYoung(), cppgc::internal::StatsCollector::NotifyAllocation(), cppgc::internal::StatsCollector::NotifyExplicitFree(), and space.
Referenced by cppgc::internal::ObjectAllocator::OutOfLineAllocateGCSafePoint(), cppgc::internal::ObjectAllocator::ResetLinearAllocationBuffers(), cppgc::internal::ObjectAllocator::TryExpandAndRefillLinearAllocationBuffer(), and cppgc::internal::ObjectAllocator::TryRefillLinearAllocationBufferFromFreeList().
TryAllocateLargeObject()
void* cppgc::internal::anonymous_namespace{object-allocator.cc}::TryAllocateLargeObject (PageBackend & page_backend, LargePageSpace & space, StatsCollector & stats_collector, size_t size, GCInfoIndex gcinfo)
Definition at line 114 of file object-allocator.cc.
                                                 {
  LargePage* page = TryAllocateLargeObjectImpl(page_backend, space, size);
  if (!page) return nullptr;
  space.AddPage(page);
  auto* header = new (page->ObjectHeader())
      HeapObjectHeader(HeapObjectHeader::kLargeObjectSizeInHeader, gcinfo);
  stats_collector.NotifyAllocation(size);
  MarkRangeAsYoung(*page, page->PayloadStart(), page->PayloadEnd());
  return header->ObjectStart();
}
References cppgc::internal::HeapObjectHeader::kLargeObjectSizeInHeader, MarkRangeAsYoung(), cppgc::internal::StatsCollector::NotifyAllocation(), cppgc::internal::LargePage::ObjectHeader(), cppgc::internal::LargePage::PayloadEnd(), cppgc::internal::LargePage::PayloadStart(), size(), space, and TryAllocateLargeObjectImpl().
Referenced by cppgc::internal::ObjectAllocator::OutOfLineAllocateImpl().
TryAllocateLargeObjectImpl()
LargePage* cppgc::internal::anonymous_namespace{object-allocator.cc}::TryAllocateLargeObjectImpl (PageBackend & page_backend, LargePageSpace & space, size_t size)
Definition at line 83 of file object-allocator.cc.
                                                                          {
  LargePage* page = LargePage::TryCreate(page_backend, space, size);
  if (page) return page;
  Sweeper& sweeper = space.raw_heap()->heap()->sweeper();
  // Lazily sweep pages of this heap. This is not exhaustive to limit jank on
  // allocation.
  if (sweeper.SweepForAllocationIfRunning(
          &space, size, v8::base::TimeDelta::FromMicroseconds(500)) &&
      (page = LargePage::TryCreate(page_backend, space, size))) {
    return page;
  }
  // Before finishing all sweeping, finish sweeping of a given space which is
  // cheaper.
  if (sweeper.SweepForAllocationIfRunning(&space, size,
                                          v8::base::TimeDelta::Max()) &&
      (page = LargePage::TryCreate(page_backend, space, size))) {
    return page;
  }
  if (sweeper.FinishIfRunning() &&
      (page = LargePage::TryCreate(page_backend, space, size))) {
    return page;
  }
  return nullptr;
}
References cppgc::internal::Sweeper::FinishIfRunning(), v8::base::TimeDelta::FromMicroseconds(), v8::base::TimeDelta::Max(), size(), space, cppgc::internal::Sweeper::SweepForAllocationIfRunning(), and cppgc::internal::LargePage::TryCreate().
Referenced by TryAllocateLargeObject().
Variable Documentation
kOnAllocationFailureGCConfig
constexpr GCConfig cppgc::internal::anonymous_namespace{object-allocator.cc}::kOnAllocationFailureGCConfig [constexpr]
Initial value:
= {
    CollectionType::kMajor, StackState::kMayContainHeapPointers,
    GCConfig::MarkingType::kAtomic,
    GCConfig::SweepingType::kIncrementalAndConcurrent,
    GCConfig::FreeMemoryHandling::kDiscardWherePossible}
Definition at line 167 of file object-allocator.cc.
Referenced by cppgc::internal::ObjectAllocator::OutOfLineAllocateImpl().