v8::base::debug Namespace Reference
Namespaces
 anonymous_namespace{stack_trace_posix.cc}
 anonymous_namespace{stack_trace_win.cc}
 anonymous_namespace{stack_trace_zos.cc}
 internal
Classes
class StackTrace
Functions
V8_BASE_EXPORT bool EnableInProcessStackDumping ()
V8_BASE_EXPORT void DisableSignalStackDump ()
Function Documentation
DisableSignalStackDump()
void v8::base::debug::DisableSignalStackDump ()
Definition at line 69 of file stack_trace_android.cc.
                              {
}
Referenced by v8::platform::anonymous_namespace{default-platform.cc}::PrintStackTrace().
EnableInProcessStackDumping()
bool v8::base::debug::EnableInProcessStackDumping ()
Definition at line 57 of file stack_trace_android.cc.
                                   {
  // When running in an application, our code typically expects SIGPIPE
  // to be ignored. Therefore, when testing that same code, it should run
  // with SIGPIPE ignored as well.
  // TODO(phajdan.jr): De-duplicate this SIGPIPE code.
  struct sigaction action;
  memset(&action, 0, sizeof(action));
  action.sa_handler = SIG_IGN;
  sigemptyset(&action.sa_mask);
  return (sigaction(SIGPIPE, &action, nullptr) == 0);
}
Referenced by v8::platform::NewDefaultPlatform(), and v8::platform::NewSingleThreadedDefaultPlatform().