v8::internal::detail Namespace Reference
Classes
struct IsRegisterArray
struct IsRegisterArray< std::array< Register, N > >
struct IsRegisterArray< EmptyRegisterArray >
struct FirstInvalidRegisterHelper
struct FirstInvalidRegisterHelper< N, N >
class BuiltinArgumentsTS
struct HeapObjectAndSlotPOD
class ArrayHeaderBase
class ArrayHeaderBase< Super, false >
class ArrayHeaderBase< Super, true >
struct TaggedArrayHeaderHelper
struct TaggedArrayHeaderHelper< Shape, Super, std::void_t< typename Shape::template ExtraFields< Super > > >
class WaiterQueueLockGuard
class SyncWaiterQueueNode
class AsyncWaiterNotifyTask
class AsyncWaiterTimeoutTask
class AsyncWaiterQueueNode
struct wrap_optional
struct wrap_optional< std::optional< T > >
struct wrap_optional< std::nullopt_t >
struct common_type_handle_nullopt
struct is_simple_subtype
struct is_complex_subtype
struct is_simple_subtype< T, T >
struct is_simple_subtype< Object, Object >
struct is_simple_subtype< Smi, Object >
struct is_simple_subtype< TaggedIndex, Object >
struct is_simple_subtype< FieldType, Object >
struct is_simple_subtype< HeapObject, Object >
struct is_simple_subtype< HeapObjectLayout, Object >
struct is_simple_subtype< T, MaybeWeak< T > >
struct is_simple_subtype< MaybeWeak< T >, MaybeWeak< T > >
struct is_simple_subtype< ClearedWeakValue, MaybeWeak< T > >
struct is_simple_subtype< Smi, MaybeWeak< Object > >
struct is_simple_subtype< MaybeWeak< Object >, Union< HeapObject, MaybeWeak< HeapObject >, Smi > >
struct is_simple_subtype< Object, Union< HeapObject, Smi > >
struct is_simple_subtype< Object, Union< HeapObject, MaybeWeak< HeapObject >, Smi > >
struct is_simple_subtype< Derived, Union< BaseTs... > >
struct is_simple_subtype< Union< DerivedTs... >, Base >
struct is_simple_subtype< Union< DerivedTs... >, Union< BaseTs... > >
struct is_simple_subtype< Union< Ts... >, Union< Ts... > >
struct is_complex_subtype< Derived, Object, std::enable_if_t< std::conjunction_v< std::negation< is_union< Derived > >, is_subtype< Derived, HeapObject > > > >
struct is_complex_subtype< Derived, HeapObject, std::enable_if_t< std::disjunction_v< std::is_base_of< HeapObject, Derived >, std::is_base_of< HeapObjectLayout, Derived > > > >
struct is_complex_subtype< Derived, TrustedObject, std::enable_if_t< std::disjunction_v< std::is_base_of< TrustedObject, Derived >, std::is_base_of< TrustedObjectLayout, Derived > > > >
struct is_complex_subtype< Derived, Struct, std::enable_if_t< std::disjunction_v< std::is_base_of< Struct, Derived >, std::is_base_of< StructLayout, Derived > > > >
struct is_complex_subtype< Derived, Union< BaseTs... > >
struct is_complex_subtype< Union< DerivedTs... >, Base >
struct is_complex_subtype< Union< DerivedTs... >, Union< BaseTs... > >
struct is_complex_subtype< Derived, MaybeWeak< Base >, std::enable_if_t<!is_union_v< Derived > &&!is_maybe_weak_v< Derived > > >
struct is_complex_subtype< MaybeWeak< Derived >, MaybeWeak< Base > >
class TaggedOperatorArrowRef
struct BaseForTagged
struct BaseForTagged< MaybeWeak< T > >
struct BaseForTagged< Union< T... > >
struct BaseForTagged< FieldType >
struct UnionWithoutHelper
struct UnionWithoutHelper< Union< OutputTs... >, TWithout >
struct UnionWithoutHelper< Union< OutputTs... >, TWithout, TWithout, Ts... >
struct UnionWithoutHelper< Union< OutputTs... >, TWithout, Head, Ts... >
struct FlattenUnionHelper
struct FlattenUnionHelper< Union< OutputTs... > >
struct FlattenUnionHelper< Union< OutputTs... >, Head, Ts... >
struct FlattenUnionHelper< Union< OutputTs... >, Smi, Ts... >
struct FlattenUnionHelper< Union< OutputTs... >, Union< HeadTs... >, Ts... >
class WaiterQueueNode
Typedefs
template<class Shape , class Super >
using TaggedArrayHeader = typename TaggedArrayHeaderHelper< Shape, Super >::type
using ArrayIndexT = uint32_t
Enumerations
enum class RuntimeFunctionFullName { F
 }
enum IndexParseResult { kSuccess
, kNonIndex
, kOverflow
 }
Functions
template<size_t N, size_t Index = 0>
constexpr size_t FirstInvalidRegister (std::array< Register, N > regs)
constexpr size_t FirstInvalidRegister (EmptyRegisterArray regs)
constexpr bool RuntimeFunctionFullNameCanTriggerGC (RuntimeFunctionFullName function_name)
template<typename CppType >
static void Destructor (void *ptr)
template<typename... T>
constexpr bool CanTriggerGC (T... properties)
V8_EXPORT_PRIVATE uint64_t HashConvertingTo8Bit (const uint16_t *chars, uint32_t length, uint64_t seed)
template<typename T >
uint32_t ConvertRawHashToUsableHash (T raw_hash)
bool IsOnly8Bit (const uint16_t *chars, unsigned len)
uint64_t GetRapidHash (const uint8_t *chars, uint32_t length, uint64_t seed)
uint64_t GetRapidHash (const uint16_t *chars, uint32_t length, uint64_t seed)
template<typename uchar >
uint32_t GetUsableRapidHash (const uchar *chars, uint32_t length, uint64_t seed)
template<typename uchar >
IndexParseResult TryParseArrayIndex (const uchar *chars, uint32_t length, uint32_t &i, ArrayIndexT &index)
Variables
constexpr int kTagBits = 2
constexpr int kTagMask = (1 << kTagBits) - 1
constexpr int kLongTagBits = 6
constexpr int kEmbeddedObjectTag = 0
constexpr int kCodeTargetTag = 1
constexpr int kWasmStubCallTag = 2
constexpr int kDefaultTag = 3
constexpr int kSmallPCDeltaBits = kBitsPerByte - kTagBits
constexpr int kSmallPCDeltaMask = (1 << kSmallPCDeltaBits) - 1
v8::internal::detail::ArrayHeaderBase< Super, false > V8_OBJECT_END
template<typename Derived , typename Base >
static constexpr bool is_simple_subtype_v
template<typename Derived , typename Base >
static constexpr bool is_complex_subtype_v
Typedef Documentation
ArrayIndexT
using v8::internal::detail::ArrayIndexT = typedef uint32_t
Definition at line 125 of file string-hasher-inl.h.
TaggedArrayHeader
template<class Shape , class Super >
using v8::internal::detail::TaggedArrayHeader = typedef typename TaggedArrayHeaderHelper<Shape, Super>::type
Definition at line 85 of file fixed-array.h.
Enumeration Type Documentation
IndexParseResult
enum v8::internal::detail::IndexParseResult
Enumerator
kSuccess
kNonIndex
kOverflow
Definition at line 118 of file string-hasher-inl.h.
{ kSuccess, kNonIndex, kOverflow };
RuntimeFunctionFullName
enum v8::internal::detail::RuntimeFunctionFullName [strong]
Enumerator
F
Definition at line 144 of file arguments.h.
                                   {
#define F(name, ...) kRuntime_##name,
  FOR_EACH_INTRINSIC(F)
#undef F
};
Function Documentation
CanTriggerGC()
template<typename... T>
constexpr bool v8::internal::detail::CanTriggerGC (T... properties) [constexpr]
Definition at line 44 of file runtime.h.
                                             {
  return !((properties == RuntimeCallProperty::kCannotTriggerGC) || ...);
}
References v8::internal::kCannotTriggerGC.
ConvertRawHashToUsableHash()
template<typename T >
uint32_t v8::internal::detail::ConvertRawHashToUsableHash (T raw_hash)
Definition at line 37 of file string-hasher-inl.h.
                                                {
  // Limit to the supported bits.
  const int32_t hash = static_cast<int32_t>(raw_hash & String::HashBits::kMax);
  // Ensure that the hash is kZeroHash, if the computed value is 0.
  return hash == 0 ? StringHasher::kZeroHash : hash;
}
References v8::base::BitField< T, shift, size, U >::kMax, and v8::internal::StringHasher::kZeroHash.
Referenced by v8::internal::RunningStringHasher::Finalize(), and GetUsableRapidHash().
Destructor()
template<typename CppType >
static void v8::internal::detail::Destructor (void * ptr) [static]
Definition at line 19 of file managed-inl.h.
                                  {
  auto shared_ptr_ptr = reinterpret_cast<std::shared_ptr<CppType>*>(ptr);
  delete shared_ptr_ptr;
}
FirstInvalidRegister() [1/2]
constexpr size_t v8::internal::detail::FirstInvalidRegister (EmptyRegisterArray regs) [constexpr]
Definition at line 201 of file interface-descriptors-inl.h.
{ return 0; }
FirstInvalidRegister() [2/2]
template<size_t N, size_t Index = 0>
constexpr size_t v8::internal::detail::FirstInvalidRegister (std::array< Register, N > regs) [constexpr]
Definition at line 198 of file interface-descriptors-inl.h.
                                                                  {
  return FirstInvalidRegisterHelper<N, 0>::Call(regs);
}
References v8::internal::detail::FirstInvalidRegisterHelper< N, Index >::Call().
Referenced by v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >::GetRegisterParameterCount().
GetRapidHash() [1/2]
uint64_t v8::internal::detail::GetRapidHash (const uint16_t * chars, uint32_t length, uint64_t seed) [inline]
Definition at line 60 of file string-hasher-inl.h.
                                               {
  // For 2-byte strings we need to preserve the same hash for strings in just
  // the latin-1 range.
  if (V8_UNLIKELY(IsOnly8Bit(chars, length))) {
    return detail::HashConvertingTo8Bit(chars, length, seed);
  }
  return rapidhash(reinterpret_cast<const uint8_t*>(chars), 2 * length, seed);
}
References HashConvertingTo8Bit(), IsOnly8Bit(), v8::internal::length, and V8_UNLIKELY.
GetRapidHash() [2/2]
uint64_t v8::internal::detail::GetRapidHash (const uint8_t * chars, uint32_t length, uint64_t seed) [inline]
Definition at line 55 of file string-hasher-inl.h.
                                               {
  return rapidhash(chars, length, seed);
}
References v8::internal::length.
Referenced by GetUsableRapidHash().
GetUsableRapidHash()
template<typename uchar >
uint32_t v8::internal::detail::GetUsableRapidHash (const uchar * chars, uint32_t length, uint64_t seed) [inline]
Definition at line 71 of file string-hasher-inl.h.
                                                     {
  return ConvertRawHashToUsableHash(GetRapidHash(chars, length, seed));
}
References ConvertRawHashToUsableHash(), GetRapidHash(), and v8::internal::length.
Referenced by v8::internal::StringHasher::HashSequentialString().
HashConvertingTo8Bit()
uint64_t v8::internal::detail::HashConvertingTo8Bit (const uint16_t * chars, uint32_t length, uint64_t seed)
Definition at line 71 of file string-hasher.cc.
                                             {
  return rapidhash<ConvertTo8BitHashReader>(
      reinterpret_cast<const uint8_t*>(chars), length, seed);
}
References v8::internal::length.
Referenced by GetRapidHash().
IsOnly8Bit()
bool v8::internal::detail::IsOnly8Bit (const uint16_t * chars, unsigned len) [inline]
Definition at line 44 of file string-hasher-inl.h.
                                                               {
  // TODO(leszeks): This could be SIMD for efficiency on large strings, if we
  // need it.
  for (unsigned i = 0; i < len; ++i) {
    if (chars[i] > 255) {
      return false;
    }
  }
  return true;
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i.
Referenced by GetRapidHash().
RuntimeFunctionFullNameCanTriggerGC()
constexpr bool v8::internal::detail::RuntimeFunctionFullNameCanTriggerGC (RuntimeFunctionFullName function_name) [constexpr]
Definition at line 150 of file arguments.h.
                                           {
  switch (function_name) {
#define CASE(name, ...) \
  case RuntimeFunctionFullName::kRuntime_##name: \
    return Runtime::kCanTriggerGC[static_cast<int>(Runtime::k##name)];
    FOR_EACH_INTRINSIC(CASE)
#undef CASE
  }
}
References CASE, and FOR_EACH_INTRINSIC.
TryParseArrayIndex()
template<typename uchar >
IndexParseResult v8::internal::detail::TryParseArrayIndex (const uchar * chars, uint32_t length, uint32_t & i, ArrayIndexT & index) [inline]
Definition at line 129 of file string-hasher-inl.h.
                                                                  {
  DCHECK_GT(length, 0);
  DCHECK_LE(length, String::kMaxIntegerIndexSize);
  // The leading character can only be a zero for the string "0"; otherwise this
  // isn't a valid index string.
  index = chars[0] - '0';
  i = 1;
  if (index > 9) return kNonIndex;
  if (index == 0) {
    if (length > 1) return kNonIndex;
    DCHECK_EQ(length, 1);
    return kSuccess;
  }
  if (length > String::kMaxArrayIndexSize) return kOverflow;
  // TODO(leszeks): Use SIMD for this loop.
  for (; i < length; i++) {
    uchar c = chars[i];
    uint32_t val = c - '0';
    if (val > 9) return kNonIndex;
    index = (10 * index) + val;
  }
  if constexpr (sizeof(index) == sizeof(uint64_t)) {
    // If we have a large type for index, we'll never overflow it, so we can
    // have a simple comparison for array index overflow.
    if (index > String::kMaxArrayIndex) {
      return kOverflow;
    }
  } else {
    DCHECK(sizeof(index) == sizeof(uint32_t));
    // If index is a 32-bit int, we have to get a bit creative with the overflow
    // check.
    if (V8_UNLIKELY(length == String::kMaxArrayIndexSize)) {
      // If length is String::kMaxArrayIndexSize, and we know there is no zero
      // prefix, the minimum valid value is 1 followed by length - 1 zeros. If
      // our value is smaller than this, then we overflowed.
      //
      // Additionally, String::kMaxArrayIndex is UInt32Max - 1, so we can fold
      // in a check that index < UInt32Max by adding 1 to both sides, making
      // index = UInt32Max overflows, and only then checking for overflow.
      constexpr uint32_t kMinValidValue =
          TenToThe(String::kMaxArrayIndexSize - 1);
      if (index + 1 < kMinValidValue + 1) {
        // We won't try an integer index if there is overflow, so just return
        // non-index.
        DCHECK(String::kMaxArrayIndexSize == String::kMaxIntegerIndexSize);
        return kNonIndex;
      }
    }
  }
  DCHECK_LT(index, TenToThe(length));
  DCHECK_GE(index, TenToThe(length - 1));
  return kSuccess;
}
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GE, DCHECK_GT, DCHECK_LE, DCHECK_LT, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::Name::kMaxArrayIndex, v8::internal::Name::kMaxArrayIndexSize, v8::internal::Name::kMaxIntegerIndexSize, kNonIndex, kOverflow, kSuccess, v8::internal::length, v8::internal::TenToThe(), and V8_UNLIKELY.
Referenced by v8::internal::StringHasher::HashSequentialString().
Variable Documentation
is_complex_subtype_v
template<typename Derived , typename Base >
constexpr bool v8::internal::detail::is_complex_subtype_v [static], [constexpr]
Initial value:
=
    is_complex_subtype<Derived, Base>::value
Definition at line 254 of file tagged.h.
is_simple_subtype_v
template<typename Derived , typename Base >
constexpr bool v8::internal::detail::is_simple_subtype_v [static], [constexpr]
Initial value:
=
    is_simple_subtype<Derived, Base>::value
Definition at line 163 of file tagged.h.
kCodeTargetTag
constexpr int v8::internal::detail::kCodeTargetTag = 1 [constexpr]
Definition at line 76 of file reloc-info.h.
Referenced by v8::internal::RelocIteratorBase< RelocInfoT >::next(), and v8::internal::RelocInfoWriter::Write().
kDefaultTag
constexpr int v8::internal::detail::kDefaultTag = 3 [constexpr]
Definition at line 78 of file reloc-info.h.
Referenced by v8::internal::RelocIteratorBase< RelocInfoT >::next(), and v8::internal::RelocInfoWriter::WriteMode().
kEmbeddedObjectTag
constexpr int v8::internal::detail::kEmbeddedObjectTag = 0 [constexpr]
Definition at line 75 of file reloc-info.h.
Referenced by v8::internal::RelocIteratorBase< RelocInfoT >::next(), and v8::internal::RelocInfoWriter::Write().
kLongTagBits
constexpr int v8::internal::detail::kLongTagBits = 6 [constexpr]
Definition at line 73 of file reloc-info.h.
Referenced by v8::internal::RelocIteratorBase< RelocInfoT >::GetMode(), and v8::internal::RelocInfoWriter::WriteMode().
kSmallPCDeltaBits
constexpr int v8::internal::detail::kSmallPCDeltaBits = kBitsPerByte - kTagBits [constexpr]
Definition at line 80 of file reloc-info.h.
Referenced by v8::internal::RelocIteratorBase< RelocInfoT >::AdvanceReadLongPCJump(), and v8::internal::RelocInfoWriter::WriteLongPCJump().
kSmallPCDeltaMask
constexpr int v8::internal::detail::kSmallPCDeltaMask = (1 << kSmallPCDeltaBits) - 1 [constexpr]
Definition at line 81 of file reloc-info.h.
Referenced by v8::internal::RelocInfoWriter::WriteLongPCJump().
kTagBits
constexpr int v8::internal::detail::kTagBits = 2 [constexpr]
Definition at line 71 of file reloc-info.h.
Referenced by v8::internal::RelocIteratorBase< RelocInfoT >::GetMode(), v8::internal::RelocIteratorBase< RelocInfoT >::ReadShortTaggedPC(), v8::internal::RelocInfoWriter::WriteMode(), and v8::internal::RelocInfoWriter::WriteShortTaggedPC().
kTagMask
constexpr int v8::internal::detail::kTagMask = (1 << kTagBits) - 1 [constexpr]
Definition at line 72 of file reloc-info.h.
Referenced by v8::internal::RelocIteratorBase< RelocInfoT >::AdvanceGetTag(), v8::internal::TaggedPayload< PayloadTaggingScheme >::ExtractTag(), v8::internal::TaggedPayload< PayloadTaggingScheme >::IsTaggedWith(), and v8::internal::TaggedPayload< PayloadTaggingScheme >::SetTag().
kWasmStubCallTag
constexpr int v8::internal::detail::kWasmStubCallTag = 2 [constexpr]
Definition at line 77 of file reloc-info.h.
Referenced by v8::internal::RelocIteratorBase< RelocInfoT >::next(), and v8::internal::RelocInfoWriter::Write().
V8_OBJECT_END
v8::internal::detail::ArrayHeaderBase< Super, true > v8::internal::detail::V8_OBJECT_END