v8::internal::compiler::anonymous_namespace{memory-lowering.cc} Namespace Reference
Functions
bool ValueNeedsWriteBarrier (Node *value, Isolate *isolate)
Function Documentation
ValueNeedsWriteBarrier()
bool v8::internal::compiler::anonymous_namespace{memory-lowering.cc}::ValueNeedsWriteBarrier (Node * value, Isolate * isolate)
Definition at line 680 of file memory-lowering.cc.
                                                           {
  switch (value->opcode()) {
    case IrOpcode::kBitcastWordToTaggedSigned:
      return false;
    case IrOpcode::kHeapConstant: {
      RootIndex root_index;
      if (isolate->roots_table().IsRootHandle(HeapConstantOf(value->op()),
                                              &root_index) &&
          RootsTable::IsImmortalImmovable(root_index)) {
        return false;
      }
      break;
    }
    default:
      break;
  }
  return true;
}
References v8::internal::compiler::HeapConstantOf(), v8::internal::RootsTable::IsImmortalImmovable(), v8::internal::RootsTable::IsRootHandle(), v8::internal::Isolate::roots_table(), and v8::internal::value.
Referenced by v8::internal::compiler::MemoryLowering::ComputeWriteBarrierKind().