v8::internal::anonymous_namespace{platform-embedded-file-writer-zos.cc} Namespace Reference
Functions
int hlasmPrintLine (FILE *fp, const char *fmt,...)
Function Documentation
hlasmPrintLine()
int v8::internal::anonymous_namespace{platform-embedded-file-writer-zos.cc}::hlasmPrintLine (FILE * fp, const char * fmt, ...)
Definition at line 21 of file platform-embedded-file-writer-zos.cc.
                                                   {
  int ret;
  char buffer[4096];
  int offset = 0;
  static char indent[kAsmContIndentLen] = "";
  va_list ap;
  va_start(ap, fmt);
  ret = vsnprintf(buffer, sizeof(buffer), fmt, ap);
  va_end(ap);
  if (!*indent) memset(indent, ' ', sizeof(indent));
  if (ret > kAsmMaxLineLen && buffer[kAsmMaxLineLen] != '\n') {
    offset += fwrite(buffer + offset, 1, kAsmMaxLineLen, fp);
    // Write continuation mark
    fwrite("-\n", 1, 2, fp);
    ret -= kAsmMaxLineLen;
    while (ret > kAsmContMaxLen) {
      // indent by kAsmContIndentLen
      fwrite(indent, 1, kAsmContIndentLen, fp);
      offset += fwrite(buffer + offset, 1, kAsmContMaxLen, fp);
      // write continuation mark
      fwrite("-\n", 1, 2, fp);
      ret -= kAsmContMaxLen;
    }
    if (ret > 0) {
      // indent kAsmContIndentLen blanks
      fwrite(indent, 1, kAsmContIndentLen, fp);
      offset += fwrite(buffer + offset, 1, ret, fp);
    }
  } else {
    offset += fwrite(buffer + offset, 1, ret, fp);
  }
  return ret;
}
References v8::internal::kAsmContIndentLen, v8::internal::kAsmContMaxLen, and v8::internal::kAsmMaxLineLen.
Referenced by v8::internal::PlatformEmbeddedFileWriterZOS::Comment(), v8::internal::PlatformEmbeddedFileWriterZOS::DeclareFunctionBegin(), v8::internal::PlatformEmbeddedFileWriterZOS::DeclareLabel(), v8::internal::PlatformEmbeddedFileWriterZOS::DeclareSymbolGlobal(), and v8::internal::PlatformEmbeddedFileWriterZOS::SourceInfo().