v8::internal::anonymous_namespace{js-array-buffer.cc} Namespace Reference
Functions
bool CanonicalNumericIndexString (Isolate *isolate, const PropertyKey &lookup_key, bool *is_minus_zero)
Function Documentation
CanonicalNumericIndexString()
bool v8::internal::anonymous_namespace{js-array-buffer.cc}::CanonicalNumericIndexString (Isolate * isolate, const PropertyKey & lookup_key, bool * is_minus_zero)
Definition at line 19 of file js-array-buffer.cc.
                                                      {
  // 1. Assert: Type(argument) is String.
  DCHECK(lookup_key.is_element() || IsString(*lookup_key.name()));
  *is_minus_zero = false;
  if (lookup_key.is_element()) return true;
  DirectHandle<String> key = Cast<String>(lookup_key.name());
  // 3. Let n be ! ToNumber(argument).
  DirectHandle<Object> result = String::ToNumber(isolate, key);
  if (IsMinusZero(*result)) {
    // 2. If argument is "-0", return -0𝔽.
    // We are not performing SaveValue check for -0 because it'll be rejected
    // anyway.
    *is_minus_zero = true;
  } else {
    // 4. If SameValue(! ToString(n), argument) is false, return undefined.
    DirectHandle<String> str =
        Object::ToString(isolate, result).ToHandleChecked();
    // Avoid treating strings like "2E1" and "20" as the same key.
    if (!Object::SameValue(*str, *key)) return false;
  }
  return true;
}
References v8::internal::DCHECK(), v8::internal::PropertyKey::is_element(), v8::internal::compiler::turboshaft::detail::is_minus_zero(), v8::internal::IsMinusZero(), v8::internal::key, v8::internal::PropertyKey::name, v8::base::internal::result, v8::internal::Object::SameValue(), v8::Value::ToNumber(), and v8::Value::ToString().
Referenced by v8::internal::JSTypedArray::DefineOwnProperty().