heap::base Namespace Reference
Namespaces
 anonymous_namespace{incremental-marking-schedule.cc}
 anonymous_namespace{stack.cc}
 internal
Classes
class ActiveSystemPages
class BasicSlotSet
struct BytesAndDuration
class SmoothedBytesAndDuration
class CachedUnorderedMap
class IncrementalMarkingSchedule
class SuspendTagCheckingScope
class StackVisitor
class Stack
class WorklistBase
class Worklist
Typedefs
using IterateStackCallback = void(*)(const Stack *, StackVisitor *, intptr_t *)
using BytesAndDurationBuffer = v8::base::RingBuffer< BytesAndDuration >
using StackVisitorCallback = void(*)(StackVisitor *)
Enumerations
enum SlotCallbackResult { KEEP_SLOT
, REMOVE_SLOT
 }
Functions
void PushAllRegistersAndIterateStack (const Stack *sp, StackVisitor *sv, IterateStackCallback callback)
std::optional< double > AverageSpeed (const BytesAndDurationBuffer &buffer, const BytesAndDuration &initial, std::optional< v8::base::TimeDelta > selected_duration, size_t min_non_empty_speed=0, size_t max_speed=std::numeric_limits< size_t >::max())
void PushAllRegistersAndIterateStack (Stack *stack, void *argument, Stack::IterateStackCallback callback)
Typedef Documentation
BytesAndDurationBuffer
using heap::base::BytesAndDurationBuffer = typedef v8::base::RingBuffer<BytesAndDuration>
Definition at line 27 of file bytes.h.
IterateStackCallback
using heap::base::IterateStackCallback = typedef void (*)(const Stack*, StackVisitor*, intptr_t*)
Definition at line 18 of file push_registers_asm.cc.
StackVisitorCallback
using heap::base::StackVisitorCallback = typedef void (*)(StackVisitor*)
Definition at line 23 of file stack.h.
Enumeration Type Documentation
SlotCallbackResult
enum heap::base::SlotCallbackResult
Enumerator
KEEP_SLOT
REMOVE_SLOT
Definition at line 22 of file basic-slot-set.h.
{ KEEP_SLOT, REMOVE_SLOT };
Function Documentation
AverageSpeed()
std::optional<double> heap::base::AverageSpeed (const BytesAndDurationBuffer & buffer, const BytesAndDuration & initial, std::optional< v8::base::TimeDelta > selected_duration, size_t min_non_empty_speed = 0, size_t max_speed = std::numeric_limits<size_t>::max()) [inline]
Definition at line 34 of file bytes.h.
                                                       {
  const BytesAndDuration sum = buffer.Reduce(
      [selected_duration](const BytesAndDuration& a,
                          const BytesAndDuration& b) {
        if (selected_duration.has_value() &&
            a.duration >= selected_duration.value()) {
          return a;
        }
        return BytesAndDuration(a.bytes + b.bytes, a.duration + b.duration);
      },
      initial);
  const auto duration = sum.duration;
  if (duration.IsZero()) {
    return std::nullopt;
  }
  return std::max(
      std::min(static_cast<double>(sum.bytes) / duration.InMillisecondsF(),
               static_cast<double>(max_speed)),
      static_cast<double>(min_non_empty_speed));
}
References heap::base::BytesAndDuration::bytes, v8::internal::duration, heap::base::BytesAndDuration::duration, and v8::base::RingBuffer< T, _SIZE >::Reduce().
Referenced by v8::internal::anonymous_namespace{gc-tracer.cc}::BoundedAverageSpeed().
PushAllRegistersAndIterateStack() [1/2]
void heap::base::PushAllRegistersAndIterateStack (const Stack * sp, StackVisitor * sv, IterateStackCallback callback)
Definition at line 19 of file push_registers_asm.cc.
                                                                               {
  __asm volatile(
      " lg 1,%0 \n" // Set up first parameter (sp)
      " lg 2,%1 \n" // Set up second parameter (sv)
      " lg 7,%2 \n" // Get callback function descriptor into r7
      " lgr 3,4 \n" // Set up third parameter (r4 - stack pointer)
      " lg 6,8(,7) \n" // Get code address into r6
      " lg 5,0(,7) \n" // Get environment into r5
      " basr 7,6 \n" // Branch to r6 (callback)
      " nopr 0 \n"
      :
      : "m"(sp), "m"(sv), "m"(callback)
      : "r0", "r1", "r2", "r3", "r5", "r6", "r7", "r9", "r10", "r11", "r12",
        "r13", "r14", "r15");
}
Referenced by heap::base::Stack::TrampolineCallbackHelper().
PushAllRegistersAndIterateStack() [2/2]
void heap::base::PushAllRegistersAndIterateStack (Stack * stack, void * argument, Stack::IterateStackCallback callback)