v8::internal::anonymous_namespace{api-natives.cc} Namespace Reference
Namespaces
 anonymous_namespace{api-natives.cc}
Classes
class InvokeScope
class AccessCheckDisableScope
Functions
MaybeHandle< JSObject > InstantiateObject (Isolate *isolate, DirectHandle< ObjectTemplateInfo > data, DirectHandle< JSReceiver > new_target, bool is_prototype)
MaybeHandle< JSFunction > InstantiateFunction (Isolate *isolate, DirectHandle< NativeContext > native_context, DirectHandle< FunctionTemplateInfo > data, MaybeDirectHandle< Name > maybe_name={})
MaybeHandle< JSFunction > InstantiateFunction (Isolate *isolate, DirectHandle< FunctionTemplateInfo > data, MaybeDirectHandle< Name > maybe_name={})
MaybeDirectHandle< Object > Instantiate (Isolate *isolate, DirectHandle< Object > data, MaybeDirectHandle< Name > maybe_name={})
MaybeDirectHandle< Object > DefineAccessorProperty (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< Name > name, DirectHandle< Object > getter, DirectHandle< Object > setter, PropertyAttributes attributes)
MaybeDirectHandle< Object > DefineDataProperty (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< Name > name, DirectHandle< Object > prop_data, PropertyAttributes attributes)
void DisableAccessChecks (Isolate *isolate, DirectHandle< JSObject > object)
void EnableAccessChecks (Isolate *isolate, DirectHandle< JSObject > object)
Tagged< Object > GetIntrinsic (Isolate *isolate, v8::Intrinsic intrinsic)
template<typename TemplateInfoT >
MaybeHandle< JSObject > ConfigureInstance (Isolate *isolate, Handle< JSObject > obj, DirectHandle< TemplateInfoT > data)
bool IsSimpleInstantiation (Isolate *isolate, Tagged< ObjectTemplateInfo > info, Tagged< JSReceiver > new_target)
void AddPropertyToPropertyList (Isolate *isolate, DirectHandle< TemplateInfoWithProperties > info, base::Vector< DirectHandle< Object >> data)
Function Documentation
AddPropertyToPropertyList()
void v8::internal::anonymous_namespace{api-natives.cc}::AddPropertyToPropertyList (Isolate * isolate, DirectHandle< TemplateInfoWithProperties > info, base::Vector< DirectHandle< Object >> data)
Definition at line 460 of file api-natives.cc.
                                                                      {
  Tagged<Object> maybe_list = info->property_list();
  DirectHandle<ArrayList> list;
  if (IsUndefined(maybe_list, isolate)) {
    list = ArrayList::New(isolate, static_cast<int>(data.size()),
                          AllocationType::kOld);
  } else {
    list = direct_handle(Cast<ArrayList>(maybe_list), isolate);
  }
  info->set_number_of_properties(info->number_of_properties() + 1);
  for (DirectHandle<Object> value : data) {
    if (value.is_null())
      value = Cast<Object>(isolate->factory()->undefined_value());
    list = ArrayList::Add(isolate, list, value);
  }
  info->set_property_list(*list);
}
References v8::internal::ArrayList::Add(), v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::kOld, v8::internal::ArrayList::New(), and v8::internal::value.
Referenced by v8::internal::ApiNatives::AddAccessorProperty(), and v8::internal::ApiNatives::AddDataProperty().
ConfigureInstance()
template<typename TemplateInfoT >
MaybeHandle<JSObject> v8::internal::anonymous_namespace{api-natives.cc}::ConfigureInstance (Isolate * isolate, Handle< JSObject > obj, DirectHandle< TemplateInfoT > data)
Definition at line 183 of file api-natives.cc.
                                                                          {
  RCS_SCOPE(isolate, RuntimeCallCounterId::kConfigureInstance);
  HandleScope scope(isolate);
  // Disable access checks while instantiating the object.
  AccessCheckDisableScope access_check_scope(isolate, obj);
  // Walk the inheritance chain and copy all accessors to current object.
  int max_number_of_properties = 0;
  Tagged<TemplateInfoT> info = *data;
  while (!info.is_null()) {
    Tagged<Object> props = info->property_accessors();
    if (!IsUndefined(props, isolate)) {
      max_number_of_properties += Cast<ArrayList>(props)->length();
    }
    info = info->GetParent(isolate);
  }
  if (max_number_of_properties > 0) {
    int valid_descriptors = 0;
    // Use a temporary FixedArray to accumulate unique accessors.
    DirectHandle<FixedArray> array =
        isolate->factory()->NewFixedArray(max_number_of_properties);
    // TODO(leszeks): Avoid creating unnecessary handles for cases where we
    // don't need to append anything.
    for (DirectHandle<TemplateInfoT> temp(*data, isolate); !(*temp).is_null();
         temp = direct_handle(temp->GetParent(isolate), isolate)) {
      // Accumulate accessors.
      Tagged<Object> maybe_properties = temp->property_accessors();
      if (!IsUndefined(maybe_properties, isolate)) {
        valid_descriptors = AccessorInfo::AppendUnique(
            isolate, direct_handle(maybe_properties, isolate), array,
            valid_descriptors);
      }
    }
    // Install accumulated accessors.
    for (int i = 0; i < valid_descriptors; i++) {
      DirectHandle<AccessorInfo> accessor(Cast<AccessorInfo>(array->get(i)),
                                          isolate);
      DirectHandle<Name> name(Cast<Name>(accessor->name()), isolate);
      JSObject::SetAccessor(obj, name, accessor,
                            accessor->initial_property_attributes())
          .Assert();
    }
  }
  Tagged<Object> maybe_property_list = data->property_list();
  if (IsUndefined(maybe_property_list, isolate)) return obj;
  DirectHandle<ArrayList> properties(Cast<ArrayList>(maybe_property_list),
                                     isolate);
  if (properties->length() == 0) return obj;
  int i = 0;
  for (int c = 0; c < data->number_of_properties(); c++) {
    auto name = direct_handle(Cast<Name>(properties->get(i++)), isolate);
    Tagged<Object> bit = properties->get(i++);
    if (IsSmi(bit)) {
      PropertyDetails details(Cast<Smi>(bit));
      PropertyAttributes attributes = details.attributes();
      PropertyKind kind = details.kind();
      if (kind == PropertyKind::kData) {
        auto prop_data = handle(properties->get(i++), isolate);
        RETURN_ON_EXCEPTION(isolate, DefineDataProperty(isolate, obj, name,
                                                        prop_data, attributes));
      } else {
        auto getter = direct_handle(properties->get(i++), isolate);
        auto setter = direct_handle(properties->get(i++), isolate);
        RETURN_ON_EXCEPTION(
            isolate, DefineAccessorProperty(isolate, obj, name, getter, setter,
                                            attributes));
      }
    } else {
      // Intrinsic data property --- Get appropriate value from the current
      // context.
      PropertyDetails details(Cast<Smi>(properties->get(i++)));
      PropertyAttributes attributes = details.attributes();
      DCHECK_EQ(PropertyKind::kData, details.kind());
      v8::Intrinsic intrinsic =
          static_cast<v8::Intrinsic>(Smi::ToInt(properties->get(i++)));
      auto prop_data = handle(GetIntrinsic(isolate, intrinsic), isolate);
      RETURN_ON_EXCEPTION(isolate, DefineDataProperty(isolate, obj, name,
                                                      prop_data, attributes));
    }
  }
  return obj;
}
References v8::internal::AccessorInfo::AppendUnique(), v8::internal::PropertyDetails::attributes(), DCHECK_EQ, DefineAccessorProperty(), DefineDataProperty(), v8::internal::direct_handle(), v8::internal::Isolate::factory(), GetIntrinsic(), v8::internal::handle(), v8::internal::DirectHandle< T >::is_null(), v8::internal::Tagged< HeapObject >::is_null(), v8::internal::IsSmi(), v8::internal::kData, v8::internal::PropertyDetails::kind(), v8::internal::name, v8::internal::FactoryBase< Impl >::NewFixedArray(), RCS_SCOPE, RETURN_ON_EXCEPTION, v8::internal::JSObject::SetAccessor(), v8::internal::setter, and v8::internal::Smi::ToInt().
Referenced by InstantiateFunction(), and InstantiateObject().
DefineAccessorProperty()
MaybeDirectHandle<Object> v8::internal::anonymous_namespace{api-natives.cc}::DefineAccessorProperty (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< Name > name, DirectHandle< Object > getter, DirectHandle< Object > setter, PropertyAttributes attributes)
Definition at line 72 of file api-natives.cc.
                                   {
  DCHECK_IMPLIES(IsFunctionTemplateInfo(*getter),
                 Cast<FunctionTemplateInfo>(*getter)->is_cacheable());
  DCHECK_IMPLIES(IsFunctionTemplateInfo(*setter),
                 Cast<FunctionTemplateInfo>(*setter)->is_cacheable());
  if (IsFunctionTemplateInfo(*getter) &&
      Cast<FunctionTemplateInfo>(*getter)->BreakAtEntry(isolate)) {
    ASSIGN_RETURN_ON_EXCEPTION(
        isolate, getter,
        InstantiateFunction(isolate, Cast<FunctionTemplateInfo>(getter)));
    DirectHandle<Code> trampoline = BUILTIN_CODE(isolate, DebugBreakTrampoline);
    Cast<JSFunction>(getter)->UpdateCode(isolate, *trampoline);
  }
  if (IsFunctionTemplateInfo(*setter) &&
      Cast<FunctionTemplateInfo>(*setter)->BreakAtEntry(isolate)) {
    ASSIGN_RETURN_ON_EXCEPTION(
        isolate, setter,
        InstantiateFunction(isolate, Cast<FunctionTemplateInfo>(setter)));
    DirectHandle<Code> trampoline = BUILTIN_CODE(isolate, DebugBreakTrampoline);
    Cast<JSFunction>(setter)->UpdateCode(isolate, *trampoline);
  }
  RETURN_ON_EXCEPTION(isolate, JSObject::DefineOwnAccessorIgnoreAttributes(
                                   object, name, getter, setter, attributes));
  return object;
}
References ASSIGN_RETURN_ON_EXCEPTION, BUILTIN_CODE, DCHECK_IMPLIES, v8::internal::JSObject::DefineOwnAccessorIgnoreAttributes(), InstantiateFunction(), v8::internal::name, RETURN_ON_EXCEPTION, and v8::internal::setter.
Referenced by ConfigureInstance().
DefineDataProperty()
MaybeDirectHandle<Object> v8::internal::anonymous_namespace{api-natives.cc}::DefineDataProperty (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< Name > name, DirectHandle< Object > prop_data, PropertyAttributes attributes)
Definition at line 101 of file api-natives.cc.
                                                                            {
  DirectHandle<Object> value;
  ASSIGN_RETURN_ON_EXCEPTION(isolate, value,
                             Instantiate(isolate, prop_data, name));
  PropertyKey key(isolate, name);
  LookupIterator it(isolate, object, key, LookupIterator::OWN_SKIP_INTERCEPTOR);
#ifdef DEBUG
  Maybe<PropertyAttributes> maybe = JSReceiver::GetPropertyAttributes(&it);
  DCHECK(maybe.IsJust());
  if (it.IsFound()) {
    THROW_NEW_ERROR(
        isolate,
        NewTypeError(MessageTemplate::kDuplicateTemplateProperty, name));
  }
#endif
  MAYBE_RETURN_NULL(Object::AddDataProperty(&it, value, attributes,
                                            Just(ShouldThrow::kThrowOnError),
                                            StoreOrigin::kNamed));
  return value;
}
References v8::internal::Object::AddDataProperty(), ASSIGN_RETURN_ON_EXCEPTION, v8::internal::DCHECK(), v8::internal::JSReceiver::GetPropertyAttributes(), Instantiate(), v8::internal::LookupIterator::IsFound(), v8::Maybe< T >::IsJust(), v8::Just(), v8::internal::key, v8::internal::kNamed, v8::internal::kThrowOnError, MAYBE_RETURN_NULL, v8::internal::name, v8::internal::LookupIterator::OWN_SKIP_INTERCEPTOR, THROW_NEW_ERROR, and v8::internal::value.
Referenced by ConfigureInstance().
DisableAccessChecks()
void v8::internal::anonymous_namespace{api-natives.cc}::DisableAccessChecks (Isolate * isolate, DirectHandle< JSObject > object)
Definition at line 129 of file api-natives.cc.
                                                                          {
  DirectHandle<Map> old_map(object->map(), isolate);
  // Copy map so it won't interfere constructor's initial map.
  DirectHandle<Map> new_map =
      Map::Copy(isolate, old_map, "DisableAccessChecks");
  new_map->set_is_access_check_needed(false);
  JSObject::MigrateToMap(isolate, object, new_map);
}
References v8::internal::Map::Copy(), and v8::internal::JSObject::MigrateToMap().
Referenced by v8::internal::anonymous_namespace{api-natives.cc}::AccessCheckDisableScope::AccessCheckDisableScope().
EnableAccessChecks()
void v8::internal::anonymous_namespace{api-natives.cc}::EnableAccessChecks (Isolate * isolate, DirectHandle< JSObject > object)
Definition at line 138 of file api-natives.cc.
                                                                         {
  DirectHandle<Map> old_map(object->map(), isolate);
  // Copy map so it won't interfere constructor's initial map.
  DirectHandle<Map> new_map = Map::Copy(isolate, old_map, "EnableAccessChecks");
  new_map->set_is_access_check_needed(true);
  new_map->set_may_have_interesting_properties(true);
  JSObject::MigrateToMap(isolate, object, new_map);
}
References v8::internal::Map::Copy(), and v8::internal::JSObject::MigrateToMap().
Referenced by v8::internal::anonymous_namespace{api-natives.cc}::AccessCheckDisableScope::~AccessCheckDisableScope().
GetIntrinsic()
Tagged<Object> v8::internal::anonymous_namespace{api-natives.cc}::GetIntrinsic (Isolate * isolate, v8::Intrinsic intrinsic)
Definition at line 169 of file api-natives.cc.
                                                                     {
  DirectHandle<Context> native_context = isolate->native_context();
  DCHECK(!native_context.is_null());
  switch (intrinsic) {
#define GET_INTRINSIC_VALUE(name, iname) \
  case v8::k##name: \
    return native_context->iname();
    V8_INTRINSICS_LIST(GET_INTRINSIC_VALUE)
#undef GET_INTRINSIC_VALUE
  }
  return Tagged<Object>();
}
References v8::internal::DCHECK(), GET_INTRINSIC_VALUE, v8::internal::Isolate::native_context(), v8::internal::native_context, v8::internal::Tagged< Object >, and V8_INTRINSICS_LIST.
Referenced by ConfigureInstance().
Instantiate()
MaybeDirectHandle<Object> v8::internal::anonymous_namespace{api-natives.cc}::Instantiate (Isolate * isolate, DirectHandle< Object > data, MaybeDirectHandle< Name > maybe_name = {})
Definition at line 58 of file api-natives.cc.
                                                                           {}) {
  if (IsFunctionTemplateInfo(*data)) {
    return InstantiateFunction(isolate, Cast<FunctionTemplateInfo>(data),
                               maybe_name);
  } else if (IsObjectTemplateInfo(*data)) {
    return InstantiateObject(isolate, Cast<ObjectTemplateInfo>(data), {},
                             false);
  } else {
    return data;
  }
}
Referenced by DefineDataProperty().
InstantiateFunction() [1/2]
MaybeHandle<JSFunction> v8::internal::anonymous_namespace{api-natives.cc}::InstantiateFunction (Isolate * isolate, DirectHandle< FunctionTemplateInfo > data, MaybeDirectHandle< Name > maybe_name = {})
Definition at line 51 of file api-natives.cc.
                                         {}) {
  return InstantiateFunction(isolate, isolate->native_context(), data,
                             maybe_name);
}
Referenced by DefineAccessorProperty(), v8::internal::anonymous_namespace{api-natives.cc}::anonymous_namespace{api-natives.cc}::GetInstancePrototype(), v8::internal::ApiNatives::InstantiateFunction(), and InstantiateObject().
InstantiateFunction() [2/2]
MaybeHandle< JSFunction > v8::internal::anonymous_namespace{api-natives.cc}::InstantiateFunction (Isolate * isolate, DirectHandle< NativeContext > native_context, DirectHandle< FunctionTemplateInfo > data, MaybeDirectHandle< Name > maybe_name = {})
Definition at line 384 of file api-natives.cc.
                                        {
  RCS_SCOPE(isolate, RuntimeCallCounterId::kInstantiateFunction);
  bool should_cache = info->is_cacheable();
  if (should_cache) {
    Handle<JSObject> result;
    if (TemplateInfo::ProbeInstantiationsCache<JSObject>(
            isolate, native_context, info,
            TemplateInfo::CachingMode::kUnlimited)
            .ToHandle(&result)) {
      return Cast<JSFunction>(result);
    }
  }
  DirectHandle<Object> prototype;
  if (!info->remove_prototype()) {
    DirectHandle<Object> prototype_templ(info->GetPrototypeTemplate(), isolate);
    if (IsUndefined(*prototype_templ, isolate)) {
      DirectHandle<Object> protoype_provider_templ(
          info->GetPrototypeProviderTemplate(), isolate);
      if (IsUndefined(*protoype_provider_templ, isolate)) {
        prototype = isolate->factory()->NewJSObject(
            direct_handle(native_context->object_function(), isolate));
      } else {
        ASSIGN_RETURN_ON_EXCEPTION(
            isolate, prototype,
            GetInstancePrototype(isolate, protoype_provider_templ));
      }
    } else {
      ASSIGN_RETURN_ON_EXCEPTION(
          isolate, prototype,
          InstantiateObject(isolate, Cast<ObjectTemplateInfo>(prototype_templ),
                            DirectHandle<JSReceiver>(), true));
    }
    DirectHandle<Object> parent(info->GetParentTemplate(), isolate);
    if (!IsUndefined(*parent, isolate)) {
      DirectHandle<Object> parent_prototype;
      ASSIGN_RETURN_ON_EXCEPTION(isolate, parent_prototype,
                                 GetInstancePrototype(isolate, parent));
      DirectHandle<JSPrototype> checked_parent_prototype;
      CHECK(TryCast(parent_prototype, &checked_parent_prototype));
      JSObject::ForceSetPrototype(isolate, Cast<JSObject>(prototype),
                                  checked_parent_prototype);
    }
  }
  InstanceType function_type = JS_SPECIAL_API_OBJECT_TYPE;
  if (!info->needs_access_check() &&
      IsUndefined(info->GetNamedPropertyHandler(), isolate) &&
      IsUndefined(info->GetIndexedPropertyHandler(), isolate)) {
    function_type = v8_flags.experimental_embedder_instance_types
                        ? info->GetInstanceType()
                        : JS_API_OBJECT_TYPE;
    DCHECK(InstanceTypeChecker::IsJSApiObject(function_type));
  }
  Handle<JSFunction> function = ApiNatives::CreateApiFunction(
      isolate, native_context, info, prototype, function_type, maybe_name);
  if (should_cache) {
    // Cache the function.
    TemplateInfo::CacheTemplateInstantiation(
        isolate, native_context, info, TemplateInfo::CachingMode::kUnlimited,
        function);
  }
  MaybeDirectHandle<JSObject> result =
      ConfigureInstance(isolate, function, info);
  if (result.is_null()) {
    // Uncache on error.
    TemplateInfo::UncacheTemplateInstantiation(
        isolate, native_context, info, TemplateInfo::CachingMode::kUnlimited);
    return {};
  }
  info->set_published(true);
  return function;
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::TemplateInfo::CacheTemplateInstantiation(), CHECK, ConfigureInstance(), v8::internal::ApiNatives::CreateApiFunction(), v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::JSObject::ForceSetPrototype(), v8::internal::anonymous_namespace{api-natives.cc}::anonymous_namespace{api-natives.cc}::GetInstancePrototype(), InstantiateObject(), v8::internal::TemplateInfo::kUnlimited, v8::internal::native_context, v8::internal::Factory::NewJSObject(), v8::internal::prototype, RCS_SCOPE, v8::base::internal::result, v8::anonymous_namespace{api.cc}::ToHandle(), v8::internal::TryCast(), v8::internal::TemplateInfo::UncacheTemplateInstantiation(), and v8::internal::v8_flags.
InstantiateObject()
MaybeHandle< JSObject > v8::internal::anonymous_namespace{api-natives.cc}::InstantiateObject (Isolate * isolate, DirectHandle< ObjectTemplateInfo > data, DirectHandle< JSReceiver > new_target, bool is_prototype)
Definition at line 287 of file api-natives.cc.
                                                           {
  RCS_SCOPE(isolate, RuntimeCallCounterId::kInstantiateObject);
  DirectHandle<JSFunction> constructor;
  bool should_cache = info->is_cacheable();
  if (!new_target.is_null()) {
    if (IsSimpleInstantiation(isolate, *info, *new_target)) {
      constructor = Cast<JSFunction>(new_target);
    } else {
      // Disable caching for subclass instantiation.
      should_cache = false;
    }
  }
  // Fast path.
  Handle<JSObject> result;
  if (should_cache) {
    if (TemplateInfo::ProbeInstantiationsCache<JSObject>(
            isolate, isolate->native_context(), info,
            TemplateInfo::CachingMode::kLimited)
            .ToHandle(&result)) {
      return isolate->factory()->CopyJSObject(result);
    }
  }
  if (constructor.is_null()) {
    Tagged<Object> maybe_constructor_info = info->constructor();
    if (IsUndefined(maybe_constructor_info, isolate)) {
      constructor = isolate->object_function();
    } else {
      // Enter a new scope. Recursion could otherwise create a lot of handles.
      HandleScope scope(isolate);
      DirectHandle<FunctionTemplateInfo> cons_templ(
          Cast<FunctionTemplateInfo>(maybe_constructor_info), isolate);
      DirectHandle<JSFunction> tmp_constructor;
      ASSIGN_RETURN_ON_EXCEPTION(isolate, tmp_constructor,
                                 InstantiateFunction(isolate, cons_templ));
      constructor = scope.CloseAndEscape(tmp_constructor);
    }
    if (new_target.is_null()) new_target = constructor;
  }
  const auto new_js_object_type =
      constructor->has_initial_map() &&
              IsJSApiWrapperObjectMap(constructor->initial_map())
          ? NewJSObjectType::kAPIWrapper
          : NewJSObjectType::kNoAPIWrapper;
  Handle<JSObject> object;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, object,
      JSObject::New(constructor, new_target, {}, new_js_object_type));
  if (is_prototype) JSObject::OptimizeAsPrototype(object);
  ASSIGN_RETURN_ON_EXCEPTION(isolate, result,
                             ConfigureInstance(isolate, object, info));
  if (info->immutable_proto()) {
    JSObject::SetImmutableProto(isolate, object);
  }
  if (!is_prototype) {
    // Keep prototypes in slow-mode. Let them be lazily turned fast later on.
    // TODO(dcarney): is this necessary?
    JSObject::MigrateSlowToFast(result, 0, "ApiNatives::InstantiateObject");
    // Don't cache prototypes.
    if (should_cache) {
      TemplateInfo::CacheTemplateInstantiation(
          isolate, isolate->native_context(), info,
          TemplateInfo::CachingMode::kLimited, result);
      result = isolate->factory()->CopyJSObject(result);
    }
  }
  return result;
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::TemplateInfo::CacheTemplateInstantiation(), ConfigureInstance(), v8::internal::Factory::CopyJSObject(), v8::internal::Isolate::factory(), InstantiateFunction(), v8::internal::DirectHandle< T >::is_null(), IsSimpleInstantiation(), v8::internal::kAPIWrapper, v8::internal::TemplateInfo::kLimited, v8::internal::kNoAPIWrapper, v8::internal::JSObject::MigrateSlowToFast(), v8::internal::Isolate::native_context(), v8::internal::JSObject::New(), v8::internal::JSObject::OptimizeAsPrototype(), RCS_SCOPE, v8::base::internal::result, and v8::internal::JSObject::SetImmutableProto().
Referenced by InstantiateFunction(), and v8::internal::ApiNatives::InstantiateObject().
IsSimpleInstantiation()
bool v8::internal::anonymous_namespace{api-natives.cc}::IsSimpleInstantiation (Isolate * isolate, Tagged< ObjectTemplateInfo > info, Tagged< JSReceiver > new_target)
Definition at line 275 of file api-natives.cc.
                                                          {
  DisallowGarbageCollection no_gc;
  if (!IsJSFunction(new_target)) return false;
  Tagged<JSFunction> fun = Cast<JSFunction>(new_target);
  if (!fun->shared()->IsApiFunction()) return false;
  if (fun->shared()->api_func_data() != info->constructor()) return false;
  if (info->immutable_proto()) return false;
  return fun->native_context() == isolate->raw_native_context();
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::Isolate::raw_native_context().
Referenced by InstantiateObject().