v8::base::helper Namespace Reference
Functions
template<typename T >
volatile std::atomic< T > * to_std_atomic (volatile T *ptr)
template<typename T >
volatile const std::atomic< T > * to_std_atomic_const (volatile const T *ptr)
int MemcmpNotEqualFundamental (Atomic8 u1, Atomic8 u2)
int MemcmpNotEqualFundamental (AtomicWord u1, AtomicWord u2)
Function Documentation
MemcmpNotEqualFundamental() [1/2]
int v8::base::helper::MemcmpNotEqualFundamental (Atomic8 u1, Atomic8 u2) [inline]
Definition at line 426 of file atomicops.h.
                                                             {
  DCHECK_NE(u1, u2);
  return u1 < u2 ? -1 : 1;
}
References DCHECK_NE.
Referenced by v8::base::Relaxed_Memcmp().
MemcmpNotEqualFundamental() [2/2]
int v8::base::helper::MemcmpNotEqualFundamental (AtomicWord u1, AtomicWord u2) [inline]
Definition at line 430 of file atomicops.h.
                                                                   {
  DCHECK_NE(u1, u2);
#if defined(V8_TARGET_BIG_ENDIAN)
  return u1 < u2 ? -1 : 1;
#else
  for (size_t i = 0; i < sizeof(AtomicWord); ++i) {
    uint8_t byte1 = u1 & 0xFF;
    uint8_t byte2 = u2 & 0xFF;
    if (byte1 != byte2) return byte1 < byte2 ? -1 : 1;
    u1 >>= 8;
    u2 >>= 8;
  }
  UNREACHABLE();
#endif
}
References DCHECK_NE, v8::internal::anonymous_namespace{json-stringifier.cc}::i, and UNREACHABLE.
to_std_atomic()
template<typename T >
volatile std::atomic<T>* v8::base::helper::to_std_atomic (volatile T * ptr)
Definition at line 82 of file atomicops.h.
                                                      {
  return reinterpret_cast<volatile std::atomic<T>*>(ptr);
}
Referenced by v8::base::Acquire_CompareAndSwap(), v8::base::AcquireRelease_CompareAndSwap(), v8::base::Relaxed_AtomicExchange(), v8::base::Relaxed_AtomicIncrement(), v8::base::Relaxed_CompareAndSwap(), v8::base::Relaxed_Store(), v8::base::Release_CompareAndSwap(), v8::base::Release_Store(), v8::base::SeqCst_AtomicExchange(), v8::base::SeqCst_CompareAndSwap(), and v8::base::SeqCst_Store().
to_std_atomic_const()
template<typename T >
volatile const std::atomic<T>* v8::base::helper::to_std_atomic_const (volatile const T * ptr)
Definition at line 86 of file atomicops.h.
                                                                        {
  return reinterpret_cast<volatile const std::atomic<T>*>(ptr);
}
Referenced by v8::base::Acquire_Load(), v8::base::Relaxed_Load(), and v8::base::SeqCst_Load().