v8::internal::compiler::anonymous_namespace{pair-load-store-reducer.cc} Namespace Reference
Functions
std::optional< std::tuple< int, const Operator * > > CanBePaired (Node *node1, Node *node2, MachineOperatorBuilder *machine, Isolate *isolate)
Function Documentation
CanBePaired()
std::optional<std::tuple<int, const Operator*> > v8::internal::compiler::anonymous_namespace{pair-load-store-reducer.cc}::CanBePaired (Node * node1, Node * node2, MachineOperatorBuilder * machine, Isolate * isolate)
Definition at line 17 of file pair-load-store-reducer.cc.
                      {
  DCHECK(node1->opcode() == IrOpcode::kStore &&
         node1->opcode() == IrOpcode::kStore);
  Node* base1 = node1->InputAt(0);
  Node* base2 = node2->InputAt(0);
  if (base1 != base2) return {};
  auto rep1 = StoreRepresentationOf(node1->op());
  auto rep2 = StoreRepresentationOf(node2->op());
  auto combo = machine->TryStorePair(rep1, rep2);
  if (!combo) return {};
  Node* index1 = node1->InputAt(1);
  Node* index2 = node2->InputAt(1);
  int idx1, idx2;
  if (index1->opcode() == IrOpcode::kInt64Constant) {
    idx1 = static_cast<int>(OpParameter<int64_t>(index1->op()));
  } else {
    return {};
  }
  if (index2->opcode() == IrOpcode::kInt64Constant) {
    idx2 = static_cast<int>(OpParameter<int64_t>(index2->op()));
  } else {
    return {};
  }
  int bytesize = 1 << ElementSizeLog2Of(rep1.representation());
  int diff = idx2 - idx1;
  if (diff != bytesize && diff != -bytesize) {
    return {};
  }
  return {{diff, *combo}};
}
References v8::internal::DCHECK(), v8::internal::ElementSizeLog2Of(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::StoreRepresentationOf(), and v8::internal::compiler::MachineOperatorBuilder::TryStorePair().
Referenced by v8::internal::compiler::PairLoadStoreReducer::Reduce().