v8::internal::anonymous_namespace{builtins-sharedarraybuffer.cc} Namespace Reference
Functions
size_t GetAddress64 (size_t index, size_t byte_offset)
size_t GetAddress32 (size_t index, size_t byte_offset)
V8_NOINLINE Maybe< bool > CheckAtomicsPauseIterationNumber (Isolate *isolate, DirectHandle< Object > iteration_number)
Function Documentation
CheckAtomicsPauseIterationNumber()
V8_NOINLINE Maybe<bool> v8::internal::anonymous_namespace{builtins-sharedarraybuffer.cc}::CheckAtomicsPauseIterationNumber (Isolate * isolate, DirectHandle< Object > iteration_number)
Definition at line 279 of file builtins-sharedarraybuffer.cc.
                                                             {
  constexpr char method_name[] = "Atomics.pause";
  // 1. If N is neither undefined nor an integral Number, throw a TypeError
  // exception.
  if (IsNumber(*iteration_number)) {
    double iter = Object::NumberValue(*iteration_number);
    if (std::isfinite(iter) && nearbyint(iter) == iter) {
      return Just(true);
    }
  }
  THROW_NEW_ERROR_RETURN_VALUE(
      isolate,
      NewError(isolate->type_error_function(),
               MessageTemplate::kArgumentIsNotUndefinedOrInteger,
               isolate->factory()->NewStringFromAsciiChecked(method_name)),
      Nothing<bool>());
}
References v8::internal::Isolate::factory(), v8::internal::IsNumber(), v8::Just(), v8::internal::anonymous_namespace{runtime-internal.cc}::NewError(), v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), v8::internal::Object::NumberValue(), and THROW_NEW_ERROR_RETURN_VALUE.
Referenced by v8::internal::BUILTIN().
GetAddress32()
size_t v8::internal::anonymous_namespace{builtins-sharedarraybuffer.cc}::GetAddress32 (size_t index, size_t byte_offset) [inline]
Definition at line 112 of file builtins-sharedarraybuffer.cc.
                                                             {
  return (index << 2) + byte_offset;
}
References v8::internal::index.
Referenced by v8::internal::BUILTIN(), and v8::internal::DoWait().
GetAddress64()
size_t v8::internal::anonymous_namespace{builtins-sharedarraybuffer.cc}::GetAddress64 (size_t index, size_t byte_offset) [inline]
Definition at line 108 of file builtins-sharedarraybuffer.cc.
                                                             {
  return (index << 3) + byte_offset;
}
References v8::internal::index.
Referenced by v8::internal::BUILTIN(), and v8::internal::DoWait().