v8::bigint::anonymous_namespace{mul-karatsuba.cc} Namespace Reference
Functions
int RoundUpLen (int len)
int KaratsubaLength (int n)
void KaratsubaSubtractionHelper (RWDigits result, Digits X, Digits Y, int *sign)
Function Documentation
KaratsubaLength()
int v8::bigint::anonymous_namespace{mul-karatsuba.cc}::KaratsubaLength (int n)
Definition at line 58 of file mul-karatsuba.cc.
                           {
  n = RoundUpLen(n);
  int i = 0;
  while (n > kKaratsubaThreshold) {
    n >>= 1;
    i++;
  }
  return n << i;
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::bigint::kKaratsubaThreshold, and RoundUpLen().
Referenced by v8::bigint::ProcessorImpl::KaratsubaChunk(), and v8::bigint::ProcessorImpl::MultiplyKaratsuba().
KaratsubaSubtractionHelper()
void v8::bigint::anonymous_namespace{mul-karatsuba.cc}::KaratsubaSubtractionHelper (RWDigits result, Digits X, Digits Y, int * sign)
Definition at line 69 of file mul-karatsuba.cc.
                                           {
  X.Normalize();
  Y.Normalize();
  digit_t borrow = 0;
  int i = 0;
  if (!GreaterThanOrEqual(X, Y)) {
    *sign = -(*sign);
    std::swap(X, Y);
  }
  for (; i < Y.len(); i++) {
    result[i] = digit_sub2(X[i], Y[i], borrow, &borrow);
  }
  for (; i < X.len(); i++) {
    result[i] = digit_sub(X[i], borrow, &borrow);
  }
  DCHECK(borrow == 0);
  for (; i < result.len(); i++) result[i] = 0;
}
References DCHECK, v8::bigint::digit_sub(), v8::bigint::digit_sub2(), v8::bigint::GreaterThanOrEqual(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::bigint::Digits::len(), v8::bigint::Digits::Normalize(), v8::base::internal::result, v8::internal::sign, and X().
Referenced by v8::bigint::ProcessorImpl::KaratsubaMain().
RoundUpLen()
int v8::bigint::anonymous_namespace{mul-karatsuba.cc}::RoundUpLen (int len)
Definition at line 41 of file mul-karatsuba.cc.
                        {
  if (len <= 36) return RoundUp(len, 2);
  // Keep the 4 or 5 most significant non-zero bits.
  int shift = BitLength(len) - 5;
  if ((len >> shift) >= 0x18) {
    shift++;
  }
  // Round up, unless we're only just above the threshold. This smoothes
  // the steps by which time goes up as input size increases.
  int additive = ((1 << shift) - 1);
  if (shift >= 2 && (len & additive) < (1 << (shift - 2))) {
    return len;
  }
  return ((len + additive) >> shift) << shift;
}
References v8::bigint::BitLength(), and v8::bigint::RoundUp().
Referenced by KaratsubaLength().