v8::internal::anonymous_namespace{sweeper.cc} Namespace Reference
Classes
class PromotedPageRecordMigratedSlotVisitor
Enumerations
enum class ZappingMode { kNone
, kCreateFillers
, kCreateFillersAndZap
 }
Functions
void AtomicZapBlock (Address addr, size_t size_in_bytes)
ZappingMode ShouldZapDeadObjectsOnPage ()
void ZapDeadObjectsInRange (Heap *heap, Address dead_start, Address dead_end, const ZappingMode zapping_mode)
bool ComparePagesForSweepingOrder (const PageMetadata *a, const PageMetadata *b)
bool ShouldUpdateRememberedSets (Heap *heap)
void ZapDeadObjectsOnPage (Heap *heap, PageMetadata *p)
void ClearPromotedPages (Heap *heap, std::vector< MutablePageMetadata * > pages)
void VerifyPreparedPage (PageMetadata *page)
Enumeration Type Documentation
ZappingMode
enum v8::internal::anonymous_namespace{sweeper.cc}::ZappingMode [strong]
Enumerator
kNone
kCreateFillers
kCreateFillersAndZap
Definition at line 607 of file sweeper.cc.
{ kNone, kCreateFillers, kCreateFillersAndZap };
Function Documentation
AtomicZapBlock()
void v8::internal::anonymous_namespace{sweeper.cc}::AtomicZapBlock (Address addr, size_t size_in_bytes) [inline]
Definition at line 594 of file sweeper.cc.
                                                                  {
  static_assert(sizeof(Tagged_t) == kTaggedSize);
  static constexpr Tagged_t kZapTagged = static_cast<Tagged_t>(kZapValue);
  DCHECK(IsAligned(addr, kTaggedSize));
  DCHECK(IsAligned(size_in_bytes, kTaggedSize));
  const size_t size_in_tagged = size_in_bytes / kTaggedSize;
  Tagged_t* current_addr = reinterpret_cast<Tagged_t*>(addr);
  for (size_t i = 0; i < size_in_tagged; ++i) {
    base::AsAtomicPtr(current_addr++)
        ->store(kZapTagged, std::memory_order_relaxed);
  }
}
References v8::base::AsAtomicPtr(), v8::internal::DCHECK(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, IsAligned(), v8::internal::kTaggedSize, and v8::internal::kZapValue.
Referenced by v8::internal::Sweeper::FreeAndProcessFreedMemory(), and ZapDeadObjectsInRange().
ClearPromotedPages()
void v8::internal::anonymous_namespace{sweeper.cc}::ClearPromotedPages (Heap * heap, std::vector< MutablePageMetadata * > pages)
Definition at line 795 of file sweeper.cc.
                                                                           {
  DCHECK(v8_flags.minor_ms);
  for (auto* page : pages) {
    DCHECK(!page->SweepingDone());
    DCHECK_EQ(PageMetadata::ConcurrentSweepingState::kPendingIteration,
              page->concurrent_sweeping_state());
    if (!page->Chunk()->IsLargePage()) {
      ZapDeadObjectsOnPage(heap, static_cast<PageMetadata*>(page));
    }
    page->ClearLiveness();
    page->set_concurrent_sweeping_state(
        PageMetadata::ConcurrentSweepingState::kDone);
  }
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::MutablePageMetadata::kDone, v8::internal::MutablePageMetadata::kPendingIteration, v8::internal::v8_flags, and ZapDeadObjectsOnPage().
Referenced by v8::internal::Sweeper::StartMinorSweeperTasks().
ComparePagesForSweepingOrder()
bool v8::internal::anonymous_namespace{sweeper.cc}::ComparePagesForSweepingOrder (const PageMetadata * a, const PageMetadata * b) [inline]
Definition at line 705 of file sweeper.cc.
                                                                   {
  // Prioritize pages that can be allocated on.
  if (a->Chunk()->IsFlagSet(MemoryChunk::NEVER_ALLOCATE_ON_PAGE) !=
      b->Chunk()->IsFlagSet(MemoryChunk::NEVER_ALLOCATE_ON_PAGE))
    return a->Chunk()->IsFlagSet(MemoryChunk::NEVER_ALLOCATE_ON_PAGE);
  // We sort in descending order of live bytes, i.e., ascending order of
  // free bytes, because GetSweepingPageSafe returns pages in reverse order.
  // This works automatically for black allocated pages, since we set live bytes
  // for them to the area size.
  return a->live_bytes() > b->live_bytes();
}
References v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::MemoryChunk::IsFlagSet(), v8::internal::MutablePageMetadata::live_bytes(), and v8::internal::MemoryChunk::NEVER_ALLOCATE_ON_PAGE.
Referenced by v8::internal::Sweeper::StartMajorSweeping(), and v8::internal::Sweeper::StartMinorSweeping().
ShouldUpdateRememberedSets()
bool v8::internal::anonymous_namespace{sweeper.cc}::ShouldUpdateRememberedSets (Heap * heap)
Definition at line 748 of file sweeper.cc.
                                            {
  DCHECK_EQ(0, heap->new_lo_space()->Size());
  if (v8_flags.sticky_mark_bits) {
    // TODO(333906585): Update OLD_TO_SHARED remembered set for promoted
    // objects.
    return false;
  }
  if (heap->new_space()->Size() > 0) {
    // Keep track of OLD_TO_NEW slots
    return true;
  }
  // TODO(v8:12612): OLD_TO_SHARED is not really needed on the main isolate and
  // this condition should only apply to client isolates.
  if (heap->isolate()->has_shared_space()) {
    // Keep track of OLD_TO_SHARED slots
    return true;
  }
  return false;
}
References DCHECK_EQ, and v8::internal::v8_flags.
Referenced by v8::internal::Sweeper::StartMinorSweeperTasks().
ShouldZapDeadObjectsOnPage()
ZappingMode v8::internal::anonymous_namespace{sweeper.cc}::ShouldZapDeadObjectsOnPage ()
Definition at line 608 of file sweeper.cc.
                                         {
  if (heap::ShouldZapGarbage() || v8_flags.track_gc_object_stats) {
    // We need to zap and create fillers on promoted pages when
    // --track-gc-object-stats is enabled because it expects all dead objects to
    // still be valid objects. Dead object on promoted pages may otherwise
    // contain invalid old-to-new references to pages that are gone or were
    // already reallocated.
    return ZappingMode::kCreateFillersAndZap;
  }
  // Conservative stack scanning requires fillers over all dead objects
  // otherwise a false reference found on stack may result in resurrecting a
  // dead object.
  return v8_flags.conservative_stack_scanning ? ZappingMode::kCreateFillers
                                              : ZappingMode::kNone;
}
References v8::internal::heap::ShouldZapGarbage(), and v8::internal::v8_flags.
Referenced by v8::internal::Sweeper::LocalSweeper::ParallelIteratePromotedPage(), and ZapDeadObjectsOnPage().
VerifyPreparedPage()
void v8::internal::anonymous_namespace{sweeper.cc}::VerifyPreparedPage (PageMetadata * page)
Definition at line 1444 of file sweeper.cc.
                                            {
#ifdef DEBUG
  DCHECK_GE(page->area_size(), static_cast<size_t>(page->live_bytes()));
  DCHECK_EQ(PageMetadata::ConcurrentSweepingState::kDone,
            page->concurrent_sweeping_state());
  page->ForAllFreeListCategories([page](FreeListCategory* category) {
    DCHECK(!category->is_linked(page->owner()->free_list()));
  });
#endif // DEBUG
}
References v8::internal::MemoryChunkMetadata::area_size(), v8::internal::MutablePageMetadata::concurrent_sweeping_state(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GE, v8::internal::PageMetadata::ForAllFreeListCategories(), v8::internal::Space::free_list(), v8::internal::FreeListCategory::is_linked(), v8::internal::MutablePageMetadata::kDone, v8::internal::MutablePageMetadata::live_bytes(), and v8::internal::MutablePageMetadata::owner().
Referenced by v8::internal::Sweeper::PrepareToBeIteratedPromotedPage(), and v8::internal::Sweeper::PrepareToBeSweptPage().
ZapDeadObjectsInRange()
void v8::internal::anonymous_namespace{sweeper.cc}::ZapDeadObjectsInRange (Heap * heap, Address dead_start, Address dead_end, const ZappingMode zapping_mode)
Definition at line 624 of file sweeper.cc.
                                                           {
  DCHECK_NE(ZappingMode::kNone, zapping_mode);
  if (dead_end != dead_start) {
    size_t free_size = static_cast<size_t>(dead_end - dead_start);
    if (zapping_mode == ZappingMode::kCreateFillersAndZap) {
      AtomicZapBlock(dead_start, free_size);
    }
    WritableFreeSpace free_space =
        WritableFreeSpace::ForNonExecutableMemory(dead_start, free_size);
    heap->CreateFillerObjectAtBackground(free_space);
  }
}
References AtomicZapBlock(), DCHECK_NE, and v8::internal::WritableFreeSpace::ForNonExecutableMemory().
Referenced by v8::internal::Sweeper::LocalSweeper::ParallelIteratePromotedPage(), and ZapDeadObjectsOnPage().
ZapDeadObjectsOnPage()
void v8::internal::anonymous_namespace{sweeper.cc}::ZapDeadObjectsOnPage (Heap * heap, PageMetadata * p)
Definition at line 780 of file sweeper.cc.
                                                       {
  const ZappingMode zapping_mode = ShouldZapDeadObjectsOnPage();
  if (zapping_mode == ZappingMode::kNone) {
    return;
  }
  Address dead_start = p->area_start();
  // Iterate over the page using the live objects.
  for (auto [object, size] : LiveObjectRange(p)) {
    Address dead_end = object.address();
    ZapDeadObjectsInRange(heap, dead_start, dead_end, zapping_mode);
    dead_start = dead_end + size;
  }
  ZapDeadObjectsInRange(heap, dead_start, p->area_end(), zapping_mode);
}
References v8::internal::MemoryChunkMetadata::area_end(), v8::internal::MemoryChunkMetadata::area_start(), ShouldZapDeadObjectsOnPage(), size(), and ZapDeadObjectsInRange().
Referenced by ClearPromotedPages().