v8::base::debug::anonymous_namespace{stack_trace_posix.cc} Namespace Reference
Classes
class BacktraceOutputHandler
class PrintBacktraceOutputHandler
class StreamBacktraceOutputHandler
Functions
void PrintToStderr (const char *output)
void StackDumpSignalHandler (int signal, siginfo_t *info, void *void_context)
void WarmUpBacktrace ()
Variables
volatile sig_atomic_t in_signal_handler = 0
bool dump_stack_in_signal_handler = true
const char kMangledSymbolPrefix [] = `_Z`
const char kSymbolCharacters []
Function Documentation
PrintToStderr()
void v8::base::debug::anonymous_namespace{stack_trace_posix.cc}::PrintToStderr (const char * output)
Definition at line 194 of file stack_trace_posix.cc.
                                       {
  // NOTE: This code MUST be async-signal safe (it's used by in-process
  // stack dumping signal handler). NO malloc or stdio is allowed here.
  ssize_t return_val = write(STDERR_FILENO, output, strlen(output));
  USE(return_val);
}
References USE.
Referenced by v8::base::debug::anonymous_namespace{stack_trace_posix.cc}::PrintBacktraceOutputHandler::HandleOutput(), and StackDumpSignalHandler().
StackDumpSignalHandler()
void v8::base::debug::anonymous_namespace{stack_trace_posix.cc}::StackDumpSignalHandler (int signal, siginfo_t * info, void * void_context)
Definition at line 201 of file stack_trace_posix.cc.
                                                                             {
  // NOTE: This code MUST be async-signal safe.
  // NO malloc or stdio is allowed here.
  // Record the fact that we are in the signal handler now, so that the rest
  // of StackTrace can behave in an async-signal-safe manner.
  in_signal_handler = 1;
#if V8_HAS_PKU_SUPPORT
  MemoryProtectionKey::SetDefaultPermissionsForAllKeysInSignalHandler();
#endif
  PrintToStderr("Received signal ");
  char buf[1024] = {0};
  internal::itoa_r(signal, buf, sizeof(buf), 10, 0);
  PrintToStderr(buf);
  if (signal == SIGBUS) {
    if (info->si_code == BUS_ADRALN)
      PrintToStderr(" BUS_ADRALN ");
    else if (info->si_code == BUS_ADRERR)
      PrintToStderr(" BUS_ADRERR ");
    else if (info->si_code == BUS_OBJERR)
      PrintToStderr(" BUS_OBJERR ");
    else
      PrintToStderr(" <unknown> ");
  } else if (signal == SIGFPE) {
    if (info->si_code == FPE_FLTDIV)
      PrintToStderr(" FPE_FLTDIV ");
    else if (info->si_code == FPE_FLTINV)
      PrintToStderr(" FPE_FLTINV ");
    else if (info->si_code == FPE_FLTOVF)
      PrintToStderr(" FPE_FLTOVF ");
    else if (info->si_code == FPE_FLTRES)
      PrintToStderr(" FPE_FLTRES ");
    else if (info->si_code == FPE_FLTSUB)
      PrintToStderr(" FPE_FLTSUB ");
    else if (info->si_code == FPE_FLTUND)
      PrintToStderr(" FPE_FLTUND ");
    else if (info->si_code == FPE_INTDIV)
      PrintToStderr(" FPE_INTDIV ");
    else if (info->si_code == FPE_INTOVF)
      PrintToStderr(" FPE_INTOVF ");
    else
      PrintToStderr(" <unknown> ");
  } else if (signal == SIGILL) {
    if (info->si_code == ILL_BADSTK)
      PrintToStderr(" ILL_BADSTK ");
    else if (info->si_code == ILL_COPROC)
      PrintToStderr(" ILL_COPROC ");
    else if (info->si_code == ILL_ILLOPN)
      PrintToStderr(" ILL_ILLOPN ");
    else if (info->si_code == ILL_ILLADR)
      PrintToStderr(" ILL_ILLADR ");
    else if (info->si_code == ILL_ILLTRP)
      PrintToStderr(" ILL_ILLTRP ");
    else if (info->si_code == ILL_PRVOPC)
      PrintToStderr(" ILL_PRVOPC ");
    else if (info->si_code == ILL_PRVREG)
      PrintToStderr(" ILL_PRVREG ");
    else
      PrintToStderr(" <unknown> ");
  } else if (signal == SIGSEGV) {
    if (info->si_code == SEGV_MAPERR)
      PrintToStderr(" SEGV_MAPERR ");
    else if (info->si_code == SEGV_ACCERR)
      PrintToStderr(" SEGV_ACCERR ");
    else
      PrintToStderr(" <unknown> ");
  }
  if (signal == SIGBUS || signal == SIGFPE || signal == SIGILL ||
      signal == SIGSEGV) {
    internal::itoa_r(reinterpret_cast<intptr_t>(info->si_addr), buf,
                     sizeof(buf), 16, 12);
    PrintToStderr(buf);
  }
  PrintToStderr("\n");
  if (dump_stack_in_signal_handler) {
    debug::StackTrace().Print();
    PrintToStderr("[end of stack trace]\n");
  }
  if (::signal(signal, SIG_DFL) == SIG_ERR) _exit(1);
}
References dump_stack_in_signal_handler, in_signal_handler, v8::base::debug::internal::itoa_r(), v8::base::debug::StackTrace::Print(), and PrintToStderr().
WarmUpBacktrace()
void v8::base::debug::anonymous_namespace{stack_trace_posix.cc}::WarmUpBacktrace ()
Definition at line 314 of file stack_trace_posix.cc.
                       {
  // Warm up stack trace infrastructure. It turns out that on the first
  // call glibc initializes some internal data structures using pthread_once,
  // and even backtrace() can call malloc(), leading to hangs.
  //
  // Example stack trace snippet (with tcmalloc):
  //
  // #8 0x0000000000a173b5 in tc_malloc
  // at ./third_party/tcmalloc/chromium/src/debugallocation.cc:1161
  // #9 0x00007ffff7de7900 in _dl_map_object_deps at dl-deps.c:517
  // #10 0x00007ffff7ded8a9 in dl_open_worker at dl-open.c:262
  // #11 0x00007ffff7de9176 in _dl_catch_error at dl-error.c:178
  // #12 0x00007ffff7ded31a in _dl_open (file=0x7ffff625e298 "libgcc_s.so.1")
  // at dl-open.c:639
  // #13 0x00007ffff6215602 in do_dlopen at dl-libc.c:89
  // #14 0x00007ffff7de9176 in _dl_catch_error at dl-error.c:178
  // #15 0x00007ffff62156c4 in dlerror_run at dl-libc.c:48
  // #16 __GI___libc_dlopen_mode at dl-libc.c:165
  // #17 0x00007ffff61ef8f5 in init
  // at ../sysdeps/x86_64/../ia64/backtrace.c:53
  // #18 0x00007ffff6aad400 in pthread_once
  // at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_once.S:104
  // #19 0x00007ffff61efa14 in __GI___backtrace
  // at ../sysdeps/x86_64/../ia64/backtrace.c:104
  // #20 0x0000000000752a54 in base::debug::StackTrace::StackTrace
  // at base/debug/stack_trace_posix.cc:175
  // #21 0x00000000007a4ae5 in
  // base::(anonymous namespace)::StackDumpSignalHandler
  // at base/process_util_posix.cc:172
  // #22 <signal handler called>
  StackTrace stack_trace;
}
Variable Documentation
dump_stack_in_signal_handler
bool v8::base::debug::anonymous_namespace{stack_trace_posix.cc}::dump_stack_in_signal_handler = true
Definition at line 65 of file stack_trace_posix.cc.
Referenced by StackDumpSignalHandler().
in_signal_handler
volatile sig_atomic_t v8::base::debug::anonymous_namespace{stack_trace_posix.cc}::in_signal_handler = 0
Definition at line 64 of file stack_trace_posix.cc.
Referenced by StackDumpSignalHandler().
kMangledSymbolPrefix
const char v8::base::debug::anonymous_namespace{stack_trace_posix.cc}::kMangledSymbolPrefix[] = `_Z`
Definition at line 69 of file stack_trace_posix.cc.
kSymbolCharacters
const char v8::base::debug::anonymous_namespace{stack_trace_posix.cc}::kSymbolCharacters[]
Initial value:
=
    "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_"
Definition at line 73 of file stack_trace_posix.cc.