v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc} Namespace Reference
Functions
void VisitRR (InstructionSelector *selector, InstructionCode opcode, OpIndex node)
void VisitRRR (InstructionSelector *selector, InstructionCode opcode, OpIndex node)
void VisitRRO (InstructionSelector *selector, InstructionCode opcode, OpIndex node, ImmediateMode operand_mode)
void VisitTryTruncateDouble (InstructionSelector *selector, InstructionCode opcode, OpIndex node)
void VisitBinop (InstructionSelector *selector, OpIndex node, InstructionCode opcode, ImmediateMode operand_mode, FlagsContinuation *cont)
void VisitBinop (InstructionSelector *selector, OpIndex node, InstructionCode opcode, ImmediateMode operand_mode)
void VisitCompare (InstructionSelector *selector, InstructionCode opcode, InstructionOperand left, InstructionOperand right, FlagsContinuation *cont)
void EmitInt32MulWithOverflow (InstructionSelector *selector, OpIndex node, FlagsContinuation *cont)
void EmitInt64MulWithOverflow (InstructionSelector *selector, OpIndex node, FlagsContinuation *cont)
void VisitWordCompare (InstructionSelector *selector, OpIndex node, InstructionCode opcode, FlagsContinuation *cont, bool commutative, ImmediateMode immediate_mode)
void VisitWord32Compare (InstructionSelector *selector, OpIndex node, FlagsContinuation *cont)
void VisitWord64Compare (InstructionSelector *selector, OpIndex node, FlagsContinuation *cont)
void VisitFloat32Compare (InstructionSelector *selector, OpIndex node, FlagsContinuation *cont)
void VisitFloat64Compare (InstructionSelector *selector, OpIndex node, FlagsContinuation *cont)
Function Documentation
EmitInt32MulWithOverflow()
void v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::EmitInt32MulWithOverflow (InstructionSelector * selector, OpIndex node, FlagsContinuation * cont)
Definition at line 1157 of file instruction-selector-ppc.cc.
                                                       {
  PPCOperandGenerator g(selector);
  const OverflowCheckedBinopOp& op =
      selector->Get(node).Cast<OverflowCheckedBinopOp>();
  OpIndex lhs = op.input(0);
  OpIndex rhs = op.input(1);
  InstructionOperand result_operand = g.DefineAsRegister(node);
  InstructionOperand high32_operand = g.TempRegister();
  InstructionOperand temp_operand = g.TempRegister();
  {
    InstructionOperand outputs[] = {result_operand, high32_operand};
    InstructionOperand inputs[] = {g.UseRegister(lhs), g.UseRegister(rhs)};
    selector->Emit(kPPC_Mul32WithHigh32, 2, outputs, 2, inputs);
  }
  {
    InstructionOperand shift_31 = g.UseImmediate(31);
    InstructionOperand outputs[] = {temp_operand};
    InstructionOperand inputs[] = {result_operand, shift_31};
    selector->Emit(kPPC_ShiftRightAlg32, 1, outputs, 2, inputs);
  }
  VisitCompare(selector, kPPC_Cmp32, high32_operand, temp_operand, cont);
}
References v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::InstructionSelector::Emit(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::OperationT< Derived >::input(), v8::internal::compiler::OperandGenerator::TempRegister(), v8::internal::compiler::OperandGenerator::UseImmediate(), v8::internal::compiler::OperandGenerator::UseRegister(), and v8::internal::compiler::VisitCompare().
EmitInt64MulWithOverflow()
void v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::EmitInt64MulWithOverflow (InstructionSelector * selector, OpIndex node, FlagsContinuation * cont)
Definition at line 1182 of file instruction-selector-ppc.cc.
                                                       {
  PPCOperandGenerator g(selector);
  const OverflowCheckedBinopOp& op =
      selector->Cast<OverflowCheckedBinopOp>(node);
  OpIndex lhs = op.input(0);
  OpIndex rhs = op.input(1);
  InstructionOperand result = g.DefineAsRegister(node);
  InstructionOperand left = g.UseRegister(lhs);
  InstructionOperand high = g.TempRegister();
  InstructionOperand result_sign = g.TempRegister();
  InstructionOperand right = g.UseRegister(rhs);
  selector->Emit(kPPC_Mul64, result, left, right);
  selector->Emit(kPPC_MulHighS64, high, left, right);
  selector->Emit(kPPC_ShiftRightAlg64, result_sign, result,
                 g.TempImmediate(63));
  // Test whether {high} is a sign-extension of {result}.
  selector->EmitWithContinuation(kPPC_Cmp64, high, result_sign, cont);
}
References v8::internal::compiler::turboshaft::OperationMatcher::Cast(), v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::InstructionSelector::Emit(), v8::internal::compiler::InstructionSelector::EmitWithContinuation(), v8::internal::compiler::turboshaft::OperationT< Derived >::input(), v8::base::internal::result, v8::internal::compiler::OperandGenerator::TempImmediate(), v8::internal::compiler::OperandGenerator::TempRegister(), and v8::internal::compiler::OperandGenerator::UseRegister().
VisitBinop() [1/2]
void v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitBinop (InstructionSelector * selector, OpIndex node, InstructionCode opcode, ImmediateMode operand_mode)
Definition at line 169 of file instruction-selector-ppc.cc.
                                                                    {
  FlagsContinuation cont;
  VisitBinop(selector, node, opcode, operand_mode, &cont);
}
References v8::internal::compiler::VisitBinop().
VisitBinop() [2/2]
void v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitBinop (InstructionSelector * selector, OpIndex node, InstructionCode opcode, ImmediateMode operand_mode, FlagsContinuation * cont)
Definition at line 137 of file instruction-selector-ppc.cc.
                                         {
  PPCOperandGenerator g(selector);
  const Operation& op = selector->Get(node);
  InstructionOperand inputs[4];
  size_t input_count = 0;
  InstructionOperand outputs[2];
  size_t output_count = 0;
  inputs[input_count++] = g.UseRegister(op.input(0));
  inputs[input_count++] = g.UseOperand(op.input(1), operand_mode);
  if (cont->IsDeoptimize()) {
    // If we can deoptimize as a result of the binop, we need to make sure that
    // the deopt inputs are not overwritten by the binop result. One way
    // to achieve that is to declare the output register as same-as-first.
    outputs[output_count++] = g.DefineSameAsFirst(node);
  } else {
    outputs[output_count++] = g.DefineAsRegister(node);
  }
  DCHECK_NE(0u, input_count);
  DCHECK_NE(0u, output_count);
  DCHECK_GE(arraysize(inputs), input_count);
  DCHECK_GE(arraysize(outputs), output_count);
  selector->EmitWithContinuation(opcode, output_count, outputs, input_count,
                                 inputs, cont);
}
References arraysize, DCHECK_GE, DCHECK_NE, v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::OperandGenerator::DefineSameAsFirst(), v8::internal::compiler::InstructionSelector::EmitWithContinuation(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::FlagsContinuation::IsDeoptimize(), v8::internal::compiler::PPCOperandGenerator::UseOperand(), and v8::internal::compiler::OperandGenerator::UseRegister().
VisitCompare()
void v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitCompare (InstructionSelector * selector, InstructionCode opcode, InstructionOperand left, InstructionOperand right, FlagsContinuation * cont)
Definition at line 1666 of file instruction-selector-ppc.cc.
                                           {
  selector->EmitWithContinuation(opcode, left, right, cont);
}
References v8::internal::compiler::InstructionSelector::EmitWithContinuation().
VisitFloat32Compare()
void v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitFloat32Compare (InstructionSelector * selector, OpIndex node, FlagsContinuation * cont)
Definition at line 1708 of file instruction-selector-ppc.cc.
                                                  {
  PPCOperandGenerator g(selector);
  const Operation& op = selector->Get(node);
  OpIndex lhs = op.input(0);
  OpIndex rhs = op.input(1);
  VisitCompare(selector, kPPC_CmpDouble, g.UseRegister(lhs), g.UseRegister(rhs),
               cont);
}
References v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::OperandGenerator::UseRegister(), and v8::internal::compiler::VisitCompare().
VisitFloat64Compare()
void v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitFloat64Compare (InstructionSelector * selector, OpIndex node, FlagsContinuation * cont)
Definition at line 1719 of file instruction-selector-ppc.cc.
                                                  {
  PPCOperandGenerator g(selector);
  const Operation& op = selector->Get(node);
  OpIndex lhs = op.input(0);
  OpIndex rhs = op.input(1);
  VisitCompare(selector, kPPC_CmpDouble, g.UseRegister(lhs), g.UseRegister(rhs),
               cont);
}
References v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::OperandGenerator::UseRegister(), and v8::internal::compiler::VisitCompare().
VisitRR()
void v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitRR (InstructionSelector * selector, InstructionCode opcode, OpIndex node)
Definition at line 94 of file instruction-selector-ppc.cc.
                           {
  PPCOperandGenerator g(selector);
  const Operation& op = selector->Get(node);
  DCHECK_EQ(op.input_count, 1);
  selector->Emit(opcode, g.DefineAsRegister(node), g.UseRegister(op.input(0)));
}
References DCHECK_EQ, v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::InstructionSelector::Emit(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::turboshaft::Operation::input_count, and v8::internal::compiler::OperandGenerator::UseRegister().
VisitRRO()
void v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitRRO (InstructionSelector * selector, InstructionCode opcode, OpIndex node, ImmediateMode operand_mode)
Definition at line 111 of file instruction-selector-ppc.cc.
                                                        {
  PPCOperandGenerator g(selector);
  const Operation& op = selector->Get(node);
  selector->Emit(opcode, g.DefineAsRegister(node), g.UseRegister(op.input(0)),
                 g.UseOperand(op.input(1), operand_mode));
}
References v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::InstructionSelector::Emit(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::PPCOperandGenerator::UseOperand(), and v8::internal::compiler::OperandGenerator::UseRegister().
VisitRRR()
void v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitRRR (InstructionSelector * selector, InstructionCode opcode, OpIndex node)
Definition at line 102 of file instruction-selector-ppc.cc.
                            {
  PPCOperandGenerator g(selector);
  const Operation& op = selector->Get(node);
  DCHECK_EQ(op.input_count, 2);
  selector->Emit(opcode, g.DefineAsRegister(node), g.UseRegister(op.input(0)),
                 g.UseRegister(op.input(1)));
}
References DCHECK_EQ, v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::InstructionSelector::Emit(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::turboshaft::Operation::input_count, and v8::internal::compiler::OperandGenerator::UseRegister().
VisitTryTruncateDouble()
void v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitTryTruncateDouble (InstructionSelector * selector, InstructionCode opcode, OpIndex node)
Definition at line 119 of file instruction-selector-ppc.cc.
                                                                  {
  PPCOperandGenerator g(selector);
  const Operation& op = selector->Get(node);
  InstructionOperand inputs[] = {g.UseRegister(op.input(0))};
  InstructionOperand outputs[2];
  size_t output_count = 0;
  outputs[output_count++] = g.DefineAsRegister(node);
  OptionalOpIndex success_output = selector->FindProjection(node, 1);
  if (success_output.valid()) {
    outputs[output_count++] = g.DefineAsRegister(success_output.value());
  }
  selector->Emit(opcode, output_count, outputs, 1, inputs);
}
References v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::InstructionSelector::Emit(), v8::internal::compiler::InstructionSelector::FindProjection(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::OperandGenerator::UseRegister(), v8::internal::compiler::turboshaft::OptionalOpIndex::valid(), and v8::internal::compiler::turboshaft::OptionalOpIndex::value().
VisitWord32Compare()
void v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitWord32Compare (InstructionSelector * selector, OpIndex node, FlagsContinuation * cont)
Definition at line 1695 of file instruction-selector-ppc.cc.
                                                 {
  ImmediateMode mode = (CompareLogical(cont) ? kInt16Imm_Unsigned : kInt16Imm);
  VisitWordCompare(selector, node, kPPC_Cmp32, cont, false, mode);
}
References v8::internal::compiler::CompareLogical(), v8::internal::compiler::kInt16Imm, v8::internal::compiler::kInt16Imm_Unsigned, mode(), and v8::internal::compiler::VisitWordCompare().
VisitWord64Compare()
void v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitWord64Compare (InstructionSelector * selector, OpIndex node, FlagsContinuation * cont)
Definition at line 1701 of file instruction-selector-ppc.cc.
                                                 {
  ImmediateMode mode = (CompareLogical(cont) ? kInt16Imm_Unsigned : kInt16Imm);
  VisitWordCompare(selector, node, kPPC_Cmp64, cont, false, mode);
}
References v8::internal::compiler::CompareLogical(), v8::internal::compiler::kInt16Imm, v8::internal::compiler::kInt16Imm_Unsigned, mode(), and v8::internal::compiler::VisitWordCompare().
VisitWordCompare()
void v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitWordCompare (InstructionSelector * selector, OpIndex node, InstructionCode opcode, FlagsContinuation * cont, bool commutative, ImmediateMode immediate_mode)
Definition at line 1673 of file instruction-selector-ppc.cc.
                                                                      {
  PPCOperandGenerator g(selector);
  const Operation& op = selector->Get(node);
  OpIndex lhs = op.input(0);
  OpIndex rhs = op.input(1);
  // Match immediates on left or right side of comparison.
  if (g.CanBeImmediate(rhs, immediate_mode)) {
    VisitCompare(selector, opcode, g.UseRegister(lhs), g.UseImmediate(rhs),
                 cont);
  } else if (g.CanBeImmediate(lhs, immediate_mode)) {
    if (!commutative) cont->Commute();
    VisitCompare(selector, opcode, g.UseRegister(rhs), g.UseImmediate(lhs),
                 cont);
  } else {
    VisitCompare(selector, opcode, g.UseRegister(lhs), g.UseRegister(rhs),
                 cont);
  }
}
References v8::internal::compiler::PPCOperandGenerator::CanBeImmediate(), v8::internal::compiler::FlagsContinuation::Commute(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::OperandGenerator::UseImmediate(), v8::internal::compiler::OperandGenerator::UseRegister(), and v8::internal::compiler::VisitCompare().