v8::internal::anonymous_namespace{asm-js.cc} Namespace Reference
Functions
DirectHandle< Object > StdlibMathMember (Isolate *isolate, DirectHandle< JSReceiver > stdlib, DirectHandle< Name > name)
bool AreStdlibMembersValid (Isolate *isolate, DirectHandle< JSReceiver > stdlib, wasm::AsmJsParser::StdlibSet members, bool *is_typed_array)
void Report (Handle< Script > script, int position, base::Vector< const char > text, MessageTemplate message_template, v8::Isolate::MessageErrorLevel level)
void ReportCompilationSuccess (Handle< Script > script, int position, double compile_time, size_t module_size)
void ReportCompilationFailure (ParseInfo *parse_info, int position, const char *reason)
void ReportInstantiationSuccess (Handle< Script > script, int position, double instantiate_time)
void ReportInstantiationFailure (Handle< Script > script, int position, const char *reason)
bool IsValidAsmjsMemorySize (size_t size)
Function Documentation
AreStdlibMembersValid()
bool v8::internal::anonymous_namespace{asm-js.cc}::AreStdlibMembersValid (Isolate * isolate, DirectHandle< JSReceiver > stdlib, wasm::AsmJsParser::StdlibSet members, bool * is_typed_array)
Definition at line 54 of file asm-js.cc.
                                                 {
  if (members.contains(wasm::AsmJsParser::StandardMember::kInfinity)) {
    members.Remove(wasm::AsmJsParser::StandardMember::kInfinity);
    DirectHandle<Name> name = isolate->factory()->Infinity_string();
    DirectHandle<Object> value =
        JSReceiver::GetDataProperty(isolate, stdlib, name);
    if (!IsNumber(*value) || !std::isinf(Object::NumberValue(*value)))
      return false;
  }
  if (members.contains(wasm::AsmJsParser::StandardMember::kNaN)) {
    members.Remove(wasm::AsmJsParser::StandardMember::kNaN);
    DirectHandle<Name> name = isolate->factory()->NaN_string();
    DirectHandle<Object> value =
        JSReceiver::GetDataProperty(isolate, stdlib, name);
    if (!IsNaN(*value)) return false;
  }
#define STDLIB_MATH_FUNC(fname, FName, ignore1, ignore2) \
  if (members.contains(wasm::AsmJsParser::StandardMember::kMath##FName)) { \
    members.Remove(wasm::AsmJsParser::StandardMember::kMath##FName); \
    DirectHandle<Name> name(isolate->factory()->InternalizeString(\
        base::StaticCharVector(#fname))); \
    DirectHandle<Object> value = StdlibMathMember(isolate, stdlib, name); \
    if (!IsJSFunction(*value)) return false; \
    Tagged<SharedFunctionInfo> shared = Cast<JSFunction>(value)->shared(); \
    if (!shared->HasBuiltinId() || \
        shared->builtin_id() != Builtin::kMath##FName) { \
      return false; \
    } \
    DCHECK_EQ(shared->GetCode(isolate), \
              isolate->builtins()->code(Builtin::kMath##FName)); \
  }
  STDLIB_MATH_FUNCTION_LIST(STDLIB_MATH_FUNC)
#undef STDLIB_MATH_FUNC
#define STDLIB_MATH_CONST(cname, const_value) \
  if (members.contains(wasm::AsmJsParser::StandardMember::kMath##cname)) { \
    members.Remove(wasm::AsmJsParser::StandardMember::kMath##cname); \
    DirectHandle<Name> name(isolate->factory()->InternalizeString(\
        base::StaticCharVector(#cname))); \
    DirectHandle<Object> value = StdlibMathMember(isolate, stdlib, name); \
    if (!IsNumber(*value) || Object::NumberValue(*value) != const_value) \
      return false; \
  }
  STDLIB_MATH_VALUE_LIST(STDLIB_MATH_CONST)
#undef STDLIB_MATH_CONST
#define STDLIB_ARRAY_TYPE(fname, FName) \
  if (members.contains(wasm::AsmJsParser::StandardMember::k##FName)) { \
    members.Remove(wasm::AsmJsParser::StandardMember::k##FName); \
    *is_typed_array = true; \
    DirectHandle<Name> name(isolate->factory()->InternalizeString(\
        base::StaticCharVector(#FName))); \
    DirectHandle<Object> value = \
        JSReceiver::GetDataProperty(isolate, stdlib, name); \
    if (!IsJSFunction(*value)) return false; \
    DirectHandle<JSFunction> func = Cast<JSFunction>(value); \
    if (!func.is_identical_to(isolate->fname())) return false; \
  }
  STDLIB_ARRAY_TYPE(int8_array_fun, Int8Array)
  STDLIB_ARRAY_TYPE(uint8_array_fun, Uint8Array)
  STDLIB_ARRAY_TYPE(int16_array_fun, Int16Array)
  STDLIB_ARRAY_TYPE(uint16_array_fun, Uint16Array)
  STDLIB_ARRAY_TYPE(int32_array_fun, Int32Array)
  STDLIB_ARRAY_TYPE(uint32_array_fun, Uint32Array)
  STDLIB_ARRAY_TYPE(float32_array_fun, Float32Array)
  STDLIB_ARRAY_TYPE(float64_array_fun, Float64Array)
#undef STDLIB_ARRAY_TYPE
  // All members accounted for.
  DCHECK(members.empty());
  return true;
}
References v8::base::EnumSet< E, T >::contains(), v8::internal::DCHECK(), v8::base::EnumSet< E, T >::empty(), v8::internal::Isolate::factory(), v8::internal::JSReceiver::GetDataProperty(), v8::internal::IsNaN(), v8::internal::IsNumber(), v8::internal::name, v8::internal::Object::NumberValue(), v8::base::EnumSet< E, T >::Remove(), STDLIB_ARRAY_TYPE, STDLIB_MATH_CONST, STDLIB_MATH_FUNC, STDLIB_MATH_FUNCTION_LIST, STDLIB_MATH_VALUE_LIST, and v8::internal::value.
Referenced by v8::internal::AsmJs::InstantiateAsmWasm().
IsValidAsmjsMemorySize()
bool v8::internal::anonymous_namespace{asm-js.cc}::IsValidAsmjsMemorySize (size_t size) [inline]
Definition at line 312 of file asm-js.cc.
                                                {
  // Enforce asm.js spec minimum size.
  if (size < (1u << 12u)) return false;
  // Enforce engine-limited and flag-limited maximum allocation size.
  if (size > wasm::max_mem32_bytes()) return false;
  // Enforce power-of-2 sizes for 2^12 - 2^24.
  if (size < (1u << 24u)) {
    uint32_t size32 = static_cast<uint32_t>(size);
    return base::bits::IsPowerOfTwo(size32);
  }
  // Enforce multiple of 2^24 for sizes >= 2^24
  if ((size % (1u << 24u)) != 0) return false;
  // Limitation of our implementation: for performance reasons, we use unsigned
  // uint32-to-uintptr extensions for memory addresses, which would give
  // incorrect behavior for memories larger than 2 GiB.
  // Note that this does not affect Chrome, which does not allow allocating
  // larger ArrayBuffers anyway.
  if (size > 0x8000'0000u) return false;
  // All checks passed!
  return true;
}
References v8::base::bits::IsPowerOfTwo(), v8::internal::wasm::max_mem32_bytes(), and size().
Referenced by v8::internal::AsmJs::InstantiateAsmWasm().
Report()
void v8::internal::anonymous_namespace{asm-js.cc}::Report (Handle< Script > script, int position, base::Vector< const char > text, MessageTemplate message_template, v8::Isolate::MessageErrorLevel level)
Definition at line 126 of file asm-js.cc.
                                              {
  Isolate* isolate = Isolate::Current();
  MessageLocation location(script, position, position);
  DirectHandle<String> text_object =
      isolate->factory()->InternalizeUtf8String(text);
  DirectHandle<JSMessageObject> message = MessageHandler::MakeMessageObject(
      isolate, message_template, &location, text_object);
  message->set_error_level(level);
  MessageHandler::ReportMessage(isolate, &location, message);
}
References v8::internal::Isolate::Current(), v8::internal::Isolate::factory(), v8::internal::Factory::InternalizeUtf8String(), v8::internal::MessageHandler::MakeMessageObject(), v8::internal::MessageHandler::ReportMessage(), and v8::internal::script.
Referenced by ReportCompilationSuccess(), ReportInstantiationFailure(), ReportInstantiationSuccess(), and v8::internal::torque::MessageBuilder::~MessageBuilder().
ReportCompilationFailure()
void v8::internal::anonymous_namespace{asm-js.cc}::ReportCompilationFailure (ParseInfo * parse_info, int position, const char * reason)
Definition at line 153 of file asm-js.cc.
                                                  {
  if (v8_flags.suppress_asm_messages) return;
  parse_info->pending_error_handler()->ReportWarningAt(
      position, position, MessageTemplate::kAsmJsInvalid, reason);
}
References v8::internal::ParseInfo::pending_error_handler(), v8::internal::PendingCompilationErrorHandler::ReportWarningAt(), and v8::internal::v8_flags.
Referenced by v8::internal::AsmJsCompilationJob::ExecuteJobImpl().
ReportCompilationSuccess()
void v8::internal::anonymous_namespace{asm-js.cc}::ReportCompilationSuccess (Handle< Script > script, int position, double compile_time, size_t module_size)
Definition at line 140 of file asm-js.cc.
                                                                       {
  if (v8_flags.suppress_asm_messages || !v8_flags.trace_asm_time) return;
  base::EmbeddedVector<char, 100> text;
  int length = SNPrintF(text, "success, compile time %0.3f ms, %zu bytes",
                        compile_time, module_size);
  CHECK_NE(-1, length);
  text.Truncate(length);
  Report(script, position, text, MessageTemplate::kAsmJsCompiled,
         v8::Isolate::kMessageInfo);
}
References CHECK_NE, v8::Isolate::kMessageInfo, v8::internal::length, Report(), v8::internal::script, v8::base::SNPrintF(), v8::base::Vector< T >::Truncate(), and v8::internal::v8_flags.
Referenced by v8::internal::AsmJsCompilationJob::FinalizeJobImpl().
ReportInstantiationFailure()
void v8::internal::anonymous_namespace{asm-js.cc}::ReportInstantiationFailure (Handle< Script > script, int position, const char * reason)
Definition at line 173 of file asm-js.cc.
                                                    {
  if (v8_flags.suppress_asm_messages) return;
  base::Vector<const char> text = base::CStrVector(reason);
  Report(script, position, text, MessageTemplate::kAsmJsLinkingFailed,
         v8::Isolate::kMessageWarning);
}
References v8::base::CStrVector(), v8::Isolate::kMessageWarning, Report(), v8::internal::script, and v8::internal::v8_flags.
Referenced by v8::internal::AsmJs::InstantiateAsmWasm().
ReportInstantiationSuccess()
void v8::internal::anonymous_namespace{asm-js.cc}::ReportInstantiationSuccess (Handle< Script > script, int position, double instantiate_time)
Definition at line 161 of file asm-js.cc.
                                                         {
  if (v8_flags.suppress_asm_messages || !v8_flags.trace_asm_time) return;
  base::EmbeddedVector<char, 50> text;
  int length = SNPrintF(text, "success, %0.3f ms", instantiate_time);
  CHECK_NE(-1, length);
  text.Truncate(length);
  Report(script, position, text, MessageTemplate::kAsmJsInstantiated,
         v8::Isolate::kMessageInfo);
}
References CHECK_NE, v8::Isolate::kMessageInfo, v8::internal::length, Report(), v8::internal::script, v8::base::SNPrintF(), v8::base::Vector< T >::Truncate(), and v8::internal::v8_flags.
Referenced by v8::internal::AsmJs::InstantiateAsmWasm().
StdlibMathMember()
DirectHandle<Object> v8::internal::anonymous_namespace{asm-js.cc}::StdlibMathMember (Isolate * isolate, DirectHandle< JSReceiver > stdlib, DirectHandle< Name > name)
Definition at line 42 of file asm-js.cc.
                                                               {
  DirectHandle<Name> math_name(
      isolate->factory()->InternalizeString(base::StaticCharVector("Math")));
  DirectHandle<Object> math =
      JSReceiver::GetDataProperty(isolate, stdlib, math_name);
  if (!IsJSReceiver(*math)) return isolate->factory()->undefined_value();
  DirectHandle<JSReceiver> math_receiver = Cast<JSReceiver>(math);
  return JSReceiver::GetDataProperty(isolate, math_receiver, name);
}
References v8::internal::Isolate::factory(), v8::internal::JSReceiver::GetDataProperty(), v8::internal::Factory::InternalizeString(), v8::internal::name, and v8::base::StaticCharVector().