v8::internal::compiler::turboshaft::anonymous_namespace{operations.cc} Namespace Reference
Classes
class InputsRepFactoryCheck
Functions
BlockIndex index_for_bound_block (const Block *block)
Function Documentation
index_for_bound_block()
BlockIndex v8::internal::compiler::turboshaft::anonymous_namespace{operations.cc}::index_for_bound_block (const Block * block)
Definition at line 2089 of file operations.cc.
                                                     {
  DCHECK_NOT_NULL(block);
  const BlockIndex index = block->index();
  DCHECK(index.valid());
  return index;
}
References v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::compiler::turboshaft::Block::index(), and v8::internal::index.
Referenced by v8::internal::compiler::turboshaft::CheckExceptionOp::hash_value(), v8::internal::compiler::turboshaft::GotoOp::hash_value(), v8::internal::compiler::turboshaft::BranchOp::hash_value(), and v8::internal::compiler::turboshaft::SwitchOp::hash_value().