v8::internal::anonymous_namespace{serializer-deserializer.cc} Namespace Reference
Functions
DISABLE_CFI_PERF void IterateObjectCache (Isolate *isolate, std::vector< Tagged< Object >> *cache, Root root_id, RootVisitor *visitor)
Function Documentation
IterateObjectCache()
DISABLE_CFI_PERF void v8::internal::anonymous_namespace{serializer-deserializer.cc}::IterateObjectCache (Isolate * isolate, std::vector< Tagged< Object >> * cache, Root root_id, RootVisitor * visitor)
Definition at line 15 of file serializer-deserializer.cc.
                                                            {
  for (size_t i = 0;; ++i) {
    // Extend the array ready to get a value when deserializing.
    if (cache->size() <= i) cache->push_back(Smi::zero());
    // During deserialization, the visitor populates the object cache and
    // eventually terminates the cache with undefined.
    visitor->VisitRootPointer(root_id, nullptr, FullObjectSlot(&cache->at(i)));
    // We may see objects in trusted space here (outside of the main pointer
    // compression cage), so have to use SafeEquals.
    Tagged<Object> undefined = ReadOnlyRoots(isolate).undefined_value();
    if (cache->at(i).SafeEquals(undefined)) break;
  }
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::undefined, v8::internal::RootVisitor::VisitRootPointer(), and v8::internal::Smi::zero().
Referenced by v8::internal::SerializerDeserializer::IterateSharedHeapObjectCache(), and v8::internal::SerializerDeserializer::IterateStartupObjectCache().