cppgc::internal::anonymous_namespace{sweeper.cc} Namespace Reference
Classes
class DeadlineChecker
class ObjectStartBitmapVerifier
class FreeHandlerBase
class DiscardingFreeHandler
class RegularFreeHandler
class ThreadSafeStack
struct SweepingState
class InlinedFinalizationBuilderBase
class InlinedFinalizationBuilder
class DeferredFinalizationBuilder
class SweepFinalizer
class MutatorThreadSweeper
class ConcurrentSweepTask
class PrepareForSweepVisitor
Typedefs
using SpaceStates = std::vector< SweepingState >
Enumerations
enum class MutatorThreadSweepingMode { kOnlyFinalizers
, kAll
 }
enum class EmptyPageHandling { kDestroy
, kReturn
 }
Functions
constexpr const char * ToString (MutatorThreadSweepingMode sweeping_mode)
void StickyUnmark (HeapObjectHeader *header, StickyBits sticky_bits)
template<typename FinalizationBuilder >
FinalizationBuilder::ResultType SweepNormalPage (NormalPage *page, PageAllocator &page_allocator, StickyBits sticky_bits)
Variables
constexpr TaskPriority kBackgroundBoostedPriority = TaskPriority::kUserBlocking
constexpr TaskPriority kBackgroundRegularPriority = TaskPriority::kUserVisible
constexpr TaskPriority kForegroundRegularPriority = TaskPriority::kUserBlocking
constexpr TaskPriority kForegroundLowPriority = TaskPriority::kUserVisible
constexpr BaseSpace * kSweepWithoutSpaceAssignment = nullptr
Typedef Documentation
SpaceStates
using cppgc::internal::anonymous_namespace{sweeper.cc}::SpaceStates = typedef std::vector<SweepingState>
Definition at line 237 of file sweeper.cc.
Enumeration Type Documentation
EmptyPageHandling
enum cppgc::internal::anonymous_namespace{sweeper.cc}::EmptyPageHandling [strong]
Enumerator
kDestroy
kReturn
Definition at line 416 of file sweeper.cc.
                             {
  kDestroy,
  kReturn,
};
MutatorThreadSweepingMode
enum cppgc::internal::anonymous_namespace{sweeper.cc}::MutatorThreadSweepingMode [strong]
Enumerator
kOnlyFinalizers
kAll
Definition at line 58 of file sweeper.cc.
                                     {
  kOnlyFinalizers,
  kAll,
};
Function Documentation
StickyUnmark()
void cppgc::internal::anonymous_namespace{sweeper.cc}::StickyUnmark (HeapObjectHeader * header, StickyBits sticky_bits)
Definition at line 239 of file sweeper.cc.
                                                                    {
#if defined(CPPGC_YOUNG_GENERATION)
  // Young generation in Oilpan uses sticky mark bits.
  if (sticky_bits == StickyBits::kDisabled)
    header->Unmark<AccessMode::kAtomic>();
#else // !defined(CPPGC_YOUNG_GENERATION)
  header->Unmark<AccessMode::kAtomic>();
#endif // !defined(CPPGC_YOUNG_GENERATION)
}
References cppgc::internal::kAtomic, cppgc::internal::kDisabled, and cppgc::internal::HeapObjectHeader::Unmark().
Referenced by cppgc::internal::anonymous_namespace{sweeper.cc}::MutatorThreadSweeper::SweepLiveLargePage(), and SweepNormalPage().
SweepNormalPage()
template<typename FinalizationBuilder >
FinalizationBuilder::ResultType cppgc::internal::anonymous_namespace{sweeper.cc}::SweepNormalPage (NormalPage * page, PageAllocator & page_allocator, StickyBits sticky_bits)
Definition at line 340 of file sweeper.cc.
                                                                             {
  constexpr auto kAtomicAccess = AccessMode::kAtomic;
  FinalizationBuilder builder(*page, page_allocator);
  PlatformAwareObjectStartBitmap& bitmap = page->object_start_bitmap();
  size_t live_bytes = 0;
  Address start_of_gap = page->PayloadStart();
  const auto clear_bit_if_coalesced_entry = [&bitmap,
                                             &start_of_gap](Address address) {
    if (address != start_of_gap) {
      // Clear only if not the first freed entry.
      bitmap.ClearBit<AccessMode::kAtomic>(address);
    } else {
      // Otherwise check that the bit is set.
      DCHECK(bitmap.CheckBit<AccessMode::kAtomic>(address));
    }
  };
  for (Address begin = page->PayloadStart(), end = page->PayloadEnd();
       begin != end;) {
    DCHECK(bitmap.CheckBit<AccessMode::kAtomic>(begin));
    HeapObjectHeader* header = reinterpret_cast<HeapObjectHeader*>(begin);
    const size_t size = header->AllocatedSize();
    // Check if this is a free list entry.
    if (header->IsFree<kAtomicAccess>()) {
      SetMemoryInaccessible(header, std::min(kFreeListEntrySize, size));
      // This prevents memory from being discarded in configurations where
      // `CheckMemoryIsInaccessibleIsNoop()` is false.
      CheckMemoryIsInaccessible(header, size);
      clear_bit_if_coalesced_entry(begin);
      begin += size;
      continue;
    }
    // Check if object is not marked (not reachable).
    if (!header->IsMarked<kAtomicAccess>()) {
      builder.AddFinalizer(header, size);
      clear_bit_if_coalesced_entry(begin);
      begin += size;
      continue;
    }
    // The object is alive.
    const Address header_address = reinterpret_cast<Address>(header);
    if (start_of_gap != header_address) {
      const size_t new_free_list_entry_size =
          static_cast<size_t>(header_address - start_of_gap);
      builder.AddFreeListEntry(start_of_gap, new_free_list_entry_size);
      DCHECK(bitmap.CheckBit<AccessMode::kAtomic>(start_of_gap));
    }
    StickyUnmark(header, sticky_bits);
    begin += size;
    start_of_gap = begin;
    live_bytes += size;
  }
  const bool is_empty = live_bytes == 0;
  CHECK_EQ(is_empty, page->marked_bytes() == 0);
  CHECK_IMPLIES(is_empty, start_of_gap == page->PayloadStart());
  // Empty pages are not added to the free list directly here. The free list is
  // either added later on or the page is destroyed.
  if (!is_empty && start_of_gap != page->PayloadEnd()) {
    builder.AddFreeListEntry(
        start_of_gap, static_cast<size_t>(page->PayloadEnd() - start_of_gap));
    DCHECK(bitmap.CheckBit<AccessMode::kAtomic>(start_of_gap));
  }
  page->SetAllocatedBytesAtLastGC(live_bytes);
  page->ResetMarkedBytes(sticky_bits == StickyBits::kDisabled ? 0 : live_bytes);
  return builder.GetResult(is_empty);
}
References cppgc::internal::HeapObjectHeader::AllocatedSize(), v8::internal::compiler::begin(), CHECK_EQ, CHECK_IMPLIES, cppgc::internal::ObjectStartBitmap::CheckBit(), cppgc::internal::CheckMemoryIsInaccessible(), cppgc::internal::PlatformAwareObjectStartBitmap::ClearBit(), DCHECK, v8::internal::compiler::end(), v8::internal::compiler::turboshaft::is_empty(), cppgc::internal::HeapObjectHeader::IsFree(), cppgc::internal::HeapObjectHeader::IsMarked(), cppgc::internal::kAtomic, cppgc::internal::kDisabled, cppgc::internal::kFreeListEntrySize, cppgc::internal::BasePage::marked_bytes(), cppgc::internal::NormalPage::object_start_bitmap(), cppgc::internal::NormalPage::PayloadEnd(), cppgc::internal::NormalPage::PayloadStart(), cppgc::internal::BasePage::ResetMarkedBytes(), cppgc::internal::NormalPage::SetAllocatedBytesAtLastGC(), cppgc::internal::SetMemoryInaccessible(), size(), and StickyUnmark().
Referenced by cppgc::internal::anonymous_namespace{sweeper.cc}::MutatorThreadSweeper::VisitNormalPage(), and cppgc::internal::anonymous_namespace{sweeper.cc}::ConcurrentSweepTask::VisitNormalPage().
ToString()
constexpr const char* cppgc::internal::anonymous_namespace{sweeper.cc}::ToString (MutatorThreadSweepingMode sweeping_mode) [constexpr]
Definition at line 63 of file sweeper.cc.
                                                                        {
  switch (sweeping_mode) {
    case MutatorThreadSweepingMode::kAll:
      return "all";
    case MutatorThreadSweepingMode::kOnlyFinalizers:
      return "only-finalizers";
  }
}
Variable Documentation
kBackgroundBoostedPriority
constexpr TaskPriority cppgc::internal::anonymous_namespace{sweeper.cc}::kBackgroundBoostedPriority = TaskPriority::kUserBlocking [constexpr]
Definition at line 37 of file sweeper.cc.
Referenced by cppgc::internal::Sweeper::SweeperImpl::FinishIfRunning().
kBackgroundRegularPriority
constexpr TaskPriority cppgc::internal::anonymous_namespace{sweeper.cc}::kBackgroundRegularPriority = TaskPriority::kUserVisible [constexpr]
Definition at line 38 of file sweeper.cc.
Referenced by cppgc::internal::Sweeper::SweeperImpl::ScheduleConcurrentSweeping().
kForegroundLowPriority
constexpr TaskPriority cppgc::internal::anonymous_namespace{sweeper.cc}::kForegroundLowPriority = TaskPriority::kUserVisible [constexpr]
Definition at line 40 of file sweeper.cc.
Referenced by cppgc::internal::Sweeper::SweeperImpl::IncrementalSweepTask::Run(), and cppgc::internal::Sweeper::SweeperImpl::Start().
kForegroundRegularPriority
constexpr TaskPriority cppgc::internal::anonymous_namespace{sweeper.cc}::kForegroundRegularPriority = TaskPriority::kUserBlocking [constexpr]
Definition at line 39 of file sweeper.cc.
Referenced by cppgc::internal::Sweeper::SweeperImpl::IncrementalSweepTask::Run(), and cppgc::internal::Sweeper::SweeperImpl::Start().
kSweepWithoutSpaceAssignment
constexpr BaseSpace* cppgc::internal::anonymous_namespace{sweeper.cc}::kSweepWithoutSpaceAssignment = nullptr [constexpr]
Definition at line 414 of file sweeper.cc.
Referenced by cppgc::internal::Sweeper::SweeperImpl::Finish(), cppgc::internal::Sweeper::SweeperImpl::PerformSweepOnMutatorThread(), and cppgc::internal::Sweeper::SweeperImpl::SynchronizeAndFinalizeConcurrentAndIncrementalSweeping().