v8::tracing::anonymous_namespace{traced-value.cc} Namespace Reference
Functions
void EscapeAndAppendString (const char *value, std::string *result)
Function Documentation
EscapeAndAppendString()
void v8::tracing::anonymous_namespace{traced-value.cc}::EscapeAndAppendString (const char * value, std::string * result)
Definition at line 32 of file traced-value.cc.
                                                                 {
  *result += '"';
  while (*value) {
    unsigned char c = *value++;
    switch (c) {
      case '\b':
        *result += "\\b";
        break;
      case '\f':
        *result += "\\f";
        break;
      case '\n':
        *result += "\\n";
        break;
      case '\r':
        *result += "\\r";
        break;
      case '\t':
        *result += "\\t";
        break;
      case '\"':
        *result += "\\\"";
        break;
      case '\\':
        *result += "\\\\";
        break;
      default:
        if (c < '\x20' || c == '\x7F') {
          char number_buffer[8];
          base::OS::SNPrintF(number_buffer, arraysize(number_buffer), "\\u%04X",
                             static_cast<unsigned>(c));
          *result += number_buffer;
        } else {
          *result += c;
        }
    }
  }
  *result += '"';
}
References arraysize, v8::base::internal::result, v8::base::SNPrintF(), and v8::internal::value.
Referenced by v8::tracing::TracedValue::AppendString(), and v8::tracing::TracedValue::SetString().