v8::internal::anonymous_namespace{tiering-manager.cc} Namespace Reference
Functions
void TraceInOptimizationQueue (Tagged< JSFunction > function, CodeKind current_code_kind)
void TraceHeuristicOptimizationDisallowed (Tagged< JSFunction > function)
void TraceRecompile (Isolate *isolate, Tagged< JSFunction > function, OptimizationDecision d)
bool FirstTimeTierUpToSparkplug (Isolate *isolate, Tagged< JSFunction > function)
bool TiersUpToMaglev (CodeKind code_kind)
bool TiersUpToMaglev (std::optional< CodeKind > code_kind)
int InterruptBudgetFor (Isolate *isolate, std::optional< CodeKind > code_kind, Tagged< JSFunction > function, CachedTieringDecision cached_tiering_decision, int bytecode_length)
void TrySetOsrUrgency (Isolate *isolate, Tagged< JSFunction > function, int osr_urgency)
void TryIncrementOsrUrgency (Isolate *isolate, Tagged< JSFunction > function)
void TryRequestOsrAtNextOpportunity (Isolate *isolate, Tagged< JSFunction > function)
bool ShouldResetInterruptBudgetByICChange (CachedTieringDecision cached_tiering_decision)
Function Documentation
FirstTimeTierUpToSparkplug()
bool v8::internal::anonymous_namespace{tiering-manager.cc}::FirstTimeTierUpToSparkplug (Isolate * isolate, Tagged< JSFunction > function)
Definition at line 158 of file tiering-manager.cc.
                                                                               {
  return !function->has_feedback_vector() ||
         // We request sparkplug even in the presence of a fbv, if we are
         // running ignition and haven't enqueued the function for sparkplug
         // batch compilation yet. This ensures we tier-up to sparkplug when the
         // feedback vector is allocated eagerly (e.g. for logging function
         // events; see JSFunction::InitializeFeedbackCell()).
         (function->ActiveTierIsIgnition(isolate) &&
          CanCompileWithBaseline(isolate, function->shared()) &&
          function->shared()->cached_tiering_decision() ==
              CachedTieringDecision::kPending);
}
References v8::internal::CanCompileWithBaseline(), and v8::internal::kPending.
Referenced by v8::internal::TieringManager::InterruptBudgetFor(), and v8::internal::TieringManager::OnInterruptTick().
InterruptBudgetFor()
int v8::internal::anonymous_namespace{tiering-manager.cc}::InterruptBudgetFor (Isolate * isolate, std::optional< CodeKind > code_kind, Tagged< JSFunction > function, CachedTieringDecision cached_tiering_decision, int bytecode_length)
Definition at line 180 of file tiering-manager.cc.
                                            {
  // Avoid interrupts while we're already tiering.
  if (function->tiering_in_progress()) return INT_MAX / 2;
  const std::optional<CodeKind> existing_request =
      function->GetRequestedOptimizationIfAny(isolate);
  if (existing_request == CodeKind::TURBOFAN_JS ||
      (code_kind.has_value() && code_kind.value() == CodeKind::TURBOFAN_JS)) {
    return v8_flags.invocation_count_for_osr * bytecode_length;
  }
  if (maglev::IsMaglevOsrEnabled() && existing_request == CodeKind::MAGLEV) {
    return v8_flags.invocation_count_for_maglev_osr * bytecode_length;
  }
  if (TiersUpToMaglev(code_kind) &&
      !function->IsTieringRequestedOrInProgress()) {
    if (v8_flags.profile_guided_optimization) {
      switch (cached_tiering_decision) {
        case CachedTieringDecision::kDelayMaglev:
          return (std::max(v8_flags.invocation_count_for_maglev,
                           v8_flags.minimum_invocations_after_ic_update) +
                  v8_flags.invocation_count_for_maglev_with_delay) *
                 bytecode_length;
        case CachedTieringDecision::kEarlyMaglev:
        case CachedTieringDecision::kEarlyTurbofan:
          return v8_flags.invocation_count_for_early_optimization *
                 bytecode_length;
        case CachedTieringDecision::kPending:
        case CachedTieringDecision::kEarlySparkplug:
        case CachedTieringDecision::kNormal:
          return v8_flags.invocation_count_for_maglev * bytecode_length;
      }
      // The enum value is coming from inside the sandbox and while the switch
      // is exhaustive, it's not guaranteed that value is one of the declared
      // values.
      SBXCHECK(false);
    }
    return v8_flags.invocation_count_for_maglev * bytecode_length;
  }
  return v8_flags.invocation_count_for_turbofan * bytecode_length;
}
References v8::internal::maglev::IsMaglevOsrEnabled(), v8::internal::kDelayMaglev, v8::internal::kEarlyMaglev, v8::internal::kEarlySparkplug, v8::internal::kEarlyTurbofan, v8::internal::kNormal, v8::internal::kPending, SBXCHECK, TiersUpToMaglev(), and v8::internal::v8_flags.
Referenced by v8::internal::TieringManager::InterruptBudgetFor().
ShouldResetInterruptBudgetByICChange()
bool v8::internal::anonymous_namespace{tiering-manager.cc}::ShouldResetInterruptBudgetByICChange (CachedTieringDecision cached_tiering_decision)
Definition at line 438 of file tiering-manager.cc.
                                                   {
  switch (cached_tiering_decision) {
    case CachedTieringDecision::kEarlyMaglev:
    case CachedTieringDecision::kEarlyTurbofan:
      return false;
    case CachedTieringDecision::kPending:
    case CachedTieringDecision::kEarlySparkplug:
    case CachedTieringDecision::kDelayMaglev:
    case CachedTieringDecision::kNormal:
      return true;
  }
  // The enum value is coming from inside the sandbox and while the switch is
  // exhaustive, it's not guaranteed that value is one of the declared values.
  SBXCHECK(false);
}
References v8::internal::kDelayMaglev, v8::internal::kEarlyMaglev, v8::internal::kEarlySparkplug, v8::internal::kEarlyTurbofan, v8::internal::kNormal, v8::internal::kPending, and SBXCHECK.
Referenced by v8::internal::TieringManager::NotifyICChanged().
TiersUpToMaglev() [1/2]
bool v8::internal::anonymous_namespace{tiering-manager.cc}::TiersUpToMaglev (CodeKind code_kind)
Definition at line 171 of file tiering-manager.cc.
                                         {
  return V8_LIKELY(maglev::IsMaglevEnabled()) &&
         CodeKindIsUnoptimizedJSFunction(code_kind);
}
References v8::internal::CodeKindIsUnoptimizedJSFunction(), v8::internal::maglev::IsMaglevEnabled(), and V8_LIKELY.
TiersUpToMaglev() [2/2]
bool v8::internal::anonymous_namespace{tiering-manager.cc}::TiersUpToMaglev (std::optional< CodeKind > code_kind)
Definition at line 176 of file tiering-manager.cc.
                                                      {
  return code_kind.has_value() && TiersUpToMaglev(code_kind.value());
}
Referenced by InterruptBudgetFor(), and v8::internal::TieringManager::ShouldOptimize().
TraceHeuristicOptimizationDisallowed()
void v8::internal::anonymous_namespace{tiering-manager.cc}::TraceHeuristicOptimizationDisallowed (Tagged< JSFunction > function)
Definition at line 109 of file tiering-manager.cc.
                                                                       {
  if (v8_flags.trace_opt_verbose) {
    PrintF(
        "[not marking function %s for optimization: marked with "
        "%%PrepareFunctionForOptimization for manual optimization]\n",
        function->DebugNameCStr().get());
  }
}
References v8::internal::PrintF(), and v8::internal::v8_flags.
Referenced by v8::internal::TieringManager::MaybeOptimizeFrame().
TraceInOptimizationQueue()
void v8::internal::anonymous_namespace{tiering-manager.cc}::TraceInOptimizationQueue (Tagged< JSFunction > function, CodeKind current_code_kind)
Definition at line 100 of file tiering-manager.cc.
                                                          {
  if (v8_flags.trace_opt_verbose) {
    PrintF("[not marking function %s (%s) for optimization: already queued]\n",
           function->DebugNameCStr().get(),
           CodeKindToString(current_code_kind));
  }
}
References v8::internal::CodeKindToString(), v8::internal::PrintF(), and v8::internal::v8_flags.
Referenced by v8::internal::TieringManager::MaybeOptimizeFrame().
TraceRecompile()
void v8::internal::anonymous_namespace{tiering-manager.cc}::TraceRecompile (Isolate * isolate, Tagged< JSFunction > function, OptimizationDecision d)
Definition at line 118 of file tiering-manager.cc.
                                            {
  if (v8_flags.trace_opt) {
    CodeTracer::Scope scope(isolate->GetCodeTracer());
    PrintF(scope.file(), "[marking ");
    ShortPrint(function, scope.file());
    PrintF(scope.file(), " for optimization to %s, %s, reason: %s",
           CodeKindToString(d.code_kind), ToString(d.concurrency_mode),
           OptimizationReasonToString(d.optimization_reason));
    PrintF(scope.file(), "]\n");
  }
}
References v8::internal::OptimizationDecision::code_kind, v8::internal::CodeKindToString(), v8::internal::OptimizationDecision::concurrency_mode, v8::internal::CodeTracer::Scope::file(), v8::internal::Isolate::GetCodeTracer(), v8::internal::OptimizationDecision::optimization_reason, v8::internal::OptimizationReasonToString(), v8::internal::PrintF(), v8::internal::ShortPrint(), v8::internal::ToString(), and v8::internal::v8_flags.
Referenced by v8::internal::TieringManager::Optimize().
TryIncrementOsrUrgency()
void v8::internal::anonymous_namespace{tiering-manager.cc}::TryIncrementOsrUrgency (Isolate * isolate, Tagged< JSFunction > function)
Definition at line 282 of file tiering-manager.cc.
                                                                           {
  int old_urgency = function->feedback_vector()->osr_urgency();
  int new_urgency = std::min(old_urgency + 1, FeedbackVector::kMaxOsrUrgency);
  TrySetOsrUrgency(isolate, function, new_urgency);
}
References v8::internal::FeedbackVector::kMaxOsrUrgency, and TrySetOsrUrgency().
Referenced by v8::internal::TieringManager::MaybeOptimizeFrame().
TryRequestOsrAtNextOpportunity()
void v8::internal::anonymous_namespace{tiering-manager.cc}::TryRequestOsrAtNextOpportunity (Isolate * isolate, Tagged< JSFunction > function)
Definition at line 288 of file tiering-manager.cc.
                                                                 {
  TrySetOsrUrgency(isolate, function, FeedbackVector::kMaxOsrUrgency);
}
References v8::internal::FeedbackVector::kMaxOsrUrgency, and TrySetOsrUrgency().
Referenced by v8::internal::TieringManager::MaybeOptimizeFrame(), and v8::internal::TieringManager::RequestOsrAtNextOpportunity().
TrySetOsrUrgency()
void v8::internal::anonymous_namespace{tiering-manager.cc}::TrySetOsrUrgency (Isolate * isolate, Tagged< JSFunction > function, int osr_urgency)
Definition at line 255 of file tiering-manager.cc.
                                       {
  Tagged<SharedFunctionInfo> shared = function->shared();
  if (V8_UNLIKELY(!v8_flags.use_osr)) return;
  if (V8_UNLIKELY(shared->optimization_disabled(
          (!v8_flags.maglev ||
           (v8_flags.turbofan && function->ActiveTierIsMaglev(isolate)))
              ? CodeKind::TURBOFAN_JS
              : CodeKind::MAGLEV))) {
    return;
  }
  // We've passed all checks - bump the OSR urgency.
  Tagged<FeedbackVector> fv = function->feedback_vector();
  if (V8_UNLIKELY(v8_flags.trace_osr)) {
    CodeTracer::Scope scope(isolate->GetCodeTracer());
    PrintF(scope.file(),
           "[OSR - setting osr urgency. function: %s, old urgency: %d, new "
           "urgency: %d]\n",
           function->DebugNameCStr().get(), fv->osr_urgency(), osr_urgency);
  }
  DCHECK_GE(osr_urgency, fv->osr_urgency()); // Never lower urgency here.
  fv->set_osr_urgency(osr_urgency);
}
References DCHECK_GE, v8::internal::CodeTracer::Scope::file(), v8::internal::Isolate::GetCodeTracer(), v8::internal::PrintF(), v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by TryIncrementOsrUrgency(), and TryRequestOsrAtNextOpportunity().