v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc} Namespace Reference
Classes
class EvaluateCallbackWrapper
Functions
template<typename ProtocolCallback >
bool wrapEvaluateResultAsync (InjectedScript *injectedScript, v8::MaybeLocal< v8::Value > maybeResultValue, const v8::TryCatch &tryCatch, const String16 &objectGroup, const WrapOptions &wrapOptions, bool throwOnSideEffect, ProtocolCallback *callback)
void innerCallFunctionOn (V8InspectorSessionImpl *session, InjectedScript::Scope &scope, v8::Local< v8::Value > recv, const String16 &expression, std::unique_ptr< protocol::Array< protocol::Runtime::CallArgument >> optionalArguments, bool silent, std::unique_ptr< WrapOptions > wrapOptions, bool userGesture, bool awaitPromise, const String16 &objectGroup, bool throwOnSideEffect, std::unique_ptr< V8RuntimeAgentImpl::CallFunctionOnCallback > callback)
Response ensureContext (V8InspectorImpl *inspector, int contextGroupId, std::optional< int > executionContextId, std::optional< String16 > uniqueContextId, int *contextId)
Response parseAdditionalSerializationParameters (protocol::DictionaryValue *additionalParameters, v8::Isolate *isolate, v8::Local< v8::Object > *result)
Response getWrapOptions (std::optional< bool > returnByValue, std::optional< bool > generatePreview, std::unique_ptr< protocol::Runtime::SerializationOptions > maybeSerializationOptions, v8::Isolate *isolate, std::unique_ptr< WrapOptions > *result)
Response getWrapOptions (std::optional< bool > returnByValue, std::optional< bool > generatePreview, v8::Isolate *isolate, std::unique_ptr< WrapOptions > *result)
protocol::DictionaryValue * getOrCreateDictionary (protocol::DictionaryValue *dict, const String16 &key)
Function Documentation
ensureContext()
Response v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::ensureContext (V8InspectorImpl * inspector, int contextGroupId, std::optional< int > executionContextId, std::optional< String16 > uniqueContextId, int * contextId)
Definition at line 216 of file v8-runtime-agent-impl.cc.
                                       {
  if (executionContextId.has_value()) {
    if (uniqueContextId.has_value()) {
      return Response::InvalidParams(
          "contextId and uniqueContextId are mutually exclusive");
    }
    *contextId = executionContextId.value();
  } else if (uniqueContextId.has_value()) {
    internal::V8DebuggerId uniqueId(uniqueContextId.value());
    if (!uniqueId.isValid())
      return Response::InvalidParams("invalid uniqueContextId");
    int id = inspector->resolveUniqueContextId(uniqueId);
    if (!id) return Response::InvalidParams("uniqueContextId not found");
    *contextId = id;
  } else {
    v8::HandleScope handles(inspector->isolate());
    v8::Local<v8::Context> defaultContext =
        inspector->client()->ensureDefaultContextInGroup(contextGroupId);
    if (defaultContext.IsEmpty())
      return Response::ServerError("Cannot find default execution context");
    *contextId = InspectedContext::contextId(defaultContext);
  }
  return Response::Success();
}
References v8_inspector::V8InspectorImpl::client(), v8_inspector::InspectedContext::contextId(), v8_inspector::V8InspectorClient::ensureDefaultContextInGroup(), v8::api_internal::IndirectHandleBase::IsEmpty(), v8_inspector::V8InspectorImpl::isolate(), v8_inspector::internal::V8DebuggerId::isValid(), and v8_inspector::V8InspectorImpl::resolveUniqueContextId().
Referenced by v8_inspector::V8RuntimeAgentImpl::callFunctionOn(), v8_inspector::V8RuntimeAgentImpl::compileScript(), v8_inspector::V8RuntimeAgentImpl::evaluate(), v8_inspector::V8RuntimeAgentImpl::globalLexicalScopeNames(), and v8_inspector::V8RuntimeAgentImpl::runScript().
getOrCreateDictionary()
protocol::DictionaryValue* v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::getOrCreateDictionary (protocol::DictionaryValue * dict, const String16 & key)
Definition at line 885 of file v8-runtime-agent-impl.cc.
                                                        {
  if (protocol::DictionaryValue* bindings = dict->getObject(key))
    return bindings;
  dict->setObject(key, protocol::DictionaryValue::create());
  return dict->getObject(key);
}
References v8_inspector::V8RuntimeAgentImplState::bindings, and v8::internal::key.
Referenced by v8_inspector::V8RuntimeAgentImpl::addBinding().
getWrapOptions() [1/2]
Response v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::getWrapOptions (std::optional< bool > returnByValue, std::optional< bool > generatePreview, std::unique_ptr< protocol::Runtime::SerializationOptions > maybeSerializationOptions, v8::Isolate * isolate, std::unique_ptr< WrapOptions > * result)
Definition at line 279 of file v8-runtime-agent-impl.cc.
                                                            {
  if (maybeSerializationOptions) {
    String16 serializationModeStr =
        maybeSerializationOptions->getSerialization();
    if (serializationModeStr ==
        protocol::Runtime::SerializationOptions::SerializationEnum::Deep) {
      v8::Local<v8::Object> additionalParameters;
      Response response = parseAdditionalSerializationParameters(
          maybeSerializationOptions->getAdditionalParameters(nullptr), isolate,
          &additionalParameters);
      if (!response.IsSuccess()) {
        return response;
      }
      *result = std::make_unique<WrapOptions>(WrapOptions{
          WrapMode::kDeep,
          {maybeSerializationOptions->getMaxDepth(v8::internal::kMaxInt),
           v8::Global<v8::Object>(isolate, additionalParameters)}});
      return Response::Success();
    }
    if (serializationModeStr ==
        protocol::Runtime::SerializationOptions::SerializationEnum::Json) {
      *result = std::make_unique<WrapOptions>(WrapOptions{WrapMode::kJson});
      return Response::Success();
    }
    if (serializationModeStr ==
        protocol::Runtime::SerializationOptions::SerializationEnum::IdOnly) {
      *result = std::make_unique<WrapOptions>(WrapOptions{WrapMode::kIdOnly});
      return Response::Success();
    }
    return Response::InvalidParams(
        "Unknown serializationOptions.serialization value " +
        serializationModeStr.utf8());
  }
  if (returnByValue.value_or(false)) {
    *result = std::make_unique<WrapOptions>(WrapOptions{WrapMode::kJson});
    return Response::Success();
  }
  if (generatePreview.value_or(false)) {
    *result = std::make_unique<WrapOptions>(WrapOptions{WrapMode::kPreview});
    return Response::Success();
  }
  *result = std::make_unique<WrapOptions>(WrapOptions{WrapMode::kIdOnly});
  return Response::Success();
}
References v8_inspector::kDeep, v8_inspector::kIdOnly, v8_inspector::kJson, v8::internal::kMaxInt, v8_inspector::kPreview, parseAdditionalSerializationParameters(), v8::base::internal::result, and v8_inspector::String16::utf8().
getWrapOptions() [2/2]
Response v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::getWrapOptions (std::optional< bool > returnByValue, std::optional< bool > generatePreview, v8::Isolate * isolate, std::unique_ptr< WrapOptions > * result)
Definition at line 330 of file v8-runtime-agent-impl.cc.
                                                            {
  return getWrapOptions(std::move(returnByValue), std::move(generatePreview),
                        nullptr /* empty serialization options */, isolate,
                        result);
}
References v8::base::internal::result.
Referenced by v8_inspector::V8RuntimeAgentImpl::awaitPromise(), v8_inspector::V8RuntimeAgentImpl::callFunctionOn(), v8_inspector::V8RuntimeAgentImpl::evaluate(), v8_inspector::V8RuntimeAgentImpl::getProperties(), and v8_inspector::V8RuntimeAgentImpl::runScript().
innerCallFunctionOn()
void v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::innerCallFunctionOn (V8InspectorSessionImpl * session, InjectedScript::Scope & scope, v8::Local< v8::Value > recv, const String16 & expression, std::unique_ptr< protocol::Array< protocol::Runtime::CallArgument >> optionalArguments, bool silent, std::unique_ptr< WrapOptions > wrapOptions, bool userGesture, bool awaitPromise, const String16 & objectGroup, bool throwOnSideEffect, std::unique_ptr< V8RuntimeAgentImpl::CallFunctionOnCallback > callback)
Definition at line 121 of file v8-runtime-agent-impl.cc.
                                                                      {
  V8InspectorImpl* inspector = session->inspector();
  v8::LocalVector<v8::Value> args(inspector->isolate());
  if (optionalArguments) {
    protocol::Array<protocol::Runtime::CallArgument>& arguments =
        *optionalArguments;
    int argc = static_cast<int>(arguments.size());
    args.resize(argc);
    for (int i = 0; i < argc; ++i) {
      Response response = scope.injectedScript()->resolveCallArgument(
          arguments[i].get(), &args[i]);
      if (!response.IsSuccess()) {
        callback->sendFailure(response);
        return;
      }
    }
  }
  if (silent) scope.ignoreExceptionsAndMuteConsole();
  if (userGesture) scope.pretendUserGesture();
  // Temporarily enable allow evals for inspector.
  scope.allowCodeGenerationFromStrings();
  v8::MaybeLocal<v8::Value> maybeFunctionValue;
  v8::Local<v8::Script> functionScript;
  if (inspector
          ->compileScript(scope.context(), "(" + expression + ")", String16())
          .ToLocal(&functionScript)) {
    v8::MicrotasksScope microtasksScope(scope.context(),
                                        v8::MicrotasksScope::kRunMicrotasks);
    maybeFunctionValue = functionScript->Run(scope.context());
  }
  // Re-initialize after running client's code, as it could have destroyed
  // context or session.
  Response response = scope.initialize();
  if (!response.IsSuccess()) {
    callback->sendFailure(response);
    return;
  }
  if (scope.tryCatch().HasCaught()) {
    wrapEvaluateResultAsync(scope.injectedScript(), maybeFunctionValue,
                            scope.tryCatch(), objectGroup,
                            WrapOptions({WrapMode::kIdOnly}), throwOnSideEffect,
                            callback.get());
    return;
  }
  v8::Local<v8::Value> functionValue;
  if (!maybeFunctionValue.ToLocal(&functionValue) ||
      !functionValue->IsFunction()) {
    callback->sendFailure(Response::ServerError(
        "Given expression does not evaluate to a function"));
    return;
  }
  v8::MaybeLocal<v8::Value> maybeResultValue;
  {
    v8::MicrotasksScope microtasksScope(scope.context(),
                                        v8::MicrotasksScope::kRunMicrotasks);
    maybeResultValue = v8::debug::CallFunctionOn(
        scope.context(), functionValue.As<v8::Function>(), recv,
        v8::base::VectorOf(args), throwOnSideEffect);
  }
  // Re-initialize after running client's code, as it could have destroyed
  // context or session.
  response = scope.initialize();
  if (!response.IsSuccess()) {
    callback->sendFailure(response);
    return;
  }
  if (!awaitPromise || scope.tryCatch().HasCaught()) {
    wrapEvaluateResultAsync(scope.injectedScript(), maybeResultValue,
                            scope.tryCatch(), objectGroup, *wrapOptions,
                            throwOnSideEffect, callback.get());
    return;
  }
  scope.injectedScript()->addPromiseCallback(
      session, maybeResultValue, objectGroup, std::move(wrapOptions),
      false /* replMode */, throwOnSideEffect,
      EvaluateCallbackWrapper<V8RuntimeAgentImpl::CallFunctionOnCallback>::wrap(
          std::move(callback)));
}
References v8_inspector::InjectedScript::addPromiseCallback(), v8_inspector::InjectedScript::Scope::allowCodeGenerationFromStrings(), v8::base::args, v8::Local< T >::As(), v8::debug::CallFunctionOn(), v8_inspector::InjectedScript::Scope::context(), v8::TryCatch::HasCaught(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8_inspector::InjectedScript::Scope::ignoreExceptionsAndMuteConsole(), v8_inspector::InjectedScript::Scope::initialize(), v8_inspector::InjectedScript::Scope::injectedScript(), v8_inspector::V8InspectorSessionImpl::inspector(), v8::Value::IsFunction(), v8_inspector::V8InspectorImpl::isolate(), v8_inspector::kIdOnly, v8::MicrotasksScope::kRunMicrotasks, v8_inspector::InjectedScript::Scope::pretendUserGesture(), v8_inspector::InjectedScript::resolveCallArgument(), v8::MaybeLocal< T >::ToLocal(), v8_inspector::InjectedScript::Scope::tryCatch(), v8::base::VectorOf(), and wrapEvaluateResultAsync().
Referenced by v8_inspector::V8RuntimeAgentImpl::callFunctionOn().
parseAdditionalSerializationParameters()
Response v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::parseAdditionalSerializationParameters (protocol::DictionaryValue * additionalParameters, v8::Isolate * isolate, v8::Local< v8::Object > * result)
Definition at line 245 of file v8-runtime-agent-impl.cc.
                               {
  v8::LocalVector<v8::Name> keys(isolate);
  v8::LocalVector<v8::Value> values(isolate);
  if (additionalParameters != nullptr) {
    for (size_t i = 0; i < additionalParameters->size(); ++i) {
      String16 key = (*additionalParameters).at(i).first;
      keys.push_back(toV8String(isolate, key));
      protocol::Value* value = (*additionalParameters).at(i).second;
      String16 stringValue;
      if (value->asString(&stringValue)) {
        values.push_back(toV8String(isolate, stringValue));
        continue;
      }
      int intValue;
      if (value->asInteger(&intValue)) {
        values.push_back(v8::Int32::New(isolate, intValue));
        continue;
      }
      return Response::InvalidParams(
          "Values of serializationOptions.additionalParameters can be only of "
          "type string or integer.");
    }
  }
  CHECK(keys.size() == values.size());
  *result = v8::Object::New(isolate, v8::Null(isolate), keys.data(),
                            values.data(), keys.size());
  return Response::Success();
}
References CHECK, v8::LocalVector< T >::data(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::key, v8::Object::New(), v8::Integer::New(), v8::Null(), v8::LocalVector< T >::push_back(), v8::base::internal::result, v8::LocalVector< T >::size(), v8_inspector::toV8String(), and v8::internal::value.
Referenced by getWrapOptions().
wrapEvaluateResultAsync()
template<typename ProtocolCallback >
bool v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::wrapEvaluateResultAsync (InjectedScript * injectedScript, v8::MaybeLocal< v8::Value > maybeResultValue, const v8::TryCatch & tryCatch, const String16 & objectGroup, const WrapOptions & wrapOptions, bool throwOnSideEffect, ProtocolCallback * callback)
Definition at line 100 of file v8-runtime-agent-impl.cc.
                                                         {
  std::unique_ptr<RemoteObject> result;
  std::unique_ptr<protocol::Runtime::ExceptionDetails> exceptionDetails;
  Response response = injectedScript->wrapEvaluateResult(
      maybeResultValue, tryCatch, objectGroup, wrapOptions, throwOnSideEffect,
      &result, &exceptionDetails);
  if (response.IsSuccess()) {
    callback->sendSuccess(std::move(result), std::move(exceptionDetails));
    return true;
  }
  callback->sendFailure(response);
  return false;
}
References v8::base::internal::result, and v8_inspector::InjectedScript::wrapEvaluateResult().
Referenced by v8_inspector::V8RuntimeAgentImpl::evaluate(), innerCallFunctionOn(), and v8_inspector::V8RuntimeAgentImpl::runScript().