v8::internal::compiler::anonymous_namespace{js-native-context-specialization.cc} Namespace Reference
Functions
bool HasNumberMaps (JSHeapBroker *broker, ZoneVector< MapRef > const &maps)
bool HasOnlyJSArrayMaps (JSHeapBroker *broker, ZoneVector< MapRef > const &maps)
bool IsStringConstant (JSHeapBroker *broker, Node *node)
bool IsStringWithNonAccessibleContent (JSHeapBroker *broker, Node *node)
FieldAccess ForPropertyCellValue (MachineRepresentation representation, Type type, OptionalMapRef map, NameRef name)
OptionalJSTypedArrayRef GetTypedArrayConstant (JSHeapBroker *broker, Node *receiver)
CallDescriptor * PushRegularApiCallInputs (JSGraph *jsgraph, JSHeapBroker *broker, Node *receiver, Node *frame_state, Node *value, Node **effect, Node **control, FunctionTemplateInfoRef function_template_info, Node **inputs, int &cursor)
Function Documentation
ForPropertyCellValue()
FieldAccess v8::internal::compiler::anonymous_namespace{js-native-context-specialization.cc}::ForPropertyCellValue (MachineRepresentation representation, Type type, OptionalMapRef map, NameRef name)
Definition at line 1076 of file js-native-context-specialization.cc.
                                                                              {
  WriteBarrierKind kind = kFullWriteBarrier;
  if (representation == MachineRepresentation::kTaggedSigned) {
    kind = kNoWriteBarrier;
  } else if (representation == MachineRepresentation::kTaggedPointer) {
    kind = kPointerWriteBarrier;
  }
  MachineType r = MachineType::TypeForRepresentation(representation);
  FieldAccess access = {
      kTaggedBase, PropertyCell::kValueOffset, name.object(), map, type, r,
      kind, "PropertyCellValue"};
  return access;
}
References v8::internal::compiler::kFullWriteBarrier, v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kPointerWriteBarrier, v8::internal::compiler::kTaggedBase, v8::internal::kTaggedPointer, v8::internal::kTaggedSigned, v8::internal::name, v8::internal::tracing::type, and v8::internal::MachineType::TypeForRepresentation().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceGlobalAccess().
GetTypedArrayConstant()
OptionalJSTypedArrayRef v8::internal::compiler::anonymous_namespace{js-native-context-specialization.cc}::GetTypedArrayConstant (JSHeapBroker * broker, Node * receiver)
Definition at line 2200 of file js-native-context-specialization.cc.
                                                              {
  HeapObjectMatcher m(receiver);
  if (!m.HasResolvedValue()) return std::nullopt;
  ObjectRef object = m.Ref(broker);
  if (!object.IsJSTypedArray()) return std::nullopt;
  JSTypedArrayRef typed_array = object.AsJSTypedArray();
  if (typed_array.is_on_heap()) return std::nullopt;
  return typed_array;
}
References broker(), v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), v8::internal::compiler::JSTypedArrayRef::is_on_heap(), and v8::internal::compiler::HeapObjectMatcherImpl< kHeapConstantOpcode >::Ref().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::BuildElementAccessForTypedArrayOrRabGsabTypedArray().
HasNumberMaps()
bool v8::internal::compiler::anonymous_namespace{js-native-context-specialization.cc}::HasNumberMaps (JSHeapBroker * broker, ZoneVector< MapRef > const & maps)
Definition at line 48 of file js-native-context-specialization.cc.
                                                                         {
  for (MapRef map : maps) {
    if (map.IsHeapNumberMap()) return true;
  }
  return false;
}
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceNamedAccess().
HasOnlyJSArrayMaps()
bool v8::internal::compiler::anonymous_namespace{js-native-context-specialization.cc}::HasOnlyJSArrayMaps (JSHeapBroker * broker, ZoneVector< MapRef > const & maps)
Definition at line 55 of file js-native-context-specialization.cc.
                                                                              {
  for (MapRef map : maps) {
    if (!map.IsJSArrayMap()) return false;
  }
  return true;
}
Referenced by v8::internal::compiler::JSNativeContextSpecialization::BuildElementAccess(), v8::internal::maglev::MaglevGraphBuilder::TryBuildElementLoadOnJSArrayOrJSObject(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildElementStoreOnJSArrayOrJSObject().
IsStringConstant()
bool v8::internal::compiler::anonymous_namespace{js-native-context-specialization.cc}::IsStringConstant (JSHeapBroker * broker, Node * node)
Definition at line 220 of file js-native-context-specialization.cc.
                                                        {
  HeapObjectMatcher matcher(node);
  return matcher.HasResolvedValue() && matcher.Ref(broker).IsString();
}
References broker(), v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), and v8::internal::compiler::HeapObjectMatcherImpl< kHeapConstantOpcode >::Ref().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAdd().
IsStringWithNonAccessibleContent()
bool v8::internal::compiler::anonymous_namespace{js-native-context-specialization.cc}::IsStringWithNonAccessibleContent (JSHeapBroker * broker, Node * node)
Definition at line 225 of file js-native-context-specialization.cc.
                                                                        {
  HeapObjectMatcher matcher(node);
  if (matcher.HasResolvedValue() && matcher.Ref(broker).IsString()) {
    StringRef input = matcher.Ref(broker).AsString();
    return !input.IsContentAccessible();
  }
  return false;
}
References broker(), v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), v8::internal::compiler::StringRef::IsContentAccessible(), and v8::internal::compiler::HeapObjectMatcherImpl< kHeapConstantOpcode >::Ref().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::StringCanSafelyBeRead().
PushRegularApiCallInputs()
CallDescriptor* v8::internal::compiler::anonymous_namespace{js-native-context-specialization.cc}::PushRegularApiCallInputs (JSGraph * jsgraph, JSHeapBroker * broker, Node * receiver, Node * frame_state, Node * value, Node ** effect, Node ** control, FunctionTemplateInfoRef function_template_info, Node ** inputs, int & cursor)
Definition at line 2946 of file js-native-context-specialization.cc.
                 {
  // Only setters have a value.
  int const argc = value == nullptr ? 0 : 1;
  // The builtin always expects the receiver as the first param on the stack.
  bool no_profiling = broker->dependencies()->DependOnNoProfilingProtector();
  Callable call_api_callback = Builtins::CallableFor(
      jsgraph->isolate(), no_profiling
                              ? Builtin::kCallApiCallbackOptimizedNoProfiling
                              : Builtin::kCallApiCallbackOptimized);
  Node* func_templ =
      jsgraph->HeapConstantNoHole(function_template_info.object());
  ApiFunction function(function_template_info.callback(broker));
  Node* function_reference = jsgraph->graph()->NewNode(
      jsgraph->common()->ExternalConstant(ExternalReference::Create(
          jsgraph->isolate(), &function, ExternalReference::DIRECT_API_CALL,
          function_template_info.c_functions(broker).data(),
          function_template_info.c_signatures(broker).data(),
          static_cast<uint32_t>(
              function_template_info.c_functions(broker).size()))));
  Node* code = jsgraph->HeapConstantNoHole(call_api_callback.code());
  // Add CallApiCallbackStub's register argument as well.
  Node* context =
      jsgraph->ConstantNoHole(broker->target_native_context(), broker);
  inputs[cursor++] = code;
  inputs[cursor++] = function_reference;
  inputs[cursor++] = jsgraph->ConstantNoHole(argc);
  inputs[cursor++] = func_templ;
  inputs[cursor++] = receiver;
  if (value) {
    inputs[cursor++] = value;
  }
  inputs[cursor++] = context;
  inputs[cursor++] = frame_state;
  inputs[cursor++] = *effect;
  inputs[cursor++] = *control;
  CallInterfaceDescriptor call_interface_descriptor =
      call_api_callback.descriptor();
  return Linkage::GetStubCallDescriptor(
      jsgraph->zone(), call_interface_descriptor,
      call_interface_descriptor.GetStackParameterCount() + argc +
          1 /* implicit receiver */,
      CallDescriptor::kNeedsFrameState);
}
References broker(), v8::internal::compiler::FunctionTemplateInfoRef::c_functions(), v8::internal::compiler::FunctionTemplateInfoRef::c_signatures(), v8::internal::Builtins::CallableFor(), v8::internal::compiler::FunctionTemplateInfoRef::callback(), v8::internal::Callable::code(), code, v8::internal::compiler::MachineGraph::common(), v8::internal::compiler::JSGraph::ConstantNoHole(), v8::internal::ExternalReference::Create(), v8::internal::Callable::descriptor(), v8::internal::ExternalReference::DIRECT_API_CALL, v8::internal::compiler::CommonOperatorBuilder::ExternalConstant(), v8::internal::CallInterfaceDescriptor::GetStackParameterCount(), v8::internal::compiler::Linkage::GetStubCallDescriptor(), v8::internal::compiler::MachineGraph::graph(), v8::internal::compiler::JSGraph::HeapConstantNoHole(), v8::internal::compiler::JSGraph::isolate(), v8::internal::compiler::CallDescriptor::kNeedsFrameState, v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::FunctionTemplateInfoRef::object(), v8::internal::value, and v8::internal::compiler::MachineGraph::zone().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::InlineApiCall().