v8::internal::compiler::anonymous_namespace{code-generator-riscv.cc} Namespace Reference
Classes
class OutOfLineRecordWrite
Functions
Condition FlagsConditionToConditionCmp (FlagsCondition condition)
Condition FlagsConditionToConditionTst (FlagsCondition condition)
FPUCondition FlagsConditionToConditionCmpFPU (bool *predicate, FlagsCondition condition)
void RecordTrapInfoIfNeeded (Zone *zone, CodeGenerator *codegen, InstructionCode opcode, Instruction *instr, int pc)
void AdjustStackPointerForTailCall (MacroAssembler *masm, FrameAccessState *state, int new_slot_above_sp, bool allow_shrinkage=true)
Function Documentation
AdjustStackPointerForTailCall()
void v8::internal::compiler::anonymous_namespace{code-generator-riscv.cc}::AdjustStackPointerForTailCall (MacroAssembler * masm, FrameAccessState * state, int new_slot_above_sp, bool allow_shrinkage = true)
Definition at line 672 of file code-generator-riscv.cc.
                                                                {
  int current_sp_offset = state->GetSPToFPSlotCount() +
                          StandardFrameConstants::kFixedSlotCountAboveFp;
  int stack_slot_delta = new_slot_above_sp - current_sp_offset;
  if (stack_slot_delta > 0) {
    masm->SubWord(sp, sp, stack_slot_delta * kSystemPointerSize);
    state->IncreaseSPDelta(stack_slot_delta);
  } else if (allow_shrinkage && stack_slot_delta < 0) {
    masm->AddWord(sp, sp, -stack_slot_delta * kSystemPointerSize);
    state->IncreaseSPDelta(stack_slot_delta);
  }
}
References v8::internal::compiler::FrameAccessState::GetSPToFPSlotCount(), v8::internal::compiler::FrameAccessState::IncreaseSPDelta(), v8::internal::CommonFrameConstants::kFixedSlotCountAboveFp, and v8::internal::kSystemPointerSize.
FlagsConditionToConditionCmp()
Condition v8::internal::compiler::anonymous_namespace{code-generator-riscv.cc}::FlagsConditionToConditionCmp (FlagsCondition condition)
Definition at line 236 of file code-generator-riscv.cc.
                                                                 {
  switch (condition) {
    case kEqual:
      return eq;
    case kNotEqual:
      return ne;
    case kSignedLessThan:
      return lt;
    case kSignedGreaterThanOrEqual:
      return ge;
    case kSignedLessThanOrEqual:
      return le;
    case kSignedGreaterThan:
      return gt;
    case kUnsignedLessThan:
      return Uless;
    case kUnsignedGreaterThanOrEqual:
      return Ugreater_equal;
    case kUnsignedLessThanOrEqual:
      return Uless_equal;
    case kUnsignedGreaterThan:
      return Ugreater;
    case kUnorderedEqual:
    case kUnorderedNotEqual:
      break;
    default:
      break;
  }
  UNREACHABLE();
}
References v8::internal::eq, v8::internal::ge, v8::internal::gt, v8::internal::compiler::kEqual, v8::internal::compiler::kNotEqual, v8::internal::compiler::kSignedGreaterThan, v8::internal::compiler::kSignedGreaterThanOrEqual, v8::internal::compiler::kSignedLessThan, v8::internal::compiler::kSignedLessThanOrEqual, v8::internal::compiler::kUnorderedEqual, v8::internal::compiler::kUnorderedNotEqual, v8::internal::compiler::kUnsignedGreaterThan, v8::internal::compiler::kUnsignedGreaterThanOrEqual, v8::internal::compiler::kUnsignedLessThan, v8::internal::compiler::kUnsignedLessThanOrEqual, v8::internal::le, v8::internal::lt, v8::internal::ne, v8::internal::Ugreater, v8::internal::Ugreater_equal, v8::internal::Uless, v8::internal::Uless_equal, and v8::internal::UNREACHABLE().
FlagsConditionToConditionCmpFPU()
FPUCondition v8::internal::compiler::anonymous_namespace{code-generator-riscv.cc}::FlagsConditionToConditionCmpFPU (bool * predicate, FlagsCondition condition)
Definition at line 292 of file code-generator-riscv.cc.
                                                                       {
  switch (condition) {
    case kEqual:
      *predicate = true;
      return EQ;
    case kNotEqual:
      *predicate = false;
      return EQ;
    case kUnsignedLessThan:
    case kFloatLessThan:
      *predicate = true;
      return LT;
    case kUnsignedGreaterThanOrEqual:
      *predicate = false;
      return LT;
    case kUnsignedLessThanOrEqual:
    case kFloatLessThanOrEqual:
      *predicate = true;
      return LE;
    case kUnsignedGreaterThan:
      *predicate = false;
      return LE;
    case kUnorderedEqual:
    case kUnorderedNotEqual:
      *predicate = true;
      break;
    case kFloatGreaterThan:
      *predicate = true;
      return GT;
    case kFloatGreaterThanOrEqual:
      *predicate = true;
      return GE;
    case kFloatLessThanOrUnordered:
      *predicate = true;
      return LT;
    case kFloatGreaterThanOrUnordered:
      *predicate = false;
      return LE;
    case kFloatGreaterThanOrEqualOrUnordered:
      *predicate = false;
      return LT;
    case kFloatLessThanOrEqualOrUnordered:
      *predicate = true;
      return LE;
    default:
      *predicate = true;
      break;
  }
  UNREACHABLE();
}
References v8::internal::EQ, v8::internal::GE, v8::internal::GT, v8::internal::compiler::kEqual, v8::internal::compiler::kFloatGreaterThan, v8::internal::compiler::kFloatGreaterThanOrEqual, v8::internal::compiler::kFloatGreaterThanOrEqualOrUnordered, v8::internal::compiler::kFloatGreaterThanOrUnordered, v8::internal::compiler::kFloatLessThan, v8::internal::compiler::kFloatLessThanOrEqual, v8::internal::compiler::kFloatLessThanOrEqualOrUnordered, v8::internal::compiler::kFloatLessThanOrUnordered, v8::internal::compiler::kNotEqual, v8::internal::compiler::kUnorderedEqual, v8::internal::compiler::kUnorderedNotEqual, v8::internal::compiler::kUnsignedGreaterThan, v8::internal::compiler::kUnsignedGreaterThanOrEqual, v8::internal::compiler::kUnsignedLessThan, v8::internal::compiler::kUnsignedLessThanOrEqual, v8::internal::LE, v8::internal::LT, and v8::internal::UNREACHABLE().
FlagsConditionToConditionTst()
Condition v8::internal::compiler::anonymous_namespace{code-generator-riscv.cc}::FlagsConditionToConditionTst (FlagsCondition condition)
Definition at line 267 of file code-generator-riscv.cc.
                                                                 {
  switch (condition) {
    case kNotEqual:
      return ne;
    case kEqual:
      return eq;
    default:
      break;
  }
  UNREACHABLE();
}
References v8::internal::eq, v8::internal::compiler::kEqual, v8::internal::compiler::kNotEqual, v8::internal::ne, and v8::internal::UNREACHABLE().
RecordTrapInfoIfNeeded()
void v8::internal::compiler::anonymous_namespace{code-generator-riscv.cc}::RecordTrapInfoIfNeeded (Zone * zone, CodeGenerator * codegen, InstructionCode opcode, Instruction * instr, int pc)
Definition at line 386 of file code-generator-riscv.cc.
                                    {
  DCHECK_EQ(kMemoryAccessDirect, AccessModeField::decode(opcode));
}
References DCHECK_EQ, v8::base::BitField< T, shift, size, U >::decode(), and v8::internal::compiler::kMemoryAccessDirect.