v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc} Namespace Reference
Functions
String16 resourceNameToUrl (V8InspectorImpl *inspector, v8::Local< v8::String > v8Name)
std::unique_ptr< protocol::Array< protocol::Profiler::PositionTickInfo > > buildInspectorObjectForPositionTicks (const v8::CpuProfileNode *node)
std::unique_ptr< protocol::Profiler::ProfileNode > buildInspectorObjectFor (V8InspectorImpl *inspector, const v8::CpuProfileNode *node)
std::unique_ptr< protocol::Array< int > > buildInspectorObjectForSamples (v8::CpuProfile *v8profile)
std::unique_ptr< protocol::Array< int > > buildInspectorObjectForTimestamps (v8::CpuProfile *v8profile)
void flattenNodesTree (V8InspectorImpl *inspector, const v8::CpuProfileNode *node, protocol::Array< protocol::Profiler::ProfileNode > *list)
std::unique_ptr< protocol::Profiler::Profile > createCPUProfile (V8InspectorImpl *inspector, v8::CpuProfile *v8profile)
std::unique_ptr< protocol::Debugger::Location > currentDebugLocation (V8InspectorImpl *inspector)
std::unique_ptr< protocol::Profiler::CoverageRange > createCoverageRange (int start, int end, int count)
Response coverageToProtocol (V8InspectorImpl *inspector, const v8::debug::Coverage &coverage, std::unique_ptr< protocol::Array< protocol::Profiler::ScriptCoverage >> *out_result)
Variables
volatile int s_lastProfileId = 0
Function Documentation
buildInspectorObjectFor()
std::unique_ptr<protocol::Profiler::ProfileNode> v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::buildInspectorObjectFor (V8InspectorImpl * inspector, const v8::CpuProfileNode * node)
Definition at line 64 of file v8-profiler-agent-impl.cc.
                                                              {
  v8::Isolate* isolate = inspector->isolate();
  v8::HandleScope handleScope(isolate);
  auto callFrame =
      protocol::Runtime::CallFrame::create()
          .setFunctionName(toProtocolString(isolate, node->GetFunctionName()))
          .setScriptId(String16::fromInteger(node->GetScriptId()))
          .setUrl(resourceNameToUrl(inspector, node->GetScriptResourceName()))
          .setLineNumber(node->GetLineNumber() - 1)
          .setColumnNumber(node->GetColumnNumber() - 1)
          .build();
  auto result = protocol::Profiler::ProfileNode::create()
                    .setCallFrame(std::move(callFrame))
                    .setHitCount(node->GetHitCount())
                    .setId(node->GetNodeId())
                    .build();
  const int childrenCount = node->GetChildrenCount();
  if (childrenCount) {
    auto children = std::make_unique<protocol::Array<int>>();
    for (int i = 0; i < childrenCount; i++)
      children->emplace_back(node->GetChild(i)->GetNodeId());
    result->setChildren(std::move(children));
  }
  const char* deoptReason = node->GetBailoutReason();
  if (deoptReason && deoptReason[0] && strcmp(deoptReason, "no reason"))
    result->setDeoptReason(deoptReason);
  auto positionTicks = buildInspectorObjectForPositionTicks(node);
  if (positionTicks) result->setPositionTicks(std::move(positionTicks));
  return result;
}
References buildInspectorObjectForPositionTicks(), v8_inspector::String16::fromInteger(), v8::CpuProfileNode::GetBailoutReason(), v8::CpuProfileNode::GetChild(), v8::CpuProfileNode::GetChildrenCount(), v8::CpuProfileNode::GetColumnNumber(), v8::CpuProfileNode::GetFunctionName(), v8::CpuProfileNode::GetHitCount(), v8::CpuProfileNode::GetLineNumber(), v8::CpuProfileNode::GetNodeId(), v8::CpuProfileNode::GetScriptId(), v8::CpuProfileNode::GetScriptResourceName(), v8_inspector::V8InspectorImpl::isolate(), resourceNameToUrl(), v8::base::internal::result, and v8_inspector::toProtocolString().
Referenced by flattenNodesTree().
buildInspectorObjectForPositionTicks()
std::unique_ptr<protocol::Array<protocol::Profiler::PositionTickInfo> > v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::buildInspectorObjectForPositionTicks (const v8::CpuProfileNode * node)
Definition at line 45 of file v8-profiler-agent-impl.cc.
                                                                   {
  unsigned lineCount = node->GetHitLineCount();
  if (!lineCount) return nullptr;
  auto array =
      std::make_unique<protocol::Array<protocol::Profiler::PositionTickInfo>>();
  std::vector<v8::CpuProfileNode::LineTick> entries(lineCount);
  if (node->GetLineTicks(&entries[0], lineCount)) {
    for (unsigned i = 0; i < lineCount; i++) {
      std::unique_ptr<protocol::Profiler::PositionTickInfo> line =
          protocol::Profiler::PositionTickInfo::create()
              .setLine(entries[i].line)
              .setTicks(entries[i].hit_count)
              .build();
      array->emplace_back(std::move(line));
    }
  }
  return array;
}
References v8::CpuProfileNode::GetHitLineCount(), and v8::CpuProfileNode::GetLineTicks().
Referenced by buildInspectorObjectFor().
buildInspectorObjectForSamples()
std::unique_ptr<protocol::Array<int> > v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::buildInspectorObjectForSamples (v8::CpuProfile * v8profile)
Definition at line 100 of file v8-profiler-agent-impl.cc.
                             {
  auto array = std::make_unique<protocol::Array<int>>();
  int count = v8profile->GetSamplesCount();
  for (int i = 0; i < count; i++)
    array->emplace_back(v8profile->GetSample(i)->GetNodeId());
  return array;
}
References v8::CpuProfileNode::GetNodeId(), v8::CpuProfile::GetSample(), and v8::CpuProfile::GetSamplesCount().
Referenced by createCPUProfile().
buildInspectorObjectForTimestamps()
std::unique_ptr<protocol::Array<int> > v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::buildInspectorObjectForTimestamps (v8::CpuProfile * v8profile)
Definition at line 109 of file v8-profiler-agent-impl.cc.
                             {
  auto array = std::make_unique<protocol::Array<int>>();
  int count = v8profile->GetSamplesCount();
  uint64_t lastTime = v8profile->GetStartTime();
  for (int i = 0; i < count; i++) {
    uint64_t ts = v8profile->GetSampleTimestamp(i);
    array->emplace_back(static_cast<int>(ts - lastTime));
    lastTime = ts;
  }
  return array;
}
References v8::CpuProfile::GetSamplesCount(), v8::CpuProfile::GetSampleTimestamp(), and v8::CpuProfile::GetStartTime().
Referenced by createCPUProfile().
coverageToProtocol()
Response v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::coverageToProtocol (V8InspectorImpl * inspector, const v8::debug::Coverage & coverage, std::unique_ptr< protocol::Array< protocol::Profiler::ScriptCoverage >> * out_result)
Definition at line 352 of file v8-profiler-agent-impl.cc.
                    {
  auto result =
      std::make_unique<protocol::Array<protocol::Profiler::ScriptCoverage>>();
  v8::Isolate* isolate = inspector->isolate();
  for (size_t i = 0; i < coverage.ScriptCount(); i++) {
    v8::debug::Coverage::ScriptData script_data = coverage.GetScriptData(i);
    v8::Local<v8::debug::Script> script = script_data.GetScript();
    auto functions = std::make_unique<
        protocol::Array<protocol::Profiler::FunctionCoverage>>();
    for (size_t j = 0; j < script_data.FunctionCount(); j++) {
      v8::debug::Coverage::FunctionData function_data =
          script_data.GetFunctionData(j);
      auto ranges = std::make_unique<
          protocol::Array<protocol::Profiler::CoverageRange>>();
      // Add function range.
      ranges->emplace_back(createCoverageRange(function_data.StartOffset(),
                                               function_data.EndOffset(),
                                               function_data.Count()));
      // Process inner blocks.
      for (size_t k = 0; k < function_data.BlockCount(); k++) {
        v8::debug::Coverage::BlockData block_data =
            function_data.GetBlockData(k);
        ranges->emplace_back(createCoverageRange(block_data.StartOffset(),
                                                 block_data.EndOffset(),
                                                 block_data.Count()));
      }
      functions->emplace_back(
          protocol::Profiler::FunctionCoverage::create()
              .setFunctionName(toProtocolString(
                  isolate,
                  function_data.Name().FromMaybe(v8::Local<v8::String>())))
              .setRanges(std::move(ranges))
              .setIsBlockCoverage(function_data.HasBlockCoverage())
              .build());
    }
    String16 url;
    v8::Local<v8::String> name;
    if (script->SourceURL().ToLocal(&name) && name->Length()) {
      url = toProtocolString(isolate, name);
    } else if (script->Name().ToLocal(&name) && name->Length()) {
      url = resourceNameToUrl(inspector, name);
    }
    result->emplace_back(protocol::Profiler::ScriptCoverage::create()
                             .setScriptId(String16::fromInteger(script->Id()))
                             .setUrl(url)
                             .setFunctions(std::move(functions))
                             .build());
  }
  *out_result = std::move(result);
  return Response::Success();
}
References v8::debug::Coverage::FunctionData::BlockCount(), v8::debug::Coverage::BlockData::Count(), v8::debug::Coverage::FunctionData::Count(), createCoverageRange(), v8::debug::Coverage::BlockData::EndOffset(), v8::debug::Coverage::FunctionData::EndOffset(), v8_inspector::String16::fromInteger(), v8::debug::Coverage::ScriptData::FunctionCount(), v8::debug::Coverage::FunctionData::GetBlockData(), v8::debug::Coverage::ScriptData::GetFunctionData(), v8::debug::Coverage::ScriptData::GetScript(), v8::debug::Coverage::GetScriptData(), v8::debug::Coverage::FunctionData::HasBlockCoverage(), v8_inspector::V8InspectorImpl::isolate(), v8::debug::Coverage::FunctionData::Name(), name, resourceNameToUrl(), v8::base::internal::result, v8::internal::script, v8::debug::Coverage::ScriptCount(), v8::debug::Coverage::BlockData::StartOffset(), v8::debug::Coverage::FunctionData::StartOffset(), and v8_inspector::toProtocolString().
Referenced by v8_inspector::V8ProfilerAgentImpl::getBestEffortCoverage(), v8_inspector::V8ProfilerAgentImpl::takePreciseCoverage(), and v8_inspector::V8ProfilerAgentImpl::triggerPreciseCoverageDeltaUpdate().
createCoverageRange()
std::unique_ptr<protocol::Profiler::CoverageRange> v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::createCoverageRange (int start, int end, int count)
Definition at line 343 of file v8-profiler-agent-impl.cc.
                                   {
  return protocol::Profiler::CoverageRange::create()
      .setStartOffset(start)
      .setEndOffset(end)
      .setCount(count)
      .build();
}
References v8::internal::compiler::end().
Referenced by coverageToProtocol().
createCPUProfile()
std::unique_ptr<protocol::Profiler::Profile> v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::createCPUProfile (V8InspectorImpl * inspector, v8::CpuProfile * v8profile)
Definition at line 131 of file v8-profiler-agent-impl.cc.
                                                         {
  auto nodes =
      std::make_unique<protocol::Array<protocol::Profiler::ProfileNode>>();
  flattenNodesTree(inspector, v8profile->GetTopDownRoot(), nodes.get());
  return protocol::Profiler::Profile::create()
      .setNodes(std::move(nodes))
      .setStartTime(static_cast<double>(v8profile->GetStartTime()))
      .setEndTime(static_cast<double>(v8profile->GetEndTime()))
      .setSamples(buildInspectorObjectForSamples(v8profile))
      .setTimeDeltas(buildInspectorObjectForTimestamps(v8profile))
      .build();
}
References buildInspectorObjectForSamples(), buildInspectorObjectForTimestamps(), flattenNodesTree(), v8::CpuProfile::GetEndTime(), v8::CpuProfile::GetStartTime(), and v8::CpuProfile::GetTopDownRoot().
Referenced by v8_inspector::V8ProfilerAgentImpl::stopProfiling().
currentDebugLocation()
std::unique_ptr<protocol::Debugger::Location> v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::currentDebugLocation (V8InspectorImpl * inspector)
Definition at line 145 of file v8-profiler-agent-impl.cc.
                                {
  auto stackTrace = V8StackTraceImpl::capture(inspector->debugger(), 1);
  CHECK(stackTrace);
  CHECK(!stackTrace->isEmpty());
  return protocol::Debugger::Location::create()
      .setScriptId(String16::fromInteger(stackTrace->topScriptId()))
      .setLineNumber(stackTrace->topLineNumber())
      .setColumnNumber(stackTrace->topColumnNumber())
      .build();
}
References v8_inspector::V8StackTraceImpl::capture(), CHECK, v8_inspector::V8InspectorImpl::debugger(), and v8_inspector::String16::fromInteger().
Referenced by v8_inspector::V8ProfilerAgentImpl::consoleProfile(), and v8_inspector::V8ProfilerAgentImpl::consoleProfileEnd().
flattenNodesTree()
void v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::flattenNodesTree (V8InspectorImpl * inspector, const v8::CpuProfileNode * node, protocol::Array< protocol::Profiler::ProfileNode > * list)
Definition at line 122 of file v8-profiler-agent-impl.cc.
                                                                        {
  list->emplace_back(buildInspectorObjectFor(inspector, node));
  const int childrenCount = node->GetChildrenCount();
  for (int i = 0; i < childrenCount; i++)
    flattenNodesTree(inspector, node->GetChild(i), list);
}
References buildInspectorObjectFor(), v8::CpuProfileNode::GetChild(), and v8::CpuProfileNode::GetChildrenCount().
Referenced by createCPUProfile().
resourceNameToUrl()
String16 v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::resourceNameToUrl (V8InspectorImpl * inspector, v8::Local< v8::String > v8Name)
Definition at line 35 of file v8-profiler-agent-impl.cc.
                                                     {
  String16 name = toProtocolString(inspector->isolate(), v8Name);
  if (!inspector) return name;
  std::unique_ptr<StringBuffer> url =
      inspector->client()->resourceNameToUrl(toStringView(name));
  return url ? toString16(url->string()) : name;
}
References v8_inspector::V8InspectorImpl::client(), v8_inspector::V8InspectorImpl::isolate(), name, v8_inspector::V8InspectorClient::resourceNameToUrl(), v8_inspector::toProtocolString(), v8_inspector::toString16(), and v8_inspector::toStringView().
Referenced by buildInspectorObjectFor(), and coverageToProtocol().
Variable Documentation
s_lastProfileId
volatile int v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::s_lastProfileId = 0
Definition at line 157 of file v8-profiler-agent-impl.cc.
Referenced by v8_inspector::V8ProfilerAgentImpl::nextProfileId().