v8::internal::maglev::detail Namespace Reference
Classes
struct PushAllHelper
struct PushAllHelper<>
struct PushAllHelper< Input, Args... >
struct PushAllHelper< Arg, Args... >
struct CountPushHelper
struct CountPushHelper<>
struct CountPushHelper< Arg, Args... >
struct PushAllHelper< Arg >
struct PushAllHelper< Arg1, Arg2, Args... >
struct CopyForDeferredHelper
struct CopyForDeferredByValue
struct CopyForDeferredHelper< T *, std::enable_if_t< std::is_base_of_v< NodeBase, T > > >
struct CopyForDeferredHelper< T, std::enable_if_t< std::is_arithmetic_v< T > > >
struct CopyForDeferredHelper< T, std::enable_if_t< std::is_enum_v< T > > >
struct CopyForDeferredHelper< MaglevCompilationInfo * >
struct CopyForDeferredHelper< Register >
struct CopyForDeferredHelper< std::optional< Register > >
struct CopyForDeferredHelper< DoubleRegister >
struct CopyForDeferredHelper< BytecodeOffset >
struct CopyForDeferredHelper< EagerDeoptInfo * >
struct CopyForDeferredHelper< LazyDeoptInfo * >
struct CopyForDeferredHelper< ZoneLabelRef >
struct CopyForDeferredHelper< MapCompare >
struct CopyForDeferredHelper< RegList >
struct CopyForDeferredHelper< RegisterSnapshot >
struct CopyForDeferredHelper< FeedbackSlot >
struct CopyForDeferredHelper< T, std::enable_if_t< std::is_base_of_v< compiler::ObjectRef, T > > >
struct FunctionArgumentsTupleHelper
struct FunctionArgumentsTupleHelper< R(C::*)(A...) const >
struct FunctionArgumentsTupleHelper< R(&)(A...)>
struct StripFirstTupleArg
struct StripFirstTupleArg< std::tuple< T1, T... > >
class DeferredCodeInfoImpl
struct is_iterator_range
struct is_iterator_range< base::iterator_range< T > >
struct opcode_of_helper
class ArrayWrapper
struct YouNeedToDefineAnInputTypesArrayInYourDerivedClass
Functions
void PushInput (MaglevAssembler *masm, const Input &input)
template<typename T , typename... Args>
void PushIterator (MaglevAssembler *masm, base::iterator_range< T > range, Args... args)
template<typename T , typename... Args>
void PushIteratorReverse (MaglevAssembler *masm, base::iterator_range< T > range, Args... args)
template<typename Arg >
bool AlreadyInARegister (Arg arg)
bool AlreadyInARegister (Register reg)
bool AlreadyInARegister (const Input &input)
template<typename Arg >
Register ToRegister (MaglevAssembler *masm, MaglevAssembler::TemporaryRegisterScope *scratch, Arg arg)
Register ToRegister (MaglevAssembler *masm, MaglevAssembler::TemporaryRegisterScope *scratch, Register reg)
Register ToRegister (MaglevAssembler *masm, MaglevAssembler::TemporaryRegisterScope *scratch, const Input &input)
template<typename... Args>
void PushAll (MaglevAssembler *masm, Args... args)
template<typename... Args>
void PushAllReverse (MaglevAssembler *masm, Args... args)
template<typename Arg1 , typename Arg2 >
void PushAligned (MaglevAssembler *masm, Arg1 arg1, Arg2 arg2)
template<typename T >
T CopyForDeferred (MaglevCompilationInfo *compilation_info, T &&value)
template<typename T >
T CopyForDeferred (MaglevCompilationInfo *compilation_info, T &value)
template<typename T >
T CopyForDeferred (MaglevCompilationInfo *compilation_info, const T &value)
template<typename Descriptor , typename... Args>
void CheckArgs (Args &&... args)
template<typename Descriptor , typename... Args>
void PushArgumentsForBuiltin (MaglevAssembler *masm, std::tuple< Args... > args)
template<typename Descriptor >
void PushArgumentsForBuiltin (MaglevAssembler *masm, std::tuple<> empty_args)
template<Builtin kBuiltin, typename... Args>
void MoveArgumentsForBuiltin (MaglevAssembler *masm, Args &&... args)
template<typename T >
constexpr T * ObjectPtrBeforeAddress (void *address)
template<typename T >
constexpr const T * ObjectPtrBeforeAddress (const void *address)
Function Documentation
AlreadyInARegister() [1/3]
template<typename Arg >
bool v8::internal::maglev::detail::AlreadyInARegister (Arg arg) [inline]
Definition at line 128 of file maglev-assembler-arm64-inl.h.
                                        {
  return false;
}
AlreadyInARegister() [2/3]
bool v8::internal::maglev::detail::AlreadyInARegister (const Input & input) [inline]
Definition at line 134 of file maglev-assembler-arm64-inl.h.
                                                   {
  if (input.operand().IsConstant()) {
    return false;
  }
  const compiler::AllocatedOperand& operand =
      compiler::AllocatedOperand::cast(input.operand());
  if (operand.IsRegister()) {
    return true;
  }
  DCHECK(operand.IsStackSlot());
  return false;
}
References v8::internal::compiler::LocationOperand::cast(), v8::internal::DCHECK(), v8::internal::compiler::InstructionOperand::IsRegister(), v8::internal::compiler::InstructionOperand::IsStackSlot(), and v8::internal::maglev::ValueLocation::operand().
Referenced by PushAligned().
AlreadyInARegister() [3/3]
bool v8::internal::maglev::detail::AlreadyInARegister (Register reg) [inline]
Definition at line 132 of file maglev-assembler-arm64-inl.h.
{ return true; }
CheckArgs()
template<typename Descriptor , typename... Args>
void v8::internal::maglev::detail::CheckArgs (Args &&... args)
Definition at line 600 of file maglev-assembler-inl.h.
{}
CopyForDeferred() [1/3]
template<typename T >
T v8::internal::maglev::detail::CopyForDeferred (MaglevCompilationInfo * compilation_info, const T & value)
Definition at line 135 of file maglev-assembler-inl.h.
                                                                           {
  return CopyForDeferredHelper<T>::Copy(compilation_info, value);
}
References v8::internal::maglev::detail::CopyForDeferredHelper< T, Enable >::Copy(), and v8::internal::value.
CopyForDeferred() [2/3]
template<typename T >
T v8::internal::maglev::detail::CopyForDeferred (MaglevCompilationInfo * compilation_info, T && value)
Definition at line 124 of file maglev-assembler-inl.h.
                                                                      {
  return CopyForDeferredHelper<T>::Copy(compilation_info,
                                        std::forward<T>(value));
}
References v8::internal::maglev::detail::CopyForDeferredHelper< T, Enable >::Copy(), and v8::internal::value.
Referenced by v8::internal::maglev::MaglevAssembler::MakeDeferredCode().
CopyForDeferred() [3/3]
template<typename T >
T v8::internal::maglev::detail::CopyForDeferred (MaglevCompilationInfo * compilation_info, T & value)
Definition at line 130 of file maglev-assembler-inl.h.
                                                                     {
  return CopyForDeferredHelper<T>::Copy(compilation_info, value);
}
References v8::internal::maglev::detail::CopyForDeferredHelper< T, Enable >::Copy(), and v8::internal::value.
MoveArgumentsForBuiltin()
template<Builtin kBuiltin, typename... Args>
void v8::internal::maglev::detail::MoveArgumentsForBuiltin (MaglevAssembler * masm, Args &&... args)
Definition at line 621 of file maglev-assembler-inl.h.
                                                                    {
  using Descriptor = typename CallInterfaceDescriptorFor<kBuiltin>::type;
  // Put the args into a tuple for easier manipulation.
  std::tuple<Args&&...> args_tuple{std::forward<Args>(args)...};
  // If there is a context, the first argument is the context parameter. Use
  // the remaining args as the actual arguments. We pass the context first
  // instead of last to avoid ambiguity around dealing with on-stack
  // arguments.
  constexpr size_t context_args = Descriptor::HasContextParameter() ? 1 : 0;
  static_assert(context_args <= std::tuple_size_v<decltype(args_tuple)>,
                "Not enough arguments passed in to builtin (are you missing a "
                "context argument?)");
  auto args_tuple_without_context = base::tuple_drop<context_args>(args_tuple);
  CheckArgs<Descriptor>(masm, args_tuple_without_context);
  // Split args into register and stack args.
  static_assert(Descriptor::GetRegisterParameterCount() <=
                    std::tuple_size_v<decltype(args_tuple_without_context)>,
                "Not enough arguments passed in to builtin (are you missing a "
                "context argument?)");
  auto register_args =
      base::tuple_head<Descriptor::GetRegisterParameterCount()>(
          args_tuple_without_context);
  auto stack_args = base::tuple_drop<Descriptor::GetRegisterParameterCount()>(
      args_tuple_without_context);
  // Split stack args into fixed and variable.
  static_assert(
      Descriptor::GetStackParameterCount() <=
          std::tuple_size_v<decltype(stack_args)>,
      "Not enough stack arguments passed in to builtin (are you missing a "
      "context argument?)");
  auto fixed_stack_args =
      base::tuple_head<Descriptor::GetStackParameterCount()>(stack_args);
  auto vararg_stack_args =
      base::tuple_drop<Descriptor::GetStackParameterCount()>(stack_args);
  if constexpr (!Descriptor::AllowVarArgs()) {
    static_assert(std::tuple_size_v<decltype(vararg_stack_args)> == 0,
                  "Too many arguments passed in to builtin that expects no "
                  "vararg stack arguments");
  }
  // First push stack arguments (if any), since some of these may be in
  // registers and we don't want to clobber them. This supports any thing
  // `masm->Push` supports, including iterator ranges, so the tuple size may be
  // smaller than the number of arguments actually pushed. We push fixed and
  // vararg stack arguments separately, so that there's an appropriate amount
  // of padding between them.
  if (Descriptor::kStackArgumentOrder == StackArgumentOrder::kDefault) {
    PushArgumentsForBuiltin<Descriptor>(
        masm, std::forward<decltype(fixed_stack_args)>(fixed_stack_args));
    PushArgumentsForBuiltin<Descriptor>(
        masm, std::forward<decltype(vararg_stack_args)>(vararg_stack_args));
  } else {
    PushArgumentsForBuiltin<Descriptor>(
        masm, std::forward<decltype(vararg_stack_args)>(vararg_stack_args));
    PushArgumentsForBuiltin<Descriptor>(
        masm, std::forward<decltype(fixed_stack_args)>(fixed_stack_args));
  }
// Then, set register arguments.
// TODO(leszeks): Use the parallel move helper to do register moves, instead
// of detecting clobbering.
#ifdef DEBUG
  RegList written_registers = {};
  DoubleRegList written_double_registers = {};
#endif // DEBUG
  base::tuple_for_each_with_index(register_args, [&](auto&& arg, auto index) {
    using Arg = decltype(arg);
    static_assert(index < Descriptor::GetRegisterParameterCount());
    // Make sure the argument wasn't clobbered by any previous write.
    DCHECK(!ClobberedBy(written_registers, arg));
    DCHECK(!ClobberedBy(written_double_registers, arg));
    static constexpr bool use_double_register =
        IsFloatingPoint(Descriptor::GetParameterType(index).representation());
    if constexpr (use_double_register) {
      DoubleRegister target = Descriptor::GetDoubleRegisterParameter(index);
      if constexpr (std::is_same_v<Input, std::decay_t<Arg>>) {
        DCHECK_EQ(target, arg.AssignedDoubleRegister());
        USE(target);
      } else {
        masm->Move(target, std::forward<Arg>(arg));
      }
#ifdef DEBUG
      written_double_registers.set(target);
#endif // DEBUG
    } else {
      Register target = Descriptor::GetRegisterParameter(index);
      if constexpr (std::is_same_v<Input, std::decay_t<Arg>>) {
        DCHECK_EQ(target, arg.AssignedGeneralRegister());
        USE(target);
      } else {
        masm->Move(target, std::forward<Arg>(arg));
      }
#ifdef DEBUG
      written_registers.set(target);
#endif // DEBUG
    }
    // TODO(leszeks): Support iterator range for register args.
  });
  // Set the context last (to avoid clobbering).
  if constexpr (Descriptor::HasContextParameter()) {
    auto&& context = std::get<0>(args_tuple);
    DCHECK(!ClobberedBy(written_registers, context));
    DCHECK(!ClobberedBy(written_double_registers, context));
    DCHECK(MachineTypeMatches(MachineType::AnyTagged(), context));
    if constexpr (std::is_same_v<Input, std::decay_t<decltype(context)>>) {
      DCHECK_EQ(Descriptor::ContextRegister(),
                context.AssignedGeneralRegister());
    } else {
      // Don't allow raw Register here, force materialisation from a constant.
      // This is because setting parameters could have clobbered the register.
      // TODO(leszeks): Include the context register in the parallel moves
      // described above.
      static_assert(!std::is_same_v<Register, std::decay_t<decltype(context)>>);
      masm->Move(Descriptor::ContextRegister(), context);
    }
  }
}
References v8::internal::MachineType::AnyTagged(), v8::base::args, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::index, v8::internal::IsFloatingPoint(), v8::internal::kDefault, v8::internal::maglev::MaglevAssembler::Move(), v8::internal::RegListBase< RegisterT >::set(), v8::base::tuple_for_each_with_index(), and USE.
ObjectPtrBeforeAddress() [1/2]
template<typename T >
constexpr const T* v8::internal::maglev::detail::ObjectPtrBeforeAddress (const void * address) [constexpr]
Definition at line 2062 of file maglev-ir.h.
                                                               {
  const char* address_as_char_ptr = reinterpret_cast<const char*>(address);
  const char* object_ptr_as_char_ptr = address_as_char_ptr - sizeof(T);
  return reinterpret_cast<const T*>(object_ptr_as_char_ptr);
}
References T.
ObjectPtrBeforeAddress() [2/2]
template<typename T >
constexpr T* v8::internal::maglev::detail::ObjectPtrBeforeAddress (void * address) [constexpr]
Definition at line 2055 of file maglev-ir.h.
                                                   {
  char* address_as_char_ptr = reinterpret_cast<char*>(address);
  char* object_ptr_as_char_ptr = address_as_char_ptr - sizeof(T);
  return reinterpret_cast<T*>(object_ptr_as_char_ptr);
}
References T.
PushAligned()
template<typename Arg1 , typename Arg2 >
void v8::internal::maglev::detail::PushAligned (MaglevAssembler * masm, Arg1 arg1, Arg2 arg2) [inline]
Definition at line 260 of file maglev-assembler-arm64-inl.h.
                                                                     {
  if (AlreadyInARegister(arg1) || AlreadyInARegister(arg2)) {
    // If one of the operands is already in a register, there is no need
    // to reuse scratch registers, so two arguments can be pushed together.
    MaglevAssembler::TemporaryRegisterScope temps(masm);
    masm->MacroAssembler::Push(ToRegister(masm, &temps, arg1),
                               ToRegister(masm, &temps, arg2));
    return;
  }
  {
    // Push the first argument together with padding to ensure alignment.
    // The second argument is not pushed together with the first so we can
    // reuse any scratch registers used to materialise the first argument for
    // the second one.
    MaglevAssembler::TemporaryRegisterScope temps(masm);
    masm->MacroAssembler::Push(ToRegister(masm, &temps, arg1), padreg);
  }
  {
    MaglevAssembler::TemporaryRegisterScope temps(masm);
    masm->MacroAssembler::str(ToRegister(masm, &temps, arg2), MemOperand(sp));
  }
}
References AlreadyInARegister(), v8::internal::padreg, and v8::internal::maglev::ToRegister().
Referenced by v8::internal::maglev::detail::PushAllHelper< Arg1, Arg2, Args... >::Push(), and v8::internal::maglev::detail::PushAllHelper< Arg1, Arg2, Args... >::PushReverse().
PushAll()
template<typename... Args>
void v8::internal::maglev::detail::PushAll (MaglevAssembler * masm, Args... args) [inline]
Definition at line 203 of file maglev-assembler-arm64-inl.h.
                                                         {
  PushAllHelper<Args...>::Push(masm, args...);
}
References v8::base::args.
PushAllReverse()
template<typename... Args>
void v8::internal::maglev::detail::PushAllReverse (MaglevAssembler * masm, Args... args) [inline]
Definition at line 208 of file maglev-assembler-arm64-inl.h.
                                                                {
  PushAllHelper<Args...>::PushReverse(masm, args...);
}
References v8::base::args.
Referenced by v8::internal::maglev::detail::PushAllHelper< Arg >::PushReverse(), and v8::internal::maglev::detail::PushAllHelper< Arg1, Arg2, Args... >::PushReverse().
PushArgumentsForBuiltin() [1/2]
template<typename Descriptor , typename... Args>
void v8::internal::maglev::detail::PushArgumentsForBuiltin (MaglevAssembler * masm, std::tuple< Args... > args)
Definition at line 605 of file maglev-assembler-inl.h.
                                                                            {
  std::apply(
      [&](auto&&... stack_args) {
        if (Descriptor::kStackArgumentOrder == StackArgumentOrder::kDefault) {
          masm->Push(std::forward<decltype(stack_args)>(stack_args)...);
        } else {
          masm->PushReverse(std::forward<decltype(stack_args)>(stack_args)...);
        }
      },
      args);
}
References v8::base::args, v8::internal::kDefault, v8::internal::maglev::MaglevAssembler::Push(), and v8::internal::maglev::MaglevAssembler::PushReverse().
PushArgumentsForBuiltin() [2/2]
template<typename Descriptor >
void v8::internal::maglev::detail::PushArgumentsForBuiltin (MaglevAssembler * masm, std::tuple<> empty_args)
Definition at line 618 of file maglev-assembler-inl.h.
{}
PushInput()
void v8::internal::maglev::detail::PushInput (MaglevAssembler * masm, const Input & input) [inline]
Definition at line 128 of file maglev-assembler-arm-inl.h.
                                                                 {
  if (input.operand().IsConstant()) {
    MaglevAssembler::TemporaryRegisterScope temps(masm);
    Register scratch = temps.AcquireScratch();
    input.node()->LoadToRegister(masm, scratch);
    masm->Push(scratch);
  } else {
    // TODO(leszeks): Consider special casing the value. (Toon: could possibly
    // be done through Input directly?)
    const compiler::AllocatedOperand& operand =
        compiler::AllocatedOperand::cast(input.operand());
    if (operand.IsRegister()) {
      masm->Push(operand.GetRegister());
    } else {
      DCHECK(operand.IsStackSlot());
      MaglevAssembler::TemporaryRegisterScope temps(masm);
      Register scratch = temps.AcquireScratch();
      masm->ldr(scratch, masm->GetStackSlot(operand));
      masm->Push(scratch);
    }
  }
}
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), v8::internal::compiler::LocationOperand::cast(), v8::internal::DCHECK(), v8::internal::compiler::LocationOperand::GetRegister(), v8::internal::maglev::MaglevAssembler::GetStackSlot(), v8::internal::compiler::InstructionOperand::IsRegister(), v8::internal::compiler::InstructionOperand::IsStackSlot(), v8::internal::Assembler::ldr(), v8::internal::maglev::ValueNode::LoadToRegister(), v8::internal::maglev::Input::node(), v8::internal::maglev::ValueLocation::operand(), and v8::internal::maglev::MaglevAssembler::Push().
Referenced by v8::internal::maglev::detail::PushAllHelper< Input, Args... >::Push(), and v8::internal::maglev::detail::PushAllHelper< Input, Args... >::PushReverse().
PushIterator()
template<typename T , typename... Args>
void v8::internal::maglev::detail::PushIterator (MaglevAssembler * masm, base::iterator_range< T > range, Args... args) [inline]
Definition at line 152 of file maglev-assembler-arm-inl.h.
                                       {
  for (auto iter = range.begin(), end = range.end(); iter != end; ++iter) {
    masm->Push(*iter);
  }
  PushAllHelper<Args...>::Push(masm, args...);
}
References v8::base::args, v8::base::iterator_range< ForwardIterator >::begin(), v8::base::iterator_range< ForwardIterator >::end(), v8::internal::compiler::end(), and v8::internal::maglev::MaglevAssembler::Push().
Referenced by v8::internal::maglev::detail::PushAllHelper< Arg >::Push(), v8::internal::maglev::detail::PushAllHelper< Arg, Args... >::Push(), and v8::internal::maglev::detail::PushAllHelper< Arg1, Arg2, Args... >::Push().
PushIteratorReverse()
template<typename T , typename... Args>
void v8::internal::maglev::detail::PushIteratorReverse (MaglevAssembler * masm, base::iterator_range< T > range, Args... args) [inline]
Definition at line 161 of file maglev-assembler-arm-inl.h.
                                                                           {
  PushAllHelper<Args...>::PushReverse(masm, args...);
  for (auto iter = range.rbegin(), end = range.rend(); iter != end; ++iter) {
    masm->Push(*iter);
  }
}
References v8::base::args, v8::internal::compiler::end(), v8::internal::maglev::MaglevAssembler::Push(), v8::base::iterator_range< ForwardIterator >::rbegin(), and v8::base::iterator_range< ForwardIterator >::rend().
Referenced by v8::internal::maglev::detail::PushAllHelper< Arg >::PushReverse(), v8::internal::maglev::detail::PushAllHelper< Arg, Args... >::PushReverse(), and v8::internal::maglev::detail::PushAllHelper< Arg1, Arg2, Args... >::PushReverse().
ToRegister() [1/3]
template<typename Arg >
Register v8::internal::maglev::detail::ToRegister (MaglevAssembler * masm, MaglevAssembler::TemporaryRegisterScope * scratch, Arg arg) [inline]
Definition at line 148 of file maglev-assembler-arm64-inl.h.
                                    {
  Register reg = scratch->AcquireScratch();
  masm->Move(reg, arg);
  return reg;
}
References v8::internal::maglev::MaglevAssembler::Move().
ToRegister() [2/3]
Register v8::internal::maglev::detail::ToRegister (MaglevAssembler * masm, MaglevAssembler::TemporaryRegisterScope * scratch, const Input & input) [inline]
Definition at line 160 of file maglev-assembler-arm64-inl.h.
                                               {
  if (input.operand().IsConstant()) {
    Register reg = scratch->AcquireScratch();
    input.node()->LoadToRegister(masm, reg);
    return reg;
  }
  const compiler::AllocatedOperand& operand =
      compiler::AllocatedOperand::cast(input.operand());
  if (operand.IsRegister()) {
    return ToRegister(input);
  } else {
    DCHECK(operand.IsStackSlot());
    Register reg = scratch->AcquireScratch();
    masm->Move(reg, masm->ToMemOperand(input));
    return reg;
  }
}
References v8::internal::compiler::LocationOperand::cast(), v8::internal::DCHECK(), v8::internal::compiler::InstructionOperand::IsRegister(), v8::internal::compiler::InstructionOperand::IsStackSlot(), v8::internal::maglev::ValueNode::LoadToRegister(), v8::internal::maglev::MaglevAssembler::Move(), v8::internal::maglev::Input::node(), v8::internal::maglev::ValueLocation::operand(), v8::internal::maglev::MaglevAssembler::ToMemOperand(), and v8::internal::maglev::ToRegister().
ToRegister() [3/3]
Register v8::internal::maglev::detail::ToRegister (MaglevAssembler * masm, MaglevAssembler::TemporaryRegisterScope * scratch, Register reg) [inline]
Definition at line 155 of file maglev-assembler-arm64-inl.h.
                                         {
  return reg;
}