v8::bigint::anonymous_namespace{mul-toom.cc} Namespace Reference
Functions
void TimesTwo (RWDigits X)
void DivideByTwo (RWDigits X)
void DivideByThree (RWDigits X)
Function Documentation
DivideByThree()
void v8::bigint::anonymous_namespace{mul-toom.cc}::DivideByThree (RWDigits X)
Definition at line 37 of file mul-toom.cc.
                               {
  digit_t remainder = 0;
  for (int i = X.len() - 1; i >= 0; i--) {
    digit_t d = X[i];
    digit_t upper = (remainder << kHalfDigitBits) | (d >> kHalfDigitBits);
    digit_t u_result = upper / 3;
    remainder = upper - 3 * u_result;
    digit_t lower = (remainder << kHalfDigitBits) | (d & kHalfDigitMask);
    digit_t l_result = lower / 3;
    remainder = lower - 3 * l_result;
    X[i] = (u_result << kHalfDigitBits) | l_result;
  }
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::bigint::kHalfDigitBits, v8::bigint::kHalfDigitMask, and X().
DivideByTwo()
void v8::bigint::anonymous_namespace{mul-toom.cc}::DivideByTwo (RWDigits X)
Definition at line 28 of file mul-toom.cc.
                             {
  digit_t carry = 0;
  for (int i = X.len() - 1; i >= 0; i--) {
    digit_t d = X[i];
    X[i] = (d >> 1) | carry;
    carry = d << (kDigitBits - 1);
  }
}
References v8::internal::carry, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::bigint::kDigitBits, and X().
TimesTwo()
void v8::bigint::anonymous_namespace{mul-toom.cc}::TimesTwo (RWDigits X)
Definition at line 19 of file mul-toom.cc.
                          {
  digit_t carry = 0;
  for (int i = 0; i < X.len(); i++) {
    digit_t d = X[i];
    X[i] = (d << 1) | carry;
    carry = d >> (kDigitBits - 1);
  }
}
References v8::internal::carry, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::bigint::kDigitBits, and X().