v8::internal::anonymous_namespace{deoptimizer.cc} Namespace Reference
Classes
class DeoptimizableCodeIterator
class ActivationsFinder
Functions
int LookupCatchHandler (Isolate *isolate, TranslatedFrame *translated_frame, int *data_out)
bool DeoptimizedMaglevvedCodeEarly (Isolate *isolate, Tagged< JSFunction > function, Tagged< Code > code)
Builtin DispatchBuiltinFor (bool advance_bc, bool is_restart_frame)
bool BuiltinContinuationModeIsJavaScript (BuiltinContinuationMode mode)
StackFrame::Type BuiltinContinuationModeToFrameType (BuiltinContinuationMode mode)
Address GetDeoptCallPCFromReturnPC (Address return_pc, Tagged< Code > code)
Function Documentation
BuiltinContinuationModeIsJavaScript()
bool v8::internal::anonymous_namespace{deoptimizer.cc}::BuiltinContinuationModeIsJavaScript (BuiltinContinuationMode mode)
Definition at line 2464 of file deoptimizer.cc.
                                                                       {
  switch (mode) {
    case BuiltinContinuationMode::STUB:
      return false;
    case BuiltinContinuationMode::JAVASCRIPT:
    case BuiltinContinuationMode::JAVASCRIPT_WITH_CATCH:
    case BuiltinContinuationMode::JAVASCRIPT_HANDLE_EXCEPTION:
      return true;
  }
  UNREACHABLE();
}
References v8::internal::JAVASCRIPT, v8::internal::JAVASCRIPT_HANDLE_EXCEPTION, v8::internal::JAVASCRIPT_WITH_CATCH, mode(), v8::internal::STUB, and v8::internal::UNREACHABLE().
Referenced by v8::internal::Deoptimizer::DoComputeBuiltinContinuation().
BuiltinContinuationModeToFrameType()
StackFrame::Type v8::internal::anonymous_namespace{deoptimizer.cc}::BuiltinContinuationModeToFrameType (BuiltinContinuationMode mode)
Definition at line 2476 of file deoptimizer.cc.
                                  {
  switch (mode) {
    case BuiltinContinuationMode::STUB:
      return StackFrame::BUILTIN_CONTINUATION;
    case BuiltinContinuationMode::JAVASCRIPT:
      return StackFrame::JAVASCRIPT_BUILTIN_CONTINUATION;
    case BuiltinContinuationMode::JAVASCRIPT_WITH_CATCH:
      return StackFrame::JAVASCRIPT_BUILTIN_CONTINUATION_WITH_CATCH;
    case BuiltinContinuationMode::JAVASCRIPT_HANDLE_EXCEPTION:
      return StackFrame::JAVASCRIPT_BUILTIN_CONTINUATION_WITH_CATCH;
  }
  UNREACHABLE();
}
References v8::internal::JAVASCRIPT, v8::internal::JAVASCRIPT_HANDLE_EXCEPTION, v8::internal::JAVASCRIPT_WITH_CATCH, mode(), v8::internal::STUB, and v8::internal::UNREACHABLE().
Referenced by v8::internal::Deoptimizer::DoComputeBuiltinContinuation().
DeoptimizedMaglevvedCodeEarly()
bool v8::internal::anonymous_namespace{deoptimizer.cc}::DeoptimizedMaglevvedCodeEarly (Isolate * isolate, Tagged< JSFunction > function, Tagged< Code > code)
Definition at line 1476 of file deoptimizer.cc.
                                                      {
  if (!code->is_maglevved()) return false;
  if (function->GetRequestedOptimizationIfAny(isolate) ==
      CodeKind::TURBOFAN_JS) {
    // We request turbofan after consuming the invocation_count_for_turbofan
    // budget which is greater than
    // invocation_count_for_maglev_with_delay.
    return false;
  }
  int current_invocation_budget =
      function->raw_feedback_cell()->interrupt_budget() /
      function->shared()->GetBytecodeArray(isolate)->length();
  return current_invocation_budget >=
         v8_flags.invocation_count_for_turbofan -
             v8_flags.invocation_count_for_maglev_with_delay;
}
References code, and v8::internal::v8_flags.
Referenced by v8::internal::Deoptimizer::DoComputeOutputFrames().
DispatchBuiltinFor()
Builtin v8::internal::anonymous_namespace{deoptimizer.cc}::DispatchBuiltinFor (bool advance_bc, bool is_restart_frame)
Definition at line 1793 of file deoptimizer.cc.
                                                                   {
  if (is_restart_frame) return Builtin::kRestartFrameTrampoline;
  return advance_bc ? Builtin::kInterpreterEnterAtNextBytecode
                    : Builtin::kInterpreterEnterAtBytecode;
}
Referenced by v8::internal::Deoptimizer::DoComputeUnoptimizedFrame().
GetDeoptCallPCFromReturnPC()
Address v8::internal::anonymous_namespace{deoptimizer.cc}::GetDeoptCallPCFromReturnPC (Address return_pc, Tagged< Code > code)
Definition at line 2991 of file deoptimizer.cc.
                                                                         {
  DCHECK_GT(Deoptimizer::kEagerDeoptExitSize, 0);
  DCHECK_GT(Deoptimizer::kLazyDeoptExitSize, 0);
  Tagged<DeoptimizationData> deopt_data =
      Cast<DeoptimizationData>(code->deoptimization_data());
  Address deopt_start =
      code->instruction_start() + deopt_data->DeoptExitStart().value();
  int eager_deopt_count = deopt_data->EagerDeoptCount().value();
  Address lazy_deopt_start =
      deopt_start + eager_deopt_count * Deoptimizer::kEagerDeoptExitSize;
  // The deoptimization exits are sorted so that lazy deopt exits appear
  // after eager deopts.
  static_assert(static_cast<int>(DeoptimizeKind::kLazy) ==
                    static_cast<int>(kLastDeoptimizeKind),
                "lazy deopts are expected to be emitted last");
  if (return_pc <= lazy_deopt_start) {
    return return_pc - Deoptimizer::kEagerDeoptExitSize;
  } else {
    return return_pc - Deoptimizer::kLazyDeoptExitSize;
  }
}
References code, DCHECK_GT, v8::internal::Deoptimizer::kEagerDeoptExitSize, v8::internal::kLastDeoptimizeKind, v8::internal::kLazy, and v8::internal::Deoptimizer::kLazyDeoptExitSize.
Referenced by v8::internal::Deoptimizer::ComputeInputFrameSize().
LookupCatchHandler()
int v8::internal::anonymous_namespace{deoptimizer.cc}::LookupCatchHandler (Isolate * isolate, TranslatedFrame * translated_frame, int * data_out)
Definition at line 799 of file deoptimizer.cc.
                                      {
  switch (translated_frame->kind()) {
    case TranslatedFrame::kUnoptimizedFunction: {
      int bytecode_offset = translated_frame->bytecode_offset().ToInt();
      HandlerTable table(
          translated_frame->raw_shared_info()->GetBytecodeArray(isolate));
      int handler_index = table.LookupHandlerIndexForRange(bytecode_offset);
      if (handler_index == HandlerTable::kNoHandlerFound) return handler_index;
      *data_out = table.GetRangeData(handler_index);
      table.MarkHandlerUsed(handler_index);
      return table.GetRangeHandler(handler_index);
    }
    case TranslatedFrame::kJavaScriptBuiltinContinuationWithCatch: {
      return 0;
    }
    default:
      break;
  }
  return -1;
}
References v8::internal::TranslatedFrame::bytecode_offset(), v8::internal::HandlerTable::GetRangeData(), v8::internal::HandlerTable::GetRangeHandler(), v8::internal::TranslatedFrame::kind(), v8::internal::TranslatedFrame::kJavaScriptBuiltinContinuationWithCatch, v8::internal::HandlerTable::kNoHandlerFound, v8::internal::TranslatedFrame::kUnoptimizedFunction, v8::internal::HandlerTable::LookupHandlerIndexForRange(), v8::internal::HandlerTable::MarkHandlerUsed(), v8::internal::TranslatedFrame::raw_shared_info(), and v8::internal::BytecodeOffset::ToInt().
Referenced by v8::internal::Deoptimizer::DoComputeOutputFrames().