v8::internal::anonymous_namespace{isolate.cc} Namespace Reference
Classes
class CallSiteBuilder
class StackFrameBuilder
class CurrentScriptNameStackVisitor
class CurrentScriptStackVisitor
class StackFrameSummaryIterator
class BigIntPlatform
Typedefs
using MapOfLoadsAndStoresPerFunction = std::map< std::string, std::pair< uint64_t, uint64_t > >
Enumerations
enum PromiseMethod { kThen
, kCatch
, kFinally
, kInvalid
 }
Functions
std::atomic< const uint8_t * > current_embedded_blob_code_ (nullptr)
std::atomic< uint32_t > current_embedded_blob_code_size_ (0)
std::atomic< const uint8_t * > current_embedded_blob_data_ (nullptr)
std::atomic< uint32_t > current_embedded_blob_data_size_ (0)
const uint8_t * StickyEmbeddedBlobCode ()
uint32_t StickyEmbeddedBlobCodeSize ()
const uint8_t * StickyEmbeddedBlobData ()
uint32_t StickyEmbeddedBlobDataSize ()
void SetStickyEmbeddedBlob (const uint8_t *code, uint32_t code_size, const uint8_t *data, uint32_t data_size)
bool IsBuiltinFunction (Isolate *isolate, Tagged< HeapObject > object, Builtin builtin)
bool IsBuiltinAsyncFulfillHandler (Isolate *isolate, Tagged< HeapObject > object)
bool IsBuiltinAsyncRejectHandler (Isolate *isolate, Tagged< HeapObject > object)
bool IsBuiltinForwardingRejectHandler (Isolate *isolate, Tagged< HeapObject > object)
MaybeHandle< JSGeneratorObject > TryGetAsyncGenerator (Isolate *isolate, DirectHandle< PromiseReaction > reaction)
int GetGeneratorBytecodeOffset (DirectHandle< JSGeneratorObject > generator_object)
void CaptureAsyncStackTrace (Isolate *isolate, DirectHandle< JSPromise > promise, CallSiteBuilder *builder)
MaybeDirectHandle< JSPromise > TryGetCurrentTaskPromise (Isolate *isolate)
void CaptureAsyncStackTrace (Isolate *isolate, CallSiteBuilder *builder)
template<typename Visitor >
void VisitStack (Isolate *isolate, Visitor *visitor, StackTrace::StackTraceOptions options=StackTrace::kDetailed)
Handle< FixedArray > CaptureSimpleStackTrace (Isolate *isolate, int limit, FrameSkipMode mode, Handle< Object > caller)
DirectHandle< StackTraceInfo > GetDetailedStackTraceFromCallSiteInfos (Isolate *isolate, DirectHandle< FixedArray > call_site_infos, int limit)
void ReportBootstrappingException (DirectHandle< Object > exception, MessageLocation *location)
HandlerTable::CatchPrediction CatchPredictionFor (Builtin builtin_id)
HandlerTable::CatchPrediction PredictExceptionFromBytecode (Tagged< BytecodeArray > bytecode, int code_offset)
HandlerTable::CatchPrediction PredictException (const FrameSummary &summary, Isolate *isolate)
HandlerTable::CatchPrediction PredictExceptionFromGenerator (DirectHandle< JSGeneratorObject > generator, Isolate *isolate)
Isolate::CatchType ToCatchType (HandlerTable::CatchPrediction prediction)
Isolate::CatchType PredictExceptionCatchAtFrame (const StackFrameSummaryIterator &iterator)
bool ReceiverIsForwardingHandler (Isolate *isolate, DirectHandle< JSReceiver > handler)
bool WalkPromiseTreeInternal (Isolate *isolate, DirectHandle< JSPromise > promise, const std::function< void(Isolate::PromiseHandler)> &callback)
PromiseMethod GetPromiseMethod (Isolate *isolate, const interpreter::BytecodeArrayIterator &iterator)
bool TouchesRegister (const interpreter::BytecodeArrayIterator &iterator, int index)
bool CallsCatchMethod (Isolate *isolate, Handle< BytecodeArray > bytecode_array, int offset)
bool CallsCatchMethod (const StackFrameSummaryIterator &iterator)
Tagged< FunctionTemplateInfo > GetTargetFunctionTemplateInfo (const v8::FunctionCallbackInfo< v8::Value > &info)
void FinalizeBuiltinCodeObjects (Isolate *isolate)
static std::string ToHexString (uintptr_t address)
MaybeDirectHandle< JSPromise > NewRejectedPromise (Isolate *isolate, v8::Local< v8::Context > api_context, DirectHandle< Object > exception)
Variables
base::LazyMutex current_embedded_blob_refcount_mutex_ = LAZY_MUTEX_INITIALIZER
const uint8_t * sticky_embedded_blob_code_ = nullptr
uint32_t sticky_embedded_blob_code_size_ = 0
const uint8_t * sticky_embedded_blob_data_ = nullptr
uint32_t sticky_embedded_blob_data_size_ = 0
bool enable_embedded_blob_refcounting_ = true
int current_embedded_blob_refs_ = 0
std::atomic< int > isolate_counter {0}
MapOfLoadsAndStoresPerFunction * stack_access_count_map = nullptr
base::LazyMutex print_with_timestamp_mutex_ = LAZY_MUTEX_INITIALIZER
Typedef Documentation
MapOfLoadsAndStoresPerFunction
using v8::internal::anonymous_namespace{isolate.cc}::MapOfLoadsAndStoresPerFunction = typedef std::map<std::string , std::pair<uint64_t , uint64_t > >
Definition at line 5390 of file isolate.cc.
Enumeration Type Documentation
PromiseMethod
enum v8::internal::anonymous_namespace{isolate.cc}::PromiseMethod
Enumerator
kThen
kCatch
kFinally
kInvalid
Definition at line 3334 of file isolate.cc.
{ kThen, kCatch, kFinally, kInvalid };
Function Documentation
CallsCatchMethod() [1/2]
bool v8::internal::anonymous_namespace{isolate.cc}::CallsCatchMethod (const StackFrameSummaryIterator & iterator)
Definition at line 3538 of file isolate.cc.
                                                                 {
  if (!iterator.frame()->is_javascript()) {
    return false;
  }
  if (iterator.frame_summary().IsJavaScript()) {
    auto& js_summary = iterator.frame_summary().AsJavaScript();
    if (IsBytecodeArray(*js_summary.abstract_code())) {
      if (CallsCatchMethod(iterator.isolate(),
                           Cast<BytecodeArray>(js_summary.abstract_code()),
                           js_summary.code_offset())) {
        return true;
      }
    }
  }
  return false;
}
References v8::internal::anonymous_namespace{isolate.cc}::StackFrameSummaryIterator::frame(), v8::internal::anonymous_namespace{isolate.cc}::StackFrameSummaryIterator::frame_summary(), v8::internal::StackFrame::is_javascript(), and v8::internal::anonymous_namespace{isolate.cc}::StackFrameSummaryIterator::isolate().
Referenced by v8::internal::Isolate::WalkCallStackAndPromiseTree().
CallsCatchMethod() [2/2]
bool v8::internal::anonymous_namespace{isolate.cc}::CallsCatchMethod (Isolate * isolate, Handle< BytecodeArray > bytecode_array, int offset)
Definition at line 3386 of file isolate.cc.
                                  {
  interpreter::BytecodeArrayIterator iterator(bytecode_array, offset);
  while (!iterator.done()) {
    // We should be on a call instruction of some kind. While we could check
    // this, it may be difficult to create an exhaustive list of instructions
    // that could call, such as property getters, but at a minimum this
    // instruction should write to the accumulator.
    if (!Bytecodes::WritesAccumulator(iterator.current_bytecode())) {
      return false;
    }
    iterator.Advance();
    // While usually the next instruction is a Star, sometimes we store and
    // reload from context first.
    if (iterator.done()) {
      return false;
    }
    if (iterator.current_bytecode() == Bytecode::kStaCurrentContextSlot ||
        iterator.current_bytecode() == Bytecode::kStaCurrentContextSlotNoCell) {
      // Step over patterns like:
      // StaCurrentContextSlot[NoCell] [x]
      // LdaImmutableCurrentContextSlot/LdaCurrentContext[NoCell] [x]
      unsigned int slot = iterator.GetIndexOperand(0);
      iterator.Advance();
      if (!iterator.done() &&
          (iterator.current_bytecode() ==
               Bytecode::kLdaImmutableCurrentContextSlot ||
           iterator.current_bytecode() == Bytecode::kLdaCurrentContextSlot ||
           iterator.current_bytecode() ==
               Bytecode::kLdaCurrentContextSlotNoCell)) {
        if (iterator.GetIndexOperand(0) != slot) {
          return false;
        }
        iterator.Advance();
      }
    } else if (iterator.current_bytecode() == Bytecode::kStaContextSlot ||
               iterator.current_bytecode() == Bytecode::kStaContextSlotNoCell) {
      // Step over patterns like:
      // StaContextSlot[NoCell] r_x [y] [z]
      // LdaContextSlot[NoCell] r_x [y] [z]
      int context = iterator.GetRegisterOperand(0).index();
      unsigned int slot = iterator.GetIndexOperand(1);
      unsigned int depth = iterator.GetUnsignedImmediateOperand(2);
      iterator.Advance();
      if (!iterator.done() &&
          (iterator.current_bytecode() == Bytecode::kLdaImmutableContextSlot ||
           iterator.current_bytecode() == Bytecode::kLdaContextSlot ||
           iterator.current_bytecode() == Bytecode::kLdaContextSlotNoCell)) {
        if (iterator.GetRegisterOperand(0).index() != context ||
            iterator.GetIndexOperand(1) != slot ||
            iterator.GetUnsignedImmediateOperand(2) != depth) {
          return false;
        }
        iterator.Advance();
      }
    } else if (iterator.current_bytecode() == Bytecode::kStaLookupSlot) {
      // Step over patterns like:
      // StaLookupSlot [x] [_]
      // LdaLookupSlot [x]
      unsigned int slot = iterator.GetIndexOperand(0);
      iterator.Advance();
      if (!iterator.done() &&
          (iterator.current_bytecode() == Bytecode::kLdaLookupSlot ||
           iterator.current_bytecode() ==
               Bytecode::kLdaLookupSlotInsideTypeof)) {
        if (iterator.GetIndexOperand(0) != slot) {
          return false;
        }
        iterator.Advance();
      }
    }
    // Next instruction should be a Star (store accumulator to register)
    if (iterator.done() || !Bytecodes::IsAnyStar(iterator.current_bytecode())) {
      return false;
    }
    // The register it stores to will be assumed to be our promise
    int promise_register = iterator.GetStarTargetRegister().index();
    // TODO(crbug/40283993): Should we loop over non-matching instructions here
    // to allow code like
    // `const promise = foo(); console.log(...); promise.catch(...);`?
    iterator.Advance();
    // We should be on a GetNamedProperty instruction.
    if (iterator.done() ||
        iterator.current_bytecode() != Bytecode::kGetNamedProperty ||
        iterator.GetRegisterOperand(0).index() != promise_register) {
      return false;
    }
    PromiseMethod method = GetPromiseMethod(isolate, iterator);
    if (method == kInvalid) {
      return false;
    }
    iterator.Advance();
    // Next instruction should be a Star (save immediate to register)
    if (iterator.done() || !Bytecodes::IsAnyStar(iterator.current_bytecode())) {
      return false;
    }
    // This register contains the method we will eventually invoke
    int method_register = iterator.GetStarTargetRegister().index();
    if (method_register == promise_register) {
      return false;
    }
    // Now we step over multiple instructions creating the arguments for the
    // method.
    while (true) {
      iterator.Advance();
      if (iterator.done()) {
        return false;
      }
      Bytecode bytecode = iterator.current_bytecode();
      if (bytecode == Bytecode::kCallProperty1 ||
          bytecode == Bytecode::kCallProperty2) {
        // This is a call property call of the right size, but is it a call of
        // the method and on the promise?
        if (iterator.GetRegisterOperand(0).index() == method_register &&
            iterator.GetRegisterOperand(1).index() == promise_register) {
          // This is our method call, but does it catch?
          if (method == kCatch ||
              (method == kThen && bytecode == Bytecode::kCallProperty2)) {
            return true;
          }
          // Break out of the inner loop, continuing the outer loop. We
          // will use the same procedure to check for chained method calls.
          break;
        }
      }
      // Check for some instructions that should make us give up scanning.
      if (Bytecodes::IsJump(bytecode) || Bytecodes::IsSwitch(bytecode) ||
          Bytecodes::Returns(bytecode) ||
          Bytecodes::UnconditionallyThrows(bytecode)) {
        // Stop scanning at control flow instructions that aren't calls
        return false;
      }
      if (TouchesRegister(iterator, promise_register) ||
          TouchesRegister(iterator, method_register)) {
        // Stop scanning at instruction that unexpectedly interacts with one of
        // the registers we care about.
        return false;
      }
    }
  }
  return false;
}
References v8::internal::interpreter::BytecodeArrayIterator::Advance(), v8::internal::Isolate::context(), v8::internal::interpreter::BytecodeArrayIterator::current_bytecode(), v8::internal::interpreter::BytecodeArrayIterator::done(), v8::internal::interpreter::BytecodeArrayIterator::GetIndexOperand(), GetPromiseMethod(), v8::internal::interpreter::BytecodeArrayIterator::GetRegisterOperand(), v8::internal::interpreter::BytecodeArrayIterator::GetStarTargetRegister(), v8::internal::interpreter::BytecodeArrayIterator::GetUnsignedImmediateOperand(), v8::internal::interpreter::Register::index(), v8::internal::Factory::isolate(), kCatch, kInvalid, kThen, and TouchesRegister().
CaptureAsyncStackTrace() [1/2]
void v8::internal::anonymous_namespace{isolate.cc}::CaptureAsyncStackTrace (Isolate * isolate, CallSiteBuilder * builder)
Definition at line 1331 of file isolate.cc.
                                                                        {
  DirectHandle<JSPromise> promise;
  if (TryGetCurrentTaskPromise(isolate).ToHandle(&promise)) {
    CaptureAsyncStackTrace(isolate, promise, builder);
  }
}
References v8::anonymous_namespace{api.cc}::ToHandle(), and TryGetCurrentTaskPromise().
Referenced by CaptureSimpleStackTrace().
CaptureAsyncStackTrace() [2/2]
void v8::internal::anonymous_namespace{isolate.cc}::CaptureAsyncStackTrace (Isolate * isolate, DirectHandle< JSPromise > promise, CallSiteBuilder * builder)
Definition at line 1131 of file isolate.cc.
                                                      {
  while (!builder->Full()) {
    // Check that the {promise} is not settled.
    if (promise->status() != Promise::kPending) return;
    // Check that we have exactly one PromiseReaction on the {promise}.
    if (!IsPromiseReaction(promise->reactions())) return;
    DirectHandle<PromiseReaction> reaction(
        Cast<PromiseReaction>(promise->reactions()), isolate);
    if (!IsSmi(reaction->next())) return;
    Handle<JSGeneratorObject> generator_object;
    if (TryGetAsyncGenerator(isolate, reaction).ToHandle(&generator_object)) {
      CHECK(generator_object->is_suspended());
      // Append async frame corresponding to the {generator_object}.
      builder->AppendAsyncFrame(generator_object);
      // Try to continue from here.
      if (IsJSAsyncFunctionObject(*generator_object)) {
        auto async_function_object =
            Cast<JSAsyncFunctionObject>(generator_object);
        promise = direct_handle(async_function_object->promise(), isolate);
      } else {
        auto async_generator_object =
            Cast<JSAsyncGeneratorObject>(generator_object);
        if (IsUndefined(async_generator_object->queue(), isolate)) return;
        DirectHandle<AsyncGeneratorRequest> async_generator_request(
            Cast<AsyncGeneratorRequest>(async_generator_object->queue()),
            isolate);
        promise = direct_handle(
            Cast<JSPromise>(async_generator_request->promise()), isolate);
      }
    } else if (IsBuiltinFunction(isolate, reaction->fulfill_handler(),
                                 Builtin::kPromiseAllResolveElementClosure)) {
      DirectHandle<JSFunction> function(
          Cast<JSFunction>(reaction->fulfill_handler()), isolate);
      DirectHandle<Context> context(function->context(), isolate);
      DirectHandle<JSFunction> combinator(
          context->native_context()->promise_all(), isolate);
      builder->AppendPromiseCombinatorFrame(function, combinator);
      if (IsNativeContext(*context)) {
        // NativeContext is used as a marker that the closure was already
        // called. We can't access the reject element context any more.
        return;
      }
      // Now peek into the Promise.all() resolve element context to
      // find the promise capability that's being resolved when all
      // the concurrent promises resolve.
      int const index =
          PromiseBuiltins::kPromiseAllResolveElementCapabilitySlot;
      DirectHandle<PromiseCapability> capability(
          Cast<PromiseCapability>(context->GetNoCell(index)), isolate);
      if (!IsJSPromise(capability->promise())) return;
      promise = direct_handle(Cast<JSPromise>(capability->promise()), isolate);
    } else if (IsBuiltinFunction(
                   isolate, reaction->fulfill_handler(),
                   Builtin::kPromiseAllSettledResolveElementClosure)) {
      DirectHandle<JSFunction> function(
          Cast<JSFunction>(reaction->fulfill_handler()), isolate);
      DirectHandle<Context> context(function->context(), isolate);
      DirectHandle<JSFunction> combinator(
          context->native_context()->promise_all_settled(), isolate);
      builder->AppendPromiseCombinatorFrame(function, combinator);
      if (IsNativeContext(*context)) {
        // NativeContext is used as a marker that the closure was already
        // called. We can't access the reject element context any more.
        return;
      }
      // Now peek into the Promise.allSettled() resolve element context to
      // find the promise capability that's being resolved when all
      // the concurrent promises resolve.
      int const index =
          PromiseBuiltins::kPromiseAllResolveElementCapabilitySlot;
      DirectHandle<PromiseCapability> capability(
          Cast<PromiseCapability>(context->GetNoCell(index)), isolate);
      if (!IsJSPromise(capability->promise())) return;
      promise = direct_handle(Cast<JSPromise>(capability->promise()), isolate);
    } else if (IsBuiltinFunction(isolate, reaction->reject_handler(),
                                 Builtin::kPromiseAnyRejectElementClosure)) {
      DirectHandle<JSFunction> function(
          Cast<JSFunction>(reaction->reject_handler()), isolate);
      DirectHandle<Context> context(function->context(), isolate);
      DirectHandle<JSFunction> combinator(
          context->native_context()->promise_any(), isolate);
      builder->AppendPromiseCombinatorFrame(function, combinator);
      if (IsNativeContext(*context)) {
        // NativeContext is used as a marker that the closure was already
        // called. We can't access the reject element context any more.
        return;
      }
      // Now peek into the Promise.any() reject element context to
      // find the promise capability that's being resolved when any of
      // the concurrent promises resolve.
      int const index = PromiseBuiltins::kPromiseAnyRejectElementCapabilitySlot;
      DirectHandle<PromiseCapability> capability(
          Cast<PromiseCapability>(context->GetNoCell(index)), isolate);
      if (!IsJSPromise(capability->promise())) return;
      promise = direct_handle(Cast<JSPromise>(capability->promise()), isolate);
    } else if (IsBuiltinFunction(isolate, reaction->fulfill_handler(),
                                 Builtin::kPromiseCapabilityDefaultResolve)) {
      DirectHandle<JSFunction> function(
          Cast<JSFunction>(reaction->fulfill_handler()), isolate);
      DirectHandle<Context> context(function->context(), isolate);
      promise = direct_handle(
          Cast<JSPromise>(context->GetNoCell(PromiseBuiltins::kPromiseSlot)),
          isolate);
    } else {
      // We have some generic promise chain here, so try to
      // continue with the chained promise on the reaction
      // (only works for native promise chains).
      Handle<HeapObject> promise_or_capability(
          reaction->promise_or_capability(), isolate);
      if (IsJSPromise(*promise_or_capability)) {
        promise = Cast<JSPromise>(promise_or_capability);
      } else if (IsPromiseCapability(*promise_or_capability)) {
        auto capability = Cast<PromiseCapability>(promise_or_capability);
        if (!IsJSPromise(capability->promise())) return;
        promise =
            direct_handle(Cast<JSPromise>(capability->promise()), isolate);
      } else {
        // Otherwise the {promise_or_capability} must be undefined here.
        CHECK(IsUndefined(*promise_or_capability, isolate));
        return;
      }
    }
  }
}
References v8::internal::anonymous_namespace{isolate.cc}::CallSiteBuilder::AppendAsyncFrame(), v8::internal::anonymous_namespace{isolate.cc}::CallSiteBuilder::AppendPromiseCombinatorFrame(), CHECK, v8::internal::direct_handle(), v8::internal::anonymous_namespace{isolate.cc}::CallSiteBuilder::Full(), v8::internal::index, IsBuiltinFunction(), v8::internal::IsSmi(), v8::Promise::kPending, v8::internal::PromiseBuiltins::kPromiseAllResolveElementCapabilitySlot, v8::internal::PromiseBuiltins::kPromiseAnyRejectElementCapabilitySlot, v8::internal::PromiseBuiltins::kPromiseSlot, v8::anonymous_namespace{api.cc}::ToHandle(), and TryGetAsyncGenerator().
CaptureSimpleStackTrace()
Handle<FixedArray> v8::internal::anonymous_namespace{isolate.cc}::CaptureSimpleStackTrace (Isolate * isolate, int limit, FrameSkipMode mode, Handle< Object > caller)
Definition at line 1394 of file isolate.cc.
                                                                  {
  TRACE_EVENT_BEGIN1(TRACE_DISABLED_BY_DEFAULT("v8.stack_trace"), __func__,
                     "maxFrameCount", limit);
#if V8_ENABLE_WEBASSEMBLY
  wasm::WasmCodeRefScope code_ref_scope;
#endif // V8_ENABLE_WEBASSEMBLY
  CallSiteBuilder builder(isolate, mode, limit, caller);
  VisitStack(isolate, &builder);
  // If --async-stack-traces are enabled and the "current microtask" is a
  // PromiseReactionJobTask, we try to enrich the stack trace with async
  // frames.
  if (v8_flags.async_stack_traces) {
    CaptureAsyncStackTrace(isolate, &builder);
  }
  Handle<FixedArray> stack_trace = builder.Build();
  TRACE_EVENT_END1(TRACE_DISABLED_BY_DEFAULT("v8.stack_trace"), __func__,
                   "frameCount", stack_trace->length());
  return stack_trace;
}
References v8::internal::anonymous_namespace{isolate.cc}::CallSiteBuilder::Build(), CaptureAsyncStackTrace(), mode(), TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT_BEGIN1, TRACE_EVENT_END1, v8::internal::v8_flags, and VisitStack().
Referenced by v8::internal::Isolate::CaptureAndSetErrorStack(), and v8::internal::Isolate::PrintCurrentStackTrace().
CatchPredictionFor()
HandlerTable::CatchPrediction v8::internal::anonymous_namespace{isolate.cc}::CatchPredictionFor (Builtin builtin_id)
Definition at line 2787 of file isolate.cc.
                                                                   {
  switch (builtin_id) {
#define CASE(Name) \
  case Builtin::k##Name: \
    return HandlerTable::PROMISE;
    BUILTIN_PROMISE_REJECTION_PREDICTION_LIST(CASE)
#undef CASE
    default:
      return HandlerTable::UNCAUGHT;
  }
}
References BUILTIN_PROMISE_REJECTION_PREDICTION_LIST, CASE, and v8::internal::HandlerTable::UNCAUGHT.
Referenced by PredictException(), and PredictExceptionCatchAtFrame().
current_embedded_blob_code_()
std::atomic<const uint8_t*> v8::internal::anonymous_namespace{isolate.cc}::current_embedded_blob_code_ (nullptr)
Referenced by v8::internal::Isolate::ClearEmbeddedBlob(), v8::internal::Isolate::CurrentEmbeddedBlobCode(), v8::internal::Isolate::CurrentEmbeddedBlobIsBinaryEmbedded(), v8::internal::FreeCurrentEmbeddedBlob(), and v8::internal::Isolate::SetEmbeddedBlob().
current_embedded_blob_code_size_()
std::atomic<uint32_t> v8::internal::anonymous_namespace{isolate.cc}::current_embedded_blob_code_size_ (0)
Referenced by v8::internal::Isolate::ClearEmbeddedBlob(), v8::internal::Isolate::CurrentEmbeddedBlobCodeSize(), v8::internal::FreeCurrentEmbeddedBlob(), and v8::internal::Isolate::SetEmbeddedBlob().
current_embedded_blob_data_()
std::atomic<const uint8_t*> v8::internal::anonymous_namespace{isolate.cc}::current_embedded_blob_data_ (nullptr)
Referenced by v8::internal::Isolate::ClearEmbeddedBlob(), v8::internal::Isolate::CurrentEmbeddedBlobData(), v8::internal::FreeCurrentEmbeddedBlob(), and v8::internal::Isolate::SetEmbeddedBlob().
current_embedded_blob_data_size_()
std::atomic<uint32_t> v8::internal::anonymous_namespace{isolate.cc}::current_embedded_blob_data_size_ (0)
Referenced by v8::internal::Isolate::ClearEmbeddedBlob(), v8::internal::Isolate::CurrentEmbeddedBlobDataSize(), v8::internal::FreeCurrentEmbeddedBlob(), and v8::internal::Isolate::SetEmbeddedBlob().
FinalizeBuiltinCodeObjects()
void v8::internal::anonymous_namespace{isolate.cc}::FinalizeBuiltinCodeObjects (Isolate * isolate)
Definition at line 5145 of file isolate.cc.
                                                  {
  DCHECK_NOT_NULL(isolate->embedded_blob_code());
  DCHECK_NE(0, isolate->embedded_blob_code_size());
  DCHECK_NOT_NULL(isolate->embedded_blob_data());
  DCHECK_NE(0, isolate->embedded_blob_data_size());
  EmbeddedData d = EmbeddedData::FromBlob(isolate);
  HandleScope scope(isolate);
  static_assert(Builtins::kAllBuiltinsAreIsolateIndependent);
  for (Builtin builtin = Builtins::kFirst; builtin <= Builtins::kLast;
       ++builtin) {
    DirectHandle<Code> old_code = isolate->builtins()->code_handle(builtin);
    // Note that `old_code.instruction_start` might point to `old_code`'s
    // InstructionStream which might be GCed once we replace the old code
    // with the new code.
    Address instruction_start = d.InstructionStartOf(builtin);
    DirectHandle<Code> new_code =
        isolate->factory()->NewCodeObjectForEmbeddedBuiltin(old_code,
                                                            instruction_start);
    // From this point onwards, the old builtin code object is unreachable and
    // will be collected by the next GC.
    isolate->builtins()->set_code(builtin, *new_code);
  }
}
References v8::internal::Isolate::builtins(), v8::internal::Builtins::code_handle(), DCHECK_NE, DCHECK_NOT_NULL, v8::internal::Isolate::embedded_blob_code(), v8::internal::Isolate::embedded_blob_code_size(), v8::internal::Isolate::embedded_blob_data(), v8::internal::Isolate::embedded_blob_data_size(), v8::internal::Isolate::factory(), v8::internal::EmbeddedData::FromBlob(), v8::internal::EmbeddedData::InstructionStartOf(), v8::internal::Builtins::kAllBuiltinsAreIsolateIndependent, v8::internal::Builtins::kFirst, v8::internal::Builtins::kLast, v8::internal::Factory::NewCodeObjectForEmbeddedBuiltin(), and v8::internal::Builtins::set_code().
Referenced by v8::internal::Isolate::CreateAndSetEmbeddedBlob().
GetDetailedStackTraceFromCallSiteInfos()
DirectHandle<StackTraceInfo> v8::internal::anonymous_namespace{isolate.cc}::GetDetailedStackTraceFromCallSiteInfos (Isolate * isolate, DirectHandle< FixedArray > call_site_infos, int limit)
Definition at line 1420 of file isolate.cc.
                                                                           {
  auto frames = isolate->factory()->NewFixedArray(
      std::min(limit, call_site_infos->length()));
  int index = 0;
  for (int i = 0; i < call_site_infos->length() && index < limit; ++i) {
    DirectHandle<CallSiteInfo> call_site_info(
        Cast<CallSiteInfo>(call_site_infos->get(i)), isolate);
    if (call_site_info->IsAsync()) {
      break;
    }
    DirectHandle<Script> script;
    if (!CallSiteInfo::GetScript(isolate, call_site_info).ToHandle(&script) ||
        !script->IsSubjectToDebugging()) {
      continue;
    }
    DirectHandle<StackFrameInfo> stack_frame_info =
        isolate->factory()->NewStackFrameInfo(
            script, CallSiteInfo::GetSourcePosition(call_site_info),
            CallSiteInfo::GetFunctionDebugName(call_site_info),
            IsConstructor(*call_site_info));
    frames->set(index++, *stack_frame_info);
  }
  frames = FixedArray::RightTrimOrEmpty(isolate, frames, index);
  return isolate->factory()->NewStackTraceInfo(frames);
}
References v8::internal::Isolate::factory(), v8::internal::CallSiteInfo::GetFunctionDebugName(), v8::internal::CallSiteInfo::GetScript(), v8::internal::CallSiteInfo::GetSourcePosition(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::Factory::NewStackFrameInfo(), v8::internal::Factory::NewStackTraceInfo(), v8::internal::script, and v8::anonymous_namespace{api.cc}::ToHandle().
Referenced by v8::internal::Isolate::CaptureAndSetErrorStack().
GetGeneratorBytecodeOffset()
int v8::internal::anonymous_namespace{isolate.cc}::GetGeneratorBytecodeOffset (DirectHandle< JSGeneratorObject > generator_object)
Definition at line 849 of file isolate.cc.
                                                      {
  // The stored bytecode offset is relative to a different base than what
  // is used in the source position table, hence the subtraction.
  return Smi::ToInt(generator_object->input_or_debug_pos()) -
         (BytecodeArray::kHeaderSize - kHeapObjectTag);
}
References v8::internal::ExposedTrustedObject::kHeaderSize, v8::internal::kHeapObjectTag, and v8::internal::Smi::ToInt().
Referenced by v8::internal::anonymous_namespace{isolate.cc}::CallSiteBuilder::AppendAsyncFrame(), and PredictExceptionFromGenerator().
GetPromiseMethod()
PromiseMethod v8::internal::anonymous_namespace{isolate.cc}::GetPromiseMethod (Isolate * isolate, const interpreter::BytecodeArrayIterator & iterator)
Definition at line 3337 of file isolate.cc.
                                                                        {
  DirectHandle<Object> object = iterator.GetConstantForIndexOperand(1, isolate);
  if (!IsString(*object)) {
    return kInvalid;
  }
  auto str = Cast<String>(object);
  if (str->Equals(ReadOnlyRoots(isolate).then_string())) {
    return kThen;
  } else if (str->IsEqualTo(base::StaticCharVector("catch"))) {
    return kCatch;
  } else if (str->IsEqualTo(base::StaticCharVector("finally"))) {
    return kFinally;
  } else {
    return kInvalid;
  }
}
References v8::internal::interpreter::BytecodeArrayIterator::GetConstantForIndexOperand(), v8::internal::Factory::isolate(), kCatch, kFinally, kInvalid, kThen, and v8::base::StaticCharVector().
Referenced by CallsCatchMethod().
GetTargetFunctionTemplateInfo()
Tagged<FunctionTemplateInfo> v8::internal::anonymous_namespace{isolate.cc}::GetTargetFunctionTemplateInfo (const v8::FunctionCallbackInfo< v8::Value > & info) [inline]
Definition at line 4890 of file isolate.cc.
                                                 {
  Tagged<Object> target = FunctionCallbackArguments::GetTarget(info);
  if (IsFunctionTemplateInfo(target)) {
    return Cast<FunctionTemplateInfo>(target);
  }
  CHECK(Is<JSFunction>(target));
  Tagged<SharedFunctionInfo> shared_info = Cast<JSFunction>(target)->shared();
  return shared_info->api_func_data();
}
References CHECK, and v8::internal::FunctionCallbackArguments::GetTarget().
Referenced by v8::internal::Isolate::NotifyExceptionPropagationCallback().
IsBuiltinAsyncFulfillHandler()
bool v8::internal::anonymous_namespace{isolate.cc}::IsBuiltinAsyncFulfillHandler (Isolate * isolate, Tagged< HeapObject > object)
Definition at line 789 of file isolate.cc.
                                                                               {
  return IsBuiltinFunction(isolate, object,
                           Builtin::kAsyncFunctionAwaitResolveClosure) ||
         IsBuiltinFunction(isolate, object,
                           Builtin::kAsyncGeneratorAwaitResolveClosure) ||
         IsBuiltinFunction(
             isolate, object,
             Builtin::kAsyncGeneratorYieldWithAwaitResolveClosure);
}
References IsBuiltinFunction().
Referenced by TryGetAsyncGenerator(), and TryGetCurrentTaskPromise().
IsBuiltinAsyncRejectHandler()
bool v8::internal::anonymous_namespace{isolate.cc}::IsBuiltinAsyncRejectHandler (Isolate * isolate, Tagged< HeapObject > object)
Definition at line 801 of file isolate.cc.
                                                                              {
  return IsBuiltinFunction(isolate, object,
                           Builtin::kAsyncFunctionAwaitRejectClosure) ||
         IsBuiltinFunction(isolate, object,
                           Builtin::kAsyncGeneratorAwaitRejectClosure);
}
References IsBuiltinFunction().
Referenced by TryGetCurrentTaskPromise().
IsBuiltinForwardingRejectHandler()
bool v8::internal::anonymous_namespace{isolate.cc}::IsBuiltinForwardingRejectHandler (Isolate * isolate, Tagged< HeapObject > object)
Definition at line 810 of file isolate.cc.
                                                                 {
  return IsBuiltinFunction(isolate, object, Builtin::kPromiseCatchFinally) ||
         IsBuiltinFunction(isolate, object,
                           Builtin::kAsyncFromSyncIteratorCloseSyncAndRethrow);
}
References IsBuiltinFunction().
Referenced by WalkPromiseTreeInternal().
IsBuiltinFunction()
bool v8::internal::anonymous_namespace{isolate.cc}::IsBuiltinFunction (Isolate * isolate, Tagged< HeapObject > object, Builtin builtin)
Definition at line 776 of file isolate.cc.
                                        {
  if (!IsJSFunction(object)) return false;
  Tagged<JSFunction> const function = Cast<JSFunction>(object);
  // Currently we have to use full pointer comparison here as builtin Code
  // objects are still inside the sandbox while runtime-generated Code objects
  // are in trusted space.
  static_assert(!kAllCodeObjectsLiveInTrustedSpace);
  return function->code(isolate).SafeEquals(isolate->builtins()->code(builtin));
}
References v8::internal::Isolate::builtins(), v8::internal::Builtins::code(), and v8::internal::kAllCodeObjectsLiveInTrustedSpace.
Referenced by CaptureAsyncStackTrace(), IsBuiltinAsyncFulfillHandler(), IsBuiltinAsyncRejectHandler(), IsBuiltinForwardingRejectHandler(), and WalkPromiseTreeInternal().
NewRejectedPromise()
MaybeDirectHandle<JSPromise> v8::internal::anonymous_namespace{isolate.cc}::NewRejectedPromise (Isolate * isolate, v8::Local< v8::Context > api_context, DirectHandle< Object > exception)
Definition at line 6586 of file isolate.cc.
                                    {
  v8::Local<v8::Promise::Resolver> resolver;
  API_ASSIGN_RETURN_ON_EXCEPTION_VALUE(isolate, resolver,
                                       v8::Promise::Resolver::New(api_context),
                                       MaybeDirectHandle<JSPromise>());
  MAYBE_RETURN_ON_EXCEPTION_VALUE(
      isolate, resolver->Reject(api_context, v8::Utils::ToLocal(exception)),
      MaybeDirectHandle<JSPromise>());
  v8::Local<v8::Promise> promise = resolver->GetPromise();
  return v8::Utils::OpenDirectHandle(*promise);
}
References API_ASSIGN_RETURN_ON_EXCEPTION_VALUE, MAYBE_RETURN_ON_EXCEPTION_VALUE, v8::Promise::Resolver::New(), and v8::Utils::OpenDirectHandle().
Referenced by v8::internal::Isolate::RunHostImportModuleDynamicallyCallback().
PredictException()
HandlerTable::CatchPrediction v8::internal::anonymous_namespace{isolate.cc}::PredictException (const FrameSummary & summary, Isolate * isolate)
Definition at line 2807 of file isolate.cc.
                                                                 {
  if (!summary.IsJavaScript()) {
    // This can happen when WASM is inlined by TurboFan. For now we ignore
    // frames that are not JavaScript.
    // TODO(https://crbug.com/349588762): We should also check Wasm code
    // for exception handling.
    return HandlerTable::UNCAUGHT;
  }
  PtrComprCageBase cage_base(isolate);
  DirectHandle<AbstractCode> code = summary.AsJavaScript().abstract_code();
  if (code->kind(cage_base) == CodeKind::BUILTIN) {
    return CatchPredictionFor(code->GetCode()->builtin_id());
  }
  // Must have been constructed from a bytecode array.
  CHECK_EQ(CodeKind::INTERPRETED_FUNCTION, code->kind(cage_base));
  return PredictExceptionFromBytecode(code->GetBytecodeArray(),
                                      summary.code_offset());
}
References BUILTIN, v8::internal::Isolate::cage_base(), CatchPredictionFor(), CHECK_EQ, code, v8::internal::FrameSummary::code_offset(), v8::internal::Factory::isolate(), PredictExceptionFromBytecode(), and v8::internal::HandlerTable::UNCAUGHT.
Referenced by PredictExceptionCatchAtFrame().
PredictExceptionCatchAtFrame()
Isolate::CatchType v8::internal::anonymous_namespace{isolate.cc}::PredictExceptionCatchAtFrame (const StackFrameSummaryIterator & iterator)
Definition at line 2851 of file isolate.cc.
                                               {
  const StackFrame* frame = iterator.frame();
  switch (frame->type()) {
    case StackFrame::ENTRY:
    case StackFrame::CONSTRUCT_ENTRY: {
      Address external_handler =
          iterator.isolate()->thread_local_top()->try_catch_handler_address();
      Address entry_handler = frame->top_handler()->next_address();
      // The exception has been externally caught if and only if there is an
      // external handler which is on top of the top-most JS_ENTRY handler.
      if (external_handler != kNullAddress &&
          !iterator.isolate()->try_catch_handler()->IsVerbose()) {
        if (entry_handler == kNullAddress || entry_handler > external_handler) {
          return Isolate::CAUGHT_BY_EXTERNAL;
        }
      }
    } break;
    // For JavaScript frames we perform a lookup in the handler table.
    case StackFrame::INTERPRETED:
    case StackFrame::BASELINE:
    case StackFrame::TURBOFAN_JS:
    case StackFrame::MAGLEV:
    case StackFrame::BUILTIN: {
      DCHECK(iterator.has_frame_summary());
      return ToCatchType(
          PredictException(iterator.frame_summary(), iterator.isolate()));
    }
    case StackFrame::STUB: {
      Tagged<Code> code = *frame->LookupCode();
      if (code->kind() != CodeKind::BUILTIN || !code->has_handler_table() ||
          !code->is_turbofanned()) {
        break;
      }
      return ToCatchType(CatchPredictionFor(code->builtin_id()));
    }
    case StackFrame::JAVASCRIPT_BUILTIN_CONTINUATION_WITH_CATCH: {
      Tagged<Code> code = *frame->LookupCode();
      return ToCatchType(CatchPredictionFor(code->builtin_id()));
    }
    default:
      // All other types can not handle exception.
      break;
  }
  return Isolate::NOT_CAUGHT;
}
References BUILTIN, CatchPredictionFor(), v8::internal::Isolate::CAUGHT_BY_EXTERNAL, code, CONSTRUCT_ENTRY, v8::internal::DCHECK(), ENTRY, v8::internal::anonymous_namespace{isolate.cc}::StackFrameSummaryIterator::frame(), v8::internal::anonymous_namespace{isolate.cc}::StackFrameSummaryIterator::frame_summary(), v8::internal::anonymous_namespace{isolate.cc}::StackFrameSummaryIterator::has_frame_summary(), v8::internal::anonymous_namespace{isolate.cc}::StackFrameSummaryIterator::isolate(), v8::TryCatch::IsVerbose(), v8::internal::kNullAddress, v8::internal::StackFrame::LookupCode(), v8::internal::StackHandler::next_address(), v8::internal::Isolate::NOT_CAUGHT, PredictException(), v8::internal::Isolate::thread_local_top(), ToCatchType(), v8::internal::StackFrame::top_handler(), v8::internal::Isolate::try_catch_handler(), v8::internal::ThreadLocalTop::try_catch_handler_address(), and v8::internal::StackFrame::type().
Referenced by v8::internal::Isolate::PredictExceptionCatcher(), and v8::internal::Isolate::WalkCallStackAndPromiseTree().
PredictExceptionFromBytecode()
HandlerTable::CatchPrediction v8::internal::anonymous_namespace{isolate.cc}::PredictExceptionFromBytecode (Tagged< BytecodeArray > bytecode, int code_offset)
Definition at line 2799 of file isolate.cc.
                                                     {
  HandlerTable table(bytecode);
  int handler_index = table.LookupHandlerIndexForRange(code_offset);
  if (handler_index < 0) return HandlerTable::UNCAUGHT;
  return table.GetRangePrediction(handler_index);
}
References v8::internal::HandlerTable::GetRangePrediction(), v8::internal::HandlerTable::LookupHandlerIndexForRange(), and v8::internal::HandlerTable::UNCAUGHT.
Referenced by PredictException(), and PredictExceptionFromGenerator().
PredictExceptionFromGenerator()
HandlerTable::CatchPrediction v8::internal::anonymous_namespace{isolate.cc}::PredictExceptionFromGenerator (DirectHandle< JSGeneratorObject > generator, Isolate * isolate)
Definition at line 2828 of file isolate.cc.
                                                                 {
  return PredictExceptionFromBytecode(
      generator->function()->shared()->GetBytecodeArray(isolate),
      GetGeneratorBytecodeOffset(generator));
}
References GetGeneratorBytecodeOffset(), v8::internal::Factory::isolate(), and PredictExceptionFromBytecode().
Referenced by WalkPromiseTreeInternal().
ReceiverIsForwardingHandler()
bool v8::internal::anonymous_namespace{isolate.cc}::ReceiverIsForwardingHandler (Isolate * isolate, DirectHandle< JSReceiver > handler)
Definition at line 3203 of file isolate.cc.
                                                                   {
  // Recurse to the forwarding Promise (e.g. return false) due to
  // - await reaction forwarding to the throwaway Promise, which has
  // a dependency edge to the outer Promise.
  // - PromiseIdResolveHandler forwarding to the output of .then
  // - Promise.all/Promise.race forwarding to a throwaway Promise, which
  // has a dependency edge to the generated outer Promise.
  // Otherwise, this is a real reject handler for the Promise.
  DirectHandle<Symbol> key =
      isolate->factory()->promise_forwarding_handler_symbol();
  DirectHandle<Object> forwarding_handler =
      JSReceiver::GetDataProperty(isolate, handler, key);
  return !IsUndefined(*forwarding_handler, isolate);
}
References v8::internal::Isolate::factory(), v8::internal::JSReceiver::GetDataProperty(), v8::internal::Isolate::handler(), v8::internal::Factory::isolate(), and v8::internal::key.
Referenced by WalkPromiseTreeInternal().
ReportBootstrappingException()
void v8::internal::anonymous_namespace{isolate.cc}::ReportBootstrappingException (DirectHandle< Object > exception, MessageLocation * location)
Definition at line 2008 of file isolate.cc.
                                                             {
  base::OS::PrintError("Exception thrown during bootstrapping\n");
  if (location == nullptr || location->script().is_null()) return;
  // We are bootstrapping and caught an error where the location is set
  // and we have a script for the location.
  // In this case we could have an extension (or an internal error
  // somewhere) and we print out the line number at which the error occurred
  // to the console for easier debugging.
  int line_number =
      location->script()->GetLineNumber(location->start_pos()) + 1;
  if (IsString(*exception) && IsString(location->script()->name())) {
    base::OS::PrintError(
        "Extension or internal compilation error: %s in %s at line %d.\n",
        Cast<String>(*exception)->ToCString().get(),
        Cast<String>(location->script()->name())->ToCString().get(),
        line_number);
  } else if (IsString(location->script()->name())) {
    base::OS::PrintError(
        "Extension or internal compilation error in %s at line %d.\n",
        Cast<String>(location->script()->name())->ToCString().get(),
        line_number);
  } else if (IsString(*exception)) {
    base::OS::PrintError("Extension or internal compilation error: %s.\n",
                         Cast<String>(*exception)->ToCString().get());
  } else {
    base::OS::PrintError("Extension or internal compilation error.\n");
  }
#ifdef OBJECT_PRINT
  // Since comments and empty lines have been stripped from the source of
  // builtins, print the actual source here so that line numbers match.
  if (IsString(location->script()->source())) {
    DirectHandle<String> src(Cast<String>(location->script()->source()),
                             Isolate::Current());
    PrintF("Failing script:");
    int len = src->length();
    if (len == 0) {
      PrintF(" <not available>\n");
    } else {
      PrintF("\n");
      line_number = 1;
      PrintF("%5d: ", line_number);
      for (int i = 0; i < len; i++) {
        uint16_t character = src->Get(i);
        PrintF("%c", character);
        if (character == '\n' && i < len - 2) {
          PrintF("%5d: ", ++line_number);
        }
      }
      PrintF("\n");
    }
  }
#endif
}
References v8::internal::character, v8::internal::Isolate::Current(), v8::internal::PrintF(), v8::internal::MessageLocation::script(), and v8::internal::MessageLocation::start_pos().
Referenced by v8::internal::Isolate::Throw().
SetStickyEmbeddedBlob()
void v8::internal::anonymous_namespace{isolate.cc}::SetStickyEmbeddedBlob (const uint8_t * code, uint32_t code_size, const uint8_t * data, uint32_t data_size)
Definition at line 271 of file isolate.cc.
                                                                    {
  sticky_embedded_blob_code_ = code;
  sticky_embedded_blob_code_size_ = code_size;
  sticky_embedded_blob_data_ = data;
  sticky_embedded_blob_data_size_ = data_size;
}
References code, sticky_embedded_blob_code_, sticky_embedded_blob_code_size_, sticky_embedded_blob_data_, and sticky_embedded_blob_data_size_.
Referenced by v8::internal::Isolate::CreateAndSetEmbeddedBlob().
StickyEmbeddedBlobCode()
const uint8_t* v8::internal::anonymous_namespace{isolate.cc}::StickyEmbeddedBlobCode ()
Definition at line 262 of file isolate.cc.
{ return sticky_embedded_blob_code_; }
References sticky_embedded_blob_code_.
Referenced by v8::internal::Isolate::ClearEmbeddedBlob(), v8::internal::Isolate::CreateAndSetEmbeddedBlob(), v8::internal::FreeCurrentEmbeddedBlob(), v8::internal::Isolate::InitializeDefaultEmbeddedBlob(), and v8::internal::Isolate::TearDownEmbeddedBlob().
StickyEmbeddedBlobCodeSize()
uint32_t v8::internal::anonymous_namespace{isolate.cc}::StickyEmbeddedBlobCodeSize ()
Definition at line 263 of file isolate.cc.
                                      {
  return sticky_embedded_blob_code_size_;
}
References sticky_embedded_blob_code_size_.
Referenced by v8::internal::Isolate::InitializeDefaultEmbeddedBlob().
StickyEmbeddedBlobData()
const uint8_t* v8::internal::anonymous_namespace{isolate.cc}::StickyEmbeddedBlobData ()
Definition at line 266 of file isolate.cc.
{ return sticky_embedded_blob_data_; }
References sticky_embedded_blob_data_.
Referenced by v8::internal::Isolate::ClearEmbeddedBlob(), v8::internal::Isolate::CreateAndSetEmbeddedBlob(), v8::internal::FreeCurrentEmbeddedBlob(), v8::internal::Isolate::InitializeDefaultEmbeddedBlob(), and v8::internal::Isolate::TearDownEmbeddedBlob().
StickyEmbeddedBlobDataSize()
uint32_t v8::internal::anonymous_namespace{isolate.cc}::StickyEmbeddedBlobDataSize ()
Definition at line 267 of file isolate.cc.
                                      {
  return sticky_embedded_blob_data_size_;
}
References sticky_embedded_blob_data_size_.
Referenced by v8::internal::Isolate::InitializeDefaultEmbeddedBlob().
ToCatchType()
Isolate::CatchType v8::internal::anonymous_namespace{isolate.cc}::ToCatchType (HandlerTable::CatchPrediction prediction)
Definition at line 2835 of file isolate.cc.
                                                                     {
  switch (prediction) {
    case HandlerTable::UNCAUGHT:
      return Isolate::NOT_CAUGHT;
    case HandlerTable::CAUGHT:
      return Isolate::CAUGHT_BY_JAVASCRIPT;
    case HandlerTable::PROMISE:
      return Isolate::CAUGHT_BY_PROMISE;
    case HandlerTable::UNCAUGHT_ASYNC_AWAIT:
    case HandlerTable::ASYNC_AWAIT:
      return Isolate::CAUGHT_BY_ASYNC_AWAIT;
    default:
      UNREACHABLE();
  }
}
References v8::internal::HandlerTable::ASYNC_AWAIT, v8::internal::HandlerTable::CAUGHT, v8::internal::Isolate::CAUGHT_BY_ASYNC_AWAIT, v8::internal::Isolate::CAUGHT_BY_JAVASCRIPT, v8::internal::Isolate::CAUGHT_BY_PROMISE, v8::internal::Isolate::NOT_CAUGHT, v8::internal::HandlerTable::PROMISE, v8::internal::HandlerTable::UNCAUGHT, v8::internal::HandlerTable::UNCAUGHT_ASYNC_AWAIT, and v8::internal::UNREACHABLE().
Referenced by PredictExceptionCatchAtFrame().
ToHexString()
static std::string v8::internal::anonymous_namespace{isolate.cc}::ToHexString (uintptr_t address) [static]
Definition at line 5330 of file isolate.cc.
                                                {
  std::stringstream stream_address;
  stream_address << "0x" << std::hex << address;
  return stream_address.str();
}
Referenced by v8::internal::Isolate::AddCrashKeysForIsolateAndHeapPointers().
TouchesRegister()
bool v8::internal::anonymous_namespace{isolate.cc}::TouchesRegister (const interpreter::BytecodeArrayIterator & iterator, int index)
Definition at line 3355 of file isolate.cc.
                                {
  Bytecode bytecode = iterator.current_bytecode();
  int num_operands = Bytecodes::NumberOfOperands(bytecode);
  const interpreter::OperandType* operand_types =
      Bytecodes::GetOperandTypes(bytecode);
  for (int i = 0; i < num_operands; ++i) {
    if (Bytecodes::IsRegisterOperandType(operand_types[i])) {
      int base_index = iterator.GetRegisterOperand(i).index();
      int num_registers;
      if (Bytecodes::IsRegisterListOperandType(operand_types[i])) {
        num_registers = iterator.GetRegisterCountOperand(++i);
      } else {
        num_registers =
            Bytecodes::GetNumberOfRegistersRepresentedBy(operand_types[i]);
      }
      if (base_index <= index && index < base_index + num_registers) {
        return true;
      }
    }
  }
  if (Bytecodes::WritesImplicitRegister(bytecode)) {
    return iterator.GetStarTargetRegister().index() == index;
  }
  return false;
}
References v8::internal::interpreter::BytecodeArrayIterator::current_bytecode(), v8::internal::interpreter::BytecodeArrayIterator::GetRegisterCountOperand(), v8::internal::interpreter::BytecodeArrayIterator::GetRegisterOperand(), v8::internal::interpreter::BytecodeArrayIterator::GetStarTargetRegister(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::interpreter::Register::index(), and v8::internal::index.
Referenced by CallsCatchMethod().
TryGetAsyncGenerator()
MaybeHandle<JSGeneratorObject> v8::internal::anonymous_namespace{isolate.cc}::TryGetAsyncGenerator (Isolate * isolate, DirectHandle< PromiseReaction > reaction)
Definition at line 817 of file isolate.cc.
                                                              {
  // Check if the {reaction} has one of the known async function or
  // async generator continuations as its fulfill handler.
  if (IsBuiltinAsyncFulfillHandler(isolate, reaction->fulfill_handler())) {
    // Now peek into the handlers' AwaitContext to get to
    // the JSGeneratorObject for the async function.
    DirectHandle<Context> context(
        Cast<JSFunction>(reaction->fulfill_handler())->context(), isolate);
    Handle<JSGeneratorObject> generator_object(
        Cast<JSGeneratorObject>(context->extension()), isolate);
    return generator_object;
  }
  return MaybeHandle<JSGeneratorObject>();
}
References IsBuiltinAsyncFulfillHandler().
Referenced by CaptureAsyncStackTrace(), and WalkPromiseTreeInternal().
TryGetCurrentTaskPromise()
MaybeDirectHandle<JSPromise> v8::internal::anonymous_namespace{isolate.cc}::TryGetCurrentTaskPromise (Isolate * isolate)
Definition at line 1268 of file isolate.cc.
                                                                        {
  Handle<Object> current_microtask = isolate->factory()->current_microtask();
  if (IsPromiseReactionJobTask(*current_microtask)) {
    auto promise_reaction_job_task =
        Cast<PromiseReactionJobTask>(current_microtask);
    // Check if the {reaction} has one of the known async function or
    // async generator continuations as its fulfill handler.
    if (IsBuiltinAsyncFulfillHandler(isolate,
                                     promise_reaction_job_task->handler()) ||
        IsBuiltinAsyncRejectHandler(isolate,
                                    promise_reaction_job_task->handler())) {
      // Now peek into the handlers' AwaitContext to get to
      // the JSGeneratorObject for the async function.
      DirectHandle<Context> context(
          Cast<JSFunction>(promise_reaction_job_task->handler())->context(),
          isolate);
      Handle<JSGeneratorObject> generator_object(
          Cast<JSGeneratorObject>(context->extension()), isolate);
      if (generator_object->is_executing()) {
        if (IsJSAsyncFunctionObject(*generator_object)) {
          auto async_function_object =
              Cast<JSAsyncFunctionObject>(generator_object);
          DirectHandle<JSPromise> promise(async_function_object->promise(),
                                          isolate);
          return promise;
        } else {
          auto async_generator_object =
              Cast<JSAsyncGeneratorObject>(generator_object);
          DirectHandle<Object> queue(async_generator_object->queue(), isolate);
          if (!IsUndefined(*queue, isolate)) {
            auto async_generator_request = Cast<AsyncGeneratorRequest>(queue);
            DirectHandle<JSPromise> promise(
                Cast<JSPromise>(async_generator_request->promise()), isolate);
            return promise;
          }
        }
      }
    } else {
#if V8_ENABLE_WEBASSEMBLY
      DirectHandle<WasmSuspenderObject> suspender;
      if (TryGetWasmSuspender(isolate, promise_reaction_job_task->handler())
              .ToHandle(&suspender)) {
        // The {promise_reaction_job_task} belongs to a suspended Wasm stack
        return direct_handle(suspender->promise(), isolate);
      }
#endif // V8_ENABLE_WEBASSEMBLY
      // The {promise_reaction_job_task} doesn't belong to an await (or
      // yield inside an async generator) or a suspended Wasm stack,
      // but we might still be able to find an async frame if we follow
      // along the chain of promises on the {promise_reaction_job_task}.
      DirectHandle<HeapObject> promise_or_capability(
          promise_reaction_job_task->promise_or_capability(), isolate);
      if (IsJSPromise(*promise_or_capability)) {
        DirectHandle<JSPromise> promise =
            Cast<JSPromise>(promise_or_capability);
        return promise;
      }
    }
  }
  return MaybeDirectHandle<JSPromise>();
}
References v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::Isolate::handler(), IsBuiltinAsyncFulfillHandler(), and IsBuiltinAsyncRejectHandler().
Referenced by CaptureAsyncStackTrace(), and v8::internal::Isolate::WalkCallStackAndPromiseTree().
VisitStack()
template<typename Visitor >
void v8::internal::anonymous_namespace{isolate.cc}::VisitStack (Isolate * isolate, Visitor * visitor, StackTrace::StackTraceOptions options = StackTrace::kDetailed)
Definition at line 1339 of file isolate.cc.
                                                                           {
  DisallowJavascriptExecution no_js(isolate);
  // Keep track if we visited a stack frame, but did not visit any summarized
  // frames. Either because the stack frame didn't create any summarized frames
  // or due to security origin.
  bool skipped_last_frame = true;
  for (StackFrameIterator it(isolate); !it.done(); it.Advance()) {
    StackFrame* frame = it.frame();
    switch (frame->type()) {
      case StackFrame::API_CALLBACK_EXIT:
      case StackFrame::BUILTIN_EXIT:
      case StackFrame::JAVASCRIPT_BUILTIN_CONTINUATION:
      case StackFrame::JAVASCRIPT_BUILTIN_CONTINUATION_WITH_CATCH:
      case StackFrame::TURBOFAN_JS:
      case StackFrame::MAGLEV:
      case StackFrame::INTERPRETED:
      case StackFrame::BASELINE:
      case StackFrame::BUILTIN:
#if V8_ENABLE_WEBASSEMBLY
      case StackFrame::STUB:
      case StackFrame::WASM:
      case StackFrame::WASM_SEGMENT_START:
#if V8_ENABLE_DRUMBRAKE
      case StackFrame::WASM_INTERPRETER_ENTRY:
#endif // V8_ENABLE_DRUMBRAKE
#endif // V8_ENABLE_WEBASSEMBLY
      {
        // A standard frame may include many summarized frames (due to
        // inlining).
        FrameSummaries summaries = CommonFrame::cast(frame)->Summarize();
        if (summaries.top_frame_is_construct_call && !skipped_last_frame) {
          visitor->SetPrevFrameAsConstructCall();
        }
        skipped_last_frame = true;
        for (auto summary = summaries.frames.rbegin();
             summary != summaries.frames.rend(); ++summary) {
          // Skip frames from other origins when asked to do so.
          if (!(options & StackTrace::kExposeFramesAcrossSecurityOrigins) &&
              !summary->native_context()->HasSameSecurityTokenAs(
                  isolate->context())) {
            continue;
          }
          if (!visitor->Visit(*summary)) return;
          skipped_last_frame = false;
        }
        break;
      }
      default:
        break;
    }
  }
}
References BUILTIN, v8::internal::CommonFrame::cast(), v8::internal::Isolate::context(), v8::internal::StackFrameIteratorBase::done(), v8::internal::FrameSummaries::frames, v8::StackTrace::kExposeFramesAcrossSecurityOrigins, v8::internal::CommonFrame::Summarize(), v8::internal::FrameSummaries::top_frame_is_construct_call, and v8::internal::StackFrame::type().
Referenced by v8::internal::Isolate::CaptureDetailedStackTrace(), CaptureSimpleStackTrace(), v8::internal::Isolate::CurrentReferrerScript(), and v8::internal::Isolate::CurrentScriptNameOrSourceURL().
WalkPromiseTreeInternal()
bool v8::internal::anonymous_namespace{isolate.cc}::WalkPromiseTreeInternal (Isolate * isolate, DirectHandle< JSPromise > promise, const std::function< void(Isolate::PromiseHandler)> & callback)
Definition at line 3219 of file isolate.cc.
                                                              {
  if (promise->status() != Promise::kPending) {
    // If a rejection reaches an exception that isn't pending, it will be
    // treated as caught.
    return true;
  }
  bool any_caught = false;
  bool any_uncaught = false;
  DirectHandle<Object> current(promise->reactions(), isolate);
  while (!IsSmi(*current)) {
    auto reaction = Cast<PromiseReaction>(current);
    DirectHandle<HeapObject> promise_or_capability(
        reaction->promise_or_capability(), isolate);
    if (!IsUndefined(*promise_or_capability, isolate)) {
      if (!IsJSPromise(*promise_or_capability)) {
        promise_or_capability = direct_handle(
            Cast<PromiseCapability>(promise_or_capability)->promise(), isolate);
      }
      if (IsJSPromise(*promise_or_capability)) {
        DirectHandle<JSPromise> next_promise =
            Cast<JSPromise>(promise_or_capability);
        bool caught = false;
        DirectHandle<JSReceiver> reject_handler;
        if (!IsUndefined(reaction->reject_handler(), isolate)) {
          reject_handler = direct_handle(
              Cast<JSReceiver>(reaction->reject_handler()), isolate);
          if (!ReceiverIsForwardingHandler(isolate, reject_handler) &&
              !IsBuiltinForwardingRejectHandler(isolate, *reject_handler)) {
            caught = true;
          }
        }
        // Pass each handler to the callback
        DirectHandle<JSGeneratorObject> async_function;
        if (TryGetAsyncGenerator(isolate, reaction).ToHandle(&async_function)) {
          caught = caught ||
                   PredictExceptionFromGenerator(async_function, isolate) ==
                       HandlerTable::CAUGHT;
          // Look at the async function, not the individual handlers
          callback({async_function->function()->shared(), true});
        } else {
          // Not an async function, look at individual handlers
          if (!IsUndefined(reaction->fulfill_handler(), isolate)) {
            DirectHandle<JSReceiver> fulfill_handler(
                Cast<JSReceiver>(reaction->fulfill_handler()), isolate);
            if (!ReceiverIsForwardingHandler(isolate, fulfill_handler)) {
              if (IsBuiltinFunction(isolate, *fulfill_handler,
                                    Builtin::kPromiseThenFinally)) {
                // If this is the finally handler, get the wrapped callback
                // from the context to use instead
                DirectHandle<Context> context(
                    Cast<JSFunction>(reaction->fulfill_handler())->context(),
                    isolate);
                int const index =
                    PromiseBuiltins::PromiseFinallyContextSlot::kOnFinallySlot;
                fulfill_handler = direct_handle(
                    Cast<JSReceiver>(context->GetNoCell(index)), isolate);
              }
              if (IsJSFunction(*fulfill_handler)) {
                callback({Cast<JSFunction>(fulfill_handler)->shared(), true});
              }
            }
          }
          if (caught) {
            // We've already checked that this isn't undefined or
            // a forwarding handler
            if (IsJSFunction(*reject_handler)) {
              callback({Cast<JSFunction>(reject_handler)->shared(), true});
            }
          }
        }
        caught =
            caught || WalkPromiseTreeInternal(isolate, next_promise, callback);
        any_caught = any_caught || caught;
        any_uncaught = any_uncaught || !caught;
      }
    } else {
#if V8_ENABLE_WEBASSEMBLY
      DirectHandle<WasmSuspenderObject> suspender;
      if (TryGetWasmSuspender(isolate, reaction->fulfill_handler())
              .ToHandle(&suspender)) {
        // If in the future we support Wasm exceptions or ignore listing in
        // Wasm, we will need to iterate through these frames. For now, we
        // only care about the resulting promise.
        DirectHandle<JSPromise> next_promise(suspender->promise(), isolate);
        bool caught = WalkPromiseTreeInternal(isolate, next_promise, callback);
        any_caught = any_caught || caught;
        any_uncaught = any_uncaught || !caught;
      }
#endif // V8_ENABLE_WEBASSEMBLY
    }
    current = direct_handle(reaction->next(), isolate);
  }
  bool caught = any_caught && !any_uncaught;
  if (!caught) {
    // If there is an outer promise, follow that to see if it is caught.
    DirectHandle<Symbol> key = isolate->factory()->promise_handled_by_symbol();
    DirectHandle<Object> outer_promise_obj =
        JSObject::GetDataProperty(isolate, promise, key);
    if (IsJSPromise(*outer_promise_obj)) {
      return WalkPromiseTreeInternal(
          isolate, Cast<JSPromise>(outer_promise_obj), callback);
    }
  }
  return caught;
}
References v8::internal::HandlerTable::CAUGHT, v8::internal::Isolate::context(), v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::index, IsBuiltinForwardingRejectHandler(), IsBuiltinFunction(), v8::internal::Factory::isolate(), v8::internal::IsSmi(), v8::internal::key, v8::Promise::kPending, PredictExceptionFromGenerator(), ReceiverIsForwardingHandler(), v8::anonymous_namespace{api.cc}::ToHandle(), and TryGetAsyncGenerator().
Referenced by v8::internal::Isolate::WalkCallStackAndPromiseTree().
Variable Documentation
current_embedded_blob_refcount_mutex_
base::LazyMutex v8::internal::anonymous_namespace{isolate.cc}::current_embedded_blob_refcount_mutex_ = LAZY_MUTEX_INITIALIZER
Definition at line 252 of file isolate.cc.
Referenced by v8::internal::Isolate::CreateAndSetEmbeddedBlob(), v8::internal::DisableEmbeddedBlobRefcounting(), v8::internal::FreeCurrentEmbeddedBlob(), v8::internal::Isolate::InitializeDefaultEmbeddedBlob(), and v8::internal::Isolate::TearDownEmbeddedBlob().
current_embedded_blob_refs_
int v8::internal::anonymous_namespace{isolate.cc}::current_embedded_blob_refs_ = 0
Definition at line 260 of file isolate.cc.
Referenced by v8::internal::Isolate::CreateAndSetEmbeddedBlob(), v8::internal::Isolate::InitializeDefaultEmbeddedBlob(), and v8::internal::Isolate::TearDownEmbeddedBlob().
enable_embedded_blob_refcounting_
bool v8::internal::anonymous_namespace{isolate.cc}::enable_embedded_blob_refcounting_ = true
Definition at line 259 of file isolate.cc.
Referenced by v8::internal::Isolate::ClearEmbeddedBlob(), v8::internal::DisableEmbeddedBlobRefcounting(), v8::internal::FreeCurrentEmbeddedBlob(), and v8::internal::Isolate::TearDownEmbeddedBlob().
isolate_counter
std::atomic<int> v8::internal::anonymous_namespace{isolate.cc}::isolate_counter {0}
Definition at line 543 of file isolate.cc.
print_with_timestamp_mutex_
base::LazyMutex v8::internal::anonymous_namespace{isolate.cc}::print_with_timestamp_mutex_ = LAZY_MUTEX_INITIALIZER
Definition at line 7285 of file isolate.cc.
stack_access_count_map
MapOfLoadsAndStoresPerFunction* v8::internal::anonymous_namespace{isolate.cc}::stack_access_count_map = nullptr
Definition at line 5393 of file isolate.cc.
Referenced by v8::internal::Isolate::DumpAndResetStats(), v8::internal::Isolate::load_from_stack_count_address(), and v8::internal::Isolate::store_to_stack_count_address().
sticky_embedded_blob_code_
const uint8_t* v8::internal::anonymous_namespace{isolate.cc}::sticky_embedded_blob_code_ = nullptr
Definition at line 254 of file isolate.cc.
Referenced by v8::internal::Isolate::ClearEmbeddedBlob(), v8::internal::FreeCurrentEmbeddedBlob(), SetStickyEmbeddedBlob(), and StickyEmbeddedBlobCode().
sticky_embedded_blob_code_size_
uint32_t v8::internal::anonymous_namespace{isolate.cc}::sticky_embedded_blob_code_size_ = 0
Definition at line 255 of file isolate.cc.
Referenced by v8::internal::Isolate::ClearEmbeddedBlob(), v8::internal::FreeCurrentEmbeddedBlob(), SetStickyEmbeddedBlob(), and StickyEmbeddedBlobCodeSize().
sticky_embedded_blob_data_
const uint8_t* v8::internal::anonymous_namespace{isolate.cc}::sticky_embedded_blob_data_ = nullptr
Definition at line 256 of file isolate.cc.
Referenced by v8::internal::Isolate::ClearEmbeddedBlob(), v8::internal::FreeCurrentEmbeddedBlob(), SetStickyEmbeddedBlob(), and StickyEmbeddedBlobData().
sticky_embedded_blob_data_size_
uint32_t v8::internal::anonymous_namespace{isolate.cc}::sticky_embedded_blob_data_size_ = 0
Definition at line 257 of file isolate.cc.
Referenced by v8::internal::Isolate::ClearEmbeddedBlob(), v8::internal::FreeCurrentEmbeddedBlob(), SetStickyEmbeddedBlob(), and StickyEmbeddedBlobDataSize().