v8::anonymous_namespace{async-hooks-wrapper.cc} Namespace Reference
Functions
std::shared_ptr< AsyncHooksWrap > UnwrapHook (const v8::FunctionCallbackInfo< v8::Value > &info)
void EnableHook (const v8::FunctionCallbackInfo< v8::Value > &info)
void DisableHook (const v8::FunctionCallbackInfo< v8::Value > &info)
Function Documentation
DisableHook()
void v8::anonymous_namespace{async-hooks-wrapper.cc}::DisableHook (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 46 of file async-hooks-wrapper.cc.
                                                              {
  DCHECK(i::ValidateCallbackInfo(info));
  auto wrap = UnwrapHook(info);
  if (wrap) wrap->Disable();
}
References DCHECK, UnwrapHook(), and v8::internal::ValidateCallbackInfo().
Referenced by v8::AsyncHooks::AsyncHooks().
EnableHook()
void v8::anonymous_namespace{async-hooks-wrapper.cc}::EnableHook (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 40 of file async-hooks-wrapper.cc.
                                                             {
  DCHECK(i::ValidateCallbackInfo(info));
  auto wrap = UnwrapHook(info);
  if (wrap) wrap->Enable();
}
References DCHECK, UnwrapHook(), and v8::internal::ValidateCallbackInfo().
Referenced by v8::AsyncHooks::AsyncHooks().
UnwrapHook()
std::shared_ptr<AsyncHooksWrap> v8::anonymous_namespace{async-hooks-wrapper.cc}::UnwrapHook (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 20 of file async-hooks-wrapper.cc.
                                                 {
  DCHECK(i::ValidateCallbackInfo(info));
  v8::Isolate* v8_isolate = info.GetIsolate();
  HandleScope scope(v8_isolate);
  Local<Object> hook = info.This();
  AsyncHooks* hooks = PerIsolateData::Get(v8_isolate)->GetAsyncHooks();
  if (!hooks->async_hook_ctor.Get(v8_isolate)->HasInstance(hook)) {
    v8_isolate->ThrowError(
        "Invalid 'this' passed instead of AsyncHooks instance");
    return nullptr;
  }
  i::DirectHandle<i::Object> handle =
      Utils::OpenDirectHandle(*hook->GetInternalField(0));
  return Cast<i::Managed<AsyncHooksWrap>>(handle)->get();
}
References v8::AsyncHooks::async_hook_ctor, DCHECK, v8::PerIsolateData::Get(), v8::PerIsolateData::GetAsyncHooks(), v8::Object::GetInternalField(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::internal::handle(), v8::Utils::OpenDirectHandle(), v8::FunctionCallbackInfo< T >::This(), v8::Isolate::ThrowError(), and v8::internal::ValidateCallbackInfo().
Referenced by DisableHook(), and EnableHook().