v8::internal::wasm::anonymous_namespace{wrappers.cc} Namespace Reference
Functions
const TSCallDescriptor * GetBuiltinCallDescriptor (Builtin name, Zone *zone)
Function Documentation
GetBuiltinCallDescriptor()
const TSCallDescriptor* v8::internal::wasm::anonymous_namespace{wrappers.cc}::GetBuiltinCallDescriptor (Builtin name, Zone * zone)
Definition at line 48 of file wrappers.cc.
                                                                           {
  CallInterfaceDescriptor interface_descriptor =
      Builtins::CallInterfaceDescriptorFor(name);
  CallDescriptor* call_desc = compiler::Linkage::GetStubCallDescriptor(
      zone, // zone
      interface_descriptor, // descriptor
      interface_descriptor.GetStackParameterCount(), // stack parameter count
      CallDescriptor::kNoFlags, // flags
      compiler::Operator::kNoProperties, // properties
      StubCallMode::kCallBuiltinPointer); // stub call mode
  return TSCallDescriptor::Create(call_desc, compiler::CanThrow::kNo,
                                  compiler::LazyDeoptOnThrow::kNo, zone);
}
References v8::internal::Builtins::CallInterfaceDescriptorFor(), v8::internal::compiler::turboshaft::TSCallDescriptor::Create(), v8::internal::CallInterfaceDescriptor::GetStackParameterCount(), v8::internal::compiler::Linkage::GetStubCallDescriptor(), v8::internal::kCallBuiltinPointer, v8::internal::compiler::kNo, v8::internal::compiler::CallDescriptor::kNoFlags, v8::internal::compiler::Operator::kNoProperties, and v8::internal::wasm::name().
Referenced by v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildSuspend().