v8::internal::anonymous_namespace{scavenger.cc} Namespace Reference
Classes
class GlobalHandlesWeakRootsUpdatingVisitor
class YoungGenerationConservativeStackVisitor
class ObjectPinningVisitorBase
class ConservativeObjectPinningVisitor
class PreciseObjectPinningVisitor
class TreatConservativelyVisitor
Functions
bool IsUnscavengedHeapObject (Heap *heap, Tagged< Object > object)
bool IsUnscavengedHeapObject (Heap *heap, Tagged< HeapObject > heap_object)
bool IsUnscavengedHeapObjectSlot (Heap *heap, FullObjectSlot p)
void RestorePinnedObjects (SemiSpaceNewSpace &new_space, const ScavengerCollector::PinnedObjects &pinned_objects)
void QuarantinePinnedPages (SemiSpaceNewSpace &new_space)
Function Documentation
IsUnscavengedHeapObject() [1/2]
bool v8::internal::anonymous_namespace{scavenger.cc}::IsUnscavengedHeapObject (Heap * heap, Tagged< HeapObject > heap_object) [inline]
Definition at line 196 of file scavenger.cc.
                                                                       {
  return Heap::InFromPage(heap_object) &&
         !heap_object->map_word(kRelaxedLoad).IsForwardingAddress();
}
References v8::internal::Heap::InFromPage(), and v8::kRelaxedLoad.
Referenced by v8::internal::ScavengerCollector::ClearOldEphemerons(), and IsUnscavengedHeapObjectSlot().
IsUnscavengedHeapObject() [2/2]
bool v8::internal::anonymous_namespace{scavenger.cc}::IsUnscavengedHeapObject (Heap * heap, Tagged< Object > object) [inline]
Definition at line 189 of file scavenger.cc.
                                                                          {
  return Heap::InFromPage(object) && !Cast<HeapObject>(object)
                                          ->map_word(kRelaxedLoad)
                                          .IsForwardingAddress();
}
References v8::internal::Heap::InFromPage(), and v8::kRelaxedLoad.
IsUnscavengedHeapObjectSlot()
bool v8::internal::anonymous_namespace{scavenger.cc}::IsUnscavengedHeapObjectSlot (Heap * heap, FullObjectSlot p)
Definition at line 202 of file scavenger.cc.
                                                               {
  return IsUnscavengedHeapObject(heap, *p);
}
References IsUnscavengedHeapObject().
QuarantinePinnedPages()
void v8::internal::anonymous_namespace{scavenger.cc}::QuarantinePinnedPages (SemiSpaceNewSpace & new_space)
Definition at line 639 of file scavenger.cc.
                                                         {
  PageMetadata* next_page = new_space.from_space().first_page();
  while (next_page) {
    PageMetadata* current_page = next_page;
    next_page = current_page->next_page();
    MemoryChunk* chunk = current_page->Chunk();
    DCHECK(chunk->IsFromPage());
    if (!chunk->IsQuarantined()) {
      continue;
    }
    if (chunk->IsFlagSet(MemoryChunk::WILL_BE_PROMOTED)) {
      // free list categories will be relinked by the quarantined page sweeper
      // after sweeping is done.
      new_space.PromotePageToOldSpace(current_page,
                                      FreeMode::kDoNotLinkCategory);
      DCHECK(!chunk->InYoungGeneration());
    } else {
      new_space.MoveQuarantinedPage(chunk);
      DCHECK(!chunk->IsFromPage());
      DCHECK(chunk->IsToPage());
    }
    DCHECK(current_page->marking_bitmap()->IsClean());
    DCHECK(!chunk->IsFromPage());
    DCHECK(!chunk->IsQuarantined());
    DCHECK(!chunk->IsFlagSet(MemoryChunk::WILL_BE_PROMOTED));
  }
}
References v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::DCHECK(), v8::internal::SemiSpace::first_page(), v8::internal::SemiSpaceNewSpace::from_space(), v8::internal::MemoryChunk::InYoungGeneration(), v8::internal::MarkingBitmap::IsClean(), v8::internal::MemoryChunk::IsFlagSet(), v8::internal::MemoryChunk::IsFromPage(), v8::internal::MemoryChunk::IsQuarantined(), v8::internal::MemoryChunk::IsToPage(), v8::internal::kDoNotLinkCategory, v8::internal::MutablePageMetadata::marking_bitmap(), v8::internal::SemiSpaceNewSpace::MoveQuarantinedPage(), v8::internal::PageMetadata::next_page(), v8::internal::NewSpace::PromotePageToOldSpace(), and v8::internal::MemoryChunk::WILL_BE_PROMOTED.
RestorePinnedObjects()
void v8::internal::anonymous_namespace{scavenger.cc}::RestorePinnedObjects (SemiSpaceNewSpace & new_space, const ScavengerCollector::PinnedObjects & pinned_objects)
Definition at line 616 of file scavenger.cc.
                                                           {
  // Restore the maps of quarantined objects. We use the iteration over
  // quarantined objects to split them based on pages. This will be used below
  // for sweeping the quarantined pages (since there are no markbits).
  DCHECK_EQ(0, new_space.QuarantinedPageCount());
  size_t quarantined_objects_size = 0;
  for (const auto& [object_address, map_word, object_size] : pinned_objects) {
    DCHECK(!map_word.IsForwardingAddress());
    Tagged<HeapObject> object = HeapObject::FromAddress(object_address);
    DCHECK(HeapLayout::IsSelfForwarded(object));
    object->set_map_word(map_word.ToMap(), kRelaxedStore);
    DCHECK(!HeapLayout::IsSelfForwarded(object));
    MemoryChunk* chunk = MemoryChunk::FromHeapObject(object);
    DCHECK(chunk->IsQuarantined());
    if (!chunk->IsFlagSet(MemoryChunk::WILL_BE_PROMOTED)) {
      quarantined_objects_size += object_size;
    }
  }
  new_space.SetQuarantinedSize(quarantined_objects_size);
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::HeapObject::FromAddress(), v8::internal::MemoryChunk::FromHeapObject(), v8::internal::MemoryChunk::IsFlagSet(), v8::internal::MemoryChunk::IsQuarantined(), v8::internal::HeapLayout::IsSelfForwarded(), v8::kRelaxedStore, v8::internal::SemiSpaceNewSpace::QuarantinedPageCount(), v8::internal::SemiSpaceNewSpace::SetQuarantinedSize(), and v8::internal::MemoryChunk::WILL_BE_PROMOTED.