v8::internal::anonymous_namespace{traced-handles.cc} Namespace Reference
Classes
class ParallelWeakHandlesProcessor
class ComputeWeaknessProcessor
class ClearWeaknessProcessor
Functions
Tagged< Object > MarkObject (Tagged< Object > obj, TracedNode &node, TracedHandles::MarkMode mark_mode)
Function Documentation
MarkObject()
Tagged<Object> v8::internal::anonymous_namespace{traced-handles.cc}::MarkObject (Tagged< Object > obj, TracedNode & node, TracedHandles::MarkMode mark_mode)
Definition at line 793 of file traced-handles.cc.
                                                           {
  if (mark_mode == TracedHandles::MarkMode::kOnlyYoung &&
      !node.is_in_young_list())
    return Smi::zero();
  node.set_markbit();
  // Being in the young list, the node may still point to an old object, in
  // which case we want to keep the node marked, but not follow the reference.
  if (mark_mode == TracedHandles::MarkMode::kOnlyYoung &&
      !HeapLayout::InYoungGeneration(obj))
    return Smi::zero();
  return obj;
}
References v8::internal::HeapLayout::InYoungGeneration(), v8::internal::TracedNode::is_in_young_list(), v8::internal::TracedHandles::kOnlyYoung, v8::internal::TracedNode::set_markbit(), and v8::internal::Smi::zero().
Referenced by v8::internal::MarkingVisitorBase< ReferenceSummarizerMarkingVisitor >::IsTrivialWeakReferenceValue(), v8::internal::TracedHandles::Mark(), v8::internal::TracedHandles::MarkConservatively(), v8::internal::FullMarkingVisitorBase< ConcurrentMarkingVisitor >::MarkPointerTableEntry(), v8::internal::MarkCompactCollector::ProcessMarkingWorklist(), and v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitJSFunction().