v8::internal::wasm::anonymous_namespace{simd-shuffle.cc} Namespace Reference
Functions
bool TryMatch32x4Pairwise (const uint8_t *shuffle)
bool TryMatch32x2Pairwise (const uint8_t *shuffle)
bool TryMatchUpperToLowerFirst (const uint8_t *shuffle)
bool TryMatchUpperToLowerSecond (const uint8_t *shuffle)
bool TryMatchUpperToLowerThird (const uint8_t *shuffle)
bool TryMatchUpperToLowerFourth (const uint8_t *shuffle)
Function Documentation
TryMatch32x2Pairwise()
bool v8::internal::wasm::anonymous_namespace{simd-shuffle.cc}::TryMatch32x2Pairwise (const uint8_t * shuffle)
Definition at line 290 of file simd-shuffle.cc.
                                                  {
  // Pattern to select 32-bit element 2.
  constexpr uint8_t pattern_arr[4] = {8, 9, 10, 11};
  // And we'll check that element 2 is shuffled to element 0.
  uint32_t low_shuffle = reinterpret_cast<const uint32_t*>(shuffle)[0];
  uint32_t pattern = *reinterpret_cast<const uint32_t*>(pattern_arr);
  return low_shuffle == pattern;
}
Referenced by v8::internal::wasm::SimdShuffle::TryMatch32x4PairwiseReduce().
TryMatch32x4Pairwise()
bool v8::internal::wasm::anonymous_namespace{simd-shuffle.cc}::TryMatch32x4Pairwise (const uint8_t * shuffle)
Definition at line 275 of file simd-shuffle.cc.
                                                  {
  // Pattern to select 32-bit element 1.
  constexpr uint8_t low_pattern_arr[4] = {4, 5, 6, 7};
  // And we'll check that element 1 is shuffled into element 0.
  uint32_t low_shuffle = reinterpret_cast<const uint32_t*>(shuffle)[0];
  // Pattern to select 32-bit element 3.
  constexpr uint8_t high_pattern_arr[4] = {12, 13, 14, 15};
  // And we'll check that element 3 is shuffled into element 2.
  uint32_t high_shuffle = reinterpret_cast<const uint32_t*>(shuffle)[2];
  uint32_t low_pattern = *reinterpret_cast<const uint32_t*>(low_pattern_arr);
  uint32_t high_pattern = *reinterpret_cast<const uint32_t*>(high_pattern_arr);
  return low_shuffle == low_pattern && high_shuffle == high_pattern;
}
Referenced by v8::internal::wasm::SimdShuffle::TryMatch32x4PairwiseReduce().
TryMatchUpperToLowerFirst()
bool v8::internal::wasm::anonymous_namespace{simd-shuffle.cc}::TryMatchUpperToLowerFirst (const uint8_t * shuffle)
Definition at line 300 of file simd-shuffle.cc.
                                                       {
  // There's 16 'active' bytes, so the pattern to select the upper half starts
  // at byte 8.
  constexpr uint8_t low_pattern_arr[8] = {8, 9, 10, 11, 12, 13, 14, 15};
  // And we'll check that the top half is shuffled into the lower.
  uint64_t low_shuffle = reinterpret_cast<const uint64_t*>(shuffle)[0];
  uint64_t low_pattern = *reinterpret_cast<const uint64_t*>(low_pattern_arr);
  return low_shuffle == low_pattern;
}
Referenced by v8::internal::wasm::SimdShuffle::TryMatch16x8UpperToLowerReduce(), v8::internal::wasm::SimdShuffle::TryMatch32x4UpperToLowerReduce(), and v8::internal::wasm::SimdShuffle::TryMatch8x16UpperToLowerReduce().
TryMatchUpperToLowerFourth()
bool v8::internal::wasm::anonymous_namespace{simd-shuffle.cc}::TryMatchUpperToLowerFourth (const uint8_t * shuffle)
Definition at line 332 of file simd-shuffle.cc.
                                                        {
  return shuffle[0] == 1;
}
Referenced by v8::internal::wasm::SimdShuffle::TryMatch8x16UpperToLowerReduce().
TryMatchUpperToLowerSecond()
bool v8::internal::wasm::anonymous_namespace{simd-shuffle.cc}::TryMatchUpperToLowerSecond (const uint8_t * shuffle)
Definition at line 311 of file simd-shuffle.cc.
                                                        {
  // There's 8 'active' bytes, so the pattern to select the upper half starts
  // at byte 4.
  constexpr uint8_t low_pattern_arr[4] = {4, 5, 6, 7};
  // And we'll check that the top half is shuffled into the lower.
  uint32_t low_shuffle = reinterpret_cast<const uint32_t*>(shuffle)[0];
  uint32_t low_pattern = *reinterpret_cast<const uint32_t*>(low_pattern_arr);
  return low_shuffle == low_pattern;
}
Referenced by v8::internal::wasm::SimdShuffle::TryMatch16x8UpperToLowerReduce(), v8::internal::wasm::SimdShuffle::TryMatch32x4UpperToLowerReduce(), and v8::internal::wasm::SimdShuffle::TryMatch8x16UpperToLowerReduce().
TryMatchUpperToLowerThird()
bool v8::internal::wasm::anonymous_namespace{simd-shuffle.cc}::TryMatchUpperToLowerThird (const uint8_t * shuffle)
Definition at line 322 of file simd-shuffle.cc.
                                                       {
  // The vector now has 4 'active' bytes, select the top two.
  constexpr uint8_t low_pattern_arr[2] = {2, 3};
  // And check they're shuffled to the lower half.
  uint16_t low_shuffle = reinterpret_cast<const uint16_t*>(shuffle)[0];
  uint16_t low_pattern = *reinterpret_cast<const uint16_t*>(low_pattern_arr);
  return low_shuffle == low_pattern;
}
Referenced by v8::internal::wasm::SimdShuffle::TryMatch16x8UpperToLowerReduce(), and v8::internal::wasm::SimdShuffle::TryMatch8x16UpperToLowerReduce().