v8::internal::anonymous_namespace{literal-objects.cc} Namespace Reference
Functions
int EncodeComputedEntry (ClassBoilerplate::ValueKind value_kind, unsigned key_index)
void SetAccessorPlaceholderIndices (Tagged< AccessorPair > pair, ClassBoilerplate::ValueKind value_kind, Tagged< Smi > index)
void SetAccessorPlaceholderIndices (Tagged< AccessorPair > pair, ClassBoilerplate::ValueKind value_kind, Tagged< Smi > index, ReleaseStoreTag tag)
template<typename IsolateT >
void AddToDescriptorArrayTemplate (IsolateT *isolate, DirectHandle< DescriptorArray > descriptor_array_template, DirectHandle< Name > name, ClassBoilerplate::ValueKind value_kind, DirectHandle< Object > value)
template<typename IsolateT >
Handle< NameDictionary > DictionaryAddNoUpdateNextEnumerationIndex (IsolateT *isolate, Handle< NameDictionary > dictionary, DirectHandle< Name > name, DirectHandle< Object > value, PropertyDetails details, InternalIndex *entry_out=nullptr)
template<typename IsolateT >
Handle< SwissNameDictionary > DictionaryAddNoUpdateNextEnumerationIndex (IsolateT *isolate, Handle< SwissNameDictionary > dictionary, DirectHandle< Name > name, DirectHandle< Object > value, PropertyDetails details, InternalIndex *entry_out=nullptr)
template<typename IsolateT >
DirectHandle< NumberDictionary > DictionaryAddNoUpdateNextEnumerationIndex (IsolateT *isolate, Handle< NumberDictionary > dictionary, uint32_t element, DirectHandle< Object > value, PropertyDetails details, InternalIndex *entry_out=nullptr)
template<template< typename > typename HandleType, typename Dictionary >
void DictionaryUpdateMaxNumberKey (HandleType< Dictionary > dictionary, DirectHandle< Name > name) requires(std
void DictionaryUpdateMaxNumberKey (DirectHandle< NumberDictionary > dictionary, uint32_t element)
constexpr int ComputeEnumerationIndex (int value_index)
int GetExistingValueIndex (Tagged< Object > value)
template<typename IsolateT , typename Dictionary , typename Key >
void AddToDictionaryTemplate (IsolateT *isolate, Handle< Dictionary > dictionary, Key key, int key_index, ClassBoilerplate::ValueKind value_kind, Tagged< Smi > value)
Variables
constexpr int kDummyEnumerationIndex = 0
constexpr int kAccessorNotDefined = -1
Function Documentation
AddToDescriptorArrayTemplate()
template<typename IsolateT >
void v8::internal::anonymous_namespace{literal-objects.cc}::AddToDescriptorArrayTemplate (IsolateT * isolate, DirectHandle< DescriptorArray > descriptor_array_template, DirectHandle< Name > name, ClassBoilerplate::ValueKind value_kind, DirectHandle< Object > value)
Definition at line 82 of file literal-objects.cc.
                                {
  InternalIndex entry = descriptor_array_template->Search(
      *name, descriptor_array_template->number_of_descriptors());
  // TODO(ishell): deduplicate properties at AST level, this will allow us to
  // avoid creation of closures that will be overwritten anyway.
  if (entry.is_not_found()) {
    // Entry not found, add new one.
    Descriptor d;
    if (value_kind == ClassBoilerplate::kData) {
      d = Descriptor::DataConstant(name, value, DONT_ENUM);
    } else {
      DCHECK(value_kind == ClassBoilerplate::kGetter ||
             value_kind == ClassBoilerplate::kSetter ||
             value_kind == ClassBoilerplate::kAutoAccessor);
      DirectHandle<AccessorPair> pair = isolate->factory()->NewAccessorPair();
      SetAccessorPlaceholderIndices(*pair, value_kind, Cast<Smi>(*value));
      d = Descriptor::AccessorConstant(name, pair, DONT_ENUM);
    }
    descriptor_array_template->Append(&d);
  } else {
    // Entry found, update it.
    int sorted_index = descriptor_array_template->GetDetails(entry).pointer();
    if (value_kind == ClassBoilerplate::kData) {
      Descriptor d = Descriptor::DataConstant(name, value, DONT_ENUM);
      d.SetSortedKeyIndex(sorted_index);
      descriptor_array_template->Set(entry, &d);
    } else {
      DCHECK(value_kind == ClassBoilerplate::kGetter ||
             value_kind == ClassBoilerplate::kSetter ||
             value_kind == ClassBoilerplate::kAutoAccessor);
      Tagged<Object> raw_accessor =
          descriptor_array_template->GetStrongValue(entry);
      Tagged<AccessorPair> pair;
      if (IsAccessorPair(raw_accessor)) {
        pair = Cast<AccessorPair>(raw_accessor);
      } else {
        DirectHandle<AccessorPair> new_pair =
            isolate->factory()->NewAccessorPair();
        Descriptor d = Descriptor::AccessorConstant(name, new_pair, DONT_ENUM);
        d.SetSortedKeyIndex(sorted_index);
        descriptor_array_template->Set(entry, &d);
        pair = *new_pair;
      }
      SetAccessorPlaceholderIndices(pair, value_kind, Cast<Smi>(*value),
                                    kReleaseStore);
    }
  }
}
References v8::internal::Descriptor::AccessorConstant(), v8::internal::Descriptor::DataConstant(), v8::internal::DCHECK(), v8::internal::DONT_ENUM, v8::internal::InternalIndex::is_not_found(), v8::internal::ClassBoilerplate::kAutoAccessor, v8::internal::ClassBoilerplate::kData, v8::internal::ClassBoilerplate::kGetter, v8::kReleaseStore, v8::internal::ClassBoilerplate::kSetter, v8::internal::name, SetAccessorPlaceholderIndices(), v8::internal::Descriptor::SetSortedKeyIndex(), and v8::internal::value.
Referenced by v8::internal::ObjectDescriptor< IsolateT >::AddNamedProperty().
AddToDictionaryTemplate()
template<typename IsolateT , typename Dictionary , typename Key >
void v8::internal::anonymous_namespace{literal-objects.cc}::AddToDictionaryTemplate (IsolateT * isolate, Handle< Dictionary > dictionary, Key key, int key_index, ClassBoilerplate::ValueKind value_kind, Tagged< Smi > value)
Definition at line 200 of file literal-objects.cc.
                                                {
  InternalIndex entry = dictionary->FindEntry(isolate, key);
  const bool is_elements_dictionary =
      std::is_same_v<Dictionary, NumberDictionary>;
  static_assert(is_elements_dictionary !=
                (std::is_same_v<Dictionary, NameDictionary> ||
                 std::is_same_v<Dictionary, SwissNameDictionary>));
  if (entry.is_not_found()) {
    // Entry not found, add new one.
    int enum_order =
        Dictionary::kIsOrderedDictionaryType || is_elements_dictionary
            ? kDummyEnumerationIndex
            : ComputeEnumerationIndex(key_index);
    DirectHandle<Object> value_handle;
    PropertyDetails details(
        value_kind != ClassBoilerplate::kData ? PropertyKind::kAccessor
                                              : PropertyKind::kData,
        DONT_ENUM, PropertyDetails::kConstIfDictConstnessTracking, enum_order);
    if (value_kind == ClassBoilerplate::kData) {
      value_handle = direct_handle(value, isolate);
    } else {
      DCHECK(value_kind == ClassBoilerplate::kGetter ||
             value_kind == ClassBoilerplate::kSetter ||
             value_kind == ClassBoilerplate::kAutoAccessor);
      DirectHandle<AccessorPair> pair(isolate->factory()->NewAccessorPair());
      SetAccessorPlaceholderIndices(*pair, value_kind, Cast<Smi>(value));
      value_handle = pair;
    }
    // Add value to the dictionary without updating next enumeration index.
    DirectHandle<Dictionary> dict = DictionaryAddNoUpdateNextEnumerationIndex(
        isolate, dictionary, key, value_handle, details, &entry);
    // It is crucial to avoid dictionary reallocations because it may remove
    // potential gaps in enumeration indices values that are necessary for
    // inserting computed properties into right places in the enumeration order.
    CHECK_EQ(*dict, *dictionary);
    DictionaryUpdateMaxNumberKey(dictionary, key);
  } else {
    // Entry found, update it.
    int enum_order_existing =
        Dictionary::kIsOrderedDictionaryType
            ? kDummyEnumerationIndex
            : dictionary->DetailsAt(entry).dictionary_index();
    int enum_order_computed =
        Dictionary::kIsOrderedDictionaryType || is_elements_dictionary
            ? kDummyEnumerationIndex
            : ComputeEnumerationIndex(key_index);
    Tagged<Object> existing_value = dictionary->ValueAt(entry);
    if (value_kind == ClassBoilerplate::kData) {
      // Computed value is a normal method.
      if (IsAccessorPair(existing_value)) {
        Tagged<AccessorPair> current_pair = Cast<AccessorPair>(existing_value);
        int existing_getter_index =
            GetExistingValueIndex(current_pair->getter());
        int existing_setter_index =
            GetExistingValueIndex(current_pair->setter());
        // At least one of the accessors must already be defined.
        static_assert(kAccessorNotDefined < 0);
        DCHECK(existing_getter_index >= 0 || existing_setter_index >= 0);
        if (existing_getter_index < key_index &&
            existing_setter_index < key_index) {
          // Either both getter and setter were defined before the computed
          // method or just one of them was defined before while the other one
          // was not defined yet, so overwrite property to kData.
          PropertyDetails details(
              PropertyKind::kData, DONT_ENUM,
              PropertyDetails::kConstIfDictConstnessTracking,
              enum_order_existing);
          dictionary->DetailsAtPut(entry, details);
          dictionary->ValueAtPut(entry, value);
        } else if (existing_getter_index != kAccessorNotDefined &&
                   existing_getter_index < key_index) {
          DCHECK_LT(key_index, existing_setter_index);
          // Getter was defined and it was done before the computed method
          // and then it was overwritten by the current computed method which
          // in turn was later overwritten by the setter method. So we clear
          // the getter.
          current_pair->set_getter(*isolate->factory()->null_value());
        } else if (existing_setter_index != kAccessorNotDefined &&
                   existing_setter_index < key_index) {
          DCHECK_LT(key_index, existing_getter_index);
          // Setter was defined and it was done before the computed method
          // and then it was overwritten by the current computed method which
          // in turn was later overwritten by the getter method. So we clear
          // the setter.
          current_pair->set_setter(*isolate->factory()->null_value());
        } else {
          // One of the following cases holds:
          // The computed method was defined before ...
          // 1.) the getter and setter, both of which are defined,
          // 2.) the getter, and the setter isn't defined,
          // 3.) the setter, and the getter isn't defined.
          // Therefore, the computed value is overwritten, receiving the
          // computed property's enum index.
          DCHECK(key_index < existing_getter_index ||
                 existing_getter_index == kAccessorNotDefined);
          DCHECK(key_index < existing_setter_index ||
                 existing_setter_index == kAccessorNotDefined);
          DCHECK(existing_getter_index != kAccessorNotDefined ||
                 existing_setter_index != kAccessorNotDefined);
          if (!is_elements_dictionary) {
            // The enum index is unused by elements dictionaries,
            // which is why we don't need to update the property details if
            // |is_elements_dictionary| holds.
            PropertyDetails details = dictionary->DetailsAt(entry);
            details = details.set_index(enum_order_computed);
            dictionary->DetailsAtPut(entry, details);
          }
        }
      } else { // if (existing_value.IsAccessorPair()) ends here
        DCHECK(value_kind == ClassBoilerplate::kData);
        DCHECK_IMPLIES(!IsSmi(existing_value), IsAccessorInfo(existing_value));
        DCHECK_IMPLIES(!IsSmi(existing_value),
                       Cast<AccessorInfo>(existing_value)->name() ==
                               *isolate->factory()->length_string() ||
                           Cast<AccessorInfo>(existing_value)->name() ==
                               *isolate->factory()->name_string());
        if (!IsSmi(existing_value) || Smi::ToInt(existing_value) < key_index) {
          // Overwrite existing value because it was defined before the computed
          // one (AccessorInfo "length" and "name" properties are always defined
          // before).
          PropertyDetails details(
              PropertyKind::kData, DONT_ENUM,
              PropertyDetails::kConstIfDictConstnessTracking,
              enum_order_existing);
          dictionary->DetailsAtPut(entry, details);
          dictionary->ValueAtPut(entry, value);
        } else {
          // The computed value appears before the existing one. Set the
          // existing entry's enum index to that of the computed one.
          if (!is_elements_dictionary) {
            // The enum index is unused by elements dictionaries,
            // which is why we don't need to update the property details if
            // |is_elements_dictionary| holds.
            PropertyDetails details(
                PropertyKind::kData, DONT_ENUM,
                PropertyDetails::kConstIfDictConstnessTracking,
                enum_order_computed);
            dictionary->DetailsAtPut(entry, details);
          }
        }
      }
    } else { // if (value_kind == ClassBoilerplate::kData) ends here
      if (IsAccessorPair(existing_value)) {
        // Update respective component of existing AccessorPair.
        Tagged<AccessorPair> current_pair = Cast<AccessorPair>(existing_value);
        bool updated = false;
        switch (value_kind) {
          case ClassBoilerplate::kAutoAccessor: {
            int existing_get_component_index =
                GetExistingValueIndex(current_pair->get(ACCESSOR_GETTER));
            int existing_set_component_index =
                GetExistingValueIndex(current_pair->get(ACCESSOR_SETTER));
            if (existing_get_component_index < key_index &&
                existing_set_component_index < key_index) {
              SetAccessorPlaceholderIndices(current_pair, value_kind, value,
                                            kReleaseStore);
              updated = true;
            } else {
              if (existing_get_component_index < key_index) {
                SetAccessorPlaceholderIndices(current_pair,
                                              ClassBoilerplate::kGetter, value,
                                              kReleaseStore);
                updated = true;
              } else if (existing_set_component_index < key_index) {
                SetAccessorPlaceholderIndices(
                    current_pair, ClassBoilerplate::kSetter,
                    Smi::FromInt(Smi::ToInt(value) + 1), kReleaseStore);
                updated = true;
              }
            }
            break;
          }
          case ClassBoilerplate::kGetter:
          case ClassBoilerplate::kSetter: {
            AccessorComponent component =
                value_kind == ClassBoilerplate::kGetter ? ACCESSOR_GETTER
                                                        : ACCESSOR_SETTER;
            int existing_component_index =
                GetExistingValueIndex(current_pair->get(component));
            if (existing_component_index < key_index) {
              SetAccessorPlaceholderIndices(current_pair, value_kind, value,
                                            kReleaseStore);
              updated = true;
            }
            break;
          }
          default:
            UNREACHABLE();
        }
        if (!updated) {
          // The existing accessor property overwrites the computed one, update
          // its enumeration order accordingly.
          if (!is_elements_dictionary) {
            // The enum index is unused by elements dictionaries,
            // which is why we don't need to update the property details if
            // |is_elements_dictionary| holds.
            PropertyDetails details(
                PropertyKind::kAccessor, DONT_ENUM,
                PropertyDetails::kConstIfDictConstnessTracking,
                enum_order_computed);
            dictionary->DetailsAtPut(entry, details);
          }
        }
      } else {
        DCHECK(!IsAccessorPair(existing_value));
        DCHECK(value_kind != ClassBoilerplate::kData);
        if (!IsSmi(existing_value) || Smi::ToInt(existing_value) < key_index) {
          // Overwrite the existing data property because it was defined before
          // the computed accessor property.
          DirectHandle<AccessorPair> pair(
              isolate->factory()->NewAccessorPair());
          SetAccessorPlaceholderIndices(*pair, value_kind, value);
          PropertyDetails details(
              PropertyKind::kAccessor, DONT_ENUM,
              PropertyDetails::kConstIfDictConstnessTracking,
              enum_order_existing);
          dictionary->DetailsAtPut(entry, details);
          dictionary->ValueAtPut(entry, *pair);
        } else {
          // The computed accessor property appears before the existing data
          // property. Set the existing entry's enum index to that of the
          // computed one.
          if (!is_elements_dictionary) {
            // The enum index is unused by elements dictionaries,
            // which is why we don't need to update the property details if
            // |is_elements_dictionary| holds.
            PropertyDetails details(
                PropertyKind::kData, DONT_ENUM,
                PropertyDetails::kConstIfDictConstnessTracking,
                enum_order_computed);
            dictionary->DetailsAtPut(entry, details);
          }
        }
      }
    }
  }
}
References v8::internal::ACCESSOR_GETTER, v8::internal::ACCESSOR_SETTER, CHECK_EQ, ComputeEnumerationIndex(), v8::internal::DCHECK(), DCHECK_IMPLIES, DCHECK_LT, DictionaryAddNoUpdateNextEnumerationIndex(), DictionaryUpdateMaxNumberKey(), v8::internal::direct_handle(), v8::internal::DONT_ENUM, v8::internal::Smi::FromInt(), GetExistingValueIndex(), v8::internal::InternalIndex::is_not_found(), v8::internal::IsSmi(), v8::internal::kAccessor, kAccessorNotDefined, v8::internal::ClassBoilerplate::kAutoAccessor, v8::internal::PropertyDetails::kConstIfDictConstnessTracking, v8::internal::ClassBoilerplate::kData, v8::internal::kData, kDummyEnumerationIndex, v8::internal::key, v8::internal::ClassBoilerplate::kGetter, v8::kReleaseStore, v8::internal::ClassBoilerplate::kSetter, v8::internal::name, v8::internal::PropertyDetails::set_index(), SetAccessorPlaceholderIndices(), v8::internal::Smi::ToInt(), v8::internal::UNREACHABLE(), and v8::internal::value.
Referenced by v8::internal::ObjectDescriptor< IsolateT >::AddIndexedProperty(), v8::internal::ObjectDescriptor< IsolateT >::AddNamedProperty(), v8::internal::ClassBoilerplate::AddToElementsTemplate(), and v8::internal::ClassBoilerplate::AddToPropertiesTemplate().
ComputeEnumerationIndex()
constexpr int v8::internal::anonymous_namespace{literal-objects.cc}::ComputeEnumerationIndex (int value_index) [constexpr]
Definition at line 184 of file literal-objects.cc.
                                                       {
  // We "shift" value indices to ensure that the enumeration index for the value
  // will not overlap with minimum properties set for both class and prototype
  // objects.
  return value_index +
         std::max({ClassBoilerplate::kMinimumClassPropertiesCount,
                   ClassBoilerplate::kMinimumPrototypePropertiesCount});
}
References v8::internal::ClassBoilerplate::kMinimumClassPropertiesCount, and v8::internal::ClassBoilerplate::kMinimumPrototypePropertiesCount.
Referenced by AddToDictionaryTemplate(), and v8::internal::ObjectDescriptor< IsolateT >::UpdateNextEnumerationIndex().
DictionaryAddNoUpdateNextEnumerationIndex() [1/3]
template<typename IsolateT >
Handle<NameDictionary> v8::internal::anonymous_namespace{literal-objects.cc}::DictionaryAddNoUpdateNextEnumerationIndex (IsolateT * isolate, Handle< NameDictionary > dictionary, DirectHandle< Name > name, DirectHandle< Object > value, PropertyDetails details, InternalIndex * entry_out = nullptr)
Definition at line 136 of file literal-objects.cc.
                                                                 {
  return NameDictionary::AddNoUpdateNextEnumerationIndex(
      isolate, dictionary, name, value, details, entry_out);
}
References v8::internal::name, and v8::internal::value.
DictionaryAddNoUpdateNextEnumerationIndex() [2/3]
template<typename IsolateT >
DirectHandle<NumberDictionary> v8::internal::anonymous_namespace{literal-objects.cc}::DictionaryAddNoUpdateNextEnumerationIndex (IsolateT * isolate, Handle< NumberDictionary > dictionary, uint32_t element, DirectHandle< Object > value, PropertyDetails details, InternalIndex * entry_out = nullptr)
Definition at line 155 of file literal-objects.cc.
                                        {
  // NumberDictionary does not maintain the enumeration order, so it's
  // a normal Add().
  return NumberDictionary::Add(isolate, dictionary, element, value, details,
                               entry_out);
}
References v8::bigint::Add(), and v8::internal::value.
Referenced by v8::internal::ObjectDescriptor< IsolateT >::AddConstant(), and AddToDictionaryTemplate().
DictionaryAddNoUpdateNextEnumerationIndex() [3/3]
template<typename IsolateT >
Handle<SwissNameDictionary> v8::internal::anonymous_namespace{literal-objects.cc}::DictionaryAddNoUpdateNextEnumerationIndex (IsolateT * isolate, Handle< SwissNameDictionary > dictionary, DirectHandle< Name > name, DirectHandle< Object > value, PropertyDetails details, InternalIndex * entry_out = nullptr)
Definition at line 145 of file literal-objects.cc.
                                                                 {
  // SwissNameDictionary does not maintain the enumeration order in property
  // details, so it's a normal Add().
  return SwissNameDictionary::Add(isolate, dictionary, name, value, details);
}
References v8::bigint::Add(), v8::internal::name, and v8::internal::value.
DictionaryUpdateMaxNumberKey() [1/2]
void v8::internal::anonymous_namespace{literal-objects.cc}::DictionaryUpdateMaxNumberKey (DirectHandle< NumberDictionary > dictionary, uint32_t element)
Definition at line 178 of file literal-objects.cc.
                                                    {
  dictionary->UpdateMaxNumberKey(element, DirectHandle<JSObject>());
  dictionary->set_requires_slow_elements();
}
Referenced by AddToDictionaryTemplate().
DictionaryUpdateMaxNumberKey() [2/2]
template<template< typename > typename HandleType, typename Dictionary >
void v8::internal::anonymous_namespace{literal-objects.cc}::DictionaryUpdateMaxNumberKey (HandleType< Dictionary > dictionary, DirectHandle< Name > name)
Definition at line 168 of file literal-objects.cc.
{
  static_assert((std::is_same_v<Dictionary, SwissNameDictionary> ||
                 std::is_same_v<Dictionary, NameDictionary>));
  // No-op for (ordered) name dictionaries.
}
EncodeComputedEntry()
int v8::internal::anonymous_namespace{literal-objects.cc}::EncodeComputedEntry (ClassBoilerplate::ValueKind value_kind, unsigned key_index) [inline]
Definition at line 33 of file literal-objects.cc.
                                                   {
  using Flags = ClassBoilerplate::ComputedEntryFlags;
  int flags = Flags::ValueKindBits::encode(value_kind) |
              Flags::KeyIndexBits::encode(key_index);
  return flags;
}
References v8::internal::Flags(), and v8::internal::flags.
Referenced by v8::internal::ObjectDescriptor< IsolateT >::AddComputed().
GetExistingValueIndex()
int v8::internal::anonymous_namespace{literal-objects.cc}::GetExistingValueIndex (Tagged< Object > value) [inline]
Definition at line 195 of file literal-objects.cc.
                                                       {
  return IsSmi(value) ? Smi::ToInt(value) : kAccessorNotDefined;
}
References v8::internal::IsSmi(), kAccessorNotDefined, v8::internal::Smi::ToInt(), and v8::internal::value.
Referenced by AddToDictionaryTemplate().
SetAccessorPlaceholderIndices() [1/2]
void v8::internal::anonymous_namespace{literal-objects.cc}::SetAccessorPlaceholderIndices (Tagged< AccessorPair > pair, ClassBoilerplate::ValueKind value_kind, Tagged< Smi > index)
Definition at line 41 of file literal-objects.cc.
                                                      {
  switch (value_kind) {
    case ClassBoilerplate::kGetter:
      pair->set_getter(index);
      break;
    case ClassBoilerplate::kSetter:
      pair->set_setter(index);
      break;
    case ClassBoilerplate::kAutoAccessor:
      // Auto-accessor set the pair of consecutive indices in a single call.
      pair->set_getter(index);
      pair->set_setter(Smi::FromInt(Smi::ToInt(index) + 1));
      break;
    default:
      UNREACHABLE();
  }
}
References v8::internal::Smi::FromInt(), v8::internal::index, v8::internal::ClassBoilerplate::kAutoAccessor, v8::internal::ClassBoilerplate::kGetter, v8::internal::ClassBoilerplate::kSetter, v8::internal::Smi::ToInt(), and v8::internal::UNREACHABLE().
SetAccessorPlaceholderIndices() [2/2]
void v8::internal::anonymous_namespace{literal-objects.cc}::SetAccessorPlaceholderIndices (Tagged< AccessorPair > pair, ClassBoilerplate::ValueKind value_kind, Tagged< Smi > index, ReleaseStoreTag tag)
Definition at line 61 of file literal-objects.cc.
                                                                           {
  switch (value_kind) {
    case ClassBoilerplate::kGetter:
      pair->set_getter(index, tag);
      break;
    case ClassBoilerplate::kSetter:
      pair->set_setter(index, tag);
      break;
    case ClassBoilerplate::kAutoAccessor:
      // Auto-accessor set the pair of consecutive indices in a single call.
      pair->set_getter(index, tag);
      pair->set_setter(Smi::FromInt(Smi::ToInt(index) + 1), tag);
      break;
    default:
      UNREACHABLE();
  }
}
References v8::internal::Smi::FromInt(), v8::internal::index, v8::internal::ClassBoilerplate::kAutoAccessor, v8::internal::ClassBoilerplate::kGetter, v8::internal::ClassBoilerplate::kSetter, v8::internal::Smi::ToInt(), and v8::internal::UNREACHABLE().
Referenced by AddToDescriptorArrayTemplate(), and AddToDictionaryTemplate().
Variable Documentation
kAccessorNotDefined
constexpr int v8::internal::anonymous_namespace{literal-objects.cc}::kAccessorNotDefined = -1 [constexpr]
Definition at line 193 of file literal-objects.cc.
Referenced by AddToDictionaryTemplate(), and GetExistingValueIndex().
kDummyEnumerationIndex
constexpr int v8::internal::anonymous_namespace{literal-objects.cc}::kDummyEnumerationIndex = 0 [constexpr]
Definition at line 31 of file literal-objects.cc.
Referenced by v8::internal::ObjectDescriptor< IsolateT >::AddConstant(), and AddToDictionaryTemplate().