v8_inspector::anonymous_namespace{custom-preview.cc} Namespace Reference
Functions
void reportError (v8::Local< v8::Context > context, const v8::TryCatch &tryCatch)
void reportError (v8::Local< v8::Context > context, const v8::TryCatch &tryCatch, const String16 &message)
InjectedScript * getInjectedScript (v8::Local< v8::Context > context, int sessionId)
bool substituteObjectTags (int sessionId, const String16 &groupName, v8::Local< v8::Context > context, v8::Local< v8::Array > jsonML, int maxDepth)
void bodyCallback (const v8::FunctionCallbackInfo< v8::Value > &info)
Function Documentation
bodyCallback()
void v8_inspector::anonymous_namespace{custom-preview.cc}::bodyCallback (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 161 of file custom-preview.cc.
                                                               {
  v8::Isolate* isolate = v8::Isolate::GetCurrent();
  v8::TryCatch tryCatch(isolate);
  v8::Local<v8::Context> context = isolate->GetCurrentContext();
  v8::Local<v8::Object> bodyConfig = info.Data().As<v8::Object>();
  v8::Local<v8::Value> objectValue;
  if (!bodyConfig->Get(context, toV8String(isolate, "object"))
           .ToLocal(&objectValue)) {
    reportError(context, tryCatch);
    return;
  }
  if (!objectValue->IsObject()) {
    reportError(context, tryCatch, "object should be an Object");
    return;
  }
  v8::Local<v8::Object> object = objectValue.As<v8::Object>();
  v8::Local<v8::Value> formatterValue;
  if (!bodyConfig->Get(context, toV8String(isolate, "formatter"))
           .ToLocal(&formatterValue)) {
    reportError(context, tryCatch);
    return;
  }
  if (!formatterValue->IsObject()) {
    reportError(context, tryCatch, "formatter should be an Object");
    return;
  }
  v8::Local<v8::Object> formatter = formatterValue.As<v8::Object>();
  v8::Local<v8::Value> bodyValue;
  if (!formatter->Get(context, toV8String(isolate, "body"))
           .ToLocal(&bodyValue)) {
    reportError(context, tryCatch);
    return;
  }
  if (!bodyValue->IsFunction()) {
    reportError(context, tryCatch, "body should be a Function");
    return;
  }
  v8::Local<v8::Function> bodyFunction = bodyValue.As<v8::Function>();
  v8::Local<v8::Value> configValue;
  if (!bodyConfig->Get(context, toV8String(isolate, "config"))
           .ToLocal(&configValue)) {
    reportError(context, tryCatch);
    return;
  }
  v8::Local<v8::Value> sessionIdValue;
  if (!bodyConfig->Get(context, toV8String(isolate, "sessionId"))
           .ToLocal(&sessionIdValue)) {
    reportError(context, tryCatch);
    return;
  }
  if (!sessionIdValue->IsInt32()) {
    reportError(context, tryCatch, "sessionId should be an Int32");
    return;
  }
  v8::Local<v8::Value> groupNameValue;
  if (!bodyConfig->Get(context, toV8String(isolate, "groupName"))
           .ToLocal(&groupNameValue)) {
    reportError(context, tryCatch);
    return;
  }
  if (!groupNameValue->IsString()) {
    reportError(context, tryCatch, "groupName should be a string");
    return;
  }
  v8::Local<v8::Value> formattedValue;
  v8::Local<v8::Value> args[] = {object, configValue};
  if (!bodyFunction->Call(context, formatter, 2, args)
           .ToLocal(&formattedValue)) {
    reportError(context, tryCatch);
    return;
  }
  if (formattedValue->IsNull()) {
    info.GetReturnValue().Set(formattedValue);
    return;
  }
  if (!formattedValue->IsArray()) {
    reportError(context, tryCatch, "body should return an Array");
    return;
  }
  v8::Local<v8::Array> jsonML = formattedValue.As<v8::Array>();
  if (jsonML->Length() &&
      !substituteObjectTags(
          sessionIdValue.As<v8::Int32>()->Value(),
          toProtocolString(isolate, groupNameValue.As<v8::String>()), context,
          jsonML, kMaxCustomPreviewDepth)) {
    return;
  }
  info.GetReturnValue().Set(jsonML);
}
References v8::base::args, v8::Local< T >::As(), v8::FunctionCallbackInfo< T >::Data(), v8::Object::Get(), v8::Isolate::GetCurrent(), v8::Isolate::GetCurrentContext(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::Value::IsArray(), v8::Value::IsInt32(), v8::Value::IsNull(), v8::Value::IsString(), v8_inspector::kMaxCustomPreviewDepth, v8::Array::Length(), reportError(), substituteObjectTags(), v8::MaybeLocal< T >::ToLocal(), v8_inspector::toProtocolString(), v8_inspector::toV8String(), and v8::Int32::Value().
Referenced by v8_inspector::generateCustomPreview().
getInjectedScript()
InjectedScript* v8_inspector::anonymous_namespace{custom-preview.cc}::getInjectedScript (v8::Local< v8::Context > context, int sessionId)
Definition at line 57 of file custom-preview.cc.
                                                 {
  v8::Isolate* isolate = v8::Isolate::GetCurrent();
  V8InspectorImpl* inspector =
      static_cast<V8InspectorImpl*>(v8::debug::GetInspector(isolate));
  InspectedContext* inspectedContext =
      inspector->getContext(InspectedContext::contextId(context));
  if (!inspectedContext) return nullptr;
  return inspectedContext->getInjectedScript(sessionId);
}
References v8_inspector::InspectedContext::contextId(), v8_inspector::V8InspectorImpl::getContext(), v8::Isolate::GetCurrent(), v8_inspector::InspectedContext::getInjectedScript(), and v8::debug::GetInspector().
Referenced by v8_inspector::generateCustomPreview(), and substituteObjectTags().
reportError() [1/2]
void v8_inspector::anonymous_namespace{custom-preview.cc}::reportError (v8::Local< v8::Context > context, const v8::TryCatch & tryCatch)
Definition at line 27 of file custom-preview.cc.
                                                                         {
  DCHECK(tryCatch.HasCaught());
  v8::Isolate* isolate = v8::Isolate::GetCurrent();
  V8InspectorImpl* inspector =
      static_cast<V8InspectorImpl*>(v8::debug::GetInspector(isolate));
  int contextId = InspectedContext::contextId(context);
  int groupId = inspector->contextGroupId(contextId);
  v8::Local<v8::String> message = toV8String(isolate, "<no message available>");
  if (!tryCatch.Message().IsEmpty()) message = tryCatch.Message()->Get();
  v8::Local<v8::String> prefix =
      toV8String(isolate, "Custom Formatter Failed: ");
  message = v8::String::Concat(isolate, prefix, message);
  v8::LocalVector<v8::Value> arguments(isolate);
  arguments.push_back(message);
  V8ConsoleMessageStorage* storage =
      inspector->ensureConsoleMessageStorage(groupId);
  if (!storage) return;
  storage->addMessage(V8ConsoleMessage::createForConsoleAPI(
      context, contextId, groupId, inspector,
      inspector->client()->currentTimeMS(), ConsoleAPIType::kError,
      {arguments.begin(), arguments.end()}, String16(), nullptr));
}
References v8_inspector::V8ConsoleMessageStorage::addMessage(), v8_inspector::V8InspectorImpl::client(), v8::String::Concat(), v8_inspector::V8InspectorImpl::contextGroupId(), v8_inspector::InspectedContext::contextId(), v8_inspector::V8ConsoleMessage::createForConsoleAPI(), v8_inspector::V8InspectorClient::currentTimeMS(), DCHECK, v8_inspector::V8InspectorImpl::ensureConsoleMessageStorage(), v8::Isolate::GetCurrent(), v8::debug::GetInspector(), v8::TryCatch::HasCaught(), v8_inspector::kError, v8::TryCatch::Message(), v8::LocalVector< T >::push_back(), and v8_inspector::toV8String().
reportError() [2/2]
void v8_inspector::anonymous_namespace{custom-preview.cc}::reportError (v8::Local< v8::Context > context, const v8::TryCatch & tryCatch, const String16 & message)
Definition at line 50 of file custom-preview.cc.
                                          {
  v8::Isolate* isolate = v8::Isolate::GetCurrent();
  isolate->ThrowException(toV8String(isolate, message));
  reportError(context, tryCatch);
}
References v8::Isolate::GetCurrent(), v8::Isolate::ThrowException(), and v8_inspector::toV8String().
Referenced by bodyCallback(), v8_inspector::generateCustomPreview(), and substituteObjectTags().
substituteObjectTags()
bool v8_inspector::anonymous_namespace{custom-preview.cc}::substituteObjectTags (int sessionId, const String16 & groupName, v8::Local< v8::Context > context, v8::Local< v8::Array > jsonML, int maxDepth)
Definition at line 68 of file custom-preview.cc.
                                                                 {
  if (!jsonML->Length()) return true;
  v8::Isolate* isolate = v8::Isolate::GetCurrent();
  v8::TryCatch tryCatch(isolate);
  if (maxDepth <= 0) {
    reportError(context, tryCatch,
                "Too deep hierarchy of inlined custom previews");
    return false;
  }
  v8::Local<v8::Value> firstValue;
  if (!jsonML->Get(context, 0).ToLocal(&firstValue)) {
    reportError(context, tryCatch);
    return false;
  }
  v8::Local<v8::String> objectLiteral = toV8String(isolate, "object");
  if (jsonML->Length() == 2 && firstValue->IsString() &&
      firstValue.As<v8::String>()->StringEquals(objectLiteral)) {
    v8::Local<v8::Value> attributesValue;
    if (!jsonML->Get(context, 1).ToLocal(&attributesValue)) {
      reportError(context, tryCatch);
      return false;
    }
    if (!attributesValue->IsObject()) {
      reportError(context, tryCatch, "attributes should be an Object");
      return false;
    }
    v8::Local<v8::Object> attributes = attributesValue.As<v8::Object>();
    v8::Local<v8::Value> originValue;
    if (!attributes->Get(context, objectLiteral).ToLocal(&originValue)) {
      reportError(context, tryCatch);
      return false;
    }
    if (originValue->IsUndefined()) {
      reportError(context, tryCatch,
                  "obligatory attribute \"object\" isn't specified");
      return false;
    }
    v8::Local<v8::Value> configValue;
    if (!attributes->Get(context, toV8String(isolate, "config"))
             .ToLocal(&configValue)) {
      reportError(context, tryCatch);
      return false;
    }
    InjectedScript* injectedScript = getInjectedScript(context, sessionId);
    if (!injectedScript) {
      reportError(context, tryCatch, "cannot find context with specified id");
      return false;
    }
    std::unique_ptr<protocol::Runtime::RemoteObject> wrapper;
    protocol::Response response = injectedScript->wrapObject(
        originValue, groupName, WrapOptions({WrapMode::kIdOnly}), configValue,
        maxDepth - 1, &wrapper);
    if (!response.IsSuccess() || !wrapper) {
      reportError(context, tryCatch, "cannot wrap value");
      return false;
    }
    std::vector<uint8_t> json;
    v8_crdtp::json::ConvertCBORToJSON(v8_crdtp::SpanFrom(wrapper->Serialize()),
                                      &json);
    v8::Local<v8::Value> jsonWrapper;
    v8_inspector::StringView serialized(json.data(), json.size());
    if (!v8::JSON::Parse(context, toV8String(isolate, serialized))
             .ToLocal(&jsonWrapper)) {
      reportError(context, tryCatch, "cannot wrap value");
      return false;
    }
    if (jsonML->Set(context, 1, jsonWrapper).IsNothing()) {
      reportError(context, tryCatch);
      return false;
    }
  } else {
    for (uint32_t i = 0; i < jsonML->Length(); ++i) {
      v8::Local<v8::Value> value;
      if (!jsonML->Get(context, i).ToLocal(&value)) {
        reportError(context, tryCatch);
        return false;
      }
      if (value->IsArray() && value.As<v8::Array>()->Length() > 0 &&
          !substituteObjectTags(sessionId, groupName, context,
                                value.As<v8::Array>(), maxDepth - 1)) {
        return false;
      }
    }
  }
  return true;
}
References v8::Local< T >::As(), v8::Object::Get(), v8::Isolate::GetCurrent(), getInjectedScript(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::Value::IsObject(), v8::Value::IsString(), v8_inspector::kIdOnly, v8::Array::Length(), v8::JSON::Parse(), reportError(), v8::Object::Set(), v8::String::StringEquals(), v8::MaybeLocal< T >::ToLocal(), v8_inspector::toV8String(), v8::internal::value, and v8_inspector::InjectedScript::wrapObject().
Referenced by bodyCallback(), and v8_inspector::generateCustomPreview().