v8::internal::anonymous_namespace{experimental-interpreter.cc} Namespace Reference
Classes
class FilterGroups
class NfaInterpreter
Functions
template<class Character >
bool SatisfiesAssertion (RegExpAssertion::Type type, base::Vector< const Character > context, int position)
base::Vector< RegExpInstruction > ToInstructionVector (Tagged< TrustedByteArray > raw_bytes, const DisallowGarbageCollection &no_gc)
template<class Character >
base::Vector< const Character > ToCharacterVector (Tagged< String > str, const DisallowGarbageCollection &no_gc)
template<> base::Vector< const uint8_t > ToCharacterVector< uint8_t > (Tagged< String > str, const DisallowGarbageCollection &no_gc)
template<> base::Vector< const base::uc16 > ToCharacterVector< base::uc16 > (Tagged< String > str, const DisallowGarbageCollection &no_gc)
Variables
constexpr int kUndefinedRegisterValue = -1
constexpr int kUndefinedMatchIndexValue = -1
constexpr uint64_t kUndefinedClockValue = -1
Function Documentation
SatisfiesAssertion()
template<class Character >
bool v8::internal::anonymous_namespace{experimental-interpreter.cc}::SatisfiesAssertion (RegExpAssertion::Type type, base::Vector< const Character > context, int position)
Definition at line 20 of file experimental-interpreter.cc.
                                                                           {
  DCHECK_LE(position, context.length());
  DCHECK_GE(position, 0);
  switch (type) {
    case RegExpAssertion::Type::START_OF_INPUT:
      return position == 0;
    case RegExpAssertion::Type::END_OF_INPUT:
      return position == context.length();
    case RegExpAssertion::Type::START_OF_LINE:
      if (position == 0) return true;
      return unibrow::IsLineTerminator(context[position - 1]);
    case RegExpAssertion::Type::END_OF_LINE:
      if (position == context.length()) return true;
      return unibrow::IsLineTerminator(context[position]);
    case RegExpAssertion::Type::BOUNDARY:
      if (context.length() == 0) {
        return false;
      } else if (position == 0) {
        return IsRegExpWord(context[position]);
      } else if (position == context.length()) {
        return IsRegExpWord(context[position - 1]);
      } else {
        return IsRegExpWord(context[position - 1]) !=
               IsRegExpWord(context[position]);
      }
    case RegExpAssertion::Type::NON_BOUNDARY:
      return !SatisfiesAssertion(RegExpAssertion::Type::BOUNDARY, context,
                                 position);
  }
}
References v8::internal::RegExpAssertion::BOUNDARY, DCHECK_GE, DCHECK_LE, v8::internal::RegExpAssertion::END_OF_INPUT, v8::internal::RegExpAssertion::END_OF_LINE, unibrow::IsLineTerminator(), v8::internal::IsRegExpWord(), v8::base::Vector< T >::length(), v8::internal::RegExpAssertion::NON_BOUNDARY, v8::internal::RegExpAssertion::START_OF_INPUT, v8::internal::RegExpAssertion::START_OF_LINE, and v8::internal::tracing::type.
Referenced by v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::RunActiveThread().
ToCharacterVector()
template<class Character >
base::Vector<const Character> v8::internal::anonymous_namespace{experimental-interpreter.cc}::ToCharacterVector (Tagged< String > str, const DisallowGarbageCollection & no_gc)
ToCharacterVector< base::uc16 >()
template<>
base::Vector<const base::uc16> v8::internal::anonymous_namespace{experimental-interpreter.cc}::ToCharacterVector< base::uc16 > (Tagged< String > str, const DisallowGarbageCollection & no_gc)
Definition at line 64 of file experimental-interpreter.cc.
                                                                {
  DCHECK(str->IsFlat());
  String::FlatContent content = str->GetFlatContent(no_gc);
  DCHECK(content.IsTwoByte());
  return content.ToUC16Vector();
}
ToCharacterVector< uint8_t >()
template<>
base::Vector<const uint8_t> v8::internal::anonymous_namespace{experimental-interpreter.cc}::ToCharacterVector< uint8_t > (Tagged< String > str, const DisallowGarbageCollection & no_gc)
Definition at line 64 of file experimental-interpreter.cc.
                                                                {
  DCHECK(str->IsFlat());
  String::FlatContent content = str->GetFlatContent(no_gc);
  DCHECK(content.IsOneByte());
  return content.ToOneByteVector();
}
ToInstructionVector()
base::Vector<RegExpInstruction> v8::internal::anonymous_namespace{experimental-interpreter.cc}::ToInstructionVector (Tagged< TrustedByteArray > raw_bytes, const DisallowGarbageCollection & no_gc)
Definition at line 53 of file experimental-interpreter.cc.
                                            {
  RegExpInstruction* inst_begin =
      reinterpret_cast<RegExpInstruction*>(raw_bytes->begin());
  int inst_num = raw_bytes->length() / sizeof(RegExpInstruction);
  DCHECK_EQ(sizeof(RegExpInstruction) * inst_num, raw_bytes->length());
  return base::Vector<RegExpInstruction>(inst_begin, inst_num);
}
References DCHECK_EQ.
Referenced by v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::HandleInterrupts().
Variable Documentation
kUndefinedClockValue
constexpr uint64_t v8::internal::anonymous_namespace{experimental-interpreter.cc}::kUndefinedClockValue = -1 [constexpr]
Definition at line 17 of file experimental-interpreter.cc.
Referenced by v8::internal::anonymous_namespace{experimental-interpreter.cc}::FilterGroups::Run().
kUndefinedMatchIndexValue
constexpr int v8::internal::anonymous_namespace{experimental-interpreter.cc}::kUndefinedMatchIndexValue = -1 [constexpr]
Definition at line 16 of file experimental-interpreter.cc.
Referenced by v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::FillLookaroundCaptures(), and v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::NewEmptyThread().
kUndefinedRegisterValue
constexpr int v8::internal::anonymous_namespace{experimental-interpreter.cc}::kUndefinedRegisterValue = -1 [constexpr]
Definition at line 15 of file experimental-interpreter.cc.
Referenced by v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::GetFilteredRegisters(), v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::NewEmptyThread(), and v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::RunActiveThread().