v8::internal::anonymous_namespace{wasm-interpreter-runtime.cc} Namespace Reference
Functions
Address FindInterpreterEntryFramePointer (Isolate *isolate)
Function Documentation
FindInterpreterEntryFramePointer()
Address v8::internal::anonymous_namespace{wasm-interpreter-runtime.cc}::FindInterpreterEntryFramePointer (Isolate * isolate)
Definition at line 52 of file wasm-interpreter-runtime.cc.
                                                           {
  StackFrameIterator it(isolate, isolate->thread_local_top());
  // On top: C entry stub.
  DCHECK_EQ(StackFrame::EXIT, it.frame()->type());
  it.Advance();
  // Next: the wasm interpreter entry.
  DCHECK_EQ(StackFrame::WASM_INTERPRETER_ENTRY, it.frame()->type());
  return it.frame()->fp();
}
References v8::internal::StackFrameIterator::Advance(), DCHECK_EQ, v8::internal::StackFrame::fp(), v8::internal::StackFrameIterator::frame(), v8::internal::Isolate::thread_local_top(), and v8::internal::StackFrame::type().
Referenced by v8::internal::wasm::WasmInterpreterRuntime::CallImportedFunction(), v8::internal::wasm::WasmInterpreterRuntime::ExecuteIndirectCall(), and v8::internal::RUNTIME_FUNCTION().