v8::internal::anonymous_namespace{strings-storage.cc} Namespace Reference
Functions
uint32_t ComputeStringHash (const char *str, size_t len)
Function Documentation
ComputeStringHash()
uint32_t v8::internal::anonymous_namespace{strings-storage.cc}::ComputeStringHash (const char * str, size_t len) [inline]
Definition at line 137 of file strings-storage.cc.
                                                               {
  uint32_t raw_hash_field = base::bits::RotateLeft32(
      StringHasher::HashSequentialString(str, base::checked_cast<uint32_t>(len),
                                         kZeroHashSeed),
      2);
  return Name::HashBits::decode(raw_hash_field);
}
References v8::base::BitField< T, shift, size, U >::decode(), v8::internal::StringHasher::HashSequentialString(), v8::internal::kZeroHashSeed, and v8::base::bits::RotateLeft32().
Referenced by v8::internal::StringsStorage::GetEntry(), and v8::internal::StringsStorage::Release().