v8::internal::anonymous_namespace{map-updater.cc} Namespace Reference
Classes
struct IntegrityLevelTransitionInfo
Functions
bool EqualImmutableValues (Tagged< Object > obj1, Tagged< Object > obj2)
V8_WARN_UNUSED_RESULT DirectHandle< FieldType > GeneralizeFieldType (Representation rep1, DirectHandle< FieldType > type1, Representation rep2, DirectHandle< FieldType > type2, Isolate *isolate)
void PrintGeneralization (Isolate *isolate, DirectHandle< Map > map, FILE *file, const char *reason, InternalIndex modify_index, int split, int descriptors, bool descriptor_to_field, Representation old_representation, Representation new_representation, PropertyConstness old_constness, PropertyConstness new_constness, MaybeDirectHandle< FieldType > old_field_type, MaybeDirectHandle< Object > old_value, MaybeDirectHandle< FieldType > new_field_type, MaybeDirectHandle< Object > new_value)
IntegrityLevelTransitionInfo DetectIntegrityLevelTransitions (Tagged< Map > map, Isolate *isolate, DisallowGarbageCollection *no_gc, ConcurrencyMode cmode)
void PrintReconfiguration (Isolate *isolate, DirectHandle< Map > map, FILE *file, InternalIndex modify_index, PropertyKind kind, PropertyAttributes attributes)
Function Documentation
DetectIntegrityLevelTransitions()
IntegrityLevelTransitionInfo v8::internal::anonymous_namespace{map-updater.cc}::DetectIntegrityLevelTransitions (Tagged< Map > map, Isolate * isolate, DisallowGarbageCollection * no_gc, ConcurrencyMode cmode)
Definition at line 308 of file map-updater.cc.
                           {
  IntegrityLevelTransitionInfo info(map);
  // Figure out the most restrictive integrity level transition (it should
  // be the last one in the transition tree).
  DCHECK(!map->is_extensible());
  Tagged<Map> previous = Cast<Map>(map->GetBackPointer(isolate));
  TransitionsAccessor last_transitions(isolate, previous, IsConcurrent(cmode));
  if (!last_transitions.HasIntegrityLevelTransitionTo(
          map, &info.integrity_level_symbol, &info.integrity_level)) {
    // The last transition was not integrity level transition - just bail out.
    // This can happen in the following cases:
    // - there are private symbol transitions following the integrity level
    // transitions (see crbug.com/v8/8854).
    // - there is a getter added in addition to an existing setter (or a setter
    // in addition to an existing getter).
    return info;
  }
  Tagged<Map> source_map = previous;
  // Now walk up the back pointer chain and skip all integrity level
  // transitions. If we encounter any non-integrity level transition interleaved
  // with integrity level transitions, just bail out.
  while (!source_map->is_extensible()) {
    previous = Cast<Map>(source_map->GetBackPointer(isolate));
    TransitionsAccessor transitions(isolate, previous, IsConcurrent(cmode));
    if (!transitions.HasIntegrityLevelTransitionTo(source_map)) {
      return info;
    }
    source_map = previous;
  }
  // Integrity-level transitions never change number of descriptors.
  CHECK_EQ(map->NumberOfOwnDescriptors(), source_map->NumberOfOwnDescriptors());
  info.has_integrity_level_transition = true;
  info.integrity_level_source_map = source_map;
  return info;
}
References CHECK_EQ, v8::internal::DCHECK(), v8::internal::anonymous_namespace{map-updater.cc}::IntegrityLevelTransitionInfo::has_integrity_level_transition, v8::internal::TransitionsAccessor::HasIntegrityLevelTransitionTo(), v8::internal::anonymous_namespace{map-updater.cc}::IntegrityLevelTransitionInfo::integrity_level, v8::internal::anonymous_namespace{map-updater.cc}::IntegrityLevelTransitionInfo::integrity_level_source_map, v8::internal::anonymous_namespace{map-updater.cc}::IntegrityLevelTransitionInfo::integrity_level_symbol, and v8::internal::IsConcurrent().
Referenced by v8::internal::MapUpdater::TryUpdateNoLock().
EqualImmutableValues()
bool v8::internal::anonymous_namespace{map-updater.cc}::EqualImmutableValues (Tagged< Object > obj1, Tagged< Object > obj2) [inline]
Definition at line 26 of file map-updater.cc.
                                                                           {
  if (obj1 == obj2) return true; // Valid for both kData and kAccessor kinds.
  // TODO(ishell): compare AccessorPairs.
  return false;
}
Referenced by v8::internal::MapUpdater::BuildDescriptorArray(), v8::internal::MapUpdater::FindSplitMap(), and v8::internal::MapUpdater::FindTargetMap().
GeneralizeFieldType()
V8_WARN_UNUSED_RESULT DirectHandle<FieldType> v8::internal::anonymous_namespace{map-updater.cc}::GeneralizeFieldType (Representation rep1, DirectHandle< FieldType > type1, Representation rep2, DirectHandle< FieldType > type2, Isolate * isolate)
Definition at line 32 of file map-updater.cc.
                                                     {
  if (FieldType::NowIs(*type1, type2)) return type2;
  if (FieldType::NowIs(*type2, type1)) return type1;
  return FieldType::Any(isolate);
}
References v8::internal::FieldType::Any(), and v8::internal::FieldType::NowIs().
Referenced by v8::internal::MapUpdater::BuildDescriptorArray(), v8::internal::MapUpdater::GeneralizeField(), v8::internal::MapUpdater::ReconfigureToDataField(), and v8::internal::MapUpdater::UpdateFieldType().
PrintGeneralization()
void v8::internal::anonymous_namespace{map-updater.cc}::PrintGeneralization (Isolate * isolate, DirectHandle< Map > map, FILE * file, const char * reason, InternalIndex modify_index, int split, int descriptors, bool descriptor_to_field, Representation old_representation, Representation new_representation, PropertyConstness old_constness, PropertyConstness new_constness, MaybeDirectHandle< FieldType > old_field_type, MaybeDirectHandle< Object > old_value, MaybeDirectHandle< FieldType > new_field_type, MaybeDirectHandle< Object > new_value)
Definition at line 40 of file map-updater.cc.
                                                              {
  OFStream os(file);
  os << "[generalizing]";
  Tagged<Name> name = map->instance_descriptors(isolate)->GetKey(modify_index);
  if (IsString(name)) {
    Cast<String>(name)->PrintOn(file);
  } else {
    os << "{symbol " << reinterpret_cast<void*>(name.ptr()) << "}";
  }
  os << ":";
  if (descriptor_to_field) {
    os << "c";
  } else {
    os << old_representation.Mnemonic() << "{";
    if (old_field_type.is_null()) {
      os << Brief(*(old_value.ToHandleChecked()));
    } else {
      FieldType::PrintTo(*old_field_type.ToHandleChecked(), os);
    }
    os << ";" << old_constness << "}";
  }
  os << "->" << new_representation.Mnemonic() << "{";
  if (new_field_type.is_null()) {
    os << Brief(*(new_value.ToHandleChecked()));
  } else {
    FieldType::PrintTo(*new_field_type.ToHandleChecked(), os);
  }
  os << ";" << new_constness << "} (";
  if (strlen(reason) > 0) {
    os << reason;
  } else {
    os << "+" << (descriptors - split) << " maps";
  }
  os << ") [";
  JavaScriptFrame::PrintTop(isolate, file, false, true);
  os << "]\n";
}
References file(), v8::internal::MaybeDirectHandle< T >::is_null(), v8::internal::Representation::Mnemonic(), v8::internal::name, v8::internal::FieldType::PrintTo(), v8::internal::JavaScriptFrame::PrintTop(), v8::internal::libvtune::split(), and v8::internal::MaybeDirectHandle< T >::ToHandleChecked().
Referenced by v8::internal::MapUpdater::ConstructNewMap(), v8::internal::MapUpdater::GeneralizeField(), and v8::internal::MapUpdater::TryReconfigureToDataFieldInplace().
PrintReconfiguration()
void v8::internal::anonymous_namespace{map-updater.cc}::PrintReconfiguration (Isolate * isolate, DirectHandle< Map > map, FILE * file, InternalIndex modify_index, PropertyKind kind, PropertyAttributes attributes)
Definition at line 1167 of file map-updater.cc.
                                                         {
  OFStream os(file);
  os << "[reconfiguring]";
  Tagged<Name> name = map->instance_descriptors(isolate)->GetKey(modify_index);
  if (IsString(name)) {
    Cast<String>(name)->PrintOn(file);
  } else {
    os << "{symbol " << reinterpret_cast<void*>(name.ptr()) << "}";
  }
  os << ": " << (kind == PropertyKind::kData ? "kData" : "ACCESSORS")
     << ", attrs: ";
  os << attributes << " [";
  JavaScriptFrame::PrintTop(isolate, file, false, true);
  os << "]\n";
}
References file(), v8::internal::kData, v8::internal::name, and v8::internal::JavaScriptFrame::PrintTop().
Referenced by v8::internal::MapUpdater::ReconfigureExistingProperty().