v8::anonymous_namespace{api.cc} Namespace Reference
Classes
class ArrayBufferAllocator
class ExtensionResource
class ObjectVisitorDeepFreezer
Enumerations
enum class PropertyType { kNamed
, kIndexed
 }
enum class MapAsArrayKind { kEntries = i::JS_MAP_KEY_VALUE_ITERATOR_TYPE
, kKeys = i::JS_MAP_KEY_ITERATOR_TYPE
, kValues = i::JS_MAP_VALUE_ITERATOR_TYPE
 }
enum class SetAsArrayKind { kEntries = i::JS_SET_KEY_VALUE_ITERATOR_TYPE
, kValues = i::JS_SET_VALUE_ITERATOR_TYPE
 }
Functions
static void EnsureNotPublished (i::DirectHandle< i::FunctionTemplateInfo > info, const char *func)
i::DirectHandle< i::FunctionTemplateInfo > FunctionTemplateNew (i::Isolate *i_isolate, FunctionCallback callback, v8::Local< Value > data, v8::Local< Signature > signature, int length, ConstructorBehavior behavior, bool do_not_cache, v8::Local< Private > cached_property_name=v8::Local< Private >(), SideEffectType side_effect_type=SideEffectType::kHasSideEffect, const MemorySpan< const CFunction > &c_function_overloads={})
template<typename Getter , typename Setter >
i::DirectHandle< i::AccessorInfo > MakeAccessorInfo (i::Isolate *i_isolate, v8::Local< Name > name, Getter getter, Setter setter, v8::Local< Value > data, bool replace_on_access)
i::DirectHandle< i::FunctionTemplateInfo > EnsureConstructor (i::Isolate *i_isolate, ObjectTemplate *object_template)
template<typename Getter , typename Setter , typename Data , typename Template >
void TemplateSetAccessor (Template *template_obj, v8::Local< Name > name, Getter getter, Setter setter, Data data, PropertyAttribute attribute, bool replace_on_access, SideEffectType getter_side_effect_type, SideEffectType setter_side_effect_type)
template<PropertyType property_type, typename Getter , typename Setter , typename Query , typename Descriptor , typename Deleter , typename Enumerator , typename Definer >
i::DirectHandle< i::InterceptorInfo > CreateInterceptorInfo (i::Isolate *i_isolate, Getter getter, Setter setter, Query query, Descriptor descriptor, Deleter deleter, Enumerator enumerator, Definer definer, Local< Value > data, base::Flags< PropertyHandlerFlags > flags)
template<typename Getter , typename Setter , typename Query , typename Descriptor , typename Deleter , typename Enumerator , typename Definer >
i::DirectHandle< i::InterceptorInfo > CreateNamedInterceptorInfo (i::Isolate *i_isolate, Getter getter, Setter setter, Query query, Descriptor descriptor, Deleter remover, Enumerator enumerator, Definer definer, Local< Value > data, base::Flags< PropertyHandlerFlags > flags)
template<typename Getter , typename Setter , typename Query , typename Descriptor , typename Deleter , typename Enumerator , typename Definer >
i::DirectHandle< i::InterceptorInfo > CreateIndexedInterceptorInfo (i::Isolate *i_isolate, Getter getter, Setter setter, Query query, Descriptor descriptor, Deleter remover, Enumerator enumerator, Definer definer, Local< Value > data, base::Flags< PropertyHandlerFlags > flags)
template<typename Getter , typename Setter , typename Query , typename Descriptor , typename Deleter , typename Enumerator , typename Definer >
void ObjectTemplateSetNamedPropertyHandler (ObjectTemplate *templ, Getter getter, Setter setter, Query query, Descriptor descriptor, Deleter remover, Enumerator enumerator, Definer definer, Local< Value > data, PropertyHandlerFlags flags)
i::ScriptDetails GetScriptDetails (i::Isolate *i_isolate, Local< Value > resource_name, int resource_line_offset, int resource_column_offset, Local< Value > source_map_url, Local< Data > host_defined_options, ScriptOriginOptions origin_options)
i::MaybeDirectHandle< i::SharedFunctionInfo > CompileStreamedSource (i::Isolate *i_isolate, ScriptCompiler::StreamedSource *v8_source, Local< String > full_source_string, const ScriptOrigin &origin)
i::Tagged< i::Object > ToObject (void *object)
Maybe< bool > SetPrototypeImpl (v8::Object *this_, Local< Context > context, Local< Value > value, bool from_javascript)
MaybeLocal< v8::Context > GetCreationContextImpl (i::DirectHandle< i::JSReceiver > object, i::Isolate *i_isolate)
Local< v8::Context > GetCreationContextCheckedImpl (i::DirectHandle< i::JSReceiver > object, i::Isolate *i_isolate)
void * GetAlignedPointerFromEmbedderDataInCreationContextImpl (i::DirectHandle< i::JSReceiver > object, i::IsolateForSandbox i_isolate_for_sandbox, int index)
base::Vector< i::DirectHandle< i::Object > > PrepareArguments (int argc, Local< Value > argv[])
template<typename Char >
static int WriteUtf8Impl (base::Vector< const Char > string, char *write_start, int write_capacity, int options, int *utf16_chars_read_out)
bool HasExternalStringResource (i::Tagged< i::String > string)
v8::String::ExternalStringResourceBase * GetExternalResourceFromForwardingTable (i::Tagged< i::String > string, uint32_t raw_hash, bool *is_one_byte)
bool MayContainObjectsToFreeze (i::InstanceType obj_type)
bool RequiresEmbedderSupportToFreeze (i::InstanceType obj_type)
bool IsJSReceiverSafeToFreeze (i::InstanceType obj_type)
i::ValueHelper::InternalRepresentationType GetSerializedDataFromFixedArray (i::Isolate *i_isolate, i::Tagged< i::FixedArray > list, size_t index)
int StringLength (const char *string)
int StringLength (const uint8_t *string)
int StringLength (const uint16_t *string)
V8_WARN_UNUSED_RESULT i::MaybeHandle< i::String > NewString (i::Factory *factory, NewStringType type, base::Vector< const char > string)
V8_WARN_UNUSED_RESULT i::MaybeHandle< i::String > NewString (i::Factory *factory, NewStringType type, base::Vector< const uint8_t > string)
V8_WARN_UNUSED_RESULT i::MaybeHandle< i::String > NewString (i::Factory *factory, NewStringType type, base::Vector< const uint16_t > string)
template<typename T >
i::DirectHandle< T > ToHandle (i::Handle< T > h)
template<typename T >
i::DirectHandle< T > ToHandle (i::MaybeHandle< T > h)
template<typename T >
i::DirectHandle< T > ToHandle (i::DirectHandle< T > h)
template<typename T >
i::DirectHandle< T > ToHandle (i::MaybeDirectHandle< T > h)
template<typename Dictionary >
void AddPropertiesAndElementsToObject (i::Isolate *i_isolate, i::DirectHandle< Dictionary > &properties, i::DirectHandle< i::FixedArrayBase > &elements, Local< Name > *names, Local< Value > *values, size_t length)
i::DirectHandle< i::JSArray > MapAsArray (i::Isolate *i_isolate, i::Tagged< i::Object > table_obj, int offset, MapAsArrayKind kind)
i::DirectHandle< i::JSArray > SetAsArray (i::Isolate *i_isolate, i::Tagged< i::Object > table_obj, int offset, SetAsArrayKind kind)
std::shared_ptr< i::BackingStore > ToInternal (std::shared_ptr< i::BackingStoreBase > backing_store)
i::InitializedFlag GetInitializedFlag (BackingStoreInitializationMode initialization_mode)
Enumeration Type Documentation
MapAsArrayKind
enum v8::anonymous_namespace{api.cc}::MapAsArrayKind [strong]
Enumerator
kEntries
kKeys
kValues
Definition at line 8452 of file api.cc.
                          {
  kEntries = i::JS_MAP_KEY_VALUE_ITERATOR_TYPE,
  kKeys = i::JS_MAP_KEY_ITERATOR_TYPE,
  kValues = i::JS_MAP_VALUE_ITERATOR_TYPE
};
PropertyType
enum v8::anonymous_namespace{api.cc}::PropertyType [strong]
Enumerator
kNamed
kIndexed
Definition at line 1483 of file api.cc.
{ kNamed, kIndexed };
SetAsArrayKind
enum v8::anonymous_namespace{api.cc}::SetAsArrayKind [strong]
Enumerator
kEntries
kValues
Definition at line 8458 of file api.cc.
                          {
  kEntries = i::JS_SET_KEY_VALUE_ITERATOR_TYPE,
  kValues = i::JS_SET_VALUE_ITERATOR_TYPE
};
Function Documentation
AddPropertiesAndElementsToObject()
template<typename Dictionary >
void v8::anonymous_namespace{api.cc}::AddPropertiesAndElementsToObject (i::Isolate * i_isolate, i::DirectHandle< Dictionary > & properties, i::DirectHandle< i::FixedArrayBase > & elements, Local< Name > * names, Local< Value > * values, size_t length)
Definition at line 7766 of file api.cc.
                                         {
  for (size_t i = 0; i < length; ++i) {
    auto name = Utils::OpenDirectHandle(*names[i]);
    auto value = Utils::OpenDirectHandle(*values[i]);
    // See if the {name} is a valid array index, in which case we need to
    // add the {name}/{value} pair to the {elements}, otherwise they end
    // up in the {properties} backing store.
    uint32_t index;
    if (name->AsArrayIndex(&index)) {
      // If this is the first element, allocate a proper
      // dictionary elements backing store for {elements}.
      if (!IsNumberDictionary(*elements)) {
        elements =
            i::NumberDictionary::New(i_isolate, static_cast<int>(length));
      }
      elements = i::NumberDictionary::Set(
          i_isolate, i::Cast<i::NumberDictionary>(elements), index, value);
    } else {
      // Internalize the {name} first.
      name = i_isolate->factory()->InternalizeName(name);
      i::InternalIndex const entry = properties->FindEntry(i_isolate, name);
      if (entry.is_not_found()) {
        // Add the {name}/{value} pair as a new entry.
        properties = ToHandle(Dictionary::Add(
            i_isolate, properties, name, value, i::PropertyDetails::Empty()));
      } else {
        // Overwrite the {entry} with the {value}.
        properties->ValueAtPut(entry, *value);
      }
    }
  }
}
References v8::bigint::Add(), v8::internal::PropertyDetails::Empty(), v8::internal::Isolate::factory(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::InternalIndex::is_not_found(), v8::internal::length, name, v8::internal::anonymous_namespace{intl-objects.cc}::New(), v8::Utils::OpenDirectHandle(), ToHandle(), and v8::internal::value.
Referenced by v8::Object::New().
CompileStreamedSource()
i::MaybeDirectHandle<i::SharedFunctionInfo> v8::anonymous_namespace{api.cc}::CompileStreamedSource (i::Isolate * i_isolate, ScriptCompiler::StreamedSource * v8_source, Local< String > full_source_string, const ScriptOrigin & origin)
Definition at line 2650 of file api.cc.
                                                                  {
  auto str = Utils::OpenHandle(*full_source_string);
  i::ScriptDetails script_details =
      GetScriptDetails(i_isolate, origin.ResourceName(), origin.LineOffset(),
                       origin.ColumnOffset(), origin.SourceMapUrl(),
                       origin.GetHostDefinedOptions(), origin.Options());
  i::ScriptStreamingData* data = v8_source->impl();
  i::IsCompiledScope is_compiled_scope;
  return i::Compiler::GetSharedFunctionInfoForStreamedScript(
      i_isolate, str, script_details, data, &is_compiled_scope,
      &v8_source->compilation_details());
}
References v8::ScriptOrigin::ColumnOffset(), v8::ScriptCompiler::StreamedSource::compilation_details(), v8::ScriptOrigin::GetHostDefinedOptions(), GetScriptDetails(), v8::internal::Compiler::GetSharedFunctionInfoForStreamedScript(), v8::ScriptCompiler::StreamedSource::impl(), v8::ScriptOrigin::LineOffset(), v8::Utils::OpenHandle(), v8::ScriptOrigin::Options(), v8::ScriptOrigin::ResourceName(), and v8::ScriptOrigin::SourceMapUrl().
Referenced by v8::ScriptCompiler::Compile(), and v8::ScriptCompiler::CompileModule().
CreateIndexedInterceptorInfo()
template<typename Getter , typename Setter , typename Query , typename Descriptor , typename Deleter , typename Enumerator , typename Definer >
i::DirectHandle<i::InterceptorInfo> v8::anonymous_namespace{api.cc}::CreateIndexedInterceptorInfo (i::Isolate * i_isolate, Getter getter, Setter setter, Query query, Descriptor descriptor, Deleter remover, Enumerator enumerator, Definer definer, Local< Value > data, base::Flags< PropertyHandlerFlags > flags)
Definition at line 1537 of file api.cc.
                                           {
  auto interceptor = CreateInterceptorInfo<PropertyType::kIndexed>(
      i_isolate, getter, setter, query, descriptor, remover, enumerator,
      definer, data, flags);
  return interceptor;
}
References flags(), and v8::internal::setter.
Referenced by v8::ObjectTemplate::SetAccessCheckCallbackAndHandler(), and v8::ObjectTemplate::SetHandler().
CreateInterceptorInfo()
template<PropertyType property_type, typename Getter , typename Setter , typename Query , typename Descriptor , typename Deleter , typename Enumerator , typename Definer >
i::DirectHandle<i::InterceptorInfo> v8::anonymous_namespace{api.cc}::CreateInterceptorInfo (i::Isolate * i_isolate, Getter getter, Setter setter, Query query, Descriptor descriptor, Deleter deleter, Enumerator enumerator, Definer definer, Local< Value > data, base::Flags< PropertyHandlerFlags > flags)
Definition at line 1487 of file api.cc.
                                           {
  // TODO(saelo): instead of an in-sandbox struct with a lot of external
  // pointers (with different tags), consider creating an object in trusted
  // space instead. That way, only a single reference going out of the sandbox
  // would be required.
  auto obj = i_isolate->factory()->NewInterceptorInfo();
  obj->set_is_named(property_type == PropertyType::kNamed);
#define SET_CALLBACK_FIELD(Name, name) \
  if (name != nullptr) { \
    if constexpr (property_type == PropertyType::kNamed) { \
      obj->set_named_##name(i_isolate, reinterpret_cast<i::Address>(name)); \
    } else { \
      obj->set_indexed_##name(i_isolate, reinterpret_cast<i::Address>(name)); \
    } \
  }
  INTERCEPTOR_INFO_CALLBACK_LIST(SET_CALLBACK_FIELD)
#undef SET_CALLBACK_FIELD
  obj->set_can_intercept_symbols(
      !(flags & PropertyHandlerFlags::kOnlyInterceptStrings));
  obj->set_non_masking(flags & PropertyHandlerFlags::kNonMasking);
  obj->set_has_no_side_effect(flags & PropertyHandlerFlags::kHasNoSideEffect);
  if (data.IsEmpty()) {
    data = v8::Undefined(reinterpret_cast<v8::Isolate*>(i_isolate));
  }
  obj->set_data(*Utils::OpenDirectHandle(*data));
  return obj;
}
References v8::internal::Isolate::factory(), flags(), INTERCEPTOR_INFO_CALLBACK_LIST, v8::api_internal::IndirectHandleBase::IsEmpty(), v8::kHasNoSideEffect, v8::kNonMasking, v8::kOnlyInterceptStrings, v8::internal::Factory::NewInterceptorInfo(), v8::Utils::OpenDirectHandle(), SET_CALLBACK_FIELD, and v8::Undefined().
CreateNamedInterceptorInfo()
template<typename Getter , typename Setter , typename Query , typename Descriptor , typename Deleter , typename Enumerator , typename Definer >
i::DirectHandle<i::InterceptorInfo> v8::anonymous_namespace{api.cc}::CreateNamedInterceptorInfo (i::Isolate * i_isolate, Getter getter, Setter setter, Query query, Descriptor descriptor, Deleter remover, Enumerator enumerator, Definer definer, Local< Value > data, base::Flags< PropertyHandlerFlags > flags)
Definition at line 1524 of file api.cc.
                                           {
  auto interceptor = CreateInterceptorInfo<PropertyType::kNamed>(
      i_isolate, getter, setter, query, descriptor, remover, enumerator,
      definer, data, flags);
  return interceptor;
}
References flags(), and v8::internal::setter.
Referenced by ObjectTemplateSetNamedPropertyHandler(), and v8::ObjectTemplate::SetAccessCheckCallbackAndHandler().
EnsureConstructor()
i::DirectHandle<i::FunctionTemplateInfo> v8::anonymous_namespace{api.cc}::EnsureConstructor (i::Isolate * i_isolate, ObjectTemplate * object_template)
Definition at line 1407 of file api.cc.
                                                          {
  i::Tagged<i::Object> obj =
      Utils::OpenDirectHandle(object_template)->constructor();
  if (!IsUndefined(obj, i_isolate)) {
    i::Tagged<i::FunctionTemplateInfo> info =
        i::Cast<i::FunctionTemplateInfo>(obj);
    return i::DirectHandle<i::FunctionTemplateInfo>(info, i_isolate);
  }
  Local<FunctionTemplate> templ =
      FunctionTemplate::New(reinterpret_cast<Isolate*>(i_isolate));
  auto constructor = Utils::OpenDirectHandle(*templ);
  i::FunctionTemplateInfo::SetInstanceTemplate(
      i_isolate, constructor, Utils::OpenDirectHandle(object_template));
  Utils::OpenDirectHandle(object_template)->set_constructor(*constructor);
  return constructor;
}
References v8::FunctionTemplate::New(), and v8::Utils::OpenDirectHandle().
Referenced by v8::CreateEnvironment(), v8::ObjectTemplate::MarkAsUndetectable(), v8::Context::NewRemoteContext(), v8::FunctionTemplate::NewRemoteInstance(), ObjectTemplateSetNamedPropertyHandler(), v8::ObjectTemplate::SetAccessCheckCallback(), v8::ObjectTemplate::SetAccessCheckCallbackAndHandler(), v8::ObjectTemplate::SetCallAsFunctionHandler(), v8::ObjectTemplate::SetHandler(), and v8::ObjectTemplate::SetInternalFieldCount().
EnsureNotPublished()
static void v8::anonymous_namespace{api.cc}::EnsureNotPublished (i::DirectHandle< i::FunctionTemplateInfo > info, const char * func) [static]
Definition at line 1063 of file api.cc.
                                                 {
  DCHECK_IMPLIES(info->instantiated(), info->published());
  Utils::ApiCheck(!info->published(), func,
                  "FunctionTemplate already instantiated");
}
References v8::Utils::ApiCheck(), and DCHECK_IMPLIES.
Referenced by v8::FunctionTemplate::Inherit(), v8::ObjectTemplate::MarkAsUndetectable(), ObjectTemplateSetNamedPropertyHandler(), v8::FunctionTemplate::ReadOnlyPrototype(), v8::FunctionTemplate::RemovePrototype(), v8::FunctionTemplate::SetAcceptAnyReceiver(), v8::ObjectTemplate::SetAccessCheckCallback(), v8::ObjectTemplate::SetAccessCheckCallbackAndHandler(), v8::ObjectTemplate::SetCallAsFunctionHandler(), v8::FunctionTemplate::SetCallHandler(), v8::FunctionTemplate::SetClassName(), v8::FunctionTemplate::SetExceptionContext(), v8::ObjectTemplate::SetHandler(), v8::FunctionTemplate::SetInterfaceName(), and v8::FunctionTemplate::SetLength().
FunctionTemplateNew()
i::DirectHandle<i::FunctionTemplateInfo> v8::anonymous_namespace{api.cc}::FunctionTemplateNew (i::Isolate * i_isolate, FunctionCallback callback, v8::Local< Value > data, v8::Local< Signature > signature, int length, ConstructorBehavior behavior, bool do_not_cache, v8::Local< Private > cached_property_name = v8::Local<Private>(), SideEffectType side_effect_type = SideEffectType::kHasSideEffect, const MemorySpan< const CFunction > & c_function_overloads = {})
Definition at line 1070 of file api.cc.
                                                              {}) {
  i::DirectHandle<i::FunctionTemplateInfo> obj =
      i_isolate->factory()->NewFunctionTemplateInfo(length, do_not_cache);
  {
    // Disallow GC until all fields of obj have acceptable types.
    i::DisallowGarbageCollection no_gc;
    i::Tagged<i::FunctionTemplateInfo> raw = *obj;
    if (!signature.IsEmpty()) {
      raw->set_signature(*Utils::OpenDirectHandle(*signature));
    }
    if (!cached_property_name.IsEmpty()) {
      raw->set_cached_property_name(
          *Utils::OpenDirectHandle(*cached_property_name));
    }
    if (behavior == ConstructorBehavior::kThrow) {
      raw->set_remove_prototype(true);
    }
  }
  if (callback != nullptr) {
    Utils::ToLocal(obj)->SetCallHandler(callback, data, side_effect_type,
                                        c_function_overloads);
  }
  return obj;
}
Referenced by v8::FunctionTemplate::New(), v8::Function::New(), v8::FunctionTemplate::NewWithCache(), and v8::FunctionTemplate::NewWithCFunctionOverloads().
GetAlignedPointerFromEmbedderDataInCreationContextImpl()
void* v8::anonymous_namespace{api.cc}::GetAlignedPointerFromEmbedderDataInCreationContextImpl (i::DirectHandle< i::JSReceiver > object, i::IsolateForSandbox i_isolate_for_sandbox, int index) [inline]
Definition at line 5172 of file api.cc.
                                                         {
  const char* location =
      "v8::Object::GetAlignedPointerFromEmbedderDataInCreationContext()";
  auto maybe_context = object->GetCreationContext();
  if (!maybe_context.has_value()) return nullptr;
  // The code below mostly mimics Context::GetAlignedPointerFromEmbedderData()
  // but it doesn't try to expand the EmbedderDataArray instance.
  i::DisallowGarbageCollection no_gc;
  i::Tagged<i::NativeContext> native_context = maybe_context.value();
  // This macro requires a real Isolate while |i_isolate_for_sandbox| might be
  // nullptr if the V8 sandbox is not enabled.
  i::DisallowJavascriptExecutionDebugOnly no_execution;
  i::DisallowExceptionsDebugOnly no_exceptions;
  // TODO(ishell): remove cast once embedder_data slot has a proper type.
  i::Tagged<i::EmbedderDataArray> data =
      i::Cast<i::EmbedderDataArray>(native_context->embedder_data());
  if (V8_LIKELY(static_cast<unsigned>(index) <
                static_cast<unsigned>(data->length()))) {
    void* result;
    Utils::ApiCheck(i::EmbedderDataSlot(data, index)
                        .ToAlignedPointer(i_isolate_for_sandbox, &result),
                    location, "Pointer is not aligned");
    return result;
  }
  // Bad index, report an API error.
  Utils::ApiCheck(index >= 0, location, "Negative index");
  Utils::ApiCheck(index < i::EmbedderDataArray::kMaxLength, location,
                  "Index too large");
  return nullptr;
}
References v8::Utils::ApiCheck(), v8::internal::index, v8::internal::EmbedderDataArray::kMaxLength, v8::internal::native_context, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, and V8_LIKELY.
Referenced by v8::Object::GetAlignedPointerFromEmbedderDataInCreationContext().
GetCreationContextCheckedImpl()
Local<v8::Context> v8::anonymous_namespace{api.cc}::GetCreationContextCheckedImpl (i::DirectHandle< i::JSReceiver > object, i::Isolate * i_isolate) [inline]
Definition at line 5150 of file api.cc.
                                                            {
  i::DirectHandle<i::NativeContext> context;
  Utils::ApiCheck(object->GetCreationContext(i_isolate).ToHandle(&context),
                  "v8::Object::GetCreationContextChecked",
                  "No creation context available");
  return Utils::ToLocal(context);
}
References v8::Utils::ApiCheck().
Referenced by v8::Object::GetCreationContextChecked().
GetCreationContextImpl()
MaybeLocal<v8::Context> v8::anonymous_namespace{api.cc}::GetCreationContextImpl (i::DirectHandle< i::JSReceiver > object, i::Isolate * i_isolate) [inline]
Definition at line 5122 of file api.cc.
                                                            {
  i::DirectHandle<i::NativeContext> context;
  if (object->GetCreationContext(i_isolate).ToHandle(&context)) {
    return Utils::ToLocal(context);
  }
  return {};
}
Referenced by v8::Object::GetCreationContext().
GetExternalResourceFromForwardingTable()
v8::String::ExternalStringResourceBase* v8::anonymous_namespace{api.cc}::GetExternalResourceFromForwardingTable (i::Tagged< i::String > string, uint32_t raw_hash, bool * is_one_byte)
Definition at line 5950 of file api.cc.
                                                                   {
  DCHECK(i::String::IsExternalForwardingIndex(raw_hash));
  const int index = i::String::ForwardingIndexValueBits::decode(raw_hash);
  // Note that with a shared heap the main and worker isolates all share the
  // same forwarding table.
  auto resource =
      i::Isolate::Current()->string_forwarding_table()->GetExternalResource(
          index, is_one_byte);
  DCHECK_NOT_NULL(resource);
  return resource;
}
References v8::internal::Isolate::Current(), DCHECK, DCHECK_NOT_NULL, v8::internal::index, and v8::internal::Name::IsExternalForwardingIndex().
Referenced by v8::String::GetExternalOneByteStringResource(), v8::String::GetExternalStringResourceBaseSlow(), v8::String::GetExternalStringResourceSlow(), v8::String::IsExternalOneByte(), v8::String::IsExternalTwoByte(), v8::String::VerifyExternalStringResource(), and v8::String::VerifyExternalStringResourceBase().
GetInitializedFlag()
i::InitializedFlag v8::anonymous_namespace{api.cc}::GetInitializedFlag (BackingStoreInitializationMode initialization_mode)
Definition at line 8970 of file api.cc.
                                                        {
  switch (initialization_mode) {
    case BackingStoreInitializationMode::kUninitialized:
      return i::InitializedFlag::kUninitialized;
    case BackingStoreInitializationMode::kZeroInitialized:
      return i::InitializedFlag::kZeroInitialized;
  }
  UNREACHABLE();
}
References v8::kUninitialized, v8::internal::kUninitialized, v8::kZeroInitialized, and UNREACHABLE.
Referenced by v8::ArrayBuffer::MaybeNew(), v8::SharedArrayBuffer::MaybeNew(), v8::ArrayBuffer::New(), v8::SharedArrayBuffer::New(), v8::ArrayBuffer::NewBackingStore(), and v8::SharedArrayBuffer::NewBackingStore().
GetScriptDetails()
i::ScriptDetails v8::anonymous_namespace{api.cc}::GetScriptDetails (i::Isolate * i_isolate, Local< Value > resource_name, int resource_line_offset, int resource_column_offset, Local< Value > source_map_url, Local< Data > host_defined_options, ScriptOriginOptions origin_options)
Definition at line 2377 of file api.cc.
                                                                          {
  i::ScriptDetails script_details(Utils::OpenHandle(*(resource_name), true),
                                  origin_options);
  script_details.line_offset = resource_line_offset;
  script_details.column_offset = resource_column_offset;
  script_details.host_defined_options =
      host_defined_options.IsEmpty()
          ? i_isolate->factory()->empty_fixed_array()
          : Utils::OpenHandle(*(host_defined_options));
  if (!source_map_url.IsEmpty()) {
    script_details.source_map_url = Utils::OpenHandle(*(source_map_url));
  }
  return script_details;
}
References v8::internal::ScriptDetails::column_offset, v8::internal::Isolate::factory(), v8::internal::ScriptDetails::host_defined_options, v8::api_internal::IndirectHandleBase::IsEmpty(), v8::internal::ScriptDetails::line_offset, v8::Utils::OpenHandle(), and v8::internal::ScriptDetails::source_map_url.
Referenced by v8::ScriptCompiler::CompileFunction(), CompileStreamedSource(), v8::ScriptCompiler::CompileUnboundInternal(), and v8::ScriptCompiler::ConsumeCodeCacheTask::SourceTextAvailable().
GetSerializedDataFromFixedArray()
i::ValueHelper::InternalRepresentationType v8::anonymous_namespace{api.cc}::GetSerializedDataFromFixedArray (i::Isolate * i_isolate, i::Tagged< i::FixedArray > list, size_t index)
Definition at line 7296 of file api.cc.
                                                                  {
  if (index < static_cast<size_t>(list->length())) {
    int int_index = static_cast<int>(index);
    i::Tagged<i::Object> object = list->get(int_index);
    if (!IsTheHole(object, i_isolate)) {
      list->set_the_hole(i_isolate, int_index);
      // Shrink the list so that the last element is not the hole (unless it's
      // the first element, because we don't want to end up with a non-canonical
      // empty FixedArray).
      int last = list->length() - 1;
      while (last >= 0 && list->is_the_hole(i_isolate, last)) last--;
      if (last != -1) list->RightTrim(i_isolate, last + 1);
      return i::Handle<i::Object>(object, i_isolate).repr();
    }
  }
  return i::ValueHelper::kEmpty;
}
References v8::internal::index, v8::internal::ValueHelper::kEmpty, and v8::internal::HandleBase::repr().
Referenced by v8::Context::GetDataFromSnapshotOnce(), and v8::Isolate::GetDataFromSnapshotOnce().
HasExternalStringResource()
bool v8::anonymous_namespace{api.cc}::HasExternalStringResource (i::Tagged< i::String > string)
Definition at line 5945 of file api.cc.
                                                        {
  return i::StringShape(string).IsExternal() ||
         string->HasExternalForwardingIndex(kAcquireLoad);
}
References v8::internal::StringShape::IsExternal(), and v8::kAcquireLoad.
Referenced by v8::String::IsExternal(), and v8::String::MakeExternal().
IsJSReceiverSafeToFreeze()
bool v8::anonymous_namespace{api.cc}::IsJSReceiverSafeToFreeze (i::InstanceType obj_type)
Definition at line 6834 of file api.cc.
                                                      {
  DCHECK(i::InstanceTypeChecker::IsJSReceiver(obj_type));
  switch (obj_type) {
    case i::JS_OBJECT_TYPE:
    case i::JS_GLOBAL_OBJECT_TYPE:
    case i::JS_GLOBAL_PROXY_TYPE:
    case i::JS_PRIMITIVE_WRAPPER_TYPE:
    case i::JS_FUNCTION_TYPE:
    /* Function types */
    case i::BIGINT64_TYPED_ARRAY_CONSTRUCTOR_TYPE:
    case i::BIGUINT64_TYPED_ARRAY_CONSTRUCTOR_TYPE:
    case i::FLOAT16_TYPED_ARRAY_CONSTRUCTOR_TYPE:
    case i::FLOAT32_TYPED_ARRAY_CONSTRUCTOR_TYPE:
    case i::FLOAT64_TYPED_ARRAY_CONSTRUCTOR_TYPE:
    case i::INT16_TYPED_ARRAY_CONSTRUCTOR_TYPE:
    case i::INT32_TYPED_ARRAY_CONSTRUCTOR_TYPE:
    case i::INT8_TYPED_ARRAY_CONSTRUCTOR_TYPE:
    case i::UINT16_TYPED_ARRAY_CONSTRUCTOR_TYPE:
    case i::UINT32_TYPED_ARRAY_CONSTRUCTOR_TYPE:
    case i::UINT8_CLAMPED_TYPED_ARRAY_CONSTRUCTOR_TYPE:
    case i::UINT8_TYPED_ARRAY_CONSTRUCTOR_TYPE:
    case i::JS_ARRAY_CONSTRUCTOR_TYPE:
    case i::JS_PROMISE_CONSTRUCTOR_TYPE:
    case i::JS_REG_EXP_CONSTRUCTOR_TYPE:
    case i::JS_CLASS_CONSTRUCTOR_TYPE:
    /* Prototype Types */
    case i::JS_ARRAY_ITERATOR_PROTOTYPE_TYPE:
    case i::JS_ITERATOR_PROTOTYPE_TYPE:
    case i::JS_MAP_ITERATOR_PROTOTYPE_TYPE:
    case i::JS_OBJECT_PROTOTYPE_TYPE:
    case i::JS_PROMISE_PROTOTYPE_TYPE:
    case i::JS_REG_EXP_PROTOTYPE_TYPE:
    case i::JS_SET_ITERATOR_PROTOTYPE_TYPE:
    case i::JS_SET_PROTOTYPE_TYPE:
    case i::JS_STRING_ITERATOR_PROTOTYPE_TYPE:
    case i::JS_TYPED_ARRAY_PROTOTYPE_TYPE:
    /* */
    case i::JS_ARRAY_TYPE:
      return true;
#if V8_ENABLE_WEBASSEMBLY
    case i::WASM_ARRAY_TYPE:
    case i::WASM_STRUCT_TYPE:
    case i::WASM_TAG_OBJECT_TYPE:
#endif // V8_ENABLE_WEBASSEMBLY
    case i::JS_PROXY_TYPE:
      return true;
    // These types are known not to freeze.
    case i::JS_MAP_KEY_ITERATOR_TYPE:
    case i::JS_MAP_KEY_VALUE_ITERATOR_TYPE:
    case i::JS_MAP_VALUE_ITERATOR_TYPE:
    case i::JS_SET_KEY_VALUE_ITERATOR_TYPE:
    case i::JS_SET_VALUE_ITERATOR_TYPE:
    case i::JS_GENERATOR_OBJECT_TYPE:
    case i::JS_ASYNC_FUNCTION_OBJECT_TYPE:
    case i::JS_ASYNC_GENERATOR_OBJECT_TYPE:
    case i::JS_ARRAY_ITERATOR_TYPE: {
      return false;
    }
    default:
      // TODO(behamilton): Handle any types that fall through here.
      return false;
  }
}
References DCHECK.
Referenced by v8::anonymous_namespace{api.cc}::ObjectVisitorDeepFreezer::VisitObject().
MakeAccessorInfo()
template<typename Getter , typename Setter >
i::DirectHandle<i::AccessorInfo> v8::anonymous_namespace{api.cc}::MakeAccessorInfo (i::Isolate * i_isolate, v8::Local< Name > name, Getter getter, Setter setter, v8::Local< Value > data, bool replace_on_access)
Definition at line 1279 of file api.cc.
                                                                          {
  i::DirectHandle<i::AccessorInfo> obj =
      i_isolate->factory()->NewAccessorInfo();
  obj->set_getter(i_isolate, reinterpret_cast<i::Address>(getter));
  DCHECK_IMPLIES(replace_on_access, setter == nullptr);
  if (setter == nullptr) {
    setter = reinterpret_cast<Setter>(&i::Accessors::ReconfigureToDataProperty);
  }
  obj->set_setter(i_isolate, reinterpret_cast<i::Address>(setter));
  auto accessor_name = Utils::OpenDirectHandle(*name);
  if (!IsUniqueName(*accessor_name)) {
    accessor_name = i_isolate->factory()->InternalizeString(
        i::Cast<i::String>(accessor_name));
  }
  i::DisallowGarbageCollection no_gc;
  i::Tagged<i::AccessorInfo> raw_obj = *obj;
  if (data.IsEmpty()) {
    raw_obj->set_data(i::ReadOnlyRoots(i_isolate).undefined_value());
  } else {
    raw_obj->set_data(*Utils::OpenDirectHandle(*data));
  }
  raw_obj->set_name(*accessor_name);
  raw_obj->set_replace_on_access(replace_on_access);
  raw_obj->set_initial_property_attributes(i::NONE);
  return obj;
}
References DCHECK_IMPLIES, v8::internal::Isolate::factory(), v8::internal::Factory::InternalizeString(), v8::api_internal::IndirectHandleBase::IsEmpty(), v8::internal::IsUniqueName(), name, v8::internal::Factory::NewAccessorInfo(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::NONE, v8::Utils::OpenDirectHandle(), and v8::internal::setter.
Referenced by v8::ObjectSetAccessor(), and TemplateSetAccessor().
MapAsArray()
i::DirectHandle<i::JSArray> v8::anonymous_namespace{api.cc}::MapAsArray (i::Isolate * i_isolate, i::Tagged< i::Object > table_obj, int offset, MapAsArrayKind kind)
Definition at line 8463 of file api.cc.
                                                                        {
  i::Factory* factory = i_isolate->factory();
  i::DirectHandle<i::OrderedHashMap> table(
      i::Cast<i::OrderedHashMap>(table_obj), i_isolate);
  const bool collect_keys =
      kind == MapAsArrayKind::kEntries || kind == MapAsArrayKind::kKeys;
  const bool collect_values =
      kind == MapAsArrayKind::kEntries || kind == MapAsArrayKind::kValues;
  int capacity = table->UsedCapacity();
  int max_length =
      (capacity - offset) * ((collect_keys && collect_values) ? 2 : 1);
  i::DirectHandle<i::FixedArray> result = factory->NewFixedArray(max_length);
  int result_index = 0;
  {
    i::DisallowGarbageCollection no_gc;
    i::Tagged<i::Hole> hash_table_hole =
        i::ReadOnlyRoots(i_isolate).hash_table_hole_value();
    for (int i = offset; i < capacity; ++i) {
      i::InternalIndex entry(i);
      i::Tagged<i::Object> key = table->KeyAt(entry);
      if (key == hash_table_hole) continue;
      if (collect_keys) result->set(result_index++, key);
      if (collect_values) result->set(result_index++, table->ValueAt(entry));
    }
  }
  DCHECK_GE(max_length, result_index);
  if (result_index == 0) return factory->NewJSArray(0);
  result->RightTrim(i_isolate, result_index);
  return factory->NewJSArrayWithElements(result, i::PACKED_ELEMENTS,
                                         result_index);
}
References DCHECK_GE, v8::internal::Isolate::factory(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::key, v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::Factory::NewJSArray(), v8::internal::Factory::NewJSArrayWithElements(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::PACKED_ELEMENTS, and v8::base::internal::result.
Referenced by v8::Map::AsArray(), and v8::Object::PreviewEntries().
MayContainObjectsToFreeze()
bool v8::anonymous_namespace{api.cc}::MayContainObjectsToFreeze (i::InstanceType obj_type)
Definition at line 6816 of file api.cc.
                                                       {
  if (i::InstanceTypeChecker::IsString(obj_type)) return false;
  // SharedFunctionInfo is cross-context so it shouldn't be frozen.
  if (i::InstanceTypeChecker::IsSharedFunctionInfo(obj_type)) return false;
  // All TemplateInfo objects are cross-context so they shouldn't be frozen.
  if (i::InstanceTypeChecker::IsTemplateInfo(obj_type)) return false;
  return true;
}
Referenced by v8::anonymous_namespace{api.cc}::ObjectVisitorDeepFreezer::VisitObject().
NewString() [1/3]
V8_WARN_UNUSED_RESULT i::MaybeHandle<i::String> v8::anonymous_namespace{api.cc}::NewString (i::Factory * factory, NewStringType type, base::Vector< const char > string) [inline]
Definition at line 7497 of file api.cc.
                                                                          {
  if (type == NewStringType::kInternalized) {
    return factory->InternalizeUtf8String(string);
  }
  return factory->NewStringFromUtf8(string);
}
References v8::internal::Factory::InternalizeUtf8String(), v8::kInternalized, v8::internal::Factory::NewStringFromUtf8(), and v8::internal::tracing::type.
NewString() [2/3]
V8_WARN_UNUSED_RESULT i::MaybeHandle<i::String> v8::anonymous_namespace{api.cc}::NewString (i::Factory * factory, NewStringType type, base::Vector< const uint16_t > string) [inline]
Definition at line 7517 of file api.cc.
                                       {
  if (type == NewStringType::kInternalized) {
    return factory->InternalizeString(string);
  }
  return factory->NewStringFromTwoByte(string);
}
References v8::internal::Factory::InternalizeString(), v8::kInternalized, v8::internal::Factory::NewStringFromTwoByte(), and v8::internal::tracing::type.
Referenced by v8::String::NewFromUtf8Literal().
NewString() [3/3]
V8_WARN_UNUSED_RESULT i::MaybeHandle<i::String> v8::anonymous_namespace{api.cc}::NewString (i::Factory * factory, NewStringType type, base::Vector< const uint8_t > string) [inline]
Definition at line 7507 of file api.cc.
                                                                             {
  if (type == NewStringType::kInternalized) {
    return factory->InternalizeString(string);
  }
  return factory->NewStringFromOneByte(string);
}
References v8::internal::Factory::InternalizeString(), v8::kInternalized, v8::internal::FactoryBase< Impl >::NewStringFromOneByte(), and v8::internal::tracing::type.
ObjectTemplateSetNamedPropertyHandler()
template<typename Getter , typename Setter , typename Query , typename Descriptor , typename Deleter , typename Enumerator , typename Definer >
void v8::anonymous_namespace{api.cc}::ObjectTemplateSetNamedPropertyHandler (ObjectTemplate * templ, Getter getter, Setter setter, Query query, Descriptor descriptor, Deleter remover, Enumerator enumerator, Definer definer, Local< Value > data, PropertyHandlerFlags flags)
Definition at line 1550 of file api.cc.
                                                                    {
  i::Isolate* i_isolate = i::Isolate::Current();
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::HandleScope scope(i_isolate);
  auto cons = EnsureConstructor(i_isolate, templ);
  EnsureNotPublished(cons, "ObjectTemplateSetNamedPropertyHandler");
  auto obj =
      CreateNamedInterceptorInfo(i_isolate, getter, setter, query, descriptor,
                                 remover, enumerator, definer, data, flags);
  i::FunctionTemplateInfo::SetNamedPropertyHandler(i_isolate, cons, obj);
}
References CreateNamedInterceptorInfo(), v8::internal::Isolate::Current(), EnsureConstructor(), EnsureNotPublished(), flags(), and v8::internal::setter.
Referenced by v8::ObjectTemplate::SetHandler().
PrepareArguments()
base::Vector<i::DirectHandle<i::Object> > v8::anonymous_namespace{api.cc}::PrepareArguments (int argc, Local< Value > argv[])
Definition at line 5256 of file api.cc.
                                                                               {
  static_assert(sizeof(v8::Local<v8::Value>) ==
                sizeof(i::DirectHandle<i::Object>));
  return {reinterpret_cast<i::DirectHandle<i::Object>*>(argv),
          static_cast<size_t>(argc)};
}
Referenced by v8::Function::Call(), v8::Object::CallAsConstructor(), v8::Object::CallAsFunction(), and v8::Function::NewInstanceWithSideEffectType().
RequiresEmbedderSupportToFreeze()
bool v8::anonymous_namespace{api.cc}::RequiresEmbedderSupportToFreeze (i::InstanceType obj_type)
Definition at line 6825 of file api.cc.
                                                             {
  DCHECK(i::InstanceTypeChecker::IsJSReceiver(obj_type));
  return (i::InstanceTypeChecker::IsJSApiObject(obj_type) ||
          i::InstanceTypeChecker::IsJSExternalObject(obj_type) ||
          i::InstanceTypeChecker::IsJSAPIObjectWithEmbedderSlots(obj_type) ||
          i::InstanceTypeChecker::IsCppHeapExternalObject(obj_type));
}
References DCHECK.
Referenced by v8::anonymous_namespace{api.cc}::ObjectVisitorDeepFreezer::VisitObject().
SetAsArray()
i::DirectHandle<i::JSArray> v8::anonymous_namespace{api.cc}::SetAsArray (i::Isolate * i_isolate, i::Tagged< i::Object > table_obj, int offset, SetAsArrayKind kind)
Definition at line 8567 of file api.cc.
                                                                        {
  i::Factory* factory = i_isolate->factory();
  i::DirectHandle<i::OrderedHashSet> table(
      i::Cast<i::OrderedHashSet>(table_obj), i_isolate);
  // Elements skipped by |offset| may already be deleted.
  int capacity = table->UsedCapacity();
  const bool collect_key_values = kind == SetAsArrayKind::kEntries;
  int max_length = (capacity - offset) * (collect_key_values ? 2 : 1);
  if (max_length == 0) return factory->NewJSArray(0);
  i::DirectHandle<i::FixedArray> result = factory->NewFixedArray(max_length);
  int result_index = 0;
  {
    i::DisallowGarbageCollection no_gc;
    i::Tagged<i::Hole> hash_table_hole =
        i::ReadOnlyRoots(i_isolate).hash_table_hole_value();
    for (int i = offset; i < capacity; ++i) {
      i::InternalIndex entry(i);
      i::Tagged<i::Object> key = table->KeyAt(entry);
      if (key == hash_table_hole) continue;
      result->set(result_index++, key);
      if (collect_key_values) result->set(result_index++, key);
    }
  }
  DCHECK_GE(max_length, result_index);
  if (result_index == 0) return factory->NewJSArray(0);
  result->RightTrim(i_isolate, result_index);
  return factory->NewJSArrayWithElements(result, i::PACKED_ELEMENTS,
                                         result_index);
}
References DCHECK_GE, v8::internal::Isolate::factory(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::key, v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::Factory::NewJSArray(), v8::internal::Factory::NewJSArrayWithElements(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::PACKED_ELEMENTS, and v8::base::internal::result.
Referenced by v8::Set::AsArray(), and v8::Object::PreviewEntries().
SetPrototypeImpl()
Maybe<bool> v8::anonymous_namespace{api.cc}::SetPrototypeImpl (v8::Object * this_, Local< Context > context, Local< Value > value, bool from_javascript)
Definition at line 4663 of file api.cc.
                                                                       {
  auto i_isolate = i::Isolate::Current();
  auto self = Utils::OpenDirectHandle(this_);
  auto value_obj = Utils::OpenDirectHandle(*value);
  // TODO(333672197): turn this to DCHECK once it's no longer possible
  // to get JSGlobalObject via API.
  CHECK_IMPLIES(from_javascript, !i::IsJSGlobalObject(*value_obj));
  if (i::IsJSObject(*self)) {
    EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
    // TODO(333672197): turn this to DCHECK once it's no longer possible
    // to get JSGlobalObject via API.
    CHECK_IMPLIES(from_javascript, !i::IsJSGlobalObject(*self));
    auto result =
        i::JSObject::SetPrototype(i_isolate, i::Cast<i::JSObject>(self),
                                  value_obj, from_javascript, i::kDontThrow);
    // Convert Just(false) to Nothing.
    if (!result.FromJust()) return {};
    return result;
  }
  if (i::IsJSProxy(*self)) {
    EnterV8Scope<> api_scope{i_isolate, context,
                             RCCId::kAPI_Object_SetPrototype};
    // We do not allow exceptions thrown while setting the prototype
    // to propagate outside.
    TryCatch try_catch(reinterpret_cast<v8::Isolate*>(i_isolate));
    auto result =
        i::JSProxy::SetPrototype(i_isolate, i::Cast<i::JSProxy>(self),
                                 value_obj, from_javascript, i::kThrowOnError);
    if (result.IsNothing()) return {};
    // Convert Just(false) to Just(true).
    return Just(true);
  }
  // Wasm object or other kind of special object not supported here.
  return {};
}
References CHECK_IMPLIES, v8::internal::Isolate::Current(), v8::Just(), v8::internal::kDontThrow, v8::internal::kThrowOnError, v8::Utils::OpenDirectHandle(), v8::base::internal::result, v8::internal::JSObject::SetPrototype(), v8::internal::JSProxy::SetPrototype(), and v8::internal::value.
Referenced by v8::Object::SetPrototypeV2().
StringLength() [1/3]
int v8::anonymous_namespace{api.cc}::StringLength (const char * string) [inline]
Definition at line 7479 of file api.cc.
                                            {
  size_t len = strlen(string);
  CHECK_GE(i::kMaxInt, len);
  return static_cast<int>(len);
}
References CHECK_GE, and v8::internal::kMaxInt.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildLoadStringLength(), v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyLoad(), v8::internal::compiler::JSTypedLowering::GenerateStringAddition(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementAccessOnString(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadNamed(), v8::internal::compiler::JSCallReducer::ReduceStringIteratorPrototypeNext(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeConcat(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeIndexOfIncludes(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeStringCodePointAt(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeSubstr(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::StringConcatHelper().
StringLength() [2/3]
int v8::anonymous_namespace{api.cc}::StringLength (const uint16_t * string) [inline]
Definition at line 7489 of file api.cc.
                                                {
  size_t length = 0;
  while (string[length] != '\0') length++;
  CHECK_GE(i::kMaxInt, length);
  return static_cast<int>(length);
}
References CHECK_GE, v8::internal::kMaxInt, and v8::internal::length.
Referenced by StringLength().
StringLength() [3/3]
int v8::anonymous_namespace{api.cc}::StringLength (const uint8_t * string) [inline]
Definition at line 7485 of file api.cc.
                                               {
  return StringLength(reinterpret_cast<const char*>(string));
}
References StringLength().
TemplateSetAccessor()
template<typename Getter , typename Setter , typename Data , typename Template >
void v8::anonymous_namespace{api.cc}::TemplateSetAccessor (Template * template_obj, v8::Local< Name > name, Getter getter, Setter setter, Data data, PropertyAttribute attribute, bool replace_on_access, SideEffectType getter_side_effect_type, SideEffectType setter_side_effect_type)
Definition at line 1426 of file api.cc.
                                                                 {
  auto info = Utils::OpenDirectHandle(template_obj);
  auto i_isolate = info->GetIsolateChecked();
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::HandleScope scope(i_isolate);
  i::DirectHandle<i::AccessorInfo> accessor_info = MakeAccessorInfo(
      i_isolate, name, getter, setter, data, replace_on_access);
  {
    i::DisallowGarbageCollection no_gc;
    i::Tagged<i::AccessorInfo> raw = *accessor_info;
    raw->set_initial_property_attributes(
        static_cast<i::PropertyAttributes>(attribute));
    raw->set_getter_side_effect_type(getter_side_effect_type);
    raw->set_setter_side_effect_type(setter_side_effect_type);
  }
  i::ApiNatives::AddNativeDataProperty(i_isolate, info, accessor_info);
}
References v8::internal::ApiNatives::AddNativeDataProperty(), v8::internal::getter_side_effect_type, MakeAccessorInfo(), name, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::Utils::OpenDirectHandle(), and v8::internal::setter.
Referenced by v8::Template::SetLazyDataProperty(), and v8::Template::SetNativeDataProperty().
ToHandle() [1/4]
template<typename T >
i::DirectHandle<T> v8::anonymous_namespace{api.cc}::ToHandle (i::DirectHandle< T > h)
Definition at line 7757 of file api.cc.
                                              {
  return h;
}
References h().
ToHandle() [2/4]
template<typename T >
i::DirectHandle<T> v8::anonymous_namespace{api.cc}::ToHandle (i::Handle< T > h)
Definition at line 7748 of file api.cc.
                                        {
  return h;
}
References h().
Referenced by v8::internal::MutableBigInt::AbsoluteAddOne(), v8::internal::BigInt::Add(), v8::internal::JSArray::AnythingToArrayLength(), v8::internal::SourceTextModule::AsyncModuleExecutionFulfilled(), v8::internal::BUILTIN(), v8::internal::anonymous_namespace{isolate.cc}::CaptureAsyncStackTrace(), v8::internal::anonymous_namespace{wasm-debug.cc}::CheckBreakPoint(), v8::internal::WasmScript::ClearBreakPointById(), v8::internal::Object::Compare(), v8::internal::anonymous_namespace{compiler.cc}::CompilationExceptionIsRangeError(), v8::internal::Compiler::Compile(), v8::internal::Compiler::CompileOptimized(), v8::internal::anonymous_namespace{runtime-compiler.cc}::CompileOptimizedOSR(), v8::internal::Compiler::CompileSharedWithBaseline(), v8::internal::wasm::JSPrototypesSetup::ConfigurePrototypes_Modular_Impl(), v8::internal::anonymous_namespace{externalize-string-extension.cc}::CreateExternalizableString(), v8::internal::BigInt::Divide(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::EncodeExceptionValues(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::EnforceBigIntUint64(), v8::internal::Object::Equals(), v8::internal::DebugEvaluate::Evaluate(), v8::internal::SourceTextModule::ExecuteModule(), v8::internal::DebugPropertyIterator::FillKeysForCurrentPrototypeAndStage(), v8::internal::FrameFunctionIterator::Find(), v8::internal::FrameFunctionIterator::FindNextNonTopLevelNativeOrUserJavaScript(), v8::internal::BigInt::FromWords64(), v8::internal::Genesis::Genesis(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::GetAddressType(), v8::internal::CallSiteInfo::GetColumnNumber(), v8::internal::anonymous_namespace{isolate.cc}::GetDetailedStackTraceFromCallSiteInfos(), v8::internal::CallSiteInfo::GetEnclosingColumnNumber(), v8::internal::CallSiteInfo::GetEnclosingLineNumber(), v8::internal::CallSiteInfo::GetEvalOrigin(), v8::internal::Compiler::GetFunctionFromEval(), v8::internal::CallSiteInfo::GetFunctionName(), v8::internal::Isolate::GetImportAttributesFromArgument(), v8::internal::wasm::JSPrototypesSetup::GetImportedObject(), v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::GetInternalImpl(), v8::debug::GetInternalProperties(), v8::internal::FastKeyAccumulator::GetKeys(), v8::internal::FastKeyAccumulator::GetKeysFast(), v8::internal::CallSiteInfo::GetLineNumber(), v8::internal::anonymous_namespace{compiler.cc}::GetOrCompileOptimized(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::GetOrCreateInstanceProxyCache(), v8::internal::JSReceiver::GetOwnPropertyDescriptor(), v8::internal::anonymous_namespace{property-descriptor.cc}::GetPropertyIfPresent(), v8::internal::CallSiteInfo::GetScriptHash(), v8::anonymous_namespace{wasm-js.cc}::GetValueType(), v8::internal::DebugEvaluate::Global(), v8::internal::SourceTextModule::InnerModuleEvaluation(), v8::internal::anonymous_namespace{api-natives.cc}::InstantiateFunction(), v8::internal::anonymous_namespace{builtins-string.cc}::IsValidCodePoint(), v8::internal::wasm::WasmInterpreterRuntime::JSToWasmObject(), v8::internal::BigInt::Multiply(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::ContextProxyPrototype::NamedGetter(), v8::internal::JsonParser< Char >::ParseJsonArray(), v8::internal::JsonParser< Char >::ParseJsonPropertyValue(), v8::internal::ValueDeserializer::ReadDenseJSArray(), v8::internal::ValueDeserializer::ReadJSArrayBuffer(), v8::internal::ValueDeserializer::ReadJSError(), v8::internal::ValueDeserializer::ReadJSMap(), v8::internal::ValueDeserializer::ReadJSObjectProperties(), v8::internal::ValueDeserializer::ReadJSPrimitiveWrapper(), v8::internal::ValueDeserializer::ReadJSRegExp(), v8::internal::ValueDeserializer::ReadJSSet(), v8::internal::ValueDeserializer::ReadObjectUsingEntireBufferForLegacyFormat(), v8::internal::ValueDeserializer::ReadString(), v8::internal::compiler::JSContextSpecialization::ReduceParameter(), v8::internal::BigInt::Remainder(), v8::internal::requires(), v8::internal::JSPromise::Resolve(), v8::internal::JSDurationFormat::ResolvedOptions(), v8::internal::JSNumberFormat::ResolvedOptions(), v8::internal::Isolate::RunHostImportModuleDynamicallyCallback(), v8::internal::RUNTIME_FUNCTION(), v8::internal::ErrorUtils::ShadowRealmConstructTypeErrorCopy(), v8::internal::StringReplaceOneCharWithString(), v8::internal::BigInt::Subtract(), v8::internal::JSObject::TryMigrateInstance(), v8::internal::ScopeIterator::TryParseAndRetrieveScopes(), v8::internal::IC::UpdateMegaDOMIC(), v8::internal::anonymous_namespace{isolate.cc}::WalkPromiseTreeInternal(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyDescriptorOptionsImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyExceptionGetArgImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyExceptionImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyExceptionIsImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyGlobalImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyInstanceImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyModuleCustomSectionsImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyModuleExportsImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyModuleImportsImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableGrowImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableSetImpl(), v8::internal::ValueSerializer::WriteJSArray(), v8::internal::ValueSerializer::WriteJSError(), v8::internal::ValueSerializer::WriteJSObject(), v8::internal::ValueSerializer::WriteJSObjectPropertiesSlow(), and v8::internal::ValueSerializer::WriteJSObjectSlow().
ToHandle() [3/4]
template<typename T >
i::DirectHandle<T> v8::anonymous_namespace{api.cc}::ToHandle (i::MaybeDirectHandle< T > h)
Definition at line 7761 of file api.cc.
                                                   {
  return h.ToHandleChecked();
}
References h().
Referenced by AddPropertiesAndElementsToObject(), v8::ScriptCompiler::Compile(), v8::ScriptCompiler::CompileModule(), v8::Isolate::EnqueueMicrotask(), v8::Object::GetPropertyAttributes(), v8::Object::Has(), v8::Value::InstanceOf(), v8::Value::Int32Value(), v8::Value::IntegerValue(), v8::FunctionTemplate::NewRemoteInstance(), v8::Value::NumberValue(), v8::JSON::Stringify(), v8::Value::ToArrayIndex(), and v8::Value::Uint32Value().
ToHandle() [4/4]
template<typename T >
i::DirectHandle<T> v8::anonymous_namespace{api.cc}::ToHandle (i::MaybeHandle< T > h)
Definition at line 7752 of file api.cc.
                                             {
  return h.ToHandleChecked();
}
References h().
ToInternal()
std::shared_ptr<i::BackingStore> v8::anonymous_namespace{api.cc}::ToInternal (std::shared_ptr< i::BackingStoreBase > backing_store)
Definition at line 8919 of file api.cc.
                                                    {
  return std::static_pointer_cast<i::BackingStore>(backing_store);
}
ToObject()
i::Tagged<i::Object> v8::anonymous_namespace{api.cc}::ToObject (void * object)
Definition at line 2788 of file api.cc.
                                        {
  return i::Tagged<i::Object>(reinterpret_cast<i::Address>(object));
}
Referenced by v8::TryCatch::Exception(), v8::TryCatch::HasCaught(), v8::TryCatch::HasTerminated(), v8::TryCatch::Message(), v8::BooleanObject::New(), v8::NumberObject::New(), v8::BigIntObject::New(), v8::StringObject::New(), v8::SymbolObject::New(), v8::internal::compiler::JSCallReducer::ReduceObjectConstructor(), v8::internal::compiler::JSIntrinsicLowering::ReduceToObject(), v8::internal::TF_BUILTIN(), v8::Value::ToObject(), and v8::TryCatch::~TryCatch().
WriteUtf8Impl()
template<typename Char >
static int v8::anonymous_namespace{api.cc}::WriteUtf8Impl (base::Vector< const Char > string, char * write_start, int write_capacity, int options, int * utf16_chars_read_out) [static]
Definition at line 5727 of file api.cc.
                                                    {
  bool write_null = !(options & v8::String::NO_NULL_TERMINATION);
  bool replace_invalid_utf8 = (options & v8::String::REPLACE_INVALID_UTF8);
  char* current_write = write_start;
  const Char* read_start = string.begin();
  int read_index = 0;
  int read_length = string.length();
  int prev_char = unibrow::Utf16::kNoPreviousCharacter;
  // Do a fast loop where there is no exit capacity check.
  // Need enough space to write everything but one character.
  static_assert(unibrow::Utf16::kMaxExtraUtf8BytesForOneUtf16CodeUnit == 3);
  static const int kMaxSizePerChar = sizeof(Char) == 1 ? 2 : 3;
  while (read_index < read_length) {
    int up_to = read_length;
    if (write_capacity != -1) {
      int remaining_capacity =
          write_capacity - static_cast<int>(current_write - write_start);
      int writable_length =
          (remaining_capacity - kMaxSizePerChar) / kMaxSizePerChar;
      // Need to drop into slow loop.
      if (writable_length <= 0) break;
      up_to = std::min(up_to, read_index + writable_length);
    }
    // Write the characters to the stream.
    if (sizeof(Char) == 1) {
      // Simply memcpy if we only have ASCII characters.
      uint8_t char_mask = 0;
      for (int i = read_index; i < up_to; i++) char_mask |= read_start[i];
      if ((char_mask & 0x80) == 0) {
        int copy_length = up_to - read_index;
        memcpy(current_write, read_start + read_index, copy_length);
        current_write += copy_length;
        read_index = up_to;
      } else {
        for (; read_index < up_to; read_index++) {
          current_write += unibrow::Utf8::EncodeOneByte(
              current_write, static_cast<uint8_t>(read_start[read_index]));
          DCHECK(write_capacity == -1 ||
                 (current_write - write_start) <= write_capacity);
        }
      }
    } else {
      for (; read_index < up_to; read_index++) {
        uint16_t character = read_start[read_index];
        current_write += unibrow::Utf8::Encode(current_write, character,
                                               prev_char, replace_invalid_utf8);
        prev_char = character;
        DCHECK(write_capacity == -1 ||
               (current_write - write_start) <= write_capacity);
      }
    }
  }
  if (read_index < read_length) {
    DCHECK_NE(-1, write_capacity);
    // Aborted due to limited capacity. Check capacity on each iteration.
    int remaining_capacity =
        write_capacity - static_cast<int>(current_write - write_start);
    DCHECK_GE(remaining_capacity, 0);
    for (; read_index < read_length && remaining_capacity > 0; read_index++) {
      uint32_t character = read_start[read_index];
      int written = 0;
      // We can't use a local buffer here because Encode needs to modify
      // previous characters in the stream. We know, however, that
      // exactly one character will be advanced.
      if (unibrow::Utf16::IsSurrogatePair(prev_char, character)) {
        written = unibrow::Utf8::Encode(current_write, character, prev_char,
                                        replace_invalid_utf8);
        DCHECK_EQ(written, 1);
      } else {
        // Use a scratch buffer to check the required characters.
        char temp_buffer[unibrow::Utf8::kMaxEncodedSize];
        // Encoding a surrogate pair to Utf8 always takes 4 bytes.
        static const int kSurrogatePairEncodedSize =
            static_cast<int>(unibrow::Utf8::kMaxEncodedSize);
        // For REPLACE_INVALID_UTF8, catch the case where we cut off in the
        // middle of a surrogate pair. Abort before encoding the pair instead.
        if (replace_invalid_utf8 &&
            remaining_capacity < kSurrogatePairEncodedSize &&
            unibrow::Utf16::IsLeadSurrogate(character) &&
            read_index + 1 < read_length &&
            unibrow::Utf16::IsTrailSurrogate(read_start[read_index + 1])) {
          write_null = false;
          break;
        }
        // Can't encode using prev_char as gcc has array bounds issues.
        written = unibrow::Utf8::Encode(temp_buffer, character,
                                        unibrow::Utf16::kNoPreviousCharacter,
                                        replace_invalid_utf8);
        if (written > remaining_capacity) {
          // Won't fit. Abort and do not null-terminate the result.
          write_null = false;
          break;
        }
        // Copy over the character from temp_buffer.
        for (int i = 0; i < written; i++) current_write[i] = temp_buffer[i];
      }
      current_write += written;
      remaining_capacity -= written;
      prev_char = character;
    }
  }
  // Write out number of utf16 characters written to the stream.
  if (utf16_chars_read_out != nullptr) *utf16_chars_read_out = read_index;
  // Only null-terminate if there's space.
  if (write_null && (write_capacity == -1 ||
                     (current_write - write_start) < write_capacity)) {
    *current_write++ = '\0';
  }
  return static_cast<int>(current_write - write_start);
}
References v8::internal::character, DCHECK, DCHECK_EQ, DCHECK_GE, DCHECK_NE, unibrow::Utf8::Encode(), unibrow::Utf8::EncodeOneByte(), unibrow::Utf16::IsLeadSurrogate(), unibrow::Utf16::IsSurrogatePair(), unibrow::Utf16::IsTrailSurrogate(), unibrow::Utf8::kMaxEncodedSize, unibrow::Utf16::kMaxExtraUtf8BytesForOneUtf16CodeUnit, unibrow::Utf16::kNoPreviousCharacter, v8::String::NO_NULL_TERMINATION, and v8::String::REPLACE_INVALID_UTF8.