v8::internal::compiler::anonymous_namespace{code-generator-s390.cc} Namespace Reference
Classes
class OutOfLineRecordWrite
Functions
Condition FlagsConditionToCondition (FlagsCondition condition, ArchOpcode op)
static int nullInstr ()
template<int numOfOperand, class RType , class MType , class IType >
static int AssembleOp (Instruction *instr, RType r, MType m, IType i)
template<class _RR , class _RM , class _RI >
static int AssembleBinOp (Instruction *instr, _RR _rr, _RM _rm, _RI _ri)
template<class _R , class _M , class _I >
static int AssembleUnaryOp (Instruction *instr, _R _r, _M _m, _I _i)
void FlushPendingPushRegisters (MacroAssembler *masm, FrameAccessState *frame_access_state, ZoneVector< Register > *pending_pushes)
void AdjustStackPointerForTailCall (MacroAssembler *masm, FrameAccessState *state, int new_slot_above_sp, ZoneVector< Register > *pending_pushes=nullptr, bool allow_shrinkage=true)
Function Documentation
AdjustStackPointerForTailCall()
void v8::internal::compiler::anonymous_namespace{code-generator-s390.cc}::AdjustStackPointerForTailCall (MacroAssembler * masm, FrameAccessState * state, int new_slot_above_sp, ZoneVector< Register > * pending_pushes = nullptr, bool allow_shrinkage = true)
Definition at line 1022 of file code-generator-s390.cc.
                                 {
  int current_sp_offset = state->GetSPToFPSlotCount() +
                          StandardFrameConstants::kFixedSlotCountAboveFp;
  int stack_slot_delta = new_slot_above_sp - current_sp_offset;
  if (stack_slot_delta > 0) {
    if (pending_pushes != nullptr) {
      FlushPendingPushRegisters(masm, state, pending_pushes);
    }
    masm->AddS64(sp, sp, Operand(-stack_slot_delta * kSystemPointerSize));
    state->IncreaseSPDelta(stack_slot_delta);
  } else if (allow_shrinkage && stack_slot_delta < 0) {
    if (pending_pushes != nullptr) {
      FlushPendingPushRegisters(masm, state, pending_pushes);
    }
    masm->AddS64(sp, sp, Operand(-stack_slot_delta * kSystemPointerSize));
    state->IncreaseSPDelta(stack_slot_delta);
  }
}
References v8::internal::MacroAssembler::AddS64(), FlushPendingPushRegisters(), v8::internal::compiler::FrameAccessState::GetSPToFPSlotCount(), v8::internal::compiler::FrameAccessState::IncreaseSPDelta(), v8::internal::CommonFrameConstants::kFixedSlotCountAboveFp, and v8::internal::kSystemPointerSize.
AssembleBinOp()
template<class _RR , class _RM , class _RI >
static int v8::internal::compiler::anonymous_namespace{code-generator-s390.cc}::AssembleBinOp (Instruction * instr, _RR _rr, _RM _rm, _RI _ri) [inline], [static]
Definition at line 454 of file code-generator-s390.cc.
                                                                               {
  return AssembleOp<2>(instr, _rr, _rm, _ri);
}
AssembleOp()
template<int numOfOperand, class RType , class MType , class IType >
static int v8::internal::compiler::anonymous_namespace{code-generator-s390.cc}::AssembleOp (Instruction * instr, RType r, MType m, IType i) [inline], [static]
Definition at line 440 of file code-generator-s390.cc.
                                                                            {
  AddressingMode mode = AddressingModeField::decode(instr->opcode());
  if (mode != kMode_None || HasStackSlotInput(instr, numOfOperand - 1)) {
    return m();
  } else if (HasRegisterInput(instr, numOfOperand - 1)) {
    return r();
  } else if (HasImmediateInput(instr, numOfOperand - 1)) {
    return i();
  } else {
    UNREACHABLE();
  }
}
References v8::base::BitField< T, shift, size, U >::decode(), v8::internal::compiler::HasImmediateInput(), v8::internal::compiler::HasRegisterInput(), v8::internal::compiler::HasStackSlotInput(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, mode(), v8::internal::compiler::Instruction::opcode(), and v8::internal::UNREACHABLE().
AssembleUnaryOp()
template<class _R , class _M , class _I >
static int v8::internal::compiler::anonymous_namespace{code-generator-s390.cc}::AssembleUnaryOp (Instruction * instr, _R _r, _M _m, _I _i) [inline], [static]
Definition at line 459 of file code-generator-s390.cc.
                                                                           {
  return AssembleOp<1>(instr, _r, _m, _i);
}
FlagsConditionToCondition()
Condition v8::internal::compiler::anonymous_namespace{code-generator-s390.cc}::FlagsConditionToCondition (FlagsCondition condition, ArchOpcode op)
Definition at line 239 of file code-generator-s390.cc.
                                                                             {
  switch (condition) {
    case kEqual:
      return eq;
    case kNotEqual:
      return ne;
    case kUnsignedLessThan:
      // unsigned number never less than 0
      if (op == kS390_LoadAndTestWord32 || op == kS390_LoadAndTestWord64)
        return CC_NOP;
      [[fallthrough]];
    case kSignedLessThan:
      return lt;
    case kUnsignedGreaterThanOrEqual:
      // unsigned number always greater than or equal 0
      if (op == kS390_LoadAndTestWord32 || op == kS390_LoadAndTestWord64)
        return CC_ALWAYS;
      [[fallthrough]];
    case kSignedGreaterThanOrEqual:
      return ge;
    case kUnsignedLessThanOrEqual:
      // unsigned number never less than 0
      if (op == kS390_LoadAndTestWord32 || op == kS390_LoadAndTestWord64)
        return CC_EQ;
      [[fallthrough]];
    case kSignedLessThanOrEqual:
      return le;
    case kUnsignedGreaterThan:
      // unsigned number always greater than or equal 0
      if (op == kS390_LoadAndTestWord32 || op == kS390_LoadAndTestWord64)
        return ne;
      [[fallthrough]];
    case kSignedGreaterThan:
      return gt;
    case kOverflow:
      // Overflow checked for AddS64/SubS64 only.
      switch (op) {
        case kS390_Add32:
        case kS390_Add64:
        case kS390_Sub32:
        case kS390_Sub64:
        case kS390_Abs64:
        case kS390_Abs32:
        case kS390_Mul32:
        case kS390_Mul64WithOverflow:
          return overflow;
        default:
          break;
      }
      break;
    case kNotOverflow:
      switch (op) {
        case kS390_Add32:
        case kS390_Add64:
        case kS390_Sub32:
        case kS390_Sub64:
        case kS390_Abs64:
        case kS390_Abs32:
        case kS390_Mul32:
        case kS390_Mul64WithOverflow:
          return nooverflow;
        default:
          break;
      }
      break;
    default:
      break;
  }
  UNREACHABLE();
}
References v8::internal::CC_ALWAYS, v8::internal::CC_EQ, v8::internal::CC_NOP, v8::internal::eq, v8::internal::ge, v8::internal::gt, v8::internal::compiler::kEqual, v8::internal::compiler::kNotEqual, v8::internal::compiler::kNotOverflow, v8::internal::compiler::kOverflow, v8::internal::compiler::kSignedGreaterThan, v8::internal::compiler::kSignedGreaterThanOrEqual, v8::internal::compiler::kSignedLessThan, v8::internal::compiler::kSignedLessThanOrEqual, v8::internal::compiler::kUnsignedGreaterThan, v8::internal::compiler::kUnsignedGreaterThanOrEqual, v8::internal::compiler::kUnsignedLessThan, v8::internal::compiler::kUnsignedLessThanOrEqual, v8::internal::le, v8::internal::lt, v8::internal::ne, v8::internal::nooverflow, v8::internal::overflow, and v8::internal::UNREACHABLE().
FlushPendingPushRegisters()
void v8::internal::compiler::anonymous_namespace{code-generator-s390.cc}::FlushPendingPushRegisters (MacroAssembler * masm, FrameAccessState * frame_access_state, ZoneVector< Register > * pending_pushes)
Definition at line 999 of file code-generator-s390.cc.
                                                                     {
  switch (pending_pushes->size()) {
    case 0:
      break;
    case 1:
      masm->Push((*pending_pushes)[0]);
      break;
    case 2:
      masm->Push((*pending_pushes)[0], (*pending_pushes)[1]);
      break;
    case 3:
      masm->Push((*pending_pushes)[0], (*pending_pushes)[1],
                 (*pending_pushes)[2]);
      break;
    default:
      UNREACHABLE();
  }
  frame_access_state->IncreaseSPDelta(pending_pushes->size());
  pending_pushes->clear();
}
References v8::internal::ZoneVector< T >::clear(), v8::internal::compiler::FrameAccessState::IncreaseSPDelta(), v8::internal::MacroAssembler::Push(), v8::internal::ZoneVector< T >::size(), and v8::internal::UNREACHABLE().
Referenced by AdjustStackPointerForTailCall().
nullInstr()
static int v8::internal::compiler::anonymous_namespace{code-generator-s390.cc}::nullInstr () [static]
Definition at line 437 of file code-generator-s390.cc.
{ UNREACHABLE(); }
References v8::internal::UNREACHABLE().