v8::internal::anonymous_namespace{builtins-atomics-synchronization.cc} Namespace Reference
Functions
std::optional< base::TimeDelta > GetTimeoutDelta (DirectHandle< Object > timeout_obj)
DirectHandle< JSPromise > UnlockAsyncLockedMutexFromPromiseHandler (Isolate *isolate)
Function Documentation
GetTimeoutDelta()
std::optional<base::TimeDelta> v8::internal::anonymous_namespace{builtins-atomics-synchronization.cc}::GetTimeoutDelta (DirectHandle< Object > timeout_obj)
Definition at line 13 of file builtins-atomics-synchronization.cc.
                                      {
  double ms = Object::NumberValue(*timeout_obj);
  if (!std::isnan(ms)) {
    if (ms < 0) ms = 0;
    if (ms <= static_cast<double>(std::numeric_limits<int64_t>::max())) {
      return base::TimeDelta::FromMilliseconds(static_cast<int64_t>(ms));
    }
  }
  return std::nullopt;
}
References v8::base::TimeDelta::FromMilliseconds(), and v8::internal::Object::NumberValue().
Referenced by v8::internal::BUILTIN().
UnlockAsyncLockedMutexFromPromiseHandler()
DirectHandle<JSPromise> v8::internal::anonymous_namespace{builtins-atomics-synchronization.cc}::UnlockAsyncLockedMutexFromPromiseHandler (Isolate * isolate)
Definition at line 25 of file builtins-atomics-synchronization.cc.
                      {
  DirectHandle<Context> context(isolate->context(), isolate);
  DirectHandle<Object> mutex(
      context->GetNoCell(JSAtomicsMutex::kMutexAsyncContextSlot), isolate);
  DirectHandle<Object> unlock_promise(
      context->GetNoCell(JSAtomicsMutex::kUnlockedPromiseAsyncContextSlot),
      isolate);
  DirectHandle<Object> waiter_wrapper_obj(
      context->GetNoCell(JSAtomicsMutex::kAsyncLockedWaiterAsyncContextSlot),
      isolate);
  auto js_mutex = Cast<JSAtomicsMutex>(mutex);
  auto js_unlock_promise = Cast<JSPromise>(unlock_promise);
  auto async_locked_waiter_wrapper = Cast<Foreign>(waiter_wrapper_obj);
  js_mutex->UnlockAsyncLockedMutex(isolate, async_locked_waiter_wrapper);
  return js_unlock_promise;
}
References v8::internal::Isolate::context(), v8::internal::JSAtomicsMutex::kAsyncLockedWaiterAsyncContextSlot, v8::internal::JSAtomicsMutex::kMutexAsyncContextSlot, and v8::internal::JSAtomicsMutex::kUnlockedPromiseAsyncContextSlot.
Referenced by v8::internal::BUILTIN().