v8::internal::anonymous_namespace{compilation-cache-table.cc} Namespace Reference
Classes
class EvalCacheKey
class RegExpKey
class CodeKey
Functions
Tagged< JSFunction > SearchLiteralsMap (Tagged< CompilationCacheTable > cache, InternalIndex cache_entry, Tagged< Context > native_context)
void AddToJSFunctionMap (DirectHandle< CompilationCacheTable > cache, InternalIndex cache_entry, DirectHandle< JSFunction > js_function)
Tagged< Smi > ScriptHash (Tagged< String > source, MaybeDirectHandle< Object > maybe_name, int line_offset, int column_offset, v8::ScriptOriginOptions origin_options, Isolate *isolate)
Function Documentation
AddToJSFunctionMap()
void v8::internal::anonymous_namespace{compilation-cache-table.cc}::AddToJSFunctionMap (DirectHandle< CompilationCacheTable > cache, InternalIndex cache_entry, DirectHandle< JSFunction > js_function)
Definition at line 41 of file compilation-cache-table.cc.
                                                              {
  Isolate* isolate = Isolate::Current();
  DirectHandle<WeakFixedArray> new_js_functions;
  int entry = -1;
  Tagged<Object> obj = cache->EvalJSFunctionsValueAt(cache_entry);
  // Check that there's no confusion between FixedArray and WeakFixedArray (the
  // object used to be a FixedArray here).
  DCHECK(!IsFixedArray(obj));
  if (!IsWeakFixedArray(obj) || Cast<WeakFixedArray>(obj)->length() == 0) {
    new_js_functions =
        isolate->factory()->NewWeakFixedArray(1, AllocationType::kOld);
    entry = 0;
  } else {
    DirectHandle<WeakFixedArray> old_js_functions(Cast<WeakFixedArray>(obj),
                                                  isolate);
    // Can we reuse an entry?
    DCHECK_LT(entry, 0);
    int length = old_js_functions->length();
    for (int i = 0; i < length; i++) {
      if (old_js_functions->get(i).IsCleared()) {
        new_js_functions = old_js_functions;
        entry = i;
        break;
      }
    }
    if (entry < 0) {
      // Copy old optimized code map and append one new entry.
      new_js_functions =
          isolate->factory()->CopyWeakFixedArrayAndGrow(old_js_functions, 1);
      entry = old_js_functions->length();
    }
  }
  new_js_functions->set(entry, MakeWeak(*js_function));
#ifdef DEBUG
  for (int i = 0; i < new_js_functions->length(); i++) {
    Tagged<MaybeObject> object = new_js_functions->get(i);
    DCHECK_IMPLIES(!object.IsCleared(),
                   IsJSFunction(object.GetHeapObjectAssumeWeak()));
  }
#endif
  Tagged<Object> old_js_functions = cache->EvalJSFunctionsValueAt(cache_entry);
  if (old_js_functions != *new_js_functions) {
    cache->SetEvalJSFunctionsValueAt(cache_entry, *new_js_functions);
  }
}
References v8::internal::Factory::CopyWeakFixedArrayAndGrow(), v8::internal::Isolate::Current(), v8::internal::DCHECK(), DCHECK_IMPLIES, DCHECK_LT, v8::internal::Isolate::factory(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::kOld, v8::internal::length, v8::internal::MakeWeak(), and v8::internal::FactoryBase< Impl >::NewWeakFixedArray().
Referenced by v8::internal::CompilationCacheTable::PutEval(), and v8::internal::CompilationCacheTable::UpdateEval().
ScriptHash()
Tagged<Smi> v8::internal::anonymous_namespace{compilation-cache-table.cc}::ScriptHash (Tagged< String > source, MaybeDirectHandle< Object > maybe_name, int line_offset, int column_offset, v8::ScriptOriginOptions origin_options, Isolate * isolate)
Definition at line 188 of file compilation-cache-table.cc.
                                         {
  DisallowGarbageCollection no_gc;
  size_t hash = base::hash_combine(source->EnsureHash());
  if (DirectHandle<Object> name;
      maybe_name.ToHandle(&name) && IsString(*name, isolate)) {
    hash =
        base::hash_combine(hash, Cast<String>(*name)->EnsureHash(), line_offset,
                           column_offset, origin_options.Flags());
  }
  // The upper bits of the hash are discarded so that the value fits in a Smi.
  return Smi::From31BitPattern(static_cast<int>(hash & (~(1u << 31))));
}
References v8::ScriptOriginOptions::Flags(), v8::internal::Smi::From31BitPattern(), v8::base::hash_combine(), v8::internal::name, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::MaybeDirectHandle< T >::ToHandle().
SearchLiteralsMap()
Tagged<JSFunction> v8::internal::anonymous_namespace{compilation-cache-table.cc}::SearchLiteralsMap (Tagged< CompilationCacheTable > cache, InternalIndex cache_entry, Tagged< Context > native_context)
Definition at line 16 of file compilation-cache-table.cc.
                                                                     {
  DisallowGarbageCollection no_gc;
  DCHECK(IsNativeContext(native_context));
  Tagged<Object> obj = cache->EvalJSFunctionsValueAt(cache_entry);
  // Check that there's no confusion between FixedArray and WeakFixedArray (the
  // object used to be a FixedArray here).
  DCHECK(!IsFixedArray(obj));
  if (IsWeakFixedArray(obj)) {
    Tagged<WeakFixedArray> literals_map = Cast<WeakFixedArray>(obj);
    int length = literals_map->length();
    for (int i = 0; i < length; i++) {
      DCHECK(literals_map->get(i).IsWeakOrCleared());
      Tagged<JSFunction> js_function;
      if (literals_map->get(i).GetHeapObjectIfWeak(&js_function) &&
          js_function->GetCreationContext().value() == native_context) {
        return js_function;
      }
    }
  }
  return {};
}
References v8::internal::DCHECK(), v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectIfWeak(), v8::internal::TaggedImpl< kRefType, StorageType >::IsWeakOrCleared(), v8::internal::length, v8::internal::native_context, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::internal::CompilationCacheTable::LookupEval().