v8::internal::compiler::anonymous_namespace{simplified-operator-reducer.cc} Namespace Reference
Functions
Decision DecideObjectIsSmi (Node *const input)
Function Documentation
DecideObjectIsSmi()
Decision v8::internal::compiler::anonymous_namespace{simplified-operator-reducer.cc}::DecideObjectIsSmi (Node *const input)
Definition at line 25 of file simplified-operator-reducer.cc.
                                              {
  NumberMatcher m(input);
  if (m.HasResolvedValue()) {
    return IsSmiDouble(m.ResolvedValue()) ? Decision::kTrue : Decision::kFalse;
  }
  if (m.IsAllocate()) return Decision::kFalse;
  if (m.IsChangeBitToTagged()) return Decision::kFalse;
  if (m.IsChangeInt31ToTaggedSigned()) return Decision::kTrue;
  if (m.IsHeapConstant()) return Decision::kFalse;
  return Decision::kUnknown;
}
References v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), v8::internal::IsSmiDouble(), v8::internal::compiler::kFalse, v8::internal::compiler::kTrue, v8::internal::compiler::kUnknown, and v8::internal::compiler::ValueMatcher< T, kOpcode >::ResolvedValue().
Referenced by v8::internal::compiler::SimplifiedOperatorReducer::Reduce().