v8::internal::maglev::anonymous_namespace{maglev-phi-representation-selector.cc} Namespace Reference
Functions
Opcode GetOpcodeForConversion (ValueRepresentation from, ValueRepresentation to, bool truncating)
Function Documentation
GetOpcodeForConversion()
Opcode v8::internal::maglev::anonymous_namespace{maglev-phi-representation-selector.cc}::GetOpcodeForConversion (ValueRepresentation from, ValueRepresentation to, bool truncating)
Definition at line 359 of file maglev-phi-representation-selector.cc.
                                               {
  DCHECK_NE(from, ValueRepresentation::kTagged);
  DCHECK_NE(to, ValueRepresentation::kTagged);
  switch (from) {
    case ValueRepresentation::kInt32:
      switch (to) {
        case ValueRepresentation::kUint32:
          return Opcode::kCheckedInt32ToUint32;
        case ValueRepresentation::kFloat64:
        case ValueRepresentation::kHoleyFloat64:
          return Opcode::kChangeInt32ToFloat64;
        case ValueRepresentation::kInt32:
        case ValueRepresentation::kTagged:
        case ValueRepresentation::kIntPtr:
          UNREACHABLE();
      }
    case ValueRepresentation::kUint32:
      switch (to) {
        case ValueRepresentation::kInt32:
          return Opcode::kCheckedUint32ToInt32;
        case ValueRepresentation::kFloat64:
        case ValueRepresentation::kHoleyFloat64:
          return Opcode::kChangeUint32ToFloat64;
        case ValueRepresentation::kUint32:
        case ValueRepresentation::kTagged:
        case ValueRepresentation::kIntPtr:
          UNREACHABLE();
      }
    case ValueRepresentation::kFloat64:
      switch (to) {
        case ValueRepresentation::kInt32:
          if (truncating) {
            return Opcode::kTruncateFloat64ToInt32;
          }
          return Opcode::kCheckedTruncateFloat64ToInt32;
        case ValueRepresentation::kUint32:
          // The graph builder never inserts Tagged->Uint32 conversions, so we
          // don't have to handle this case.
          UNREACHABLE();
        case ValueRepresentation::kHoleyFloat64:
#ifdef V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
          // When converting to kHoleyFloat64 representation, we need to turn
          // those NaN patterns that have a special interpretation in
          // HoleyFloat64 (e.g. undefined and hole) into the canonical NaN so
          // that they keep representing NaNs in the new representation.
          return Opcode::kFloat64ToHoleyFloat64;
#else
          return Opcode::kIdentity;
#endif // V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
        case ValueRepresentation::kFloat64:
        case ValueRepresentation::kTagged:
        case ValueRepresentation::kIntPtr:
          UNREACHABLE();
      }
    case ValueRepresentation::kHoleyFloat64:
      switch (to) {
        case ValueRepresentation::kInt32:
          // Holes are NaNs, so we can truncate them to int32 same as real NaNs.
          if (truncating) {
            return Opcode::kTruncateFloat64ToInt32;
          }
          return Opcode::kCheckedTruncateFloat64ToInt32;
        case ValueRepresentation::kUint32:
          // The graph builder never inserts Tagged->Uint32 conversions, so we
          // don't have to handle this case.
          UNREACHABLE();
        case ValueRepresentation::kFloat64:
          return Opcode::kHoleyFloat64ToMaybeNanFloat64;
        case ValueRepresentation::kHoleyFloat64:
        case ValueRepresentation::kTagged:
        case ValueRepresentation::kIntPtr:
          UNREACHABLE();
      }
    case ValueRepresentation::kTagged:
    case ValueRepresentation::kIntPtr:
      UNREACHABLE();
  }
  UNREACHABLE();
}
References DCHECK_NE, v8::internal::maglev::kFloat64, v8::internal::maglev::kHoleyFloat64, v8::internal::maglev::kInt32, v8::internal::maglev::kIntPtr, v8::internal::maglev::kTagged, v8::internal::maglev::kUint32, and v8::internal::UNREACHABLE().
Referenced by v8::internal::maglev::MaglevPhiRepresentationSelector::ConvertTaggedPhiTo(), and v8::internal::maglev::MaglevPhiRepresentationSelector::UpdateUntaggingOfPhi().