v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::anonymous_namespace{implementation-visitor.cc} Namespace Reference
Functions
std::string GenerateRuntimeTypeCheck (const Type *type, const std::string &value)
void GenerateBoundsDCheck (std::ostream &os, const std::string &index, const ClassType *type, const Field &f)
bool CanGenerateFieldAccessors (const Type *field_type)
Function Documentation
CanGenerateFieldAccessors()
bool v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::anonymous_namespace{implementation-visitor.cc}::CanGenerateFieldAccessors (const Type * field_type)
Definition at line 4504 of file implementation-visitor.cc.
                                                       {
  // float64_or_undefined_or_hole should be treated like float64. For now, we
  // don't need it.
  // TODO(v8:10391) Generate accessors for external pointers.
  return field_type != TypeOracle::GetVoidType() &&
         field_type != TypeOracle::GetFloat64OrUndefinedOrHoleType() &&
         !field_type->IsSubtypeOf(TypeOracle::GetExternalPointerType()) &&
         !field_type->IsSubtypeOf(TypeOracle::GetTrustedPointerType()) &&
         !field_type->IsSubtypeOf(TypeOracle::GetProtectedPointerType());
}
References v8::internal::torque::Type::IsSubtypeOf().
Referenced by v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::GenerateFieldAccessors(), and v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::GeneratePrintDefinitionsForClass().
GenerateBoundsDCheck()
void v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::anonymous_namespace{implementation-visitor.cc}::GenerateBoundsDCheck (std::ostream & os, const std::string & index, const ClassType * type, const Field & f)
Definition at line 4487 of file implementation-visitor.cc.
                                                                 {
  os << " DCHECK_GE(" << index << ", 0);\n";
  std::string length_expression;
  if (std::optional<NameAndType> array_length =
          ExtractSimpleFieldArraySize(*type, f.index->expr)) {
    length_expression = "this ->" + array_length->name + "()";
  } else {
    // The length is element 2 in the flattened field slice.
    length_expression =
        "static_cast<int>(std::get<2>(" +
        Callable::PrefixNameForCCOutput(type->GetSliceMacroName(f)) +
        "(*static_cast<const D*>(this))))";
  }
  os << " DCHECK_LT(" << index << ", " << length_expression << ");\n";
}
References v8::internal::torque::ExtractSimpleFieldArraySize(), v8::internal::index, v8::internal::torque::Field::index, v8::internal::string, and v8::internal::tracing::type.
Referenced by v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::EmitLoadFieldStatement(), and v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::EmitStoreFieldStatement().
GenerateRuntimeTypeCheck()
std::string v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::anonymous_namespace{implementation-visitor.cc}::GenerateRuntimeTypeCheck (const Type * type, const std::string & value)
Definition at line 4455 of file implementation-visitor.cc.
                                                             {
  bool maybe_object = !type->IsSubtypeOf(TypeOracle::GetStrongTaggedType());
  std::stringstream type_check;
  bool at_start = true;
  // If weak pointers are allowed, then start by checking for a cleared value.
  if (maybe_object) {
    type_check << value << ".IsCleared()";
    at_start = false;
  }
  for (const TypeChecker& runtime_type : type->GetTypeCheckers()) {
    if (!at_start) type_check << " || ";
    at_start = false;
    if (maybe_object) {
      bool strong = runtime_type.weak_ref_to.empty();
      if (strong && runtime_type.type == WEAK_HEAP_OBJECT) {
        // Rather than a generic Weak<T>, this is the basic type WeakHeapObject.
        // We can't validate anything more about the type of the object pointed
        // to, so just check that it's weak.
        type_check << value << ".IsWeak()";
      } else {
        type_check << "(" << (strong ? "!" : "") << value << ".IsWeak() && Is"
                   << (strong ? runtime_type.type : runtime_type.weak_ref_to)
                   << "(" << value << ".GetHeapObjectOrSmi()))";
      }
    } else {
      type_check << "Is" << runtime_type.type << "(" << value << ")";
    }
  }
  return type_check.str();
}
References v8::internal::tracing::type, v8::internal::value, and v8::internal::torque::WEAK_HEAP_OBJECT.
Referenced by v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::EmitLoadFieldStatement(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::EmitStoreFieldStatement(), and v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::GenerateFieldValueVerifier().