v8::internal::heap Namespace Reference
Classes
class List
class ListNode
Functions
void ZapCodeBlock (Address start, int size_in_bytes)
void ZapBlock (Address start, size_t size, uintptr_t zap_value)
bool ShouldZapGarbage ()
uintptr_t ZapValue ()
Function Documentation
ShouldZapGarbage()
bool v8::internal::heap::ShouldZapGarbage () [inline]
Definition at line 18 of file zapping.h.
                               {
#ifdef DEBUG
  return true;
#else
#ifdef VERIFY_HEAP
  return v8_flags.verify_heap;
#else
  return false;
#endif
#endif
}
References v8::internal::v8_flags.
Referenced by v8::internal::HeapAllocator::AllocateRaw(), v8::internal::MemoryAllocator::AllocateUninitializedChunkAt(), v8::internal::MemoryAllocator::AllocateUninitializedPageFromPool(), v8::internal::SemiSpaceNewSpace::GarbageCollectionEpilogue(), v8::Isolate::GetHeapStatistics(), v8::internal::Sweeper::LocalSweeper::ParallelSweepPage(), v8::internal::MarkCompactCollector::RightTrimDescriptorArray(), v8::internal::anonymous_namespace{sweeper.cc}::ShouldZapDeadObjectsOnPage(), v8::internal::Sweeper::SweepEmptyNewSpacePage(), v8::internal::MemoryAllocator::TryAllocateUninitializedLargePageFromPool(), ZapBlock(), and ZapCodeBlock().
ZapBlock()
void v8::internal::heap::ZapBlock (Address start, size_t size, uintptr_t zap_value)
Definition at line 26 of file zapping.cc.
                                                               {
  DCHECK(ShouldZapGarbage());
  DCHECK(IsAligned(start, kTaggedSize));
  DCHECK(IsAligned(size, kTaggedSize));
  MemsetTagged(ObjectSlot(start),
               Tagged<Object>(static_cast<Address>(zap_value)),
               size >> kTaggedSizeLog2);
}
References v8::internal::DCHECK(), IsAligned(), v8::internal::kTaggedSize, v8::internal::kTaggedSizeLog2, v8::internal::MemsetTagged(), ShouldZapGarbage(), and size().
Referenced by v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::AddToFreeListFreeSpaceHandler(), v8::internal::MemoryAllocator::AllocateUninitializedChunkAt(), v8::internal::MemoryAllocator::AllocateUninitializedPageFromPool(), v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::CreateFillerFreeSpaceHandler(), v8::internal::MemoryAllocator::TryAllocateUninitializedLargePageFromPool(), and v8::internal::SemiSpaceNewSpace::ZapUnusedMemory().
ZapCodeBlock()
V8_EXPORT_PRIVATE void v8::internal::heap::ZapCodeBlock (Address start, int size_in_bytes)
Definition at line 14 of file zapping.cc.
                                                    {
#ifdef DEBUG
  DCHECK(ShouldZapGarbage());
  CodePageMemoryModificationScopeForDebugging code_modification_scope(
      MemoryChunkMetadata::FromAddress(start));
  DCHECK(IsAligned(start, kIntSize));
  for (int i = 0; i < size_in_bytes / kIntSize; i++) {
    base::Memory<int>(start + i * kIntSize) = kCodeZapValue;
  }
#endif
}
References v8::internal::DCHECK(), v8::internal::MemoryChunkMetadata::FromAddress(), IsAligned(), v8::internal::kCodeZapValue, v8::internal::kIntSize, and ShouldZapGarbage().
Referenced by v8::internal::HeapAllocator::AllocateRaw().
ZapValue()
uintptr_t v8::internal::heap::ZapValue () [inline]
Definition at line 30 of file zapping.h.
                            {
  return v8_flags.clear_free_memory ? kClearedFreeMemoryValue : kZapValue;
}
References v8::internal::kClearedFreeMemoryValue, v8::internal::kZapValue, and v8::internal::v8_flags.
Referenced by v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::AddToFreeListFreeSpaceHandler(), v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::CreateFillerFreeSpaceHandler(), and v8::internal::SemiSpaceNewSpace::ZapUnusedMemory().