v8::base::anonymous_namespace{platform-win32.cc} Namespace Reference
Functions
bool UserShadowStackEnabled ()
DWORD GetProtectionFromMemoryPermission (OS::MemoryPermission access)
DWORD GetFileViewAccessFromMemoryPermission (OS::MemoryPermission access)
void * VirtualAllocWrapper (void *address, size_t size, DWORD flags, DWORD protect)
uint8_t * VirtualAllocWithHint (size_t size, DWORD flags, DWORD protect, void *hint)
void * AllocateInternal (void *hint, size_t size, size_t alignment, size_t page_size, DWORD flags, DWORD protect)
void CheckIsOOMError (int error)
Function Documentation
AllocateInternal()
void* v8::base::anonymous_namespace{platform-win32.cc}::AllocateInternal (void * hint, size_t size, size_t alignment, size_t page_size, DWORD flags, DWORD protect)
Definition at line 946 of file platform-win32.cc.
                                                                     {
  // First, try an exact size aligned allocation.
  uint8_t* base = VirtualAllocWithHint(size, flags, protect, hint);
  if (base == nullptr) return nullptr; // Can't allocate, we're OOM.
  // If address is suitably aligned, we're done.
  uint8_t* aligned_base = reinterpret_cast<uint8_t*>(
      RoundUp(reinterpret_cast<uintptr_t>(base), alignment));
  if (base == aligned_base) return reinterpret_cast<void*>(base);
  // Otherwise, free it and try a larger allocation.
  CHECK(VirtualFree(base, 0, MEM_RELEASE));
  // Clear the hint. It's unlikely we can allocate at this address.
  hint = nullptr;
  // Add the maximum misalignment so we are guaranteed an aligned base address
  // in the allocated region.
  size_t padded_size = size + (alignment - page_size);
  const int kMaxAttempts = 3;
  aligned_base = nullptr;
  for (int i = 0; i < kMaxAttempts; ++i) {
    base = VirtualAllocWithHint(padded_size, flags, protect, hint);
    if (base == nullptr) return nullptr; // Can't allocate, we're OOM.
    // Try to trim the allocation by freeing the padded allocation and then
    // calling VirtualAlloc at the aligned base.
    CHECK(VirtualFree(base, 0, MEM_RELEASE));
    aligned_base = reinterpret_cast<uint8_t*>(
        RoundUp(reinterpret_cast<uintptr_t>(base), alignment));
    base = reinterpret_cast<uint8_t*>(
        VirtualAllocWrapper(aligned_base, size, flags, protect));
    // We might not get the reduced allocation due to a race. In that case,
    // base will be nullptr.
    if (base != nullptr) break;
  }
  DCHECK_IMPLIES(base, base == aligned_base);
  return reinterpret_cast<void*>(base);
}
References CHECK, DCHECK_IMPLIES, flags(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, RoundUp(), size(), VirtualAllocWithHint(), and VirtualAllocWrapper().
CheckIsOOMError()
void v8::base::anonymous_namespace{platform-win32.cc}::CheckIsOOMError (int error)
Definition at line 987 of file platform-win32.cc.
                                {
  // We expect one of ERROR_NOT_ENOUGH_MEMORY or ERROR_COMMITMENT_LIMIT. We'd
  // still like to get the actual error code when it's not one of the expected
  // errors, so use the construct below to achieve that.
  if (error != ERROR_NOT_ENOUGH_MEMORY) CHECK_EQ(ERROR_COMMITMENT_LIMIT, error);
}
References CHECK_EQ.
GetFileViewAccessFromMemoryPermission()
DWORD v8::base::anonymous_namespace{platform-win32.cc}::GetFileViewAccessFromMemoryPermission (OS::MemoryPermission access)
Definition at line 909 of file platform-win32.cc.
                                                                       {
  switch (access) {
    case OS::MemoryPermission::kNoAccess:
    case OS::MemoryPermission::kNoAccessWillJitLater:
    case OS::MemoryPermission::kRead:
      return FILE_MAP_READ;
    case OS::MemoryPermission::kReadWrite:
      return FILE_MAP_READ | FILE_MAP_WRITE;
    default:
      // Execute access is not supported
      break;
  }
  UNREACHABLE();
}
References v8::base::OS::kNoAccess, v8::base::OS::kNoAccessWillJitLater, v8::base::OS::kRead, v8::base::OS::kReadWrite, and UNREACHABLE.
GetProtectionFromMemoryPermission()
DWORD v8::base::anonymous_namespace{platform-win32.cc}::GetProtectionFromMemoryPermission (OS::MemoryPermission access)
Definition at line 887 of file platform-win32.cc.
                                                                   {
  switch (access) {
    case OS::MemoryPermission::kNoAccess:
    case OS::MemoryPermission::kNoAccessWillJitLater:
      return PAGE_NOACCESS;
    case OS::MemoryPermission::kRead:
      return PAGE_READONLY;
    case OS::MemoryPermission::kReadWrite:
      return PAGE_READWRITE;
    case OS::MemoryPermission::kReadWriteExecute:
      if (IsWindows10OrGreater())
        return PAGE_EXECUTE_READWRITE | PAGE_TARGETS_INVALID;
      return PAGE_EXECUTE_READWRITE;
    case OS::MemoryPermission::kReadExecute:
      if (IsWindows10OrGreater())
        return PAGE_EXECUTE_READ | PAGE_TARGETS_INVALID;
      return PAGE_EXECUTE_READ;
  }
  UNREACHABLE();
}
References v8::base::OS::kNoAccess, v8::base::OS::kNoAccessWillJitLater, v8::base::OS::kRead, v8::base::OS::kReadExecute, v8::base::OS::kReadWrite, v8::base::OS::kReadWriteExecute, and UNREACHABLE.
UserShadowStackEnabled()
bool v8::base::anonymous_namespace{platform-win32.cc}::UserShadowStackEnabled ()
Definition at line 755 of file platform-win32.cc.
                              {
  auto is_user_cet_available_in_environment =
      reinterpret_cast<decltype(&IsUserCetAvailableInEnvironment)>(
          ::GetProcAddress(::GetModuleHandleW(L"kernel32.dll"),
                           "IsUserCetAvailableInEnvironment"));
  auto get_process_mitigation_policy =
      reinterpret_cast<decltype(&GetProcessMitigationPolicy)>(::GetProcAddress(
          ::GetModuleHandle(L"Kernel32.dll"), "GetProcessMitigationPolicy"));
  if (!is_user_cet_available_in_environment || !get_process_mitigation_policy) {
    return false;
  }
  if (!is_user_cet_available_in_environment(
          USER_CET_ENVIRONMENT_WIN32_PROCESS)) {
    return false;
  }
  PROCESS_MITIGATION_USER_SHADOW_STACK_POLICY uss_policy;
  if (!get_process_mitigation_policy(GetCurrentProcess(),
                                     ProcessUserShadowStackPolicy, &uss_policy,
                                     sizeof(uss_policy))) {
    return false;
  }
  return uss_policy.EnableUserShadowStack;
}
References v8::internal::L.
VirtualAllocWithHint()
uint8_t* v8::base::anonymous_namespace{platform-win32.cc}::VirtualAllocWithHint (size_t size, DWORD flags, DWORD protect, void * hint)
Definition at line 934 of file platform-win32.cc.
                                          {
  LPVOID base = VirtualAllocWrapper(hint, size, flags, protect);
  // On failure, let the OS find an address to use.
  if (hint && base == nullptr) {
    base = VirtualAllocWrapper(nullptr, size, flags, protect);
  }
  return reinterpret_cast<uint8_t*>(base);
}
References flags(), size(), and VirtualAllocWrapper().
Referenced by AllocateInternal().
VirtualAllocWrapper()
void* v8::base::anonymous_namespace{platform-win32.cc}::VirtualAllocWrapper (void * address, size_t size, DWORD flags, DWORD protect)
Definition at line 924 of file platform-win32.cc.
                                         {
  if (VirtualAlloc2) {
    return VirtualAlloc2(GetCurrentProcess(), address, size, flags, protect,
                         NULL, 0);
  } else {
    return VirtualAlloc(address, size, flags, protect);
  }
}
References flags(), size(), and v8::base::VirtualAlloc2.
Referenced by AllocateInternal(), and VirtualAllocWithHint().