v8::internal::anonymous_namespace{cpp-heap.cc} Namespace Reference
Classes
class CppgcPlatformAdapter
class UnifiedHeapConcurrentMarker
class UnifiedHeapConservativeMarkingVisitor
class SweepingOnMutatorThreadForGlobalHandlesScope
class SweepingOnMutatorThreadForGlobalHandlesObserver
class MoveListenerImpl
class CollectCustomSpaceStatisticsAtLastGCTask
Functions
void FatalOutOfMemoryHandlerImpl (const std::string &reason, const SourceLocation &, HeapBase *heap)
void GlobalFatalOutOfMemoryHandlerImpl (const std::string &reason, const SourceLocation &, HeapBase *heap)
bool IsMemoryReducingGC (CppHeap::GarbageCollectionFlags flags)
bool IsForceGC (CppHeap::GarbageCollectionFlags flags)
bool ShouldReduceMemory (CppHeap::GarbageCollectionFlags flags)
MarkingWorklists::Local * GetV8MarkingWorklists (Isolate *isolate, cppgc::internal::CollectionType collection_type)
void RecordEmbedderMarkingSpeed (GCTracer *tracer, base::TimeDelta marking_time, size_t marked_bytes)
void ReportCustomSpaceStatistics (cppgc::internal::RawHeap &raw_heap, std::vector< cppgc::CustomSpaceIndex > custom_spaces, std::unique_ptr< CustomSpaceStatisticsReceiver > receiver)
Variables
constexpr size_t kIncrementalMarkingCheckInterval = 128 * KB
Function Documentation
FatalOutOfMemoryHandlerImpl()
void v8::internal::anonymous_namespace{cpp-heap.cc}::FatalOutOfMemoryHandlerImpl (const std::string & reason, const SourceLocation & , HeapBase * heap)
Definition at line 229 of file cpp-heap.cc.
                                                                        {
  auto* cpp_heap = static_cast<v8::internal::CppHeap*>(heap);
  auto* isolate = cpp_heap->isolate();
  DCHECK_NOT_NULL(isolate);
  if (v8_flags.heap_snapshot_on_oom) {
    cppgc::internal::ClassNameAsHeapObjectNameScope names_scope(
        cpp_heap->AsBase());
    isolate->heap()->heap_profiler()->WriteSnapshotToDiskAfterGC(
        v8::HeapProfiler::HeapSnapshotMode::kExposeInternals);
  }
  V8::FatalProcessOutOfMemory(isolate, reason.c_str());
}
References DCHECK_NOT_NULL, v8::internal::V8::FatalProcessOutOfMemory(), heap(), v8::internal::CppHeap::isolate(), v8::HeapProfiler::kExposeInternals, and v8::internal::v8_flags.
Referenced by v8::internal::CppHeap::AttachIsolate().
GetV8MarkingWorklists()
MarkingWorklists::Local* v8::internal::anonymous_namespace{cpp-heap.cc}::GetV8MarkingWorklists (Isolate * isolate, cppgc::internal::CollectionType collection_type)
Definition at line 822 of file cpp-heap.cc.
                                                                   {
  auto* heap = isolate->heap();
  if (collection_type == cppgc::internal::CollectionType::kMajor) {
    return heap->mark_compact_collector()->local_marking_worklists();
  } else {
    return heap->minor_mark_sweep_collector()->local_marking_worklists();
  }
}
References v8::internal::Isolate::heap(), and cppgc::internal::kMajor.
Referenced by v8::internal::CppHeap::EnterFinalPause(), and v8::internal::CppHeap::StartMarking().
GlobalFatalOutOfMemoryHandlerImpl()
void v8::internal::anonymous_namespace{cpp-heap.cc}::GlobalFatalOutOfMemoryHandlerImpl (const std::string & reason, const SourceLocation & , HeapBase * heap)
Definition at line 243 of file cpp-heap.cc.
                                                                              {
  V8::FatalProcessOutOfMemory(nullptr, reason.c_str());
}
References v8::internal::V8::FatalProcessOutOfMemory().
Referenced by v8::internal::CppHeap::InitializeOncePerProcess().
IsForceGC()
bool v8::internal::anonymous_namespace{cpp-heap.cc}::IsForceGC (CppHeap::GarbageCollectionFlags flags)
Definition at line 692 of file cpp-heap.cc.
                                                    {
  return flags & CppHeap::GarbageCollectionFlagValues::kForced;
}
References v8::internal::flags.
Referenced by v8::internal::CppHeap::InitializeMarking(), v8::internal::CppHeap::SelectMarkingType(), v8::internal::CppHeap::SelectSweepingType(), and ShouldReduceMemory().
IsMemoryReducingGC()
bool v8::internal::anonymous_namespace{cpp-heap.cc}::IsMemoryReducingGC (CppHeap::GarbageCollectionFlags flags)
Definition at line 688 of file cpp-heap.cc.
                                                             {
  return flags & CppHeap::GarbageCollectionFlagValues::kReduceMemory;
}
References v8::internal::flags.
Referenced by ShouldReduceMemory().
RecordEmbedderMarkingSpeed()
void v8::internal::anonymous_namespace{cpp-heap.cc}::RecordEmbedderMarkingSpeed (GCTracer * tracer, base::TimeDelta marking_time, size_t marked_bytes)
Definition at line 928 of file cpp-heap.cc.
                                                     {
  tracer->RecordEmbedderMarkingSpeed(marked_bytes, marking_time);
}
References v8::internal::GCTracer::RecordEmbedderMarkingSpeed().
Referenced by v8::internal::CppHeap::FinishMarkingAndProcessWeakness().
ReportCustomSpaceStatistics()
void v8::internal::anonymous_namespace{cpp-heap.cc}::ReportCustomSpaceStatistics (cppgc::internal::RawHeap & raw_heap, std::vector< cppgc::CustomSpaceIndex > custom_spaces, std::unique_ptr< CustomSpaceStatisticsReceiver > receiver)
Definition at line 1159 of file cpp-heap.cc.
                                                           {
  for (auto custom_space_index : custom_spaces) {
    const cppgc::internal::BaseSpace* space =
        raw_heap.CustomSpace(custom_space_index);
    size_t allocated_bytes = std::accumulate(
        space->begin(), space->end(), 0, [](size_t sum, auto* page) {
          return sum + page->AllocatedBytesAtLastGC();
        });
    receiver->AllocatedBytes(custom_space_index, allocated_bytes);
  }
}
References cppgc::internal::RawHeap::CustomSpace(), and space.
Referenced by v8::internal::CppHeap::CollectCustomSpaceStatisticsAtLastGC(), and v8::internal::anonymous_namespace{cpp-heap.cc}::CollectCustomSpaceStatisticsAtLastGCTask::Run().
ShouldReduceMemory()
bool v8::internal::anonymous_namespace{cpp-heap.cc}::ShouldReduceMemory (CppHeap::GarbageCollectionFlags flags)
Definition at line 696 of file cpp-heap.cc.
                                                             {
  return IsMemoryReducingGC(flags) || IsForceGC(flags);
}
References v8::internal::flags, IsForceGC(), and IsMemoryReducingGC().
Referenced by v8::internal::CppHeap::CompactAndSweep(), v8::internal::CppHeap::FinishSweepingIfRunning(), and v8::internal::CppHeap::InitializeMarking().
Variable Documentation
kIncrementalMarkingCheckInterval
constexpr size_t v8::internal::anonymous_namespace{cpp-heap.cc}::kIncrementalMarkingCheckInterval = 128 * KB [constexpr]
Definition at line 700 of file cpp-heap.cc.
Referenced by v8::internal::CppHeap::ReportBufferedAllocationSizeIfPossible().