v8::internal::compiler::anonymous_namespace{js-context-specialization.cc} Namespace Reference
Functions
bool IsContextParameter (Node *node)
OptionalContextRef GetSpecializationContext (JSHeapBroker *broker, Node *node, size_t *distance, Maybe< OuterContext > maybe_outer)
Function Documentation
GetSpecializationContext()
OptionalContextRef v8::internal::compiler::anonymous_namespace{js-context-specialization.cc}::GetSpecializationContext (JSHeapBroker * broker, Node * node, size_t * distance, Maybe< OuterContext > maybe_outer)
Definition at line 150 of file js-context-specialization.cc.
                                                                             {
  switch (node->opcode()) {
    case IrOpcode::kHeapConstant: {
      // TODO(jgruber,chromium:1209798): Using kAssumeMemoryFence works around
      // the fact that the graph stores handles (and not refs). The assumption
      // is that any handle inserted into the graph is safe to read; but we
      // don't preserve the reason why it is safe to read. Thus we must
      // over-approximate here and assume the existence of a memory fence. In
      // the future, we should consider having the graph store ObjectRefs or
      // ObjectData pointer instead, which would make new ref construction here
      // unnecessary.
      HeapObjectRef object =
          MakeRefAssumeMemoryFence(broker, HeapConstantOf(node->op()));
      if (object.IsContext()) return object.AsContext();
      break;
    }
    case IrOpcode::kParameter: {
      OuterContext outer;
      if (maybe_outer.To(&outer) && IsContextParameter(node) &&
          *distance >= outer.distance) {
        *distance -= outer.distance;
        return MakeRef(broker, outer.context);
      }
      break;
    }
    default:
      break;
  }
  return OptionalContextRef();
}
References broker(), v8::internal::compiler::OuterContext::context, v8::internal::compiler::OuterContext::distance, v8::internal::compiler::HeapConstantOf(), IsContextParameter(), v8::internal::compiler::MakeRef(), v8::internal::compiler::MakeRefAssumeMemoryFence(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), and v8::Maybe< T >::To().
Referenced by v8::internal::compiler::JSContextSpecialization::ReduceJSLoadContext(), v8::internal::compiler::JSContextSpecialization::ReduceJSLoadContextNoCell(), v8::internal::compiler::JSContextSpecialization::ReduceJSStoreContext(), and v8::internal::compiler::JSContextSpecialization::ReduceJSStoreContextNoCell().
IsContextParameter()
bool v8::internal::compiler::anonymous_namespace{js-context-specialization.cc}::IsContextParameter (Node * node)
Definition at line 139 of file js-context-specialization.cc.
                                    {
  DCHECK_EQ(IrOpcode::kParameter, node->opcode());
  return ParameterIndexOf(node->op()) ==
         StartNode{NodeProperties::GetValueInput(node, 0)}
             .ContextParameterIndex_MaybeNonStandardLayout();
}
References DCHECK_EQ, v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), and v8::internal::compiler::ParameterIndexOf().
Referenced by v8::internal::compiler::GetModuleContext(), and GetSpecializationContext().