v8::internal::compiler::anonymous_namespace{simplified-operator.cc} Namespace Reference
Classes
class TransitionAndStoreElementParameters
class TransitionAndStoreNonNumberElementParameters
class TransitionAndStoreNumberElementParameters
Functions
bool operator== (TransitionAndStoreElementParameters const &lhs, TransitionAndStoreElementParameters const &rhs)
size_t hash_value (TransitionAndStoreElementParameters parameters)
std::ostream & operator<< (std::ostream &os, TransitionAndStoreElementParameters parameters)
bool operator== (TransitionAndStoreNonNumberElementParameters const &lhs, TransitionAndStoreNonNumberElementParameters const &rhs)
size_t hash_value (TransitionAndStoreNonNumberElementParameters parameters)
std::ostream & operator<< (std::ostream &os, TransitionAndStoreNonNumberElementParameters parameters)
bool operator== (TransitionAndStoreNumberElementParameters const &lhs, TransitionAndStoreNumberElementParameters const &rhs)
size_t hash_value (TransitionAndStoreNumberElementParameters parameters)
std::ostream & operator<< (std::ostream &os, TransitionAndStoreNumberElementParameters parameters)
Function Documentation
hash_value() [1/3]
size_t v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::hash_value (TransitionAndStoreElementParameters parameters)
Definition at line 449 of file simplified-operator.cc.
                                                                  {
  return base::hash_combine(parameters.fast_map(), parameters.double_map());
}
References v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::TransitionAndStoreElementParameters::double_map(), v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::TransitionAndStoreElementParameters::fast_map(), and v8::base::hash_combine().
hash_value() [2/3]
size_t v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::hash_value (TransitionAndStoreNonNumberElementParameters parameters)
Definition at line 488 of file simplified-operator.cc.
                                                                           {
  return base::hash_combine(parameters.fast_map(), parameters.value_type());
}
References v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::TransitionAndStoreNonNumberElementParameters::fast_map(), v8::base::hash_combine(), and v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::TransitionAndStoreNonNumberElementParameters::value_type().
hash_value() [3/3]
size_t v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::hash_value (TransitionAndStoreNumberElementParameters parameters)
Definition at line 522 of file simplified-operator.cc.
                                                                        {
  return base::hash_combine(parameters.double_map());
}
References v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::TransitionAndStoreNumberElementParameters::double_map(), and v8::base::hash_combine().
operator<<() [1/3]
std::ostream& v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::operator<< (std::ostream & os, TransitionAndStoreElementParameters parameters)
Definition at line 453 of file simplified-operator.cc.
                                                                         {
  return os << "fast-map" << Brief(*parameters.fast_map().object())
            << " double-map" << Brief(*parameters.double_map().object());
}
References v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::TransitionAndStoreElementParameters::double_map(), v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::TransitionAndStoreElementParameters::fast_map(), and v8::internal::compiler::MapRef::object().
operator<<() [2/3]
std::ostream& v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::operator<< (std::ostream & os, TransitionAndStoreNonNumberElementParameters parameters)
Definition at line 492 of file simplified-operator.cc.
                                                                             {
  return os << parameters.value_type() << ", fast-map"
            << Brief(*parameters.fast_map().object());
}
References v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::TransitionAndStoreNonNumberElementParameters::fast_map(), v8::internal::compiler::MapRef::object(), and v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::TransitionAndStoreNonNumberElementParameters::value_type().
operator<<() [3/3]
std::ostream& v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::operator<< (std::ostream & os, TransitionAndStoreNumberElementParameters parameters)
Definition at line 526 of file simplified-operator.cc.
                                                                               {
  return os << "double-map" << Brief(*parameters.double_map().object());
}
References v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::TransitionAndStoreNumberElementParameters::double_map(), and v8::internal::compiler::MapRef::object().
operator==() [1/3]
bool v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::operator== (TransitionAndStoreElementParameters const & lhs, TransitionAndStoreElementParameters const & rhs)
Definition at line 443 of file simplified-operator.cc.
                                                                {
  return lhs.fast_map() == rhs.fast_map() &&
         lhs.double_map() == rhs.double_map();
}
References v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::TransitionAndStoreElementParameters::double_map(), and v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::TransitionAndStoreElementParameters::fast_map().
operator==() [2/3]
bool v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::operator== (TransitionAndStoreNonNumberElementParameters const & lhs, TransitionAndStoreNonNumberElementParameters const & rhs)
Definition at line 482 of file simplified-operator.cc.
                                                                         {
  return lhs.fast_map() == rhs.fast_map() &&
         lhs.value_type() == rhs.value_type();
}
References v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::TransitionAndStoreNonNumberElementParameters::fast_map(), and v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::TransitionAndStoreNonNumberElementParameters::value_type().
operator==() [3/3]
bool v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::operator== (TransitionAndStoreNumberElementParameters const & lhs, TransitionAndStoreNumberElementParameters const & rhs)
Definition at line 517 of file simplified-operator.cc.
                                                                      {
  return lhs.double_map() == rhs.double_map();
}
References v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::TransitionAndStoreNumberElementParameters::double_map().