v8::internal::anonymous_namespace{code-serializer.cc} Namespace Reference
Classes
class StressOffThreadDeserializeThread
Functions
void CreateInterpreterDataForDeserializedCode (Isolate *isolate, DirectHandle< SharedFunctionInfo > result_sfi, bool log_code_creation)
void FinalizeDeserialization (Isolate *isolate, DirectHandle< SharedFunctionInfo > result, const base::ElapsedTimer &timer, const ScriptDetails &script_details)
void BaselineBatchCompileIfSparkplugCompiled (Isolate *, Tagged< Script >)
const char * ToString (SerializedCodeSanityCheckResult result)
Function Documentation
BaselineBatchCompileIfSparkplugCompiled()
void v8::internal::anonymous_namespace{code-serializer.cc}::BaselineBatchCompileIfSparkplugCompiled (Isolate * , Tagged< Script >)
Definition at line 454 of file code-serializer.cc.
{}
Referenced by v8::internal::CodeSerializer::Deserialize(), and v8::internal::CodeSerializer::FinishOffThreadDeserialize().
CreateInterpreterDataForDeserializedCode()
void v8::internal::anonymous_namespace{code-serializer.cc}::CreateInterpreterDataForDeserializedCode (Isolate * isolate, DirectHandle< SharedFunctionInfo > result_sfi, bool log_code_creation)
Definition at line 294 of file code-serializer.cc.
                            {
  DCHECK_IMPLIES(log_code_creation, isolate->NeedsSourcePositions());
  DirectHandle<Script> script(Cast<Script>(result_sfi->script()), isolate);
  if (log_code_creation) Script::InitLineEnds(isolate, script);
  Tagged<String> name = ReadOnlyRoots(isolate).empty_string();
  if (IsString(script->name())) name = Cast<String>(script->name());
  DirectHandle<String> name_handle(name, isolate);
  SharedFunctionInfo::ScriptIterator iter(isolate, *script);
  for (Tagged<SharedFunctionInfo> shared_info = iter.Next();
       !shared_info.is_null(); shared_info = iter.Next()) {
    IsCompiledScope is_compiled(shared_info, isolate);
    if (!is_compiled.is_compiled()) continue;
    DCHECK(shared_info->HasBytecodeArray());
    DirectHandle<SharedFunctionInfo> sfi(shared_info, isolate);
    DirectHandle<BytecodeArray> bytecode(sfi->GetBytecodeArray(isolate),
                                         isolate);
    DirectHandle<Code> code =
        Builtins::CreateInterpreterEntryTrampolineForProfiling(isolate);
    DirectHandle<InterpreterData> interpreter_data =
        isolate->factory()->NewInterpreterData(bytecode, code);
    if (sfi->HasBaselineCode()) {
      sfi->baseline_code(kAcquireLoad)
          ->set_bytecode_or_interpreter_data(*interpreter_data);
    } else {
      sfi->set_interpreter_data(isolate, *interpreter_data);
    }
    if (!log_code_creation) continue;
    DirectHandle<AbstractCode> abstract_code = Cast<AbstractCode>(code);
    Script::PositionInfo info;
    Script::GetPositionInfo(script, sfi->StartPosition(), &info);
    int line_num = info.line_start + 1;
    int column_num = info.line_end + 1;
    PROFILE(isolate,
            CodeCreateEvent(LogEventListener::CodeTag::kFunction, abstract_code,
                            sfi, name_handle, line_num, column_num));
  }
}
References code, v8::internal::Builtins::CreateInterpreterEntryTrampolineForProfiling(), v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::Isolate::factory(), v8::internal::Script::GetPositionInfo(), v8::internal::Script::InitLineEnds(), v8::internal::IsCompiledScope::is_compiled(), v8::kAcquireLoad, v8::internal::torque::ls::kFunction, v8::internal::Script::PositionInfo::line_end, v8::internal::Script::PositionInfo::line_start, v8::internal::name, v8::internal::Isolate::NeedsSourcePositions(), v8::internal::Factory::NewInterpreterData(), v8::internal::SharedFunctionInfo::ScriptIterator::Next(), PROFILE, and v8::internal::script.
Referenced by FinalizeDeserialization().
FinalizeDeserialization()
void v8::internal::anonymous_namespace{code-serializer.cc}::FinalizeDeserialization (Isolate * isolate, DirectHandle< SharedFunctionInfo > result, const base::ElapsedTimer & timer, const ScriptDetails & script_details)
Definition at line 372 of file code-serializer.cc.
                                                                  {
  // Devtools can report time in this function as profiler overhead, since none
  // of the following tasks would need to happen normally.
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.compile"),
               "V8.FinalizeDeserialization");
  const bool log_code_creation = isolate->IsLoggingCodeCreation();
  if (V8_UNLIKELY(isolate->interpreted_frames_native_stack())) {
    CreateInterpreterDataForDeserializedCode(isolate, result,
                                             log_code_creation);
  }
  DirectHandle<Script> script(Cast<Script>(result->script()), isolate);
  // Reset the script details, including host-defined options.
  {
    DisallowGarbageCollection no_gc;
    SetScriptFieldsFromDetails(isolate, *script, script_details, &no_gc);
  }
  bool needs_source_positions = isolate->NeedsSourcePositions();
  if (!log_code_creation && !needs_source_positions) return;
  if (needs_source_positions) {
    Script::InitLineEnds(isolate, script);
  }
  DirectHandle<String> name(IsString(script->name())
                                ? Cast<String>(script->name())
                                : ReadOnlyRoots(isolate).empty_string(),
                            isolate);
  if (V8_UNLIKELY(v8_flags.log_function_events)) {
    LOG(isolate,
        FunctionEvent("deserialize", script->id(),
                      timer.Elapsed().InMillisecondsF(),
                      result->StartPosition(), result->EndPosition(), *name));
  }
  SharedFunctionInfo::ScriptIterator iter(isolate, *script);
  for (Tagged<SharedFunctionInfo> info = iter.Next(); !info.is_null();
       info = iter.Next()) {
    if (!info->is_compiled()) continue;
    DirectHandle<SharedFunctionInfo> shared_info(info, isolate);
    if (needs_source_positions) {
      SharedFunctionInfo::EnsureSourcePositionsAvailable(isolate, shared_info);
    }
    Script::PositionInfo pos_info;
    Script::GetPositionInfo(script, shared_info->StartPosition(), &pos_info);
    int line_num = pos_info.line + 1;
    int column_num = pos_info.column + 1;
    PROFILE(
        isolate,
        CodeCreateEvent(
            shared_info->is_toplevel() ? LogEventListener::CodeTag::kScript
                                       : LogEventListener::CodeTag::kFunction,
            direct_handle(shared_info->abstract_code(isolate), isolate),
            shared_info, name, line_num, column_num));
  }
}
References v8::internal::Script::PositionInfo::column, CreateInterpreterDataForDeserializedCode(), v8::internal::direct_handle(), v8::base::ElapsedTimer::Elapsed(), v8::internal::SharedFunctionInfo::EnsureSourcePositionsAvailable(), v8::internal::Script::GetPositionInfo(), v8::internal::Script::InitLineEnds(), v8::base::TimeDelta::InMillisecondsF(), v8::internal::Isolate::interpreted_frames_native_stack(), v8::internal::Isolate::IsLoggingCodeCreation(), v8::internal::torque::ls::kFunction, v8::internal::Script::PositionInfo::line, LOG, v8::internal::name, v8::internal::Isolate::NeedsSourcePositions(), v8::internal::SharedFunctionInfo::ScriptIterator::Next(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, PROFILE, v8::base::internal::result, v8::internal::script, v8::internal::SetScriptFieldsFromDetails(), TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT0, v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by v8::internal::CodeSerializer::Deserialize(), and v8::internal::CodeSerializer::FinishOffThreadDeserialize().
ToString()
const char* v8::internal::anonymous_namespace{code-serializer.cc}::ToString (SerializedCodeSanityCheckResult result)
Definition at line 457 of file code-serializer.cc.
                                                             {
  switch (result) {
    case SerializedCodeSanityCheckResult::kSuccess:
      return "success";
    case SerializedCodeSanityCheckResult::kMagicNumberMismatch:
      return "magic number mismatch";
    case SerializedCodeSanityCheckResult::kVersionMismatch:
      return "version mismatch";
    case SerializedCodeSanityCheckResult::kSourceMismatch:
      return "source mismatch";
    case SerializedCodeSanityCheckResult::kFlagsMismatch:
      return "flags mismatch";
    case SerializedCodeSanityCheckResult::kChecksumMismatch:
      return "checksum mismatch";
    case SerializedCodeSanityCheckResult::kInvalidHeader:
      return "invalid header";
    case SerializedCodeSanityCheckResult::kLengthMismatch:
      return "length mismatch";
    case SerializedCodeSanityCheckResult::kReadOnlySnapshotChecksumMismatch:
      return "read-only snapshot checksum mismatch";
  }
}
References v8::internal::detail::kSuccess, and v8::base::internal::result.