v8::internal::anonymous_namespace{code-data-source.cc} Namespace Reference
Functions
InternedV8JsScript::Type GetJsScriptType (Tagged< Script > script)
InternedV8JsFunction::Kind GetJsFunctionKind (FunctionKind kind)
Function Documentation
GetJsFunctionKind()
InternedV8JsFunction::Kind v8::internal::anonymous_namespace{code-data-source.cc}::GetJsFunctionKind (FunctionKind kind)
Definition at line 62 of file code-data-source.cc.
                                                              {
  switch (kind) {
    case FunctionKind::kNormalFunction:
      return InternedV8JsFunction::KIND_NORMAL_FUNCTION;
    case FunctionKind::kModule:
      return InternedV8JsFunction::KIND_MODULE;
    case FunctionKind::kModuleWithTopLevelAwait:
      return InternedV8JsFunction::KIND_ASYNC_MODULE;
    case FunctionKind::kBaseConstructor:
      return InternedV8JsFunction::KIND_BASE_CONSTRUCTOR;
    case FunctionKind::kDefaultBaseConstructor:
      return InternedV8JsFunction::KIND_DEFAULT_BASE_CONSTRUCTOR;
    case FunctionKind::kDefaultDerivedConstructor:
      return InternedV8JsFunction::KIND_DEFAULT_DERIVED_CONSTRUCTOR;
    case FunctionKind::kDerivedConstructor:
      return InternedV8JsFunction::KIND_DERIVED_CONSTRUCTOR;
    case FunctionKind::kGetterFunction:
      return InternedV8JsFunction::KIND_GETTER_FUNCTION;
    case FunctionKind::kStaticGetterFunction:
      return InternedV8JsFunction::KIND_STATIC_GETTER_FUNCTION;
    case FunctionKind::kSetterFunction:
      return InternedV8JsFunction::KIND_SETTER_FUNCTION;
    case FunctionKind::kStaticSetterFunction:
      return InternedV8JsFunction::KIND_STATIC_SETTER_FUNCTION;
    case FunctionKind::kArrowFunction:
      return InternedV8JsFunction::KIND_ARROW_FUNCTION;
    case FunctionKind::kAsyncArrowFunction:
      return InternedV8JsFunction::KIND_ASYNC_ARROW_FUNCTION;
    case FunctionKind::kAsyncFunction:
      return InternedV8JsFunction::KIND_ASYNC_FUNCTION;
    case FunctionKind::kAsyncConciseMethod:
      return InternedV8JsFunction::KIND_ASYNC_CONCISE_METHOD;
    case FunctionKind::kStaticAsyncConciseMethod:
      return InternedV8JsFunction::KIND_STATIC_ASYNC_CONCISE_METHOD;
    case FunctionKind::kAsyncConciseGeneratorMethod:
      return InternedV8JsFunction::KIND_ASYNC_CONCISE_GENERATOR_METHOD;
    case FunctionKind::kStaticAsyncConciseGeneratorMethod:
      return InternedV8JsFunction::KIND_STATIC_ASYNC_CONCISE_GENERATOR_METHOD;
    case FunctionKind::kAsyncGeneratorFunction:
      return InternedV8JsFunction::KIND_ASYNC_GENERATOR_FUNCTION;
    case FunctionKind::kGeneratorFunction:
      return InternedV8JsFunction::KIND_GENERATOR_FUNCTION;
    case FunctionKind::kConciseGeneratorMethod:
      return InternedV8JsFunction::KIND_CONCISE_GENERATOR_METHOD;
    case FunctionKind::kStaticConciseGeneratorMethod:
      return InternedV8JsFunction::KIND_STATIC_CONCISE_GENERATOR_METHOD;
    case FunctionKind::kConciseMethod:
      return InternedV8JsFunction::KIND_CONCISE_METHOD;
    case FunctionKind::kStaticConciseMethod:
      return InternedV8JsFunction::KIND_STATIC_CONCISE_METHOD;
    case FunctionKind::kClassMembersInitializerFunction:
      return InternedV8JsFunction::KIND_CLASS_MEMBERS_INITIALIZER_FUNCTION;
    case FunctionKind::kClassStaticInitializerFunction:
      return InternedV8JsFunction::KIND_CLASS_STATIC_INITIALIZER_FUNCTION;
    case FunctionKind::kInvalid:
      return InternedV8JsFunction::KIND_INVALID;
  }
  return InternedV8JsFunction::KIND_UNKNOWN;
}
References v8::internal::kArrowFunction, v8::internal::kAsyncArrowFunction, v8::internal::kAsyncConciseGeneratorMethod, v8::internal::kAsyncConciseMethod, v8::internal::kAsyncFunction, v8::internal::kAsyncGeneratorFunction, v8::internal::kBaseConstructor, v8::internal::kClassMembersInitializerFunction, v8::internal::kClassStaticInitializerFunction, v8::internal::kConciseGeneratorMethod, v8::internal::kConciseMethod, v8::internal::kDefaultBaseConstructor, v8::internal::kDefaultDerivedConstructor, v8::internal::kDerivedConstructor, v8::internal::kGeneratorFunction, v8::internal::kGetterFunction, v8::internal::kInvalid, v8::internal::kModule, v8::internal::kModuleWithTopLevelAwait, v8::internal::kNormalFunction, v8::internal::kSetterFunction, v8::internal::kStaticAsyncConciseGeneratorMethod, v8::internal::kStaticAsyncConciseMethod, v8::internal::kStaticConciseGeneratorMethod, v8::internal::kStaticConciseMethod, v8::internal::kStaticGetterFunction, and v8::internal::kStaticSetterFunction.
Referenced by v8::internal::CodeDataSourceIncrementalState::InternJsFunction().
GetJsScriptType()
InternedV8JsScript::Type v8::internal::anonymous_namespace{code-data-source.cc}::GetJsScriptType (Tagged< Script > script)
Definition at line 38 of file code-data-source.cc.
                                                              {
  if (script->compilation_type() == Script::CompilationType::kEval) {
    return InternedV8JsScript::TYPE_EVAL;
  }
  // TODO(carlscab): Camillo to extend the Script::Type enum. compilation_type
  // will no longer be needed.
  switch (script->type()) {
    case Script::Type::kNative:
      return InternedV8JsScript::TYPE_NATIVE;
    case Script::Type::kExtension:
      return InternedV8JsScript::TYPE_EXTENSION;
    case Script::Type::kNormal:
      return InternedV8JsScript::TYPE_NORMAL;
#if V8_ENABLE_WEBASSEMBLY
    case Script::Type::kWasm:
      UNREACHABLE();
#endif // V8_ENABLE_WEBASSEMBLY
    case Script::Type::kInspector:
      return InternedV8JsScript::TYPE_INSPECTOR;
  }
}
References v8::internal::Script::kEval, v8::internal::Script::kExtension, v8::internal::Script::kInspector, v8::internal::Script::kNative, v8::internal::Script::kNormal, v8::internal::script, and v8::internal::UNREACHABLE().
Referenced by v8::internal::CodeDataSourceIncrementalState::InternJsScript().