v8::internal::anonymous_namespace{heap.cc} Namespace Reference
Functions
int NumberOfSemiSpaces ()
size_t MinorMSConcurrentMarkingTrigger (Heap *heap)
intptr_t CompareWords (int size, Tagged< HeapObject > a, Tagged< HeapObject > b)
void ReportDuplicates (int size, std::vector< Tagged< HeapObject >> *objects)
void FreeCachesOnMemoryPressure (Isolate *isolate)
template<typename Callback >
void InvokeExternalCallbacks (Isolate *isolate, Callback callback)
size_t GlobalMemorySizeFromV8Size (size_t v8_size)
void CompleteArrayBufferSweeping (Heap *heap)
template<typename TSlot , typename AtomicOp , typename NonAtomicOp >
void CopyOrMoveRangeImpl (Heap *heap, Tagged< HeapObject > dst_object, const TSlot dst_slot, const TSlot src_slot, int len, WriteBarrierMode mode, AtomicOp atomic_op, NonAtomicOp non_atomic_op)
GCTracer::Scope::ScopeId CollectorScopeId (GarbageCollector collector)
void ClearStubCaches (Isolate *isolate)
void CreateFillerObjectAtImpl (const WritableFreeSpace &free_space, Heap *heap, ClearFreedMemoryMode clear_memory_mode)
void VerifyNoNeedToClearSlots (Address start, Address end)
bool MayContainRecordedSlots (Tagged< HeapObject > object)
double ComputeMutatorUtilizationImpl (double mutator_speed, std::optional< double > gc_speed)
size_t ComputeReducedNewSpaceSize (NewSpace *new_space)
double PercentToLimit (size_t size_at_gc, size_t size_now, size_t limit)
size_t ReturnNull ()
Handle< WeakArrayList > CompactWeakArrayList (Heap *heap, Handle< WeakArrayList > array, AllocationType allocation)
Variables
static constexpr int kMaxConsecutiveIneffectiveMarkCompacts = 4
thread_local Address pending_layout_change_object_address = kNullAddress
Function Documentation
ClearStubCaches()
void v8::internal::anonymous_namespace{heap.cc}::ClearStubCaches (Isolate * isolate)
Definition at line 2283 of file heap.cc.
                                       {
  isolate->load_stub_cache()->Clear();
  isolate->store_stub_cache()->Clear();
  isolate->define_own_stub_cache()->Clear();
  if (isolate->is_shared_space_isolate()) {
    isolate->global_safepoint()->IterateClientIsolates([](Isolate* client) {
      client->load_stub_cache()->Clear();
      client->store_stub_cache()->Clear();
      client->define_own_stub_cache()->Clear();
    });
  }
}
References v8::internal::StubCache::Clear(), v8::internal::Isolate::define_own_stub_cache(), v8::internal::Isolate::global_safepoint(), v8::internal::Isolate::is_shared_space_isolate(), v8::internal::Heap::isolate(), v8::internal::GlobalSafepoint::IterateClientIsolates(), v8::internal::Isolate::load_stub_cache(), and v8::internal::Isolate::store_stub_cache().
Referenced by v8::internal::Heap::PerformGarbageCollection().
CollectorScopeId()
GCTracer::Scope::ScopeId v8::internal::anonymous_namespace{heap.cc}::CollectorScopeId (GarbageCollector collector)
Definition at line 2271 of file heap.cc.
                                                                  {
  switch (collector) {
    case GarbageCollector::MARK_COMPACTOR:
      return GCTracer::Scope::ScopeId::MARK_COMPACTOR;
    case GarbageCollector::MINOR_MARK_SWEEPER:
      return GCTracer::Scope::ScopeId::MINOR_MARK_SWEEPER;
    case GarbageCollector::SCAVENGER:
      return GCTracer::Scope::ScopeId::SCAVENGER;
  }
  UNREACHABLE();
}
References v8::internal::MARK_COMPACTOR, v8::internal::MINOR_MARK_SWEEPER, v8::internal::SCAVENGER, and v8::internal::UNREACHABLE().
Referenced by v8::internal::Heap::PerformGarbageCollection().
CompactWeakArrayList()
Handle<WeakArrayList> v8::internal::anonymous_namespace{heap.cc}::CompactWeakArrayList (Heap * heap, Handle< WeakArrayList > array, AllocationType allocation)
Definition at line 6458 of file heap.cc.
                                                                      {
  if (array->length() == 0) {
    return array;
  }
  int new_length = array->CountLiveWeakReferences();
  if (new_length == array->length()) {
    return array;
  }
  Handle<WeakArrayList> new_array = WeakArrayList::EnsureSpace(
      heap->isolate(),
      handle(ReadOnlyRoots(heap).empty_weak_array_list(), heap->isolate()),
      new_length, allocation);
  // Allocation might have caused GC and turned some of the elements into
  // cleared weak heap objects. Count the number of live references again and
  // fill in the new array.
  int copy_to = 0;
  for (int i = 0; i < array->length(); i++) {
    Tagged<MaybeObject> element = array->Get(i);
    if (element.IsCleared()) continue;
    new_array->Set(copy_to++, element);
  }
  new_array->set_length(copy_to);
  return new_array;
}
References v8::internal::WeakArrayList::EnsureSpace(), v8::internal::handle(), and v8::internal::TaggedImpl< kRefType, StorageType >::IsCleared().
Referenced by v8::internal::Heap::CompactWeakArrayLists().
CompareWords()
intptr_t v8::internal::anonymous_namespace{heap.cc}::CompareWords (int size, Tagged< HeapObject > a, Tagged< HeapObject > b)
Definition at line 1277 of file heap.cc.
                                                                            {
  int slots = size / kTaggedSize;
  DCHECK_EQ(a->Size(), size);
  DCHECK_EQ(b->Size(), size);
  Tagged_t* slot_a = reinterpret_cast<Tagged_t*>(a.address());
  Tagged_t* slot_b = reinterpret_cast<Tagged_t*>(b.address());
  for (int i = 0; i < slots; i++) {
    if (*slot_a != *slot_b) {
      return *slot_a - *slot_b;
    }
    slot_a++;
    slot_b++;
  }
  return 0;
}
References v8::internal::Tagged< HeapObject >::address(), DCHECK_EQ, v8::internal::kTaggedSize, and size().
Referenced by ReportDuplicates().
CompleteArrayBufferSweeping()
void v8::internal::anonymous_namespace{heap.cc}::CompleteArrayBufferSweeping (Heap * heap)
Definition at line 1996 of file heap.cc.
                                             {
  auto* array_buffer_sweeper = heap->array_buffer_sweeper();
  if (array_buffer_sweeper->sweeping_in_progress()) {
    auto* tracer = heap->tracer();
    GCTracer::Scope::ScopeId scope_id;
    switch (tracer->GetCurrentCollector()) {
      case GarbageCollector::MINOR_MARK_SWEEPER:
        scope_id = GCTracer::Scope::MINOR_MS_COMPLETE_SWEEP_ARRAY_BUFFERS;
        break;
      case GarbageCollector::SCAVENGER:
        scope_id = GCTracer::Scope::SCAVENGER_COMPLETE_SWEEP_ARRAY_BUFFERS;
        break;
      case GarbageCollector::MARK_COMPACTOR:
        scope_id = GCTracer::Scope::MC_COMPLETE_SWEEP_ARRAY_BUFFERS;
    }
    TRACE_GC_EPOCH_WITH_FLOW(
        tracer, scope_id, ThreadKind::kMain,
        array_buffer_sweeper->GetTraceIdForFlowEvent(scope_id),
        TRACE_EVENT_FLAG_FLOW_IN);
    array_buffer_sweeper->EnsureFinished();
  }
}
References v8::internal::Heap::array_buffer_sweeper(), v8::internal::ArrayBufferSweeper::EnsureFinished(), v8::internal::GCTracer::GetCurrentCollector(), v8::internal::ArrayBufferSweeper::GetTraceIdForFlowEvent(), v8::internal::kMain, v8::internal::MARK_COMPACTOR, v8::internal::MINOR_MARK_SWEEPER, v8::internal::SCAVENGER, v8::internal::ArrayBufferSweeper::sweeping_in_progress(), TRACE_EVENT_FLAG_FLOW_IN, TRACE_GC_EPOCH_WITH_FLOW, and v8::internal::Heap::tracer().
Referenced by v8::internal::Heap::EagerlyFreeExternalMemoryAndWasmCode(), v8::internal::Heap::EnsureSweepingCompleted(), and v8::internal::Heap::EnsureYoungSweepingCompleted().
ComputeMutatorUtilizationImpl()
double v8::internal::anonymous_namespace{heap.cc}::ComputeMutatorUtilizationImpl (double mutator_speed, std::optional< double > gc_speed)
Definition at line 3786 of file heap.cc.
                                                                   {
  constexpr double kMinMutatorUtilization = 0.0;
  constexpr double kConservativeGcSpeedInBytesPerMillisecond = 200000;
  if (mutator_speed == 0) return kMinMutatorUtilization;
  if (!gc_speed) gc_speed = kConservativeGcSpeedInBytesPerMillisecond;
  // Derivation:
  // mutator_utilization = mutator_time / (mutator_time + gc_time)
  // mutator_time = 1 / mutator_speed
  // gc_time = 1 / gc_speed
  // mutator_utilization = (1 / mutator_speed) /
  // (1 / mutator_speed + 1 / gc_speed)
  // mutator_utilization = gc_speed / (mutator_speed + gc_speed)
  return *gc_speed / (mutator_speed + *gc_speed);
}
Referenced by v8::internal::Heap::ComputeMutatorUtilization().
ComputeReducedNewSpaceSize()
size_t v8::internal::anonymous_namespace{heap.cc}::ComputeReducedNewSpaceSize (NewSpace * new_space)
Definition at line 3967 of file heap.cc.
                                                       {
  size_t new_capacity =
      std::max(new_space->MinimumCapacity(), 2 * new_space->Size());
  size_t rounded_new_capacity =
      ::RoundUp(new_capacity, PageMetadata::kPageSize);
  DCHECK_LE(new_space->TotalCapacity(), new_space->MaximumCapacity());
  return std::min(new_space->TotalCapacity(), rounded_new_capacity);
}
References DCHECK_LE, v8::internal::MutablePageMetadata::kPageSize, v8::internal::NewSpace::MaximumCapacity(), v8::internal::NewSpace::MinimumCapacity(), v8::internal::Heap::new_space(), RoundUp(), and v8::internal::NewSpace::TotalCapacity().
Referenced by v8::internal::Heap::ReduceNewSpaceSize(), and v8::internal::Heap::StartResizeNewSpace().
CopyOrMoveRangeImpl()
template<typename TSlot , typename AtomicOp , typename NonAtomicOp >
void v8::internal::anonymous_namespace{heap.cc}::CopyOrMoveRangeImpl (Heap * heap, Tagged< HeapObject > dst_object, const TSlot dst_slot, const TSlot src_slot, int len, WriteBarrierMode mode, AtomicOp atomic_op, NonAtomicOp non_atomic_op)
Definition at line 2081 of file heap.cc.
                                                    {
  DCHECK_GT(len, 0);
  DCHECK_NE(dst_object->map(), ReadOnlyRoots(heap).fixed_cow_array_map());
  MemoryChunk* dst_chunk = MemoryChunk::FromHeapObject(dst_object);
  // Young generation object with marking being off, we can use plain memcopy
  // without write barriers.
  if (!dst_chunk->IsFlagSet(MemoryChunk::POINTERS_FROM_HERE_ARE_INTERESTING)) {
    non_atomic_op(dst_slot, src_slot, len);
    return;
  }
  const TSlot dst_end(dst_slot + len);
  // Falling through here means either old generation object or marking being
  // on.
  DCHECK_IMPLIES(heap->sweeper()->IsIteratingPromotedPages(),
                 v8_flags.minor_ms);
  if ((heap->incremental_marking()->IsMarking() &&
       v8_flags.concurrent_marking) ||
      (v8_flags.minor_ms && heap->sweeper()->IsIteratingPromotedPages())) {
    atomic_op(dst_slot, dst_end, src_slot, len);
  } else {
    non_atomic_op(dst_slot, src_slot, len);
  }
  if (mode == SKIP_WRITE_BARRIER) {
    return;
  }
  WriteBarrier::ForRange(heap, dst_object, dst_slot, dst_end);
}
References DCHECK_GT, DCHECK_IMPLIES, DCHECK_NE, v8::internal::WriteBarrier::ForRange(), v8::internal::MemoryChunk::FromHeapObject(), v8::internal::MemoryChunk::IsFlagSet(), mode(), v8::internal::MemoryChunk::POINTERS_FROM_HERE_ARE_INTERESTING, v8::internal::SKIP_WRITE_BARRIER, and v8::internal::v8_flags.
Referenced by v8::internal::Heap::CopyRange(), and v8::internal::Heap::MoveRange().
CreateFillerObjectAtImpl()
void v8::internal::anonymous_namespace{heap.cc}::CreateFillerObjectAtImpl (const WritableFreeSpace & free_space, Heap * heap, ClearFreedMemoryMode clear_memory_mode)
Definition at line 3279 of file heap.cc.
                                                                      {
  int size = free_space.Size();
  if (size == 0) return;
  DCHECK_IMPLIES(V8_COMPRESS_POINTERS_8GB_BOOL,
                 IsAligned(free_space.Address(), kObjectAlignment8GbHeap));
  DCHECK_IMPLIES(V8_COMPRESS_POINTERS_8GB_BOOL,
                 IsAligned(size, kObjectAlignment8GbHeap));
  // TODO(v8:13070): Filler sizes are irrelevant for 8GB+ heaps. Adding them
  // should be avoided in this mode.
  ReadOnlyRoots roots(heap);
  if (size == kTaggedSize) {
    HeapObject::SetFillerMap(free_space,
                             roots.unchecked_one_pointer_filler_map());
    // Ensure the filler map is properly initialized.
    DCHECK(IsMap(
        HeapObject::FromAddress(free_space.Address())->map(heap->isolate())));
  } else if (size == 2 * kTaggedSize) {
    HeapObject::SetFillerMap(free_space,
                             roots.unchecked_two_pointer_filler_map());
    if (clear_memory_mode == ClearFreedMemoryMode::kClearFreedMemory) {
      free_space.ClearTagged<kTaggedSize>((size / kTaggedSize) - 1);
    }
    // Ensure the filler map is properly initialized.
    DCHECK(IsMap(
        HeapObject::FromAddress(free_space.Address())->map(heap->isolate())));
  } else {
    DCHECK_GT(size, 2 * kTaggedSize);
    HeapObject::SetFillerMap(free_space, roots.unchecked_free_space_map());
    FreeSpace::SetSize(free_space, size, kRelaxedStore);
    if (clear_memory_mode == ClearFreedMemoryMode::kClearFreedMemory) {
      free_space.ClearTagged<2 * kTaggedSize>((size / kTaggedSize) - 2);
    }
    // During bootstrapping we need to create a free space object before its
    // map is initialized. In this case we cannot access the map yet, as it
    // might be null, or not set up properly yet.
    DCHECK_IMPLIES(roots.is_initialized(RootIndex::kFreeSpaceMap),
                   IsMap(HeapObject::FromAddress(free_space.Address())
                             ->map(heap->isolate())));
  }
}
References v8::internal::WritableFreeSpace::Address(), v8::internal::WritableFreeSpace::ClearTagged(), v8::internal::DCHECK(), DCHECK_GT, DCHECK_IMPLIES, v8::internal::HeapObject::FromAddress(), v8::internal::ReadOnlyRoots::is_initialized(), IsAligned(), v8::internal::kClearFreedMemory, v8::internal::kObjectAlignment8GbHeap, v8::kRelaxedStore, v8::internal::kTaggedSize, v8::internal::HeapObject::SetFillerMap(), v8::internal::FreeSpace::SetSize(), v8::internal::WritableFreeSpace::Size(), size(), and V8_COMPRESS_POINTERS_8GB_BOOL.
Referenced by v8::internal::Heap::CreateFillerObjectAtRaw().
FreeCachesOnMemoryPressure()
void v8::internal::anonymous_namespace{heap.cc}::FreeCachesOnMemoryPressure (Isolate * isolate)
Definition at line 1337 of file heap.cc.
                                                  {
  isolate->AbortConcurrentOptimization(BlockingBehavior::kDontBlock);
  isolate->ClearSerializerData();
  isolate->compilation_cache()->Clear();
  // TODO(ishell): consider trimming number to string caches to initial size.
  if (v8_flags.discard_memory_pool_before_memory_pressure_gcs) {
    IsolateGroup::current()->page_pool()->ReleaseImmediately(isolate);
  }
}
References v8::internal::Isolate::AbortConcurrentOptimization(), v8::internal::CompilationCache::Clear(), v8::internal::Isolate::ClearSerializerData(), v8::internal::Isolate::compilation_cache(), v8::internal::IsolateGroup::current(), v8::internal::kDontBlock, v8::internal::IsolateGroup::page_pool(), v8::internal::PagePool::ReleaseImmediately(), and v8::internal::v8_flags.
Referenced by v8::internal::Heap::CheckMemoryPressure(), and v8::internal::Heap::CollectAllAvailableGarbage().
GlobalMemorySizeFromV8Size()
size_t v8::internal::anonymous_namespace{heap.cc}::GlobalMemorySizeFromV8Size (size_t v8_size)
Definition at line 1543 of file heap.cc.
                                                  {
  const size_t kGlobalMemoryToV8Ratio = 2;
  return std::min(static_cast<uint64_t>(std::numeric_limits<size_t>::max()),
                  static_cast<uint64_t>(v8_size) * kGlobalMemoryToV8Ratio);
}
Referenced by v8::internal::Heap::ConfigureHeap(), v8::internal::Heap::EnsureMinimumRemainingAllocationLimit(), v8::internal::Heap::RecomputeLimits(), v8::internal::Heap::RecomputeLimitsAfterLoadingIfNeeded(), v8::internal::Heap::ResetOldGenerationAndGlobalAllocationLimit(), and v8::internal::Heap::SetOldGenerationAndGlobalMaximumSize().
InvokeExternalCallbacks()
template<typename Callback >
void v8::internal::anonymous_namespace{heap.cc}::InvokeExternalCallbacks (Isolate * isolate, Callback callback)
Definition at line 1530 of file heap.cc.
                                                                  {
  DCHECK(!AllowJavascriptExecution::IsAllowed(isolate));
  AllowGarbageCollection allow_gc;
  // Temporary override any embedder stack state as callbacks may create
  // their own state on the stack and recursively trigger GC.
  EmbedderStackStateScope embedder_scope(
      isolate->heap(), EmbedderStackStateOrigin::kExplicitInvocation,
      StackState::kMayContainHeapPointers);
  VMState<EXTERNAL> callback_state(isolate);
  callback();
}
References v8::internal::DCHECK(), v8::internal::Isolate::heap(), v8::internal::Heap::isolate(), and v8::internal::kExplicitInvocation.
Referenced by v8::internal::Heap::CollectGarbage().
MayContainRecordedSlots()
bool v8::internal::anonymous_namespace{heap.cc}::MayContainRecordedSlots (Tagged< HeapObject > object)
Definition at line 3471 of file heap.cc.
                                                        {
  // New space object do not have recorded slots.
  if (HeapLayout::InYoungGeneration(object)) {
    return false;
  }
  // Allowlist objects that definitely do not have pointers.
  if (IsByteArray(object) || IsFixedDoubleArray(object)) return false;
  // Conservatively return true for other objects.
  return true;
}
References v8::internal::HeapLayout::InYoungGeneration().
Referenced by v8::internal::Heap::LeftTrimFixedArray(), v8::internal::Heap::NotifyObjectLayoutChange(), and v8::internal::Heap::RightTrimArray().
MinorMSConcurrentMarkingTrigger()
size_t v8::internal::anonymous_namespace{heap.cc}::MinorMSConcurrentMarkingTrigger (Heap * heap)
Definition at line 1224 of file heap.cc.
                                                   {
  size_t young_capacity = 0;
  if (v8_flags.sticky_mark_bits) {
    // TODO(333906585): Adjust parameters.
    young_capacity = heap->sticky_space()->Capacity() -
                     heap->sticky_space()->old_objects_size();
  } else {
    young_capacity = heap->new_space()->TotalCapacity();
  }
  return young_capacity * v8_flags.minor_ms_concurrent_marking_trigger / 100;
}
References v8::internal::v8_flags.
Referenced by v8::internal::Heap::StartMinorMSConcurrentMarkingIfNeeded().
NumberOfSemiSpaces()
int v8::internal::anonymous_namespace{heap.cc}::NumberOfSemiSpaces ()
Definition at line 312 of file heap.cc.
{ return v8_flags.minor_ms ? 1 : 2; }
References v8::internal::v8_flags.
Referenced by v8::internal::Heap::SemiSpaceSizeFromYoungGenerationSize(), and v8::internal::Heap::YoungGenerationSizeFromSemiSpaceSize().
PercentToLimit()
double v8::internal::anonymous_namespace{heap.cc}::PercentToLimit (size_t size_at_gc, size_t size_now, size_t limit)
Definition at line 5607 of file heap.cc.
                                                                        {
  if (size_now < size_at_gc) {
    return 0.0;
  }
  if (size_now > limit) {
    return 100.0;
  }
  const size_t current_bytes = size_now - size_at_gc;
  const size_t total_bytes = limit - size_at_gc;
  DCHECK_LE(current_bytes, total_bytes);
  return static_cast<double>(current_bytes) * 100 / total_bytes;
}
References DCHECK_LE.
Referenced by v8::internal::Heap::PercentToGlobalMemoryLimit(), and v8::internal::Heap::PercentToOldGenerationLimit().
ReportDuplicates()
void v8::internal::anonymous_namespace{heap.cc}::ReportDuplicates (int size, std::vector< Tagged< HeapObject >> * objects)
Definition at line 1293 of file heap.cc.
                                                                        {
  if (objects->empty()) return;
  sort(objects->begin(), objects->end(),
       [size](Tagged<HeapObject> a, Tagged<HeapObject> b) {
         intptr_t c = CompareWords(size, a, b);
         if (c != 0) return c < 0;
         return a < b;
       });
  std::vector<std::pair<int, Tagged<HeapObject>>> duplicates;
  Tagged<HeapObject> current = (*objects)[0];
  int count = 1;
  for (size_t i = 1; i < objects->size(); i++) {
    if (CompareWords(size, current, (*objects)[i]) == 0) {
      count++;
    } else {
      if (count > 1) {
        duplicates.push_back(std::make_pair(count - 1, current));
      }
      count = 1;
      current = (*objects)[i];
    }
  }
  if (count > 1) {
    duplicates.push_back(std::make_pair(count - 1, current));
  }
  int threshold = v8_flags.trace_duplicate_threshold_kb * KB;
  sort(duplicates.begin(), duplicates.end());
  for (auto it = duplicates.rbegin(); it != duplicates.rend(); ++it) {
    int duplicate_bytes = it->first * size;
    if (duplicate_bytes < threshold) break;
    PrintF("%d duplicates of size %d each (%dKB)\n", it->first, size,
           duplicate_bytes / KB);
    PrintF("Sample object: ");
    Print(it->second);
    PrintF("============================\n");
  }
}
References CompareWords(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::KB, v8::internal::Print(), v8::internal::PrintF(), size(), v8::base::sort(), and v8::internal::v8_flags.
Referenced by v8::internal::Heap::CollectAllAvailableGarbage().
ReturnNull()
size_t v8::internal::anonymous_namespace{heap.cc}::ReturnNull ()
Definition at line 5963 of file heap.cc.
{ return 0; }
VerifyNoNeedToClearSlots()
void v8::internal::anonymous_namespace{heap.cc}::VerifyNoNeedToClearSlots (Address start, Address end)
Definition at line 3334 of file heap.cc.
{}
Referenced by v8::internal::Heap::CreateFillerObjectAtRaw().
Variable Documentation
kMaxConsecutiveIneffectiveMarkCompacts
constexpr int v8::internal::anonymous_namespace{heap.cc}::kMaxConsecutiveIneffectiveMarkCompacts = 4 [static], [constexpr]
Definition at line 3858 of file heap.cc.
Referenced by v8::internal::Heap::CheckIneffectiveMarkCompact().
pending_layout_change_object_address
thread_local Address v8::internal::anonymous_namespace{heap.cc}::pending_layout_change_object_address = kNullAddress
Definition at line 4086 of file heap.cc.
Referenced by v8::internal::Heap::NotifyObjectLayoutChange(), and v8::internal::Heap::NotifyObjectLayoutChangeDone().