v8::internal::anonymous_namespace{temporal-parser.cc} Namespace Reference
Functions
constexpr bool IsTZLeadingChar (base::uc32 c)
constexpr bool IsTZChar (base::uc32 c)
constexpr bool IsDecimalSeparator (base::uc32 c)
constexpr bool IsDateTimeSeparator (base::uc32 c)
constexpr bool IsAsciiSign (base::uc32 c)
constexpr bool IsSign (base::uc32 c)
constexpr bool IsTimeZoneUTCOffsetSign (base::uc32 c)
constexpr base::uc32 CanonicalSign (base::uc32 c)
constexpr int32_t ToInt (base::uc32 c)
template<typename Char >
bool HasTwoDigits (base::Vector< Char > str, int32_t s, int32_t *out)
template<typename Char >
int32_t ScanTwoDigitsExpectValue (base::Vector< Char > str, int32_t s, int32_t expected, int32_t *out)
template<typename Char >
int32_t ScanTwoDigitsExpectRange (base::Vector< Char > str, int32_t s, int32_t min, int32_t max, int32_t *out)
template<typename Char >
int32_t ScanTwoDigitsExpectZeroOrRange (base::Vector< Char > str, int32_t s, int32_t min, int32_t max, int32_t *out)
template<typename Char >
int32_t ScanHour (base::Vector< Char > str, int32_t s, int32_t *out)
The TemporalParser use two types of internal routine:
template<typename Char >
int32_t ScanUnpaddedHour (base::Vector< Char > str, int32_t s)
template<typename Char >
int32_t ScanMinuteSecond (base::Vector< Char > str, int32_t s, int32_t *out)
template<typename Char >
int32_t ScanTimeSecond (base::Vector< Char > str, int32_t s, int32_t *out)
template<typename Char >
int32_t ScanFractionalPart (base::Vector< Char > str, int32_t s, int32_t *out)
template<typename Char >
int32_t ScanFraction (base::Vector< Char > str, int32_t s, int32_t *out)
template<typename Char >
int32_t ScanTimeFraction (base::Vector< Char > str, int32_t s, int32_t *out)
template<typename Char >
int32_t ScanTimeFraction (base::Vector< Char > str, int32_t s, ParsedISO8601Result *r)
template<typename Char >
int32_t ScanTimeSpec (base::Vector< Char > str, int32_t s, ParsedISO8601Result *r)
template<typename Char >
int32_t ScanTimeSpecSeparator (base::Vector< Char > str, int32_t s, ParsedISO8601Result *r)
template<typename Char >
int32_t ScanDateExtendedYear (base::Vector< Char > str, int32_t s, int32_t *out)
template<typename Char >
int32_t ScanDateFourDigitYear (base::Vector< Char > str, int32_t s, int32_t *out)
template<typename Char >
int32_t ScanDateMonth (base::Vector< Char > str, int32_t s, int32_t *out)
template<typename Char >
int32_t ScanDateDay (base::Vector< Char > str, int32_t s, int32_t *out)
template<typename Char >
int32_t ScanDate (base::Vector< Char > str, int32_t s, ParsedISO8601Result *r)
template<typename Char >
int32_t ScanDateMonthWithThirtyOneDays (base::Vector< Char > str, int32_t s)
template<typename Char >
int32_t ScanTimeZoneUTCOffsetFraction (base::Vector< Char > str, int32_t s, int32_t *out)
template<typename Char >
int32_t ScanTimeZoneNumericUTCOffset (base::Vector< Char > str, int32_t s, ParsedISO8601Result *r)
template<typename Char >
int32_t ScanTimeZoneUTCOffset (base::Vector< Char > str, int32_t s, ParsedISO8601Result *r)
template<typename Char >
int32_t ScanTimeZoneIANANameComponent (base::Vector< Char > str, int32_t s)
template<typename Char >
int32_t ScanTimeZoneIANALegacyName (base::Vector< Char > str, int32_t s)
template<typename Char >
int32_t ScanEtcGMTASCIISignUnpaddedHour (base::Vector< Char > str, int32_t s)
template<typename Char >
int32_t ScanTimeZoneIANAName (base::Vector< Char > str, int32_t s)
template<typename Char >
int32_t ScanTimeZoneUTCOffsetName (base::Vector< Char > str, int32_t s)
template<typename Char >
int32_t ScanEtcGMTAsciiSignHour (base::Vector< Char > str, int32_t s)
template<typename Char >
int32_t ScanTimeZoneIdentifier (base::Vector< Char > str, int32_t s, ParsedISO8601Result *r)
template<typename Char >
int32_t ScanTimeZoneBracketedAnnotation (base::Vector< Char > str, int32_t s, ParsedISO8601Result *r)
template<typename Char >
int32_t ScanTimeZoneOffsetRequired (base::Vector< Char > str, int32_t s, ParsedISO8601Result *r)
template<typename Char >
int32_t ScanTimeZoneNameRequired (base::Vector< Char > str, int32_t s, ParsedISO8601Result *r)
template<typename Char >
int32_t ScanTimeZone (base::Vector< Char > str, int32_t s, ParsedISO8601Result *r)
template<typename Char >
int32_t ScanValidMonthDay (base::Vector< Char > str, int32_t s)
template<typename Char >
int32_t ScanDateSpecYearMonth (base::Vector< Char > str, int32_t s, ParsedISO8601Result *r)
template<typename Char >
int32_t ScanTimeSpecWithOptionalTimeZoneNotAmbiguous (base::Vector< Char > str, int32_t s, ParsedISO8601Result *r)
template<typename Char >
int32_t ScanCalendarNameComponent (base::Vector< Char > str, int32_t s)
template<typename Char >
int32_t ScanCalendarName (base::Vector< Char > str, int32_t s, ParsedISO8601Result *r)
template<typename Char >
int32_t ScanCalendar (base::Vector< Char > str, int32_t s, ParsedISO8601Result *r)
template<typename Char >
int32_t ScanCalendarTime_L1 (base::Vector< Char > str, int32_t s, ParsedISO8601Result *r)
template<typename Char >
int32_t ScanCalendarTime_L2 (base::Vector< Char > str, int32_t s, ParsedISO8601Result *r)
template<typename Char >
int32_t ScanDateTime (base::Vector< Char > str, int32_t s, ParsedISO8601Result *r)
template<typename Char >
int32_t ScanDateSpecMonthDay (base::Vector< Char > str, int32_t s, ParsedISO8601Result *r)
template<typename Char >
int32_t ScanCalendarDateTime (base::Vector< Char > str, int32_t s, ParsedISO8601Result *r)
template<typename Char >
int32_t ScanCalendarDateTimeTimeRequired (base::Vector< Char > str, int32_t s, ParsedISO8601Result *r)
template<typename Char >
int32_t ScanTemporalZonedDateTimeString (base::Vector< Char > str, int32_t s, ParsedISO8601Result *r)
SCAN_EITHER_FORWARD (TemporalMonthDayString, DateSpecMonthDay, CalendarDateTime, ParsedISO8601Result) template< typename Char > int32_t ScanTemporalInstantString(base
template<typename Char >
bool SatisfyCalendarTime (base::Vector< Char > str, ParsedISO8601Result *r)
SATISIFY_EITHER (TemporalTimeString, CalendarTime, CalendarDateTimeTimeRequired, ParsedISO8601Result) SATISIFY_EITHER(TemporalYearMonthString
ParsedISO8601Result SATISIFY_EITHER (TemporalMonthDayString, DateSpecMonthDay, CalendarDateTime, ParsedISO8601Result) template< typename Char > int32_t ScanDigits(base
SCAN_FORWARD (DurationSecondsPart, DurationWholeSecondsFractionDesignator, ParsedISO8601Duration) template< typename Char > int32_t ScanDurationMinutesPart(base
template<typename Char >
int32_t ScanDurationHoursPart (base::Vector< Char > str, int32_t s, ParsedISO8601Duration *r)
template<typename Char >
int32_t ScanDurationTime (base::Vector< Char > str, int32_t s, ParsedISO8601Duration *r)
template<typename Char >
int32_t ScanDurationWeeksPart (base::Vector< Char > str, int32_t s, ParsedISO8601Duration *r)
template<typename Char >
int32_t ScanDurationMonthsPart (base::Vector< Char > str, int32_t s, ParsedISO8601Duration *r)
template<typename Char >
int32_t ScanDurationYearsPart (base::Vector< Char > str, int32_t s, ParsedISO8601Duration *r)
template<typename Char >
int32_t ScanDurationDate (base::Vector< Char > str, int32_t s, ParsedISO8601Duration *r)
template<typename Char >
int32_t ScanDuration (base::Vector< Char > str, int32_t s, ParsedISO8601Duration *r)
Variables
constexpr int kPowerOfTen []
DateSpecYearMonth
CalendarDateTime
Function Documentation
CanonicalSign()
constexpr base::uc32 v8::internal::anonymous_namespace{temporal-parser.cc}::CanonicalSign (base::uc32 c) [inline], [constexpr]
Definition at line 51 of file temporal-parser.cc.
                                                    {
  return c == 0x2212 ? '-' : c;
}
Referenced by ScanDateExtendedYear(), ScanDuration(), and ScanTimeZoneNumericUTCOffset().
HasTwoDigits()
template<typename Char >
bool v8::internal::anonymous_namespace{temporal-parser.cc}::HasTwoDigits (base::Vector< Char > str, int32_t s, int32_t * out)
Definition at line 59 of file temporal-parser.cc.
                                                                 {
  if (str.length() >= (s + 2) && IsDecimalDigit(str[s]) &&
      IsDecimalDigit(str[s + 1])) {
    *out = ToInt(str[s]) * 10 + ToInt(str[s + 1]);
    return true;
  }
  return false;
}
References v8::internal::IsDecimalDigit(), v8::base::Vector< T >::length(), and ToInt().
Referenced by ScanDateMonthWithThirtyOneDays().
IsAsciiSign()
constexpr bool v8::internal::anonymous_namespace{temporal-parser.cc}::IsAsciiSign (base::uc32 c) [inline], [constexpr]
Definition at line 39 of file temporal-parser.cc.
{ return c == '-' || c == '+'; }
Referenced by IsSign(), ScanEtcGMTAsciiSignHour(), and ScanEtcGMTASCIISignUnpaddedHour().
IsDateTimeSeparator()
constexpr bool v8::internal::anonymous_namespace{temporal-parser.cc}::IsDateTimeSeparator (base::uc32 c) [inline], [constexpr]
Definition at line 34 of file temporal-parser.cc.
                                                      {
  return c == ' ' || AsciiAlphaToLower(c) == 't';
}
References v8::internal::AsciiAlphaToLower().
Referenced by ScanTimeSpecSeparator().
IsDecimalSeparator()
constexpr bool v8::internal::anonymous_namespace{temporal-parser.cc}::IsDecimalSeparator (base::uc32 c) [inline], [constexpr]
Definition at line 29 of file temporal-parser.cc.
                                                     {
  return c == '.' || c == ',';
}
Referenced by ScanFraction(), ScanTimeFraction(), and ScanTimeZoneUTCOffsetFraction().
IsSign()
constexpr bool v8::internal::anonymous_namespace{temporal-parser.cc}::IsSign (base::uc32 c) [inline], [constexpr]
Definition at line 42 of file temporal-parser.cc.
                                         {
  return c == 0x2212 || IsAsciiSign(c);
}
References IsAsciiSign().
Referenced by IsTimeZoneUTCOffsetSign(), ScanDateExtendedYear(), ScanDuration(), and ScanTimeZoneUTCOffsetName().
IsTimeZoneUTCOffsetSign()
constexpr bool v8::internal::anonymous_namespace{temporal-parser.cc}::IsTimeZoneUTCOffsetSign (base::uc32 c) [inline], [constexpr]
Definition at line 47 of file temporal-parser.cc.
                                                          {
  return IsSign(c);
}
References IsSign().
Referenced by ScanTimeZoneNumericUTCOffset().
IsTZChar()
constexpr bool v8::internal::anonymous_namespace{temporal-parser.cc}::IsTZChar (base::uc32 c) [inline], [constexpr]
Definition at line 24 of file temporal-parser.cc.
                                           {
  return IsTZLeadingChar(c) || c == '-';
}
References IsTZLeadingChar().
Referenced by ScanTimeZoneIANANameComponent().
IsTZLeadingChar()
constexpr bool v8::internal::anonymous_namespace{temporal-parser.cc}::IsTZLeadingChar (base::uc32 c) [inline], [constexpr]
Definition at line 18 of file temporal-parser.cc.
                                                  {
  return base::IsInRange(AsciiAlphaToLower(c), 'a', 'z') || c == '.' ||
         c == '_';
}
References v8::internal::AsciiAlphaToLower().
Referenced by IsTZChar(), and ScanTimeZoneIANANameComponent().
SatisfyCalendarTime()
template<typename Char >
bool v8::internal::anonymous_namespace{temporal-parser.cc}::SatisfyCalendarTime (base::Vector< Char > str, ParsedISO8601Result * r)
Definition at line 1123 of file temporal-parser.cc.
                                                                       {
  IF_SATISFY_RETURN(CalendarTime_L1)
  IF_SATISFY_RETURN(CalendarTime_L2)
  return false;
}
References IF_SATISFY_RETURN.
SATISIFY_EITHER() [1/2]
ParsedISO8601Result v8::internal::anonymous_namespace{temporal-parser.cc}::SATISIFY_EITHER (TemporalMonthDayString , DateSpecMonthDay , CalendarDateTime , ParsedISO8601Result)
Definition at line 1133 of file temporal-parser.cc.
                                                                 {
  if (str.length() < (s + 1) || !IsDecimalDigit(str[s])) return 0;
  *out = ToInt(str[s]);
  int32_t len = 1;
  while (s + len + 1 <= str.length() && IsDecimalDigit(str[s + len])) {
    *out = 10 * (*out) + ToInt(str[s + len]);
    len++;
  }
  return len;
}
References v8::internal::IsDecimalDigit(), and ToInt().
SATISIFY_EITHER() [2/2]
v8::internal::anonymous_namespace{temporal-parser.cc}::SATISIFY_EITHER (TemporalTimeString , CalendarTime , CalendarDateTimeTimeRequired , ParsedISO8601Result)
SCAN_EITHER_FORWARD()
v8::internal::anonymous_namespace{temporal-parser.cc}::SCAN_EITHER_FORWARD (TemporalMonthDayString , DateSpecMonthDay , CalendarDateTime , ParsedISO8601Result)
Definition at line 1062 of file temporal-parser.cc.
                                                          {
  // Date
  int32_t cur = s;
  int32_t len = ScanDate(str, cur, r);
  if (len == 0) return 0;
  cur += len;
  // [TimeSpecSeparator]
  cur += ScanTimeSpecSeparator(str, cur, r);
  // TimeZoneOffsetRequired
  len = ScanTimeZoneOffsetRequired(str, cur, r);
  if (len == 0) return 0;
  cur += len;
  // [Calendar]
  cur += ScanCalendar(str, cur, r);
  return cur - s;
}
References ScanCalendar(), ScanDate(), ScanTimeSpecSeparator(), and ScanTimeZoneOffsetRequired().
SCAN_FORWARD()
v8::internal::anonymous_namespace{temporal-parser.cc}::SCAN_FORWARD (DurationSecondsPart , DurationWholeSecondsFractionDesignator , ParsedISO8601Duration)
Definition at line 1205 of file temporal-parser.cc.
                                                          {
  int32_t cur = s;
  int32_t len = ScanDurationWholeMinutesFractionDesignator(str, s, r);
  if (len == 0) return 0;
  cur += len;
  cur += ScanDurationSecondsPart(str, cur, r);
  return cur - s;
}
ScanCalendar()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanCalendar (base::Vector< Char > str, int32_t s, ParsedISO8601Result * r)
Definition at line 873 of file temporal-parser.cc.
                                             {
  if (str.length() < (s + 7)) return 0;
  int32_t cur = s;
  // "[u-ca="
  if ((str[cur++] != '[') || (str[cur++] != 'u') || (str[cur++] != '-') ||
      (str[cur++] != 'c') || (str[cur++] != 'a') || (str[cur++] != '=')) {
    return 0;
  }
  int32_t len = ScanCalendarName(str, cur, r);
  if (len == 0) return 0;
  if ((str.length() < (cur + len + 1)) || (str[cur + len] != ']')) {
    // Only ScanCalendar know the post condition of CalendarName is not met and
    // need to reset here.
    r->calendar_name_start = 0;
    r->calendar_name_length = 0;
    return 0;
  }
  return 6 + len + 1;
}
References v8::internal::ParsedISO8601Result::calendar_name_length, v8::internal::ParsedISO8601Result::calendar_name_start, v8::base::Vector< T >::length(), and ScanCalendarName().
Referenced by SCAN_EITHER_FORWARD(), ScanCalendarDateTime(), ScanCalendarDateTimeTimeRequired(), ScanCalendarTime_L1(), ScanCalendarTime_L2(), and ScanTemporalZonedDateTimeString().
ScanCalendarDateTime()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanCalendarDateTime (base::Vector< Char > str, int32_t s, ParsedISO8601Result * r)
Definition at line 1007 of file temporal-parser.cc.
                                                     {
  int32_t len = ScanDateTime(str, s, r);
  if (len == 0) return 0;
  return len + ScanCalendar(str, len, r);
}
References ScanCalendar(), and ScanDateTime().
ScanCalendarDateTimeTimeRequired()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanCalendarDateTimeTimeRequired (base::Vector< Char > str, int32_t s, ParsedISO8601Result * r)
Definition at line 1016 of file temporal-parser.cc.
                                                                 {
  int32_t cur = s;
  int32_t len = ScanDate(str, cur, r);
  if (len == 0) return 0;
  cur += len;
  len = ScanTimeSpecSeparator(str, cur, r);
  if (len == 0) return 0;
  cur += len;
  // [TimeZone]
  cur += ScanTimeZone(str, cur, r);
  // [Calendar]
  cur += ScanCalendar(str, cur, r);
  return cur - s;
}
References ScanCalendar(), ScanDate(), ScanTimeSpecSeparator(), and ScanTimeZone().
ScanCalendarName()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanCalendarName (base::Vector< Char > str, int32_t s, ParsedISO8601Result * r)
Definition at line 855 of file temporal-parser.cc.
                                                 {
  int32_t cur = s;
  int32_t len;
  if ((len = ScanCalendarNameComponent(str, cur)) == 0) return 0;
  cur += len;
  while ((str.length() > (cur + 1)) && (str[cur++] == '-')) {
    if ((len = ScanCalendarNameComponent(str, cur)) == 0) return 0;
    // CalendarNameComponent - CalendarName
    cur += len;
  }
  r->calendar_name_start = s;
  r->calendar_name_length = cur - s;
  return cur - s;
}
References v8::internal::ParsedISO8601Result::calendar_name_length, v8::internal::ParsedISO8601Result::calendar_name_start, v8::base::Vector< T >::length(), and ScanCalendarNameComponent().
Referenced by ScanCalendar().
ScanCalendarNameComponent()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanCalendarNameComponent (base::Vector< Char > str, int32_t s)
Definition at line 840 of file temporal-parser.cc.
                                                                   {
  int32_t cur = s;
  while ((cur < str.length()) && IsAlphaNumeric(str[cur])) cur++;
  if ((cur - s) < 3 || (cur - s) > 8) return 0;
  return cur - s;
}
References v8::internal::IsAlphaNumeric(), and v8::base::Vector< T >::length().
Referenced by ScanCalendarName().
ScanCalendarTime_L1()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanCalendarTime_L1 (base::Vector< Char > str, int32_t s, ParsedISO8601Result * r)
Definition at line 897 of file temporal-parser.cc.
                                                    {
  int32_t cur = s;
  if (str.length() < (s + 1)) return 0;
  // TimeDesignator
  if (AsciiAlphaToLower(str[cur++]) != 't') return 0;
  int32_t len = ScanTimeSpec(str, cur, r);
  if (len == 0) return 0;
  cur += len;
  // [TimeZone]
  cur += ScanTimeZone(str, cur, r);
  // [Calendar]
  cur += ScanCalendar(str, cur, r);
  return cur - s;
}
References v8::internal::AsciiAlphaToLower(), v8::base::Vector< T >::length(), ScanCalendar(), ScanTimeSpec(), and ScanTimeZone().
ScanCalendarTime_L2()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanCalendarTime_L2 (base::Vector< Char > str, int32_t s, ParsedISO8601Result * r)
Definition at line 916 of file temporal-parser.cc.
                                                    {
  int32_t cur = s;
  int32_t len = ScanTimeSpecWithOptionalTimeZoneNotAmbiguous(str, cur, r);
  if (len == 0) return 0;
  cur += len;
  // [Calendar]
  cur += ScanCalendar(str, cur, r);
  return cur - s;
}
References ScanCalendar(), and ScanTimeSpecWithOptionalTimeZoneNotAmbiguous().
ScanDate()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanDate (base::Vector< Char > str, int32_t s, ParsedISO8601Result * r)
Definition at line 363 of file temporal-parser.cc.
                                                                          {
  int32_t date_year, date_month, date_day;
  int32_t cur = s;
  int32_t len;
  if ((len = ScanDateYear(str, cur, &date_year)) == 0) return 0;
  if (((cur += len) + 1) > str.length()) return 0;
  if (str[cur] == '-') {
    cur++;
    if ((len = ScanDateMonth(str, cur, &date_month)) == 0) return 0;
    cur += len;
    if (((cur + 1) > str.length()) || (str[cur++] != '-')) return 0;
  } else {
    if ((len = ScanDateMonth(str, cur, &date_month)) == 0) return 0;
    cur += len;
  }
  if ((len = ScanDateDay(str, cur, &date_day)) == 0) return 0;
  r->date_year = date_year;
  r->date_month = date_month;
  r->date_day = date_day;
  return cur + len - s;
}
References v8::internal::ParsedISO8601Result::date_day, v8::internal::ParsedISO8601Result::date_month, v8::internal::ParsedISO8601Result::date_year, v8::base::Vector< T >::length(), ScanDateDay(), and ScanDateMonth().
Referenced by SCAN_EITHER_FORWARD(), ScanCalendarDateTimeTimeRequired(), ScanDateTime(), and ScanTemporalZonedDateTimeString().
ScanDateDay()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanDateDay (base::Vector< Char > str, int32_t s, int32_t * out)
Definition at line 355 of file temporal-parser.cc.
                                                                   {
  return ScanTwoDigitsExpectRange<Char>(str, s, 1, 31, out);
}
Referenced by ScanDate(), and ScanDateSpecMonthDay().
ScanDateExtendedYear()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanDateExtendedYear (base::Vector< Char > str, int32_t s, int32_t * out)
Definition at line 300 of file temporal-parser.cc.
                                                                            {
  if (str.length() < (s + 7)) return 0;
  if (IsSign(str[s]) && IsDecimalDigit(str[s + 1]) &&
      IsDecimalDigit(str[s + 2]) && IsDecimalDigit(str[s + 3]) &&
      IsDecimalDigit(str[s + 4]) && IsDecimalDigit(str[s + 5]) &&
      IsDecimalDigit(str[s + 6])) {
    int32_t sign = (CanonicalSign(str[s]) == '-') ? -1 : 1;
    *out = sign * (ToInt(str[s + 1]) * 100000 + ToInt(str[s + 2]) * 10000 +
                   ToInt(str[s + 3]) * 1000 + ToInt(str[s + 4]) * 100 +
                   ToInt(str[s + 5]) * 10 + ToInt(str[s + 6]));
    // In the end of #sec-temporal-iso8601grammar
    // It is a Syntax Error if DateExtendedYear is "-000000" or "000000"
    // (U+2212 MINUS SIGN followed by 000000).
    if (sign == -1 && *out == 0) return 0;
    return 7;
  }
  return 0;
}
References CanonicalSign(), v8::internal::IsDecimalDigit(), IsSign(), v8::base::Vector< T >::length(), v8::internal::sign, and ToInt().
ScanDateFourDigitYear()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanDateFourDigitYear (base::Vector< Char > str, int32_t s, int32_t * out)
Definition at line 321 of file temporal-parser.cc.
                                                                             {
  if (str.length() < (s + 4)) return 0;
  if (IsDecimalDigit(str[s]) && IsDecimalDigit(str[s + 1]) &&
      IsDecimalDigit(str[s + 2]) && IsDecimalDigit(str[s + 3])) {
    *out = ToInt(str[s]) * 1000 + ToInt(str[s + 1]) * 100 +
           ToInt(str[s + 2]) * 10 + ToInt(str[s + 3]);
    return 4;
  }
  return 0;
}
References v8::internal::IsDecimalDigit(), v8::base::Vector< T >::length(), and ToInt().
ScanDateMonth()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanDateMonth (base::Vector< Char > str, int32_t s, int32_t * out)
Definition at line 344 of file temporal-parser.cc.
                                                                     {
  return ScanTwoDigitsExpectRange<Char>(str, s, 1, 12, out);
}
Referenced by ScanDate(), ScanDateSpecMonthDay(), ScanDateSpecYearMonth(), and ScanValidMonthDay().
ScanDateMonthWithThirtyOneDays()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanDateMonthWithThirtyOneDays (base::Vector< Char > str, int32_t s)
Definition at line 388 of file temporal-parser.cc.
                                                                        {
  int32_t value;
  if (!HasTwoDigits(str, s, &value)) return false;
  return value == 1 || value == 3 || value == 5 || value == 7 || value == 8 ||
         value == 10 || value == 12;
}
References HasTwoDigits(), and v8::internal::value.
Referenced by ScanValidMonthDay().
ScanDateSpecMonthDay()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanDateSpecMonthDay (base::Vector< Char > str, int32_t s, ParsedISO8601Result * r)
Definition at line 962 of file temporal-parser.cc.
                                                     {
  if (str.length() < (s + 4)) return 0;
  int32_t cur = s;
  if (str[cur] == '-') {
    // The first two dash are optional together
    if (str[++cur] != '-') return 0;
    // TwoDash
    cur++;
  }
  int32_t date_month, date_day;
  int32_t len = ScanDateMonth(str, cur, &date_month);
  if (len == 0) return 0;
  cur += len;
  if (str.length() < (cur + 1)) return 0;
  // '-'
  if (str[cur] == '-') cur++;
  len = ScanDateDay(str, cur, &date_day);
  if (len == 0) return 0;
  r->date_month = date_month;
  r->date_day = date_day;
  cur += len;
  return cur - s;
}
References v8::internal::ParsedISO8601Result::date_day, v8::internal::ParsedISO8601Result::date_month, v8::base::Vector< T >::length(), ScanDateDay(), and ScanDateMonth().
ScanDateSpecYearMonth()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanDateSpecYearMonth (base::Vector< Char > str, int32_t s, ParsedISO8601Result * r)
Definition at line 942 of file temporal-parser.cc.
                                                      {
  int32_t date_year, date_month;
  int32_t cur = s;
  int32_t len = ScanDateYear(str, cur, &date_year);
  if (len == 0) return 0;
  cur += len;
  if (str.length() < (cur + 1)) return 0;
  if (str[cur] == '-') cur++;
  len = ScanDateMonth(str, cur, &date_month);
  if (len == 0) return 0;
  r->date_year = date_year;
  r->date_month = date_month;
  cur += len;
  return cur - s;
}
References v8::internal::ParsedISO8601Result::date_month, v8::internal::ParsedISO8601Result::date_year, v8::base::Vector< T >::length(), and ScanDateMonth().
Referenced by ScanTimeSpecWithOptionalTimeZoneNotAmbiguous().
ScanDateTime()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanDateTime (base::Vector< Char > str, int32_t s, ParsedISO8601Result * r)
Definition at line 929 of file temporal-parser.cc.
                                             {
  int32_t cur = s;
  int32_t len = ScanDate(str, cur, r);
  if (len == 0) return 0;
  cur += len;
  cur += ScanTimeSpecSeparator(str, cur, r);
  cur += ScanTimeZone(str, cur, r);
  return cur - s;
}
References ScanDate(), ScanTimeSpecSeparator(), and ScanTimeZone().
Referenced by ScanCalendarDateTime().
ScanDuration()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanDuration (base::Vector< Char > str, int32_t s, ParsedISO8601Duration * r)
Definition at line 1356 of file temporal-parser.cc.
                                               {
  if (str.length() < (s + 2)) return 0;
  int32_t cur = s;
  int32_t sign =
      (IsSign(str[cur]) && CanonicalSign(str[cur++]) == '-') ? -1 : 1;
  if (AsciiAlphaToLower(str[cur++]) != 'p') return 0;
  int32_t len = ScanDurationDate(str, cur, r);
  if (len == 0) len = ScanDurationTime(str, cur, r);
  if (len == 0) return 0;
  r->sign = sign;
  cur += len;
  return cur - s;
}
References v8::internal::AsciiAlphaToLower(), CanonicalSign(), IsSign(), v8::base::Vector< T >::length(), ScanDurationDate(), ScanDurationTime(), v8::internal::sign, and v8::internal::ParsedISO8601Duration::sign.
ScanDurationDate()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanDurationDate (base::Vector< Char > str, int32_t s, ParsedISO8601Duration * r)
Definition at line 1338 of file temporal-parser.cc.
                                                   {
  int32_t cur = s;
  do {
    if ((cur += ScanDurationYearsPart(str, cur, r)) > s) break;
    if ((cur += ScanDurationMonthsPart(str, cur, r)) > s) break;
    if ((cur += ScanDurationWeeksPart(str, cur, r)) > s) break;
    if ((cur += ScanDurationDaysPart(str, cur, r)) > s) break;
    return 0;
  } while (false);
  cur += ScanDurationTime(str, cur, r);
  return cur - s;
}
References ScanDurationMonthsPart(), ScanDurationTime(), ScanDurationWeeksPart(), and ScanDurationYearsPart().
Referenced by ScanDuration().
ScanDurationHoursPart()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanDurationHoursPart (base::Vector< Char > str, int32_t s, ParsedISO8601Duration * r)
Definition at line 1229 of file temporal-parser.cc.
                                                        {
  int32_t cur = s;
  int32_t len = ScanDurationWholeHoursFractionDesignator(str, s, r);
  if (len == 0) return 0;
  cur += len;
  len = ScanDurationMinutesPart(str, cur, r);
  if (len > 0) {
    cur += len;
  } else {
    cur += ScanDurationSecondsPart(str, cur, r);
  }
  return cur - s;
}
Referenced by ScanDurationTime().
ScanDurationMonthsPart()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanDurationMonthsPart (base::Vector< Char > str, int32_t s, ParsedISO8601Duration * r)
Definition at line 1296 of file temporal-parser.cc.
                                                         {
  int32_t cur = s;
  int32_t len = ScanDurationMonthsDesignator(str, cur, r);
  if (len == 0) return 0;
  cur += len;
  if ((len = ScanDurationWeeksPart(str, cur, r)) > 0) {
    cur += len;
  } else {
    cur += ScanDurationDaysPart(str, cur, r);
  }
  return cur - s;
}
References ScanDurationWeeksPart().
Referenced by ScanDurationDate(), and ScanDurationYearsPart().
ScanDurationTime()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanDurationTime (base::Vector< Char > str, int32_t s, ParsedISO8601Duration * r)
Definition at line 1249 of file temporal-parser.cc.
                                                   {
  int32_t cur = s;
  if (str.length() < (s + 1)) return 0;
  if (AsciiAlphaToLower(str[cur++]) != 't') return 0;
  if ((cur += ScanDurationHoursPart(str, cur, r)) - s > 1) return cur - s;
  if ((cur += ScanDurationMinutesPart(str, cur, r)) - s > 1) return cur - s;
  if ((cur += ScanDurationSecondsPart(str, cur, r)) - s > 1) return cur - s;
  return 0;
}
References v8::internal::AsciiAlphaToLower(), v8::base::Vector< T >::length(), and ScanDurationHoursPart().
Referenced by ScanDuration(), and ScanDurationDate().
ScanDurationWeeksPart()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanDurationWeeksPart (base::Vector< Char > str, int32_t s, ParsedISO8601Duration * r)
Definition at line 1284 of file temporal-parser.cc.
                                                        {
  int32_t cur = s;
  if ((cur += ScanDurationWeeksDesignator(str, cur, r)) == s) return 0;
  cur += ScanDurationDaysPart(str, cur, r);
  return cur - s;
}
Referenced by ScanDurationDate(), ScanDurationMonthsPart(), and ScanDurationYearsPart().
ScanDurationYearsPart()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanDurationYearsPart (base::Vector< Char > str, int32_t s, ParsedISO8601Duration * r)
Definition at line 1315 of file temporal-parser.cc.
                                                        {
  int32_t cur = s;
  int32_t len = ScanDurationYearsDesignator(str, cur, r);
  if (len == 0) return 0;
  cur += len;
  if ((len = ScanDurationMonthsPart(str, cur, r)) > 0) {
    cur += len;
  } else if ((len = ScanDurationWeeksPart(str, cur, r)) > 0) {
    cur += len;
  } else {
    len = ScanDurationDaysPart(str, cur, r);
    cur += len;
  }
  return cur - s;
}
References ScanDurationMonthsPart(), and ScanDurationWeeksPart().
Referenced by ScanDurationDate().
ScanEtcGMTAsciiSignHour()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanEtcGMTAsciiSignHour (base::Vector< Char > str, int32_t s)
Definition at line 680 of file temporal-parser.cc.
                                                                 {
  if ((s + 10) > str.length()) return 0;
  int32_t cur = s;
  if ((str[cur++] != 'E') || (str[cur++] != 't') || (str[cur++] != 'c') ||
      (str[cur++] != '/') || (str[cur++] != 'G') || (str[cur++] != 'M') ||
      (str[cur++] != 'T')) {
    return 0;
  }
  Char sign = str[cur++];
  if (!IsAsciiSign(sign)) return 0;
  int32_t hour;
  int32_t len = ScanHour(str, cur, &hour);
  if (len == 0) return 0;
  // "Etc/GMT" ASCIISign Hour
  return 10;
}
References IsAsciiSign(), v8::base::Vector< T >::length(), ScanHour(), and v8::internal::sign.
ScanEtcGMTASCIISignUnpaddedHour()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanEtcGMTASCIISignUnpaddedHour (base::Vector< Char > str, int32_t s)
Definition at line 576 of file temporal-parser.cc.
                                                                         {
  if ((s + 9) > str.length()) return 0;
  int32_t cur = s;
  int32_t len = arraysize("Etc/GMT") - 1;
  if (!CompareCharsEqual(str.begin() + cur, "Etc/GMT", len)) return 0;
  cur += len;
  Char sign = str[cur++];
  if (!IsAsciiSign(sign)) return 0;
  len = ScanUnpaddedHour(str, cur);
  if (len == 0) return 0;
  cur += len;
  return cur - s;
}
References arraysize, v8::base::Vector< T >::begin(), v8::internal::CompareCharsEqual(), IsAsciiSign(), v8::base::Vector< T >::length(), ScanUnpaddedHour(), and v8::internal::sign.
Referenced by ScanTimeZoneIANAName().
ScanFraction()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanFraction (base::Vector< Char > str, int32_t s, int32_t * out)
Definition at line 211 of file temporal-parser.cc.
                                                                    {
  if ((str.length() < (s + 2)) || (!IsDecimalSeparator(str[s]))) return 0;
  int32_t len;
  if ((len = ScanFractionalPart(str, s + 1, out)) == 0) return 0;
  return len + 1;
}
References IsDecimalSeparator(), v8::base::Vector< T >::length(), and ScanFractionalPart().
Referenced by ScanTimeZoneUTCOffsetName().
ScanFractionalPart()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanFractionalPart (base::Vector< Char > str, int32_t s, int32_t * out)
Definition at line 194 of file temporal-parser.cc.
                                                                          {
  int32_t cur = s;
  if ((str.length() < (cur + 1)) || !IsDecimalDigit(str[cur])) return 0;
  *out = ToInt(str[cur++]);
  while ((cur < str.length()) && ((cur - s) < 9) && IsDecimalDigit(str[cur])) {
    *out = 10 * (*out) + ToInt(str[cur++]);
  }
  *out *= kPowerOfTen[9 - (cur - s)];
  return cur - s;
}
References v8::internal::IsDecimalDigit(), kPowerOfTen, v8::base::Vector< T >::length(), and ToInt().
Referenced by ScanFraction().
ScanHour()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanHour (base::Vector< Char > str, int32_t s, int32_t * out)
The TemporalParser use two types of internal routine:
Scan routines: Follow the function signature below: template <typename Char> int32_t Scan$ProductionName(base::Vector<Char> str, int32_t s, R* out)
These routine scan the next item from position s in str and store the parsed result into out if the expected string is successfully scanned. It return the length of matched text from s or 0 to indicate no expected item matched.
Satisfy routines: Follow the function sigature below: template <typename Char> bool Satisfy$ProductionName(base::Vector<Char> str, R* r); It scan from the beginning of the str by calling Scan routines to put parsed result into r and return true if the entire str satisfy the production. It internally use Scan routines.
TODO(ftang) investigate refactoring to class before shipping Reference to RegExpParserImpl by encapsulating the cursor position and only manipulating the current character and position with Next(), Advance(), current(), etc
Definition at line 125 of file temporal-parser.cc.
                                                                {
  return ScanTwoDigitsExpectRange<Char>(str, s, 0, 23, out);
}
Referenced by ScanEtcGMTAsciiSignHour(), and ScanTimeZoneUTCOffsetName().
ScanMinuteSecond()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanMinuteSecond (base::Vector< Char > str, int32_t s, int32_t * out)
Definition at line 148 of file temporal-parser.cc.
                                                                        {
  return ScanTwoDigitsExpectRange<Char>(str, s, 0, 59, out);
}
Referenced by ScanTimeZoneUTCOffsetName().
ScanTemporalZonedDateTimeString()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanTemporalZonedDateTimeString (base::Vector< Char > str, int32_t s, ParsedISO8601Result * r)
Definition at line 1035 of file temporal-parser.cc.
                                                                {
  // Date
  int32_t cur = s;
  int32_t len = ScanDate(str, cur, r);
  if (len == 0) return 0;
  cur += len;
  // TimeSpecSeparator
  cur += ScanTimeSpecSeparator(str, cur, r);
  // TimeZoneNameRequired
  len = ScanTimeZoneNameRequired(str, cur, r);
  if (len == 0) return 0;
  cur += len;
  // Calendar
  cur += ScanCalendar(str, cur, r);
  return cur - s;
}
References ScanCalendar(), ScanDate(), ScanTimeSpecSeparator(), and ScanTimeZoneNameRequired().
ScanTimeFraction() [1/2]
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanTimeFraction (base::Vector< Char > str, int32_t s, int32_t * out)
Definition at line 221 of file temporal-parser.cc.
                                                                        {
  if ((str.length() < (s + 2)) || (!IsDecimalSeparator(str[s]))) return 0;
  int32_t len;
  if ((len = ScanTimeFractionalPart(str, s + 1, out)) == 0) return 0;
  return len + 1;
}
References IsDecimalSeparator(), and v8::base::Vector< T >::length().
ScanTimeFraction() [2/2]
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanTimeFraction (base::Vector< Char > str, int32_t s, ParsedISO8601Result * r)
Definition at line 229 of file temporal-parser.cc.
                                                 {
  return ScanTimeFraction(str, s, &(r->time_nanosecond));
}
References v8::internal::ParsedISO8601Result::time_nanosecond.
Referenced by ScanTimeSpec().
ScanTimeSecond()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanTimeSecond (base::Vector< Char > str, int32_t s, int32_t * out)
Definition at line 185 of file temporal-parser.cc.
                                                                      {
  return ScanTwoDigitsExpectRange<Char>(str, s, 0, 60, out);
}
Referenced by ScanTimeSpec().
ScanTimeSpec()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanTimeSpec (base::Vector< Char > str, int32_t s, ParsedISO8601Result * r)
Definition at line 241 of file temporal-parser.cc.
                                             {
  int32_t time_hour, time_minute, time_second;
  int32_t len;
  int32_t cur = s;
  if ((len = ScanTimeHour(str, cur, &time_hour)) == 0) return 0;
  cur += len;
  if ((cur + 1) > str.length()) {
    // TimeHour
    r->time_hour = time_hour;
    return cur - s;
  }
  if (str[cur] == ':') {
    cur++;
    if ((len = ScanTimeMinute(str, cur, &time_minute)) == 0) return 0;
    cur += len;
    if ((cur + 1) > str.length() || (str[cur] != ':')) {
      // TimeHour : TimeMinute
      r->time_hour = time_hour;
      r->time_minute = time_minute;
      return cur - s;
    }
    cur++;
    if ((len = ScanTimeSecond(str, cur, &time_second)) == 0) return 0;
  } else {
    if ((len = ScanTimeMinute(str, cur, &time_minute)) == 0) {
      // TimeHour
      r->time_hour = time_hour;
      return cur - s;
    }
    cur += len;
    if ((len = ScanTimeSecond(str, cur, &time_second)) == 0) {
      // TimeHour TimeMinute
      r->time_hour = time_hour;
      r->time_minute = time_minute;
      return cur - s;
    }
  }
  cur += len;
  len = ScanTimeFraction(str, cur, r);
  r->time_hour = time_hour;
  r->time_minute = time_minute;
  r->time_second = time_second;
  cur += len;
  return cur - s;
}
References v8::base::Vector< T >::length(), ScanTimeFraction(), ScanTimeSecond(), v8::internal::ParsedISO8601Result::time_hour, v8::internal::ParsedISO8601Result::time_minute, and v8::internal::ParsedISO8601Result::time_second.
Referenced by ScanCalendarTime_L1(), ScanTimeSpecSeparator(), and ScanTimeSpecWithOptionalTimeZoneNotAmbiguous().
ScanTimeSpecSeparator()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanTimeSpecSeparator (base::Vector< Char > str, int32_t s, ParsedISO8601Result * r)
Definition at line 291 of file temporal-parser.cc.
                                                      {
  if (!(((s + 1) < str.length()) && IsDateTimeSeparator(str[s]))) return 0;
  int32_t len = ScanTimeSpec(str, s + 1, r);
  return (len == 0) ? 0 : len + 1;
}
References IsDateTimeSeparator(), v8::base::Vector< T >::length(), and ScanTimeSpec().
Referenced by SCAN_EITHER_FORWARD(), ScanCalendarDateTimeTimeRequired(), ScanDateTime(), and ScanTemporalZonedDateTimeString().
ScanTimeSpecWithOptionalTimeZoneNotAmbiguous()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanTimeSpecWithOptionalTimeZoneNotAmbiguous (base::Vector< Char > str, int32_t s, ParsedISO8601Result * r)
Definition at line 818 of file temporal-parser.cc.
                                                                             {
  int32_t cur = s;
  int32_t len;
  if ((len = ScanTimeSpec(str, cur, r)) == 0) return 0;
  cur += len;
  // [TimeZone]
  len = ScanTimeZone(str, cur, r);
  cur += len;
  len = cur - s;
  // If it match ValidMonthDay, consider invalid.
  if (ScanValidMonthDay(str, s) == len) return 0;
  // If it match DateSpecYearMonth, consider invalid.
  ParsedISO8601Result tmp;
  if (ScanDateSpecYearMonth(str, s, &tmp) == len) return 0;
  return len;
}
References ScanDateSpecYearMonth(), ScanTimeSpec(), ScanTimeZone(), and ScanValidMonthDay().
Referenced by ScanCalendarTime_L2().
ScanTimeZone()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanTimeZone (base::Vector< Char > str, int32_t s, ParsedISO8601Result * r)
Definition at line 749 of file temporal-parser.cc.
                                             {
  int32_t cur = s;
  int32_t len;
  // TimeZoneUTCOffset [TimeZoneBracketedAnnotation]
  if ((len = ScanTimeZoneUTCOffset(str, cur, r)) > 0) {
    cur += len;
    // [TimeZoneBracketedAnnotation]
    len = ScanTimeZoneBracketedAnnotation(str, cur, r);
    cur += len;
    return cur - s;
  }
  // TimeZoneBracketedAnnotation
  return ScanTimeZoneBracketedAnnotation(str, cur, r);
}
References ScanTimeZoneBracketedAnnotation(), and ScanTimeZoneUTCOffset().
Referenced by ScanCalendarDateTimeTimeRequired(), ScanCalendarTime_L1(), ScanDateTime(), and ScanTimeSpecWithOptionalTimeZoneNotAmbiguous().
ScanTimeZoneBracketedAnnotation()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanTimeZoneBracketedAnnotation (base::Vector< Char > str, int32_t s, ParsedISO8601Result * r)
Definition at line 703 of file temporal-parser.cc.
                                                                {
  if ((str.length() < (s + 3)) || (str[s] != '[')) return 0;
  int32_t cur = s + 1;
  int32_t len = ScanTimeZoneIdentifier(str, cur, r);
  cur += len;
  if (len == 0 || str.length() < (cur + 1) || (str[cur] != ']')) {
    // Only ScanTimeZoneBracketedAnnotation know the post condition of
    // TimeZoneIdentifier is not matched so we need to reset here.
    r->tzi_name_start = 0;
    r->tzi_name_length = 0;
    return 0;
  }
  cur++;
  return cur - s;
}
References v8::base::Vector< T >::length(), ScanTimeZoneIdentifier(), v8::internal::ParsedISO8601Result::tzi_name_length, and v8::internal::ParsedISO8601Result::tzi_name_start.
Referenced by ScanTimeZone(), ScanTimeZoneNameRequired(), and ScanTimeZoneOffsetRequired().
ScanTimeZoneIANALegacyName()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanTimeZoneIANALegacyName (base::Vector< Char > str, int32_t s)
Definition at line 537 of file temporal-parser.cc.
                                                                    {
  int32_t cur = s;
  {
    constexpr int32_t len = 4;
    if (str.length() < cur + len) return 0;
    if (CompareCharsEqual(str.begin() + cur, "GMT0", len)) return len;
  }
  {
    constexpr int32_t len = 5;
    if (str.length() < cur + len) return 0;
    if (CompareCharsEqual(str.begin() + cur, "GMT+0", len) ||
        CompareCharsEqual(str.begin() + cur, "GMT-0", len)) {
      return len;
    }
  }
  {
    constexpr int32_t len = 7;
    if (str.length() < cur + len) return 0;
    if (CompareCharsEqual(str.begin() + cur, "EST5EDT", len) ||
        CompareCharsEqual(str.begin() + cur, "CST6CDT", len) ||
        CompareCharsEqual(str.begin() + cur, "MST7MDT", len) ||
        CompareCharsEqual(str.begin() + cur, "PST8PDT", len)) {
      return len;
    }
  }
  {
    constexpr int32_t len = 8;
    if (str.length() < cur + len) return 0;
    if (CompareCharsEqual(str.begin() + cur, "Etc/GMT0", len)) return len;
  }
  return 0;
}
References v8::base::Vector< T >::begin(), v8::internal::CompareCharsEqual(), and v8::base::Vector< T >::length().
Referenced by ScanTimeZoneIANAName().
ScanTimeZoneIANAName()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanTimeZoneIANAName (base::Vector< Char > str, int32_t s)
Definition at line 601 of file temporal-parser.cc.
                                                              {
  int32_t len;
  if ((len = ScanEtcGMTASCIISignUnpaddedHour(str, s)) > 0 ||
      (len = ScanTimeZoneIANALegacyName(str, s)) > 0) {
    return len;
  }
  int32_t cur = s;
  if ((len = ScanTimeZoneIANANameComponent(str, cur)) == 0) return 0;
  cur += len;
  while ((str.length() > (cur + 1)) && (str[cur] == '/')) {
    cur++;
    if ((len = ScanTimeZoneIANANameComponent(str, cur)) == 0) {
      return 0;
    }
    // TimeZoneIANANameComponent / TimeZoneIANAName
    cur += len;
  }
  return cur - s;
}
References v8::base::Vector< T >::length(), ScanEtcGMTASCIISignUnpaddedHour(), ScanTimeZoneIANALegacyName(), and ScanTimeZoneIANANameComponent().
Referenced by ScanTimeZoneIdentifier().
ScanTimeZoneIANANameComponent()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanTimeZoneIANANameComponent (base::Vector< Char > str, int32_t s)
Definition at line 516 of file temporal-parser.cc.
                                                                       {
  int32_t cur = s;
  if (str.length() < (cur + 1) || !IsTZLeadingChar(str[cur++])) return 0;
  while (((cur) < str.length()) && ((cur - s) < 14) && IsTZChar(str[cur])) {
    cur++;
  }
  if ((cur - s) == 1 && str[s] == '.') return 0;
  if ((cur - s) == 2 && str[s] == '.' && str[s + 1] == '.') return 0;
  return cur - s;
}
References IsTZChar(), IsTZLeadingChar(), and v8::base::Vector< T >::length().
Referenced by ScanTimeZoneIANAName().
ScanTimeZoneIdentifier()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanTimeZoneIdentifier (base::Vector< Char > str, int32_t s, ParsedISO8601Result * r)
Definition at line 991 of file temporal-parser.cc.
                                                       {
  int32_t len;
  int32_t cur = s;
  if ((len = ScanTimeZoneIANAName(str, cur)) > 0 ||
      (len = ScanTimeZoneUTCOffsetName(str, cur)) > 0) {
    cur += len;
    r->tzi_name_start = s;
    r->tzi_name_length = len;
    return cur - s;
  }
  return 0;
}
References ScanTimeZoneIANAName(), ScanTimeZoneUTCOffsetName(), v8::internal::ParsedISO8601Result::tzi_name_length, and v8::internal::ParsedISO8601Result::tzi_name_start.
Referenced by ScanTimeZoneBracketedAnnotation().
ScanTimeZoneNameRequired()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanTimeZoneNameRequired (base::Vector< Char > str, int32_t s, ParsedISO8601Result * r)
Definition at line 735 of file temporal-parser.cc.
                                                         {
  int32_t cur = s;
  cur += ScanTimeZoneUTCOffset(str, cur, r);
  int32_t len = ScanTimeZoneBracketedAnnotation(str, cur, r);
  if (len == 0) return 0;
  cur += len;
  return cur - s;
}
References ScanTimeZoneBracketedAnnotation(), and ScanTimeZoneUTCOffset().
Referenced by ScanTemporalZonedDateTimeString().
ScanTimeZoneNumericUTCOffset()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanTimeZoneNumericUTCOffset (base::Vector< Char > str, int32_t s, ParsedISO8601Result * r)
Definition at line 431 of file temporal-parser.cc.
                                                             {
  int32_t len, hour, minute, second, nanosecond;
  int32_t cur = s;
  if ((str.length() < (cur + 1)) || (!IsTimeZoneUTCOffsetSign(str[cur]))) {
    return 0;
  }
  int32_t sign = (CanonicalSign(str[cur++]) == '-') ? -1 : 1;
  if ((len = ScanTimeZoneUTCOffsetHour(str, cur, &hour)) == 0) return 0;
  cur += len;
  if ((cur + 1) > str.length()) {
    // TimeZoneUTCOffsetSign TimeZoneUTCOffsetHour
    r->tzuo_sign = sign;
    r->tzuo_hour = hour;
    r->offset_string_start = s;
    r->offset_string_length = cur - s;
    return cur - s;
  }
  if (str[cur] == ':') {
    cur++;
    if ((len = ScanTimeZoneUTCOffsetMinute(str, cur, &minute)) == 0) return 0;
    cur += len;
    if ((cur + 1) > str.length() || str[cur] != ':') {
      // TimeZoneUTCOffsetSign TimeZoneUTCOffsetHour : TimeZoneUTCOffsetMinute
      r->tzuo_sign = sign;
      r->tzuo_hour = hour;
      r->tzuo_minute = minute;
      r->offset_string_start = s;
      r->offset_string_length = cur - s;
      return cur - s;
    }
    cur++;
    if ((len = ScanTimeZoneUTCOffsetSecond(str, cur, &second)) == 0) return 0;
  } else {
    if ((len = ScanTimeZoneUTCOffsetMinute(str, cur, &minute)) == 0) {
      // TimeZoneUTCOffsetSign TimeZoneUTCOffsetHour
      r->tzuo_sign = sign;
      r->tzuo_hour = hour;
      r->offset_string_start = s;
      r->offset_string_length = cur - s;
      return cur - s;
    }
    cur += len;
    if ((len = ScanTimeZoneUTCOffsetSecond(str, cur, &second)) == 0) {
      // TimeZoneUTCOffsetSign TimeZoneUTCOffsetHour TimeZoneUTCOffsetMinute
      r->tzuo_sign = sign;
      r->tzuo_hour = hour;
      r->tzuo_minute = minute;
      r->offset_string_start = s;
      r->offset_string_length = cur - s;
      return cur - s;
    }
  }
  cur += len;
  len = ScanTimeZoneUTCOffsetFraction(str, cur, &nanosecond);
  r->tzuo_sign = sign;
  r->tzuo_hour = hour;
  r->tzuo_minute = minute;
  r->tzuo_second = second;
  if (len > 0) r->tzuo_nanosecond = nanosecond;
  r->offset_string_start = s;
  r->offset_string_length = cur + len - s;
  cur += len;
  return cur - s;
}
References CanonicalSign(), IsTimeZoneUTCOffsetSign(), v8::base::Vector< T >::length(), v8::internal::ParsedISO8601Result::offset_string_length, v8::internal::ParsedISO8601Result::offset_string_start, ScanTimeZoneUTCOffsetFraction(), v8::internal::sign, v8::internal::ParsedISO8601Result::tzuo_hour, v8::internal::ParsedISO8601Result::tzuo_minute, v8::internal::ParsedISO8601Result::tzuo_nanosecond, v8::internal::ParsedISO8601Result::tzuo_second, and v8::internal::ParsedISO8601Result::tzuo_sign.
Referenced by ScanTimeZoneUTCOffset().
ScanTimeZoneOffsetRequired()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanTimeZoneOffsetRequired (base::Vector< Char > str, int32_t s, ParsedISO8601Result * r)
Definition at line 723 of file temporal-parser.cc.
                                                           {
  int32_t cur = s;
  cur += ScanTimeZoneUTCOffset(str, cur, r);
  if (cur == s) return 0;
  cur += ScanTimeZoneBracketedAnnotation(str, cur, r);
  return cur - s;
}
References ScanTimeZoneBracketedAnnotation(), and ScanTimeZoneUTCOffset().
Referenced by SCAN_EITHER_FORWARD().
ScanTimeZoneUTCOffset()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanTimeZoneUTCOffset (base::Vector< Char > str, int32_t s, ParsedISO8601Result * r)
Definition at line 501 of file temporal-parser.cc.
                                                      {
  if (str.length() < (s + 1)) return 0;
  if (AsciiAlphaToLower(str[s]) == 'z') {
    // UTCDesignator
    r->utc_designator = true;
    return 1;
  }
  // TimeZoneNumericUTCOffset
  return ScanTimeZoneNumericUTCOffset(str, s, r);
}
References v8::internal::AsciiAlphaToLower(), v8::base::Vector< T >::length(), ScanTimeZoneNumericUTCOffset(), and v8::internal::ParsedISO8601Result::utc_designator.
Referenced by ScanTimeZone(), ScanTimeZoneNameRequired(), and ScanTimeZoneOffsetRequired().
ScanTimeZoneUTCOffsetFraction()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanTimeZoneUTCOffsetFraction (base::Vector< Char > str, int32_t s, int32_t * out)
Definition at line 411 of file temporal-parser.cc.
                                                    {
  if ((str.length() < (s + 2)) || (!IsDecimalSeparator(str[s]))) return 0;
  int32_t len;
  if ((len = ScanTimeZoneUTCOffsetFractionalPart(str, s + 1, out)) > 0) {
    return len + 1;
  }
  return 0;
}
References IsDecimalSeparator(), and v8::base::Vector< T >::length().
Referenced by ScanTimeZoneNumericUTCOffset().
ScanTimeZoneUTCOffsetName()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanTimeZoneUTCOffsetName (base::Vector< Char > str, int32_t s)
Definition at line 629 of file temporal-parser.cc.
                                                                   {
  int32_t cur = s;
  int32_t len;
  if ((str.length() < (s + 3)) || !IsSign(str[cur++])) return 0;
  int32_t hour, minute, second, fraction;
  if ((len = ScanHour(str, cur, &hour)) == 0) return 0;
  cur += len;
  if ((cur + 1) > str.length()) {
    // Sign Hour
    return cur - s;
  }
  if (str[cur] == ':') {
    // Sign Hour :
    cur++;
    if ((len = ScanMinuteSecond(str, cur, &minute)) == 0) return 0;
    cur += len;
    if ((cur + 1) > str.length() || (str[cur] != ':')) {
      // Sign Hour : MinuteSecond
      return cur - s;
    }
    cur++;
    // Sign Hour : MinuteSecond :
    if ((len = ScanMinuteSecond(str, cur, &second)) == 0) return 0;
    cur += len;
    len = ScanFraction(str, cur, &fraction);
    return cur + len - s;
  } else {
    if ((len = ScanMinuteSecond(str, cur, &minute)) == 0) {
      // Sign Hour
      return cur - s;
    }
    cur += len;
    if ((len = ScanMinuteSecond(str, cur, &second)) == 0) {
      // Sign Hour MinuteSecond
      return cur - s;
    }
    cur += len;
    len = ScanFraction(str, cur, &fraction);
    // Sign Hour MinuteSecond MinuteSecond [Fraction]
    cur += len;
    return cur - s;
  }
}
References IsSign(), v8::base::Vector< T >::length(), ScanFraction(), ScanHour(), and ScanMinuteSecond().
Referenced by ScanTimeZoneIdentifier().
ScanTwoDigitsExpectRange()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanTwoDigitsExpectRange (base::Vector< Char > str, int32_t s, int32_t min, int32_t max, int32_t * out)
Definition at line 79 of file temporal-parser.cc.
                                                            {
  return HasTwoDigits<Char>(str, s, out) && base::IsInRange(*out, min, max) ? 2
                                                                            : 0;
}
Referenced by ScanValidMonthDay().
ScanTwoDigitsExpectValue()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanTwoDigitsExpectValue (base::Vector< Char > str, int32_t s, int32_t expected, int32_t * out)
Definition at line 71 of file temporal-parser.cc.
                                                                 {
  return HasTwoDigits<Char>(str, s, out) && (*out == expected) ? 2 : 0;
}
Referenced by ScanValidMonthDay().
ScanTwoDigitsExpectZeroOrRange()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanTwoDigitsExpectZeroOrRange (base::Vector< Char > str, int32_t s, int32_t min, int32_t max, int32_t * out)
Definition at line 88 of file temporal-parser.cc.
                                                                               {
  return HasTwoDigits<Char>(str, s, out) &&
                 (*out == 0 || base::IsInRange(*out, min, max))
             ? 2
             : 0;
}
ScanUnpaddedHour()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanUnpaddedHour (base::Vector< Char > str, int32_t s)
Definition at line 137 of file temporal-parser.cc.
                                                          {
  int32_t dummy;
  int32_t len = ScanTwoDigitsExpectRange<Char>(str, s, 10, 23, &dummy);
  if (len > 0) return len;
  if (str.length() >= (s + 1) && IsDecimalDigit(str[s])) return 1;
  return 0;
}
References v8::internal::IsDecimalDigit(), and v8::base::Vector< T >::length().
Referenced by ScanEtcGMTASCIISignUnpaddedHour().
ScanValidMonthDay()
template<typename Char >
int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ScanValidMonthDay (base::Vector< Char > str, int32_t s)
Definition at line 772 of file temporal-parser.cc.
                                                           {
  int32_t len;
  int32_t cur = s;
  int32_t date_month;
  if ((len = ScanDateMonth(str, cur, &date_month)) > 0) {
    cur += len;
    if (str.length() >= (cur + 1)) {
      if (str[cur] == '-') cur++;
      int32_t day_of_month;
      if ((len = ScanTwoDigitsExpectRange(str, cur, 1, 30, &day_of_month)) >
          0) {
        cur += len;
        // 0 NonZeroDigit
        // 1 DecimalDigit
        // 2 DecimalDigit
        // 30 but not one of 0230 or 02-30
        if (date_month != 2 || day_of_month != 30) {
          return cur - s;
        }
      }
    }
  }
  // Reset cur
  cur = s;
  // DateMonthWithThirtyOneDays [-] 31
  if ((len = ScanDateMonthWithThirtyOneDays(str, cur)) > 0) {
    cur += len;
    if (str.length() >= (cur + 1)) {
      if (str[cur] == '-') cur++;
      int32_t dummy;
      if ((len = ScanTwoDigitsExpectValue(str, cur, 31, &dummy)) > 0) {
        cur += len;
        return cur - s;
      }
    }
  }
  return 0;
}
References v8::base::Vector< T >::length(), ScanDateMonth(), ScanDateMonthWithThirtyOneDays(), ScanTwoDigitsExpectRange(), and ScanTwoDigitsExpectValue().
Referenced by ScanTimeSpecWithOptionalTimeZoneNotAmbiguous().
ToInt()
constexpr int32_t v8::internal::anonymous_namespace{temporal-parser.cc}::ToInt (base::uc32 c) [inline], [constexpr]
Definition at line 55 of file temporal-parser.cc.
{ return c - '0'; }
Referenced by v8::internal::JSMapIterator::CurrentValue(), v8::internal::AccessorAssembler::GenerateLoadIC_NoFeedback(), v8::internal::GetLength(), v8::internal::OrderedHashTableIterator< Derived, TableType >::HasMore(), HasTwoDigits(), v8::internal::KeyedStoreGenericAssembler::KeyedStoreGeneric(), v8::internal::anonymous_namespace{builtins-riscv.cc}::OnStackReplacement(), v8::internal::compiler::LiveRangeBuilder::ProcessLoopHeader(), SATISIFY_EITHER(), ScanDateExtendedYear(), ScanDateFourDigitYear(), ScanFractionalPart(), v8::internal::KeyedStoreGenericAssembler::StoreIC_NoFeedback(), v8::internal::KeyedStoreGenericAssembler::StoreProperty(), v8::internal::FeedbackVector::ToSlot(), v8::internal::OrderedHashTableIterator< Derived, TableType >::Transition(), v8::internal::compiler::InstructionSelector::VisitNode(), and v8::internal::JSObject::WriteToField().
Variable Documentation
CalendarDateTime
v8::internal::anonymous_namespace{temporal-parser.cc}::CalendarDateTime
Definition at line 1131 of file temporal-parser.cc.
DateSpecYearMonth
v8::internal::anonymous_namespace{temporal-parser.cc}::DateSpecYearMonth
Definition at line 1131 of file temporal-parser.cc.
kPowerOfTen
constexpr int v8::internal::anonymous_namespace{temporal-parser.cc}::kPowerOfTen[] [constexpr]
Initial value:
= {1, 10, 100, 1000, 10000,
                               100000, 1000000, 10000000, 100000000}
Definition at line 189 of file temporal-parser.cc.
Referenced by ScanFractionalPart().