v8::internal::anonymous_namespace{serializer.cc} Namespace Reference
Functions
const char * ToString (SnapshotSpace space)
SnapshotSpace GetSnapshotSpace (Tagged< HeapObject > object)
void OutputRawWithCustomField (SnapshotByteSink *sink, Address object_start, int written_so_far, int bytes_to_write, int field_offset, int field_size, const uint8_t *field_value)
Function Documentation
GetSnapshotSpace()
SnapshotSpace v8::internal::anonymous_namespace{serializer.cc}::GetSnapshotSpace (Tagged< HeapObject > object)
Definition at line 868 of file serializer.cc.
                                                          {
  if (ReadOnlyHeap::Contains(object)) {
    return SnapshotSpace::kReadOnlyHeap;
  } else {
    AllocationSpace heap_space =
        MutablePageMetadata::FromHeapObject(object)->owner_identity();
    // Large code objects are not supported and cannot be expressed by
    // SnapshotSpace.
    DCHECK_NE(heap_space, CODE_LO_SPACE);
    switch (heap_space) {
      case OLD_SPACE:
      // Young generation objects are tenured, as objects that have survived
      // until snapshot building probably deserve to be considered 'old'.
      case NEW_SPACE:
      // Large objects (young and old) are encoded as simply 'old' snapshot
      // objects, as "normal" objects vs large objects is a heap implementation
      // detail and isn't relevant to the snapshot.
      case NEW_LO_SPACE:
      case LO_SPACE:
      // Shared objects are currently encoded as 'old' snapshot objects. This
      // basically duplicates shared heap objects for each isolate again.
      case SHARED_SPACE:
      case SHARED_LO_SPACE:
        return SnapshotSpace::kOld;
      case CODE_SPACE:
        return SnapshotSpace::kCode;
      case TRUSTED_SPACE:
      case TRUSTED_LO_SPACE:
        return SnapshotSpace::kTrusted;
      // Shared objects are currently encoded as 'trusteds' snapshot objects.
      // This basically duplicates shared trusted heap objects for each isolate
      // again.
      case SHARED_TRUSTED_SPACE:
      case SHARED_TRUSTED_LO_SPACE:
        return SnapshotSpace::kTrusted;
      case CODE_LO_SPACE:
      case RO_SPACE:
        UNREACHABLE();
    }
  }
}
References v8::internal::CODE_LO_SPACE, v8::internal::CODE_SPACE, v8::internal::ReadOnlyHeap::Contains(), DCHECK_NE, v8::internal::MutablePageMetadata::FromHeapObject(), v8::internal::kCode, v8::internal::kOld, v8::internal::kReadOnlyHeap, v8::internal::kTrusted, v8::internal::LO_SPACE, v8::internal::NEW_LO_SPACE, v8::internal::NEW_SPACE, v8::internal::OLD_SPACE, v8::internal::MutablePageMetadata::owner_identity(), v8::internal::RO_SPACE, v8::internal::SHARED_LO_SPACE, v8::internal::SHARED_SPACE, v8::internal::SHARED_TRUSTED_LO_SPACE, v8::internal::SHARED_TRUSTED_SPACE, v8::internal::TRUSTED_LO_SPACE, v8::internal::TRUSTED_SPACE, and v8::internal::UNREACHABLE().
Referenced by v8::internal::Serializer::ObjectSerializer::SerializeObject().
OutputRawWithCustomField()
void v8::internal::anonymous_namespace{serializer.cc}::OutputRawWithCustomField (SnapshotByteSink * sink, Address object_start, int written_so_far, int bytes_to_write, int field_offset, int field_size, const uint8_t * field_value)
Definition at line 1340 of file serializer.cc.
                                                          {
  int offset = field_offset - written_so_far;
  if (0 <= offset && offset < bytes_to_write) {
    DCHECK_GE(bytes_to_write, offset + field_size);
    sink->PutRaw(reinterpret_cast<uint8_t*>(object_start + written_so_far),
                 offset, "Bytes");
    sink->PutRaw(field_value, field_size, "Bytes");
    written_so_far += offset + field_size;
    bytes_to_write -= offset + field_size;
    sink->PutRaw(reinterpret_cast<uint8_t*>(object_start + written_so_far),
                 bytes_to_write, "Bytes");
  } else {
    sink->PutRaw(reinterpret_cast<uint8_t*>(object_start + written_so_far),
                 bytes_to_write, "Bytes");
  }
}
References DCHECK_GE, and v8::internal::SnapshotByteSink::PutRaw().
Referenced by v8::internal::Serializer::ObjectSerializer::OutputRawData().
ToString()
const char* v8::internal::anonymous_namespace{serializer.cc}::ToString (SnapshotSpace space)
Definition at line 90 of file serializer.cc.
                                          {
  switch (space) {
    case SnapshotSpace::kReadOnlyHeap:
      return "ReadOnlyHeap";
    case SnapshotSpace::kOld:
      return "Old";
    case SnapshotSpace::kCode:
      return "Code";
    case SnapshotSpace::kTrusted:
      return "Trusted";
  }
}
References v8::internal::kCode, v8::internal::kOld, v8::internal::kReadOnlyHeap, v8::internal::kTrusted, and space.