v8::internal::torque::anonymous_namespace{csa-generator.cc} Namespace Reference
Functions
std::string GetBitFieldSpecialization (const Type *container, const BitField &field)
Function Documentation
GetBitFieldSpecialization()
std::string v8::internal::torque::anonymous_namespace{csa-generator.cc}::GetBitFieldSpecialization (const Type * container, const BitField & field)
Definition at line 949 of file csa-generator.cc.
                                                             {
  auto smi_tagged_type =
      Type::MatchUnaryGeneric(container, TypeOracle::GetSmiTaggedGeneric());
  std::string container_type = smi_tagged_type
                                   ? "uintptr_t"
                                   : container->GetConstexprGeneratedTypeName();
  int offset = smi_tagged_type
                   ? field.offset + TargetArchitecture::SmiTagAndShiftSize()
                   : field.offset;
  std::stringstream stream;
  stream << "base::BitField<"
         << field.name_and_type.type->GetConstexprGeneratedTypeName() << ", "
         << offset << ", " << field.num_bits << ", " << container_type << ">";
  return stream.str();
}
References v8::internal::torque::Type::GetConstexprGeneratedTypeName(), v8::internal::torque::TypeOracle::GetSmiTaggedGeneric(), v8::internal::torque::Type::MatchUnaryGeneric(), v8::internal::torque::BitField::name_and_type, v8::internal::torque::BitField::num_bits, v8::internal::torque::BitField::offset, v8::internal::torque::TargetArchitecture::SmiTagAndShiftSize(), v8::internal::string, and v8::internal::torque::NameAndType::type.