v8::internal::math Namespace Reference
Functions
double pow (double x, double y)
Function Documentation
pow()
V8_EXPORT_PRIVATE double v8::internal::math::pow (double x, double y)
Definition at line 14 of file ieee754.cc.
                               {
  if (v8_flags.use_std_math_pow) {
    if (std::isnan(y)) {
      // 1. If exponent is NaN, return NaN.
      return std::numeric_limits<double>::quiet_NaN();
    }
    if (std::isinf(y) && (x == 1 || x == -1)) {
      // 9. If exponent is +∞𝔽, then
      // b. If abs(ℝ(base)) = 1, return NaN.
      // and
      // 10. If exponent is -∞𝔽, then
      // b. If abs(ℝ(base)) = 1, return NaN.
      return std::numeric_limits<double>::quiet_NaN();
    }
    if (std::isnan(x)) {
      // std::pow distinguishes between quiet and signaling NaN; JS doesn't.
      x = std::numeric_limits<double>::quiet_NaN();
    }
    // The following special cases just exist to match the optimizing compilers'
    // behavior, which avoid calls to `pow` in those cases.
    if (y == 2) {
      // x ** 2 ==> x * x
      return x * x;
    } else if (y == 0.5) {
      // x ** 0.5 ==> sqrt(x), except if x is -Infinity
      if (std::isinf(x)) {
        return std::numeric_limits<double>::infinity();
      } else {
        // Note the +0 so that we get +0 for -0**0.5 rather than -0.
        return std::sqrt(x + 0);
      }
    }
    return std::pow(x, y);
  }
  return base::ieee754::legacy::pow(x, y);
}
References v8::base::ieee754::legacy::pow(), v8::internal::v8_flags, and v8::internal::y.
Referenced by v8::internal::wasm::float64_pow_wrapper(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::FloatBinop(), v8::internal::compiler::MachineOperatorReducer::Reduce(), v8::internal::Parser::ShortcutLiteralBinaryExpression(), and v8::internal::maglev::MaglevGraphBuilder::TryFoldFloat64BinaryOperationForToNumber().