v8::internal::compiler::anonymous_namespace{instruction-selector.cc} Namespace Reference
Functions
bool is_exclusive_user_of (const Graph *graph, OpIndex user, OpIndex value)
InstructionOperand OperandForDeopt (Isolate *isolate, OperandGenerator *g, OpIndex input, FrameStateInputKind kind, MachineRepresentation rep)
bool increment_effect_level_for_node (InstructionSelector *selector, OpIndex node)
LinkageLocation ExceptionLocation ()
constexpr InstructionCode EncodeCallDescriptorFlags (InstructionCode opcode, CallDescriptor::Flags flags)
FrameStateDescriptor * GetFrameStateDescriptorInternal (Zone *zone, Graph *graph, const FrameStateOp &state)
Variables
constexpr EffectDimensions kTurboshaftEffectLevelMask
Function Documentation
EncodeCallDescriptorFlags()
constexpr InstructionCode v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::EncodeCallDescriptorFlags (InstructionCode opcode, CallDescriptor::Flags flags) [constexpr]
Definition at line 1981 of file instruction-selector.cc.
                                                       {
  // Note: Not all bits of `flags` are preserved.
  static_assert(CallDescriptor::kFlagsBitsEncodedInInstructionCode ==
                MiscField::kSize);
  DCHECK(Instruction::IsCallWithDescriptorFlags(opcode));
  return opcode | MiscField::encode(flags & MiscField::kMax);
}
References v8::internal::DCHECK(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::flags, v8::internal::compiler::Instruction::IsCallWithDescriptorFlags(), v8::internal::compiler::CallDescriptor::kFlagsBitsEncodedInInstructionCode, v8::base::BitField< T, shift, size, U >::kMax, and v8::base::BitField< T, shift, size, U >::kSize.
Referenced by v8::internal::compiler::InstructionSelector::VisitCall(), and v8::internal::compiler::InstructionSelector::VisitTailCall().
ExceptionLocation()
LinkageLocation v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::ExceptionLocation ()
Definition at line 1976 of file instruction-selector.cc.
                                    {
  return LinkageLocation::ForRegister(kReturnRegister0.code(),
                                      MachineType::TaggedPointer());
}
References v8::internal::LinkageLocation::ForRegister(), v8::internal::kReturnRegister0, and v8::internal::MachineType::TaggedPointer().
Referenced by v8::internal::compiler::InstructionSelector::VisitIfException().
GetFrameStateDescriptorInternal()
FrameStateDescriptor* v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::GetFrameStateDescriptorInternal (Zone * zone, Graph * graph, const FrameStateOp & state)
Definition at line 3936 of file instruction-selector.cc.
                                                         {
  const FrameStateInfo& state_info = state.data->frame_state_info;
  uint16_t parameters = state_info.parameter_count();
  uint16_t max_arguments = state_info.max_arguments();
  int locals = state_info.local_count();
  int stack = state_info.stack_count();
  FrameStateDescriptor* outer_state = nullptr;
  if (state.inlined) {
    outer_state = GetFrameStateDescriptorInternal(
        zone, graph,
        graph->Get(state.parent_frame_state()).template Cast<FrameStateOp>());
  }
#if V8_ENABLE_WEBASSEMBLY
  if (state_info.type() == FrameStateType::kJSToWasmBuiltinContinuation) {
    auto function_info = static_cast<const JSToWasmFrameStateFunctionInfo*>(
        state_info.function_info());
    return zone->New<JSToWasmFrameStateDescriptor>(
        zone, state_info.type(), state_info.bailout_id(),
        state_info.state_combine(), parameters, locals, stack,
        state_info.shared_info(), outer_state, function_info->signature());
  }
#endif // V8_ENABLE_WEBASSEMBLY
  return zone->New<FrameStateDescriptor>(
      zone, state_info.type(), state_info.bailout_id(),
      state_info.state_combine(), parameters, max_arguments, locals, stack,
      state_info.shared_info(), state_info.bytecode_array(), outer_state,
      state_info.function_info()->wasm_liftoff_frame_size(),
      state_info.function_info()->wasm_function_index());
}
References v8::internal::compiler::FrameStateInfo::bailout_id(), v8::internal::compiler::FrameStateInfo::bytecode_array(), v8::internal::compiler::turboshaft::FrameStateOp::data, v8::internal::compiler::turboshaft::FrameStateData::frame_state_info, v8::internal::compiler::FrameStateInfo::function_info(), graph(), v8::internal::compiler::turboshaft::FrameStateOp::inlined, v8::internal::compiler::FrameStateInfo::local_count(), v8::internal::compiler::FrameStateInfo::max_arguments(), v8::internal::Zone::New(), v8::internal::compiler::FrameStateInfo::parameter_count(), v8::internal::compiler::turboshaft::FrameStateOp::parent_frame_state(), v8::internal::compiler::FrameStateInfo::shared_info(), v8::internal::stack, v8::internal::compiler::FrameStateInfo::stack_count(), v8::internal::compiler::FrameStateInfo::state_combine(), v8::internal::compiler::FrameStateInfo::type(), v8::internal::compiler::FrameStateFunctionInfo::wasm_function_index(), and v8::internal::compiler::FrameStateFunctionInfo::wasm_liftoff_frame_size().
Referenced by v8::internal::compiler::InstructionSelector::GetFrameStateDescriptor().
increment_effect_level_for_node()
bool v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::increment_effect_level_for_node (InstructionSelector * selector, OpIndex node)
Definition at line 1419 of file instruction-selector.cc.
                                                   {
  // We need to increment the effect level if the operation consumes any of the
  // dimensions of the {kTurboshaftEffectLevelMask}.
  const Operation& op = selector->Get(node);
  if (op.Is<RetainOp>()) {
    // Retain has CanWrite effect so that it's not reordered before the last
    // read it protects, but it shouldn't increment the effect level, since
    // doing a Load(x) after a Retain(x) is safe as long as there is not call
    // (or something that can trigger GC) in between Retain(x) and Load(x), and
    // if there were, then this call would increment the effect level, which
    // would prevent covering in the ISEL.
    return false;
  }
  return (op.Effects().consumes.bits() & kTurboshaftEffectLevelMask.bits()) !=
         0;
}
References v8::internal::compiler::turboshaft::EffectDimensions::bits(), v8::internal::compiler::turboshaft::OpEffects::consumes, v8::internal::compiler::turboshaft::Operation::Effects(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::Is(), and kTurboshaftEffectLevelMask.
Referenced by v8::internal::compiler::InstructionSelector::VisitBlock().
is_exclusive_user_of()
bool v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::is_exclusive_user_of (const Graph * graph, OpIndex user, OpIndex value)
Definition at line 319 of file instruction-selector.cc.
                                                                           {
  DCHECK(user.valid());
  DCHECK(value.valid());
  const Operation& value_op = graph->Get(value);
  const Operation& user_op = graph->Get(user);
  size_t use_count = base::count_if(
      user_op.inputs(), [value](OpIndex input) { return input == value; });
  if (V8_UNLIKELY(use_count == 0)) {
    // We have a special case here:
    //
    // value
    // |
    // TruncateWord64ToWord32
    // |
    // user
    //
    // If emitting user performs the truncation implicitly, we end up calling
    // CanCover with value and user such that user might have no (direct) uses
    // of value. There are cases of other unnecessary operations that can lead
    // to the same situation (e.g. bitwise and, ...). In this case, we still
    // cover if value has only a single use and this is one of the direct
    // inputs of user, which also only has a single use (in user).
    // TODO(nicohartmann@): We might generalize this further if we see use
    // cases.
    if (!value_op.saturated_use_count.IsOne()) return false;
    for (auto input : user_op.inputs()) {
      const Operation& input_op = graph->Get(input);
      const size_t indirect_use_count = base::count_if(
          input_op.inputs(), [value](OpIndex input) { return input == value; });
      if (indirect_use_count > 0) {
        return input_op.saturated_use_count.IsOne();
      }
    }
    return false;
  }
  if (value_op.Is<ProjectionOp>()) {
    // Projections always have a Tuple use, but it shouldn't count as a use as
    // far as is_exclusive_user_of is concerned, since no instructions are
    // emitted for the TupleOp, which is just a Turboshaft "meta operation".
    // We thus increase the use_count by 1, to attribute the TupleOp use to
    // the current operation.
    use_count++;
  }
  DCHECK_LE(use_count, graph->Get(value).saturated_use_count.Get());
  return (value_op.saturated_use_count.Get() == use_count) &&
         !value_op.saturated_use_count.IsSaturated();
}
References v8::base::count_if(), v8::internal::DCHECK(), DCHECK_LE, v8::internal::compiler::turboshaft::SaturatedUint8::Get(), graph(), v8::internal::compiler::turboshaft::Operation::inputs(), v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::compiler::turboshaft::SaturatedUint8::IsOne(), v8::internal::compiler::turboshaft::SaturatedUint8::IsSaturated(), v8::internal::compiler::turboshaft::Operation::saturated_use_count, V8_UNLIKELY, v8::internal::compiler::turboshaft::OpIndex::valid(), and v8::internal::value.
Referenced by v8::internal::compiler::InstructionSelector::CanCover().
OperandForDeopt()
InstructionOperand v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::OperandForDeopt (Isolate * isolate, OperandGenerator * g, OpIndex input, FrameStateInputKind kind, MachineRepresentation rep)
Definition at line 624 of file instruction-selector.cc.
                                                              {
  if (rep == MachineRepresentation::kNone) {
    return g->TempImmediate(FrameStateDescriptor::kImpossibleValue);
  }
  const Operation& op = g->turboshaft_graph()->Get(input);
  if (const ConstantOp* constant = op.TryCast<ConstantOp>()) {
    using Kind = ConstantOp::Kind;
    switch (constant->kind) {
      case Kind::kWord32:
      case Kind::kWord64:
      case Kind::kSmi:
      case Kind::kFloat32:
      case Kind::kFloat64:
        return g->UseImmediate(input);
      case Kind::kNumber:
        if (rep == MachineRepresentation::kWord32) {
          const double d = constant->number().get_scalar();
          Tagged<Smi> smi = Smi::FromInt(static_cast<int32_t>(d));
          CHECK_EQ(smi.value(), d);
          return g->UseImmediate(static_cast<int32_t>(smi.ptr()));
        }
        return g->UseImmediate(input);
      case Kind::kHeapObject:
      case Kind::kCompressedHeapObject:
      case Kind::kTrustedHeapObject: {
        if (!CanBeTaggedOrCompressedPointer(rep)) {
          // If we have inconsistent static and dynamic types, e.g. if we
          // smi-check a string, we can get here with a heap object that
          // says it is a smi. In that case, we return an invalid instruction
          // operand, which will be interpreted as an optimized-out value.
          // TODO(jarin) Ideally, we should turn the current instruction
          // into an abort (we should never execute it).
          return InstructionOperand();
        }
        Handle<HeapObject> object = constant->handle();
        RootIndex root_index;
        if (isolate->roots_table().IsRootHandle(object, &root_index) &&
            root_index == RootIndex::kOptimizedOut) {
          // For an optimized-out object we return an invalid instruction
          // operand, so that we take the fast path for optimized-out values.
          return InstructionOperand();
        }
        return g->UseImmediate(input);
      }
      default:
        UNIMPLEMENTED();
    }
  } else if (const TaggedBitcastOp* bitcast =
                 op.TryCast<Opmask::kTaggedBitcastSmi>()) {
    const Operation& bitcast_input = g->Get(bitcast->input());
    if (const ConstantOp* cst =
            bitcast_input.TryCast<Opmask::kWord32Constant>()) {
      if constexpr (Is64()) {
        return g->UseImmediate64(cst->word32());
      } else {
        return g->UseImmediate(cst->word32());
      }
    } else if (Is64() && bitcast_input.Is<Opmask::kWord64Constant>()) {
      if (rep == MachineRepresentation::kWord32) {
        return g->UseImmediate(bitcast_input.Cast<ConstantOp>().word32());
      } else {
        return g->UseImmediate64(bitcast_input.Cast<ConstantOp>().word64());
      }
    }
  }
  switch (kind) {
    case FrameStateInputKind::kStackSlot:
      return g->UseUniqueSlot(input);
    case FrameStateInputKind::kAny:
      // Currently deopts "wrap" other operations, so the deopt's inputs
      // are potentially needed until the end of the deoptimising code.
      return g->UseAnyAtEnd(input);
  }
}
References v8::internal::CanBeTaggedOrCompressedPointer(), v8::internal::compiler::turboshaft::Operation::Cast(), CHECK_EQ, v8::internal::Smi::FromInt(), v8::internal::compiler::turboshaft::Graph::Get(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::Is64(), v8::internal::RootsTable::IsRootHandle(), v8::internal::compiler::kAny, v8::internal::compiler::FrameStateDescriptor::kImpossibleValue, v8::internal::kNone, v8::internal::compiler::kSmi, v8::internal::compiler::kStackSlot, v8::internal::kWord32, v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), v8::internal::Isolate::roots_table(), v8::internal::compiler::OperandGenerator::TempImmediate(), v8::internal::compiler::turboshaft::Operation::TryCast(), v8::internal::compiler::OperandGenerator::turboshaft_graph(), v8::internal::compiler::UNIMPLEMENTED(), v8::internal::compiler::OperandGenerator::UseAnyAtEnd(), v8::internal::compiler::OperandGenerator::UseImmediate(), v8::internal::compiler::OperandGenerator::UseImmediate64(), v8::internal::compiler::OperandGenerator::UseUniqueSlot(), v8::internal::Tagged< Smi >::value(), v8::internal::compiler::turboshaft::ConstantOp::word32(), and v8::internal::compiler::turboshaft::ConstantOp::word64().
Referenced by v8::internal::compiler::AddOperandToStateValueDescriptor().
Variable Documentation
kTurboshaftEffectLevelMask
constexpr EffectDimensions v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::kTurboshaftEffectLevelMask [constexpr]
Initial value:
=
    OpEffects().CanReadMemory().produces
Definition at line 46 of file instruction-selector.cc.
Referenced by increment_effect_level_for_node().