v8::internal::baseline Namespace Reference
Namespaces
 anonymous_namespace{baseline-compiler.cc}
 detail
Classes
class BaselineAssembler
class EnsureAccumulatorPreservedScope
class BaselineCompilerTask
class BaselineBatchCompilerJob
class ConcurrentBaselineCompiler
class BaselineBatchCompiler
class BytecodeOffsetTableBuilder
class BaselineCompiler
class SaveAccumulatorScope
class BytecodeOffsetIterator
Functions
static bool CanCompileWithConcurrentBaseline (Tagged< SharedFunctionInfo > shared, Isolate *isolate)
template<int width = 64>
static void JumpIfHelper (MacroAssembler *assm, Condition cc, Register lhs, Register rhs, Label *target)
template<int width = 64>
static void JumpIfHelper (MacroAssembler *assm, Condition cc, Register lhs, Register rhs, Label *target)
Variables
constexpr BuiltinCallJumpMode kFallbackBuiltinCallJumpModeForBaseline
constexpr static int stack_bias = 0
Function Documentation
CanCompileWithConcurrentBaseline()
static bool v8::internal::baseline::CanCompileWithConcurrentBaseline (Tagged< SharedFunctionInfo > shared, Isolate * isolate) [static]
Definition at line 26 of file baseline-batch-compiler.cc.
                                                               {
  return !shared->HasBaselineCode() && CanCompileWithBaseline(isolate, shared);
}
References v8::internal::CanCompileWithBaseline().
Referenced by v8::internal::baseline::BaselineBatchCompilerJob::BaselineBatchCompilerJob(), and v8::internal::baseline::BaselineCompilerTask::Install().
JumpIfHelper() [1/2]
template<int width = 64>
static void v8::internal::baseline::JumpIfHelper (MacroAssembler * assm, Condition cc, Register lhs, Register rhs, Label * target) [static]
Definition at line 55 of file baseline-assembler-ppc-inl.h.
                                                      {
  static_assert(width == 64 || width == 32,
                "only support 64 and 32 bit compare");
  if (width == 64) {
    if (is_signed(cc)) {
      __ CmpS64(lhs, rhs);
    } else {
      __ CmpU64(lhs, rhs);
    }
  } else {
    if (is_signed(cc)) {
      __ CmpS32(lhs, rhs);
    } else {
      __ CmpU32(lhs, rhs);
    }
  }
  __ b(to_condition(cc), target);
}
References __, v8::internal::cc, v8::internal::is_signed(), and v8::internal::to_condition().
JumpIfHelper() [2/2]
template<int width = 64>
static void v8::internal::baseline::JumpIfHelper (MacroAssembler * assm, Condition cc, Register lhs, Register rhs, Label * target) [static]
Definition at line 54 of file baseline-assembler-s390-inl.h.
                                                      {
  static_assert(width == 64 || width == 32,
                "only support 64 and 32 bit compare");
  if (width == 64) {
    if (is_signed(cc)) {
      __ CmpS64(lhs, rhs);
    } else {
      __ CmpU64(lhs, rhs);
    }
  } else {
    if (is_signed(cc)) {
      __ CmpS32(lhs, rhs);
    } else {
      __ CmpU32(lhs, rhs);
    }
  }
  __ b(to_condition(cc), target);
}
References __, v8::internal::cc, v8::internal::is_signed(), and v8::internal::to_condition().
Variable Documentation
kFallbackBuiltinCallJumpModeForBaseline
constexpr BuiltinCallJumpMode v8::internal::baseline::kFallbackBuiltinCallJumpModeForBaseline [constexpr]
Initial value:
=
    BuiltinCallJumpMode::kIndirect
Definition at line 19 of file baseline-compiler-arm-inl.h.
Referenced by v8::internal::baseline::anonymous_namespace{baseline-compiler.cc}::BaselineAssemblerOptions().
stack_bias
constexpr static int v8::internal::baseline::stack_bias = 0 [static], [constexpr]
Definition at line 219 of file baseline-assembler-s390-inl.h.