v8::internal::anonymous_namespace{js-locale.cc} Namespace Reference
Classes
struct OptionData
struct ValueAndType
Functions
Maybe< bool > InsertOptionsIntoLocale (Isolate *isolate, DirectHandle< JSReceiver > options, icu::LocaleBuilder *builder)
DirectHandle< Object > UnicodeKeywordValue (Isolate *isolate, DirectHandle< JSLocale > locale, const char *key)
bool IsCheckRange (std::string_view str, size_t min, size_t max, bool(range_check_func)(char))
bool IsAlpha (std::string_view str, size_t min, size_t max)
bool IsDigit (std::string_view str, size_t min, size_t max)
bool IsAlphanum (std::string_view str, size_t min, size_t max)
bool IsUnicodeLanguageSubtag (std::string_view value)
bool IsUnicodeScriptSubtag (std::string_view value)
bool IsUnicodeRegionSubtag (std::string_view value)
bool IsDigitAlphanum3 (std::string_view value)
bool IsUnicodeVariantSubtag (std::string_view value)
bool IsExtensionSingleton (std::string_view value)
int32_t weekdayFromEDaysOfWeek (icu::Calendar::EDaysOfWeek eDaysOfWeek)
Maybe< bool > ApplyOptionsToTag (Isolate *isolate, DirectHandle< String > tag, DirectHandle< JSReceiver > options, icu::LocaleBuilder *builder)
MaybeDirectHandle< JSLocale > Construct (Isolate *isolate, const icu::Locale &icu_locale)
MaybeDirectHandle< JSArray > CalendarsForLocale (Isolate *isolate, const icu::Locale &icu_locale, bool commonly_used, bool sort)
Function Documentation
ApplyOptionsToTag()
Maybe<bool> v8::internal::anonymous_namespace{js-locale.cc}::ApplyOptionsToTag (Isolate * isolate, DirectHandle< String > tag, DirectHandle< JSReceiver > options, icu::LocaleBuilder * builder)
Definition at line 272 of file js-locale.cc.
                                                         {
  v8::Isolate* v8_isolate = reinterpret_cast<v8::Isolate*>(isolate);
  if (tag->length() == 0) {
    THROW_NEW_ERROR_RETURN_VALUE(
        isolate, NewRangeError(MessageTemplate::kLocaleNotEmpty),
        Nothing<bool>());
  }
  v8::String::Utf8Value bcp47_tag(v8_isolate, v8::Utils::ToLocal(tag));
  builder->setLanguageTag(
      {*bcp47_tag, static_cast<int32_t>(bcp47_tag.length())});
  DCHECK_LT(0, bcp47_tag.length());
  DCHECK_NOT_NULL(*bcp47_tag);
  // 2. If IsStructurallyValidLanguageTag(tag) is false, throw a RangeError
  // exception.
  if (!JSLocale::StartsWithUnicodeLanguageId(*bcp47_tag)) {
    return Just(false);
  }
  UErrorCode status = U_ZERO_ERROR;
  icu::Locale canonicalized = builder->build(status);
  canonicalized.canonicalize(status);
  if (U_FAILURE(status)) {
    return Just(false);
  }
  builder->setLocale(canonicalized);
  // 3. Let language be ? GetOption(options, "language", "string", undefined,
  // undefined).
  DirectHandle<String> language_str;
  Maybe<bool> maybe_language = GetStringOption(
      isolate, options, "language", std::span<std::string_view>(),
      "ApplyOptionsToTag", &language_str);
  MAYBE_RETURN(maybe_language, Nothing<bool>());
  // 4. If language is not undefined, then
  if (maybe_language.FromJust()) {
    std::string language_stdstr = language_str->ToStdString();
    builder->setLanguage(language_stdstr);
    builder->build(status);
    // a. If language does not match the unicode_language_subtag production,
    // throw a RangeError exception.
    if (U_FAILURE(status) || language_stdstr.empty() ||
        IsAlpha(language_stdstr, 4, 4)) {
      return Just(false);
    }
  }
  // 5. Let script be ? GetOption(options, "script", "string", undefined,
  // undefined).
  DirectHandle<String> script_str;
  Maybe<bool> maybe_script =
      GetStringOption(isolate, options, "script", std::span<std::string_view>(),
                      "ApplyOptionsToTag", &script_str);
  MAYBE_RETURN(maybe_script, Nothing<bool>());
  // 6. If script is not undefined, then
  if (maybe_script.FromJust()) {
    std::string script_stdstr = script_str->ToStdString();
    builder->setScript(script_stdstr);
    builder->build(status);
    // a. If script does not match the unicode_script_subtag production, throw
    // a RangeError exception.
    if (U_FAILURE(status) || script_stdstr.empty()) {
      return Just(false);
    }
  }
  // 7. Let region be ? GetOption(options, "region", "string", undefined,
  // undefined).
  DirectHandle<String> region_str;
  Maybe<bool> maybe_region =
      GetStringOption(isolate, options, "region", std::span<std::string_view>(),
                      "ApplyOptionsToTag", &region_str);
  MAYBE_RETURN(maybe_region, Nothing<bool>());
  // 8. If region is not undefined, then
  if (maybe_region.FromJust()) {
    std::string region_stdstr = region_str->ToStdString();
    // a. If region does not match the region production, throw a RangeError
    // exception.
    builder->setRegion(region_stdstr);
    builder->build(status);
    if (U_FAILURE(status) || region_stdstr.empty()) {
      return Just(false);
    }
  }
  // 9. Set tag to CanonicalizeLanguageTag(tag).
  // 10. If language is not undefined,
  // a. Assert: tag matches the unicode_locale_id production.
  // b. Set tag to tag with the substring corresponding to the
  // unicode_language_subtag production replaced by the string language.
  // 11. If script is not undefined, then
  // a. If tag does not contain a unicode_script_subtag production, then
  // i. Set tag to the concatenation of the unicode_language_subtag
  // production of tag, "-", script, and the rest of tag.
  // b. Else,
  // i. Set tag to tag with the substring corresponding to the
  // unicode_script_subtag production replaced by the string script.
  // 12. If region is not undefined, then
  // a. If tag does not contain a unicode_region_subtag production, then
  // i. Set tag to the concatenation of the unicode_language_subtag
  // production of tag, the substring corresponding to the "-"
  // unicode_script_subtag production if present, "-", region, and
  // the rest of tag.
  // b. Else,
  // i. Set tag to tag with the substring corresponding to the
  // unicode_region_subtag production replaced by the string region.
  // 13. Return CanonicalizeLanguageTag(tag).
  return Just(true);
}
References DCHECK_LT, DCHECK_NOT_NULL, v8::Maybe< T >::FromJust(), v8::internal::GetStringOption(), IsAlpha(), v8::Just(), v8::String::Utf8Value::length(), MAYBE_RETURN, v8::internal::JSLocale::StartsWithUnicodeLanguageId(), v8::internal::status, v8::internal::string, and THROW_NEW_ERROR_RETURN_VALUE.
Referenced by v8::internal::JSLocale::New().
CalendarsForLocale()
MaybeDirectHandle<JSArray> v8::internal::anonymous_namespace{js-locale.cc}::CalendarsForLocale (Isolate * isolate, const icu::Locale & icu_locale, bool commonly_used, bool sort)
Definition at line 543 of file js-locale.cc.
                                                                             {
  return GetKeywordValuesFromLocale<icu::Calendar>(
      isolate, "calendar", "ca", icu_locale, nullptr, commonly_used, sort);
}
References v8::base::sort().
Referenced by v8::internal::Intl::AvailableCalendars(), and v8::internal::JSLocale::GetCalendars().
Construct()
MaybeDirectHandle<JSLocale> v8::internal::anonymous_namespace{js-locale.cc}::Construct (Isolate * isolate, const icu::Locale & icu_locale)
Definition at line 425 of file js-locale.cc.
                                                                   {
  DirectHandle<Managed<icu::Locale>> managed_locale =
      Managed<icu::Locale>::From(
          isolate, 0, std::shared_ptr<icu::Locale>{icu_locale.clone()});
  DirectHandle<JSFunction> constructor(
      isolate->native_context()->intl_locale_function(), isolate);
  DirectHandle<Map> map;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, map,
      JSFunction::GetDerivedMap(isolate, constructor, constructor));
  DirectHandle<JSLocale> locale =
      Cast<JSLocale>(isolate->factory()->NewFastOrSlowJSObjectFromMap(map));
  DisallowGarbageCollection no_gc;
  locale->set_icu_locale(*managed_locale);
  return locale;
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::Isolate::factory(), v8::internal::Managed< CppType >::From(), v8::internal::JSFunction::GetDerivedMap(), v8::internal::Isolate::native_context(), v8::internal::Factory::NewFastOrSlowJSObjectFromMap(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::internal::CodeStubAssembler::ArraySpeciesCreate(), v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER(), v8::base::StaticallyAllocatedInstanceTrait< T >::InitStorageUsingTrait(), v8::internal::JSLocale::Maximize(), v8::internal::JSLocale::Minimize(), v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpreadOfCreateArguments(), v8::internal::compiler::JSCallReducer::ReduceJSConstruct(), and v8::internal::compiler::JSCallReducer::ReduceJSConstructForwardAllArgs().
InsertOptionsIntoLocale()
Maybe<bool> v8::internal::anonymous_namespace{js-locale.cc}::InsertOptionsIntoLocale (Isolate * isolate, DirectHandle< JSReceiver > options, icu::LocaleBuilder * builder)
Definition at line 52 of file js-locale.cc.
                                                               {
  DCHECK(isolate);
  static const auto hour_cycle_values =
      std::to_array<const std::string_view>({"h11", "h12", "h23", "h24"});
  static const auto case_first_values =
      std::to_array<const std::string_view>({"upper", "lower", "false"});
  const auto empty_values = std::span<std::string_view>();
  const std::array<OptionData, 7> kOptionToUnicodeTagMap = {
      {{"calendar", "ca", empty_values, false},
       {"collation", "co", empty_values, false},
       {"firstDayOfWeek", "fw", empty_values, false},
       {"hourCycle", "hc", hour_cycle_values, false},
       {"caseFirst", "kf", case_first_values, false},
       {"numeric", "kn", empty_values, true},
       {"numberingSystem", "nu", empty_values, false}}};
  // TODO(cira): Pass in values as per the spec to make this to be
  // spec compliant.
  for (const auto& option_to_bcp47 : kOptionToUnicodeTagMap) {
    DirectHandle<String> value_str;
    bool value_bool = false;
    Maybe<bool> maybe_found =
        option_to_bcp47.is_bool_value
            ? GetBoolOption(isolate, options, option_to_bcp47.name, "locale",
                            &value_bool)
            : GetStringOption(isolate, options, option_to_bcp47.name,
                              option_to_bcp47.possible_values, "locale",
                              &value_str);
    MAYBE_RETURN(maybe_found, Nothing<bool>());
    // TODO(cira): Use fallback value if value is not found to make
    // this spec compliant.
    if (!maybe_found.FromJust()) continue;
    std::string value_stdstr;
    const char* type = nullptr;
    if (!value_str.is_null()) {
      value_stdstr = value_str->ToStdString();
      type = value_stdstr.data();
    }
    if (strcmp(option_to_bcp47.key, "fw") == 0) {
      const std::array<ValueAndType, 8> kFirstDayValuesAndTypes = {
          {{"0", "sun"},
           {"1", "mon"},
           {"2", "tue"},
           {"3", "wed"},
           {"4", "thu"},
           {"5", "fri"},
           {"6", "sat"},
           {"7", "sun"}}};
      for (const auto& value_to_type : kFirstDayValuesAndTypes) {
        if (strcmp(type, value_to_type.value) == 0) {
          type = value_to_type.type;
          break;
        }
      }
    } else if (option_to_bcp47.is_bool_value) {
      type = value_bool ? "true" : "false";
    }
    DCHECK_NOT_NULL(type);
    // Overwrite existing, or insert new key-value to the locale string.
    if (!uloc_toLegacyType(uloc_toLegacyKey(option_to_bcp47.key), type)) {
      return Just(false);
    }
    builder->setUnicodeLocaleKeyword(option_to_bcp47.key, type);
  }
  return Just(true);
}
References v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::Maybe< T >::FromJust(), v8::internal::GetBoolOption(), v8::internal::GetStringOption(), v8::internal::DirectHandle< T >::is_null(), v8::Just(), MAYBE_RETURN, v8::internal::string, and v8::internal::tracing::type.
Referenced by v8::internal::JSLocale::New().
IsAlpha()
bool v8::internal::anonymous_namespace{js-locale.cc}::IsAlpha (std::string_view str, size_t min, size_t max)
Definition at line 156 of file js-locale.cc.
                                                         {
  return IsCheckRange(str, min, max, [](char c) -> bool {
    return base::IsInRange(c, 'a', 'z') || base::IsInRange(c, 'A', 'Z');
  });
}
References IsCheckRange().
Referenced by ApplyOptionsToTag(), v8::internal::JSLocale::Is3Alpha(), IsUnicodeLanguageSubtag(), IsUnicodeRegionSubtag(), and IsUnicodeScriptSubtag().
IsAlphanum()
bool v8::internal::anonymous_namespace{js-locale.cc}::IsAlphanum (std::string_view str, size_t min, size_t max)
Definition at line 168 of file js-locale.cc.
                                                            {
  return IsCheckRange(str, min, max, [](char c) -> bool {
    return base::IsInRange(c, 'a', 'z') || base::IsInRange(c, 'A', 'Z') ||
           base::IsInRange(c, '0', '9');
  });
}
References IsCheckRange().
Referenced by v8::internal::JSLocale::Is38AlphaNumList(), IsDigitAlphanum3(), IsExtensionSingleton(), and IsUnicodeVariantSubtag().
IsCheckRange()
bool v8::internal::anonymous_namespace{js-locale.cc}::IsCheckRange (std::string_view str, size_t min, size_t max, bool(range_check_func)(char))
Definition at line 148 of file js-locale.cc.
                                                {
  if (!base::IsInRange(str.length(), min, max)) return false;
  for (size_t i = 0; i < str.length(); i++) {
    if (!range_check_func(str[i])) return false;
  }
  return true;
}
Referenced by IsAlpha(), IsAlphanum(), and IsDigit().
IsDigit()
bool v8::internal::anonymous_namespace{js-locale.cc}::IsDigit (std::string_view str, size_t min, size_t max)
Definition at line 162 of file js-locale.cc.
                                                         {
  return IsCheckRange(str, min, max, [](char c) -> bool {
    return base::IsInRange(c, '0', '9');
  });
}
References IsCheckRange().
Referenced by IsUnicodeRegionSubtag().
IsDigitAlphanum3()
bool v8::internal::anonymous_namespace{js-locale.cc}::IsDigitAlphanum3 (std::string_view value)
Definition at line 190 of file js-locale.cc.
                                            {
  return value.length() == 4 && base::IsInRange(value[0], '0', '9') &&
         IsAlphanum(value.substr(1), 3, 3);
}
References IsAlphanum(), and v8::internal::value.
Referenced by IsUnicodeVariantSubtag().
IsExtensionSingleton()
bool v8::internal::anonymous_namespace{js-locale.cc}::IsExtensionSingleton (std::string_view value)
Definition at line 200 of file js-locale.cc.
                                                {
  return IsAlphanum(value, 1, 1);
}
References IsAlphanum(), and v8::internal::value.
Referenced by v8::internal::JSLocale::StartsWithUnicodeLanguageId().
IsUnicodeLanguageSubtag()
bool v8::internal::anonymous_namespace{js-locale.cc}::IsUnicodeLanguageSubtag (std::string_view value)
Definition at line 175 of file js-locale.cc.
                                                   {
  // unicode_language_subtag = alpha{2,3} | alpha{5,8};
  return IsAlpha(value, 2, 3) || IsAlpha(value, 5, 8);
}
References IsAlpha(), and v8::internal::value.
Referenced by v8::internal::JSLocale::StartsWithUnicodeLanguageId().
IsUnicodeRegionSubtag()
bool v8::internal::anonymous_namespace{js-locale.cc}::IsUnicodeRegionSubtag (std::string_view value)
Definition at line 185 of file js-locale.cc.
                                                 {
  // unicode_region_subtag = (alpha{2} | digit{3});
  return IsAlpha(value, 2, 2) || IsDigit(value, 3, 3);
}
References IsAlpha(), IsDigit(), and v8::internal::value.
Referenced by v8::internal::JSLocale::StartsWithUnicodeLanguageId().
IsUnicodeScriptSubtag()
bool v8::internal::anonymous_namespace{js-locale.cc}::IsUnicodeScriptSubtag (std::string_view value)
Definition at line 180 of file js-locale.cc.
                                                 {
  // unicode_script_subtag = alpha{4} ;
  return IsAlpha(value, 4, 4);
}
References IsAlpha(), and v8::internal::value.
Referenced by v8::internal::JSLocale::StartsWithUnicodeLanguageId().
IsUnicodeVariantSubtag()
bool v8::internal::anonymous_namespace{js-locale.cc}::IsUnicodeVariantSubtag (std::string_view value)
Definition at line 195 of file js-locale.cc.
                                                  {
  // unicode_variant_subtag = (alphanum{5,8} | digit alphanum{3}) ;
  return IsAlphanum(value, 5, 8) || IsDigitAlphanum3(value);
}
References IsAlphanum(), IsDigitAlphanum3(), and v8::internal::value.
Referenced by v8::internal::JSLocale::StartsWithUnicodeLanguageId().
UnicodeKeywordValue()
DirectHandle<Object> v8::internal::anonymous_namespace{js-locale.cc}::UnicodeKeywordValue (Isolate * isolate, DirectHandle< JSLocale > locale, const char * key)
Definition at line 129 of file js-locale.cc.
                                                          {
  icu::Locale* icu_locale = locale->icu_locale()->raw();
  UErrorCode status = U_ZERO_ERROR;
  std::string value =
      icu_locale->getUnicodeKeywordValue<std::string>(key, status);
  if (status == U_ILLEGAL_ARGUMENT_ERROR || value.empty()) {
    return isolate->factory()->undefined_value();
  }
  if (value == "yes") {
    value = "true";
  }
  if (value == "true" && strcmp(key, "kf") == 0) {
    return isolate->factory()->NewStringFromStaticChars("");
  }
  return isolate->factory()->NewStringFromAsciiChecked(value.c_str());
}
References v8::internal::Isolate::factory(), v8::internal::key, v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), v8::internal::Factory::NewStringFromStaticChars(), v8::internal::status, v8::internal::string, and v8::internal::value.
Referenced by v8::internal::JSLocale::Calendar(), v8::internal::JSLocale::CaseFirst(), v8::internal::JSLocale::Collation(), v8::internal::JSLocale::FirstDayOfWeek(), v8::internal::JSLocale::HourCycle(), and v8::internal::JSLocale::NumberingSystem().
weekdayFromEDaysOfWeek()
int32_t v8::internal::anonymous_namespace{js-locale.cc}::weekdayFromEDaysOfWeek (icu::Calendar::EDaysOfWeek eDaysOfWeek)
Definition at line 204 of file js-locale.cc.
                                                                   {
  return (eDaysOfWeek == icu::Calendar::SUNDAY) ? 7 : eDaysOfWeek - 1;
}
Referenced by v8::internal::JSLocale::GetWeekInfo().