v8::internal::compiler::anonymous_namespace{basic-block-instrumentor.cc} Namespace Reference
Functions
void StoreBuiltinCallForNode (Node *n, Builtin builtin, int block_id, BuiltinsCallGraph *bcc_profiler)
Function Documentation
StoreBuiltinCallForNode()
void v8::internal::compiler::anonymous_namespace{basic-block-instrumentor.cc}::StoreBuiltinCallForNode (Node * n, Builtin builtin, int block_id, BuiltinsCallGraph * bcc_profiler)
Definition at line 166 of file basic-block-instrumentor.cc.
                                                              {
  if (n == nullptr) return;
  IrOpcode::Value opcode = n->opcode();
  if (opcode == IrOpcode::kCall || opcode == IrOpcode::kTailCall) {
    const CallDescriptor* des = CallDescriptorOf(n->op());
    if (des->kind() == CallDescriptor::kCallCodeObject) {
      Node* callee = n->InputAt(0);
      Operator* op = const_cast<Operator*>(callee->op());
      if (op->opcode() == IrOpcode::kHeapConstant) {
        IndirectHandle<HeapObject> para =
            OpParameter<IndirectHandle<HeapObject>>(op);
        if (IsCode(*para)) {
          DirectHandle<Code> code = Cast<Code>(para);
          if (code->is_builtin()) {
            bcc_profiler->AddBuiltinCall(builtin, code->builtin_id(), block_id);
            return;
          }
        }
      }
    }
  }
}
References v8::internal::BuiltinsCallGraph::AddBuiltinCall(), v8::internal::compiler::CallDescriptorOf(), code, v8::internal::compiler::Node::InputAt(), v8::internal::compiler::CallDescriptor::kCallCodeObject, v8::internal::compiler::CallDescriptor::kind(), v8::internal::wasm::kTailCall, v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), and v8::internal::compiler::Operator::opcode().
Referenced by v8::internal::compiler::BasicBlockCallGraphProfiler::StoreCallGraph().