v8::base::anonymous_namespace{platform-posix.cc} Namespace Reference
Enumerations
enum class PageType { kShared
, kPrivate
 }
Functions
DEFINE_LAZY_LEAKY_OBJECT_GETTER (RandomNumberGenerator, GetPlatformRandomNumberGenerator) static LazyMutex rng_mutex
int GetFlagsForMemoryPermission (OS::MemoryPermission access, PageType page_type)
void * Allocate (void *hint, size_t size, OS::MemoryPermission access, PageType page_type)
Variables
const pthread_t kNoThread = static_cast<pthread_t>(0)
const char * g_gc_fake_mmap = nullptr
const int kMmapFd = -1
const int kMmapFdOffset = 0
Enumeration Type Documentation
PageType
enum v8::base::anonymous_namespace{platform-posix.cc}::PageType [strong]
Enumerator
kShared
kPrivate
Definition at line 138 of file platform-posix.cc.
{ kShared, kPrivate };
Function Documentation
Allocate()
void* v8::base::anonymous_namespace{platform-posix.cc}::Allocate (void * hint, size_t size, OS::MemoryPermission access, PageType page_type)
Definition at line 166 of file platform-posix.cc.
                                   {
  int prot = GetProtectionFromMemoryPermission(access);
  int flags = GetFlagsForMemoryPermission(access, page_type);
  void* result = mmap(hint, size, prot, flags, kMmapFd, kMmapFdOffset);
  if (result == MAP_FAILED) return nullptr;
#if V8_OS_LINUX && V8_ENABLE_PRIVATE_MAPPING_FORK_OPTIMIZATION
  // This is advisory, so we ignore errors.
  madvise(result, size, MADV_DONTFORK);
#endif
#if ENABLE_HUGEPAGE
  if (result != nullptr && size >= kHugePageSize) {
    const uintptr_t huge_start =
        RoundUp(reinterpret_cast<uintptr_t>(result), kHugePageSize);
    const uintptr_t huge_end =
        RoundDown(reinterpret_cast<uintptr_t>(result) + size, kHugePageSize);
    if (huge_end > huge_start) {
      // Bail out in case the aligned addresses do not provide a block of at
      // least kHugePageSize size.
      madvise(reinterpret_cast<void*>(huge_start), huge_end - huge_start,
              MADV_HUGEPAGE);
    }
  }
#endif
  return result;
}
References flags(), GetFlagsForMemoryPermission(), v8::base::GetProtectionFromMemoryPermission(), kMmapFd, kMmapFdOffset, v8::base::internal::result, RoundDown(), RoundUp(), and size().
Referenced by v8::internal::OrderedHashMapHandler::AdjustRepresentation(), v8::internal::OrderedHashSetHandler::AdjustRepresentation(), v8::internal::OrderedNameDictionaryHandler::AdjustRepresentation(), v8::anonymous_namespace{d8.cc}::ShellArrayBufferAllocator::Allocate(), v8::anonymous_namespace{d8.cc}::MockArrayBufferAllocator::Allocate(), v8::anonymous_namespace{d8.cc}::MockArrayBufferAllocatiorWithLimit::Allocate(), v8::internal::anonymous_namespace{builtins-async-generator-gen.cc}::AsyncGeneratorBuiltinsAssembler::AllocateAsyncGeneratorRequest(), v8::internal::CodeStubAssembler::AllocateJSIteratorResult(), v8::internal::CodeStubAssembler::AllocateJSIteratorResultForEntry(), v8::internal::CodeStubAssembler::AllocatePromiseWithResolversResult(), v8::internal::CodeStubAssembler::AllocatePropertyDescriptorObject(), v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(), v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(), v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::BuildAllocateJSExternalObject(), v8::internal::OrderedHashTable< Derived, entrysize >::Clear(), v8::internal::HeapAllocator::CollectGarbageAndRetryAllocation(), v8::internal::CodeStubAssembler::CreateAllocationSiteInFeedbackVector(), v8::internal::HeapAllocator::CustomAllocateWithRetryOrFail(), v8::internal::AstConsString::GetString(), v8::internal::ArrayList::New(), v8::internal::ByteArray::New(), v8::internal::TrustedByteArray::New(), v8::internal::SmallOrderedHashMap::OBJECT_CONSTRUCTORS(), v8::internal::StringTable::Data::operator new(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::Deserializer< IsolateT >::ReadMetaMap(), v8::internal::Deserializer< IsolateT >::ReadObject(), v8::internal::Deserializer< IsolateT >::ReadOffHeapBackingStore(), v8::internal::HeapAllocator::RetryAllocation(), and v8::internal::TF_BUILTIN().
DEFINE_LAZY_LEAKY_OBJECT_GETTER()
v8::base::anonymous_namespace{platform-posix.cc}::DEFINE_LAZY_LEAKY_OBJECT_GETTER (RandomNumberGenerator , GetPlatformRandomNumberGenerator)
GetFlagsForMemoryPermission()
int v8::base::anonymous_namespace{platform-posix.cc}::GetFlagsForMemoryPermission (OS::MemoryPermission access, PageType page_type)
Definition at line 140 of file platform-posix.cc.
                                                    {
  int flags = MAP_ANONYMOUS;
  flags |= (page_type == PageType::kShared) ? MAP_SHARED : MAP_PRIVATE;
  if (access == OS::MemoryPermission::kNoAccess ||
      access == OS::MemoryPermission::kNoAccessWillJitLater) {
#if !V8_OS_AIX && !V8_OS_FREEBSD && !V8_OS_QNX
    flags |= MAP_NORESERVE;
#endif // !V8_OS_AIX && !V8_OS_FREEBSD && !V8_OS_QNX
#if V8_OS_QNX
    flags |= MAP_LAZY;
#endif // V8_OS_QNX
  }
#if V8_OS_DARWIN
  // MAP_JIT is required to obtain writable and executable pages when the
  // hardened runtime/memory protection is enabled, which is optional (via code
  // signing) on Intel-based Macs but mandatory on Apple silicon ones. See also
  // https://developer.apple.com/documentation/apple-silicon/porting-just-in-time-compilers-to-apple-silicon.
  if (access == OS::MemoryPermission::kNoAccessWillJitLater ||
      access == OS::MemoryPermission::kReadWriteExecute) {
    flags |= MAP_JIT;
  }
#endif // V8_OS_DARWIN
  return flags;
}
References flags(), v8::base::OS::kNoAccess, v8::base::OS::kNoAccessWillJitLater, v8::base::OS::kReadWriteExecute, and v8::internal::anonymous_namespace{elements.cc}::kShared.
Referenced by Allocate().
Variable Documentation
g_gc_fake_mmap
const char* v8::base::anonymous_namespace{platform-posix.cc}::g_gc_fake_mmap = nullptr
Definition at line 113 of file platform-posix.cc.
Referenced by v8::base::PosixInitializeCommon().
kMmapFd
const int v8::base::anonymous_namespace{platform-posix.cc}::kMmapFd = -1
Definition at line 126 of file platform-posix.cc.
Referenced by Allocate().
kMmapFdOffset
const int v8::base::anonymous_namespace{platform-posix.cc}::kMmapFdOffset = 0
Definition at line 136 of file platform-posix.cc.
Referenced by Allocate().
kNoThread
const pthread_t v8::base::anonymous_namespace{platform-posix.cc}::kNoThread = static_cast<pthread_t>(0)
Definition at line 110 of file platform-posix.cc.