v8 Namespace Reference
This file provides additional API on top of the default one for making API calls, which come from embedder C++ functions.
Namespaces
 anonymous_namespace{api.cc}
 anonymous_namespace{async-hooks-wrapper.cc}
 anonymous_namespace{code-generator-riscv.cc}
 anonymous_namespace{d8-console.cc}
 anonymous_namespace{d8-posix.cc}
 anonymous_namespace{d8-test.cc}
 anonymous_namespace{d8.cc}
 anonymous_namespace{unwinder.cc}
 anonymous_namespace{v8threads.cc}
 anonymous_namespace{wasm-js.cc}
 api_internal
 base
 bigint
 debug
 detail
Helper function template to create an array of fixed length, initialized by the provided initializer list, without explicitly specifying the array size, e.g.
 internal
 metrics
 platform
 sampler
 tracing
Classes
class CallDepthScope
class InternalEscapableScope
class EnterV8InternalScope
class EnterV8Scope
class EnterV8NoScriptScope
class EnterV8NoScriptNoExceptionScope
class EnterV8BasicScope
class PrepareForExecutionScope
class PrepareForDebugInterfaceExecutionScope
class ApiRuntimeCallStatsScope
class PropertyDescriptor
An instance of a Property Descriptor, see Ecma-262 6.2.4.
struct OneByteMask
struct OneByteMask< 4 >
struct OneByteMask< 8 >
class ContainsOnlyOneByteHelper
struct InvokeBootstrapper
struct InvokeBootstrapper< i::NativeContext >
struct InvokeBootstrapper< i::JSGlobalProxy >
class ApiFunction
class RegisteredExtension
class Utils
struct AcquireLoadTag
struct RelaxedLoadTag
struct ReleaseStoreTag
struct RelaxedStoreTag
struct SeqCstAccessTag
struct AsyncContext
class AsyncHooksWrap
class AsyncHooks
class D8Console
class PredictablePlatform
class DelayedTasksPlatform
class ZombieProtector
class OpenFDCloser
class ExecArgs
class ExternalOwningOneByteStringResource
class DummySourceStream
class StreamerThread
struct DynamicImportData
class SetTimeoutTask
class OnMessageFromWorkerTask
class CheckMessageFromWorkerTask
class CleanUpWorkerTask
class InspectorFrontend
class InspectorClient
class ProcessMessageTask
class TerminateTask
class Serializer
class Deserializer
class D8Testing
class Counter
class CounterCollection
class SourceGroup
class SerializationData
class SerializationDataQueue
class Worker
class PerIsolateData
class ShellOptions
class Shell
class FuzzerMonitor
class FunctionCallbackInfo
The argument information given to function call callbacks.
class BackingStore
A wrapper around the backing store (i.e.
class ArrayBuffer
An instance of the built-in ArrayBuffer constructor (ES6 draft 15.13.5).
class ArrayBufferView
A base class for an instance of one of `views` over ArrayBuffer, including TypedArrays and DataView (ES6 draft 15.13).
class DataView
An instance of DataView constructor (ES6 draft 15.13.7).
class SharedArrayBuffer
An instance of the built-in SharedArrayBuffer constructor.
struct JitCodeEvent
A JIT code event is issued each time code is added, moved or removed.
struct OOMDetails
struct ModifyCodeGenerationFromStringsResult
class Array
An instance of the built-in array constructor (ECMA-262, 15.4.2).
class Map
An instance of the built-in Map constructor (ECMA-262, 6th Edition, 23.1.1).
class Set
An instance of the built-in Set constructor (ECMA-262, 6th Edition, 23.2.1).
class ExtensionConfiguration
A container for extension names.
class Context
A sandboxed execution context with its own set of built-in objects and functions.
class CppHeapExternal
A JavaScript value that wraps a cppgc::GarbageCollected<T> object allocated on the managed C++ heap (CppHeap).
struct CppHeapCreateParams
class CppHeap
A heap for allocating managed C++ objects.
class JSVisitor
class CustomSpaceStatisticsReceiver
Provided as input to CppHeap::CollectCustomSpaceStatisticsAtLastGC().
class Data
The superclass of objects that can reside on V8's heap.
class FixedArray
A fixed-sized array with elements of type Data.
class Date
An instance of the built-in Date constructor (ECMA-262, 15.9).
class StackFrame
A single JavaScript stack frame.
class StackTrace
Representation of a JavaScript stack trace.
class EmbedderRootsHandler
Handler for embedder roots on non-unified heap garbage collections.
class EmbedderStateScope
class Exception
Create new error objects by calling the corresponding error object constructor with the message.
class ExceptionPropagationMessage
This is a part of experimental Api and might be changed without further notice.
class TryCatch
An external exception handler.
class Extension
Ignore.
class ExternalMemoryAccounter
This class is used to give V8 an indication of the amount of externally allocated memory that is kept alive by JavaScript objects.
class External
A JavaScript value that wraps a C++ void*.
class CTypeInfo
struct FastOneByteString
class CFunctionInfo
union AnyCType
class CFunction
struct FastApiCallbackOptions
A struct which may be passed to a fast call callback, like so:
class CTypeInfoBuilder
class BasicTracedReference
A traced handle with copy and move semantics.
class Global
A PersistentBase which has move semantics.
class ReturnValue
class PropertyCallbackInfo
The information passed to a property callback about the context of the property access.
class Function
A JavaScript function object (ECMA-262, 15.3).
class PersistentValueMapBase
A map wrapper that allows using Global as a mapped value.
class V8
Container class for static utility functions.
class ResourceConstraints
A set of constraints that specifies the limits of the runtime's memory use.
class IsolateGroup
The set of V8 isolates in a process is partitioned into groups.
class Isolate
Isolate represents an isolated instance of the V8 engine.
class JSON
A JSON Parser and Stringifier.
class LocalBase
A base class for local handles.
class Local
An object reference managed by the v8 garbage collector.
class LocalVector
class MaybeLocal
A MaybeLocal<> is a wrapper around Local<> that enforces a check whether the Local<> is empty before it can be used.
class Eternal
Eternal handles are set-once handles that live for the lifetime of the isolate.
class NonCopyablePersistentTraits
Default traits for Persistent.
class PersistentBase
An object reference that is independent of any handle scope.
class Persistent
A PersistentBase which allows copy and assignment.
class TracedReference
A traced handle without destructor that clears the handle.
class Traced
class HandleScope
A stack-allocated class that governs a number of local handles.
class EscapableHandleScopeBase
A HandleScope which first allocates a handle in the current scope which will be later filled with the escape value.
class EscapableHandleScope
class SealHandleScope
A SealHandleScope acts like a handle scope in which no handle allocations are allowed.
class Unlocker
Multiple threads in V8 are allowed, but only one thread at a time is allowed to use any given V8 isolate, see the comments in the Isolate class.
class Locker
class Maybe
A simple Maybe type, representing an object which may or may not have a value, see https://hackage.haskell.org/package/base/docs/Data-Maybe.html.
class Maybe< void >
class MemorySpan
Points to an unowned contiguous buffer holding a known number of elements.
class ScriptOriginOptions
The optional attributes of ScriptOrigin.
class ScriptOrigin
The origin, within a file, of a script.
class Message
An error message.
class MicrotaskQueue
Represents the microtask queue, where microtasks are stored and processed.
class MicrotasksScope
This scope is used to control microtasks when MicrotasksPolicy::kScoped is used on Isolate.
class Private
A private symbol.
class Object
A JavaScript object (ECMA-262, 4.3.3)
class PersistentValueMap
class PersistentHandleVisitor
Interface for iterating through all the persistent handles in the heap.
class Task
A Task represents a unit of work.
class IdleTask
An IdleTask represents a unit of work to be performed in idle time.
class TaskRunner
A TaskRunner allows scheduling of tasks.
class JobDelegate
Delegate that's passed to Job's worker task, providing an entry point to communicate with the scheduler.
class JobHandle
Handle returned when posting a Job.
class JobTask
A JobTask represents work to run in parallel from Platform::PostJob().
class ScopedBlockingCall
This class is instantiated with CreateBlockingScope() in every scope where a blocking call is made and serves as a precise annotation of the scope that may/will block.
class ConvertableToTraceFormat
The interface represents complex arguments to trace events.
class TracingController
V8 Tracing controller.
class PageAllocator
A V8 memory page allocator.
class ThreadIsolatedAllocator
An allocator that uses per-thread permissions to protect the memory.
class VirtualAddressSpace
Class to manage a virtual memory address space.
class HighAllocationThroughputObserver
Observer used by V8 to notify the embedder about entering/leaving sections with high throughput of malloc/free operations.
class Platform
V8 Platform abstraction layer.
class NumberObject
A Number object (ECMA-262, 4.3.21).
class BigIntObject
A BigInt object (https://tc39.github.io/proposal-bigint)
class BooleanObject
A Boolean object (ECMA-262, 4.3.15).
class StringObject
A String object (ECMA-262, 4.3.18).
class SymbolObject
A Symbol object (ECMA-262 edition 6).
class Primitive
The superclass of primitive values.
class Boolean
A primitive boolean value (ECMA-262, 4.3.14).
class PrimitiveArray
An array to hold Primitive values.
class Name
A superclass for symbols and strings.
class String
A JavaScript string value (ECMA-262, 4.3.17).
class ExternalResourceVisitor
Interface for iterating through all external resources in the heap.
class Symbol
A JavaScript symbol (ECMA-262 edition 6)
class Numeric
A JavaScript numeric value (either Number or BigInt).
class Number
A JavaScript number value (ECMA-262, 4.3.20)
class Integer
A JavaScript value representing a signed integer.
class Int32
A JavaScript value representing a 32-bit signed integer.
class Uint32
A JavaScript value representing a 32-bit unsigned integer.
class BigInt
A JavaScript BigInt value (https://tc39.github.io/proposal-bigint)
struct CpuProfileDeoptFrame
struct CpuProfileDeoptInfo
class CpuProfileNode
CpuProfileNode represents a node in a call graph.
class OutputStream
An interface for exporting data from V8, using `push` model.
class CpuProfile
CpuProfile contains a CPU profile in a form of top-down call tree (from main() down to functions that do all the work).
struct CpuProfilingResult
Result from StartProfiling returning the Profiling Status, and id of the started profiler, or 0 if profiler is not started.
class DiscardedSamplesDelegate
Delegate for when max samples reached and samples are discarded.
class CpuProfilingOptions
Optional profiling attributes.
class CpuProfiler
Interface for controlling CPU profiling.
class HeapGraphEdge
HeapSnapshotEdge represents a directed connection between heap graph nodes: from retainers to retained nodes.
class HeapGraphNode
HeapGraphNode represents a node in a heap graph.
class HeapSnapshot
HeapSnapshots record the state of the JS heap at some moment.
class ActivityControl
An interface for reporting progress and controlling long-running activities.
class AllocationProfile
AllocationProfile is a sampled profile of allocations done by the program.
class EmbedderGraph
An object graph consisting of embedder objects and V8 objects.
class QueryObjectPredicate
class HeapProfiler
Interface for controlling heap profiling.
struct HeapStatsUpdate
A struct for exporting HeapStats data from V8, using `push` model.
class CodeEvent
Representation of a code creation event.
class CodeEventHandler
Interface to listen to code creation and code relocation events.
class Promise
An instance of the built-in Promise constructor (ES6 draft).
class PromiseRejectMessage
class Proxy
An instance of the built-in Proxy constructor (ECMA-262, 6th Edition, 26.2.1).
class RegExp
An instance of the built-in RegExp constructor (ECMA-262, 15.10).
struct CppHeapPointerTagRange
class SandboxHardwareSupport
class ScriptOrModule
A container type that holds relevant metadata for module loading.
class UnboundScript
A compiled JavaScript script, not yet tied to a Context.
class UnboundModuleScript
A compiled JavaScript module, not yet tied to a Context.
class Location
A location in JavaScript source.
class ModuleRequest
class Module
A compiled JavaScript module.
class CompileHintsCollector
class Script
A compiled JavaScript script, tied to a Context which was active when the script was compiled.
class ScriptCompiler
For compiling scripts.
class StartupData
struct SerializeInternalFieldsCallback
Callback and supporting data used in SnapshotCreator to implement embedder logic to serialize internal fields of v8::Objects.
struct SerializeContextDataCallback
Similar to SerializeInternalFieldsCallback, but works with the embedder data in a v8::Context.
struct SerializeAPIWrapperCallback
Similar to SerializeInternalFieldsCallback, but is used exclusively to serialize API wrappers.
struct DeserializeInternalFieldsCallback
Callback and supporting data used to implement embedder logic to deserialize internal fields of v8::Objects.
struct DeserializeContextDataCallback
Similar to DeserializeInternalFieldsCallback, but works with the embedder data in a v8::Context.
struct DeserializeAPIWrapperCallback
class SnapshotCreator
Helper class to create a snapshot data blob.
class SourceLocation
Encapsulates source location information.
class MeasureMemoryDelegate
The delegate is used in Isolate::MeasureMemory API.
class SharedMemoryStatistics
Collection of shared per-process V8 memory information.
class HeapStatistics
Collection of V8 heap information.
class HeapSpaceStatistics
class HeapObjectStatistics
class HeapCodeStatistics
class Template
The superclass of object and function templates.
class FunctionTemplate
A FunctionTemplate is used to create functions at runtime.
struct NamedPropertyHandlerConfiguration
struct IndexedPropertyHandlerConfiguration
class ObjectTemplate
An ObjectTemplate is used to create objects at runtime.
class DictionaryTemplate
A template to create dictionary objects at runtime.
class Signature
A Signature specifies which receiver is valid for a function.
class TracedReferenceBase
An indirect handle, where the indirect pointer points to a GlobalHandles node.
class TypedArray
A base class for an instance of TypedArray series of constructors (ES6 draft 15.13.6).
class Uint8Array
An instance of Uint8Array constructor (ES6 draft 15.13.6).
class Uint8ClampedArray
An instance of Uint8ClampedArray constructor (ES6 draft 15.13.6).
class Int8Array
An instance of Int8Array constructor (ES6 draft 15.13.6).
class Uint16Array
An instance of Uint16Array constructor (ES6 draft 15.13.6).
class Int16Array
An instance of Int16Array constructor (ES6 draft 15.13.6).
class Uint32Array
An instance of Uint32Array constructor (ES6 draft 15.13.6).
class Int32Array
An instance of Int32Array constructor (ES6 draft 15.13.6).
class Float16Array
An instance of Float16Array constructor.
class Float32Array
An instance of Float32Array constructor (ES6 draft 15.13.6).
class Float64Array
An instance of Float64Array constructor (ES6 draft 15.13.6).
class BigInt64Array
An instance of BigInt64Array constructor.
class BigUint64Array
An instance of BigUint64Array constructor.
struct RegisterState
struct SampleInfo
struct MemoryRange
struct JSEntryStub
struct JSEntryStubs
class Unwinder
Various helpers for skipping over V8 frames in a given stack.
class GlobalValueMap
class StdMapTraits
A default trait implementation for PersistentValueMap which uses std::map as a backing map.
class DefaultPersistentValueMapTraits
A default trait implementation for PersistentValueMap, which inherits a std:map backing map from StdMapTraits and holds non-weak persistent objects and has no special Dispose handling.
class DefaultGlobalMapTraits
class StdPersistentValueMap
A map that uses Global as value and std::map as the backing implementation.
class StdGlobalValueMap
A map that uses Global as value and std::map as the backing implementation.
class SharedValueConveyor
A move-only class for managing the lifetime of shared value conveyors used by V8 to keep JS shared values alive in transit when serialized.
class ValueSerializer
Value serialization compatible with the HTML structured clone algorithm.
class ValueDeserializer
Deserializes values from data written with ValueSerializer, or a compatible implementation.
class Value
The superclass of all JavaScript values and objects.
class TypecheckWitness
Can be used to avoid repeated expensive type checks for groups of objects that are expected to be similar (e.g.
struct OwnedBuffer
An owned byte buffer with associated size.
class CompiledWasmModule
class WasmMemoryObject
class WasmModuleObject
class WasmStreaming
The V8 interface for WebAssembly streaming compilation.
class WasmMemoryMapDescriptor
The V8 interface for a WebAssembly memory map descriptor.
class WeakCallbackInfo
Typedefs
using RCCId = i::RuntimeCallCounterId
using async_id_t = double
using CounterMap = std::unordered_map< std::string, Counter * >
using BackingStoreDeleterCallback = void(*)(void *data, size_t length, void *deleter_data)
using JitCodeEventHandler = void(*)(const JitCodeEvent *event)
Callback function passed to SetJitCodeEventHandler.
using GCCallback = void(*)(GCType type, GCCallbackFlags flags)
using InterruptCallback = void(*)(Isolate *isolate, void *data)
using PrintCurrentStackTraceFilterCallback = bool(*)(Isolate *isolate, Local< String > script_name)
using NearHeapLimitCallback = size_t(*)(void *data, size_t current_heap_limit, size_t initial_heap_limit)
This callback is invoked when the heap size is close to the heap limit and V8 is likely to abort with out-of-memory error.
using CounterLookupCallback = int *(*)(const char *name)
Callback function passed to SetUnhandledExceptionCallback.
using CreateHistogramCallback = void *(*)(const char *name, int min, int max, size_t buckets)
using AddHistogramSampleCallback = void(*)(void *histogram, int sample)
using FatalErrorCallback = void(*)(const char *location, const char *message)
using OOMErrorCallback = void(*)(const char *location, const OOMDetails &details)
using MessageCallback = void(*)(Local< Message > message, Local< Value > data)
using LogEventCallback = void(*)(const char *name, int status)
using AddCrashKeyCallback = void(*)(CrashKeyId id, const std::string &value)
using BeforeCallEnteredCallback = void(*)(Isolate *)
using CallCompletedCallback = void(*)(Isolate *)
using ModifyCodeGenerationFromStringsCallback = ModifyCodeGenerationFromStringsResult(*)(Local< Context > context, Local< Value > source)
Callback to check if codegen is allowed from a source object, and convert the source to string if necessary.
using ModifyCodeGenerationFromStringsCallback2 = ModifyCodeGenerationFromStringsResult(*)(Local< Context > context, Local< Value > source, bool is_code_like)
using FailedAccessCheckCallback = void(*)(Local< Object > target, AccessType type, Local< Value > data)
using ExtensionCallback = bool(*)(const FunctionCallbackInfo< Value > &)
using AllowWasmCodeGenerationCallback = bool(*)(Local< Context > context, Local< String > source)
using ApiImplementationCallback = void(*)(const FunctionCallbackInfo< Value > &)
using WasmStreamingCallback = void(*)(const FunctionCallbackInfo< Value > &)
using WasmAsyncResolvePromiseCallback = void(*)(Isolate *isolate, Local< Context > context, Local< Promise::Resolver > resolver, Local< Value > result, WasmAsyncSuccess success)
using WasmLoadSourceMapCallback = Local< String >(*)(Isolate *isolate, const char *name)
using WasmImportedStringsEnabledCallback = bool(*)(Local< Context > context)
using SharedArrayBufferConstructorEnabledCallback = bool(*)(Local< Context > context)
using WasmJSPIEnabledCallback = bool(*)(Local< Context > context)
using HostImportModuleDynamicallyCallback = MaybeLocal< Promise >(*)(Local< Context > context, Local< Data > host_defined_options, Local< Value > resource_name, Local< String > specifier, Local< FixedArray > import_attributes)
HostImportModuleDynamicallyCallback is called when we require the embedder to load a module.
using HostImportModuleWithPhaseDynamicallyCallback = MaybeLocal< Promise >(*)(Local< Context > context, Local< Data > host_defined_options, Local< Value > resource_name, Local< String > specifier, ModuleImportPhase phase, Local< FixedArray > import_attributes)
HostImportModuleWithPhaseDynamicallyCallback is called when we require the embedder to load a module with a specific phase.
using CompileHintCallback = bool(*)(int, void *)
Callback for requesting a compile hint for a function from the embedder.
using HostInitializeImportMetaObjectCallback = void(*)(Local< Context > context, Local< Module > module, Local< Object > meta)
HostInitializeImportMetaObjectCallback is called the first time import.meta is accessed for a module.
using HostCreateShadowRealmContextCallback = MaybeLocal< Context >(*)(Local< Context > initiator_context)
HostCreateShadowRealmContextCallback is called each time a ShadowRealm is being constructed in the initiator_context.
using IsJSApiWrapperNativeErrorCallback = bool(*)(Isolate *isolate, Local< Object > obj)
IsJSApiWrapperNativeErrorCallback is called on an JSApiWrapper object to determine if Error.isError should return true or false.
using PrepareStackTraceCallback = MaybeLocal< Value >(*)(Local< Context > context, Local< Value > error, Local< Array > sites)
PrepareStackTraceCallback is called when the stack property of an error is first accessed.
using ExceptionPropagationCallback = void(*)(ExceptionPropagationMessage message)
using CFunctionBuilder = internal::CFunctionBuilder
using FunctionCallback = void(*)(const FunctionCallbackInfo< Value > &info)
using EntropySource = bool(*)(unsigned char *buffer, size_t length)
EntropySource is used as a callback function when v8 needs a source of entropy.
using ReturnAddressLocationResolver = uintptr_t(*)(uintptr_t return_addr_location)
ReturnAddressLocationResolver is used as a callback function when v8 is resolving the location of a return address on the stack.
using DcheckErrorCallback = void(*)(const char *file, int line, const char *message)
using V8FatalErrorCallback = void(*)(const char *file, int line, const char *message)
using StackState = cppgc::EmbedderStackState
Indicator for the stack state.
template<class T >
using Handle = Local< T >
using MicrotasksCompletedCallbackWithData = void(*)(Isolate *, void *)
using MicrotaskCallback = void(*)(void *data)
using AccessorNameGetterCallback = void(*)(Local< Name > property, const PropertyCallbackInfo< Value > &info)
Accessor[Getter|Setter] are used as callback functions when setting|getting a particular data property.
using AccessorNameSetterCallback = void(*)(Local< Name > property, Local< Value > value, const PropertyCallbackInfo< void > &info)
template<class T >
using UniquePersistent = Global< T >
using PlatformSharedMemoryHandle = intptr_t
using NativeObject = uint16_t void *
using SnapshotObjectId = uint32_t
using ProfilerId = uint32_t
using PromiseHook = void(*)(PromiseHookType type, Local< Promise > promise, Local< Value > parent)
using PromiseRejectCallback = void(*)(PromiseRejectMessage message)
using NamedPropertyGetterCallback = Intercepted(*)(Local< Name > property, const PropertyCallbackInfo< Value > &info)
Interceptor for get requests on an object.
using instead = void(*)(Local< Name > property, const PropertyCallbackInfo< Value > &info)
using NamedPropertySetterCallback = Intercepted(*)(Local< Name > property, Local< Value > value, const PropertyCallbackInfo< void > &info)
Interceptor for set requests on an object.
using NamedPropertyQueryCallback = Intercepted(*)(Local< Name > property, const PropertyCallbackInfo< Integer > &info)
Intercepts all requests that query the attributes of the property, e.g., getOwnPropertyDescriptor(), propertyIsEnumerable(), and defineProperty().
using NamedPropertyDeleterCallback = Intercepted(*)(Local< Name > property, const PropertyCallbackInfo< Boolean > &info)
Interceptor for delete requests on an object.
using NamedPropertyEnumeratorCallback = void(*)(const PropertyCallbackInfo< Array > &info)
Returns an array containing the names of the properties the named property getter intercepts.
using NamedPropertyDefinerCallback = Intercepted(*)(Local< Name > property, const PropertyDescriptor &desc, const PropertyCallbackInfo< void > &info)
Interceptor for defineProperty requests on an object.
using NamedPropertyDescriptorCallback = Intercepted(*)(Local< Name > property, const PropertyCallbackInfo< Value > &info)
Interceptor for getOwnPropertyDescriptor requests on an object.
using IndexedPropertyGetterCallbackV2 = Intercepted(*)(uint32_t index, const PropertyCallbackInfo< Value > &info)
See v8::NamedPropertyGetterCallback.
using IndexedPropertySetterCallbackV2 = Intercepted(*)(uint32_t index, Local< Value > value, const PropertyCallbackInfo< void > &info)
See v8::NamedPropertySetterCallback.
using IndexedPropertyQueryCallbackV2 = Intercepted(*)(uint32_t index, const PropertyCallbackInfo< Integer > &info)
See v8::NamedPropertyQueryCallback.
using IndexedPropertyDeleterCallbackV2 = Intercepted(*)(uint32_t index, const PropertyCallbackInfo< Boolean > &info)
See v8::NamedPropertyDeleterCallback.
using IndexedPropertyEnumeratorCallback = void(*)(const PropertyCallbackInfo< Array > &info)
Returns an array containing the indices of the properties the indexed property getter intercepts.
using IndexedPropertyDefinerCallbackV2 = Intercepted(*)(uint32_t index, const PropertyDescriptor &desc, const PropertyCallbackInfo< void > &info)
See v8::NamedPropertyDefinerCallback.
using IndexedPropertyDescriptorCallbackV2 = Intercepted(*)(uint32_t index, const PropertyCallbackInfo< Value > &info)
See v8::NamedPropertyDescriptorCallback.
using AccessCheckCallback = bool(*)(Local< Context > accessing_context, Local< Object > accessed_object, Local< Value > data)
Returns true if the given context should be allowed to access the given object.
typedef uintptr_t PersistentContainerValue
Enumerations
enum class AddStringConstantAndInternalizeVariant : uint8_t { kLhsIsStringConstant = 0
, kRhsIsStringConstant = 1
 }
enum class JSApiInstanceType : uint16_t {
kGenericApiObject = 0
, kEventTarget
, kNode
, kElement
,
kHTMLElement
, kHTMLDivElement
 }
enum class ModuleType { kJavaScript
, kJSON
, kWebAssembly
, kInvalid
 }
enum class ArrayBufferCreationMode { kInternalized
, kExternalized
 }
enum class BackingStoreInitializationMode { kZeroInitialized
, kUninitialized
 }
enum class BackingStoreOnFailureMode { kReturnNull
, kOutOfMemory
 }
enum JitCodeEventOptions { kJitCodeEventDefault = 0
, kJitCodeEventEnumExisting = 1
, kLastJitCodeEventOption = kJitCodeEventEnumExisting
 }
Option flags passed to the SetJitCodeEventHandler function.
enum GCType {
kGCTypeScavenge = 1 << 0
, kGCTypeMinorMarkSweep = 1 << 1
, kGCTypeMarkSweepCompact = 1 << 2
, kGCTypeIncrementalMarking = 1 << 3
,
kGCTypeProcessWeakCallbacks = 1 << 4
, kGCTypeAll
 }
Applications can register callback functions which will be called before and after certain garbage collection operations.
enum GCCallbackFlags {
kNoGCCallbackFlags = 0
, kGCCallbackFlagConstructRetainedObjectInfos = 1 << 1
, kGCCallbackFlagForced = 1 << 2
, kGCCallbackFlagSynchronousPhantomCallbackProcessing = 1 << 3
,
kGCCallbackFlagCollectAllAvailableGarbage = 1 << 4
, kGCCallbackFlagCollectAllExternalMemory = 1 << 5
, kGCCallbackScheduleIdleGarbageCollection = 1 << 6
 }
GCCallbackFlags is used to notify additional information about the GC callback.
enum LogEventStatus : int { kStart = 0
, kEnd = 1
, kLog = 2
 }
enum class CrashKeyId {
kIsolateAddress
, kReadonlySpaceFirstPageAddress
, V8_ENUM_DEPRECATE_SOON =(`Map space got removed`)
, kOldSpaceFirstPageAddress
,
kCodeRangeBaseAddress
, kCodeSpaceFirstPageAddress
, kDumpType
, kSnapshotChecksumCalculated
,
kSnapshotChecksumExpected
 }
enum AccessType {
ACCESS_GET
, ACCESS_SET
, ACCESS_HAS
, ACCESS_DELETE
,
ACCESS_KEYS
 }
Access type specification.
enum class WasmAsyncSuccess { kSuccess
, kFail
 }
enum class ModuleImportPhase { kSource
, kEvaluation
 }
Import phases in import requests.
enum class EmbedderStateTag : uint8_t { EMPTY = 0
, OTHER = 1
 }
enum class ExceptionContext : uint32_t {
kUnknown
, kConstructor
, kOperation
, kAttributeGet
,
kAttributeSet
, kIndexedQuery
, kIndexedGetter
, kIndexedDescriptor
,
kIndexedSetter
, kIndexedDefiner
, kIndexedDeleter
, kNamedQuery
,
kNamedGetter
, kNamedDescriptor
, kNamedSetter
, kNamedDefiner
,
kNamedDeleter
, kNamedEnumerator
 }
This is a part of experimental Api and might be changed without further notice.
enum class MemoryPressureLevel { kNone
, kModerate
, kCritical
 }
Memory pressure level for the MemoryPressureNotification.
enum class ContextDependants { kNoDependants
, kSomeDependants
 }
Signal for dependants of contexts.
enum class MicrotasksPolicy { kExplicit
, kScoped
, kAuto
 }
Policy for running microtasks:
enum PropertyAttribute { None = 0
, ReadOnly = 1 << 0
, DontEnum = 1 << 1
, DontDelete = 1 << 2
 }
PropertyAttribute.
enum PropertyFilter {
ALL_PROPERTIES = 0
, ONLY_WRITABLE = 1
, ONLY_ENUMERABLE = 2
, ONLY_CONFIGURABLE = 4
,
SKIP_STRINGS = 8
, SKIP_SYMBOLS = 16
 }
Property filter bits.
enum class SideEffectType { kHasSideEffect
, kHasNoSideEffect
, kHasSideEffectToReceiver
 }
Options for marking whether callbacks may trigger JS-observable side effects.
enum class KeyCollectionMode { kOwnOnly
, kIncludePrototypes
 }
Keys/Properties filter enums:
enum class IndexFilter { kIncludeIndices
, kSkipIndices
 }
kIncludesIndices allows for integer indices to be collected, while kSkipIndices will exclude integer indices from being collected.
enum class KeyConversionMode { kConvertToString
, kKeepNumbers
, kNoNumbers
 }
kConvertToString will convert integer indices to strings.
enum class IntegrityLevel { kFrozen
, kSealed
 }
Integrity level for objects.
enum class TaskPriority : uint8_t { kBestEffort
, kUserVisible
, kUserBlocking
, kMaxPriority = kUserBlocking
 }
enum class BlockingType { kMayBlock
, kWillBlock
 }
A `blocking call` refers to any call that causes the calling thread to wait off-CPU.
enum class PagePermissions {
kNoAccess
, kRead
, kReadWrite
, kReadWriteExecute
,
kReadExecute
 }
Possible permissions for memory pages.
enum class NewStringType { kNormal
, kInternalized
 }
A flag describing different modes of string creation.
enum CpuProfilingMode { kLeafNodeLineNumbers
, kCallerLineNumbers
 }
enum CpuProfilingNamingMode { kStandardNaming
, kDebugNaming
 }
enum CpuProfilingLoggingMode { kLazyLogging
, kEagerLogging
 }
enum class CpuProfilingStatus { kStarted
, kAlreadyStarted
, kErrorTooManyProfilers
 }
enum CodeEventType { kUnknownType
 }
Note that this enum may be extended in the future.
enum class PromiseHookType { kInit
, kResolve
, kBefore
, kAfter
 }
PromiseHook with type kInit is called when a new promise is created.
enum PromiseRejectEvent { kPromiseRejectWithNoHandler = 0
, kPromiseHandlerAddedAfterReject = 1
, kPromiseRejectAfterResolved = 2
, kPromiseResolveAfterResolved = 3
 }
enum class CppHeapPointerTag : uint16_t {
kFirstTag = 0
, kNullTag = 0
, kDefaultTag = 0x7000
, kZappedEntryTag = 0x7ffd
,
kEvacuationEntryTag = 0x7ffe
, kFreeEntryTag = 0x7fff
, kLastTag = 0x7fff
 }
A pointer tag used for wrapping and unwrapping CppHeap pointers as used with JS API wrapper objects that rely on v8::Object::Wrap() and v8::Object::Unwrap().
enum class ScriptType { kClassic
, kModule
 }
enum class MeasureMemoryMode { kSummary
, kDetailed
 }
Controls how the default MeasureMemoryDelegate reports the result of the memory measurement to JS.
enum class MeasureMemoryExecution { kDefault
, kEager
, kLazy
 }
Controls how promptly a memory measurement request is executed.
enum Intrinsic
enum class Intercepted : uint8_t { kNo = 0
, kYes = 1
 }
Interceptor callbacks use this value to indicate whether the request was intercepted or not.
enum class ConstructorBehavior { kThrow
, kAllow
 }
enum class PropertyHandlerFlags {
kNone = 0
, kNonMasking = 1
, kOnlyInterceptStrings = 1 << 1
, kHasNoSideEffect = 1 << 2
,
kInternalNewCallbacksSignatures = 1 << 10
 }
Configuration flags for v8::NamedPropertyHandlerConfiguration or v8::IndexedPropertyHandlerConfiguration.
enum StateTag : uint16_t {
JS
, GC
, PARSER
, BYTECODE_COMPILER
,
COMPILER
, OTHER
, OTHER = 1
, EXTERNAL
,
ATOMICS_WAIT
, IDLE
, LOGGING
 }
enum PersistentContainerCallbackType { kNotWeak
, kWeakWithParameter
, kWeakWithInternalFields
 }
enum class WeakCallbackType { kParameter
, kInternalFields
 }
Weakness type for weak handles.
Functions
template<typename T , internal::ExternalPointerTag tag>
T ToCData (i::Isolate *isolate, i::Tagged< i::Object > obj)
template<internal::ExternalPointerTag tag>
i::Address ToCData (i::Isolate *isolate, i::Tagged< i::Object > obj)
template<internal::ExternalPointerTag tag, typename T >
i::DirectHandle< i::UnionOf< i::Smi, i::Foreign > > FromCData (i::Isolate *isolate, T obj)
template<internal::ExternalPointerTag tag>
i::DirectHandle< i::UnionOf< i::Smi, i::Foreign > > FromCData (i::Isolate *isolate, i::Address obj)
template<typename T >
void CopySmiElementsToTypedBuffer (T *dst, uint32_t length, i::Tagged< i::FixedArray > elements)
template<typename T >
void CopyDoubleElementsToTypedBuffer (T *dst, uint32_t length, i::Tagged< i::FixedDoubleArray > elements)
template<CTypeInfo::Identifier type_info_id, typename T >
bool CopyAndConvertArrayToCppBuffer (Local< Array > src, T *dst, uint32_t max_length)
template<const CTypeInfo * type_info, typename T >
bool TryCopyAndConvertArrayToCppBuffer (Local< Array > src, T *dst, uint32_t max_length)
template<CTypeInfo::Identifier type_info_id, typename T >
bool TryToCopyAndConvertArrayToCppBuffer (Local< Array > src, T *dst, uint32_t max_length)
Copies the contents of this JavaScript array to a C++ buffer with a given max_length.
static ScriptOrigin GetScriptOriginForScript (i::Isolate *i_isolate, i::DirectHandle< i::Script > script)
void RegisterExtension (std::unique_ptr< Extension > extension)
static i::DirectHandle< i::EmbedderDataArray > EmbedderDataFor (Context *context, int index, bool can_grow, const char *location)
template<typename Getter , typename Setter , typename Data >
static Maybe< bool > ObjectSetAccessor (Local< Context > context, Object *self, Local< Name > name, Getter getter, Setter setter, Data data, PropertyAttribute attributes, bool replace_on_access, SideEffectType getter_side_effect_type, SideEffectType setter_side_effect_type)
static bool Unaligned (const uint16_t *chars)
static const uint16_t * Align (const uint16_t *chars)
template<typename CharType >
static int WriteHelper (i::Isolate *i_isolate, const String *string, CharType *buffer, int start, int length, int options)
template<typename CharType >
static void WriteHelperV2 (i::Isolate *i_isolate, const String *string, CharType *buffer, uint32_t offset, uint32_t length, int flags)
static bool InternalFieldOK (i::DirectHandle< i::JSReceiver > obj, int index, const char *location)
template<typename ObjectType >
static i::DirectHandle< ObjectType > CreateEnvironment (i::Isolate *i_isolate, v8::ExtensionConfiguration *extensions, v8::MaybeLocal< ObjectTemplate > maybe_global_template, v8::MaybeLocal< Value > maybe_global_proxy, size_t context_snapshot_index, i::DeserializeEmbedderFieldsCallback embedder_fields_deserializer, v8::MicrotaskQueue *microtask_queue)
Local< Context > NewContext (v8::Isolate *external_isolate, v8::ExtensionConfiguration *extensions, v8::MaybeLocal< ObjectTemplate > global_template, v8::MaybeLocal< Value > global_object, size_t context_snapshot_index, i::DeserializeEmbedderFieldsCallback embedder_fields_deserializer, v8::MicrotaskQueue *microtask_queue)
REGEXP_FLAG_ASSERT_EQ (kNone)
REGEXP_FLAG_ASSERT_EQ (kGlobal)
REGEXP_FLAG_ASSERT_EQ (kIgnoreCase)
REGEXP_FLAG_ASSERT_EQ (kMultiline)
REGEXP_FLAG_ASSERT_EQ (kSticky)
REGEXP_FLAG_ASSERT_EQ (kUnicode)
REGEXP_FLAG_ASSERT_EQ (kHasIndices)
REGEXP_FLAG_ASSERT_EQ (kLinear)
REGEXP_FLAG_ASSERT_EQ (kUnicodeSets)
static void CallGCCallbackWithoutData (Isolate *v8_isolate, GCType type, GCCallbackFlags flags, void *data)
CALLBACK_SETTER (ModifyCodeGenerationFromStringsCallback, ModifyCodeGenerationFromStringsCallback2, modify_code_gen_callback) CALLBACK_SETTER(AllowWasmCodeGenerationCallback
allow_wasm_code_gen_callback CALLBACK_SETTER (WasmStreamingCallback, WasmStreamingCallback, wasm_streaming_callback) CALLBACK_SETTER(WasmAsyncResolvePromiseCallback
allow_wasm_code_gen_callback wasm_async_resolve_promise_callback CALLBACK_SETTER (WasmLoadSourceMapCallback, WasmLoadSourceMapCallback, wasm_load_source_map_callback) CALLBACK_SETTER(WasmImportedStringsEnabledCallback
allow_wasm_code_gen_callback wasm_async_resolve_promise_callback wasm_imported_strings_enabled_callback CALLBACK_SETTER (WasmJSPIEnabledCallback, WasmJSPIEnabledCallback, wasm_jspi_enabled_callback) CALLBACK_SETTER(SharedArrayBufferConstructorEnabledCallback
allow_wasm_code_gen_callback wasm_async_resolve_promise_callback wasm_imported_strings_enabled_callback sharedarraybuffer_constructor_enabled_callback CALLBACK_SETTER (IsJSApiWrapperNativeErrorCallback, IsJSApiWrapperNativeErrorCallback, is_js_api_wrapper_native_error_callback) void Isolate
static i::CpuProfile * ToInternal (const CpuProfile *profile)
static i::HeapGraphEdge * ToInternal (const HeapGraphEdge *edge)
static i::HeapEntry * ToInternal (const HeapGraphNode *entry)
static i::HeapSnapshot * ToInternal (const HeapSnapshot *snapshot)
template<class T >
v8::Local< T > ToApiHandle (i::DirectHandle< i::Object > obj)
ASSERT_TRIVIALLY_COPYABLE (api_internal::IndirectHandleBase)
ASSERT_TRIVIALLY_COPYABLE (LocalBase< Object >)
ASSERT_TRIVIALLY_COPYABLE (Local< Object >)
ASSERT_TRIVIALLY_COPYABLE (internal::LocalUnchecked< Object >)
ASSERT_TRIVIALLY_COPYABLE (MaybeLocal< Object >)
std::unique_ptr< Platform > MakePredictablePlatform (std::unique_ptr< Platform > platform)
std::unique_ptr< Platform > MakeDelayedTasksPlatform (std::unique_ptr< Platform > platform, int64_t random_seed)
static int LengthWithoutIncompleteUtf8 (char *buffer, int len)
static bool WaitOnFD (int fd, int read_timeout, int total_timeout, const struct timeval &start_time)
static bool TimeIsOut (const struct timeval &start_time, const int &total_time)
static bool GetTimeouts (const v8::FunctionCallbackInfo< v8::Value > &info, int *read_timeout, int *total_timeout)
static void ExecSubprocess (int *exec_error_fds, int *stdout_fds, const ExecArgs &exec_args)
static bool ChildLaunchedOK (Isolate *isolate, int *exec_error_fds)
static Local< Value > GetStdout (Isolate *isolate, int child_fd, const struct timeval &start_time, int read_timeout, int total_timeout)
static bool WaitForChild (Isolate *isolate, int pid, ZombieProtector &child_waiter, const struct timeval &start_time, int read_timeout, int total_timeout)
static bool CheckItsADirectory (Isolate *isolate, char *directory)
static bool mkdirp (Isolate *isolate, char *directory, mode_t mask)
void CreateFastCAPIObject (const FunctionCallbackInfo< Value > &info)
void CreateLeafInterfaceObject (const FunctionCallbackInfo< Value > &info)
void WriteToFile (FILE *file, const v8::FunctionCallbackInfo< v8::Value > &info, int first_arg_index=0)
void WriteAndFlush (FILE *file, const v8::FunctionCallbackInfo< v8::Value > &info)
Local< FunctionTemplate > NewDOMFunctionTemplate (Isolate *isolate, JSApiInstanceType instance_type)
static void PrintMessageCallback (Local< Message > message, Local< Value > error)
void Dummy (char *arg)
bool ends_with (const char *input, const char *suffix)
void GetCalleeSavedRegistersFromEntryFrame (void *fp, RegisterState *register_state)
i::Address Load (i::Address address)
static i::DirectHandle< i::FunctionTemplateInfo > NewFunctionTemplate (i::Isolate *i_isolate, FunctionCallback func, bool has_prototype, SideEffectType side_effect_type=SideEffectType::kHasSideEffect)
static i::DirectHandle< i::ObjectTemplateInfo > NewObjectTemplate (i::Isolate *i_isolate)
template<CTypeInfo::Identifier type_info_id, typename T >
bool V8_WARN_UNUSED_RESULT TryToCopyAndConvertArrayToCppBuffer (Local< Array > src, T *dst, uint32_t max_length)
Copies the contents of this JavaScript array to a C++ buffer with a given max_length.
template<class T >
constexpr Maybe< T > Nothing ()
template<class T >
Maybe< T > Just (const T &t)
template<class T , std::enable_if_t<!std::is_lvalue_reference_v< T >> * = nullptr>
Maybe< T > Just (T &&t)
Maybe< void > JustVoid ()
template<class T , std::size_t N>
constexpr std::array< std::remove_cv_t< T >, N > to_array (T(&a)[N])
template<class T , std::size_t N>
constexpr std::array< std::remove_cv_t< T >, N > to_array (T(&&a)[N])
PlatformSharedMemoryHandle SharedMemoryHandleFromFileDescriptor (int fd)
int FileDescriptorFromSharedMemoryHandle (PlatformSharedMemoryHandle handle)
Local< Primitive > Undefined (Isolate *isolate)
Local< Primitive > Null (Isolate *isolate)
Local< Boolean > True (Isolate *isolate)
Local< Boolean > False (Isolate *isolate)
constexpr CppHeapPointerTagRange kAnyCppHeapPointer (CppHeapPointerTag::kFirstTag, CppHeapPointerTag::kLastTag)
bool operator== (const TracedReferenceBase &lhs, const TracedReferenceBase &rhs)
template<typename U >
bool operator== (const TracedReferenceBase &lhs, const v8::Local< U > &rhs)
template<typename U >
bool operator== (const v8::Local< U > &lhs, const TracedReferenceBase &rhs)
bool operator!= (const TracedReferenceBase &lhs, const TracedReferenceBase &rhs)
template<typename U >
bool operator!= (const TracedReferenceBase &lhs, const v8::Local< U > &rhs)
template<typename U >
bool operator!= (const v8::Local< U > &lhs, const TracedReferenceBase &rhs)
constexpr uint32_t CurrentValueSerializerFormatVersion ()
bool TryHandleWebAssemblyTrapPosix (int sig_code, siginfo_t *info, void *context)
This function determines whether a memory access violation has been an out-of-bounds memory access in WebAssembly.
bool TryHandleWebAssemblyTrapWindows (EXCEPTION_POINTERS *exception)
This function determines whether a memory access violation has been an out-of-bounds memory access in WebAssembly.
Variables
static OOMErrorCallback g_oom_error_callback = nullptr
static const uintptr_t kOneByteMask = OneByteMask<sizeof(uintptr_t)>::value
static const uintptr_t kAlignmentMask = sizeof(uintptr_t) - 1
else
static constexpr AcquireLoadTag kAcquireLoad
static constexpr RelaxedLoadTag kRelaxedLoad
static constexpr ReleaseStoreTag kReleaseStore
static constexpr RelaxedStoreTag kRelaxedStore
static constexpr SeqCstAccessTag kSeqCstAccess
static constexpr int kAdd_StringConstant_Internalize_CacheSlotOffset = 1
constexpr Isolate * kProcessGlobalPredictablePlatformWorkerTaskQueue = nullptr
static const int kReadFD = 0
static const int kWriteFD = 1
bool check_d8_flag_contradictions = true
static v8::debug::DebugDelegate dummy_delegate
static constexpr CTypeInfo kTypeInfoInt32 = CTypeInfo(CTypeInfo::Type::kInt32)
static constexpr CTypeInfo kTypeInfoFloat64
static constexpr PlatformSharedMemoryHandle kInvalidSharedMemoryHandle = -1
static const uintptr_t kPersistentContainerNotFound = 0
static constexpr int kInternalFieldsInWeakCallback = 2
static constexpr int kEmbedderFieldsInWeakCallback = 2
Detailed Description
This file provides additional API on top of the default one for making API calls, which come from embedder C++ functions.
Compile-time constants.
Support for Persistent containers.
Profiler support for the V8 JavaScript engine.
The v8 JavaScript engine.
The functions are being called directly from optimized code, doing all the necessary typechecks in the compiler itself, instead of on the embedder side. Hence the `fast` in the name. Example usage might look like:
void FastMethod(int param, bool another_param);
v8::FunctionTemplate::New(isolate, SlowCallback, data,
                          signature, length, constructor_behavior
                          side_effect_type,
                          &v8::CFunction::Make(FastMethod));
By design, fast calls are limited by the following requirements, which the embedder should enforce themselves:
they should not allocate on the JS heap;
they should not trigger JS execution. To enforce them, the embedder could use the existing v8::Isolate::DisallowJavascriptExecutionScope and a utility similar to Blink's NoAllocationScope: https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/platform/heap/thread_state_scopes.h;l=16
Due to these limitations, it's not directly possible to report errors by throwing a JS exception or to otherwise do an allocation. There is an alternative way of creating fast calls that supports falling back to the slow call and then performing the necessary allocation. When one creates the fast method by using CFunction::MakeWithFallbackSupport instead of CFunction::Make, the fast callback gets as last parameter an output variable, through which it can request falling back to the slow call. So one might declare their method like:
void FastMethodWithFallback(int param, FastApiCallbackOptions& options);
If the callback wants to signal an error condition or to perform an allocation, it must set options.fallback to true and do an early return from the fast method. Then V8 checks the value of options.fallback and if it's true, falls back to executing the SlowCallback, which is capable of reporting the error (either by throwing a JS exception or logging to the console) or doing the allocation. It's the embedder's responsibility to ensure that the fast callback is idempotent up to the point where error and fallback conditions are checked, because otherwise executing the slow callback might produce visible side-effects twice.
An example for custom embedder type support might employ a way to wrap/ unwrap various C++ types in JSObject instances, e.g:
// Helper method with a check for field count.
template <typename T, int offset>
inline T* GetInternalField(v8::Local<v8::Object> wrapper) {
  assert(offset < wrapper->InternalFieldCount());
  return reinterpret_cast<T*>(
      wrapper->GetAlignedPointerFromInternalField(offset));
}
class CustomEmbedderType {
 public:
  // Returns the raw C object from a wrapper JS object.
  static CustomEmbedderType* Unwrap(v8::Local<v8::Object> wrapper) {
    return GetInternalField<CustomEmbedderType,
                            kV8EmbedderWrapperObjectIndex>(wrapper);
  }
  static void FastMethod(v8::Local<v8::Object> receiver_obj, int param) {
    CustomEmbedderType* receiver = static_cast<CustomEmbedderType*>(
      receiver_obj->GetAlignedPointerFromInternalField(
        kV8EmbedderWrapperObjectIndex));
    // Type checks are already done by the optimized code.
    // Then call some performance-critical method like:
    // receiver->Method(param);
  }
  static void SlowMethod(
      const v8::FunctionCallbackInfo<v8::Value>& info) {
    v8::Local<v8::Object> instance =
      v8::Local<v8::Object>::Cast(info.Holder());
    CustomEmbedderType* receiver = Unwrap(instance);
    // TODO: Do type checks and extract {param}.
    receiver->Method(param);
  }
};
// TODO(mslekova): Clean-up these constants
// The constants kV8EmbedderWrapperTypeIndex and
// kV8EmbedderWrapperObjectIndex describe the offsets for the type info
// struct and the native object, when expressed as internal field indices
// within a JSObject. The existance of this helper function assumes that
// all embedder objects have their JSObject-side type info at the same
// offset, but this is not a limitation of the API itself. For a detailed
// use case, see the third example.
static constexpr int kV8EmbedderWrapperTypeIndex = 0;
static constexpr int kV8EmbedderWrapperObjectIndex = 1;
// The following setup function can be templatized based on
// the {embedder_object} argument.
void SetupCustomEmbedderObject(v8::Isolate* isolate,
                               v8::Local<v8::Context> context,
                               CustomEmbedderType* embedder_object) {
  isolate->set_embedder_wrapper_type_index(
    kV8EmbedderWrapperTypeIndex);
  isolate->set_embedder_wrapper_object_index(
    kV8EmbedderWrapperObjectIndex);
  v8::CFunction c_func =
    MakeV8CFunction(CustomEmbedderType::FastMethod);
  Local<v8::FunctionTemplate> method_template =
    v8::FunctionTemplate::New(
      isolate, CustomEmbedderType::SlowMethod, v8::Local<v8::Value>(),
      v8::Local<v8::Signature>(), 1, v8::ConstructorBehavior::kAllow,
      v8::SideEffectType::kHasSideEffect, &c_func);
  v8::Local<v8::ObjectTemplate> object_template =
    v8::ObjectTemplate::New(isolate);
  object_template->SetInternalFieldCount(
    kV8EmbedderWrapperObjectIndex + 1);
  object_template->Set(isolate, "method", method_template);
  // Instantiate the wrapper JS object.
  v8::Local<v8::Object> object =
      object_template->NewInstance(context).ToLocalChecked();
  object->SetAlignedPointerInInternalField(
    kV8EmbedderWrapperObjectIndex,
    reinterpret_cast<void*>(embedder_object));
  // TODO: Expose {object} where it's necessary.
}
For instance if {object} is exposed via a global `obj` variable, one could write in JS: function hot_func() { obj.method(42); } and once {hot_func} gets optimized, CustomEmbedderType::FastMethod will be called instead of the slow version, with the following arguments: receiver := the {embedder_object} from above param := 42
Currently supported return types:
void
bool
int32_t
uint32_t
float32_t
float64_t Currently supported argument types:
pointer to an embedder type
JavaScript array of primitive types
bool
int32_t
uint32_t
int64_t
uint64_t
float32_t
float64_t
The 64-bit integer types currently have the IDL (unsigned) long long semantics: https://heycam.github.io/webidl/#abstract-opdef-converttoint In the future we'll extend the API to also provide conversions from/to BigInt to preserve full precision. The floating point types currently have the IDL (unrestricted) semantics, which is the only one used by WebGL. We plan to add support also for restricted floats/doubles, similarly to the BigInt conversion policies. We also differ from the specific NaN bit pattern that WebIDL prescribes (https://heycam.github.io/webidl/#es-unrestricted-float) in that Blink passes NaN values as-is, i.e. doesn't normalize them.
To be supported types:
TypedArrays and ArrayBuffers
arrays of embedder types
The API offers a limited support for function overloads:
void FastMethod_2Args(int param, bool another_param);
void FastMethod_3Args(int param, bool another_param, int third_param);
v8::CFunction fast_method_2args_c_func =
     MakeV8CFunction(FastMethod_2Args);
v8::CFunction fast_method_3args_c_func =
     MakeV8CFunction(FastMethod_3Args);
const v8::CFunction fast_method_overloads[] = {fast_method_2args_c_func,
                                               fast_method_3args_c_func};
Local<v8::FunctionTemplate> method_template =
    v8::FunctionTemplate::NewWithCFunctionOverloads(
        isolate, SlowCallback, data, signature, length,
        constructor_behavior, side_effect_type,
        {fast_method_overloads, 2});
In this example a single FunctionTemplate is associated to multiple C++ functions. The overload resolution is currently only based on the number of arguments passed in a call. For example, if this method_template is registered with a wrapper JS object as described above, a call with two arguments: obj.method(42, true); will result in a fast call to FastMethod_2Args, while a call with three or more arguments: obj.method(42, true, 11); will result in a fast call to FastMethod_3Args. Instead a call with less than two arguments, like: obj.method(42); would not result in a fast call but would fall back to executing the associated SlowCallback.
C++11 embedders can use STL containers with Global values, but pre-C++11 does not support the required move semantic and hence may want these container classes.
This header provides access to information about the value serializer at compile time, without declaring or defining any symbols that require linking to V8.
Typedef Documentation
AccessCheckCallback
using v8::AccessCheckCallback = typedef bool (*)(Local<Context> accessing_context, Local<Object> accessed_object, Local<Value> data)
Returns true if the given context should be allowed to access the given object.
Definition at line 471 of file v8-template.h.
AccessorNameGetterCallback
using v8::AccessorNameGetterCallback = typedef void (*)(Local<Name> property, const PropertyCallbackInfo<Value>& info)
Accessor[Getter|Setter] are used as callback functions when setting|getting a particular data property.
See Object::SetNativeDataProperty and ObjectTemplate::SetNativeDataProperty methods.
Definition at line 157 of file v8-object.h.
AccessorNameSetterCallback
using v8::AccessorNameSetterCallback = typedef void (*)(Local<Name> property, Local<Value> value, const PropertyCallbackInfo<void>& info)
Definition at line 160 of file v8-object.h.
AddCrashKeyCallback
using v8::AddCrashKeyCallback = typedef void (*)(CrashKeyId id, const std::string& value)
Definition at line 256 of file v8-callbacks.h.
AddHistogramSampleCallback
using v8::AddHistogramSampleCallback = typedef void (*)(void* histogram, int sample)
Definition at line 221 of file v8-callbacks.h.
AllowWasmCodeGenerationCallback
v8::AllowWasmCodeGenerationCallback
Definition at line 303 of file v8-callbacks.h.
ApiImplementationCallback
using v8::ApiImplementationCallback = typedef void (*)(const FunctionCallbackInfo<Value>&)
Definition at line 308 of file v8-callbacks.h.
async_id_t
using v8::async_id_t = typedef double
Definition at line 22 of file async-hooks-wrapper.h.
BackingStoreDeleterCallback
using v8::BackingStoreDeleterCallback = typedef void (*)(void* data, size_t length, void* deleter_data)
Definition at line 123 of file v8-array-buffer.h.
BeforeCallEnteredCallback
using v8::BeforeCallEnteredCallback = typedef void (*)(Isolate*)
Definition at line 259 of file v8-callbacks.h.
CallCompletedCallback
using v8::CallCompletedCallback = typedef void (*)(Isolate*)
Definition at line 260 of file v8-callbacks.h.
CFunctionBuilder
using v8::CFunctionBuilder = typedef internal::CFunctionBuilder
Definition at line 768 of file v8-fast-api-calls.h.
CompileHintCallback
using v8::CompileHintCallback = typedef bool (*)(int, void*)
Callback for requesting a compile hint for a function from the embedder.
The first parameter is the position of the function in source code and the second parameter is embedder data to be passed back.
Definition at line 419 of file v8-callbacks.h.
CounterLookupCallback
using v8::CounterLookupCallback = typedef int* (*)(const char* name)
Callback function passed to SetUnhandledExceptionCallback.
Definition at line 216 of file v8-callbacks.h.
CounterMap
using v8::CounterMap = typedef std::unordered_map<std::string, Counter*>
Definition at line 86 of file d8.h.
CreateHistogramCallback
using v8::CreateHistogramCallback = typedef void* (*)(const char* name, int min, int max, size_t buckets)
Definition at line 218 of file v8-callbacks.h.
DcheckErrorCallback
using v8::DcheckErrorCallback = typedef void (*)(const char* file, int line, const char* message)
Definition at line 52 of file v8-initialization.h.
EntropySource
using v8::EntropySource = typedef bool (*)(unsigned char* buffer, size_t length)
EntropySource is used as a callback function when v8 needs a source of entropy.
Definition at line 34 of file v8-initialization.h.
ExceptionPropagationCallback
using v8::ExceptionPropagationCallback = typedef void (*)(ExceptionPropagationMessage message)
Definition at line 132 of file v8-exception.h.
ExtensionCallback
using v8::ExtensionCallback = typedef bool (*)(const FunctionCallbackInfo<Value>&)
Definition at line 301 of file v8-callbacks.h.
FailedAccessCheckCallback
using v8::FailedAccessCheckCallback = typedef void (*)(Local<Object> target, AccessType type, Local<Value> data)
Definition at line 297 of file v8-callbacks.h.
FatalErrorCallback
using v8::FatalErrorCallback = typedef void (*)(const char* location, const char* message)
Definition at line 225 of file v8-callbacks.h.
FunctionCallback
using v8::FunctionCallback = typedef void (*)(const FunctionCallbackInfo<Value>& info)
Definition at line 314 of file v8-function-callback.h.
GCCallback
using v8::GCCallback = typedef void (*)(GCType type, GCCallbackFlags flags)
Definition at line 189 of file v8-callbacks.h.
Handle
template<class T >
using v8::Handle = typedef Local<T>
Definition at line 651 of file v8-local-handle.h.
HostCreateShadowRealmContextCallback
using v8::HostCreateShadowRealmContextCallback = typedef MaybeLocal<Context> (*)(Local<Context> initiator_context)
HostCreateShadowRealmContextCallback is called each time a ShadowRealm is being constructed in the initiator_context.
The method combines Context creation and implementation defined abstract operation HostInitializeShadowRealm into one.
The embedder should use v8::Context::New or v8::Context:NewFromSnapshot to create a new context. If the creation fails, the embedder must propagate that exception by returning an empty MaybeLocal.
Definition at line 446 of file v8-callbacks.h.
HostImportModuleDynamicallyCallback
using v8::HostImportModuleDynamicallyCallback = typedef MaybeLocal<Promise> (*)(Local<Context> context, Local<Data> host_defined_options, Local<Value> resource_name, Local<String> specifier, Local<FixedArray> import_attributes)
HostImportModuleDynamicallyCallback is called when we require the embedder to load a module.
This is used as part of the dynamic import syntax.
The referrer contains metadata about the script/module that calls import.
The specifier is the name of the module that should be imported.
The import_attributes are import attributes for this request in the form: [key1, value1, key2, value2, ...] where the keys and values are of type v8::String. Note, unlike the FixedArray passed to ResolveModuleCallback and returned from ModuleRequest::GetImportAttributes(), this array does not contain the source Locations of the attributes.
The embedder must compile, instantiate, evaluate the Module, and obtain its namespace object.
The Promise returned from this function is forwarded to userland JavaScript. The embedder must resolve this promise with the module namespace object. In case of an exception, the embedder must reject this promise with the exception. If the promise creation itself fails (e.g. due to stack overflow), the embedder must propagate that exception by returning an empty MaybeLocal.
Definition at line 368 of file v8-callbacks.h.
HostImportModuleWithPhaseDynamicallyCallback
using v8::HostImportModuleWithPhaseDynamicallyCallback = typedef MaybeLocal<Promise> (*)(Local<Context> context, Local<Data> host_defined_options, Local<Value> resource_name, Local<String> specifier, ModuleImportPhase phase, Local<FixedArray> import_attributes)
HostImportModuleWithPhaseDynamicallyCallback is called when we require the embedder to load a module with a specific phase.
This is used as part of the dynamic import syntax.
The referrer contains metadata about the script/module that calls import.
The specifier is the name of the module that should be imported.
The phase is the phase of the import requested.
The import_attributes are import attributes for this request in the form: [key1, value1, key2, value2, ...] where the keys and values are of type v8::String. Note, unlike the FixedArray passed to ResolveModuleCallback and returned from ModuleRequest::GetImportAttributes(), this array does not contain the source Locations of the attributes.
The Promise returned from this function is forwarded to userland JavaScript. The embedder must resolve this promise according to the phase requested:
For ModuleImportPhase::kSource, the promise must be resolved with a compiled ModuleSource object, or rejected with a SyntaxError if the module does not support source representation.
For ModuleImportPhase::kEvaluation, the promise must be resolved with a ModuleNamespace object of a module that has been compiled, instantiated, and evaluated.
In case of an exception, the embedder must reject this promise with the exception. If the promise creation itself fails (e.g. due to stack overflow), the embedder must propagate that exception by returning an empty MaybeLocal.
This callback is still experimental and is only invoked for source phase imports.
Definition at line 409 of file v8-callbacks.h.
HostInitializeImportMetaObjectCallback
using v8::HostInitializeImportMetaObjectCallback = typedef void (*)(Local<Context> context, Local<Module> module, Local<Object> meta)
HostInitializeImportMetaObjectCallback is called the first time import.meta is accessed for a module.
Subsequent access will reuse the same value.
The method combines two implementation-defined abstract operations into one: HostGetImportMetaProperties and HostFinalizeImportMeta.
The embedder should use v8::Object::CreateDataProperty to add properties on the meta object.
Definition at line 431 of file v8-callbacks.h.
IndexedPropertyDefinerCallbackV2
using v8::IndexedPropertyDefinerCallbackV2 = typedef Intercepted (*)(uint32_t index, const PropertyDescriptor& desc, const PropertyCallbackInfo<void>& info)
See v8::NamedPropertyDefinerCallback.
Definition at line 448 of file v8-template.h.
IndexedPropertyDeleterCallbackV2
using v8::IndexedPropertyDeleterCallbackV2 = typedef Intercepted (*)(uint32_t index, const PropertyCallbackInfo<Boolean>& info)
See v8::NamedPropertyDeleterCallback.
Definition at line 429 of file v8-template.h.
IndexedPropertyDescriptorCallbackV2
using v8::IndexedPropertyDescriptorCallbackV2 = typedef Intercepted (*)(uint32_t index, const PropertyCallbackInfo<Value>& info)
See v8::NamedPropertyDescriptorCallback.
Definition at line 460 of file v8-template.h.
IndexedPropertyEnumeratorCallback
using v8::IndexedPropertyEnumeratorCallback = typedef void (*)(const PropertyCallbackInfo<Array>& info)
Returns an array containing the indices of the properties the indexed property getter intercepts.
Note: The values in the array must be uint32_t.
Definition at line 442 of file v8-template.h.
IndexedPropertyGetterCallbackV2
using v8::IndexedPropertyGetterCallbackV2 = typedef Intercepted (*)(uint32_t index, const PropertyCallbackInfo<Value>& info)
See v8::NamedPropertyGetterCallback.
Definition at line 398 of file v8-template.h.
IndexedPropertyQueryCallbackV2
using v8::IndexedPropertyQueryCallbackV2 = typedef Intercepted (*)(uint32_t index, const PropertyCallbackInfo<Integer>& info)
See v8::NamedPropertyQueryCallback.
Definition at line 419 of file v8-template.h.
IndexedPropertySetterCallbackV2
using v8::IndexedPropertySetterCallbackV2 = typedef Intercepted (*)(uint32_t index, Local<Value> value, const PropertyCallbackInfo<void>& info)
See v8::NamedPropertySetterCallback.
Definition at line 408 of file v8-template.h.
instead
typedef void(* v8::instead)(uint32_t index, const PropertyCallbackInfo< Value > &info)
Definition at line 192 of file v8-template.h.
InterruptCallback
using v8::InterruptCallback = typedef void (*)(Isolate* isolate, void* data)
Definition at line 191 of file v8-callbacks.h.
IsJSApiWrapperNativeErrorCallback
using v8::IsJSApiWrapperNativeErrorCallback = typedef bool (*)(Isolate* isolate, Local<Object> obj)
IsJSApiWrapperNativeErrorCallback is called on an JSApiWrapper object to determine if Error.isError should return true or false.
For instance, in an HTML embedder, DOMExceptions return true when passed to Error.isError.
Definition at line 454 of file v8-callbacks.h.
JitCodeEventHandler
using v8::JitCodeEventHandler = typedef void (*)(const JitCodeEvent* event)
Callback function passed to SetJitCodeEventHandler.
Parameters
event code add, move or removal event.
Definition at line 142 of file v8-callbacks.h.
LogEventCallback
using v8::LogEventCallback = typedef void (*)(const char* name, int status)
Definition at line 240 of file v8-callbacks.h.
MessageCallback
using v8::MessageCallback = typedef void (*)(Local<Message> message, Local<Value> data)
Definition at line 235 of file v8-callbacks.h.
MicrotaskCallback
using v8::MicrotaskCallback = typedef void (*)(void* data)
Definition at line 14 of file v8-microtask.h.
MicrotasksCompletedCallbackWithData
using v8::MicrotasksCompletedCallbackWithData = typedef void (*)(Isolate*, void*)
Definition at line 13 of file v8-microtask.h.
ModifyCodeGenerationFromStringsCallback
using v8::ModifyCodeGenerationFromStringsCallback = typedef ModifyCodeGenerationFromStringsResult (*)(Local<Context> context, Local<Value> source)
Callback to check if codegen is allowed from a source object, and convert the source to string if necessary.
See: ModifyCodeGenerationFromStrings.
Definition at line 276 of file v8-callbacks.h.
ModifyCodeGenerationFromStringsCallback2
using v8::ModifyCodeGenerationFromStringsCallback2 = typedef ModifyCodeGenerationFromStringsResult (*)(Local<Context> context, Local<Value> source, bool is_code_like)
Definition at line 279 of file v8-callbacks.h.
NamedPropertyDefinerCallback
using v8::NamedPropertyDefinerCallback = typedef Intercepted (*)(Local<Name> property, const PropertyDescriptor& desc, const PropertyCallbackInfo<void>& info)
Interceptor for defineProperty requests on an object.
If the interceptor handles the request (i.e. the property should not be looked up beyond the interceptor or in case an exception was thrown) it should return Intercepted::kYes. If the interceptor does not handle the request it must return Intercepted::kNo and it must not produce side effects.
Parameters
property The name of the property for which the request was intercepted.
desc The property descriptor which is used to define the property if the request is not intercepted.
info Information about the intercepted request, such as isolate, receiver, return value, or whether running in `'use strict'mode. SeePropertyCallbackInfo.
See also ObjectTemplate::SetHandler.
Definition at line 339 of file v8-template.h.
NamedPropertyDeleterCallback
using v8::NamedPropertyDeleterCallback = typedef Intercepted (*)(Local<Name> property, const PropertyCallbackInfo<Boolean>& info)
Interceptor for delete requests on an object.
If the interceptor handles the request (i.e. the property should not be looked up beyond the interceptor or in case an exception was thrown) it should
(optionally) use info.GetReturnValue().Set() to set to a Boolean value indicating whether the property deletion was successful or not,
return Intercepted::kYes. If the interceptor does not handle the request it must return Intercepted::kNo and it must not produce side effects.
Parameters
property The name of the property for which the request was intercepted.
info Information about the intercepted request, such as isolate, receiver, return value, or whether running in `'use strict'mode. SeePropertyCallbackInfo.
Note
If you need to mimic the behavior of delete, i.e., throw in strict mode instead of returning false, use info.ShouldThrowOnError() to determine if you are in strict mode.
See also ObjectTemplate::SetHandler.
Definition at line 292 of file v8-template.h.
NamedPropertyDescriptorCallback
using v8::NamedPropertyDescriptorCallback = typedef Intercepted (*)(Local<Name> property, const PropertyCallbackInfo<Value>& info)
Interceptor for getOwnPropertyDescriptor requests on an object.
If the interceptor handles the request (i.e. the property should not be looked up beyond the interceptor or in case an exception was thrown) it should
(optionally) use info.GetReturnValue().Set() to set the return value which must be object that can be converted to a PropertyDescriptor (for example, a value returned by v8::Object::getOwnPropertyDescriptor),
return Intercepted::kYes. If the interceptor does not handle the request it must return Intercepted::kNo and it must not produce side effects.
Parameters
property The name of the property for which the request was intercepted. \info Information about the intercepted request, such as isolate, receiver, return value, or whether running in `'use strict'mode. SeePropertyCallbackInfo.
Note
If GetOwnPropertyDescriptor is intercepted, it will always return true, i.e., indicate that the property was found.
See also ObjectTemplate::SetHandler.
Definition at line 379 of file v8-template.h.
NamedPropertyEnumeratorCallback
using v8::NamedPropertyEnumeratorCallback = typedef void (*)(const PropertyCallbackInfo<Array>& info)
Returns an array containing the names of the properties the named property getter intercepts.
Note: The values in the array must be of type v8::Name.
Definition at line 312 of file v8-template.h.
NamedPropertyGetterCallback
using v8::NamedPropertyGetterCallback = typedef Intercepted (*)(Local<Name> property, const PropertyCallbackInfo<Value>& info)
Interceptor for get requests on an object.
If the interceptor handles the request (i.e. the property should not be looked up beyond the interceptor or in case an exception was thrown) it should
(optionally) use info.GetReturnValue().Set() to set the return value (by default the result is set to v8::Undefined),
return Intercepted::kYes. If the interceptor does not handle the request it must return Intercepted::kNo and it must not produce side effects.
Parameters
property The name of the property for which the request was intercepted.
info Information about the intercepted request, such as isolate, receiver, return value, or whether running in `'use strict'mode. SeePropertyCallbackInfo.
Intercepted GetterCallback(
    Local<Name> name, const v8::PropertyCallbackInfo<v8::Value>& info) {
  if (!IsKnownProperty(info.GetIsolate(), name)) return Intercepted::kNo;
  info.GetReturnValue().Set(v8_num(42));
  return Intercepted::kYes;
}
v8::Local<v8::FunctionTemplate> templ =
    v8::FunctionTemplate::New(isolate);
templ->InstanceTemplate()->SetHandler(
    v8::NamedPropertyHandlerConfiguration(GetterCallback));
LocalContext env;
env->Global()
    ->Set(env.local(), v8_str("obj"), templ->GetFunction(env.local())
                                           .ToLocalChecked()
                                           ->NewInstance(env.local())
                                           .ToLocalChecked())
    .FromJust();
v8::Local<v8::Value> result = CompileRun("obj.a = 17; obj.a");
CHECK(v8_num(42)->Equals(env.local(), result).FromJust());
See also ObjectTemplate::SetHandler.
Definition at line 184 of file v8-template.h.
NamedPropertyQueryCallback
using v8::NamedPropertyQueryCallback = typedef Intercepted (*)(Local<Name> property, const PropertyCallbackInfo<Integer>& info)
Intercepts all requests that query the attributes of the property, e.g., getOwnPropertyDescriptor(), propertyIsEnumerable(), and defineProperty().
If the interceptor handles the request (i.e. the property should not be looked up beyond the interceptor or in case an exception was thrown) it should
(optionally) use info.GetReturnValue().Set() to set to an Integer value encoding a v8::PropertyAttribute bits,
return Intercepted::kYes. If the interceptor does not handle the request it must return Intercepted::kNo and it must not produce side effects.
Parameters
property The name of the property for which the request was intercepted.
info Information about the intercepted request, such as isolate, receiver, return value, or whether running in `'use strict'mode. SeePropertyCallbackInfo.
Note
Some functions query the property attributes internally, even though they do not return the attributes. For example, hasOwnProperty() can trigger this interceptor depending on the state of the object.
See also ObjectTemplate::SetHandler.
Definition at line 256 of file v8-template.h.
NamedPropertySetterCallback
using v8::NamedPropertySetterCallback = typedef Intercepted (*)(Local<Name> property, Local<Value> value, const PropertyCallbackInfo<void>& info)
Interceptor for set requests on an object.
If the interceptor handles the request (i.e. the property should not be looked up beyond the interceptor or in case an exception was thrown) it should return Intercepted::kYes. If the interceptor does not handle the request it must return Intercepted::kNo and it must not produce side effects.
Parameters
property The name of the property for which the request was intercepted.
value The value which the property will have if the request is not intercepted.
info Information about the intercepted request, such as isolate, receiver, return value, or whether running in `'use strict'mode. SeePropertyCallbackInfo.
See also ObjectTemplate::SetHandler.
Definition at line 214 of file v8-template.h.
NativeObject
using v8::NativeObject = typedef uint16_t void*
Definition at line 30 of file v8-profiler.h.
NearHeapLimitCallback
using v8::NearHeapLimitCallback = typedef size_t (*)(void* data, size_t current_heap_limit, size_t initial_heap_limit)
This callback is invoked when the heap size is close to the heap limit and V8 is likely to abort with out-of-memory error.
The callback can extend the heap limit by returning a value that is greater than the current_heap_limit. The initial heap limit is the limit that was set after heap setup.
Definition at line 203 of file v8-callbacks.h.
OOMErrorCallback
using v8::OOMErrorCallback = typedef void (*)(const char* location, const OOMDetails& details)
Definition at line 232 of file v8-callbacks.h.
PersistentContainerValue
typedef uintptr_t v8::PersistentContainerValue
Definition at line 28 of file v8-util.h.
PlatformSharedMemoryHandle
using v8::PlatformSharedMemoryHandle = typedef intptr_t
Definition at line 708 of file v8-platform.h.
PrepareStackTraceCallback
using v8::PrepareStackTraceCallback = typedef MaybeLocal<Value> (*)(Local<Context> context, Local<Value> error, Local<Array> sites)
PrepareStackTraceCallback is called when the stack property of an error is first accessed.
The return value will be used as the stack value. If this callback is registed, the |Error.prepareStackTrace| API will be disabled. |sites| is an array of call sites, specified in https://v8.dev/docs/stack-trace-api
Definition at line 464 of file v8-callbacks.h.
PrintCurrentStackTraceFilterCallback
using v8::PrintCurrentStackTraceFilterCallback = typedef bool (*)(Isolate* isolate, Local<String> script_name)
Definition at line 193 of file v8-callbacks.h.
ProfilerId
using v8::ProfilerId = typedef uint32_t
Definition at line 32 of file v8-profiler.h.
PromiseHook
using v8::PromiseHook = typedef void (*)(PromiseHookType type, Local<Promise> promise, Local<Value> parent)
Definition at line 143 of file v8-promise.h.
PromiseRejectCallback
using v8::PromiseRejectCallback = typedef void (*)(PromiseRejectMessage message)
Definition at line 170 of file v8-promise.h.
RCCId
using v8::RCCId = typedef i::RuntimeCallCounterId
Definition at line 189 of file api.cc.
ReturnAddressLocationResolver
using v8::ReturnAddressLocationResolver = typedef uintptr_t (*)(uintptr_t return_addr_location)
ReturnAddressLocationResolver is used as a callback function when v8 is resolving the location of a return address on the stack.
Profilers that change the return address on the stack can use this to resolve the stack location to wherever the profiler stashed the original return address.
Parameters
return_addr_location A location on stack where a machine return address resides.
Returns
Either return_addr_location, or else a pointer to the profiler's copy of the original return address.
Note
The resolver function must not cause garbage collection.
Definition at line 49 of file v8-initialization.h.
SharedArrayBufferConstructorEnabledCallback
allow_wasm_code_gen_callback wasm_async_resolve_promise_callback wasm_imported_strings_enabled_callback v8::SharedArrayBufferConstructorEnabledCallback
Definition at line 328 of file v8-callbacks.h.
SnapshotObjectId
using v8::SnapshotObjectId = typedef uint32_t
Definition at line 31 of file v8-profiler.h.
StackState
using v8::StackState = typedef cppgc::EmbedderStackState
Indicator for the stack state.
Definition at line 192 of file v8-isolate.h.
UniquePersistent
template<class T >
using v8::UniquePersistent = typedef Global<T>
Definition at line 411 of file v8-persistent-handle.h.
V8FatalErrorCallback
using v8::V8FatalErrorCallback = typedef void (*)(const char* file, int line, const char* message)
Definition at line 55 of file v8-initialization.h.
WasmAsyncResolvePromiseCallback
allow_wasm_code_gen_callback v8::WasmAsyncResolvePromiseCallback
Definition at line 316 of file v8-callbacks.h.
WasmImportedStringsEnabledCallback
allow_wasm_code_gen_callback wasm_async_resolve_promise_callback v8::WasmImportedStringsEnabledCallback
Definition at line 325 of file v8-callbacks.h.
WasmJSPIEnabledCallback
using v8::WasmJSPIEnabledCallback = typedef bool (*)(Local<Context> context)
Definition at line 332 of file v8-callbacks.h.
WasmLoadSourceMapCallback
using v8::WasmLoadSourceMapCallback = typedef Local<String> (*)(Isolate* isolate, const char* name)
Definition at line 321 of file v8-callbacks.h.
WasmStreamingCallback
using v8::WasmStreamingCallback = typedef void (*)(const FunctionCallbackInfo<Value>&)
Definition at line 311 of file v8-callbacks.h.
Enumeration Type Documentation
AccessType
enum v8::AccessType
Access type specification.
Enumerator
ACCESS_GET
ACCESS_SET
ACCESS_HAS
ACCESS_DELETE
ACCESS_KEYS
Definition at line 289 of file v8-callbacks.h.
                {
  ACCESS_GET,
  ACCESS_SET,
  ACCESS_HAS,
  ACCESS_DELETE,
  ACCESS_KEYS
};
AddStringConstantAndInternalizeVariant
enum v8::AddStringConstantAndInternalizeVariant : uint8_t [strong]
Enumerator
kLhsIsStringConstant
kRhsIsStringConstant
Definition at line 2950 of file globals.h.
                                                  : uint8_t {
  kLhsIsStringConstant = 0,
  kRhsIsStringConstant = 1,
};
ArrayBufferCreationMode
enum v8::ArrayBufferCreationMode [strong]
Enumerator
kInternalized
kExternalized
Definition at line 32 of file v8-array-buffer.h.
{ kInternalized, kExternalized };
BackingStoreInitializationMode
enum v8::BackingStoreInitializationMode [strong]
Enumerator
kZeroInitialized
kUninitialized
Definition at line 33 of file v8-array-buffer.h.
{ kZeroInitialized, kUninitialized };
BackingStoreOnFailureMode
enum v8::BackingStoreOnFailureMode [strong]
Enumerator
kReturnNull
kOutOfMemory
Definition at line 34 of file v8-array-buffer.h.
{ kReturnNull, kOutOfMemory };
BlockingType
enum v8::BlockingType [strong]
A `blocking call` refers to any call that causes the calling thread to wait off-CPU.
It includes but is not limited to calls that wait on synchronous file I/O operations: read or write a file from disk, interact with a pipe or a socket, rename or delete a file, enumerate files in a directory, etc. Acquiring a low contention lock is not considered a blocking call. BlockingType indicates the likelihood that a blocking call will actually block.
Enumerator
kMayBlock
kWillBlock
Definition at line 332 of file v8-platform.h.
                        {
  // The call might block (e.g. file I/O that might hit in memory cache).
  kMayBlock,
  // The call will definitely block (e.g. cache already checked and now pinging
  // server synchronously).
  kWillBlock
};
CodeEventType
enum v8::CodeEventType
Note that this enum may be extended in the future.
Please include a default case if this enum is used in a switch statement.
Enumerator
kUnknownType
Definition at line 1279 of file v8-profiler.h.
                   {
  kUnknownType = 0
#define V(Name) , k##Name##Type
  CODE_EVENTS_LIST(V)
#undef V
};
ConstructorBehavior
enum v8::ConstructorBehavior [strong]
Enumerator
kThrow
kAllow
Definition at line 475 of file v8-template.h.
{ kThrow, kAllow };
ContextDependants
enum v8::ContextDependants [strong]
Signal for dependants of contexts.
Useful for ContextDisposedNotification() to implement different strategies.
Enumerator
kNoDependants Context has no dependants. These are usually top-level contexts.
kSomeDependants Context has some dependants, i.e., it may depend on other contexts. This is usually the case for inner contexts.
Definition at line 181 of file v8-isolate.h.
                             {
  /** Context has no dependants. These are usually top-level contexts. */
  kNoDependants,
  /** Context has some dependants, i.e., it may depend on other contexts. This
     is usually the case for inner contexts. */
  kSomeDependants
};
CppHeapPointerTag
enum v8::CppHeapPointerTag : uint16_t [strong]
A pointer tag used for wrapping and unwrapping CppHeap pointers as used with JS API wrapper objects that rely on v8::Object::Wrap() and v8::Object::Unwrap().
The CppHeapPointers use a range-based type checking scheme, where on access to a pointer, the actual type of the pointer is checked to be within a specified range of types. This allows supporting type hierarchies, where a type check for a supertype must succeed for any subtype.
The tag is currently in practice limited to 15 bits since it needs to fit together with a marking bit into the unused parts of a pointer.
Enumerator
kFirstTag
kNullTag
kDefaultTag The lower type ids are reserved for the embedder to assign. For that, the main requirement is that all (transitive) child classes of a given parent class have type ids in the same range, and that there are no unrelated types in that range. For example, given the following type hierarchy:
     A     F
    / \
   B   E
  / \
 C   D
 a potential type id assignment that satistifes these requirements is {C: 0, D: 1, B: 2, A: 3, E: 4, F: 5}. With that, the type check for type A would check for the range [0, 4], while the check for B would check range [0, 2], and for F it would simply check [5, 5].
In addition, there is an option for performance tweaks: if the size of the type range corresponding to a supertype is a power of two and starts at a power of two (e.g. [0x100, 0x13f]), then the compiler can often optimize the type check to use even fewer instructions (essentially replace a AND + SUB with a single AND).
kZappedEntryTag
kEvacuationEntryTag
kFreeEntryTag
kLastTag
Definition at line 28 of file v8-sandbox.h.
                             : uint16_t {
  kFirstTag = 0,
  kNullTag = 0,
  /**
   * The lower type ids are reserved for the embedder to assign. For that, the
   * main requirement is that all (transitive) child classes of a given parent
   * class have type ids in the same range, and that there are no unrelated
   * types in that range. For example, given the following type hierarchy:
   *
   * A F
   * / \
   * B E
   * / \
   * C D
   *
   * a potential type id assignment that satistifes these requirements is
   * {C: 0, D: 1, B: 2, A: 3, E: 4, F: 5}. With that, the type check for type A
   * would check for the range [0, 4], while the check for B would check range
   * [0, 2], and for F it would simply check [5, 5].
   *
   * In addition, there is an option for performance tweaks: if the size of the
   * type range corresponding to a supertype is a power of two and starts at a
   * power of two (e.g. [0x100, 0x13f]), then the compiler can often optimize
   * the type check to use even fewer instructions (essentially replace a AND +
   * SUB with a single AND).
   */
  kDefaultTag = 0x7000,
  kZappedEntryTag = 0x7ffd,
  kEvacuationEntryTag = 0x7ffe,
  kFreeEntryTag = 0x7fff,
  // The tags are limited to 15 bits, so the last tag is 0x7fff.
  kLastTag = 0x7fff,
};
CpuProfilingLoggingMode
enum v8::CpuProfilingLoggingMode
Enumerator
kLazyLogging
kEagerLogging
Definition at line 312 of file v8-profiler.h.
                             {
  // Enables logging when a profile is active, and disables logging when all
  // profiles are detached.
  kLazyLogging,
  // Enables logging for the lifetime of the CpuProfiler. Calls to
  // StartRecording are faster, at the expense of runtime overhead.
  kEagerLogging,
};
CpuProfilingMode
enum v8::CpuProfilingMode
Enumerator
kLeafNodeLineNumbers
kCallerLineNumbers
Definition at line 293 of file v8-profiler.h.
                      {
  // In the resulting CpuProfile tree, intermediate nodes in a stack trace
  // (from the root to a leaf) will have line numbers that point to the start
  // line of the function, rather than the line of the callsite of the child.
  kLeafNodeLineNumbers,
  // In the resulting CpuProfile tree, nodes are separated based on the line
  // number of their callsite in their parent.
  kCallerLineNumbers,
};
CpuProfilingNamingMode
enum v8::CpuProfilingNamingMode
Enumerator
kStandardNaming
kDebugNaming
Definition at line 304 of file v8-profiler.h.
                            {
  // Use the immediate name of functions at compilation time.
  kStandardNaming,
  // Use more verbose naming for functions without names, inferred from scope
  // where possible.
  kDebugNaming,
};
CpuProfilingStatus
enum v8::CpuProfilingStatus [strong]
Enumerator
kStarted
kAlreadyStarted
kErrorTooManyProfilers
Definition at line 324 of file v8-profiler.h.
                              {
  kStarted,
  kAlreadyStarted,
  kErrorTooManyProfilers
};
CrashKeyId
enum v8::CrashKeyId [strong]
Enumerator
kIsolateAddress
kReadonlySpaceFirstPageAddress
V8_ENUM_DEPRECATE_SOON
kOldSpaceFirstPageAddress
kCodeRangeBaseAddress
kCodeSpaceFirstPageAddress
kDumpType
kSnapshotChecksumCalculated
kSnapshotChecksumExpected
Definition at line 244 of file v8-callbacks.h.
                      {
  kIsolateAddress,
  kReadonlySpaceFirstPageAddress,
  kMapSpaceFirstPageAddress V8_ENUM_DEPRECATE_SOON("Map space got removed"),
  kOldSpaceFirstPageAddress,
  kCodeRangeBaseAddress,
  kCodeSpaceFirstPageAddress,
  kDumpType,
  kSnapshotChecksumCalculated,
  kSnapshotChecksumExpected,
};
EmbedderStateTag
enum v8::EmbedderStateTag : uint8_t [strong]
Enumerator
EMPTY
OTHER
Definition at line 22 of file v8-embedder-state-scope.h.
                            : uint8_t {
  // reserved
  EMPTY = 0,
  OTHER = 1,
  // embedder can define any state after
};
ExceptionContext
enum v8::ExceptionContext : uint32_t [strong]
This is a part of experimental Api and might be changed without further notice.
Do not use it.
Enumerator
kUnknown
kConstructor
kOperation
kAttributeGet
kAttributeSet
kIndexedQuery
kIndexedGetter
kIndexedDescriptor
kIndexedSetter
kIndexedDefiner
kIndexedDeleter
kNamedQuery
kNamedGetter
kNamedDescriptor
kNamedSetter
kNamedDefiner
kNamedDeleter
kNamedEnumerator
Definition at line 78 of file v8-exception.h.
                            : uint32_t {
  kUnknown,
  kConstructor,
  kOperation,
  kAttributeGet,
  kAttributeSet,
  kIndexedQuery,
  kIndexedGetter,
  kIndexedDescriptor,
  kIndexedSetter,
  kIndexedDefiner,
  kIndexedDeleter,
  kNamedQuery,
  kNamedGetter,
  kNamedDescriptor,
  kNamedSetter,
  kNamedDefiner,
  kNamedDeleter,
  kNamedEnumerator
};
GCCallbackFlags
enum v8::GCCallbackFlags
GCCallbackFlags is used to notify additional information about the GC callback.
kGCCallbackFlagConstructRetainedObjectInfos: The GC callback is for constructing retained object infos.
kGCCallbackFlagForced: The GC callback is for a forced GC for testing.
kGCCallbackFlagSynchronousPhantomCallbackProcessing: The GC callback is called synchronously without getting posted to an idle task.
kGCCallbackFlagCollectAllAvailableGarbage: The GC callback is called in a phase where V8 is trying to collect all available garbage (e.g., handling a low memory notification).
kGCCallbackScheduleIdleGarbageCollection: The GC callback is called to trigger an idle garbage collection.
Enumerator
kNoGCCallbackFlags
kGCCallbackFlagConstructRetainedObjectInfos
kGCCallbackFlagForced
kGCCallbackFlagSynchronousPhantomCallbackProcessing
kGCCallbackFlagCollectAllAvailableGarbage
kGCCallbackFlagCollectAllExternalMemory
kGCCallbackScheduleIdleGarbageCollection
Definition at line 179 of file v8-callbacks.h.
                     {
  kNoGCCallbackFlags = 0,
  kGCCallbackFlagConstructRetainedObjectInfos = 1 << 1,
  kGCCallbackFlagForced = 1 << 2,
  kGCCallbackFlagSynchronousPhantomCallbackProcessing = 1 << 3,
  kGCCallbackFlagCollectAllAvailableGarbage = 1 << 4,
  kGCCallbackFlagCollectAllExternalMemory = 1 << 5,
  kGCCallbackScheduleIdleGarbageCollection = 1 << 6,
};
GCType
enum v8::GCType
Applications can register callback functions which will be called before and after certain garbage collection operations.
Allocations are not allowed in the callback functions, you therefore cannot manipulate objects (set or delete properties for example) since it is possible such operations will result in the allocation of objects. TODO(v8:12612): Deprecate kGCTypeMinorMarkSweep after updating blink.
Enumerator
kGCTypeScavenge
kGCTypeMinorMarkSweep
kGCTypeMarkSweepCompact
kGCTypeIncrementalMarking
kGCTypeProcessWeakCallbacks
kGCTypeAll
Definition at line 154 of file v8-callbacks.h.
            {
  kGCTypeScavenge = 1 << 0,
  kGCTypeMinorMarkSweep = 1 << 1,
  kGCTypeMarkSweepCompact = 1 << 2,
  kGCTypeIncrementalMarking = 1 << 3,
  kGCTypeProcessWeakCallbacks = 1 << 4,
  kGCTypeAll = kGCTypeScavenge | kGCTypeMinorMarkSweep |
               kGCTypeMarkSweepCompact | kGCTypeIncrementalMarking |
               kGCTypeProcessWeakCallbacks
};
IndexFilter
enum v8::IndexFilter [strong]
kIncludesIndices allows for integer indices to be collected, while kSkipIndices will exclude integer indices from being collected.
Enumerator
kIncludeIndices
kSkipIndices
Definition at line 219 of file v8-object.h.
{ kIncludeIndices, kSkipIndices };
IntegrityLevel
enum v8::IntegrityLevel [strong]
Integrity level for objects.
Enumerator
kFrozen
kSealed
Definition at line 230 of file v8-object.h.
{ kFrozen, kSealed };
Intercepted
enum v8::Intercepted : uint8_t [strong]
Interceptor callbacks use this value to indicate whether the request was intercepted or not.
Enumerator
kNo
kYes
Definition at line 139 of file v8-template.h.
: uint8_t { kNo = 0, kYes = 1 };
Intrinsic
enum v8::Intrinsic
Definition at line 41 of file v8-template.h.
               {
#define V8_DECL_INTRINSIC(name, iname) k##name,
  V8_INTRINSICS_LIST(V8_DECL_INTRINSIC)
#undef V8_DECL_INTRINSIC
};
JitCodeEventOptions
enum v8::JitCodeEventOptions
Option flags passed to the SetJitCodeEventHandler function.
Enumerator
kJitCodeEventDefault
kJitCodeEventEnumExisting
kLastJitCodeEventOption
Definition at line 129 of file v8-callbacks.h.
                         {
  kJitCodeEventDefault = 0,
  // Generate callbacks for already existent code.
  kJitCodeEventEnumExisting = 1,
  kLastJitCodeEventOption = kJitCodeEventEnumExisting
};
JSApiInstanceType
enum v8::JSApiInstanceType : uint16_t [strong]
Enumerator
kGenericApiObject
kEventTarget
kNode
kElement
kHTMLElement
kHTMLDivElement
Definition at line 3898 of file d8.cc.
                             : uint16_t {
  kGenericApiObject = 0, // FunctionTemplateInfo::kNoJSApiObjectType.
  kEventTarget,
  kNode,
  kElement,
  kHTMLElement,
  kHTMLDivElement,
};
KeyCollectionMode
enum v8::KeyCollectionMode [strong]
Keys/Properties filter enums:
KeyCollectionMode limits the range of collected properties. kOwnOnly limits the collected properties to the given Object only. kIncludesPrototypes will include all keys of the objects's prototype chain as well.
Enumerator
kOwnOnly
kIncludePrototypes
Definition at line 213 of file v8-object.h.
{ kOwnOnly, kIncludePrototypes };
KeyConversionMode
enum v8::KeyConversionMode [strong]
kConvertToString will convert integer indices to strings.
kKeepNumbers will return numbers for integer indices.
Enumerator
kConvertToString
kKeepNumbers
kNoNumbers
Definition at line 225 of file v8-object.h.
{ kConvertToString, kKeepNumbers, kNoNumbers };
LogEventStatus
enum v8::LogEventStatus : int
Enumerator
kStart
kEnd
kLog
Definition at line 239 of file v8-callbacks.h.
: int { kStart = 0, kEnd = 1, kLog = 2 };
MeasureMemoryExecution
enum v8::MeasureMemoryExecution [strong]
Controls how promptly a memory measurement request is executed.
By default the measurement is folded with the next scheduled GC which may happen after a while and is forced after some timeout. The kEager mode starts incremental GC right away and is useful for testing. The kLazy mode does not force GC.
Enumerator
kDefault
kEager
kLazy
Definition at line 43 of file v8-statistics.h.
{ kDefault, kEager, kLazy };
MeasureMemoryMode
enum v8::MeasureMemoryMode [strong]
Controls how the default MeasureMemoryDelegate reports the result of the memory measurement to JS.
With kSummary only the total size is reported. With kDetailed the result includes the size of each native context.
Enumerator
kSummary
kDetailed
Definition at line 34 of file v8-statistics.h.
{ kSummary, kDetailed };
MemoryPressureLevel
enum v8::MemoryPressureLevel [strong]
Memory pressure level for the MemoryPressureNotification.
kNone hints V8 that there is no memory pressure. kModerate hints V8 to speed up incremental garbage collection at the cost of of higher latency due to garbage collection pauses. kCritical hints V8 to free memory as soon as possible. Garbage collection pauses at this level will be large.
Enumerator
kNone
kModerate
kCritical
Definition at line 175 of file v8-isolate.h.
{ kNone, kModerate, kCritical };
MicrotasksPolicy
enum v8::MicrotasksPolicy [strong]
Policy for running microtasks:
explicit: microtasks are invoked with the Isolate::PerformMicrotaskCheckpoint() method;
scoped: microtasks invocation is controlled by MicrotasksScope objects;
auto: microtasks are invoked when the script call depth decrements to zero.
Enumerator
kExplicit
kScoped
kAuto
Definition at line 24 of file v8-microtask.h.
{ kExplicit, kScoped, kAuto };
ModuleImportPhase
enum v8::ModuleImportPhase [strong]
Import phases in import requests.
Enumerator
kSource
kEvaluation
Definition at line 337 of file v8-callbacks.h.
                             {
  kSource,
  kEvaluation,
};
ModuleType
enum v8::ModuleType [strong]
Enumerator
kJavaScript
kJSON
kWebAssembly
kInvalid
Definition at line 37 of file d8.h.
{ kJavaScript, kJSON, kWebAssembly, kInvalid };
NewStringType
enum v8::NewStringType [strong]
A flag describing different modes of string creation.
Aside from performance implications there are no differences between the two creation modes.
Enumerator
kNormal Create a new string, always allocating new storage memory.
kInternalized Acts as a hint that the string should be created in the old generation heap space and be deduplicated if an identical string already exists.
Definition at line 107 of file v8-primitive.h.
                         {
  /**
   * Create a new string, always allocating new storage memory.
   */
  kNormal,
  /**
   * Acts as a hint that the string should be created in the
   * old generation heap space and be deduplicated if an identical string
   * already exists.
   */
  kInternalized
};
PagePermissions
enum v8::PagePermissions [strong]
Possible permissions for memory pages.
Enumerator
kNoAccess
kRead
kReadWrite
kReadWriteExecute
kReadExecute
Definition at line 761 of file v8-platform.h.
                           {
  kNoAccess,
  kRead,
  kReadWrite,
  kReadWriteExecute,
  kReadExecute,
};
PersistentContainerCallbackType
enum v8::PersistentContainerCallbackType
Enumerator
kNotWeak
kWeakWithParameter
kWeakWithInternalFields
Definition at line 30 of file v8-util.h.
                                     {
  kNotWeak,
  // These correspond to v8::WeakCallbackType
  kWeakWithParameter,
  kWeakWithInternalFields
};
PromiseHookType
enum v8::PromiseHookType [strong]
PromiseHook with type kInit is called when a new promise is created.
When a new promise is created as part of the chain in the case of Promise.then or in the intermediate promises created by Promise.{race, all}/AsyncFunctionAwait, we pass the parent promise otherwise we pass undefined.
PromiseHook with type kResolve is called at the beginning of resolve or reject function defined by CreateResolvingFunctions.
PromiseHook with type kBefore is called at the beginning of the PromiseReactionJob.
PromiseHook with type kAfter is called right at the end of the PromiseReactionJob.
Enumerator
kInit
kResolve
kBefore
kAfter
Definition at line 141 of file v8-promise.h.
{ kInit, kResolve, kBefore, kAfter };
PromiseRejectEvent
enum v8::PromiseRejectEvent
Enumerator
kPromiseRejectWithNoHandler
kPromiseHandlerAddedAfterReject
kPromiseRejectAfterResolved
kPromiseResolveAfterResolved
Definition at line 147 of file v8-promise.h.
                        {
  kPromiseRejectWithNoHandler = 0,
  kPromiseHandlerAddedAfterReject = 1,
  kPromiseRejectAfterResolved = 2,
  kPromiseResolveAfterResolved = 3,
};
PropertyAttribute
enum v8::PropertyAttribute
PropertyAttribute.
Enumerator
None None.
ReadOnly ReadOnly, i.e., not writable.
DontEnum DontEnum, i.e., not enumerable.
DontDelete DontDelete, i.e., not configurable.
Definition at line 141 of file v8-object.h.
                       {
  /** None. **/
  None = 0,
  /** ReadOnly, i.e., not writable. **/
  ReadOnly = 1 << 0,
  /** DontEnum, i.e., not enumerable. **/
  DontEnum = 1 << 1,
  /** DontDelete, i.e., not configurable. **/
  DontDelete = 1 << 2
};
PropertyFilter
enum v8::PropertyFilter
Property filter bits.
They can be or'ed to build a composite filter.
Enumerator
ALL_PROPERTIES
ONLY_WRITABLE
ONLY_ENUMERABLE
ONLY_CONFIGURABLE
SKIP_STRINGS
SKIP_SYMBOLS
Definition at line 181 of file v8-object.h.
                    {
  ALL_PROPERTIES = 0,
  ONLY_WRITABLE = 1,
  ONLY_ENUMERABLE = 2,
  ONLY_CONFIGURABLE = 4,
  SKIP_STRINGS = 8,
  SKIP_SYMBOLS = 16
};
PropertyHandlerFlags
enum v8::PropertyHandlerFlags [strong]
Configuration flags for v8::NamedPropertyHandlerConfiguration or v8::IndexedPropertyHandlerConfiguration.
Enumerator
kNone None.
kNonMasking Will not call into interceptor for properties on the receiver or prototype chain, i.e., only call into interceptor for properties that do not exist. Currently only valid for named interceptors.
kOnlyInterceptStrings Will not call into interceptor for symbol lookup. Only meaningful for named interceptors.
kHasNoSideEffect The getter, query, enumerator callbacks do not produce side effects.
kInternalNewCallbacksSignatures This flag is used to distinguish which callbacks were provided - GenericNamedPropertyXXXCallback (old signature) or NamedPropertyXXXCallback (new signature). DO NOT use this flag, it'll be removed once embedders migrate to new callbacks signatures.
Definition at line 740 of file v8-template.h.
                                {
  /**
   * None.
   */
  kNone = 0,
  /**
   * Will not call into interceptor for properties on the receiver or prototype
   * chain, i.e., only call into interceptor for properties that do not exist.
   * Currently only valid for named interceptors.
   */
  kNonMasking = 1,
  /**
   * Will not call into interceptor for symbol lookup. Only meaningful for
   * named interceptors.
   */
  kOnlyInterceptStrings = 1 << 1,
  /**
   * The getter, query, enumerator callbacks do not produce side effects.
   */
  kHasNoSideEffect = 1 << 2,
  /**
   * This flag is used to distinguish which callbacks were provided -
   * GenericNamedPropertyXXXCallback (old signature) or
   * NamedPropertyXXXCallback (new signature).
   * DO NOT use this flag, it'll be removed once embedders migrate to new
   * callbacks signatures.
   */
  kInternalNewCallbacksSignatures = 1 << 10,
};
ScriptType
enum v8::ScriptType [strong]
Enumerator
kClassic
kModule
Definition at line 397 of file v8-script.h.
{ kClassic, kModule };
SideEffectType
enum v8::SideEffectType [strong]
Options for marking whether callbacks may trigger JS-observable side effects.
Side-effect-free callbacks are allowlisted during debug evaluation with throwOnSideEffect. It applies when calling a Function, FunctionTemplate, or an Accessor callback. For Interceptors, please see PropertyHandlerFlags's kHasNoSideEffect. Callbacks that only cause side effects to the receiver are allowlisted if invoked on receiver objects that are created within the same debug-evaluate call, as these objects are temporary and the side effect does not escape.
Enumerator
kHasSideEffect
kHasNoSideEffect
kHasSideEffectToReceiver
Definition at line 200 of file v8-object.h.
                          {
  kHasSideEffect,
  kHasNoSideEffect,
  kHasSideEffectToReceiver
};
StateTag
enum v8::StateTag : uint16_t
Enumerator
JS
GC
PARSER
BYTECODE_COMPILER
COMPILER
OTHER
OTHER
EXTERNAL
ATOMICS_WAIT
IDLE
LOGGING
Definition at line 36 of file v8-unwinder.h.
              : uint16_t {
  JS,
  GC,
  PARSER,
  BYTECODE_COMPILER,
  COMPILER,
  OTHER,
  EXTERNAL,
  ATOMICS_WAIT,
  IDLE,
  LOGGING,
};
TaskPriority
enum v8::TaskPriority : uint8_t [strong]
Enumerator
kBestEffort Best effort tasks are not critical for performance of the application. The platform implementation should preempt such tasks if higher priority tasks arrive.
kUserVisible User visible tasks are long running background tasks that will improve performance and memory usage of the application upon completion. Example: background compilation and garbage collection.
kUserBlocking User blocking tasks are highest priority tasks that block the execution thread (e.g. major garbage collection). They must be finished as soon as possible.
kMaxPriority
Definition at line 24 of file v8-platform.h.
                        : uint8_t {
  /**
   * Best effort tasks are not critical for performance of the application. The
   * platform implementation should preempt such tasks if higher priority tasks
   * arrive.
   */
  kBestEffort,
  /**
   * User visible tasks are long running background tasks that will
   * improve performance and memory usage of the application upon completion.
   * Example: background compilation and garbage collection.
   */
  kUserVisible,
  /**
   * User blocking tasks are highest priority tasks that block the execution
   * thread (e.g. major garbage collection). They must be finished as soon as
   * possible.
   */
  kUserBlocking,
  kMaxPriority = kUserBlocking
};
WasmAsyncSuccess
enum v8::WasmAsyncSuccess [strong]
Enumerator
kSuccess
kFail
Definition at line 313 of file v8-callbacks.h.
{ kSuccess, kFail };
WeakCallbackType
enum v8::WeakCallbackType [strong]
Weakness type for weak handles.
Enumerator
kParameter Passes a user-defined void* parameter back to the callback.
kInternalFields Passes the first two internal fields of the object back to the callback.
Definition at line 65 of file v8-weak-callback-info.h.
                            {
  /**
   * Passes a user-defined void* parameter back to the callback.
   */
  kParameter,
  /**
   * Passes the first two internal fields of the object back to the callback.
   */
  kInternalFields,
};
Function Documentation
Align()
static const uint16_t* v8::Align (const uint16_t * chars) [inline], [static]
Definition at line 5584 of file api.cc.
                                                           {
  return reinterpret_cast<uint16_t*>(reinterpret_cast<uintptr_t>(chars) &
                                     ~kAlignmentMask);
}
References kAlignmentMask.
Referenced by v8::ContainsOnlyOneByteHelper::VisitTwoByteString().
ASSERT_TRIVIALLY_COPYABLE() [1/5]
v8::ASSERT_TRIVIALLY_COPYABLE (api_internal::IndirectHandleBase)
ASSERT_TRIVIALLY_COPYABLE() [2/5]
v8::ASSERT_TRIVIALLY_COPYABLE (internal::LocalUnchecked< Object >)
ASSERT_TRIVIALLY_COPYABLE() [3/5]
v8::ASSERT_TRIVIALLY_COPYABLE (Local< Object >)
ASSERT_TRIVIALLY_COPYABLE() [4/5]
v8::ASSERT_TRIVIALLY_COPYABLE (LocalBase< Object >)
ASSERT_TRIVIALLY_COPYABLE() [5/5]
v8::ASSERT_TRIVIALLY_COPYABLE (MaybeLocal< Object >)
CALLBACK_SETTER() [1/5]
allow_wasm_code_gen_callback wasm_async_resolve_promise_callback wasm_imported_strings_enabled_callback sharedarraybuffer_constructor_enabled_callback v8::CALLBACK_SETTER (IsJSApiWrapperNativeErrorCallback , IsJSApiWrapperNativeErrorCallback , is_js_api_wrapper_native_error_callback)
Definition at line 10790 of file api.cc.
                                                               {
  v8::HandleScope handle_scope(this);
  v8::Context::Scope context_scope(context);
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(this);
  if (i_isolate->is_execution_terminating()) return;
  i_isolate->InstallConditionalFeatures(Utils::OpenDirectHandle(*context));
  if (i_isolate->has_exception()) return;
#if V8_ENABLE_WEBASSEMBLY
  i::WasmJs::InstallConditionalFeatures(i_isolate,
                                        Utils::OpenDirectHandle(*context));
#endif // V8_ENABLE_WEBASSEMBLY
}
References v8::internal::Isolate::has_exception(), v8::internal::Isolate::InstallConditionalFeatures(), v8::internal::WasmJs::InstallConditionalFeatures(), v8::internal::Isolate::is_execution_terminating(), and v8::Utils::OpenDirectHandle().
CALLBACK_SETTER() [2/5]
v8::CALLBACK_SETTER (ModifyCodeGenerationFromStringsCallback , ModifyCodeGenerationFromStringsCallback2 , modify_code_gen_callback)
CALLBACK_SETTER() [3/5]
allow_wasm_code_gen_callback wasm_async_resolve_promise_callback wasm_imported_strings_enabled_callback v8::CALLBACK_SETTER (WasmJSPIEnabledCallback , WasmJSPIEnabledCallback , wasm_jspi_enabled_callback)
CALLBACK_SETTER() [4/5]
allow_wasm_code_gen_callback wasm_async_resolve_promise_callback v8::CALLBACK_SETTER (WasmLoadSourceMapCallback , WasmLoadSourceMapCallback , wasm_load_source_map_callback)
CALLBACK_SETTER() [5/5]
allow_wasm_code_gen_callback v8::CALLBACK_SETTER (WasmStreamingCallback , WasmStreamingCallback , wasm_streaming_callback)
CallGCCallbackWithoutData()
static void v8::CallGCCallbackWithoutData (Isolate * v8_isolate, GCType type, GCCallbackFlags flags, void * data) [static]
Definition at line 9811 of file api.cc.
                                                                         {
  reinterpret_cast<Isolate::GCCallback>(data)(v8_isolate, type, flags);
}
References flags(), and v8::internal::tracing::type.
Referenced by v8::Isolate::AddGCEpilogueCallback(), v8::Isolate::AddGCPrologueCallback(), v8::Isolate::RemoveGCEpilogueCallback(), and v8::Isolate::RemoveGCPrologueCallback().
CheckItsADirectory()
static bool v8::CheckItsADirectory (Isolate * isolate, char * directory) [static]
Definition at line 528 of file d8-posix.cc.
                                                                  {
  struct stat stat_buf;
  int stat_result = stat(directory, &stat_buf);
  if (stat_result != 0) {
    isolate->ThrowError(v8_strerror(isolate, errno));
    return false;
  }
  if ((stat_buf.st_mode & S_IFDIR) != 0) return true;
  isolate->ThrowError(v8_strerror(isolate, EEXIST));
  return false;
}
References v8::Isolate::ThrowError(), and v8::anonymous_namespace{d8-posix.cc}::v8_strerror().
Referenced by mkdirp().
ChildLaunchedOK()
static bool v8::ChildLaunchedOK (Isolate * isolate, int * exec_error_fds) [static]
Definition at line 274 of file d8-posix.cc.
                                                                   {
  ssize_t bytes_read;
  int err;
  do {
    bytes_read = read(exec_error_fds[kReadFD], &err, sizeof(err));
  } while (bytes_read == -1 && errno == EINTR);
  if (bytes_read != 0) {
    isolate->ThrowError(v8_strerror(isolate, err));
    return false;
  }
  return true;
}
References kReadFD, v8::Isolate::ThrowError(), and v8::anonymous_namespace{d8-posix.cc}::v8_strerror().
Referenced by v8::Shell::System().
CopyAndConvertArrayToCppBuffer()
template<CTypeInfo::Identifier type_info_id, typename T >
bool v8::CopyAndConvertArrayToCppBuffer (Local< Array > src, T * dst, uint32_t max_length)
Definition at line 449 of file api-inl.h.
                                                         {
  static_assert(
      std::is_same_v<T, typename i::CTypeInfoTraits<
                            CTypeInfo(type_info_id).GetType()>::ctype>,
      "Type mismatch between the expected CTypeInfo::Type and the destination "
      "array");
  uint32_t length = src->Length();
  if (length == 0) {
    // Early return here to avoid a cast error below, as the EmptyFixedArray
    // cannot be cast to a FixedDoubleArray.
    return true;
  }
  if (length > max_length) {
    return false;
  }
  i::DisallowGarbageCollection no_gc;
  i::Tagged<i::JSArray> obj = *Utils::OpenDirectHandle(*src);
  if (i::Object::IterationHasObservableEffects(obj)) {
    // The array has a custom iterator.
    return false;
  }
  i::Tagged<i::FixedArrayBase> elements = obj->elements();
  switch (obj->GetElementsKind()) {
    case i::PACKED_SMI_ELEMENTS:
      CopySmiElementsToTypedBuffer(dst, length,
                                   i::Cast<i::FixedArray>(elements));
      return true;
    case i::PACKED_DOUBLE_ELEMENTS:
      CopyDoubleElementsToTypedBuffer(dst, length,
                                      i::Cast<i::FixedDoubleArray>(elements));
      return true;
    default:
      return false;
  }
}
References CopyDoubleElementsToTypedBuffer(), CopySmiElementsToTypedBuffer(), v8::internal::Object::IterationHasObservableEffects(), v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::Utils::OpenDirectHandle(), v8::internal::PACKED_DOUBLE_ELEMENTS, and v8::internal::PACKED_SMI_ELEMENTS.
Referenced by TryCopyAndConvertArrayToCppBuffer().
CopyDoubleElementsToTypedBuffer()
template<typename T >
void v8::CopyDoubleElementsToTypedBuffer (T * dst, uint32_t length, i::Tagged< i::FixedDoubleArray > elements)
Definition at line 438 of file api-inl.h.
                                                                          {
  for (uint32_t i = 0; i < length; ++i) {
    double value = elements->get_scalar(static_cast<int>(i));
    // TODO(mslekova): There are certain cases, e.g. double->double, in which
    // we could do a memcpy directly.
    dst[i] = i::ConvertDouble<T>(value);
  }
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::length, and v8::internal::value.
Referenced by CopyAndConvertArrayToCppBuffer().
CopySmiElementsToTypedBuffer()
template<typename T >
void v8::CopySmiElementsToTypedBuffer (T * dst, uint32_t length, i::Tagged< i::FixedArray > elements)
Definition at line 426 of file api-inl.h.
                                                                 {
  for (uint32_t i = 0; i < length; ++i) {
    double value = i::Object::NumberValue(
        i::Cast<i::Smi>(elements->get(static_cast<int>(i))));
    // TODO(mslekova): Avoid converting back-and-forth when possible, e.g
    // avoid int->double->int conversions to boost performance.
    dst[i] = i::ConvertDouble<T>(value);
  }
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::length, v8::internal::Object::NumberValue(), and v8::internal::value.
Referenced by CopyAndConvertArrayToCppBuffer().
CreateEnvironment()
template<typename ObjectType >
static i::DirectHandle<ObjectType> v8::CreateEnvironment (i::Isolate * i_isolate, v8::ExtensionConfiguration * extensions, v8::MaybeLocal< ObjectTemplate > maybe_global_template, v8::MaybeLocal< Value > maybe_global_proxy, size_t context_snapshot_index, i::DeserializeEmbedderFieldsCallback embedder_fields_deserializer, v8::MicrotaskQueue * microtask_queue) [static]
Definition at line 6593 of file api.cc.
                                       {
  i::DirectHandle<ObjectType> result;
  {
    // Do some part of the EnterV8Scope, but without a context yet.
    DCHECK_IMPLIES(i::v8_flags.strict_termination_checks,
                   !i_isolate->is_execution_terminating());
    i::VMState<v8::OTHER> vm_state(i_isolate);
    i::DisallowExceptionsDebugOnly no_exceptions(i_isolate);
    v8::Local<ObjectTemplate> proxy_template;
    i::DirectHandle<i::FunctionTemplateInfo> proxy_constructor;
    i::DirectHandle<i::FunctionTemplateInfo> global_constructor;
    i::DirectHandle<i::UnionOf<i::Undefined, i::InterceptorInfo>>
        named_interceptor(i_isolate->factory()->undefined_value());
    i::DirectHandle<i::UnionOf<i::Undefined, i::InterceptorInfo>>
        indexed_interceptor(i_isolate->factory()->undefined_value());
    if (!maybe_global_template.IsEmpty()) {
      v8::Local<v8::ObjectTemplate> global_template =
          maybe_global_template.ToLocalChecked();
      // Make sure that the global_template has a constructor.
      global_constructor = EnsureConstructor(i_isolate, *global_template);
      // Create a fresh template for the global proxy object.
      proxy_template =
          ObjectTemplate::New(reinterpret_cast<v8::Isolate*>(i_isolate));
      proxy_constructor = EnsureConstructor(i_isolate, *proxy_template);
      // Set the global template to be the prototype template of
      // global proxy template.
      i::FunctionTemplateInfo::SetPrototypeTemplate(
          i_isolate, proxy_constructor,
          Utils::OpenDirectHandle(*global_template));
      proxy_template->SetInternalFieldCount(
          global_template->InternalFieldCount());
      // Migrate security handlers from global_template to
      // proxy_template. Temporarily removing access check
      // information from the global template.
      if (!IsUndefined(global_constructor->GetAccessCheckInfo(), i_isolate)) {
        i::FunctionTemplateInfo::SetAccessCheckInfo(
            i_isolate, proxy_constructor,
            direct_handle(global_constructor->GetAccessCheckInfo(), i_isolate));
        proxy_constructor->set_needs_access_check(
            global_constructor->needs_access_check());
        global_constructor->set_needs_access_check(false);
        i::FunctionTemplateInfo::SetAccessCheckInfo(
            i_isolate, global_constructor,
            i_isolate->factory()->undefined_value());
      }
      // Same for other interceptors. If the global constructor has
      // interceptors, we need to replace them temporarily with noop
      // interceptors, so the map is correctly marked as having interceptors,
      // but we don't invoke any.
      if (!IsUndefined(global_constructor->GetNamedPropertyHandler(),
                       i_isolate)) {
        named_interceptor = direct_handle(
            global_constructor->GetNamedPropertyHandler(), i_isolate);
        i::FunctionTemplateInfo::SetNamedPropertyHandler(
            i_isolate, global_constructor,
            i_isolate->factory()->noop_interceptor_info());
      }
      if (!IsUndefined(global_constructor->GetIndexedPropertyHandler(),
                       i_isolate)) {
        indexed_interceptor = direct_handle(
            global_constructor->GetIndexedPropertyHandler(), i_isolate);
        i::FunctionTemplateInfo::SetIndexedPropertyHandler(
            i_isolate, global_constructor,
            i_isolate->factory()->noop_interceptor_info());
      }
    }
    i::MaybeDirectHandle<i::JSGlobalProxy> maybe_proxy;
    if (!maybe_global_proxy.IsEmpty()) {
      maybe_proxy = i::Cast<i::JSGlobalProxy>(
          Utils::OpenDirectHandle(*maybe_global_proxy.ToLocalChecked()));
    }
    // Create the environment.
    InvokeBootstrapper<ObjectType> invoke;
    result = invoke.Invoke(i_isolate, maybe_proxy, proxy_template, extensions,
                           context_snapshot_index, embedder_fields_deserializer,
                           microtask_queue);
    // Restore the access check info and interceptors on the global template.
    if (!maybe_global_template.IsEmpty()) {
      DCHECK(!global_constructor.is_null());
      DCHECK(!proxy_constructor.is_null());
      i::FunctionTemplateInfo::SetAccessCheckInfo(
          i_isolate, global_constructor,
          i::direct_handle(proxy_constructor->GetAccessCheckInfo(), i_isolate));
      global_constructor->set_needs_access_check(
          proxy_constructor->needs_access_check());
      i::FunctionTemplateInfo::SetNamedPropertyHandler(
          i_isolate, global_constructor, named_interceptor);
      i::FunctionTemplateInfo::SetIndexedPropertyHandler(
          i_isolate, global_constructor, indexed_interceptor);
    }
  }
  // Leave V8.
  return result;
}
References DCHECK, DCHECK_IMPLIES, v8::internal::direct_handle(), v8::anonymous_namespace{api.cc}::EnsureConstructor(), v8::internal::Isolate::factory(), v8::internal::libvtune::invoke(), v8::internal::Isolate::is_execution_terminating(), v8::internal::DirectHandle< T >::is_null(), v8::MaybeLocal< T >::IsEmpty(), v8::ObjectTemplate::New(), v8::Utils::OpenDirectHandle(), v8::base::internal::result, v8::MaybeLocal< T >::ToLocalChecked(), and v8::internal::v8_flags.
CreateFastCAPIObject()
void v8::CreateFastCAPIObject (const FunctionCallbackInfo< Value > & info)
Definition at line 1492 of file d8-test.cc.
                                                                   {
  DCHECK(i::ValidateCallbackInfo(info));
  if (!info.IsConstructCall()) {
    info.GetIsolate()->ThrowError(
        "FastCAPI helper must be constructed with new.");
    return;
  }
  Local<Object> api_object = info.This();
  api_object->SetAlignedPointerInInternalField(
      FastCApiObject::kV8WrapperObjectIndex,
      reinterpret_cast<void*>(&kFastCApiObject));
  api_object->SetAccessorProperty(
      String::NewFromUtf8Literal(info.GetIsolate(), "supports_fp_params"),
      FunctionTemplate::New(info.GetIsolate(), FastCApiObject::SupportsFPParams)
          ->GetFunction(api_object->GetCreationContext(info.GetIsolate())
                            .ToLocalChecked())
          .ToLocalChecked());
}
References DCHECK, v8::Object::GetCreationContext(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::IsConstructCall(), v8::anonymous_namespace{d8-test.cc}::kFastCApiObject, v8::FunctionTemplate::New(), v8::String::NewFromUtf8Literal(), v8::Object::SetAccessorProperty(), v8::Object::SetAlignedPointerInInternalField(), v8::FunctionCallbackInfo< T >::This(), v8::Isolate::ThrowError(), v8::MaybeLocal< T >::ToLocalChecked(), and v8::internal::ValidateCallbackInfo().
Referenced by v8::Shell::CreateTestFastCApiTemplate().
CreateLeafInterfaceObject()
void v8::CreateLeafInterfaceObject (const FunctionCallbackInfo< Value > & info)
Definition at line 2001 of file d8-test.cc.
                                                                        {
  if (!info.IsConstructCall()) {
    info.GetIsolate()->ThrowError(
        "LeafInterfaceType helper must be constructed with new.");
  }
}
References v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::IsConstructCall(), and v8::Isolate::ThrowError().
Referenced by v8::Shell::CreateLeafInterfaceTypeTemplate().
CurrentValueSerializerFormatVersion()
constexpr uint32_t v8::CurrentValueSerializerFormatVersion () [constexpr]
Definition at line 20 of file v8-value-serializer-version.h.
{ return 15; }
Dummy()
void v8::Dummy (char * arg)
Definition at line 4739 of file d8.cc.
{}
Referenced by v8::internal::compiler::CodeAssembler::BitcastTaggedToWord(), v8::internal::compiler::LinearScanAllocator::ChooseOneOfTwoPredecessorStates(), v8::FuzzerMonitor::ControlFlowViolation(), v8::base::EXPLICIT_CHECK_OP_INSTANTIATION(), and v8::internal::compiler::MoveOptimizer::MigrateMoves().
EmbedderDataFor()
static i::DirectHandle<i::EmbedderDataArray> v8::EmbedderDataFor (Context * context, int index, bool can_grow, const char * location) [static]
Definition at line 884 of file api.cc.
                                                                      {
  auto env = Utils::OpenDirectHandle(context);
  i::Isolate* i_isolate = i::Isolate::Current();
  i::DisallowJavascriptExecutionDebugOnly no_execution(i_isolate);
  i::DisallowExceptionsDebugOnly no_exceptions(i_isolate);
  bool ok = Utils::ApiCheck(i::IsNativeContext(*env), location,
                            "Not a native context") &&
            Utils::ApiCheck(index >= 0, location, "Negative index");
  if (!ok) return {};
  // TODO(ishell): remove cast once embedder_data slot has a proper type.
  i::DirectHandle<i::EmbedderDataArray> data(
      i::Cast<i::EmbedderDataArray>(env->embedder_data()), i_isolate);
  if (index < data->length()) return data;
  if (!Utils::ApiCheck(can_grow && index < i::EmbedderDataArray::kMaxLength,
                       location, "Index too large")) {
    return {};
  }
  data = i::EmbedderDataArray::EnsureCapacity(i_isolate, data, index);
  env->set_embedder_data(*data);
  return data;
}
References v8::Utils::ApiCheck(), v8::internal::Isolate::Current(), v8::internal::EmbedderDataArray::EnsureCapacity(), v8::internal::index, v8::internal::EmbedderDataArray::kMaxLength, v8::internal::length, and v8::Utils::OpenDirectHandle().
Referenced by v8::Context::SetAlignedPointerInEmbedderData(), v8::Context::SetEmbedderData(), v8::Context::SlowGetAlignedPointerFromEmbedderData(), and v8::Context::SlowGetEmbedderData().
ends_with()
bool v8::ends_with (const char * input, const char * suffix)
Definition at line 5160 of file d8.cc.
                                                      {
  size_t input_length = strlen(input);
  size_t suffix_length = strlen(suffix);
  if (suffix_length <= input_length) {
    return strcmp(input + input_length - suffix_length, suffix) == 0;
  }
  return false;
}
Referenced by v8::SourceGroup::Execute().
ExecSubprocess()
static void v8::ExecSubprocess (int * exec_error_fds, int * stdout_fds, const ExecArgs & exec_args) [static]
Definition at line 253 of file d8-posix.cc.
                                                      {
  close(exec_error_fds[kReadFD]); // Don't need this in the child.
  close(stdout_fds[kReadFD]); // Don't need this in the child.
  close(1); // Close stdout.
  dup2(stdout_fds[kWriteFD], 1); // Dup pipe fd to stdout.
  close(stdout_fds[kWriteFD]); // Don't need the original fd now.
  fcntl(exec_error_fds[kWriteFD], F_SETFD, FD_CLOEXEC);
  execvp(exec_args.arg0(), exec_args.arg_array());
  // Only get here if the exec failed. Write errno to the parent to tell
  // them it went wrong. If it went well the pipe is closed.
  int err = errno;
  ssize_t bytes_written;
  do {
    bytes_written = write(exec_error_fds[kWriteFD], &err, sizeof(err));
  } while (bytes_written == -1 && errno == EINTR);
  // Return (and exit child process).
}
References v8::ExecArgs::arg0(), v8::ExecArgs::arg_array(), kReadFD, and kWriteFD.
Referenced by v8::Shell::System().
False()
Local<Boolean> v8::False (Isolate * isolate) [inline]
Definition at line 1079 of file v8-primitive.h.
                                                 {
  using S = internal::Address;
  using I = internal::Internals;
  I::CheckInitialized(isolate);
  S* slot = I::GetRootSlot(isolate, I::kFalseValueRootIndex);
  return Local<Boolean>::FromSlot(slot);
}
Referenced by v8::Boolean::New(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyValidateImpl().
FileDescriptorFromSharedMemoryHandle()
int v8::FileDescriptorFromSharedMemoryHandle (PlatformSharedMemoryHandle handle) [inline]
Definition at line 752 of file v8-platform.h.
                                       {
  return static_cast<int>(handle);
}
References v8::internal::handle().
FromCData() [1/2]
template<internal::ExternalPointerTag tag>
i::DirectHandle< i::UnionOf< i::Smi, i::Foreign > > v8::FromCData (i::Isolate * isolate, i::Address obj) [inline]
Definition at line 47 of file api-inl.h.
                                     {
  if (obj == i::kNullAddress) {
    return direct_handle(i::Smi::zero(), isolate);
  }
  return isolate->factory()->NewForeign<tag>(obj);
}
References v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::base::kNullAddress, v8::internal::Factory::NewForeign(), and v8::internal::Smi::zero().
FromCData() [2/2]
template<internal::ExternalPointerTag tag, typename T >
i::DirectHandle< i::UnionOf< i::Smi, i::Foreign > > v8::FromCData (i::Isolate * isolate, T obj) [inline]
Definition at line 39 of file api-inl.h.
                              {
  static_assert(sizeof(T) == sizeof(i::Address));
  if (obj == nullptr) return direct_handle(i::Smi::zero(), isolate);
  return isolate->factory()->NewForeign<tag>(reinterpret_cast<i::Address>(obj));
}
References v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::Factory::NewForeign(), and v8::internal::Smi::zero().
GetCalleeSavedRegistersFromEntryFrame()
void v8::GetCalleeSavedRegistersFromEntryFrame (void * fp, RegisterState * register_state)
Definition at line 14 of file unwinder-arm.cc.
                                                                          {
  const i::Address base_addr =
      reinterpret_cast<i::Address>(fp) +
      i::EntryFrameConstants::kDirectCallerGeneralRegistersOffset;
  if (!register_state->callee_saved) {
    register_state->callee_saved = std::make_unique<CalleeSavedRegisters>();
  }
  register_state->callee_saved->arm_r4 =
      reinterpret_cast<void*>(Load(base_addr + 0 * i::kSystemPointerSize));
  register_state->callee_saved->arm_r5 =
      reinterpret_cast<void*>(Load(base_addr + 1 * i::kSystemPointerSize));
  register_state->callee_saved->arm_r6 =
      reinterpret_cast<void*>(Load(base_addr + 2 * i::kSystemPointerSize));
  register_state->callee_saved->arm_r7 =
      reinterpret_cast<void*>(Load(base_addr + 3 * i::kSystemPointerSize));
  register_state->callee_saved->arm_r8 =
      reinterpret_cast<void*>(Load(base_addr + 4 * i::kSystemPointerSize));
  register_state->callee_saved->arm_r9 =
      reinterpret_cast<void*>(Load(base_addr + 5 * i::kSystemPointerSize));
  register_state->callee_saved->arm_r10 =
      reinterpret_cast<void*>(Load(base_addr + 6 * i::kSystemPointerSize));
}
References v8::RegisterState::callee_saved, v8::internal::EntryFrameConstants::kDirectCallerGeneralRegistersOffset, v8::internal::kSystemPointerSize, and Load().
Referenced by v8::Unwinder::TryUnwindV8Frames().
GetScriptOriginForScript()
static ScriptOrigin v8::GetScriptOriginForScript (i::Isolate * i_isolate, i::DirectHandle< i::Script > script) [static]
Definition at line 191 of file api.cc.
                                                        {
  i::DirectHandle<i::Object> scriptName(script->GetNameOrSourceURL(),
                                        i_isolate);
  i::DirectHandle<i::Object> source_map_url(script->source_mapping_url(),
                                            i_isolate);
  i::DirectHandle<i::Object> host_defined_options(
      script->host_defined_options(), i_isolate);
  ScriptOriginOptions options(script->origin_options());
  bool is_wasm = false;
#if V8_ENABLE_WEBASSEMBLY
  is_wasm = script->type() == i::Script::Type::kWasm;
#endif // V8_ENABLE_WEBASSEMBLY
  v8::ScriptOrigin origin(
      Utils::ToLocal(scriptName), script->line_offset(),
      script->column_offset(), options.IsSharedCrossOrigin(), script->id(),
      Utils::ToLocal(source_map_url), options.IsOpaque(), is_wasm,
      options.IsModule(), Utils::ToLocal(host_defined_options));
  return origin;
}
References v8::ScriptOriginOptions::IsModule(), v8::ScriptOriginOptions::IsOpaque(), v8::ScriptOriginOptions::IsSharedCrossOrigin(), and v8::internal::script.
Referenced by v8::Function::GetScriptOrigin(), and v8::Message::GetScriptOrigin().
GetStdout()
static Local<Value> v8::GetStdout (Isolate * isolate, int child_fd, const struct timeval & start_time, int read_timeout, int total_timeout) [static]
Definition at line 289 of file d8-posix.cc.
                                                                   {
  Local<String> accumulator = String::Empty(isolate);
  int fullness = 0;
  static const int kStdoutReadBufferSize = 4096;
  char buffer[kStdoutReadBufferSize];
  if (fcntl(child_fd, F_SETFL, O_NONBLOCK) != 0) {
    return isolate->ThrowError(v8_strerror(isolate, errno));
  }
  int bytes_read;
  do {
    bytes_read = static_cast<int>(
        read(child_fd, buffer + fullness, kStdoutReadBufferSize - fullness));
    if (bytes_read == -1) {
      if (errno == EAGAIN) {
        if (!WaitOnFD(child_fd, read_timeout, total_timeout, start_time) ||
            (TimeIsOut(start_time, total_timeout))) {
          return isolate->ThrowError("Timed out waiting for output");
        }
        continue;
      } else if (errno == EINTR) {
        continue;
      } else {
        break;
      }
    }
    if (bytes_read + fullness > 0) {
      int length = bytes_read == 0 ? bytes_read + fullness
                                   : LengthWithoutIncompleteUtf8(
                                         buffer, bytes_read + fullness);
      Local<String> addition =
          String::NewFromUtf8(isolate, buffer, NewStringType::kNormal, length)
              .ToLocalChecked();
      accumulator = String::Concat(isolate, accumulator, addition);
      fullness = bytes_read + fullness - length;
      memcpy(buffer, buffer + length, fullness);
    }
  } while (bytes_read != 0);
  return accumulator;
}
References v8::String::Concat(), v8::String::Empty(), kNormal, v8::internal::length, LengthWithoutIncompleteUtf8(), v8::String::NewFromUtf8(), v8::Isolate::ThrowError(), TimeIsOut(), v8::anonymous_namespace{d8-posix.cc}::v8_strerror(), and WaitOnFD().
Referenced by v8::Shell::System().
GetTimeouts()
static bool v8::GetTimeouts (const v8::FunctionCallbackInfo< v8::Value > & info, int * read_timeout, int * total_timeout) [static]
Definition at line 216 of file d8-posix.cc.
                                                               {
  if (info.Length() > 3) {
    if (info[3]->IsNumber()) {
      *total_timeout = info[3]
                           ->Int32Value(info.GetIsolate()->GetCurrentContext())
                           .FromJust();
    } else {
      info.GetIsolate()->ThrowError("system: Argument 4 must be a number");
      return false;
    }
  }
  if (info.Length() > 2) {
    if (info[2]->IsNumber()) {
      *read_timeout = info[2]
                          ->Int32Value(info.GetIsolate()->GetCurrentContext())
                          .FromJust();
    } else {
      info.GetIsolate()->ThrowError("system: Argument 3 must be a number");
      return false;
    }
  }
  return true;
}
References v8::Isolate::GetCurrentContext(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::internal::IsNumber(), v8::FunctionCallbackInfo< T >::Length(), and v8::Isolate::ThrowError().
Referenced by v8::Shell::System().
InternalFieldOK()
static bool v8::InternalFieldOK (i::DirectHandle< i::JSReceiver > obj, int index, const char * location) [inline], [static]
Definition at line 6225 of file api.cc.
                                                                       {
  return Utils::ApiCheck(
      IsJSObject(*obj) &&
          (index < i::Cast<i::JSObject>(*obj)->GetEmbedderFieldCount()),
      location, "Internal field out of bounds");
}
References v8::Utils::ApiCheck(), and v8::internal::index.
Referenced by v8::Object::SetAlignedPointerInInternalField(), v8::Object::SetInternalField(), v8::Object::SlowGetAlignedPointerFromInternalField(), and v8::Object::SlowGetInternalField().
Just() [1/2]
template<class T >
Maybe<T> v8::Just (const T & t) [inline]
Definition at line 126 of file v8-maybe.h.
                                 {
  return Maybe<T>(t);
}
Referenced by v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::AddArguments(), v8::internal::JSObject::AddDataElement(), v8::internal::Object::AddDataProperty(), v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::AddImpl(), v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::AddImpl(), v8::internal::anonymous_namespace{elements.cc}::SlowSloppyArgumentsElementsAccessor::AddImpl(), v8::internal::anonymous_namespace{elements.cc}::FastSloppyArgumentsElementsAccessor::AddImpl(), v8::internal::anonymous_namespace{elements.cc}::StringWrapperElementsAccessor< Subclass, BackingStoreAccessor, KindTraits >::AddImpl(), v8::internal::KeyAccumulator::AddKeysFromJSProxy(), v8::internal::anonymous_namespace{js-relative-time-format.cc}::AddLiteral(), v8::internal::anonymous_namespace{js-date-time-format.cc}::AddPartForFormatRange(), v8::internal::JSObject::AddProperty(), v8::internal::anonymous_namespace{runtime-scopes.cc}::AddToDisposableStack(), v8::internal::anonymous_namespace{js-relative-time-format.cc}::AddUnit(), v8::internal::DebugPropertyIterator::Advance(), v8::internal::anonymous_namespace{js-locale.cc}::ApplyOptionsToTag(), v8::internal::JSArray::ArraySetLength(), v8::internal::SourceTextModule::AsyncModuleExecutionFulfilled(), v8::internal::anonymous_namespace{runtime-atomics.cc}::AtomicFieldWrite(), v8::internal::DebugPropertyIterator::attributes(), v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::BasicGrowCapacityAndConvertImpl(), v8::internal::wasm::InstanceBuilder::Build_Phase1(), v8::internal::wasm::InstanceBuilder::Build_Phase2(), v8::internal::BUILTIN(), v8::internal::temporal::CanonicalizeCalendar(), v8::internal::Intl::CanonicalizeLocaleList(), v8::internal::Isolate::CaptureAndSetErrorStack(), v8::internal::ErrorUtils::CaptureStackTrace(), v8::Exception::CaptureStackTrace(), v8::anonymous_namespace{d8.cc}::ChainDynamicImportPromise(), v8::internal::anonymous_namespace{builtins-sharedarraybuffer.cc}::CheckAtomicsPauseIterationNumber(), v8::internal::JSProxy::CheckDeleteTrap(), v8::internal::JSProxy::CheckHasTrap(), v8::internal::JSObject::CheckIfCanDefineAsConfigurable(), v8::internal::JSReceiver::CheckPrivateNameStore(), v8::internal::compiler::TFPipelineData::ChooseSpecializationContext(), v8::internal::JSFinalizationRegistry::Cleanup(), v8::internal::KeyAccumulator::CollectAccessCheckInterceptorKeys(), v8::internal::anonymous_namespace{builtins-struct.cc}::CollectFieldsAndElements(), v8::internal::KeyAccumulator::CollectInterceptorKeys(), v8::internal::KeyAccumulator::CollectInterceptorKeysInternal(), v8::internal::KeyAccumulator::CollectKeys(), v8::internal::KeyAccumulator::CollectOwnElementIndices(), v8::internal::KeyAccumulator::CollectOwnJSProxyKeys(), v8::internal::KeyAccumulator::CollectOwnKeys(), v8::internal::anonymous_namespace{runtime-object.cc}::CollectPrivateMembersFromReceiver(), v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::CollectValuesOrEntriesImpl(), v8::internal::anonymous_namespace{elements.cc}::FastSmiOrObjectElementsAccessor< Subclass, KindTraits >::CollectValuesOrEntriesImpl(), v8::internal::anonymous_namespace{elements.cc}::FastDoubleElementsAccessor< Subclass, KindTraits >::CollectValuesOrEntriesImpl(), v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::CollectValuesOrEntriesImpl(), v8::internal::Object::Compare(), v8::internal::BigInt::CompareToString(), v8::internal::anonymous_namespace{runtime-regexp.cc}::ConstructNamedCaptureGroupsObject(), v8::internal::anonymous_namespace{js-number-format.cc}::ConstructParts(), v8::debug::Script::ContextId(), v8::internal::JSFunctionOrBoundFunctionOrWrappedFunction::CopyNameAndLength(), v8::internal::ArrayProxy::Create(), v8::internal::temporal::TimeDurationRecord::Create(), v8::internal::temporal::DurationRecord::Create(), v8::internal::JSObject::CreateDataProperty(), v8::Object::CreateDataProperty(), v8::internal::anonymous_namespace{js-plural-rules.cc}::CreateDataPropertyForOptions(), v8::internal::anonymous_namespace{js-collator.cc}::CreateDataPropertyForOptions(), v8::internal::anonymous_namespace{intl-objects.cc}::CreateICULocale(), v8::internal::DefaultNumberOption(), v8::internal::anonymous_namespace{api-natives.cc}::DefineDataProperty(), v8::internal::AlwaysSharedSpaceJSObject::DefineOwnProperty(), v8::internal::JSArray::DefineOwnProperty(), v8::internal::JSModuleNamespace::DefineOwnProperty(), v8::internal::JSProxy::DefineOwnProperty(), v8::internal::JSTypedArray::DefineOwnProperty(), v8::Object::DefineOwnProperty(), v8::internal::JSObject::DefineOwnPropertyIgnoreAttributes(), v8::internal::JSReceiver::DefineProperties(), v8::internal::JSReceiver::DefineProperty(), v8::Object::DefineProperty(), v8::internal::anonymous_namespace{js-objects.cc}::DefinePropertyWithInterceptorInternal(), v8::Map::Delete(), v8::Set::Delete(), v8::internal::JSReceiver::DeleteProperty(), v8::internal::JSObject::DeletePropertyWithInterceptor(), v8::internal::DebugPropertyIterator::descriptor(), v8::internal::JSArrayBuffer::Detach(), v8::ArrayBuffer::Detach(), v8::internal::Object::Equals(), v8::internal::BigInt::EqualToString(), v8::internal::ValueSerializer::ExpandBuffer(), v8::internal::anonymous_namespace{js-temporal-objects.cc}::ExtractRustResult(), v8::internal::anonymous_namespace{js-objects.cc}::FastAssign(), v8::internal::FastGetOwnValuesOrEntries(), v8::internal::compiler::VirtualObject::FieldAt(), v8::internal::KeyAccumulator::FilterForEnumerableProperties(), v8::Serializer::FinalizeTransfer(), v8::internal::anonymous_namespace{runtime-object.cc}::FindPrivateMembersFromReceiver(), v8::internal::IntlMathematicalValue::FormatNumeric(), v8::internal::IntlMathematicalValue::FormatRange(), v8::internal::IntlMathematicalValue::From(), v8::internal::compiler::anonymous_namespace{access-info.cc}::GeneralizeElementsKind(), v8::internal::anonymous_namespace{builtins-array.cc}::GenericArrayFill(), v8::internal::anonymous_namespace{builtins-array.cc}::GenericArrayPop(), v8::internal::anonymous_namespace{builtins-array.cc}::GenericArrayPush(), v8::internal::anonymous_namespace{builtins-array.cc}::GenericArrayShift(), v8::internal::anonymous_namespace{js-objects.cc}::GenericTestIntegrityLevel(), v8::internal::PointerToIndexHashMap< Type >::Get(), v8::internal::compiler::VariableTracker::Scope::Get(), v8::internal::PropertyCallbackArguments::GetBooleanReturnValue(), v8::internal::GetBoolOption(), v8::internal::temporal::GetDifferenceSettingsWithoutChecks(), v8::internal::anonymous_namespace{js-duration-format.cc}::GetDurationUnitOptions(), v8::Message::GetEndColumn(), v8::internal::ErrorUtils::GetFormattedStack(), v8::internal::JSBoundFunction::GetLength(), v8::internal::JSWrappedFunction::GetLength(), v8::internal::anonymous_namespace{builtins-array.cc}::GetLengthProperty(), v8::Message::GetLineNumber(), v8::internal::compiler::GetModuleContext(), v8::internal::Intl::GetNumberingSystem(), v8::internal::GetNumberOptionAsDouble(), v8::internal::JSProxy::GetOwnPropertyDescriptor(), v8::internal::JSReceiver::GetOwnPropertyDescriptor(), v8::Object::GetPropertyAttributes(), v8::internal::JSReceiver::GetPropertyAttributes(), v8::internal::JSProxy::GetPropertyAttributes(), v8::internal::JSModuleNamespace::GetPropertyAttributes(), v8::internal::anonymous_namespace{js-objects.cc}::GetPropertyAttributesWithInterceptorInternal(), v8::internal::anonymous_namespace{js-objects.cc}::GetPropertyDescriptorWithInterceptor(), v8::internal::Object::GetPropertyWithAccessor(), v8::internal::anonymous_namespace{js-objects.cc}::GetPropertyWithInterceptorInternal(), v8::internal::JSNumberFormat::GetRangeFormatter(), v8::Object::GetRealNamedPropertyAttributes(), v8::Object::GetRealNamedPropertyAttributesInPrototypeChain(), v8::internal::anonymous_namespace{builtins-array.cc}::GetRelativeIndex(), v8::internal::JSArrayBuffer::GetResizableBackingStorePageConfiguration(), v8::internal::temporal::GetRoundingIncrementOption(), v8::internal::temporal::GetSingleDurationField(), v8::internal::temporal::GetSingleTimeRecordField(), v8::debug::Script::GetSourceOffset(), v8::Message::GetStartColumn(), v8::internal::GetStringOption(), v8::internal::GetStringOrBooleanOption(), v8::internal::temporal::GetTemporalFractionalSecondDigitsOption(), v8::internal::JSLocale::GetTextInfo(), v8::internal::JSLocale::GetWeekInfo(), v8::internal::Object::GreaterThan(), v8::internal::Object::GreaterThanOrEqual(), v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::GrowCapacity(), v8::internal::anonymous_namespace{elements.cc}::FastSloppyArgumentsElementsAccessor::GrowCapacityAndConvertImpl(), v8::internal::anonymous_namespace{js-date-time-format.cc}::HandleDateTimeOthers(), v8::internal::anonymous_namespace{builtins-typed-array.cc}::HandleOptionsBag(), v8::Map::Has(), v8::Set::Has(), v8::internal::anonymous_namespace{runtime-forin.cc}::HasEnumerableProperty(), v8::internal::JSReceiver::HasInPrototypeChain(), v8::internal::AlwaysSharedSpaceJSObject::HasInstance(), v8::internal::JSReceiver::HasOwnProperty(), v8::internal::JSProxy::HasProperty(), v8::internal::JSReceiver::HasProperty(), v8::Object::HasRealIndexedProperty(), v8::internal::JSObject::HasRealNamedCallbackProperty(), v8::Object::HasRealNamedCallbackProperty(), v8::Object::HasRealNamedProperty(), v8::internal::anonymous_namespace{js-number-format.cc}::IcuFormatNumber(), v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::IncludesValueFastPath(), v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::IncludesValueImpl(), v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::IncludesValueImpl(), v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::IncludesValueImpl(), v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::IncludesValueImpl(), v8::internal::anonymous_namespace{elements.cc}::IncludesValueSlowPath(), v8::internal::anonymous_namespace{js-locale.cc}::InsertOptionsIntoLocale(), v8::internal::Genesis::InstallABunchOfRandomThings(), v8::internal::wasm::JSPrototypesSetup::InstallMethodImpl(), v8::Value::InstanceOf(), v8::Module::InstantiateModule(), v8::Value::Int32Value(), v8::Value::IntegerValue(), v8::internal::JsonParseInternalizer::InternalizeJsonProperty(), v8::internal::JSProxy::IsArray(), v8::internal::Object::IsArray(), v8::internal::anonymous_namespace{builtins-array.cc}::IsConcatSpreadable(), v8::internal::JSReceiver::IsExtensible(), v8::internal::anonymous_namespace{js-number-format.cc}::IsWellFormedUnitIdentifier(), v8::internal::temporal::anonymous_namespace{js-temporal-helpers.cc}::IterateDurationRecordFieldsTable(), v8::internal::anonymous_namespace{builtins-intl.cc}::LegacyFormatConstructor(), v8::internal::Object::LessThan(), v8::internal::Object::LessThanOrEqual(), v8::internal::Context::Lookup(), v8::internal::MoveMessageToPromise(), v8::internal::Factory::NewArgumentsObject(), v8::internal::JSAsyncDisposableStack::NextDisposeAsyncIteration(), v8::Value::NumberValue(), v8::internal::anonymous_namespace{builtins-object.cc}::ObjectDefineAccessor(), ObjectSetAccessor(), v8::internal::anonymous_namespace{js-display-names.cc}::LanguageNames::of(), v8::internal::anonymous_namespace{js-display-names.cc}::RegionNames::of(), v8::internal::anonymous_namespace{js-display-names.cc}::ScriptNames::of(), v8::internal::anonymous_namespace{js-display-names.cc}::KeyValueDisplayNames::of(), v8::internal::anonymous_namespace{js-display-names.cc}::DateTimeFieldNames::of(), v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::OffsetOfElementAt(), v8::internal::Isolate::OnPromiseThen(), v8::internal::JSReceiver::OrdinaryDefineOwnProperty(), v8::internal::ValueDeserializer::PeekTag(), v8::Serializer::PrepareTransfer(), v8::internal::JSProxy::PreventExtensions(), v8::internal::JSObject::PreventExtensions(), v8::internal::JSObject::PreventExtensionsWithTransition(), v8::internal::wasm::InstanceBuilder::ProcessExports(), v8::internal::ValueDeserializer::ReadHeader(), v8::ValueDeserializer::ReadHeader(), v8::internal::ValueDeserializer::ReadJSObjectProperties(), v8::internal::ValueDeserializer::ReadRawBytes(), v8::internal::ValueDeserializer::ReadRawTwoBytes(), v8::internal::ValueDeserializer::ReadTag(), v8::internal::ValueDeserializer::ReadVarint(), v8::internal::ValueDeserializer::ReadVarintLoop(), v8::internal::ValueDeserializer::ReadZigZag(), v8::internal::JsonParseInternalizer::RecurseAndApply(), v8::Promise::Resolver::Reject(), v8::internal::ValueSerializer::ReserveRawBytes(), v8::Promise::Resolver::Resolve(), v8::internal::JSCollator::ResolvedOptions(), v8::internal::JSDateTimeFormat::ResolvedOptions(), v8::internal::JSDisplayNames::ResolvedOptions(), v8::internal::JSNumberFormat::ResolvedOptions(), v8::internal::Intl::ResolveLocale(), v8::internal::JSTemporalInstant::Round(), v8::internal::RUNTIME_FUNCTION(), v8::internal::ScopeIterator::ScopeObject(), v8::internal::Serializer::ObjectSerializer::SerializeJSArrayBuffer(), v8::internal::Serializer::ObjectSerializer::SerializeJSTypedArray(), v8::Object::Set(), v8::Object::SetAccessorProperty(), v8::internal::Object::SetDataProperty(), v8::internal::Object::SetElement(), v8::internal::SyntheticModule::SetExport(), v8::internal::ErrorUtils::SetFormattedStack(), v8::internal::JSReceiver::SetIntegrityLevel(), v8::internal::RegExpUtils::SetLastIndex(), v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::SetLengthImpl(), v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::SetLengthImpl(), v8::internal::anonymous_namespace{elements.cc}::FastNonextensibleObjectElementsAccessor< Subclass, KindTraits >::SetLengthImpl(), v8::internal::anonymous_namespace{elements.cc}::FastSealedObjectElementsAccessor< Subclass, KindTraits >::SetLengthImpl(), v8::internal::anonymous_namespace{builtins-array.cc}::SetLengthProperty(), v8::internal::Intl::SetNumberFormatDigitOptions(), v8::internal::JSReceiver::SetOrCopyDataProperties(), v8::Object::SetPrivate(), v8::internal::JSProxy::SetPrivateSymbol(), v8::internal::SetPropertiesFromKeyValuePairs(), v8::internal::JSProxy::SetProperty(), v8::internal::Object::SetPropertyInternal(), v8::internal::Object::SetPropertyWithAccessor(), v8::internal::Object::SetPropertyWithDefinedSetter(), v8::internal::JSObject::SetPropertyWithFailedAccessCheck(), v8::internal::anonymous_namespace{js-objects.cc}::SetPropertyWithInterceptorInternal(), v8::internal::JSObject::SetPrototype(), v8::internal::JSProxy::SetPrototype(), v8::anonymous_namespace{api.cc}::SetPrototypeImpl(), v8::Module::SetSyntheticModuleExport(), v8::internal::ErrorUtils::ShadowRealmConstructTypeErrorCopy(), v8::TryCatch::StackTrace(), v8::internal::anonymous_namespace{ic.cc}::StoreOwnElement(), v8::internal::KeyedStoreGenericAssembler::StoreProperty(), v8::internal::JSObject::TestIntegrityLevel(), v8::internal::Isolate::ThrowAt(), v8::internal::ValueSerializer::ThrowIfOutOfMemory(), v8::internal::anonymous_namespace{js-duration-format.cc}::ToDurationRecord(), v8::internal::IntlMathematicalValue::ToFormattable(), v8::internal::temporal::ToIntegerIfIntegral(), v8::internal::temporal::anonymous_namespace{js-temporal-helpers.cc}::ToIntegerWithoutRounding(), v8::internal::temporal::ToIntegerWithTruncation(), v8::internal::anonymous_namespace{builtins-array.cc}::ArrayConcatVisitor::ToJSReceiver(), v8::internal::Intl::ToLanguageTag(), v8::internal::temporal::ToPartialDuration(), v8::internal::temporal::ToTemporalOverflowHandleUndefined(), v8::internal::temporal::ToTemporalPartialDurationRecord(), v8::internal::temporal::ToTemporalTimeRecord(), v8::internal::anonymous_namespace{js-list-format.cc}::ToUnicodeStringArray(), v8::internal::Object::TransitionAndWriteDataProperty(), v8::Value::Uint32Value(), v8::internal::UnscopableLookup(), v8::internal::JSReceiver::ValidateAndApplyPropertyDescriptor(), v8::internal::Intl::ValidateAndCanonicalizeUnicodeLocaleId(), v8::internal::anonymous_namespace{builtins-array.cc}::ArrayConcatVisitor::visit(), v8::internal::FutexEmulation::WaitAsync(), v8::internal::ValueSerializer::WriteJSObjectPropertiesSlow(), and v8::Serializer::WriteValue().
Just() [2/2]
template<class T , std::enable_if_t<!std::is_lvalue_reference_v< T >> * = nullptr>
Maybe<T> v8::Just (T && t) [inline]
Definition at line 134 of file v8-maybe.h.
                            {
  return Maybe<T>(std::move(t));
}
JustVoid()
Maybe<void> v8::JustVoid () [inline]
Definition at line 165 of file v8-maybe.h.
{ return Maybe<void>(Maybe<void>::JustTag()); }
Referenced by v8::Context::DeepFreeze(), and v8::Array::Iterate().
kAnyCppHeapPointer()
constexpr CppHeapPointerTagRange v8::kAnyCppHeapPointer (CppHeapPointerTag::kFirstTag , CppHeapPointerTag::kLastTag) [constexpr]
Referenced by v8::internal::CppGraphBuilderImpl::AddEdgeForCppHeapExternalObject(), v8::internal::ExtractEmbedderDataBackref(), v8::internal::HeapProfiler::GetDetachedJSWrapperObjects(), v8::internal::ContextSerializer::SerializeApiWrapperFields(), v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitCppHeapPointer(), v8::internal::YoungGenerationMarkingVisitor< marking_mode >::VisitCppHeapPointer(), and v8::internal::anonymous_namespace{minor-mark-sweep.cc}::VisitObjectWithCppHeapPointerField().
LengthWithoutIncompleteUtf8()
static int v8::LengthWithoutIncompleteUtf8 (char * buffer, int len) [static]
Definition at line 33 of file d8-posix.cc.
                                                              {
  int answer = len;
  // 1-byte encoding.
  static const int kUtf8SingleByteMask = 0x80;
  static const int kUtf8SingleByteValue = 0x00;
  // 2-byte encoding.
  static const int kUtf8TwoByteMask = 0xE0;
  static const int kUtf8TwoByteValue = 0xC0;
  // 3-byte encoding.
  static const int kUtf8ThreeByteMask = 0xF0;
  static const int kUtf8ThreeByteValue = 0xE0;
  // 4-byte encoding.
  static const int kUtf8FourByteMask = 0xF8;
  static const int kUtf8FourByteValue = 0xF0;
  // Subsequent bytes of a multi-byte encoding.
  static const int kMultiByteMask = 0xC0;
  static const int kMultiByteValue = 0x80;
  int multi_byte_bytes_seen = 0;
  while (answer > 0) {
    int c = buffer[answer - 1];
    // Ends in valid single-byte sequence?
    if ((c & kUtf8SingleByteMask) == kUtf8SingleByteValue) return answer;
    // Ends in one or more subsequent bytes of a multi-byte value?
    if ((c & kMultiByteMask) == kMultiByteValue) {
      multi_byte_bytes_seen++;
      answer--;
    } else {
      if ((c & kUtf8TwoByteMask) == kUtf8TwoByteValue) {
        if (multi_byte_bytes_seen >= 1) {
          return answer + 2;
        }
        return answer - 1;
      } else if ((c & kUtf8ThreeByteMask) == kUtf8ThreeByteValue) {
        if (multi_byte_bytes_seen >= 2) {
          return answer + 3;
        }
        return answer - 1;
      } else if ((c & kUtf8FourByteMask) == kUtf8FourByteValue) {
        if (multi_byte_bytes_seen >= 3) {
          return answer + 4;
        }
        return answer - 1;
      } else {
        return answer; // Malformed UTF-8.
      }
    }
  }
  return 0;
}
Referenced by GetStdout().
Load()
internal::Address v8::Load (i::Address address)
Definition at line 19 of file unwinder.cc.
                                {
  return *reinterpret_cast<i::Address*>(address);
}
Referenced by v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::Allocate(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ArrayGet(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ArrayLength(), v8::internal::wasm::TurboshaftGraphBuildingInterface::AsmjsLoadMem(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::AssertNotNull(), v8::internal::wasm::TurboshaftGraphBuildingInterface::AtomicOp(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BoundsCheckArray(), v8::internal::compiler::fast_api_call::FastApiCallBuilder::Build(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCallAndReturn(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCapiCallWrapper(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildCcallConvertFloat(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildCcallConvertFloatSat(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildDiv64Call(), v8::internal::wasm::WasmGraphBuilderBase::BuildFunctionTargetAndImplicitArg(), v8::internal::wasm::WasmGraphBuilderBase::BuildImportedFunctionTargetAndImplicitArg(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildIndirectCallTargetAndImplicitArg(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildIntToFloatConversionInstruction(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildJSToWasmWrapper(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildLoadCallTargetFromExportedFunctionData(), v8::internal::wasm::WasmGraphBuilderBase::BuildModifyThreadInWasmFlag(), v8::internal::wasm::WasmGraphBuilderBase::BuildModifyThreadInWasmFlagHelper(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildReceiverNode(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildSuspend(), v8::internal::wasm::WasmGraphBuilderBase::BuildSwitchBackFromCentralStack(), v8::internal::wasm::WasmGraphBuilderBase::BuildSwitchToTheCentralStack(), v8::internal::wasm::WasmGraphBuilderBase::BuildSwitchToTheCentralStackIfNeeded(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildWasmToJSWrapper(), v8::internal::compiler::turboshaft::WasmInJSInliningReducer< Next >::Call(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallCStackSlotToStackSlot(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallIndirectImpl(), v8::internal::wasm::WasmGraphBuilderBase::CallRuntime(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CatchCase(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CatchException(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CheckMaxSteps(), v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::DecodeExternalPointer(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitDebuggingInfo(), v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::FastApiCall(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::FindOrderedHashEntry(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GetBaseAndOffsetForImportedMutableExternRefGlobal(), GetCalleeSavedRegistersFromEntryFrame(), v8::anonymous_namespace{unwinder.cc}::GetCallerFPFromFP(), v8::internal::wasm::TurboshaftGraphBuildingInterface::GetCodeUnitImpl(), v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::GetLimitAddress(), v8::anonymous_namespace{unwinder.cc}::GetReturnAddressFromFP(), v8::internal::wasm::TurboshaftGraphBuildingInterface::GetRttFromDescriptor(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GlobalGet(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InstanceCache::Initialize(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineMemCopy(), v8::internal::CodeStubAssembler::IsPageFlagReset(), v8::internal::CodeStubAssembler::IsPageFlagSet(), v8::internal::compiler::turboshaft::StackCheckLoweringReducer< Next >::JSStackCheck(), v8::internal::compiler::RawMachineAssembler::Load(), v8::internal::compiler::CodeAssembler::Load(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Load(), v8::internal::anonymous_namespace{code-stub-assembler.cc}::MetaTableAccessor::Load(), v8::internal::CodeStubAssembler::LoadBufferData(), v8::internal::interpreter::BytecodeHandlerReducer< Next >::LoadBytecode(), v8::internal::wasm::WasmWrapperTSGraphBuilder::LoadContextFromJSFunction(), v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::LoadCounterValue(), v8::internal::compiler::turboshaft::DataViewLoweringReducer< Next >::LoadDataViewElement(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadElement(), v8::internal::wasm::WasmWrapperTSGraphBuilder::LoadExportedFunctionIndexAsSmi(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadExternalPointerFromObject(), v8::internal::FeedbackCollectorReducer< Next >::LoadFeedbackVectorSlot(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::LoadFieldByIndex(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadFixedArrayElement(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadFixedDoubleArrayElement(), v8::internal::interpreter::BytecodeHandlerReducer< Next >::LoadFromBytecodeArrayAt(), v8::internal::compiler::RawMachineAssembler::LoadFromPointer(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::LoadInstanceType(), v8::internal::wasm::WasmWrapperTSGraphBuilder::LoadInstanceType(), v8::internal::wasm::WasmWrapperTSGraphBuilder::LoadMap(), v8::internal::wasm::TurboshaftGraphBuildingInterface::LoadMem(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::LoadMem(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InstanceCache::LoadMemSize(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InstanceCache::LoadMemStart(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::LoadObjectField(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadOffHeap(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadPageFlags(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadProtectedPointerField(), v8::internal::CodeStubAssembler::LoadRuntimeFlag(), v8::internal::wasm::WasmWrapperTSGraphBuilder::LoadSharedFunctionInfo(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::LoadStackArgument(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadTrustedPointerField(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::LoadWasmTypeInfo(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::LowerGlobalSetOrGet(), v8::internal::wasm::TurboshaftGraphBuildingInterface::MemSize(), v8::internal::wasm::TurboshaftGraphBuildingInterface::MemStart(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::fast_api_call::FastApiCallBuilder::PropagateException(), v8::internal::compiler::MemoryLowering::ReduceAllocateRaw(), v8::internal::compiler::MemoryLowering::ReduceLoadElement(), v8::internal::compiler::MemoryLowering::ReduceLoadExternalPointerField(), v8::internal::compiler::MemoryLowering::ReduceLoadField(), v8::internal::compiler::MemoryLowering::ReduceLoadMap(), v8::internal::compiler::MachineOperatorReducer::ReduceTruncateInt64ToInt32(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ReduceWasmTypeCastRtt(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ReduceWasmTypeCheckRtt(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::RefAsNonNull(), v8::internal::wasm::TurboshaftGraphBuildingInterface::RefGetDesc(), v8::internal::compiler::turboshaft::GrowableStacksReducer< Next >::Return(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::RootConstant(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::RttCanon(), v8::internal::wasm::WasmWrapperTSGraphBuilder::SafeLoad(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StartFunctionBody(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::StringAt(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StringCodePointAt(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::StructGet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SubtypeCheck(), v8::internal::wasm::TurboshaftGraphBuildingInterface::TableGet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::TableSize(), v8::internal::wasm::TurboshaftGraphBuildingInterface::TableSize(), v8::internal::wasm::WasmWrapperTSGraphBuilder::ToJS(), v8::internal::compiler::RawMachineAssembler::UnalignedLoad(), v8::internal::compiler::SimplifiedLoweringVerifier::VisitNode(), v8::internal::compiler::turboshaft::GrowableStacksReducer< Next >::WasmStackCheck(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::WellKnown_FastApi().
MakeDelayedTasksPlatform()
std::unique_ptr< Platform > v8::MakeDelayedTasksPlatform (std::unique_ptr< Platform > platform, int64_t random_seed)
Definition at line 356 of file d8-platforms.cc.
                                                           {
  if (random_seed) {
    return std::make_unique<DelayedTasksPlatform>(std::move(platform),
                                                  random_seed);
  }
  return std::make_unique<DelayedTasksPlatform>(std::move(platform));
}
Referenced by v8::Shell::Main().
MakePredictablePlatform()
std::unique_ptr< Platform > v8::MakePredictablePlatform (std::unique_ptr< Platform > platform)
Definition at line 116 of file d8-platforms.cc.
                                      {
  return std::make_unique<PredictablePlatform>(std::move(platform));
}
Referenced by v8::Shell::Main().
mkdirp()
static bool v8::mkdirp (Isolate * isolate, char * directory, mode_t mask) [static]
Definition at line 542 of file d8-posix.cc.
                                                                   {
  int result = mkdir(directory, mask);
  if (result == 0) return true;
  if (errno == EEXIST) {
    return CheckItsADirectory(isolate, directory);
  } else if (errno == ENOENT) { // Intermediate path element is missing.
    char* last_slash = strrchr(directory, '/');
    if (last_slash == nullptr) {
      isolate->ThrowError(v8_strerror(isolate, errno));
      return false;
    }
    *last_slash = 0;
    if (!mkdirp(isolate, directory, mask)) return false;
    *last_slash = '/';
    result = mkdir(directory, mask);
    if (result == 0) return true;
    if (errno == EEXIST) {
      return CheckItsADirectory(isolate, directory);
    }
    isolate->ThrowError(v8_strerror(isolate, errno));
    return false;
  } else {
    isolate->ThrowError(v8_strerror(isolate, errno));
    return false;
  }
}
References CheckItsADirectory(), v8::base::internal::result, v8::Isolate::ThrowError(), and v8::anonymous_namespace{d8-posix.cc}::v8_strerror().
Referenced by v8::Shell::MakeDirectory().
NewContext()
Local<Context> v8::NewContext (v8::Isolate * external_isolate, v8::ExtensionConfiguration * extensions, v8::MaybeLocal< ObjectTemplate > global_template, v8::MaybeLocal< Value > global_object, size_t context_snapshot_index, i::DeserializeEmbedderFieldsCallback embedder_fields_deserializer, v8::MicrotaskQueue * microtask_queue)
Definition at line 6704 of file api.cc.
                                       {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(external_isolate);
  // TODO(jkummerow): This is for crbug.com/713699. Remove it if it doesn't
  // fail.
  // Sanity-check that the isolate is initialized and usable.
  CHECK(IsCode(i_isolate->builtins()->code(i::Builtin::kIllegal)));
  TRACE_EVENT_CALL_STATS_SCOPED(i_isolate, "v8", "V8.NewContext");
  ApiRuntimeCallStatsScope rcs_scope(i_isolate, RCCId::kAPI_Context_New);
  i::HandleScope scope(i_isolate);
  ExtensionConfiguration no_extensions;
  if (extensions == nullptr) extensions = &no_extensions;
  i::DirectHandle<i::NativeContext> env = CreateEnvironment<i::NativeContext>(
      i_isolate, extensions, global_template, global_object,
      context_snapshot_index, embedder_fields_deserializer, microtask_queue);
  if (env.is_null()) return {};
  return Utils::ToLocal(scope.CloseAndEscape(env));
}
References v8::internal::Isolate::builtins(), CHECK, v8::internal::Builtins::code(), v8::internal::DirectHandle< T >::is_null(), and TRACE_EVENT_CALL_STATS_SCOPED.
Referenced by v8::Context::FromSnapshot(), and v8::Context::New().
NewDOMFunctionTemplate()
Local<FunctionTemplate> v8::NewDOMFunctionTemplate (Isolate * isolate, JSApiInstanceType instance_type)
Definition at line 3907 of file d8.cc.
                                                       {
  return FunctionTemplate::New(
      isolate, nullptr, Local<Value>(), Local<Signature>(), 0,
      ConstructorBehavior::kAllow, SideEffectType::kHasSideEffect, nullptr,
      static_cast<uint16_t>(instance_type));
}
References kAllow, kHasSideEffect, and v8::FunctionTemplate::New().
Referenced by v8::Shell::CreateEventTargetTemplate(), and v8::Shell::CreateNodeTemplates().
NewFunctionTemplate()
static i::DirectHandle<i::FunctionTemplateInfo> v8::NewFunctionTemplate (i::Isolate * i_isolate, FunctionCallback func, bool has_prototype, SideEffectType side_effect_type = SideEffectType::kHasSideEffect) [static]
Definition at line 3258 of file wasm-js.cc.
                                                                    {
  Isolate* isolate = reinterpret_cast<Isolate*>(i_isolate);
  ConstructorBehavior behavior =
      has_prototype ? ConstructorBehavior::kAllow : ConstructorBehavior::kThrow;
  Local<FunctionTemplate> templ = FunctionTemplate::New(
      isolate, func, {}, {}, 0, behavior, side_effect_type);
  if (has_prototype) templ->ReadOnlyPrototype();
  return v8::Utils::OpenDirectHandle(*templ);
}
References kAllow, kThrow, v8::FunctionTemplate::New(), and v8::Utils::OpenDirectHandle().
Referenced by v8::internal::WasmJs::InstallModule().
NewObjectTemplate()
static i::DirectHandle<i::ObjectTemplateInfo> v8::NewObjectTemplate (i::Isolate * i_isolate) [static]
Definition at line 3270 of file wasm-js.cc.
                         {
  Isolate* isolate = reinterpret_cast<Isolate*>(i_isolate);
  Local<ObjectTemplate> templ = ObjectTemplate::New(isolate);
  return v8::Utils::OpenDirectHandle(*templ);
}
References v8::ObjectTemplate::New(), and v8::Utils::OpenDirectHandle().
Referenced by v8::internal::anonymous_namespace{wasm-js.cc}::SetDummyInstanceTemplate().
Nothing()
template<class T >
constexpr Maybe<T> v8::Nothing () [inline], [constexpr]
Definition at line 121 of file v8-maybe.h.
                                    {
  return {};
}
Referenced by v8::internal::Intl::CanonicalizeLocaleList(), v8::internal::temporal::GetSingleDurationField(), v8::internal::temporal::GetSingleTimeRecordField(), v8::internal::temporal::GetTemporalUnit(), v8::internal::anonymous_namespace{builtins-typed-array.cc}::HandleOptionsBag(), and v8::internal::temporal::ToTemporalTimeZoneIdentifier().
Null()
Local<Primitive> v8::Null (Isolate * isolate) [inline]
Definition at line 1063 of file v8-primitive.h.
                                                  {
  using S = internal::Address;
  using I = internal::Internals;
  I::CheckInitialized(isolate);
  S* slot = I::GetRootSlot(isolate, I::kNullValueRootIndex);
  return Local<Primitive>::FromSlot(slot);
}
Referenced by v8_inspector::V8InspectorImpl::associateExceptionData(), v8::anonymous_namespace{d8.cc}::ChainDynamicImportPromise(), v8_inspector::V8Debugger::collectionsEntries(), v8_inspector::V8Console::createCommandLineAPI(), v8::internal::wasm::TurboshaftGraphBuildingInterface::DefaultValue(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::GetNullPointerSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::GetPointerSlowCallback(), v8_inspector::V8Debugger::getTargetScopes(), v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::parseAdditionalSerializationParameters(), v8_inspector::V8Debugger::privateMethods(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::RefNull().
ObjectSetAccessor()
template<typename Getter , typename Setter , typename Data >
static Maybe<bool> v8::ObjectSetAccessor (Local< Context > context, Object * self, Local< Name > name, Getter getter, Setter setter, Data data, PropertyAttribute attributes, bool replace_on_access, SideEffectType getter_side_effect_type, SideEffectType setter_side_effect_type) [static]
Definition at line 4879 of file api.cc.
                                                                             {
  auto i_isolate = i::Isolate::Current();
  EnterV8NoScriptScope<> api_scope{i_isolate, context,
                                   RCCId::kAPI_Object_SetAccessor};
  if (!IsJSObject(*Utils::OpenDirectHandle(self))) return Just(false);
  auto obj = i::Cast<i::JSObject>(Utils::OpenHandle(self));
  i::DirectHandle<i::AccessorInfo> info = MakeAccessorInfo(
      i_isolate, name, getter, setter, data, replace_on_access);
  info->set_getter_side_effect_type(getter_side_effect_type);
  info->set_setter_side_effect_type(setter_side_effect_type);
  if (info.is_null()) return {};
  bool fast = obj->HasFastProperties();
  i::DirectHandle<i::Object> result;
  i::DirectHandle<i::Name> accessor_name(info->name(), i_isolate);
  i::PropertyAttributes attrs = static_cast<i::PropertyAttributes>(attributes);
  if (!i::JSObject::SetAccessor(obj, accessor_name, info, attrs)
           .ToHandle(&result)) {
    return {};
  }
  if (i::IsUndefined(*result, i_isolate)) return Just(false);
  if (fast) {
    i::JSObject::MigrateSlowToFast(obj, 0, "APISetAccessor");
  }
  return Just(true);
}
References v8::internal::Isolate::Current(), v8::internal::getter_side_effect_type, v8::internal::DirectHandle< T >::is_null(), Just(), v8::anonymous_namespace{api.cc}::MakeAccessorInfo(), v8::internal::JSObject::MigrateSlowToFast(), name, v8::Utils::OpenDirectHandle(), v8::Utils::OpenHandle(), v8::base::internal::result, v8::internal::JSObject::SetAccessor(), and v8::internal::setter.
Referenced by v8::Object::SetLazyDataProperty(), and v8::Object::SetNativeDataProperty().
operator!=() [1/3]
bool v8::operator!= (const TracedReferenceBase & lhs, const TracedReferenceBase & rhs) [inline]
Definition at line 334 of file v8-traced-handle.h.
                                                          {
  return !(lhs == rhs);
}
operator!=() [2/3]
template<typename U >
bool v8::operator!= (const TracedReferenceBase & lhs, const v8::Local< U > & rhs) [inline]
Definition at line 340 of file v8-traced-handle.h.
                                                 {
  return !(lhs == rhs);
}
operator!=() [3/3]
template<typename U >
bool v8::operator!= (const v8::Local< U > & lhs, const TracedReferenceBase & rhs) [inline]
Definition at line 346 of file v8-traced-handle.h.
                                                          {
  return !(rhs == lhs);
}
operator==() [1/3]
bool v8::operator== (const TracedReferenceBase & lhs, const TracedReferenceBase & rhs) [inline]
Definition at line 317 of file v8-traced-handle.h.
                                                          {
  return internal::HandleHelper::EqualHandles(lhs, rhs);
}
Referenced by v8::IsolateGroup::operator!=(), and v8::Local< T >::operator!=().
operator==() [2/3]
template<typename U >
bool v8::operator== (const TracedReferenceBase & lhs, const v8::Local< U > & rhs) [inline]
Definition at line 323 of file v8-traced-handle.h.
                                                 {
  return internal::HandleHelper::EqualHandles(lhs, rhs);
}
operator==() [3/3]
template<typename U >
bool v8::operator== (const v8::Local< U > & lhs, const TracedReferenceBase & rhs) [inline]
Definition at line 329 of file v8-traced-handle.h.
                                                          {
  return rhs == lhs;
}
PrintMessageCallback()
static void v8::PrintMessageCallback (Local< Message > message, Local< Value > error) [static]
Definition at line 4255 of file d8.cc.
                                                                             {
  Isolate* isolate = Isolate::GetCurrent();
  switch (message->ErrorLevel()) {
    case v8::Isolate::kMessageWarning:
    case v8::Isolate::kMessageLog:
    case v8::Isolate::kMessageInfo:
    case v8::Isolate::kMessageDebug: {
      break;
    }
    case v8::Isolate::kMessageError: {
      Shell::ReportException(isolate, message, error);
      return;
    }
    default: {
      UNREACHABLE();
    }
  }
  // Converts a V8 value to a C string.
  auto ToCString = [](const v8::String::Utf8Value& value) {
    return *value ? *value : "<string conversion failed>";
  };
  v8::String::Utf8Value msg(isolate, message->Get());
  const char* msg_string = ToCString(msg);
  // Print (filename):(line number): (message).
  v8::String::Utf8Value filename(isolate,
                                 message->GetScriptOrigin().ResourceName());
  const char* filename_string = ToCString(filename);
  Maybe<int> maybeline = message->GetLineNumber(isolate->GetCurrentContext());
  int linenum = maybeline.IsJust() ? maybeline.FromJust() : -1;
  printf("%s:%i: %s\n", filename_string, linenum, msg_string);
}
References v8::Maybe< T >::FromJust(), v8::Isolate::GetCurrent(), v8::Isolate::GetCurrentContext(), v8::Maybe< T >::IsJust(), v8::Isolate::kMessageDebug, v8::Isolate::kMessageError, v8::Isolate::kMessageInfo, v8::Isolate::kMessageLog, v8::Isolate::kMessageWarning, v8::Shell::ReportException(), UNREACHABLE, and v8::internal::value.
Referenced by v8::Shell::Initialize().
REGEXP_FLAG_ASSERT_EQ() [1/9]
v8::REGEXP_FLAG_ASSERT_EQ (kGlobal)
REGEXP_FLAG_ASSERT_EQ() [2/9]
v8::REGEXP_FLAG_ASSERT_EQ (kHasIndices)
REGEXP_FLAG_ASSERT_EQ() [3/9]
v8::REGEXP_FLAG_ASSERT_EQ (kIgnoreCase)
REGEXP_FLAG_ASSERT_EQ() [4/9]
v8::REGEXP_FLAG_ASSERT_EQ (kLinear)
REGEXP_FLAG_ASSERT_EQ() [5/9]
v8::REGEXP_FLAG_ASSERT_EQ (kMultiline)
REGEXP_FLAG_ASSERT_EQ() [6/9]
v8::REGEXP_FLAG_ASSERT_EQ (kNone)
REGEXP_FLAG_ASSERT_EQ() [7/9]
v8::REGEXP_FLAG_ASSERT_EQ (kSticky)
REGEXP_FLAG_ASSERT_EQ() [8/9]
v8::REGEXP_FLAG_ASSERT_EQ (kUnicode)
REGEXP_FLAG_ASSERT_EQ() [9/9]
v8::REGEXP_FLAG_ASSERT_EQ (kUnicodeSets)
RegisterExtension()
void v8::RegisterExtension (std::unique_ptr< Extension > extension)
Definition at line 490 of file api.cc.
                                                           {
  RegisteredExtension::Register(std::move(extension));
}
References v8::RegisteredExtension::Register().
Referenced by v8::internal::Bootstrapper::InitializeOncePerProcess().
SharedMemoryHandleFromFileDescriptor()
PlatformSharedMemoryHandle v8::SharedMemoryHandleFromFileDescriptor (int fd) [inline]
Definition at line 749 of file v8-platform.h.
                                                                               {
  return static_cast<PlatformSharedMemoryHandle>(fd);
}
TimeIsOut()
static bool v8::TimeIsOut (const struct timeval & start_time, const int & total_time) [static]
Definition at line 116 of file d8-posix.cc.
                                                                               {
  if (total_time == -1) return false;
  struct timeval time_now;
  gettimeofday(&time_now, nullptr);
  // Careful about overflow.
  int seconds = static_cast<int>(time_now.tv_sec - start_time.tv_sec);
  if (seconds > 100) {
    if (seconds * 1000 > total_time) return true;
    return false;
  }
  int useconds = static_cast<int>(time_now.tv_usec - start_time.tv_usec);
  if (seconds * 1000000 + useconds > total_time * 1000) {
    return true;
  }
  return false;
}
References v8::internal::seconds.
Referenced by GetStdout(), and WaitForChild().
to_array() [1/2]
template<class T , std::size_t N>
constexpr std::array<std::remove_cv_t<T>, N> v8::to_array (T(&&) a[N]) [constexpr]
Definition at line 316 of file v8-memory-span.h.
                {
  return detail::to_array_rvalue_impl(std::move(a),
                                      std::make_index_sequence<N>{});
}
References v8::detail::to_array_rvalue_impl().
to_array() [2/2]
template<class T , std::size_t N>
constexpr std::array<std::remove_cv_t<T>, N> v8::to_array (T(&) a[N]) [constexpr]
Definition at line 311 of file v8-memory-span.h.
                                                                           {
  return detail::to_array_lvalue_impl(a, std::make_index_sequence<N>{});
}
References v8::detail::to_array_lvalue_impl().
Referenced by v8::internal::CodeStubAssembler::CopyFixedArrayElements(), v8::internal::CodeStubAssembler::CopyPropertyArrayValues(), and v8::internal::GrowableFixedArray::ResizeFixedArray().
ToApiHandle()
template<class T >
v8::Local<T> v8::ToApiHandle (i::DirectHandle< i::Object > obj) [inline]
Definition at line 312 of file api.h.
                                                          {
  return Utils::Convert<i::Object, T>(obj);
}
ToCData() [1/2]
template<typename T , internal::ExternalPointerTag tag>
T v8::ToCData (i::Isolate * isolate, i::Tagged< i::Object > obj) [inline]
Definition at line 25 of file api-inl.h.
                                                          {
  static_assert(sizeof(T) == sizeof(i::Address));
  if (obj == i::Smi::zero()) return nullptr;
  return reinterpret_cast<T>(
      i::Cast<i::Foreign>(obj)->foreign_address<tag>(isolate));
}
References v8::internal::Smi::zero().
Referenced by v8::internal::anonymous_namespace{execution.cc}::Invoke().
ToCData() [2/2]
template<internal::ExternalPointerTag tag>
i::Address v8::ToCData (i::Isolate * isolate, i::Tagged< i::Object > obj) [inline]
Definition at line 33 of file api-inl.h.
                                                                 {
  if (obj == i::Smi::zero()) return i::kNullAddress;
  return i::Cast<i::Foreign>(obj)->foreign_address<tag>(isolate);
}
References v8::base::kNullAddress, and v8::internal::Smi::zero().
ToInternal() [1/4]
static i::CpuProfile* v8::ToInternal (const CpuProfile * profile) [static]
Definition at line 11392 of file api.cc.
                                                          {
  return const_cast<i::CpuProfile*>(
      reinterpret_cast<const i::CpuProfile*>(profile));
}
Referenced by v8::HeapSnapshot::Delete(), v8::HeapGraphNode::GetChild(), v8::HeapGraphNode::GetChildrenCount(), v8::HeapGraphEdge::GetFromNode(), v8::HeapGraphNode::GetId(), v8::HeapSnapshot::GetMaxSnapshotJSObjectId(), v8::HeapGraphEdge::GetName(), v8::HeapGraphNode::GetName(), v8::HeapSnapshot::GetNode(), v8::HeapSnapshot::GetNodeById(), v8::HeapSnapshot::GetNodesCount(), v8::HeapSnapshot::GetRoot(), v8::HeapGraphNode::GetShallowSize(), v8::HeapGraphEdge::GetToNode(), v8::HeapGraphEdge::GetType(), v8::HeapGraphNode::GetType(), v8::ArrayBuffer::New(), v8::SharedArrayBuffer::New(), v8::CpuProfile::Serialize(), and v8::HeapSnapshot::Serialize().
ToInternal() [2/4]
static i::HeapGraphEdge* v8::ToInternal (const HeapGraphEdge * edge) [static]
Definition at line 11599 of file api.cc.
                                                             {
  return const_cast<i::HeapGraphEdge*>(
      reinterpret_cast<const i::HeapGraphEdge*>(edge));
}
ToInternal() [3/4]
static i::HeapEntry* v8::ToInternal (const HeapGraphNode * entry) [static]
Definition at line 11638 of file api.cc.
                                                          {
  return const_cast<i::HeapEntry*>(
      reinterpret_cast<const i::HeapEntry*>(entry));
}
ToInternal() [4/4]
static i::HeapSnapshot* v8::ToInternal (const HeapSnapshot * snapshot) [static]
Definition at line 11667 of file api.cc.
                                                               {
  return const_cast<i::HeapSnapshot*>(
      reinterpret_cast<const i::HeapSnapshot*>(snapshot));
}
True()
Local<Boolean> v8::True (Isolate * isolate) [inline]
Definition at line 1071 of file v8-primitive.h.
                                                {
  using S = internal::Address;
  using I = internal::Internals;
  I::CheckInitialized(isolate);
  S* slot = I::GetRootSlot(isolate, I::kTrueValueRootIndex);
  return Local<Boolean>::FromSlot(slot);
}
Referenced by v8_inspector::ValueMirror::getInternalProperties(), v8::Boolean::New(), and v8::InspectorClient::SendInspectorMessage().
TryCopyAndConvertArrayToCppBuffer()
template<const CTypeInfo * type_info, typename T >
bool v8::TryCopyAndConvertArrayToCppBuffer (Local< Array > src, T * dst, uint32_t max_length) [inline]
Definition at line 491 of file api-inl.h.
                                                                             {
  return CopyAndConvertArrayToCppBuffer<type_info->GetId(), T>(src, dst,
                                                               max_length);
}
References CopyAndConvertArrayToCppBuffer().
TryHandleWebAssemblyTrapPosix()
bool v8::TryHandleWebAssemblyTrapPosix (int sig_code, siginfo_t * info, void * context)
This function determines whether a memory access violation has been an out-of-bounds memory access in WebAssembly.
If so, it will modify the context parameter and add a return address where the execution can continue after the signal handling, and return true. Otherwise, false will be returned.
The parameters to this function correspond to those passed to a Posix signal handler. Use this function only on Linux and Mac.
Parameters
sig_code The signal code, e.g. SIGSEGV.
info A pointer to the siginfo_t struct provided to the signal handler.
context A pointer to a ucontext_t struct provided to the signal handler.
TryHandleWebAssemblyTrapWindows()
bool v8::TryHandleWebAssemblyTrapWindows (EXCEPTION_POINTERS * exception)
This function determines whether a memory access violation has been an out-of-bounds memory access in WebAssembly.
If so, it will modify the exception parameter and add a return address where the execution can continue after the exception handling, and return true. Otherwise the return value will be false.
The parameter to this function corresponds to the one passed to a Windows vectored exception handler. Use this function only on Windows.
Parameters
exception An EXCEPTION_POINTERS* as provided to the exception handler.
TryToCopyAndConvertArrayToCppBuffer() [1/2]
template<CTypeInfo::Identifier type_info_id, typename T >
bool V8_WARN_UNUSED_RESULT v8::TryToCopyAndConvertArrayToCppBuffer (Local< Array > src, T * dst, uint32_t max_length) [inline]
Copies the contents of this JavaScript array to a C++ buffer with a given max_length.
A CTypeInfo is passed as an argument, instructing different rules for conversion (e.g. restricted float/double). The element type T of the destination array must match the C type corresponding to the CTypeInfo (specified by CTypeInfoTraits). If the array length is larger than max_length or the array is of unsupported type, the operation will fail, returning false. Generally, an array which contains objects, undefined, null or anything not convertible to the requested destination type, is considered unsupported. The operation returns true on success. type_info will be used for conversions.
Definition at line 499 of file api-inl.h.
                                                                               {
  return CopyAndConvertArrayToCppBuffer<type_info_id, T>(src, dst, max_length);
}
Referenced by v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllSequenceFastCallback().
TryToCopyAndConvertArrayToCppBuffer() [2/2]
template<CTypeInfo::Identifier type_info_id, typename T >
bool v8::TryToCopyAndConvertArrayToCppBuffer (Local< Array > src, T * dst, uint32_t max_length) [inline]
Copies the contents of this JavaScript array to a C++ buffer with a given max_length.
A CTypeInfo is passed as an argument, instructing different rules for conversion (e.g. restricted float/double). The element type T of the destination array must match the C type corresponding to the CTypeInfo (specified by CTypeInfoTraits). If the array length is larger than max_length or the array is of unsupported type, the operation will fail, returning false. Generally, an array which contains objects, undefined, null or anything not convertible to the requested destination type, is considered unsupported. The operation returns true on success. type_info will be used for conversions.
Definition at line 499 of file api-inl.h.
                                                                               {
  return CopyAndConvertArrayToCppBuffer<type_info_id, T>(src, dst, max_length);
}
Referenced by v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllSequenceFastCallback().
Unaligned()
static bool v8::Unaligned (const uint16_t * chars) [inline], [static]
Definition at line 5580 of file api.cc.
                                                    {
  return reinterpret_cast<const uintptr_t>(chars) & kAlignmentMask;
}
References kAlignmentMask.
Referenced by v8::ContainsOnlyOneByteHelper::VisitTwoByteString().
Undefined()
Local<Primitive> v8::Undefined (Isolate * isolate) [inline]
Definition at line 1055 of file v8-primitive.h.
                                                       {
  using S = internal::Address;
  using I = internal::Internals;
  I::CheckInitialized(isolate);
  S* slot = I::GetRootSlot(isolate, I::kUndefinedValueRootIndex);
  return Local<Primitive>::FromSlot(slot);
}
Referenced by v8_inspector::V8Console::CommandLineAPIScope::accessorSetterCallback(), v8_inspector::InjectedScript::ProtocolPromiseHandler::catchCallback(), v8::anonymous_namespace{api.cc}::CreateInterceptorInfo(), v8_inspector::generateCustomPreview(), v8::Function::GetBoundFunction(), v8::Isolate::GetContinuationPreservedEmbedderData(), v8::Isolate::GetContinuationPreservedEmbedderDataV2(), v8::Object::GetOwnPropertyDescriptor(), v8_inspector::V8Console::inspectedObject(), v8::Shell::JSONModuleEvaluationSteps(), v8_inspector::InjectedScript::lastEvaluationResult(), v8::FunctionCallbackInfo< T >::operator[](), v8::debug::ConsoleCallArguments::operator[](), v8::Worker::PostMessageOut(), v8::AsyncHooks::PromiseHookDispatch(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::ResetCounts(), v8_inspector::InjectedScript::resolveCallArgument(), v8::TryCatch::ReThrow(), v8::SetTimeoutTask::Run(), v8::internal::anonymous_namespace{gc-extension.cc}::AsyncGC::RunInternal(), v8::InspectorClient::runMessageLoopOnPause(), v8_inspector::V8Console::runTask(), v8::InspectorFrontend::Send(), v8::InspectorClient::SendInspectorMessage(), v8::ObjectTemplate::SetAccessCheckCallback(), v8::ObjectTemplate::SetAccessCheckCallbackAndHandler(), v8::FunctionTemplate::SetCallHandler(), v8::Isolate::SetContinuationPreservedEmbedderData(), v8::Isolate::SetContinuationPreservedEmbedderDataV2(), v8::Shell::SetPromiseHooks(), v8::Shell::Stringify(), v8_inspector::InjectedScript::ProtocolPromiseHandler::thenCallback(), v8::Isolate::ThrowException(), v8::Shell::TriggerOnProfileEndListener(), and v8::Shell::WorkerPostMessage().
WaitForChild()
static bool v8::WaitForChild (Isolate * isolate, int pid, ZombieProtector & child_waiter, const struct timeval & start_time, int read_timeout, int total_timeout) [static]
Definition at line 352 of file d8-posix.cc.
                                            {
#ifdef HAS_WAITID
  siginfo_t child_info;
  child_info.si_pid = 0;
  int useconds = 1;
  // Wait for child to exit.
  while (child_info.si_pid == 0) {
    waitid(P_PID, pid, &child_info, WEXITED | WNOHANG | WNOWAIT);
    usleep(useconds);
    if (useconds < 1000000) useconds <<= 1;
    if ((read_timeout != -1 && useconds / 1000 > read_timeout) ||
        (TimeIsOut(start_time, total_timeout))) {
      isolate->ThrowError("Timed out waiting for process to terminate");
      kill(pid, SIGINT);
      return false;
    }
  }
  if (child_info.si_code == CLD_KILLED) {
    char message[999];
    snprintf(message, sizeof(message), "Child killed by signal %d",
             child_info.si_status);
    isolate->ThrowError(message);
    return false;
  }
  if (child_info.si_code == CLD_EXITED && child_info.si_status != 0) {
    char message[999];
    snprintf(message, sizeof(message), "Child exited with status %d",
             child_info.si_status);
    isolate->ThrowError(message);
    return false;
  }
#else // No waitid call.
  int child_status;
  waitpid(pid, &child_status, 0); // We hang here if the child doesn't exit.
  child_waiter.ChildIsDeadNow();
  if (WIFSIGNALED(child_status)) {
    char message[999];
    snprintf(message, sizeof(message), "Child killed by signal %d",
             WTERMSIG(child_status));
    isolate->ThrowError(message);
    return false;
  }
  if (WEXITSTATUS(child_status) != 0) {
    char message[999];
    int exit_status = WEXITSTATUS(child_status);
    snprintf(message, sizeof(message), "Child exited with status %d",
             exit_status);
    isolate->ThrowError(message);
    return false;
  }
#endif // No waitid call.
  return true;
}
References v8::ZombieProtector::ChildIsDeadNow(), v8::Isolate::ThrowError(), and TimeIsOut().
Referenced by v8::Shell::System().
WaitOnFD()
static bool v8::WaitOnFD (int fd, int read_timeout, int total_timeout, const struct timeval & start_time) [static]
Definition at line 85 of file d8-posix.cc.
                                                       {
  fd_set readfds, writefds, exceptfds;
  struct timeval timeout;
  int gone = 0;
  if (total_timeout != -1) {
    struct timeval time_now;
    gettimeofday(&time_now, nullptr);
    time_t seconds = time_now.tv_sec - start_time.tv_sec;
    gone = static_cast<int>(seconds * 1000 +
                            (time_now.tv_usec - start_time.tv_usec) / 1000);
    if (gone >= total_timeout) return false;
  }
  FD_ZERO(&readfds);
  FD_ZERO(&writefds);
  FD_ZERO(&exceptfds);
  FD_SET(fd, &readfds);
  FD_SET(fd, &exceptfds);
  if (read_timeout == -1 ||
      (total_timeout != -1 && total_timeout - gone < read_timeout)) {
    read_timeout = total_timeout - gone;
  }
  timeout.tv_usec = (read_timeout % 1000) * 1000;
  timeout.tv_sec = read_timeout / 1000;
  int number_of_fds_ready = select(fd + 1, &readfds, &writefds, &exceptfds,
                                   read_timeout != -1 ? &timeout : nullptr);
  return number_of_fds_ready == 1;
}
References v8::internal::seconds.
Referenced by GetStdout().
WriteAndFlush()
void v8::WriteAndFlush (FILE * file, const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 2970 of file d8.cc.
                                                                {
  DCHECK(i::ValidateCallbackInfo(info));
  WriteToFile(file, info);
  fprintf(file, "\n");
  fflush(file);
}
References DCHECK, file(), v8::internal::ValidateCallbackInfo(), and WriteToFile().
Referenced by v8::Shell::Print(), and v8::Shell::PrintErr().
WriteHelper()
template<typename CharType >
static int v8::WriteHelper (i::Isolate * i_isolate, const String * string, CharType * buffer, int start, int length, int options) [inline], [static]
Definition at line 5863 of file api.cc.
                                           {
  ApiRuntimeCallStatsScope rcs_scope(i_isolate, RCCId::kAPI_String_Write);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  DCHECK(start >= 0 && length >= -1);
  auto str = Utils::OpenDirectHandle(string);
  int end = start + length;
  if ((length == -1) || (static_cast<uint32_t>(length) > str->length() - start))
    end = str->length();
  if (end < 0) return 0;
  int write_length = end - start;
  if (start < end) i::String::WriteToFlat(*str, buffer, start, write_length);
  if (!(options & String::NO_NULL_TERMINATION) &&
      (length == -1 || write_length < length)) {
    buffer[write_length] = '\0';
  }
  return write_length;
}
References DCHECK, v8::internal::compiler::end(), v8::internal::length, v8::String::NO_NULL_TERMINATION, v8::Utils::OpenDirectHandle(), and v8::internal::String::WriteToFlat().
Referenced by v8::String::Write(), and v8::String::WriteOneByte().
WriteHelperV2()
template<typename CharType >
static void v8::WriteHelperV2 (i::Isolate * i_isolate, const String * string, CharType * buffer, uint32_t offset, uint32_t length, int flags) [inline], [static]
Definition at line 5896 of file api.cc.
                                                             {
  ApiRuntimeCallStatsScope rcs_scope(i_isolate, RCCId::kAPI_String_Write);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  DCHECK_LE(length, string->Length());
  DCHECK_LE(offset, string->Length() - length);
  auto str = Utils::OpenDirectHandle(string);
  i::String::WriteToFlat(*str, buffer, offset, length);
  if (flags & String::WriteFlags::kNullTerminate) {
    buffer[length] = '\0';
  }
}
References DCHECK_LE, flags(), v8::String::WriteFlags::kNullTerminate, v8::internal::length, v8::Utils::OpenDirectHandle(), v8::internal::string, and v8::internal::String::WriteToFlat().
Referenced by v8::String::WriteOneByteV2(), and v8::String::WriteV2().
WriteToFile()
void v8::WriteToFile (FILE * file, const v8::FunctionCallbackInfo< v8::Value > & info, int first_arg_index = 0)
Definition at line 2939 of file d8.cc.
                                          {
  for (int i = first_arg_index; i < info.Length(); i++) {
    HandleScope handle_scope(info.GetIsolate());
    if (i != first_arg_index) {
      fprintf(file, " ");
    }
    // Explicitly catch potential exceptions in toString().
    v8::TryCatch try_catch(info.GetIsolate());
    Local<Value> arg = info[i];
    Local<String> str_obj;
    if (arg->IsSymbol()) {
      arg = arg.As<Symbol>()->Description(info.GetIsolate());
    }
    if (!arg->ToString(info.GetIsolate()->GetCurrentContext())
             .ToLocal(&str_obj)) {
      try_catch.ReThrow();
      return;
    }
    v8::String::Utf8Value str(info.GetIsolate(), str_obj);
    size_t n = fwrite(*str, sizeof(**str), str.length(), file);
    if (n != str.length()) {
      printf("Error in fwrite\n");
      base::OS::ExitProcess(1);
    }
  }
}
References v8::Local< T >::As(), v8::base::OS::ExitProcess(), file(), v8::Isolate::GetCurrentContext(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::FunctionCallbackInfo< T >::Length(), v8::String::Utf8Value::length(), and v8::TryCatch::ReThrow().
Referenced by v8::D8Console::Assert(), v8::D8Console::Debug(), v8::D8Console::Error(), v8::D8Console::Info(), v8::D8Console::Log(), v8::D8Console::Warn(), WriteAndFlush(), v8::Shell::WriteFile(), and v8::Shell::WriteStdout().
Variable Documentation
check_d8_flag_contradictions
bool v8::check_d8_flag_contradictions = true
Definition at line 557 of file d8.cc.
Referenced by v8::ShellOptions::DisallowReassignment< T, kAllowIdenticalAssignment >::operator=(), and v8::Shell::SetOptions().
dummy_delegate
v8::debug::DebugDelegate v8::dummy_delegate [static]
Definition at line 2787 of file d8.cc.
Referenced by v8::Shell::EnableDebugger().
else
v8::else
Initial value:
{
    return target_constant_address_at(pc)
Definition at line 1619 of file assembler-riscv.cc.
g_oom_error_callback
OOMErrorCallback v8::g_oom_error_callback = nullptr [static]
Definition at line 187 of file api.cc.
Referenced by v8::V8::SetFatalMemoryErrorCallback().
kAcquireLoad
constexpr AcquireLoadTag v8::kAcquireLoad [static], [constexpr]
Definition at line 2942 of file globals.h.
Referenced by v8::internal::JSFunction::abstract_code(), v8::internal::compiler::anonymous_namespace{access-info.cc}::AccessorAccessInfoHelper(), v8::internal::ScriptContextTable::Add(), v8::internal::StringForwardingTable::AddExternalResourceAndHash(), v8::internal::StringForwardingTable::AddForwardString(), v8::internal::LiveObjectRange::iterator::AdvanceToNextMarkedObject(), v8::internal::FeedbackMetadata::AllocatedSize(), v8::internal::TaggedArrayBase< Derived, ShapeT, Super >::AllocatedSize(), v8::internal::PrimitiveArrayBase< Derived, ShapeT, Super >::AllocatedSize(), v8::internal::SeqOneByteString::AllocatedSize(), v8::internal::SeqTwoByteString::AllocatedSize(), v8::internal::FunctionTemplateInfo::AllocateFunctionTemplateRareData(), v8::internal::LookupIterator::ApplyTransitionToDataProperty(), v8::internal::compiler::AllocationSiteRef::boilerplate(), v8::internal::MegaDomHandler::BriefPrintDetails(), v8::internal::compiler::PropertyCellData::Cache(), v8::internal::compiler::JSFunctionData::Cache(), v8::internal::compiler::FunctionTemplateInfoRef::callback_data(), v8::internal::TransitionsAccessor::CanHaveMoreTransitions(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::CheckForWellKnownImport(), v8::internal::NativeRegExpMacroAssembler::CheckStackGuardState(), v8::internal::JitLogger::CodeMoveEvent(), v8::internal::ExternalLogEventListener::CodeMoveEvent(), v8::internal::JavaScriptFrame::CollectFunctionAndOffsetForICStats(), v8::internal::KeyAccumulator::CollectOwnPropertyNames(), v8::internal::KeyAccumulator::CollectPrivateNames(), v8::internal::Isolate::CollectSourcePositionsForAllBytecodeArrays(), v8::internal::PropertyArray::CompareAndSwap(), v8::internal::Compiler::CompileBaseline(), v8::internal::BackgroundMergeTask::CompleteMergeInForeground(), v8::internal::String::ComputeAndSetRawHash(), v8::internal::Factory::CopyBytecodeArray(), v8::internal::SharedFunctionInfo::CopyFrom(), v8::internal::anonymous_namespace{code-serializer.cc}::CreateInterpreterDataForDeserializedCode(), v8::internal::DebugInfo::DebugBytecodeArray(), v8::internal::DEF_ACQUIRE_GETTER(), v8::internal::DEF_GETTER(), v8::internal::JSReceiver::DeleteNormalizedProperty(), v8::internal::SharedFunctionInfo::EndPosition(), v8::internal::TransitionsAccessor::EnsureHasFullTransitionArray(), v8::internal::Name::EnsureRawHash(), v8::internal::Map::EquivalentToForElementsKindTransition(), v8::internal::Map::EquivalentToForTransition(), v8::internal::EXTERNAL_POINTER_ACCESSORS_MAYBE_READ_ONLY_HOST(), v8::internal::V8HeapExplorer::ExtractBytecodeArrayReferences(), v8::internal::V8HeapExplorer::ExtractInstructionStreamReferences(), v8::internal::V8HeapExplorer::ExtractJSObjectReferences(), v8::internal::V8HeapExplorer::ExtractPropertyReferences(), v8::internal::V8HeapExplorer::ExtractSharedFunctionInfoReferences(), v8::internal::LookupIterator::FetchValue(), v8::internal::SharedFunctionInfo::FlushBaselineCode(), v8::internal::Code::FromTargetAddress(), v8::internal::Heap::GcSafeGetCodeFromInstructionStream(), v8::internal::Heap::GcSafeInstructionStreamContains(), v8::internal::ScriptContextTable::get(), v8::internal::StatisticsExtension::GetCounters(), v8::internal::TransitionsAccessor::GetEncoding(), v8::String::GetExternalOneByteStringResource(), v8::internal::StringForwardingTable::GetExternalResource(), v8::String::GetExternalStringResourceSlow(), v8::internal::compiler::NativeContextRef::GetFunctionMapFromIndex(), v8::api_internal::GetFunctionTemplateData(), v8::internal::SourceTextModule::GetImportMeta(), v8::internal::TransitionsAccessor::GetMigrationTarget(), v8::internal::compiler::JSObjectRef::GetObjectCreateMap(), v8::internal::SharedFunctionInfo::GetOuterScopeInfo(), v8::internal::KeyAccumulator::GetOwnEnumPropertyKeys(), v8::internal::compiler::anonymous_namespace{heap-refs.cc}::GetOwnFastConstantDataPropertyFromHeap(), v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::GetPromoRecommendationSharedFunctionInfo(), v8::internal::LookupIterator::GetPropertyCell(), v8::internal::TransitionArray::GetPrototypeTransitions(), v8::internal::TransitionsAccessor::GetPrototypeTransitions(), v8::internal::StringForwardingTable::GetRawHash(), v8::internal::TransitionsAccessor::GetSimpleTransition(), v8::internal::TransitionsAccessor::GetTransitionArray(), v8::internal::SharedFunctionInfo::GetTrustedData(), v8::debug::GlobalLexicalScopeNames(), v8::internal::SharedFunctionInfo::has_simple_parameters(), v8::internal::Name::HasExternalForwardingIndex(), v8::internal::anonymous_namespace{externalize-string-extension.cc}::HasExternalForwardingIndex(), v8::anonymous_namespace{api.cc}::HasExternalStringResource(), v8::internal::Name::HasForwardingIndex(), v8::internal::Name::hash(), v8::internal::SharedFunctionInfo::HasInferredName(), v8::internal::Name::HasInternalizedForwardingIndex(), v8::internal::SharedFunctionInfo::HasOuterScopeInfo(), v8::internal::TransitionArray::HasPrototypeTransitions(), v8::internal::SharedFunctionInfo::HasSharedName(), v8::internal::BytecodeArray::HasSourcePositionTable(), v8::internal::compiler::HeapObjectData::HeapObjectData(), v8::internal::compiler::SourceTextModuleRef::import_meta(), v8::internal::anonymous_namespace{call-site-info.cc}::InferMethodName(), v8::internal::SharedFunctionInfo::InitFromFunctionLiteral(), v8::internal::Compiler::InstallInterpreterTrampolineCopy(), v8::internal::compiler::MapRef::instance_descriptors(), v8::internal::Map::InstancesNeedRewriting(), v8::internal::JSGlobalObject::InvalidatePropertyCell(), v8::internal::JSFunction::is_compiled(), v8::internal::compiler::JSTypedArrayRef::is_on_heap(), v8::internal::SharedFunctionInfo::is_script(), v8::internal::compiler::JSFunctionData::IsConsistentWithHeapState(), v8::String::IsExternalOneByte(), v8::String::IsExternalTwoByte(), v8::internal::InstructionStream::IsFullyInitialized(), v8::internal::MarkingVisitorBase< ReferenceSummarizerMarkingVisitor >::IsTrivialWeakReferenceValue(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ElementsKindDependency::IsValid(), v8::internal::Code::IsWeakObjectInOptimizedCode(), v8::internal::compiler::StringRef::length(), v8::internal::PropertyArray::length(), v8::internal::ExistingCodeLogger::LogCompiledFunctions(), v8::internal::ScriptContextTable::Lookup(), v8::internal::LookupIterator::LookupInSpecialHolder(), v8::internal::compiler::AccessInfoFactory::LookupSpecialFieldAccessorInHolder(), v8::internal::StringTable::LookupString(), v8::internal::String::MakeThin(), v8::internal::HeapObjectLayout::map(), v8::internal::compiler::HeapObjectRef::map_direct_read(), v8::internal::SharedFunctionInfo::Name(), v8::internal::SharedFunctionInfo::needs_script_context(), v8::internal::JSFunction::NeedsResetDueToFlushedBytecode(), v8::internal::FactoryBase< Impl >::NewSharedFunctionInfo(), v8::internal::anonymous_namespace{deoptimizer.cc}::DeoptimizableCodeIterator::Next(), v8::internal::Map::NumberOfFields(), v8::internal::anonymous_namespace{runtime-test.cc}::OptimizeFunctionOnNextCall(), v8::internal::DebugInfo::OriginalBytecodeArray(), v8::internal::LookupIterator::PrepareForDataProperty(), v8::internal::JSObject::PreventExtensionsWithTransition(), v8::internal::MarkCompactCollector::ProcessOldBaselineSFI(), v8::internal::Name::RawHash(), v8::internal::compiler::JSObjectRef::RawInobjectPropertyAt(), v8::internal::JSObject::RawInobjectPropertyAt(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForGlobalAccess(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForPropertyAccess(), v8::internal::HeapObject::ReadTrustedPointerField(), v8::internal::LookupIterator::ReconfigureDataProperty(), v8::internal::FieldStatsCollector::RecordStats(), v8::internal::ObjectStatsCollectorImpl::RecordVirtualCodeDetails(), v8::internal::ObjectStatsCollectorImpl::RecordVirtualJSGlobalObjectDetails(), v8::internal::InstructionStream::Relocate(), v8::internal::InstructionStream::RelocateFromDescWriteBarriers(), v8::internal::SourceTextModule::Reset(), v8::internal::Isolate::RunHostInitializeImportMetaObjectCallback(), v8::internal::ConcurrentMarking::RunMajor(), v8::internal::RUNTIME_FUNCTION(), v8::internal::compiler::SharedFunctionInfoRef::scope_info(), v8::internal::PropertyArray::set(), v8::internal::anonymous_namespace{string-table.cc}::SetInternalizedReference(), v8::internal::SharedFunctionInfo::SetName(), v8::internal::JSObject::SetNormalizedProperty(), v8::internal::JSReceiver::SetOrCopyDataProperties(), v8::internal::TransitionsAccessor::SetPrototypeTransitions(), v8::internal::SharedFunctionInfo::SetScopeInfo(), v8::internal::MarkingVisitorBase< ConcreteVisitor >::ShouldFlushBaselineCode(), v8::internal::HeapObject::SizeFromMap(), v8::internal::BytecodeArray::BodyDescriptor::SizeOf(), v8::internal::BigInt::BodyDescriptor< HandleType >::SizeOf(), v8::internal::JSObject::SlowReverseLookup(), v8::internal::BytecodeArray::SourcePosition(), v8::internal::BytecodeArray::SourceStatementPosition(), v8::internal::SharedFunctionInfo::StartPosition(), v8::internal::PropertyArray::Swap(), v8::internal::NativeContext::synchronized_script_context_table(), v8::internal::Genesis::TransferNamedProperties(), v8::internal::TransitionsAccessor::TraverseTransitionTreeInternal(), v8::internal::compiler::FixedArrayRef::TryGet(), v8::internal::Name::TryGetHash(), v8::internal::ConcurrentLookupIterator::TryGetOwnChar(), v8::internal::ConcurrentLookupIterator::TryGetPropertyCell(), v8::internal::Map::TryReplayPropertyTransitions(), v8::internal::StringTable::Data::TryStringToIndexOrLookupExisting(), v8::internal::StringForwardingTable::UpdateAfterFullEvacuation(), v8::internal::StringForwardingTable::UpdateAfterYoungEvacuation(), v8::internal::StringForwardingTable::UpdateForwardString(), v8::internal::SharedFunctionInfo::UpdateFromFunctionLiteralForLiveEdit(), v8::internal::compiler::FeedbackCellRef::value(), v8::String::VerifyExternalStringResource(), v8::String::VerifyExternalStringResourceBase(), v8::internal::IndexedReferencesExtractor::VisitEmbeddedPointer(), v8::internal::ScopeIterator::VisitScriptScope(), v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitSharedFunctionInfo(), and v8::internal::LookupIterator::WriteDataValue().
kAdd_StringConstant_Internalize_CacheSlotOffset
constexpr int v8::kAdd_StringConstant_Internalize_CacheSlotOffset = 1 [static], [constexpr]
Definition at line 2948 of file globals.h.
Referenced by v8::internal::BinaryOpAssembler::Generate_AddStringConstantInternalizeWithFeedback(), and v8::internal::anonymous_namespace{runtime-strings.cc}::StringAdd_StringConstant_Internalize().
kAlignmentMask
const uintptr_t v8::kAlignmentMask = sizeof(uintptr_t) - 1 [static]
Definition at line 5579 of file api.cc.
Referenced by v8::internal::MemoryChunk::AddressToOffset(), Align(), cppgc::internal::ObjectAllocator::AllocateObjectOnSpace(), v8::internal::MemoryChunk::BaseAddress(), v8::internal::MemoryChunk::GetAlignmentMaskForAssembler(), v8::internal::MemoryChunk::IsAligned(), and Unaligned().
kEmbedderFieldsInWeakCallback
constexpr int v8::kEmbedderFieldsInWeakCallback = 2 [static], [constexpr]
Definition at line 22 of file v8-weak-callback-info.h.
Referenced by v8::internal::GlobalHandles::Node::CollectPhantomCallbackData(), v8::WeakCallbackInfo< T >::GetInternalField(), v8::internal::GlobalHandles::PendingPhantomCallback::PendingPhantomCallback(), and v8::WeakCallbackInfo< T >::WeakCallbackInfo().
kInternalFieldsInWeakCallback
constexpr int v8::kInternalFieldsInWeakCallback = 2 [static], [constexpr]
Definition at line 21 of file v8-weak-callback-info.h.
Referenced by v8::api_internal::InternalFieldOutOfBounds().
kInvalidSharedMemoryHandle
constexpr PlatformSharedMemoryHandle v8::kInvalidSharedMemoryHandle = -1 [static], [constexpr]
Definition at line 709 of file v8-platform.h.
Referenced by v8::base::OS::CreateSharedMemoryHandleForTesting(), and v8::base::OS::DestroySharedMemoryHandle().
kOneByteMask
const uintptr_t v8::kOneByteMask = OneByteMask<sizeof(uintptr_t)>::value [static]
Definition at line 5578 of file api.cc.
Referenced by v8::ContainsOnlyOneByteHelper::VisitTwoByteString().
kPersistentContainerNotFound
const uintptr_t v8::kPersistentContainerNotFound = 0 [static]
Definition at line 29 of file v8-util.h.
Referenced by v8::PersistentValueMapBase< K, V, Traits >::Contains(), v8::StdMapTraits< K, V >::Get(), v8::PersistentValueMapBase< K, V, Traits >::PersistentValueReference::IsEmpty(), v8::StdMapTraits< K, V >::Remove(), v8::PersistentValueMapBase< K, V, Traits >::PersistentValueReference::Reset(), v8::StdMapTraits< K, V >::Set(), and v8::PersistentValueMapBase< K, V, Traits >::SetReturnValueFromVal().
kProcessGlobalPredictablePlatformWorkerTaskQueue
constexpr Isolate* v8::kProcessGlobalPredictablePlatformWorkerTaskQueue = nullptr [constexpr]
Definition at line 33 of file d8-platforms.h.
Referenced by v8::PredictablePlatform::PostTaskOnWorkerThreadImpl(), and v8::anonymous_namespace{d8.cc}::ProcessMessages().
kReadFD
const int v8::kReadFD = 0 [static]
Definition at line 247 of file d8-posix.cc.
Referenced by ChildLaunchedOK(), ExecSubprocess(), and v8::Shell::System().
kRelaxedLoad
constexpr RelaxedLoadTag v8::kRelaxedLoad [static], [constexpr]
Definition at line 2943 of file globals.h.
Referenced by v8::internal::compiler::anonymous_namespace{access-info.cc}::AccessorAccessInfoHelper(), v8::internal::DescriptorArrayMarkingState::AcquireDescriptorRangeToMark(), v8::internal::WeakArrayList::AllocatedSize(), v8::internal::DebugInfo::BreakAtEntry(), v8::internal::maglev::MaglevGraphBuilder::BuildInlineFunction(), v8::internal::compiler::JSFunctionData::Cache(), v8::internal::SharedFunctionInfo::CalculateConstructAsBuiltin(), v8::internal::Map::CanBeDeprecated(), v8::internal::DebugInfo::CanBreakAtEntry(), v8::internal::anonymous_namespace{mark-compact.cc}::RememberedSetUpdatingItem::CheckAndUpdateOldToNewSlot(), v8::internal::DebugInfo::ClearBreakAtEntry(), v8::internal::DebugInfo::ClearBreakInfo(), v8::internal::DebugInfo::ClearCoverageInfo(), v8::internal::compiler::AccessInfoFactory::ComputeAccessorDescriptorAccessInfo(), v8::internal::FeedbackNexus::ComputeCallFrequency(), v8::internal::SharedFunctionInfo::construct_as_builtin(), v8::internal::SharedFunctionInfo::CopyFrom(), v8::internal::Debug::CreateBreakInfo(), v8::internal::DebugInfo::DebugExecutionMode(), v8::internal::DEF_GETTER(), v8::internal::AllocationSite::deopt_dependent_code(), v8::internal::JSObject::DictionaryPropertyAt(), v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::DirectCollectElementIndicesImpl(), v8::internal::SharedFunctionInfo::disabled_optimization_reason(), v8::internal::SharedFunctionInfo::DisableOptimization(), v8::internal::Code::embedded_objects_cleared(), v8::internal::Scavenger::EvacuateShortcutCandidate(), v8::internal::Context::extension(), v8::internal::V8HeapExplorer::ExtractContextReferences(), v8::internal::V8HeapExplorer::ExtractMapReferences(), v8::internal::DescriptorArray::fast_iterable(), v8::internal::anonymous_namespace{scavenger.cc}::YoungGenerationConservativeStackVisitor::FilterLargeObject(), v8::internal::anonymous_namespace{scavenger.cc}::YoungGenerationConservativeStackVisitor::FilterNormalObject(), v8::internal::ConservativeStackVisitorBase< ConcreteVisitor >::FindBasePtr(), v8::internal::Map::FindFieldOwner(), v8::internal::Map::FindRootMap(), v8::internal::ScopeInfo::Flags(), v8::internal::FieldIndex::ForDescriptor(), v8::internal::TransitionsAccessor::ForEachTransitionTo(), v8::internal::ForwardingAddress(), v8::internal::Heap::GcSafeMapOfHeapObject(), v8::internal::Context::Get(), v8::internal::FeedbackVector::Get(), v8::internal::compiler::ContextRef::get(), v8::internal::WeakArrayList::Get(), v8::internal::Context::get(), v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::GetImpl(), v8::internal::Context::GetInitialJSArrayMap(), v8::internal::Context::GetNoCell(), v8::internal::anonymous_namespace{compiler.cc}::GetOrCompileOptimized(), v8::internal::Map::GetOrCreatePrototypeChainValidityCell(), v8::internal::anonymous_namespace{compiler.cc}::GetOrCreateTopLevelSharedFunctionInfo(), v8::internal::compiler::JSObjectRef::GetOwnConstantElementFromHeap(), v8::internal::compiler::anonymous_namespace{heap-refs.cc}::GetOwnFastConstantDataPropertyFromHeap(), v8::internal::TransitionsAccessor::GetTargetDetails(), v8::internal::TemplateObjectDescription::GetTemplateObject(), v8::internal::anonymous_namespace{scavenger.cc}::ObjectPinningVisitorBase< ConcreteVisitor >::HandleHeapObject(), v8::internal::DebugInfo::HasBreakInfo(), v8::internal::DebugInfo::HasCoverageInfo(), v8::internal::ScopeInfo::Hash(), v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::HasParameterMapArg(), v8::internal::SharedFunctionInfo::InitFromFunctionLiteral(), v8::internal::Debug::InstallCoverageInfo(), v8::internal::Debug::InstallDebugBreakTrampoline(), v8::internal::anonymous_namespace{js-objects.cc}::InvalidateOnePrototypeValidityCellInternal(), v8::internal::SharedFunctionInfo::is_class_constructor(), v8::internal::Code::is_context_specialized(), v8::internal::Code::is_turbofanned(), v8::internal::Context::IsElementTheHole(), v8::internal::DebugInfo::IsEmpty(), v8::internal::Heap::IsFreeSpaceValid(), v8::internal::ClearStaleLeftTrimmedPointerVisitor::IsLeftTrimmed(), v8::internal::MapWord::IsMapOrForwarded(), v8::internal::TransitionsAccessor::IsMatchingMap(), v8::internal::Map::IsPrototypeChainInvalidated(), v8::internal::Map::IsPrototypeValidityCellValid(), v8::internal::compiler::anonymous_namespace{heap-refs.cc}::IsReadOnlyLengthDescriptor(), v8::internal::HeapLayout::IsSelfForwarded(), v8::internal::anonymous_namespace{scavenger.cc}::IsUnscavengedHeapObject(), v8::internal::Code::kind(), v8::internal::SharedFunctionInfo::kind(), v8::internal::SharedFunctionInfo::language_mode(), v8::internal::compiler::JSArrayRef::length_unsafe(), v8::internal::Context::Lookup(), v8::internal::compiler::AccessInfoFactory::LookupSpecialFieldAccessorInHolder(), v8::internal::HeapObjectLayout::map_word(), v8::internal::AllocationSite::memento_found_count(), v8::internal::PretenuringHandler::MergeAllocationSitePretenuringFeedback(), v8::internal::Context::next_context_link(), v8::internal::Map::NextFreePropertyIndex(), v8::internal::TieringManager::NotifyICChanged(), v8::internal::Map::NumberOfEnumerableProperties(), v8::internal::compiler::AccessInfoFactory::ObjectMayHaveElements(), v8::internal::Parser::ParseFunction(), v8::internal::LiveEdit::PatchScript(), v8::internal::Scavenger::PinAndPushObject(), v8::internal::Debug::PrepareFunctionForDebugExecution(), v8::internal::AllocationSite::pretenure_decision(), v8::internal::Context::previous(), v8::internal::JavaScriptFrame::Print(), v8::internal::EphemeronTableUpdatingItem::Process(), v8::internal::MarkCompactCollector::ProcessOldBaselineSFI(), v8::internal::Scavenger::PromoteObject(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForCall(), v8::internal::anonymous_namespace{elements.cc}::SlowSloppyArgumentsElementsAccessor::ReconfigureImpl(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementLoadFromHeapConstant(), v8::internal::compiler::JSInliner::ReduceJSCall(), v8::internal::SharedFunctionInfo::relaxed_flags(), v8::internal::RELAXED_UINT32_ACCESSORS(), v8::internal::EvacuationWeakObjectRetainer::RetainAs(), v8::internal::Scavenger::ScavengeObject(), v8::internal::FreeListCategory::SearchForNodeInList(), v8::internal::Scavenger::SemiSpaceCopyObject(), v8::internal::Context::Set(), v8::internal::Context::set(), v8::internal::AllocationSite::set_deopt_dependent_code(), v8::internal::Code::set_embedded_objects_cleared(), v8::internal::DescriptorArray::set_fast_iterable(), v8::internal::DescriptorArray::set_fast_iterable_if(), v8::internal::SharedFunctionInfo::set_kind(), v8::internal::SharedFunctionInfo::set_language_mode(), v8::internal::AllocationSite::set_memento_found_count(), v8::internal::AllocationSite::set_pretenure_decision(), v8::internal::FunctionLiteral::set_shared_function_info(), v8::internal::DebugInfo::SetBreakAtEntry(), v8::internal::DebugInfo::SetDebugExecutionMode(), v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::SetImpl(), v8::internal::Context::SetNoCell(), v8::internal::FreeSpace::Size(), v8::internal::HeapObject::SizeFromMap(), v8::internal::FreeListCategory::SumFreeList(), v8::internal::MinorMarkSweepCollector::Sweep(), v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteralElements(), v8::internal::GlobalDictionary::TryFindPropertyCellForConcurrentLookupIterator(), v8::internal::Map::TryGetBackPointer(), v8::internal::ConcurrentLookupIterator::TryGetPropertyCell(), v8::internal::maglev::MaglevGraphBuilder::TryReadBoilerplateForFastLiteral(), v8::internal::DescriptorArrayMarkingState::TryUpdateIndicesToMark(), v8::internal::NativeContext::TypedArrayElementsKindToCtorMap(), v8::internal::NativeContext::TypedArrayElementsKindToRabGsabCtorMap(), v8::internal::Context::unchecked_previous(), v8::internal::SharedFunctionInfo::UniqueIdInScript(), v8::internal::StringForwardingTable::Block::UpdateAfterYoungEvacuation(), v8::internal::anonymous_namespace{string-forwarding-table.cc}::UpdateForwardedSlot(), v8::internal::anonymous_namespace{scavenger.cc}::GlobalHandlesWeakRootsUpdatingVisitor::UpdatePointer(), v8::internal::MarkCompactCollector::UpdatePointersInPointerTables(), v8::internal::UpdateReferenceInExternalStringTableEntry(), v8::internal::anonymous_namespace{mark-compact.cc}::UpdateSlot(), v8::internal::Heap::UpdateYoungReferenceInExternalStringTableEntry(), v8::internal::anonymous_namespace{compiler.cc}::VerifyCodeMerge(), v8::internal::EvacuateOldSpaceVisitor::Visit(), v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitEphemeronHashTable(), v8::internal::ConstantPoolPointerForwarder::VisitSharedFunctionInfo(), v8::internal::anonymous_namespace{frames.cc}::VisitSpillSlot(), v8::internal::FeedbackVector::was_once_deoptimized(), v8::internal::Heap::WeakenDescriptorArrays(), and v8::internal::MarkCompactCollector::WeakenStrongDescriptorArrays().
kRelaxedStore
constexpr RelaxedStoreTag v8::kRelaxedStore [static], [constexpr]
Definition at line 2945 of file globals.h.
Referenced by v8::internal::anonymous_namespace{runtime-classes.cc}::AddDescriptorsByTemplate(), v8::internal::LookupIterator::ApplyTransitionToDataProperty(), v8::internal::SharedFunctionInfo::CalculateConstructAsBuiltin(), v8::internal::DebugInfo::ClearBreakAtEntry(), v8::internal::DebugInfo::ClearBreakInfo(), v8::internal::DebugInfo::ClearCoverageInfo(), v8::internal::anonymous_namespace{debug-coverage.cc}::CollectAndMaybeResetCounts(), v8::internal::SharedFunctionInfo::CopyFrom(), v8::internal::Factory::CopyJSObjectWithAllocationSite(), v8::internal::ScopeInfo::Create(), v8::internal::Debug::CreateBreakInfo(), v8::internal::anonymous_namespace{heap.cc}::CreateFillerObjectAtImpl(), v8::internal::ScopeInfo::CreateForBootstrapping(), v8::internal::ScopeInfo::CreateForEmptyFunction(), v8::internal::Heap::CreateImportantReadOnlyObjects(), v8::internal::Isolate::DetachGlobal(), v8::internal::SharedFunctionInfo::DisableOptimization(), v8::internal::wasm::JumpTableAssembler::emit(), v8::internal::Scavenger::EvacuateShortcutCandidate(), v8::internal::anonymous_namespace{compiler.cc}::GetOrCompileOptimized(), v8::internal::Map::GetOrCreatePrototypeChainValidityCell(), v8::internal::ScavengerCollector::HandleSurvivingNewLargeObjects(), v8::internal::SharedFunctionInfo::Init(), v8::internal::AllocationSite::Initialize(), v8::internal::DescriptorArray::Initialize(), v8::internal::InstructionStream::Initialize(), v8::internal::Code::initialize_flags(), v8::internal::Factory::InitializeJSObjectFromMap(), v8::internal::Factory::InitializeMap(), v8::internal::anonymous_namespace{setup-heap-internal.cc}::InitializePartialMap(), v8::internal::Debug::InstallCoverageInfo(), v8::internal::ScopeInfo::mark_some_context_has_extension(), v8::internal::Scavenger::MigrateObject(), v8::internal::Factory::NewDebugInfo(), v8::internal::Factory::NewFunctionTemplateInfo(), v8::internal::Factory::NewSlowJSObjectFromMap(), v8::internal::TieringManager::NotifyICChanged(), v8::internal::TieringManager::OnInterruptTick(), v8::internal::LiveEdit::PatchScript(), v8::internal::Scavenger::PinAndPushObject(), v8::internal::Debug::PrepareFunctionForDebugExecution(), v8::internal::anonymous_namespace{js-struct.cc}::PrepareMapCommon(), v8::internal::EvacuateVisitorBase::RawMigrateObject(), v8::internal::WriteProtectedSlot< SlotT >::Relaxed_Store(), v8::internal::anonymous_namespace{scavenger.cc}::RestorePinnedObjects(), v8::internal::Coverage::SelectMode(), v8::internal::FeedbackVector::Set(), v8::internal::WeakArrayList::Set(), v8::internal::Context::set(), v8::internal::AllocationSite::set_deopt_dependent_code(), v8::internal::Code::set_embedded_objects_cleared(), v8::internal::DescriptorArray::set_fast_iterable(), v8::internal::DescriptorArray::set_fast_iterable_if(), v8::internal::SharedFunctionInfo::set_kind(), v8::internal::SharedFunctionInfo::set_language_mode(), v8::internal::HeapObject::set_map(), v8::internal::HeapObject::set_map_after_allocation(), v8::internal::HeapObject::set_map_no_write_barrier(), v8::internal::HeapObject::set_map_safe_transition(), v8::internal::HeapObject::set_map_safe_transition_no_write_barrier(), v8::internal::AllocationSite::set_memento_found_count(), v8::internal::AllocationSite::set_pretenure_decision(), v8::internal::SharedFunctionInfo::set_relaxed_flags(), v8::internal::FeedbackVector::set_was_once_deoptimized(), v8::internal::DebugInfo::SetBreakAtEntry(), v8::internal::DebugInfo::SetDebugExecutionMode(), v8::internal::HeapObject::SetFillerMap(), v8::internal::JSReceiver::SetIdentityHash(), v8::internal::ScopeInfo::SetIsDebugEvaluateScope(), v8::internal::FreeSpace::SetNext(), v8::internal::Context::SetNoCell(), v8::internal::JSReceiver::SetProperties(), v8::internal::StoreHandler::StoreTransition(), and v8::internal::EvacuateNewSpaceVisitor::TryEvacuateWithoutCopy().
kReleaseStore
constexpr ReleaseStoreTag v8::kReleaseStore [static], [constexpr]
Definition at line 2944 of file globals.h.
Referenced by v8::internal::ScriptContextTable::Add(), v8::internal::PrototypeInfo::AddDerivedMap(), v8::internal::anonymous_namespace{runtime-classes.cc}::AddDescriptorsByTemplate(), v8::internal::anonymous_namespace{literal-objects.cc}::AddToDescriptorArrayTemplate(), v8::internal::anonymous_namespace{literal-objects.cc}::AddToDictionaryTemplate(), v8::internal::FunctionTemplateInfo::AllocateFunctionTemplateRareData(), v8::internal::JSObject::AllocateStorageForMap(), v8::internal::LookupIterator::ApplyTransitionToDataProperty(), v8::internal::BackgroundMergeTask::BeginMergeInBackground(), v8::internal::ArrayLiteralBoilerplateBuilder::BuildBoilerplateDescription(), v8::internal::Factory::JSFunctionBuilder::BuildRaw(), v8::internal::BUILTIN(), v8::internal::MutableBigInt::Canonicalize(), v8::internal::SharedFunctionInfo::ClearPreparseData(), v8::internal::Compiler::CollectSourcePositions(), v8::internal::Compiler::CompileSharedWithBaseline(), v8::internal::BackgroundMergeTask::CompleteMergeInForeground(), v8::internal::Factory::CopyBytecodeArray(), v8::internal::SharedFunctionInfo::CopyFrom(), v8::internal::anonymous_namespace{bootstrapper.cc}::CreateSharedObjectConstructor(), v8::internal::JSReceiver::DeleteNormalizedProperty(), v8::internal::interpreter::InterpreterCompilationJob::DoFinalizeJobImpl(), v8::internal::JSFunction::EnsureClosureFeedbackCellArray(), v8::internal::anonymous_namespace{runtime-literals.cc}::AllocationSiteCreationContext::ExitScope(), v8::internal::EXTERNAL_POINTER_ACCESSORS(), v8::internal::InstructionStream::Finalize(), v8::internal::AccessorPair::GetComponent(), v8::internal::Compiler::GetFunctionFromEval(), v8::internal::SourceTextModule::GetImportMeta(), v8::internal::Map::GetOrCreatePrototypeInfo(), v8::internal::SharedFunctionInfo::Init(), v8::internal::anonymous_namespace{runtime-classes.cc}::InitClassPrototype(), v8::internal::InstructionStream::Initialize(), v8::internal::Genesis::InitializeGlobal(), v8::internal::Genesis::InitializeIteratorFunctions(), v8::internal::anonymous_namespace{bootstrapper.cc}::InitializeJSArrayMaps(), v8::internal::TranslatedState::InitializeJSObjectAt(), v8::internal::TranslatedState::InitializeObjectWithTaggedFieldsAt(), v8::internal::baseline::BaselineCompilerTask::Install(), v8::internal::SharedFunctionInfo::InstallDebugBytecode(), v8::internal::Genesis::InstallTypedArray(), v8::internal::anonymous_namespace{compiler.cc}::InstallUnoptimizedCode(), v8::internal::InstallWithIntrinsicDefaultProto(), v8::internal::PropertyCell::InvalidateProtector(), v8::internal::wasm::JSPrototypesSetup::MakeConstructor(), v8::internal::String::MakeExternal(), v8::internal::String::MakeExternalDuringGC(), v8::internal::String::MakeThin(), v8::internal::anonymous_namespace{js-objects.cc}::MigrateFastToFast(), v8::internal::anonymous_namespace{js-objects.cc}::MigrateFastToSlow(), v8::internal::JSObject::MigrateSlowToFast(), v8::internal::JSObject::MigrateToMap(), v8::internal::FeedbackVector::New(), v8::internal::WasmExportedFunction::New(), v8::internal::ScriptContextTable::New(), v8::internal::Factory::NewFunctionTemplateInfo(), v8::internal::Factory::NewJSGlobalObject(), v8::internal::Factory::NewMegaDomHandler(), v8::internal::FactoryBase< Impl >::NewSharedFunctionInfo(), v8::internal::Factory::NewSourceTextModule(), v8::internal::LiveEdit::PatchScript(), v8::internal::Factory::ReinitializeJSGlobalProxy(), v8::internal::TransitionsAccessor::ReplaceTransitions(), v8::internal::FeedbackCell::reset_feedback_vector(), v8::internal::Heap::RightTrimArray(), v8::internal::anonymous_namespace{bigint.cc}::RightTrimString(), v8::internal::HeapObjectLayout::set_map(), v8::internal::HeapObject::set_map(), v8::internal::HeapObject::set_map_no_write_barrier(), v8::internal::HeapObjectLayout::set_map_safe_transition(), v8::internal::HeapObject::set_map_safe_transition(), v8::internal::HeapObject::set_map_safe_transition_no_write_barrier(), v8::FunctionTemplate::SetCallHandler(), v8::internal::PropertyArray::SetHash(), v8::internal::JSObject::SetImmutableProto(), v8::internal::JSFunction::SetInitialMap(), v8::internal::Map::SetInstanceDescriptors(), v8::internal::anonymous_namespace{js-function.cc}::SetInstancePrototype(), v8::internal::anonymous_namespace{string-table.cc}::SetInternalizedReference(), v8::internal::TransitionsAccessor::SetMigrationTarget(), v8::internal::SharedFunctionInfo::SetName(), v8::internal::JSObject::SetNormalizedProperty(), v8::internal::PrototypeInfo::SetObjectCreateMap(), v8::internal::JSTypedArray::SetOffHeapDataPtr(), v8::internal::TransitionArray::SetPrototypeTransitions(), v8::internal::SharedFunctionInfo::SetScopeInfo(), v8::internal::SharedFunctionInfo::SetScript(), v8::internal::SharedFunctionInfo::SetUntrustedData(), v8::internal::anonymous_namespace{builtins-array.cc}::ArrayConcatVisitor::ToArray(), v8::internal::PropertyCell::Transition(), v8::internal::anonymous_namespace{liveedit.cc}::TranslateSourcePositionTable(), v8::internal::JSPromise::TriggerPromiseReactions(), v8::internal::SeqString::Truncate(), v8::internal::JSObject::UpdatePrototypeUserRegistration(), and v8::internal::HeapObject::WriteTrustedPointerField().
kSeqCstAccess
constexpr SeqCstAccessTag v8::kSeqCstAccess [static], [constexpr]
Definition at line 2946 of file globals.h.
Referenced by v8::internal::LookupIterator::CompareAndSwapDataValue(), v8::internal::LookupIterator::GetDataValue(), v8::internal::RUNTIME_FUNCTION(), v8::internal::LookupIterator::SwapDataValue(), and v8::internal::LookupIterator::WriteDataValue().
kTypeInfoFloat64
constexpr CTypeInfo v8::kTypeInfoFloat64 [static], [constexpr]
Initial value:
=
    CTypeInfo(CTypeInfo::Type::kFloat64)
Definition at line 771 of file v8-fast-api-calls.h.
kTypeInfoInt32
constexpr CTypeInfo v8::kTypeInfoInt32 = CTypeInfo(CTypeInfo::Type::kInt32) [static], [constexpr]
Definition at line 770 of file v8-fast-api-calls.h.
kWriteFD
const int v8::kWriteFD = 1 [static]
Definition at line 248 of file d8-posix.cc.
Referenced by ExecSubprocess(), and v8::Shell::System().