v8::internal::compiler::anonymous_namespace{code-generator-arm.cc} Namespace Reference
Classes
class OutOfLineRecordWrite
class OutOfLineFloatMin
class OutOfLineFloatMax
Typedefs
using OutOfLineFloat32Min = OutOfLineFloatMin< SwVfpRegister >
using OutOfLineFloat64Min = OutOfLineFloatMin< DwVfpRegister >
using OutOfLineFloat32Max = OutOfLineFloatMax< SwVfpRegister >
using OutOfLineFloat64Max = OutOfLineFloatMax< DwVfpRegister >
Functions
Condition FlagsConditionToCondition (FlagsCondition condition)
void FlushPendingPushRegisters (MacroAssembler *masm, FrameAccessState *frame_access_state, ZoneVector< Register > *pending_pushes)
void AdjustStackPointerForTailCall (MacroAssembler *masm, FrameAccessState *state, int new_slot_above_sp, ZoneVector< Register > *pending_pushes=nullptr, bool allow_shrinkage=true)
Typedef Documentation
OutOfLineFloat32Max
using v8::internal::compiler::anonymous_namespace{code-generator-arm.cc}::OutOfLineFloat32Max = typedef OutOfLineFloatMax<SwVfpRegister>
Definition at line 262 of file code-generator-arm.cc.
OutOfLineFloat32Min
using v8::internal::compiler::anonymous_namespace{code-generator-arm.cc}::OutOfLineFloat32Min = typedef OutOfLineFloatMin<SwVfpRegister>
Definition at line 246 of file code-generator-arm.cc.
OutOfLineFloat64Max
using v8::internal::compiler::anonymous_namespace{code-generator-arm.cc}::OutOfLineFloat64Max = typedef OutOfLineFloatMax<DwVfpRegister>
Definition at line 263 of file code-generator-arm.cc.
OutOfLineFloat64Min
using v8::internal::compiler::anonymous_namespace{code-generator-arm.cc}::OutOfLineFloat64Min = typedef OutOfLineFloatMin<DwVfpRegister>
Definition at line 247 of file code-generator-arm.cc.
Function Documentation
AdjustStackPointerForTailCall()
void v8::internal::compiler::anonymous_namespace{code-generator-arm.cc}::AdjustStackPointerForTailCall (MacroAssembler * masm, FrameAccessState * state, int new_slot_above_sp, ZoneVector< Register > * pending_pushes = nullptr, bool allow_shrinkage = true)
Definition at line 541 of file code-generator-arm.cc.
                                 {
  int current_sp_offset = state->GetSPToFPSlotCount() +
                          StandardFrameConstants::kFixedSlotCountAboveFp;
  int stack_slot_delta = new_slot_above_sp - current_sp_offset;
  if (stack_slot_delta > 0) {
    if (pending_pushes != nullptr) {
      FlushPendingPushRegisters(masm, state, pending_pushes);
    }
    masm->AllocateStackSpace(stack_slot_delta * kSystemPointerSize);
    state->IncreaseSPDelta(stack_slot_delta);
  } else if (allow_shrinkage && stack_slot_delta < 0) {
    if (pending_pushes != nullptr) {
      FlushPendingPushRegisters(masm, state, pending_pushes);
    }
    masm->add(sp, sp, Operand(-stack_slot_delta * kSystemPointerSize));
    state->IncreaseSPDelta(stack_slot_delta);
  }
}
References v8::internal::Assembler::add(), v8::internal::MacroAssembler::AllocateStackSpace(), FlushPendingPushRegisters(), v8::internal::compiler::FrameAccessState::GetSPToFPSlotCount(), v8::internal::compiler::FrameAccessState::IncreaseSPDelta(), v8::internal::CommonFrameConstants::kFixedSlotCountAboveFp, and v8::internal::kSystemPointerSize.
Referenced by v8::internal::compiler::CodeGenerator::AssembleTailCallAfterGap(), and v8::internal::compiler::CodeGenerator::AssembleTailCallBeforeGap().
FlagsConditionToCondition()
Condition v8::internal::compiler::anonymous_namespace{code-generator-arm.cc}::FlagsConditionToCondition (FlagsCondition condition)
Definition at line 265 of file code-generator-arm.cc.
                                                              {
  switch (condition) {
    case kEqual:
      return eq;
    case kNotEqual:
      return ne;
    case kSignedLessThan:
      return lt;
    case kSignedGreaterThanOrEqual:
      return ge;
    case kSignedLessThanOrEqual:
      return le;
    case kSignedGreaterThan:
      return gt;
    case kUnsignedLessThan:
      return lo;
    case kUnsignedGreaterThanOrEqual:
      return hs;
    case kUnsignedLessThanOrEqual:
      return ls;
    case kUnsignedGreaterThan:
      return hi;
    case kFloatLessThanOrUnordered:
      return lt;
    case kFloatGreaterThanOrEqual:
      return ge;
    case kFloatLessThanOrEqual:
      return ls;
    case kFloatGreaterThanOrUnordered:
      return hi;
    case kFloatLessThan:
      return lo;
    case kFloatGreaterThanOrEqualOrUnordered:
      return hs;
    case kFloatLessThanOrEqualOrUnordered:
      return le;
    case kFloatGreaterThan:
      return gt;
    case kOverflow:
      return vs;
    case kNotOverflow:
      return vc;
    case kPositiveOrZero:
      return pl;
    case kNegative:
      return mi;
    default:
      break;
  }
  UNREACHABLE();
}
References v8::internal::eq, v8::internal::ge, v8::internal::gt, v8::internal::hi, v8::internal::hs, v8::internal::compiler::kEqual, v8::internal::compiler::kFloatGreaterThan, v8::internal::compiler::kFloatGreaterThanOrEqual, v8::internal::compiler::kFloatGreaterThanOrEqualOrUnordered, v8::internal::compiler::kFloatGreaterThanOrUnordered, v8::internal::compiler::kFloatLessThan, v8::internal::compiler::kFloatLessThanOrEqual, v8::internal::compiler::kFloatLessThanOrEqualOrUnordered, v8::internal::compiler::kFloatLessThanOrUnordered, v8::internal::compiler::kNegative, v8::internal::compiler::kNotEqual, v8::internal::compiler::kNotOverflow, v8::internal::compiler::kOverflow, v8::internal::compiler::kPositiveOrZero, v8::internal::compiler::kSignedGreaterThan, v8::internal::compiler::kSignedGreaterThanOrEqual, v8::internal::compiler::kSignedLessThan, v8::internal::compiler::kSignedLessThanOrEqual, v8::internal::compiler::kUnsignedGreaterThan, v8::internal::compiler::kUnsignedGreaterThanOrEqual, v8::internal::compiler::kUnsignedLessThan, v8::internal::compiler::kUnsignedLessThanOrEqual, v8::internal::le, v8::internal::lo, v8::internal::ls, v8::internal::lt, v8::internal::mi, v8::internal::ne, v8::internal::pl, v8::internal::UNREACHABLE(), v8::internal::vc, and v8::internal::vs.
FlushPendingPushRegisters()
void v8::internal::compiler::anonymous_namespace{code-generator-arm.cc}::FlushPendingPushRegisters (MacroAssembler * masm, FrameAccessState * frame_access_state, ZoneVector< Register > * pending_pushes)
Definition at line 518 of file code-generator-arm.cc.
                                                                     {
  switch (pending_pushes->size()) {
    case 0:
      break;
    case 1:
      masm->push((*pending_pushes)[0]);
      break;
    case 2:
      masm->Push((*pending_pushes)[0], (*pending_pushes)[1]);
      break;
    case 3:
      masm->Push((*pending_pushes)[0], (*pending_pushes)[1],
                 (*pending_pushes)[2]);
      break;
    default:
      UNREACHABLE();
  }
  frame_access_state->IncreaseSPDelta(pending_pushes->size());
  pending_pushes->clear();
}
References v8::internal::ZoneVector< T >::clear(), v8::internal::compiler::FrameAccessState::IncreaseSPDelta(), v8::internal::MacroAssembler::Push(), v8::internal::MacroAssembler::push(), v8::internal::ZoneVector< T >::size(), and v8::internal::UNREACHABLE().
Referenced by AdjustStackPointerForTailCall(), and v8::internal::compiler::CodeGenerator::AssembleTailCallBeforeGap().