v8::internal::maglev::anonymous_namespace{maglev-ir-arm64.cc} Namespace Reference
Enumerations
enum class ReduceInterruptBudgetType { kLoop
, kReturn
 }
Functions
std::optional< int32_t > TryGetAddImmediateInt32ConstantInput (Node *node, int index)
std::optional< int32_t > TryGetLogicalImmediateInt32ConstantInput (Node *node, int index)
void HandleInterruptsAndTiering (MaglevAssembler *masm, ZoneLabelRef done, Node *node, ReduceInterruptBudgetType type, Register scratch0)
void GenerateReduceInterruptBudget (MaglevAssembler *masm, Node *node, Register feedback_cell, ReduceInterruptBudgetType type, int amount)
Enumeration Type Documentation
ReduceInterruptBudgetType
enum v8::internal::maglev::anonymous_namespace{maglev-ir-arm64.cc}::ReduceInterruptBudgetType [strong]
Enumerator
kLoop
kReturn
Definition at line 824 of file maglev-ir-arm64.cc.
{ kLoop, kReturn };
Function Documentation
GenerateReduceInterruptBudget()
void v8::internal::maglev::anonymous_namespace{maglev-ir-arm64.cc}::GenerateReduceInterruptBudget (MaglevAssembler * masm, Node * node, Register feedback_cell, ReduceInterruptBudgetType type, int amount)
Definition at line 878 of file maglev-ir-arm64.cc.
                                                                               {
  MaglevAssembler::TemporaryRegisterScope temps(masm);
  Register scratch = temps.Acquire();
  Register budget = scratch.W();
  __ Ldr(budget,
         FieldMemOperand(feedback_cell, FeedbackCell::kInterruptBudgetOffset));
  __ Subs(budget, budget, Immediate(amount));
  __ Str(budget,
         FieldMemOperand(feedback_cell, FeedbackCell::kInterruptBudgetOffset));
  ZoneLabelRef done(masm);
  __ JumpToDeferredIf(lt, HandleInterruptsAndTiering, done, node, type,
                      scratch);
  __ Bind(*done);
}
References __, v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::Acquire(), v8::internal::FieldMemOperand(), HandleInterruptsAndTiering(), v8::internal::lt, v8::internal::tracing::type, and v8::internal::CPURegister::W().
HandleInterruptsAndTiering()
void v8::internal::maglev::anonymous_namespace{maglev-ir-arm64.cc}::HandleInterruptsAndTiering (MaglevAssembler * masm, ZoneLabelRef done, Node * node, ReduceInterruptBudgetType type, Register scratch0)
Definition at line 826 of file maglev-ir-arm64.cc.
                                                   {
  // For loops, first check for interrupts. Don't do this for returns, as we
  // can't lazy deopt to the end of a return.
  if (type == ReduceInterruptBudgetType::kLoop) {
    Label next;
    // Here, we only care about interrupts since we've already guarded against
    // real stack overflows on function entry.
    {
      Register stack_limit = scratch0;
      __ LoadStackLimit(stack_limit, StackLimitKind::kInterruptStackLimit);
      __ Cmp(sp, stack_limit);
      __ B(&next, hi);
    }
    // An interrupt has been requested and we must call into runtime to handle
    // it; since we already pay the call cost, combine with the TieringManager
    // call.
    {
      SaveRegisterStateForCall save_register_state(masm,
                                                   node->register_snapshot());
      Register function = scratch0;
      __ Ldr(function, MemOperand(fp, StandardFrameConstants::kFunctionOffset));
      __ Push(function);
      // Move into kContextRegister after the load into scratch0, just in case
      // scratch0 happens to be kContextRegister.
      __ Move(kContextRegister, masm->native_context().object());
      __ CallRuntime(Runtime::kBytecodeBudgetInterruptWithStackCheck_Maglev, 1);
      save_register_state.DefineSafepointWithLazyDeopt(node->lazy_deopt_info());
    }
    __ B(*done); // All done, continue.
    __ Bind(&next);
  }
  // No pending interrupts. Call into the TieringManager if needed.
  {
    SaveRegisterStateForCall save_register_state(masm,
                                                 node->register_snapshot());
    Register function = scratch0;
    __ Ldr(function, MemOperand(fp, StandardFrameConstants::kFunctionOffset));
    __ Push(function);
    // Move into kContextRegister after the load into scratch0, just in case
    // scratch0 happens to be kContextRegister.
    __ Move(kContextRegister, masm->native_context().object());
    // Note: must not cause a lazy deopt!
    __ CallRuntime(Runtime::kBytecodeBudgetInterrupt_Maglev, 1);
    save_register_state.DefineSafepoint();
  }
  __ B(*done);
}
References __, v8::internal::B, v8::internal::compiler::turboshaft::anonymous_namespace{loop-unrolling-reducer.cc}::Cmp(), v8::internal::maglev::SaveRegisterStateForCall::DefineSafepoint(), v8::internal::maglev::SaveRegisterStateForCall::DefineSafepointWithLazyDeopt(), v8::internal::hi, v8::internal::kContextRegister, v8::internal::StandardFrameConstants::kFunctionOffset, v8::internal::kInterruptStackLimit, v8::internal::maglev::NodeBase::lazy_deopt_info(), v8::internal::maglev::MaglevAssembler::native_context(), v8::internal::compiler::NativeContextRef::object(), v8::internal::maglev::NodeBase::register_snapshot(), and v8::internal::tracing::type.
Referenced by GenerateReduceInterruptBudget().
TryGetAddImmediateInt32ConstantInput()
std::optional<int32_t> v8::internal::maglev::anonymous_namespace{maglev-ir-arm64.cc}::TryGetAddImmediateInt32ConstantInput (Node * node, int index)
Definition at line 26 of file maglev-ir-arm64.cc.
                                                                       {
  if (auto res = node->TryGetInt32ConstantInput(index)) {
    if (MacroAssemblerBase::IsImmAddSub(*res)) {
      return res;
    }
  }
  return {};
}
References v8::internal::index, v8::internal::Assembler::IsImmAddSub(), and v8::internal::maglev::NodeBase::TryGetInt32ConstantInput().
TryGetLogicalImmediateInt32ConstantInput()
std::optional<int32_t> v8::internal::maglev::anonymous_namespace{maglev-ir-arm64.cc}::TryGetLogicalImmediateInt32ConstantInput (Node * node, int index)
Definition at line 36 of file maglev-ir-arm64.cc.
                                                                           {
  if (auto res = node->TryGetInt32ConstantInput(index)) {
    if (*res <= 0) {
      return {};
    }
    unsigned u1, u2, u3;
    if (MacroAssemblerBase::IsImmLogical(*res, 32, &u1, &u2, &u3)) {
      return res;
    }
  }
  return {};
}
References v8::internal::index, v8::internal::Assembler::IsImmLogical(), and v8::internal::maglev::NodeBase::TryGetInt32ConstantInput().