v8::internal::compiler::anonymous_namespace{pipeline.cc} Namespace Reference
Classes
class SourcePositionWrapper
class NodeOriginsWrapper
class PipelineRunScope
class LocalIsolateScope
class PipelineJobScope
Functions
void PrintFunctionSource (OptimizedCompilationInfo *info, Isolate *isolate, int source_id, DirectHandle< SharedFunctionInfo > shared)
void PrintInlinedFunctionInfo (OptimizedCompilationInfo *info, Isolate *isolate, int source_id, int inlining_id, const OptimizedCompilationInfo::InlinedFunctionHolder &h)
void PrintParticipatingSource (OptimizedCompilationInfo *info, Isolate *isolate)
void TraceScheduleAndVerify (OptimizedCompilationInfo *info, TFPipelineData *data, Schedule *schedule, const char *phase_name)
void AddReducer (TFPipelineData *data, GraphReducer *graph_reducer, Reducer *reducer)
TurbofanPipelineStatistics * CreatePipelineStatistics (DirectHandle< Script > script, OptimizedCompilationInfo *info, Isolate *isolate, ZoneStats *zone_stats)
bool GenerateCodeFromTurboshaftGraph (Linkage *linkage, turboshaft::Pipeline &turboshaft_pipeline, PipelineImpl *turbofan_pipeline=nullptr, std::shared_ptr< OsrHelper > osr_helper={})
int HashGraphForPGO (const turboshaft::Graph *graph)
int HashGraphForPGO (const TFGraph *graph)
template<typename Graph >
int ComputeInitialGraphHash (Builtin builtin, const ProfileDataFromFile *profile_data, const Graph *graph)
const ProfileDataFromFile * ValidateProfileData (const ProfileDataFromFile *profile_data, int initial_graph_hash, const char *debug_name)
Function Documentation
AddReducer()
void v8::internal::compiler::anonymous_namespace{pipeline.cc}::AddReducer (TFPipelineData * data, GraphReducer * graph_reducer, Reducer * reducer)
Definition at line 388 of file pipeline.cc.
                                  {
  if (data->info()->source_positions()) {
    SourcePositionWrapper* const wrapper =
        data->graph_zone()->New<SourcePositionWrapper>(
            reducer, data->source_positions());
    reducer = wrapper;
  }
  if (data->info()->trace_turbo_json()) {
    NodeOriginsWrapper* const wrapper =
        data->graph_zone()->New<NodeOriginsWrapper>(reducer,
                                                    data->node_origins());
    reducer = wrapper;
  }
  graph_reducer->AddReducer(reducer);
}
References v8::internal::compiler::GraphReducer::AddReducer(), v8::internal::compiler::TFPipelineData::graph_zone(), v8::internal::compiler::TFPipelineData::info(), v8::internal::Zone::New(), v8::internal::compiler::TFPipelineData::node_origins(), and v8::internal::compiler::TFPipelineData::source_positions().
Referenced by v8::internal::compiler::InliningPhase::Run(), v8::internal::compiler::UntyperPhase::Run(), v8::internal::compiler::TypedLoweringPhase::Run(), v8::internal::compiler::EscapeAnalysisPhase::Run(), v8::internal::compiler::GenericLoweringPhase::Run(), v8::internal::compiler::EarlyOptimizationPhase::Run(), and v8::internal::compiler::LoadEliminationPhase::Run().
ComputeInitialGraphHash()
template<typename Graph >
int v8::internal::compiler::anonymous_namespace{pipeline.cc}::ComputeInitialGraphHash (Builtin builtin, const ProfileDataFromFile * profile_data, const Graph * graph)
Definition at line 2199 of file pipeline.cc.
                                                {
  int initial_graph_hash = 0;
  if (v8_flags.turbo_profiling || v8_flags.dump_builtins_hashes_to_file ||
      profile_data != nullptr) {
    initial_graph_hash = HashGraphForPGO(graph);
    if (v8_flags.dump_builtins_hashes_to_file) {
      std::ofstream out(v8_flags.dump_builtins_hashes_to_file,
                        std::ios_base::app);
      out << "Builtin: " << Builtins::name(builtin) << ", hash: 0x" << std::hex
          << initial_graph_hash << std::endl;
    }
  }
  return initial_graph_hash;
}
References graph(), HashGraphForPGO(), v8::internal::Builtins::name(), and v8::internal::v8_flags.
Referenced by v8::internal::compiler::Pipeline::GenerateCodeForTurboshaftBuiltin(), and v8::internal::compiler::CodeAssemblerCompilationJob::PrepareJobImpl().
CreatePipelineStatistics()
TurbofanPipelineStatistics* v8::internal::compiler::anonymous_namespace{pipeline.cc}::CreatePipelineStatistics (DirectHandle< Script > script, OptimizedCompilationInfo * info, Isolate * isolate, ZoneStats * zone_stats)
Definition at line 406 of file pipeline.cc.
                                             {
  TurbofanPipelineStatistics* pipeline_statistics = nullptr;
  bool tracing_enabled;
  TRACE_EVENT_CATEGORY_GROUP_ENABLED(TRACE_DISABLED_BY_DEFAULT("v8.turbofan"),
                                     &tracing_enabled);
  if (tracing_enabled || v8_flags.turbo_stats || v8_flags.turbo_stats_nvp) {
    pipeline_statistics = new TurbofanPipelineStatistics(
        info, isolate->GetTurboStatistics(), zone_stats);
    pipeline_statistics->BeginPhaseKind("V8.TFInitializing");
  }
  if (info->trace_turbo_json()) {
    TurboJsonFile json_of(info, std::ios_base::trunc);
    json_of << "{\"function\" : ";
    JsonPrintFunctionSource(json_of, -1, info->GetDebugName(), script, isolate,
                            info->shared_info());
    json_of << ",\n\"phases\":[";
  }
  return pipeline_statistics;
}
References v8::internal::compiler::TurbofanPipelineStatistics::BeginPhaseKind(), v8::internal::OptimizedCompilationInfo::GetDebugName(), v8::internal::Isolate::GetTurboStatistics(), v8::internal::compiler::JsonPrintFunctionSource(), v8::internal::script, v8::internal::OptimizedCompilationInfo::shared_info(), TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT_CATEGORY_GROUP_ENABLED, and v8::internal::v8_flags.
Referenced by v8::internal::compiler::Pipeline::GenerateCodeForTesting(), and v8::internal::compiler::Pipeline::GenerateCodeForTurboshaftBuiltin().
GenerateCodeFromTurboshaftGraph()
bool v8::internal::compiler::anonymous_namespace{pipeline.cc}::GenerateCodeFromTurboshaftGraph (Linkage * linkage, turboshaft::Pipeline & turboshaft_pipeline, PipelineImpl * turbofan_pipeline = nullptr, std::shared_ptr< OsrHelper > osr_helper = {})
Definition at line 482 of file pipeline.cc.
                                          {}) {
  turboshaft::PipelineData* turboshaft_data = turboshaft_pipeline.data();
  turboshaft_data->InitializeCodegenComponent(osr_helper);
  // Run Turboshaft instruction selection.
  if (!turboshaft_pipeline.PrepareForInstructionSelection()) return false;
  if (!turboshaft_pipeline.SelectInstructions(linkage)) return false;
  // We can release the graph now.
  turboshaft_data->ClearGraphComponent();
  if (!turboshaft_pipeline.AllocateRegisters(
          linkage->GetIncomingDescriptor())) {
    return false;
  }
  if (!turboshaft_pipeline.AssembleCode(linkage)) {
    return false;
  }
  return true;
}
Referenced by v8::internal::compiler::PipelineCompilationJob::ExecuteJobImpl(), and v8::internal::compiler::Pipeline::GenerateCodeForTesting().
HashGraphForPGO() [1/2]
int v8::internal::compiler::anonymous_namespace{pipeline.cc}::HashGraphForPGO (const TFGraph * graph)
Definition at line 2141 of file pipeline.cc.
                                          {
  AccountingAllocator allocator;
  Zone local_zone(&allocator, ZONE_NAME);
  constexpr NodeId kUnassigned = static_cast<NodeId>(-1);
  constexpr uint8_t kUnvisited = 0;
  constexpr uint8_t kOnStack = 1;
  constexpr uint8_t kVisited = 2;
  // Do a depth-first post-order traversal of the graph. For every node, hash:
  //
  // - the node's traversal number
  // - the opcode
  // - the number of inputs
  // - each input node's traversal number
  //
  // What's a traversal number? We can't use node IDs because they're not stable
  // build-to-build, so we assign a new number for each node as it is visited.
  ZoneVector<uint8_t> state(graph->NodeCount(), kUnvisited, &local_zone);
  ZoneVector<NodeId> traversal_numbers(graph->NodeCount(), kUnassigned,
                                       &local_zone);
  ZoneStack<Node*> stack(&local_zone);
  NodeId visited_count = 0;
  size_t hash = 0;
  stack.push(graph->end());
  state[graph->end()->id()] = kOnStack;
  traversal_numbers[graph->end()->id()] = visited_count++;
  while (!stack.empty()) {
    Node* n = stack.top();
    bool pop = true;
    for (Node* const i : n->inputs()) {
      if (state[i->id()] == kUnvisited) {
        state[i->id()] = kOnStack;
        traversal_numbers[i->id()] = visited_count++;
        stack.push(i);
        pop = false;
        break;
      }
    }
    if (pop) {
      state[n->id()] = kVisited;
      stack.pop();
      hash = base::hash_combine(hash, traversal_numbers[n->id()], n->opcode(),
                                n->InputCount());
      for (Node* const i : n->inputs()) {
        DCHECK(traversal_numbers[i->id()] != kUnassigned);
        hash = base::hash_combine(hash, traversal_numbers[i->id()]);
      }
    }
  }
  return Tagged<Smi>(IntToSmi(static_cast<int>(hash))).value();
}
References v8::internal::DCHECK(), graph(), v8::base::hash_combine(), v8::internal::compiler::Node::id(), v8::internal::compiler::Node::InputCount(), v8::internal::compiler::Node::inputs(), v8::internal::IntToSmi(), v8::internal::compiler::kOnStack, v8::internal::compiler::kUnvisited, v8::internal::compiler::kVisited, v8::internal::compiler::Node::opcode(), v8::internal::stack, v8::internal::CompilationJob::state(), v8::internal::Tagged< Smi >, and ZONE_NAME.
Referenced by ComputeInitialGraphHash().
HashGraphForPGO() [2/2]
int v8::internal::compiler::anonymous_namespace{pipeline.cc}::HashGraphForPGO (const turboshaft::Graph * graph)
Definition at line 2112 of file pipeline.cc.
                                                  {
  size_t hash = 0;
  for (const turboshaft::Operation& op : graph->AllOperations()) {
    VisitOperation(op, [&hash, &graph](const auto& derived) {
      const auto op_hash =
          derived.hash_value(turboshaft::HashingStrategy::kMakeSnapshotStable);
      hash = turboshaft::fast_hash_combine(hash, op_hash);
      // Use for tracing while developing:
      constexpr bool kTraceHashing = false;
      if constexpr (kTraceHashing) {
        std::cout << "[" << std::setw(3) << graph->Index(derived)
                  << "] Type: " << std::setw(30)
                  << turboshaft::OpcodeName(
                         turboshaft::operation_to_opcode_v<decltype(derived)>);
        std::cout << " + 0x" << std::setw(20) << std::left << std::hex
                  << op_hash << " => 0x" << hash << std::dec << std::endl;
      }
    });
  }
  return Tagged<Smi>(IntToSmi(static_cast<int>(hash))).value();
}
References v8::internal::compiler::turboshaft::fast_hash_combine(), graph(), v8::internal::IntToSmi(), v8::internal::compiler::turboshaft::kMakeSnapshotStable, v8::internal::compiler::turboshaft::OpcodeName(), v8::internal::compiler::turboshaft::operation_to_opcode_v, v8::internal::Tagged< Smi >, and v8::internal::compiler::turboshaft::VisitOperation().
PrintFunctionSource()
void v8::internal::compiler::anonymous_namespace{pipeline.cc}::PrintFunctionSource (OptimizedCompilationInfo * info, Isolate * isolate, int source_id, DirectHandle< SharedFunctionInfo > shared)
Definition at line 308 of file pipeline.cc.
                                                                  {
  if (!IsUndefined(shared->script(), isolate)) {
    DirectHandle<Script> script(Cast<Script>(shared->script()), isolate);
    if (!IsUndefined(script->source(), isolate)) {
      CodeTracer::StreamScope tracing_scope(isolate->GetCodeTracer());
      Tagged<Object> source_name = script->name();
      auto& os = tracing_scope.stream();
      os << "--- FUNCTION SOURCE (";
      if (IsString(source_name)) {
        os << Cast<String>(source_name)->ToCString().get() << ":";
      }
      os << shared->DebugNameCStr().get() << ") id{";
      os << info->optimization_id() << "," << source_id << "} start{";
      os << shared->StartPosition() << "} ---\n";
      {
        DisallowGarbageCollection no_gc;
        int start = shared->StartPosition();
        int len = shared->EndPosition() - start;
        SubStringRange source(Cast<String>(script->source()), no_gc, start,
                              len);
        for (auto c : source) {
          os << AsReversiblyEscapedUC16(c);
        }
      }
      os << "\n--- END ---\n";
    }
  }
}
References v8::internal::Isolate::GetCodeTracer(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::OptimizedCompilationInfo::optimization_id(), v8::internal::script, and v8::internal::CodeTracer::StreamScope::stream().
Referenced by PrintParticipatingSource().
PrintInlinedFunctionInfo()
void v8::internal::compiler::anonymous_namespace{pipeline.cc}::PrintInlinedFunctionInfo (OptimizedCompilationInfo * info, Isolate * isolate, int source_id, int inlining_id, const OptimizedCompilationInfo::InlinedFunctionHolder & h)
Definition at line 343 of file pipeline.cc.
                                                                             {
  CodeTracer::StreamScope tracing_scope(isolate->GetCodeTracer());
  auto& os = tracing_scope.stream();
  os << "INLINE (" << h.shared_info->DebugNameCStr().get() << ") id{"
     << info->optimization_id() << "," << source_id << "} AS " << inlining_id
     << " AT ";
  const SourcePosition position = h.position.position;
  if (position.IsKnown()) {
    os << "<" << position.InliningId() << ":" << position.ScriptOffset() << ">";
  } else {
    os << "<?>";
  }
  os << std::endl;
}
References v8::internal::Isolate::GetCodeTracer(), h(), v8::internal::SourcePosition::InliningId(), v8::internal::SourcePosition::IsKnown(), v8::internal::OptimizedCompilationInfo::optimization_id(), v8::internal::SourcePosition::ScriptOffset(), and v8::internal::CodeTracer::StreamScope::stream().
Referenced by PrintParticipatingSource().
PrintParticipatingSource()
void v8::internal::compiler::anonymous_namespace{pipeline.cc}::PrintParticipatingSource (OptimizedCompilationInfo * info, Isolate * isolate)
Definition at line 362 of file pipeline.cc.
                                                {
  SourceIdAssigner id_assigner(info->inlined_functions().size());
  PrintFunctionSource(info, isolate, -1, info->shared_info());
  const auto& inlined = info->inlined_functions();
  for (unsigned id = 0; id < inlined.size(); id++) {
    const int source_id = id_assigner.GetIdFor(inlined[id].shared_info);
    PrintFunctionSource(info, isolate, source_id, inlined[id].shared_info);
    PrintInlinedFunctionInfo(info, isolate, source_id, id, inlined[id]);
  }
}
References v8::internal::compiler::SourceIdAssigner::GetIdFor(), v8::internal::OptimizedCompilationInfo::inlined_functions(), PrintFunctionSource(), PrintInlinedFunctionInfo(), and v8::internal::OptimizedCompilationInfo::shared_info().
Referenced by v8::internal::compiler::PrintCode().
TraceScheduleAndVerify()
void v8::internal::compiler::anonymous_namespace{pipeline.cc}::TraceScheduleAndVerify (OptimizedCompilationInfo * info, TFPipelineData * data, Schedule * schedule, const char * phase_name)
Definition at line 374 of file pipeline.cc.
                                                    {
  RCS_SCOPE(data->runtime_call_stats(),
            RuntimeCallCounterId::kOptimizeTraceScheduleAndVerify,
            RuntimeCallStats::kThreadSpecific);
  TRACE_EVENT0(TurbofanPipelineStatistics::kTraceCategory,
               "V8.TraceScheduleAndVerify");
  TraceSchedule(info, data, schedule, phase_name);
  if (v8_flags.turbo_verify) ScheduleVerifier::Run(schedule);
}
References v8::internal::compiler::TurbofanPipelineStatistics::kTraceCategory, RCS_SCOPE, v8::internal::compiler::ScheduleVerifier::Run(), v8::internal::compiler::TFPipelineData::runtime_call_stats(), TRACE_EVENT0, v8::internal::compiler::TraceSchedule(), and v8::internal::v8_flags.
Referenced by v8::internal::compiler::PipelineImpl::ComputeScheduledGraph().
ValidateProfileData()
const ProfileDataFromFile* v8::internal::compiler::anonymous_namespace{pipeline.cc}::ValidateProfileData (const ProfileDataFromFile * profile_data, int initial_graph_hash, const char * debug_name)
Definition at line 2216 of file pipeline.cc.
                            {
  if (profile_data != nullptr && profile_data->hash() != initial_graph_hash) {
    if (v8_flags.reorder_builtins) {
      BuiltinsCallGraph::Get()->set_all_hash_matched(false);
    }
    if (v8_flags.abort_on_bad_builtin_profile_data ||
        v8_flags.warn_about_builtin_profile_data) {
      base::EmbeddedVector<char, 256> msg;
      SNPrintF(
          msg,
          "Rejected profile data for %s due to function change. "
          "Please use tools/builtins-pgo/generate.py to refresh it, you can "
          "also try adding `'checkout_pgo_profiles': True` to your .gclient "
          "file and run `gclient sync` to download the latest PGO profiles.",
          debug_name);
      if (v8_flags.abort_on_bad_builtin_profile_data) {
        // mksnapshot might fail here because of the following reasons:
        // * builtins were changed since the builtins profile generation,
        // * current build options affect builtins code and they don't match
        // the options used for building the profile (for example, it might
        // be because of gn argument 'dcheck_always_on=true').
        // To fix the issue one must either update the builtins PGO profiles
        // (see tools/builtins-pgo/generate.py) or disable builtins PGO by
        // setting gn argument v8_builtins_profiling_log_file="".
        // One might also need to update the tools/builtins-pgo/generate.py if
        // the set of default release arguments has changed.
        FATAL("%s", msg.begin());
      } else {
        PrintF("%s\n", msg.begin());
      }
    }
#ifdef LOG_BUILTIN_BLOCK_COUNT
    if (v8_flags.turbo_log_builtins_count_input) {
      PrintF("The hash came from execution count file for %s was not match!\n",
             debug_name);
    }
#endif
    return nullptr;
  }
  return profile_data;
}
References v8::base::Vector< T >::begin(), FATAL, v8::internal::BuiltinsCallGraph::Get(), v8::internal::ProfileDataFromFile::hash(), v8::internal::PrintF(), v8::internal::BuiltinsCallGraph::set_all_hash_matched(), v8::base::SNPrintF(), and v8::internal::v8_flags.
Referenced by v8::internal::compiler::Pipeline::GenerateCodeForTurboshaftBuiltin(), and v8::internal::compiler::CodeAssemblerCompilationJob::PrepareJobImpl().