v8::internal::anonymous_namespace{contexts.cc} Namespace Reference
Functions
Handle< NameToIndexHashTable > AddLocalNamesFromContext (Isolate *isolate, Handle< NameToIndexHashTable > names_table, DirectHandle< Context > script_context, bool ignore_duplicates, int script_context_index)
std::optional< int32_t > DoubleFitsInInt32 (double value)
bool IsEmptyDependentCode (Tagged< DependentCode > value, Isolate *isolate)
void NotifyContextCellStateWillChange (DirectHandle< ContextCell > cell, Isolate *isolate)
void TransitionContextCellToUntagged (Tagged< HeapNumber > number, DirectHandle< ContextCell > cell)
Function Documentation
AddLocalNamesFromContext()
Handle<NameToIndexHashTable> v8::internal::anonymous_namespace{contexts.cc}::AddLocalNamesFromContext (Isolate * isolate, Handle< NameToIndexHashTable > names_table, DirectHandle< Context > script_context, bool ignore_duplicates, int script_context_index)
Definition at line 52 of file contexts.cc.
                              {
  ReadOnlyRoots roots(isolate);
  DirectHandle<ScopeInfo> scope_info(script_context->scope_info(), isolate);
  int local_count = scope_info->ContextLocalCount();
  names_table = names_table->EnsureCapacity(isolate, names_table, local_count);
  for (auto it : ScopeInfo::IterateLocalNames(scope_info)) {
    DirectHandle<Name> name(it->name(), isolate);
    if (ignore_duplicates) {
      int32_t hash = NameToIndexShape::Hash(roots, *name);
      if (names_table->FindEntry(isolate, roots, *name, hash).is_found()) {
        continue;
      }
    }
    names_table = NameToIndexHashTable::Add(isolate, names_table, name,
                                            script_context_index);
  }
  return names_table;
}
References v8::internal::NameToIndexHashTable::Add(), v8::internal::NameToIndexShape::Hash(), v8::internal::ScopeInfo::IterateLocalNames(), and v8::internal::name.
Referenced by v8::internal::ScriptContextTable::Add().
DoubleFitsInInt32()
std::optional<int32_t> v8::internal::anonymous_namespace{contexts.cc}::DoubleFitsInInt32 (double value)
Definition at line 486 of file contexts.cc.
                                                     {
  constexpr double int32_min = std::numeric_limits<int32_t>::min();
  constexpr double int32_max = std::numeric_limits<int32_t>::max();
  // Check -0.0 first.
  if (value == 0.0 && std::signbit(value)) return {};
  double trunc_value = std::trunc(value);
  if (int32_min <= value && value <= int32_max && value == trunc_value) {
    return static_cast<int32_t>(trunc_value);
  }
  return {};
}
References v8::internal::value.
Referenced by v8::internal::Context::Set(), and TransitionContextCellToUntagged().
IsEmptyDependentCode()
bool v8::internal::anonymous_namespace{contexts.cc}::IsEmptyDependentCode (Tagged< DependentCode > value, Isolate * isolate) [inline]
Definition at line 498 of file contexts.cc.
                                                      {
  return value == DependentCode::empty_dependent_code(ReadOnlyRoots(isolate));
}
References v8::internal::DependentCode::empty_dependent_code(), and v8::internal::value.
Referenced by NotifyContextCellStateWillChange().
NotifyContextCellStateWillChange()
void v8::internal::anonymous_namespace{contexts.cc}::NotifyContextCellStateWillChange (DirectHandle< ContextCell > cell, Isolate * isolate) [inline]
Definition at line 503 of file contexts.cc.
                                                                  {
  if (!IsEmptyDependentCode(cell->dependent_code(), isolate)) {
    DependentCode::DeoptimizeDependencyGroups(
        isolate, *cell, DependentCode::kContextCellChangedGroup);
  }
}
References v8::internal::DependentCode::DeoptimizeDependencyGroups(), IsEmptyDependentCode(), and v8::internal::DependentCode::kContextCellChangedGroup.
Referenced by v8::internal::Context::Set().
TransitionContextCellToUntagged()
void v8::internal::anonymous_namespace{contexts.cc}::TransitionContextCellToUntagged (Tagged< HeapNumber > number, DirectHandle< ContextCell > cell) [inline]
Definition at line 511 of file contexts.cc.
                                                                               {
  double double_value = number->value();
  if (auto int32_value = DoubleFitsInInt32(double_value)) {
    cell->set_int32_value(*int32_value);
    cell->set_state(ContextCell::kInt32);
  } else {
    cell->set_float64_value(double_value);
    cell->set_state(ContextCell::kFloat64);
  }
}
References DoubleFitsInInt32(), v8::internal::ContextCell::kFloat64, and v8::internal::ContextCell::kInt32.
Referenced by v8::internal::Context::Set().