v8::internal::anonymous_namespace{js-plural-rules.cc} Namespace Reference
Classes
class PluralRulesAvailableLocales
Functions
bool CreateICUPluralRules (Isolate *isolate, const icu::Locale &icu_locale, JSPluralRules::Type type, std::unique_ptr< icu::PluralRules > *pl)
void CreateDataPropertyForOptions (Isolate *isolate, DirectHandle< JSObject > options, DirectHandle< Object > value, const char *key)
void CreateDataPropertyForOptions (Isolate *isolate, DirectHandle< JSObject > options, int value, const char *key)
Function Documentation
CreateDataPropertyForOptions() [1/2]
void v8::internal::anonymous_namespace{js-plural-rules.cc}::CreateDataPropertyForOptions (Isolate * isolate, DirectHandle< JSObject > options, DirectHandle< Object > value, const char * key)
Definition at line 228 of file js-plural-rules.cc.
                                                                               {
  DirectHandle<String> key_str =
      isolate->factory()->NewStringFromAsciiChecked(key);
  // This is a brand new JSObject that shouldn't already have the same
  // key so this shouldn't fail.
  Maybe<bool> maybe = JSReceiver::CreateDataProperty(isolate, options, key_str,
                                                     value, Just(kDontThrow));
  DCHECK(maybe.FromJust());
  USE(maybe);
}
References v8::internal::JSReceiver::CreateDataProperty(), v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::Maybe< T >::FromJust(), v8::Just(), v8::internal::kDontThrow, v8::internal::key, v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), USE, and v8::internal::value.
CreateDataPropertyForOptions() [2/2]
void v8::internal::anonymous_namespace{js-plural-rules.cc}::CreateDataPropertyForOptions (Isolate * isolate, DirectHandle< JSObject > options, int value, const char * key)
Definition at line 242 of file js-plural-rules.cc.
                                                   {
  DirectHandle<Smi> value_smi(Smi::FromInt(value), isolate);
  CreateDataPropertyForOptions(isolate, options, value_smi, key);
}
References v8::internal::Smi::FromInt(), v8::internal::key, and v8::internal::value.
Referenced by v8::internal::JSPluralRules::ResolvedOptions().
CreateICUPluralRules()
bool v8::internal::anonymous_namespace{js-plural-rules.cc}::CreateICUPluralRules (Isolate * isolate, const icu::Locale & icu_locale, JSPluralRules::Type type, std::unique_ptr< icu::PluralRules > * pl)
Definition at line 31 of file js-plural-rules.cc.
                                                             {
  // Make formatter from options. Numbering system is added
  // to the locale as Unicode extension (if it was specified at all).
  UErrorCode status = U_ZERO_ERROR;
  UPluralType icu_type = UPLURAL_TYPE_CARDINAL;
  if (type == JSPluralRules::Type::ORDINAL) {
    icu_type = UPLURAL_TYPE_ORDINAL;
  } else {
    DCHECK_EQ(JSPluralRules::Type::CARDINAL, type);
  }
  std::unique_ptr<icu::PluralRules> plural_rules(
      icu::PluralRules::forLocale(icu_locale, icu_type, status));
  if (U_FAILURE(status)) {
    return false;
  }
  DCHECK_NOT_NULL(plural_rules.get());
  *pl = std::move(plural_rules);
  return true;
}
References v8::internal::JSPluralRules::CARDINAL, DCHECK_EQ, DCHECK_NOT_NULL, v8::internal::JSPluralRules::ORDINAL, v8::internal::pl, v8::internal::status, and v8::internal::tracing::type.
Referenced by v8::internal::JSPluralRules::New().