v8::internal::anonymous_namespace{runtime-classes.cc} Namespace Reference
Enumerations
enum class SuperMode { kLoad
, kStore
 }
Functions
Tagged< Object > ThrowNotSuperConstructor (Isolate *isolate, DirectHandle< Object > constructor, DirectHandle< JSFunction > function)
template<typename Dictionary >
Handle< Name > KeyToName (Isolate *isolate, Handle< Object > key)
template<> Handle< Name > KeyToName< NumberDictionary > (Isolate *isolate, Handle< Object > key)
template<typename Dictionary >
MaybeDirectHandle< Object > GetMethodAndSetName (Isolate *isolate, RuntimeArguments &args, Tagged< Smi > index, DirectHandle< String > name_prefix, Handle< Object > key)
Tagged< Object > GetMethodWithSharedName (Isolate *isolate, RuntimeArguments &args, Tagged< Object > index)
template<typename Dictionary >
Handle< Dictionary > ShallowCopyDictionaryTemplate (Isolate *isolate, DirectHandle< Dictionary > dictionary_template)
template<typename Dictionary >
bool SubstituteValues (Isolate *isolate, DirectHandle< Dictionary > dictionary, RuntimeArguments &args)
template<typename Dictionary >
void UpdateProtectors (Isolate *isolate, DirectHandle< JSObject > receiver, DirectHandle< Dictionary > properties_dictionary)
void UpdateProtectors (Isolate *isolate, DirectHandle< JSObject > receiver, DirectHandle< DescriptorArray > properties_template)
bool AddDescriptorsByTemplate (Isolate *isolate, DirectHandle< Map > map, DirectHandle< DescriptorArray > descriptors_template, DirectHandle< NumberDictionary > elements_dictionary_template, DirectHandle< JSObject > receiver, RuntimeArguments &args)
template<typename T >
DirectHandle< T > ToHandle (Handle< T > h)
template<typename T >
DirectHandle< T > ToHandle (MaybeHandle< T > h)
template<typename Dictionary >
bool AddDescriptorsByTemplate (Isolate *isolate, DirectHandle< Map > map, DirectHandle< Dictionary > properties_dictionary_template, DirectHandle< NumberDictionary > elements_dictionary_template, DirectHandle< FixedArray > computed_properties, DirectHandle< JSObject > receiver, RuntimeArguments &args)
DirectHandle< JSObject > CreateClassPrototype (Isolate *isolate)
bool InitClassPrototype (Isolate *isolate, DirectHandle< ClassBoilerplate > class_boilerplate, DirectHandle< JSObject > prototype, DirectHandle< JSPrototype > prototype_parent, DirectHandle< JSFunction > constructor, RuntimeArguments &args)
bool InitClassConstructor (Isolate *isolate, DirectHandle< ClassBoilerplate > class_boilerplate, DirectHandle< JSPrototype > constructor_parent, DirectHandle< JSFunction > constructor, RuntimeArguments &args)
MaybeDirectHandle< Object > DefineClass (Isolate *isolate, DirectHandle< ClassBoilerplate > class_boilerplate, DirectHandle< Object > super_class, DirectHandle< JSFunction > constructor, RuntimeArguments &args)
MaybeDirectHandle< JSReceiver > GetSuperHolder (Isolate *isolate, DirectHandle< Object > home_object_proto, SuperMode mode, PropertyKey *key)
MaybeDirectHandle< Object > LoadFromSuper (Isolate *isolate, DirectHandle< JSAny > receiver, DirectHandle< Object > home_object_proto, PropertyKey *key)
MaybeDirectHandle< Object > StoreToSuper (Isolate *isolate, DirectHandle< Object > home_object_proto, DirectHandle< JSAny > receiver, PropertyKey *key, DirectHandle< Object > value, StoreOrigin store_origin)
Enumeration Type Documentation
SuperMode
enum v8::internal::anonymous_namespace{runtime-classes.cc}::SuperMode [strong]
Enumerator
kLoad
kStore
Definition at line 672 of file runtime-classes.cc.
{ kLoad, kStore };
Function Documentation
AddDescriptorsByTemplate() [1/2]
bool v8::internal::anonymous_namespace{runtime-classes.cc}::AddDescriptorsByTemplate (Isolate * isolate, DirectHandle< Map > map, DirectHandle< DescriptorArray > descriptors_template, DirectHandle< NumberDictionary > elements_dictionary_template, DirectHandle< JSObject > receiver, RuntimeArguments & args)
Definition at line 272 of file runtime-classes.cc.
                                                             {
  int nof_descriptors = descriptors_template->number_of_descriptors();
  DirectHandle<DescriptorArray> descriptors =
      DescriptorArray::Allocate(isolate, nof_descriptors, 0);
  DirectHandle<NumberDictionary> elements_dictionary =
      *elements_dictionary_template ==
              ReadOnlyRoots(isolate).empty_slow_element_dictionary()
          ? elements_dictionary_template
          : ShallowCopyDictionaryTemplate(isolate,
                                          elements_dictionary_template);
  // Count the number of properties that must be in the instance and
  // create the property array to hold the constants.
  int count = 0;
  for (InternalIndex i : InternalIndex::Range(nof_descriptors)) {
    PropertyDetails details = descriptors_template->GetDetails(i);
    if (details.location() == PropertyLocation::kDescriptor &&
        details.kind() == PropertyKind::kData) {
      count++;
    }
  }
  DirectHandle<PropertyArray> property_array =
      isolate->factory()->NewPropertyArray(count);
  // Read values from |descriptors_template| and store possibly post-processed
  // values into "instantiated" |descriptors| array.
  int field_index = 0;
  for (InternalIndex i : InternalIndex::Range(nof_descriptors)) {
    Tagged<Object> value = descriptors_template->GetStrongValue(i);
    if (IsAccessorPair(value)) {
      DirectHandle<AccessorPair> pair = AccessorPair::Copy(
          isolate, direct_handle(Cast<AccessorPair>(value), isolate));
      value = *pair;
    }
    DisallowGarbageCollection no_gc;
    Tagged<Name> name = descriptors_template->GetKey(i);
    // TODO(v8:5799): consider adding a ClassBoilerplate flag
    // "has_interesting_properties".
    if (name->IsInteresting(isolate)) {
      map->set_may_have_interesting_properties(true);
    }
    DCHECK(IsUniqueName(name));
    PropertyDetails details = descriptors_template->GetDetails(i);
    if (details.location() == PropertyLocation::kDescriptor) {
      if (details.kind() == PropertyKind::kData) {
        if (IsSmi(value)) {
          value = GetMethodWithSharedName(isolate, args, value);
        }
        details = details.CopyWithRepresentation(
            Object::OptimalRepresentation(value, isolate));
      } else {
        DCHECK_EQ(PropertyKind::kAccessor, details.kind());
        if (IsAccessorPair(value)) {
          Tagged<AccessorPair> pair = Cast<AccessorPair>(value);
          Tagged<Object> tmp = pair->getter();
          if (IsSmi(tmp)) {
            pair->set_getter(GetMethodWithSharedName(isolate, args, tmp));
          }
          tmp = pair->setter();
          if (IsSmi(tmp)) {
            pair->set_setter(GetMethodWithSharedName(isolate, args, tmp));
          }
        }
      }
    } else {
      UNREACHABLE();
    }
    DCHECK(Object::FitsRepresentation(value, details.representation()));
    if (details.location() == PropertyLocation::kDescriptor &&
        details.kind() == PropertyKind::kData) {
      details =
          PropertyDetails(details.kind(), details.attributes(),
                          PropertyLocation::kField, PropertyConstness::kConst,
                          details.representation(), field_index)
              .set_pointer(details.pointer());
      property_array->set(field_index, value);
      field_index++;
      descriptors->Set(i, name, FieldType::Any(), details);
    } else {
      descriptors->Set(i, name, value, details);
    }
  }
  UpdateProtectors(isolate, receiver, descriptors_template);
  map->InitializeDescriptors(isolate, *descriptors);
  if (elements_dictionary->NumberOfElements() > 0) {
    if (!SubstituteValues<NumberDictionary>(isolate, elements_dictionary,
                                            args)) {
      return false;
    }
    map->set_elements_kind(DICTIONARY_ELEMENTS);
  }
  // Atomically commit the changes.
  receiver->set_map(isolate, *map, kReleaseStore);
  if (elements_dictionary->NumberOfElements() > 0) {
    receiver->set_elements(*elements_dictionary);
  }
  if (property_array->length() > 0) {
    receiver->SetProperties(*property_array);
  }
  return true;
}
References v8::internal::DescriptorArray::Allocate(), v8::internal::FieldType::Any(), v8::base::args, v8::internal::PropertyDetails::attributes(), v8::internal::AccessorPair::Copy(), v8::internal::PropertyDetails::CopyWithRepresentation(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::DICTIONARY_ELEMENTS, v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::Object::FitsRepresentation(), GetMethodWithSharedName(), v8::internal::IsSmi(), v8::internal::IsUniqueName(), v8::internal::kAccessor, v8::internal::kConst, v8::internal::kData, v8::internal::kDescriptor, v8::internal::kField, v8::internal::PropertyDetails::kind(), v8::kReleaseStore, v8::internal::PropertyDetails::location(), v8::internal::name, v8::internal::Factory::NewPropertyArray(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Object::OptimalRepresentation(), v8::internal::PropertyDetails::pointer(), v8::internal::PropertyDetails::representation(), v8::internal::PropertyDetails::set_pointer(), ShallowCopyDictionaryTemplate(), v8::internal::UNREACHABLE(), UpdateProtectors(), and v8::internal::value.
AddDescriptorsByTemplate() [2/2]
template<typename Dictionary >
bool v8::internal::anonymous_namespace{runtime-classes.cc}::AddDescriptorsByTemplate (Isolate * isolate, DirectHandle< Map > map, DirectHandle< Dictionary > properties_dictionary_template, DirectHandle< NumberDictionary > elements_dictionary_template, DirectHandle< FixedArray > computed_properties, DirectHandle< JSObject > receiver, RuntimeArguments & args)
Definition at line 398 of file runtime-classes.cc.
                                                             {
  int computed_properties_length = computed_properties->length();
  // Shallow-copy properties template.
  Handle<Dictionary> properties_dictionary =
      ShallowCopyDictionaryTemplate(isolate, properties_dictionary_template);
  Handle<NumberDictionary> elements_dictionary =
      ShallowCopyDictionaryTemplate(isolate, elements_dictionary_template);
  using ValueKind = ClassBoilerplate::ValueKind;
  using ComputedEntryFlags = ClassBoilerplate::ComputedEntryFlags;
  // Merge computed properties with properties and elements dictionary
  // templates.
  int i = 0;
  while (i < computed_properties_length) {
    int flags = Smi::ToInt(computed_properties->get(i++));
    ValueKind value_kind = ComputedEntryFlags::ValueKindBits::decode(flags);
    int key_index = ComputedEntryFlags::KeyIndexBits::decode(flags);
    Tagged<Smi> value = Smi::FromInt(key_index + 1); // Value follows name.
    Handle<Object> key = args.at(key_index);
    DCHECK(IsName(*key));
    uint32_t element;
    Handle<Name> name = Cast<Name>(key);
    if (name->AsArrayIndex(&element)) {
      ClassBoilerplate::AddToElementsTemplate(
          isolate, elements_dictionary, element, key_index, value_kind, value);
    } else {
      name = isolate->factory()->InternalizeName(name);
      ClassBoilerplate::AddToPropertiesTemplate(
          isolate, properties_dictionary, name, key_index, value_kind, value);
      if (name->IsInteresting(isolate)) {
        // TODO(pthier): Add flags to swiss dictionaries.
        if constexpr (!V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
          properties_dictionary->set_may_have_interesting_properties(true);
        }
      }
    }
  }
  // Replace all indices with proper methods.
  if (!SubstituteValues<Dictionary>(isolate, properties_dictionary, args)) {
    return false;
  }
  UpdateProtectors(isolate, receiver,
                   DirectHandle<Dictionary>(properties_dictionary));
  if (elements_dictionary->NumberOfElements() > 0) {
    if (!SubstituteValues<NumberDictionary>(isolate, elements_dictionary,
                                            args)) {
      return false;
    }
    map->set_elements_kind(DICTIONARY_ELEMENTS);
  }
  // Atomically commit the changes.
  receiver->set_map(isolate, *map, kReleaseStore);
  receiver->set_raw_properties_or_hash(*properties_dictionary, kRelaxedStore);
  if (elements_dictionary->NumberOfElements() > 0) {
    receiver->set_elements(*elements_dictionary);
  }
  return true;
}
References v8::internal::ClassBoilerplate::AddToElementsTemplate(), v8::internal::ClassBoilerplate::AddToPropertiesTemplate(), v8::base::args, v8::internal::DCHECK(), v8::internal::DICTIONARY_ELEMENTS, v8::internal::Isolate::factory(), v8::internal::flags, v8::internal::Smi::FromInt(), v8::internal::key, v8::kRelaxedStore, v8::kReleaseStore, v8::internal::name, ShallowCopyDictionaryTemplate(), v8::internal::Smi::ToInt(), UpdateProtectors(), V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL, and v8::internal::value.
Referenced by InitClassConstructor(), and InitClassPrototype().
CreateClassPrototype()
DirectHandle<JSObject> v8::internal::anonymous_namespace{runtime-classes.cc}::CreateClassPrototype (Isolate * isolate)
Definition at line 471 of file runtime-classes.cc.
                                                              {
  // For constant tracking we want to avoid the hassle of handling
  // in-object properties, so create a map with no in-object
  // properties.
  // TODO(ishell) Support caching of zero in-object properties map
  // by ObjectLiteralMapFromCache().
  DirectHandle<Map> map = Map::Create(isolate, 0);
  return isolate->factory()->NewJSObjectFromMap(map);
}
References v8::internal::Map::Create(), v8::internal::Isolate::factory(), and v8::internal::Factory::NewJSObjectFromMap().
Referenced by DefineClass().
DefineClass()
MaybeDirectHandle<Object> v8::internal::anonymous_namespace{runtime-classes.cc}::DefineClass (Isolate * isolate, DirectHandle< ClassBoilerplate > class_boilerplate, DirectHandle< Object > super_class, DirectHandle< JSFunction > constructor, RuntimeArguments & args)
Definition at line 584 of file runtime-classes.cc.
                            {
  DirectHandle<JSPrototype> prototype_parent;
  DirectHandle<JSPrototype> constructor_parent;
  if (IsTheHole(*super_class, isolate)) {
    prototype_parent = isolate->initial_object_prototype();
  } else {
    if (IsNull(*super_class, isolate)) {
      prototype_parent = isolate->factory()->null_value();
    } else if (IsConstructor(*super_class)) {
      DCHECK(!IsJSFunction(*super_class) ||
             !IsResumableFunction(
                 Cast<JSFunction>(super_class)->shared()->kind()));
      DirectHandle<Object> maybe_prototype_parent;
      ASSIGN_RETURN_ON_EXCEPTION(
          isolate, maybe_prototype_parent,
          Runtime::GetObjectProperty(isolate, Cast<JSAny>(super_class),
                                     isolate->factory()->prototype_string()));
      if (!TryCast(maybe_prototype_parent, &prototype_parent)) {
        THROW_NEW_ERROR(
            isolate, NewTypeError(MessageTemplate::kPrototypeParentNotAnObject,
                                  maybe_prototype_parent));
      }
      // Create new handle to avoid |constructor_parent| corruption because of
      // |super_class| handle value overwriting via storing to
      // args[ClassBoilerplate::kPrototypeArgumentIndex] below.
      constructor_parent =
          direct_handle(Cast<JSPrototype>(*super_class), isolate);
    } else {
      THROW_NEW_ERROR(isolate,
                      NewTypeError(MessageTemplate::kExtendsValueNotConstructor,
                                   super_class));
    }
  }
  DirectHandle<JSObject> prototype = CreateClassPrototype(isolate);
  DCHECK_EQ(*constructor, args[ClassBoilerplate::kConstructorArgumentIndex]);
  // Temporarily change ClassBoilerplate::kPrototypeArgumentIndex for the
  // subsequent calls, but use a scope to make sure to change it back before
  // returning, to not corrupt the caller's argument frame (in particular, for
  // the interpreter, to not clobber the register frame).
  RuntimeArguments::ChangeValueScope set_prototype_value_scope(
      isolate, &args, ClassBoilerplate::kPrototypeArgumentIndex, *prototype);
  if (!InitClassConstructor(isolate, class_boilerplate, constructor_parent,
                            constructor, args) ||
      !InitClassPrototype(isolate, class_boilerplate, prototype,
                          prototype_parent, constructor, args)) {
    DCHECK(isolate->has_exception());
    return MaybeDirectHandle<Object>();
  }
  if (v8_flags.log_maps) {
    DirectHandle<Map> empty_map;
    LOG(isolate,
        MapEvent("InitialMap", empty_map,
                 direct_handle(constructor->map(), isolate),
                 "init class constructor",
                 SharedFunctionInfo::DebugName(
                     isolate, direct_handle(constructor->shared(), isolate))));
    LOG(isolate, MapEvent("InitialMap", empty_map,
                          direct_handle(prototype->map(), isolate),
                          "init class prototype"));
  }
  return prototype;
}
References v8::base::args, ASSIGN_RETURN_ON_EXCEPTION, CreateClassPrototype(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::SharedFunctionInfo::DebugName(), v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::Runtime::GetObjectProperty(), v8::internal::Isolate::has_exception(), InitClassConstructor(), InitClassPrototype(), v8::internal::IsNull(), v8::internal::IsResumableFunction(), v8::internal::ClassBoilerplate::kConstructorArgumentIndex, v8::internal::ClassBoilerplate::kPrototypeArgumentIndex, LOG, v8::internal::prototype, THROW_NEW_ERROR, v8::internal::TryCast(), and v8::internal::v8_flags.
Referenced by v8::internal::RUNTIME_FUNCTION().
GetMethodAndSetName()
template<typename Dictionary >
MaybeDirectHandle<Object> v8::internal::anonymous_namespace{runtime-classes.cc}::GetMethodAndSetName (Isolate * isolate, RuntimeArguments & args, Tagged< Smi > index, DirectHandle< String > name_prefix, Handle< Object > key)
Definition at line 138 of file runtime-classes.cc.
                                                                  {
  int int_index = index.value();
  // Class constructor and prototype values do not require post processing.
  if (int_index < ClassBoilerplate::kFirstDynamicArgumentIndex) {
    return args.at<Object>(int_index);
  }
  DirectHandle<JSFunction> method = args.at<JSFunction>(int_index);
  if (!method->shared()->HasSharedName()) {
    // TODO(ishell): method does not have a shared name at this point only if
    // the key is a computed property name. However, the bytecode generator
    // explicitly generates ToName bytecodes to ensure that the computed
    // property name is properly converted to Name. So, we can actually be smart
    // here and avoid converting Smi keys back to Name.
    DirectHandle<Name> name = KeyToName<Dictionary>(isolate, key);
    if (!JSFunction::SetName(isolate, method, name, name_prefix)) {
      return MaybeDirectHandle<Object>();
    }
  }
  return method;
}
References v8::base::args, v8::internal::index, v8::internal::key, v8::internal::ClassBoilerplate::kFirstDynamicArgumentIndex, v8::internal::name, and v8::internal::JSFunction::SetName().
GetMethodWithSharedName()
Tagged<Object> v8::internal::anonymous_namespace{runtime-classes.cc}::GetMethodWithSharedName (Isolate * isolate, RuntimeArguments & args, Tagged< Object > index)
Definition at line 171 of file runtime-classes.cc.
                                                             {
  DisallowGarbageCollection no_gc;
  int int_index = Smi::ToInt(index);
  // Class constructor and prototype values do not require post processing.
  if (int_index < ClassBoilerplate::kFirstDynamicArgumentIndex) {
    return args[int_index];
  }
  DirectHandle<JSFunction> method = args.at<JSFunction>(int_index);
  DCHECK(method->shared()->HasSharedName());
  return *method;
}
References v8::base::args, v8::internal::DCHECK(), v8::internal::index, v8::internal::ClassBoilerplate::kFirstDynamicArgumentIndex, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::Smi::ToInt().
Referenced by AddDescriptorsByTemplate().
GetSuperHolder()
MaybeDirectHandle<JSReceiver> v8::internal::anonymous_namespace{runtime-classes.cc}::GetSuperHolder (Isolate * isolate, DirectHandle< Object > home_object_proto, SuperMode mode, PropertyKey * key)
Definition at line 674 of file runtime-classes.cc.
                      {
  if (!IsJSReceiver(*home_object_proto)) {
    MessageTemplate message =
        mode == SuperMode::kLoad
            ? MessageTemplate::kNonObjectPropertyLoadWithProperty
            : MessageTemplate::kNonObjectPropertyStoreWithProperty;
    DirectHandle<Name> name = key->GetName(isolate);
    THROW_NEW_ERROR(isolate, NewTypeError(message, home_object_proto, name));
  }
  return Cast<JSReceiver>(home_object_proto);
}
References v8::internal::key, mode(), v8::internal::name, and THROW_NEW_ERROR.
Referenced by LoadFromSuper(), and StoreToSuper().
InitClassConstructor()
bool v8::internal::anonymous_namespace{runtime-classes.cc}::InitClassConstructor (Isolate * isolate, DirectHandle< ClassBoilerplate > class_boilerplate, DirectHandle< JSPrototype > constructor_parent, DirectHandle< JSFunction > constructor, RuntimeArguments & args)
Definition at line 527 of file runtime-classes.cc.
                                                  {
  DirectHandle<Map> map(constructor->map(), isolate);
  map = Map::CopyDropDescriptors(isolate, map);
  DCHECK(map->is_prototype_map());
  if (!constructor_parent.is_null()) {
    // Set map's prototype without enabling prototype setup mode for superclass
    // because it does not make sense.
    Map::SetPrototype(isolate, map, constructor_parent, false);
    // Ensure that setup mode will never be enabled for superclass.
    JSObject::MakePrototypesFast(constructor_parent, kStartAtReceiver, isolate);
  }
  DirectHandle<NumberDictionary> elements_dictionary_template(
      Cast<NumberDictionary>(class_boilerplate->static_elements_template()),
      isolate);
  DirectHandle<FixedArray> computed_properties(
      class_boilerplate->static_computed_properties(), isolate);
  Handle<Object> properties_template(
      class_boilerplate->static_properties_template(), isolate);
  if (IsDescriptorArray(*properties_template)) {
    auto descriptors_template = Cast<DescriptorArray>(properties_template);
    return AddDescriptorsByTemplate(isolate, map, descriptors_template,
                                    elements_dictionary_template, constructor,
                                    args);
  } else {
    map->set_is_dictionary_map(true);
    map->InitializeDescriptors(isolate,
                               ReadOnlyRoots(isolate).empty_descriptor_array());
    map->set_is_migration_target(false);
    map->set_may_have_interesting_properties(true);
    map->set_construction_counter(Map::kNoSlackTracking);
    if constexpr (V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
      DirectHandle<SwissNameDictionary> properties_dictionary_template =
          Cast<SwissNameDictionary>(properties_template);
      return AddDescriptorsByTemplate(
          isolate, map, properties_dictionary_template,
          elements_dictionary_template, computed_properties, constructor, args);
    } else {
      DirectHandle<NameDictionary> properties_dictionary_template =
          Cast<NameDictionary>(properties_template);
      return AddDescriptorsByTemplate(
          isolate, map, properties_dictionary_template,
          elements_dictionary_template, computed_properties, constructor, args);
    }
  }
}
References AddDescriptorsByTemplate(), v8::base::args, v8::internal::Cast< NumberDictionary >(), v8::internal::Map::CopyDropDescriptors(), v8::internal::DCHECK(), v8::internal::DirectHandle< T >::is_null(), v8::internal::Map::kNoSlackTracking, v8::internal::kStartAtReceiver, v8::internal::JSObject::MakePrototypesFast(), v8::internal::Map::SetPrototype(), and V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL.
Referenced by DefineClass().
InitClassPrototype()
bool v8::internal::anonymous_namespace{runtime-classes.cc}::InitClassPrototype (Isolate * isolate, DirectHandle< ClassBoilerplate > class_boilerplate, DirectHandle< JSObject > prototype, DirectHandle< JSPrototype > prototype_parent, DirectHandle< JSFunction > constructor, RuntimeArguments & args)
Definition at line 482 of file runtime-classes.cc.
                                                {
  DirectHandle<Map> map(prototype->map(), isolate);
  map = Map::CopyDropDescriptors(isolate, map);
  map->set_is_prototype_map(true);
  Map::SetPrototype(isolate, map, prototype_parent);
  isolate->UpdateProtectorsOnSetPrototype(prototype, prototype_parent);
  constructor->set_prototype_or_initial_map(*prototype, kReleaseStore);
  map->SetConstructor(*constructor);
  DirectHandle<FixedArray> computed_properties(
      class_boilerplate->instance_computed_properties(), isolate);
  DirectHandle<NumberDictionary> elements_dictionary_template(
      Cast<NumberDictionary>(class_boilerplate->instance_elements_template()),
      isolate);
  Handle<Object> properties_template(
      class_boilerplate->instance_properties_template(), isolate);
  if (IsDescriptorArray(*properties_template)) {
    auto descriptors_template = Cast<DescriptorArray>(properties_template);
    // The size of the prototype object is known at this point.
    // So we can create it now and then add the rest instance methods to the
    // map.
    return AddDescriptorsByTemplate(isolate, map, descriptors_template,
                                    elements_dictionary_template, prototype,
                                    args);
  } else {
    map->set_is_dictionary_map(true);
    map->set_is_migration_target(false);
    map->set_may_have_interesting_properties(true);
    map->set_construction_counter(Map::kNoSlackTracking);
    DirectHandle<PropertyDictionary> properties_dictionary_template =
        Cast<PropertyDictionary>(properties_template);
    return AddDescriptorsByTemplate(
        isolate, map, properties_dictionary_template,
        elements_dictionary_template, computed_properties, prototype, args);
  }
}
References AddDescriptorsByTemplate(), v8::base::args, v8::internal::Cast< NumberDictionary >(), v8::internal::Map::CopyDropDescriptors(), v8::internal::Map::kNoSlackTracking, v8::kReleaseStore, v8::internal::prototype, v8::internal::Map::SetPrototype(), and v8::internal::Isolate::UpdateProtectorsOnSetPrototype().
Referenced by DefineClass().
KeyToName()
template<typename Dictionary >
Handle<Name> v8::internal::anonymous_namespace{runtime-classes.cc}::KeyToName (Isolate * isolate, Handle< Object > key)
Definition at line 118 of file runtime-classes.cc.
                                                             {
  static_assert((std::is_same_v<Dictionary, SwissNameDictionary> ||
                 std::is_same_v<Dictionary, NameDictionary>));
  DCHECK(IsName(*key));
  return Cast<Name>(key);
}
References v8::internal::DCHECK(), and v8::internal::key.
KeyToName< NumberDictionary >()
template<>
Handle<Name> v8::internal::anonymous_namespace{runtime-classes.cc}::KeyToName< NumberDictionary > (Isolate * isolate, Handle< Object > key)
Definition at line 118 of file runtime-classes.cc.
                                                                               {
  DCHECK(IsNumber(*key));
  return isolate->factory()->NumberToString(key);
}
LoadFromSuper()
MaybeDirectHandle<Object> v8::internal::anonymous_namespace{runtime-classes.cc}::LoadFromSuper (Isolate * isolate, DirectHandle< JSAny > receiver, DirectHandle< Object > home_object_proto, PropertyKey * key)
Definition at line 688 of file runtime-classes.cc.
                                                          {
  DirectHandle<JSReceiver> holder;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, holder,
      GetSuperHolder(isolate, home_object_proto, SuperMode::kLoad, key));
  LookupIterator it(isolate, receiver, *key, holder);
  DirectHandle<Object> result;
  ASSIGN_RETURN_ON_EXCEPTION(isolate, result, Object::GetProperty(&it));
  return result;
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::Object::GetProperty(), GetSuperHolder(), v8::internal::key, and v8::base::internal::result.
Referenced by v8::internal::RUNTIME_FUNCTION().
ShallowCopyDictionaryTemplate()
template<typename Dictionary >
Handle<Dictionary> v8::internal::anonymous_namespace{runtime-classes.cc}::ShallowCopyDictionaryTemplate (Isolate * isolate, DirectHandle< Dictionary > dictionary_template)
Definition at line 187 of file runtime-classes.cc.
                                                                    {
  Handle<Dictionary> dictionary =
      Dictionary::ShallowCopy(isolate, dictionary_template);
  // Clone all AccessorPairs in the dictionary.
  for (InternalIndex i : dictionary->IterateEntries()) {
    Tagged<Object> value = dictionary->ValueAt(i);
    if (IsAccessorPair(value)) {
      DirectHandle<AccessorPair> pair(Cast<AccessorPair>(value), isolate);
      pair = AccessorPair::Copy(isolate, pair);
      dictionary->ValueAtPut(i, *pair);
    }
  }
  return dictionary;
}
References v8::internal::AccessorPair::Copy(), and v8::internal::value.
Referenced by AddDescriptorsByTemplate().
StoreToSuper()
MaybeDirectHandle<Object> v8::internal::anonymous_namespace{runtime-classes.cc}::StoreToSuper (Isolate * isolate, DirectHandle< Object > home_object_proto, DirectHandle< JSAny > receiver, PropertyKey * key, DirectHandle< Object > value, StoreOrigin store_origin)
Definition at line 754 of file runtime-classes.cc.
                                                                 {
  DirectHandle<JSReceiver> holder;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, holder,
      GetSuperHolder(isolate, home_object_proto, SuperMode::kStore, key));
  LookupIterator it(isolate, receiver, *key, holder);
  MAYBE_RETURN(Object::SetSuperProperty(&it, value, store_origin),
               MaybeDirectHandle<Object>());
  return value;
}
References ASSIGN_RETURN_ON_EXCEPTION, GetSuperHolder(), v8::internal::key, MAYBE_RETURN, v8::internal::Object::SetSuperProperty(), and v8::internal::value.
Referenced by v8::internal::RUNTIME_FUNCTION().
SubstituteValues()
template<typename Dictionary >
bool v8::internal::anonymous_namespace{runtime-classes.cc}::SubstituteValues (Isolate * isolate, DirectHandle< Dictionary > dictionary, RuntimeArguments & args)
Definition at line 204 of file runtime-classes.cc.
                                              {
  // Replace all indices with proper methods.
  ReadOnlyRoots roots(isolate);
  for (InternalIndex i : dictionary->IterateEntries()) {
    Tagged<Object> maybe_key = dictionary->KeyAt(i);
    if (!Dictionary::IsKey(roots, maybe_key)) continue;
    Handle<Object> key(maybe_key, isolate);
    Handle<Object> value(dictionary->ValueAt(i), isolate);
    if (IsAccessorPair(*value)) {
      auto pair = Cast<AccessorPair>(value);
      Tagged<Object> tmp = pair->getter();
      if (IsSmi(tmp)) {
        DirectHandle<Object> result;
        ASSIGN_RETURN_ON_EXCEPTION_VALUE(
            isolate, result,
            GetMethodAndSetName<Dictionary>(isolate, args, Cast<Smi>(tmp),
                                            isolate->factory()->get_string(),
                                            key),
            false);
        pair->set_getter(*result);
      }
      tmp = pair->setter();
      if (IsSmi(tmp)) {
        DirectHandle<Object> result;
        ASSIGN_RETURN_ON_EXCEPTION_VALUE(
            isolate, result,
            GetMethodAndSetName<Dictionary>(isolate, args, Cast<Smi>(tmp),
                                            isolate->factory()->set_string(),
                                            key),
            false);
        pair->set_setter(*result);
      }
    } else if (IsSmi(*value)) {
      DirectHandle<Object> result;
      ASSIGN_RETURN_ON_EXCEPTION_VALUE(
          isolate, result,
          GetMethodAndSetName<Dictionary>(isolate, args, Cast<Smi>(*value),
                                          isolate->factory()->empty_string(),
                                          key),
          false);
      dictionary->ValueAtPut(i, *result);
    }
  }
  return true;
}
References v8::base::args, ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::Isolate::factory(), v8::internal::IsSmi(), v8::internal::key, v8::base::internal::result, and v8::internal::value.
ThrowNotSuperConstructor()
Tagged<Object> v8::internal::anonymous_namespace{runtime-classes.cc}::ThrowNotSuperConstructor (Isolate * isolate, DirectHandle< Object > constructor, DirectHandle< JSFunction > function)
Definition at line 75 of file runtime-classes.cc.
                                                                           {
  DirectHandle<String> super_name;
  if (IsJSFunction(*constructor)) {
    super_name =
        direct_handle(Cast<JSFunction>(constructor)->shared()->Name(), isolate);
  } else if (IsOddball(*constructor)) {
    DCHECK(IsNull(*constructor, isolate));
    super_name = isolate->factory()->null_string();
  } else {
    super_name = Object::NoSideEffectsToString(isolate, constructor);
  }
  // null constructor
  if (super_name->length() == 0) {
    super_name = isolate->factory()->null_string();
  }
  Handle<String> function_name(function->shared()->Name(), isolate);
  // anonymous class
  if (function_name->length() == 0) {
    THROW_NEW_ERROR_RETURN_FAILURE(
        isolate,
        NewTypeError(MessageTemplate::kNotSuperConstructorAnonymousClass,
                     super_name));
  }
  THROW_NEW_ERROR_RETURN_FAILURE(
      isolate, NewTypeError(MessageTemplate::kNotSuperConstructor, super_name,
                            function_name));
}
References v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::IsNull(), v8::internal::Object::NoSideEffectsToString(), and THROW_NEW_ERROR_RETURN_FAILURE.
Referenced by v8::internal::RUNTIME_FUNCTION().
ToHandle() [1/2]
template<typename T >
DirectHandle<T> v8::internal::anonymous_namespace{runtime-classes.cc}::ToHandle (Handle< T > h)
Definition at line 389 of file runtime-classes.cc.
                                      {
  return h;
}
References h().
ToHandle() [2/2]
template<typename T >
DirectHandle<T> v8::internal::anonymous_namespace{runtime-classes.cc}::ToHandle (MaybeHandle< T > h)
Definition at line 393 of file runtime-classes.cc.
                                           {
  return h.ToHandleChecked();
}
References h().
UpdateProtectors() [1/2]
void v8::internal::anonymous_namespace{runtime-classes.cc}::UpdateProtectors (Isolate * isolate, DirectHandle< JSObject > receiver, DirectHandle< DescriptorArray > properties_template)
Definition at line 263 of file runtime-classes.cc.
                                                                         {
  int nof_descriptors = properties_template->number_of_descriptors();
  for (InternalIndex i : InternalIndex::Range(nof_descriptors)) {
    DirectHandle<Name> name(properties_template->GetKey(i), isolate);
    LookupIterator::UpdateProtector(isolate, receiver, name);
  }
}
References v8::internal::name, and v8::internal::LookupIterator::UpdateProtector().
Referenced by AddDescriptorsByTemplate().
UpdateProtectors() [2/2]
template<typename Dictionary >
void v8::internal::anonymous_namespace{runtime-classes.cc}::UpdateProtectors (Isolate * isolate, DirectHandle< JSObject > receiver, DirectHandle< Dictionary > properties_dictionary)
Definition at line 252 of file runtime-classes.cc.
                                                                      {
  ReadOnlyRoots roots(isolate);
  for (InternalIndex i : properties_dictionary->IterateEntries()) {
    Tagged<Object> maybe_key = properties_dictionary->KeyAt(i);
    if (!Dictionary::IsKey(roots, maybe_key)) continue;
    DirectHandle<Name> name(Cast<Name>(maybe_key), isolate);
    LookupIterator::UpdateProtector(isolate, receiver, name);
  }
}
References v8::internal::name, and v8::internal::LookupIterator::UpdateProtector().