v8::internal::anonymous_namespace{regexp-utils.cc} Namespace Reference
Functions
bool HasInitialRegExpMap (Isolate *isolate, Tagged< JSReceiver > recv)
Function Documentation
HasInitialRegExpMap()
bool v8::internal::anonymous_namespace{regexp-utils.cc}::HasInitialRegExpMap (Isolate * isolate, Tagged< JSReceiver > recv) [inline]
Definition at line 59 of file regexp-utils.cc.
                                                                              {
  return recv->map() == isolate->regexp_function()->initial_map();
}
Referenced by v8::internal::RegExpUtils::GetLastIndex(), v8::internal::RegExpUtils::IsUnmodifiedRegExp(), and v8::internal::RegExpUtils::SetLastIndex().