v8::internal::wasm::anonymous_namespace{names-provider.cc} Namespace Reference
Functions
void SanitizeUnicodeName (StringBuilder &out, const uint8_t *utf8_src, size_t length)
void MaybeAddComment (StringBuilder &out, uint32_t index, bool add_comment)
size_t StringMapSize (const std::map< uint32_t, std::string > &map)
Variables
static constexpr char kIdentifierChar []
Function Documentation
MaybeAddComment()
void v8::internal::wasm::anonymous_namespace{names-provider.cc}::MaybeAddComment (StringBuilder & out, uint32_t index, bool add_comment) [inline]
Definition at line 173 of file names-provider.cc.
                                                 {
  if (add_comment) out << " (;" << index << ";)";
}
References v8::internal::index.
Referenced by v8::internal::wasm::NamesProvider::PrintDataSegmentName(), v8::internal::wasm::NamesProvider::PrintElementSegmentName(), v8::internal::wasm::NamesProvider::PrintFieldName(), v8::internal::wasm::NamesProvider::PrintFunctionName(), v8::internal::wasm::NamesProvider::PrintGlobalName(), v8::internal::wasm::NamesProvider::PrintLocalName(), v8::internal::wasm::NamesProvider::PrintMemoryName(), v8::internal::wasm::NamesProvider::PrintTableName(), v8::internal::wasm::NamesProvider::PrintTagName(), v8::internal::wasm::CanonicalTypeNamesProvider::PrintTypeName(), and v8::internal::wasm::NamesProvider::PrintTypeName().
SanitizeUnicodeName()
void v8::internal::wasm::anonymous_namespace{names-provider.cc}::SanitizeUnicodeName (StringBuilder & out, const uint8_t * utf8_src, size_t length)
Definition at line 129 of file names-provider.cc.
                                        {
  if (length == 0) return; // Illegal nullptrs arise below when length == 0.
  base::Vector<const uint8_t> utf8_data(utf8_src, length);
  Utf8Decoder decoder(utf8_data);
  std::vector<uint16_t> utf16(decoder.utf16_length());
  decoder.Decode(utf16.data(), utf8_data);
  for (uint16_t c : utf16) {
    if (c < 32 || c >= 127) {
      out << '_';
    } else {
      out << kIdentifierChar[c - 32];
    }
  }
}
References v8::internal::Utf8DecoderBase< Decoder >::Decode(), kIdentifierChar, v8::internal::length, and v8::internal::Utf8DecoderBase< Decoder >::utf16_length().
Referenced by v8::internal::wasm::NamesProvider::ComputeExportName(), and v8::internal::wasm::NamesProvider::ComputeImportName().
StringMapSize()
size_t v8::internal::wasm::anonymous_namespace{names-provider.cc}::StringMapSize (const std::map< uint32_t, std::string > & map)
Definition at line 412 of file names-provider.cc.
                                                             {
  size_t result = ContentSize(map);
  for (const auto& entry : map) {
    result += entry.second.size();
  }
  return result;
}
References v8::internal::wasm::ContentSize(), and v8::base::internal::result.
Referenced by v8::internal::wasm::NamesProvider::EstimateCurrentMemoryConsumption().
Variable Documentation
kIdentifierChar
constexpr char v8::internal::wasm::anonymous_namespace{names-provider.cc}::kIdentifierChar[] [static], [constexpr]
Initial value:
= {
    '_', '!', '_', '#', '$', '%', '&', '\'',
    '_', '_', '*', '+', '_', '-', '.', '/',
    '0', '1', '2', '3', '4', '5', '6', '7',
    '8', '9', ':', '_', '<', '=', '>', '?',
    '@', 'A', 'B', 'C', 'D', 'E', 'F', 'G',
    'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O',
    'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W',
    'X', 'Y', 'Z', '_', '\\', '_', '^', '_',
    '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g',
    'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o',
    'p', 'q', 'r', 's', 't', 'u', 'v', 'w',
    'x', 'y', 'z', '_', '|', '_', '~', '_',
}
Definition at line 110 of file names-provider.cc.
Referenced by SanitizeUnicodeName().