v8::internal::anonymous_namespace{basic-block-profiler.cc} Namespace Reference
Functions
DirectHandle< String > CopyStringToJSHeap (const std::string &source, Isolate *isolate)
Variables
constexpr int kBlockIdSlotSize = kInt32Size
constexpr int kBlockCountSlotSize = kInt32Size
Function Documentation
CopyStringToJSHeap()
DirectHandle<String> v8::internal::anonymous_namespace{basic-block-profiler.cc}::CopyStringToJSHeap (const std::string & source, Isolate * isolate)
Definition at line 64 of file basic-block-profiler.cc.
                                                          {
  return isolate->factory()->NewStringFromAsciiChecked(source.c_str(),
                                                       AllocationType::kOld);
}
References v8::internal::Isolate::factory(), v8::internal::kOld, and v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked().
Referenced by v8::internal::BasicBlockProfilerData::CopyToJSHeap().
Variable Documentation
kBlockCountSlotSize
constexpr int v8::internal::anonymous_namespace{basic-block-profiler.cc}::kBlockCountSlotSize = kInt32Size [constexpr]
Definition at line 71 of file basic-block-profiler.cc.
Referenced by v8::internal::BasicBlockProfilerData::CopyFromJSHeap(), v8::internal::BasicBlockProfilerData::CopyToJSHeap(), and v8::internal::BasicBlockProfiler::ResetCounts().
kBlockIdSlotSize
constexpr int v8::internal::anonymous_namespace{basic-block-profiler.cc}::kBlockIdSlotSize = kInt32Size [constexpr]
Definition at line 70 of file basic-block-profiler.cc.
Referenced by v8::internal::BasicBlockProfilerData::CopyFromJSHeap(), and v8::internal::BasicBlockProfilerData::CopyToJSHeap().