v8::internal::compiler::anonymous_namespace{typed-optimization.cc} Namespace Reference
Functions
OptionalMapRef GetStableMapFromObjectType (JSHeapBroker *broker, Type object_type)
Node * ResolveSameValueRenames (Node *node)
bool CheckMapsHelper (OptionalMapRef object_map, ZoneRefSet< Map > maps, CompilationDependencies *dependencies)
bool BothAre (Type t1, Type t2, Type t3)
bool NeitherCanBe (Type t1, Type t2, Type t3)
const Operator * NumberOpFromSpeculativeNumberOp (SimplifiedOperatorBuilder *simplified, const Operator *op)
Function Documentation
BothAre()
bool v8::internal::compiler::anonymous_namespace{typed-optimization.cc}::BothAre (Type t1, Type t2, Type t3)
Definition at line 851 of file typed-optimization.cc.
{ return t1.Is(t3) && t2.Is(t3); }
References v8::internal::compiler::Type::Is().
Referenced by v8::internal::compiler::TypedOptimization::ReduceSpeculativeNumberAdd(), v8::internal::compiler::TypedOptimization::ReduceSpeculativeNumberBinop(), and v8::internal::compiler::TypedOptimization::ReduceSpeculativeNumberComparison().
CheckMapsHelper()
bool v8::internal::compiler::anonymous_namespace{typed-optimization.cc}::CheckMapsHelper (OptionalMapRef object_map, ZoneRefSet< Map > maps, CompilationDependencies * dependencies)
Definition at line 239 of file typed-optimization.cc.
                                                            {
  if (object_map.has_value()) {
    for (MapRef map : maps) {
      if (map.equals(*object_map)) {
        if (object_map->CanTransition()) {
          dependencies->DependOnStableMap(*object_map);
        }
        return true;
      }
    }
  }
  return false;
}
References v8::internal::compiler::CompilationDependencies::DependOnStableMap().
Referenced by v8::internal::compiler::TypedOptimization::ReduceCheckMaps(), and v8::internal::compiler::TypedOptimization::ReduceTransitionElementsKindOrCheckMap().
GetStableMapFromObjectType()
OptionalMapRef v8::internal::compiler::anonymous_namespace{typed-optimization.cc}::GetStableMapFromObjectType (JSHeapBroker * broker, Type object_type)
Definition at line 119 of file typed-optimization.cc.
                                                            {
  if (object_type.IsHeapConstant()) {
    HeapObjectRef object = object_type.AsHeapConstant()->Ref();
    MapRef object_map = object.map(broker);
    if (object_map.is_stable()) return object_map;
  }
  return {};
}
References v8::internal::compiler::Type::AsHeapConstant(), broker(), v8::internal::compiler::MapRef::is_stable(), v8::internal::compiler::Type::IsHeapConstant(), v8::internal::compiler::HeapObjectRef::map(), and v8::internal::compiler::HeapConstantType::Ref().
Referenced by v8::internal::compiler::TypedOptimization::ReduceCheckMaps(), v8::internal::compiler::TypedOptimization::ReduceLoadField(), and v8::internal::compiler::TypedOptimization::ReduceTransitionElementsKindOrCheckMap().
NeitherCanBe()
bool v8::internal::compiler::anonymous_namespace{typed-optimization.cc}::NeitherCanBe (Type t1, Type t2, Type t3)
Definition at line 853 of file typed-optimization.cc.
                                             {
  return !t1.Maybe(t3) && !t2.Maybe(t3);
}
References v8::internal::compiler::Type::Maybe().
Referenced by v8::internal::compiler::TypedOptimization::ReduceSpeculativeNumberAdd().
NumberOpFromSpeculativeNumberOp()
const Operator* v8::internal::compiler::anonymous_namespace{typed-optimization.cc}::NumberOpFromSpeculativeNumberOp (SimplifiedOperatorBuilder * simplified, const Operator * op)
Definition at line 857 of file typed-optimization.cc.
                                                               {
  switch (op->opcode()) {
    case IrOpcode::kSpeculativeNumberEqual:
      return simplified->NumberEqual();
    case IrOpcode::kSpeculativeNumberLessThan:
      return simplified->NumberLessThan();
    case IrOpcode::kSpeculativeNumberLessThanOrEqual:
      return simplified->NumberLessThanOrEqual();
    case IrOpcode::kSpeculativeNumberAdd:
      // Handled by ReduceSpeculativeNumberAdd.
      UNREACHABLE();
    case IrOpcode::kSpeculativeNumberSubtract:
      return simplified->NumberSubtract();
    case IrOpcode::kSpeculativeNumberMultiply:
      return simplified->NumberMultiply();
    case IrOpcode::kSpeculativeNumberPow:
      return simplified->NumberPow();
    case IrOpcode::kSpeculativeNumberDivide:
      return simplified->NumberDivide();
    case IrOpcode::kSpeculativeNumberModulus:
      return simplified->NumberModulus();
    default:
      break;
  }
  UNREACHABLE();
}
References v8::internal::compiler::SimplifiedOperatorBuilder::NumberDivide(), v8::internal::compiler::SimplifiedOperatorBuilder::NumberEqual(), v8::internal::compiler::SimplifiedOperatorBuilder::NumberLessThan(), v8::internal::compiler::SimplifiedOperatorBuilder::NumberLessThanOrEqual(), v8::internal::compiler::SimplifiedOperatorBuilder::NumberModulus(), v8::internal::compiler::SimplifiedOperatorBuilder::NumberMultiply(), v8::internal::compiler::SimplifiedOperatorBuilder::NumberPow(), v8::internal::compiler::SimplifiedOperatorBuilder::NumberSubtract(), v8::internal::compiler::Operator::opcode(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::TypedOptimization::ReduceSpeculativeNumberBinop(), and v8::internal::compiler::TypedOptimization::ReduceSpeculativeNumberComparison().
ResolveSameValueRenames()
Node* v8::internal::compiler::anonymous_namespace{typed-optimization.cc}::ResolveSameValueRenames (Node * node)
Definition at line 129 of file typed-optimization.cc.
                                          {
  while (true) {
    switch (node->opcode()) {
      case IrOpcode::kCheckHeapObject:
      case IrOpcode::kCheckNumber:
      case IrOpcode::kCheckNumberFitsInt32:
      case IrOpcode::kCheckSmi:
      case IrOpcode::kFinishRegion:
      case IrOpcode::kTypeGuard:
        if (node->IsDead()) {
          return node;
        } else {
          node = node->InputAt(0);
          continue;
        }
      default:
        return node;
    }
  }
}
References v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::IsDead(), and v8::internal::compiler::Node::opcode().
Referenced by v8::internal::compiler::TypedOptimization::ReduceSameValue().