/mnt/V8SourceCode/src/diagnostics/objects-printer.cc File Reference
#include <iomanip>
#include <memory>
#include <optional>
#include `include/v8-internal.h`
#include `src/api/api-arguments.h`
#include `src/common/assert-scope.h`
#include `src/common/globals.h`
#include `src/diagnostics/disasm.h`
#include `src/diagnostics/disassembler.h`
#include `src/execution/frames-inl.h`
#include `src/execution/isolate-utils-inl.h`
#include `src/heap/heap-inl.h`
#include `src/heap/heap-layout-inl.h`
#include `src/heap/heap-write-barrier-inl.h`
#include `src/heap/marking-inl.h`
#include `src/ic/handler-configuration-inl.h`
#include `src/init/bootstrapper.h`
#include `src/interpreter/bytecodes.h`
#include `src/objects/all-objects-inl.h`
#include `src/objects/allocation-site.h`
#include `src/objects/code-kind.h`
#include `src/objects/contexts.h`
#include `src/objects/cpp-heap-object-wrapper-inl.h`
#include `src/objects/instance-type.h`
#include `src/objects/js-function-inl.h`
#include `src/objects/js-objects.h`
#include `src/objects/shared-function-info-inl.h`
#include `src/objects/struct.h`
#include `src/regexp/regexp.h`
#include `src/sandbox/isolate.h`
#include `src/sandbox/js-dispatch-table.h`
#include `src/snapshot/embedded/embedded-data.h`
#include `src/strings/string-stream.h`
#include `src/utils/ostreams.h`
#include `third_party/fp16/src/include/fp16.h`
Classes
struct _v8_internal_debugonly::StackTraceDebugDetails
Namespaces
 v8
This file provides additional API on top of the default one for making API calls, which come from embedder C++ functions.
 v8::internal
 v8::internal::anonymous_namespace{objects-printer.cc}
 anonymous_namespace{objects-printer.cc}
 _v8_internal_debugonly
Macros
#define MAKE_STRUCT_CASE(TYPE, Name, name)
#define PRINT_HOLE(Type, Value, _)
#define AS_HELPER_DEF(Type, ...)
Functions
void v8::internal::anonymous_namespace{objects-printer.cc}::PrintDouble (std::ostream &os, double val)
i::Tagged< i::Object > anonymous_namespace{objects-printer.cc}::GetObjectFromRaw (void *object)
V8_DEBUGGING_EXPORT i::Tagged< i::Object > _v8_internal_Get_Object (void *object)
V8_DEBUGGING_EXPORT C void _v8_internal_Print_Object (void *object)
V8_DEBUGGING_EXPORT std::string _v8_internal_Print_Object_To_String (void *object)
V8_DEBUGGING_EXPORT C void _v8_internal_Print_LoadHandler (void *object)
V8_DEBUGGING_EXPORT C void _v8_internal_Print_StoreHandler (void *object)
V8_DEBUGGING_EXPORT C void _v8_internal_Print_Code (void *object)
V8_DEBUGGING_EXPORT C void _v8_internal_Print_OnlyCode (void *object, size_t range_limit)
V8_DEBUGGING_EXPORT C void _v8_internal_Print_StackTrace ()
V8_DEBUGGING_EXPORT std::vector< _v8_internal_debugonly::StackTraceDebugDetails > _v8_internal_Expand_StackTrace (i::Isolate *isolate)
V8_DEBUGGING_EXPORT C void _v8_internal_Print_TransitionTree (void *object, bool start_at_root=false)
V8_DEBUGGING_EXPORT C void _v8_internal_Print_Object_MarkBit (void *object)
V8_DEBUGGING_EXPORT C void _v8_internal_Print_FunctionCallbackInfo (void *function_callback_info)
V8_DEBUGGING_EXPORT C void _v8_internal_Print_PropertyCallbackInfo (void *property_callback_info)
Variables
constexpr char v8::internal::anonymous_namespace{objects-printer.cc}::kUnavailableString [] = `unavailable`
Macro Definition Documentation
AS_HELPER_DEF
#define AS_HELPER_DEF(Type, ...)
Value:
  V8_DEBUGGING_EXPORT auto& _As_##Type(i::Address ptr) { \
    i::Tagged<i::Type> tagged = UncheckedCast<i::Type>(\
        GetObjectFromRaw(reinterpret_cast<void*>(ptr))); \
    /* _As_XXX(..) functions provide storage for TaggedOperatorArrowRef<T> */ \
    /* temporary object and return a reference as a measure against gdb */ \
    /* error "Attempt to take address of value not located in memory." */ \
    static auto result = tagged.operator->(); /* There's no default ctor. */ \
    result = tagged.operator->(); \
    return result; \
  } \
  V8_DEBUGGING_EXPORT auto& _As_##Type(i::Tagged<i::HeapObject>& obj) { \
    return _As_##Type(obj.ptr()); \
  }
Definition at line 4369 of file objects-printer.cc.
MAKE_STRUCT_CASE
#define MAKE_STRUCT_CASE(TYPE, Name, name)
Value:
  case TYPE: \
    os << "<" #Name; \
    Cast<Name>(*this)->BriefPrintDetails(os); \
    os << ">"; \
    break;
PRINT_HOLE
#define PRINT_HOLE(Type, Value, _)
Value:
  if (Is##Type(*this)) { \
    os << "<" #Value ">"; \
    break; \
  }
Function Documentation
_v8_internal_Expand_StackTrace()
V8_DEBUGGING_EXPORT std::vector< _v8_internal_debugonly::StackTraceDebugDetails> _v8_internal_Expand_StackTrace (i::Isolate * isolate)
Definition at line 4513 of file objects-printer.cc.
                                                  {
  std::vector<_v8_internal_debugonly::StackTraceDebugDetails> stack;
  i::DisallowGarbageCollection no_gc;
  int frame_index = 0;
  for (i::StackFrameIterator it(isolate); !it.done(); it.Advance()) {
    i::CommonFrame* frame = i::CommonFrame::cast(it.frame());
    _v8_internal_debugonly::StackTraceDebugDetails details;
    details.type = frame->type();
    if (frame->is_javascript()) {
      i::JavaScriptFrame::cast(frame)->GetFunctions(&details.functions);
      if (!frame->is_optimized_js()) {
        int exprcount = frame->ComputeExpressionsCount();
        for (int i = 0; i < exprcount; i++) {
          details.expressions.push_back(frame->GetExpression(i));
        }
      }
    }
    i::HandleScope scope(isolate);
    i::StringStream::ClearMentionedObjectCache(isolate);
    i::HeapStringAllocator allocator;
    i::StringStream accumulator(&allocator);
    frame->Print(&accumulator, i::StackFrame::OVERVIEW, frame_index++);
    std::unique_ptr<char[]> overview = accumulator.ToCString();
    details.summary = overview.get();
    stack.push_back(std::move(details));
  }
  return stack;
}
References v8::internal::CommonFrame::cast(), v8::internal::JavaScriptFrame::cast(), v8::internal::StringStream::ClearMentionedObjectCache(), v8::internal::CommonFrame::ComputeExpressionsCount(), v8::internal::StackFrameIteratorBase::done(), _v8_internal_debugonly::StackTraceDebugDetails::expressions, _v8_internal_debugonly::StackTraceDebugDetails::functions, v8::internal::CommonFrame::GetExpression(), v8::internal::JavaScriptFrame::GetFunctions(), v8::internal::StackFrame::is_javascript(), v8::internal::StackFrame::is_optimized_js(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::StackFrame::OVERVIEW, v8::internal::StackFrame::Print(), v8::internal::stack, _v8_internal_debugonly::StackTraceDebugDetails::summary, v8::internal::StringStream::ToCString(), _v8_internal_debugonly::StackTraceDebugDetails::type, and v8::internal::StackFrame::type().
_v8_internal_Get_Object()
V8_DEBUGGING_EXPORT i::Tagged<i::Object> _v8_internal_Get_Object (void * object)
Definition at line 4352 of file objects-printer.cc.
                  {
  return GetObjectFromRaw(object);
}
References anonymous_namespace{objects-printer.cc}::GetObjectFromRaw().
_v8_internal_Print_Code()
V8_DEBUGGING_EXPORT C void _v8_internal_Print_Code (void * object)
Definition at line 4421 of file objects-printer.cc.
                                                                          {
  i::Address address = reinterpret_cast<i::Address>(object);
  i::Isolate* isolate = i::Isolate::Current();
#if V8_ENABLE_WEBASSEMBLY
  {
    if (auto* wasm_code =
            i::wasm::GetWasmCodeManager()->LookupCode(isolate, address)) {
      i::StdoutStream os;
      wasm_code->Disassemble(nullptr, os, address);
      return;
    }
  }
#endif // V8_ENABLE_WEBASSEMBLY
  std::optional<i::Tagged<i::Code>> lookup_result =
      isolate->heap()->TryFindCodeForInnerPointerForPrinting(address);
  if (!lookup_result.has_value()) {
    i::PrintF(
        "%p is not within the current isolate's code or embedded spaces\n",
        object);
    return;
  }
#if defined(OBJECT_PRINT)
  i::StdoutStream os;
  lookup_result.value()->CodePrint(os, nullptr, address);
#elif defined(ENABLE_DISASSEMBLER)
  i::StdoutStream os;
  lookup_result.value()->Disassemble(nullptr, os, isolate, address);
#else
  i::Print(lookup_result.value());
#endif
}
References v8::internal::Isolate::Current(), v8::internal::wasm::GetWasmCodeManager(), v8::internal::Isolate::heap(), v8::internal::Print(), v8::internal::PrintF(), and v8::internal::Heap::TryFindCodeForInnerPointerForPrinting().
_v8_internal_Print_FunctionCallbackInfo()
V8_DEBUGGING_EXPORT C void _v8_internal_Print_FunctionCallbackInfo (void * function_callback_info)
Definition at line 4574 of file objects-printer.cc.
                                  {
#ifdef OBJECT_PRINT
  i::PrintFunctionCallbackInfo(function_callback_info);
#endif
}
References v8::internal::PrintFunctionCallbackInfo().
_v8_internal_Print_LoadHandler()
V8_DEBUGGING_EXPORT C void _v8_internal_Print_LoadHandler (void * object)
Definition at line 4403 of file objects-printer.cc.
                  {
#ifdef OBJECT_PRINT
  i::StdoutStream os;
  i::LoadHandler::PrintHandler(GetObjectFromRaw(object), os);
  os << std::endl << std::flush;
#endif
}
References anonymous_namespace{objects-printer.cc}::GetObjectFromRaw().
_v8_internal_Print_Object()
V8_DEBUGGING_EXPORT C void _v8_internal_Print_Object (void * object)
Definition at line 4389 of file objects-printer.cc.
                                                                            {
  i::AllowHandleDereference allow_deref;
  i::AllowHandleUsageOnAllThreads allow_deref_all_threads;
  i::Print(GetObjectFromRaw(object));
}
References anonymous_namespace{objects-printer.cc}::GetObjectFromRaw(), and v8::internal::Print().
_v8_internal_Print_Object_MarkBit()
V8_DEBUGGING_EXPORT C void _v8_internal_Print_Object_MarkBit (void * object)
Definition at line 4561 of file objects-printer.cc.
                  {
#ifdef OBJECT_PRINT
  const auto mark_bit =
      v8::internal::MarkBit::From(reinterpret_cast<i::Address>(object));
  i::StdoutStream os;
  os << "Object " << object << " is "
     << (mark_bit.Get() ? "marked" : "unmarked") << std::endl;
  os << " mark-bit cell: " << mark_bit.CellAddress()
     << ", mask: " << mark_bit.Mask() << std::endl;
#endif
}
References v8::internal::MarkBit::From().
_v8_internal_Print_Object_To_String()
V8_DEBUGGING_EXPORT std::string _v8_internal_Print_Object_To_String (void * object)
Definition at line 4396 of file objects-printer.cc.
                  {
  std::stringstream strm;
  i::Print(GetObjectFromRaw(object), strm);
  return strm.str();
}
References anonymous_namespace{objects-printer.cc}::GetObjectFromRaw(), and v8::internal::Print().
_v8_internal_Print_OnlyCode()
V8_DEBUGGING_EXPORT C void _v8_internal_Print_OnlyCode (void * object, size_t range_limit)
Definition at line 4464 of file objects-printer.cc.
                                      {
  i::Address address = reinterpret_cast<i::Address>(object);
  i::Isolate* isolate = i::Isolate::Current();
#if V8_ENABLE_WEBASSEMBLY
  {
    if (i::wasm::GetWasmCodeManager()->LookupCode(isolate, address)) {
      i::PrintF("Not supported on wasm code");
      return;
    }
  }
#endif // V8_ENABLE_WEBASSEMBLY
  std::optional<i::Tagged<i::Code>> lookup_result =
      isolate->heap()->TryFindCodeForInnerPointerForPrinting(address);
  if (!lookup_result.has_value()) {
    i::PrintF(
        "%p is not within the current isolate's code or embedded spaces\n",
        object);
    return;
  }
#if defined(ENABLE_DISASSEMBLER)
  i::StdoutStream os;
  lookup_result.value()->DisassembleOnlyCode(nullptr, os, isolate, address,
                                             range_limit);
#endif
}
References v8::internal::Isolate::Current(), v8::internal::wasm::GetWasmCodeManager(), v8::internal::Isolate::heap(), v8::internal::PrintF(), and v8::internal::Heap::TryFindCodeForInnerPointerForPrinting().
_v8_internal_Print_PropertyCallbackInfo()
V8_DEBUGGING_EXPORT C void _v8_internal_Print_PropertyCallbackInfo (void * property_callback_info)
Definition at line 4581 of file objects-printer.cc.
                                  {
#ifdef OBJECT_PRINT
  i::PrintPropertyCallbackInfo(property_callback_info);
#endif
}
References v8::internal::PrintPropertyCallbackInfo().
_v8_internal_Print_StackTrace()
V8_DEBUGGING_EXPORT C void _v8_internal_Print_StackTrace ()
Definition at line 4494 of file objects-printer.cc.
                                                                    {
  i::Isolate* isolate = i::Isolate::Current();
  isolate->PrintStack(stdout);
}
References v8::internal::Isolate::Current(), and v8::internal::Isolate::PrintStack().
_v8_internal_Print_StoreHandler()
V8_DEBUGGING_EXPORT C void _v8_internal_Print_StoreHandler (void * object)
Definition at line 4412 of file objects-printer.cc.
                  {
#ifdef OBJECT_PRINT
  i::StdoutStream os;
  i::StoreHandler::PrintHandler(GetObjectFromRaw(object), os);
  os << std::flush;
#endif
}
References anonymous_namespace{objects-printer.cc}::GetObjectFromRaw().
_v8_internal_Print_TransitionTree()
V8_DEBUGGING_EXPORT C void _v8_internal_Print_TransitionTree (void * object, bool start_at_root = false)
Definition at line 4545 of file objects-printer.cc.
                                              {
  i::Tagged<i::Object> o(GetObjectFromRaw(object));
  if (!IsMap(o)) {
    printf("Please provide a valid Map\n");
  } else {
#if defined(DEBUG) || defined(OBJECT_PRINT)
    i::Tagged<i::Map> map = i::UncheckedCast<i::Map>(o);
    i::TransitionsAccessor transitions(
        i::Isolate::Current(),
        start_at_root ? map->FindRootMap(GetPtrComprCageBase(map)) : map);
    transitions.PrintTransitionTree();
#endif
  }
}
References v8::internal::Isolate::Current(), anonymous_namespace{objects-printer.cc}::GetObjectFromRaw(), and v8::internal::GetPtrComprCageBase().