/mnt/V8SourceCode/src/base/logging.h File Reference
#include <cstdint>
#include <cstring>
#include <iterator>
#include <sstream>
#include <string>
#include <utility>
#include <vector>
#include `src/base/abort-mode.h`
#include `src/base/base-export.h`
#include `src/base/build_config.h`
#include `src/base/compiler-specific.h`
#include `src/base/immediate-crash.h`
#include `src/base/template-utils.h`
Classes
class v8::base::CheckMessageStream
struct v8::base::is_signed_vs_unsigned< Lhs, Rhs >
struct v8::base::is_unsigned_vs_signed< Lhs, Rhs >
Namespaces
 v8
This file provides additional API on top of the default one for making API calls, which come from embedder C++ functions.
 v8::base
 v8::base::detail
Macros
#define GRACEFUL_FATAL(...) V8_Fatal(__VA_ARGS__)
#define FATAL(...) V8_Fatal(__VA_ARGS__)
#define UNIMPLEMENTED() FATAL(::v8::base::kUnimplementedCodeMessage)
#define UNREACHABLE() FATAL(::v8::base::kUnreachableCodeMessage)
#define CONSTEXPR_UNREACHABLE() UNREACHABLE()
#define CHECK_FAILED_HANDLER(message) FATAL(`Check failed: %s.`, message)
#define CHECK_WITH_MSG(condition, message)
#define CHECK(condition) CHECK_WITH_MSG(condition, #condition)
#define CHECK_OP(name, op, lhs, rhs)
#define DCHECK_WITH_MSG(condition, msg) void(0);
#define DEFINE_PRINT_CHECK_OPERAND_CHAR(type)
#define EXPLICIT_CHECK_OP_INSTANTIATION(type)
#define MAKE_UNDERLYING(Type, value) static_cast<typename comparison_underlying_type<Type>::type>(value)
#define DEFINE_CMP_IMPL(NAME, op)
#define MAKE_UNSIGNED(Type, value)
#define DEFINE_SIGNED_MISMATCH_COMP(CHECK, NAME, IMPL)
#define DEFINE_CHECK_OP_IMPL(NAME)
#define CHECK_EQ(lhs, rhs) CHECK_OP(EQ, ==, lhs, rhs)
#define CHECK_NE(lhs, rhs) CHECK_OP(NE, !=, lhs, rhs)
#define CHECK_LE(lhs, rhs) CHECK_OP(LE, <=, lhs, rhs)
#define CHECK_LT(lhs, rhs) CHECK_OP(LT, <, lhs, rhs)
#define CHECK_GE(lhs, rhs) CHECK_OP(GE, >=, lhs, rhs)
#define CHECK_GT(lhs, rhs) CHECK_OP(GT, >, lhs, rhs)
#define CHECK_NULL(val) CHECK((val) == nullptr)
#define CHECK_NOT_NULL(val) CHECK((val) != nullptr)
#define CHECK_IMPLIES(lhs, rhs) CHECK_WITH_MSG(!(lhs) || (rhs), #lhs ` implies ` #rhs)
#define CHECK_BOUNDS(index, limit)
#define DCHECK(condition) ((void) 0)
#define DCHECK_WITH_LOC(condition, location) ((void)0)
#define DCHECK_WITH_MSG_AND_LOC(condition, message, location) ((void)0)
#define DCHECK_EQ(v1, v2) ((void) 0)
#define DCHECK_NE(v1, v2) ((void) 0)
#define DCHECK_GT(v1, v2) ((void) 0)
#define DCHECK_GE(v1, v2) ((void) 0)
#define DCHECK_LT(v1, v2) ((void) 0)
#define DCHECK_LE(v1, v2) ((void) 0)
#define DCHECK_NULL(val) ((void) 0)
#define DCHECK_NOT_NULL(val) ((void) 0)
#define DCHECK_IMPLIES(v1, v2) ((void) 0)
#define DCHECK_BOUNDS(index, limit) ((void)0)
Enumerations
enum class v8::base::OOMType { v8::base::kJavaScript
, v8::base::kProcess
 }
Functions
V8_BASE_EXPORT V8_NOINLINE void V8_Dcheck (const char *file, int line, const char *message)
PRINTF_FORMAT (1, 2) V8_BASE_EXPORT V8_NOINLINE void V8_Fatal(const char *format
void v8::base::SetPrintStackTrace (void(*print_stack_trace)())
void v8::base::SetDcheckFunction (void(*dcheck_function)(const char *, int, const char *))
void v8::base::SetFatalFunction (void(*fatal_function)(const char *, int, const char *))
void v8::base::FatalOOM (OOMType type, const char *msg)
template<typename... Ts>
std::string v8::base::detail::PrintToString (Ts &&... ts)
template<typename T >
auto v8::base::detail::GetUnderlyingEnumTypeForPrinting (T val)
template<typename T >
std::string v8::base::PrintCheckOperand (T val)
template<typename T >
v8::base::requires (!std::is_function_v< std::remove_pointer_t< T >> &&!std::is_enum_v< T > &&has_output_operator< T, CheckMessageStream >) std
template<typename T >
v8::base::requires (std::is_function_v< typename std::remove_pointer_t< T >>) std
template<typename T >
v8::base::requires (std::is_enum_v< T >) std
template<typename T >
v8::base::requires (!has_output_operator< T, CheckMessageStream > &&requires(T t) { { t.begin() } -> std::forward_iterator;}) std
template<typename Lhs , typename Rhs >
V8_NOINLINE std::string * v8::base::MakeCheckOpString (Lhs lhs, Rhs rhs, char const *msg)
v8::base::EXPLICIT_CHECK_OP_INSTANTIATION (long) EXPLICIT_CHECK_OP_INSTANTIATION(long long) EXPLICIT_CHECK_OP_INSTANTIATION(unsigned long) EXPLICIT_CHECK_OP_INSTANTIATION(unsigned long long) template< typename T > struct comparison_underlying_type
v8::base::DEFINE_SIGNED_MISMATCH_COMP (is_signed_vs_unsigned, EQ, lhs >=0 &&MAKE_UNSIGNED(Lhs, lhs)==MAKE_UNDERLYING(Rhs, rhs)) DEFINE_SIGNED_MISMATCH_COMP(is_signed_vs_unsigned
Variables
constexpr const char * v8::base::kUnimplementedCodeMessage = `unimplemented code`
constexpr const char * v8::base::kUnreachableCodeMessage = `unreachable code`
v8::base::LT
Macro Definition Documentation
CHECK
#define CHECK(condition) CHECK_WITH_MSG(condition, #condition)
Definition at line 124 of file logging.h.
CHECK_BOUNDS
#define CHECK_BOUNDS(index, limit)
Value:
  CHECK_LT(static_cast<std::make_unsigned_t<decltype(index)>>(index), \
           static_cast<std::make_unsigned_t<decltype(limit)>>(limit))
CHECK_EQ
#define CHECK_EQ(lhs, rhs) CHECK_OP(EQ, ==, lhs, rhs)
CHECK_FAILED_HANDLER
#define CHECK_FAILED_HANDLER(message) FATAL(`Check failed: %s.`, message)
Definition at line 109 of file logging.h.
CHECK_GE
#define CHECK_GE(lhs, rhs) CHECK_OP(GE, >=, lhs, rhs)
CHECK_GT
#define CHECK_GT(lhs, rhs) CHECK_OP(GT, >, lhs, rhs)
CHECK_IMPLIES
#define CHECK_IMPLIES(lhs, rhs) CHECK_WITH_MSG(!(lhs) || (rhs), #lhs ` implies ` #rhs)
CHECK_LE
#define CHECK_LE(lhs, rhs) CHECK_OP(LE, <=, lhs, rhs)
CHECK_LT
#define CHECK_LT(lhs, rhs) CHECK_OP(LT, <, lhs, rhs)
CHECK_NE
#define CHECK_NE(lhs, rhs) CHECK_OP(NE, !=, lhs, rhs)
CHECK_NOT_NULL
#define CHECK_NOT_NULL(val) CHECK((val) != nullptr)
CHECK_NULL
#define CHECK_NULL(val) CHECK((val) == nullptr)
CHECK_OP
#define CHECK_OP(name, op, lhs, rhs)
Value:
  do { \
    bool _cmp = ::v8::base::Cmp##name##Impl< \
        typename ::v8::base::pass_value_or_ref<decltype(lhs)>::type, \
        typename ::v8::base::pass_value_or_ref<decltype(rhs)>::type>((lhs), \
                                                                     (rhs)); \
    CHECK_WITH_MSG(_cmp, #lhs " " #op " " #rhs); \
  } while (false)
Definition at line 173 of file logging.h.
CHECK_WITH_MSG
#define CHECK_WITH_MSG(condition, message)
Value:
  do { \
    if (V8_UNLIKELY(!(condition))) { \
      CHECK_FAILED_HANDLER(message); \
    } \
  } while (false)
Definition at line 118 of file logging.h.
CONSTEXPR_UNREACHABLE
#define CONSTEXPR_UNREACHABLE() UNREACHABLE()
Definition at line 73 of file logging.h.
DCHECK
#define DCHECK(condition) ((void) 0)
Definition at line 481 of file logging.h.
DCHECK_BOUNDS
#define DCHECK_BOUNDS(index, limit) ((void)0)
Definition at line 493 of file logging.h.
DCHECK_EQ
#define DCHECK_EQ(v1, v2) ((void) 0)
Definition at line 484 of file logging.h.
DCHECK_GE
#define DCHECK_GE(v1, v2) ((void) 0)
Definition at line 487 of file logging.h.
DCHECK_GT
#define DCHECK_GT(v1, v2) ((void) 0)
Definition at line 486 of file logging.h.
DCHECK_IMPLIES
#define DCHECK_IMPLIES(v1, v2) ((void) 0)
Definition at line 492 of file logging.h.
DCHECK_LE
#define DCHECK_LE(v1, v2) ((void) 0)
Definition at line 489 of file logging.h.
DCHECK_LT
#define DCHECK_LT(v1, v2) ((void) 0)
Definition at line 488 of file logging.h.
DCHECK_NE
#define DCHECK_NE(v1, v2) ((void) 0)
Definition at line 485 of file logging.h.
DCHECK_NOT_NULL
#define DCHECK_NOT_NULL(val) ((void) 0)
Definition at line 491 of file logging.h.
DCHECK_NULL
#define DCHECK_NULL(val) ((void) 0)
Definition at line 490 of file logging.h.
DCHECK_WITH_LOC
#define DCHECK_WITH_LOC(condition, location) ((void)0)
Definition at line 482 of file logging.h.
DCHECK_WITH_MSG
#define DCHECK_WITH_MSG(condition, msg) void(0);
Definition at line 182 of file logging.h.
DCHECK_WITH_MSG_AND_LOC
#define DCHECK_WITH_MSG_AND_LOC(condition, message, location) ((void)0)
Definition at line 483 of file logging.h.
DEFINE_CHECK_OP_IMPL
#define DEFINE_CHECK_OP_IMPL(NAME)
Value:
  template <typename Lhs, typename Rhs> \
  V8_INLINE constexpr std::string* Check##NAME##Impl(Lhs lhs, Rhs rhs, \
                                                     char const* msg) { \
    using LhsPassT = typename pass_value_or_ref<Lhs>::type; \
    using RhsPassT = typename pass_value_or_ref<Rhs>::type; \
    bool cmp = Cmp##NAME##Impl<LhsPassT, RhsPassT>(lhs, rhs); \
    return V8_LIKELY(cmp) \
               ? nullptr \
               : MakeCheckOpString<LhsPassT, RhsPassT>(lhs, rhs, msg); \
  }
DEFINE_CMP_IMPL
#define DEFINE_CMP_IMPL(NAME, op)
Value:
  template <typename Lhs, typename Rhs> \
  V8_INLINE constexpr bool Cmp##NAME##Impl(Lhs lhs, Rhs rhs) { \
    return lhs op rhs; \
  }
Definition at line 378 of file logging.h.
DEFINE_PRINT_CHECK_OPERAND_CHAR
#define DEFINE_PRINT_CHECK_OPERAND_CHAR(type)
Value:
  template <> \
  V8_BASE_EXPORT std::string PrintCheckOperand<type>(type ch); \
  template <> \
  V8_BASE_EXPORT std::string PrintCheckOperand<type*>(type * cstr); \
  template <> \
  V8_BASE_EXPORT std::string PrintCheckOperand<const type*>(const type* cstr);
Definition at line 283 of file logging.h.
DEFINE_SIGNED_MISMATCH_COMP
#define DEFINE_SIGNED_MISMATCH_COMP(CHECK, NAME, IMPL)
Value:
  template <typename Lhs, typename Rhs> \
    requires(CHECK<Lhs, Rhs>::value) \
  V8_INLINE constexpr bool Cmp##NAME##Impl(Lhs lhs, Rhs rhs) { \
    return IMPL; \
  }
Definition at line 396 of file logging.h.
EXPLICIT_CHECK_OP_INSTANTIATION
#define EXPLICIT_CHECK_OP_INSTANTIATION(type)
Value:
  extern template V8_BASE_EXPORT std::string* MakeCheckOpString<type, type>(\
      type, type, char const*); \
  extern template V8_BASE_EXPORT std::string PrintCheckOperand<type>(type);
Definition at line 318 of file logging.h.
FATAL
#define FATAL(...) V8_Fatal(__VA_ARGS__)
Definition at line 47 of file logging.h.
GRACEFUL_FATAL
#define GRACEFUL_FATAL(...) V8_Fatal(__VA_ARGS__)
Definition at line 41 of file logging.h.
MAKE_UNDERLYING
#define MAKE_UNDERLYING(Type, value) static_cast<typename comparison_underlying_type<Type>::type>(value)
Definition at line 349 of file logging.h.
MAKE_UNSIGNED
#define MAKE_UNSIGNED(Type, value)
Value:
  static_cast<typename std::make_unsigned_t< \
      typename comparison_underlying_type<Type>::type>>(value)
Definition at line 393 of file logging.h.
UNIMPLEMENTED
#define UNIMPLEMENTED() FATAL(::v8::base::kUnimplementedCodeMessage)
Definition at line 66 of file logging.h.
UNREACHABLE
#define UNREACHABLE() FATAL(::v8::base::kUnreachableCodeMessage)
Definition at line 67 of file logging.h.
Function Documentation
PRINTF_FORMAT()
PRINTF_FORMAT (1 , 2) const
V8_Dcheck()
V8_BASE_EXPORT V8_NOINLINE void V8_Dcheck (const char * file, int line, const char * message)
Definition at line 218 of file logging.cc.
                                                                {
  if (v8::base::DcheckFailuresAreIgnored()) {
    // In this mode, DCHECK failures don't lead to process termination.
    v8::base::OS::PrintError(
        "# Ignoring debug check failure in %s, line %d: %s\n", file, line,
        message);
    return;
  }
  v8::base::g_dcheck_function(file, line, message);
}
References v8::base::DcheckFailuresAreIgnored(), file(), and v8::base::anonymous_namespace{logging.cc}::g_dcheck_function.
Referenced by cppgc::internal::DCheckImpl().