/mnt/V8SourceCode/src/base/macros.h File Reference
#include <limits>
#include <type_traits>
#include `include/v8config.h`
#include `src/base/compiler-specific.h`
#include `src/base/logging.h`
Classes
struct v8::base::is_trivially_copyable< T >
struct v8::base::is_trivially_destructible< T >
struct v8::base::Use
Namespaces
 v8
This file provides additional API on top of the default one for making API calls, which come from embedder C++ functions.
 v8::base
Macros
#define EXPAND(X) X
#define NOTHING(...)
#define CONCAT_(a, ...) a##__VA_ARGS__
#define CONCAT(a, ...) CONCAT_(a, __VA_ARGS__)
#define UNIQUE_IDENTIFIER(base) CONCAT(base, __COUNTER__)
#define COUNT_MACRO_ARGS(...) EXPAND(COUNT_MACRO_ARGS_IMPL(__VA_ARGS__, 8, 7, 6, 5, 4, 3, 2, 1, 0))
#define COUNT_MACRO_ARGS_IMPL(_8, _7, _6, _5, _4, _3, _2, _1, N, ...) N
#define GET_NTH_ARG(N, ...) CONCAT(GET_NTH_ARG_IMPL_, N)(__VA_ARGS__)
#define GET_NTH_ARG_IMPL_0(_0, ...) _0
#define GET_NTH_ARG_IMPL_1(_0, _1, ...) _1
#define GET_NTH_ARG_IMPL_2(_0, _1, _2, ...) _2
#define GET_NTH_ARG_IMPL_3(_0, _1, _2, _3, ...) _3
#define GET_NTH_ARG_IMPL_4(_0, _1, _2, _3, _4, ...) _4
#define GET_NTH_ARG_IMPL_5(_0, _1, _2, _3, _4, _5, ...) _5
#define GET_NTH_ARG_IMPL_6(_0, _1, _2, _3, _4, _5, _6, ...) _6
#define GET_NTH_ARG_IMPL_7(_0, _1, _2, _3, _4, _5, _6, _7, ...) _7
#define UNPAREN(X) CONCAT(DROP_, UNPAREN_ X)
#define UNPAREN_(...) UNPAREN_ __VA_ARGS__
#define DROP_UNPAREN_
#define OFFSET_OF(type, field) offsetof(type, field)
#define LITERAL_COMMA ,
#define arraysize(array) (sizeof(ArraySizeHelper(array)))
#define DISALLOW_ASSIGN(TypeName) TypeName& operator=(const TypeName&) = delete
#define DISALLOW_IMPLICIT_CONSTRUCTORS(TypeName)
#define MOVE_ONLY_WITH_DEFAULT_CONSTRUCTORS(TypeName)
#define MOVE_ONLY_NO_DEFAULT_CONSTRUCTOR(TypeName)
#define DISALLOW_NEW_AND_DELETE()
#define DISABLE_CFI_PERF V8_CLANG_NO_SANITIZE(`cfi`)
#define DISABLE_CFI_ICALL
#define V8_PRETTY_FUNCTION_VALUE_OR(ELSE) ELSE
#define ASSERT_TRIVIALLY_COPYABLE(T)
#define ASSERT_NOT_TRIVIALLY_COPYABLE(T)
#define ASSERT_TRIVIALLY_DESTRUCTIBLE(T)
#define ASSERT_NOT_TRIVIALLY_DESTRUCTIBLE(T)
#define USE(...)
#define V8_PTR_PREFIX ``
#define V8PRIxPTR V8_PTR_PREFIX `x`
#define V8PRIdPTR V8_PTR_PREFIX `d`
#define V8PRIuPTR V8_PTR_PREFIX `u`
#define V8_PTR_HEX_DIGITS 8
#define V8PRIxPTR_FMT `0x%08` V8PRIxPTR
#define V8PRIxPTRDIFF `tx`
#define V8PRIdPTRDIFF `td`
#define V8PRIuPTRDIFF `tu`
#define V8_EXPORT_PRIVATE
#define V8_EXPORT_ENUM
#define IF_WASM(V, ...)
#define IF_WASM_DRUMBRAKE(V, ...)
#define IF_WASM_DRUMBRAKE_INSTR_HANDLER(V, ...)
#define IF_TSAN(V, ...)
#define IF_INTL(V, ...)
#define IF_SHADOW_STACK(V, ...)
#define IF_TARGET_ARCH_64_BIT(V, ...)
#define IF_V8_WASM_RANDOM_FUZZERS(V, ...)
#define IF_NO_V8_WASM_RANDOM_FUZZERS(V, ...) EXPAND(V(__VA_ARGS__))
#define IF_FUNCTION_ARGUMENTS_CALLER_ARE_OWN_PROPS(V, ...)
#define IF_FUNCTION_ARGUMENTS_CALLER_ARE_ON_PROTOTYPE(V, ...) EXPAND(V(__VA_ARGS__))
Functions
template<typename T , size_t N>
char(& ArraySizeHelper (T(&array)[N]))[N]
template<typename T , size_t N>
char(& ArraySizeHelper (const T(&array)[N]))[N]
template<class Dest , class Source >
Dest v8::base::bit_cast (Source const &source)
template<class A >
A implicit_cast (A x)
uint64_t make_uint64 (uint32_t high, uint32_t low)
template<typename T >
constexpr T RoundDown (T x, intptr_t m)
template<intptr_t m, typename T >
constexpr T RoundDown (T x)
template<typename T >
constexpr T RoundUp (T x, intptr_t m)
template<intptr_t m, typename T >
constexpr T RoundUp (T x)
template<typename T , typename U >
constexpr bool IsAligned (T value, U alignment)
void * AlignedAddress (void *address, size_t alignment)
void * RoundUpAddress (void *address, size_t alignment)
template<typename int_t , typename float_t , typename biggest_int_t = int64_t>
bool is_inbounds (float_t v)
Macro Definition Documentation
arraysize
#define arraysize(array) (sizeof(ArraySizeHelper(array)))
Definition at line 67 of file macros.h.
ASSERT_NOT_TRIVIALLY_COPYABLE
#define ASSERT_NOT_TRIVIALLY_COPYABLE(T)
Value:
  static_assert(!::v8::base::is_trivially_copyable<T>::value, \
                #T " should not be trivially copyable")
Definition at line 270 of file macros.h.
ASSERT_NOT_TRIVIALLY_DESTRUCTIBLE
#define ASSERT_NOT_TRIVIALLY_DESTRUCTIBLE(T)
Value:
  static_assert(!::v8::base::is_trivially_destructible<T>::value, \
                #T " should not be trivially destructible")
Definition at line 282 of file macros.h.
ASSERT_TRIVIALLY_COPYABLE
#define ASSERT_TRIVIALLY_COPYABLE(T)
Value:
  static_assert(::v8::base::is_trivially_copyable<T>::value, \
                #T " should be trivially copyable")
Definition at line 267 of file macros.h.
ASSERT_TRIVIALLY_DESTRUCTIBLE
#define ASSERT_TRIVIALLY_DESTRUCTIBLE(T)
Value:
  static_assert(::v8::base::is_trivially_destructible<T>::value, \
                #T " should be trivially destructible")
Definition at line 279 of file macros.h.
CONCAT
#define CONCAT(a, ...) CONCAT_(a, __VA_ARGS__)
Definition at line 22 of file macros.h.
CONCAT_
#define CONCAT_(a, ...) a##__VA_ARGS__
Definition at line 21 of file macros.h.
COUNT_MACRO_ARGS
#define COUNT_MACRO_ARGS(...) EXPAND(COUNT_MACRO_ARGS_IMPL(__VA_ARGS__, 8, 7, 6, 5, 4, 3, 2, 1, 0))
Definition at line 28 of file macros.h.
COUNT_MACRO_ARGS_IMPL
#define COUNT_MACRO_ARGS_IMPL(_8, _7, _6, _5, _4, _3, _2, _1, N, ...) N
Definition at line 30 of file macros.h.
DISABLE_CFI_ICALL
#define DISABLE_CFI_ICALL
Value:
  V8_CLANG_NO_SANITIZE("cfi-icall") \
  V8_CLANG_NO_SANITIZE("function")
Definition at line 209 of file macros.h.
DISABLE_CFI_PERF
#define DISABLE_CFI_PERF V8_CLANG_NO_SANITIZE(`cfi`)
Definition at line 197 of file macros.h.
DISALLOW_ASSIGN
#define DISALLOW_ASSIGN(TypeName) TypeName& operator=(const TypeName&) = delete
Definition at line 125 of file macros.h.
DISALLOW_IMPLICIT_CONSTRUCTORS
#define DISALLOW_IMPLICIT_CONSTRUCTORS(TypeName)
Value:
  TypeName() = delete; \
  TypeName(const TypeName&) = delete; \
  DISALLOW_ASSIGN(TypeName)
Definition at line 130 of file macros.h.
DISALLOW_NEW_AND_DELETE
#define DISALLOW_NEW_AND_DELETE()
Value:
  void* operator new(size_t) { v8::base::OS::Abort(); } \
  void* operator new[](size_t) { v8::base::OS::Abort(); } \
  void operator delete(void*, size_t) { v8::base::OS::Abort(); } \
  void operator delete[](void*, size_t) { v8::base::OS::Abort(); }
Definition at line 155 of file macros.h.
DROP_UNPAREN_
#define DROP_UNPAREN_
Definition at line 55 of file macros.h.
EXPAND
#define EXPAND(X) X
Definition at line 16 of file macros.h.
GET_NTH_ARG
#define GET_NTH_ARG(N, ...) CONCAT(GET_NTH_ARG_IMPL_, N)(__VA_ARGS__)
Definition at line 33 of file macros.h.
GET_NTH_ARG_IMPL_0
#define GET_NTH_ARG_IMPL_0(_0, ...) _0
Definition at line 34 of file macros.h.
GET_NTH_ARG_IMPL_1
#define GET_NTH_ARG_IMPL_1(_0, _1, ...) _1
Definition at line 35 of file macros.h.
GET_NTH_ARG_IMPL_2
#define GET_NTH_ARG_IMPL_2(_0, _1, _2, ...) _2
Definition at line 36 of file macros.h.
GET_NTH_ARG_IMPL_3
#define GET_NTH_ARG_IMPL_3(_0, _1, _2, _3, ...) _3
Definition at line 37 of file macros.h.
GET_NTH_ARG_IMPL_4
#define GET_NTH_ARG_IMPL_4(_0, _1, _2, _3, _4, ...) _4
Definition at line 38 of file macros.h.
GET_NTH_ARG_IMPL_5
#define GET_NTH_ARG_IMPL_5(_0, _1, _2, _3, _4, _5, ...) _5
Definition at line 39 of file macros.h.
GET_NTH_ARG_IMPL_6
#define GET_NTH_ARG_IMPL_6(_0, _1, _2, _3, _4, _5, _6, ...) _6
Definition at line 40 of file macros.h.
GET_NTH_ARG_IMPL_7
#define GET_NTH_ARG_IMPL_7(_0, _1, _2, _3, _4, _5, _6, _7, ...) _7
Definition at line 41 of file macros.h.
IF_FUNCTION_ARGUMENTS_CALLER_ARE_ON_PROTOTYPE
#define IF_FUNCTION_ARGUMENTS_CALLER_ARE_ON_PROTOTYPE(V, ...) EXPAND(V(__VA_ARGS__))
Definition at line 541 of file macros.h.
IF_FUNCTION_ARGUMENTS_CALLER_ARE_OWN_PROPS
#define IF_FUNCTION_ARGUMENTS_CALLER_ARE_OWN_PROPS(V, ...)
Definition at line 540 of file macros.h.
IF_INTL
#define IF_INTL(V, ...)
Definition at line 502 of file macros.h.
IF_NO_V8_WASM_RANDOM_FUZZERS
#define IF_NO_V8_WASM_RANDOM_FUZZERS(V, ...) EXPAND(V(__VA_ARGS__))
Definition at line 532 of file macros.h.
IF_SHADOW_STACK
#define IF_SHADOW_STACK(V, ...)
Definition at line 511 of file macros.h.
IF_TARGET_ARCH_64_BIT
#define IF_TARGET_ARCH_64_BIT(V, ...)
Definition at line 520 of file macros.h.
IF_TSAN
#define IF_TSAN(V, ...)
Definition at line 493 of file macros.h.
IF_V8_WASM_RANDOM_FUZZERS
#define IF_V8_WASM_RANDOM_FUZZERS(V, ...)
Definition at line 531 of file macros.h.
IF_WASM
#define IF_WASM(V, ...)
Definition at line 472 of file macros.h.
IF_WASM_DRUMBRAKE
#define IF_WASM_DRUMBRAKE(V, ...)
Definition at line 478 of file macros.h.
IF_WASM_DRUMBRAKE_INSTR_HANDLER
#define IF_WASM_DRUMBRAKE_INSTR_HANDLER(V, ...)
Definition at line 484 of file macros.h.
LITERAL_COMMA
#define LITERAL_COMMA ,
Definition at line 61 of file macros.h.
MOVE_ONLY_NO_DEFAULT_CONSTRUCTOR
#define MOVE_ONLY_NO_DEFAULT_CONSTRUCTOR(TypeName)
Value:
  TypeName(TypeName&&) V8_NOEXCEPT = default; \
  TypeName& operator=(TypeName&&) V8_NOEXCEPT = default; \
  TypeName(const TypeName&) = delete; \
  DISALLOW_ASSIGN(TypeName)
Definition at line 143 of file macros.h.
MOVE_ONLY_WITH_DEFAULT_CONSTRUCTORS
#define MOVE_ONLY_WITH_DEFAULT_CONSTRUCTORS(TypeName)
Value:
  TypeName() = default; \
  MOVE_ONLY_NO_DEFAULT_CONSTRUCTOR(TypeName)
Definition at line 137 of file macros.h.
NOTHING
#define NOTHING(...)
Definition at line 19 of file macros.h.
OFFSET_OF
#define OFFSET_OF(type, field) offsetof(type, field)
Definition at line 57 of file macros.h.
UNIQUE_IDENTIFIER
#define UNIQUE_IDENTIFIER(base) CONCAT(base, __COUNTER__)
Definition at line 24 of file macros.h.
UNPAREN
#define UNPAREN(X) CONCAT(DROP_, UNPAREN_ X)
Definition at line 53 of file macros.h.
UNPAREN_
#define UNPAREN_(...) UNPAREN_ __VA_ARGS__
Definition at line 54 of file macros.h.
USE
#define USE(...)
Value:
  do { \
    ::v8::base::Use unused_tmp_array_for_use_macro[]{__VA_ARGS__}; \
    (void)unused_tmp_array_for_use_macro; \
  } while (false)
Definition at line 293 of file macros.h.
V8_EXPORT_ENUM
#define V8_EXPORT_ENUM
Definition at line 461 of file macros.h.
V8_EXPORT_PRIVATE
#define V8_EXPORT_PRIVATE
Definition at line 460 of file macros.h.
V8_PRETTY_FUNCTION_VALUE_OR
#define V8_PRETTY_FUNCTION_VALUE_OR(ELSE) ELSE
Definition at line 221 of file macros.h.
V8_PTR_HEX_DIGITS
#define V8_PTR_HEX_DIGITS 8
Definition at line 339 of file macros.h.
V8_PTR_PREFIX
#define V8_PTR_PREFIX ``
Definition at line 327 of file macros.h.
V8PRIdPTR
#define V8PRIdPTR V8_PTR_PREFIX `d`
Definition at line 332 of file macros.h.
V8PRIdPTRDIFF
#define V8PRIdPTRDIFF `td`
Definition at line 350 of file macros.h.
V8PRIuPTR
#define V8PRIuPTR V8_PTR_PREFIX `u`
Definition at line 333 of file macros.h.
V8PRIuPTRDIFF
#define V8PRIuPTRDIFF `tu`
Definition at line 351 of file macros.h.
V8PRIxPTR
#define V8PRIxPTR V8_PTR_PREFIX `x`
Definition at line 331 of file macros.h.
V8PRIxPTR_FMT
#define V8PRIxPTR_FMT `0x%08` V8PRIxPTR
Definition at line 340 of file macros.h.
V8PRIxPTRDIFF
#define V8PRIxPTRDIFF `tx`
Definition at line 349 of file macros.h.
Function Documentation
AlignedAddress()
void* AlignedAddress (void * address, size_t alignment) [inline]
Definition at line 407 of file macros.h.
                                                             {
  return reinterpret_cast<void*>(
      RoundDown(reinterpret_cast<uintptr_t>(address), alignment));
}
References RoundDown().
Referenced by v8::base::OS::Allocate(), v8::internal::AllocatePages(), v8::internal::MemoryAllocator::AllocateUninitializedChunkAt(), and v8::internal::OffHeapInstructionStream::CreateOffHeapOffHeapInstructionStream().
ArraySizeHelper() [1/2]
template<typename T , size_t N>
char(& ArraySizeHelper (const T(&) array[N]))[N]
ArraySizeHelper() [2/2]
template<typename T , size_t N>
char(& ArraySizeHelper (T(&) array[N]))[N]
implicit_cast()
template<class A >
A implicit_cast (A x) [inline]
Definition at line 306 of file macros.h.
                               {
  return x;
}
Referenced by v8::internal::CodeStubAssembler::ConstructWithTarget(), v8::internal::CodeStubAssembler::TimesDoubleSize(), v8::internal::CodeStubAssembler::TimesSystemPointerSize(), and v8::internal::CodeStubAssembler::TimesTaggedSize().
is_inbounds()
template<typename int_t , typename float_t , typename biggest_int_t = int64_t>
bool is_inbounds (float_t v)
Definition at line 420 of file macros.h.
                            {
  static_assert(sizeof(int_t) < sizeof(biggest_int_t),
                "int_t can't be bounds checked by the compiler");
  constexpr float_t kLowerBound =
      static_cast<float_t>(std::numeric_limits<int_t>::min()) - 1;
  constexpr float_t kUpperBound =
      static_cast<float_t>(std::numeric_limits<int_t>::max()) + 1;
  constexpr bool kLowerBoundIsMin =
      static_cast<biggest_int_t>(kLowerBound) ==
      static_cast<biggest_int_t>(std::numeric_limits<int_t>::min());
  constexpr bool kUpperBoundIsMax =
      static_cast<biggest_int_t>(kUpperBound) ==
      static_cast<biggest_int_t>(std::numeric_limits<int_t>::max());
  // Using USE(var) is only a workaround for a GCC 8.1 bug.
  USE(kLowerBoundIsMin);
  USE(kUpperBoundIsMax);
  return (kLowerBoundIsMin ? (kLowerBound <= v) : (kLowerBound < v)) &&
         (kUpperBoundIsMax ? (v <= kUpperBound) : (v < kUpperBound));
}
References USE.
IsAligned()
template<typename T , typename U >
constexpr bool IsAligned (T value, U alignment) [inline], [constexpr]
Definition at line 403 of file macros.h.
                                                      {
  return (value & (alignment - 1)) == 0;
}
References v8::internal::value.
Referenced by v8::internal::AlignedCachedData::AlignedCachedData(), heap::base::BasicSlotSet< SlotGranularity >::Allocate(), v8::internal::maglev::NodeBase::Allocate(), v8::base::RegionAllocator::AllocateAlignedRegion(), v8::internal::wasm::WasmCodeAllocator::AllocateForCodeInRegion(), v8::base::VirtualAddressSpace::AllocateGuardRegion(), v8::base::VirtualAddressSubspace::AllocateGuardRegion(), v8::internal::ReadOnlySpace::AllocateNextPageAt(), v8::base::VirtualAddressSpace::AllocatePages(), v8::base::VirtualAddressSubspace::AllocatePages(), v8::base::BoundedPageAllocator::AllocatePages(), v8::internal::AllocatePages(), v8::base::BoundedPageAllocator::AllocatePagesAt(), v8::base::RegionAllocator::AllocateRegion(), v8::base::RegionAllocator::AllocateRegionAt(), v8::base::VirtualAddressSpace::AllocateSharedPages(), v8::base::VirtualAddressSubspace::AllocateSharedPages(), v8::base::VirtualAddressSpace::AllocateSubspace(), v8::base::VirtualAddressSubspace::AllocateSubspace(), v8::internal::Zone::AsanNew(), v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::SegmentedTable< Entry, size >::Segment::At(), v8::internal::JSSynchronizationPrimitive::AtomicStatePtr(), v8::internal::anonymous_namespace{sweeper.cc}::AtomicZapBlock(), v8::base::BoundedPageAllocator::BoundedPageAllocator(), heap::base::BasicSlotSet< SlotGranularity >::BucketForSlot(), v8::internal::Factory::CodeBuilder::BuildInternal(), v8::internal::RegExpMacroAssemblerRISCV::CallCheckStackGuardState(), v8::internal::wasm::LiftoffAssembler::CallCWithStackBuffer(), v8::internal::Isolate::CheckIsolateLayout(), v8::internal::wasm::WasmCodeManager::Commit(), v8::internal::Heap::CopyBlock(), v8::internal::CopyImpl(), v8::internal::anonymous_namespace{heap.cc}::CreateFillerObjectAtImpl(), v8::internal::wasm::WasmCodeManager::Decommit(), v8::base::VirtualAddressSpace::DecommitPages(), v8::base::VirtualAddressSubspace::DecommitPages(), v8::base::VirtualAddressSpace::DiscardSystemPages(), v8::base::VirtualAddressSubspace::DiscardSystemPages(), v8::internal::anonymous_namespace{read-only-serializer.cc}::Encode(), v8::internal::Heap::ExpandNewSpaceSize(), v8::internal::FastAsciiCasePrefixLength(), v8::internal::FastAsciiConvert(), v8::internal::compiler::VirtualObject::FieldAt(), v8::internal::FieldIndex::FieldIndex(), v8::internal::compiler::LoadElimination::FieldIndexOf(), v8::internal::CodeStubAssembler::FixedArrayBoundsCheck(), v8::internal::FieldIndex::ForInObjectOffset(), v8::base::VirtualAddressSpace::FreeGuardRegion(), v8::base::VirtualAddressSubspace::FreeGuardRegion(), v8::internal::wasm::WasmCodeManager::FreeNativeModule(), v8::base::VirtualAddressSpace::FreePages(), v8::base::VirtualAddressSubspace::FreePages(), v8::internal::FreePages(), v8::base::VirtualAddressSpace::FreeSharedPages(), v8::base::VirtualAddressSubspace::FreeSharedPages(), v8::internal::MapWord::FromForwardingAddress(), v8::internal::CodeRangeAddressHint::GetAddressHint(), v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::GetImpl(), v8::internal::anonymous_namespace{accounting-allocator.cc}::ManagedZones::GetOrCreateMemoryForSegment(), v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::GetValue(), v8::internal::AllocationStats::IncreaseAllocatedBytes(), v8::internal::MutablePageMetadata::IncrementLiveBytesAtomically(), v8::internal::ConcurrentMarkingVisitor::IncrementLiveBytesCached(), v8::internal::YoungGenerationMarkingVisitor< marking_mode >::IncrementLiveBytesCached(), v8::internal::FieldIndex::index(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::IndexStaticallyInBoundsAndAligned(), v8::internal::SegmentedTable< Entry, size >::Initialize(), v8::internal::VirtualMemoryCage::InitReservation(), v8::internal::CodeRange::InitReservation(), v8::internal::Instruction::InstructionAtOffset(), v8::internal::StackFrameIteratorForProfiler::IsValidExitFrame(), v8::internal::ByteArray::LengthFor(), v8::internal::TrustedByteArray::LengthFor(), v8::internal::Assembler::LinkAndGetBranchInstructionOffsetTo(), v8::internal::CodeStubAssembler::LoadAndUntagToWord32ArrayElement(), v8::internal::CodeStubAssembler::LoadArrayElement(), v8::base::Memory(), v8::internal::Factory::NewContextInternal(), v8::internal::EmbeddedData::NewFromIsolate(), v8::internal::NonAsciiStart(), v8::internal::String::NonOneByteStart(), v8::internal::SegmentedTable< Entry, size >::WriteIterator::operator++(), v8::internal::SegmentedTable< Entry, size >::WriteIterator::operator--(), v8::internal::Serializer::ObjectSerializer::OutputExternalReference(), v8::internal::Serializer::ObjectSerializer::OutputRawData(), v8::internal::Serializer::Pad(), v8::internal::PagedSpaceForNewSpace::PagedSpaceForNewSpace(), v8::internal::SerializedCodeData::Payload(), v8::internal::anonymous_namespace{read-only-serializer.cc}::EncodeRelocationsVisitor::ProcessSlot(), v8::internal::EvacuateVisitorBase::RawMigrateObject(), v8::internal::wasm::NativeModuleDeserializer::ReadCode(), v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlySegmentForSerialization::ReadOnlySegmentForSerialization(), v8::internal::ValueDeserializer::ReadRawTwoBytes(), v8::base::VirtualAddressSpace::RecommitPages(), v8::base::VirtualAddressSubspace::RecommitPages(), v8::base::BoundedPageAllocator::RecommitPages(), v8::internal::MacroAssembler::RecordWriteField(), v8::internal::compiler::MemoryLowering::ReduceAllocateRaw(), v8::base::RegionAllocator::RegionAllocator(), v8::base::Relaxed_Memcmp(), v8::base::Relaxed_Memcpy(), v8::base::Relaxed_Memmove(), v8::internal::VirtualMemory::Release(), v8::internal::ReleasePages(), v8::base::BoundedPageAllocator::ReleasePages(), v8::internal::CodeRange::RemapEmbeddedBuiltins(), v8::base::OS::RemapPages(), v8::base::BoundedPageAllocator::ReserveForSharedMemoryMapping(), v8::internal::VirtualMemory::Resize(), v8::base::BoundedPageAllocator::ResizeAllocationAt(), v8::internal::RUNTIME_FUNCTION(), v8::internal::SemiSpaceNewSpace::SemiSpaceNewSpace(), v8::internal::SerializedCodeData::SerializedCodeData(), v8::internal::Serializer::ObjectSerializer::SerializeExternalStringAsSequentialString(), v8::internal::Instruction::SetBranchImmTarget(), v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::SetImpl(), v8::internal::MutablePageMetadata::SetLiveBytes(), v8::internal::FreeSpace::SetNext(), v8::base::VirtualAddressSpace::SetPagePermissions(), v8::base::VirtualAddressSubspace::SetPagePermissions(), v8::base::BoundedPageAllocator::SetPermissions(), v8::internal::MemoryAllocator::SetPermissionsOnExecutableMemoryChunk(), v8::internal::SignatureBuilder< SigT, T >::SignatureBuilder(), v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::SlotBase(), heap::base::BasicSlotSet< SlotGranularity >::SlotToIndices(), v8::base::RegionAllocator::Split(), v8::internal::CodeStubAssembler::StoreFeedbackVectorSlot(), v8::internal::FeedbackCollectorReducer< Next >::StoreFeedbackVectorSlot(), v8::internal::CodeStubAssembler::StoreFixedArrayOrPropertyArrayElement(), v8::internal::wasm::WasmCodePointerTable::SweepSegments(), v8::base::RegionAllocator::TrimRegion(), v8::internal::SeqString::Truncate(), v8::internal::PagedSpaceAllocatorPolicy::TryAllocationFromFreeList(), v8::base::RegionAllocator::TryGrowRegion(), v8::internal::LinearAllocationArea::Verify(), v8::base::VirtualAddressSpace::VirtualAddressSpace(), v8::base::VirtualAddressSubspace::VirtualAddressSubspace(), cppgc::internal::VirtualMemory::VirtualMemory(), v8::internal::VirtualMemory::VirtualMemory(), v8::internal::compiler::VirtualObject::VirtualObject(), v8::internal::wasm::NativeModuleSerializer::Write(), v8::internal::wasm::NativeModuleSerializer::WriteCode(), v8::internal::heap::ZapBlock(), and v8::internal::heap::ZapCodeBlock().
make_uint64()
uint64_t make_uint64 (uint32_t high, uint32_t low) [inline]
Definition at line 365 of file macros.h.
                                                         {
  return (uint64_t{high} << 32) + low;
}
Referenced by v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::compiler::turboshaft::RedundantStoreAnalysis::ProcessBlock(), v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::SetupSimd256ImmediateInRegister(), and v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::SetupSimdImmediateInRegister().
RoundDown() [1/2]
template<intptr_t m, typename T >
constexpr T RoundDown (T x) [constexpr]
Definition at line 378 of file macros.h.
                           {
  static_assert(std::is_integral_v<T>);
  // m must be a power of two.
  static_assert(m != 0 && ((m & (m - 1)) == 0));
  return x & static_cast<T>(-m);
}
RoundDown() [2/2]
template<typename T >
constexpr T RoundDown (T x, intptr_t m) [constexpr]
Definition at line 371 of file macros.h.
                                       {
  static_assert(std::is_integral_v<T>);
  // m must be a power of two.
  DCHECK(m != 0 && ((m & (m - 1)) == 0));
  return x & static_cast<T>(-m);
}
References DCHECK.
Referenced by heap::base::ActiveSystemPages::Add(), AlignedAddress(), v8::base::anonymous_namespace{platform-posix.cc}::Allocate(), v8::base::EmulatedVirtualAddressSubspace::AllocatePages(), v8::internal::Sweeper::ComputeDiscardMemoryArea(), v8::internal::MainAllocator::ComputeLimit(), v8::internal::Zone::Expand(), cppgc::internal::anonymous_namespace{sweeper.cc}::DiscardingFreeHandler::Free(), v8::internal::wasm::WasmCodeAllocator::FreeCode(), v8::internal::CodeRange::GetPreferredRegion(), v8::base::OS::GetRandomMmapAddr(), v8::internal::JSTypedArray::GetVariableByteLengthOrOutOfBounds(), v8::internal::wasm::StackMemory::Grow(), v8::internal::VirtualMemoryCage::InitReservation(), v8::internal::CodeRange::InitReservation(), v8::internal::MemoryChunkLayout::MaxRegularCodeObjectSize(), v8::internal::BitVector::Iterator::operator++(), v8::base::EmulatedVirtualAddressSubspace::RandomPageAddress(), v8::base::VirtualAddressSubspace::RandomPageAddress(), cppgc::internal::anonymous_namespace{caged-heap.cc}::ReserveCagedHeap(), and v8::internal::ReadOnlyPageMetadata::ShrinkToHighWaterMark().
RoundUp() [1/2]
template<intptr_t m, typename T >
constexpr T RoundUp (T x) [constexpr]
Definition at line 395 of file macros.h.
                         {
  static_assert(std::is_integral_v<T>);
  DCHECK_GE(x, 0);
  DCHECK_GE(std::numeric_limits<T>::max() - x, m - 1); // Overflow check.
  return RoundDown<m, T>(static_cast<T>(x + (m - 1)));
}
References DCHECK_GE.
RoundUp() [2/2]
template<typename T >
constexpr T RoundUp (T x, intptr_t m) [constexpr]
Definition at line 387 of file macros.h.
                                     {
  static_assert(std::is_integral_v<T>);
  DCHECK_GE(x, 0);
  DCHECK_GE(std::numeric_limits<T>::max() - x, m - 1); // Overflow check.
  return RoundDown<T>(static_cast<T>(x + (m - 1)), m);
}
References DCHECK_GE.
Referenced by heap::base::ActiveSystemPages::Add(), v8::internal::wasm::StructTypeBase::Align(), cppgc::internal::anonymous_namespace{heap-page.cc}::AlignAddress(), v8::internal::Zone::Allocate(), v8::base::OS::Allocate(), v8::base::anonymous_namespace{platform-posix.cc}::Allocate(), v8::base::RegionAllocator::AllocateAlignedRegion(), v8::internal::baseline::anonymous_namespace{baseline-compiler.cc}::AllocateBuffer(), cppgc::internal::BasePage::AllocatedSize(), v8::internal::wasm::WasmCodeAllocator::AllocateForCodeInRegion(), v8::base::anonymous_namespace{platform-win32.cc}::AllocateInternal(), v8::internal::anonymous_namespace{accounting-allocator.cc}::ManagedZones::AllocateSegment(), v8::anonymous_namespace{d8.cc}::ShellArrayBufferAllocator::AllocateVM(), v8::internal::Heap::AllocatorLimitOnMaxOldGenerationSize(), v8::internal::Zone::AsanNew(), v8::internal::wasm::InstanceBuilder::Build_Phase1(), cppgc::internal::CagedHeap::CagedHeap(), cppgc::internal::CagedHeap::CommitAgeTable(), v8::internal::MemoryAllocator::ComputeChunkSize(), v8::internal::Sweeper::ComputeDiscardMemoryArea(), v8::internal::anonymous_namespace{heap.cc}::ComputeReducedNewSpaceSize(), cppgc::internal::anonymous_namespace{page-memory.cc}::CreateLargePageMemoryRegion(), v8::internal::OffHeapInstructionStream::CreateOffHeapOffHeapInstructionStream(), v8::internal::Heap::CreateReadOnlyObjects(), v8::internal::Heap::DefaultMaxSemiSpaceSize(), v8::internal::Heap::DefaultMinSemiSpaceSize(), v8::internal::Zone::Delete(), v8::internal::MacroAssembler::DropArguments(), v8::internal::MacroAssembler::DropSlots(), v8::internal::Zone::Expand(), v8::internal::EhFrameWriter::Finish(), v8::internal::VirtualMemory::Free(), cppgc::internal::anonymous_namespace{sweeper.cc}::DiscardingFreeHandler::Free(), v8::internal::wasm::WasmCodeAllocator::FreeCode(), v8::internal::OffHeapInstructionStream::FreeOffHeapOffHeapInstructionStream(), v8::internal::MemoryAllocator::FreeReadOnlyPage(), v8::anonymous_namespace{d8.cc}::ShellArrayBufferAllocator::FreeVM(), v8::internal::CodeRangeAddressHint::GetAddressHint(), v8::internal::CodeRange::GetPreferredRegion(), v8::internal::wasm::StackMemory::Grow(), v8::internal::Heap::HeapSizeFromPhysicalMemory(), heap::base::ActiveSystemPages::Init(), v8::internal::wasm::StructTypeBase::InitializeOffsets(), cppgc::internal::GCInfoTable::InitialTableLimit(), v8::internal::VirtualMemoryCage::InitReservation(), v8::internal::PreparseData::InnerOffset(), v8::internal::WasmMemoryMapDescriptor::MapDescriptor(), cppgc::internal::GCInfoTable::MaxTableSize(), v8::internal::compiler::Instruction::New(), v8::internal::wasm::LiftoffAssembler::NextSpillOffset(), v8::internal::MemoryChunkLayout::ObjectStartOffsetInCodePage(), v8::internal::MemoryChunkLayout::ObjectStartOffsetInDataPage(), cppgc::internal::NormalPage::PayloadSize(), v8::base::BoundedPageAllocator::ReleasePages(), v8::internal::CodeRange::RemapEmbeddedBuiltins(), v8::base::BoundedPageAllocator::ReserveForSharedMemoryMapping(), v8::internal::Zone::Reset(), v8::base::BoundedPageAllocator::ResizeAllocationAt(), v8::internal::MemoryAllocator::ResizeLargePage(), RoundUpAddress(), v8::internal::RoundUpToPageSize(), v8::internal::LargeObjectSpace::ShrinkPageToObjectSize(), v8::internal::SmallOrderedHashTable< Derived >::SizeFor(), v8::internal::WasmArray::SizeFor(), v8::internal::wasm::StackMemory::StackMemory(), v8::internal::anonymous_namespace{builtins-riscv.cc}::SwitchToAllocatedStack(), v8::internal::wasm::WasmCodeManager::TryAllocate(), v8::internal::JsonStringifier::TrySerializeSimplePropertyKey(), v8::internal::LargeObjectSpace::UpdateAccountingAfterResizingObject(), cppgc::internal::VirtualMemory::VirtualMemory(), v8::internal::VirtualMemory::VirtualMemory(), v8::internal::Serializer::ObjectSerializer::VisitJSDispatchTableEntry(), v8::internal::EhFrameWriter::WriteEhFrameHdr(), v8::internal::EhFrameWriter::WritePaddingToAlignedSize(), v8::internal::Heap::YoungGenerationSizeFromOldGenerationSize(), v8::base::PosixMemoryMappedFile::~PosixMemoryMappedFile(), and v8::internal::ReadOnlyArtifacts::~ReadOnlyArtifacts().
RoundUpAddress()
void* RoundUpAddress (void * address, size_t alignment) [inline]
Definition at line 412 of file macros.h.
                                                             {
  return reinterpret_cast<void*>(
      RoundUp(reinterpret_cast<uintptr_t>(address), alignment));
}
References RoundUp().