v8::internal::torque::PushBuiltinPointerInstruction Struct Reference
#include <instructions.h>
Public Member Functions
PushBuiltinPointerInstruction (std::string external_name, const Type *type)
DefinitionLocation GetValueDefinition () const
Public Attributes
std::string external_name
const Type * type
Detailed Description
Definition at line 346 of file instructions.h.
Constructor & Destructor Documentation
PushBuiltinPointerInstruction()
v8::internal::torque::PushBuiltinPointerInstruction::PushBuiltinPointerInstruction (std::string external_name, const Type * type) [inline]
Definition at line 348 of file instructions.h.
      : external_name(std::move(external_name)), type(type) {
    DCHECK(type->IsBuiltinPointerType());
  }
References v8::internal::DCHECK(), v8::internal::torque::TypeBase::IsBuiltinPointerType(), and type.
Member Function Documentation
GetValueDefinition()
DefinitionLocation v8::internal::torque::PushBuiltinPointerInstruction::GetValueDefinition () const
Definition at line 107 of file instructions.cc.
                                                                           {
  return DefinitionLocation::Instruction(this, 0);
}
References v8::internal::torque::DefinitionLocation::Instruction().
Member Data Documentation
external_name
std::string v8::internal::torque::PushBuiltinPointerInstruction::external_name
Definition at line 355 of file instructions.h.
Referenced by v8::internal::torque::operator<<().
type
const Type* v8::internal::torque::PushBuiltinPointerInstruction::type
Definition at line 356 of file instructions.h.
Referenced by v8::internal::torque::operator<<(), and PushBuiltinPointerInstruction().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/torque/instructions.h
/mnt/V8SourceCode/src/torque/instructions.cc