v8_inspector::V8StackTraceId Struct Reference
#include <v8-inspector.h>
Public Member Functions
V8StackTraceId ()
V8StackTraceId (const V8StackTraceId &)=default
V8StackTraceId (uintptr_t id, const std::pair< int64_t, int64_t > debugger_id)
V8StackTraceId (uintptr_t id, const std::pair< int64_t, int64_t > debugger_id, bool should_pause)
V8StackTraceId (StringView)
V8StackTraceId & operator= (const V8StackTraceId &)=default
V8StackTraceId & operator= (V8StackTraceId &&) noexcept=default
~V8StackTraceId ()=default
bool IsInvalid () const
std::unique_ptr< StringBuffer > ToString ()
Public Attributes
uintptr_t id
std::pair< int64_t, int64_t > debugger_id
bool should_pause = false
Detailed Description
Definition at line 337 of file v8-inspector.h.
Constructor & Destructor Documentation
V8StackTraceId() [1/5]
v8_inspector::V8StackTraceId::V8StackTraceId ()
Definition at line 105 of file v8-stack-trace-impl.cc.
    : id(0), debugger_id(internal::V8DebuggerId().pair()) {}
V8StackTraceId() [2/5]
v8_inspector::V8StackTraceId::V8StackTraceId (const V8StackTraceId &) [default]
V8StackTraceId() [3/5]
v8_inspector::V8StackTraceId::V8StackTraceId (uintptr_t id, const std::pair< int64_t, int64_t > debugger_id)
Definition at line 108 of file v8-stack-trace-impl.cc.
    : id(id), debugger_id(debugger_id) {}
V8StackTraceId() [4/5]
v8_inspector::V8StackTraceId::V8StackTraceId (uintptr_t id, const std::pair< int64_t, int64_t > debugger_id, bool should_pause)
Definition at line 112 of file v8-stack-trace-impl.cc.
    : id(id), debugger_id(debugger_id), should_pause(should_pause) {}
V8StackTraceId() [5/5]
v8_inspector::V8StackTraceId::V8StackTraceId (StringView json) [explicit]
Definition at line 117 of file v8-stack-trace-impl.cc.
    : id(0), debugger_id(internal::V8DebuggerId().pair()) {
  if (json.length() == 0) return;
  std::vector<uint8_t> cbor;
  if (json.is8Bit()) {
    ConvertJSONToCBOR(
        v8_crdtp::span<uint8_t>(json.characters8(), json.length()), &cbor);
  } else {
    ConvertJSONToCBOR(
        v8_crdtp::span<uint16_t>(json.characters16(), json.length()), &cbor);
  }
  auto dict = protocol::DictionaryValue::cast(
      protocol::Value::parseBinary(cbor.data(), cbor.size()));
  if (!dict) return;
  String16 s;
  if (!dict->getString(kId, &s)) return;
  bool isOk = false;
  int64_t parsedId = s.toInteger64(&isOk);
  if (!isOk || !parsedId) return;
  if (!dict->getString(kDebuggerId, &s)) return;
  internal::V8DebuggerId debuggerId(s);
  if (!debuggerId.isValid()) return;
  if (!dict->getBoolean(kShouldPause, &should_pause)) return;
  id = parsedId;
  debugger_id = debuggerId.pair();
}
References v8_inspector::StringView::characters16(), v8_inspector::StringView::characters8(), debugger_id, v8_inspector::StringView::is8Bit(), v8_inspector::internal::V8DebuggerId::isValid(), v8_inspector::anonymous_namespace{v8-stack-trace-impl.cc}::kDebuggerId, v8_inspector::anonymous_namespace{v8-stack-trace-impl.cc}::kId, v8_inspector::anonymous_namespace{v8-stack-trace-impl.cc}::kShouldPause, v8_inspector::StringView::length(), v8_inspector::internal::V8DebuggerId::pair(), should_pause, and v8_inspector::String16::toInteger64().
 V8StackTraceId()
v8_inspector::V8StackTraceId::~V8StackTraceId () [default]
Member Function Documentation
IsInvalid()
bool v8_inspector::V8StackTraceId::IsInvalid () const
Definition at line 144 of file v8-stack-trace-impl.cc.
{ return !id; }
References id.
Referenced by v8_inspector::V8Debugger::asyncParentFor(), v8_inspector::anonymous_namespace{v8-stack-trace-impl.cc}::buildInspectorObjectCommon(), v8_inspector::AsyncStackTrace::capture(), v8_inspector::V8StackTraceImpl::create(), v8_inspector::V8DebuggerAgentImpl::currentExternalStackTrace(), v8_inspector::V8Debugger::externalAsyncTaskStarted(), v8_inspector::V8DebuggerAgentImpl::getStackTrace(), and ToString().
operator=() [1/2]
V8StackTraceId& v8_inspector::V8StackTraceId::operator= (const V8StackTraceId &) [default]
operator=() [2/2]
V8StackTraceId& v8_inspector::V8StackTraceId::operator= (V8StackTraceId &&) [default], [noexcept]
ToString()
std::unique_ptr< StringBuffer > v8_inspector::V8StackTraceId::ToString ()
Definition at line 146 of file v8-stack-trace-impl.cc.
                                                     {
  if (IsInvalid()) return nullptr;
  auto dict = protocol::DictionaryValue::create();
  dict->setString(kId, String16::fromInteger64(id));
  dict->setString(kDebuggerId, internal::V8DebuggerId(debugger_id).toString());
  dict->setBoolean(kShouldPause, should_pause);
  std::vector<uint8_t> json;
  v8_crdtp::json::ConvertCBORToJSON(v8_crdtp::SpanFrom(dict->Serialize()),
                                    &json);
  return StringBufferFrom(std::move(json));
}
References debugger_id, v8_inspector::String16::fromInteger64(), IsInvalid(), v8_inspector::anonymous_namespace{v8-stack-trace-impl.cc}::kDebuggerId, v8_inspector::anonymous_namespace{v8-stack-trace-impl.cc}::kId, v8_inspector::anonymous_namespace{v8-stack-trace-impl.cc}::kShouldPause, should_pause, and v8_inspector::StringBufferFrom().
Member Data Documentation
debugger_id
std::pair<int64_t, int64_t> v8_inspector::V8StackTraceId::debugger_id
Definition at line 339 of file v8-inspector.h.
Referenced by v8_inspector::anonymous_namespace{v8-stack-trace-impl.cc}::buildInspectorObjectCommon(), v8_inspector::V8DebuggerAgentImpl::currentExternalStackTrace(), ToString(), and V8StackTraceId().
id
uintptr_t v8_inspector::V8StackTraceId::id
Definition at line 338 of file v8-inspector.h.
Referenced by v8_inspector::anonymous_namespace{v8-stack-trace-impl.cc}::buildInspectorObjectCommon(), v8_inspector::V8DebuggerAgentImpl::currentExternalStackTrace(), v8_inspector::V8Debugger::externalAsyncTaskFinished(), v8_inspector::V8Debugger::externalAsyncTaskStarted(), and IsInvalid().
should_pause
bool v8_inspector::V8StackTraceId::should_pause = false
Definition at line 340 of file v8-inspector.h.
Referenced by v8_inspector::V8Debugger::externalAsyncTaskFinished(), v8_inspector::V8Debugger::externalAsyncTaskStarted(), ToString(), and V8StackTraceId().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/include/v8-inspector.h
/mnt/V8SourceCode/src/inspector/v8-stack-trace-impl.cc