v8::internal::wasm::WasmBytecodeGenerator::BlockData Struct Reference
Public Member Functions
BlockData (WasmOpcode opcode, uint32_t begin_code_offset, int32_t parent_block_index, uint32_t stack_size, WasmInstruction::Optional::Block signature, uint32_t first_block_index, uint32_t rets_slots_count, uint32_t params_slots_count, int32_t parent_try_block_index)
bool IsRootBlock () const
bool IsBlock () const
bool IsLoop () const
bool IsIf () const
bool IsElse () const
bool HasElseBranch () const
bool IsTry () const
bool IsCatch () const
bool IsCatchAll () const
void SaveParams (uint32_t *from, size_t params_count)
uint32_t GetParam (size_t index) const
Public Attributes
WasmOpcode opcode_
uint32_t stack_size_
uint32_t begin_code_offset_
uint32_t end_code_offset_
int32_t parent_block_index_
int32_t if_else_block_index_
base::SmallVector< uint32_t, 4 > branch_code_offsets_
WasmInstruction::Optional::Block signature_
uint32_t first_block_index_
uint32_t rets_slots_count_
uint32_t params_slots_count_
int32_t parent_try_block_index_
bool is_unreachable_
base::SmallVector< uint32_t, 4 > if_block_params_
Detailed Description
Definition at line 1467 of file wasm-interpreter.h.
Constructor & Destructor Documentation
BlockData()
v8::internal::wasm::WasmBytecodeGenerator::BlockData::BlockData (WasmOpcode opcode, uint32_t begin_code_offset, int32_t parent_block_index, uint32_t stack_size, WasmInstruction::Optional::Block signature, uint32_t first_block_index, uint32_t rets_slots_count, uint32_t params_slots_count, int32_t parent_try_block_index) [inline]
Definition at line 1468 of file wasm-interpreter.h.
        : opcode_(opcode),
          stack_size_(stack_size),
          begin_code_offset_(begin_code_offset),
          end_code_offset_(0),
          parent_block_index_(parent_block_index),
          if_else_block_index_(-1),
          signature_(signature),
          first_block_index_(first_block_index),
          rets_slots_count_(rets_slots_count),
          params_slots_count_(params_slots_count),
          parent_try_block_index_(parent_try_block_index),
          is_unreachable_(false) {}
Member Function Documentation
GetParam()
uint32_t v8::internal::wasm::WasmBytecodeGenerator::BlockData::GetParam (size_t index) const [inline]
Definition at line 1503 of file wasm-interpreter.h.
                                          {
      DCHECK(IsIf());
      DCHECK_LE(index, if_block_params_.size());
      return if_block_params_[index];
    }
References v8::internal::DCHECK(), DCHECK_LE, if_block_params_, v8::internal::index, IsIf(), and v8::base::SmallVector< T, kSize, Allocator >::size().
Referenced by v8::internal::wasm::WasmBytecodeGenerator::RestoreIfElseParams().
HasElseBranch()
bool v8::internal::wasm::WasmBytecodeGenerator::BlockData::HasElseBranch () const [inline]
Definition at line 1491 of file wasm-interpreter.h.
{ return if_else_block_index_ > 0; }
References if_else_block_index_.
IsBlock()
bool v8::internal::wasm::WasmBytecodeGenerator::BlockData::IsBlock () const [inline]
Definition at line 1487 of file wasm-interpreter.h.
{ return opcode_ == kExprBlock; }
References opcode_.
IsCatch()
bool v8::internal::wasm::WasmBytecodeGenerator::BlockData::IsCatch () const [inline]
Definition at line 1493 of file wasm-interpreter.h.
{ return opcode_ == kExprCatch; }
References opcode_.
Referenced by v8::internal::wasm::WasmBytecodeGenerator::EndBlock(), and v8::internal::wasm::WasmBytecodeGenerator::PatchBranchOffsets().
IsCatchAll()
bool v8::internal::wasm::WasmBytecodeGenerator::BlockData::IsCatchAll () const [inline]
Definition at line 1494 of file wasm-interpreter.h.
{ return opcode_ == kExprCatchAll; }
References opcode_.
Referenced by v8::internal::wasm::WasmBytecodeGenerator::EndBlock(), and v8::internal::wasm::WasmBytecodeGenerator::PatchBranchOffsets().
IsElse()
bool v8::internal::wasm::WasmBytecodeGenerator::BlockData::IsElse () const [inline]
Definition at line 1490 of file wasm-interpreter.h.
{ return opcode_ == kExprElse; }
References opcode_.
Referenced by v8::internal::wasm::WasmBytecodeGenerator::EndBlock().
IsIf()
bool v8::internal::wasm::WasmBytecodeGenerator::BlockData::IsIf () const [inline]
Definition at line 1489 of file wasm-interpreter.h.
{ return opcode_ == kExprIf; }
References opcode_.
Referenced by GetParam(), v8::internal::wasm::WasmBytecodeGenerator::PatchBranchOffsets(), and SaveParams().
IsLoop()
bool v8::internal::wasm::WasmBytecodeGenerator::BlockData::IsLoop () const [inline]
Definition at line 1488 of file wasm-interpreter.h.
{ return opcode_ == kExprLoop; }
References opcode_.
Referenced by v8::internal::wasm::WasmBytecodeGenerator::PatchBranchOffsets().
IsRootBlock()
bool v8::internal::wasm::WasmBytecodeGenerator::BlockData::IsRootBlock () const [inline]
Definition at line 1486 of file wasm-interpreter.h.
{ return parent_block_index_ < 0; }
References parent_block_index_.
IsTry()
bool v8::internal::wasm::WasmBytecodeGenerator::BlockData::IsTry () const [inline]
Definition at line 1492 of file wasm-interpreter.h.
{ return opcode_ == kExprTry; }
References opcode_.
Referenced by v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction(), and v8::internal::wasm::WasmBytecodeGenerator::EndBlock().
SaveParams()
void v8::internal::wasm::WasmBytecodeGenerator::BlockData::SaveParams (uint32_t * from, size_t params_count) [inline]
Definition at line 1496 of file wasm-interpreter.h.
                                                         {
      DCHECK(IsIf());
      if_block_params_ = base::SmallVector<uint32_t, 4>(params_count);
      for (size_t i = 0; i < params_count; i++) {
        if_block_params_[i] = from[i];
      }
    }
References v8::internal::DCHECK(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, if_block_params_, and IsIf().
Member Data Documentation
begin_code_offset_
uint32_t v8::internal::wasm::WasmBytecodeGenerator::BlockData::begin_code_offset_
Definition at line 1511 of file wasm-interpreter.h.
Referenced by v8::internal::wasm::WasmBytecodeGenerator::PatchBranchOffsets().
branch_code_offsets_
base::SmallVector<uint32_t, 4> v8::internal::wasm::WasmBytecodeGenerator::BlockData::branch_code_offsets_
Definition at line 1515 of file wasm-interpreter.h.
Referenced by v8::internal::wasm::WasmBytecodeGenerator::PatchBranchOffsets().
end_code_offset_
uint32_t v8::internal::wasm::WasmBytecodeGenerator::BlockData::end_code_offset_
Definition at line 1512 of file wasm-interpreter.h.
Referenced by v8::internal::wasm::WasmBytecodeGenerator::EndBlock(), and v8::internal::wasm::WasmBytecodeGenerator::PatchBranchOffsets().
first_block_index_
uint32_t v8::internal::wasm::WasmBytecodeGenerator::BlockData::first_block_index_
Definition at line 1517 of file wasm-interpreter.h.
Referenced by v8::internal::wasm::WasmBytecodeGenerator::StoreBlockParamsAndResultsIntoSlots(), and v8::internal::wasm::WasmBytecodeGenerator::StoreBlockParamsIntoSlots().
if_block_params_
base::SmallVector<uint32_t, 4> v8::internal::wasm::WasmBytecodeGenerator::BlockData::if_block_params_
Definition at line 1522 of file wasm-interpreter.h.
Referenced by GetParam(), and SaveParams().
if_else_block_index_
int32_t v8::internal::wasm::WasmBytecodeGenerator::BlockData::if_else_block_index_
Definition at line 1514 of file wasm-interpreter.h.
Referenced by v8::internal::wasm::WasmBytecodeGenerator::EndBlock(), HasElseBranch(), and v8::internal::wasm::WasmBytecodeGenerator::PatchBranchOffsets().
is_unreachable_
bool v8::internal::wasm::WasmBytecodeGenerator::BlockData::is_unreachable_
Definition at line 1521 of file wasm-interpreter.h.
opcode_
WasmOpcode v8::internal::wasm::WasmBytecodeGenerator::BlockData::opcode_
Definition at line 1509 of file wasm-interpreter.h.
Referenced by IsBlock(), IsCatch(), IsCatchAll(), IsElse(), IsIf(), IsLoop(), IsTry(), v8::internal::wasm::WasmBytecodeGenerator::RestoreIfElseParams(), v8::internal::wasm::WasmBytecodeGenerator::StoreBlockParamsAndResultsIntoSlots(), and v8::internal::wasm::WasmBytecodeGenerator::StoreBlockParamsIntoSlots().
params_slots_count_
uint32_t v8::internal::wasm::WasmBytecodeGenerator::BlockData::params_slots_count_
Definition at line 1519 of file wasm-interpreter.h.
parent_block_index_
int32_t v8::internal::wasm::WasmBytecodeGenerator::BlockData::parent_block_index_
Definition at line 1513 of file wasm-interpreter.h.
Referenced by IsRootBlock().
parent_try_block_index_
int32_t v8::internal::wasm::WasmBytecodeGenerator::BlockData::parent_try_block_index_
Definition at line 1520 of file wasm-interpreter.h.
Referenced by v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction().
rets_slots_count_
uint32_t v8::internal::wasm::WasmBytecodeGenerator::BlockData::rets_slots_count_
Definition at line 1518 of file wasm-interpreter.h.
signature_
WasmInstruction::Optional::Block v8::internal::wasm::WasmBytecodeGenerator::BlockData::signature_
Definition at line 1516 of file wasm-interpreter.h.
Referenced by v8::internal::wasm::WasmBytecodeGenerator::GetParamType(), v8::internal::wasm::WasmBytecodeGenerator::GetReturnType(), v8::internal::wasm::WasmBytecodeGenerator::HasVoidSignature(), v8::internal::wasm::WasmBytecodeGenerator::ParamsCount(), and v8::internal::wasm::WasmBytecodeGenerator::ReturnsCount().
stack_size_
uint32_t v8::internal::wasm::WasmBytecodeGenerator::BlockData::stack_size_
Definition at line 1510 of file wasm-interpreter.h.
Referenced by v8::internal::wasm::WasmBytecodeGenerator::RestoreIfElseParams(), v8::internal::wasm::WasmBytecodeGenerator::Return(), and v8::internal::wasm::WasmBytecodeGenerator::StoreBlockParamsAndResultsIntoSlots().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/wasm/interpreter/wasm-interpreter.h