v8::internal::torque::CallCsaMacroInstruction Struct Reference
#include <instructions.h>
Public Member Functions
CallCsaMacroInstruction (Macro *macro, std::vector< std::string > constexpr_arguments, std::optional< Block * > catch_block)
void AppendSuccessorBlocks (std::vector< Block * > *block_list) const override
std::optional< DefinitionLocation > GetExceptionObjectDefinition () const
std::size_t GetValueDefinitionCount () const
DefinitionLocation GetValueDefinition (std::size_t index) const
Public Attributes
Macro * macro
std::vector< std::string > constexpr_arguments
std::optional< Block * > catch_block
Detailed Description
Definition at line 475 of file instructions.h.
Constructor & Destructor Documentation
CallCsaMacroInstruction()
v8::internal::torque::CallCsaMacroInstruction::CallCsaMacroInstruction (Macro * macro, std::vector< std::string > constexpr_arguments, std::optional< Block * > catch_block) [inline]
Definition at line 477 of file instructions.h.
      : macro(macro),
        constexpr_arguments(constexpr_arguments),
        catch_block(catch_block) {}
Member Function Documentation
AppendSuccessorBlocks()
void v8::internal::torque::CallCsaMacroInstruction::AppendSuccessorBlocks (std::vector< Block * > * block_list) const [inline], [override], [virtual]
Reimplemented from v8::internal::torque::InstructionBase.
Definition at line 483 of file instructions.h.
                                                                           {
    if (catch_block) block_list->push_back(*catch_block);
  }
References catch_block.
GetExceptionObjectDefinition()
std::optional< DefinitionLocation > v8::internal::torque::CallCsaMacroInstruction::GetExceptionObjectDefinition () const
Definition at line 253 of file instructions.cc.
                                                            {
  if (!catch_block) return std::nullopt;
  return DefinitionLocation::Instruction(this, GetValueDefinitionCount());
}
References catch_block, GetValueDefinitionCount(), and v8::internal::torque::DefinitionLocation::Instruction().
GetValueDefinition()
DefinitionLocation v8::internal::torque::CallCsaMacroInstruction::GetValueDefinition (std::size_t index) const
Definition at line 262 of file instructions.cc.
                           {
  DCHECK_LT(index, GetValueDefinitionCount());
  return DefinitionLocation::Instruction(this, index);
}
References DCHECK_LT, GetValueDefinitionCount(), v8::internal::index, and v8::internal::torque::DefinitionLocation::Instruction().
GetValueDefinitionCount()
std::size_t v8::internal::torque::CallCsaMacroInstruction::GetValueDefinitionCount () const
Definition at line 258 of file instructions.cc.
                                                                 {
  return LowerType(macro->signature().return_type).size();
}
References v8::internal::torque::LowerType(), macro, v8::internal::torque::Signature::return_type, and v8::internal::torque::Callable::signature().
Referenced by GetExceptionObjectDefinition(), and GetValueDefinition().
Member Data Documentation
catch_block
std::optional<Block*> v8::internal::torque::CallCsaMacroInstruction::catch_block
Definition at line 493 of file instructions.h.
Referenced by AppendSuccessorBlocks(), GetExceptionObjectDefinition(), and v8::internal::torque::operator<<().
constexpr_arguments
std::vector<std::string> v8::internal::torque::CallCsaMacroInstruction::constexpr_arguments
Definition at line 492 of file instructions.h.
Referenced by v8::internal::torque::operator<<().
macro
Macro* v8::internal::torque::CallCsaMacroInstruction::macro
Definition at line 491 of file instructions.h.
Referenced by GetValueDefinitionCount(), and v8::internal::torque::operator<<().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/torque/instructions.h
/mnt/V8SourceCode/src/torque/instructions.cc