v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar Struct Reference
Public Member Functions
template<class T >
Symbol * NonemptyListAllowIfAnnotation (Symbol *element, std::optional< Symbol * > separator={})
template<class T >
Symbol * ListAllowIfAnnotation (Symbol *element, std::optional< Symbol * > separator={})
TorqueGrammar ()
Symbol * OneOf (const std::vector< std::string > &alternatives)
Symbol * BinaryOperator (Symbol *nextLevel, Symbol *op)
Static Public Member Functions
static bool MatchWhitespace (InputPosition *pos)
static bool MatchIdentifier (InputPosition *pos)
static bool MatchAnnotation (InputPosition *pos)
static bool MatchIntrinsicName (InputPosition *pos)
static bool MatchStringLiteral (InputPosition *pos)
static bool MatchHexLiteral (InputPosition *pos)
static bool MatchIntegerLiteral (InputPosition *pos)
static bool MatchFloatingPointLiteral (InputPosition *pos)
template<class T , bool first>
static std::optional< ParseResult > MakeExtendedVectorIfAnnotation (ParseResultIterator *child_results)
Public Attributes
Symbol * expression = &assignmentExpression
Symbol identifier
Symbol name = {Rule({&identifier}, MakeIdentifier)}
Symbol annotationName
Symbol intrinsicName
Symbol stringLiteral
Symbol externalString = {Rule({&stringLiteral}, StringLiteralUnquoteAction)}
Symbol integerLiteral
Symbol floatingPointLiteral
Symbol int32Literal
Symbol annotationParameter
Symbol annotationParameters
Symbol annotation
Symbol * annotations = List<Annotation>(&annotation)
Symbol namespaceQualification
Symbol * typeList = List<TypeExpression*>(&type, Token(`,`))
Symbol simpleType
Symbol type
Symbol genericParameter
Symbol genericParameters
Symbol genericSpecializationTypeList
Symbol * optionalGenericParameters = Optional<TypeList>(&genericParameters)
Symbol implicitParameterList
Symbol * optionalImplicitParameterList
Symbol typeListMaybeVarArgs
Symbol labelParameter
Symbol returnType
Symbol * optionalLabelList
Symbol * optionalOtherwise
Symbol nameAndType = {Rule({&name, Token(`:`), &type}, MakeNameAndType)}
Symbol * optionalArraySpecifier
Symbol classField
Symbol structField
Symbol bitFieldDeclaration
Symbol parameterListNoVararg
Symbol parameterListAllowVararg
Symbol incrementDecrementOperator
Symbol identifierExpression
Symbol argumentList
Symbol callExpression
Symbol callMethodExpression
Symbol namedExpression
Symbol initializerList
Symbol intrinsicCallExpression
Symbol newExpression
Symbol primaryExpression
Symbol unaryExpression
Symbol * multiplicativeExpression
Symbol * additiveExpression
Symbol shiftOperator
Symbol * shiftExpression = BinaryOperator(additiveExpression, &shiftOperator)
Symbol relationalExpression
Symbol * equalityExpression
Symbol * bitwiseExpression
Symbol logicalAndExpression
Symbol logicalOrExpression
Symbol conditionalExpression
Symbol assignmentOperator
Symbol assignmentExpression
Symbol block
Symbol tryHandler
Symbol expressionWithSource = {Rule({expression}, MakeExpressionWithSource)}
Symbol * optionalTypeSpecifier
Symbol enumEntry
Symbol varDeclaration
Symbol varDeclarationWithInitialization
Symbol atomarStatement
Symbol statement
Symbol typeswitchCase
Symbol optionalBody
Symbol method
Symbol optionalClassBody
Symbol declaration
Symbol declarationList
Symbol file
Additional Inherited Members
Detailed Description
Definition at line 2264 of file torque-parser.cc.
Constructor & Destructor Documentation
TorqueGrammar()
v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::TorqueGrammar () [inline]
Definition at line 2409 of file torque-parser.cc.
: Grammar(&file) { SetWhitespace(MatchWhitespace); }
Member Function Documentation
BinaryOperator()
Symbol* v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::BinaryOperator (Symbol * nextLevel, Symbol * op) [inline]
Definition at line 2596 of file torque-parser.cc.
                                                        {
    Symbol* result = NewSymbol();
    *result = {Rule({nextLevel}),
               Rule({result, op, nextLevel}, MakeBinaryOperator)};
    return result;
  }
References v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeBinaryOperator(), and v8::base::internal::result.
ListAllowIfAnnotation()
template<class T >
Symbol* v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::ListAllowIfAnnotation (Symbol * element, std::optional< Symbol * > separator = {}) [inline]
Definition at line 2403 of file torque-parser.cc.
                                                                 {}) {
    return TryOrDefault<std::vector<T>>(
        NonemptyListAllowIfAnnotation<T>(element, separator));
  }
MakeExtendedVectorIfAnnotation()
template<class T , bool first>
static std::optional<ParseResult> v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::MakeExtendedVectorIfAnnotation (ParseResultIterator * child_results) [inline], [static]
Definition at line 2378 of file torque-parser.cc.
                                          {
    std::vector<T> l = {};
    if (!first) l = child_results->NextAs<std::vector<T>>();
    bool enabled = ProcessIfAnnotation(child_results);
    T x = child_results->NextAs<T>();
    if (enabled) l.push_back(std::move(x));
    return ParseResult{std::move(l)};
  }
References v8::internal::compiler::turboshaft::l, v8::internal::torque::ParseResultIterator::NextAs(), and v8::internal::torque::anonymous_namespace{torque-parser.cc}::ProcessIfAnnotation().
MatchAnnotation()
static bool v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::MatchAnnotation (InputPosition * pos) [inline], [static]
Definition at line 2291 of file torque-parser.cc.
                                                  {
    InputPosition current = *pos;
    if (!MatchString("@", &current)) return false;
    if (!MatchIdentifier(&current)) return false;
    *pos = current;
    return true;
  }
MatchFloatingPointLiteral()
static bool v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::MatchFloatingPointLiteral (InputPosition * pos) [inline], [static]
Definition at line 2357 of file torque-parser.cc.
                                                            {
    InputPosition current = *pos;
    bool found_digit = false;
    MatchString("-", &current);
    while (MatchChar(std::isdigit, &current)) found_digit = true;
    if (!MatchString(".", &current)) return false;
    while (MatchChar(std::isdigit, &current)) found_digit = true;
    if (!found_digit) return false;
    *pos = current;
    if ((MatchString("e", &current) || MatchString("E", &current)) &&
        (MatchString("+", &current) || MatchString("-", &current) || true) &&
        MatchChar(std::isdigit, &current)) {
      while (MatchChar(std::isdigit, &current)) {
      }
      *pos = current;
      return true;
    }
    return true;
  }
MatchHexLiteral()
static bool v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::MatchHexLiteral (InputPosition * pos) [inline], [static]
Definition at line 2333 of file torque-parser.cc.
                                                  {
    InputPosition current = *pos;
    MatchString("-", &current);
    if (MatchString("0x", &current) && MatchChar(std::isxdigit, &current)) {
      while (MatchChar(std::isxdigit, &current)) {
      }
      *pos = current;
      return true;
    }
    return false;
  }
MatchIdentifier()
static bool v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::MatchIdentifier (InputPosition * pos) [inline], [static]
Definition at line 2281 of file torque-parser.cc.
                                                  {
    InputPosition current = *pos;
    MatchString("_", &current);
    if (!MatchChar(std::isalpha, &current)) return false;
    while (MatchChar(std::isalnum, &current) || MatchString("_", &current)) {
    }
    *pos = current;
    return true;
  }
MatchIntegerLiteral()
static bool v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::MatchIntegerLiteral (InputPosition * pos) [inline], [static]
Definition at line 2345 of file torque-parser.cc.
                                                      {
    InputPosition current = *pos;
    bool found_digit = false;
    MatchString("-", &current);
    while (MatchChar(std::isdigit, &current)) found_digit = true;
    if (found_digit) {
      *pos = current;
      return true;
    }
    return false;
  }
MatchIntrinsicName()
static bool v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::MatchIntrinsicName (InputPosition * pos) [inline], [static]
Definition at line 2299 of file torque-parser.cc.
                                                     {
    InputPosition current = *pos;
    if (!MatchString("%", &current)) return false;
    if (!MatchIdentifier(&current)) return false;
    *pos = current;
    return true;
  }
MatchStringLiteral()
static bool v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::MatchStringLiteral (InputPosition * pos) [inline], [static]
Definition at line 2307 of file torque-parser.cc.
                                                     {
    InputPosition current = *pos;
    if (MatchString("\"", &current)) {
      while (
          (MatchString("\\", &current) && MatchAnyChar(&current)) ||
          MatchChar([](char c) { return c != '"' && c != '\n'; }, &current)) {
      }
      if (MatchString("\"", &current)) {
        *pos = current;
        return true;
      }
    }
    current = *pos;
    if (MatchString("'", &current)) {
      while (
          (MatchString("\\", &current) && MatchAnyChar(&current)) ||
          MatchChar([](char c) { return c != '\'' && c != '\n'; }, &current)) {
      }
      if (MatchString("'", &current)) {
        *pos = current;
        return true;
      }
    }
    return false;
  }
MatchWhitespace()
static bool v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::MatchWhitespace (InputPosition * pos) [inline], [static]
Definition at line 2265 of file torque-parser.cc.
                                                  {
    while (true) {
      if (MatchChar(std::isspace, pos)) continue;
      if (MatchString("//", pos)) {
        while (MatchChar([](char c) { return c != '\n'; }, pos)) {
        }
        continue;
      }
      if (MatchString("/*", pos)) {
        while (!MatchString("*/", pos)) ++*pos;
        continue;
      }
      return true;
    }
  }
NonemptyListAllowIfAnnotation()
template<class T >
Symbol* v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::NonemptyListAllowIfAnnotation (Symbol * element, std::optional< Symbol * > separator = {}) [inline]
Definition at line 2390 of file torque-parser.cc.
                                                                         {}) {
    Symbol* list = NewSymbol();
    *list = {
        Rule({annotations, element}, MakeExtendedVectorIfAnnotation<T, true>),
        separator ? Rule({list, annotations, *separator, element},
                         MakeExtendedVectorIfAnnotation<T, false>)
                  : Rule({list, annotations, element},
                         MakeExtendedVectorIfAnnotation<T, false>)};
    return list;
  }
OneOf()
Symbol* v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::OneOf (const std::vector< std::string > & alternatives) [inline]
Definition at line 2587 of file torque-parser.cc.
                                                          {
    Symbol* result = NewSymbol();
    for (const std::string& s : alternatives) {
      result->AddRule(Rule({Token(s)}, MakeIdentifierFromMatchedInput));
    }
    return result;
  }
References v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeIdentifierFromMatchedInput(), v8::base::internal::result, and v8::internal::string.
Member Data Documentation
additiveExpression
Symbol* v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::additiveExpression
Initial value:
=
      BinaryOperator(multiplicativeExpression, OneOf({"+", "-"}))
Definition at line 2691 of file torque-parser.cc.
annotation
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::annotation
Initial value:
= {Rule(
      {&annotationName, Optional<AnnotationParameter>(&annotationParameters)},
      MakeAnnotation)}
Definition at line 2460 of file torque-parser.cc.
annotationName
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::annotationName
Initial value:
= {
      Rule({Pattern(MatchAnnotation)}, MakeIdentifierFromMatchedInput)}
Definition at line 2422 of file torque-parser.cc.
annotationParameter
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::annotationParameter
Initial value:
= {
      Rule({&identifier}, MakeStringAnnotationParameter),
      Rule({&int32Literal}, MakeIntAnnotationParameter),
      Rule({&externalString}, MakeStringAnnotationParameter)}
Definition at line 2450 of file torque-parser.cc.
annotationParameters
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::annotationParameters
Initial value:
= {
      Rule({Token("("), &annotationParameter, Token(")")})}
Definition at line 2456 of file torque-parser.cc.
annotations
Symbol* v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::annotations = List<Annotation>(&annotation)
Definition at line 2465 of file torque-parser.cc.
argumentList
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::argumentList
Initial value:
= {Rule(
      {Token("("), List<Expression*>(expression, Token(",")), Token(")")})}
Definition at line 2620 of file torque-parser.cc.
assignmentExpression
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::assignmentExpression
Initial value:
= {
      Rule({&conditionalExpression}),
      Rule({&conditionalExpression, &assignmentOperator, &assignmentExpression},
           MakeAssignmentExpression)}
Definition at line 2746 of file torque-parser.cc.
assignmentOperator
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::assignmentOperator
Initial value:
= {
      Rule({Token("=")}, YieldDefaultValue<std::optional<std::string>>),
      Rule({OneOf({"*=", "/=", "%=", "+=", "-=", "<<=", ">>=", ">>>=", "&=",
                   "^=", "|="})},
           ExtractAssignmentOperator)}
Definition at line 2739 of file torque-parser.cc.
atomarStatement
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::atomarStatement
Initial value:
= {
      Rule({expression}, MakeExpressionStatement),
      Rule({Token("return"), Optional<Expression*>(expression)},
           MakeReturnStatement),
      Rule({Token("tail"), &callExpression}, MakeTailCallStatement),
      Rule({Token("break")}, MakeBreakStatement),
      Rule({Token("continue")}, MakeContinueStatement),
      Rule({Token("goto"), &name,
            TryOrDefault<std::vector<Expression*>>(&argumentList)},
           MakeGotoStatement),
      Rule({OneOf({"debug", "unreachable"})}, MakeDebugStatement)}
Definition at line 2788 of file torque-parser.cc.
bitFieldDeclaration
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::bitFieldDeclaration
Initial value:
= {Rule({&name, Token(":"), &type, Token(":"),
                                      &int32Literal, Token("bit"), Token(";")},
                                     MakeBitFieldDeclaration)}
Definition at line 2568 of file torque-parser.cc.
bitwiseExpression
Symbol* v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::bitwiseExpression
Initial value:
=
      BinaryOperator(equalityExpression, OneOf({"&", "|"}))
Definition at line 2716 of file torque-parser.cc.
block
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::block
Initial value:
= {
      Rule({CheckIf(Token("deferred")), Token("{"),
            ListAllowIfAnnotation<Statement*>(&statement), Token("}")},
           MakeBlockStatement)}
Definition at line 2752 of file torque-parser.cc.
callExpression
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::callExpression
Initial value:
= {Rule(
      {&identifierExpression, &argumentList, optionalOtherwise}, MakeCall)}
Definition at line 2624 of file torque-parser.cc.
callMethodExpression
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::callMethodExpression
Initial value:
= {Rule(
      {&primaryExpression, Token("."), &name, &argumentList, optionalOtherwise},
      MakeMethodCall)}
Definition at line 2628 of file torque-parser.cc.
classField
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::classField
Initial value:
= {
      Rule({annotations, CheckIf(Token("weak")), CheckIf(Token("const")), &name,
            CheckIf(Token("?")), optionalArraySpecifier, Token(":"), &type,
            Token(";")},
           MakeClassField)}
Definition at line 2556 of file torque-parser.cc.
conditionalExpression
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::conditionalExpression
Initial value:
= {
      Rule({&logicalOrExpression}),
      Rule({&logicalOrExpression, Token("?"), expression, Token(":"),
            &conditionalExpression},
           MakeConditionalExpression)}
Definition at line 2732 of file torque-parser.cc.
declaration
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::declaration
Definition at line 2862 of file torque-parser.cc.
declarationList
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::declarationList
Initial value:
= {
      Rule({List<std::vector<Declaration*>>(&declaration)}, ConcatList)}
Definition at line 2949 of file torque-parser.cc.
enumEntry
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::enumEntry
Initial value:
= {
      Rule({annotations, &name, optionalTypeSpecifier}, MakeEnumEntry)}
Definition at line 2773 of file torque-parser.cc.
equalityExpression
Symbol* v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::equalityExpression
Initial value:
=
      BinaryOperator(&relationalExpression, OneOf({"==", "!="}))
Definition at line 2712 of file torque-parser.cc.
expression
Symbol* v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::expression = &assignmentExpression
Definition at line 2412 of file torque-parser.cc.
expressionWithSource
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::expressionWithSource = {Rule({expression}, MakeExpressionWithSource)}
Definition at line 2767 of file torque-parser.cc.
externalString
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::externalString = {Rule({&stringLiteral}, StringLiteralUnquoteAction)}
Definition at line 2434 of file torque-parser.cc.
file
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::file
Initial value:
= {Rule({&file, Token("import"), &externalString},
                      ProcessTorqueImportDeclaration),
                 Rule({&file, &declaration}, AddGlobalDeclarations), Rule({})}
Definition at line 2952 of file torque-parser.cc.
floatingPointLiteral
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::floatingPointLiteral
Initial value:
= {
      Rule({Pattern(MatchFloatingPointLiteral)}, YieldDouble)}
Definition at line 2442 of file torque-parser.cc.
genericParameter
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::genericParameter
Initial value:
= {
      Rule({&name, Token(":"), Token("type"),
            Optional<TypeExpression*>(Sequence({Token("extends"), &type}))},
           MakeGenericParameter)}
Definition at line 2494 of file torque-parser.cc.
genericParameters
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::genericParameters
Initial value:
= {
      Rule({Token("<"), List<GenericParameter>(&genericParameter, Token(",")),
            Token(">")})}
Definition at line 2500 of file torque-parser.cc.
genericSpecializationTypeList
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::genericSpecializationTypeList
Initial value:
= {
      Rule({Token("<"), typeList, Token(">")})}
Definition at line 2505 of file torque-parser.cc.
identifier
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::identifier
Initial value:
= {Rule({Pattern(MatchIdentifier)}, YieldMatchedInput),
                       Rule({Token("runtime")}, YieldMatchedInput)}
Definition at line 2415 of file torque-parser.cc.
identifierExpression
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::identifierExpression
Initial value:
= {
      Rule({&namespaceQualification, &name,
            TryOrDefault<TypeList>(&genericSpecializationTypeList)},
           MakeIdentifierExpression),
  }
Definition at line 2613 of file torque-parser.cc.
implicitParameterList
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::implicitParameterList
Initial value:
{
      Rule({Token("("), OneOf({"implicit", "js-implicit"}),
            List<NameAndTypeExpression>(&nameAndType, Token(",")), Token(")")},
           MakeImplicitParameterList)}
Definition at line 2511 of file torque-parser.cc.
incrementDecrementOperator
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::incrementDecrementOperator
Initial value:
= {
      Rule({Token("++")},
           YieldIntegralConstant<IncrementDecrementOperator,
                                 IncrementDecrementOperator::kIncrement>),
      Rule({Token("--")},
           YieldIntegralConstant<IncrementDecrementOperator,
                                 IncrementDecrementOperator::kDecrement>)}
Definition at line 2604 of file torque-parser.cc.
initializerList
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::initializerList
Initial value:
= {
      Rule({Token("{"), List<NameAndExpression>(&namedExpression, Token(",")),
            Token("}")})}
Definition at line 2638 of file torque-parser.cc.
int32Literal
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::int32Literal
Initial value:
= {Rule({Pattern(MatchIntegerLiteral)}, YieldInt32),
                         Rule({Pattern(MatchHexLiteral)}, YieldInt32)}
Definition at line 2446 of file torque-parser.cc.
integerLiteral
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::integerLiteral
Initial value:
= {
      Rule({Pattern(MatchIntegerLiteral)}, YieldIntegerLiteral),
      Rule({Pattern(MatchHexLiteral)}, YieldIntegerLiteral)}
Definition at line 2437 of file torque-parser.cc.
intrinsicCallExpression
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::intrinsicCallExpression
Initial value:
= {Rule(
      {&intrinsicName, TryOrDefault<TypeList>(&genericSpecializationTypeList),
       &argumentList},
      MakeIntrinsicCallExpression)}
Definition at line 2643 of file torque-parser.cc.
intrinsicName
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::intrinsicName
Initial value:
= {
      Rule({Pattern(MatchIntrinsicName)}, MakeIdentifierFromMatchedInput)}
Definition at line 2426 of file torque-parser.cc.
labelParameter
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::labelParameter
Initial value:
= {Rule(
      {&name,
       TryOrDefault<TypeList>(Sequence({Token("("), typeList, Token(")")}))},
      MakeLabelAndTypes)}
Definition at line 2529 of file torque-parser.cc.
logicalAndExpression
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::logicalAndExpression
Initial value:
= {
      Rule({bitwiseExpression}),
      Rule({&logicalAndExpression, Token("&&"), bitwiseExpression},
           MakeLogicalAndExpression)}
Definition at line 2720 of file torque-parser.cc.
logicalOrExpression
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::logicalOrExpression
Initial value:
= {
      Rule({&logicalAndExpression}),
      Rule({&logicalOrExpression, Token("||"), &logicalAndExpression},
           MakeLogicalOrExpression)}
Definition at line 2726 of file torque-parser.cc.
method
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::method
Initial value:
= {Rule(
      {CheckIf(Token("transitioning")),
       Optional<std::string>(Sequence({Token("operator"), &externalString})),
       Token("macro"), &name, &parameterListNoVararg, &returnType,
       optionalLabelList, &block},
      MakeMethodDeclaration)}
Definition at line 2847 of file torque-parser.cc.
multiplicativeExpression
Symbol* v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::multiplicativeExpression
Initial value:
=
      BinaryOperator(&unaryExpression, OneOf({"*", "/", "%"}))
Definition at line 2687 of file torque-parser.cc.
name
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::name = {Rule({&identifier}, MakeIdentifier)}
Definition at line 2419 of file torque-parser.cc.
nameAndType
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::nameAndType = {Rule({&name, Token(`:`), &type}, MakeNameAndType)}
Definition at line 2549 of file torque-parser.cc.
namedExpression
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::namedExpression
Initial value:
= {
      Rule({&name, Token(":"), expression}, MakeNameAndExpression),
      Rule({expression}, MakeNameAndExpressionFromExpression)}
Definition at line 2633 of file torque-parser.cc.
namespaceQualification
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::namespaceQualification
Initial value:
= {
      Rule({CheckIf(Token("::")),
            List<std::string>(Sequence({&identifier, Token("::")}))},
           MakeNamespaceQualification)}
Definition at line 2468 of file torque-parser.cc.
newExpression
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::newExpression
Initial value:
= {
      Rule({Token("new"),
            CheckIf(Sequence({Token("("), Token("Pretenured"), Token(")")})),
            CheckIf(Sequence({Token("("), Token("ClearPadding"), Token(")")})),
            &simpleType, &initializerList},
           MakeNewExpression)}
Definition at line 2649 of file torque-parser.cc.
optionalArraySpecifier
Symbol* v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::optionalArraySpecifier
Initial value:
=
      Optional<Expression*>(Sequence({Token("["), expression, Token("]")}))
Definition at line 2552 of file torque-parser.cc.
optionalBody
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::optionalBody
Initial value:
= {
      Rule({&block}, CastParseResult<Statement*, std::optional<Statement*>>),
      Rule({Token(";")}, YieldDefaultValue<std::optional<Statement*>>)}
Definition at line 2842 of file torque-parser.cc.
optionalClassBody
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::optionalClassBody
Initial value:
= {
      Rule({Token("{"), List<Declaration*>(&method),
            List<ClassFieldExpression>(&classField), Token("}")},
           MakeClassBody),
      Rule({Token(";")}, YieldDefaultValue<std::optional<ClassBody*>>)}
Definition at line 2855 of file torque-parser.cc.
optionalGenericParameters
Symbol* v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::optionalGenericParameters = Optional<TypeList>(&genericParameters)
Definition at line 2509 of file torque-parser.cc.
optionalImplicitParameterList
Symbol* v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::optionalImplicitParameterList
Initial value:
{
      Optional<ImplicitParameters>(&implicitParameterList)}
Definition at line 2516 of file torque-parser.cc.
optionalLabelList
Symbol* v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::optionalLabelList
Initial value:
{TryOrDefault<LabelAndTypesVector>(
      Sequence({Token("labels"),
                NonemptyList<LabelAndTypes>(&labelParameter, Token(","))}))}
Definition at line 2539 of file torque-parser.cc.
optionalOtherwise
Symbol* v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::optionalOtherwise
Initial value:
{TryOrDefault<std::vector<Statement*>>(
      Sequence({Token("otherwise"),
                NonemptyList<Statement*>(&atomarStatement, Token(","))}))}
Definition at line 2544 of file torque-parser.cc.
optionalTypeSpecifier
Symbol* v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::optionalTypeSpecifier
Initial value:
=
      Optional<TypeExpression*>(Sequence({Token(":"), &type}))
Definition at line 2769 of file torque-parser.cc.
parameterListAllowVararg
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::parameterListAllowVararg
Initial value:
= {
      Rule({&parameterListNoVararg}),
      Rule({optionalImplicitParameterList, Token("("),
            List<NameAndTypeExpression>(Sequence({&nameAndType, Token(",")})),
            Token("..."), &identifier, Token(")")},
           MakeParameterList<true, true>)}
Definition at line 2579 of file torque-parser.cc.
parameterListNoVararg
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::parameterListNoVararg
Initial value:
= {
      Rule({optionalImplicitParameterList, Token("("),
            List<NameAndTypeExpression>(&nameAndType, Token(",")), Token(")")},
           MakeParameterList<false, true>)}
Definition at line 2573 of file torque-parser.cc.
primaryExpression
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::primaryExpression
Initial value:
= {
      Rule({&callExpression}),
      Rule({&callMethodExpression}),
      Rule({&intrinsicCallExpression}),
      Rule({&identifierExpression}),
      Rule({&primaryExpression, Token("."), &name}, MakeFieldAccessExpression),
      Rule({&primaryExpression, Token("->"), &name},
           MakeReferenceFieldAccessExpression),
      Rule({&primaryExpression, Token("["), expression, Token("]")},
           MakeElementAccessExpression),
      Rule({&integerLiteral}, MakeIntegerLiteralExpression),
      Rule({&floatingPointLiteral}, MakeFloatingPointLiteralExpression),
      Rule({&stringLiteral}, MakeStringLiteralExpression),
      Rule({&simpleType, &initializerList}, MakeStructExpression),
      Rule({&newExpression}),
      Rule({Token("("), expression, Token(")")})}
Definition at line 2657 of file torque-parser.cc.
relationalExpression
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::relationalExpression
Initial value:
= {
      Rule({shiftExpression}),
      Rule({shiftExpression, OneOf({"<", ">", "<=", ">="}), shiftExpression},
           MakeBinaryOperator)}
Definition at line 2706 of file torque-parser.cc.
returnType
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::returnType
Initial value:
= {Rule({Token(":"), &type}),
                       Rule({}, DeprecatedMakeVoidType)}
Definition at line 2535 of file torque-parser.cc.
shiftExpression
Symbol* v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::shiftExpression = BinaryOperator(additiveExpression, &shiftOperator)
Definition at line 2701 of file torque-parser.cc.
shiftOperator
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::shiftOperator
Initial value:
= {
      Rule({Token("<<")}, MakeIdentifierFromMatchedInput),
      Rule({Token(">"), Token(">")}, MakeRightShiftIdentifier),
      Rule({Token(">"), Token(">"), Token(">")}, MakeRightShiftIdentifier)}
Definition at line 2695 of file torque-parser.cc.
simpleType
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::simpleType
Initial value:
= {
      Rule({Token("("), &type, Token(")")}),
      Rule({&namespaceQualification, CheckIf(Token("constexpr")), &identifier,
            TryOrDefault<std::vector<TypeExpression*>>(
                &genericSpecializationTypeList)},
           MakeBasicTypeExpression),
      Rule({Token("builtin"), Token("("), typeList, Token(")"), Token("=>"),
            &simpleType},
           MakeFunctionTypeExpression),
      Rule({CheckIf(Token("const")), Token("&"), &simpleType},
           MakeReferenceTypeExpression)}
Definition at line 2477 of file torque-parser.cc.
statement
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::statement
Definition at line 2801 of file torque-parser.cc.
stringLiteral
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::stringLiteral
Initial value:
= {
      Rule({Pattern(MatchStringLiteral)}, YieldMatchedInput)}
Definition at line 2430 of file torque-parser.cc.
structField
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::structField
Initial value:
= {
      Rule({CheckIf(Token("const")), &name, Token(":"), &type, Token(";")},
           MakeStructField)}
Definition at line 2563 of file torque-parser.cc.
tryHandler
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::tryHandler
Initial value:
= {
      Rule({Token("label"), &name,
            TryOrDefault<ParameterList>(&parameterListNoVararg), &block},
           MakeLabelBlock),
      Rule({Token("catch"), Token("("),
            List<std::string>(&identifier, Token(",")), Token(")"), &block},
           MakeCatchBlock)}
Definition at line 2758 of file torque-parser.cc.
type
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::type
Initial value:
= {Rule({&simpleType}), Rule({&type, Token("|"), &simpleType},
                                           MakeUnionTypeExpression)}
Definition at line 2490 of file torque-parser.cc.
typeList
Symbol* v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::typeList = List<TypeExpression*>(&type, Token(`,`))
Definition at line 2474 of file torque-parser.cc.
typeListMaybeVarArgs
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::typeListMaybeVarArgs
Initial value:
= {
      Rule({optionalImplicitParameterList, Token("("),
            List<TypeExpression*>(Sequence({&type, Token(",")})), Token("..."),
            Token(")")},
           MakeParameterList<true, false>),
      Rule({optionalImplicitParameterList, Token("("), typeList, Token(")")},
           MakeParameterList<false, false>)}
Definition at line 2520 of file torque-parser.cc.
typeswitchCase
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::typeswitchCase
Initial value:
= {
      Rule({Token("case"), Token("("),
            Optional<Identifier*>(Sequence({&name, Token(":")})), &type,
            Token(")"), Token(":"), &block},
           MakeTypeswitchCase)}
Definition at line 2835 of file torque-parser.cc.
unaryExpression
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::unaryExpression
Initial value:
= {
      Rule({&primaryExpression}),
      Rule({OneOf({"+", "-", "!", "~", "&"}), &unaryExpression},
           MakeUnaryOperator),
      Rule({Token("*"), &unaryExpression}, MakeDereferenceExpression),
      Rule({Token("..."), &unaryExpression}, MakeSpreadExpression),
      Rule({&incrementDecrementOperator, &unaryExpression},
           MakeIncrementDecrementExpressionPrefix),
      Rule({&unaryExpression, &incrementDecrementOperator},
           MakeIncrementDecrementExpressionPostfix)}
Definition at line 2675 of file torque-parser.cc.
varDeclaration
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::varDeclaration
Initial value:
= {
      Rule({OneOf({"let", "const"}), &name, optionalTypeSpecifier},
           MakeVarDeclarationStatement)}
Definition at line 2777 of file torque-parser.cc.
varDeclarationWithInitialization
Symbol v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::varDeclarationWithInitialization
Initial value:
= {
      Rule({OneOf({"let", "const"}), &name, optionalTypeSpecifier, Token("="),
            expression},
           MakeVarDeclarationStatement)}
Definition at line 2782 of file torque-parser.cc.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/torque/torque-parser.cc