v8::internal::DateParser::DateToken Struct Reference
Public Member Functions
bool IsInvalid ()
bool IsUnknown ()
bool IsNumber ()
bool IsSymbol ()
bool IsWhiteSpace ()
bool IsEndOfInput ()
bool IsKeyword ()
int length ()
int number ()
KeywordType keyword_type ()
int keyword_value ()
char symbol ()
bool IsSymbol (char symbol)
bool IsKeywordType (KeywordType tag)
bool IsFixedLengthNumber (int length)
bool IsAsciiSign ()
int ascii_sign ()
bool IsKeywordZ ()
bool IsUnknown (int character)
Static Public Member Functions
static DateToken Keyword (KeywordType tag, int value, int length)
static DateToken Number (int value, int length)
static DateToken Symbol (char symbol)
static DateToken EndOfInput ()
static DateToken WhiteSpace (int length)
static DateToken Unknown ()
static DateToken Invalid ()
Private Types
enum TagType {
kInvalidTokenTag = -6
, kUnknownTokenTag = -5
, kWhiteSpaceTag = -4
, kNumberTag = -3
,
kSymbolTag = -2
, kEndOfInputTag = -1
, kKeywordTagStart = 0
 }
Private Member Functions
DateToken (int tag, int length, int value)
Private Attributes
int tag_
int length_
int value_
Detailed Description
Definition at line 139 of file dateparser.h.
Member Enumeration Documentation
TagType
enum v8::internal::DateParser::DateToken::TagType [private]
Enumerator
kInvalidTokenTag
kUnknownTokenTag
kWhiteSpaceTag
kNumberTag
kSymbolTag
kEndOfInputTag
kKeywordTagStart
Definition at line 203 of file dateparser.h.
                 {
      kInvalidTokenTag = -6,
      kUnknownTokenTag = -5,
      kWhiteSpaceTag = -4,
      kNumberTag = -3,
      kSymbolTag = -2,
      kEndOfInputTag = -1,
      kKeywordTagStart = 0
    };
Constructor & Destructor Documentation
DateToken()
v8::internal::DateParser::DateToken::DateToken (int tag, int length, int value) [inline], [private]
Definition at line 212 of file dateparser.h.
        : tag_(tag), length_(length), value_(value) {}
Referenced by EndOfInput(), Invalid(), Keyword(), Number(), Symbol(), Unknown(), and WhiteSpace().
Member Function Documentation
ascii_sign()
int v8::internal::DateParser::DateToken::ascii_sign () [inline]
Definition at line 177 of file dateparser.h.
                     {
      DCHECK(IsAsciiSign());
      return 44 - value_;
    }
References v8::internal::DCHECK(), IsAsciiSign(), and value_.
Referenced by v8::internal::DateParser::ParseES5DateTime().
EndOfInput()
static DateToken v8::internal::DateParser::DateToken::EndOfInput () [inline], [static]
Definition at line 195 of file dateparser.h.
{ return DateToken(kEndOfInputTag, 0, -1); }
References DateToken(), and kEndOfInputTag.
Referenced by v8::internal::DateParser::ParseES5DateTime().
Invalid()
static DateToken v8::internal::DateParser::DateToken::Invalid () [inline], [static]
Definition at line 200 of file dateparser.h.
{ return DateToken(kInvalidTokenTag, 0, -1); }
References DateToken(), and kInvalidTokenTag.
Referenced by v8::internal::DateParser::ParseES5DateTime().
IsAsciiSign()
bool v8::internal::DateParser::DateToken::IsAsciiSign () [inline]
Definition at line 174 of file dateparser.h.
                       {
      return tag_ == kSymbolTag && (value_ == '-' || value_ == '+');
    }
References kSymbolTag, tag_, and value_.
Referenced by ascii_sign(), v8::internal::DateParser::Parse(), and v8::internal::DateParser::ParseES5DateTime().
IsEndOfInput()
bool v8::internal::DateParser::DateToken::IsEndOfInput () [inline]
Definition at line 146 of file dateparser.h.
{ return tag_ == kEndOfInputTag; }
References kEndOfInputTag, and tag_.
Referenced by v8::internal::DateParser::Parse(), and v8::internal::DateParser::ParseES5DateTime().
IsFixedLengthNumber()
bool v8::internal::DateParser::DateToken::IsFixedLengthNumber (int length) [inline]
Definition at line 171 of file dateparser.h.
                                         {
      return IsNumber() && length_ == length;
    }
References IsNumber(), length(), and length_.
Referenced by v8::internal::DateParser::ParseES5DateTime().
IsInvalid()
bool v8::internal::DateParser::DateToken::IsInvalid () [inline]
Definition at line 141 of file dateparser.h.
{ return tag_ == kInvalidTokenTag; }
References kInvalidTokenTag, and tag_.
Referenced by v8::internal::DateParser::Parse().
IsKeyword()
bool v8::internal::DateParser::DateToken::IsKeyword () [inline]
Definition at line 147 of file dateparser.h.
{ return tag_ >= kKeywordTagStart; }
References kKeywordTagStart, and tag_.
Referenced by keyword_type(), and keyword_value().
IsKeywordType()
bool v8::internal::DateParser::DateToken::IsKeywordType (KeywordType tag) [inline]
Definition at line 170 of file dateparser.h.
{ return tag_ == tag; }
References tag_.
Referenced by IsKeywordZ(), and v8::internal::DateParser::ParseES5DateTime().
IsKeywordZ()
bool v8::internal::DateParser::DateToken::IsKeywordZ () [inline]
Definition at line 181 of file dateparser.h.
                      {
      return IsKeywordType(TIME_ZONE_NAME) && length_ == 1 && value_ == 0;
    }
References IsKeywordType(), length_, v8::internal::DateParser::TIME_ZONE_NAME, and value_.
Referenced by v8::internal::DateParser::Parse(), and v8::internal::DateParser::ParseES5DateTime().
IsNumber()
bool v8::internal::DateParser::DateToken::IsNumber () [inline]
Definition at line 143 of file dateparser.h.
{ return tag_ == kNumberTag; }
References kNumberTag, and tag_.
Referenced by IsFixedLengthNumber(), number(), v8::internal::DateParser::Parse(), and v8::internal::DateParser::ParseES5DateTime().
IsSymbol() [1/2]
bool v8::internal::DateParser::DateToken::IsSymbol () [inline]
Definition at line 144 of file dateparser.h.
{ return tag_ == kSymbolTag; }
References kSymbolTag, and tag_.
Referenced by IsSymbol(), v8::internal::DateParser::Parse(), v8::internal::DateParser::ParseES5DateTime(), v8::internal::DateParser::DateStringTokenizer< Char >::SkipSymbol(), and symbol().
IsSymbol() [2/2]
bool v8::internal::DateParser::DateToken::IsSymbol (char symbol) [inline]
Definition at line 167 of file dateparser.h.
                               {
      return IsSymbol() && this->symbol() == symbol;
    }
References IsSymbol(), and symbol().
IsUnknown() [1/2]
bool v8::internal::DateParser::DateToken::IsUnknown () [inline]
Definition at line 142 of file dateparser.h.
{ return tag_ == kUnknownTokenTag; }
References kUnknownTokenTag, and tag_.
IsUnknown() [2/2]
bool v8::internal::DateParser::DateToken::IsUnknown (int character) [inline]
Definition at line 184 of file dateparser.h.
{ return IsUnknown() && value_ == character; }
References v8::internal::character, IsUnknown(), and value_.
Referenced by IsUnknown().
IsWhiteSpace()
bool v8::internal::DateParser::DateToken::IsWhiteSpace () [inline]
Definition at line 145 of file dateparser.h.
{ return tag_ == kWhiteSpaceTag; }
References kWhiteSpaceTag, and tag_.
Referenced by v8::internal::DateParser::Parse().
Keyword()
static DateToken v8::internal::DateParser::DateToken::Keyword (KeywordType tag, int value, int length) [inline], [static]
Definition at line 186 of file dateparser.h.
                                                                     {
      return DateToken(tag, length, value);
    }
References DateToken(), length(), and v8::internal::value.
keyword_type()
KeywordType v8::internal::DateParser::DateToken::keyword_type () [inline]
Definition at line 155 of file dateparser.h.
                               {
      DCHECK(IsKeyword());
      return static_cast<KeywordType>(tag_);
    }
References v8::internal::DCHECK(), IsKeyword(), and tag_.
keyword_value()
int v8::internal::DateParser::DateToken::keyword_value () [inline]
Definition at line 159 of file dateparser.h.
                        {
      DCHECK(IsKeyword());
      return value_;
    }
References v8::internal::DCHECK(), IsKeyword(), and value_.
length()
int v8::internal::DateParser::DateToken::length () [inline]
Definition at line 149 of file dateparser.h.
{ return length_; }
References length_.
Referenced by IsFixedLengthNumber(), Keyword(), Number(), v8::internal::DateParser::Parse(), v8::internal::DateParser::ReadMilliseconds(), and WhiteSpace().
number()
int v8::internal::DateParser::DateToken::number () [inline]
Definition at line 151 of file dateparser.h.
                 {
      DCHECK(IsNumber());
      return value_;
    }
References v8::internal::DCHECK(), IsNumber(), and value_.
Referenced by v8::internal::DateParser::Parse(), v8::internal::DateParser::ParseES5DateTime(), and v8::internal::DateParser::ReadMilliseconds().
Number()
static DateToken v8::internal::DateParser::DateToken::Number (int value, int length) [inline], [static]
Definition at line 189 of file dateparser.h.
                                                   {
      return DateToken(kNumberTag, length, value);
    }
References DateToken(), kNumberTag, length(), and v8::internal::value.
symbol()
char v8::internal::DateParser::DateToken::symbol () [inline]
Definition at line 163 of file dateparser.h.
                  {
      DCHECK(IsSymbol());
      return static_cast<char>(value_);
    }
References v8::internal::DCHECK(), IsSymbol(), and value_.
Referenced by IsSymbol(), v8::internal::DateParser::ParseES5DateTime(), and Symbol().
Symbol()
static DateToken v8::internal::DateParser::DateToken::Symbol (char symbol) [inline], [static]
Definition at line 192 of file dateparser.h.
                                         {
      return DateToken(kSymbolTag, 1, symbol);
    }
References DateToken(), kSymbolTag, and symbol().
Unknown()
static DateToken v8::internal::DateParser::DateToken::Unknown () [inline], [static]
Definition at line 199 of file dateparser.h.
{ return DateToken(kUnknownTokenTag, 1, -1); }
References DateToken(), and kUnknownTokenTag.
WhiteSpace()
static DateToken v8::internal::DateParser::DateToken::WhiteSpace (int length) [inline], [static]
Definition at line 196 of file dateparser.h.
                                            {
      return DateToken(kWhiteSpaceTag, length, -1);
    }
References DateToken(), kWhiteSpaceTag, and length().
Member Data Documentation
length_
int v8::internal::DateParser::DateToken::length_ [private]
Definition at line 216 of file dateparser.h.
Referenced by IsFixedLengthNumber(), IsKeywordZ(), and length().
tag_
int v8::internal::DateParser::DateToken::tag_ [private]
Definition at line 215 of file dateparser.h.
Referenced by IsAsciiSign(), IsEndOfInput(), IsInvalid(), IsKeyword(), IsKeywordType(), IsNumber(), IsSymbol(), IsUnknown(), IsWhiteSpace(), and keyword_type().
value_
int v8::internal::DateParser::DateToken::value_ [private]
Definition at line 217 of file dateparser.h.
Referenced by ascii_sign(), IsAsciiSign(), IsKeywordZ(), IsUnknown(), keyword_value(), number(), and symbol().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/date/dateparser.h