v8::internal::ProfileNode::Hasher Struct Reference
Public Member Functions
std::size_t operator() (CodeEntryAndPosition pair) const
Detailed Description
Definition at line 346 of file profile-generator.h.
Member Function Documentation
operator()()
std::size_t v8::internal::ProfileNode::Hasher::operator() (CodeEntryAndPosition pair) const [inline]
Definition at line 347 of file profile-generator.h.
                                                          {
      base::Hasher hasher(pair.code_entry->GetHash());
      hasher.Add(pair.line_and_column.line);
      hasher.Add(pair.line_and_column.column);
      return hasher.hash();
    }
References v8::base::Hasher::Add(), v8::internal::CodeEntryAndPosition::code_entry, v8::internal::LineAndColumn::column, v8::internal::CodeEntry::GetHash(), v8::base::Hasher::hash(), v8::internal::LineAndColumn::line, and v8::internal::CodeEntryAndPosition::line_and_column.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/profiler/profile-generator.h