v8::internal::compiler::turboshaft::OpEffects Struct Reference
#include <operations.h>
Public Types
using Bits = uint32_t
Public Member Functions
constexpr OpEffects ()
Bits bits () const
bool operator== (OpEffects other) const
bool operator!= (OpEffects other) const
OpEffects operator| (OpEffects other) const
OpEffects operator& (OpEffects other) const
bool IsSubsetOf (OpEffects other) const
constexpr OpEffects AssumesConsistentHeap () const
constexpr OpEffects CanAllocateWithoutIdentity () const
constexpr OpEffects CanAllocate () const
constexpr OpEffects CanDoRawHeapAccess () const
constexpr OpEffects CanReadHeapMemory () const
constexpr OpEffects CanReadOffHeapMemory () const
constexpr OpEffects CanWriteOffHeapMemory () const
constexpr OpEffects CanWriteHeapMemory () const
constexpr OpEffects CanWriteMemory () const
constexpr OpEffects CanReadMemory () const
constexpr OpEffects CanReadImmutableMemory () const
constexpr OpEffects CanDependOnChecks () const
constexpr OpEffects CanChangeControlFlow () const
constexpr OpEffects CanLeaveCurrentFunction () const
constexpr OpEffects CanDeopt () const
constexpr OpEffects CanCreateIdentity () const
constexpr OpEffects CanCallAnything () const
constexpr OpEffects RequiredWhenUnused () const
constexpr bool is_required_when_unused () const
bool hoistable_before_a_branch () const
bool can_read_mutable_memory () const
bool requires_consistent_heap () const
bool can_write () const
bool can_be_constant_folded () const
Static Public Member Functions
static OpEffects FromBits (Bits bits)
Public Attributes
EffectDimensions produces
EffectDimensions consumes
bool can_create_identity: 1
bool can_allocate: 1
bool required_when_unused: 1
uint8_t unused_padding_1: 5
uint8_t unused_padding_2
Detailed Description
Definition at line 620 of file operations.h.
Member Typedef Documentation
Bits
using v8::internal::compiler::turboshaft::OpEffects::Bits = uint32_t
Definition at line 650 of file operations.h.
Constructor & Destructor Documentation
OpEffects()
constexpr v8::internal::compiler::turboshaft::OpEffects::OpEffects () [inline], [constexpr]
Definition at line 643 of file operations.h.
      : can_create_identity(false),
        can_allocate(false),
        required_when_unused(false),
        unused_padding_1(0),
        unused_padding_2(0) {}
Member Function Documentation
AssumesConsistentHeap()
constexpr OpEffects v8::internal::compiler::turboshaft::OpEffects::AssumesConsistentHeap () const [inline], [constexpr]
Definition at line 668 of file operations.h.
                                                    {
    OpEffects result = *this;
    // Do not move the operation into a region with raw heap access.
    result.produces.before_raw_heap_access = true;
    result.consumes.after_raw_heap_access = true;
    return result;
  }
References v8::base::internal::result.
bits()
Bits v8::internal::compiler::turboshaft::OpEffects::bits () const [inline]
Definition at line 651 of file operations.h.
{ return base::bit_cast<Bits>(*this); }
Referenced by v8::internal::compiler::turboshaft::hash_value(), IsSubsetOf(), operator!=(), operator&(), operator==(), and operator|().
can_be_constant_folded()
bool v8::internal::compiler::turboshaft::OpEffects::can_be_constant_folded () const [inline]
Definition at line 832 of file operations.h.
                                      {
    // Operations that CanDependOnChecks can still be constant-folded. If they
    // did indeed depend on a check, then their result will only be used after
    // said check has been executed anyways.
    return IsSubsetOf(OpEffects().CanDependOnChecks());
  }
Referenced by v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::CanBeConstantFolded().
can_read_mutable_memory()
bool v8::internal::compiler::turboshaft::OpEffects::can_read_mutable_memory () const [inline]
Definition at line 823 of file operations.h.
                                       {
    return produces.load_heap_memory | produces.load_off_heap_memory;
  }
References v8::internal::compiler::turboshaft::EffectDimensions::load_heap_memory, and v8::internal::compiler::turboshaft::EffectDimensions::load_off_heap_memory.
Referenced by v8::internal::compiler::turboshaft::RedundantStoreAnalysis::ProcessBlock().
can_write()
bool v8::internal::compiler::turboshaft::OpEffects::can_write () const [inline]
Definition at line 829 of file operations.h.
                         {
    return produces.store_heap_memory | produces.store_off_heap_memory;
  }
References v8::internal::compiler::turboshaft::EffectDimensions::store_heap_memory, and v8::internal::compiler::turboshaft::EffectDimensions::store_off_heap_memory.
Referenced by v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessBlock(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessBlock(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessCall(), and v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessCall().
CanAllocate()
constexpr OpEffects v8::internal::compiler::turboshaft::OpEffects::CanAllocate () const [inline], [constexpr]
Definition at line 686 of file operations.h.
                                          {
    return CanAllocateWithoutIdentity().CanCreateIdentity();
  }
References CanCreateIdentity().
Referenced by CanCallAnything(), v8::internal::compiler::turboshaft::JSStackCheckOp::Effects(), and v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
CanAllocateWithoutIdentity()
constexpr OpEffects v8::internal::compiler::turboshaft::OpEffects::CanAllocateWithoutIdentity () const [inline], [constexpr]
Definition at line 679 of file operations.h.
                                                         {
    OpEffects result = AssumesConsistentHeap();
    result.can_allocate = true;
    return result;
  }
References v8::base::internal::result.
CanCallAnything()
constexpr OpEffects v8::internal::compiler::turboshaft::OpEffects::CanCallAnything () const [inline], [constexpr]
Definition at line 798 of file operations.h.
                                              {
    return CanReadMemory()
        .CanWriteMemory()
        .CanAllocate()
        .CanChangeControlFlow()
        .CanDependOnChecks()
        .RequiredWhenUnused();
  }
References CanAllocate(), CanChangeControlFlow(), CanDependOnChecks(), CanWriteMemory(), and RequiredWhenUnused().
Referenced by v8::internal::compiler::turboshaft::JSStackCheckOp::Effects().
CanChangeControlFlow()
constexpr OpEffects v8::internal::compiler::turboshaft::OpEffects::CanChangeControlFlow () const [inline], [constexpr]
Definition at line 767 of file operations.h.
                                                   {
    OpEffects result = *this;
    result.required_when_unused = true;
    // Signal that this changes control flow. Prevents stores or operations
    // relying on checks from flowing before this operation.
    result.produces.control_flow = true;
    // Stores must not flow past something that affects control flow.
    result.consumes.store_heap_memory = true;
    result.consumes.store_off_heap_memory = true;
    return result;
  }
References v8::base::internal::result.
Referenced by CanCallAnything(), and v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
CanCreateIdentity()
constexpr OpEffects v8::internal::compiler::turboshaft::OpEffects::CanCreateIdentity () const [inline], [constexpr]
Definition at line 792 of file operations.h.
                                                {
    OpEffects result = *this;
    result.can_create_identity = true;
    return result;
  }
References v8::base::internal::result.
Referenced by CanAllocate(), and v8::internal::compiler::turboshaft::GrowableStacksReducer< Next >::WasmStackCheck().
CanDeopt()
constexpr OpEffects v8::internal::compiler::turboshaft::OpEffects::CanDeopt () const [inline], [constexpr]
Definition at line 785 of file operations.h.
                                       {
    return CanLeaveCurrentFunction()
        // We might depend on previous checks to avoid deopting.
        .CanDependOnChecks();
  }
References CanDependOnChecks().
Referenced by v8::internal::compiler::turboshaft::JSStackCheckOp::Effects(), and v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
CanDependOnChecks()
constexpr OpEffects v8::internal::compiler::turboshaft::OpEffects::CanDependOnChecks () const [inline], [constexpr]
Definition at line 761 of file operations.h.
                                                {
    OpEffects result = *this;
    result.consumes.control_flow = true;
    return result;
  }
References v8::base::internal::result.
Referenced by CanCallAnything(), CanDeopt(), v8::internal::compiler::turboshaft::LoadOp::Effects(), v8::internal::compiler::turboshaft::AtomicRMWOp::Effects(), v8::internal::compiler::turboshaft::AtomicWord32PairOp::Effects(), v8::internal::compiler::turboshaft::StoreOp::Effects(), v8::internal::compiler::turboshaft::JSStackCheckOp::Effects(), and v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
CanDoRawHeapAccess()
constexpr OpEffects v8::internal::compiler::turboshaft::OpEffects::CanDoRawHeapAccess () const [inline], [constexpr]
Definition at line 691 of file operations.h.
                                                 {
    OpEffects result = *this;
    // Do not move any operation that relies on a consistent heap state accross.
    result.produces.after_raw_heap_access = true;
    result.consumes.before_raw_heap_access = true;
    return result;
  }
References v8::base::internal::result.
Referenced by v8::internal::compiler::turboshaft::TaggedBitcastOp::Effects(), and v8::internal::compiler::turboshaft::StoreOp::Effects().
CanLeaveCurrentFunction()
constexpr OpEffects v8::internal::compiler::turboshaft::OpEffects::CanLeaveCurrentFunction () const [inline], [constexpr]
Definition at line 780 of file operations.h.
                                                      {
    // All memory becomes observable.
    return CanChangeControlFlow().CanReadMemory().RequiredWhenUnused();
  }
References CanReadMemory(), and RequiredWhenUnused().
Referenced by v8::internal::compiler::turboshaft::LoadOp::Effects(), v8::internal::compiler::turboshaft::AtomicRMWOp::Effects(), and v8::internal::compiler::turboshaft::StoreOp::Effects().
CanReadHeapMemory()
constexpr OpEffects v8::internal::compiler::turboshaft::OpEffects::CanReadHeapMemory () const [inline], [constexpr]
Definition at line 699 of file operations.h.
                                                {
    OpEffects result = *this;
    result.produces.load_heap_memory = true;
    // Do not reorder before stores.
    result.consumes.store_heap_memory = true;
    return result;
  }
References v8::base::internal::result.
Referenced by v8::internal::compiler::turboshaft::JSStackCheckOp::Effects().
CanReadImmutableMemory()
constexpr OpEffects v8::internal::compiler::turboshaft::OpEffects::CanReadImmutableMemory () const [inline], [constexpr]
Definition at line 754 of file operations.h.
                                                     {
    OpEffects result = AssumesConsistentHeap();
    return result;
  }
References v8::base::internal::result.
CanReadMemory()
constexpr OpEffects v8::internal::compiler::turboshaft::OpEffects::CanReadMemory () const [inline], [constexpr]
Definition at line 747 of file operations.h.
                                            {
    return CanReadHeapMemory().CanReadOffHeapMemory();
  }
References CanReadOffHeapMemory().
Referenced by CanLeaveCurrentFunction(), v8::internal::compiler::turboshaft::LoadOp::Effects(), v8::internal::compiler::turboshaft::AtomicRMWOp::Effects(), v8::internal::compiler::turboshaft::AtomicWord32PairOp::Effects(), v8::internal::compiler::turboshaft::StoreOp::Effects(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), and v8::internal::compiler::turboshaft::GrowableStacksReducer< Next >::WasmStackCheck().
CanReadOffHeapMemory()
constexpr OpEffects v8::internal::compiler::turboshaft::OpEffects::CanReadOffHeapMemory () const [inline], [constexpr]
Definition at line 708 of file operations.h.
                                                   {
    OpEffects result = *this;
    result.produces.load_off_heap_memory = true;
    // Do not reorder before stores.
    result.consumes.store_off_heap_memory = true;
    return result;
  }
References v8::base::internal::result.
Referenced by CanReadMemory().
CanWriteHeapMemory()
constexpr OpEffects v8::internal::compiler::turboshaft::OpEffects::CanWriteHeapMemory () const [inline], [constexpr]
Definition at line 730 of file operations.h.
                                                 {
    OpEffects result = *this;
    result.required_when_unused = true;
    result.produces.store_heap_memory = true;
    // Do not reorder before stores.
    result.consumes.store_heap_memory = true;
    // Do not reorder before loads.
    result.consumes.load_heap_memory = true;
    // Do not move before deopting or aborting operations.
    result.consumes.control_flow = true;
    return result;
  }
References v8::base::internal::result.
CanWriteMemory()
constexpr OpEffects v8::internal::compiler::turboshaft::OpEffects::CanWriteMemory () const [inline], [constexpr]
Definition at line 743 of file operations.h.
                                             {
    return CanWriteHeapMemory().CanWriteOffHeapMemory();
  }
References CanWriteOffHeapMemory().
Referenced by CanCallAnything(), v8::internal::compiler::turboshaft::LoadOp::Effects(), v8::internal::compiler::turboshaft::AtomicRMWOp::Effects(), v8::internal::compiler::turboshaft::AtomicWord32PairOp::Effects(), v8::internal::compiler::turboshaft::StoreOp::Effects(), and v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
CanWriteOffHeapMemory()
constexpr OpEffects v8::internal::compiler::turboshaft::OpEffects::CanWriteOffHeapMemory () const [inline], [constexpr]
Definition at line 716 of file operations.h.
                                                    {
    OpEffects result = *this;
    result.required_when_unused = true;
    result.produces.store_off_heap_memory = true;
    // Do not reorder before stores.
    result.consumes.store_off_heap_memory = true;
    // Do not reorder before loads.
    result.consumes.load_off_heap_memory = true;
    // Do not move before deopting or aborting operations.
    result.consumes.control_flow = true;
    return result;
  }
References v8::base::internal::result.
Referenced by CanWriteMemory().
FromBits()
static OpEffects v8::internal::compiler::turboshaft::OpEffects::FromBits (Bits bits) [inline], [static]
Definition at line 652 of file operations.h.
                                       {
    return base::bit_cast<OpEffects>(bits);
  }
hoistable_before_a_branch()
bool v8::internal::compiler::turboshaft::OpEffects::hoistable_before_a_branch () const [inline]
Definition at line 818 of file operations.h.
                                         {
    // Since this excludes `CanDependOnChecks()`, most loads actually cannot be
    // hoisted.
    return IsSubsetOf(OpEffects().CanReadMemory());
  }
is_required_when_unused()
constexpr bool v8::internal::compiler::turboshaft::OpEffects::is_required_when_unused () const [inline], [constexpr]
Definition at line 814 of file operations.h.
                                                 {
    return required_when_unused;
  }
IsSubsetOf()
bool v8::internal::compiler::turboshaft::OpEffects::IsSubsetOf (OpEffects other) const [inline]
Definition at line 664 of file operations.h.
                                         {
    return (bits() & ~other.bits()) == 0;
  }
References bits().
Referenced by v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::CanGVN().
operator!=()
bool v8::internal::compiler::turboshaft::OpEffects::operator!= (OpEffects other) const [inline]
Definition at line 657 of file operations.h.
{ return bits() != other.bits(); }
References bits().
operator&()
OpEffects v8::internal::compiler::turboshaft::OpEffects::operator& (OpEffects other) const [inline]
Definition at line 661 of file operations.h.
                                             {
    return FromBits(bits() & other.bits());
  }
References bits().
operator==()
bool v8::internal::compiler::turboshaft::OpEffects::operator== (OpEffects other) const [inline]
Definition at line 656 of file operations.h.
{ return bits() == other.bits(); }
References bits().
operator|()
OpEffects v8::internal::compiler::turboshaft::OpEffects::operator| (OpEffects other) const [inline]
Definition at line 658 of file operations.h.
                                             {
    return FromBits(bits() | other.bits());
  }
References bits().
RequiredWhenUnused()
constexpr OpEffects v8::internal::compiler::turboshaft::OpEffects::RequiredWhenUnused () const [inline], [constexpr]
Definition at line 806 of file operations.h.
                                                 {
    OpEffects result = *this;
    result.required_when_unused = true;
    return result;
  }
References v8::base::internal::result.
Referenced by CanCallAnything(), CanLeaveCurrentFunction(), and v8::internal::compiler::turboshaft::GrowableStacksReducer< Next >::WasmStackCheck().
requires_consistent_heap()
bool v8::internal::compiler::turboshaft::OpEffects::requires_consistent_heap () const [inline]
Definition at line 826 of file operations.h.
                                        {
    return produces.before_raw_heap_access | consumes.after_raw_heap_access;
  }
References v8::internal::compiler::turboshaft::EffectDimensions::after_raw_heap_access, and v8::internal::compiler::turboshaft::EffectDimensions::before_raw_heap_access.
Referenced by v8::internal::compiler::turboshaft::RedundantStoreAnalysis::ProcessBlock().
Member Data Documentation
can_allocate
bool v8::internal::compiler::turboshaft::OpEffects::can_allocate
Definition at line 633 of file operations.h.
Referenced by v8::internal::compiler::turboshaft::operator<<(), v8::internal::compiler::turboshaft::MemoryAnalyzer::Process(), and v8::internal::compiler::turboshaft::CallOp::Validate().
can_create_identity
bool v8::internal::compiler::turboshaft::OpEffects::can_create_identity
Definition at line 631 of file operations.h.
Referenced by v8::internal::compiler::turboshaft::operator<<().
consumes
EffectDimensions v8::internal::compiler::turboshaft::OpEffects::consumes
Definition at line 622 of file operations.h.
Referenced by v8::internal::compiler::turboshaft::CannotSwapOperations(), v8::internal::compiler::turboshaft::CannotSwapProtectedLoads(), v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::increment_effect_level_for_node(), and v8::internal::compiler::turboshaft::operator<<().
produces
EffectDimensions v8::internal::compiler::turboshaft::OpEffects::produces
Definition at line 621 of file operations.h.
Referenced by v8::internal::compiler::InstructionSelector::CanCover(), v8::internal::compiler::InstructionSelector::CanCoverProtectedLoad(), v8::internal::compiler::turboshaft::CannotSwapOperations(), v8::internal::compiler::turboshaft::CannotSwapProtectedLoads(), and v8::internal::compiler::turboshaft::operator<<().
required_when_unused
bool v8::internal::compiler::turboshaft::OpEffects::required_when_unused
Definition at line 636 of file operations.h.
Referenced by v8::internal::compiler::InstructionSelector::CanCoverProtectedLoad().
unused_padding_1
uint8_t v8::internal::compiler::turboshaft::OpEffects::unused_padding_1
Definition at line 640 of file operations.h.
unused_padding_2
uint8_t v8::internal::compiler::turboshaft::OpEffects::unused_padding_2
Definition at line 641 of file operations.h.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h