v8::internal::interpreter::anonymous_namespace{bytecode-generator.cc}::SwitchInfo Struct Reference
Public Member Functions
SwitchInfo ()
bool DefaultExists ()
bool CaseExists (int j)
bool CaseExists (Expression *expr)
CaseClause * GetClause (int j)
bool IsDuplicate (CaseClause *clause)
int MinCase ()
int MaxCase ()
void Print ()
Public Attributes
std::map< int, CaseClause * > covered_cases
int default_case
Static Public Attributes
static const int kDefaultNotFound = -1
Detailed Description
Definition at line 2400 of file bytecode-generator.cc.
Constructor & Destructor Documentation
SwitchInfo()
v8::internal::interpreter::anonymous_namespace{bytecode-generator.cc}::SwitchInfo::SwitchInfo () [inline]
Definition at line 2406 of file bytecode-generator.cc.
{ default_case = kDefaultNotFound; }
Member Function Documentation
CaseExists() [1/2]
bool v8::internal::interpreter::anonymous_namespace{bytecode-generator.cc}::SwitchInfo::CaseExists (Expression * expr) [inline]
Definition at line 2412 of file bytecode-generator.cc.
                                    {
    return IsSmiLiteralSwitchCaseValue(expr)
               ? CaseExists(ReduceToSmiSwitchCaseValue(expr))
               : false;
  }
References v8::internal::interpreter::anonymous_namespace{bytecode-generator.cc}::IsSmiLiteralSwitchCaseValue(), and v8::internal::interpreter::anonymous_namespace{bytecode-generator.cc}::ReduceToSmiSwitchCaseValue().
CaseExists() [2/2]
bool v8::internal::interpreter::anonymous_namespace{bytecode-generator.cc}::SwitchInfo::CaseExists (int j) [inline]
Definition at line 2409 of file bytecode-generator.cc.
                         {
    return covered_cases.find(j) != covered_cases.end();
  }
DefaultExists()
bool v8::internal::interpreter::anonymous_namespace{bytecode-generator.cc}::SwitchInfo::DefaultExists () [inline]
Definition at line 2408 of file bytecode-generator.cc.
{ return default_case != kDefaultNotFound; }
GetClause()
CaseClause* v8::internal::interpreter::anonymous_namespace{bytecode-generator.cc}::SwitchInfo::GetClause (int j) [inline]
Definition at line 2417 of file bytecode-generator.cc.
{ return covered_cases[j]; }
IsDuplicate()
bool v8::internal::interpreter::anonymous_namespace{bytecode-generator.cc}::SwitchInfo::IsDuplicate (CaseClause * clause) [inline]
Definition at line 2419 of file bytecode-generator.cc.
                                       {
    return IsSmiLiteralSwitchCaseValue(clause->label()) &&
           CaseExists(clause->label()) &&
           clause != GetClause(ReduceToSmiSwitchCaseValue(clause->label()));
  }
References v8::internal::interpreter::anonymous_namespace{bytecode-generator.cc}::IsSmiLiteralSwitchCaseValue(), v8::internal::CaseClause::label(), and v8::internal::interpreter::anonymous_namespace{bytecode-generator.cc}::ReduceToSmiSwitchCaseValue().
MaxCase()
int v8::internal::interpreter::anonymous_namespace{bytecode-generator.cc}::SwitchInfo::MaxCase () [inline]
Definition at line 2427 of file bytecode-generator.cc.
                {
    return covered_cases.empty() ? INT_MIN : covered_cases.rbegin()->first;
  }
Referenced by v8::internal::interpreter::anonymous_namespace{bytecode-generator.cc}::IsSwitchOptimizable().
MinCase()
int v8::internal::interpreter::anonymous_namespace{bytecode-generator.cc}::SwitchInfo::MinCase () [inline]
Definition at line 2424 of file bytecode-generator.cc.
                {
    return covered_cases.empty() ? INT_MAX : covered_cases.begin()->first;
  }
Referenced by v8::internal::interpreter::anonymous_namespace{bytecode-generator.cc}::IsSwitchOptimizable().
Print()
void v8::internal::interpreter::anonymous_namespace{bytecode-generator.cc}::SwitchInfo::Print () [inline]
Definition at line 2430 of file bytecode-generator.cc.
               {
    std::cout << "Covered_cases: " << '\n';
    for (auto iter = covered_cases.begin(); iter != covered_cases.end();
         ++iter) {
      std::cout << iter->first << "->" << iter->second << '\n';
    }
    std::cout << "Default_case: " << default_case << '\n';
  }
Member Data Documentation
covered_cases
std::map<int, CaseClause*> v8::internal::interpreter::anonymous_namespace{bytecode-generator.cc}::SwitchInfo::covered_cases
Definition at line 2403 of file bytecode-generator.cc.
Referenced by v8::internal::interpreter::anonymous_namespace{bytecode-generator.cc}::IsSwitchOptimizable().
default_case
int v8::internal::interpreter::anonymous_namespace{bytecode-generator.cc}::SwitchInfo::default_case
Definition at line 2404 of file bytecode-generator.cc.
kDefaultNotFound
const int v8::internal::interpreter::anonymous_namespace{bytecode-generator.cc}::SwitchInfo::kDefaultNotFound = -1 [static]
Definition at line 2401 of file bytecode-generator.cc.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/interpreter/bytecode-generator.cc