v8::internal::compiler::NodeMatcher Struct Reference
#include <node-matchers.h>
Public Member Functions
NodeMatcher (Node *node)
Node * node () const
const Operator * op () const
IrOpcode::Value opcode () const
bool HasProperty (Operator::Property property) const
Node * InputAt (int index) const
bool Equals (const Node *node) const
bool IsComparison () const
Private Attributes
Node * node_
Detailed Description
Definition at line 28 of file node-matchers.h.
Constructor & Destructor Documentation
NodeMatcher()
v8::internal::compiler::NodeMatcher::NodeMatcher (Node * node) [inline], [explicit]
Definition at line 29 of file node-matchers.h.
: node_(node) {}
Member Function Documentation
Equals()
bool v8::internal::compiler::NodeMatcher::Equals (const Node * node) const [inline]
Definition at line 40 of file node-matchers.h.
{ return node_ == node; }
References node(), and node_.
HasProperty()
bool v8::internal::compiler::NodeMatcher::HasProperty (Operator::Property property) const [inline]
Definition at line 35 of file node-matchers.h.
                                                    {
    return op()->HasProperty(property);
  }
References v8::internal::compiler::Operator::HasProperty(), and op().
Referenced by v8::internal::compiler::BinopMatcher< Left, Right, rep >::BinopMatcher().
InputAt()
Node* v8::internal::compiler::NodeMatcher::InputAt (int index) const [inline]
Definition at line 38 of file node-matchers.h.
{ return node()->InputAt(index); }
References v8::internal::index, v8::internal::compiler::Node::InputAt(), and node().
Referenced by v8::internal::compiler::SimplifiedOperatorReducer::Reduce(), and v8::internal::compiler::MachineOperatorReducer::Reduce().
IsComparison()
bool v8::internal::compiler::NodeMatcher::IsComparison () const
Definition at line 11 of file node-matchers.cc.
                                     {
  return IrOpcode::IsComparisonOpcode(opcode());
}
References v8::internal::compiler::IrOpcode::IsComparisonOpcode(), and opcode().
node()
Node* v8::internal::compiler::NodeMatcher::node () const [inline]
Definition at line 31 of file node-matchers.h.
{ return node_; }
References node_.
Referenced by v8::internal::compiler::AddMatcher< BinopMatcher, AddOpcode, SubOpcode, kMulOpcode, kShiftOpcode >::AddMatcher(), v8::internal::compiler::JSInliningHeuristic::CollectFunctions(), v8::internal::compiler::JSInliner::DetermineCallContext(), Equals(), v8::internal::compiler::AddMatcher< BinopMatcher, AddOpcode, SubOpcode, kMulOpcode, kShiftOpcode >::Initialize(), InputAt(), op(), opcode(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::OwnsInput(), v8::internal::compiler::SimplifiedOperatorReducer::Reduce(), v8::internal::compiler::MachineOperatorReducer::Reduce(), v8::internal::compiler::MachineOperatorReducer::ReduceConditional(), v8::internal::compiler::MachineOperatorReducer::ReduceConditionalN(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeSlice(), v8::internal::compiler::JSIntrinsicLowering::ReduceToString(), v8::internal::compiler::MachineOperatorReducer::ReduceTruncateInt64ToInt32(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ShouldUseCallICFeedback(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::SwapInputs(), and v8::internal::compiler::ValueMatcher< T, kOpcode >::ValueMatcher().
op()
const Operator* v8::internal::compiler::NodeMatcher::op () const [inline]
Definition at line 32 of file node-matchers.h.
{ return node()->op(); }
References node(), and v8::internal::compiler::Node::op().
Referenced by v8::internal::compiler::JSInliningHeuristic::CollectFunctions(), v8::internal::compiler::JSInliner::DetermineCallContext(), v8::internal::compiler::JSInliner::DetermineCallTarget(), HasProperty(), v8::internal::compiler::MachineOperatorReducer::ReduceWord32Shl(), and v8::internal::compiler::MachineOperatorReducer::ReduceWord64Shl().
opcode()
IrOpcode::Value v8::internal::compiler::NodeMatcher::opcode () const [inline]
Definition at line 33 of file node-matchers.h.
{ return node()->opcode(); }
References node(), and v8::internal::compiler::Node::opcode().
Referenced by v8::internal::compiler::AddMatcher< BinopMatcher, AddOpcode, SubOpcode, kMulOpcode, kShiftOpcode >::Initialize(), and IsComparison().
Member Data Documentation
node_
Node* v8::internal::compiler::NodeMatcher::node_ [private]
Definition at line 50 of file node-matchers.h.
Referenced by Equals(), and node().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/compiler/node-matchers.h
/mnt/V8SourceCode/src/compiler/node-matchers.cc