v8::internal::compiler::turboshaft::BuildGraphPhase Struct Reference
#include <build-graph-phase.h>
Public Member Functions
std::optional< BailoutReason > Run (PipelineData *data, Zone *temp_zone, compiler::TFPipelineData *turbofan_data, Linkage *linkage)
Detailed Description
Definition at line 20 of file build-graph-phase.h.
Member Function Documentation
Run()
std::optional< BailoutReason > v8::internal::compiler::turboshaft::BuildGraphPhase::Run (PipelineData * data, Zone * temp_zone, compiler::TFPipelineData * turbofan_data, Linkage * linkage)
Definition at line 18 of file build-graph-phase.cc.
                                                             {
  Schedule* schedule = turbofan_data->schedule();
  turbofan_data->reset_schedule();
  DCHECK_NOT_NULL(schedule);
  JsWasmCallsSidetable* js_wasm_calls_sidetable =
#if V8_ENABLE_WEBASSEMBLY
      turbofan_data->js_wasm_calls_sidetable();
#else
      nullptr;
#endif // V8_ENABLE_WEBASSEMBLY
  UnparkedScopeIfNeeded scope(data->broker());
  // Construct a new graph.
  ZoneWithNamePointer<SourcePositionTable, kGraphZoneName> source_positions(
      turbofan_data->source_positions());
  ZoneWithNamePointer<NodeOriginTable, kGraphZoneName> node_origins(
      turbofan_data->node_origins());
  data->InitializeGraphComponentWithGraphZone(turbofan_data->ReleaseGraphZone(),
                                              source_positions, node_origins);
  if (auto bailout = turboshaft::BuildGraph(data, schedule, temp_zone, linkage,
                                            js_wasm_calls_sidetable)) {
    return bailout;
  }
  return {};
}
References v8::internal::compiler::turboshaft::PipelineData::broker(), v8::internal::compiler::turboshaft::BuildGraph(), DCHECK_NOT_NULL, v8::internal::compiler::turboshaft::PipelineData::InitializeGraphComponentWithGraphZone(), v8::internal::compiler::TFPipelineData::node_origins(), v8::internal::compiler::TFPipelineData::ReleaseGraphZone(), v8::internal::compiler::TFPipelineData::reset_schedule(), v8::internal::compiler::TFPipelineData::schedule(), and v8::internal::compiler::TFPipelineData::source_positions().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/build-graph-phase.h
/mnt/V8SourceCode/src/compiler/turboshaft/build-graph-phase.cc