v8::internal::baseline::detail::PushHelper< Arg > Struct Template Reference
#include <baseline-assembler-ia32-inl.h>
Static Public Member Functions
static int Push (BaselineAssembler *basm, Arg arg)
static int PushReverse (BaselineAssembler *basm, Arg arg)
static int Push (BaselineAssembler *basm, Arg arg)
static int PushReverse (BaselineAssembler *basm, Arg arg)
Detailed Description
template<typename Arg>
struct v8::internal::baseline::detail::PushHelper< Arg >
Definition at line 247 of file baseline-assembler-ia32-inl.h.
Member Function Documentation
Push() [1/2]
template<typename Arg >
static int v8::internal::baseline::detail::PushHelper< Arg >::Push (BaselineAssembler * basm, Arg arg) [inline], [static]
Definition at line 248 of file baseline-assembler-ia32-inl.h.
                                                    {
    PushSingle(basm->masm(), arg);
    return 1;
  }
References v8::internal::baseline::BaselineAssembler::masm(), and v8::internal::baseline::detail::PushSingle().
Referenced by v8::internal::baseline::detail::PushAllHelper< Arg, Args... >::Push(), and v8::internal::baseline::detail::PushHelper< Arg >::PushReverse().
Push() [2/2]
template<typename Arg >
static int v8::internal::baseline::detail::PushHelper< Arg >::Push (BaselineAssembler * basm, Arg arg) [inline], [static]
Definition at line 259 of file baseline-assembler-x64-inl.h.
                                                    {
    PushSingle(basm->masm(), arg);
    return 1;
  }
References v8::internal::baseline::BaselineAssembler::masm(), and v8::internal::baseline::detail::PushSingle().
PushReverse() [1/2]
template<typename Arg >
static int v8::internal::baseline::detail::PushHelper< Arg >::PushReverse (BaselineAssembler * basm, Arg arg) [inline], [static]
Definition at line 252 of file baseline-assembler-ia32-inl.h.
                                                           {
    return Push(basm, arg);
  }
References v8::internal::baseline::detail::PushHelper< Arg >::Push().
Referenced by v8::internal::baseline::detail::PushAllHelper< Arg, Args... >::PushReverse().
PushReverse() [2/2]
template<typename Arg >
static int v8::internal::baseline::detail::PushHelper< Arg >::PushReverse (BaselineAssembler * basm, Arg arg) [inline], [static]
Definition at line 263 of file baseline-assembler-x64-inl.h.
                                                           {
    return Push(basm, arg);
  }
References v8::internal::baseline::detail::PushHelper< Arg >::Push().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/baseline/ia32/baseline-assembler-ia32-inl.h
/mnt/V8SourceCode/src/baseline/x64/baseline-assembler-x64-inl.h