v8::internal::wasm::LiftoffAssembler::CacheState Struct Reference
#include <liftoff-assembler.h>
Public Types
enum class SpillLocation { kTopOfStack
, kStackSlots
 }
Public Member Functions
CacheState (Zone *zone)
CacheState (CacheState &&) V8_NOEXCEPT=default
CacheState & operator= (CacheState &&) V8_NOEXCEPT=default
CacheState (const CacheState &)=delete
void GetTaggedSlotsForOOLCode (ZoneVector< int > *slots, LiftoffRegList *spills, SpillLocation spill_location)
void DefineSafepoint (SafepointTableBuilder::Safepoint &safepoint)
void DefineSafepointWithCalleeSavedRegisters (SafepointTableBuilder::Safepoint &safepoint)
bool has_unused_register (RegClass rc, LiftoffRegList pinned={}) const
bool has_unused_register (LiftoffRegList candidates) const
LiftoffRegister unused_register (RegClass rc, LiftoffRegList pinned={}) const
LiftoffRegister unused_register (LiftoffRegList candidates, LiftoffRegList pinned={}) const
bool has_volatile_register (LiftoffRegList candidates)
LiftoffRegister take_volatile_register (LiftoffRegList candidates)
void SetCacheRegister (Register *cache, Register reg)
void SetInstanceCacheRegister (Register reg)
void SetMemStartCacheRegister (Register reg, int memory_index)
Register TrySetCachedInstanceRegister (LiftoffRegList pinned)
void ClearCacheRegister (Register *cache)
void ClearCachedInstanceRegister ()
void ClearCachedMemStartRegister ()
void ClearAllCacheRegisters ()
void inc_used (LiftoffRegister reg)
void dec_used (LiftoffRegister reg)
bool is_used (LiftoffRegister reg) const
uint32_t get_use_count (LiftoffRegister reg) const
void clear_used (LiftoffRegister reg)
bool is_free (LiftoffRegister reg) const
void reset_used_registers ()
LiftoffRegister GetNextSpillReg (LiftoffRegList candidates)
void Steal (CacheState &source)
void Split (const CacheState &source)
uint32_t stack_height () const
Public Attributes
SmallZoneVector< VarState, 16 > stack_state
LiftoffRegList used_registers
uint32_t register_use_count [kAfterMaxLiftoffRegCode] = {0}
LiftoffRegList last_spilled_regs
Register cached_instance_data = no_reg
int cached_mem_index = kNoCachedMemIndex
Register cached_mem_start = no_reg
Static Public Attributes
static constexpr int kNoCachedMemIndex = -1
Private Member Functions
CacheState & operator= (const CacheState &) V8_NOEXCEPT=default
Detailed Description
Definition at line 113 of file liftoff-assembler.h.
Member Enumeration Documentation
SpillLocation
enum v8::internal::wasm::LiftoffAssembler::CacheState::SpillLocation [strong]
Enumerator
kTopOfStack
kStackSlots
Definition at line 122 of file liftoff-assembler.h.
{ kTopOfStack, kStackSlots };
Constructor & Destructor Documentation
CacheState() [1/3]
v8::internal::wasm::LiftoffAssembler::CacheState::CacheState (Zone * zone) [inline], [explicit]
Definition at line 114 of file liftoff-assembler.h.
: stack_state(zone) {}
CacheState() [2/3]
v8::internal::wasm::LiftoffAssembler::CacheState::CacheState (CacheState &&) [default]
CacheState() [3/3]
v8::internal::wasm::LiftoffAssembler::CacheState::CacheState (const CacheState &) [delete]
Member Function Documentation
clear_used()
void v8::internal::wasm::LiftoffAssembler::CacheState::clear_used (LiftoffRegister reg) [inline]
Definition at line 341 of file liftoff-assembler.h.
                                         {
      DCHECK(!frozen);
      if (reg.is_pair()) {
        clear_used(reg.low());
        clear_used(reg.high());
        return;
      }
      register_use_count[reg.liftoff_code()] = 0;
      used_registers.clear(reg);
    }
References v8::internal::wasm::LiftoffRegList::clear(), v8::internal::DCHECK(), v8::internal::wasm::LiftoffRegister::high(), v8::internal::wasm::LiftoffRegister::is_pair(), v8::internal::wasm::LiftoffRegister::liftoff_code(), v8::internal::wasm::LiftoffRegister::low(), register_use_count, and used_registers.
Referenced by v8::internal::wasm::LiftoffAssembler::SpillRegister().
ClearAllCacheRegisters()
void v8::internal::wasm::LiftoffAssembler::CacheState::ClearAllCacheRegisters () [inline]
Definition at line 289 of file liftoff-assembler.h.
                                  {
      ClearCachedInstanceRegister();
      ClearCachedMemStartRegister();
    }
References ClearCachedInstanceRegister(), and ClearCachedMemStartRegister().
Referenced by v8::internal::wasm::LiftoffAssembler::PrepareCall(), and v8::internal::wasm::LiftoffAssembler::SpillAllRegisters().
ClearCachedInstanceRegister()
void v8::internal::wasm::LiftoffAssembler::CacheState::ClearCachedInstanceRegister () [inline]
Definition at line 277 of file liftoff-assembler.h.
                                       {
      ClearCacheRegister(&cached_instance_data);
    }
References cached_instance_data, and ClearCacheRegister().
Referenced by ClearAllCacheRegisters(), v8::internal::wasm::LiftoffAssembler::ClearRegister(), v8::internal::wasm::LiftoffAssembler::MergeFullStackWith(), v8::internal::wasm::LiftoffAssembler::MergeStackWith(), and v8::internal::wasm::LiftoffAssembler::SpillRegisters().
ClearCachedMemStartRegister()
void v8::internal::wasm::LiftoffAssembler::CacheState::ClearCachedMemStartRegister () [inline]
Definition at line 281 of file liftoff-assembler.h.
                                       {
      V8_ASSUME(cached_mem_index == kNoCachedMemIndex || cached_mem_index >= 0);
      if (cached_mem_index == kNoCachedMemIndex) return;
      cached_mem_index = kNoCachedMemIndex;
      DCHECK_NE(no_reg, cached_mem_start);
      ClearCacheRegister(&cached_mem_start);
    }
References cached_mem_index, cached_mem_start, ClearCacheRegister(), DCHECK_NE, kNoCachedMemIndex, v8::internal::no_reg, and V8_ASSUME.
Referenced by ClearAllCacheRegisters(), v8::internal::wasm::LiftoffAssembler::ClearRegister(), v8::internal::wasm::LiftoffAssembler::MergeFullStackWith(), v8::internal::wasm::LiftoffAssembler::MergeStackWith(), and v8::internal::wasm::LiftoffAssembler::SpillRegisters().
ClearCacheRegister()
void v8::internal::wasm::LiftoffAssembler::CacheState::ClearCacheRegister (Register * cache) [inline]
Definition at line 266 of file liftoff-assembler.h.
                                                       {
      DCHECK(!frozen);
      V8_ASSUME(cache == &cached_instance_data || cache == &cached_mem_start);
      if (*cache == no_reg) return;
      int liftoff_code = LiftoffRegister{*cache}.liftoff_code();
      DCHECK_EQ(1, register_use_count[liftoff_code]);
      register_use_count[liftoff_code] = 0;
      used_registers.clear(*cache);
      *cache = no_reg;
    }
References cached_instance_data, cached_mem_start, v8::internal::wasm::LiftoffRegList::clear(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::no_reg, register_use_count, used_registers, and V8_ASSUME.
Referenced by ClearCachedInstanceRegister(), and ClearCachedMemStartRegister().
dec_used()
void v8::internal::wasm::LiftoffAssembler::CacheState::dec_used (LiftoffRegister reg) [inline]
Definition at line 307 of file liftoff-assembler.h.
                                       {
      // Note that we do not DCHECK(!frozen) here due to a special case: When
      // performign a call_indirect, we first create an OOL trap label (which
      // freezes the state to make sure that the safe point table remains valid)
      // and then we drop values (which doesn't invalidate safe point table, so
      // it is actually fine to do it.)
      DCHECK(is_used(reg));
      if (reg.is_pair()) {
        dec_used(reg.low());
        dec_used(reg.high());
        return;
      }
      int code = reg.liftoff_code();
      DCHECK_LT(0, register_use_count[code]);
      if (--register_use_count[code] == 0) used_registers.clear(reg);
    }
References v8::internal::wasm::LiftoffRegList::clear(), code, v8::internal::DCHECK(), DCHECK_LT, v8::internal::wasm::LiftoffRegister::high(), v8::internal::wasm::LiftoffRegister::is_pair(), is_used(), v8::internal::wasm::LiftoffRegister::liftoff_code(), v8::internal::wasm::LiftoffRegister::low(), register_use_count, and used_registers.
Referenced by v8::internal::wasm::LiftoffAssembler::DropExceptionValueAtOffset(), v8::internal::wasm::LiftoffAssembler::DropValues(), v8::internal::wasm::LiftoffAssembler::PopToFixedRegister(), v8::internal::wasm::LiftoffAssembler::PopVarState(), v8::internal::wasm::LiftoffAssembler::PrepareCall(), v8::internal::wasm::LiftoffAssembler::PrepareForBranch(), v8::internal::wasm::LiftoffAssembler::Spill(), and v8::internal::wasm::LiftoffAssembler::SpillRegister().
DefineSafepoint()
void v8::internal::wasm::LiftoffAssembler::CacheState::DefineSafepoint (SafepointTableBuilder::Safepoint & safepoint)
Definition at line 307 of file liftoff-assembler.cc.
                                               {
  // Go in reversed order to set the higher bits first; this avoids cost for
  // growing the underlying bitvector.
  for (const auto& slot : base::Reversed(stack_state)) {
    if (is_reference(slot.kind())) {
      // TODO(v8:14422): References that are not on the stack now will get lost
      // at the moment. Once v8:14422 is resolved, this `continue` should be
      // revisited and potentially updated to a DCHECK.
      if (!slot.is_stack()) continue;
      safepoint.DefineTaggedStackSlot(GetSafepointIndexForStackSlot(slot));
    }
  }
}
References v8::internal::SafepointTableBuilder::Safepoint::DefineTaggedStackSlot(), v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::GetSafepointIndexForStackSlot(), v8::internal::wasm::is_reference(), and v8::base::Reversed().
DefineSafepointWithCalleeSavedRegisters()
void v8::internal::wasm::LiftoffAssembler::CacheState::DefineSafepointWithCalleeSavedRegisters (SafepointTableBuilder::Safepoint & safepoint)
Definition at line 322 of file liftoff-assembler.cc.
                                               {
  for (const auto& slot : stack_state) {
    if (!is_reference(slot.kind())) continue;
    if (slot.is_stack()) {
      safepoint.DefineTaggedStackSlot(GetSafepointIndexForStackSlot(slot));
    } else {
      DCHECK(slot.is_reg());
      safepoint.DefineTaggedRegister(slot.reg().gp().code());
    }
  }
  if (cached_instance_data != no_reg) {
    safepoint.DefineTaggedRegister(cached_instance_data.code());
  }
}
References v8::internal::DCHECK(), v8::internal::SafepointTableBuilder::Safepoint::DefineTaggedRegister(), v8::internal::SafepointTableBuilder::Safepoint::DefineTaggedStackSlot(), v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::GetSafepointIndexForStackSlot(), v8::internal::wasm::is_reference(), and v8::internal::no_reg.
get_use_count()
uint32_t v8::internal::wasm::LiftoffAssembler::CacheState::get_use_count (LiftoffRegister reg) const [inline]
Definition at line 331 of file liftoff-assembler.h.
                                                      {
      if (reg.is_pair()) {
        DCHECK_EQ(register_use_count[reg.low().liftoff_code()],
                  register_use_count[reg.high().liftoff_code()]);
        reg = reg.low();
      }
      DCHECK_GT(arraysize(register_use_count), reg.liftoff_code());
      return register_use_count[reg.liftoff_code()];
    }
References arraysize, DCHECK_EQ, DCHECK_GT, v8::internal::wasm::LiftoffRegister::high(), v8::internal::wasm::LiftoffRegister::is_pair(), v8::internal::wasm::LiftoffRegister::liftoff_code(), v8::internal::wasm::LiftoffRegister::low(), and register_use_count.
Referenced by v8::internal::wasm::LiftoffAssembler::GetNumUses(), v8::internal::wasm::LiftoffAssembler::PrepareForBranch(), and v8::internal::wasm::LiftoffAssembler::SpillRegister().
GetNextSpillReg()
LiftoffRegister v8::internal::wasm::LiftoffAssembler::CacheState::GetNextSpillReg (LiftoffRegList candidates) [inline]
Definition at line 360 of file liftoff-assembler.h.
                                                               {
      DCHECK(!frozen);
      DCHECK(!candidates.is_empty());
      // This method should only be called if none of the candidates is free.
      DCHECK(candidates.MaskOut(used_registers).is_empty());
      LiftoffRegList unspilled = candidates.MaskOut(last_spilled_regs);
      if (unspilled.is_empty()) {
        unspilled = candidates;
        last_spilled_regs = {};
      }
      LiftoffRegister reg = unspilled.GetFirstRegSet();
      return reg;
    }
References v8::internal::DCHECK(), v8::internal::wasm::LiftoffRegList::GetFirstRegSet(), v8::internal::wasm::LiftoffRegList::is_empty(), last_spilled_regs, v8::internal::wasm::LiftoffRegList::MaskOut(), and used_registers.
Referenced by v8::internal::wasm::LiftoffAssembler::SpillOneRegister().
GetTaggedSlotsForOOLCode()
void v8::internal::wasm::LiftoffAssembler::CacheState::GetTaggedSlotsForOOLCode (ZoneVector< int > * slots, LiftoffRegList * spills, SpillLocation spill_location)
Definition at line 288 of file liftoff-assembler.cc.
                                  {
  for (const auto& slot : stack_state) {
    if (!is_reference(slot.kind())) continue;
    if (spill_location == SpillLocation::kTopOfStack && slot.is_reg()) {
      // Registers get spilled just before the call to the runtime. In {spills}
      // we store which of the spilled registers contain references, so that we
      // can add the spill slots to the safepoint.
      spills->set(slot.reg());
      continue;
    }
    DCHECK_IMPLIES(slot.is_reg(), spill_location == SpillLocation::kStackSlots);
    slots->push_back(GetSafepointIndexForStackSlot(slot));
  }
}
References DCHECK_IMPLIES, v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::GetSafepointIndexForStackSlot(), v8::internal::wasm::is_reference(), v8::internal::ZoneVector< T >::push_back(), and v8::internal::wasm::LiftoffRegList::set().
has_unused_register() [1/2]
bool v8::internal::wasm::LiftoffAssembler::CacheState::has_unused_register (LiftoffRegList candidates) const [inline]
Definition at line 170 of file liftoff-assembler.h.
                                                              {
      LiftoffRegList available_regs = candidates.MaskOut(used_registers);
      return !available_regs.is_empty();
    }
References v8::internal::wasm::LiftoffRegList::is_empty(), v8::internal::wasm::LiftoffRegList::MaskOut(), and used_registers.
has_unused_register() [2/2]
bool v8::internal::wasm::LiftoffAssembler::CacheState::has_unused_register (RegClass rc, LiftoffRegList pinned = {}) const [inline]
Definition at line 156 of file liftoff-assembler.h.
                                                                  {}) const {
      if (kNeedI64RegPair && rc == kGpRegPair) {
        LiftoffRegList available_regs =
            kGpCacheRegList.MaskOut(used_registers).MaskOut(pinned);
        return available_regs.GetNumRegsSet() >= 2;
      } else if (kNeedS128RegPair && rc == kFpRegPair) {
        LiftoffRegList available_regs =
            kFpCacheRegList.MaskOut(used_registers).MaskOut(pinned);
        return available_regs.HasAdjacentFpRegsSet();
      }
      LiftoffRegList candidates = GetCacheRegList(rc);
      return has_unused_register(candidates.MaskOut(pinned));
    }
Referenced by v8::internal::wasm::liftoff::CacheStatePreservingTempRegisters::Acquire(), v8::internal::wasm::LiftoffAssembler::GetUnusedRegister(), v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::InitMergeRegion(), v8::internal::wasm::liftoff::MoveStackValue(), and v8::internal::wasm::LiftoffAssembler::PrepareForBranch().
has_volatile_register()
bool v8::internal::wasm::LiftoffAssembler::CacheState::has_volatile_register (LiftoffRegList candidates) [inline]
Definition at line 203 of file liftoff-assembler.h.
                                                          {
      return (cached_instance_data != no_reg &&
              candidates.has(cached_instance_data)) ||
             (cached_mem_start != no_reg && candidates.has(cached_mem_start));
    }
References cached_instance_data, cached_mem_start, v8::internal::wasm::LiftoffRegList::has(), and v8::internal::no_reg.
Referenced by v8::internal::wasm::LiftoffAssembler::SpillOneRegister(), and take_volatile_register().
inc_used()
void v8::internal::wasm::LiftoffAssembler::CacheState::inc_used (LiftoffRegister reg) [inline]
Definition at line 294 of file liftoff-assembler.h.
                                       {
      DCHECK(!frozen);
      if (reg.is_pair()) {
        inc_used(reg.low());
        inc_used(reg.high());
        return;
      }
      used_registers.set(reg);
      DCHECK_GT(kMaxInt, register_use_count[reg.liftoff_code()]);
      ++register_use_count[reg.liftoff_code()];
    }
References v8::internal::DCHECK(), DCHECK_GT, v8::internal::wasm::LiftoffRegister::high(), v8::internal::wasm::LiftoffRegister::is_pair(), v8::internal::kMaxInt, v8::internal::wasm::LiftoffRegister::liftoff_code(), v8::internal::wasm::LiftoffRegister::low(), register_use_count, v8::internal::wasm::LiftoffRegList::set(), and used_registers.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::InitMergeRegion(), v8::internal::wasm::LiftoffAssembler::PeekToRegister(), v8::internal::wasm::LiftoffAssembler::PrepareForBranch(), v8::internal::wasm::LiftoffAssembler::PushException(), and v8::internal::wasm::LiftoffAssembler::PushRegister().
is_free()
bool v8::internal::wasm::LiftoffAssembler::CacheState::is_free (LiftoffRegister reg) const [inline]
Definition at line 352 of file liftoff-assembler.h.
{ return !is_used(reg); }
References is_used().
Referenced by v8::internal::wasm::LiftoffAssembler::GetUnusedRegister(), v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::InitMergeRegion(), v8::internal::wasm::LiftoffAssembler::PushException(), and v8::internal::wasm::LiftoffAssembler::SpillRegisters().
is_used()
bool v8::internal::wasm::LiftoffAssembler::CacheState::is_used (LiftoffRegister reg) const [inline]
Definition at line 324 of file liftoff-assembler.h.
                                            {
      if (reg.is_pair()) return is_used(reg.low()) || is_used(reg.high());
      bool used = used_registers.has(reg);
      DCHECK_EQ(used, register_use_count[reg.liftoff_code()] != 0);
      return used;
    }
References DCHECK_EQ, v8::internal::wasm::LiftoffRegList::has(), v8::internal::wasm::LiftoffRegister::high(), v8::internal::wasm::LiftoffRegister::is_pair(), v8::internal::wasm::LiftoffRegister::liftoff_code(), v8::internal::wasm::LiftoffRegister::low(), register_use_count, and used_registers.
Referenced by v8::internal::wasm::LiftoffAssembler::AtomicCompareExchange(), dec_used(), v8::internal::wasm::liftoff::Emit64BitShiftOperation(), v8::internal::wasm::liftoff::EmitShiftOperation(), is_free(), v8::internal::wasm::LiftoffAssembler::PopToFixedRegister(), and v8::internal::wasm::LiftoffAssembler::SpillAdjacentFpRegisters().
operator=() [1/2]
CacheState& v8::internal::wasm::LiftoffAssembler::CacheState::operator= (CacheState &&) [default]
operator=() [2/2]
CacheState& v8::internal::wasm::LiftoffAssembler::CacheState::operator= (const CacheState &) [private], [default]
reset_used_registers()
void v8::internal::wasm::LiftoffAssembler::CacheState::reset_used_registers () [inline]
Definition at line 354 of file liftoff-assembler.h.
                                {
      DCHECK(!frozen);
      used_registers = {};
      memset(register_use_count, 0, sizeof(register_use_count));
    }
References v8::internal::DCHECK(), register_use_count, and used_registers.
Referenced by v8::internal::wasm::LiftoffAssembler::PrepareBuiltinCall(), and v8::internal::wasm::LiftoffAssembler::SpillAllRegisters().
SetCacheRegister()
void v8::internal::wasm::LiftoffAssembler::CacheState::SetCacheRegister (Register * cache, Register reg) [inline]
Definition at line 231 of file liftoff-assembler.h.
                                                         {
      DCHECK(!frozen);
      DCHECK_EQ(no_reg, *cache);
      *cache = reg;
      int liftoff_code = LiftoffRegister{reg}.liftoff_code();
      DCHECK_EQ(0, register_use_count[liftoff_code]);
      register_use_count[liftoff_code] = 1;
      used_registers.set(reg);
    }
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::no_reg, register_use_count, v8::internal::wasm::LiftoffRegList::set(), and used_registers.
Referenced by SetInstanceCacheRegister(), and SetMemStartCacheRegister().
SetInstanceCacheRegister()
void v8::internal::wasm::LiftoffAssembler::CacheState::SetInstanceCacheRegister (Register reg) [inline]
Definition at line 241 of file liftoff-assembler.h.
                                                {
      SetCacheRegister(&cached_instance_data, reg);
    }
References cached_instance_data, and SetCacheRegister().
Referenced by TrySetCachedInstanceRegister().
SetMemStartCacheRegister()
void v8::internal::wasm::LiftoffAssembler::CacheState::SetMemStartCacheRegister (Register reg, int memory_index) [inline]
Definition at line 245 of file liftoff-assembler.h.
                                                                  {
      SetCacheRegister(&cached_mem_start, reg);
      DCHECK_EQ(kNoCachedMemIndex, cached_mem_index);
      cached_mem_index = memory_index;
    }
References cached_mem_index, cached_mem_start, DCHECK_EQ, kNoCachedMemIndex, and SetCacheRegister().
Split()
void v8::internal::wasm::LiftoffAssembler::CacheState::Split (const CacheState & source)
Definition at line 269 of file liftoff-assembler.cc.
                                                               {
  // Call the private copy assignment operator.
  *this = source;
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CatchCase(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CatchException(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitDeoptPoint(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::If(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::Loop(), and v8::internal::wasm::LiftoffAssembler::MoveToReturnLocationsMultiReturn().
stack_height()
uint32_t v8::internal::wasm::LiftoffAssembler::CacheState::stack_height () const [inline]
Definition at line 378 of file liftoff-assembler.h.
                                  {
      return static_cast<uint32_t>(stack_state.size());
    }
References stack_state.
Referenced by v8::internal::wasm::LiftoffAssembler::MergeFullStackWith(), v8::internal::wasm::LiftoffAssembler::MergeIntoNewState(), v8::internal::wasm::LiftoffAssembler::MergeStackWith(), v8::internal::wasm::LiftoffAssembler::MoveToReturnLocationsMultiReturn(), v8::internal::wasm::LiftoffAssembler::PrepareCall(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::Rethrow(), and v8::internal::wasm::LiftoffAssembler::SpillRegister().
Steal()
void v8::internal::wasm::LiftoffAssembler::CacheState::Steal (CacheState & source)
Definition at line 264 of file liftoff-assembler.cc.
                                                         {
  // Just use the move assignment operator.
  *this = std::move(source);
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CatchCase(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CatchException(), and v8::internal::wasm::LiftoffAssembler::MoveToReturnLocationsMultiReturn().
take_volatile_register()
LiftoffRegister v8::internal::wasm::LiftoffAssembler::CacheState::take_volatile_register (LiftoffRegList candidates) [inline]
Definition at line 209 of file liftoff-assembler.h.
                                                                      {
      DCHECK(!frozen);
      DCHECK(has_volatile_register(candidates));
      Register reg = no_reg;
      if (cached_instance_data != no_reg &&
          candidates.has(cached_instance_data)) {
        reg = cached_instance_data;
        cached_instance_data = no_reg;
      } else {
        DCHECK(candidates.has(cached_mem_start));
        reg = cached_mem_start;
        cached_mem_start = no_reg;
        cached_mem_index = kNoCachedMemIndex;
      }
      LiftoffRegister ret{reg};
      DCHECK_EQ(1, register_use_count[ret.liftoff_code()]);
      register_use_count[ret.liftoff_code()] = 0;
      used_registers.clear(ret);
      return ret;
    }
References cached_instance_data, cached_mem_index, cached_mem_start, v8::internal::wasm::LiftoffRegList::clear(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::wasm::LiftoffRegList::has(), has_volatile_register(), kNoCachedMemIndex, v8::internal::no_reg, register_use_count, v8::internal::AssemblerRISCVI::ret(), and used_registers.
Referenced by v8::internal::wasm::LiftoffAssembler::SpillOneRegister().
TrySetCachedInstanceRegister()
Register v8::internal::wasm::LiftoffAssembler::CacheState::TrySetCachedInstanceRegister (LiftoffRegList pinned) [inline]
Definition at line 251 of file liftoff-assembler.h.
                                                                 {
      DCHECK_EQ(no_reg, cached_instance_data);
      LiftoffRegList available_regs =
          kGpCacheRegList.MaskOut(pinned).MaskOut(used_registers);
      if (available_regs.is_empty()) return no_reg;
      // Prefer the {kWasmImplicitArgRegister}, because that's where the
      // instance data initially is, and where it needs to be for calls.
      Register new_cache_reg = available_regs.has(kWasmImplicitArgRegister)
                                   ? kWasmImplicitArgRegister
                                   : available_regs.GetFirstRegSet().gp();
      SetInstanceCacheRegister(new_cache_reg);
      DCHECK_EQ(new_cache_reg, cached_instance_data);
      return new_cache_reg;
    }
References cached_instance_data, DCHECK_EQ, v8::internal::wasm::LiftoffRegList::GetFirstRegSet(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::wasm::LiftoffRegList::has(), v8::internal::wasm::LiftoffRegList::is_empty(), v8::internal::wasm::kGpCacheRegList, v8::internal::kWasmImplicitArgRegister, v8::internal::wasm::LiftoffRegList::MaskOut(), v8::internal::no_reg, SetInstanceCacheRegister(), and used_registers.
unused_register() [1/2]
LiftoffRegister v8::internal::wasm::LiftoffAssembler::CacheState::unused_register (LiftoffRegList candidates, LiftoffRegList pinned = {}) const [inline]
Definition at line 193 of file liftoff-assembler.h.
                                                            {}) const {
      LiftoffRegList available_regs =
          candidates.MaskOut(used_registers).MaskOut(pinned);
      return available_regs.GetFirstRegSet();
    }
unused_register() [2/2]
LiftoffRegister v8::internal::wasm::LiftoffAssembler::CacheState::unused_register (RegClass rc, LiftoffRegList pinned = {}) const [inline]
Definition at line 175 of file liftoff-assembler.h.
                                                            {}) const {
      if (kNeedI64RegPair && rc == kGpRegPair) {
        Register low = pinned.set(unused_register(kGpReg, pinned)).gp();
        Register high = unused_register(kGpReg, pinned).gp();
        return LiftoffRegister::ForPair(low, high);
      } else if (kNeedS128RegPair && rc == kFpRegPair) {
        LiftoffRegList available_regs =
            kFpCacheRegList.MaskOut(used_registers).MaskOut(pinned);
        DoubleRegister low =
            available_regs.GetAdjacentFpRegsSet().GetFirstRegSet().fp();
        DCHECK(is_free(LiftoffRegister::ForFpPair(low)));
        return LiftoffRegister::ForFpPair(low);
      }
      LiftoffRegList candidates = GetCacheRegList(rc);
      return unused_register(candidates, pinned);
    }
Referenced by v8::internal::wasm::liftoff::CacheStatePreservingTempRegisters::Acquire(), v8::internal::wasm::LiftoffAssembler::GetUnusedRegister(), v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::InitMergeRegion(), v8::internal::wasm::liftoff::MoveStackValue(), and v8::internal::wasm::LiftoffAssembler::PrepareForBranch().
Member Data Documentation
cached_instance_data
Register v8::internal::wasm::LiftoffAssembler::CacheState::cached_instance_data = no_reg
Definition at line 146 of file liftoff-assembler.h.
Referenced by v8::internal::wasm::LiftoffAssembler::CheckTierUp(), ClearCachedInstanceRegister(), ClearCacheRegister(), has_volatile_register(), v8::internal::wasm::LiftoffAssembler::MergeFullStackWith(), v8::internal::wasm::LiftoffAssembler::MergeIntoNewState(), v8::internal::wasm::LiftoffAssembler::MergeStackWith(), v8::internal::wasm::LiftoffAssembler::PrepareCall(), SetInstanceCacheRegister(), v8::internal::wasm::LiftoffAssembler::SpillRegisters(), take_volatile_register(), and TrySetCachedInstanceRegister().
cached_mem_index
int v8::internal::wasm::LiftoffAssembler::CacheState::cached_mem_index = kNoCachedMemIndex
Definition at line 150 of file liftoff-assembler.h.
Referenced by ClearCachedMemStartRegister(), v8::internal::wasm::LiftoffAssembler::MergeFullStackWith(), v8::internal::wasm::LiftoffAssembler::MergeIntoNewState(), v8::internal::wasm::LiftoffAssembler::MergeStackWith(), SetMemStartCacheRegister(), v8::internal::wasm::LiftoffAssembler::SpillRegisters(), and take_volatile_register().
cached_mem_start
Register v8::internal::wasm::LiftoffAssembler::CacheState::cached_mem_start = no_reg
Definition at line 151 of file liftoff-assembler.h.
Referenced by ClearCachedMemStartRegister(), ClearCacheRegister(), has_volatile_register(), v8::internal::wasm::LiftoffAssembler::MergeFullStackWith(), v8::internal::wasm::LiftoffAssembler::MergeIntoNewState(), v8::internal::wasm::LiftoffAssembler::MergeStackWith(), SetMemStartCacheRegister(), v8::internal::wasm::LiftoffAssembler::SpillRegisters(), and take_volatile_register().
kNoCachedMemIndex
constexpr int v8::internal::wasm::LiftoffAssembler::CacheState::kNoCachedMemIndex = -1 [static], [constexpr]
Definition at line 147 of file liftoff-assembler.h.
Referenced by ClearCachedMemStartRegister(), v8::internal::wasm::LiftoffAssembler::MergeIntoNewState(), v8::internal::wasm::LiftoffAssembler::MergeStackWith(), SetMemStartCacheRegister(), and take_volatile_register().
last_spilled_regs
LiftoffRegList v8::internal::wasm::LiftoffAssembler::CacheState::last_spilled_regs
Definition at line 145 of file liftoff-assembler.h.
Referenced by GetNextSpillReg(), and v8::internal::wasm::LiftoffAssembler::SpillRegister().
register_use_count
uint32_t v8::internal::wasm::LiftoffAssembler::CacheState::register_use_count[kAfterMaxLiftoffRegCode] = {0}
Definition at line 144 of file liftoff-assembler.h.
Referenced by clear_used(), ClearCacheRegister(), dec_used(), get_use_count(), inc_used(), is_used(), reset_used_registers(), SetCacheRegister(), and take_volatile_register().
stack_state
SmallZoneVector<VarState, 16> v8::internal::wasm::LiftoffAssembler::CacheState::stack_state
Definition at line 142 of file liftoff-assembler.h.
Referenced by v8::internal::wasm::LiftoffAssembler::DropExceptionValueAtOffset(), v8::internal::wasm::LiftoffAssembler::DropValues(), v8::internal::wasm::LiftoffAssembler::MergeFullStackWith(), v8::internal::wasm::LiftoffAssembler::MergeIntoNewState(), v8::internal::wasm::LiftoffAssembler::MergeStackWith(), v8::internal::wasm::LiftoffAssembler::MoveToReturnLocations(), v8::internal::wasm::LiftoffAssembler::MoveToReturnLocationsMultiReturn(), v8::internal::wasm::LiftoffAssembler::PeekToRegister(), v8::internal::wasm::LiftoffAssembler::PopToFixedRegister(), v8::internal::wasm::LiftoffAssembler::PopVarState(), v8::internal::wasm::LiftoffAssembler::PrepareCall(), v8::internal::wasm::LiftoffAssembler::PrepareForBranch(), v8::internal::wasm::LiftoffAssembler::PushConstant(), v8::internal::wasm::LiftoffAssembler::PushException(), v8::internal::wasm::LiftoffAssembler::PushRegister(), v8::internal::wasm::LiftoffAssembler::PushStack(), v8::internal::wasm::LiftoffAssembler::SpillAllRegisters(), v8::internal::wasm::LiftoffAssembler::SpillLocals(), v8::internal::wasm::LiftoffAssembler::SpillLoopArgs(), v8::internal::wasm::LiftoffAssembler::SpillRegister(), stack_height(), v8::internal::wasm::LiftoffAssembler::TopSpillOffset(), and v8::internal::wasm::LiftoffAssembler::zone().
used_registers
LiftoffRegList v8::internal::wasm::LiftoffAssembler::CacheState::used_registers
Definition at line 143 of file liftoff-assembler.h.
Referenced by clear_used(), ClearCacheRegister(), dec_used(), v8::internal::wasm::LiftoffAssembler::emit_i64x2_mul(), GetNextSpillReg(), has_unused_register(), inc_used(), is_used(), v8::internal::wasm::LiftoffAssembler::LoadOldFramePointer(), v8::internal::wasm::LiftoffAssembler::PrepareCall(), reset_used_registers(), SetCacheRegister(), v8::internal::wasm::LiftoffAssembler::SpillAdjacentFpRegisters(), take_volatile_register(), and TrySetCachedInstanceRegister().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/wasm/baseline/liftoff-assembler.h
/mnt/V8SourceCode/src/wasm/baseline/liftoff-assembler.cc