v8::internal::ArrayProxy Struct Reference
Static Public Member Functions
static DirectHandle< JSObject > Create (Isolate *isolate, DirectHandle< WasmArray > value)
static v8::Local< v8::FunctionTemplate > CreateTemplate (v8::Isolate *isolate)
static uint32_t Count (Isolate *isolate, DirectHandle< WasmArray > array)
static DirectHandle< Object > Get (Isolate *isolate, DirectHandle< WasmArray > array, uint32_t index)
Static Public Attributes
static constexpr char const * kClassName = `Array`
Detailed Description
Definition at line 941 of file debug-wasm-objects.cc.
Member Function Documentation
Count()
static uint32_t v8::internal::ArrayProxy::Count (Isolate * isolate, DirectHandle< WasmArray > array) [inline], [static]
Definition at line 966 of file debug-wasm-objects.cc.
                                                                         {
    return array->length();
  }
Create()
static DirectHandle<JSObject> v8::internal::ArrayProxy::Create (Isolate * isolate, DirectHandle< WasmArray > value) [inline], [static]
Definition at line 944 of file debug-wasm-objects.cc.
                                                                      {
    DirectHandle<JSObject> proxy = IndexedDebugProxy::Create(
        isolate, value, false /* leave map extensible */);
    uint32_t length = value->length();
    DirectHandle<Object> length_obj =
        isolate->factory()->NewNumberFromUint(length);
    Object::SetProperty(isolate, proxy, isolate->factory()->length_string(),
                        length_obj, StoreOrigin::kNamed,
                        Just(ShouldThrow::kThrowOnError))
        .Check();
    return proxy;
  }
References v8::internal::Isolate::factory(), v8::Just(), v8::internal::kNamed, v8::internal::kThrowOnError, v8::internal::length, v8::internal::FactoryBase< Impl >::NewNumberFromUint(), v8::internal::Object::SetProperty(), and v8::internal::value.
Referenced by v8::internal::WasmValueObject::New().
CreateTemplate()
static v8::Local<v8::FunctionTemplate> v8::internal::ArrayProxy::CreateTemplate (v8::Isolate * isolate) [inline], [static]
Definition at line 958 of file debug-wasm-objects.cc.
                                                                        {
    Local<v8::FunctionTemplate> templ =
        IndexedDebugProxy::CreateTemplate(isolate);
    templ->InstanceTemplate()->Set(isolate, "length",
                                   v8::Number::New(isolate, 0));
    return templ;
  }
References v8::Number::New().
Get()
static DirectHandle<Object> v8::internal::ArrayProxy::Get (Isolate * isolate, DirectHandle< WasmArray > array, uint32_t index) [inline], [static]
Definition at line 970 of file debug-wasm-objects.cc.
                                                  {
    return WasmValueObject::New(isolate, array->GetElement(index));
  }
References v8::internal::index, and v8::internal::WasmValueObject::New().
Member Data Documentation
kClassName
constexpr char const* v8::internal::ArrayProxy::kClassName = `Array` [static], [constexpr]
Definition at line 942 of file debug-wasm-objects.cc.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/debug/debug-wasm-objects.cc