v8::internal::compiler::turboshaft::TransitionAndStoreArrayElementOp Struct Reference
#include <operations.h>
Public Types
enum class Kind : uint8_t {
kElement
, kNumberElement
, kOddballElement
, kNonNumberElement
,
kSignedSmallElement
 }
Public Member Functions
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
V< JSArray > array () const
V< WordPtr > index () const
V< Any > value () const
TransitionAndStoreArrayElementOp (V< JSArray > array, V< WordPtr > index, V< Any > value, Kind kind, MaybeIndirectHandle< Map > fast_map, MaybeIndirectHandle< Map > double_map)
RegisterRepresentation value_representation () const
size_t hash_value (HashingStrategy strategy=HashingStrategy::kDefault) const
bool operator== (const TransitionAndStoreArrayElementOp &other) const
auto options () const
Public Attributes
Kind kind
MaybeIndirectHandle< Map > fast_map
MaybeIndirectHandle< Map > double_map
Static Public Attributes
static constexpr OpEffects effects
Additional Inherited Members
Detailed Description
Definition at line 6062 of file operations.h.
Member Enumeration Documentation
Kind
enum v8::internal::compiler::turboshaft::TransitionAndStoreArrayElementOp::Kind : uint8_t [strong]
Enumerator
kElement
kNumberElement
kOddballElement
kNonNumberElement
kSignedSmallElement
Definition at line 6064 of file operations.h.
                  : uint8_t {
    kElement,
    kNumberElement,
    kOddballElement,
    kNonNumberElement,
    kSignedSmallElement,
  };
Constructor & Destructor Documentation
TransitionAndStoreArrayElementOp()
v8::internal::compiler::turboshaft::TransitionAndStoreArrayElementOp::TransitionAndStoreArrayElementOp (V< JSArray > array, V< WordPtr > index, V< Any > value, Kind kind, MaybeIndirectHandle< Map > fast_map, MaybeIndirectHandle< Map > double_map) [inline]
Definition at line 6095 of file operations.h.
      : Base(array, index, value),
        kind(kind),
        fast_map(fast_map),
        double_map(double_map) {}
Member Function Documentation
array()
V<JSArray> v8::internal::compiler::turboshaft::TransitionAndStoreArrayElementOp::array () const [inline]
Definition at line 6091 of file operations.h.
{ return Base::input<JSArray>(0); }
hash_value()
size_t v8::internal::compiler::turboshaft::TransitionAndStoreArrayElementOp::hash_value (HashingStrategy strategy = HashingStrategy::kDefault) const [inline]
Definition at line 6118 of file operations.h.
                                                                {
    DCHECK_EQ(strategy, HashingStrategy::kDefault);
    return HashWithOptions(fast_map.address(), double_map.address());
  }
References v8::internal::MaybeHandle< T >::address(), DCHECK_EQ, and v8::internal::compiler::turboshaft::kDefault.
index()
V<WordPtr> v8::internal::compiler::turboshaft::TransitionAndStoreArrayElementOp::index () const [inline]
Definition at line 6092 of file operations.h.
{ return Base::input<WordPtr>(1); }
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::TransitionAndStoreArrayElementOp::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 6084 of file operations.h.
                                                              {
    return InitVectorOf(
        storage, {RegisterRepresentation::Tagged(),
                  RegisterRepresentation::WordPtr(), value_representation()});
  }
References v8::internal::compiler::turboshaft::InitVectorOf(), v8::internal::compiler::turboshaft::RegisterRepresentation::Tagged(), and v8::internal::compiler::turboshaft::RegisterRepresentation::WordPtr().
operator==()
bool v8::internal::compiler::turboshaft::TransitionAndStoreArrayElementOp::operator== (const TransitionAndStoreArrayElementOp & other) const [inline]
Definition at line 6124 of file operations.h.
                                                                       {
    return kind == other.kind && fast_map.equals(other.fast_map) &&
           double_map.equals(other.double_map);
  }
References double_map, v8::internal::MaybeHandle< T >::equals(), fast_map, and kind.
options()
auto v8::internal::compiler::turboshaft::TransitionAndStoreArrayElementOp::options () const [inline]
Definition at line 6129 of file operations.h.
{ return std::tuple{kind, fast_map, double_map}; }
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::TransitionAndStoreArrayElementOp::outputs_rep () const [inline]
Definition at line 6082 of file operations.h.
{ return {}; }
value()
V<Any> v8::internal::compiler::turboshaft::TransitionAndStoreArrayElementOp::value () const [inline]
Definition at line 6093 of file operations.h.
{ return Base::input<Any>(2); }
value_representation()
RegisterRepresentation v8::internal::compiler::turboshaft::TransitionAndStoreArrayElementOp::value_representation () const [inline]
Definition at line 6105 of file operations.h.
                                                      {
    switch (kind) {
      case Kind::kElement:
      case Kind::kNonNumberElement:
      case Kind::kOddballElement:
        return RegisterRepresentation::Tagged();
      case Kind::kNumberElement:
        return RegisterRepresentation::Float64();
      case Kind::kSignedSmallElement:
        return RegisterRepresentation::Word32();
    }
  }
References v8::internal::compiler::turboshaft::RegisterRepresentation::Float64(), v8::internal::compiler::turboshaft::RegisterRepresentation::Tagged(), and v8::internal::compiler::turboshaft::RegisterRepresentation::Word32().
Member Data Documentation
double_map
MaybeIndirectHandle<Map> v8::internal::compiler::turboshaft::TransitionAndStoreArrayElementOp::double_map
Definition at line 6073 of file operations.h.
Referenced by operator==().
effects
constexpr OpEffects v8::internal::compiler::turboshaft::TransitionAndStoreArrayElementOp::effects [static], [constexpr]
Initial value:
=
      OpEffects()
          
          .CanReadHeapMemory()
          .CanWriteHeapMemory()
          
          .CanDependOnChecks()
Definition at line 6075 of file operations.h.
fast_map
MaybeIndirectHandle<Map> v8::internal::compiler::turboshaft::TransitionAndStoreArrayElementOp::fast_map
Definition at line 6072 of file operations.h.
Referenced by operator==().
kind
Kind v8::internal::compiler::turboshaft::TransitionAndStoreArrayElementOp::kind
Definition at line 6071 of file operations.h.
Referenced by operator==().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h