v8::internal::CodeSerializer::OffThreadDeserializeData Struct Reference
#include <code-serializer.h>
Public Member Functions
bool HasResult () const
DirectHandle< Script > GetOnlyScript (LocalHeap *heap)
Private Attributes
MaybeIndirectHandle< SharedFunctionInfo > maybe_result
std::vector< IndirectHandle< Script > > scripts
std::unique_ptr< PersistentHandles > persistent_handles
SerializedCodeSanityCheckResult sanity_check_result
Friends
class CodeSerializer
Detailed Description
Definition at line 62 of file code-serializer.h.
Member Function Documentation
GetOnlyScript()
DirectHandle< Script > v8::internal::CodeSerializer::OffThreadDeserializeData::GetOnlyScript (LocalHeap * heap)
Definition at line 562 of file code-serializer.cc.
                     {
  std::unique_ptr<PersistentHandles> previous_persistent_handles =
      heap->DetachPersistentHandles();
  heap->AttachPersistentHandles(std::move(persistent_handles));
  DCHECK_EQ(scripts.size(), 1);
  // Make a non-persistent handle to return.
  DirectHandle<Script> script = direct_handle(*scripts[0], heap);
  DCHECK_EQ(*script, maybe_result.ToHandleChecked()->script());
  persistent_handles = heap->DetachPersistentHandles();
  if (previous_persistent_handles) {
    heap->AttachPersistentHandles(std::move(previous_persistent_handles));
  }
  return script;
}
References DCHECK_EQ, v8::internal::direct_handle(), maybe_result, persistent_handles, v8::internal::script, and scripts.
Referenced by v8::internal::BackgroundDeserializeTask::MergeWithExistingScript(), and v8::internal::BackgroundDeserializeTask::Run().
HasResult()
bool v8::internal::CodeSerializer::OffThreadDeserializeData::HasResult () const [inline]
Definition at line 64 of file code-serializer.h.
{ return !maybe_result.is_null(); }
References maybe_result.
Referenced by v8::internal::BackgroundDeserializeTask::Run(), and v8::internal::BackgroundDeserializeTask::ShouldMergeWithExistingScript().
Friends And Related Function Documentation
CodeSerializer
friend class CodeSerializer [friend]
Definition at line 68 of file code-serializer.h.
Member Data Documentation
maybe_result
MaybeIndirectHandle<SharedFunctionInfo> v8::internal::CodeSerializer::OffThreadDeserializeData::maybe_result [private]
Definition at line 69 of file code-serializer.h.
Referenced by GetOnlyScript(), and HasResult().
persistent_handles
std::unique_ptr<PersistentHandles> v8::internal::CodeSerializer::OffThreadDeserializeData::persistent_handles [private]
Definition at line 71 of file code-serializer.h.
Referenced by GetOnlyScript().
sanity_check_result
SerializedCodeSanityCheckResult v8::internal::CodeSerializer::OffThreadDeserializeData::sanity_check_result [private]
Definition at line 72 of file code-serializer.h.
scripts
std::vector<IndirectHandle<Script> > v8::internal::CodeSerializer::OffThreadDeserializeData::scripts [private]
Definition at line 70 of file code-serializer.h.
Referenced by GetOnlyScript().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/snapshot/code-serializer.h
/mnt/V8SourceCode/src/snapshot/code-serializer.cc