v8::internal::anonymous_namespace{liveedit.cc}::SourcePositionEvent Struct Reference
Public Types
enum Type { LITERAL_STARTS
, LITERAL_ENDS
, DIFF_STARTS
, DIFF_ENDS
 }
Public Member Functions
SourcePositionEvent (FunctionLiteral *literal, bool is_start)
SourcePositionEvent (const SourceChangeRange &change, bool is_start)
Static Public Member Functions
static bool LessThan (const SourcePositionEvent &a, const SourcePositionEvent &b)
Public Attributes
int position
Type type
union v8::internal::anonymous_namespace{liveedit.cc}::SourcePositionEvent:: { ... }
FunctionLiteral * literal
int pos_diff
Detailed Description
Definition at line 287 of file liveedit.cc.
Member Enumeration Documentation
Type
enum v8::internal::anonymous_namespace{liveedit.cc}::SourcePositionEvent::Type
Enumerator
LITERAL_STARTS
LITERAL_ENDS
DIFF_STARTS
DIFF_ENDS
Definition at line 288 of file liveedit.cc.
{ LITERAL_STARTS, LITERAL_ENDS, DIFF_STARTS, DIFF_ENDS };
Constructor & Destructor Documentation
SourcePositionEvent() [1/2]
v8::internal::anonymous_namespace{liveedit.cc}::SourcePositionEvent::SourcePositionEvent (FunctionLiteral * literal, bool is_start) [inline]
Definition at line 298 of file liveedit.cc.
      : position(is_start ? literal->start_position()
                          : literal->end_position()),
        type(is_start ? LITERAL_STARTS : LITERAL_ENDS),
        literal(literal) {}
SourcePositionEvent() [2/2]
v8::internal::anonymous_namespace{liveedit.cc}::SourcePositionEvent::SourcePositionEvent (const SourceChangeRange & change, bool is_start) [inline]
Definition at line 303 of file liveedit.cc.
      : position(is_start ? change.start_position : change.end_position),
        type(is_start ? DIFF_STARTS : DIFF_ENDS),
        pos_diff((change.new_end_position - change.new_start_position) -
                 (change.end_position - change.start_position)) {}
Member Function Documentation
LessThan()
static bool v8::internal::anonymous_namespace{liveedit.cc}::SourcePositionEvent::LessThan (const SourcePositionEvent & a, const SourcePositionEvent & b) [inline], [static]
Definition at line 309 of file liveedit.cc.
                                                     {
    if (a.position != b.position) return a.position < b.position;
    if (a.type != b.type) return a.type < b.type;
    if (a.type == LITERAL_STARTS && b.type == LITERAL_STARTS) {
      // If the literals start in the same position, we want the one with the
      // furthest (i.e. largest) end position to be first.
      if (a.literal->end_position() != b.literal->end_position()) {
        return a.literal->end_position() > b.literal->end_position();
      }
      // If they also end in the same position, we want the first in order of
      // literal ids to be first.
      return a.literal->function_literal_id() <
             b.literal->function_literal_id();
    } else if (a.type == LITERAL_ENDS && b.type == LITERAL_ENDS) {
      // If the literals end in the same position, we want the one with the
      // nearest (i.e. largest) start position to be first.
      if (a.literal->start_position() != b.literal->start_position()) {
        return a.literal->start_position() > b.literal->start_position();
      }
      // If they also end in the same position, we want the last in order of
      // literal ids to be first.
      return a.literal->function_literal_id() >
             b.literal->function_literal_id();
    } else {
      return a.pos_diff < b.pos_diff;
    }
  }
References v8::internal::FunctionLiteral::end_position(), v8::internal::FunctionLiteral::function_literal_id(), literal, pos_diff, position, v8::internal::FunctionLiteral::start_position(), and type.
Member Data Documentation
union { ... }
literal
FunctionLiteral* v8::internal::anonymous_namespace{liveedit.cc}::SourcePositionEvent::literal
Definition at line 294 of file liveedit.cc.
Referenced by LessThan().
pos_diff
int v8::internal::anonymous_namespace{liveedit.cc}::SourcePositionEvent::pos_diff
Definition at line 295 of file liveedit.cc.
Referenced by LessThan().
position
int v8::internal::anonymous_namespace{liveedit.cc}::SourcePositionEvent::position
Definition at line 290 of file liveedit.cc.
Referenced by LessThan().
type
Type v8::internal::anonymous_namespace{liveedit.cc}::SourcePositionEvent::type
Definition at line 291 of file liveedit.cc.
Referenced by LessThan().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/debug/liveedit.cc