v8::internal::TracingFlags Struct Reference
#include <tracing-flags.h>
Static Public Member Functions
static bool is_gc_enabled ()
static bool is_gc_stats_enabled ()
static bool is_ic_stats_enabled ()
static bool is_zone_stats_enabled ()
Static Public Attributes
static V8_EXPORT_PRIVATE std::atomic_uint runtime_stats {0}
static V8_EXPORT_PRIVATE std::atomic_uint gc {0}
static V8_EXPORT_PRIVATE std::atomic_uint gc_stats {0}
static V8_EXPORT_PRIVATE std::atomic_uint ic_stats {0}
static V8_EXPORT_PRIVATE std::atomic_uint zone_stats {0}
Detailed Description
Definition at line 19 of file tracing-flags.h.
Member Function Documentation
is_gc_enabled()
static bool v8::internal::TracingFlags::is_gc_enabled () [inline], [static]
Definition at line 32 of file tracing-flags.h.
                              {
    return gc.load(std::memory_order_relaxed) != 0;
  }
References gc.
is_gc_stats_enabled()
static bool v8::internal::TracingFlags::is_gc_stats_enabled () [inline], [static]
Definition at line 36 of file tracing-flags.h.
                                    {
    return gc_stats.load(std::memory_order_relaxed) != 0;
  }
References gc_stats.
Referenced by v8::internal::Heap::CreateObjectStats(), v8::Isolate::GetHeapObjectStatisticsAtLastGC(), v8::internal::Genesis::InstallExtensions(), v8::Shell::Main(), and v8::internal::Heap::SetUpSpaces().
is_ic_stats_enabled()
static bool v8::internal::TracingFlags::is_ic_stats_enabled () [inline], [static]
Definition at line 40 of file tracing-flags.h.
                                    {
    return ic_stats.load(std::memory_order_relaxed) != 0;
  }
References ic_stats.
Referenced by v8::internal::ICStats::Begin(), and v8::internal::IC::TraceIC().
is_zone_stats_enabled()
static bool v8::internal::TracingFlags::is_zone_stats_enabled () [inline], [static]
Definition at line 44 of file tracing-flags.h.
                                      {
    return zone_stats.load(std::memory_order_relaxed) != 0;
  }
References zone_stats.
Referenced by v8::internal::Zone::Allocate(), v8::internal::Zone::Delete(), v8::internal::AccountingAllocator::TraceAllocateSegment(), v8::internal::AccountingAllocator::TraceZoneCreation(), and v8::internal::AccountingAllocator::TraceZoneDestruction().
Member Data Documentation
gc
std::atomic_uint v8::internal::TracingFlags::gc {0} [static]
Definition at line 21 of file tracing-flags.h.
Referenced by is_gc_enabled(), v8::tracing::TracingCategoryObserver::OnTraceDisabled(), v8::tracing::TracingCategoryObserver::OnTraceEnabled(), and v8::internal::GCTracer::StopObservablePause().
gc_stats
std::atomic_uint v8::internal::TracingFlags::gc_stats {0} [static]
Definition at line 22 of file tracing-flags.h.
Referenced by v8::internal::Deserializer< IsolateT >::DisableGCStats::DisableGCStats(), is_gc_stats_enabled(), v8::tracing::TracingCategoryObserver::OnTraceDisabled(), v8::tracing::TracingCategoryObserver::OnTraceEnabled(), and v8::internal::Deserializer< IsolateT >::DisableGCStats::~DisableGCStats().
ic_stats
std::atomic_uint v8::internal::TracingFlags::ic_stats {0} [static]
Definition at line 23 of file tracing-flags.h.
Referenced by is_ic_stats_enabled(), v8::tracing::TracingCategoryObserver::OnTraceDisabled(), v8::tracing::TracingCategoryObserver::OnTraceEnabled(), and v8::internal::IC::TraceIC().
runtime_stats
std::atomic_uint v8::internal::TracingFlags::runtime_stats {0} [static]
Definition at line 20 of file tracing-flags.h.
Referenced by v8::internal::Isolate::DumpAndResetStats(), v8::tracing::TracingCategoryObserver::OnTraceDisabled(), v8::tracing::TracingCategoryObserver::OnTraceEnabled(), and v8::internal::V8FileLogger::TickEvent().
zone_stats
std::atomic_uint v8::internal::TracingFlags::zone_stats {0} [static]
Definition at line 24 of file tracing-flags.h.
Referenced by is_zone_stats_enabled(), v8::tracing::TracingCategoryObserver::OnTraceEnabled(), and v8::internal::TracingAccountingAllocator::UpdateMemoryTrafficAndReportMemoryUsage().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/logging/tracing-flags.h
/mnt/V8SourceCode/src/logging/tracing-flags.cc