v8::internal::compiler::turboshaft::BuiltinCallDescriptor::Descriptor< Derived > Struct Template Reference
Static Public Member Functions
static const TSCallDescriptor * Create (StubCallMode call_mode, Zone *zone, LazyDeoptOnThrow lazy_deopt_on_throw=LazyDeoptOnThrow::kNo)
Detailed Description
template<typename Derived>
struct v8::internal::compiler::turboshaft::BuiltinCallDescriptor::Descriptor< Derived >
Definition at line 23 of file builtin-call-descriptors.h.
Member Function Documentation
Create()
template<typename Derived >
static const TSCallDescriptor* v8::internal::compiler::turboshaft::BuiltinCallDescriptor::Descriptor< Derived >::Create (StubCallMode call_mode, Zone * zone, LazyDeoptOnThrow lazy_deopt_on_throw = LazyDeoptOnThrow::kNo) [inline], [static]
Definition at line 24 of file builtin-call-descriptors.h.
                                                                    {
      CallInterfaceDescriptor interface_descriptor =
          Builtins::CallInterfaceDescriptorFor(Derived::kFunction);
      auto descriptor = Linkage::GetStubCallDescriptor(
          zone, interface_descriptor,
          interface_descriptor.GetStackParameterCount(),
          Derived::kNeedsFrameState ? CallDescriptor::kNeedsFrameState
                                    : CallDescriptor::kNoFlags,
          Derived::kProperties, call_mode);
#ifdef DEBUG
      Derived::Verify(descriptor);
#endif // DEBUG
      bool can_throw = !(Derived::kProperties & Operator::kNoThrow);
      return TSCallDescriptor::Create(
          descriptor, can_throw ? CanThrow::kYes : CanThrow::kNo,
          lazy_deopt_on_throw, zone);
    }
References v8::internal::Builtins::CallInterfaceDescriptorFor(), v8::internal::compiler::turboshaft::TSCallDescriptor::Create(), v8::internal::CallInterfaceDescriptor::GetStackParameterCount(), v8::internal::compiler::Linkage::GetStubCallDescriptor(), v8::internal::torque::ls::kFunction, v8::internal::compiler::CallDescriptor::kNeedsFrameState, v8::internal::compiler::kNo, v8::internal::compiler::CallDescriptor::kNoFlags, v8::internal::compiler::Operator::kNoThrow, and v8::internal::compiler::kYes.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/builtin-call-descriptors.h