v8::internal::compiler::turboshaft::SwitchOp Struct Reference
#include <operations.h>
Classes
struct Case
Public Member Functions
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
V< Word32 > input () const
SwitchOp (V< Word32 > input, base::Vector< Case > cases, Block *default_case, BranchHint default_hint)
V8_EXPORT_PRIVATE void Validate (const Graph &graph) const
void PrintOptions (std::ostream &os) const
size_t hash_value (HashingStrategy strategy=HashingStrategy::kDefault) const
auto options () const
Public Attributes
BranchHint default_hint
base::Vector< Case > cases
Block * default_case
Static Public Attributes
static constexpr OpEffects effects = OpEffects().CanChangeControlFlow()
Additional Inherited Members
Detailed Description
Definition at line 4445 of file operations.h.
Constructor & Destructor Documentation
SwitchOp()
v8::internal::compiler::turboshaft::SwitchOp::SwitchOp (V< Word32 > input, base::Vector< Case > cases, Block * default_case, BranchHint default_hint) [inline]
Definition at line 4473 of file operations.h.
      : Base(input),
        default_hint(default_hint),
        cases(cases),
        default_case(default_case) {}
Member Function Documentation
hash_value()
size_t v8::internal::compiler::turboshaft::SwitchOp::hash_value (HashingStrategy strategy = HashingStrategy::kDefault) const
Definition at line 2144 of file operations.cc.
                                                          {
  if (strategy == HashingStrategy::kMakeSnapshotStable) {
    // Destructure here to cause a compilation error in case `options` is
    // changed.
    auto [cases_value, default_case_value, default_hint_value] = options();
    DCHECK_NOT_NULL(default_case_value);
    size_t hash = HashWithOptions(index_for_bound_block(default_case_value),
                                  default_hint_value);
    for (const auto& c : cases_value) {
      hash = fast_hash_combine(hash, c.value,
                               index_for_bound_block(c.destination), c.hint);
    }
    return hash;
  } else {
    return Base::hash_value(strategy);
  }
}
References DCHECK_NOT_NULL, v8::internal::compiler::turboshaft::fast_hash_combine(), v8::internal::compiler::turboshaft::OperationT< Derived >::hash_value(), v8::internal::compiler::turboshaft::OperationT< Derived >::HashWithOptions(), v8::internal::compiler::turboshaft::anonymous_namespace{operations.cc}::index_for_bound_block(), v8::internal::compiler::turboshaft::kMakeSnapshotStable, and options().
input()
V<Word32> v8::internal::compiler::turboshaft::SwitchOp::input () const [inline]
Definition at line 4471 of file operations.h.
{ return Base::input<Word32>(0); }
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphSwitch().
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::SwitchOp::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 4466 of file operations.h.
                                                              {
    return MaybeRepVector<MaybeRegisterRepresentation::Word32()>();
  }
options()
auto v8::internal::compiler::turboshaft::SwitchOp::options () const [inline]
Definition at line 4483 of file operations.h.
{ return std::tuple{cases, default_case, default_hint}; }
Referenced by hash_value().
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::SwitchOp::outputs_rep () const [inline]
Definition at line 4464 of file operations.h.
{ return {}; }
PrintOptions()
void v8::internal::compiler::turboshaft::SwitchOp::PrintOptions (std::ostream & os) const
Definition at line 1137 of file operations.cc.
                                                {
  os << '[';
  for (const Case& c : cases) {
    os << "case " << c.value << ": " << c.destination << ", ";
  }
  os << " default: " << default_case << ']';
}
References cases, and default_case.
Validate()
void v8::internal::compiler::turboshaft::SwitchOp::Validate (const Graph & graph) const
Definition at line 1145 of file operations.cc.
                                                {
  // Checking that there are no duplicated cases.
  std::unordered_set<int> cases_set;
  for (Case cas : cases) {
    DCHECK(!cases_set.contains(cas.value));
    cases_set.insert(cas.value);
  }
}
References cases, and v8::internal::DCHECK().
Member Data Documentation
cases
base::Vector<Case> v8::internal::compiler::turboshaft::SwitchOp::cases
Definition at line 4460 of file operations.h.
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphSwitch(), v8::internal::compiler::turboshaft::IsUnlikelySuccessor(), PrintOptions(), v8::internal::compiler::turboshaft::Assembler< Reducers >::SplitEdge(), Validate(), and v8::internal::compiler::InstructionSelector::VisitControl().
default_case
Block* v8::internal::compiler::turboshaft::SwitchOp::default_case
Definition at line 4461 of file operations.h.
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphSwitch(), v8::internal::compiler::turboshaft::IsUnlikelySuccessor(), PrintOptions(), v8::internal::compiler::turboshaft::Assembler< Reducers >::SplitEdge(), and v8::internal::compiler::InstructionSelector::VisitControl().
default_hint
BranchHint v8::internal::compiler::turboshaft::SwitchOp::default_hint
Definition at line 4459 of file operations.h.
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphSwitch(), and v8::internal::compiler::turboshaft::IsUnlikelySuccessor().
effects
constexpr OpEffects v8::internal::compiler::turboshaft::SwitchOp::effects = OpEffects().CanChangeControlFlow() [static], [constexpr]
Definition at line 4463 of file operations.h.
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h
/mnt/V8SourceCode/src/compiler/turboshaft/operations.cc