v8::internal::compiler::turboshaft::LoadFieldByIndexOp Struct Reference
#include <operations.h>
Public Member Functions
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
OpIndex object () const
OpIndex index () const
LoadFieldByIndexOp (OpIndex object, OpIndex index)
auto options () const
Static Public Attributes
static constexpr OpEffects effects
Additional Inherited Members
Detailed Description
Definition at line 5289 of file operations.h.
Constructor & Destructor Documentation
LoadFieldByIndexOp()
v8::internal::compiler::turboshaft::LoadFieldByIndexOp::LoadFieldByIndexOp (OpIndex object, OpIndex index) [inline]
Definition at line 5318 of file operations.h.
: Base(object, index) {}
Member Function Documentation
index()
OpIndex v8::internal::compiler::turboshaft::LoadFieldByIndexOp::index () const [inline]
Definition at line 5316 of file operations.h.
{ return Base::input(1); }
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::LoadFieldByIndexOp::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 5302 of file operations.h.
                                                              {
    return MaybeRepVector<MaybeRegisterRepresentation::Tagged(),
                          MaybeRegisterRepresentation::Word32()>();
  }
References v8::internal::compiler::turboshaft::MaybeRepVector(), v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::Tagged(), and v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::Word32().
object()
OpIndex v8::internal::compiler::turboshaft::LoadFieldByIndexOp::object () const [inline]
Definition at line 5308 of file operations.h.
{ return Base::input(0); }
options()
auto v8::internal::compiler::turboshaft::LoadFieldByIndexOp::options () const [inline]
Definition at line 5320 of file operations.h.
{ return std::tuple{}; }
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::LoadFieldByIndexOp::outputs_rep () const [inline]
Definition at line 5298 of file operations.h.
                                                               {
    return RepVector<RegisterRepresentation::Tagged()>();
  }
Member Data Documentation
effects
constexpr OpEffects v8::internal::compiler::turboshaft::LoadFieldByIndexOp::effects [static], [constexpr]
Initial value:
=
      OpEffects()
          
          .CanReadHeapMemory()
          
          .CanAllocateWithoutIdentity()
          
          .CanDependOnChecks()
Definition at line 5290 of file operations.h.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h