v8::internal::compiler::turboshaft::CompareMapsOp Struct Reference
#include <operations.h>
Public Member Functions
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
V< HeapObject > heap_object () const
OptionalV< Map > map () const
CompareMapsOp (V< HeapObject > heap_object, OptionalV< Map > map, ZoneRefSet< Map > maps)
auto options () const
void PrintOptions (std::ostream &os) const
template<typename Fn , typename Mapper >
auto Explode (Fn fn, Mapper &mapper) const
Static Public Member Functions
static CompareMapsOp & New (Graph *graph, V< HeapObject > heap_object, OptionalV< Map > map, ZoneRefSet< Map > maps)
Public Attributes
ZoneRefSet< Map > maps
Static Public Attributes
static constexpr OpEffects effects = OpEffects().CanReadHeapMemory()
Additional Inherited Members
Detailed Description
Definition at line 6135 of file operations.h.
Constructor & Destructor Documentation
CompareMapsOp()
v8::internal::compiler::turboshaft::CompareMapsOp::CompareMapsOp (V< HeapObject > heap_object, OptionalV< Map > map, ZoneRefSet< Map > maps) [inline]
Definition at line 6154 of file operations.h.
      : Base(1 + map.valid()), maps(std::move(maps)) {
    input(0) = heap_object;
    if (map.valid()) {
      input(1) = map.value();
    }
  }
References v8::internal::compiler::turboshaft::OptionalOpIndex::valid(), and v8::internal::compiler::turboshaft::OptionalV< T >::value().
Member Function Documentation
Explode()
template<typename Fn , typename Mapper >
auto v8::internal::compiler::turboshaft::CompareMapsOp::Explode (Fn fn, Mapper & mapper) const [inline]
Definition at line 6168 of file operations.h.
                                                      {
    return fn(mapper.Map(heap_object()), mapper.Map(map()), maps);
  }
heap_object()
V<HeapObject> v8::internal::compiler::turboshaft::CompareMapsOp::heap_object () const [inline]
Definition at line 6148 of file operations.h.
{ return Base::input<HeapObject>(0); }
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::CompareMapsOp::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 6143 of file operations.h.
                                                              {
    return MaybeRepVector<MaybeRegisterRepresentation::Tagged()>();
  }
map()
OptionalV<Map> v8::internal::compiler::turboshaft::CompareMapsOp::map () const [inline]
Definition at line 6150 of file operations.h.
                             {
    return input_count > 1 ? input<Map>(1) : OptionalV<Map>::Nullopt();
  }
References v8::internal::compiler::turboshaft::detail::input_count(), and v8::internal::compiler::turboshaft::OptionalV< T >::Nullopt().
New()
static CompareMapsOp& v8::internal::compiler::turboshaft::CompareMapsOp::New (Graph * graph, V< HeapObject > heap_object, OptionalV< Map > map, ZoneRefSet< Map > maps) [inline], [static]
Definition at line 6172 of file operations.h.
                                                                      {
    return Base::New(graph, 1 + map.valid(), heap_object, map, maps);
  }
References graph(), v8::internal::anonymous_namespace{intl-objects.cc}::New(), and v8::internal::compiler::turboshaft::OptionalOpIndex::valid().
options()
auto v8::internal::compiler::turboshaft::CompareMapsOp::options () const [inline]
Definition at line 6164 of file operations.h.
{ return std::tuple{maps}; }
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::CompareMapsOp::outputs_rep () const [inline]
Definition at line 6139 of file operations.h.
                                                               {
    return RepVector<RegisterRepresentation::Word32()>();
  }
PrintOptions()
void v8::internal::compiler::turboshaft::CompareMapsOp::PrintOptions (std::ostream & os) const
Definition at line 1563 of file operations.cc.
                                                     {
  os << "[";
  PrintMapSet(os, maps);
  os << "]";
}
References maps, and v8::internal::compiler::turboshaft::PrintMapSet().
Member Data Documentation
effects
constexpr OpEffects v8::internal::compiler::turboshaft::CompareMapsOp::effects = OpEffects().CanReadHeapMemory() [static], [constexpr]
Definition at line 6138 of file operations.h.
maps
ZoneRefSet<Map> v8::internal::compiler::turboshaft::CompareMapsOp::maps
Definition at line 6136 of file operations.h.
Referenced by PrintOptions().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h
/mnt/V8SourceCode/src/compiler/turboshaft/operations.cc