v8::internal::compiler::turboshaft::CallOp Struct Reference
#include <operations.h>
Public Member Functions
OpEffects Effects () const
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const RegisterRepresentation > results_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
bool HasFrameState () const
V< CallTarget > callee () const
OptionalV< FrameState > frame_state () const
base::Vector< const OpIndex > arguments () const
CallOp (V< CallTarget > callee, OptionalV< FrameState > frame_state, base::Vector< const OpIndex > arguments, const TSCallDescriptor *descriptor, OpEffects effects)
template<typename Fn , typename Mapper >
auto Explode (Fn fn, Mapper &mapper) const
V8_EXPORT_PRIVATE void Validate (const Graph &graph) const
auto options () const
size_t hash_value (HashingStrategy strategy=HashingStrategy::kDefault) const
void PrintOptions (std::ostream &os) const
Static Public Member Functions
static CallOp & New (Graph *graph, V< CallTarget > callee, OptionalV< FrameState > frame_state, base::Vector< const OpIndex > arguments, const TSCallDescriptor *descriptor, OpEffects effects)
Public Attributes
const TSCallDescriptor * descriptor
OpEffects callee_effects
Additional Inherited Members
Detailed Description
Definition at line 4069 of file operations.h.
Constructor & Destructor Documentation
CallOp()
v8::internal::compiler::turboshaft::CallOp::CallOp (V< CallTarget > callee, OptionalV< FrameState > frame_state, base::Vector< const OpIndex > arguments, const TSCallDescriptor * descriptor, OpEffects effects) [inline]
Definition at line 4121 of file operations.h.
      : Base(1 + frame_state.valid() + arguments.size()),
        descriptor(descriptor),
        callee_effects(effects) {
    base::Vector<OpIndex> inputs = this->inputs();
    inputs[0] = callee;
    if (frame_state.valid()) {
      inputs[1] = frame_state.value();
    }
    inputs.SubVector(1 + frame_state.valid(), inputs.size())
        .OverwriteWith(arguments);
  }
References v8::base::Vector< T >::size(), v8::base::Vector< T >::SubVector(), v8::internal::compiler::turboshaft::OptionalOpIndex::valid(), and v8::internal::compiler::turboshaft::OptionalV< T >::value().
Member Function Documentation
arguments()
base::Vector<const OpIndex> v8::internal::compiler::turboshaft::CallOp::arguments () const [inline]
Definition at line 4117 of file operations.h.
                                              {
    return inputs().SubVector(1 + HasFrameState(), input_count);
  }
References v8::internal::compiler::turboshaft::detail::input_count().
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphCall(), v8::internal::compiler::turboshaft::CallView::CallView(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessCall(), and v8::internal::compiler::InstructionSelector::VisitCall().
callee()
V<CallTarget> v8::internal::compiler::turboshaft::CallOp::callee () const [inline]
Definition at line 4112 of file operations.h.
{ return input<CallTarget>(0); }
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphCall(), v8::internal::compiler::turboshaft::CallView::CallView(), v8::internal::wasm::TurboshaftGraphBuildingInterface::IsArrayNewSegment(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessCall(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessCall(), Validate(), and v8::internal::compiler::InstructionSelector::VisitCall().
Effects()
OpEffects v8::internal::compiler::turboshaft::CallOp::Effects () const [inline]
Definition at line 4073 of file operations.h.
{ return callee_effects; }
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphCall(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessCall(), and v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessCall().
Explode()
template<typename Fn , typename Mapper >
auto v8::internal::compiler::turboshaft::CallOp::Explode (Fn fn, Mapper & mapper) const [inline]
Definition at line 4137 of file operations.h.
                                                      {
    V<CallTarget> mapped_callee = mapper.Map(callee());
    OptionalV<FrameState> mapped_frame_state = mapper.Map(frame_state());
    auto mapped_arguments = mapper.template Map<16>(arguments());
    return fn(mapped_callee, mapped_frame_state,
              base::VectorOf(mapped_arguments), descriptor, Effects());
  }
References v8::base::VectorOf().
frame_state()
OptionalV<FrameState> v8::internal::compiler::turboshaft::CallOp::frame_state () const [inline]
Definition at line 4113 of file operations.h.
                                            {
    return HasFrameState() ? input<FrameState>(1)
                           : OptionalV<FrameState>::Nullopt();
  }
References v8::internal::compiler::turboshaft::OptionalV< T >::Nullopt().
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphCall(), Validate(), and v8::internal::compiler::InstructionSelector::VisitCall().
HasFrameState()
bool v8::internal::compiler::turboshaft::CallOp::HasFrameState () const [inline]
Definition at line 4108 of file operations.h.
                             {
    return descriptor->descriptor->NeedsFrameState();
  }
References v8::internal::compiler::turboshaft::TSCallDescriptor::descriptor, and v8::internal::compiler::CallDescriptor::NeedsFrameState().
hash_value()
size_t v8::internal::compiler::turboshaft::CallOp::hash_value (HashingStrategy strategy = HashingStrategy::kDefault) const
Definition at line 2097 of file operations.cc.
                                                        {
  if (strategy == HashingStrategy::kMakeSnapshotStable) {
    // Destructure here to cause a compilation error in case `options` is
    // changed.
    auto [descriptor_value, effects] = options();
    return HashWithOptions(*descriptor, effects);
  } else {
    return Base::hash_value(strategy);
  }
}
References descriptor, v8::internal::compiler::turboshaft::OperationT< Derived >::hash_value(), v8::internal::compiler::turboshaft::OperationT< CallOp >::HashWithOptions(), v8::internal::compiler::turboshaft::kMakeSnapshotStable, and options().
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::CallOp::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 4081 of file operations.h.
                                                              {
    storage.resize(input_count);
    size_t i = 0;
    if (descriptor->descriptor->IsCodeObjectCall() ||
        descriptor->descriptor->IsJSFunctionCall() ||
        descriptor->descriptor->IsBuiltinPointerCall()) {
      storage[i++] = MaybeRegisterRepresentation::Tagged();
#ifdef V8_ENABLE_WEBASSEMBLY
    } else if (descriptor->descriptor->IsIndirectWasmFunctionCall()) {
      storage[i++] = MaybeRegisterRepresentation::Word32();
#endif
    } else {
      storage[i++] = MaybeRegisterRepresentation::WordPtr();
    }
    if (HasFrameState()) {
      storage[i++] = MaybeRegisterRepresentation::None();
    }
    for (auto rep : descriptor->in_reps) {
      // In JavaScript, parameters are optional.
      if (i >= input_count) break;
      storage[i++] = rep;
    }
    storage.resize(i);
    return base::VectorOf(storage);
  }
References v8::internal::compiler::turboshaft::TSCallDescriptor::descriptor, v8::internal::compiler::turboshaft::TSCallDescriptor::in_reps, v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::CallDescriptor::IsBuiltinPointerCall(), v8::internal::compiler::CallDescriptor::IsCodeObjectCall(), v8::internal::compiler::CallDescriptor::IsJSFunctionCall(), v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::None(), v8::internal::ZoneVector< T >::resize(), v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::Tagged(), v8::base::VectorOf(), v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::Word32(), and v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::WordPtr().
New()
static CallOp& v8::internal::compiler::turboshaft::CallOp::New (Graph * graph, V< CallTarget > callee, OptionalV< FrameState > frame_state, base::Vector< const OpIndex > arguments, const TSCallDescriptor * descriptor, OpEffects effects) [inline], [static]
Definition at line 4147 of file operations.h.
                                                                            {
    return Base::New(graph, 1 + frame_state.valid() + arguments.size(), callee,
                     frame_state, arguments, descriptor, effects);
  }
References graph(), v8::internal::anonymous_namespace{intl-objects.cc}::New(), v8::base::Vector< T >::size(), and v8::internal::compiler::turboshaft::OptionalOpIndex::valid().
options()
auto v8::internal::compiler::turboshaft::CallOp::options () const [inline]
Definition at line 4157 of file operations.h.
{ return std::tuple{descriptor, callee_effects}; }
Referenced by hash_value().
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::CallOp::outputs_rep () const [inline]
Definition at line 4076 of file operations.h.
{ return {}; }
PrintOptions()
void v8::internal::compiler::turboshaft::CallOp::PrintOptions (std::ostream & os) const
Definition at line 66 of file operations.cc.
                                              {
  os << '[' << *descriptor->descriptor << ']';
}
References v8::internal::compiler::turboshaft::TSCallDescriptor::descriptor, and descriptor.
results_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::CallOp::results_rep () const [inline]
Definition at line 4077 of file operations.h.
                                                               {
    return descriptor->out_reps;
  }
References v8::internal::compiler::turboshaft::TSCallDescriptor::out_reps.
Referenced by v8::internal::compiler::InstructionSelector::VisitCall().
Validate()
void v8::internal::compiler::turboshaft::CallOp::Validate (const Graph & graph) const
Definition at line 876 of file operations.cc.
                                              {
#ifdef DEBUG
  if (frame_state().valid()) {
    DCHECK(Get(graph, frame_state().value()).Is<FrameStateOp>());
  }
  if (!graph.has_broker()) return;
  if (const ConstantOp* target =
          graph.Get(callee()).TryCast<Opmask::kHeapConstant>()) {
    if (std::optional<Builtin> builtin =
            TryGetBuiltinId(target, graph.broker())) {
      CHECK_IMPLIES(!callee_effects.can_allocate,
                    !BuiltinCanAllocate(*builtin));
    }
  }
#endif
}
References v8::internal::BuiltinCanAllocate(), callee(), callee_effects, v8::internal::compiler::turboshaft::OpEffects::can_allocate, CHECK_IMPLIES, v8::internal::DCHECK(), frame_state(), v8::internal::compiler::turboshaft::Get(), graph(), v8::internal::compiler::turboshaft::TryGetBuiltinId(), and v8::internal::value.
Member Data Documentation
callee_effects
OpEffects v8::internal::compiler::turboshaft::CallOp::callee_effects
Definition at line 4071 of file operations.h.
Referenced by Validate().
descriptor
const TSCallDescriptor* v8::internal::compiler::turboshaft::CallOp::descriptor
Definition at line 4070 of file operations.h.
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphCall(), v8::internal::compiler::turboshaft::CallView::CallView(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::CheckPairOrPairOp(), hash_value(), PrintOptions(), and v8::internal::compiler::InstructionSelector::VisitCall().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h
/mnt/V8SourceCode/src/compiler/turboshaft/operations.cc