v8::internal::compiler::turboshaft::NewConsStringOp Struct Reference
#include <operations.h>
Public Member Functions
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
V< Word32 > length () const
V< String > first () const
V< String > second () const
NewConsStringOp (V< Word32 > length, V< String > first, V< String > second)
auto options () const
Static Public Attributes
static constexpr OpEffects effects
Additional Inherited Members
Detailed Description
Definition at line 5190 of file operations.h.
Constructor & Destructor Documentation
NewConsStringOp()
v8::internal::compiler::turboshaft::NewConsStringOp::NewConsStringOp (V< Word32 > length, V< String > first, V< String > second) [inline]
Definition at line 5214 of file operations.h.
      : Base(length, first, second) {}
Member Function Documentation
first()
V<String> v8::internal::compiler::turboshaft::NewConsStringOp::first () const [inline]
Definition at line 5211 of file operations.h.
{ return Base::input<String>(1); }
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::NewConsStringOp::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 5203 of file operations.h.
                                                              {
    return MaybeRepVector<MaybeRegisterRepresentation::Word32(),
                          MaybeRegisterRepresentation::Tagged(),
                          MaybeRegisterRepresentation::Tagged()>();
  }
References v8::internal::compiler::turboshaft::MaybeRepVector(), v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::Tagged(), and v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::Word32().
length()
V<Word32> v8::internal::compiler::turboshaft::NewConsStringOp::length () const [inline]
Definition at line 5210 of file operations.h.
{ return Base::input<Word32>(0); }
options()
auto v8::internal::compiler::turboshaft::NewConsStringOp::options () const [inline]
Definition at line 5217 of file operations.h.
{ return std::tuple{}; }
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::NewConsStringOp::outputs_rep () const [inline]
Definition at line 5199 of file operations.h.
                                                               {
    return RepVector<RegisterRepresentation::Tagged()>();
  }
second()
V<String> v8::internal::compiler::turboshaft::NewConsStringOp::second () const [inline]
Definition at line 5212 of file operations.h.
{ return Base::input<String>(2); }
Member Data Documentation
effects
constexpr OpEffects v8::internal::compiler::turboshaft::NewConsStringOp::effects [static], [constexpr]
Initial value:
=
      OpEffects()
          
          .CanAllocateWithoutIdentity()
          
          
          
          .CanDependOnChecks()
Definition at line 5191 of file operations.h.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h