v8::internal::compiler::anonymous_namespace{jump-threading.cc}::GapJumpRecord Struct Reference
Classes
struct Record
struct RpoNumberHash
Public Member Functions
GapJumpRecord (Zone *zone)
bool CanForwardGapJump (Instruction *instr, RpoNumber instr_block, RpoNumber target_block, RpoNumber *forward_to)
Public Attributes
Zone * zone_
ZoneUnorderedMap< RpoNumber, ZoneVector< Record >, RpoNumberHash > gap_jump_records_
Detailed Description
Definition at line 58 of file jump-threading.cc.
Constructor & Destructor Documentation
GapJumpRecord()
v8::internal::compiler::anonymous_namespace{jump-threading.cc}::GapJumpRecord::GapJumpRecord (Zone * zone) [inline], [explicit]
Definition at line 59 of file jump-threading.cc.
: zone_(zone), gap_jump_records_(zone) {}
Member Function Documentation
CanForwardGapJump()
bool v8::internal::compiler::anonymous_namespace{jump-threading.cc}::GapJumpRecord::CanForwardGapJump (Instruction * instr, RpoNumber instr_block, RpoNumber target_block, RpoNumber * forward_to) [inline]
Definition at line 72 of file jump-threading.cc.
                                                                        {
    DCHECK_EQ(instr->arch_opcode(), kArchJmp);
    bool can_forward = false;
    auto search = gap_jump_records_.find(target_block);
    if (search != gap_jump_records_.end()) {
      for (Record& record : search->second) {
        Instruction* record_instr = record.instr;
        DCHECK_EQ(record_instr->arch_opcode(), kArchJmp);
        bool is_same_instr = true;
        for (int i = Instruction::FIRST_GAP_POSITION;
             i <= Instruction::LAST_GAP_POSITION; i++) {
          Instruction::GapPosition pos =
              static_cast<Instruction::GapPosition>(i);
          ParallelMove* record_move = record_instr->GetParallelMove(pos);
          ParallelMove* instr_move = instr->GetParallelMove(pos);
          if (record_move == nullptr && instr_move == nullptr) continue;
          if (((record_move == nullptr) != (instr_move == nullptr)) ||
              !record_move->Equals(*instr_move)) {
            is_same_instr = false;
            break;
          }
        }
        if (is_same_instr) {
          // Found an instruction same as the recorded one.
          *forward_to = record.block;
          can_forward = true;
          break;
        }
      }
      if (!can_forward) {
        // No recorded instruction has been found for this target block,
        // so create a new record with the given instruction.
        search->second.push_back({instr_block, instr});
      }
    } else {
      // This is the first explored gap jump to target block.
      auto ins =
          gap_jump_records_.insert({target_block, ZoneVector<Record>(zone_)});
      if (ins.second) {
        ins.first->second.reserve(4);
        ins.first->second.push_back({instr_block, instr});
      }
    }
    return can_forward;
  }
References v8::internal::compiler::Instruction::arch_opcode(), v8::internal::compiler::anonymous_namespace{jump-threading.cc}::GapJumpRecord::Record::block, DCHECK_EQ, v8::internal::compiler::ParallelMove::Equals(), v8::internal::compiler::Instruction::FIRST_GAP_POSITION, v8::internal::compiler::Instruction::GetParallelMove(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::anonymous_namespace{jump-threading.cc}::GapJumpRecord::Record::instr, v8::internal::compiler::Instruction::LAST_GAP_POSITION, and v8::internal::anonymous_namespace{simd.cc}::search().
Member Data Documentation
gap_jump_records_
ZoneUnorderedMap<RpoNumber, ZoneVector<Record>, RpoNumberHash> v8::internal::compiler::anonymous_namespace{jump-threading.cc}::GapJumpRecord::gap_jump_records_
Definition at line 121 of file jump-threading.cc.
zone_
Zone* v8::internal::compiler::anonymous_namespace{jump-threading.cc}::GapJumpRecord::zone_
Definition at line 119 of file jump-threading.cc.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/jump-threading.cc