v8::internal::ro::EncodedExternalReference Struct Reference
#include <read-only-serializer-deserializer.h>
Public Member Functions
uint32_t ToUint32 () const
EncodedExternalReference (bool is_api_reference, uint32_t index)
Static Public Member Functions
static EncodedExternalReference FromUint32 (uint32_t v)
Public Attributes
int is_api_reference: kIsApiReferenceBits
int index: kIndexBits
Static Public Attributes
static constexpr int kIsApiReferenceBits = 1
static constexpr int kIndexBits = 31
static constexpr int kSize = kUInt32Size
Detailed Description
Definition at line 123 of file read-only-serializer-deserializer.h.
Constructor & Destructor Documentation
EncodedExternalReference()
v8::internal::ro::EncodedExternalReference::EncodedExternalReference (bool is_api_reference, uint32_t index) [inline]
Definition at line 139 of file read-only-serializer-deserializer.h.
      : is_api_reference(is_api_reference), index(index) {}
Member Function Documentation
FromUint32()
static EncodedExternalReference v8::internal::ro::EncodedExternalReference::FromUint32 (uint32_t v) [inline], [static]
Definition at line 132 of file read-only-serializer-deserializer.h.
                                                         {
    return *reinterpret_cast<EncodedExternalReference*>(&v);
  }
Referenced by v8::internal::ObjectPostProcessor::DecodeExternalPointerSlot(), v8::internal::ObjectPostProcessor::DecodeLazilyInitializedExternalPointerSlot(), and v8::internal::anonymous_namespace{read-only-serializer.cc}::EncodeRelocationsVisitor::VisitExternalPointer().
ToUint32()
uint32_t v8::internal::ro::EncodedExternalReference::ToUint32 () const [inline]
Definition at line 128 of file read-only-serializer-deserializer.h.
                            {
    static_assert(kSize == kUInt32Size);
    return *reinterpret_cast<const uint32_t*>(this);
  }
References kSize, and v8::internal::kUInt32Size.
Member Data Documentation
index
int v8::internal::ro::EncodedExternalReference::index
Definition at line 143 of file read-only-serializer-deserializer.h.
is_api_reference
int v8::internal::ro::EncodedExternalReference::is_api_reference
Definition at line 142 of file read-only-serializer-deserializer.h.
kIndexBits
constexpr int v8::internal::ro::EncodedExternalReference::kIndexBits = 31 [static], [constexpr]
Definition at line 125 of file read-only-serializer-deserializer.h.
Referenced by v8::internal::anonymous_namespace{read-only-serializer.cc}::ObjectPreProcessor::EncodeExternalPointerSlot().
kIsApiReferenceBits
constexpr int v8::internal::ro::EncodedExternalReference::kIsApiReferenceBits = 1 [static], [constexpr]
Definition at line 124 of file read-only-serializer-deserializer.h.
kSize
constexpr int v8::internal::ro::EncodedExternalReference::kSize = kUInt32Size [static], [constexpr]
Definition at line 126 of file read-only-serializer-deserializer.h.
Referenced by ToUint32().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/snapshot/read-only-serializer-deserializer.h