v8::internal::wasm::ControlBase< Value, ValidationTag > Struct Template Reference
#include <function-body-decoder-impl.h>
Public Member Functions
MOVE_ONLY_NO_DEFAULT_CONSTRUCTOR (ControlBase)
ControlBase (Zone *zone, ControlKind kind, uint32_t stack_depth, uint32_t init_stack_depth, const uint8_t *pc, Reachability reachability)
bool reachable () const
bool unreachable () const
Reachability innerReachability () const
bool is_if () const
bool is_onearmed_if () const
bool is_if_else () const
bool is_block () const
bool is_loop () const
bool is_incomplete_try () const
bool is_try_catch () const
bool is_try_catchall () const
bool is_try () const
bool is_try_table ()
Merge< Value > * br_merge ()
Public Attributes
ControlKind kind = kControlBlock
Reachability reachability = kReachable
base::Vector< CatchCase > catch_cases
uint32_t stack_depth = 0
uint32_t init_stack_depth = 0
int32_t previous_catch = -1
Merge< Value > start_merge
Merge< Value > end_merge
bool might_throw = false
Detailed Description
template<typename Value, typename ValidationTag>
struct v8::internal::wasm::ControlBase< Value, ValidationTag >
Definition at line 1283 of file function-body-decoder-impl.h.
Constructor & Destructor Documentation
ControlBase()
template<typename Value , typename ValidationTag >
v8::internal::wasm::ControlBase< Value, ValidationTag >::ControlBase (Zone * zone, ControlKind kind, uint32_t stack_depth, uint32_t init_stack_depth, const uint8_t * pc, Reachability reachability) [inline]
Definition at line 1304 of file function-body-decoder-impl.h.
      : PcForErrors<ValidationTag::validate>(pc),
        kind(kind),
        reachability(reachability),
        stack_depth(stack_depth),
        init_stack_depth(init_stack_depth),
        start_merge(reachability == kReachable) {}
Member Function Documentation
br_merge()
template<typename Value , typename ValidationTag >
Merge<Value>* v8::internal::wasm::ControlBase< Value, ValidationTag >::br_merge () [inline]
Definition at line 1341 of file function-body-decoder-impl.h.
                           {
    return is_loop() ? &this->start_merge : &this->end_merge;
  }
References v8::internal::wasm::ControlBase< Value, ValidationTag >::end_merge, v8::internal::wasm::ControlBase< Value, ValidationTag >::is_loop(), and v8::internal::wasm::ControlBase< Value, ValidationTag >::start_merge.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::Block(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BrImpl(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::FallThruTo(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::FinishTry(), v8::internal::wasm::TurboshaftGraphBuildingInterface::PopControl(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::Try().
innerReachability()
template<typename Value , typename ValidationTag >
Reachability v8::internal::wasm::ControlBase< Value, ValidationTag >::innerReachability () const [inline]
Definition at line 1324 of file function-body-decoder-impl.h.
                                         {
    return reachability == kReachable ? kReachable : kSpecOnlyReachable;
  }
References v8::internal::wasm::kReachable, v8::internal::wasm::kSpecOnlyReachable, and v8::internal::wasm::ControlBase< Value, ValidationTag >::reachability.
is_block()
template<typename Value , typename ValidationTag >
bool v8::internal::wasm::ControlBase< Value, ValidationTag >::is_block () const [inline]
Definition at line 1331 of file function-body-decoder-impl.h.
{ return kind == kControlBlock; }
References v8::internal::wasm::kControlBlock, and v8::internal::wasm::ControlBase< Value, ValidationTag >::kind.
is_if()
template<typename Value , typename ValidationTag >
bool v8::internal::wasm::ControlBase< Value, ValidationTag >::is_if () const [inline]
Definition at line 1328 of file function-body-decoder-impl.h.
{ return is_onearmed_if() || is_if_else(); }
References v8::internal::wasm::ControlBase< Value, ValidationTag >::is_if_else(), and v8::internal::wasm::ControlBase< Value, ValidationTag >::is_onearmed_if().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::If().
is_if_else()
template<typename Value , typename ValidationTag >
bool v8::internal::wasm::ControlBase< Value, ValidationTag >::is_if_else () const [inline]
Definition at line 1330 of file function-body-decoder-impl.h.
{ return kind == kControlIfElse; }
References v8::internal::wasm::kControlIfElse, and v8::internal::wasm::ControlBase< Value, ValidationTag >::kind.
Referenced by v8::internal::wasm::ControlBase< Value, ValidationTag >::is_if().
is_incomplete_try()
template<typename Value , typename ValidationTag >
bool v8::internal::wasm::ControlBase< Value, ValidationTag >::is_incomplete_try () const [inline]
Definition at line 1333 of file function-body-decoder-impl.h.
{ return kind == kControlTry; }
References v8::internal::wasm::kControlTry, and v8::internal::wasm::ControlBase< Value, ValidationTag >::kind.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::Delegate(), and v8::internal::wasm::ControlBase< Value, ValidationTag >::is_try().
is_loop()
template<typename Value , typename ValidationTag >
bool v8::internal::wasm::ControlBase< Value, ValidationTag >::is_loop () const [inline]
Definition at line 1332 of file function-body-decoder-impl.h.
{ return kind == kControlLoop; }
References v8::internal::wasm::kControlLoop, and v8::internal::wasm::ControlBase< Value, ValidationTag >::kind.
Referenced by v8::internal::wasm::ControlBase< Value, ValidationTag >::br_merge(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BrImpl(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::PopControl().
is_onearmed_if()
template<typename Value , typename ValidationTag >
bool v8::internal::wasm::ControlBase< Value, ValidationTag >::is_onearmed_if () const [inline]
Definition at line 1329 of file function-body-decoder-impl.h.
{ return kind == kControlIf; }
References v8::internal::wasm::kControlIf, and v8::internal::wasm::ControlBase< Value, ValidationTag >::kind.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::FinishOneArmedIf(), v8::internal::wasm::ControlBase< Value, ValidationTag >::is_if(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::PopControl().
is_try()
template<typename Value , typename ValidationTag >
bool v8::internal::wasm::ControlBase< Value, ValidationTag >::is_try () const [inline]
Definition at line 1336 of file function-body-decoder-impl.h.
                      {
    return is_incomplete_try() || is_try_catch() || is_try_catchall();
  }
References v8::internal::wasm::ControlBase< Value, ValidationTag >::is_incomplete_try(), v8::internal::wasm::ControlBase< Value, ValidationTag >::is_try_catch(), and v8::internal::wasm::ControlBase< Value, ValidationTag >::is_try_catchall().
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::Delegate().
is_try_catch()
template<typename Value , typename ValidationTag >
bool v8::internal::wasm::ControlBase< Value, ValidationTag >::is_try_catch () const [inline]
Definition at line 1334 of file function-body-decoder-impl.h.
{ return kind == kControlTryCatch; }
References v8::internal::wasm::kControlTryCatch, and v8::internal::wasm::ControlBase< Value, ValidationTag >::kind.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CatchAll(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CatchAll(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CatchException(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::FinishTry(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GetCurrentDebugSideTableEntries(), v8::internal::wasm::ControlBase< Value, ValidationTag >::is_try(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::PopControl().
is_try_catchall()
template<typename Value , typename ValidationTag >
bool v8::internal::wasm::ControlBase< Value, ValidationTag >::is_try_catchall () const [inline]
Definition at line 1335 of file function-body-decoder-impl.h.
{ return kind == kControlTryCatchAll; }
References v8::internal::wasm::kControlTryCatchAll, and v8::internal::wasm::ControlBase< Value, ValidationTag >::kind.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CatchAll(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CatchAll(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::FallThruTo(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::FinishTry(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GetCurrentDebugSideTableEntries(), v8::internal::wasm::ControlBase< Value, ValidationTag >::is_try(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::PopControl().
is_try_table()
template<typename Value , typename ValidationTag >
bool v8::internal::wasm::ControlBase< Value, ValidationTag >::is_try_table () [inline]
Definition at line 1339 of file function-body-decoder-impl.h.
{ return kind == kControlTryTable; }
References v8::internal::wasm::kControlTryTable, and v8::internal::wasm::ControlBase< Value, ValidationTag >::kind.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CatchCase(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::FinishTry(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::PopControl().
MOVE_ONLY_NO_DEFAULT_CONSTRUCTOR()
template<typename Value , typename ValidationTag >
v8::internal::wasm::ControlBase< Value, ValidationTag >::MOVE_ONLY_NO_DEFAULT_CONSTRUCTOR (ControlBase< Value, ValidationTag >)
reachable()
template<typename Value , typename ValidationTag >
bool v8::internal::wasm::ControlBase< Value, ValidationTag >::reachable () const [inline]
Definition at line 1315 of file function-body-decoder-impl.h.
{ return reachability == kReachable; }
References v8::internal::wasm::kReachable, and v8::internal::wasm::ControlBase< Value, ValidationTag >::reachability.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::Else(), v8::internal::wasm::TurboshaftGraphBuildingInterface::Else(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::FinishOneArmedIf(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::FinishTry(), v8::internal::wasm::TurboshaftGraphBuildingInterface::PopControl(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::PopControl().
unreachable()
template<typename Value , typename ValidationTag >
bool v8::internal::wasm::ControlBase< Value, ValidationTag >::unreachable () const [inline]
Definition at line 1321 of file function-body-decoder-impl.h.
{ return reachability == kUnreachable; }
References v8::internal::wasm::kUnreachable, and v8::internal::wasm::ControlBase< Value, ValidationTag >::reachability.
Member Data Documentation
catch_cases
template<typename Value , typename ValidationTag >
base::Vector<CatchCase> v8::internal::wasm::ControlBase< Value, ValidationTag >::catch_cases
Definition at line 1288 of file function-body-decoder-impl.h.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CatchCase(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::CatchCase().
end_merge
template<typename Value , typename ValidationTag >
Merge<Value> v8::internal::wasm::ControlBase< Value, ValidationTag >::end_merge
Definition at line 1298 of file function-body-decoder-impl.h.
Referenced by v8::internal::wasm::ControlBase< Value, ValidationTag >::br_merge(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::Else(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::FallThruTo(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::FinishOneArmedIf(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::FinishTry(), v8::internal::wasm::TurboshaftGraphBuildingInterface::If(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::PopControl().
init_stack_depth
template<typename Value , typename ValidationTag >
uint32_t v8::internal::wasm::ControlBase< Value, ValidationTag >::init_stack_depth = 0
Definition at line 1291 of file function-body-decoder-impl.h.
kind
template<typename Value , typename ValidationTag >
ControlKind v8::internal::wasm::ControlBase< Value, ValidationTag >::kind = kControlBlock
Definition at line 1284 of file function-body-decoder-impl.h.
Referenced by v8::internal::wasm::ControlBase< Value, ValidationTag >::is_block(), v8::internal::wasm::ControlBase< Value, ValidationTag >::is_if_else(), v8::internal::wasm::ControlBase< Value, ValidationTag >::is_incomplete_try(), v8::internal::wasm::ControlBase< Value, ValidationTag >::is_loop(), v8::internal::wasm::ControlBase< Value, ValidationTag >::is_onearmed_if(), v8::internal::wasm::ControlBase< Value, ValidationTag >::is_try_catch(), v8::internal::wasm::ControlBase< Value, ValidationTag >::is_try_catchall(), v8::internal::wasm::ControlBase< Value, ValidationTag >::is_try_table(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::PopControl().
might_throw
template<typename Value , typename ValidationTag >
bool v8::internal::wasm::ControlBase< Value, ValidationTag >::might_throw = false
Definition at line 1300 of file function-body-decoder-impl.h.
previous_catch
template<typename Value , typename ValidationTag >
int32_t v8::internal::wasm::ControlBase< Value, ValidationTag >::previous_catch = -1
Definition at line 1293 of file function-body-decoder-impl.h.
reachability
template<typename Value , typename ValidationTag >
Reachability v8::internal::wasm::ControlBase< Value, ValidationTag >::reachability = kReachable
Definition at line 1285 of file function-body-decoder-impl.h.
Referenced by v8::internal::wasm::ControlBase< Value, ValidationTag >::innerReachability(), v8::internal::wasm::ControlBase< Value, ValidationTag >::reachable(), and v8::internal::wasm::ControlBase< Value, ValidationTag >::unreachable().
stack_depth
template<typename Value , typename ValidationTag >
uint32_t v8::internal::wasm::ControlBase< Value, ValidationTag >::stack_depth = 0
Definition at line 1290 of file function-body-decoder-impl.h.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BrImpl(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::Delegate(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::Else(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitLandingPad(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::FallThruTo(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::FinishOneArmedIf(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::FinishTry(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GetCurrentDebugSideTableEntries().
start_merge
template<typename Value , typename ValidationTag >
Merge<Value> v8::internal::wasm::ControlBase< Value, ValidationTag >::start_merge
Definition at line 1297 of file function-body-decoder-impl.h.
Referenced by v8::internal::wasm::ControlBase< Value, ValidationTag >::br_merge(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::FinishOneArmedIf(), v8::internal::wasm::TurboshaftGraphBuildingInterface::Loop(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::Loop(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::PopControl().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/wasm/function-body-decoder-impl.h