v8::internal::compiler::EarlyOptimizationPhase Struct Reference
Public Member Functions
void Run (TFPipelineData *data, Zone *temp_zone)
Detailed Description
Definition at line 1249 of file pipeline.cc.
Member Function Documentation
Run()
void v8::internal::compiler::EarlyOptimizationPhase::Run (TFPipelineData * data, Zone * temp_zone) [inline]
Definition at line 1252 of file pipeline.cc.
                                                  {
    GraphReducer graph_reducer(
        temp_zone, data->graph(), &data->info()->tick_counter(), data->broker(),
        data->jsgraph()->Dead(), data->observe_node_manager());
    DeadCodeElimination dead_code_elimination(&graph_reducer, data->graph(),
                                              data->common(), temp_zone);
    SimplifiedOperatorReducer simple_reducer(&graph_reducer, data->jsgraph(),
                                             data->broker(),
                                             BranchSemantics::kMachine);
    RedundancyElimination redundancy_elimination(&graph_reducer,
                                                 data->jsgraph(), temp_zone);
    ValueNumberingReducer value_numbering(temp_zone, data->graph()->zone());
    MachineOperatorReducer machine_reducer(
        &graph_reducer, data->jsgraph(),
        MachineOperatorReducer::kPropagateSignallingNan);
    CommonOperatorReducer common_reducer(
        &graph_reducer, data->graph(), data->broker(), data->common(),
        data->machine(), temp_zone, BranchSemantics::kMachine);
    AddReducer(data, &graph_reducer, &dead_code_elimination);
    AddReducer(data, &graph_reducer, &simple_reducer);
    AddReducer(data, &graph_reducer, &redundancy_elimination);
    AddReducer(data, &graph_reducer, &machine_reducer);
    AddReducer(data, &graph_reducer, &common_reducer);
    AddReducer(data, &graph_reducer, &value_numbering);
    graph_reducer.ReduceGraph();
  }
References v8::internal::compiler::anonymous_namespace{pipeline.cc}::AddReducer(), v8::internal::compiler::GraphReducer::graph(), v8::internal::compiler::kMachine, v8::internal::compiler::MachineOperatorReducer::kPropagateSignallingNan, and v8::internal::compiler::GraphReducer::ReduceGraph().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/pipeline.cc