v8::internal::anonymous_namespace{unicode-decoder.cc}::DecoderTraits< Utf8Decoder > Struct Reference
Public Types
using DfaDecoder = Utf8DfaDecoder
Static Public Member Functions
static bool IsInvalidSurrogatePair (uint32_t lead, uint32_t trail)
Static Public Attributes
static const bool kAllowIncompleteSequences = true
Detailed Description
Definition at line 22 of file unicode-decoder.cc.
Member Typedef Documentation
DfaDecoder
using v8::internal::anonymous_namespace{unicode-decoder.cc}::DecoderTraits< Utf8Decoder >::DfaDecoder = Utf8DfaDecoder
Definition at line 31 of file unicode-decoder.cc.
Member Function Documentation
IsInvalidSurrogatePair()
static bool v8::internal::anonymous_namespace{unicode-decoder.cc}::DecoderTraits< Utf8Decoder >::IsInvalidSurrogatePair (uint32_t lead, uint32_t trail) [inline], [static]
Definition at line 23 of file unicode-decoder.cc.
                                                                    {
    // The DfaDecoder will only ever decode Unicode scalar values, and all
    // sequences of USVs are valid.
    DCHECK(!unibrow::Utf16::IsLeadSurrogate(trail));
    DCHECK(!unibrow::Utf16::IsTrailSurrogate(trail));
    return false;
  }
References v8::internal::DCHECK(), unibrow::Utf16::IsLeadSurrogate(), and unibrow::Utf16::IsTrailSurrogate().
Member Data Documentation
kAllowIncompleteSequences
const bool v8::internal::anonymous_namespace{unicode-decoder.cc}::DecoderTraits< Utf8Decoder >::kAllowIncompleteSequences = true [static]
Definition at line 30 of file unicode-decoder.cc.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/strings/unicode-decoder.cc