v8::internal::compiler::turboshaft::AtomicWord32PairOp Struct Reference
#include <operations.h>
Public Types
enum class Kind : uint8_t {
kAdd
, kSub
, kAnd
, kOr
,
kXor
, kExchange
, kCompareExchange
, kLoad
,
kStore
 }
Public Member Functions
OpEffects Effects () const
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
V< WordPtr > base () const
OptionalV< WordPtr > index () const
OptionalV< Word32 > value_low () const
OptionalV< Word32 > value_high () const
OptionalV< Word32 > expected_low () const
OptionalV< Word32 > expected_high () const
AtomicWord32PairOp (V< WordPtr > base, OptionalV< WordPtr > index, OptionalV< Word32 > value_low, OptionalV< Word32 > value_high, OptionalV< Word32 > expected_low, OptionalV< Word32 > expected_high, Kind kind, int32_t offset)
template<typename Fn , typename Mapper >
auto Explode (Fn fn, Mapper &mapper) const
bool HasIndex () const
void PrintInputs (std::ostream &os, const std::string &op_index_prefix) const
void PrintOptions (std::ostream &os) const
auto options () const
Static Public Member Functions
static Kind KindFromBinOp (AtomicRMWOp::BinOp bin_op)
static constexpr size_t InputCount (Kind kind, bool has_index)
static AtomicWord32PairOp & New (Graph *graph, V< WordPtr > base, OptionalV< WordPtr > index, OptionalV< Word32 > value_low, OptionalV< Word32 > value_high, OptionalV< Word32 > expected_low, OptionalV< Word32 > expected_high, Kind kind, int32_t offset)
Public Attributes
Kind kind
int32_t offset
Additional Inherited Members
Detailed Description
Definition at line 3192 of file operations.h.
Member Enumeration Documentation
Kind
enum v8::internal::compiler::turboshaft::AtomicWord32PairOp::Kind : uint8_t [strong]
Enumerator
kAdd
kSub
kAnd
kOr
kXor
kExchange
kCompareExchange
kLoad
kStore
Definition at line 3193 of file operations.h.
                  : uint8_t {
    kAdd,
    kSub,
    kAnd,
    kOr,
    kXor,
    kExchange,
    kCompareExchange,
    kLoad,
    kStore
  };
Constructor & Destructor Documentation
AtomicWord32PairOp()
v8::internal::compiler::turboshaft::AtomicWord32PairOp::AtomicWord32PairOp (V< WordPtr > base, OptionalV< WordPtr > index, OptionalV< Word32 > value_low, OptionalV< Word32 > value_high, OptionalV< Word32 > expected_low, OptionalV< Word32 > expected_high, Kind kind, int32_t offset) [inline]
Definition at line 3287 of file operations.h.
      : Base(InputCount(kind, index.has_value())), kind(kind), offset(offset) {
    DCHECK_EQ(value_low.valid(), value_high.valid());
    DCHECK_EQ(expected_low.valid(), expected_high.valid());
    DCHECK_EQ(kind == Kind::kCompareExchange, expected_low.valid());
    DCHECK_EQ(kind != Kind::kLoad, value_low.valid());
    const bool has_index = index.has_value();
    DCHECK_EQ(has_index, HasIndex());
    input(0) = base;
    if (has_index) input(1) = index.value();
    if (kind != Kind::kLoad) {
      input(1 + has_index) = value_low.value();
      input(2 + has_index) = value_high.value();
      if (kind == Kind::kCompareExchange) {
        input(3 + has_index) = expected_low.value();
        input(4 + has_index) = expected_high.value();
      }
    }
  }
References DCHECK_EQ, v8::internal::index, v8::internal::compiler::turboshaft::OptionalOpIndex::valid(), and v8::internal::compiler::turboshaft::OptionalV< T >::value().
Member Function Documentation
base()
V<WordPtr> v8::internal::compiler::turboshaft::AtomicWord32PairOp::base () const [inline]
Definition at line 3265 of file operations.h.
{ return input<WordPtr>(0); }
Referenced by PrintInputs(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitPairAtomicBinOp(), and v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitPairAtomicBinOp().
Effects()
OpEffects v8::internal::compiler::turboshaft::AtomicWord32PairOp::Effects () const [inline]
Definition at line 3227 of file operations.h.
                            {
    OpEffects effects = OpEffects().CanDependOnChecks();
    if (kind == Kind::kStore) {
      return effects.CanWriteMemory();
    }
    // Atomic loads are marked as "can write memory" as they should not be
    // reordered with other loads. Secondly, they may not be removed even if
    // unused as they might make writes of other threads visible.
    return effects.CanReadMemory().CanWriteMemory();
  }
References v8::internal::compiler::turboshaft::OpEffects::CanDependOnChecks(), v8::internal::compiler::turboshaft::OpEffects::CanReadMemory(), and v8::internal::compiler::turboshaft::OpEffects::CanWriteMemory().
expected_high()
OptionalV<Word32> v8::internal::compiler::turboshaft::AtomicWord32PairOp::expected_high () const [inline]
Definition at line 3281 of file operations.h.
                                          {
    return kind == Kind::kCompareExchange ? input<Word32>(4 + HasIndex())
                                          : V<Word32>::Invalid();
  }
References v8::internal::compiler::turboshaft::V< T >::Invalid().
expected_low()
OptionalV<Word32> v8::internal::compiler::turboshaft::AtomicWord32PairOp::expected_low () const [inline]
Definition at line 3277 of file operations.h.
                                         {
    return kind == Kind::kCompareExchange ? input<Word32>(3 + HasIndex())
                                          : V<Word32>::Invalid();
  }
References v8::internal::compiler::turboshaft::V< T >::Invalid().
Explode()
template<typename Fn , typename Mapper >
auto v8::internal::compiler::turboshaft::AtomicWord32PairOp::Explode (Fn fn, Mapper & mapper) const [inline]
Definition at line 3313 of file operations.h.
                                                      {
    return fn(mapper.Map(base()), mapper.Map(index()), mapper.Map(value_low()),
              mapper.Map(value_high()), mapper.Map(expected_low()),
              mapper.Map(expected_high()), kind, offset);
  }
References v8::internal::index.
HasIndex()
bool v8::internal::compiler::turboshaft::AtomicWord32PairOp::HasIndex () const [inline]
Definition at line 3336 of file operations.h.
{ return input_count == InputCount(kind, true); }
References v8::internal::compiler::turboshaft::detail::input_count().
index()
OptionalV<WordPtr> v8::internal::compiler::turboshaft::AtomicWord32PairOp::index () const [inline]
Definition at line 3266 of file operations.h.
                                   {
    return HasIndex() ? input<WordPtr>(1) : V<WordPtr>::Invalid();
  }
References v8::internal::compiler::turboshaft::V< T >::Invalid().
Referenced by PrintInputs(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitPairAtomicBinOp(), and v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitPairAtomicBinOp().
InputCount()
static constexpr size_t v8::internal::compiler::turboshaft::AtomicWord32PairOp::InputCount (Kind kind, bool has_index) [inline], [static], [constexpr]
Definition at line 3319 of file operations.h.
                                                                {
    switch (kind) {
      case Kind::kLoad:
        return 1 + has_index; // base, index?
      case Kind::kAdd:
      case Kind::kSub:
      case Kind::kAnd:
      case Kind::kOr:
      case Kind::kXor:
      case Kind::kExchange:
      case Kind::kStore:
        return 3 + has_index; // base, index?, value_low, value_high
      case Kind::kCompareExchange:
        return 5 + has_index; // base, index?, value_low, value_high,
                               // expected_low, expected_high
    }
  }
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::AtomicWord32PairOp::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 3243 of file operations.h.
                                                              {
    storage.resize(input_count);
    const bool has_index = HasIndex();
    storage[0] = RegisterRepresentation::WordPtr(); // base
    if (has_index) {
      storage[1] = RegisterRepresentation::WordPtr(); // index
    }
    if (kind != Kind::kLoad) {
      storage[1 + has_index] = RegisterRepresentation::Word32(); // value_low
      storage[2 + has_index] = RegisterRepresentation::Word32(); // value_high
      if (kind == Kind::kCompareExchange) {
        storage[3 + has_index] =
            RegisterRepresentation::Word32(); // expected_low
        storage[4 + has_index] =
            RegisterRepresentation::Word32(); // expected_high
      }
    }
    return base::VectorOf(storage);
  }
References v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::ZoneVector< T >::resize(), v8::base::VectorOf(), v8::internal::compiler::turboshaft::RegisterRepresentation::Word32(), and v8::internal::compiler::turboshaft::RegisterRepresentation::WordPtr().
KindFromBinOp()
static Kind v8::internal::compiler::turboshaft::AtomicWord32PairOp::KindFromBinOp (AtomicRMWOp::BinOp bin_op) [inline], [static]
Definition at line 3208 of file operations.h.
                                                     {
    switch (bin_op) {
      case AtomicRMWOp::BinOp::kAdd:
        return Kind::kAdd;
      case AtomicRMWOp::BinOp::kSub:
        return Kind::kSub;
      case AtomicRMWOp::BinOp::kAnd:
        return Kind::kAnd;
      case AtomicRMWOp::BinOp::kOr:
        return Kind::kOr;
      case AtomicRMWOp::BinOp::kXor:
        return Kind::kXor;
      case AtomicRMWOp::BinOp::kExchange:
        return Kind::kExchange;
      case AtomicRMWOp::BinOp::kCompareExchange:
        return Kind::kCompareExchange;
    }
  }
Referenced by v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::AtomicWord32PairBinop().
New()
static AtomicWord32PairOp& v8::internal::compiler::turboshaft::AtomicWord32PairOp::New (Graph * graph, V< WordPtr > base, OptionalV< WordPtr > index, OptionalV< Word32 > value_low, OptionalV< Word32 > value_high, OptionalV< Word32 > expected_low, OptionalV< Word32 > expected_high, Kind kind, int32_t offset) [inline], [static]
Definition at line 3338 of file operations.h.
                                                 {
    return Base::New(graph, InputCount(kind, index.has_value()), base, index,
                     value_low, value_high, expected_low, expected_high, kind,
                     offset);
  }
References graph(), v8::internal::index, and v8::internal::anonymous_namespace{intl-objects.cc}::New().
options()
auto v8::internal::compiler::turboshaft::AtomicWord32PairOp::options () const [inline]
Definition at line 3354 of file operations.h.
{ return std::tuple{kind, offset}; }
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::AtomicWord32PairOp::outputs_rep () const [inline]
Definition at line 3238 of file operations.h.
                                                               {
    if (kind == Kind::kStore) return {};
    return RepVector<RegisterRepresentation::Word32(),
                     RegisterRepresentation::Word32()>();
  }
References v8::internal::compiler::turboshaft::RepVector(), and v8::internal::compiler::turboshaft::RegisterRepresentation::Word32().
PrintInputs()
void v8::internal::compiler::turboshaft::AtomicWord32PairOp::PrintInputs (std::ostream & os, const std::string & op_index_prefix) const
Definition at line 660 of file operations.cc.
                                                                             {
  os << " *(" << op_index_prefix << base().id();
  if (index().valid()) {
    os << " + " << op_index_prefix << index().value().id();
  }
  if (offset) {
    os << " + offset=" << offset;
  }
  os << ").atomic_word32_pair_" << kind << '(';
  if (kind == Kind::kCompareExchange) {
    os << "expected: {lo: " << op_index_prefix << value_low()
       << ", hi: " << op_index_prefix << value_high();
    os << "}, value: {lo: " << op_index_prefix << value_low()
       << ", hi: " << op_index_prefix << value_high() << '}';
  } else if (kind != Kind::kLoad) {
    os << "lo: " << op_index_prefix << value_low()
       << ", hi: " << op_index_prefix << value_high();
  }
  os << ')';
}
References base(), v8::internal::compiler::turboshaft::OpIndex::id(), index(), kCompareExchange, kind, kLoad, offset, value_high(), and value_low().
PrintOptions()
void v8::internal::compiler::turboshaft::AtomicWord32PairOp::PrintOptions (std::ostream & os) const
Definition at line 682 of file operations.cc.
                                                          {
  os << "[opkind: " << kind << ']';
}
References kind.
value_high()
OptionalV<Word32> v8::internal::compiler::turboshaft::AtomicWord32PairOp::value_high () const [inline]
Definition at line 3273 of file operations.h.
                                       {
    return kind != Kind::kLoad ? input<Word32>(2 + HasIndex())
                               : V<Word32>::Invalid();
  }
References v8::internal::compiler::turboshaft::V< T >::Invalid().
Referenced by PrintInputs(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitPairAtomicBinOp(), and v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitPairAtomicBinOp().
value_low()
OptionalV<Word32> v8::internal::compiler::turboshaft::AtomicWord32PairOp::value_low () const [inline]
Definition at line 3269 of file operations.h.
                                      {
    return kind != Kind::kLoad ? input<Word32>(1 + HasIndex())
                               : V<Word32>::Invalid();
  }
References v8::internal::compiler::turboshaft::V< T >::Invalid().
Referenced by PrintInputs(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitPairAtomicBinOp(), and v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitPairAtomicBinOp().
Member Data Documentation
kind
Kind v8::internal::compiler::turboshaft::AtomicWord32PairOp::kind
Definition at line 3205 of file operations.h.
Referenced by PrintInputs(), PrintOptions(), and v8::internal::compiler::InstructionSelector::VisitNode().
offset
int32_t v8::internal::compiler::turboshaft::AtomicWord32PairOp::offset
Definition at line 3206 of file operations.h.
Referenced by PrintInputs().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h
/mnt/V8SourceCode/src/compiler/turboshaft/operations.cc