v8::internal::compiler::PersistentMap< Key, Value, Hasher >::KeyValue Struct Reference
Public Member Functions
const Key & key () const
const Value & value () const
Detailed Description
template<class Key, class Value, class Hasher = base::hash<Key>>
struct v8::internal::compiler::PersistentMap< Key, Value, Hasher >::KeyValue
Definition at line 58 of file persistent-map.h.
Member Function Documentation
key()
template<class Key , class Value , class Hasher = base::hash<Key>>
const Key& v8::internal::compiler::PersistentMap< Key, Value, Hasher >::KeyValue::key () const [inline]
Definition at line 59 of file persistent-map.h.
{ return this->first; }
Referenced by v8::internal::compiler::PersistentMap< Key, Value, Hasher >::GetFocusedValue(), and v8::internal::compiler::PersistentMap< Key, Value, Hasher >::Modify().
value()
template<class Key , class Value , class Hasher = base::hash<Key>>
const Value& v8::internal::compiler::PersistentMap< Key, Value, Hasher >::KeyValue::value () const [inline]
Definition at line 60 of file persistent-map.h.
{ return this->second; }
Referenced by v8::internal::compiler::PersistentMap< Key, Value, Hasher >::GetFocusedValue(), and v8::internal::compiler::PersistentMap< Key, Value, Hasher >::Modify().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/persistent-map.h