v8::internal::compiler::turboshaft::ControlState Struct Reference
#include <dead-code-elimination-reducer.h>
Public Types
enum Kind { kUnreachable
, kBlock
, kNotEliminatable
 }
Public Member Functions
ControlState (Kind kind, BlockIndex block=BlockIndex::Invalid())
Static Public Member Functions
static ControlState NotEliminatable ()
static ControlState Block (BlockIndex block)
static ControlState Unreachable ()
static ControlState LeastUpperBound (const ControlState &lhs, const ControlState &rhs)
Public Attributes
Kind kind
BlockIndex block
Detailed Description
Definition at line 67 of file dead-code-elimination-reducer.h.
Member Enumeration Documentation
Kind
enum v8::internal::compiler::turboshaft::ControlState::Kind
Enumerator
kUnreachable
kBlock
kNotEliminatable
Definition at line 86 of file dead-code-elimination-reducer.h.
            {
    kUnreachable,
    kBlock,
    kNotEliminatable,
  };
Constructor & Destructor Documentation
ControlState()
v8::internal::compiler::turboshaft::ControlState::ControlState (Kind kind, BlockIndex block = BlockIndex::Invalid()) [inline], [explicit]
Definition at line 100 of file dead-code-elimination-reducer.h.
      : kind(kind), block(block) {}
Member Function Documentation
Block()
static ControlState v8::internal::compiler::turboshaft::ControlState::Block (BlockIndex block) [inline], [static]
Definition at line 95 of file dead-code-elimination-reducer.h.
                                              {
    return ControlState{kBlock, block};
  }
References block, and kBlock.
Referenced by v8::internal::compiler::turboshaft::DeadCodeAnalysis::ProcessBlock().
LeastUpperBound()
static ControlState v8::internal::compiler::turboshaft::ControlState::LeastUpperBound (const ControlState & lhs, const ControlState & rhs) [inline], [static]
Definition at line 103 of file dead-code-elimination-reducer.h.
                                                               {
    switch (lhs.kind) {
      case Kind::kUnreachable:
        return rhs;
      case Kind::kBlock: {
        if (rhs.kind == Kind::kUnreachable) return lhs;
        if (rhs.kind == Kind::kNotEliminatable) return rhs;
        if (lhs.block == rhs.block) return lhs;
        return NotEliminatable();
      }
      case Kind::kNotEliminatable:
        return lhs;
    }
  }
References block, kind, v8::internal::wasm::kUnreachable, and NotEliminatable().
Referenced by v8::internal::compiler::turboshaft::DeadCodeAnalysis::ProcessBlock().
NotEliminatable()
static ControlState v8::internal::compiler::turboshaft::ControlState::NotEliminatable () [inline], [static]
Definition at line 92 of file dead-code-elimination-reducer.h.
                                        {
    return ControlState{kNotEliminatable};
  }
References kNotEliminatable.
Referenced by LeastUpperBound(), and v8::internal::compiler::turboshaft::DeadCodeAnalysis::ProcessBlock().
Unreachable()
static ControlState v8::internal::compiler::turboshaft::ControlState::Unreachable () [inline], [static]
Definition at line 98 of file dead-code-elimination-reducer.h.
{ return ControlState{kUnreachable}; }
References kUnreachable.
Referenced by v8::internal::compiler::turboshaft::DeadCodeAnalysis::ProcessBlock().
Member Data Documentation
block
BlockIndex v8::internal::compiler::turboshaft::ControlState::block
Definition at line 120 of file dead-code-elimination-reducer.h.
Referenced by Block(), LeastUpperBound(), v8::internal::compiler::turboshaft::operator<<(), v8::internal::compiler::turboshaft::operator==(), and v8::internal::compiler::turboshaft::DeadCodeAnalysis::ProcessBlock().
kind
Kind v8::internal::compiler::turboshaft::ControlState::kind
Definition at line 119 of file dead-code-elimination-reducer.h.
Referenced by LeastUpperBound(), v8::internal::compiler::turboshaft::operator<<(), v8::internal::compiler::turboshaft::operator==(), and v8::internal::compiler::turboshaft::DeadCodeAnalysis::ProcessBlock().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/dead-code-elimination-reducer.h