v8::internal::compiler::anonymous_namespace{add-type-assertions-reducer.cc}::AddTypeAssertionsImpl Struct Reference
Public Member Functions
void Run ()
void ProcessBlock (BasicBlock *block)
void InsertAssertion (Node *asserted, Node *effect_successor)
Public Attributes
JSGraph * jsgraph
Schedule * schedule
Zone * phase_zone
SimplifiedOperatorBuilder * simplified = jsgraph->simplified()
TFGraph * graph = jsgraph->graph()
Detailed Description
Definition at line 15 of file add-type-assertions-reducer.cc.
Member Function Documentation
InsertAssertion()
void v8::internal::compiler::anonymous_namespace{add-type-assertions-reducer.cc}::AddTypeAssertionsImpl::InsertAssertion (Node * asserted, Node * effect_successor)
Definition at line 72 of file add-type-assertions-reducer.cc.
                                                                    {
  Node* assertion = graph->NewNode(
      simplified->AssertType(NodeProperties::GetType(asserted)), asserted,
      NodeProperties::GetEffectInput(effect_successor));
  NodeProperties::ReplaceEffectInput(effect_successor, assertion);
}
References v8::internal::compiler::SimplifiedOperatorBuilder::AssertType(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetType(), graph(), and v8::internal::compiler::NodeProperties::ReplaceEffectInput().
ProcessBlock()
void v8::internal::compiler::anonymous_namespace{add-type-assertions-reducer.cc}::AddTypeAssertionsImpl::ProcessBlock (BasicBlock * block)
Definition at line 34 of file add-type-assertions-reducer.cc.
                                                          {
  // To keep things simple, this only inserts type assertions for nodes that are
  // followed by an effectful operation in the same basic block. We could build
  // a proper new effect chain like in the EffectControlLinearizer, but right
  // now, this doesn't quite seem worth the effort.
  std::vector<Node*> pending;
  bool inside_of_region = false;
  for (Node* node : *block) {
    if (node->opcode() == IrOpcode::kBeginRegion) {
      inside_of_region = true;
    } else if (inside_of_region) {
      if (node->opcode() == IrOpcode::kFinishRegion) {
        inside_of_region = false;
      }
      continue;
    }
    if (node->op()->EffectOutputCount() == 1 &&
        node->op()->EffectInputCount() == 1) {
      for (Node* pending_node : pending) {
        InsertAssertion(pending_node, node);
      }
      pending.clear();
    }
    if (node->opcode() == IrOpcode::kAssertType ||
        node->opcode() == IrOpcode::kAllocate ||
        node->opcode() == IrOpcode::kObjectState ||
        node->opcode() == IrOpcode::kObjectId ||
        node->opcode() == IrOpcode::kPhi || !NodeProperties::IsTyped(node) ||
        node->opcode() == IrOpcode::kUnreachable) {
      continue;
    }
    Type type = NodeProperties::GetType(node);
    if (type.CanBeAsserted()) {
      pending.push_back(node);
    }
  }
}
References v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::IsTyped(), v8::internal::wasm::kUnreachable, and v8::internal::tracing::type.
Run()
void v8::internal::compiler::anonymous_namespace{add-type-assertions-reducer.cc}::AddTypeAssertionsImpl::Run ()
Definition at line 28 of file add-type-assertions-reducer.cc.
                                {
  for (BasicBlock* block : *(schedule->rpo_order())) {
    ProcessBlock(block);
  }
}
References v8::internal::compiler::Schedule::rpo_order().
Member Data Documentation
graph
TFGraph* v8::internal::compiler::anonymous_namespace{add-type-assertions-reducer.cc}::AddTypeAssertionsImpl::graph = jsgraph->graph()
Definition at line 21 of file add-type-assertions-reducer.cc.
jsgraph
JSGraph* v8::internal::compiler::anonymous_namespace{add-type-assertions-reducer.cc}::AddTypeAssertionsImpl::jsgraph
Definition at line 16 of file add-type-assertions-reducer.cc.
phase_zone
Zone* v8::internal::compiler::anonymous_namespace{add-type-assertions-reducer.cc}::AddTypeAssertionsImpl::phase_zone
Definition at line 18 of file add-type-assertions-reducer.cc.
schedule
Schedule* v8::internal::compiler::anonymous_namespace{add-type-assertions-reducer.cc}::AddTypeAssertionsImpl::schedule
Definition at line 17 of file add-type-assertions-reducer.cc.
simplified
SimplifiedOperatorBuilder* v8::internal::compiler::anonymous_namespace{add-type-assertions-reducer.cc}::AddTypeAssertionsImpl::simplified = jsgraph->simplified()
Definition at line 20 of file add-type-assertions-reducer.cc.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/add-type-assertions-reducer.cc