v8::internal::TickSample Struct Reference
#include <tick-sample.h>
Public Types
enum RecordCEntryFrame { kIncludeCEntryFrame
, kSkipCEntryFrame
 }
Public Member Functions
TickSample ()
void Init (Isolate *isolate, const v8::RegisterState &state, RecordCEntryFrame record_c_entry_frame, bool update_stats, bool use_simulator_reg_state=true, base::TimeDelta sampling_interval=base::TimeDelta(), const std::optional< uint64_t > trace_id=std::nullopt)
Initialize a tick sample from the isolate.
void print () const
Static Public Member Functions
static bool GetStackSample (Isolate *isolate, v8::RegisterState *state, RecordCEntryFrame record_c_entry_frame, void **frames, size_t frames_limit, v8::SampleInfo *sample_info, StateTag *out_state=nullptr, bool use_simulator_reg_state=true)
Get a call stack sample from the isolate.
Public Attributes
void * pc = nullptr
xx xx xx xx xx xx xx xx xx
union {
 void * tos
 void * external_callback_entry = nullptr
};
void * context = nullptr
void * embedder_context = nullptr
base::TimeTicks timestamp
base::TimeDelta sampling_interval_
StateTag state = OTHER
EmbedderStateTag embedder_state = EmbedderStateTag::EMPTY
uint16_t frames_count = 0
bool has_external_callback = false
bool update_stats_ = true
std::optional< uint64_t > trace_id_
void * stack [kMaxFramesCount]
Static Public Attributes
static constexpr unsigned kMaxFramesCountLog2 = 8
static constexpr unsigned kMaxFramesCount = (1 << kMaxFramesCountLog2) - 1
Detailed Description
Definition at line 18 of file tick-sample.h.
Member Enumeration Documentation
RecordCEntryFrame
enum v8::internal::TickSample::RecordCEntryFrame
Enumerator
kIncludeCEntryFrame
kSkipCEntryFrame
Definition at line 22 of file tick-sample.h.
{ kIncludeCEntryFrame, kSkipCEntryFrame };
Constructor & Destructor Documentation
TickSample()
v8::internal::TickSample::TickSample () [inline]
Definition at line 24 of file tick-sample.h.
{}
Member Function Documentation
GetStackSample()
bool v8::internal::TickSample::GetStackSample (Isolate * isolate, v8::RegisterState * state, RecordCEntryFrame record_c_entry_frame, void ** frames, size_t frames_limit, v8::SampleInfo * sample_info, StateTag * out_state = nullptr, bool use_simulator_reg_state = true) [static]
Get a call stack sample from the isolate.
Parameters
isolate The isolate.
state Register state.
record_c_entry_frame Include or skip the runtime function.
frames Caller allocated buffer to store stack frames.
frames_limit Maximum number of frames to capture. The buffer must be large enough to hold the number of frames.
sample_info The sample info is filled up by the function provides number of actual captured stack frames and the current VM state.
out_state Output parameter. If non-nullptr pointer is provided, and the execution is currently in a fast API call, records StateTag::EXTERNAL to it. The caller could then use this as a marker to not take into account the actual VM state recorded in |sample_info|. In the case of fast API calls, the VM state must be EXTERNAL, as the callback is always an external C++ function.
use_simulator_reg_state When set to true and V8 is running under a simulator, the method will use the simulator register state rather than the one provided with |state| argument. Otherwise the method will use provided register |state| as is.
Note
GetStackSample is thread and signal safe and should only be called when the JS thread is paused or interrupted. Otherwise the behavior is undefined.
Definition at line 219 of file tick-sample.cc.
                                                              {
  i::Isolate* isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  sample_info->frames_count = 0;
  sample_info->vm_state = isolate->current_vm_state();
  sample_info->external_callback_entry = nullptr;
  sample_info->embedder_state = EmbedderStateTag::EMPTY;
  sample_info->embedder_context = nullptr;
  sample_info->context = nullptr;
  if (sample_info->vm_state == GC || v8_isolate->heap()->IsInGC()) {
    // GC can happen any time, not directly caused by its caller. Don't collect
    // stacks for it. We check for both GC VMState and IsInGC, since we can
    // observe LOGGING VM states during GC.
    // TODO(leszeks): We could still consider GC stacks (as long as this isn't a
    // moving GC), e.g. to surface if one particular function is triggering all
    // the GCs. However, this is a user-visible change, and we would need to
    // adjust the symbolizer and devtools to expose this information.
    return true;
  }
  EmbedderState* embedder_state = isolate->current_embedder_state();
  if (embedder_state != nullptr) {
    sample_info->embedder_context =
        reinterpret_cast<void*>(embedder_state->native_context_address());
    sample_info->embedder_state = embedder_state->GetState();
  }
  Tagged<Context> top_context = isolate->context();
  if (top_context.ptr() != i::Context::kNoContext) {
    Tagged<NativeContext> top_native_context = top_context->native_context();
    sample_info->context = reinterpret_cast<void*>(top_native_context.ptr());
  }
  i::Address js_entry_sp = isolate->js_entry_sp();
  if (js_entry_sp == 0) return true; // Not executing JS now.
#if V8_ENABLE_WEBASSEMBLY
  // With stack-switching, the js_entry_sp and current sp may be in different
  // stacks. Use the active stack base instead as the upper bound to correctly
  // validate addresses in the stack frame iterator.
  wasm::StackMemory* stack = isolate->isolate_data()->active_stack();
  if (stack != nullptr && stack->jmpbuf()->parent != nullptr) {
    js_entry_sp = stack->base();
  }
#endif
#if defined(USE_SIMULATOR)
  if (use_simulator_reg_state) {
    if (!i::SimulatorHelper::FillRegisters(isolate, regs)) {
      i::ProfilerStats::Instance()->AddReason(
          i::ProfilerStats::Reason::kSimulatorFillRegistersFailed);
      return false;
    }
  }
#else
  USE(use_simulator_reg_state);
#endif
  DCHECK(regs->sp);
  // Check whether we interrupted setup/teardown of a stack frame in JS code.
  // Avoid this check for C++ code, as that would trigger false positives.
  // TODO(petermarshall): Code range is always null on ia32 so this check for
  // IsNoFrameRegion will never actually run there.
  if (regs->pc &&
      isolate->heap()->code_region().contains(
          reinterpret_cast<i::Address>(regs->pc)) &&
      IsNoFrameRegion(reinterpret_cast<i::Address>(regs->pc))) {
    // The frame is not setup, so it'd be hard to iterate the stack. Bailout.
    i::ProfilerStats::Instance()->AddReason(
        i::ProfilerStats::Reason::kNoFrameRegion);
    return false;
  }
  i::ExternalCallbackScope* scope = isolate->external_callback_scope();
  i::Address handler = i::Isolate::handler(isolate->thread_local_top());
  // If there is a handler on top of the external callback scope then
  // we have already entered JavaScript again and the external callback
  // is not the top function.
  if (scope && scope->JSStackComparableAddress() < handler) {
    i::Address* external_callback_entry_ptr =
        scope->callback_entrypoint_address();
    sample_info->external_callback_entry =
        external_callback_entry_ptr == nullptr
            ? nullptr
            : reinterpret_cast<void*>(*external_callback_entry_ptr);
  }
  // 'Fast API calls' are similar to fast C calls (see frames.cc) in that
  // they don't build an exit frame when entering C from JS. They have the
  // added speciality of having separate "fast" and "default" callbacks, the
  // latter being the regular API callback called before the JS function is
  // optimized. When TurboFan optimizes the JS caller, the fast callback
  // gets executed instead of the default one, therefore we need to store
  // its address in the sample.
  IsolateData* isolate_data = isolate->isolate_data();
  Address fast_c_fp = isolate_data->fast_c_call_caller_fp();
  if (fast_c_fp != kNullAddress &&
      isolate_data->fast_api_call_target() != kNullAddress) {
    sample_info->external_callback_entry =
        reinterpret_cast<void*>(isolate_data->fast_api_call_target());
    if (out_state) {
      *out_state = StateTag::EXTERNAL;
    }
  }
  i::StackFrameIteratorForProfiler it(
      isolate, reinterpret_cast<i::Address>(regs->pc),
      reinterpret_cast<i::Address>(regs->fp),
      reinterpret_cast<i::Address>(regs->sp),
      reinterpret_cast<i::Address>(regs->lr), js_entry_sp);
  if (it.done()) return true;
  size_t i = 0;
  if (record_c_entry_frame == kIncludeCEntryFrame &&
      (it.top_frame_type() == internal::StackFrame::EXIT ||
       it.top_frame_type() == internal::StackFrame::BUILTIN_EXIT)) {
    // While BUILTIN_EXIT definitely represents a call to CEntry the EXIT frame
    // might represent either a call to CEntry or an optimized call to
    // Api callback. In the latter case the ExternalCallbackScope points to
    // the same function, so skip adding a frame in that case in order to avoid
    // double-reporting.
    void* c_function = reinterpret_cast<void*>(isolate->c_function());
    if (sample_info->external_callback_entry != c_function) {
      frames[i] = c_function;
      i++;
    }
  }
#ifdef V8_RUNTIME_CALL_STATS
  i::RuntimeCallTimer* timer =
      isolate->counters()->runtime_call_stats()->current_timer();
#endif // V8_RUNTIME_CALL_STATS
  for (; !it.done() && i < frames_limit; it.Advance()) {
#ifdef V8_RUNTIME_CALL_STATS
    while (timer && reinterpret_cast<i::Address>(timer) < it.frame()->fp() &&
           i < frames_limit) {
      frames[i++] = reinterpret_cast<void*>(timer->counter());
      timer = timer->parent();
    }
    if (i == frames_limit) break;
#endif // V8_RUNTIME_CALL_STATS
    if (it.frame()->is_interpreted()) {
      // For interpreted frames use the bytecode array pointer as the pc.
      i::InterpretedFrame* frame =
          static_cast<i::InterpretedFrame*>(it.frame());
      // Since the sampler can interrupt execution at any point the
      // bytecode_array might be garbage, so don't actually dereference it. We
      // avoid the frame->GetXXX functions since they call Cast<BytecodeArray>,
      // which has a heap access in its DCHECK.
      i::Address bytecode_array = base::Memory<i::Address>(
          frame->fp() + i::InterpreterFrameConstants::kBytecodeArrayFromFp);
      i::Address bytecode_offset = base::Memory<i::Address>(
          frame->fp() + i::InterpreterFrameConstants::kBytecodeOffsetFromFp);
      // If the bytecode array is a heap object and the bytecode offset is a
      // Smi, use those, otherwise fall back to using the frame's pc.
      if (HAS_STRONG_HEAP_OBJECT_TAG(bytecode_array) &&
          HAS_SMI_TAG(bytecode_offset)) {
        frames[i++] = reinterpret_cast<void*>(
            bytecode_array + i::Internals::SmiValue(bytecode_offset));
        continue;
      }
    }
    // For arm64, the PC for the frame sometimes doesn't come from the stack,
    // but from the link register instead. For this reason, we skip
    // authenticating it.
    frames[i++] = reinterpret_cast<void*>(it.frame()->unauthenticated_pc());
  }
  sample_info->frames_count = i;
  return true;
}
References v8::internal::IsolateData::active_stack(), v8::internal::ProfilerStats::AddReason(), v8::internal::StackFrameIteratorForProfiler::Advance(), v8::internal::Isolate::c_function(), v8::internal::ExternalCallbackScope::callback_entrypoint_address(), v8::internal::Heap::code_region(), v8::base::AddressRegion::contains(), v8::SampleInfo::context, v8::internal::Isolate::context(), v8::internal::Isolate::counters(), v8::internal::DCHECK(), v8::internal::StackFrameIteratorBase::done(), v8::SampleInfo::embedder_context, v8::SampleInfo::embedder_state, embedder_state, v8::EMPTY, v8::EXTERNAL, v8::SampleInfo::external_callback_entry, v8::internal::IsolateData::fast_api_call_target(), v8::internal::IsolateData::fast_c_call_caller_fp(), v8::RegisterState::fp, v8::internal::StackFrame::fp(), v8::internal::StackFrameIteratorForProfiler::frame(), v8::SampleInfo::frames_count, v8::GC, v8::internal::Isolate::handler(), HAS_SMI_TAG, HAS_STRONG_HEAP_OBJECT_TAG, v8::internal::Isolate::heap(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::ProfilerStats::Instance(), v8::internal::StackFrame::is_interpreted(), v8::internal::Heap::IsInGC(), v8::internal::anonymous_namespace{tick-sample.cc}::IsNoFrameRegion(), v8::internal::Isolate::isolate_data(), v8::internal::Isolate::js_entry_sp(), v8::internal::ExternalCallbackScope::JSStackComparableAddress(), v8::internal::UnoptimizedFrameConstants::kBytecodeArrayFromFp, v8::internal::InterpreterFrameConstants::kBytecodeOffsetFromFp, kIncludeCEntryFrame, v8::internal::Context::kNoContext, v8::internal::kNullAddress, v8::RegisterState::lr, nullptr, v8::RegisterState::pc, v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), v8::internal::Counters::runtime_call_stats(), v8::internal::Internals::SmiValue(), v8::RegisterState::sp, stack, v8::internal::Isolate::thread_local_top(), v8::internal::StackFrameIteratorForProfiler::top_frame_type(), v8::internal::StackFrame::unauthenticated_pc(), USE, and v8::SampleInfo::vm_state.
Referenced by v8::Isolate::GetStackSample(), and Init().
Init()
DISABLE_ASAN void v8::internal::TickSample::Init (Isolate * isolate, const v8::RegisterState & state, RecordCEntryFrame record_c_entry_frame, bool update_stats, bool use_simulator_reg_state = true, base::TimeDelta sampling_interval = base::TimeDelta(), const std::optional< uint64_t > trace_id = std::nullopt)
Initialize a tick sample from the isolate.
Parameters
isolate The isolate.
state Execution state.
record_c_entry_frame Include or skip the runtime function.
update_stats Whether update the sample to the aggregated stats.
use_simulator_reg_state When set to true and V8 is running under a simulator, the method will use the simulator register state rather than the one provided with |state| argument. Otherwise the method will use provided register |state| as is.
Definition at line 164 of file tick-sample.cc.
                                                                         {
  update_stats_ = update_stats;
  SampleInfo info;
  RegisterState regs = reg_state;
  if (!GetStackSample(v8_isolate, &regs, record_c_entry_frame, stack,
                      kMaxFramesCount, &info, &state,
                      use_simulator_reg_state)) {
    // It is executing JS but failed to collect a stack trace.
    // Mark the sample as spoiled.
    pc = nullptr;
    return;
  }
  if (state != StateTag::EXTERNAL) {
    state = info.vm_state;
  }
  pc = regs.pc;
  frames_count = static_cast<unsigned>(info.frames_count);
  has_external_callback = info.external_callback_entry != nullptr;
  context = info.context;
  embedder_context = info.embedder_context;
  embedder_state = info.embedder_state;
  if (has_external_callback) {
    external_callback_entry = info.external_callback_entry;
  } else if (frames_count) {
    // sp register may point at an arbitrary place in memory, make
    // sure sanitizers don't complain about it.
    ASAN_UNPOISON_MEMORY_REGION(regs.sp, sizeof(void*));
    MSAN_MEMORY_IS_INITIALIZED(regs.sp, sizeof(void*));
    // Sample potential return address value for frameless invocation of
    // stubs (we'll figure out later, if this value makes sense).
    // TODO(petermarshall): This read causes guard page violations on Windows.
    // Either fix this mechanism for frameless stubs or remove it.
    // tos =
    // i::ReadUnalignedValue<void*>(reinterpret_cast<i::Address>(regs.sp));
    tos = nullptr;
  } else {
    tos = nullptr;
  }
  sampling_interval_ = sampling_interval;
  trace_id_ = trace_id;
  timestamp = base::TimeTicks::Now();
}
References ASAN_UNPOISON_MEMORY_REGION, v8::SampleInfo::context, context, v8::SampleInfo::embedder_context, embedder_context, v8::SampleInfo::embedder_state, embedder_state, v8::EXTERNAL, v8::SampleInfo::external_callback_entry, external_callback_entry, v8::SampleInfo::frames_count, frames_count, GetStackSample(), has_external_callback, kMaxFramesCount, MSAN_MEMORY_IS_INITIALIZED, v8::base::TimeTicks::Now(), v8::RegisterState::pc, pc, sampling_interval_, v8::RegisterState::sp, stack, state, timestamp, tos, trace_id_, update_stats_, and v8::SampleInfo::vm_state.
Referenced by v8::internal::ProfilerEventsProcessor::AddCurrentStack(), v8::internal::ProfilerEventsProcessor::AddDeoptStack(), v8::internal::CpuSampler::SampleStack(), and v8::internal::Ticker::SampleStack().
print()
void v8::internal::TickSample::print () const
Definition at line 395 of file tick-sample.cc.
                             {
  PrintF("TickSample: at %p\n", this);
  PrintF(" - state: %s\n", StateToString(state));
  PrintF(" - pc: %p\n", pc);
  PrintF(" - stack: (%u frames)\n", frames_count);
  for (unsigned i = 0; i < frames_count; i++) {
    PrintF(" %p\n", stack[i]);
  }
  PrintF(" - has_external_callback: %d\n", has_external_callback);
  PrintF(" - %s: %p\n",
         has_external_callback ? "external_callback_entry" : "tos", tos);
  PrintF(" - update_stats: %d\n", update_stats_);
  PrintF(" - sampling_interval: %" PRId64 "\n",
         sampling_interval_.InMicroseconds());
  PrintF("\n");
}
References frames_count, has_external_callback, v8::base::TimeDelta::InMicroseconds(), pc, v8::internal::PrintF(), sampling_interval_, stack, state, v8::internal::StateToString(), tos, and update_stats_.
Member Data Documentation
union { ... }
context
void* v8::internal::TickSample::context = nullptr
Definition at line 87 of file tick-sample.h.
Referenced by Init(), and v8::internal::SamplingEventsProcessor::SymbolizeAndAddToProfiles().
embedder_context
void* v8::internal::TickSample::embedder_context = nullptr
Definition at line 88 of file tick-sample.h.
Referenced by Init(), and v8::internal::SamplingEventsProcessor::SymbolizeAndAddToProfiles().
embedder_state
EmbedderStateTag v8::internal::TickSample::embedder_state = EmbedderStateTag::EMPTY
Definition at line 94 of file tick-sample.h.
Referenced by GetStackSample(), Init(), and v8::internal::SamplingEventsProcessor::SymbolizeAndAddToProfiles().
external_callback_entry
void* v8::internal::TickSample::external_callback_entry = nullptr
Definition at line 85 of file tick-sample.h.
Referenced by Init(), v8::internal::Symbolizer::SymbolizeTickSample(), and v8::internal::V8FileLogger::TickEvent().
frames_count
uint16_t v8::internal::TickSample::frames_count = 0
Definition at line 96 of file tick-sample.h.
Referenced by Init(), print(), v8::internal::Symbolizer::SymbolizeTickSample(), and v8::internal::V8FileLogger::TickEvent().
has_external_callback
bool v8::internal::TickSample::has_external_callback = false
Definition at line 98 of file tick-sample.h.
Referenced by Init(), print(), v8::internal::Symbolizer::SymbolizeTickSample(), and v8::internal::V8FileLogger::TickEvent().
kMaxFramesCount
constexpr unsigned v8::internal::TickSample::kMaxFramesCount = (1 << kMaxFramesCountLog2) - 1 [static], [constexpr]
Definition at line 80 of file tick-sample.h.
Referenced by Init().
kMaxFramesCountLog2
constexpr unsigned v8::internal::TickSample::kMaxFramesCountLog2 = 8 [static], [constexpr]
Definition at line 79 of file tick-sample.h.
pc
void* v8::internal::TickSample::pc = nullptr
Definition at line 82 of file tick-sample.h.
Referenced by Init(), print(), v8::internal::Symbolizer::SymbolizeTickSample(), and v8::internal::V8FileLogger::TickEvent().
sampling_interval_
base::TimeDelta v8::internal::TickSample::sampling_interval_
Definition at line 91 of file tick-sample.h.
Referenced by Init(), print(), and v8::internal::SamplingEventsProcessor::SymbolizeAndAddToProfiles().
stack
void* v8::internal::TickSample::stack[kMaxFramesCount]
Definition at line 104 of file tick-sample.h.
Referenced by GetStackSample(), Init(), print(), v8::internal::Symbolizer::SymbolizeTickSample(), and v8::internal::V8FileLogger::TickEvent().
state
StateTag v8::internal::TickSample::state = OTHER
Definition at line 93 of file tick-sample.h.
Referenced by Init(), print(), v8::internal::CpuSampler::SampleStack(), v8::internal::SamplingEventsProcessor::SymbolizeAndAddToProfiles(), v8::internal::Symbolizer::SymbolizeTickSample(), and v8::internal::V8FileLogger::TickEvent().
timestamp
base::TimeTicks v8::internal::TickSample::timestamp
Definition at line 90 of file tick-sample.h.
Referenced by Init(), v8::internal::CpuSampler::SampleStack(), and v8::internal::SamplingEventsProcessor::SymbolizeAndAddToProfiles().
tos
void* v8::internal::TickSample::tos
Definition at line 84 of file tick-sample.h.
Referenced by Init(), print(), v8::internal::Symbolizer::SymbolizeTickSample(), and v8::internal::V8FileLogger::TickEvent().
trace_id_
std::optional<uint64_t> v8::internal::TickSample::trace_id_
Definition at line 102 of file tick-sample.h.
Referenced by Init(), and v8::internal::SamplingEventsProcessor::SymbolizeAndAddToProfiles().
update_stats_
bool v8::internal::TickSample::update_stats_ = true
Definition at line 100 of file tick-sample.h.
Referenced by Init(), print(), and v8::internal::SamplingEventsProcessor::SymbolizeAndAddToProfiles().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/profiler/tick-sample.h
/mnt/V8SourceCode/src/profiler/tick-sample.cc