v8::internal::compiler::turboshaft::WasmSimdPhase Struct Reference
#include <wasm-simd-phase.h>
Public Member Functions
void Run (PipelineData *data, Zone *temp_zone)
Detailed Description
Definition at line 16 of file wasm-simd-phase.h.
Member Function Documentation
Run()
void v8::internal::compiler::turboshaft::WasmSimdPhase::Run (PipelineData * data, Zone * temp_zone)
Definition at line 12 of file wasm-simd-phase.cc.
                                                           {
  WasmShuffleAnalyzer analyzer(temp_zone, data->graph());
  if (analyzer.ShouldReduce()) {
    data->set_wasm_shuffle_analyzer(&analyzer);
    CopyingPhase<WasmShuffleReducer>::Run(data, temp_zone);
    data->clear_wasm_shuffle_analyzer();
  }
}
References v8::internal::compiler::turboshaft::PipelineData::graph(), v8::internal::compiler::turboshaft::CopyingPhase< Reducers >::Run(), and v8::internal::compiler::turboshaft::WasmShuffleAnalyzer::ShouldReduce().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/wasm-simd-phase.h
/mnt/V8SourceCode/src/compiler/turboshaft/wasm-simd-phase.cc