v8::internal::compiler::turboshaft::SameValueOp Struct Reference
#include <operations.h>
Public Types
enum class Mode : uint8_t { kSameValue
, kSameValueNumbersOnly
 }
Public Member Functions
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
V< Object > left () const
V< Object > right () const
SameValueOp (V< Object > left, V< Object > right, Mode mode)
auto options () const
Public Attributes
Mode mode
Static Public Attributes
static constexpr OpEffects effects
Additional Inherited Members
Detailed Description
Definition at line 6374 of file operations.h.
Member Enumeration Documentation
Mode
enum v8::internal::compiler::turboshaft::SameValueOp::Mode : uint8_t [strong]
Enumerator
kSameValue
kSameValueNumbersOnly
Definition at line 6375 of file operations.h.
                  : uint8_t {
    kSameValue,
    kSameValueNumbersOnly,
  };
Constructor & Destructor Documentation
SameValueOp()
v8::internal::compiler::turboshaft::SameValueOp::SameValueOp (V< Object > left, V< Object > right, Mode mode) [inline]
Definition at line 6398 of file operations.h.
      : Base(left, right), mode(mode) {}
Member Function Documentation
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::SameValueOp::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 6389 of file operations.h.
                                                              {
    return MaybeRepVector<MaybeRegisterRepresentation::Tagged(),
                          MaybeRegisterRepresentation::Tagged()>();
  }
References v8::internal::compiler::turboshaft::MaybeRepVector(), and v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::Tagged().
left()
V<Object> v8::internal::compiler::turboshaft::SameValueOp::left () const [inline]
Definition at line 6395 of file operations.h.
{ return Base::input<Object>(0); }
options()
auto v8::internal::compiler::turboshaft::SameValueOp::options () const [inline]
Definition at line 6402 of file operations.h.
{ return std::tuple{mode}; }
References mode().
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::SameValueOp::outputs_rep () const [inline]
Definition at line 6385 of file operations.h.
                                                               {
    return RepVector<RegisterRepresentation::Tagged()>();
  }
right()
V<Object> v8::internal::compiler::turboshaft::SameValueOp::right () const [inline]
Definition at line 6396 of file operations.h.
{ return Base::input<Object>(1); }
Member Data Documentation
effects
constexpr OpEffects v8::internal::compiler::turboshaft::SameValueOp::effects [static], [constexpr]
Initial value:
=
      OpEffects()
          
          .CanDependOnChecks()
Definition at line 6381 of file operations.h.
mode
Mode v8::internal::compiler::turboshaft::SameValueOp::mode
Definition at line 6379 of file operations.h.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h