v8::internal::compiler::turboshaft::detail::OptionMatch< T > Struct Template Reference
#include <operation-matcher.h>
Classes
struct Wildcard
Public Member Functions
OptionMatch ()
OptionMatch (const T &value)
OptionMatch (T *value)
bool matches (const T &matched)
void bind (const T &matched)
Public Attributes
std::variant< Wildcard, T, T * > v_
Detailed Description
template<typename T>
struct v8::internal::compiler::turboshaft::detail::OptionMatch< T >
Definition at line 63 of file operation-matcher.h.
Constructor & Destructor Documentation
OptionMatch() [1/3]
template<typename T >
v8::internal::compiler::turboshaft::detail::OptionMatch< T >::OptionMatch () [inline]
Definition at line 66 of file operation-matcher.h.
: v_(Wildcard{}) {}
OptionMatch() [2/3]
template<typename T >
v8::internal::compiler::turboshaft::detail::OptionMatch< T >::OptionMatch (const T & value) [inline]
Definition at line 67 of file operation-matcher.h.
: v_(value) {} // NOLINT(runtime/explicit)
OptionMatch() [3/3]
template<typename T >
v8::internal::compiler::turboshaft::detail::OptionMatch< T >::OptionMatch (T * value) [inline]
Definition at line 68 of file operation-matcher.h.
: v_(value) {} // NOLINT(runtime/explicit)
Member Function Documentation
bind()
template<typename T >
void v8::internal::compiler::turboshaft::detail::OptionMatch< T >::bind (const T & matched) [inline]
Definition at line 77 of file operation-matcher.h.
                              {
    DCHECK(matches(matched));
    if (v_.index() == 2) *std::get<2>(v_) = matched;
  }
References v8::internal::DCHECK(), v8::internal::compiler::turboshaft::detail::OptionMatch< T >::matches(), and v8::internal::compiler::turboshaft::detail::OptionMatch< T >::v_.
matches()
template<typename T >
bool v8::internal::compiler::turboshaft::detail::OptionMatch< T >::matches (const T & matched) [inline]
Definition at line 72 of file operation-matcher.h.
                                 {
    if (v_.index() == 1) return std::get<1>(v_) == matched;
    return true;
  }
References v8::internal::compiler::turboshaft::detail::OptionMatch< T >::v_.
Referenced by v8::internal::compiler::turboshaft::detail::OptionMatch< T >::bind().
Member Data Documentation
v_
template<typename T >
std::variant<Wildcard, T, T*> v8::internal::compiler::turboshaft::detail::OptionMatch< T >::v_
Definition at line 70 of file operation-matcher.h.
Referenced by v8::internal::compiler::turboshaft::detail::OptionMatch< T >::bind(), and v8::internal::compiler::turboshaft::detail::OptionMatch< T >::matches().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/operation-matcher.h