v8::internal::compiler::turboshaft::DeoptimizeOp Struct Reference
#include <operations.h>
Public Member Functions
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
V< FrameState > frame_state () const
DeoptimizeOp (V< FrameState > frame_state, const DeoptimizeParameters *parameters)
void Validate (const Graph &graph) const
auto options () const
Public Attributes
const DeoptimizeParameters * parameters
Static Public Attributes
static constexpr OpEffects effects = OpEffects().CanDeopt()
Additional Inherited Members
Detailed Description
Definition at line 3797 of file operations.h.
Constructor & Destructor Documentation
DeoptimizeOp()
v8::internal::compiler::turboshaft::DeoptimizeOp::DeoptimizeOp (V< FrameState > frame_state, const DeoptimizeParameters * parameters) [inline]
Definition at line 3810 of file operations.h.
      : Base(frame_state), parameters(parameters) {}
Member Function Documentation
frame_state()
V<FrameState> v8::internal::compiler::turboshaft::DeoptimizeOp::frame_state () const [inline]
Definition at line 3808 of file operations.h.
{ return input<FrameState>(0); }
Referenced by v8::internal::compiler::InstructionSelector::VisitControl().
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::DeoptimizeOp::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 3803 of file operations.h.
                                                              {
    return {};
  }
options()
auto v8::internal::compiler::turboshaft::DeoptimizeOp::options () const [inline]
Definition at line 3816 of file operations.h.
{ return std::tuple{parameters}; }
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::DeoptimizeOp::outputs_rep () const [inline]
Definition at line 3801 of file operations.h.
{ return {}; }
Validate()
void v8::internal::compiler::turboshaft::DeoptimizeOp::Validate (const Graph & graph) const [inline]
Definition at line 3813 of file operations.h.
                                          {
    DCHECK(Get(graph, frame_state()).Is<FrameStateOp>());
  }
References v8::internal::DCHECK(), v8::internal::compiler::turboshaft::Get(), and graph().
Member Data Documentation
effects
constexpr OpEffects v8::internal::compiler::turboshaft::DeoptimizeOp::effects = OpEffects().CanDeopt() [static], [constexpr]
Definition at line 3800 of file operations.h.
parameters
const DeoptimizeParameters* v8::internal::compiler::turboshaft::DeoptimizeOp::parameters
Definition at line 3798 of file operations.h.
Referenced by v8::internal::compiler::InstructionSelector::VisitControl().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h