v8::internal::compiler::PropertyAccessTarget::Hash Struct Reference
#include <js-heap-broker.h>
Public Member Functions
size_t operator() (const PropertyAccessTarget &pair) const
Detailed Description
Definition at line 66 of file js-heap-broker.h.
Member Function Documentation
operator()()
size_t v8::internal::compiler::PropertyAccessTarget::Hash::operator() (const PropertyAccessTarget & pair) const [inline]
Definition at line 67 of file js-heap-broker.h.
                                                              {
      return base::hash_combine(
          base::hash_combine(pair.map.object().address(),
                             pair.name.object().address()),
          static_cast<int>(pair.mode));
    }
References v8::base::hash_combine(), v8::internal::compiler::PropertyAccessTarget::map, v8::internal::compiler::PropertyAccessTarget::mode, v8::internal::compiler::PropertyAccessTarget::name, v8::internal::compiler::NameRef::object(), and v8::internal::compiler::MapRef::object().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-heap-broker.h