v8::internal::compiler::ExternalReferenceMatcher Struct Reference
#include <node-matchers.h>
Public Member Functions
ExternalReferenceMatcher (Node *node)
bool Is (const ExternalReference &value) const
Additional Inherited Members
Detailed Description
Definition at line 254 of file node-matchers.h.
Constructor & Destructor Documentation
ExternalReferenceMatcher()
v8::internal::compiler::ExternalReferenceMatcher::ExternalReferenceMatcher (Node * node) [inline], [explicit]
Definition at line 256 of file node-matchers.h.
      : ValueMatcher<ExternalReference, IrOpcode::kExternalConstant>(node) {}
Member Function Documentation
Is()
bool v8::internal::compiler::ExternalReferenceMatcher::Is (const ExternalReference & value) const [inline]
Definition at line 258 of file node-matchers.h.
                                                {
    return this->HasResolvedValue() && this->ResolvedValue() == value;
  }
References v8::internal::compiler::ValueMatcher< ExternalReference, IrOpcode::kExternalConstant >::HasResolvedValue(), v8::internal::compiler::ValueMatcher< ExternalReference, IrOpcode::kExternalConstant >::ResolvedValue(), and v8::internal::value.
Referenced by v8::internal::compiler::CsaLoadElimination::ReduceCall().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/node-matchers.h