v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::GetResultLocationAndSizeHelper< index, interpreter::OperandType::kRegOutList, operands... > Struct Template Reference
Static Public Member Functions
static std::pair< interpreter::Register, int > GetResultLocationAndSize (const interpreter::BytecodeArrayIterator &iterator)
static bool HasOutputRegisterOperand ()
Detailed Description
template<int index, interpreter::OperandType... operands>
struct v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::GetResultLocationAndSizeHelper< index, interpreter::OperandType::kRegOutList, operands... >
Definition at line 1238 of file maglev-graph-builder.cc.
Member Function Documentation
GetResultLocationAndSize()
template<int index, interpreter::OperandType... operands>
static std::pair<interpreter::Register, int> v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::GetResultLocationAndSizeHelper< index, interpreter::OperandType::kRegOutList, operands... >::GetResultLocationAndSize (const interpreter::BytecodeArrayIterator & iterator) [inline], [static]
Definition at line 1240 of file maglev-graph-builder.cc.
                                                        {
    interpreter::RegisterList list = iterator.GetRegisterListOperand(index);
    return {list.first_register(), list.register_count()};
  }
References v8::internal::interpreter::RegisterList::first_register(), v8::internal::interpreter::BytecodeArrayIterator::GetRegisterListOperand(), v8::internal::index, and v8::internal::interpreter::RegisterList::register_count().
HasOutputRegisterOperand()
template<int index, interpreter::OperandType... operands>
static bool v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::GetResultLocationAndSizeHelper< index, interpreter::OperandType::kRegOutList, operands... >::HasOutputRegisterOperand () [inline], [static]
Definition at line 1245 of file maglev-graph-builder.cc.
{ return true; }
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-graph-builder.cc