v8::internal::compiler::EarlyGraphTrimmingPhase Struct Reference
Public Member Functions
void Run (TFPipelineData *data, Zone *temp_zone)
Detailed Description
Definition at line 1030 of file pipeline.cc.
Member Function Documentation
Run()
void v8::internal::compiler::EarlyGraphTrimmingPhase::Run (TFPipelineData * data, Zone * temp_zone) [inline]
Definition at line 1033 of file pipeline.cc.
                                                  {
    GraphTrimmer trimmer(temp_zone, data->graph());
    NodeVector roots(temp_zone);
    data->jsgraph()->GetCachedNodes(&roots);
    UnparkedScopeIfNeeded scope(data->broker(), v8_flags.trace_turbo_trimming);
    trimmer.TrimGraph(roots.begin(), roots.end());
  }
References v8::internal::ZoneVector< T >::begin(), v8::internal::ZoneVector< T >::end(), v8::internal::compiler::GraphTrimmer::TrimGraph(), and v8::internal::v8_flags.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/pipeline.cc