cppgc::internal::StrongPersistentPolicy Struct Reference
#include <pointer-policies.h>
Public Types
using IsStrongPersistent = std::true_type
Static Public Member Functions
static PersistentRegion & GetPersistentRegion (const void *object)
Detailed Description
Definition at line 240 of file pointer-policies.h.
Member Typedef Documentation
IsStrongPersistent
using cppgc::internal::StrongPersistentPolicy::IsStrongPersistent = std::true_type
Definition at line 241 of file pointer-policies.h.
Member Function Documentation
GetPersistentRegion()
PersistentRegion & cppgc::internal::StrongPersistentPolicy::GetPersistentRegion (const void * object) [static]
Definition at line 109 of file pointer-policies.cc.
                        {
  return BasePage::FromPayload(object)->heap().GetStrongPersistentRegion();
}
References cppgc::internal::BasePage::FromPayload(), cppgc::internal::HeapBase::GetStrongPersistentRegion(), and cppgc::internal::BasePage::heap().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/include/cppgc/internal/pointer-policies.h
/mnt/V8SourceCode/src/heap/cppgc/pointer-policies.cc