v8::internal::maglev::detail::PushAllHelper< Arg > Struct Template Reference
#include <maglev-assembler-arm64-inl.h>
Static Public Member Functions
static void Push (MaglevAssembler *masm, Arg arg)
static void PushReverse (MaglevAssembler *masm, Arg arg)
Detailed Description
template<typename Arg>
struct v8::internal::maglev::detail::PushAllHelper< Arg >
Definition at line 284 of file maglev-assembler-arm64-inl.h.
Member Function Documentation
Push()
template<typename Arg >
static void v8::internal::maglev::detail::PushAllHelper< Arg >::Push (MaglevAssembler * masm, Arg arg) [inline], [static]
Definition at line 285 of file maglev-assembler-arm64-inl.h.
                                                   {
    if constexpr (is_iterator_range<Arg>::value) {
      PushIterator(masm, arg);
    } else {
      FATAL("Unaligned push");
    }
  }
References FATAL, and v8::internal::maglev::detail::PushIterator().
PushReverse()
template<typename Arg >
static void v8::internal::maglev::detail::PushAllHelper< Arg >::PushReverse (MaglevAssembler * masm, Arg arg) [inline], [static]
Definition at line 292 of file maglev-assembler-arm64-inl.h.
                                                          {
    if constexpr (is_iterator_range<Arg>::value) {
      PushIteratorReverse(masm, arg);
    } else {
      PushAllReverse(masm, arg, padreg);
    }
  }
References v8::internal::padreg, v8::internal::maglev::detail::PushAllReverse(), and v8::internal::maglev::detail::PushIteratorReverse().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/maglev/arm64/maglev-assembler-arm64-inl.h