v8::internal::compiler::anonymous_namespace{machine-operator-reducer.cc}::BitfieldCheck Struct Reference
Public Member Functions
BitfieldCheck (Node *source, uint32_t mask, uint32_t masked_value, bool truncate_from_64_bit)
std::optional< BitfieldCheck > TryCombine (const BitfieldCheck &other)
Static Public Member Functions
static std::optional< BitfieldCheck > Detect (Node *node)
Public Attributes
Node *const source
uint32_t const mask
uint32_t const masked_value
bool const truncate_from_64_bit
Static Private Member Functions
template<typename WordNAdapter >
static std::optional< BitfieldCheck > TryDetectShiftAndMaskOneBit (Node *node)
Detailed Description
Definition at line 2276 of file machine-operator-reducer.cc.
Constructor & Destructor Documentation
BitfieldCheck()
v8::internal::compiler::anonymous_namespace{machine-operator-reducer.cc}::BitfieldCheck::BitfieldCheck (Node * source, uint32_t mask, uint32_t masked_value, bool truncate_from_64_bit) [inline]
Definition at line 2282 of file machine-operator-reducer.cc.
      : source(source),
        mask(mask),
        masked_value(masked_value),
        truncate_from_64_bit(truncate_from_64_bit) {
    CHECK_EQ(masked_value & ~mask, 0);
  }
References CHECK_EQ.
Member Function Documentation
Detect()
static std::optional<BitfieldCheck> v8::internal::compiler::anonymous_namespace{machine-operator-reducer.cc}::BitfieldCheck::Detect (Node * node) [inline], [static]
Definition at line 2291 of file machine-operator-reducer.cc.
                                                       {
    // There are two patterns to check for here:
    // 1. Single-bit checks: `(val >> shift) & 1`, where:
    // - the shift may be omitted, and/or
    // - the result may be truncated from 64 to 32
    // 2. Equality checks: `(val & mask) == expected`, where:
    // - val may be truncated from 64 to 32 before masking (see
    // ReduceWordEqualForConstantRhs)
    if (node->opcode() == IrOpcode::kWord32Equal) {
      Uint32BinopMatcher eq(node);
      if (eq.left().IsWord32And()) {
        Uint32BinopMatcher mand(eq.left().node());
        if (mand.right().HasResolvedValue() && eq.right().HasResolvedValue()) {
          uint32_t mask = mand.right().ResolvedValue();
          uint32_t masked_value = eq.right().ResolvedValue();
          if ((masked_value & ~mask) != 0) return {};
          if (mand.left().IsTruncateInt64ToInt32()) {
            return BitfieldCheck(
                NodeProperties::GetValueInput(mand.left().node(), 0), mask,
                masked_value, true);
          } else {
            return BitfieldCheck(mand.left().node(), mask, masked_value, false);
          }
        }
      }
    } else {
      if (node->opcode() == IrOpcode::kTruncateInt64ToInt32) {
        return TryDetectShiftAndMaskOneBit<Word64Adapter>(
            NodeProperties::GetValueInput(node, 0));
      } else {
        return TryDetectShiftAndMaskOneBit<Word32Adapter>(node);
      }
    }
    return {};
  }
References v8::internal::eq, v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::left(), v8::internal::compiler::Node::opcode(), and v8::internal::compiler::BinopMatcher< Left, Right, rep >::right().
TryCombine()
std::optional<BitfieldCheck> v8::internal::compiler::anonymous_namespace{machine-operator-reducer.cc}::BitfieldCheck::TryCombine (const BitfieldCheck & other) [inline]
Definition at line 2327 of file machine-operator-reducer.cc.
                                                                    {
    if (source != other.source ||
        truncate_from_64_bit != other.truncate_from_64_bit) {
      return {};
    }
    uint32_t overlapping_bits = mask & other.mask;
    // It would be kind of strange to have any overlapping bits, but they can be
    // allowed as long as they don't require opposite values in the same
    // positions.
    if ((masked_value & overlapping_bits) !=
        (other.masked_value & overlapping_bits)) {
      return {};
    }
    return BitfieldCheck{source, mask | other.mask,
                         masked_value | other.masked_value,
                         truncate_from_64_bit};
  }
References mask, masked_value, source, and truncate_from_64_bit.
TryDetectShiftAndMaskOneBit()
template<typename WordNAdapter >
static std::optional<BitfieldCheck> v8::internal::compiler::anonymous_namespace{machine-operator-reducer.cc}::BitfieldCheck::TryDetectShiftAndMaskOneBit (Node * node) [inline], [static], [private]
Definition at line 2347 of file machine-operator-reducer.cc.
                                                                            {
    // Look for the pattern `(val >> shift) & 1`. The shift may be omitted.
    if (WordNAdapter::IsWordNAnd(NodeMatcher(node))) {
      typename WordNAdapter::IntNBinopMatcher mand(node);
      if (mand.right().HasResolvedValue() &&
          mand.right().ResolvedValue() == 1) {
        if (WordNAdapter::IsWordNShr(mand.left()) ||
            WordNAdapter::IsWordNSar(mand.left())) {
          typename WordNAdapter::UintNBinopMatcher shift(mand.left().node());
          if (shift.right().HasResolvedValue() &&
              shift.right().ResolvedValue() < 32u) {
            uint32_t mask = 1 << shift.right().ResolvedValue();
            return BitfieldCheck{shift.left().node(), mask, mask,
                                 WordNAdapter::WORD_SIZE == 64};
          }
        }
        return BitfieldCheck{mand.left().node(), 1, 1,
                             WordNAdapter::WORD_SIZE == 64};
      }
    }
    return {};
  }
Member Data Documentation
mask
uint32_t const v8::internal::compiler::anonymous_namespace{machine-operator-reducer.cc}::BitfieldCheck::mask
Definition at line 2278 of file machine-operator-reducer.cc.
Referenced by TryCombine().
masked_value
uint32_t const v8::internal::compiler::anonymous_namespace{machine-operator-reducer.cc}::BitfieldCheck::masked_value
Definition at line 2279 of file machine-operator-reducer.cc.
Referenced by TryCombine().
source
Node* const v8::internal::compiler::anonymous_namespace{machine-operator-reducer.cc}::BitfieldCheck::source
Definition at line 2277 of file machine-operator-reducer.cc.
Referenced by TryCombine().
truncate_from_64_bit
bool const v8::internal::compiler::anonymous_namespace{machine-operator-reducer.cc}::BitfieldCheck::truncate_from_64_bit
Definition at line 2280 of file machine-operator-reducer.cc.
Referenced by TryCombine().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/machine-operator-reducer.cc