v8::internal::compiler::CallBuffer Struct Reference
Public Member Functions
CallBuffer (Zone *zone, const CallDescriptor *call_descriptor, FrameStateDescriptor *frame_state)
size_t input_count () const
size_t frame_state_count () const
size_t frame_state_value_count () const
Public Attributes
const CallDescriptor * descriptor
FrameStateDescriptor * frame_state_descriptor
ZoneVector< PushParameter > output_nodes
InstructionOperandVector outputs
InstructionOperandVector instruction_args
ZoneVector< PushParameter > pushed_nodes
Detailed Description
Definition at line 1088 of file instruction-selector.cc.
Constructor & Destructor Documentation
CallBuffer()
v8::internal::compiler::CallBuffer::CallBuffer (Zone * zone, const CallDescriptor * call_descriptor, FrameStateDescriptor * frame_state) [inline]
Definition at line 1089 of file instruction-selector.cc.
      : descriptor(call_descriptor),
        frame_state_descriptor(frame_state),
        output_nodes(zone),
        outputs(zone),
        instruction_args(zone),
        pushed_nodes(zone) {
    output_nodes.reserve(call_descriptor->ReturnCount());
    outputs.reserve(call_descriptor->ReturnCount());
    pushed_nodes.reserve(input_count());
    instruction_args.reserve(input_count() + frame_state_value_count());
  }
References frame_state_value_count(), input_count(), instruction_args, output_nodes, outputs, pushed_nodes, v8::internal::ZoneVector< T >::reserve(), and v8::internal::compiler::CallDescriptor::ReturnCount().
Member Function Documentation
frame_state_count()
size_t v8::internal::compiler::CallBuffer::frame_state_count () const [inline]
Definition at line 1112 of file instruction-selector.cc.
{ return descriptor->FrameStateCount(); }
References descriptor, and v8::internal::compiler::CallDescriptor::FrameStateCount().
frame_state_value_count()
size_t v8::internal::compiler::CallBuffer::frame_state_value_count () const [inline]
Definition at line 1114 of file instruction-selector.cc.
                                         {
    return (frame_state_descriptor == nullptr)
               ? 0
               : (frame_state_descriptor->GetTotalSize() +
                  1); // Include deopt id.
  }
References frame_state_descriptor, and v8::internal::compiler::FrameStateDescriptor::GetTotalSize().
Referenced by CallBuffer().
input_count()
size_t v8::internal::compiler::CallBuffer::input_count () const [inline]
Definition at line 1110 of file instruction-selector.cc.
{ return descriptor->InputCount(); }
References descriptor, and v8::internal::compiler::CallDescriptor::InputCount().
Referenced by CallBuffer(), and v8::internal::compiler::InstructionSelector::InitializeCallBuffer().
Member Data Documentation
descriptor
const CallDescriptor* v8::internal::compiler::CallBuffer::descriptor
Definition at line 1103 of file instruction-selector.cc.
Referenced by frame_state_count(), v8::internal::compiler::InstructionSelector::InitializeCallBuffer(), and input_count().
frame_state_descriptor
FrameStateDescriptor* v8::internal::compiler::CallBuffer::frame_state_descriptor
Definition at line 1104 of file instruction-selector.cc.
Referenced by frame_state_value_count(), and v8::internal::compiler::InstructionSelector::InitializeCallBuffer().
instruction_args
InstructionOperandVector v8::internal::compiler::CallBuffer::instruction_args
Definition at line 1107 of file instruction-selector.cc.
Referenced by CallBuffer(), v8::internal::compiler::InstructionSelector::InitializeCallBuffer(), v8::internal::compiler::InstructionSelector::VisitCall(), and v8::internal::compiler::InstructionSelector::VisitTailCall().
output_nodes
ZoneVector<PushParameter> v8::internal::compiler::CallBuffer::output_nodes
Definition at line 1105 of file instruction-selector.cc.
Referenced by CallBuffer(), v8::internal::compiler::InstructionSelector::InitializeCallBuffer(), and v8::internal::compiler::InstructionSelector::VisitCall().
outputs
InstructionOperandVector v8::internal::compiler::CallBuffer::outputs
Definition at line 1106 of file instruction-selector.cc.
Referenced by CallBuffer(), v8::internal::compiler::InstructionSelector::InitializeCallBuffer(), and v8::internal::compiler::InstructionSelector::VisitCall().
pushed_nodes
ZoneVector<PushParameter> v8::internal::compiler::CallBuffer::pushed_nodes
Definition at line 1108 of file instruction-selector.cc.
Referenced by CallBuffer(), v8::internal::compiler::InstructionSelector::InitializeCallBuffer(), and v8::internal::compiler::InstructionSelector::VisitCall().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/instruction-selector.cc