v8::internal::compiler::turboshaft::Operation Struct Reference
#include <operations.h>
Classes
struct IdentityMapper
Public Member Functions
base::Vector< const OpIndex > inputs () const
OpIndex input (size_t i) const
size_t StorageSlotCount () const
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
template<class Op >
bool Is () const
template<class Op >
underlying_operation_t< Op > & Cast ()
template<class Op >
const underlying_operation_t< Op > & Cast () const
template<class Op >
const underlying_operation_t< Op > * TryCast () const
template<class Op >
underlying_operation_t< Op > * TryCast ()
OpEffects Effects () const
bool IsBlockTerminator () const
bool IsRequiredWhenUnused () const
bool IsProtectedLoad () const
std::string ToString () const
void PrintInputs (std::ostream &os, const std::string &op_index_prefix) const
void PrintOptions (std::ostream &os) const
bool IsOnlyUserOf (const Operation &value, const Graph &graph) const
void Print () const
Static Public Member Functions
static size_t StorageSlotCount (Opcode opcode, size_t input_count)
Public Attributes
const Opcode opcode
SaturatedUint8 saturated_use_count
const uint16_t input_count
Protected Member Functions
Operation (Opcode opcode, size_t input_count)
template<class OpmaskT >
V8_CLANG_NO_SANITIZE (`memory`) bool IsOpmask() const
Operation (const Operation &)=delete
Operation & operator= (const Operation &)=delete
Detailed Description
Definition at line 925 of file operations.h.
Constructor & Destructor Documentation
Operation() [1/2]
v8::internal::compiler::turboshaft::Operation::Operation (Opcode opcode, size_t input_count) [inline], [explicit], [protected]
Definition at line 1012 of file operations.h.
      : opcode(opcode), input_count(input_count) {
    DCHECK_LE(input_count,
              std::numeric_limits<decltype(this->input_count)>::max());
  }
References DCHECK_LE, and v8::internal::compiler::turboshaft::detail::input_count().
Operation() [2/2]
v8::internal::compiler::turboshaft::Operation::Operation (const Operation &) [protected], [delete]
Member Function Documentation
Cast() [1/2]
template<class Op >
underlying_operation_t<Op>& v8::internal::compiler::turboshaft::Operation::Cast () [inline]
Definition at line 971 of file operations.h.
                                     {
    DCHECK(Is<Op>());
    return *static_cast<underlying_operation_t<Op>*>(this);
  }
References v8::internal::DCHECK().
Referenced by v8::internal::compiler::turboshaft::SLPTree::BuildTreeRec(), v8::internal::compiler::turboshaft::CallView::CallView(), v8::internal::compiler::CanBeImmediate(), v8::internal::compiler::turboshaft::StringEscapeAnalyzer::ComputeFrameStatesToReconstruct(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::EmitInt32MulWithOverflow(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::EmitInt32MulWithOverflow(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitLoad(), v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::Find(), v8::internal::compiler::turboshaft::FindCompareChain(), v8::internal::compiler::GetImmediateIntegerValue(), v8::internal::compiler::IA32OperandGenerator::GetImmediateIntegerValue(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::GetType(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::ExtendingLoadMatcher::Initialize(), v8::internal::compiler::ExtendingLoadMatcher::Initialize(), v8::internal::compiler::turboshaft::InstructionSelectionNormalizationReducer< Next >::IsComplexConstant(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::IsNodeUnsigned(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::IsSupportedReduceSeed(), v8::internal::compiler::turboshaft::IsUnlikelySuccessor(), v8::internal::compiler::IsWord32Binop(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::LoadStoreView::LoadStoreView(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::LoadStoreView::LoadStoreView(), v8::internal::compiler::turboshaft::LoadStrideEqualTo(), v8::internal::compiler::turboshaft::anonymous_namespace{decompression-optimization.cc}::DecompressionAnalyzer::MarkAddressingBase(), v8::internal::compiler::turboshaft::AnalyzerIterator::MarkLoopForRevisit(), v8::internal::compiler::turboshaft::AnalyzerIterator::MarkLoopForRevisitSkipHeader(), v8::internal::compiler::turboshaft::LateEscapeAnalysisAnalyzer::MarkToRemove(), v8::internal::compiler::turboshaft::DuplicationOptimizationReducer< Next >::MaybeDuplicateCond(), v8::internal::compiler::turboshaft::SLPTree::NewCommutativePackNodeAndRecurs(), v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::OperandForDeopt(), v8::internal::wasm::TurboshaftGraphBuildingInterface::PopControl(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessAllocateArray(), v8::internal::compiler::turboshaft::RedundantStoreAnalysis::ProcessBlock(), v8::internal::compiler::turboshaft::StringEscapeAnalyzer::ProcessBlock(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessBlock(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessBlock(), v8::internal::compiler::turboshaft::anonymous_namespace{decompression-optimization.cc}::DecompressionAnalyzer::ProcessBlock(), v8::internal::compiler::turboshaft::DeadCodeAnalysis::ProcessBlock(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessBlock(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessBranchOnTarget(), v8::internal::compiler::turboshaft::anonymous_namespace{decompression-optimization.cc}::DecompressionAnalyzer::ProcessOperation(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessOperations(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::ProduceWord32Result(), v8::internal::compiler::turboshaft::StringEscapeAnalyzer::RecursivelyMarkAllStringConcatInputsAsEscaping(), v8::internal::compiler::turboshaft::StringEscapeAnalyzer::RecursiveMarkAsShouldReconstruct(), v8::internal::compiler::turboshaft::IfElseCascadeToSwitchReducer< Next >::ReduceInputGraphBranch(), v8::internal::compiler::turboshaft::EmitProjectionReducer< Next >::ReduceOperation(), v8::internal::compiler::turboshaft::StringEscapeAnalyzer::ReprocessStringConcats(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ResolveAliases(), v8::internal::compiler::turboshaft::RunDecompressionOptimization(), v8::internal::compiler::turboshaft::Assembler< Reducers >::SplitEdge(), v8::internal::compiler::turboshaft::SuccessorBlocks(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::TagExceptionPhiInputsForBlock(), v8::internal::compiler::turboshaft::SLPTree::Try256ShuffleMatchLoad8x8U(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryAdjustIndex(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryAdjustOffset(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitBitfieldExtract32(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitMultiplyAdd(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitMultiplyNegate(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitMultiplySub(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::TryMatchBaseWithScaledIndexAndDisplacement(), v8::internal::compiler::TryMatchBaseWithScaledIndexAndDisplacement64ForWordBinop(), v8::internal::compiler::turboshaft::TryMatchConditionalCompareChainBranch(), v8::internal::compiler::turboshaft::TryMatchConditionalCompareChainSet(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::TryMatchShift(), v8::internal::compiler::TryMatchShiftFromMul(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::TryMatchShiftImmediate(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryMatchSignExtendShift(), v8::internal::compiler::TryMatchSignExtInt16OrInt8FromWord32Sar(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAddSub(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitBinopImpl(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitBlockTerminator(), v8::internal::compiler::InstructionSelector::VisitControl(), v8::internal::compiler::VisitLogical(), v8::internal::compiler::turboshaft::LoopFinder::VisitLoop(), v8::internal::compiler::InstructionSelector::VisitNode(), v8::internal::compiler::InstructionSelector::VisitProjection(), v8::internal::compiler::InstructionSelector::VisitReturn(), and v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitWord32Compare().
Cast() [2/2]
template<class Op >
const underlying_operation_t<Op>& v8::internal::compiler::turboshaft::Operation::Cast () const [inline]
Definition at line 976 of file operations.h.
                                                 {
    DCHECK(Is<Op>());
    return *static_cast<const underlying_operation_t<Op>*>(this);
  }
References v8::internal::DCHECK().
Effects()
OpEffects v8::internal::compiler::turboshaft::Operation::Effects () const
Referenced by v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::CanBeConstantFolded(), v8::internal::compiler::InstructionSelector::CanCover(), v8::internal::compiler::InstructionSelector::CanCoverProtectedLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::increment_effect_level_for_node(), v8::internal::compiler::turboshaft::SLPTree::IsSideEffectFree(), v8::internal::compiler::turboshaft::MemoryAnalyzer::Process(), v8::internal::compiler::turboshaft::RedundantStoreAnalysis::ProcessBlock(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessBlock(), and v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessBlock().
input()
OpIndex v8::internal::compiler::turboshaft::Operation::input (size_t i) const [inline]
Definition at line 950 of file operations.h.
{ return inputs()[i]; }
References v8::internal::anonymous_namespace{json-stringifier.cc}::i.
Referenced by v8::internal::compiler::turboshaft::SLPTree::BuildTreeRec(), v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::CanBeConstantFolded(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::CanUseOptimizedWord32Compare(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Change(), v8::internal::compiler::turboshaft::CombineFlagSettingOps(), v8::internal::compiler::InstructionSelector::EmitIdentity(), v8::internal::compiler::EmitS128Load(), v8::internal::compiler::EmitSignExtendWord(), v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::MatchPhiCompareCst(), v8::internal::compiler::turboshaft::SLPTree::NewCommutativePackNodeAndRecurs(), v8::internal::compiler::turboshaft::SLPTree::NewPackNodeAndRecurs(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitCbzOrTbz(), v8::internal::compiler::turboshaft::UseMap::UseMap(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitBinOp(), v8::internal::compiler::VisitBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitBitMask(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitFloat32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitFloat64Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitFloat64Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitFloat64Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitFloat64Compare(), v8::internal::compiler::VisitFloat64Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitFullWord32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitFullWord32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitFullWord32Compare(), v8::internal::compiler::VisitGeneralStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitMinOrMax(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitOptimizedWord32Compare(), v8::internal::compiler::VisitPairAtomicBinop(), v8::internal::compiler::InstructionSelector::VisitPhi(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitRO(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitRO(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitROWithTemp(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitROWithTempSimd(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitRR(), v8::internal::compiler::VisitRR(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitRR(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitRR(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitRR(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitRR(), v8::internal::compiler::VisitRRI(), v8::internal::compiler::VisitRRO(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitRRO(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitRRO(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitRRO(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitRROFloat(), v8::internal::compiler::VisitRRR(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitRRR(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitRRR(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitRRR(), v8::internal::compiler::VisitSimdShift(), v8::internal::compiler::VisitStoreCommon(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitTestUnderMask(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitTryTruncateDouble(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitTryTruncateDouble(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitUnaryOp(), v8::internal::compiler::VisitUniqueRRR(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitWord32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitWord32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitWordCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWordCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitWordCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitWordCompare(), v8::internal::compiler::VisitWordCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitWordCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitWordCompare(), and v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitWordCompare().
inputs()
base::Vector<const OpIndex> v8::internal::compiler::turboshaft::Operation::inputs () const
Referenced by v8::internal::compiler::turboshaft::SLPTree::HasInputDependencies(), v8::internal::compiler::turboshaft::Graph::InputsValid(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::InvalidateAllNonAliasingInputs(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::InvalidateAllNonAliasingInputs(), v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::is_exclusive_user_of(), v8::internal::compiler::turboshaft::anonymous_namespace{decompression-optimization.cc}::DecompressionAnalyzer::MarkAddressingBase(), v8::internal::compiler::turboshaft::StringEscapeAnalyzer::MarkAllInputsAsEscaping(), v8::internal::compiler::turboshaft::DeadCodeAnalysis::ProcessBlock(), v8::internal::compiler::turboshaft::anonymous_namespace{decompression-optimization.cc}::DecompressionAnalyzer::ProcessOperation(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::ReduceInputsOfOp(), and v8::internal::compiler::turboshaft::UseMap::UseMap().
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::Operation::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const
Is()
template<class Op >
bool v8::internal::compiler::turboshaft::Operation::Is () const [inline]
Definition at line 962 of file operations.h.
                  {
    if constexpr (std::is_base_of_v<Operation, Op>) {
      return opcode == Op::opcode;
    } else {
      // Otherwise this must be OpMaskT.
      return IsOpmask<Op>();
    }
  }
Referenced by v8::internal::compiler::AtomicOrder(), v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::CanBeConstantFolded(), v8::internal::compiler::CanBeImmediate(), v8::internal::compiler::turboshaft::CanBeUsedAsInput(), v8::internal::compiler::turboshaft::LateEscapeAnalysisAnalyzer::CollectUsesAndAllocations(), v8::internal::compiler::turboshaft::StringEscapeAnalyzer::ComputeFrameStatesToReconstruct(), v8::internal::compiler::turboshaft::anonymous_namespace{pretenuring-propagation-reducer.cc}::CouldBeAllocate(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitLoad(), v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::Find(), v8::internal::compiler::turboshaft::FindCompareChain(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::GenerateRightOperands(), v8::internal::compiler::IA32OperandGenerator::GetEffectiveAddressMemoryOperand(), v8::internal::compiler::S390OperandGenerator::GetEffectiveAddressMemoryOperand(), v8::internal::compiler::X64OperandGenerator::GetEffectiveAddressMemoryOperand(), v8::internal::compiler::turboshaft::GetSimdOpcodeName(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::GetType(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::GetTypeForPhiInput(), v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::increment_effect_level_for_node(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::ExtendingLoadMatcher::Initialize(), v8::internal::compiler::ExtendingLoadMatcher::Initialize(), v8::internal::compiler::InstructionSelector::InitializeCallBuffer(), v8::internal::compiler::InstructionBlockFor(), v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::is_exclusive_user_of(), v8::internal::compiler::InstructionSelector::is_load(), v8::internal::compiler::turboshaft::StringEscapeAnalyzer::IsEscaping(), v8::internal::compiler::turboshaft::IsInt32TruncatedLoadPattern(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::IsNodeUnsigned(), v8::internal::compiler::InstructionSelector::IsRetain(), v8::internal::compiler::InstructionSelector::IsSourcePositionUsed(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::IsSupportedReduceSeed(), v8::internal::compiler::IsWord32Binop(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::LoadStoreView::LoadStoreView(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::LoadStoreView::LoadStoreView(), v8::internal::compiler::turboshaft::anonymous_namespace{decompression-optimization.cc}::DecompressionAnalyzer::MarkAddressingBase(), v8::internal::compiler::turboshaft::StringEscapeAnalyzer::MarkAllInputsAsEscaping(), v8::internal::compiler::turboshaft::StringEscapeAnalyzer::MarkAsEscaping(), v8::internal::compiler::turboshaft::LateEscapeAnalysisAnalyzer::MarkToRemove(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::MaybeReplaceCmpZeroWithFlagSettingBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::MaybeReplaceCmpZeroWithFlagSettingBinop(), v8::internal::compiler::turboshaft::PretenuringPropagationAnalyzer::OldifySubgraph(), v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::OperandForDeopt(), v8::internal::compiler::turboshaft::DeadCodeAnalysis::ProcessBlock(), v8::internal::compiler::turboshaft::StringEscapeAnalyzer::ProcessFrameState(), v8::internal::compiler::turboshaft::PretenuringPropagationAnalyzer::ProcessPhi(), v8::internal::compiler::turboshaft::StringEscapeAnalyzer::RecursivelyMarkAllStringConcatInputsAsEscaping(), v8::internal::compiler::turboshaft::IfElseCascadeToSwitchReducer< Next >::ReduceInputGraphBranch(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::Run(), v8::internal::compiler::turboshaft::ShouldSkipOperation(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryAdjustIndex(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryAdjustOffset(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitBitfieldExtract32(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitCbzOrTbz(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::TryEmitLoadForLoadWord64AndShiftRight(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitMultiplyAdd(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitMultiplyNegate(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitMultiplySub(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::TryMatchBaseWithScaledIndexAndDisplacement(), v8::internal::compiler::TryMatchBaseWithScaledIndexAndDisplacement64(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::TryMatchShift(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::TryMatchShiftImmediate(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryMatchSignExtendShift(), v8::internal::compiler::TryMatchSignExtInt16OrInt8FromWord32Sar(), v8::internal::compiler::turboshaft::UseMap::UseMap(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitBlockBody(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitBlockTerminator(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitFloat64Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitFloat64Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitFloat64Compare(), v8::internal::compiler::VisitFloat64Compare(), v8::internal::compiler::VisitGeneralStore(), v8::internal::compiler::VisitLogical(), v8::internal::compiler::turboshaft::LoopFinder::VisitLoop(), v8::internal::compiler::InstructionSelector::VisitNode(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitOpNoMappingUpdate(), v8::internal::compiler::InstructionSelector::VisitProjection(), v8::internal::compiler::InstructionSelector::VisitReturn(), v8::internal::compiler::VisitStoreCommon(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitTestUnderMask(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitWord32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitWord32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitWordCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitWordCompare(), and v8::internal::compiler::InstructionSelector::VisitWordCompareZero().
IsBlockTerminator()
bool v8::internal::compiler::turboshaft::Operation::IsBlockTerminator () const [inline]
Definition at line 991 of file operations.h.
                                 {
    return turboshaft::IsBlockTerminator(opcode);
  }
References v8::internal::compiler::turboshaft::IsBlockTerminator().
Referenced by v8::internal::compiler::turboshaft::MemoryAnalyzer::Process(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessBlock(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessBlock(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitBlockBody(), and v8::internal::compiler::InstructionSelector::VisitNode().
IsOnlyUserOf()
bool v8::internal::compiler::turboshaft::Operation::IsOnlyUserOf (const Operation & value, const Graph & graph) const
Referenced by v8::internal::compiler::turboshaft::anonymous_namespace{decompression-optimization.cc}::DecompressionAnalyzer::MarkAddressingBase().
IsProtectedLoad()
bool v8::internal::compiler::turboshaft::Operation::IsProtectedLoad () const
IsRequiredWhenUnused()
bool v8::internal::compiler::turboshaft::Operation::IsRequiredWhenUnused () const [inline]
Definition at line 994 of file operations.h.
                                    {
    DCHECK_IMPLIES(IsBlockTerminator(), Effects().is_required_when_unused());
    return Effects().is_required_when_unused();
  }
References DCHECK_IMPLIES, and v8::internal::compiler::turboshaft::IsBlockTerminator().
Referenced by v8::internal::compiler::turboshaft::DeadCodeAnalysis::ProcessBlock(), and v8::internal::compiler::turboshaft::ShouldSkipOperation().
operator=()
Operation& v8::internal::compiler::turboshaft::Operation::operator= (const Operation &) [protected], [delete]
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::Operation::outputs_rep () const
Referenced by v8::internal::compiler::AddOperandToStateValueDescriptor(), v8::internal::compiler::turboshaft::CanBeUsedAsInput(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::GetType(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::GetType(), v8::internal::compiler::turboshaft::PrintTurboshaftGraphForTurbolizer(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessArrayLength(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessBlock(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessLoad(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessStructGet(), and v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitOpNoMappingUpdate().
Print()
void v8::internal::compiler::turboshaft::Operation::Print () const
Referenced by v8::internal::compiler::turboshaft::WasmRevecAnalyzer::Run().
PrintInputs()
void v8::internal::compiler::turboshaft::Operation::PrintInputs (std::ostream & os, const std::string & op_index_prefix) const
Referenced by v8::internal::compiler::turboshaft::operator<<().
PrintOptions()
void v8::internal::compiler::turboshaft::Operation::PrintOptions (std::ostream & os) const
Referenced by v8::internal::compiler::turboshaft::GetSimdOpcodeName(), and v8::internal::compiler::turboshaft::operator<<().
StorageSlotCount() [1/2]
size_t v8::internal::compiler::turboshaft::Operation::StorageSlotCount () const [inline]
Definition at line 953 of file operations.h.
                                  {
    return StorageSlotCount(opcode, input_count);
  }
References v8::internal::compiler::turboshaft::detail::input_count().
Referenced by v8::internal::compiler::turboshaft::CreateOperation(), and v8::internal::compiler::turboshaft::OperationT< Derived >::StorageSlotCount().
StorageSlotCount() [2/2]
static size_t v8::internal::compiler::turboshaft::Operation::StorageSlotCount (Opcode opcode, size_t input_count) [static]
ToString()
std::string v8::internal::compiler::turboshaft::Operation::ToString () const
Referenced by v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessCheckTurboshaftTypeOf(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessLoopPhi(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::RefineOperationType(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::RefineTypesAfterBranch(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::RefineTypesAfterBranch(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::SetType(), and v8::internal::compiler::InstructionSelector::VisitControl().
TryCast() [1/2]
template<class Op >
underlying_operation_t<Op>* v8::internal::compiler::turboshaft::Operation::TryCast () [inline]
Definition at line 986 of file operations.h.
                                        {
    if (!Is<Op>()) return nullptr;
    return static_cast<underlying_operation_t<Op>*>(this);
  }
TryCast() [2/2]
template<class Op >
const underlying_operation_t<Op>* v8::internal::compiler::turboshaft::Operation::TryCast () const [inline]
Definition at line 981 of file operations.h.
                                                    {
    if (!Is<Op>()) return nullptr;
    return static_cast<const underlying_operation_t<Op>*>(this);
  }
Referenced by v8::internal::compiler::AtomicOrder(), v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::Bind(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Bind(), v8::internal::compiler::Arm64OperandGenerator::CanBeImmediate(), v8::internal::compiler::PPCOperandGenerator::CanBeImmediate(), v8::internal::compiler::Loong64OperandGenerator::CanBeImmediate(), v8::internal::compiler::Mips64OperandGenerator::CanBeImmediate(), v8::internal::compiler::RiscvOperandGenerator::CanBeImmediate(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Change(), v8::internal::compiler::turboshaft::detail::BitfieldCheck::Detect(), v8::internal::compiler::turboshaft::LateEscapeAnalysisAnalyzer::EscapesThroughUse(), v8::internal::compiler::turboshaft::GetFlagsCondition(), v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::GetLoopIterationCount(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::InvalidateIfAlias(), v8::internal::compiler::IsBuiltinCall(), v8::internal::compiler::InstructionSelector::IsCommutative(), v8::internal::compiler::turboshaft::SLPTree::IsEqual(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::IsIntConstant(), v8::internal::compiler::turboshaft::IsSignExtensionOp(), v8::internal::compiler::InstructionSelector::IsSourcePositionUsed(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::IsWordAnd(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::LoadStoreView::LoadStoreView(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::LoadStoreView::LoadStoreView(), v8::internal::compiler::turboshaft::anonymous_namespace{decompression-optimization.cc}::DecompressionAnalyzer::MarkAddressingBase(), v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::MatchPhiCompareCst(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::MatchScaledIndex(), v8::internal::compiler::MatchScaledIndex(), v8::internal::compiler::turboshaft::PretenuringPropagationAnalyzer::OldifySubgraph(), v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::OperandForDeopt(), v8::internal::compiler::turboshaft::MemoryAnalyzer::Process(), v8::internal::compiler::turboshaft::WasmShuffleAnalyzer::Process(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessAllocateStruct(), v8::internal::compiler::turboshaft::RedundantStoreAnalysis::ProcessBlock(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::ProcessBlock(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessBlock(), v8::internal::compiler::turboshaft::MemoryAnalyzer::ProcessBlockTerminator(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessCall(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessCall(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessLoad(), v8::internal::compiler::turboshaft::WasmShuffleAnalyzer::ProcessShuffle(), v8::internal::compiler::turboshaft::DemandedElementAnalysis::RecordOp(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceMemoryIndex(), v8::internal::compiler::turboshaft::Typer::BranchRefinements::RefineTypes(), v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::ReplayMissingPredecessors(), v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::ResolveBase(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::Run(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::Run(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::Run(), v8::internal::compiler::turboshaft::ProfileApplicationPhase::Run(), v8::internal::compiler::turboshaft::Simd128UseMap::Simd128UseMap(), v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::StoreLoadInfo(), v8::internal::compiler::turboshaft::SLPTree::Try256ShuffleMatchLoad8x8U(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitCbzOrTbz(), v8::internal::compiler::turboshaft::SLPTree::TryGetExtendIntToF32x4Info(), v8::internal::compiler::TryGetRightWordConstant(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryMatchAnyExtend(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryMatchAnyShift(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::TryMatchBaseWithScaledIndexAndDisplacement(), v8::internal::compiler::TryMatchBaseWithScaledIndexAndDisplacement64(), v8::internal::compiler::TryMatchBaseWithScaledIndexAndDisplacement64ForWordBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::TryMatchBaseWithScaledIndexAndDisplacementForWordBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryMatchLoadStoreShift(), v8::internal::compiler::turboshaft::UnwrapAllocate(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitBinOp(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitBlock(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitCompareZero(), v8::internal::compiler::VisitSimdShift(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitWordCompare(), and v8::internal::compiler::InstructionSelector::VisitWordCompareZero().
V8_CLANG_NO_SANITIZE()
template<class OpmaskT >
v8::internal::compiler::turboshaft::Operation::V8_CLANG_NO_SANITIZE (`memory`) const [inline], [protected]
Definition at line 1024 of file operations.h.
                                                       {
    static_assert(std::is_same_v<
                  underlying_operation_t<OpmaskT>,
                  typename OpMaskT<typename OpmaskT::operation, OpmaskT::mask,
                                   OpmaskT::value>::operation>);
    // We check with the given mask.
    uint64_t b;
    memcpy(&b, this, sizeof(uint64_t));
    b &= OpmaskT::mask;
    return b == OpmaskT::value;
  }
References v8::internal::value.
Member Data Documentation
input_count
const uint16_t v8::internal::compiler::turboshaft::Operation::input_count
Definition at line 945 of file operations.h.
Referenced by v8::internal::compiler::turboshaft::SLPTree::BuildTreeRec(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildWasmToJSWrapper(), v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::CanBeConstantFolded(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::CanUseOptimizedWord32Compare(), v8::internal::compiler::EmitS128Load(), v8::internal::compiler::EmitSignExtendWord(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::FixLoopPhi(), v8::internal::compiler::InstructionSelector::Inputs(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::MergeFrameState(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::turboshaft::DeadCodeAnalysis::ProcessBlock(), v8::internal::compiler::turboshaft::StringEscapeAnalyzer::ProcessFrameState(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessPhi(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::ResolvePhi(), v8::internal::compiler::turboshaft::TooManyArgumentsForCall(), v8::internal::compiler::turboshaft::UseMap::UseMap(), v8::internal::compiler::VisitBinop(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitBlockBody(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitFullWord32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitFullWord32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitFullWord32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitMinOrMax(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitOptimizedWord32Compare(), v8::internal::compiler::VisitPairAtomicBinop(), v8::internal::compiler::InstructionSelector::VisitPhi(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitRO(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitRR(), v8::internal::compiler::VisitRR(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitRR(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitRR(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitRR(), v8::internal::compiler::VisitRRO(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitRRO(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitRRO(), v8::internal::compiler::VisitRRR(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitRRR(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitRRR(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitRRR(), v8::internal::compiler::VisitUniqueRRR(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitWord32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitWord32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWordCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitWordCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitWordCompare(), v8::internal::compiler::VisitWordCompare(), and v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitWordCompare().
opcode
const Opcode v8::internal::compiler::turboshaft::Operation::opcode
Definition at line 935 of file operations.h.
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphDidntThrow(), v8::internal::compiler::turboshaft::Opmask::MaskBuilder< Op, Fields >::BuildBaseMask(), v8::internal::compiler::turboshaft::SLPTree::BuildTreeRec(), v8::internal::compiler::turboshaft::CallView::CallView(), v8::internal::compiler::turboshaft::SLPTree::CanBePacked(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::DecideVectorize(), v8::internal::compiler::turboshaft::Opmask::MaskBuilder< Op, Fields >::EncodeBaseValue(), v8::internal::compiler::turboshaft::Graph::Get(), v8::internal::compiler::turboshaft::GetSimdOpcodeName(), v8::internal::compiler::turboshaft::InstructionSelectionNormalizationReducer< Next >::IsComplexConstant(), v8::internal::compiler::InstructionSelector::IsLoadOrLoadImmutable(), v8::internal::compiler::turboshaft::IsSameOpAndKind(), v8::internal::compiler::turboshaft::IsUnlikelySuccessor(), v8::internal::compiler::turboshaft::DuplicationOptimizationReducer< Next >::MaybeDuplicateCond(), v8::internal::compiler::turboshaft::operator<<(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessAnyConvertExtern(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessAssertNotNull(), v8::internal::compiler::turboshaft::RedundantStoreAnalysis::ProcessBlock(), v8::internal::compiler::turboshaft::StringEscapeAnalyzer::ProcessBlock(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::ProcessBlock(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessBlock(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessBlock(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessBlock(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessBranchOnTarget(), v8::internal::compiler::turboshaft::anonymous_namespace{decompression-optimization.cc}::DecompressionAnalyzer::ProcessOperation(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessOperations(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessPhi(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessStringAsWtf16(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessStringPrepareForGetCodeUnit(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::ProduceWord32Result(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::RefineTypeKnowledge(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::RefineTypeKnowledgeNotNull(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ResolveAliases(), v8::internal::compiler::turboshaft::RunDecompressionOptimization(), v8::internal::compiler::turboshaft::Assembler< Reducers >::SplitEdge(), v8::internal::compiler::turboshaft::SuccessorBlocks(), v8::internal::compiler::InstructionSelector::VisitControl(), v8::internal::compiler::InstructionSelector::VisitNode(), v8::internal::compiler::turboshaft::VisitOperation(), and v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitOpNoMappingUpdate().
saturated_use_count
SaturatedUint8 v8::internal::compiler::turboshaft::Operation::saturated_use_count
Definition at line 943 of file operations.h.
Referenced by v8::internal::compiler::turboshaft::DemandedElementAnalysis::AddBinaryOp(), v8::internal::compiler::turboshaft::DemandedElementAnalysis::AddUnaryOp(), v8::internal::compiler::InstructionSelector::CanDoBranchIfOverflowFusion(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Comparison(), v8::internal::compiler::turboshaft::Graph::DecrementInputUses(), v8::internal::compiler::InstructionSelector::FindProjection(), v8::internal::compiler::turboshaft::Graph::IncrementInputUses(), v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::is_exclusive_user_of(), v8::internal::compiler::turboshaft::IsInt32TruncatedLoadPattern(), v8::internal::compiler::InstructionSelector::IsOnlyUserOfNodeInSameBlock(), v8::internal::compiler::turboshaft::DuplicationOptimizationReducer< Next >::MaybeDuplicateCond(), v8::internal::compiler::turboshaft::LateEscapeAnalysisAnalyzer::RecordAllocateUse(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceCompareEqual(), v8::internal::compiler::turboshaft::Graph::Replace(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::Run(), v8::internal::compiler::turboshaft::ShouldSkipOperation(), v8::internal::compiler::turboshaft::UseMap::UseMap(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordBinop().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h