v8::internal::wasm::ParallelMove::RegisterLoad Struct Reference
Public Types
enum LoadKind : uint8_t {
kNop
, kConstant
, kStack
, kLowHalfStack
,
kHighHalfStack
 }
Static Public Member Functions
static RegisterLoad Const (ValueKind kind, int32_t constant)
static RegisterLoad Stack (int32_t offset, ValueKind kind)
static RegisterLoad HalfStack (int32_t offset, RegPairHalf half)
static RegisterLoad Nop ()
Public Attributes
LoadKind load_kind
ValueKind kind
int32_t value
Private Member Functions
RegisterLoad (LoadKind load_kind, ValueKind kind, int32_t value)
Detailed Description
Definition at line 34 of file parallel-move.h.
Member Enumeration Documentation
LoadKind
enum v8::internal::wasm::ParallelMove::RegisterLoad::LoadKind : uint8_t
Enumerator
kNop
kConstant
kStack
kLowHalfStack
kHighHalfStack
Definition at line 35 of file parallel-move.h.
                  : uint8_t {
      kNop, // no-op, used for high fp of a fp pair.
      kConstant, // load a constant value into a register.
      kStack, // fill a register from a stack slot.
      kLowHalfStack, // fill a register from the low half of a stack slot.
      kHighHalfStack // fill a register from the high half of a stack slot.
    };
Constructor & Destructor Documentation
RegisterLoad()
v8::internal::wasm::ParallelMove::RegisterLoad::RegisterLoad (LoadKind load_kind, ValueKind kind, int32_t value) [inline], [private]
Definition at line 66 of file parallel-move.h.
        : load_kind(load_kind), kind(kind), value(value) {}
Member Function Documentation
Const()
static RegisterLoad v8::internal::wasm::ParallelMove::RegisterLoad::Const (ValueKind kind, int32_t constant) [inline], [static]
Definition at line 50 of file parallel-move.h.
                                                                {
      V8_ASSUME(kind == kI32 || kind == kI64);
      return {kConstant, kind, constant};
    }
References kConstant, v8::internal::kI32, v8::internal::kI64, kind, and V8_ASSUME.
Referenced by v8::internal::wasm::ParallelMove::LoadConstant().
HalfStack()
static RegisterLoad v8::internal::wasm::ParallelMove::RegisterLoad::HalfStack (int32_t offset, RegPairHalf half) [inline], [static]
Definition at line 57 of file parallel-move.h.
                                                                    {
      return {half == kLowWord ? kLowHalfStack : kHighHalfStack, kI32, offset};
    }
References kHighHalfStack, v8::internal::kI32, kLowHalfStack, and v8::internal::wasm::kLowWord.
Referenced by v8::internal::wasm::ParallelMove::LoadI64HalfStackSlot(), and v8::internal::wasm::ParallelMove::LoadStackSlot().
Nop()
static RegisterLoad v8::internal::wasm::ParallelMove::RegisterLoad::Nop () [inline], [static]
Definition at line 60 of file parallel-move.h.
                              {
      // ValueKind does not matter.
      return {kNop, kI32, 0};
    }
References v8::internal::kI32, and kNop.
Referenced by v8::internal::wasm::ParallelMove::LoadStackSlot().
Stack()
static RegisterLoad v8::internal::wasm::ParallelMove::RegisterLoad::Stack (int32_t offset, ValueKind kind) [inline], [static]
Definition at line 54 of file parallel-move.h.
                                                              {
      return {kStack, kind, offset};
    }
References kind, and kStack.
Referenced by v8::internal::wasm::ParallelMove::LoadStackSlot().
Member Data Documentation
kind
ValueKind v8::internal::wasm::ParallelMove::RegisterLoad::kind
Definition at line 44 of file parallel-move.h.
Referenced by Const(), v8::internal::wasm::ParallelMove::ExecuteLoads(), and Stack().
load_kind
LoadKind v8::internal::wasm::ParallelMove::RegisterLoad::load_kind
Definition at line 43 of file parallel-move.h.
Referenced by v8::internal::wasm::ParallelMove::ExecuteLoads(), and v8::internal::wasm::ParallelMove::TransferToStack().
value
int32_t v8::internal::wasm::ParallelMove::RegisterLoad::value
Definition at line 47 of file parallel-move.h.
Referenced by v8::internal::wasm::ParallelMove::ExecuteLoads(), and v8::internal::wasm::ParallelMove::TransferToStack().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/wasm/baseline/parallel-move.h