v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::LoadStoreView Struct Reference
Public Member Functions
LoadStoreView (const Operation &op)
Public Attributes
OpIndex base
OptionalOpIndex index
int32_t offset
Detailed Description
Definition at line 49 of file instruction-selector-ia32.cc.
Constructor & Destructor Documentation
LoadStoreView()
v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::LoadStoreView::LoadStoreView (const Operation & op) [inline], [explicit]
Definition at line 50 of file instruction-selector-ia32.cc.
                                              {
    DCHECK(op.Is<LoadOp>() || op.Is<StoreOp>());
    if (const LoadOp* load = op.TryCast<LoadOp>()) {
      base = load->base();
      index = load->index();
      offset = load->offset;
    } else {
      DCHECK(op.Is<StoreOp>());
      const StoreOp& store = op.Cast<StoreOp>();
      base = store.base();
      index = store.index();
      offset = store.offset;
    }
  }
References v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::DCHECK(), v8::internal::index, v8::internal::compiler::turboshaft::Operation::Is(), store(), and v8::internal::compiler::turboshaft::Operation::TryCast().
Member Data Documentation
base
OpIndex v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::LoadStoreView::base
Definition at line 64 of file instruction-selector-ia32.cc.
index
OptionalOpIndex v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::LoadStoreView::index
Definition at line 65 of file instruction-selector-ia32.cc.
offset
int32_t v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::LoadStoreView::offset
Definition at line 66 of file instruction-selector-ia32.cc.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/ia32/instruction-selector-ia32.cc