v8::internal::compiler::LoopPeelingPhase Struct Reference
Public Member Functions
void Run (TFPipelineData *data, Zone *temp_zone)
Detailed Description
Definition at line 1199 of file pipeline.cc.
Member Function Documentation
Run()
void v8::internal::compiler::LoopPeelingPhase::Run (TFPipelineData * data, Zone * temp_zone) [inline]
Definition at line 1202 of file pipeline.cc.
                                                  {
    GraphTrimmer trimmer(temp_zone, data->graph());
    NodeVector roots(temp_zone);
    data->jsgraph()->GetCachedNodes(&roots);
    {
      UnparkedScopeIfNeeded scope(data->broker(),
                                  v8_flags.trace_turbo_trimming);
      trimmer.TrimGraph(roots.begin(), roots.end());
    }
    LoopTree* loop_tree = LoopFinder::BuildLoopTree(
        data->jsgraph()->graph(), &data->info()->tick_counter(), temp_zone);
    // We call the typer inside of PeelInnerLoopsOfTree which inspects heap
    // objects, so we need to unpark the local heap.
    UnparkedScopeIfNeeded scope(data->broker());
    LoopPeeler(data->graph(), data->common(), loop_tree, temp_zone,
               data->source_positions(), data->node_origins())
        .PeelInnerLoopsOfTree();
  }
References v8::internal::ZoneVector< T >::begin(), v8::internal::compiler::LoopFinder::BuildLoopTree(), v8::internal::ZoneVector< T >::end(), v8::internal::compiler::LoopPeeler::PeelInnerLoopsOfTree(), v8::internal::compiler::GraphTrimmer::TrimGraph(), and v8::internal::v8_flags.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/pipeline.cc