v8::internal::compiler::turboshaft::LoadDataViewElementOp Struct Reference
#include <operations.h>
Public Member Functions
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
OpIndex object () const
OpIndex storage () const
OpIndex index () const
OpIndex is_little_endian () const
LoadDataViewElementOp (OpIndex object, OpIndex storage, OpIndex index, OpIndex is_little_endian, ExternalArrayType element_type)
auto options () const
Public Attributes
ExternalArrayType element_type
Static Public Attributes
static constexpr OpEffects effects
Additional Inherited Members
Detailed Description
Definition at line 5927 of file operations.h.
Constructor & Destructor Documentation
LoadDataViewElementOp()
v8::internal::compiler::turboshaft::LoadDataViewElementOp::LoadDataViewElementOp (OpIndex object, OpIndex storage, OpIndex index, OpIndex is_little_endian, ExternalArrayType element_type) [inline]
Definition at line 5952 of file operations.h.
      : Base(object, storage, index, is_little_endian),
        element_type(element_type) {}
Member Function Documentation
index()
OpIndex v8::internal::compiler::turboshaft::LoadDataViewElementOp::index () const [inline]
Definition at line 5949 of file operations.h.
{ return Base::input(2); }
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::LoadDataViewElementOp::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 5939 of file operations.h.
                                                              {
    return MaybeRepVector<MaybeRegisterRepresentation::Tagged(),
                          MaybeRegisterRepresentation::Tagged(),
                          MaybeRegisterRepresentation::WordPtr(),
                          MaybeRegisterRepresentation::Word32()>();
  }
References v8::internal::compiler::turboshaft::MaybeRepVector(), v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::Tagged(), v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::Word32(), and v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::WordPtr().
is_little_endian()
OpIndex v8::internal::compiler::turboshaft::LoadDataViewElementOp::is_little_endian () const [inline]
Definition at line 5950 of file operations.h.
{ return Base::input(3); }
object()
OpIndex v8::internal::compiler::turboshaft::LoadDataViewElementOp::object () const [inline]
Definition at line 5947 of file operations.h.
{ return Base::input(0); }
options()
auto v8::internal::compiler::turboshaft::LoadDataViewElementOp::options () const [inline]
Definition at line 5959 of file operations.h.
{ return std::tuple{element_type}; }
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::LoadDataViewElementOp::outputs_rep () const [inline]
Definition at line 5935 of file operations.h.
                                                               {
    return VectorForRep(RegisterRepresentationForArrayType(element_type));
  }
References v8::internal::compiler::turboshaft::RegisterRepresentationForArrayType(), and v8::internal::compiler::turboshaft::VectorForRep().
storage()
OpIndex v8::internal::compiler::turboshaft::LoadDataViewElementOp::storage () const [inline]
Definition at line 5948 of file operations.h.
{ return Base::input(1); }
Member Data Documentation
effects
constexpr OpEffects v8::internal::compiler::turboshaft::LoadDataViewElementOp::effects [static], [constexpr]
Initial value:
= OpEffects()
                                           
                                           .CanReadMemory()
                                           
                                           .CanDependOnChecks()
Definition at line 5930 of file operations.h.
element_type
ExternalArrayType v8::internal::compiler::turboshaft::LoadDataViewElementOp::element_type
Definition at line 5928 of file operations.h.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h