v8::internal::wasm::TypeCanonicalizer::RecursionGroupRange Struct Reference
Public Member Functions
bool Contains (CanonicalTypeIndex index) const
Public Attributes
const CanonicalTypeIndex first
const CanonicalTypeIndex last
Detailed Description
Definition at line 196 of file canonical-types.h.
Member Function Documentation
Contains()
bool v8::internal::wasm::TypeCanonicalizer::RecursionGroupRange::Contains (CanonicalTypeIndex index) const [inline]
Definition at line 200 of file canonical-types.h.
                                                  {
      return base::IsInRange(index.index, first.index, last.index);
    }
References first, v8::internal::index, v8::internal::wasm::TypeIndex::index, and last.
Referenced by v8::internal::wasm::TypeCanonicalizer::CanonicalHashing::Add(), v8::internal::wasm::TypeCanonicalizer::CanonicalEquality::EqualTypeIndex(), and v8::internal::wasm::TypeCanonicalizer::CanonicalHashing::MakeGroupRelative().
Member Data Documentation
first
const CanonicalTypeIndex v8::internal::wasm::TypeCanonicalizer::RecursionGroupRange::first
Definition at line 197 of file canonical-types.h.
Referenced by v8::internal::wasm::TypeCanonicalizer::CanonicalHashing::Add(), Contains(), v8::internal::wasm::TypeCanonicalizer::CanonicalEquality::EqualTypeIndex(), and v8::internal::wasm::TypeCanonicalizer::CanonicalHashing::MakeGroupRelative().
last
const CanonicalTypeIndex v8::internal::wasm::TypeCanonicalizer::RecursionGroupRange::last
Definition at line 198 of file canonical-types.h.
Referenced by Contains().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/wasm/canonical-types.h