v8::internal::compiler::PersistentMap< Key, Value, Hasher >::FocusedTree Struct Reference
#include <persistent-map.h>
Public Types
using more_iterator = typename ZoneMap< Key, Value >::const_iterator
Public Member Functions
const FocusedTree *& path (int i)
const FocusedTree * path (int i) const
Public Attributes
KeyValue key_value
int8_t length
HashValue key_hash
const ZoneMap< Key, Value > * more
const FocusedTree * path_array [1]
Detailed Description
template<class Key, class Value, class Hasher = base::hash<Key>>
struct v8::internal::compiler::PersistentMap< Key, Value, Hasher >::FocusedTree
Definition at line 195 of file persistent-map.h.
Member Typedef Documentation
more_iterator
template<class Key , class Value , class Hasher = base::hash<Key>>
using v8::internal::compiler::PersistentMap< Key, Value, Hasher >::FocusedTree::more_iterator = typename ZoneMap<Key, Value>::const_iterator
Definition at line 203 of file persistent-map.h.
Member Function Documentation
path() [1/2]
template<class Key , class Value , class Hasher = base::hash<Key>>
const FocusedTree*& v8::internal::compiler::PersistentMap< Key, Value, Hasher >::FocusedTree::path (int i) [inline]
Definition at line 209 of file persistent-map.h.
                                  {
    DCHECK(i < length);
    return reinterpret_cast<const FocusedTree**>(
        reinterpret_cast<uint8_t*>(this) +
        offsetof(FocusedTree, path_array))[i];
  }
References v8::internal::DCHECK(), and v8::internal::length.
Referenced by v8::internal::compiler::PersistentMap< Key, Value, Hasher >::FindHash(), v8::internal::compiler::PersistentMap< Key, Value, Hasher >::GetChild(), and v8::internal::compiler::PersistentMap< Key, Value, Hasher >::Modify().
path() [2/2]
template<class Key , class Value , class Hasher = base::hash<Key>>
const FocusedTree* v8::internal::compiler::PersistentMap< Key, Value, Hasher >::FocusedTree::path (int i) const [inline]
Definition at line 215 of file persistent-map.h.
                                       {
    DCHECK(i < length);
    return reinterpret_cast<const FocusedTree* const*>(
        reinterpret_cast<const uint8_t*>(this) +
        offsetof(FocusedTree, path_array))[i];
  }
References v8::internal::DCHECK(), and v8::internal::length.
Member Data Documentation
key_hash
template<class Key , class Value , class Hasher = base::hash<Key>>
HashValue v8::internal::compiler::PersistentMap< Key, Value, Hasher >::FocusedTree::key_hash
Definition at line 200 of file persistent-map.h.
Referenced by v8::internal::compiler::PersistentMap< Key, Value, Hasher >::FindHash(), v8::internal::compiler::PersistentMap< Key, Value, Hasher >::GetChild(), v8::internal::compiler::PersistentMap< Key, Value, Hasher >::iterator::operator<(), and v8::internal::compiler::PersistentMap< Key, Value, Hasher >::iterator::operator==().
key_value
template<class Key , class Value , class Hasher = base::hash<Key>>
KeyValue v8::internal::compiler::PersistentMap< Key, Value, Hasher >::FocusedTree::key_value
Definition at line 196 of file persistent-map.h.
Referenced by v8::internal::compiler::PersistentMap< Key, Value, Hasher >::GetFocusedValue(), and v8::internal::compiler::PersistentMap< Key, Value, Hasher >::Modify().
length
template<class Key , class Value , class Hasher = base::hash<Key>>
int8_t v8::internal::compiler::PersistentMap< Key, Value, Hasher >::FocusedTree::length
Definition at line 199 of file persistent-map.h.
Referenced by v8::internal::compiler::PersistentMap< Key, Value, Hasher >::FindHash(), and v8::internal::compiler::PersistentMap< Key, Value, Hasher >::last_depth().
more
template<class Key , class Value , class Hasher = base::hash<Key>>
const ZoneMap<Key, Value>* v8::internal::compiler::PersistentMap< Key, Value, Hasher >::FocusedTree::more
Definition at line 202 of file persistent-map.h.
Referenced by v8::internal::compiler::PersistentMap< Key, Value, Hasher >::GetFocusedValue(), and v8::internal::compiler::PersistentMap< Key, Value, Hasher >::Modify().
path_array
template<class Key , class Value , class Hasher = base::hash<Key>>
const FocusedTree* v8::internal::compiler::PersistentMap< Key, Value, Hasher >::FocusedTree::path_array[1]
Definition at line 208 of file persistent-map.h.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/persistent-map.h