v8::internal::Flag Struct Reference
#include <flags-impl.h>
Public Types
enum FlagType {
TYPE_BOOL
, TYPE_MAYBE_BOOL
, TYPE_INT
, TYPE_UINT
,
TYPE_UINT64
, TYPE_FLOAT
, TYPE_SIZE_T
, TYPE_STRING
 }
enum class SetBy { kDefault
, kWeakImplication
, kImplication
, kCommandLine
 }
Public Member Functions
constexpr bool IsAnyImplication (Flag::SetBy set_by)
FlagType type () const
const char * name () const
const char * comment () const
bool PointsTo (const void *ptr) const
bool bool_variable () const
void set_bool_variable (bool value, SetBy set_by)
std::optional< bool > maybe_bool_variable () const
void set_maybe_bool_variable (std::optional< bool > value, SetBy set_by)
int int_variable () const
void set_int_variable (int value, SetBy set_by)
unsigned int uint_variable () const
void set_uint_variable (unsigned int value, SetBy set_by)
uint64_t uint64_variable () const
void set_uint64_variable (uint64_t value, SetBy set_by)
double float_variable () const
void set_float_variable (double value, SetBy set_by)
size_t size_t_variable () const
void set_size_t_variable (size_t value, SetBy set_by)
const char * string_value () const
void set_string_value (const char *new_value, bool owns_new_value, SetBy set_by)
template<typename T >
T GetDefaultValue () const
bool bool_default () const
int int_default () const
unsigned int uint_default () const
uint64_t uint64_default () const
double float_default () const
size_t size_t_default () const
const char * string_default () const
bool CheckFlagChange (SetBy new_set_by, bool change_flag, const char *implied_by=nullptr)
bool IsReadOnly () const
template<FlagType flag_type, typename T >
T GetValue () const
template<FlagType flag_type, typename T >
void SetValue (T new_value, SetBy set_by)
bool IsDefault () const
void ReleaseDynamicAllocations ()
V8_EXPORT_PRIVATE void Reset ()
void AllowOverwriting ()
Static Public Member Functions
static bool ShouldCheckFlagContradictions ()
Public Attributes
FlagType type_
const char * name_
void * valptr_
const void * defptr_
const char * cmt_
bool owns_ptr_
SetBy set_by_ = SetBy::kDefault
const char * implied_by_ = nullptr
Detailed Description
Definition at line 54 of file flags-impl.h.
Member Enumeration Documentation
FlagType
enum v8::internal::Flag::FlagType
Enumerator
TYPE_BOOL
TYPE_MAYBE_BOOL
TYPE_INT
TYPE_UINT
TYPE_UINT64
TYPE_FLOAT
TYPE_SIZE_T
TYPE_STRING
Definition at line 55 of file flags-impl.h.
                {
    TYPE_BOOL,
    TYPE_MAYBE_BOOL,
    TYPE_INT,
    TYPE_UINT,
    TYPE_UINT64,
    TYPE_FLOAT,
    TYPE_SIZE_T,
    TYPE_STRING,
  };
SetBy
enum v8::internal::Flag::SetBy [strong]
Enumerator
kDefault
kWeakImplication
kImplication
kCommandLine
Definition at line 66 of file flags-impl.h.
{ kDefault, kWeakImplication, kImplication, kCommandLine };
Member Function Documentation
AllowOverwriting()
void v8::internal::Flag::AllowOverwriting () [inline]
Definition at line 241 of file flags-impl.h.
{ set_by_ = SetBy::kDefault; }
References kDefault, and set_by_.
bool_default()
bool v8::internal::Flag::bool_default () const [inline]
Definition at line 166 of file flags-impl.h.
                            {
    DCHECK_EQ(TYPE_BOOL, type_);
    return GetDefaultValue<bool>();
  }
References DCHECK_EQ, type_, and TYPE_BOOL.
Referenced by IsDefault(), and Reset().
bool_variable()
bool v8::internal::Flag::bool_variable () const [inline]
Definition at line 108 of file flags-impl.h.
{ return GetValue<TYPE_BOOL, bool>(); }
Referenced by IsDefault(), and v8::internal::operator<<().
CheckFlagChange()
bool v8::internal::Flag::CheckFlagChange (SetBy new_set_by, bool change_flag, const char * implied_by = nullptr)
Definition at line 126 of file flags.cc.
                                                   {
  if (new_set_by == SetBy::kWeakImplication &&
      (set_by_ == SetBy::kImplication || set_by_ == SetBy::kCommandLine)) {
    return false;
  }
  if (ShouldCheckFlagContradictions()) {
    static constexpr const char kHint[] =
        "If a test variant caused this, it might be necessary to specify "
        "additional contradictory flags in "
        "tools/testrunner/local/variants.py.";
    struct FatalError : public std::ostringstream {
      // MSVC complains about non-returning destructor; disable that.
      MSVC_SUPPRESS_WARNING(4722)
      ~FatalError() { FATAL("%s.\n%s", str().c_str(), kHint); }
    };
    // Readonly flags cannot change value.
    if (change_flag && IsReadOnly()) {
      // Exit instead of abort for certain testing situations.
      if (v8_flags.exit_on_contradictory_flags) base::OS::ExitProcess(0);
      if (implied_by == nullptr) {
        FatalError{} << "Contradictory value for readonly flag "
                     << FlagName{name()};
      } else {
        DCHECK(IsAnyImplication(new_set_by));
        FatalError{} << "Contradictory value for readonly flag "
                     << FlagName{name()} << " implied by " << implied_by;
      }
    }
    // For bool flags, we only check for a conflict if the value actually
    // changes. So specifying the same flag with the same value multiple times
    // is allowed.
    // For other flags, we disallow specifying them explicitly or in the
    // presence of an implication if the value is not the same.
    // This is to simplify the rules describing conflicts in variants.py: A
    // repeated non-boolean flag is considered an error.
    bool is_bool_flag = type_ == TYPE_MAYBE_BOOL || type_ == TYPE_BOOL;
    bool check_implications = change_flag;
    switch (set_by_) {
      case SetBy::kDefault:
        break;
      case SetBy::kWeakImplication:
        if (new_set_by == SetBy::kWeakImplication && check_implications) {
          FatalError{} << "Contradictory weak flag implications from "
                       << FlagName{implied_by_} << " and "
                       << FlagName{implied_by} << " for flag "
                       << FlagName{name()};
        }
        break;
      case SetBy::kImplication:
        if (new_set_by == SetBy::kImplication && check_implications) {
          FatalError{} << "Contradictory flag implications from "
                       << FlagName{implied_by_} << " and "
                       << FlagName{implied_by} << " for flag "
                       << FlagName{name()};
        }
        break;
      case SetBy::kCommandLine:
        if (new_set_by == SetBy::kImplication && check_implications) {
          // Exit instead of abort for certain testing situations.
          if (v8_flags.exit_on_contradictory_flags) base::OS::ExitProcess(0);
          if (is_bool_flag) {
            FatalError{} << "Flag " << FlagName{name()} << ": value implied by "
                         << FlagName{implied_by}
                         << " conflicts with explicit specification";
          } else {
            FatalError{} << "Flag " << FlagName{name()} << " is implied by "
                         << FlagName{implied_by}
                         << " but also specified explicitly";
          }
        } else if (new_set_by == SetBy::kCommandLine && check_implications) {
          // Exit instead of abort for certain testing situations.
          if (v8_flags.exit_on_contradictory_flags) base::OS::ExitProcess(0);
          if (is_bool_flag) {
            FatalError{} << "Command-line provided flag " << FlagName{name()}
                         << " specified as both true and false";
          } else {
            FatalError{} << "Command-line provided flag " << FlagName{name()}
                         << " specified multiple times";
          }
        }
        break;
    }
  }
  if (change_flag && IsReadOnly()) {
    // Readonly flags must never change value.
    return false;
  }
  set_by_ = new_set_by;
  if (IsAnyImplication(new_set_by)) {
    DCHECK_NOT_NULL(implied_by);
    implied_by_ = implied_by;
#ifdef DEBUG
    // This only works when implied_by is a flag_name or !flag_name, but it
    // can also be a condition e.g. flag_name > 3. Since this is only used for
    // checks in DEBUG mode, we will just ignore the more complex conditions
    // for now - that will just lead to a nullptr which won't be followed.
    implied_by_ptr_ = static_cast<Flag*>(FindImplicationFlagByName(
        implied_by[0] == '!' ? implied_by + 1 : implied_by));
    DCHECK_NE(implied_by_ptr_, this);
#endif
  }
  return change_flag;
}
References v8::internal::DCHECK(), DCHECK_NE, DCHECK_NOT_NULL, v8::base::OS::ExitProcess(), FATAL, v8::internal::FindImplicationFlagByName(), implied_by_, IsAnyImplication(), IsReadOnly(), kCommandLine, kDefault, kImplication, kWeakImplication, MSVC_SUPPRESS_WARNING, name(), set_by_, ShouldCheckFlagContradictions(), type_, TYPE_BOOL, TYPE_MAYBE_BOOL, and v8::internal::v8_flags.
Referenced by set_string_value(), SetValue(), and v8::internal::anonymous_namespace{flags.cc}::ImplicationProcessor::TriggerImplication().
comment()
const char* v8::internal::Flag::comment () const [inline]
Definition at line 90 of file flags-impl.h.
{ return cmt_; }
References cmt_.
float_default()
double v8::internal::Flag::float_default () const [inline]
Definition at line 186 of file flags-impl.h.
                               {
    DCHECK_EQ(TYPE_FLOAT, type_);
    return GetDefaultValue<double>();
  }
References DCHECK_EQ, type_, and TYPE_FLOAT.
Referenced by IsDefault(), and Reset().
float_variable()
double v8::internal::Flag::float_variable () const [inline]
Definition at line 142 of file flags-impl.h.
{ return GetValue<TYPE_FLOAT, double>(); }
Referenced by IsDefault(), and v8::internal::operator<<().
GetDefaultValue()
template<typename T >
T v8::internal::Flag::GetDefaultValue () const [inline]
Definition at line 162 of file flags-impl.h.
                            {
    return *reinterpret_cast<const T*>(defptr_);
  }
References defptr_.
Referenced by v8::internal::anonymous_namespace{flags.cc}::ImplicationProcessor::TriggerImplication().
GetValue()
template<FlagType flag_type, typename T >
T v8::internal::Flag::GetValue () const [inline]
Definition at line 216 of file flags-impl.h.
                     {
    DCHECK_EQ(flag_type, type_);
    if (IsReadOnly()) return GetDefaultValue<T>();
    return *reinterpret_cast<const FlagValue<T>*>(valptr_);
  }
References DCHECK_EQ, IsReadOnly(), type_, and valptr_.
int_default()
int v8::internal::Flag::int_default () const [inline]
Definition at line 171 of file flags-impl.h.
                          {
    DCHECK_EQ(TYPE_INT, type_);
    return GetDefaultValue<int>();
  }
References DCHECK_EQ, type_, and TYPE_INT.
Referenced by IsDefault(), and Reset().
int_variable()
int v8::internal::Flag::int_variable () const [inline]
Definition at line 122 of file flags-impl.h.
{ return GetValue<TYPE_INT, int>(); }
Referenced by IsDefault(), and v8::internal::operator<<().
IsAnyImplication()
constexpr bool v8::internal::Flag::IsAnyImplication (Flag::SetBy set_by) [inline], [constexpr]
Definition at line 68 of file flags-impl.h.
                                                    {
    return set_by == SetBy::kWeakImplication || set_by == SetBy::kImplication;
  }
References kImplication, and kWeakImplication.
Referenced by CheckFlagChange().
IsDefault()
bool v8::internal::Flag::IsDefault () const
Definition at line 231 of file flags.cc.
                           {
  switch (type_) {
    case TYPE_BOOL:
      return bool_variable() == bool_default();
    case TYPE_MAYBE_BOOL:
      return maybe_bool_variable().has_value() == false;
    case TYPE_INT:
      return int_variable() == int_default();
    case TYPE_UINT:
      return uint_variable() == uint_default();
    case TYPE_UINT64:
      return uint64_variable() == uint64_default();
    case TYPE_FLOAT:
      return float_variable() == float_default();
    case TYPE_SIZE_T:
      return size_t_variable() == size_t_default();
    case TYPE_STRING: {
      const char* str1 = string_value();
      const char* str2 = string_default();
      if (str2 == nullptr) return str1 == nullptr;
      if (str1 == nullptr) return str2 == nullptr;
      return strcmp(str1, str2) == 0;
    }
  }
  UNREACHABLE();
}
References bool_default(), bool_variable(), float_default(), float_variable(), int_default(), int_variable(), maybe_bool_variable(), size_t_default(), size_t_variable(), string_default(), string_value(), type_, TYPE_BOOL, TYPE_FLOAT, TYPE_INT, TYPE_MAYBE_BOOL, TYPE_SIZE_T, TYPE_STRING, TYPE_UINT, TYPE_UINT64, uint64_default(), uint64_variable(), uint_default(), uint_variable(), and v8::internal::UNREACHABLE().
IsReadOnly()
bool v8::internal::Flag::IsReadOnly () const [inline]
Definition at line 210 of file flags-impl.h.
                          {
    // See the FLAG_READONLY definition for FLAG_MODE_META.
    return valptr_ == nullptr;
  }
References valptr_.
Referenced by CheckFlagChange(), GetValue(), set_string_value(), SetValue(), and v8::internal::anonymous_namespace{flags.cc}::ImplicationProcessor::TriggerImplication().
maybe_bool_variable()
std::optional<bool> v8::internal::Flag::maybe_bool_variable () const [inline]
Definition at line 114 of file flags-impl.h.
                                                {
    return GetValue<TYPE_MAYBE_BOOL, std::optional<bool>>();
  }
Referenced by IsDefault(), and v8::internal::operator<<().
name()
const char* v8::internal::Flag::name () const [inline]
Definition at line 88 of file flags-impl.h.
{ return name_; }
References name_.
Referenced by CheckFlagChange(), v8::internal::FindFlagByName(), v8::internal::FindImplicationFlagByName(), v8::internal::FlagNameGreater::operator()(), v8::internal::FlagLess::operator()(), v8::internal::operator<<(), and v8::internal::anonymous_namespace{flags.cc}::ImplicationProcessor::TriggerImplication().
PointsTo()
bool v8::internal::Flag::PointsTo (const void * ptr) const [inline]
Definition at line 92 of file flags-impl.h.
{ return valptr_ == ptr; }
References valptr_.
ReleaseDynamicAllocations()
void v8::internal::Flag::ReleaseDynamicAllocations ()
Definition at line 258 of file flags.cc.
                                     {
  if (type_ != TYPE_STRING) return;
  if (owns_ptr_) DeleteArray(string_value());
}
References owns_ptr_, string_value(), type_, and TYPE_STRING.
Referenced by v8::internal::FlagList::ReleaseDynamicAllocations().
Reset()
void v8::internal::Flag::Reset ()
Definition at line 263 of file flags.cc.
                 {
  switch (type_) {
    case TYPE_BOOL:
      set_bool_variable(bool_default(), SetBy::kDefault);
      break;
    case TYPE_MAYBE_BOOL:
      set_maybe_bool_variable(std::nullopt, SetBy::kDefault);
      break;
    case TYPE_INT:
      set_int_variable(int_default(), SetBy::kDefault);
      break;
    case TYPE_UINT:
      set_uint_variable(uint_default(), SetBy::kDefault);
      break;
    case TYPE_UINT64:
      set_uint64_variable(uint64_default(), SetBy::kDefault);
      break;
    case TYPE_FLOAT:
      set_float_variable(float_default(), SetBy::kDefault);
      break;
    case TYPE_SIZE_T:
      set_size_t_variable(size_t_default(), SetBy::kDefault);
      break;
    case TYPE_STRING:
      set_string_value(string_default(), false, SetBy::kDefault);
      break;
  }
}
References bool_default(), float_default(), int_default(), kDefault, set_bool_variable(), set_float_variable(), set_int_variable(), set_maybe_bool_variable(), set_size_t_variable(), set_string_value(), set_uint64_variable(), set_uint_variable(), size_t_default(), string_default(), type_, TYPE_BOOL, TYPE_FLOAT, TYPE_INT, TYPE_MAYBE_BOOL, TYPE_SIZE_T, TYPE_STRING, TYPE_UINT, TYPE_UINT64, uint64_default(), and uint_default().
Referenced by ShouldCheckFlagContradictions().
set_bool_variable()
void v8::internal::Flag::set_bool_variable (bool value, SetBy set_by) [inline]
Definition at line 110 of file flags-impl.h.
                                                   {
    SetValue<TYPE_BOOL, bool>(value, set_by);
  }
References v8::internal::value.
Referenced by Reset(), and v8::internal::FlagList::SetFlagsFromCommandLine().
set_float_variable()
void v8::internal::Flag::set_float_variable (double value, SetBy set_by) [inline]
Definition at line 144 of file flags-impl.h.
                                                      {
    SetValue<TYPE_FLOAT, double>(value, set_by);
  }
References v8::internal::value.
Referenced by Reset(), and v8::internal::FlagList::SetFlagsFromCommandLine().
set_int_variable()
void v8::internal::Flag::set_int_variable (int value, SetBy set_by) [inline]
Definition at line 124 of file flags-impl.h.
                                                 {
    SetValue<TYPE_INT, int>(value, set_by);
  }
References v8::internal::value.
Referenced by Reset(), and v8::internal::FlagList::SetFlagsFromCommandLine().
set_maybe_bool_variable()
void v8::internal::Flag::set_maybe_bool_variable (std::optional< bool > value, SetBy set_by) [inline]
Definition at line 118 of file flags-impl.h.
                                                                      {
    SetValue<TYPE_MAYBE_BOOL, std::optional<bool>>(value, set_by);
  }
References v8::internal::value.
Referenced by Reset(), and v8::internal::FlagList::SetFlagsFromCommandLine().
set_size_t_variable()
void v8::internal::Flag::set_size_t_variable (size_t value, SetBy set_by) [inline]
Definition at line 150 of file flags-impl.h.
                                                       {
    SetValue<TYPE_SIZE_T, size_t>(value, set_by);
  }
References v8::internal::value.
Referenced by Reset(), and v8::internal::FlagList::SetFlagsFromCommandLine().
set_string_value()
void v8::internal::Flag::set_string_value (const char * new_value, bool owns_new_value, SetBy set_by)
Definition at line 95 of file flags.cc.
                                          {
  DCHECK_EQ(TYPE_STRING, type_);
  DCHECK_IMPLIES(owns_new_value, new_value != nullptr);
  const char* old_value = string_value();
  DCHECK_IMPLIES(owns_ptr_, old_value != nullptr);
  bool change_flag = old_value
                         ? !new_value || std::strcmp(old_value, new_value) != 0
                         : !!new_value;
  change_flag = CheckFlagChange(set_by, change_flag);
  if (change_flag) {
    DCHECK(!IsReadOnly());
    if (owns_ptr_) DeleteArray(old_value);
    *reinterpret_cast<FlagValue<const char*>*>(valptr_) = new_value;
    owns_ptr_ = owns_new_value;
  } else {
    if (owns_new_value) DeleteArray(new_value);
  }
}
References CheckFlagChange(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, IsReadOnly(), owns_ptr_, string_value(), type_, TYPE_STRING, and valptr_.
Referenced by Reset(), and v8::internal::FlagList::SetFlagsFromCommandLine().
set_uint64_variable()
void v8::internal::Flag::set_uint64_variable (uint64_t value, SetBy set_by) [inline]
Definition at line 138 of file flags-impl.h.
                                                         {
    SetValue<TYPE_UINT64, uint64_t>(value, set_by);
  }
References v8::internal::value.
Referenced by Reset(), and v8::internal::FlagList::SetFlagsFromCommandLine().
set_uint_variable()
void v8::internal::Flag::set_uint_variable (unsigned int value, SetBy set_by) [inline]
Definition at line 132 of file flags-impl.h.
                                                           {
    SetValue<TYPE_UINT, unsigned int>(value, set_by);
  }
References v8::internal::value.
Referenced by Reset(), and v8::internal::FlagList::SetFlagsFromCommandLine().
SetValue()
template<FlagType flag_type, typename T >
void v8::internal::Flag::SetValue (T new_value, SetBy set_by) [inline]
Definition at line 223 of file flags-impl.h.
                                           {
    DCHECK_EQ(flag_type, type_);
    bool change_flag = GetValue<flag_type, T>() != new_value;
    change_flag = CheckFlagChange(set_by, change_flag);
    if (change_flag) {
      DCHECK(!IsReadOnly());
      *reinterpret_cast<FlagValue<T>*>(valptr_) = new_value;
    }
  }
References CheckFlagChange(), v8::internal::DCHECK(), DCHECK_EQ, IsReadOnly(), type_, and valptr_.
ShouldCheckFlagContradictions()
bool v8::internal::Flag::ShouldCheckFlagContradictions () [static]
Definition at line 115 of file flags.cc.
                                         {
  if (v8_flags.allow_overwriting_for_next_flag) {
    // Setting the flag manually to false before calling Reset() avoids this
    // becoming re-entrant.
    v8_flags.allow_overwriting_for_next_flag = false;
    FindFlagByPointer(&v8_flags.allow_overwriting_for_next_flag)->Reset();
    return false;
  }
  return v8_flags.abort_on_contradictory_flags && !v8_flags.fuzzing;
}
References v8::internal::FindFlagByPointer(), Reset(), and v8::internal::v8_flags.
Referenced by CheckFlagChange().
size_t_default()
size_t v8::internal::Flag::size_t_default () const [inline]
Definition at line 191 of file flags-impl.h.
                                {
    DCHECK_EQ(TYPE_SIZE_T, type_);
    return GetDefaultValue<size_t>();
  }
References DCHECK_EQ, type_, and TYPE_SIZE_T.
Referenced by IsDefault(), and Reset().
size_t_variable()
size_t v8::internal::Flag::size_t_variable () const [inline]
Definition at line 148 of file flags-impl.h.
{ return GetValue<TYPE_SIZE_T, size_t>(); }
Referenced by IsDefault(), and v8::internal::operator<<().
string_default()
const char* v8::internal::Flag::string_default () const [inline]
Definition at line 196 of file flags-impl.h.
                                     {
    DCHECK_EQ(TYPE_STRING, type_);
    return GetDefaultValue<const char*>();
  }
References DCHECK_EQ, type_, and TYPE_STRING.
Referenced by IsDefault(), and Reset().
string_value()
const char* v8::internal::Flag::string_value () const [inline]
Definition at line 154 of file flags-impl.h.
                                   {
    return GetValue<TYPE_STRING, const char*>();
  }
Referenced by IsDefault(), v8::internal::operator<<(), ReleaseDynamicAllocations(), and set_string_value().
type()
FlagType v8::internal::Flag::type () const [inline]
Definition at line 86 of file flags-impl.h.
{ return type_; }
References type_.
Referenced by v8::internal::operator<<(), v8::internal::FlagList::SetFlagsFromCommandLine(), and v8::internal::TryParseUnsigned().
uint64_default()
uint64_t v8::internal::Flag::uint64_default () const [inline]
Definition at line 181 of file flags-impl.h.
                                  {
    DCHECK_EQ(TYPE_UINT64, type_);
    return GetDefaultValue<uint64_t>();
  }
References DCHECK_EQ, type_, and TYPE_UINT64.
Referenced by IsDefault(), and Reset().
uint64_variable()
uint64_t v8::internal::Flag::uint64_variable () const [inline]
Definition at line 136 of file flags-impl.h.
{ return GetValue<TYPE_UINT64, uint64_t>(); }
Referenced by IsDefault(), and v8::internal::operator<<().
uint_default()
unsigned int v8::internal::Flag::uint_default () const [inline]
Definition at line 176 of file flags-impl.h.
                                    {
    DCHECK_EQ(TYPE_UINT, type_);
    return GetDefaultValue<unsigned int>();
  }
References DCHECK_EQ, type_, and TYPE_UINT.
Referenced by IsDefault(), and Reset().
uint_variable()
unsigned int v8::internal::Flag::uint_variable () const [inline]
Definition at line 128 of file flags-impl.h.
                                     {
    return GetValue<TYPE_UINT, unsigned int>();
  }
Referenced by IsDefault(), and v8::internal::operator<<().
Member Data Documentation
cmt_
const char* v8::internal::Flag::cmt_
Definition at line 76 of file flags-impl.h.
Referenced by comment().
defptr_
const void* v8::internal::Flag::defptr_
Definition at line 75 of file flags-impl.h.
Referenced by GetDefaultValue().
implied_by_
const char* v8::internal::Flag::implied_by_ = nullptr
Definition at line 80 of file flags-impl.h.
Referenced by CheckFlagChange().
name_
const char* v8::internal::Flag::name_
Definition at line 73 of file flags-impl.h.
Referenced by name().
owns_ptr_
bool v8::internal::Flag::owns_ptr_
Definition at line 77 of file flags-impl.h.
Referenced by ReleaseDynamicAllocations(), and set_string_value().
set_by_
SetBy v8::internal::Flag::set_by_ = SetBy::kDefault
Definition at line 78 of file flags-impl.h.
Referenced by AllowOverwriting(), and CheckFlagChange().
type_
FlagType v8::internal::Flag::type_
Definition at line 72 of file flags-impl.h.
Referenced by bool_default(), CheckFlagChange(), float_default(), GetValue(), int_default(), IsDefault(), ReleaseDynamicAllocations(), Reset(), set_string_value(), SetValue(), size_t_default(), string_default(), type(), uint64_default(), and uint_default().
valptr_
void* v8::internal::Flag::valptr_
Definition at line 74 of file flags-impl.h.
Referenced by GetValue(), IsReadOnly(), PointsTo(), set_string_value(), and SetValue().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/flags/flags-impl.h
/mnt/V8SourceCode/src/flags/flags.cc