v8::internal::anonymous_namespace{debug-wasm-objects.cc}::LocalsProxy Struct Reference
Static Public Member Functions
static DirectHandle< JSObject > Create (WasmFrame *frame)
static uint32_t Count (Isolate *isolate, DirectHandle< FixedArray > values)
static DirectHandle< Object > Get (Isolate *isolate, DirectHandle< FixedArray > values, uint32_t index)
static DirectHandle< String > GetName (Isolate *isolate, DirectHandle< FixedArray > values, uint32_t index)
Static Public Attributes
static constexpr char const * kClassName = `Locals`
Additional Inherited Members
Detailed Description
Definition at line 410 of file debug-wasm-objects.cc.
Member Function Documentation
Count()
static uint32_t v8::internal::anonymous_namespace{debug-wasm-objects.cc}::LocalsProxy::Count (Isolate * isolate, DirectHandle< FixedArray > values) [inline], [static]
Definition at line 431 of file debug-wasm-objects.cc.
                                                                           {
    return values->length() - 2;
  }
Create()
static DirectHandle<JSObject> v8::internal::anonymous_namespace{debug-wasm-objects.cc}::LocalsProxy::Create (WasmFrame * frame) [inline], [static]
Definition at line 413 of file debug-wasm-objects.cc.
                                                         {
    auto isolate = frame->isolate();
    auto debug_info = frame->native_module()->GetDebugInfo();
    // TODO(bmeurer): Check if pc is inspectable.
    int count = debug_info->GetNumLocals(frame->pc(), isolate);
    auto function = debug_info->GetFunctionAtAddress(frame->pc(), isolate);
    auto values = isolate->factory()->NewFixedArray(count + 2);
    for (int i = 0; i < count; ++i) {
      auto value = WasmValueObject::New(
          isolate, debug_info->GetLocalValue(i, frame->pc(), frame->fp(),
                                             frame->callee_fp(), isolate));
      values->set(i, *value);
    }
    values->set(count + 0, frame->wasm_instance()->module_object());
    values->set(count + 1, Smi::FromInt(function.func_index));
    return NamedDebugProxy::Create(isolate, values);
  }
References v8::internal::Isolate::factory(), v8::internal::Smi::FromInt(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::Factory::isolate(), v8::internal::WasmValueObject::New(), v8::internal::FactoryBase< Impl >::NewFixedArray(), and v8::internal::value.
Get()
static DirectHandle<Object> v8::internal::anonymous_namespace{debug-wasm-objects.cc}::LocalsProxy::Get (Isolate * isolate, DirectHandle< FixedArray > values, uint32_t index) [inline], [static]
Definition at line 435 of file debug-wasm-objects.cc.
                                                  {
    return direct_handle(values->get(index), isolate);
  }
References v8::internal::direct_handle(), and v8::internal::index.
GetName()
static DirectHandle<String> v8::internal::anonymous_namespace{debug-wasm-objects.cc}::LocalsProxy::GetName (Isolate * isolate, DirectHandle< FixedArray > values, uint32_t index) [inline], [static]
Definition at line 441 of file debug-wasm-objects.cc.
                                                      {
    uint32_t count = Count(isolate, values);
    auto native_module =
        Cast<WasmModuleObject>(values->get(count + 0))->native_module();
    auto function_index = Smi::ToInt(Cast<Smi>(values->get(count + 1)));
    wasm::NamesProvider* names = native_module->GetNamesProvider();
    StringBuilder sb;
    names->PrintLocalName(sb, function_index, index);
    return ToInternalString(sb, isolate);
  }
References v8::internal::index, v8::internal::wasm::NamesProvider::PrintLocalName(), v8::internal::Smi::ToInt(), and v8::internal::anonymous_namespace{debug-wasm-objects.cc}::ToInternalString().
Member Data Documentation
kClassName
constexpr char const* v8::internal::anonymous_namespace{debug-wasm-objects.cc}::LocalsProxy::kClassName = `Locals` [static], [constexpr]
Definition at line 411 of file debug-wasm-objects.cc.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/debug/debug-wasm-objects.cc