v8::internal::torque::NamespaceConstantInstruction Struct Reference
#include <instructions.h>
Public Member Functions
NamespaceConstantInstruction (NamespaceConstant *constant)
std::size_t GetValueDefinitionCount () const
DefinitionLocation GetValueDefinition (std::size_t index) const
Public Attributes
NamespaceConstant * constant
Detailed Description
Definition at line 366 of file instructions.h.
Constructor & Destructor Documentation
NamespaceConstantInstruction()
v8::internal::torque::NamespaceConstantInstruction::NamespaceConstantInstruction (NamespaceConstant * constant) [inline], [explicit]
Definition at line 368 of file instructions.h.
      : constant(constant) {}
Member Function Documentation
GetValueDefinition()
DefinitionLocation v8::internal::torque::NamespaceConstantInstruction::GetValueDefinition (std::size_t index) const
Definition at line 127 of file instructions.cc.
                           {
  DCHECK_LT(index, GetValueDefinitionCount());
  return DefinitionLocation::Instruction(this, index);
}
References DCHECK_LT, GetValueDefinitionCount(), v8::internal::index, and v8::internal::torque::DefinitionLocation::Instruction().
GetValueDefinitionCount()
std::size_t v8::internal::torque::NamespaceConstantInstruction::GetValueDefinitionCount () const
Definition at line 123 of file instructions.cc.
                                                                      {
  return LowerType(constant->type()).size();
}
References constant, v8::internal::torque::LowerType(), and v8::internal::torque::Value::type().
Referenced by GetValueDefinition().
Member Data Documentation
constant
NamespaceConstant* v8::internal::torque::NamespaceConstantInstruction::constant
Definition at line 374 of file instructions.h.
Referenced by GetValueDefinitionCount(), and v8::internal::torque::operator<<().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/torque/instructions.h
/mnt/V8SourceCode/src/torque/instructions.cc