v8::internal::compiler::turboshaft::FindOrderedHashEntryOp Struct Reference
#include <operations.h>
Public Types
enum class Kind : uint8_t { kFindOrderedHashMapEntry
, kFindOrderedHashMapEntryForInt32Key
, kFindOrderedHashSetEntry
 }
Public Member Functions
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
OpIndex data_structure () const
V< Word32 > key () const
FindOrderedHashEntryOp (OpIndex data_structure, V< Word32 > key, Kind kind)
auto options () const
Public Attributes
Kind kind
Static Public Attributes
static constexpr OpEffects effects
Additional Inherited Members
Detailed Description
Definition at line 6695 of file operations.h.
Member Enumeration Documentation
Kind
enum v8::internal::compiler::turboshaft::FindOrderedHashEntryOp::Kind : uint8_t [strong]
Enumerator
kFindOrderedHashMapEntry
kFindOrderedHashMapEntryForInt32Key
kFindOrderedHashSetEntry
Definition at line 6697 of file operations.h.
                  : uint8_t {
    kFindOrderedHashMapEntry,
    kFindOrderedHashMapEntryForInt32Key,
    kFindOrderedHashSetEntry,
  };
Constructor & Destructor Documentation
FindOrderedHashEntryOp()
v8::internal::compiler::turboshaft::FindOrderedHashEntryOp::FindOrderedHashEntryOp (OpIndex data_structure, V< Word32 > key, Kind kind) [inline]
Definition at line 6728 of file operations.h.
      : Base(data_structure, key), kind(kind) {}
Member Function Documentation
data_structure()
OpIndex v8::internal::compiler::turboshaft::FindOrderedHashEntryOp::data_structure () const [inline]
Definition at line 6725 of file operations.h.
{ return Base::input(0); }
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::FindOrderedHashEntryOp::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 6716 of file operations.h.
                                                              {
    return kind == Kind::kFindOrderedHashMapEntryForInt32Key
               ? MaybeRepVector<MaybeRegisterRepresentation::Tagged(),
                                MaybeRegisterRepresentation::Word32()>()
               : MaybeRepVector<MaybeRegisterRepresentation::Tagged(),
                                MaybeRegisterRepresentation::Tagged()>();
  }
References v8::internal::compiler::turboshaft::MaybeRepVector(), v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::Tagged(), and v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::Word32().
key()
V<Word32> v8::internal::compiler::turboshaft::FindOrderedHashEntryOp::key () const [inline]
Definition at line 6726 of file operations.h.
{ return Base::input<Word32>(1); }
options()
auto v8::internal::compiler::turboshaft::FindOrderedHashEntryOp::options () const [inline]
Definition at line 6732 of file operations.h.
{ return std::tuple{kind}; }
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::FindOrderedHashEntryOp::outputs_rep () const [inline]
Definition at line 6706 of file operations.h.
                                                               {
    switch (kind) {
      case Kind::kFindOrderedHashMapEntry:
      case Kind::kFindOrderedHashSetEntry:
        return RepVector<RegisterRepresentation::Tagged()>();
      case Kind::kFindOrderedHashMapEntryForInt32Key:
        return RepVector<RegisterRepresentation::WordPtr()>();
    }
  }
Member Data Documentation
effects
constexpr OpEffects v8::internal::compiler::turboshaft::FindOrderedHashEntryOp::effects [static], [constexpr]
Initial value:
=
      OpEffects().CanDependOnChecks().CanReadMemory().CanAllocate()
Definition at line 6704 of file operations.h.
kind
Kind v8::internal::compiler::turboshaft::FindOrderedHashEntryOp::kind
Definition at line 6702 of file operations.h.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h