v8::internal::compiler::turboshaft::CsaEffectsComputationPhase Struct Reference
#include <csa-effects-computation.h>
Public Member Functions
void Run (PipelineData *data, Zone *temp_zone)
Detailed Description
Definition at line 37 of file csa-effects-computation.h.
Member Function Documentation
Run()
void v8::internal::compiler::turboshaft::CsaEffectsComputationPhase::Run (PipelineData * data, Zone * temp_zone)
Definition at line 101 of file csa-effects-computation.cc.
                                                                        {
  // We need to unpark the local heap so that we can look if HeapConstants are
  // builtin code or not.
  UnparkedScopeIfNeeded scope(data->broker());
  Builtin builtin = data->info()->builtin();
  BuiltinAllocateEffect can_allocate = BuiltinAllocateEffect::kNo;
  std::unordered_set<Builtin> called_builtins;
  for (const Operation& op : data->graph().AllOperations()) {
    switch (op.opcode) {
      case Opcode::kAllocate:
        can_allocate = BuiltinAllocateEffect::kYes;
        break;
      case Opcode::kCall:
      case Opcode::kTailCall:
        AnalyzeCall(CallView{op}, called_builtins, &can_allocate, data->graph(),
                    builtin);
        break;
      default:
        break;
    }
  }
  data->isolate()->builtins_effects_analyzer()->RegisterInitialEffects(
      builtin, can_allocate, called_builtins);
}
References v8::internal::compiler::turboshaft::Graph::AllOperations(), v8::internal::compiler::turboshaft::AnalyzeCall(), v8::internal::compiler::turboshaft::PipelineData::broker(), v8::internal::OptimizedCompilationInfo::builtin(), v8::internal::Isolate::builtins_effects_analyzer(), v8::internal::compiler::turboshaft::PipelineData::graph(), v8::internal::compiler::turboshaft::PipelineData::info(), v8::internal::compiler::turboshaft::PipelineData::isolate(), v8::internal::kNo, v8::internal::wasm::kTailCall, v8::internal::kYes, and v8::internal::BuiltinsEffectsAnalyzer::RegisterInitialEffects().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/csa-effects-computation.h
/mnt/V8SourceCode/src/compiler/turboshaft/csa-effects-computation.cc