v8::internal::PerfettoV8String::Hasher Struct Reference
#include <perfetto-utils.h>
Public Member Functions
size_t operator() (const PerfettoV8String &s) const
Detailed Description
Definition at line 54 of file perfetto-utils.h.
Member Function Documentation
operator()()
size_t v8::internal::PerfettoV8String::Hasher::operator() (const PerfettoV8String & s) const [inline]
Definition at line 55 of file perfetto-utils.h.
                                                       {
      base::Hasher hash;
      hash.AddRange(s.buffer_.get(), s.buffer_.get() + s.size_);
      hash.Combine(s.is_one_byte_);
      return hash.hash();
    }
References v8::base::Hasher::AddRange(), v8::internal::PerfettoV8String::buffer_, v8::base::Hasher::Combine(), v8::base::Hasher::hash(), v8::internal::PerfettoV8String::is_one_byte_, and v8::internal::PerfettoV8String::size_.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/tracing/perfetto-utils.h