v8::internal::compiler::turboshaft::AtomicRMWOp Struct Reference
#include <operations.h>
Public Types
enum class BinOp : uint8_t {
kAdd
, kSub
, kAnd
, kOr
,
kXor
, kExchange
, kCompareExchange
 }
Public Member Functions
OpEffects Effects () const
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
V< Any > base () const
V< WordPtr > index () const
OpIndex value () const
OptionalOpIndex expected () const
void Validate (const Graph &graph) const
AtomicRMWOp (OpIndex base, OpIndex index, OpIndex value, OptionalOpIndex expected, BinOp bin_op, RegisterRepresentation in_out_rep, MemoryRepresentation memory_rep, MemoryAccessKind kind, RegisterRepresentation base_rep)
template<typename Fn , typename Mapper >
auto Explode (Fn fn, Mapper &mapper) const
void PrintInputs (std::ostream &os, const std::string &op_index_prefix) const
void PrintOptions (std::ostream &os) const
auto options () const
Static Public Member Functions
static AtomicRMWOp & New (Graph *graph, OpIndex base, V< WordPtr > index, OpIndex value, OptionalOpIndex expected, BinOp bin_op, RegisterRepresentation result_rep, MemoryRepresentation input_rep, MemoryAccessKind kind, RegisterRepresentation base_rep)
Public Attributes
BinOp bin_op
RegisterRepresentation in_out_rep
MemoryRepresentation memory_rep
MemoryAccessKind memory_access_kind
RegisterRepresentation base_rep
Additional Inherited Members
Detailed Description
Definition at line 3089 of file operations.h.
Member Enumeration Documentation
BinOp
enum v8::internal::compiler::turboshaft::AtomicRMWOp::BinOp : uint8_t [strong]
Enumerator
kAdd
kSub
kAnd
kOr
kXor
kExchange
kCompareExchange
Definition at line 3090 of file operations.h.
                   : uint8_t {
    kAdd,
    kSub,
    kAnd,
    kOr,
    kXor,
    kExchange,
    kCompareExchange
  };
Constructor & Destructor Documentation
AtomicRMWOp()
v8::internal::compiler::turboshaft::AtomicRMWOp::AtomicRMWOp (OpIndex base, OpIndex index, OpIndex value, OptionalOpIndex expected, BinOp bin_op, RegisterRepresentation in_out_rep, MemoryRepresentation memory_rep, MemoryAccessKind kind, RegisterRepresentation base_rep) [inline]
Definition at line 3143 of file operations.h.
      : Base(3 + expected.valid()),
        bin_op(bin_op),
        in_out_rep(in_out_rep),
        memory_rep(memory_rep),
        memory_access_kind(kind),
        base_rep(base_rep) {
    input(0) = base;
    input(1) = index;
    input(2) = value;
    if (expected.valid()) {
      input(3) = expected.value();
    }
  }
References v8::internal::index, v8::internal::compiler::turboshaft::OptionalOpIndex::valid(), v8::internal::compiler::turboshaft::OptionalOpIndex::value(), and v8::internal::value.
Member Function Documentation
base()
V<Any> v8::internal::compiler::turboshaft::AtomicRMWOp::base () const [inline]
Definition at line 3128 of file operations.h.
{ return input<Any>(0); }
Referenced by PrintInputs(), v8::internal::compiler::VisitAtomicBinaryOperation(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicBinop(), v8::internal::compiler::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitAtomicBinOp(), v8::internal::compiler::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitAtomicCompareExchange(), v8::internal::compiler::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitAtomicExchange(), and v8::internal::compiler::InstructionSelector::VisitWord32AtomicBinaryOperation().
Effects()
OpEffects v8::internal::compiler::turboshaft::AtomicRMWOp::Effects () const [inline]
Definition at line 3105 of file operations.h.
                            {
    OpEffects effects =
        OpEffects().CanWriteMemory().CanDependOnChecks().CanReadMemory();
    if (memory_access_kind == MemoryAccessKind::kProtectedByTrapHandler) {
      effects = effects.CanLeaveCurrentFunction();
    }
    return effects;
  }
References v8::internal::compiler::turboshaft::OpEffects::CanDependOnChecks(), v8::internal::compiler::turboshaft::OpEffects::CanLeaveCurrentFunction(), v8::internal::compiler::turboshaft::OpEffects::CanReadMemory(), v8::internal::compiler::turboshaft::OpEffects::CanWriteMemory(), and v8::internal::compiler::kProtectedByTrapHandler.
expected()
OptionalOpIndex v8::internal::compiler::turboshaft::AtomicRMWOp::expected () const [inline]
Definition at line 3133 of file operations.h.
                                   {
    return (input_count == 4) ? input(3) : OpIndex::Invalid();
  }
References v8::internal::compiler::turboshaft::detail::input_count(), and v8::internal::compiler::turboshaft::OpIndex::Invalid().
Referenced by PrintInputs(), v8::internal::compiler::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicCompareExchange(), and v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitAtomicCompareExchange().
Explode()
template<typename Fn , typename Mapper >
auto v8::internal::compiler::turboshaft::AtomicRMWOp::Explode (Fn fn, Mapper & mapper) const [inline]
Definition at line 3163 of file operations.h.
                                                      {
    return fn(mapper.Map(base()), mapper.Map(index()), mapper.Map(value()),
              mapper.Map(expected()), bin_op, in_out_rep, memory_rep,
              memory_access_kind, base_rep);
  }
References v8::internal::index, and v8::internal::value.
index()
V<WordPtr> v8::internal::compiler::turboshaft::AtomicRMWOp::index () const [inline]
Definition at line 3131 of file operations.h.
{ return input<WordPtr>(1); }
Referenced by PrintInputs(), v8::internal::compiler::VisitAtomicBinaryOperation(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicBinop(), v8::internal::compiler::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitAtomicBinOp(), v8::internal::compiler::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitAtomicCompareExchange(), v8::internal::compiler::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitAtomicExchange(), and v8::internal::compiler::InstructionSelector::VisitWord32AtomicBinaryOperation().
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::AtomicRMWOp::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 3118 of file operations.h.
                                                              {
    if (bin_op == BinOp::kCompareExchange) {
      return InitVectorOf(storage, {base_rep, RegisterRepresentation::WordPtr(),
                                    in_out_rep, in_out_rep});
    }
    return InitVectorOf(
        storage, {base_rep, RegisterRepresentation::WordPtr(), in_out_rep});
  }
References v8::internal::compiler::turboshaft::InitVectorOf(), and v8::internal::compiler::turboshaft::RegisterRepresentation::WordPtr().
New()
static AtomicRMWOp& v8::internal::compiler::turboshaft::AtomicRMWOp::New (Graph * graph, OpIndex base, V< WordPtr > index, OpIndex value, OptionalOpIndex expected, BinOp bin_op, RegisterRepresentation result_rep, MemoryRepresentation input_rep, MemoryAccessKind kind, RegisterRepresentation base_rep) [inline], [static]
Definition at line 3169 of file operations.h.
                                                           {
    return Base::New(graph, 3 + expected.valid(), base, index, value, expected,
                     bin_op, result_rep, input_rep, kind, base_rep);
  }
References graph(), v8::internal::index, v8::internal::anonymous_namespace{intl-objects.cc}::New(), v8::internal::compiler::turboshaft::OptionalOpIndex::valid(), and v8::internal::value.
options()
auto v8::internal::compiler::turboshaft::AtomicRMWOp::options () const [inline]
Definition at line 3182 of file operations.h.
                       {
    return std::tuple{bin_op, in_out_rep, memory_rep, memory_access_kind,
                      base_rep};
  }
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::AtomicRMWOp::outputs_rep () const [inline]
Definition at line 3114 of file operations.h.
                                                               {
    return base::VectorOf(&in_out_rep, 1);
  }
References v8::base::VectorOf().
PrintInputs()
void v8::internal::compiler::turboshaft::AtomicRMWOp::PrintInputs (std::ostream & os, const std::string & op_index_prefix) const
Definition at line 642 of file operations.cc.
                                                                      {
  os << " *(" << op_index_prefix << base().id() << " + " << op_index_prefix
     << index().id() << ").atomic_" << bin_op << '(';
  if (bin_op == BinOp::kCompareExchange) {
    os << "expected: " << op_index_prefix << expected();
    os << ", new: " << op_index_prefix << value();
  } else {
    os << op_index_prefix << value().id();
  }
  os << ')';
}
References base(), bin_op, expected(), v8::internal::compiler::turboshaft::OpIndex::id(), index(), kCompareExchange, and value().
PrintOptions()
void v8::internal::compiler::turboshaft::AtomicRMWOp::PrintOptions (std::ostream & os) const
Definition at line 655 of file operations.cc.
                                                   {
  os << '[' << "binop: " << bin_op << ", in_out_rep: " << in_out_rep
     << ", memory_rep: " << memory_rep << ", base_rep: " << base_rep << ']';
}
References base_rep, bin_op, in_out_rep, and memory_rep.
Validate()
void v8::internal::compiler::turboshaft::AtomicRMWOp::Validate (const Graph & graph) const [inline]
Definition at line 3137 of file operations.h.
                                          {
    DCHECK_EQ(bin_op == BinOp::kCompareExchange, expected().valid());
    DCHECK(base_rep == RegisterRepresentation::WordPtr() ||
           base_rep == RegisterRepresentation::Tagged());
  }
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::turboshaft::RegisterRepresentation::Tagged(), and v8::internal::compiler::turboshaft::RegisterRepresentation::WordPtr().
value()
OpIndex v8::internal::compiler::turboshaft::AtomicRMWOp::value () const [inline]
Definition at line 3132 of file operations.h.
{ return input(2); }
Referenced by PrintInputs(), v8::internal::compiler::VisitAtomicBinaryOperation(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicBinop(), v8::internal::compiler::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitAtomicBinOp(), v8::internal::compiler::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitAtomicCompareExchange(), v8::internal::compiler::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitAtomicExchange(), and v8::internal::compiler::InstructionSelector::VisitWord32AtomicBinaryOperation().
Member Data Documentation
base_rep
RegisterRepresentation v8::internal::compiler::turboshaft::AtomicRMWOp::base_rep
Definition at line 3103 of file operations.h.
Referenced by PrintOptions().
bin_op
BinOp v8::internal::compiler::turboshaft::AtomicRMWOp::bin_op
Definition at line 3099 of file operations.h.
Referenced by PrintInputs(), PrintOptions(), and v8::internal::compiler::InstructionSelector::VisitNode().
in_out_rep
RegisterRepresentation v8::internal::compiler::turboshaft::AtomicRMWOp::in_out_rep
Definition at line 3100 of file operations.h.
Referenced by PrintOptions(), and v8::internal::compiler::InstructionSelector::VisitNode().
memory_access_kind
MemoryAccessKind v8::internal::compiler::turboshaft::AtomicRMWOp::memory_access_kind
Definition at line 3102 of file operations.h.
Referenced by v8::internal::compiler::InstructionSelector::VisitWord64AtomicBinaryOperation().
memory_rep
MemoryRepresentation v8::internal::compiler::turboshaft::AtomicRMWOp::memory_rep
Definition at line 3101 of file operations.h.
Referenced by v8::internal::compiler::AtomicOpType(), PrintOptions(), v8::internal::compiler::VisitAtomicBinaryOperation(), v8::internal::compiler::InstructionSelector::VisitNode(), v8::internal::compiler::InstructionSelector::VisitWord32AtomicBinaryOperation(), and v8::internal::compiler::InstructionSelector::VisitWord64AtomicBinaryOperation().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h
/mnt/V8SourceCode/src/compiler/turboshaft/operations.cc