v8::internal::compiler::turboshaft::FinalizeCodePhase Struct Reference
#include <register-allocation-phase.h>
Public Member Functions
DECL_TURBOSHAFT_MAIN_THREAD_PIPELINE_PHASE_CONSTANTS_WITH_LEGACY_NAME (FinalizeCode) static const expr bool kOutputIsTraceableGraph
void Run (PipelineData *data, Zone *temp_zone)
Detailed Description
Definition at line 205 of file register-allocation-phase.h.
Member Function Documentation
DECL_TURBOSHAFT_MAIN_THREAD_PIPELINE_PHASE_CONSTANTS_WITH_LEGACY_NAME()
v8::internal::compiler::turboshaft::FinalizeCodePhase::DECL_TURBOSHAFT_MAIN_THREAD_PIPELINE_PHASE_CONSTANTS_WITH_LEGACY_NAME (FinalizeCode) const
Run()
void v8::internal::compiler::turboshaft::FinalizeCodePhase::Run (PipelineData * data, Zone * temp_zone) [inline]
Definition at line 210 of file register-allocation-phase.h.
                                                {
    CodeGenerator* code_generator = data->code_generator();
    DCHECK_NOT_NULL(code_generator);
    data->set_code(code_generator->FinalizeCode());
  }
References v8::internal::compiler::turboshaft::PipelineData::code_generator(), DCHECK_NOT_NULL, v8::internal::compiler::CodeGenerator::FinalizeCode(), and v8::internal::compiler::turboshaft::PipelineData::set_code().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/register-allocation-phase.h