v8::internal::compiler::turboshaft::TSCallDescriptor Struct Reference
#include <operations.h>
Public Member Functions
TSCallDescriptor (const CallDescriptor *descriptor, base::Vector< const RegisterRepresentation > in_reps, base::Vector< const RegisterRepresentation > out_reps, CanThrow can_throw, LazyDeoptOnThrow lazy_deopt_on_throw, const JSWasmCallParameters *js_wasm_call_parameters)
Static Public Member Functions
static const TSCallDescriptor * Create (const CallDescriptor *descriptor, CanThrow can_throw, LazyDeoptOnThrow lazy_deopt_on_throw, Zone *graph_zone, const JSWasmCallParameters *js_wasm_call_parameters=nullptr)
Public Attributes
const CallDescriptor * descriptor
base::Vector< const RegisterRepresentation > in_reps
base::Vector< const RegisterRepresentation > out_reps
CanThrow can_throw
LazyDeoptOnThrow lazy_deopt_on_throw
const JSWasmCallParameters * js_wasm_call_parameters
Detailed Description
Definition at line 3998 of file operations.h.
Constructor & Destructor Documentation
TSCallDescriptor()
v8::internal::compiler::turboshaft::TSCallDescriptor::TSCallDescriptor (const CallDescriptor * descriptor, base::Vector< const RegisterRepresentation > in_reps, base::Vector< const RegisterRepresentation > out_reps, CanThrow can_throw, LazyDeoptOnThrow lazy_deopt_on_throw, const JSWasmCallParameters * js_wasm_call_parameters) [inline]
Definition at line 4013 of file operations.h.
      : descriptor(descriptor),
        in_reps(in_reps),
        out_reps(out_reps),
        can_throw(can_throw),
        lazy_deopt_on_throw(lazy_deopt_on_throw),
        js_wasm_call_parameters(js_wasm_call_parameters) {}
Member Function Documentation
Create()
static const TSCallDescriptor* v8::internal::compiler::turboshaft::TSCallDescriptor::Create (const CallDescriptor * descriptor, CanThrow can_throw, LazyDeoptOnThrow lazy_deopt_on_throw, Zone * graph_zone, const JSWasmCallParameters * js_wasm_call_parameters = nullptr) [inline], [static]
Definition at line 4025 of file operations.h.
                                                                     {
    DCHECK_IMPLIES(can_throw == CanThrow::kNo,
                   lazy_deopt_on_throw == LazyDeoptOnThrow::kNo);
    base::Vector<RegisterRepresentation> in_reps =
        graph_zone->AllocateVector<RegisterRepresentation>(
            descriptor->ParameterCount());
    for (size_t i = 0; i < descriptor->ParameterCount(); ++i) {
      in_reps[i] = RegisterRepresentation::FromMachineRepresentation(
          descriptor->GetParameterType(i).representation());
    }
    base::Vector<RegisterRepresentation> out_reps =
        graph_zone->AllocateVector<RegisterRepresentation>(
            descriptor->ReturnCount());
    for (size_t i = 0; i < descriptor->ReturnCount(); ++i) {
      out_reps[i] = RegisterRepresentation::FromMachineRepresentation(
          descriptor->GetReturnType(i).representation());
    }
    return graph_zone->New<TSCallDescriptor>(descriptor, in_reps, out_reps,
                                             can_throw, lazy_deopt_on_throw,
                                             js_wasm_call_parameters);
  }
References v8::internal::Zone::AllocateVector(), DCHECK_IMPLIES, v8::internal::compiler::turboshaft::RegisterRepresentation::FromMachineRepresentation(), v8::internal::compiler::CallDescriptor::GetParameterType(), v8::internal::compiler::CallDescriptor::GetReturnType(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::kNo, v8::internal::Zone::New(), v8::internal::compiler::CallDescriptor::ParameterCount(), v8::internal::MachineType::representation(), and v8::internal::compiler::CallDescriptor::ReturnCount().
Referenced by v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::BuildAllocateJSExternalObject(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCallWasmFromWrapper(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCapiCallWrapper(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildChangeBigIntToInt64(), v8::internal::wasm::WasmGraphBuilderBase::BuildChangeInt64ToBigInt(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildWasmCall(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildWasmMaybeReturnCall(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildWasmToJSWrapper(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin(), v8::internal::wasm::WasmWrapperTSGraphBuilder::CallBuiltin(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::CallBuiltinForBigIntOp(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltinWithVarStackArgs(), v8::internal::wasm::WasmGraphBuilderBase::CallC(), v8::internal::wasm::WasmGraphBuilderBase::CallRuntime(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::CheckEqualsInternalizedString(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::ConvertJSPrimitiveToUntaggedOrDeopt(), v8::internal::compiler::turboshaft::BuiltinCallDescriptor::Descriptor< Derived >::Create(), v8::internal::compiler::turboshaft::RuntimeCallDescriptor::Descriptor< Derived >::Create(), v8::internal::compiler::turboshaft::CreateAllocateBuiltinDescriptor(), v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::FastApiCall(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::GenerateBuiltinCall(), v8::internal::wasm::anonymous_namespace{wrappers.cc}::GetBuiltinCallDescriptor(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerCall(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::turboshaft::GrowableStacksReducer< Next >::Return(), v8::internal::interpreter::BytecodeHandlerReducer< Next >::TailCallBytecodeDispatch(), v8::internal::compiler::turboshaft::WasmJSLoweringReducer< Next >::TrapIf(), v8::internal::compiler::turboshaft::GrowableStacksReducer< Next >::WasmStackCheck(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::WellKnown_FastApi().
Member Data Documentation
can_throw
CanThrow v8::internal::compiler::turboshaft::TSCallDescriptor::can_throw
Definition at line 4002 of file operations.h.
Referenced by v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerCall().
descriptor
const CallDescriptor* v8::internal::compiler::turboshaft::TSCallDescriptor::descriptor
Definition at line 3999 of file operations.h.
Referenced by v8::internal::compiler::turboshaft::AnalyzeCall(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::CheckPairOrPairOp(), v8::internal::compiler::turboshaft::CallOp::HasFrameState(), v8::internal::compiler::turboshaft::CallOp::inputs_rep(), v8::internal::compiler::turboshaft::TailCallOp::inputs_rep(), v8::internal::compiler::IsBuiltinCall(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerCall(), v8::internal::compiler::turboshaft::fast_hash< TSCallDescriptor >::operator()(), v8::internal::compiler::turboshaft::CallOp::PrintOptions(), v8::internal::compiler::turboshaft::TailCallOp::PrintOptions(), v8::internal::compiler::InstructionSelector::VisitCall(), and v8::internal::compiler::InstructionSelector::VisitTailCall().
in_reps
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::TSCallDescriptor::in_reps
Definition at line 4000 of file operations.h.
Referenced by v8::internal::compiler::turboshaft::CallOp::inputs_rep(), and v8::internal::compiler::turboshaft::TailCallOp::inputs_rep().
js_wasm_call_parameters
const JSWasmCallParameters* v8::internal::compiler::turboshaft::TSCallDescriptor::js_wasm_call_parameters
Definition at line 4011 of file operations.h.
lazy_deopt_on_throw
LazyDeoptOnThrow v8::internal::compiler::turboshaft::TSCallDescriptor::lazy_deopt_on_throw
Definition at line 4003 of file operations.h.
Referenced by v8::internal::compiler::InstructionSelector::VisitCall().
out_reps
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::TSCallDescriptor::out_reps
Definition at line 4001 of file operations.h.
Referenced by v8::internal::compiler::turboshaft::CallOp::results_rep().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h