v8::internal::compiler::turboshaft::WordBinopDeoptOnOverflowOp Struct Reference
#include <operations.h>
Public Types
enum class Kind : uint8_t {
kSignedAdd
, kSignedMul
, kSignedSub
, kSignedDiv
,
kSignedMod
, kUnsignedDiv
, kUnsignedMod
 }
Public Member Functions
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
V< Word > left () const
V< Word > right () const
V< FrameState > frame_state () const
WordBinopDeoptOnOverflowOp (V< Word > left, V< Word > right, V< FrameState > frame_state, Kind kind, WordRepresentation rep, FeedbackSource feedback, CheckForMinusZeroMode mode)
void Validate (const Graph &graph) const
auto options () const
void PrintOptions (std::ostream &os) const
Public Attributes
Kind kind
WordRepresentation rep
FeedbackSource feedback
CheckForMinusZeroMode mode
Static Public Attributes
static constexpr OpEffects effects = OpEffects().CanDeopt()
Additional Inherited Members
Detailed Description
Definition at line 1776 of file operations.h.
Member Enumeration Documentation
Kind
enum v8::internal::compiler::turboshaft::WordBinopDeoptOnOverflowOp::Kind : uint8_t [strong]
Enumerator
kSignedAdd
kSignedMul
kSignedSub
kSignedDiv
kSignedMod
kUnsignedDiv
kUnsignedMod
Definition at line 1778 of file operations.h.
                  : uint8_t {
    kSignedAdd,
    kSignedMul,
    kSignedSub,
    kSignedDiv,
    kSignedMod,
    kUnsignedDiv,
    kUnsignedMod
  };
Constructor & Destructor Documentation
WordBinopDeoptOnOverflowOp()
v8::internal::compiler::turboshaft::WordBinopDeoptOnOverflowOp::WordBinopDeoptOnOverflowOp (V< Word > left, V< Word > right, V< FrameState > frame_state, Kind kind, WordRepresentation rep, FeedbackSource feedback, CheckForMinusZeroMode mode) [inline]
Definition at line 1806 of file operations.h.
      : Base(left, right, frame_state),
        kind(kind),
        rep(rep),
        feedback(feedback),
        mode(mode) {}
Member Function Documentation
frame_state()
V<FrameState> v8::internal::compiler::turboshaft::WordBinopDeoptOnOverflowOp::frame_state () const [inline]
Definition at line 1804 of file operations.h.
{ return input<FrameState>(2); }
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::WordBinopDeoptOnOverflowOp::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 1797 of file operations.h.
                                                              {
    return InputsRepFactory::PairOf(rep);
  }
References v8::internal::compiler::turboshaft::InputsRepFactory::PairOf().
left()
V<Word> v8::internal::compiler::turboshaft::WordBinopDeoptOnOverflowOp::left () const [inline]
Definition at line 1802 of file operations.h.
{ return input<Word>(0); }
options()
auto v8::internal::compiler::turboshaft::WordBinopDeoptOnOverflowOp::options () const [inline]
Definition at line 1820 of file operations.h.
{ return std::tuple{kind, rep, feedback, mode}; }
References mode().
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::WordBinopDeoptOnOverflowOp::outputs_rep () const [inline]
Definition at line 1793 of file operations.h.
                                                               {
    return base::VectorOf(static_cast<const RegisterRepresentation*>(&rep), 1);
  }
References v8::base::VectorOf().
PrintOptions()
void v8::internal::compiler::turboshaft::WordBinopDeoptOnOverflowOp::PrintOptions (std::ostream & os) const
Definition at line 1037 of file operations.cc.
                                                                  {
  os << '[';
  switch (kind) {
    case Kind::kSignedAdd:
      os << "signed add, ";
      break;
    case Kind::kSignedMul:
      os << "signed mul, ";
      break;
    case Kind::kSignedSub:
      os << "signed sub, ";
      break;
    case Kind::kSignedDiv:
      os << "signed div, ";
      break;
    case Kind::kSignedMod:
      os << "signed mod, ";
      break;
    case Kind::kUnsignedDiv:
      os << "unsigned div, ";
      break;
    case Kind::kUnsignedMod:
      os << "unsigned mod, ";
      break;
  }
  os << rep << ", " << mode;
  os << ']';
}
References kind, kSignedAdd, kSignedDiv, kSignedMod, kSignedMul, kSignedSub, kUnsignedDiv, kUnsignedMod, mode, and rep.
right()
V<Word> v8::internal::compiler::turboshaft::WordBinopDeoptOnOverflowOp::right () const [inline]
Definition at line 1803 of file operations.h.
{ return input<Word>(1); }
Validate()
void v8::internal::compiler::turboshaft::WordBinopDeoptOnOverflowOp::Validate (const Graph & graph) const [inline]
Definition at line 1816 of file operations.h.
                                          {
    DCHECK_IMPLIES(kind == Kind::kUnsignedDiv || kind == Kind::kUnsignedMod,
                   rep == WordRepresentation::Word32());
  }
References DCHECK_IMPLIES, and v8::internal::compiler::turboshaft::WordRepresentation::Word32().
Member Data Documentation
effects
constexpr OpEffects v8::internal::compiler::turboshaft::WordBinopDeoptOnOverflowOp::effects = OpEffects().CanDeopt() [static], [constexpr]
Definition at line 1792 of file operations.h.
feedback
FeedbackSource v8::internal::compiler::turboshaft::WordBinopDeoptOnOverflowOp::feedback
Definition at line 1789 of file operations.h.
kind
Kind v8::internal::compiler::turboshaft::WordBinopDeoptOnOverflowOp::kind
Definition at line 1787 of file operations.h.
Referenced by PrintOptions().
mode
CheckForMinusZeroMode v8::internal::compiler::turboshaft::WordBinopDeoptOnOverflowOp::mode
Definition at line 1790 of file operations.h.
Referenced by PrintOptions().
rep
WordRepresentation v8::internal::compiler::turboshaft::WordBinopDeoptOnOverflowOp::rep
Definition at line 1788 of file operations.h.
Referenced by PrintOptions().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h
/mnt/V8SourceCode/src/compiler/turboshaft/operations.cc