v8::internal::wasm::TypeCanonicalizer::CanonicalHashing Struct Reference
Public Member Functions
CanonicalHashing (RecursionGroupRange recgroup)
uint32_t MakeGroupRelative (CanonicalTypeIndex index)
void Add (CanonicalType type)
void Add (CanonicalValueType value_type)
void Add (const CanonicalSig &sig)
void Add (const CanonicalStructType &struct_type)
void Add (const CanonicalArrayType &array_type)
void Add (const CanonicalContType &cont_type)
size_t hash () const
Public Attributes
base::Hasher hasher
const RecursionGroupRange recgroup
Detailed Description
Definition at line 207 of file canonical-types.h.
Constructor & Destructor Documentation
CanonicalHashing()
v8::internal::wasm::TypeCanonicalizer::CanonicalHashing::CanonicalHashing (RecursionGroupRange recgroup) [inline], [explicit]
Definition at line 211 of file canonical-types.h.
        : recgroup{recgroup} {}
Member Function Documentation
Add() [1/6]
void v8::internal::wasm::TypeCanonicalizer::CanonicalHashing::Add (CanonicalType type) [inline]
Definition at line 220 of file canonical-types.h.
                                 {
      // Add several pieces of information in a single number, for faster
      // hashing.
      uint32_t supertype_index = MakeGroupRelative(type.supertype);
      static_assert(kMaxCanonicalTypes <= kMaxUInt32 >> 3);
      uint32_t metadata =
          (supertype_index << 2) | (type.is_shared << 1) | (type.is_final << 0);
      hasher.Add(metadata);
      switch (type.kind) {
        case CanonicalType::kFunction:
          Add(*type.function_sig);
          break;
        case CanonicalType::kStruct: {
          uint32_t descriptor_index = MakeGroupRelative(type.descriptor);
          uint32_t describes_index = MakeGroupRelative(type.describes);
          // {MakeGroupRelative} returns a value at most 1 bit bigger than
          // the max canonical index, which currently fits into 20 bits. So
          // by shifting left by 11, we're not truncating anything. (And even
          // if we did, it's just a hash, collisions are OK.)
          uint32_t desc = (descriptor_index << 11) ^ (describes_index);
          hasher.Add(desc);
          Add(*type.struct_type);
          break;
        }
        case CanonicalType::kArray:
          Add(*type.array_type);
          break;
        case CanonicalType::kCont:
          Add(*type.cont_type);
          break;
      }
    }
References v8::base::Hasher::Add(), hasher, v8::internal::wasm::TypeCanonicalizer::CanonicalType::kArray, v8::internal::wasm::TypeCanonicalizer::CanonicalType::kCont, v8::internal::wasm::TypeCanonicalizer::CanonicalType::kFunction, v8::internal::wasm::TypeCanonicalizer::CanonicalType::kStruct, MakeGroupRelative(), and v8::internal::tracing::type.
Referenced by Add().
Add() [2/6]
void v8::internal::wasm::TypeCanonicalizer::CanonicalHashing::Add (CanonicalValueType value_type) [inline]
Definition at line 253 of file canonical-types.h.
                                            {
      if (value_type.has_index() && recgroup.Contains(value_type.ref_index())) {
        // For relative indexed types, add their nullability, exactness, and
        // the relative index to the hash.
        // Shift the relative index by {kMaxCanonicalTypes} to map it to a
        // different index space (note that collisions in hashing are OK
        // though).
        static_assert(kMaxCanonicalTypes <= kMaxUInt32 / 2);
        // TODO(403372470): Add the 'exact' bit.
        hasher.Add((value_type.is_exact() << 1) | value_type.is_nullable());
        hasher.Add((value_type.ref_index().index - recgroup.first.index) +
                   kMaxCanonicalTypes);
      } else {
        hasher.Add(value_type);
      }
    }
References v8::base::Hasher::Add(), v8::internal::wasm::TypeCanonicalizer::RecursionGroupRange::Contains(), v8::internal::wasm::TypeCanonicalizer::RecursionGroupRange::first, v8::internal::wasm::ValueTypeBase::has_index(), hasher, v8::internal::wasm::TypeIndex::index, v8::internal::wasm::ValueTypeBase::is_exact(), v8::internal::wasm::ValueTypeBase::is_nullable(), v8::internal::wasm::kMaxCanonicalTypes, v8::internal::kMaxUInt32, recgroup, v8::internal::wasm::ValueType::ref_index(), and v8::internal::wasm::value_type().
Add() [3/6]
void v8::internal::wasm::TypeCanonicalizer::CanonicalHashing::Add (const CanonicalArrayType & array_type) [inline]
Definition at line 282 of file canonical-types.h.
                                                   {
      hasher.Add(array_type.mutability());
      Add(array_type.element_type());
    }
References Add(), v8::base::Hasher::Add(), v8::internal::wasm::CanonicalArrayType::element_type(), hasher, and v8::internal::wasm::ArrayTypeBase::mutability().
Add() [4/6]
void v8::internal::wasm::TypeCanonicalizer::CanonicalHashing::Add (const CanonicalContType & cont_type) [inline]
Definition at line 287 of file canonical-types.h.
                                                 {
      CanonicalTypeIndex cont_index = cont_type.contfun_typeindex();
      if (recgroup.Contains(cont_index)) {
        hasher.Add(cont_index.index - recgroup.first.index +
                   kMaxCanonicalTypes);
      } else {
        hasher.Add(cont_index.index); // Not relative to this rec group
      }
    }
References v8::base::Hasher::Add(), v8::internal::wasm::TypeCanonicalizer::RecursionGroupRange::Contains(), v8::internal::wasm::CanonicalContType::contfun_typeindex(), v8::internal::wasm::TypeCanonicalizer::RecursionGroupRange::first, hasher, v8::internal::wasm::TypeIndex::index, v8::internal::wasm::kMaxCanonicalTypes, and recgroup.
Add() [5/6]
void v8::internal::wasm::TypeCanonicalizer::CanonicalHashing::Add (const CanonicalSig & sig) [inline]
Definition at line 270 of file canonical-types.h.
                                      {
      hasher.Add(sig.parameter_count());
      for (CanonicalValueType type : sig.all()) Add(type);
    }
References Add(), v8::base::Hasher::Add(), hasher, v8::internal::sig, and v8::internal::tracing::type.
Add() [6/6]
void v8::internal::wasm::TypeCanonicalizer::CanonicalHashing::Add (const CanonicalStructType & struct_type) [inline]
Definition at line 275 of file canonical-types.h.
                                                     {
      hasher.AddRange(struct_type.mutabilities());
      for (const ValueTypeBase& field : struct_type.fields()) {
        Add(CanonicalValueType{field});
      }
    }
References Add(), v8::base::Hasher::AddRange(), v8::internal::wasm::CanonicalStructType::fields(), hasher, and v8::internal::wasm::StructTypeBase::mutabilities().
hash()
size_t v8::internal::wasm::TypeCanonicalizer::CanonicalHashing::hash () const [inline]
Definition at line 298 of file canonical-types.h.
{ return hasher.hash(); }
References v8::base::Hasher::hash(), and hasher.
MakeGroupRelative()
uint32_t v8::internal::wasm::TypeCanonicalizer::CanonicalHashing::MakeGroupRelative (CanonicalTypeIndex index) [inline]
Definition at line 214 of file canonical-types.h.
                                                         {
      uint32_t is_relative = recgroup.Contains(index) ? 1 : 0;
      uint32_t relative = index.index - is_relative * recgroup.first.index;
      return (relative << 1) | is_relative;
    }
References v8::internal::wasm::TypeCanonicalizer::RecursionGroupRange::Contains(), v8::internal::wasm::TypeCanonicalizer::RecursionGroupRange::first, v8::internal::index, v8::internal::wasm::TypeIndex::index, and recgroup.
Referenced by Add().
Member Data Documentation
hasher
base::Hasher v8::internal::wasm::TypeCanonicalizer::CanonicalHashing::hasher
Definition at line 208 of file canonical-types.h.
Referenced by Add(), and hash().
recgroup
const RecursionGroupRange v8::internal::wasm::TypeCanonicalizer::CanonicalHashing::recgroup
Definition at line 209 of file canonical-types.h.
Referenced by Add(), and MakeGroupRelative().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/wasm/canonical-types.h