v8::internal::compiler::turboshaft::InstructionSelectionPhase Struct Reference
#include <instruction-selection-phase.h>
Public Member Functions
std::optional< BailoutReason > Run (PipelineData *data, Zone *temp_zone, const CallDescriptor *call_descriptor, Linkage *linkage, CodeTracer *code_tracer)
Static Public Attributes
static constexpr bool kOutputIsTraceableGraph = false
Detailed Description
Definition at line 128 of file instruction-selection-phase.h.
Member Function Documentation
Run()
std::optional< BailoutReason > v8::internal::compiler::turboshaft::InstructionSelectionPhase::Run (PipelineData * data, Zone * temp_zone, const CallDescriptor * call_descriptor, Linkage * linkage, CodeTracer * code_tracer)
Definition at line 329 of file instruction-selection-phase.cc.
                                               {
  Graph& graph = data->graph();
  // Initialize an instruction sequence.
  data->InitializeInstructionComponent(call_descriptor);
  // Run the actual instruction selection.
  InstructionSelector selector = InstructionSelector::ForTurboshaft(
      temp_zone, graph.op_id_count(), linkage, data->sequence(), &graph,
      data->frame(),
      data->info()->switch_jump_table()
          ? InstructionSelector::kEnableSwitchJumpTable
          : InstructionSelector::kDisableSwitchJumpTable,
      &data->info()->tick_counter(), data->broker(),
      &data->max_unoptimized_frame_height(), &data->max_pushed_argument_count(),
      data->info()->source_positions()
          ? InstructionSelector::kAllSourcePositions
          : InstructionSelector::kCallSourcePositions,
      InstructionSelector::SupportedFeatures(),
      v8_flags.turbo_instruction_scheduling
          ? InstructionSelector::kEnableScheduling
          : InstructionSelector::kDisableScheduling,
      data->assembler_options().enable_root_relative_access
          ? InstructionSelector::kEnableRootsRelativeAddressing
          : InstructionSelector::kDisableRootsRelativeAddressing,
      data->info()->trace_turbo_json()
          ? InstructionSelector::kEnableTraceTurboJson
          : InstructionSelector::kDisableTraceTurboJson,
      // For now only ensure a deterministic NaN pattern for Wasm code. The spec
      // does not mandate it, but we want it for differential fuzzing.
      // TODO(353475584): This will have to be refined for Wasm-in-JS inlining.
      data->is_wasm() ? InstructionSelector::kEnsureDeterministicNan
                      : InstructionSelector::kNoDeterministicNan);
  if (std::optional<BailoutReason> bailout = selector.SelectInstructions()) {
    return bailout;
  }
  TraceSequence(data->info(), data->sequence(), data->broker(), code_tracer,
                "after instruction selection");
  return std::nullopt;
}
References v8::internal::compiler::turboshaft::PipelineData::assembler_options(), v8::internal::compiler::turboshaft::PipelineData::broker(), v8::internal::AssemblerOptions::enable_root_relative_access, v8::internal::compiler::InstructionSelector::ForTurboshaft(), v8::internal::compiler::turboshaft::PipelineData::frame(), v8::internal::compiler::turboshaft::PipelineData::graph(), graph(), v8::internal::compiler::turboshaft::PipelineData::info(), v8::internal::compiler::turboshaft::PipelineData::InitializeInstructionComponent(), v8::internal::compiler::turboshaft::PipelineData::is_wasm(), v8::internal::compiler::InstructionSelector::kAllSourcePositions, v8::internal::compiler::InstructionSelector::kCallSourcePositions, v8::internal::compiler::InstructionSelector::kDisableRootsRelativeAddressing, v8::internal::compiler::InstructionSelector::kDisableScheduling, v8::internal::compiler::InstructionSelector::kDisableSwitchJumpTable, v8::internal::compiler::InstructionSelector::kDisableTraceTurboJson, v8::internal::compiler::InstructionSelector::kEnableRootsRelativeAddressing, v8::internal::compiler::InstructionSelector::kEnableScheduling, v8::internal::compiler::InstructionSelector::kEnableSwitchJumpTable, v8::internal::compiler::InstructionSelector::kEnableTraceTurboJson, v8::internal::compiler::InstructionSelector::kEnsureDeterministicNan, v8::internal::compiler::InstructionSelector::kNoDeterministicNan, v8::internal::compiler::turboshaft::PipelineData::max_pushed_argument_count(), v8::internal::compiler::turboshaft::PipelineData::max_unoptimized_frame_height(), v8::internal::compiler::InstructionSelector::SelectInstructions(), v8::internal::compiler::turboshaft::PipelineData::sequence(), v8::internal::compiler::InstructionSelector::SupportedFeatures(), v8::internal::OptimizedCompilationInfo::tick_counter(), v8::internal::compiler::turboshaft::anonymous_namespace{instruction-selection-phase.cc}::TraceSequence(), and v8::internal::v8_flags.
Member Data Documentation
kOutputIsTraceableGraph
constexpr bool v8::internal::compiler::turboshaft::InstructionSelectionPhase::kOutputIsTraceableGraph = false [static], [constexpr]
Definition at line 130 of file instruction-selection-phase.h.
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/instruction-selection-phase.h
/mnt/V8SourceCode/src/compiler/turboshaft/instruction-selection-phase.cc