v8::internal::wasm::ModuleWireBytes Struct Reference
#include <wasm-module.h>
Public Member Functions
ModuleWireBytes (base::Vector< const uint8_t > module_bytes)
constexpr ModuleWireBytes (const uint8_t *start, const uint8_t *end)
bool operator== (const ModuleWireBytes &other) const =default
WasmName GetNameOrNull (WireBytesRef ref) const
WasmName GetNameOrNull (int func_index, const WasmModule *module) const
bool BoundsCheck (WireBytesRef ref) const
base::Vector< const uint8_t > GetFunctionBytes (const WasmFunction *function) const
base::Vector< const uint8_t > module_bytes () const
const uint8_t * start () const
const uint8_t * end () const
size_t length () const
Private Attributes
base::Vector< const uint8_t > module_bytes_
Detailed Description
Definition at line 993 of file wasm-module.h.
Constructor & Destructor Documentation
ModuleWireBytes() [1/2]
v8::internal::wasm::ModuleWireBytes::ModuleWireBytes (base::Vector< const uint8_t > module_bytes) [inline], [explicit]
Definition at line 994 of file wasm-module.h.
      : module_bytes_(module_bytes) {}
ModuleWireBytes() [2/2]
constexpr v8::internal::wasm::ModuleWireBytes::ModuleWireBytes (const uint8_t * start, const uint8_t * end) [inline], [constexpr]
Definition at line 996 of file wasm-module.h.
      : module_bytes_(start, static_cast<int>(end - start)) {
    DCHECK_GE(kMaxInt, end - start);
  }
References DCHECK_GE, v8::internal::compiler::end(), and v8::internal::kMaxInt.
Member Function Documentation
BoundsCheck()
bool v8::internal::wasm::ModuleWireBytes::BoundsCheck (WireBytesRef ref) const [inline]
Definition at line 1010 of file wasm-module.h.
                                           {
    size_t size = module_bytes_.size();
    return ref.offset() <= size && ref.length() <= size - ref.offset();
  }
References v8::internal::wasm::WireBytesRef::length(), v8::internal::wasm::WireBytesRef::offset(), and size().
Referenced by GetNameOrNull().
end()
const uint8_t* v8::internal::wasm::ModuleWireBytes::end () const [inline]
Definition at line 1023 of file wasm-module.h.
{ return module_bytes_.end(); }
GetFunctionBytes()
base::Vector<const uint8_t> v8::internal::wasm::ModuleWireBytes::GetFunctionBytes (const WasmFunction * function) const [inline]
Definition at line 1015 of file wasm-module.h.
                                          {
    return module_bytes_.SubVector(function->code.offset(),
                                   function->code.end_offset());
  }
References v8::base::Vector< T >::SubVector().
Referenced by v8::internal::wasm::DisassembleFunction(), and v8::internal::wasm::ModuleDisassembler::PrintModule().
GetNameOrNull() [1/2]
WasmName v8::internal::wasm::ModuleWireBytes::GetNameOrNull (int func_index, const WasmModule * module) const
Definition at line 225 of file wasm-module.cc.
                                                                        {
  return GetNameOrNull(
      module->lazily_generated_names.LookupFunctionName(*this, func_index));
}
References GetNameOrNull(), v8::internal::wasm::WasmModule::lazily_generated_names, and v8::internal::wasm::LazilyGeneratedNames::LookupFunctionName().
GetNameOrNull() [2/2]
WasmName v8::internal::wasm::ModuleWireBytes::GetNameOrNull (WireBytesRef ref) const
Definition at line 217 of file wasm-module.cc.
                                                              {
  if (!ref.is_set()) return {nullptr, 0}; // no name.
  DCHECK(BoundsCheck(ref));
  return WasmName::cast(
      module_bytes_.SubVector(ref.offset(), ref.end_offset()));
}
References BoundsCheck(), v8::internal::DCHECK(), v8::internal::wasm::WireBytesRef::end_offset(), v8::internal::wasm::WireBytesRef::is_set(), module_bytes_, v8::internal::wasm::WireBytesRef::offset(), and v8::base::Vector< T >::SubVector().
Referenced by v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::CreateWasmScript(), v8::internal::wasm::WasmCode::DebugName(), v8::internal::wasm::AsyncCompileJob::FinishCompile(), GetNameOrNull(), v8::internal::WasmModuleObject::GetRawFunctionName(), v8::internal::wasm::WasmCode::LogCode(), and v8::internal::RUNTIME_FUNCTION().
length()
size_t v8::internal::wasm::ModuleWireBytes::length () const [inline]
Definition at line 1024 of file wasm-module.h.
{ return module_bytes_.size(); }
Referenced by v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmModuleBytes(), v8::internal::wasm::AsyncStreamingProcessor::OnFinishedStream(), v8::internal::wasm::ModuleDisassembler::PrintModule(), and v8::internal::wasm::AsyncCompileJob::PrepareAndStartCompile::RunInForeground().
module_bytes()
base::Vector<const uint8_t> v8::internal::wasm::ModuleWireBytes::module_bytes () const [inline]
Definition at line 1021 of file wasm-module.h.
{ return module_bytes_; }
Referenced by v8::internal::wasm::AsyncCompileJob::Failed(), v8::internal::wasm::AsyncCompileJob::GetOrCreateNativeModule(), v8::internal::wasm::LazilyGeneratedNames::LookupFunctionName(), v8::internal::wasm::ModuleDisassembler::ModuleDisassembler(), v8::internal::wasm::AsyncStreamingProcessor::OnFinishedStream(), v8::internal::wasm::ModuleDisassembler::PrintModule(), and v8::internal::wasm::AsyncCompileJob::DecodeModule::RunInBackground().
operator==()
bool v8::internal::wasm::ModuleWireBytes::operator== (const ModuleWireBytes & other) const [default]
start()
const uint8_t* v8::internal::wasm::ModuleWireBytes::start () const [inline]
Definition at line 1022 of file wasm-module.h.
{ return module_bytes_.begin(); }
Referenced by v8::internal::wasm::WasmCompilationUnit::CompileWasmFunction(), v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmModuleBytes(), and v8::internal::wasm::ImmediatesPrinter< ValidationTag >::StringConst().
Member Data Documentation
module_bytes_
base::Vector<const uint8_t> v8::internal::wasm::ModuleWireBytes::module_bytes_ [private]
Definition at line 1027 of file wasm-module.h.
Referenced by GetNameOrNull().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-module.h
/mnt/V8SourceCode/src/wasm/wasm-module.cc