v8::internal::torque::SpecializationRequester Struct Reference
#include <declarable.h>
Public Member Functions
bool IsNone () const
SpecializationRequester (SourcePosition position, Scope *scope, std::string name)
Static Public Member Functions
static SpecializationRequester None ()
Public Attributes
SourcePosition position
Scope * scope
std::string name
Detailed Description
Definition at line 150 of file declarable.h.
Constructor & Destructor Documentation
SpecializationRequester()
v8::internal::torque::SpecializationRequester::SpecializationRequester (SourcePosition position, Scope * scope, std::string name)
Definition at line 81 of file declarable.cc.
    : position(position), name(std::move(name)) {
  // Skip scopes that are not related to template specializations, they might be
  // stack-allocated and not live for long enough.
  while (s && s->GetSpecializationRequester().IsNone()) s = s->ParentScope();
  this->scope = s;
}
References v8::internal::torque::Scope::GetSpecializationRequester(), IsNone(), v8::internal::torque::Declarable::ParentScope(), and scope.
Member Function Documentation
IsNone()
bool v8::internal::torque::SpecializationRequester::IsNone () const [inline]
Definition at line 164 of file declarable.h.
                      {
    return position == SourcePosition::Invalid() && scope == nullptr &&
           name == "";
  }
References v8::internal::torque::SourcePosition::Invalid(), name, position, and scope.
Referenced by v8::internal::torque::MessageBuilder::MessageBuilder(), and SpecializationRequester().
None()
static SpecializationRequester v8::internal::torque::SpecializationRequester::None () [inline], [static]
Definition at line 160 of file declarable.h.
                                        {
    return {SourcePosition::Invalid(), nullptr, ""};
  }
References v8::internal::torque::SourcePosition::Invalid().
Member Data Documentation
name
std::string v8::internal::torque::SpecializationRequester::name
Definition at line 158 of file declarable.h.
Referenced by IsNone(), and v8::internal::torque::MessageBuilder::MessageBuilder().
position
SourcePosition v8::internal::torque::SpecializationRequester::position
Definition at line 152 of file declarable.h.
Referenced by IsNone(), and v8::internal::torque::MessageBuilder::MessageBuilder().
scope
Scope* v8::internal::torque::SpecializationRequester::scope
Definition at line 156 of file declarable.h.
Referenced by IsNone(), v8::internal::torque::MessageBuilder::MessageBuilder(), and SpecializationRequester().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/torque/declarable.h
/mnt/V8SourceCode/src/torque/declarable.cc