v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOrDeoptOp Struct Reference
#include <operations.h>
Public Types
enum class JSPrimitiveKind : uint8_t { kSmi
 }
enum class InputInterpretation : uint8_t { kSigned
, kUnsigned
 }
Public Member Functions
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
V< Untagged > input () const
V< FrameState > frame_state () const
ConvertUntaggedToJSPrimitiveOrDeoptOp (V< Untagged > input, V< FrameState > frame_state, JSPrimitiveKind kind, RegisterRepresentation input_rep, InputInterpretation input_interpretation, const FeedbackSource &feedback)
void Validate (const Graph &graph) const
auto options () const
Public Attributes
JSPrimitiveKind kind
RegisterRepresentation input_rep
InputInterpretation input_interpretation
FeedbackSource feedback
Static Public Attributes
static constexpr OpEffects effects = OpEffects().CanDeopt()
Additional Inherited Members
Detailed Description
Definition at line 4868 of file operations.h.
Member Enumeration Documentation
InputInterpretation
enum v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOrDeoptOp::InputInterpretation : uint8_t [strong]
Enumerator
kSigned
kUnsigned
Definition at line 4873 of file operations.h.
                                 : uint8_t {
    kSigned,
    kUnsigned,
  };
JSPrimitiveKind
enum v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOrDeoptOp::JSPrimitiveKind : uint8_t [strong]
Enumerator
kSmi
Definition at line 4870 of file operations.h.
                             : uint8_t {
    kSmi,
  };
Constructor & Destructor Documentation
ConvertUntaggedToJSPrimitiveOrDeoptOp()
v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOrDeoptOp::ConvertUntaggedToJSPrimitiveOrDeoptOp (V< Untagged > input, V< FrameState > frame_state, JSPrimitiveKind kind, RegisterRepresentation input_rep, InputInterpretation input_interpretation, const FeedbackSource & feedback) [inline]
Definition at line 4897 of file operations.h.
      : Base(input, frame_state),
        kind(kind),
        input_rep(input_rep),
        input_interpretation(input_interpretation),
        feedback(feedback) {}
Member Function Documentation
frame_state()
V<FrameState> v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOrDeoptOp::frame_state () const [inline]
Definition at line 4895 of file operations.h.
{ return Base::input<FrameState>(1); }
input()
V<Untagged> v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOrDeoptOp::input () const [inline]
Definition at line 4894 of file operations.h.
{ return Base::input<Untagged>(0); }
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOrDeoptOp::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 4889 of file operations.h.
                                                              {
    return InputsRepFactory::SingleRep(input_rep);
  }
References v8::internal::compiler::turboshaft::InputsRepFactory::SingleRep().
options()
auto v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOrDeoptOp::options () const [inline]
Definition at line 4911 of file operations.h.
                       {
    return std::tuple{kind, input_rep, input_interpretation, feedback};
  }
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOrDeoptOp::outputs_rep () const [inline]
Definition at line 4885 of file operations.h.
                                                               {
    return RepVector<RegisterRepresentation::Tagged()>();
  }
Validate()
void v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOrDeoptOp::Validate (const Graph & graph) const [inline]
Definition at line 4907 of file operations.h.
                                          {
    DCHECK(Get(graph, frame_state()).Is<FrameStateOp>());
  }
References v8::internal::DCHECK(), v8::internal::compiler::turboshaft::Get(), and graph().
Member Data Documentation
effects
constexpr OpEffects v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOrDeoptOp::effects = OpEffects().CanDeopt() [static], [constexpr]
Definition at line 4884 of file operations.h.
feedback
FeedbackSource v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOrDeoptOp::feedback
Definition at line 4880 of file operations.h.
input_interpretation
InputInterpretation v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOrDeoptOp::input_interpretation
Definition at line 4879 of file operations.h.
input_rep
RegisterRepresentation v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOrDeoptOp::input_rep
Definition at line 4878 of file operations.h.
kind
JSPrimitiveKind v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOrDeoptOp::kind
Definition at line 4877 of file operations.h.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h