v8::internal::compiler::turboshaft::WordOperationTyper< Bits > Struct Template Reference
#include <typer.h>
Public Types
using word_t = uint_type< Bits >
using type_t = WordType< Bits >
using ElementsVector = base::SmallVector< word_t, type_t::kMaxSetSize *2 >
Static Public Member Functions
static type_t FromElements (ElementsVector elements, Zone *zone)
static std::pair< word_t, word_t > MakeRange (const type_t &t)
static std::pair< word_t, word_t > MakeRange (base::Vector< const word_t > elements)
static word_t distance (const std::pair< word_t, word_t > &range)
static word_t distance (word_t from, word_t to)
static bool is_wrapping (const std::pair< word_t, word_t > &range)
static bool is_wrapping (word_t from, word_t to)
static type_t Add (const type_t &lhs, const type_t &rhs, Zone *zone)
static type_t Subtract (const type_t &lhs, const type_t &rhs, Zone *zone)
static Word32Type UnsignedLessThan (const type_t &lhs, const type_t &rhs, Zone *zone)
static Word32Type UnsignedLessThanOrEqual (const type_t &lhs, const type_t &rhs, Zone *zone)
static std::pair< Type, Type > RestrictionForUnsignedLessThan_True (const type_t &lhs, const type_t &rhs, Zone *zone)
static std::pair< Type, Type > RestrictionForUnsignedLessThan_False (const type_t &lhs, const type_t &rhs, Zone *zone)
static std::pair< Type, Type > RestrictionForUnsignedLessThanOrEqual_True (const type_t &lhs, const type_t &rhs, Zone *zone)
static std::pair< Type, Type > RestrictionForUnsignedLessThanOrEqual_False (const type_t &lhs, const type_t &rhs, Zone *zone)
static type_t WidenMaximal (const type_t &old_type, const type_t &new_type, Zone *zone)
static type_t WidenExponential (const type_t &old_type, type_t new_type, Zone *zone)
Static Public Attributes
static constexpr word_t max = std::numeric_limits<word_t>::max()
Detailed Description
template<size_t Bits>
struct v8::internal::compiler::turboshaft::WordOperationTyper< Bits >
Definition at line 51 of file typer.h.
Member Typedef Documentation
ElementsVector
template<size_t Bits>
using v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::ElementsVector = base::SmallVector<word_t, type_t::kMaxSetSize * 2>
Definition at line 55 of file typer.h.
type_t
template<size_t Bits>
using v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::type_t = WordType<Bits>
Definition at line 54 of file typer.h.
word_t
template<size_t Bits>
using v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::word_t = uint_type<Bits>
Definition at line 53 of file typer.h.
Member Function Documentation
Add()
template<size_t Bits>
static type_t v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::Add (const type_t & lhs, const type_t & rhs, Zone * zone) [inline], [static]
Definition at line 122 of file typer.h.
                                                                      {
    if (lhs.is_any() || rhs.is_any()) return type_t::Any();
    // If both sides are decently small sets, we produce the product set (which
    // we convert to a range if it exceeds the set limit).
    if (lhs.is_set() && rhs.is_set()) {
      ElementsVector result_elements;
      for (int i = 0; i < lhs.set_size(); ++i) {
        for (int j = 0; j < rhs.set_size(); ++j) {
          result_elements.push_back(lhs.set_element(i) + rhs.set_element(j));
        }
      }
      return FromElements(std::move(result_elements), zone);
    }
    // Otherwise just construct a range.
    std::pair<word_t, word_t> x = MakeRange(lhs);
    std::pair<word_t, word_t> y = MakeRange(rhs);
    // If the result would not be a complete range, we compute it.
    // Check: (lhs.to - lhs.from + 1) + rhs.to - rhs.from < max
    // =====> (lhs.to - lhs.from + 1) < max - rhs.to + rhs.from
    // =====> (lhs.to - lhs.from + 1) < max - (rhs.to - rhs.from)
    if (distance(x) + 1 < max - distance(y)) {
      return type_t::Range(x.first + y.first, x.second + y.second, zone);
    }
    return type_t::Any();
  }
References v8::internal::compiler::turboshaft::WordType< Bits >::Any(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::distance(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::FromElements(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::WordType< Bits >::is_any(), v8::internal::compiler::turboshaft::WordType< Bits >::is_set(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::MakeRange(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::max, v8::base::SmallVector< T, kSize, Allocator >::push_back(), v8::internal::compiler::turboshaft::WordType< Bits >::Range(), v8::internal::compiler::turboshaft::WordType< Bits >::set_element(), v8::internal::compiler::turboshaft::WordType< Bits >::set_size(), and v8::internal::y.
Referenced by v8::internal::compiler::turboshaft::Typer::TypeWord32Add(), v8::internal::compiler::turboshaft::Typer::TypeWord32OverflowCheckedAdd(), and v8::internal::compiler::turboshaft::Typer::TypeWord64Add().
distance() [1/2]
template<size_t Bits>
static word_t v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::distance (const std::pair< word_t, word_t > & range) [inline], [static]
Definition at line 110 of file typer.h.
                                                               {
    return distance(range.first, range.second);
  }
Referenced by v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::Add(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::Subtract(), and v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::WidenExponential().
distance() [2/2]
template<size_t Bits>
static word_t v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::distance (word_t from, word_t to) [inline], [static]
Definition at line 113 of file typer.h.
                                                 {
    return is_wrapping(from, to) ? (max - from + to) : to - from;
  }
References v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::is_wrapping(), and v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::max.
FromElements()
template<size_t Bits>
static type_t v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::FromElements (ElementsVector elements, Zone * zone) [inline], [static]
Definition at line 58 of file typer.h.
                                                                  {
    base::sort(elements);
    auto it = std::unique(elements.begin(), elements.end());
    elements.pop_back(std::distance(it, elements.end()));
    DCHECK(!elements.empty());
    if (elements.size() <= type_t::kMaxSetSize) {
      return type_t::Set(elements, zone);
    }
    auto range = MakeRange(base::VectorOf(elements));
    auto result = type_t::Range(range.first, range.second, zone);
    DCHECK(
        base::all_of(elements, [&](word_t e) { return result.Contains(e); }));
    return result;
  }
References v8::base::all_of(), v8::base::SmallVector< T, kSize, Allocator >::begin(), v8::internal::DCHECK(), v8::base::SmallVector< T, kSize, Allocator >::empty(), v8::base::SmallVector< T, kSize, Allocator >::end(), v8::internal::compiler::turboshaft::WordType< Bits >::kMaxSetSize, v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::MakeRange(), v8::base::SmallVector< T, kSize, Allocator >::pop_back(), v8::internal::compiler::turboshaft::WordType< Bits >::Range(), v8::base::internal::result, v8::internal::compiler::turboshaft::WordType< Bits >::Set(), v8::base::SmallVector< T, kSize, Allocator >::size(), v8::base::sort(), and v8::base::VectorOf().
Referenced by v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::Add(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::Subtract(), and v8::internal::compiler::turboshaft::Typer::TruncateWord32Input().
is_wrapping() [1/2]
template<size_t Bits>
static bool v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::is_wrapping (const std::pair< word_t, word_t > & range) [inline], [static]
Definition at line 117 of file typer.h.
                                                                {
    return is_wrapping(range.first, range.second);
  }
Referenced by v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::distance(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::Subtract(), and v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::WidenExponential().
is_wrapping() [2/2]
template<size_t Bits>
static bool v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::is_wrapping (word_t from, word_t to) [inline], [static]
Definition at line 120 of file typer.h.
{ return from > to; }
MakeRange() [1/2]
template<size_t Bits>
static std::pair<word_t, word_t> v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::MakeRange (base::Vector< const word_t > elements) [inline], [static]
Definition at line 88 of file typer.h.
                                         {
    DCHECK(!elements.empty());
    DCHECK(detail::is_unique_and_sorted(elements));
    if (elements[elements.size() - 1] - elements[0] <= max / 2) {
      // Construct a non-wrapping range.
      return {elements[0], elements[elements.size() - 1]};
    }
    // Construct a wrapping range.
    size_t from_index = elements.size() - 1;
    size_t to_index = 0;
    while (to_index + 1 < from_index) {
      if ((elements[to_index + 1] - elements[to_index]) <
          (elements[from_index] - elements[from_index - 1])) {
        ++to_index;
      } else {
        --from_index;
      }
    }
    return {elements[from_index], elements[to_index]};
  }
References v8::internal::DCHECK(), v8::base::Vector< T >::empty(), v8::internal::compiler::turboshaft::detail::is_unique_and_sorted(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::max, and v8::base::Vector< T >::size().
MakeRange() [2/2]
template<size_t Bits>
static std::pair<word_t, word_t> v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::MakeRange (const type_t & t) [inline], [static]
Definition at line 74 of file typer.h.
                                                            {
    if (t.is_range()) return t.range();
    DCHECK(t.is_set());
    return MakeRange(t.set_elements());
  }
References v8::internal::DCHECK(), v8::internal::compiler::turboshaft::WordType< Bits >::is_range(), v8::internal::compiler::turboshaft::WordType< Bits >::is_set(), v8::internal::compiler::turboshaft::WordType< Bits >::range(), and v8::internal::compiler::turboshaft::WordType< Bits >::set_elements().
Referenced by v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::Add(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::FromElements(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::Subtract(), and v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::WidenExponential().
RestrictionForUnsignedLessThan_False()
template<size_t Bits>
static std::pair<Type, Type> v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::RestrictionForUnsignedLessThan_False (const type_t & lhs, const type_t & rhs, Zone * zone) [inline], [static]
Definition at line 232 of file typer.h.
                                                        {
    return {type_t::Range(rhs.unsigned_min(), max, zone),
            type_t::Range(0, lhs.unsigned_max(), zone)};
  }
References v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::max, v8::internal::compiler::turboshaft::WordType< Bits >::Range(), v8::internal::compiler::turboshaft::WordType< Bits >::unsigned_max(), and v8::internal::compiler::turboshaft::WordType< Bits >::unsigned_min().
RestrictionForUnsignedLessThan_True()
template<size_t Bits>
static std::pair<Type, Type> v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::RestrictionForUnsignedLessThan_True (const type_t & lhs, const type_t & rhs, Zone * zone) [inline], [static]
Definition at line 208 of file typer.h.
                                                        {
    Type restrict_lhs;
    if (rhs.unsigned_max() == 0) {
      // There is no value for lhs that could make (lhs < 0) true.
      restrict_lhs = Type::None();
    } else {
      restrict_lhs = type_t::Range(0, next_smaller(rhs.unsigned_max()), zone);
    }
    Type restrict_rhs;
    if (lhs.unsigned_min() == max) {
      // There is no value for rhs that could make (max < rhs) true.
      restrict_rhs = Type::None();
    } else {
      restrict_rhs = type_t::Range(next_larger(lhs.unsigned_min()), max, zone);
    }
    return {restrict_lhs, restrict_rhs};
  }
References v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::max, v8::internal::compiler::turboshaft::Type::None(), v8::internal::compiler::turboshaft::WordType< Bits >::Range(), v8::internal::compiler::turboshaft::WordType< Bits >::unsigned_max(), and v8::internal::compiler::turboshaft::WordType< Bits >::unsigned_min().
RestrictionForUnsignedLessThanOrEqual_False()
template<size_t Bits>
static std::pair<Type, Type> v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::RestrictionForUnsignedLessThanOrEqual_False (const type_t & lhs, const type_t & rhs, Zone * zone) [inline], [static]
Definition at line 250 of file typer.h.
                                                        {
    Type restrict_lhs;
    if (rhs.unsigned_min() == max) {
      // There is no value for lhs that could make (lhs <= max) false.
      restrict_lhs = Type::None();
    } else {
      restrict_lhs = type_t::Range(next_larger(rhs.unsigned_min()), max, zone);
    }
    Type restrict_rhs;
    if (lhs.unsigned_max() == 0) {
      // There is no value for rhs that could make (0 <= rhs) false.
      restrict_rhs = Type::None();
    } else {
      restrict_rhs = type_t::Range(0, next_smaller(lhs.unsigned_max()), zone);
    }
    return {restrict_lhs, restrict_rhs};
  }
References v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::max, v8::internal::compiler::turboshaft::Type::None(), v8::internal::compiler::turboshaft::WordType< Bits >::Range(), v8::internal::compiler::turboshaft::WordType< Bits >::unsigned_max(), and v8::internal::compiler::turboshaft::WordType< Bits >::unsigned_min().
RestrictionForUnsignedLessThanOrEqual_True()
template<size_t Bits>
static std::pair<Type, Type> v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::RestrictionForUnsignedLessThanOrEqual_True (const type_t & lhs, const type_t & rhs, Zone * zone) [inline], [static]
Definition at line 241 of file typer.h.
                                                        {
    return {type_t::Range(0, rhs.unsigned_max(), zone),
            type_t::Range(lhs.unsigned_min(), max, zone)};
  }
References v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::max, v8::internal::compiler::turboshaft::WordType< Bits >::Range(), v8::internal::compiler::turboshaft::WordType< Bits >::unsigned_max(), and v8::internal::compiler::turboshaft::WordType< Bits >::unsigned_min().
Subtract()
template<size_t Bits>
static type_t v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::Subtract (const type_t & lhs, const type_t & rhs, Zone * zone) [inline], [static]
Definition at line 152 of file typer.h.
                                                                           {
    if (lhs.is_any() || rhs.is_any()) return type_t::Any();
    // If both sides are decently small sets, we produce the product set (which
    // we convert to a range if it exceeds the set limit).
    if (lhs.is_set() && rhs.is_set()) {
      ElementsVector result_elements;
      for (int i = 0; i < lhs.set_size(); ++i) {
        for (int j = 0; j < rhs.set_size(); ++j) {
          result_elements.push_back(lhs.set_element(i) - rhs.set_element(j));
        }
      }
      return FromElements(std::move(result_elements), zone);
    }
    // Otherwise just construct a range.
    std::pair<word_t, word_t> x = MakeRange(lhs);
    std::pair<word_t, word_t> y = MakeRange(rhs);
    if (!is_wrapping(x) && !is_wrapping(y)) {
      // If the result would not be a complete range, we compute it.
      // Check: (lhs.to - lhs.from + 1) + rhs.to - rhs.from < max
      // =====> (lhs.to - lhs.from + 1) < max - rhs.to + rhs.from
      // =====> (lhs.to - lhs.from + 1) < max - (rhs.to - rhs.from)
      if (distance(x) + 1 < max - distance(y)) {
        return type_t::Range(x.first - y.second, x.second - y.first, zone);
      }
    }
    // TODO(nicohartmann@): Improve the wrapping cases.
    return type_t::Any();
  }
References v8::internal::compiler::turboshaft::WordType< Bits >::Any(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::distance(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::FromElements(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::WordType< Bits >::is_any(), v8::internal::compiler::turboshaft::WordType< Bits >::is_set(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::is_wrapping(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::MakeRange(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::max, v8::base::SmallVector< T, kSize, Allocator >::push_back(), v8::internal::compiler::turboshaft::WordType< Bits >::Range(), v8::internal::compiler::turboshaft::WordType< Bits >::set_element(), v8::internal::compiler::turboshaft::WordType< Bits >::set_size(), and v8::internal::y.
Referenced by v8::internal::compiler::turboshaft::Typer::TypeWord32Sub(), and v8::internal::compiler::turboshaft::Typer::TypeWord64Sub().
UnsignedLessThan()
template<size_t Bits>
static Word32Type v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::UnsignedLessThan (const type_t & lhs, const type_t & rhs, Zone * zone) [inline], [static]
Definition at line 185 of file typer.h.
                                                 {
    bool can_be_true = lhs.unsigned_min() < rhs.unsigned_max();
    bool can_be_false = lhs.unsigned_max() >= rhs.unsigned_min();
    if (!can_be_true) return Word32Type::Constant(0);
    if (!can_be_false) return Word32Type::Constant(1);
    return Word32Type::Set({0, 1}, zone);
  }
References v8::internal::compiler::turboshaft::WordType< Bits >::Constant(), v8::internal::compiler::turboshaft::WordType< Bits >::Set(), v8::internal::compiler::turboshaft::WordType< Bits >::unsigned_max(), and v8::internal::compiler::turboshaft::WordType< Bits >::unsigned_min().
Referenced by v8::internal::compiler::turboshaft::Typer::TypeWord32Comparison(), and v8::internal::compiler::turboshaft::Typer::TypeWord64Comparison().
UnsignedLessThanOrEqual()
template<size_t Bits>
static Word32Type v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::UnsignedLessThanOrEqual (const type_t & lhs, const type_t & rhs, Zone * zone) [inline], [static]
Definition at line 195 of file typer.h.
                                                                           {
    bool can_be_true = lhs.unsigned_min() <= rhs.unsigned_max();
    bool can_be_false = lhs.unsigned_max() > rhs.unsigned_min();
    if (!can_be_true) return Word32Type::Constant(0);
    if (!can_be_false) return Word32Type::Constant(1);
    return Word32Type::Set({0, 1}, zone);
  }
References v8::internal::compiler::turboshaft::WordType< Bits >::Constant(), v8::internal::compiler::turboshaft::WordType< Bits >::Set(), v8::internal::compiler::turboshaft::WordType< Bits >::unsigned_max(), and v8::internal::compiler::turboshaft::WordType< Bits >::unsigned_min().
Referenced by v8::internal::compiler::turboshaft::Typer::TypeWord32Comparison(), and v8::internal::compiler::turboshaft::Typer::TypeWord64Comparison().
WidenExponential()
template<size_t Bits>
static type_t v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::WidenExponential (const type_t & old_type, type_t new_type, Zone * zone) [inline], [static]
Definition at line 290 of file typer.h.
                                             {
    if (new_type.is_any()) return new_type;
    word_t old_from, old_to, new_from, new_to;
    if (old_type.is_set()) {
      const word_t old_size = old_type.set_size();
      if (new_type.is_set()) {
        const word_t new_size = new_type.set_size();
        if (new_size >= 2 * old_size) return new_type;
        std::tie(new_from, new_to) = MakeRange(new_type);
      } else {
        DCHECK(new_type.is_range());
        std::tie(new_from, new_to) = new_type.range();
      }
      if (distance(new_from, new_to) >= 2 * old_size) {
        return type_t::Range(new_from, new_to, zone);
      }
      std::tie(old_from, old_to) = MakeRange(old_type);
    } else {
      DCHECK(old_type.is_range());
      std::tie(old_from, old_to) = old_type.range();
      if (new_type.is_set()) {
        std::tie(new_from, new_to) = MakeRange(new_type);
      } else {
        DCHECK(new_type.is_range());
        std::tie(new_from, new_to) = new_type.range();
      }
    }
    // If the old type is already quite large, we go to full range.
    if (distance(old_from, old_to) >= std::numeric_limits<word_t>::max() / 4) {
      return type_t::Any();
    }
    const word_t min_size = 2 * (distance(old_from, old_to) + 1);
    if (distance(new_from, new_to) >= min_size) {
      return type_t::Range(new_from, new_to, zone);
    }
    // If old is wrapping (and so is new).
    if (is_wrapping(old_from, old_to)) {
      DCHECK(is_wrapping(new_from, new_to));
      if (new_from < old_from) {
        DCHECK_LE(old_to, new_to);
        // We widen the `from` (although `to` might have grown, too).
        DCHECK_LT(new_to, min_size);
        word_t result_from =
            std::numeric_limits<word_t>::max() - (min_size - new_to);
        DCHECK_LT(result_from, new_from);
        DCHECK_LE(min_size, distance(result_from, new_to));
        return type_t::Range(result_from, new_to, zone);
      } else {
        DCHECK_EQ(old_from, new_from);
        // We widen the `to`.
        DCHECK_LT(std::numeric_limits<word_t>::max() - new_from, min_size);
        word_t result_to =
            min_size - (std::numeric_limits<word_t>::max() - new_from);
        DCHECK_GT(result_to, new_to);
        DCHECK_LE(min_size, distance(new_from, result_to));
        return type_t::Range(new_from, result_to, zone);
      }
    }
    // If old is not wrapping, but new is.
    if (is_wrapping(new_from, new_to)) {
      if (new_to < old_to) {
        // If wrapping was caused by to growing over max, grow `to` further
        // (although `from` might have grown, too).
        DCHECK_LT(std::numeric_limits<word_t>::max() - new_from, min_size);
        word_t result_to =
            min_size - (std::numeric_limits<word_t>::max() - new_from);
        DCHECK_LT(new_to, result_to);
        return type_t::Range(new_from, result_to, zone);
      } else {
        DCHECK_LT(old_from, new_from);
        // If wrapping was caused by `from` growing below 0, grow `from`
        // further.
        DCHECK_LT(new_to, min_size);
        word_t result_from =
            std::numeric_limits<word_t>::max() - (min_size - new_to);
        DCHECK_LT(result_from, new_from);
        return type_t::Range(result_from, new_to, zone);
      }
    }
    // Neither old nor new is wrapping.
    if (new_from < old_from) {
      DCHECK_LE(old_to, new_to);
      // Check if we can widen the `from`.
      if (new_to >= min_size) {
        // We can decrease `from` without going below 0.
        word_t result_from = new_to - min_size;
        DCHECK_LT(result_from, new_from);
        return type_t::Range(result_from, new_to, zone);
      } else {
        // We cannot grow `from` enough, so we also have to grow `to`.
        return type_t::Range(0, min_size, zone);
      }
    } else {
      DCHECK_EQ(old_from, new_from);
      // Check if we can widen the `to`.
      if (new_from <= std::numeric_limits<word_t>::max() - min_size) {
        // We can increase `to` without going above max.
        word_t result_to = new_from + min_size;
        DCHECK_GT(result_to, new_to);
        return type_t::Range(new_from, result_to, zone);
      } else {
        // We cannot grow `to` enough, so we also have to grow `from`.
        return type_t::Range(std::numeric_limits<word_t>::max() - min_size,
                             std::numeric_limits<word_t>::max(), zone);
      }
    }
  }
References v8::internal::compiler::turboshaft::WordType< Bits >::Any(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GT, DCHECK_LE, DCHECK_LT, v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::distance(), v8::internal::compiler::turboshaft::WordType< Bits >::is_any(), v8::internal::compiler::turboshaft::WordType< Bits >::is_range(), v8::internal::compiler::turboshaft::WordType< Bits >::is_set(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::is_wrapping(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::MakeRange(), v8::internal::compiler::turboshaft::WordType< Bits >::range(), v8::internal::compiler::turboshaft::WordType< Bits >::Range(), and v8::internal::compiler::turboshaft::WordType< Bits >::set_size().
WidenMaximal()
template<size_t Bits>
static type_t v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::WidenMaximal (const type_t & old_type, const type_t & new_type, Zone * zone) [inline], [static]
Definition at line 272 of file typer.h.
                                         {
    if (new_type.is_any()) return new_type;
    if (old_type.is_wrapping() || new_type.is_wrapping()) return type_t::Any();
    word_t result_from = new_type.unsigned_min();
    if (result_from < old_type.unsigned_min()) result_from = 0;
    word_t result_to = new_type.unsigned_max();
    if (result_to > old_type.unsigned_max()) {
      result_to = std::numeric_limits<word_t>::max();
    }
    return type_t::Range(result_from, result_to, zone);
  }
References v8::internal::compiler::turboshaft::WordType< Bits >::Any(), v8::internal::compiler::turboshaft::WordType< Bits >::is_any(), v8::internal::compiler::turboshaft::WordType< Bits >::is_wrapping(), v8::internal::compiler::turboshaft::WordType< Bits >::Range(), v8::internal::compiler::turboshaft::WordType< Bits >::unsigned_max(), and v8::internal::compiler::turboshaft::WordType< Bits >::unsigned_min().
Referenced by v8::internal::compiler::turboshaft::TypeInferenceAnalysis::Widen().
Member Data Documentation
max
template<size_t Bits>
constexpr word_t v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::max = std::numeric_limits<word_t>::max() [static], [constexpr]
Definition at line 56 of file typer.h.
Referenced by v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::Add(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::distance(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::MakeRange(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::RestrictionForUnsignedLessThan_False(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::RestrictionForUnsignedLessThan_True(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::RestrictionForUnsignedLessThanOrEqual_False(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::RestrictionForUnsignedLessThanOrEqual_True(), and v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::Subtract().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/typer.h