v8::internal::compiler::turboshaft::detail::BitfieldCheck Struct Reference
#include <machine-optimization-reducer.h>
Public Member Functions
BitfieldCheck (V< Word > source, uint32_t mask, uint32_t masked_value, bool truncate_from_64_bit)
std::optional< BitfieldCheck > TryCombine (const BitfieldCheck &other)
Static Public Member Functions
static std::optional< BitfieldCheck > Detect (const OperationMatcher &matcher, const Graph &graph, V< Word > index)
Public Attributes
V< Word > const source
uint32_t const mask
uint32_t const masked_value
bool const truncate_from_64_bit
Static Private Member Functions
template<typename WordType >
static std::optional< BitfieldCheck > TryDetectShiftAndMaskOneBit (const OperationMatcher &matcher, V< Word > index)
Detailed Description
Definition at line 80 of file machine-optimization-reducer.h.
Constructor & Destructor Documentation
BitfieldCheck()
v8::internal::compiler::turboshaft::detail::BitfieldCheck::BitfieldCheck (V< Word > source, uint32_t mask, uint32_t masked_value, bool truncate_from_64_bit) [inline]
Definition at line 86 of file machine-optimization-reducer.h.
      : source(source),
        mask(mask),
        masked_value(masked_value),
        truncate_from_64_bit(truncate_from_64_bit) {
    CHECK_EQ(masked_value & ~mask, 0);
  }
References CHECK_EQ, mask, and masked_value.
Member Function Documentation
Detect()
static std::optional<BitfieldCheck> v8::internal::compiler::turboshaft::detail::BitfieldCheck::Detect (const OperationMatcher & matcher, const Graph & graph, V< Word > index) [inline], [static]
Definition at line 95 of file machine-optimization-reducer.h.
                                                            {
    // There are two patterns to check for here:
    // 1. Single-bit checks: `(val >> shift) & 1`, where:
    // - the shift may be omitted, and/or
    // - the result may be truncated from 64 to 32
    // 2. Equality checks: `(val & mask) == expected`, where:
    // - val may be truncated from 64 to 32 before masking (see
    // ReduceWordEqualForConstantRhs)
    const Operation& op = graph.Get(index);
    if (const ComparisonOp* equal = op.TryCast<Opmask::kWord32Equal>()) {
      if (const WordBinopOp* left_and =
              graph.Get(equal->left<Word32>())
                  .TryCast<Opmask::kWord32BitwiseAnd>()) {
        uint32_t mask;
        uint32_t masked_value;
        if (matcher.MatchIntegralWord32Constant(left_and->right(), &mask) &&
            matcher.MatchIntegralWord32Constant(equal->right<Word32>(),
                                                &masked_value)) {
          if ((masked_value & ~mask) != 0) return std::nullopt;
          if (const ChangeOp* truncate =
                  graph.Get(left_and->left())
                      .TryCast<Opmask::kTruncateWord64ToWord32>()) {
            return BitfieldCheck{truncate->input<Word64>(), mask, masked_value,
                                 true};
          } else {
            return BitfieldCheck{left_and->left(), mask, masked_value, false};
          }
        }
      }
    } else if (const ChangeOp* truncate =
                   op.TryCast<Opmask::kTruncateWord64ToWord32>()) {
      return TryDetectShiftAndMaskOneBit<Word64>(matcher,
                                                 truncate->input<Word64>());
    } else {
      return TryDetectShiftAndMaskOneBit<Word32>(matcher, index);
    }
    return std::nullopt;
  }
References v8::internal::equal, graph(), v8::internal::index, mask, masked_value, v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralWord32Constant(), and v8::internal::compiler::turboshaft::Operation::TryCast().
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordBinop().
TryCombine()
std::optional<BitfieldCheck> v8::internal::compiler::turboshaft::detail::BitfieldCheck::TryCombine (const BitfieldCheck & other) [inline]
Definition at line 136 of file machine-optimization-reducer.h.
                                                                    {
    if (source != other.source ||
        truncate_from_64_bit != other.truncate_from_64_bit) {
      return std::nullopt;
    }
    uint32_t overlapping_bits = mask & other.mask;
    // It would be kind of strange to have any overlapping bits, but they can be
    // allowed as long as they don't require opposite values in the same
    // positions.
    if ((masked_value & overlapping_bits) !=
        (other.masked_value & overlapping_bits)) {
      return std::nullopt;
    }
    return BitfieldCheck{source, mask | other.mask,
                         masked_value | other.masked_value,
                         truncate_from_64_bit};
  }
References mask, masked_value, source, and truncate_from_64_bit.
TryDetectShiftAndMaskOneBit()
template<typename WordType >
static std::optional<BitfieldCheck> v8::internal::compiler::turboshaft::detail::BitfieldCheck::TryDetectShiftAndMaskOneBit (const OperationMatcher & matcher, V< Word > index) [inline], [static], [private]
Definition at line 156 of file machine-optimization-reducer.h.
                                                      {
    constexpr WordRepresentation Rep = V<WordType>::rep;
    // Look for the pattern `(val >> shift) & 1`. The shift may be omitted.
    V<WordType> value;
    uint64_t constant;
    if (matcher.MatchBitwiseAndWithConstant(index, &value, &constant, Rep) &&
        constant == 1) {
      V<WordType> input;
      if (int shift_amount;
          matcher.MatchConstantRightShift(value, &input, Rep, &shift_amount) &&
          shift_amount >= 0 && shift_amount < 32) {
        uint32_t mask = 1 << shift_amount;
        return BitfieldCheck{input, mask, mask,
                             Rep == WordRepresentation::Word64()};
      }
      return BitfieldCheck{value, 1, 1, Rep == WordRepresentation::Word64()};
    }
    return std::nullopt;
  }
References v8::internal::index, mask, v8::internal::value, and v8::internal::compiler::turboshaft::WordRepresentation::Word64().
Member Data Documentation
mask
uint32_t const v8::internal::compiler::turboshaft::detail::BitfieldCheck::mask
Definition at line 82 of file machine-optimization-reducer.h.
Referenced by BitfieldCheck(), Detect(), TryCombine(), and TryDetectShiftAndMaskOneBit().
masked_value
uint32_t const v8::internal::compiler::turboshaft::detail::BitfieldCheck::masked_value
Definition at line 83 of file machine-optimization-reducer.h.
Referenced by BitfieldCheck(), Detect(), and TryCombine().
source
V<Word> const v8::internal::compiler::turboshaft::detail::BitfieldCheck::source
Definition at line 81 of file machine-optimization-reducer.h.
Referenced by TryCombine().
truncate_from_64_bit
bool const v8::internal::compiler::turboshaft::detail::BitfieldCheck::truncate_from_64_bit
Definition at line 84 of file machine-optimization-reducer.h.
Referenced by TryCombine().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/machine-optimization-reducer.h