v8::internal::compiler::InstructionSelector::CachedStateValues Struct Reference
Public Member Functions
CachedStateValues (Zone *zone, StateValueList *values, size_t values_start, InstructionOperandVector *inputs, size_t inputs_start)
size_t Emit (InstructionOperandVector *inputs, StateValueList *values)
Private Attributes
InstructionOperandVector inputs_
StateValueList::Slice values_
Detailed Description
Definition at line 747 of file instruction-selector.cc.
Constructor & Destructor Documentation
CachedStateValues()
v8::internal::compiler::InstructionSelector::CachedStateValues::CachedStateValues (Zone * zone, StateValueList * values, size_t values_start, InstructionOperandVector * inputs, size_t inputs_start) [inline]
Definition at line 749 of file instruction-selector.cc.
      : inputs_(inputs->begin() + inputs_start, inputs->end(), zone),
        values_(values->MakeSlice(values_start)) {}
Member Function Documentation
Emit()
size_t v8::internal::compiler::InstructionSelector::CachedStateValues::Emit (InstructionOperandVector * inputs, StateValueList * values) [inline]
Definition at line 754 of file instruction-selector.cc.
                                                                        {
    inputs->insert(inputs->end(), inputs_.begin(), inputs_.end());
    values->PushCachedSlice(values_);
    return inputs_.size();
  }
References v8::internal::ZoneVector< T >::begin(), v8::internal::ZoneVector< T >::end(), inputs_, v8::internal::ZoneVector< T >::insert(), v8::internal::compiler::StateValueList::PushCachedSlice(), v8::internal::ZoneVector< T >::size(), and values_.
Member Data Documentation
inputs_
InstructionOperandVector v8::internal::compiler::InstructionSelector::CachedStateValues::inputs_ [private]
Definition at line 761 of file instruction-selector.cc.
Referenced by Emit().
values_
StateValueList::Slice v8::internal::compiler::InstructionSelector::CachedStateValues::values_ [private]
Definition at line 762 of file instruction-selector.cc.
Referenced by Emit().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/instruction-selector.cc