v8::internal::compiler::Node::OutOfLineInputs Struct Reference
Public Member Functions
ZoneNodePtr * inputs ()
void ExtractFrom (Use *use_ptr, ZoneNodePtr *input_ptr, int count)
Static Public Member Functions
static OutOfLineInputs * New (Zone *zone, int capacity)
Public Attributes
ZoneNodePtr node_
int count_
int capacity_
Detailed Description
Definition at line 167 of file node.h.
Member Function Documentation
ExtractFrom()
void v8::internal::compiler::Node::OutOfLineInputs::ExtractFrom (Use * use_ptr, ZoneNodePtr * input_ptr, int count)
Definition at line 23 of file node.cc.
                                                                               {
  DCHECK_GE(count, 0);
  // Extract the inputs from the old use and input pointers and copy them
  // to this out-of-line-storage.
  Use* new_use_ptr = reinterpret_cast<Use*>(this) - 1;
  ZoneNodePtr* new_input_ptr = inputs();
  CHECK_IMPLIES(count > 0, Use::InputIndexField::is_valid(count - 1));
  for (int current = 0; current < count; current++) {
    new_use_ptr->bit_field_ =
        Use::InputIndexField::encode(current) | Use::InlineField::encode(false);
    DCHECK_EQ(old_input_ptr, old_use_ptr->input_ptr());
    DCHECK_EQ(new_input_ptr, new_use_ptr->input_ptr());
    Node* old_to = *old_input_ptr;
    if (old_to) {
      *old_input_ptr = nullptr;
      old_to->RemoveUse(old_use_ptr);
      *new_input_ptr = old_to;
      old_to->AppendUse(new_use_ptr);
    } else {
      *new_input_ptr = nullptr;
    }
    old_input_ptr++;
    new_input_ptr++;
    old_use_ptr--;
    new_use_ptr--;
  }
  this->count_ = count;
}
References v8::internal::compiler::Node::AppendUse(), v8::internal::compiler::Node::Use::bit_field_, CHECK_IMPLIES, v8::internal::compiler::Node::count(), v8::internal::compiler::Node::count_, DCHECK_EQ, DCHECK_GE, v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::Node::Use::input_ptr(), v8::internal::compiler::Node::inputs(), v8::base::BitField< T, shift, size, U >::is_valid(), and v8::internal::compiler::Node::RemoveUse().
Referenced by v8::internal::compiler::Node::AppendInput().
inputs()
ZoneNodePtr * v8::internal::compiler::Node::OutOfLineInputs::inputs () [inline]
Definition at line 312 of file node.h.
                                         {
  return reinterpret_cast<ZoneNodePtr*>(reinterpret_cast<Address>(this) +
                                        sizeof(Node::OutOfLineInputs));
}
Referenced by v8::internal::compiler::Node::Clone(), and v8::internal::compiler::Node::NewImpl().
New()
Node::OutOfLineInputs * v8::internal::compiler::Node::OutOfLineInputs::New (Zone * zone, int capacity) [static]
Definition at line 11 of file node.cc.
                                                                      {
  size_t size =
      sizeof(OutOfLineInputs) + capacity * (sizeof(Node*) + sizeof(Use));
  intptr_t raw_buffer =
      reinterpret_cast<intptr_t>(zone->Allocate<Node::OutOfLineInputs>(size));
  Node::OutOfLineInputs* outline =
      reinterpret_cast<OutOfLineInputs*>(raw_buffer + capacity * sizeof(Use));
  outline->capacity_ = capacity;
  outline->count_ = 0;
  return outline;
}
References v8::internal::Zone::Allocate(), capacity_, count_, and size().
Referenced by v8::internal::compiler::Node::AppendInput(), and v8::internal::compiler::Node::NewImpl().
Member Data Documentation
capacity_
int v8::internal::compiler::Node::OutOfLineInputs::capacity_
Definition at line 170 of file node.h.
Referenced by v8::internal::compiler::Node::AppendInput(), and New().
count_
int v8::internal::compiler::Node::OutOfLineInputs::count_
Definition at line 169 of file node.h.
Referenced by v8::internal::compiler::Node::AppendInput(), New(), v8::internal::compiler::Node::NewImpl(), and v8::internal::compiler::Node::TrimInputCount().
node_
ZoneNodePtr v8::internal::compiler::Node::OutOfLineInputs::node_
Definition at line 168 of file node.h.
Referenced by v8::internal::compiler::Node::AppendInput(), v8::internal::compiler::Node::Use::from(), and v8::internal::compiler::Node::NewImpl().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/compiler/node.h
/mnt/V8SourceCode/src/compiler/node.cc