v8::internal::SegmentedTable< Entry, size >::FreelistHead Struct Reference
#include <segmented-table.h>
Public Member Functions
constexpr FreelistHead ()
constexpr FreelistHead (uint32_t next, uint32_t length)
uint32_t next () const
uint32_t length () const
bool is_empty () const
Private Attributes
uint32_t next_
uint32_t length_
Detailed Description
template<typename Entry, size_t size>
struct v8::internal::SegmentedTable< Entry, size >::FreelistHead
Definition at line 126 of file segmented-table.h.
Constructor & Destructor Documentation
FreelistHead() [1/2]
template<typename Entry , size_t size>
constexpr v8::internal::SegmentedTable< Entry, size >::FreelistHead::FreelistHead () [inline], [constexpr]
Definition at line 127 of file segmented-table.h.
: next_(0), length_(0) {}
FreelistHead() [2/2]
template<typename Entry , size_t size>
constexpr v8::internal::SegmentedTable< Entry, size >::FreelistHead::FreelistHead (uint32_t next, uint32_t length) [inline], [constexpr]
Definition at line 128 of file segmented-table.h.
        : next_(next), length_(length) {}
Member Function Documentation
is_empty()
template<typename Entry , size_t size>
bool v8::internal::SegmentedTable< Entry, size >::FreelistHead::is_empty () const [inline]
Definition at line 138 of file segmented-table.h.
{ return length_ == 0; }
Referenced by v8::internal::ExternalEntityTable< Entry, size >::AllocateEntryBelow(), v8::internal::ExternalEntityTable< Entry, size >::TryAllocateEntry(), v8::internal::ExternalEntityTable< Entry, size >::TryAllocateEntryFromFreelist(), and v8::internal::ExternalEntityTable< Entry, size >::TryExtend().
length()
template<typename Entry , size_t size>
uint32_t v8::internal::SegmentedTable< Entry, size >::FreelistHead::length () const [inline]
Definition at line 136 of file segmented-table.h.
{ return length_; }
Referenced by v8::internal::ExternalEntityTable< Entry, size >::TryAllocateEntry(), and v8::internal::ExternalEntityTable< Entry, size >::TryAllocateEntryFromFreelist().
next()
template<typename Entry , size_t size>
uint32_t v8::internal::SegmentedTable< Entry, size >::FreelistHead::next () const [inline]
Definition at line 133 of file segmented-table.h.
{ return next_; }
Referenced by v8::internal::ExternalEntityTable< Entry, size >::AllocateEntryBelow(), v8::internal::ExternalEntityTable< Entry, size >::TryAllocateEntry(), and v8::internal::ExternalEntityTable< Entry, size >::TryAllocateEntryFromFreelist().
Member Data Documentation
length_
template<typename Entry , size_t size>
uint32_t v8::internal::SegmentedTable< Entry, size >::FreelistHead::length_ [private]
Definition at line 142 of file segmented-table.h.
next_
template<typename Entry , size_t size>
uint32_t v8::internal::SegmentedTable< Entry, size >::FreelistHead::next_ [private]
Definition at line 141 of file segmented-table.h.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/common/segmented-table.h