cppgc::internal::MakeGarbageCollectedTraitInternal::AllocationDispatcher< GCInfoType, void, api_constants::kDefaultAlignment > Struct Template Reference
#include <allocation.h>
Static Public Member Functions
static void * Invoke (AllocationHandle &handle, size_t size)
Detailed Description
template<typename GCInfoType>
struct cppgc::internal::MakeGarbageCollectedTraitInternal::AllocationDispatcher< GCInfoType, void, api_constants::kDefaultAlignment >
Definition at line 89 of file allocation.h.
Member Function Documentation
Invoke()
template<typename GCInfoType >
static void* cppgc::internal::MakeGarbageCollectedTraitInternal::AllocationDispatcher< GCInfoType, void, api_constants::kDefaultAlignment >::Invoke (AllocationHandle & handle, size_t size) [inline], [static]
Definition at line 92 of file allocation.h.
                                                               {
      return MakeGarbageCollectedTraitInternal::Allocate(
          handle, size, internal::GCInfoTrait<GCInfoType>::Index());
    }
References cppgc::internal::MakeGarbageCollectedTraitInternal::Allocate(), v8::internal::handle(), and size().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/include/cppgc/allocation.h