v8::internal::maglev::detail::PushAllHelper< Input, Args... > Struct Template Reference
#include <maglev-assembler-arm-inl.h>
Static Public Member Functions
static void Push (MaglevAssembler *masm, const Input &arg, Args... args)
static void PushReverse (MaglevAssembler *masm, const Input &arg, Args... args)
static void Push (MaglevAssembler *masm, const Input &arg, Args... args)
static void PushReverse (MaglevAssembler *masm, const Input &arg, Args... args)
static void Push (MaglevAssembler *masm, const Input &arg, Args... args)
static void PushReverse (MaglevAssembler *masm, const Input &arg, Args... args)
static void Push (MaglevAssembler *masm, const Input &arg, Args... args)
static void PushReverse (MaglevAssembler *masm, const Input &arg, Args... args)
Detailed Description
template<typename... Args>
struct v8::internal::maglev::detail::PushAllHelper< Input, Args... >
Definition at line 170 of file maglev-assembler-arm-inl.h.
Member Function Documentation
Push() [1/4]
template<typename... Args>
static void v8::internal::maglev::detail::PushAllHelper< Input, Args... >::Push (MaglevAssembler * masm, const Input & arg, Args... args) [inline], [static]
Definition at line 171 of file maglev-assembler-arm-inl.h.
                                                                          {
    PushInput(masm, arg);
    PushAllHelper<Args...>::Push(masm, args...);
  }
References v8::base::args, and v8::internal::maglev::detail::PushInput().
Push() [2/4]
template<typename... Args>
static void v8::internal::maglev::detail::PushAllHelper< Input, Args... >::Push (MaglevAssembler * masm, const Input & arg, Args... args) [inline], [static]
Definition at line 264 of file maglev-assembler-riscv-inl.h.
                                                                          {
    PushInput(masm, arg);
    PushAllHelper<Args...>::Push(masm, args...);
  }
References v8::base::args, and v8::internal::maglev::detail::PushInput().
Push() [3/4]
template<typename... Args>
static void v8::internal::maglev::detail::PushAllHelper< Input, Args... >::Push (MaglevAssembler * masm, const Input & arg, Args... args) [inline], [static]
Definition at line 170 of file maglev-assembler-s390-inl.h.
                                                                          {
    PushInput(masm, arg);
    PushAllHelper<Args...>::Push(masm, args...);
  }
References v8::base::args, and v8::internal::maglev::detail::PushInput().
Push() [4/4]
template<typename... Args>
static void v8::internal::maglev::detail::PushAllHelper< Input, Args... >::Push (MaglevAssembler * masm, const Input & arg, Args... args) [inline], [static]
Definition at line 201 of file maglev-assembler-x64-inl.h.
                                                                          {
    PushInput(masm, arg);
    PushAllHelper<Args...>::Push(masm, args...);
  }
References v8::base::args, and v8::internal::maglev::detail::PushInput().
PushReverse() [1/4]
template<typename... Args>
static void v8::internal::maglev::detail::PushAllHelper< Input, Args... >::PushReverse (MaglevAssembler * masm, const Input & arg, Args... args) [inline], [static]
Definition at line 175 of file maglev-assembler-arm-inl.h.
                                        {
    PushAllHelper<Args...>::PushReverse(masm, args...);
    PushInput(masm, arg);
  }
References v8::base::args, and v8::internal::maglev::detail::PushInput().
PushReverse() [2/4]
template<typename... Args>
static void v8::internal::maglev::detail::PushAllHelper< Input, Args... >::PushReverse (MaglevAssembler * masm, const Input & arg, Args... args) [inline], [static]
Definition at line 268 of file maglev-assembler-riscv-inl.h.
                                        {
    PushAllHelper<Args...>::PushReverse(masm, args...);
    PushInput(masm, arg);
  }
References v8::base::args, and v8::internal::maglev::detail::PushInput().
PushReverse() [3/4]
template<typename... Args>
static void v8::internal::maglev::detail::PushAllHelper< Input, Args... >::PushReverse (MaglevAssembler * masm, const Input & arg, Args... args) [inline], [static]
Definition at line 174 of file maglev-assembler-s390-inl.h.
                                        {
    PushAllHelper<Args...>::PushReverse(masm, args...);
    PushInput(masm, arg);
  }
References v8::base::args, and v8::internal::maglev::detail::PushInput().
PushReverse() [4/4]
template<typename... Args>
static void v8::internal::maglev::detail::PushAllHelper< Input, Args... >::PushReverse (MaglevAssembler * masm, const Input & arg, Args... args) [inline], [static]
Definition at line 205 of file maglev-assembler-x64-inl.h.
                                        {
    PushAllHelper<Args...>::PushReverse(masm, args...);
    PushInput(masm, arg);
  }
References v8::base::args, and v8::internal::maglev::detail::PushInput().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/maglev/arm/maglev-assembler-arm-inl.h
/mnt/V8SourceCode/src/maglev/riscv/maglev-assembler-riscv-inl.h
/mnt/V8SourceCode/src/maglev/s390/maglev-assembler-s390-inl.h
/mnt/V8SourceCode/src/maglev/x64/maglev-assembler-x64-inl.h