v8::internal::compiler::turboshaft::FloatUnaryOp Struct Reference
#include <operations.h>
Public Types
enum class Kind : uint8_t {
kAbs
, kNegate
, kSilenceNaN
, kRoundDown
,
kRoundUp
, kRoundToZero
, kRoundTiesEven
, kLog
,
kLog2
, kLog10
, kLog1p
, kSqrt
,
kCbrt
, kExp
, kExpm1
, kSin
,
kCos
, kSinh
, kCosh
, kAcos
,
kAsin
, kAsinh
, kAcosh
, kTan
,
kTanh
, kAtan
, kAtanh
 }
Public Member Functions
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
V< Float > input () const
FloatUnaryOp (V< Float > input, Kind kind, FloatRepresentation rep)
auto options () const
Static Public Member Functions
static V8_EXPORT_PRIVATE bool IsSupported (Kind kind, FloatRepresentation rep)
Public Attributes
Kind kind
FloatRepresentation rep
Static Public Attributes
static constexpr OpEffects effects = OpEffects()
Additional Inherited Members
Detailed Description
Definition at line 1944 of file operations.h.
Member Enumeration Documentation
Kind
enum v8::internal::compiler::turboshaft::FloatUnaryOp::Kind : uint8_t [strong]
Enumerator
kAbs
kNegate
kSilenceNaN
kRoundDown
kRoundUp
kRoundToZero
kRoundTiesEven
kLog
kLog2
kLog10
kLog1p
kSqrt
kCbrt
kExp
kExpm1
kSin
kCos
kSinh
kCosh
kAcos
kAsin
kAsinh
kAcosh
kTan
kTanh
kAtan
kAtanh
Definition at line 1945 of file operations.h.
                  : uint8_t {
    kAbs,
    kNegate,
    kSilenceNaN,
    kRoundDown, // round towards -infinity
    kRoundUp, // round towards +infinity
    kRoundToZero, // round towards 0
    kRoundTiesEven, // break ties by rounding towards the next even number
    kLog,
    kLog2,
    kLog10,
    kLog1p,
    kSqrt,
    kCbrt,
    kExp,
    kExpm1,
    kSin,
    kCos,
    kSinh,
    kCosh,
    kAcos,
    kAsin,
    kAsinh,
    kAcosh,
    kTan,
    kTanh,
    kAtan,
    kAtanh,
  };
Constructor & Destructor Documentation
FloatUnaryOp()
v8::internal::compiler::turboshaft::FloatUnaryOp::FloatUnaryOp (V< Float > input, Kind kind, FloatRepresentation rep) [inline], [explicit]
Definition at line 1992 of file operations.h.
      : Base(input), kind(kind), rep(rep) {}
Member Function Documentation
input()
V<Float> v8::internal::compiler::turboshaft::FloatUnaryOp::input () const [inline]
Definition at line 1988 of file operations.h.
{ return Base::input<Float>(0); }
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::FloatUnaryOp::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 1983 of file operations.h.
                                                              {
    return InputsRepFactory::SingleRep(rep);
  }
References v8::internal::compiler::turboshaft::InputsRepFactory::SingleRep().
IsSupported()
bool v8::internal::compiler::turboshaft::FloatUnaryOp::IsSupported (Kind kind, FloatRepresentation rep) [static]
Definition at line 274 of file operations.cc.
                                                                 {
  switch (rep.value()) {
    case FloatRepresentation::Float32():
      switch (kind) {
        case Kind::kRoundDown:
          return SupportedOperations::float32_round_down();
        case Kind::kRoundUp:
          return SupportedOperations::float32_round_up();
        case Kind::kRoundToZero:
          return SupportedOperations::float32_round_to_zero();
        case Kind::kRoundTiesEven:
          return SupportedOperations::float32_round_ties_even();
        default:
          return true;
      }
    case FloatRepresentation::Float64():
      switch (kind) {
        case Kind::kRoundDown:
          return SupportedOperations::float64_round_down();
        case Kind::kRoundUp:
          return SupportedOperations::float64_round_up();
        case Kind::kRoundToZero:
          return SupportedOperations::float64_round_to_zero();
        case Kind::kRoundTiesEven:
          return SupportedOperations::float64_round_ties_even();
        default:
          return true;
      }
  }
}
References v8::internal::compiler::turboshaft::FloatRepresentation::Float32(), v8::internal::compiler::turboshaft::FloatRepresentation::Float64(), kind, kRoundDown, kRoundTiesEven, kRoundToZero, kRoundUp, rep, and v8::internal::compiler::turboshaft::FloatRepresentation::value().
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::FloatBinop(), and v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::FloatUnary().
options()
auto v8::internal::compiler::turboshaft::FloatUnaryOp::options () const [inline]
Definition at line 1995 of file operations.h.
{ return std::tuple{kind, rep}; }
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::FloatUnaryOp::outputs_rep () const [inline]
Definition at line 1979 of file operations.h.
                                                               {
    return base::VectorOf(static_cast<const RegisterRepresentation*>(&rep), 1);
  }
References v8::base::VectorOf().
Member Data Documentation
effects
constexpr OpEffects v8::internal::compiler::turboshaft::FloatUnaryOp::effects = OpEffects() [static], [constexpr]
Definition at line 1978 of file operations.h.
kind
Kind v8::internal::compiler::turboshaft::FloatUnaryOp::kind
Definition at line 1975 of file operations.h.
Referenced by IsSupported().
rep
FloatRepresentation v8::internal::compiler::turboshaft::FloatUnaryOp::rep
Definition at line 1976 of file operations.h.
Referenced by IsSupported().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h
/mnt/V8SourceCode/src/compiler/turboshaft/operations.cc