v8::internal::anonymous_namespace{debug-wasm-objects.cc}::GlobalsProxy Struct Reference
Static Public Member Functions
static uint32_t Count (Isolate *isolate, DirectHandle< WasmInstanceObject > instance)
static DirectHandle< Object > Get (Isolate *isolate, DirectHandle< WasmInstanceObject > instance, uint32_t index)
static DirectHandle< String > GetName (Isolate *isolate, DirectHandle< WasmInstanceObject > instance, uint32_t index)
Static Public Attributes
static constexpr char const * kClassName = `Globals`
Additional Inherited Members
Detailed Description
Definition at line 328 of file debug-wasm-objects.cc.
Member Function Documentation
Count()
static uint32_t v8::internal::anonymous_namespace{debug-wasm-objects.cc}::GlobalsProxy::Count (Isolate * isolate, DirectHandle< WasmInstanceObject > instance) [inline], [static]
Definition at line 331 of file debug-wasm-objects.cc.
                                                                   {
    return static_cast<uint32_t>(instance->module()->globals.size());
  }
Get()
static DirectHandle<Object> v8::internal::anonymous_namespace{debug-wasm-objects.cc}::GlobalsProxy::Get (Isolate * isolate, DirectHandle< WasmInstanceObject > instance, uint32_t index) [inline], [static]
Definition at line 336 of file debug-wasm-objects.cc.
                                                  {
    return WasmValueObject::New(
        isolate, instance->trusted_data(isolate)->GetGlobalValue(
                     isolate, instance->module()->globals[index]));
  }
References v8::internal::index, and v8::internal::WasmValueObject::New().
GetName()
static DirectHandle<String> v8::internal::anonymous_namespace{debug-wasm-objects.cc}::GlobalsProxy::GetName (Isolate * isolate, DirectHandle< WasmInstanceObject > instance, uint32_t index) [inline], [static]
Definition at line 344 of file debug-wasm-objects.cc.
                                                      {
    wasm::NamesProvider* names =
        instance->module_object()->native_module()->GetNamesProvider();
    StringBuilder sb;
    names->PrintGlobalName(sb, index);
    return ToInternalString(sb, isolate);
  }
References v8::internal::index, v8::internal::wasm::NamesProvider::PrintGlobalName(), and v8::internal::anonymous_namespace{debug-wasm-objects.cc}::ToInternalString().
Member Data Documentation
kClassName
constexpr char const* v8::internal::anonymous_namespace{debug-wasm-objects.cc}::GlobalsProxy::kClassName = `Globals` [static], [constexpr]
Definition at line 329 of file debug-wasm-objects.cc.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/debug/debug-wasm-objects.cc