v8::internal::compiler::turboshaft::wle::OffsetListTraits Struct Reference
#include <wasm-load-elimination-reducer.h>
Public Types
using T = SnapshotTable< OpIndex, KeyData >::Key
Static Public Member Functions
static T ** prev (T t)
static T * next (T t)
static bool non_empty (T t)
Detailed Description
Definition at line 81 of file wasm-load-elimination-reducer.h.
Member Typedef Documentation
T
using v8::internal::compiler::turboshaft::wle::OffsetListTraits::T = SnapshotTable<OpIndex, KeyData>::Key
Definition at line 82 of file wasm-load-elimination-reducer.h.
Member Function Documentation
next()
static T* v8::internal::compiler::turboshaft::wle::OffsetListTraits::next (T t) [inline], [static]
Definition at line 84 of file wasm-load-elimination-reducer.h.
{ return &(t.data().next_same_offset); }
References v8::internal::compiler::turboshaft::SnapshotTableKey< Value, KeyData >::data(), and v8::internal::compiler::turboshaft::KeyData::next_same_offset.
non_empty()
static bool v8::internal::compiler::turboshaft::wle::OffsetListTraits::non_empty (T t) [inline], [static]
Definition at line 85 of file wasm-load-elimination-reducer.h.
{ return t.valid(); }
References v8::internal::compiler::turboshaft::SnapshotTableKey< Value, KeyData >::valid().
prev()
static T** v8::internal::compiler::turboshaft::wle::OffsetListTraits::prev (T t) [inline], [static]
Definition at line 83 of file wasm-load-elimination-reducer.h.
{ return &(t.data().prev_same_offset); }
References v8::internal::compiler::turboshaft::SnapshotTableKey< Value, KeyData >::data(), and v8::internal::compiler::turboshaft::KeyData::prev_same_offset.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/wasm-load-elimination-reducer.h