v8::base::AsAtomicImpl< TAtomicStorageType >::cast_helper< U > Struct Template Reference
Static Public Member Functions
static AtomicStorageType to_storage_type (U value)
static U to_return_type (AtomicStorageType value)
Detailed Description
template<typename TAtomicStorageType>
template<typename U>
struct v8::base::AsAtomicImpl< TAtomicStorageType >::cast_helper< U >
Definition at line 192 of file atomic-utils.h.
Member Function Documentation
to_return_type()
template<typename TAtomicStorageType >
template<typename U >
static U v8::base::AsAtomicImpl< TAtomicStorageType >::cast_helper< U >::to_return_type (AtomicStorageType value) [inline], [static]
Definition at line 196 of file atomic-utils.h.
                                                     {
      return static_cast<U>(value);
    }
References v8::base::internal::U, and v8::internal::value.
Referenced by v8::base::AsAtomicImpl< TAtomicStorageType >::Acquire_Load(), v8::base::AsAtomicImpl< TAtomicStorageType >::AcquireRelease_CompareAndSwap(), v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_CompareAndSwap(), v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_Load(), v8::base::AsAtomicImpl< TAtomicStorageType >::Release_CompareAndSwap(), v8::base::AsAtomicImpl< TAtomicStorageType >::SeqCst_CompareAndSwap(), and v8::base::AsAtomicImpl< TAtomicStorageType >::SeqCst_Load().
to_storage_type()
template<typename TAtomicStorageType >
template<typename U >
static AtomicStorageType v8::base::AsAtomicImpl< TAtomicStorageType >::cast_helper< U >::to_storage_type (U value) [inline], [static]
Definition at line 193 of file atomic-utils.h.
                                                      {
      return static_cast<AtomicStorageType>(value);
    }
References v8::internal::value.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/base/atomic-utils.h