v8::internal::SharedMacroAssemblerBase::AvxHelper< Dst, Arg, Args > Struct Template Reference
#include <macro-assembler-shared-ia32-x64.h>
Public Member Functions
template<void(Assembler::*)(Dst, Dst, Arg, Args...) avx, void(Assembler::*)(Dst, Arg, Args...) no_avx>
void emit (Dst dst, Arg arg, Args... args)
template<void(Assembler::*)(Dst, Arg, Args...) avx, void(Assembler::*)(Dst, Args...) no_avx>
void emit (Dst dst, Arg arg, Args... args)
template<void(Assembler::*)(Dst, Arg, Args...) avx, void(Assembler::*)(Dst, Arg, Args...) no_avx>
void emit (Dst dst, Arg arg, Args... args)
Public Attributes
Assembler * assm
std::optional< CpuFeature > feature = std::nullopt
Detailed Description
template<typename Dst, typename Arg, typename... Args>
struct v8::internal::SharedMacroAssemblerBase::AvxHelper< Dst, Arg, Args >
Definition at line 174 of file macro-assembler-shared-ia32-x64.h.
Member Function Documentation
emit() [1/3]
template<typename Dst , typename Arg , typename... Args>
template<void(Assembler::*)(Dst, Dst, Arg, Args...) avx, void(Assembler::*)(Dst, Arg, Args...) no_avx>
void v8::internal::SharedMacroAssemblerBase::AvxHelper< Dst, Arg, Args >::emit (Dst dst, Arg arg, Args... args) [inline]
Definition at line 183 of file macro-assembler-shared-ia32-x64.h.
                                              {
      if (CpuFeatures::IsSupported(AVX)) {
        CpuFeatureScope scope(assm, AVX);
        (assm->*avx)(dst, dst, arg, args...);
      } else if (feature.has_value()) {
        DCHECK(CpuFeatures::IsSupported(*feature));
        CpuFeatureScope scope(assm, *feature);
        (assm->*no_avx)(dst, arg, args...);
      } else {
        (assm->*no_avx)(dst, arg, args...);
      }
    }
References v8::base::args, v8::internal::DCHECK(), and v8::internal::CpuFeatures::IsSupported().
emit() [2/3]
template<typename Dst , typename Arg , typename... Args>
template<void(Assembler::*)(Dst, Arg, Args...) avx, void(Assembler::*)(Dst, Args...) no_avx>
void v8::internal::SharedMacroAssemblerBase::AvxHelper< Dst, Arg, Args >::emit (Dst dst, Arg arg, Args... args) [inline]
Definition at line 202 of file macro-assembler-shared-ia32-x64.h.
                                              {
      if (CpuFeatures::IsSupported(AVX)) {
        CpuFeatureScope scope(assm, AVX);
        (assm->*avx)(dst, arg, args...);
      } else if (feature.has_value()) {
        DCHECK_EQ(dst, arg);
        DCHECK(CpuFeatures::IsSupported(*feature));
        CpuFeatureScope scope(assm, *feature);
        (assm->*no_avx)(dst, args...);
      } else {
        DCHECK_EQ(dst, arg);
        (assm->*no_avx)(dst, args...);
      }
    }
References v8::base::args, v8::internal::DCHECK(), DCHECK_EQ, and v8::internal::CpuFeatures::IsSupported().
emit() [3/3]
template<typename Dst , typename Arg , typename... Args>
template<void(Assembler::*)(Dst, Arg, Args...) avx, void(Assembler::*)(Dst, Arg, Args...) no_avx>
void v8::internal::SharedMacroAssemblerBase::AvxHelper< Dst, Arg, Args >::emit (Dst dst, Arg arg, Args... args) [inline]
Definition at line 222 of file macro-assembler-shared-ia32-x64.h.
                                              {
      if (CpuFeatures::IsSupported(AVX)) {
        CpuFeatureScope scope(assm, AVX);
        (assm->*avx)(dst, arg, args...);
      } else if (feature.has_value()) {
        DCHECK(CpuFeatures::IsSupported(*feature));
        CpuFeatureScope scope(assm, *feature);
        (assm->*no_avx)(dst, arg, args...);
      } else {
        (assm->*no_avx)(dst, arg, args...);
      }
    }
References v8::base::args, v8::internal::DCHECK(), and v8::internal::CpuFeatures::IsSupported().
Member Data Documentation
assm
template<typename Dst , typename Arg , typename... Args>
Assembler* v8::internal::SharedMacroAssemblerBase::AvxHelper< Dst, Arg, Args >::assm
Definition at line 175 of file macro-assembler-shared-ia32-x64.h.
feature
template<typename Dst , typename Arg , typename... Args>
std::optional<CpuFeature> v8::internal::SharedMacroAssemblerBase::AvxHelper< Dst, Arg, Args >::feature = std::nullopt
Definition at line 176 of file macro-assembler-shared-ia32-x64.h.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/codegen/shared-ia32-x64/macro-assembler-shared-ia32-x64.h