v8::internal::ThreadIsolation::StlAllocator< T > Struct Template Reference
#include <code-memory-access.h>
Public Types
typedef T value_type
Public Member Functions
StlAllocator ()=default
template<class U >
StlAllocator (const StlAllocator< U > &) noexcept
value_type * allocate (size_t n)
void deallocate (value_type *ptr, size_t n)
Detailed Description
template<class T>
struct v8::internal::ThreadIsolation::StlAllocator< T >
Definition at line 222 of file code-memory-access.h.
Member Typedef Documentation
value_type
template<class T >
typedef T v8::internal::ThreadIsolation::StlAllocator< T >::value_type
Definition at line 223 of file code-memory-access.h.
Constructor & Destructor Documentation
StlAllocator() [1/2]
template<class T >
v8::internal::ThreadIsolation::StlAllocator< T >::StlAllocator () [default]
StlAllocator() [2/2]
template<class T >
template<class U >
v8::internal::ThreadIsolation::StlAllocator< T >::StlAllocator (const StlAllocator< U > &) [inline], [explicit], [noexcept]
Definition at line 227 of file code-memory-access.h.
{}
Member Function Documentation
allocate()
template<class T >
value_type* v8::internal::ThreadIsolation::StlAllocator< T >::allocate (size_t n) [inline]
Definition at line 229 of file code-memory-access.h.
                                   {
      if (Enabled()) {
        return static_cast<value_type*>(
            ThreadIsolation::allocator()->Allocate(n * sizeof(value_type)));
      } else {
        return static_cast<value_type*>(::operator new(n * sizeof(T)));
      }
    }
References v8::ThreadIsolatedAllocator::Allocate(), v8::internal::ThreadIsolation::allocator(), and T.
deallocate()
template<class T >
void v8::internal::ThreadIsolation::StlAllocator< T >::deallocate (value_type * ptr, size_t n) [inline]
Definition at line 238 of file code-memory-access.h.
                                               {
      if (Enabled()) {
        ThreadIsolation::allocator()->Free(ptr);
      } else {
        ::operator delete(ptr);
      }
    }
References v8::internal::ThreadIsolation::allocator(), and v8::ThreadIsolatedAllocator::Free().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/common/code-memory-access.h