v8::internal::compiler::WasmLoadElimination::FieldOrElementValue Struct Reference
Public Member Functions
FieldOrElementValue ()=default
FieldOrElementValue (Node *value)
bool operator== (const FieldOrElementValue &other) const
bool operator!= (const FieldOrElementValue &other) const
bool IsEmpty () const
Public Attributes
Node * value = nullptr
Detailed Description
Definition at line 36 of file wasm-load-elimination.h.
Constructor & Destructor Documentation
FieldOrElementValue() [1/2]
v8::internal::compiler::WasmLoadElimination::FieldOrElementValue::FieldOrElementValue () [default]
FieldOrElementValue() [2/2]
v8::internal::compiler::WasmLoadElimination::FieldOrElementValue::FieldOrElementValue (Node * value) [inline], [explicit]
Definition at line 38 of file wasm-load-elimination.h.
: value(value) {}
Member Function Documentation
IsEmpty()
bool v8::internal::compiler::WasmLoadElimination::FieldOrElementValue::IsEmpty () const [inline]
Definition at line 48 of file wasm-load-elimination.h.
{ return value == nullptr; }
References v8::internal::value.
Referenced by v8::internal::compiler::WasmLoadElimination::ReduceLoadLikeFromImmutable(), v8::internal::compiler::WasmLoadElimination::ReduceStringPrepareForGetCodeunit(), v8::internal::compiler::WasmLoadElimination::ReduceWasmArrayInitializeLength(), v8::internal::compiler::WasmLoadElimination::ReduceWasmStructGet(), and v8::internal::compiler::WasmLoadElimination::ReduceWasmStructSet().
operator!=()
bool v8::internal::compiler::WasmLoadElimination::FieldOrElementValue::operator!= (const FieldOrElementValue & other) const [inline]
Definition at line 44 of file wasm-load-elimination.h.
                                                            {
      return !(*this == other);
    }
operator==()
bool v8::internal::compiler::WasmLoadElimination::FieldOrElementValue::operator== (const FieldOrElementValue & other) const [inline]
Definition at line 40 of file wasm-load-elimination.h.
                                                            {
      return value == other.value;
    }
References value, and v8::internal::value.
Member Data Documentation
value
Node* v8::internal::compiler::WasmLoadElimination::FieldOrElementValue::value = nullptr
Definition at line 50 of file wasm-load-elimination.h.
Referenced by operator==(), v8::internal::compiler::WasmLoadElimination::ReduceLoadLikeFromImmutable(), v8::internal::compiler::WasmLoadElimination::ReduceStringPrepareForGetCodeunit(), and v8::internal::compiler::WasmLoadElimination::ReduceWasmStructGet().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/wasm-load-elimination.h