cppgc::internal::WeakPersistentPolicy Struct Reference
#include <pointer-policies.h>
Public Types
using IsStrongPersistent = std::false_type
Static Public Member Functions
static PersistentRegion & GetPersistentRegion (const void *object)
Detailed Description
Definition at line 245 of file pointer-policies.h.
Member Typedef Documentation
IsStrongPersistent
using cppgc::internal::WeakPersistentPolicy::IsStrongPersistent = std::false_type
Definition at line 246 of file pointer-policies.h.
Member Function Documentation
GetPersistentRegion()
PersistentRegion & cppgc::internal::WeakPersistentPolicy::GetPersistentRegion (const void * object) [static]
Definition at line 114 of file pointer-policies.cc.
                        {
  return BasePage::FromPayload(object)->heap().GetWeakPersistentRegion();
}
References cppgc::internal::BasePage::FromPayload(), cppgc::internal::HeapBase::GetWeakPersistentRegion(), and cppgc::internal::BasePage::heap().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/include/cppgc/internal/pointer-policies.h
/mnt/V8SourceCode/src/heap/cppgc/pointer-policies.cc