v8::internal::compiler::turboshaft::PhiOp Struct Reference
#include <operations.h>
Public Member Functions
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
PhiOp (base::Vector< const OpIndex > inputs, RegisterRepresentation rep)
template<typename Fn , typename Mapper >
auto Explode (Fn fn, Mapper &mapper) const
void Validate (const Graph &graph) const
auto options () const
Public Attributes
RegisterRepresentation rep
Static Public Attributes
static constexpr OpEffects effects = OpEffects()
static constexpr size_t kLoopPhiBackEdgeIndex = 1
Additional Inherited Members
Detailed Description
Definition at line 2539 of file operations.h.
Constructor & Destructor Documentation
PhiOp()
v8::internal::compiler::turboshaft::PhiOp::PhiOp (base::Vector< const OpIndex > inputs, RegisterRepresentation rep) [inline], [explicit]
Definition at line 2561 of file operations.h.
      : Base(inputs), rep(rep) {}
Member Function Documentation
Explode()
template<typename Fn , typename Mapper >
auto v8::internal::compiler::turboshaft::PhiOp::Explode (Fn fn, Mapper & mapper) const [inline]
Definition at line 2565 of file operations.h.
                                                      {
    auto mapped_inputs = mapper.template Map<64>(inputs());
    return fn(base::VectorOf(mapped_inputs), rep);
  }
References v8::base::VectorOf().
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::PhiOp::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 2550 of file operations.h.
                                                              {
    storage.resize(input_count);
    for (size_t i = 0; i < input_count; ++i) {
      storage[i] = rep;
    }
    return base::VectorOf(storage);
  }
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::ZoneVector< T >::resize(), and v8::base::VectorOf().
options()
auto v8::internal::compiler::turboshaft::PhiOp::options () const [inline]
Definition at line 2571 of file operations.h.
{ return std::tuple{rep}; }
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::PhiOp::outputs_rep () const [inline]
Definition at line 2546 of file operations.h.
                                                               {
    return base::VectorOf(&rep, 1);
  }
References v8::base::VectorOf().
Validate()
void v8::internal::compiler::turboshaft::PhiOp::Validate (const Graph & graph) const [inline]
Definition at line 2570 of file operations.h.
{ DCHECK_GT(input_count, 0); }
References DCHECK_GT, and v8::internal::compiler::turboshaft::detail::input_count().
Member Data Documentation
effects
constexpr OpEffects v8::internal::compiler::turboshaft::PhiOp::effects = OpEffects() [static], [constexpr]
Definition at line 2545 of file operations.h.
kLoopPhiBackEdgeIndex
constexpr size_t v8::internal::compiler::turboshaft::PhiOp::kLoopPhiBackEdgeIndex = 1 [static], [constexpr]
Definition at line 2559 of file operations.h.
Referenced by v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::Phi(), v8::internal::compiler::turboshaft::DeadCodeAnalysis::ProcessBlock(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::ResolvePhi(), and v8::internal::compiler::turboshaft::UseMap::UseMap().
rep
RegisterRepresentation v8::internal::compiler::turboshaft::PhiOp::rep
Definition at line 2540 of file operations.h.
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphPhi(), v8::internal::compiler::turboshaft::SLPTree::BuildTreeRec(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ComputeTypeForPhi(), v8::internal::compiler::turboshaft::GenericReducerBase< Next >::FixLoopPhi(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::FixLoopPhi(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::FixLoopPhi(), v8::internal::compiler::turboshaft::RunDecompressionOptimization(), and v8::internal::compiler::InstructionSelector::VisitNode().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h