v8::internal::wasm::SigIndexImmediate Struct Reference
#include <function-body-decoder-impl.h>
Public Member Functions
template<typename ValidationTag >
SigIndexImmediate (Decoder *decoder, const uint8_t *pc, ValidationTag validate={})
HeapType heap_type () const
Public Attributes
const FunctionSig * sig = nullptr
bool shared = false
Detailed Description
Definition at line 675 of file function-body-decoder-impl.h.
Constructor & Destructor Documentation
SigIndexImmediate()
template<typename ValidationTag >
v8::internal::wasm::SigIndexImmediate::SigIndexImmediate (Decoder * decoder, const uint8_t * pc, ValidationTag validate = {}) [inline]
Definition at line 680 of file function-body-decoder-impl.h.
                                             {})
      : TypeIndexImmediate(decoder, pc, "signature index", validate) {}
Member Function Documentation
heap_type()
HeapType v8::internal::wasm::SigIndexImmediate::heap_type () const [inline]
Definition at line 684 of file function-body-decoder-impl.h.
                             {
    return HeapType::Index(index, shared, RefTypeKind::kFunction);
  }
References v8::internal::wasm::TypeIndexImmediate::index, v8::internal::wasm::HeapType::Index(), v8::internal::wasm::kFunction, and shared.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildIndirectCallTargetAndImplicitArg(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallIndirectImpl(), and v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE().
Member Data Documentation
shared
bool v8::internal::wasm::SigIndexImmediate::shared = false
Definition at line 677 of file function-body-decoder-impl.h.
Referenced by heap_type(), and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate().
sig
const FunctionSig* v8::internal::wasm::SigIndexImmediate::sig = nullptr
Definition at line 676 of file function-body-decoder-impl.h.
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE(), and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/wasm/function-body-decoder-impl.h