v8::internal::torque::ls::JsonValue Struct Reference
#include <json.h>
Public Types
enum {
OBJECT
, ARRAY
, STRING
, NUMBER
,
BOOL
, IS_NULL
 }
Public Member Functions
JsonValue () V8_NOEXCEPT=default
constexpr JsonValue (const JsonValue &other)=delete
JsonValue & operator= (const JsonValue &other)=delete
JsonValue (JsonValue &&other) V8_NOEXCEPT=default
JsonValue & operator= (JsonValue &&other) V8_NOEXCEPT=default
bool IsNumber () const
double ToNumber () const
bool IsBool () const
bool ToBool () const
bool IsString () const
const std::string & ToString () const
bool IsObject () const
const JsonObject & ToObject () const
JsonObject & ToObject ()
bool IsArray () const
const JsonArray & ToArray () const
JsonArray & ToArray ()
Static Public Member Functions
static JsonValue From (double number)
static JsonValue From (JsonObject object)
static JsonValue From (bool b)
static JsonValue From (const std::string &string)
static JsonValue From (JsonArray array)
static JsonValue JsonNull ()
Public Attributes
enum v8::internal::torque::ls::JsonValue:: { ... } tag
Private Attributes
double number_ = 0
bool flag_ = false
std::string string_
std::unique_ptr< JsonObject > object_
std::unique_ptr< JsonArray > array_
Detailed Description
Definition at line 25 of file json.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
OBJECT
ARRAY
STRING
NUMBER
BOOL
IS_NULL
Definition at line 27 of file json.h.
{ OBJECT, ARRAY, STRING, NUMBER, BOOL, IS_NULL } tag;
Constructor & Destructor Documentation
JsonValue() [1/3]
v8::internal::torque::ls::JsonValue::JsonValue () [default]
JsonValue() [2/3]
constexpr v8::internal::torque::ls::JsonValue::JsonValue (const JsonValue & other) [constexpr], [delete]
JsonValue() [3/3]
v8::internal::torque::ls::JsonValue::JsonValue (JsonValue && other) [default]
Member Function Documentation
From() [1/5]
static JsonValue v8::internal::torque::ls::JsonValue::From (bool b) [inline], [static]
Definition at line 51 of file json.h.
                                {
    JsonValue result;
    result.tag = JsonValue::BOOL;
    result.flag_ = b;
    return result;
  }
References BOOL, and v8::base::internal::result.
From() [2/5]
static JsonValue v8::internal::torque::ls::JsonValue::From (const std::string & string) [inline], [static]
Definition at line 58 of file json.h.
                                                 {
    JsonValue result;
    result.tag = JsonValue::STRING;
    result.string_ = string;
    return result;
  }
References v8::base::internal::result, v8::internal::string, and STRING.
From() [3/5]
static JsonValue v8::internal::torque::ls::JsonValue::From (double number) [inline], [static]
Definition at line 37 of file json.h.
                                       {
    JsonValue result;
    result.tag = JsonValue::NUMBER;
    result.number_ = number;
    return result;
  }
References NUMBER, and v8::base::internal::result.
Referenced by v8::internal::torque::ls::BaseJsonAccessor::AddObjectElementToArrayProperty(), v8::internal::torque::ls::BaseJsonAccessor::GetArrayProperty(), v8::internal::torque::ls::BaseJsonAccessor::GetObjectProperty(), v8::internal::torque::ls::MakeArray(), v8::internal::torque::ls::MakeBoolLiteral(), v8::internal::torque::ls::MakeNumberLiteral(), v8::internal::torque::ls::MakeObject(), v8::internal::torque::ls::MakeStringLiteral(), and v8::internal::torque::ls::Message::Message().
From() [4/5]
static JsonValue v8::internal::torque::ls::JsonValue::From (JsonArray array) [inline], [static]
Definition at line 65 of file json.h.
                                         {
    JsonValue result;
    result.tag = JsonValue::ARRAY;
    result.array_ = std::make_unique<JsonArray>(std::move(array));
    return result;
  }
References ARRAY, and v8::base::internal::result.
From() [5/5]
static JsonValue v8::internal::torque::ls::JsonValue::From (JsonObject object) [inline], [static]
Definition at line 44 of file json.h.
                                           {
    JsonValue result;
    result.tag = JsonValue::OBJECT;
    result.object_ = std::make_unique<JsonObject>(std::move(object));
    return result;
  }
References OBJECT, and v8::base::internal::result.
IsArray()
bool v8::internal::torque::ls::JsonValue::IsArray () const [inline]
Definition at line 106 of file json.h.
{ return array_ && tag == ARRAY; }
References ARRAY, array_, and tag.
Referenced by ToArray().
IsBool()
bool v8::internal::torque::ls::JsonValue::IsBool () const [inline]
Definition at line 84 of file json.h.
{ return tag == BOOL; }
References BOOL, and tag.
Referenced by ToBool().
IsNumber()
bool v8::internal::torque::ls::JsonValue::IsNumber () const [inline]
Definition at line 78 of file json.h.
{ return tag == NUMBER; }
References NUMBER, and tag.
Referenced by ToNumber().
IsObject()
bool v8::internal::torque::ls::JsonValue::IsObject () const [inline]
Definition at line 96 of file json.h.
{ return object_ && tag == OBJECT; }
References OBJECT, object_, and tag.
Referenced by ToObject().
IsString()
bool v8::internal::torque::ls::JsonValue::IsString () const [inline]
Definition at line 90 of file json.h.
{ return tag == STRING; }
References STRING, and tag.
Referenced by ToString().
JsonNull()
static JsonValue v8::internal::torque::ls::JsonValue::JsonNull () [inline], [static]
Definition at line 72 of file json.h.
                              {
    JsonValue result;
    result.tag = JsonValue::IS_NULL;
    return result;
  }
References IS_NULL, and v8::base::internal::result.
Referenced by v8::internal::torque::ls::BaseJsonAccessor::SetNull().
operator=() [1/2]
JsonValue& v8::internal::torque::ls::JsonValue::operator= (const JsonValue & other) [delete]
operator=() [2/2]
JsonValue& v8::internal::torque::ls::JsonValue::operator= (JsonValue && other) [default]
ToArray() [1/2]
JsonArray& v8::internal::torque::ls::JsonValue::ToArray () [inline]
Definition at line 111 of file json.h.
                       {
    CHECK(IsArray());
    return *array_;
  }
References array_, CHECK, and IsArray().
ToArray() [2/2]
const JsonArray& v8::internal::torque::ls::JsonValue::ToArray () const [inline]
Definition at line 107 of file json.h.
                                   {
    CHECK(IsArray());
    return *array_;
  }
References array_, CHECK, and IsArray().
ToBool()
bool v8::internal::torque::ls::JsonValue::ToBool () const [inline]
Definition at line 85 of file json.h.
                      {
    CHECK(IsBool());
    return flag_;
  }
References CHECK, flag_, and IsBool().
ToNumber()
double v8::internal::torque::ls::JsonValue::ToNumber () const [inline]
Definition at line 79 of file json.h.
                          {
    CHECK(IsNumber());
    return number_;
  }
References CHECK, IsNumber(), and number_.
ToObject() [1/2]
JsonObject& v8::internal::torque::ls::JsonValue::ToObject () [inline]
Definition at line 101 of file json.h.
                         {
    CHECK(IsObject());
    return *object_;
  }
References CHECK, IsObject(), and object_.
ToObject() [2/2]
const JsonObject& v8::internal::torque::ls::JsonValue::ToObject () const [inline]
Definition at line 97 of file json.h.
                                     {
    CHECK(IsObject());
    return *object_;
  }
References CHECK, IsObject(), and object_.
Referenced by v8::internal::torque::ls::Message::object().
ToString()
const std::string& v8::internal::torque::ls::JsonValue::ToString () const [inline]
Definition at line 91 of file json.h.
                                    {
    CHECK(IsString());
    return string_;
  }
References CHECK, IsString(), and string_.
Member Data Documentation
array_
std::unique_ptr<JsonArray> v8::internal::torque::ls::JsonValue::array_ [private]
Definition at line 121 of file json.h.
Referenced by IsArray(), and ToArray().
flag_
bool v8::internal::torque::ls::JsonValue::flag_ = false [private]
Definition at line 118 of file json.h.
Referenced by ToBool().
number_
double v8::internal::torque::ls::JsonValue::number_ = 0 [private]
Definition at line 117 of file json.h.
Referenced by ToNumber().
object_
std::unique_ptr<JsonObject> v8::internal::torque::ls::JsonValue::object_ [private]
Definition at line 120 of file json.h.
Referenced by IsObject(), and ToObject().
string_
std::string v8::internal::torque::ls::JsonValue::string_ [private]
Definition at line 119 of file json.h.
Referenced by ToString().
enum { ... } v8::internal::torque::ls::JsonValue::tag
Referenced by IsArray(), IsBool(), IsNumber(), IsObject(), IsString(), and v8::internal::torque::ls::Message::Message().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/torque/ls/json.h