v8::internal::torque::CallBuiltinInstruction Struct Reference
#include <instructions.h>
Public Member Functions
bool IsBlockTerminator () const override
CallBuiltinInstruction (bool is_tailcall, Builtin *builtin, size_t argc, std::optional< Block * > catch_block)
void AppendSuccessorBlocks (std::vector< Block * > *block_list) const override
std::size_t GetValueDefinitionCount () const
DefinitionLocation GetValueDefinition (std::size_t index) const
std::optional< DefinitionLocation > GetExceptionObjectDefinition () const
Public Attributes
bool is_tailcall
Builtin * builtin
size_t argc
std::optional< Block * > catch_block
Detailed Description
Definition at line 554 of file instructions.h.
Constructor & Destructor Documentation
CallBuiltinInstruction()
v8::internal::torque::CallBuiltinInstruction::CallBuiltinInstruction (bool is_tailcall, Builtin * builtin, size_t argc, std::optional< Block * > catch_block) [inline]
Definition at line 557 of file instructions.h.
      : is_tailcall(is_tailcall),
        builtin(builtin),
        argc(argc),
        catch_block(catch_block) {}
Member Function Documentation
AppendSuccessorBlocks()
void v8::internal::torque::CallBuiltinInstruction::AppendSuccessorBlocks (std::vector< Block * > * block_list) const [inline], [override], [virtual]
Reimplemented from v8::internal::torque::InstructionBase.
Definition at line 563 of file instructions.h.
                                                                           {
    if (catch_block) block_list->push_back(*catch_block);
  }
References catch_block.
GetExceptionObjectDefinition()
std::optional< DefinitionLocation > v8::internal::torque::CallBuiltinInstruction::GetExceptionObjectDefinition () const
Definition at line 466 of file instructions.cc.
                                                           {
  if (!catch_block) return std::nullopt;
  return DefinitionLocation::Instruction(this, GetValueDefinitionCount());
}
References catch_block, GetValueDefinitionCount(), and v8::internal::torque::DefinitionLocation::Instruction().
GetValueDefinition()
DefinitionLocation v8::internal::torque::CallBuiltinInstruction::GetValueDefinition (std::size_t index) const
Definition at line 459 of file instructions.cc.
                           {
  DCHECK_LT(index, GetValueDefinitionCount());
  return DefinitionLocation::Instruction(this, index);
}
References DCHECK_LT, GetValueDefinitionCount(), v8::internal::index, and v8::internal::torque::DefinitionLocation::Instruction().
GetValueDefinitionCount()
std::size_t v8::internal::torque::CallBuiltinInstruction::GetValueDefinitionCount () const
Definition at line 455 of file instructions.cc.
                                                                {
  return LowerType(builtin->signature().return_type).size();
}
References builtin, v8::internal::torque::LowerType(), v8::internal::torque::Signature::return_type, and v8::internal::torque::Callable::signature().
Referenced by GetExceptionObjectDefinition(), and GetValueDefinition().
IsBlockTerminator()
bool v8::internal::torque::CallBuiltinInstruction::IsBlockTerminator () const [inline], [override], [virtual]
Reimplemented from v8::internal::torque::InstructionBase.
Definition at line 556 of file instructions.h.
{ return is_tailcall; }
References is_tailcall.
Member Data Documentation
argc
size_t v8::internal::torque::CallBuiltinInstruction::argc
Definition at line 573 of file instructions.h.
Referenced by v8::internal::torque::operator<<().
builtin
Builtin* v8::internal::torque::CallBuiltinInstruction::builtin
Definition at line 572 of file instructions.h.
Referenced by GetValueDefinitionCount(), and v8::internal::torque::operator<<().
catch_block
std::optional<Block*> v8::internal::torque::CallBuiltinInstruction::catch_block
Definition at line 574 of file instructions.h.
Referenced by AppendSuccessorBlocks(), GetExceptionObjectDefinition(), and v8::internal::torque::operator<<().
is_tailcall
bool v8::internal::torque::CallBuiltinInstruction::is_tailcall
Definition at line 571 of file instructions.h.
Referenced by IsBlockTerminator(), and v8::internal::torque::operator<<().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/torque/instructions.h
/mnt/V8SourceCode/src/torque/instructions.cc