v8::internal::compiler::turboshaft::OperationT< Derived > Struct Template Reference
#include <operations.h>
Inherits v8::internal::compiler::turboshaft::Operation.
Inherited by v8::internal::compiler::turboshaft::FixedArityOperationT< 1, WordUnaryOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 3, WordBinopDeoptOnOverflowOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 1, SwitchOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 1, StackPointerGreaterThanOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 3, NewConsStringOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 0, GotoOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 1, DoubleArrayMinMaxOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 1, DeoptimizeOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 1, TaggedBitcastOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 5, StoreDataViewElementOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 0, RuntimeAbortOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 1, RetainOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 1, OverflowCheckedUnaryOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 1, ObjectIsNumericValueOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 3, GenericUnopOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 1, TransitionElementsKindOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 1, ProjectionOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 1, NewArrayOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 2, CheckedClosureOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 2, StringComparisonOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 5, StoreTypedElementOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 1, NewArgumentsElementsOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 0, MemoryBarrierOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 1, ConvertUntaggedToJSPrimitiveOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 1, CheckExceptionOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 1, BigIntUnaryOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 3, StringSubstringOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 0, ParameterOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 0, OsrValueOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 1, ObjectIsOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 4, LoadTypedElementOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 2, Float64SameValueOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 3, CheckEqualsInternalizedStringOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 1, Word32SignHintOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 0, UnreachableOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 1, TypedArrayLengthOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 3, TransitionElementsKindOrCheckMapOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 3, StringConcatOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 5, MaybeGrowFastElementsOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 1, TruncateJSPrimitiveToUntaggedOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 0, LoadRootRegisterOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 2, DeoptimizeIfOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 1, DebugPrintOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 1, ConvertOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 1, AbortCSADcheckOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 3, TransitionAndStoreArrayElementOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 2, SameValueOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 2, LoadStackArgumentOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 4, LoadDataViewElementOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 0, StackSlotOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 2, FloatBinopOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 1, DecodeExternalPointerOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 2, ComparisonOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 1, StringLengthOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 1, StaticAssertOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 2, ShiftOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 2, LoadFieldByIndexOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 0, FrameConstantOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 2, ConvertJSPrimitiveToUntaggedOrDeoptOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 1, ConvertJSPrimitiveToUntaggedOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 1, CheckTurboshaftTypeOfOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 0, CatchBlockBeginOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 1, BranchOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 3, BigIntBinopOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 4, Word32PairBinopOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 3, SelectOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 2, BigIntComparisonOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 1, AssumeMapOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 1, Float64IsOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 2, EnsureWritableFastElementsOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 2, ConvertUntaggedToJSPrimitiveOrDeoptOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 0, ConstantOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 1, AllocateOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 2, OverflowCheckedBinopOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 2, ChangeOrDeoptOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 2, WordBinopOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 1, TryChangeOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 2, TruncateJSPrimitiveToUntaggedOrDeoptOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 2, StringOrOddballStrictEqualOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 2, StoreMessageOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 2, FindOrderedHashEntryOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 0, DeadOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 3, ConvertJSPrimitiveToObjectOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 0, CommentOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 2, BitcastWord32PairToFloat64Op >, v8::internal::compiler::turboshaft::FixedArityOperationT< 2, StringFromCodePointAtOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 1, LoadMessageOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 4, GenericBinopOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 1, DidntThrowOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 0, DebugBreakOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 0, ArgumentsLengthOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 3, ToNumberOrNumericOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 3, StringIndexOfOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 2, StringAtOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 1, PendingLoopPhiOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 1, FloatUnaryOp >, v8::internal::compiler::turboshaft::FixedArityOperationT< 1, ChangeOp >, and v8::internal::compiler::turboshaft::FixedArityOperationT< InputCount, Derived >.
Public Types
using Base = OperationT
Public Member Functions
bool IsRequiredWhenUnused () const
Derived & derived_this ()
const Derived & derived_this () const
base::Vector< OpIndex > inputs ()
base::Vector< const OpIndex > inputs () const
OpIndex & input (size_t i)
V< Any > input (size_t i) const
template<typename T >
V< T > input (size_t i) const
size_t StorageSlotCount () const
OperationT (size_t input_count)
OperationT (ShadowyOpIndexVectorWrapper inputs)
bool EqualsForGVN (const Base &other) const
bool operator== (const Base &other) const
template<typename... Args>
size_t HashWithOptions (const Args &... args) const
size_t hash_value (HashingStrategy strategy=HashingStrategy::kDefault) const
void PrintInputs (std::ostream &os, const std::string &op_index_prefix) const
void PrintOptions (std::ostream &os) const
void Validate (const Graph &graph) const
Static Public Member Functions
static constexpr OpEffects Effects ()
static constexpr bool IsBlockTerminator ()
static constexpr std::optional< OpEffects > EffectsIfStatic ()
static size_t StorageSlotCount (size_t input_count)
template<class... Args>
static Derived & New (Graph *graph, size_t input_count, Args... args)
template<class... Args>
static Derived & New (Graph *graph, ShadowyOpIndexVectorWrapper inputs, Args... args)
Static Public Attributes
static const Opcode opcode = operation_to_opcode<Op>::value
Private Member Functions
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
Static Private Member Functions
template<class... T, size_t... I>
static void PrintOptionsHelper (std::ostream &os, const std::tuple< T... > &options, std::index_sequence< I... >)
Additional Inherited Members
Detailed Description
template<class Derived>
struct v8::internal::compiler::turboshaft::OperationT< Derived >
Definition at line 1071 of file operations.h.
Member Typedef Documentation
Base
template<class Derived >
using v8::internal::compiler::turboshaft::OperationT< Derived >::Base = OperationT
Definition at line 1073 of file operations.h.
Constructor & Destructor Documentation
OperationT() [1/2]
template<class Derived >
v8::internal::compiler::turboshaft::OperationT< Derived >::OperationT (size_t input_count) [inline], [explicit]
Definition at line 1165 of file operations.h.
                                          : Operation(opcode, input_count) {
    static_assert((std::is_base_of_v<OperationT, Derived>));
#if !V8_CC_MSVC
    static_assert(std::is_trivially_copyable_v<Derived>);
#endif // !V8_CC_MSVC
    static_assert(std::is_trivially_destructible_v<Derived>);
  }
OperationT() [2/2]
template<class Derived >
v8::internal::compiler::turboshaft::OperationT< Derived >::OperationT (ShadowyOpIndexVectorWrapper inputs) [inline], [explicit]
Definition at line 1172 of file operations.h.
      : OperationT(inputs.size()) {
    this->inputs().OverwriteWith(
        static_cast<base::Vector<const OpIndex>>(inputs));
  }
Member Function Documentation
derived_this() [1/2]
template<class Derived >
Derived& v8::internal::compiler::turboshaft::OperationT< Derived >::derived_this () [inline]
Definition at line 1093 of file operations.h.
{ return *static_cast<Derived*>(this); }
Referenced by v8::internal::compiler::turboshaft::OperationT< Derived >::EqualsForGVN(), and v8::internal::compiler::turboshaft::OperationT< Derived >::operator==().
derived_this() [2/2]
template<class Derived >
const Derived& v8::internal::compiler::turboshaft::OperationT< Derived >::derived_this () const [inline]
Definition at line 1094 of file operations.h.
                                      {
    return *static_cast<const Derived*>(this);
  }
Effects()
template<class Derived >
static constexpr OpEffects v8::internal::compiler::turboshaft::OperationT< Derived >::Effects () [inline], [static], [constexpr]
Definition at line 1077 of file operations.h.
{ return Derived::effects; }
EffectsIfStatic()
template<class Derived >
static constexpr std::optional<OpEffects> v8::internal::compiler::turboshaft::OperationT< Derived >::EffectsIfStatic () [inline], [static], [constexpr]
Definition at line 1086 of file operations.h.
                                                            {
    if constexpr (HasStaticEffects<Derived>::value) {
      return Derived::Effects();
    }
    return std::nullopt;
  }
EqualsForGVN()
template<class Derived >
bool v8::internal::compiler::turboshaft::OperationT< Derived >::EqualsForGVN (const Base & other) const [inline]
Definition at line 1178 of file operations.h.
                                             {
    // By default, GVN only removed identical Operations. However, some
    // Operations (like DeoptimizeIf) can be GVNed when a dominating
    // similar-but-not-identical one exists. In that case, the Operation should
    // redefine EqualsForGVN, so that GVN knows which inputs or options of the
    // Operation to ignore (you should also probably redefine hash_value,
    // otherwise GVN won't even try to call EqualsForGVN).
    return derived_this() == other.derived_this();
  }
References v8::internal::compiler::turboshaft::OperationT< Derived >::derived_this().
hash_value()
template<class Derived >
size_t v8::internal::compiler::turboshaft::OperationT< Derived >::hash_value (HashingStrategy strategy = HashingStrategy::kDefault) const [inline]
Definition at line 1195 of file operations.h.
                                                                {
    return HashWithOptions(derived_this().options());
  }
Referenced by v8::internal::compiler::turboshaft::CallOp::hash_value(), v8::internal::compiler::turboshaft::CheckExceptionOp::hash_value(), v8::internal::compiler::turboshaft::GotoOp::hash_value(), v8::internal::compiler::turboshaft::BranchOp::hash_value(), and v8::internal::compiler::turboshaft::SwitchOp::hash_value().
HashWithOptions()
template<class Derived >
template<typename... Args>
size_t v8::internal::compiler::turboshaft::OperationT< Derived >::HashWithOptions (const Args &... args) const [inline]
Definition at line 1192 of file operations.h.
                                                    {
    return fast_hash_combine(opcode, derived_this().inputs(), args...);
  }
References v8::base::args, and v8::internal::compiler::turboshaft::fast_hash_combine().
Referenced by v8::internal::compiler::turboshaft::CheckExceptionOp::hash_value(), v8::internal::compiler::turboshaft::GotoOp::hash_value(), v8::internal::compiler::turboshaft::BranchOp::hash_value(), and v8::internal::compiler::turboshaft::SwitchOp::hash_value().
input() [1/3]
template<class Derived >
OpIndex& v8::internal::compiler::turboshaft::OperationT< Derived >::input (size_t i) [inline]
Definition at line 1110 of file operations.h.
{ return derived_this().inputs()[i]; }
References v8::internal::anonymous_namespace{json-stringifier.cc}::i.
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::EmitInt32MulWithOverflow(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::EmitInt64MulWithOverflow(), v8::internal::compiler::EmitInt64MulWithOverflow(), v8::internal::compiler::turboshaft::GenericReducerBase< Next >::FixLoopPhi(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::FixLoopPhi(), v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::GetIterCountIfStaticCanonicalForLoop(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::GetTypeForPhiInput(), v8::internal::compiler::turboshaft::anonymous_namespace{decompression-optimization.cc}::DecompressionAnalyzer::ProcessBlock(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessPhi(), and v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::ResolvePhi().
input() [2/3]
template<class Derived >
V<Any> v8::internal::compiler::turboshaft::OperationT< Derived >::input (size_t i) const [inline]
Definition at line 1113 of file operations.h.
{ return derived_this().inputs()[i]; }
References v8::internal::anonymous_namespace{json-stringifier.cc}::i.
input() [3/3]
template<class Derived >
template<typename T >
V<T> v8::internal::compiler::turboshaft::OperationT< Derived >::input (size_t i) const [inline]
Definition at line 1115 of file operations.h.
                                       {
    return V<T>::Cast(derived_this().inputs()[i]);
  }
References v8::internal::compiler::turboshaft::V< T >::Cast().
inputs() [1/2]
template<class Derived >
base::Vector<OpIndex> v8::internal::compiler::turboshaft::OperationT< Derived >::inputs () [inline]
Definition at line 1099 of file operations.h.
                               {
    return {reinterpret_cast<OpIndex*>(reinterpret_cast<char*>(this) +
                                       sizeof(Derived)),
            derived_this().input_count};
  }
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphFrameState(), v8::internal::compiler::turboshaft::StringEscapeAnalyzer::ComputeFrameStatesToReconstruct(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ComputeTypeForPhi(), v8::internal::compiler::turboshaft::WasmJSLoweringReducer< Next >::CreateFrameStateWithUpdatedBailoutId(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::GetTupleType(), v8::internal::compiler::turboshaft::DeadCodeAnalysis::ProcessBlock(), v8::internal::compiler::turboshaft::StringEscapeAnalyzer::ProcessFrameState(), v8::internal::compiler::turboshaft::PretenuringPropagationAnalyzer::ProcessPhi(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessPhi(), v8::internal::compiler::turboshaft::StringEscapeAnalyzer::RecursivelyMarkAllStringConcatInputsAsEscaping(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::ResolvePhi(), and v8::internal::compiler::InstructionSelector::SelectInstructions().
inputs() [2/2]
template<class Derived >
base::Vector<const OpIndex> v8::internal::compiler::turboshaft::OperationT< Derived >::inputs () const [inline]
Definition at line 1104 of file operations.h.
                                           {
    return {reinterpret_cast<const OpIndex*>(
                reinterpret_cast<const char*>(this) + sizeof(Derived)),
            derived_this().input_count};
  }
inputs_rep()
template<class Derived >
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::OperationT< Derived >::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [private]
IsBlockTerminator()
template<class Derived >
static constexpr bool v8::internal::compiler::turboshaft::OperationT< Derived >::IsBlockTerminator () [inline], [static], [constexpr]
Definition at line 1078 of file operations.h.
                                            {
    return turboshaft::IsBlockTerminator(opcode);
  }
References v8::internal::compiler::turboshaft::IsBlockTerminator().
IsRequiredWhenUnused()
template<class Derived >
bool v8::internal::compiler::turboshaft::OperationT< Derived >::IsRequiredWhenUnused () const [inline]
Definition at line 1081 of file operations.h.
                                    {
    return IsBlockTerminator() ||
           derived_this().Effects().is_required_when_unused();
  }
References v8::internal::compiler::turboshaft::IsBlockTerminator().
New() [1/2]
template<class Derived >
template<class... Args>
static Derived& v8::internal::compiler::turboshaft::OperationT< Derived >::New (Graph * graph, ShadowyOpIndexVectorWrapper inputs, Args... args) [inline], [static]
Definition at line 1160 of file operations.h.
                                    {
    return New(graph, inputs.size(), inputs, args...);
  }
References v8::base::args, graph(), v8::internal::anonymous_namespace{intl-objects.cc}::New(), and v8::internal::compiler::turboshaft::ShadowyOpIndexVectorWrapper::size().
New() [2/2]
template<class Derived >
template<class... Args>
static Derived& v8::internal::compiler::turboshaft::OperationT< Derived >::New (Graph * graph, size_t input_count, Args... args) [inline], [static]
Definition at line 1135 of file operations.h.
                                                                      {
    OperationStorageSlot* ptr =
        AllocateOpStorage(graph, StorageSlotCount(input_count));
    Derived* result = new (ptr) Derived(args...);
#ifdef DEBUG
    result->Validate(*graph);
    ZoneVector<MaybeRegisterRepresentation> storage(get_zone(graph));
    base::Vector<const MaybeRegisterRepresentation> expected =
        result->inputs_rep(storage);
    // TODO(mliedtke): DCHECK that expected and inputs are of the same size
    // and adapt inputs_rep() to always emit a representation for all inputs.
    size_t end = std::min<size_t>(expected.size(), result->input_count);
    for (size_t i = 0; i < end; ++i) {
      if (expected[i] == MaybeRegisterRepresentation::None()) continue;
      ValidateOpInputRep(*graph, result->inputs()[i],
                         RegisterRepresentation(expected[i]), result);
    }
#endif
    // If this DCHECK fails, then the number of inputs specified in the
    // operation constructor and in the static New function disagree.
    DCHECK_EQ(input_count, result->Operation::input_count);
    return *result;
  }
References v8::internal::compiler::turboshaft::AllocateOpStorage(), v8::base::args, DCHECK_EQ, v8::internal::compiler::end(), v8::internal::compiler::turboshaft::get_zone(), graph(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::None(), v8::base::internal::result, and v8::base::Vector< T >::size().
Referenced by v8::internal::compiler::turboshaft::FixedArityOperationT< InputCount, Derived >::New().
operator==()
template<class Derived >
bool v8::internal::compiler::turboshaft::OperationT< Derived >::operator== (const Base & other) const [inline]
Definition at line 1187 of file operations.h.
                                           {
    return derived_this().inputs() == other.derived_this().inputs() &&
           derived_this().options() == other.derived_this().options();
  }
References v8::internal::compiler::turboshaft::OperationT< Derived >::derived_this().
outputs_rep()
template<class Derived >
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::OperationT< Derived >::outputs_rep () const [private]
PrintInputs()
template<class Derived >
void v8::internal::compiler::turboshaft::OperationT< Derived >::PrintInputs (std::ostream & os, const std::string & op_index_prefix) const [inline]
Definition at line 1200 of file operations.h.
                                                                           {
    os << "(";
    bool first = true;
    for (OpIndex input : inputs()) {
      if (!first) os << ", ";
      first = false;
      os << op_index_prefix << input.id();
    }
    os << ")";
  }
PrintOptions()
template<class Derived >
void v8::internal::compiler::turboshaft::OperationT< Derived >::PrintOptions (std::ostream & os) const [inline]
Definition at line 1211 of file operations.h.
                                          {
    const auto& options = derived_this().options();
    constexpr size_t options_count =
        std::tuple_size<std::remove_reference_t<decltype(options)>>::value;
    if (options_count == 0) {
      return;
    }
    PrintOptionsHelper(os, options, std::make_index_sequence<options_count>());
  }
References v8::internal::value.
PrintOptionsHelper()
template<class Derived >
template<class... T, size_t... I>
static void v8::internal::compiler::turboshaft::OperationT< Derived >::PrintOptionsHelper (std::ostream & os, const std::tuple< T... > & options, std::index_sequence< I... >) [inline], [static], [private]
Definition at line 1228 of file operations.h.
                                                          {
    os << "[";
    bool first = true;
    USE(first);
    ((first ? (first = false, os << std::get<I>(options))
            : os << ", " << std::get<I>(options)),
     ...);
    os << "]";
  }
References USE.
StorageSlotCount() [1/2]
template<class Derived >
size_t v8::internal::compiler::turboshaft::OperationT< Derived >::StorageSlotCount () const [inline]
Definition at line 1132 of file operations.h.
{ return StorageSlotCount(input_count); }
References v8::internal::compiler::turboshaft::detail::input_count(), and v8::internal::compiler::turboshaft::OperationT< Derived >::StorageSlotCount().
Referenced by v8::internal::compiler::turboshaft::OperationT< Derived >::StorageSlotCount().
StorageSlotCount() [2/2]
template<class Derived >
static size_t v8::internal::compiler::turboshaft::OperationT< Derived >::StorageSlotCount (size_t input_count) [inline], [static]
Definition at line 1119 of file operations.h.
                                                     {
    // The operation size in bytes is:
    // `sizeof(Derived) + input_count*sizeof(OpIndex)`.
    // This is an optimized computation of:
    // round_up(size_in_bytes / sizeof(StorageSlot))
    constexpr size_t r = sizeof(OperationStorageSlot) / sizeof(OpIndex);
    static_assert(sizeof(OperationStorageSlot) % sizeof(OpIndex) == 0);
    static_assert(sizeof(Derived) % sizeof(OpIndex) == 0);
    size_t result = std::max<size_t>(
        2, (r - 1 + sizeof(Derived) / sizeof(OpIndex) + input_count) / r);
    DCHECK_EQ(result, Operation::StorageSlotCount(opcode, input_count));
    return result;
  }
References DCHECK_EQ, v8::internal::compiler::turboshaft::detail::input_count(), v8::base::internal::result, and v8::internal::compiler::turboshaft::Operation::StorageSlotCount().
Validate()
template<class Derived >
void v8::internal::compiler::turboshaft::OperationT< Derived >::Validate (const Graph & graph) const [inline]
Definition at line 1224 of file operations.h.
{}
Member Data Documentation
opcode
template<class Op >
const Opcode v8::internal::compiler::turboshaft::OperationT< Op >::opcode = operation_to_opcode<Op>::value [static]
Definition at line 1075 of file operations.h.
Referenced by v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessBranchOnTarget(), and v8::internal::compiler::turboshaft::DidntThrowOp::Validate().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h