v8::internal::compiler::turboshaft::LoadTypedElementOp Struct Reference
#include <operations.h>
Public Member Functions
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
OpIndex buffer () const
OpIndex base () const
OpIndex external () const
OpIndex index () const
LoadTypedElementOp (OpIndex buffer, OpIndex base, OpIndex external, OpIndex index, ExternalArrayType array_type)
auto options () const
Public Attributes
ExternalArrayType array_type
Static Public Attributes
static constexpr OpEffects effects
Additional Inherited Members
Detailed Description
Definition at line 5893 of file operations.h.
Constructor & Destructor Documentation
LoadTypedElementOp()
v8::internal::compiler::turboshaft::LoadTypedElementOp::LoadTypedElementOp (OpIndex buffer, OpIndex base, OpIndex external, OpIndex index, ExternalArrayType array_type) [inline]
Definition at line 5919 of file operations.h.
      : Base(buffer, base, external, index), array_type(array_type) {}
Member Function Documentation
base()
OpIndex v8::internal::compiler::turboshaft::LoadTypedElementOp::base () const [inline]
Definition at line 5915 of file operations.h.
{ return Base::input(1); }
buffer()
OpIndex v8::internal::compiler::turboshaft::LoadTypedElementOp::buffer () const [inline]
Definition at line 5914 of file operations.h.
{ return Base::input(0); }
external()
OpIndex v8::internal::compiler::turboshaft::LoadTypedElementOp::external () const [inline]
Definition at line 5916 of file operations.h.
{ return Base::input(2); }
index()
OpIndex v8::internal::compiler::turboshaft::LoadTypedElementOp::index () const [inline]
Definition at line 5917 of file operations.h.
{ return Base::input(3); }
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::LoadTypedElementOp::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 5906 of file operations.h.
                                                              {
    return MaybeRepVector<MaybeRegisterRepresentation::Tagged(),
                          MaybeRegisterRepresentation::Tagged(),
                          MaybeRegisterRepresentation::WordPtr(),
                          MaybeRegisterRepresentation::WordPtr()>();
  }
References v8::internal::compiler::turboshaft::MaybeRepVector(), v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::Tagged(), and v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::WordPtr().
options()
auto v8::internal::compiler::turboshaft::LoadTypedElementOp::options () const [inline]
Definition at line 5924 of file operations.h.
{ return std::tuple{array_type}; }
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::LoadTypedElementOp::outputs_rep () const [inline]
Definition at line 5902 of file operations.h.
                                                               {
    return VectorForRep(RegisterRepresentationForArrayType(array_type));
  }
References v8::internal::compiler::turboshaft::RegisterRepresentationForArrayType(), and v8::internal::compiler::turboshaft::VectorForRep().
Member Data Documentation
array_type
ExternalArrayType v8::internal::compiler::turboshaft::LoadTypedElementOp::array_type
Definition at line 5894 of file operations.h.
effects
constexpr OpEffects v8::internal::compiler::turboshaft::LoadTypedElementOp::effects [static], [constexpr]
Initial value:
=
      OpEffects()
          
          .CanReadMemory()
          
          .CanDependOnChecks()
Definition at line 5896 of file operations.h.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h