v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlySegmentForSerialization Struct Reference
Public Member Functions
ReadOnlySegmentForSerialization (Isolate *isolate, const ReadOnlyPageMetadata *page, Address segment_start, size_t segment_size, ObjectPreProcessor *pre_processor)
void PreProcessSegment (ObjectPreProcessor *pre_processor)
void EncodeTaggedSlots (Isolate *isolate)
Public Attributes
const ReadOnlyPageMetadata *const page
const Address segment_start
const size_t segment_size
const size_t segment_offset
std::unique_ptr< uint8_t[]> contents
ro::BitSet tagged_slots
Friends
class EncodeRelocationsVisitor
Detailed Description
Definition at line 135 of file read-only-serializer.cc.
Constructor & Destructor Documentation
ReadOnlySegmentForSerialization()
v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlySegmentForSerialization::ReadOnlySegmentForSerialization (Isolate * isolate, const ReadOnlyPageMetadata * page, Address segment_start, size_t segment_size, ObjectPreProcessor * pre_processor) [inline]
Definition at line 136 of file read-only-serializer.cc.
      : page(page),
        segment_start(segment_start),
        segment_size(segment_size),
        segment_offset(segment_start - page->area_start()),
        contents(new uint8_t[segment_size]),
        tagged_slots(segment_size / kTaggedSize) {
    // .. because tagged_slots records a bit for each slot:
    DCHECK(IsAligned(segment_size, kTaggedSize));
    // Ensure incoming pointers to this page are representable.
    CHECK_LT(isolate->read_only_heap()->read_only_space()->IndexOf(page),
             1UL << ro::EncodedTagged::kPageIndexBits);
    MemCopy(contents.get(), reinterpret_cast<void*>(segment_start),
            segment_size);
    PreProcessSegment(pre_processor);
    if (!V8_STATIC_ROOTS_BOOL) EncodeTaggedSlots(isolate);
  }
References CHECK_LT, v8::internal::DCHECK(), v8::internal::ReadOnlySpace::IndexOf(), IsAligned(), v8::internal::ro::EncodedTagged::kPageIndexBits, v8::internal::kTaggedSize, v8::internal::MemCopy(), v8::internal::Isolate::read_only_heap(), v8::internal::ReadOnlyHeap::read_only_space(), and V8_STATIC_ROOTS_BOOL.
Member Function Documentation
EncodeTaggedSlots()
void v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlySegmentForSerialization::EncodeTaggedSlots (Isolate * isolate)
Definition at line 308 of file read-only-serializer.cc.
                                                                        {
  DCHECK(!V8_STATIC_ROOTS_BOOL);
  EncodeRelocationsVisitor v(isolate, this);
  PtrComprCageBase cage_base(isolate);
  DCHECK_GE(segment_start, page->area_start());
  const Address segment_end = segment_start + segment_size;
  ReadOnlyPageObjectIterator it(page, segment_start,
                                SkipFreeSpaceOrFiller::kNo);
  for (Tagged<HeapObject> o = it.Next(); !o.is_null(); o = it.Next()) {
    if (o.address() >= segment_end) break;
    VisitObject(isolate, o, &v);
  }
}
References v8::internal::DCHECK(), DCHECK_GE, v8::internal::Tagged< HeapObject >::is_null(), v8::internal::kNo, v8::internal::ReadOnlyPageObjectIterator::Next(), V8_STATIC_ROOTS_BOOL, and v8::internal::VisitObject().
PreProcessSegment()
void v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlySegmentForSerialization::PreProcessSegment (ObjectPreProcessor * pre_processor) [inline]
Definition at line 158 of file read-only-serializer.cc.
                                                            {
    // Iterate the RO page and the contents copy in lockstep, preprocessing
    // objects as we go along.
    //
    // See also ObjectSerializer::OutputRawData.
    DCHECK_GE(segment_start, page->area_start());
    const Address segment_end = segment_start + segment_size;
    ReadOnlyPageObjectIterator it(page, segment_start);
    for (Tagged<HeapObject> o = it.Next(); !o.is_null(); o = it.Next()) {
      if (o.address() >= segment_end) break;
      size_t o_offset = o.ptr() - segment_start;
      Address o_dst = reinterpret_cast<Address>(contents.get()) + o_offset;
      pre_processor->PreProcessIfNeeded(
          Cast<HeapObject>(Tagged<Object>(o_dst)));
    }
  }
References DCHECK_GE, v8::internal::Tagged< HeapObject >::is_null(), v8::internal::ReadOnlyPageObjectIterator::Next(), and v8::internal::anonymous_namespace{read-only-serializer.cc}::ObjectPreProcessor::PreProcessIfNeeded().
Friends And Related Function Documentation
EncodeRelocationsVisitor
friend class EncodeRelocationsVisitor [friend]
Definition at line 186 of file read-only-serializer.cc.
Member Data Documentation
contents
std::unique_ptr<uint8_t[]> v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlySegmentForSerialization::contents
Definition at line 182 of file read-only-serializer.cc.
Referenced by v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlyHeapImageSerializer::EmitSegment().
page
const ReadOnlyPageMetadata* const v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlySegmentForSerialization::page
Definition at line 177 of file read-only-serializer.cc.
Referenced by v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlyHeapImageSerializer::EmitSegment().
segment_offset
const size_t v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlySegmentForSerialization::segment_offset
Definition at line 180 of file read-only-serializer.cc.
Referenced by v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlyHeapImageSerializer::EmitSegment().
segment_size
const size_t v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlySegmentForSerialization::segment_size
Definition at line 179 of file read-only-serializer.cc.
Referenced by v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlyHeapImageSerializer::EmitSegment().
segment_start
const Address v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlySegmentForSerialization::segment_start
Definition at line 178 of file read-only-serializer.cc.
tagged_slots
ro::BitSet v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlySegmentForSerialization::tagged_slots
Definition at line 184 of file read-only-serializer.cc.
Referenced by v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlyHeapImageSerializer::EmitSegment().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/snapshot/read-only-serializer.cc