v8::internal::SourceTextModuleDescriptor::ModuleRequestComparer Struct Reference
#include <modules.h>
Public Member Functions
bool operator() (const AstModuleRequest *lhs, const AstModuleRequest *rhs) const
Detailed Description
Definition at line 168 of file modules.h.
Member Function Documentation
operator()()
bool v8::internal::SourceTextModuleDescriptor::ModuleRequestComparer::operator() (const AstModuleRequest * lhs, const AstModuleRequest * rhs) const
Definition at line 23 of file modules.cc.
                                                                    {
  if (int specifier_comparison =
          AstRawString::Compare(lhs->specifier(), rhs->specifier())) {
    return specifier_comparison < 0;
  }
  auto lhsIt = lhs->import_attributes()->cbegin();
  auto rhsIt = rhs->import_attributes()->cbegin();
  for (; lhsIt != lhs->import_attributes()->cend() &&
         rhsIt != rhs->import_attributes()->cend();
       ++lhsIt, ++rhsIt) {
    if (int assertion_key_comparison =
            AstRawString::Compare(lhsIt->first, rhsIt->first)) {
      return assertion_key_comparison < 0;
    }
    if (int assertion_value_comparison =
            AstRawString::Compare(lhsIt->second.first, rhsIt->second.first)) {
      return assertion_value_comparison < 0;
    }
  }
  if (lhs->import_attributes()->size() != rhs->import_attributes()->size()) {
    return (lhs->import_attributes()->size() <
            rhs->import_attributes()->size());
  }
  if (lhs->phase() != rhs->phase()) {
    return lhs->phase() < rhs->phase();
  }
  return false;
}
References v8::internal::AstRawString::Compare(), v8::internal::SourceTextModuleDescriptor::AstModuleRequest::import_attributes(), v8::internal::SourceTextModuleDescriptor::AstModuleRequest::phase(), and v8::internal::SourceTextModuleDescriptor::AstModuleRequest::specifier().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/ast/modules.h
/mnt/V8SourceCode/src/ast/modules.cc