v8::internal::RegExpInstruction Struct Reference
#include <experimental-bytecode.h>
Classes
class LookaroundPayload
struct Uc16Range
Public Types
enum Opcode : int32_t {
ACCEPT
, ASSERTION
, CLEAR_REGISTER
, CONSUME_RANGE
,
RANGE_COUNT
, FORK
, JMP
, SET_REGISTER_TO_CP
,
SET_QUANTIFIER_TO_CLOCK
, FILTER_QUANTIFIER
, FILTER_GROUP
, FILTER_LOOKAROUND
,
FILTER_CHILD
, BEGIN_LOOP
, END_LOOP
, START_LOOKAROUND
,
END_LOOKAROUND
, WRITE_LOOKAROUND_TABLE
, READ_LOOKAROUND_TABLE
 }
Static Public Member Functions
static RegExpInstruction ConsumeRange (base::uc16 min, base::uc16 max)
static RegExpInstruction ConsumeAnyChar ()
static RegExpInstruction Fail ()
static RegExpInstruction RangeCount (int32_t num_ranges)
static RegExpInstruction Fork (int32_t alt_index)
static RegExpInstruction Jmp (int32_t alt_index)
static RegExpInstruction Accept ()
static RegExpInstruction SetRegisterToCp (int32_t register_index)
static RegExpInstruction Assertion (RegExpAssertion::Type t)
static RegExpInstruction ClearRegister (int32_t register_index)
static RegExpInstruction SetQuantifierToClock (int32_t quantifier_id)
static RegExpInstruction FilterQuantifier (int32_t quantifier_id)
static RegExpInstruction FilterGroup (int32_t group_id)
static RegExpInstruction FilterLookaround (int32_t lookaround_id)
static RegExpInstruction FilterChild (int32_t pc)
static RegExpInstruction BeginLoop ()
static RegExpInstruction EndLoop ()
static RegExpInstruction StartLookaround (int lookaround_index, bool is_positive, RegExpLookaround::Type type)
static RegExpInstruction EndLookaround ()
static RegExpInstruction WriteLookTable (int32_t index)
static RegExpInstruction ReadLookTable (int32_t index, bool is_positive, RegExpLookaround::Type type)
static bool IsFilter (const RegExpInstruction &instruction)
Public Attributes
Opcode opcode
xx xx xx xx xx xx xx xx xx
union {
 Uc16Range consume_range
 int32_t num_ranges
 int32_t pc
 int32_t register_index
 RegExpAssertion::Type assertion_type
 int32_t quantifier_id
 int32_t group_id
 int32_t lookaround_id
 LookaroundPayload lookaround
} payload
Detailed Description
Definition at line 99 of file experimental-bytecode.h.
Member Enumeration Documentation
Opcode
enum v8::internal::RegExpInstruction::Opcode : int32_t
Enumerator
ACCEPT
ASSERTION
CLEAR_REGISTER
CONSUME_RANGE
RANGE_COUNT
FORK
JMP
SET_REGISTER_TO_CP
SET_QUANTIFIER_TO_CLOCK
FILTER_QUANTIFIER
FILTER_GROUP
FILTER_LOOKAROUND
FILTER_CHILD
BEGIN_LOOP
END_LOOP
START_LOOKAROUND
END_LOOKAROUND
WRITE_LOOKAROUND_TABLE
READ_LOOKAROUND_TABLE
Definition at line 100 of file experimental-bytecode.h.
              : int32_t {
    ACCEPT,
    ASSERTION,
    CLEAR_REGISTER,
    CONSUME_RANGE,
    RANGE_COUNT,
    FORK,
    JMP,
    SET_REGISTER_TO_CP,
    SET_QUANTIFIER_TO_CLOCK,
    FILTER_QUANTIFIER,
    FILTER_GROUP,
    FILTER_LOOKAROUND,
    FILTER_CHILD,
    BEGIN_LOOP,
    END_LOOP,
    START_LOOKAROUND,
    END_LOOKAROUND,
    WRITE_LOOKAROUND_TABLE,
    READ_LOOKAROUND_TABLE,
  };
Member Function Documentation
Accept()
static RegExpInstruction v8::internal::RegExpInstruction::Accept () [inline], [static]
Definition at line 187 of file experimental-bytecode.h.
                                    {
    RegExpInstruction result;
    result.opcode = ACCEPT;
    return result;
  }
References ACCEPT, and v8::base::internal::result.
Referenced by v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::Accept().
Assertion()
static RegExpInstruction v8::internal::RegExpInstruction::Assertion (RegExpAssertion::Type t) [inline], [static]
Definition at line 200 of file experimental-bytecode.h.
                                                            {
    RegExpInstruction result;
    result.opcode = ASSERTION;
    result.payload.assertion_type = t;
    return result;
  }
References ASSERTION, and v8::base::internal::result.
Referenced by v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::Assertion().
BeginLoop()
static RegExpInstruction v8::internal::RegExpInstruction::BeginLoop () [inline], [static]
Definition at line 249 of file experimental-bytecode.h.
                                       {
    RegExpInstruction result;
    result.opcode = BEGIN_LOOP;
    return result;
  }
References BEGIN_LOOP, and v8::base::internal::result.
Referenced by v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::BeginLoop().
ClearRegister()
static RegExpInstruction v8::internal::RegExpInstruction::ClearRegister (int32_t register_index) [inline], [static]
Definition at line 207 of file experimental-bytecode.h.
                                                                 {
    RegExpInstruction result;
    result.opcode = CLEAR_REGISTER;
    result.payload.register_index = register_index;
    return result;
  }
References CLEAR_REGISTER, register_index, and v8::base::internal::result.
Referenced by v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::ClearRegister().
ConsumeAnyChar()
static RegExpInstruction v8::internal::RegExpInstruction::ConsumeAnyChar () [inline], [static]
Definition at line 156 of file experimental-bytecode.h.
                                            {
    return ConsumeRange(0x0000, 0xFFFF);
  }
References ConsumeRange().
Referenced by v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::ConsumeAnyChar().
ConsumeRange()
static RegExpInstruction v8::internal::RegExpInstruction::ConsumeRange (base::uc16 min, base::uc16 max) [inline], [static]
Definition at line 149 of file experimental-bytecode.h.
                                                                    {
    RegExpInstruction result;
    result.opcode = CONSUME_RANGE;
    result.payload.consume_range = Uc16Range{min, max};
    return result;
  }
References CONSUME_RANGE, and v8::base::internal::result.
Referenced by ConsumeAnyChar(), v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::ConsumeRange(), and Fail().
EndLookaround()
static RegExpInstruction v8::internal::RegExpInstruction::EndLookaround () [inline], [static]
Definition at line 271 of file experimental-bytecode.h.
                                           {
    RegExpInstruction result;
    result.opcode = END_LOOKAROUND;
    return result;
  }
References END_LOOKAROUND, and v8::base::internal::result.
Referenced by v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::EndLookaround().
EndLoop()
static RegExpInstruction v8::internal::RegExpInstruction::EndLoop () [inline], [static]
Definition at line 255 of file experimental-bytecode.h.
                                     {
    RegExpInstruction result;
    result.opcode = END_LOOP;
    return result;
  }
References END_LOOP, and v8::base::internal::result.
Referenced by v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::EndLoop().
Fail()
static RegExpInstruction v8::internal::RegExpInstruction::Fail () [inline], [static]
Definition at line 160 of file experimental-bytecode.h.
                                  {
    // This is encoded as the empty CONSUME_RANGE of characters 0xFFFF <= c <=
    // 0x0000.
    return ConsumeRange(0xFFFF, 0x0000);
  }
References ConsumeRange().
Referenced by v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::Fail().
FilterChild()
static RegExpInstruction v8::internal::RegExpInstruction::FilterChild (int32_t pc) [inline], [static]
Definition at line 242 of file experimental-bytecode.h.
                                                   {
    RegExpInstruction result;
    result.opcode = FILTER_CHILD;
    result.payload.pc = pc;
    return result;
  }
References FILTER_CHILD, pc, and v8::base::internal::result.
FilterGroup()
static RegExpInstruction v8::internal::RegExpInstruction::FilterGroup (int32_t group_id) [inline], [static]
Definition at line 228 of file experimental-bytecode.h.
                                                         {
    RegExpInstruction result;
    result.opcode = FILTER_GROUP;
    result.payload.group_id = group_id;
    return result;
  }
References FILTER_GROUP, group_id, and v8::base::internal::result.
Referenced by v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::FilterGroup().
FilterLookaround()
static RegExpInstruction v8::internal::RegExpInstruction::FilterLookaround (int32_t lookaround_id) [inline], [static]
Definition at line 235 of file experimental-bytecode.h.
                                                                   {
    RegExpInstruction result;
    result.opcode = FILTER_LOOKAROUND;
    result.payload.lookaround_id = lookaround_id;
    return result;
  }
References FILTER_LOOKAROUND, lookaround_id, and v8::base::internal::result.
Referenced by v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::FilterLookaround().
FilterQuantifier()
static RegExpInstruction v8::internal::RegExpInstruction::FilterQuantifier (int32_t quantifier_id) [inline], [static]
Definition at line 221 of file experimental-bytecode.h.
                                                                   {
    RegExpInstruction result;
    result.opcode = FILTER_QUANTIFIER;
    result.payload.quantifier_id = quantifier_id;
    return result;
  }
References FILTER_QUANTIFIER, quantifier_id, and v8::base::internal::result.
Referenced by v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::FilterQuantifier().
Fork()
static RegExpInstruction v8::internal::RegExpInstruction::Fork (int32_t alt_index) [inline], [static]
Definition at line 173 of file experimental-bytecode.h.
                                                   {
    RegExpInstruction result;
    result.opcode = FORK;
    result.payload.pc = alt_index;
    return result;
  }
References FORK, and v8::base::internal::result.
IsFilter()
static bool v8::internal::RegExpInstruction::IsFilter (const RegExpInstruction & instruction) [inline], [static]
Definition at line 294 of file experimental-bytecode.h.
                                                             {
    return instruction.opcode == RegExpInstruction::Opcode::FILTER_GROUP ||
           instruction.opcode == RegExpInstruction::Opcode::FILTER_QUANTIFIER ||
           instruction.opcode == RegExpInstruction::Opcode::FILTER_CHILD;
  }
References opcode.
Referenced by v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::NfaInterpreter().
Jmp()
static RegExpInstruction v8::internal::RegExpInstruction::Jmp (int32_t alt_index) [inline], [static]
Definition at line 180 of file experimental-bytecode.h.
                                                  {
    RegExpInstruction result;
    result.opcode = JMP;
    result.payload.pc = alt_index;
    return result;
  }
References JMP, and v8::base::internal::result.
RangeCount()
static RegExpInstruction v8::internal::RegExpInstruction::RangeCount (int32_t num_ranges) [inline], [static]
Definition at line 166 of file experimental-bytecode.h.
                                                          {
    RegExpInstruction result;
    result.opcode = RANGE_COUNT;
    result.payload.num_ranges = num_ranges;
    return result;
  }
References num_ranges, RANGE_COUNT, and v8::base::internal::result.
Referenced by v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::RangeCount().
ReadLookTable()
static RegExpInstruction v8::internal::RegExpInstruction::ReadLookTable (int32_t index, bool is_positive, RegExpLookaround::Type type) [inline], [static]
Definition at line 284 of file experimental-bytecode.h.
                                                                    {
    RegExpInstruction result;
    result.opcode = READ_LOOKAROUND_TABLE;
    result.payload.lookaround = LookaroundPayload(index, is_positive, type);
    return result;
  }
References v8::internal::index, READ_LOOKAROUND_TABLE, v8::base::internal::result, and v8::internal::tracing::type.
Referenced by v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::ReadLookaroundTable().
SetQuantifierToClock()
static RegExpInstruction v8::internal::RegExpInstruction::SetQuantifierToClock (int32_t quantifier_id) [inline], [static]
Definition at line 214 of file experimental-bytecode.h.
                                                                       {
    RegExpInstruction result;
    result.opcode = SET_QUANTIFIER_TO_CLOCK;
    result.payload.quantifier_id = quantifier_id;
    return result;
  }
References quantifier_id, v8::base::internal::result, and SET_QUANTIFIER_TO_CLOCK.
Referenced by v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::SetQuantifierToClock().
SetRegisterToCp()
static RegExpInstruction v8::internal::RegExpInstruction::SetRegisterToCp (int32_t register_index) [inline], [static]
Definition at line 193 of file experimental-bytecode.h.
                                                                   {
    RegExpInstruction result;
    result.opcode = SET_REGISTER_TO_CP;
    result.payload.register_index = register_index;
    return result;
  }
References register_index, v8::base::internal::result, and SET_REGISTER_TO_CP.
Referenced by v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::SetRegisterToCp().
StartLookaround()
static RegExpInstruction v8::internal::RegExpInstruction::StartLookaround (int lookaround_index, bool is_positive, RegExpLookaround::Type type) [inline], [static]
Definition at line 261 of file experimental-bytecode.h.
                                                                      {
    RegExpInstruction result;
    result.opcode = START_LOOKAROUND;
    result.payload.lookaround =
        LookaroundPayload(lookaround_index, is_positive, type);
    return result;
  }
References v8::base::internal::result, START_LOOKAROUND, and v8::internal::tracing::type.
Referenced by v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::StartLookaround().
WriteLookTable()
static RegExpInstruction v8::internal::RegExpInstruction::WriteLookTable (int32_t index) [inline], [static]
Definition at line 277 of file experimental-bytecode.h.
                                                         {
    RegExpInstruction result;
    result.opcode = WRITE_LOOKAROUND_TABLE;
    result.payload.lookaround_id = index;
    return result;
  }
References v8::internal::index, v8::base::internal::result, and WRITE_LOOKAROUND_TABLE.
Referenced by v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::WriteLookaroundTable().
Member Data Documentation
assertion_type
RegExpAssertion::Type v8::internal::RegExpInstruction::assertion_type
Definition at line 312 of file experimental-bytecode.h.
Referenced by v8::internal::operator<<(), and v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::RunActiveThread().
consume_range
Uc16Range v8::internal::RegExpInstruction::consume_range
Definition at line 303 of file experimental-bytecode.h.
Referenced by v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::FlushBlockedThreads(), and v8::internal::operator<<().
group_id
int32_t v8::internal::RegExpInstruction::group_id
Definition at line 316 of file experimental-bytecode.h.
Referenced by FilterGroup(), and v8::internal::operator<<().
lookaround
LookaroundPayload v8::internal::RegExpInstruction::lookaround
Definition at line 320 of file experimental-bytecode.h.
Referenced by v8::internal::operator<<(), and v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::RunActiveThread().
lookaround_id
int32_t v8::internal::RegExpInstruction::lookaround_id
Definition at line 318 of file experimental-bytecode.h.
Referenced by FilterLookaround(), v8::internal::operator<<(), and v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::RunActiveThread().
num_ranges
int32_t v8::internal::RegExpInstruction::num_ranges
Definition at line 305 of file experimental-bytecode.h.
Referenced by v8::internal::operator<<(), and RangeCount().
opcode
Opcode v8::internal::RegExpInstruction::opcode
Definition at line 300 of file experimental-bytecode.h.
Referenced by v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::Bind(), v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::FlushBlockedThreads(), IsFilter(), v8::internal::operator<<(), and v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::RunActiveThread().
union { ... } v8::internal::RegExpInstruction::payload
Referenced by v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::Bind(), v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::FlushBlockedThreads(), v8::internal::operator<<(), and v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::RunActiveThread().
pc
int32_t v8::internal::RegExpInstruction::pc
Definition at line 308 of file experimental-bytecode.h.
Referenced by v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::Bind(), FilterChild(), v8::internal::operator<<(), and v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::RunActiveThread().
quantifier_id
int32_t v8::internal::RegExpInstruction::quantifier_id
Definition at line 314 of file experimental-bytecode.h.
Referenced by FilterQuantifier(), v8::internal::operator<<(), v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::RunActiveThread(), and SetQuantifierToClock().
register_index
int32_t v8::internal::RegExpInstruction::register_index
Definition at line 310 of file experimental-bytecode.h.
Referenced by ClearRegister(), v8::internal::operator<<(), v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::RunActiveThread(), and SetRegisterToCp().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/regexp/experimental/experimental-bytecode.h