v8::internal::compiler::turboshaft::FloatOperationTyper< Bits > Struct Template Reference
#include <typer.h>
Public Types
using float_t = std::conditional_t< Bits==32, float, double >
using type_t = FloatType< Bits >
Static Public Member Functions
static type_t Range (float_t min, float_t max, uint32_t special_values, Zone *zone)
static type_t Set (std::vector< float_t > elements, uint32_t special_values, Zone *zone)
static bool IsIntegerSet (const type_t &t)
static bool IsZeroish (const type_t &l)
static Type ProductSet (const type_t &l, const type_t &r, uint32_t special_values, Zone *zone, std::function< float_t(float_t, float_t)> combine)
static Type Add (type_t l, type_t r, Zone *zone)
static Type Subtract (type_t l, type_t r, Zone *zone)
static Type Multiply (type_t l, type_t r, Zone *zone)
static Type Divide (const type_t &l, const type_t &r, Zone *zone)
static Type Modulus (type_t l, type_t r, Zone *zone)
static Type Min (type_t l, type_t r, Zone *zone)
static Type Max (type_t l, type_t r, Zone *zone)
static Type Power (const type_t &l, const type_t &r, Zone *zone)
static Type Atan2 (const type_t &l, const type_t &r, Zone *zone)
static Type LessThan (const type_t &lhs, const type_t &rhs, Zone *zone)
static Type LessThanOrEqual (const type_t &lhs, const type_t &rhs, Zone *zone)
static Word32Type UnsignedLessThanOrEqual (const type_t &lhs, const type_t &rhs, Zone *zone)
static std::pair< Type, Type > RestrictionForLessThan_True (const type_t &lhs, const type_t &rhs, Zone *zone)
static std::pair< Type, Type > RestrictionForLessThan_False (const type_t &lhs, const type_t &rhs, Zone *zone)
static std::pair< Type, Type > RestrictionForLessThanOrEqual_True (const type_t &lhs, const type_t &rhs, Zone *zone)
static std::pair< Type, Type > RestrictionForLessThanOrEqual_False (const type_t &lhs, const type_t &rhs, Zone *zone)
Static Public Attributes
static constexpr float_t inf = std::numeric_limits<float_t>::infinity()
static constexpr int kSetThreshold = type_t::kMaxSetSize
Detailed Description
template<size_t Bits>
struct v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >
Definition at line 406 of file typer.h.
Member Typedef Documentation
float_t
template<size_t Bits>
using v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::float_t = std::conditional_t<Bits == 32, float, double>
Definition at line 408 of file typer.h.
type_t
template<size_t Bits>
using v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::type_t = FloatType<Bits>
Definition at line 409 of file typer.h.
Member Function Documentation
Add()
template<size_t Bits>
static Type v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Add (type_t l, type_t r, Zone * zone) [inline], [static]
Definition at line 507 of file typer.h.
                                                  {
    // Addition can return NaN if either input can be NaN or we try to compute
    // the sum of two infinities of opposite sign.
    if (l.is_only_nan() || r.is_only_nan()) return type_t::NaN();
    bool maybe_nan = l.has_nan() || r.has_nan();
    // Addition can yield minus zero only if both inputs can be minus zero.
    bool maybe_minuszero = true;
    if (l.has_minus_zero()) {
      l = type_t::LeastUpperBound(l, type_t::Constant(0), zone);
    } else {
      maybe_minuszero = false;
    }
    if (r.has_minus_zero()) {
      r = type_t::LeastUpperBound(r, type_t::Constant(0), zone);
    } else {
      maybe_minuszero = false;
    }
    uint32_t special_values = (maybe_nan ? type_t::kNaN : 0) |
                              (maybe_minuszero ? type_t::kMinusZero : 0);
    // If both sides are decently small sets, we produce the product set.
    auto combine = [](float_t a, float_t b) { return a + b; };
    if (l.is_set() && r.is_set()) {
      auto result = ProductSet(l, r, special_values, zone, combine);
      if (!result.IsInvalid()) return result;
    }
    // Otherwise just construct a range.
    auto [l_min, l_max] = l.minmax();
    auto [r_min, r_max] = r.minmax();
    std::array<float_t, 4> results;
    results[0] = l_min + r_min;
    results[1] = l_min + r_max;
    results[2] = l_max + r_min;
    results[3] = l_max + r_max;
    int nans = 0;
    for (int i = 0; i < 4; ++i) {
      if (std::isnan(results[i])) ++nans;
    }
    if (nans > 0) {
      special_values |= type_t::kNaN;
      if (nans >= 4) {
        // All combinations of inputs produce NaN.
        return type_t::OnlySpecialValues(special_values);
      }
    }
    const float_t result_min = array_min(results);
    const float_t result_max = array_max(results);
    return Range(result_min, result_max, special_values, zone);
  }
References v8::internal::compiler::turboshaft::array_max(), v8::internal::compiler::turboshaft::array_min(), v8::internal::compiler::turboshaft::FloatType< Bits >::Constant(), v8::internal::compiler::turboshaft::FloatType< Bits >::has_minus_zero(), v8::internal::compiler::turboshaft::FloatType< Bits >::has_nan(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::FloatType< Bits >::is_only_nan(), v8::internal::compiler::turboshaft::FloatType< Bits >::is_set(), v8::internal::compiler::turboshaft::FloatType< Bits >::kMinusZero, v8::internal::compiler::turboshaft::FloatType< Bits >::kNaN, v8::internal::compiler::turboshaft::l, v8::internal::compiler::turboshaft::FloatType< Bits >::LeastUpperBound(), v8::internal::compiler::turboshaft::FloatType< Bits >::minmax(), v8::internal::compiler::turboshaft::FloatType< Bits >::NaN(), v8::internal::compiler::turboshaft::FloatType< Bits >::OnlySpecialValues(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::ProductSet(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Range(), and v8::base::internal::result.
Atan2()
template<size_t Bits>
static Type v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Atan2 (const type_t & l, const type_t & r, Zone * zone) [inline], [static]
Definition at line 940 of file typer.h.
                                                                  {
    // TODO(nicohartmann@): Maybe we can produce a more precise range here.
    return type_t::Any();
  }
References v8::internal::compiler::turboshaft::Type::Any().
Divide()
template<size_t Bits>
static Type v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Divide (const type_t & l, const type_t & r, Zone * zone) [inline], [static]
Definition at line 677 of file typer.h.
                                                                   {
    // Division is tricky, so all we do is try ruling out -0 and NaN.
    if (l.is_only_nan() || r.is_only_nan()) return type_t::NaN();
    // If both sides are decently small sets, we produce the product set.
    auto combine = [](float_t a, float_t b) {
      if V8_UNLIKELY (!std::isfinite(a) && !std::isfinite(b)) {
        return nan_v<Bits>;
      }
      if V8_UNLIKELY (IsMinusZero(b)) {
        // +-0 / -0 ==> NaN
        if (a == 0 || std::isnan(a)) return nan_v<Bits>;
        return a > 0 ? -inf : inf;
      }
      if V8_UNLIKELY (b == 0) {
        // +-0 / 0 ==> NaN
        if (a == 0 || std::isnan(a)) return nan_v<Bits>;
        return a > 0 ? inf : -inf;
      }
      return a / b;
    };
    if (l.is_set() && r.is_set()) {
      auto result = ProductSet(l, r, 0, zone, combine);
      if (!result.IsInvalid()) return result;
    }
    auto [l_min, l_max] = l.minmax();
    auto [r_min, r_max] = r.minmax();
    bool maybe_nan =
        l.has_nan() || IsZeroish(r) ||
        ((l_min == -inf || l_max == inf) && (r_min == -inf || r_max == inf));
    // Try to rule out -0.
    bool maybe_minuszero =
        // -0 / r (r > 0)
        (l.has_minus_zero() && r_max > 0)
        // 0 / r (r < 0)
        || (l.Contains(0) && r_min < 0)
        // -0.0..01 / r (r > 1)
        || (l.Contains(0) && l_min < 0 && r_max > 1)
        // 0.0..01 / r (r < -1)
        || (l.Contains(0) && l_max >= 0 && r_min < -1)
        // l / large (l < 0)
        || (l_max < 0 && detail::is_minus_zero(l_max / r_max))
        // l / -large (l > 0)
        || (l_min > 0 && detail::is_minus_zero(l_min / r_min));
    uint32_t special_values = (maybe_nan ? type_t::kNaN : 0) |
                              (maybe_minuszero ? type_t::kMinusZero : 0);
    const bool r_all_positive = r_min >= 0 && !r.has_minus_zero();
    const bool r_all_negative = r_max < 0;
    // If r doesn't span 0, we can try to compute a more precise type.
    if (r_all_positive || r_all_negative) {
      // If r does not contain 0 or -0, we can compute a range.
      if (r_min > 0 && !r.has_minus_zero()) {
        std::array<float_t, 4> results;
        results[0] = l_min / r_min;
        results[1] = l_min / r_max;
        results[2] = l_max / r_min;
        results[3] = l_max / r_max;
        for (float_t res : results) {
          if (std::isnan(res)) return type_t::Any();
        }
        const float_t result_min = array_min(results);
        const float_t result_max = array_max(results);
        return Range(result_min, result_max, special_values, zone);
      }
      // Otherwise we try to check for the sign of the result.
      if (l_max < 0) {
        if (r_all_positive) {
          // All values are negative.
          return Range(-inf, next_smaller(float_t{0}), special_values, zone);
        } else {
          DCHECK(r_all_negative);
          // All values are positive.
          return Range(0, inf, special_values, zone);
        }
      } else if (l_min >= 0 && !l.has_minus_zero()) {
        if (r_all_positive) {
          // All values are positive.
          DCHECK_EQ(special_values & type_t::kMinusZero, 0);
          return Range(0, inf, special_values, zone);
        } else {
          DCHECK(r_all_negative);
          // All values are negative.
          return Range(-inf, next_smaller(float_t{0}), special_values, zone);
        }
      }
    }
    // Otherwise we give up on a precise type.
    return type_t::Any(special_values);
  }
References v8::internal::compiler::turboshaft::Type::Any(), v8::internal::compiler::turboshaft::array_max(), v8::internal::compiler::turboshaft::array_min(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::turboshaft::FloatType< Bits >::has_minus_zero(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::inf, v8::internal::compiler::turboshaft::detail::is_minus_zero(), v8::internal::compiler::turboshaft::FloatType< Bits >::is_only_nan(), v8::internal::compiler::turboshaft::FloatType< Bits >::is_set(), v8::internal::IsMinusZero(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::IsZeroish(), v8::internal::compiler::turboshaft::FloatType< Bits >::kMinusZero, v8::internal::compiler::turboshaft::FloatType< Bits >::kNaN, v8::internal::compiler::turboshaft::l, v8::internal::compiler::turboshaft::FloatType< Bits >::minmax(), v8::internal::compiler::turboshaft::FloatType< Bits >::NaN(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::ProductSet(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Range(), v8::base::internal::result, and V8_UNLIKELY.
IsIntegerSet()
template<size_t Bits>
static bool v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::IsIntegerSet (const type_t & t) [inline], [static]
Definition at line 445 of file typer.h.
                                            {
    if (!t.is_set()) return false;
    int size = t.set_size();
    DCHECK_LT(0, size);
    float_t unused_ipart;
    float_t min = t.set_element(0);
    if (std::modf(min, &unused_ipart) != 0.0) return false;
    if (min == -inf) return false;
    float_t max = t.set_element(size - 1);
    if (std::modf(max, &unused_ipart) != 0.0) return false;
    if (max == inf) return false;
    for (int i = 1; i < size - 1; ++i) {
      if (std::modf(t.set_element(i), &unused_ipart) != 0.0) return false;
    }
    return true;
  }
References DCHECK_LT, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::inf, v8::internal::compiler::turboshaft::FloatType< Bits >::is_set(), v8::internal::compiler::turboshaft::FloatType< Bits >::set_element(), v8::internal::compiler::turboshaft::FloatType< Bits >::set_size(), and size().
Referenced by v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Modulus(), and v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Power().
IsZeroish()
template<size_t Bits>
static bool v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::IsZeroish (const type_t & l) [inline], [static]
Definition at line 464 of file typer.h.
                                         {
    return l.has_nan() || l.has_minus_zero() || l.Contains(0);
  }
References v8::internal::compiler::turboshaft::l.
Referenced by v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Divide(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Modulus(), and v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Multiply().
LessThan()
template<size_t Bits>
static Type v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::LessThan (const type_t & lhs, const type_t & rhs, Zone * zone) [inline], [static]
Definition at line 945 of file typer.h.
                                                                         {
    bool can_be_true = false;
    bool can_be_false = false;
    if (lhs.is_only_special_values()) {
      if (lhs.has_minus_zero()) {
        can_be_true = !rhs.is_only_special_values() && rhs.max() > 0.0;
        can_be_false = rhs.min() <= 0.0;
      } else {
        DCHECK(lhs.is_only_nan());
      }
    } else if (rhs.is_only_special_values()) {
      if (rhs.has_minus_zero()) {
        can_be_true = lhs.min() < 0.0;
        can_be_false = lhs.max() >= 0.0;
      } else {
        DCHECK(rhs.is_only_nan());
      }
    } else {
      // Both sides have at least one non-special value. We don't have to treat
      // special values here, because nan has been taken care of already and
      // -0.0 is included in min/max.
      can_be_true = lhs.min() < rhs.max();
      can_be_false = lhs.max() >= rhs.min();
    }
    // Consider NaN.
    can_be_false = can_be_false || lhs.has_nan() || rhs.has_nan();
    if (!can_be_true) return Word32Type::Constant(0);
    if (!can_be_false) return Word32Type::Constant(1);
    return Word32Type::Set({0, 1}, zone);
  }
References v8::internal::compiler::turboshaft::WordType< Bits >::Constant(), v8::internal::DCHECK(), v8::internal::compiler::turboshaft::FloatType< Bits >::has_minus_zero(), v8::internal::compiler::turboshaft::FloatType< Bits >::has_nan(), v8::internal::compiler::turboshaft::FloatType< Bits >::is_only_nan(), v8::internal::compiler::turboshaft::FloatType< Bits >::is_only_special_values(), v8::internal::compiler::turboshaft::FloatType< Bits >::max(), v8::internal::compiler::turboshaft::FloatType< Bits >::min(), and v8::internal::compiler::turboshaft::WordType< Bits >::Set().
Referenced by v8::internal::compiler::turboshaft::Typer::TypeFloat32Comparison(), and v8::internal::compiler::turboshaft::Typer::TypeFloat64Comparison().
LessThanOrEqual()
template<size_t Bits>
static Type v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::LessThanOrEqual (const type_t & lhs, const type_t & rhs, Zone * zone) [inline], [static]
Definition at line 978 of file typer.h.
                                          {
    bool can_be_true = false;
    bool can_be_false = false;
    if (lhs.is_only_special_values()) {
      if (lhs.has_minus_zero()) {
        can_be_true = (!rhs.is_only_special_values() && rhs.max() >= 0.0) ||
                      rhs.has_minus_zero();
        can_be_false = rhs.min() < 0.0;
      } else {
        DCHECK(lhs.is_only_nan());
      }
    } else if (rhs.is_only_special_values()) {
      if (rhs.has_minus_zero()) {
        can_be_true = (!lhs.is_only_special_values() && lhs.min() <= 0.0) ||
                      lhs.has_minus_zero();
        can_be_false = lhs.max() > 0.0;
      } else {
        DCHECK(rhs.is_only_nan());
      }
    } else {
      // Both sides have at least one non-special value. We don't have to treat
      // special values here, because nan has been taken care of already and
      // -0.0 is included in min/max.
      can_be_true = can_be_true || lhs.min() <= rhs.max();
      can_be_false = can_be_false || lhs.max() > rhs.min();
    }
    // Consider NaN.
    can_be_false = can_be_false || lhs.has_nan() || rhs.has_nan();
    if (!can_be_true) return Word32Type::Constant(0);
    if (!can_be_false) return Word32Type::Constant(1);
    return Word32Type::Set({0, 1}, zone);
  }
References v8::internal::compiler::turboshaft::WordType< Bits >::Constant(), v8::internal::DCHECK(), v8::internal::compiler::turboshaft::FloatType< Bits >::has_minus_zero(), v8::internal::compiler::turboshaft::FloatType< Bits >::has_nan(), v8::internal::compiler::turboshaft::FloatType< Bits >::is_only_nan(), v8::internal::compiler::turboshaft::FloatType< Bits >::is_only_special_values(), v8::internal::compiler::turboshaft::FloatType< Bits >::max(), v8::internal::compiler::turboshaft::FloatType< Bits >::min(), and v8::internal::compiler::turboshaft::WordType< Bits >::Set().
Referenced by v8::internal::compiler::turboshaft::Typer::TypeFloat32Comparison(), and v8::internal::compiler::turboshaft::Typer::TypeFloat64Comparison().
Max()
template<size_t Bits>
static Type v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Max (type_t l, type_t r, Zone * zone) [inline], [static]
Definition at line 864 of file typer.h.
                                                  {
    if (l.is_only_nan() || r.is_only_nan()) return type_t::NaN();
    bool maybe_nan = l.has_nan() || r.has_nan();
    // In order to ensure monotonicity of the computation below, we additionally
    // pretend +0 is present (for simplicity on both sides).
    bool maybe_minuszero = false;
    if (l.has_minus_zero() && !(r.min() > 0.0)) {
      maybe_minuszero = true;
      l = type_t::LeastUpperBound(l, type_t::Constant(0), zone);
    }
    if (r.has_minus_zero() && !(l.min() > 0.0)) {
      maybe_minuszero = true;
      r = type_t::LeastUpperBound(r, type_t::Constant(0), zone);
    }
    uint32_t special_values = (maybe_nan ? type_t::kNaN : 0) |
                              (maybe_minuszero ? type_t::kMinusZero : 0);
    // If both sides are decently small sets, we produce the product set.
    auto combine = [](float_t a, float_t b) { return std::max(a, b); };
    if (l.is_set() && r.is_set()) {
      // TODO(nicohartmann@): There is a faster way to compute this set.
      auto result = ProductSet(l, r, special_values, zone, combine);
      if (!result.IsInvalid()) return result;
    }
    // Otherwise just construct a range.
    auto [l_min, l_max] = l.minmax();
    auto [r_min, r_max] = r.minmax();
    auto min = std::max(l_min, r_min);
    auto max = std::max(l_max, r_max);
    return Range(min, max, special_values, zone);
  }
References v8::internal::compiler::turboshaft::FloatType< Bits >::Constant(), v8::internal::compiler::turboshaft::FloatType< Bits >::has_minus_zero(), v8::internal::compiler::turboshaft::FloatType< Bits >::has_nan(), v8::internal::compiler::turboshaft::FloatType< Bits >::is_only_nan(), v8::internal::compiler::turboshaft::FloatType< Bits >::is_set(), v8::internal::compiler::turboshaft::FloatType< Bits >::kMinusZero, v8::internal::compiler::turboshaft::FloatType< Bits >::kNaN, v8::internal::compiler::turboshaft::l, v8::internal::compiler::turboshaft::FloatType< Bits >::LeastUpperBound(), v8::internal::compiler::turboshaft::FloatType< Bits >::min(), v8::internal::compiler::turboshaft::FloatType< Bits >::minmax(), v8::internal::compiler::turboshaft::FloatType< Bits >::NaN(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::ProductSet(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Range(), and v8::base::internal::result.
Min()
template<size_t Bits>
static Type v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Min (type_t l, type_t r, Zone * zone) [inline], [static]
Definition at line 829 of file typer.h.
                                                  {
    if (l.is_only_nan() || r.is_only_nan()) return type_t::NaN();
    bool maybe_nan = l.has_nan() || r.has_nan();
    // In order to ensure monotonicity of the computation below, we additionally
    // pretend +0 is present (for simplicity on both sides).
    bool maybe_minuszero = false;
    if (l.has_minus_zero() && !(r.max() < 0.0)) {
      maybe_minuszero = true;
      l = type_t::LeastUpperBound(l, type_t::Constant(0), zone);
    }
    if (r.has_minus_zero() && !(l.max() < 0.0)) {
      maybe_minuszero = true;
      r = type_t::LeastUpperBound(r, type_t::Constant(0), zone);
    }
    uint32_t special_values = (maybe_nan ? type_t::kNaN : 0) |
                              (maybe_minuszero ? type_t::kMinusZero : 0);
    // If both sides are decently small sets, we produce the product set.
    auto combine = [](float_t a, float_t b) { return std::min(a, b); };
    if (l.is_set() && r.is_set()) {
      // TODO(nicohartmann@): There is a faster way to compute this set.
      auto result = ProductSet(l, r, special_values, zone, combine);
      if (!result.IsInvalid()) return result;
    }
    // Otherwise just construct a range.
    auto [l_min, l_max] = l.minmax();
    auto [r_min, r_max] = r.minmax();
    auto min = std::min(l_min, r_min);
    auto max = std::min(l_max, r_max);
    return Range(min, max, special_values, zone);
  }
References v8::internal::compiler::turboshaft::FloatType< Bits >::Constant(), v8::internal::compiler::turboshaft::FloatType< Bits >::has_minus_zero(), v8::internal::compiler::turboshaft::FloatType< Bits >::has_nan(), v8::internal::compiler::turboshaft::FloatType< Bits >::is_only_nan(), v8::internal::compiler::turboshaft::FloatType< Bits >::is_set(), v8::internal::compiler::turboshaft::FloatType< Bits >::kMinusZero, v8::internal::compiler::turboshaft::FloatType< Bits >::kNaN, v8::internal::compiler::turboshaft::l, v8::internal::compiler::turboshaft::FloatType< Bits >::LeastUpperBound(), v8::internal::compiler::turboshaft::FloatType< Bits >::max(), v8::internal::compiler::turboshaft::FloatType< Bits >::minmax(), v8::internal::compiler::turboshaft::FloatType< Bits >::NaN(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::ProductSet(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Range(), and v8::base::internal::result.
Modulus()
template<size_t Bits>
static Type v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Modulus (type_t l, type_t r, Zone * zone) [inline], [static]
Definition at line 777 of file typer.h.
                                                      {
    // Modulus can yield NaN if either {lhs} or {rhs} are NaN, or
    // {lhs} is not finite, or the {rhs} is a zero value.
    if (l.is_only_nan() || r.is_only_nan()) return type_t::NaN();
    bool maybe_nan =
        l.has_nan() || IsZeroish(r) || l.min() == -inf || l.max() == inf;
    // Deal with -0 inputs, only the signbit of {lhs} matters for the result.
    bool maybe_minuszero = l.min() < 0;
    if (l.has_minus_zero()) {
      maybe_minuszero = true;
      l = type_t::LeastUpperBound(l, type_t::Constant(0), zone);
    }
    if (r.has_minus_zero()) {
      r = type_t::LeastUpperBound(r, type_t::Constant(0), zone);
    }
    uint32_t special_values = (maybe_nan ? type_t::kNaN : 0) |
                              (maybe_minuszero ? type_t::kMinusZero : 0);
    // For integer inputs {l} and {r} we can infer a precise type.
    if (IsIntegerSet(l) && IsIntegerSet(r)) {
      auto [l_min, l_max] = l.minmax();
      auto [r_min, r_max] = r.minmax();
      // l % r is:
      // - never greater than abs(l)
      // - never greater than abs(r) - 1
      auto l_abs = std::max(std::abs(l_min), std::abs(l_max));
      auto r_abs = std::max(std::abs(r_min), std::abs(r_max));
      // If rhs is 0, we can only produce NaN.
      if (r_abs == 0) return type_t::NaN();
      r_abs -= 1;
      auto abs = std::min(l_abs, r_abs);
      float_t min = 0.0, max = 0.0;
      if (l_min >= 0.0) {
        // {l} positive.
        max = abs;
      } else if (l_max <= 0.0) {
        // {l} negative.
        min = 0.0 - abs;
      } else {
        // {l} positive or negative.
        min = 0.0 - abs;
        max = abs;
      }
      if (min == max) return Set({min}, special_values, zone);
      return Range(min, max, special_values, zone);
    }
    // Otherwise, we give up.
    return type_t::Any(special_values);
  }
References v8::internal::compiler::turboshaft::Type::Any(), v8::internal::compiler::turboshaft::FloatType< Bits >::Constant(), v8::internal::compiler::turboshaft::FloatType< Bits >::has_minus_zero(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::inf, v8::internal::compiler::turboshaft::FloatType< Bits >::is_only_nan(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::IsIntegerSet(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::IsZeroish(), v8::internal::compiler::turboshaft::FloatType< Bits >::kMinusZero, v8::internal::compiler::turboshaft::FloatType< Bits >::kNaN, v8::internal::compiler::turboshaft::l, v8::internal::compiler::turboshaft::FloatType< Bits >::LeastUpperBound(), v8::internal::compiler::turboshaft::FloatType< Bits >::minmax(), v8::internal::compiler::turboshaft::FloatType< Bits >::NaN(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Range(), and v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Set().
Multiply()
template<size_t Bits>
static Type v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Multiply (type_t l, type_t r, Zone * zone) [inline], [static]
Definition at line 613 of file typer.h.
                                                       {
    // Multiplication propagates NaN:
    // NaN * x = NaN (regardless of sign of x)
    // 0 * Infinity = NaN (regardless of signs)
    if (l.is_only_nan() || r.is_only_nan()) return type_t::NaN();
    bool maybe_nan = l.has_nan() || r.has_nan() ||
                     (IsZeroish(l) && (r.min() == -inf || r.max() == inf)) ||
                     (IsZeroish(r) && (l.min() == -inf || r.max() == inf));
    // Try to rule out -0.
    bool maybe_minuszero = l.has_minus_zero() || r.has_minus_zero() ||
                           (IsZeroish(l) && r.min() < 0.0) ||
                           (IsZeroish(r) && l.min() < 0.0);
    if (l.has_minus_zero()) {
      l = type_t::LeastUpperBound(l, type_t::Constant(0), zone);
    }
    if (r.has_minus_zero()) {
      r = type_t::LeastUpperBound(r, type_t::Constant(0), zone);
    }
    uint32_t special_values = (maybe_nan ? type_t::kNaN : 0) |
                              (maybe_minuszero ? type_t::kMinusZero : 0);
    // If both sides are decently small sets, we produce the product set.
    auto combine = [](float_t a, float_t b) { return a * b; };
    if (l.is_set() && r.is_set()) {
      auto result = ProductSet(l, r, special_values, zone, combine);
      if (!result.IsInvalid()) return result;
    }
    // Otherwise just construct a range.
    auto [l_min, l_max] = l.minmax();
    auto [r_min, r_max] = r.minmax();
    std::array<float_t, 4> results;
    results[0] = l_min * r_min;
    results[1] = l_min * r_max;
    results[2] = l_max * r_min;
    results[3] = l_max * r_max;
    for (int i = 0; i < 4; ++i) {
      if (std::isnan(results[i])) {
        return type_t::Any();
      }
    }
    float_t result_min = array_min(results);
    float_t result_max = array_max(results);
    if (result_min <= 0.0 && 0.0 <= result_max &&
        (l_min < 0.0 || r_min < 0.0)) {
      special_values |= type_t::kMinusZero;
      // Remove -0.
      result_min += 0.0;
      result_max += 0.0;
    }
    // 0 * V8_INFINITY is NaN, regardless of sign
    if (((l_min == -inf || l_max == inf) && (r_min <= 0.0 && 0.0 <= r_max)) ||
        ((r_min == -inf || r_max == inf) && (l_min <= 0.0 && 0.0 <= l_max))) {
      special_values |= type_t::kNaN;
    }
    type_t type = Range(result_min, result_max, special_values, zone);
    return type;
  }
References v8::internal::compiler::turboshaft::Type::Any(), v8::internal::compiler::turboshaft::array_max(), v8::internal::compiler::turboshaft::array_min(), v8::internal::compiler::turboshaft::FloatType< Bits >::Constant(), v8::internal::compiler::turboshaft::FloatType< Bits >::has_minus_zero(), v8::internal::compiler::turboshaft::FloatType< Bits >::has_nan(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::inf, v8::internal::compiler::turboshaft::FloatType< Bits >::is_only_nan(), v8::internal::compiler::turboshaft::FloatType< Bits >::is_set(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::IsZeroish(), v8::internal::compiler::turboshaft::FloatType< Bits >::kMinusZero, v8::internal::compiler::turboshaft::FloatType< Bits >::kNaN, v8::internal::compiler::turboshaft::l, v8::internal::compiler::turboshaft::FloatType< Bits >::LeastUpperBound(), v8::internal::compiler::turboshaft::FloatType< Bits >::max(), v8::internal::compiler::turboshaft::FloatType< Bits >::min(), v8::internal::compiler::turboshaft::FloatType< Bits >::minmax(), v8::internal::compiler::turboshaft::FloatType< Bits >::NaN(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::ProductSet(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Range(), v8::base::internal::result, and v8::internal::tracing::type.
Power()
template<size_t Bits>
static Type v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Power (const type_t & l, const type_t & r, Zone * zone) [inline], [static]
Definition at line 899 of file typer.h.
                                                                  {
    // x ** NaN => Nan.
    if (r.is_only_nan()) return type_t::NaN();
    // x ** +-0 => 1.
    if (r.is_constant(0) || r.is_only_minus_zero()) return type_t::Constant(1);
    if (l.is_only_nan()) {
      // NaN ** 0 => 1.
      if (r.Contains(0) || r.has_minus_zero()) {
        return type_t::Set({1}, type_t::kNaN, zone);
      }
      // NaN ** x => NaN (x != +-0).
      return type_t::NaN();
    }
    bool maybe_nan = l.has_nan() || r.has_nan();
    // +-1 ** +-Infinity => NaN.
    if (r.Contains(-inf) || r.Contains(inf)) {
      if (l.Contains(1) || l.Contains(-1)) maybe_nan = true;
    }
    // a ** b produces NaN if a < 0 && b is fraction.
    if (l.min() < 0.0 && !IsIntegerSet(r)) maybe_nan = true;
    // Precise checks for when the result can be -0 is difficult, because of
    // large (negative) exponents. To be safe we add -0 whenever the left hand
    // side can be negative. We might refine this when necessary.
    bool maybe_minus_zero = l.min() < 0.0 || l.has_minus_zero();
    uint32_t special_values = (maybe_nan ? type_t::kNaN : 0) |
                              (maybe_minus_zero ? type_t::kMinusZero : 0) |
                              l.special_values();
    // If both sides are decently small sets, we produce the product set.
    auto combine = [](float_t a, float_t b) { return std::pow(a, b); };
    if (l.is_set() && r.is_set()) {
      auto result = ProductSet(l, r, special_values, zone, combine);
      if (!result.IsInvalid()) return result;
    }
    // TODO(nicohartmann@): Maybe we can produce a more precise range here.
    return type_t::Any(special_values);
  }
References v8::internal::compiler::turboshaft::Type::Any(), v8::internal::compiler::turboshaft::FloatType< Bits >::Constant(), v8::internal::compiler::turboshaft::FloatType< Bits >::Contains(), v8::internal::compiler::turboshaft::FloatType< Bits >::has_minus_zero(), v8::internal::compiler::turboshaft::FloatType< Bits >::has_nan(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::inf, v8::internal::compiler::turboshaft::FloatType< Bits >::is_constant(), v8::internal::compiler::turboshaft::FloatType< Bits >::is_only_minus_zero(), v8::internal::compiler::turboshaft::FloatType< Bits >::is_only_nan(), v8::internal::compiler::turboshaft::FloatType< Bits >::is_set(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::IsIntegerSet(), v8::internal::compiler::turboshaft::FloatType< Bits >::kMinusZero, v8::internal::compiler::turboshaft::FloatType< Bits >::kNaN, v8::internal::compiler::turboshaft::l, v8::internal::compiler::turboshaft::FloatType< Bits >::NaN(), v8::base::ieee754::legacy::pow(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::ProductSet(), v8::base::internal::result, and v8::internal::compiler::turboshaft::FloatType< Bits >::Set().
ProductSet()
template<size_t Bits>
static Type v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::ProductSet (const type_t & l, const type_t & r, uint32_t special_values, Zone * zone, std::function< float_t(float_t, float_t)> combine) [inline], [static]
Definition at line 471 of file typer.h.
                                                                         {
    DCHECK(l.is_set());
    DCHECK(r.is_set());
    std::vector<float_t> results;
    auto CombineWithLeft = [&](float_t left) {
      for (int j = 0; j < r.set_size(); ++j) {
        results.push_back(combine(left, r.set_element(j)));
      }
      if (r.has_minus_zero()) results.push_back(combine(left, -0.0));
      if (r.has_nan()) results.push_back(combine(left, nan_v<Bits>));
    };
    for (int i = 0; i < l.set_size(); ++i) {
      CombineWithLeft(l.set_element(i));
    }
    if (l.has_minus_zero()) CombineWithLeft(-0.0);
    if (l.has_nan()) CombineWithLeft(nan_v<Bits>);
    if (base::erase_if(results, [](float_t v) { return std::isnan(v); }) > 0) {
      special_values |= type_t::kNaN;
    }
    if (base::erase_if(results, [](float_t v) { return IsMinusZero(v); }) > 0) {
      special_values |= type_t::kMinusZero;
    }
    base::sort(results);
    auto it = std::unique(results.begin(), results.end());
    if (std::distance(results.begin(), it) > kSetThreshold)
      return Type::Invalid();
    results.erase(it, results.end());
    if (results.empty()) return type_t::OnlySpecialValues(special_values);
    return Set(std::move(results), special_values, zone);
  }
References v8::internal::DCHECK(), v8::base::erase_if(), v8::internal::compiler::turboshaft::FloatType< Bits >::has_minus_zero(), v8::internal::compiler::turboshaft::FloatType< Bits >::has_nan(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::Type::Invalid(), v8::internal::compiler::turboshaft::FloatType< Bits >::is_set(), v8::internal::IsMinusZero(), v8::internal::compiler::turboshaft::FloatType< Bits >::kMinusZero, v8::internal::compiler::turboshaft::FloatType< Bits >::kNaN, v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::kSetThreshold, v8::internal::compiler::turboshaft::l, v8::internal::compiler::turboshaft::FloatType< Bits >::OnlySpecialValues(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Set(), v8::internal::compiler::turboshaft::FloatType< Bits >::set_element(), v8::internal::compiler::turboshaft::FloatType< Bits >::set_size(), and v8::base::sort().
Referenced by v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Add(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Divide(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Max(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Min(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Multiply(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Power(), and v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Subtract().
Range()
template<size_t Bits>
static type_t v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Range (float_t min, float_t max, uint32_t special_values, Zone * zone) [inline], [static]
Definition at line 413 of file typer.h.
                                  {
    DCHECK_LE(min, max);
    DCHECK_IMPLIES(detail::is_minus_zero(min),
                   (special_values & type_t::kMinusZero));
    DCHECK_IMPLIES(detail::is_minus_zero(max),
                   (special_values & type_t::kMinusZero));
    if (min == max) return Set({min + float_t{0}}, special_values, zone);
    return type_t::Range(min, max, special_values, zone);
  }
References DCHECK_IMPLIES, DCHECK_LE, v8::internal::compiler::turboshaft::detail::is_minus_zero(), v8::internal::compiler::turboshaft::FloatType< Bits >::kMinusZero, v8::internal::compiler::turboshaft::FloatType< Bits >::Range(), and v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Set().
Referenced by v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Add(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Divide(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Max(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Min(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Modulus(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Multiply(), and v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Subtract().
RestrictionForLessThan_False()
template<size_t Bits>
static std::pair<Type, Type> v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::RestrictionForLessThan_False (const type_t & lhs, const type_t & rhs, Zone * zone) [inline], [static]
Definition at line 1062 of file typer.h.
                                                                        {
    Type restrict_lhs;
    if (rhs.has_nan()) {
      restrict_lhs = type_t::Any();
    } else {
      uint32_t lhs_sv =
          type_t::kNaN |
          (rhs.min() <= 0 ? type_t::kMinusZero : type_t::kNoSpecialValues);
      restrict_lhs = type_t::Range(rhs.min(), inf, lhs_sv, zone);
    }
    Type restrict_rhs;
    if (lhs.has_nan()) {
      restrict_rhs = type_t::Any();
    } else {
      uint32_t rhs_sv =
          type_t::kNaN |
          (lhs.max() >= 0 ? type_t::kMinusZero : type_t::kNoSpecialValues);
      restrict_rhs = type_t::Range(-inf, lhs.max(), rhs_sv, zone);
    }
    return {restrict_lhs, restrict_rhs};
  }
References v8::internal::compiler::turboshaft::Type::Any(), v8::internal::compiler::turboshaft::FloatType< Bits >::has_nan(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::inf, v8::internal::compiler::turboshaft::FloatType< Bits >::kMinusZero, v8::internal::compiler::turboshaft::FloatType< Bits >::kNaN, v8::internal::compiler::turboshaft::FloatType< Bits >::kNoSpecialValues, v8::internal::compiler::turboshaft::FloatType< Bits >::max(), v8::internal::compiler::turboshaft::FloatType< Bits >::min(), and v8::internal::compiler::turboshaft::FloatType< Bits >::Range().
RestrictionForLessThan_True()
template<size_t Bits>
static std::pair<Type, Type> v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::RestrictionForLessThan_True (const type_t & lhs, const type_t & rhs, Zone * zone) [inline], [static]
Definition at line 1028 of file typer.h.
                                                                       {
    // If either side is only NaN, this comparison can never be true.
    if (lhs.is_only_nan() || rhs.is_only_nan()) {
      return {Type::None(), Type::None()};
    }
    Type restrict_lhs;
    if (rhs.max() == -inf) {
      // There is no value for lhs that could make (lhs < -inf) true.
      restrict_lhs = Type::None();
    } else {
      const auto max = next_smaller(rhs.max());
      uint32_t sv = max >= 0 ? type_t::kMinusZero : type_t::kNoSpecialValues;
      restrict_lhs = type_t::Range(-inf, max, sv, zone);
    }
    Type restrict_rhs;
    if (lhs.min() == inf) {
      // There is no value for rhs that could make (inf < rhs) true.
      restrict_rhs = Type::None();
    } else {
      const auto min = next_larger(lhs.min());
      uint32_t sv = min <= 0 ? type_t::kMinusZero : type_t::kNoSpecialValues;
      restrict_rhs = type_t::Range(min, inf, sv, zone);
    }
    return {restrict_lhs, restrict_rhs};
  }
References v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::inf, v8::internal::compiler::turboshaft::FloatType< Bits >::is_only_nan(), v8::internal::compiler::turboshaft::FloatType< Bits >::kMinusZero, v8::internal::compiler::turboshaft::FloatType< Bits >::kNoSpecialValues, v8::internal::compiler::turboshaft::FloatType< Bits >::max(), v8::internal::compiler::turboshaft::FloatType< Bits >::min(), v8::internal::compiler::turboshaft::Type::None(), and v8::internal::compiler::turboshaft::FloatType< Bits >::Range().
RestrictionForLessThanOrEqual_False()
template<size_t Bits>
static std::pair<Type, Type> v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::RestrictionForLessThanOrEqual_False (const type_t & lhs, const type_t & rhs, Zone * zone) [inline], [static]
Definition at line 1110 of file typer.h.
                                                        {
    Type restrict_lhs;
    if (rhs.has_nan()) {
      restrict_lhs = type_t::Any();
    } else if (rhs.min() == inf) {
      // The only value for lhs that could make (lhs <= inf) false is NaN.
      restrict_lhs = type_t::NaN();
    } else {
      const auto min = next_larger(rhs.min());
      uint32_t sv = type_t::kNaN |
                    (min <= 0 ? type_t::kMinusZero : type_t::kNoSpecialValues);
      restrict_lhs = type_t::Range(min, inf, sv, zone);
    }
    Type restrict_rhs;
    if (lhs.has_nan()) {
      restrict_rhs = type_t::Any();
    } else if (lhs.max() == -inf) {
      // The only value for rhs that could make (-inf <= rhs) false is NaN.
      restrict_rhs = type_t::NaN();
    } else {
      const auto max = next_smaller(lhs.max());
      uint32_t sv = type_t::kNaN |
                    (max >= 0 ? type_t::kMinusZero : type_t::kNoSpecialValues);
      restrict_rhs = type_t::Range(-inf, max, sv, zone);
    }
    return {restrict_lhs, restrict_rhs};
  }
References v8::internal::compiler::turboshaft::Type::Any(), v8::internal::compiler::turboshaft::FloatType< Bits >::has_nan(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::inf, v8::internal::compiler::turboshaft::FloatType< Bits >::kMinusZero, v8::internal::compiler::turboshaft::FloatType< Bits >::kNaN, v8::internal::compiler::turboshaft::FloatType< Bits >::kNoSpecialValues, v8::internal::compiler::turboshaft::FloatType< Bits >::max(), v8::internal::compiler::turboshaft::FloatType< Bits >::min(), v8::internal::compiler::turboshaft::FloatType< Bits >::NaN(), and v8::internal::compiler::turboshaft::FloatType< Bits >::Range().
RestrictionForLessThanOrEqual_True()
template<size_t Bits>
static std::pair<Type, Type> v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::RestrictionForLessThanOrEqual_True (const type_t & lhs, const type_t & rhs, Zone * zone) [inline], [static]
Definition at line 1092 of file typer.h.
                                                        {
    // If either side is only NaN, this comparison can never be true.
    if (lhs.is_only_nan() || rhs.is_only_nan()) {
      return {Type::None(), Type::None()};
    }
    uint32_t lhs_sv =
        rhs.max() >= 0 ? type_t::kMinusZero : type_t::kNoSpecialValues;
    uint32_t rhs_sv =
        lhs.min() <= 0 ? type_t::kMinusZero : type_t::kNoSpecialValues;
    return {type_t::Range(-inf, rhs.max(), lhs_sv, zone),
            type_t::Range(lhs.min(), inf, rhs_sv, zone)};
  }
References v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::inf, v8::internal::compiler::turboshaft::FloatType< Bits >::is_only_nan(), v8::internal::compiler::turboshaft::FloatType< Bits >::kMinusZero, v8::internal::compiler::turboshaft::FloatType< Bits >::kNoSpecialValues, v8::internal::compiler::turboshaft::FloatType< Bits >::max(), v8::internal::compiler::turboshaft::FloatType< Bits >::min(), v8::internal::compiler::turboshaft::Type::None(), and v8::internal::compiler::turboshaft::FloatType< Bits >::Range().
Set()
template<size_t Bits>
static type_t v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Set (std::vector< float_t > elements, uint32_t special_values, Zone * zone) [inline], [static]
Definition at line 424 of file typer.h.
                                {
    base::sort(elements);
    elements.erase(std::unique(elements.begin(), elements.end()),
                   elements.end());
    if (base::erase_if(elements, [](float_t v) { return std::isnan(v); }) > 0) {
      special_values |= type_t::kNaN;
    }
    if (base::erase_if(elements, [](float_t v) { return IsMinusZero(v); }) >
        0) {
      special_values |= type_t::kMinusZero;
    }
    if (elements.empty()) {
      DCHECK_NE(0, special_values);
      return type_t::OnlySpecialValues(special_values);
    }
    return type_t::Set(elements, special_values, zone);
  }
References DCHECK_NE, v8::base::erase_if(), v8::internal::IsMinusZero(), v8::internal::compiler::turboshaft::FloatType< Bits >::kMinusZero, v8::internal::compiler::turboshaft::FloatType< Bits >::kNaN, v8::internal::compiler::turboshaft::FloatType< Bits >::OnlySpecialValues(), v8::internal::compiler::turboshaft::FloatType< Bits >::Set(), and v8::base::sort().
Referenced by v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Modulus(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::ProductSet(), and v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Range().
Subtract()
template<size_t Bits>
static Type v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Subtract (type_t l, type_t r, Zone * zone) [inline], [static]
Definition at line 561 of file typer.h.
                                                       {
    // Subtraction can return NaN if either input can be NaN or we try to
    // compute the sum of two infinities of opposite sign.
    if (l.is_only_nan() || r.is_only_nan()) return type_t::NaN();
    bool maybe_nan = l.has_nan() || r.has_nan();
    // Subtraction can yield minus zero if {lhs} can be minus zero and {rhs}
    // can be zero.
    bool maybe_minuszero = false;
    if (l.has_minus_zero()) {
      l = type_t::LeastUpperBound(l, type_t::Constant(0), zone);
      maybe_minuszero = r.Contains(0);
    }
    if (r.has_minus_zero()) {
      r = type_t::LeastUpperBound(r, type_t::Constant(0), zone);
    }
    uint32_t special_values = (maybe_nan ? type_t::kNaN : 0) |
                              (maybe_minuszero ? type_t::kMinusZero : 0);
    // If both sides are decently small sets, we produce the product set.
    auto combine = [](float_t a, float_t b) { return a - b; };
    if (l.is_set() && r.is_set()) {
      auto result = ProductSet(l, r, special_values, zone, combine);
      if (!result.IsInvalid()) return result;
    }
    // Otherwise just construct a range.
    auto [l_min, l_max] = l.minmax();
    auto [r_min, r_max] = r.minmax();
    std::array<float_t, 4> results;
    results[0] = l_min - r_min;
    results[1] = l_min - r_max;
    results[2] = l_max - r_min;
    results[3] = l_max - r_max;
    int nans = 0;
    for (int i = 0; i < 4; ++i) {
      if (std::isnan(results[i])) ++nans;
    }
    if (nans > 0) {
      special_values |= type_t::kNaN;
      if (nans >= 4) {
        // All combinations of inputs produce NaN.
        return type_t::NaN();
      }
    }
    const float_t result_min = array_min(results);
    const float_t result_max = array_max(results);
    return Range(result_min, result_max, special_values, zone);
  }
References v8::internal::compiler::turboshaft::array_max(), v8::internal::compiler::turboshaft::array_min(), v8::internal::compiler::turboshaft::FloatType< Bits >::Constant(), v8::internal::compiler::turboshaft::FloatType< Bits >::Contains(), v8::internal::compiler::turboshaft::FloatType< Bits >::has_minus_zero(), v8::internal::compiler::turboshaft::FloatType< Bits >::has_nan(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::FloatType< Bits >::is_only_nan(), v8::internal::compiler::turboshaft::FloatType< Bits >::is_set(), v8::internal::compiler::turboshaft::FloatType< Bits >::kMinusZero, v8::internal::compiler::turboshaft::FloatType< Bits >::kNaN, v8::internal::compiler::turboshaft::l, v8::internal::compiler::turboshaft::FloatType< Bits >::LeastUpperBound(), v8::internal::compiler::turboshaft::FloatType< Bits >::minmax(), v8::internal::compiler::turboshaft::FloatType< Bits >::NaN(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::ProductSet(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Range(), and v8::base::internal::result.
UnsignedLessThanOrEqual()
template<size_t Bits>
static Word32Type v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::UnsignedLessThanOrEqual (const type_t & lhs, const type_t & rhs, Zone * zone) [inline], [static]
Definition at line 1014 of file typer.h.
                                                                           {
    bool can_be_true = lhs.unsigned_min() <= rhs.unsigned_max();
    bool can_be_false = lhs.unsigned_max() > rhs.unsigned_min();
    if (!can_be_true) return Word32Type::Constant(0);
    if (!can_be_false) return Word32Type::Constant(1);
    return Word32Type::Set({0, 1}, zone);
  }
References v8::internal::compiler::turboshaft::WordType< Bits >::Constant(), and v8::internal::compiler::turboshaft::WordType< Bits >::Set().
Member Data Documentation
inf
template<size_t Bits>
constexpr float_t v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::inf = std::numeric_limits<float_t>::infinity() [static], [constexpr]
Definition at line 410 of file typer.h.
Referenced by v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Divide(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::IsIntegerSet(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Modulus(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Multiply(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Power(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::RestrictionForLessThan_False(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::RestrictionForLessThan_True(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::RestrictionForLessThanOrEqual_False(), and v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::RestrictionForLessThanOrEqual_True().
kSetThreshold
template<size_t Bits>
constexpr int v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::kSetThreshold = type_t::kMaxSetSize [static], [constexpr]
Definition at line 411 of file typer.h.
Referenced by v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::ProductSet().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/typer.h