v8::internal::SourcePositionInfo Struct Reference
#include <source-position.h>
Public Member Functions
SourcePositionInfo (Isolate *isolate, SourcePosition pos, DirectHandle< SharedFunctionInfo > f)
Public Attributes
SourcePosition position
IndirectHandle< SharedFunctionInfo > shared
IndirectHandle< Script > script
int line = -1
int column = -1
Detailed Description
Definition at line 183 of file source-position.h.
Constructor & Destructor Documentation
SourcePositionInfo()
v8::internal::SourcePositionInfo::SourcePositionInfo (Isolate * isolate, SourcePosition pos, DirectHandle< SharedFunctionInfo > f)
Definition at line 151 of file source-position.cc.
    : position(pos), shared(indirect_handle(sfi, isolate)) {
  {
    DisallowGarbageCollection no_gc;
    if (sfi.is_null()) return;
    Tagged<Object> maybe_script = sfi->script();
    if (!IsScript(maybe_script)) return;
    script = handle(Cast<Script>(maybe_script), isolate);
  }
  Script::PositionInfo info;
  if (Script::GetPositionInfo(script, pos.ScriptOffset(), &info)) {
    line = info.line;
    column = info.column;
  }
}
References column, v8::internal::Script::PositionInfo::column, v8::internal::Script::GetPositionInfo(), v8::internal::handle(), v8::internal::DirectHandle< T >::is_null(), line, v8::internal::Script::PositionInfo::line, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, script, and v8::internal::SourcePosition::ScriptOffset().
Member Data Documentation
column
int v8::internal::SourcePositionInfo::column = -1
Definition at line 191 of file source-position.h.
Referenced by v8::internal::operator<<(), and SourcePositionInfo().
line
int v8::internal::SourcePositionInfo::line = -1
Definition at line 190 of file source-position.h.
Referenced by v8::internal::operator<<(), and SourcePositionInfo().
position
SourcePosition v8::internal::SourcePositionInfo::position
Definition at line 187 of file source-position.h.
script
IndirectHandle<Script> v8::internal::SourcePositionInfo::script
Definition at line 189 of file source-position.h.
Referenced by v8::internal::operator<<(), and SourcePositionInfo().
shared
IndirectHandle<SharedFunctionInfo> v8::internal::SourcePositionInfo::shared
Definition at line 188 of file source-position.h.
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/codegen/source-position.h
/mnt/V8SourceCode/src/codegen/source-position.cc