v8::base::internal::CheckedNumeric< T >::Wrapper< Src > Struct Template Reference
Static Public Member Functions
static constexpr bool is_valid (Src)
static constexpr Src value (Src value)
Detailed Description
template<typename T>
template<typename Src>
struct v8::base::internal::CheckedNumeric< T >::Wrapper< Src >
Definition at line 253 of file checked_math.h.
Member Function Documentation
is_valid()
template<typename T >
template<typename Src >
static constexpr bool v8::base::internal::CheckedNumeric< T >::Wrapper< Src >::is_valid (Src) [inline], [static], [constexpr]
Definition at line 254 of file checked_math.h.
{ return true; }
Referenced by v8::base::internal::CheckedNumeric< T >::MathOp().
value()
template<typename T >
template<typename Src >
static constexpr Src v8::base::internal::CheckedNumeric< T >::Wrapper< Src >::value (Src value) [inline], [static], [constexpr]
Definition at line 255 of file checked_math.h.
{ return value; }
References v8::base::internal::CheckedNumeric< T >::Wrapper< Src >::value().
Referenced by v8::base::internal::CheckedNumeric< T >::Wrapper< Src >::value().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/base/numerics/checked_math.h