cppgc::internal::TraceTraitBase< T > Struct Template Reference
Trait specifying how the garbage collector processes an object of type T.
#include <trace-trait.h>
Static Public Member Functions
static TraceDescriptor GetTraceDescriptor (const void *self)
Accessor for retrieving a TraceDescriptor to process an object of type T.
static void Trace (Visitor *visitor, const void *self)
Function invoking the tracing for an object of type T.
Detailed Description
template<typename T>
struct cppgc::internal::TraceTraitBase< T >
Trait specifying how the garbage collector processes an object of type T.
Advanced users may override handling by creating a specialization for their type.
Definition at line 76 of file trace-trait.h.
Member Function Documentation
GetTraceDescriptor()
template<typename T >
static TraceDescriptor cppgc::internal::TraceTraitBase< T >::GetTraceDescriptor (const void * self) [inline], [static]
Accessor for retrieving a TraceDescriptor to process an object of type T.
Parameters
self The object to be processed.
Returns
a TraceDescriptor to process the object.
Definition at line 85 of file trace-trait.h.
                                                              {
    return internal::TraceTraitImpl<T>::GetTraceDescriptor(
        static_cast<const T*>(self));
  }
Referenced by cppgc::Visitor::TraceEphemeron().
Trace()
template<typename T >
static void cppgc::internal::TraceTraitBase< T >::Trace (Visitor * visitor, const void * self) [inline], [static]
Function invoking the tracing for an object of type T.
Parameters
visitor The visitor to dispatch to.
self The object to invoke tracing on.
Definition at line 96 of file trace-trait.h.
                                                        {
    static_cast<const T*>(self)->Trace(visitor);
  }
Referenced by cppgc::Visitor::Trace(), and cppgc::Visitor::TraceMultiple().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/include/cppgc/trace-trait.h