v8::internal::compiler::IntMatcher< T, kOpcode > Struct Template Reference
#include <node-matchers.h>
Public Member Functions
IntMatcher (Node *node)
bool Is (const T &value) const
bool IsInRange (const T &low, const T &high) const
bool IsMultipleOf (T n) const
bool IsPowerOf2 () const
bool IsNegativePowerOf2 () const
bool IsNegative () const
Additional Inherited Members
Detailed Description
template<typename T, IrOpcode::Value kOpcode>
struct v8::internal::compiler::IntMatcher< T, kOpcode >
Definition at line 137 of file node-matchers.h.
Constructor & Destructor Documentation
IntMatcher()
template<typename T , IrOpcode::Value kOpcode>
v8::internal::compiler::IntMatcher< T, kOpcode >::IntMatcher (Node * node) [inline], [explicit]
Definition at line 138 of file node-matchers.h.
: ValueMatcher<T, kOpcode>(node) {}
Member Function Documentation
Is()
template<typename T , IrOpcode::Value kOpcode>
bool v8::internal::compiler::IntMatcher< T, kOpcode >::Is (const T & value) const [inline]
Definition at line 140 of file node-matchers.h.
                                {
    return this->HasResolvedValue() && this->ResolvedValue() == value;
  }
References v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), v8::internal::compiler::ValueMatcher< T, kOpcode >::ResolvedValue(), and v8::internal::value.
Referenced by v8::internal::compiler::RawMachineAssembler::IsMapOffsetConstant(), v8::internal::compiler::RawMachineAssembler::IsMapOffsetConstantMinusTag(), v8::internal::compiler::SimplifiedOperatorReducer::Reduce(), v8::internal::compiler::MachineOperatorReducer::Reduce(), and v8::internal::compiler::BranchElimination::TryEliminateBranchWithPhiCondition().
IsInRange()
template<typename T , IrOpcode::Value kOpcode>
bool v8::internal::compiler::IntMatcher< T, kOpcode >::IsInRange (const T & low, const T & high) const [inline]
Definition at line 143 of file node-matchers.h.
                                                    {
    return this->HasResolvedValue() &&
           base::IsInRange(this->ResolvedValue(), low, high);
  }
References v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), and v8::internal::compiler::ValueMatcher< T, kOpcode >::ResolvedValue().
Referenced by v8::internal::compiler::MemoryLowering::ReduceAllocateRaw(), and v8::internal::compiler::CodeAssembler::TryToInt32Constant().
IsMultipleOf()
template<typename T , IrOpcode::Value kOpcode>
bool v8::internal::compiler::IntMatcher< T, kOpcode >::IsMultipleOf (T n) const [inline]
Definition at line 147 of file node-matchers.h.
                               {
    return this->HasResolvedValue() && (this->ResolvedValue() % n) == 0;
  }
References v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), and v8::internal::compiler::ValueMatcher< T, kOpcode >::ResolvedValue().
IsNegative()
template<typename T , IrOpcode::Value kOpcode>
bool v8::internal::compiler::IntMatcher< T, kOpcode >::IsNegative () const [inline]
Definition at line 159 of file node-matchers.h.
                          {
    return this->HasResolvedValue() && this->ResolvedValue() < 0;
  }
References v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), and v8::internal::compiler::ValueMatcher< T, kOpcode >::ResolvedValue().
IsNegativePowerOf2()
template<typename T , IrOpcode::Value kOpcode>
bool v8::internal::compiler::IntMatcher< T, kOpcode >::IsNegativePowerOf2 () const [inline]
Definition at line 154 of file node-matchers.h.
                                  {
    return this->HasResolvedValue() && this->ResolvedValue() < 0 &&
           ((this->ResolvedValue() == std::numeric_limits<T>::min()) ||
            (-this->ResolvedValue() & (-this->ResolvedValue() - 1)) == 0);
  }
References v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), and v8::internal::compiler::ValueMatcher< T, kOpcode >::ResolvedValue().
IsPowerOf2()
template<typename T , IrOpcode::Value kOpcode>
bool v8::internal::compiler::IntMatcher< T, kOpcode >::IsPowerOf2 () const [inline]
Definition at line 150 of file node-matchers.h.
                          {
    return this->HasResolvedValue() && this->ResolvedValue() > 0 &&
           (this->ResolvedValue() & (this->ResolvedValue() - 1)) == 0;
  }
References v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), and v8::internal::compiler::ValueMatcher< T, kOpcode >::ResolvedValue().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/node-matchers.h