v8::internal::compiler::turboshaft::MemoryAnalyzer Struct Reference
#include <memory-optimization-reducer.h>
Classes
struct BlockState
Public Types
enum class AllocationFolding { kDoAllocationFolding
, kDontAllocationFolding
 }
Public Member Functions
MemoryAnalyzer (PipelineData *data, Zone *phase_zone, const Graph &input_graph, AllocationFolding allocation_folding, bool is_wasm)
bool IsPartOfLastAllocation (const Operation *op)
bool SkipWriteBarrier (const StoreOp &store)
bool IsFoldedAllocation (V< AnyOrNone > op)
std::optional< uint32_t > ReservedSize (V< AnyOrNone > alloc)
void Run ()
void Process (const Operation &op)
void ProcessBlockTerminator (const Operation &op)
void ProcessAllocation (const AllocateOp &alloc)
void ProcessStore (const StoreOp &store)
void MergeCurrentStateIntoSuccessor (const Block *successor)
Public Attributes
PipelineData * data
Zone * phase_zone
const Graph & input_graph
Isolate * isolate_ = data->isolate()
AllocationFolding allocation_folding
bool is_wasm
FixedBlockSidetable< std::optional< BlockState > > block_states
ZoneAbslFlatHashMap< const AllocateOp *, const AllocateOp * > folded_into
ZoneAbslFlatHashSet< V< None > > skipped_write_barriers {phase_zone}
ZoneAbslFlatHashMap< const AllocateOp *, uint32_t > reserved_size {phase_zone}
BlockIndex current_block = BlockIndex(0)
BlockState state
TurboshaftPipelineKind pipeline_kind = data->pipeline_kind()
Detailed Description
Definition at line 93 of file memory-optimization-reducer.h.
Member Enumeration Documentation
AllocationFolding
enum v8::internal::compiler::turboshaft::MemoryAnalyzer::AllocationFolding [strong]
Enumerator
kDoAllocationFolding
kDontAllocationFolding
Definition at line 94 of file memory-optimization-reducer.h.
{ kDoAllocationFolding, kDontAllocationFolding };
Constructor & Destructor Documentation
MemoryAnalyzer()
v8::internal::compiler::turboshaft::MemoryAnalyzer::MemoryAnalyzer (PipelineData * data, Zone * phase_zone, const Graph & input_graph, AllocationFolding allocation_folding, bool is_wasm) [inline]
Definition at line 102 of file memory-optimization-reducer.h.
      : data(data),
        phase_zone(phase_zone),
        input_graph(input_graph),
        allocation_folding(allocation_folding),
        is_wasm(is_wasm) {}
Member Function Documentation
IsFoldedAllocation()
bool v8::internal::compiler::turboshaft::MemoryAnalyzer::IsFoldedAllocation (V< AnyOrNone > op) [inline]
Definition at line 163 of file memory-optimization-reducer.h.
                                           {
    return folded_into.count(
        input_graph.Get(op).template TryCast<AllocateOp>());
  }
References folded_into, v8::internal::compiler::turboshaft::Graph::Get(), and input_graph.
IsPartOfLastAllocation()
bool v8::internal::compiler::turboshaft::MemoryAnalyzer::IsPartOfLastAllocation (const Operation * op) [inline]
Definition at line 129 of file memory-optimization-reducer.h.
                                                   {
    const AllocateOp* allocation = UnwrapAllocate(&input_graph, op);
    if (allocation == nullptr) return false;
    if (state.last_allocation == nullptr) return false;
    if (state.last_allocation->type != AllocationType::kYoung) return false;
    if (state.last_allocation == allocation) return true;
    auto it = folded_into.find(allocation);
    if (it == folded_into.end()) return false;
    return it->second == state.last_allocation;
  }
References folded_into, input_graph, v8::internal::kYoung, v8::internal::compiler::turboshaft::MemoryAnalyzer::BlockState::last_allocation, state, v8::internal::compiler::turboshaft::AllocateOp::type, and v8::internal::compiler::turboshaft::UnwrapAllocate().
Referenced by SkipWriteBarrier().
MergeCurrentStateIntoSuccessor()
void v8::internal::compiler::turboshaft::MemoryAnalyzer::MergeCurrentStateIntoSuccessor (const Block * successor)
Definition at line 163 of file memory-optimization-reducer.cc.
                                                                          {
  std::optional<BlockState>& target_state = block_states[successor->index()];
  if (!target_state.has_value()) {
    target_state = state;
    return;
  }
  // All predecessors need to have the same last allocation for us to continue
  // folding into it.
  if (target_state->last_allocation != state.last_allocation) {
    target_state = BlockState();
    return;
  }
  // We take the maximum allocation size of all predecessors. If the size is
  // unknown because it is dynamic, we remember the allocation to eliminate
  // write barriers.
  if (target_state->reserved_size.has_value() &&
      state.reserved_size.has_value()) {
    target_state->reserved_size =
        std::max(*target_state->reserved_size, *state.reserved_size);
  } else {
    target_state->reserved_size = std::nullopt;
  }
}
References block_states, v8::internal::compiler::turboshaft::Block::index(), v8::internal::compiler::turboshaft::MemoryAnalyzer::BlockState::last_allocation, v8::internal::compiler::turboshaft::MemoryAnalyzer::BlockState::reserved_size, and state.
Referenced by ProcessBlockTerminator().
Process()
void v8::internal::compiler::turboshaft::MemoryAnalyzer::Process (const Operation & op)
Definition at line 56 of file memory-optimization-reducer.cc.
                                                {
  if (ShouldSkipOperation(op)) {
    return;
  }
  if (auto* alloc = op.TryCast<AllocateOp>()) {
    ProcessAllocation(*alloc);
    return;
  }
  if (auto* store = op.TryCast<StoreOp>()) {
    ProcessStore(*store);
    return;
  }
  if (op.Effects().can_allocate) {
    state = BlockState();
  }
  if (op.IsBlockTerminator()) {
    ProcessBlockTerminator(op);
  }
}
References v8::internal::compiler::turboshaft::OpEffects::can_allocate, v8::internal::compiler::turboshaft::Operation::Effects(), v8::internal::compiler::turboshaft::Operation::IsBlockTerminator(), ProcessAllocation(), ProcessBlockTerminator(), ProcessStore(), v8::internal::compiler::turboshaft::ShouldSkipOperation(), state, store(), and v8::internal::compiler::turboshaft::Operation::TryCast().
Referenced by Run().
ProcessAllocation()
void v8::internal::compiler::turboshaft::MemoryAnalyzer::ProcessAllocation (const AllocateOp & alloc)
Definition at line 117 of file memory-optimization-reducer.cc.
                                                              {
  if (ShouldSkipOptimizationStep()) return;
  std::optional<uint64_t> new_size;
  if (auto* size =
          input_graph.Get(alloc.size()).template TryCast<ConstantOp>()) {
    new_size = size->integral();
  }
  // If the new allocation has a static size and is of the same type, then we
  // can fold it into the previous allocation unless the folded allocation would
  // exceed `kMaxRegularHeapObjectSize`.
  if (allocation_folding == AllocationFolding::kDoAllocationFolding &&
      state.last_allocation && new_size.has_value() &&
      state.reserved_size.has_value() &&
      alloc.type == state.last_allocation->type &&
      alloc.type != AllocationType::kSharedOld &&
      *new_size <= kMaxRegularHeapObjectSize - *state.reserved_size) {
    state.reserved_size =
        static_cast<uint32_t>(*state.reserved_size + *new_size);
    folded_into[&alloc] = state.last_allocation;
    uint32_t& max_reserved_size = reserved_size[state.last_allocation];
    max_reserved_size = std::max(max_reserved_size, *state.reserved_size);
    return;
  }
  state.last_allocation = &alloc;
  state.reserved_size = std::nullopt;
  if (new_size.has_value() && *new_size <= kMaxRegularHeapObjectSize) {
    state.reserved_size = static_cast<uint32_t>(*new_size);
  }
  // We might be re-visiting the current block. In this case, we need to remove
  // an allocation that can no longer be folded.
  reserved_size.erase(&alloc);
  folded_into.erase(&alloc);
}
References allocation_folding, folded_into, v8::internal::compiler::turboshaft::Graph::Get(), input_graph, kDoAllocationFolding, v8::internal::kMaxRegularHeapObjectSize, v8::internal::kSharedOld, v8::internal::compiler::turboshaft::MemoryAnalyzer::BlockState::last_allocation, v8::internal::compiler::turboshaft::MemoryAnalyzer::BlockState::reserved_size, reserved_size, v8::internal::compiler::turboshaft::ShouldSkipOptimizationStep(), v8::internal::compiler::turboshaft::AllocateOp::size(), size(), state, and v8::internal::compiler::turboshaft::AllocateOp::type.
Referenced by Process().
ProcessBlockTerminator()
void v8::internal::compiler::turboshaft::MemoryAnalyzer::ProcessBlockTerminator (const Operation & op)
Definition at line 80 of file memory-optimization-reducer.cc.
                                                                       {
  if (auto* goto_op = terminator.TryCast<GotoOp>()) {
    if (input_graph.IsLoopBackedge(*goto_op)) {
      std::optional<BlockState>& target_state =
          block_states[goto_op->destination->index()];
      BlockState old_state = *target_state;
      MergeCurrentStateIntoSuccessor(goto_op->destination);
      if (old_state != *target_state) {
        // We can never fold allocations inside of the loop into an
        // allocation before the loop, since this leads to unbounded
        // allocation size. An unknown `reserved_size` will prevent adding
        // allocations inside of the loop.
        target_state->reserved_size = std::nullopt;
        // Redo the analysis from the beginning of the loop.
        current_block = goto_op->destination->index();
      }
      return;
    } else if (goto_op->destination->IsLoop()) {
      // Look ahead to detect allocating loops earlier, avoiding a wrong
      // speculation resulting in processing the loop twice.
      for (const Operation& op :
           input_graph.operations(*goto_op->destination)) {
        if (op.Effects().can_allocate && !ShouldSkipOperation(op)) {
          state = BlockState();
          break;
        }
      }
    }
  }
  for (Block* successor : SuccessorBlocks(terminator)) {
    MergeCurrentStateIntoSuccessor(successor);
  }
}
References block_states, current_block, input_graph, v8::internal::compiler::turboshaft::Graph::IsLoopBackedge(), MergeCurrentStateIntoSuccessor(), v8::internal::compiler::turboshaft::Graph::operations(), v8::internal::compiler::turboshaft::ShouldSkipOperation(), state, v8::internal::compiler::turboshaft::SuccessorBlocks(), and v8::internal::compiler::turboshaft::Operation::TryCast().
Referenced by Process().
ProcessStore()
void v8::internal::compiler::turboshaft::MemoryAnalyzer::ProcessStore (const StoreOp & store)
Definition at line 151 of file memory-optimization-reducer.cc.
                                                      {
  V<None> store_op_index = input_graph.Index(store);
  if (SkipWriteBarrier(store)) {
    skipped_write_barriers.insert(store_op_index);
  } else {
    // We might be re-visiting the current block. In this case, we need to
    // still update the information.
    DCHECK_NE(store.write_barrier, WriteBarrierKind::kAssertNoWriteBarrier);
    skipped_write_barriers.erase(store_op_index);
  }
}
References DCHECK_NE, v8::internal::compiler::turboshaft::Graph::Index(), input_graph, v8::internal::compiler::kAssertNoWriteBarrier, skipped_write_barriers, SkipWriteBarrier(), and store().
Referenced by Process().
ReservedSize()
std::optional<uint32_t> v8::internal::compiler::turboshaft::MemoryAnalyzer::ReservedSize (V< AnyOrNone > alloc) [inline]
Definition at line 168 of file memory-optimization-reducer.h.
                                                         {
    if (auto it = reserved_size.find(
            input_graph.Get(alloc).template TryCast<AllocateOp>());
        it != reserved_size.end()) {
      return it->second;
    }
    return std::nullopt;
  }
References v8::internal::compiler::turboshaft::Graph::Get(), input_graph, and reserved_size.
Run()
void v8::internal::compiler::turboshaft::MemoryAnalyzer::Run ()
Definition at line 40 of file memory-optimization-reducer.cc.
                         {
  block_states[current_block] = BlockState{};
  BlockIndex end = BlockIndex(input_graph.block_count());
  while (current_block < end) {
    state = *block_states[current_block];
    auto operations_range =
        input_graph.operations(input_graph.Get(current_block));
    // Set the next block index here already, to allow it to be changed if
    // needed.
    current_block = BlockIndex(current_block.id() + 1);
    for (const Operation& op : operations_range) {
      Process(op);
    }
  }
}
References v8::internal::compiler::turboshaft::Graph::block_count(), block_states, current_block, v8::internal::compiler::end(), v8::internal::compiler::turboshaft::Graph::Get(), v8::internal::compiler::turboshaft::BlockIndex::id(), input_graph, v8::internal::compiler::turboshaft::Graph::operations(), Process(), and state.
SkipWriteBarrier()
bool v8::internal::compiler::turboshaft::MemoryAnalyzer::SkipWriteBarrier (const StoreOp & store) [inline]
Definition at line 140 of file memory-optimization-reducer.h.
                                              {
    const Operation& object = input_graph.Get(store.base());
    const Operation& value = input_graph.Get(store.value());
    WriteBarrierKind write_barrier_kind = store.write_barrier;
    if (write_barrier_kind != WriteBarrierKind::kAssertNoWriteBarrier) {
      // If we have {kAssertNoWriteBarrier}, we cannot skip elimination
      // checks.
      if (ShouldSkipOptimizationStep()) return false;
    }
    if (IsPartOfLastAllocation(&object)) return true;
    if (!ValueNeedsWriteBarrier(&input_graph, value, isolate_)) return true;
    if (v8_flags.disable_write_barriers) return true;
    if (write_barrier_kind == WriteBarrierKind::kAssertNoWriteBarrier) {
      std::stringstream str;
      str << "MemoryOptimizationReducer could not remove write barrier for "
             "operation\n #"
          << input_graph.Index(store) << ": " << store.ToString() << "\n";
      FATAL("%s", str.str().c_str());
    }
    return false;
  }
References FATAL, v8::internal::compiler::turboshaft::Graph::Get(), v8::internal::compiler::turboshaft::Graph::Index(), input_graph, isolate_, IsPartOfLastAllocation(), v8::internal::compiler::kAssertNoWriteBarrier, v8::internal::compiler::turboshaft::ShouldSkipOptimizationStep(), store(), v8::internal::v8_flags, v8::internal::value, and v8::internal::compiler::turboshaft::ValueNeedsWriteBarrier().
Referenced by ProcessStore().
Member Data Documentation
allocation_folding
AllocationFolding v8::internal::compiler::turboshaft::MemoryAnalyzer::allocation_folding
Definition at line 100 of file memory-optimization-reducer.h.
Referenced by ProcessAllocation().
block_states
FixedBlockSidetable<std::optional<BlockState> > v8::internal::compiler::turboshaft::MemoryAnalyzer::block_states
Initial value:
{
      input_graph.block_count(), phase_zone}
Definition at line 119 of file memory-optimization-reducer.h.
Referenced by MergeCurrentStateIntoSuccessor(), ProcessBlockTerminator(), and Run().
current_block
BlockIndex v8::internal::compiler::turboshaft::MemoryAnalyzer::current_block = BlockIndex(0)
Definition at line 125 of file memory-optimization-reducer.h.
Referenced by ProcessBlockTerminator(), and Run().
data
PipelineData* v8::internal::compiler::turboshaft::MemoryAnalyzer::data
Definition at line 96 of file memory-optimization-reducer.h.
folded_into
ZoneAbslFlatHashMap<const AllocateOp*, const AllocateOp*> v8::internal::compiler::turboshaft::MemoryAnalyzer::folded_into
Initial value:
{
      phase_zone}
Definition at line 121 of file memory-optimization-reducer.h.
Referenced by IsFoldedAllocation(), IsPartOfLastAllocation(), and ProcessAllocation().
input_graph
const Graph& v8::internal::compiler::turboshaft::MemoryAnalyzer::input_graph
Definition at line 98 of file memory-optimization-reducer.h.
Referenced by IsFoldedAllocation(), IsPartOfLastAllocation(), ProcessAllocation(), ProcessBlockTerminator(), ProcessStore(), ReservedSize(), Run(), and SkipWriteBarrier().
is_wasm
bool v8::internal::compiler::turboshaft::MemoryAnalyzer::is_wasm
Definition at line 101 of file memory-optimization-reducer.h.
isolate_
Isolate* v8::internal::compiler::turboshaft::MemoryAnalyzer::isolate_ = data->isolate()
Definition at line 99 of file memory-optimization-reducer.h.
Referenced by SkipWriteBarrier().
phase_zone
Zone* v8::internal::compiler::turboshaft::MemoryAnalyzer::phase_zone
Definition at line 97 of file memory-optimization-reducer.h.
pipeline_kind
TurboshaftPipelineKind v8::internal::compiler::turboshaft::MemoryAnalyzer::pipeline_kind = data->pipeline_kind()
Definition at line 127 of file memory-optimization-reducer.h.
reserved_size
ZoneAbslFlatHashMap<const AllocateOp*, uint32_t> v8::internal::compiler::turboshaft::MemoryAnalyzer::reserved_size {phase_zone}
Definition at line 124 of file memory-optimization-reducer.h.
Referenced by ProcessAllocation(), and ReservedSize().
skipped_write_barriers
ZoneAbslFlatHashSet<V<None> > v8::internal::compiler::turboshaft::MemoryAnalyzer::skipped_write_barriers {phase_zone}
Definition at line 123 of file memory-optimization-reducer.h.
Referenced by ProcessStore().
state
BlockState v8::internal::compiler::turboshaft::MemoryAnalyzer::state
Definition at line 126 of file memory-optimization-reducer.h.
Referenced by IsPartOfLastAllocation(), MergeCurrentStateIntoSuccessor(), Process(), ProcessAllocation(), ProcessBlockTerminator(), and Run().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/memory-optimization-reducer.h
/mnt/V8SourceCode/src/compiler/turboshaft/memory-optimization-reducer.cc