cppgc::internal::MakeGarbageCollectedTraitInternal::AllocationDispatcher< GCInfoType, CustomSpace, api_constants::kDefaultAlignment > Struct Template Reference
#include <allocation.h>
Static Public Member Functions
static void * Invoke (AllocationHandle &handle, size_t size)
Detailed Description
template<typename GCInfoType, typename CustomSpace>
struct cppgc::internal::MakeGarbageCollectedTraitInternal::AllocationDispatcher< GCInfoType, CustomSpace, api_constants::kDefaultAlignment >
Definition at line 110 of file allocation.h.
Member Function Documentation
Invoke()
template<typename GCInfoType , typename CustomSpace >
static void* cppgc::internal::MakeGarbageCollectedTraitInternal::AllocationDispatcher< GCInfoType, CustomSpace, api_constants::kDefaultAlignment >::Invoke (AllocationHandle & handle, size_t size) [inline], [static]
Definition at line 113 of file allocation.h.
                                                               {
      static_assert(std::is_base_of_v<CustomSpaceBase, CustomSpace>,
                    "Custom space must inherit from CustomSpaceBase.");
      return MakeGarbageCollectedTraitInternal::Allocate(
          handle, size, internal::GCInfoTrait<GCInfoType>::Index(),
          CustomSpace::kSpaceIndex);
    }
References cppgc::internal::MakeGarbageCollectedTraitInternal::Allocate(), v8::internal::handle(), and size().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/include/cppgc/allocation.h