v8::internal::Scanner::Location Struct Reference
#include <scanner.h>
Public Member Functions
Location (int b, int e)
Location ()
int length () const
bool IsValid () const
Static Public Member Functions
static Location invalid ()
Public Attributes
int beg_pos
int end_pos
Detailed Description
Definition at line 263 of file scanner.h.
Constructor & Destructor Documentation
Location() [1/2]
v8::internal::Scanner::Location::Location (int b, int e) [inline]
Definition at line 264 of file scanner.h.
: beg_pos(b), end_pos(e) { }
Location() [2/2]
v8::internal::Scanner::Location::Location () [inline]
Definition at line 265 of file scanner.h.
: beg_pos(0), end_pos(0) { }
Member Function Documentation
invalid()
static Location v8::internal::Scanner::Location::invalid () [inline], [static]
Definition at line 270 of file scanner.h.
{ return Location(-1, 0); }
Referenced by v8::internal::ParserBase< Impl >::CheckConflictingVarDeclarations(), v8::internal::ExpressionParsingScope< Types >::clear(), v8::internal::ParserBase< Impl >::NextArrowFunctionInfo::ClearStrictParameterError(), v8::internal::Parser::DoParseFunction(), v8::internal::Scanner::ErrorState::ErrorState(), v8::internal::Scanner::ErrorState::MoveErrorTo(), v8::internal::ParserBase< Impl >::ParseClassExpression(), v8::internal::Parser::ParseExportDeclaration(), v8::internal::Parser::ParseExportStar(), v8::internal::ParserBase< Impl >::ParseFunctionExpression(), and v8::internal::Parser::ReportVarRedeclarationIn().
IsValid()
bool v8::internal::Scanner::Location::IsValid () const [inline]
Definition at line 268 of file scanner.h.
{ return base::IsInRange(beg_pos, 0, end_pos); }
Referenced by v8::internal::anonymous_namespace{modules.cc}::BetterDuplicate(), v8::internal::ParserBase< Impl >::CheckStrictOctalLiteral(), v8::internal::ParameterDeclarationParsingScope< Types >::has_duplicate(), v8::internal::ParserFormalParameters::has_duplicate(), v8::internal::ExpressionParsingScope< Types >::is_valid(), v8::internal::Parser::ParseExportClause(), v8::internal::Parser::ParseExportDeclaration(), v8::internal::ParserBase< Impl >::ParseForAwaitStatement(), v8::internal::ParserBase< Impl >::ParseForEachStatementWithDeclarations(), v8::internal::ParserBase< Impl >::ParseVariableDeclarations(), v8::internal::ArrowHeadParsingScope< Types >::ValidateAndCreateScope(), and v8::internal::ParserFormalParameters::ValidateStrictMode().
length()
int v8::internal::Scanner::Location::length () const [inline]
Definition at line 267 of file scanner.h.
{ return end_pos - beg_pos; }
Member Data Documentation
beg_pos
int v8::internal::Scanner::Location::beg_pos
Definition at line 272 of file scanner.h.
Referenced by v8::internal::SourceTextModuleDescriptor::AddModuleRequest(), v8::internal::anonymous_namespace{modules.cc}::BetterDuplicate(), v8::internal::ParserBase< Impl >::CheckStrictOctalLiteral(), v8::internal::Scanner::LiteralContainsEscapes(), v8::internal::ParserBase< Impl >::ParseAccessorPropertyOrAutoAccessors(), v8::internal::ParserBase< Impl >::ParseArrowParametersWithRest(), v8::internal::ParserBase< Impl >::ParseClassPropertyDefinition(), v8::internal::ParserBase< Impl >::ParseForStatement(), v8::internal::ParserBase< Impl >::ParseLeftHandSideContinuation(), v8::internal::ParserBase< Impl >::ParseObjectPropertyDefinition(), v8::internal::ParserBase< Impl >::peek_position(), v8::internal::ParserBase< Impl >::position(), v8::internal::ParserBase< Impl >::ReportMessageAt(), v8::internal::Scanner::ScanSingleToken(), v8::internal::Scanner::SeekForward(), v8::internal::Scanner::SeekNext(), v8::internal::SourceRangeScope::SourceRangeScope(), and v8::internal::SourceTextModuleDescriptor::Validate().
end_pos
int v8::internal::Scanner::Location::end_pos
Definition at line 273 of file scanner.h.
Referenced by v8::internal::ParserBase< Impl >::CheckStrictOctalLiteral(), v8::internal::Parser::DeclareArrowFunctionFormalParameters(), v8::internal::ParserBase< Impl >::end_position(), v8::internal::Scanner::LiteralContainsEscapes(), v8::internal::ParserBase< Impl >::ParseConditionalChainExpression(), v8::internal::Parser::ParseExportClause(), v8::internal::PreParser::ParseFunctionLiteral(), v8::internal::Parser::ParseImportWithOrAssertClause(), v8::internal::PreParser::ParseStatementListAndLogFunction(), v8::internal::ParserBase< Impl >::ParseVariableDeclarations(), v8::internal::ParserBase< Impl >::peek_end_position(), v8::internal::PreParser::PreParseFunction(), v8::internal::ParserBase< Impl >::ReportMessageAt(), v8::internal::Scanner::Scan(), v8::internal::Scanner::ScanRegExpFlags(), v8::internal::Scanner::ScanTemplateSpan(), v8::internal::Scanner::SeekForward(), and v8::internal::SourceTextModuleDescriptor::Validate().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/parsing/scanner.h