v8::internal::maglev::KnownNodeAspects Struct Reference
#include <maglev-interpreter-frame-state.h>
Classes
struct AvailableExpression
class LoadedPropertyMapKey
Public Types
enum class ContextSlotLoadsAlias : uint8_t { kNone
, kOnlyLoadsRelativeToCurrentContext
, kOnlyLoadsRelativeToConstant
, kYes
 }
using NodeInfos = ZoneMap< ValueNode *, NodeInfo >
using LoadedPropertyMap = ZoneMap< LoadedPropertyMapKey, ZoneMap< ValueNode *, ValueNode * > >
using LoadedContextSlotsKey = std::tuple< ValueNode *, int >
using LoadedContextSlots = ZoneMap< LoadedContextSlotsKey, ValueNode * >
Public Member Functions
KnownNodeAspects & operator= (const KnownNodeAspects &other)=delete
KnownNodeAspects (KnownNodeAspects &&other)=delete
KnownNodeAspects & operator= (KnownNodeAspects &&other)=delete
KnownNodeAspects * Clone (Zone *zone) const
KnownNodeAspects * CloneForLoopHeader (bool optimistic_initial_state, LoopEffects *loop_effects, Zone *zone) const
void ClearUnstableNodeAspects ()
void ClearUnstableMaps ()
template<typename Function >
void ClearUnstableMapsIfAny (const Function &condition)
void ClearAvailableExpressions ()
NodeInfos::iterator FindInfo (ValueNode *node)
NodeInfos::const_iterator FindInfo (ValueNode *node) const
bool IsValid (NodeInfos::iterator &it)
bool IsValid (NodeInfos::const_iterator &it) const
const NodeInfo * TryGetInfoFor (ValueNode *node) const
NodeInfo * TryGetInfoFor (ValueNode *node)
NodeInfo * GetOrCreateInfoFor (compiler::JSHeapBroker *broker, ValueNode *node)
NodeType GetType (compiler::JSHeapBroker *broker, ValueNode *node) const
bool CheckType (compiler::JSHeapBroker *broker, ValueNode *node, NodeType type, NodeType *current_type)
NodeType CheckTypes (compiler::JSHeapBroker *broker, ValueNode *node, std::initializer_list< NodeType > types)
bool MayBeNullOrUndefined (compiler::JSHeapBroker *broker, ValueNode *node)
bool EnsureType (compiler::JSHeapBroker *broker, ValueNode *node, NodeType type, NodeType *old_type)
template<typename Function >
bool EnsureType (compiler::JSHeapBroker *broker, ValueNode *node, NodeType type, Function ensure_new_type)
bool HaveDisjointTypes (compiler::JSHeapBroker *broker, ValueNode *lhs, ValueNode *rhs)
bool HasDisjointType (compiler::JSHeapBroker *broker, ValueNode *lhs, NodeType rhs_type)
void Merge (const KnownNodeAspects &other, Zone *zone)
bool IsCompatibleWithLoopHeader (const KnownNodeAspects &other) const
ContextSlotLoadsAlias may_have_aliasing_contexts () const
void UpdateMayHaveAliasingContexts (compiler::JSHeapBroker *broker, LocalIsolate *local_isolate, ValueNode *context)
uint32_t effect_epoch () const
void increment_effect_epoch ()
KnownNodeAspects (Zone *zone)
Static Public Member Functions
static ContextSlotLoadsAlias ContextSlotLoadsAliasMerge (ContextSlotLoadsAlias m1, ContextSlotLoadsAlias m2)
Public Attributes
bool any_map_for_any_node_is_unstable
LoadedPropertyMap loaded_constant_properties
LoadedPropertyMap loaded_properties
ZoneMap< std::tuple< ValueNode *, int >, ValueNode * > loaded_context_constants
LoadedContextSlots loaded_context_slots
ZoneMap< uint32_t, AvailableExpression > available_expressions
Static Public Attributes
static constexpr uint32_t kEffectEpochForPureInstructions
static constexpr uint32_t kEffectEpochOverflow
Private Member Functions
KnownNodeAspects (const KnownNodeAspects &other) V8_NOEXCEPT=default
KnownNodeAspects (const KnownNodeAspects &other, bool optimistic_initial_state, LoopEffects *loop_effects, Zone *zone)
Private Attributes
ContextSlotLoadsAlias may_have_aliasing_contexts_
uint32_t effect_epoch_
NodeInfos node_infos
Friends
KnownNodeAspects * Zone::New (const KnownNodeAspects &)
KnownNodeAspects * Zone::New (const KnownNodeAspects &, bool &, maglev::LoopEffects *&, Zone *&)
Detailed Description
Definition at line 269 of file maglev-interpreter-frame-state.h.
Member Typedef Documentation
LoadedContextSlots
using v8::internal::maglev::KnownNodeAspects::LoadedContextSlots = ZoneMap<LoadedContextSlotsKey, ValueNode*>
Definition at line 561 of file maglev-interpreter-frame-state.h.
LoadedContextSlotsKey
using v8::internal::maglev::KnownNodeAspects::LoadedContextSlotsKey = std::tuple<ValueNode*, int>
Definition at line 560 of file maglev-interpreter-frame-state.h.
LoadedPropertyMap
using v8::internal::maglev::KnownNodeAspects::LoadedPropertyMap = ZoneMap<LoadedPropertyMapKey, ZoneMap<ValueNode*, ValueNode*> >
Definition at line 529 of file maglev-interpreter-frame-state.h.
NodeInfos
using v8::internal::maglev::KnownNodeAspects::NodeInfos = ZoneMap<ValueNode*, NodeInfo>
Definition at line 271 of file maglev-interpreter-frame-state.h.
Member Enumeration Documentation
ContextSlotLoadsAlias
enum v8::internal::maglev::KnownNodeAspects::ContextSlotLoadsAlias : uint8_t [strong]
Enumerator
kNone
kOnlyLoadsRelativeToCurrentContext
kOnlyLoadsRelativeToConstant
kYes
Definition at line 539 of file maglev-interpreter-frame-state.h.
                                   : uint8_t {
    kNone,
    kOnlyLoadsRelativeToCurrentContext,
    kOnlyLoadsRelativeToConstant,
    kYes,
  };
Constructor & Destructor Documentation
KnownNodeAspects() [1/4]
v8::internal::maglev::KnownNodeAspects::KnownNodeAspects (KnownNodeAspects && other) [delete]
KnownNodeAspects() [2/4]
v8::internal::maglev::KnownNodeAspects::KnownNodeAspects (Zone * zone) [inline], [explicit]
Definition at line 578 of file maglev-interpreter-frame-state.h.
      : any_map_for_any_node_is_unstable(false),
        loaded_constant_properties(zone),
        loaded_properties(zone),
        loaded_context_constants(zone),
        loaded_context_slots(zone),
        available_expressions(zone),
        may_have_aliasing_contexts_(ContextSlotLoadsAlias::kNone),
        effect_epoch_(0),
        node_infos(zone) {}
References v8::internal::kNone.
KnownNodeAspects() [3/4]
v8::internal::maglev::KnownNodeAspects::KnownNodeAspects (const KnownNodeAspects & other) [private], [default]
KnownNodeAspects() [4/4]
v8::internal::maglev::KnownNodeAspects::KnownNodeAspects (const KnownNodeAspects & other, bool optimistic_initial_state, LoopEffects * loop_effects, Zone * zone) [private]
Definition at line 206 of file maglev-interpreter-frame-state.cc.
    : any_map_for_any_node_is_unstable(false),
      loaded_constant_properties(other.loaded_constant_properties),
      loaded_properties(zone),
      loaded_context_constants(other.loaded_context_constants),
      loaded_context_slots(zone),
      available_expressions(zone),
      may_have_aliasing_contexts_(
          KnownNodeAspects::ContextSlotLoadsAlias::kNone),
      effect_epoch_(other.effect_epoch_),
      node_infos(zone) {
  if (!other.any_map_for_any_node_is_unstable) {
    node_infos = other.node_infos;
#ifdef DEBUG
    for (const auto& it : node_infos) {
      DCHECK(!it.second.any_map_is_unstable());
    }
#endif
  } else if (optimistic_initial_state &&
             !loop_effects->unstable_aspects_cleared) {
    node_infos = other.node_infos;
    any_map_for_any_node_is_unstable = other.any_map_for_any_node_is_unstable;
  } else {
    for (const auto& it : other.node_infos) {
      node_infos.emplace(it.first,
                         NodeInfo::ClearUnstableMapsOnCopy{it.second});
    }
  }
  if (optimistic_initial_state && !loop_effects->unstable_aspects_cleared) {
    // IMPORTANT: Whatever we clone here needs to be checked for consistency
    // in when we try to terminate the loop in `IsCompatibleWithLoopHeader`.
    if (loop_effects->objects_written.empty() &&
        loop_effects->keys_cleared.empty()) {
      loaded_properties = other.loaded_properties;
    } else {
      auto cleared_key = loop_effects->keys_cleared.begin();
      auto cleared_keys_end = loop_effects->keys_cleared.end();
      auto cleared_obj = loop_effects->objects_written.begin();
      auto cleared_objs_end = loop_effects->objects_written.end();
      for (auto loaded_key : other.loaded_properties) {
        if (NextInIgnoreList(cleared_key, cleared_keys_end, loaded_key.first)) {
          continue;
        }
        auto& props_for_key =
            loaded_properties.try_emplace(loaded_key.first, zone).first->second;
        for (auto loaded_obj : loaded_key.second) {
          if (!NextInIgnoreList(cleared_obj, cleared_objs_end,
                                loaded_obj.first)) {
            props_for_key.emplace(loaded_obj);
          }
        }
      }
    }
    if (loop_effects->context_slot_written.empty()) {
      loaded_context_slots = other.loaded_context_slots;
    } else {
      auto slot_written = loop_effects->context_slot_written.begin();
      auto slot_written_end = loop_effects->context_slot_written.end();
      for (auto loaded : other.loaded_context_slots) {
        if (!NextInIgnoreList(slot_written, slot_written_end, loaded.first)) {
          loaded_context_slots.emplace(loaded);
        }
      }
    }
    if (!loaded_context_slots.empty()) {
      if (loop_effects->may_have_aliasing_contexts) {
        may_have_aliasing_contexts_ = ContextSlotLoadsAlias::kYes;
      } else {
        DCHECK_EQ(may_have_aliasing_contexts_, ContextSlotLoadsAlias::kNone);
        may_have_aliasing_contexts_ = other.may_have_aliasing_contexts();
      }
    }
  }
  // To account for the back-jump we must not allow effects to be reshuffled
  // across loop headers.
  // TODO(olivf): Only do this if the loop contains write effects.
  increment_effect_epoch();
  for (const auto& e : other.available_expressions) {
    if (e.second.effect_epoch >= effect_epoch()) {
      available_expressions.emplace(e);
    }
  }
}
References any_map_for_any_node_is_unstable, available_expressions, v8::internal::maglev::LoopEffects::context_slot_written, v8::internal::DCHECK(), DCHECK_EQ, effect_epoch(), increment_effect_epoch(), v8::internal::maglev::LoopEffects::keys_cleared, v8::internal::kNone, kNone, kYes, loaded_context_slots, loaded_properties, may_have_aliasing_contexts(), v8::internal::maglev::LoopEffects::may_have_aliasing_contexts, may_have_aliasing_contexts_, v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::NextInIgnoreList(), node_infos, v8::internal::maglev::LoopEffects::objects_written, and v8::internal::maglev::LoopEffects::unstable_aspects_cleared.
Member Function Documentation
CheckType()
bool v8::internal::maglev::KnownNodeAspects::CheckType (compiler::JSHeapBroker * broker, ValueNode * node, NodeType type, NodeType * current_type) [inline]
Definition at line 374 of file maglev-interpreter-frame-state.h.
                                         {
    NodeType static_type = node->GetStaticType(broker);
    if (current_type) *current_type = static_type;
    if (NodeTypeIs(static_type, type)) return true;
    auto it = FindInfo(node);
    if (!IsValid(it)) return false;
    if (current_type) *current_type = it->second.type();
    return NodeTypeIs(it->second.type(), type);
  }
References broker(), FindInfo(), v8::internal::maglev::ValueNode::GetStaticType(), IsValid(), v8::internal::maglev::NodeTypeIs(), and v8::internal::tracing::type.
Referenced by v8::internal::maglev::MaglevGraphBuilder::CheckType().
CheckTypes()
NodeType v8::internal::maglev::KnownNodeAspects::CheckTypes (compiler::JSHeapBroker * broker, ValueNode * node, std::initializer_list< NodeType > types) [inline]
Definition at line 385 of file maglev-interpreter-frame-state.h.
                                                           {
    auto it = FindInfo(node);
    bool has_kna = IsValid(it);
    for (NodeType type : types) {
      if (node->StaticTypeIs(broker, type)) return type;
      if (has_kna) {
        if (NodeTypeIs(it->second.type(), type)) return type;
      }
    }
    return NodeType::kUnknown;
  }
References broker(), FindInfo(), IsValid(), v8::internal::maglev::NodeTypeIs(), v8::internal::maglev::ValueNode::StaticTypeIs(), and v8::internal::tracing::type.
Referenced by v8::internal::maglev::MaglevGraphBuilder::CheckTypes().
ClearAvailableExpressions()
void v8::internal::maglev::KnownNodeAspects::ClearAvailableExpressions () [inline]
Definition at line 315 of file maglev-interpreter-frame-state.h.
{ available_expressions.clear(); }
References available_expressions.
Referenced by v8::internal::maglev::MaglevGraphBuilder::ProcessMergePointAtExceptionHandlerStart().
ClearUnstableMaps()
void v8::internal::maglev::KnownNodeAspects::ClearUnstableMaps () [inline]
Definition at line 293 of file maglev-interpreter-frame-state.h.
                           {
    // A side effect could change existing objects' maps. For stable maps we
    // know this hasn't happened (because we added a dependency on the maps
    // staying stable and therefore not possible to transition away from), but
    // we can no longer assume that objects with unstable maps still have the
    // same map. Unstable maps can also transition to stable ones, so we have to
    // clear _all_ maps for a node if it had _any_ unstable map.
    if (!any_map_for_any_node_is_unstable) return;
    for (auto& it : node_infos) {
      it.second.ClearUnstableMaps();
    }
    any_map_for_any_node_is_unstable = false;
  }
References any_map_for_any_node_is_unstable, and node_infos.
Referenced by ClearUnstableNodeAspects(), and v8::internal::maglev::StoreMap::ClearUnstableNodeAspects().
ClearUnstableMapsIfAny()
template<typename Function >
void v8::internal::maglev::KnownNodeAspects::ClearUnstableMapsIfAny (const Function & condition) [inline]
Definition at line 308 of file maglev-interpreter-frame-state.h.
                                                         {
    if (!any_map_for_any_node_is_unstable) return;
    for (auto& it : node_infos) {
      it.second.ClearUnstableMapsIfAny(condition);
    }
  }
References any_map_for_any_node_is_unstable, and node_infos.
Referenced by v8::internal::maglev::StoreMap::ClearUnstableNodeAspects().
ClearUnstableNodeAspects()
void v8::internal::maglev::KnownNodeAspects::ClearUnstableNodeAspects ()
Definition at line 187 of file maglev-interpreter-frame-state.cc.
                                                {
  if (v8_flags.trace_maglev_graph_building) {
    std::cout << " ! Clearing unstable node aspects" << std::endl;
  }
  ClearUnstableMaps();
  // Side-effects can change object contents, so we have to clear
  // our known loaded properties -- however, constant properties are known
  // to not change (and we added a dependency on this), so we don't have to
  // clear those.
  loaded_properties.clear();
  loaded_context_slots.clear();
  may_have_aliasing_contexts_ = KnownNodeAspects::ContextSlotLoadsAlias::kNone;
}
References ClearUnstableMaps(), kNone, loaded_context_slots, loaded_properties, may_have_aliasing_contexts_, and v8::internal::v8_flags.
Referenced by v8::internal::maglev::NodeBase::ClearUnstableNodeAspects().
Clone()
KnownNodeAspects* v8::internal::maglev::KnownNodeAspects::Clone (Zone * zone) const [inline]
Definition at line 279 of file maglev-interpreter-frame-state.h.
                                            {
    return zone->New<KnownNodeAspects>(*this);
  }
References v8::internal::Zone::New().
Referenced by v8::internal::maglev::MergePointInterpreterFrameState::CloneKnownNodeAspects(), v8::internal::maglev::MergePointInterpreterFrameState::MergeThrow(), and v8::internal::maglev::MergePointInterpreterFrameState::New().
CloneForLoopHeader()
KnownNodeAspects * v8::internal::maglev::KnownNodeAspects::CloneForLoopHeader (bool optimistic_initial_state, LoopEffects * loop_effects, Zone * zone) const
Definition at line 201 of file maglev-interpreter-frame-state.cc.
                                                                  {
  return zone->New<KnownNodeAspects>(*this, optimistic, loop_effects, zone);
}
References v8::internal::Zone::New().
Referenced by v8::internal::maglev::MergePointInterpreterFrameState::InitializeLoop().
ContextSlotLoadsAliasMerge()
static ContextSlotLoadsAlias v8::internal::maglev::KnownNodeAspects::ContextSlotLoadsAliasMerge (ContextSlotLoadsAlias m1, ContextSlotLoadsAlias m2) [inline], [static]
Definition at line 548 of file maglev-interpreter-frame-state.h.
                                                          {
    if (m1 == m2) return m1;
    if (m1 == ContextSlotLoadsAlias::kNone) return m2;
    if (m2 == ContextSlotLoadsAlias::kNone) return m1;
    return ContextSlotLoadsAlias::kYes;
  }
References kNone, and kYes.
Referenced by Merge(), and UpdateMayHaveAliasingContexts().
effect_epoch()
uint32_t v8::internal::maglev::KnownNodeAspects::effect_epoch () const [inline]
Definition at line 569 of file maglev-interpreter-frame-state.h.
{ return effect_epoch_; }
References effect_epoch_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::AddNewNodeOrGetEquivalent(), IsCompatibleWithLoopHeader(), and KnownNodeAspects().
EnsureType() [1/2]
template<typename Function >
bool v8::internal::maglev::KnownNodeAspects::EnsureType (compiler::JSHeapBroker * broker, ValueNode * node, NodeType type, Function ensure_new_type) [inline]
Definition at line 426 of file maglev-interpreter-frame-state.h.
                                                           {
    if (node->StaticTypeIs(broker, type)) return true;
    NodeInfo* known_info = GetOrCreateInfoFor(broker, node);
    if (NodeTypeIs(known_info->type(), type)) return true;
    ensure_new_type(known_info->type());
    known_info->IntersectType(type);
    if (NodeTypeIsUnstable(type)) {
      known_info->set_node_type_is_unstable();
      any_map_for_any_node_is_unstable = true;
    }
    return false;
  }
References any_map_for_any_node_is_unstable, broker(), GetOrCreateInfoFor(), v8::internal::maglev::NodeInfo::IntersectType(), v8::internal::maglev::NodeTypeIs(), v8::internal::maglev::NodeTypeIsUnstable(), v8::internal::maglev::NodeInfo::set_node_type_is_unstable(), v8::internal::maglev::ValueNode::StaticTypeIs(), v8::internal::maglev::NodeInfo::type(), and v8::internal::tracing::type.
EnsureType() [2/2]
bool v8::internal::maglev::KnownNodeAspects::EnsureType (compiler::JSHeapBroker * broker, ValueNode * node, NodeType type, NodeType * old_type) [inline]
Definition at line 406 of file maglev-interpreter-frame-state.h.
                                                     {
    NodeType static_type = node->GetStaticType(broker);
    if (old_type) *old_type = static_type;
    if (NodeTypeIs(static_type, type)) return true;
    NodeInfo* known_info = GetOrCreateInfoFor(broker, node);
    if (old_type) *old_type = known_info->type();
    if (NodeTypeIs(known_info->type(), type)) return true;
    known_info->IntersectType(type);
    if (auto phi = node->TryCast<Phi>()) {
      known_info->IntersectType(phi->type());
    }
    if (NodeTypeIsUnstable(type)) {
      known_info->set_node_type_is_unstable();
      any_map_for_any_node_is_unstable = true;
    }
    return false;
  }
References any_map_for_any_node_is_unstable, broker(), GetOrCreateInfoFor(), v8::internal::maglev::ValueNode::GetStaticType(), v8::internal::maglev::NodeInfo::IntersectType(), v8::internal::maglev::NodeTypeIs(), v8::internal::maglev::NodeTypeIsUnstable(), v8::internal::maglev::NodeInfo::set_node_type_is_unstable(), v8::internal::maglev::NodeBase::TryCast(), v8::internal::maglev::NodeInfo::type(), and v8::internal::tracing::type.
Referenced by v8::internal::maglev::MaglevGraphBuilder::EnsureType().
FindInfo() [1/2]
NodeInfos::iterator v8::internal::maglev::KnownNodeAspects::FindInfo (ValueNode * node) [inline]
Definition at line 317 of file maglev-interpreter-frame-state.h.
                                              {
    return node_infos.find(node);
  }
References node_infos.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildTestUndetectable(), CheckType(), CheckTypes(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::EnsureTagged(), GetOrCreateInfoFor(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::KnownMapsMerger::IntersectWithKnownNodeAspects(), MayBeNullOrUndefined(), and TryGetInfoFor().
FindInfo() [2/2]
NodeInfos::const_iterator v8::internal::maglev::KnownNodeAspects::FindInfo (ValueNode * node) const [inline]
Definition at line 320 of file maglev-interpreter-frame-state.h.
                                                          {
    return node_infos.find(node);
  }
References node_infos.
GetOrCreateInfoFor()
NodeInfo* v8::internal::maglev::KnownNodeAspects::GetOrCreateInfoFor (compiler::JSHeapBroker * broker, ValueNode * node) [inline]
Definition at line 338 of file maglev-interpreter-frame-state.h.
                                                {
    auto info_it = FindInfo(node);
    if (IsValid(info_it)) return &info_it->second;
    auto res = &node_infos.emplace(node, NodeInfo()).first->second;
    res->IntersectType(node->GetStaticType(broker));
    return res;
  }
References broker(), FindInfo(), v8::internal::maglev::ValueNode::GetStaticType(), IsValid(), and node_infos.
Referenced by EnsureType(), v8::internal::maglev::MaglevGraphBuilder::GetOrCreateInfoFor(), and v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::KnownMapsMerger::UpdateKnownNodeAspects().
GetType()
NodeType v8::internal::maglev::KnownNodeAspects::GetType (compiler::JSHeapBroker * broker, ValueNode * node) const [inline]
Definition at line 347 of file maglev-interpreter-frame-state.h.
                                                                        {
    // We first check the KnownNodeAspects in order to return the most precise
    // type possible.
    auto info = TryGetInfoFor(node);
    if (info == nullptr) {
      // If this node has no NodeInfo (or not known type in its NodeInfo), we
      // fall back to its static type.
      return node->GetStaticType(broker);
    }
    NodeType actual_type = info->type();
    if (auto phi = node->TryCast<Phi>()) {
      actual_type = IntersectType(actual_type, phi->type());
    }
#ifdef DEBUG
    NodeType static_type = node->GetStaticType(broker);
    if (!NodeTypeIs(actual_type, static_type)) {
      // In case we needed a numerical alternative of a smi value, the type
      // must generalize. In all other cases the node info type should reflect
      // the actual type.
      DCHECK(static_type == NodeType::kSmi &&
             actual_type == NodeType::kNumber &&
             !TryGetInfoFor(node)->alternative().has_none());
    }
#endif // DEBUG
    return actual_type;
  }
References broker(), v8::internal::DCHECK(), v8::internal::maglev::ValueNode::GetStaticType(), v8::internal::maglev::IntersectType(), v8::internal::compiler::kSmi, v8::internal::maglev::NodeTypeIs(), v8::internal::maglev::NodeBase::TryCast(), and TryGetInfoFor().
Referenced by v8::internal::maglev::MaglevGraphBuilder::GetType(), HasDisjointType(), HaveDisjointTypes(), v8::internal::maglev::MergePointInterpreterFrameState::MergeLoopValue(), v8::internal::maglev::MergePointInterpreterFrameState::MergeValue(), v8::internal::maglev::MergePointInterpreterFrameState::MergeVirtualObjectValue(), v8::internal::maglev::MergePointInterpreterFrameState::TryMergeLoop(), and UpdateMayHaveAliasingContexts().
HasDisjointType()
bool v8::internal::maglev::KnownNodeAspects::HasDisjointType (compiler::JSHeapBroker * broker, ValueNode * lhs, NodeType rhs_type) [inline]
Definition at line 447 of file maglev-interpreter-frame-state.h.
                                          {
    return IsEmptyNodeType(IntersectType(GetType(broker, lhs), rhs_type));
  }
References broker(), GetType(), v8::internal::maglev::IntersectType(), and v8::internal::maglev::IsEmptyNodeType().
Referenced by v8::internal::maglev::MaglevGraphBuilder::HasDisjointType(), and HaveDisjointTypes().
HaveDisjointTypes()
bool v8::internal::maglev::KnownNodeAspects::HaveDisjointTypes (compiler::JSHeapBroker * broker, ValueNode * lhs, ValueNode * rhs) [inline]
Definition at line 442 of file maglev-interpreter-frame-state.h.
                                         {
    return HasDisjointType(broker, lhs, GetType(broker, rhs));
  }
References broker(), GetType(), and HasDisjointType().
Referenced by v8::internal::maglev::MaglevGraphBuilder::HaveDisjointTypes().
increment_effect_epoch()
void v8::internal::maglev::KnownNodeAspects::increment_effect_epoch () [inline]
Definition at line 574 of file maglev-interpreter-frame-state.h.
                                {
    if (effect_epoch_ < kEffectEpochOverflow) effect_epoch_++;
  }
References effect_epoch_, and kEffectEpochOverflow.
Referenced by KnownNodeAspects().
IsCompatibleWithLoopHeader()
bool v8::internal::maglev::KnownNodeAspects::IsCompatibleWithLoopHeader (const KnownNodeAspects & other) const
Definition at line 369 of file maglev-interpreter-frame-state.cc.
                                               {
  // Needs to be in sync with `CloneForLoopHeader(zone, true)`.
  // Analysis state can change with loads.
  if (!loop_header.loaded_context_slots.empty() &&
      loop_header.may_have_aliasing_contexts() != ContextSlotLoadsAlias::kYes &&
      loop_header.may_have_aliasing_contexts() !=
          may_have_aliasing_contexts() &&
      may_have_aliasing_contexts() != ContextSlotLoadsAlias::kNone) {
    if (V8_UNLIKELY(v8_flags.trace_maglev_loop_speeling)) {
      std::cout << "KNA after loop has incompatible "
                   "loop_header.may_have_aliasing_contexts\n";
    }
    return false;
  }
  bool had_effects = effect_epoch() != loop_header.effect_epoch();
  if (!had_effects) {
    if (!AspectIncludes(loop_header.node_infos, node_infos, NodeInfoTypeIs,
                        NodeInfoIsEmpty)) {
      if (V8_UNLIKELY(v8_flags.trace_maglev_loop_speeling)) {
        std::cout << "KNA after effectless loop has incompatible node_infos\n";
      }
      return false;
    }
    // In debug builds we do a full comparison to ensure that without an effect
    // epoch change all unstable properties still hold.
#ifndef DEBUG
    return true;
#endif
  }
  if (!AspectIncludes(loop_header.node_infos, node_infos, NodeInfoIncludes,
                      NodeInfoIsEmpty)) {
    if (V8_UNLIKELY(v8_flags.trace_maglev_loop_speeling)) {
      std::cout << "KNA after loop has incompatible node_infos\n";
    }
    DCHECK(had_effects);
    return false;
  }
  if (!MaybeEmptyAspectIncludes(
          loop_header.loaded_properties, loaded_properties,
          [](auto a, auto b) { return AspectIncludes(a, b, SameValue); })) {
    if (V8_UNLIKELY(v8_flags.trace_maglev_loop_speeling)) {
      std::cout << "KNA after loop has incompatible loaded_properties\n";
    }
    DCHECK(had_effects);
    return false;
  }
  if (!MaybeNullAspectIncludes(loop_header.loaded_context_slots,
                               loaded_context_slots, SameValue)) {
    if (V8_UNLIKELY(v8_flags.trace_maglev_loop_speeling)) {
      std::cout << "KNA after loop has incompatible loaded_context_slots\n";
    }
    DCHECK(had_effects);
    return false;
  }
  return true;
}
References v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::AspectIncludes(), v8::internal::DCHECK(), effect_epoch(), kNone, kYes, loaded_context_slots, loaded_properties, may_have_aliasing_contexts(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::MaybeEmptyAspectIncludes(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::MaybeNullAspectIncludes(), node_infos, v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::NodeInfoIncludes(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::NodeInfoIsEmpty(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::NodeInfoTypeIs(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::SameValue(), v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by v8::internal::maglev::MergePointInterpreterFrameState::TryMergeLoop().
IsValid() [1/2]
bool v8::internal::maglev::KnownNodeAspects::IsValid (NodeInfos::const_iterator & it) const [inline]
Definition at line 324 of file maglev-interpreter-frame-state.h.
                                                  {
    return it != node_infos.end();
  }
References node_infos.
IsValid() [2/2]
bool v8::internal::maglev::KnownNodeAspects::IsValid (NodeInfos::iterator & it) [inline]
Definition at line 323 of file maglev-interpreter-frame-state.h.
{ return it != node_infos.end(); }
References node_infos.
Referenced by CheckType(), CheckTypes(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::EnsureTagged(), GetOrCreateInfoFor(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::KnownMapsMerger::IntersectWithKnownNodeAspects(), MayBeNullOrUndefined(), and TryGetInfoFor().
may_have_aliasing_contexts()
ContextSlotLoadsAlias v8::internal::maglev::KnownNodeAspects::may_have_aliasing_contexts () const [inline]
Definition at line 545 of file maglev-interpreter-frame-state.h.
                                                           {
    return may_have_aliasing_contexts_;
  }
References may_have_aliasing_contexts_.
Referenced by IsCompatibleWithLoopHeader(), KnownNodeAspects(), and Merge().
MayBeNullOrUndefined()
bool v8::internal::maglev::KnownNodeAspects::MayBeNullOrUndefined (compiler::JSHeapBroker * broker, ValueNode * node) [inline]
Definition at line 398 of file maglev-interpreter-frame-state.h.
                                                                           {
    NodeType static_type = node->GetStaticType(broker);
    if (!NodeTypeMayBeNullOrUndefined(static_type)) return false;
    auto it = FindInfo(node);
    if (!IsValid(it)) return true;
    return NodeTypeMayBeNullOrUndefined(it->second.type());
  }
References broker(), FindInfo(), v8::internal::maglev::ValueNode::GetStaticType(), IsValid(), and v8::internal::maglev::NodeTypeMayBeNullOrUndefined().
Merge()
void v8::internal::maglev::KnownNodeAspects::Merge (const KnownNodeAspects & other, Zone * zone)
Definition at line 26 of file maglev-interpreter-frame-state.cc.
                                                                      {
  bool any_merged_map_is_unstable = false;
  DestructivelyIntersect(node_infos, other.node_infos,
                         [&](NodeInfo& lhs, const NodeInfo& rhs) {
                           lhs.MergeWith(rhs, zone, any_merged_map_is_unstable);
                           return !lhs.no_info_available();
                         });
  if (effect_epoch_ != other.effect_epoch_) {
    effect_epoch_ = std::max(effect_epoch_, other.effect_epoch_) + 1;
  }
  DestructivelyIntersect(
      available_expressions, other.available_expressions,
      [&](const AvailableExpression& lhs, const AvailableExpression& rhs) {
        DCHECK_IMPLIES(lhs.node == rhs.node,
                       lhs.effect_epoch == rhs.effect_epoch);
        DCHECK_NE(lhs.effect_epoch, kEffectEpochOverflow);
        DCHECK_EQ(Node::needs_epoch_check(lhs.node->opcode()),
                  lhs.effect_epoch != kEffectEpochForPureInstructions);
        return lhs.node == rhs.node && lhs.effect_epoch >= effect_epoch_;
      });
  this->any_map_for_any_node_is_unstable = any_merged_map_is_unstable;
  auto merge_loaded_properties =
      [](ZoneMap<ValueNode*, ValueNode*>& lhs,
         const ZoneMap<ValueNode*, ValueNode*>& rhs) {
        // Loaded properties are maps of maps, so just do the destructive
        // intersection recursively.
        DestructivelyIntersect(lhs, rhs);
        return !lhs.empty();
      };
  DestructivelyIntersect(loaded_constant_properties,
                         other.loaded_constant_properties,
                         merge_loaded_properties);
  DestructivelyIntersect(loaded_properties, other.loaded_properties,
                         merge_loaded_properties);
  DestructivelyIntersect(loaded_context_constants,
                         other.loaded_context_constants);
  may_have_aliasing_contexts_ = ContextSlotLoadsAliasMerge(
      may_have_aliasing_contexts_, other.may_have_aliasing_contexts());
  DestructivelyIntersect(loaded_context_slots, other.loaded_context_slots);
}
References any_map_for_any_node_is_unstable, available_expressions, ContextSlotLoadsAliasMerge(), v8::internal::maglev::DestructivelyIntersect(), effect_epoch_, loaded_constant_properties, loaded_context_constants, loaded_context_slots, loaded_properties, may_have_aliasing_contexts(), may_have_aliasing_contexts_, and node_infos.
Referenced by v8::internal::maglev::MergePointInterpreterFrameState::Merge(), and v8::internal::maglev::MergePointInterpreterFrameState::MergeThrow().
operator=() [1/2]
KnownNodeAspects& v8::internal::maglev::KnownNodeAspects::operator= (const KnownNodeAspects & other) [delete]
operator=() [2/2]
KnownNodeAspects& v8::internal::maglev::KnownNodeAspects::operator= (KnownNodeAspects && other) [delete]
TryGetInfoFor() [1/2]
NodeInfo* v8::internal::maglev::KnownNodeAspects::TryGetInfoFor (ValueNode * node) [inline]
Definition at line 332 of file maglev-interpreter-frame-state.h.
                                           {
    auto info_it = FindInfo(node);
    if (!IsValid(info_it)) return nullptr;
    return &info_it->second;
  }
References FindInfo(), and IsValid().
TryGetInfoFor() [2/2]
const NodeInfo* v8::internal::maglev::KnownNodeAspects::TryGetInfoFor (ValueNode * node) const [inline]
Definition at line 328 of file maglev-interpreter-frame-state.h.
                                                       {
    return const_cast<KnownNodeAspects*>(this)->TryGetInfoFor(node);
  }
Referenced by v8::internal::maglev::StoreMap::ClearUnstableNodeAspects(), GetType(), v8::internal::maglev::MaglevGraphBuilder::GetUint8ClampedForToNumber(), v8::internal::maglev::MergePointInterpreterFrameState::MergeValue(), v8::internal::maglev::MergePointInterpreterFrameState::New(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::PrintAfterMerge(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::PrintBeforeMerge(), v8::internal::maglev::MaglevGraphBuilder::TryBuildNamedAccess(), and v8::internal::maglev::MaglevGraphBuilder::TryGetConstantAlternative().
UpdateMayHaveAliasingContexts()
void v8::internal::maglev::KnownNodeAspects::UpdateMayHaveAliasingContexts (compiler::JSHeapBroker * broker, LocalIsolate * local_isolate, ValueNode * context)
Definition at line 122 of file maglev-interpreter-frame-state.cc.
                        {
  while (true) {
    if (auto load_prev_ctxt =
            context->TryCast<LoadTaggedFieldForContextSlotNoCells>()) {
      DCHECK_EQ(load_prev_ctxt->offset(),
                Context::OffsetOfElementAt(Context::PREVIOUS_INDEX));
      // Recurse until we find the root.
      context = load_prev_ctxt->input(0).node();
      continue;
    }
    break;
  }
  switch (context->opcode()) {
    case Opcode::kInitialValue:
      may_have_aliasing_contexts_ = ContextSlotLoadsAliasMerge(
          may_have_aliasing_contexts_,
          ContextSlotLoadsAlias::kOnlyLoadsRelativeToCurrentContext);
      break;
    case Opcode::kConstant:
      may_have_aliasing_contexts_ = ContextSlotLoadsAliasMerge(
          may_have_aliasing_contexts_,
          ContextSlotLoadsAlias::kOnlyLoadsRelativeToConstant);
      DCHECK(NodeTypeIs(GetType(broker, context), NodeType::kContext));
      break;
    case Opcode::kCreateFunctionContext:
    case Opcode::kInlinedAllocation:
      // These can be precisely tracked.
      DCHECK(NodeTypeIs(GetType(broker, context), NodeType::kContext));
      break;
    case Opcode::kLoadTaggedField: {
      LoadTaggedField* load = context->Cast<LoadTaggedField>();
      // Currently, the only way to leak a context via load tagged field is with
      // JSFunction or JSGeneratorObject.
      USE(load);
      DCHECK(load->offset() == JSFunction::kContextOffset ||
             load->offset() == JSGeneratorObject::kContextOffset);
      may_have_aliasing_contexts_ = ContextSlotLoadsAlias::kYes;
      DCHECK(NodeTypeIs(GetType(broker, context), NodeType::kContext));
      break;
    }
    case Opcode::kCallRuntime:
      DCHECK(NodeTypeIs(GetType(broker, context), NodeType::kContext));
      may_have_aliasing_contexts_ = ContextSlotLoadsAlias::kYes;
      break;
    case Opcode::kGeneratorRestoreRegister:
      may_have_aliasing_contexts_ = ContextSlotLoadsAlias::kYes;
      break;
    case Opcode::kPhi:
      SLOW_DCHECK(CheckAllPhiInputsAreContextType(broker, local_isolate, *this,
                                                  context->Cast<Phi>()));
      may_have_aliasing_contexts_ = ContextSlotLoadsAlias::kYes;
      break;
    default:
      // This DCHECK only shows which kind of nodes can be a context, even if
      // this DCHECK fails, it is always safe to set aliasing context mode to
      // kYes.
      DCHECK(false);
      may_have_aliasing_contexts_ = ContextSlotLoadsAlias::kYes;
      break;
  }
}
References broker(), v8::internal::maglev::NodeBase::Cast(), ContextSlotLoadsAliasMerge(), v8::internal::DCHECK(), DCHECK_EQ, GetType(), v8::internal::maglev::NodeBase::input(), v8::internal::compiler::anonymous_namespace{gap-resolver.cc}::kConstant, v8::internal::anonymous_namespace{assert-scope.cc}::kInitialValue, kOnlyLoadsRelativeToConstant, kOnlyLoadsRelativeToCurrentContext, kYes, may_have_aliasing_contexts_, v8::internal::maglev::Input::node(), v8::internal::maglev::NodeTypeIs(), v8::internal::maglev::AbstractLoadTaggedField< Derived >::offset(), v8::internal::Context::OffsetOfElementAt(), v8::internal::maglev::NodeBase::opcode(), v8::internal::Context::PREVIOUS_INDEX, SLOW_DCHECK, v8::internal::maglev::NodeBase::TryCast(), and USE.
Referenced by v8::internal::maglev::MaglevGraphBuilder::LoadAndCacheContextSlot(), and v8::internal::maglev::MaglevGraphBuilder::StoreAndCacheContextSlot().
Friends And Related Function Documentation
Zone::New [1/2]
KnownNodeAspects* Zone::New (const KnownNodeAspects &) [friend]
Zone::New [2/2]
KnownNodeAspects* Zone::New (const KnownNodeAspects & , bool & , maglev::LoopEffects *& , Zone *&) [friend]
Member Data Documentation
any_map_for_any_node_is_unstable
bool v8::internal::maglev::KnownNodeAspects::any_map_for_any_node_is_unstable
Definition at line 462 of file maglev-interpreter-frame-state.h.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildStoreMap(), v8::internal::maglev::MaglevGraphBuilder::BuildTransitionElementsKindAndCompareMaps(), v8::internal::maglev::MaglevGraphBuilder::BuildTransitionElementsKindOrCheckMap(), ClearUnstableMaps(), ClearUnstableMapsIfAny(), EnsureType(), KnownNodeAspects(), Merge(), and v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::KnownMapsMerger::UpdateKnownNodeAspects().
available_expressions
ZoneMap<uint32_t, AvailableExpression> v8::internal::maglev::KnownNodeAspects::available_expressions
Definition at line 568 of file maglev-interpreter-frame-state.h.
Referenced by v8::internal::maglev::MaglevGraphBuilder::AddNewNodeOrGetEquivalent(), ClearAvailableExpressions(), KnownNodeAspects(), and Merge().
effect_epoch_
uint32_t v8::internal::maglev::KnownNodeAspects::effect_epoch_ [private]
Definition at line 594 of file maglev-interpreter-frame-state.h.
Referenced by effect_epoch(), increment_effect_epoch(), and Merge().
kEffectEpochForPureInstructions
constexpr uint32_t v8::internal::maglev::KnownNodeAspects::kEffectEpochForPureInstructions [static], [constexpr]
Initial value:
=
      std::numeric_limits<uint32_t>::max()
Definition at line 570 of file maglev-interpreter-frame-state.h.
Referenced by v8::internal::maglev::MaglevGraphBuilder::AddNewNodeOrGetEquivalent().
kEffectEpochOverflow
constexpr uint32_t v8::internal::maglev::KnownNodeAspects::kEffectEpochOverflow [static], [constexpr]
Initial value:
=
      kEffectEpochForPureInstructions - 1
Definition at line 572 of file maglev-interpreter-frame-state.h.
Referenced by v8::internal::maglev::MaglevGraphBuilder::AddNewNodeOrGetEquivalent(), and increment_effect_epoch().
loaded_constant_properties
LoadedPropertyMap v8::internal::maglev::KnownNodeAspects::loaded_constant_properties
Definition at line 533 of file maglev-interpreter-frame-state.h.
Referenced by Merge().
loaded_context_constants
ZoneMap<std::tuple<ValueNode*, int>, ValueNode*> v8::internal::maglev::KnownNodeAspects::loaded_context_constants
Definition at line 538 of file maglev-interpreter-frame-state.h.
Referenced by v8::internal::maglev::MaglevGraphBuilder::LoadAndCacheContextSlot(), and Merge().
loaded_context_slots
LoadedContextSlots v8::internal::maglev::KnownNodeAspects::loaded_context_slots
Definition at line 562 of file maglev-interpreter-frame-state.h.
Referenced by ClearUnstableNodeAspects(), IsCompatibleWithLoopHeader(), KnownNodeAspects(), v8::internal::maglev::MaglevGraphBuilder::LoadAndCacheContextSlot(), Merge(), and v8::internal::maglev::MaglevGraphBuilder::StoreAndCacheContextSlot().
loaded_properties
LoadedPropertyMap v8::internal::maglev::KnownNodeAspects::loaded_properties
Definition at line 535 of file maglev-interpreter-frame-state.h.
Referenced by v8::internal::maglev::NodeBase::ClearElementsProperties(), ClearUnstableNodeAspects(), IsCompatibleWithLoopHeader(), KnownNodeAspects(), and Merge().
may_have_aliasing_contexts_
ContextSlotLoadsAlias v8::internal::maglev::KnownNodeAspects::may_have_aliasing_contexts_ [private]
Definition at line 593 of file maglev-interpreter-frame-state.h.
Referenced by ClearUnstableNodeAspects(), KnownNodeAspects(), may_have_aliasing_contexts(), Merge(), and UpdateMayHaveAliasingContexts().
node_infos
NodeInfos v8::internal::maglev::KnownNodeAspects::node_infos [private]
Definition at line 596 of file maglev-interpreter-frame-state.h.
Referenced by ClearUnstableMaps(), ClearUnstableMapsIfAny(), FindInfo(), GetOrCreateInfoFor(), IsCompatibleWithLoopHeader(), IsValid(), KnownNodeAspects(), and Merge().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-interpreter-frame-state.h
/mnt/V8SourceCode/src/maglev/maglev-interpreter-frame-state.cc