v8::internal::wasm::ValidateFunctionsStreamingJobData Struct Reference
Classes
struct Unit
Public Member Functions
void Initialize (int num_declared_functions)
void AddUnit (int declared_func_index, base::Vector< const uint8_t > code, JobHandle *job_handle)
size_t NumOutstandingUnits () const
Unit GetUnit ()
void UpdateDetectedFeatures (WasmDetectedFeatures new_detected_features)
Public Attributes
base::OwnedVector< Unit > units
std::atomic< Unit * > next_available_unit
std::atomic< Unit * > end_of_available_units
std::atomic< bool > found_error {false}
std::atomic< WasmDetectedFeatures > detected_features
Detailed Description
Definition at line 2489 of file module-compiler.cc.
Member Function Documentation
AddUnit()
void v8::internal::wasm::ValidateFunctionsStreamingJobData::AddUnit (int declared_func_index, base::Vector< const uint8_t > code, JobHandle * job_handle) [inline]
Definition at line 2510 of file module-compiler.cc.
                                      {
    DCHECK_NOT_NULL(units);
    // Write new unit to {*end}, then increment {end}. There is only one thread
    // adding new units, so no further synchronization needed.
    Unit* ptr = end_of_available_units.load(std::memory_order_relaxed);
    // Check invariant: {next <= end}.
    DCHECK_LE(next_available_unit.load(std::memory_order_relaxed), ptr);
    *ptr++ = {declared_func_index, code};
    // Use release semantics, so whoever loads this pointer (using acquire
    // semantics) sees all our previous stores.
    end_of_available_units.store(ptr, std::memory_order_release);
    size_t total_units_added = ptr - units.begin();
    // Periodically notify concurrency increase. This has overhead, so avoid
    // calling it too often. As long as threads are still running they will
    // continue processing new units anyway, and if background threads validate
    // faster than we can add units, then only notifying after increasingly long
    // delays is the right thing to do to avoid too many small validation tasks.
    // We notify on each power of two after 16 units, and every 16k units (just
    // to have *some* upper limit and avoiding to pile up too many units).
    // Additionally, notify after receiving the last unit of the module.
    if ((total_units_added >= 16 &&
         base::bits::IsPowerOfTwo(total_units_added)) ||
        (total_units_added % (16 * 1024)) == 0 || ptr == units.end()) {
      job_handle->NotifyConcurrencyIncrease();
    }
  }
References code, DCHECK_LE, DCHECK_NOT_NULL, end_of_available_units, v8::base::bits::IsPowerOfTwo(), next_available_unit, v8::JobHandle::NotifyConcurrencyIncrease(), and units.
Referenced by v8::internal::wasm::AsyncStreamingProcessor::ProcessFunctionBody().
GetUnit()
Unit v8::internal::wasm::ValidateFunctionsStreamingJobData::GetUnit () [inline]
Definition at line 2547 of file module-compiler.cc.
                 {
    // Use an acquire load to synchronize with the store in {AddUnit}. All units
    // before this {end} are fully initialized and ready to execute.
    Unit* end = end_of_available_units.load(std::memory_order_acquire);
    Unit* next = next_available_unit.load(std::memory_order_relaxed);
    while (next < end) {
      if (next_available_unit.compare_exchange_weak(
              next, next + 1, std::memory_order_relaxed)) {
        return *next;
      }
      // Otherwise retry with updated {next} pointer.
    }
    return {};
  }
References v8::internal::compiler::end(), end_of_available_units, and next_available_unit.
Referenced by v8::internal::wasm::ValidateFunctionsStreamingJob::Run().
Initialize()
void v8::internal::wasm::ValidateFunctionsStreamingJobData::Initialize (int num_declared_functions) [inline]
Definition at line 2502 of file module-compiler.cc.
                                              {
    DCHECK_NULL(units);
    units = base::OwnedVector<Unit>::NewForOverwrite(num_declared_functions);
    // Initially {next == end}.
    next_available_unit.store(units.begin(), std::memory_order_relaxed);
    end_of_available_units.store(units.begin(), std::memory_order_relaxed);
  }
References DCHECK_NULL, end_of_available_units, v8::base::OwnedVector< T >::NewForOverwrite(), next_available_unit, and units.
Referenced by v8::internal::wasm::AsyncStreamingProcessor::ProcessFunctionBody().
NumOutstandingUnits()
size_t v8::internal::wasm::ValidateFunctionsStreamingJobData::NumOutstandingUnits () const [inline]
Definition at line 2538 of file module-compiler.cc.
                                     {
    Unit* next = next_available_unit.load(std::memory_order_relaxed);
    Unit* end = end_of_available_units.load(std::memory_order_relaxed);
    DCHECK_LE(next, end);
    return end - next;
  }
References DCHECK_LE, v8::internal::compiler::end(), end_of_available_units, and next_available_unit.
Referenced by v8::internal::wasm::ValidateFunctionsStreamingJob::GetMaxConcurrency().
UpdateDetectedFeatures()
void v8::internal::wasm::ValidateFunctionsStreamingJobData::UpdateDetectedFeatures (WasmDetectedFeatures new_detected_features) [inline]
Definition at line 2562 of file module-compiler.cc.
                                                                          {
    WasmDetectedFeatures old_features =
        detected_features.load(std::memory_order_relaxed);
    while (!detected_features.compare_exchange_weak(
        old_features, old_features | new_detected_features,
        std::memory_order_relaxed)) {
      // Retry with updated {old_features}.
    }
  }
References detected_features.
Referenced by v8::internal::wasm::ValidateFunctionsStreamingJob::Run().
Member Data Documentation
detected_features
std::atomic<WasmDetectedFeatures> v8::internal::wasm::ValidateFunctionsStreamingJobData::detected_features
Definition at line 2576 of file module-compiler.cc.
Referenced by v8::internal::wasm::AsyncStreamingProcessor::OnFinishedStream(), and UpdateDetectedFeatures().
end_of_available_units
std::atomic<Unit*> v8::internal::wasm::ValidateFunctionsStreamingJobData::end_of_available_units
Definition at line 2574 of file module-compiler.cc.
Referenced by AddUnit(), GetUnit(), Initialize(), and NumOutstandingUnits().
found_error
std::atomic<bool> v8::internal::wasm::ValidateFunctionsStreamingJobData::found_error {false}
Definition at line 2575 of file module-compiler.cc.
Referenced by v8::internal::wasm::AsyncStreamingProcessor::OnFinishedStream(), and v8::internal::wasm::ValidateFunctionsStreamingJob::Run().
next_available_unit
std::atomic<Unit*> v8::internal::wasm::ValidateFunctionsStreamingJobData::next_available_unit
Definition at line 2573 of file module-compiler.cc.
Referenced by AddUnit(), GetUnit(), Initialize(), and NumOutstandingUnits().
units
base::OwnedVector<Unit> v8::internal::wasm::ValidateFunctionsStreamingJobData::units
Definition at line 2572 of file module-compiler.cc.
Referenced by AddUnit(), and Initialize().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/wasm/module-compiler.cc