v8::internal::anonymous_namespace{debug-wasm-objects.cc}::MemoriesProxy Struct Reference
Static Public Member Functions
static uint32_t Count (Isolate *isolate, DirectHandle< WasmInstanceObject > instance)
static DirectHandle< Object > Get (Isolate *isolate, DirectHandle< WasmInstanceObject > instance, uint32_t index)
static DirectHandle< String > GetName (Isolate *isolate, DirectHandle< WasmInstanceObject > instance, uint32_t index)
Static Public Attributes
static constexpr char const * kClassName = `Memories`
Additional Inherited Members
Detailed Description
Definition at line 356 of file debug-wasm-objects.cc.
Member Function Documentation
Count()
static uint32_t v8::internal::anonymous_namespace{debug-wasm-objects.cc}::MemoriesProxy::Count (Isolate * isolate, DirectHandle< WasmInstanceObject > instance) [inline], [static]
Definition at line 359 of file debug-wasm-objects.cc.
                                                                   {
    return instance->trusted_data(isolate)->memory_objects()->length();
  }
Get()
static DirectHandle<Object> v8::internal::anonymous_namespace{debug-wasm-objects.cc}::MemoriesProxy::Get (Isolate * isolate, DirectHandle< WasmInstanceObject > instance, uint32_t index) [inline], [static]
Definition at line 364 of file debug-wasm-objects.cc.
                                                  {
    return direct_handle(instance->trusted_data(isolate)->memory_object(index),
                         isolate);
  }
References v8::internal::direct_handle(), and v8::internal::index.
GetName()
static DirectHandle<String> v8::internal::anonymous_namespace{debug-wasm-objects.cc}::MemoriesProxy::GetName (Isolate * isolate, DirectHandle< WasmInstanceObject > instance, uint32_t index) [inline], [static]
Definition at line 371 of file debug-wasm-objects.cc.
                                                      {
    wasm::NamesProvider* names =
        instance->module_object()->native_module()->GetNamesProvider();
    StringBuilder sb;
    names->PrintMemoryName(sb, index);
    return ToInternalString(sb, isolate);
  }
References v8::internal::index, v8::internal::wasm::NamesProvider::PrintMemoryName(), and v8::internal::anonymous_namespace{debug-wasm-objects.cc}::ToInternalString().
Member Data Documentation
kClassName
constexpr char const* v8::internal::anonymous_namespace{debug-wasm-objects.cc}::MemoriesProxy::kClassName = `Memories` [static], [constexpr]
Definition at line 357 of file debug-wasm-objects.cc.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/debug/debug-wasm-objects.cc