v8::internal::compiler::turboshaft::StringSubstringOp Struct Reference
#include <operations.h>
Public Member Functions
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
V< String > string () const
V< Word32 > start () const
V< Word32 > end () const
StringSubstringOp (V< String > string, V< Word32 > start, V< Word32 > end)
auto options () const
Static Public Attributes
static constexpr OpEffects effects
Additional Inherited Members
Detailed Description
Definition at line 5677 of file operations.h.
Constructor & Destructor Documentation
StringSubstringOp()
v8::internal::compiler::turboshaft::StringSubstringOp::StringSubstringOp (V< String > string, V< Word32 > start, V< Word32 > end) [inline]
Definition at line 5700 of file operations.h.
      : Base(string, start, end) {}
Member Function Documentation
end()
V<Word32> v8::internal::compiler::turboshaft::StringSubstringOp::end () const [inline]
Definition at line 5698 of file operations.h.
{ return Base::input<Word32>(2); }
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::StringSubstringOp::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 5689 of file operations.h.
                                                              {
    return MaybeRepVector<MaybeRegisterRepresentation::Tagged(),
                          MaybeRegisterRepresentation::Word32(),
                          MaybeRegisterRepresentation::Word32()>();
  }
References v8::internal::compiler::turboshaft::MaybeRepVector(), v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::Tagged(), and v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::Word32().
options()
auto v8::internal::compiler::turboshaft::StringSubstringOp::options () const [inline]
Definition at line 5704 of file operations.h.
{ return std::tuple{}; }
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::StringSubstringOp::outputs_rep () const [inline]
Definition at line 5685 of file operations.h.
                                                               {
    return RepVector<RegisterRepresentation::Tagged()>();
  }
start()
V<Word32> v8::internal::compiler::turboshaft::StringSubstringOp::start () const [inline]
Definition at line 5697 of file operations.h.
{ return Base::input<Word32>(1); }
string()
V<String> v8::internal::compiler::turboshaft::StringSubstringOp::string () const [inline]
Definition at line 5696 of file operations.h.
{ return Base::input<String>(0); }
Member Data Documentation
effects
constexpr OpEffects v8::internal::compiler::turboshaft::StringSubstringOp::effects [static], [constexpr]
Initial value:
=
      OpEffects()
          
          
          .CanAllocateWithoutIdentity()
          
          .CanDependOnChecks()
Definition at line 5678 of file operations.h.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h