cppgc::internal::BaseObjectSizeTrait Struct Reference
#include <object-size-trait.h>
Static Protected Member Functions
static size_t GetObjectSizeForGarbageCollected (const void *)
static size_t GetObjectSizeForGarbageCollectedMixin (const void *)
Detailed Description
Definition at line 17 of file object-size-trait.h.
Member Function Documentation
GetObjectSizeForGarbageCollected()
size_t cppgc::internal::BaseObjectSizeTrait::GetObjectSizeForGarbageCollected (const void * object) [static], [protected]
Definition at line 15 of file object-size-trait.cc.
                        {
  return ObjectView<AccessMode::kAtomic>(HeapObjectHeader::FromObject(object))
      .Size();
}
References cppgc::internal::HeapObjectHeader::FromObject(), and cppgc::internal::ObjectView< AccessMode >::Size().
GetObjectSizeForGarbageCollectedMixin()
size_t cppgc::internal::BaseObjectSizeTrait::GetObjectSizeForGarbageCollectedMixin (const void * address) [static], [protected]
Definition at line 22 of file object-size-trait.cc.
                         {
  // `address` is guaranteed to be on a normal page because large object mixins
  // are not supported.
  const auto& header =
      BasePage::FromPayload(address)
          ->ObjectHeaderFromInnerAddress<AccessMode::kAtomic>(address);
  DCHECK(!header.IsLargeObject<AccessMode::kAtomic>());
  return header.ObjectSize<AccessMode::kAtomic>();
}
References DCHECK, cppgc::internal::BasePage::FromPayload(), cppgc::internal::kAtomic, and cppgc::internal::BasePage::ObjectHeaderFromInnerAddress().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/include/cppgc/object-size-trait.h
/mnt/V8SourceCode/src/heap/cppgc/object-size-trait.cc