v8::internal::compiler::fast_api_call::OverloadsResolutionResult Struct Reference
#include <fast-api-calls.h>
Public Member Functions
OverloadsResolutionResult (int distinguishable_arg_index_, CTypeInfo::Type element_type_)
bool is_valid () const
Static Public Member Functions
static OverloadsResolutionResult Invalid ()
Public Attributes
int distinguishable_arg_index
CTypeInfo::Type element_type
Node * target_address = nullptr
Detailed Description
Definition at line 16 of file fast-api-calls.h.
Constructor & Destructor Documentation
OverloadsResolutionResult()
v8::internal::compiler::fast_api_call::OverloadsResolutionResult::OverloadsResolutionResult (int distinguishable_arg_index_, CTypeInfo::Type element_type_) [inline]
Definition at line 21 of file fast-api-calls.h.
      : distinguishable_arg_index(distinguishable_arg_index_),
        element_type(element_type_) {
    DCHECK(distinguishable_arg_index_ < 0 ||
           element_type_ != CTypeInfo::Type::kVoid);
  }
References v8::internal::DCHECK(), and v8::CTypeInfo::kVoid.
Referenced by Invalid().
Member Function Documentation
Invalid()
static OverloadsResolutionResult v8::internal::compiler::fast_api_call::OverloadsResolutionResult::Invalid () [inline], [static]
Definition at line 17 of file fast-api-calls.h.
                                             {
    return OverloadsResolutionResult(-1, CTypeInfo::Type::kVoid);
  }
References v8::CTypeInfo::kVoid, and OverloadsResolutionResult().
is_valid()
bool v8::internal::compiler::fast_api_call::OverloadsResolutionResult::is_valid () const [inline]
Definition at line 29 of file fast-api-calls.h.
{ return distinguishable_arg_index >= 0; }
References distinguishable_arg_index.
Member Data Documentation
distinguishable_arg_index
int v8::internal::compiler::fast_api_call::OverloadsResolutionResult::distinguishable_arg_index
Definition at line 33 of file fast-api-calls.h.
Referenced by is_valid().
element_type
CTypeInfo::Type v8::internal::compiler::fast_api_call::OverloadsResolutionResult::element_type
Definition at line 36 of file fast-api-calls.h.
target_address
Node* v8::internal::compiler::fast_api_call::OverloadsResolutionResult::target_address = nullptr
Definition at line 38 of file fast-api-calls.h.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/fast-api-calls.h