v8::internal::FrameSummaries Struct Reference
#include <frames.h>
Public Member Functions
FrameSummaries ()=default
FrameSummaries (FrameSummary summary)
int size () const
Public Attributes
std::vector< FrameSummary > frames
bool top_frame_is_construct_call = false
Detailed Description
Definition at line 627 of file frames.h.
Constructor & Destructor Documentation
FrameSummaries() [1/2]
v8::internal::FrameSummaries::FrameSummaries () [default]
FrameSummaries() [2/2]
v8::internal::FrameSummaries::FrameSummaries (FrameSummary summary) [inline], [explicit]
Definition at line 633 of file frames.h.
                                                : frames() {
    frames.push_back(summary);
  }
References frames.
Member Function Documentation
size()
int v8::internal::FrameSummaries::size () const [inline]
Definition at line 637 of file frames.h.
{ return static_cast<int>(frames.size()); }
References frames.
Referenced by v8::internal::anonymous_namespace{accessors.cc}::FindFunctionInFrame(), v8::internal::wasm::gdb_server::WasmModuleDebug::FindWasmFrame(), v8::internal::FrameSummary::Get(), v8::internal::wasm::gdb_server::WasmModuleDebug::GetCallStack(), v8::internal::FrameFunctionIterator::GetFrames(), v8::internal::FrameSummary::GetSingle(), v8::internal::FrameSummary::GetTop(), v8::internal::DebuggableStackFrameIterator::GetTopValidFrame(), v8::internal::Debug::PrepareStepOnThrow(), and v8::internal::DebugStackTraceIterator::UpdateInlineFrameIndexAndResumableFnOnStack().
Member Data Documentation
frames
std::vector<FrameSummary> v8::internal::FrameSummaries::frames
Definition at line 628 of file frames.h.
Referenced by v8::internal::anonymous_namespace{messages.cc}::ComputeLocation(), v8::internal::anonymous_namespace{accessors.cc}::FindFunctionInFrame(), v8::internal::wasm::gdb_server::WasmModuleDebug::FindWasmFrame(), FrameSummaries(), v8::internal::FrameSummary::Get(), v8::internal::wasm::gdb_server::WasmModuleDebug::GetCallStack(), v8::internal::MaglevFrame::GetInnermostFunction(), v8::internal::FrameSummary::GetSingle(), v8::internal::FrameSummary::GetTop(), v8::internal::DebuggableStackFrameIterator::GetTopValidFrame(), v8::internal::FrameFunctionIterator::next(), v8::internal::Debug::PrepareStepOnThrow(), v8::internal::RUNTIME_FUNCTION(), size(), v8::internal::StubFrame::Summarize(), v8::internal::OptimizedJSFrame::Summarize(), and v8::internal::anonymous_namespace{isolate.cc}::VisitStack().
top_frame_is_construct_call
bool v8::internal::FrameSummaries::top_frame_is_construct_call = false
Definition at line 629 of file frames.h.
Referenced by v8::internal::OptimizedJSFrame::Summarize(), and v8::internal::anonymous_namespace{isolate.cc}::VisitStack().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/execution/frames.h