v8::internal::compiler::turboshaft::LoopUnrollingPhase Struct Reference
#include <loop-unrolling-phase.h>
Public Member Functions
void Run (PipelineData *data, Zone *temp_zone)
Detailed Description
Definition at line 12 of file loop-unrolling-phase.h.
Member Function Documentation
Run()
void v8::internal::compiler::turboshaft::LoopUnrollingPhase::Run (PipelineData * data, Zone * temp_zone)
Definition at line 19 of file loop-unrolling-phase.cc.
                                                                {
  LoopUnrollingAnalyzer analyzer(temp_zone, &data->graph(), data->is_wasm());
  if (analyzer.CanUnrollAtLeastOneLoop()) {
    data->graph().set_loop_unrolling_analyzer(&analyzer);
    turboshaft::CopyingPhase<LoopStackCheckElisionReducer, LoopUnrollingReducer,
                             MachineOptimizationReducer,
                             ValueNumberingReducer>::Run(data, temp_zone);
    // When the CopyingPhase finishes, it calls SwapWithCompanion, which resets
    // the current graph's LoopUnrollingAnalyzer (since the old input_graph is
    // now somewhat out-dated).
    DCHECK(!data->graph().has_loop_unrolling_analyzer());
    // The LoopUnrollingAnalyzer should not be copied to the output_graph during
    // CopyingPhase, since it's refering to the input_graph.
    DCHECK(!data->graph().GetOrCreateCompanion().has_loop_unrolling_analyzer());
  }
}
References v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::CanUnrollAtLeastOneLoop(), v8::internal::DCHECK(), v8::internal::compiler::turboshaft::Graph::GetOrCreateCompanion(), v8::internal::compiler::turboshaft::PipelineData::graph(), v8::internal::compiler::turboshaft::PipelineData::is_wasm(), and v8::internal::compiler::turboshaft::Graph::set_loop_unrolling_analyzer().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/loop-unrolling-phase.h
/mnt/V8SourceCode/src/compiler/turboshaft/loop-unrolling-phase.cc