v8::internal::StructProxy Struct Reference
Static Public Member Functions
static DirectHandle< JSObject > Create (Isolate *isolate, DirectHandle< WasmStruct > value)
static uint32_t Count (Isolate *isolate, DirectHandle< WasmStruct > obj)
static DirectHandle< Object > Get (Isolate *isolate, DirectHandle< WasmStruct > obj, uint32_t index)
static DirectHandle< String > GetName (Isolate *isolate, DirectHandle< WasmStruct > obj, uint32_t index)
Static Public Attributes
static constexpr char const * kClassName = `Struct`
Detailed Description
Definition at line 906 of file debug-wasm-objects.cc.
Member Function Documentation
Count()
static uint32_t v8::internal::StructProxy::Count (Isolate * isolate, DirectHandle< WasmStruct > obj) [inline], [static]
Definition at line 914 of file debug-wasm-objects.cc.
                                                                        {
    wasm::CanonicalTypeIndex type_index =
        obj->map()->wasm_type_info()->type().ref_index();
    return wasm::GetTypeCanonicalizer()
        ->LookupStruct(type_index)
        ->field_count();
  }
References v8::internal::wasm::StructTypeBase::field_count(), v8::internal::wasm::GetTypeCanonicalizer(), and v8::internal::wasm::TypeCanonicalizer::LookupStruct().
Create()
static DirectHandle<JSObject> v8::internal::StructProxy::Create (Isolate * isolate, DirectHandle< WasmStruct > value) [inline], [static]
Definition at line 909 of file debug-wasm-objects.cc.
                                                                       {
    return NamedDebugProxy::Create(isolate, value);
  }
References v8::internal::value.
Referenced by v8::internal::WasmValueObject::New().
Get()
static DirectHandle<Object> v8::internal::StructProxy::Get (Isolate * isolate, DirectHandle< WasmStruct > obj, uint32_t index) [inline], [static]
Definition at line 922 of file debug-wasm-objects.cc.
                                                  {
    return WasmValueObject::New(isolate, obj->GetFieldValue(index));
  }
References v8::internal::index, and v8::internal::WasmValueObject::New().
GetName()
static DirectHandle<String> v8::internal::StructProxy::GetName (Isolate * isolate, DirectHandle< WasmStruct > obj, uint32_t index) [inline], [static]
Definition at line 928 of file debug-wasm-objects.cc.
                                                      {
    wasm::CanonicalTypeIndex struct_index =
        obj->map()->wasm_type_info()->type().ref_index();
    StringBuilder sb;
    wasm::GetCanonicalTypeNamesProvider()->PrintFieldName(sb, struct_index,
                                                          index);
    return ToInternalString(sb, isolate);
  }
References v8::internal::wasm::GetCanonicalTypeNamesProvider(), v8::internal::index, v8::internal::wasm::CanonicalTypeNamesProvider::PrintFieldName(), and v8::internal::anonymous_namespace{debug-wasm-objects.cc}::ToInternalString().
Member Data Documentation
kClassName
constexpr char const* v8::internal::StructProxy::kClassName = `Struct` [static], [constexpr]
Definition at line 907 of file debug-wasm-objects.cc.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/debug/debug-wasm-objects.cc