cppgc::internal::WriteBarrierTypeForNonCagedHeapPolicy::ValueModeDispatch< WriteBarrier::ValueMode::kValuePresent > Struct Reference
#include <write-barrier.h>
Static Public Member Functions
template<typename HeapHandleCallback >
static WriteBarrier::Type Get (const void *, const void *object, WriteBarrier::Params &params, HeapHandleCallback callback)
Detailed Description
Definition at line 343 of file write-barrier.h.
Member Function Documentation
Get()
template<typename HeapHandleCallback >
static WriteBarrier::Type cppgc::internal::WriteBarrierTypeForNonCagedHeapPolicy::ValueModeDispatch< WriteBarrier::ValueMode::kValuePresent >::Get (const void * , const void * object, WriteBarrier::Params & params, HeapHandleCallback callback) [inline], [static]
Definition at line 346 of file write-barrier.h.
                                                                       {
    // The following check covers nullptr as well as sentinel pointer.
    if (object <= static_cast<void*>(kSentinelPointer)) {
      return SetAndReturnType<WriteBarrier::Type::kNone>(params);
    }
    if (V8_LIKELY(!WriteBarrier::IsEnabled())) {
      return SetAndReturnType<WriteBarrier::Type::kNone>(params);
    }
    // We know that |object| is within the normal page or in the beginning of a
    // large page, so extract the page header by bitmasking.
    BasePageHandle* page =
        BasePageHandle::FromPayload(const_cast<void*>(object));
    HeapHandle& heap_handle = page->heap_handle();
    if (V8_LIKELY(heap_handle.is_incremental_marking_in_progress())) {
      return SetAndReturnType<WriteBarrier::Type::kMarking>(params);
    }
    return SetAndReturnType<WriteBarrier::Type::kNone>(params);
  }
References cppgc::internal::BasePageHandle::FromPayload(), cppgc::internal::BasePageHandle::heap_handle(), cppgc::HeapHandle::is_incremental_marking_in_progress(), cppgc::internal::WriteBarrier::IsEnabled(), cppgc::kSentinelPointer, and V8_LIKELY.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/include/cppgc/internal/write-barrier.h