v8::internal::compiler::turboshaft::FastApiCallOp Struct Reference
#include <operations.h>
Public Member Functions
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
MaybeRegisterRepresentation argument_representation (unsigned argument_index) const
V< FrameState > frame_state () const
V< Object > data_argument () const
V< Context > context () const
base::Vector< const OpIndex > arguments () const
FastApiCallOp (V< FrameState > frame_state, V< Object > data_argument, V< Context > context, base::Vector< const OpIndex > arguments, const FastApiCallParameters *parameters, base::Vector< const RegisterRepresentation > out_reps)
template<typename Fn , typename Mapper >
auto Explode (Fn fn, Mapper &mapper) const
auto options () const
Static Public Member Functions
static FastApiCallOp & New (Graph *graph, V< FrameState > frame_state, V< Object > data_argument, V< Context > context, base::Vector< const OpIndex > arguments, const FastApiCallParameters *parameters, base::Vector< const RegisterRepresentation > out_reps)
Public Attributes
const FastApiCallParameters * parameters
base::Vector< const RegisterRepresentation > out_reps
LazyDeoptOnThrow lazy_deopt_on_throw
Static Public Attributes
static constexpr uint32_t kSuccessValue = 1
static constexpr uint32_t kFailureValue = 0
static constexpr OpEffects effects = OpEffects().CanCallAnything()
static constexpr int kNumNonParamInputs = 3
Additional Inherited Members
Detailed Description
Definition at line 6442 of file operations.h.
Constructor & Destructor Documentation
FastApiCallOp()
v8::internal::compiler::turboshaft::FastApiCallOp::FastApiCallOp (V< FrameState > frame_state, V< Object > data_argument, V< Context > context, base::Vector< const OpIndex > arguments, const FastApiCallParameters * parameters, base::Vector< const RegisterRepresentation > out_reps) [inline]
Definition at line 6527 of file operations.h.
      : Base(kNumNonParamInputs + arguments.size()),
        parameters(parameters),
        out_reps(out_reps),
        lazy_deopt_on_throw(LazyDeoptOnThrow::kNo) {
    base::Vector<OpIndex> inputs = this->inputs();
    inputs[0] = frame_state;
    inputs[1] = data_argument;
    inputs[2] = context;
    inputs.SubVector(kNumNonParamInputs, kNumNonParamInputs + arguments.size())
        .OverwriteWith(arguments);
  }
References v8::internal::kNo, v8::base::Vector< T >::size(), and v8::base::Vector< T >::SubVector().
Member Function Documentation
argument_representation()
MaybeRegisterRepresentation v8::internal::compiler::turboshaft::FastApiCallOp::argument_representation (unsigned argument_index) const [inline]
Definition at line 6473 of file operations.h.
                                     {
    const CTypeInfo& arg_type =
        parameters->c_signature()->ArgumentInfo(argument_index);
    uint8_t flags = static_cast<uint8_t>(arg_type.GetFlags());
    START_ALLOW_USE_DEPRECATED()
    switch (arg_type.GetSequenceType()) {
      case CTypeInfo::SequenceType::kScalar:
        if (flags & (static_cast<uint8_t>(CTypeInfo::Flags::kEnforceRangeBit) |
                     static_cast<uint8_t>(CTypeInfo::Flags::kClampBit))) {
          return MaybeRegisterRepresentation::Float64();
        }
        switch (arg_type.GetType()) {
          case CTypeInfo::Type::kVoid:
            UNREACHABLE();
          case CTypeInfo::Type::kBool:
          case CTypeInfo::Type::kUint8:
          case CTypeInfo::Type::kInt32:
          case CTypeInfo::Type::kUint32:
            return MaybeRegisterRepresentation::Word32();
          case CTypeInfo::Type::kInt64:
          case CTypeInfo::Type::kUint64:
            return MaybeRegisterRepresentation::Word64();
          case CTypeInfo::Type::kV8Value:
          case CTypeInfo::Type::kApiObject:
          case CTypeInfo::Type::kPointer:
          case CTypeInfo::Type::kSeqOneByteString:
            return MaybeRegisterRepresentation::Tagged();
          case CTypeInfo::Type::kFloat32:
          case CTypeInfo::Type::kFloat64:
            return MaybeRegisterRepresentation::Float64();
          case CTypeInfo::Type::kAny:
            // As the register representation is unknown, just treat it as None
            // to prevent any validation.
            return MaybeRegisterRepresentation::None();
        }
      case CTypeInfo::SequenceType::kIsSequence:
        return MaybeRegisterRepresentation::Tagged();
      case CTypeInfo::SequenceType::kIsArrayBuffer:
        UNREACHABLE();
    }
    END_ALLOW_USE_DEPRECATED()
  }
References v8::CFunctionInfo::ArgumentInfo(), v8::internal::compiler::turboshaft::FastApiCallParameters::c_signature(), END_ALLOW_USE_DEPRECATED, v8::internal::flags, v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::Float64(), v8::CTypeInfo::GetFlags(), v8::CTypeInfo::GetSequenceType(), v8::CTypeInfo::GetType(), v8::CTypeInfo::kAny, v8::CTypeInfo::kApiObject, v8::CTypeInfo::kBool, v8::CTypeInfo::kClampBit, v8::CTypeInfo::kEnforceRangeBit, v8::CTypeInfo::kFloat32, v8::CTypeInfo::kFloat64, v8::CTypeInfo::kInt32, v8::CTypeInfo::kInt64, v8::CTypeInfo::kPointer, v8::CTypeInfo::kSeqOneByteString, v8::CTypeInfo::kUint32, v8::CTypeInfo::kUint64, v8::CTypeInfo::kUint8, v8::CTypeInfo::kV8Value, v8::CTypeInfo::kVoid, v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::None(), START_ALLOW_USE_DEPRECATED, v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::Tagged(), v8::internal::UNREACHABLE(), v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::Word32(), and v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::Word64().
arguments()
base::Vector<const OpIndex> v8::internal::compiler::turboshaft::FastApiCallOp::arguments () const [inline]
Definition at line 6523 of file operations.h.
                                              {
    return inputs().SubVector(kNumNonParamInputs, inputs().size());
  }
References size().
context()
V<Context> v8::internal::compiler::turboshaft::FastApiCallOp::context () const [inline]
Definition at line 6521 of file operations.h.
{ return input<Context>(2); }
data_argument()
V<Object> v8::internal::compiler::turboshaft::FastApiCallOp::data_argument () const [inline]
Definition at line 6519 of file operations.h.
{ return input<Object>(1); }
Explode()
template<typename Fn , typename Mapper >
auto v8::internal::compiler::turboshaft::FastApiCallOp::Explode (Fn fn, Mapper & mapper) const [inline]
Definition at line 6544 of file operations.h.
                                                      {
    V<FrameState> mapped_frame_state = mapper.Map(frame_state());
    OpIndex mapped_data_argument = mapper.Map(data_argument());
    V<Context> mapped_context = mapper.Map(context());
    auto mapped_arguments = mapper.template Map<8>(arguments());
    return fn(mapped_frame_state, mapped_data_argument, mapped_context,
              base::VectorOf(mapped_arguments), parameters, out_reps);
  }
References v8::base::VectorOf().
frame_state()
V<FrameState> v8::internal::compiler::turboshaft::FastApiCallOp::frame_state () const [inline]
Definition at line 6517 of file operations.h.
{ return input<FrameState>(0); }
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::FastApiCallOp::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 6459 of file operations.h.
                                                              {
    DCHECK_EQ(inputs().size(),
              kNumNonParamInputs + parameters->c_signature()->ArgumentCount());
    storage.resize(inputs().size());
    storage[0] = MaybeRegisterRepresentation::None();
    storage[1] = MaybeRegisterRepresentation::Tagged();
    storage[2] = MaybeRegisterRepresentation::Tagged();
    for (unsigned i = 0; i < parameters->c_signature()->ArgumentCount(); ++i) {
      storage[i + kNumNonParamInputs] = argument_representation(i);
    }
    return base::VectorOf(storage);
  }
References v8::CFunctionInfo::ArgumentCount(), v8::internal::compiler::turboshaft::FastApiCallParameters::c_signature(), DCHECK_EQ, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::None(), v8::internal::ZoneVector< T >::resize(), size(), v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::Tagged(), and v8::base::VectorOf().
New()
static FastApiCallOp& v8::internal::compiler::turboshaft::FastApiCallOp::New (Graph * graph, V< FrameState > frame_state, V< Object > data_argument, V< Context > context, base::Vector< const OpIndex > arguments, const FastApiCallParameters * parameters, base::Vector< const RegisterRepresentation > out_reps) [inline], [static]
Definition at line 6554 of file operations.h.
                                                         {
    return Base::New(graph, kNumNonParamInputs + arguments.size(), frame_state,
                     data_argument, context, arguments, parameters, out_reps);
  }
References graph(), v8::internal::anonymous_namespace{intl-objects.cc}::New(), and v8::base::Vector< T >::size().
options()
auto v8::internal::compiler::turboshaft::FastApiCallOp::options () const [inline]
Definition at line 6564 of file operations.h.
                       {
    DCHECK_EQ(out_reps[0], RegisterRepresentation::Word32());
    return std::tuple{parameters, out_reps[1], lazy_deopt_on_throw};
  }
References DCHECK_EQ, and v8::internal::compiler::turboshaft::RegisterRepresentation::Word32().
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::FastApiCallOp::outputs_rep () const [inline]
Definition at line 6457 of file operations.h.
{ return {}; }
Member Data Documentation
effects
constexpr OpEffects v8::internal::compiler::turboshaft::FastApiCallOp::effects = OpEffects().CanCallAnything() [static], [constexpr]
Definition at line 6450 of file operations.h.
kFailureValue
constexpr uint32_t v8::internal::compiler::turboshaft::FastApiCallOp::kFailureValue = 0 [static], [constexpr]
Definition at line 6444 of file operations.h.
Referenced by v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::FastApiCall(), and v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
kNumNonParamInputs
constexpr int v8::internal::compiler::turboshaft::FastApiCallOp::kNumNonParamInputs = 3 [static], [constexpr]
Definition at line 6454 of file operations.h.
kSuccessValue
constexpr uint32_t v8::internal::compiler::turboshaft::FastApiCallOp::kSuccessValue = 1 [static], [constexpr]
Definition at line 6443 of file operations.h.
Referenced by v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::FastApiCall().
lazy_deopt_on_throw
LazyDeoptOnThrow v8::internal::compiler::turboshaft::FastApiCallOp::lazy_deopt_on_throw
Definition at line 6448 of file operations.h.
out_reps
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::FastApiCallOp::out_reps
Definition at line 6447 of file operations.h.
parameters
const FastApiCallParameters* v8::internal::compiler::turboshaft::FastApiCallOp::parameters
Definition at line 6446 of file operations.h.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h