v8::internal::compiler::turboshaft::StoreOp Struct Reference
#include <operations.h>
Public Types
using Kind = LoadOp::Kind
Public Member Functions
OpEffects Effects () const
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
OpIndex base () const
OpIndex value () const
OptionalOpIndex index () const
IndirectPointerTag indirect_pointer_tag () const
StoreOp (OpIndex base, OptionalOpIndex index, OpIndex value, Kind kind, MemoryRepresentation stored_rep, WriteBarrierKind write_barrier, int32_t offset, uint8_t element_size_log2, bool maybe_initializing_or_transitioning, IndirectPointerTag maybe_indirect_pointer_tag=kIndirectPointerNullTag)
template<typename Fn , typename Mapper >
auto Explode (Fn fn, Mapper &mapper) const
void Validate (const Graph &graph) const
void PrintInputs (std::ostream &os, const std::string &op_index_prefix) const
void PrintOptions (std::ostream &os) const
auto options () const
Static Public Member Functions
static StoreOp & New (Graph *graph, OpIndex base, OptionalOpIndex index, OpIndex value, Kind kind, MemoryRepresentation stored_rep, WriteBarrierKind write_barrier, int32_t offset, uint8_t element_size_log2, bool maybe_initializing_or_transitioning, IndirectPointerTag maybe_indirect_pointer_tag=kIndirectPointerNullTag)
Public Attributes
Kind kind
MemoryRepresentation stored_rep
WriteBarrierKind write_barrier
uint8_t element_size_log2
int32_t offset
bool maybe_initializing_or_transitioning
uint16_t shifted_indirect_pointer_tag
Additional Inherited Members
Detailed Description
Definition at line 3384 of file operations.h.
Member Typedef Documentation
Kind
using v8::internal::compiler::turboshaft::StoreOp::Kind = LoadOp::Kind
Definition at line 3385 of file operations.h.
Constructor & Destructor Documentation
StoreOp()
v8::internal::compiler::turboshaft::StoreOp::StoreOp (OpIndex base, OptionalOpIndex index, OpIndex value, Kind kind, MemoryRepresentation stored_rep, WriteBarrierKind write_barrier, int32_t offset, uint8_t element_size_log2, bool maybe_initializing_or_transitioning, IndirectPointerTag maybe_indirect_pointer_tag = kIndirectPointerNullTag) [inline]
Definition at line 3447 of file operations.h.
      : Base(2 + index.valid()),
        kind(kind),
        stored_rep(stored_rep),
        write_barrier(write_barrier),
        element_size_log2(element_size_log2),
        offset(offset),
        maybe_initializing_or_transitioning(
            maybe_initializing_or_transitioning),
        shifted_indirect_pointer_tag(maybe_indirect_pointer_tag >>
                                     kIndirectPointerTagShift) {
    DCHECK_EQ(indirect_pointer_tag(), maybe_indirect_pointer_tag);
    input(0) = base;
    input(1) = value;
    if (index.valid()) {
      input(2) = index.value();
    }
  }
References DCHECK_EQ, v8::internal::index, and v8::internal::value.
Member Function Documentation
base()
OpIndex v8::internal::compiler::turboshaft::StoreOp::base () const [inline]
Definition at line 3436 of file operations.h.
{ return input(0); }
Referenced by PrintInputs(), and v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Store().
Effects()
OpEffects v8::internal::compiler::turboshaft::StoreOp::Effects () const [inline]
Definition at line 3403 of file operations.h.
                            {
    // Stores might depend on checks for pointer validity, object layout, bounds
    // checks, etc.
    // TODO(tebbi): Distinghish between on-heap and off-heap stores.
    OpEffects effects = OpEffects().CanWriteMemory().CanDependOnChecks();
    if (kind.with_trap_handler) effects = effects.CanLeaveCurrentFunction();
    if (maybe_initializing_or_transitioning) {
      effects = effects.CanDoRawHeapAccess();
    }
    if (kind.is_atomic) {
      // Atomic stores should not be eliminated away, even if the situation
      // seems to allow e.g. store-store elimination. Elimination is avoided by
      // setting the `CanReadMemory` effect.
      effects = effects.CanReadMemory();
    }
    return effects;
  }
References v8::internal::compiler::turboshaft::OpEffects::CanDependOnChecks(), v8::internal::compiler::turboshaft::OpEffects::CanDoRawHeapAccess(), v8::internal::compiler::turboshaft::OpEffects::CanLeaveCurrentFunction(), v8::internal::compiler::turboshaft::OpEffects::CanReadMemory(), and v8::internal::compiler::turboshaft::OpEffects::CanWriteMemory().
Explode()
template<typename Fn , typename Mapper >
auto v8::internal::compiler::turboshaft::StoreOp::Explode (Fn fn, Mapper & mapper) const [inline]
Definition at line 3472 of file operations.h.
                                                      {
    return fn(mapper.Map(base()), mapper.Map(index()), mapper.Map(value()),
              kind, stored_rep, write_barrier, offset, element_size_log2,
              maybe_initializing_or_transitioning, indirect_pointer_tag());
  }
References v8::internal::index, and v8::internal::value.
index()
OptionalOpIndex v8::internal::compiler::turboshaft::StoreOp::index () const [inline]
Definition at line 3438 of file operations.h.
                                {
    return input_count == 3 ? input(2) : OpIndex::Invalid();
  }
References v8::internal::compiler::turboshaft::detail::input_count(), and v8::internal::compiler::turboshaft::OpIndex::Invalid().
Referenced by PrintInputs(), and v8::internal::compiler::turboshaft::RedundantStoreAnalysis::ProcessBlock().
indirect_pointer_tag()
IndirectPointerTag v8::internal::compiler::turboshaft::StoreOp::indirect_pointer_tag () const [inline]
Definition at line 3442 of file operations.h.
                                                  {
    uint64_t shifted = shifted_indirect_pointer_tag;
    return static_cast<IndirectPointerTag>(shifted << kIndirectPointerTagShift);
  }
References v8::internal::kIndirectPointerTagShift.
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::StoreOp::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 3422 of file operations.h.
                                                              {
    RegisterRepresentation base = kind.tagged_base
                                      ? RegisterRepresentation::Tagged()
                                      : RegisterRepresentation::WordPtr();
    if (index() == OpIndex::Invalid()) {
      return InitVectorOf(
          storage, {base, stored_rep.ToRegisterRepresentationForStore()});
    }
    return InitVectorOf(storage,
                        {base, stored_rep.ToRegisterRepresentationForStore(),
                         RegisterRepresentation::WordPtr()});
  }
References v8::internal::index, v8::internal::compiler::turboshaft::InitVectorOf(), v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::compiler::turboshaft::RegisterRepresentation::Tagged(), v8::internal::compiler::turboshaft::MemoryRepresentation::ToRegisterRepresentationForStore(), and v8::internal::compiler::turboshaft::RegisterRepresentation::WordPtr().
New()
static StoreOp& v8::internal::compiler::turboshaft::StoreOp::New (Graph * graph, OpIndex base, OptionalOpIndex index, OpIndex value, Kind kind, MemoryRepresentation stored_rep, WriteBarrierKind write_barrier, int32_t offset, uint8_t element_size_log2, bool maybe_initializing_or_transitioning, IndirectPointerTag maybe_indirect_pointer_tag = kIndirectPointerNullTag) [inline], [static]
Definition at line 3484 of file operations.h.
                                                                               {
    return Base::New(graph, 2 + index.valid(), base, index, value, kind,
                     stored_rep, write_barrier, offset, element_size_log2,
                     maybe_initializing_or_transitioning,
                     maybe_indirect_pointer_tag);
  }
References graph(), v8::internal::index, v8::internal::anonymous_namespace{intl-objects.cc}::New(), and v8::internal::value.
options()
auto v8::internal::compiler::turboshaft::StoreOp::options () const [inline]
Definition at line 3498 of file operations.h.
                       {
    return std::tuple{
        kind, stored_rep, write_barrier,
        offset, element_size_log2, maybe_initializing_or_transitioning};
  }
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::StoreOp::outputs_rep () const [inline]
Definition at line 3420 of file operations.h.
{ return {}; }
PrintInputs()
void v8::internal::compiler::turboshaft::StoreOp::PrintInputs (std::ostream & os, const std::string & op_index_prefix) const
Definition at line 690 of file operations.cc.
                                                                  {
  os << " *(" << op_index_prefix << base().id();
  if (offset < 0) {
    os << " - " << -offset;
  } else if (offset > 0) {
    os << " + " << offset;
  }
  if (index().valid()) {
    os << " + " << op_index_prefix << index().value().id();
    if (element_size_log2 > 0) os << '*' << (1 << element_size_log2);
  }
  os << ") = " << op_index_prefix << value().id() << ' ';
}
References base(), element_size_log2, v8::internal::compiler::turboshaft::OpIndex::id(), index(), offset, v8::internal::compiler::turboshaft::OptionalOpIndex::value(), and value().
PrintOptions()
void v8::internal::compiler::turboshaft::StoreOp::PrintOptions (std::ostream & os) const
Definition at line 704 of file operations.cc.
                                               {
  os << '[';
  os << (kind.tagged_base ? "tagged base" : "raw");
  if (kind.maybe_unaligned) os << ", unaligned";
  if (kind.with_trap_handler) os << ", protected";
  os << ", " << stored_rep;
  os << ", " << write_barrier;
  if (element_size_log2 != 0)
    os << ", element size: 2^" << int{element_size_log2};
  if (offset != 0) os << ", offset: " << offset;
  if (maybe_initializing_or_transitioning) os << ", initializing";
  os << ']';
}
References element_size_log2, kind, maybe_initializing_or_transitioning, v8::internal::compiler::turboshaft::LoadOp::Kind::maybe_unaligned, offset, stored_rep, v8::internal::compiler::turboshaft::LoadOp::Kind::tagged_base, v8::internal::compiler::turboshaft::LoadOp::Kind::with_trap_handler, and write_barrier.
Validate()
void v8::internal::compiler::turboshaft::StoreOp::Validate (const Graph & graph) const [inline]
Definition at line 3478 of file operations.h.
                                          {
    DCHECK_IMPLIES(element_size_log2 > 0, index().valid());
    DCHECK_IMPLIES(kind.maybe_unaligned,
                   !SupportedOperations::IsUnalignedLoadSupported(stored_rep));
    DCHECK(LoadOp::OffsetIsValid(offset, kind.tagged_base));
  }
References v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::index, v8::internal::compiler::turboshaft::SupportedOperations::IsUnalignedLoadSupported(), and v8::internal::compiler::turboshaft::LoadOp::OffsetIsValid().
value()
OpIndex v8::internal::compiler::turboshaft::StoreOp::value () const [inline]
Definition at line 3437 of file operations.h.
{ return input(1); }
Referenced by PrintInputs(), and v8::internal::compiler::turboshaft::RedundantStoreAnalysis::ProcessBlock().
Member Data Documentation
element_size_log2
uint8_t v8::internal::compiler::turboshaft::StoreOp::element_size_log2
Definition at line 3389 of file operations.h.
Referenced by v8::internal::compiler::InstructionSelector::LoadView::element_size_log2(), v8::internal::compiler::InstructionSelector::StoreView::element_size_log2(), PrintInputs(), and PrintOptions().
kind
Kind v8::internal::compiler::turboshaft::StoreOp::kind
Definition at line 3386 of file operations.h.
Referenced by PrintOptions().
maybe_initializing_or_transitioning
bool v8::internal::compiler::turboshaft::StoreOp::maybe_initializing_or_transitioning
Definition at line 3391 of file operations.h.
Referenced by PrintOptions().
offset
int32_t v8::internal::compiler::turboshaft::StoreOp::offset
Definition at line 3390 of file operations.h.
Referenced by v8::internal::compiler::InstructionSelector::LoadView::displacement(), v8::internal::compiler::InstructionSelector::StoreView::displacement(), PrintInputs(), PrintOptions(), v8::internal::compiler::turboshaft::RedundantStoreAnalysis::ProcessBlock(), and v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Store().
shifted_indirect_pointer_tag
uint16_t v8::internal::compiler::turboshaft::StoreOp::shifted_indirect_pointer_tag
Definition at line 3393 of file operations.h.
stored_rep
MemoryRepresentation v8::internal::compiler::turboshaft::StoreOp::stored_rep
Definition at line 3387 of file operations.h.
Referenced by PrintOptions().
write_barrier
WriteBarrierKind v8::internal::compiler::turboshaft::StoreOp::write_barrier
Definition at line 3388 of file operations.h.
Referenced by PrintOptions().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h
/mnt/V8SourceCode/src/compiler/turboshaft/operations.cc