v8::internal::baseline::detail::PushAllHelper< Arg > Struct Template Reference
#include <baseline-assembler-arm-inl.h>
Static Public Member Functions
static int Push (BaselineAssembler *basm, Arg arg)
static int PushReverse (BaselineAssembler *basm, Arg arg)
static void Push (BaselineAssembler *basm, Arg)
static void PushReverse (BaselineAssembler *basm, Arg arg)
static int Push (BaselineAssembler *basm, Arg arg)
static int PushReverse (BaselineAssembler *basm, Arg arg)
static int Push (BaselineAssembler *basm, Arg arg)
static int PushReverse (BaselineAssembler *basm, Arg arg)
static int Push (BaselineAssembler *basm, Arg arg)
static int PushReverse (BaselineAssembler *basm, Arg arg)
static int Push (BaselineAssembler *basm, Arg arg)
static int PushReverse (BaselineAssembler *basm, Arg arg)
static int Push (BaselineAssembler *basm, Arg arg)
static int PushReverse (BaselineAssembler *basm, Arg arg)
Detailed Description
template<typename Arg>
struct v8::internal::baseline::detail::PushAllHelper< Arg >
Definition at line 240 of file baseline-assembler-arm-inl.h.
Member Function Documentation
Push() [1/7]
template<typename Arg >
static int v8::internal::baseline::detail::PushAllHelper< Arg >::Push (BaselineAssembler * basm, Arg arg) [inline], [static]
Definition at line 241 of file baseline-assembler-arm-inl.h.
                                                    {
    BaselineAssembler::ScratchRegisterScope scope(basm);
    basm->masm()->Push(ToRegister(basm, &scope, arg));
    return 1;
  }
References v8::internal::baseline::BaselineAssembler::masm(), v8::internal::MacroAssembler::Push(), and v8::internal::baseline::detail::ToRegister().
Push() [2/7]
template<typename Arg >
static int v8::internal::baseline::detail::PushAllHelper< Arg >::Push (BaselineAssembler * basm, Arg arg) [inline], [static]
Definition at line 239 of file baseline-assembler-loong64-inl.h.
                                                    {
    BaselineAssembler::ScratchRegisterScope scope(basm);
    basm->masm()->Push(ToRegister(basm, &scope, arg));
    return 1;
  }
References v8::internal::baseline::BaselineAssembler::masm(), v8::internal::MacroAssembler::Push(), and v8::internal::baseline::detail::ToRegister().
Push() [3/7]
template<typename Arg >
static int v8::internal::baseline::detail::PushAllHelper< Arg >::Push (BaselineAssembler * basm, Arg arg) [inline], [static]
Definition at line 236 of file baseline-assembler-mips64-inl.h.
                                                    {
    BaselineAssembler::ScratchRegisterScope scope(basm);
    basm->masm()->Push(ToRegister(basm, &scope, arg));
    return 1;
  }
References v8::internal::baseline::BaselineAssembler::masm(), v8::internal::MacroAssembler::Push(), and v8::internal::baseline::detail::ToRegister().
Push() [4/7]
template<typename Arg >
static int v8::internal::baseline::detail::PushAllHelper< Arg >::Push (BaselineAssembler * basm, Arg arg) [inline], [static]
Definition at line 324 of file baseline-assembler-ppc-inl.h.
                                                    {
    BaselineAssembler::ScratchRegisterScope scope(basm);
    basm->masm()->Push(ToRegister(basm, &scope, arg));
    return 1;
  }
References v8::internal::baseline::BaselineAssembler::masm(), v8::internal::MacroAssembler::Push(), and v8::internal::baseline::detail::ToRegister().
Push() [5/7]
template<typename Arg >
static int v8::internal::baseline::detail::PushAllHelper< Arg >::Push (BaselineAssembler * basm, Arg arg) [inline], [static]
Definition at line 248 of file baseline-assembler-riscv-inl.h.
                                                    {
    BaselineAssembler::ScratchRegisterScope scope(basm);
    basm->masm()->Push(ToRegister(basm, &scope, arg));
    return 1;
  }
References v8::internal::baseline::BaselineAssembler::masm(), v8::internal::MacroAssembler::Push(), and v8::internal::baseline::detail::ToRegister().
Push() [6/7]
template<typename Arg >
static int v8::internal::baseline::detail::PushAllHelper< Arg >::Push (BaselineAssembler * basm, Arg arg) [inline], [static]
Definition at line 324 of file baseline-assembler-s390-inl.h.
                                                    {
    BaselineAssembler::ScratchRegisterScope scope(basm);
    basm->masm()->Push(ToRegister(basm, &scope, arg));
    return 1;
  }
References v8::internal::baseline::BaselineAssembler::masm(), v8::internal::MacroAssembler::Push(), and v8::internal::baseline::detail::ToRegister().
Push() [7/7]
template<typename Arg >
static void v8::internal::baseline::detail::PushAllHelper< Arg >::Push (BaselineAssembler * basm, Arg) [inline], [static]
Definition at line 284 of file baseline-assembler-arm64-inl.h.
{ FATAL("Unaligned push"); }
References FATAL.
PushReverse() [1/7]
template<typename Arg >
static int v8::internal::baseline::detail::PushAllHelper< Arg >::PushReverse (BaselineAssembler * basm, Arg arg) [inline], [static]
Definition at line 246 of file baseline-assembler-arm-inl.h.
                                                           {
    return Push(basm, arg);
  }
PushReverse() [2/7]
template<typename Arg >
static void v8::internal::baseline::detail::PushAllHelper< Arg >::PushReverse (BaselineAssembler * basm, Arg arg) [inline], [static]
Definition at line 285 of file baseline-assembler-arm64-inl.h.
                                                            {
    // Push the padding register to round up the amount of values pushed.
    return PushAllReverse(basm, arg, padreg);
  }
References v8::internal::padreg, and v8::internal::baseline::detail::PushAllReverse().
PushReverse() [3/7]
template<typename Arg >
static int v8::internal::baseline::detail::PushAllHelper< Arg >::PushReverse (BaselineAssembler * basm, Arg arg) [inline], [static]
Definition at line 244 of file baseline-assembler-loong64-inl.h.
                                                           {
    return Push(basm, arg);
  }
PushReverse() [4/7]
template<typename Arg >
static int v8::internal::baseline::detail::PushAllHelper< Arg >::PushReverse (BaselineAssembler * basm, Arg arg) [inline], [static]
Definition at line 241 of file baseline-assembler-mips64-inl.h.
                                                           {
    return Push(basm, arg);
  }
PushReverse() [5/7]
template<typename Arg >
static int v8::internal::baseline::detail::PushAllHelper< Arg >::PushReverse (BaselineAssembler * basm, Arg arg) [inline], [static]
Definition at line 329 of file baseline-assembler-ppc-inl.h.
                                                           {
    return Push(basm, arg);
  }
PushReverse() [6/7]
template<typename Arg >
static int v8::internal::baseline::detail::PushAllHelper< Arg >::PushReverse (BaselineAssembler * basm, Arg arg) [inline], [static]
Definition at line 253 of file baseline-assembler-riscv-inl.h.
                                                           {
    return Push(basm, arg);
  }
PushReverse() [7/7]
template<typename Arg >
static int v8::internal::baseline::detail::PushAllHelper< Arg >::PushReverse (BaselineAssembler * basm, Arg arg) [inline], [static]
Definition at line 329 of file baseline-assembler-s390-inl.h.
                                                           {
    return Push(basm, arg);
  }
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/baseline/arm/baseline-assembler-arm-inl.h
/mnt/V8SourceCode/src/baseline/arm64/baseline-assembler-arm64-inl.h
/mnt/V8SourceCode/src/baseline/loong64/baseline-assembler-loong64-inl.h
/mnt/V8SourceCode/src/baseline/mips64/baseline-assembler-mips64-inl.h
/mnt/V8SourceCode/src/baseline/ppc/baseline-assembler-ppc-inl.h
/mnt/V8SourceCode/src/baseline/riscv/baseline-assembler-riscv-inl.h
/mnt/V8SourceCode/src/baseline/s390/baseline-assembler-s390-inl.h