v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::ExtendingLoadMatcher Struct Reference
Public Member Functions
ExtendingLoadMatcher (OpIndex node, InstructionSelector *selector)
bool Matches () const
OpIndex base () const
int64_t immediate () const
ArchOpcode opcode () const
Private Member Functions
void Initialize (OpIndex node)
Private Attributes
bool matches_
InstructionSelector * selector_
OpIndex base_ {}
int64_t immediate_
ArchOpcode opcode_
Detailed Description
Definition at line 262 of file instruction-selector-arm64.cc.
Constructor & Destructor Documentation
ExtendingLoadMatcher()
v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::ExtendingLoadMatcher::ExtendingLoadMatcher (OpIndex node, InstructionSelector * selector) [inline]
Definition at line 263 of file instruction-selector-arm64.cc.
      : matches_(false), selector_(selector), immediate_(0) {
    Initialize(node);
  }
Member Function Documentation
base()
OpIndex v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::ExtendingLoadMatcher::base () const [inline]
Definition at line 270 of file instruction-selector-arm64.cc.
                       {
    DCHECK(Matches());
    return base_;
  }
References v8::internal::DCHECK(), and v8::internal::anonymous_namespace{json-parser.cc}::Matches().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitExtendingLoad().
immediate()
int64_t v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::ExtendingLoadMatcher::immediate () const [inline]
Definition at line 274 of file instruction-selector-arm64.cc.
                            {
    DCHECK(Matches());
    return immediate_;
  }
References v8::internal::DCHECK(), and v8::internal::anonymous_namespace{json-parser.cc}::Matches().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitExtendingLoad().
Initialize()
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::ExtendingLoadMatcher::Initialize (OpIndex node) [inline], [private]
Definition at line 290 of file instruction-selector-arm64.cc.
                                {
    const ShiftOp& shift = selector_->Get(node).template Cast<ShiftOp>();
    DCHECK(shift.kind == ShiftOp::Kind::kShiftRightArithmetic ||
           shift.kind == ShiftOp::Kind::kShiftRightArithmeticShiftOutZeros);
    // When loading a 64-bit value and shifting by 32, we should
    // just load and sign-extend the interesting 4 bytes instead.
    // This happens, for example, when we're loading and untagging SMIs.
    const Operation& lhs = selector_->Get(shift.left());
    int64_t constant_rhs;
    if (lhs.Is<LoadOp>() &&
        selector_->MatchIntegralWord64Constant(shift.right(), &constant_rhs) &&
        constant_rhs == 32 && selector_->CanCover(node, shift.left())) {
      Arm64OperandGenerator g(selector_);
      const LoadOp& load = lhs.Cast<LoadOp>();
      base_ = load.base();
      opcode_ = kArm64Ldrsw;
      if (load.index().has_value()) {
        int64_t index_constant;
        if (selector_->MatchIntegralWord64Constant(load.index().value(),
                                                   &index_constant)) {
          DCHECK_EQ(load.element_size_log2, 0);
          immediate_ = index_constant + 4;
          matches_ = g.CanBeImmediate(immediate_, kLoadStoreImm32);
        }
      } else {
        immediate_ = load.offset + 4;
        matches_ = g.CanBeImmediate(immediate_, kLoadStoreImm32);
      }
    }
  }
References v8::internal::compiler::turboshaft::LoadOp::base(), v8::internal::compiler::Arm64OperandGenerator::CanBeImmediate(), v8::internal::compiler::InstructionSelector::CanCover(), v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::turboshaft::LoadOp::element_size_log2, v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::OptionalOpIndex::has_value(), v8::internal::compiler::turboshaft::LoadOp::index(), v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::compiler::turboshaft::ShiftOp::kind, v8::internal::compiler::kLoadStoreImm32, v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralWord64Constant(), v8::internal::compiler::turboshaft::LoadOp::offset, v8::internal::compiler::turboshaft::ShiftOp::right(), and v8::internal::compiler::turboshaft::OptionalOpIndex::value().
Matches()
bool v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::ExtendingLoadMatcher::Matches () const [inline]
Definition at line 268 of file instruction-selector-arm64.cc.
{ return matches_; }
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitExtendingLoad(), and v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryMatchExtendingLoad().
opcode()
ArchOpcode v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::ExtendingLoadMatcher::opcode () const [inline]
Definition at line 278 of file instruction-selector-arm64.cc.
                            {
    DCHECK(Matches());
    return opcode_;
  }
References v8::internal::DCHECK(), and v8::internal::anonymous_namespace{json-parser.cc}::Matches().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitExtendingLoad().
Member Data Documentation
base_
OpIndex v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::ExtendingLoadMatcher::base_ {} [private]
Definition at line 286 of file instruction-selector-arm64.cc.
immediate_
int64_t v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::ExtendingLoadMatcher::immediate_ [private]
Definition at line 287 of file instruction-selector-arm64.cc.
matches_
bool v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::ExtendingLoadMatcher::matches_ [private]
Definition at line 284 of file instruction-selector-arm64.cc.
opcode_
ArchOpcode v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::ExtendingLoadMatcher::opcode_ [private]
Definition at line 288 of file instruction-selector-arm64.cc.
selector_
InstructionSelector* v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::ExtendingLoadMatcher::selector_ [private]
Definition at line 285 of file instruction-selector-arm64.cc.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/arm64/instruction-selector-arm64.cc