v8::internal::TagRange< Tag > Struct Template Reference
#include <v8-internal.h>
Public Member Functions
constexpr TagRange (Tag first, Tag last)
constexpr TagRange (Tag tag)
constexpr TagRange ()
constexpr bool IsEmpty () const
constexpr size_t Size () const
constexpr bool Contains (Tag tag) const
constexpr bool Contains (TagRange tag_range) const
constexpr bool operator== (const TagRange other) const
constexpr size_t hash_value () const
Public Attributes
const Tag first
const Tag last
Detailed Description
template<typename Tag>
struct v8::internal::TagRange< Tag >
Definition at line 452 of file v8-internal.h.
Constructor & Destructor Documentation
TagRange() [1/3]
template<typename Tag >
constexpr v8::internal::TagRange< Tag >::TagRange (Tag first, Tag last) [inline], [constexpr]
Definition at line 458 of file v8-internal.h.
: first(first), last(last) {}
TagRange() [2/3]
template<typename Tag >
constexpr v8::internal::TagRange< Tag >::TagRange (Tag tag) [inline], [constexpr]
Definition at line 465 of file v8-internal.h.
      : first(tag), last(tag) {}
TagRange() [3/3]
template<typename Tag >
constexpr v8::internal::TagRange< Tag >::TagRange () [inline], [constexpr]
Definition at line 469 of file v8-internal.h.
: TagRange(static_cast<Tag>(0)) {}
Member Function Documentation
Contains() [1/2]
template<typename Tag >
constexpr bool v8::internal::TagRange< Tag >::Contains (Tag tag) const [inline], [constexpr]
Definition at line 482 of file v8-internal.h.
                                         {
    // Need to perform the math with uint32_t. Otherwise, the uint16_ts would
    // be promoted to (signed) int, allowing the compiler to (wrongly) assume
    // that an underflow cannot happen as that would be undefined behavior.
    return static_cast<uint32_t>(tag) - first <=
           static_cast<uint32_t>(last) - first;
  }
References v8::internal::TagRange< Tag >::first, and v8::internal::TagRange< Tag >::last.
Referenced by v8::internal::V8HeapExplorer::AddEntry(), v8::internal::ExternalPointerCanBeEmpty(), v8::internal::IsManagedExternalPointerType(), v8::internal::IsMaybeReadOnlyExternalPointerType(), and v8::internal::IsSharedExternalPointerType().
Contains() [2/2]
template<typename Tag >
constexpr bool v8::internal::TagRange< Tag >::Contains (TagRange< Tag > tag_range) const [inline], [constexpr]
Definition at line 490 of file v8-internal.h.
                                                    {
    return tag_range.first >= first && tag_range.last <= last;
  }
References v8::internal::TagRange< Tag >::first, and v8::internal::TagRange< Tag >::last.
hash_value()
template<typename Tag >
constexpr size_t v8::internal::TagRange< Tag >::hash_value () const [inline], [constexpr]
Definition at line 498 of file v8-internal.h.
                                      {
    static_assert(std::is_same_v<std::underlying_type_t<Tag>, uint16_t>);
    return (static_cast<size_t>(first) << 16) | last;
  }
References v8::internal::TagRange< Tag >::first, and v8::internal::TagRange< Tag >::last.
IsEmpty()
template<typename Tag >
constexpr bool v8::internal::TagRange< Tag >::IsEmpty () const [inline], [constexpr]
Definition at line 472 of file v8-internal.h.
{ return first == 0 && last == 0; }
References v8::internal::TagRange< Tag >::first, and v8::internal::TagRange< Tag >::last.
Referenced by v8::internal::compiler::WasmGraphAssembler::BuildLoadExternalPointerFromObject(), v8::internal::MacroAssembler::LoadExternalPointerField(), v8::internal::CodeStubAssembler::LoadExternalPointerFromObject(), v8::internal::TagRange< Tag >::Size(), v8::internal::compiler::turboshaft::DecodeExternalPointerOp::Validate(), v8::internal::ScavengeVisitor::VisitExternalPointer(), and v8::internal::IterateAndScavengePromotedObjectsVisitor::VisitExternalPointer().
operator==()
template<typename Tag >
constexpr bool v8::internal::TagRange< Tag >::operator== (const TagRange< Tag > other) const [inline], [constexpr]
Definition at line 494 of file v8-internal.h.
                                                        {
    return first == other.first && last == other.last;
  }
References v8::internal::TagRange< Tag >::first, and v8::internal::TagRange< Tag >::last.
Size()
template<typename Tag >
constexpr size_t v8::internal::TagRange< Tag >::Size () const [inline], [constexpr]
Definition at line 474 of file v8-internal.h.
                                {
    if (IsEmpty()) {
      return 0;
    } else {
      return last - first + 1;
    }
  }
References v8::internal::TagRange< Tag >::first, v8::internal::TagRange< Tag >::IsEmpty(), and v8::internal::TagRange< Tag >::last.
Referenced by v8::internal::compiler::WasmGraphAssembler::BuildDecodeSandboxedExternalPointer(), v8::internal::MacroAssembler::LoadExternalPointerField(), and v8::internal::CodeStubAssembler::LoadExternalPointerFromObject().
Member Data Documentation
first
template<typename Tag >
const Tag v8::internal::TagRange< Tag >::first
Definition at line 504 of file v8-internal.h.
Referenced by v8::internal::compiler::WasmGraphAssembler::BuildDecodeSandboxedExternalPointer(), v8::internal::TagRange< Tag >::Contains(), v8::internal::TagRange< Tag >::hash_value(), v8::internal::TagRange< Tag >::IsEmpty(), v8::internal::MacroAssembler::LoadExternalPointerField(), v8::internal::CodeStubAssembler::LoadExternalPointerFromObject(), v8::internal::TagRange< Tag >::operator==(), v8::internal::compiler::turboshaft::DecodeExternalPointerOp::PrintOptions(), and v8::internal::TagRange< Tag >::Size().
last
template<typename Tag >
const Tag v8::internal::TagRange< Tag >::last
Definition at line 505 of file v8-internal.h.
Referenced by v8::internal::TagRange< Tag >::Contains(), v8::internal::TagRange< Tag >::hash_value(), v8::internal::TagRange< Tag >::IsEmpty(), v8::internal::TagRange< Tag >::operator==(), v8::internal::compiler::turboshaft::DecodeExternalPointerOp::PrintOptions(), and v8::internal::TagRange< Tag >::Size().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/include/v8-internal.h