v8::internal::compiler::turboshaft::TaggedBitcastOp Struct Reference
#include <operations.h>
Public Types
enum class Kind : uint8_t { kSmi
, kHeapObject
, kTagAndSmiBits
, kAny
 }
Public Member Functions
OpEffects Effects () const
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
OpIndex input () const
TaggedBitcastOp (OpIndex input, RegisterRepresentation from, RegisterRepresentation to, Kind kind)
void Validate (const Graph &graph) const
auto options () const
Public Attributes
Kind kind
RegisterRepresentation from
RegisterRepresentation to
Additional Inherited Members
Detailed Description
Definition at line 2436 of file operations.h.
Member Enumeration Documentation
Kind
enum v8::internal::compiler::turboshaft::TaggedBitcastOp::Kind : uint8_t [strong]
Enumerator
kSmi
kHeapObject
kTagAndSmiBits
kAny
Definition at line 2437 of file operations.h.
                  : uint8_t {
    kSmi, // This is a bitcast from a Word to a Smi or from a Smi to a Word
    kHeapObject, // This is a bitcast from or to a Heap Object
    kTagAndSmiBits, // This is a bitcast where only access to the tag and the
                     // smi bits (if it's a smi) are valid
    kAny
  };
Constructor & Destructor Documentation
TaggedBitcastOp()
v8::internal::compiler::turboshaft::TaggedBitcastOp::TaggedBitcastOp (OpIndex input, RegisterRepresentation from, RegisterRepresentation to, Kind kind) [inline]
Definition at line 2472 of file operations.h.
      : Base(input), kind(kind), from(from), to(to) {}
Member Function Documentation
Effects()
OpEffects v8::internal::compiler::turboshaft::TaggedBitcastOp::Effects () const [inline]
Definition at line 2448 of file operations.h.
                            {
    switch (kind) {
      case Kind::kSmi:
      case Kind::kTagAndSmiBits:
        return OpEffects();
      case Kind::kHeapObject:
      case Kind::kAny:
        // Due to moving GC, converting from or to pointers doesn't commute with
        // GC.
        return OpEffects().CanDoRawHeapAccess();
    }
  }
References v8::internal::compiler::turboshaft::OpEffects::CanDoRawHeapAccess(), and v8::internal::compiler::kSmi.
input()
OpIndex v8::internal::compiler::turboshaft::TaggedBitcastOp::input () const [inline]
Definition at line 2470 of file operations.h.
{ return Base::input(0); }
Referenced by v8::internal::compiler::turboshaft::InstructionSelectionNormalizationReducer< Next >::IsComplexConstant(), and v8::internal::compiler::turboshaft::IsInt32TruncatedLoadPattern().
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::TaggedBitcastOp::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 2465 of file operations.h.
                                                              {
    return InputsRepFactory::SingleRep(from);
  }
References v8::internal::compiler::turboshaft::InputsRepFactory::SingleRep().
options()
auto v8::internal::compiler::turboshaft::TaggedBitcastOp::options () const [inline]
Definition at line 2493 of file operations.h.
{ return std::tuple{from, to, kind}; }
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::TaggedBitcastOp::outputs_rep () const [inline]
Definition at line 2461 of file operations.h.
                                                               {
    return base::VectorOf(&to, 1);
  }
References v8::base::VectorOf().
Validate()
void v8::internal::compiler::turboshaft::TaggedBitcastOp::Validate (const Graph & graph) const [inline]
Definition at line 2476 of file operations.h.
                                          {
    if (kind == Kind::kSmi) {
      DCHECK((from.IsWord() && to.IsTaggedOrCompressed()) ||
             (from.IsTaggedOrCompressed() && to.IsWord()));
      DCHECK_IMPLIES(from == RegisterRepresentation::Word64() ||
                         to == RegisterRepresentation::Word64(),
                     Is64());
    } else {
      // TODO(nicohartmann@): Without implicit truncation, the first case might
      // not be correct anymore.
      DCHECK((from.IsWord() && to == RegisterRepresentation::Tagged()) ||
             (from == RegisterRepresentation::Tagged() &&
              to == RegisterRepresentation::WordPtr()) ||
             (from == RegisterRepresentation::Compressed() &&
              to == RegisterRepresentation::Word32()));
    }
  }
References v8::internal::compiler::turboshaft::RegisterRepresentation::Compressed(), v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::Is64(), v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::IsTaggedOrCompressed(), v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::IsWord(), v8::internal::compiler::kSmi, v8::internal::compiler::turboshaft::RegisterRepresentation::Tagged(), v8::internal::compiler::turboshaft::RegisterRepresentation::Word32(), v8::internal::compiler::turboshaft::RegisterRepresentation::Word64(), and v8::internal::compiler::turboshaft::RegisterRepresentation::WordPtr().
Member Data Documentation
from
RegisterRepresentation v8::internal::compiler::turboshaft::TaggedBitcastOp::from
Definition at line 2445 of file operations.h.
Referenced by v8::internal::compiler::turboshaft::RunDecompressionOptimization(), and v8::internal::compiler::InstructionSelector::VisitNode().
kind
Kind v8::internal::compiler::turboshaft::TaggedBitcastOp::kind
Definition at line 2444 of file operations.h.
Referenced by v8::internal::compiler::InstructionSelector::VisitNode().
to
RegisterRepresentation v8::internal::compiler::turboshaft::TaggedBitcastOp::to
Definition at line 2446 of file operations.h.
Referenced by v8::internal::compiler::InstructionSelector::VisitNode().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h