cppgc::internal::EnsureGCInfoIndexTrait Struct Reference
#include <gc-info.h>
Classes
struct EnsureGCInfoIndexTraitDispatch
Static Public Member Functions
template<typename T >
static GCInfoIndex EnsureIndex (std::atomic< GCInfoIndex > &registered_index)
Static Private Member Functions
static GCInfoIndex V8_PRESERVE_MOST EnsureGCInfoIndex (std::atomic< GCInfoIndex > &, TraceCallback, FinalizationCallback, NameCallback)
static GCInfoIndex V8_PRESERVE_MOST EnsureGCInfoIndex (std::atomic< GCInfoIndex > &, TraceCallback, FinalizationCallback)
static GCInfoIndex V8_PRESERVE_MOST EnsureGCInfoIndex (std::atomic< GCInfoIndex > &, TraceCallback, NameCallback)
static GCInfoIndex V8_PRESERVE_MOST EnsureGCInfoIndex (std::atomic< GCInfoIndex > &, TraceCallback)
Detailed Description
Definition at line 23 of file gc-info.h.
Member Function Documentation
EnsureGCInfoIndex() [1/4]
GCInfoIndex cppgc::internal::EnsureGCInfoIndexTrait::EnsureGCInfoIndex (std::atomic< GCInfoIndex > & registered_index, TraceCallback trace_callback) [static], [private]
Definition at line 51 of file gc-info.cc.
                                                                            {
  return GlobalGCInfoTable::GetMutable().RegisterNewGCInfo(
      registered_index, GCInfo(nullptr, trace_callback, GetHiddenName));
}
References cppgc::internal::anonymous_namespace{gc-info.cc}::GetHiddenName(), cppgc::internal::GlobalGCInfoTable::GetMutable(), and cppgc::internal::GCInfoTable::RegisterNewGCInfo().
EnsureGCInfoIndex() [2/4]
GCInfoIndex cppgc::internal::EnsureGCInfoIndexTrait::EnsureGCInfoIndex (std::atomic< GCInfoIndex > & registered_index, TraceCallback trace_callback, FinalizationCallback finalization_callback) [static], [private]
Definition at line 34 of file gc-info.cc.
                                                {
  return GlobalGCInfoTable::GetMutable().RegisterNewGCInfo(
      registered_index,
      GCInfo(finalization_callback, trace_callback, GetHiddenName));
}
References cppgc::internal::anonymous_namespace{gc-info.cc}::GetHiddenName(), cppgc::internal::GlobalGCInfoTable::GetMutable(), and cppgc::internal::GCInfoTable::RegisterNewGCInfo().
EnsureGCInfoIndex() [3/4]
GCInfoIndex cppgc::internal::EnsureGCInfoIndexTrait::EnsureGCInfoIndex (std::atomic< GCInfoIndex > & registered_index, TraceCallback trace_callback, FinalizationCallback finalization_callback, NameCallback name_callback) [static], [private]
Definition at line 25 of file gc-info.cc.
                                                                            {
  return GlobalGCInfoTable::GetMutable().RegisterNewGCInfo(
      registered_index,
      GCInfo(finalization_callback, trace_callback, name_callback));
}
References cppgc::internal::GlobalGCInfoTable::GetMutable(), and cppgc::internal::GCInfoTable::RegisterNewGCInfo().
EnsureGCInfoIndex() [4/4]
GCInfoIndex cppgc::internal::EnsureGCInfoIndexTrait::EnsureGCInfoIndex (std::atomic< GCInfoIndex > & registered_index, TraceCallback trace_callback, NameCallback name_callback) [static], [private]
Definition at line 43 of file gc-info.cc.
                                {
  return GlobalGCInfoTable::GetMutable().RegisterNewGCInfo(
      registered_index, GCInfo(nullptr, trace_callback, name_callback));
}
References cppgc::internal::GlobalGCInfoTable::GetMutable(), and cppgc::internal::GCInfoTable::RegisterNewGCInfo().
EnsureIndex()
template<typename T >
static GCInfoIndex cppgc::internal::EnsureGCInfoIndexTrait::EnsureIndex (std::atomic< GCInfoIndex > & registered_index) [inline], [static]
Definition at line 27 of file gc-info.h.
                                                {
    return EnsureGCInfoIndexTraitDispatch<T>{}(registered_index);
  }
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/include/cppgc/internal/gc-info.h
/mnt/V8SourceCode/src/heap/cppgc/gc-info.cc