v8::internal::compiler::PrintGraphPhase Struct Reference
Public Member Functions
void Run (TFPipelineData *data, Zone *temp_zone, const char *phase)
Detailed Description
Definition at line 1508 of file pipeline.cc.
Member Function Documentation
Run()
void v8::internal::compiler::PrintGraphPhase::Run (TFPipelineData * data, Zone * temp_zone, const char * phase) [inline]
Definition at line 1511 of file pipeline.cc.
                                                                     {
    OptimizedCompilationInfo* info = data->info();
    TFGraph* graph = data->graph();
    if (info->trace_turbo_json()) { // Print JSON.
      UnparkedScopeIfNeeded scope(data->broker());
      AllowHandleDereference allow_deref;
      TurboJsonFile json_of(info, std::ios_base::app);
      json_of << "{\"name\":\"" << phase << "\",\"type\":\"graph\",\"data\":"
              << AsJSON(*graph, data->source_positions(), data->node_origins())
              << "},\n";
    }
    if (info->trace_turbo_scheduled()) {
      AccountingAllocator allocator;
      Schedule* schedule = data->schedule();
      if (schedule == nullptr) {
        schedule = Scheduler::ComputeSchedule(
            temp_zone, data->graph(), Scheduler::kNoFlags,
            &info->tick_counter(), data->profile_data());
      }
      UnparkedScopeIfNeeded scope(data->broker());
      AllowHandleDereference allow_deref;
      CodeTracer::StreamScope tracing_scope(data->GetCodeTracer());
      tracing_scope.stream()
          << "----- Graph after " << phase << " ----- " << std::endl
          << AsScheduledGraph(schedule);
    } else if (info->trace_turbo_graph()) { // Simple textual RPO.
      UnparkedScopeIfNeeded scope(data->broker());
      AllowHandleDereference allow_deref;
      CodeTracer::StreamScope tracing_scope(data->GetCodeTracer());
      tracing_scope.stream()
          << "----- Graph after " << phase << " ----- " << std::endl
          << AsRPO(*graph);
    }
  }
References v8::internal::compiler::AsJSON(), v8::internal::compiler::Scheduler::ComputeSchedule(), graph(), v8::internal::compiler::Scheduler::kNoFlags, v8::internal::CodeTracer::StreamScope::stream(), and v8::internal::OptimizedCompilationInfo::tick_counter().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/pipeline.cc