v8::internal::EncodedCSignature Struct Reference
#include <encoded-c-signature.h>
Public Member Functions
EncodedCSignature ()=default
EncodedCSignature (uint32_t bitfield, int parameter_count)
EncodedCSignature (int parameter_count)
EncodedCSignature (const CFunctionInfo *signature)
bool IsFloat (int index) const
bool IsReturnFloat () const
void SetFloat (int index)
void SetReturnFloat64 ()
void SetReturnFloat32 ()
bool IsValid () const
int ParameterCount () const
int FPParameterCount () const
Static Public Member Functions
static const EncodedCSignature & Invalid ()
Static Public Attributes
static const int kReturnIndex = 31
static const int kInvalidParamCount = kReturnIndex + 1
Private Attributes
uint32_t bitfield_ = 0
int parameter_count_ = kInvalidParamCount
Detailed Description
Definition at line 23 of file encoded-c-signature.h.
Constructor & Destructor Documentation
EncodedCSignature() [1/4]
v8::internal::EncodedCSignature::EncodedCSignature () [default]
EncodedCSignature() [2/4]
v8::internal::EncodedCSignature::EncodedCSignature (uint32_t bitfield, int parameter_count) [inline]
Definition at line 26 of file encoded-c-signature.h.
      : bitfield_(bitfield), parameter_count_(parameter_count) {}
EncodedCSignature() [3/4]
v8::internal::EncodedCSignature::EncodedCSignature (int parameter_count) [inline], [explicit]
Definition at line 28 of file encoded-c-signature.h.
      : parameter_count_(parameter_count) {}
EncodedCSignature() [4/4]
v8::internal::EncodedCSignature::EncodedCSignature (const CFunctionInfo * signature) [explicit]
Definition at line 20 of file encoded-c-signature.cc.
                                                                   {
  parameter_count_ = static_cast<int>(signature->ArgumentCount());
  for (int i = 0; i < parameter_count_; ++i) {
    if (signature->ArgumentInfo(i).GetSequenceType() ==
            CTypeInfo::SequenceType::kScalar &&
        CTypeInfo::IsFloatingPointType(signature->ArgumentInfo(i).GetType())) {
      SetFloat(i);
    }
  }
  // The struct holding the options of the CFunction (e.g. callback) is not
  // included in the number of regular parameters, so we add it manually here.
  if (signature->HasOptions()) {
    parameter_count_++;
  }
  if (signature->ReturnInfo().GetSequenceType() ==
          CTypeInfo::SequenceType::kScalar &&
      CTypeInfo::IsFloatingPointType(signature->ReturnInfo().GetType())) {
    if (signature->ReturnInfo().GetType() == CTypeInfo::Type::kFloat64) {
      SetReturnFloat64();
    } else {
      SetReturnFloat32();
    }
  }
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::CTypeInfo::IsFloatingPointType(), and v8::CTypeInfo::kFloat64.
Member Function Documentation
FPParameterCount()
int v8::internal::EncodedCSignature::FPParameterCount () const
Definition at line 14 of file encoded-c-signature.cc.
                                              {
  CHECK(IsValid());
  return base::bits::CountPopulation(bitfield_ & ~(1 << kReturnIndex));
}
References bitfield_, CHECK, v8::base::bits::CountPopulation(), IsValid(), and kReturnIndex.
Invalid()
static const EncodedCSignature& v8::internal::EncodedCSignature::Invalid () [inline], [static]
Definition at line 61 of file encoded-c-signature.h.
                                            {
    static EncodedCSignature kInvalid = {0, kInvalidParamCount};
    return kInvalid;
  }
References kInvalidParamCount.
IsFloat()
bool v8::internal::EncodedCSignature::IsFloat (int index) const [inline]
Definition at line 32 of file encoded-c-signature.h.
                                {
    return (bitfield_ & (static_cast<uint32_t>(1) << index)) != 0;
  }
References bitfield_, and v8::internal::index.
Referenced by IsReturnFloat().
IsReturnFloat()
bool v8::internal::EncodedCSignature::IsReturnFloat () const [inline]
Definition at line 35 of file encoded-c-signature.h.
{ return IsFloat(kReturnIndex); }
References IsFloat(), and kReturnIndex.
IsValid()
bool v8::internal::EncodedCSignature::IsValid () const [inline]
Definition at line 56 of file encoded-c-signature.h.
{ return parameter_count_ < kInvalidParamCount; }
References kInvalidParamCount, and parameter_count_.
Referenced by FPParameterCount().
ParameterCount()
int v8::internal::EncodedCSignature::ParameterCount () const [inline]
Definition at line 58 of file encoded-c-signature.h.
{ return parameter_count_; }
References parameter_count_.
SetFloat()
void v8::internal::EncodedCSignature::SetFloat (int index) [inline]
Definition at line 41 of file encoded-c-signature.h.
{ bitfield_ |= (static_cast<uint32_t>(1) << index); }
References bitfield_, and v8::internal::index.
Referenced by SetReturnFloat32(), and SetReturnFloat64().
SetReturnFloat32()
void v8::internal::EncodedCSignature::SetReturnFloat32 () [inline]
Definition at line 49 of file encoded-c-signature.h.
                          {
    SetFloat(kReturnIndex);
#ifdef V8_TARGET_ARCH_RISCV64
    return_type_is_float64_ = false;
#endif
  }
References kReturnIndex, and SetFloat().
SetReturnFloat64()
void v8::internal::EncodedCSignature::SetReturnFloat64 () [inline]
Definition at line 43 of file encoded-c-signature.h.
                          {
    SetFloat(kReturnIndex);
#ifdef V8_TARGET_ARCH_RISCV64
    return_type_is_float64_ = true;
#endif
  }
References kReturnIndex, and SetFloat().
Member Data Documentation
bitfield_
uint32_t v8::internal::EncodedCSignature::bitfield_ = 0 [private]
Definition at line 71 of file encoded-c-signature.h.
Referenced by FPParameterCount(), IsFloat(), and SetFloat().
kInvalidParamCount
const int v8::internal::EncodedCSignature::kInvalidParamCount = kReturnIndex + 1 [static]
Definition at line 67 of file encoded-c-signature.h.
Referenced by Invalid(), IsValid(), and v8::internal::compiler::CallDescriptor::ToEncodedCSignature().
kReturnIndex
const int v8::internal::EncodedCSignature::kReturnIndex = 31 [static]
Definition at line 66 of file encoded-c-signature.h.
Referenced by FPParameterCount(), IsReturnFloat(), SetReturnFloat32(), and SetReturnFloat64().
parameter_count_
int v8::internal::EncodedCSignature::parameter_count_ = kInvalidParamCount [private]
Definition at line 77 of file encoded-c-signature.h.
Referenced by IsValid(), and ParameterCount().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/execution/encoded-c-signature.h
/mnt/V8SourceCode/src/execution/encoded-c-signature.cc