v8::internal::wasm::WasmModule Struct Reference
#include <wasm-module.h>
Public Member Functions
WasmModule (ModuleOrigin=kWasmOrigin)
WasmModule (const WasmModule &)=delete
WasmModule & operator= (const WasmModule &)=delete
void AddTypeForTesting (TypeDefinition type)
void AddSignatureForTesting (const FunctionSig *sig, ModuleTypeIndex supertype, bool is_final, bool is_shared)
void AddStructTypeForTesting (const StructType *type, ModuleTypeIndex supertype, bool is_final, bool is_shared)
void AddArrayTypeForTesting (const ArrayType *type, ModuleTypeIndex supertype, bool is_final, bool is_shared)
void AddContTypeForTesting (const ContType *type, ModuleTypeIndex supertype, bool is_final, bool is_shared)
bool has_type (ModuleTypeIndex index) const
const TypeDefinition & type (ModuleTypeIndex index) const
HeapType heap_type (ModuleTypeIndex index) const
CanonicalTypeIndex canonical_type_id (ModuleTypeIndex index) const
CanonicalValueType canonical_type (ValueType type) const
bool has_signature (ModuleTypeIndex index) const
const FunctionSig * signature (ModuleTypeIndex index) const
bool has_cont_type (ModuleTypeIndex index) const
const ContType * cont_type (ModuleTypeIndex index) const
CanonicalTypeIndex canonical_sig_id (ModuleTypeIndex index) const
uint64_t signature_hash (const TypeCanonicalizer *, uint32_t function_index) const
bool has_struct (ModuleTypeIndex index) const
const StructType * struct_type (ModuleTypeIndex index) const
bool has_array (ModuleTypeIndex index) const
const ArrayType * array_type (ModuleTypeIndex index) const
ModuleTypeIndex supertype (ModuleTypeIndex index) const
bool has_supertype (ModuleTypeIndex index) const
CanonicalTypeIndex MaxCanonicalTypeIndex () const
bool function_is_shared (int func_index) const
bool function_was_validated (int func_index) const
void set_function_validated (int func_index) const
void set_all_functions_validated () const
base::Vector< const WasmFunction > declared_functions () const
size_t EstimateStoredSize () const
size_t EstimateCurrentMemoryConsumption () const
Public Attributes
Zone signature_zone
int start_function_index = -1
uint32_t untagged_globals_buffer_size = 0
uint32_t tagged_globals_buffer_size = 0
uint32_t num_imported_globals = 0
uint32_t num_imported_mutable_globals = 0
uint32_t num_imported_functions = 0
uint32_t num_imported_tables = 0
uint32_t num_imported_tags = 0
uint32_t num_declared_functions = 0
std::atomic< uint32_t > num_small_functions = 0
uint32_t num_exported_functions = 0
uint32_t num_declared_data_segments = 0
WireBytesRef code = {0, 0}
WireBytesRef name = {0, 0}
WireBytesRef name_section = {0, 0}
WireBytesRef descriptors_section = {0, 0}
std::atomic< bool > canonical_typenames_decoded = false
bool is_wasm_gc = false
bool has_shared_part = false
std::vector< TypeDefinition > types
std::vector< CanonicalTypeIndex > isorecursive_canonical_type_ids
std::vector< WasmFunction > functions
std::vector< WasmGlobal > globals
std::vector< WasmDataSegment > data_segments
std::vector< WasmTable > tables
std::vector< WasmMemory > memories
std::vector< WasmImport > import_table
std::vector< WasmExport > export_table
std::vector< WasmTag > tags
std::vector< WasmStringRefLiteral > stringref_literals
std::vector< WasmElemSegment > elem_segments
std::vector< WasmCompilationHint > compilation_hints
BranchHintInfo branch_hints
std::vector< std::pair< uint32_t, uint32_t > > inst_traces
TypeFeedbackStorage type_feedback
const ModuleOrigin origin
LazilyGeneratedNames lazily_generated_names
std::array< WasmDebugSymbols, WasmDebugSymbols::kNumTypes > debug_symbols {}
WireBytesRef build_id
std::unique_ptr< AsmJsOffsetInformation > asm_js_offset_information
std::unique_ptr< std::atomic< uint8_t >[]> validated_functions
Detailed Description
Definition at line 666 of file wasm-module.h.
Constructor & Destructor Documentation
WasmModule() [1/2]
v8::internal::wasm::WasmModule::WasmModule (ModuleOrigin origin = kWasmOrigin) [explicit]
Definition at line 244 of file wasm-module.cc.
    : signature_zone(GetWasmEngine()->allocator(), "signature zone"),
      origin(origin) {}
Referenced by EstimateStoredSize().
WasmModule() [2/2]
v8::internal::wasm::WasmModule::WasmModule (const WasmModule &) [delete]
Member Function Documentation
AddArrayTypeForTesting()
void v8::internal::wasm::WasmModule::AddArrayTypeForTesting (const ArrayType * type, ModuleTypeIndex supertype, bool is_final, bool is_shared) [inline]
Definition at line 784 of file wasm-module.h.
                                                             {
    DCHECK_NOT_NULL(type);
    AddTypeForTesting(TypeDefinition(type, supertype, is_final, is_shared));
  }
References DCHECK_NOT_NULL, v8::internal::is_shared, and v8::internal::wasm::WasmElemSegment::type.
AddContTypeForTesting()
void v8::internal::wasm::WasmModule::AddContTypeForTesting (const ContType * type, ModuleTypeIndex supertype, bool is_final, bool is_shared) [inline]
Definition at line 790 of file wasm-module.h.
                                                            {
    DCHECK_NOT_NULL(type);
    AddTypeForTesting(TypeDefinition(type, supertype, is_final, is_shared));
  }
References DCHECK_NOT_NULL, v8::internal::is_shared, and v8::internal::wasm::WasmElemSegment::type.
AddSignatureForTesting()
void v8::internal::wasm::WasmModule::AddSignatureForTesting (const FunctionSig * sig, ModuleTypeIndex supertype, bool is_final, bool is_shared) [inline]
Definition at line 771 of file wasm-module.h.
                                                             {
    DCHECK_NOT_NULL(sig);
    AddTypeForTesting(TypeDefinition(sig, supertype, is_final, is_shared));
  }
References DCHECK_NOT_NULL, v8::internal::is_shared, and v8::internal::sig.
AddStructTypeForTesting()
void v8::internal::wasm::WasmModule::AddStructTypeForTesting (const StructType * type, ModuleTypeIndex supertype, bool is_final, bool is_shared) [inline]
Definition at line 777 of file wasm-module.h.
                                               {
    DCHECK_NOT_NULL(type);
    AddTypeForTesting(TypeDefinition(type, supertype, is_final, is_shared));
  }
References DCHECK_NOT_NULL, v8::internal::is_shared, and v8::internal::wasm::WasmElemSegment::type.
AddTypeForTesting()
void v8::internal::wasm::WasmModule::AddTypeForTesting (TypeDefinition type) [inline]
Definition at line 757 of file wasm-module.h.
                                              {
    types.push_back(type);
    if (type.supertype.valid()) {
      // Set the subtyping depth. Outside of unit tests this is done by the
      // module decoder.
      DCHECK_GT(types.size(), 0);
      DCHECK_LT(type.supertype.index, types.size() - 1);
      types.back().subtyping_depth =
          this->type(type.supertype).subtyping_depth + 1;
    }
    // Isorecursive canonical type will be computed later.
    isorecursive_canonical_type_ids.push_back(CanonicalTypeIndex{kNoSuperType});
  }
References DCHECK_GT, DCHECK_LT, v8::internal::wasm::kNoSuperType, v8::internal::wasm::TypeDefinition::supertype, and v8::internal::wasm::WasmElemSegment::type.
array_type()
const ArrayType* v8::internal::wasm::WasmModule::array_type (ModuleTypeIndex index) const [inline]
Definition at line 876 of file wasm-module.h.
                                                           {
    DCHECK(has_array(index));
    size_t num_types = types.size();
    V8_ASSUME(index.index < num_types);
    return types[index.index].array_type;
  }
References v8::internal::DCHECK(), v8::internal::index, and V8_ASSUME.
Referenced by v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction(), v8::internal::wasm::WasmInterpreterRuntime::GetArrayType(), and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate().
canonical_sig_id()
CanonicalTypeIndex v8::internal::wasm::WasmModule::canonical_sig_id (ModuleTypeIndex index) const [inline]
Definition at line 850 of file wasm-module.h.
                                                                   {
    DCHECK(has_signature(index));
    size_t num_types = isorecursive_canonical_type_ids.size();
    V8_ASSUME(index.index < num_types);
    return isorecursive_canonical_type_ids[index.index];
  }
References v8::internal::DCHECK(), v8::internal::index, and V8_ASSUME.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildIndirectCallTargetAndImplicitArg(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallIndirectImpl(), v8::internal::wasm::NativeModuleSerializer::CanonicalSigIdToModuleLocalTypeId(), v8::internal::wasm::WasmInterpreterRuntime::CheckIndirectCallSignature(), v8::internal::wasm::WasmInterpreterRuntime::ContinueExecution(), v8::internal::wasm::NativeModuleDeserializer::CopyAndRelocate(), v8::internal::wasm::WasmBytecodeGenerator::GenerateBytecode(), v8::internal::WasmInternalFunction::GetOrCreateExternal(), v8::internal::WasmExportedFunction::New(), v8::internal::wasm::InstanceBuilder::ProcessExports(), v8::internal::wasm::InstanceBuilder::ProcessImportedFunction(), v8::internal::wasm::InstanceBuilder::ProcessImports(), v8::internal::RUNTIME_FUNCTION(), signature_hash(), and v8::internal::WasmTableObject::UpdateDispatchTable().
canonical_type()
CanonicalValueType v8::internal::wasm::WasmModule::canonical_type (ValueType type) const [inline]
Definition at line 820 of file wasm-module.h.
                                                          {
    if (!type.has_index()) {
      return CanonicalValueType{type};
    }
    return type.Canonicalize(canonical_type_id(type.ref_index()));
  }
References v8::internal::wasm::ValueType::Canonicalize(), v8::internal::wasm::ValueTypeBase::has_index(), v8::internal::wasm::ValueType::ref_index(), and v8::internal::wasm::WasmElemSegment::type.
Referenced by v8::internal::wasm::InstanceBuilder::Build_Phase1(), v8::internal::WasmTableObject::canonical_type(), v8::internal::wasm::anonymous_namespace{constant-expression-interface.cc}::DefaultValueForType(), v8::internal::wasm::EvaluateConstantExpression(), v8::internal::wasm::JSToWasmObject(), v8::internal::wasm::InstanceBuilder::ProcessImportedGlobal(), v8::internal::wasm::InstanceBuilder::ProcessImportedTable(), v8::internal::wasm::InstanceBuilder::ProcessImportedWasmGlobalObject(), and v8::internal::wasm::InstanceBuilder::WriteGlobalValue().
canonical_type_id()
CanonicalTypeIndex v8::internal::wasm::WasmModule::canonical_type_id (ModuleTypeIndex index) const [inline]
Definition at line 813 of file wasm-module.h.
                                                                    {
    size_t num_types = isorecursive_canonical_type_ids.size();
    DCHECK_EQ(num_types, types.size());
    V8_ASSUME(index.index < num_types);
    return isorecursive_canonical_type_ids[index.index];
  }
References DCHECK_EQ, v8::internal::index, and V8_ASSUME.
Referenced by v8::internal::WasmStruct::AllocateDescriptorUninitialized(), v8::internal::wasm::TypeCanonicalizer::CanonicalizeTypeDef(), v8::internal::wasm::CreateMapForType(), v8::internal::wasm::DecodeCanonicalTypeNames(), v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::EquivalentIndices(), v8::internal::wasm::EquivalentTypes(), v8::internal::wasm::ConstantExpressionInterface::GetRtt(), v8::internal::wasm::TypeCanonicalizer::IsCanonicalSubtype(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::IsI16Array(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::IsI8Array(), v8::internal::wasm::IsSubtypeOfImpl(), and signature_hash().
cont_type()
const ContType* v8::internal::wasm::WasmModule::cont_type (ModuleTypeIndex index) const [inline]
Definition at line 843 of file wasm-module.h.
                                                         {
    DCHECK(has_cont_type(index));
    size_t num_types = types.size();
    V8_ASSUME(index.index < num_types);
    return types[index.index].cont_type;
  }
References v8::internal::DCHECK(), v8::internal::index, and V8_ASSUME.
Referenced by v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::ValidateCont().
declared_functions()
base::Vector<const WasmFunction> v8::internal::wasm::WasmModule::declared_functions () const [inline]
Definition at line 943 of file wasm-module.h.
                                                            {
    return base::VectorOf(functions) + num_imported_functions;
  }
References v8::base::VectorOf().
Referenced by v8::internal::wasm::NativeModuleSerializer::WriteHeader().
EstimateCurrentMemoryConsumption()
size_t v8::internal::wasm::WasmModule::EstimateCurrentMemoryConsumption () const
Definition at line 801 of file wasm-module.cc.
                                                          {
  UPDATE_WHEN_CLASS_CHANGES(WasmModule,
#if V8_ENABLE_DRUMBRAKE
                            808
#else // V8_ENABLE_DRUMBRAKE
                            776
#endif // V8_ENABLE_DRUMBRAKE
  );
  size_t result = EstimateStoredSize();
  result += type_feedback.EstimateCurrentMemoryConsumption();
  // For type_feedback.well_known_imports:
  result += num_imported_functions * sizeof(WellKnownImport);
  result += lazily_generated_names.EstimateCurrentMemoryConsumption();
  if (v8_flags.trace_wasm_offheap_memory) {
    PrintF("WasmModule: %zu\n", result);
  }
  return result;
}
References v8::internal::PrintF(), v8::base::internal::result, UPDATE_WHEN_CLASS_CHANGES, and v8::internal::v8_flags.
EstimateStoredSize()
size_t v8::internal::wasm::WasmModule::EstimateStoredSize () const
Definition at line 722 of file wasm-module.cc.
                                            {
  UPDATE_WHEN_CLASS_CHANGES(WasmModule,
#if V8_ENABLE_DRUMBRAKE
                            808
#else // V8_ENABLE_DRUMBRAKE
                            776
#endif // V8_ENABLE_DRUMBRAKE
  );
  return sizeof(WasmModule) + // --
         signature_zone.allocation_size_for_tracing() + // --
         ContentSize(types) + // --
         ContentSize(isorecursive_canonical_type_ids) + // --
         ContentSize(functions) + // --
         ContentSize(globals) + // --
         ContentSize(data_segments) + // --
         ContentSize(tables) + // --
         ContentSize(memories) + // --
         ContentSize(import_table) + // --
         ContentSize(export_table) + // --
         ContentSize(tags) + // --
         ContentSize(stringref_literals) + // --
         ContentSize(elem_segments) + // --
         ContentSize(compilation_hints) + // --
         ContentSize(branch_hints) + // --
         ContentSize(inst_traces) + // --
         (num_declared_functions + 7) / 8; // validated_functions
}
References v8::internal::Zone::allocation_size_for_tracing(), branch_hints, compilation_hints, v8::internal::wasm::ContentSize(), data_segments, elem_segments, export_table, functions, globals, import_table, inst_traces, isorecursive_canonical_type_ids, memories, num_declared_functions, signature_zone, stringref_literals, tables, tags, types, UPDATE_WHEN_CLASS_CHANGES, and WasmModule().
Referenced by v8::internal::wasm::WasmCodeManager::EstimateNativeModuleMetaDataSize().
function_is_shared()
bool v8::internal::wasm::WasmModule::function_is_shared (int func_index) const [inline]
Definition at line 901 of file wasm-module.h.
                                                {
    return type(functions[func_index].sig_index).is_shared;
  }
References v8::internal::wasm::ValueTypeBase::is_shared(), and v8::internal::wasm::WasmElemSegment::type.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::CallDirect(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallRef(), v8::internal::wasm::JSPrototypesSetup::GetExportedFunction(), v8::internal::wasm::JSPrototypesSetup::GetFunction(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineWasmCall(), v8::internal::wasm::InstanceBuilder::ProcessExports(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ReturnCall(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ReturnCallRef(), v8::internal::wasm::TurboshaftGraphBuildingInterface::should_inline(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate(), and v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::WasmRefFunc().
function_was_validated()
bool v8::internal::wasm::WasmModule::function_was_validated (int func_index) const [inline]
Definition at line 905 of file wasm-module.h.
                                                    {
    DCHECK_NOT_NULL(validated_functions);
    static_assert(sizeof(validated_functions[0]) == 1);
    DCHECK_LE(num_imported_functions, func_index);
    int pos = func_index - num_imported_functions;
    DCHECK_LE(pos, num_declared_functions);
    uint8_t byte =
        validated_functions[pos >> 3].load(std::memory_order_relaxed);
    DCHECK_IMPLIES(origin != kWasmOrigin, byte == 0xff);
    return byte & (1 << (pos & 7));
  }
References DCHECK_IMPLIES, DCHECK_LE, DCHECK_NOT_NULL, and v8::internal::wasm::kWasmOrigin.
Referenced by v8::internal::wasm::BuildTSGraph(), v8::internal::wasm::WasmCompilationUnit::ExecuteCompilation(), v8::internal::wasm::ExecuteLiftoffCompilation(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineWasmCall(), v8::internal::wasm::DebugInfoImpl::RecompileLiftoffWithBreakpoints(), v8::internal::compiler::WasmGraphBuilder::TryWasmInlining(), v8::internal::anonymous_namespace{runtime-test-wasm.cc}::ValidateFunctionNowIfNeeded(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ValidateSingleFunction(), and v8::internal::wasm::NativeModuleSerializer::WriteHeader().
has_array()
bool v8::internal::wasm::WasmModule::has_array (ModuleTypeIndex index) const [inline]
Definition at line 872 of file wasm-module.h.
                                              {
    return index.index < types.size() &&
           types[index.index].kind == TypeDefinition::kArray;
  }
References v8::internal::index, and v8::internal::wasm::TypeDefinition::kArray.
Referenced by v8::internal::wasm::InstanceBuilder::Build_Phase1(), v8::internal::WasmTableObject::Get(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::IsI16Array(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::IsI8Array(), and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate().
has_cont_type()
bool v8::internal::wasm::WasmModule::has_cont_type (ModuleTypeIndex index) const [inline]
Definition at line 838 of file wasm-module.h.
                                                  {
    return index.index < types.size() &&
           types[index.index].kind == TypeDefinition::kCont;
  }
References v8::internal::index, and v8::internal::wasm::TypeDefinition::kCont.
Referenced by v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::ValidateCont().
has_signature()
bool v8::internal::wasm::WasmModule::has_signature (ModuleTypeIndex index) const [inline]
Definition at line 827 of file wasm-module.h.
                                                  {
    return index.index < types.size() &&
           types[index.index].kind == TypeDefinition::kFunction;
  }
References v8::internal::index, and v8::internal::wasm::TypeDefinition::kFunction.
Referenced by v8::internal::wasm::InstanceBuilder::Build_Phase1(), v8::internal::wasm::NativeModuleSerializer::CanonicalSigIdToModuleLocalTypeId(), v8::internal::wasm::ModuleDecoderImpl::consume_sig_index(), v8::internal::WasmTableObject::Get(), v8::internal::wasm::ModuleDisassembler::PrintModule(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::PrintSignature(), v8::internal::WasmTableObject::Set(), and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate().
has_struct()
bool v8::internal::wasm::WasmModule::has_struct (ModuleTypeIndex index) const [inline]
Definition at line 860 of file wasm-module.h.
                                               {
    return index.index < types.size() &&
           types[index.index].kind == TypeDefinition::kStruct;
  }
References v8::internal::index, and v8::internal::wasm::TypeDefinition::kStruct.
Referenced by v8::internal::wasm::InstanceBuilder::Build_Phase1(), v8::internal::wasm::DecodeCanonicalTypeNames(), v8::internal::WasmTableObject::Get(), and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate().
has_supertype()
bool v8::internal::wasm::WasmModule::has_supertype (ModuleTypeIndex index) const [inline]
Definition at line 888 of file wasm-module.h.
                                                  {
    return supertype(index).valid();
  }
References v8::internal::index.
has_type()
bool v8::internal::wasm::WasmModule::has_type (ModuleTypeIndex index) const [inline]
Definition at line 797 of file wasm-module.h.
                                             {
    return index.index < types.size();
  }
References v8::internal::index.
Referenced by v8::internal::WasmTableObject::canonical_type(), v8::internal::wasm::DecodeCanonicalTypeNames(), v8::internal::wasm::EquivalentTypes(), v8::internal::wasm::value_type_reader::Populate(), v8::internal::wasm::InstanceBuilder::ProcessImportedWasmGlobalObject(), and v8::internal::RUNTIME_FUNCTION().
heap_type()
HeapType v8::internal::wasm::WasmModule::heap_type (ModuleTypeIndex index) const [inline]
Definition at line 807 of file wasm-module.h.
                                                  {
    const TypeDefinition& t = type(index);
    return HeapType::Index(index, t.is_shared,
                           static_cast<RefTypeKind>(t.kind));
  }
References v8::internal::index, v8::internal::wasm::HeapType::Index(), v8::internal::wasm::TypeDefinition::is_shared, v8::internal::wasm::TypeDefinition::kind, and v8::internal::wasm::WasmElemSegment::type.
Referenced by v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessAllocateArray(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessAllocateStruct(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessRefFunc(), v8::internal::RUNTIME_FUNCTION(), v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::TypesUnrelated(), v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::ValidContinuationSubtypeDefinition(), and v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::ValidStructSubtypeDefinition().
MaxCanonicalTypeIndex()
CanonicalTypeIndex v8::internal::wasm::WasmModule::MaxCanonicalTypeIndex () const [inline]
Definition at line 893 of file wasm-module.h.
                                                   {
    if (isorecursive_canonical_type_ids.empty()) {
      return CanonicalTypeIndex::Invalid();
    }
    return *std::max_element(isorecursive_canonical_type_ids.begin(),
                             isorecursive_canonical_type_ids.end());
  }
References v8::internal::wasm::CanonicalTypeIndex::Invalid().
Referenced by v8::internal::wasm::InstanceBuilder::Build_Phase1().
operator=()
WasmModule& v8::internal::wasm::WasmModule::operator= (const WasmModule &) [delete]
set_all_functions_validated()
void v8::internal::wasm::WasmModule::set_all_functions_validated () const [inline]
Definition at line 933 of file wasm-module.h.
                                           {
    DCHECK_EQ(kWasmOrigin, origin);
    if (num_declared_functions == 0) return;
    DCHECK_NOT_NULL(validated_functions);
    size_t num_words = (num_declared_functions + 7) / 8;
    for (size_t i = 0; i < num_words; ++i) {
      validated_functions[i].store(0xff, std::memory_order_relaxed);
    }
  }
References DCHECK_EQ, DCHECK_NOT_NULL, v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::wasm::kWasmOrigin.
Referenced by v8::internal::wasm::NativeModuleDeserializer::Read().
set_function_validated()
void v8::internal::wasm::WasmModule::set_function_validated (int func_index) const [inline]
Definition at line 917 of file wasm-module.h.
                                                    {
    DCHECK_EQ(kWasmOrigin, origin);
    DCHECK_NOT_NULL(validated_functions);
    DCHECK_LE(num_imported_functions, func_index);
    int pos = func_index - num_imported_functions;
    DCHECK_LE(pos, num_declared_functions);
    std::atomic<uint8_t>* atomic_byte = &validated_functions[pos >> 3];
    uint8_t old_byte = atomic_byte->load(std::memory_order_relaxed);
    uint8_t new_bit = 1 << (pos & 7);
    while ((old_byte & new_bit) == 0 &&
           !atomic_byte->compare_exchange_weak(old_byte, old_byte | new_bit,
                                               std::memory_order_relaxed)) {
      // Retry with updated {old_byte}.
    }
  }
References DCHECK_EQ, DCHECK_LE, DCHECK_NOT_NULL, and v8::internal::wasm::kWasmOrigin.
Referenced by v8::internal::wasm::WasmCompilationUnit::ExecuteCompilation(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineWasmCall(), v8::internal::wasm::DebugInfoImpl::RecompileLiftoffWithBreakpoints(), v8::internal::compiler::WasmGraphBuilder::TryWasmInlining(), v8::internal::anonymous_namespace{runtime-test-wasm.cc}::ValidateFunctionNowIfNeeded(), and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ValidateSingleFunction().
signature()
const FunctionSig* v8::internal::wasm::WasmModule::signature (ModuleTypeIndex index) const [inline]
Definition at line 831 of file wasm-module.h.
                                                            {
    DCHECK(has_signature(index));
    size_t num_types = types.size();
    V8_ASSUME(index.index < num_types);
    return types[index.index].function_sig;
  }
References v8::internal::DCHECK(), v8::internal::index, and V8_ASSUME.
Referenced by v8::internal::wasm::ModuleDecoderImpl::consume_sig_index(), v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction(), v8::internal::wasm::WasmInterpreterRuntime::ExecuteCallRef(), v8::internal::wasm::WasmInterpreterRuntime::ExecuteIndirectCall(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::PrintSignature(), v8::internal::wasm::WasmBytecodeGenerator::ReserveBlockSlots(), and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate().
signature_hash()
uint64_t v8::internal::wasm::WasmModule::signature_hash (const TypeCanonicalizer * type_canonicalizer, uint32_t function_index) const
Definition at line 248 of file wasm-module.cc.
                                                                   {
  if (function_index >= functions.size()) {
    return kInvalidWasmSignatureHash;
  }
  CanonicalTypeIndex canonical_type_id =
      canonical_sig_id(functions[function_index].sig_index);
  return type_canonicalizer->LookupFunctionSignature(canonical_type_id)
      ->signature_hash();
}
References canonical_sig_id(), canonical_type_id(), functions, v8::internal::kInvalidWasmSignatureHash, v8::internal::wasm::TypeCanonicalizer::LookupFunctionSignature(), and v8::internal::wasm::CanonicalSig::signature_hash().
struct_type()
const StructType* v8::internal::wasm::WasmModule::struct_type (ModuleTypeIndex index) const [inline]
Definition at line 865 of file wasm-module.h.
                                                             {
    DCHECK(has_struct(index));
    size_t num_types = types.size();
    V8_ASSUME(index.index < num_types);
    return types[index.index].struct_type;
  }
References v8::internal::DCHECK(), v8::internal::index, and V8_ASSUME.
Referenced by v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction(), v8::internal::wasm::WasmInterpreterRuntime::StructNewUninitialized(), and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate().
supertype()
ModuleTypeIndex v8::internal::wasm::WasmModule::supertype (ModuleTypeIndex index) const [inline]
Definition at line 883 of file wasm-module.h.
                                                         {
    size_t num_types = types.size();
    V8_ASSUME(index.index < num_types);
    return types[index.index].supertype;
  }
References v8::internal::index, and V8_ASSUME.
Referenced by v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::CommonAncestor(), v8::internal::wasm::CreateMapForType(), and v8::internal::wasm::IsSubtypeOfImpl().
type()
const TypeDefinition& v8::internal::wasm::WasmModule::type (ModuleTypeIndex index) const [inline]
Definition at line 801 of file wasm-module.h.
                                                          {
    size_t num_types = types.size();
    V8_ASSUME(index.index < num_types);
    return types[index.index];
  }
References v8::internal::index, and V8_ASSUME.
Referenced by v8::internal::WasmStruct::AllocateDescriptorUninitialized(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayInitSegment(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayNew(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayNewFixed(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayNewFixed(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayNewImpl(), v8::internal::wasm::InstanceBuilder::Build_Phase1(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildImportedFunctionTargetAndImplicitArg(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildIndirectCallTargetAndImplicitArg(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallIndirectImpl(), v8::internal::wasm::TypeCanonicalizer::CanonicalizeTypeDef(), v8::internal::wasm::WasmCompilationUnit::CompileWasmFunction(), v8::internal::wasm::ModuleDecoderImpl::consume_element_func_index(), v8::internal::wasm::ModuleDecoderImpl::consume_init_expr(), v8::internal::wasm::CreateMapForType(), v8::internal::wasm::DisassembleFunctionImpl(), v8::internal::wasm::EvaluateConstantExpression(), v8::internal::wasm::WasmCompilationUnit::ExecuteCompilation(), v8::internal::wasm::ModuleDecoderImpl::FinalizeRecgroup(), v8::internal::wasm::TurboshaftGraphBuildingInterface::GetExactness(), v8::internal::wasm::GetSubtypingDepth(), v8::internal::wasm::ConstantExpressionInterface::GetTrustedInstanceDataForTypeIndex(), v8::internal::wasm::JSPrototypesSetup::IsDescriptorGlobal(), v8::internal::wasm::value_type_reader::Populate(), v8::internal::wasm::ModuleDisassembler::PrintModule(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessAllocateStruct(), v8::internal::wasm::InstanceBuilder::ProcessImports(), v8::internal::wasm::DebugInfoImpl::RecompileLiftoffWithBreakpoints(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCast(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ReduceWasmTypeCastRtt(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheck(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ReduceWasmTypeCheckRtt(), v8::internal::wasm::TurboshaftGraphBuildingInterface::RefFunc(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::RttCanon(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructNew(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StructNewImpl(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SubtypeCheck(), v8::internal::compiler::turboshaft::WasmInJSInliningReducer< Next >::TryInlineWasmCall(), v8::internal::compiler::WasmGraphBuilder::TryWasmInlining(), v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::ValidArraySubtypeDefinition(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::ValidateCont(), v8::internal::anonymous_namespace{runtime-test-wasm.cc}::ValidateFunctionNowIfNeeded(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ValidateSingleFunction(), v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::ValidContinuationSubtypeDefinition(), v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::ValidFunctionSubtypeDefinition(), v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::ValidStructSubtypeDefinition(), and v8::internal::wasm::ValidSubtypeDefinition().
Member Data Documentation
asm_js_offset_information
std::unique_ptr<AsmJsOffsetInformation> v8::internal::wasm::WasmModule::asm_js_offset_information
Definition at line 741 of file wasm-module.h.
Referenced by v8::internal::wasm::GetSourcePosition(), and v8::internal::JSFunction::ToString().
branch_hints
BranchHintInfo v8::internal::wasm::WasmModule::branch_hints
Definition at line 725 of file wasm-module.h.
Referenced by EstimateStoredSize(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::StartFunction().
build_id
WireBytesRef v8::internal::wasm::WasmModule::build_id
Definition at line 737 of file wasm-module.h.
canonical_typenames_decoded
std::atomic<bool> v8::internal::wasm::WasmModule::canonical_typenames_decoded = false [mutable]
Definition at line 704 of file wasm-module.h.
Referenced by v8::internal::wasm::CanonicalTypeNamesProvider::DecodeNames().
code
WireBytesRef v8::internal::wasm::WasmModule::code = {0, 0}
Definition at line 696 of file wasm-module.h.
Referenced by v8::internal::wasm::ValidateFunctionsStreamingJob::Run().
compilation_hints
std::vector<WasmCompilationHint> v8::internal::wasm::WasmModule::compilation_hints
Definition at line 724 of file wasm-module.h.
Referenced by EstimateStoredSize(), and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::GetCompilationHint().
data_segments
std::vector<WasmDataSegment> v8::internal::wasm::WasmModule::data_segments
Definition at line 716 of file wasm-module.h.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayInitSegment(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayNewSegment(), v8::internal::wasm::InstanceBuilder::Build_Phase2(), v8::internal::wasm::OffsetsProvider::CollectOffsets(), v8::internal::wasm::TurboshaftGraphBuildingInterface::DataDrop(), EstimateStoredSize(), v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmData(), v8::internal::WasmTrustedInstanceData::InitDataSegmentArrays(), v8::internal::wasm::InstanceBuilder::LoadDataSegments(), v8::internal::wasm::ModuleDisassembler::PrintModule(), and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::ValidateDataSegment().
debug_symbols
std::array<WasmDebugSymbols, WasmDebugSymbols::kNumTypes> v8::internal::wasm::WasmModule::debug_symbols {}
Definition at line 736 of file wasm-module.h.
Referenced by v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::CreateWasmScript(), v8::internal::wasm::AsyncCompileJob::FinishCompile(), and v8::internal::wasm::WasmCode::LogCode().
descriptors_section
WireBytesRef v8::internal::wasm::WasmModule::descriptors_section = {0, 0}
Definition at line 702 of file wasm-module.h.
Referenced by v8::internal::wasm::InstanceBuilder::SanitizeImports().
elem_segments
std::vector<WasmElemSegment> v8::internal::wasm::WasmModule::elem_segments
Definition at line 723 of file wasm-module.h.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayInitSegment(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayNewSegment(), v8::internal::wasm::InstanceBuilder::Build_Phase1(), v8::internal::wasm::OffsetsProvider::CollectOffsets(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ElemDrop(), EstimateStoredSize(), v8::internal::wasm::InitializeElementSegment(), v8::internal::WasmTrustedInstanceData::InitTableEntries(), v8::internal::wasm::InstanceBuilder::LoadTableSegments(), v8::internal::wasm::ModuleDisassembler::PrintModule(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate(), and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::ValidateElementSegment().
export_table
std::vector<WasmExport> v8::internal::wasm::WasmModule::export_table
Definition at line 720 of file wasm-module.h.
Referenced by v8::internal::wasm::NamesProvider::ComputeFunctionNamesFromImportsExports(), v8::internal::wasm::NamesProvider::ComputeNamesFromImportsExports(), EstimateStoredSize(), v8::internal::wasm::JSPrototypesSetup::GetExportedFunction(), v8::internal::wasm::GetExports(), v8::internal::wasm::ModuleDisassembler::PrintExportName(), v8::internal::wasm::ModuleDisassembler::PrintModule(), v8::internal::wasm::InstanceBuilder::ProcessExports(), and v8::internal::RUNTIME_FUNCTION().
functions
std::vector<WasmFunction> v8::internal::wasm::WasmModule::functions
Definition at line 714 of file wasm-module.h.
Referenced by v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::AddUnits(), v8::internal::wasm::WasmInterpreterRuntime::BeginExecution(), v8::internal::wasm::InstanceBuilder::Build_Phase1(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildImportedFunctionTargetAndImplicitArg(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallDirect(), v8::internal::wasm::WasmInterpreterRuntime::CallImportedFunction(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallIndirect(), v8::internal::wasm::WasmInterpreter::CodeMap::CodeMap(), v8::internal::wasm::WasmEngine::CompileFunction(), v8::internal::wasm::JSPrototypesSetup::ConfigurePrototypes_Direct_Impl(), v8::internal::wasm::ModuleDecoderImpl::consume_func_index(), v8::internal::wasm::ModuleDecoderImpl::consume_init_expr(), v8::internal::wasm::WasmInterpreterRuntime::ContinueExecution(), v8::internal::wasm::DisassembleFunction(), v8::internal::wasm::DisassembleFunctionImpl(), v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction(), v8::internal::wasm::WasmCodeManager::EstimateNativeModuleCodeSize(), EstimateStoredSize(), v8::internal::wasm::EvaluateConstantExpression(), v8::internal::wasm::InterpreterHandle::Execute(), v8::internal::wasm::WasmCompilationUnit::ExecuteCompilation(), v8::internal::anonymous_namespace{wasm-debug.cc}::FindNextBreakablePosition(), v8::internal::wasm::InliningTree::FullyExpand(), v8::internal::wasm::WasmBytecodeGenerator::GenerateBytecode(), v8::internal::wasm::GetContainingWasmFunction(), v8::internal::wasm::GetExports(), v8::internal::DebugStackTraceIterator::GetFunctionLocation(), v8::internal::wasm::GetImports(), v8::internal::wasm::GetNearestWasmFunction(), v8::internal::WasmInternalFunction::GetOrCreateExternal(), v8::internal::WasmTrustedInstanceData::GetOrCreateFuncRef(), v8::internal::Script::GetPositionInfo(), v8::internal::WasmScript::GetPossibleBreakpoints(), v8::internal::wasm::GetWasmFunctionOffset(), v8::internal::wasm::InliningTree::Inline(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineWasmCall(), v8::internal::wasm::DebugInfoImpl::IsAtReturn(), v8::internal::wasm::DebugInfoImpl::IsFrameBlackboxed(), v8::internal::wasm::WasmCode::LogCode(), v8::internal::WasmTrustedInstanceData::New(), v8::internal::WasmExportedFunction::New(), v8::anonymous_namespace{wasm-js.cc}::NewPromisingWasmExportedFunction(), v8::internal::wasm::InliningTree::NoLiftoffBudget(), v8::internal::wasm::ModuleDisassembler::PrintModule(), v8::internal::wasm::InstanceBuilder::ProcessImportedFunction(), v8::internal::wasm::InstanceBuilder::ProcessImports(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessRefFunc(), v8::internal::wasm::DebugInfoImpl::RecompileLiftoffWithBreakpoints(), v8::internal::wasm::TurboshaftGraphBuildingInterface::RefFunc(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ReturnCall(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ReturnCallIndirect(), v8::internal::RUNTIME_FUNCTION(), v8::internal::WasmScript::SetBreakPoint(), v8::internal::WasmScript::SetBreakPointForFunction(), v8::internal::WasmTableObject::SetFunctionTableEntry(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::SetFunctionTablePlaceholder(), v8::internal::wasm::WasmInterpreterRuntime::SetTrap(), signature_hash(), v8::internal::wasm::ThrowLazyCompilationError(), v8::internal::compiler::turboshaft::WasmInJSInliningReducer< Next >::TryInlineWasmCall(), v8::internal::compiler::WasmGraphBuilder::TryWasmInlining(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate(), v8::internal::wasm::ValidateAndSetBuiltinImports(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::ValidateFunction(), v8::internal::anonymous_namespace{runtime-test-wasm.cc}::ValidateFunctionNowIfNeeded(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ValidateSingleFunction(), v8::internal::wasm::WasmBytecodeGenerator::WasmBytecodeGenerator(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::WellKnown_FastApi().
globals
std::vector<WasmGlobal> v8::internal::wasm::WasmModule::globals
Definition at line 715 of file wasm-module.h.
Referenced by v8::internal::wasm::ModuleDecoderImpl::CalculateGlobalOffsets(), v8::internal::wasm::OffsetsProvider::CollectOffsets(), v8::internal::wasm::JSPrototypesSetup::ConfigurePrototypes_Direct_Impl(), v8::internal::wasm::ModuleDecoderImpl::consume_global_index(), v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction(), EstimateStoredSize(), v8::internal::wasm::GetExports(), v8::internal::wasm::WasmInterpreterRuntime::GetGlobalAddress(), v8::internal::wasm::WasmInterpreterRuntime::GetGlobalRef(), v8::internal::wasm::GetImports(), v8::internal::wasm::JSPrototypesSetup::GetRttInGlobal(), v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmGlobal(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::GlobalGet(), v8::internal::wasm::TurboshaftGraphBuildingInterface::GlobalGet(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::GlobalSet(), v8::internal::wasm::TurboshaftGraphBuildingInterface::GlobalSet(), v8::internal::wasm::WasmInterpreterRuntime::InitGlobalAddressCache(), v8::internal::wasm::InstanceBuilder::InitGlobals(), v8::internal::wasm::ModuleDisassembler::PrintModule(), v8::internal::wasm::InstanceBuilder::ProcessExports(), v8::internal::wasm::InstanceBuilder::ProcessImportedGlobal(), v8::internal::wasm::InstanceBuilder::ProcessImports(), v8::internal::wasm::WasmInterpreterRuntime::SetGlobalRef(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate(), and v8::internal::wasm::ValidateAndSetBuiltinImports().
has_shared_part
bool v8::internal::wasm::WasmModule::has_shared_part = false
Definition at line 708 of file wasm-module.h.
import_table
std::vector<WasmImport> v8::internal::wasm::WasmModule::import_table
Definition at line 719 of file wasm-module.h.
Referenced by v8::internal::wasm::InstanceBuilder::Build_Phase1(), v8::internal::wasm::OffsetsProvider::CollectOffsets(), v8::internal::wasm::NamesProvider::ComputeFunctionNamesFromImportsExports(), v8::internal::wasm::NamesProvider::ComputeNamesFromImportsExports(), EstimateStoredSize(), v8::internal::wasm::GetImports(), v8::internal::wasm::InstanceBuilder::ImportName(), v8::internal::wasm::InstanceBuilder::InstanceBuilder(), v8::internal::wasm::InstanceBuilder::LookupImportAsm(), v8::internal::wasm::ModuleDisassembler::PrintModule(), v8::internal::wasm::InstanceBuilder::ProcessExports(), v8::internal::wasm::InstanceBuilder::ProcessImportedMemories(), v8::internal::wasm::InstanceBuilder::ProcessImports(), v8::internal::wasm::InstanceBuilder::SanitizeImports(), and v8::internal::wasm::ValidateAndSetBuiltinImports().
inst_traces
std::vector<std::pair<uint32_t, uint32_t> > v8::internal::wasm::WasmModule::inst_traces
Definition at line 727 of file wasm-module.h.
Referenced by EstimateStoredSize(), and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::WasmDecoder().
is_wasm_gc
bool v8::internal::wasm::WasmModule::is_wasm_gc = false
Definition at line 706 of file wasm-module.h.
isorecursive_canonical_type_ids
std::vector<CanonicalTypeIndex> v8::internal::wasm::WasmModule::isorecursive_canonical_type_ids
Definition at line 713 of file wasm-module.h.
Referenced by v8::internal::wasm::TypeCanonicalizer::AddRecursiveGroup(), v8::internal::wasm::TypeCanonicalizer::AddRecursiveSingletonGroup(), v8::internal::wasm::InstanceBuilder::Build_Phase1(), v8::internal::wasm::NativeModuleSerializer::CanonicalSigIdToModuleLocalTypeId(), EstimateStoredSize(), and v8::internal::wasm::ModuleDecoderImpl::FinalizeRecgroup().
lazily_generated_names
LazilyGeneratedNames v8::internal::wasm::WasmModule::lazily_generated_names [mutable]
Definition at line 735 of file wasm-module.h.
Referenced by v8::internal::wasm::NamesProvider::ComputeFunctionNamesFromImportsExports(), v8::internal::wasm::WasmCode::DebugName(), v8::internal::compiler::GetDebugName(), v8::internal::wasm::ModuleWireBytes::GetNameOrNull(), v8::internal::WasmModuleObject::GetRawFunctionName(), v8::internal::wasm::NamesProvider::PrintFunctionName(), and v8::internal::RUNTIME_FUNCTION().
memories
std::vector<WasmMemory> v8::internal::wasm::WasmModule::memories
Definition at line 718 of file wasm-module.h.
Referenced by v8::internal::wasm::InstanceBuilder::AllocateMemory(), v8::internal::wasm::WasmInterpreterRuntime::AllowsAtomicsWait(), v8::internal::wasm::WasmInterpreterRuntime::AtomicNotify(), v8::internal::wasm::InstanceBuilder::Build_Phase1(), v8::internal::wasm::InstanceBuilder::Build_Phase1_Infallible(), EstimateStoredSize(), v8::internal::wasm::GetExports(), v8::internal::wasm::GetImports(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InstanceCache::Initialize(), v8::internal::wasm::WasmInterpreterRuntime::IsMemory64(), v8::internal::wasm::InstanceBuilder::LoadDataSegments(), v8::internal::WasmTrustedInstanceData::New(), v8::internal::wasm::ModuleDisassembler::PrintModule(), v8::internal::wasm::InstanceBuilder::ProcessImportedMemories(), v8::internal::anonymous_namespace{wasm-objects.cc}::SetInstanceMemory(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate(), v8::internal::wasm::WasmBytecodeGenerator::WasmBytecodeGenerator(), and v8::internal::compiler::WasmGraphBuilder::WasmGraphBuilder().
name
WireBytesRef v8::internal::wasm::WasmModule::name = {0, 0}
Definition at line 697 of file wasm-module.h.
Referenced by v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::CreateWasmScript(), v8::internal::WasmModuleObject::GetModuleNameOrNull(), and v8::internal::wasm::ModuleDisassembler::PrintModule().
name_section
WireBytesRef v8::internal::wasm::WasmModule::name_section = {0, 0}
Definition at line 700 of file wasm-module.h.
Referenced by v8::internal::wasm::CanonicalTypeNamesProvider::DecodeNames(), and v8::internal::wasm::NamesProvider::DecodeNamesIfNotYetDone().
num_declared_data_segments
uint32_t v8::internal::wasm::WasmModule::num_declared_data_segments = 0
Definition at line 693 of file wasm-module.h.
Referenced by v8::internal::wasm::WasmBytecodeGenerator::DecodeNumericOp(), v8::internal::WasmTrustedInstanceData::InitDataSegmentArrays(), v8::internal::WasmTrustedInstanceData::New(), and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::ValidateDataSegment().
num_declared_functions
uint32_t v8::internal::wasm::WasmModule::num_declared_functions = 0
Definition at line 684 of file wasm-module.h.
Referenced by v8::internal::wasm::WasmCodeAllocator::AllocateForCodeInRegion(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::AllowAnotherTopTierJobForAllFunctions(), v8::internal::wasm::InliningTree::BudgetScaleFactor(), v8::internal::wasm::InstanceBuilder::Build_Phase1(), v8::internal::wasm::declared_function_index(), v8::internal::wasm::DeserializeTieringInformation(), v8::internal::wasm::DeserializeTypeFeedback(), v8::internal::wasm::DumpProfileToFile(), v8::internal::wasm::WasmCodeManager::EstimateNativeModuleCodeSize(), v8::internal::wasm::WasmCodeManager::EstimateNativeModuleMetaDataSize(), EstimateStoredSize(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::InitializeCompilationUnits(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::MayCompriseLazyFunctions(), v8::internal::wasm::NativeModuleSerializer::Measure(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::OnFinishedUnits(), v8::internal::wasm::AsyncStreamingProcessor::ProcessFunctionBody(), v8::internal::wasm::NativeModuleDeserializer::ReadTieringBudget(), v8::internal::wasm::ProfileGenerator::SerializeTieringInfo(), v8::internal::wasm::TierUpAllForTesting(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::TierUpAllFunctions(), v8::internal::compiler::turboshaft::WasmInJSInliningReducer< Next >::TryInlineWasmCall(), and v8::internal::wasm::ValidateFunctions().
num_exported_functions
uint32_t v8::internal::wasm::WasmModule::num_exported_functions = 0
Definition at line 692 of file wasm-module.h.
num_imported_functions
uint32_t v8::internal::wasm::WasmModule::num_imported_functions = 0
Definition at line 681 of file wasm-module.h.
Referenced by v8::internal::anonymous_namespace{runtime-wasm.cc}::AllocateFeedbackVector(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::AllowAnotherTopTierJobForAllFunctions(), v8::internal::wasm::InstanceBuilder::Build(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallDirect(), v8::internal::wasm::WasmInterpreterRuntime::CallImportedFunction(), v8::internal::wasm::declared_function_index(), v8::internal::wasm::DeserializeTieringInformation(), v8::internal::wasm::DisassembleFunction(), v8::internal::wasm::WasmCodeManager::EstimateNativeModuleCodeSize(), v8::internal::wasm::WasmCompilationUnit::ExecuteCompilation(), v8::internal::wasm::ExecuteLiftoffCompilation(), v8::internal::wasm::InliningTree::FullyExpand(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::GetCompilationEventName(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::GetCompilationHint(), v8::internal::WasmTrustedInstanceData::GetOrCreateFuncRef(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::InitializeCompilationUnits(), v8::internal::wasm::InstanceBuilder::InstanceBuilder(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::MayCompriseLazyFunctions(), v8::internal::WasmTrustedInstanceData::New(), v8::internal::wasm::ModuleDisassembler::PrintModule(), v8::internal::wasm::AsyncStreamingProcessor::ProcessFunctionBody(), v8::internal::wasm::NativeModuleDeserializer::ReadHeader(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ReturnCall(), v8::internal::RUNTIME_FUNCTION(), v8::internal::wasm::ProfileGenerator::SerializeTieringInfo(), v8::internal::wasm::TierUpAllForTesting(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::TierUpAllFunctions(), v8::internal::compiler::turboshaft::WasmInJSInliningReducer< Next >::TryInlineWasmCall(), and v8::internal::wasm::ValidateAndSetBuiltinImports().
num_imported_globals
uint32_t v8::internal::wasm::WasmModule::num_imported_globals = 0
Definition at line 679 of file wasm-module.h.
Referenced by v8::internal::wasm::OffsetsProvider::CollectOffsets(), v8::internal::wasm::OffsetsProvider::ImportsDone(), and v8::internal::wasm::ModuleDisassembler::PrintModule().
num_imported_mutable_globals
uint32_t v8::internal::wasm::WasmModule::num_imported_mutable_globals = 0
Definition at line 680 of file wasm-module.h.
Referenced by v8::internal::wasm::InstanceBuilder::Build_Phase1(), v8::internal::WasmTrustedInstanceData::New(), and v8::internal::wasm::InstanceBuilder::ProcessImportedWasmGlobalObject().
num_imported_tables
uint32_t v8::internal::wasm::WasmModule::num_imported_tables = 0
Definition at line 682 of file wasm-module.h.
Referenced by v8::internal::wasm::InstanceBuilder::Build_Phase1(), v8::internal::wasm::OffsetsProvider::CollectOffsets(), v8::internal::wasm::OffsetsProvider::ImportsDone(), and v8::internal::wasm::ModuleDisassembler::PrintModule().
num_imported_tags
uint32_t v8::internal::wasm::WasmModule::num_imported_tags = 0
Definition at line 683 of file wasm-module.h.
Referenced by v8::internal::wasm::OffsetsProvider::CollectOffsets(), v8::internal::wasm::OffsetsProvider::ImportsDone(), and v8::internal::wasm::ModuleDisassembler::PrintModule().
num_small_functions
std::atomic<uint32_t> v8::internal::wasm::WasmModule::num_small_functions = 0
Definition at line 691 of file wasm-module.h.
Referenced by v8::internal::wasm::InliningTree::BudgetScaleFactor().
origin
const ModuleOrigin v8::internal::wasm::WasmModule::origin
Definition at line 734 of file wasm-module.h.
Referenced by v8::internal::wasm::InstanceBuilder::Build(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompileNativeModule(), v8::internal::wasm::NativeModuleCache::Erase(), v8::internal::wasm::WasmCompilationUnit::ExecuteCompilation(), v8::internal::wasm::InstanceBuilder::FinalizeExportsObject(), v8::internal::wasm::is_asmjs_module(), v8::internal::WasmExportedFunction::New(), v8::internal::wasm::AsyncStreamingProcessor::ProcessCodeSectionHeader(), v8::internal::wasm::AsyncStreamingProcessor::ProcessFunctionBody(), v8::internal::wasm::NativeModule::SampleCodeSize(), v8::internal::anonymous_namespace{wasm-objects.cc}::SetInstanceMemory(), v8::internal::wasm::ValidateAndSetBuiltinImports(), v8::internal::wasm::ValidateFunctionBody(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ValidateFunctions(), and v8::internal::wasm::ValidateFunctions().
signature_zone
Zone v8::internal::wasm::WasmModule::signature_zone [mutable]
Definition at line 672 of file wasm-module.h.
Referenced by v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::CheckForWellKnownImport(), and EstimateStoredSize().
start_function_index
int v8::internal::wasm::WasmModule::start_function_index = -1
Definition at line 673 of file wasm-module.h.
Referenced by v8::internal::wasm::InstanceBuilder::Build_Phase1(), and v8::internal::wasm::ModuleDisassembler::PrintModule().
stringref_literals
std::vector<WasmStringRefLiteral> v8::internal::wasm::WasmModule::stringref_literals
Definition at line 722 of file wasm-module.h.
Referenced by EstimateStoredSize(), v8::internal::wasm::ModuleDisassembler::PrintModule(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::StringConst(), and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate().
tables
std::vector<WasmTable> v8::internal::wasm::WasmModule::tables
Definition at line 717 of file wasm-module.h.
Referenced by v8::internal::wasm::InstanceBuilder::Build_Phase1(), v8::internal::wasm::InstanceBuilder::Build_Phase1_Infallible(), v8::internal::wasm::InstanceBuilder::Build_Phase2(), v8::internal::wasm::WasmInterpreterRuntime::CheckIndirectCallSignature(), v8::internal::wasm::OffsetsProvider::CollectOffsets(), v8::internal::wasm::ModuleDecoderImpl::consume_table_index(), v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction(), EstimateStoredSize(), v8::internal::wasm::GetExports(), v8::internal::wasm::GetImports(), v8::internal::wasm::WasmInterpreterRuntime::InitIndirectFunctionTables(), v8::internal::WasmTrustedInstanceData::InitTableEntries(), v8::internal::wasm::InstanceBuilder::LoadTableSegments(), v8::internal::wasm::ModuleDisassembler::PrintModule(), v8::internal::wasm::InstanceBuilder::ProcessExports(), v8::internal::wasm::InstanceBuilder::ProcessImportedTable(), v8::internal::wasm::InstanceBuilder::ProcessImports(), v8::internal::wasm::WasmInterpreterRuntime::PurgeIndirectCallCache(), v8::internal::wasm::InstanceBuilder::SetTableInitialValues(), and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate().
tagged_globals_buffer_size
uint32_t v8::internal::wasm::WasmModule::tagged_globals_buffer_size = 0
Definition at line 678 of file wasm-module.h.
Referenced by v8::internal::wasm::InstanceBuilder::Build_Phase1(), and v8::internal::wasm::ModuleDecoderImpl::CalculateGlobalOffsets().
tags
std::vector<WasmTag> v8::internal::wasm::WasmModule::tags
Definition at line 721 of file wasm-module.h.
Referenced by v8::internal::wasm::InstanceBuilder::Build_Phase1(), v8::internal::wasm::OffsetsProvider::CollectOffsets(), v8::internal::wasm::ModuleDecoderImpl::consume_tag_index(), v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction(), EstimateStoredSize(), v8::internal::wasm::WasmInterpreterRuntime::GetWasmTag(), v8::internal::wasm::WasmInterpreterRuntime::HandleException(), v8::internal::wasm::ModuleDisassembler::PrintModule(), v8::internal::wasm::InstanceBuilder::ProcessExports(), v8::internal::wasm::InstanceBuilder::ProcessImports(), and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate().
type_feedback
TypeFeedbackStorage v8::internal::wasm::WasmModule::type_feedback [mutable]
Definition at line 732 of file wasm-module.h.
Referenced by v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::AllowAnotherTopTierJobForAllFunctions(), v8::internal::wasm::TurboshaftGraphBuildingInterface::deopts_enabled(), v8::internal::wasm::DeserializeTypeFeedback(), v8::internal::wasm::InliningTree::FullyExpand(), v8::internal::wasm::GetImports(), v8::internal::wasm::TurboshaftGraphBuildingInterface::GetLiftoffFrameSize(), v8::internal::wasm::TurboshaftGraphBuildingInterface::HandleWellKnownImport(), v8::internal::wasm::InliningTree::Inline(), v8::internal::wasm::NumFeedbackSlots(), v8::internal::wasm::TransitiveTypeFeedbackProcessor::ProcessFunction(), v8::internal::wasm::InstanceBuilder::ProcessImports(), v8::internal::wasm::NativeModuleDeserializer::ReadHeader(), v8::internal::RUNTIME_FUNCTION(), v8::internal::wasm::InstanceBuilder::SanitizeImports(), v8::internal::wasm::ProfileGenerator::SerializeTieringInfo(), v8::internal::wasm::ProfileGenerator::SerializeTypeFeedback(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StartFunction(), v8::internal::wasm::TriggerTierUp(), and v8::internal::wasm::ValidateAndSetBuiltinImports().
types
std::vector<TypeDefinition> v8::internal::wasm::WasmModule::types
Definition at line 710 of file wasm-module.h.
Referenced by v8::internal::wasm::TypeCanonicalizer::AddRecursiveGroup(), v8::internal::wasm::TypeCanonicalizer::AddRecursiveSingletonGroup(), v8::internal::wasm::InstanceBuilder::Build_Phase1(), v8::internal::wasm::NativeModuleSerializer::CanonicalSigIdToModuleLocalTypeId(), v8::internal::wasm::WasmInterpreterRuntime::CheckIndirectCallSignature(), v8::internal::wasm::OffsetsProvider::CollectOffsets(), v8::internal::wasm::ModuleDecoderImpl::consume_sig_index(), EstimateStoredSize(), v8::internal::wasm::ModuleDecoderImpl::FinalizeRecgroup(), v8::internal::wasm::GetSubtypingDepth(), v8::internal::wasm::ModuleDisassembler::PrintModule(), v8::internal::wasm::ModuleDisassembler::PrintTypeDefinition(), v8::internal::wasm::WasmInterpreterRuntime::SubtypeCheck(), and v8::internal::wasm::value_type_reader::ValidateHeapType().
untagged_globals_buffer_size
uint32_t v8::internal::wasm::WasmModule::untagged_globals_buffer_size = 0
Definition at line 677 of file wasm-module.h.
Referenced by v8::internal::wasm::InstanceBuilder::Build_Phase1(), and v8::internal::wasm::ModuleDecoderImpl::CalculateGlobalOffsets().
validated_functions
std::unique_ptr<std::atomic<uint8_t>[]> v8::internal::wasm::WasmModule::validated_functions [mutable]
Definition at line 747 of file wasm-module.h.
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-module.h
/mnt/V8SourceCode/src/wasm/wasm-module.cc