v8::internal::compiler::JSInliningHeuristic::CandidateCompare Struct Reference
Public Member Functions
bool operator() (const Candidate &left, const Candidate &right) const
Detailed Description
Definition at line 92 of file js-inlining-heuristic.h.
Member Function Documentation
operator()()
bool v8::internal::compiler::JSInliningHeuristic::CandidateCompare::operator() (const Candidate & left, const Candidate & right) const
Definition at line 867 of file js-inlining-heuristic.cc.
                                                         {
  constexpr bool kInlineLeftFirst = true, kInlineRightFirst = false;
  if (right.frequency.IsUnknown()) {
    if (left.frequency.IsUnknown()) {
      // If left and right are both unknown then the ordering is indeterminate,
      // which breaks strict weak ordering requirements, so we fall back to the
      // node id as a tie breaker.
      if (left.total_size < right.total_size) {
        return kInlineLeftFirst;
      } else if (left.total_size > right.total_size) {
        return kInlineRightFirst;
      } else {
        return left.node->id() > right.node->id();
      }
    } else {
      return kInlineLeftFirst;
    }
  } else if (left.frequency.IsUnknown()) {
    return kInlineRightFirst;
  }
  float left_score = left.frequency.value() / left.total_size;
  float right_score = right.frequency.value() / right.total_size;
  if (left_score > right_score) {
    return kInlineLeftFirst;
  } else if (left_score < right_score) {
    return kInlineRightFirst;
  } else {
    return left.node->id() > right.node->id();
  }
}
References v8::internal::compiler::JSInliningHeuristic::Candidate::frequency, v8::internal::compiler::Node::id(), v8::internal::compiler::CallFrequency::IsUnknown(), v8::internal::compiler::JSInliningHeuristic::Candidate::node, v8::internal::compiler::JSInliningHeuristic::Candidate::total_size, and v8::internal::compiler::CallFrequency::value().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/compiler/js-inlining-heuristic.h
/mnt/V8SourceCode/src/compiler/js-inlining-heuristic.cc