v8::internal::anonymous_namespace{debug-wasm-objects.cc}::IndexedDebugProxy< T, id, Provider > Struct Template Reference
Public Types
enum { kProviderField
, kFieldCount
 }
Static Public Member Functions
static DirectHandle< JSObject > Create (Isolate *isolate, DirectHandle< Provider > provider, bool make_map_non_extensible=true)
static v8::Local< v8::FunctionTemplate > CreateTemplate (v8::Isolate *isolate)
template<typename V >
static Isolate * GetIsolate (const PropertyCallbackInfo< V > &info)
template<typename V >
static DirectHandle< JSObject > GetHolder (const PropertyCallbackInfo< V > &info)
static DirectHandle< Provider > GetProvider (DirectHandle< JSObject > holder, Isolate *isolate)
template<typename V >
static DirectHandle< Provider > GetProvider (const PropertyCallbackInfo< V > &info)
static v8::Intercepted IndexedGetter (uint32_t index, const PropertyCallbackInfo< v8::Value > &info)
static v8::Intercepted IndexedDescriptor (uint32_t index, const PropertyCallbackInfo< v8::Value > &info)
static v8::Intercepted IndexedQuery (uint32_t index, const PropertyCallbackInfo< v8::Integer > &info)
static void IndexedEnumerator (const PropertyCallbackInfo< v8::Array > &info)
Static Public Attributes
static constexpr DebugProxyId kId = id
Detailed Description
template<typename T, DebugProxyId id, typename Provider>
struct v8::internal::anonymous_namespace{debug-wasm-objects.cc}::IndexedDebugProxy< T, id, Provider >
Definition at line 97 of file debug-wasm-objects.cc.
Member Enumeration Documentation
anonymous enum
template<typename T , DebugProxyId id, typename Provider >
anonymous enum
Enumerator
kProviderField
kFieldCount
Definition at line 112 of file debug-wasm-objects.cc.
       {
    kProviderField,
    kFieldCount,
  };
Member Function Documentation
Create()
template<typename T , DebugProxyId id, typename Provider >
static DirectHandle<JSObject> v8::internal::anonymous_namespace{debug-wasm-objects.cc}::IndexedDebugProxy< T, id, Provider >::Create (Isolate * isolate, DirectHandle< Provider > provider, bool make_map_non_extensible = true) [inline], [static]
Definition at line 100 of file debug-wasm-objects.cc.
                                                                            {
    auto object_map = GetOrCreateDebugProxyMap(isolate, kId, &T::CreateTemplate,
                                               make_map_non_extensible);
    auto object = isolate->factory()->NewFastOrSlowJSObjectFromMap(
        object_map, 0, AllocationType::kYoung,
        DirectHandle<AllocationSite>::null(), NewJSObjectType::kAPIWrapper);
    object->SetEmbedderField(kProviderField, *provider);
    return object;
  }
References v8::internal::Isolate::factory(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::GetOrCreateDebugProxyMap(), v8::internal::kAPIWrapper, v8_inspector::anonymous_namespace{v8-stack-trace-impl.cc}::kId, v8::internal::kYoung, and v8::internal::Factory::NewFastOrSlowJSObjectFromMap().
CreateTemplate()
template<typename T , DebugProxyId id, typename Provider >
static v8::Local<v8::FunctionTemplate> v8::internal::anonymous_namespace{debug-wasm-objects.cc}::IndexedDebugProxy< T, id, Provider >::CreateTemplate (v8::Isolate * isolate) [inline], [static]
Definition at line 117 of file debug-wasm-objects.cc.
                                                                        {
    Local<v8::FunctionTemplate> templ = v8::FunctionTemplate::New(isolate);
    templ->SetClassName(
        v8::String::NewFromUtf8(isolate, T::kClassName).ToLocalChecked());
    templ->InstanceTemplate()->SetInternalFieldCount(T::kFieldCount);
    templ->InstanceTemplate()->SetHandler(
        v8::IndexedPropertyHandlerConfiguration(
            &T::IndexedGetter, {}, &T::IndexedQuery, {}, &T::IndexedEnumerator,
            {}, &T::IndexedDescriptor, {},
            v8::PropertyHandlerFlags::kHasNoSideEffect));
    return templ;
  }
References v8::kHasNoSideEffect, v8::FunctionTemplate::New(), and v8::String::NewFromUtf8().
GetHolder()
template<typename T , DebugProxyId id, typename Provider >
template<typename V >
static DirectHandle<JSObject> v8::internal::anonymous_namespace{debug-wasm-objects.cc}::IndexedDebugProxy< T, id, Provider >::GetHolder (const PropertyCallbackInfo< V > & info) [inline], [static]
Definition at line 136 of file debug-wasm-objects.cc.
                                                                               {
    return Cast<JSObject>(Utils::OpenHandle(*info.HolderV2()));
  }
References v8::PropertyCallbackInfo< T >::HolderV2(), and v8::Utils::OpenHandle().
GetIsolate()
template<typename T , DebugProxyId id, typename Provider >
template<typename V >
static Isolate* v8::internal::anonymous_namespace{debug-wasm-objects.cc}::IndexedDebugProxy< T, id, Provider >::GetIsolate (const PropertyCallbackInfo< V > & info) [inline], [static]
Definition at line 131 of file debug-wasm-objects.cc.
                                                                  {
    return reinterpret_cast<Isolate*>(info.GetIsolate());
  }
References v8::PropertyCallbackInfo< T >::GetIsolate().
GetProvider() [1/2]
template<typename T , DebugProxyId id, typename Provider >
template<typename V >
static DirectHandle<Provider> v8::internal::anonymous_namespace{debug-wasm-objects.cc}::IndexedDebugProxy< T, id, Provider >::GetProvider (const PropertyCallbackInfo< V > & info) [inline], [static]
Definition at line 147 of file debug-wasm-objects.cc.
                                           {
    return GetProvider(GetHolder(info), GetIsolate(info));
  }
GetProvider() [2/2]
template<typename T , DebugProxyId id, typename Provider >
static DirectHandle<Provider> v8::internal::anonymous_namespace{debug-wasm-objects.cc}::IndexedDebugProxy< T, id, Provider >::GetProvider (DirectHandle< JSObject > holder, Isolate * isolate) [inline], [static]
Definition at line 140 of file debug-wasm-objects.cc.
                                                              {
    return direct_handle(
        Cast<Provider>(holder->GetEmbedderField(kProviderField)), isolate);
  }
References v8::internal::direct_handle().
IndexedDescriptor()
template<typename T , DebugProxyId id, typename Provider >
static v8::Intercepted v8::internal::anonymous_namespace{debug-wasm-objects.cc}::IndexedDebugProxy< T, id, Provider >::IndexedDescriptor (uint32_t index, const PropertyCallbackInfo< v8::Value > & info) [inline], [static]
Definition at line 164 of file debug-wasm-objects.cc.
                                                                 {
    auto isolate = GetIsolate(info);
    auto provider = GetProvider(info);
    if (index < T::Count(isolate, provider)) {
      PropertyDescriptor descriptor;
      descriptor.set_configurable(false);
      descriptor.set_enumerable(true);
      descriptor.set_writable(false);
      descriptor.set_value(Cast<JSAny>(T::Get(isolate, provider, index)));
      info.GetReturnValue().Set(Utils::ToLocal(descriptor.ToObject(isolate)));
      return v8::Intercepted::kYes;
    }
    return v8::Intercepted::kNo;
  }
References v8::internal::compiler::turboshaft::Get(), v8::PropertyCallbackInfo< T >::GetReturnValue(), v8::internal::index, v8::kNo, v8::kYes, v8::internal::PropertyDescriptor::set_configurable(), v8::internal::PropertyDescriptor::set_enumerable(), v8::internal::PropertyDescriptor::set_value(), v8::internal::PropertyDescriptor::set_writable(), and v8::internal::PropertyDescriptor::ToObject().
IndexedEnumerator()
template<typename T , DebugProxyId id, typename Provider >
static void v8::internal::anonymous_namespace{debug-wasm-objects.cc}::IndexedDebugProxy< T, id, Provider >::IndexedEnumerator (const PropertyCallbackInfo< v8::Array > & info) [inline], [static]
Definition at line 191 of file debug-wasm-objects.cc.
                                                                           {
    auto isolate = GetIsolate(info);
    auto count = T::Count(isolate, GetProvider(info));
    auto indices = isolate->factory()->NewFixedArray(count);
    for (uint32_t index = 0; index < count; ++index) {
      indices->set(index, Smi::FromInt(index));
    }
    info.GetReturnValue().Set(
        Utils::ToLocal(isolate->factory()->NewJSArrayWithElements(
            indices, PACKED_SMI_ELEMENTS)));
  }
References v8::internal::Isolate::factory(), v8::internal::Smi::FromInt(), v8::PropertyCallbackInfo< T >::GetReturnValue(), v8::internal::index, v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::Factory::NewJSArrayWithElements(), and v8::internal::PACKED_SMI_ELEMENTS.
IndexedGetter()
template<typename T , DebugProxyId id, typename Provider >
static v8::Intercepted v8::internal::anonymous_namespace{debug-wasm-objects.cc}::IndexedDebugProxy< T, id, Provider >::IndexedGetter (uint32_t index, const PropertyCallbackInfo< v8::Value > & info) [inline], [static]
Definition at line 152 of file debug-wasm-objects.cc.
                                                                 {
    auto isolate = GetIsolate(info);
    auto provider = GetProvider(info);
    if (index < T::Count(isolate, provider)) {
      auto value = T::Get(isolate, provider, index);
      info.GetReturnValue().Set(Utils::ToLocal(value));
      return v8::Intercepted::kYes;
    }
    return v8::Intercepted::kNo;
  }
References v8::internal::compiler::turboshaft::Get(), v8::PropertyCallbackInfo< T >::GetReturnValue(), v8::internal::index, v8::kNo, v8::kYes, and v8::internal::value.
IndexedQuery()
template<typename T , DebugProxyId id, typename Provider >
static v8::Intercepted v8::internal::anonymous_namespace{debug-wasm-objects.cc}::IndexedDebugProxy< T, id, Provider >::IndexedQuery (uint32_t index, const PropertyCallbackInfo< v8::Integer > & info) [inline], [static]
Definition at line 180 of file debug-wasm-objects.cc.
                                                                   {
    if (index < T::Count(GetIsolate(info), GetProvider(info))) {
      info.GetReturnValue().Set(Integer::New(
          info.GetIsolate(),
          PropertyAttribute::DontDelete | PropertyAttribute::ReadOnly));
      return v8::Intercepted::kYes;
    }
    return v8::Intercepted::kNo;
  }
References v8::DontDelete, v8::PropertyCallbackInfo< T >::GetIsolate(), v8::PropertyCallbackInfo< T >::GetReturnValue(), v8::internal::index, v8::kNo, v8::kYes, v8::Integer::New(), and v8::ReadOnly.
Member Data Documentation
kId
template<typename T , DebugProxyId id, typename Provider >
constexpr DebugProxyId v8::internal::anonymous_namespace{debug-wasm-objects.cc}::IndexedDebugProxy< T, id, Provider >::kId = id [static], [constexpr]
Definition at line 98 of file debug-wasm-objects.cc.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/debug/debug-wasm-objects.cc