v8::internal::compiler::turboshaft::ChangeOrDeoptOp Struct Reference
#include <operations.h>
Public Types
enum class Kind : uint8_t {
kUint32ToInt32
, kInt64ToInt32
, kInt64ToAdditiveSafeInteger
, kUint64ToInt32
,
kUint64ToInt64
, kFloat64ToInt32
, kFloat64ToUint32
, kFloat64ToAdditiveSafeInteger
,
kFloat64ToInt64
, kFloat64NotHole
 }
Public Member Functions
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
V< Untagged > input () const
V< FrameState > frame_state () const
ChangeOrDeoptOp (V< Untagged > input, V< FrameState > frame_state, Kind kind, CheckForMinusZeroMode minus_zero_mode, const FeedbackSource &feedback)
void Validate (const Graph &graph) const
auto options () const
Public Attributes
Kind kind
CheckForMinusZeroMode minus_zero_mode
FeedbackSource feedback
Static Public Attributes
static constexpr OpEffects effects = OpEffects().CanDeopt()
Additional Inherited Members
Detailed Description
Definition at line 2297 of file operations.h.
Member Enumeration Documentation
Kind
enum v8::internal::compiler::turboshaft::ChangeOrDeoptOp::Kind : uint8_t [strong]
Enumerator
kUint32ToInt32
kInt64ToInt32
kInt64ToAdditiveSafeInteger
kUint64ToInt32
kUint64ToInt64
kFloat64ToInt32
kFloat64ToUint32
kFloat64ToAdditiveSafeInteger
kFloat64ToInt64
kFloat64NotHole
Definition at line 2298 of file operations.h.
                  : uint8_t {
    kUint32ToInt32,
    kInt64ToInt32,
    kInt64ToAdditiveSafeInteger,
    kUint64ToInt32,
    kUint64ToInt64,
    kFloat64ToInt32,
    kFloat64ToUint32,
    kFloat64ToAdditiveSafeInteger,
    kFloat64ToInt64,
    kFloat64NotHole,
  };
Constructor & Destructor Documentation
ChangeOrDeoptOp()
v8::internal::compiler::turboshaft::ChangeOrDeoptOp::ChangeOrDeoptOp (V< Untagged > input, V< FrameState > frame_state, Kind kind, CheckForMinusZeroMode minus_zero_mode, const FeedbackSource & feedback) [inline]
Definition at line 2355 of file operations.h.
      : Base(input, frame_state),
        kind(kind),
        minus_zero_mode(minus_zero_mode),
        feedback(feedback) {}
Member Function Documentation
frame_state()
V<FrameState> v8::internal::compiler::turboshaft::ChangeOrDeoptOp::frame_state () const [inline]
Definition at line 2353 of file operations.h.
{ return Base::input<FrameState>(1); }
input()
V<Untagged> v8::internal::compiler::turboshaft::ChangeOrDeoptOp::input () const [inline]
Definition at line 2352 of file operations.h.
{ return Base::input<Untagged>(0); }
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::ChangeOrDeoptOp::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 2333 of file operations.h.
                                                              {
    switch (kind) {
      case Kind::kUint32ToInt32:
        return MaybeRepVector<MaybeRegisterRepresentation::Word32()>();
      case Kind::kInt64ToInt32:
      case Kind::kInt64ToAdditiveSafeInteger:
      case Kind::kUint64ToInt32:
      case Kind::kUint64ToInt64:
        return MaybeRepVector<MaybeRegisterRepresentation::Word64()>();
      case Kind::kFloat64ToInt32:
      case Kind::kFloat64ToUint32:
      case Kind::kFloat64ToAdditiveSafeInteger:
      case Kind::kFloat64ToInt64:
      case Kind::kFloat64NotHole:
        return MaybeRepVector<MaybeRegisterRepresentation::Float64()>();
    }
  }
options()
auto v8::internal::compiler::turboshaft::ChangeOrDeoptOp::options () const [inline]
Definition at line 2367 of file operations.h.
{ return std::tuple{kind, minus_zero_mode, feedback}; }
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::ChangeOrDeoptOp::outputs_rep () const [inline]
Definition at line 2315 of file operations.h.
                                                               {
    switch (kind) {
      case Kind::kUint32ToInt32:
      case Kind::kInt64ToInt32:
      case Kind::kUint64ToInt32:
      case Kind::kFloat64ToInt32:
      case Kind::kFloat64ToUint32:
        return RepVector<RegisterRepresentation::Word32()>();
      case Kind::kUint64ToInt64:
      case Kind::kInt64ToAdditiveSafeInteger:
      case Kind::kFloat64ToAdditiveSafeInteger:
      case Kind::kFloat64ToInt64:
        return RepVector<RegisterRepresentation::Word64()>();
      case Kind::kFloat64NotHole:
        return RepVector<RegisterRepresentation::Float64()>();
    }
  }
Validate()
void v8::internal::compiler::turboshaft::ChangeOrDeoptOp::Validate (const Graph & graph) const [inline]
Definition at line 2363 of file operations.h.
                                          {
    DCHECK(Get(graph, frame_state()).Is<FrameStateOp>());
  }
References v8::internal::DCHECK(), v8::internal::compiler::turboshaft::Get(), and graph().
Member Data Documentation
effects
constexpr OpEffects v8::internal::compiler::turboshaft::ChangeOrDeoptOp::effects = OpEffects().CanDeopt() [static], [constexpr]
Definition at line 2314 of file operations.h.
feedback
FeedbackSource v8::internal::compiler::turboshaft::ChangeOrDeoptOp::feedback
Definition at line 2312 of file operations.h.
kind
Kind v8::internal::compiler::turboshaft::ChangeOrDeoptOp::kind
Definition at line 2310 of file operations.h.
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::IsNodeUnsigned().
minus_zero_mode
CheckForMinusZeroMode v8::internal::compiler::turboshaft::ChangeOrDeoptOp::minus_zero_mode
Definition at line 2311 of file operations.h.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h