v8::internal::compiler::HeapObjectMatcherImpl< kHeapConstantOpcode > Struct Template Reference
#include <node-matchers.h>
Public Member Functions
HeapObjectMatcherImpl (Node *node)
bool Is (IndirectHandle< HeapObject > const &value) const
HeapObjectRef Ref (JSHeapBroker *broker) const
Additional Inherited Members
Detailed Description
template<IrOpcode::Value kHeapConstantOpcode>
struct v8::internal::compiler::HeapObjectMatcherImpl< kHeapConstantOpcode >
Definition at line 227 of file node-matchers.h.
Constructor & Destructor Documentation
HeapObjectMatcherImpl()
template<IrOpcode::Value kHeapConstantOpcode>
v8::internal::compiler::HeapObjectMatcherImpl< kHeapConstantOpcode >::HeapObjectMatcherImpl (Node * node) [inline], [explicit]
Definition at line 229 of file node-matchers.h.
      : ValueMatcher<IndirectHandle<HeapObject>, kHeapConstantOpcode>(node) {}
Member Function Documentation
Is()
template<IrOpcode::Value kHeapConstantOpcode>
bool v8::internal::compiler::HeapObjectMatcherImpl< kHeapConstantOpcode >::Is (IndirectHandle< HeapObject > const & value) const [inline]
Definition at line 232 of file node-matchers.h.
                                                         {
    return this->HasResolvedValue() &&
           this->ResolvedValue().address() == value.address();
  }
References v8::internal::HandleBase::address(), v8::internal::compiler::ValueMatcher< IndirectHandle< HeapObject >, kHeapConstantOpcode >::HasResolvedValue(), and v8::internal::compiler::ValueMatcher< IndirectHandle< HeapObject >, kHeapConstantOpcode >::ResolvedValue().
Referenced by v8::internal::compiler::PropertyAccessBuilder::BuildCheckValue(), v8::internal::compiler::RepresentationChanger::GetBitRepresentationFor(), v8::internal::compiler::CodeAssembler::IsNullConstant(), v8::internal::compiler::CodeAssembler::IsUndefinedConstant(), v8::internal::compiler::SimplifiedOperatorReducer::Reduce(), and v8::internal::compiler::JSCallReducer::ReduceNumberParseInt().
Ref()
template<IrOpcode::Value kHeapConstantOpcode>
HeapObjectRef v8::internal::compiler::HeapObjectMatcherImpl< kHeapConstantOpcode >::Ref (JSHeapBroker * broker) const [inline]
Definition at line 237 of file node-matchers.h.
                                                {
    // TODO(jgruber,chromium:1209798): Using kAssumeMemoryFence works around
    // the fact that the graph stores handles (and not refs). The assumption is
    // that any handle inserted into the graph is safe to read; but we don't
    // preserve the reason why it is safe to read. Thus we must over-approximate
    // here and assume the existence of a memory fence. In the future, we should
    // consider having the graph store ObjectRefs or ObjectData pointer instead,
    // which would make new ref construction here unnecessary.
    return MakeRefAssumeMemoryFence(broker, this->ResolvedValue());
  }
References broker(), v8::internal::compiler::MakeRefAssumeMemoryFence(), and v8::internal::compiler::ValueMatcher< IndirectHandle< HeapObject >, kHeapConstantOpcode >::ResolvedValue().
Referenced by v8::internal::compiler::PropertyAccessBuilder::BuildCheckMaps(), v8::internal::compiler::JSInliningHeuristic::CollectFunctions(), v8::internal::compiler::JSNativeContextSpecialization::CreateStringConstant(), v8::internal::compiler::CommonOperatorReducer::DecideCondition(), v8::internal::compiler::JSInliner::DetermineCallContext(), v8::internal::compiler::JSInliner::DetermineCallTarget(), v8::internal::compiler::NodeProperties::GetJSCreateMap(), v8::internal::compiler::JSNativeContextSpecialization::GetMaxStringLength(), v8::internal::compiler::anonymous_namespace{js-native-context-specialization.cc}::GetTypedArrayConstant(), v8::internal::compiler::RepresentationChanger::GetWord64RepresentationFor(), v8::internal::compiler::NodeProperties::InferMapsUnsafe(), v8::internal::compiler::JSNativeContextSpecialization::InferRootMap(), v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::IsLiteralString(), v8::internal::compiler::anonymous_namespace{js-native-context-specialization.cc}::IsStringConstant(), v8::internal::compiler::anonymous_namespace{js-native-context-specialization.cc}::IsStringWithNonAccessibleContent(), v8::internal::compiler::OneOrTwoByteAnalysis::OneOrTwoByte(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::SimplifiedOperatorReducer::Reduce(), v8::internal::compiler::JSCallReducer::ReduceDataViewAccess(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementLoadFromHeapConstant(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeCall(), v8::internal::compiler::JSCallReducer::ReduceJSCall(), v8::internal::compiler::JSInliner::ReduceJSCall(), v8::internal::compiler::JSCallReducer::ReduceJSConstruct(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSFindNonDefaultConstructorOrConstruct(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSGetSuperConstructor(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSHasInPrototypeChain(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSInstanceOf(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadNamed(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSOrdinaryHasInstance(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSPromiseResolve(), v8::internal::compiler::JSTypedLowering::ReduceJSToNumberInput(), v8::internal::compiler::TypedOptimization::ReduceJSToNumberInput(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSToString(), v8::internal::compiler::JSCallReducer::ReduceNumberParseInt(), v8::internal::compiler::JSNativeContextSpecialization::ReducePropertyAccess(), v8::internal::compiler::TypedOptimization::ReduceStringLength(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeCharAt(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeEndsWith(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeStartsWith(), v8::internal::compiler::JSIntrinsicLowering::ReduceToString(), v8::internal::compiler::TypedOptimization::ReduceTypedArrayLength(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::TargetIsClassConstructor(), v8::internal::compiler::PropertyAccessBuilder::TryFoldLoadConstantDataField(), v8::internal::compiler::OneOrTwoByteAnalysis::TryGetRange(), and v8::internal::compiler::JSCallReducer::TryReduceJSCallMathMinMaxWithArrayLike().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/node-matchers.h