v8::internal::compiler::turboshaft::SpecialRPOSchedulingPhase Struct Reference
#include <instruction-selection-phase.h>
Public Member Functions
void Run (PipelineData *data, Zone *temp_zone)
Detailed Description
Definition at line 122 of file instruction-selection-phase.h.
Member Function Documentation
Run()
void v8::internal::compiler::turboshaft::SpecialRPOSchedulingPhase::Run (PipelineData * data, Zone * temp_zone)
Definition at line 314 of file instruction-selection-phase.cc.
                                                                       {
  Graph& graph = data->graph();
  // Compute special RPO order....
  TurboshaftSpecialRPONumberer numberer(graph, temp_zone);
  if (!data->graph_has_special_rpo()) {
    auto schedule = numberer.ComputeSpecialRPO();
    graph.ReorderBlocks(base::VectorOf(schedule));
    data->set_graph_has_special_rpo();
  }
  // Determine deferred blocks.
  PropagateDeferred(graph);
}
References v8::internal::compiler::turboshaft::TurboshaftSpecialRPONumberer::ComputeSpecialRPO(), v8::internal::compiler::turboshaft::PipelineData::graph(), graph(), v8::internal::compiler::turboshaft::PipelineData::graph_has_special_rpo(), v8::internal::compiler::turboshaft::PropagateDeferred(), v8::internal::compiler::turboshaft::PipelineData::set_graph_has_special_rpo(), and v8::base::VectorOf().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/instruction-selection-phase.h
/mnt/V8SourceCode/src/compiler/turboshaft/instruction-selection-phase.cc