v8::internal::compiler::turboshaft::ProjectionOp Struct Reference
#include <operations.h>
Public Member Functions
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
V< Any > input () const
ProjectionOp (V< Any > input, uint16_t index, RegisterRepresentation rep)
void Validate (const Graph &graph) const
auto options () const
Public Attributes
uint16_t index
RegisterRepresentation rep
Static Public Attributes
static constexpr OpEffects effects = OpEffects()
Additional Inherited Members
Detailed Description
Definition at line 4555 of file operations.h.
Constructor & Destructor Documentation
ProjectionOp()
v8::internal::compiler::turboshaft::ProjectionOp::ProjectionOp (V< Any > input, uint16_t index, RegisterRepresentation rep) [inline]
Definition at line 4571 of file operations.h.
      : Base(input), index(index), rep(rep) {}
Member Function Documentation
input()
V<Any> v8::internal::compiler::turboshaft::ProjectionOp::input () const [inline]
Definition at line 4569 of file operations.h.
{ return Base::input<Any>(0); }
Referenced by v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessProjection(), v8::internal::compiler::InstructionSelector::TryPrepareScheduleFirstProjection(), and v8::internal::compiler::InstructionSelector::VisitProjection().
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::ProjectionOp::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 4564 of file operations.h.
                                                              {
    return {};
  }
options()
auto v8::internal::compiler::turboshaft::ProjectionOp::options () const [inline]
Definition at line 4579 of file operations.h.
{ return std::tuple{index, rep}; }
References v8::internal::index.
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::ProjectionOp::outputs_rep () const [inline]
Definition at line 4560 of file operations.h.
                                                               {
    return base::VectorOf(&rep, 1);
  }
References v8::base::VectorOf().
Validate()
void v8::internal::compiler::turboshaft::ProjectionOp::Validate (const Graph & graph) const [inline]
Definition at line 4574 of file operations.h.
                                          {
#ifdef DEBUG
    ValidateOpInputRep(graph, input(), rep, this, index);
#endif // DEBUG
  }
References graph(), and v8::internal::index.
Member Data Documentation
effects
constexpr OpEffects v8::internal::compiler::turboshaft::ProjectionOp::effects = OpEffects() [static], [constexpr]
Definition at line 4559 of file operations.h.
index
uint16_t v8::internal::compiler::turboshaft::ProjectionOp::index
Definition at line 4556 of file operations.h.
Referenced by v8::internal::compiler::InstructionSelector::CanDoBranchIfOverflowFusion(), v8::internal::compiler::InstructionSelector::FindProjection(), v8::internal::compiler::InstructionSelector::InitializeCallBuffer(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessProjection(), v8::internal::compiler::InstructionSelector::TryPrepareScheduleFirstProjection(), and v8::internal::compiler::InstructionSelector::VisitProjection().
rep
RegisterRepresentation v8::internal::compiler::turboshaft::ProjectionOp::rep
Definition at line 4557 of file operations.h.
Referenced by v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessProjection().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h