v8::internal::compiler::GraphBuilderPhase Struct Reference
Public Member Functions
void Run (TFPipelineData *data, Zone *temp_zone, Linkage *linkage)
Detailed Description
Definition at line 854 of file pipeline.cc.
Member Function Documentation
Run()
void v8::internal::compiler::GraphBuilderPhase::Run (TFPipelineData * data, Zone * temp_zone, Linkage * linkage) [inline]
Definition at line 857 of file pipeline.cc.
                                                                    {
    BytecodeGraphBuilderFlags flags;
    if (data->info()->analyze_environment_liveness()) {
      flags |= BytecodeGraphBuilderFlag::kAnalyzeEnvironmentLiveness;
    }
    if (data->info()->bailout_on_uninitialized()) {
      flags |= BytecodeGraphBuilderFlag::kBailoutOnUninitialized;
    }
    JSHeapBroker* broker = data->broker();
    UnparkedScopeIfNeeded scope(broker);
    SharedFunctionInfoRef sfi_ref =
        MakeRef(broker, data->info()->closure()->shared());
    FeedbackCellRef feedback_cell_ref =
        MakeRef(broker, data->info()->closure()->raw_feedback_cell());
    BytecodeArrayRef bytecode = MakeRef(broker, data->info()->bytecode_array());
    CallFrequency frequency(1.0f);
    BuildGraphFromBytecode(broker, temp_zone, sfi_ref, bytecode,
                           feedback_cell_ref, data->info()->osr_offset(),
                           data->jsgraph(), frequency, data->source_positions(),
                           data->node_origins(), SourcePosition::kNotInlined,
                           data->info()->code_kind(), flags,
                           &data->info()->tick_counter(),
                           ObserveNodeInfo{data->observe_node_manager(),
                                           data->info()->node_observer()});
    // We need to be certain that the parameter count reported by our output
    // Code object matches what the code we compile expects. Otherwise, this
    // may lead to effectively signature mismatches during function calls. This
    // CHECK is a defense-in-depth measure to ensure this doesn't happen.
    SBXCHECK_EQ(
        StartNode(data->jsgraph()->graph()->start()).FormalParameterCount(),
        linkage->GetIncomingDescriptor()->ParameterSlotCount());
  }
References broker(), v8::internal::compiler::BuildGraphFromBytecode(), v8::internal::flags, v8::internal::compiler::StartNode::FormalParameterCount(), v8::internal::compiler::kAnalyzeEnvironmentLiveness, v8::internal::compiler::kBailoutOnUninitialized, v8::internal::SourcePosition::kNotInlined, v8::internal::compiler::MakeRef(), and SBXCHECK_EQ.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/pipeline.cc