v8::internal::compiler::turboshaft::DidntThrowOp Struct Reference
#include <operations.h>
Public Member Functions
OpEffects Effects () const
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
OpIndex throwing_operation () const
DidntThrowOp (OpIndex throwing_operation, bool has_catch_block, const base::Vector< const RegisterRepresentation > *results_rep, OpEffects throwing_op_effects)
V8_EXPORT_PRIVATE void Validate (const Graph &graph) const
auto options () const
Public Attributes
OpEffects throwing_op_effects
bool has_catch_block
const base::Vector< const RegisterRepresentation > * results_rep
Additional Inherited Members
Detailed Description
Definition at line 4237 of file operations.h.
Constructor & Destructor Documentation
DidntThrowOp()
v8::internal::compiler::turboshaft::DidntThrowOp::DidntThrowOp (OpIndex throwing_operation, bool has_catch_block, const base::Vector< const RegisterRepresentation > * results_rep, OpEffects throwing_op_effects) [inline], [explicit]
Definition at line 4260 of file operations.h.
      : Base(throwing_operation),
        throwing_op_effects(throwing_op_effects),
        has_catch_block(has_catch_block),
        results_rep(results_rep) {}
Member Function Documentation
Effects()
OpEffects v8::internal::compiler::turboshaft::DidntThrowOp::Effects () const [inline]
Definition at line 4247 of file operations.h.
{ return throwing_op_effects; }
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::DidntThrowOp::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 4253 of file operations.h.
                                                              {
    return MaybeRepVector<MaybeRegisterRepresentation::None()>();
  }
options()
auto v8::internal::compiler::turboshaft::DidntThrowOp::options () const [inline]
Definition at line 4269 of file operations.h.
                       {
    return std::tuple{throwing_op_effects, has_catch_block};
  }
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::DidntThrowOp::outputs_rep () const [inline]
Definition at line 4249 of file operations.h.
                                                               {
    return *results_rep;
  }
Referenced by Validate().
throwing_operation()
OpIndex v8::internal::compiler::turboshaft::DidntThrowOp::throwing_operation () const [inline]
Definition at line 4258 of file operations.h.
{ return input(0); }
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphDidntThrow(), Validate(), and v8::internal::compiler::InstructionSelector::VisitNode().
Validate()
void v8::internal::compiler::turboshaft::DidntThrowOp::Validate (const Graph & graph) const
Definition at line 894 of file operations.cc.
                                                    {
#ifdef DEBUG
  DCHECK(MayThrow(graph.Get(throwing_operation()).opcode));
  switch (graph.Get(throwing_operation()).opcode) {
    case Opcode::kCall: {
      auto& call_op = graph.Get(throwing_operation()).Cast<CallOp>();
      DCHECK_EQ(call_op.descriptor->out_reps, outputs_rep());
      break;
    }
    case Opcode::kFastApiCall: {
      auto& call_op = graph.Get(throwing_operation()).Cast<FastApiCallOp>();
      DCHECK_EQ(call_op.out_reps, outputs_rep());
      break;
    }
#define STATIC_OUTPUT_CASE(Name) \
  case Opcode::k##Name: { \
    const Name##Op& op = graph.Get(throwing_operation()).Cast<Name##Op>(); \
    DCHECK_EQ(op.kOutReps, outputs_rep()); \
    break; \
  }
      TURBOSHAFT_THROWING_STATIC_OUTPUTS_OPERATIONS_LIST(STATIC_OUTPUT_CASE)
#undef STATIC_OUTPUT_CASE
    default:
      UNREACHABLE();
  }
  // Check that `may_throw()` is either immediately before or that there is only
  // a `CheckExceptionOp` in-between.
  OpIndex this_index = graph.Index(*this);
  OpIndex in_between = graph.NextIndex(throwing_operation());
  if (has_catch_block) {
    DCHECK_NE(in_between, this_index);
    auto& catch_op = graph.Get(in_between).Cast<CheckExceptionOp>();
    DCHECK_EQ(catch_op.didnt_throw_block->begin(), this_index);
  } else {
    DCHECK_EQ(in_between, this_index);
  }
#endif
}
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NE, graph(), has_catch_block, v8::internal::compiler::turboshaft::MayThrow(), v8::internal::compiler::turboshaft::OperationT< Derived >::opcode, outputs_rep(), throwing_operation(), TURBOSHAFT_THROWING_STATIC_OUTPUTS_OPERATIONS_LIST, and v8::internal::UNREACHABLE().
Member Data Documentation
has_catch_block
bool v8::internal::compiler::turboshaft::DidntThrowOp::has_catch_block
Definition at line 4242 of file operations.h.
Referenced by Validate().
results_rep
const base::Vector<const RegisterRepresentation>* v8::internal::compiler::turboshaft::DidntThrowOp::results_rep
Definition at line 4245 of file operations.h.
throwing_op_effects
OpEffects v8::internal::compiler::turboshaft::DidntThrowOp::throwing_op_effects
Definition at line 4238 of file operations.h.
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h
/mnt/V8SourceCode/src/compiler/turboshaft/operations.cc