v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::SnapshotData Struct Reference
#include <snapshot-table.h>
Public Member Functions
SnapshotData (SnapshotData *parent, size_t log_begin)
SnapshotData * CommonAncestor (SnapshotData *other)
void Seal (size_t end)
bool IsSealed () const
Public Attributes
SnapshotData * parent
const uint32_t depth = parent ? parent->depth + 1 : 0
size_t log_begin
size_t log_end = kInvalidOffset
Static Public Attributes
static constexpr size_t kInvalidOffset = std::numeric_limits<size_t>::max()
Detailed Description
template<class Value, class KeyData = NoKeyData>
struct v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::SnapshotData
Definition at line 349 of file snapshot-table.h.
Constructor & Destructor Documentation
SnapshotData()
template<class Value , class KeyData = NoKeyData>
v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::SnapshotData::SnapshotData (SnapshotData * parent, size_t log_begin) [inline]
Definition at line 358 of file snapshot-table.h.
      : parent(parent), log_begin(log_begin) {}
Member Function Documentation
CommonAncestor()
template<class Value , class KeyData = NoKeyData>
SnapshotData* v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::SnapshotData::CommonAncestor (SnapshotData * other) [inline]
Definition at line 361 of file snapshot-table.h.
                                                    {
    SnapshotData* self = this;
    while (other->depth > self->depth) other = other->parent;
    while (self->depth > other->depth) self = self->parent;
    while (other != self) {
      self = self->parent;
      other = other->parent;
    }
    return self;
  }
References v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::SnapshotData::depth, and v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::SnapshotData::parent.
Referenced by v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::MoveToNewSnapshot().
IsSealed()
template<class Value , class KeyData = NoKeyData>
bool v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::SnapshotData::IsSealed () const [inline]
Definition at line 376 of file snapshot-table.h.
{ return log_end != kInvalidOffset; }
Referenced by v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::GetPredecessorValue(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::IsSealed(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::RevertCurrentSnapshot(), and v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Set().
Seal()
template<class Value , class KeyData = NoKeyData>
void v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::SnapshotData::Seal (size_t end) [inline]
Definition at line 371 of file snapshot-table.h.
                        {
    DCHECK_WITH_MSG(!IsSealed(), "A Snapshot can only be sealed once");
    this->log_end = end;
  }
References DCHECK_WITH_MSG, v8::internal::compiler::end(), and v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::IsSealed().
Referenced by v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Seal(), and v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::SnapshotTable().
Member Data Documentation
depth
template<class Value , class KeyData = NoKeyData>
const uint32_t v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::SnapshotData::depth = parent ? parent->depth + 1 : 0
Definition at line 352 of file snapshot-table.h.
Referenced by v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::SnapshotData::CommonAncestor().
kInvalidOffset
template<class Value , class KeyData = NoKeyData>
constexpr size_t v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::SnapshotData::kInvalidOffset = std::numeric_limits<size_t>::max() [static], [constexpr]
Definition at line 356 of file snapshot-table.h.
log_begin
template<class Value , class KeyData = NoKeyData>
size_t v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::SnapshotData::log_begin
Definition at line 353 of file snapshot-table.h.
Referenced by v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::LogEntries(), and v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Seal().
log_end
template<class Value , class KeyData = NoKeyData>
size_t v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::SnapshotData::log_end = kInvalidOffset
Definition at line 354 of file snapshot-table.h.
Referenced by v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::LogEntries(), and v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Seal().
parent
template<class Value , class KeyData = NoKeyData>
SnapshotData* v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::SnapshotData::parent
Definition at line 350 of file snapshot-table.h.
Referenced by v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::SnapshotData::CommonAncestor(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::MergePredecessors(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::MoveToNewSnapshot(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::ReplaySnapshot(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::RevertCurrentSnapshot(), and v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Seal().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/snapshot-table.h