v8::internal::MarkingHelper Struct Reference
#include <marking.h>
Public Types
enum class WorklistTarget : uint8_t { kRegular
 }
enum class LivenessMode : uint8_t { kMarkbit
, kAlwaysLive
 }
Static Public Member Functions
static std::optional< WorklistTarget > ShouldMarkObject (Heap *heap, Tagged< HeapObject > object)
static LivenessMode GetLivenessMode (Heap *heap, Tagged< HeapObject > object)
template<typename MarkingStateT >
static bool IsMarkedOrAlwaysLive (Heap *heap, MarkingStateT *marking_state, Tagged< HeapObject > object)
template<typename MarkingStateT >
static bool IsUnmarkedAndNotAlwaysLive (Heap *heap, MarkingStateT *marking_state, Tagged< HeapObject > object)
template<typename MarkingState >
static bool TryMarkAndPush (Heap *heap, MarkingWorklists::Local *marking_worklist, MarkingState *marking_state, WorklistTarget target_worklis, Tagged< HeapObject > object)
Detailed Description
Definition at line 233 of file marking.h.
Member Enumeration Documentation
LivenessMode
enum v8::internal::MarkingHelper::LivenessMode : uint8_t [strong]
Enumerator
kMarkbit
kAlwaysLive
Definition at line 240 of file marking.h.
                          : uint8_t {
    kMarkbit,
    kAlwaysLive,
  };
WorklistTarget
enum v8::internal::MarkingHelper::WorklistTarget : uint8_t [strong]
Enumerator
kRegular
Definition at line 236 of file marking.h.
                            : uint8_t {
    kRegular,
  };
Member Function Documentation
GetLivenessMode()
MarkingHelper::LivenessMode v8::internal::MarkingHelper::GetLivenessMode (Heap * heap, Tagged< HeapObject > object) [inline], [static]
Definition at line 304 of file marking-inl.h.
                                           {
  const auto* chunk = MemoryChunk::FromHeapObject(object);
  const auto flags = chunk->GetFlags();
  if (flags & MemoryChunk::READ_ONLY_HEAP) {
    return MarkingHelper::LivenessMode::kAlwaysLive;
  }
  if (v8_flags.black_allocated_pages &&
      (flags & MemoryChunk::BLACK_ALLOCATED)) {
    return MarkingHelper::LivenessMode::kAlwaysLive;
  }
  if (V8_LIKELY(!(flags & MemoryChunk::IN_WRITABLE_SHARED_SPACE))) {
    return MarkingHelper::LivenessMode::kMarkbit;
  }
  // Object in shared writable space. Only mark it if the Isolate is owning the
  // shared space.
  //
  // TODO(340989496): Speed up check here by keeping the flag on Heap.
  if (heap->isolate()->is_shared_space_isolate()) {
    return MarkingHelper::LivenessMode::kMarkbit;
  }
  return MarkingHelper::LivenessMode::kAlwaysLive;
}
References v8::internal::MemoryChunk::BLACK_ALLOCATED, v8::internal::flags, v8::internal::MemoryChunk::FromHeapObject(), v8::internal::MemoryChunk::IN_WRITABLE_SHARED_SPACE, kAlwaysLive, kMarkbit, v8::internal::MemoryChunk::READ_ONLY_HEAP, v8::internal::v8_flags, and V8_LIKELY.
Referenced by IsMarkedOrAlwaysLive(), and IsUnmarkedAndNotAlwaysLive().
IsMarkedOrAlwaysLive()
template<typename MarkingStateT >
bool v8::internal::MarkingHelper::IsMarkedOrAlwaysLive (Heap * heap, MarkingStateT * marking_state, Tagged< HeapObject > object) [inline], [static]
Definition at line 330 of file marking-inl.h.
                                                                    {
  return (MarkingHelper::GetLivenessMode(heap, object) ==
          MarkingHelper::LivenessMode::kAlwaysLive) ||
         marking_state->IsMarked(object);
}
References GetLivenessMode(), and kAlwaysLive.
Referenced by v8::internal::MarkCompactWeakObjectRetainer::RetainAs(), v8::internal::ObjectStatsCollectorImpl::SameLiveness(), v8::internal::ObjectStatsVisitor::Visit(), v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitEphemeronHashTable(), v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitJSWeakRef(), and v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitWeakCell().
IsUnmarkedAndNotAlwaysLive()
template<typename MarkingStateT >
bool v8::internal::MarkingHelper::IsUnmarkedAndNotAlwaysLive (Heap * heap, MarkingStateT * marking_state, Tagged< HeapObject > object) [inline], [static]
Definition at line 340 of file marking-inl.h.
                                                                          {
  return (MarkingHelper::GetLivenessMode(heap, object) !=
          MarkingHelper::LivenessMode::kAlwaysLive) &&
         marking_state->IsUnmarked(object);
}
References GetLivenessMode(), and kAlwaysLive.
Referenced by v8::internal::MarkCompactCollector::IsUnmarkedHeapObject(), v8::internal::MarkCompactCollector::IsUnmarkedSharedHeapObject(), and v8::internal::InternalizedStringTableCleaner::VisitRootPointers().
ShouldMarkObject()
std::optional< MarkingHelper::WorklistTarget > v8::internal::MarkingHelper::ShouldMarkObject (Heap * heap, Tagged< HeapObject > object) [inline], [static]
Definition at line 278 of file marking-inl.h.
                                           {
  const auto* chunk = MemoryChunk::FromHeapObject(object);
  const auto flags = chunk->GetFlags();
  if (flags & MemoryChunk::READ_ONLY_HEAP) {
    return {};
  }
  if (v8_flags.black_allocated_pages &&
      V8_UNLIKELY(flags & MemoryChunk::BLACK_ALLOCATED)) {
    DCHECK(!(flags & MemoryChunk::kIsInYoungGenerationMask));
    return {};
  }
  if (V8_LIKELY(!(flags & MemoryChunk::IN_WRITABLE_SHARED_SPACE))) {
    return {MarkingHelper::WorklistTarget::kRegular};
  }
  // Object in shared writable space. Only mark it if the Isolate is owning the
  // shared space.
  //
  // TODO(340989496): Speed up check here by keeping the flag on Heap.
  if (heap->isolate()->is_shared_space_isolate()) {
    return {MarkingHelper::WorklistTarget::kRegular};
  }
  return {};
}
References v8::internal::MemoryChunk::BLACK_ALLOCATED, v8::internal::DCHECK(), v8::internal::flags, v8::internal::MemoryChunk::FromHeapObject(), v8::internal::MemoryChunk::IN_WRITABLE_SHARED_SPACE, v8::internal::MemoryChunk::kIsInYoungGenerationMask, kRegular, v8::internal::MemoryChunk::READ_ONLY_HEAP, v8::internal::v8_flags, V8_LIKELY, and V8_UNLIKELY.
Referenced by v8::internal::MarkCompactCollector::SharedHeapObjectVisitor::CheckForSharedObject(), v8::internal::UnifiedHeapMarkingState::MarkAndPush(), v8::internal::MarkCompactCollector::CustomRootBodyMarkingVisitor::MarkObject(), v8::internal::RootMarkingVisitor::MarkObjectByPointer(), v8::internal::MarkCompactCollector::MarkObjectsFromClientHeap(), v8::internal::FullMarkingVisitorBase< ConcurrentMarkingVisitor >::MarkPointerTableEntry(), v8::internal::MarkingBarrier::MarkValueLocal(), v8::internal::ConcurrentMarkingVisitor::ProcessEphemeron(), v8::internal::MarkingVisitorBase< ConcreteVisitor >::ProcessStrongHeapObject(), v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitDescriptorsForMap(), v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitEmbeddedPointer(), v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitEphemeronHashTable(), v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitFixedArrayWithProgressTracker(), v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitJSFunction(), v8::internal::ConservativeTracedHandlesMarkingVisitor::VisitPointer(), and v8::internal::MarkingBarrier::Write().
TryMarkAndPush()
template<typename MarkingState >
bool v8::internal::MarkingHelper::TryMarkAndPush (Heap * heap, MarkingWorklists::Local * marking_worklist, MarkingState * marking_state, WorklistTarget target_worklis, Tagged< HeapObject > object) [inline], [static]
Definition at line 350 of file marking-inl.h.
                                                              {
  DCHECK(heap->Contains(object));
  if (marking_state->TryMark(object)) {
    if (V8_LIKELY(target_worklist == WorklistTarget::kRegular)) {
      marking_worklist->Push(object);
    }
    return true;
  }
  return false;
}
References v8::internal::DCHECK(), kRegular, v8::internal::MarkingStateBase< ConcreteState, access_mode >::TryMark(), and V8_LIKELY.
Referenced by v8::internal::UnifiedHeapMarkingState::MarkAndPush(), v8::internal::MarkCompactCollector::MarkObject(), v8::internal::MarkingVisitorBase< ConcreteVisitor >::MarkObject(), v8::internal::MarkCompactCollector::MarkRootObject(), v8::internal::MarkingBarrier::MarkValueLocal(), and v8::internal::ConservativeTracedHandlesMarkingVisitor::VisitPointer().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/heap/marking.h
/mnt/V8SourceCode/src/heap/marking-inl.h