cppgc::internal::WeakCrossThreadPersistentPolicy Struct Reference
#include <pointer-policies.h>
Public Types
using IsStrongPersistent = std::false_type
Static Public Member Functions
static CrossThreadPersistentRegion & GetPersistentRegion (const void *object)
Detailed Description
Definition at line 256 of file pointer-policies.h.
Member Typedef Documentation
IsStrongPersistent
using cppgc::internal::WeakCrossThreadPersistentPolicy::IsStrongPersistent = std::false_type
Definition at line 257 of file pointer-policies.h.
Member Function Documentation
GetPersistentRegion()
CrossThreadPersistentRegion & cppgc::internal::WeakCrossThreadPersistentPolicy::GetPersistentRegion (const void * object) [static]
Definition at line 127 of file pointer-policies.cc.
                                                                       {
  return BasePage::FromPayload(object)
      ->heap()
      .GetWeakCrossThreadPersistentRegion();
}
References cppgc::internal::BasePage::FromPayload(), cppgc::internal::HeapBase::GetWeakCrossThreadPersistentRegion(), and cppgc::internal::BasePage::heap().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/include/cppgc/internal/pointer-policies.h
/mnt/V8SourceCode/src/heap/cppgc/pointer-policies.cc