v8::internal::torque::AbstractTypeDeclaration Struct Reference
#include <ast.h>
Public Member Functions
AbstractTypeDeclaration (SourcePosition pos, Identifier *name, AbstractTypeFlags flags, std::optional< TypeExpression * > extends, std::optional< std::string > generates)
bool IsConstexpr () const
bool IsTransient () const
Public Attributes
AbstractTypeFlags flags
std::optional< TypeExpression * > extends
std::optional< std::string > generates
Additional Inherited Members
Detailed Description
Definition at line 873 of file ast.h.
Constructor & Destructor Documentation
AbstractTypeDeclaration()
v8::internal::torque::AbstractTypeDeclaration::AbstractTypeDeclaration (SourcePosition pos, Identifier * name, AbstractTypeFlags flags, std::optional< TypeExpression * > extends, std::optional< std::string > generates) [inline]
Definition at line 875 of file ast.h.
      : TypeDeclaration(kKind, pos, name),
        flags(flags),
        extends(extends),
        generates(std::move(generates)) {
    CHECK_EQ(IsConstexprName(name->value),
             !!(flags & AbstractTypeFlag::kConstexpr));
  }
References CHECK_EQ, flags, v8::internal::torque::IsConstexprName(), v8::internal::torque::kConstexpr, v8::internal::torque::TypeDeclaration::name, and v8::internal::torque::Identifier::value.
Member Function Documentation
IsConstexpr()
bool v8::internal::torque::AbstractTypeDeclaration::IsConstexpr () const [inline]
Definition at line 887 of file ast.h.
{ return flags & AbstractTypeFlag::kConstexpr; }
References flags, and v8::internal::torque::kConstexpr.
Referenced by v8::internal::torque::TypeVisitor::ComputeType().
IsTransient()
bool v8::internal::torque::AbstractTypeDeclaration::IsTransient () const [inline]
Definition at line 888 of file ast.h.
{ return flags & AbstractTypeFlag::kTransient; }
References flags, and v8::internal::torque::kTransient.
Referenced by v8::internal::torque::TypeVisitor::ComputeType().
Member Data Documentation
extends
std::optional<TypeExpression*> v8::internal::torque::AbstractTypeDeclaration::extends
Definition at line 891 of file ast.h.
Referenced by v8::internal::torque::TypeVisitor::ComputeType().
flags
AbstractTypeFlags v8::internal::torque::AbstractTypeDeclaration::flags
Definition at line 890 of file ast.h.
Referenced by AbstractTypeDeclaration(), v8::internal::torque::TypeVisitor::ComputeType(), IsConstexpr(), and IsTransient().
generates
std::optional<std::string> v8::internal::torque::AbstractTypeDeclaration::generates
Definition at line 892 of file ast.h.
Referenced by v8::internal::torque::TypeVisitor::ComputeType().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/torque/ast.h