v8::internal::MSAControlRegister Struct Reference
#include <register-mips64.h>
Public Member Functions
bool is_valid () const
bool is (MSAControlRegister creg) const
int code () const
int bit () const
void setcode (int f)
Public Attributes
int reg_code
Detailed Description
Definition at line 263 of file register-mips64.h.
Member Function Documentation
bit()
int v8::internal::MSAControlRegister::bit () const [inline]
Definition at line 272 of file register-mips64.h.
                  {
    DCHECK(is_valid());
    return 1 << reg_code;
  }
References v8::internal::DCHECK(), is_valid(), and reg_code.
code()
int v8::internal::MSAControlRegister::code () const [inline]
Definition at line 268 of file register-mips64.h.
                   {
    DCHECK(is_valid());
    return reg_code;
  }
References v8::internal::DCHECK(), is_valid(), and reg_code.
is()
bool v8::internal::MSAControlRegister::is (MSAControlRegister creg) const [inline]
Definition at line 267 of file register-mips64.h.
{ return reg_code == creg.reg_code; }
References reg_code.
is_valid()
bool v8::internal::MSAControlRegister::is_valid () const [inline]
Definition at line 264 of file register-mips64.h.
                        {
    return (reg_code == kMSAIRRegister) || (reg_code == kMSACSRRegister);
  }
References v8::internal::kMSACSRRegister, v8::internal::kMSAIRRegister, and reg_code.
Referenced by bit(), code(), and setcode().
setcode()
void v8::internal::MSAControlRegister::setcode (int f) [inline]
Definition at line 276 of file register-mips64.h.
                      {
    reg_code = f;
    DCHECK(is_valid());
  }
References v8::internal::DCHECK(), is_valid(), and reg_code.
Member Data Documentation
reg_code
int v8::internal::MSAControlRegister::reg_code
Definition at line 281 of file register-mips64.h.
Referenced by bit(), code(), is(), is_valid(), and setcode().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/codegen/mips64/register-mips64.h