v8::internal::compiler::turboshaft::WasmRevecPhase Struct Reference
#include <wasm-revec-phase.h>
Public Member Functions
void Run (PipelineData *data, Zone *temp_zone)
Detailed Description
Definition at line 29 of file wasm-revec-phase.h.
Member Function Documentation
Run()
void v8::internal::compiler::turboshaft::WasmRevecPhase::Run (PipelineData * data, Zone * temp_zone)
Definition at line 14 of file wasm-revec-phase.cc.
                                                            {
  WasmRevecAnalyzer analyzer(data, temp_zone, data->graph());
  if (analyzer.ShouldReduce()) {
    data->set_wasm_revec_analyzer(&analyzer);
    UnparkedScopeIfNeeded scope(data->broker(),
                                v8_flags.turboshaft_trace_reduction);
    CopyingPhase<WasmRevecReducer>::Run(data, temp_zone);
    Isolate* isolate = Isolate::TryGetCurrent();
    WasmRevecVerifier* revec_observer_for_test =
        isolate ? isolate->wasm_revec_verifier_for_test() : nullptr;
    if (revec_observer_for_test) {
      revec_observer_for_test->Verify(data->graph());
    }
    data->clear_wasm_revec_analyzer();
  }
}
References v8::internal::compiler::turboshaft::PipelineData::broker(), v8::internal::compiler::turboshaft::PipelineData::graph(), v8::internal::compiler::turboshaft::CopyingPhase< Reducers >::Run(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::ShouldReduce(), v8::Isolate::TryGetCurrent(), v8::internal::v8_flags, and v8::internal::compiler::turboshaft::WasmRevecVerifier::Verify().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/wasm-revec-phase.h
/mnt/V8SourceCode/src/compiler/turboshaft/wasm-revec-phase.cc