v8::internal::ArrayBufferList Struct Reference
#include <array-buffer-sweeper.h>
Public Types
using Age = ArrayBufferExtension::Age
Public Member Functions
ArrayBufferList (Age age)
bool IsEmpty () const
size_t ApproximateBytes () const
size_t BytesSlow () const
size_t Append (ArrayBufferExtension *extension)
void Append (ArrayBufferList &list)
V8_EXPORT_PRIVATE bool ContainsSlow (ArrayBufferExtension *extension) const
Private Attributes
ArrayBufferExtension * head_ = nullptr
ArrayBufferExtension * tail_ = nullptr
size_t bytes_ = 0
ArrayBufferExtension::Age age_
Friends
class ArrayBufferSweeper
Detailed Description
Definition at line 26 of file array-buffer-sweeper.h.
Member Typedef Documentation
Age
using v8::internal::ArrayBufferList::Age = ArrayBufferExtension::Age
Definition at line 27 of file array-buffer-sweeper.h.
Constructor & Destructor Documentation
ArrayBufferList()
v8::internal::ArrayBufferList::ArrayBufferList (Age age) [inline], [explicit]
Definition at line 29 of file array-buffer-sweeper.h.
: age_(age) {}
Referenced by Append().
Member Function Documentation
Append() [1/2]
size_t v8::internal::ArrayBufferList::Append (ArrayBufferExtension * extension)
Definition at line 23 of file array-buffer-sweeper.cc.
                                                              {
  if (head_ == nullptr) {
    DCHECK_NULL(tail_);
    head_ = tail_ = extension;
  } else {
    tail_->set_next(extension);
    tail_ = extension;
  }
  const size_t accounting_length = [&] {
    if (age_ == ArrayBufferExtension::Age::kOld) {
      return extension->SetOld().accounting_length();
    } else {
      return extension->SetYoung().accounting_length();
    }
  }();
  DCHECK_GE(bytes_ + accounting_length, bytes_);
  bytes_ += accounting_length;
  extension->set_next(nullptr);
  return accounting_length;
}
References v8::internal::ArrayBufferExtension::AccountingState::accounting_length(), age_, bytes_, DCHECK_GE, DCHECK_NULL, head_, v8::internal::ArrayBufferExtension::kOld, v8::internal::ArrayBufferExtension::set_next(), v8::internal::ArrayBufferExtension::SetOld(), v8::internal::ArrayBufferExtension::SetYoung(), and tail_.
Referenced by v8::internal::ArrayBufferSweeper::Append(), v8::internal::ArrayBufferSweeper::SweepingState::MergeTo(), v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::SweepListFull(), and v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::SweepYoung().
Append() [2/2]
void v8::internal::ArrayBufferList::Append (ArrayBufferList & list)
Definition at line 45 of file array-buffer-sweeper.cc.
                                                  {
  DCHECK_EQ(age_, list.age_);
  if (head_ == nullptr) {
    DCHECK_NULL(tail_);
    head_ = list.head_;
    tail_ = list.tail_;
  } else if (list.head_) {
    DCHECK_NOT_NULL(list.tail_);
    tail_->set_next(list.head_);
    tail_ = list.tail_;
  } else {
    DCHECK_NULL(list.tail_);
  }
  bytes_ += list.ApproximateBytes();
  list = ArrayBufferList(age_);
}
References age_, ApproximateBytes(), ArrayBufferList(), bytes_, DCHECK_EQ, DCHECK_NOT_NULL, DCHECK_NULL, head_, v8::internal::ArrayBufferExtension::set_next(), and tail_.
ApproximateBytes()
size_t v8::internal::ArrayBufferList::ApproximateBytes () const [inline]
Definition at line 32 of file array-buffer-sweeper.h.
{ return bytes_; }
References bytes_.
Referenced by Append(), BytesSlow(), v8::internal::ArrayBufferSweeper::OldBytes(), and v8::internal::ArrayBufferSweeper::YoungBytes().
BytesSlow()
size_t v8::internal::ArrayBufferList::BytesSlow () const
Definition at line 72 of file array-buffer-sweeper.cc.
                                        {
  ArrayBufferExtension* current = head_;
  size_t sum = 0;
  while (current) {
    sum += current->accounting_length();
    current = current->next();
  }
  DCHECK_GE(sum, ApproximateBytes());
  return sum;
}
References v8::internal::ArrayBufferExtension::accounting_length(), ApproximateBytes(), DCHECK_GE, head_, and v8::internal::ArrayBufferExtension::next().
ContainsSlow()
bool v8::internal::ArrayBufferList::ContainsSlow (ArrayBufferExtension * extension) const
Definition at line 64 of file array-buffer-sweeper.cc.
                                                                        {
  for (ArrayBufferExtension* current = head_; current;
       current = current->next()) {
    if (current == extension) return true;
  }
  return false;
}
References head_, and v8::internal::ArrayBufferExtension::next().
IsEmpty()
bool v8::internal::ArrayBufferList::IsEmpty () const
Definition at line 83 of file array-buffer-sweeper.cc.
                                    {
  DCHECK_IMPLIES(head_, tail_);
  DCHECK_IMPLIES(!head_, bytes_ == 0);
  return head_ == nullptr;
}
References bytes_, DCHECK_IMPLIES, head_, and tail_.
Referenced by v8::internal::ArrayBufferSweeper::RequestSweep().
Friends And Related Function Documentation
ArrayBufferSweeper
friend class ArrayBufferSweeper [friend]
Definition at line 49 of file array-buffer-sweeper.h.
Member Data Documentation
age_
ArrayBufferExtension::Age v8::internal::ArrayBufferList::age_ [private]
Definition at line 47 of file array-buffer-sweeper.h.
Referenced by Append(), v8::internal::ArrayBufferSweeper::ReleaseAll(), and v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::SweepListFull().
bytes_
size_t v8::internal::ArrayBufferList::bytes_ = 0 [private]
Definition at line 46 of file array-buffer-sweeper.h.
Referenced by Append(), ApproximateBytes(), IsEmpty(), v8::internal::ArrayBufferSweeper::SweepingState::MergeTo(), and v8::internal::ArrayBufferSweeper::UpdateApproximateBytes().
head_
ArrayBufferExtension* v8::internal::ArrayBufferList::head_ = nullptr [private]
Definition at line 41 of file array-buffer-sweeper.h.
Referenced by Append(), BytesSlow(), ContainsSlow(), IsEmpty(), v8::internal::ArrayBufferSweeper::ReleaseAll(), v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::SweepListFull(), and v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::SweepYoung().
tail_
ArrayBufferExtension* v8::internal::ArrayBufferList::tail_ = nullptr [private]
Definition at line 42 of file array-buffer-sweeper.h.
Referenced by Append(), and IsEmpty().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/heap/array-buffer-sweeper.h
/mnt/V8SourceCode/src/heap/array-buffer-sweeper.cc