v8::internal::wasm::WasmInstruction::Optional::Block Struct Reference
#include <wasm-interpreter.h>
Public Member Functions
constexpr bool is_bottom () const
constexpr ValueType value_type () const
Public Attributes
ModuleTypeIndex sig_index
uint32_t value_type_bitfield
Detailed Description
Definition at line 1088 of file wasm-interpreter.h.
Member Function Documentation
is_bottom()
constexpr bool v8::internal::wasm::WasmInstruction::Optional::Block::is_bottom () const [inline], [constexpr]
Definition at line 1092 of file wasm-interpreter.h.
{ return value_type().is_bottom(); }
References v8::internal::wasm::ValueTypeBase::is_bottom(), and value_type().
Referenced by v8::internal::wasm::WasmBytecodeGenerator::GetParamType(), v8::internal::wasm::WasmBytecodeGenerator::GetReturnType(), v8::internal::wasm::WasmBytecodeGenerator::HasVoidSignature(), v8::internal::wasm::WasmBytecodeGenerator::ParamsCount(), and v8::internal::wasm::WasmBytecodeGenerator::ReturnsCount().
value_type()
constexpr ValueType v8::internal::wasm::WasmInstruction::Optional::Block::value_type () const [inline], [constexpr]
Definition at line 1093 of file wasm-interpreter.h.
                                             {
        return ValueType::FromRawBitField(value_type_bitfield);
      }
References v8::internal::wasm::ValueType::FromRawBitField(), and value_type_bitfield.
Referenced by v8::internal::wasm::WasmBytecodeGenerator::GetReturnType(), v8::internal::wasm::WasmBytecodeGenerator::HasVoidSignature(), is_bottom(), v8::internal::wasm::WasmBytecodeGenerator::ReserveBlockSlots(), and v8::internal::wasm::WasmBytecodeGenerator::ReturnsCount().
Member Data Documentation
sig_index
ModuleTypeIndex v8::internal::wasm::WasmInstruction::Optional::Block::sig_index
Definition at line 1089 of file wasm-interpreter.h.
Referenced by v8::internal::wasm::WasmBytecodeGenerator::DecodeInstruction(), v8::internal::wasm::WasmBytecodeGenerator::GetParamType(), v8::internal::wasm::WasmBytecodeGenerator::GetReturnType(), v8::internal::wasm::WasmBytecodeGenerator::HasVoidSignature(), v8::internal::wasm::WasmBytecodeGenerator::ParamsCount(), v8::internal::wasm::WasmBytecodeGenerator::ReserveBlockSlots(), and v8::internal::wasm::WasmBytecodeGenerator::ReturnsCount().
value_type_bitfield
uint32_t v8::internal::wasm::WasmInstruction::Optional::Block::value_type_bitfield
Definition at line 1090 of file wasm-interpreter.h.
Referenced by v8::internal::wasm::WasmBytecodeGenerator::DecodeInstruction(), and value_type().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/wasm/interpreter/wasm-interpreter.h