v8::internal::compiler::turboshaft::anonymous_namespace{decompression-optimization.cc}::DecompressionAnalyzer Struct Reference
Public Member Functions
DecompressionAnalyzer (const Graph &graph, Zone *phase_zone)
void Run ()
bool NeedsDecompression (OpIndex op)
bool NeedsDecompression (const Operation &op)
bool MarkAsNeedsDecompression (OpIndex op)
template<bool is_loop>
void ProcessBlock (const Block &block, int32_t *next_block_id)
void ProcessOperation (const Operation &op)
void MarkAddressingBase (OpIndex base_idx)
Public Attributes
const Graph & graph
Zone * phase_zone
FixedOpIndexSidetable< uint8_t > needs_decompression
ZoneVector< OpIndex > candidates
Detailed Description
Definition at line 23 of file decompression-optimization.cc.
Constructor & Destructor Documentation
DecompressionAnalyzer()
v8::internal::compiler::turboshaft::anonymous_namespace{decompression-optimization.cc}::DecompressionAnalyzer::DecompressionAnalyzer (const Graph & graph, Zone * phase_zone) [inline]
Definition at line 31 of file decompression-optimization.cc.
      : graph(graph),
        phase_zone(phase_zone),
        needs_decompression(graph.op_id_count(), phase_zone, &graph),
        candidates(phase_zone) {
    candidates.reserve(graph.op_id_count() / 8);
  }
References graph(), and v8::internal::ZoneVector< T >::reserve().
Member Function Documentation
MarkAddressingBase()
void v8::internal::compiler::turboshaft::anonymous_namespace{decompression-optimization.cc}::DecompressionAnalyzer::MarkAddressingBase (OpIndex base_idx)
Definition at line 182 of file decompression-optimization.cc.
                                                               {
  DCHECK(DECOMPRESS_POINTER_BY_ADDRESSING_MODE);
  const Operation& base = graph.Get(base_idx);
  if (const LoadOp* load = base.TryCast<LoadOp>();
      load && load->loaded_rep.IsCompressibleTagged()) {
    // We can keep {load} (the base) as compressed and untag with complex
    // addressing mode.
    return;
  }
  if (base.Is<PhiOp>()) {
    bool keep_compressed = true;
    for (OpIndex input_idx : base.inputs()) {
      const Operation& input = graph.Get(input_idx);
      if (!input.Is<LoadOp>() || !base.IsOnlyUserOf(input, graph) ||
          !input.Cast<LoadOp>().loaded_rep.IsCompressibleTagged()) {
        keep_compressed = false;
        break;
      }
    }
    if (keep_compressed) return;
  }
  MarkAsNeedsDecompression(base_idx);
}
References v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::DCHECK(), DECOMPRESS_POINTER_BY_ADDRESSING_MODE, graph(), v8::internal::compiler::turboshaft::Operation::inputs(), v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::compiler::turboshaft::MemoryRepresentation::IsCompressibleTagged(), v8::internal::compiler::turboshaft::Operation::IsOnlyUserOf(), v8::internal::compiler::turboshaft::LoadOp::loaded_rep, and v8::internal::compiler::turboshaft::Operation::TryCast().
MarkAsNeedsDecompression()
bool v8::internal::compiler::turboshaft::anonymous_namespace{decompression-optimization.cc}::DecompressionAnalyzer::MarkAsNeedsDecompression (OpIndex op) [inline]
Definition at line 56 of file decompression-optimization.cc.
                                            {
    return (needs_decompression[op] = true);
  }
NeedsDecompression() [1/2]
bool v8::internal::compiler::turboshaft::anonymous_namespace{decompression-optimization.cc}::DecompressionAnalyzer::NeedsDecompression (const Operation & op) [inline]
Definition at line 53 of file decompression-optimization.cc.
                                               {
    return NeedsDecompression(graph.Index(op));
  }
References graph().
NeedsDecompression() [2/2]
bool v8::internal::compiler::turboshaft::anonymous_namespace{decompression-optimization.cc}::DecompressionAnalyzer::NeedsDecompression (OpIndex op) [inline]
Definition at line 52 of file decompression-optimization.cc.
{ return needs_decompression[op]; }
ProcessBlock()
template<bool is_loop>
void v8::internal::compiler::turboshaft::anonymous_namespace{decompression-optimization.cc}::DecompressionAnalyzer::ProcessBlock (const Block & block, int32_t * next_block_id) [inline]
Definition at line 61 of file decompression-optimization.cc.
                                                                {
    for (const Operation& op : base::Reversed(graph.operations(block))) {
      if (is_loop && op.Is<PhiOp>() && NeedsDecompression(op)) {
        const PhiOp& phi = op.Cast<PhiOp>();
        if (!NeedsDecompression(phi.input(1))) {
          Block* backedge = block.LastPredecessor();
          *next_block_id =
              std::max<int32_t>(*next_block_id, backedge->index().id());
        }
      }
      ProcessOperation(op);
    }
  }
References v8::internal::compiler::turboshaft::Operation::Cast(), graph(), v8::internal::compiler::turboshaft::BlockIndex::id(), v8::internal::compiler::turboshaft::Block::index(), v8::internal::compiler::turboshaft::OperationT< Derived >::input(), v8::internal::compiler::turboshaft::Block::LastPredecessor(), and v8::base::Reversed().
ProcessOperation()
void v8::internal::compiler::turboshaft::anonymous_namespace{decompression-optimization.cc}::DecompressionAnalyzer::ProcessOperation (const Operation & op)
Definition at line 78 of file decompression-optimization.cc.
                                                                {
  switch (op.opcode) {
    case Opcode::kStore: {
      auto& store = op.Cast<StoreOp>();
      MarkAsNeedsDecompression(store.base());
      if (store.index().valid()) {
        MarkAsNeedsDecompression(store.index().value());
      }
      if (!store.stored_rep.IsCompressibleTagged()) {
        MarkAsNeedsDecompression(store.value());
      }
      break;
    }
    case Opcode::kFrameState:
      // The deopt code knows how to handle compressed inputs.
      break;
    case Opcode::kPhi: {
      // Replicate the phi's state for its inputs.
      auto& phi = op.Cast<PhiOp>();
      if (NeedsDecompression(op)) {
        for (OpIndex input : phi.inputs()) {
          MarkAsNeedsDecompression(input);
        }
      } else {
        candidates.push_back(graph.Index(op));
      }
      break;
    }
    case Opcode::kComparison: {
      auto& comp = op.Cast<ComparisonOp>();
      if (comp.rep == WordRepresentation::Word64()) {
        MarkAsNeedsDecompression(comp.left());
        MarkAsNeedsDecompression(comp.right());
      }
      break;
    }
    case Opcode::kWordBinop: {
      auto& binary_op = op.Cast<WordBinopOp>();
      if (binary_op.rep == WordRepresentation::Word64()) {
        MarkAsNeedsDecompression(binary_op.left());
        MarkAsNeedsDecompression(binary_op.right());
      }
      break;
    }
    case Opcode::kShift: {
      auto& shift_op = op.Cast<ShiftOp>();
      if (shift_op.rep == WordRepresentation::Word64()) {
        MarkAsNeedsDecompression(shift_op.left());
      }
      break;
    }
    case Opcode::kChange: {
      auto& change = op.Cast<ChangeOp>();
      if (change.to == WordRepresentation::Word64() && NeedsDecompression(op)) {
        MarkAsNeedsDecompression(change.input());
      }
      break;
    }
    case Opcode::kTaggedBitcast: {
      auto& bitcast = op.Cast<TaggedBitcastOp>();
      if (bitcast.kind != TaggedBitcastOp::Kind::kSmi &&
          NeedsDecompression(op)) {
        MarkAsNeedsDecompression(bitcast.input());
      } else {
        candidates.push_back(graph.Index(op));
      }
      break;
    }
    case Opcode::kConstant:
      if (!NeedsDecompression(op)) {
        candidates.push_back(graph.Index(op));
      }
      break;
    case Opcode::kLoad: {
      if (!NeedsDecompression(op)) {
        candidates.push_back(graph.Index(op));
      }
      const LoadOp& load = op.Cast<LoadOp>();
      if (DECOMPRESS_POINTER_BY_ADDRESSING_MODE && !load.index().valid() &&
          graph.Get(load.base()).saturated_use_count.IsOne()) {
        // On x64, if the Index is invalid, we can rely on complex addressing
        // mode to decompress the base, and can thus keep it compressed.
        // We only do this if the use-count of the base is 1, in order to avoid
        // having to decompress multiple time the same value.
        MarkAddressingBase(load.base());
      } else {
        MarkAsNeedsDecompression(load.base());
        if (load.index().valid()) {
          MarkAsNeedsDecompression(load.index().value());
        }
      }
      break;
    }
    default:
      for (OpIndex input : op.inputs()) {
        MarkAsNeedsDecompression(input);
      }
      break;
  }
}
References v8::internal::compiler::turboshaft::LoadOp::base(), v8::internal::compiler::turboshaft::Operation::Cast(), DECOMPRESS_POINTER_BY_ADDRESSING_MODE, graph(), v8::internal::compiler::turboshaft::LoadOp::index(), v8::internal::compiler::turboshaft::Operation::inputs(), v8::internal::compiler::anonymous_namespace{gap-resolver.cc}::kConstant, v8::internal::compiler::turboshaft::TaggedBitcastOp::kSmi, v8::internal::compiler::turboshaft::Operation::opcode, store(), v8::internal::compiler::turboshaft::OptionalOpIndex::valid(), v8::internal::compiler::turboshaft::OptionalOpIndex::value(), and v8::internal::compiler::turboshaft::WordRepresentation::Word64().
Run()
void v8::internal::compiler::turboshaft::anonymous_namespace{decompression-optimization.cc}::DecompressionAnalyzer::Run () [inline]
Definition at line 39 of file decompression-optimization.cc.
             {
    for (int32_t next_block_id = graph.block_count() - 1; next_block_id >= 0;) {
      BlockIndex block_index = BlockIndex(next_block_id);
      --next_block_id;
      const Block& block = graph.Get(block_index);
      if (block.IsLoop()) {
        ProcessBlock<true>(block, &next_block_id);
      } else {
        ProcessBlock<false>(block, &next_block_id);
      }
    }
  }
References graph(), and v8::internal::compiler::turboshaft::Block::IsLoop().
Member Data Documentation
candidates
ZoneVector<OpIndex> v8::internal::compiler::turboshaft::anonymous_namespace{decompression-optimization.cc}::DecompressionAnalyzer::candidates
Definition at line 29 of file decompression-optimization.cc.
graph
const Graph& v8::internal::compiler::turboshaft::anonymous_namespace{decompression-optimization.cc}::DecompressionAnalyzer::graph
Definition at line 24 of file decompression-optimization.cc.
needs_decompression
FixedOpIndexSidetable<uint8_t> v8::internal::compiler::turboshaft::anonymous_namespace{decompression-optimization.cc}::DecompressionAnalyzer::needs_decompression
Definition at line 28 of file decompression-optimization.cc.
phase_zone
Zone* v8::internal::compiler::turboshaft::anonymous_namespace{decompression-optimization.cc}::DecompressionAnalyzer::phase_zone
Definition at line 25 of file decompression-optimization.cc.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/decompression-optimization.cc