v8::internal::CompiledReplacement::ReplacementPart Struct Reference
Public Member Functions
ReplacementPart (int tag, int data)
Static Public Member Functions
static ReplacementPart SubjectMatch ()
static ReplacementPart SubjectCapture (int capture_index)
static ReplacementPart SubjectPrefix ()
static ReplacementPart SubjectSuffix (int subject_length)
static ReplacementPart ReplacementString ()
static ReplacementPart EmptyReplacement ()
static ReplacementPart ReplacementSubString (int from, int to)
Public Attributes
int tag
int data
Detailed Description
Definition at line 116 of file runtime-regexp.cc.
Constructor & Destructor Documentation
ReplacementPart()
v8::internal::CompiledReplacement::ReplacementPart::ReplacementPart (int tag, int data) [inline]
Definition at line 143 of file runtime-regexp.cc.
                                       : tag(tag), data(data) {
      // Must be non-positive or a PartType value.
      DCHECK(tag < NUMBER_OF_PART_TYPES);
    }
References v8::internal::DCHECK(), v8::internal::CompiledReplacement::NUMBER_OF_PART_TYPES, and tag.
Referenced by EmptyReplacement(), ReplacementString(), ReplacementSubString(), SubjectCapture(), SubjectMatch(), SubjectPrefix(), and SubjectSuffix().
Member Function Documentation
EmptyReplacement()
static ReplacementPart v8::internal::CompiledReplacement::ReplacementPart::EmptyReplacement () [inline], [static]
Definition at line 132 of file runtime-regexp.cc.
                                                     {
      return ReplacementPart(EMPTY_REPLACEMENT, 0);
    }
References v8::internal::CompiledReplacement::EMPTY_REPLACEMENT, and ReplacementPart().
Referenced by v8::internal::CompiledReplacement::ParseReplacementPattern().
ReplacementString()
static ReplacementPart v8::internal::CompiledReplacement::ReplacementPart::ReplacementString () [inline], [static]
Definition at line 129 of file runtime-regexp.cc.
                                                      {
      return ReplacementPart(REPLACEMENT_STRING, 0);
    }
References v8::internal::CompiledReplacement::REPLACEMENT_STRING, and ReplacementPart().
ReplacementSubString()
static ReplacementPart v8::internal::CompiledReplacement::ReplacementPart::ReplacementSubString (int from, int to) [inline], [static]
Definition at line 135 of file runtime-regexp.cc.
                                                                         {
      DCHECK_LE(0, from);
      DCHECK_GT(to, from);
      return ReplacementPart(-from, to);
    }
References DCHECK_GT, DCHECK_LE, and ReplacementPart().
Referenced by v8::internal::CompiledReplacement::ParseReplacementPattern().
SubjectCapture()
static ReplacementPart v8::internal::CompiledReplacement::ReplacementPart::SubjectCapture (int capture_index) [inline], [static]
Definition at line 120 of file runtime-regexp.cc.
                                                                    {
      return ReplacementPart(SUBJECT_CAPTURE, capture_index);
    }
References ReplacementPart(), and v8::internal::CompiledReplacement::SUBJECT_CAPTURE.
Referenced by v8::internal::CompiledReplacement::ParseReplacementPattern().
SubjectMatch()
static ReplacementPart v8::internal::CompiledReplacement::ReplacementPart::SubjectMatch () [inline], [static]
Definition at line 117 of file runtime-regexp.cc.
                                                 {
      return ReplacementPart(SUBJECT_CAPTURE, 0);
    }
References ReplacementPart(), and v8::internal::CompiledReplacement::SUBJECT_CAPTURE.
Referenced by v8::internal::CompiledReplacement::ParseReplacementPattern().
SubjectPrefix()
static ReplacementPart v8::internal::CompiledReplacement::ReplacementPart::SubjectPrefix () [inline], [static]
Definition at line 123 of file runtime-regexp.cc.
                                                  {
      return ReplacementPart(SUBJECT_PREFIX, 0);
    }
References ReplacementPart(), and v8::internal::CompiledReplacement::SUBJECT_PREFIX.
Referenced by v8::internal::CompiledReplacement::ParseReplacementPattern().
SubjectSuffix()
static ReplacementPart v8::internal::CompiledReplacement::ReplacementPart::SubjectSuffix (int subject_length) [inline], [static]
Definition at line 126 of file runtime-regexp.cc.
                                                                    {
      return ReplacementPart(SUBJECT_SUFFIX, subject_length);
    }
References ReplacementPart(), and v8::internal::CompiledReplacement::SUBJECT_SUFFIX.
Referenced by v8::internal::CompiledReplacement::ParseReplacementPattern().
Member Data Documentation
data
int v8::internal::CompiledReplacement::ReplacementPart::data
Definition at line 162 of file runtime-regexp.cc.
tag
int v8::internal::CompiledReplacement::ReplacementPart::tag
Definition at line 149 of file runtime-regexp.cc.
Referenced by ReplacementPart().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/runtime/runtime-regexp.cc