v8::internal::compiler::turboshaft::FrameStateData::Iterator Struct Reference
#include <deopt-data.h>
Public Member Functions
bool has_more () const
Instr current_instr ()
void ConsumeInput (MachineType *machine_type, OpIndex *input)
void ConsumeUnusedRegister ()
void ConsumeDematerializedObject (uint32_t *id, uint32_t *field_count)
void ConsumeDematerializedObjectReference (uint32_t *id)
void ConsumeDematerializedStringConcat (uint32_t *id)
void ConsumeDematerializedStringConcatReference (uint32_t *id)
void ConsumeArgumentsElements (CreateArgumentsType *type)
void ConsumeArgumentsLength ()
void ConsumeRestLength ()
Public Attributes
base::Vector< const Instr > instructions
base::Vector< const MachineType > machine_types
base::Vector< const uint32_t > int_operands
base::Vector< const OpIndex > inputs
Detailed Description
Definition at line 103 of file deopt-data.h.
Member Function Documentation
ConsumeArgumentsElements()
void v8::internal::compiler::turboshaft::FrameStateData::Iterator::ConsumeArgumentsElements (CreateArgumentsType * type) [inline]
Definition at line 155 of file deopt-data.h.
                                                             {
      DCHECK_EQ(instructions[0], Instr::kArgumentsElements);
      instructions += 1;
      *type = static_cast<CreateArgumentsType>(int_operands[0]);
      int_operands += 1;
    }
References DCHECK_EQ, instructions, int_operands, v8::internal::compiler::turboshaft::FrameStateData::kArgumentsElements, and v8::internal::tracing::type.
Referenced by v8::internal::compiler::AddOperandToStateValueDescriptor(), v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::BuildFrameStateInput(), v8::internal::compiler::turboshaft::FrameStateOp::PrintOptions(), and v8::internal::compiler::turboshaft::FrameStateOp::Validate().
ConsumeArgumentsLength()
void v8::internal::compiler::turboshaft::FrameStateData::Iterator::ConsumeArgumentsLength () [inline]
Definition at line 161 of file deopt-data.h.
                                  {
      DCHECK_EQ(instructions[0], Instr::kArgumentsLength);
      instructions += 1;
    }
References DCHECK_EQ, instructions, and v8::internal::compiler::turboshaft::FrameStateData::kArgumentsLength.
Referenced by v8::internal::compiler::AddOperandToStateValueDescriptor(), v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::BuildFrameStateInput(), v8::internal::compiler::turboshaft::FrameStateOp::PrintOptions(), and v8::internal::compiler::turboshaft::FrameStateOp::Validate().
ConsumeDematerializedObject()
void v8::internal::compiler::turboshaft::FrameStateData::Iterator::ConsumeDematerializedObject (uint32_t * id, uint32_t * field_count) [inline]
Definition at line 130 of file deopt-data.h.
                                                                          {
      DCHECK_EQ(instructions[0], Instr::kDematerializedObject);
      instructions += 1;
      *id = int_operands[0];
      *field_count = int_operands[1];
      int_operands += 2;
    }
References DCHECK_EQ, instructions, int_operands, and v8::internal::compiler::turboshaft::FrameStateData::kDematerializedObject.
Referenced by v8::internal::compiler::AddOperandToStateValueDescriptor(), v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::BuildFrameStateInput(), v8::internal::compiler::turboshaft::FrameStateOp::PrintOptions(), and v8::internal::compiler::turboshaft::FrameStateOp::Validate().
ConsumeDematerializedObjectReference()
void v8::internal::compiler::turboshaft::FrameStateData::Iterator::ConsumeDematerializedObjectReference (uint32_t * id) [inline]
Definition at line 137 of file deopt-data.h.
                                                            {
      DCHECK_EQ(instructions[0], Instr::kDematerializedObjectReference);
      instructions += 1;
      *id = int_operands[0];
      int_operands += 1;
    }
References DCHECK_EQ, instructions, int_operands, and v8::internal::compiler::turboshaft::FrameStateData::kDematerializedObjectReference.
Referenced by v8::internal::compiler::AddOperandToStateValueDescriptor(), v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::BuildFrameStateInput(), v8::internal::compiler::turboshaft::FrameStateOp::PrintOptions(), and v8::internal::compiler::turboshaft::FrameStateOp::Validate().
ConsumeDematerializedStringConcat()
void v8::internal::compiler::turboshaft::FrameStateData::Iterator::ConsumeDematerializedStringConcat (uint32_t * id) [inline]
Definition at line 143 of file deopt-data.h.
                                                         {
      DCHECK_EQ(instructions[0], Instr::kDematerializedStringConcat);
      instructions += 1;
      *id = int_operands[0];
      int_operands += 1;
    }
References DCHECK_EQ, instructions, int_operands, and v8::internal::compiler::turboshaft::FrameStateData::kDematerializedStringConcat.
Referenced by v8::internal::compiler::AddOperandToStateValueDescriptor(), v8::internal::compiler::turboshaft::FrameStateOp::PrintOptions(), and v8::internal::compiler::turboshaft::FrameStateOp::Validate().
ConsumeDematerializedStringConcatReference()
void v8::internal::compiler::turboshaft::FrameStateData::Iterator::ConsumeDematerializedStringConcatReference (uint32_t * id) [inline]
Definition at line 149 of file deopt-data.h.
                                                                  {
      DCHECK_EQ(instructions[0], Instr::kDematerializedStringConcatReference);
      instructions += 1;
      *id = int_operands[0];
      int_operands += 1;
    }
References DCHECK_EQ, instructions, int_operands, and v8::internal::compiler::turboshaft::FrameStateData::kDematerializedStringConcatReference.
Referenced by v8::internal::compiler::AddOperandToStateValueDescriptor(), v8::internal::compiler::turboshaft::FrameStateOp::PrintOptions(), and v8::internal::compiler::turboshaft::FrameStateOp::Validate().
ConsumeInput()
void v8::internal::compiler::turboshaft::FrameStateData::Iterator::ConsumeInput (MachineType * machine_type, OpIndex * input) [inline]
Definition at line 118 of file deopt-data.h.
                                                                 {
      DCHECK_EQ(instructions[0], Instr::kInput);
      instructions += 1;
      *machine_type = machine_types[0];
      machine_types += 1;
      *input = inputs[0];
      inputs += 1;
    }
References DCHECK_EQ, inputs, instructions, v8::internal::compiler::turboshaft::FrameStateData::kInput, v8::internal::wasm::machine_type(), and machine_types.
Referenced by v8::internal::compiler::InstructionSelector::AddInputsToFrameStateDescriptor(), v8::internal::compiler::AddOperandToStateValueDescriptor(), v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::BuildFrameStateInput(), v8::internal::compiler::turboshaft::StringEscapeAnalyzer::MarkNextFrameStateInputAsEscaping(), v8::internal::compiler::turboshaft::FrameStateOp::PrintOptions(), and v8::internal::compiler::turboshaft::FrameStateOp::Validate().
ConsumeRestLength()
void v8::internal::compiler::turboshaft::FrameStateData::Iterator::ConsumeRestLength () [inline]
Definition at line 165 of file deopt-data.h.
                             {
      DCHECK_EQ(instructions[0], Instr::kRestLength);
      instructions += 1;
    }
References DCHECK_EQ, instructions, and v8::internal::compiler::turboshaft::FrameStateData::kRestLength.
Referenced by v8::internal::compiler::AddOperandToStateValueDescriptor(), v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::BuildFrameStateInput(), v8::internal::compiler::turboshaft::FrameStateOp::PrintOptions(), and v8::internal::compiler::turboshaft::FrameStateOp::Validate().
ConsumeUnusedRegister()
void v8::internal::compiler::turboshaft::FrameStateData::Iterator::ConsumeUnusedRegister () [inline]
Definition at line 126 of file deopt-data.h.
                                 {
      DCHECK_EQ(instructions[0], Instr::kUnusedRegister);
      instructions += 1;
    }
References DCHECK_EQ, instructions, and v8::internal::compiler::turboshaft::FrameStateData::kUnusedRegister.
Referenced by v8::internal::compiler::AddOperandToStateValueDescriptor(), v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::BuildFrameStateInput(), v8::internal::compiler::turboshaft::FrameStateOp::PrintOptions(), and v8::internal::compiler::turboshaft::FrameStateOp::Validate().
current_instr()
Instr v8::internal::compiler::turboshaft::FrameStateData::Iterator::current_instr () [inline]
Definition at line 116 of file deopt-data.h.
{ return instructions[0]; }
References instructions.
Referenced by v8::internal::compiler::AddOperandToStateValueDescriptor(), v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::BuildFrameStateInput(), v8::internal::compiler::turboshaft::StringEscapeAnalyzer::MarkNextFrameStateInputAsEscaping(), v8::internal::compiler::turboshaft::FrameStateOp::PrintOptions(), and v8::internal::compiler::turboshaft::FrameStateOp::Validate().
has_more()
bool v8::internal::compiler::turboshaft::FrameStateData::Iterator::has_more () const [inline]
Definition at line 109 of file deopt-data.h.
                          {
      DCHECK_IMPLIES(instructions.empty(), machine_types.empty());
      DCHECK_IMPLIES(instructions.empty(), int_operands.empty());
      DCHECK_IMPLIES(instructions.empty(), inputs.empty());
      return !instructions.empty();
    }
References DCHECK_IMPLIES, v8::base::Vector< T >::empty(), inputs, instructions, int_operands, and machine_types.
Referenced by v8::internal::compiler::turboshaft::FrameStateOp::PrintOptions(), and v8::internal::compiler::turboshaft::FrameStateOp::Validate().
Member Data Documentation
inputs
base::Vector<const OpIndex> v8::internal::compiler::turboshaft::FrameStateData::Iterator::inputs
Definition at line 107 of file deopt-data.h.
Referenced by ConsumeInput(), and has_more().
instructions
base::Vector<const Instr> v8::internal::compiler::turboshaft::FrameStateData::Iterator::instructions
Definition at line 104 of file deopt-data.h.
Referenced by ConsumeArgumentsElements(), ConsumeArgumentsLength(), ConsumeDematerializedObject(), ConsumeDematerializedObjectReference(), ConsumeDematerializedStringConcat(), ConsumeDematerializedStringConcatReference(), ConsumeInput(), ConsumeRestLength(), ConsumeUnusedRegister(), current_instr(), and has_more().
int_operands
base::Vector<const uint32_t> v8::internal::compiler::turboshaft::FrameStateData::Iterator::int_operands
Definition at line 106 of file deopt-data.h.
Referenced by ConsumeArgumentsElements(), ConsumeDematerializedObject(), ConsumeDematerializedObjectReference(), ConsumeDematerializedStringConcat(), ConsumeDematerializedStringConcatReference(), and has_more().
machine_types
base::Vector<const MachineType> v8::internal::compiler::turboshaft::FrameStateData::Iterator::machine_types
Definition at line 105 of file deopt-data.h.
Referenced by ConsumeInput(), and has_more().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/deopt-data.h