v8::internal::compiler::turboshaft::TruncateJSPrimitiveToUntaggedOrDeoptOp Struct Reference
#include <operations.h>
Public Types
enum class UntaggedKind : uint8_t { kInt32
 }
using InputRequirement = ConvertJSPrimitiveToUntaggedOrDeoptOp::JSPrimitiveKind
Public Member Functions
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
V< JSPrimitive > input () const
V< FrameState > frame_state () const
TruncateJSPrimitiveToUntaggedOrDeoptOp (V< JSPrimitive > input, V< FrameState > frame_state, UntaggedKind kind, InputRequirement input_requirement, const FeedbackSource &feedback)
void Validate (const Graph &graph) const
auto options () const
Public Attributes
UntaggedKind kind
InputRequirement input_requirement
FeedbackSource feedback
Static Public Attributes
static constexpr OpEffects effects = OpEffects().CanDeopt()
Additional Inherited Members
Detailed Description
Definition at line 5114 of file operations.h.
Member Typedef Documentation
InputRequirement
using v8::internal::compiler::turboshaft::TruncateJSPrimitiveToUntaggedOrDeoptOp::InputRequirement = ConvertJSPrimitiveToUntaggedOrDeoptOp::JSPrimitiveKind
Definition at line 5119 of file operations.h.
Member Enumeration Documentation
UntaggedKind
enum v8::internal::compiler::turboshaft::TruncateJSPrimitiveToUntaggedOrDeoptOp::UntaggedKind : uint8_t [strong]
Enumerator
kInt32
Definition at line 5116 of file operations.h.
                          : uint8_t {
    kInt32,
  };
Constructor & Destructor Documentation
TruncateJSPrimitiveToUntaggedOrDeoptOp()
v8::internal::compiler::turboshaft::TruncateJSPrimitiveToUntaggedOrDeoptOp::TruncateJSPrimitiveToUntaggedOrDeoptOp (V< JSPrimitive > input, V< FrameState > frame_state, UntaggedKind kind, InputRequirement input_requirement, const FeedbackSource & feedback) [inline]
Definition at line 5141 of file operations.h.
      : Base(input, frame_state),
        kind(kind),
        input_requirement(input_requirement),
        feedback(feedback) {}
Member Function Documentation
frame_state()
V<FrameState> v8::internal::compiler::turboshaft::TruncateJSPrimitiveToUntaggedOrDeoptOp::frame_state () const [inline]
Definition at line 5139 of file operations.h.
{ return Base::input<FrameState>(1); }
input()
V<JSPrimitive> v8::internal::compiler::turboshaft::TruncateJSPrimitiveToUntaggedOrDeoptOp::input () const [inline]
Definition at line 5138 of file operations.h.
{ return Base::input<JSPrimitive>(0); }
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::TruncateJSPrimitiveToUntaggedOrDeoptOp::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 5133 of file operations.h.
                                                              {
    return MaybeRepVector<MaybeRegisterRepresentation::Tagged()>();
  }
options()
auto v8::internal::compiler::turboshaft::TruncateJSPrimitiveToUntaggedOrDeoptOp::options () const [inline]
Definition at line 5154 of file operations.h.
{ return std::tuple{kind, input_requirement, feedback}; }
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::TruncateJSPrimitiveToUntaggedOrDeoptOp::outputs_rep () const [inline]
Definition at line 5126 of file operations.h.
                                                               {
    switch (kind) {
      case UntaggedKind::kInt32:
        return RepVector<RegisterRepresentation::Word32()>();
    }
  }
Validate()
void v8::internal::compiler::turboshaft::TruncateJSPrimitiveToUntaggedOrDeoptOp::Validate (const Graph & graph) const [inline]
Definition at line 5150 of file operations.h.
                                          {
    DCHECK(Get(graph, frame_state()).Is<FrameStateOp>());
  }
References v8::internal::DCHECK(), v8::internal::compiler::turboshaft::Get(), and graph().
Member Data Documentation
effects
constexpr OpEffects v8::internal::compiler::turboshaft::TruncateJSPrimitiveToUntaggedOrDeoptOp::effects = OpEffects().CanDeopt() [static], [constexpr]
Definition at line 5125 of file operations.h.
feedback
FeedbackSource v8::internal::compiler::turboshaft::TruncateJSPrimitiveToUntaggedOrDeoptOp::feedback
Definition at line 5123 of file operations.h.
input_requirement
InputRequirement v8::internal::compiler::turboshaft::TruncateJSPrimitiveToUntaggedOrDeoptOp::input_requirement
Definition at line 5122 of file operations.h.
kind
UntaggedKind v8::internal::compiler::turboshaft::TruncateJSPrimitiveToUntaggedOrDeoptOp::kind
Definition at line 5121 of file operations.h.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h