v8::internal::compiler::ConstFieldInfo Struct Reference
#include <simplified-operator.h>
Public Member Functions
ConstFieldInfo ()
ConstFieldInfo (MapRef owner_map)
bool IsConst () const
Static Public Member Functions
static ConstFieldInfo None ()
Public Attributes
OptionalMapRef owner_map
Detailed Description
Definition at line 52 of file simplified-operator.h.
Constructor & Destructor Documentation
ConstFieldInfo() [1/2]
v8::internal::compiler::ConstFieldInfo::ConstFieldInfo () [inline]
Definition at line 57 of file simplified-operator.h.
: owner_map(OptionalMapRef()) {}
ConstFieldInfo() [2/2]
v8::internal::compiler::ConstFieldInfo::ConstFieldInfo (MapRef owner_map) [inline], [explicit]
Definition at line 58 of file simplified-operator.h.
: owner_map(owner_map) {}
Member Function Documentation
IsConst()
bool v8::internal::compiler::ConstFieldInfo::IsConst () const [inline]
Definition at line 60 of file simplified-operator.h.
{ return owner_map.has_value(); }
Referenced by v8::internal::compiler::LoadElimination::AbstractState::AddField(), v8::internal::compiler::LoadElimination::AbstractState::LookupField(), v8::internal::compiler::operator<<(), v8::internal::compiler::LoadElimination::ReduceLoadField(), and v8::internal::compiler::LoadElimination::ReduceStoreField().
None()
static ConstFieldInfo v8::internal::compiler::ConstFieldInfo::None () [inline], [static]
Definition at line 63 of file simplified-operator.h.
{ return ConstFieldInfo(); }
Referenced by v8::internal::compiler::AccessBuilder::ForExternalStringResourceData(), v8::internal::compiler::AccessBuilder::ForJSDataViewDataPointer(), v8::internal::compiler::AccessBuilder::ForJSExternalObjectValue(), v8::internal::compiler::AccessBuilder::ForJSTypedArrayExternalPointer(), v8::internal::compiler::PropertyAccessInfo::GetConstFieldInfo(), v8::internal::compiler::LoadElimination::ReduceLoadField(), v8::internal::compiler::LoadElimination::ReduceStoreField(), and v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteral().
Member Data Documentation
owner_map
OptionalMapRef v8::internal::compiler::ConstFieldInfo::owner_map
Definition at line 55 of file simplified-operator.h.
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), and v8::internal::compiler::operator==().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/simplified-operator.h