cppgc::internal::MakeGarbageCollectedTraitInternal::AllocationDispatcher< GCInfoType, CustomSpace, alignment > Struct Template Reference
#include <allocation.h>
Static Public Member Functions
static void * Invoke (AllocationHandle &handle, size_t size)
Detailed Description
template<typename GCInfoType, typename CustomSpace, size_t alignment>
struct cppgc::internal::MakeGarbageCollectedTraitInternal::AllocationDispatcher< GCInfoType, CustomSpace, alignment >
Definition at line 72 of file allocation.h.
Member Function Documentation
Invoke()
template<typename GCInfoType , typename CustomSpace , size_t alignment>
static void* cppgc::internal::MakeGarbageCollectedTraitInternal::AllocationDispatcher< GCInfoType, CustomSpace, alignment >::Invoke (AllocationHandle & handle, size_t size) [inline], [static]
Definition at line 73 of file allocation.h.
                                                               {
      static_assert(std::is_base_of_v<CustomSpaceBase, CustomSpace>,
                    "Custom space must inherit from CustomSpaceBase.");
      static_assert(
          !CustomSpace::kSupportsCompaction,
          "Custom spaces that support compaction do not support allocating "
          "objects with non-default (i.e. word-sized) alignment.");
      return MakeGarbageCollectedTraitInternal::Allocate(
          handle, size, static_cast<AlignVal>(alignment),
          internal::GCInfoTrait<GCInfoType>::Index(), CustomSpace::kSpaceIndex);
    }
References cppgc::internal::MakeGarbageCollectedTraitInternal::Allocate(), v8::internal::handle(), cppgc::CustomSpace< ConcreteCustomSpace >::kSupportsCompaction, and size().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/include/cppgc/allocation.h