v8::internal::compiler::turboshaft::Word32PairBinopOp Struct Reference
#include <operations.h>
Public Types
enum class Kind : uint8_t {
kAdd
, kSub
, kMul
, kShiftLeft
,
kShiftRightArithmetic
, kShiftRightLogical
 }
Public Member Functions
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (const ZoneVector< MaybeRegisterRepresentation > &storage) const
V< Word32 > left_low () const
V< Word32 > left_high () const
V< Word32 > right_low () const
V< Word32 > right_high () const
Word32PairBinopOp (V< Word32 > left_low, V< Word32 > left_high, V< Word32 > right_low, V< Word32 > right_high, Kind kind)
auto options () const
void PrintOptions (std::ostream &os) const
Public Attributes
Kind kind
Static Public Attributes
static constexpr OpEffects effects = OpEffects()
Additional Inherited Members
Detailed Description
Definition at line 1737 of file operations.h.
Member Enumeration Documentation
Kind
enum v8::internal::compiler::turboshaft::Word32PairBinopOp::Kind : uint8_t [strong]
Enumerator
kAdd
kSub
kMul
kShiftLeft
kShiftRightArithmetic
kShiftRightLogical
Definition at line 1738 of file operations.h.
                  : uint8_t {
    kAdd,
    kSub,
    kMul,
    kShiftLeft,
    kShiftRightArithmetic,
    kShiftRightLogical,
  };
Constructor & Destructor Documentation
Word32PairBinopOp()
v8::internal::compiler::turboshaft::Word32PairBinopOp::Word32PairBinopOp (V< Word32 > left_low, V< Word32 > left_high, V< Word32 > right_low, V< Word32 > right_high, Kind kind) [inline]
Definition at line 1768 of file operations.h.
      : Base(left_low, left_high, right_low, right_high), kind(kind) {}
Member Function Documentation
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::Word32PairBinopOp::inputs_rep (const ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 1755 of file operations.h.
                                                                    {
    return MaybeRepVector<MaybeRegisterRepresentation::Word32(),
                          MaybeRegisterRepresentation::Word32(),
                          MaybeRegisterRepresentation::Word32(),
                          MaybeRegisterRepresentation::Word32()>();
  }
References v8::internal::compiler::turboshaft::MaybeRepVector(), and v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::Word32().
left_high()
V<Word32> v8::internal::compiler::turboshaft::Word32PairBinopOp::left_high () const [inline]
Definition at line 1764 of file operations.h.
{ return input<Word32>(1); }
Referenced by v8::internal::compiler::VisitInt32PairBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitWord32PairShift(), v8::internal::compiler::VisitWord32PairShift(), and v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitWord32PairShift().
left_low()
V<Word32> v8::internal::compiler::turboshaft::Word32PairBinopOp::left_low () const [inline]
Definition at line 1763 of file operations.h.
{ return input<Word32>(0); }
Referenced by v8::internal::compiler::VisitInt32PairBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitWord32PairShift(), v8::internal::compiler::VisitWord32PairShift(), and v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitWord32PairShift().
options()
auto v8::internal::compiler::turboshaft::Word32PairBinopOp::options () const [inline]
Definition at line 1772 of file operations.h.
{ return std::tuple{kind}; }
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::Word32PairBinopOp::outputs_rep () const [inline]
Definition at line 1750 of file operations.h.
                                                               {
    return RepVector<RegisterRepresentation::Word32(),
                     RegisterRepresentation::Word32()>();
  }
References v8::internal::compiler::turboshaft::RepVector(), and v8::internal::compiler::turboshaft::RegisterRepresentation::Word32().
PrintOptions()
void v8::internal::compiler::turboshaft::Word32PairBinopOp::PrintOptions (std::ostream & os) const
Definition at line 1012 of file operations.cc.
                                                         {
  os << '[';
  switch (kind) {
    case Kind::kAdd:
      os << "Add";
      break;
    case Kind::kSub:
      os << "Sub";
      break;
    case Kind::kMul:
      os << "Mul";
      break;
    case Kind::kShiftLeft:
      os << "ShiftLeft";
      break;
    case Kind::kShiftRightArithmetic:
      os << "ShiftRightSigned";
      break;
    case Kind::kShiftRightLogical:
      os << "ShiftRightUnsigned";
      break;
  }
  os << ']';
}
References kAdd, kind, kMul, kShiftLeft, kShiftRightArithmetic, kShiftRightLogical, and kSub.
right_high()
V<Word32> v8::internal::compiler::turboshaft::Word32PairBinopOp::right_high () const [inline]
Definition at line 1766 of file operations.h.
{ return input<Word32>(3); }
Referenced by v8::internal::compiler::VisitInt32PairBinop().
right_low()
V<Word32> v8::internal::compiler::turboshaft::Word32PairBinopOp::right_low () const [inline]
Definition at line 1765 of file operations.h.
{ return input<Word32>(2); }
Referenced by v8::internal::compiler::VisitInt32PairBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitWord32PairShift(), v8::internal::compiler::VisitWord32PairShift(), and v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitWord32PairShift().
Member Data Documentation
effects
constexpr OpEffects v8::internal::compiler::turboshaft::Word32PairBinopOp::effects = OpEffects() [static], [constexpr]
Definition at line 1748 of file operations.h.
kind
Kind v8::internal::compiler::turboshaft::Word32PairBinopOp::kind
Definition at line 1746 of file operations.h.
Referenced by PrintOptions(), and v8::internal::compiler::InstructionSelector::VisitNode().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h
/mnt/V8SourceCode/src/compiler/turboshaft/operations.cc