v8::internal::compiler::BranchMatcher Struct Reference
#include <node-matchers.h>
Public Member Functions
BranchMatcher (Node *branch)
bool Matched () const
Node * Branch () const
Node * IfTrue () const
Node * IfFalse () const
Private Attributes
Node * if_true_
Node * if_false_
Detailed Description
Definition at line 790 of file node-matchers.h.
Constructor & Destructor Documentation
BranchMatcher()
v8::internal::compiler::BranchMatcher::BranchMatcher (Node * branch) [explicit]
Definition at line 16 of file node-matchers.cc.
    : NodeMatcher(branch), if_true_(nullptr), if_false_(nullptr) {
  if (branch->opcode() != IrOpcode::kBranch) return;
  for (Node* use : branch->uses()) {
    if (use->opcode() == IrOpcode::kIfTrue) {
      DCHECK_NULL(if_true_);
      if_true_ = use;
    } else if (use->opcode() == IrOpcode::kIfFalse) {
      DCHECK_NULL(if_false_);
      if_false_ = use;
    }
  }
}
References DCHECK_NULL, if_false_, if_true_, v8::internal::compiler::turboshaft::kBranch, v8::internal::compiler::Node::opcode(), use(), and v8::internal::compiler::Node::uses().
Member Function Documentation
Branch()
Node* v8::internal::compiler::BranchMatcher::Branch () const [inline]
Definition at line 795 of file node-matchers.h.
{ return node(); }
IfFalse()
Node* v8::internal::compiler::BranchMatcher::IfFalse () const [inline]
Definition at line 797 of file node-matchers.h.
{ return if_false_; }
IfTrue()
Node* v8::internal::compiler::BranchMatcher::IfTrue () const [inline]
Definition at line 796 of file node-matchers.h.
{ return if_true_; }
Matched()
bool v8::internal::compiler::BranchMatcher::Matched () const [inline]
Definition at line 793 of file node-matchers.h.
{ return if_true_ && if_false_; }
Member Data Documentation
if_false_
Node* v8::internal::compiler::BranchMatcher::if_false_ [private]
Definition at line 801 of file node-matchers.h.
Referenced by BranchMatcher().
if_true_
Node* v8::internal::compiler::BranchMatcher::if_true_ [private]
Definition at line 800 of file node-matchers.h.
Referenced by BranchMatcher().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/compiler/node-matchers.h
/mnt/V8SourceCode/src/compiler/node-matchers.cc