v8::internal::SegmentedTable< Entry, size >::Segment Struct Reference
#include <segmented-table.h>
Public Member Functions
Segment (uint32_t number)
uint32_t number () const
uint32_t offset () const
uint32_t first_entry () const
uint32_t last_entry () const
bool operator< (const Segment &other) const
Static Public Member Functions
static Segment At (uint32_t offset)
static Segment Containing (uint32_t entry_index)
Private Attributes
const uint32_t number_
Detailed Description
template<typename Entry, size_t size>
struct v8::internal::SegmentedTable< Entry, size >::Segment
Definition at line 83 of file segmented-table.h.
Constructor & Destructor Documentation
Segment()
template<typename Entry , size_t size>
v8::internal::SegmentedTable< Entry, size >::Segment::Segment (uint32_t number) [inline], [explicit]
Definition at line 86 of file segmented-table.h.
: number_(number) {}
Referenced by v8::internal::SegmentedTable< Entry, size >::Segment::At().
Member Function Documentation
At()
template<typename Entry , size_t size>
SegmentedTable< Entry, size >::Segment v8::internal::SegmentedTable< Entry, size >::Segment::At (uint32_t offset) [static]
Definition at line 20 of file segmented-table-inl.h.
                                                      {
  DCHECK(IsAligned(offset, kSegmentSize));
  uint32_t number = offset / kSegmentSize;
  return Segment(number);
}
References v8::internal::DCHECK(), IsAligned(), v8::internal::SegmentedTable< Entry, size >::kSegmentSize, v8::internal::SegmentedTable< Entry, size >::Segment::number(), v8::internal::SegmentedTable< Entry, size >::Segment::offset(), and v8::internal::SegmentedTable< Entry, size >::Segment::Segment().
Referenced by v8::internal::SegmentedTable< WasmCodePointerTableEntry, kCodePointerTableReservationSize >::iter_at(), v8::internal::SegmentedTable< Entry, size >::TryAllocateSegment(), v8::internal::ExternalEntityTable< Entry, size >::TryExtend(), and v8::internal::SegmentedTable< Entry, size >::TryGetSegmentFromPool().
Containing()
template<typename Entry , size_t size>
SegmentedTable< Entry, size >::Segment v8::internal::SegmentedTable< Entry, size >::Segment::Containing (uint32_t entry_index) [static]
Definition at line 28 of file segmented-table-inl.h.
                                                                   {
  uint32_t number = entry_index / kEntriesPerSegment;
  return Segment(number);
}
References v8::internal::SegmentedTable< Entry, size >::kEntriesPerSegment.
Referenced by v8::internal::ExternalEntityTable< Entry, size >::Space::Contains().
first_entry()
template<typename Entry , size_t size>
uint32_t v8::internal::SegmentedTable< Entry, size >::Segment::first_entry () const [inline]
Definition at line 103 of file segmented-table.h.
{ return number_ * kEntriesPerSegment; }
Referenced by v8::internal::SegmentedTable< Entry, size >::InitializeFreeList().
last_entry()
template<typename Entry , size_t size>
uint32_t v8::internal::SegmentedTable< Entry, size >::Segment::last_entry () const [inline]
Definition at line 106 of file segmented-table.h.
                                {
      return first_entry() + kEntriesPerSegment - 1;
    }
Referenced by v8::internal::SegmentedTable< Entry, size >::InitializeFreeList(), and v8::internal::ExternalEntityTable< Entry, size >::TryExtend().
number()
template<typename Entry , size_t size>
uint32_t v8::internal::SegmentedTable< Entry, size >::Segment::number () const [inline]
Definition at line 97 of file segmented-table.h.
{ return number_; }
Referenced by v8::internal::SegmentedTable< Entry, size >::Segment::At(), and v8::internal::ExternalEntityTable< Entry, size >::Extend().
offset()
template<typename Entry , size_t size>
uint32_t v8::internal::SegmentedTable< Entry, size >::Segment::offset () const [inline]
Definition at line 100 of file segmented-table.h.
{ return number_ * kSegmentSize; }
Referenced by v8::internal::SegmentedTable< Entry, size >::Segment::At(), v8::internal::ExternalEntityTable< Entry, size >::Extend(), and v8::internal::SegmentedTable< Entry, size >::FreeTableSegment().
operator<()
template<typename Entry , size_t size>
bool v8::internal::SegmentedTable< Entry, size >::Segment::operator< (const Segment & other) const [inline]
Definition at line 111 of file segmented-table.h.
                                               {
      return number_ < other.number_;
    }
References v8::internal::SegmentedTable< Entry, size >::Segment::number_.
Member Data Documentation
number_
template<typename Entry , size_t size>
const uint32_t v8::internal::SegmentedTable< Entry, size >::Segment::number_ [private]
Definition at line 118 of file segmented-table.h.
Referenced by v8::internal::SegmentedTable< Entry, size >::Segment::operator<().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/common/segmented-table.h
/mnt/V8SourceCode/src/common/segmented-table-inl.h