v8::internal::baseline::detail::PushAllHelper< Arg, Args... > Struct Template Reference
#include <baseline-assembler-arm-inl.h>
Static Public Member Functions
static int Push (BaselineAssembler *basm, Arg arg, Args... args)
static int PushReverse (BaselineAssembler *basm, Arg arg, Args... args)
static int Push (BaselineAssembler *masm, Arg arg, Args... args)
static int PushReverse (BaselineAssembler *masm, Arg arg, Args... args)
static int Push (BaselineAssembler *basm, Arg arg, Args... args)
static int PushReverse (BaselineAssembler *basm, Arg arg, Args... args)
static int Push (BaselineAssembler *basm, Arg arg, Args... args)
static int PushReverse (BaselineAssembler *basm, Arg arg, Args... args)
static int Push (BaselineAssembler *basm, Arg arg, Args... args)
static int PushReverse (BaselineAssembler *basm, Arg arg, Args... args)
static int Push (BaselineAssembler *basm, Arg arg, Args... args)
static int PushReverse (BaselineAssembler *basm, Arg arg, Args... args)
static int Push (BaselineAssembler *basm, Arg arg, Args... args)
static int PushReverse (BaselineAssembler *basm, Arg arg, Args... args)
static int Push (BaselineAssembler *masm, Arg arg, Args... args)
static int PushReverse (BaselineAssembler *masm, Arg arg, Args... args)
Detailed Description
template<typename Arg, typename... Args>
struct v8::internal::baseline::detail::PushAllHelper< Arg, Args... >
Definition at line 254 of file baseline-assembler-arm-inl.h.
Member Function Documentation
Push() [1/8]
template<typename Arg , typename... Args>
static int v8::internal::baseline::detail::PushAllHelper< Arg, Args... >::Push (BaselineAssembler * basm, Arg arg, Args... args) [inline], [static]
Definition at line 255 of file baseline-assembler-arm-inl.h.
                                                                  {
    PushAllHelper<Arg>::Push(basm, arg);
    return 1 + PushAllHelper<Args...>::Push(basm, args...);
  }
References v8::base::args.
Push() [2/8]
template<typename Arg , typename... Args>
static int v8::internal::baseline::detail::PushAllHelper< Arg, Args... >::Push (BaselineAssembler * basm, Arg arg, Args... args) [inline], [static]
Definition at line 253 of file baseline-assembler-loong64-inl.h.
                                                                  {
    PushAllHelper<Arg>::Push(basm, arg);
    return 1 + PushAllHelper<Args...>::Push(basm, args...);
  }
References v8::base::args.
Push() [3/8]
template<typename Arg , typename... Args>
static int v8::internal::baseline::detail::PushAllHelper< Arg, Args... >::Push (BaselineAssembler * basm, Arg arg, Args... args) [inline], [static]
Definition at line 250 of file baseline-assembler-mips64-inl.h.
                                                                  {
    PushAllHelper<Arg>::Push(basm, arg);
    return 1 + PushAllHelper<Args...>::Push(basm, args...);
  }
References v8::base::args.
Push() [4/8]
template<typename Arg , typename... Args>
static int v8::internal::baseline::detail::PushAllHelper< Arg, Args... >::Push (BaselineAssembler * basm, Arg arg, Args... args) [inline], [static]
Definition at line 338 of file baseline-assembler-ppc-inl.h.
                                                                  {
    PushAllHelper<Arg>::Push(basm, arg);
    return 1 + PushAllHelper<Args...>::Push(basm, args...);
  }
References v8::base::args.
Push() [5/8]
template<typename Arg , typename... Args>
static int v8::internal::baseline::detail::PushAllHelper< Arg, Args... >::Push (BaselineAssembler * basm, Arg arg, Args... args) [inline], [static]
Definition at line 259 of file baseline-assembler-riscv-inl.h.
                                                                  {
    PushAllHelper<Arg>::Push(basm, arg);
    return 1 + PushAllHelper<Args...>::Push(basm, args...);
  }
References v8::base::args.
Push() [6/8]
template<typename Arg , typename... Args>
static int v8::internal::baseline::detail::PushAllHelper< Arg, Args... >::Push (BaselineAssembler * basm, Arg arg, Args... args) [inline], [static]
Definition at line 338 of file baseline-assembler-s390-inl.h.
                                                                  {
    PushAllHelper<Arg>::Push(basm, arg);
    return 1 + PushAllHelper<Args...>::Push(basm, args...);
  }
References v8::base::args.
Push() [7/8]
template<typename Arg , typename... Args>
static int v8::internal::baseline::detail::PushAllHelper< Arg, Args... >::Push (BaselineAssembler * masm, Arg arg, Args... args) [inline], [static]
Definition at line 284 of file baseline-assembler-ia32-inl.h.
                                                                  {
    int nargs = PushHelper<Arg>::Push(masm, arg);
    return nargs + PushAllHelper<Args...>::Push(masm, args...);
  }
References v8::base::args, and v8::internal::baseline::detail::PushHelper< Arg >::Push().
Push() [8/8]
template<typename Arg , typename... Args>
static int v8::internal::baseline::detail::PushAllHelper< Arg, Args... >::Push (BaselineAssembler * masm, Arg arg, Args... args) [inline], [static]
Definition at line 295 of file baseline-assembler-x64-inl.h.
                                                                  {
    int nargs = PushHelper<Arg>::Push(masm, arg);
    return nargs + PushAllHelper<Args...>::Push(masm, args...);
  }
References v8::base::args, and v8::internal::baseline::detail::PushHelper< Arg >::Push().
PushReverse() [1/8]
template<typename Arg , typename... Args>
static int v8::internal::baseline::detail::PushAllHelper< Arg, Args... >::PushReverse (BaselineAssembler * basm, Arg arg, Args... args) [inline], [static]
Definition at line 259 of file baseline-assembler-arm-inl.h.
                                                                         {
    int nargs = PushAllHelper<Args...>::PushReverse(basm, args...);
    PushAllHelper<Arg>::Push(basm, arg);
    return nargs + 1;
  }
References v8::base::args.
PushReverse() [2/8]
template<typename Arg , typename... Args>
static int v8::internal::baseline::detail::PushAllHelper< Arg, Args... >::PushReverse (BaselineAssembler * basm, Arg arg, Args... args) [inline], [static]
Definition at line 257 of file baseline-assembler-loong64-inl.h.
                                                                         {
    int nargs = PushAllHelper<Args...>::PushReverse(basm, args...);
    PushAllHelper<Arg>::Push(basm, arg);
    return nargs + 1;
  }
References v8::base::args.
PushReverse() [3/8]
template<typename Arg , typename... Args>
static int v8::internal::baseline::detail::PushAllHelper< Arg, Args... >::PushReverse (BaselineAssembler * basm, Arg arg, Args... args) [inline], [static]
Definition at line 254 of file baseline-assembler-mips64-inl.h.
                                                                         {
    int nargs = PushAllHelper<Args...>::PushReverse(basm, args...);
    PushAllHelper<Arg>::Push(basm, arg);
    return nargs + 1;
  }
References v8::base::args.
PushReverse() [4/8]
template<typename Arg , typename... Args>
static int v8::internal::baseline::detail::PushAllHelper< Arg, Args... >::PushReverse (BaselineAssembler * basm, Arg arg, Args... args) [inline], [static]
Definition at line 342 of file baseline-assembler-ppc-inl.h.
                                                                         {
    int nargs = PushAllHelper<Args...>::PushReverse(basm, args...);
    PushAllHelper<Arg>::Push(basm, arg);
    return nargs + 1;
  }
References v8::base::args.
PushReverse() [5/8]
template<typename Arg , typename... Args>
static int v8::internal::baseline::detail::PushAllHelper< Arg, Args... >::PushReverse (BaselineAssembler * basm, Arg arg, Args... args) [inline], [static]
Definition at line 263 of file baseline-assembler-riscv-inl.h.
                                                                         {
    int nargs = PushAllHelper<Args...>::PushReverse(basm, args...);
    PushAllHelper<Arg>::Push(basm, arg);
    return nargs + 1;
  }
References v8::base::args.
PushReverse() [6/8]
template<typename Arg , typename... Args>
static int v8::internal::baseline::detail::PushAllHelper< Arg, Args... >::PushReverse (BaselineAssembler * basm, Arg arg, Args... args) [inline], [static]
Definition at line 342 of file baseline-assembler-s390-inl.h.
                                                                         {
    int nargs = PushAllHelper<Args...>::PushReverse(basm, args...);
    PushAllHelper<Arg>::Push(basm, arg);
    return nargs + 1;
  }
References v8::base::args.
PushReverse() [7/8]
template<typename Arg , typename... Args>
static int v8::internal::baseline::detail::PushAllHelper< Arg, Args... >::PushReverse (BaselineAssembler * masm, Arg arg, Args... args) [inline], [static]
Definition at line 288 of file baseline-assembler-ia32-inl.h.
                                                                         {
    int nargs = PushAllHelper<Args...>::PushReverse(masm, args...);
    return nargs + PushHelper<Arg>::PushReverse(masm, arg);
  }
References v8::base::args, and v8::internal::baseline::detail::PushHelper< Arg >::PushReverse().
PushReverse() [8/8]
template<typename Arg , typename... Args>
static int v8::internal::baseline::detail::PushAllHelper< Arg, Args... >::PushReverse (BaselineAssembler * masm, Arg arg, Args... args) [inline], [static]
Definition at line 299 of file baseline-assembler-x64-inl.h.
                                                                         {
    int nargs = PushAllHelper<Args...>::PushReverse(masm, args...);
    return nargs + PushHelper<Arg>::PushReverse(masm, arg);
  }
References v8::base::args, and v8::internal::baseline::detail::PushHelper< Arg >::PushReverse().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/baseline/arm/baseline-assembler-arm-inl.h
/mnt/V8SourceCode/src/baseline/ia32/baseline-assembler-ia32-inl.h
/mnt/V8SourceCode/src/baseline/loong64/baseline-assembler-loong64-inl.h
/mnt/V8SourceCode/src/baseline/mips64/baseline-assembler-mips64-inl.h
/mnt/V8SourceCode/src/baseline/ppc/baseline-assembler-ppc-inl.h
/mnt/V8SourceCode/src/baseline/riscv/baseline-assembler-riscv-inl.h
/mnt/V8SourceCode/src/baseline/s390/baseline-assembler-s390-inl.h
/mnt/V8SourceCode/src/baseline/x64/baseline-assembler-x64-inl.h