v8::internal::ArrayBufferExtension::AccountingState Struct Reference
#include <js-array-buffer.h>
Public Member Functions
size_t accounting_length () const
Age age () const
Public Attributes
uint64_t value
Detailed Description
Definition at line 204 of file js-array-buffer.h.
Member Function Documentation
accounting_length()
size_t v8::internal::ArrayBufferExtension::AccountingState::accounting_length () const [inline]
Definition at line 205 of file js-array-buffer.h.
                                     {
      return AccountingLengthField::decode(value);
    }
References v8::base::BitField< T, shift, size, U >::decode(), and value.
Referenced by v8::internal::ArrayBufferList::Append(), v8::internal::ArrayBufferSweeper::Detach(), and v8::internal::ArrayBufferSweeper::ReleaseAll().
age()
Age v8::internal::ArrayBufferExtension::AccountingState::age () const [inline]
Definition at line 208 of file js-array-buffer.h.
{ return static_cast<Age>(AgeField::decode(value)); }
References v8::base::BitField< T, shift, size, U >::decode(), and value.
Referenced by v8::internal::ArrayBufferSweeper::Detach(), and v8::internal::ArrayBufferSweeper::Resize().
Member Data Documentation
value
uint64_t v8::internal::ArrayBufferExtension::AccountingState::value
Definition at line 210 of file js-array-buffer.h.
Referenced by accounting_length(), and age().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/objects/js-array-buffer.h