v8::internal::wasm::FrameState Struct Reference
#include <wasm-interpreter.h>
Public Member Functions
FrameState ()
void SetCaughtException (Isolate *isolate, uint32_t catch_block_index, DirectHandle< Object > exception)
DirectHandle< Object > GetCaughtException (Isolate *isolate, uint32_t catch_block_index) const
void DisposeCaughtExceptionsArray (Isolate *isolate)
void ResetHandleScope (Isolate *isolate)
Public Attributes
const WasmBytecode * current_function_
const FrameState * previous_frame_
const uint8_t * current_bytecode_
uint8_t * current_sp_
WasmInterpreterThread * thread_
uint32_t ref_array_current_sp_
HandleScope * handle_scope_
Handle< FixedArray > caught_exceptions_
Detailed Description
Definition at line 96 of file wasm-interpreter.h.
Constructor & Destructor Documentation
FrameState()
v8::internal::wasm::FrameState::FrameState () [inline]
Definition at line 97 of file wasm-interpreter.h.
      : current_function_(nullptr),
        previous_frame_(nullptr),
        current_bytecode_(nullptr),
        current_sp_(nullptr),
        thread_(nullptr),
        ref_array_current_sp_(0),
        handle_scope_(nullptr)
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
        ,
        current_stack_height_(0),
        current_stack_start_args_(0),
        current_stack_start_locals_(0),
        current_stack_start_stack_(0)
#endif // V8_ENABLE_DRUMBRAKE_TRACING
  {
  }
References current_bytecode_, current_function_, current_sp_, handle_scope_, previous_frame_, ref_array_current_sp_, and thread_.
Member Function Documentation
DisposeCaughtExceptionsArray()
void v8::internal::wasm::FrameState::DisposeCaughtExceptionsArray (Isolate * isolate)
Definition at line 209 of file wasm-interpreter.cc.
                                                              {
  if (!caught_exceptions_.is_null()) {
    isolate->global_handles()->Destroy(caught_exceptions_.location());
    caught_exceptions_ = Handle<FixedArray>::null();
  }
}
References v8::internal::GlobalHandles::Destroy(), v8::internal::Isolate::global_handles(), and v8::internal::Handle< T >::null().
GetCaughtException()
DirectHandle< Object > v8::internal::wasm::FrameState::GetCaughtException (Isolate * isolate, uint32_t catch_block_index) const
Definition at line 201 of file wasm-interpreter.cc.
                                                        {
  DirectHandle<Object> exception(caught_exceptions_->get(catch_block_index),
                                 isolate);
  DCHECK(!IsTheHole(*exception));
  return exception;
}
References v8::internal::DCHECK().
ResetHandleScope()
void v8::internal::wasm::FrameState::ResetHandleScope (Isolate * isolate) [inline]
Definition at line 156 of file wasm-interpreter-inl.h.
                                                         {
  DCHECK_NOT_NULL(handle_scope_);
  {
    HandleScope old(std::move(*handle_scope_));
    // The HandleScope destructor cleans up the old HandleScope.
  }
  // Now that the old HandleScope has been destroyed, make a new one.
  *handle_scope_ = HandleScope(isolate);
}
References DCHECK_NOT_NULL.
SetCaughtException()
void v8::internal::wasm::FrameState::SetCaughtException (Isolate * isolate, uint32_t catch_block_index, DirectHandle< Object > exception)
Definition at line 188 of file wasm-interpreter.cc.
                                                                    {
  if (caught_exceptions_.is_null()) {
    DCHECK_NOT_NULL(current_function_);
    uint32_t blocks_count = current_function_->GetBlocksCount();
    DirectHandle<FixedArray> caught_exceptions =
        isolate->factory()->NewFixedArrayWithHoles(blocks_count);
    caught_exceptions_ = isolate->global_handles()->Create(*caught_exceptions);
  }
  caught_exceptions_->set(catch_block_index, *exception);
}
References v8::internal::GlobalHandles::Create(), DCHECK_NOT_NULL, v8::internal::Isolate::factory(), v8::internal::Isolate::global_handles(), and v8::internal::FactoryBase< Impl >::NewFixedArrayWithHoles().
Member Data Documentation
caught_exceptions_
Handle<FixedArray> v8::internal::wasm::FrameState::caught_exceptions_
Definition at line 129 of file wasm-interpreter.h.
current_bytecode_
const uint8_t* v8::internal::wasm::FrameState::current_bytecode_
Definition at line 117 of file wasm-interpreter.h.
Referenced by FrameState().
current_function_
const WasmBytecode* v8::internal::wasm::FrameState::current_function_
Definition at line 115 of file wasm-interpreter.h.
Referenced by FrameState().
current_sp_
uint8_t* v8::internal::wasm::FrameState::current_sp_
Definition at line 118 of file wasm-interpreter.h.
Referenced by FrameState().
handle_scope_
HandleScope* v8::internal::wasm::FrameState::handle_scope_
Definition at line 121 of file wasm-interpreter.h.
Referenced by FrameState().
previous_frame_
const FrameState* v8::internal::wasm::FrameState::previous_frame_
Definition at line 116 of file wasm-interpreter.h.
Referenced by FrameState().
ref_array_current_sp_
uint32_t v8::internal::wasm::FrameState::ref_array_current_sp_
Definition at line 120 of file wasm-interpreter.h.
Referenced by FrameState().
thread_
WasmInterpreterThread* v8::internal::wasm::FrameState::thread_
Definition at line 119 of file wasm-interpreter.h.
Referenced by FrameState().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/wasm/interpreter/wasm-interpreter.h
/mnt/V8SourceCode/src/wasm/interpreter/wasm-interpreter-inl.h
/mnt/V8SourceCode/src/wasm/interpreter/wasm-interpreter.cc