v8::internal::compiler::turboshaft::fast_hash< base::Vector< T > > Struct Template Reference
#include <fast-hash.h>
Public Member Functions
size_t operator() (base::Vector< T > v) const
Detailed Description
template<typename T>
struct v8::internal::compiler::turboshaft::fast_hash< base::Vector< T > >
Definition at line 81 of file fast-hash.h.
Member Function Documentation
operator()()
template<typename T >
size_t v8::internal::compiler::turboshaft::fast_hash< base::Vector< T > >::operator() (base::Vector< T > v) const [inline]
Definition at line 82 of file fast-hash.h.
                                                     {
    return fast_hash_range(v.begin(), v.end());
  }
References v8::base::Vector< T >::begin(), v8::base::Vector< T >::end(), and v8::internal::compiler::turboshaft::fast_hash_range().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/fast-hash.h