v8::internal::compiler::turboshaft::BitcastWord32PairToFloat64Op Struct Reference
#include <operations.h>
Public Member Functions
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
V< Word32 > high_word32 () const
V< Word32 > low_word32 () const
BitcastWord32PairToFloat64Op (V< Word32 > high_word32, V< Word32 > low_word32)
auto options () const
Static Public Attributes
static constexpr OpEffects effects = OpEffects()
Additional Inherited Members
Detailed Description
Definition at line 2414 of file operations.h.
Constructor & Destructor Documentation
BitcastWord32PairToFloat64Op()
v8::internal::compiler::turboshaft::BitcastWord32PairToFloat64Op::BitcastWord32PairToFloat64Op (V< Word32 > high_word32, V< Word32 > low_word32) [inline]
Definition at line 2430 of file operations.h.
      : Base(high_word32, low_word32) {}
Member Function Documentation
high_word32()
V<Word32> v8::internal::compiler::turboshaft::BitcastWord32PairToFloat64Op::high_word32 () const [inline]
Definition at line 2427 of file operations.h.
{ return input<Word32>(0); }
Referenced by v8::internal::compiler::InstructionSelector::VisitBitcastWord32PairToFloat64().
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::BitcastWord32PairToFloat64Op::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 2421 of file operations.h.
                                                              {
    return MaybeRepVector<MaybeRegisterRepresentation::Word32(),
                          MaybeRegisterRepresentation::Word32()>();
  }
References v8::internal::compiler::turboshaft::MaybeRepVector(), and v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::Word32().
low_word32()
V<Word32> v8::internal::compiler::turboshaft::BitcastWord32PairToFloat64Op::low_word32 () const [inline]
Definition at line 2428 of file operations.h.
{ return input<Word32>(1); }
Referenced by v8::internal::compiler::InstructionSelector::VisitBitcastWord32PairToFloat64().
options()
auto v8::internal::compiler::turboshaft::BitcastWord32PairToFloat64Op::options () const [inline]
Definition at line 2433 of file operations.h.
{ return std::tuple{}; }
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::BitcastWord32PairToFloat64Op::outputs_rep () const [inline]
Definition at line 2417 of file operations.h.
                                                               {
    return RepVector<RegisterRepresentation::Float64()>();
  }
Member Data Documentation
effects
constexpr OpEffects v8::internal::compiler::turboshaft::BitcastWord32PairToFloat64Op::effects = OpEffects() [static], [constexpr]
Definition at line 2416 of file operations.h.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h