v8::internal::ParserBase< Impl >::NextArrowFunctionInfo Struct Reference
Public Member Functions
bool HasInitialState () const
void Reset ()
void ClearStrictParameterError ()
Public Attributes
Scanner::Location strict_parameter_error_location
MessageTemplate strict_parameter_error_message = MessageTemplate::kNone
DeclarationScope * scope = nullptr
int function_literal_id = -1
bool could_be_immediately_invoked = false
Detailed Description
template<typename Impl>
struct v8::internal::ParserBase< Impl >::NextArrowFunctionInfo
Definition at line 1779 of file parser-base.h.
Member Function Documentation
ClearStrictParameterError()
template<typename Impl >
void v8::internal::ParserBase< Impl >::NextArrowFunctionInfo::ClearStrictParameterError () [inline]
Definition at line 1801 of file parser-base.h.
                                     {
      strict_parameter_error_location = Scanner::Location::invalid();
      strict_parameter_error_message = MessageTemplate::kNone;
    }
References v8::internal::Scanner::Location::invalid(), v8::internal::ParserBase< Impl >::NextArrowFunctionInfo::strict_parameter_error_location, and v8::internal::ParserBase< Impl >::NextArrowFunctionInfo::strict_parameter_error_message.
Referenced by v8::internal::ParserBase< Impl >::ParsePrimaryExpression(), and v8::internal::ParserBase< Impl >::NextArrowFunctionInfo::Reset().
HasInitialState()
template<typename Impl >
bool v8::internal::ParserBase< Impl >::NextArrowFunctionInfo::HasInitialState () const [inline]
Definition at line 1787 of file parser-base.h.
{ return scope == nullptr; }
References v8::internal::ParserBase< Impl >::NextArrowFunctionInfo::scope.
Referenced by v8::internal::ParserBase< Impl >::ParseAssignmentExpressionCoverGrammar(), v8::internal::ParserBase< Impl >::ParseConditionalChainAssignmentExpressionCoverGrammar(), and v8::internal::ParserBase< Impl >::NextArrowFunctionInfo::Reset().
Reset()
template<typename Impl >
void v8::internal::ParserBase< Impl >::NextArrowFunctionInfo::Reset () [inline]
Definition at line 1789 of file parser-base.h.
                 {
      scope = nullptr;
      function_literal_id = -1;
      ClearStrictParameterError();
      could_be_immediately_invoked = false;
      DCHECK(HasInitialState());
    }
References v8::internal::ParserBase< Impl >::NextArrowFunctionInfo::ClearStrictParameterError(), v8::internal::ParserBase< Impl >::NextArrowFunctionInfo::could_be_immediately_invoked, v8::internal::DCHECK(), v8::internal::ParserBase< Impl >::NextArrowFunctionInfo::function_literal_id, v8::internal::ParserBase< Impl >::NextArrowFunctionInfo::HasInitialState(), and v8::internal::ParserBase< Impl >::NextArrowFunctionInfo::scope.
Referenced by v8::internal::ParserBase< Impl >::ParseArrowFunctionLiteral(), and v8::internal::ParserBase< Impl >::ParseAssignmentExpressionCoverGrammarContinuation().
Member Data Documentation
could_be_immediately_invoked
template<typename Impl >
bool v8::internal::ParserBase< Impl >::NextArrowFunctionInfo::could_be_immediately_invoked = false
Definition at line 1785 of file parser-base.h.
Referenced by v8::internal::ParserBase< Impl >::ParseAssignmentExpressionCoverGrammarContinuation(), v8::internal::ParserBase< Impl >::ParsePrimaryExpression(), and v8::internal::ParserBase< Impl >::NextArrowFunctionInfo::Reset().
function_literal_id
template<typename Impl >
int v8::internal::ParserBase< Impl >::NextArrowFunctionInfo::function_literal_id = -1
Definition at line 1784 of file parser-base.h.
Referenced by v8::internal::ParserBase< Impl >::ParseAssignmentExpressionCoverGrammarContinuation(), v8::internal::ParserBase< Impl >::ParseLeftHandSideContinuation(), v8::internal::ParserBase< Impl >::ParsePrimaryExpression(), and v8::internal::ParserBase< Impl >::NextArrowFunctionInfo::Reset().
scope
template<typename Impl >
DeclarationScope* v8::internal::ParserBase< Impl >::NextArrowFunctionInfo::scope = nullptr
Definition at line 1783 of file parser-base.h.
Referenced by v8::internal::ParserBase< Impl >::NextArrowFunctionInfo::HasInitialState(), v8::internal::ParserBase< Impl >::ParseArrowFunctionLiteral(), v8::internal::ParserBase< Impl >::ParseAssignmentExpressionCoverGrammarContinuation(), v8::internal::ParserBase< Impl >::ParseLeftHandSideContinuation(), v8::internal::ParserBase< Impl >::ParsePrimaryExpression(), and v8::internal::ParserBase< Impl >::NextArrowFunctionInfo::Reset().
strict_parameter_error_location
template<typename Impl >
Scanner::Location v8::internal::ParserBase< Impl >::NextArrowFunctionInfo::strict_parameter_error_location
Initial value:
=
        Scanner::Location::invalid()
Definition at line 1780 of file parser-base.h.
Referenced by v8::internal::ParserBase< Impl >::NextArrowFunctionInfo::ClearStrictParameterError(), and v8::internal::ParserBase< Impl >::ParseAssignmentExpressionCoverGrammarContinuation().
strict_parameter_error_message
template<typename Impl >
MessageTemplate v8::internal::ParserBase< Impl >::NextArrowFunctionInfo::strict_parameter_error_message = MessageTemplate::kNone
Definition at line 1782 of file parser-base.h.
Referenced by v8::internal::ParserBase< Impl >::NextArrowFunctionInfo::ClearStrictParameterError(), and v8::internal::ParserBase< Impl >::ParseAssignmentExpressionCoverGrammarContinuation().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/parsing/parser-base.h