v8::internal::baseline::detail::PopAllHelper< Register > Struct Reference
#include <baseline-assembler-arm-inl.h>
Static Public Member Functions
static void Pop (BaselineAssembler *basm, Register reg)
static void Pop (BaselineAssembler *basm, Register reg)
static void Pop (BaselineAssembler *basm, Register reg)
static void Pop (BaselineAssembler *basm, Register reg)
static void Pop (BaselineAssembler *basm, Register reg)
static void Pop (BaselineAssembler *basm, Register reg)
static void Pop (BaselineAssembler *basm, Register reg)
Detailed Description
Definition at line 293 of file baseline-assembler-arm-inl.h.
Member Function Documentation
Pop() [1/7]
static void v8::internal::baseline::detail::PopAllHelper< Register >::Pop (BaselineAssembler * basm, Register reg) [inline], [static]
Definition at line 294 of file baseline-assembler-arm-inl.h.
                                                         {
    basm->masm()->Pop(reg);
  }
References v8::internal::baseline::BaselineAssembler::masm(), and v8::internal::MacroAssembler::Pop().
Pop() [2/7]
static void v8::internal::baseline::detail::PopAllHelper< Register >::Pop (BaselineAssembler * basm, Register reg) [inline], [static]
Definition at line 360 of file baseline-assembler-arm64-inl.h.
                                                         {
    basm->masm()->Pop(reg, padreg);
  }
References v8::internal::baseline::BaselineAssembler::masm(), v8::internal::padreg, and v8::internal::MacroAssembler::Pop().
Pop() [3/7]
static void v8::internal::baseline::detail::PopAllHelper< Register >::Pop (BaselineAssembler * basm, Register reg) [inline], [static]
Definition at line 293 of file baseline-assembler-loong64-inl.h.
                                                         {
    basm->masm()->Pop(reg);
  }
References v8::internal::baseline::BaselineAssembler::masm(), and v8::internal::MacroAssembler::Pop().
Pop() [4/7]
static void v8::internal::baseline::detail::PopAllHelper< Register >::Pop (BaselineAssembler * basm, Register reg) [inline], [static]
Definition at line 289 of file baseline-assembler-mips64-inl.h.
                                                         {
    basm->masm()->Pop(reg);
  }
References v8::internal::baseline::BaselineAssembler::masm(), and v8::internal::MacroAssembler::Pop().
Pop() [5/7]
static void v8::internal::baseline::detail::PopAllHelper< Register >::Pop (BaselineAssembler * basm, Register reg) [inline], [static]
Definition at line 377 of file baseline-assembler-ppc-inl.h.
                                                         {
    basm->masm()->Pop(reg);
  }
References v8::internal::baseline::BaselineAssembler::masm(), and v8::internal::MacroAssembler::Pop().
Pop() [6/7]
static void v8::internal::baseline::detail::PopAllHelper< Register >::Pop (BaselineAssembler * basm, Register reg) [inline], [static]
Definition at line 295 of file baseline-assembler-riscv-inl.h.
                                                         {
    basm->masm()->Pop(reg);
  }
References v8::internal::baseline::BaselineAssembler::masm(), and v8::internal::MacroAssembler::Pop().
Pop() [7/7]
static void v8::internal::baseline::detail::PopAllHelper< Register >::Pop (BaselineAssembler * basm, Register reg) [inline], [static]
Definition at line 377 of file baseline-assembler-s390-inl.h.
                                                         {
    basm->masm()->Pop(reg);
  }
References v8::internal::baseline::BaselineAssembler::masm(), and v8::internal::MacroAssembler::Pop().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/baseline/arm/baseline-assembler-arm-inl.h
/mnt/V8SourceCode/src/baseline/arm64/baseline-assembler-arm64-inl.h
/mnt/V8SourceCode/src/baseline/loong64/baseline-assembler-loong64-inl.h
/mnt/V8SourceCode/src/baseline/mips64/baseline-assembler-mips64-inl.h
/mnt/V8SourceCode/src/baseline/ppc/baseline-assembler-ppc-inl.h
/mnt/V8SourceCode/src/baseline/riscv/baseline-assembler-riscv-inl.h
/mnt/V8SourceCode/src/baseline/s390/baseline-assembler-s390-inl.h