v8_inspector::anonymous_namespace{value-mirror.cc}::EntryMirror Struct Reference
Static Public Member Functions
static bool getEntries (v8::Local< v8::Context > context, v8::Local< v8::Object > object, size_t limit, bool *overflow, std::vector< EntryMirror > *mirrors)
Public Attributes
std::unique_ptr< ValueMirror > key
std::unique_ptr< ValueMirror > value
Detailed Description
Definition at line 994 of file value-mirror.cc.
Member Function Documentation
getEntries()
static bool v8_inspector::anonymous_namespace{value-mirror.cc}::EntryMirror::getEntries (v8::Local< v8::Context > context, v8::Local< v8::Object > object, size_t limit, bool * overflow, std::vector< EntryMirror > * mirrors) [inline], [static]
Definition at line 998 of file value-mirror.cc.
                                                                          {
    bool isKeyValue = false;
    v8::Local<v8::Array> entries;
    if (!object->PreviewEntries(&isKeyValue).ToLocal(&entries)) return false;
    for (uint32_t i = 0; i < entries->Length(); i += isKeyValue ? 2 : 1) {
      v8::Local<v8::Value> tmp;
      std::unique_ptr<ValueMirror> keyMirror;
      if (isKeyValue && entries->Get(context, i).ToLocal(&tmp)) {
        keyMirror = ValueMirror::create(context, tmp);
      }
      std::unique_ptr<ValueMirror> valueMirror;
      if (entries->Get(context, isKeyValue ? i + 1 : i).ToLocal(&tmp)) {
        valueMirror = ValueMirror::create(context, tmp);
      } else {
        continue;
      }
      if (mirrors->size() == limit) {
        *overflow = true;
        return true;
      }
      mirrors->emplace_back(
          EntryMirror{std::move(keyMirror), std::move(valueMirror)});
    }
    return !mirrors->empty();
  }
References v8_inspector::ValueMirror::create(), v8::Object::Get(), v8::Array::Length(), v8::internal::overflow, v8::Object::PreviewEntries(), and v8::MaybeLocal< T >::ToLocal().
Member Data Documentation
key
std::unique_ptr<ValueMirror> v8_inspector::anonymous_namespace{value-mirror.cc}::EntryMirror::key
Definition at line 995 of file value-mirror.cc.
value
std::unique_ptr<ValueMirror> v8_inspector::anonymous_namespace{value-mirror.cc}::EntryMirror::value
Definition at line 996 of file value-mirror.cc.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/inspector/value-mirror.cc