v8::internal::compiler::turboshaft::ProfileApplicationPhase Struct Reference
#include <instruction-selection-phase.h>
Public Member Functions
void Run (PipelineData *data, Zone *temp_zone, const ProfileDataFromFile *profile)
Detailed Description
Definition at line 115 of file instruction-selection-phase.h.
Member Function Documentation
Run()
void v8::internal::compiler::turboshaft::ProfileApplicationPhase::Run (PipelineData * data, Zone * temp_zone, const ProfileDataFromFile * profile)
Definition at line 298 of file instruction-selection-phase.cc.
                                                                      {
  Graph& graph = data->graph();
  for (auto& op : graph.AllOperations()) {
    if (BranchOp* branch = op.TryCast<BranchOp>()) {
      uint32_t true_block_id = branch->if_true->index().id();
      uint32_t false_block_id = branch->if_false->index().id();
      BranchHint hint = profile->GetHint(true_block_id, false_block_id);
      if (hint != BranchHint::kNone) {
        // We update the hint in-place.
        branch->hint = hint;
      }
    }
  }
}
References v8::internal::ProfileDataFromFile::GetHint(), v8::internal::compiler::turboshaft::PipelineData::graph(), graph(), v8::internal::kNone, and v8::internal::compiler::turboshaft::Operation::TryCast().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/instruction-selection-phase.h
/mnt/V8SourceCode/src/compiler/turboshaft/instruction-selection-phase.cc