v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::ElidedStringPart Struct Reference
#include <string-escape-analysis-reducer.h>
Public Types
enum class Kind : uint8_t { kNotElided
, kElided
 }
Public Member Functions
bool is_elided () const
V< String > og_index () const
V< String > ig_index () const
bool operator== (const ElidedStringPart &other) const
Static Public Member Functions
static ElidedStringPart Elided (V< String > ig_index)
static ElidedStringPart NotElided (V< String > og_index)
static ElidedStringPart Invalid ()
Public Attributes
xx xx xx xx xx xx xx xx xx
union {
 V< String > og_index
 V< String > ig_index
} data
Kind kind
Private Member Functions
ElidedStringPart (Kind kind, V< String > index)
Detailed Description
template<class Next>
struct v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::ElidedStringPart
Definition at line 112 of file string-escape-analysis-reducer.h.
Member Enumeration Documentation
Kind
template<class Next >
enum v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer::ElidedStringPart::Kind : uint8_t [strong]
Enumerator
kNotElided
kElided
Definition at line 113 of file string-escape-analysis-reducer.h.
: uint8_t { kNotElided, kElided };
Constructor & Destructor Documentation
ElidedStringPart()
template<class Next >
v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::ElidedStringPart::ElidedStringPart (Kind kind, V< String > index) [inline], [private]
Definition at line 154 of file string-escape-analysis-reducer.h.
: data(index), kind(kind) {}
Member Function Documentation
Elided()
template<class Next >
static ElidedStringPart v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::ElidedStringPart::Elided (V< String > ig_index) [inline], [static]
Definition at line 121 of file string-escape-analysis-reducer.h.
                                                       {
      return ElidedStringPart(Kind::kElided, ig_index);
    }
Referenced by v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::BuildFrameStateInput(), and v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::GetElidedStringInput().
ig_index()
template<class Next >
V<String> v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::ElidedStringPart::ig_index () const [inline]
Definition at line 134 of file string-escape-analysis-reducer.h.
                               {
      DCHECK_EQ(kind, Kind::kElided);
      return data.ig_index;
    }
References DCHECK_EQ.
Invalid()
template<class Next >
static ElidedStringPart v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::ElidedStringPart::Invalid () [inline], [static]
Definition at line 149 of file string-escape-analysis-reducer.h.
                                      {
      return ElidedStringPart(Kind::kNotElided, V<String>::Invalid());
    }
is_elided()
template<class Next >
bool v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::ElidedStringPart::is_elided () const [inline]
Definition at line 128 of file string-escape-analysis-reducer.h.
{ return kind == Kind::kElided; }
Referenced by v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::BuildMaybeElidedString().
NotElided()
template<class Next >
static ElidedStringPart v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::ElidedStringPart::NotElided (V< String > og_index) [inline], [static]
Definition at line 124 of file string-escape-analysis-reducer.h.
                                                          {
      return ElidedStringPart(Kind::kNotElided, og_index);
    }
Referenced by v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::GetElidedStringInput().
og_index()
template<class Next >
V<String> v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::ElidedStringPart::og_index () const [inline]
Definition at line 130 of file string-escape-analysis-reducer.h.
                               {
      DCHECK_EQ(kind, Kind::kNotElided);
      return data.og_index;
    }
References DCHECK_EQ.
operator==()
template<class Next >
bool v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::ElidedStringPart::operator== (const ElidedStringPart & other) const [inline]
Definition at line 139 of file string-escape-analysis-reducer.h.
                                                         {
      if (kind != other.kind) return false;
      switch (kind) {
        case Kind::kElided:
          return ig_index() == other.ig_index();
        case Kind::kNotElided:
          return og_index() == other.og_index();
      }
    }
References v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::ElidedStringPart::ig_index, v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::ElidedStringPart::kind, and v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::ElidedStringPart::og_index.
Member Data Documentation
union { ... } v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::ElidedStringPart::data
ig_index
template<class Next >
V<String> v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::ElidedStringPart::ig_index
Definition at line 116 of file string-escape-analysis-reducer.h.
Referenced by v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::BuildMaybeElidedString(), and v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::ElidedStringPart::operator==().
kind
template<class Next >
Kind v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::ElidedStringPart::kind
Definition at line 119 of file string-escape-analysis-reducer.h.
Referenced by v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::ElidedStringPart::operator==().
og_index
template<class Next >
V<String> v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::ElidedStringPart::og_index
Definition at line 115 of file string-escape-analysis-reducer.h.
Referenced by v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::BuildMaybeElidedString(), and v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::ElidedStringPart::operator==().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/string-escape-analysis-reducer.h