v8::internal::baseline::detail::PushAllHelper< Arg, interpreter::RegisterList > Struct Template Reference
#include <baseline-assembler-arm64-inl.h>
Static Public Member Functions
static void Push (BaselineAssembler *basm, Arg arg, interpreter::RegisterList list)
static void PushReverse (BaselineAssembler *basm, Arg arg, interpreter::RegisterList list)
Detailed Description
template<typename Arg>
struct v8::internal::baseline::detail::PushAllHelper< Arg, interpreter::RegisterList >
Definition at line 315 of file baseline-assembler-arm64-inl.h.
Member Function Documentation
Push()
template<typename Arg >
static void v8::internal::baseline::detail::PushAllHelper< Arg, interpreter::RegisterList >::Push (BaselineAssembler * basm, Arg arg, interpreter::RegisterList list) [inline], [static]
Definition at line 316 of file baseline-assembler-arm64-inl.h.
                                                 {
    DCHECK_EQ(list.register_count() % 2, 1);
    PushAll(basm, arg, list[0], list.PopLeft());
  }
References DCHECK_EQ, v8::internal::interpreter::RegisterList::PopLeft(), v8::internal::baseline::detail::PushAll(), and v8::internal::interpreter::RegisterList::register_count().
PushReverse()
template<typename Arg >
static void v8::internal::baseline::detail::PushAllHelper< Arg, interpreter::RegisterList >::PushReverse (BaselineAssembler * basm, Arg arg, interpreter::RegisterList list) [inline], [static]
Definition at line 321 of file baseline-assembler-arm64-inl.h.
                                                        {
    if (list.register_count() == 0) {
      PushAllReverse(basm, arg);
    } else {
      PushAllReverse(basm, arg, list[0], list.PopLeft());
    }
  }
References v8::internal::interpreter::RegisterList::PopLeft(), v8::internal::baseline::detail::PushAllReverse(), and v8::internal::interpreter::RegisterList::register_count().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/baseline/arm64/baseline-assembler-arm64-inl.h