v8::internal::interpreter::ConstantArrayBuilder::ConstantArraySlice Struct Reference
Public Member Functions
ConstantArraySlice (Zone *zone, size_t start_index, size_t capacity, OperandSize operand_size)
ConstantArraySlice (const ConstantArraySlice &)=delete
ConstantArraySlice & operator= (const ConstantArraySlice &)=delete
void Reserve ()
void Unreserve ()
size_t Allocate (Entry entry, size_t count=1)
Entry & At (size_t index)
const Entry & At (size_t index) const
size_t available () const
size_t reserved () const
size_t capacity () const
size_t size () const
size_t start_index () const
size_t max_index () const
OperandSize operand_size () const
Private Attributes
const size_t start_index_
const size_t capacity_
size_t reserved_
OperandSize operand_size_
ZoneVector< Entry > constants_
Detailed Description
Definition at line 202 of file constant-array-builder.h.
Constructor & Destructor Documentation
ConstantArraySlice() [1/2]
v8::internal::interpreter::ConstantArrayBuilder::ConstantArraySlice::ConstantArraySlice (Zone * zone, size_t start_index, size_t capacity, OperandSize operand_size)
Definition at line 24 of file constant-array-builder.cc.
    : start_index_(start_index),
      capacity_(capacity),
      reserved_(0),
      operand_size_(operand_size),
      constants_(zone) {}
ConstantArraySlice() [2/2]
v8::internal::interpreter::ConstantArrayBuilder::ConstantArraySlice::ConstantArraySlice (const ConstantArraySlice &) [delete]
Member Function Documentation
Allocate()
size_t v8::internal::interpreter::ConstantArrayBuilder::ConstantArraySlice::Allocate (ConstantArrayBuilder::Entry entry, size_t count = 1)
Definition at line 43 of file constant-array-builder.cc.
                                                   {
  DCHECK_GE(available(), count);
  size_t index = constants_.size();
  DCHECK_LT(index, capacity());
  for (size_t i = 0; i < count; ++i) {
    constants_.push_back(entry);
  }
  return index + start_index();
}
References available(), DCHECK_GE, DCHECK_LT, v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::index.
Referenced by v8::internal::interpreter::ConstantArrayBuilder::AllocateIndexArray().
At() [1/2]
ConstantArrayBuilder::Entry & v8::internal::interpreter::ConstantArrayBuilder::ConstantArraySlice::At (size_t index)
Definition at line 54 of file constant-array-builder.cc.
                  {
  DCHECK_GE(index, start_index());
  DCHECK_LT(index, start_index() + size());
  return constants_[index - start_index()];
}
References DCHECK_GE, DCHECK_LT, v8::internal::index, and v8::internal::interpreter::ConstantArrayBuilder::size().
Referenced by v8::internal::interpreter::ConstantArrayBuilder::At(), v8::internal::interpreter::ConstantArrayBuilder::SetDeferredAt(), and v8::internal::interpreter::ConstantArrayBuilder::SetJumpTableSmi().
At() [2/2]
const ConstantArrayBuilder::Entry & v8::internal::interpreter::ConstantArrayBuilder::ConstantArraySlice::At (size_t index) const
Definition at line 61 of file constant-array-builder.cc.
                        {
  DCHECK_GE(index, start_index());
  DCHECK_LT(index, start_index() + size());
  return constants_[index - start_index()];
}
References DCHECK_GE, DCHECK_LT, v8::internal::index, and v8::internal::interpreter::ConstantArrayBuilder::size().
available()
size_t v8::internal::interpreter::ConstantArrayBuilder::ConstantArraySlice::available () const [inline]
Definition at line 219 of file constant-array-builder.h.
{ return capacity() - reserved() - size(); }
References size().
capacity()
size_t v8::internal::interpreter::ConstantArrayBuilder::ConstantArraySlice::capacity () const [inline]
Definition at line 221 of file constant-array-builder.h.
{ return capacity_; }
Referenced by v8::internal::interpreter::ConstantArrayBuilder::At().
max_index()
size_t v8::internal::interpreter::ConstantArrayBuilder::ConstantArraySlice::max_index () const [inline]
Definition at line 224 of file constant-array-builder.h.
{ return start_index_ + capacity() - 1; }
Referenced by v8::internal::interpreter::ConstantArrayBuilder::CommitReservedEntry().
operand_size()
OperandSize v8::internal::interpreter::ConstantArrayBuilder::ConstantArraySlice::operand_size () const [inline]
Definition at line 225 of file constant-array-builder.h.
{ return operand_size_; }
Referenced by v8::internal::interpreter::ConstantArrayBuilder::CreateReservedEntry(), and v8::internal::interpreter::ConstantArrayBuilder::OperandSizeToSlice().
operator=()
ConstantArraySlice& v8::internal::interpreter::ConstantArrayBuilder::ConstantArraySlice::operator= (const ConstantArraySlice &) [delete]
Reserve()
void v8::internal::interpreter::ConstantArrayBuilder::ConstantArraySlice::Reserve ()
Definition at line 32 of file constant-array-builder.cc.
                                                     {
  DCHECK_GT(available(), 0u);
  reserved_++;
  DCHECK_LE(reserved_, capacity() - constants_.size());
}
References available(), DCHECK_GT, and DCHECK_LE.
Referenced by v8::internal::interpreter::ConstantArrayBuilder::CreateReservedEntry().
reserved()
size_t v8::internal::interpreter::ConstantArrayBuilder::ConstantArraySlice::reserved () const [inline]
Definition at line 220 of file constant-array-builder.h.
{ return reserved_; }
size()
size_t v8::internal::interpreter::ConstantArrayBuilder::ConstantArraySlice::size () const [inline]
Definition at line 222 of file constant-array-builder.h.
{ return constants_.size(); }
Referenced by v8::internal::interpreter::ConstantArrayBuilder::At(), and v8::internal::interpreter::ConstantArrayBuilder::size().
start_index()
size_t v8::internal::interpreter::ConstantArrayBuilder::ConstantArraySlice::start_index () const [inline]
Definition at line 223 of file constant-array-builder.h.
{ return start_index_; }
Referenced by v8::internal::interpreter::ConstantArrayBuilder::size().
Unreserve()
void v8::internal::interpreter::ConstantArrayBuilder::ConstantArraySlice::Unreserve ()
Definition at line 38 of file constant-array-builder.cc.
                                                       {
  DCHECK_GT(reserved_, 0u);
  reserved_--;
}
References DCHECK_GT.
Referenced by v8::internal::interpreter::ConstantArrayBuilder::DiscardReservedEntry().
Member Data Documentation
capacity_
const size_t v8::internal::interpreter::ConstantArrayBuilder::ConstantArraySlice::capacity_ [private]
Definition at line 229 of file constant-array-builder.h.
constants_
ZoneVector<Entry> v8::internal::interpreter::ConstantArrayBuilder::ConstantArraySlice::constants_ [private]
Definition at line 232 of file constant-array-builder.h.
operand_size_
OperandSize v8::internal::interpreter::ConstantArrayBuilder::ConstantArraySlice::operand_size_ [private]
Definition at line 231 of file constant-array-builder.h.
reserved_
size_t v8::internal::interpreter::ConstantArrayBuilder::ConstantArraySlice::reserved_ [private]
Definition at line 230 of file constant-array-builder.h.
start_index_
const size_t v8::internal::interpreter::ConstantArrayBuilder::ConstantArraySlice::start_index_ [private]
Definition at line 228 of file constant-array-builder.h.
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/interpreter/constant-array-builder.h
/mnt/V8SourceCode/src/interpreter/constant-array-builder.cc