v8::internal::maglev::NodeBase::OwnerOrTemporaries Struct Reference
Classes
struct Regs
union Store
Public Member Functions
BasicBlock * owner () const
template<typename RegisterT >
RegListBase< RegisterT > & temporaries ()
BasicBlock * operator= (BasicBlock *owner)
void InitReglist ()
Private Attributes
Store store_
Detailed Description
Definition at line 2488 of file maglev-ir.h.
Member Function Documentation
InitReglist()
void v8::internal::maglev::NodeBase::OwnerOrTemporaries::InitReglist () [inline]
Definition at line 2512 of file maglev-ir.h.
                       {
#ifdef DEBUG
      DCHECK(state_ == State::kNull || state_ == State::kOwner);
      state_ = State::kReglist;
#endif
      store_.regs_.temporaries_ = RegList();
      store_.regs_.double_temporaries_ = DoubleRegList();
    }
References v8::internal::DCHECK(), v8::internal::maglev::NodeBase::OwnerOrTemporaries::Regs::double_temporaries_, v8::internal::maglev::NodeBase::OwnerOrTemporaries::Store::regs_, store_, and v8::internal::maglev::NodeBase::OwnerOrTemporaries::Regs::temporaries_.
Referenced by v8::internal::maglev::NodeBase::InitTemporaries().
operator=()
BasicBlock* v8::internal::maglev::NodeBase::OwnerOrTemporaries::operator= (BasicBlock * owner) [inline]
Definition at line 2504 of file maglev-ir.h.
                                             {
#ifdef DEBUG
      DCHECK(state_ == State::kNull || state_ == State::kOwner);
      state_ = State::kOwner;
#endif
      return store_.owner_ = owner;
    }
References v8::internal::DCHECK(), owner(), v8::internal::maglev::NodeBase::OwnerOrTemporaries::Store::owner_, and store_.
owner()
BasicBlock* v8::internal::maglev::NodeBase::OwnerOrTemporaries::owner () const [inline]
Definition at line 2489 of file maglev-ir.h.
                              {
      DCHECK_EQ(state_, State::kOwner);
      return store_.owner_;
    }
References DCHECK_EQ, v8::internal::maglev::NodeBase::OwnerOrTemporaries::Store::owner_, and store_.
Referenced by operator=(), and v8::internal::maglev::NodeBase::owner().
temporaries()
template<typename RegisterT >
RegListBase<RegisterT>& v8::internal::maglev::NodeBase::OwnerOrTemporaries::temporaries () [inline]
Definition at line 2495 of file maglev-ir.h.
                                          {
      DCHECK_EQ(state_, State::kReglist);
      if constexpr (std::is_same_v<RegisterT, Register>) {
        return store_.regs_.temporaries_;
      } else {
        return store_.regs_.double_temporaries_;
      }
    }
References DCHECK_EQ, v8::internal::maglev::NodeBase::OwnerOrTemporaries::Regs::double_temporaries_, v8::internal::maglev::NodeBase::OwnerOrTemporaries::Store::regs_, store_, and v8::internal::maglev::NodeBase::OwnerOrTemporaries::Regs::temporaries_.
Referenced by v8::internal::maglev::NodeBase::assign_temporaries(), and v8::internal::maglev::NodeBase::temporaries().
Member Data Documentation
store_
Store v8::internal::maglev::NodeBase::OwnerOrTemporaries::store_ [private]
Definition at line 2531 of file maglev-ir.h.
Referenced by InitReglist(), operator=(), owner(), and temporaries().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-ir.h