v8::internal::AccessorAssembler::LoadICParameters Struct Reference
#include <accessor-assembler.h>
Public Member Functions
LoadICParameters (TNode< Context > context, TNode< JSAny > receiver, TNode< Object > name, TNode< TaggedIndex > slot, TNode< HeapObject > vector, std::optional< TNode< JSAny >> lookup_start_object=std::nullopt, std::optional< TNode< Smi >> enum_index=std::nullopt, std::optional< TNode< Object >> cache_type=std::nullopt)
LoadICParameters (const LoadICParameters *p, TNode< Object > unique_name)
TNode< Context > context () const
TNode< JSAny > receiver () const
TNode< Object > name () const
TNode< TaggedIndex > slot () const
TNode< HeapObject > vector () const
TNode< JSAny > lookup_start_object () const
TNode< Smi > enum_index () const
TNode< Object > cache_type () const
TNode< JSAny > receiver_and_lookup_start_object () const
bool IsEnumeratedKeyedLoad () const
Private Attributes
TNode< Context > context_
TNode< JSAny > receiver_
TNode< Object > name_
TNode< TaggedIndex > slot_
TNode< HeapObject > vector_
std::optional< TNode< JSAny > > lookup_start_object_
std::optional< TNode< Smi > > enum_index_
std::optional< TNode< Object > > cache_type_
Detailed Description
Definition at line 111 of file accessor-assembler.h.
Constructor & Destructor Documentation
LoadICParameters() [1/2]
v8::internal::AccessorAssembler::LoadICParameters::LoadICParameters (TNode< Context > context, TNode< JSAny > receiver, TNode< Object > name, TNode< TaggedIndex > slot, TNode< HeapObject > vector, std::optional< TNode< JSAny >> lookup_start_object = std::nullopt, std::optional< TNode< Smi >> enum_index = std::nullopt, std::optional< TNode< Object >> cache_type = std::nullopt) [inline]
Definition at line 112 of file accessor-assembler.h.
        : context_(context),
          receiver_(receiver),
          name_(name),
          slot_(slot),
          vector_(vector),
          lookup_start_object_(lookup_start_object ? lookup_start_object.value()
                                                   : receiver),
          enum_index_(enum_index),
          cache_type_(cache_type) {}
LoadICParameters() [2/2]
v8::internal::AccessorAssembler::LoadICParameters::LoadICParameters (const LoadICParameters * p, TNode< Object > unique_name) [inline]
Definition at line 128 of file accessor-assembler.h.
        : context_(p->context_),
          receiver_(p->receiver_),
          name_(unique_name),
          slot_(p->slot_),
          vector_(p->vector_),
          lookup_start_object_(p->lookup_start_object_) {}
Member Function Documentation
cache_type()
TNode<Object> v8::internal::AccessorAssembler::LoadICParameters::cache_type () const [inline]
Definition at line 145 of file accessor-assembler.h.
{ return *cache_type_; }
Referenced by v8::internal::AccessorAssembler::TryEnumeratedKeyedLoad().
context()
TNode<Context> v8::internal::AccessorAssembler::LoadICParameters::context () const [inline]
Definition at line 136 of file accessor-assembler.h.
{ return context_; }
Referenced by v8::internal::AccessorAssembler::GenericPropertyLoad(), v8::internal::AccessorAssembler::KeyedLoadIC(), v8::internal::AccessorAssembler::KeyedLoadICGeneric(), v8::internal::AccessorAssembler::KeyedLoadICPolymorphicName(), v8::internal::AccessorAssembler::LazyLoadICParameters::LazyLoadICParameters(), v8::internal::AccessorAssembler::LoadIC(), v8::internal::AccessorAssembler::LoadIC_NoFeedback(), v8::internal::AccessorAssembler::LoadSuperIC(), and v8::internal::AccessorAssembler::LoadSuperIC_NoFeedback().
enum_index()
TNode<Smi> v8::internal::AccessorAssembler::LoadICParameters::enum_index () const [inline]
Definition at line 144 of file accessor-assembler.h.
{ return *enum_index_; }
Referenced by v8::internal::AccessorAssembler::TryEnumeratedKeyedLoad().
IsEnumeratedKeyedLoad()
bool v8::internal::AccessorAssembler::LoadICParameters::IsEnumeratedKeyedLoad () const [inline]
Definition at line 155 of file accessor-assembler.h.
{ return enum_index_ != std::nullopt; }
Referenced by v8::internal::AccessorAssembler::TryEnumeratedKeyedLoad().
lookup_start_object()
TNode<JSAny> v8::internal::AccessorAssembler::LoadICParameters::lookup_start_object () const [inline]
Definition at line 141 of file accessor-assembler.h.
                                             {
      return lookup_start_object_.value();
    }
Referenced by v8::internal::AccessorAssembler::GenerateLoadIC_Noninlined(), v8::internal::AccessorAssembler::GenericPropertyLoad(), v8::internal::AccessorAssembler::KeyedLoadICGeneric(), v8::internal::AccessorAssembler::KeyedLoadICPolymorphicName(), v8::internal::AccessorAssembler::LoadIC_Noninlined(), v8::internal::AccessorAssembler::LoadSuperIC(), and v8::internal::AccessorAssembler::LoadSuperIC_NoFeedback().
name()
TNode<Object> v8::internal::AccessorAssembler::LoadICParameters::name () const [inline]
Definition at line 138 of file accessor-assembler.h.
{ return name_; }
Referenced by v8::internal::AccessorAssembler::GenericPropertyLoad(), v8::internal::AccessorAssembler::KeyedLoadIC(), v8::internal::AccessorAssembler::KeyedLoadICGeneric(), v8::internal::AccessorAssembler::KeyedLoadICPolymorphicName(), v8::internal::AccessorAssembler::LazyLoadICParameters::LazyLoadICParameters(), v8::internal::AccessorAssembler::LoadIC(), v8::internal::AccessorAssembler::LoadIC_NoFeedback(), v8::internal::AccessorAssembler::LoadIC_Noninlined(), v8::internal::AccessorAssembler::LoadSuperIC(), v8::internal::AccessorAssembler::LoadSuperIC_NoFeedback(), and v8::internal::AccessorAssembler::TryEnumeratedKeyedLoad().
receiver()
TNode<JSAny> v8::internal::AccessorAssembler::LoadICParameters::receiver () const [inline]
Definition at line 137 of file accessor-assembler.h.
{ return receiver_; }
Referenced by v8::internal::AccessorAssembler::GenericPropertyLoad(), v8::internal::AccessorAssembler::KeyedLoadIC(), v8::internal::AccessorAssembler::LoadIC(), v8::internal::AccessorAssembler::LoadIC_NoFeedback(), v8::internal::AccessorAssembler::LoadSuperIC(), and v8::internal::AccessorAssembler::LoadSuperIC_NoFeedback().
receiver_and_lookup_start_object()
TNode<JSAny> v8::internal::AccessorAssembler::LoadICParameters::receiver_and_lookup_start_object () const [inline]
Definition at line 150 of file accessor-assembler.h.
                                                          {
      DCHECK_EQ(receiver_, lookup_start_object_);
      return receiver_;
    }
References DCHECK_EQ.
Referenced by v8::internal::AccessorAssembler::GenericPropertyLoad(), v8::internal::AccessorAssembler::KeyedLoadIC(), v8::internal::AccessorAssembler::KeyedLoadICGeneric(), v8::internal::AccessorAssembler::KeyedLoadICPolymorphicName(), v8::internal::AccessorAssembler::LoadIC(), v8::internal::AccessorAssembler::LoadIC_NoFeedback(), and v8::internal::AccessorAssembler::TryEnumeratedKeyedLoad().
slot()
TNode<TaggedIndex> v8::internal::AccessorAssembler::LoadICParameters::slot () const [inline]
Definition at line 139 of file accessor-assembler.h.
{ return slot_; }
Referenced by v8::internal::AccessorAssembler::GenericPropertyLoad(), v8::internal::AccessorAssembler::KeyedLoadIC(), v8::internal::AccessorAssembler::KeyedLoadICPolymorphicName(), v8::internal::AccessorAssembler::LazyLoadICParameters::LazyLoadICParameters(), v8::internal::AccessorAssembler::LoadIC(), v8::internal::AccessorAssembler::LoadIC_Noninlined(), and v8::internal::AccessorAssembler::LoadSuperIC().
vector()
TNode<HeapObject> v8::internal::AccessorAssembler::LoadICParameters::vector () const [inline]
Definition at line 140 of file accessor-assembler.h.
{ return vector_; }
Referenced by v8::internal::AccessorAssembler::GenericPropertyLoad(), v8::internal::AccessorAssembler::KeyedLoadIC(), v8::internal::AccessorAssembler::KeyedLoadICPolymorphicName(), v8::internal::AccessorAssembler::LoadIC(), v8::internal::AccessorAssembler::LoadIC_Noninlined(), and v8::internal::AccessorAssembler::LoadSuperIC().
Member Data Documentation
cache_type_
std::optional<TNode<Object> > v8::internal::AccessorAssembler::LoadICParameters::cache_type_ [private]
Definition at line 165 of file accessor-assembler.h.
context_
TNode<Context> v8::internal::AccessorAssembler::LoadICParameters::context_ [private]
Definition at line 158 of file accessor-assembler.h.
enum_index_
std::optional<TNode<Smi> > v8::internal::AccessorAssembler::LoadICParameters::enum_index_ [private]
Definition at line 164 of file accessor-assembler.h.
lookup_start_object_
std::optional<TNode<JSAny> > v8::internal::AccessorAssembler::LoadICParameters::lookup_start_object_ [private]
Definition at line 163 of file accessor-assembler.h.
name_
TNode<Object> v8::internal::AccessorAssembler::LoadICParameters::name_ [private]
Definition at line 160 of file accessor-assembler.h.
receiver_
TNode<JSAny> v8::internal::AccessorAssembler::LoadICParameters::receiver_ [private]
Definition at line 159 of file accessor-assembler.h.
slot_
TNode<TaggedIndex> v8::internal::AccessorAssembler::LoadICParameters::slot_ [private]
Definition at line 161 of file accessor-assembler.h.
vector_
TNode<HeapObject> v8::internal::AccessorAssembler::LoadICParameters::vector_ [private]
Definition at line 162 of file accessor-assembler.h.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/ic/accessor-assembler.h