v8::internal::compiler::FeedbackSource Struct Reference
#include <feedback-source.h>
Classes
struct Equal
struct Hash
Public Member Functions
FeedbackSource ()
V8_EXPORT_PRIVATE FeedbackSource (IndirectHandle< FeedbackVector > vector_, FeedbackSlot slot_)
FeedbackSource (FeedbackVectorRef vector_, FeedbackSlot slot_)
bool IsValid () const
int index () const
Public Attributes
IndirectHandle< FeedbackVector > vector
FeedbackSlot slot
Detailed Description
Definition at line 15 of file feedback-source.h.
Constructor & Destructor Documentation
FeedbackSource() [1/3]
v8::internal::compiler::FeedbackSource::FeedbackSource () [inline]
Definition at line 16 of file feedback-source.h.
{ DCHECK(!IsValid()); }
References v8::internal::DCHECK(), and IsValid().
FeedbackSource() [2/3]
v8::internal::compiler::FeedbackSource::FeedbackSource (IndirectHandle< FeedbackVector > vector_, FeedbackSlot slot_)
Definition at line 11 of file feedback-source.cc.
    : vector(vector_), slot(slot_) {
  DCHECK(!slot.IsInvalid());
}
References v8::internal::DCHECK(), v8::internal::FeedbackSlot::IsInvalid(), and slot.
FeedbackSource() [3/3]
v8::internal::compiler::FeedbackSource::FeedbackSource (FeedbackVectorRef vector_, FeedbackSlot slot_)
Definition at line 17 of file feedback-source.cc.
    : FeedbackSource(vector_.object(), slot_) {}
Member Function Documentation
index()
int v8::internal::compiler::FeedbackSource::index () const
Definition at line 20 of file feedback-source.cc.
                                {
  CHECK(IsValid());
  return FeedbackVector::GetIndex(slot);
}
References CHECK, v8::internal::FeedbackVector::GetIndex(), IsValid(), and slot.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildBeginDeopt(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
IsValid()
bool v8::internal::compiler::FeedbackSource::IsValid () const [inline]
Definition at line 21 of file feedback-source.h.
{ return !vector.is_null() && !slot.IsInvalid(); }
References v8::internal::FeedbackSlot::IsInvalid(), slot, and vector.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildBeginDeopt(), v8::internal::compiler::CodeGenerator::BuildTranslation(), v8::internal::compiler::CallParameters::CallParameters(), v8::internal::compiler::JSOperatorBuilder::CallWithSpread(), v8::internal::compiler::Verifier::Visitor::Check(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckBounds(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedFloat64ToAdditiveSafeInteger(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedFloat64ToInt32(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedFloat64ToInt64(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedTaggedToAdditiveSafeInteger(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedTaggedToFloat64(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedTaggedToInt32(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedTaggedToInt64(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedTruncateTaggedToWord32(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckFloat64Hole(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckIf(), FeedbackSource(), v8::internal::compiler::JSHeapBroker::GetFeedback(), v8::internal::maglev::MaglevGraphBuilder::SaveCallSpeculationScope::GetSpeculationMode(), v8::internal::compiler::JSHeapBroker::HasFeedback(), index(), v8::internal::compiler::MapInference::InsertMapChecks(), v8::internal::compiler::SimplifiedOperatorBuilder::MaybeGrowFastElements(), v8::internal::compiler::operator<<(), v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewByteLengthAccessor(), v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpread(), v8::internal::compiler::JSCallReducer::ReduceJSCall(), v8::internal::compiler::JSCallReducer::ReduceJSConstruct(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateArray(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSDefineKeyedOwnProperty(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSDefineKeyedOwnPropertyInLiteral(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSDefineNamedOwnProperty(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSHasProperty(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSInstanceOf(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadGlobal(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadNamed(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadNamedFromSuper(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadProperty(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSSetKeyedProperty(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSSetNamedProperty(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSStoreGlobal(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSStoreInArrayLiteral(), v8::internal::compiler::MapInference::RelyOnMapsHelper(), v8::internal::compiler::JSHeapBroker::SetFeedback(), v8::internal::compiler::SimplifiedOperatorBuilder::SpeculativeToBigInt(), v8::internal::compiler::SimplifiedOperatorBuilder::SpeculativeToNumber(), v8::internal::maglev::MaglevGraphBuilder::TryBuildFastInstanceOfWithFeedback(), v8::internal::maglev::MaglevGraphBuilder::TryBuildInlineCall(), and v8::internal::compiler::JSCallReducer::TryReduceJSCallMathMinMaxWithArrayLike().
Member Data Documentation
slot
FeedbackSlot v8::internal::compiler::FeedbackSource::slot
Definition at line 25 of file feedback-source.h.
Referenced by v8::internal::compiler::BytecodeGraphBuilder::BuildNamedStore(), v8::internal::compiler::CodeGenerator::BuildTranslation(), v8::internal::compiler::JSHeapBroker::FeedbackIsInsufficient(), FeedbackSource(), v8::internal::compiler::JSHeapBroker::GetFeedbackSlotKind(), index(), IsValid(), v8::internal::compiler::FeedbackSource::Equal::operator()(), v8::internal::compiler::FeedbackSource::Hash::operator()(), v8::internal::compiler::operator<<(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForArrayOrObjectLiteral(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForBinaryOperation(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForCall(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForCompareOperation(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForForIn(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForGlobalAccess(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForInstanceOf(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForPropertyAccess(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForRegExpLiteral(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForTemplateObject(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForTypeOf(), and v8::internal::compiler::JSNativeContextSpecialization::ReduceJSGetIterator().
vector
IndirectHandle<FeedbackVector> v8::internal::compiler::FeedbackSource::vector
Definition at line 24 of file feedback-source.h.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildBeginDeopt(), v8::internal::compiler::CodeGenerator::BuildTranslation(), v8::internal::compiler::JSHeapBroker::FeedbackIsInsufficient(), v8::internal::compiler::JSHeapBroker::GetFeedbackSlotKind(), IsValid(), v8::internal::compiler::FeedbackSource::Equal::operator()(), v8::internal::compiler::FeedbackSource::Hash::operator()(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForArrayOrObjectLiteral(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForBinaryOperation(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForCall(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForCompareOperation(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForForIn(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForGlobalAccess(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForInstanceOf(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForPropertyAccess(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForRegExpLiteral(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForTemplateObject(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForTypeOf(), and v8::internal::compiler::JSNativeContextSpecialization::ReduceJSGetIterator().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/compiler/feedback-source.h
/mnt/V8SourceCode/src/compiler/feedback-source.cc