v8::internal::compiler::turboshaft::CheckMapsOp Struct Reference
#include <operations.h>
Public Member Functions
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
V< HeapObject > heap_object () const
V< FrameState > frame_state () const
OptionalV< Map > map () const
CheckMapsOp (V< HeapObject > heap_object, V< FrameState > frame_state, OptionalV< Map > map, ZoneRefSet< Map > maps, CheckMapsFlags flags, const FeedbackSource &feedback)
void Validate (const Graph &graph) const
auto options () const
void PrintOptions (std::ostream &os) const
template<typename Fn , typename Mapper >
auto Explode (Fn fn, Mapper &mapper) const
Static Public Member Functions
static CheckMapsOp & New (Graph *graph, V< HeapObject > heap_object, V< FrameState > frame_state, OptionalV< Map > map, ZoneRefSet< Map > maps, CheckMapsFlags flags, const FeedbackSource &feedback)
Public Attributes
CheckMapsFlags flags
ZoneRefSet< Map > maps
FeedbackSource feedback
Static Public Attributes
static constexpr OpEffects effects
Additional Inherited Members
Detailed Description
Definition at line 6178 of file operations.h.
Constructor & Destructor Documentation
CheckMapsOp()
v8::internal::compiler::turboshaft::CheckMapsOp::CheckMapsOp (V< HeapObject > heap_object, V< FrameState > frame_state, OptionalV< Map > map, ZoneRefSet< Map > maps, CheckMapsFlags flags, const FeedbackSource & feedback) [inline]
Definition at line 6202 of file operations.h.
      : Base(2 + map.valid()),
        flags(flags),
        maps(std::move(maps)),
        feedback(feedback) {
    input(0) = heap_object;
    input(1) = frame_state;
    if (map.valid()) {
      input(2) = map.value();
    }
  }
References v8::internal::compiler::turboshaft::OptionalOpIndex::valid(), and v8::internal::compiler::turboshaft::OptionalV< T >::value().
Member Function Documentation
Explode()
template<typename Fn , typename Mapper >
auto v8::internal::compiler::turboshaft::CheckMapsOp::Explode (Fn fn, Mapper & mapper) const [inline]
Definition at line 6224 of file operations.h.
                                                      {
    return fn(mapper.Map(heap_object()), mapper.Map(frame_state()),
              mapper.Map(map()), maps, flags, feedback);
  }
References v8::internal::flags.
frame_state()
V<FrameState> v8::internal::compiler::turboshaft::CheckMapsOp::frame_state () const [inline]
Definition at line 6197 of file operations.h.
{ return Base::input<FrameState>(1); }
heap_object()
V<HeapObject> v8::internal::compiler::turboshaft::CheckMapsOp::heap_object () const [inline]
Definition at line 6196 of file operations.h.
{ return Base::input<HeapObject>(0); }
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::CheckMapsOp::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 6191 of file operations.h.
                                                              {
    return MaybeRepVector<MaybeRegisterRepresentation::Tagged()>();
  }
map()
OptionalV<Map> v8::internal::compiler::turboshaft::CheckMapsOp::map () const [inline]
Definition at line 6198 of file operations.h.
                             {
    return input_count > 2 ? input<Map>(2) : OptionalV<Map>::Nullopt();
  }
References v8::internal::compiler::turboshaft::detail::input_count(), and v8::internal::compiler::turboshaft::OptionalV< T >::Nullopt().
New()
static CheckMapsOp& v8::internal::compiler::turboshaft::CheckMapsOp::New (Graph * graph, V< HeapObject > heap_object, V< FrameState > frame_state, OptionalV< Map > map, ZoneRefSet< Map > maps, CheckMapsFlags flags, const FeedbackSource & feedback) [inline], [static]
Definition at line 6229 of file operations.h.
                                                          {
    return Base::New(graph, 2 + map.valid(), heap_object, frame_state, map,
                     maps, flags, feedback);
  }
References v8::internal::flags, graph(), v8::internal::anonymous_namespace{intl-objects.cc}::New(), and v8::internal::compiler::turboshaft::OptionalOpIndex::valid().
options()
auto v8::internal::compiler::turboshaft::CheckMapsOp::options () const [inline]
Definition at line 6220 of file operations.h.
{ return std::tuple{maps, flags, feedback}; }
References v8::internal::flags.
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::CheckMapsOp::outputs_rep () const [inline]
Definition at line 6189 of file operations.h.
{ return {}; }
PrintOptions()
void v8::internal::compiler::turboshaft::CheckMapsOp::PrintOptions (std::ostream & os) const
Definition at line 1569 of file operations.cc.
                                                   {
  os << "[";
  PrintMapSet(os, maps);
  os << ", " << flags << ", " << feedback << "]";
}
References feedback, flags, maps, and v8::internal::compiler::turboshaft::PrintMapSet().
Validate()
void v8::internal::compiler::turboshaft::CheckMapsOp::Validate (const Graph & graph) const [inline]
Definition at line 6216 of file operations.h.
                                          {
    DCHECK(Get(graph, frame_state()).Is<FrameStateOp>());
  }
References v8::internal::DCHECK(), v8::internal::compiler::turboshaft::Get(), and graph().
Member Data Documentation
effects
constexpr OpEffects v8::internal::compiler::turboshaft::CheckMapsOp::effects [static], [constexpr]
Initial value:
= OpEffects()
                                           .CanDependOnChecks()
                                           .CanDeopt()
                                           .CanReadHeapMemory()
                                           .CanWriteHeapMemory()
Definition at line 6184 of file operations.h.
feedback
FeedbackSource v8::internal::compiler::turboshaft::CheckMapsOp::feedback
Definition at line 6181 of file operations.h.
Referenced by PrintOptions().
flags
CheckMapsFlags v8::internal::compiler::turboshaft::CheckMapsOp::flags
Definition at line 6179 of file operations.h.
Referenced by PrintOptions().
maps
ZoneRefSet<Map> v8::internal::compiler::turboshaft::CheckMapsOp::maps
Definition at line 6180 of file operations.h.
Referenced by PrintOptions().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h
/mnt/V8SourceCode/src/compiler/turboshaft/operations.cc