v8::internal::torque::CallCsaMacroAndBranchInstruction Struct Reference
#include <instructions.h>
Public Member Functions
CallCsaMacroAndBranchInstruction (Macro *macro, std::vector< std::string > constexpr_arguments, std::optional< Block * > return_continuation, std::vector< Block * > label_blocks, std::optional< Block * > catch_block)
bool IsBlockTerminator () const override
void AppendSuccessorBlocks (std::vector< Block * > *block_list) const override
std::size_t GetLabelCount () const
std::size_t GetLabelValueDefinitionCount (std::size_t label) const
DefinitionLocation GetLabelValueDefinition (std::size_t label, std::size_t index) const
std::size_t GetValueDefinitionCount () const
DefinitionLocation GetValueDefinition (std::size_t index) const
std::optional< DefinitionLocation > GetExceptionObjectDefinition () const
Public Attributes
Macro * macro
std::vector< std::string > constexpr_arguments
std::optional< Block * > return_continuation
std::vector< Block * > label_blocks
std::optional< Block * > catch_block
Detailed Description
Definition at line 499 of file instructions.h.
Constructor & Destructor Documentation
CallCsaMacroAndBranchInstruction()
v8::internal::torque::CallCsaMacroAndBranchInstruction::CallCsaMacroAndBranchInstruction (Macro * macro, std::vector< std::string > constexpr_arguments, std::optional< Block * > return_continuation, std::vector< Block * > label_blocks, std::optional< Block * > catch_block) [inline]
Definition at line 501 of file instructions.h.
      : macro(macro),
        constexpr_arguments(constexpr_arguments),
        return_continuation(return_continuation),
        label_blocks(label_blocks),
        catch_block(catch_block) {}
Member Function Documentation
AppendSuccessorBlocks()
void v8::internal::torque::CallCsaMacroAndBranchInstruction::AppendSuccessorBlocks (std::vector< Block * > * block_list) const [inline], [override], [virtual]
Reimplemented from v8::internal::torque::InstructionBase.
Definition at line 512 of file instructions.h.
                                                                           {
    if (catch_block) block_list->push_back(*catch_block);
    if (return_continuation) block_list->push_back(*return_continuation);
    for (Block* block : label_blocks) block_list->push_back(block);
  }
References catch_block, label_blocks, and return_continuation.
GetExceptionObjectDefinition()
std::optional< DefinitionLocation > v8::internal::torque::CallCsaMacroAndBranchInstruction::GetExceptionObjectDefinition () const
Definition at line 395 of file instructions.cc.
                                                                     {
  if (!catch_block) return std::nullopt;
  return DefinitionLocation::Instruction(this, GetValueDefinitionCount());
}
References catch_block, GetValueDefinitionCount(), and v8::internal::torque::DefinitionLocation::Instruction().
GetLabelCount()
std::size_t v8::internal::torque::CallCsaMacroAndBranchInstruction::GetLabelCount () const
Definition at line 362 of file instructions.cc.
                                                                {
  return label_blocks.size();
}
References label_blocks.
Referenced by GetLabelValueDefinitionCount().
GetLabelValueDefinition()
DefinitionLocation v8::internal::torque::CallCsaMacroAndBranchInstruction::GetLabelValueDefinition (std::size_t label, std::size_t index) const
Definition at line 372 of file instructions.cc.
                                            {
  DCHECK_LT(index, GetLabelValueDefinitionCount(label));
  std::size_t offset = GetValueDefinitionCount() + (catch_block ? 1 : 0);
  for (std::size_t label_index = 0; label_index < label; ++label_index) {
    offset += GetLabelValueDefinitionCount(label_index);
  }
  return DefinitionLocation::Instruction(this, offset + index);
}
References catch_block, DCHECK_LT, GetLabelValueDefinitionCount(), GetValueDefinitionCount(), v8::internal::index, v8::internal::torque::DefinitionLocation::Instruction(), and v8::internal::size_t.
GetLabelValueDefinitionCount()
std::size_t v8::internal::torque::CallCsaMacroAndBranchInstruction::GetLabelValueDefinitionCount (std::size_t label) const
Definition at line 366 of file instructions.cc.
                           {
  DCHECK_LT(label, GetLabelCount());
  return LowerParameterTypes(macro->signature().labels[label].types).size();
}
References DCHECK_LT, GetLabelCount(), v8::internal::torque::Signature::labels, v8::internal::torque::LowerParameterTypes(), macro, and v8::internal::torque::Callable::signature().
Referenced by GetLabelValueDefinition().
GetValueDefinition()
DefinitionLocation v8::internal::torque::CallCsaMacroAndBranchInstruction::GetValueDefinition (std::size_t index) const
Definition at line 388 of file instructions.cc.
                           {
  DCHECK_LT(index, GetValueDefinitionCount());
  return DefinitionLocation::Instruction(this, index);
}
References DCHECK_LT, GetValueDefinitionCount(), v8::internal::index, and v8::internal::torque::DefinitionLocation::Instruction().
GetValueDefinitionCount()
std::size_t v8::internal::torque::CallCsaMacroAndBranchInstruction::GetValueDefinitionCount () const
Definition at line 382 of file instructions.cc.
                                                                          {
  if (macro->signature().return_type == TypeOracle::GetNeverType()) return 0;
  if (!return_continuation) return 0;
  return LowerType(macro->signature().return_type).size();
}
References v8::internal::torque::TypeOracle::GetNeverType(), v8::internal::torque::LowerType(), macro, return_continuation, v8::internal::torque::Signature::return_type, and v8::internal::torque::Callable::signature().
Referenced by GetExceptionObjectDefinition(), GetLabelValueDefinition(), and GetValueDefinition().
IsBlockTerminator()
bool v8::internal::torque::CallCsaMacroAndBranchInstruction::IsBlockTerminator () const [inline], [override], [virtual]
Reimplemented from v8::internal::torque::InstructionBase.
Definition at line 511 of file instructions.h.
{ return true; }
Member Data Documentation
catch_block
std::optional<Block*> v8::internal::torque::CallCsaMacroAndBranchInstruction::catch_block
Definition at line 530 of file instructions.h.
Referenced by AppendSuccessorBlocks(), GetExceptionObjectDefinition(), GetLabelValueDefinition(), and v8::internal::torque::operator<<().
constexpr_arguments
std::vector<std::string> v8::internal::torque::CallCsaMacroAndBranchInstruction::constexpr_arguments
Definition at line 527 of file instructions.h.
Referenced by v8::internal::torque::operator<<().
label_blocks
std::vector<Block*> v8::internal::torque::CallCsaMacroAndBranchInstruction::label_blocks
Definition at line 529 of file instructions.h.
Referenced by AppendSuccessorBlocks(), GetLabelCount(), and v8::internal::torque::operator<<().
macro
Macro* v8::internal::torque::CallCsaMacroAndBranchInstruction::macro
Definition at line 526 of file instructions.h.
Referenced by GetLabelValueDefinitionCount(), GetValueDefinitionCount(), and v8::internal::torque::operator<<().
return_continuation
std::optional<Block*> v8::internal::torque::CallCsaMacroAndBranchInstruction::return_continuation
Definition at line 528 of file instructions.h.
Referenced by AppendSuccessorBlocks(), GetValueDefinitionCount(), and v8::internal::torque::operator<<().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/torque/instructions.h
/mnt/V8SourceCode/src/torque/instructions.cc