v8::internal::compiler::ScaleMatcher< BinopMatcher, kMulOpcode, kShiftOpcode > Struct Template Reference
#include <node-matchers.h>
Public Member Functions
ScaleMatcher (Node *node, bool allow_power_of_two_plus_one=false)
bool matches () const
int scale () const
bool power_of_two_plus_one () const
Private Attributes
int scale_
bool power_of_two_plus_one_
Detailed Description
template<class BinopMatcher, IrOpcode::Value kMulOpcode, IrOpcode::Value kShiftOpcode>
struct v8::internal::compiler::ScaleMatcher< BinopMatcher, kMulOpcode, kShiftOpcode >
Definition at line 366 of file node-matchers.h.
Constructor & Destructor Documentation
ScaleMatcher()
template<class BinopMatcher , IrOpcode::Value kMulOpcode, IrOpcode::Value kShiftOpcode>
v8::internal::compiler::ScaleMatcher< BinopMatcher, kMulOpcode, kShiftOpcode >::ScaleMatcher (Node * node, bool allow_power_of_two_plus_one = false) [inline], [explicit]
Definition at line 367 of file node-matchers.h.
      : scale_(-1), power_of_two_plus_one_(false) {
    if (node->InputCount() < 2) return;
    BinopMatcher m(node);
    if (node->opcode() == kShiftOpcode) {
      if (m.right().HasResolvedValue()) {
        typename BinopMatcher::RightMatcher::ValueType value =
            m.right().ResolvedValue();
        if (value >= 0 && value <= 3) {
          scale_ = static_cast<int>(value);
        }
      }
    } else if (node->opcode() == kMulOpcode) {
      if (m.right().HasResolvedValue()) {
        typename BinopMatcher::RightMatcher::ValueType value =
            m.right().ResolvedValue();
        if (value == 1) {
          scale_ = 0;
        } else if (value == 2) {
          scale_ = 1;
        } else if (value == 4) {
          scale_ = 2;
        } else if (value == 8) {
          scale_ = 3;
        } else if (allow_power_of_two_plus_one) {
          if (value == 3) {
            scale_ = 1;
            power_of_two_plus_one_ = true;
          } else if (value == 5) {
            scale_ = 2;
            power_of_two_plus_one_ = true;
          } else if (value == 9) {
            scale_ = 3;
            power_of_two_plus_one_ = true;
          }
        }
      }
    }
  }
References v8::internal::compiler::Node::InputCount(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::ScaleMatcher< BinopMatcher, kMulOpcode, kShiftOpcode >::power_of_two_plus_one_, v8::internal::compiler::BinopMatcher< Left, Right, rep >::right(), v8::internal::compiler::ScaleMatcher< BinopMatcher, kMulOpcode, kShiftOpcode >::scale_, and v8::internal::value.
Member Function Documentation
matches()
template<class BinopMatcher , IrOpcode::Value kMulOpcode, IrOpcode::Value kShiftOpcode>
bool v8::internal::compiler::ScaleMatcher< BinopMatcher, kMulOpcode, kShiftOpcode >::matches () const [inline]
Definition at line 407 of file node-matchers.h.
{ return scale_ != -1; }
References v8::internal::compiler::ScaleMatcher< BinopMatcher, kMulOpcode, kShiftOpcode >::scale_.
Referenced by v8::internal::compiler::AddMatcher< BinopMatcher, AddOpcode, SubOpcode, kMulOpcode, kShiftOpcode >::Initialize().
power_of_two_plus_one()
template<class BinopMatcher , IrOpcode::Value kMulOpcode, IrOpcode::Value kShiftOpcode>
bool v8::internal::compiler::ScaleMatcher< BinopMatcher, kMulOpcode, kShiftOpcode >::power_of_two_plus_one () const [inline]
Definition at line 409 of file node-matchers.h.
{ return power_of_two_plus_one_; }
References v8::internal::compiler::ScaleMatcher< BinopMatcher, kMulOpcode, kShiftOpcode >::power_of_two_plus_one_.
Referenced by v8::internal::compiler::AddMatcher< BinopMatcher, AddOpcode, SubOpcode, kMulOpcode, kShiftOpcode >::Initialize().
scale()
template<class BinopMatcher , IrOpcode::Value kMulOpcode, IrOpcode::Value kShiftOpcode>
int v8::internal::compiler::ScaleMatcher< BinopMatcher, kMulOpcode, kShiftOpcode >::scale () const [inline]
Definition at line 408 of file node-matchers.h.
{ return scale_; }
References v8::internal::compiler::ScaleMatcher< BinopMatcher, kMulOpcode, kShiftOpcode >::scale_.
Referenced by v8::internal::compiler::AddMatcher< BinopMatcher, AddOpcode, SubOpcode, kMulOpcode, kShiftOpcode >::Initialize().
Member Data Documentation
power_of_two_plus_one_
template<class BinopMatcher , IrOpcode::Value kMulOpcode, IrOpcode::Value kShiftOpcode>
bool v8::internal::compiler::ScaleMatcher< BinopMatcher, kMulOpcode, kShiftOpcode >::power_of_two_plus_one_ [private]
Definition at line 413 of file node-matchers.h.
Referenced by v8::internal::compiler::ScaleMatcher< BinopMatcher, kMulOpcode, kShiftOpcode >::power_of_two_plus_one(), and v8::internal::compiler::ScaleMatcher< BinopMatcher, kMulOpcode, kShiftOpcode >::ScaleMatcher().
scale_
template<class BinopMatcher , IrOpcode::Value kMulOpcode, IrOpcode::Value kShiftOpcode>
int v8::internal::compiler::ScaleMatcher< BinopMatcher, kMulOpcode, kShiftOpcode >::scale_ [private]
Definition at line 412 of file node-matchers.h.
Referenced by v8::internal::compiler::ScaleMatcher< BinopMatcher, kMulOpcode, kShiftOpcode >::matches(), v8::internal::compiler::ScaleMatcher< BinopMatcher, kMulOpcode, kShiftOpcode >::scale(), and v8::internal::compiler::ScaleMatcher< BinopMatcher, kMulOpcode, kShiftOpcode >::ScaleMatcher().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/node-matchers.h