v8::internal::VariableProxy::UnresolvedNext Struct Reference
#include <ast.h>
Static Public Member Functions
static VariableProxy ** filter (VariableProxy **t)
static VariableProxy ** start (VariableProxy **head)
static VariableProxy ** next (VariableProxy *t)
Detailed Description
Definition at line 1573 of file ast.h.
Member Function Documentation
filter()
static VariableProxy** v8::internal::VariableProxy::UnresolvedNext::filter (VariableProxy ** t) [inline], [static]
Definition at line 1574 of file ast.h.
                                                     {
      VariableProxy** n = t;
      // Skip over possibly removed values.
      while (*n != nullptr && (*n)->is_removed_from_unresolved()) {
        n = (*n)->next();
      }
      return n;
    }
References v8::internal::VariableProxy::is_removed_from_unresolved(), and v8::internal::VariableProxy::next().
Referenced by next(), and start().
next()
static VariableProxy** v8::internal::VariableProxy::UnresolvedNext::next (VariableProxy * t) [inline], [static]
Definition at line 1585 of file ast.h.
{ return filter(t->next()); }
References filter(), and v8::internal::VariableProxy::next().
start()
static VariableProxy** v8::internal::VariableProxy::UnresolvedNext::start (VariableProxy ** head) [inline], [static]
Definition at line 1583 of file ast.h.
{ return filter(head); }
References filter().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/ast/ast.h