v8::internal::SerializerDeserializer::VariableRepeatRootCount Struct Reference
#include <serializer-deserializer.h>
Static Public Member Functions
static constexpr bool IsEncodable (int repeat_count)
static constexpr int Encode (int repeat_count)
static constexpr int Decode (int value)
Detailed Description
Definition at line 259 of file serializer-deserializer.h.
Member Function Documentation
Decode()
static constexpr int v8::internal::SerializerDeserializer::VariableRepeatRootCount::Decode (int value) [inline], [static], [constexpr]
Definition at line 269 of file serializer-deserializer.h.
                                           {
      return value + kFirstEncodableVariableRepeatRootCount;
    }
References v8::internal::SerializerDeserializer::kFirstEncodableVariableRepeatRootCount, and v8::internal::value.
Encode()
static constexpr int v8::internal::SerializerDeserializer::VariableRepeatRootCount::Encode (int repeat_count) [inline], [static], [constexpr]
Definition at line 264 of file serializer-deserializer.h.
                                                  {
      DCHECK(IsEncodable(repeat_count));
      return repeat_count - kFirstEncodableVariableRepeatRootCount;
    }
References v8::internal::DCHECK(), IsEncodable(), and v8::internal::SerializerDeserializer::kFirstEncodableVariableRepeatRootCount.
Referenced by v8::internal::Serializer::PutRepeatRoot().
IsEncodable()
static constexpr bool v8::internal::SerializerDeserializer::VariableRepeatRootCount::IsEncodable (int repeat_count) [inline], [static], [constexpr]
Definition at line 260 of file serializer-deserializer.h.
                                                        {
      return repeat_count >= kFirstEncodableVariableRepeatRootCount;
    }
References v8::internal::SerializerDeserializer::kFirstEncodableVariableRepeatRootCount.
Referenced by Encode().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/snapshot/serializer-deserializer.h