v8::internal::compiler::turboshaft::OverflowCheckedUnaryOp Struct Reference
#include <operations.h>
Public Types
enum class Kind : uint8_t { kAbs
 }
Public Member Functions
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
V< Word > input () const
OverflowCheckedUnaryOp (V< Word > input, Kind kind, WordRepresentation rep)
auto options () const
Public Attributes
Kind kind
WordRepresentation rep
Static Public Attributes
static constexpr int kValueIndex = 0
static constexpr int kOverflowIndex = 1
static constexpr OpEffects effects = OpEffects()
Additional Inherited Members
Detailed Description
Definition at line 1908 of file operations.h.
Member Enumeration Documentation
Kind
enum v8::internal::compiler::turboshaft::OverflowCheckedUnaryOp::Kind : uint8_t [strong]
Enumerator
kAbs
Definition at line 1913 of file operations.h.
: uint8_t { kAbs };
Constructor & Destructor Documentation
OverflowCheckedUnaryOp()
v8::internal::compiler::turboshaft::OverflowCheckedUnaryOp::OverflowCheckedUnaryOp (V< Word > input, Kind kind, WordRepresentation rep) [inline], [explicit]
Definition at line 1935 of file operations.h.
      : Base(input), kind(kind), rep(rep) {}
Member Function Documentation
input()
V<Word> v8::internal::compiler::turboshaft::OverflowCheckedUnaryOp::input () const [inline]
Definition at line 1933 of file operations.h.
{ return Base::input<Word>(0); }
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::OverflowCheckedUnaryOp::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 1928 of file operations.h.
                                                              {
    return InputsRepFactory::SingleRep(rep);
  }
References v8::internal::compiler::turboshaft::InputsRepFactory::SingleRep().
options()
auto v8::internal::compiler::turboshaft::OverflowCheckedUnaryOp::options () const [inline]
Definition at line 1939 of file operations.h.
{ return std::tuple{kind, rep}; }
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::OverflowCheckedUnaryOp::outputs_rep () const [inline]
Definition at line 1917 of file operations.h.
                                                               {
    switch (rep.value()) {
      case WordRepresentation::Word32():
        return RepVector<RegisterRepresentation::Word32(),
                         RegisterRepresentation::Word32()>();
      case WordRepresentation::Word64():
        return RepVector<RegisterRepresentation::Word64(),
                         RegisterRepresentation::Word32()>();
    }
  }
References v8::internal::compiler::turboshaft::RepVector(), v8::internal::compiler::turboshaft::WordRepresentation::value(), v8::internal::compiler::turboshaft::RegisterRepresentation::Word32(), v8::internal::compiler::turboshaft::WordRepresentation::Word32(), v8::internal::compiler::turboshaft::RegisterRepresentation::Word64(), and v8::internal::compiler::turboshaft::WordRepresentation::Word64().
Member Data Documentation
effects
constexpr OpEffects v8::internal::compiler::turboshaft::OverflowCheckedUnaryOp::effects = OpEffects() [static], [constexpr]
Definition at line 1916 of file operations.h.
kind
Kind v8::internal::compiler::turboshaft::OverflowCheckedUnaryOp::kind
Definition at line 1914 of file operations.h.
kOverflowIndex
constexpr int v8::internal::compiler::turboshaft::OverflowCheckedUnaryOp::kOverflowIndex = 1 [static], [constexpr]
Definition at line 1911 of file operations.h.
kValueIndex
constexpr int v8::internal::compiler::turboshaft::OverflowCheckedUnaryOp::kValueIndex = 0 [static], [constexpr]
Definition at line 1910 of file operations.h.
rep
WordRepresentation v8::internal::compiler::turboshaft::OverflowCheckedUnaryOp::rep
Definition at line 1915 of file operations.h.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h