v8::internal::compiler::ExtendingLoadMatcher Struct Reference
Public Member Functions
ExtendingLoadMatcher (OpIndex node, InstructionSelector *selector)
bool Matches () const
OpIndex base () const
int64_t immediate () const
ArchOpcode opcode () const
ExtendingLoadMatcher (OpIndex node, InstructionSelector *selector)
bool Matches () const
OpIndex base () const
int64_t immediate () const
ArchOpcode opcode () const
ExtendingLoadMatcher (OpIndex node, InstructionSelector *selector)
bool Matches () const
OpIndex base () const
int64_t immediate () const
ArchOpcode opcode () const
Private Member Functions
void Initialize (turboshaft::OpIndex node)
void Initialize (turboshaft::OpIndex node)
void Initialize (turboshaft::OpIndex node)
Private Attributes
bool matches_
InstructionSelector * selector_
OpIndex base_ {}
int64_t immediate_
ArchOpcode opcode_
Detailed Description
Definition at line 198 of file instruction-selector-loong64.cc.
Constructor & Destructor Documentation
ExtendingLoadMatcher() [1/3]
v8::internal::compiler::ExtendingLoadMatcher::ExtendingLoadMatcher (OpIndex node, InstructionSelector * selector) [inline]
Definition at line 199 of file instruction-selector-loong64.cc.
      : matches_(false), selector_(selector), immediate_(0) {
    Initialize(node);
  }
ExtendingLoadMatcher() [2/3]
v8::internal::compiler::ExtendingLoadMatcher::ExtendingLoadMatcher (OpIndex node, InstructionSelector * selector) [inline]
Definition at line 170 of file instruction-selector-mips64.cc.
      : matches_(false), selector_(selector), immediate_(0) {
    Initialize(node);
  }
ExtendingLoadMatcher() [3/3]
v8::internal::compiler::ExtendingLoadMatcher::ExtendingLoadMatcher (OpIndex node, InstructionSelector * selector) [inline]
Definition at line 62 of file instruction-selector-riscv64.cc.
      : matches_(false), selector_(selector), immediate_(0) {
    Initialize(node);
  }
References Initialize().
Member Function Documentation
base() [1/3]
OpIndex v8::internal::compiler::ExtendingLoadMatcher::base () const [inline]
Definition at line 206 of file instruction-selector-loong64.cc.
                       {
    DCHECK(Matches());
    return base_;
  }
References v8::internal::DCHECK(), and v8::internal::anonymous_namespace{json-parser.cc}::Matches().
Referenced by v8::internal::compiler::TryEmitExtendingLoad().
base() [2/3]
OpIndex v8::internal::compiler::ExtendingLoadMatcher::base () const [inline]
Definition at line 177 of file instruction-selector-mips64.cc.
                       {
    DCHECK(Matches());
    return base_;
  }
References v8::internal::DCHECK(), and v8::internal::anonymous_namespace{json-parser.cc}::Matches().
base() [3/3]
OpIndex v8::internal::compiler::ExtendingLoadMatcher::base () const [inline]
Definition at line 69 of file instruction-selector-riscv64.cc.
                       {
    DCHECK(Matches());
    return base_;
  }
References base_, v8::internal::DCHECK(), and Matches().
immediate() [1/3]
int64_t v8::internal::compiler::ExtendingLoadMatcher::immediate () const [inline]
Definition at line 210 of file instruction-selector-loong64.cc.
                            {
    DCHECK(Matches());
    return immediate_;
  }
References v8::internal::DCHECK(), and v8::internal::anonymous_namespace{json-parser.cc}::Matches().
Referenced by v8::internal::compiler::TryEmitExtendingLoad().
immediate() [2/3]
int64_t v8::internal::compiler::ExtendingLoadMatcher::immediate () const [inline]
Definition at line 181 of file instruction-selector-mips64.cc.
                            {
    DCHECK(Matches());
    return immediate_;
  }
References v8::internal::DCHECK(), and v8::internal::anonymous_namespace{json-parser.cc}::Matches().
immediate() [3/3]
int64_t v8::internal::compiler::ExtendingLoadMatcher::immediate () const [inline]
Definition at line 73 of file instruction-selector-riscv64.cc.
                            {
    DCHECK(Matches());
    return immediate_;
  }
References v8::internal::DCHECK(), immediate_, and Matches().
Initialize() [1/3]
void v8::internal::compiler::ExtendingLoadMatcher::Initialize (turboshaft::OpIndex node) [inline], [private]
Definition at line 226 of file instruction-selector-loong64.cc.
                                          {
    const ShiftOp& shift = selector_->Get(node).template Cast<ShiftOp>();
    DCHECK(shift.kind == ShiftOp::Kind::kShiftRightArithmetic ||
           shift.kind == ShiftOp::Kind::kShiftRightArithmeticShiftOutZeros);
    // When loading a 64-bit value and shifting by 32, we should
    // just load and sign-extend the interesting 4 bytes instead.
    // This happens, for example, when we're loading and untagging SMIs.
    const Operation& lhs = selector_->Get(shift.left());
    int64_t constant_rhs;
    if (lhs.Is<LoadOp>() &&
        selector_->MatchIntegralWord64Constant(shift.right(), &constant_rhs) &&
        constant_rhs == 32 && selector_->CanCover(node, shift.left())) {
      Loong64OperandGenerator g(selector_);
      const LoadOp& load = lhs.Cast<LoadOp>();
      base_ = load.base();
      opcode_ = kLoong64Ld_w;
      if (load.index().has_value()) {
        int64_t index_constant;
        if (selector_->MatchIntegralWord64Constant(load.index().value(),
                                                   &index_constant)) {
          DCHECK_EQ(load.element_size_log2, 0);
          immediate_ = index_constant + 4;
          matches_ = g.CanBeImmediate(immediate_, kLoong64Ld_w);
        }
      } else {
        immediate_ = load.offset + 4;
        matches_ = g.CanBeImmediate(immediate_, kLoong64Ld_w);
      }
    }
  }
References v8::internal::compiler::turboshaft::LoadOp::base(), v8::internal::compiler::Loong64OperandGenerator::CanBeImmediate(), v8::internal::compiler::InstructionSelector::CanCover(), v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::turboshaft::LoadOp::element_size_log2, v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::OptionalOpIndex::has_value(), v8::internal::compiler::turboshaft::LoadOp::index(), v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::compiler::turboshaft::ShiftOp::kind, v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralWord64Constant(), v8::internal::compiler::turboshaft::LoadOp::offset, v8::internal::compiler::turboshaft::ShiftOp::right(), and v8::internal::compiler::turboshaft::OptionalOpIndex::value().
Referenced by ExtendingLoadMatcher().
Initialize() [2/3]
void v8::internal::compiler::ExtendingLoadMatcher::Initialize (turboshaft::OpIndex node) [inline], [private]
Definition at line 197 of file instruction-selector-mips64.cc.
                                          {
    const ShiftOp& shift = selector_->Get(node).template Cast<ShiftOp>();
    DCHECK(shift.kind == ShiftOp::Kind::kShiftRightArithmetic ||
           shift.kind == ShiftOp::Kind::kShiftRightArithmeticShiftOutZeros);
    // When loading a 64-bit value and shifting by 32, we should
    // just load and sign-extend the interesting 4 bytes instead.
    // This happens, for example, when we're loading and untagging SMIs.
    const Operation& lhs = selector_->Get(shift.left());
    int64_t constant_rhs;
    if (lhs.Is<LoadOp>() &&
        selector_->MatchIntegralWord64Constant(shift.right(), &constant_rhs) &&
        constant_rhs == 32 && selector_->CanCover(node, shift.left())) {
      Mips64OperandGenerator g(selector_);
      const LoadOp& load = lhs.Cast<LoadOp>();
      base_ = load.base();
      opcode_ = kMips64Lw;
      if (load.index().has_value()) {
        int64_t index_constant;
        if (selector_->MatchIntegralWord64Constant(load.index().value(),
                                                   &index_constant)) {
          DCHECK_EQ(load.element_size_log2, 0);
          immediate_ = index_constant + 4;
          matches_ = g.CanBeImmediate(immediate_, kMips64Lw);
        }
      } else {
        immediate_ = load.offset + 4;
        matches_ = g.CanBeImmediate(immediate_, kMips64Lw);
      }
    }
  }
References v8::internal::compiler::turboshaft::LoadOp::base(), v8::internal::compiler::Mips64OperandGenerator::CanBeImmediate(), v8::internal::compiler::InstructionSelector::CanCover(), v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::turboshaft::LoadOp::element_size_log2, v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::OptionalOpIndex::has_value(), v8::internal::compiler::turboshaft::LoadOp::index(), v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::compiler::turboshaft::ShiftOp::kind, v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralWord64Constant(), v8::internal::compiler::turboshaft::LoadOp::offset, v8::internal::compiler::turboshaft::ShiftOp::right(), and v8::internal::compiler::turboshaft::OptionalOpIndex::value().
Initialize() [3/3]
void v8::internal::compiler::ExtendingLoadMatcher::Initialize (turboshaft::OpIndex node) [inline], [private]
Definition at line 89 of file instruction-selector-riscv64.cc.
                                          {
    const ShiftOp& shift = selector_->Get(node).template Cast<ShiftOp>();
    DCHECK(shift.kind == ShiftOp::Kind::kShiftRightArithmetic ||
           shift.kind == ShiftOp::Kind::kShiftRightArithmeticShiftOutZeros);
    // When loading a 64-bit value and shifting by 32, we should
    // just load and sign-extend the interesting 4 bytes instead.
    // This happens, for example, when we're loading and untagging SMIs.
    const Operation& lhs = selector_->Get(shift.left());
    int64_t constant_rhs;
    if (lhs.Is<LoadOp>() &&
        selector_->MatchIntegralWord64Constant(shift.right(), &constant_rhs) &&
        constant_rhs == 32 && selector_->CanCover(node, shift.left())) {
      RiscvOperandGenerator g(selector_);
      const LoadOp& load = lhs.Cast<LoadOp>();
      base_ = load.base();
      opcode_ = kRiscvLw;
      if (load.index().has_value()) {
        int64_t index_constant;
        if (selector_->MatchIntegralWord64Constant(load.index().value(),
                                                   &index_constant)) {
          DCHECK_EQ(load.element_size_log2, 0);
          immediate_ = index_constant + 4;
          matches_ = g.CanBeImmediate(immediate_, kRiscvLw);
        }
      } else {
        immediate_ = load.offset + 4;
        matches_ = g.CanBeImmediate(immediate_, kRiscvLw);
      }
    }
  }
References v8::internal::compiler::turboshaft::LoadOp::base(), base_, v8::internal::compiler::RiscvOperandGenerator::CanBeImmediate(), v8::internal::compiler::InstructionSelector::CanCover(), v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::turboshaft::LoadOp::element_size_log2, v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::OptionalOpIndex::has_value(), immediate_, v8::internal::compiler::turboshaft::LoadOp::index(), v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::compiler::turboshaft::ShiftOp::kind, matches_, v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralWord64Constant(), v8::internal::compiler::turboshaft::LoadOp::offset, opcode_, v8::internal::compiler::turboshaft::ShiftOp::right(), selector_, and v8::internal::compiler::turboshaft::OptionalOpIndex::value().
Matches() [1/3]
bool v8::internal::compiler::ExtendingLoadMatcher::Matches () const [inline]
Definition at line 204 of file instruction-selector-loong64.cc.
{ return matches_; }
Referenced by base(), immediate(), opcode(), and v8::internal::compiler::TryEmitExtendingLoad().
Matches() [2/3]
bool v8::internal::compiler::ExtendingLoadMatcher::Matches () const [inline]
Definition at line 175 of file instruction-selector-mips64.cc.
{ return matches_; }
Matches() [3/3]
bool v8::internal::compiler::ExtendingLoadMatcher::Matches () const [inline]
Definition at line 67 of file instruction-selector-riscv64.cc.
{ return matches_; }
References matches_.
opcode() [1/3]
ArchOpcode v8::internal::compiler::ExtendingLoadMatcher::opcode () const [inline]
Definition at line 214 of file instruction-selector-loong64.cc.
                            {
    DCHECK(Matches());
    return opcode_;
  }
References v8::internal::DCHECK(), and v8::internal::anonymous_namespace{json-parser.cc}::Matches().
Referenced by v8::internal::compiler::TryEmitExtendingLoad().
opcode() [2/3]
ArchOpcode v8::internal::compiler::ExtendingLoadMatcher::opcode () const [inline]
Definition at line 185 of file instruction-selector-mips64.cc.
                            {
    DCHECK(Matches());
    return opcode_;
  }
References v8::internal::DCHECK(), and v8::internal::anonymous_namespace{json-parser.cc}::Matches().
opcode() [3/3]
ArchOpcode v8::internal::compiler::ExtendingLoadMatcher::opcode () const [inline]
Definition at line 77 of file instruction-selector-riscv64.cc.
                            {
    DCHECK(Matches());
    return opcode_;
  }
References v8::internal::DCHECK(), Matches(), and opcode_.
Member Data Documentation
base_
OpIndex v8::internal::compiler::ExtendingLoadMatcher::base_ {} [private]
Definition at line 222 of file instruction-selector-loong64.cc.
Referenced by base(), and Initialize().
immediate_
int64_t v8::internal::compiler::ExtendingLoadMatcher::immediate_ [private]
Definition at line 223 of file instruction-selector-loong64.cc.
Referenced by immediate(), and Initialize().
matches_
bool v8::internal::compiler::ExtendingLoadMatcher::matches_ [private]
Definition at line 220 of file instruction-selector-loong64.cc.
Referenced by Initialize(), and Matches().
opcode_
ArchOpcode v8::internal::compiler::ExtendingLoadMatcher::opcode_ [private]
Definition at line 224 of file instruction-selector-loong64.cc.
Referenced by Initialize(), and opcode().
selector_
InstructionSelector * v8::internal::compiler::ExtendingLoadMatcher::selector_ [private]
Definition at line 221 of file instruction-selector-loong64.cc.
Referenced by Initialize().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/compiler/backend/loong64/instruction-selector-loong64.cc
/mnt/V8SourceCode/src/compiler/backend/mips64/instruction-selector-mips64.cc
/mnt/V8SourceCode/src/compiler/backend/riscv/instruction-selector-riscv64.cc