v8::internal::compiler::turboshaft::FloatBinopOp Struct Reference
#include <operations.h>
Public Types
enum class Kind : uint8_t {
kAdd
, kMul
, kMin
, kMax
,
kSub
, kDiv
, kMod
, kPower
,
kAtan2
 }
Public Member Functions
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
V< Float > left () const
V< Float > right () const
FloatBinopOp (V< Float > left, V< Float > right, Kind kind, FloatRepresentation rep)
void Validate (const Graph &graph) const
auto options () const
void PrintOptions (std::ostream &os) const
Static Public Member Functions
static bool IsCommutative (Kind kind)
Public Attributes
Kind kind
FloatRepresentation rep
Static Public Attributes
static constexpr OpEffects effects = OpEffects()
Additional Inherited Members
Detailed Description
Definition at line 1681 of file operations.h.
Member Enumeration Documentation
Kind
enum v8::internal::compiler::turboshaft::FloatBinopOp::Kind : uint8_t [strong]
Enumerator
kAdd
kMul
kMin
kMax
kSub
kDiv
kMod
kPower
kAtan2
Definition at line 1682 of file operations.h.
                  : uint8_t {
    kAdd,
    kMul,
    kMin,
    kMax,
    kSub,
    kDiv,
    kMod,
    kPower,
    kAtan2,
  };
Constructor & Destructor Documentation
FloatBinopOp()
v8::internal::compiler::turboshaft::FloatBinopOp::FloatBinopOp (V< Float > left, V< Float > right, Kind kind, FloatRepresentation rep) [inline]
Definition at line 1725 of file operations.h.
      : Base(left, right), kind(kind), rep(rep) {}
Member Function Documentation
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::FloatBinopOp::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 1701 of file operations.h.
                                                              {
    return InputsRepFactory::PairOf(rep);
  }
References v8::internal::compiler::turboshaft::InputsRepFactory::PairOf().
IsCommutative()
static bool v8::internal::compiler::turboshaft::FloatBinopOp::IsCommutative (Kind kind) [inline], [static]
Definition at line 1709 of file operations.h.
                                       {
    switch (kind) {
      case Kind::kAdd:
      case Kind::kMul:
      case Kind::kMin:
      case Kind::kMax:
        return true;
      case Kind::kSub:
      case Kind::kDiv:
      case Kind::kMod:
      case Kind::kPower:
      case Kind::kAtan2:
        return false;
    }
  }
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::FloatBinop(), and v8::internal::compiler::InstructionSelector::IsCommutative().
left()
V<Float> v8::internal::compiler::turboshaft::FloatBinopOp::left () const [inline]
Definition at line 1706 of file operations.h.
{ return input<Float>(0); }
Referenced by v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessFloatBinop(), v8::internal::compiler::InstructionSelector::VisitFloat64Ieee754Binop(), and v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitFloatBinop().
options()
auto v8::internal::compiler::turboshaft::FloatBinopOp::options () const [inline]
Definition at line 1733 of file operations.h.
{ return std::tuple{kind, rep}; }
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::FloatBinopOp::outputs_rep () const [inline]
Definition at line 1697 of file operations.h.
                                                               {
    return base::VectorOf(static_cast<const RegisterRepresentation*>(&rep), 1);
  }
References v8::base::VectorOf().
PrintOptions()
void v8::internal::compiler::turboshaft::FloatBinopOp::PrintOptions (std::ostream & os) const
Definition at line 977 of file operations.cc.
                                                    {
  os << '[';
  switch (kind) {
    case Kind::kAdd:
      os << "Add, ";
      break;
    case Kind::kSub:
      os << "Sub, ";
      break;
    case Kind::kMul:
      os << "Mul, ";
      break;
    case Kind::kDiv:
      os << "Div, ";
      break;
    case Kind::kMod:
      os << "Mod, ";
      break;
    case Kind::kMin:
      os << "Min, ";
      break;
    case Kind::kMax:
      os << "Max, ";
      break;
    case Kind::kPower:
      os << "Power, ";
      break;
    case Kind::kAtan2:
      os << "Atan2, ";
      break;
  }
  os << rep;
  os << ']';
}
References kAdd, kAtan2, kDiv, kind, kMax, kMin, kMod, kMul, kPower, kSub, and rep.
right()
V<Float> v8::internal::compiler::turboshaft::FloatBinopOp::right () const [inline]
Definition at line 1707 of file operations.h.
{ return input<Float>(1); }
Referenced by v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessFloatBinop(), v8::internal::compiler::InstructionSelector::VisitFloat64Ieee754Binop(), and v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitFloatBinop().
Validate()
void v8::internal::compiler::turboshaft::FloatBinopOp::Validate (const Graph & graph) const [inline]
Definition at line 1729 of file operations.h.
                                          {
    DCHECK_IMPLIES(kind == any_of(Kind::kPower, Kind::kAtan2, Kind::kMod),
                   rep == FloatRepresentation::Float64());
  }
References v8::base::any_of(), DCHECK_IMPLIES, and v8::internal::compiler::turboshaft::FloatRepresentation::Float64().
Member Data Documentation
effects
constexpr OpEffects v8::internal::compiler::turboshaft::FloatBinopOp::effects = OpEffects() [static], [constexpr]
Definition at line 1696 of file operations.h.
kind
Kind v8::internal::compiler::turboshaft::FloatBinopOp::kind
Definition at line 1693 of file operations.h.
Referenced by PrintOptions(), and v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessFloatBinop().
rep
FloatRepresentation v8::internal::compiler::turboshaft::FloatBinopOp::rep
Definition at line 1694 of file operations.h.
Referenced by PrintOptions(), and v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessFloatBinop().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h
/mnt/V8SourceCode/src/compiler/turboshaft/operations.cc