v8::internal::compiler::turboshaft::JSStackCheckOp Struct Reference
#include <operations.h>
Public Types
enum class Kind : uint8_t { kFunctionEntry
, kBuiltinEntry
, kLoop
 }
Public Member Functions
OpEffects Effects () const
V< Context > native_context () const
OptionalV< FrameState > frame_state () const
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
JSStackCheckOp (V< Context > context, OptionalV< FrameState > frame_state, Kind kind)
void Validate (const Graph &graph) const
template<typename Fn , typename Mapper >
auto Explode (Fn fn, Mapper &mapper) const
auto options () const
Static Public Member Functions
static JSStackCheckOp & New (Graph *graph, V< Context > context, OptionalV< FrameState > frame_state, Kind kind)
Public Attributes
Kind kind
Additional Inherited Members
Detailed Description
Definition at line 3573 of file operations.h.
Member Enumeration Documentation
Kind
enum v8::internal::compiler::turboshaft::JSStackCheckOp::Kind : uint8_t [strong]
Enumerator
kFunctionEntry
kBuiltinEntry
kLoop
Definition at line 3574 of file operations.h.
: uint8_t { kFunctionEntry, kBuiltinEntry, kLoop };
Constructor & Destructor Documentation
JSStackCheckOp()
v8::internal::compiler::turboshaft::JSStackCheckOp::JSStackCheckOp (V< Context > context, OptionalV< FrameState > frame_state, Kind kind) [inline], [explicit]
Definition at line 3611 of file operations.h.
      : Base(1 + frame_state.has_value()), kind(kind) {
    input(0) = context;
    if (frame_state.has_value()) {
      input(1) = frame_state.value();
    }
  }
References v8::internal::compiler::turboshaft::OptionalOpIndex::has_value(), and v8::internal::compiler::turboshaft::OptionalV< T >::value().
Member Function Documentation
Effects()
OpEffects v8::internal::compiler::turboshaft::JSStackCheckOp::Effects () const [inline]
Definition at line 3577 of file operations.h.
                            {
    switch (kind) {
      case Kind::kFunctionEntry:
        return OpEffects().CanCallAnything();
      case Kind::kBuiltinEntry:
        return OpEffects().CanCallAnything();
      case Kind::kLoop:
        // Loop body iteration stack checks can't write memory.
        // TODO(dmercadier): we could prevent this from allocating. In
        // particular, we'd need to:
        // - forbid GC interrupts from being processed in loop stack checks.
        // - make sure that the debugger always deopts the current function
        // when it triggers a loop interrupt.
        return OpEffects()
            .CanDependOnChecks()
            .CanDeopt()
            .CanReadHeapMemory()
            .CanAllocate();
    }
  }
References v8::internal::compiler::turboshaft::OpEffects::CanAllocate(), v8::internal::compiler::turboshaft::OpEffects::CanCallAnything(), v8::internal::compiler::turboshaft::OpEffects::CanDeopt(), v8::internal::compiler::turboshaft::OpEffects::CanDependOnChecks(), and v8::internal::compiler::turboshaft::OpEffects::CanReadHeapMemory().
Explode()
template<typename Fn , typename Mapper >
auto v8::internal::compiler::turboshaft::JSStackCheckOp::Explode (Fn fn, Mapper & mapper) const [inline]
Definition at line 3631 of file operations.h.
                                                      {
    return fn(mapper.Map(native_context()), mapper.Map(frame_state()), kind);
  }
References v8::internal::native_context.
frame_state()
OptionalV<FrameState> v8::internal::compiler::turboshaft::JSStackCheckOp::frame_state () const [inline]
Definition at line 3599 of file operations.h.
                                            {
    return input_count > 1 ? Base::input<FrameState>(1)
                           : OptionalV<FrameState>::Nullopt();
  }
References v8::internal::compiler::turboshaft::detail::input_count(), and v8::internal::compiler::turboshaft::OptionalV< T >::Nullopt().
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::JSStackCheckOp::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 3606 of file operations.h.
                                                              {
    return {};
  }
native_context()
V<Context> v8::internal::compiler::turboshaft::JSStackCheckOp::native_context () const [inline]
Definition at line 3598 of file operations.h.
{ return Base::input<Context>(0); }
New()
static JSStackCheckOp& v8::internal::compiler::turboshaft::JSStackCheckOp::New (Graph * graph, V< Context > context, OptionalV< FrameState > frame_state, Kind kind) [inline], [static]
Definition at line 3620 of file operations.h.
                                                                           {
    return Base::New(graph, 1 + frame_state.has_value(), context, frame_state,
                     kind);
  }
References graph(), v8::internal::compiler::turboshaft::OptionalOpIndex::has_value(), and v8::internal::anonymous_namespace{intl-objects.cc}::New().
options()
auto v8::internal::compiler::turboshaft::JSStackCheckOp::options () const [inline]
Definition at line 3635 of file operations.h.
{ return std::tuple{kind}; }
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::JSStackCheckOp::outputs_rep () const [inline]
Definition at line 3604 of file operations.h.
{ return {}; }
Validate()
void v8::internal::compiler::turboshaft::JSStackCheckOp::Validate (const Graph & graph) const [inline]
Definition at line 3626 of file operations.h.
                                          {
    DCHECK_EQ(kind == Kind::kBuiltinEntry, !frame_state().has_value());
  }
References DCHECK_EQ.
Member Data Documentation
kind
Kind v8::internal::compiler::turboshaft::JSStackCheckOp::kind
Definition at line 3575 of file operations.h.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h