v8::internal::compiler::EscapeAnalysisPhase Struct Reference
Public Member Functions
void Run (TFPipelineData *data, Zone *temp_zone)
Detailed Description
Definition at line 1144 of file pipeline.cc.
Member Function Documentation
Run()
void v8::internal::compiler::EscapeAnalysisPhase::Run (TFPipelineData * data, Zone * temp_zone) [inline]
Definition at line 1147 of file pipeline.cc.
                                                  {
    EscapeAnalysis escape_analysis(data->jsgraph(),
                                   &data->info()->tick_counter(), temp_zone);
    escape_analysis.ReduceGraph();
    GraphReducer reducer(temp_zone, data->graph(),
                         &data->info()->tick_counter(), data->broker(),
                         data->jsgraph()->Dead(), data->observe_node_manager());
    EscapeAnalysisReducer escape_reducer(
        &reducer, data->jsgraph(), data->broker(),
        escape_analysis.analysis_result(), temp_zone);
    AddReducer(data, &reducer, &escape_reducer);
    // EscapeAnalysisReducer accesses the heap.
    UnparkedScopeIfNeeded scope(data->broker());
    reducer.ReduceGraph();
    // TODO(turbofan): Turn this into a debug mode check once we have
    // confidence.
    escape_reducer.VerifyReplacement();
  }
References v8::internal::compiler::anonymous_namespace{pipeline.cc}::AddReducer(), v8::internal::compiler::EscapeAnalysis::analysis_result(), v8::internal::compiler::GraphReducer::ReduceGraph(), and v8::internal::compiler::EscapeAnalysisReducer::VerifyReplacement().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/pipeline.cc