v8::internal::anonymous_namespace{debug-wasm-objects.cc}::StackProxy Struct Reference
Static Public Member Functions
static DirectHandle< JSObject > Create (WasmFrame *frame)
static uint32_t Count (Isolate *isolate, DirectHandle< FixedArray > values)
static DirectHandle< Object > Get (Isolate *isolate, DirectHandle< FixedArray > values, uint32_t index)
Static Public Attributes
static constexpr char const * kClassName = `Stack`
Additional Inherited Members
Detailed Description
Definition at line 456 of file debug-wasm-objects.cc.
Member Function Documentation
Count()
static uint32_t v8::internal::anonymous_namespace{debug-wasm-objects.cc}::StackProxy::Count (Isolate * isolate, DirectHandle< FixedArray > values) [inline], [static]
Definition at line 474 of file debug-wasm-objects.cc.
                                                                           {
    return values->length();
  }
Create()
static DirectHandle<JSObject> v8::internal::anonymous_namespace{debug-wasm-objects.cc}::StackProxy::Create (WasmFrame * frame) [inline], [static]
Definition at line 459 of file debug-wasm-objects.cc.
                                                         {
    auto isolate = frame->isolate();
    auto debug_info =
        frame->trusted_instance_data()->native_module()->GetDebugInfo();
    int count = debug_info->GetStackDepth(frame->pc(), isolate);
    auto values = isolate->factory()->NewFixedArray(count);
    for (int i = 0; i < count; ++i) {
      auto value = WasmValueObject::New(
          isolate, debug_info->GetStackValue(i, frame->pc(), frame->fp(),
                                             frame->callee_fp(), isolate));
      values->set(i, *value);
    }
    return IndexedDebugProxy::Create(isolate, values);
  }
References v8::internal::Isolate::factory(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::Factory::isolate(), v8::internal::WasmValueObject::New(), v8::internal::FactoryBase< Impl >::NewFixedArray(), and v8::internal::value.
Get()
static DirectHandle<Object> v8::internal::anonymous_namespace{debug-wasm-objects.cc}::StackProxy::Get (Isolate * isolate, DirectHandle< FixedArray > values, uint32_t index) [inline], [static]
Definition at line 478 of file debug-wasm-objects.cc.
                                                  {
    return direct_handle(values->get(index), isolate);
  }
References v8::internal::direct_handle(), and v8::internal::index.
Member Data Documentation
kClassName
constexpr char const* v8::internal::anonymous_namespace{debug-wasm-objects.cc}::StackProxy::kClassName = `Stack` [static], [constexpr]
Definition at line 457 of file debug-wasm-objects.cc.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/debug/debug-wasm-objects.cc