v8::internal::torque::CallIntrinsicInstruction Struct Reference
#include <instructions.h>
Public Member Functions
CallIntrinsicInstruction (Intrinsic *intrinsic, TypeVector specialization_types, std::vector< std::string > constexpr_arguments)
std::size_t GetValueDefinitionCount () const
DefinitionLocation GetValueDefinition (std::size_t index) const
Public Attributes
Intrinsic * intrinsic
TypeVector specialization_types
std::vector< std::string > constexpr_arguments
Detailed Description
Definition at line 455 of file instructions.h.
Constructor & Destructor Documentation
CallIntrinsicInstruction()
v8::internal::torque::CallIntrinsicInstruction::CallIntrinsicInstruction (Intrinsic * intrinsic, TypeVector specialization_types, std::vector< std::string > constexpr_arguments) [inline]
Definition at line 457 of file instructions.h.
      : intrinsic(intrinsic),
        specialization_types(std::move(specialization_types)),
        constexpr_arguments(constexpr_arguments) {}
Member Function Documentation
GetValueDefinition()
DefinitionLocation v8::internal::torque::CallIntrinsicInstruction::GetValueDefinition (std::size_t index) const
Definition at line 186 of file instructions.cc.
                           {
  DCHECK_LT(index, GetValueDefinitionCount());
  return DefinitionLocation::Instruction(this, index);
}
References DCHECK_LT, GetValueDefinitionCount(), v8::internal::index, and v8::internal::torque::DefinitionLocation::Instruction().
GetValueDefinitionCount()
std::size_t v8::internal::torque::CallIntrinsicInstruction::GetValueDefinitionCount () const
Definition at line 182 of file instructions.cc.
                                                                  {
  return LowerType(intrinsic->signature().return_type).size();
}
References intrinsic, v8::internal::torque::LowerType(), v8::internal::torque::Signature::return_type, and v8::internal::torque::Callable::signature().
Referenced by GetValueDefinition().
Member Data Documentation
constexpr_arguments
std::vector<std::string> v8::internal::torque::CallIntrinsicInstruction::constexpr_arguments
Definition at line 469 of file instructions.h.
Referenced by v8::internal::torque::operator<<().
intrinsic
Intrinsic* v8::internal::torque::CallIntrinsicInstruction::intrinsic
Definition at line 467 of file instructions.h.
Referenced by GetValueDefinitionCount(), and v8::internal::torque::operator<<().
specialization_types
TypeVector v8::internal::torque::CallIntrinsicInstruction::specialization_types
Definition at line 468 of file instructions.h.
Referenced by v8::internal::torque::operator<<().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/torque/instructions.h
/mnt/V8SourceCode/src/torque/instructions.cc