v8::internal::compiler::turboshaft::BranchOp Struct Reference
#include <operations.h>
Public Member Functions
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
V< Word32 > condition () const
BranchOp (V< Word32 > condition, Block *if_true, Block *if_false, BranchHint hint)
size_t hash_value (HashingStrategy strategy=HashingStrategy::kDefault) const
auto options () const
Public Attributes
BranchHint hint
Block * if_true
Block * if_false
Static Public Attributes
static constexpr OpEffects effects = OpEffects().CanChangeControlFlow()
Additional Inherited Members
Detailed Description
Definition at line 4422 of file operations.h.
Constructor & Destructor Documentation
BranchOp()
v8::internal::compiler::turboshaft::BranchOp::BranchOp (V< Word32 > condition, Block * if_true, Block * if_false, BranchHint hint) [inline]
Definition at line 4437 of file operations.h.
      : Base(condition), hint(hint), if_true(if_true), if_false(if_false) {}
Member Function Documentation
condition()
V<Word32> v8::internal::compiler::turboshaft::BranchOp::condition () const [inline]
Definition at line 4435 of file operations.h.
{ return input<Word32>(0); }
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphBranch(), v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::GetLoopIterationCount(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessBranchOnTarget(), v8::internal::compiler::turboshaft::IfElseCascadeToSwitchReducer< Next >::ReduceInputGraphBranch(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::RefineTypesAfterBranch(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::RefineTypesAfterBranch(), and v8::internal::compiler::InstructionSelector::VisitBranch().
hash_value()
size_t v8::internal::compiler::turboshaft::BranchOp::hash_value (HashingStrategy strategy = HashingStrategy::kDefault) const
Definition at line 2132 of file operations.cc.
                                                          {
  if (strategy == HashingStrategy::kMakeSnapshotStable) {
    // Destructure here to cause a compilation error in case `options` is
    // changed.
    auto [if_true_value, if_false_value, hint_value] = options();
    return HashWithOptions(index_for_bound_block(if_true_value),
                           index_for_bound_block(if_false_value), hint_value);
  } else {
    return Base::hash_value(strategy);
  }
}
References v8::internal::compiler::turboshaft::OperationT< Derived >::hash_value(), v8::internal::compiler::turboshaft::OperationT< Derived >::HashWithOptions(), v8::internal::compiler::turboshaft::anonymous_namespace{operations.cc}::index_for_bound_block(), v8::internal::compiler::turboshaft::kMakeSnapshotStable, and options().
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::BranchOp::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 4430 of file operations.h.
                                                              {
    return MaybeRepVector<MaybeRegisterRepresentation::Word32()>();
  }
options()
auto v8::internal::compiler::turboshaft::BranchOp::options () const [inline]
Definition at line 4442 of file operations.h.
{ return std::tuple{if_true, if_false, hint}; }
Referenced by hash_value().
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::BranchOp::outputs_rep () const [inline]
Definition at line 4428 of file operations.h.
{ return {}; }
Member Data Documentation
effects
constexpr OpEffects v8::internal::compiler::turboshaft::BranchOp::effects = OpEffects().CanChangeControlFlow() [static], [constexpr]
Definition at line 4427 of file operations.h.
hint
BranchHint v8::internal::compiler::turboshaft::BranchOp::hint
Definition at line 4423 of file operations.h.
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphBranch(), v8::internal::compiler::turboshaft::IsUnlikelySuccessor(), v8::internal::compiler::turboshaft::IfElseCascadeToSwitchReducer< Next >::ReduceInputGraphBranch(), and v8::internal::compiler::InstructionSelector::VisitBranch().
if_false
Block* v8::internal::compiler::turboshaft::BranchOp::if_false
Definition at line 4425 of file operations.h.
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphBranch(), v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::GetLoopIterationCount(), v8::internal::compiler::turboshaft::IsUnlikelySuccessor(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessBranchOnTarget(), v8::internal::compiler::turboshaft::IfElseCascadeToSwitchReducer< Next >::ReduceInputGraphBranch(), v8::internal::compiler::turboshaft::Assembler< Reducers >::SplitEdge(), and v8::internal::compiler::InstructionSelector::VisitControl().
if_true
Block* v8::internal::compiler::turboshaft::BranchOp::if_true
Definition at line 4424 of file operations.h.
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphBranch(), v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::GetLoopIterationCount(), v8::internal::compiler::turboshaft::IsUnlikelySuccessor(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessBranchOnTarget(), v8::internal::compiler::turboshaft::IfElseCascadeToSwitchReducer< Next >::ReduceInputGraphBranch(), v8::internal::compiler::turboshaft::Assembler< Reducers >::SplitEdge(), v8::internal::compiler::turboshaft::SuccessorBlocks(), and v8::internal::compiler::InstructionSelector::VisitControl().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h
/mnt/V8SourceCode/src/compiler/turboshaft/operations.cc