v8::internal::compiler::turboshaft::Opmask::MaskBuilder< Op, Fields > Struct Template Reference
#include <opmasks.h>
Public Types
template<typename Fields::type... Args>
using For = OpMaskT< Op, BuildMask(), EncodeValue(Args...)>
Static Public Member Functions
static constexpr uint64_t BuildBaseMask ()
static constexpr uint64_t EncodeBaseValue (Opcode opcode)
static constexpr uint64_t BuildMask ()
static constexpr uint64_t EncodeValue (typename Fields::type... args)
template<typename F >
static constexpr uint64_t BuildFieldMask ()
template<typename F >
static constexpr uint64_t EncodeFieldValue (typename F::type value)
Detailed Description
template<typename Op, typename... Fields>
struct v8::internal::compiler::turboshaft::Opmask::MaskBuilder< Op, Fields >
Definition at line 80 of file opmasks.h.
Member Typedef Documentation
For
template<typename Op , typename... Fields>
template<typename Fields::type... Args>
using v8::internal::compiler::turboshaft::Opmask::MaskBuilder< Op, Fields >::For = OpMaskT<Op, BuildMask(), EncodeValue(Args...)>
Definition at line 137 of file opmasks.h.
Member Function Documentation
BuildBaseMask()
template<typename Op , typename... Fields>
static constexpr uint64_t v8::internal::compiler::turboshaft::Opmask::MaskBuilder< Op, Fields >::BuildBaseMask () [inline], [static], [constexpr]
Definition at line 81 of file opmasks.h.
                                            {
    static_assert(OFFSET_OF(Operation, opcode) == 0);
    static_assert(sizeof(Operation::opcode) == sizeof(uint8_t));
    static_assert(sizeof(Operation) == 4);
#if V8_TARGET_BIG_ENDIAN
    return static_cast<uint64_t>(0xFF)
           << ((sizeof(uint64_t) - sizeof(uint8_t)) * kBitsPerByte);
#else
    return static_cast<uint64_t>(0xFF);
#endif
  }
References v8::internal::kBitsPerByte, OFFSET_OF, and v8::internal::compiler::turboshaft::Operation::opcode.
Referenced by v8::internal::compiler::turboshaft::Opmask::MaskBuilder< Op, Fields >::BuildMask().
BuildFieldMask()
template<typename Op , typename... Fields>
template<typename F >
static constexpr uint64_t v8::internal::compiler::turboshaft::Opmask::MaskBuilder< Op, Fields >::BuildFieldMask () [inline], [static], [constexpr]
Definition at line 114 of file opmasks.h.
                                             {
    static_assert(F::size < sizeof(uint64_t));
    static_assert(F::offset + F::size <= sizeof(uint64_t));
    constexpr uint64_t ones = static_cast<uint64_t>(-1) >>
                              ((sizeof(uint64_t) - F::size) * kBitsPerByte);
#if V8_TARGET_BIG_ENDIAN
    return ones << ((sizeof(uint64_t) - F::size - F::offset) * kBitsPerByte);
#else
    return ones << (F::offset * kBitsPerByte);
#endif
  }
References v8::internal::kBitsPerByte, and size().
BuildMask()
template<typename Op , typename... Fields>
static constexpr uint64_t v8::internal::compiler::turboshaft::Opmask::MaskBuilder< Op, Fields >::BuildMask () [inline], [static], [constexpr]
Definition at line 103 of file opmasks.h.
                                        {
    constexpr uint64_t base_mask = BuildBaseMask();
    return (base_mask | ... | BuildFieldMask<Fields>());
  }
References v8::internal::compiler::turboshaft::Opmask::MaskBuilder< Op, Fields >::BuildBaseMask().
EncodeBaseValue()
template<typename Op , typename... Fields>
static constexpr uint64_t v8::internal::compiler::turboshaft::Opmask::MaskBuilder< Op, Fields >::EncodeBaseValue (Opcode opcode) [inline], [static], [constexpr]
Definition at line 93 of file opmasks.h.
                                                           {
    static_assert(OFFSET_OF(Operation, opcode) == 0);
#if V8_TARGET_BIG_ENDIAN
    return static_cast<uint64_t>(opcode)
           << ((sizeof(uint64_t) - sizeof(Operation::opcode)) * kBitsPerByte);
#else
    return static_cast<uint64_t>(opcode);
#endif
  }
References v8::internal::kBitsPerByte, OFFSET_OF, and v8::internal::compiler::turboshaft::Operation::opcode.
Referenced by v8::internal::compiler::turboshaft::Opmask::MaskBuilder< Op, Fields >::EncodeValue().
EncodeFieldValue()
template<typename Op , typename... Fields>
template<typename F >
static constexpr uint64_t v8::internal::compiler::turboshaft::Opmask::MaskBuilder< Op, Fields >::EncodeFieldValue (typename F::type value) [inline], [static], [constexpr]
Definition at line 127 of file opmasks.h.
                                                                   {
#if V8_TARGET_BIG_ENDIAN
    return encode_for_mask(value)
           << ((sizeof(uint64_t) - F::size - F::offset) * kBitsPerByte);
#else
    return encode_for_mask(value) << (F::offset * kBitsPerByte);
#endif
  }
References v8::internal::compiler::turboshaft::Opmask::encode_for_mask(), v8::internal::kBitsPerByte, size(), and v8::internal::value.
EncodeValue()
template<typename Op , typename... Fields>
static constexpr uint64_t v8::internal::compiler::turboshaft::Opmask::MaskBuilder< Op, Fields >::EncodeValue (typename Fields::type... args) [inline], [static], [constexpr]
Definition at line 108 of file opmasks.h.
                                                                     {
    constexpr uint64_t base_mask = EncodeBaseValue(operation_to_opcode_v<Op>);
    return (base_mask | ... | EncodeFieldValue<Fields>(args));
  }
References v8::base::args, and v8::internal::compiler::turboshaft::Opmask::MaskBuilder< Op, Fields >::EncodeBaseValue().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/opmasks.h