v8::base::internal::IsGreater< L, R > Struct Template Reference
#include <safe_conversions_impl.h>
Public Types
using SumT = decltype(std::declval< L >()+std::declval< R >())
Static Public Member Functions
static constexpr bool Test (L lhs, R rhs)
Detailed Description
template<typename L, typename R>
struct v8::base::internal::IsGreater< L, R >
Definition at line 605 of file safe_conversions_impl.h.
Member Typedef Documentation
SumT
template<typename L , typename R >
using v8::base::internal::IsGreater< L, R >::SumT = decltype(std::declval<L>() + std::declval<R>())
Definition at line 606 of file safe_conversions_impl.h.
Member Function Documentation
Test()
template<typename L , typename R >
static constexpr bool v8::base::internal::IsGreater< L, R >::Test (L lhs, R rhs) [inline], [static], [constexpr]
Definition at line 607 of file safe_conversions_impl.h.
                                           {
    const RangeCheck l_range = DstRangeRelationToSrcRange<R>(lhs);
    const RangeCheck r_range = DstRangeRelationToSrcRange<L>(rhs);
    return l_range.IsOverflow() || r_range.IsUnderflow() ||
           (l_range == r_range &&
            static_cast<SumT>(lhs) > static_cast<SumT>(rhs));
  }
References v8::base::internal::RangeCheck::IsOverflow(), and v8::base::internal::RangeCheck::IsUnderflow().
Referenced by v8::base::internal::requires().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/base/numerics/safe_conversions_impl.h