wasm::FuncData Struct Reference
Public Types
enum Kind { kCallback
, kCallbackWithEnv
 }
Public Member Functions
FuncData (Store *store, const FuncType *type, Kind kind)
~FuncData ()
Static Public Member Functions
static i::Address v8_callback (i::Address host_data_foreign, i::Address argv)
Public Attributes
Store * store
own< FuncType > type
enum wasm::FuncData::Kind kind
xx xx xx xx xx xx xx xx xx
union {
 Func::callback callback
 Func::callback_with_env callback_with_env
};
void(* finalizer)(void *)
void * env
Static Public Attributes
static constexpr i::ExternalPointerTag kManagedTag = i::kWasmFuncDataTag
Detailed Description
Definition at line 1481 of file c-api.cc.
Member Enumeration Documentation
Kind
enum wasm::FuncData::Kind
Enumerator
kCallback
kCallbackWithEnv
Definition at line 1486 of file c-api.cc.
{ kCallback, kCallbackWithEnv } kind;
Constructor & Destructor Documentation
FuncData()
wasm::FuncData::FuncData (Store * store, const FuncType * type, Kind kind) [inline]
Definition at line 1494 of file c-api.cc.
      : store(store),
        type(type->copy()),
        kind(kind),
        finalizer(nullptr),
        env(nullptr) {}
 FuncData()
wasm::FuncData::~FuncData () [inline]
Definition at line 1501 of file c-api.cc.
              {
    if (finalizer) (*finalizer)(env);
  }
References env, and finalizer.
Member Function Documentation
v8_callback()
i::Address wasm::FuncData::v8_callback (i::Address host_data_foreign, i::Address argv) [static]
Definition at line 1884 of file c-api.cc.
                                                {
  FuncData* self =
      i::Cast<i::Managed<FuncData>>(i::Tagged<i::Object>(host_data_foreign))
          ->raw();
  StoreImpl* store = impl(self->store);
  i::Isolate* isolate = store->i_isolate();
  v8::Isolate::Scope isolate_scope(store->isolate());
  i::HandleScope scope(isolate);
  isolate->set_context(*v8::Utils::OpenDirectHandle(*store->context()));
  const ownvec<ValType>& param_types = self->type->params();
  const ownvec<ValType>& result_types = self->type->results();
  int num_param_types = static_cast<int>(param_types.size());
  int num_result_types = static_cast<int>(result_types.size());
  auto params = vec<Val>::make_uninitialized(num_param_types);
  auto results = vec<Val>::make_uninitialized(num_result_types);
  i::Address p = argv;
  for (int i = 0; i < num_param_types; ++i) {
    switch (param_types[i]->kind()) {
      case ValKind::I32:
        params[i] = Val(v8::base::ReadUnalignedValue<int32_t>(p));
        p += 4;
        break;
      case ValKind::I64:
        params[i] = Val(v8::base::ReadUnalignedValue<int64_t>(p));
        p += 8;
        break;
      case ValKind::F32:
        params[i] = Val(v8::base::ReadUnalignedValue<float32_t>(p));
        p += 4;
        break;
      case ValKind::F64:
        params[i] = Val(v8::base::ReadUnalignedValue<float64_t>(p));
        p += 8;
        break;
      case ValKind::EXTERNREF:
      case ValKind::FUNCREF: {
        i::Address raw = v8::base::ReadUnalignedValue<i::Address>(p);
        p += sizeof(raw);
        i::DirectHandle<i::Object> obj(i::Tagged<i::Object>(raw), isolate);
        params[i] = Val(V8RefValueToWasm(store, obj));
        break;
      }
    }
  }
  own<Trap> trap;
  if (self->kind == kCallbackWithEnv) {
    trap = self->callback_with_env(self->env, params, results);
  } else {
    trap = self->callback(params, results);
  }
  if (trap) {
    isolate->Throw(*impl(trap.get())->v8_object());
    i::Tagged<i::Object> ex = isolate->exception();
    isolate->clear_exception();
    return ex.ptr();
  }
  p = argv;
  for (int i = 0; i < num_result_types; ++i) {
    switch (result_types[i]->kind()) {
      case ValKind::I32:
        v8::base::WriteUnalignedValue(p, results[i].i32());
        p += 4;
        break;
      case ValKind::I64:
        v8::base::WriteUnalignedValue(p, results[i].i64());
        p += 8;
        break;
      case ValKind::F32:
        v8::base::WriteUnalignedValue(p, results[i].f32());
        p += 4;
        break;
      case ValKind::F64:
        v8::base::WriteUnalignedValue(p, results[i].f64());
        p += 8;
        break;
      case ValKind::EXTERNREF:
      case ValKind::FUNCREF: {
        v8::base::WriteUnalignedValue(
            p, (*WasmRefToV8(isolate, results[i].ref())).ptr());
        p += sizeof(i::Address);
        break;
      }
    }
  }
  return i::kNullAddress;
}
References v8::internal::Isolate::clear_exception(), v8::internal::Isolate::exception(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, wasm::impl(), kCallbackWithEnv, kind, v8::base::kNullAddress, v8::Utils::OpenDirectHandle(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), v8::internal::Isolate::set_context(), store, v8::internal::Isolate::Throw(), wasm::anonymous_namespace{c-api.cc}::V8RefValueToWasm(), wasm::anonymous_namespace{c-api.cc}::WasmRefToV8(), and v8::base::WriteUnalignedValue().
Referenced by wasm::anonymous_namespace{c-api.cc}::make_func().
Member Data Documentation
union { ... }
callback
Func::callback wasm::FuncData::callback
Definition at line 1488 of file c-api.cc.
Referenced by wasm::anonymous_namespace{c-api.cc}::CallWasmCapiFunction().
callback_with_env
Func::callback_with_env wasm::FuncData::callback_with_env
Definition at line 1489 of file c-api.cc.
Referenced by wasm::anonymous_namespace{c-api.cc}::CallWasmCapiFunction().
env
void* wasm::FuncData::env
Definition at line 1492 of file c-api.cc.
Referenced by wasm::anonymous_namespace{c-api.cc}::CallWasmCapiFunction(), and ~FuncData().
finalizer
void(* wasm::FuncData::finalizer) (void *)
Definition at line 1491 of file c-api.cc.
Referenced by ~FuncData().
kind
enum wasm::FuncData::Kind wasm::FuncData::kind
Referenced by wasm::anonymous_namespace{c-api.cc}::CallWasmCapiFunction(), and v8_callback().
kManagedTag
constexpr i::ExternalPointerTag wasm::FuncData::kManagedTag = i::kWasmFuncDataTag [static], [constexpr]
Definition at line 1482 of file c-api.cc.
store
Store* wasm::FuncData::store
Definition at line 1484 of file c-api.cc.
Referenced by v8_callback().
type
own<FuncType> wasm::FuncData::type
Definition at line 1485 of file c-api.cc.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/wasm/c-api.cc