v8::internal::compiler::turboshaft::CallView Struct Reference
Public Member Functions
CallView (const Operation &op)
Public Attributes
V< CallTarget > target
base::Vector< const OpIndex > arguments
const TSCallDescriptor * descriptor
Detailed Description
Definition at line 19 of file csa-effects-computation.cc.
Constructor & Destructor Documentation
CallView()
v8::internal::compiler::turboshaft::CallView::CallView (const Operation & op) [inline], [explicit]
Definition at line 24 of file csa-effects-computation.cc.
                                         {
    switch (op.opcode) {
      case Opcode::kCall: {
        const CallOp& call = op.Cast<CallOp>();
        this->target = call.callee();
        this->arguments = call.arguments();
        this->descriptor = call.descriptor;
        return;
      }
      case Opcode::kTailCall: {
        const TailCallOp& call = op.Cast<TailCallOp>();
        this->target = call.callee();
        this->arguments = call.arguments();
        this->descriptor = call.descriptor;
        return;
      }
      default:
        UNREACHABLE();
    }
  }
References v8::internal::compiler::turboshaft::CallOp::arguments(), v8::internal::compiler::turboshaft::TailCallOp::arguments(), v8::internal::compiler::turboshaft::CallOp::callee(), v8::internal::compiler::turboshaft::TailCallOp::callee(), v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::compiler::turboshaft::CallOp::descriptor, v8::internal::compiler::turboshaft::TailCallOp::descriptor, v8::internal::wasm::kTailCall, v8::internal::compiler::turboshaft::Operation::opcode, and v8::internal::UNREACHABLE().
Member Data Documentation
arguments
base::Vector<const OpIndex> v8::internal::compiler::turboshaft::CallView::arguments
Definition at line 21 of file csa-effects-computation.cc.
descriptor
const TSCallDescriptor* v8::internal::compiler::turboshaft::CallView::descriptor
Definition at line 22 of file csa-effects-computation.cc.
Referenced by v8::internal::compiler::turboshaft::AnalyzeCall().
target
V<CallTarget> v8::internal::compiler::turboshaft::CallView::target
Definition at line 20 of file csa-effects-computation.cc.
Referenced by v8::internal::compiler::turboshaft::AnalyzeCall().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/csa-effects-computation.cc