v8::internal::torque::MatchedInput Struct Reference
#include <earley-parser.h>
Public Member Functions
MatchedInput (InputPosition begin, InputPosition end, SourcePosition pos)
std::string ToString () const
Public Attributes
InputPosition begin
InputPosition end
SourcePosition pos
Detailed Description
Definition at line 152 of file earley-parser.h.
Constructor & Destructor Documentation
MatchedInput()
v8::internal::torque::MatchedInput::MatchedInput (InputPosition begin, InputPosition end, SourcePosition pos) [inline]
Definition at line 153 of file earley-parser.h.
      : begin(begin), end(end), pos(pos) {}
Member Function Documentation
ToString()
std::string v8::internal::torque::MatchedInput::ToString () const [inline]
Definition at line 158 of file earley-parser.h.
{ return {begin, end}; }
References begin, and end.
Referenced by v8::internal::torque::Item::CheckAmbiguity(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeExpressionWithSource(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeIdentifierFromMatchedInput(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeRightShiftIdentifier(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::YieldDouble(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::YieldInt32(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::YieldIntegerLiteral(), and v8::internal::torque::Grammar::YieldMatchedInput().
Member Data Documentation
begin
InputPosition v8::internal::torque::MatchedInput::begin
Definition at line 155 of file earley-parser.h.
Referenced by ToString().
end
InputPosition v8::internal::torque::MatchedInput::end
Definition at line 156 of file earley-parser.h.
Referenced by ToString().
pos
SourcePosition v8::internal::torque::MatchedInput::pos
Definition at line 157 of file earley-parser.h.
Referenced by v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeEnumDeclaration(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeTypeswitchCase(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeTypeswitchStatement(), v8::internal::torque::Rule::RunAction(), and v8::internal::torque::RunEarleyAlgorithm().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/torque/earley-parser.h