v8::internal::compiler::turboshaft::WordBinopOp Struct Reference
#include <operations.h>
Public Types
enum class Kind : uint8_t {
kAdd
, kMul
, kSignedMulOverflownBits
, kUnsignedMulOverflownBits
,
kBitwiseAnd
, kBitwiseOr
, kBitwiseXor
, kSub
,
kSignedDiv
, kUnsignedDiv
, kSignedMod
, kUnsignedMod
 }
Public Member Functions
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
template<class WordType = Word>
V< WordType > left () const requires(IsWord< WordType >())
template<class WordType = Word>
V< WordType > right () const requires(IsWord< WordType >())
bool IsCommutative () const
WordBinopOp (V< Word > left, V< Word > right, Kind kind, WordRepresentation rep)
auto options () const
void PrintOptions (std::ostream &os) const
Static Public Member Functions
static bool IsCommutative (Kind kind)
static bool IsAssociative (Kind kind)
static bool AllowsWord64ToWord32Truncation (Kind kind)
Public Attributes
Kind kind
WordRepresentation rep
Static Public Attributes
static constexpr OpEffects effects = OpEffects().CanDependOnChecks()
Additional Inherited Members
Detailed Description
Definition at line 1572 of file operations.h.
Member Enumeration Documentation
Kind
enum v8::internal::compiler::turboshaft::WordBinopOp::Kind : uint8_t [strong]
Enumerator
kAdd
kMul
kSignedMulOverflownBits
kUnsignedMulOverflownBits
kBitwiseAnd
kBitwiseOr
kBitwiseXor
kSub
kSignedDiv
kUnsignedDiv
kSignedMod
kUnsignedMod
Definition at line 1573 of file operations.h.
                  : uint8_t {
    kAdd,
    kMul,
    kSignedMulOverflownBits,
    kUnsignedMulOverflownBits,
    kBitwiseAnd,
    kBitwiseOr,
    kBitwiseXor,
    kSub,
    kSignedDiv,
    kUnsignedDiv,
    kSignedMod,
    kUnsignedMod,
  };
Constructor & Destructor Documentation
WordBinopOp()
v8::internal::compiler::turboshaft::WordBinopOp::WordBinopOp (V< Word > left, V< Word > right, Kind kind, WordRepresentation rep) [inline]
Definition at line 1674 of file operations.h.
      : Base(left, right), kind(kind), rep(rep) {}
Member Function Documentation
AllowsWord64ToWord32Truncation()
static bool v8::internal::compiler::turboshaft::WordBinopOp::AllowsWord64ToWord32Truncation (Kind kind) [inline], [static]
Definition at line 1655 of file operations.h.
                                                        {
    switch (kind) {
      case Kind::kAdd:
      case Kind::kMul:
      case Kind::kBitwiseAnd:
      case Kind::kBitwiseOr:
      case Kind::kBitwiseXor:
      case Kind::kSub:
        return true;
      case Kind::kSignedMulOverflownBits:
      case Kind::kUnsignedMulOverflownBits:
      case Kind::kSignedDiv:
      case Kind::kUnsignedDiv:
      case Kind::kSignedMod:
      case Kind::kUnsignedMod:
        return false;
    }
  }
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::WordBinopOp::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 1596 of file operations.h.
                                                              {
    return InputsRepFactory::PairOf(rep);
  }
References v8::internal::compiler::turboshaft::InputsRepFactory::PairOf().
IsAssociative()
static bool v8::internal::compiler::turboshaft::WordBinopOp::IsAssociative (Kind kind) [inline], [static]
Definition at line 1635 of file operations.h.
                                       {
    switch (kind) {
      case Kind::kAdd:
      case Kind::kMul:
      case Kind::kBitwiseAnd:
      case Kind::kBitwiseOr:
      case Kind::kBitwiseXor:
        return true;
      case Kind::kSignedMulOverflownBits:
      case Kind::kUnsignedMulOverflownBits:
      case Kind::kSub:
      case Kind::kSignedDiv:
      case Kind::kUnsignedDiv:
      case Kind::kSignedMod:
      case Kind::kUnsignedMod:
        return false;
    }
  }
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordBinop().
IsCommutative() [1/2]
bool v8::internal::compiler::turboshaft::WordBinopOp::IsCommutative () const [inline]
Definition at line 1614 of file operations.h.
{ return IsCommutative(kind); }
References IsCommutative().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::GetBinopLeftRightCstOnTheRight(), IsCommutative(), v8::internal::compiler::InstructionSelector::IsCommutative(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitBinOp(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitWordCompare(), v8::internal::compiler::turboshaft::InstructionSelectionNormalizationReducer< Next >::WordBinop(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordBinop().
IsCommutative() [2/2]
static bool v8::internal::compiler::turboshaft::WordBinopOp::IsCommutative (Kind kind) [inline], [static]
Definition at line 1616 of file operations.h.
                                       {
    switch (kind) {
      case Kind::kAdd:
      case Kind::kMul:
      case Kind::kSignedMulOverflownBits:
      case Kind::kUnsignedMulOverflownBits:
      case Kind::kBitwiseAnd:
      case Kind::kBitwiseOr:
      case Kind::kBitwiseXor:
        return true;
      case Kind::kSub:
      case Kind::kSignedDiv:
      case Kind::kUnsignedDiv:
      case Kind::kSignedMod:
      case Kind::kUnsignedMod:
        return false;
    }
  }
left()
template<class WordType = Word>
V<WordType> v8::internal::compiler::turboshaft::WordBinopOp::left () const [inline]
Definition at line 1602 of file operations.h.
  {
    return input<WordType>(0);
  }
Referenced by v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::DcheckWordBinop(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::DcheckWordBinop(), v8::internal::compiler::turboshaft::FindCompareChain(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::GetBinopLeftRightCstOnTheRight(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Load(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::MachineTypeForNarrowWordAnd(), v8::internal::compiler::turboshaft::DuplicationOptimizationReducer< Next >::MaybeDuplicateWordBinop(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessWordBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::RemoveUnnecessaryWordAnd(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Store(), v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::StoreLoadInfo(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitMultiplyAdd(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitMultiplyNegate(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitMultiplySub(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::TryMatchBaseWithScaledIndexAndDisplacement(), v8::internal::compiler::TryMatchNegFromSub(), v8::internal::compiler::TryMatchShiftFromMul(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitDiv(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitDiv(), v8::internal::compiler::VisitLogical(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitMod(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitMod(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitMulHigh(), and v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitWord32Compare().
options()
auto v8::internal::compiler::turboshaft::WordBinopOp::options () const [inline]
Definition at line 1677 of file operations.h.
{ return std::tuple{kind, rep}; }
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::WordBinopOp::outputs_rep () const [inline]
Definition at line 1592 of file operations.h.
                                                               {
    return base::VectorOf(static_cast<const RegisterRepresentation*>(&rep), 1);
  }
References v8::base::VectorOf().
PrintOptions()
void v8::internal::compiler::turboshaft::WordBinopOp::PrintOptions (std::ostream & os) const
Definition at line 933 of file operations.cc.
                                                   {
  os << '[';
  switch (kind) {
    case Kind::kAdd:
      os << "Add, ";
      break;
    case Kind::kSub:
      os << "Sub, ";
      break;
    case Kind::kMul:
      os << "Mul, ";
      break;
    case Kind::kSignedMulOverflownBits:
      os << "SignedMulOverflownBits, ";
      break;
    case Kind::kUnsignedMulOverflownBits:
      os << "UnsignedMulOverflownBits, ";
      break;
    case Kind::kSignedDiv:
      os << "SignedDiv, ";
      break;
    case Kind::kUnsignedDiv:
      os << "UnsignedDiv, ";
      break;
    case Kind::kSignedMod:
      os << "SignedMod, ";
      break;
    case Kind::kUnsignedMod:
      os << "UnsignedMod, ";
      break;
    case Kind::kBitwiseAnd:
      os << "BitwiseAnd, ";
      break;
    case Kind::kBitwiseOr:
      os << "BitwiseOr, ";
      break;
    case Kind::kBitwiseXor:
      os << "BitwiseXor, ";
      break;
  }
  os << rep;
  os << ']';
}
References kAdd, kBitwiseAnd, kBitwiseOr, kBitwiseXor, kind, kMul, kSignedDiv, kSignedMod, kSignedMulOverflownBits, kSub, kUnsignedDiv, kUnsignedMod, kUnsignedMulOverflownBits, and rep.
right()
template<class WordType = Word>
V<WordType> v8::internal::compiler::turboshaft::WordBinopOp::right () const [inline]
Definition at line 1608 of file operations.h.
  {
    return input<WordType>(1);
  }
Referenced by v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::DcheckWordBinop(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::DcheckWordBinop(), v8::internal::compiler::turboshaft::FindCompareChain(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::GetBinopLeftRightCstOnTheRight(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Load(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::MachineTypeForNarrowWordAnd(), v8::internal::compiler::turboshaft::DuplicationOptimizationReducer< Next >::MaybeDuplicateWordBinop(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessWordBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::RemoveUnnecessaryWordAnd(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Store(), v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::StoreLoadInfo(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitMultiplyAdd(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitMultiplyNegate(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitMultiplySub(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::TryMatchBaseWithScaledIndexAndDisplacement(), v8::internal::compiler::TryMatchNegFromSub(), v8::internal::compiler::TryMatchShiftFromMul(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitDiv(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitDiv(), v8::internal::compiler::VisitLogical(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitMod(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitMod(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitMulHigh(), and v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitWord32Compare().
Member Data Documentation
effects
constexpr OpEffects v8::internal::compiler::turboshaft::WordBinopOp::effects = OpEffects().CanDependOnChecks() [static], [constexpr]
Definition at line 1591 of file operations.h.
kind
Kind v8::internal::compiler::turboshaft::WordBinopOp::kind
Definition at line 1587 of file operations.h.
Referenced by v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::DcheckWordBinop(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::DcheckWordBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::GetBinopLeftRightCstOnTheRight(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::IsNodeUnsigned(), v8::internal::compiler::IsWord32Binop(), v8::internal::compiler::turboshaft::DuplicationOptimizationReducer< Next >::MaybeDuplicateWordBinop(), PrintOptions(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessWordBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::ProduceWord32Result(), v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::StoreLoadInfo(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitMultiplySub(), v8::internal::compiler::TryMatchBaseWithScaledIndexAndDisplacement64ForWordBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::TryMatchBaseWithScaledIndexAndDisplacementForWordBinop(), v8::internal::compiler::turboshaft::UnwrapAllocate(), and v8::internal::compiler::InstructionSelector::VisitNode().
rep
WordRepresentation v8::internal::compiler::turboshaft::WordBinopOp::rep
Definition at line 1588 of file operations.h.
Referenced by v8::internal::compiler::IsWord32Binop(), v8::internal::compiler::turboshaft::DuplicationOptimizationReducer< Next >::MaybeDuplicateWordBinop(), PrintOptions(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessWordBinop(), v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::StoreLoadInfo(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAddSub(), and v8::internal::compiler::InstructionSelector::VisitNode().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h
/mnt/V8SourceCode/src/compiler/turboshaft/operations.cc