cppgc::internal::TraceTraitFromInnerAddressImpl Struct Reference
#include <trace-trait.h>
Static Public Member Functions
static TraceDescriptor GetTraceDescriptor (const void *address)
Detailed Description
Definition at line 65 of file trace-trait.h.
Member Function Documentation
GetTraceDescriptor()
TraceDescriptor cppgc::internal::TraceTraitFromInnerAddressImpl::GetTraceDescriptor (const void * address) [static]
Definition at line 13 of file trace-trait.cc.
                         {
  // address is guaranteed to be on a normal page because this is used only for
  // mixins.
  const BasePage* page = BasePage::FromPayload(address);
  page->SynchronizedLoad();
  const HeapObjectHeader& header =
      page->ObjectHeaderFromInnerAddress<AccessMode::kAtomic>(address);
  return {header.ObjectStart(),
          GlobalGCInfoTable::GCInfoFromIndex(
              header.GetGCInfoIndex<AccessMode::kAtomic>())
              .trace};
}
References cppgc::internal::BasePage::FromPayload(), cppgc::internal::GlobalGCInfoTable::GCInfoFromIndex(), cppgc::internal::HeapObjectHeader::GetGCInfoIndex(), cppgc::internal::kAtomic, cppgc::internal::BasePage::ObjectHeaderFromInnerAddress(), cppgc::internal::HeapObjectHeader::ObjectStart(), cppgc::internal::BasePage::SynchronizedLoad(), and cppgc::internal::GCInfo::trace.
Referenced by cppgc::internal::TraceTraitImpl< T, true >::GetTraceDescriptor().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/include/cppgc/trace-trait.h
/mnt/V8SourceCode/src/heap/cppgc/trace-trait.cc