v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TestAndBranchMatcherTurboshaft Struct Reference
Public Member Functions
TestAndBranchMatcherTurboshaft (InstructionSelector *selector, const WordBinopOp &binop)
bool Matches () const
unsigned bit () const
Private Member Functions
void Initialize ()
Private Attributes
InstructionSelector * selector_
const WordBinopOp & binop_
bool matches_ = false
unsigned bit_ = 0
Detailed Description
Definition at line 3466 of file instruction-selector-arm64.cc.
Constructor & Destructor Documentation
TestAndBranchMatcherTurboshaft()
v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TestAndBranchMatcherTurboshaft::TestAndBranchMatcherTurboshaft (InstructionSelector * selector, const WordBinopOp & binop) [inline]
Definition at line 3467 of file instruction-selector-arm64.cc.
      : selector_(selector), binop_(binop) {
    Initialize();
  }
Member Function Documentation
bit()
unsigned v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TestAndBranchMatcherTurboshaft::bit () const [inline]
Definition at line 3475 of file instruction-selector-arm64.cc.
                       {
    DCHECK(Matches());
    return bit_;
  }
References v8::internal::DCHECK(), and v8::internal::anonymous_namespace{json-parser.cc}::Matches().
Initialize()
void v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TestAndBranchMatcherTurboshaft::Initialize () [inline], [private]
Definition at line 3481 of file instruction-selector-arm64.cc.
                    {
    if (binop_.kind != WordBinopOp::Kind::kBitwiseAnd) return;
    uint64_t value{0};
    if (!selector_->MatchUnsignedIntegralConstant(binop_.right(), &value) ||
        !base::bits::IsPowerOfTwo(value)) {
      return;
    }
    // All preconditions for TBZ/TBNZ matched.
    matches_ = true;
    bit_ = base::bits::CountTrailingZeros(value);
  }
References v8::base::bits::CountTrailingZeros(), v8::base::bits::IsPowerOfTwo(), v8::internal::compiler::turboshaft::WordBinopOp::kBitwiseAnd, and v8::internal::value.
Matches()
bool v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TestAndBranchMatcherTurboshaft::Matches () const [inline]
Definition at line 3473 of file instruction-selector-arm64.cc.
{ return matches_; }
Member Data Documentation
binop_
const WordBinopOp& v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TestAndBranchMatcherTurboshaft::binop_ [private]
Definition at line 3494 of file instruction-selector-arm64.cc.
bit_
unsigned v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TestAndBranchMatcherTurboshaft::bit_ = 0 [private]
Definition at line 3496 of file instruction-selector-arm64.cc.
matches_
bool v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TestAndBranchMatcherTurboshaft::matches_ = false [private]
Definition at line 3495 of file instruction-selector-arm64.cc.
selector_
InstructionSelector* v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TestAndBranchMatcherTurboshaft::selector_ [private]
Definition at line 3493 of file instruction-selector-arm64.cc.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/arm64/instruction-selector-arm64.cc