cppgc::internal::SingleThreadedHandle Struct Reference
#include <task-handle.h>
Classes
struct NonEmptyTag
Public Member Functions
SingleThreadedHandle ()=default
SingleThreadedHandle (NonEmptyTag)
void Cancel ()
void CancelIfNonEmpty ()
bool IsCanceled () const
operator bool () const
Private Attributes
std::shared_ptr< bool > is_cancelled_
Detailed Description
Definition at line 16 of file task-handle.h.
Constructor & Destructor Documentation
SingleThreadedHandle() [1/2]
cppgc::internal::SingleThreadedHandle::SingleThreadedHandle () [default]
SingleThreadedHandle() [2/2]
cppgc::internal::SingleThreadedHandle::SingleThreadedHandle (NonEmptyTag) [inline], [explicit]
Definition at line 22 of file task-handle.h.
      : is_cancelled_(std::make_shared<bool>(false)) {}
Member Function Documentation
Cancel()
void cppgc::internal::SingleThreadedHandle::Cancel () [inline]
Definition at line 25 of file task-handle.h.
                {
    DCHECK(is_cancelled_);
    *is_cancelled_ = true;
  }
References DCHECK, and is_cancelled_.
Referenced by cppgc::internal::Sweeper::SweeperImpl::CancelAllSweepingTasks(), and cppgc::internal::GCInvoker::GCInvokerImpl::GCTask::Run().
CancelIfNonEmpty()
void cppgc::internal::SingleThreadedHandle::CancelIfNonEmpty () [inline]
Definition at line 30 of file task-handle.h.
                          {
    if (is_cancelled_) {
      *is_cancelled_ = true;
    }
  }
References is_cancelled_.
Referenced by cppgc::internal::MarkerBase::EnterAtomicPause().
IsCanceled()
bool cppgc::internal::SingleThreadedHandle::IsCanceled () const [inline]
Definition at line 36 of file task-handle.h.
                          {
    DCHECK(is_cancelled_);
    return *is_cancelled_;
  }
References DCHECK, and is_cancelled_.
Referenced by cppgc::internal::GCInvoker::GCInvokerImpl::GCTask::Run(), cppgc::internal::MarkerBase::IncrementalMarkingTask::Run(), and cppgc::internal::Sweeper::SweeperImpl::IncrementalSweepTask::Run().
operator bool()
cppgc::internal::SingleThreadedHandle::operator bool () const [inline], [explicit]
Definition at line 42 of file task-handle.h.
                                 {
    return is_cancelled_.get() && !*is_cancelled_.get();
  }
References is_cancelled_.
Member Data Documentation
is_cancelled_
std::shared_ptr<bool> cppgc::internal::SingleThreadedHandle::is_cancelled_ [private]
Definition at line 47 of file task-handle.h.
Referenced by Cancel(), CancelIfNonEmpty(), IsCanceled(), and operator bool().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/heap/cppgc/task-handle.h