v8::internal::anonymous_namespace{compiler.cc}::ScriptCompileTimerScope Struct Reference
Public Types
enum class CacheBehaviour {
kProduceCodeCache
, kHitIsolateCacheWhenNoCache
, kConsumeCodeCache
, kConsumeCodeCacheFailed
,
kNoCacheBecauseInlineScript
, kNoCacheBecauseScriptTooSmall
, kNoCacheBecauseCacheTooCold
, kNoCacheNoReason
,
kNoCacheBecauseNoResource
, kNoCacheBecauseInspector
, kNoCacheBecauseCachingDisabled
, kNoCacheBecauseModule
,
kNoCacheBecauseStreamingSource
, kNoCacheBecauseV8Extension
, kHitIsolateCacheWhenProduceCodeCache
, kHitIsolateCacheWhenConsumeCodeCache
,
kNoCacheBecauseExtensionModule
, kNoCacheBecausePacScript
, kNoCacheBecauseInDocumentWrite
, kNoCacheBecauseResourceWithNoCacheHandler
,
kHitIsolateCacheWhenStreamingSource
, kNoCacheBecauseStaticCodeCache
, kCount
 }
Public Member Functions
ScriptCompileTimerScope (Isolate *isolate, ScriptCompiler::NoCacheReason no_cache_reason, ScriptCompiler::CompilationDetails *compilation_details)
~ScriptCompileTimerScope ()
void set_hit_isolate_cache ()
void set_consuming_code_cache ()
void set_consuming_code_cache_failed ()
Private Member Functions
CacheBehaviour GetCacheBehaviour ()
TimedHistogram * GetCacheBehaviourTimedHistogram (CacheBehaviour cache_behaviour)
Private Attributes
Isolate * isolate_
LazyTimedHistogramScope histogram_scope_
NestedTimedHistogramScope all_scripts_histogram_scope_
ScriptCompiler::NoCacheReason no_cache_reason_
bool hit_isolate_cache_
bool consuming_code_cache_
bool consuming_code_cache_failed_
Detailed Description
Definition at line 3528 of file compiler.cc.
Member Enumeration Documentation
CacheBehaviour
enum v8::internal::anonymous_namespace{compiler.cc}::ScriptCompileTimerScope::CacheBehaviour [strong]
Enumerator
kProduceCodeCache
kHitIsolateCacheWhenNoCache
kConsumeCodeCache
kConsumeCodeCacheFailed
kNoCacheBecauseInlineScript
kNoCacheBecauseScriptTooSmall
kNoCacheBecauseCacheTooCold
kNoCacheNoReason
kNoCacheBecauseNoResource
kNoCacheBecauseInspector
kNoCacheBecauseCachingDisabled
kNoCacheBecauseModule
kNoCacheBecauseStreamingSource
kNoCacheBecauseV8Extension
kHitIsolateCacheWhenProduceCodeCache
kHitIsolateCacheWhenConsumeCodeCache
kNoCacheBecauseExtensionModule
kNoCacheBecausePacScript
kNoCacheBecauseInDocumentWrite
kNoCacheBecauseResourceWithNoCacheHandler
kHitIsolateCacheWhenStreamingSource
kNoCacheBecauseStaticCodeCache
kCount
Definition at line 3533 of file compiler.cc.
                            {
    kProduceCodeCache,
    kHitIsolateCacheWhenNoCache,
    kConsumeCodeCache,
    kConsumeCodeCacheFailed,
    kNoCacheBecauseInlineScript,
    kNoCacheBecauseScriptTooSmall,
    kNoCacheBecauseCacheTooCold,
    kNoCacheNoReason,
    kNoCacheBecauseNoResource,
    kNoCacheBecauseInspector,
    kNoCacheBecauseCachingDisabled,
    kNoCacheBecauseModule,
    kNoCacheBecauseStreamingSource,
    kNoCacheBecauseV8Extension,
    kHitIsolateCacheWhenProduceCodeCache,
    kHitIsolateCacheWhenConsumeCodeCache,
    kNoCacheBecauseExtensionModule,
    kNoCacheBecausePacScript,
    kNoCacheBecauseInDocumentWrite,
    kNoCacheBecauseResourceWithNoCacheHandler,
    kHitIsolateCacheWhenStreamingSource,
    kNoCacheBecauseStaticCodeCache,
    kCount
  };
Constructor & Destructor Documentation
ScriptCompileTimerScope()
v8::internal::anonymous_namespace{compiler.cc}::ScriptCompileTimerScope::ScriptCompileTimerScope (Isolate * isolate, ScriptCompiler::NoCacheReason no_cache_reason, ScriptCompiler::CompilationDetails * compilation_details) [inline]
Definition at line 3559 of file compiler.cc.
      : isolate_(isolate),
        histogram_scope_(&compilation_details->foreground_time_in_microseconds),
        all_scripts_histogram_scope_(isolate->counters()->compile_script()),
        no_cache_reason_(no_cache_reason),
        hit_isolate_cache_(false),
        consuming_code_cache_(false),
        consuming_code_cache_failed_(false) {}
 ScriptCompileTimerScope()
v8::internal::anonymous_namespace{compiler.cc}::ScriptCompileTimerScope::~ScriptCompileTimerScope () [inline]
Definition at line 3570 of file compiler.cc.
                             {
    CacheBehaviour cache_behaviour = GetCacheBehaviour();
    Histogram* cache_behaviour_histogram =
        isolate_->counters()->compile_script_cache_behaviour();
    // Sanity check that the histogram has exactly one bin per enum entry.
    DCHECK_EQ(0, cache_behaviour_histogram->min());
    DCHECK_EQ(static_cast<int>(CacheBehaviour::kCount),
              cache_behaviour_histogram->max() + 1);
    DCHECK_EQ(static_cast<int>(CacheBehaviour::kCount),
              cache_behaviour_histogram->num_buckets());
    cache_behaviour_histogram->AddSample(static_cast<int>(cache_behaviour));
    histogram_scope_.set_histogram(
        GetCacheBehaviourTimedHistogram(cache_behaviour));
  }
References v8::internal::Histogram::AddSample(), v8::internal::Histogram::counters(), DCHECK_EQ, v8::internal::Histogram::max(), v8::internal::Histogram::min(), and v8::internal::Histogram::num_buckets().
Member Function Documentation
GetCacheBehaviour()
CacheBehaviour v8::internal::anonymous_namespace{compiler.cc}::ScriptCompileTimerScope::GetCacheBehaviour () [inline], [private]
Definition at line 3606 of file compiler.cc.
                                     {
    if (consuming_code_cache_) {
      if (hit_isolate_cache_) {
        return CacheBehaviour::kHitIsolateCacheWhenConsumeCodeCache;
      } else if (consuming_code_cache_failed_) {
        return CacheBehaviour::kConsumeCodeCacheFailed;
      }
      return CacheBehaviour::kConsumeCodeCache;
    }
    if (hit_isolate_cache_) {
      // A roundabout way of knowing the embedder is going to produce a code
      // cache (which is done by a separate API call later) is to check whether
      // no_cache_reason_ is
      // ScriptCompiler::kNoCacheBecauseDeferredProduceCodeCache.
      if (no_cache_reason_ ==
          ScriptCompiler::kNoCacheBecauseDeferredProduceCodeCache) {
        return CacheBehaviour::kHitIsolateCacheWhenProduceCodeCache;
      } else if (no_cache_reason_ ==
                 ScriptCompiler::kNoCacheBecauseStreamingSource) {
        return CacheBehaviour::kHitIsolateCacheWhenStreamingSource;
      }
      return CacheBehaviour::kHitIsolateCacheWhenNoCache;
    }
    switch (no_cache_reason_) {
      case ScriptCompiler::kNoCacheBecauseInlineScript:
        return CacheBehaviour::kNoCacheBecauseInlineScript;
      case ScriptCompiler::kNoCacheBecauseScriptTooSmall:
        return CacheBehaviour::kNoCacheBecauseScriptTooSmall;
      case ScriptCompiler::kNoCacheBecauseCacheTooCold:
        return CacheBehaviour::kNoCacheBecauseCacheTooCold;
      case ScriptCompiler::kNoCacheNoReason:
        return CacheBehaviour::kNoCacheNoReason;
      case ScriptCompiler::kNoCacheBecauseNoResource:
        return CacheBehaviour::kNoCacheBecauseNoResource;
      case ScriptCompiler::kNoCacheBecauseInspector:
        return CacheBehaviour::kNoCacheBecauseInspector;
      case ScriptCompiler::kNoCacheBecauseCachingDisabled:
        return CacheBehaviour::kNoCacheBecauseCachingDisabled;
      case ScriptCompiler::kNoCacheBecauseModule:
        return CacheBehaviour::kNoCacheBecauseModule;
      case ScriptCompiler::kNoCacheBecauseStreamingSource:
        return CacheBehaviour::kNoCacheBecauseStreamingSource;
      case ScriptCompiler::kNoCacheBecauseV8Extension:
        return CacheBehaviour::kNoCacheBecauseV8Extension;
      case ScriptCompiler::kNoCacheBecauseExtensionModule:
        return CacheBehaviour::kNoCacheBecauseExtensionModule;
      case ScriptCompiler::kNoCacheBecausePacScript:
        return CacheBehaviour::kNoCacheBecausePacScript;
      case ScriptCompiler::kNoCacheBecauseInDocumentWrite:
        return CacheBehaviour::kNoCacheBecauseInDocumentWrite;
      case ScriptCompiler::kNoCacheBecauseResourceWithNoCacheHandler:
        return CacheBehaviour::kNoCacheBecauseResourceWithNoCacheHandler;
      case ScriptCompiler::kNoCacheBecauseDeferredProduceCodeCache:
        return CacheBehaviour::kProduceCodeCache;
      case ScriptCompiler::kNoCacheBecauseStaticCodeCache:
        return CacheBehaviour::kNoCacheBecauseStaticCodeCache;
      }
    UNREACHABLE();
  }
References v8::ScriptCompiler::kNoCacheBecauseCacheTooCold, v8::ScriptCompiler::kNoCacheBecauseCachingDisabled, v8::ScriptCompiler::kNoCacheBecauseDeferredProduceCodeCache, v8::ScriptCompiler::kNoCacheBecauseExtensionModule, v8::ScriptCompiler::kNoCacheBecauseInDocumentWrite, v8::ScriptCompiler::kNoCacheBecauseInlineScript, v8::ScriptCompiler::kNoCacheBecauseInspector, v8::ScriptCompiler::kNoCacheBecauseModule, v8::ScriptCompiler::kNoCacheBecauseNoResource, v8::ScriptCompiler::kNoCacheBecausePacScript, v8::ScriptCompiler::kNoCacheBecauseResourceWithNoCacheHandler, v8::ScriptCompiler::kNoCacheBecauseScriptTooSmall, v8::ScriptCompiler::kNoCacheBecauseStaticCodeCache, v8::ScriptCompiler::kNoCacheBecauseStreamingSource, v8::ScriptCompiler::kNoCacheBecauseV8Extension, v8::ScriptCompiler::kNoCacheNoReason, and v8::internal::UNREACHABLE().
GetCacheBehaviourTimedHistogram()
TimedHistogram* v8::internal::anonymous_namespace{compiler.cc}::ScriptCompileTimerScope::GetCacheBehaviourTimedHistogram (CacheBehaviour cache_behaviour) [inline], [private]
Definition at line 3668 of file compiler.cc.
                                      {
    switch (cache_behaviour) {
      case CacheBehaviour::kProduceCodeCache:
      // Even if we hit the isolate's compilation cache, we currently recompile
      // when we want to produce the code cache.
      case CacheBehaviour::kHitIsolateCacheWhenProduceCodeCache:
        return isolate_->counters()->compile_script_with_produce_cache();
      case CacheBehaviour::kHitIsolateCacheWhenNoCache:
      case CacheBehaviour::kHitIsolateCacheWhenConsumeCodeCache:
      case CacheBehaviour::kHitIsolateCacheWhenStreamingSource:
        return isolate_->counters()->compile_script_with_isolate_cache_hit();
      case CacheBehaviour::kConsumeCodeCacheFailed:
        return isolate_->counters()->compile_script_consume_failed();
      case CacheBehaviour::kConsumeCodeCache:
        return isolate_->counters()->compile_script_with_consume_cache();
      // Note that this only counts the finalization part of streaming, the
      // actual streaming compile is counted by BackgroundCompileTask into
      // "compile_script_on_background".
      case CacheBehaviour::kNoCacheBecauseStreamingSource:
        return isolate_->counters()->compile_script_streaming_finalization();
      case CacheBehaviour::kNoCacheBecauseInlineScript:
        return isolate_->counters()
            ->compile_script_no_cache_because_inline_script();
      case CacheBehaviour::kNoCacheBecauseScriptTooSmall:
        return isolate_->counters()
            ->compile_script_no_cache_because_script_too_small();
      case CacheBehaviour::kNoCacheBecauseCacheTooCold:
        return isolate_->counters()
            ->compile_script_no_cache_because_cache_too_cold();
      // Aggregate all the other "no cache" counters into a single histogram, to
      // save space.
      case CacheBehaviour::kNoCacheNoReason:
      case CacheBehaviour::kNoCacheBecauseNoResource:
      case CacheBehaviour::kNoCacheBecauseInspector:
      case CacheBehaviour::kNoCacheBecauseCachingDisabled:
      // TODO(leszeks): Consider counting separately once modules are more
      // common.
      case CacheBehaviour::kNoCacheBecauseModule:
      case CacheBehaviour::kNoCacheBecauseV8Extension:
      case CacheBehaviour::kNoCacheBecauseExtensionModule:
      case CacheBehaviour::kNoCacheBecausePacScript:
      case CacheBehaviour::kNoCacheBecauseInDocumentWrite:
      case CacheBehaviour::kNoCacheBecauseResourceWithNoCacheHandler:
      case CacheBehaviour::kNoCacheBecauseStaticCodeCache:
        return isolate_->counters()->compile_script_no_cache_other();
      case CacheBehaviour::kCount:
        UNREACHABLE();
    }
    UNREACHABLE();
  }
References v8::internal::Isolate::counters(), and v8::internal::UNREACHABLE().
set_consuming_code_cache()
void v8::internal::anonymous_namespace{compiler.cc}::ScriptCompileTimerScope::set_consuming_code_cache () [inline]
Definition at line 3589 of file compiler.cc.
{ consuming_code_cache_ = true; }
Referenced by v8::internal::anonymous_namespace{compiler.cc}::GetSharedFunctionInfoForScriptImpl().
set_consuming_code_cache_failed()
void v8::internal::anonymous_namespace{compiler.cc}::ScriptCompileTimerScope::set_consuming_code_cache_failed () [inline]
Definition at line 3591 of file compiler.cc.
                                         {
    consuming_code_cache_failed_ = true;
  }
Referenced by v8::internal::anonymous_namespace{compiler.cc}::GetSharedFunctionInfoForScriptImpl().
set_hit_isolate_cache()
void v8::internal::anonymous_namespace{compiler.cc}::ScriptCompileTimerScope::set_hit_isolate_cache () [inline]
Definition at line 3587 of file compiler.cc.
{ hit_isolate_cache_ = true; }
Referenced by v8::internal::anonymous_namespace{compiler.cc}::GetSharedFunctionInfoForScriptImpl().
Member Data Documentation
all_scripts_histogram_scope_
NestedTimedHistogramScope v8::internal::anonymous_namespace{compiler.cc}::ScriptCompileTimerScope::all_scripts_histogram_scope_ [private]
Definition at line 3600 of file compiler.cc.
consuming_code_cache_
bool v8::internal::anonymous_namespace{compiler.cc}::ScriptCompileTimerScope::consuming_code_cache_ [private]
Definition at line 3603 of file compiler.cc.
consuming_code_cache_failed_
bool v8::internal::anonymous_namespace{compiler.cc}::ScriptCompileTimerScope::consuming_code_cache_failed_ [private]
Definition at line 3604 of file compiler.cc.
histogram_scope_
LazyTimedHistogramScope v8::internal::anonymous_namespace{compiler.cc}::ScriptCompileTimerScope::histogram_scope_ [private]
Definition at line 3597 of file compiler.cc.
hit_isolate_cache_
bool v8::internal::anonymous_namespace{compiler.cc}::ScriptCompileTimerScope::hit_isolate_cache_ [private]
Definition at line 3602 of file compiler.cc.
isolate_
Isolate* v8::internal::anonymous_namespace{compiler.cc}::ScriptCompileTimerScope::isolate_ [private]
Definition at line 3596 of file compiler.cc.
no_cache_reason_
ScriptCompiler::NoCacheReason v8::internal::anonymous_namespace{compiler.cc}::ScriptCompileTimerScope::no_cache_reason_ [private]
Definition at line 3601 of file compiler.cc.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/codegen/compiler.cc