v8::internal::compiler::turboshaft::wle::BaseListTraits Struct Reference
#include <wasm-load-elimination-reducer.h>
Public Types
using T = SnapshotTable< OpIndex, KeyData >::Key
Static Public Member Functions
static T ** prev (T t)
static T * next (T t)
static bool non_empty (T t)
Detailed Description
Definition at line 88 of file wasm-load-elimination-reducer.h.
Member Typedef Documentation
T
using v8::internal::compiler::turboshaft::wle::BaseListTraits::T = SnapshotTable<OpIndex, KeyData>::Key
Definition at line 89 of file wasm-load-elimination-reducer.h.
Member Function Documentation
next()
static T* v8::internal::compiler::turboshaft::wle::BaseListTraits::next (T t) [inline], [static]
Definition at line 91 of file wasm-load-elimination-reducer.h.
{ return &(t.data().next_same_base); }
References v8::internal::compiler::turboshaft::SnapshotTableKey< Value, KeyData >::data(), and v8::internal::compiler::turboshaft::KeyData::next_same_base.
non_empty()
static bool v8::internal::compiler::turboshaft::wle::BaseListTraits::non_empty (T t) [inline], [static]
Definition at line 92 of file wasm-load-elimination-reducer.h.
{ return t.valid(); }
References v8::internal::compiler::turboshaft::SnapshotTableKey< Value, KeyData >::valid().
prev()
static T** v8::internal::compiler::turboshaft::wle::BaseListTraits::prev (T t) [inline], [static]
Definition at line 90 of file wasm-load-elimination-reducer.h.
{ return &(t.data().prev_same_base); }
References v8::internal::compiler::turboshaft::SnapshotTableKey< Value, KeyData >::data(), and v8::internal::compiler::turboshaft::KeyData::prev_same_base.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/wasm-load-elimination-reducer.h