v8::internal::compiler::MemoryOptimizationPhase Struct Reference
Public Member Functions
void Run (TFPipelineData *data, Zone *temp_zone)
Detailed Description
Definition at line 1325 of file pipeline.cc.
Member Function Documentation
Run()
void v8::internal::compiler::MemoryOptimizationPhase::Run (TFPipelineData * data, Zone * temp_zone) [inline]
Definition at line 1328 of file pipeline.cc.
                                                  {
    // The memory optimizer requires the graphs to be trimmed, so trim now.
    GraphTrimmer trimmer(temp_zone, data->graph());
    NodeVector roots(temp_zone);
    data->jsgraph()->GetCachedNodes(&roots);
    {
      UnparkedScopeIfNeeded scope(data->broker(),
                                  v8_flags.trace_turbo_trimming);
      trimmer.TrimGraph(roots.begin(), roots.end());
    }
    // Optimize allocations and load/store operations.
#if V8_ENABLE_WEBASSEMBLY
    bool is_wasm = data->info()->IsWasm() || data->info()->IsWasmBuiltin();
#else
    bool is_wasm = false;
#endif
    MemoryOptimizer optimizer(
        data->broker(), data->jsgraph(), temp_zone,
        data->info()->allocation_folding()
            ? MemoryLowering::AllocationFolding::kDoAllocationFolding
            : MemoryLowering::AllocationFolding::kDontAllocationFolding,
        data->debug_name(), &data->info()->tick_counter(), is_wasm);
    optimizer.Optimize();
  }
References v8::internal::ZoneVector< T >::begin(), v8::internal::ZoneVector< T >::end(), v8::internal::compiler::MemoryLowering::kDoAllocationFolding, v8::internal::compiler::MemoryLowering::kDontAllocationFolding, v8::internal::compiler::MemoryOptimizer::Optimize(), v8::internal::compiler::GraphTrimmer::TrimGraph(), and v8::internal::v8_flags.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/pipeline.cc