v8::internal::maglev::detail::PushAllHelper< Arg, Args... > Struct Template Reference
#include <maglev-assembler-arm-inl.h>
Static Public Member Functions
static void Push (MaglevAssembler *masm, Arg arg, Args... args)
static void PushReverse (MaglevAssembler *masm, Arg arg, Args... args)
static void Push (MaglevAssembler *masm, Arg arg, Args... args)
static void PushReverse (MaglevAssembler *masm, Arg arg, Args... args)
static void Push (MaglevAssembler *masm, Arg arg, Args... args)
static void PushReverse (MaglevAssembler *masm, Arg arg, Args... args)
static void Push (MaglevAssembler *masm, Arg arg, Args... args)
static void PushReverse (MaglevAssembler *masm, Arg arg, Args... args)
Detailed Description
template<typename Arg, typename... Args>
struct v8::internal::maglev::detail::PushAllHelper< Arg, Args... >
Definition at line 182 of file maglev-assembler-arm-inl.h.
Member Function Documentation
Push() [1/4]
template<typename Arg , typename... Args>
static void v8::internal::maglev::detail::PushAllHelper< Arg, Args... >::Push (MaglevAssembler * masm, Arg arg, Args... args) [inline], [static]
Definition at line 183 of file maglev-assembler-arm-inl.h.
                                                                 {
    if constexpr (is_iterator_range<Arg>::value) {
      PushIterator(masm, arg, args...);
    } else {
      masm->MacroAssembler::Push(arg);
      PushAllHelper<Args...>::Push(masm, args...);
    }
  }
References v8::base::args, and v8::internal::maglev::detail::PushIterator().
Push() [2/4]
template<typename Arg , typename... Args>
static void v8::internal::maglev::detail::PushAllHelper< Arg, Args... >::Push (MaglevAssembler * masm, Arg arg, Args... args) [inline], [static]
Definition at line 276 of file maglev-assembler-riscv-inl.h.
                                                                 {
    if constexpr (is_iterator_range<Arg>::value) {
      PushIterator(masm, arg, args...);
    } else {
      masm->MacroAssembler::Push(arg);
      PushAllHelper<Args...>::Push(masm, args...);
    }
  }
References v8::base::args, and v8::internal::maglev::detail::PushIterator().
Push() [3/4]
template<typename Arg , typename... Args>
static void v8::internal::maglev::detail::PushAllHelper< Arg, Args... >::Push (MaglevAssembler * masm, Arg arg, Args... args) [inline], [static]
Definition at line 182 of file maglev-assembler-s390-inl.h.
                                                                 {
    if constexpr (is_iterator_range<Arg>::value) {
      PushIterator(masm, arg, args...);
    } else {
      masm->MacroAssembler::Push(arg);
      PushAllHelper<Args...>::Push(masm, args...);
    }
  }
References v8::base::args, and v8::internal::maglev::detail::PushIterator().
Push() [4/4]
template<typename Arg , typename... Args>
static void v8::internal::maglev::detail::PushAllHelper< Arg, Args... >::Push (MaglevAssembler * masm, Arg arg, Args... args) [inline], [static]
Definition at line 213 of file maglev-assembler-x64-inl.h.
                                                                 {
    if constexpr (is_iterator_range<Arg>::value) {
      PushIterator(masm, arg, args...);
    } else {
      masm->MacroAssembler::Push(arg);
      PushAllHelper<Args...>::Push(masm, args...);
    }
  }
References v8::base::args, and v8::internal::maglev::detail::PushIterator().
PushReverse() [1/4]
template<typename Arg , typename... Args>
static void v8::internal::maglev::detail::PushAllHelper< Arg, Args... >::PushReverse (MaglevAssembler * masm, Arg arg, Args... args) [inline], [static]
Definition at line 191 of file maglev-assembler-arm-inl.h.
                                                                        {
    if constexpr (is_iterator_range<Arg>::value) {
      PushIteratorReverse(masm, arg, args...);
    } else {
      PushAllHelper<Args...>::PushReverse(masm, args...);
      masm->Push(arg);
    }
  }
References v8::base::args, v8::internal::maglev::MaglevAssembler::Push(), and v8::internal::maglev::detail::PushIteratorReverse().
PushReverse() [2/4]
template<typename Arg , typename... Args>
static void v8::internal::maglev::detail::PushAllHelper< Arg, Args... >::PushReverse (MaglevAssembler * masm, Arg arg, Args... args) [inline], [static]
Definition at line 284 of file maglev-assembler-riscv-inl.h.
                                                                        {
    if constexpr (is_iterator_range<Arg>::value) {
      PushIteratorReverse(masm, arg, args...);
    } else {
      PushAllHelper<Args...>::PushReverse(masm, args...);
      masm->Push(arg);
    }
  }
References v8::base::args, v8::internal::maglev::MaglevAssembler::Push(), and v8::internal::maglev::detail::PushIteratorReverse().
PushReverse() [3/4]
template<typename Arg , typename... Args>
static void v8::internal::maglev::detail::PushAllHelper< Arg, Args... >::PushReverse (MaglevAssembler * masm, Arg arg, Args... args) [inline], [static]
Definition at line 190 of file maglev-assembler-s390-inl.h.
                                                                        {
    if constexpr (is_iterator_range<Arg>::value) {
      PushIteratorReverse(masm, arg, args...);
    } else {
      PushAllHelper<Args...>::PushReverse(masm, args...);
      masm->Push(arg);
    }
  }
References v8::base::args, v8::internal::maglev::MaglevAssembler::Push(), and v8::internal::maglev::detail::PushIteratorReverse().
PushReverse() [4/4]
template<typename Arg , typename... Args>
static void v8::internal::maglev::detail::PushAllHelper< Arg, Args... >::PushReverse (MaglevAssembler * masm, Arg arg, Args... args) [inline], [static]
Definition at line 221 of file maglev-assembler-x64-inl.h.
                                                                        {
    if constexpr (is_iterator_range<Arg>::value) {
      PushIteratorReverse(masm, arg, args...);
    } else {
      PushAllHelper<Args...>::PushReverse(masm, args...);
      masm->Push(arg);
    }
  }
References v8::base::args, v8::internal::maglev::MaglevAssembler::Push(), and v8::internal::maglev::detail::PushIteratorReverse().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/maglev/arm/maglev-assembler-arm-inl.h
/mnt/V8SourceCode/src/maglev/riscv/maglev-assembler-riscv-inl.h
/mnt/V8SourceCode/src/maglev/s390/maglev-assembler-s390-inl.h
/mnt/V8SourceCode/src/maglev/x64/maglev-assembler-x64-inl.h