v8::internal::baseline::detail::PushHelper< interpreter::RegisterList > Struct Reference
#include <baseline-assembler-ia32-inl.h>
Static Public Member Functions
static int Push (BaselineAssembler *basm, interpreter::RegisterList list)
static int PushReverse (BaselineAssembler *basm, interpreter::RegisterList list)
static int Push (BaselineAssembler *basm, interpreter::RegisterList list)
static int PushReverse (BaselineAssembler *basm, interpreter::RegisterList list)
Detailed Description
Definition at line 258 of file baseline-assembler-ia32-inl.h.
Member Function Documentation
Push() [1/2]
static int v8::internal::baseline::detail::PushHelper< interpreter::RegisterList >::Push (BaselineAssembler * basm, interpreter::RegisterList list) [inline], [static]
Definition at line 259 of file baseline-assembler-ia32-inl.h.
                                                                         {
    for (int reg_index = 0; reg_index < list.register_count(); ++reg_index) {
      PushSingle(basm->masm(), list[reg_index]);
    }
    return list.register_count();
  }
References v8::internal::baseline::BaselineAssembler::masm(), v8::internal::baseline::detail::PushSingle(), and v8::internal::interpreter::RegisterList::register_count().
Push() [2/2]
static int v8::internal::baseline::detail::PushHelper< interpreter::RegisterList >::Push (BaselineAssembler * basm, interpreter::RegisterList list) [inline], [static]
Definition at line 270 of file baseline-assembler-x64-inl.h.
                                                                         {
    for (int reg_index = 0; reg_index < list.register_count(); ++reg_index) {
      PushSingle(basm->masm(), list[reg_index]);
    }
    return list.register_count();
  }
References v8::internal::baseline::BaselineAssembler::masm(), v8::internal::baseline::detail::PushSingle(), and v8::internal::interpreter::RegisterList::register_count().
PushReverse() [1/2]
static int v8::internal::baseline::detail::PushHelper< interpreter::RegisterList >::PushReverse (BaselineAssembler * basm, interpreter::RegisterList list) [inline], [static]
Definition at line 265 of file baseline-assembler-ia32-inl.h.
                                                       {
    for (int reg_index = list.register_count() - 1; reg_index >= 0;
         --reg_index) {
      PushSingle(basm->masm(), list[reg_index]);
    }
    return list.register_count();
  }
References v8::internal::baseline::BaselineAssembler::masm(), v8::internal::baseline::detail::PushSingle(), and v8::internal::interpreter::RegisterList::register_count().
PushReverse() [2/2]
static int v8::internal::baseline::detail::PushHelper< interpreter::RegisterList >::PushReverse (BaselineAssembler * basm, interpreter::RegisterList list) [inline], [static]
Definition at line 276 of file baseline-assembler-x64-inl.h.
                                                       {
    for (int reg_index = list.register_count() - 1; reg_index >= 0;
         --reg_index) {
      PushSingle(basm->masm(), list[reg_index]);
    }
    return list.register_count();
  }
References v8::internal::baseline::BaselineAssembler::masm(), v8::internal::baseline::detail::PushSingle(), and v8::internal::interpreter::RegisterList::register_count().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/baseline/ia32/baseline-assembler-ia32-inl.h
/mnt/V8SourceCode/src/baseline/x64/baseline-assembler-x64-inl.h