v8::internal::compiler::DiamondMatcher Struct Reference
#include <node-matchers.h>
Public Member Functions
DiamondMatcher (Node *merge)
bool Matched () const
bool IfProjectionsAreOwned () const
Node * Branch () const
Node * IfTrue () const
Node * IfFalse () const
Node * Merge () const
Node * TrueInputOf (Node *phi) const
Node * FalseInputOf (Node *phi) const
Private Attributes
Node * branch_
Node * if_true_
Node * if_false_
Detailed Description
Definition at line 804 of file node-matchers.h.
Constructor & Destructor Documentation
DiamondMatcher()
v8::internal::compiler::DiamondMatcher::DiamondMatcher (Node * merge) [explicit]
Definition at line 31 of file node-matchers.cc.
    : NodeMatcher(merge),
      branch_(nullptr),
      if_true_(nullptr),
      if_false_(nullptr) {
  if (merge->InputCount() != 2) return;
  if (merge->opcode() != IrOpcode::kMerge) return;
  Node* input0 = merge->InputAt(0);
  if (input0->InputCount() != 1) return;
  Node* input1 = merge->InputAt(1);
  if (input1->InputCount() != 1) return;
  Node* branch = input0->InputAt(0);
  if (branch != input1->InputAt(0)) return;
  if (branch->opcode() != IrOpcode::kBranch) return;
  if (input0->opcode() == IrOpcode::kIfTrue &&
      input1->opcode() == IrOpcode::kIfFalse) {
    branch_ = branch;
    if_true_ = input0;
    if_false_ = input1;
  } else if (input0->opcode() == IrOpcode::kIfFalse &&
             input1->opcode() == IrOpcode::kIfTrue) {
    branch_ = branch;
    if_true_ = input1;
    if_false_ = input0;
  }
}
References branch_, if_false_, if_true_, v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::InputCount(), v8::internal::compiler::turboshaft::kBranch, and v8::internal::compiler::Node::opcode().
Member Function Documentation
Branch()
Node* v8::internal::compiler::DiamondMatcher::Branch () const [inline]
Definition at line 813 of file node-matchers.h.
{ return branch_; }
FalseInputOf()
Node* v8::internal::compiler::DiamondMatcher::FalseInputOf (Node * phi) const [inline]
Definition at line 825 of file node-matchers.h.
                                      {
    DCHECK(IrOpcode::IsPhiOpcode(phi->opcode()));
    DCHECK_EQ(3, phi->InputCount());
    DCHECK_EQ(Merge(), phi->InputAt(2));
    return phi->InputAt(if_true_ == Merge()->InputAt(0) ? 1 : 0);
  }
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::InputCount(), v8::internal::compiler::IrOpcode::IsPhiOpcode(), and v8::internal::compiler::Node::opcode().
IfFalse()
Node* v8::internal::compiler::DiamondMatcher::IfFalse () const [inline]
Definition at line 815 of file node-matchers.h.
{ return if_false_; }
IfProjectionsAreOwned()
bool v8::internal::compiler::DiamondMatcher::IfProjectionsAreOwned () const [inline]
Definition at line 809 of file node-matchers.h.
                                     {
    return if_true_->OwnedBy(node()) && if_false_->OwnedBy(node());
  }
IfTrue()
Node* v8::internal::compiler::DiamondMatcher::IfTrue () const [inline]
Definition at line 814 of file node-matchers.h.
{ return if_true_; }
Matched()
bool v8::internal::compiler::DiamondMatcher::Matched () const [inline]
Definition at line 808 of file node-matchers.h.
{ return branch_; }
Merge()
Node* v8::internal::compiler::DiamondMatcher::Merge () const [inline]
Definition at line 816 of file node-matchers.h.
{ return node(); }
TrueInputOf()
Node* v8::internal::compiler::DiamondMatcher::TrueInputOf (Node * phi) const [inline]
Definition at line 818 of file node-matchers.h.
                                     {
    DCHECK(IrOpcode::IsPhiOpcode(phi->opcode()));
    DCHECK_EQ(3, phi->InputCount());
    DCHECK_EQ(Merge(), phi->InputAt(2));
    return phi->InputAt(if_true_ == Merge()->InputAt(0) ? 0 : 1);
  }
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::InputCount(), v8::internal::compiler::IrOpcode::IsPhiOpcode(), and v8::internal::compiler::Node::opcode().
Member Data Documentation
branch_
Node* v8::internal::compiler::DiamondMatcher::branch_ [private]
Definition at line 833 of file node-matchers.h.
Referenced by DiamondMatcher().
if_false_
Node* v8::internal::compiler::DiamondMatcher::if_false_ [private]
Definition at line 835 of file node-matchers.h.
Referenced by DiamondMatcher().
if_true_
Node* v8::internal::compiler::DiamondMatcher::if_true_ [private]
Definition at line 834 of file node-matchers.h.
Referenced by DiamondMatcher().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/compiler/node-matchers.h
/mnt/V8SourceCode/src/compiler/node-matchers.cc