v8::internal::compiler::turboshaft::TryChangeOp Struct Reference
#include <operations.h>
Public Types
enum class Kind : uint8_t { kSignedFloatTruncateOverflowUndefined
, kUnsignedFloatTruncateOverflowUndefined
 }
Public Member Functions
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
V< Float > input () const
TryChangeOp (V< Float > input, Kind kind, FloatRepresentation from, WordRepresentation to)
auto options () const
Public Attributes
Kind kind
FloatRepresentation from
WordRepresentation to
Static Public Attributes
static constexpr uint32_t kSuccessValue = 1
static constexpr uint32_t kFailureValue = 0
static constexpr OpEffects effects = OpEffects()
Additional Inherited Members
Detailed Description
Definition at line 2374 of file operations.h.
Member Enumeration Documentation
Kind
enum v8::internal::compiler::turboshaft::TryChangeOp::Kind : uint8_t [strong]
Enumerator
kSignedFloatTruncateOverflowUndefined
kUnsignedFloatTruncateOverflowUndefined
Definition at line 2377 of file operations.h.
                  : uint8_t {
    // The result of the truncation is undefined if the result is out of range.
    kSignedFloatTruncateOverflowUndefined,
    kUnsignedFloatTruncateOverflowUndefined,
  };
Constructor & Destructor Documentation
TryChangeOp()
v8::internal::compiler::turboshaft::TryChangeOp::TryChangeOp (V< Float > input, Kind kind, FloatRepresentation from, WordRepresentation to) [inline]
Definition at line 2405 of file operations.h.
      : Base(input), kind(kind), from(from), to(to) {}
Member Function Documentation
input()
V<Float> v8::internal::compiler::turboshaft::TryChangeOp::input () const [inline]
Definition at line 2403 of file operations.h.
{ return Base::input<Float>(0); }
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::TryChangeOp::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 2398 of file operations.h.
                                                              {
    return InputsRepFactory::SingleRep(from);
  }
References v8::internal::compiler::turboshaft::InputsRepFactory::SingleRep().
options()
auto v8::internal::compiler::turboshaft::TryChangeOp::options () const [inline]
Definition at line 2409 of file operations.h.
{ return std::tuple{kind, from, to}; }
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::TryChangeOp::outputs_rep () const [inline]
Definition at line 2387 of file operations.h.
                                                               {
    switch (to.value()) {
      case WordRepresentation::Word32():
        return RepVector<RegisterRepresentation::Word32(),
                         RegisterRepresentation::Word32()>();
      case WordRepresentation::Word64():
        return RepVector<RegisterRepresentation::Word64(),
                         RegisterRepresentation::Word32()>();
    }
  }
References v8::internal::compiler::turboshaft::RepVector(), v8::internal::compiler::turboshaft::WordRepresentation::value(), v8::internal::compiler::turboshaft::RegisterRepresentation::Word32(), v8::internal::compiler::turboshaft::WordRepresentation::Word32(), v8::internal::compiler::turboshaft::RegisterRepresentation::Word64(), and v8::internal::compiler::turboshaft::WordRepresentation::Word64().
Member Data Documentation
effects
constexpr OpEffects v8::internal::compiler::turboshaft::TryChangeOp::effects = OpEffects() [static], [constexpr]
Definition at line 2386 of file operations.h.
from
FloatRepresentation v8::internal::compiler::turboshaft::TryChangeOp::from
Definition at line 2383 of file operations.h.
Referenced by v8::internal::compiler::InstructionSelector::VisitNode().
kFailureValue
constexpr uint32_t v8::internal::compiler::turboshaft::TryChangeOp::kFailureValue = 0 [static], [constexpr]
Definition at line 2376 of file operations.h.
kind
Kind v8::internal::compiler::turboshaft::TryChangeOp::kind
Definition at line 2382 of file operations.h.
Referenced by v8::internal::compiler::InstructionSelector::VisitNode().
kSuccessValue
constexpr uint32_t v8::internal::compiler::turboshaft::TryChangeOp::kSuccessValue = 1 [static], [constexpr]
Definition at line 2375 of file operations.h.
Referenced by v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::Checked(), and v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
to
WordRepresentation v8::internal::compiler::turboshaft::TryChangeOp::to
Definition at line 2384 of file operations.h.
Referenced by v8::internal::compiler::InstructionSelector::VisitNode().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h