v8::internal::baseline::detail::PushAllHelper< interpreter::RegisterList > Struct Reference
#include <baseline-assembler-arm-inl.h>
Static Public Member Functions
static int Push (BaselineAssembler *basm, interpreter::RegisterList list)
static int PushReverse (BaselineAssembler *basm, interpreter::RegisterList list)
static void Push (BaselineAssembler *basm, interpreter::RegisterList list)
static void PushReverse (BaselineAssembler *basm, interpreter::RegisterList list)
static int Push (BaselineAssembler *basm, interpreter::RegisterList list)
static int PushReverse (BaselineAssembler *basm, interpreter::RegisterList list)
static int Push (BaselineAssembler *basm, interpreter::RegisterList list)
static int PushReverse (BaselineAssembler *basm, interpreter::RegisterList list)
static int Push (BaselineAssembler *basm, interpreter::RegisterList list)
static int PushReverse (BaselineAssembler *basm, interpreter::RegisterList list)
static int Push (BaselineAssembler *basm, interpreter::RegisterList list)
static int PushReverse (BaselineAssembler *basm, interpreter::RegisterList list)
static int Push (BaselineAssembler *basm, interpreter::RegisterList list)
static int PushReverse (BaselineAssembler *basm, interpreter::RegisterList list)
Detailed Description
Definition at line 266 of file baseline-assembler-arm-inl.h.
Member Function Documentation
Push() [1/7]
static int v8::internal::baseline::detail::PushAllHelper< interpreter::RegisterList >::Push (BaselineAssembler * basm, interpreter::RegisterList list) [inline], [static]
Definition at line 267 of file baseline-assembler-arm-inl.h.
                                                                         {
    for (int reg_index = 0; reg_index < list.register_count(); ++reg_index) {
      PushAllHelper<interpreter::Register>::Push(basm, list[reg_index]);
    }
    return list.register_count();
  }
References v8::internal::interpreter::RegisterList::register_count().
Push() [2/7]
static void v8::internal::baseline::detail::PushAllHelper< interpreter::RegisterList >::Push (BaselineAssembler * basm, interpreter::RegisterList list) [inline], [static]
Definition at line 332 of file baseline-assembler-arm64-inl.h.
                                                                          {
    DCHECK_EQ(list.register_count() % 2, 0);
    for (int reg_index = 0; reg_index < list.register_count(); reg_index += 2) {
      PushAll(basm, list[reg_index], list[reg_index + 1]);
    }
  }
References DCHECK_EQ, v8::internal::baseline::detail::PushAll(), and v8::internal::interpreter::RegisterList::register_count().
Push() [3/7]
static int v8::internal::baseline::detail::PushAllHelper< interpreter::RegisterList >::Push (BaselineAssembler * basm, interpreter::RegisterList list) [inline], [static]
Definition at line 266 of file baseline-assembler-loong64-inl.h.
                                                                         {
    for (int reg_index = 0; reg_index < list.register_count(); ++reg_index) {
      PushAllHelper<interpreter::Register>::Push(basm, list[reg_index]);
    }
    return list.register_count();
  }
References v8::internal::interpreter::RegisterList::register_count().
Push() [4/7]
static int v8::internal::baseline::detail::PushAllHelper< interpreter::RegisterList >::Push (BaselineAssembler * basm, interpreter::RegisterList list) [inline], [static]
Definition at line 262 of file baseline-assembler-mips64-inl.h.
                                                                         {
    for (int reg_index = 0; reg_index < list.register_count(); ++reg_index) {
      PushAllHelper<interpreter::Register>::Push(basm, list[reg_index]);
    }
    return list.register_count();
  }
References v8::internal::interpreter::RegisterList::register_count().
Push() [5/7]
static int v8::internal::baseline::detail::PushAllHelper< interpreter::RegisterList >::Push (BaselineAssembler * basm, interpreter::RegisterList list) [inline], [static]
Definition at line 350 of file baseline-assembler-ppc-inl.h.
                                                                         {
    for (int reg_index = 0; reg_index < list.register_count(); ++reg_index) {
      PushAllHelper<interpreter::Register>::Push(basm, list[reg_index]);
    }
    return list.register_count();
  }
References v8::internal::interpreter::RegisterList::register_count().
Push() [6/7]
static int v8::internal::baseline::detail::PushAllHelper< interpreter::RegisterList >::Push (BaselineAssembler * basm, interpreter::RegisterList list) [inline], [static]
Definition at line 271 of file baseline-assembler-riscv-inl.h.
                                                                         {
    for (int reg_index = 0; reg_index < list.register_count(); ++reg_index) {
      PushAllHelper<interpreter::Register>::Push(basm, list[reg_index]);
    }
    return list.register_count();
  }
References v8::internal::interpreter::RegisterList::register_count().
Push() [7/7]
static int v8::internal::baseline::detail::PushAllHelper< interpreter::RegisterList >::Push (BaselineAssembler * basm, interpreter::RegisterList list) [inline], [static]
Definition at line 350 of file baseline-assembler-s390-inl.h.
                                                                         {
    for (int reg_index = 0; reg_index < list.register_count(); ++reg_index) {
      PushAllHelper<interpreter::Register>::Push(basm, list[reg_index]);
    }
    return list.register_count();
  }
References v8::internal::interpreter::RegisterList::register_count().
PushReverse() [1/7]
static int v8::internal::baseline::detail::PushAllHelper< interpreter::RegisterList >::PushReverse (BaselineAssembler * basm, interpreter::RegisterList list) [inline], [static]
Definition at line 273 of file baseline-assembler-arm-inl.h.
                                                       {
    for (int reg_index = list.register_count() - 1; reg_index >= 0;
         --reg_index) {
      PushAllHelper<interpreter::Register>::Push(basm, list[reg_index]);
    }
    return list.register_count();
  }
References v8::internal::interpreter::RegisterList::register_count().
PushReverse() [2/7]
static void v8::internal::baseline::detail::PushAllHelper< interpreter::RegisterList >::PushReverse (BaselineAssembler * basm, interpreter::RegisterList list) [inline], [static]
Definition at line 338 of file baseline-assembler-arm64-inl.h.
                                                        {
    int reg_index = list.register_count() - 1;
    if (reg_index % 2 == 0) {
      // Push the padding register to round up the amount of values pushed.
      PushAllReverse(basm, list[reg_index], padreg);
      reg_index--;
    }
    for (; reg_index >= 1; reg_index -= 2) {
      PushAllReverse(basm, list[reg_index - 1], list[reg_index]);
    }
  }
References v8::internal::padreg, v8::internal::baseline::detail::PushAllReverse(), and v8::internal::interpreter::RegisterList::register_count().
PushReverse() [3/7]
static int v8::internal::baseline::detail::PushAllHelper< interpreter::RegisterList >::PushReverse (BaselineAssembler * basm, interpreter::RegisterList list) [inline], [static]
Definition at line 272 of file baseline-assembler-loong64-inl.h.
                                                       {
    for (int reg_index = list.register_count() - 1; reg_index >= 0;
         --reg_index) {
      PushAllHelper<interpreter::Register>::Push(basm, list[reg_index]);
    }
    return list.register_count();
  }
References v8::internal::interpreter::RegisterList::register_count().
PushReverse() [4/7]
static int v8::internal::baseline::detail::PushAllHelper< interpreter::RegisterList >::PushReverse (BaselineAssembler * basm, interpreter::RegisterList list) [inline], [static]
Definition at line 268 of file baseline-assembler-mips64-inl.h.
                                                       {
    for (int reg_index = list.register_count() - 1; reg_index >= 0;
         --reg_index) {
      PushAllHelper<interpreter::Register>::Push(basm, list[reg_index]);
    }
    return list.register_count();
  }
References v8::internal::interpreter::RegisterList::register_count().
PushReverse() [5/7]
static int v8::internal::baseline::detail::PushAllHelper< interpreter::RegisterList >::PushReverse (BaselineAssembler * basm, interpreter::RegisterList list) [inline], [static]
Definition at line 356 of file baseline-assembler-ppc-inl.h.
                                                       {
    for (int reg_index = list.register_count() - 1; reg_index >= 0;
         --reg_index) {
      PushAllHelper<interpreter::Register>::Push(basm, list[reg_index]);
    }
    return list.register_count();
  }
References v8::internal::interpreter::RegisterList::register_count().
PushReverse() [6/7]
static int v8::internal::baseline::detail::PushAllHelper< interpreter::RegisterList >::PushReverse (BaselineAssembler * basm, interpreter::RegisterList list) [inline], [static]
Definition at line 277 of file baseline-assembler-riscv-inl.h.
                                                       {
    for (int reg_index = list.register_count() - 1; reg_index >= 0;
         --reg_index) {
      PushAllHelper<interpreter::Register>::Push(basm, list[reg_index]);
    }
    return list.register_count();
  }
References v8::internal::interpreter::RegisterList::register_count().
PushReverse() [7/7]
static int v8::internal::baseline::detail::PushAllHelper< interpreter::RegisterList >::PushReverse (BaselineAssembler * basm, interpreter::RegisterList list) [inline], [static]
Definition at line 356 of file baseline-assembler-s390-inl.h.
                                                       {
    for (int reg_index = list.register_count() - 1; reg_index >= 0;
         --reg_index) {
      PushAllHelper<interpreter::Register>::Push(basm, list[reg_index]);
    }
    return list.register_count();
  }
References v8::internal::interpreter::RegisterList::register_count().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/baseline/arm/baseline-assembler-arm-inl.h
/mnt/V8SourceCode/src/baseline/arm64/baseline-assembler-arm64-inl.h
/mnt/V8SourceCode/src/baseline/loong64/baseline-assembler-loong64-inl.h
/mnt/V8SourceCode/src/baseline/mips64/baseline-assembler-mips64-inl.h
/mnt/V8SourceCode/src/baseline/ppc/baseline-assembler-ppc-inl.h
/mnt/V8SourceCode/src/baseline/riscv/baseline-assembler-riscv-inl.h
/mnt/V8SourceCode/src/baseline/s390/baseline-assembler-s390-inl.h