v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher > Struct Template Reference
#include <node-matchers.h>
Public Member Functions
BaseWithIndexAndDisplacementMatcher (Node *node, AddressOptions options)
BaseWithIndexAndDisplacementMatcher (Node *node)
bool matches () const
Node * index () const
int scale () const
Node * base () const
Node * displacement () const
DisplacementMode displacement_mode () const
Private Member Functions
void Initialize (Node *node, AddressOptions options)
Static Private Member Functions
static bool OwnedByAddressingOperand (Node *node)
Private Attributes
bool matches_
Node * index_
int scale_
Node * base_
Node * displacement_
DisplacementMode displacement_mode_
Detailed Description
template<class AddMatcher>
struct v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >
Definition at line 506 of file node-matchers.h.
Constructor & Destructor Documentation
BaseWithIndexAndDisplacementMatcher() [1/2]
template<class AddMatcher >
v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::BaseWithIndexAndDisplacementMatcher (Node * node, AddressOptions options) [inline]
Definition at line 507 of file node-matchers.h.
      : matches_(false),
        index_(nullptr),
        scale_(0),
        base_(nullptr),
        displacement_(nullptr),
        displacement_mode_(kPositiveDisplacement) {
    Initialize(node, options);
  }
References v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::Initialize().
BaseWithIndexAndDisplacementMatcher() [2/2]
template<class AddMatcher >
v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::BaseWithIndexAndDisplacementMatcher (Node * node) [inline], [explicit]
Definition at line 517 of file node-matchers.h.
      : matches_(false),
        index_(nullptr),
        scale_(0),
        base_(nullptr),
        displacement_(nullptr),
        displacement_mode_(kPositiveDisplacement) {
    Initialize(node, AddressOption::kAllowScale |
                         (node->op()->HasProperty(Operator::kCommutative)
                              ? AddressOption::kAllowInputSwap
                              : AddressOption::kAllowNone));
  }
References v8::internal::compiler::Operator::HasProperty(), v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::Initialize(), v8::internal::compiler::kAllowInputSwap, v8::internal::compiler::kAllowNone, v8::internal::compiler::kAllowScale, v8::internal::compiler::Operator::kCommutative, and v8::internal::compiler::Node::op().
Member Function Documentation
base()
template<class AddMatcher >
Node* v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::base () const [inline]
Definition at line 533 of file node-matchers.h.
{ return base_; }
References v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::base_.
Referenced by v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::Initialize().
displacement()
template<class AddMatcher >
Node* v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::displacement () const [inline]
Definition at line 534 of file node-matchers.h.
{ return displacement_; }
References v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::displacement_.
Referenced by v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::Initialize().
displacement_mode()
template<class AddMatcher >
DisplacementMode v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::displacement_mode () const [inline]
Definition at line 535 of file node-matchers.h.
{ return displacement_mode_; }
References v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::displacement_mode_.
Referenced by v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::Initialize().
index()
template<class AddMatcher >
Node* v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::index () const [inline]
Definition at line 531 of file node-matchers.h.
{ return index_; }
References v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::index_.
Referenced by v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::Initialize().
Initialize()
template<class AddMatcher >
void v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::Initialize (Node * node, AddressOptions options) [inline], [private]
Definition at line 545 of file node-matchers.h.
                                                      {
    // The BaseWithIndexAndDisplacementMatcher canonicalizes the order of
    // displacements and scale factors that are used as inputs, so instead of
    // enumerating all possible patterns by brute force, checking for node
    // clusters using the following templates in the following order suffices to
    // find all of the interesting cases (S = index * scale, B = base input, D =
    // displacement input):
    // (S + (B + D))
    // (S + (B + B))
    // (S + D)
    // (S + B)
    // ((S + D) + B)
    // ((S + B) + D)
    // ((B + D) + B)
    // ((B + B) + D)
    // (B + D)
    // (B + B)
    if (node->InputCount() < 2) return;
    AddMatcher m(node, options & AddressOption::kAllowInputSwap);
    Node* left = m.left().node();
    Node* right = m.right().node();
    Node* displacement = nullptr;
    Node* base = nullptr;
    Node* index = nullptr;
    Node* scale_expression = nullptr;
    bool power_of_two_plus_one = false;
    DisplacementMode displacement_mode = kPositiveDisplacement;
    int scale = 0;
    if (m.HasIndexInput() && OwnedByAddressingOperand(left)) {
      index = m.IndexInput();
      scale = m.scale();
      scale_expression = left;
      power_of_two_plus_one = m.power_of_two_plus_one();
      bool match_found = false;
      if (right->opcode() == AddMatcher::kSubOpcode &&
          OwnedByAddressingOperand(right)) {
        AddMatcher right_matcher(right);
        if (right_matcher.right().HasResolvedValue()) {
          // (S + (B - D))
          base = right_matcher.left().node();
          displacement = right_matcher.right().node();
          displacement_mode = kNegativeDisplacement;
          match_found = true;
        }
      }
      if (!match_found) {
        if (right->opcode() == AddMatcher::kAddOpcode &&
            OwnedByAddressingOperand(right)) {
          AddMatcher right_matcher(right);
          if (right_matcher.right().HasResolvedValue()) {
            // (S + (B + D))
            base = right_matcher.left().node();
            displacement = right_matcher.right().node();
          } else {
            // (S + (B + B))
            base = right;
          }
        } else if (m.right().HasResolvedValue()) {
          // (S + D)
          displacement = right;
        } else {
          // (S + B)
          base = right;
        }
      }
    } else {
      bool match_found = false;
      if (left->opcode() == AddMatcher::kSubOpcode &&
          OwnedByAddressingOperand(left)) {
        AddMatcher left_matcher(left);
        Node* left_left = left_matcher.left().node();
        Node* left_right = left_matcher.right().node();
        if (left_matcher.right().HasResolvedValue()) {
          if (left_matcher.HasIndexInput() &&
              OwnedByAddressingOperand(left_left)) {
            // ((S - D) + B)
            index = left_matcher.IndexInput();
            scale = left_matcher.scale();
            scale_expression = left_left;
            power_of_two_plus_one = left_matcher.power_of_two_plus_one();
            displacement = left_right;
            displacement_mode = kNegativeDisplacement;
            base = right;
          } else {
            // ((B - D) + B)
            index = left_left;
            displacement = left_right;
            displacement_mode = kNegativeDisplacement;
            base = right;
          }
          match_found = true;
        }
      }
      if (!match_found) {
        if (left->opcode() == AddMatcher::kAddOpcode &&
            OwnedByAddressingOperand(left)) {
          AddMatcher left_matcher(left);
          Node* left_left = left_matcher.left().node();
          Node* left_right = left_matcher.right().node();
          if (left_matcher.HasIndexInput() &&
              OwnedByAddressingOperand(left_left)) {
            if (left_matcher.right().HasResolvedValue()) {
              // ((S + D) + B)
              index = left_matcher.IndexInput();
              scale = left_matcher.scale();
              scale_expression = left_left;
              power_of_two_plus_one = left_matcher.power_of_two_plus_one();
              displacement = left_right;
              base = right;
            } else if (m.right().HasResolvedValue()) {
              if (left->OwnedBy(node)) {
                // ((S + B) + D)
                index = left_matcher.IndexInput();
                scale = left_matcher.scale();
                scale_expression = left_left;
                power_of_two_plus_one = left_matcher.power_of_two_plus_one();
                base = left_right;
                displacement = right;
              } else {
                // (B + D)
                base = left;
                displacement = right;
              }
            } else {
              // (B + B)
              index = left;
              base = right;
            }
          } else {
            if (left_matcher.right().HasResolvedValue()) {
              // ((B + D) + B)
              index = left_left;
              displacement = left_right;
              base = right;
            } else if (m.right().HasResolvedValue()) {
              if (left->OwnedBy(node)) {
                // ((B + B) + D)
                index = left_left;
                base = left_right;
                displacement = right;
              } else {
                // (B + D)
                base = left;
                displacement = right;
              }
            } else {
              // (B + B)
              index = left;
              base = right;
            }
          }
        } else {
          if (m.right().HasResolvedValue()) {
            // (B + D)
            base = left;
            displacement = right;
          } else {
            // (B + B)
            base = left;
            index = right;
          }
        }
      }
    }
    if (displacement != nullptr) {
      if (displacement->opcode() == IrOpcode::kInt32Constant) {
        if (OpParameter<int32_t>(displacement->op()) == 0) {
          displacement = nullptr;
        }
      } else {
        DCHECK_EQ(displacement->opcode(), IrOpcode::kInt64Constant);
        if (OpParameter<int64_t>(displacement->op()) == 0) {
          displacement = nullptr;
        }
      }
    }
    if (power_of_two_plus_one) {
      if (base != nullptr) {
        // If the scale requires explicitly using the index as the base, but a
        // base is already part of the match, then the (1 << N + 1) scale factor
        // can't be folded into the match and the entire index * scale
        // calculation must be computed separately.
        index = scale_expression;
        scale = 0;
      } else {
        base = index;
      }
    }
    if (!(options & AddressOption::kAllowScale) && scale != 0) {
      index = scale_expression;
      scale = 0;
    }
    base_ = base;
    displacement_ = displacement;
    displacement_mode_ = displacement_mode;
    index_ = index;
    scale_ = scale;
    matches_ = true;
  }
References v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::base(), v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::base_, DCHECK_EQ, v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::displacement(), v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::displacement_, v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::displacement_mode(), v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::displacement_mode_, v8::internal::compiler::AddMatcher< BinopMatcher, AddOpcode, SubOpcode, kMulOpcode, kShiftOpcode >::HasIndexInput(), v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::index(), v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::index_, v8::internal::compiler::AddMatcher< BinopMatcher, AddOpcode, SubOpcode, kMulOpcode, kShiftOpcode >::IndexInput(), v8::internal::compiler::Node::InputCount(), v8::internal::compiler::AddMatcher< BinopMatcher, AddOpcode, SubOpcode, kMulOpcode, kShiftOpcode >::kAddOpcode, v8::internal::compiler::kAllowInputSwap, v8::internal::compiler::kAllowScale, v8::internal::compiler::kNegativeDisplacement, v8::internal::compiler::kPositiveDisplacement, v8::internal::compiler::AddMatcher< BinopMatcher, AddOpcode, SubOpcode, kMulOpcode, kShiftOpcode >::kSubOpcode, v8::internal::compiler::BinopMatcher< Left, Right, rep >::left(), v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::matches_, v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::Node::OwnedBy(), v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::OwnedByAddressingOperand(), v8::internal::compiler::AddMatcher< BinopMatcher, AddOpcode, SubOpcode, kMulOpcode, kShiftOpcode >::power_of_two_plus_one(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::right(), v8::internal::compiler::AddMatcher< BinopMatcher, AddOpcode, SubOpcode, kMulOpcode, kShiftOpcode >::scale(), v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::scale(), and v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::scale_.
Referenced by v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::BaseWithIndexAndDisplacementMatcher().
matches()
template<class AddMatcher >
bool v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::matches () const [inline]
Definition at line 530 of file node-matchers.h.
{ return matches_; }
References v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::matches_.
OwnedByAddressingOperand()
template<class AddMatcher >
static bool v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::OwnedByAddressingOperand (Node * node) [inline], [static], [private]
Definition at line 747 of file node-matchers.h.
                                                   {
    for (auto use : node->use_edges()) {
      Node* from = use.from();
      switch (from->opcode()) {
        case IrOpcode::kLoad:
        case IrOpcode::kLoadImmutable:
        case IrOpcode::kProtectedLoad:
        case IrOpcode::kLoadTrapOnNull:
        case IrOpcode::kInt32Add:
        case IrOpcode::kInt64Add:
          // Skip addressing uses.
          break;
        case IrOpcode::kInt32Sub:
          // If the subtrahend is not a constant, it is not an addressing use.
          if (from->InputAt(1)->opcode() != IrOpcode::kInt32Constant)
            return false;
          break;
        case IrOpcode::kInt64Sub:
          // If the subtrahend is not a constant, it is not an addressing use.
          if (from->InputAt(1)->opcode() != IrOpcode::kInt64Constant)
            return false;
          break;
        case IrOpcode::kStore:
        case IrOpcode::kProtectedStore:
        case IrOpcode::kStoreTrapOnNull:
          // If the stored value is this node, it is not an addressing use.
          if (from->InputAt(2) == node) return false;
          // Otherwise it is used as an address and skipped.
          break;
        default:
          // Non-addressing use found.
          return false;
      }
    }
    return true;
  }
References v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::opcode(), use(), and v8::internal::compiler::Node::use_edges().
Referenced by v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::Initialize().
scale()
template<class AddMatcher >
int v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::scale () const [inline]
Definition at line 532 of file node-matchers.h.
{ return scale_; }
References v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::scale_.
Referenced by v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::Initialize().
Member Data Documentation
base_
template<class AddMatcher >
Node* v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::base_ [private]
Definition at line 541 of file node-matchers.h.
Referenced by v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::base(), and v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::Initialize().
displacement_
template<class AddMatcher >
Node* v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::displacement_ [private]
Definition at line 542 of file node-matchers.h.
Referenced by v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::displacement(), and v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::Initialize().
displacement_mode_
template<class AddMatcher >
DisplacementMode v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::displacement_mode_ [private]
Definition at line 543 of file node-matchers.h.
Referenced by v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::displacement_mode(), and v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::Initialize().
index_
template<class AddMatcher >
Node* v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::index_ [private]
Definition at line 539 of file node-matchers.h.
Referenced by v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::index(), and v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::Initialize().
matches_
template<class AddMatcher >
bool v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::matches_ [private]
Definition at line 538 of file node-matchers.h.
Referenced by v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::Initialize(), and v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::matches().
scale_
template<class AddMatcher >
int v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::scale_ [private]
Definition at line 540 of file node-matchers.h.
Referenced by v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::Initialize(), and v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::scale().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/node-matchers.h