v8::internal::torque::CallBuiltinPointerInstruction Struct Reference
#include <instructions.h>
Public Member Functions
bool IsBlockTerminator () const override
CallBuiltinPointerInstruction (bool is_tailcall, const BuiltinPointerType *type, size_t argc)
std::size_t GetValueDefinitionCount () const
DefinitionLocation GetValueDefinition (std::size_t index) const
Public Attributes
bool is_tailcall
const BuiltinPointerType * type
size_t argc
Detailed Description
Definition at line 580 of file instructions.h.
Constructor & Destructor Documentation
CallBuiltinPointerInstruction()
v8::internal::torque::CallBuiltinPointerInstruction::CallBuiltinPointerInstruction (bool is_tailcall, const BuiltinPointerType * type, size_t argc) [inline]
Definition at line 583 of file instructions.h.
      : is_tailcall(is_tailcall), type(type), argc(argc) {}
Member Function Documentation
GetValueDefinition()
DefinitionLocation v8::internal::torque::CallBuiltinPointerInstruction::GetValueDefinition (std::size_t index) const
Definition at line 498 of file instructions.cc.
                           {
  DCHECK_LT(index, GetValueDefinitionCount());
  return DefinitionLocation::Instruction(this, index);
}
References DCHECK_LT, GetValueDefinitionCount(), v8::internal::index, and v8::internal::torque::DefinitionLocation::Instruction().
GetValueDefinitionCount()
std::size_t v8::internal::torque::CallBuiltinPointerInstruction::GetValueDefinitionCount () const
Definition at line 494 of file instructions.cc.
                                                                       {
  return LowerType(type->return_type()).size();
}
References v8::internal::torque::LowerType(), v8::internal::torque::BuiltinPointerType::return_type(), and type.
Referenced by GetValueDefinition().
IsBlockTerminator()
bool v8::internal::torque::CallBuiltinPointerInstruction::IsBlockTerminator () const [inline], [override], [virtual]
Reimplemented from v8::internal::torque::InstructionBase.
Definition at line 582 of file instructions.h.
{ return is_tailcall; }
References is_tailcall.
Member Data Documentation
argc
size_t v8::internal::torque::CallBuiltinPointerInstruction::argc
Definition at line 592 of file instructions.h.
Referenced by v8::internal::torque::operator<<().
is_tailcall
bool v8::internal::torque::CallBuiltinPointerInstruction::is_tailcall
Definition at line 590 of file instructions.h.
Referenced by IsBlockTerminator(), and v8::internal::torque::operator<<().
type
const BuiltinPointerType* v8::internal::torque::CallBuiltinPointerInstruction::type
Definition at line 591 of file instructions.h.
Referenced by GetValueDefinitionCount(), and v8::internal::torque::operator<<().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/torque/instructions.h
/mnt/V8SourceCode/src/torque/instructions.cc