v8::internal::compiler::turboshaft::ChangeOp Struct Reference
#include <operations.h>
Public Types
enum class Kind : uint8_t {
kFloatConversion
, kSignedFloatTruncateOverflowToMin
, kUnsignedFloatTruncateOverflowToMin
, kJSFloatTruncate
,
kJSFloat16TruncateWithBitcast
, kJSFloat16ChangeWithBitcast
, kSignedToFloat
, kUnsignedToFloat
,
kExtractHighHalf
, kExtractLowHalf
, kZeroExtend
, kSignExtend
,
kTruncate
, kBitcast
 }
enum class Assumption : uint8_t { kNoAssumption
, kNoOverflow
, kReversible
 }
Public Member Functions
bool IsReversibleBy (Kind reverse_kind, bool signalling_nan_possible) const
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
template<typename Type = Untagged>
requires IsUntagged< Type > V< Type > input () const
ChangeOp (V< Untagged > input, Kind kind, Assumption assumption, RegisterRepresentation from, RegisterRepresentation to)
void Validate (const Graph &graph) const
auto options () const
Static Public Member Functions
static bool IsReversible (Kind kind, Assumption assumption, RegisterRepresentation from, RegisterRepresentation to, Kind reverse_kind, bool signalling_nan_possible)
Public Attributes
Kind kind
Assumption assumption
RegisterRepresentation from
RegisterRepresentation to
Static Public Attributes
static constexpr OpEffects effects = OpEffects()
Additional Inherited Members
Detailed Description
Definition at line 2144 of file operations.h.
Member Enumeration Documentation
Assumption
enum v8::internal::compiler::turboshaft::ChangeOp::Assumption : uint8_t [strong]
Enumerator
kNoAssumption
kNoOverflow
kReversible
Definition at line 2177 of file operations.h.
                        : uint8_t {
    kNoAssumption,
    // Used for conversions from floating-point to integer, assumes that the
    // value doesn't exceed the integer range.
    kNoOverflow,
    // Assume that the original value can be recovered by a corresponding
    // reverse transformation.
    kReversible,
  };
Kind
enum v8::internal::compiler::turboshaft::ChangeOp::Kind : uint8_t [strong]
Enumerator
kFloatConversion
kSignedFloatTruncateOverflowToMin
kUnsignedFloatTruncateOverflowToMin
kJSFloatTruncate
kJSFloat16TruncateWithBitcast
kJSFloat16ChangeWithBitcast
kSignedToFloat
kUnsignedToFloat
kExtractHighHalf
kExtractLowHalf
kZeroExtend
kSignExtend
kTruncate
kBitcast
Definition at line 2145 of file operations.h.
                  : uint8_t {
    // convert between different floating-point types. Note that the
    // Float64->Float32 conversion is truncating.
    kFloatConversion,
    // overflow guaranteed to result in the minimal integer
    kSignedFloatTruncateOverflowToMin,
    kUnsignedFloatTruncateOverflowToMin,
    // JS semantics float64 to word32 truncation
    // https://tc39.es/ecma262/#sec-touint32
    kJSFloatTruncate,
    // convert float64 to float16, then bitcast word32. Used for storing into
    // Float16Array and Math.fround16.
    kJSFloat16TruncateWithBitcast,
    // bitcast word32 to float16 and convert to float64. Used for loading from
    // Float16Array and Math.fround16.
    kJSFloat16ChangeWithBitcast,
    // convert (un)signed integer to floating-point value
    kSignedToFloat,
    kUnsignedToFloat,
    // extract half of a float64 value
    kExtractHighHalf,
    kExtractLowHalf,
    // increase bit-width for unsigned integer values
    kZeroExtend,
    // increase bid-width for signed integer values
    kSignExtend,
    // truncate word64 to word32
    kTruncate,
    // preserve bits, change meaning
    kBitcast
  };
Constructor & Destructor Documentation
ChangeOp()
v8::internal::compiler::turboshaft::ChangeOp::ChangeOp (V< Untagged > input, Kind kind, Assumption assumption, RegisterRepresentation from, RegisterRepresentation to) [inline]
Definition at line 2277 of file operations.h.
      : Base(input), kind(kind), assumption(assumption), from(from), to(to) {}
Member Function Documentation
input()
template<typename Type = Untagged>
requires IsUntagged<Type> V<Type> v8::internal::compiler::turboshaft::ChangeOp::input () const [inline]
Definition at line 2272 of file operations.h.
                        {
    DCHECK(IsValidTypeFor<Type>(from));
    return Base::input<Type>(0);
  }
References v8::internal::DCHECK().
Referenced by v8::internal::compiler::turboshaft::InstructionSelectionNormalizationReducer< Next >::IsComplexConstant(), v8::internal::compiler::turboshaft::IsInt32TruncatedLoadPattern(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessChange(), and v8::internal::compiler::turboshaft::SLPTree::TryGetExtendIntToF32x4Info().
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::ChangeOp::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 2265 of file operations.h.
                                                              {
    return InputsRepFactory::SingleRep(from);
  }
References v8::internal::compiler::turboshaft::InputsRepFactory::SingleRep().
IsReversible()
static bool v8::internal::compiler::turboshaft::ChangeOp::IsReversible (Kind kind, Assumption assumption, RegisterRepresentation from, RegisterRepresentation to, Kind reverse_kind, bool signalling_nan_possible) [inline], [static]
Definition at line 2197 of file operations.h.
                                                         {
    switch (kind) {
      case Kind::kFloatConversion:
        return from == RegisterRepresentation::Float32() &&
               to == RegisterRepresentation::Float64() &&
               reverse_kind == Kind::kFloatConversion &&
               !signalling_nan_possible;
      case Kind::kSignedFloatTruncateOverflowToMin:
        return assumption == Assumption::kReversible &&
               reverse_kind == Kind::kSignedToFloat;
      case Kind::kUnsignedFloatTruncateOverflowToMin:
        return assumption == Assumption::kReversible &&
               reverse_kind == Kind::kUnsignedToFloat;
      case Kind::kJSFloatTruncate:
        return false;
      case Kind::kJSFloat16TruncateWithBitcast:
      case Kind::kJSFloat16ChangeWithBitcast:
        return false;
      case Kind::kSignedToFloat:
        if (from == RegisterRepresentation::Word32() &&
            to == RegisterRepresentation::Float64()) {
          return reverse_kind == any_of(Kind::kSignedFloatTruncateOverflowToMin,
                                        Kind::kJSFloatTruncate);
        } else {
          return assumption == Assumption::kReversible &&
                 reverse_kind ==
                     any_of(Kind::kSignedFloatTruncateOverflowToMin);
        }
      case Kind::kUnsignedToFloat:
        if (from == RegisterRepresentation::Word32() &&
            to == RegisterRepresentation::Float64()) {
          return reverse_kind ==
                 any_of(Kind::kUnsignedFloatTruncateOverflowToMin,
                        Kind::kJSFloatTruncate);
        } else {
          return assumption == Assumption::kReversible &&
                 reverse_kind == Kind::kUnsignedFloatTruncateOverflowToMin;
        }
      case Kind::kExtractHighHalf:
      case Kind::kExtractLowHalf:
        return false;
      case Kind::kZeroExtend:
      case Kind::kSignExtend:
        DCHECK_EQ(from, RegisterRepresentation::Word32());
        DCHECK_EQ(to, RegisterRepresentation::Word64());
        return reverse_kind == Kind::kTruncate;
      case Kind::kTruncate:
        DCHECK_EQ(from, RegisterRepresentation::Word64());
        DCHECK_EQ(to, RegisterRepresentation::Word32());
        return reverse_kind == Kind::kBitcast;
      case Kind::kBitcast:
        return reverse_kind == Kind::kBitcast;
    }
  }
References v8::base::any_of(), DCHECK_EQ, v8::internal::compiler::turboshaft::RegisterRepresentation::Float32(), v8::internal::compiler::turboshaft::RegisterRepresentation::Float64(), v8::internal::compiler::turboshaft::RegisterRepresentation::Word32(), and v8::internal::compiler::turboshaft::RegisterRepresentation::Word64().
IsReversibleBy()
bool v8::internal::compiler::turboshaft::ChangeOp::IsReversibleBy (Kind reverse_kind, bool signalling_nan_possible) const [inline]
Definition at line 2255 of file operations.h.
                                                                             {
    return IsReversible(kind, assumption, from, to, reverse_kind,
                        signalling_nan_possible);
  }
options()
auto v8::internal::compiler::turboshaft::ChangeOp::options () const [inline]
Definition at line 2288 of file operations.h.
{ return std::tuple{kind, assumption, from, to}; }
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::ChangeOp::outputs_rep () const [inline]
Definition at line 2261 of file operations.h.
                                                               {
    return base::VectorOf(&to, 1);
  }
References v8::base::VectorOf().
Validate()
void v8::internal::compiler::turboshaft::ChangeOp::Validate (const Graph & graph) const [inline]
Definition at line 2281 of file operations.h.
                                          {
    DCHECK_NE(from, RegisterRepresentation::Tagged());
    DCHECK_NE(to, RegisterRepresentation::Tagged());
    // Bitcasts from and to Tagged should use a TaggedBitcast instead (which has
    // different effects, since it's unsafe to reorder such bitcasts accross
    // GCs).
  }
References DCHECK_NE, and v8::internal::compiler::turboshaft::RegisterRepresentation::Tagged().
Member Data Documentation
assumption
Assumption v8::internal::compiler::turboshaft::ChangeOp::assumption
Definition at line 2189 of file operations.h.
Referenced by v8::internal::compiler::InstructionSelector::VisitNode().
effects
constexpr OpEffects v8::internal::compiler::turboshaft::ChangeOp::effects = OpEffects() [static], [constexpr]
Definition at line 2260 of file operations.h.
from
RegisterRepresentation v8::internal::compiler::turboshaft::ChangeOp::from
Definition at line 2190 of file operations.h.
Referenced by v8::internal::compiler::InstructionSelector::VisitNode().
kind
Kind v8::internal::compiler::turboshaft::ChangeOp::kind
Definition at line 2186 of file operations.h.
Referenced by v8::internal::compiler::turboshaft::SLPTree::TryGetExtendIntToF32x4Info(), and v8::internal::compiler::InstructionSelector::VisitNode().
to
RegisterRepresentation v8::internal::compiler::turboshaft::ChangeOp::to
Definition at line 2191 of file operations.h.
Referenced by v8::internal::compiler::InstructionSelector::VisitNode().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h