v8::internal::wasm::ModuleDecoderImpl::LimitsByte Struct Reference
Public Member Functions
bool is_valid () const
bool has_maximum () const
bool is_shared () const
bool is_64bit () const
AddressType address_type () const
Public Attributes
uint8_t flags
Detailed Description
Definition at line 2187 of file module-decoder-impl.h.
Member Function Documentation
address_type()
AddressType v8::internal::wasm::ModuleDecoderImpl::LimitsByte::address_type () const [inline]
Definition at line 2195 of file module-decoder-impl.h.
                                     {
      return is_64bit() ? AddressType::kI64 : AddressType::kI32;
    }
References is_64bit(), v8::internal::wasm::kI32, and v8::internal::wasm::kI64.
Referenced by v8::internal::wasm::ModuleDecoderImpl::consume_memory_flags(), and v8::internal::wasm::ModuleDecoderImpl::consume_table_flags().
has_maximum()
bool v8::internal::wasm::ModuleDecoderImpl::LimitsByte::has_maximum () const [inline]
Definition at line 2192 of file module-decoder-impl.h.
{ return flags & 0x1; }
References flags.
Referenced by v8::internal::wasm::ModuleDecoderImpl::consume_memory_flags(), and v8::internal::wasm::ModuleDecoderImpl::consume_table_flags().
is_64bit()
bool v8::internal::wasm::ModuleDecoderImpl::LimitsByte::is_64bit () const [inline]
Definition at line 2194 of file module-decoder-impl.h.
{ return flags & 0x4; }
References flags.
Referenced by address_type().
is_shared()
bool v8::internal::wasm::ModuleDecoderImpl::LimitsByte::is_shared () const [inline]
Definition at line 2193 of file module-decoder-impl.h.
{ return flags & 0x2; }
References flags.
Referenced by v8::internal::wasm::ModuleDecoderImpl::consume_memory_flags(), and v8::internal::wasm::ModuleDecoderImpl::consume_table_flags().
is_valid()
bool v8::internal::wasm::ModuleDecoderImpl::LimitsByte::is_valid () const [inline]
Definition at line 2191 of file module-decoder-impl.h.
{ return (flags & ~0x7) == 0; }
References flags.
Member Data Documentation
flags
uint8_t v8::internal::wasm::ModuleDecoderImpl::LimitsByte::flags
Definition at line 2188 of file module-decoder-impl.h.
Referenced by has_maximum(), is_64bit(), is_shared(), and is_valid().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/wasm/module-decoder-impl.h