v8::internal::anonymous_namespace{debug-wasm-objects.cc}::FunctionsProxy Struct Reference
Static Public Member Functions
static uint32_t Count (Isolate *isolate, DirectHandle< WasmInstanceObject > instance)
static DirectHandle< Object > Get (Isolate *isolate, DirectHandle< WasmInstanceObject > instance, uint32_t index)
static DirectHandle< String > GetName (Isolate *isolate, DirectHandle< WasmInstanceObject > instance, uint32_t index)
Static Public Attributes
static constexpr char const * kClassName = `Functions`
Additional Inherited Members
Detailed Description
Definition at line 297 of file debug-wasm-objects.cc.
Member Function Documentation
Count()
static uint32_t v8::internal::anonymous_namespace{debug-wasm-objects.cc}::FunctionsProxy::Count (Isolate * isolate, DirectHandle< WasmInstanceObject > instance) [inline], [static]
Definition at line 300 of file debug-wasm-objects.cc.
                                                                   {
    return static_cast<uint32_t>(instance->module()->functions.size());
  }
Get()
static DirectHandle<Object> v8::internal::anonymous_namespace{debug-wasm-objects.cc}::FunctionsProxy::Get (Isolate * isolate, DirectHandle< WasmInstanceObject > instance, uint32_t index) [inline], [static]
Definition at line 305 of file debug-wasm-objects.cc.
                                                  {
    DirectHandle<WasmTrustedInstanceData> trusted_data{
        instance->trusted_data(isolate), isolate};
    DirectHandle<WasmFuncRef> func_ref =
        WasmTrustedInstanceData::GetOrCreateFuncRef(isolate, trusted_data,
                                                    index);
    DirectHandle<WasmInternalFunction> internal_function{
        func_ref->internal(isolate), isolate};
    return WasmInternalFunction::GetOrCreateExternal(internal_function);
  }
References v8::internal::WasmInternalFunction::GetOrCreateExternal(), v8::internal::WasmTrustedInstanceData::GetOrCreateFuncRef(), and v8::internal::index.
GetName()
static DirectHandle<String> v8::internal::anonymous_namespace{debug-wasm-objects.cc}::FunctionsProxy::GetName (Isolate * isolate, DirectHandle< WasmInstanceObject > instance, uint32_t index) [inline], [static]
Definition at line 318 of file debug-wasm-objects.cc.
                                                      {
    i::DirectHandle<i::WasmTrustedInstanceData> instance_data{
        instance->trusted_data(isolate), isolate};
    return GetWasmFunctionDebugName(isolate, instance_data, index);
  }
References v8::internal::GetWasmFunctionDebugName(), v8::internal::index, and v8::internal::instance_data.
Member Data Documentation
kClassName
constexpr char const* v8::internal::anonymous_namespace{debug-wasm-objects.cc}::FunctionsProxy::kClassName = `Functions` [static], [constexpr]
Definition at line 298 of file debug-wasm-objects.cc.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/debug/debug-wasm-objects.cc