v8::internal::compiler::turboshaft::FrameStateOp Struct Reference
#include <operations.h>
Public Member Functions
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
V< FrameState > parent_frame_state () const
base::Vector< const OpIndex > state_values () const
uint16_t state_values_count () const
const OpIndex state_value (size_t idx) const
RegisterRepresentation state_value_rep (size_t idx) const
FrameStateOp (base::Vector< const OpIndex > inputs, bool inlined, const FrameStateData *data)
template<typename Fn , typename Mapper >
auto Explode (Fn fn, Mapper &mapper) const
size_t hash_value (HashingStrategy strategy=HashingStrategy::kDefault) const
V8_EXPORT_PRIVATE void Validate (const Graph &graph) const
V8_EXPORT_PRIVATE void PrintOptions (std::ostream &os) const
auto options () const
Public Attributes
bool inlined
const FrameStateData * data
Static Public Attributes
static constexpr OpEffects effects = OpEffects()
Additional Inherited Members
Detailed Description
Definition at line 3741 of file operations.h.
Constructor & Destructor Documentation
FrameStateOp()
v8::internal::compiler::turboshaft::FrameStateOp::FrameStateOp (base::Vector< const OpIndex > inputs, bool inlined, const FrameStateData * data) [inline]
Definition at line 3773 of file operations.h.
      : Base(inputs), inlined(inlined), data(data) {}
Member Function Documentation
Explode()
template<typename Fn , typename Mapper >
auto v8::internal::compiler::turboshaft::FrameStateOp::Explode (Fn fn, Mapper & mapper) const [inline]
Definition at line 3778 of file operations.h.
                                                      {
    auto mapped_inputs = mapper.template Map<32>(inputs());
    return fn(base::VectorOf(mapped_inputs), inlined, data);
  }
References v8::base::VectorOf().
hash_value()
size_t v8::internal::compiler::turboshaft::FrameStateOp::hash_value (HashingStrategy strategy = HashingStrategy::kDefault) const [inline]
Definition at line 3783 of file operations.h.
                                                                {
    // Computing the full hash of {data} would be a bit slow, so we just use the
    // `bailout_id` and `inlined` (+ the inputs) to get a quick hash (and rely
    // on the == operator to properly check later if 2 FrameStateOp with the
    // same hash are really equal)
    return HashWithOptions(inlined, data->frame_state_info.bailout_id());
  }
References v8::internal::compiler::FrameStateInfo::bailout_id(), and v8::internal::compiler::turboshaft::FrameStateData::frame_state_info.
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::FrameStateOp::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 3748 of file operations.h.
                                                              {
    return {};
  }
options()
auto v8::internal::compiler::turboshaft::FrameStateOp::options () const [inline]
Definition at line 3794 of file operations.h.
{ return std::tuple{inlined, *data}; }
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::FrameStateOp::outputs_rep () const [inline]
Definition at line 3746 of file operations.h.
{ return {}; }
parent_frame_state()
V<FrameState> v8::internal::compiler::turboshaft::FrameStateOp::parent_frame_state () const [inline]
Definition at line 3753 of file operations.h.
                                           {
    DCHECK(inlined);
    return input<FrameState>(0);
  }
References v8::internal::DCHECK().
Referenced by v8::internal::compiler::InstructionSelector::AddInputsToFrameStateDescriptor(), v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::BuildFrameState(), v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::GetFrameStateDescriptorInternal(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::MergeFrameState(), v8::internal::compiler::turboshaft::StringEscapeAnalyzer::RecursiveMarkAsShouldReconstruct(), and Validate().
PrintOptions()
void v8::internal::compiler::turboshaft::FrameStateOp::PrintOptions (std::ostream & os) const
Definition at line 740 of file operations.cc.
                                                    {
  os << '[';
  os << (inlined ? "inlined" : "not inlined");
  os << ", ";
  os << data->frame_state_info;
  os << ", state values:";
  FrameStateData::Iterator it = data->iterator(state_values());
  while (it.has_more()) {
    os << ' ';
    switch (it.current_instr()) {
      case FrameStateData::Instr::kInput: {
        MachineType type;
        OpIndex input;
        it.ConsumeInput(&type, &input);
        os << '#' << input.id() << '(' << type << ')';
        break;
      }
      case FrameStateData::Instr::kUnusedRegister:
        it.ConsumeUnusedRegister();
        os << '.';
        break;
      case FrameStateData::Instr::kDematerializedObject: {
        uint32_t id;
        uint32_t field_count;
        it.ConsumeDematerializedObject(&id, &field_count);
        os << '$' << id << "(field count: " << field_count << ')';
        break;
      }
      case FrameStateData::Instr::kDematerializedObjectReference: {
        uint32_t id;
        it.ConsumeDematerializedObjectReference(&id);
        os << '$' << id;
        break;
      }
      case FrameStateData::Instr::kDematerializedStringConcat: {
        uint32_t id;
        it.ConsumeDematerializedStringConcat(&id);
        os << "£" << id << "DematerializedStringConcat";
        break;
      }
      case FrameStateData::Instr::kDematerializedStringConcatReference: {
        uint32_t id;
        it.ConsumeDematerializedStringConcatReference(&id);
        os << "£" << id;
        break;
      }
      case FrameStateData::Instr::kArgumentsElements: {
        CreateArgumentsType type;
        it.ConsumeArgumentsElements(&type);
        os << "ArgumentsElements(" << type << ')';
        break;
      }
      case FrameStateData::Instr::kArgumentsLength: {
        it.ConsumeArgumentsLength();
        os << "ArgumentsLength";
        break;
      }
      case FrameStateData::Instr::kRestLength: {
        it.ConsumeRestLength();
        os << "RestLength";
        break;
      }
    }
  }
  os << ']';
}
References v8::internal::compiler::turboshaft::FrameStateData::Iterator::ConsumeArgumentsElements(), v8::internal::compiler::turboshaft::FrameStateData::Iterator::ConsumeArgumentsLength(), v8::internal::compiler::turboshaft::FrameStateData::Iterator::ConsumeDematerializedObject(), v8::internal::compiler::turboshaft::FrameStateData::Iterator::ConsumeDematerializedObjectReference(), v8::internal::compiler::turboshaft::FrameStateData::Iterator::ConsumeDematerializedStringConcat(), v8::internal::compiler::turboshaft::FrameStateData::Iterator::ConsumeDematerializedStringConcatReference(), v8::internal::compiler::turboshaft::FrameStateData::Iterator::ConsumeInput(), v8::internal::compiler::turboshaft::FrameStateData::Iterator::ConsumeRestLength(), v8::internal::compiler::turboshaft::FrameStateData::Iterator::ConsumeUnusedRegister(), v8::internal::compiler::turboshaft::FrameStateData::Iterator::current_instr(), data, v8::internal::compiler::turboshaft::FrameStateData::frame_state_info, v8::internal::compiler::turboshaft::FrameStateData::Iterator::has_more(), v8::internal::compiler::turboshaft::OpIndex::id(), inlined, v8::internal::compiler::turboshaft::OperationT< FrameStateOp >::input(), v8::internal::compiler::turboshaft::FrameStateData::iterator(), v8::internal::compiler::turboshaft::FrameStateData::kArgumentsElements, v8::internal::compiler::turboshaft::FrameStateData::kArgumentsLength, v8::internal::compiler::turboshaft::FrameStateData::kDematerializedObject, v8::internal::compiler::turboshaft::FrameStateData::kDematerializedObjectReference, v8::internal::compiler::turboshaft::FrameStateData::kDematerializedStringConcat, v8::internal::compiler::turboshaft::FrameStateData::kDematerializedStringConcatReference, v8::internal::compiler::turboshaft::FrameStateData::kInput, v8::internal::compiler::turboshaft::FrameStateData::kRestLength, v8::internal::compiler::turboshaft::FrameStateData::kUnusedRegister, state_values(), and v8::internal::tracing::type.
state_value()
const OpIndex v8::internal::compiler::turboshaft::FrameStateOp::state_value (size_t idx) const [inline]
Definition at line 3766 of file operations.h.
{ return state_values()[idx]; }
Referenced by v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::MergeFrameState().
state_value_rep()
RegisterRepresentation v8::internal::compiler::turboshaft::FrameStateOp::state_value_rep (size_t idx) const [inline]
Definition at line 3768 of file operations.h.
                                                           {
    return RegisterRepresentation::FromMachineRepresentation(
        data->machine_types[idx].representation());
  }
References v8::internal::compiler::turboshaft::RegisterRepresentation::FromMachineRepresentation(), and v8::internal::compiler::turboshaft::FrameStateData::machine_types.
Referenced by v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::MergeFrameState().
state_values()
base::Vector<const OpIndex> v8::internal::compiler::turboshaft::FrameStateOp::state_values () const [inline]
Definition at line 3757 of file operations.h.
                                                 {
    base::Vector<const OpIndex> result = inputs();
    if (inlined) result += 1;
    return result;
  }
References v8::base::internal::result.
Referenced by v8::internal::compiler::InstructionSelector::AddInputsToFrameStateDescriptor(), v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::BuildFrameState(), PrintOptions(), v8::internal::compiler::turboshaft::StringEscapeAnalyzer::ProcessFrameState(), and Validate().
state_values_count()
uint16_t v8::internal::compiler::turboshaft::FrameStateOp::state_values_count () const [inline]
Definition at line 3762 of file operations.h.
                                      {
    DCHECK_EQ(input_count - inlined, state_values().size());
    return input_count - inlined;
  }
References DCHECK_EQ, v8::internal::compiler::turboshaft::detail::input_count(), and size().
Referenced by v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::MergeFrameState().
Validate()
void v8::internal::compiler::turboshaft::FrameStateOp::Validate (const Graph & graph) const
Definition at line 807 of file operations.cc.
                                                    {
  if (inlined) {
    DCHECK(Get(graph, parent_frame_state()).Is<FrameStateOp>());
  }
  FrameStateData::Iterator it = data->iterator(state_values());
  while (it.has_more()) {
    switch (it.current_instr()) {
      case FrameStateData::Instr::kInput: {
        MachineType type;
        OpIndex input;
        it.ConsumeInput(&type, &input);
        RegisterRepresentation rep =
            RegisterRepresentation::FromMachineRepresentation(
                type.representation());
        if (rep == RegisterRepresentation::Tagged()) {
          // The deoptimizer can handle compressed values.
          rep = RegisterRepresentation::Compressed();
        }
#ifdef DEBUG
        ValidateOpInputRep(graph, input, rep);
#endif // DEBUG
        break;
      }
      case FrameStateData::Instr::kUnusedRegister:
        it.ConsumeUnusedRegister();
        break;
      case FrameStateData::Instr::kDematerializedObject: {
        uint32_t id;
        uint32_t field_count;
        it.ConsumeDematerializedObject(&id, &field_count);
        break;
      }
      case FrameStateData::Instr::kDematerializedObjectReference: {
        uint32_t id;
        it.ConsumeDematerializedObjectReference(&id);
        break;
      }
      case FrameStateData::Instr::kDematerializedStringConcat: {
        uint32_t id;
        it.ConsumeDematerializedStringConcat(&id);
        break;
      }
      case FrameStateData::Instr::kDematerializedStringConcatReference: {
        uint32_t id;
        it.ConsumeDematerializedStringConcatReference(&id);
        break;
      }
      case FrameStateData::Instr::kArgumentsElements: {
        CreateArgumentsType type;
        it.ConsumeArgumentsElements(&type);
        break;
      }
      case FrameStateData::Instr::kArgumentsLength: {
        it.ConsumeArgumentsLength();
        break;
      }
      case FrameStateData::Instr::kRestLength: {
        it.ConsumeRestLength();
        break;
      }
    }
  }
}
References v8::internal::compiler::turboshaft::RegisterRepresentation::Compressed(), v8::internal::compiler::turboshaft::FrameStateData::Iterator::ConsumeArgumentsElements(), v8::internal::compiler::turboshaft::FrameStateData::Iterator::ConsumeArgumentsLength(), v8::internal::compiler::turboshaft::FrameStateData::Iterator::ConsumeDematerializedObject(), v8::internal::compiler::turboshaft::FrameStateData::Iterator::ConsumeDematerializedObjectReference(), v8::internal::compiler::turboshaft::FrameStateData::Iterator::ConsumeDematerializedStringConcat(), v8::internal::compiler::turboshaft::FrameStateData::Iterator::ConsumeDematerializedStringConcatReference(), v8::internal::compiler::turboshaft::FrameStateData::Iterator::ConsumeInput(), v8::internal::compiler::turboshaft::FrameStateData::Iterator::ConsumeRestLength(), v8::internal::compiler::turboshaft::FrameStateData::Iterator::ConsumeUnusedRegister(), v8::internal::compiler::turboshaft::FrameStateData::Iterator::current_instr(), data, v8::internal::DCHECK(), v8::internal::compiler::turboshaft::RegisterRepresentation::FromMachineRepresentation(), v8::internal::compiler::turboshaft::Get(), graph(), v8::internal::compiler::turboshaft::FrameStateData::Iterator::has_more(), inlined, v8::internal::compiler::turboshaft::OperationT< FrameStateOp >::input(), v8::internal::compiler::turboshaft::FrameStateData::iterator(), v8::internal::compiler::turboshaft::FrameStateData::kArgumentsElements, v8::internal::compiler::turboshaft::FrameStateData::kArgumentsLength, v8::internal::compiler::turboshaft::FrameStateData::kDematerializedObject, v8::internal::compiler::turboshaft::FrameStateData::kDematerializedObjectReference, v8::internal::compiler::turboshaft::FrameStateData::kDematerializedStringConcat, v8::internal::compiler::turboshaft::FrameStateData::kDematerializedStringConcatReference, v8::internal::compiler::turboshaft::FrameStateData::kInput, v8::internal::compiler::turboshaft::FrameStateData::kRestLength, v8::internal::compiler::turboshaft::FrameStateData::kUnusedRegister, parent_frame_state(), state_values(), v8::internal::compiler::turboshaft::RegisterRepresentation::Tagged(), and v8::internal::tracing::type.
Member Data Documentation
data
const FrameStateData* v8::internal::compiler::turboshaft::FrameStateOp::data
Definition at line 3743 of file operations.h.
Referenced by v8::internal::compiler::InstructionSelector::AddInputsToFrameStateDescriptor(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphFrameState(), v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::BuildFrameState(), v8::internal::compiler::turboshaft::WasmJSLoweringReducer< Next >::CreateFrameStateWithUpdatedBailoutId(), v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::GetFrameStateDescriptorInternal(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::MergeFrameState(), PrintOptions(), v8::internal::compiler::turboshaft::StringEscapeAnalyzer::ProcessFrameState(), and Validate().
effects
constexpr OpEffects v8::internal::compiler::turboshaft::FrameStateOp::effects = OpEffects() [static], [constexpr]
Definition at line 3745 of file operations.h.
inlined
bool v8::internal::compiler::turboshaft::FrameStateOp::inlined
Definition at line 3742 of file operations.h.
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphFrameState(), v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::BuildFrameState(), v8::internal::compiler::turboshaft::WasmJSLoweringReducer< Next >::CreateFrameStateWithUpdatedBailoutId(), v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::GetFrameStateDescriptorInternal(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::MergeFrameState(), PrintOptions(), v8::internal::compiler::turboshaft::StringEscapeAnalyzer::RecursiveMarkAsShouldReconstruct(), and Validate().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h
/mnt/V8SourceCode/src/compiler/turboshaft/operations.cc