v8::internal::wasm::TypeCanonicalizer::CanonicalEquality Struct Reference
Public Member Functions
CanonicalEquality (RecursionGroupRange recgroup1, RecursionGroupRange recgroup2)
bool EqualTypeIndex (CanonicalTypeIndex index1, CanonicalTypeIndex index2) const
bool EqualType (const CanonicalType &type1, const CanonicalType &type2) const
bool EqualTypes (base::Vector< const CanonicalType > types1, base::Vector< const CanonicalType > types2) const
bool EqualValueType (CanonicalValueType type1, CanonicalValueType type2) const
bool EqualSig (const CanonicalSig &sig1, const CanonicalSig &sig2) const
bool EqualStructType (const CanonicalStructType &type1, const CanonicalStructType &type2) const
bool EqualArrayType (const CanonicalArrayType &type1, const CanonicalArrayType &type2) const
bool EqualContType (const CanonicalContType &type1, const CanonicalContType &type2) const
Public Attributes
const RecursionGroupRange recgroup1
const RecursionGroupRange recgroup2
Detailed Description
Definition at line 303 of file canonical-types.h.
Constructor & Destructor Documentation
CanonicalEquality()
v8::internal::wasm::TypeCanonicalizer::CanonicalEquality::CanonicalEquality (RecursionGroupRange recgroup1, RecursionGroupRange recgroup2) [inline]
Definition at line 308 of file canonical-types.h.
        : recgroup1{recgroup1}, recgroup2{recgroup2} {}
Member Function Documentation
EqualArrayType()
bool v8::internal::wasm::TypeCanonicalizer::CanonicalEquality::EqualArrayType (const CanonicalArrayType & type1, const CanonicalArrayType & type2) const [inline]
Definition at line 389 of file canonical-types.h.
                                                               {
      return type1.mutability() == type2.mutability() &&
             EqualValueType(type1.element_type(), type2.element_type());
    }
References v8::internal::wasm::CanonicalArrayType::element_type(), EqualValueType(), and v8::internal::wasm::ArrayTypeBase::mutability().
Referenced by EqualType().
EqualContType()
bool v8::internal::wasm::TypeCanonicalizer::CanonicalEquality::EqualContType (const CanonicalContType & type1, const CanonicalContType & type2) const [inline]
Definition at line 395 of file canonical-types.h.
                                                             {
      return EqualTypeIndex(type1.contfun_typeindex(),
                            type2.contfun_typeindex());
    }
References v8::internal::wasm::CanonicalContType::contfun_typeindex(), and EqualTypeIndex().
Referenced by EqualType().
EqualSig()
bool v8::internal::wasm::TypeCanonicalizer::CanonicalEquality::EqualSig (const CanonicalSig & sig1, const CanonicalSig & sig2) const [inline]
Definition at line 368 of file canonical-types.h.
                                                                            {
      if (sig1.parameter_count() != sig2.parameter_count()) return false;
      return std::equal(
          sig1.all().begin(), sig1.all().end(), sig2.all().begin(),
          sig2.all().end(),
          std::bind_front(&CanonicalEquality::EqualValueType, this));
    }
References v8::internal::Signature< T >::all(), v8::internal::equal, EqualValueType(), and v8::internal::Signature< T >::parameter_count().
Referenced by EqualType().
EqualStructType()
bool v8::internal::wasm::TypeCanonicalizer::CanonicalEquality::EqualStructType (const CanonicalStructType & type1, const CanonicalStructType & type2) const [inline]
Definition at line 376 of file canonical-types.h.
                                                                 {
      return
          // Compare fields, including a check that the size is the same.
          std::equal(
              type1.fields().begin(), type1.fields().end(),
              type2.fields().begin(), type2.fields().end(),
              std::bind_front(&CanonicalEquality::EqualValueType, this)) &&
          // Compare mutabilities, skipping the check for the size.
          std::equal(type1.mutabilities().begin(), type1.mutabilities().end(),
                     type2.mutabilities().begin());
    }
References v8::internal::equal, EqualValueType(), v8::internal::wasm::CanonicalStructType::fields(), and v8::internal::wasm::StructTypeBase::mutabilities().
Referenced by EqualType().
EqualType()
bool v8::internal::wasm::TypeCanonicalizer::CanonicalEquality::EqualType (const CanonicalType & type1, const CanonicalType & type2) const [inline]
Definition at line 327 of file canonical-types.h.
                                                     {
      if (!EqualTypeIndex(type1.supertype, type2.supertype)) return false;
      if (type1.is_final != type2.is_final) return false;
      if (type1.is_shared != type2.is_shared) return false;
      switch (type1.kind) {
        case CanonicalType::kFunction:
          return type2.kind == CanonicalType::kFunction &&
                 EqualSig(*type1.function_sig, *type2.function_sig);
        case CanonicalType::kStruct:
          return type2.kind == CanonicalType::kStruct &&
                 EqualTypeIndex(type1.descriptor, type2.descriptor) &&
                 EqualTypeIndex(type1.describes, type2.describes) &&
                 EqualStructType(*type1.struct_type, *type2.struct_type);
        case CanonicalType::kArray:
          return type2.kind == CanonicalType::kArray &&
                 EqualArrayType(*type1.array_type, *type2.array_type);
        case CanonicalType::kCont:
          return type2.kind == CanonicalType::kCont &&
                 EqualContType(*type1.cont_type, *type2.cont_type);
      }
    }
References v8::internal::wasm::TypeCanonicalizer::CanonicalType::array_type, v8::internal::wasm::TypeCanonicalizer::CanonicalType::cont_type, v8::internal::wasm::TypeCanonicalizer::CanonicalType::describes, v8::internal::wasm::TypeCanonicalizer::CanonicalType::descriptor, EqualArrayType(), EqualContType(), EqualSig(), EqualStructType(), EqualTypeIndex(), v8::internal::wasm::TypeCanonicalizer::CanonicalType::function_sig, v8::internal::wasm::TypeCanonicalizer::CanonicalType::is_final, v8::internal::wasm::TypeCanonicalizer::CanonicalType::is_shared, v8::internal::wasm::TypeCanonicalizer::CanonicalType::kArray, v8::internal::wasm::TypeCanonicalizer::CanonicalType::kCont, v8::internal::wasm::TypeCanonicalizer::CanonicalType::kFunction, v8::internal::wasm::TypeCanonicalizer::CanonicalType::kind, v8::internal::wasm::TypeCanonicalizer::CanonicalType::kStruct, v8::internal::wasm::TypeCanonicalizer::CanonicalType::struct_type, and v8::internal::wasm::TypeCanonicalizer::CanonicalType::supertype.
Referenced by EqualTypes().
EqualTypeIndex()
bool v8::internal::wasm::TypeCanonicalizer::CanonicalEquality::EqualTypeIndex (CanonicalTypeIndex index1, CanonicalTypeIndex index2) const [inline]
Definition at line 312 of file canonical-types.h.
                                                         {
      const bool relative_index = recgroup1.Contains(index1);
      if (relative_index != recgroup2.Contains(index2)) return false;
      if (relative_index) {
        // Compare relative type indexes within the respective recgroups.
        uint32_t rel_type1 = index1.index - recgroup1.first.index;
        uint32_t rel_type2 = index2.index - recgroup2.first.index;
        if (rel_type1 != rel_type2) return false;
      } else if (index1 != index2) {
        return false;
      }
      return true;
    }
References v8::internal::wasm::TypeCanonicalizer::RecursionGroupRange::Contains(), v8::internal::wasm::TypeCanonicalizer::RecursionGroupRange::first, v8::internal::wasm::TypeIndex::index, recgroup1, and recgroup2.
Referenced by EqualContType(), EqualType(), and EqualValueType().
EqualTypes()
bool v8::internal::wasm::TypeCanonicalizer::CanonicalEquality::EqualTypes (base::Vector< const CanonicalType > types1, base::Vector< const CanonicalType > types2) const [inline]
Definition at line 350 of file canonical-types.h.
                                                                  {
      return std::equal(types1.begin(), types1.end(), types2.begin(),
                        types2.end(),
                        std::bind_front(&CanonicalEquality::EqualType, this));
    }
References v8::base::Vector< T >::begin(), v8::base::Vector< T >::end(), v8::internal::equal, and EqualType().
EqualValueType()
bool v8::internal::wasm::TypeCanonicalizer::CanonicalEquality::EqualValueType (CanonicalValueType type1, CanonicalValueType type2) const [inline]
Definition at line 357 of file canonical-types.h.
                                                        {
      const bool indexed = type1.has_index();
      if (indexed != type2.has_index()) return false;
      if (indexed) {
        return type1.is_equal_except_index(type2) &&
               EqualTypeIndex(type1.ref_index(), type2.ref_index());
      }
      return type1 == type2;
    }
References EqualTypeIndex(), v8::internal::wasm::ValueTypeBase::has_index(), v8::internal::wasm::CanonicalValueType::is_equal_except_index(), and v8::internal::wasm::CanonicalValueType::ref_index().
Referenced by EqualArrayType(), EqualSig(), and EqualStructType().
Member Data Documentation
recgroup1
const RecursionGroupRange v8::internal::wasm::TypeCanonicalizer::CanonicalEquality::recgroup1
Definition at line 305 of file canonical-types.h.
Referenced by EqualTypeIndex().
recgroup2
const RecursionGroupRange v8::internal::wasm::TypeCanonicalizer::CanonicalEquality::recgroup2
Definition at line 306 of file canonical-types.h.
Referenced by EqualTypeIndex().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/wasm/canonical-types.h