v8::internal::WeakListVisitor< Context > Struct Reference
Static Public Member Functions
static void SetWeakNext (Tagged< Context > context, Tagged< HeapObject > next)
static Tagged< Object > WeakNext (Tagged< Context > context)
static Tagged< HeapObject > WeakNextHolder (Tagged< Context > context)
static int WeakNextOffset ()
static void VisitLiveObject (Heap *heap, Tagged< Context > context, WeakObjectRetainer *retainer)
template<class T >
static void DoWeakList (Heap *heap, Tagged< Context > context, WeakObjectRetainer *retainer, int index)
static void VisitPhantomObject (Heap *heap, Tagged< Context > context)
Detailed Description
Definition at line 91 of file heap-visitor.cc.
Member Function Documentation
DoWeakList()
template<class T >
static void v8::internal::WeakListVisitor< Context >::DoWeakList (Heap * heap, Tagged< Context > context, WeakObjectRetainer * retainer, int index) [inline], [static]
Definition at line 122 of file heap-visitor.cc.
                                                                  {
    // Visit the weak list, removing dead intermediate elements.
    Tagged<Object> list_head =
        VisitWeakList<T>(heap, context->GetNoCell(index), retainer);
    // Update the list head.
    context->SetNoCell(index, list_head, UPDATE_WRITE_BARRIER);
    if (MustRecordSlots(heap)) {
      // Record the updated slot if necessary.
      ObjectSlot head_slot = context->RawField(FixedArray::SizeFor(index));
      heap->mark_compact_collector()->RecordSlot(context, head_slot,
                                                 Cast<HeapObject>(list_head));
    }
  }
References v8::internal::index, v8::internal::MustRecordSlots(), v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::SizeFor(), and v8::internal::UPDATE_WRITE_BARRIER.
SetWeakNext()
static void v8::internal::WeakListVisitor< Context >::SetWeakNext (Tagged< Context > context, Tagged< HeapObject > next) [inline], [static]
Definition at line 92 of file heap-visitor.cc.
                                                                            {
    context->SetNoCell(Context::NEXT_CONTEXT_LINK, next, UPDATE_WRITE_BARRIER);
  }
References v8::internal::Context::NEXT_CONTEXT_LINK, and v8::internal::UPDATE_WRITE_BARRIER.
VisitLiveObject()
static void v8::internal::WeakListVisitor< Context >::VisitLiveObject (Heap * heap, Tagged< Context > context, WeakObjectRetainer * retainer) [inline], [static]
Definition at line 108 of file heap-visitor.cc.
                                                            {
    if (heap->gc_state() == Heap::MARK_COMPACT) {
      // Record the slots of the weak entries in the native context.
      for (int idx = Context::FIRST_WEAK_SLOT;
           idx < Context::NATIVE_CONTEXT_SLOTS; ++idx) {
        ObjectSlot slot = context->RawField(Context::OffsetOfElementAt(idx));
        MarkCompactCollector::RecordSlot(context, slot,
                                         Cast<HeapObject>(*slot));
      }
    }
  }
References v8::internal::Context::FIRST_WEAK_SLOT, v8::internal::Heap::MARK_COMPACT, v8::internal::Context::NATIVE_CONTEXT_SLOTS, v8::internal::Context::OffsetOfElementAt(), and v8::internal::MarkCompactCollector::RecordSlot().
VisitPhantomObject()
static void v8::internal::WeakListVisitor< Context >::VisitPhantomObject (Heap * heap, Tagged< Context > context) [inline], [static]
Definition at line 139 of file heap-visitor.cc.
{}
WeakNext()
static Tagged<Object> v8::internal::WeakListVisitor< Context >::WeakNext (Tagged< Context > context) [inline], [static]
Definition at line 96 of file heap-visitor.cc.
                                                          {
    return context->next_context_link();
  }
WeakNextHolder()
static Tagged<HeapObject> v8::internal::WeakListVisitor< Context >::WeakNextHolder (Tagged< Context > context) [inline], [static]
Definition at line 100 of file heap-visitor.cc.
                                                                    {
    return context;
  }
WeakNextOffset()
static int v8::internal::WeakListVisitor< Context >::WeakNextOffset () [inline], [static]
Definition at line 104 of file heap-visitor.cc.
                              {
    return FixedArray::SizeFor(Context::NEXT_CONTEXT_LINK);
  }
References v8::internal::Context::NEXT_CONTEXT_LINK, and v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::SizeFor().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/heap/heap-visitor.cc