v8::internal::ParserFormalParameters::Parameter Struct Reference
#include <parser.h>
Public Member Functions
Parameter (Expression *pattern, Expression *initializer, int position, int initializer_end_position, bool is_rest)
Expression * initializer () const
bool is_rest () const
bool is_simple () const
const AstRawString * name () const
Parameter ** next ()
Parameter *const * next () const
Public Attributes
base::PointerWithPayload< Expression, bool, 1 > initializer_and_is_rest
Expression * pattern
int position
int initializer_end_position
Parameter * next_parameter = nullptr
Detailed Description
Definition at line 46 of file parser.h.
Constructor & Destructor Documentation
Parameter()
v8::internal::ParserFormalParameters::Parameter::Parameter (Expression * pattern, Expression * initializer, int position, int initializer_end_position, bool is_rest) [inline]
Definition at line 47 of file parser.h.
        : initializer_and_is_rest(initializer, is_rest),
          pattern(pattern),
          position(position),
          initializer_end_position(initializer_end_position) {}
Member Function Documentation
initializer()
Expression* v8::internal::ParserFormalParameters::Parameter::initializer () const [inline]
Definition at line 57 of file parser.h.
                                    {
      return initializer_and_is_rest.GetPointer();
    }
References initializer_and_is_rest.
Referenced by is_simple().
is_rest()
bool v8::internal::ParserFormalParameters::Parameter::is_rest () const [inline]
Definition at line 62 of file parser.h.
{ return initializer_and_is_rest.GetPayload(); }
References initializer_and_is_rest.
Referenced by is_simple().
is_simple()
bool v8::internal::ParserFormalParameters::Parameter::is_simple () const [inline]
Definition at line 65 of file parser.h.
                           {
      return pattern->IsVariableProxy() && initializer() == nullptr &&
             !is_rest();
    }
References initializer(), is_rest(), and pattern.
Referenced by name().
name()
const AstRawString* v8::internal::ParserFormalParameters::Parameter::name () const [inline]
Definition at line 70 of file parser.h.
                                     {
      DCHECK(is_simple());
      return pattern->AsVariableProxy()->raw_name();
    }
References v8::internal::DCHECK(), is_simple(), and pattern.
next() [1/2]
Parameter** v8::internal::ParserFormalParameters::Parameter::next () [inline]
Definition at line 75 of file parser.h.
{ return &next_parameter; }
References next_parameter.
next() [2/2]
Parameter* const* v8::internal::ParserFormalParameters::Parameter::next () const [inline]
Definition at line 76 of file parser.h.
{ return &next_parameter; }
References next_parameter.
Member Data Documentation
initializer_and_is_rest
base::PointerWithPayload<Expression, bool, 1> v8::internal::ParserFormalParameters::Parameter::initializer_and_is_rest
Definition at line 54 of file parser.h.
Referenced by initializer(), and is_rest().
initializer_end_position
int v8::internal::ParserFormalParameters::Parameter::initializer_end_position
Definition at line 61 of file parser.h.
next_parameter
Parameter* v8::internal::ParserFormalParameters::Parameter::next_parameter = nullptr
Definition at line 64 of file parser.h.
Referenced by next().
pattern
Expression* v8::internal::ParserFormalParameters::Parameter::pattern
Definition at line 56 of file parser.h.
Referenced by is_simple(), and name().
position
int v8::internal::ParserFormalParameters::Parameter::position
Definition at line 60 of file parser.h.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/parsing/parser.h