v8::internal::torque::CallRuntimeInstruction Struct Reference
#include <instructions.h>
Public Member Functions
bool IsBlockTerminator () const override
CallRuntimeInstruction (bool is_tailcall, RuntimeFunction *runtime_function, size_t argc, std::optional< Block * > catch_block)
void AppendSuccessorBlocks (std::vector< Block * > *block_list) const override
std::size_t GetValueDefinitionCount () const
DefinitionLocation GetValueDefinition (std::size_t index) const
std::optional< DefinitionLocation > GetExceptionObjectDefinition () const
Public Attributes
bool is_tailcall
RuntimeFunction * runtime_function
size_t argc
std::optional< Block * > catch_block
Detailed Description
Definition at line 605 of file instructions.h.
Constructor & Destructor Documentation
CallRuntimeInstruction()
v8::internal::torque::CallRuntimeInstruction::CallRuntimeInstruction (bool is_tailcall, RuntimeFunction * runtime_function, size_t argc, std::optional< Block * > catch_block) [inline]
Definition at line 609 of file instructions.h.
      : is_tailcall(is_tailcall),
        runtime_function(runtime_function),
        argc(argc),
        catch_block(catch_block) {}
Member Function Documentation
AppendSuccessorBlocks()
void v8::internal::torque::CallRuntimeInstruction::AppendSuccessorBlocks (std::vector< Block * > * block_list) const [inline], [override], [virtual]
Reimplemented from v8::internal::torque::InstructionBase.
Definition at line 615 of file instructions.h.
                                                                           {
    if (catch_block) block_list->push_back(*catch_block);
  }
References catch_block.
GetExceptionObjectDefinition()
std::optional< DefinitionLocation > v8::internal::torque::CallRuntimeInstruction::GetExceptionObjectDefinition () const
Definition at line 572 of file instructions.cc.
                                                           {
  if (!catch_block) return std::nullopt;
  return DefinitionLocation::Instruction(this, GetValueDefinitionCount());
}
References catch_block, GetValueDefinitionCount(), and v8::internal::torque::DefinitionLocation::Instruction().
GetValueDefinition()
DefinitionLocation v8::internal::torque::CallRuntimeInstruction::GetValueDefinition (std::size_t index) const
Definition at line 565 of file instructions.cc.
                           {
  DCHECK_LT(index, GetValueDefinitionCount());
  return DefinitionLocation::Instruction(this, index);
}
References DCHECK_LT, GetValueDefinitionCount(), v8::internal::index, and v8::internal::torque::DefinitionLocation::Instruction().
GetValueDefinitionCount()
std::size_t v8::internal::torque::CallRuntimeInstruction::GetValueDefinitionCount () const
Definition at line 559 of file instructions.cc.
                                                                {
  const Type* return_type = runtime_function->signature().return_type;
  if (return_type == TypeOracle::GetNeverType()) return 0;
  return LowerType(return_type).size();
}
References v8::internal::torque::TypeOracle::GetNeverType(), v8::internal::torque::LowerType(), v8::internal::torque::Signature::return_type, runtime_function, and v8::internal::torque::Callable::signature().
Referenced by GetExceptionObjectDefinition(), and GetValueDefinition().
IsBlockTerminator()
bool v8::internal::torque::CallRuntimeInstruction::IsBlockTerminator () const [override], [virtual]
Reimplemented from v8::internal::torque::InstructionBase.
Definition at line 803 of file instructions.cc.
                                                     {
  return is_tailcall || runtime_function->signature().return_type ==
                            TypeOracle::GetNeverType();
}
References v8::internal::torque::TypeOracle::GetNeverType(), is_tailcall, v8::internal::torque::Signature::return_type, runtime_function, and v8::internal::torque::Callable::signature().
Member Data Documentation
argc
size_t v8::internal::torque::CallRuntimeInstruction::argc
Definition at line 625 of file instructions.h.
Referenced by v8::internal::torque::operator<<().
catch_block
std::optional<Block*> v8::internal::torque::CallRuntimeInstruction::catch_block
Definition at line 626 of file instructions.h.
Referenced by AppendSuccessorBlocks(), GetExceptionObjectDefinition(), and v8::internal::torque::operator<<().
is_tailcall
bool v8::internal::torque::CallRuntimeInstruction::is_tailcall
Definition at line 623 of file instructions.h.
Referenced by IsBlockTerminator(), and v8::internal::torque::operator<<().
runtime_function
RuntimeFunction* v8::internal::torque::CallRuntimeInstruction::runtime_function
Definition at line 624 of file instructions.h.
Referenced by GetValueDefinitionCount(), IsBlockTerminator(), and v8::internal::torque::operator<<().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/torque/instructions.h
/mnt/V8SourceCode/src/torque/instructions.cc