v8::internal::compiler::turboshaft::ConvertJSPrimitiveToUntaggedOrDeoptOp Struct Reference
#include <operations.h>
Public Types
enum class UntaggedKind : uint8_t {
kInt32
, kAdditiveSafeInteger
, kInt64
, kFloat64
,
kArrayIndex
 }
enum class JSPrimitiveKind : uint8_t {
kAdditiveSafeInteger
, kNumber
, kNumberOrBoolean
, kNumberOrOddball
,
kNumberOrString
, kSmi
 }
Public Member Functions
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
V< Object > input () const
V< FrameState > frame_state () const
ConvertJSPrimitiveToUntaggedOrDeoptOp (V< Object > input, V< FrameState > frame_state, JSPrimitiveKind from_kind, UntaggedKind to_kind, CheckForMinusZeroMode minus_zero_mode, const FeedbackSource &feedback)
void Validate (const Graph &graph) const
auto options () const
Public Attributes
JSPrimitiveKind from_kind
UntaggedKind to_kind
CheckForMinusZeroMode minus_zero_mode
FeedbackSource feedback
Static Public Attributes
static constexpr OpEffects effects = OpEffects().CanDeopt()
Additional Inherited Members
Detailed Description
Definition at line 4984 of file operations.h.
Member Enumeration Documentation
JSPrimitiveKind
enum v8::internal::compiler::turboshaft::ConvertJSPrimitiveToUntaggedOrDeoptOp::JSPrimitiveKind : uint8_t [strong]
Enumerator
kAdditiveSafeInteger
kNumber
kNumberOrBoolean
kNumberOrOddball
kNumberOrString
kSmi
Definition at line 4996 of file operations.h.
                             : uint8_t {
    kAdditiveSafeInteger,
    kNumber,
    kNumberOrBoolean,
    kNumberOrOddball,
    kNumberOrString,
    kSmi,
  };
UntaggedKind
enum v8::internal::compiler::turboshaft::ConvertJSPrimitiveToUntaggedOrDeoptOp::UntaggedKind : uint8_t [strong]
Enumerator
kInt32
kAdditiveSafeInteger
kInt64
kFloat64
kArrayIndex
Definition at line 4986 of file operations.h.
                          : uint8_t {
    kInt32,
    kAdditiveSafeInteger,
    kInt64,
    kFloat64,
#ifdef V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
    kHoleyFloat64,
#endif // V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
    kArrayIndex,
  };
Constructor & Destructor Documentation
ConvertJSPrimitiveToUntaggedOrDeoptOp()
v8::internal::compiler::turboshaft::ConvertJSPrimitiveToUntaggedOrDeoptOp::ConvertJSPrimitiveToUntaggedOrDeoptOp (V< Object > input, V< FrameState > frame_state, JSPrimitiveKind from_kind, UntaggedKind to_kind, CheckForMinusZeroMode minus_zero_mode, const FeedbackSource & feedback) [inline]
Definition at line 5038 of file operations.h.
      : Base(input, frame_state),
        from_kind(from_kind),
        to_kind(to_kind),
        minus_zero_mode(minus_zero_mode),
        feedback(feedback) {}
Member Function Documentation
frame_state()
V<FrameState> v8::internal::compiler::turboshaft::ConvertJSPrimitiveToUntaggedOrDeoptOp::frame_state () const [inline]
Definition at line 5036 of file operations.h.
{ return Base::input<FrameState>(1); }
input()
V<Object> v8::internal::compiler::turboshaft::ConvertJSPrimitiveToUntaggedOrDeoptOp::input () const [inline]
Definition at line 5035 of file operations.h.
{ return Base::input<Object>(0); }
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::ConvertJSPrimitiveToUntaggedOrDeoptOp::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 5030 of file operations.h.
                                                              {
    return MaybeRepVector<MaybeRegisterRepresentation::Tagged()>();
  }
options()
auto v8::internal::compiler::turboshaft::ConvertJSPrimitiveToUntaggedOrDeoptOp::options () const [inline]
Definition at line 5053 of file operations.h.
                       {
    return std::tuple{from_kind, to_kind, minus_zero_mode, feedback};
  }
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::ConvertJSPrimitiveToUntaggedOrDeoptOp::outputs_rep () const [inline]
Definition at line 5012 of file operations.h.
                                                               {
    switch (to_kind) {
      case UntaggedKind::kInt32:
        return RepVector<RegisterRepresentation::Word32()>();
      case UntaggedKind::kAdditiveSafeInteger:
      case UntaggedKind::kInt64:
        return RepVector<RegisterRepresentation::Word64()>();
      case UntaggedKind::kFloat64:
#ifdef V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
      case UntaggedKind::kHoleyFloat64:
#endif // V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
        return RepVector<RegisterRepresentation::Float64()>();
      case UntaggedKind::kArrayIndex:
        return Is64() ? RepVector<RegisterRepresentation::Word64()>()
                      : RepVector<RegisterRepresentation::Word32()>();
    }
  }
References v8::internal::Is64().
Validate()
void v8::internal::compiler::turboshaft::ConvertJSPrimitiveToUntaggedOrDeoptOp::Validate (const Graph & graph) const [inline]
Definition at line 5049 of file operations.h.
                                          {
    DCHECK(Get(graph, frame_state()).Is<FrameStateOp>());
  }
References v8::internal::DCHECK(), v8::internal::compiler::turboshaft::Get(), and graph().
Member Data Documentation
effects
constexpr OpEffects v8::internal::compiler::turboshaft::ConvertJSPrimitiveToUntaggedOrDeoptOp::effects = OpEffects().CanDeopt() [static], [constexpr]
Definition at line 5011 of file operations.h.
feedback
FeedbackSource v8::internal::compiler::turboshaft::ConvertJSPrimitiveToUntaggedOrDeoptOp::feedback
Definition at line 5007 of file operations.h.
from_kind
JSPrimitiveKind v8::internal::compiler::turboshaft::ConvertJSPrimitiveToUntaggedOrDeoptOp::from_kind
Definition at line 5004 of file operations.h.
minus_zero_mode
CheckForMinusZeroMode v8::internal::compiler::turboshaft::ConvertJSPrimitiveToUntaggedOrDeoptOp::minus_zero_mode
Definition at line 5006 of file operations.h.
to_kind
UntaggedKind v8::internal::compiler::turboshaft::ConvertJSPrimitiveToUntaggedOrDeoptOp::to_kind
Definition at line 5005 of file operations.h.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h