v8::internal::TaggedPayload< PayloadTaggingScheme > Struct Template Reference
#include <tagged-payload.h>
Public Member Functions
TaggedPayload (Address pointer, typename PayloadTaggingScheme::TagType tag)
Address Untag (typename PayloadTaggingScheme::TagType tag) const
bool IsTaggedWith (typename PayloadTaggingScheme::TagType tag) const
void SetTag (typename PayloadTaggingScheme::TagType new_tag)
void SetMarkBit ()
void ClearMarkBit ()
bool HasMarkBitSet () const
uint32_t ExtractFreelistLink () const
PayloadTaggingScheme::TagType ExtractTag () const
bool ContainsFreelistLink () const
bool ContainsEvacuationEntry () const
bool IsZapped () const
Address ExtractEvacuationEntryHandleLocation () const
bool ContainsPointer () const
bool operator== (TaggedPayload other) const
bool operator!= (TaggedPayload other) const
Static Public Member Functions
static Address Tag (Address pointer, typename PayloadTaggingScheme::TagType tag)
Private Attributes
Address encoded_word_
Detailed Description
template<typename PayloadTaggingScheme>
struct v8::internal::TaggedPayload< PayloadTaggingScheme >
Definition at line 16 of file tagged-payload.h.
Constructor & Destructor Documentation
TaggedPayload()
template<typename PayloadTaggingScheme >
v8::internal::TaggedPayload< PayloadTaggingScheme >::TaggedPayload (Address pointer, typename PayloadTaggingScheme::TagType tag) [inline]
Definition at line 23 of file tagged-payload.h.
      : encoded_word_(Tag(pointer, tag)) {}
Member Function Documentation
ClearMarkBit()
template<typename PayloadTaggingScheme >
void v8::internal::TaggedPayload< PayloadTaggingScheme >::ClearMarkBit () [inline]
Definition at line 45 of file tagged-payload.h.
{ encoded_word_ &= ~PayloadTaggingScheme::kMarkBit; }
References v8::internal::TaggedPayload< PayloadTaggingScheme >::encoded_word_.
ContainsEvacuationEntry()
template<typename PayloadTaggingScheme >
bool v8::internal::TaggedPayload< PayloadTaggingScheme >::ContainsEvacuationEntry () const [inline]
Definition at line 65 of file tagged-payload.h.
                                       {
    if constexpr (PayloadTaggingScheme::kSupportsEvacuation) {
      return IsTaggedWith(PayloadTaggingScheme::kEvacuationEntryTag);
    } else {
      return false;
    }
  }
References v8::internal::TaggedPayload< PayloadTaggingScheme >::IsTaggedWith().
Referenced by v8::internal::TaggedPayload< PayloadTaggingScheme >::ContainsPointer().
ContainsFreelistLink()
template<typename PayloadTaggingScheme >
bool v8::internal::TaggedPayload< PayloadTaggingScheme >::ContainsFreelistLink () const [inline]
Definition at line 61 of file tagged-payload.h.
                                    {
      return IsTaggedWith(PayloadTaggingScheme::kFreeEntryTag);
  }
References v8::internal::TaggedPayload< PayloadTaggingScheme >::IsTaggedWith().
Referenced by v8::internal::TaggedPayload< PayloadTaggingScheme >::ContainsPointer().
ContainsPointer()
template<typename PayloadTaggingScheme >
bool v8::internal::TaggedPayload< PayloadTaggingScheme >::ContainsPointer () const [inline]
Definition at line 89 of file tagged-payload.h.
                               {
    return !ContainsFreelistLink() && !ContainsEvacuationEntry() && !IsZapped();
  }
References v8::internal::TaggedPayload< PayloadTaggingScheme >::ContainsEvacuationEntry(), v8::internal::TaggedPayload< PayloadTaggingScheme >::ContainsFreelistLink(), and v8::internal::TaggedPayload< PayloadTaggingScheme >::IsZapped().
ExtractEvacuationEntryHandleLocation()
template<typename PayloadTaggingScheme >
Address v8::internal::TaggedPayload< PayloadTaggingScheme >::ExtractEvacuationEntryHandleLocation () const [inline]
Definition at line 81 of file tagged-payload.h.
                                                       {
    if constexpr (PayloadTaggingScheme::kSupportsEvacuation) {
      return Untag(PayloadTaggingScheme::kEvacuationEntryTag);
    } else {
      UNREACHABLE();
    }
  }
References v8::internal::UNREACHABLE(), and v8::internal::TaggedPayload< PayloadTaggingScheme >::Untag().
ExtractFreelistLink()
template<typename PayloadTaggingScheme >
uint32_t v8::internal::TaggedPayload< PayloadTaggingScheme >::ExtractFreelistLink () const [inline]
Definition at line 51 of file tagged-payload.h.
                                       {
    return static_cast<uint32_t>(encoded_word_);
  }
References v8::internal::TaggedPayload< PayloadTaggingScheme >::encoded_word_.
ExtractTag()
template<typename PayloadTaggingScheme >
PayloadTaggingScheme::TagType v8::internal::TaggedPayload< PayloadTaggingScheme >::ExtractTag () const [inline]
Definition at line 55 of file tagged-payload.h.
                                                          {
    return static_cast<typename PayloadTaggingScheme::TagType>(
        (encoded_word_ & PayloadTaggingScheme::kTagMask) |
        PayloadTaggingScheme::kMarkBit);
  }
References v8::internal::TaggedPayload< PayloadTaggingScheme >::encoded_word_, and v8::internal::detail::kTagMask.
HasMarkBitSet()
template<typename PayloadTaggingScheme >
bool v8::internal::TaggedPayload< PayloadTaggingScheme >::HasMarkBitSet () const [inline]
Definition at line 47 of file tagged-payload.h.
                             {
    return (encoded_word_ & PayloadTaggingScheme::kMarkBit) != 0;
  }
References v8::internal::TaggedPayload< PayloadTaggingScheme >::encoded_word_.
IsTaggedWith()
template<typename PayloadTaggingScheme >
bool v8::internal::TaggedPayload< PayloadTaggingScheme >::IsTaggedWith (typename PayloadTaggingScheme::TagType tag) const [inline]
Definition at line 35 of file tagged-payload.h.
                                                                    {
    return (encoded_word_ & PayloadTaggingScheme::kTagMask) == tag;
  }
References v8::internal::TaggedPayload< PayloadTaggingScheme >::encoded_word_, and v8::internal::detail::kTagMask.
Referenced by v8::internal::TaggedPayload< PayloadTaggingScheme >::ContainsEvacuationEntry(), v8::internal::TaggedPayload< PayloadTaggingScheme >::ContainsFreelistLink(), and v8::internal::TaggedPayload< PayloadTaggingScheme >::IsZapped().
IsZapped()
template<typename PayloadTaggingScheme >
bool v8::internal::TaggedPayload< PayloadTaggingScheme >::IsZapped () const [inline]
Definition at line 73 of file tagged-payload.h.
                        {
    if constexpr (PayloadTaggingScheme::kSupportsZapping) {
      return IsTaggedWith(PayloadTaggingScheme::kZappedEntryTag);
    } else {
      return false;
    }
  }
References v8::internal::TaggedPayload< PayloadTaggingScheme >::IsTaggedWith().
Referenced by v8::internal::TaggedPayload< PayloadTaggingScheme >::ContainsPointer().
operator!=()
template<typename PayloadTaggingScheme >
bool v8::internal::TaggedPayload< PayloadTaggingScheme >::operator!= (TaggedPayload< PayloadTaggingScheme > other) const [inline]
Definition at line 97 of file tagged-payload.h.
                                             {
    return encoded_word_ != other.encoded_word_;
  }
References v8::internal::TaggedPayload< PayloadTaggingScheme >::encoded_word_.
operator==()
template<typename PayloadTaggingScheme >
bool v8::internal::TaggedPayload< PayloadTaggingScheme >::operator== (TaggedPayload< PayloadTaggingScheme > other) const [inline]
Definition at line 93 of file tagged-payload.h.
                                             {
    return encoded_word_ == other.encoded_word_;
  }
References v8::internal::TaggedPayload< PayloadTaggingScheme >::encoded_word_.
SetMarkBit()
template<typename PayloadTaggingScheme >
void v8::internal::TaggedPayload< PayloadTaggingScheme >::SetMarkBit () [inline]
Definition at line 43 of file tagged-payload.h.
{ encoded_word_ |= PayloadTaggingScheme::kMarkBit; }
References v8::internal::TaggedPayload< PayloadTaggingScheme >::encoded_word_.
SetTag()
template<typename PayloadTaggingScheme >
void v8::internal::TaggedPayload< PayloadTaggingScheme >::SetTag (typename PayloadTaggingScheme::TagType new_tag) [inline]
Definition at line 39 of file tagged-payload.h.
                                                            {
    encoded_word_ = (encoded_word_ & ~PayloadTaggingScheme::kTagMask) | new_tag;
  }
References v8::internal::TaggedPayload< PayloadTaggingScheme >::encoded_word_, and v8::internal::detail::kTagMask.
Tag()
template<typename PayloadTaggingScheme >
static Address v8::internal::TaggedPayload< PayloadTaggingScheme >::Tag (Address pointer, typename PayloadTaggingScheme::TagType tag) [inline], [static]
Definition at line 30 of file tagged-payload.h.
                                                               {
    return pointer | tag;
  }
Untag()
template<typename PayloadTaggingScheme >
Address v8::internal::TaggedPayload< PayloadTaggingScheme >::Untag (typename PayloadTaggingScheme::TagType tag) const [inline]
Definition at line 26 of file tagged-payload.h.
                                                                {
    return encoded_word_ & ~(tag | PayloadTaggingScheme::kMarkBit);
  }
References v8::internal::TaggedPayload< PayloadTaggingScheme >::encoded_word_.
Referenced by v8::internal::TaggedPayload< PayloadTaggingScheme >::ExtractEvacuationEntryHandleLocation().
Member Data Documentation
encoded_word_
template<typename PayloadTaggingScheme >
Address v8::internal::TaggedPayload< PayloadTaggingScheme >::encoded_word_ [private]
Definition at line 102 of file tagged-payload.h.
Referenced by v8::internal::TaggedPayload< PayloadTaggingScheme >::ClearMarkBit(), v8::internal::TaggedPayload< PayloadTaggingScheme >::ExtractFreelistLink(), v8::internal::TaggedPayload< PayloadTaggingScheme >::ExtractTag(), v8::internal::TaggedPayload< PayloadTaggingScheme >::HasMarkBitSet(), v8::internal::TaggedPayload< PayloadTaggingScheme >::IsTaggedWith(), v8::internal::TaggedPayload< PayloadTaggingScheme >::operator!=(), v8::internal::TaggedPayload< PayloadTaggingScheme >::operator==(), v8::internal::TaggedPayload< PayloadTaggingScheme >::SetMarkBit(), v8::internal::TaggedPayload< PayloadTaggingScheme >::SetTag(), and v8::internal::TaggedPayload< PayloadTaggingScheme >::Untag().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/sandbox/tagged-payload.h