v8::internal::compiler::turboshaft::CheckExceptionOp Struct Reference
#include <operations.h>
Public Member Functions
base::Vector< const RegisterRepresentation > outputs_rep () const
V< Any > throwing_operation () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
CheckExceptionOp (V< Any > throwing_operation, Block *successor, Block *catch_block)
V8_EXPORT_PRIVATE void Validate (const Graph &graph) const
size_t hash_value (HashingStrategy strategy=HashingStrategy::kDefault) const
auto options () const
Public Attributes
Block * didnt_throw_block
Block * catch_block
Static Public Attributes
static constexpr OpEffects effects = OpEffects().CanCallAnything()
Additional Inherited Members
Detailed Description
Definition at line 4164 of file operations.h.
Constructor & Destructor Documentation
CheckExceptionOp()
v8::internal::compiler::turboshaft::CheckExceptionOp::CheckExceptionOp (V< Any > throwing_operation, Block * successor, Block * catch_block) [inline]
Definition at line 4178 of file operations.h.
      : Base(throwing_operation),
        didnt_throw_block(successor),
        catch_block(catch_block) {}
Member Function Documentation
hash_value()
size_t v8::internal::compiler::turboshaft::CheckExceptionOp::hash_value (HashingStrategy strategy = HashingStrategy::kDefault) const
Definition at line 2108 of file operations.cc.
                                                                  {
  if (strategy == HashingStrategy::kMakeSnapshotStable) {
    // Destructure here to cause a compilation error in case `options` is
    // changed.
    auto [didnt_throw_block_value, catch_block_value] = options();
    return HashWithOptions(index_for_bound_block(didnt_throw_block_value),
                           index_for_bound_block(catch_block_value));
  } else {
    return Base::hash_value(strategy);
  }
}
References v8::internal::compiler::turboshaft::OperationT< Derived >::hash_value(), v8::internal::compiler::turboshaft::OperationT< Derived >::HashWithOptions(), v8::internal::compiler::turboshaft::anonymous_namespace{operations.cc}::index_for_bound_block(), v8::internal::compiler::turboshaft::kMakeSnapshotStable, and options().
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::CheckExceptionOp::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 4173 of file operations.h.
                                                              {
    return {};
  }
options()
auto v8::internal::compiler::turboshaft::CheckExceptionOp::options () const [inline]
Definition at line 4187 of file operations.h.
{ return std::tuple{didnt_throw_block, catch_block}; }
Referenced by hash_value().
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::CheckExceptionOp::outputs_rep () const [inline]
Definition at line 4169 of file operations.h.
{ return {}; }
throwing_operation()
V<Any> v8::internal::compiler::turboshaft::CheckExceptionOp::throwing_operation () const [inline]
Definition at line 4171 of file operations.h.
{ return input<Any>(0); }
Referenced by Validate(), and v8::internal::compiler::InstructionSelector::VisitControl().
Validate()
void v8::internal::compiler::turboshaft::CheckExceptionOp::Validate (const Graph & graph) const
Definition at line 2081 of file operations.cc.
                                                        {
  DCHECK_NE(didnt_throw_block, catch_block);
  // `CheckException` should follow right after the throwing operation.
  DCHECK_EQ(throwing_operation(),
            V<Any>::Cast(graph.PreviousIndex(graph.Index(*this))));
}
References catch_block, DCHECK_EQ, DCHECK_NE, didnt_throw_block, graph(), and throwing_operation().
Member Data Documentation
catch_block
Block* v8::internal::compiler::turboshaft::CheckExceptionOp::catch_block
Definition at line 4166 of file operations.h.
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphCheckException(), v8::internal::compiler::turboshaft::IsUnlikelySuccessor(), v8::internal::compiler::turboshaft::Assembler< Reducers >::SplitEdge(), Validate(), and v8::internal::compiler::InstructionSelector::VisitControl().
didnt_throw_block
Block* v8::internal::compiler::turboshaft::CheckExceptionOp::didnt_throw_block
Definition at line 4165 of file operations.h.
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphCheckException(), v8::internal::compiler::turboshaft::Assembler< Reducers >::SplitEdge(), v8::internal::compiler::turboshaft::SuccessorBlocks(), Validate(), and v8::internal::compiler::InstructionSelector::VisitControl().
effects
constexpr OpEffects v8::internal::compiler::turboshaft::CheckExceptionOp::effects = OpEffects().CanCallAnything() [static], [constexpr]
Definition at line 4168 of file operations.h.
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h
/mnt/V8SourceCode/src/compiler/turboshaft/operations.cc