v8::internal::baseline::detail::PushAllHelper< Arg1, Arg2, Args... > Struct Template Reference
#include <baseline-assembler-arm64-inl.h>
Static Public Member Functions
static void Push (BaselineAssembler *basm, Arg1 arg1, Arg2 arg2, Args... args)
static void PushReverse (BaselineAssembler *basm, Arg1 arg1, Arg2 arg2, Args... args)
Detailed Description
template<typename Arg1, typename Arg2, typename... Args>
struct v8::internal::baseline::detail::PushAllHelper< Arg1, Arg2, Args... >
Definition at line 291 of file baseline-assembler-arm64-inl.h.
Member Function Documentation
Push()
template<typename Arg1 , typename Arg2 , typename... Args>
static void v8::internal::baseline::detail::PushAllHelper< Arg1, Arg2, Args... >::Push (BaselineAssembler * basm, Arg1 arg1, Arg2 arg2, Args... args) [inline], [static]
Definition at line 292 of file baseline-assembler-arm64-inl.h.
                                 {
    {
      BaselineAssembler::ScratchRegisterScope scope(basm);
      basm->masm()->Push(ToRegister(basm, &scope, arg1),
                         ToRegister(basm, &scope, arg2));
    }
    PushAll(basm, args...);
  }
References v8::base::args, v8::internal::baseline::BaselineAssembler::masm(), v8::internal::MacroAssembler::Push(), v8::internal::baseline::detail::PushAll(), and v8::internal::baseline::detail::ToRegister().
PushReverse()
template<typename Arg1 , typename Arg2 , typename... Args>
static void v8::internal::baseline::detail::PushAllHelper< Arg1, Arg2, Args... >::PushReverse (BaselineAssembler * basm, Arg1 arg1, Arg2 arg2, Args... args) [inline], [static]
Definition at line 301 of file baseline-assembler-arm64-inl.h.
                                        {
    PushAllReverse(basm, args...);
    {
      BaselineAssembler::ScratchRegisterScope scope(basm);
      basm->masm()->Push(ToRegister(basm, &scope, arg2),
                         ToRegister(basm, &scope, arg1));
    }
  }
References v8::base::args, v8::internal::baseline::BaselineAssembler::masm(), v8::internal::MacroAssembler::Push(), v8::internal::baseline::detail::PushAllReverse(), and v8::internal::baseline::detail::ToRegister().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/baseline/arm64/baseline-assembler-arm64-inl.h