v8::internal::compiler::ValueMatcher< T, kOpcode > Struct Template Reference
#include <node-matchers.h>
Public Types
using ValueType = T
Public Member Functions
ValueMatcher (Node *node)
bool HasResolvedValue () const
const T & ResolvedValue () const
ValueMatcher (Node *node)
ValueMatcher (Node *node)
ValueMatcher (Node *node)
Private Attributes
T resolved_value_
bool has_resolved_value_
Detailed Description
template<typename T, IrOpcode::Value kOpcode>
struct v8::internal::compiler::ValueMatcher< T, kOpcode >
Definition at line 67 of file node-matchers.h.
Member Typedef Documentation
ValueType
template<typename T , IrOpcode::Value kOpcode>
using v8::internal::compiler::ValueMatcher< T, kOpcode >::ValueType = T
Definition at line 75 of file node-matchers.h.
Constructor & Destructor Documentation
ValueMatcher() [1/4]
template<typename T , IrOpcode::Value kOpcode>
v8::internal::compiler::ValueMatcher< T, kOpcode >::ValueMatcher (Node * node) [inline], [explicit]
Definition at line 77 of file node-matchers.h.
      : NodeMatcher(node), resolved_value_(), has_resolved_value_(false) {
    node = SkipValueIdentities(node);
    has_resolved_value_ = node->opcode() == kOpcode;
    if (has_resolved_value_) {
      resolved_value_ = OpParameter<T>(node->op());
    }
  }
References v8::internal::compiler::ValueMatcher< T, kOpcode >::has_resolved_value_, v8::internal::compiler::NodeMatcher::node(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::ValueMatcher< T, kOpcode >::resolved_value_, and v8::internal::compiler::SkipValueIdentities().
ValueMatcher() [2/4]
v8::internal::compiler::ValueMatcher< uint32_t, IrOpcode::kInt32Constant >::ValueMatcher (Node * node) [inline]
Definition at line 98 of file node-matchers.h.
    : NodeMatcher(node), resolved_value_(), has_resolved_value_(false) {
  node = SkipValueIdentities(node);
  has_resolved_value_ = node->opcode() == IrOpcode::kInt32Constant;
  if (has_resolved_value_) {
    resolved_value_ = static_cast<uint32_t>(OpParameter<int32_t>(node->op()));
  }
}
References v8::internal::compiler::ValueMatcher< T, kOpcode >::has_resolved_value_, v8::internal::compiler::NodeMatcher::node(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::ValueMatcher< T, kOpcode >::resolved_value_, and v8::internal::compiler::SkipValueIdentities().
ValueMatcher() [3/4]
v8::internal::compiler::ValueMatcher< int64_t, IrOpcode::kInt64Constant >::ValueMatcher (Node * node) [inline]
Definition at line 109 of file node-matchers.h.
    : NodeMatcher(node), resolved_value_(), has_resolved_value_(false) {
  node = SkipValueIdentities(node);
  if (node->opcode() == IrOpcode::kInt32Constant) {
    resolved_value_ = OpParameter<int32_t>(node->op());
    has_resolved_value_ = true;
  } else if (node->opcode() == IrOpcode::kInt64Constant) {
    resolved_value_ = OpParameter<int64_t>(node->op());
    has_resolved_value_ = true;
  }
}
References v8::internal::compiler::ValueMatcher< T, kOpcode >::has_resolved_value_, v8::internal::compiler::NodeMatcher::node(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::ValueMatcher< T, kOpcode >::resolved_value_, and v8::internal::compiler::SkipValueIdentities().
ValueMatcher() [4/4]
v8::internal::compiler::ValueMatcher< uint64_t, IrOpcode::kInt64Constant >::ValueMatcher (Node * node) [inline]
Definition at line 122 of file node-matchers.h.
    : NodeMatcher(node), resolved_value_(), has_resolved_value_(false) {
  node = SkipValueIdentities(node);
  if (node->opcode() == IrOpcode::kInt32Constant) {
    resolved_value_ = static_cast<uint32_t>(OpParameter<int32_t>(node->op()));
    has_resolved_value_ = true;
  } else if (node->opcode() == IrOpcode::kInt64Constant) {
    resolved_value_ = static_cast<uint64_t>(OpParameter<int64_t>(node->op()));
    has_resolved_value_ = true;
  }
}
References v8::internal::compiler::ValueMatcher< T, kOpcode >::has_resolved_value_, v8::internal::compiler::NodeMatcher::node(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::ValueMatcher< T, kOpcode >::resolved_value_, and v8::internal::compiler::SkipValueIdentities().
Member Function Documentation
HasResolvedValue()
template<typename T , IrOpcode::Value kOpcode>
bool v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue () const [inline]
Definition at line 86 of file node-matchers.h.
{ return has_resolved_value_; }
References v8::internal::compiler::ValueMatcher< T, kOpcode >::has_resolved_value_.
Referenced by v8::internal::compiler::CsaLoadElimination::HalfState::AddField(), v8::internal::compiler::WasmGraphAssembler::BuildChangeUint32ToUintPtr(), v8::internal::compiler::PropertyAccessBuilder::BuildCheckMaps(), v8::internal::compiler::JSInliningHeuristic::CollectFunctions(), v8::internal::compiler::JSNativeContextSpecialization::CreateStringConstant(), v8::internal::compiler::anonymous_namespace{simplified-operator-reducer.cc}::DecideObjectIsSmi(), v8::internal::compiler::JSInliner::DetermineCallContext(), v8::internal::compiler::JSInliner::DetermineCallTarget(), v8::internal::compiler::JSCreateClosureNode::GetFeedbackCellRefChecked(), v8::internal::compiler::RepresentationChanger::GetFloat64RepresentationFor(), v8::internal::compiler::NodeProperties::GetJSCreateMap(), v8::internal::compiler::JSNativeContextSpecialization::GetMaxStringLength(), v8::internal::compiler::anonymous_namespace{js-native-context-specialization.cc}::GetTypedArrayConstant(), v8::internal::compiler::RepresentationChanger::GetWord64RepresentationFor(), v8::internal::compiler::NodeProperties::InferMapsUnsafe(), v8::internal::compiler::JSNativeContextSpecialization::InferRootMap(), v8::internal::compiler::IntMatcher< T, kOpcode >::Is(), v8::internal::compiler::FloatMatcher< T, kOpcode >::Is(), v8::internal::compiler::anonymous_namespace{machine-operator-reducer.cc}::IsFloat64RepresentableAsFloat32(), v8::internal::compiler::IntMatcher< T, kOpcode >::IsInRange(), v8::internal::compiler::FloatMatcher< T, kOpcode >::IsInRange(), v8::internal::compiler::FloatMatcher< T, kOpcode >::IsInteger(), v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::IsLiteralString(), v8::internal::compiler::IntMatcher< T, kOpcode >::IsMultipleOf(), v8::internal::compiler::FloatMatcher< T, kOpcode >::IsNaN(), v8::internal::compiler::IntMatcher< T, kOpcode >::IsNegative(), v8::internal::compiler::FloatMatcher< T, kOpcode >::IsNegative(), v8::internal::compiler::IntMatcher< T, kOpcode >::IsNegativePowerOf2(), v8::internal::compiler::FloatMatcher< T, kOpcode >::IsNormal(), v8::internal::compiler::FloatMatcher< T, kOpcode >::IsPositiveOrNegativePowerOf2(), v8::internal::compiler::IntMatcher< T, kOpcode >::IsPowerOf2(), v8::internal::compiler::anonymous_namespace{js-native-context-specialization.cc}::IsStringConstant(), v8::internal::compiler::anonymous_namespace{js-native-context-specialization.cc}::IsStringWithNonAccessibleContent(), v8::internal::compiler::CsaLoadElimination::HalfState::KillField(), v8::internal::compiler::CsaLoadElimination::HalfState::Lookup(), v8::internal::compiler::OneOrTwoByteAnalysis::OneOrTwoByte(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::SimplifiedOperatorReducer::Reduce(), v8::internal::compiler::MachineOperatorReducer::Reduce(), v8::internal::compiler::JSCallReducer::ReduceDataViewAccess(), v8::internal::compiler::MachineOperatorReducer::ReduceFloat64InsertHighWord32(), v8::internal::compiler::MachineOperatorReducer::ReduceFloat64InsertLowWord32(), v8::internal::compiler::MachineOperatorReducer::ReduceFloat64RoundDown(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeCall(), v8::internal::compiler::JSCallReducer::ReduceJSCall(), v8::internal::compiler::JSInliner::ReduceJSCall(), v8::internal::compiler::JSCallReducer::ReduceJSConstruct(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSDefineKeyedOwnPropertyInLiteral(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSFindNonDefaultConstructorOrConstruct(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSGetSuperConstructor(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSHasInPrototypeChain(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSInstanceOf(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadNamed(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSOrdinaryHasInstance(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSPromiseResolve(), v8::internal::compiler::JSTypedLowering::ReduceJSToNumberInput(), v8::internal::compiler::TypedOptimization::ReduceJSToNumberInput(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSToString(), v8::internal::compiler::JSCallReducer::ReduceNumberParseInt(), v8::internal::compiler::JSNativeContextSpecialization::ReducePropertyAccess(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeCharAt(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeEndsWith(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeStartsWith(), v8::internal::compiler::CommonOperatorReducer::ReduceSwitch(), v8::internal::compiler::JSIntrinsicLowering::ReduceToString(), v8::internal::compiler::MachineOperatorReducer::ReduceTruncateInt64ToInt32(), v8::internal::compiler::TypedOptimization::ReduceTypedArrayLength(), v8::internal::compiler::ValueMatcher< T, kOpcode >::ResolvedValue(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ShouldUseCallICFeedback(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::TargetIsClassConstructor(), v8::internal::compiler::PropertyAccessBuilder::TryFoldLoadConstantDataField(), v8::internal::compiler::OneOrTwoByteAnalysis::TryGetRange(), v8::internal::compiler::JSCallReducer::TryReduceJSCallMathMinMaxWithArrayLike(), v8::internal::compiler::CodeAssembler::TryToInt32Constant(), v8::internal::compiler::CodeAssembler::TryToInt64Constant(), v8::internal::compiler::CodeAssembler::TryToIntPtrConstant(), v8::internal::compiler::CodeAssembler::TryToSmiConstant(), and v8::internal::compiler::RepresentationSelector::WriteBarrierKindFor().
ResolvedValue()
template<typename T , IrOpcode::Value kOpcode>
const T& v8::internal::compiler::ValueMatcher< T, kOpcode >::ResolvedValue () const [inline]
Definition at line 87 of file node-matchers.h.
                                 {
    CHECK(HasResolvedValue());
    return resolved_value_;
  }
References CHECK, v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), and v8::internal::compiler::ValueMatcher< T, kOpcode >::resolved_value_.
Referenced by v8::internal::compiler::CsaLoadElimination::HalfState::AddField(), v8::internal::compiler::WasmGraphAssembler::BuildChangeUint32ToUintPtr(), v8::internal::compiler::JSNativeContextSpecialization::CreateStringConstant(), v8::internal::compiler::CommonOperatorReducer::DecideCondition(), v8::internal::compiler::anonymous_namespace{simplified-operator-reducer.cc}::DecideObjectIsSmi(), v8::internal::compiler::JSCreateClosureNode::GetFeedbackCellRefChecked(), v8::internal::compiler::RepresentationChanger::GetFloat64RepresentationFor(), v8::internal::compiler::IntMatcher< T, kOpcode >::Is(), v8::internal::compiler::FloatMatcher< T, kOpcode >::Is(), v8::internal::compiler::anonymous_namespace{machine-operator-reducer.cc}::IsFloat64RepresentableAsFloat32(), v8::internal::compiler::IntMatcher< T, kOpcode >::IsInRange(), v8::internal::compiler::FloatMatcher< T, kOpcode >::IsInRange(), v8::internal::compiler::FloatMatcher< T, kOpcode >::IsInteger(), v8::internal::compiler::FloatMatcher< T, kOpcode >::IsMinusZero(), v8::internal::compiler::IntMatcher< T, kOpcode >::IsMultipleOf(), v8::internal::compiler::FloatMatcher< T, kOpcode >::IsNaN(), v8::internal::compiler::IntMatcher< T, kOpcode >::IsNegative(), v8::internal::compiler::FloatMatcher< T, kOpcode >::IsNegative(), v8::internal::compiler::IntMatcher< T, kOpcode >::IsNegativePowerOf2(), v8::internal::compiler::FloatMatcher< T, kOpcode >::IsNormal(), v8::internal::compiler::FloatMatcher< T, kOpcode >::IsPositiveOrNegativePowerOf2(), v8::internal::compiler::IntMatcher< T, kOpcode >::IsPowerOf2(), v8::internal::compiler::FloatMatcher< T, kOpcode >::IsZero(), v8::internal::compiler::CsaLoadElimination::HalfState::KillField(), v8::internal::compiler::CsaLoadElimination::HalfState::Lookup(), v8::internal::compiler::SimplifiedOperatorReducer::Reduce(), v8::internal::compiler::MachineOperatorReducer::Reduce(), v8::internal::compiler::MemoryLowering::ReduceAllocateRaw(), v8::internal::compiler::JSCallReducer::ReduceBigIntAsN(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementLoadFromHeapConstant(), v8::internal::compiler::MachineOperatorReducer::ReduceFloat64InsertHighWord32(), v8::internal::compiler::MachineOperatorReducer::ReduceFloat64InsertLowWord32(), v8::internal::compiler::MachineOperatorReducer::ReduceFloat64RoundDown(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSDefineKeyedOwnPropertyInLiteral(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSToString(), v8::internal::compiler::JSCallReducer::ReduceNumberParseInt(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeCharAt(), v8::internal::compiler::CommonOperatorReducer::ReduceSwitch(), v8::internal::compiler::MachineOperatorReducer::ReduceTruncateInt64ToInt32(), v8::internal::compiler::CodeAssembler::TryToInt32Constant(), v8::internal::compiler::CodeAssembler::TryToInt64Constant(), v8::internal::compiler::CodeAssembler::TryToIntPtrConstant(), v8::internal::compiler::CodeAssembler::TryToSmiConstant(), and v8::internal::compiler::RepresentationSelector::WriteBarrierKindFor().
Member Data Documentation
has_resolved_value_
template<typename T , IrOpcode::Value kOpcode>
bool v8::internal::compiler::ValueMatcher< T, kOpcode >::has_resolved_value_ [private]
Definition at line 94 of file node-matchers.h.
Referenced by v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), and v8::internal::compiler::ValueMatcher< T, kOpcode >::ValueMatcher().
resolved_value_
template<typename T , IrOpcode::Value kOpcode>
T v8::internal::compiler::ValueMatcher< T, kOpcode >::resolved_value_ [private]
Definition at line 93 of file node-matchers.h.
Referenced by v8::internal::compiler::ValueMatcher< T, kOpcode >::ResolvedValue(), and v8::internal::compiler::ValueMatcher< T, kOpcode >::ValueMatcher().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/node-matchers.h