cppgc::internal::MakeGarbageCollectedTraitInternal::AllocationDispatcher< GCInfoType, void, alignment > Struct Template Reference
#include <allocation.h>
Static Public Member Functions
static void * Invoke (AllocationHandle &handle, size_t size)
Detailed Description
template<typename GCInfoType, size_t alignment>
struct cppgc::internal::MakeGarbageCollectedTraitInternal::AllocationDispatcher< GCInfoType, void, alignment >
Definition at line 100 of file allocation.h.
Member Function Documentation
Invoke()
template<typename GCInfoType , size_t alignment>
static void* cppgc::internal::MakeGarbageCollectedTraitInternal::AllocationDispatcher< GCInfoType, void, alignment >::Invoke (AllocationHandle & handle, size_t size) [inline], [static]
Definition at line 101 of file allocation.h.
                                                               {
      return MakeGarbageCollectedTraitInternal::Allocate(
          handle, size, static_cast<AlignVal>(alignment),
          internal::GCInfoTrait<GCInfoType>::Index());
    }
References cppgc::internal::MakeGarbageCollectedTraitInternal::Allocate(), v8::internal::handle(), and size().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/include/cppgc/allocation.h