v8::internal::compiler::turboshaft::OverflowCheckedBinopOp Struct Reference
#include <operations.h>
Public Types
enum class Kind : uint8_t { kSignedAdd
, kSignedMul
, kSignedSub
 }
Public Member Functions
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
V< Word > left () const
V< Word > right () const
OverflowCheckedBinopOp (V< Word > left, V< Word > right, Kind kind, WordRepresentation rep)
auto options () const
void PrintOptions (std::ostream &os) const
Static Public Member Functions
static bool IsCommutative (Kind kind)
Public Attributes
Kind kind
WordRepresentation rep
Static Public Attributes
static constexpr int kValueIndex = 0
static constexpr int kOverflowIndex = 1
static constexpr OpEffects effects = OpEffects()
Additional Inherited Members
Detailed Description
Definition at line 1824 of file operations.h.
Member Enumeration Documentation
Kind
enum v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::Kind : uint8_t [strong]
Enumerator
kSignedAdd
kSignedMul
kSignedSub
Definition at line 1829 of file operations.h.
                  : uint8_t {
    kSignedAdd,
    kSignedMul,
    kSignedSub,
  };
Constructor & Destructor Documentation
OverflowCheckedBinopOp()
v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::OverflowCheckedBinopOp (V< Word > left, V< Word > right, Kind kind, WordRepresentation rep) [inline]
Definition at line 1867 of file operations.h.
      : Base(left, right), kind(kind), rep(rep) {}
Member Function Documentation
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 1849 of file operations.h.
                                                              {
    return InputsRepFactory::PairOf(rep);
  }
References v8::internal::compiler::turboshaft::InputsRepFactory::PairOf().
IsCommutative()
static bool v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::IsCommutative (Kind kind) [inline], [static]
Definition at line 1857 of file operations.h.
                                       {
    switch (kind) {
      case Kind::kSignedAdd:
      case Kind::kSignedMul:
        return true;
      case Kind::kSignedSub:
        return false;
    }
  }
Referenced by v8::internal::compiler::InstructionSelector::IsCommutative(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::OverflowCheckedBinop().
left()
V<Word> v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::left () const [inline]
Definition at line 1854 of file operations.h.
{ return input<Word>(0); }
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitInt32MulWithOverflow(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::EmitInt32MulWithOverflow(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::EmitInt64MulWithOverflow(), and v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessOverflowCheckedBinop().
options()
auto v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::options () const [inline]
Definition at line 1871 of file operations.h.
{ return std::tuple{kind, rep}; }
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::outputs_rep () const [inline]
Definition at line 1838 of file operations.h.
                                                               {
    switch (rep.value()) {
      case WordRepresentation::Word32():
        return RepVector<RegisterRepresentation::Word32(),
                         RegisterRepresentation::Word32()>();
      case WordRepresentation::Word64():
        return RepVector<RegisterRepresentation::Word64(),
                         RegisterRepresentation::Word32()>();
    }
  }
References v8::internal::compiler::turboshaft::RepVector(), v8::internal::compiler::turboshaft::WordRepresentation::value(), v8::internal::compiler::turboshaft::RegisterRepresentation::Word32(), v8::internal::compiler::turboshaft::WordRepresentation::Word32(), v8::internal::compiler::turboshaft::RegisterRepresentation::Word64(), and v8::internal::compiler::turboshaft::WordRepresentation::Word64().
PrintOptions()
void v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::PrintOptions (std::ostream & os) const
Definition at line 1066 of file operations.cc.
                                                              {
  os << '[';
  switch (kind) {
    case Kind::kSignedAdd:
      os << "signed add, ";
      break;
    case Kind::kSignedSub:
      os << "signed sub, ";
      break;
    case Kind::kSignedMul:
      os << "signed mul, ";
      break;
  }
  os << rep;
  os << ']';
}
References kind, kSignedAdd, kSignedMul, kSignedSub, and rep.
right()
V<Word> v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::right () const [inline]
Definition at line 1855 of file operations.h.
{ return input<Word>(1); }
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitInt32MulWithOverflow(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::EmitInt32MulWithOverflow(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::EmitInt64MulWithOverflow(), and v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessOverflowCheckedBinop().
Member Data Documentation
effects
constexpr OpEffects v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::effects = OpEffects() [static], [constexpr]
Definition at line 1837 of file operations.h.
kind
Kind v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::kind
Definition at line 1834 of file operations.h.
Referenced by PrintOptions(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessOverflowCheckedBinop(), and v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::ProduceWord32Result().
kOverflowIndex
constexpr int v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::kOverflowIndex = 1 [static], [constexpr]
Definition at line 1827 of file operations.h.
kValueIndex
constexpr int v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::kValueIndex = 0 [static], [constexpr]
Definition at line 1826 of file operations.h.
Referenced by v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::MatchCheckedOverflowBinop().
rep
WordRepresentation v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::rep
Definition at line 1835 of file operations.h.
Referenced by PrintOptions(), and v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessOverflowCheckedBinop().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h
/mnt/V8SourceCode/src/compiler/turboshaft/operations.cc