v8::internal::compiler::UntyperPhase Struct Reference
Public Member Functions
void Run (TFPipelineData *data, Zone *temp_zone)
Detailed Description
Definition at line 1063 of file pipeline.cc.
Member Function Documentation
Run()
void v8::internal::compiler::UntyperPhase::Run (TFPipelineData * data, Zone * temp_zone) [inline]
Definition at line 1066 of file pipeline.cc.
                                                  {
    class RemoveTypeReducer final : public Reducer {
     public:
      const char* reducer_name() const override { return "RemoveTypeReducer"; }
      Reduction Reduce(Node* node) final {
        if (NodeProperties::IsTyped(node)) {
          NodeProperties::RemoveType(node);
          return Changed(node);
        }
        return NoChange();
      }
    };
    NodeVector roots(temp_zone);
    data->jsgraph()->GetCachedNodes(&roots);
    for (Node* node : roots) {
      NodeProperties::RemoveType(node);
    }
    GraphReducer graph_reducer(
        temp_zone, data->graph(), &data->info()->tick_counter(), data->broker(),
        data->jsgraph()->Dead(), data->observe_node_manager());
    RemoveTypeReducer remove_type_reducer;
    AddReducer(data, &graph_reducer, &remove_type_reducer);
    graph_reducer.ReduceGraph();
  }
References v8::internal::compiler::anonymous_namespace{pipeline.cc}::AddReducer(), v8::internal::compiler::NodeProperties::IsTyped(), v8::internal::compiler::GraphReducer::ReduceGraph(), and v8::internal::compiler::NodeProperties::RemoveType().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/pipeline.cc