v8::internal::compiler::turboshaft::StringFromCodePointAtOp Struct Reference
#include <operations.h>
Public Member Functions
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
V< String > string () const
V< WordPtr > index () const
StringFromCodePointAtOp (V< String > string, V< WordPtr > index)
auto options () const
Static Public Attributes
static constexpr OpEffects effects
Additional Inherited Members
Detailed Description
Definition at line 5648 of file operations.h.
Constructor & Destructor Documentation
StringFromCodePointAtOp()
v8::internal::compiler::turboshaft::StringFromCodePointAtOp::StringFromCodePointAtOp (V< String > string, V< WordPtr > index) [inline]
Definition at line 5670 of file operations.h.
      : Base(string, index) {}
Member Function Documentation
index()
V<WordPtr> v8::internal::compiler::turboshaft::StringFromCodePointAtOp::index () const [inline]
Definition at line 5668 of file operations.h.
{ return Base::input<WordPtr>(1); }
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::StringFromCodePointAtOp::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 5661 of file operations.h.
                                                              {
    return MaybeRepVector<MaybeRegisterRepresentation::Tagged(),
                          MaybeRegisterRepresentation::WordPtr()>();
  }
References v8::internal::compiler::turboshaft::MaybeRepVector(), v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::Tagged(), and v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::WordPtr().
options()
auto v8::internal::compiler::turboshaft::StringFromCodePointAtOp::options () const [inline]
Definition at line 5674 of file operations.h.
{ return std::tuple{}; }
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::StringFromCodePointAtOp::outputs_rep () const [inline]
Definition at line 5657 of file operations.h.
                                                               {
    return RepVector<RegisterRepresentation::Tagged()>();
  }
string()
V<String> v8::internal::compiler::turboshaft::StringFromCodePointAtOp::string () const [inline]
Definition at line 5667 of file operations.h.
{ return Base::input<String>(0); }
Member Data Documentation
effects
constexpr OpEffects v8::internal::compiler::turboshaft::StringFromCodePointAtOp::effects [static], [constexpr]
Initial value:
=
      OpEffects()
          
          
          .CanAllocateWithoutIdentity()
          
          .CanDependOnChecks()
Definition at line 5650 of file operations.h.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h