v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait > Struct Template Reference
#include <lazy-instance.h>
Public Types
using StorageType = typename AllocationTrait::StorageType
using AlignmentType = typename AllocationTrait::AlignmentType
Public Member Functions
T * Pointer ()
const T & Get () const
Public Attributes
OnceType once_
StorageType storage_
Private Member Functions
void Init () const
Static Private Member Functions
static void InitInstance (void *storage)
Detailed Description
template<typename T, typename AllocationTrait, typename CreateTrait, typename InitOnceTrait, typename DestroyTrait>
struct v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >
Definition at line 165 of file lazy-instance.h.
Member Typedef Documentation
AlignmentType
template<typename T , typename AllocationTrait , typename CreateTrait , typename InitOnceTrait , typename DestroyTrait >
using v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::AlignmentType = typename AllocationTrait::AlignmentType
Definition at line 168 of file lazy-instance.h.
StorageType
template<typename T , typename AllocationTrait , typename CreateTrait , typename InitOnceTrait , typename DestroyTrait >
using v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::StorageType = typename AllocationTrait::StorageType
Definition at line 167 of file lazy-instance.h.
Member Function Documentation
Get()
template<typename T , typename AllocationTrait , typename CreateTrait , typename InitOnceTrait , typename DestroyTrait >
const T& v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::Get () const [inline]
Definition at line 186 of file lazy-instance.h.
                       {
    Init();
    return *AllocationTrait::MutableInstance(&storage_);
  }
References v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::Init(), and v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::storage_.
Init()
template<typename T , typename AllocationTrait , typename CreateTrait , typename InitOnceTrait , typename DestroyTrait >
void v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::Init () const [inline], [private]
Definition at line 176 of file lazy-instance.h.
                    {
    InitOnceTrait::Init(&once_, &InitInstance, static_cast<void*>(&storage_));
  }
References v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::InitInstance(), v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::once_, and v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::storage_.
Referenced by v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::Get(), and v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::Pointer().
InitInstance()
template<typename T , typename AllocationTrait , typename CreateTrait , typename InitOnceTrait , typename DestroyTrait >
static void v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::InitInstance (void * storage) [inline], [static], [private]
Definition at line 171 of file lazy-instance.h.
                                          {
    AllocationTrait::template InitStorageUsingTrait<CreateTrait>(
        static_cast<StorageType*>(storage));
  }
Referenced by v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::Init().
Pointer()
template<typename T , typename AllocationTrait , typename CreateTrait , typename InitOnceTrait , typename DestroyTrait >
T* v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::Pointer () [inline]
Definition at line 181 of file lazy-instance.h.
               {
    Init();
    return AllocationTrait::MutableInstance(&storage_);
  }
References v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::Init(), and v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::storage_.
Referenced by v8::internal::ETWJITInterface::IsolateLoadScriptData::AddIsolate(), cppgc::internal::ProcessGlobalLock::AssertHeld(), v8::internal::ObjectStats::CheckpointObjectStats(), v8::internal::Isolate::CreateAndSetEmbeddedBlob(), v8::internal::DisableEmbeddedBlobRefcounting(), v8::internal::ETWJITInterface::IsolateLoadScriptData::DisableLog(), v8::internal::ETWJITInterface::IsolateLoadScriptData::EnableLog(), v8::internal::ETWJITInterface::IsolateLoadScriptData::EnableLogWithFilterData(), v8::internal::ETWJITInterface::IsolateLoadScriptData::EnableLogWithFilterDataOnAllIsolates(), v8::internal::FreeCurrentEmbeddedBlob(), v8::base::OS::GetRandomMmapAddr(), v8::internal::compiler::turboshaft::SupportedOperations::Initialize(), v8::internal::Isolate::InitializeBuiltinJSDispatchTable(), v8::internal::Isolate::InitializeDefaultEmbeddedBlob(), v8::internal::anonymous_namespace{runtime-test-wasm.cc}::IsWasmCompileAllowed(), v8::internal::anonymous_namespace{runtime-test-wasm.cc}::IsWasmInstantiateAllowed(), cppgc::internal::ProcessGlobalLock::Lock(), v8::Shell::LookupCodeCache(), v8::internal::ETWJITInterface::IsolateLoadScriptData::MaybeAddLoadedScript(), v8::base::RandomNumberGenerator::RandomNumberGenerator(), cppgc::internal::HeapRegistry::RegisterHeap(), v8::internal::ETWJITInterface::IsolateLoadScriptData::RemoveIsolate(), v8::base::RandomNumberGenerator::SetEntropySource(), v8::base::OS::SetRandomMmapSeed(), v8::internal::SetSnapshotFromFile(), v8::Shell::StoreInCodeCache(), v8::internal::Isolate::TearDownEmbeddedBlob(), cppgc::internal::HeapRegistry::TryFromManagedPointer(), cppgc::internal::ProcessGlobalLock::Unlock(), cppgc::internal::HeapRegistry::UnregisterHeap(), and v8::internal::ETWJITInterface::IsolateLoadScriptData::UpdateAllIsolates().
Member Data Documentation
once_
template<typename T , typename AllocationTrait , typename CreateTrait , typename InitOnceTrait , typename DestroyTrait >
OnceType v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::once_ [mutable]
Definition at line 191 of file lazy-instance.h.
Referenced by v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::Init().
storage_
template<typename T , typename AllocationTrait , typename CreateTrait , typename InitOnceTrait , typename DestroyTrait >
StorageType v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::storage_ [mutable]
Definition at line 192 of file lazy-instance.h.
Referenced by v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::Get(), v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::Init(), and v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::Pointer().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/base/lazy-instance.h