wasm::EngineImpl Struct Reference
Public Member Functions
EngineImpl ()
~EngineImpl ()
Public Attributes
std::unique_ptr< v8::Platform > platform
Static Public Attributes
static bool created = false
Detailed Description
Definition at line 329 of file c-api.cc.
Constructor & Destructor Documentation
EngineImpl()
wasm::EngineImpl::EngineImpl () [inline]
Definition at line 376 of file c-api.cc.
               {
    assert(!created);
    created = true;
#if DUMP_COUNTERS
    counter_map_ = new CounterMap();
#endif
  }
References anonymous_namespace{mksnapshot.cc}::counter_map_, and created.
 EngineImpl()
wasm::EngineImpl::~EngineImpl () [inline]
Definition at line 384 of file c-api.cc.
                {
#if DUMP_COUNTERS
    std::vector<std::pair<std::string, Counter*>> counters(
        counter_map_->begin(), counter_map_->end());
    std::sort(counters.begin(), counters.end());
    // Dump counters in formatted boxes.
    constexpr int kNameBoxSize = 64;
    constexpr int kValueBoxSize = 13;
    std::cout << "+" << std::string(kNameBoxSize, '-') << "+"
              << std::string(kValueBoxSize, '-') << "+\n";
    std::cout << "| Name" << std::string(kNameBoxSize - 5, ' ') << "| Value"
              << std::string(kValueBoxSize - 6, ' ') << "|\n";
    std::cout << "+" << std::string(kNameBoxSize, '-') << "+"
              << std::string(kValueBoxSize, '-') << "+\n";
    for (const auto& pair : counters) {
      std::string key = pair.first;
      Counter* counter = pair.second;
      if (counter->is_histogram()) {
        std::cout << "| c:" << std::setw(kNameBoxSize - 4) << std::left << key
                  << " | " << std::setw(kValueBoxSize - 2) << std::right
                  << counter->count() << " |\n";
        std::cout << "| t:" << std::setw(kNameBoxSize - 4) << std::left << key
                  << " | " << std::setw(kValueBoxSize - 2) << std::right
                  << counter->sample_total() << " |\n";
      } else {
        std::cout << "| " << std::setw(kNameBoxSize - 2) << std::left << key
                  << " | " << std::setw(kValueBoxSize - 2) << std::right
                  << counter->count() << " |\n";
      }
    }
    std::cout << "+" << std::string(kNameBoxSize, '-') << "+"
              << std::string(kValueBoxSize, '-') << "+\n";
    delete counter_map_;
#endif
    v8::V8::Dispose();
    v8::V8::DisposePlatform();
  }
References anonymous_namespace{mksnapshot.cc}::counter_map_, v8::V8::Dispose(), v8::V8::DisposePlatform(), v8::internal::key, v8::base::sort(), and v8::internal::string.
Member Data Documentation
created
bool wasm::EngineImpl::created = false [static]
Definition at line 330 of file c-api.cc.
Referenced by EngineImpl().
platform
std::unique_ptr<v8::Platform> wasm::EngineImpl::platform
Definition at line 332 of file c-api.cc.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/wasm/c-api.cc