v8::internal::compiler::BinopMatcher< Left, Right, rep > Struct Template Reference
#include <node-matchers.h>
Public Types
using LeftMatcher = Left
using RightMatcher = Right
Public Member Functions
BinopMatcher (Node *node)
BinopMatcher (Node *node, bool allow_input_swap)
const Left & left () const
const Right & right () const
bool IsFoldable () const
bool LeftEqualsRight () const
bool OwnsInput (Node *input)
Static Public Attributes
static constexpr MachineRepresentation representation = rep
Protected Member Functions
void SwapInputs ()
Private Member Functions
void PutConstantOnRight ()
Private Attributes
Left left_
Right right_
Detailed Description
template<typename Left, typename Right, MachineRepresentation rep>
struct v8::internal::compiler::BinopMatcher< Left, Right, rep >
Definition at line 286 of file node-matchers.h.
Member Typedef Documentation
LeftMatcher
template<typename Left , typename Right , MachineRepresentation rep>
using v8::internal::compiler::BinopMatcher< Left, Right, rep >::LeftMatcher = Left
Definition at line 296 of file node-matchers.h.
RightMatcher
template<typename Left , typename Right , MachineRepresentation rep>
using v8::internal::compiler::BinopMatcher< Left, Right, rep >::RightMatcher = Right
Definition at line 297 of file node-matchers.h.
Constructor & Destructor Documentation
BinopMatcher() [1/2]
template<typename Left , typename Right , MachineRepresentation rep>
v8::internal::compiler::BinopMatcher< Left, Right, rep >::BinopMatcher (Node * node) [inline], [explicit]
Definition at line 287 of file node-matchers.h.
      : NodeMatcher(node), left_(InputAt(0)), right_(InputAt(1)) {
    if (HasProperty(Operator::kCommutative)) PutConstantOnRight();
  }
References v8::internal::compiler::NodeMatcher::HasProperty(), v8::internal::compiler::Operator::kCommutative, and v8::internal::compiler::BinopMatcher< Left, Right, rep >::PutConstantOnRight().
BinopMatcher() [2/2]
template<typename Left , typename Right , MachineRepresentation rep>
v8::internal::compiler::BinopMatcher< Left, Right, rep >::BinopMatcher (Node * node, bool allow_input_swap) [inline]
Definition at line 291 of file node-matchers.h.
      : NodeMatcher(node), left_(InputAt(0)), right_(InputAt(1)) {
    if (allow_input_swap) PutConstantOnRight();
  }
References v8::internal::compiler::BinopMatcher< Left, Right, rep >::PutConstantOnRight().
Member Function Documentation
IsFoldable()
template<typename Left , typename Right , MachineRepresentation rep>
bool v8::internal::compiler::BinopMatcher< Left, Right, rep >::IsFoldable () const [inline]
Definition at line 304 of file node-matchers.h.
                          {
    return left().HasResolvedValue() && right().HasResolvedValue();
  }
References v8::internal::compiler::BinopMatcher< Left, Right, rep >::left(), and v8::internal::compiler::BinopMatcher< Left, Right, rep >::right().
Referenced by v8::internal::compiler::MachineOperatorReducer::Reduce(), v8::internal::compiler::MachineOperatorReducer::ReduceFloat64Compare(), v8::internal::compiler::MachineOperatorReducer::ReduceInt32Add(), v8::internal::compiler::MachineOperatorReducer::ReduceInt32Div(), v8::internal::compiler::MachineOperatorReducer::ReduceInt32Mod(), v8::internal::compiler::MachineOperatorReducer::ReduceInt32Sub(), v8::internal::compiler::MachineOperatorReducer::ReduceInt64Add(), v8::internal::compiler::MachineOperatorReducer::ReduceInt64Div(), v8::internal::compiler::MachineOperatorReducer::ReduceInt64Mod(), v8::internal::compiler::MachineOperatorReducer::ReduceInt64Mul(), v8::internal::compiler::MachineOperatorReducer::ReduceInt64Sub(), v8::internal::compiler::MachineOperatorReducer::ReduceProjection(), v8::internal::compiler::MachineOperatorReducer::ReduceUint32Div(), v8::internal::compiler::MachineOperatorReducer::ReduceUint32Mod(), v8::internal::compiler::MachineOperatorReducer::ReduceUint64Div(), v8::internal::compiler::MachineOperatorReducer::ReduceUint64Mod(), v8::internal::compiler::MachineOperatorReducer::ReduceWord32Equal(), v8::internal::compiler::MachineOperatorReducer::ReduceWord32Sar(), v8::internal::compiler::MachineOperatorReducer::ReduceWord32Shl(), v8::internal::compiler::MachineOperatorReducer::ReduceWord32Shr(), v8::internal::compiler::MachineOperatorReducer::ReduceWord64Equal(), v8::internal::compiler::MachineOperatorReducer::ReduceWord64Sar(), v8::internal::compiler::MachineOperatorReducer::ReduceWord64Shl(), and v8::internal::compiler::MachineOperatorReducer::ReduceWord64Shr().
left()
template<typename Left , typename Right , MachineRepresentation rep>
const Left& v8::internal::compiler::BinopMatcher< Left, Right, rep >::left () const [inline]
Definition at line 301 of file node-matchers.h.
{ return left_; }
References v8::internal::compiler::BinopMatcher< Left, Right, rep >::left_.
Referenced by v8::internal::compiler::anonymous_namespace{machine-operator-reducer.cc}::BitfieldCheck::Detect(), v8::internal::compiler::AddMatcher< BinopMatcher, AddOpcode, SubOpcode, kMulOpcode, kShiftOpcode >::IndexInput(), v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::Initialize(), v8::internal::compiler::AddMatcher< BinopMatcher, AddOpcode, SubOpcode, kMulOpcode, kShiftOpcode >::Initialize(), v8::internal::compiler::SimplifiedLowering::Int32Div(), v8::internal::compiler::SimplifiedLowering::Int32Mod(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::IsFoldable(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::LeftEqualsRight(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::PutConstantOnRight(), v8::internal::compiler::SimplifiedOperatorReducer::Reduce(), v8::internal::compiler::MachineOperatorReducer::Reduce(), v8::internal::compiler::MachineOperatorReducer::ReduceFloat64Compare(), v8::internal::compiler::MachineOperatorReducer::ReduceInt32Add(), v8::internal::compiler::MachineOperatorReducer::ReduceInt32Div(), v8::internal::compiler::MachineOperatorReducer::ReduceInt32Mod(), v8::internal::compiler::MachineOperatorReducer::ReduceInt32Sub(), v8::internal::compiler::MachineOperatorReducer::ReduceInt64Add(), v8::internal::compiler::MachineOperatorReducer::ReduceInt64Div(), v8::internal::compiler::MachineOperatorReducer::ReduceInt64Mod(), v8::internal::compiler::MachineOperatorReducer::ReduceInt64Mul(), v8::internal::compiler::MachineOperatorReducer::ReduceInt64Sub(), v8::internal::compiler::CommonOperatorReducer::ReducePhi(), v8::internal::compiler::MachineOperatorReducer::ReduceProjection(), v8::internal::compiler::CommonOperatorReducer::ReduceSelect(), v8::internal::compiler::MachineOperatorReducer::ReduceStore(), v8::internal::compiler::MachineOperatorReducer::ReduceUint32Div(), v8::internal::compiler::MachineOperatorReducer::ReduceUint32Mod(), v8::internal::compiler::MachineOperatorReducer::ReduceUint64Div(), v8::internal::compiler::MachineOperatorReducer::ReduceUint64Mod(), v8::internal::compiler::MachineOperatorReducer::ReduceWord32And(), v8::internal::compiler::MachineOperatorReducer::ReduceWord32Comparisons(), v8::internal::compiler::MachineOperatorReducer::ReduceWord32Equal(), v8::internal::compiler::MachineOperatorReducer::ReduceWord32Sar(), v8::internal::compiler::MachineOperatorReducer::ReduceWord32Shifts(), v8::internal::compiler::MachineOperatorReducer::ReduceWord32Shl(), v8::internal::compiler::MachineOperatorReducer::ReduceWord32Shr(), v8::internal::compiler::MachineOperatorReducer::ReduceWord32Xor(), v8::internal::compiler::MachineOperatorReducer::ReduceWord64Comparisons(), v8::internal::compiler::MachineOperatorReducer::ReduceWord64Equal(), v8::internal::compiler::MachineOperatorReducer::ReduceWord64Sar(), v8::internal::compiler::MachineOperatorReducer::ReduceWord64Shl(), v8::internal::compiler::MachineOperatorReducer::ReduceWord64Shr(), v8::internal::compiler::JSBinopReduction::ShouldCreateConsString(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::SwapInputs(), v8::internal::compiler::anonymous_namespace{machine-operator-reducer.cc}::TryGetInvertedCondition(), v8::internal::compiler::MachineOperatorReducer::TryMatchWord32Ror(), v8::internal::compiler::SimplifiedLowering::Uint32Div(), v8::internal::compiler::SimplifiedLowering::Uint32Mod(), and v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWord64Shift().
LeftEqualsRight()
template<typename Left , typename Right , MachineRepresentation rep>
bool v8::internal::compiler::BinopMatcher< Left, Right, rep >::LeftEqualsRight () const [inline]
Definition at line 307 of file node-matchers.h.
{ return left().node() == right().node(); }
References v8::internal::compiler::BinopMatcher< Left, Right, rep >::left(), and v8::internal::compiler::BinopMatcher< Left, Right, rep >::right().
Referenced by v8::internal::compiler::MachineOperatorReducer::Reduce(), v8::internal::compiler::MachineOperatorReducer::ReduceInt32Div(), v8::internal::compiler::MachineOperatorReducer::ReduceInt32Mod(), v8::internal::compiler::MachineOperatorReducer::ReduceInt32Sub(), v8::internal::compiler::MachineOperatorReducer::ReduceInt64Div(), v8::internal::compiler::MachineOperatorReducer::ReduceInt64Mod(), v8::internal::compiler::MachineOperatorReducer::ReduceInt64Sub(), v8::internal::compiler::MachineOperatorReducer::ReduceUint32Div(), v8::internal::compiler::MachineOperatorReducer::ReduceUint32Mod(), v8::internal::compiler::MachineOperatorReducer::ReduceUint64Div(), v8::internal::compiler::MachineOperatorReducer::ReduceUint64Mod(), v8::internal::compiler::MachineOperatorReducer::ReduceWord32Equal(), and v8::internal::compiler::MachineOperatorReducer::ReduceWord64Equal().
OwnsInput()
template<typename Left , typename Right , MachineRepresentation rep>
bool v8::internal::compiler::BinopMatcher< Left, Right, rep >::OwnsInput (Node * input) [inline]
Definition at line 309 of file node-matchers.h.
                              {
    for (Node* use : input->uses()) {
      if (use != node()) {
        return false;
      }
    }
    return true;
  }
References v8::internal::compiler::NodeMatcher::node(), use(), and v8::internal::compiler::Node::uses().
Referenced by v8::internal::compiler::MachineOperatorReducer::Reduce(), v8::internal::compiler::MachineOperatorReducer::ReduceInt32Add(), v8::internal::compiler::MachineOperatorReducer::ReduceInt64Add(), and v8::internal::compiler::MachineOperatorReducer::ReduceInt64Mul().
PutConstantOnRight()
template<typename Left , typename Right , MachineRepresentation rep>
void v8::internal::compiler::BinopMatcher< Left, Right, rep >::PutConstantOnRight () [inline], [private]
Definition at line 329 of file node-matchers.h.
                            {
    if (left().HasResolvedValue() && !right().HasResolvedValue()) {
      SwapInputs();
    }
  }
References v8::internal::compiler::BinopMatcher< Left, Right, rep >::left(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::right(), and v8::internal::compiler::BinopMatcher< Left, Right, rep >::SwapInputs().
Referenced by v8::internal::compiler::BinopMatcher< Left, Right, rep >::BinopMatcher().
right()
template<typename Left , typename Right , MachineRepresentation rep>
const Right& v8::internal::compiler::BinopMatcher< Left, Right, rep >::right () const [inline]
Definition at line 302 of file node-matchers.h.
{ return right_; }
References v8::internal::compiler::BinopMatcher< Left, Right, rep >::right_.
Referenced by v8::internal::compiler::anonymous_namespace{machine-operator-reducer.cc}::BitfieldCheck::Detect(), v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::Initialize(), v8::internal::compiler::AddMatcher< BinopMatcher, AddOpcode, SubOpcode, kMulOpcode, kShiftOpcode >::Initialize(), v8::internal::compiler::SimplifiedLowering::Int32Div(), v8::internal::compiler::SimplifiedLowering::Int32Mod(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::IsFoldable(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::LeftEqualsRight(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::PutConstantOnRight(), v8::internal::compiler::SimplifiedOperatorReducer::Reduce(), v8::internal::compiler::MachineOperatorReducer::Reduce(), v8::internal::compiler::MachineOperatorReducer::ReduceFloat64Compare(), v8::internal::compiler::MachineOperatorReducer::ReduceInt32Add(), v8::internal::compiler::MachineOperatorReducer::ReduceInt32Div(), v8::internal::compiler::MachineOperatorReducer::ReduceInt32Mod(), v8::internal::compiler::MachineOperatorReducer::ReduceInt32Sub(), v8::internal::compiler::MachineOperatorReducer::ReduceInt64Add(), v8::internal::compiler::MachineOperatorReducer::ReduceInt64Div(), v8::internal::compiler::MachineOperatorReducer::ReduceInt64Mod(), v8::internal::compiler::MachineOperatorReducer::ReduceInt64Mul(), v8::internal::compiler::MachineOperatorReducer::ReduceInt64Sub(), v8::internal::compiler::CommonOperatorReducer::ReducePhi(), v8::internal::compiler::MachineOperatorReducer::ReduceProjection(), v8::internal::compiler::CommonOperatorReducer::ReduceSelect(), v8::internal::compiler::MachineOperatorReducer::ReduceStore(), v8::internal::compiler::MachineOperatorReducer::ReduceUint32Div(), v8::internal::compiler::MachineOperatorReducer::ReduceUint32Mod(), v8::internal::compiler::MachineOperatorReducer::ReduceUint64Div(), v8::internal::compiler::MachineOperatorReducer::ReduceUint64Mod(), v8::internal::compiler::MachineOperatorReducer::ReduceWord32And(), v8::internal::compiler::MachineOperatorReducer::ReduceWord32Comparisons(), v8::internal::compiler::MachineOperatorReducer::ReduceWord32Equal(), v8::internal::compiler::MachineOperatorReducer::ReduceWord32Sar(), v8::internal::compiler::MachineOperatorReducer::ReduceWord32Shifts(), v8::internal::compiler::MachineOperatorReducer::ReduceWord32Shl(), v8::internal::compiler::MachineOperatorReducer::ReduceWord32Shr(), v8::internal::compiler::MachineOperatorReducer::ReduceWord32Xor(), v8::internal::compiler::MachineOperatorReducer::ReduceWord64Comparisons(), v8::internal::compiler::MachineOperatorReducer::ReduceWord64Equal(), v8::internal::compiler::MachineOperatorReducer::ReduceWord64Sar(), v8::internal::compiler::MachineOperatorReducer::ReduceWord64Shl(), v8::internal::compiler::MachineOperatorReducer::ReduceWord64Shr(), v8::internal::compiler::ScaleMatcher< BinopMatcher, kMulOpcode, kShiftOpcode >::ScaleMatcher(), v8::internal::compiler::JSBinopReduction::ShouldCreateConsString(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::SwapInputs(), v8::internal::compiler::anonymous_namespace{machine-operator-reducer.cc}::TryGetInvertedCondition(), v8::internal::compiler::MachineOperatorReducer::TryMatchWord32Ror(), v8::internal::compiler::SimplifiedLowering::Uint32Div(), v8::internal::compiler::SimplifiedLowering::Uint32Mod(), and v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWord64Shift().
SwapInputs()
template<typename Left , typename Right , MachineRepresentation rep>
void v8::internal::compiler::BinopMatcher< Left, Right, rep >::SwapInputs () [inline], [protected]
Definition at line 319 of file node-matchers.h.
                    {
    std::swap(left_, right_);
    // TODO(turbofan): This modification should notify the reducers using
    // BinopMatcher. Alternatively, all reducers (especially value numbering)
    // could ignore the ordering for commutative binops.
    node()->ReplaceInput(0, left().node());
    node()->ReplaceInput(1, right().node());
  }
References v8::internal::compiler::BinopMatcher< Left, Right, rep >::left(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::left_, v8::internal::compiler::NodeMatcher::node(), v8::internal::compiler::Node::ReplaceInput(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::right(), and v8::internal::compiler::BinopMatcher< Left, Right, rep >::right_.
Referenced by v8::internal::compiler::AddMatcher< BinopMatcher, AddOpcode, SubOpcode, kMulOpcode, kShiftOpcode >::Initialize(), and v8::internal::compiler::BinopMatcher< Left, Right, rep >::PutConstantOnRight().
Member Data Documentation
left_
template<typename Left , typename Right , MachineRepresentation rep>
Left v8::internal::compiler::BinopMatcher< Left, Right, rep >::left_ [private]
Definition at line 335 of file node-matchers.h.
Referenced by v8::internal::compiler::BinopMatcher< Left, Right, rep >::left(), and v8::internal::compiler::BinopMatcher< Left, Right, rep >::SwapInputs().
representation
template<typename Left , typename Right , MachineRepresentation rep>
constexpr MachineRepresentation v8::internal::compiler::BinopMatcher< Left, Right, rep >::representation = rep [static], [constexpr]
Definition at line 299 of file node-matchers.h.
right_
template<typename Left , typename Right , MachineRepresentation rep>
Right v8::internal::compiler::BinopMatcher< Left, Right, rep >::right_ [private]
Definition at line 336 of file node-matchers.h.
Referenced by v8::internal::compiler::BinopMatcher< Left, Right, rep >::right(), and v8::internal::compiler::BinopMatcher< Left, Right, rep >::SwapInputs().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/node-matchers.h