v8::internal::compiler::turboshaft::ComparisonOp Struct Reference
#include <operations.h>
Public Types
enum class Kind : uint8_t {
kEqual
, kSignedLessThan
, kSignedLessThanOrEqual
, kUnsignedLessThan
,
kUnsignedLessThanOrEqual
 }
Public Member Functions
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
template<typename T = Any>
V< T > left () const
template<typename T = Any>
V< T > right () const
ComparisonOp (V< Any > left, V< Any > right, Kind kind, RegisterRepresentation rep)
void Validate (const Graph &graph) const
auto options () const
Static Public Member Functions
static bool IsCommutative (Kind kind)
Public Attributes
Kind kind
RegisterRepresentation rep
Static Public Attributes
static constexpr OpEffects effects = OpEffects()
Additional Inherited Members
Detailed Description
Definition at line 2069 of file operations.h.
Member Enumeration Documentation
Kind
enum v8::internal::compiler::turboshaft::ComparisonOp::Kind : uint8_t [strong]
Enumerator
kEqual
kSignedLessThan
kSignedLessThanOrEqual
kUnsignedLessThan
kUnsignedLessThanOrEqual
Definition at line 2070 of file operations.h.
                  : uint8_t {
    kEqual,
    kSignedLessThan,
    kSignedLessThanOrEqual,
    kUnsignedLessThan,
    kUnsignedLessThanOrEqual
  };
Constructor & Destructor Documentation
ComparisonOp()
v8::internal::compiler::turboshaft::ComparisonOp::ComparisonOp (V< Any > left, V< Any > right, Kind kind, RegisterRepresentation rep) [inline]
Definition at line 2103 of file operations.h.
      : Base(left, right), kind(kind), rep(rep) {}
Member Function Documentation
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::ComparisonOp::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 2085 of file operations.h.
                                                              {
    return InputsRepFactory::PairOf(rep);
  }
References v8::internal::compiler::turboshaft::InputsRepFactory::PairOf().
IsCommutative()
static bool v8::internal::compiler::turboshaft::ComparisonOp::IsCommutative (Kind kind) [inline], [static]
Definition at line 2090 of file operations.h.
{ return kind == Kind::kEqual; }
References v8::internal::kEqual.
Referenced by v8::internal::compiler::turboshaft::InstructionSelectionNormalizationReducer< Next >::Comparison(), v8::internal::compiler::InstructionSelector::IsCommutative(), and v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitWordCompare().
left()
template<typename T = Any>
V<T> v8::internal::compiler::turboshaft::ComparisonOp::left () const [inline]
Definition at line 2093 of file operations.h.
                    {
    DCHECK(IsValidTypeFor<T>(rep));
    return input<T>(0);
  }
References v8::internal::DCHECK().
Referenced by v8::internal::compiler::turboshaft::CombineFlagSettingOps(), v8::internal::compiler::turboshaft::FindCompareChain(), v8::internal::compiler::turboshaft::DuplicationOptimizationReducer< Next >::MaybeDuplicateComparison(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessComparison(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitFloat32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitFloat32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitFloat32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitFloat32Compare(), v8::internal::compiler::VisitFloat32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitFloat32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitFloat64Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitFloat64Compare(), and v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitWordCompare().
options()
auto v8::internal::compiler::turboshaft::ComparisonOp::options () const [inline]
Definition at line 2138 of file operations.h.
{ return std::tuple{kind, rep}; }
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::ComparisonOp::outputs_rep () const [inline]
Definition at line 2081 of file operations.h.
                                                               {
    return RepVector<RegisterRepresentation::Word32()>();
  }
right()
template<typename T = Any>
V<T> v8::internal::compiler::turboshaft::ComparisonOp::right () const [inline]
Definition at line 2098 of file operations.h.
                     {
    DCHECK(IsValidTypeFor<T>(rep));
    return input<T>(1);
  }
References v8::internal::DCHECK().
Referenced by v8::internal::compiler::turboshaft::CombineFlagSettingOps(), v8::internal::compiler::turboshaft::FindCompareChain(), v8::internal::compiler::turboshaft::DuplicationOptimizationReducer< Next >::MaybeDuplicateComparison(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessComparison(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitFloat32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitFloat32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitFloat32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitFloat32Compare(), v8::internal::compiler::VisitFloat32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitFloat32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitFloat64Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitFloat64Compare(), and v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitWordCompare().
Validate()
void v8::internal::compiler::turboshaft::ComparisonOp::Validate (const Graph & graph) const [inline]
Definition at line 2106 of file operations.h.
                                          {
    if (kind == Kind::kEqual) {
      DCHECK(rep == any_of(RegisterRepresentation::Word32(),
                           RegisterRepresentation::Word64(),
                           RegisterRepresentation::Float32(),
                           RegisterRepresentation::Float64(),
                           RegisterRepresentation::Tagged()));
      RegisterRepresentation input_rep = rep;
#ifdef V8_COMPRESS_POINTERS
      // In the presence of pointer compression, we only compare the lower
      // 32bit.
      if (input_rep == RegisterRepresentation::Tagged()) {
        input_rep = RegisterRepresentation::Compressed();
      }
#endif // V8_COMPRESS_POINTERS
#ifdef DEBUG
      ValidateOpInputRep(graph, left(), input_rep);
      ValidateOpInputRep(graph, right(), input_rep);
#endif // DEBUG
      USE(input_rep);
    } else {
      DCHECK_EQ(rep, any_of(RegisterRepresentation::Word32(),
                            RegisterRepresentation::Word64(),
                            RegisterRepresentation::Float32(),
                            RegisterRepresentation::Float64()));
      DCHECK_IMPLIES(
          rep == any_of(RegisterRepresentation::Float32(),
                        RegisterRepresentation::Float64()),
          kind == any_of(Kind::kSignedLessThan, Kind::kSignedLessThanOrEqual));
    }
  }
References v8::base::any_of(), v8::internal::compiler::turboshaft::RegisterRepresentation::Compressed(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::compiler::turboshaft::RegisterRepresentation::Float32(), v8::internal::compiler::turboshaft::RegisterRepresentation::Float64(), graph(), v8::internal::kEqual, v8::internal::compiler::kSignedLessThan, v8::internal::compiler::kSignedLessThanOrEqual, v8::internal::compiler::turboshaft::RegisterRepresentation::Tagged(), USE, v8::internal::compiler::turboshaft::RegisterRepresentation::Word32(), and v8::internal::compiler::turboshaft::RegisterRepresentation::Word64().
Member Data Documentation
effects
constexpr OpEffects v8::internal::compiler::turboshaft::ComparisonOp::effects = OpEffects() [static], [constexpr]
Definition at line 2080 of file operations.h.
kind
Kind v8::internal::compiler::turboshaft::ComparisonOp::kind
Definition at line 2077 of file operations.h.
Referenced by v8::internal::compiler::turboshaft::FindCompareChain(), v8::internal::compiler::InstructionSelector::GetComparisonFlagCondition(), v8::internal::compiler::turboshaft::DuplicationOptimizationReducer< Next >::MaybeDuplicateComparison(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessComparison(), and v8::internal::compiler::InstructionSelector::VisitNode().
rep
RegisterRepresentation v8::internal::compiler::turboshaft::ComparisonOp::rep
Definition at line 2078 of file operations.h.
Referenced by v8::internal::compiler::turboshaft::CombineFlagSettingOps(), v8::internal::compiler::turboshaft::DuplicationOptimizationReducer< Next >::MaybeDuplicateComparison(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessComparison(), v8::internal::compiler::turboshaft::TryMatchConditionalCompareChainBranch(), v8::internal::compiler::turboshaft::TryMatchConditionalCompareChainSet(), and v8::internal::compiler::InstructionSelector::VisitNode().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h