v8::internal::compiler::turboshaft::TailCallOp Struct Reference
#include <operations.h>
Public Member Functions
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
OpIndex callee () const
base::Vector< const OpIndex > arguments () const
TailCallOp (OpIndex callee, base::Vector< const OpIndex > arguments, const TSCallDescriptor *descriptor)
template<typename Fn , typename Mapper >
auto Explode (Fn fn, Mapper &mapper) const
auto options () const
void PrintOptions (std::ostream &os) const
Static Public Member Functions
static TailCallOp & New (Graph *graph, OpIndex callee, base::Vector< const OpIndex > arguments, const TSCallDescriptor *descriptor)
Public Attributes
const TSCallDescriptor * descriptor
Static Public Attributes
static constexpr OpEffects effects = OpEffects().CanLeaveCurrentFunction()
Additional Inherited Members
Detailed Description
Definition at line 4274 of file operations.h.
Constructor & Destructor Documentation
TailCallOp()
v8::internal::compiler::turboshaft::TailCallOp::TailCallOp (OpIndex callee, base::Vector< const OpIndex > arguments, const TSCallDescriptor * descriptor) [inline]
Definition at line 4315 of file operations.h.
      : Base(1 + arguments.size()), descriptor(descriptor) {
    base::Vector<OpIndex> inputs = this->inputs();
    inputs[0] = callee;
    inputs.SubVector(1, inputs.size()).OverwriteWith(arguments);
  }
References v8::base::Vector< T >::size(), and v8::base::Vector< T >::SubVector().
Member Function Documentation
arguments()
base::Vector<const OpIndex> v8::internal::compiler::turboshaft::TailCallOp::arguments () const [inline]
Definition at line 4311 of file operations.h.
                                              {
    return inputs().SubVector(1, input_count);
  }
References v8::internal::compiler::turboshaft::detail::input_count().
Referenced by v8::internal::compiler::turboshaft::CallView::CallView(), and v8::internal::compiler::InstructionSelector::VisitTailCall().
callee()
OpIndex v8::internal::compiler::turboshaft::TailCallOp::callee () const [inline]
Definition at line 4310 of file operations.h.
{ return input(0); }
Referenced by v8::internal::compiler::turboshaft::CallView::CallView(), and v8::internal::compiler::InstructionSelector::VisitTailCall().
Explode()
template<typename Fn , typename Mapper >
auto v8::internal::compiler::turboshaft::TailCallOp::Explode (Fn fn, Mapper & mapper) const [inline]
Definition at line 4324 of file operations.h.
                                                      {
    OpIndex mapped_callee = mapper.Map(callee());
    auto mapped_arguments = mapper.template Map<16>(arguments());
    return fn(mapped_callee, base::VectorOf(mapped_arguments), descriptor);
  }
References v8::base::VectorOf().
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::TailCallOp::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 4286 of file operations.h.
                                                              {
    storage.resize(input_count);
    size_t i = 0;
#ifdef V8_ENABLE_WEBASSEMBLY
    if (descriptor->descriptor->IsIndirectWasmFunctionCall()) {
      storage[i++] = MaybeRegisterRepresentation::Word32();
    } else if (descriptor->descriptor->IsDirectWasmFunctionCall() ||
               descriptor->descriptor->IsWasmImportWrapper() ||
               descriptor->descriptor->IsWasmCapiFunction()) {
      storage[i++] = MaybeRegisterRepresentation::WordPtr();
    } else {
      storage[i++] = MaybeRegisterRepresentation::Tagged();
    }
#else
    storage[i++] = MaybeRegisterRepresentation::Tagged();
#endif
    for (auto rep : descriptor->in_reps) {
      storage[i++] = rep;
    }
    storage.resize(i);
    return base::VectorOf(storage);
  }
References v8::internal::compiler::turboshaft::TSCallDescriptor::descriptor, v8::internal::compiler::turboshaft::TSCallDescriptor::in_reps, v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::ZoneVector< T >::resize(), v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::Tagged(), v8::base::VectorOf(), v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::Word32(), and v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::WordPtr().
New()
static TailCallOp& v8::internal::compiler::turboshaft::TailCallOp::New (Graph * graph, OpIndex callee, base::Vector< const OpIndex > arguments, const TSCallDescriptor * descriptor) [inline], [static]
Definition at line 4330 of file operations.h.
                                                             {
    return Base::New(graph, 1 + arguments.size(), callee, arguments,
                     descriptor);
  }
References graph(), v8::internal::anonymous_namespace{intl-objects.cc}::New(), and v8::base::Vector< T >::size().
options()
auto v8::internal::compiler::turboshaft::TailCallOp::options () const [inline]
Definition at line 4336 of file operations.h.
{ return std::tuple{descriptor}; }
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::TailCallOp::outputs_rep () const [inline]
Definition at line 4278 of file operations.h.
                                                               {
    // While TailCalls do return some values, those values are returned to the
    // caller rather than to the current function (and a TailCallOp thus never
    // has any uses), so we set the outputs_rep to empty. If you need to know
    // what a TailCallOp returns, you can find out in `descriptor->outputs_rep`.
    return {};
  }
Referenced by v8::internal::compiler::InstructionSelector::VisitTailCall().
PrintOptions()
void v8::internal::compiler::turboshaft::TailCallOp::PrintOptions (std::ostream & os) const
Definition at line 70 of file operations.cc.
                                                  {
  os << '[' << *descriptor->descriptor << ']';
}
References v8::internal::compiler::turboshaft::TSCallDescriptor::descriptor, and descriptor.
Member Data Documentation
descriptor
const TSCallDescriptor* v8::internal::compiler::turboshaft::TailCallOp::descriptor
Definition at line 4275 of file operations.h.
Referenced by v8::internal::compiler::turboshaft::CallView::CallView(), PrintOptions(), and v8::internal::compiler::InstructionSelector::VisitTailCall().
effects
constexpr OpEffects v8::internal::compiler::turboshaft::TailCallOp::effects = OpEffects().CanLeaveCurrentFunction() [static], [constexpr]
Definition at line 4277 of file operations.h.
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h
/mnt/V8SourceCode/src/compiler/turboshaft/operations.cc