v8::internal::RegExpCompiler::CompilationResult Struct Reference
#include <regexp-compiler.h>
Public Member Functions
CompilationResult (RegExpError err)
CompilationResult (DirectHandle< Object > code, int registers)
bool Succeeded () const
Static Public Member Functions
static CompilationResult RegExpTooBig ()
Public Attributes
const RegExpError error = RegExpError::kNone
DirectHandle< Object > code
int num_registers = 0
Detailed Description
Definition at line 492 of file regexp-compiler.h.
Constructor & Destructor Documentation
CompilationResult() [1/2]
v8::internal::RegExpCompiler::CompilationResult::CompilationResult (RegExpError err) [inline], [explicit]
Definition at line 493 of file regexp-compiler.h.
: error(err) {}
Referenced by RegExpTooBig().
CompilationResult() [2/2]
v8::internal::RegExpCompiler::CompilationResult::CompilationResult (DirectHandle< Object > code, int registers) [inline]
Definition at line 494 of file regexp-compiler.h.
        : code(code), num_registers(registers) {}
Member Function Documentation
RegExpTooBig()
static CompilationResult v8::internal::RegExpCompiler::CompilationResult::RegExpTooBig () [inline], [static]
Definition at line 497 of file regexp-compiler.h.
                                            {
      return CompilationResult(RegExpError::kTooLarge);
    }
References CompilationResult().
Referenced by v8::internal::RegExpCompiler::Assemble().
Succeeded()
bool v8::internal::RegExpCompiler::CompilationResult::Succeeded () const [inline]
Definition at line 501 of file regexp-compiler.h.
{ return error == RegExpError::kNone; }
References error.
Member Data Documentation
code
DirectHandle<Object> v8::internal::RegExpCompiler::CompilationResult::code
Definition at line 504 of file regexp-compiler.h.
error
const RegExpError v8::internal::RegExpCompiler::CompilationResult::error = RegExpError::kNone
Definition at line 503 of file regexp-compiler.h.
Referenced by Succeeded().
num_registers
int v8::internal::RegExpCompiler::CompilationResult::num_registers = 0
Definition at line 505 of file regexp-compiler.h.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/regexp/regexp-compiler.h