v8::internal::compiler::turboshaft::FastApiCallParameters Struct Reference
#include <operations.h>
Public Member Functions
const CFunctionInfo * c_signature () const
FastApiCallParameters (FastApiCallFunction c_function)
Static Public Member Functions
static const FastApiCallParameters * Create (FastApiCallFunction c_function, Zone *graph_zone)
Public Attributes
FastApiCallFunction c_function
Detailed Description
Definition at line 6428 of file operations.h.
Constructor & Destructor Documentation
FastApiCallParameters()
v8::internal::compiler::turboshaft::FastApiCallParameters::FastApiCallParameters (FastApiCallFunction c_function) [inline], [explicit]
Definition at line 6433 of file operations.h.
      : c_function(c_function) {}
Member Function Documentation
c_signature()
const CFunctionInfo* v8::internal::compiler::turboshaft::FastApiCallParameters::c_signature () const [inline]
Definition at line 6431 of file operations.h.
{ return c_function.signature; }
References v8::internal::compiler::FastApiCallFunction::signature.
Referenced by v8::internal::compiler::turboshaft::FastApiCallOp::argument_representation(), v8::internal::compiler::turboshaft::FastApiCallOp::inputs_rep(), and v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
Create()
static const FastApiCallParameters* v8::internal::compiler::turboshaft::FastApiCallParameters::Create (FastApiCallFunction c_function, Zone * graph_zone) [inline], [static]
Definition at line 6436 of file operations.h.
                                                               {
    return graph_zone->New<FastApiCallParameters>(c_function);
  }
References v8::internal::Zone::New().
Referenced by v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
Member Data Documentation
c_function
FastApiCallFunction v8::internal::compiler::turboshaft::FastApiCallParameters::c_function
Definition at line 6429 of file operations.h.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h