v8::internal::AccessorAssembler::StoreICParameters Struct Reference
#include <accessor-assembler.h>
Public Member Functions
StoreICParameters (TNode< Context > context, std::optional< TNode< JSAny >> receiver, TNode< Object > name, TNode< Object > value, std::optional< TNode< Smi >> flags, TNode< TaggedIndex > slot, TNode< HeapObject > vector, StoreICMode mode)
TNode< Context > context () const
TNode< JSAny > receiver () const
TNode< Object > name () const
TNode< Object > value () const
TNode< Smi > flags () const
TNode< TaggedIndex > slot () const
TNode< HeapObject > vector () const
TNode< Object > lookup_start_object () const
bool receiver_is_null () const
bool flags_is_null () const
bool IsDefineNamedOwn () const
bool IsDefineKeyedOwn () const
bool IsAnyDefineOwn () const
StubCache * stub_cache (Isolate *isolate) const
Private Attributes
TNode< Context > context_
std::optional< TNode< JSAny > > receiver_
TNode< Object > name_
TNode< Object > value_
std::optional< TNode< Smi > > flags_
TNode< TaggedIndex > slot_
TNode< HeapObject > vector_
StoreICMode mode_
Detailed Description
Definition at line 236 of file accessor-assembler.h.
Constructor & Destructor Documentation
StoreICParameters()
v8::internal::AccessorAssembler::StoreICParameters::StoreICParameters (TNode< Context > context, std::optional< TNode< JSAny >> receiver, TNode< Object > name, TNode< Object > value, std::optional< TNode< Smi >> flags, TNode< TaggedIndex > slot, TNode< HeapObject > vector, StoreICMode mode) [inline]
Definition at line 237 of file accessor-assembler.h.
        : context_(context),
          receiver_(receiver),
          name_(name),
          value_(value),
          flags_(flags),
          slot_(slot),
          vector_(vector),
          mode_(mode) {}
Member Function Documentation
context()
TNode<Context> v8::internal::AccessorAssembler::StoreICParameters::context () const [inline]
Definition at line 251 of file accessor-assembler.h.
{ return context_; }
Referenced by v8::internal::AccessorAssembler::DefineKeyedOwnIC(), v8::internal::KeyedStoreGenericAssembler::EmitGenericPropertyStore(), v8::internal::AccessorAssembler::HandleStoreICHandlerCase(), v8::internal::AccessorAssembler::HandleStoreICNativeDataProperty(), v8::internal::AccessorAssembler::HandleStoreICProtoHandler(), v8::internal::AccessorAssembler::HandleStoreToProxy(), v8::internal::AccessorAssembler::KeyedStoreIC(), v8::internal::AccessorAssembler::StoreGlobalIC(), v8::internal::AccessorAssembler::StoreIC(), and v8::internal::AccessorAssembler::StoreInArrayLiteralIC().
flags()
TNode<Smi> v8::internal::AccessorAssembler::StoreICParameters::flags () const [inline]
Definition at line 255 of file accessor-assembler.h.
{ return flags_.value(); }
Referenced by v8::internal::AccessorAssembler::DefineKeyedOwnIC().
flags_is_null()
bool v8::internal::AccessorAssembler::StoreICParameters::flags_is_null () const [inline]
Definition at line 262 of file accessor-assembler.h.
{ return !flags_.has_value(); }
Referenced by v8::internal::AccessorAssembler::StoreGlobalIC().
IsAnyDefineOwn()
bool v8::internal::AccessorAssembler::StoreICParameters::IsAnyDefineOwn () const [inline]
Definition at line 270 of file accessor-assembler.h.
                                {
      return IsDefineNamedOwn() || IsDefineKeyedOwn();
    }
Referenced by v8::internal::AccessorAssembler::HandleStoreICHandlerCase().
IsDefineKeyedOwn()
bool v8::internal::AccessorAssembler::StoreICParameters::IsDefineKeyedOwn () const [inline]
Definition at line 267 of file accessor-assembler.h.
                                  {
      return mode_ == StoreICMode::kDefineKeyedOwn;
    }
Referenced by v8::internal::AccessorAssembler::HandleStoreICHandlerCase(), and v8::internal::AccessorAssembler::HandleStoreICProtoHandler().
IsDefineNamedOwn()
bool v8::internal::AccessorAssembler::StoreICParameters::IsDefineNamedOwn () const [inline]
Definition at line 264 of file accessor-assembler.h.
                                  {
      return mode_ == StoreICMode::kDefineNamedOwn;
    }
Referenced by v8::internal::AccessorAssembler::HandleStoreICHandlerCase(), and v8::internal::AccessorAssembler::StoreIC().
lookup_start_object()
TNode<Object> v8::internal::AccessorAssembler::StoreICParameters::lookup_start_object () const [inline]
Definition at line 259 of file accessor-assembler.h.
{ return receiver(); }
name()
TNode<Object> v8::internal::AccessorAssembler::StoreICParameters::name () const [inline]
Definition at line 253 of file accessor-assembler.h.
{ return name_; }
Referenced by v8::internal::AccessorAssembler::DefineKeyedOwnIC(), v8::internal::KeyedStoreGenericAssembler::EmitGenericPropertyStore(), v8::internal::AccessorAssembler::HandleStoreICHandlerCase(), v8::internal::AccessorAssembler::HandleStoreICNativeDataProperty(), v8::internal::AccessorAssembler::HandleStoreICProtoHandler(), v8::internal::AccessorAssembler::HandleStoreICTransitionMapHandlerCase(), v8::internal::AccessorAssembler::HandleStoreToProxy(), v8::internal::AccessorAssembler::KeyedStoreIC(), v8::internal::AccessorAssembler::StoreGlobalIC(), v8::internal::AccessorAssembler::StoreIC(), and v8::internal::AccessorAssembler::StoreInArrayLiteralIC().
receiver()
TNode<JSAny> v8::internal::AccessorAssembler::StoreICParameters::receiver () const [inline]
Definition at line 252 of file accessor-assembler.h.
{ return receiver_.value(); }
Referenced by v8::internal::AccessorAssembler::DefineKeyedOwnIC(), v8::internal::KeyedStoreGenericAssembler::EmitGenericPropertyStore(), v8::internal::AccessorAssembler::HandleStoreICHandlerCase(), v8::internal::AccessorAssembler::HandleStoreICNativeDataProperty(), v8::internal::AccessorAssembler::HandleStoreICProtoHandler(), v8::internal::AccessorAssembler::HandleStoreICTransitionMapHandlerCase(), v8::internal::AccessorAssembler::HandleStoreToProxy(), v8::internal::AccessorAssembler::KeyedStoreIC(), v8::internal::AccessorAssembler::StoreIC(), and v8::internal::AccessorAssembler::StoreInArrayLiteralIC().
receiver_is_null()
bool v8::internal::AccessorAssembler::StoreICParameters::receiver_is_null () const [inline]
Definition at line 261 of file accessor-assembler.h.
{ return !receiver_.has_value(); }
Referenced by v8::internal::AccessorAssembler::StoreGlobalIC().
slot()
TNode<TaggedIndex> v8::internal::AccessorAssembler::StoreICParameters::slot () const [inline]
Definition at line 256 of file accessor-assembler.h.
{ return slot_; }
Referenced by v8::internal::AccessorAssembler::DefineKeyedOwnIC(), v8::internal::KeyedStoreGenericAssembler::EmitGenericPropertyStore(), v8::internal::AccessorAssembler::HandleStoreICHandlerCase(), v8::internal::AccessorAssembler::HandleStoreICProtoHandler(), v8::internal::AccessorAssembler::KeyedStoreIC(), v8::internal::AccessorAssembler::StoreGlobalIC(), v8::internal::AccessorAssembler::StoreIC(), and v8::internal::AccessorAssembler::StoreInArrayLiteralIC().
stub_cache()
StubCache* v8::internal::AccessorAssembler::StoreICParameters::stub_cache (Isolate * isolate) const [inline]
Definition at line 274 of file accessor-assembler.h.
                                                  {
      return IsAnyDefineOwn() ? isolate->define_own_stub_cache()
                              : isolate->store_stub_cache();
    }
References v8::internal::Isolate::define_own_stub_cache(), and v8::internal::Isolate::store_stub_cache().
Referenced by v8::internal::KeyedStoreGenericAssembler::EmitGenericPropertyStore(), and v8::internal::AccessorAssembler::StoreIC().
value()
TNode<Object> v8::internal::AccessorAssembler::StoreICParameters::value () const [inline]
Definition at line 254 of file accessor-assembler.h.
{ return value_; }
Referenced by v8::internal::AccessorAssembler::DefineKeyedOwnIC(), v8::internal::KeyedStoreGenericAssembler::EmitGenericPropertyStore(), v8::internal::AccessorAssembler::GenerateStoreIC_Megamorphic(), v8::internal::AccessorAssembler::HandleStoreICHandlerCase(), v8::internal::AccessorAssembler::HandleStoreICNativeDataProperty(), v8::internal::AccessorAssembler::HandleStoreICProtoHandler(), v8::internal::AccessorAssembler::HandleStoreICTransitionMapHandlerCase(), v8::internal::AccessorAssembler::HandleStoreToProxy(), v8::internal::AccessorAssembler::KeyedStoreIC(), v8::internal::AccessorAssembler::StoreGlobalIC(), v8::internal::AccessorAssembler::StoreIC(), and v8::internal::AccessorAssembler::StoreInArrayLiteralIC().
vector()
TNode<HeapObject> v8::internal::AccessorAssembler::StoreICParameters::vector () const [inline]
Definition at line 257 of file accessor-assembler.h.
{ return vector_; }
Referenced by v8::internal::AccessorAssembler::DefineKeyedOwnIC(), v8::internal::KeyedStoreGenericAssembler::EmitGenericPropertyStore(), v8::internal::AccessorAssembler::HandleStoreICHandlerCase(), v8::internal::AccessorAssembler::HandleStoreICProtoHandler(), v8::internal::AccessorAssembler::KeyedStoreIC(), v8::internal::AccessorAssembler::StoreGlobalIC(), v8::internal::AccessorAssembler::StoreIC(), and v8::internal::AccessorAssembler::StoreInArrayLiteralIC().
Member Data Documentation
context_
TNode<Context> v8::internal::AccessorAssembler::StoreICParameters::context_ [private]
Definition at line 280 of file accessor-assembler.h.
flags_
std::optional<TNode<Smi> > v8::internal::AccessorAssembler::StoreICParameters::flags_ [private]
Definition at line 284 of file accessor-assembler.h.
mode_
StoreICMode v8::internal::AccessorAssembler::StoreICParameters::mode_ [private]
Definition at line 287 of file accessor-assembler.h.
name_
TNode<Object> v8::internal::AccessorAssembler::StoreICParameters::name_ [private]
Definition at line 282 of file accessor-assembler.h.
receiver_
std::optional<TNode<JSAny> > v8::internal::AccessorAssembler::StoreICParameters::receiver_ [private]
Definition at line 281 of file accessor-assembler.h.
slot_
TNode<TaggedIndex> v8::internal::AccessorAssembler::StoreICParameters::slot_ [private]
Definition at line 285 of file accessor-assembler.h.
value_
TNode<Object> v8::internal::AccessorAssembler::StoreICParameters::value_ [private]
Definition at line 283 of file accessor-assembler.h.
vector_
TNode<HeapObject> v8::internal::AccessorAssembler::StoreICParameters::vector_ [private]
Definition at line 286 of file accessor-assembler.h.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/ic/accessor-assembler.h