v8::internal::anonymous_namespace{debug-wasm-objects.cc}::NamedDebugProxy< T, id, Provider > Struct Template Reference
Static Public Member Functions
static v8::Local< v8::FunctionTemplate > CreateTemplate (v8::Isolate *isolate)
static void IndexedEnumerator (const PropertyCallbackInfo< v8::Array > &info)
static DirectHandle< NameDictionary > GetNameTable (DirectHandle< JSObject > holder, Isolate *isolate)
template<typename V >
static std::optional< uint32_t > FindName (Local< v8::Name > name, const PropertyCallbackInfo< V > &info)
static v8::Intercepted NamedGetter (Local< v8::Name > name, const PropertyCallbackInfo< v8::Value > &info)
static v8::Intercepted NamedQuery (Local< v8::Name > name, const PropertyCallbackInfo< v8::Integer > &info)
static v8::Intercepted NamedDescriptor (Local< v8::Name > name, const PropertyCallbackInfo< v8::Value > &info)
static void NamedEnumerator (const PropertyCallbackInfo< v8::Array > &info)
Additional Inherited Members
Detailed Description
template<typename T, DebugProxyId id, typename Provider = WasmInstanceObject>
struct v8::internal::anonymous_namespace{debug-wasm-objects.cc}::NamedDebugProxy< T, id, Provider >
Definition at line 209 of file debug-wasm-objects.cc.
Member Function Documentation
CreateTemplate()
template<typename T , DebugProxyId id, typename Provider = WasmInstanceObject>
static v8::Local<v8::FunctionTemplate> v8::internal::anonymous_namespace{debug-wasm-objects.cc}::NamedDebugProxy< T, id, Provider >::CreateTemplate (v8::Isolate * isolate) [inline], [static]
Definition at line 210 of file debug-wasm-objects.cc.
                                                                        {
    auto templ = IndexedDebugProxy<T, id, Provider>::CreateTemplate(isolate);
    templ->InstanceTemplate()->SetHandler(v8::NamedPropertyHandlerConfiguration(
        &T::NamedGetter, {}, &T::NamedQuery, {}, &T::NamedEnumerator, {},
        &T::NamedDescriptor, {}, v8::PropertyHandlerFlags::kHasNoSideEffect));
    return templ;
  }
References v8::kHasNoSideEffect.
FindName()
template<typename T , DebugProxyId id, typename Provider = WasmInstanceObject>
template<typename V >
static std::optional<uint32_t> v8::internal::anonymous_namespace{debug-wasm-objects.cc}::NamedDebugProxy< T, id, Provider >::FindName (Local< v8::Name > name, const PropertyCallbackInfo< V > & info) [inline], [static]
Definition at line 247 of file debug-wasm-objects.cc.
                                                                               {
    if (!name->IsString()) return {};
    auto name_str = Utils::OpenHandle(*name.As<v8::String>());
    if (name_str->length() == 0 || name_str->Get(0) != '$') return {};
    auto isolate = T::GetIsolate(info);
    auto table = GetNameTable(T::GetHolder(info), isolate);
    auto entry = table->FindEntry(isolate, name_str);
    if (entry.is_found()) return Smi::ToInt(table->ValueAt(entry));
    return {};
  }
References v8::internal::name, v8::Utils::OpenHandle(), and v8::internal::Smi::ToInt().
GetNameTable()
template<typename T , DebugProxyId id, typename Provider = WasmInstanceObject>
static DirectHandle<NameDictionary> v8::internal::anonymous_namespace{debug-wasm-objects.cc}::NamedDebugProxy< T, id, Provider >::GetNameTable (DirectHandle< JSObject > holder, Isolate * isolate) [inline], [static]
Definition at line 222 of file debug-wasm-objects.cc.
                                                       {
    DirectHandle<Symbol> symbol =
        isolate->factory()->wasm_debug_proxy_names_symbol();
    DirectHandle<Object> table_or_undefined =
        JSObject::GetProperty(isolate, holder, symbol).ToHandleChecked();
    if (!IsUndefined(*table_or_undefined, isolate)) {
      return Cast<NameDictionary>(table_or_undefined);
    }
    auto provider = T::GetProvider(holder, isolate);
    auto count = T::Count(isolate, provider);
    auto table = NameDictionary::New(isolate, count);
    for (uint32_t index = 0; index < count; ++index) {
      HandleScope scope(isolate);
      auto key = T::GetName(isolate, provider, index);
      if (table->FindEntry(isolate, key).is_found()) continue;
      DirectHandle<Smi> value(Smi::FromInt(index), isolate);
      table = NameDictionary::Add(isolate, table, key, value,
                                  PropertyDetails::Empty());
    }
    Object::SetProperty(isolate, holder, symbol, table).Check();
    return table;
  }
References v8::bigint::Add(), v8::internal::PropertyDetails::Empty(), v8::internal::Isolate::factory(), v8::internal::Smi::FromInt(), v8::internal::index, v8::internal::key, v8::internal::NameDictionary::New(), v8::internal::Object::SetProperty(), and v8::internal::value.
IndexedEnumerator()
template<typename T , DebugProxyId id, typename Provider = WasmInstanceObject>
static void v8::internal::anonymous_namespace{debug-wasm-objects.cc}::NamedDebugProxy< T, id, Provider >::IndexedEnumerator (const PropertyCallbackInfo< v8::Array > & info) [inline], [static]
Definition at line 218 of file debug-wasm-objects.cc.
                                                                           {
    info.GetReturnValue().Set(v8::Array::New(info.GetIsolate()));
  }
References v8::PropertyCallbackInfo< T >::GetIsolate(), v8::PropertyCallbackInfo< T >::GetReturnValue(), and v8::Array::New().
NamedDescriptor()
template<typename T , DebugProxyId id, typename Provider = WasmInstanceObject>
static v8::Intercepted v8::internal::anonymous_namespace{debug-wasm-objects.cc}::NamedDebugProxy< T, id, Provider >::NamedDescriptor (Local< v8::Name > name, const PropertyCallbackInfo< v8::Value > & info) [inline], [static]
Definition at line 275 of file debug-wasm-objects.cc.
                                                                     {
    if (auto index = FindName(name, info)) {
      return T::IndexedDescriptor(*index, info);
    }
    return v8::Intercepted::kNo;
  }
References v8::internal::index, v8::kNo, and v8::internal::name.
NamedEnumerator()
template<typename T , DebugProxyId id, typename Provider = WasmInstanceObject>
static void v8::internal::anonymous_namespace{debug-wasm-objects.cc}::NamedDebugProxy< T, id, Provider >::NamedEnumerator (const PropertyCallbackInfo< v8::Array > & info) [inline], [static]
Definition at line 283 of file debug-wasm-objects.cc.
                                                                         {
    auto isolate = T::GetIsolate(info);
    auto table = GetNameTable(T::GetHolder(info), isolate);
    auto names = NameDictionary::IterationIndices(isolate, table);
    for (int i = 0; i < names->length(); ++i) {
      InternalIndex entry(Smi::ToInt(names->get(i)));
      names->set(i, table->NameAt(entry));
    }
    info.GetReturnValue().Set(Utils::ToLocal(
        isolate->factory()->NewJSArrayWithElements(names, PACKED_ELEMENTS)));
  }
References v8::internal::Isolate::factory(), v8::PropertyCallbackInfo< T >::GetReturnValue(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::Factory::NewJSArrayWithElements(), v8::internal::PACKED_ELEMENTS, and v8::internal::Smi::ToInt().
NamedGetter()
template<typename T , DebugProxyId id, typename Provider = WasmInstanceObject>
static v8::Intercepted v8::internal::anonymous_namespace{debug-wasm-objects.cc}::NamedDebugProxy< T, id, Provider >::NamedGetter (Local< v8::Name > name, const PropertyCallbackInfo< v8::Value > & info) [inline], [static]
Definition at line 259 of file debug-wasm-objects.cc.
                                                                     {
    if (auto index = FindName(name, info)) {
      return T::IndexedGetter(*index, info);
    }
    return v8::Intercepted::kNo;
  }
References v8::internal::index, v8::kNo, and v8::internal::name.
NamedQuery()
template<typename T , DebugProxyId id, typename Provider = WasmInstanceObject>
static v8::Intercepted v8::internal::anonymous_namespace{debug-wasm-objects.cc}::NamedDebugProxy< T, id, Provider >::NamedQuery (Local< v8::Name > name, const PropertyCallbackInfo< v8::Integer > & info) [inline], [static]
Definition at line 267 of file debug-wasm-objects.cc.
                                                                       {
    if (auto index = FindName(name, info)) {
      return T::IndexedQuery(*index, info);
    }
    return v8::Intercepted::kNo;
  }
References v8::internal::index, v8::kNo, and v8::internal::name.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/debug/debug-wasm-objects.cc