v8::internal::compiler::turboshaft::LoadOp::Kind Struct Reference
#include <operations.h>
Public Member Functions
constexpr Kind NotLoadEliminable ()
constexpr Kind Immutable () const
constexpr Kind Atomic () const
bool operator== (const Kind &other) const
Static Public Member Functions
static constexpr Kind Aligned (BaseTaggedness base_is_tagged)
static constexpr Kind TaggedBase ()
static constexpr Kind RawAligned ()
static constexpr Kind RawUnaligned ()
static constexpr Kind Protected ()
static constexpr Kind TrapOnNull ()
static constexpr Kind MaybeUnaligned (MemoryRepresentation rep)
Public Attributes
bool tagged_base: 1
bool maybe_unaligned: 1
bool with_trap_handler: 1
bool trap_on_null: 1
bool load_eliminable: 1
bool is_immutable: 1
bool is_atomic: 1
Detailed Description
Definition at line 2853 of file operations.h.
Member Function Documentation
Aligned()
static constexpr Kind v8::internal::compiler::turboshaft::LoadOp::Kind::Aligned (BaseTaggedness base_is_tagged) [inline], [static], [constexpr]
Definition at line 2899 of file operations.h.
                                                                 {
      switch (base_is_tagged) {
        case BaseTaggedness::kTaggedBase:
          return TaggedBase();
        case BaseTaggedness::kUntaggedBase:
          return RawAligned();
      }
    }
References v8::internal::compiler::kTaggedBase, and v8::internal::compiler::kUntaggedBase.
Referenced by v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::LoadFieldByIndex(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), and v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::StringAt().
Atomic()
constexpr Kind v8::internal::compiler::turboshaft::LoadOp::Kind::Atomic () const [inline], [constexpr]
Definition at line 2972 of file operations.h.
                                  {
      Kind new_kind(*this);
      new_kind.is_atomic = true;
      return new_kind;
    }
Referenced by v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ArrayGet(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ArraySet(), v8::internal::wasm::TurboshaftGraphBuildingInterface::AtomicOp(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::StructGet(), and v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::StructSet().
Immutable()
constexpr Kind v8::internal::compiler::turboshaft::LoadOp::Kind::Immutable () const [inline], [constexpr]
Definition at line 2966 of file operations.h.
                                     {
      Kind new_kind(*this);
      new_kind.is_immutable = true;
      return new_kind;
    }
Referenced by v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ArrayGet(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ArrayLength(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildFunctionReferenceTargetAndImplicitArg(), v8::internal::wasm::TurboshaftGraphBuildingInterface::GetRttFromDescriptor(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InstanceCache::LoadMemSize(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InstanceCache::LoadMemStart(), v8::internal::compiler::turboshaft::LoadRootHelper(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::LowerGlobalSetOrGet(), and v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::StructGet().
MaybeUnaligned()
static constexpr Kind v8::internal::compiler::turboshaft::LoadOp::Kind::MaybeUnaligned (MemoryRepresentation rep) [inline], [static], [constexpr]
Definition at line 2952 of file operations.h.
                                                                   {
      return rep == MemoryRepresentation::Int8() ||
                     rep == MemoryRepresentation::Uint8() ||
                     SupportedOperations::IsUnalignedLoadSupported(rep)
                 ? LoadOp::Kind::RawAligned()
                 : LoadOp::Kind::RawUnaligned();
    }
References v8::internal::compiler::turboshaft::MemoryRepresentation::Int8(), v8::internal::compiler::turboshaft::SupportedOperations::IsUnalignedLoadSupported(), and v8::internal::compiler::turboshaft::MemoryRepresentation::Uint8().
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::CallCStackSlotToInt32(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallCStackSlotToStackSlot(), v8::internal::compiler::turboshaft::DataViewLoweringReducer< Next >::LoadDataViewElement(), and v8::internal::compiler::turboshaft::DataViewLoweringReducer< Next >::StoreDataViewElement().
NotLoadEliminable()
constexpr Kind v8::internal::compiler::turboshaft::LoadOp::Kind::NotLoadEliminable () [inline], [constexpr]
Definition at line 2960 of file operations.h.
                                       {
      Kind new_kind = *this;
      new_kind.load_eliminable = false;
      return new_kind;
    }
References load_eliminable.
Referenced by v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadElement(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InstanceCache::LoadMemSize(), and v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StoreElement().
operator==()
bool v8::internal::compiler::turboshaft::LoadOp::Kind::operator== (const Kind & other) const [inline]
Definition at line 2978 of file operations.h.
                                             {
      return tagged_base == other.tagged_base &&
             maybe_unaligned == other.maybe_unaligned &&
             with_trap_handler == other.with_trap_handler &&
             load_eliminable == other.load_eliminable &&
             is_immutable == other.is_immutable &&
             is_atomic == other.is_atomic && trap_on_null == other.trap_on_null;
    }
Protected()
static constexpr Kind v8::internal::compiler::turboshaft::LoadOp::Kind::Protected () [inline], [static], [constexpr]
Definition at line 2934 of file operations.h.
                                      {
      return {.tagged_base = false,
              .maybe_unaligned = false,
              .with_trap_handler = true,
              .trap_on_null = false,
              .load_eliminable = true,
              .is_immutable = false,
              .is_atomic = false};
    }
References tagged_base.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::AtomicOp(), v8::internal::wasm::TurboshaftGraphBuildingInterface::GetMemoryAccessKind(), and v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
RawAligned()
static constexpr Kind v8::internal::compiler::turboshaft::LoadOp::Kind::RawAligned () [inline], [static], [constexpr]
Definition at line 2916 of file operations.h.
                                       {
      return {.tagged_base = false,
              .maybe_unaligned = false,
              .with_trap_handler = false,
              .trap_on_null = false,
              .load_eliminable = true,
              .is_immutable = false,
              .is_atomic = false};
    }
References tagged_base.
Referenced by v8::internal::StringBuiltinsReducer< Next >::AllocateSeqOneByteString(), v8::internal::StringBuiltinsReducer< Next >::AllocateSeqTwoByteString(), v8::internal::wasm::TurboshaftGraphBuildingInterface::AsmjsLoadMem(), v8::internal::wasm::TurboshaftGraphBuildingInterface::AsmjsStoreMem(), v8::internal::wasm::TurboshaftGraphBuildingInterface::AtomicOp(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCapiCallWrapper(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildCcallConvertFloat(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildCcallConvertFloatSat(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildCCallForFloatConversion(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildDiv64Call(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildIntToFloatConversionInstruction(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildLoadCallTargetFromExportedFunctionData(), v8::internal::wasm::WasmGraphBuilderBase::BuildModifyThreadInWasmFlag(), v8::internal::wasm::WasmGraphBuilderBase::BuildModifyThreadInWasmFlagHelper(), v8::internal::wasm::WasmGraphBuilderBase::BuildSetNewStackLimit(), v8::internal::wasm::WasmGraphBuilderBase::BuildSwitchBackFromCentralStack(), v8::internal::wasm::WasmGraphBuilderBase::BuildSwitchToTheCentralStack(), v8::internal::wasm::WasmGraphBuilderBase::BuildSwitchToTheCentralStackIfNeeded(), v8::internal::compiler::turboshaft::WasmInJSInliningReducer< Next >::Call(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallCStackSlotToInt32(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallCStackSlotToStackSlot(), v8::internal::wasm::WasmGraphBuilderBase::CallRuntime(), v8::internal::StringBuiltinsReducer< Next >::CopyStringCharacters(), v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::DecodeExternalPointer(), v8::internal::compiler::turboshaft::StringView::Dereference(), v8::internal::wasm::TurboshaftGraphBuildingInterface::DoReturn(), v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::FastApiCall(), v8::internal::wasm::TurboshaftGraphBuildingInterface::GetCodeUnitImpl(), v8::internal::wasm::TurboshaftGraphBuildingInterface::GetMemoryAccessKind(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineMemCopy(), v8::internal::compiler::turboshaft::StackCheckLoweringReducer< Next >::JSStackCheck(), v8::internal::compiler::turboshaft::LoadRootHelper(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::LoadStackArgument(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::LowerGlobalSetOrGet(), v8::internal::wasm::WasmWrapperTSGraphBuilder::ModifyThreadInWasmFlagScope::ModifyThreadInWasmFlagScope(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::turboshaft::GrowableStacksReducer< Next >::Return(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::RootConstant(), v8::internal::wasm::WasmWrapperTSGraphBuilder::SafeLoad(), v8::internal::wasm::WasmWrapperTSGraphBuilder::SafeStore(), v8::internal::wasm::TurboshaftGraphBuildingInterface::SetDataViewOpForErrorMessage(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StoreInStackSlot(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StringCodePointAt(), v8::internal::wasm::TurboshaftGraphBuildingInterface::TraceMemoryOperation(), v8::internal::compiler::turboshaft::GrowableStacksReducer< Next >::WasmStackCheck(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::WellKnown_FastApi().
RawUnaligned()
static constexpr Kind v8::internal::compiler::turboshaft::LoadOp::Kind::RawUnaligned () [inline], [static], [constexpr]
Definition at line 2925 of file operations.h.
                                         {
      return {.tagged_base = false,
              .maybe_unaligned = true,
              .with_trap_handler = false,
              .trap_on_null = false,
              .load_eliminable = true,
              .is_immutable = false,
              .is_atomic = false};
    }
References tagged_base.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::GetMemoryAccessKind(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::wasm::WasmWrapperTSGraphBuilder::SafeLoad(), and v8::internal::wasm::WasmWrapperTSGraphBuilder::SafeStore().
TaggedBase()
static constexpr Kind v8::internal::compiler::turboshaft::LoadOp::Kind::TaggedBase () [inline], [static], [constexpr]
Definition at line 2907 of file operations.h.
                                       {
      return {.tagged_base = true,
              .maybe_unaligned = false,
              .with_trap_handler = false,
              .trap_on_null = false,
              .load_eliminable = true,
              .is_immutable = false,
              .is_atomic = false};
    }
References tagged_base.
Referenced by v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::Allocate(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ArrayGet(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ArrayLength(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ArraySet(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCallAndReturn(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCapiCallWrapper(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildFunctionReferenceTargetAndImplicitArg(), v8::internal::wasm::WasmGraphBuilderBase::BuildFunctionTargetAndImplicitArg(), v8::internal::wasm::WasmGraphBuilderBase::BuildImportedFunctionTargetAndImplicitArg(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildIndirectCallTargetAndImplicitArg(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildJSToWasmWrapper(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildLoadCallTargetFromExportedFunctionData(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildReceiverNode(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildSuspend(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildWasmToJSWrapper(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CatchCase(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CatchException(), v8::internal::wasm::TurboshaftGraphBuildingInterface::DataDrop(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::FindOrderedHashEntry(), v8::internal::compiler::turboshaft::TurbolevEarlyLoweringReducer< Next >::GeneratorStore(), v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::GetLimitAddress(), v8::internal::wasm::TurboshaftGraphBuildingInterface::GetRttFromDescriptor(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InstanceCache::Initialize(), v8::internal::wasm::WasmWrapperTSGraphBuilder::LoadContextFromJSFunction(), v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::LoadCounterValue(), v8::internal::wasm::WasmWrapperTSGraphBuilder::LoadExportedFunctionIndexAsSmi(), v8::internal::FeedbackCollectorReducer< Next >::LoadFeedbackVectorSlot(), v8::internal::wasm::WasmWrapperTSGraphBuilder::LoadInstanceType(), v8::internal::wasm::WasmWrapperTSGraphBuilder::LoadMap(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InstanceCache::LoadMemSize(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InstanceCache::LoadMemStart(), v8::internal::wasm::WasmWrapperTSGraphBuilder::LoadSharedFunctionInfo(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::LoadWasmTypeInfo(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::LowerGlobalSetOrGet(), v8::internal::wasm::TurboshaftGraphBuildingInterface::MemSize(), v8::internal::wasm::TurboshaftGraphBuildingInterface::MemStart(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::turboshaft::RedundantStoreAnalysis::ProcessBlock(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ReduceWasmTypeCastRtt(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ReduceWasmTypeCheckRtt(), v8::internal::wasm::TurboshaftGraphBuildingInterface::RefGetDesc(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::RttCanon(), v8::internal::compiler::turboshaft::StoreStoreEliminationReducer< Next >::Store(), v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::StoreCounterValue(), v8::internal::FeedbackCollectorReducer< Next >::StoreFeedbackVectorSlot(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::StructGet(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::StructSet(), v8::internal::wasm::TurboshaftGraphBuildingInterface::TableGet(), v8::internal::wasm::TurboshaftGraphBuildingInterface::TableSize(), v8::internal::wasm::WasmWrapperTSGraphBuilder::ToJS(), v8::internal::compiler::turboshaft::TurbolevEarlyLoweringReducer< Next >::UpdateJSArrayLength(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::WellKnown_FastApi().
TrapOnNull()
static constexpr Kind v8::internal::compiler::turboshaft::LoadOp::Kind::TrapOnNull () [inline], [static], [constexpr]
Definition at line 2943 of file operations.h.
                                       {
      return {.tagged_base = true,
              .maybe_unaligned = false,
              .with_trap_handler = true,
              .trap_on_null = true,
              .load_eliminable = true,
              .is_immutable = false,
              .is_atomic = false};
    }
References tagged_base.
Referenced by v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ArrayLength(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::AssertNotNull(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildFunctionReferenceTargetAndImplicitArg(), v8::internal::wasm::TurboshaftGraphBuildingInterface::GetRttFromDescriptor(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::StructGet(), and v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::StructSet().
Member Data Documentation
is_atomic
bool v8::internal::compiler::turboshaft::LoadOp::Kind::is_atomic
Definition at line 2897 of file operations.h.
Referenced by v8::internal::compiler::turboshaft::hash_value(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessLoad(), v8::internal::compiler::turboshaft::LoadStoreSimplificationReducer< Next >::SimplifyLoadStore(), and v8::internal::compiler::InstructionSelector::VisitNode().
is_immutable
bool v8::internal::compiler::turboshaft::LoadOp::Kind::is_immutable
Definition at line 2895 of file operations.h.
Referenced by v8::internal::compiler::turboshaft::hash_value(), and v8::internal::compiler::turboshaft::MemoryContentTable::Insert().
load_eliminable
bool v8::internal::compiler::turboshaft::LoadOp::Kind::load_eliminable
Definition at line 2893 of file operations.h.
Referenced by v8::internal::compiler::turboshaft::hash_value(), NotLoadEliminable(), and v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessLoad().
maybe_unaligned
bool v8::internal::compiler::turboshaft::LoadOp::Kind::maybe_unaligned
Definition at line 2859 of file operations.h.
Referenced by v8::internal::compiler::turboshaft::hash_value(), v8::internal::compiler::turboshaft::LoadOp::PrintOptions(), v8::internal::compiler::turboshaft::StoreOp::PrintOptions(), and v8::internal::compiler::InstructionSelector::VisitNode().
tagged_base
bool v8::internal::compiler::turboshaft::LoadOp::Kind::tagged_base
Definition at line 2855 of file operations.h.
Referenced by v8::internal::compiler::turboshaft::hash_value(), v8::internal::compiler::turboshaft::LoadOp::PrintOptions(), v8::internal::compiler::turboshaft::StoreOp::PrintOptions(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::turboshaft::RedundantStoreAnalysis::ProcessBlock(), Protected(), RawAligned(), RawUnaligned(), v8::internal::compiler::turboshaft::LoadStoreSimplificationReducer< Next >::SimplifyLoadStore(), TaggedBase(), and TrapOnNull().
trap_on_null
bool v8::internal::compiler::turboshaft::LoadOp::Kind::trap_on_null
Definition at line 2864 of file operations.h.
with_trap_handler
bool v8::internal::compiler::turboshaft::LoadOp::Kind::with_trap_handler
Definition at line 2861 of file operations.h.
Referenced by v8::internal::compiler::turboshaft::hash_value(), v8::internal::compiler::turboshaft::LoadOp::PrintOptions(), v8::internal::compiler::turboshaft::StoreOp::PrintOptions(), and v8::internal::compiler::InstructionSelector::VisitNode().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h