v8::internal::AccessorAssembler::LazyLoadICParameters Struct Reference
#include <accessor-assembler.h>
Public Member Functions
LazyLoadICParameters (LazyNode< Context > context, TNode< JSAny > receiver, LazyNode< Object > name, LazyNode< TaggedIndex > slot, TNode< HeapObject > vector, std::optional< TNode< JSAny >> lookup_start_object=std::nullopt)
LazyLoadICParameters (const LoadICParameters *p)
TNode< Context > context () const
TNode< JSAny > receiver () const
TNode< Object > name () const
TNode< TaggedIndex > slot () const
TNode< HeapObject > vector () const
TNode< JSAny > lookup_start_object () const
TNode< JSAny > receiver_and_lookup_start_object () const
Private Attributes
LazyNode< Context > context_
TNode< JSAny > receiver_
LazyNode< Object > name_
LazyNode< TaggedIndex > slot_
TNode< HeapObject > vector_
TNode< JSAny > lookup_start_object_
Detailed Description
Definition at line 168 of file accessor-assembler.h.
Constructor & Destructor Documentation
LazyLoadICParameters() [1/2]
v8::internal::AccessorAssembler::LazyLoadICParameters::LazyLoadICParameters (LazyNode< Context > context, TNode< JSAny > receiver, LazyNode< Object > name, LazyNode< TaggedIndex > slot, TNode< HeapObject > vector, std::optional< TNode< JSAny >> lookup_start_object = std::nullopt) [inline]
Definition at line 169 of file accessor-assembler.h.
        : context_(context),
          receiver_(receiver),
          name_(name),
          slot_(slot),
          vector_(vector),
          lookup_start_object_(lookup_start_object ? lookup_start_object.value()
                                                   : receiver) {}
LazyLoadICParameters() [2/2]
v8::internal::AccessorAssembler::LazyLoadICParameters::LazyLoadICParameters (const LoadICParameters * p) [inline], [explicit]
Definition at line 181 of file accessor-assembler.h.
        : receiver_(p->receiver()),
          vector_(p->vector()),
          lookup_start_object_(p->lookup_start_object()) {
      slot_ = [=] { return p->slot(); };
      context_ = [=] { return p->context(); };
      name_ = [=] { return p->name(); };
    }
References v8::internal::AccessorAssembler::LoadICParameters::context(), v8::internal::AccessorAssembler::LoadICParameters::name(), and v8::internal::AccessorAssembler::LoadICParameters::slot().
Member Function Documentation
context()
TNode<Context> v8::internal::AccessorAssembler::LazyLoadICParameters::context () const [inline]
Definition at line 190 of file accessor-assembler.h.
{ return context_(); }
Referenced by v8::internal::AccessorAssembler::HandleLoadAccessor(), v8::internal::AccessorAssembler::HandleLoadCallbackProperty(), v8::internal::AccessorAssembler::HandleLoadICHandlerCase(), v8::internal::AccessorAssembler::HandleLoadICProtoHandler(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerCase(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerHasNamedCase(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerLoadNamedCase(), and v8::internal::AccessorAssembler::LoadIC_BytecodeHandler().
lookup_start_object()
TNode<JSAny> v8::internal::AccessorAssembler::LazyLoadICParameters::lookup_start_object () const [inline]
Definition at line 195 of file accessor-assembler.h.
{ return lookup_start_object_; }
Referenced by v8::internal::AccessorAssembler::HandleLoadICHandlerCase(), and v8::internal::AccessorAssembler::HandleLoadICSmiHandlerLoadNamedCase().
name()
TNode<Object> v8::internal::AccessorAssembler::LazyLoadICParameters::name () const [inline]
Definition at line 192 of file accessor-assembler.h.
{ return name_(); }
Referenced by v8::internal::AccessorAssembler::HandleLoadICHandlerCase(), v8::internal::AccessorAssembler::HandleLoadICProtoHandler(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerCase(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerHasNamedCase(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerLoadNamedCase(), and v8::internal::AccessorAssembler::LoadIC_BytecodeHandler().
receiver()
TNode<JSAny> v8::internal::AccessorAssembler::LazyLoadICParameters::receiver () const [inline]
Definition at line 191 of file accessor-assembler.h.
{ return receiver_; }
Referenced by v8::internal::AccessorAssembler::HandleLoadAccessor(), v8::internal::AccessorAssembler::HandleLoadCallbackProperty(), v8::internal::AccessorAssembler::HandleLoadICHandlerCase(), v8::internal::AccessorAssembler::HandleLoadICProtoHandler(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerCase(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerHasNamedCase(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerLoadNamedCase(), and v8::internal::AccessorAssembler::LoadIC_BytecodeHandler().
receiver_and_lookup_start_object()
TNode<JSAny> v8::internal::AccessorAssembler::LazyLoadICParameters::receiver_and_lookup_start_object () const [inline]
Definition at line 200 of file accessor-assembler.h.
                                                          {
      DCHECK_EQ(receiver_, lookup_start_object_);
      return receiver_;
    }
References DCHECK_EQ.
Referenced by v8::internal::AccessorAssembler::LoadIC_BytecodeHandler().
slot()
TNode<TaggedIndex> v8::internal::AccessorAssembler::LazyLoadICParameters::slot () const [inline]
Definition at line 193 of file accessor-assembler.h.
{ return slot_(); }
Referenced by v8::internal::AccessorAssembler::HandleLoadICHandlerCase(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerHasNamedCase(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerLoadNamedCase(), and v8::internal::AccessorAssembler::LoadIC_BytecodeHandler().
vector()
TNode<HeapObject> v8::internal::AccessorAssembler::LazyLoadICParameters::vector () const [inline]
Definition at line 194 of file accessor-assembler.h.
{ return vector_; }
Referenced by v8::internal::AccessorAssembler::HandleLoadICHandlerCase(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerHasNamedCase(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerLoadNamedCase(), and v8::internal::AccessorAssembler::LoadIC_BytecodeHandler().
Member Data Documentation
context_
LazyNode<Context> v8::internal::AccessorAssembler::LazyLoadICParameters::context_ [private]
Definition at line 206 of file accessor-assembler.h.
lookup_start_object_
TNode<JSAny> v8::internal::AccessorAssembler::LazyLoadICParameters::lookup_start_object_ [private]
Definition at line 211 of file accessor-assembler.h.
name_
LazyNode<Object> v8::internal::AccessorAssembler::LazyLoadICParameters::name_ [private]
Definition at line 208 of file accessor-assembler.h.
receiver_
TNode<JSAny> v8::internal::AccessorAssembler::LazyLoadICParameters::receiver_ [private]
Definition at line 207 of file accessor-assembler.h.
slot_
LazyNode<TaggedIndex> v8::internal::AccessorAssembler::LazyLoadICParameters::slot_ [private]
Definition at line 209 of file accessor-assembler.h.
vector_
TNode<HeapObject> v8::internal::AccessorAssembler::LazyLoadICParameters::vector_ [private]
Definition at line 210 of file accessor-assembler.h.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/ic/accessor-assembler.h