v8::internal::compiler::turboshaft::PendingLoopPhiOp Struct Reference
#include <operations.h>
Public Member Functions
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
OpIndex first () const
PendingLoopPhiOp (OpIndex first, RegisterRepresentation rep)
auto options () const
Public Attributes
RegisterRepresentation rep
Static Public Attributes
static constexpr OpEffects effects = OpEffects()
Additional Inherited Members
Detailed Description
Definition at line 2577 of file operations.h.
Constructor & Destructor Documentation
PendingLoopPhiOp()
v8::internal::compiler::turboshaft::PendingLoopPhiOp::PendingLoopPhiOp (OpIndex first, RegisterRepresentation rep) [inline]
Definition at line 2591 of file operations.h.
      : Base(first), rep(rep) {}
Member Function Documentation
first()
OpIndex v8::internal::compiler::turboshaft::PendingLoopPhiOp::first () const [inline]
Definition at line 2590 of file operations.h.
{ return input(0); }
Referenced by v8::internal::compiler::turboshaft::LoopLabel< Ts >::FixLoopPhi(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::FixLoopPhi(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::FixLoopPhis(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::Goto(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::PopControl().
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::PendingLoopPhiOp::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 2585 of file operations.h.
                                                              {
    return InputsRepFactory::SingleRep(rep);
  }
References v8::internal::compiler::turboshaft::InputsRepFactory::SingleRep().
options()
auto v8::internal::compiler::turboshaft::PendingLoopPhiOp::options () const [inline]
Definition at line 2594 of file operations.h.
{ return std::tuple{rep}; }
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::PendingLoopPhiOp::outputs_rep () const [inline]
Definition at line 2581 of file operations.h.
                                                               {
    return base::VectorOf(&rep, 1);
  }
References v8::base::VectorOf().
Member Data Documentation
effects
constexpr OpEffects v8::internal::compiler::turboshaft::PendingLoopPhiOp::effects = OpEffects() [static], [constexpr]
Definition at line 2580 of file operations.h.
rep
RegisterRepresentation v8::internal::compiler::turboshaft::PendingLoopPhiOp::rep
Definition at line 2578 of file operations.h.
Referenced by v8::internal::compiler::turboshaft::LoopLabel< Ts >::FixLoopPhi(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::FixLoopPhi(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::FixLoopPhis(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::Goto(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::PopControl().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h