v8::internal::compiler::turboshaft::WordUnaryOp Struct Reference
#include <operations.h>
Public Types
enum class Kind : uint8_t {
kReverseBytes
, kCountLeadingZeros
, kCountTrailingZeros
, kPopCount
,
kSignExtend8
, kSignExtend16
 }
Public Member Functions
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
V< Word > input () const
WordUnaryOp (V< Word > input, Kind kind, WordRepresentation rep)
auto options () const
Static Public Member Functions
static V8_EXPORT_PRIVATE bool IsSupported (Kind kind, WordRepresentation rep)
Public Attributes
Kind kind
WordRepresentation rep
Static Public Attributes
static constexpr OpEffects effects = OpEffects()
Additional Inherited Members
Detailed Description
Definition at line 1875 of file operations.h.
Member Enumeration Documentation
Kind
enum v8::internal::compiler::turboshaft::WordUnaryOp::Kind : uint8_t [strong]
Enumerator
kReverseBytes
kCountLeadingZeros
kCountTrailingZeros
kPopCount
kSignExtend8
kSignExtend16
Definition at line 1876 of file operations.h.
                  : uint8_t {
    kReverseBytes,
    kCountLeadingZeros,
    kCountTrailingZeros,
    kPopCount,
    kSignExtend8,
    kSignExtend16,
  };
Constructor & Destructor Documentation
WordUnaryOp()
v8::internal::compiler::turboshaft::WordUnaryOp::WordUnaryOp (V< Word > input, Kind kind, WordRepresentation rep) [inline], [explicit]
Definition at line 1900 of file operations.h.
      : Base(input), kind(kind), rep(rep) {}
Member Function Documentation
input()
V<Word> v8::internal::compiler::turboshaft::WordUnaryOp::input () const [inline]
Definition at line 1896 of file operations.h.
{ return Base::input<Word>(0); }
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::WordUnaryOp::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 1891 of file operations.h.
                                                              {
    return InputsRepFactory::SingleRep(rep);
  }
References v8::internal::compiler::turboshaft::InputsRepFactory::SingleRep().
IsSupported()
bool v8::internal::compiler::turboshaft::WordUnaryOp::IsSupported (Kind kind, WordRepresentation rep) [static]
Definition at line 306 of file operations.cc.
                                                               {
  switch (kind) {
    case Kind::kCountLeadingZeros:
    case Kind::kReverseBytes:
    case Kind::kSignExtend8:
    case Kind::kSignExtend16:
      return true;
    case Kind::kCountTrailingZeros:
      return rep == WordRepresentation::Word32()
                 ? SupportedOperations::word32_ctz()
                 : SupportedOperations::word64_ctz();
    case Kind::kPopCount:
      return rep == WordRepresentation::Word32()
                 ? SupportedOperations::word32_popcnt()
                 : SupportedOperations::word64_popcnt();
  }
}
References kCountLeadingZeros, kCountTrailingZeros, kind, kPopCount, kReverseBytes, kSignExtend16, kSignExtend8, rep, and v8::internal::compiler::turboshaft::WordRepresentation::Word32().
options()
auto v8::internal::compiler::turboshaft::WordUnaryOp::options () const [inline]
Definition at line 1903 of file operations.h.
{ return std::tuple{kind, rep}; }
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::WordUnaryOp::outputs_rep () const [inline]
Definition at line 1887 of file operations.h.
                                                               {
    return base::VectorOf(static_cast<const RegisterRepresentation*>(&rep), 1);
  }
References v8::base::VectorOf().
Member Data Documentation
effects
constexpr OpEffects v8::internal::compiler::turboshaft::WordUnaryOp::effects = OpEffects() [static], [constexpr]
Definition at line 1886 of file operations.h.
kind
Kind v8::internal::compiler::turboshaft::WordUnaryOp::kind
Definition at line 1884 of file operations.h.
Referenced by IsSupported(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::ProduceWord32Result(), and v8::internal::compiler::InstructionSelector::VisitNode().
rep
WordRepresentation v8::internal::compiler::turboshaft::WordUnaryOp::rep
Definition at line 1885 of file operations.h.
Referenced by IsSupported(), and v8::internal::compiler::InstructionSelector::VisitNode().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h
/mnt/V8SourceCode/src/compiler/turboshaft/operations.cc