v8::internal::baseline::detail::ArgumentSettingHelper< Descriptor, ArgIndex, true, interpreter::RegisterList > Struct Template Reference
Static Public Member Functions
static void Set (BaselineAssembler *masm, interpreter::RegisterList list)
Detailed Description
template<typename Descriptor, int ArgIndex>
struct v8::internal::baseline::detail::ArgumentSettingHelper< Descriptor, ArgIndex, true, interpreter::RegisterList >
Definition at line 212 of file baseline-compiler.cc.
Member Function Documentation
Set()
template<typename Descriptor , int ArgIndex>
static void v8::internal::baseline::detail::ArgumentSettingHelper< Descriptor, ArgIndex, true, interpreter::RegisterList >::Set (BaselineAssembler * masm, interpreter::RegisterList list) [inline], [static]
Definition at line 214 of file baseline-compiler.cc.
                                                                         {
    static_assert(ArgIndex < Descriptor::GetRegisterParameterCount());
    DCHECK_EQ(ArgIndex + list.register_count(),
              Descriptor::GetRegisterParameterCount());
    for (int i = 0; ArgIndex + i < Descriptor::GetRegisterParameterCount();
         ++i) {
      Register target = Descriptor::GetRegisterParameter(ArgIndex + i);
      masm->Move(target, masm->RegisterFrameOperand(list[i]));
    }
  }
References DCHECK_EQ, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::baseline::BaselineAssembler::Move(), v8::internal::interpreter::RegisterList::register_count(), and v8::internal::baseline::BaselineAssembler::RegisterFrameOperand().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/baseline/baseline-compiler.cc