v8::internal::SerializerDeserializer::BytecodeValueEncoder< kBytecode, kMinValue, kMaxValue, TValue > Struct Template Reference
#include <serializer-deserializer.h>
Static Public Member Functions
static constexpr bool IsEncodable (TValue value)
static constexpr uint8_t Encode (TValue value)
static constexpr TValue Decode (uint8_t bytecode)
Detailed Description
template<Bytecode kBytecode, int kMinValue, int kMaxValue, typename TValue = int>
struct v8::internal::SerializerDeserializer::BytecodeValueEncoder< kBytecode, kMinValue, kMaxValue, TValue >
Definition at line 203 of file serializer-deserializer.h.
Member Function Documentation
Decode()
template<Bytecode kBytecode, int kMinValue, int kMaxValue, typename TValue = int>
static constexpr TValue v8::internal::SerializerDeserializer::BytecodeValueEncoder< kBytecode, kMinValue, kMaxValue, TValue >::Decode (uint8_t bytecode) [inline], [static], [constexpr]
Definition at line 216 of file serializer-deserializer.h.
                                                     {
      DCHECK(base::IsInRange(bytecode, Encode(static_cast<TValue>(kMinValue)),
                             Encode(static_cast<TValue>(kMaxValue))));
      return static_cast<TValue>(bytecode - kBytecode + kMinValue);
    }
References v8::internal::DCHECK(), v8::internal::SerializerDeserializer::BytecodeValueEncoder< kBytecode, kMinValue, kMaxValue, TValue >::Encode(), and v8::internal::kBytecode.
Encode()
template<Bytecode kBytecode, int kMinValue, int kMaxValue, typename TValue = int>
static constexpr uint8_t v8::internal::SerializerDeserializer::BytecodeValueEncoder< kBytecode, kMinValue, kMaxValue, TValue >::Encode (TValue value) [inline], [static], [constexpr]
Definition at line 210 of file serializer-deserializer.h.
                                                  {
      DCHECK(IsEncodable(value));
      return static_cast<uint8_t>(kBytecode + static_cast<int>(value) -
                                  kMinValue);
    }
References v8::internal::DCHECK(), v8::internal::SerializerDeserializer::BytecodeValueEncoder< kBytecode, kMinValue, kMaxValue, TValue >::IsEncodable(), v8::internal::kBytecode, and v8::internal::value.
Referenced by v8::internal::SerializerDeserializer::BytecodeValueEncoder< kBytecode, kMinValue, kMaxValue, TValue >::Decode(), v8::internal::Serializer::ObjectSerializer::OutputExternalReference(), v8::internal::Serializer::ObjectSerializer::OutputRawData(), v8::internal::Serializer::PutRepeatRoot(), v8::internal::Serializer::PutRoot(), v8::internal::Serializer::PutSmiRoot(), v8::internal::Serializer::SerializeHotObject(), v8::internal::Serializer::ObjectSerializer::SerializePrologue(), and v8::internal::Serializer::ObjectSerializer::VisitCppHeapPointer().
IsEncodable()
template<Bytecode kBytecode, int kMinValue, int kMaxValue, typename TValue = int>
static constexpr bool v8::internal::SerializerDeserializer::BytecodeValueEncoder< kBytecode, kMinValue, kMaxValue, TValue >::IsEncodable (TValue value) [inline], [static], [constexpr]
Definition at line 206 of file serializer-deserializer.h.
                                                    {
      return base::IsInRange(static_cast<int>(value), kMinValue, kMaxValue);
    }
References v8::internal::value.
Referenced by v8::internal::SerializerDeserializer::BytecodeValueEncoder< kBytecode, kMinValue, kMaxValue, TValue >::Encode().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/snapshot/serializer-deserializer.h