v8::internal::compiler::turboshaft::SelectOp Struct Reference
#include <operations.h>
Public Types
enum class Implementation : uint8_t { kBranch
, kCMove
 }
Public Member Functions
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
SelectOp (V< Word32 > cond, V< Any > vtrue, V< Any > vfalse, RegisterRepresentation rep, BranchHint hint, Implementation implem)
void Validate (const Graph &graph) const
V< Word32 > cond () const
V< Any > vtrue () const
V< Any > vfalse () const
auto options () const
Public Attributes
RegisterRepresentation rep
BranchHint hint
Implementation implem
Static Public Attributes
static constexpr OpEffects effects = OpEffects()
Additional Inherited Members
Detailed Description
Definition at line 2497 of file operations.h.
Member Enumeration Documentation
Implementation
enum v8::internal::compiler::turboshaft::SelectOp::Implementation : uint8_t [strong]
Enumerator
kBranch
kCMove
Definition at line 2498 of file operations.h.
: uint8_t { kBranch, kCMove };
Constructor & Destructor Documentation
SelectOp()
v8::internal::compiler::turboshaft::SelectOp::SelectOp (V< Word32 > cond, V< Any > vtrue, V< Any > vfalse, RegisterRepresentation rep, BranchHint hint, Implementation implem) [inline]
Definition at line 2514 of file operations.h.
      : Base(cond, vtrue, vfalse), rep(rep), hint(hint), implem(implem) {}
Member Function Documentation
cond()
V<Word32> v8::internal::compiler::turboshaft::SelectOp::cond () const [inline]
Definition at line 2530 of file operations.h.
{ return input<Word32>(0); }
Referenced by v8::internal::compiler::InstructionSelector::VisitSelect().
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::SelectOp::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 2509 of file operations.h.
                                                              {
    return InitVectorOf(storage, {RegisterRepresentation::Word32(), rep, rep});
  }
References v8::internal::compiler::turboshaft::InitVectorOf(), and v8::internal::compiler::turboshaft::RegisterRepresentation::Word32().
options()
auto v8::internal::compiler::turboshaft::SelectOp::options () const [inline]
Definition at line 2534 of file operations.h.
{ return std::tuple{rep, hint, implem}; }
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::SelectOp::outputs_rep () const [inline]
Definition at line 2505 of file operations.h.
                                                               {
    return base::VectorOf(&rep, 1);
  }
References v8::base::VectorOf().
Validate()
void v8::internal::compiler::turboshaft::SelectOp::Validate (const Graph & graph) const [inline]
Definition at line 2518 of file operations.h.
                                          {
    DCHECK_IMPLIES(implem == Implementation::kCMove,
                   (rep == RegisterRepresentation::Word32() &&
                    SupportedOperations::word32_select()) ||
                       (rep == RegisterRepresentation::Word64() &&
                        SupportedOperations::word64_select()) ||
                       (rep == RegisterRepresentation::Float32() &&
                        SupportedOperations::float32_select()) ||
                       (rep == RegisterRepresentation::Float64() &&
                        SupportedOperations::float64_select()));
  }
References DCHECK_IMPLIES, v8::internal::compiler::turboshaft::RegisterRepresentation::Float32(), v8::internal::compiler::turboshaft::RegisterRepresentation::Float64(), v8::internal::compiler::turboshaft::RegisterRepresentation::Word32(), and v8::internal::compiler::turboshaft::RegisterRepresentation::Word64().
vfalse()
V<Any> v8::internal::compiler::turboshaft::SelectOp::vfalse () const [inline]
Definition at line 2532 of file operations.h.
{ return input<Any>(2); }
Referenced by v8::internal::compiler::InstructionSelector::VisitSelect().
vtrue()
V<Any> v8::internal::compiler::turboshaft::SelectOp::vtrue () const [inline]
Definition at line 2531 of file operations.h.
{ return input<Any>(1); }
Referenced by v8::internal::compiler::InstructionSelector::VisitSelect().
Member Data Documentation
effects
constexpr OpEffects v8::internal::compiler::turboshaft::SelectOp::effects = OpEffects() [static], [constexpr]
Definition at line 2504 of file operations.h.
hint
BranchHint v8::internal::compiler::turboshaft::SelectOp::hint
Definition at line 2501 of file operations.h.
implem
Implementation v8::internal::compiler::turboshaft::SelectOp::implem
Definition at line 2502 of file operations.h.
Referenced by v8::internal::compiler::InstructionSelector::VisitNode().
rep
RegisterRepresentation v8::internal::compiler::turboshaft::SelectOp::rep
Definition at line 2500 of file operations.h.
Referenced by v8::internal::compiler::InstructionSelector::VisitNode().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h