v8::internal::wasm::NativeModule::JumpTablesRef Struct Reference
#include <wasm-code-manager.h>
Public Member Functions
bool is_valid () const
Public Attributes
Address jump_table_start = kNullAddress
Address far_jump_table_start = kNullAddress
Detailed Description
Definition at line 667 of file wasm-code-manager.h.
Member Function Documentation
is_valid()
bool v8::internal::wasm::NativeModule::JumpTablesRef::is_valid () const [inline]
Definition at line 671 of file wasm-code-manager.h.
{ return far_jump_table_start != kNullAddress; }
References v8::internal::kNullAddress.
Referenced by v8::internal::wasm::NativeModule::AddCodeSpaceLocked(), v8::internal::wasm::NativeModule::AddCompiledCode(), v8::internal::wasm::NativeModule::GetJumpTableEntryForBuiltin(), v8::internal::wasm::NativeModule::GetNearCallTargetForFunction(), and v8::internal::wasm::NativeModuleDeserializer::ReadCode().
Member Data Documentation
far_jump_table_start
Address v8::internal::wasm::NativeModule::JumpTablesRef::far_jump_table_start = kNullAddress
Definition at line 669 of file wasm-code-manager.h.
Referenced by v8::internal::wasm::NativeModule::GetJumpTableEntryForBuiltin().
jump_table_start
Address v8::internal::wasm::NativeModule::JumpTablesRef::jump_table_start = kNullAddress
Definition at line 668 of file wasm-code-manager.h.
Referenced by v8::internal::wasm::NativeModule::GetNearCallTargetForFunction().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/wasm/wasm-code-manager.h