cppgc::internal::DijkstraWriteBarrierPolicy Struct Reference
#include <pointer-policies.h>
Static Public Member Functions
static void InitializingBarrier (const void *, const void *)
static void InitializingBarrier (const void *, RawPointer storage)
template<WriteBarrierSlotType SlotType>
static void AssigningBarrier (const void *slot, const void *value)
template<WriteBarrierSlotType SlotType>
static void AssigningBarrier (const void *slot, RawPointer storage)
Static Private Member Functions
static void WriteBarrier (WriteBarrier::Type type, const WriteBarrier::Params &params, const void *slot, const void *value)
Detailed Description
Definition at line 30 of file pointer-policies.h.
Member Function Documentation
AssigningBarrier() [1/2]
template<WriteBarrierSlotType SlotType>
static void cppgc::internal::DijkstraWriteBarrierPolicy::AssigningBarrier (const void * slot, const void * value) [inline], [static]
Definition at line 42 of file pointer-policies.h.
                                                              {
#ifdef CPPGC_SLIM_WRITE_BARRIER
    if (V8_UNLIKELY(WriteBarrier::IsEnabled()))
      WriteBarrier::CombinedWriteBarrierSlow<SlotType>(slot);
#else // !CPPGC_SLIM_WRITE_BARRIER
    WriteBarrier::Params params;
    const WriteBarrier::Type type =
        WriteBarrier::GetWriteBarrierType(slot, value, params);
    WriteBarrier(type, params, slot, value);
#endif // !CPPGC_SLIM_WRITE_BARRIER
    }
References cppgc::internal::WriteBarrier::GetWriteBarrierType(), cppgc::internal::WriteBarrier::IsEnabled(), v8::internal::tracing::type, V8_UNLIKELY, v8::internal::value, and WriteBarrier().
AssigningBarrier() [2/2]
template<WriteBarrierSlotType SlotType>
static void cppgc::internal::DijkstraWriteBarrierPolicy::AssigningBarrier (const void * slot, RawPointer storage) [inline], [static]
Definition at line 56 of file pointer-policies.h.
                                                                               {
    static_assert(
        SlotType == WriteBarrierSlotType::kUncompressed,
        "Assigning storages of Member and UncompressedMember is not supported");
#ifdef CPPGC_SLIM_WRITE_BARRIER
    if (V8_UNLIKELY(WriteBarrier::IsEnabled()))
      WriteBarrier::CombinedWriteBarrierSlow<SlotType>(slot);
#else // !CPPGC_SLIM_WRITE_BARRIER
    WriteBarrier::Params params;
    const WriteBarrier::Type type =
        WriteBarrier::GetWriteBarrierType(slot, storage, params);
    WriteBarrier(type, params, slot, storage.Load());
#endif // !CPPGC_SLIM_WRITE_BARRIER
  }
References cppgc::internal::WriteBarrier::GetWriteBarrierType(), cppgc::internal::WriteBarrier::IsEnabled(), cppgc::internal::kUncompressed, cppgc::internal::RawPointer::Load(), v8::internal::tracing::type, V8_UNLIKELY, and WriteBarrier().
InitializingBarrier() [1/2]
static void cppgc::internal::DijkstraWriteBarrierPolicy::InitializingBarrier (const void * , const void *) [inline], [static]
Definition at line 33 of file pointer-policies.h.
{}
InitializingBarrier() [2/2]
static void cppgc::internal::DijkstraWriteBarrierPolicy::InitializingBarrier (const void * , RawPointer storage) [inline], [static]
Definition at line 34 of file pointer-policies.h.
                                                                               {
    }
WriteBarrier()
static void cppgc::internal::DijkstraWriteBarrierPolicy::WriteBarrier (WriteBarrier::Type type, const WriteBarrier::Params & params, const void * slot, const void * value) [inline], [static], [private]
Definition at line 91 of file pointer-policies.h.
                                                                          {
    switch (type) {
      case WriteBarrier::Type::kGenerational:
        WriteBarrier::GenerationalBarrier<
            WriteBarrier::GenerationalBarrierType::kPreciseSlot>(params, slot);
        break;
      case WriteBarrier::Type::kMarking:
        WriteBarrier::DijkstraMarkingBarrier(params, value);
        break;
      case WriteBarrier::Type::kNone:
        break;
    }
  }
References cppgc::internal::WriteBarrier::DijkstraMarkingBarrier(), cppgc::internal::WriteBarrier::GenerationalBarrier(), cppgc::internal::WriteBarrier::kGenerational, cppgc::internal::WriteBarrier::kMarking, cppgc::internal::WriteBarrier::kNone, cppgc::internal::WriteBarrier::kPreciseSlot, v8::internal::tracing::type, and v8::internal::value.
Referenced by AssigningBarrier().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/include/cppgc/internal/pointer-policies.h