v8::internal::wasm::NativeModuleCache::Key Struct Reference
#include <wasm-engine.h>
Public Member Functions
Key (size_t prefix_hash, CompileTimeImports compile_imports, const base::Vector< const uint8_t > &bytes)
bool operator== (const Key &other) const
bool operator< (const Key &other) const
Public Attributes
size_t prefix_hash
CompileTimeImports compile_imports
base::Vector< const uint8_t > bytes
Detailed Description
Definition at line 75 of file wasm-engine.h.
Constructor & Destructor Documentation
Key()
v8::internal::wasm::NativeModuleCache::Key::Key (size_t prefix_hash, CompileTimeImports compile_imports, const base::Vector< const uint8_t > & bytes) [inline]
Definition at line 76 of file wasm-engine.h.
        : prefix_hash(prefix_hash),
          compile_imports(std::move(compile_imports)),
          bytes(bytes) {}
Member Function Documentation
operator<()
bool v8::internal::wasm::NativeModuleCache::Key::operator< (const Key & other) const [inline]
Definition at line 95 of file wasm-engine.h.
                                           {
      if (prefix_hash != other.prefix_hash) {
        DCHECK_IMPLIES(!bytes.empty() && !other.bytes.empty(),
                       bytes != other.bytes);
        return prefix_hash < other.prefix_hash;
      }
      if (bytes.size() != other.bytes.size()) {
        return bytes.size() < other.bytes.size();
      }
      if (int cmp = compile_imports.compare(other.compile_imports)) {
        return cmp < 0;
      }
      // Fast path when the base pointers are the same.
      // Also handles the {nullptr} case which would be UB for memcmp.
      if (bytes.begin() == other.bytes.begin()) {
        DCHECK_EQ(prefix_hash, other.prefix_hash);
        return false;
      }
      DCHECK_NOT_NULL(bytes.begin());
      DCHECK_NOT_NULL(other.bytes.begin());
      return memcmp(bytes.begin(), other.bytes.begin(), bytes.size()) < 0;
    }
References v8::base::Vector< T >::begin(), bytes, v8::internal::wasm::CompileTimeImports::compare(), compile_imports, DCHECK_EQ, DCHECK_IMPLIES, DCHECK_NOT_NULL, v8::base::Vector< T >::empty(), prefix_hash, and v8::base::Vector< T >::size().
operator==()
bool v8::internal::wasm::NativeModuleCache::Key::operator== (const Key & other) const [inline]
Definition at line 88 of file wasm-engine.h.
                                            {
      bool eq = bytes == other.bytes &&
                compile_imports.compare(other.compile_imports) == 0;
      DCHECK_IMPLIES(eq, prefix_hash == other.prefix_hash);
      return eq;
    }
References bytes, v8::internal::wasm::CompileTimeImports::compare(), compile_imports, DCHECK_IMPLIES, v8::internal::eq, and prefix_hash.
Member Data Documentation
bytes
base::Vector<const uint8_t> v8::internal::wasm::NativeModuleCache::Key::bytes
Definition at line 86 of file wasm-engine.h.
Referenced by operator<(), and operator==().
compile_imports
CompileTimeImports v8::internal::wasm::NativeModuleCache::Key::compile_imports
Definition at line 85 of file wasm-engine.h.
Referenced by operator<(), and operator==().
prefix_hash
size_t v8::internal::wasm::NativeModuleCache::Key::prefix_hash
Definition at line 84 of file wasm-engine.h.
Referenced by operator<(), and operator==().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/wasm/wasm-engine.h