v8::internal::compiler::turboshaft::fast_hash< TSCallDescriptor > Struct Reference
#include <operations.h>
Public Member Functions
size_t operator() (const TSCallDescriptor &v)
Detailed Description
Definition at line 4052 of file operations.h.
Member Function Documentation
operator()()
size_t v8::internal::compiler::turboshaft::fast_hash< TSCallDescriptor >::operator() (const TSCallDescriptor & v) [inline]
Definition at line 4053 of file operations.h.
                                               {
    const CallDescriptor& d = *v.descriptor;
    // This does not include all fields of the call descriptor, but it should be
    // sufficient to differentiate between different calls (and collisions are
    // not too critical).
    return fast_hash_combine(d.kind(), d.tag(), d.ReturnCount(),
                             d.ParameterCount(), d.GPParameterCount(),
                             d.FPParameterCount(), d.ParameterSlotCount(),
                             d.ReturnSlotCount(), d.flags());
  }
References v8::internal::compiler::turboshaft::TSCallDescriptor::descriptor, v8::internal::compiler::turboshaft::fast_hash_combine(), v8::internal::compiler::CallDescriptor::flags(), v8::internal::compiler::CallDescriptor::FPParameterCount(), v8::internal::compiler::CallDescriptor::GPParameterCount(), v8::internal::compiler::CallDescriptor::kind(), v8::internal::compiler::CallDescriptor::ParameterCount(), v8::internal::compiler::CallDescriptor::ParameterSlotCount(), v8::internal::compiler::CallDescriptor::ReturnCount(), v8::internal::compiler::CallDescriptor::ReturnSlotCount(), and v8::internal::compiler::CallDescriptor::tag().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h