v8::internal::compiler::turboshaft::StoreTypedElementOp Struct Reference
#include <operations.h>
Public Member Functions
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
OpIndex buffer () const
OpIndex base () const
OpIndex external () const
OpIndex index () const
OpIndex value () const
StoreTypedElementOp (OpIndex buffer, OpIndex base, OpIndex external, OpIndex index, OpIndex value, ExternalArrayType array_type)
auto options () const
Public Attributes
ExternalArrayType array_type
Static Public Attributes
static constexpr OpEffects effects
Additional Inherited Members
Detailed Description
Definition at line 5987 of file operations.h.
Constructor & Destructor Documentation
StoreTypedElementOp()
v8::internal::compiler::turboshaft::StoreTypedElementOp::StoreTypedElementOp (OpIndex buffer, OpIndex base, OpIndex external, OpIndex index, OpIndex value, ExternalArrayType array_type) [inline]
Definition at line 6014 of file operations.h.
      : Base(buffer, base, external, index, value), array_type(array_type) {}
Member Function Documentation
base()
OpIndex v8::internal::compiler::turboshaft::StoreTypedElementOp::base () const [inline]
Definition at line 6009 of file operations.h.
{ return Base::input(1); }
buffer()
OpIndex v8::internal::compiler::turboshaft::StoreTypedElementOp::buffer () const [inline]
Definition at line 6008 of file operations.h.
{ return Base::input(0); }
external()
OpIndex v8::internal::compiler::turboshaft::StoreTypedElementOp::external () const [inline]
Definition at line 6010 of file operations.h.
{ return Base::input(2); }
index()
OpIndex v8::internal::compiler::turboshaft::StoreTypedElementOp::index () const [inline]
Definition at line 6011 of file operations.h.
{ return Base::input(3); }
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::StoreTypedElementOp::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 5999 of file operations.h.
                                                              {
    return InitVectorOf(
        storage,
        {RegisterRepresentation::Tagged(), RegisterRepresentation::Tagged(),
         RegisterRepresentation::WordPtr(), RegisterRepresentation::WordPtr(),
         RegisterRepresentationForArrayType(array_type)});
  }
References v8::internal::compiler::turboshaft::InitVectorOf(), v8::internal::compiler::turboshaft::RegisterRepresentationForArrayType(), v8::internal::compiler::turboshaft::RegisterRepresentation::Tagged(), and v8::internal::compiler::turboshaft::RegisterRepresentation::WordPtr().
options()
auto v8::internal::compiler::turboshaft::StoreTypedElementOp::options () const [inline]
Definition at line 6020 of file operations.h.
{ return std::tuple{array_type}; }
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::StoreTypedElementOp::outputs_rep () const [inline]
Definition at line 5997 of file operations.h.
{ return {}; }
value()
OpIndex v8::internal::compiler::turboshaft::StoreTypedElementOp::value () const [inline]
Definition at line 6012 of file operations.h.
{ return Base::input(4); }
Member Data Documentation
array_type
ExternalArrayType v8::internal::compiler::turboshaft::StoreTypedElementOp::array_type
Definition at line 5988 of file operations.h.
effects
constexpr OpEffects v8::internal::compiler::turboshaft::StoreTypedElementOp::effects [static], [constexpr]
Initial value:
=
      OpEffects()
          
          .CanReadMemory()
          .CanWriteMemory()
          
          .CanDependOnChecks()
Definition at line 5990 of file operations.h.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h