v8::internal::maglev::detail::PushAllHelper< Arg1, Arg2, Args... > Struct Template Reference
#include <maglev-assembler-arm64-inl.h>
Static Public Member Functions
static void Push (MaglevAssembler *masm, Arg1 arg1, Arg2 arg2, Args... args)
static void PushReverse (MaglevAssembler *masm, Arg1 arg1, Arg2 arg2, Args... args)
Detailed Description
template<typename Arg1, typename Arg2, typename... Args>
struct v8::internal::maglev::detail::PushAllHelper< Arg1, Arg2, Args... >
Definition at line 302 of file maglev-assembler-arm64-inl.h.
Member Function Documentation
Push()
template<typename Arg1 , typename Arg2 , typename... Args>
static void v8::internal::maglev::detail::PushAllHelper< Arg1, Arg2, Args... >::Push (MaglevAssembler * masm, Arg1 arg1, Arg2 arg2, Args... args) [inline], [static]
Definition at line 303 of file maglev-assembler-arm64-inl.h.
                                                                              {
    if constexpr (is_iterator_range<Arg1>::value) {
      PushIterator(masm, arg1, arg2, args...);
    } else if constexpr (is_iterator_range<Arg2>::value) {
      if (arg2.begin() != arg2.end()) {
        auto val = *arg2.begin();
        PushAligned(masm, arg1, val);
        PushAll(masm,
                base::make_iterator_range(std::next(arg2.begin()), arg2.end()),
                args...);
      } else {
        PushAll(masm, arg1, args...);
      }
    } else {
      PushAligned(masm, arg1, arg2);
      PushAll(masm, args...);
    }
  }
References v8::base::args, v8::base::make_iterator_range(), v8::internal::maglev::detail::PushAligned(), v8::internal::MacroAssembler::PushAll(), and v8::internal::maglev::detail::PushIterator().
PushReverse()
template<typename Arg1 , typename Arg2 , typename... Args>
static void v8::internal::maglev::detail::PushAllHelper< Arg1, Arg2, Args... >::PushReverse (MaglevAssembler * masm, Arg1 arg1, Arg2 arg2, Args... args) [inline], [static]
Definition at line 321 of file maglev-assembler-arm64-inl.h.
                                        {
    if constexpr (is_iterator_range<Arg1>::value) {
      PushIteratorReverse(masm, arg1, arg2, args...);
    } else if constexpr (is_iterator_range<Arg2>::value) {
      if (arg2.begin() != arg2.end()) {
        auto val = *arg2.begin();
        PushAllReverse(
            masm,
            base::make_iterator_range(std::next(arg2.begin()), arg2.end()),
            args...);
        PushAligned(masm, val, arg1);
      } else {
        PushAllReverse(masm, arg1, args...);
      }
    } else {
      PushAllReverse(masm, args...);
      PushAligned(masm, arg2, arg1);
    }
  }
References v8::base::args, v8::base::make_iterator_range(), v8::internal::maglev::detail::PushAligned(), v8::internal::maglev::detail::PushAllReverse(), and v8::internal::maglev::detail::PushIteratorReverse().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/maglev/arm64/maglev-assembler-arm64-inl.h