v8::internal::compiler::FloatMatcher< T, kOpcode > Struct Template Reference
#include <node-matchers.h>
Public Member Functions
FloatMatcher (Node *node)
bool Is (const T &value) const
bool IsInRange (const T &low, const T &high) const
bool IsMinusZero () const
bool IsNegative () const
bool IsNaN () const
bool IsZero () const
bool IsNormal () const
bool IsInteger () const
bool IsPositiveOrNegativePowerOf2 () const
Additional Inherited Members
Detailed Description
template<typename T, IrOpcode::Value kOpcode>
struct v8::internal::compiler::FloatMatcher< T, kOpcode >
Definition at line 183 of file node-matchers.h.
Constructor & Destructor Documentation
FloatMatcher()
template<typename T , IrOpcode::Value kOpcode>
v8::internal::compiler::FloatMatcher< T, kOpcode >::FloatMatcher (Node * node) [inline], [explicit]
Definition at line 184 of file node-matchers.h.
: ValueMatcher<T, kOpcode>(node) {}
Member Function Documentation
Is()
template<typename T , IrOpcode::Value kOpcode>
bool v8::internal::compiler::FloatMatcher< T, kOpcode >::Is (const T & value) const [inline]
Definition at line 186 of file node-matchers.h.
                                {
    return this->HasResolvedValue() && this->ResolvedValue() == value;
  }
References v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), v8::internal::compiler::ValueMatcher< T, kOpcode >::ResolvedValue(), and v8::internal::value.
Referenced by v8::internal::compiler::FloatMatcher< T, kOpcode >::IsMinusZero(), v8::internal::compiler::FloatMatcher< T, kOpcode >::IsZero(), and v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeSlice().
IsInRange()
template<typename T , IrOpcode::Value kOpcode>
bool v8::internal::compiler::FloatMatcher< T, kOpcode >::IsInRange (const T & low, const T & high) const [inline]
Definition at line 189 of file node-matchers.h.
                                                    {
    return this->HasResolvedValue() && low <= this->ResolvedValue() &&
           this->ResolvedValue() <= high;
  }
References v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), and v8::internal::compiler::ValueMatcher< T, kOpcode >::ResolvedValue().
Referenced by v8::internal::compiler::JSCallReducer::ReduceBigIntAsN(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementLoadFromHeapConstant(), and v8::internal::compiler::JSCallReducer::ReduceStringPrototypeCharAt().
IsInteger()
template<typename T , IrOpcode::Value kOpcode>
bool v8::internal::compiler::FloatMatcher< T, kOpcode >::IsInteger () const [inline]
Definition at line 208 of file node-matchers.h.
                         {
    return this->HasResolvedValue() &&
           std::nearbyint(this->ResolvedValue()) == this->ResolvedValue();
  }
References v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), and v8::internal::compiler::ValueMatcher< T, kOpcode >::ResolvedValue().
Referenced by v8::internal::compiler::JSCallReducer::ReduceBigIntAsN(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementLoadFromHeapConstant(), and v8::internal::compiler::JSCallReducer::ReduceStringPrototypeCharAt().
IsMinusZero()
template<typename T , IrOpcode::Value kOpcode>
bool v8::internal::compiler::FloatMatcher< T, kOpcode >::IsMinusZero () const [inline]
Definition at line 193 of file node-matchers.h.
                           {
    return this->Is(0.0) && std::signbit(this->ResolvedValue());
  }
References v8::internal::compiler::FloatMatcher< T, kOpcode >::Is(), and v8::internal::compiler::ValueMatcher< T, kOpcode >::ResolvedValue().
IsNaN()
template<typename T , IrOpcode::Value kOpcode>
bool v8::internal::compiler::FloatMatcher< T, kOpcode >::IsNaN () const [inline]
Definition at line 199 of file node-matchers.h.
                     {
    return this->HasResolvedValue() && std::isnan(this->ResolvedValue());
  }
References v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), and v8::internal::compiler::ValueMatcher< T, kOpcode >::ResolvedValue().
Referenced by v8::internal::compiler::MachineOperatorReducer::Reduce().
IsNegative()
template<typename T , IrOpcode::Value kOpcode>
bool v8::internal::compiler::FloatMatcher< T, kOpcode >::IsNegative () const [inline]
Definition at line 196 of file node-matchers.h.
                          {
    return this->HasResolvedValue() && this->ResolvedValue() < 0.0;
  }
References v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), and v8::internal::compiler::ValueMatcher< T, kOpcode >::ResolvedValue().
IsNormal()
template<typename T , IrOpcode::Value kOpcode>
bool v8::internal::compiler::FloatMatcher< T, kOpcode >::IsNormal () const [inline]
Definition at line 205 of file node-matchers.h.
                        {
    return this->HasResolvedValue() && std::isnormal(this->ResolvedValue());
  }
References v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), and v8::internal::compiler::ValueMatcher< T, kOpcode >::ResolvedValue().
IsPositiveOrNegativePowerOf2()
template<typename T , IrOpcode::Value kOpcode>
bool v8::internal::compiler::FloatMatcher< T, kOpcode >::IsPositiveOrNegativePowerOf2 () const [inline]
Definition at line 212 of file node-matchers.h.
                                            {
    if (!this->HasResolvedValue() || (this->ResolvedValue() == 0.0)) {
      return false;
    }
    base::Double value = base::Double(this->ResolvedValue());
    return !value.IsInfinite() && base::bits::IsPowerOfTwo(value.Significand());
  }
References v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), v8::base::Double::IsInfinite(), v8::base::bits::IsPowerOfTwo(), v8::internal::compiler::ValueMatcher< T, kOpcode >::ResolvedValue(), and v8::internal::value.
IsZero()
template<typename T , IrOpcode::Value kOpcode>
bool v8::internal::compiler::FloatMatcher< T, kOpcode >::IsZero () const [inline]
Definition at line 202 of file node-matchers.h.
                      {
    return this->Is(0.0) && !std::signbit(this->ResolvedValue());
  }
References v8::internal::compiler::FloatMatcher< T, kOpcode >::Is(), and v8::internal::compiler::ValueMatcher< T, kOpcode >::ResolvedValue().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/node-matchers.h