v8::internal::compiler::AddMatcher< BinopMatcher, AddOpcode, SubOpcode, kMulOpcode, kShiftOpcode > Struct Template Reference
#include <node-matchers.h>
Public Types
using Matcher = ScaleMatcher< BinopMatcher, kMulOpcode, kShiftOpcode >
Public Member Functions
AddMatcher (Node *node, bool allow_input_swap)
AddMatcher (Node *node)
bool HasIndexInput () const
Node * IndexInput () const
int scale () const
bool power_of_two_plus_one () const
Static Public Attributes
static const IrOpcode::Value kAddOpcode = AddOpcode
static const IrOpcode::Value kSubOpcode = SubOpcode
Private Member Functions
void Initialize (Node *node, bool allow_input_swap)
Private Attributes
int scale_
bool power_of_two_plus_one_
Additional Inherited Members
Detailed Description
template<class BinopMatcher, IrOpcode::Value AddOpcode, IrOpcode::Value SubOpcode, IrOpcode::Value kMulOpcode, IrOpcode::Value kShiftOpcode>
struct v8::internal::compiler::AddMatcher< BinopMatcher, AddOpcode, SubOpcode, kMulOpcode, kShiftOpcode >
Definition at line 424 of file node-matchers.h.
Member Typedef Documentation
Matcher
template<class BinopMatcher , IrOpcode::Value AddOpcode, IrOpcode::Value SubOpcode, IrOpcode::Value kMulOpcode, IrOpcode::Value kShiftOpcode>
using v8::internal::compiler::AddMatcher< BinopMatcher, AddOpcode, SubOpcode, kMulOpcode, kShiftOpcode >::Matcher = ScaleMatcher<BinopMatcher, kMulOpcode, kShiftOpcode>
Definition at line 427 of file node-matchers.h.
Constructor & Destructor Documentation
AddMatcher() [1/2]
template<class BinopMatcher , IrOpcode::Value AddOpcode, IrOpcode::Value SubOpcode, IrOpcode::Value kMulOpcode, IrOpcode::Value kShiftOpcode>
v8::internal::compiler::AddMatcher< BinopMatcher, AddOpcode, SubOpcode, kMulOpcode, kShiftOpcode >::AddMatcher (Node * node, bool allow_input_swap) [inline]
Definition at line 429 of file node-matchers.h.
      : BinopMatcher(node, allow_input_swap),
        scale_(-1),
        power_of_two_plus_one_(false) {
    Initialize(node, allow_input_swap);
  }
References v8::internal::compiler::AddMatcher< BinopMatcher, AddOpcode, SubOpcode, kMulOpcode, kShiftOpcode >::Initialize(), and v8::internal::compiler::NodeMatcher::node().
AddMatcher() [2/2]
template<class BinopMatcher , IrOpcode::Value AddOpcode, IrOpcode::Value SubOpcode, IrOpcode::Value kMulOpcode, IrOpcode::Value kShiftOpcode>
v8::internal::compiler::AddMatcher< BinopMatcher, AddOpcode, SubOpcode, kMulOpcode, kShiftOpcode >::AddMatcher (Node * node) [inline], [explicit]
Definition at line 435 of file node-matchers.h.
      : BinopMatcher(node, node->op()->HasProperty(Operator::kCommutative)),
        scale_(-1),
        power_of_two_plus_one_(false) {
    Initialize(node, node->op()->HasProperty(Operator::kCommutative));
  }
References v8::internal::compiler::Operator::HasProperty(), v8::internal::compiler::AddMatcher< BinopMatcher, AddOpcode, SubOpcode, kMulOpcode, kShiftOpcode >::Initialize(), v8::internal::compiler::Operator::kCommutative, v8::internal::compiler::NodeMatcher::node(), and v8::internal::compiler::Node::op().
Member Function Documentation
HasIndexInput()
template<class BinopMatcher , IrOpcode::Value AddOpcode, IrOpcode::Value SubOpcode, IrOpcode::Value kMulOpcode, IrOpcode::Value kShiftOpcode>
bool v8::internal::compiler::AddMatcher< BinopMatcher, AddOpcode, SubOpcode, kMulOpcode, kShiftOpcode >::HasIndexInput () const [inline]
Definition at line 442 of file node-matchers.h.
{ return scale_ != -1; }
References v8::internal::compiler::AddMatcher< BinopMatcher, AddOpcode, SubOpcode, kMulOpcode, kShiftOpcode >::scale_.
Referenced by v8::internal::compiler::AddMatcher< BinopMatcher, AddOpcode, SubOpcode, kMulOpcode, kShiftOpcode >::IndexInput(), v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::Initialize(), and v8::internal::compiler::AddMatcher< BinopMatcher, AddOpcode, SubOpcode, kMulOpcode, kShiftOpcode >::scale().
IndexInput()
template<class BinopMatcher , IrOpcode::Value AddOpcode, IrOpcode::Value SubOpcode, IrOpcode::Value kMulOpcode, IrOpcode::Value kShiftOpcode>
Node* v8::internal::compiler::AddMatcher< BinopMatcher, AddOpcode, SubOpcode, kMulOpcode, kShiftOpcode >::IndexInput () const [inline]
Definition at line 443 of file node-matchers.h.
                           {
    DCHECK(HasIndexInput());
    return this->left().node()->InputAt(0);
  }
References v8::internal::DCHECK(), v8::internal::compiler::AddMatcher< BinopMatcher, AddOpcode, SubOpcode, kMulOpcode, kShiftOpcode >::HasIndexInput(), and v8::internal::compiler::BinopMatcher< Left, Right, rep >::left().
Referenced by v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::Initialize().
Initialize()
template<class BinopMatcher , IrOpcode::Value AddOpcode, IrOpcode::Value SubOpcode, IrOpcode::Value kMulOpcode, IrOpcode::Value kShiftOpcode>
void v8::internal::compiler::AddMatcher< BinopMatcher, AddOpcode, SubOpcode, kMulOpcode, kShiftOpcode >::Initialize (Node * node, bool allow_input_swap) [inline], [private]
Definition at line 454 of file node-matchers.h.
                                                     {
    Matcher left_matcher(this->left().node(), true);
    if (left_matcher.matches()) {
      scale_ = left_matcher.scale();
      power_of_two_plus_one_ = left_matcher.power_of_two_plus_one();
      return;
    }
    if (!allow_input_swap) {
      return;
    }
    Matcher right_matcher(this->right().node(), true);
    if (right_matcher.matches()) {
      scale_ = right_matcher.scale();
      power_of_two_plus_one_ = right_matcher.power_of_two_plus_one();
      this->SwapInputs();
      return;
    }
    if ((this->left().opcode() != kSubOpcode &&
         this->left().opcode() != kAddOpcode) &&
        (this->right().opcode() == kAddOpcode ||
         this->right().opcode() == kSubOpcode)) {
      this->SwapInputs();
    }
  }
References v8::internal::compiler::BinopMatcher< Left, Right, rep >::left(), v8::internal::compiler::ScaleMatcher< BinopMatcher, kMulOpcode, kShiftOpcode >::matches(), v8::internal::compiler::NodeMatcher::node(), v8::internal::compiler::NodeMatcher::opcode(), v8::internal::compiler::ScaleMatcher< BinopMatcher, kMulOpcode, kShiftOpcode >::power_of_two_plus_one(), v8::internal::compiler::AddMatcher< BinopMatcher, AddOpcode, SubOpcode, kMulOpcode, kShiftOpcode >::power_of_two_plus_one_, v8::internal::compiler::BinopMatcher< Left, Right, rep >::right(), v8::internal::compiler::ScaleMatcher< BinopMatcher, kMulOpcode, kShiftOpcode >::scale(), v8::internal::compiler::AddMatcher< BinopMatcher, AddOpcode, SubOpcode, kMulOpcode, kShiftOpcode >::scale_, and v8::internal::compiler::BinopMatcher< Left, Right, rep >::SwapInputs().
Referenced by v8::internal::compiler::AddMatcher< BinopMatcher, AddOpcode, SubOpcode, kMulOpcode, kShiftOpcode >::AddMatcher().
power_of_two_plus_one()
template<class BinopMatcher , IrOpcode::Value AddOpcode, IrOpcode::Value SubOpcode, IrOpcode::Value kMulOpcode, IrOpcode::Value kShiftOpcode>
bool v8::internal::compiler::AddMatcher< BinopMatcher, AddOpcode, SubOpcode, kMulOpcode, kShiftOpcode >::power_of_two_plus_one () const [inline]
Definition at line 451 of file node-matchers.h.
{ return power_of_two_plus_one_; }
References v8::internal::compiler::AddMatcher< BinopMatcher, AddOpcode, SubOpcode, kMulOpcode, kShiftOpcode >::power_of_two_plus_one_.
Referenced by v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::Initialize().
scale()
template<class BinopMatcher , IrOpcode::Value AddOpcode, IrOpcode::Value SubOpcode, IrOpcode::Value kMulOpcode, IrOpcode::Value kShiftOpcode>
int v8::internal::compiler::AddMatcher< BinopMatcher, AddOpcode, SubOpcode, kMulOpcode, kShiftOpcode >::scale () const [inline]
Definition at line 447 of file node-matchers.h.
                    {
    DCHECK(HasIndexInput());
    return scale_;
  }
References v8::internal::DCHECK(), v8::internal::compiler::AddMatcher< BinopMatcher, AddOpcode, SubOpcode, kMulOpcode, kShiftOpcode >::HasIndexInput(), and v8::internal::compiler::AddMatcher< BinopMatcher, AddOpcode, SubOpcode, kMulOpcode, kShiftOpcode >::scale_.
Referenced by v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::Initialize().
Member Data Documentation
kAddOpcode
template<class BinopMatcher , IrOpcode::Value AddOpcode, IrOpcode::Value SubOpcode, IrOpcode::Value kMulOpcode, IrOpcode::Value kShiftOpcode>
const IrOpcode::Value v8::internal::compiler::AddMatcher< BinopMatcher, AddOpcode, SubOpcode, kMulOpcode, kShiftOpcode >::kAddOpcode = AddOpcode [static]
Definition at line 425 of file node-matchers.h.
Referenced by v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::Initialize().
kSubOpcode
template<class BinopMatcher , IrOpcode::Value AddOpcode, IrOpcode::Value SubOpcode, IrOpcode::Value kMulOpcode, IrOpcode::Value kShiftOpcode>
const IrOpcode::Value v8::internal::compiler::AddMatcher< BinopMatcher, AddOpcode, SubOpcode, kMulOpcode, kShiftOpcode >::kSubOpcode = SubOpcode [static]
Definition at line 426 of file node-matchers.h.
Referenced by v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::Initialize().
power_of_two_plus_one_
template<class BinopMatcher , IrOpcode::Value AddOpcode, IrOpcode::Value SubOpcode, IrOpcode::Value kMulOpcode, IrOpcode::Value kShiftOpcode>
bool v8::internal::compiler::AddMatcher< BinopMatcher, AddOpcode, SubOpcode, kMulOpcode, kShiftOpcode >::power_of_two_plus_one_ [private]
Definition at line 483 of file node-matchers.h.
Referenced by v8::internal::compiler::AddMatcher< BinopMatcher, AddOpcode, SubOpcode, kMulOpcode, kShiftOpcode >::Initialize(), and v8::internal::compiler::AddMatcher< BinopMatcher, AddOpcode, SubOpcode, kMulOpcode, kShiftOpcode >::power_of_two_plus_one().
scale_
template<class BinopMatcher , IrOpcode::Value AddOpcode, IrOpcode::Value SubOpcode, IrOpcode::Value kMulOpcode, IrOpcode::Value kShiftOpcode>
int v8::internal::compiler::AddMatcher< BinopMatcher, AddOpcode, SubOpcode, kMulOpcode, kShiftOpcode >::scale_ [private]
Definition at line 482 of file node-matchers.h.
Referenced by v8::internal::compiler::AddMatcher< BinopMatcher, AddOpcode, SubOpcode, kMulOpcode, kShiftOpcode >::HasIndexInput(), v8::internal::compiler::AddMatcher< BinopMatcher, AddOpcode, SubOpcode, kMulOpcode, kShiftOpcode >::Initialize(), and v8::internal::compiler::AddMatcher< BinopMatcher, AddOpcode, SubOpcode, kMulOpcode, kShiftOpcode >::scale().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/node-matchers.h