v8::internal::wasm::CompilationEnv Struct Reference
#include <compilation-environment.h>
Static Public Member Functions
static CompilationEnv ForModule (const NativeModule *native_module)
static CompilationEnv NoModuleAllFeaturesForTesting ()
Public Attributes
const WasmModule *const module
const WasmEnabledFeatures enabled_features
const std::atomic< Address > * fast_api_targets
std::atomic< const MachineSignature * > * fast_api_signatures
std::shared_ptr< WasmModuleCoverageData > module_coverage_data
Private Member Functions
CompilationEnv (const WasmModule *module, WasmEnabledFeatures enabled_features, std::atomic< Address > *fast_api_targets, std::atomic< const MachineSignature * > *fast_api_signatures, std::shared_ptr< WasmModuleCoverageData > module_coverage_data)
Detailed Description
Definition at line 52 of file compilation-environment.h.
Constructor & Destructor Documentation
CompilationEnv()
v8::internal::wasm::CompilationEnv::CompilationEnv (const WasmModule * module, WasmEnabledFeatures enabled_features, std::atomic< Address > * fast_api_targets, std::atomic< const MachineSignature * > * fast_api_signatures, std::shared_ptr< WasmModuleCoverageData > module_coverage_data) [inline], [private]
Definition at line 73 of file compilation-environment.h.
      : module(module),
        enabled_features(enabled_features),
        fast_api_targets(fast_api_targets),
        fast_api_signatures(fast_api_signatures),
        module_coverage_data(std::move(module_coverage_data)) {}
Referenced by ForModule(), and NoModuleAllFeaturesForTesting().
Member Function Documentation
ForModule()
CompilationEnv v8::internal::wasm::CompilationEnv::ForModule (const NativeModule * native_module) [inline], [static]
Definition at line 19 of file compilation-environment-inl.h.
                                       {
  return CompilationEnv(
      native_module->module(), native_module->enabled_features(),
      native_module->fast_api_targets(), native_module->fast_api_signatures(),
      native_module->coverage_data());
}
References CompilationEnv(), v8::internal::wasm::NativeModule::coverage_data(), v8::internal::wasm::NativeModule::enabled_features(), v8::internal::wasm::NativeModule::fast_api_signatures(), v8::internal::wasm::NativeModule::fast_api_targets(), and v8::internal::wasm::NativeModule::module().
Referenced by v8::internal::wasm::CompileLazy(), v8::internal::wasm::WasmCompilationUnit::CompileWasmFunction(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ExecuteCompilationUnits(), v8::internal::wasm::GenerateLiftoffDebugSideTable(), v8::internal::wasm::DebugInfoImpl::RecompileLiftoffWithBreakpoints(), and v8::internal::compiler::turboshaft::WasmInJSInliningReducer< Next >::TryInlineWasmCall().
NoModuleAllFeaturesForTesting()
CompilationEnv v8::internal::wasm::CompilationEnv::NoModuleAllFeaturesForTesting () [inline], [static]
Definition at line 27 of file compilation-environment-inl.h.
                                                                    {
  return CompilationEnv(nullptr, WasmEnabledFeatures::All(), nullptr, nullptr,
                        nullptr);
}
References v8::internal::wasm::WasmEnabledFeatures::All(), and CompilationEnv().
Member Data Documentation
enabled_features
const WasmEnabledFeatures v8::internal::wasm::CompilationEnv::enabled_features
Definition at line 57 of file compilation-environment.h.
Referenced by v8::internal::wasm::BuildTSGraph(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::CheckBailoutAllowed(), v8::internal::wasm::WasmCompilationUnit::ExecuteCompilation(), v8::internal::wasm::ExecuteLiftoffCompilation(), v8::internal::wasm::GenerateLiftoffDebugSideTable(), and v8::internal::wasm::DebugInfoImpl::RecompileLiftoffWithBreakpoints().
fast_api_signatures
std::atomic<const MachineSignature*>* v8::internal::wasm::CompilationEnv::fast_api_signatures
Definition at line 61 of file compilation-environment.h.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::WellKnown_FastApi().
fast_api_targets
const std::atomic<Address>* v8::internal::wasm::CompilationEnv::fast_api_targets
Definition at line 59 of file compilation-environment.h.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::WellKnown_FastApi().
module
const WasmModule* const v8::internal::wasm::CompilationEnv::module
Definition at line 54 of file compilation-environment.h.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildIndirectCallTargetAndImplicitArg(), v8::internal::wasm::BuildTSGraph(), v8::internal::wasm::TurboshaftGraphBuildingInterface::deopts_enabled(), v8::internal::wasm::WasmCompilationUnit::ExecuteCompilation(), v8::internal::wasm::ExecuteLiftoffCompilation(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::GetCompilationEventName(), v8::internal::wasm::DebugInfoImpl::RecompileLiftoffWithBreakpoints(), v8::internal::compiler::WasmGraphBuilder::SetType(), v8::internal::wasm::TurboshaftGraphBuildingInterface::TurboshaftGraphBuildingInterface(), v8::internal::compiler::WasmGraphBuilder::TypeGuard(), and v8::internal::compiler::WasmGraphBuilder::WasmGraphBuilder().
module_coverage_data
std::shared_ptr<WasmModuleCoverageData> v8::internal::wasm::CompilationEnv::module_coverage_data
Definition at line 63 of file compilation-environment.h.
Referenced by v8::internal::wasm::ExecuteLiftoffCompilation().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/wasm/compilation-environment.h
/mnt/V8SourceCode/src/wasm/compilation-environment-inl.h