v8::internal::compiler::turboshaft::LoadOp Struct Reference
#include <operations.h>
Classes
struct Kind
Public Member Functions
OpEffects Effects () const
base::Vector< const RegisterRepresentation > outputs_rep () const
MachineType machine_type () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
OpIndex base () const
OptionalOpIndex index () const
LoadOp (OpIndex base, OptionalOpIndex index, Kind kind, MemoryRepresentation loaded_rep, RegisterRepresentation result_rep, int32_t offset, uint8_t element_size_log2)
template<typename Fn , typename Mapper >
auto Explode (Fn fn, Mapper &mapper) const
void Validate (const Graph &graph) const
void PrintInputs (std::ostream &os, const std::string &op_index_prefix) const
void PrintOptions (std::ostream &os) const
auto options () const
Static Public Member Functions
static constexpr bool OffsetIsValid (int32_t offset, bool tagged_base)
static LoadOp & New (Graph *graph, OpIndex base, OptionalOpIndex index, Kind kind, MemoryRepresentation loaded_rep, RegisterRepresentation result_rep, int32_t offset, uint8_t element_size_log2)
Public Attributes
Kind kind
MemoryRepresentation loaded_rep
RegisterRepresentation result_rep
uint8_t element_size_log2
int32_t offset
Additional Inherited Members
Detailed Description
Definition at line 2852 of file operations.h.
Constructor & Destructor Documentation
LoadOp()
v8::internal::compiler::turboshaft::LoadOp::LoadOp (OpIndex base, OptionalOpIndex index, Kind kind, MemoryRepresentation loaded_rep, RegisterRepresentation result_rep, int32_t offset, uint8_t element_size_log2) [inline]
Definition at line 3037 of file operations.h.
      : Base(1 + index.valid()),
        kind(kind),
        loaded_rep(loaded_rep),
        result_rep(result_rep),
        element_size_log2(element_size_log2),
        offset(offset) {
    input(0) = base;
    if (index.valid()) {
      input(1) = index.value();
    }
  }
References v8::internal::index.
Member Function Documentation
base()
OpIndex v8::internal::compiler::turboshaft::LoadOp::base () const [inline]
Definition at line 3022 of file operations.h.
{ return input(0); }
Referenced by v8::internal::compiler::turboshaft::MemoryContentTable::Find(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::ExtendingLoadMatcher::Initialize(), v8::internal::compiler::ExtendingLoadMatcher::Initialize(), v8::internal::compiler::turboshaft::MemoryContentTable::Insert(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Load(), PrintInputs(), v8::internal::compiler::turboshaft::RedundantStoreAnalysis::ProcessBlock(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessLoad(), v8::internal::compiler::turboshaft::anonymous_namespace{decompression-optimization.cc}::DecompressionAnalyzer::ProcessOperation(), and v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Shuffle().
Effects()
OpEffects v8::internal::compiler::turboshaft::LoadOp::Effects () const [inline]
Definition at line 2993 of file operations.h.
                            {
    // Loads might depend on checks for pointer validity, object layout, bounds
    // checks, etc.
    // TODO(tebbi): Distinguish between on-heap and off-heap loads.
    OpEffects effects = OpEffects().CanReadMemory().CanDependOnChecks();
    if (kind.with_trap_handler) effects = effects.CanLeaveCurrentFunction();
    if (kind.is_atomic) {
      // Atomic load should not be reordered with other loads.
      effects = effects.CanWriteMemory();
    }
    return effects;
  }
References v8::internal::compiler::turboshaft::OpEffects::CanDependOnChecks(), v8::internal::compiler::turboshaft::OpEffects::CanLeaveCurrentFunction(), v8::internal::compiler::turboshaft::OpEffects::CanReadMemory(), and v8::internal::compiler::turboshaft::OpEffects::CanWriteMemory().
Explode()
template<typename Fn , typename Mapper >
auto v8::internal::compiler::turboshaft::LoadOp::Explode (Fn fn, Mapper & mapper) const [inline]
Definition at line 3053 of file operations.h.
                                                      {
    return fn(mapper.Map(base()), mapper.Map(index()), kind, loaded_rep,
              result_rep, offset, element_size_log2);
  }
References v8::internal::index.
index()
OptionalOpIndex v8::internal::compiler::turboshaft::LoadOp::index () const [inline]
Definition at line 3023 of file operations.h.
                                {
    return input_count == 2 ? input(1) : OpIndex::Invalid();
  }
References v8::internal::compiler::turboshaft::detail::input_count(), and v8::internal::compiler::turboshaft::OpIndex::Invalid().
Referenced by v8::internal::compiler::turboshaft::MemoryContentTable::Find(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::ExtendingLoadMatcher::Initialize(), v8::internal::compiler::ExtendingLoadMatcher::Initialize(), v8::internal::compiler::turboshaft::MemoryContentTable::Insert(), PrintInputs(), v8::internal::compiler::turboshaft::RedundantStoreAnalysis::ProcessBlock(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessLoad(), v8::internal::compiler::turboshaft::anonymous_namespace{decompression-optimization.cc}::DecompressionAnalyzer::ProcessOperation(), and v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Shuffle().
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::LoadOp::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 3011 of file operations.h.
                                                              {
    base::Vector<const MaybeRegisterRepresentation> result =
        kind.tagged_base
            ? MaybeRepVector<MaybeRegisterRepresentation::Tagged(),
                             MaybeRegisterRepresentation::WordPtr()>()
            : MaybeRepVector<MaybeRegisterRepresentation::WordPtr(),
                             MaybeRegisterRepresentation::WordPtr()>();
    return index().valid() ? result : base::VectorOf(result.data(), 1);
  }
References v8::internal::index, v8::internal::compiler::turboshaft::MaybeRepVector(), v8::base::internal::result, v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::Tagged(), v8::base::VectorOf(), and v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::WordPtr().
machine_type()
MachineType v8::internal::compiler::turboshaft::LoadOp::machine_type () const
Definition at line 604 of file operations.cc.
                                       {
  if (result_rep == RegisterRepresentation::Compressed()) {
    if (loaded_rep == MemoryRepresentation::AnyTagged()) {
      return MachineType::AnyCompressed();
    } else if (loaded_rep == MemoryRepresentation::TaggedPointer()) {
      return MachineType::CompressedPointer();
    }
  }
  return loaded_rep.ToMachineType();
}
References v8::internal::MachineType::AnyCompressed(), v8::internal::compiler::turboshaft::MemoryRepresentation::AnyTagged(), v8::internal::compiler::turboshaft::RegisterRepresentation::Compressed(), v8::internal::MachineType::CompressedPointer(), loaded_rep, result_rep, v8::internal::compiler::turboshaft::MemoryRepresentation::TaggedPointer(), and v8::internal::compiler::turboshaft::MemoryRepresentation::ToMachineType().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::IsNodeUnsigned(), and v8::internal::compiler::InstructionSelector::VisitNode().
New()
static LoadOp& v8::internal::compiler::turboshaft::LoadOp::New (Graph * graph, OpIndex base, OptionalOpIndex index, Kind kind, MemoryRepresentation loaded_rep, RegisterRepresentation result_rep, int32_t offset, uint8_t element_size_log2) [inline], [static]
Definition at line 3068 of file operations.h.
                                                {
    return Base::New(graph, 1 + index.valid(), base, index, kind, loaded_rep,
                     result_rep, offset, element_size_log2);
  }
References graph(), v8::internal::index, and v8::internal::anonymous_namespace{intl-objects.cc}::New().
OffsetIsValid()
static constexpr bool v8::internal::compiler::turboshaft::LoadOp::OffsetIsValid (int32_t offset, bool tagged_base) [inline], [static], [constexpr]
Definition at line 3027 of file operations.h.
                                                                        {
    if (tagged_base) {
      // When a Load has the tagged_base Kind, it means that {offset} will
      // eventually need a "-kHeapObjectTag". If the {offset} is
      // min_int, then subtracting kHeapObjectTag will underflow.
      return offset >= std::numeric_limits<int32_t>::min() + kHeapObjectTag;
    }
    return true;
  }
References v8::internal::kHeapObjectTag.
Referenced by v8::internal::compiler::turboshaft::LoadStoreSimplificationReducer< Next >::CanEncodeOffset(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::IncreaseOffset(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryAdjustOffset(), and v8::internal::compiler::turboshaft::StoreOp::Validate().
options()
auto v8::internal::compiler::turboshaft::LoadOp::options () const [inline]
Definition at line 3077 of file operations.h.
                       {
    return std::tuple{kind, loaded_rep, result_rep, offset, element_size_log2};
  }
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::LoadOp::outputs_rep () const [inline]
Definition at line 3005 of file operations.h.
                                                               {
    return base::VectorOf(&result_rep, 1);
  }
References v8::base::VectorOf().
Referenced by v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessLoad().
PrintInputs()
void v8::internal::compiler::turboshaft::LoadOp::PrintInputs (std::ostream & os, const std::string & op_index_prefix) const
Definition at line 615 of file operations.cc.
                                                                 {
  os << " *(" << op_index_prefix << base().id();
  if (offset < 0) {
    os << " - " << -offset;
  } else if (offset > 0) {
    os << " + " << offset;
  }
  if (index().valid()) {
    os << " + " << op_index_prefix << index().value().id();
    if (element_size_log2 > 0) os << '*' << (1 << element_size_log2);
  }
  os << ") ";
}
References base(), element_size_log2, v8::internal::compiler::turboshaft::OpIndex::id(), index(), offset, and v8::internal::compiler::turboshaft::OptionalOpIndex::value().
PrintOptions()
void v8::internal::compiler::turboshaft::LoadOp::PrintOptions (std::ostream & os) const
Definition at line 629 of file operations.cc.
                                              {
  os << '[';
  os << (kind.tagged_base ? "tagged base" : "raw");
  if (kind.maybe_unaligned) os << ", unaligned";
  if (kind.with_trap_handler) os << ", protected";
  os << ", " << loaded_rep;
  os << ", " << result_rep;
  if (element_size_log2 != 0)
    os << ", element size: 2^" << int{element_size_log2};
  if (offset != 0) os << ", offset: " << offset;
  os << ']';
}
References element_size_log2, kind, loaded_rep, v8::internal::compiler::turboshaft::LoadOp::Kind::maybe_unaligned, offset, result_rep, v8::internal::compiler::turboshaft::LoadOp::Kind::tagged_base, and v8::internal::compiler::turboshaft::LoadOp::Kind::with_trap_handler.
Validate()
void v8::internal::compiler::turboshaft::LoadOp::Validate (const Graph & graph) const [inline]
Definition at line 3058 of file operations.h.
                                          {
    DCHECK(loaded_rep.ToRegisterRepresentation() == result_rep ||
           (loaded_rep.IsCompressibleTagged() &&
            result_rep == RegisterRepresentation::Compressed()) ||
           kind.is_atomic);
    DCHECK_IMPLIES(element_size_log2 > 0, index().valid());
    DCHECK_IMPLIES(kind.maybe_unaligned,
                   !SupportedOperations::IsUnalignedLoadSupported(loaded_rep));
    DCHECK(OffsetIsValid(offset, kind.tagged_base));
  }
References v8::internal::compiler::turboshaft::RegisterRepresentation::Compressed(), v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::index, v8::internal::compiler::turboshaft::MemoryRepresentation::IsCompressibleTagged(), v8::internal::compiler::turboshaft::SupportedOperations::IsUnalignedLoadSupported(), and v8::internal::compiler::turboshaft::MemoryRepresentation::ToRegisterRepresentation().
Member Data Documentation
element_size_log2
uint8_t v8::internal::compiler::turboshaft::LoadOp::element_size_log2
Definition at line 2990 of file operations.h.
Referenced by v8::internal::compiler::turboshaft::MemoryContentTable::Find(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::ExtendingLoadMatcher::Initialize(), v8::internal::compiler::ExtendingLoadMatcher::Initialize(), v8::internal::compiler::turboshaft::MemoryContentTable::Insert(), PrintInputs(), and PrintOptions().
kind
Kind v8::internal::compiler::turboshaft::LoadOp::kind
Definition at line 2987 of file operations.h.
Referenced by v8::internal::compiler::turboshaft::MemoryContentTable::Insert(), PrintOptions(), v8::internal::compiler::turboshaft::RedundantStoreAnalysis::ProcessBlock(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessLoad(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Shuffle(), and v8::internal::compiler::InstructionSelector::VisitNode().
loaded_rep
MemoryRepresentation v8::internal::compiler::turboshaft::LoadOp::loaded_rep
Definition at line 2988 of file operations.h.
Referenced by v8::internal::compiler::turboshaft::SLPTree::BuildTreeRec(), v8::internal::compiler::turboshaft::MemoryContentTable::Find(), v8::internal::compiler::turboshaft::MemoryContentTable::Insert(), v8::internal::compiler::turboshaft::IsInt32TruncatedLoadPattern(), machine_type(), v8::internal::compiler::turboshaft::anonymous_namespace{decompression-optimization.cc}::DecompressionAnalyzer::MarkAddressingBase(), PrintOptions(), and v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessLoad().
offset
int32_t v8::internal::compiler::turboshaft::LoadOp::offset
Definition at line 2991 of file operations.h.
Referenced by v8::internal::compiler::turboshaft::MemoryContentTable::Find(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::ExtendingLoadMatcher::Initialize(), v8::internal::compiler::ExtendingLoadMatcher::Initialize(), v8::internal::compiler::turboshaft::MemoryContentTable::Insert(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Load(), PrintInputs(), PrintOptions(), v8::internal::compiler::turboshaft::RedundantStoreAnalysis::ProcessBlock(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessLoad(), and v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Shuffle().
result_rep
RegisterRepresentation v8::internal::compiler::turboshaft::LoadOp::result_rep
Definition at line 2989 of file operations.h.
Referenced by machine_type(), PrintOptions(), and v8::internal::compiler::InstructionSelector::VisitNode().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h
/mnt/V8SourceCode/src/compiler/turboshaft/operations.cc