v8::internal::ParserBase< Impl >::ClassInfo Struct Reference
#include <parser-base.h>
Public Member Functions
ClassInfo (ParserBase *parser)
bool has_static_elements () const
bool has_instance_members () const
DeclarationScope * EnsureStaticElementsScope (ParserBase *parser, int beg_pos, int info_id)
DeclarationScope * EnsureInstanceMembersScope (ParserBase *parser, int beg_pos, int info_id)
Public Attributes
ExpressionT extends
ClassPropertyListT public_members
ClassPropertyListT private_members
ClassStaticElementListT static_elements
ClassPropertyListT instance_fields
FunctionLiteralT constructor
DeclarationScope * static_elements_scope = nullptr
DeclarationScope * instance_members_scope = nullptr
Variable * home_object_variable = nullptr
Variable * static_home_object_variable = nullptr
int autoaccessor_count = 0
int static_elements_function_id = -1
int instance_members_function_id = -1
int computed_field_count = 0
bool has_seen_constructor = false
bool has_static_computed_names: 1 = false
bool has_static_private_methods_or_accessors: 1 = false
bool has_static_blocks: 1 = false
bool requires_brand: 1 = false
bool is_anonymous: 1 = false
Detailed Description
template<typename Impl>
struct v8::internal::ParserBase< Impl >::ClassInfo
Definition at line 605 of file parser-base.h.
Constructor & Destructor Documentation
ClassInfo()
template<typename Impl >
v8::internal::ParserBase< Impl >::ClassInfo::ClassInfo (ParserBase * parser) [inline], [explicit]
Definition at line 607 of file parser-base.h.
        : extends(parser->impl()->NullExpression()),
          public_members(parser->impl()->NewClassPropertyList(4)),
          private_members(parser->impl()->NewClassPropertyList(4)),
          static_elements(parser->impl()->NewClassStaticElementList(4)),
          instance_fields(parser->impl()->NewClassPropertyList(4)),
          constructor(parser->impl()->NullExpression()) {}
Member Function Documentation
EnsureInstanceMembersScope()
template<typename Impl >
DeclarationScope* v8::internal::ParserBase< Impl >::ClassInfo::EnsureInstanceMembersScope (ParserBase * parser, int beg_pos, int info_id) [inline]
Definition at line 643 of file parser-base.h.
                                                                           {
      if (!has_instance_members()) {
        instance_members_scope = parser->NewFunctionScope(
            FunctionKind::kClassMembersInitializerFunction);
        instance_members_scope->SetLanguageMode(LanguageMode::kStrict);
        instance_members_scope->set_start_position(beg_pos);
        instance_members_function_id = info_id;
        // Actually consume the id. The id that was passed in might be an
        // earlier id in case of computed property names.
        parser->GetNextInfoId();
      }
      return instance_members_scope;
    }
References v8::internal::ParserBase< Impl >::GetNextInfoId(), v8::internal::ParserBase< Impl >::ClassInfo::has_instance_members(), v8::internal::ParserBase< Impl >::ClassInfo::instance_members_function_id, v8::internal::ParserBase< Impl >::ClassInfo::instance_members_scope, v8::internal::kClassMembersInitializerFunction, v8::internal::kStrict, v8::internal::ParserBase< Impl >::NewFunctionScope(), v8::internal::Scope::set_start_position(), and v8::internal::Scope::SetLanguageMode().
Referenced by v8::internal::ParserBase< Impl >::ParseMemberInitializer().
EnsureStaticElementsScope()
template<typename Impl >
DeclarationScope* v8::internal::ParserBase< Impl >::ClassInfo::EnsureStaticElementsScope (ParserBase * parser, int beg_pos, int info_id) [inline]
Definition at line 628 of file parser-base.h.
                                                             {
      if (!has_static_elements()) {
        static_elements_scope = parser->NewFunctionScope(
            FunctionKind::kClassStaticInitializerFunction);
        static_elements_scope->SetLanguageMode(LanguageMode::kStrict);
        static_elements_scope->set_start_position(beg_pos);
        static_elements_function_id = info_id;
        // Actually consume the id. The id that was passed in might be an
        // earlier id in case of computed property names.
        parser->GetNextInfoId();
      }
      return static_elements_scope;
    }
References v8::internal::ParserBase< Impl >::GetNextInfoId(), v8::internal::ParserBase< Impl >::ClassInfo::has_static_elements(), v8::internal::kClassStaticInitializerFunction, v8::internal::kStrict, v8::internal::ParserBase< Impl >::NewFunctionScope(), v8::internal::Scope::set_start_position(), v8::internal::Scope::SetLanguageMode(), v8::internal::ParserBase< Impl >::ClassInfo::static_elements_function_id, and v8::internal::ParserBase< Impl >::ClassInfo::static_elements_scope.
Referenced by v8::internal::ParserBase< Impl >::ParseClassStaticBlock(), and v8::internal::ParserBase< Impl >::ParseMemberInitializer().
has_instance_members()
template<typename Impl >
bool v8::internal::ParserBase< Impl >::ClassInfo::has_instance_members () const [inline]
Definition at line 624 of file parser-base.h.
                                      {
      return instance_members_scope != nullptr;
    }
References v8::internal::ParserBase< Impl >::ClassInfo::instance_members_scope.
Referenced by v8::internal::ParserBase< Impl >::ClassInfo::EnsureInstanceMembersScope(), and v8::internal::ParserBase< Impl >::ParseClassPropertyDefinition().
has_static_elements()
template<typename Impl >
bool v8::internal::ParserBase< Impl >::ClassInfo::has_static_elements () const [inline]
Definition at line 621 of file parser-base.h.
                                     {
      return static_elements_scope != nullptr;
    }
References v8::internal::ParserBase< Impl >::ClassInfo::static_elements_scope.
Referenced by v8::internal::ParserBase< Impl >::ClassInfo::EnsureStaticElementsScope(), and v8::internal::ParserBase< Impl >::ParseClassPropertyDefinition().
Member Data Documentation
autoaccessor_count
template<typename Impl >
int v8::internal::ParserBase< Impl >::ClassInfo::autoaccessor_count = 0
Definition at line 662 of file parser-base.h.
computed_field_count
template<typename Impl >
int v8::internal::ParserBase< Impl >::ClassInfo::computed_field_count = 0
Definition at line 665 of file parser-base.h.
Referenced by v8::internal::ParserBase< Impl >::ParseClassLiteralBody().
constructor
template<typename Impl >
FunctionLiteralT v8::internal::ParserBase< Impl >::ClassInfo::constructor
Definition at line 619 of file parser-base.h.
extends
template<typename Impl >
ExpressionT v8::internal::ParserBase< Impl >::ClassInfo::extends
Definition at line 614 of file parser-base.h.
Referenced by v8::internal::ParserBase< Impl >::ParseClassLiteral(), and v8::internal::ParserBase< Impl >::ParseClassLiteralBody().
has_seen_constructor
template<typename Impl >
bool v8::internal::ParserBase< Impl >::ClassInfo::has_seen_constructor = false
Definition at line 666 of file parser-base.h.
Referenced by v8::internal::ParserBase< Impl >::ParseClassLiteralBody(), and v8::internal::ParserBase< Impl >::ParseClassPropertyDefinition().
has_static_blocks
template<typename Impl >
bool v8::internal::ParserBase< Impl >::ClassInfo::has_static_blocks
Definition at line 669 of file parser-base.h.
has_static_computed_names
template<typename Impl >
bool v8::internal::ParserBase< Impl >::ClassInfo::has_static_computed_names
Definition at line 667 of file parser-base.h.
Referenced by v8::internal::ParserBase< Impl >::ParseClassLiteralBody().
has_static_private_methods_or_accessors
template<typename Impl >
bool v8::internal::ParserBase< Impl >::ClassInfo::has_static_private_methods_or_accessors
Definition at line 668 of file parser-base.h.
Referenced by v8::internal::ParserBase< Impl >::ParseClassLiteralBody().
home_object_variable
template<typename Impl >
Variable* v8::internal::ParserBase< Impl >::ClassInfo::home_object_variable = nullptr
Definition at line 660 of file parser-base.h.
Referenced by v8::internal::ParserBase< Impl >::ParseClassLiteral().
instance_fields
template<typename Impl >
ClassPropertyListT v8::internal::ParserBase< Impl >::ClassInfo::instance_fields
Definition at line 618 of file parser-base.h.
instance_members_function_id
template<typename Impl >
int v8::internal::ParserBase< Impl >::ClassInfo::instance_members_function_id = -1
Definition at line 664 of file parser-base.h.
Referenced by v8::internal::ParserBase< Impl >::ClassInfo::EnsureInstanceMembersScope().
instance_members_scope
template<typename Impl >
DeclarationScope* v8::internal::ParserBase< Impl >::ClassInfo::instance_members_scope = nullptr
Definition at line 659 of file parser-base.h.
Referenced by v8::internal::ParserBase< Impl >::ClassInfo::EnsureInstanceMembersScope(), and v8::internal::ParserBase< Impl >::ClassInfo::has_instance_members().
is_anonymous
template<typename Impl >
bool v8::internal::ParserBase< Impl >::ClassInfo::is_anonymous
Definition at line 671 of file parser-base.h.
Referenced by v8::internal::ParserBase< Impl >::ParseClassLiteral().
private_members
template<typename Impl >
ClassPropertyListT v8::internal::ParserBase< Impl >::ClassInfo::private_members
Definition at line 616 of file parser-base.h.
public_members
template<typename Impl >
ClassPropertyListT v8::internal::ParserBase< Impl >::ClassInfo::public_members
Definition at line 615 of file parser-base.h.
requires_brand
template<typename Impl >
bool v8::internal::ParserBase< Impl >::ClassInfo::requires_brand
Definition at line 670 of file parser-base.h.
Referenced by v8::internal::ParserBase< Impl >::ParseClassLiteral(), and v8::internal::ParserBase< Impl >::ParseClassLiteralBody().
static_elements
template<typename Impl >
ClassStaticElementListT v8::internal::ParserBase< Impl >::ClassInfo::static_elements
Definition at line 617 of file parser-base.h.
static_elements_function_id
template<typename Impl >
int v8::internal::ParserBase< Impl >::ClassInfo::static_elements_function_id = -1
Definition at line 663 of file parser-base.h.
Referenced by v8::internal::ParserBase< Impl >::ClassInfo::EnsureStaticElementsScope().
static_elements_scope
template<typename Impl >
DeclarationScope* v8::internal::ParserBase< Impl >::ClassInfo::static_elements_scope = nullptr
Definition at line 658 of file parser-base.h.
Referenced by v8::internal::ParserBase< Impl >::ClassInfo::EnsureStaticElementsScope(), and v8::internal::ParserBase< Impl >::ClassInfo::has_static_elements().
static_home_object_variable
template<typename Impl >
Variable* v8::internal::ParserBase< Impl >::ClassInfo::static_home_object_variable = nullptr
Definition at line 661 of file parser-base.h.
Referenced by v8::internal::ParserBase< Impl >::ParseClassLiteral().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/parsing/parser-base.h