v8::internal::SourceRange Struct Reference
#include <ast-source-ranges.h>
Public Member Functions
SourceRange ()
SourceRange (int start, int end)
bool IsEmpty () const
Static Public Member Functions
static SourceRange Empty ()
static SourceRange OpenEnded (int32_t start)
static SourceRange ContinuationOf (const SourceRange &that, int end=kNoSourcePosition)
static SourceRange FunctionLiteralMarkerRange ()
Public Attributes
int32_t start
int32_t end
Static Public Attributes
static constexpr int kFunctionLiteralSourcePosition = -2
Detailed Description
Definition at line 16 of file ast-source-ranges.h.
Constructor & Destructor Documentation
SourceRange() [1/2]
v8::internal::SourceRange::SourceRange () [inline]
Definition at line 17 of file ast-source-ranges.h.
: SourceRange(kNoSourcePosition, kNoSourcePosition) {}
Referenced by ContinuationOf(), Empty(), and OpenEnded().
SourceRange() [2/2]
v8::internal::SourceRange::SourceRange (int start, int end) [inline]
Definition at line 18 of file ast-source-ranges.h.
: start(start), end(end) {}
Member Function Documentation
ContinuationOf()
static SourceRange v8::internal::SourceRange::ContinuationOf (const SourceRange & that, int end = kNoSourcePosition) [inline], [static]
Definition at line 24 of file ast-source-ranges.h.
                                                                 {
    return that.IsEmpty() ? Empty() : SourceRange(that.end, end);
  }
References Empty(), end, IsEmpty(), and SourceRange().
Referenced by v8::internal::IfStatementSourceRanges::GetRange(), v8::internal::IterationStatementSourceRanges::GetRange(), v8::internal::TryCatchStatementSourceRanges::GetRange(), v8::internal::TryFinallyStatementSourceRanges::GetRange(), and v8::internal::ParserBase< Impl >::ParseIfStatement().
Empty()
static SourceRange v8::internal::SourceRange::Empty () [inline], [static]
Definition at line 20 of file ast-source-ranges.h.
{ return SourceRange(); }
References SourceRange().
Referenced by ContinuationOf(), v8::internal::IfStatementSourceRanges::GetRange(), v8::internal::IterationStatementSourceRanges::GetRange(), v8::internal::TryCatchStatementSourceRanges::GetRange(), and v8::internal::TryFinallyStatementSourceRanges::GetRange().
FunctionLiteralMarkerRange()
static SourceRange v8::internal::SourceRange::FunctionLiteralMarkerRange () [inline], [static]
Definition at line 36 of file ast-source-ranges.h.
                                                  {
    return {kFunctionLiteralSourcePosition, kFunctionLiteralSourcePosition};
  }
References kFunctionLiteralSourcePosition.
Referenced by v8::internal::FunctionLiteralSourceRanges::GetRange().
IsEmpty()
bool v8::internal::SourceRange::IsEmpty () const [inline]
Definition at line 19 of file ast-source-ranges.h.
{ return start == kNoSourcePosition; }
References v8::internal::kNoSourcePosition, and start.
Referenced by v8::internal::interpreter::BlockCoverageBuilder::AllocateBlockCoverageSlot(), v8::internal::interpreter::BlockCoverageBuilder::AllocateConditionalChainBlockCoverageSlot(), v8::internal::interpreter::BlockCoverageBuilder::AllocateNaryBlockCoverageSlot(), ContinuationOf(), and v8::internal::IfStatementSourceRanges::GetRange().
OpenEnded()
static SourceRange v8::internal::SourceRange::OpenEnded (int32_t start) [inline], [static]
Definition at line 21 of file ast-source-ranges.h.
                                              {
    return SourceRange(start, kNoSourcePosition);
  }
References v8::internal::kNoSourcePosition, SourceRange(), and start.
Referenced by v8::internal::ContinuationSourceRanges::GetRange().
Member Data Documentation
end
int32_t v8::internal::SourceRange::end
Definition at line 40 of file ast-source-ranges.h.
Referenced by ContinuationOf(), and v8::internal::FactoryBase< Impl >::NewCoverageInfo().
kFunctionLiteralSourcePosition
constexpr int v8::internal::SourceRange::kFunctionLiteralSourcePosition = -2 [static], [constexpr]
Definition at line 29 of file ast-source-ranges.h.
Referenced by FunctionLiteralMarkerRange(), and v8::internal::anonymous_namespace{debug-coverage.cc}::RewriteFunctionScopeCounter().
start
int32_t v8::internal::SourceRange::start
Definition at line 40 of file ast-source-ranges.h.
Referenced by IsEmpty(), v8::internal::FactoryBase< Impl >::NewCoverageInfo(), OpenEnded(), and v8::internal::SourceRangeAstVisitor::VisitNode().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/ast/ast-source-ranges.h