v8::internal::compiler::turboshaft::ReturnOp Struct Reference
#include <operations.h>
Public Member Functions
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
V< Word32 > pop_count () const
base::Vector< const OpIndex > return_values () const
ReturnOp (V< Word32 > pop_count, base::Vector< const OpIndex > return_values, bool spill_caller_frame_slots)
template<typename Fn , typename Mapper >
auto Explode (Fn fn, Mapper &mapper) const
auto options () const
Static Public Member Functions
static ReturnOp & New (Graph *graph, V< Word32 > pop_count, base::Vector< const OpIndex > return_values, bool spill_caller_frame_slots)
Public Attributes
bool spill_caller_frame_slots
Static Public Attributes
static constexpr OpEffects effects = OpEffects().CanLeaveCurrentFunction()
Additional Inherited Members
Detailed Description
Definition at line 4355 of file operations.h.
Constructor & Destructor Documentation
ReturnOp()
v8::internal::compiler::turboshaft::ReturnOp::ReturnOp (V< Word32 > pop_count, base::Vector< const OpIndex > return_values, bool spill_caller_frame_slots) [inline]
Definition at line 4378 of file operations.h.
      : Base(1 + return_values.size()),
        spill_caller_frame_slots(spill_caller_frame_slots) {
    base::Vector<OpIndex> inputs = this->inputs();
    inputs[0] = pop_count;
    inputs.SubVector(1, inputs.size()).OverwriteWith(return_values);
  }
References v8::base::Vector< T >::size(), and v8::base::Vector< T >::SubVector().
Member Function Documentation
Explode()
template<typename Fn , typename Mapper >
auto v8::internal::compiler::turboshaft::ReturnOp::Explode (Fn fn, Mapper & mapper) const [inline]
Definition at line 4388 of file operations.h.
                                                      {
    OpIndex mapped_pop_count = mapper.Map(pop_count());
    auto mapped_return_values = mapper.template Map<4>(return_values());
    return fn(mapped_pop_count, base::VectorOf(mapped_return_values),
              spill_caller_frame_slots);
  }
References v8::base::VectorOf().
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::ReturnOp::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 4364 of file operations.h.
                                                              {
    // TODO(mliedtke): Ideally, a return op would expect to get the correct
    // types for all its return values, not just the pop count.
    return MaybeRepVector<MaybeRegisterRepresentation::Word32()>();
  }
New()
static ReturnOp& v8::internal::compiler::turboshaft::ReturnOp::New (Graph * graph, V< Word32 > pop_count, base::Vector< const OpIndex > return_values, bool spill_caller_frame_slots) [inline], [static]
Definition at line 4395 of file operations.h.
                                                      {
    return Base::New(graph, 1 + return_values.size(), pop_count, return_values,
                     spill_caller_frame_slots);
  }
References graph(), v8::internal::anonymous_namespace{intl-objects.cc}::New(), and v8::base::Vector< T >::size().
options()
auto v8::internal::compiler::turboshaft::ReturnOp::options () const [inline]
Definition at line 4401 of file operations.h.
{ return std::tuple{spill_caller_frame_slots}; }
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::ReturnOp::outputs_rep () const [inline]
Definition at line 4362 of file operations.h.
{ return {}; }
pop_count()
V<Word32> v8::internal::compiler::turboshaft::ReturnOp::pop_count () const [inline]
Definition at line 4372 of file operations.h.
{ return input<Word32>(0); }
Referenced by v8::internal::compiler::InstructionSelector::VisitReturn().
return_values()
base::Vector<const OpIndex> v8::internal::compiler::turboshaft::ReturnOp::return_values () const [inline]
Definition at line 4374 of file operations.h.
                                                  {
    return inputs().SubVector(1, input_count);
  }
References v8::internal::compiler::turboshaft::detail::input_count().
Referenced by v8::internal::compiler::InstructionSelector::VisitReturn().
Member Data Documentation
effects
constexpr OpEffects v8::internal::compiler::turboshaft::ReturnOp::effects = OpEffects().CanLeaveCurrentFunction() [static], [constexpr]
Definition at line 4361 of file operations.h.
spill_caller_frame_slots
bool v8::internal::compiler::turboshaft::ReturnOp::spill_caller_frame_slots
Definition at line 4360 of file operations.h.
Referenced by v8::internal::compiler::InstructionSelector::VisitReturn().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h