v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::GapMoveTargets Struct Reference
Public Member Functions
GapMoveTargets ()=default
GapMoveTargets (GapMoveTargets &&) V8_NOEXCEPT=default
GapMoveTargets & operator= (GapMoveTargets &&) V8_NOEXCEPT=default
GapMoveTargets (const GapMoveTargets &)=delete
GapMoveTargets & operator= (const GapMoveTargets &)=delete
bool is_empty () const
Public Attributes
base::SmallVector< int32_t, 1 > stack_slots = base::SmallVector<int32_t, 1>{}
RegListBase< RegisterT > registers
V8_NO_UNIQUE_ADDRESS std::conditional_t< DecompressIfNeeded, NeedsDecompression, DummyNeedsDecompression > needs_decompression = kDoesNotNeedDecompression
Detailed Description
template<typename RegisterT, bool DecompressIfNeeded>
struct v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::GapMoveTargets
Definition at line 166 of file maglev-code-generator.cc.
Constructor & Destructor Documentation
GapMoveTargets() [1/3]
template<typename RegisterT , bool DecompressIfNeeded>
v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::GapMoveTargets::GapMoveTargets () [default]
GapMoveTargets() [2/3]
template<typename RegisterT , bool DecompressIfNeeded>
v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::GapMoveTargets::GapMoveTargets (GapMoveTargets &&) [default]
GapMoveTargets() [3/3]
template<typename RegisterT , bool DecompressIfNeeded>
v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::GapMoveTargets::GapMoveTargets (const GapMoveTargets &) [delete]
Member Function Documentation
is_empty()
template<typename RegisterT , bool DecompressIfNeeded>
bool v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::GapMoveTargets::is_empty () const [inline]
Definition at line 183 of file maglev-code-generator.cc.
                          {
      return registers.is_empty() && stack_slots.empty();
    }
References v8::base::SmallVector< T, kSize, Allocator >::empty(), and v8::internal::RegListBase< RegisterT >::is_empty().
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::ContinueEmitMoveChain(), and v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::StartEmitMoveChain().
operator=() [1/2]
template<typename RegisterT , bool DecompressIfNeeded>
GapMoveTargets& v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::GapMoveTargets::operator= (const GapMoveTargets &) [delete]
operator=() [2/2]
template<typename RegisterT , bool DecompressIfNeeded>
GapMoveTargets& v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::GapMoveTargets::operator= (GapMoveTargets &&) [default]
Member Data Documentation
needs_decompression
template<typename RegisterT , bool DecompressIfNeeded>
V8_NO_UNIQUE_ADDRESS std::conditional_t<DecompressIfNeeded, NeedsDecompression, DummyNeedsDecompression> v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::GapMoveTargets::needs_decompression = kDoesNotNeedDecompression
Definition at line 175 of file maglev-code-generator.cc.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::RecordMoveToRegister(), and v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::RecordMoveToStackSlot().
registers
template<typename RegisterT , bool DecompressIfNeeded>
RegListBase<RegisterT> v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::GapMoveTargets::registers
Definition at line 168 of file maglev-code-generator.cc.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::RecordMoveToRegister(), and v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::RecursivelyEmitMoveChainTargets().
stack_slots
template<typename RegisterT , bool DecompressIfNeeded>
base::SmallVector<int32_t, 1> v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::GapMoveTargets::stack_slots = base::SmallVector<int32_t, 1>{}
Definition at line 167 of file maglev-code-generator.cc.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::RecordMoveToStackSlot(), and v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::RecursivelyEmitMoveChainTargets().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-code-generator.cc