v8::internal::compiler::anonymous_namespace{jump-threading.cc}::JumpThreadingState Struct Reference
Public Member Functions
void Clear (size_t count)
void PushIfUnvisited (RpoNumber num)
void Forward (RpoNumber to)
RpoNumber unvisited ()
RpoNumber onstack ()
Public Attributes
bool forwarded
ZoneVector< RpoNumber > & result
ZoneStack< RpoNumber > & stack
Detailed Description
Definition at line 19 of file jump-threading.cc.
Member Function Documentation
Clear()
void v8::internal::compiler::anonymous_namespace{jump-threading.cc}::JumpThreadingState::Clear (size_t count) [inline]
Definition at line 24 of file jump-threading.cc.
{ result.assign(count, unvisited()); }
References v8::base::internal::result.
Forward()
void v8::internal::compiler::anonymous_namespace{jump-threading.cc}::JumpThreadingState::Forward (RpoNumber to) [inline]
Definition at line 31 of file jump-threading.cc.
                             {
    RpoNumber from = stack.top();
    RpoNumber to_to = result[to.ToInt()];
    bool pop = true;
    if (to == from) {
      TRACE(" xx %d\n", from.ToInt());
      result[from.ToInt()] = from;
    } else if (to_to == unvisited()) {
      TRACE(" fw %d -> %d (recurse)\n", from.ToInt(), to.ToInt());
      stack.push(to);
      result[to.ToInt()] = onstack();
      pop = false; // recurse.
    } else if (to_to == onstack()) {
      TRACE(" fw %d -> %d (cycle)\n", from.ToInt(), to.ToInt());
      result[from.ToInt()] = to; // break the cycle.
      forwarded = true;
    } else {
      TRACE(" fw %d -> %d (forward)\n", from.ToInt(), to.ToInt());
      result[from.ToInt()] = to_to; // forward the block.
      forwarded = true;
    }
    if (pop) stack.pop();
  }
References v8::base::internal::result, v8::internal::stack, v8::internal::compiler::RpoNumber::ToInt(), and v8::internal::TRACE().
onstack()
RpoNumber v8::internal::compiler::anonymous_namespace{jump-threading.cc}::JumpThreadingState::onstack () [inline]
Definition at line 55 of file jump-threading.cc.
{ return RpoNumber::FromInt(-2); }
References v8::internal::compiler::RpoNumber::FromInt().
PushIfUnvisited()
void v8::internal::compiler::anonymous_namespace{jump-threading.cc}::JumpThreadingState::PushIfUnvisited (RpoNumber num) [inline]
Definition at line 25 of file jump-threading.cc.
                                      {
    if (result[num.ToInt()] == unvisited()) {
      stack.push(num);
      result[num.ToInt()] = onstack();
    }
  }
References v8::base::internal::result, v8::internal::stack, and v8::internal::compiler::RpoNumber::ToInt().
unvisited()
RpoNumber v8::internal::compiler::anonymous_namespace{jump-threading.cc}::JumpThreadingState::unvisited () [inline]
Definition at line 54 of file jump-threading.cc.
{ return RpoNumber::FromInt(-1); }
References v8::internal::compiler::RpoNumber::FromInt().
Member Data Documentation
forwarded
bool v8::internal::compiler::anonymous_namespace{jump-threading.cc}::JumpThreadingState::forwarded
Definition at line 20 of file jump-threading.cc.
result
ZoneVector<RpoNumber>& v8::internal::compiler::anonymous_namespace{jump-threading.cc}::JumpThreadingState::result
Definition at line 21 of file jump-threading.cc.
stack
ZoneStack<RpoNumber>& v8::internal::compiler::anonymous_namespace{jump-threading.cc}::JumpThreadingState::stack
Definition at line 22 of file jump-threading.cc.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/jump-threading.cc