v8::internal::compiler::turboshaft::ConstantOp Struct Reference
#include <operations.h>
Classes
union Storage
Public Types
enum class Kind : uint8_t {
kWord32
, kWord64
, kFloat32
, kFloat64
,
kSmi
, kNumber
, kTaggedIndex
, kExternal
,
kHeapObject
, kCompressedHeapObject
, kTrustedHeapObject
, kRelocatableWasmCall
,
kRelocatableWasmStubCall
, kRelocatableWasmIndirectCallTarget
, kRelocatableWasmCanonicalSignatureId
 }
Public Member Functions
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &) const
ConstantOp (Kind kind, Storage storage)
void Validate (const Graph &graph) const
uint64_t integral () const
int64_t signed_integral () const
uint32_t word32 () const
uint64_t word64 () const
i::Tagged< Smi > smi () const
i::Float64 number () const
i::Float32 float32 () const
i::Float64 float64 () const
int32_t tagged_index () const
ExternalReference external_reference () const
IndirectHandle< i::HeapObject > handle () const
bool IsWord (uint64_t value) const
bool IsIntegral () const
auto options () const
void PrintOptions (std::ostream &os) const
size_t hash_value (HashingStrategy strategy=HashingStrategy::kDefault) const
bool operator== (const ConstantOp &other) const
Static Public Member Functions
static RegisterRepresentation Representation (Kind kind)
Public Attributes
Kind kind
RegisterRepresentation rep = Representation(kind)
union v8::internal::compiler::turboshaft::ConstantOp::Storage storage
Static Public Attributes
static constexpr OpEffects effects = OpEffects()
Additional Inherited Members
Detailed Description
Definition at line 2597 of file operations.h.
Member Enumeration Documentation
Kind
enum v8::internal::compiler::turboshaft::ConstantOp::Kind : uint8_t [strong]
Enumerator
kWord32
kWord64
kFloat32
kFloat64
kSmi
kNumber
kTaggedIndex
kExternal
kHeapObject
kCompressedHeapObject
kTrustedHeapObject
kRelocatableWasmCall
kRelocatableWasmStubCall
kRelocatableWasmIndirectCallTarget
kRelocatableWasmCanonicalSignatureId
Definition at line 2598 of file operations.h.
                  : uint8_t {
    kWord32,
    kWord64,
    kFloat32,
    kFloat64,
    kSmi,
    kNumber, // TODO(tebbi): See if we can avoid number constants.
    kTaggedIndex,
    kExternal,
    kHeapObject,
    kCompressedHeapObject,
    kTrustedHeapObject,
    kRelocatableWasmCall,
    kRelocatableWasmStubCall,
    kRelocatableWasmIndirectCallTarget,
    kRelocatableWasmCanonicalSignatureId
  };
Constructor & Destructor Documentation
ConstantOp()
v8::internal::compiler::turboshaft::ConstantOp::ConstantOp (Kind kind, Storage storage) [inline]
Definition at line 2677 of file operations.h.
      : Base(), kind(kind), storage(storage) {}
Member Function Documentation
external_reference()
ExternalReference v8::internal::compiler::turboshaft::ConstantOp::external_reference () const [inline]
Definition at line 2742 of file operations.h.
                                               {
    DCHECK_EQ(kind, Kind::kExternal);
    return storage.external;
  }
References DCHECK_EQ.
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitLoad(), and PrintOptions().
float32()
i::Float32 v8::internal::compiler::turboshaft::ConstantOp::float32 () const [inline]
Definition at line 2727 of file operations.h.
                           {
    DCHECK_EQ(kind, Kind::kFloat32);
    return storage.float32;
  }
References DCHECK_EQ.
Referenced by v8::internal::compiler::turboshaft::OperationMatcher::MatchZero(), and PrintOptions().
float64()
i::Float64 v8::internal::compiler::turboshaft::ConstantOp::float64 () const [inline]
Definition at line 2732 of file operations.h.
                           {
    DCHECK_EQ(kind, Kind::kFloat64);
    return storage.float64;
  }
References DCHECK_EQ.
Referenced by v8::internal::compiler::turboshaft::OperationMatcher::MatchZero(), PrintOptions(), and v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessConstant().
handle()
IndirectHandle<i::HeapObject> v8::internal::compiler::turboshaft::ConstantOp::handle () const [inline]
Definition at line 2747 of file operations.h.
                                             {
    DCHECK(kind == Kind::kHeapObject || kind == Kind::kCompressedHeapObject ||
           kind == Kind::kTrustedHeapObject);
    return storage.handle;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::compiler::CanBeImmediate(), v8::internal::compiler::Arm64OperandGenerator::CanBeImmediate(), v8::internal::compiler::PPCOperandGenerator::CanBeImmediate(), v8::internal::compiler::Loong64OperandGenerator::CanBeImmediate(), v8::internal::compiler::RiscvOperandGenerator::CanBeImmediate(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::GetStringEncoding(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Load(), v8::internal::compiler::turboshaft::OperationMatcher::MatchHeapConstant(), PrintOptions(), v8::internal::compiler::turboshaft::RedundantStoreAnalysis::ProcessBlock(), and v8::internal::compiler::turboshaft::TryGetBuiltinId().
hash_value()
size_t v8::internal::compiler::turboshaft::ConstantOp::hash_value (HashingStrategy strategy = HashingStrategy::kDefault) const [inline]
Definition at line 2775 of file operations.h.
                                                                {
    switch (kind) {
      case Kind::kWord32:
      case Kind::kWord64:
      case Kind::kSmi:
      case Kind::kTaggedIndex:
      case Kind::kRelocatableWasmCall:
      case Kind::kRelocatableWasmStubCall:
      case Kind::kRelocatableWasmIndirectCallTarget:
      case Kind::kRelocatableWasmCanonicalSignatureId:
        return HashWithOptions(storage.integral);
      case Kind::kFloat32:
        return HashWithOptions(storage.float32.get_bits());
      case Kind::kFloat64:
      case Kind::kNumber:
        return HashWithOptions(storage.float64.get_bits());
      case Kind::kExternal:
        return HashWithOptions(strategy == HashingStrategy::kMakeSnapshotStable
                                   ? 0
                                   : storage.external.raw());
      case Kind::kHeapObject:
      case Kind::kCompressedHeapObject:
      case Kind::kTrustedHeapObject:
        if (strategy == HashingStrategy::kMakeSnapshotStable) {
          return HashWithOptions();
        }
        return HashWithOptions(storage.handle.address());
    }
  }
References v8::internal::compiler::kSmi.
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::ConstantOp::inputs_rep (ZoneVector< MaybeRegisterRepresentation > &) const [inline]
Definition at line 2644 of file operations.h.
                                                      {
    return {};
  }
integral()
uint64_t v8::internal::compiler::turboshaft::ConstantOp::integral () const [inline]
Definition at line 2689 of file operations.h.
                            {
    DCHECK(IsIntegral());
    return storage.integral;
  }
References v8::internal::DCHECK(), and v8::internal::IsIntegral().
Referenced by v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralWordConstant(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::MatchScaledIndex(), v8::internal::compiler::MatchScaledIndex(), v8::internal::compiler::turboshaft::OperationMatcher::MatchWasmStubCallConstant(), and v8::internal::compiler::turboshaft::OperationMatcher::MatchZero().
IsIntegral()
bool v8::internal::compiler::turboshaft::ConstantOp::IsIntegral () const [inline]
Definition at line 2764 of file operations.h.
                          {
    return kind == Kind::kWord32 || kind == Kind::kWord64 ||
           kind == Kind::kRelocatableWasmCall ||
           kind == Kind::kRelocatableWasmStubCall ||
           kind == Kind::kRelocatableWasmCanonicalSignatureId ||
           kind == Kind::kRelocatableWasmIndirectCallTarget;
  }
Referenced by v8::internal::compiler::turboshaft::LoadStoreSimplificationReducer< Next >::Store(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryAdjustIndex(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryAdjustOffset().
IsWord()
bool v8::internal::compiler::turboshaft::ConstantOp::IsWord (uint64_t value) const [inline]
Definition at line 2753 of file operations.h.
                                    {
    switch (kind) {
      case Kind::kWord32:
        return static_cast<uint32_t>(value) == word32();
      case Kind::kWord64:
        return value == word64();
      default:
        UNREACHABLE();
    }
  }
References v8::internal::UNREACHABLE(), and v8::internal::value.
number()
i::Float64 v8::internal::compiler::turboshaft::ConstantOp::number () const [inline]
Definition at line 2722 of file operations.h.
                          {
    DCHECK_EQ(kind, Kind::kNumber);
    return storage.float64;
  }
References DCHECK_EQ.
Referenced by v8::internal::compiler::CanBeImmediate(), v8::internal::compiler::GetImmediateIntegerValue(), v8::internal::compiler::IA32OperandGenerator::GetImmediateIntegerValue(), PrintOptions(), and v8::internal::compiler::InstructionSelector::VisitNode().
operator==()
bool v8::internal::compiler::turboshaft::ConstantOp::operator== (const ConstantOp & other) const [inline]
Definition at line 2805 of file operations.h.
                                                 {
    if (kind != other.kind) return false;
    switch (kind) {
      case Kind::kWord32:
      case Kind::kWord64:
      case Kind::kSmi:
      case Kind::kTaggedIndex:
      case Kind::kRelocatableWasmCall:
      case Kind::kRelocatableWasmStubCall:
      case Kind::kRelocatableWasmCanonicalSignatureId:
      case Kind::kRelocatableWasmIndirectCallTarget:
        return storage.integral == other.storage.integral;
      case Kind::kFloat32:
        // Using a bit_cast to uint32_t in order to return false when comparing
        // +0 and -0.
        // Note: for JavaScript, it would be fine to return true when both
        // values are NaNs, but for Wasm we must not merge NaNs that way.
        // Since we canonicalize NaNs for JS anyway, we don't need to treat
        // them specially here.
        return base::bit_cast<uint32_t>(storage.float32) ==
               base::bit_cast<uint32_t>(other.storage.float32);
      case Kind::kFloat64:
      case Kind::kNumber:
        // Using a bit_cast to uint64_t in order to return false when comparing
        // +0 and -0.
        // Note: for JavaScript, it would be fine to return true when both
        // values are NaNs, but for Wasm we must not merge NaNs that way.
        // Since we canonicalize NaNs for JS anyway, we don't need to treat
        // them specially here.
        return base::bit_cast<uint64_t>(storage.float64) ==
               base::bit_cast<uint64_t>(other.storage.float64);
      case Kind::kExternal:
        return storage.external.raw() == other.storage.external.raw();
      case Kind::kHeapObject:
      case Kind::kCompressedHeapObject:
      case Kind::kTrustedHeapObject:
        return storage.handle.address() == other.storage.handle.address();
    }
  }
References v8::internal::compiler::turboshaft::ConstantOp::Storage::external, v8::internal::compiler::turboshaft::ConstantOp::Storage::float32, v8::internal::compiler::turboshaft::ConstantOp::Storage::float64, v8::internal::compiler::turboshaft::ConstantOp::Storage::handle, v8::internal::compiler::turboshaft::ConstantOp::Storage::integral, kind, v8::internal::compiler::kSmi, v8::internal::ExternalReference::raw(), and storage.
options()
auto v8::internal::compiler::turboshaft::ConstantOp::options () const [inline]
Definition at line 2772 of file operations.h.
{ return std::tuple{kind, storage}; }
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::ConstantOp::outputs_rep () const [inline]
Definition at line 2640 of file operations.h.
                                                               {
    return base::VectorOf(&rep, 1);
  }
References v8::base::VectorOf().
PrintOptions()
void v8::internal::compiler::turboshaft::ConstantOp::PrintOptions (std::ostream & os) const
Definition at line 532 of file operations.cc.
                                                  {
  os << '[';
  switch (kind) {
    case Kind::kWord32:
      os << "word32: " << static_cast<int32_t>(storage.integral);
      break;
    case Kind::kWord64:
      os << "word64: " << static_cast<int64_t>(storage.integral);
      break;
    case Kind::kSmi:
      os << "smi: " << smi();
      break;
    case Kind::kNumber:
      os << "number: " << number().get_scalar();
      break;
    case Kind::kTaggedIndex:
      os << "tagged index: " << tagged_index();
      break;
    case Kind::kFloat64:
      os << "float64: " << float64().get_scalar();
      if (float64().is_hole_nan()) {
        os << " (hole nan: 0x" << std::hex << float64().get_bits() << std::dec
           << ')';
      } else if (float64().is_nan()) {
        os << " (0x" << std::hex << float64().get_bits() << std::dec << ')';
      }
      break;
    case Kind::kFloat32:
      os << "float32: " << float32().get_scalar();
      if (float32().is_nan()) {
        os << " (0x" << std::hex << base::bit_cast<uint32_t>(storage.float32)
           << std::dec << ')';
      }
      break;
    case Kind::kExternal:
      os << "external: " << external_reference();
      break;
    case Kind::kHeapObject:
      os << "heap object: " << JSONEscaped(handle());
      break;
    case Kind::kCompressedHeapObject:
      os << "compressed heap object: " << JSONEscaped(handle());
      break;
    case Kind::kTrustedHeapObject:
      os << "trusted heap object: " << JSONEscaped(handle());
      break;
    case Kind::kRelocatableWasmCall:
      os << "relocatable wasm call: 0x"
         << reinterpret_cast<void*>(storage.integral);
      break;
    case Kind::kRelocatableWasmStubCall:
      os << "relocatable wasm stub call: 0x"
         << reinterpret_cast<void*>(storage.integral);
      break;
    case Kind::kRelocatableWasmCanonicalSignatureId:
      os << "relocatable wasm canonical signature ID: "
         << static_cast<int32_t>(storage.integral);
      break;
    case Kind::kRelocatableWasmIndirectCallTarget:
      os << "relocatable wasm indirect call target: "
         << static_cast<uint32_t>(storage.integral);
      break;
  }
  os << ']';
}
References external_reference(), v8::internal::compiler::turboshaft::ConstantOp::Storage::float32, float32(), float64(), v8::internal::Float64::get_bits(), v8::internal::Float32::get_scalar(), v8::internal::Float64::get_scalar(), handle(), v8::internal::compiler::turboshaft::ConstantOp::Storage::integral, kCompressedHeapObject, kExternal, kFloat32, kFloat64, kHeapObject, kind, kNumber, kRelocatableWasmCall, kRelocatableWasmCanonicalSignatureId, kRelocatableWasmIndirectCallTarget, kRelocatableWasmStubCall, kSmi, kTaggedIndex, kTrustedHeapObject, kWord32, kWord64, number(), smi(), storage, and tagged_index().
Representation()
static RegisterRepresentation v8::internal::compiler::turboshaft::ConstantOp::Representation (Kind kind) [inline], [static]
Definition at line 2649 of file operations.h.
                                                          {
    switch (kind) {
      case Kind::kRelocatableWasmCanonicalSignatureId:
      case Kind::kWord32:
        return RegisterRepresentation::Word32();
      case Kind::kWord64:
        return RegisterRepresentation::Word64();
      case Kind::kFloat32:
        return RegisterRepresentation::Float32();
      case Kind::kFloat64:
        return RegisterRepresentation::Float64();
      case Kind::kExternal:
      case Kind::kTaggedIndex:
      case Kind::kTrustedHeapObject:
      case Kind::kRelocatableWasmCall:
      case Kind::kRelocatableWasmStubCall:
        return RegisterRepresentation::WordPtr();
      case Kind::kRelocatableWasmIndirectCallTarget:
        return RegisterRepresentation::Word32();
      case Kind::kSmi:
      case Kind::kHeapObject:
      case Kind::kNumber:
        return RegisterRepresentation::Tagged();
      case Kind::kCompressedHeapObject:
        return RegisterRepresentation::Compressed();
    }
  }
References v8::internal::compiler::turboshaft::RegisterRepresentation::Compressed(), v8::internal::compiler::turboshaft::RegisterRepresentation::Float32(), v8::internal::compiler::turboshaft::RegisterRepresentation::Float64(), v8::internal::compiler::kSmi, v8::internal::compiler::turboshaft::RegisterRepresentation::Tagged(), v8::internal::compiler::turboshaft::RegisterRepresentation::Word32(), v8::internal::compiler::turboshaft::RegisterRepresentation::Word64(), and v8::internal::compiler::turboshaft::RegisterRepresentation::WordPtr().
signed_integral()
int64_t v8::internal::compiler::turboshaft::ConstantOp::signed_integral () const [inline]
Definition at line 2694 of file operations.h.
                                  {
    DCHECK(IsIntegral());
    switch (kind) {
      case Kind::kWord32:
      case Kind::kRelocatableWasmCanonicalSignatureId:
        return static_cast<int32_t>(storage.integral);
      case Kind::kWord64:
        return static_cast<int64_t>(storage.integral);
      default:
        UNREACHABLE();
    }
  }
References v8::internal::DCHECK(), v8::internal::IsIntegral(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralWordConstant(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryAdjustIndex(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryAdjustOffset().
smi()
i::Tagged<Smi> v8::internal::compiler::turboshaft::ConstantOp::smi () const [inline]
Definition at line 2717 of file operations.h.
                           {
    DCHECK_EQ(kind, Kind::kSmi);
    return i::Tagged<Smi>(storage.integral);
  }
References DCHECK_EQ, v8::internal::compiler::kSmi, and v8::internal::Tagged< Smi >.
Referenced by v8::internal::compiler::CanBeImmediate(), v8::internal::compiler::GetImmediateIntegerValue(), v8::internal::compiler::IA32OperandGenerator::GetImmediateIntegerValue(), v8::internal::compiler::turboshaft::OperationMatcher::MatchSmiZero(), v8::internal::compiler::turboshaft::OperationMatcher::MatchZero(), PrintOptions(), and v8::internal::compiler::OperandGenerator::ToNegatedConstant().
tagged_index()
int32_t v8::internal::compiler::turboshaft::ConstantOp::tagged_index () const [inline]
Definition at line 2737 of file operations.h.
                               {
    DCHECK_EQ(kind, Kind::kTaggedIndex);
    return static_cast<int32_t>(static_cast<uint32_t>(storage.integral));
  }
References DCHECK_EQ.
Referenced by PrintOptions().
Validate()
void v8::internal::compiler::turboshaft::ConstantOp::Validate (const Graph & graph) const [inline]
Definition at line 2680 of file operations.h.
                                          {
    DCHECK_IMPLIES(
        kind == Kind::kWord32,
        storage.integral <= WordRepresentation::Word32().MaxUnsignedValue());
    DCHECK_IMPLIES(
        kind == Kind::kRelocatableWasmCanonicalSignatureId,
        storage.integral <= WordRepresentation::Word32().MaxSignedValue());
  }
References DCHECK_IMPLIES, v8::internal::compiler::turboshaft::WordRepresentation::MaxSignedValue(), v8::internal::compiler::turboshaft::WordRepresentation::MaxUnsignedValue(), and v8::internal::compiler::turboshaft::WordRepresentation::Word32().
word32()
uint32_t v8::internal::compiler::turboshaft::ConstantOp::word32 () const [inline]
Definition at line 2707 of file operations.h.
                          {
    DCHECK(kind == Kind::kWord32 || kind == Kind::kWord64);
    return static_cast<uint32_t>(storage.integral);
  }
References v8::internal::DCHECK().
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::BoundsCheckMem(), v8::internal::compiler::CanBeImmediate(), v8::internal::compiler::S390OperandGenerator::GetImmediate(), v8::internal::compiler::GetImmediateIntegerValue(), v8::internal::compiler::IA32OperandGenerator::GetImmediateIntegerValue(), v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::OperandForDeopt(), v8::internal::compiler::turboshaft::IfElseCascadeToSwitchReducer< Next >::ReduceInputGraphBranch(), v8::internal::compiler::OperandGenerator::ToNegatedConstant(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::UndoWord32ToWord64Conversion().
word64()
uint64_t v8::internal::compiler::turboshaft::ConstantOp::word64 () const [inline]
Definition at line 2712 of file operations.h.
                          {
    DCHECK_EQ(kind, Kind::kWord64);
    return static_cast<uint64_t>(storage.integral);
  }
References DCHECK_EQ.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::BoundsCheckMem(), v8::internal::compiler::CanBeImmediate(), v8::internal::compiler::S390OperandGenerator::GetImmediate(), v8::internal::compiler::GetImmediateIntegerValue(), v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::OperandForDeopt(), v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::StoreLoadInfo(), and v8::internal::compiler::OperandGenerator::ToNegatedConstant().
Member Data Documentation
effects
constexpr OpEffects v8::internal::compiler::turboshaft::ConstantOp::effects = OpEffects() [static], [constexpr]
Definition at line 2639 of file operations.h.
kind
Kind v8::internal::compiler::turboshaft::ConstantOp::kind
Definition at line 2616 of file operations.h.
Referenced by v8::internal::compiler::CanBeImmediate(), v8::internal::compiler::Arm64OperandGenerator::CanBeImmediate(), v8::internal::compiler::PPCOperandGenerator::CanBeImmediate(), v8::internal::compiler::Loong64OperandGenerator::CanBeImmediate(), v8::internal::compiler::RiscvOperandGenerator::CanBeImmediate(), v8::internal::compiler::S390OperandGenerator::GetImmediate(), v8::internal::compiler::GetImmediateIntegerValue(), v8::internal::compiler::IA32OperandGenerator::GetImmediateIntegerValue(), v8::internal::compiler::InstructionSelector::IsExternalConstant(), v8::internal::compiler::InstructionSelector::IsHeapConstant(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::IsNodeUnsigned(), v8::internal::compiler::InstructionSelector::IsRelocatableWasmConstant(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Load(), v8::internal::compiler::turboshaft::OperationMatcher::MatchExternalConstant(), v8::internal::compiler::turboshaft::OperationMatcher::MatchFloat(), v8::internal::compiler::turboshaft::OperationMatcher::MatchFloat32Constant(), v8::internal::compiler::turboshaft::OperationMatcher::MatchFloat64Constant(), v8::internal::compiler::turboshaft::OperationMatcher::MatchHeapConstant(), v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralWordConstant(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::MatchScaledIndex(), v8::internal::compiler::MatchScaledIndex(), v8::internal::compiler::turboshaft::OperationMatcher::MatchSmiZero(), v8::internal::compiler::turboshaft::OperationMatcher::MatchWasmStubCallConstant(), v8::internal::compiler::turboshaft::OperationMatcher::MatchZero(), operator==(), PrintOptions(), v8::internal::compiler::turboshaft::RedundantStoreAnalysis::ProcessBlock(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessConstant(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessLoad(), v8::internal::compiler::turboshaft::RunDecompressionOptimization(), v8::internal::compiler::turboshaft::LoadStoreSimplificationReducer< Next >::Store(), v8::internal::compiler::OperandGenerator::ToNegatedConstant(), v8::internal::compiler::turboshaft::TryGetBuiltinId(), and v8::internal::compiler::InstructionSelector::VisitNode().
rep
RegisterRepresentation v8::internal::compiler::turboshaft::ConstantOp::rep = Representation(kind)
Definition at line 2617 of file operations.h.
Referenced by v8::internal::compiler::turboshaft::detail::ValueMatch< T, HasConstexpr >::matches(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryAdjustIndex(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryAdjustOffset().
storage
union v8::internal::compiler::turboshaft::ConstantOp::Storage v8::internal::compiler::turboshaft::ConstantOp::storage
Referenced by v8::internal::compiler::turboshaft::detail::ValueMatch< T, HasConstexpr >::matches(), v8::internal::compiler::turboshaft::OperationMatcher::MatchExternalConstant(), v8::internal::compiler::turboshaft::OperationMatcher::MatchFloat(), v8::internal::compiler::turboshaft::OperationMatcher::MatchFloat32Constant(), v8::internal::compiler::turboshaft::OperationMatcher::MatchFloat64Constant(), operator==(), PrintOptions(), and v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessConstant().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h
/mnt/V8SourceCode/src/compiler/turboshaft/operations.cc