v8::internal::compiler::LoopInfo Struct Reference
#include <bytecode-analysis.h>
Public Member Functions
LoopInfo (int parent_offset, int loop_start, int loop_end, int parameter_count, int register_count, Zone *zone)
int parent_offset () const
int loop_start () const
int loop_end () const
bool resumable () const
void mark_resumable ()
bool innermost () const
void mark_not_innermost ()
bool Contains (int offset) const
const ZoneVector< ResumeJumpTarget > & resume_jump_targets () const
void AddResumeTarget (const ResumeJumpTarget &target)
BytecodeLoopAssignments & assignments ()
const BytecodeLoopAssignments & assignments () const
Private Attributes
int parent_offset_
int loop_start_
int loop_end_
bool resumable_ = false
bool innermost_ = true
BytecodeLoopAssignments assignments_
ZoneVector< ResumeJumpTarget > resume_jump_targets_
Detailed Description
Definition at line 69 of file bytecode-analysis.h.
Constructor & Destructor Documentation
LoopInfo()
v8::internal::compiler::LoopInfo::LoopInfo (int parent_offset, int loop_start, int loop_end, int parameter_count, int register_count, Zone * zone) [inline]
Definition at line 71 of file bytecode-analysis.h.
      : parent_offset_(parent_offset),
        loop_start_(loop_start),
        loop_end_(loop_end),
        assignments_(parameter_count, register_count, zone),
        resume_jump_targets_(zone) {}
Member Function Documentation
AddResumeTarget()
void v8::internal::compiler::LoopInfo::AddResumeTarget (const ResumeJumpTarget & target) [inline]
Definition at line 94 of file bytecode-analysis.h.
                                                       {
    resume_jump_targets_.push_back(target);
  }
Referenced by v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::Analyze().
assignments() [1/2]
BytecodeLoopAssignments& v8::internal::compiler::LoopInfo::assignments () [inline]
Definition at line 98 of file bytecode-analysis.h.
{ return assignments_; }
Referenced by v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::Analyze(), v8::internal::compiler::BytecodeGraphBuilder::BuildLoopExitsUntilLoop(), v8::internal::compiler::BytecodeGraphBuilder::BuildLoopHeaderEnvironment(), and v8::internal::maglev::MergePointInterpreterFrameState::NewForLoop().
assignments() [2/2]
const BytecodeLoopAssignments& v8::internal::compiler::LoopInfo::assignments () const [inline]
Definition at line 99 of file bytecode-analysis.h.
{ return assignments_; }
Contains()
bool v8::internal::compiler::LoopInfo::Contains (int offset) const [inline]
Definition at line 87 of file bytecode-analysis.h.
                                  {
    return offset >= loop_start_ && offset < loop_end_;
  }
innermost()
bool v8::internal::compiler::LoopInfo::innermost () const [inline]
Definition at line 84 of file bytecode-analysis.h.
{ return innermost_; }
Referenced by v8::internal::maglev::MaglevGraphBuilder::CalculatePredecessorCounts().
loop_end()
int v8::internal::compiler::LoopInfo::loop_end () const [inline]
Definition at line 81 of file bytecode-analysis.h.
{ return loop_end_; }
Referenced by v8::internal::maglev::MaglevGraphBuilder::CalculatePredecessorCounts().
loop_start()
int v8::internal::compiler::LoopInfo::loop_start () const [inline]
Definition at line 80 of file bytecode-analysis.h.
{ return loop_start_; }
Referenced by v8::internal::maglev::MaglevGraphBuilder::CalculatePredecessorCounts().
mark_not_innermost()
void v8::internal::compiler::LoopInfo::mark_not_innermost () [inline]
Definition at line 85 of file bytecode-analysis.h.
{ innermost_ = false; }
mark_resumable()
void v8::internal::compiler::LoopInfo::mark_resumable () [inline]
Definition at line 83 of file bytecode-analysis.h.
{ resumable_ = true; }
Referenced by v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::Analyze().
parent_offset()
int v8::internal::compiler::LoopInfo::parent_offset () const [inline]
Definition at line 79 of file bytecode-analysis.h.
{ return parent_offset_; }
Referenced by v8::internal::compiler::BytecodeGraphBuilder::AdvanceToOsrEntryAndPeelLoops(), v8::internal::compiler::BytecodeGraphBuilder::BuildLoopExitsUntilLoop(), and v8::internal::maglev::MaglevGraphBuilder::IsInsideLoop().
resumable()
bool v8::internal::compiler::LoopInfo::resumable () const [inline]
Definition at line 82 of file bytecode-analysis.h.
{ return resumable_; }
Referenced by v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::Analyze(), v8::internal::maglev::MaglevGraphBuilder::CalculatePredecessorCounts(), and v8::internal::maglev::MergePointInterpreterFrameState::NewForLoop().
resume_jump_targets()
const ZoneVector<ResumeJumpTarget>& v8::internal::compiler::LoopInfo::resume_jump_targets () const [inline]
Definition at line 91 of file bytecode-analysis.h.
                                                                  {
    return resume_jump_targets_;
  }
Referenced by v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::Analyze(), and v8::internal::compiler::BytecodeGraphBuilder::BuildLoopHeaderEnvironment().
Member Data Documentation
assignments_
BytecodeLoopAssignments v8::internal::compiler::LoopInfo::assignments_ [private]
Definition at line 108 of file bytecode-analysis.h.
innermost_
bool v8::internal::compiler::LoopInfo::innermost_ = true [private]
Definition at line 107 of file bytecode-analysis.h.
loop_end_
int v8::internal::compiler::LoopInfo::loop_end_ [private]
Definition at line 105 of file bytecode-analysis.h.
loop_start_
int v8::internal::compiler::LoopInfo::loop_start_ [private]
Definition at line 104 of file bytecode-analysis.h.
parent_offset_
int v8::internal::compiler::LoopInfo::parent_offset_ [private]
Definition at line 103 of file bytecode-analysis.h.
resumable_
bool v8::internal::compiler::LoopInfo::resumable_ = false [private]
Definition at line 106 of file bytecode-analysis.h.
resume_jump_targets_
ZoneVector<ResumeJumpTarget> v8::internal::compiler::LoopInfo::resume_jump_targets_ [private]
Definition at line 109 of file bytecode-analysis.h.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/bytecode-analysis.h