v8::internal::CodeCommentEntry Struct Reference
#include <code-comments.h>
Public Member Functions
uint32_t comment_length () const
uint32_t size () const
Public Attributes
uint32_t pc_offset
std::string comment
Detailed Description
Definition at line 29 of file code-comments.h.
Member Function Documentation
comment_length()
uint32_t v8::internal::CodeCommentEntry::comment_length () const
Definition at line 22 of file code-comments.cc.
                                                {
  return static_cast<uint32_t>(comment.size() + 1);
}
References comment.
Referenced by size().
size()
uint32_t v8::internal::CodeCommentEntry::size () const
Definition at line 26 of file code-comments.cc.
                                      {
  return kOffsetToCommentString + comment_length();
}
References comment_length(), and v8::internal::anonymous_namespace{code-comments.cc}::kOffsetToCommentString.
Referenced by v8::internal::CodeCommentsWriter::Add().
Member Data Documentation
comment
std::string v8::internal::CodeCommentEntry::comment
Definition at line 31 of file code-comments.h.
Referenced by comment_length().
pc_offset
uint32_t v8::internal::CodeCommentEntry::pc_offset
Definition at line 30 of file code-comments.h.
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/codegen/code-comments.h
/mnt/V8SourceCode/src/codegen/code-comments.cc