v8::internal::JumpOptimizationInfo Struct Reference
#include <assembler.h>
Classes
struct JumpInfo
Public Types
enum { kCollection
, kOptimization
 }
Public Member Functions
bool is_collecting () const
bool is_optimizing () const
void set_optimizing ()
bool is_optimizable () const
void set_optimizable ()
int MaxAlignInRange (int from, int to)
void Print ()
Public Attributes
enum v8::internal::JumpOptimizationInfo:: { ... } stage = kCollection
size_t hash_code = 0u
std::map< int, int > align_pos_size
int farjmp_num = 0
std::vector< JumpInfo > farjmps
bool optimizable = false
std::map< int, JumpInfo > may_optimizable_farjmp
std::map< Label *, std::vector< int > > label_farjmp_maps
Detailed Description
Definition at line 86 of file assembler.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
kCollection
kOptimization
Definition at line 145 of file assembler.h.
{ kCollection, kOptimization } stage = kCollection;
Member Function Documentation
is_collecting()
bool v8::internal::JumpOptimizationInfo::is_collecting () const [inline]
Definition at line 95 of file assembler.h.
{ return stage == kCollection; }
References kCollection, and stage.
Referenced by set_optimizable(), and v8::internal::compiler::turboshaft::Pipeline::VerifyGeneratedCodeIsIdempotent().
is_optimizable()
bool v8::internal::JumpOptimizationInfo::is_optimizable () const [inline]
Definition at line 102 of file assembler.h.
{ return optimizable; }
References optimizable.
Referenced by v8::internal::compiler::turboshaft::Pipeline::GenerateCode(), and set_optimizing().
is_optimizing()
bool v8::internal::JumpOptimizationInfo::is_optimizing () const [inline]
Definition at line 96 of file assembler.h.
{ return stage == kOptimization; }
References kOptimization, and stage.
MaxAlignInRange()
int v8::internal::JumpOptimizationInfo::MaxAlignInRange (int from, int to) [inline]
Definition at line 108 of file assembler.h.
                                        {
    int max_align = 0;
    auto it = align_pos_size.upper_bound(from);
    while (it != align_pos_size.end()) {
      if (it->first <= to) {
        max_align = std::max(max_align, it->second);
        it++;
      } else {
        break;
      }
    }
    return max_align;
  }
References align_pos_size.
Print()
void v8::internal::JumpOptimizationInfo::Print () [inline]
Definition at line 125 of file assembler.h.
               {
    std::cout << "align_pos_size:" << std::endl;
    for (auto p : align_pos_size) {
      std::cout << "{" << p.first << "," << p.second << "}"
                << " ";
    }
    std::cout << std::endl;
    std::cout << "may_optimizable_farjmp:" << std::endl;
    for (auto p : may_optimizable_farjmp) {
      const auto& jmp_info = p.second;
      printf("{postion:%d, opcode_size:%d, distance:%d, dest:%d}\n",
             jmp_info.pos, jmp_info.opcode_size, jmp_info.distance,
             jmp_info.pos + jmp_info.opcode_size + 4 + jmp_info.distance);
    }
    std::cout << std::endl;
  }
References align_pos_size, and may_optimizable_farjmp.
set_optimizable()
void v8::internal::JumpOptimizationInfo::set_optimizable () [inline]
Definition at line 103 of file assembler.h.
                         {
    DCHECK(is_collecting());
    optimizable = true;
  }
References v8::internal::DCHECK(), is_collecting(), and optimizable.
set_optimizing()
void v8::internal::JumpOptimizationInfo::set_optimizing () [inline]
Definition at line 97 of file assembler.h.
                        {
    DCHECK(is_optimizable());
    stage = kOptimization;
  }
References v8::internal::DCHECK(), is_optimizable(), kOptimization, and stage.
Referenced by v8::internal::compiler::turboshaft::Pipeline::GenerateCode().
Member Data Documentation
align_pos_size
std::map<int, int> v8::internal::JumpOptimizationInfo::align_pos_size
Definition at line 150 of file assembler.h.
Referenced by MaxAlignInRange(), and Print().
farjmp_num
int v8::internal::JumpOptimizationInfo::farjmp_num = 0
Definition at line 152 of file assembler.h.
farjmps
std::vector<JumpInfo> v8::internal::JumpOptimizationInfo::farjmps
Definition at line 155 of file assembler.h.
hash_code
size_t v8::internal::JumpOptimizationInfo::hash_code = 0u
Definition at line 147 of file assembler.h.
Referenced by v8::internal::compiler::turboshaft::Pipeline::VerifyGeneratedCodeIsIdempotent().
label_farjmp_maps
std::map<Label*, std::vector<int> > v8::internal::JumpOptimizationInfo::label_farjmp_maps
Definition at line 162 of file assembler.h.
may_optimizable_farjmp
std::map<int, JumpInfo> v8::internal::JumpOptimizationInfo::may_optimizable_farjmp
Definition at line 159 of file assembler.h.
Referenced by Print().
optimizable
bool v8::internal::JumpOptimizationInfo::optimizable = false
Definition at line 157 of file assembler.h.
Referenced by is_optimizable(), and set_optimizable().
enum { ... } v8::internal::JumpOptimizationInfo::stage
Referenced by is_collecting(), is_optimizing(), and set_optimizing().
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/codegen/assembler.h