v8::internal::wasm::CanonicalTypeIndex Struct Reference
#include <value-type.h>
Public Member Functions
bool operator== (CanonicalTypeIndex other) const
auto operator<=> (CanonicalTypeIndex other) const
Static Public Member Functions
static constexpr CanonicalTypeIndex Invalid ()
Additional Inherited Members
Detailed Description
Definition at line 82 of file value-type.h.
Member Function Documentation
Invalid()
constexpr CanonicalTypeIndex v8::internal::wasm::CanonicalTypeIndex::Invalid () [inline], [static], [constexpr]
Definition at line 94 of file value-type.h.
                                                         {
  return CanonicalTypeIndex{CanonicalTypeIndex::kInvalid};
}
References v8::internal::wasm::TypeIndex::kInvalid.
Referenced by v8::internal::wasm::TypeCanonicalizer::CanonicalizeTypeDef(), v8::internal::wasm::TypeCanonicalizer::FindCanonicalGroup(), and v8::internal::wasm::WasmModule::MaxCanonicalTypeIndex().
operator<=>()
auto v8::internal::wasm::CanonicalTypeIndex::operator<=> (CanonicalTypeIndex other) const [inline]
Definition at line 88 of file value-type.h.
                                                   {
    return index <=> other.index;
  }
References v8::internal::wasm::TypeIndex::index.
operator==()
bool v8::internal::wasm::CanonicalTypeIndex::operator== (CanonicalTypeIndex other) const [inline]
Definition at line 85 of file value-type.h.
                                                  {
    return index == other.index;
  }
References v8::internal::wasm::TypeIndex::index.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/wasm/value-type.h