v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOp Struct Reference
#include <operations.h>
Public Types
enum class JSPrimitiveKind : uint8_t {
kBigInt
, kBoolean
, kHeapNumber
, kHeapNumberOrUndefined
,
kNumber
, kSmi
, kString
 }
enum class InputInterpretation : uint8_t {
kSigned
, kUnsigned
, kDouble
, kDoubleOrHole
,
kDoubleOrUndefined
, kDoubleOrUndefinedOrHole
, kCharCode
, kCodePoint
 }
Public Member Functions
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
V< Untagged > input () const
ConvertUntaggedToJSPrimitiveOp (V< Untagged > input, JSPrimitiveKind kind, RegisterRepresentation input_rep, InputInterpretation input_interpretation, CheckForMinusZeroMode minus_zero_mode)
void Validate (const Graph &graph) const
auto options () const
Public Attributes
JSPrimitiveKind kind
RegisterRepresentation input_rep
InputInterpretation input_interpretation
CheckForMinusZeroMode minus_zero_mode
Static Public Attributes
static constexpr OpEffects effects = OpEffects().CanAllocateWithoutIdentity()
Additional Inherited Members
Detailed Description
Definition at line 4768 of file operations.h.
Member Enumeration Documentation
InputInterpretation
enum v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOp::InputInterpretation : uint8_t [strong]
Enumerator
kSigned
kUnsigned
kDouble
kDoubleOrHole
kDoubleOrUndefined
kDoubleOrUndefinedOrHole
kCharCode
kCodePoint
Definition at line 4779 of file operations.h.
                                 : uint8_t {
    kSigned,
    kUnsigned,
    kDouble,
    kDoubleOrHole,
    kDoubleOrUndefined,
    kDoubleOrUndefinedOrHole,
    kCharCode,
    kCodePoint,
  };
JSPrimitiveKind
enum v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOp::JSPrimitiveKind : uint8_t [strong]
Enumerator
kBigInt
kBoolean
kHeapNumber
kHeapNumberOrUndefined
kNumber
kSmi
kString
Definition at line 4770 of file operations.h.
                             : uint8_t {
    kBigInt,
    kBoolean,
    kHeapNumber,
    kHeapNumberOrUndefined,
    kNumber,
    kSmi,
    kString,
  };
Constructor & Destructor Documentation
ConvertUntaggedToJSPrimitiveOp()
v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOp::ConvertUntaggedToJSPrimitiveOp (V< Untagged > input, JSPrimitiveKind kind, RegisterRepresentation input_rep, InputInterpretation input_interpretation, CheckForMinusZeroMode minus_zero_mode) [inline]
Definition at line 4807 of file operations.h.
      : Base(input),
        kind(kind),
        input_rep(input_rep),
        input_interpretation(input_interpretation),
        minus_zero_mode(minus_zero_mode) {
    DCHECK_EQ(input_rep == RegisterRepresentation::Float64(),
              (input_interpretation ==
               any_of(InputInterpretation::kDouble,
                      InputInterpretation::kDoubleOrHole,
                      InputInterpretation::kDoubleOrUndefined,
                      InputInterpretation::kDoubleOrUndefinedOrHole)));
  }
References v8::base::any_of(), DCHECK_EQ, and v8::internal::compiler::turboshaft::RegisterRepresentation::Float64().
Member Function Documentation
input()
V<Untagged> v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOp::input () const [inline]
Definition at line 4805 of file operations.h.
{ return Base::input<Untagged>(0); }
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOp::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 4800 of file operations.h.
                                                              {
    return InputsRepFactory::SingleRep(input_rep);
  }
References v8::internal::compiler::turboshaft::InputsRepFactory::SingleRep().
options()
auto v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOp::options () const [inline]
Definition at line 4861 of file operations.h.
                       {
    return std::tuple{kind, input_rep, input_interpretation, minus_zero_mode};
  }
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOp::outputs_rep () const [inline]
Definition at line 4796 of file operations.h.
                                                               {
    return RepVector<RegisterRepresentation::Tagged()>();
  }
Validate()
void v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOp::Validate (const Graph & graph) const [inline]
Definition at line 4824 of file operations.h.
                                          {
    switch (kind) {
      case JSPrimitiveKind::kBigInt:
        DCHECK_EQ(input_rep, RegisterRepresentation::Word64());
        DCHECK_EQ(minus_zero_mode,
                  CheckForMinusZeroMode::kDontCheckForMinusZero);
        break;
      case JSPrimitiveKind::kBoolean:
        DCHECK_EQ(input_rep, RegisterRepresentation::Word32());
        DCHECK_EQ(minus_zero_mode,
                  CheckForMinusZeroMode::kDontCheckForMinusZero);
        break;
      case JSPrimitiveKind::kNumber:
      case JSPrimitiveKind::kHeapNumber:
        DCHECK_IMPLIES(
            minus_zero_mode == CheckForMinusZeroMode::kCheckForMinusZero,
            input_rep == RegisterRepresentation::Float64());
        break;
      case JSPrimitiveKind::kHeapNumberOrUndefined:
        DCHECK_IMPLIES(
            minus_zero_mode == CheckForMinusZeroMode::kDontCheckForMinusZero,
            input_rep == RegisterRepresentation::Float64());
        break;
      case JSPrimitiveKind::kSmi:
        DCHECK_EQ(input_rep, WordRepresentation::Word32());
        DCHECK_EQ(minus_zero_mode,
                  CheckForMinusZeroMode::kDontCheckForMinusZero);
        break;
      case JSPrimitiveKind::kString:
        DCHECK_EQ(input_rep, WordRepresentation::Word32());
        DCHECK_EQ(input_interpretation,
                  any_of(InputInterpretation::kCharCode,
                         InputInterpretation::kCodePoint));
        break;
    }
  }
References v8::base::any_of(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::compiler::turboshaft::RegisterRepresentation::Float64(), v8::internal::compiler::kCheckForMinusZero, v8::internal::compiler::kDontCheckForMinusZero, v8::internal::compiler::kSmi, v8::internal::compiler::turboshaft::RegisterRepresentation::Word32(), v8::internal::compiler::turboshaft::WordRepresentation::Word32(), and v8::internal::compiler::turboshaft::RegisterRepresentation::Word64().
Member Data Documentation
effects
constexpr OpEffects v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOp::effects = OpEffects().CanAllocateWithoutIdentity() [static], [constexpr]
Definition at line 4795 of file operations.h.
input_interpretation
InputInterpretation v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOp::input_interpretation
Definition at line 4791 of file operations.h.
input_rep
RegisterRepresentation v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOp::input_rep
Definition at line 4790 of file operations.h.
kind
JSPrimitiveKind v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOp::kind
Definition at line 4789 of file operations.h.
minus_zero_mode
CheckForMinusZeroMode v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOp::minus_zero_mode
Definition at line 4792 of file operations.h.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h