v8::internal::compiler::turboshaft::StoreDataViewElementOp Struct Reference
#include <operations.h>
Public Member Functions
base::Vector< const RegisterRepresentation > outputs_rep () const
base::Vector< const MaybeRegisterRepresentation > inputs_rep (ZoneVector< MaybeRegisterRepresentation > &storage) const
OpIndex object () const
OpIndex storage () const
OpIndex index () const
OpIndex value () const
OpIndex is_little_endian () const
StoreDataViewElementOp (OpIndex object, OpIndex storage, OpIndex index, OpIndex value, OpIndex is_little_endian, ExternalArrayType element_type)
auto options () const
Public Attributes
ExternalArrayType element_type
Static Public Attributes
static constexpr OpEffects effects
Additional Inherited Members
Detailed Description
Definition at line 6023 of file operations.h.
Constructor & Destructor Documentation
StoreDataViewElementOp()
v8::internal::compiler::turboshaft::StoreDataViewElementOp::StoreDataViewElementOp (OpIndex object, OpIndex storage, OpIndex index, OpIndex value, OpIndex is_little_endian, ExternalArrayType element_type) [inline]
Definition at line 6052 of file operations.h.
      : Base(object, storage, index, value, is_little_endian),
        element_type(element_type) {}
Member Function Documentation
index()
OpIndex v8::internal::compiler::turboshaft::StoreDataViewElementOp::index () const [inline]
Definition at line 6048 of file operations.h.
{ return Base::input(2); }
inputs_rep()
base::Vector<const MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::StoreDataViewElementOp::inputs_rep (ZoneVector< MaybeRegisterRepresentation > & storage) const [inline]
Definition at line 6036 of file operations.h.
                                                              {
    return InitVectorOf(
        storage,
        {RegisterRepresentation::Tagged(), RegisterRepresentation::Tagged(),
         RegisterRepresentation::WordPtr(),
         RegisterRepresentationForArrayType(element_type),
         RegisterRepresentation::Word32()});
  }
References v8::internal::compiler::turboshaft::InitVectorOf(), v8::internal::compiler::turboshaft::RegisterRepresentationForArrayType(), v8::internal::compiler::turboshaft::RegisterRepresentation::Tagged(), v8::internal::compiler::turboshaft::RegisterRepresentation::Word32(), and v8::internal::compiler::turboshaft::RegisterRepresentation::WordPtr().
is_little_endian()
OpIndex v8::internal::compiler::turboshaft::StoreDataViewElementOp::is_little_endian () const [inline]
Definition at line 6050 of file operations.h.
{ return Base::input(4); }
object()
OpIndex v8::internal::compiler::turboshaft::StoreDataViewElementOp::object () const [inline]
Definition at line 6046 of file operations.h.
{ return Base::input(0); }
options()
auto v8::internal::compiler::turboshaft::StoreDataViewElementOp::options () const [inline]
Definition at line 6059 of file operations.h.
{ return std::tuple{element_type}; }
outputs_rep()
base::Vector<const RegisterRepresentation> v8::internal::compiler::turboshaft::StoreDataViewElementOp::outputs_rep () const [inline]
Definition at line 6034 of file operations.h.
{ return {}; }
storage()
OpIndex v8::internal::compiler::turboshaft::StoreDataViewElementOp::storage () const [inline]
Definition at line 6047 of file operations.h.
{ return Base::input(1); }
value()
OpIndex v8::internal::compiler::turboshaft::StoreDataViewElementOp::value () const [inline]
Definition at line 6049 of file operations.h.
{ return Base::input(3); }
Member Data Documentation
effects
constexpr OpEffects v8::internal::compiler::turboshaft::StoreDataViewElementOp::effects [static], [constexpr]
Initial value:
=
      OpEffects()
          
          .CanReadMemory()
          .CanWriteMemory()
          
          .CanDependOnChecks()
Definition at line 6027 of file operations.h.
element_type
ExternalArrayType v8::internal::compiler::turboshaft::StoreDataViewElementOp::element_type
Definition at line 6025 of file operations.h.
The documentation for this struct was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h