cppgc::internal::StrongCrossThreadPersistentPolicy Struct Reference
#include <pointer-policies.h>
Public Types
using IsStrongPersistent = std::true_type
Static Public Member Functions
static CrossThreadPersistentRegion & GetPersistentRegion (const void *object)
Detailed Description
Definition at line 250 of file pointer-policies.h.
Member Typedef Documentation
IsStrongPersistent
using cppgc::internal::StrongCrossThreadPersistentPolicy::IsStrongPersistent = std::true_type
Definition at line 251 of file pointer-policies.h.
Member Function Documentation
GetPersistentRegion()
CrossThreadPersistentRegion & cppgc::internal::StrongCrossThreadPersistentPolicy::GetPersistentRegion (const void * object) [static]
Definition at line 120 of file pointer-policies.cc.
                                                                         {
  return BasePage::FromPayload(object)
      ->heap()
      .GetStrongCrossThreadPersistentRegion();
}
References cppgc::internal::BasePage::FromPayload(), cppgc::internal::HeapBase::GetStrongCrossThreadPersistentRegion(), and cppgc::internal::BasePage::heap().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/include/cppgc/internal/pointer-policies.h
/mnt/V8SourceCode/src/heap/cppgc/pointer-policies.cc