v8::internal::FPUControlRegister Struct Reference
#include <register-loong64.h>
Public Member Functions
bool is_valid () const
bool is (FPUControlRegister creg) const
int code () const
int bit () const
void setcode (int f)
bool is_valid () const
bool is (FPUControlRegister creg) const
int code () const
int bit () const
void setcode (int f)
Public Attributes
int reg_code
Detailed Description
Definition at line 181 of file register-loong64.h.
Member Function Documentation
bit() [1/2]
int v8::internal::FPUControlRegister::bit () const [inline]
Definition at line 188 of file register-loong64.h.
                  {
    DCHECK(is_valid());
    return 1 << reg_code;
  }
References v8::internal::DCHECK(), is_valid(), and reg_code.
bit() [2/2]
int v8::internal::FPUControlRegister::bit () const [inline]
Definition at line 247 of file register-mips64.h.
                  {
    DCHECK(is_valid());
    return 1 << reg_code;
  }
References v8::internal::DCHECK(), is_valid(), and reg_code.
code() [1/2]
int v8::internal::FPUControlRegister::code () const [inline]
Definition at line 184 of file register-loong64.h.
                   {
    DCHECK(is_valid());
    return reg_code;
  }
References v8::internal::DCHECK(), is_valid(), and reg_code.
code() [2/2]
int v8::internal::FPUControlRegister::code () const [inline]
Definition at line 243 of file register-mips64.h.
                   {
    DCHECK(is_valid());
    return reg_code;
  }
References v8::internal::DCHECK(), is_valid(), and reg_code.
is() [1/2]
bool v8::internal::FPUControlRegister::is (FPUControlRegister creg) const [inline]
Definition at line 183 of file register-loong64.h.
{ return reg_code == creg.reg_code; }
References reg_code.
is() [2/2]
bool v8::internal::FPUControlRegister::is (FPUControlRegister creg) const [inline]
Definition at line 242 of file register-mips64.h.
{ return reg_code == creg.reg_code; }
References reg_code.
is_valid() [1/2]
bool v8::internal::FPUControlRegister::is_valid () const [inline]
Definition at line 182 of file register-loong64.h.
{ return (reg_code >> 2) == 0; }
References reg_code.
Referenced by bit(), code(), and setcode().
is_valid() [2/2]
bool v8::internal::FPUControlRegister::is_valid () const [inline]
Definition at line 241 of file register-mips64.h.
{ return reg_code == kFCSRRegister; }
References v8::internal::kFCSRRegister, and reg_code.
setcode() [1/2]
void v8::internal::FPUControlRegister::setcode (int f) [inline]
Definition at line 192 of file register-loong64.h.
                      {
    reg_code = f;
    DCHECK(is_valid());
  }
References v8::internal::DCHECK(), is_valid(), and reg_code.
setcode() [2/2]
void v8::internal::FPUControlRegister::setcode (int f) [inline]
Definition at line 251 of file register-mips64.h.
                      {
    reg_code = f;
    DCHECK(is_valid());
  }
References v8::internal::DCHECK(), is_valid(), and reg_code.
Member Data Documentation
reg_code
int v8::internal::FPUControlRegister::reg_code
Definition at line 197 of file register-loong64.h.
Referenced by bit(), code(), is(), is_valid(), and setcode().
The documentation for this struct was generated from the following files:
/mnt/V8SourceCode/src/codegen/loong64/register-loong64.h
/mnt/V8SourceCode/src/codegen/mips64/register-mips64.h