name: Create

on:
  workflow_dispatch:
    inputs:
      V8Version:
        description: Version or Commit
        type: string
        required: true

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Download doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Download V8 Source Code
        run: |
          mkdir /tmp/V8SourceCode
          git clone --depth 1 https://github.com/v8/v8 /tmp/V8SourceCode

      - name: Create V8Docs
        run: |
          mkdir /tmp/V8Docs
          doxygen Doxyfile

      - name: Commit and Push V8Docs
        run: |
          mkdir -p $GITHUB_WORKSPACE/V8Docs
          cp -r /tmp/V8Docs/* $GITHUB_WORKSPACE/V8Docs/

          git config --global user.name '7resp4ss'
          git config --global user.email '81899344+7resp4ss@users.noreply.github.com'

          git add V8Docs/
          git commit -m "Add V8Docs for V8 version ${{ inputs.V8Version }}"

          # Use PAT for authentication
          git push https://${{ secrets.REPO_ACCESS_TOKEN }}@github.com/7resp4ss/DoxygenV8.git HEAD:${{ github.ref_name }}
